### ISSUE TITLE
Probelm z api do autoryzacji

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#100]
Stukam pod adres:
https://api.allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=[cod]&api-key=[klucz]&redirect_uri=[url]
dodaje nagłówek 
Authorization: Basic [base64]
i otrzymuję odpowiedź:

> {"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}

przy wejściu na ten sam adres bez aliasu api poprazez przeglądarkę, po wpisaniu danych kluczy apki do zalogowania otrzymuję poprawną odpowiedź.

**Comment by dtarczynski** [comment]
Stukaj https://allegro.pl.allegrosandbox.pl/auth/oauth/

**Comment by mapsi-fixi** [comment]
W jaki sposób nie wyślę danych autoryzacyjnych to 403 zwraca zawszez adresu https://allegro.pl.allegrosandbox.pl/auth/oauth/

**Comment by kormichu** [comment]
@mapsi-fixi Spróbuj przesłać jeszcze nagłówek Api-Key

**Comment by TomekKaczmarek** [comment]
@mapsi-fixi Tak wygląda poprawny request

https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code=[code]&api-key=[apikey]&redirect_uri=[url]

Pamiętaj, że code jest ważny 10 sekund i możesz go użyć tylko raz.
