### ISSUE TITLE
/offer/{offerId}

### ISSUE THREAD

**Issue by Stanislav93** [allegro/allegro-api#1000]
Dzień dobry.
Jest jeszcze pytanie.

Jak za pomocą rest api, uzyskać dane dotyczące konkretnego produktu?

GET
/offer/{offerId}
ta metoda zwraca błąd zapytania: 
 $data = [];
$data["offerId"] = 7253124971;
$r = $AllegroApi->offers->get($data);

Otrzymywać:
{"{"errors":[{"code":"No Significant Query Param Exception","message":"Lack of significant query parameter. At least one of: categoryId (other than root categoryidentifier), category Alias (other than /), phrase, seller Id, seller Login must be provided.","details":null,"path":null,"userMessage":"Błąd komunikacji. Sprawdź czy używasz najnowszej wersji."}]

Czy informacje Masz w całości do zawężenia?

Jeśli użyć opcji:
$data["phrase"] = 7253124971;

Otrzymywać:
{"{"offers":[],"pageToken":{"next":null,"previous":null},"count":0,"fallback Mode":{"mode":"EMPTY"},"sponsoredOffers":[],"searchScenarioName":"baseline-cl-n-dict-uni-1-2-1219"}

Bardzo potrzebuję Twojej pomocy.
Pozdrawiam Igor.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem co dokładnie chcesz zrobić, zasobem GET /sale/offers/{offerId} pobierzesz tylko oferty jakie wystawiłeś jako sprzedawca, którego token posiadasz. Przykład wywołania znajdziesz [tutaj](https://developer.allegro.pl/sale/#similar-offer).

**Comment by grzegorzjj** [comment]
Koledze zapewne chodzi o to, aby za pomocą REST-API zrobić to, co robi doGetItemsInfo w WebApi.
Nie da się. Listę publiczną aukcji ( nie Twoje wystawione ) pobierasz za pomocą offers/listing z parametrami filtrującymi ( REST API ), a szczegóły oferty za pomocą doGetItemsInfo , czyli WebApi.
To taki okres przejściowy, w którym jest trochę tego i trochę tego.

**Comment by PawelTaberski** [comment]
Teraz rozumiem to dokładnie, tak jak napisałeś informacje o swoich ofertach przez REST API pobierzesz przy pomocy zasobu /sale/offers a o innych ofertach nie wystawionych przez danego sprzedawcę przy pomocy /offers/listing.
