### ISSUE TITLE
POST/https://api.allegro.pl/sale/shipping-rates - stworzenie więcej cenników w jednym requescie

### ISSUE THREAD

**Issue by SunkovyChlebiczek** [allegro/allegro-api#10009]
Dzień dobry,
czy jest możliwe stworzyć więcej cenników za pomocą jednego requestu POST/https://api.allegro.pl/sale/shipping-rates? W żadnej kompozycji nam się nie udaje. Jeźeli tak, to w jakim formatu? Dziękuję.

**Comment by AureliuszBrussy** [comment]
Za pomocą [POST /sale/shipping-rates](https://developer.allegro.pl/documentation#operation/createShippingRatesSetUsingPOST) utworzysz tylko jeden cennik dostawy na raz (w jednym cenniku może znaleźć się wiele metod dostawy). Jeżeli chcesz utworzyć kolejny, musisz powtórzyć request.

**Comment by SunkovyChlebiczek** [comment]
Rozumiem. Dzięki za info.
