### ISSUE TITLE
Problem z autoryzacja device flow. Nie dziala

### ISSUE THREAD

**Issue by michalkrokezzz** [allegro/allegro-api#10011]
Mam problem z autoryzacja device flow. Pomimo podania odpowiednich kluczy jak puszczam curl i przez skrypt php to nie dziala. Moje konto michalrokezzz88. Korzystam z sandbox. Nie dostaje w odpowiedzi trace-id tylko odpowiedz unauthorized. Nie moge uzyskac device code

**Comment by AureliuszBrussy** [comment]
Czy spojrzałeś na [przykłady z poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika)? Działają one prawidłowo, o ile właściwie uzupełnisz brakujące dane. Upewnij się też, czy na pewno zarejestrowałeś odpowiedni typ aplikacji (device) w Developer Apps ([prod](https://apps.developer.allegro.pl/) lub [test](https://apps.developer.allegro.pl.allegrosandbox.pl/)).

**Comment by michalkrokezzz** [comment]
@AureliuszBrussy  curl -X POST \
  'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \ Puszczalem ten request i pomimo wprowadzenia poprawnych danych zwracalo mi unauthorized
curl -vX POST \
  'https://allegro.pl/auth/oauth/device?client_id={client_id}' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded'
dokladnie taki format puscilem (oczywiscie podstawilem swoje dane). Aplikacja mam oznaczona jako: 

Aplikacja działa w środowisku bez dostępu do przeglądarki lub klawiatury (np. aplikacja konsolowa lub na urządzeniu typu telewizor)
Aplikacja otrzyma OAuth grant-type: device_code

**Comment by michalkrokezzz** [comment]
verbose z curl *   Trying 185.31.27.160:443...
* Connected to allegro.pl (185.31.27.160) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=PL; ST=Wielkopolskie; L=Pozna\U0144; O=Allegro sp. z o.o.; CN=*.allegro.pl
*  start date: Aug 20 00:00:00 2024 GMT
*  expire date: Sep 10 23:59:59 2025 GMT
*  subjectAltName: host "allegro.pl" matched cert's "allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x55ca0fb1aeb0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /auth/oauth/device?client_id=client_id HTTP/2
> Host: allegro.pl
> user-agent: curl/7.81.0
> accept: */*
> authorization: Basic {base64(client_id:client_secret)}
> content-type: application/x-www-form-urlencoded
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 401 
< date: Wed, 02 Oct 2024 07:59:40 GMT
< content-type: application/json
< set-cookie: wdctx=v5.72aAfJUsUExEh4n1KgHoJ7bdElK_gfO2RqhZl0Uau6xLNnAaRZdUsXMjcBW1x7HBRu4l6vBNv79jxqihLsXMrs70UiNEPSGen24IdxD6GFHeoX1MZOXinbOP2NK5g0eHgwp9a1NfFONKDHE-A010MrPCL6xatRuL_pw3gQdTzXBs92nDRjnZF722QeEN9v2f-YfwQuPxgg66rc5Byxp76yDXT9MN_hmWs-Fa2et4cq5y.QpdxlUKsT8mTCxJjFR57pg.mKNS1HpnAEc; Max-Age=2592000; Domain=.allegro.pl; Path=/; Secure
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< pragma: no-cache
< www-authenticate: Basic realm="Allegro"
< vary: Accept-Encoding
< age: 0
< content-security-policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp;
< x-content-type-options: nosniff
< grace: none
< x-xss-protection: 1; report=/seclog/xss
< x-frame-options: SAMEORIGIN
< strict-transport-security: max-age=15552000
< set-cookie: _cmuid=6a410878-6973-4778-a16a-17eace220a10; Expires=Thu, 06 Nov 2025 07:59:40 GMT; Path=/; Domain=.allegro.pl; Secure
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host allegro.pl left intact
{"error":"Unauthorized","error_description":"Unauthorized"}

**Comment by AureliuszBrussy** [comment]
Niestety, ale trudno mi będzie podpowiedzieć - nie mamy żadnych problemów czy awarii, cały proces działa prawidłowo. Upewnij się, czy query parametry są przekazane w całości i że korzystasz z Client ID i Client Secret dla właściwego środowiska. 

Sprawdziłem też [przykłady kodu z poradnika](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika) - działają one prawidłowo.

**Comment by michalkrokezzz** [comment]
@AureliuszBrussy tu udalo mi sie naprawic problem. allegro.pl zamienilem na sandbox i poszlo. Natomiast mam inny problem. Case mam taki ze bede chcial autoryzowac sie z poziomu CLI. Raz w nocy bedzie odpalana komenda i bede chcial uzyskac token na poczatku. Problem jest tego typu ze aby uzyska token nawet jak wybralem rodzaj aplikacji 
(Aplikacja działa w środowisku bez dostępu do przeglądarki lub klawiatury (np. aplikacja konsolowa lub na urządzeniu typu telewizor - Aplikacja otrzyma OAuth grant-type: device_code) po odpaleniu tego kodu z przykladowego waszego skryptu php pojawia mi sie info aby przejsc na link "Użytkowniku, otwórz ten adres w przeglądarce: "
https://allegro.pl.allegrosandbox.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=m9m9n15cd"
chcialbym ten krok pominac w swoim kodzie gdyz bede robil autoryzacje z poziomu komendy CLI (z konsoli). Czy moge ten krok pominac aby uzyskac access_token?

**Comment by AureliuszBrussy** [comment]
Tak, możesz pominąć interakcję użytkownika. Wraz z access tokenem otrzymujesz refresh token, który służy do pozyskania kolejnej pary access i refresh token. W ten sposób pomijasz konieczność kolejnej interakcji użytkownika. Więcej o tym przeczytasz w sekcji [Przedłużenie ważności tokena](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by AureliuszBrussy** [comment]
@michalkrokezzz tak, zgadza się. Nie da się pominąć pierwszej interakcji użytkownika - musi on wyrazić zgodę za działanie aplikacji w jego imieniu, więc ten proces jest niepomijalny.

**Comment by michalkrokezzz** [comment]
Issue solved
