### ISSUE TITLE
[REST] statusy: INACTIVE / ENDED / END / CLOSED - to może FINISHED / TERMINATED ??

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1001]
:bulb: **Sugestia**
Ludzie, kto tam tak szaleje przy semantyce i składni ? Gdzie nie zajrzeć to inaczej, a jeszcze co chwilę błędów co niemiara... Zwyczajnie przesuńcie termin wygaszania WebAPI o jakieś pół roku, ogarnijcie to wszystko i nanieście POPRAWNIE do Swagger'a - wtedy zobaczymy czy to się nadaje do integracji. STOP !!

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem Twoją sugestię obecnie w REST oferta może mieć status ACTIVE (aktywna widoczna na serwisie); ENDED (zakończona) no i INACTIVE (draft). W metodzie PUT /sale/offer-publication-commands/{commandId} możesz użyć END, aby zakończyć ofertę i ACTIVATE aby ją  opublikować.
Co do czasu wygaszenia WebAPI jest to proces długotrwały i na pewno będzie to następowało stopniowo o czym będziemy informować.

**Comment by FromAnyHole** [comment]
Nie jest tak pięknie... Statusy zwracane dla konkretnych przedmiotów, potrafią się zwyczajnie mieszać - powinno być niby ENDED (po zamknięciu oferty sprzedaży ze stanem "niezerowym" ilości), a czasem jest wtedy INACTIVE (ponownie status draft'a). Z kolei dla niektórych zasobów przewidziano wartość CLOSED - na potrzebę filtrowania zakończonych, po co więc raz jest ENDED a innym razem CLOSED ?? Powinna być jednoznaczna semantyka na całym REST.

**Comment by FromAnyHole** [comment]
Ok, zanim pójdą jakiekolwiek zmiany, to zróbcie może specjalny wątek na temat nomenklatury / semantyki / składni - niech się też inni wypowiedzą, ja nie zjadłem wszystkich rozumów, zjadłem tylko trochę ;-)

**Comment by PawelTaberski** [comment]
Oczywiście jeśli zdecydujemy się na wprowadzanie zmian, to założenie takiego wątku jest jak najbardziej dobrym pomysłem, aby objąć jak najwięcej przypadków. Tymczasem życzę Wesołych Świąt :-)
