### ISSUE TITLE
Odblokowanie sprzedaży na Sandbox

### ISSUE THREAD

**Issue by ruzampl** [allegro/allegro-api#10019]
Proszę o zatwierdzenie weryfikacji konta/odblokowanie sprzedaży dla konta: ruzampl

Dziękuję i pozdrawiam

**Comment by AureliuszBrussy** [comment]
@ruzampl aktywowałem Twoje konto.

**Comment by ruzampl** [comment]
Hmm. Weryfikacja jest zaliczona, ale nadal jest blokada sprzedaży: You do not have the permissions required to list an offer (sales suspended). Pay the arrears in Settlements with Allegro;

> Zablokowana sprzedaż
Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub skontaktuj się z nami.

**Comment by AureliuszBrussy** [comment]
@ruzampl przepraszam, usunąłem blokadę.

**Comment by ruzampl** [comment]
Dzięki. Potwierdzam, blokada zdjęta.
