### ISSUE TITLE
Niepoprawny email w bid

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#1002]
Występuje problem:
 - [x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Metoda *doGetPostBuyData* dla aukcji *5374349797* zawraca mail o niepoprawnej strukturze. Ten mail to m#####1@onet.pl_guest_inactive
Prosiłbym o informację czy powinno się dać użyć takiego maila przy zakupach czy może został on zmieniony w dalszym procesowaniu? 
Nie jest on poprawny więc nie mogę za bardzo nic z nim zrobić.

**Comment by manhunto** [comment]
> Dodanie takiej końcówki jest spowodowane tym, że akurat ten użytkownik ma więcej niż jedno konto z takim adresem e-mail, wystarczy w takim wypadku, że zignorujesz/usuniesz tą końcówkę.

Czy są jakieś inne końcówki które powinienem wycinać czy to jednostkowy przypadek?

**Comment by PawelTaberski** [comment]
To wyjątkowa sytuacja i nie powinny się pojawiać inne końcówki przy adresach.

**Comment by manhunto** [comment]
@PawelTaberski dziękuje za informacje
