### ISSUE TITLE
Próba aktualizacji ceny jest odrzucona błędem `prices.price.currency.incorrectBaseCurrency`

### ISSUE THREAD

**Issue by medikoo** [allegro/allegro-api#10036]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbuję zaktualizować ofertę, pod `PATCH https://api.allegro.pl/sale/product-offers/<id oferty` wysyłam payload jak poniżej:

```javascript
{ sellingMode: { price: { amount: 233, currency: 'PLN' } },
  additionalMarketplaces:
   { 'allegro-cz': { sellingMode: { price: { amount: 54.1, currency: 'EUR' } }, publication: { state: 'APPROVED' } },
     'allegro-sk': { sellingMode: { price: { amount: 1369, currency: 'CZK' } }, publication: { state: 'APPROVED' } },
     'allegro-hu': { sellingMode: { price: { amount: 21680, currency: 'HUF' } }, publication: { state: 'APPROVED' } } },
  publication:
   { status: 'ACTIVE',
     marketplaces:
      { base: { id: 'allegro-pl' },
        additional: [ { id: 'allegro-cz' }, { id: 'allegro-sk' }, { id: 'allegro-hu' } } } }
```

Zwracany jest błąd:

```
{
  "code":"VALIDATION_FAILED",
  "message":"prices.price.currency.incorrectBaseCurrency",
  "details":null,
  "path":"prices[0].price.currency",
  "userMessage":"Waluta jest niepoprawna dla podanego rynku.","metadata":{}
```

Co dokładnie jest nie tak? Waluty na pewno podawane są poprawne (podany `path` w treści błędu nie wydaje się adekwatny)

Trace Id: `2cfefe4342a4a12c`

**Comment by MaciejFrackowiak** [comment]
Waluty niestety są źle przypisane - dla allegro.cz podajesz EUR, dla allegro.sk podajesz CZK.

**Comment by medikoo** [comment]
Ah 🤦 faktycznie
