### ISSUE TITLE
kampanie Allegro 

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#10043]

**Comment by Vitalka13** [comment]
Dzień dobry!

Chcielibyśmy przetestować kilka kampanii, i potrzebujemy Państwa pomocy.
Allegro Days,  Allegro Days Smart! only,  AlleObniżka. Czy mogą Państwo włączyć tę kampanii na sandboxie? Oraz mam pytanie, czy jest możliwość zrobić nasze konto  Test_3PRozetka SMART, aby móc testować kampanii?

**Comment by Vitalka13** [comment]
A dla klienta  Client:106045932 na sandboxie można włączyć smart bez numeru telefonu?

![uuu](https://github.com/user-attachments/assets/ffcc4ec9-5a70-4bf9-a3f4-ea5b2f499095)

**Comment by MaciejFrackowiak** [comment]
Wystarczy podać dowolny numer, ponieważ na Sandox i tak nie wysyłamy SMS - kod do potwierdzenia operacji to 123456.
