### ISSUE TITLE
Mam problem z dodaniem przesyłki przez AP Allegro Automaty Paczkowe DPD Słowacja

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#10045]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Mam problem z dodaniem przesyłki przez API:

Metoda dostawy: 0e523d1e-1e43-4825-8d10-9cbc2e691bef Allegro Automaty Paczkowe DPD Słowacja
Zamówienie: bef7d070-84ba-11ef-8b51-35d1c0477846

Z widoku WZA w panelu allegro mam taki komunikat:
Pole "Dane nadawcy - adres" zawiera błędne dane: Niewspierany kraj nadania

W API mam komunikat:  Waluta nie jest wspierana przez metodę dostawy
Chcę wysłać z Polski. Kwota dla ubezpieczenia podana w PLN.

W czym jest problem ?

**Comment by AureliuszBrussy** [comment]
Czy jesteś w stanie podać trace-id lub commandId próby utworzenia przesyłki? Sprawdzę, co tam się stało.

**Comment by manoos** [comment]
Proszę: c8ea61ea-41d5-49d1-ac04-f4eabe1fde34

**Comment by AureliuszBrussy** [comment]
Zwróć uwagę, jaką walutę zwracamy po pobraniu informacji o danej usłudze dostawy ([GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation#operation/getDeliveryServices)). 

W odpowiedzi otrzymasz: 

```
            "insurance": {
                "limit": 500000,
                "currency": "CZK"
            }
```

**Comment by manoos** [comment]
Ok, rozumie,
