### ISSUE TITLE
Stare Allegro WebApi

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1004]
Mamy kilku dużych klientów na Allegro. I na 100% nie zdążymy do kwietnia przepisać obecnych systemów na nowe api Allegro. Mam nadzieje, że nie wyłączycie niektórych metod w kwietniu. Podejrzewam, że takich firm jest więcej.

**Comment by PawelTaberski** [comment]
Zgodnie z [wcześniejszą zapowiedzią](https://allegro.pl/webapi/news.php/page,2#news_100632) w kwietniu 2019 usuniemy metodę doGetItemsList. Ponadto będziemy niedługo oznaczać większą liczbę metod jako deprecated. W nowym roku zaktualizujemy komunikat odnośnie dalszych planów na temat WebAPI prosiłbym poczekać na więcej szczegółów, jeśli wtedy będzie miał Pan jakieś wątpliwości/pytania postaramy się na nie odpowiedzieć.
