### ISSUE TITLE
Ciche zmiany w limitach ofert?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#10044]
Błąd 1
> You cannot list another offer with this product. In this category, you can link a maximum of 5 offers to one product. Find another product in the Catalog or add a new one.

Błąd 2
> The item you want to list is already on the list of your active offers. Pursuant to the Allegro Terms & Conditions You cannot list more than two offers related to the same item with the “New“ condition parameter within the same subcategory, regardless of the number of accounts you have. Listing the same product in a single category affects the transparency of the search results, which has an impact on the purchase decisions made by customers. Listing the offer is not possible.

Czy wprowadzaliście ostatnio jakieś ciche zmiany w związku z limitami? Dlaczego są 2 rodzaje błędów dot. limitów? Ostatnio klient skarżył się, że nie wznawia mu aukcji tak jak wcześniej.

---
Wpis z 30 września 2024

https://help.allegro.com/sell/pl/a/nowosci-i-zmiany-dla-sprzedajacych-w-najblizszych-miesiacach-PgM60zwVwtB

> Kiedy: 21 października 2024

![image](https://github.com/user-attachments/assets/75fed878-eaef-44a2-b1d6-aec6e55f4c72)

Czy to oznacza, że już nie będzie można mieć 5 ofert dla tego samego produktu w niektórych kategoriach?

Jednak 21 października jeszcze nie ma...

**Comment by AureliuszBrussy** [comment]
Komunikat nr 1 dotyczy ofert powiązanych z tym samym produktem - jednak mogą się one różnić pozostałymi parametrami, opisem, tytułem czy miniaturką.

Komunikat nr 2 dotyczy powielonych ofert - w takim przypadku wykryliśmy, że oferta nie dość, że jest połączona z tym samym produktem, to jeszcze parametry identyfikujące i wariantujące mają dokładnie taką samą wartość. 

Ten drugi limit również funkcjonuje już od dłuższego czasu - możesz o nim przeczytać więcej [np. tutaj](https://help.allegro.com/sell/pl/a/jakich-przedmiotow-nie-mozna-wystawiac-na-allegro-a-jakie-mozna-wystawiac-warunkowo-8dvEzZMRkT8?marketplaceId=allegro-pl#powielone-oferty).

Nowa zamiana regulaminowa przez Ciebie przytoczona to tylko doprecyzowanie powiązane z komunikatem nr 2. Chodzi o dopisanie, że limit dotyczy każdego rynku z osobna.
