### ISSUE TITLE
Niespodziewany błąd - kod 405 - przy próbie edycji na systemie testowym

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#10059]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

Na systemie testowym, kiedy próbuję dokonać edycji oferty - np. zmienić cenę, lub czas dostawy np. na "P3D", dostaję kod błędu 405, który oznacza nieprawidłową metodę. 

Jednak stosuję prawidłową metodę PATH, i generalnie wszystko wygląda właściwie.

Trace Id jednej z komend na systemie testowym:

df126989276d692

Szczegóły błędu jako zrzut z PHP:

stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => NotAllowedException [message] => The HTTP method is not allowed [details] => [path] => [userMessage] => An error occurred [metadata] => stdClass Object ( ) ) ) )

**Comment by MaciejFrackowiak** [comment]
Czy w wywołaniu przekazujesz pełną ścieżkę tj. PATCH /sale/product-offers/{offerId}? Podpytuję, ponieważ z logów wynika, że request zawiera tylko PATCH /sale/product-offers i przez to kończy się błędem 405.

**Comment by tztztztz** [comment]
Dziękuję za informacje, naprawione.

Natomiast jest coś jeszcze: 

zmieniłem w ofercie czas dostawy na P21D (czyli trzy tygodnie), już jakieś 20 minut temu, a w ofercie nadal wisi info, że dostawa będzie pojutrze, zamiast za 3 tygodnie.

Czy ja coś nie tak robię, czy to coś nie tak z systemem testowym?

Edycja zwróciła sukces (kod 200)

trace-id:  b8f3c499f33b8151
offerId:  7775422208

**Comment by tztztztz** [comment]
Ok, dziękuję za pomoc. 

Kod 200 mnie nieco zmylił, sądziłem, że oznacza on zawsze zarówno prawidłowy request jak i prawidłowe dane.

**Comment by MaciejFrackowiak** [comment]
I tak de facto jest - od 22 października 2024 dla takich [przypadków](https://github.com/allegro/allegro-api/issues/9925) zwracać będziemy błąd.

**Comment by tztztztz** [comment]
Rozumiem w takim razie, że po 22 października nie dostałbym kodu 200 tylko inny np. 422 albo 400?

**Comment by tztztztz** [comment]
Jeśli można to jeszcze pytanie, bo nie chcę zakładać osobnego wątku:

W jaki sposób najlepiej obsłużyć ofertę z produktem premierowym, którego wysyłka będzie np. za 3 miesiące?

Mamy pole w ofercie:

delivery->shipmentDate

i rozumiem, że tam mogę wpisać datę premiery jako czas wysyłki + ewentualnie 1 dzień.

Tylko co wtedy z polem:

delivery->handlingTime 

Czy należy jest ustawić np. na puste, czy na jakąś specjalną wartość?

**Comment by MaciejFrackowiak** [comment]
shipmentDate to data przedsprzedaży, czyli dzień, od którego produkt będzie de facto dostępny. handlingTime to czas przygotowania wysyłki. Zatem przykładowo:
- shipmentDate 1.12.2024
- handlingTime 5 dni
- realny czas wysyłki 6.12.2024

**Comment by tztztztz** [comment]
Dziękuje i zamykam.
