### ISSUE TITLE
Wieczna weryfikacja urząrzenia

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#10057]
Problem występuje na jednej z przeglądarek.
Czyściłem cookies, logowałem się na nowo.
![obraz](https://github.com/user-attachments/assets/d4d0135a-548b-48bc-9e93-1d23ace6c081)

Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by tomasz-grzesik** [comment]
![obraz](https://github.com/user-attachments/assets/d8e5892c-7d11-4bf4-a8f1-d5552592b260)

![obraz](https://github.com/user-attachments/assets/7b561174-19fa-4269-b9cc-f64490f749a7)

**Comment by AureliuszBrussy** [comment]
Dzięki za zrzuty. Czy w oknie widzisz dodatkowo request id w formie uuid i czy możesz go przekazać?

**Comment by tomasz-grzesik** [comment]
Strona się przedładowywuje z dużą częstotliwością i ciężko coś wydobyć.
Poniżej kod strony:

`<html><head><title>allegrosandbox.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={'rt':'i','cid':'AHrlqAAAAAMAHGszvyI6KN0AJW0hXA==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','b':1352779,'s':29544,'host':'geo.captcha-delivery.com','cookie':'NK293D1fpEHUfMHC2kB1vSws9RMcsPNMwBXiqQYZkgSZC6xwWsdAlfhiviDr7bSAjknPAh5n9N4Dp7GjNIMvLBj6sdIXconI4QOimgfNTth1ul1POy5YCjggV0HFnuy9'}</script><script data-cfasync="false" src="[https://ct.captcha-delivery.com/i.js](view-source:https://ct.captcha-delivery.com/i.js)"></script></body></html>`

**Comment by AureliuszBrussy** [comment]
Próbujemy namierzyć ten problem. Daj proszę znać, jeżeli się coś zmieni.

**Comment by tomasz-grzesik** [comment]
Gdzieś tak od tygodnia występuje ten problem

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik dałeś na początku znać, że problem występuje na jednej z przeglądarek. Czy tylko na jednej i gdy testujesz na innej - problem nie występuje?

**Comment by tomasz-grzesik** [comment]
tak, tylko na jednej, sprawdzę jeszcze w trybie Incognito tej samej.

**Comment by tomasz-grzesik** [comment]
Dziękuję.
