### ISSUE TITLE
metoda doLogin

### ISSUE THREAD

**Issue by pap7tomek** [allegro/allegro-api#1005]
Czy ta metoda będzie działać do września 2019?
Ile czasu jest ważne sessionHandle?

**Comment by MartaNowaczyk** [comment]
1. Tak jak pisaliśmy [tutaj](https://github.com/allegro/allegro-api/issues/911) - jeśli będzie znany termin podamy go w oddzielnym komunikacie.
2.  Zgodnie z [tą informacją](https://allegro.pl/webapi/documentation.php/show/id,82) sessionHandle jest ważne godzinę.
