### ISSUE TITLE
Get a list of billing entries - pozyskanie "Szczegółów operacji"

### ISSUE THREAD

**Issue by Swistu93** [allegro/allegro-api#10052]
Dzień Dobry,

Informacje dot. rozliczeń z allegro pobieranie przez API różnią się względem informacji pobieranych przez API przy wykorzystaniu metody https://api.{environment}/billing/billing-entries.

Mianowicie nie ma dostępnego pola "Szczegóły operacji", które zawiera bardzo przydatne info np.

> Numer nadania: XXXXX, Kod: YYYYY, Identyfikator zamówienia: XXXXXXX-YYYYYY-ZZZZZZZ-AAAAAAAA, Szczegóły: Allegro Delivery PUP i APM; Order value = 12.34 PLN - w ramach Uslugi Allegro Smart

Czy istnieje jakaś możliwość by pozyskać te dane poprzez API?

**Comment by MaciejFrackowiak** [comment]
Nie, tych danych nie zwracamy w API.

**Comment by Swistu93** [comment]
Dziękuję za szybkie info
