### ISSUE TITLE
Replacing product images on offer creation

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#10066]
Hi, on **sandbox** I was trying to create an offer, using only own images following instructions from https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#own-images-and-description, but the resulting offer contained original image as well. I can see the original image is used in description. Is that a reason, why this process did not work as intended?

trace-id: cafd2272e7998c6c

Cheers!

Jikra

**Comment by AureliuszBrussy** [comment]
To get rid of product images (from our Product Catalog), pass an empty array in the `product.images` field. 

If those images are used in the description saved in the product, they will be added back to the gallery. If you want to make sure that only your images will be in the offer, modify the description.
