### ISSUE TITLE
403 error - Access denied on GET /billing/billing-entries

### ISSUE THREAD

**Issue by rumikk80** [allegro/allegro-api#10065]
Hello Allegro team,
I get this error massage  while sending GET request to the api.allegro.pl/billing/billing-entries
![image](https://github.com/user-attachments/assets/27a2921c-3e84-462d-918e-6645c0c1f79a)

 At the same time I have no any errors with this request 
 ![image](https://github.com/user-attachments/assets/b0b9db64-5103-49a4-9cfe-a50935443401)

I use the same token for the both requests

Best refards,
Mykhailo

**Comment by AureliuszBrussy** [comment]
You are likely trying to use a token obtained within [Client_credentials flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#client-credentials-flow). Such a token does not have a user context, so you get a 403 code in the response (e.g. when you try to access billing). To retrieve the billing correctly, use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) authorization type flow.

In our [documentation](https://developer.allegro.pl/documentation), you'll find the appropriate labels for what type of authorization you need to use to get the correct response from a given endpoint:

- bearer-token-for-user - code or device flow;
- bearer-token-for-application - client credentials.

**Comment by rumikk80** [comment]
Thank you for the fast and clear reply!
I'll try what you recommend
