### ISSUE TITLE
Jak sprawdzić czy produkt z katalogu jest powiązany z bazą tecdoc?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#10072]
Czy jest jakiś sposób?

Czy da się to zrobić na etapie wyszukiwania produktu?

**Comment by MaciejFrackowiak** [comment]
Nie, informacje o TecDoc zwracamy tylko na szczegółach produktu tj. [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).

**Comment by bugproof** [comment]
Czyli dla kazdego wyniku wyszukiwania musze pobrać szczegóły produktu i sprawdzić czy tecdocSpecification != null

**Comment by MaciejFrackowiak** [comment]
Tak.
