### ISSUE TITLE
Wyłączenie doGetItemsList i GET /offers/listing - brak?

### ISSUE THREAD

**Issue by grzegorzjj** [allegro/allegro-api#1007]
:bulb: **Sugestia**

Skoro zasób **GET /offers/listing** ma zastąpić metodę **doGetItemsList**, to dlaczego w tym zasobie REST API nie ma tak ważnego parametru, jak **data i czas zakończenia aukcji** ( lub dowolnej kombinacji tego parametru aukcji - typu data rozpoczęcia, pozostało do zakończenia ) ?

W/g mnie jest to jeden z podstawowych parametrów, na podstawie których podejmuje się kolejne operacje związane z aukcjami. 

Proponuję dodanie tego parametru ( data, czas zakończenia ) do zasobu /offers/listing

grzegorzjj.

**Comment by MartaNowaczyk** [comment]
@grzegorzjj Dziękujemy za sugestię. Zgłosiłam ją do odpowiedniego zespołu.

**Comment by grzegorzjj** [comment]
Dziękuję za zajęcie się tematem. Jeśli to możliwe - poproszę o informację o jego rozstrzygnięciu - to znaczy, czy będzie realizacja tej sugestii i mniej więcej w jakim terminie.
GrzegorzJJ
