### ISSUE TITLE
Zarządzanie aplikacjami Allegro Sandbox - aktywowanie kont na Sandbox 

### ISSUE THREAD

**Issue by Arek3A** [allegro/allegro-api#10079]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by Arek3A** [comment]
Chcę stworzyć środowisko testowe do testowania integracji mojego sklepu w BestSeller z Allegro. Dla środowiska produkcyjnego się udało, ale dla środowiska Sandbox nie mogę. 
Proszę o sugestie...
![image](https://github.com/user-attachments/assets/77d41eca-734d-4721-86c2-ede34cb81c45)

**Comment by Arek3A** [comment]
Jak mam aktywować konto na Sandbox? w przeczytanych komentarzach widzę że robicie to ręcznie czy tak? czy to tylko w okresie przejściowym czy tak już będzie to działać?

**Comment by MaciejFrackowiak** [comment]
Aktywowałem Twoje konto.

**Comment by Lukasz-Zurek** [comment]
@arcziii Konto w pełni aktywne.
