### ISSUE TITLE
acc activation - sandbox

### ISSUE THREAD

**Issue by rateleu** [allegro/allegro-api#10082]
od kilku dni próbuję aktywować konto do sprzedaży na sandbox, ale bez skutku. próbowałem z interfejsu podstawowego jak i nowego sales canter. Zrobiłem nawet drugie konto i nadal nic. NIP i IBAN wygenerowane randomowe. 
Mogę prosić o ręczną aktywację?
konto o nazwie: ratel1

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.
