### ISSUE TITLE
 [id Nowe konto Allegro] jest nieaktywne

### ISSUE THREAD

**Issue by Arek3A** [allegro/allegro-api#10086]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by Arek3A** [comment]
Proszę o aktywowanie konta. Konto było aktywowane na osobę ale, aby wprowadzać oferty na Allegro musimy mieć aktywowane konto na firmę. Zmieniliśmy rodzaj konta, ale jak rozumiem to spowodowało utratę aktywności. Ergo proszę o ponowne aktywowani

**Comment by AureliuszBrussy** [comment]
Rozumiem, że chodzi tutaj o konto na Sandboxie? Jeżeli tak - proszę o login tego konta.

**Comment by Arek3A** [comment]
akotlicki

**Comment by Arek3A** [comment]
Sorry jeszcze nie czuję co tu widać a co nie widać i jakie informacje podawać 
![image](https://github.com/user-attachments/assets/440812fe-f6cd-4d8a-8265-8bae92a81fe

**Comment by Arek3A** [comment]
Chciałem się tylko upewnić że dobrze komunikuję problem. Miałem konto na osobę, aby testować integrację. Było aktywowane i wszystko szło zgodnie z planem aż do momentu kiedy trzeba było dodać produkty. Tu się pojawił błąd który inni mieli opisany jako brak konta firmowego. Więc zamieniłem konto na firmowe, ale wtedy nic nie działało. Dlatego zakładam że zmieniając konto na firmowe muszę je aktywować oraz przejść całą ścieżkę integracyjną raz jeszcze i dopiero spróbować dodać nowy produkt. czy tak?

**Comment by AureliuszBrussy** [comment]
Proszę, abyś skorzystał z zakładki "[Ustawienia wypłat](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat)" oraz wskazał fikcyjne konto do wypłat oraz przeszedł symulację weryfikacji. Po tym będę mógł aktywować Twoje konto.

**Comment by Arek3A** [comment]
Witam zrobiłem ale nie wiem jak zweryfikować czy wszystko jest poprawnie zakończone?

**Comment by Arek3A** [comment]
Czy dużo jest takich ukrytych show-stopperów? To jest jak gra komputerowa z ukrytymi skarbami... : )

**Comment by AureliuszBrussy** [comment]
@Arek3A aktywowałem Twoje konto - już wszystkie czynności zostały wykonane, konto jest w pełni aktywne.
