### ISSUE TITLE
Allegro Automat ORLEN Paczka - Błąd pobierania historii statusów paczki 

### ISSUE THREAD

**Issue by piotreqm** [allegro/allegro-api#10081]
mam problem z pobieraniem historii statusów paczek wykorzystujących ten sposób dostawy. Api zwraca tylko jeden rekord, w którym mam nastepujące dane: trackingdetails = null oraz&nbsp;waybill = {nr listu przewozowego}.&nbsp;Inne dostawy zwracają prawidłowe dane. Zamówienie od strony panelu na allegro ma historię statusów. Jak mogę otrzymać prawidłowe dane dla tego sposobu dostawy?

Przykładowy nr zamówienia: 511e4090-86e3-11ef-a811-852efa26fac6

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że zapytanie `GET /order/carriers/ALLEGRO/tracking?waybill=AD0021AI97` zwraca pełną drogę przesyłki. Zawsze za pomocą zapytania `GET /order/checkout-forms/{orderID}/shipments` możesz upewnić się, jakie są prawidłowe wartości dla `carrierId` i `waybill`, tak aby przekazać je przy sprawdzaniu historii statusów.
