### ISSUE TITLE
/offers/listing ogranicza wyniki do 6000 i nie pozwala filtrować po promoted / regular

### ISSUE THREAD

**Issue by maciekjaros** [allegro/allegro-api#1008]
:bulb: **Sugestia**

Dowiedziałem się, że **/offers/listing** ma zastąpić **doGetItemsList**, więc chciałem przepisać moją aplikację, aby korzystała z nowej metody API REST. Okazuje się, że jest to niemożliwe, ponieważ maksymalna ilość rekordów aukcji z kategorii to 6000. Za pomocą **doGetItemsList** mogłem pobrać wszystkie aukcje z danej kategorii. Sortując po dacie dodania przerywałem pobieranie, gdy aukcje miałem juz u siebie. Reszty operacji (wyszukiwanie) dokonywałem już na pobranych od Was danych, żeby nie obciążać API i nie wykorzystywać limitu requestów.

W **/offers/listing** jestem ograniczony do 6000 rekordów. Wszystko byłoby super, gdybym mógł chociaż wybrać czy chciałbym otrzymać itemy 'regular' czy 'promoted'. W przypadku kategorii, gdzie itemów 'promoted' jest więcej niż 6000 nie mam nawet szans dokopać się do tych 'regular'.

/edit: Przeanalizowałem sobie to i rzeczywiście na stronie też wyświetlacie max 100 stron, czyli 6000 produktów na liście ofert. W obecnym API nijak nie jestem w stanie pobrać wszystkich aukcji z danej kategorii. W starej metodzie mogłem chociaż wybrać "wystawione w ciągu x godzin" jako filtr. To też by mnie zadowoliło... teoretycznie takie działanie zapewnia mi sortowanie po dacie wystawienia oferty, ale z racji tego, że oferty promowane są wypychane przed zwykłe aukcje jest to po prostu bezużyteczne.

/edit2: Zauważyłem, że filtrowanie po czasie wystawienia zniknęło też z kategorii na stronie. Nie można teraz w żaden sposób podejrzeć nowo wystawionych aukcji np. w ciągu godziny, bo wszystko przesłaniaja promowane. W kategoriach takich jak telefony czy laptopy nie da się tego przeglądać :/

/edit3: Dałem sobie radę. Wygląda na to, że filtr 'startingTime' działa też na innych kategoriach, mimo tego że widoczny jako dozwolony jest tylko w kategorii "motoryzacja" i "kolekcje i sztuka". Nie zmieniajcie tego proszę lub pozwólcie wybrać między promoted i regular. :)

**Comment by maciekjaros** [comment]
To korzystając z okazji mam pytanie odnośnie zastąpienia tej metody.

doGetItemsList zwracała listę parametrów dla wystawionych aukcji, żadna metoda API rest tego nie zwraca dla zasobów dostępnych ogólnie. Na potrzeby aplikacji powiadamiającej o nowych aukcjach spełniających kryteria użytkowników przydałaby mi się taka informacja. W przeciwnym razie o każde zapytanie musiałbym pytać API, co na pewno poskutkuje przekroczeniem ilości zapytań. Niby mogę prosić użytkowników o dodanie indywidualnego klucza api, ale wtedy musiałbym kupić więcej serwerów z publicznym IP, bo przekroczę ilość zapytań na sekundę z jednego serwera.

**Comment by MartaNowaczyk** [comment]
@maciekjaros metoda /offers/listing odzwierciedla zachowanie listy ofert, także tutaj nie dostaniemy informacji o parametrach danej oferty. Takie dane można teraz pobrać tylko jako zautoryzowany sprzedawca, który wystawił taką ofertę. Sugestię przekaazałam.

**Comment by maciekjaros** [comment]
Rozumiem, ale stara metoda zwracała te dane, teraz chcecie ją wyłaczyć i pozbawiacie mnie tych informacji, a tym samym pieniędzy za usługę wyszukiwania ofert, którą świadczyłem :)

**Comment by MartaNowaczyk** [comment]
Rozumiem, zgłoszę taką sugestię do odpowiedniego zespołu.

**Comment by 19bartek92** [comment]
@MartaNowaczyk W jaki sposób w takim razie mogę najłatwiej uzyskać listę wszystkich ofert? Rozwiązanie przedstawione przez Macka jest w porządku ale co w przypadku aukcji wystawionych np 3 temu, które są ciągle odnawiane? Chciałbym finalnie móc otrzymać wszystkie aukcje w danej kategorii.

**Comment by maciekjaros** [comment]
Nie da się, jeśli nie jesteś ich właścicielem. Dla moich zastosowań aukcje z x ostatnich godzin są jak najbardziej ok, bo piszę oprogramowanie, które powiadamia o nowych aukcjach, stare automatycznie usuwam i nie biorę ich pod uwagę. Choć odnowiona aukcja z np. nową ceną też by mi się przydała, to nie jest to wielki problem. Przez nowe API REST nie dostaniesz tych informacji w kategoriach, które mają ponad 6000 aukcji. No ewentualnie 12000 bo możesz to samo zapytanie pobrać z obu stron sortowania :)

**Comment by 19bartek92** [comment]
Z tym sortowaniem masz rację aczkolwiek wszystkie rozwiązania tego typu mnie delikatnie mówiąc drażnią ponieważ jest to już rzeźbienie czegoś co nie powinno moim zdaniem tak wyglądać. Tak czy inaczej dzięki za sugestie :)
