### ISSUE TITLE
What is the REST request url to get offer info (not mine)?

### ISSUE THREAD

**Issue by mapexpert** [allegro/allegro-api#1009]
Hi,
couldn't find rest request for item info (not mine as a seller)
can I get offer html description and params for an offer?

thanks in advance

**Comment by MartaNowaczyk** [comment]
@mapexpert No, you can't. You must be authenticated and authorized as a seller that listed the offer to get a description and offer parameters.

**Comment by mapexpert** [comment]
Thank you Marta.
If I'll register is a seller can I get other sellers offers info and params?
Thanks in advance

**Comment by MartaNowaczyk** [comment]
No, you can only get info about yours offers.

**Comment by fero-sk** [comment]
Hello,
will it be available in future version of REST API?

**Comment by MartaNowaczyk** [comment]
@fero-sk We will work on it. We will provide information about this in a separate message. Follow us on GitHub.
