### ISSUE TITLE
Image pixel count is too high. What is the limit?

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#10090]
Hi, I believe I understand what the error sais, but I was not able to find in your documentation, what the limit for pixel count is. Can you please advice?
`userMessage='Image pixel count is too high.`

Thanks

Jirka Z

**Comment by jezewskiBNetrox** [comment]
@ZajdaBear Hi, use this guideline: https://help.allegro.com/sell/en/a/rules-for-images-in-the-gallery-and-in-descriptions-8dvWB8Y2PIq

>- Image minimum size — a minimum of 500 pixels (the longer side)
>- Image maximum size — 2560 x 2560 pixels. On Allegro, you can upload images with a maximum resolution of 26 Mpx. We will proportionally scale images with a side longer than 2560 pixels to fit the 2560x2560 size.
