### ISSUE TITLE
Konto SandBox firmowy [id SandBox firmowy] jest nieaktywne

### ISSUE THREAD

**Issue by Arek3A** [allegro/allegro-api#10093]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by Arek3A** [comment]
bardzo proszę o aktywację tego konta
Login akotlicki lub arek.kotlicki@gmail.com

**Comment by AureliuszBrussy** [comment]
Odpisałem na Twoje zgłoszenie w #10086 - tam kontynuujmy wątek.
