### ISSUE TITLE
Tabele rozmiarów

### ISSUE THREAD

**Issue by kudel** [allegro/allegro-api#101]
Witam.

Czy API umożliwia zarządzanie ostatnio wprowadzonymi tabelami rozmiarów?
Czy można je definiować i przypisywać do itemID aukcji?

Ew. jakaś podpowiedź jak wprowadzić tabele rozmiarów i szybko je przypisać do serii aukcji?

Dzięki.

**Comment by KrzysztofLukanowski** [comment]
Cześć,

jeszcze nie udostępniliśmy obsługi tabel rozmiarów przez API. W przeciągu najbliższych tygodni planujemy udostępnić takie rozwiązanie w REST API. Na tę chwilę pozostaje przygotować i przypisać tabele rozmiarów do poszczególnych ofert poprzez stronę allegro.pl

**Comment by kudel** [comment]
Rozumiem.
Dziękuję za odpowiedź.
