### ISSUE TITLE
swagger.yaml - klasa DescriptionSectionItem

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#1010]
Korzystam z openapi-generator do wygenerowania klas (java) z pliku swagger.yaml. 

1. Wygląda na to, że plik ma złą definicję klasy DescriptionSectionItem, bo po wygenerowaniu zawiera ona w konstruktorze przypisanie wartości do pola `type`, ale nie posiada definicji tego pola:

```
public class DescriptionSectionItem {
  public DescriptionSectionItem() {
    this.type = this.getClass().getSimpleName();
  }
```

2. Klasa `DescriptionSection` posiada listę itemów danej sekcji, które są typu `DescriptionSectionItem`:

```
private List<DescriptionSectionItem> items = null;
```

Po pobraniu szczegółów konkretnej oferty metodą `/sale/offers/{offerId}` w polu `description `otrzymuję co prawda poprawną liczbę sekcji i elementów w danej sekcji, jednak jest to całkowicie bezużyteczne, bo nie ma w nich zawartości. Klasa ta (`DescriptionSectionItem`) nie zawiera nic. Dopiero klasy:

```
DescriptionSectionItemText
DescriptionSectionItemImage
```

rozszerzają wspomnianą wyżej klasę i posiadają pola `content` i `url` odpowiednio, ale nic mi to nie daje, bo metoda REST zwraca obiekty klasy bazowej (`DescriptionSectionItem`) i wartości te są gubione.
Czy nie lepiej by było, gdyby pola `content` i `url` były bezpośrednio w klasie `DescriptionSectionItem`? Wtedy wartości tych pól są poprawnie uzupełniane.

**Comment by MartaNowaczyk** [comment]
@Radziasss dziękujemy za zgłoszenie. Sprawę przekazałam do odpowiedniego zespołu.

**Comment by MartaNowaczyk** [comment]
@Radziasss dostałam informację, że nasz swagger jest poprawny z punktu widzenia specyfikacji openapi. Nie mamy w planach zmiany według powyższych sugestii.
1. wygenerowaliśmy klasę najnowszą wersją openapi-generatora.
2. błąd wynikać może z wielu przyczyn m.in starej wersji openapi-generatora
