### ISSUE TITLE
sprawdzenie poprawności danych do wystawienia aukcji

### ISSUE THREAD

**Issue by programista06** [allegro/allegro-api#10108]
Witam.
Czy obecne API oferuje funkcje do sprawdzania poprawności przesyłanych danych i ewentualnie pobrania kosztów bez samego wystawienia ?
Kiedyś chyba była funkcja CheckNewAuctionExt, teraz na https://developer.allegro.pl/documentation w sekcji Offer management chyba nie ma nic takiego ?

**Comment by AureliuszBrussy** [comment]
Możesz skorzystać z [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation#operation/calculateFeePreviewUsingPOST) aby sprawdzić opłaty dla danego zestawu danych o ofercie. 

Jeżeli chodzi o wstępne zwalidowanie przed wystawieniem - pozostaje możliwość utworzenia draftu oferty, czyli podczas skorzystania z [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers) w `publication.status` wyślij `INACTIVE`. To jedyna możliwość.
