### ISSUE TITLE
Nadawanie przesyłek na środowisku testowym

### ISSUE THREAD

**Issue by sk-cosmo** [allegro/allegro-api#10104]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Mam problem z nadawaniem przesyłek na testowym środowisku z poniższymi metodami dostawy.
Co jest przyczyną problemów?

Allegro International Automaty Paczkowe Czechy 
trace-id: c37fdd8746c14b51
Przesyłka nie została zamówiona. Przekroczono czas oczekiwania na potwierdzenie zlecenia ze strony przewoźnika. Ponów operację później.

Allegro Odbiór w Punkcie DPD Pickup Czechy
trace-id: 2e0ab723590f890e
Punkt odbioru nie istnieje lub nie przyjmuje nowych przesyłek

Allegro Automaty Paczkowe DPD Czechy
trace-id: ecc9bd76f6f4d9ee
Punkt odbioru nie istnieje lub nie przyjmuje nowych przesyłek

**Comment by PrzemyslawLukanowski** [comment]
> Allegro International Automaty Paczkowe Czechy
> trace-id: c37fdd8746c14b51
> Przesyłka nie została zamówiona. Przekroczono czas oczekiwania na potwierdzenie zlecenia ze strony przewoźnika. Ponów operację później.

W tym przypadku problem powoduje numer odbiory. Numer telefonu odbiorcy z Czech:

- musi składać się z 9 cyfr
- rozpoczynać się cyfrą 6 albo 7
- może mieć przedrostek +420

> Allegro Odbiór w Punkcie DPD Pickup Czechy
> trace-id: 2e0ab723590f890e
> Punkt odbioru nie istnieje lub nie przyjmuje nowych przesyłek

Nie wszystkie punkty są aktywne na środowisku testowym, dlatego skorzystaj z punktu: CZ25297 Uralská 634/10, 16000 Praha.

> Allegro Automaty Paczkowe DPD Czechy
> trace-id: ecc9bd76f6f4d9ee
> Punkt odbioru nie istnieje lub nie przyjmuje nowych przesyłek

W tym przypadku skorzystaj z CZ24519 Partyzánská -, 17000 Praha 7.

**Comment by sk-cosmo** [comment]
Dziękuję, jeśli problem nie ustąpi, to dodam nowy komentarz.
Czy istnieje jakiś adres na środowisku testowym, który pozwala na wywołanie metody dostawy Allegro International Kurier Czechy oraz Allegro International Odbiór w Punkcie Czechy?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o dostawę przez Kuriera na adres, to możesz użyć dowolnego adresu. W przypadku odbioru w punkcie, możesz skorzystać z AWD0286.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, źle zrozumiałem to pytanie. Tak, wyłączenie metody Allegro DPD Kurier Czechy powinno pomóc w tej sytuacji.

**Comment by sk-cosmo** [comment]
Niestety, muszę po czasie wrócić do tematu. 

Wciąż mam problem z nadaniem przesyłek dla:

- Allegro International Kurier Czechy 
trace-id: e1242602dcf9bdbd
Błąd zewnętrznego przewoźnika

- Allegro International Automaty Paczkowe Czechy
trace-id: e4ca9ce4d66b5706
Błąd zewnętrznego przewoźnika

- Allegro International Odbiór w Punkcie Czechy
trace-id: 763df3803fae3586
Błąd zewnętrznego przewoźnika

Proszę o wsparcie w tym temacie oraz o wskazanie przyczyn, dla których otrzymuję wymienione wyżej błędy.
