### ISSUE TITLE
Problemy z ustawieniem daty premiery dla oferty na systemie testowym

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#10105]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem testowym / with the test environment

Dzień dobry,

na systemie testowym Allegro, kiedy próbują ustawić datę premiery (delivery->shipmentDate) otrzymuję błąd:

"Request contains invalid data. Contact the application author"
"path":"delivery.shipmentDate"

Trace id: d1fa7603de4a117d

Tylko kwestia jest taka, że wysyłana data wygląda prawidłowo, poniżej wysyłane dane do edycji:

stdClass Object ( [delivery] => stdClass Object ( [handlingTime] => PT24H [shipmentDate] => 2025-05-09T00:00:00.000 ) )

Data "2025-05-09T00:00:00.000" jest wg. standardu ISO 8601

Próbowałem także "2025-05-09T00:00:00", "2025-05-09T00:00:00", "2025-05-09 00:00:00" oraz "2025-05-09" 

Za każdym razem zgłasza ten sam błąd.

Jaki jest Wasz prawidłowy format daty, tak, żeby to można było ustawić?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, dodaj proszę o końcu literę Z (oznaczającą czas Zulu, uniwersalny), czyli "2025-05-09T00:00:00.000Z".

**Comment by tztztztz** [comment]
Działa, dziękuję.
