### ISSUE TITLE
Pickup in parcel-management

### ISSUE THREAD

**Issue by omursemih** [allegro/allegro-api#10113]
I see there is option to order a courier pickup via API.as part of the "Wysyłam z Allegro" service, you provide resources on the /shipment-management path, using which we can manage our shipments, create a label, download the shipping protocol, and also
**_order a courier pickup_**.

Is that possible to make order courier pickup from "parcel-management"?

**Comment by AureliuszBrussy** [comment]
It is possible, but please do not use parcel-management endpoints. They are deprecated and will be completely removed on January 31, 2025. Use only shimpement-managment.
