### ISSUE TITLE
REST API offer info and data

### ISSUE THREAD

**Issue by mapexpert** [allegro/allegro-api#1011]
I'am developing an application for a buyer from EU.
Our company has a warehouse in Poland and intends to buy car parts from allegro to deliver to customers in EU.
The idea is in delepoling a kind of proxy which will provide allegro offers with translation to Spanish, German, etc and delivery to other EU countries. 
To do this we need almost all allegro functions for frontend including offer info and data.
Idea is in providing special status to rest application - "BUYER" - and opening access to offer data.

**Comment by MartaNowaczyk** [comment]
We don't have a resource in REST API to do that without authorization. At this moment, to get the offers data, you must be logged to a seller account.

**Comment by aktywnitu** [comment]
@mapexpert why not use google translator proxy or create browser plugin, which translate the page?

**Comment by mapexpert** [comment]
> @mapexpert why not use google translator proxy or create browser plugin, which translate the page?

1. google translator is not free ;-)
2. google translator translates awfully special car parts terms. I found an translations server (not free) with specialized dictionaries (e.g "machinery")
3. I do not want to parse web pages when there is an API
4. I do not to increase traffic and resources load on allegro and my server

**Comment by TimothyKoval** [comment]
@mapexpert Would You be so kind to share a link to that service?

**Comment by TimothyKoval** [comment]
@mapexpert Thank You :) I'll let You know if it's any good if I end up trying it out :)

**Comment by aktywnitu** [comment]
@mapexpert old WEBAPI has such methods, but it will be soon deprecated and disabled.
Maybe you'd like to invite some car parts sellers to connect their allegro accounts and load their offers to your database.

**Comment by TimothyKoval** [comment]
@mapexpert Are You sure they have Polish language support?
