### ISSUE TITLE
/offers/listing zwraca różne wyniki dla kolejnych zapytań

### ISSUE THREAD

**Issue by maciekjaros** [allegro/allegro-api#1012]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Załóżmy, że chcę pobrać wszystkie aukcje z kategorii 125154 (Smartfony Huawei). W momencie pobierania w kategorii było 4779 aukcji.

Po pierwszym requeście w SearchMeta mam informację ile jest aukcji. Wiem ile stron muszę przeiterować, żeby pobrać wszystkie dane:

Przykładowy request:

https://allegroapi.io/offers/listing?category.id=125154&include=-all&include=items&include=searchMeta&sort=-startTime&limit=100&offset=100

I teraz mam problem, bo co n-ty request dostaję inny count. Nie jest to spowodowane wypadnięciem aukcji z wyników wyszukiwania ani dodaniem nowych, bo w kolejnych requestach liczba staje się taka jak poprzednia, np:

- 4779
- 4779
- 4778
- 4779
- 4778
- 4779

Wygląda to jakby odpowiedzi pochodziły z innych serwerów? Skutkuje to tym, że zdarza mi się w kolejnych paczkach otrzymywać aukcje, które już pobrałem. Finalnie, po pełnej iteracji, zapisuję mniej aukcji niż zwrócona w searchMeta wartość.

**Comment by FromAnyHole** [comment]
Przyzwyczaj się - taka jest istota "dynamicznych strumieni" danych...

**Comment by maciekjaros** [comment]
Na froncie macie to samo :D 

Odświeżenie strony zmienia mi liczbę aukcji między 4 789 i 4 790.

**Comment by maciekjaros** [comment]
Oj, nieprawda. Pobieram cały czas pierwszą stronę i w jednym requeście już mam nowo wystawioną aukcję, a w drugim nie. I tak na zmianę co n-ty request.

**Comment by grzegorzjj** [comment]
Tak na prawdę nie ma znaczenia, ile jest ofert przy ich cyklicznym pobieraniu. Jeśli robi to automat ( crontab ), to i tak jakieś mogą Ci umknąć, bo ktoś coś wystawi i po 5 minutach już się sprzedało pomiędzy pobraniami. Jeśli chcesz uniknąć straty oferty podczas pobierania, to ustaw sort na +endTime i pobierzesz najpierw te kończące. Ja pobieram nie według ilości zwracanej przez searchMeta, ale do momentu, gdy ilość zwracana jest pusta.
