### ISSUE TITLE
Brak prawidłowej spłaty zamówienia na środowisku testowym

### ISSUE THREAD

**Issue by KrystianBogiel** [allegro/allegro-api#10125]
Występuje problem:
 - [X] ze środowiskiem testowym / with the test environment

Po symulacji płatności które nie zakończyły się pomyślną spłatą - nie mogę prawidłowo spłacić zamówienia.

Przy składaniu zamówień testowych wybieram metodę płatności "przelew" z PKO Bank Polski.
![image](https://github.com/user-attachments/assets/10b664f2-f318-4ad7-9341-368c58367d59)

Po złożeniu zamówień z symulowanym brakiem płatności i oczekiwaniem na wpłatę:
![image](https://github.com/user-attachments/assets/24fa7786-f9f5-41a9-9e7b-dfd8e9da9423)

następujące po nich kolejne zamówienia z wyborem czynności zapłać:
![image](https://github.com/user-attachments/assets/ca294692-0317-462a-aca4-b88a8d9942ba)

nie są spłacane, zamówienie dalej oczekuje na płatność:
![image](https://github.com/user-attachments/assets/29c39488-eb94-4126-a7fe-3ee13f2b0f8e)

![image](https://github.com/user-attachments/assets/2d37cf21-5392-4f10-bde8-cd5db5636ef5)

Sytuacja ma miejsce od dziś, od godziny ok. 13:00.

Konto: Januszeks
Przykładowe zamówienie gdzie wybrałem "zapłać" a dalej oczekuje na płatność:  fde20ff0-8c83-11ef-9d39-6f950d1f32f1

**Comment by Lukasz-Zurek** [comment]
@KrystianBogiel Z góry przepraszamy za utrudnienia - mogło to wynikać z tymczasowych problemów po stronie operatora płatności i ich środowiska testowego. Sprawdziłem przed momentem i płatności działają już prawidłowo.
