### ISSUE TITLE
Delivery method not returned on /shipment-management/delivery-services endpoint (SANDBOX)

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#10123]
Hi, we are testing the move from deprecated 'parcel management' to 'shipment management'. We wanted to use endpoint /shipment-management/delivery-services to get insurance currency you would accept in shipment create command. The issue is, I cannot find delivery method id in the list. 
order number: a7d75750-8bd4-11ef-9da8-b136fd248e29
deliveryMethodId: 1205bb4a-7d74-46a4-b7de-1cb66a3d0c03

Could you please explain
1) why is this deliveryMethod is not returned in the list
2) how can we get the currency for insurance, if delivery method is not present in the list

Thx!

Jirka Z

**Comment by AureliuszBrussy** [comment]
This delivery method is just simply not available through Ship with Allegro. You will get all supported delivery methods within Ship with Allegro just by using [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation#operation/getDeliveryServices).

**Comment by ZajdaBear** [comment]
Understood. It was an error mapping the delivery on our side, registering it as ship with Allegro. Thanks
