### ISSUE TITLE
ERROR: "An authorization code must be supplied."

### ISSUE THREAD

**Issue by kingab100** [allegro/allegro-api#1013]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zarejestrowałam aplikację. Po przekierowaniu na stronę logowania, zalogowaniu się i powiązaniu aplikacji otrzymuję kod do wygenerowania tokena w linku. Wcześniej otrzymane: client_id:client_secret w takiej formie przekształcam na Base64 i wpisuję w konsolę zapytanie
curl -X POST -H "Authorization: Basic (to co otrzymalam z Base64)" https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=0Cvh9q0V9t82t80b6Ro5JYrVtGJ1uGIV&redirect_uri=https://salonik-piekna.000webhostapp.com/index.html

Otrzymuję błąd:
{"error":"invalid_request","error_description":"An authorization code must be supplied."}
nie mogę zatem uzyskac tokena

**Comment by MartaNowaczyk** [comment]
@kingab100 Sprawdź czy na pewno wykonujesz wszystkie kroki, które opisaliśmy [tutaj](https://developer.allegro.pl/auth/#app). Do weryfikacji potrzebuję twojego klucza API/client-id. Możesz go podesłać przez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt)podając numer wątku.

**Comment by kingab100** [comment]
Nie wiem jaki temat problemu podac w formularzu, ale chciałabym przesłać client id, może jakąś szybszą drogą?

**Comment by MartaNowaczyk** [comment]
@kingab100 tematem problemu się nie przejmuj tak czy inaczej do mnie dotre jak dopiszesz, że to API i zgłoszenie na GitHubie #1013. Jeśli chcesz koniecznie jakąś ścieżkę możesz wybrać Sprzedaję > Zarządzanie sprzedażą > Wystawianie i edycja oferty.

**Comment by kingab100** [comment]
przesłałam

**Comment by kingab100** [comment]
mam też pytanie, czy Wasze dane to listy produktów/kategorii, czy wystąpienia tych nazw i kategorii w jakichś kontekstach?

**Comment by MartaNowaczyk** [comment]
@kingab100 z tego co sprawdziłam wygląda na to, że podajesz błędny kod autoryzujący - trzeba pamiętać, że jest ważny 10 sekund. Sprawdź proszę czy na pewno jest poprawny.

> mam też pytanie, czy Wasze dane to listy produktów/kategorii, czy wystąpienia tych nazw i kategorii w jakichś kontekstach?

tutaj proszę doprecyzuj, bo nie rozumiem o co tu dokładnie chodzi, a nie chciałabym się domyślać.

**Comment by kingab100** [comment]
Podaję kod, który pojawia się w linku aplikacji po kliknięciu przekierowania do logowania allegro (kiedy jestem juz zalogowana, po prostu pojawia się nowy kod w linku). Nie mija 10s od kiedy wywoluję zapytanie z nowym kodem, czy sprawdzała Pani czy wszystko w porządku z aplikacją, rozumiem, że kod należy skopiować z linku?

**Comment by MartaNowaczyk** [comment]
@kingab100 nie widzę problemów po stronie konfiguracji API. To właśnie ten kod z linku należy skopiować. Podeślij jeszcze proszę przez formularz kontaktowy wszystkie curle z pełnymi danymi od początku do końca jakie wywołujesz. Może gdzieś wkradł się błąd.

Jeśli chodzi o listę ofert, które wystawiasz możesz je pobrać metodą GET na zasobie [/sale/offers](https://developer.allegro.pl/documentation/#/offer-management/searchOffersUsingGET) wraz ze szczegółami. Szczegóły pojedynczej oferty pobierzesz metodą GET [/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#!/offer-management/getOfferUsingGET). 

Więcej w naszych [poradnikach](https://developer.allegro.pl/my_offers/) na stronie.

**Comment by kingab100** [comment]
Przesłałam dokładny opis kroków. Tych requestóœ nie wykonam dopóki nei otrzymam tokena usera, poprzez niedziałające zapytanie. Chyba, że mogę otrzymać go inną drogą.

**Comment by MartaNowaczyk** [comment]
@kingab100 spróbuj umieścić w ostatnim kroku adres w apostrofach zamiast w cudzysłowie:

curl -X POST -H 'Authorization: Basic YTI...Hg' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=p...nCJDWto&redirect_uri=https://salonik-piekna.000webhostapp.com/index.html'

**Comment by MartaNowaczyk** [comment]
Sprawdź czy na końcu tokena nie podajesz jakiegoś dodatkowego znaku np. kropki, nawiasu itp.
