### ISSUE TITLE
Niewłaściwe kodowanie

### ISSUE THREAD

**Issue by request4t** [allegro/allegro-api#10133]
Gratulacje.

Otrzymuję listę zamówień. Ale niektóre znaki w odpowiedzi pojawiają się w niewłaściwym kodowaniu. Na przykład: GdaA?sk.

Jak można to naprawić?

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj do nagłówka Accept dodać wartość ";charset=UTF-8". Domyślnie powinniśmy jednak zwracać polskie litery - nie udało mi się powtórzyć Twojego przypadku, jak i w logach również widzimy polskie znaki.

**Comment by request4t** [comment]
Dziękuję za odpowiedź.

Teraz jest lepiej, ale polskie litery bez ogonków i kresek. Np.: Gdansk, SPOLKA.

Mam taki problem, ponieważ jestem z Ukrainy i korzystam z ukraińskiej applikacji.

Czy jest coś jeszcze, co możesz polecić?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale niewiele więcej mogę doradzić. Wygląda to na problem po stronie Twojego narzędzia, ponieważ kodowanie UTF-8 wspiera wszystkie znaki unicode, w tym polskie.

**Comment by request4t** [comment]
Dobrze, dziękuję) Będe szukać rozwiązania.
