### ISSUE TITLE
Authentication for Allegro One Fulfillment Stock Level

### ISSUE THREAD

**Issue by Thangthebrandlab** [allegro/allegro-api#10147]
Hi,

I'm currently experiencing issues developing an API connection to retrieve One Fulfilment Stock Level, but keeps on experiencing 403 Forbidden error code. 

For you context, I have already obtained an Rest API application:

- application type: "The application runs in an environment without access to a browser or keyboard (e.g., a console application or a TV device)"
- Access to allegro:api:fulfillment:read is toggled on. 
- I have already received an access token.

Here is my sample code below:

```
import requests

url = "https://api.allegro.pl/fulfillment/stock"

payload = {}
headers = {
  'Accept': 'application/vnd.allegro.public.v1+json',
  'Accept-Language': 'en-US',
  'Authorization': '{Bearer Token goes here}',
  'Cookie': ''
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

Where am I missing and what am I doing wrong? How can I retrieve One Fulfilment Stock Level? Thanks!

**Comment by PrzemyslawLukanowski** [comment]
Hi, only One Fulfillment type of accounts can access the One Fulfillment resources. To check whether yours is marked as 1F, use [GET /me](https://developer.allegro.pl/documentation#operation/meGET) and check the information in the `features` field. If not, please use [the contact form](https://allegro.pl/pomoc/kontakt?srsltid=AfmBOoqKZ0xNRE7Sd3n6eWFChHSv5MYuHgRR8bZrsDRLoAtMeaQAJQ9f) to get more information on how to register this type of account.

**Comment by Thangthebrandlab** [comment]
Hi, I also cannot access to the Get/me.

`import requests
import json

url = "https://api.allegro.pl/me"

payload = {}
headers = {
  'Accept': 'application/vnd.allegro.public.v1+json',
  'Content-Type': 'application/vnd.allegro.public.v1+json',
  'Authorization': 'Bearer + {Token}',
  'Cookie': ''
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
`
What have I perhaps done wrong here?

**Error message 403 Forbidden:**
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "No access to the specified resource.",
            "metadata": {}
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
It seems that you are using a token generated in [the client credentials flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow). That type of token does not have the user context and gives you access only to resources that are marked as bearer-token-for-application in our documentation. To have access to resources with bearer-token-for-user, please generate token via [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow.
