### ISSUE TITLE
UnknownProperties: type - mimo że jest podane w dokumentacji

### ISSUE THREAD

**Issue by Pitupitupit** [allegro/allegro-api#10143]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

POST /sale/product-offers
trace-id = 176a40298fd05574

W odpowiedzi mamy błąd "unknownProperties" : "...**type**, ..."

Proszę o wskazanie gdzie w żądaniu jest nieznane pole **type**. Wg [dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers) to pole powinno być tylko w obiekcie **DescriptionSectionItem** i tak też to wysyłamy. Jest to jedyne pole **type** w żądaniu.
```
"description" : {
      "sections" : [ {
        "items" : [ {
          "type" : "IMAGE",
          "url" : "https://a.allegroimg.com/original/11<...>"
        }, {
          "type" : "TEXT",
          "content" : "<...>"
        } ]
      },
...
```

**Comment by Lukasz-Zurek** [comment]
Weryfikujemy to. Proszę Cię o cierpliwość.
