### ISSUE TITLE
Web API metoda doGetPostBuyFormsIds zwraca pustą listę.

### ISSUE THREAD

**Issue by snapmic** [allegro/allegro-api#1014]
Wywołanie metody doGetPostBuyFormsIds zwraca pustą listę. Otrzymaną listę potrzebuję do pobrania danych formularzy metodą doGetPostBuyFormsDataForSellers.
Jeżeli pobieram zdarzenia przez doGetSiteJournalDeals, to na liście mam pozycje dealTransactionId i na tej podstawie mogę przekazać argument do doGetPostBuyFormsDataForSellers.
Jednak takie pobieranie na podstawie dziennika zdarzeń jest mało wygodne. Czy użycie doGetPostBuyFormsIds powinno dawać te same wyniki, czy popełniam jakieś błędy przy użyciu?

**Comment by MartaNowaczyk** [comment]
@snapmic jeśli chodzi o obsługę sprzedaży, rekomendujemy działanie na dziennikach zdarzeń, tak jak opisaliśmy to w naszym [poradniku](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421). 
Poza tym metoda doGetPostBuyFormsIds powinna zwracać odpowiednie wyniki, jeśli w danej ofercie kupujący wypełnił formularz dostawy i zapłaty. Podeślij proszę request i response w formacie XML wywołania, które zwraca pustą listę (jeśli chcesz możesz zrobić to przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) allegro z dopiskiem, że sprawa dotyczy zgłoszenia #1014 na GitHubie)

**Comment by MartaNowaczyk** [comment]
@snapmic dla podanej metody użyj filtra "Rola użytkownika w transakcji" jako sprzedający - seller:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoGetPostBuyFormsIdsRequest>
         <ser:sessionId>e5dd...17//01_1</ser:sessionId>
         <ser:filterOptions>
            <ser:item>
               <ser:filterId>userRole</ser:filterId>
               <ser:filterValueId>
                  <ser:item>seller</ser:item>
               </ser:filterValueId>
            </ser:item>
         </ser:filterOptions>
      </ser:DoGetPostBuyFormsIdsRequest>
   </soapenv:Body>
</soapenv:Envelope>
```


Co do obsługi przesyłek, to prawda - nie ma jeszcze tego w REST API, jednak jesteśmy w trakcie prac nad takim zasobem.
