### ISSUE TITLE
GPSR   /sale/responsible-producers   od frontu

### ISSUE THREAD

**Issue by biuronimo** [allegro/allegro-api#10144]
Cześć, 
wiecie może czy metody 

POST  /sale/responsible-producers
i
GET    /sale/responsible-producers

są już dostępne gdzieś w interfejsie użytkownika? 

Jeśli nie to kiedy będą dostępne? 

Dzięki

**Comment by Lukasz-Zurek** [comment]
Nie, nie są jeszcze dostępne i nie wiemy kiedy to nastąpi. Zachęcam Cię jednak do kontaktu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), być może uda Ci się uzyskać informacje dotyczące ewentualnego terminu.

**Comment by biuronimo** [comment]
Dowiedziałem się, że do końca miesiąca interfejs użytkownika będzie już dostępny. 
Pozdrawiam
