### ISSUE TITLE
Jak określić kierunek dostawy dla metod pobranych z sale/delivery-methods?

### ISSUE THREAD

**Issue by d-golebiowski** [allegro/allegro-api#10154]
W ustawieniach dostaw na froncie jest możliwość wyboru metod dostawy poprzez ich kierunek.

![image](https://github.com/user-attachments/assets/e14e3f8c-f1fb-4654-ab59-930359ba8edd)

Jak można określić taki kierunek na podstawie metody dostawy pobranych z `sale/delivery-methods`?

**Comment by PrzemyslawLukanowski** [comment]
Nie mamy dokładnego odpowiednika tej funkcjonalności. Możesz jedynie sugerować się polem `"marketplaces"`, w którym zwracamy informację, na jakim serwisie dana metoda dostawy będzie widoczna dla kupującego.

**Comment by d-golebiowski** [comment]
ok, dzięki za szybką odpowiedź
