### ISSUE TITLE
Request contains invalid data. Contact the application author.

### ISSUE THREAD

**Issue by mesia2010** [allegro/allegro-api#10158]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

https://api.allegro.pl/sale/product-offers

Wysyłając request:
{"name":"DOZOWNIK R\u0118CZNY \u0141AZIENKOWY DO P\u0141YNU DO MYD\u0141A SZAMPONU \u015aCIENNY 200ml","category":{"id":"105334"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":null},{"id":"229205","valuesIds":["229205_340245"],"values":null}],"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>R\u0119czny dozownik myd\u0142a do r\u0105k do monta\u017cu na \u015bcianie podw\u00f3jny szampon w p\u0142ynie dozownik \u017celu pod prysznic \u015brodek do mycia r\u0105k dozownik balsamu do toalety do \u0142azienki toaleta hotelowa 200mlx2 <\/p><p> <\/p>"}],"radio":"0"},{"items":[{"type":"TEXT","content":"<p>Cecha: <\/p><p>1. Podw\u00f3jny dozownik myd\u0142a, trwa\u0142y i elegancki. <\/p><p>2. Doskona\u0142y do myde\u0142 w p\u0142ynie, \u017celi pod prysznic, szampon\u00f3w itp. <\/p><p>3. Wyeliminuj ba\u0142agan w butelce pod prysznic i po\u017cegnaj si\u0119 z niechlujnymi butelkami po balsamie. <\/p><p> <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986"}],"radio":"1"},{"items":[{"type":"TEXT","content":"<p>Dane techniczne:  <\/p><p>Kolor: srebrny\u00a0 <\/p><p>Materia\u0142: ABS  <\/p><p>Typ g\u0142owicy pompy: ciecz  <\/p><p>Dawkowanie: oko\u0142o 0,9-1,0 ml \u00a0  <\/p><p>Korzystanie z trybu: Naci\u015bnij  <\/p><p>Instalacja: Monta\u017c na \u015bcianie  <\/p><p>Pojemno\u015b\u0107: 200 ml * 2  <\/p><p>Zastosowanie: komercyjne, domowe, hotelowe, biurowe, szkolne, bankowe, szpitalne, barowe itp.\u00a0  <\/p><p>Waga przedmiotu: ok. 340 g \/ 11,99 uncji  <\/p><p>Rozmiar przedmiotu: ok. 130 * 53 * 198 mm \/ 5,12 * 2,09 * 7,80 cala (d\u0142. * szer. * wys.)  <\/p><p>Waga opakowania: ok. 416 g \/ 14,67 uncji  <\/p><p>Rozmiar opakowania: ok. 20,5 * 13,5 * 7 cm \/ 8,07 * 5,31 * 2,76 cala (d\u0142. * szer. * wys.) <\/p><p> <\/p><p> <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}],"radio":"0"},{"items":[{"type":"TEXT","content":"<p>Lista pakiet\u00f3w: <\/p><p>\u00a0 \u00a0 <\/p><p> <\/p><p>1 * r\u0119czny dozownik myd\u0142a <\/p><p> <\/p><p>4 * \u015aruba\u00a0 <\/p><p> <\/p><p>4 * w\u0105\u017c\u00a0 <\/p><p> <\/p><p>2 * klucz <\/p><p> <\/p><p>1 * naklejka na etykiet\u0119 <\/p><p> <\/p><p> <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}],"radio":"1"}]},"language":"pl-PL","payments":{"invoice":"NO_INVOICE"},"external":{"id":"H17982S"},"location":{"countryCode":"DE","province":"Niemcy","city":"Brema","postCode":"64546"},"sellingMode":{"format":"BUY_NOW","price":{"amount":108.49,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"373a6ace-2436-4bb5-bb3c-1e711c7cafa4"},"handlingTime":"P2D","additionalInfo":null,"shipmentDate":null},"stock":{"available":"100","unit":"UNIT"},"afterSalesServices":{"impliedWarranty":{"id":"5640aecb-298c-463e-b786-9dded9ae94dd"},"returnPolicy":{"id":"e357b775-e65d-4872-adc8-96976c278bf5"},"warranty":{"id":"e4d95e66-83dd-4f60-b5a0-16a9ed1e3727"}},"productSet":[{"product":{"name":"DOZOWNIK R\u0118CZNY \u0141AZIENKOWY DO P\u0141YNU DO MYD\u0141A SZAMPONU \u015aCIENNY 200ml","category":{"id":"105334"},"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"parameters":[{"id":"248811","valuesIds":["248811_958954"],"values":null,"rangeValue":null},{"id":"11527","valuesIds":["11527_1"],"values":null,"rangeValue":null},{"id":"11528","valuesIds":["11528_1"],"values":null,"rangeValue":null},{"id":"11530","valuesIds":null,"values":["200"],"rangeValue":null},{"id":"224017","valuesIds":null,"values":["H17982S"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["0792172835251"],"rangeValue":null},{"id":"223333","valuesIds":null,"values":["7"],"rangeValue":null},{"id":"223329","valuesIds":null,"values":["20.5"],"rangeValue":null}]}}]}

dostaję zwrotkę:
{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Request contains invalid data. Contact the application author.","metadata":{}}]}

**Comment by MartaNowaczyk** [comment]
Problemem z tego co widzę jest opis. Jak widać na pierwszy rzut oka masz pełno tagów zamykających </p> ale otwierających już nie. Masz też tam nadmiarowe pole "radio":"1" itp. 
To jak powinien wyglądać prawidłowy opis znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty#jak-dodac-opis-oferty).

**Comment by mesia2010** [comment]
Próbowałem wielu rzeczy, filtrowałem tagi html i nadal nie działa
{"name":"DOZOWNIK RĘCZNY ŁAZIENKOWY DO PŁYNU DO MYDŁA SZAMPONU ŚCIENNY 200ml","category":{"id":"105334"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":null},{"id":"229205","valuesIds":["229205_340245"],"values":null}],"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"description":{"sections":[{"items":[{"type":"TEXT","content":"Ręczny dozownik mydła do rąk do montażu na ścianie podwójny szampon w płynie dozownik żelu pod prysznic środek do mycia rąk dozownik balsamu do toalety do łazienki toaleta hotelowa 200mlx2"}]},{"items":[{"type":"TEXT","content":"Cecha:1. Podwójny dozownik mydła, trwały i elegancki.2. Doskonały do mydeł w płynie, żeli pod prysznic, szamponów itp.3. Wyeliminuj bałagan w butelce pod prysznic i pożegnaj się z niechlujnymi butelkami po balsamie."},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986"}]},{"items":[{"type":"TEXT","content":"Dane techniczne:Kolor: srebrnyMateriał: ABSTyp głowicy pompy: cieczDawkowanie: około 0,9-1,0 mlKorzystanie z trybu: NaciśnijInstalacja: Montaż na ścianiePojemność: 200 ml * 2Zastosowanie: komercyjne, domowe, hotelowe, biurowe, szkolne, bankowe, szpitalne, barowe itp.Waga przedmiotu: ok. 340 g \/ 11,99 uncjiRozmiar przedmiotu: ok. 130 * 53 * 198 mm \/ 5,12 * 2,09 * 7,80 cala (dł. * szer. * wys.)Waga opakowania: ok. 416 g \/ 14,67 uncjiRozmiar opakowania: ok. 20,5 * 13,5 * 7 cm \/ 8,07 * 5,31 * 2,76 cala (dł. * szer. * wys.)"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]},{"items":[{"type":"TEXT","content":"Lista pakietów:1 * ręczny dozownik mydła4 * Śruba4 * wąż2 * klucz1 * naklejka na etykietę"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]}]},"language":"pl-PL","payments":{"invoice":"NO_INVOICE"},"external":{"id":"H17982S"},"location":{"countryCode":"DE","province":"Niemcy","city":"Brema","postCode":"64546"},"sellingMode":{"format":"BUY_NOW","price":{"amount":108.49,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"373a6ace-2436-4bb5-bb3c-1e711c7cafa4"},"handlingTime":"P2D","additionalInfo":null,"shipmentDate":null},"stock":{"available":"100","unit":"UNIT"},"afterSalesServices":{"impliedWarranty":{"id":"5640aecb-298c-463e-b786-9dded9ae94dd"},"returnPolicy":{"id":"e357b775-e65d-4872-adc8-96976c278bf5"},"warranty":{"id":"e4d95e66-83dd-4f60-b5a0-16a9ed1e3727"}},"productSet":[{"product":{"name":"DOZOWNIK RĘCZNY ŁAZIENKOWY DO PŁYNU DO MYDŁA SZAMPONU ŚCIENNY 200ml","category":{"id":"105334"},"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"parameters":[{"id":"248811","valuesIds":["248811_958954"],"values":null,"rangeValue":null},{"id":"11527","valuesIds":["11527_1"],"values":null,"rangeValue":null},{"id":"11528","valuesIds":["11528_1"],"values":null,"rangeValue":null},{"id":"11530","valuesIds":null,"values":["200"],"rangeValue":null},{"id":"224017","valuesIds":null,"values":["H17982S"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["0792172835251"],"rangeValue":null},{"id":"223333","valuesIds":null,"values":["7"],"rangeValue":null},{"id":"223329","valuesIds":null,"values":["20.5"],"rangeValue":null}]}}]}

**Comment by Lukasz-Zurek** [comment]
Z opisu w "description" wynika, że treści w "content" nie zamieszczasz w tagach, zgodnie z naszym [tutorialem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty#jak-dodac-opis-oferty). 

Czy próbowałeś korzystać z naszej biblioteki, która konwertuje opis produktu i oferty do formatu wspieranego przez Allegro REST API? Informowaliśmy o tym [tutaj](https://developer.allegro.pl/news/udostepnilismy-biblioteke-ktora-konwertuje-opis-produktu-i-oferty-do-formatu-wspieranego-przez-allegro-rest-api-K63rbow3nS1).

Niemniej jednak nie przyjmiemy opisu w formie czystego tekstu, bez wpięcia go przynajmniej w <p></p>.

**Comment by mesia2010** [comment]
Witaj, wspomniana biblioteka opisów konwersji jest używana w front-end strony internetowej, podczas gdy opis i inne przesłane treści są generowane z back-endu.
Ponadto wypróbowałem również następujące metody żądania, ale nadal wyświetla się pytanie: Żądanie zawiera nieprawidłowe dane. Możesz mi pomóc jeszcze raz spojrzeć? Dziękuję za pomoc!

1. Parametr żądania zawiera tylko tagi HTML<p>i usuwa nieprawidłowe tagi<p>bez zawartości
{"name":"DOZOWNIK RĘCZNY ŁAZIENKOWY DO PŁYNU DO MYDŁA SZAMPONU ŚCIENNY 200ml","category":{"id":"105334"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":null},{"id":"229205","valuesIds":["229205_340245"],"values":null}],"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Ręczny dozownik mydła do rąk do montażu na ścianie podwójny szampon w płynie dozownik żelu pod prysznic środek do mycia rąk dozownik balsamu do toalety do łazienki toaleta hotelowa 200mlx2 <\/p>"}]},{"items":[{"type":"TEXT","content":"<p>Cecha: <\/p><p>1. Podwójny dozownik mydła, trwały i elegancki. <\/p><p>2. Doskonały do mydeł w płynie, żeli pod prysznic, szamponów itp. <\/p><p>3. Wyeliminuj bałagan w butelce pod prysznic i pożegnaj się z niechlujnymi butelkami po balsamie. <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986"}]},{"items":[{"type":"TEXT","content":"<p>Dane techniczne: <\/p><p>Kolor: srebrny <\/p><p>Materiał: ABS <\/p><p>Typ głowicy pompy: ciecz <\/p><p>Dawkowanie: około 0,9-1,0 ml <\/p><p>Korzystanie z trybu: Naciśnij <\/p><p>Instalacja: Montaż na ścianie <\/p><p>Pojemność: 200 ml * 2 <\/p><p>Zastosowanie: komercyjne, domowe, hotelowe, biurowe, szkolne, bankowe, szpitalne, barowe itp. <\/p><p>Waga przedmiotu: ok. 340 g \/ 11,99 uncji <\/p><p>Rozmiar przedmiotu: ok. 130 * 53 * 198 mm \/ 5,12 * 2,09 * 7,80 cala (dł. * szer. * wys.) <\/p><p>Waga opakowania: ok. 416 g \/ 14,67 uncji <\/p><p>Rozmiar opakowania: ok. 20,5 * 13,5 * 7 cm \/ 8,07 * 5,31 * 2,76 cala (dł. * szer. * wys.) <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]},{"items":[{"type":"TEXT","content":"<p>Lista pakietów: <\/p><p>1 * ręczny dozownik mydła <\/p><p>4 * Śruba <\/p><p>4 * wąż <\/p><p>2 * klucz <\/p><p>1 * naklejka na etykietę <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]}]},"language":"pl-PL","payments":{"invoice":"NO_INVOICE"},"external":{"id":"H17982S"},"location":{"countryCode":"DE","province":"Niemcy","city":"Brema","postCode":"64546"},"sellingMode":{"format":"BUY_NOW","price":{"amount":108.49,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"373a6ace-2436-4bb5-bb3c-1e711c7cafa4"},"handlingTime":"P2D","additionalInfo":null,"shipmentDate":null},"stock":{"available":"100","unit":"UNIT"},"afterSalesServices":{"impliedWarranty":{"id":"5640aecb-298c-463e-b786-9dded9ae94dd"},"returnPolicy":{"id":"e357b775-e65d-4872-adc8-96976c278bf5"},"warranty":{"id":"e4d95e66-83dd-4f60-b5a0-16a9ed1e3727"}},"productSet":[{"product":{"name":"DOZOWNIK RĘCZNY ŁAZIENKOWY DO PŁYNU DO MYDŁA SZAMPONU ŚCIENNY 200ml","category":{"id":"105334"},"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"parameters":[{"id":"248811","valuesIds":["248811_958954"],"values":null,"rangeValue":null},{"id":"11527","valuesIds":["11527_1"],"values":null,"rangeValue":null},{"id":"11528","valuesIds":["11528_1"],"values":null,"rangeValue":null},{"id":"11530","valuesIds":null,"values":["200"],"rangeValue":null},{"id":"224017","valuesIds":null,"values":["H17982S"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["0792172835251"],"rangeValue":null},{"id":"223333","valuesIds":null,"values":["7"],"rangeValue":null},{"id":"223329","valuesIds":null,"values":["20.5"],"rangeValue":null}]}}]}

2. Parametry żądania zawierające Unicode. 
{"name":"DOZOWNIK R\u0118CZNY \u0141AZIENKOWY DO P\u0141YNU DO MYD\u0141A SZAMPONU \u015aCIENNY 200ml","category":{"id":"105334"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":null},{"id":"229205","valuesIds":["229205_340245"],"values":null}],"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>R\u0119czny dozownik myd\u0142a do r\u0105k do monta\u017cu na \u015bcianie podw\u00f3jny szampon w p\u0142ynie dozownik \u017celu pod prysznic \u015brodek do mycia r\u0105k dozownik balsamu do toalety do \u0142azienki toaleta hotelowa 200mlx2 <\/p>"}]},{"items":[{"type":"TEXT","content":"<p>Cecha: <\/p><p>1. Podw\u00f3jny dozownik myd\u0142a, trwa\u0142y i elegancki. <\/p><p>2. Doskona\u0142y do myde\u0142 w p\u0142ynie, \u017celi pod prysznic, szampon\u00f3w itp. <\/p><p>3. Wyeliminuj ba\u0142agan w butelce pod prysznic i po\u017cegnaj si\u0119 z niechlujnymi butelkami po balsamie. <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986"}]},{"items":[{"type":"TEXT","content":"<p>Dane techniczne: <\/p><p>Kolor: srebrny <\/p><p>Materia\u0142: ABS <\/p><p>Typ g\u0142owicy pompy: ciecz <\/p><p>Dawkowanie: oko\u0142o 0,9-1,0 ml <\/p><p>Korzystanie z trybu: Naci\u015bnij <\/p><p>Instalacja: Monta\u017c na \u015bcianie <\/p><p>Pojemno\u015b\u0107: 200 ml * 2 <\/p><p>Zastosowanie: komercyjne, domowe, hotelowe, biurowe, szkolne, bankowe, szpitalne, barowe itp. <\/p><p>Waga przedmiotu: ok. 340 g \/ 11,99 uncji <\/p><p>Rozmiar przedmiotu: ok. 130 * 53 * 198 mm \/ 5,12 * 2,09 * 7,80 cala (d\u0142. * szer. * wys.) <\/p><p>Waga opakowania: ok. 416 g \/ 14,67 uncji <\/p><p>Rozmiar opakowania: ok. 20,5 * 13,5 * 7 cm \/ 8,07 * 5,31 * 2,76 cala (d\u0142. * szer. * wys.) <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]},{"items":[{"type":"TEXT","content":"<p>Lista pakiet\u00f3w: <\/p><p>1 * r\u0119czny dozownik myd\u0142a <\/p><p>4 * \u015aruba <\/p><p>4 * w\u0105\u017c <\/p><p>2 * klucz <\/p><p>1 * naklejka na etykiet\u0119 <\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb"}]}]},"language":"pl-PL","payments":{"invoice":"NO_INVOICE"},"external":{"id":"H17982S"},"location":{"countryCode":"DE","province":"Niemcy","city":"Brema","postCode":"64546"},"sellingMode":{"format":"BUY_NOW","price":{"amount":108.49,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"373a6ace-2436-4bb5-bb3c-1e711c7cafa4"},"handlingTime":"P2D","additionalInfo":null,"shipmentDate":null},"stock":{"available":"100","unit":"UNIT"},"afterSalesServices":{"impliedWarranty":{"id":"5640aecb-298c-463e-b786-9dded9ae94dd"},"returnPolicy":{"id":"e357b775-e65d-4872-adc8-96976c278bf5"},"warranty":{"id":"e4d95e66-83dd-4f60-b5a0-16a9ed1e3727"}},"productSet":[{"product":{"name":"DOZOWNIK R\u0118CZNY \u0141AZIENKOWY DO P\u0141YNU DO MYD\u0141A SZAMPONU \u015aCIENNY 200ml","category":{"id":"105334"},"images":["https:\/\/a.allegroimg.com\/original\/11b39c\/93b44e70406d9bfa74fb70ae13bb","https:\/\/a.allegroimg.com\/original\/1160d0\/1a86128e4a0cad9088b5fe8408c1","https:\/\/a.allegroimg.com\/original\/113a24\/671a8ed444858e4ece2ccc766986","https:\/\/a.allegroimg.com\/original\/11cb4a\/463f34b7404a8476c309a60a6691","https:\/\/a.allegroimg.com\/original\/116f5d\/50011f3f4a9cabe1d0185aab35b7","https:\/\/a.allegroimg.com\/original\/115f90\/15c11dc841458108367567e638a3","https:\/\/a.allegroimg.com\/original\/11a9d5\/6ac6de354ad2abf68fcb809260f6"],"parameters":[{"id":"248811","valuesIds":["248811_958954"],"values":null,"rangeValue":null},{"id":"11527","valuesIds":["11527_1"],"values":null,"rangeValue":null},{"id":"11528","valuesIds":["11528_1"],"values":null,"rangeValue":null},{"id":"11530","valuesIds":null,"values":["200"],"rangeValue":null},{"id":"224017","valuesIds":null,"values":["H17982S"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["0792172835251"],"rangeValue":null},{"id":"223333","valuesIds":null,"values":["7"],"rangeValue":null},{"id":"223329","valuesIds":null,"values":["20.5"],"rangeValue":null}]}}]}

**Comment by lipin529** [comment]
Witaj, wspomniana biblioteka opisów konwersji jest używana w front-end strony internetowej, podczas gdy opis i inne przesłane treści są generowane z back-endu.
Ponadto wypróbowałem również następujące metody żądania, ale nadal wyświetla się pytanie: Żądanie zawiera nieprawidłowe dane. Możesz mi pomóc jeszcze raz spojrzeć? Dziękuję za pomoc!
[Uploading allegro创建offer请求参数.txt…]()


Dołączyłem format parametru do załącznika

**Comment by lipin529** [comment]
[allegro创建offer请求参数.txt](https://github.com/user-attachments/files/17536834/allegro.offer.txt)

Format opisu wklejonego bezpośrednio powyżej jest nieprawidłowy. Proszę zapoznać się z załączonym dokumentem

**Comment by Lukasz-Zurek** [comment]
@mesia2010 @lipin529 Z tego co widzę - nadal brakuje tagów otwierających <p> praktycznie w każdej linii tekstu. Kwestia ich przekazywania i generalnie dostosowania opisu do naszych standardów - leży w Waszej gestii. Nasz system nie przyjmie takiego żądania, zwracając błąd j.w.

**Comment by lipin529** [comment]
Przesłane dane zawierają nieobsługiwane atrybuty. Witaj, czy możesz mi pomóc sprawdzić ten błąd? Interfejs nie zwraca określonego atrybutu, który nie jest obsługiwany

[allegro创建offer请求参数.txt](https://github.com/user-attachments/files/17550847/allegro.offer.txt)
