### ISSUE TITLE
Nowe zasady walidacji pól - brak szczegółów lokalizacji pola

### ISSUE THREAD

**Issue by blauweb** [allegro/allegro-api#10155]
Dzień dobry,

Po nowej zmianie, sczegóły na temat występujących błędów są zbyt lakoniczne. Są wymienione pola, ale nie jest wskazane w którym obiekcie, którym ciągu.
Proszę o pomoc w określeniu, w których miejscah znajdują się niewłaściwe parametry:
![image](https://github.com/user-attachments/assets/cb139629-0317-4598-9029-3479b4907665)

Pole 'tax' widać na screenie. Ale gdzie znajdują się błędne pola "type' i 'id' - wiele parametrów wymaga takich pól.

Konto: lewian.pl

**Comment by MartaNowaczyk** [comment]
Dzień dobry, zasada jest taka, że przesyłane pola mają być zgodne z dokumentacją. Brak pełnej ścieżki spowodowany jest możliwościami technicznymi. Jeśli mam zweryfikować konkretny przykład podeślij pełen request przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Możesz podać też konkretne trace-id do weryfikacji, ale może to nie być wystarczające we wszystkich przypadkach.

**Comment by blauweb** [comment]
Dzień dobry,Dziękuję za szybką odpowiedź.Ja wiem jaka jest zasada - problem nie jest w zasadzie, tylko sposobie zwracania informacji o błędzie.Brak pełnej ścieżki nie jest spowodowany przez brak możliwości technicznych, tylko przez źle napisany kod. Ta sama rekursywna funkcja co wrzuca niezgodne pola do zwykłej tablicy, powinna po prostu tworzyć zagnieżdżone tablice z parami klucz->wartość i zwracać taką tablicę. Wówczas każdy zespół będzię mógł sam odnaleźć po błędzie, gdzie ma niepożądane pola i nie będzie musiał wam zawracać głowy ani marnować czasu na pisanie takich postów.Jest to waszym interesie.Gdzie mogę zgłosić taką poprawkę?Co do mojego problemu, wyślę zapytanie przez formularz.Dziękuję.Wysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: MartaNowaczyk ***@***.***> Data: 24.10.2024  06:50  (GMT+01:00) Do: allegro/allegro-api ***@***.***> DW: Blaubit ***@***.***>, Author ***@***.***> Temat: Re: [allegro/allegro-api] Nowe zasady walidacji pól - brak szczegółów lokalizacji pola (Issue #10155) 
Dzień dobry, zasada jest taka, że przesyłane pola mają być zgodne z dokumentacją. Brak pełnej ścieżki spowodowany jest możliwościami technicznymi. Jeśli mam zweryfikować konkretny przykład podeślij pełen request przez formularz kontaktowy. Możesz podać też konkretne trace-id do weryfikacji, ale może to nie być wystarczające we wszystkich przypadkach.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, dziękujemy za podpowiedzi, jednak w tej chwili jest tylko taka możliwość, więc z takiej trzeba korzystać. Tak jak pisałam można przesłać pełen request do weryfikacji, wtedy postaram się pomóc w odszukaniu nadmiarowych pól.

**Comment by blauweb** [comment]
Można zamknąć to zapytanie. Myślę, że obecnie wprowadzone zmiany u nas powinny wyłapać wadliwe pola. Jeżeli jednak tak nie będzie to zgłosimy się ponownie. Jako, że mechanizm raz zaskakuje, a raz nie, to nawet nie jesteśmy w stanie zweryfikować teraz, bo wszystko obecnie przechodzi. Dziękuję i pozdrawiam!
