### ISSUE TITLE
HTTP 413 Request Entity Too Large

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1015]
Przy wysyłaniu requestów na zasób `/sale/offers`, dla trzech requestów o rozmiarach 43963, 45739, 55397, otrzymuję powyższy błąd (tekst błędu _Payload Too Large_)

Nie znalazłem w dokumentacji jaki jest limit rozmiaru dla requestu, ale to raczej nie jest limit na request, tylko limit na rozmiar atrybutu `description`, który w tych trzech requestach mam przekroczony.

Jaki jest zatem limit na rozmiar atrybutu `description` dla zasobu `sale/offers`?

**Comment by PawelTaberski** [comment]
Mamy ograniczenie opisu do 40960 znaków na całego JSONa z opisem, a także do 100 sekcji, dlatego otrzymujesz taki błąd.

**Comment by mindc** [comment]
Dzięki, wszystko jasne.

**Comment by PawelTaberski** [comment]
@mindc Jeszce tylko chciałem doprecyzować limit to dokładnie 40960 bajtów bo niektóre znaki mogą być przechowywane w więcej niż 1 bajcie.

**Comment by PhotoSoft** [comment]
Proszę poprawić treść komunikatu, aby była zrozumiała dla użytkownika zamiast _Payload Too Large_, które nie wiadomo co oznacza.

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem prośbę o doprecyzowanie tego komunikatu.
