### ISSUE TITLE
Wysyłka za pobraniem

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#10167]
Próbuję nadać przesyłkę za pobraniem 
`{"commandId":"7056069d-b9f4-4345-814b-21ac3efac3e2","input":{"deliveryMethodId":"259b5c7a-9056-4c74-80ec-8bdc50cb0413","sender":{"name":"...","company":"...","streetNumber":"","street":"...","postalCode":"...","city":"...","countryCode":"PL","email":"...","phone":"..."},"receiver":{"name":"...","company":"","street":"... ","streetNumber":"","postalCode":"...","city":"...","countryCode":"PL","email":"z3oz3pa6dx+79dbc2757@allegromail.pl","phone":"..."},"referenceNumber":175731,"description":"","packages":[{"type":"PACKAGE","length":{"value":"30","unit":"CENTIMETER"},"width":{"value":"30","unit":"CENTIMETER"},"height":{"value":"30","unit":"CENTIMETER"},"weight":{"value":"2.3","unit":"KILOGRAMS"}}],"labelFormat":"PDF"},"cashOnDelivery":{"amount":"124.5","currency":"PLN"}}`

W odpowiedzi dostaję 

> COD_DATA_REQUIRED
> This delivery option requires data for payment on delivery

Tylko że wysyłam dane o pobraniu `"cashOnDelivery":{"amount":"124.5","currency":"PLN"}`
Są uzupełnione pola wymagane.

W czym tu może być problem?

**Comment by PrzemyslawLukanowski** [comment]
Zwróć proszę uwagę, że pole `"cashOnDelivery"` przekazałeś poza obiektem `"input"`. Jeśli osadzisz je w nim, problem ustąpi.
