### ISSUE TITLE
[sandbox]strona nieosiągalna przy przejsciu do strony wystaw produkt

### ISSUE THREAD

**Issue by darkiteye** [allegro/allegro-api#10168]
Witam, 
allegrosandbox przy wejściu w
  //sprzedaż/wystaw produkt   
Wyskakuje komunikat "strona jest nieosiągalna."
Konto założone 25.10.2024
nazwa:         testSklepOptima
email:         krissit@wp.pl

**Comment by PrzemyslawLukanowski** [comment]
Czy problem w dalszym ciągu występuje. Z mojej strony nie udało się powtórzyć tego błędu. Jeśli tak, prześlij proszę zrzut ekranu wraz z tym, co zwraca konsola.

**Comment by darkiteye** [comment]
Problem w dalszym ciągu niestety wystepuje. Załączam zrzut ekranu.

<img width="960" alt="sandbox_allegro_p" src="https://github.com/user-attachments/assets/9a679c68-3d2c-4b12-943d-3ff3946d7908">

**Comment by darkiteye** [comment]
Czy mógłbym prosić o aktywowanie nowego konta firmowego?  nazwa: krissit   
     
      
       
        Dnia 25 października 2024 14:27 PrzemyslawLukanowski ***@***.***&gt; napisał(a):
       
    
       
         
 Problem może wynikać z tego, że posiadasz konto zwykłe. Możesz spróbować skorzystać z linku  allegro.pl.allegrosandbox.pl https://allegro.pl.allegrosandbox.pl/offer/  , jeśli jednak zostaniesz przekierowany, wymagana będzie zmiana konta na firmowe. Zrobisz to w zakładce Dane Konta. Możesz również utworzyć nowe konto, a obecne zostawiać jako drugie - jako kupującego.

**Comment by PrzemyslawLukanowski** [comment]
Jasne, aktywowałem Twoje konto.

**Comment by darkiteye** [comment]
Działa
