### ISSUE TITLE
[Pytanie] Możliwość wykorzystania REST dla aplikacji na własny użytek

### ISSUE THREAD

**Issue by ThatKidMike** [allegro/allegro-api#1016]
Witam! 

Ciężko mi było znaleźć coś na ten temat na stronie API, więc zapytam tutaj. Czy istnieje możliwość uzyskania dostępu do API na potrzeby własne? Chciałbym (w ramach praktyki poniekąd i dla własnej wygody - jeśli uda mi się zrobić to, co planuję) opracować prostą aplikację, która po przyjęciu linku do danej aukcji (oferty) - zapisze lokalnie dane o niej, tj. tytuł aukcji, czas do końca oraz aktualną cenę - aby można było mieć stały podgląd wytypowanych ofert na desktopie. Coś jak obserwowanie aukcji, ale w formie aplikacji. Czy jest to wykonalne z pomocą tego API oraz rozumiem, że wymagałoby to rejestracji tego wszystko - zgodnie z tym: https://developer.allegro.pl/auth/ ?

**Comment by grzegorzjj** [comment]
Heh, Coś takiego napisałem dla siebie jakiś czas temu. Potrzebujesz zarówno Rest API ( lista aukcji z wybranej kategorii ) oraz Allegro Web API ( szczegóły danej konkretnej aukcji ). Jeśli tylko linku ( konkretna jedna aukcja ) to tylko Web API ( na razie, bo potem metoda doGetItemsInfo przejdzie do Rest API ). Web API jest dobrze opisane - poszukaj w necie są przykłady gotowych funkcji.

**Comment by ThatKidMike** [comment]
Dzięki wielkie za odpowiedź. Nie przyglądałem się Web API ani trochę - myślałem, że Rest API ma pełną funkcjonalność. Mimo wszystko - dostęp do Web API również obowiązuje po zarejestrowaniu aplikacji? Wystarczy tylko nazwa, opis i otrzymuję dostęp do API, mając konto na Allegro?

**Comment by PawelTaberski** [comment]
@ThatKidMike  Pamiętaj że nowa aplikacja musi być zgodna z naszym regulaminem https://developer.allegro.pl/rules/
Jeśli chcesz tylko prowadzić testy możesz zawsze utworzyć taką aplikację na naszym[ środowisku testowym](https://developer.allegro.pl/about/#Sandbox).

**Comment by Uriziel01** [comment]
@ThatKidMike Zgadza się, możesz zalogować się do WebApi za pomocą metody `doLoginWithAccessToken` dzięki czemu jeden token działa zarówno do nowego jak i starego api. Powodzenia.

**Comment by grzegorzjj** [comment]
@ThatKidMike Jest to sytuacja nieco przejściowa. Nie jest to wyraźnie napisane, ale zespół Allegro chce przemigrować cały dostęp do zasobów na REST Api. Robi to po kawałku stopniowo dodając nowe zasoby do REST'a i zamykając ich odpowiedniki w WebAPI. Tak, jak napisałem chcąc zrobić własny systemik dziś-jutro musisz tak czy owak nauczyć się obu. Pewnie za rok-póltora będzie już tylko REST, ale to tylko moja zgadywanka.... Potrzebne jest do tego pełne konto na Allegro. W jego ramach udostępnią Ci token do WebAPI oraz tokeny do REST'a.

**Comment by PawelTaberski** [comment]
Dokładnie tak docelowo ma już być tylko REST API o czym staramy się informować jak najszerzej. Na oficjalnej stronie WebAPI widnieje nawet od niedawna spory baner :-). https://allegro.pl/webapi
