### ISSUE TITLE
`Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.` dla `POST sale/offers`

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#1017]
Witam,
czy mogę prosić o sprawdzenie problemu dla zapytań 'POST sale/offers'

Do poniedziałku wszystko działało prawidłowo, teraz jednak każde zapytanie kończy się błędem `Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.` jednak nie dokonywaliśmy żadnych zmian po naszej stronie. 

Przykładowe zapytanie:
`HTTP/1.1 406 Not Acceptable Trace-Id: 313dd24d97bf4e4a`

Dziękuję.

**Comment by PawelTaberski** [comment]
Zmień nagłówki z bety na `application/vnd.allegro.public.v1+json` i powinno być ok o przejściu na public informowaliśmy już jakiś czas temu #652

**Comment by Uriziel01** [comment]
Z naszej strony proszę jedynie o popracowanie nad komunikatami błędów zwracanymi przez serwer, temat zamykam.
