### ISSUE TITLE
UTC Time

### ISSUE THREAD

**Issue by request4t** [allegro/allegro-api#10170]
Witam.

lineItems.boughtAt.lte=2018-07-31T08%3A48%3A14.889Z&lineItems.boughtAt.gte=2018-07-31T08%3A48%3A14.888Z

Proszę o wyjaśnienie co one oznaczają w tym przypadku liczby 888 i 889 przed literą Z.

**Comment by Lukasz-Zurek** [comment]
Wartości te to milisekundy. Wszystkie pola daty i czasu prezentujemy w standardzie [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601). Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#data-i-czas).
