### ISSUE TITLE
Request to API POST /sale/product-offers

### ISSUE THREAD

**Issue by Ciabatos** [allegro/allegro-api#10181]
Witam serdecznie, przesyłając dane nie dostałem w odpowiedzi '"metadata" czy mógłbym się dowiedzieć dlaczego ?
Próbowałem różnych rzeczy ale zgłupiałem, przesyłam dane :

Json :
`{
  "productSet": [
    {
      "product": {
        "name": "BUDKA DOMEK dla psa kota z wikliny (naturalny) OWAL",
        "category": {
          "id": "90045"
        },
        "parameters": [
          {
            "name": "Marka",
            "values": [
              "Wickerland"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Kod producenta",
            "values": [
              "4543"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Rodzaj",
            "values": [
              "budka"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Kolor",
            "values": [
              "odcienie brązowego"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Długość (cm)",
            "values": [
              "60"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Szerokość produktu",
            "values": [
              "30"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "Typ",
            "values": [
              "wolnostojące"
            ],
            "valuesIds": null,
            "rangeValue": null
          },
          {
            "name": "EAN (GTIN)",
            "values": [
              "5907131642275"
            ],
            "valuesIds": null,
            "rangeValue": null
          }
        ],
        "images": [
          "https://wickerland.pl/17553-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
          "https://wickerland.pl/17572-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
          "https://wickerland.pl/17573-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
          "https://wickerland.pl/17574-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
          "https://wickerland.pl/17575-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
        ]
      },
      "quantity": {
        "value": 1
      },
      "responsiblePerson": null
    }
  ],
  "name": "BUDKA DOMEK dla psa kota z wikliny (naturalny) OWAL",
  "category": {
    "id": "90045"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "119.00",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null
  },
  "delivery": {
    "shippingRates": null,
    "handlingTime": "PT48H",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "images": [
    "https://wickerland.pl/17553-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
    "https://wickerland.pl/17572-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
    "https://wickerland.pl/17573-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
    "https://wickerland.pl/17574-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg",
    "https://wickerland.pl/17575-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>SZAFKA Z WIKLINY </b><b>(regał, półka)</b></p>\n<p><b>kolor nautral</b></p>\n<p><b>________________________________</b></p>\n<p><b>Wymiary:</b></p>\n<ul>\n<li>Szerokość: 30 cm</li>\n<li>Długość: 60 cm</li>\n<li>Wysokość: 68 cm</li>\n</ul>\n<p>Wymiary ze względu na ręczne wykonanie mogą wahać się +/- 1 cm</p>\n<p>_______________________________</p>\n<p>Szafka jest ekologiczna i ręcznie wykonana.</p>\n<p>Regał jest wyplatany z taśmy wiklinowej co sprawia że jest on wyjątkowy w każdym calu.</p>"
          },
          {
            "type": "IMAGE",
            "url": "https://wickerland.pl/17553-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://wickerland.pl/17572-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
          },
          {
            "type": "IMAGE",
            "url": "https://wickerland.pl/17573-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://wickerland.pl/17574-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
          },
          {
            "type": "IMAGE",
            "url": "https://wickerland.pl/17575-large_default/budka-domek-dla-psa-kota-z-wikliny-naturalny-owal.jpg"
          }
        ]
      }
    ]
  },
  "additionalMarketplaces": {
    "allegro-sk": {
      "sellingMode": null,
      "publication": {
        "state": "NOT_REQUESTED",
        "refusalReasons": []
      }
    },
    "allegro-cz": {
      "sellingMode": null,
      "publication": {
        "state": "NOT_REQUESTED",
        "refusalReasons": []
      }
    },
    "allegro-business-cz": {
      "sellingMode": null,
      "publication": {
        "state": "NOT_REQUESTED",
        "refusalReasons": []
      }
    }
  },
  "parameters": [
    {
      "id": "11323",
      "name": "Stan",
      "values": [
        "Nowy"
      ],
      "valuesIds": [
        "11323_1"
      ],
      "rangeValue": null
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": null,
    "returnPolicy": null,
    "warranty": null
  },
  "sizeTable": null,
  "contact": null,
  "discounts": {
    "wholesalePriceList": null
  },
  "payments": {
    "invoice": "WITHOUT_VAT"
  },
  "publication": {
    "status": "INACTIVE",
    "duration": null,
    "endedBy": null,
    "endingAt": null,
    "startingAt": null,
    "republish": true,
    "marketplaces": {
      "base": {
        "id": "allegro-pl"
      },
      "additional": []
    }
  },
  "compatibilityList": null,
  "language": "pl-PL",
  "external": null,
  "taxSettings": null,
  "messageToSellerSettings": null,
  "b2b": null,
  "attachments": [],
  "fundraisingCampaign": null,
  "additionalServices": null,
  "stock": {
    "available": 999,
    "unit": "UNIT"
  }
}`

Response :

`{
    "error": [
        {
            "code": "UnknownJSONProperty",
            "message": "Unknown properties found in the request.",
            "details": null,
            "userMessage": "Przesłane dane zawierają nieobsługiwane właściwości. Skontaktuj się z dostawcą oprogramowania."
        }
    ]
}`

**Comment by MaciejFrackowiak** [comment]
W metada zwróciliśmy:
```
metadata={unknownProperties='additionalMarketplaces.allegro-sk.publication, additionalMarketplaces.allegro-cz.publication, additionalMarketplaces.allegro-business-cz.publica..., ...base, ...endedBy, ...endingAt'}
```

**Comment by Ciabatos** [comment]
dziękuję za odpowiedź, chciałbym jeszcze zapytać czy przeglądarka nie zwraca tego błędu z jakiejś przyczyny czy nie obsługuję response błędu poprawnie ?

**Comment by MaciejFrackowiak** [comment]
Konieczne jest sprawdzenie, czy aplikacja z której korzystasz prawidłowo obsługuje pole "metadata" - pole to [dodaliśmy](https://github.com/allegro/allegro-api/issues/9184) w czerwcu 2024, zatem możliwe, że aplikacja nie uwzględnia go w strukturze błędów.

**Comment by Ciabatos** [comment]
Ma Pan absolutna rację tak wygląda kod na ten moment, nie miałem obsłużonego tego pola.

  if (response.status === 422) {
      const errorData = await response.json()
      const errorMessage = errorData.errors.map((err: any) => ({
        code: err.code,
        message: err.message,
        details: err.details,
        userMessage: err.userMessage,
      }))
