### ISSUE TITLE
Lista kodów błędów wraz z ich opisami

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#1018]
Chcemy prezentować użytkownikom bardziej precyzyjne komunikaty o błędach.
Np. code ERR_ITEM_CAN_NOT_BE_RENEW nie jest do końca zrozumiały.
Czy mogę prosić o podesłanie listy w postaci code  - message?
Lub jeśli takiej nie ma, o listę wszystkich kodów błędów które może zwrócić REST?

**Comment by PawelTaberski** [comment]
Pracujemy nad ujednoliceniem i dopracowaniem komunikatów o błędach, a jakie dokładnie Tobie komunikaty rzuciły się w oczy, które są nieprecyzyjne/niejasne .

**Comment by rtnet-pl** [comment]
Np. ten komunikat powyżej, ERR_OBLIGATORY_ATTRIB_NOT_SET, itd.
Przewijają się w różnych miejscach, dlatego przydałaby się kompletna lista lub zasób z którego można by ją pobrać.

**Comment by PawelTaberski** [comment]
Bardzo dziękuję za informacje, oczywiście rozumiem i tak, jak mówiłem pracujemy nad ujednoliceniem i dopracowaniem komunikatów i docelowo również udostępnieniu takiej listy.
