### ISSUE TITLE
Aktywacja kont

### ISSUE THREAD

**Issue by fzdunek** [allegro/allegro-api#10192]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

dzień dobry,
prośba o aktywowanie dwóch kont, ponieważ pomimo ustalenia testowej płatności pozostają nieaktywne:
partsmanager oraz partsclient

**Comment by MaciejFrackowiak** [comment]
"partsmanager" jest już aktywne. Natomiast "partsclient" nie mogę znaleźć w bazie - czy potwierdziłeś rejestrację tego konta?

**Comment by fzdunek** [comment]
@MaciejFrackowiak kliknąłem raz jeszcze w linki, wcześniejsza nazwa konta to była - Client:107463460

**Comment by MaciejFrackowiak** [comment]
I to konto jest już aktywne.

**Comment by fzdunek** [comment]
> I to konto jest już aktywne.

Świetnie, dziękuje
