### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kiczek** [allegro/allegro-api#1019]
WSDL zwraca obecnie:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>SOAP-ENV:Client</faultcode>
<faultstring xml:lang="en">Internal Server Error</faultstring>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by TimothyKoval** [comment]
Komuś nie zeszło jeszcze po wczorajszym ;)

**Comment by magik092** [comment]
Potwierdzam, WSDL dopiero skończył zabawę sylwestrową i poszedł spać :)
Nasze API przez to stoi :/

**Comment by PawelTaberski** [comment]
Rzeczywiście jest jakiś problem, sprawę już zgłosiłem do odpowiedniego zespołu, pracujemy nad rozwiązaniem tego problemu.
