### ISSUE TITLE
Analiza danych sprzedażowych przez API

### ISSUE THREAD

**Issue by BartlomiejCalus** [allegro/allegro-api#10191]
Dzień dobry,
Szukamy możliwości pobierania danych związanych ze sprzedażą w określonych kategoriach (np. pozycja konta względem innych, ilości sprzedanych produktów w naszych kategoriach przez wszystkich sprzedawców).
Czy przez Wasze API możemy pobierać informacje, którymi jesteśmy zainteresowani?

**Comment by MaciejFrackowiak** [comment]
Nie, nie udostępniamy zasobów, którymi możnaby uzyskać opisane dane.

**Comment by BartlomiejCalus** [comment]
Dziękuję za odpowiedź
