### ISSUE TITLE
Problem z usuwaniem przesyłek po anulowaniu poprzez API Allegro

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#10196]
Korzystam z endpointu `https://api.allegro.pl/shipment-management/shipments/cancel-commands` i wysyłam na niego następujące dane:

```json
{
  "headers": {
    "Authorization": "Bearer [wyciete]",
    "Accept-Language": "pl-PL",
    "Accept": "application/vnd.allegro.public.v1+json",
    "Content-Type": "application/vnd.allegro.public.v1+json"
  },
  "json": {
    "input": {
      "shipmentId": "SU5QT1NUOjYyMDAyMjY5NjQwODQzMDExOTQ1ODQwOA=="
    }
  }
}
```

W odpowiedzi otrzymuję np.:

```json
{
  "commandId": "5ca9cdc0-25bd-42a7-9f95-2a16a8008981",
  "input": {
    "shipmentId": "SU5QT1NUOjYyMDAyMjY5NjQwODQzMDExOTQ1ODQwOA=="
  }
}
```

Wygląda na to, że zapytanie zostało poprawnie przetworzone i otrzymuję `commandId` do śledzenia postępu wykonania polecenia.

Niestety, nawet po czasie w Menedżerze Zamówień ([link do zamówienia](https://salescenter.allegro.com/orders/?marketplaceLogin=uts-gsm&query=dea939d0-96a4-11ef-a2e1-8b883a23b473)) widnieją nadal przesyłki, które zostały w ten sposób anulowane.

Dlaczego te przesyłki nie zostają usunięte z zamówienia?

Naszym celem jest anulowanie przesyłek oraz usunięcie informacji o nich z zamówienia.

**Comment by Lukasz-Zurek** [comment]
@studiowizjo Zgłosiłem ten temat do zespołu WZA. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@studiowizjo Anulowanie przesyłki w ramach "Wysyłam z Allegro" nie ma wpływu na odpięcie/usunięcie przesyłki z zamówienia. W tym przypadku po prostu nie usuwamy anulowanych przesyłek. Jednocześnie nie można wykonać już dla nich żadnych dodatkowych operacji, np. wygenerować etykietę, itp. Anulowanie samo w sobie zostało zrealizowane prawidłowo.

**Comment by studiowizjo** [comment]
Czy jest w takim razie mozliwosc w jakis sposob usuniecia przez API tych informacji o numerach przesylek?

**Comment by Lukasz-Zurek** [comment]
@studiowizjo Niestety nie.

**Comment by studiowizjo** [comment]
Z poziomu interfejsu samego Allegro jest jednak taka mozliwosc. Z czego wynika roznica, ze przez API taka funkcjonalnosc nie jest osiagalna?

**Comment by Lukasz-Zurek** [comment]
@studiowizjo Trudno wskazać tutaj konkretną przyczynę dlaczego takiej funkcjonalności nie ma w API. Mogę jedynie zachęcić do przekazania nam sugestii udostępnienia takiej opcji/zasobu, za pośrednictwem zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).
