### ISSUE TITLE
cennik sklepowy / oferta zwykła

### ISSUE THREAD

**Issue by kudel** [allegro/allegro-api#102]
Czy przez API można określić jakimś parametrem, czy wystawiana oferta ma być 'zwykła' czy 'sklepowa'?
Nie widzę w dokumentacji takiego pola, nic też nie pojawia się nowego w zwrotce z metody doGetSellFormFieldsForCategory.

Obecnie wszystkie oferty, które dodajemy przez API określane są jako 'zwykłe'.

**Comment by KrzysztofLukanowski** [comment]
Tak, możesz to zrobić w FID 29 metody [doNewAuctionExt](https://allegro.pl/webapi/documentation.php/show/id,113) przypisując wartość 1. Informację o tym możesz otrzymać w odpowiedzi metody [doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782).

**Comment by kudel** [comment]
Uściślając, proszę o informację czy dobrze rozumiem:
Format sprzedaży - 0|1|2 -> Tylko Kup Teraz! (bez licytacji) lub Licytacja|Sklep (bez licytacji)|Ogłoszenie

- 0 - zwykła oferta (obowiązuje Cennik Allegro)
- 1 - oferta sklepowa (obowiązuje Cennik Sklepów Allegro)
- 2 - ogłoszenie

?

p.s. 
Kiedy stosujemy 2 - ogłoszenie?

**Comment by KrzysztofLukanowski** [comment]
ok, uściślam ;) 

- 1 - stosujesz wtedy, gdy korzystasz z [abonamentu sklepowego](https://allegro.pl/myaccount/Subscriptions.php#/),
- 2 -  ma zastosowanie dla ofert, które mają format ogłoszenia (wtedy jest nieco inny zestaw FIDów). Przeczytaj nasz tutorial [Jak zarządzać ogłoszeniami w WebAPI](https://allegro.pl/webapi/tutorials.php/tutorial/id,100461).

**Comment by kudel** [comment]
OK, dzięki za info.
