### ISSUE TITLE
Internal server error - przy każdym wywołaniu API

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#1020]
Od ok. 20 minut. https://webapi.allegro.pl/uploader.php
<faultstring xml:lang="en">Internal Server Error</faultstring>

**Comment by PawelTaberski** [comment]
Zgodnie z #1019 
"Rzeczywiście jest jakiś problem, sprawę już zgłosiłem do odpowiedniego zespołu, pracujemy nad rozwiązaniem tego problemu."
