### ISSUE TITLE
Pole etag w headerze odpowiedzi zdjęcia 

### ISSUE THREAD

**Issue by KaMisza** [allegro/allegro-api#10219]
Przykładowo dla https://a.allegroimg.com/original/11d137/46e13b944008807fe27fae41608e 
w headerze otrzymujemy etag bcbb3570baae1d7b53ada2f10a72064d 

co dokładnie oznacza etag i za co odpowiada?

**Comment by MaciejFrackowiak** [comment]
Jest to identyfikator zasobu, dzięki czemu mamy możliwość rozpoznać, czy podczas kolejnego uploadu tego samego zdjęcia otrzymaliśmy te same dane wejściowe. [Tu](https://en.wikipedia.org/wiki/HTTP_ETag) przykładowe wyjaśnienie.
