### ISSUE TITLE
/pricing/offer-quotes zwraca nieprawidłowe dane

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#1022]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Czemu endpoint /pricing/offer-quotes zwraca dane:

```
"quotes": [{
	"type": "EMPHASIZED",
	"name": "Wyróżnienie",
	"nextDate": "2019-01-09T16:13:14.997Z",
	"fee": {
		"amount": "19.00",
		"currency": "PLN"
	},
	"offer": {
		"id": "7722190761"
	},
	"enabled": true
}, {

...
```

skoro sprzedawca jest zwolniony z tej opłaty?

**Comment by PawelTaberski** [comment]
Ten zasób nie bierze pod uwagę pakietów, jednakże widzę, że masz jeszcze ważny pakiet w tym czasie także opłata nie powinna zostać pobrana.

**Comment by TimothyKoval** [comment]
Czego jeszcze ten zasób nie bierze pod uwagę?

**Comment by PawelTaberski** [comment]
Ten zasób nie może brać pod uwagę pakietów ze względu na sposób ich działania bo pakiet jest zmniejszany wg. kolejności zarejestrowanych opłat na koncie, to oznacza, że nie możemy w 100% być pewni że między podaniem wyceny a zarejestrowaniem faktycznej opłaty jakaś inna oferta nie zużyje pakietu. Bo może Pan w międzyczasie np. wystawić 100 ofert z promowaniem i wyczerpać pakiet przed datą naliczenia kolejnych opłat w ofercie X.

**Comment by TimothyKoval** [comment]
Oczywiście że może. Powinien zwracać 0 do momentu wyczerpania pakietu, po tym fakcie powinien zwracać odpowiednią kwotę.

Wskazuje to na fakt, iż mechanizm działania tej metody jest niezależny od mechanizmu faktycznego naliczania opłat, co prędzej czy później doprowadzi do rozbieżności i błędów. To sprawia, że zasób jest bezużyteczny, ponieważ - po pierwsze primo - nie można mu ufać, po drugie primo - nie stanowi (jak zakładam) podstaw do roszczeń.

**Comment by TimothyKoval** [comment]
A tak poza tym, skoro pakiet jest ilościowy a nie czasowy, to doskonale wiadomo która oferta spowoduje wyczerpanie pakietu, nieprawdaż?

**Comment by PawelTaberski** [comment]
Tak, jak opisaliśmy ten zasób w dokumentacji z założenia ma on służyć [do sprawdzania daty naliczenia kolejnej opłaty w ofercie](https://developer.allegro.pl/news/2018-07-18-aktualizacja_zasob_do_sprawdzania_daty_oplaty/). Ponadto tak, jak napisałem nie jesteśmy w stanie stwierdzić ze 100% pewnością, czy przykładowo do 9.01 nie wykorzystasz swojego pakietu 100 promowań. W takim wypadku mimo iż w odpowiedzi otrzymałbyś, że nie pobierzemy opłaty faktycznie byśmy ją pobrali bo wykorzystałeś ten pakiet przed pobraniem kolejnej opłaty w tej ofercie o którą odpytywałeś.
