### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by yellowBunnyy** [allegro/allegro-api#10232]
Dlaczego mój token jest niewłaściwy ???
![image](https://github.com/user-attachments/assets/2859dae5-b5ac-4bcc-881a-801836a6505d)
![image](https://github.com/user-attachments/assets/4576103c-6721-428b-b6d7-a921673abcfa)
![image](https://github.com/user-attachments/assets/70a193d3-0739-4f44-ba75-544171c66493)
Scope
![image](https://github.com/user-attachments/assets/52d5fac7-cf31-4c64-9ec6-8482b087d7d4)
Posługuję się waszym snippetem:
![image](https://github.com/user-attachments/assets/d9aa07a1-1386-46b7-ac02-c794adfd1d8f)

**Comment by MartaNowaczyk** [comment]
Sprawdź czy czasem nie używasz tokena ze środowiska testowego na produkcyjnym.

**Comment by yellowBunnyy** [comment]
wygenerowane dla 
![image](https://github.com/user-attachments/assets/704b49a4-f9dd-420b-9fe9-ebebe32628ae)
CLIENT_ID oraz CLIENT_SECRET z produkcji (nie sandbox
)

**Comment by yellowBunnyy** [comment]
dobra widzę już XD
