### ISSUE TITLE
Allegro International CZ na środowisku testowym

### ISSUE THREAD

**Issue by sk-cosmo** [allegro/allegro-api#10236]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Jakiś czas temu zakładałem zadanie dot problemu z nadawaniem przesyłek na środowisku testowym: https://github.com/allegro/allegro-api/issues/10104
Zastosowałem się do wskazówek i ostatecznie udało nadać się testowe przesyłki z metodami dostawy Allegro DPD.

Niestety, wciąż mam problem z Allegro International, a konkretniej:

- Allegro International Kurier Czechy
trace-id: e1242602dcf9bdbd
Błąd zewnętrznego przewoźnika

- Allegro International Automaty Paczkowe Czechy
trace-id: e4ca9ce4d66b5706
Błąd zewnętrznego przewoźnika

- Allegro International Odbiór w Punkcie Czechy
trace-id: 763df3803fae3586
Błąd zewnętrznego przewoźnika

Proszę o wsparcie w tym temacie oraz o wskazanie przyczyn, dla których otrzymuję wymienione wyżej błędy.
Numer telefonu odbiorcy jest poprawny, tzn zgodny z wymaganiami -> +420700800900

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisany problem, wrócę z informacją.

**Comment by sk-cosmo** [comment]
Czy udało się coś ustalić?

**Comment by MartaNowaczyk** [comment]
Tak, przewoźnik włączył walidację, której wcześniej nie było i w tych przypadkach numer telefonu +420700800900 nadal nie jest prawidłowy. Poza kodem kraju (+420) musi pasować do jednego z nw. regexów:
```
{"prefixes": "(60[345][0-9]{6}|(73[0-9]{7})|(709[0-9]{6}))"}
{"prefixes": "((60[1267][0-9]{6})|(72[0-9]{7})|702[0-9]{6})|792[01345][0-9]{5}"}
{"prefixes": "(608[0-9]{6}|77[0345678][0-9]{6})"}
{"prefixes": "(797[56789][0-9]{5})|70[2345][0-9]{6}|79[0123459][0-9]{6}|77[129][0-9]{6}"}
```

**Comment by sk-cosmo** [comment]
Dziękuję, sprawdzę i wrócę z odpowiedzią.

**Comment by sk-cosmo** [comment]
@MartaNowaczyk 

Po poprawie numeru telefonu jest możliwe nadanie przesyłki, jednak potrzeba na to wielu prób, by się to w końcu udało.
Jeśli występuje błąd, to zazwyczaj jest zwracany błąd o treści:

Przesyłka nie została zamówiona. Przekroczono czas oczekiwania na potwierdzenie zlecenia ze strony przewoźnika. Ponów operację później.

**Comment by MartaNowaczyk** [comment]
W takim wypadku niestety należy ponowić próbę, bo jesteśmy zależni od operatora. Być może w tym dniu były jakieś problemy. Czy dzisiaj np. jest podobnie?

**Comment by sk-cosmo** [comment]
@MartaNowaczyk 

Niestety, dziś jest to samo :/
Mam też nadzieję, że takie problemy nie dotyczą środowiska produkcyjnego.

**Comment by MartaNowaczyk** [comment]
Postaramy się to jeszcze zweryfikowali z operatorem w takim razie. Nie zawsze jest idealnie, ale na produkcji tak to nie wygląda. Chyba, że jest jakaś awaria u operatora, ale to nie przez kilka dni.

**Comment by sk-cosmo** [comment]
@MartaNowaczyk 

Dzień dobry,
czy udało się ten temat zweryfikować z operatorem?

Mam jeszcze dwie prośby:

- czy mogę prosić o podanie adresu do odbioru w punkcie w Allegro International (AWD0286)?
- czy mogę prosić o podanie adresu oraz ID automatu paczkowego Allegro International, który zezwoli na nadanie przesyłki na środowisku testowym? Czy może w tym przypadku nie istnieje takie ograniczenie?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, jeszcze nie, rozumiem, że problem nadal się powtarza? Co do reszty postaram się uzyskać te informacje i wrócę z odpowiedzią.

**Comment by sk-cosmo** [comment]
@MartaNowaczyk 

Na wstępie bardzo dziękuję za przesłanie adresu do punktu AWD0286.

Przez wymagania ma Pani na myśli konkretny punkt odbioru/automatu, tak?
Jak dziś sytuacja wygląda z automatami Allegro International - mogę spróbować wygenerować etykietę na dowolnym automacie?
Oczywiście, mówię tutaj o środowisku testowym :)

**Comment by sk-cosmo** [comment]
@MartaNowaczyk

Czy mogę prosić o odpowiedź w temacie?

**Comment by MartaNowaczyk** [comment]
Etykiety też można generować testowo, mogą się one jednak różnić wyglądem od tych na produkcji. Nie wyślesz jednak fizycznie przesyłki.
Przez wymagania miałam na myśli walidację przez którą widzimy problemy w możliwości testowania tych przesyłek.

**Comment by sk-cosmo** [comment]
@MartaNowaczyk 

Nie chodzi o fizyczną wysyłkę, a wygenerowanie etykiety.

We wcześniejszym zgłoszeniu https://github.com/allegro/allegro-api/issues/10104 otrzymałem informację, że "nie wszystkie punkty są aktywne na środowisku testowym" stąd pytanie, czy w przypadku automatów Allegro International mogę spróbować wygenerować etykietę na dowolnym automacie?

**Comment by MartaNowaczyk** [comment]
Ok, to się nie zrozumieliśmy. Miałam na myśli, na każdym, ale dostępnym na sandbox.
