### ISSUE TITLE
Wrong URL in english documentation 

### ISSUE THREAD

**Issue by fabian-bw** [allegro/allegro-api#1023]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by fabian-bw** [comment]
There is a wrong URL in the documentation:

https://developer.allegro.pl/en/auth/#DeviceFlow

> 1, 2/ Call POST https://allegro.pl/auth/oauth/headless/codes to receive:

should be **https://allegro.pl/auth/oauth/device** like mentioned in the example call below.

**Comment by PawelTaberski** [comment]
You are right in sample response is ok, we will change that in the closest web page update. Thank you for information.

**Comment by PawelTaberski** [comment]
Done
