### ISSUE TITLE
[sandbox] activation

### ISSUE THREAD

**Issue by nysander** [allegro/allegro-api#10248]
Hello, 

how can I remove account from sandbox to be able to create new one or to update seller data to not contain mine personal data?

**Comment by AureliuszBrussy** [comment]
On Sandbox, just as on production, you can withdraw or terminate the contract through the appropriate forms:
- [withdraw](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rozwiazywanie-umowy/wniosek/odstapienie)
- [terminate](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rozwiazywanie-umowy/wniosek/rozwiazanie).

As for changing data, for that, you can use the [Account Details](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) tab.

**Comment by nysander** [comment]
Ok I have terminated old account. Can I ask for approval of new account `MT_Sandbox` ?

**Comment by MaciejFrackowiak** [comment]
@nysander Your account is active now.

**Comment by nysander** [comment]
thank you
