### ISSUE TITLE
[REST-beta] Warianty - niezgodne ilości spiętych przedmiotów ?

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1024]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Poniżej tablica z dostępnymi wariantami ("count":329), a kiedy odpytujemy każdy wariant z osobna wychodzi łącznie już NIE 329, a zaledwie 49 przedmiotów w tych 10 wariantach...

Trace-Id: d9de8b9e3b79663c
034a
{"count":329,"offerVariants":[{"id":"3466275a-a923-4831-ac64-bea0b0ca00de","name":"50 Twarzy Greya zestaw akcesoriów bondage"},{"id":"36cb0d62-fffc-479f-8b0e-b179820c45de","name":"AGAPE"},{"id":"03431289-3506-4ace-9565-4312b5010baa","name":"AQUAGLIDE"},{"id":"803b5f8d-97cb-43c7-943b-2c5005c23ed6","name":"AdultBodyArt Zestaw Tatuaży Erotycznych"},{"id":"1ba322be-6f7b-4e0f-807f-9aca9ac5e326","name":"BACI –SEXY EROTYCZNE stringi"},{"id":"863186a0-8493-427c-9c4c-ba0d5e212f7c","name":"BFILLED"},{"id":"4a86fd93-c2ea-48aa-9f52-d140bbb4e4fe","name":"BIJOUX Cosmetiques olejek do masażu jadalny"},{"id":"b80082fc-b0ab-4acb-a079-7dabcacd89ca","name":"BIJOUX Cosmetiques łańcuszki bez niklu"},{"id":"77a16939-08f5-4be1-9848-3bf5e2ad0b05","name":"BIUSTONOSZE BYE BRA GALA 2"},{"id":"52c793cf-f3b8-4ce4-9792-6d3c2eb45780","name":"BODYWAND"}]}
0

**Comment by PawelTaberski** [comment]
@FromAnyHole  Z defaultu dostajesz 10 ofert wielowariantowych a masz ich na tym koncie aż 329 musisz sterować offsetem, aby przejrzeć wszystkie. Opisaliśmy te parametry w dokumentacji [GET /sale/offer-variants](https://developer.allegro.pl/documentation/#/offer-variants/getVariantSets)

**Comment by FromAnyHole** [comment]
O szlag, rzeczywiście jest OFFSET ! ;-)
Można zamknąć...
