### ISSUE TITLE
sale/offers/ zwraca NotAcceptableException

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#1025]
Występuje problem: 
 - [X] ze środowiskiem produkcyjnym
:beetle: **Opis**
Witam, czy coś zmieniło się w Sylwestrową noc z sale/offers/ ? Używamy tego do pobrania oferty tylko po to, aby ją wznowić... No i lipa, bo nie zmieniając NIC w skryptach dostajemy NotAcceptableException czyli Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji. 

Czy ktoś ma jakiś pomysł co się zmieniło albo co jest przyczyną ? Oczywiście token jest poprawny, bo zmiana cen na tym samym tokenie działa...

**Comment by PawelTaberski** [comment]
Jeśli dostajesz status 406 to problem musi być w nagłówku zapewne musisz zmienić zasób z beta na public i będzie ok.

**Comment by partyumarty** [comment]
Harakiri chyba zaraz popełnię. I przez 3 dni wpiz(*&R^%$& poszło kilkaset aukcji... Dziękuję @PawelTaberski - działa. Przy okazji dopytam - gdzie znaleźć na przyszłość info, że to się zmieniło akurat 31 grudnia oraz... w jakich jeszcze zasobach mam to poprawić, bo gdzieś mi w logach mignęło, że inne skrypty też się wyłożyły...

**Comment by partyumarty** [comment]
OK, moja wina. Najważniejsze, że działa... dziękuję.
