### ISSUE TITLE
Błąd w dokumentacji Order Events

### ISSUE THREAD

**Issue by Atospl** [allegro/allegro-api#1026]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://developer.allegro.pl/documentation/#/order-management/get_order_events

Występuje drobny błąd w dokumentacji zasobu /order/events
Jedno ze zwracanych pól wg dokumentacji zasobu nosi nazwę "occuredAt", podczas gdy serwer zwraca **"occurred**At"

**Comment by PawelTaberski** [comment]
Dzięki za zwrócenie uwagi poprawimy przy najbliższym wdrożeniu.

**Comment by PawelTaberski** [comment]
Poprawione :-)
