### ISSUE TITLE
Pobieranie etykiety do przesyłki

### ISSUE THREAD

**Issue by balandzik** [allegro/allegro-api#10264]
Witajcie, próbuję bezskutecznie pobrać etykietę do przesyłki z API. Przesyłka jest utworzona, widzę jej numer, a z poziomu Sales Center pobiera mi się prawidłowo etykietka do niej. Mam numer zamówienia: 0413f100-a0e7-11ef-94bf-d347e081db06. Wywołuję endpoint: /order/checkout-forms/0413f100-a0e7-11ef-94bf-d347e081db06/shipments. Otrzymuję nr przesyłki: 040ac940-a0e7-11ef-94bf-d347e081db06. Teraz usiłuję pobrać label przez POST /shipment-management/label. Przy wywołaniu jako parametr podaję shipmentIds=040ac940-a0e7-11ef-94bf-d347e081db06. Otrzymuję błąd 404, zamiast pliku PDF.

**Comment by PrzemyslawLukanowski** [comment]
Dzieje się tak, ponieważ wartość, którą otrzymałeś w GET /order/checkout-forms/0413f100-a0e7-11ef-94bf-d347e081db06/shipments nie jest tożsama z wartościami powiązanymi z zasobami z Wysyłam z Allegro. Są to dwa oddzielne, niepowiązane ze sobą endpointy. W ramach POST /shipment-management/label musisz przekazać identyfikator paczki, który otrzymałeś w odpowiedzi [GET /shipment-management/shipments/create-commands/{commandId} ](https://developer.allegro.pl/documentation/#operation/getShipmentCreationStatus), czyli na etapie, gdy sprawdzasz status utworzenia paczki.

<img width="521" alt="Zrzut ekranu 2024-11-12 o 13 40 55" src="https://github.com/user-attachments/assets/af8ce06d-efc8-4fb3-b3ba-03b1a239532f">

**Comment by balandzik** [comment]
OK, dzięki!
