### ISSUE TITLE
Sandbox activation

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#10267]
Hello,

I have recently activated my business account (Client:106138510) on the Allegro Sandbox. If I remember correctly, I need to contact you here to have it fully activated, as it doesn’t happen automatically on sandbox. Please proceed with the activation.

Thank you.

**Comment by PrzemyslawLukanowski** [comment]
Hi, I've activated your account, but please keep in mind that's a regular account. Only on the company account you can list and manage offers via API.

**Comment by DHSC1** [comment]
Hello,

thank you. I thought I was activating a business account, as I need a business account for the API testing connection.
Could you please activate it directly? Is that possible?

**Comment by PrzemyslawLukanowski** [comment]
I've activated the Client:106138510 but this is a regular account, not a business type.

**Comment by DHSC1** [comment]
OK, Thank you. I´ve created another one - MasterBlaster. 
Could you please activate it as a business account?

**Comment by PrzemyslawLukanowski** [comment]
Sure, it should be activated now.
