### ISSUE TITLE
Status odebrania przesyłki

### ISSUE THREAD

**Issue by request4t** [allegro/allegro-api#10270]
Witam!

Przepraszam za litery bez kresek i ogonkow)

Przeczytalem documentacje о przesylkach. Ale trudno...) Raczej zapytam wprost)

Czy jest mozliwe otrzymac status odebrania przesylki?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz śledzić całą drogę przesyłki, zrobisz to za pomocą [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET). Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-historie-statusow-przesylek).

**Comment by request4t** [comment]
Dziekuje.

Pytanie o waybill. Dlia otrzymanina waybill mam wypelnic: GET /shipment-management/shipments/{shipmentId}

Dlia otrzymania shipmentId mam wypelnic GET /shipment-management/shipments/create-commands/{commandId}

Ale nie korzystuje z tego, poniewaz paczki tworza sie recznie. Jak mam dzialac w takiej sytuacji?

**Comment by PrzemyslawLukanowski** [comment]
Tak, zwracamy statusy dla wszystkich przewoźników zintegrowanych z Allegro.

**Comment by request4t** [comment]
Przepraszam, ale nie rozumiem do konca. Sytuacja jest taka, ze manager recznie tworzy przesylke. Otrzymuje waybill, ale do mojej applikacji jego ne wnosi. Moja applikacja nie ma waybillow i zwraca sie do Allegro po statusy. Jak w takim wypadku moge otrzymac statusy?

**Comment by PrzemyslawLukanowski** [comment]
Możesz je otrzymać odpytując [GET /order/carriers/{carrierId}/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getParcelTrackingUsingGET).

**Comment by PrzemyslawLukanowski** [comment]
Natomiast waybill przypisany do zamówienia otrzymasz za pomocą [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation#operation/getOrderShipmentsUsingGET).

**Comment by request4t** [comment]
Dziękuję bardzo)
