### ISSUE TITLE
Integracja z DPD - brakujące transakcje

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#1028]
Witam,

od pewnego czasy korzystam z integracji z DPD.
importuje transakcje przez stronę https://online.dpd.com.pl/import-allegro/

Niestety od kilku dni nie importują się wszystkie transakcje.
Zwłaszcza jest problem z transakcjami z dni poprzednich.

Dzisiaj zaimportuje transakcje z Allegro z dnia dzisiejszego, ale niestety nie wyświetlą się już te z dnia wczorajszego.

Problem po Waszej stronie czy atakować DPD?

**Comment by PawelTaberski** [comment]
Wczoraj mieliśmy awarię Allegro WebAPI pisaliśmy o tym tytaj #1021 jednakże problem został szybko rozwiązany i wszystko wróciło do normy.  W tej sprawie zalecam kontakt z dpd. Jeśli problem występuje już od kilku dni nie jest to spowodowane awarią.
