### ISSUE TITLE
Aktywacja konta - Sandbox

### ISSUE THREAD

**Issue by Xachik-del** [allegro/allegro-api#10280]
WItam, proszę o pomoc i aktywacje konta na Sandboxie, Konto : wowdobra
Czy mogę poprosić aktywować dla konta klienta na sandbox smart? Konto [marek.sznuk@gmail.com](mailto:marek.sznuk@gmail.com)

**Comment by AureliuszBrussy** [comment]
Odpisałem już w wątku #10263.
