### ISSUE TITLE
Payments on Allegro.cz Sandbox Are Not Working

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#10286]
Hello,

Orders are not being created on the Allegro sandbox in the CZ version. Today, I was able to create orders on the PL version. However, on the CZ version, I keep getting "We still don't know if the payment was successful," even in cases where the order is cash on delivery.

Transactions: 5f3aced0-a1ca-11ef-a042-7fc01ee46d42, 13a295b0-a1cb-11ef-a042-7fc01ee46d42

This has been happening throughout the day.

Could you please check this?

![image](https://github.com/user-attachments/assets/a153d531-f195-49d5-b258-20f788a0f8e3)

**Comment by PrzemyslawLukanowski** [comment]
Hello, could you please try to process the payment once again? I was able to make a bank transfer in a random offer.
