### ISSUE TITLE
Problem z tworzeniem przesyłek Allegro Odbiór w Punkcie Pocztex za pobraniem

### ISSUE THREAD

**Issue by szymonkrygier** [allegro/allegro-api#10291]
Mamy problem z tworzeniem przesyłek Allegro Odbiór w Punkcie Pocztex za pobraniem przez API.

Klienci mają możliwość zamawiania z wyborem takiej formy dostawy, natomiast API nie zwraca takiego dostawcy z wartością cashOnDelivery -> available ustawioną na true. Podczas tworzenia przesyłki przez API wyświetla się komunikat, że pobranie nie jest dostepne dla wybranej metody dostawy.

  ```
"service":"POCZTA_POLSKA",
  "name":"Allegro Odbiór w Punkcie Pocztex",
  "owner":"ALLEGRO",
  "carrierId":"POCZTA_POLSKA",
  "additionalServices":{
  
      "cashOnDelivery":{
          "available":false,
          "expressAvailable":false
      }
```

**Comment by MaciejFrackowiak** [comment]
Wspomniana metoda "Allegro Odbiór w Punkcie Pocztex" nie obsługuje pobrania. Dla wersji z pobraniem istnieje osobna metoda dostawy - Allegro Odbiór w Punkcie Pocztex pobranie".

**Comment by szymonkrygier** [comment]
Rozumiem, niestety taka metoda nie jest listowana w JSON zwracanym przez API.

**Comment by MaciejFrackowiak** [comment]
Musisz dodać umowę własną dla przesyłek pobraniowych - szczegóły znajdziesz w [Pomocy Allegro](https://help.allegro.com/sell/pl/a/metody-dostawy-poczty-polskiej-i-pocztex-informacje-dla-sprzedajacych-lL55gykEqtk).

**Comment by szymonkrygier** [comment]
Dziękuje.
