### ISSUE TITLE
Problem z tworzeniem przesyłek na umowie Allegro

### ISSUE THREAD

**Issue by szymonkrygier** [allegro/allegro-api#10292]
Przy próbie utworzenia przesyłki przez Allegro API dla przewoźnika na umowie Allegro otrzymujemy komunikat: 

> Nie mozna utworzyć przesyłki przy użyciu umowy Allegro Standard. Metoda przypisana do tego zamówienia to umowa własna. Zmień umowę i spróbuj ponownie

Przykładowo dla dostawy Allegro One Punkt, DPD. Na liście dostępnych kurierów zwracanych przez API, dla tej metody dostawy, pole OWNER ustawione jest na ALLEGRO - czyli właścicielem umowy jest ALLEGRO. Tutaj wygląda wszystko poprawnie. Przy próbie natomiast utworzenia przesyłki na podstawie zwracanej wartości wyskakuje wyżej wspomniany błąd mimo iż nie jest przypisana umowa własna.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj konkretny przykład.

**Comment by szymonkrygier** [comment]
Co konkretnie podać? Identyfikator tworzonej przesyłki? Przekazywany JSON?

**Comment by MaciejFrackowiak** [comment]
Trace-id wywołania lub commandId przesyłki.

**Comment by szymonkrygier** [comment]
81c82290-4959-46d3-bf02-83dfd8ce2fb5

**Comment by MaciejFrackowiak** [comment]
W zleceniu użyłeś metody dostawy "Allegro One Box, DPD" (0b257488-c85d-4507-b967-9b45ffbfa2e8), natomiast metoda dostawy w zamówieniu to "Allegro One Punkt, DPD" (09ef5a54-c34d-41ef-908e-9b45ffbfa2e8).

**Comment by szymonkrygier** [comment]
Dziękuje.
