### ISSUE TITLE
cennik dostaw

### ISSUE THREAD

**Issue by kudel** [allegro/allegro-api#103]
Czy przez API można określić jakimś parametrem, który cennik dostaw zdefiniowany na koncie użytkownika ma dotyczyć wystawianej oferty (tak jak robimy to dla afterSalesServiceConditions)?

Obecnie można jedynie określić koszty dostawy osobno per oferta.
To powoduje, że gdy musimy zmienić ceny we wszystkich ofertach (bo np. kurier podniósł ceny)
to musimy użyć metody doChangeItemFields, która dość długo się przetwarza...

Ew. jak to szybko zrobić bez wielogodzinnego przetwarzania?

**Comment by KrzysztofLukanowski** [comment]
Niestety nie obsługujemy jeszcze cenników dostawy przez API. Zmieni się to w najbliższej przyszłości.

Rozwiązanie tymczasowe to wystawienie ofert z poszczególnymi kosztami dostaw. W międzyczasie możesz przygotować docelowy cennik dostawy. Jak już wystawisz wszystkie oferty, przejdź do zakładki [Sprzedaję ](https://allegro.pl/myaccount/sell.php), zaznacz oferty, które chciałbyś objąć danym cennikiem, następnie pod listą ofert wybierz przycisk "Zmień opcje dostawy". Na kolejnym ekranie wybierz pożądany cennik i zatwierdź zmiany.

**Comment by kudel** [comment]
Dziękuję za info i podpowiedź
