### ISSUE TITLE
parcel-management/parcel-create-commands - Nadanie paczki bez podjazdu

### ISSUE THREAD

**Issue by hubus999** [allegro/allegro-api#10303]
Jak nadawać przez API bez zamawiania podjazdu? Wykorzystujemy parcel-management/parcel-create-commands podczas nadawania paczek. Mamy stałe podjazdy z DPD, DHL wynikające z naszych umów. Nadając pojedyncze paczki w ramach allegro smart przez API allegro naliczane są opłaty za podjazd ze zbyt mała ilościa paczek...

**Comment by jezewskiBNetrox** [comment]
@hubus999 To dziwne, ponieważ do zamawiania podjazdu są osobne zasoby w API: https://developer.allegro.pl/documentation#operation/createPickup

Stąd podjazd nie powinien być zamawiany automatycznie.

**Comment by MaciejFrackowiak** [comment]
@hubus999 Dokładnie jest tak jak @jezewskiBNetrox napisał - podjazd nie jest zamawiany automatycznie, wymaga wykonania osobnego requestu.

**Comment by hubus999** [comment]
Nie korzystam z zasobu operation/createPickup. W takim razie wszystkie paczki są nadawane bez podjazdu (tak jak chciałem), a allegro/DPD/DHL zamawiają podjazd bez mojej wiedzy? Przesyłam screen z rozliczenia gdzie widoczne są dopłaty. DHL na szczęscie na razie nalicza opłaty 0,00zł, DPD już nie.
![Screenshot 2024-11-15 at 12-48-12 Rozliczenia z Allegro Allegro Sales Center](https://github.com/user-attachments/assets/c87b30ff-74b5-4bef-a477-d6491814ce84)
![Screenshot 2024-11-15 at 12-47-49 Rozliczenia z Allegro Allegro Sales Center](https://github.com/user-attachments/assets/d7d293d2-5a8e-4afd-955f-ca8efadf3819)

**Comment by MaciejFrackowiak** [comment]
@hubus999 Kwestię rozliczeń wyjaśnij proszę bezpośrednio z [obsługą Allegro](https://allegro.pl/pomoc/kontakt).

**Comment by hubus999** [comment]
Dziękuję. Wysłałem zapytanie do obsługi allegro.
