### ISSUE TITLE
Aktywacja konta allegro sandbox Client ID secret ID

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#10300]
Potrzebuję, aby Państwo aktywowali konto 4ftest - widzę, że rachunek bankowy jest w trakcie weryfikacji i tożsamość,
dodatkowo nie wiem jak mam wygenerować client id, secret id, id sprzedawcy, email marektplace@otcf.pl
![image](https://github.com/user-attachments/assets/800ddb96-7aa6-4416-a0da-ea7541983f06)

Czekam na pomoc, temat dosyc pilny.

**Comment by JasMieDev** [comment]
Prosiłbym o aktywację konta na sandboxie 
client:107523874
Z góry dziękuję

**Comment by Lukasz-Zurek** [comment]
@JasMieDev Aktywowałem.

**Comment by pzareba86** [comment]
Dziękuję, wszytsko działa poprawnie.

**Comment by Kontotest100** [comment]
.

**Comment by jakub8109** [comment]
Dzien dobry prosze o aktywację konta Client:108945821

**Comment by AureliuszBrussy** [comment]
@jakub8109 to konto zwykłe, aktywujesz je przy pierwszej transakcji. 

Jeżeli chcesz testować funkcjonalności związane ze sprzedażą - [zarejestruj nowe konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto).
