### ISSUE TITLE
Metoda i wartości zwracane : doShowUser

### ISSUE THREAD

**Issue by tieburach** [allegro/allegro-api#1030]
Występuje problem: 
 - [ X] z metodą WebAPI (doShowUser)

:beetle: **Opis**
Nie wiem czy to po prostu wynika z faktu, iż wygaszacie WebAPI, aczkolwiek metoda doShowUser zwraca następujące dane jak na zrzucie poniżej. Chciałem wyciągnąć sobie średnią ocenę użytkownika aczkolwiek wszystkie wartości są wyzerowane. Jeżeli taki wynik jest zamierzony to proszę o informację, poszukam innego sposobu.

dzisiaj (03.01)
Przykład dla konkretnego użytkownika (chyba pseudonim może być? jak niezgodne z RODO to mnie poprawcie 👍  ).
![blad](https://user-images.githubusercontent.com/32689802/50641705-1fbd6780-0f69-11e9-8754-b81c50738d2a.png)

**Comment by PawelTaberski** [comment]
Respons jest zgodny z naszą [dokumentacją do tej metody](https://allegro.pl/webapi/documentation.php/show/id,341#method-output). Większośc pól jest już nieaktualnych. Zalecam pobranie takich informacji przez REST API więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2017-10-09-news_informacje_o_ocenach/).

**Comment by tieburach** [comment]
Dziękuję bardzo za szybką odpowiedź! Miłego dnia
