### ISSUE TITLE
Unable to list an offer for EAN 5057847297631

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#10312]
Hi, when we try listing and offer against EAN 5057847297631, we get 422 - MatchingProductForIdNotFoundException
(trace-id: ef29e46a874f1599)

When we try to list offer while creating product at the same time, we get 422 - ProductLanguageVersionUnavailableException
(trace-id: b96269e79f24cfa7)

Can you please advice?

Thanks

Jirka Z

**Comment by PrzemyslawLukanowski** [comment]
Hi, the error appeared because we have such a product in our database, but it has not been translated into the Czech language at the moment. Please wait some time and try to create an offer once again.

**Comment by ZajdaBear** [comment]
Ok, thanks
