### ISSUE TITLE
How to tell, if the parameter value can be changed

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#10310]
Hi, I am looking for information, if the parameter value, already assigned, can be changed.

example from sandbox

offer_id: 7775344054

I can change value for parameters 224017_Manufacturer's code and 18118_Type, but can't change the value for 248811_brand.
Is there a way, to tell in advance, what parameters allows change of the value?

Thanks

Jirka

**Comment by Lukasz-Zurek** [comment]
We do not return this kind of information in our API. What is important - while you trying to edit an offer, you cannot change product parameters. You can check it by using [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) where in the **options.describesProduct** field we return **true** - if it is a product parameter or not (**false**).

We returned: `The provided parameter 'Brand'(248811) value (Abruzzo(248811_1785917)) does not match the existing parameter value (no brand(248811_958954))` - for the specific product from our catalog we do have (no brand(248811_958954) value so you have to provide it in your request.
