### ISSUE TITLE
Dostęp do zarządzania aplikacjami na Sandbox

### ISSUE THREAD

**Issue by tomek2x1** [allegro/allegro-api#10316]
Mam konto zarejestrowane na Sandbox ( t.lewandowski@emultimax.pl ) i chciałbym uzyskać dostęp do API. Klikając w "Zarządzaj dostępem do API Allegro." przenosi mnie do https://allegro.pl/logowanie gdzie moje dane do logowania nie działają. W jaki sposób uzyskać dostęp do zarejestrowania aplikacji i uzyskać ClientId i ClientSecret?

**Comment by PrzemyslawLukanowski** [comment]
Zaloguj się bezpośrednio przez stronę https://apps.developer.allegro.pl.allegrosandbox.pl/.
