### ISSUE TITLE
Sandbox orders not working

### ISSUE THREAD

**Issue by SunkovyChlebiczek** [allegro/allegro-api#10317]
Hello,
I am trying do make test order from sandbox account scmuminci, for offer id 7775750257 and it is not working. I've tried to do the order from another sandbox account and also as a guest, but there is still error message "There is unexpected mistake. Something went wrong, please try again..." I also tried other sellers with the same results. Is it outage of sandbox, or is the problem somewhere in the account settings? Thank you!

**Comment by PrzemyslawLukanowski** [comment]
Hello, seems that everything is right with your account, so if an error still appears, please attach a sample screenshot. I will verify this with the responsible department.

**Comment by PrzemyslawLukanowski** [comment]
And add information, when specifically this error appears.

**Comment by SunkovyChlebiczek** [comment]
When I am trying to place the order, when I clicked on the "Buy and Pay", there is an error message. Here is a video: https://drive.google.com/file/d/1DFoVxT1FN6Vj9MpGonezJLNoTBEkgLB1/view?usp=drive_link. The video is with "host" mode, but when I am singed in, it is the same.

![image](https://github.com/user-attachments/assets/c2bdac9c-fe2f-4130-9879-1d4c3b69036f)

**Comment by PrzemyslawLukanowski** [comment]
Thank you for details, I'll be back with more information after the investigation.

**Comment by PrzemyslawLukanowski** [comment]
We didn't find any logs on our side. Could you please try to buy as a quest and show web developer console after fail attempt?

**Comment by SunkovyChlebiczek** [comment]
Hello, now it is working correctly, so it seems everything is allright. Thank you for your help.
