### ISSUE TITLE
Rest Api, pobranie listy transakcji (odpowiednik doGetPostBuyFormsDataForSellers)

### ISSUE THREAD

**Issue by lkeska** [allegro/allegro-api#1031]
Czy w rest api znajde metody do pobierania listy transakcji na ofercie (odpowiedniki doGetSiteJournalDeals i doGetPostBuyFormsDataForSellers)?

**Comment by PawelTaberski** [comment]
Oczywiście, zachęcam do zapoznania się z naszym poradnikiem, opisaliśmy w nim [jak obsługiwać zamówienia przez REST API](https://developer.allegro.pl/orders/).
