### ISSUE TITLE
Kod pocztowy nadawcy znajduje się poza obszarem One Kuriera

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#10313]
Próbuję przetestować wysyłkę kurierem allegro na sandbox, pomijam już to że na karcie produktu mam inne formy wysyłki niż przy zakupie bo to pewnie przez to że je edytowałem i coś się nie odświeżyło.

W każdym razie wybieram jedną z form którą mam dostępna.
Przykładowo "Allegro One Punkt, One Kurier" i dostaję błąd 

```
object(stdClass)[70]
  public 'commandId' => string 'cb49f730-e1b4-4203-bea9-78ed1beda0b5' (length=36)
  public 'status' => string 'ERROR' (length=5)
  public 'errors' => 
    array (size=1)
      0 => 
        object(stdClass)[69]
          public 'code' => string 'BAD_REQUEST' (length=11)
          public 'message' => string 'Sender post code not support next day' (length=37)
          public 'details' => string '' (length=0)
          public 'path' => string 'sender.postCode' (length=15)
          public 'userMessage' => string 'Kod pocztowy nadawcy znajduje się poza obszarem One Kuriera' (length=60)
  public 'shipmentId' => null
```

Sprawdzałem różne kody pocztowe, obecnie mam centrum warszawy i dalej nic.
Próbowałem ustawić identyczny kod jak ten punktu odbioru, też nic.

Czy jakikolwiek kod pocztowy jest godzien zadziałania z wysyłką allegro?

**Comment by PrzemyslawLukanowski** [comment]
Z tego co widzę, to w polu sender przekazujesz:

```
        "sender": {
            "name": "aa",
            "company": "aa",
            "street": "uu",
            "streetNumber": "",
            "postalCode": "00001",
            "city": "mm",
            "state": null,
            "countryCode": "PL",
            "email": "aa@aa.pl",
            "phone": "123123123",
            "point": null
        },
```

Posiadasz może przykład z prawidłowym kodem, gdzie zwróciliśmy błąd?
