### ISSUE TITLE
Walidacja ilości znaków

### ISSUE THREAD

**Issue by piotreqm** [allegro/allegro-api#10326]
Oto wycinek jsona wysyłanego do API create-commands; *** - dane zanonimizowane

`{
	"commandId": "69eae1da-ea9d-4205-9f62-71c804ee8add",
	"input": {
		"deliveryMethodId": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
		"sender": {
			"company": "EL12 Oddział Gliwice",
			"street": "ul. Bojkowska",
			"streetNumber": "51",
			"postalCode": "44-100",
			"city": "GLIWICE",
			"countryCode": "PL",
			"email": "***",
			"phone": "***"
		},
		"receiver": {
			"name": "***",
			"street": "ul. Generała Witolda Urbanowicza",
			"streetNumber": "**",
			"postalCode": "**",
			"city": "***",
			"countryCode": "PL",
			"email": "***",
			"phone": "***",
			"point": "AL053LU1"
		},
		"referenceNumber": "***",
		"packages": [
			{
				"type": "PACKAGE",
				"length": {
					"value": 12.0,
					"unit": "CENTIMETER"
				},
				"width": {
					"value": 12.0,
					"unit": "CENTIMETER"
				},
				"height": {
					"value": 10.0,
					"unit": "CENTIMETER"
				},
				"weight": {
					"value": 1.0,
					"unit": "KILOGRAMS"
				}
			}
		],
		"additionalServices": [],
		"additionalProperties": {}
	}
}`

Otrzymuję błąd:

`{
	"commandId": "69eae1da-ea9d-4205-9f62-71c804ee8add",
	"status": "ERROR",
	"errors": [
		{
			"code": "SHIPMENT_VALIDATION_ERROR",
			"details": "Shipment request has validation errors",
			"message": "Entered text exceeds 35 characters",
			"path": "receiver.street",
			"userMessage": "Długość podanego tekstu przekracza 35 znaków"
		}
	]
}`

problem w tym, że "ul. Generała Witolda Urbanowicza" ma 32 znaki. Czy wskazanie błędu jest poprawne?

**Comment by Lukasz-Zurek** [comment]
@piotreqm Przekazałem to dalej do weryfikacji. Proszę o cierpliwość.

**Comment by piotreqm** [comment]
Ok, dziękuję i czekam cierpliwie

**Comment by Lukasz-Zurek** [comment]
@piotreqm Zawartość pola **"street"** i **"streetNumber"** (łącznie) przekracza limit przeznaczony dla **"street"** - czyli 35 znaków. Komunikat może być mylący, jednak zgodnie z [naszym komunikatem](https://developer.allegro.pl/news/wysylam-z-allegro-31-stycznia-2025-usuniemy-pole-streetnumber-6M7kKbzw5CB) - pole **"streetNumber"** **zostanie usunięte 31 stycznia 2025 roku**, dlatego sugerujemy, aby cały adres, czyli nazwę ulicy oraz jej numer, przekazywać w polu **"street"**.

**Comment by piotreqm** [comment]
@Lukasz-Zurek ok, dziękuję za wyjaśnienie

**Comment by Lukasz-Zurek** [comment]
@piotreqm Nie przekazuj w ogóle tego pola. Jest ono obecnie opcjonalne, właśnie z uwagi na powyższe zmiany.

**Comment by piotreqm** [comment]
Ok
