### ISSUE TITLE
Pytanie do formatu etykiet Pocztex

### ISSUE THREAD

**Issue by testytema** [allegro/allegro-api#10338]
Dzień dobry,

prosiłbym o sprawdzenie co może być powodem, że pobranie etykiety (zarówno przez stronę jak i API) do zamówienia wysyłanego Pocztexem powoduje, że zostaje ona pobrana w rozmiarze większym niż 10x15cm.

Trace-id wywołania: 50e4d6934ef04644

Dodam, że w Elektronicznym Nadawcy wszędzie gdzie się da, rozmiar etykiety jest ustawiony właśnie na 10x15cm

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

1. Czy problem dotyczy tylko tej metody wysyłki? 
2. Czy możemy prosić o jakiś screenshot/zdjęcie? 
3. Rozumiem że format to ZPL?

**Comment by testytema** [comment]
Dzień dobry,

Ad 1. Tak, problem występuje tylko dla przesyłek Pocztex. DHL lub DPD są w prawidłowym formacie.

Ad 2. Poniżej skan takiej etykiety
![etykieta pocztex ucieta](https://github.com/user-attachments/assets/9eaafa4d-738e-41b6-b621-c1b250279e43)

Ad 3. Tak, etykiety są generowane w formacie ZPL

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Jeszcze jedno pytanie - czy używasz innych metod Poczty (Przesyłka Polecona, MiniPrzesyłka)?

**Comment by testytema** [comment]
Przesyłka Polecona wystąpiła na kilku zamówieniach (do czerwca) a MiniPrzesyłka nie jest używana.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, czy jak przestawisz drukarkę na 300DPI to etykieta drukuje się poprawnie?

**Comment by testytema** [comment]
Musiałem to sprawdzić na labelary.com, ponieważ drukarki obsługują max. 203 DPI, ale po wydrukowaniu jej w 300 DPI etykieta jest prawidłowa.

Dodam, że w ustawieniach Elektronicznego Nadawcy jest ustawione 203 DPI.

**Comment by PrzemyslawLukanowski** [comment]
Wgraliśmy poprawkę, proszę o anulowanie przesyłki i wygenerowanie nowej.

**Comment by testytema** [comment]
Sprawdziliśmy, etykiety generują się poprawnie, dziękują za pomoc :)
