### ISSUE TITLE
[REST] Powiązanie Payment id z Payout

### ISSUE THREAD

**Issue by TinTours** [allegro/allegro-api#1033]
Czy istnieje / planujecie wprowadzić w REST API odpowiednik doGetMyPayouts i doGetMyPayoutsDetails? Ewentualnie czy jest możliwość jakiegokolwiek powiązania wyniku /order/checkout-forms z transactionId występującym w WebAPI (przez identyfikator, a nie czas, użytkownika i kwotę)?

Potrzebujemy przypisać transakcje i użytkowników do konkretnego przelewu, który pojawia się na naszym koncie - WebAPI niestety nie rozróżnia PayU i P24 we wpłatach użytkowników i wypłatach na konto.

**Comment by TinTours** [comment]
Właśnie o pole Provider chodzi, niestety nie mam możliwości powiązać go z transakcją z WebAPI, ani tych samych transakcji ze sobą w WebAPI i REST.

W takim razie czekamy na nowe metody.

**Comment by PawelTaberski** [comment]
Co prawda nie jest to rozwiązaniem idealnym, ale do powiązania samych aktów zakupowych możesz wykorzystać zasób do mapowania dealId i lineItemId, o którym pisaliśmy [tutaj](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/).

**Comment by TinTours** [comment]
Jako tymczasowy workaround powinno wystarczyć, dziękuję.
