### ISSUE TITLE
Bezobsługowy integracja zamówień Allegro z aplikacją, działającą w tle na serwerze

### ISSUE THREAD

**Issue by matteopolserv** [allegro/allegro-api#10355]
Przeglądam dokumentację API i szukam odpowiedzi jak najprościej rozwiązać taki problem:
Aplikacja pracująca na serwerze ma w tle pobierać zamówienia bez angażowania użytkownika.
I napotykam na następujące trudności:
1. Użycie [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) oraz [Device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) wymaga regularnego angażowania użytkownika (raz na 3 miesiące) a tego chcemy zdecydowanie uniknąć. 
2. Użycie [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) nie daje wystarczających uprawnień do pobierania zamówień.

Czy jest jakieś nieangażujące użytkowników rozwiązanie, które pozwoli na zarządzanie zamówieniami za pośrednictwem zewnętrznej aplikacji?

**Comment by matteopolserv** [comment]
Ok, już doczytałem na innym forum, że refresh token się odświeża i zastępuje stary i można go użyć za jego pomocą przedłużać ważność poświadczeń bezobsługowo. Warto to umieścić w dokumentacji

**Comment by AureliuszBrussy** [comment]
Aby pobierać zamówienia, musisz skorzystać z [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [Device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow), gdyż token musi mieć kontekst konkretnego użytkownika - [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) odpada. 

Nie jest natomiast prawdą, że raz na 3 miesiące konieczne będzie zaangażowanie użytkownika. Po skorzystaniu z refresh tokena otrzymujesz całkiem nową parę access oraz refresh token. Ten nowy refresh token znowy jest ważny przez 3 miesiące. Oznacza to, że interakcja użytkownika końcowego jest wymagana tylko raz - przy pierwszej autoryzacji (wyrażaniu zgodu na działanie aplikacji w jego imieniu). 

Natomiast musisz mieć świadomość, że może zdarzyć się tak, że access token i refresh token w swoim cyklu życia może być w pewnych warunkach unieważniony. Dzieje się tak w przypadku:

- wylogowania się ze wszystkich urządzeń, np. poprzez zakładkę [Logowanie i hasło](https://allegro.pl/moje-allegro/moje-konto/logowanie-i-haslo),
- zmiany hasła,
- zmiany adresu e-mail,
- blokady sprzedaży,
- w wyniku przekroczenia liczby aktywnych sesji (max. 20 otwartych sesji dla jednego użytkownika).

Sytuacja dotyczy zarówno access_tokena, jak i refresh_tokena.

Aplikacja więc musi być przygotowana na to, aby ponownie wygenerować nową parę access i refresh token, bez używania wcześniej wygenerowanego refresh tokena.

**Comment by matteopolserv** [comment]
Dzięki, właśnie doczytałem o odnawianiu pary token - refresh token to w innym źródle - albo nie piszą o tym w dokumentacji albo przeoczyłem, sugerując się maksymalną ważnością 3 miesiące.
