### ISSUE TITLE
Token EXPIRED

### ISSUE THREAD

**Issue by Sylvesterx1** [allegro/allegro-api#10353]
Dzień dobry,
Allegro Sandbox.

Aplikacja została utworzona. Następnie loguje się na konto, zezwalam aplikacji na dostęp, w odpowiedzi otrzymuje ?code=..........

Używam kodu tymczasowego aby otrzymać token. W odpowiedzi otrzymuje Bearer token 

Używam tokena do operacji api,  problem polega na tym że z dokumentacji wynika że bearer token powinien być ważny (rok?) ale niestety po kilku godzinach (może 24h - zazwyczaj następnego dnia) widzę błąd z API Allegro że token stracił ważność i ponownie musze pozyskać nowy kod ?code=......... czyli powiązać aplikacje z kontem. aby otrzymać Bearer token.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,

Jeśli gdzieś na naszych stronach znalazłes informację, że access token jest ważny rok, daj proszę znać, zmienimy to info. Raczej wszędzie wspominamy, że jest to 24h. Rok ważności z perspektywy bezpieczeństwa byłby niedopuszalny :)

Nie musisz za każdym razem na nowo autoryzować aplikacji, możesz za pomocą refresh tokena (który otrzymałeś wraz z access tokenem) generować nową parę access token + refresh token zanim access token straci ważność. Więcej na ten temat przeczytasz [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena).

**Comment by Sylvesterx1** [comment]
Dziękuje za szybką odpowiedź.

Przy autoryzacji za pomocą  uzyskanego code  mogę prawidłowo pozyskać token i refresh_token

 ```
public function getToken()
    {
        $code = $this->request->getVar('code'); // Get authorization code from request

        if (!$code) {
            return $this->fail([
                'status' => 400,
                'error' => 'Authorization code is missing',
                'message' => 'Please provide a valid authorization code.'
            ], 400);
        }

        $tokenUrl = 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token';
        $postData = [
            'grant_type' => 'authorization_code',
            'code' => $code,
            'redirect_uri' => $this->redirectUri,
        ];

        $headers = [
            'Authorization: Basic ' . base64_encode("{$this->clientId}:{$this->clientSecret}"),
            'Content-Type: application/x-www-form-urlencoded',
        ];
```

Obecnie próbuje za pomocą refresh_token pozyskać ponownie nową parę token i refresh_token

```
 private function refreshToken($refreshToken)
    {
        $tokenUrl = 'https://allegro.pl/auth/oauth/token';
        $postData = [
            'grant_type' => 'refresh_token',
            'refresh_token' => $refreshToken,
        ];

       
         $clientId = 'd9************';
         $clientSecret = 'jn7i****************';
        $headers = [
            'Authorization: Basic ' . base64_encode("{$clientId}:{$clientSecret}"),
            'Content-Type: application/x-www-form-urlencoded',
        ];

        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $tokenUrl);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($postData));

        $response = curl_exec($curl);
        curl_close($curl);

        if ($response === false) {
            log_message('error', 'Curl error: ' . curl_error($curl));
            return null;
        }

        $data = json_decode($response, true);

        // Debugging the response 
        var_dump($data);
```


ale niestety w przypadku  'grant_type' => 'refresh_token', otrzymuje za każdym razem 

```
array(2) {
  ["error"]=>
  string(12) "Unauthorized"
  ["error_description"]=>
  string(12) "Unauthorized"
}
```

client id, client secret oraz refresh_token jest poprawny / aktualny. Pozyskany chwile wcześniej przez standardową funkcję autoryzacji "code".

**Comment by Sylvesterx1** [comment]
@PrzemyslawLukanowski  temat do zamknięcia :)

Problem był w adresie zamiast na sandbox, zapytanie zostało przesłane na produkcje.

Pozdrawiam i dziękuje za pomoc.
