### ISSUE TITLE
Problem z dodaniem uprawnień na portalu developer.allegro.pl

### ISSUE THREAD

**Issue by tsodo** [allegro/allegro-api#10351]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie dodania uprawnień 

![uprawnienia](https://github.com/user-attachments/assets/4eddca21-39de-4f94-b014-134784aae5e5)

pojawia się komunikat
![błąd](https://github.com/user-attachments/assets/deac5ee1-4d00-49b6-8956-49528edee846)

**Comment by PrzemyslawLukanowski** [comment]
Przypadek Waszej aplikacji jest nieco bardziej specyficzny, dlatego scope'y musimy dodać manualnie po naszej stronie. Wrócę z informacją, gdy to się wydarzy.

**Comment by tsodo** [comment]
@PrzemyslawLukanowski jesteś w stanie wskazać kiedy zmiana zostanie wprowadzona?

**Comment by PrzemyslawLukanowski** [comment]
Zakresy zostały niedawno nadane, powinny już być widoczne w danych aplikacji.

**Comment by tsodo** [comment]
Mam jeszcze pytanie uzupełniające. 
Te scope'y zostały włączone na środowisku testowym i produkcyjnym?
Pytam bo rzeczywiście przy opisywaniu wskazałem, że problem występuje tylko na produkcji.

**Comment by PrzemyslawLukanowski** [comment]
Wyłącznie na produkcyjnym.

**Comment by tsodo** [comment]
Poproszę więc również na środowisku testowym.

**Comment by PrzemyslawLukanowski** [comment]
Poproszę w takim razie clientID ze środowiska testowego :)

**Comment by tsodo** [comment]
Przepraszam za zamieszanie. 
Jednak pomimo tego co napisałeś wcześniej, nie widzimy w panelu żeby wskazane scope'y były włączone.
Dla pewności podaje jeszcze raz o client id, o które chodziło od początku 677535760e304f968a80966d1e25a655

**Comment by PrzemyslawLukanowski** [comment]
Może to wynikać ze specyfiki Waszej aplikacji, jednak po naszej stronie widzimy, że aplikacja zawiera te zakresy.

Jeśli nadal otrzymujecie 403 przy odpytywaniu zasobu, to dlatego, że zapewne operujecie w ramach tokena, który wciąż zawiera poprzednie zakresy. Aby objął on te nowo nadane, musicie na nowo [zautoryzować aplikację](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika), czyli ponownie potwierdzić, że aplikacja może wykonywać operacje w imieniu użytkownika. Tym sposobem wygenerujecie nową parę tokenów, już z uwzględnionym nowym scope.

**Comment by tsodo** [comment]
Generalnie mamy dwa problemy. 
1. Dla id = 677535760e304f968a80966d1e25a655 (produkcja) jeszcze nie sprawdzaliśmy czy dostajemy poprawną odpowiedź. Na razie brak włączenia dodatkowych scope'ów oceniliśmy po tym, że w portalu nie widać, żeby były włączone.
2. Dla id = 2f47c4d3dc2b4f65becc40febf9286c5 (środowisko testowe, tutaj sami dodaliśmy dodatkowe scope'y). Usunęliśmy źródło importu powiązane z Allegro, podłączyliśmy ponownie. Nastąpiła ponowna autoryzacja i dostaliśmy nowy token, który nadal nie ma tych dodatkowych uprawnień.

**Comment by PrzemyslawLukanowski** [comment]
1. Prosiłbym się tym nie sugerować. Tak jak wspomniałem, może to wynikać z nieco innego przypadku dla Waszej aplikacji, gdzie to my po naszej stronie musieliśmy dodać wspomniane zakresy.
2. Dzieje się tak dlatego, ponieważ przy żądaniu do https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize dodajecie parametr scope, w którym przekazujecie mniejszy zakres, tj. `allegro:api:profile:read allegro:api:orders:read allegro:api:orders:write`. Tym sposobem, nieważne co będziecie mieli zaznaczone na stronie, i tak automatycznie ograniczacie liczbę scope'ów i nie widać żadnych zmian. Możecie usunąć ten parametr w zupełności, jeśli chcecie, aby aplikacja miała dostęp do wszystkich zakresów zdefiniowanych na stronie. Prosiłbym, aby mieć to również na uwadze na środowisku produkcyjnym.
