### ISSUE TITLE
Wznawianie restapi

### ISSUE THREAD

**Issue by danmckp** [allegro/allegro-api#1035]
Namawiacie do przesyłania prawdziwych stanow towaru jednak gdy on jest wykupiony przez allegro taka aukcja znika i można wystawić tylko nową. Kiedy będzie to poprawione i czy w ogóle wznawianie w restapi działa już prawidłowo??

**Comment by PawelTaberski** [comment]
W REST API można nie tylko wznowić aukcje z zerowym stokiem (wystarczy go wcześniej uzupełnić przy pomocy metody PUT na zasobie /sale/offers/{offerId} tak jak to [opisaliśmy w poradniku](https://developer.allegro.pl/my_offers/#2)) Ponadto w REST API możesz wstrzymać ofertę jak zabraknie Tobie zapasu i później możesz ją aktywować z tym samym numeru, aby nie straciła całej popularności. Te czynności wykonasz przy pomocy metody  PUT /sale/offer-publication-commands/{commandId} polecam zapoznać się z n[aszymi poradnikami](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).
