### ISSUE TITLE
Aktywacja konta w WZA w środowisku sandbox.

### ISSUE THREAD

**Issue by mstrojecki** [allegro/allegro-api#10366]
Witam,

przy próbie odpytania endpointów z grupy shipment-management lub pracel-management otrzymuję błąd:

      "code" => "ACCOUNT_NOT_ACTIVATED"
      "message" => "User account was not activated in SwA. The account must be a Business Account and go through the verification process."
      "details" => "Not Authorized"
      "path" => "header.authorization"
      "userMessage" => "Konto użytkownika nie zostało aktywowane w WZA. Konto musi być firmowe i przejść proces weryfikacji."
      "metadata" => []

Konto: **sandbox-apteka**

Mógłbym prosić o aktywację konta?

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Na Twoim koncie widniała blokada, którą przed momentem zdjąłem. Sprawdź proszę czy jest już ok.

**Comment by mstrojecki** [comment]
Niestety dalej taki sam błąd

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Podaj proszę trace-id.

**Comment by mstrojecki** [comment]
trace-id: 7332fe0264a806f3

**Comment by Lukasz-Zurek** [comment]
Dzięki! Zgłosiłem dalej.

**Comment by Lukasz-Zurek** [comment]
@mstrojecki Problem był po naszej stronie, przepraszamy za utrudnienia. Aktywuj proszę ponownie konto w WZA, zgodnie z instrukcją w pierwszej ramce z góry w tym [tutorialu](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).

**Comment by mstrojecki** [comment]
Teraz wszystko działa. Dzięki za pomoc!
