### ISSUE TITLE
Aktywacja konta na platformie sandbox

### ISSUE THREAD

**Issue by plegenza** [allegro/allegro-api#10374]
Cześć,

W odpowiedzi na utworzenie oferty otrzymuję błąd:
`{
  "errors": [
    {
      "code": "OfferAccessDeniedException",
      "message": "Forbidden",
      "details": null,
      "path": "",
      "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer",
      "metadata": []
    }
  ]
}`

Proszę o aktywację konta o loginie: random-dev na platformie sandbox (https://allegro.pl.allegrosandbox.pl/) taka by można było wystawiać oferty.

**Comment by Lukasz-Zurek** [comment]
@plegenza Aktywowałem konto.

**Comment by plegenza** [comment]
Podziękował
