### ISSUE TITLE
Swagger file productSet problem

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#10377]
Cześć,
Mam pytanie odnośnie https://developer.allegro.pl/swagger.yaml, czy mógłbym prosić o weryfikacje deklaracji SaleProductOfferRequestV1? Generator klienta nie tworzy mi w prawidłowy sposób powiązań productSet w modelu.
Czy deklaracja jest prawidłowa?
`productSet:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/ProductSetElement'
                    - description: List of products sold in the offer.
                    - $ref: '#/components/schemas/ProductSetElementQuantity'
                    - $ref: '#/components/schemas/ProductSetElementResponsiblePersonRequest'
                    - $ref: '#/components/schemas/ProductSetElementResponsibleProducerRequestWrapper'
                    - $ref: '#/components/schemas/ProductSetElementSafetyInformationWrapper'`

**Comment by PrzemyslawLukanowski** [comment]
Cześć, pozwól, że zacytuję odpowiedź z podobnego wątku #9407:

> (...) Problemy mogą występować również dla SaleProductOfferRequestV1. Nie wspieramy w pełni generatora i nie przewidujemy tutaj w najbliższym czasie optymalizacji w tym zakresie, ponieważ konieczne byłyby poważniejsze zmiany, wymagające czasu.

**Comment by jakub-marchewka** [comment]
Dziękuję za informację
