### ISSUE TITLE
numer transakcji / numer płatności

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#1037]
Czy numery nazywane przez Was numer płatności są w jakikolwiek sposób powiązane między REST a webapi ? Nie bardzo wiem jak to wszystko ugryźć. Obecnie z webapi zaciągając FOD dostajemy numer 9 cyfrowy. Natomiast w REST widzę zwracany jest już tylko ten nowy numer. Pytania są dwa:
1) czy gdziekolwiek jest wspólny mianownik - chcemy uruchomić testowo pobieranie w REST api zamówień, ale na razie chcemy to zrobić równolegle - do weryfikacji - na testy i nie bardzo jest po czym je spiąć...
2) gdy siadziemy już tylko do REST api - jaki numer mamy podawać do inpostu ? oni wymagają do paczkomatów allegro m.in. podanie ID płatności....

![obraz](https://user-images.githubusercontent.com/38914331/50758177-b9cf2980-1261-11e9-8503-2748f9665066.png)

**Comment by MartaNowaczyk** [comment]
@partyumarty 
1. Możesz skorzystać z [mapowania dealId i lineItemId](https://github.com/allegro/allegro-api/issues/731) 
2. Na ten moment InPost przyjmuje ten 9 cyfrowy numer, także trzeba jeszcze poczekać za uspójnieniem w tej kwestii.
