### ISSUE TITLE
Poczta Polska oraz OTHER Zdublowany numer listu przewozowego 

### ISSUE THREAD

**Issue by DawidInnSoft** [allegro/allegro-api#10386]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
w jednym z zamówień złożonym u nas dla kuriera Poczta Polska przy odbiorze do Punktu Pocztex, zamiast pozycji 
Poczta Polska PX0000000000
pojawiły się dwie pozycje
Inny: OTHER PX0000000000
Poczta Polska PX0000000000
A przesyłka została zaliczona 1 z 1 tylko jako OTHER PX0000000000

Problem wystąpił dla zamówienia: fc75d0c0-98ef-11ef-a012-21efe8bb2dc3

Sprawdziliśmy po naszej stronie czy nie wysyłamy dwukrotnie listu, przewozowego na endpoint z różnym carrierId /order/checkout-forms/{id}/shipments jednak taka sytuacja u nas nie wystąpiła. Prosiłbym o sprawdzenie, czy nie jest to problem po waszej stronie lub po stronie poczty polskiej. Z góry bardzo dziękuję za odpowiedź.

**Comment by MartaNowaczyk** [comment]
Nie mam już logów dla wysyłania listów przewozowych dla tego zamówienia. Jeśli problem by się powtórzył daj znać wcześniej.

**Comment by DawidInnSoft** [comment]
Rozumiem, będziemy obserwować sytuację i jeżeli się powtórzy, natychmiastowo zgłosimy to ponownie. Jakie okienko czasowe mamy do zgłoszenia? Przez jaki czas u Państwa przechowywane są logi?

**Comment by MartaNowaczyk** [comment]
W tym wypadku jest to max 14 dni.

**Comment by DawidInnSoft** [comment]
W takim wypadku zamykam ten issue, jeżeli problem się powtórzy, jak najszybciej się odezwiemy w tej sprawie. Dziękuję za pomoc i poświęcony czas.
