### ISSUE TITLE
Blokada na prodzie - "Zostałeś zablokowany."

### ISSUE THREAD

**Issue by MNBrandly360** [allegro/allegro-api#10388]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie autoryzacji  na prodzie dostaję komunikat:
Zostałeś zablokowany.

Dlaczego zostałeś zablokowany? Coś w zachowaniu twojej przeglądarki zwróciło naszą uwagę. Powody mogą być różne:
 przeglądasz strony i klikasz dużo szybciej niż przeciętny człowiek
 coś uniemożliwia działanie Javascript na twoim komputerze
 w tej samej sieci (IP xxx.xx.xxx.xx) operuje robot
Jeśli coś nie działa prawidłowo wyślij nam wiadomość.

ID: 6e4c8afc-120a-6734-39a5-94870a479c18

Najpierw dostawałam to na sandboxie po kilku requestach, więc uznałam że przeglądanie danych mogę sprawdzić na prodzie ale taki efekt dostałam po rozwiązaniu pierwszej captchy.

**Comment by MartaNowaczyk** [comment]
Sprawa przekazana do weryfikacji w odpowiednim dziale. Jak tylko będę miała jakieś informacje wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Prosimy o wyłączenie wszelkich wtyczek przeglądarki, które mogą zmieniać ruch do allegro, takie jak adblocki itp. Najlepiej uruchom proszę Allegro na świeżej przeglądarce bez żadnych wtyczek.

**Comment by MNBrandly360** [comment]
zainstalowałam na nowo firefox, i zaraz po instalacji i tak mam bana: ID: a1c8bf68-58f7-cc4d-256e-74f5a625013d

**Comment by Maczuga** [comment]
Zauważyłem 3 rzeczy, które to trkggeruja:

1. Odpalone devtoolsy
2. Nagla zmiana rozmiaru okna (np triggerowanie widoku mobile na desktopie)
3. Narzędzia typu Fiddler odpalone w tle.

Może coś z tego jest u Ciebie?

**Comment by MNBrandly360** [comment]
Nic z tych rzeczy. 
Jak już dostaję takiego bana, to jest sens próbować ponownie czy powinnam odczekać jakiś minimalny czas?

**Comment by MartaNowaczyk** [comment]
@MNBrandly360 może masz jakieś oprogramowanie w komputerze, które ma na to wpływ. Możliwe, że na innym komputerze nie będziesz mieć takiej sytuacji. Sprawdzam jeszcze jaki jest czas dla twojej blokady.
