### ISSUE TITLE
Śledzenie przesyłki

### ISSUE THREAD

**Issue by tspodymek** [allegro/allegro-api#1038]
Witam 
Czy nowe api(Rest) umożliwia pobranie numeru przesyłki z Allegro ?

**Comment by MartaNowaczyk** [comment]
@tspodymek na ten moment nie ma takiej możliwość. Pracujemy nad zasobami do obsługi numerów przesyłek. Jeśli takie się pojawią na pewno poinformujemy o tym w stosownym komunikcie.

**Comment by MartaNowaczyk** [comment]
Bezpośrdniego połączenia nie ma, ale jest połączenie dwóch światów przez [mapowanie lineItemID i dealID](https://github.com/allegro/allegro-api/issues/731).

**Comment by tspodymek** [comment]
Dzieki za informacje

**Comment by KyjoWeg** [comment]
Czy Rest Api umożliwi przekazywanie danych o numerze przewozowym gotowej paczki do allegro ?

**Comment by MartaNowaczyk** [comment]
@KyjoWeg tak, pracujemy nad zasobami, dzięki którym będzie można między innymi dodać numer przesyłki.

**Comment by KyjoWeg** [comment]
> @KyjoWeg tak, pracujemy nad zasobami, dzięki którym będzie można między innymi dodać numer przesyłki.

A wyrobicie się do końca tego miesiąca? 
Pytam ponieważ otrzymałem maling z allegro że taki informacja będzie wymagana od 1 lutego
