### ISSUE TITLE
/order/checkout-forms/ PHP - pytanie laika

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#1039]
Hej, może znajdzie się jakaś dobra dusza, która wrzuci swój fragment kodu w PHP, bo ja chyba czegoś nie rozumiem... Jest sobie funkcja:
```
function commandRequest($uri, $generatedKey,$data)
    {
    $headers = array(
        'Accept: application/vnd.allegro.beta.v1+json',
        'Content-Type: application/vnd.allegro.public.v1+json',
        'Authorization: Bearer '.$generatedKey.'');
		$curl = curl_init($uri);
		curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		return curl_exec($curl);
    }
```
i jest sobie wywołanie funkcji, które działa :)
```
$generatedKey   = xxxxx
$data = '';
$xx=commandRequest('https://api.allegro.pl/order/checkout-forms',$generatedKey,$data);
print_r($xx);
```
I zwraca cały sznur danych...
> 
> stdClass Object
> (
>     [checkoutForms] => Array
>         (
>             [0] => stdClass Object
>                 (
>                     [id] => fa2380ba-1321-11e9-9136-cb4fd9107bf1
>                     [buyer] => stdClass Object
>                         (
>                             [id] => 8795070
>                             [email] => xxx
>                             [login] => xxx
>                             [guest] => 
>                             [phoneNumber] => xxx
>                         )
> 
>                     [payment] => stdClass Object
>                         (
>                             [id] => 021fe01a-1322-11e9-a3d5-f582b5b2547a
>                             [type] => ONLINE
>                             [provider] => PAYU
>                             [finishedAt] => 2019-01-08T08:48:34.689Z
>                             [paidAmount] => stdClass Object
>                                 (
>                                     [amount] => 60.66
>                                     [currency] => PLN
>                                 )
> ...

A czy może mi ktoś powiedzieć dlaczego wywołanie z konkretnym checkoutem generuje błąd ?

```
$xx=commandRequest('https://api.allegro.pl/order/checkout-forms/647d9fb2-131b-11e9-a474-55c966d57068',$generatedKey,$data);
```

I w odpowiedzi dostajemy 

>                     [code] => ERROR
>                     [message] => An error has occurred
>                     [path] => /order/checkout-forms/647d9fb2-131b-11e9-a474-55c966d57068

**Comment by MartaNowaczyk** [comment]
@partyumarty wygląda na to, że podajesz błędny identyfikator zamówienia. 
Poza tym zwróć uwagę, że w nagłówku masz raz wersję beta, a raz public.
