### ISSUE TITLE
Aktywacja konta allegro sandbox

### ISSUE THREAD

**Issue by adriansinko** [allegro/allegro-api#10392]
Założyłem konto w testowym środowisku allegro sandbox lecz mam problem z automatyczna aktywacją konta. Czy można prosić o ręczną aktywację konta dla adresu e-mail: **audia6c6v8@gmail.com** ?

**Comment by adriansinko** [comment]
@MartaNowaczyk Czy mogę również prosić o Potwierdzenie rachunku bankowego oraz tożsamości i dane firmy abym mógł zacząć testować sprzedaż ?

**Comment by adriansinko** [comment]
@MartaNowaczyk nowy adres e-mail to **adrianps26107@gmail.com**

**Comment by MartaNowaczyk** [comment]
Z tego co widzę, dla tego konta też nie wybrałeś pełnej opcji sprzedażowej. Zobacz czy w [ustawieniach konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy) masz link na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)", jak tak to skorzystaj z niego, wybierz "Weryfikacja pełna" i uzupełnij dane.

**Comment by adriansinko** [comment]
@MartaNowaczyk Tak mogę wrócić i do wyboru mam 'Sprzedaż sporadyczna', 'Sprzedaż regularna' d wyboru

**Comment by MartaNowaczyk** [comment]
to wybierz regularną

**Comment by adriansinko** [comment]
@MartaNowaczyk gotowe to samo wybrałem również wcześniej

**Comment by MartaNowaczyk** [comment]
Aktywowałam twoje konto.

**Comment by MartaNowaczyk** [comment]
Dzień dobry @OmegaVZ. Aktywowałam twoje konto BLGtest.

**Comment by serwis-nd** [comment]
Dzień dobry, proszę o aktywację konta: pneumatico_pl

**Comment by MaciejFrackowiak** [comment]
@serwis-nd Konto jest już aktywne.

**Comment by ttoporek** [comment]
Dzień dobry, proszę o aktywacje konta dla loginu: jp2

**Comment by Lukasz-Zurek** [comment]
@Exootic Aktywowałem konto.

**Comment by Lukasz-Zurek** [comment]
@ttoporek Aktywowałem.

**Comment by ttoporek** [comment]
Dzień dobry, proszę o aktywacje konta dla loginu: kkm2

**Comment by MaciejFrackowiak** [comment]
@ttoporek Konto aktywowane.
