### ISSUE TITLE
Kup Teraz dla 2 i więcej przedmiotów kończy się błędem

### ISSUE THREAD

**Issue by dtarczynski** [allegro/allegro-api#104]
Dotyczy: allegro.pl.allegrosandbox.pl

Podczas próby zakupienia 2 przedmiotów otrzymuję błąd 
![image](https://user-images.githubusercontent.com/3863083/38079950-78aac398-3340-11e8-8e13-59384bb94b85.png)

Przy zakupie 1 sztuki wszystko jest OK. Oczywiście mam ponad 80 przedmiotów dostępnych.

**Comment by PawelTaberski** [comment]
Przetestowałem na dwóch dowolnych ofertach i wydaje się, że wszystko jest ok podaj proszę numery ofert jakie chciałeś kupić.

**Comment by dtarczynski** [comment]
@PawelTaberski Kurde, teraz działa :|
