### ISSUE TITLE
Nie istniejący checkout-form

### ISSUE THREAD

**Issue by GrzegorzWegrzyn** [allegro/allegro-api#10406]
Dzień dobry,

kilka dni temu wystąpił u nas błąd przy próbie pobrania danych zamówienia. Po odpytaniu /order/events otrzymaliśmy listę zdarzeń, gdzie kilka z nich np: 1732064772154451. Wskazują na nieistniejący checkout-form: 91474370-a6db-11ef-beb1-2953ecce8ded (/order/checkout-forms zwraca: błąd 404 CheckoutFormNotFoundException). Dodam że problem występuje tylko z tym zamówieniem. Czy jest to zachowanie normalne, jeżeli tak to dlaczego? 

Pozdrawiam,
Grzegorz Wegrzyn

**Comment by jezewskiBNetrox** [comment]
@GrzegorzWegrzyn https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#w-dzienniku-zdarzen-otrzymalem-event-filled_in-z-konkretnym-numerem-zamowienia-kiedy-przekazuje-ten-numer-w-get-order-checkout-forms-id-w-odpowiedzi-otrzymuje-status-404-z-informacja-ze-nie-znaleziono-takiego-zamowienia-co-sie-z-nim-z-stalo-

>FAQ: W dzienniku zdarzeń otrzymałem event FILLED_IN z konkretnym numerem zamówienia. Kiedy przekazuję ten numer w GET /order/checkout-forms/{id} w odpowiedzi otrzymuję status 404 z informacją, że nie znaleziono takiego zamówienia. Co się z nim z stało?

>Kupujący najprawdopodobniej wykonał oddzielne zakupy, a następnie łącznie je opłacił. Otrzymasz nowy event z nowym numerem zamówienia, a stare usuniemy. Aby zidentyfikować taką sytuację możesz oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

**Comment by GrzegorzWegrzyn** [comment]
@jezewskiBNetrox Dzieki bardzo, coś musieliśmy przeoczyć. Faktycznie zaszedł taki przypadek. Podzrawiam
