### ISSUE TITLE
Cost Summary Endpoint

### ISSUE THREAD

**Issue by Thangthebrandlab** [allegro/allegro-api#10401]
Hi,

I'm currently working on automating our Allegro Sales Analysis. Is there an endpoint in Allegro that provides an Cost Summary charged to an account within a certain period of time?

Thank you.

**Comment by MaciejFrackowiak** [comment]
You can check your billing by [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries). You can specify results by several parameters, e.g. occurredAt.gte or occurredAt.lte.
