### ISSUE TITLE
DPD API problem?

### ISSUE THREAD

**Issue by xmarti13** [allegro/allegro-api#10400]
Good morning,

is there any problem with DPD API?
We're not able to create shipment for DPD carrier.

Other carriers works fine, but every DPD shipment returns error Unexpected carrier error
[e.g. trace-id: 795cdc53ccfcec64] 

Is it problem on DPD API or something by us?

Best regards

Pavel

**Comment by MaciejFrackowiak** [comment]
I am verifying your issue with the team, I will come back with an answer.

**Comment by xmarti13** [comment]
Is something new, at this case? 
Our warehouse is not able to finish all the packages, and is waiting for informations.

Best regards.  
Pavel

**Comment by MaciejFrackowiak** [comment]
We are observing a problem with the DPD_CZ carrier. I'll get back to you with more details when I have them. Sorry for the inconvenience.

**Comment by MaciejFrackowiak** [comment]
The issue is fixed now.

**Comment by xmarti13** [comment]
Ok, thank you.
