### ISSUE TITLE
Sandbox Shipments Scope

### ISSUE THREAD

**Issue by jakub-marchewka** [allegro/allegro-api#10407]
Cześć, czy aktualnie na środowisku sandbox występują problemy z allegro:api:shipments:write oraz allegro:api:shipments:read? Podczas uzyskiwania tokenu otrzymuję błąd "Invalid scope: allegro:api:shipments:read". Podane uprawnienie występuje w dokumentacji.

**Comment by MartaNowaczyk** [comment]
Cześć, nie ma z tym problemów. Sprawdź czy masz ten scope w [konfiguracji aplikacji](https://apps.developer.allegro.pl.allegrosandbox.pl/).

**Comment by jakub-marchewka** [comment]
Dzięki, nie miałem nadanych uprawnień do tego scope.
