### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by omursemih** [allegro/allegro-api#10416]
Hi,

I've sent a couple of request to that endpoint;
https://allegro.pl.allegrosandbox.pl/shipment-management/delivery-services and then I started to get 403 forbidden error;

{
    "url": "https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAM5H37XC5ijoAW-DGDA==&cid=3EPPb96h4Ux6SowZku~8bKg4002HDdtxYIy~MUoLOeQprJQTwDr_Nyd~H6qrlZiONL0Q5OUThcrUpcXLltkRjoCgK5owXdDA0VlmIj2o6w7LO~tQHxYvSFO2tp794xQB&referer=https%3A%2F%2Fallegro.pl.allegrosandbox.pl%2Fshipment-management%2Fdelivery-services&hash=77DC0FFBAA0B77570F6B414F8E5BDB&t=bv&s=29544&e=b33bc0fe162db3c27503f2c8b808153b91120133615db2d997ff69c03c6fa6f1"
}

Can you please unblock me?

**Comment by Lukasz-Zurek** [comment]
We cannot do it. Please first of all check on this situation on your side. As we return 403 error code - apparently you are trying to access our resource with a token which is not valid anymore or does not have required scopes.
