### ISSUE TITLE
Problem z autoryzacją Allegro, API blokuje nasze adresy IP

### ISSUE THREAD

**Issue by Red0h** [allegro/allegro-api#10414]
Obecnie tworzymy aplikację BI, która wymaga integracji z interfejsem Allegro Marketplace API w celu uzyskania dostępu do określonych danych kampanii i rozumiemy proces wdrażania. Mamy jednak problemy z etapem autoryzacji (Auth code flow), ponieważ systemy Allegro API blokuje nasze adresy IP. 
Próbowaliśmy uzyskać dostęp za pomocą pięciu różnych niemieckich adresów IP za pośrednictwem Allegro Postman Collection, ale wszystkie żądania są blokowane.

Czy możliwe jest odpytanie szczegółowych danych kampanii i do których konkretnych punktów końcowych API musielibyśmy uzyskać dostęp?

**Comment by MaciejFrackowiak** [comment]
Proszę spróbować obecnie raz jeszcze - czy problem nadal występuje?

**Comment by Red0h** [comment]
tak, Postman nie puszcza testów i blokuje dostęp API do danych [Campaign Name • Ad Group • Ad • Article ID/SKU • Title • Status • Price • Impressions • Clicks • Click-through Rate (CTR) • Costs • Conversions • Conversion Rate • Conversion Value • Cost per Conversion • Average Cost per Click (CPC) • Time Period]

**Comment by MaciejFrackowiak** [comment]
Zasoby, o których wspominasz nie należą do zasobów publicznego API, co oznacza, że nie są dostępne w kolekcji [Allegro REST API public collection](https://www.postman.com/allegro-rest-api/allegro-rest-api/collection/4puh6ls/allegro-rest-api). Autoryzacja code flow powinna zostać przeprowadzona zgodnie z [opisem](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-uzytkownika) w naszym poradniku - jeżeli kroki są wykonane tak, to żadna blokada nie ma prawa się pojawić.
