### ISSUE TITLE
new methods /shipment-management 

### ISSUE THREAD

**Issue by omursemih** [allegro/allegro-api#10427]
I added permission for shipments management from https://apps.developer.allegro.pl.allegrosandbox.pl/.
I re-authorized users but still I get this issue when I use "shipment-management/shipments/create-commands"

: {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"No access to the specified resource.","metadata":{}}]}.

Test environment client id: 657877f29cc34c7589b6e04bbd4b7ea5

**Comment by MaciejFrackowiak** [comment]
I see you resolved your issue because we have returned code 200.

**Comment by omursemih** [comment]
can you check it again?
Time to time it works but now it get broken again.
![2024-12-05 08_56_18-Allegro Developer Apps (sandbox) - zarządzanie dostępem do Allegro REST API](https://github.com/user-attachments/assets/29f0220c-1602-4a3d-97da-fe2b4372e914)

User payload from jwt.io:

{
  "user_name": "106175457",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:messaging"
  ],
  "allegro_api": true,
  "iss": "https://allegro.pl.allegrosandbox.pl",
  "exp": 1733428485,
  "jti": "ea35ed9a-2b0e-4c38-940c-2586150a4db2",
  "client_id": "657877f29cc34c7589b6e04bbd4b7ea5"
}

**Comment by MaciejFrackowiak** [comment]
Please, give me a trace-id of your request.

**Comment by omursemih** [comment]
Do you mean commanId? If yes: 0fe1a5c9-1740-4233-bcee-103e32d41219

**Comment by omursemih** [comment]
e8af4df982e9a030

**Comment by MaciejFrackowiak** [comment]
The token which you used to make a request didn't have a required scope "allegro:api:shipments:write".

**Comment by omursemih** [comment]
![2024-12-05 08_56_18-Allegro Developer Apps (sandbox) - zarządzanie dostępem do Allegro REST API](https://github.com/user-attachments/assets/df87f364-620f-4845-9b8a-3ae5ad108bce)

You can compare edition scope date and re-authorized date.

**Comment by omursemih** [comment]
I see thanks
