### ISSUE TITLE
Prośba o aktywację konta sandbox

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#10434]
Poproszę o aktywację konta santbox **gd_invento**

**Comment by Lukasz-Zurek** [comment]
@gkopec Skonfiguruj proszę jeszcze [wypłaty](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i skorzystaj z symulatora płatności, potwierdzając fikcyjną płatność. Daj proszę znać, a pomogę przy aktywacji.

**Comment by gkopec** [comment]
@Lukasz-Zurek nie mogłem zrobić opcji automatycznej wpłaty na konto

**Comment by Lukasz-Zurek** [comment]
@gkopec Udało się ostatecznie aktywować Twoje konto :)

**Comment by gkopec** [comment]
Dziękuję @Lukasz-Zurek
