### ISSUE TITLE
GPSR: Czy można usunąć Producenta lub Osobę odpowiedzialna?

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#10439]
Zastanawiam się jak można usunąć Producenta lub Osobę, nie musi być przez API :)
Czy planujecie wdrożyć taką możliwość?

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną nie ma takiej możliwości - można tylko edytować rekord. Jeżeli pojawi się realna potrzeba to zespół odpowiedzialny za zasoby z pewnością będzie to rozważać.
