### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by jkaflik** [allegro/allegro-api#10444]
Proszę o aktywację konta: jkaflik

**Comment by MaciejFrackowiak** [comment]
Konto jest już aktywne.

**Comment by jkaflik** [comment]
Dziękuję. Na przyszłość - dlaczego wymagane jest utworzenie issue na GH? Nie jesteście w stanie aktywować "jak leci"?

**Comment by jkaflik** [comment]
Muszę przyznać, że moja zabawa z Waszym API była krótka. WAF mnie zablokował korzystając z Waszej kolekcji Postmana.
![Screenshot 2024-12-07 at 08 40 38](https://github.com/user-attachments/assets/28b83931-a881-4a71-a25e-986ac26fe835)

(`9b564eb1-aca8-54fb-fa00-15f2a4bf2daa`)

**Comment by MaciejFrackowiak** [comment]
Zostałeś zablokowany, ponieważ podczas wywoływania zasobów nie została rozwiązana Captcha.
