### ISSUE TITLE
Adres przekierowań Allegro API -> Subiekt NEXO PRO 

### ISSUE THREAD

**Issue by velnopl** [allegro/allegro-api#10465]
Może głupie pytanie, ale jestem totalnie zielony w tym temacie. 
Konfiguruje połączenie API pomiędzy Allegro a Subiektem NEXO pro. 

Skąd mam wziąć adres przekierowań? W jaki sposób powinien wyglądać?
![image](https://github.com/user-attachments/assets/5525735e-ef0f-4aa1-b545-2960ab6a7e9f)

![image](https://github.com/user-attachments/assets/ee3e380c-3b2d-4dc1-a79b-3ee41a58256d)

**Comment by MartaNowaczyk** [comment]
Chętnie bym Ci pomogła, ale sam musisz to ustalić. Skontaktuj się z obsługą oprogramowania z którego korzystasz.

**Comment by velnopl** [comment]
Dzięki za odpowiedź.
