### ISSUE TITLE
Prośba o odblokowanie konta - Zablokowana sprzedaż

### ISSUE THREAD

**Issue by ttryksza** [allegro/allegro-api#10464]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Prośba o odblokowanie sprzedaży na ALLEGO_SANDBOX dla konta:

Login: **sandbox_omecon**  

Saldo jest =0zł, wykonywanie nadpłaty nic nie daje

Konto nie ma możliwości wystawiania testowych aukcji, komunikat j.n.  

**_Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki, konieczność ponownej weryfikacji lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub skontaktuj się z nami._**

**Comment by MartaNowaczyk** [comment]
Odblokowałam twoje konto sandbox_omecon.

**Comment by ttryksza** [comment]
> Odblokowałam twoje konto sandbox_omecon.

Jest poprawnie, dziękuję
