### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by burnoo** [allegro/allegro-api#10463]
Chciałbym poprosić o aktywację konta sandbox: burnO2

**Comment by MartaNowaczyk** [comment]
Z tego co widzę, dla tego konta nie wybrałeś pełnej opcji sprzedażowej. Zobacz czy w [ustawieniach konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy) masz link na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)", jak tak to skorzystaj z niego, wybierz opcję w stylu "Weryfikacja pełna" i uzupełnij dane.

**Comment by burnoo** [comment]
Wybrałem opcję pełnej sprzedaży

**Comment by burnoo** [comment]
Aktywowane, dziękuję
