### ISSUE TITLE
GPSR - aktualizacja oferty o SafetyInformation

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#10469]
Aktualizacja oferty przebiega prawidłowo:
`PATCH /sale/product-offers/7776032552`
```
{
  "productSet": [
    {
      "safetyInformation": {
        "type": "ATTACHMENTS",
        "attachments": [
          {
            "id": "114485a8-f9d7-47ed-a50a-5264bfb87287"
          },
          {
            "id": "cad4aebb-5f82-46ee-9ddf-d02e334d7fb7"
          }
        ]
      }
    }
  ]
}
```

W odpowiedzi znajdują się zaktualizowane dane, jednak na stronie oferty w zakładce _Bezpieczeństwo, zgodność i ostrzeżenia_ - nie widać załącznika. Czy mogę prosić o sprawdzenie?
Załączniki zostały dodane według tych instrukcji: https://developer.allegro.pl/documentation#operation/createOfferAttachmentUsingPOST

**Comment by MartaNowaczyk** [comment]
Załączniki są dodane. Jednak cały czas pracujemy nad implementacją zmian na stronie internetowej.

**Comment by gkopec** [comment]
Czy wiadomo już kiedy będzie można je przetestować na sandboxie?

**Comment by MartaNowaczyk** [comment]
Niestety nie mam takich informacji, ale pewnie podobnie jak na produkcji.
