### ISSUE TITLE
REST API vs WebAPI

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1047]
Dwa pytania: 

czym w  RestApi  zastąpić pobieranie ofert z parametrem not_sold przez doMyAccount2?

czy jest jakiś odpowiednik pola itEndingInfo (doGetItemsInfo) który informowałby czy oferta zakończyła się w sposób "naturalny" czy też została zamknięta przed czasem?

Pozdrawiam

**Comment by deneb-k** [comment]
Co do drugiej kwestii, to przydałoby się info, czy oferta została zamknięta przez administrację. To ważne, by system nie próbował jej w kółko wznawiać/wystawiać ponownie pod nowym numerem.

Najlepszy byłby odpowiednik pola w starym API, bo taka gimnastyka ze sprawdzaniem kilku pól jest zawsze niepewna i niewygodna.

**Comment by MartaNowaczyk** [comment]
@daneb-k dzięki za sugestię. Przekażę ją do odpowiedniego zespołu.
