### ISSUE TITLE
Dodanie osoby odpowiedzialnej do produktu z oferty. 

### ISSUE THREAD

**Issue by biuronimo** [allegro/allegro-api#10470]
Cześć, 
mogę prosić o weryfikację co robię źle? 
Pytanie:

```
'{"productSet":

  [{
  "responsibleProducer":{"type":"NAME","name":"Acco GB"},
  "responsiblePerson":{"type":"NAME","name":"Acco DE"},
  "safetyInformation":{"type":"NO_SAFETY_INFORMATION"}
  }]

}'
```
`trace-id = 'bea7cf2b191f4d7'`
Odpowiedź: 
`'Unknown properties found in the request.'`

**Comment by biuronimo** [comment]
Ok, już wiem. Dla   `"responsiblePerson"` zbędne było `"type":"NAME"` 
Teraz, odpowiedzi `trace-id = '8638bfeaf1b5b7f4'` mam status 200, ale po wejściu w edycję oferty przez przeglądarkę nie widać naniesionych zmian (osoba odpowiedzialna nadal jest do wyboru). 
Bez edycji - na podglądzie oferty po kliknięciu na "[Osoba odpowiedzialna za produkt](https://allegro.pl/oferta/niszczarka-automatyczna-optimum-autofeed-150x-p4-15543144927#responsible-entity)" dane są widoczne. 

Drugie pytanie: Czy osoba odpowiedzialna może być dodana jedynie do pierwszego produktu w zestawie?
Jeśli  tak to czy planujecie umożliwić dodanie jej do każdego produktu ?

**Comment by MartaNowaczyk** [comment]
1. Cały czas pracujemy nad implementacją zmian na stronie internetowej, stąd może nie być to jeszcze widoczne.
2. Tak, na ten moment tylko dla głównego produktu. Mamy na uwadze dodanie takiej opcji. Jeśli taka możliwość się pojawi zamieścimy stosowny komunikat.

**Comment by biuronimo** [comment]
Czy możliwość dodania osoby odpowiedzialnej do każdego produktu w zestawie planujecie wdrożyć przed przed 13.12.2014 czy raczej w późniejszych aktualizacjach? Przy okazji zauważyłem, że jeden z większych integratorów (na B) przy wystawianiu oferty dodał opcję "Produkt wprowadzony do obrotu na terenie UE przed 13.12.2024" Czy mogę prosić o informację co po stronie oferty ma ustawiać to ustawienie?

**Comment by MartaNowaczyk** [comment]
Chcielibyśmy wdrożyć to tak szybko jak to możliwe, ale szczegółowej daty niestety nie mogę podać. Takiej opcji "Produkt wprowadzony do obrotu na terenie UE przed 13.12.2024" nie mamy w API na ten moment.

**Comment by MartaNowaczyk** [comment]
Chyba, że nie chodzi o oddzielną funkcjonalność tylko parametr i ustawienie w ofercie integrator B bierze z parametrów. W takim przypadku w ofercie można dodać parametr:
```
"id": "250553",
"name": "Produkt wprowadzony do obrotu na terenie UE przed 13.12.2024"
```

**Comment by biuronimo** [comment]
Czy mogę prosić o informację do czego służyć ma ten parametr?

**Comment by MartaNowaczyk** [comment]
Można go ustawić w ofercie jak inny parametr ofertowy i wybrać wartość tak lub nie.

**Comment by biuronimo** [comment]
Dziękluję za niejasną odpowiedź. Dla zainteresowanych: https://spolecznosc.allegro.pl/t5/zaawansowani-sprzedawcy/rozporz%C4%85dzenie-gpsr-co-musisz-wiedzie%C4%87-w%C4%85tek-aktualizowany/td-p/923089

> Dzięki temu wystawisz ofertę bez podawania informacji o producencie. Pamiętaj jednak, że należy wypełniać parametr zgodnie ze stanem faktycznym. Odpowiedzialność za wprowadzenie błędnych informacji spoczywa na Tobie. :megafon:
> 
> WAŻNE: Możliwość zaznaczenia tego parametru grupowo zostanie udostępniona 20 grudnia.
> 
> Parametr znajdziecie w sekcji  "informacje o bezpieczeństwie", po kliknięciu opcji "więcej parametrów".
