### ISSUE TITLE
OfferImagesNotAvailableException - Nie można obecnie pobrać zdjęć oferty. Spróbuj ponownie.

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#10486]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
trace-id: 7a06ab08ba5c66b2

POST /sale/product-offers - przy próbie dodania nowej oferty.

```json
{
   "errors":[
      {
         "code":"OfferImagesNotAvailableException",
         "message":"Unable to download the offer images at this time. Try again.",
         "details":"OfferImagesNotAvailableException",
         "path":null,
         "userMessage":"Nie można obecnie pobrać zdjęć oferty. Spróbuj ponownie.",
         "metadata":{
            
         }
      }
   ]
}
```

W logach widzę, że wasz downloader łączy się z naszymi serwerami:
[11/Dec/2024:11:24:40 +0100] "GET /pubs/uploads/aa9c047deabd4edbacc2ef11eff11ac7.png HTTP/1.1" 200 984572 "-" "Allegro-ImageDownloader/1.0"
[11/Dec/2024:11:24:40 +0100] "GET /pubs/uploads/91c85a49a65f4c1a81adadf79fa39ccb.png HTTP/1.1" 200 1238129 "-" "Allegro-ImageDownloader/1.0"

Do dzisiaj działało to bez problemu. W czym problem?

**Comment by gkopec** [comment]
U nas to samo

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie, weryfikuję sprawę z zespołem.

**Comment by DamianKAtomStore** [comment]
Mamy to samo pomimo tego że zdjęcia są wystawione poprawnie

**Comment by MaciejFrackowiak** [comment]
Problem został wyeliminowany, przepraszam za utrudnienia.
