### ISSUE TITLE
Raport Allegro operations all

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#10482]

**Comment by Vitalka13** [comment]
Dzień dobry!
Proszę powiedzieć, czy jest możliwość, aby uprawiony użytkownik z dostępem do wkładki finanse mógł pobierać raport  Allegro operations all i otrzymywać ten raport na swój email, pod którym użytkownik został zalogowany?

**Comment by AureliuszBrussy** [comment]
Za pomocą publicznego API Allegro możesz pobrać historię operacji płatniczych (jako zautoryzowany użytkownik) używając [GET /payments/payment-operations](https://developer.allegro.pl/documentation#operation/getPaymentsOperationHistory). Nie można natomiast zlecić utworzenia raportu i wysłania go na adres mailowy użytkownika.
