### ISSUE TITLE
Oferty w "zawieszeniu"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1048]
Jakiś czas temu zakończyliście moje oferty z nieregulaminowym opisem.
Mam teraz taką sytuację, że oferta pojawia się w /sale/offers jako ACTIVE natomiast nie pojawia się w /offers/listing.
W serwisie jak wyszukam po numerze oferty to mam info "sprzedaz zakończona" natomiast w moim koncie->moje oferty widnieje jako aktywna.

**Comment by MartaNowaczyk** [comment]
@kfijalko sprawdzam twój przypadek, dam znać gdy coś ustalę.

**Comment by MartaNowaczyk** [comment]
@kfijalko możesz podać przykładowy numer oferty?

**Comment by kfijalko** [comment]
7331092749

**Comment by MartaNowaczyk** [comment]
@kfijalko dzięki za info. Potwierdziliśmy twoją wersję, teraz sprawdzamy przyczynę.

**Comment by kfijalko** [comment]
Dzień dobry,
mam taką ofertę:7746027896
jest w allegro.pl, nie ma w "moje oferty"
proszę poprawić

**Comment by kfijalko** [comment]
Dzień dobry,
oferta: 7764928090 od 2 dni jest w statusie 'activating',
proszę popchnąć dalej 
@MartaNowaczyk 
poprzednie wpis: sytuacja nadal występuje

**Comment by kfijalko** [comment]
Oferta 7734245689 również w statusie activating od 2 dni

**Comment by MartaNowaczyk** [comment]
@kfijalko działamy

**Comment by MartaNowaczyk** [comment]
@kfijalko w tej chwili oferty powinny wyświetlać się poprawnie

**Comment by kfijalko** [comment]
fajnie, dziękuję
w ciągu dnia sprawdzę co przyszło i dam znać
