### ISSUE TITLE
Edit an offer

### ISSUE THREAD

**Issue by omursemih** [allegro/allegro-api#10487]
PATCH-https://api.{environment}/sale/product-offers/{offerId}
I use this endpoint to update available to stock. When I set 0 quantity, offer status is changed automatically to "zakończona" status.
But when I update available with > 0  amount. Offer status was still same "zakończona".
What should I do it to sell it back?

**Comment by MaciejFrackowiak** [comment]
You have to change its publication.status to "ACTIVE".
