### ISSUE TITLE
Data ważności nieużywanych załączników

### ISSUE THREAD

**Issue by mateuszWd** [allegro/allegro-api#10488]
Witam,
W naszej integracji z Allegro API może wyniknąć sytuacja, że pomiędzy uploadem attachmentu, a wystawieniu oferty / przypisaniu do oferty może upłynąć pewien czas i pytanie czy takie nieużywane Attachmenty mają swój termin ważności, po którym zostaną usunięte ?

Pozdrawiam,
Mateusz

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma określonego takiego czasu.

**Comment by mateuszWd** [comment]
Dziękuję za odpowiedź
