### ISSUE TITLE
"Obca" dopłata w REST API i Web API

### ISSUE THREAD

**Issue by TinTours** [allegro/allegro-api#1049]
Mamy apkę, która wiąże nam wypłatę z PayU i P24 (konkretny przelew na naszym koncie) z transakcjami użytkowników.

Wczoraj w zasobach zarówno WebAPI (doGetMyIncomingPayments) jak i REST API (order/checkout-forms?status=READY_FOR_PROCESSING) pojawiła nam się dopłata użytkownika, który był kiedyś naszym klientem, natomiast dopłatę wykonał na rzecz innego sprzedającego. Zasób payTransMainId wskazuje na poprzedni zakup klienta u nas.

W panelu Allegro nie jest widoczna ta dopłata, nie została także wypłacona na nasze konto, więc podejrzewamy, że klient się nie pomylił i transakcja nie jest "nasza".

**Comment by MartaNowaczyk** [comment]
@TinTours podeślij proszę pełne cURL-e z tymi danymi oraz paczki XML z responsem i requestem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) allegro - z dopiskiem, że sprawa dotyczy zgłoszenia #1049 na GitHubie.
