### ISSUE TITLE
Problem z nadawaniem niektórych przesyłek WzA

### ISSUE THREAD

**Issue by SDSMA12412** [allegro/allegro-api#10496]
Dzień dobry,

czy ktoś posiada ten sam problem lub jego rozwiązanie dotyczące zwrotu błędu z API podczas próby nadania niektórych przesyłek z formami dostawy z WzA dobijając się do API allegro?

Zwracany komunikat o treści:

"Błąd przy tworzeniu paczki: 1.You cannot create a shipment using the Allegro Standard agreement. The method assigned to this order is the Separate Agreement. Change the agreement and try again."

Tutaj jest to np. forma dostawy "Allegro Kurier DPD".

Dotyczy to tylko niektórych przesyłek, część przez API przechodzi, część nie.
Zwracany komunikat pojawia się z dwóch różnych środowisk - awocado shipping oraz way2send.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, nie podajesz konkretnego przypadku, ale wygląda na to, że próbujesz użyć nieodpowiedniej usługi dostawy, która jest niezgodna z tą w zamówieniu (wybraną przez kupującego). Poprawną metodę dostawy możesz pobrać bezpośrednio z zamówienia. Identyfikator znajdziesz w polu "delivery.method.id".

**Comment by SDSMA12412** [comment]
Podaję dwa takie przykłady:
25636740-b574-11ef-b577-b95619ea60c8
4496ff10-b58c-11ef-a1da-1556169e312d

**Comment by MartaNowaczyk** [comment]
Z tego co sprawdziliśmy w requestach podajecie inną metodę dostawy niż jest w zamówieniu. Np. ostatnie zamówienie, które sprawdzałam to dla zamówienia d928ac00-b294-11ef-a33d-fd2e1eb9bba2 w zamówieniu jest  metoda dostawy "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93" (Allegro Paczkomaty InPost"), a wysyłaliście "09164667-daa5-42dc-8087-33d7485790ac" (Allegro Automat ORLEN Paczka).

**Comment by SDSMA12412** [comment]
Wkradł się mały błąd, to jest poprawny przykład: 25636740-b574-11ef-b577-b95619ea60c8

**Comment by MartaNowaczyk** [comment]
Tego zamówienia nie widzę w logach dla tworzenia przesyłki. Żeby to dokładnie sprawdzić potrzebowałabym trace-id z nagłówka odpowiedzi z błędem który podajesz. Uzyskasz go od obsługi aplikacji, gdzie tworzysz przesyłki.

**Comment by SDSMA12412** [comment]
Prawdopodobnie wiem już w czym leży problem, W2S w przypadku więcej niż jednego zamówienia od klienta allegro tworzy adnotacje login-2 lub login-3 (np. 2 zamówienie danego klienta, lub 3). Jednakże podstawiany jest 1 wygenerowany przez allegro adres email, a nie kolejne (różne) 2 lub 3, tym samym W2S próbuje zrobić eksport ID listu cały czas do 1 zamówienia klienta.
Zostawię taki trop gdyby ktoś się z tym jeszcze głowił. Zgłoszone do W2S.

**Comment by MartaNowaczyk** [comment]
Trochę to tak wygląda, bo zamówienie, które znalazłam i przedstawiłam jako przykład należy do tego samego kupującego.

**Comment by SDSMA12412** [comment]
Potwierdzam, problem w W2S już rozwiązany.
