### ISSUE TITLE
Handling time question

### ISSUE THREAD

**Issue by Lohdern** [allegro/allegro-api#10497]
Hello, I would like to know if is there any chance to get the handling_time on the batch endpoint (https://api.allegro.pl/_sale/offers?limit=100&offset=0_)? Or is there any endpoint where I can get this information in a batch way?
    "delivery": {
        "shippingRates": {
            "id": "fb090697-e4af-4335-b125-ee85d02d1086"
        },
        _"handlingTime": "PT0S",_
        "additionalInfo": null,
        "shipmentDate": null
    },
Thanks for the answer.

**Comment by MartaNowaczyk** [comment]
Hello, we do not have such a batch endpoint that will give such a result.
