### ISSUE TITLE
Status "ACTIVATING"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1050]
Mam ofertę 7734245773.
W https://api.allegro.pl/sale/offers?offset=6000&limit=1000 ma status:
            "publication": {
                "status": "ACTIVATING",
                "startingAt": null,
                "startedAt": null,
                "endingAt": null,
                "endedAt": null
            },
W https://api.allegro.pl/sale/offers/7734245773 ma status:
    "publication": {
        "duration": null,
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": null
    },
Zobaczyłem to wczoraj wieczorem, teraz jest tak samo więc nie wstrzeliłem się w jakąś "nanosekundę" kiedy się zmienia status oferty, tylko trwa to od kilku godzin.

Zerknijcie, poprawcie, dacie znać.

**Comment by MartaNowaczyk** [comment]
@kfijalko Zerknęłam, sprawdziłam - potwierdzam i dam znać :)
