### ISSUE TITLE
Odblokowanie sprzedaży - Sandbox

### ISSUE THREAD

**Issue by testytema** [allegro/allegro-api#10518]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, 

proszę o odblokowanie konta: testytema.

Wyświetla się informacja:
Sprzedaż na Twoim koncie jest obecnie zablokowana. Powodem mogą być nieopłacone rachunki lub inne naruszenia Regulaminu. Aby odblokować możliwość sprzedaży, ureguluj zaległe płatności lub skontaktuj się z nami.

Niestety nie widzę, żeby były jakieś zaległości w płatnościach.

Dziękuje.

**Comment by AureliuszBrussy** [comment]
@testytema usunąłem blokadę.

**Comment by testytema** [comment]
Dziękuję, działa.
