### ISSUE TITLE
Pytanie o statusy ofert w https://api.allegro.pl/sale/offers

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1051]
Nie bardzo mogę znaleźć odpowiedź w dokumentacji.
Wszystkie moje oferty są BUY_NOW i "do wyczerpania zapasów".
Pytanie:
Czy jeżeli oferta zostanie już raz wystawiona i otrzyma status ACTIVE to może przejść w inny status niż ENDED?
Ewentualnie czy możecie podać jakiś diagram stanów dla oferty?

**Comment by MartaNowaczyk** [comment]
@kfijalko Nie mam takiego diagramu, ale ogólnie wygląda to tak INACTIVE -> ACTIVATING -> ACTIVE -> ENDED czyli z ACTIVE może przejść tylko w ENDED, z ENDED w ACTIVATING, ACTIVE lub się zarchiwizować.
Aktualizacja stanów magazynowych i cen nie powinna zmieniać stanu oferty.

**Comment by MartaNowaczyk** [comment]
![image](https://user-images.githubusercontent.com/38425363/50970820-c7dfad00-14e2-11e9-9f3a-0ff41c571a76.png)
Znalazł się jakiś ;P

**Comment by kfijalko** [comment]
Ten widziałem, myślałem że sytuacja jest bardziej skomplikowana.
Wygląda na to, że będę miał jeszcze jedno zgłoszenie. Pojawiają  mi się 'ACTIVATING', tylko muszę złapać konkretny przypadek.
Dziękuję za odpowiedź i dam znać jak coś znajdę (w osobnym wątku).
