### ISSUE TITLE
Moje zgłoszenia zmian w produktach

### ISSUE THREAD

**Issue by Vitalka13** [allegro/allegro-api#10517]

**Comment by Vitalka13** [comment]
Dzień dobry!
Wcześniej, kiedy uprawiony użytkownik zgłaszał o błąd, to we wkładce "Moje zgłoszenia zmian w produktach" miał listę tylko wyłącznie swoich zgłoszeń. A teraz od 13.12 we wkładce zapisują się zgłoszenia wszystkich użytkowników i nie ma możliwości łatwo znaleźć potrzebne zgłoszenie. To bardzo utrudnia pracę, więc czy jest możliwość powrócić do poprzednich ustawień?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, tematy związane ze stroną internetową proszę zgłaszać za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt). Na forum świadczymy wsparcie stricte w tematach związanych z API.
