### ISSUE TITLE
@raffx94 oba konta powinny już być aktywne.

### ISSUE THREAD

**Issue by LetroLiu** [allegro/allegro-api#10522]
Hello!
Please activate my account:
it_cn@grll.co.uk

**Comment by PrzemyslawLukanowski** [comment]
Hello, please complete the [payout settings](https://salescenter.allegro.com.allegrosandbox.pl/funds-and-operations-history?dateTo=2024-12-17&dateFrom=2024-11-17) (you can use a fake bank account number) - after that I will be able to activate your account.

**Comment by LetroLiu** [comment]
Already added, please help handle it, thank you!

**Comment by PrzemyslawLukanowski** [comment]
Sorry, but I see there are additional steps you need to take because of the NO-EEA account - you need to fill the documents section and send the application. Please let me know when it's done.

**Comment by LetroLiu** [comment]
Completed, please help confirm if the conditions are met. Thank you!

**Comment by PrzemyslawLukanowski** [comment]
Yes, everything is ok, I activated your account.
