### ISSUE TITLE
Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Marka - parametr 7108

### ISSUE THREAD

**Issue by twylandowski-cfi** [allegro/allegro-api#10524]
Cześć,
Wysyłam propozycję nowego produktu poprzez endpoint https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals.
W wymaganym parametrze Marka (7108) podaję wartość ValueIds -> 7108_52 jako wartość "inna".

Dostaję błąd o statusie 422 o treści "Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Marka".

Do testów zmieniam markę na dowolną inną. Dostaję też błąd brakującego parametru wymaganego o id 219629 (Oryginalne opakowanie producenta). Tego parametru nie ma na liście kiedy pobieram listę wszystkich parametrów dla danej kategorii (id: 5549).

Pytanie pierwsze czy można też wyłączyć sprawdzanie EAN w bazie GS1?
Czy jest jakaś lista parametrów wymaganych bez względu na kategorię? Jak pobrać definicję przykładowego parametru 219629 albo dla wyrobów medycznych mamy 249829?

Pozdrawiam,
Tomasz

**Comment by PrzemyslawLukanowski** [comment]
Cześć,

> Dostaję błąd o statusie 422 o treści "Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Marka".

Ten błąd oznacza, że po wybraniu wartości niejednoznacznej ("inna") musisz przekazać własną wartość w polu "values". Więcej informacji znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasna-wartosc-parametru).

> Do testów zmieniam markę na dowolną inną. Dostaję też błąd brakującego parametru wymaganego o id 219629 (Oryginalne opakowanie producenta). Tego parametru nie ma na liście kiedy pobieram listę wszystkich parametrów dla danej kategorii (id: 5549).

Odpytałem przed chwilą GET /sale/categories/5549/parameters i parametr 219629 znajduje się na liście. Rzeczywiście nie zwracamy go dla GET /sale/categories/5549/product-parameters, ponieważ nie powinien być wymagany do utworzenia produktu, gdyż nie opisuje on produktu (posiada flagę `options.describesProduct` równą false). 
Czy na pewno komunikat otrzymałeś podczas żądania do POST /sale/product-proposals a nie do POST /sale/product-offers? Jeśli w pierwszym przypadku, podaj proszę przykładowe trace-id, jeśli w drugim - wszystko się zgadza, ponieważ parametr nie jest wymagany do utworzenia produktu, ale jest to stworzenia oferty.

> Pytanie pierwsze czy można też wyłączyć sprawdzanie EAN w bazie GS1?

Niestety nie mamy takiej możliwości.

> Czy jest jakaś lista parametrów wymaganych bez względu na kategorię? Jak pobrać definicję przykładowego parametru 219629 albo dla wyrobów medycznych mamy 249829?

Każda kategoria posiada specyficzny zestaw wymaganych parametrów, dlatego musisz je pobrać za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) - w odpowiedzi zasobu znajdziesz pełen zestaw informacji o parametrach w danej kategorii.

**Comment by twylandowski-cfi** [comment]
Dziękuję, już wszystko jasne. Rzeczywiście przeoczyłem, że parametry dla produktu są inne niż dla oferty.
