### ISSUE TITLE
Status ENDED i publication_ended_at

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1052]
Mam oferty, które mają status ENDED i nie mają wypełnionej daty zakończenia.
Oferty pobieram /sale/offers/.
Mam 11 takich ofert.
Przykłady:
6666843348
--
6700902378

**Comment by MartaNowaczyk** [comment]
@kfijalko Nie dziwię sie, że nie mają dat - nie powinieneś nawet dostać tak "starych" ofert. Sprawa do wyjaśnienia.

**Comment by kfijalko** [comment]
Ile czasu oferta może występować w statusie ENDED w metodzie /sale/offers/?

**Comment by MartaNowaczyk** [comment]
Tak jak na liście ofert w allegro - 90 dni od jej zakończenia - czyli gdy przejdzie do archiwum.

**Comment by MartaNowaczyk** [comment]
@kfijalko podasz wszystkie ID tych ofert? Poprawimy, żebyś nie dostawał błędnych wyników.

**Comment by kfijalko** [comment]
mam takie numerki - nie mają category-id

6666835865
6700902378
6700924846
6700924924
6700970612
6700970845
6700971098
6700971461
6700972119
6700972816
6700974098

**Comment by MartaNowaczyk** [comment]
@kfijalko dzięki, poprawimy.

**Comment by MartaNowaczyk** [comment]
@kfijalko oferty już w kolejce do przeindeksowania, więc niedługo powinno być ok.

**Comment by MartaNowaczyk** [comment]
@kfijalko oferty już w kolejce do odświeżenia, więc niedługo powinno być ok.

**Comment by kfijalko** [comment]
dziękuję, zamykam ten wątek, jak znajdę coś nowego to założę nowe zgłoszenie
pozdrawiam,kf
