### ISSUE TITLE
List przewozowy

### ISSUE THREAD

**Issue by nukotel** [allegro/allegro-api#1053]
Niedługo dodawanie numeru listu przewozowego do karty transakcji będzie wymagane z Państwa strony bezwarunkowo. Czy metoda do dodawania listu przewozowego pojawi się przed wprowadzeniem wyżej wspomnianego obowiązku?

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o REST API planujemy zrobić to do końca marca. W WebAPI jest jeszcze metoda, która to obsługuje - [doAddPackageInfoToPostBuyForm.](https://allegro.pl/webapi/documentation.php/show/id,744)

**Comment by MartaNowaczyk** [comment]
Metoda do dodawania numerów przesyłek jest już dostępna https://github.com/allegro/allegro-api/issues/1217
