### ISSUE TITLE
createPickup NotFoundException

### ISSUE THREAD

**Issue by matcapi** [allegro/allegro-api#10535]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

POST shipments-management/pickups/create-commands zwraca NotFoundException.
trace-id:d7dc5774593a7b07

**Comment by AureliuszBrussy** [comment]
Widzę literówkę w ścieżce, jest:

`/shipments-management/pickups/create-commands`

Powinno być:

`/shipment-management/pickups/create-commands`

**Comment by matcapi** [comment]
:facepalm: 

Dziękuję
