### ISSUE TITLE
Menedżer sprzedaży - aktualizacja ceny

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#1054]
Cześć, czy jest możliwość, aby change-price-commands aktualizował cenę także w MS?

**Comment by MartaNowaczyk** [comment]
@rtnet-pl o jakiej zakładce w MS mówimy? "OFERTY"?

**Comment by rtnet-pl** [comment]
Przepraszam, już nieaktualne - źle zrozumiałem pytanie od Klienta.
