### ISSUE TITLE
problem z logowaniem do konta via WEBapi

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#1055]
Dzień dobry,
Pomimo usilnych starań nie jestem w stanie zalogować się do nowego konta via WEBApi

taki oto komunikat otrzymujemy:
faultstring - Zła nazwa użytkownika i/lub hasło. Sprawdź też, czy nie masz włączonych haseł do aplikacji. Jeśli tak - podaj hasło do aplikacji, zamiast hasła do konta. faultcode - ERR_USER_PASSWD

Te same dane do logowania pozwalają na zalogowanie się do konta przez przeglądarkę.
Jedyna różnica pomiędzy działającymi kontami jest taka  że podczas logowania używamy ID zamiast klucza tak jak to opisaliście w dokumentacji. Niestety, nie daje się zalogować. Konto sma_TYC.

Proszę o sprawdzenie po swojej stronie. Wszystkie pozostałe konta działają okey.

Pozdrawiamy www factory

**Comment by wwwfactory** [comment]
Z tego co widzę włączone były hasła do aplikacji - choć jak widzę nie było zdefiniowanej żadnej aplikacji. 
proszę się wstrzymać z szukaniem błędu ...

**Comment by MartaNowaczyk** [comment]
@wwwfactory ok

**Comment by wwwfactory** [comment]
zamykamy - jak się okazuje włączone były hasła do aplikacji, choć żadne hasła nie były wygenerowane, taka dziwna sytuacja.
