### ISSUE TITLE
GetProductOffer error

### ISSUE THREAD

**Issue by Lohdern** [allegro/allegro-api#10555]
Hello there,

I would like to ask a question related to get product offer.
We are getting the following error when we would like to request a product offer by id:
**Error calling GetProductOffer: {"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer","metadata":{}}]}**
It worked couple of days ago. The only thing changed since that our company email address switched from "theimporttuning@gmail.hu" to "allegro@jazini.hu". As our offers were uploaded with the previous email maybe it can be moved to the new one or how should it be handled? The first email cannot be used/logged in anymore.

Thanks for your answer.

**Comment by PrzemyslawLukanowski** [comment]
Hello, if offers are on the same account as before, changing the email address shouldn't be an issue here. Could you please send me a sample trace-id or offer ID, which you attempted to retrieve?

**Comment by PrzemyslawLukanowski** [comment]
On the account 1266****3 which is connected with the mentioned email address I don't see any 403 for GET /sale/product-offers/{offerId}, so maybe you are authorized as a different seller, who indeed, is not an owner of these offers? You can decode your token and check it, for example [here](https://jwt.io/).

**Comment by Lohdern** [comment]
Here is an offerId: "Id": "16934981296", also I tried to make a request just now, maybe you can see that.
I will try to relogin.

**Comment by PrzemyslawLukanowski** [comment]
Yes, I see it. You are authorized as a different seller (1082***73), who is not an owner of this offer - that's the cause of the returned error.

**Comment by Lohdern** [comment]
Here is an offerId: "Id": "16934981296", also I tried to make a request just now, maybe you can see that.
I will try to relogin.
Based on the jwt token:

  "user_name": "108****73",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:fulfillment:read",
    "allegro:api:profile:write",
    "allegro:api:fulfillment:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:shipments:write",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read",
    "allegro:api:shipments:read",
    "allegro:api:messaging"
  ],
We have the right scope. Which part should I look at?

**Comment by PrzemyslawLukanowski** [comment]
Scopes are not the problem, but the user you are authorized as - "user_name": "108xxxx73". Offers belong to user 1266xxx3 and as this user, you should authorize the application to generate a token, that will give you the possibility to perform operations on behalf of this account.

**Comment by Lohdern** [comment]
Okay after relogin it is working. I do not know how we authenticated to another account as we have just one, but thanks. Resolving the ticket.
