### ISSUE TITLE
Brak wymaganych uprawnień do zasobu.

### ISSUE THREAD

**Issue by PolishDywan** [allegro/allegro-api#10551]
Witam serdecznie, próbowałem wczytać oferty w SandBox ale przy próbie załadowania wyskakuje mi błąd:

`Brak wymaganych uprawnień do zasobu`. 

Co mogę zrobić w takim przypadku? 
Korzystam z `client_credentials`

`info: Server running at http://localhost:3001 {"timestamp":"2024-12-18T19:57:19.089Z"}
info: Requesting new access token {"timestamp":"2024-12-18T19:57:19.794Z","tokenUrl":"https://allegro.pl.allegrosandbox.pl/auth/oauth/token"}
info: Successfully obtained new access token {"timestamp":"2024-12-18T19:57:19.977Z"}`

static async getOffers(offset: number = 0, limit: number = 100): Promise<AllegroOffersResponse> {
    try {
      return await this.retryOperation(async () => {
        const api = await this.getInstance();
        const response = await api.get<AllegroOffersResponse>("/sale/offers", {
          params: { offset, limit }
        });
        
        logger.info("Pobrano ${response.data.offers?.length || 0} ofert");
        return response.data;
      });
    } catch (error) {
      return this.handleError(error);
    }
  }`

**Comment by MaciejFrackowiak** [comment]
Autoryzacja "client_credentials" nie pozwala na pobranie listy ofert - zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) wymaga autoryzacji [bearer-token-for-user](https://developer.allegro.pl/documentation/#section/Authentication/bearer-token-for-user), czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by PolishDywan** [comment]
Czyli nie mogę sprawdzić swojej listy ofert bez autoryzacji z kontem Allegro?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak. Lista ofert należy do konkretnego użytkownika, stąd wymóg autoryzacji.

**Comment by PolishDywan** [comment]
Dziękuję ślicznie, zamykam.
