### ISSUE TITLE
Lista transakcji dla danej aukcji w REST API

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#1056]
:bulb: **Sugestia**

Czy możliwe byłoby stworzenie zasobu działającego na podobnej zasadzie jak metoda: https://allegro.pl/webapi/documentation.php/show/id,121 tylko dodatkowo, aby zwracała przynajmniej informacje o identyfikatorze kupującego ? Chodzi mi oczywiście o REST API

Potrzebuję ich bo u nas monitoring sprzedaży działa w ten sposób, że pobiera zamówienia, ale tylko jeśli dana aukcja istnieje u nas w systemie. Jeśli nie, to jest ona pomijana na etapie monitoringu sprzedaży (journala). Zdarzają się więc takie sytuacje w których klient doda aukcje do naszego systemu po tym jak zamówienie zostało złożone przez klienta co powoduje że nie jest ono zaciągane. Jedyne rozwiązanie na chwilę obecną to przelecenie na nowo całego journala co przy większych klientach może chwilę potrwać, ale nie jest to rozwiązanie satysfakcjonujące

**Comment by MartaNowaczyk** [comment]
@kormichu czego ci dokładnie brakuje oprócz dodatkowego id kupującego?

**Comment by kormichu** [comment]
Hmm jakbym miał wybierać to widziałbym to w takiej samej formie jak w /order/events: https://developer.allegro.pl/documentation/#/order-management/get_order_events

Najbardziej interesują mnie te 3 rzeczy: lineItems.id, checkoutForm.id, buyer.id
Mając te 3 rzeczy mógłbym wpiąć się tym samym typem danych do obecnego mechanizmu do obsługi zadań po przeleceniu journala

**Comment by MartaNowaczyk** [comment]
@kormichu nie możesz zatem skorzystać właśnie z zasobu /order/events? W REST API nie znajdziesz dokładnego odzwierciedlenia tej metody doGetTransactionsIDs. Sugestię oczywiście przekażę do odpowiedniego zespołu. Trzeba się jednak nastawić, że niektóre schematy działania trzeba będzie przerobić przy przejściu na REST API.

**Comment by kormichu** [comment]
@MartaNowaczyk ależ korzystam z journala. Nie będę go jednak całego ponownie skanował tylko po to aby wyciągnąć informacje o transakcjach dla pojedynczej aukcji, którą klient przypisał do produktu w sklepie. To nie trzyma się kupy. U nas jest to tak zrobione, że aukcje nie dodają się z automatu jeśli pojawią się po Waszej stronie tylko na wyraźne żądanie klienta. Zamówienia zaś pobierane są tylko dla aukcji które istnieją w sklepie. Każdą aukcje może klient w dowolnej chwili usunąć i tym samym reguluje sobie co chce, aby zaciągało się do sklepu

**Comment by MartaNowaczyk** [comment]
@kormichu czyli, jeśli dobrze rozumiem, chciałbyś dodatkowy zasób z danymi tj. lineItems.id, checkoutForm.id, buyer.id.

Staram się zrozumieć czego dokładnie potrzebujesz, ale nie mam pełnego obrazu waszego działania. Jak to wygląda w praktyce, klient wprowadza produkt, którego nie było w systemie (ale był na allegro i ktoś go kupił). Jak powiązujecie ofertę allegro z produktem w waszym systemie? Robi to klient ręcznie? Następnie co robi? Klika, sprawdź czy w ofercie dokonano zakupu? Czy jak?

**Comment by kormichu** [comment]
Tak, dokładnie. Potrzebuje dodatkowy zasób z tymi danymi dla wybranej aukcji

System wygląda tak, że klient może od Was zaciągnąć wszystkie aukcje na wyraźne żądanie (kliknięcie w przycisk "zaimportuj") i wiąże je jednocześnie z produktami w sklepie i ich stanem magazynowym. Taki przycisk może klikać wielokrotnie dodając tym samym nowe aukcje do sklepu. Jest też druga opcja z manualnym dodawaniem aukcji do produktu. Każdą aukcje może też klient odwiązać od produktu. Opcje te zostały dodane z tego powodu, aby klient był w stanie sam zarządzać tym jakie zamówienia, z których aukcji trafiają do sklepu. W praktyce wygląda to tak, że pobierane są tylko te zamówienia które zostały złożone na aukcjach istniejących w sklepie. Pod spodem mamy oczywiście monitoring journala, ale wystarczy że zamówienie pojawi się u Was wcześniej niż klient był w stanie je przypisać do produktu (obojętnie czy ręcznie czy przez przycisk "zaimportuj") i wtedy jest ono pomijane. 

Chciałbym zrobić w ten sposób, że po imporcie aukcji lub ich ręcznym przypisaniu pobierałbym informacje o brakującyh zamówieniach i dodawałbym je do sklepu. W chwili obecnej jedyną opcją jest ponowne skanowanie całego journala. Mogę zrobić też tak, że wszystkie zamówienia będą się od Was zaciągać, ale byłoby to o tyle problematyczne, że stan magazynowy produktów by się nie zgadzał. Produkty z zamówień nie byłyby w końcu przypisane do produktów w sklepie bo nie ma żadnego kryterium porównawczego. Automatyczne zaciąganie aukcji też nie byłoby dobre bo klient traciłby kontrolę nad tym co dostaje w sklepie

**Comment by MartaNowaczyk** [comment]
@kormichu sugestię zgłosiłam do odpowiedniego zespołu, ale nie obiecuję, że coś takiego powstanie. Na ten moment nikt inny takiego zapotrzebowania nie zgłaszał, dlatego ciężko będzie ruszyć ten temat.
