### ISSUE TITLE
Business Account Activation on Sandbox 

### ISSUE THREAD

**Issue by risky-raya** [allegro/allegro-api#10561]
Hello team! I tried to convert my regular accounts to business one on sandbox app. But after several days I'm unable to convert it. Here are my login: dodol and bisnis. Can you activate business on both accounts or atleast one (dodol) of them? Thank you ^^

**Comment by AureliuszBrussy** [comment]
The account **dodol** is already converted, I accepted the change. In the case of the **bisnis** account, the process was interrupted at some point and the data is missing to complete the conversion. Could you make sure you have gone through the conversion process to the end?
