### ISSUE TITLE
Wymagany parametr, którego nie zwraca endpoint /sale/categories/:categoryId/product-parameters

### ISSUE THREAD

**Issue by fzdunek** [allegro/allegro-api#10579]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbując wystawić produkt w kategorii o ID 257689 dostaję zwrotkę 
"code" => "ConstraintViolationException.MissingRequiredParameters"
    "message" => "Missing required parameters: 15808"
    "details" => "ConstraintViolationException.MissingRequiredParameters"
    "path" => "parameters"
    "userMessage" => "Uzupełnij parametry obowiązkowe: Liczba opon w ofercie."
    
ale gdy odpytuję endpoint {{baseUrl}}/sale/categories/:categoryId/product-parameters
to nie dostaje w odpowiedzi parametru o ID 15808 - więc siłą rzeczy nie mogę go uzupełnić, dodatkowo w stock -> available oraz unit jest uzupełniony

**Comment by Lukasz-Zurek** [comment]
W komunikacie błędu wskazaliśmy parametr ofertowy, który jest obowiązkowy dla oferty. Sprawdzisz to za pomocą **GET /sale/categories/257689/parameters** (wspomniany parametr ma `"required": true`).

**Comment by fzdunek** [comment]
> W komunikacie błędu wskazaliśmy parametr ofertowy, który jest obowiązkowy dla oferty. Sprawdzisz to za pomocą **GET /sale/categories/257689/parameters** (wspomniany parametr ma `"required": true`).

faktycznie, ten endpoint zwraca ten parametr, w takim razie jaka jest różnica pomiędzy :
{{baseUrl}}/sale/categories/:categoryId/product-parameters
a
{{baseUrl}}/sale/categories/:categoryId/parameters 
nie mogę nigdzie znaleźć opisanej różnicy oraz use case.

**Comment by Lukasz-Zurek** [comment]
Zasób [GET /sale/categories/{categoryId}/product-parameters](https://developer.allegro.pl/documentation/#operation/getFlatProductParametersUsingGET) - jak opisujemy w dokumentacji - utworzony został z uwagi na parametry produktowe, potrzebne do utworzenia produktu, natomiast [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) obejmuje wszystkie parametry, zarówno produktowe, jak i ofertowe.

**Comment by fzdunek** [comment]
@Lukasz-Zurek co definiuje które parametry z endpoint [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) powinny znajdować się w tablicy parameters a które w productSet?

**Comment by Lukasz-Zurek** [comment]
@fzdunek Definiuje to wartość **options.describesProduct**:

- true - parametr produktowy
- false - parametr ofertowy.

Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).
