### ISSUE TITLE
Brak możliwości rejestracji aplikacji w Sandbox

### ISSUE THREAD

**Issue by tomaszwaszak** [allegro/allegro-api#10573]
Nie mogę zarejestrować aplikacji w Sandbox. Widzę komunikat 'Aktywuj konto oraz włącz dwustopniowe logowanie'. Przechodzę do opcji włączenia dwustopniowego logowania, gdzie aplikacja informuje mnie iż wysłała na mój poprawny numer telefonu SMS z kodem do aktywacji. Jednak ten SMS nie przychodzi.

**Comment by AureliuszBrussy** [comment]
Na Sandboxie nie wysyłamy SMSów, natomiast włączenie dwustopniowego logowania nie jest na tym środowisku konieczne do zarejestrowania aplikacji. Chodzi tutaj o tą pierwszą część zdania, czyli o aktywację konta. Podaj proszę login tego konta. Sprawdzę jaki jest status aktywacji.

**Comment by tomaszwaszak** [comment]
Loguję się moim kontem gmail, tomasz.waszak@gmail.com

Login wygląda na BTWtomaszwaszak

**Comment by tomaszwaszak** [comment]
Problem rozwiązany, dziękuję.
