### ISSUE TITLE
Walidacja kodu pocztowego w Allegro

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#1057]
Mam pytanie o walidacje kodów pocztowych. Czy jakakolwiek istnieje. Z moich testów wynika że można wpisać dowolny "poprawny" kod. Pod słowem "poprawny" mam namyśli składający się z cyfr. Mi bardziej chodzi o sprawdzenie czy taki kod pocztowy ma przypisaną miejscowość, czy istnieje. Jest do dość istotna sprawa w przypadku kupujących jako gość oraz połączeń z innymi systemami do wysyłek. Konta raczej mają poprawne kody, ale i tak nie ma pewności, gość może wpisać cokolwiek.  Nie wiem jak to funkcjonuje na środowisku produkcyjnym ale na sandbox'ie wpisuje cokolwiek i przechodzi.

Jeżeli nie ma walidacji to może nie jest złym pomysłem na implementacje czegoś takiego.
Mam nadzieję, że się nie powtórzyłem z pytaniem. Nigdzie nie znalazłem odpowiedzi.

**Comment by MartaNowaczyk** [comment]
Walidacja jest tylko na poziomie kraju i dotyczy to tylko formy jaką wpisujesz. Dla kraju Polska jest to 00-000. Na poziomie powiązania kodu z miejscowością już takiej walidacji nie ma. 
Dodatkowo jeśli wybierzesz inny kraj niż Polska w polu Kod pocztowy możesz wpisać cyfry i litery w dowolnej konfiguracji do 12 znaków.
