### ISSUE TITLE
Środowisko testowe nie zwróciło żadnych informacji o zamówieniu z interfejsu zamówienia użytkownika

### ISSUE THREAD

**Issue by LetroLiu** [allegro/allegro-api#10575]
trace-id : 9983c5b245afc2ad
Proszę pomóc sprawdzić ten wniosek, aby uzyskać zamówienia użytkownika. Istnieją trzy zamówienia w systemie, ale interfejs zwraca pustą listę
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms

**Comment by Lukasz-Zurek** [comment]
@LetroLiu Użytkownik, na którym jesteś autoryzowany nie ma na swoim koncie jakichkolwiek zamówień, dlatego prawidłowo zwróciliśmy pustą listę.

**Comment by LetroLiu** [comment]
> @LetroLiu Użytkownik, na którym jesteś autoryzowany nie ma na swoim koncie jakichkolwiek zamówień, dlatego prawidłowo zwróciliśmy pustą listę.

Cześć, używam [ce660556b72a43f0915a2e164bcefb21] Ten klient działa z ponowną autoryzacją, w dzień Bożego Narodzenia są prawie dane zamówienia, ale dzień poprzedni i wczoraj i dzisiaj są normalne, to dziwne, prawda?

**Comment by Lukasz-Zurek** [comment]
@LetroLiu Dla wskazanego wcześniej trace-id - ja już wspomniałem - odpytujesz zamówienia dla użytkownika, których takowych na koncie nie posiada. Nie odnotowałem tutaj błędu.

Jeśli posiadasz inny przykład, w którym zwróciliśmy zamówienia, podaj proszę kolejne trace-id - sprawdzę to.

**Comment by LetroLiu** [comment]
@Lukasz-Zurek Dobrze, ponieważ minęły dwa dni i nie przechowywałem dziennika w tym czasie, a jeśli to się stanie ponownie, skonsultuję się z wami ponownie, dzięki!
