### ISSUE TITLE
Account activation

### ISSUE THREAD

**Issue by m3dad** [allegro/allegro-api#10571]
Hello! 

I`m trying use sandbox API, but when trying to register sandbox API keys I get error "Activate your account and enable two-factor authentication.". Can you activate my account, please?

Login: m3dad

Thanks!

PS. And I cant enable 2FA - there is no SMS with code activation.

**Comment by PrzemyslawLukanowski** [comment]
Hi, I've just activated your account so you can register a new app (enabling 2FA is not required on Sandbox).

**Comment by m3dad** [comment]
Thank yoг so much, now all works correctly! Merry Christmas =)

**Comment by PrzemyslawLukanowski** [comment]
No worries, I'm glad I could help :) Thank you, Merry Christmas! :)
