### ISSUE TITLE
Środowisko testowe nie zwróciło żadnych informacji o zamówieniu z interfejsu zamówienia użytkownika

### ISSUE THREAD

**Issue by LetroLiu** [allegro/allegro-api#10586]
trace-id : b4e9179cb7590cab
Client ID:ce660556b72a43f0915a2e164bcefb21
Proszę pomóc sprawdzić ten wniosek, aby uzyskać zamówienia użytkownika. Istnieją trzy zamówienia w systemie, ale interfejs zwraca pustą listę
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms

**Comment by MartaNowaczyk** [comment]
Pobierasz zamówienia z konta kupującego - jesteś zautoryzowany na koncie na którym robiono tylko zakupy. Zamówienia można pobrać tylko z konta sprzedającego - zautoryzuj się jako sprzedawca by pobrać zamówienia od klientów.

**Comment by LetroLiu** [comment]
Jestem autoryzowany używając identyfikatora klienta sprzedawcy i ekranu klienta, ale podczas ponownej autoryzacji zalogowałem się na konto kupującego. Zgodnie z opisem, po wylogowaniu się z konta kupującego, ponowne autoryzacja rzeczywiście rozwiązała problem. Dziękuję, ale nadal może to powodować nieporozumienie.
