### ISSUE TITLE
Parametry z kategorii, które są dostępne w filtrach

### ISSUE THREAD

**Issue by morawcik** [allegro/allegro-api#10580]
Czy jest jakaś możliwość poznania, które parametry z kategorii są dostępne w filtrach na stronie? Część parametrów nie jest wyświetlana w filtrach jak np. Długość pochwytu (id 250309) w kategorii Klamki do drzwi (id 255634) https://allegro.pl/kategoria/drzwi-klamki-255634  W parametrach nie widzę niczego co by bezpośrednio na to wskazywało a byłoby to przydatne dla niewymaganych parametrach - pozwoliłoby to skupić się też na tych parametrach, które mogą mieć większy wpływ na wyszukiwanie.

**Comment by Lukasz-Zurek** [comment]
Jeżeli chodzi o nasze publiczne API, bo tym zajmujemy się na tym forum - w przypadku korzystania z GET /offers/listing, wszystkie dostępne filtry w danych kategoriach zwracamy w sekcji **"filters"**. Nie oznaczamy w żaden sposób parametrów. 

Niemniej jednak Twoje pytanie nie dotyczy stricte API, więc tu warto skontaktować się z [obsługą klienta](https://allegro.pl/pomoc/kontakt) - jak to wygląda bezpośrednio na Allegro.pl.

**Comment by morawcik** [comment]
No właśnie dotyczy API - może nie do końca jasno wyraziłem o co mi chodzi.
Na stronie w danej kategorii mamy filtry - część jest uniwersalna dla wszystkich kategorii (jak cena, sposoby dostawy itd) a część jest zależna od kategorii (jak np. kolor czy rodzaj). Poprzez API chciałbym się dowiedzieć jakie są dostępne filtry w danej kategorii (oczywiście poza tymi uniwersalnymi).

Jeśli chodzi o /offers/listing to rozumiem, że te filtry dotyczą filtrów wyszukiwania ofert poprzez /offers/listing, więc to jednak nie to.

**Comment by Lukasz-Zurek** [comment]
> No właśnie dotyczy API - może nie do końca jasno wyraziłem o co mi chodzi. Na stronie w danej kategorii mamy filtry - część jest uniwersalna dla wszystkich kategorii (jak cena, sposoby dostawy itd) a część jest zależna od kategorii (jak np. kolor czy rodzaj). Poprzez API chciałbym się dowiedzieć jakie są dostępne filtry w danej kategorii (oczywiście poza tymi uniwersalnymi).

Ok, teraz rozumiem. Nie udostępniamy takich informacji w naszym API.
> 
> Jeśli chodzi o /offers/listing to rozumiem, że te filtry dotyczą filtrów wyszukiwania ofert poprzez /offers/listing, więc to jednak nie to.

Ok.

**Comment by morawcik** [comment]
Rozumiem, dziękuję za informację.
