### ISSUE TITLE
INSURANCE_AMOUNT_BELOW_COD - pobranie CZK

### ISSUE THREAD

**Issue by Pibrusz** [allegro/allegro-api#10588]
Podczas uderzenia po paczkę na czeski adres dostaję błąd: 
`Error response: ["Could not create shipment, one or more shipments failed: Allegro API returned error: (INSURANCE_AMOUNT_BELOW_COD) : The insurance amount is lower than the POD value"]`

Reqeust jaki leci: 

```
{
  "input": {
    "deliveryMethodId": "1b28f4fb-df3e-4324-a6ef-707a3f1be43b",
    "sender": {... },
    "receiver": {
      "name": "....",
      "street": ".....",
      "streetNumber": "......",
      "postalCode": "77900",
      "city": "Olomouc",
      "countryCode": "CZ",
      "email": ".....@allegromail.pl",
      "phone": "+.......",
      "company": ""
    },
    "labelFormat": "ZPL",
    "referenceNumber": ".........",
    "packages": [
      {
        "type": "PACKAGE",
        "length": {
          "value": 30,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 26,
          "unit": "CENTIMETER"
        },
        "height": {
          "value": 20,
          "unit": "CENTIMETER"
        },
        "weight": {
          "value": 0.43,
          "unit": "KILOGRAMS"
        }
      }
    ],
    "insurance": {
      "amount": "113.43",
      "currency": "PLN"
    },
    "cashOnDelivery": {
      "amount": "668.00",
      "currency": "CZK"
    },
    "additionalServices": []
  }
}
```
Ubezpieczenie wysyłam w PLN zgodnie z sugestiami z API, dodatkowo stosuję przeliczenia kwot. 
Co tu robię nie tak ?

**Comment by Lukasz-Zurek** [comment]
@Pibrusz Zgodnie z komunikatem w polu **"insurance"** otrzymujemy niższą kwotę aniżeli tę w czeskich koronach w sekcji **"cashOnDelivery"**. Przelicznik dla tej metody dostawy nie jest nam znany z uwagi na to, że jest on bezpośrednio po stronie DHL. Będziesz go musiał jednak skorygować po swojej stronie.

**Comment by Pibrusz** [comment]
dzięki za podpowiedź 
![image](https://github.com/user-attachments/assets/26046186-f224-42ff-83f3-b27e9fedeceb)
spróbuję zmienić przelicznik
