### ISSUE TITLE
doChangePriceItem- brakujące parametry obowiązkowe: Kolor dominujący, Cechy

### ISSUE THREAD

**Issue by rafwlaz** [allegro/allegro-api#1059]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
XML:
REQUEST:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
  <SOAP-ENV:Body>
    <ns1:DoChangePriceItemRequest>
      <ns1:sessionHandle>abcdefgh//00_1</ns1:sessionHandle>
      <ns1:itemId>7546637572</ns1:itemId>
      <ns1:newBuyNowPrice>71</ns1:newBuyNowPrice>
    </ns1:DoChangePriceItemRequest>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

RESPONSE:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>ERR_CONSTRAINT_VIOLATION_EXCEPTION_HAS_ALL_REQUIRED_ATTRIBUTES</faultcode>
      <faultstring>Uzupełnij brakujące parametry obowiązkowe: Kolor dominujący, Cechy.</faultstring>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Czas wystąpienia: 1547308841.7945

Podczas wywołania metody otrzymuję błąd: `Uzupełnij brakujące parametry obowiązkowe: Kolor dominujący, Cechy.`, których absolutnie nie ma wymogu przesyłać przy tej metodzie.

**Comment by FromAnyHole** [comment]
SundayHelp...
Niestety masz złe informacje, w tej kategorii wymagane są:
* Rodzaj
* Stan
* Materiał
* Kamień
* Motyw
* Kolor dominujący
* Cechy

**Comment by rafwlaz** [comment]
@FromAnyHole masz 100% racji, tylko pytanie brzmi gdzie w metodzie `doChangePriceItem` a raczej jej dokumentacji jest napisane, że mam wysłać takie parametry?

Wysyłamy:  
* `sessionHandle`  
* `itemId`  

I odpowiednią kwotę u mnie jest to `newBuyNowPrice`.

Mało tego w liście błędów nie ma `ERR_CONSTRAINT_VIOLATION_EXCEPTION_HAS_ALL_REQUIRED_ATTRIBUTES `

**Comment by dlis2010** [comment]
@rafwlaz nie możesz zmienić ceny w aukcji która nie ma wszystkich obowiązkowych parametrów.
Musisz najpierw je uzupełnić. Możesz zerknąć tutaj, aby zobaczyć jak dużo tego masz: https://allegro.pl/moje-allegro/sprzedaz/uzupelnij-parametry

**Comment by rafwlaz** [comment]
@dlis2010 w takim razie wszystko jasne, aukcja była wystawiana z wymaganymi na tamten moment parametrami. Doszły nowe wymagane parametry i stąd błąd. 

Brakuje tylko takiej informacji w API gdyż sam błąd na to jasno nie wskazuje...
