### ISSUE TITLE
Modyfikowanie oferty, błąd: Offer id cannot be changed

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#1060]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuję zmodyfikować ofertę poprzez REST API. Podczas wywołania metody PUT sale/offers/7768994462
dostaję błąd 422 Unprocessable Entity, a w response body dziwną informację:
Offer id cannot be changed.
`{"errors":[{"code":"VALIDATION_ERROR","message":"Offer id cannot be changed.","details":"","path":"","userMessage":"Offer id cannot be changed."}]}`
O co chodzi? Wcześniej opis oferty pobrałem metodą GET sale/offers/7768994462
Trace-Id: 3d741764ee2d6d61

**Comment by MartaNowaczyk** [comment]
@Radziasss sprawdź czy w body podajesz ten sam ID oferty co w URL - 7768994462.

**Comment by Radziasss** [comment]
@MartaNowaczyk oczywiście podaję ten sam numer ID

**Comment by MartaNowaczyk** [comment]
@Radziasss w takim razie podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1060. Sprawdzę w czym jest problem.

**Comment by MartaNowaczyk** [comment]
@Radziasss powinieneś dostać niedługo maila od naszej obsługi z prawidłową strukturą oferty, która działa bez problemu. Sprawdź proszę u siebie i daj znać.

**Comment by Radziasss** [comment]
@MartaNowaczyk Przekazuję JSONa, którego otrzymałem od Was i dostaję cały czas ten sam komunikat.

Mam jeszcze taką wątpliwość: czy przekazując nową treść aukcji w formie JSONa powinna ona iść jako jeden parametr w body requesta? Jeśli tak, to jaką powinien mieć nazwę ten parametr?
Bo jeśli powinno to być wiele parametrów (dla każdej właściwości oferty osobny, czyli np. pierwszy parametr to id, drugi to name, trzeci category, itd) to w takim przypadku dostaję komunikat już w ogóle nic nie znaczący:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/7768994462","userMessage":null}]}`

więc zakładam, że pierwsza opcja jest właściwsza? Tylko jaka powinna być nazwa parametru?

**Comment by lukasnet** [comment]
@Radziasss  Miałem ten sam problem, strukturę zmienionej oferty przesyłasz bezpośrednio bez przypisywania jej do parametru. Zwróć też uwagę na to że przy tej metodzie PUT nie przesyłasz commandID.

**Comment by MartaNowaczyk** [comment]
@Radziasss wszystko jasne, czy potrzebujesz więcej informacji?

**Comment by Radziasss** [comment]
@lukasnet ooo, dzięki Ci dobry człowieku. Tak czułem, że chodzi o coś ze sposobem przesyłania informacji. Musiałem skorzystać z innej biblioteki, bo ta moja nie umożliwiała w ogóle takiego czegoś. W końcu API zaczęło ze mną gadać. Co prawda nie chce jeszcze przyjąć tego, co wysyłam, ale JSON, który dostałem od supportu przechodzi, więc problem jest już w samej treści oferty.

@MartaNowaczyk dziękuję za pomoc, na razie tyle mi wystarczy, ale może warto rozważyć, żeby metoda akceptowała też treść oferty pod postacią jakiegoś parametru w body requesta? Np.: 
`"offer" : "{TUTAJ_TREŚĆ_DŻEJSONA}"`
