### ISSUE TITLE
allegro rest api i problem z CORS

### ISSUE THREAD

**Issue by xmossdev** [allegro/allegro-api#1061]
Cześć,

próbuje zalogować się do allegro przy użyciu JavaScript ale niestety cały czas dostaje odpowiedź 
OPTIONS https://allegro.pl/auth/oauth/device 401 (Unauthorized)
Access to XMLHttpRequest at 'https://allegro.pl/auth/oauth/device' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Czy istnieje jakiś sposób na obejście tego?

Mój kod:
`
<html ng-app="APP">
<head>
	<meta charset="utf-8">
	<title></title>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.5/angular.min.js" type="text/javascript"></script>
</head>
<body>
	<div ng-controller="loginAllegro">
		<button ng-click="logAll()">login</button>
	</div>
	<script>
			
		var clientID = 'niepodam'; //normalnie to tu jest
		var clientSecret = 'niepodam'; //normalnie to tu jest
		var authToken = btoa(clientID +':'+clientSecret);

		angular.module('APP',[]).
		controller('loginAllegro',['$scope','$http',function ($scope,$http) {
			$scope.logAll = function(){
			
					var data = 'client_id=' + clientID
				var config = {
	                headers : {
	                    'Authorization': 'Basic ' + authToken,
	                    'Content-Type' : 'application/x-www-form-urlencoded'
	                }
            	}

				$http.post('https://allegro.pl/auth/oauth/device',data,config)
			}
		}])

	</script>
	
</body>
</html>`

**Comment by MartaNowaczyk** [comment]
Nie prowadzimy tutaj wsparcia w tym zakresie. Prowadzimy wsparcie dla języków w jakich dochodzi do ostatecznej komunikacji z naszymi serwerami.
Spójrz na rozwiązanie w https://github.com/allegro/allegro-api/issues/935 może będzie dla Ciebie pomocne.

**Comment by xmossdev** [comment]
Pani odpowiedź nie wnosi nic do tematu. Nie oczekuję wsparcia dla języka tylko informacji w jaki sposób macie skonfigurowane CORS i czy istnieje możliwość komunikacja z waszymi serwerami przy użyciu JS. Nie wiem czy to ja coś źle robi czy to wasza konfiguracja mnie nie puszcza.

**Comment by MartaNowaczyk** [comment]
@xmossdev przepraszam, mój błąd. Oczywiście nie pozwalamy na to. Nie ma obejścia. Musisz to zrobić z poziomu backendu.

**Comment by rtnet-pl** [comment]
Twój request w ogóle nie wychodzi z przeglądarki. Obejście jest takie, że tworzysz po swojej stronie skrypt na serwerze (np. w php) który pobiera token, a z poziomu js wywołujesz sobie ten skrypt.

**Comment by xmossdev** [comment]
@rtnet-pl Tak zrobiłem ale liczyłem na to że jest jakaś możliwość ominięcia tego.

**Comment by rtnet-pl** [comment]
Można jeszcze wyłączyć SOP w ustawieniach przeglądarki, ale to pewnie odpada
