### ISSUE TITLE
Czy jest nowa metoda zastępująca doGetItemsInfo ?

### ISSUE THREAD

**Issue by GregNx1** [allegro/allegro-api#1062]
Witam,
Czy jest już (albo będzie) nowa metoda zamiast doGetItemsInfo?
Pozdrawiam
Grzegorz

**Comment by Radziasss** [comment]
Możesz użyć GET /sale/offers/{offerId}
https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET

**Comment by MartaNowaczyk** [comment]
zgadzam się z @Radziasss 
Więcej o zasobach związanych z ofertami znajdziesz w naszym [poradniku](https://developer.allegro.pl/my_offers/).

**Comment by roman-kuzyk** [comment]
Witam,
@MartaNowaczyk 
Czy jest planowane dodanie możliwości uzyskania informacji o dowolnym produkcie?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
@roman-kuzyk tak, mamy to w planach. Informację o udostępnieniu takiej możliwości oraz jakie to będą informacje podamy w oddzielnym komunikacie. Data na ten moment nie jest znana.

**Comment by GregNx1** [comment]
Dziękuję za informację. Metoda GET /sale/offers/{offerId} pozwala pobrać tylko pojedyncze aukcje, a ja potrzebuje coś do pobierania paczkami. doGetItemsInfo pozwalało pobierać chyba po 25, a teraz zmniejszyliście do 10. Czy są plany podobnej metody z większym limitem w api rest?

**Comment by MartaNowaczyk** [comment]
@GregNx1 możesz skorzystać z metody [GET /sale/offers](https://developer.allegro.pl/documentation/#/offer-management/searchOffersUsingGET) lub z zasobów do pobrania [listy ofert](https://developer.allegro.pl/news/2018-07-03-listing_ofert/) GET /offers/listing

**Comment by aktywnitu** [comment]
Pani Marto dotychczasowe aplikacje korzystają z funkcji  doGetItemsInfo oraz doGetSiteJournal do pobierania globalnych danych na temat sprzedaży - analiza konkurencji, trendów itd.
Niestety na tą chwilę brak odpowiedników tych metod w REST API Allegro.

**Comment by MartaNowaczyk** [comment]
@aktywnitu to prawda, na ten moment nie ma takiego odpowiednika w REST API. Jeśli udostępnimy dodatkowe dane dotyczące sprzedaży, oferty bez kontekstu użytkonika, na pewno poinformujemy o tym w oddzielnym komunikacie.
