### ISSUE TITLE
Edycja pola "External id"

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1063]
Witam,

czy jest możliwość ręcznej edycji pola "External ID" w panelu Allegro podczas wystawiania / modyfikacji oferty ? Chodzi o to, że metoda  /order/checkout-forms/{checkoutForm_id} zwraca dane w postaci
```
"offer": {
                "id": "6205584023",                         
                "name": "Koło ratunkowe",                   
                "external": {
                "id": "ext_2018_08_17"                     
              } 
            },
```
Dodatkowe pytanie: Czy pole EAN wypełniane podczas wystawiania/modyfikacji oferty to jest odpowiednik "External ID" w API. Czy EAN jest gdzieś zwracany w danych o zamówieniu klienta ?

Pozdrawiam

**Comment by PawelTaberski** [comment]
Pole external id jest to zewnętrzny ID który nadaje sprzedający nie jest to to samo co EAN i jest on dostępny tylko przez REST API. EAN nie jest zwracany przy zamówieniach ale external id jest. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#04).
