### ISSUE TITLE
Długość pola numer części

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1064]
Dzień dobry,
Proszę uzgodnić długości pól (części samochodowe): "Numer katalogowy części" oraz "Numery katalogowe zamienników".
Powinny mieć identyczne maxLength, oczywiście wolę 30 znaków.

        {
            "id": "215858",
            "name": "Numer katalogowy części",
            "type": "string",
            "required": false,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false
            },
            "restrictions": {
                "minLength": 1,
                "maxLength": 20,
                "allowedNumberOfValues": 1
            }
        },
        {
            "id": "215941",
            "name": "Numery katalogowe zamienników",
            "type": "string",
            "required": false,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false
            },
            "restrictions": {
                "minLength": 1,
                "maxLength": 30,
                "allowedNumberOfValues": 10
            }
        }

**Comment by FromAnyHole** [comment]
No i od razu ustalcie i wyraźnie podajcie - czy jeśli zasób odpytany jest z nagłówkiem:
[Accept-Language: pl-PL]
... to maksymalna długość tego czy innego pola są to BAJTY czy ZNAKI UTF-8 ?!?

**Comment by PawelTaberski** [comment]
@kfijalko Moim zdaniem bardzo trafna sugestia, przekazałem ją do odpowiedniego zespołu, proszę o cierpliwość.
@FromAnyHole Jest to ilość znaków.

**Comment by PawelTaberski** [comment]
@kfijalko Otrzymałem odpowiedź, że rozbieżność jest celowa - pojedynczy numer katalogowy powinien mieć maksymalnie 15-20 znaków. W przypadku zamienników numery katalogowe są jednak zazwyczaj podawane razem z nazwą producenta. Dlatego zamienniki mają dopuszczalny dłuższy numer. 
Czy Tobie w wypadku któregoś z tych parametrów brakuje znaków?

**Comment by kfijalko** [comment]
Ok, nie brałem pod uwagę podawania producenta.
Czy brakuje to jeszcze nie wiem. Dopiero wziąłem się za Rest'a.

**Comment by PawelTaberski** [comment]
Rozumiem w takim razie zamykam sprawę.
