### ISSUE TITLE
[REST] / [Client_credentials] - aktualna lista wszystkich zasobów ?

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1065]
:bulb: **Sugestia**
Czy nie wypadało by może, wyraźnie określić każdy zasób z osobna (w dokumentacji), który jest osiągalny bez "kontekstu użytkownika" ? A może niektóre z zasobów mogły by się takimi w ogóle stać - oczywiście wtedy z pewnymi ograniczeniami, w sensie odsyłania danych zastrzeżonych tylko dla "kontekstu" ?

**Comment by PawelTaberski** [comment]
Słuszna uwaga i mamy to już w planach, jak również lepszy podział metod w dokumentacji.
