### ISSUE TITLE
Pytanie o liczbę kategorii

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1066]
Czy możecie Państwo [allegro] podać liczby:
- wszystkich kategorii 
- kategorii najniższego poziomu (leaf=true)
Chciałbym sprawdzić czy wszystko pobrałem.

**Comment by PawelTaberski** [comment]
Nie są to stałe wartości liczba kategorii zmienia się z dnia na dzień. Aby pobrać całe drzewo przez REST API musisz tak długo odpytywać, aż w każdym wypadku dotrzesz do liścia. Obecnie możesz również pobrać przez WebAPI całe drzewo przy pomocy metody [doGetCatsData](https://allegro.pl/webapi/documentation.php/show/id,46), bądź skorzystaj z [doGetCatsDataCount](https://allegro.pl/webapi/documentation.php/show/id,47#method-input) by sprawdzić licznik dostępnych kategorii.

**Comment by kfijalko** [comment]
ok, dziękuję
