### ISSUE TITLE
Alternatywa w REST API do GetMyData WSDL

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#1067]
Cześć :)
Czy nowe REST API udostępnia już metodę analogiczną do GetMyData? Tworzymy zupełnie nową integrację i chcieliśmy się całkowicie oprzeć o nowego RESTa, ale widzę, że na dzień dzisiejszy nie jest to chyba jeszcze możliwe.

**Comment by PawelTaberski** [comment]
Obecnie nie ma w REST API takiej metody, niektóre pola tak jak w opisie tej metody już są dostępne przez REST API. Jakich informacji, które otrzymujesz w odpowiedzi na tą metodę brakuje tobie najbardziej, aby móc w pełni przejść na REST API i do czego są one Tobie niezbędne?

**Comment by artzie92** [comment]
Aplikacja obsługuje wiele kont allegro. Po pierwszym zalogowaniu do allegro przez użytkownika i pobraniu tokena potrzebujemy pobrać dane o koncie takie jak np. Login użytkownika. Chodzi nam głównie o to aby dany token można było powiązać z kontem. Metoda GetMyData wydaje się być tutaj idealna, ale chcieliśmy uniknąć integracji ze starym WSDL. Pozdrawiam

**Comment by PawelTaberski** [comment]
Co do powiązania tokentów to są  one zgodne ze standardem JWT i możesz je rozkodować w odpowiedzi otrzymasz m.in. identyfikator użytkownika, dzięki czemu łatwo powiążesz token z danym userem.

**Comment by PawelTaberski** [comment]
@artzie92 Rozumiem, a czy również pozostałe dane z tej metody są dla Ciebie potrzebne czy chodzi Tobie głównie o zasób do mapowania id na login?

**Comment by artzie92** [comment]
To są elementy, które na pewno byłby przydatne :)
userLogin 
Imię użytkownika.
Nazwisko użytkownika.
Nazwa firmy.
e-mail użytkownika.

**Comment by PawelTaberski** [comment]
Rozumiem, dziękuję za informacje planujemy wdrożenie dedykowanego zasobu, ale kiedy się pojawi na chwilę obecną nie jestem w stanie powiedzieć. Jeśli będziemy mieli dokładniejsze informacje przekażemy je w dedykowanym komunikacie.
