### ISSUE TITLE
REST API ściąganie zamówień + doAddPackageInfoToPostBuyForm

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1068]
Czy wywołanie REST API `/order/checkout-forms/{checkoutForm_id}` zwraca dane a konkretnie "transactionId", który pozwoli na wykonanie metody WEBAPI doAddPackageInfoToPostBuyForm

**Comment by PawelTaberski** [comment]
Niestety nie, ale możesz skorzystać z zasobu do mapowanie dealId i lineItemId /order/line-item-id-mappings. Więcej na ten temat [tutaj](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/). Wiemy, że nie jest to idealne rozwiązanie, jednakże jest to jedyne co mogę polecić na dany moment.
