### ISSUE TITLE
https://allegro.pl/myaccount/newpayments_my_payouts.php

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1069]
Dzień dobry,
potrzebujemy przez API pobrać zestawienie wpłat od klientów powiązanych z konkretną wypłatą. Dokładnie to co otrzymujemy tutaj w pdf-ie: https://allegro.pl/myaccount/newpayments_my_payouts.php
jak tego dokonać, proszę o wskazanie metody.
![1111](https://user-images.githubusercontent.com/40828332/51185132-9bf36b80-18d6-11e9-87a3-1a787a02729c.png)

**Comment by PawelTaberski** [comment]
Obecnie w REST API nie ma takiej metody, ale możesz skorzystać z zasobów w WebAPI do zarządzania [AllegroFinansami](https://allegro.pl/webapi/documentation.php/theme/id,65).
