### ISSUE TITLE
GET /sale/offers przy dostępie client_crendentials

### ISSUE THREAD

**Issue by quayle** [allegro/allegro-api#1070]
W związku ze stopniowym wygaszaniem WebAPI, jestem zmuszony zmigrować istniejący kod integracji na nowe REST API.

Chcę pobrać listę ofert/aukcji utworzonych przez klienta, korzystającego z
podanych danych dostępowych.

Teoretycznie powinno wystarczyć do tego grant_type=auth_code.
Pojawia się jednak związany z tym problem:

https://developer.allegro.pl/auth/#user

> redirect_uri - Adres powrotu, na który wysłany zostanie kod (musi być zgodny
>                 z tym podanym przy rejestracji aplikacji)

Aplikacja może być pod różnymi adresami URL, ponieważ każdy *z naszych* klientów
ma ją zainstalowaną pod innym (swoim) adresem.

W związku z tym, każdy *z naszych klientów*, będzie zmuszony wygenerować dla
siebie oddzielne dane dostępowe, czyli zarejestrować oddzielną aplikację, by
pozyskać własne klucze, do których będzie przypisany odpowiedni adres powrotu.

Skoro tak, to nie widzę powodu, by każdy z takich klientów, musiał oddzielnie
autoryzować aplikację i powinno mu do integracji wystarczyć:
grant_type=client_credentials.

To jednak się nie nadaje, ponieważ nie będę w stanie dla:

`GET /sale/offers`

określić "seller.id", a nawet jak podam go "na sztywno" na podstawie:
https://allegro.pl.allegrosandbox.pl/login/user
to i tak mam 401, ponieważ nie znajduję się w "kontekście użytkownika".

IMHO, jeżeli aplikacja jest zarejestrowana na określonego użytkownika, to
korzystając grant_type=client_credentials, powinno się mieć dostęp do
ofert/zakupów/sprzedaży powiązanych z tym właśnie, konkretnym użytkownikiem bez podawania oddzielnie seller.id.

Czy bierzecie pod uwagę możliwość, wprowadzenie takiego dostępu?

**Comment by quayle** [comment]
Ech... Device Flow? Wyszedł, więc klasyczny "Teddy Bear Problem Solving". Dzięki.

**Comment by PawelTaberski** [comment]
Na przyszłość polecam naszą stronę są tam opisane wszystkie formy dostępu, tutaj np. wspomniane [device flow](https://developer.allegro.pl/auth/#DeviceFlow) :-)

**Comment by quayle** [comment]
Czytałem, czytałem, ale jak to bywa przy początkowych pracach w każdym nowym API, nie wszystko się od razu do końca wyłapuje.

**Comment by PawelTaberski** [comment]
Jasne, ważne że udało się znaleźć dobre rozwiązanie 👍
