### ISSUE TITLE
Zakładka: https://allegro.pl/billinghistory/#/history

### ISSUE THREAD

**Issue by Masakrancja** [allegro/allegro-api#1071]
Witam,
Proszę o informacje czy jest planowane wdrożenie funkcjonalności zakładki: https://allegro.pl/billinghistory/#/history poprzez rest api?

**Comment by PawelTaberski** [comment]
Nie jestem w stanie podać obecnie jakiegoś terminu. Jak tylko będziemy mieli jakieś informacje kiedy planujemy wdrożyć takie zasoby, to poinformujemy o tym w dedykowanym komunikacie.
