### ISSUE TITLE
RestApi opis html 

### ISSUE THREAD

**Issue by lukasnet** [allegro/allegro-api#1073]
Nie widzę takiej opcji w restapi aby pobrać opis oferty w formacie html, czyli pola z metody webapi doShowItemInfoExt->{'itemListInfoExt'}->{'itDescription'}. Czy możecie dodać je np. do GET /sale/offers/{offerId}?

**Comment by PawelTaberski** [comment]
Nie ma już takiej możliwości, w WebAPI jest to zaszłość, bo kiedyś opisy można było wprowadzać w formacie HTML z niemal dowolnymi formatkami. W API Allegro nie ma już takiej możliwości. W REST API nie planujemy wprowadzać takich pól aby pobrać opis jako HTML.

**Comment by lukasnet** [comment]
No to wielka szkoda, bo pobieram obecne opisy w html aby mieć ich podgląd/zapis do własnej bazy aukcji. W takim razie mam nadzieję że metoda doShowItemInfoExt pozostanie jeszcze na długo.

**Comment by PawelTaberski** [comment]
Obecnie nie znamy dokładnej daty wygaszenia tego zasobu, jak tylko będziemy znać taką informację umieścimy dedykowany komunikat.
