### ISSUE TITLE
Ilość sprzedanych sztuk w ofercie

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#1074]
:bulb: **Sugestia**
Witam,
Czy będzie dodana ilość sprzedanych sztuk w ofercie dostępne przez nowe API dla ofert nienależących do zalogowanego użytkownika? Takie dane mamy dostępne w starym API i liczę że to również zostanie przeniesione do nowego.

**Comment by PawelTaberski** [comment]
W zasobie /offers/listing  jest dostępne pole popularity, jest to w przypadku oferty typu BUY_NOW  liczba zakupów od unikalnych użytkowników z ostatnich 30 dni. W przypadku oferty typu AUCTION  jest to liczba użytkowników, którzy biorą udział w licytacji.

**Comment by expondo** [comment]
Tak wiem że jest dostępna ilość złożonych zakupów, jednak stare API daje możliwość sprawdzenia ilości sprzedanych sztuk. Kiedy można liczyć na dodanie takiej informacji?

**Comment by PawelTaberski** [comment]
Obecnie nie planujemy przy publicznie dostępnych zasobach dodawać liczby całkowitej sprzedanych przedmiotów poza obecnie dostępną w polu popularity, o którym wspominałem wcześniej.

**Comment by lukasnet** [comment]
Mam podobną sugestię, ale dla metod GET /sale/offers... (ofert zalogowanego sprzedającego) aby zwracały ilość sprzedanych sztuk od początku wystawienia aukcji, a nie tylko z ostatnich 30 dni. 
Problem polega na tym że z pola popularity/sold nie wiadomo czy daną aukcję można w pełni edytować (np. tytuł) jeśli w ciągu ostatnich 30 dni nie było sprzedaży.

**Comment by expondo** [comment]
Ilość sprzedanych sztuk z ostatnich 30 dni jest daną publiczną, ponieważ w końcu wyświetlacie ją na stronie oferty. Więc dlaczego nie możecie dodać tej informacji do API?

**Comment by PawelTaberski** [comment]
@lukasnet No ale w takim wypadku możesz np. sprawdzać czy nie zmieniło się pole stock, jeśli zmalało nie przez twojego requesta to musi oznaczać, że była sprzedaż. Albo połączyć to z zasobami do zarządzania zamówieniami.

**Comment by lukasnet** [comment]
@PawelTaberski Tyle kombinacji/monitorowania stocku/zapytań api i marnowania zasobów aby uzyskać tą informację?! Czemu nie możecie zrobić tego w prosty sposób i zwracać tej informacji tak jak jest w webapi???

Jaki jest sens naszych sugestii/próśb skoro i tak macie je głęboko i robicie wszystko aby jak najmniej się narobić, a nam utrudniać z wami współpracę. 
Skoro jest zapewne grupa osób którym przydałaby się jakaś poprawka etc. to dlaczego jej nie może zrealizować?!
Poza zgłaszaniem waszych błędów to forum w takie razie jest bezużyteczne :[

**Comment by PawelTaberski** [comment]
@lukasnet Przekazałem Twoją sugestię do odpowiedniego zespołu, jak zdecydujemy się wdrożyć takie pole poinformujemy o tym w dedykowanym komunikacie. Zbieramy takie potrzeby i zgłaszamy ilu userów potrzebuje dane rozwiązanie im więcej osób zgłasza zapotrzebowanie na dane pole tym mamy większą szansę na szybsze wdrożenie takiej zmiany, bo możemy to mocniej zaargumentować, dlatego dopytuje tak mocno o powody.
Moja sugestia rozwiązania miała być tymczasowa, jak obecnie możesz to ograć bo nie wiem kiedy uda się wdrożyć takie pole, bynajmniej nie miała zniechęcić do zgłaszania sugestii i nie wpłynęła na to czy przyjąłem ją. Niestety nie tylko od nas zależy wdrażanie zmian i kiedy one następują.

**Comment by lukasnet** [comment]
Jeśli została przyjęta to OK. Tymczasem radzę sobie z tym poprzez webapi, ale w związku z jego wygaszeniem nie chcę zostać z dnia na dzień bez rozwiązania tego problemu, więc liczę że to zostanie zrealizowane.

**Comment by expondo** [comment]
@PawelTaberski jeszcze bym prosił o odpowiedź w mojej sprawie

**Comment by expondo** [comment]
Liczba zakupów to nie to samo co ilość sprzedanych sztuk.
Gdy klient 5 sztukl w jednym zamówieniu.
API poda mi popularity 1, brakuje info o ilości czyli 5 sztuk tak jak to wyświetlacie na stronie oferty.
Poniżej przykład z pierwszej lepszej oferty.
![przyklad](https://user-images.githubusercontent.com/40236075/51307215-703fc500-1a3f-11e9-98ec-046b2958ad20.png)

**Comment by PawelTaberski** [comment]
@expondo Teraz rozumiem o co Tobie chodziło, zgłosiłem zapotrzebowanie na tą informację jako sugestię. Prosiłbym, abyś mi jeszcze tylko napisał do czego posłużyła by Tobie taka informacja.

**Comment by expondo** [comment]
Moja firma stale rozszerza asortyment na rynek polski. W naszym programie mamy integrację z Allegro gdzie na podstawie listingu z API wiemy jakie produkty się sprzedają w Polsce i wówczas te produkty wdrażamy do sprzedaży. Sama ilość zakupów nie jest wystarcza, na podstawie sprzedanych sztuk można podjąć decyzję czy warto wystawiać produkt na Allegro.

**Comment by expondo** [comment]
Kiedy w takim razie można się spodziewać jakieś informacji czy będzie to wdrożone? Rozumiem że musicie to sobie dodać do kolejki zadań ale prosiłbym tylko o informację czy w ogóle będzie to dodane i mniej więcej w którym miesiącu.

**Comment by PawelTaberski** [comment]
I w jakim zasobie chciałbyś taką daną? 
Na listingach allegro na froncie nie ma takich informacji tylko już w samym widoku oferty, czyli taką informacje widziałbyś w zasobie /sale/offers/{offerId}. Jednakże wtedy nie byłaby to informacja publiczna. Rozumiem, że wtedy potrzebowałbyś zasób, który zwracałby publiczne dane z widoku oferty.

**Comment by martacronic** [comment]
Podpinam się pod prośbę @expondo. Dokładnie takich samych danych używam teraz z WebAPI i  nie mogę przejść na REST API, bo są braki.

**Comment by FromAnyHole** [comment]
Szykuje się Katastrofa...
Państwo Administratorzy - tutaj nie ma co dopytywać po kawałku na zasadzie: "... a co jeszcze byście chcieli ??", w nowym API-REST musi być po prostu odwzorowanie metody [DoShowItemInfoExt] - dla niektórych rozwiązań to jedna z kilku NAJWAŻNIEJSZYCH metod w całym WebAPI !! To Wasze gadanie, że niby można będzie z wielu zasobów REST uzyskać te same dane nie zmienia faktu, że chcecie całkowicie ograniczyć dostęp do danych karty przedmiotu - spoza zasięgu sesji (token'a) konkretnego użytkownika, czyli wystawiającego dany przedmiot - TO NIE PRZEJDZIE !!! Uwalicie w ten sposób ponad połowę drobnych czy dedykowanych rozwiązań API, ja już bilet do Poznania kupuję...

**Comment by expondo** [comment]
Dokładnie tak, skoro informacja na froncie jest publiczna to nie ma przeszkód aby nie była publiczna w API.
W mojej ocenie te informacje powinny znaleźć się w dwóch metodach:
1. /sale/offers/{offerId}
2. /offers/listing

W pierwszej metodzie jest jasne, ponieważ obecnie na stronie oferty to wyświetlacie.

Dlaczego powinno być również na listingu?
Ponieważ wówczas zarówno ja jak i pewnie wielu innych programistów będziemy wówczas pobierać listing a następnie odpytywać każdą ofertę osobno. Będzie to dla nas utrudnienie a dla was niepotrzebne obciążenie serwerów. Dodając ilość sprzedanych sztuk na listingu w API unikniecie niepotrzebnych setki/tysięcy requestów.

**Comment by expondo** [comment]
@FromAnyHole Przenoszenie 1:1 jest bezsensu, więc po co przenosić?
Dobrze że API jest przenoszone do REST, ponieważ jest wydajniejsze i rozwiązuje kilka starych problemów i liczę że nasze prośby o niektóre dane trafią tam gdzie trzeba.

**Comment by PawelTaberski** [comment]
@expondo Bardzo dziękuje za informacje i doprecyzowanie. Informacje przekazałem, kiedy wdrożymy taką zmianę nie jestem w stanie powiedzieć. Jak będziemy mieli już jakieś konkretne informacje damy znać w dedykowanym komunikacie.

**Comment by expondo** [comment]
Będę oczekiwał pozytywnych informacji z niecierpliwością

**Comment by FromAnyHole** [comment]
@expondo - żadne tam przenoszenie 1:1 !!
Zwyczajnie chodzi o to, że nadal muszą być TAKIE SAME DANE w dostępie "publicznym", czyli bez "kontekstu użytkownika". Zrobiono już przecież w REST nowy typ autoryzacji [grant_type=client_credentials], ale jak na razie tylko kilka mało znaczących zasobów jest z tego obsługiwane, a chyba nie jest dla Ciebie problemem kiedy będzie więcej możliwości - dla wszystkich zainteresowanych ??

**Comment by dxsoftware** [comment]
Dołączam się do tematu.
Możliwość pobrania ilości sprzedanych sztuk w ostatnich 30 dniach będzie bardzo przydatna przy analizach zakupowych. 
Liczę że zostanie to wdrożone w w miarę szybko, ponieważ wtedy będziemy mogli się już zupełnie przestawić na nowe API.

**Comment by PawelTaberski** [comment]
@dxsoftware Przekazałem Twoją sugestię, jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym w dedykowanym komunikacie.
