### ISSUE TITLE
Pytanie o GET /pricing/offer-quotes

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1076]
Poproszę o odpowiedzi:
1) czy indeks (oferta->id, typ_opłaty, next_date) jest unikatowy. Czyli czy mogą dla jednej oferty wystąpić dwie opłaty tego samego typu i z tą samą datą naliczenia?
2) czy jeżeli opłata została raz "zaplanowana" (pojawiła się w tej metodzie) to czy może zostać zmieniona (typ, kwota, data naliczenia) ?
3) czy jeżeli opłata została raz "zaplanowana" (pojawiła się w tej metodzie) to czy może zostać usunięta (nie pojawi się ponownie przed upłynięciem next_date) ?
4) powyższe pytania nie będą miały znaczenia jeżeli planujecie udostępnić id dla opłat? Bo zakładam, że każda opłata ma u Was w systemie jakieś id.
Edit:
Zapomniałem
5) co oznacza pole enabled?

**Comment by PawelTaberski** [comment]
Poniżej odpowiedzi na Twoje pytania:
1/ Indeks (oferta->id, typ_opłaty, next_date) jest unikatowy. Dla jednej oferty nie mogą wystąpić dwie takie same opłaty z tą samą datą naliczenia.
2/ Typ nie może się zmienić, kwota oraz data naliczenia mogą ulec zmianie - np. w wypadku opłaty za utrzymanie aktywnych ofert. W przypadku zakupu na danej ofercie opłata zostanie przesunięta o 365 dni. Więcej na ten temat [tutaj](https://allegro.pl/dla-sprzedajacych/zmiana-w-regulaminie-allegro-oplata-za-utrzymanie-ofert-GDeqX15MMUg).
3/ Opłata może zostać usunięta, gdy użytkownik zakończył ofertę przed naliczeniem. Kwota może być mniejsza, gdy użytkownik w momencie naliczenia ma aktywny pakiet.
4/ Obecnie nie planujemy wprowadzania zmian w tej metodzie.
5/ Oznacza status opłaty

**Comment by kfijalko** [comment]
Dziękuję za odpowiedzi. Nie brałem pod uwagę takich zmian. Trochę mi to komplikuje pobieranie, ale dam radę.
Natomiast zastanówcie się nad udostępnieniem "id", to by znacznie ułatwiło życie.
Jak dla mnie wątek do zamknięcia.

**Comment by PawelTaberski** [comment]
Oczywiście przemyślimy, jeśli zdecydujemy się na jakieś zmiany, poinformujemy o tym w dedykowanym komunikacie.
