### ISSUE TITLE
Odpowiednik itemPostageOptions w REST API

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#1077]
Gdzie w REST API znajdę informację o opcjach dostawy wybranych dla konkretnej oferty? 
Chodzi mi odpowiednik doGetItemsInfo -> itemPostageOptions 
Zaznaczam, że aukcje nie mają zdefiniowanego cennika dostawy
GET /sale/offers/{offerId} "delivery->shippingRates" zwraca NULL

**Comment by PawelTaberski** [comment]
Jeśli oferty nie mają zdefiniowanego i podpiętego cennika dostawy to nie pobierzesz informacji o opcjach dostawy z takiej oferty. Tak samo nie wystawisz przez REST API oferty bez cennika.
