### ISSUE TITLE
Problem z połączeniem do sandboxa

### ISSUE THREAD

**Issue by opliplax** [allegro/allegro-api#108]
Od 2 dni mam problem z połączeniem ze środowiskiem testowym. Każda próba połączenia z nowym sandboxem kończy się błędem "Niepoprawna wartość klucza WebAPI lub klucz został zablokowany". Łączenie do https://webapi.allegro.pl/service.php?wsdl działa poprawnie natomiast do https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl niestety nie. Wcześniej wszystko działało poprawnie. Czy po zmianie adresu środowiska testowego klucz powinien być od nowa wygenerowany?

**Comment by delvier** [comment]
Witam, mam taki sam problem.  
Komunikat bledu (j/w)
`System.ServiceModel.FaultException: Niepoprawna wartość klucza WebAPI lub klucz został zablokowany.`

**Comment by dtarczynski** [comment]
Należy przełączyć się na nowy WSDL oraz zarejestrować od nowa aplikacje. Zostaną wygenerowane nowe klucze.

**Comment by MarcinLuczak** [comment]
@opliplax @delvier Tak, dla środowiska trzeba wygenerować nowy klucz WebAPI. Wszystko opisaliśmy tutaj - https://allegro.pl/webapi/general.php#test_platform

**Comment by delvier** [comment]
@MarcinLuczak Postepujac wedle instrukcji i zakladajac konto na sandboxie przy probie pelnej aktywacji dochodze do symulatora przelewow. W efekcie nie moge przejsc przez nastepujacy ekran. Bez pelnej aktywacji konta nie mozna generowac klucza.

![image](https://user-images.githubusercontent.com/1397476/38237733-4490b86a-3728-11e8-9924-dd53070c484a.png)

**Comment by delvier** [comment]
@opliplax Dzieki, widze ze juz sie uzbieral backlog issues :)

**Comment by MarcinLuczak** [comment]
@delvier faktycznie, sprawdziliśmy i aktywacja obecnie nie działa. Przekazałem to zgłoszenie do odpowiedniego działu.

**Comment by MarcinLuczak** [comment]
@delvier aktywacja na Sandboxie powinna już działać.

**Comment by delvier** [comment]
@opliplax udalo ci sie polaczyc z sandboxem po API ?

**Comment by opliplax** [comment]
@delvier Nie miałem czasu tego przetestować. Na razie założyłem konto testowe na nowym sandboksie i wygenerowałem tam klucze. Ufam, że zadziałają ;)

**Comment by delvier** [comment]
@MarcinLuczak prosba o zerkniecie w ticket: Ticket#1246839876 (dot. problemu polaczenia z API.)  Podalem tam dane konta, oraz zdjecia z fiddlera dot. requesta oraz odpowiedzi. W requescie widac dokladnie jaki klucz api jest wysylany.

**Comment by MarcinLuczak** [comment]
@delvier 
> prosba o zerkniecie w ticket: Ticket#1246839876 (dot. problemu polaczenia z API.) Podalem tam dane konta, oraz zdjecia z fiddlera dot. requesta oraz odpowiedzi. W requescie widac dokladnie jaki klucz api jest wysylany.

Sprawdziłem - podajesz nieprawidłowy klucz. Zapewne tutaj https://allegro.pl.allegrosandbox.pl/myaccount/webapi.php/settings wygenerowałeś dwa klucze. Ten drugi, opisany jako do środowiska deweloperskiego, jest bezużyteczny. To tylko pozostałość po starym środowisku testowym - wkrótce to usuniemy z serwisu produkcyjnego i nowego testowego. Wystarczy, że wygenerujesz klucz oznaczony jako środowisko produkcyjne - ten klucz używaj podczas korzystania z naszego nowego środowiska testowego.

**Comment by delvier** [comment]
@MarcinLuczak dzieki za wyjasnienie, faktycznie podawalem zly klucz. 
Teraz juz dziala.
