### ISSUE TITLE
PUT /sale/offers/{offerId}  zwraca dziwny błąd

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#1080]
Występuje problem:  z zasobem z
 - [X ] z zasobem REST API

Skrypty wcześniej działające prawidłowo metodą PUT na zasobie /sale/offers/ , dziś dostają w odpowiedzi nieznany wcześniej błąd

HTTP/1.1 415 Unsupported Media Type
Trace-Id: d82f43fe42a300be
Content-Type: application/json; charset=utf-8
Content-Length: 140
Date: Thu, 17 Jan 2019 14:02:07 GMT

{"errors":[{"code":"NotSupportedException","message":"An error has occurred","details":null,"path":null,"userMessage":"An error occurred"}]}
HTTP/1.1 415 Unsupported Media Type
Trace-Id: b438869a8e4587b7
Content-Type: application/json; charset=utf-8
Content-Length: 140
Date: Thu, 17 Jan 2019 14:02:08 GMT

**Comment by PawelTaberski** [comment]
Wydaje mi się że może być problem z nagłówkiem content-type. Sprawdź czy masz na pewno ustawioną wartość application/vnd.allegro.public.v1+json a nie application/vnd.allegro.beta.v1+json

**Comment by 11mszot** [comment]
Nagłówki z całą pewnością są prawidłowe , skrypt kilka dni temu jeszcze działał
    $headers = [
      'Accept: application/vnd.allegro.public.v1+json',
      'Content-Type: application/vnd.public.v1+json',
      'Authorization: Bearer '.$access_token.'',
    ];

**Comment by PawelTaberski** [comment]
Ale czy one ostatecznie nie są u Ciebie zastąpione tymi, jakie podesłałeś w pierwszej wiadomości:
Content-Type: application/json
Jeśli nie to podeślij proszę pełnego requesta i responsa od Trace-Id: b438869a8e4587b7 przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/mam-problem-z-api-allegro-qzdAgORR5cz). W zgłoszeniu zaznacz, że dan e są potrzebne do ticketa numer 1080 na GitHub-ie. Sprawdzimy w czym jest problem.

**Comment by kfijalko** [comment]
może chodzi o to że brakuje "allegro" 
'content-type: application/vnd.allegro.public.v1+json' != 'Content-Type: application/vnd.public.v1+json',

**Comment by PawelTaberski** [comment]
true musi być identyczny z tym jaki podesłałem czyli: application/vnd.allegro.public.v1+json 
@kfijalko 👍 nawet nie zwróciłem uwagi na początek w głowie miałem tylko czy czasem nie beta

**Comment by 11mszot** [comment]
Istotnie to był powód nieprawidłowej odpowiedzi - moje przeoczenie , natomiast podstawowy problem nadal istnieje

W tej chwili dostaję odpowiedź prawidłową , aczkolwiek  bardzo niezadawalającą

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => You don't have the required permissions to publish offer (sell blocked).
                    [details] =>.
                    [path] =>.
                    [userMessage] => You don't have the required permissions to publish offer (sell blocked).
                )

        )

)

Dostałem od klienta zlecenie na edycję 20 000 aukcji , które zamknęliście z powodu nieprawidłowości w opisie. Tylko jak mam je poprawić skoro blokada nałożona przez was na koncie uniemożliwia ich edycję ?

**Comment by PawelTaberski** [comment]
@11mszot W tej sprawie sprzedawca musi się skontaktować ze swoim opiekunem, jeśli takiego ma bądź przez [formularz kontaktowy](https://allegro.pl/pomoc). My nie zajmujemy się tutaj takimi sprawami, nawet nie mamy możliwości odblokowania takiej sprzedaży.

**Comment by FromAnyHole** [comment]
@PawelTaberski - a tak przy okazji:
Gdzie w oficjalnej dokumentacji REST jest opis zasobu do wysyłki zdjęć ??
To wszystko jest nadal w takiej rozsypce, że lepiej nie próbujcie wyłączać niczego przed wakacjami...

**Comment by FromAnyHole** [comment]
@PawelTaberski - czyli w dokumentacji nie ma tego zasobu...
Widziałem w zeszłym roku ten poradnik, sądziłem zwyczajnie, że coś będzie więcej w dokumentacji.

**Comment by PawelTaberski** [comment]
@FromAnyHole  Nie ze względu na adres na jakim jest dostępny ten konkretny zasób. Pracujemy nad nowym wyglądem dokumentacji ze względu na to, że jej obecny podział, wygląd i możliwości stają się niewystarczalne.
