### ISSUE TITLE
Pole "Wznawianie oferty"

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#1081]
W formularzu Allegro jest pole "Wznawianie oferty (opcjonalnie) po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów". Jak zarządzać nim przez REST API? Po podpięciu ofert wystawianych przez panel Allegro do swojego systemu chciałbym im wszystkim powyłączać tę opcję, by zarządzać wznawianiem już u siebie.

**Comment by PawelTaberski** [comment]
W REST API możesz wystawić ofertę [do wyczerpania zapasów](https://developer.allegro.pl/sale/#new-offer), ale nie ma takiej opcji wznawiania. Zależy nam by wartość stocku była realna. Pamiętaj, że nawet jak oferta się zakończy przez wyprzedanie, to zawsze możesz ją wznowić pod tym samym id (po uzupełnieniu stocku) i nie utracisz popularności.

**Comment by qls-api** [comment]
"W REST API możesz wystawić ofertę [do wyczerpania zapasów] " a co w przypadku licytacji tam nie można ustawić takiej opcji. Należy podać czas trwania. Jak w takim przypadku aukcja ma się wznowić automatycznie.

**Comment by PawelTaberski** [comment]
Licytacje możesz wystawić tylko na określony czas przez REST API 3, 5 7 i 10 dni. Pamiętaj, że po jej zakończeniu zawsze możesz ją aktywować przy pomocy metody  PUT /sale/offer-publication-commands/{commandId} więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

**Comment by qls-api** [comment]
Owszem przy 10 licytacjach fajnie, ale co jak mam 10k , to jest permanentne odpytywanie -> aukcja zakończona -> nie -> wystaw ponownie. 
W starym api (również przez www) ustawiamy parametr "po zakończeniu wystaw ponownie ofertę, jeśli nie zostanie sprzedana" i to allegro zarządza całym procesem. 
Jaki jest sens przechodzić na nowe api ?

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię do zespołu, który zajmuje się tymi zasobami, jeśli zdecydują się wdrożyć taką zmianę, to poinformuję o tym w dedykowanym komunikacie.

**Comment by Ontr** [comment]
Dlaczego permanentne odczytywanie? Znana jest data zakończenia licytacji, wystarczy po tej dacie ją ponownie aktywować. Jeśli były oferty powinno wywalić błąd - brak przedmiotów.

Pytanie do allegro jakie są opóźnienia w aktualizacji danych apropo ofert. Czy da się tak wznowić dokładnie w momencie planowego zakończenia wcześniejszej licytacji, czy co wznowienie aukcje będą się przesuwać o kilkanaście minut.

**Comment by PawelTaberski** [comment]
Wszystkie akcje o ofercie mogą zająć do godziny czasu zazwyczaj jest to czas o wiele krótszy. Zależy od łącza od ilości zakolejkowanych zadań itp.

**Comment by qls-api** [comment]
"Dlaczego permanentne odczytywanie? Znana jest data zakończenia licytacji, wystarczy po tej dacie ją ponownie aktywować.  Jeśli były oferty powinno wywalić błąd - brak przedmiotów. "

Dziennie kończy się 10k aukcji, według twojej sugestii, sprawdzam "tylko" 10k ofert czy należy je ponownie aktywować. 

Przez www można ten parametr ustawić, w czym jest problem aby dodać go do api.
Czy rozważane jest dodanie tej opcji? Jeśli tak kiedy można spodziewać się konkretów ?

**Comment by PawelTaberski** [comment]
Rozumiem, obecnie pobrania takich informacji po REST API nie ma, przekazałem to jako sugestię, do zespołu, który pracuje nad tymi zasobami. Jeśli zdecydujemy się wdrożyć taką informację, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by PawelTaberski** [comment]
Obecnie nie planujemy wprowadzania zmian w czasach trwania licytacji. Jednakże zgłosiłem Twoją uwagę jako sugestię.

**Comment by Kuba-Id** [comment]
Panie Pawle, czy API Allegro po automatycznym wznowieniu oferty:
Parametr: republish = true
informuję w jakiś sposób o nowym numerze aukcji? Jak można poznać numer pod którym API wznowiło daną ofertę?
Moje pytanie dotyczy ofert z licytacją.

**Comment by PawelTaberski** [comment]
@Kuba-Id Takie informacje znajdziesz w dzienniku ofertowym, więcej na temat dziennika znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#journal).

**Comment by vbdbsoft** [comment]
A jak wyłączyć znacznik 'po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów' przez REST API?

**Comment by MaciejFrackowiak** [comment]
@vbdbsoft W modelu oferty znajdziesz obiekt "publication", a w nim pole "republish" - i tu należy wybrać opcję false - przykład znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty).
