### ISSUE TITLE
Odpowiedniki dla metod doGetBidItem2, doSendEmailToUser

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1082]
Czy planowane jest dodanie odpowiedników dla tych metod do REST API?

1. doGetBidItem2: Chodzi o pobranie ofert kupna. Jeśli jest to możliwe przy wykorzystaniu już istniejących końcówek, to musiałem coś przegapić. Można uzyskać od was jakąś wskazówkę?

2. doSendEmailToUser: o tym nie znalazłem żadnego info. Jak realizować wysłanie emaili do klientów za waszym pośrednictwem?

**Comment by PawelTaberski** [comment]
Odnośnie Twoich pytań to co do doGetBidItem2 nie zwracamy już takich danych na froncie i nie jestem w stanie powiedzieć, czy będziemy wdrażać takie zasoby w REST API. Odnośnie wysyłania maili to nie planujemy wdrażania takich metod w REST API. Jeśli będziemy planowali wdrażanie takich zasobów, to poinformujemy o tym w dedykowanym komunikacie.
