### ISSUE TITLE
order/events - An error has occurred

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#1083]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam!
Zaczynam dopiero przygody z waszym API i sporo rzeczy nie rozumiem. 
Próbuje zintegrować Allegro z Comarch Optima, ale tylko na poziomie kupionych rzeczy i zrobienia z tego odpowiedniego dokumentu w systemie ERP. 
Według dokumentacji lista kupionych jest w `order/events`. Aplikacja jest dla testów w konsoli w C#
```c#
        static string authorize = "https://allegro.pl/auth/oauth/token";
        static string allegroAPI = "https://api.allegro.pl/";

        public static void GetOrders()
        {
            string base64 = Convert.ToBase64String(Encoding.ASCII.GetBytes("client_id:secret"));
            var client = new RestClient(authorize);
            var request = new RestRequest(Method.POST);
            request.AddQueryParameter("grant_type", "client_credentials");
            request.AddHeader("Authorization", $"Basic {base64}");

            IRestResponse response = client.Execute(request);
            var content = response.Content;
            var accessToken = JsonConvert.DeserializeObject<AuthorizeResponse>(response.Content);

            var client2 = new RestClient(allegroAPI);
            var request2 = new RestRequest("order/events", Method.GET);

            request2.AddHeader("Authorization", $"Bearer {accessToken.access_token}");
            request2.AddHeader("Accept", "application/vnd.allegro.beta.v1+json");
            request2.AddHeader("Content-Type", "application/vnd.allegro.beta.v1+json");

            IRestResponse response2 = client2.Execute(request2);
            string result = response2.Content;
        }
```
Response jaki otrzymuje:
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}`

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a z ostatecznym requestem jaki od Ciebie do nas wychodzi, dołącz także responsa i trace-id, sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1083 na GitHub-ie.

**Comment by PawelTaberski** [comment]
@troncomputers Dostałem Twojego requesta i problem jednak nie jest w nagłówkach a w autoryzacji, korzystasz z client credentials, która nie ma kontekstu usera i jest przeznaczona do zasobów publicznych. Dlatego masz status 403 Forbidden - Użytkownik jest uwierzytelniony, ale nie ma praw do danego zasobu. Aby korzystać z zasobów nie publicznych skorzystaj z [flow code albo device](https://developer.allegro.pl/auth/).

**Comment by troncomputers** [comment]
Korzystając z flow code dla device również mam błąd:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}`

Status:
 ` HTTP/1.1 405 Method Not Allowed`

**Comment by PawelTaberski** [comment]
Teraz masz ciągle problem z zasobem order/events czy /auth/oauth/device udało się Tobie otrzymać poprawnie tokena z tego flow? Bow podesłanym błędzie widzę ścieżkę dedykowaną do autoryzacji.

**Comment by troncomputers** [comment]
Błąd `HTTP/1.1 400 Bad Request` jest przy próbie pobrania user_code i device_code. Do tokena jeszcze nie doszedłem odkąd korzystam z device flow.

**Comment by PawelTaberski** [comment]
Rozumiem a czy pamiętałeś, aby dodać odpowiedni nagłówek i w body podać client-id:
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'
I czy zarejestrowałeś na nowo aplikację i wybrałeś, że:
"Aplikacja będzie działać w środowisku bez dostępu do przeglądarki albo klawiatury (np. aplikacja konsolowa albo na urządzeniu typu telewizor)"

**Comment by troncomputers** [comment]
Nie jestem orłem programistycznym. Powinniście wziąć pod uwagę, że nie każdy w życiu miał styczność z curl i wie, że komenda `-d client_id={client_id}` znaczy, że trzeba dodać parametr do body. Z punktu widzenia laika takiego jak ja, wasza dokumentacja jest bardzo chaotyczna 😅 
Autoryzacja działa, order/events działają. 
Dzięki za pomoc

**Comment by pawelignatowski** [comment]
Udało mi się powiązać aplikację z kontem allegro sandbox, ale nie rozwizało to mojego pierwotnego problemu z https://api.allegro.pl.allegrosandbox.pl/order/events
nadal mam 403 Zabroniono

**Comment by PrzemyslawLukanowski** [comment]
@pawelignatowski Odpowiemy w wątku #3746.
