### ISSUE TITLE
Checkout-forms na środowisku testowym

### ISSUE THREAD

**Issue by przemekMrzyglod** [allegro/allegro-api#1084]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,
obecnie przy próbie pobrania zamówień na sandboxie wywołanie typu:
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?status=READY_FOR_PROCESSING&offset=0&limit=100
zwracają błąd:

`{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "path": "/order/checkout-forms"
        }
    ]
}`
Podobnie dla statusu: ALL. Błąd nie występuje dla statusów BOUGHT i FILLED_IN.
ClienID jakiego używam do testów: c0a4af6dec364231b716dbc185dfe09d.

Trace-Id nieudanego wywołania: 654fab2b94272d38 , wywołanie: https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?status=READY_FOR_PROCESSING&offset=0&limit=100

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta bez tokena. Na pierwszy rzut oka wygląda to na jakiś problem z nagłówkami.

**Comment by PawelTaberski** [comment]
@przemekMrzyglod a o jakim statusie otrzymujesz odpowiedź?

**Comment by przemekMrzyglod** [comment]
Przy requeście z status=BOUGHT, dostaje jeden element w odpowiedzi:
"id": "61b598f1-a9c6-11e8-968e-0382008e2288"
"status": "BOUGHT"

Przy requeście z status=FILLED_IN dostaję pustą listę:
`{
    "checkoutForms": [],
    "count": 0,
    "totalCount": 0
}`.
Dla statusu READY_FOR_PROCESSING powinienem dostawać przynajmniej jedną odpowiedź, bo zrobiłem dzisiaj zakup testowy, plus ewentualnie jakieś z przeszłości. 
Niestety dla READY_FOR_PROCESSING i ALL pojawia się ten błąd, który jest treścią zgłoszenia.

**Comment by PawelTaberski** [comment]
Sorka mało precyzyjny byłem, chodziło mi o status responsa :-) czyli jak dostajesz odp to masz 200 a jak dostajesz ERROR to jaki jest status 40X?

**Comment by przemekMrzyglod** [comment]
Leci 500 Internal Server Error

**Comment by PawelTaberski** [comment]
@przemekMrzyglod Dziwna sprawa, wygląda to na błąd, zgłosiłem Twój przypadek do głębszej analizy, przez zespół który opiekuje się tym zasobem, proszę o cierpliwość.

**Comment by przemekMrzyglod** [comment]
Dziękuję. 
Tak orientacyjnie ile zazwyczaj trwa proces takiej analizy/poprawy problemu?

**Comment by PawelTaberski** [comment]
Ciężko powiedzieć zależy od tego co jest problemem i na ile jest on złożony. Czasem najdłużej zajmuje samo wykrycie przyczyny problemu, bo pojawia się tylko w specyficznych wypadkach u niektórych userów itp.
