### ISSUE TITLE
Płatność przelewem standardowym a status

### ISSUE THREAD

**Issue by ifiszu** [allegro/allegro-api#1085]
Czy zakończony zakup, przy metodzie płatności 'przelew standardowy' (poza PayU), ustawia status zamówienia na READY_FOR_PROCESSING, czy dopiero późniejsze, ręczne ustawienie go na stronie allegro, na 'wysłano'?

**Comment by PawelTaberski** [comment]
Do momentu, aż nie zostanie to opłacone zgodnie z druczkiem w banku, bądź na poczcie i się nie zaksięguje to będzie status FILLED_IN.

Status wysłano na froncie jest tylko do późniejszego filtrowania sobie wyników na Moim Allegro nie ma innego zastosowania.

**Comment by ifiszu** [comment]
Tzn. mam na myśli opcję 'Płacę przelewem tradycyjnym' (wybierany w ramach opcji 'szybki przelew'). W tym momencie, klient płaci poza PayU, bezpośrednio na konto sprzedawcy. Kiedy, w takiej sytuacji, zamówienie ma status READY_FOR_PROCESSING? Od razu po dokonaniu płatności (chociaż allegro nie ma potwierdzenia, że została dokonana), czy należy ręcznie to wymusić na danym zamówieniu?

**Comment by ifiszu** [comment]
Jasne, rozumiem.
Proszę jeszcze o potwierdzenie, że faktycznie tak jest, gdyż, kiedy testuję omawianą ścieżkę na allegro.sandbox, to, status po skończeniu zamówienia mam READY_FOR_PROCESSING. A skoro jest tak jak mówisz, to testy również powinny uwzględniać to, że przy płatności 'Płacę przelewem tradycyjnym' status danego zamówienia kończy się na FILLED_IN. Powyższa sytuacja sugeruje, że jakoś jednak można na niego wpłynąć i doprowadzić do końca, bądź jest to błąd.

**Comment by PawelTaberski** [comment]
To wszystko zależy jak sobie to oznaczysz w symulatorze płatności, jak sprawdziłem jeszcze na produkcji to jest FILLED_IN. Tak samo jak jak na sandboxie wybiorę ta płatność i ją canceluje.

**Comment by ifiszu** [comment]
Dobra, czyli przy tym rodzaju płatności nie mamy możliwości osiągnięcia statusu READY_FOR_PROCESSING, tak? Musimy to jakoś u siebie obsłużyć.

**Comment by PawelTaberski** [comment]
Dokładnie tak.

**Comment by ifiszu** [comment]
Dziękuję za pomoc.

**Comment by ifiszu** [comment]
Trochę ciężko wyłapać te zamówienia, gdyż w polu provider, mają również wartość 'payu'.

**Comment by ifiszu** [comment]
Chociaż, w polu "paidAmount": { "amount": } powinny mieć wartość 0.00. Przeciwnie do tych płaconych przez PayU.

**Comment by PawelTaberski** [comment]
W wypadku nie zaksięgowania wpłaty w statusie FILLED_IN będziesz miał tylko w strukturze payment pola:
id, type i provider nie ma pola paidAmount ani finishedAt bo nie doszło jeszcze do płatności.

**Comment by ifiszu** [comment]
Racja.
