### ISSUE TITLE
Nie działa parametr limit przy /sale/offers

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1086]
Występuje problem: 
 - [ X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/sale/offers?offset=0&limit=100&seller.id={wycietysellerID}&publication.status=ACTIVE

Mimo, że w żądaniu przekazano parametr limit, to zwracana jest mniejsza liczba rekordów.
Dopiero zwiększanie offset umożliwia pobranie ich wszystkich.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa wraz z trace-id sprawdzimy w czym jest problem. W zgłoszeniu zaznacz proszę, że dane są potrzebne do ticketa numer 1086 na GitHub-ie.

**Comment by aktywnitu** [comment]
A jednak offset działa inaczej: offset*limit
