### ISSUE TITLE
Filtrowanie po statusie dla .../{commandId}/tasks 

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1087]
:bulb: **Sugestia**

Fajnie jakby na tych zasobach gdzie wprowadza się zmiany dla wielu ofert, status można było pobrać np. tylko dla tych ofert którym nie zmieniono wartości z jakiegoś powodu "status" = "FAIL". Np. mam sytuacje gdzie wysyłam zmianę sztuk dla 10 tys ofert i jednej nie udało się zmienić. Teraz żeby wyciągnąć id tej oferty muszę wywoływać wielokrotnie /{commandId}/tasks i szukać tej oferty.

**Comment by PawelTaberski** [comment]
Rozumiem, że chodzi Tobie o możliwość dodania filtrowania po statusie na zasobie /{commandId}/tasks?

**Comment by PawelTaberski** [comment]
Rozumiem, sugestię przekazałem, jeśli zdecydujemy się na wdrożenie takiego rozwiązania, dam znać w dedykowanym komunikacie.
