### ISSUE TITLE
Propozycja nowego zasobu /sale/offers/events

### ISSUE THREAD

**Issue by marcinek1312** [allegro/allegro-api#1088]
:bulb: **Sugestia**
Bardzo pomocne było by dla mnie dodanie nowego zasobu, którym by można było monitorować zmiany w ofertach. Głównie potrzebuję monitorować zmiany ilości dostępnej z każdej oferty. W webapi było doGetSiteJournal i to mi bardzo się przydawało w mojej aplikacji do zarządzania magazynem. Chodzi o taką sytuacją żeby system magazynowy uniemożliwił sprzedaż tego co jest wystawione w allegro bo inaczej mogło by dojść do podwójnej sprzedaży tego samego produktu w dwóch miejscach (na allegro i w systemie magazynowym). Dlatego potrzebuję w momencie gdy ktoś wystawi na allegro np 1 szt jakiegoś przedmiotu to żeby ta 1 szt została zablokowana w systemie magazynowym i nikt nie mógł jej stamtąd sprzedać. I do tego potrzebuję  być nieustannie powiadamiany o każdym zdarzeniu dotyczącym zmian w ofertach. Chyba, że macie na to inny pomysł, ale ja przejrzałem wnikliwie wszystkie zasoby i nie wymyśliłem jak dotychczas prostego algorytmu na obsługę tego przypadku. Aktualnie używam /sale/offers i przeglądam całą listę ofert ale np. mam klienta, który ma 1000 aktywnych ofert i przejrzenie takiej ilości ofert bardzo długo trwa, a trzeba to robić praktycznie nieustannie. Pomocy!

**Comment by PawelTaberski** [comment]
Rozumiem, że potrzebowałbyś jakiś dedykowany zasób do pobrania zestawienia zmian w ofertach. Jednakże, już obecnie możesz to dosyć wygodnie rozwiązać, mianowicie zarządzać sprzedażą zgodnie z tym jak opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/orders/#01).
Dodatkowo musiałbyś śledzić ruch na metodach do zmian stocku w ofercie, jednakże jeśli user dokonuje zmian także przez moje allegro to lepiej polegać na liście z [/sale/offers](https://developer.allegro.pl/my_offers/#1), którą możesz dosyć wygodnie zarządzać i jednokrotnie pobrać nawet 1000 ofert. A jak pobierasz ją co jakiś czas wystarczy proste porównanie stocków między tymi listami, aby wychwycić zmianę.

**Comment by pskz** [comment]
Podczepiam się do tej sugestii, obecny dziennik zdarzeń WebApi zwraca też informacje o zakończeniu oferty, czy jej wznowieniu. Pozwala to na lepszą wymianę danych między Allegro a sklepem z którego wystawiane są aukcje, i poprawne zarządzanie magazynem. 
Dzięki temu też wiadomo które produkty są aktualnie wystawione i aktywne w Allegro. Niezależnie od tego czy klient wznowi/zakończy ofertę przez Allegro czy przez aplikacje, albo oferta zostanie zbita przez Allegro z przyczyn regulaminowych, czy zakończy się z przyczyn naturalnych - na bieżąco aplikacja operuje na świeżych danych.

Bez tego zasobu będziemy musieli okroić aplikację z bardzo pożądanej przez klientów funkcjonalności, utrudni to też monitorowanie aktywnych ofert.

**Comment by PawelTaberski** [comment]
@pskz Rozumiem, oczywiście przekazałem Twoją sugestię, czy dana oferta jest aktywna czy nie możesz obserwować przy pomocy /sale/offers
