### ISSUE TITLE
błędny format zdjęcia - mimo że wystawiane zdjęcie jest w praiwdłowym formacie

### ISSUE THREAD

**Issue by Garbi3500788** [allegro/allegro-api#1089]
Występuje problem z wystawieniem aukcji allegro za pomocą web API. 
Zdjęcie w formacie jpg  info zwrotne 
ERR_BAD_PICTURE_FORMAT: Niepoprawny format zdjęcia (dopuszczalne formaty: GIF, JPG, PNG).

Sprawdzone na wszystkich "dozwolonych" formatach. 

O co może chodzić ?

**Comment by PawelTaberski** [comment]
Jesteś pewny, że poprawnie zakodowałeś zdjęcia w formacie base64Binary? Jeśli tak, to podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem.

**Comment by Garbi3500788** [comment]
Problem polega na tym, że korzystam z narzędzia z wrapowanym kodem źródłowym , myślę że do zapytań/odpowiedzi XMLa będzie ciężko mi się dostać. 

Nie mniej jednak to samo zdjęcie początkiem stycznia jeszcze się wystawiało.

**Comment by PawelTaberski** [comment]
To podeślij choć proszę zdjęcia, z którymi masz problem już zakodowane w taki sposób jak wychodzą z Twojego systemu.

**Comment by Garbi3500788** [comment]
Dwa przykładowe zdjęcia - jedno gif, drugie jpg 
https://drive.google.com/open?id=11PDKiapumDYZ3qO5Xzq-TQnSpsy0oVsw

**Comment by PawelTaberski** [comment]
@Garbi3500788 Przetestowałem i dodanie drugiego zdjęcia po jego przekonwertowaniu na base64 działa jak najbardziej normalnie, natomiast nie możesz przesłać GIF-a. Zdjęcie możesz dodać w formatach: jpg i png. Maksymalny rozmiar zdjęcia: 26 Mpix. Problem musi być z błędnym kodowaniem zdjęcia.

**Comment by PawelTaberski** [comment]
Dokładnie tak, jednakże jeśli Tworzysz nowe oprogramowanie koniecznie korzystaj z zasobów w REST API nie WebAPI, bo metody do wystawiania i zarządzania ofertami usuniemy z WebAPI 3 czerwca 2019, już teraz są oznaczone jako deprecated. Poradnik o tym jak wystawić ofertę przez REST znajdziesz [tutaj](https://developer.allegro.pl/sale/). Tam nie musisz już konwertować zdjęcia na base 64 do wysyłania zdjęć na nasze serwery jest dedykowany zasób.

**Comment by Garbi3500788** [comment]
rozumiem, jestem też świadomy przejścia na resty .. 
natomiast aby na ten moment ruszyć temat muszę zgłosić do swojego obecnego dostawcy ten problem, 
muszę jednak mieć wiadomość - czy ten serwis uległ zmianie przez moje obecne oprogramowanie przestało się integrować z allegro... czy może to coś jedna po stronie dostawcy.  Mogę dostać taką informację ?

**Comment by PawelTaberski** [comment]
Nic mi nie wiadomo, abyśmy zmieniali coś w WebAPI w związku ze zdjęciami, dodatkowo po przetestowaniu i konwertowaniu zdjęcia wszystko wygląda ok.

**Comment by Garbi3500788** [comment]
ok - a bez konwertowania działa ? 
ja nie mogę konwertować z poziomu sklepu , nigdy to nie było robione a mimo to wszystko działało w tym zakresie.

**Comment by PawelTaberski** [comment]
Ale w WebAPI zdjęcia musza być a takim formacie:
```
fvalueImage | base64Binary 
Wartość pola dla plików graficznych.
```

**Comment by Garbi3500788** [comment]
no dobrze, muszą być  od zawsze ? 
początkiem roku wszystkie zdjęcia jakie mam w obecnej postaci wystawiały się więc musiały być w formacie base64Binary . Od strony sklepu nic się nie zmieniło, nie było żadnych instalacji. Nagle te same zdjęcia, które nie były ruszane stały się błędne. (straciły format base64Binary  ?)

**Comment by PawelTaberski** [comment]
Od zawsze był taki format nic w tym zakresie nie zmienialiśmy, do weryfikacji Twojego błędu potrzebowałbym pełnego requesta w formacie XML. Jednakże tak, jak pisałem zdjęcia w formacie jpg po zakodowaniu dodało się poprawnie do oferty. Możesz przesyłać zakodowane zdjęcia w formacie png i jpg.

**Comment by Garbi3500788** [comment]
Od ponad roku czasu wystawiam zdjęcia w ten sam sposób w takim samym formacie. Nigdy nie miałem podobnego komunikatu. Gif jest nie dozwolony a w komunikacie jest wyszczególniony jak format dozwolony. 
Wysyłałem już jpg , które ponoć po "zakodowaniu dodało się poprawnie". 
Może to zakodowanie dodatkowe zostało dołożone w rezultacie jest błąd bo soft dostawcy tego nie robi ?

**Comment by PawelTaberski** [comment]
@Garbi3500788 nic nie zmienialiśmy w metodach do wystawiania ofert przez WebAPI od długiego czasu i nie planujemy tam wdrażania zmian, bo tak jak pisałem 3 czerwca (#1043 ) chcemy usunąć te metody. Nie dodaliśmy żadnego dodatkowego kodowania działa tak to od lat.
