### ISSUE TITLE
Dziwny błąd podczas wysatawiania oferty na sandbox - "description musi być podane"

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#109]
Cześć, wysyłam aukcję ( doNewAuctionExt) na sandbox w fid341, wartość fvalueString dla tego fida to:
```
JSON.stringify({"sections": [{
        "items": [{
            "type": "TEXT",
            "content": "<h1>Tytuł sekcji</h1>"
        }]
      }]
    });
```

Cały czas jest zwracany ten błąd, opis jest zaciagnięty ze strony informuyjącej jak tworzyć nowe opisy.

**Comment by KrzysztofLukanowski** [comment]
Cześć, jeżeli nie używasz encji, zamieść cały opis CDATA, o tak: 
`<![CDATA[
                    {"sections": [
                            {"items": [{"type":"TEXT","content":"<h1>tytuł sekcji</h1>"}]}
                ]}
            ]]>`

proponuję również wystawić ofertę przez GUI, a potem pobrać jej pola za pomocą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842?cod=OGZkZlVlNmJk). Dzięki temu, w FID 342,  poznasz dokładną strukturę nowego opisu.
