### ISSUE TITLE
Previous offer modification is still being processed.

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1091]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

> Could not change offer publication status. Previous offer modification is still being processed. Please try again in a few minutes.

Taki błąd dostaję od czasu do czasu przy próbie wznowienia pojedynczej aukcji przez PUT /sale/offer-publication-commands/{commandId}. Wznawianie aukcji w interwale 150 sekundowym. Czy zmiana statusu może trwać tak długo? Czy inne zmiany ze sobą kolidują np. zmiana sztuk w ofercie?

**Comment by rtnet-pl** [comment]
> Czy inne zmiany ze sobą kolidują np. zmiana sztuk w ofercie?
Dokładnie tak, edycja czegokolwiek w ofercie (poza ceną sprzedaży przez change-price-commands) blokuje ofertę na chwilę

**Comment by MartaNowaczyk** [comment]
@Sojtin zmiana statusu może trwać dłużej niż 150s, dlatego najlepiej odczekać kilka minut z ponawianiem/wysyłaniem innego requestu dot. tej samej oferty
