### ISSUE TITLE
Wartość pola provider przy płatności kartą

### ISSUE THREAD

**Issue by ifiszu** [allegro/allegro-api#1092]
Jaka jest wartość pola method, w payment, kiedy sposobem płatności jest karta?
Na testowym środowisko nie ma możliwości sprawdzenia.

**Comment by ifiszu** [comment]
Przy zamówieniach allegro. Pytanie co pojawi się w polu **provider** (przepraszam, błędnie wcześniej napisałem 'method') gdy klient płaci kartą. Tak wygląda przy płatności payu:
"payment": {
        "id": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "type": "ONLINE",
        "provider": "PAYU",

**Comment by MartaNowaczyk** [comment]
Też będzie "PAYU", bo każda płatność musi iść przez operatora.

**Comment by ifiszu** [comment]
Dziękuję za informację.
