### ISSUE TITLE
Encoded token is not a refresh token

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#1093]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę odświeżyć tokena. Mam response o treści `{"error":"invalid_token","error_description":"Encoded token is not a refresh token"}`

Token z wczoraj zapisany mam w pliku tekstowym i działało cały dzień. Znowu coś robię źle... 😢

**Comment by MartaNowaczyk** [comment]
Token dostępowy jest ważny 12h. Zobacz [tutaj](https://developer.allegro.pl/auth/#refresh-token) jak przedłużyć ważność tokena.

**Comment by troncomputers** [comment]
Wiem, dlatego piszę z problemem, ponieważ podczas zapytania do API o przedłużenie tokena mam taki błąd.

**Comment by MartaNowaczyk** [comment]
Nie podałeś czasem access_tokena zamiast refresh_tokena przy odświeżaniu?

**Comment by troncomputers** [comment]
Czytanie ze zrozumieniem się kłania. Muszę się wrócić do podstawówki i na serio zacząć dokładnie czytać i rozumieć co się czyta 🙈 
Masz rację. Podawałem access_token zamiast refresh_token. Błagam o wybaczenie.
