### ISSUE TITLE
Aktywacja oferty przestała działać?

### ISSUE THREAD

**Issue by Krystus** [allegro/allegro-api#1095]
REST API, całość się zapisuje od strony Allegro wszystko widać jako szkic po stronie serwisu, a finalnie publikacja na zasobie /sale/offer-publication-commands nic nie zmienia. Co jest grane?

```
{#1498 ▼
  +"id": "fcd931f0-bd21-4467-8039-ee2ad3364efb"
  +"taskCount": {#1510 ▼
    +"total": 0
    +"success": 0
    +"failed": 0
  }
}
```

**Comment by MartaNowaczyk** [comment]
@Krystus podaj proszę numer tej oferty.
