### ISSUE TITLE
Wysyłka kurierska na zagraniczny adres - bug?

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#1097]
Witam,

mam nietypową sytuację. W ofercie mam podpięty cennik - kurier pobranie za 16zł oraz wysyłka do Wielkiej Brytanii za 105zł

Kupujący dokonał zakupu i zamiast wyboru przesyłki na Wielką Brytanie wybrał zwykłą przesyłkę kurier pobranie podając jednocześnie adres do GB.
![gb kurier](https://user-images.githubusercontent.com/36523118/51546967-944b3e00-1e65-11e9-87bd-8354e17acd91.png)

Czy taka sytuacja jest w ogóle możliwa/dozwolona?

**Comment by MartaNowaczyk** [comment]
@dlis2010 w tym temacie najlepiej skontaktować się przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Nasza obsługa lepiej poprowadzi Cię przez temat - tutaj odpowiadamy na zgłoszenia dotyczące API allegro.

**Comment by kuli-g** [comment]
@dlis2010 wiesz, nic nowego. Allegro nie prowadzi ŻADNEJ walidacji wprowadzonych adresów, ja u siebie nie raz miałem sytuacje że przy braku możliwości opcji wysyłki zagranicznej kupujący wpisywał zagraniczne adresy i później problemy albo z dopłatami albo zwrotami pieniędzy, że o komentarzach nie wspomnę. Nawet do paczkomatów przepuszczają numery stacjonarne telefonów.
