### ISSUE TITLE
MS allegro

### ISSUE THREAD

**Issue by vittekk** [allegro/allegro-api#1098]
Szukam opisu struktury pliku CSV / XML eksportu danych transakcji. Jest możliwość testowania narzędzia https://ms.allegro.pl? kontem sandbox nie mogę się zalogować.

**Comment by MartaNowaczyk** [comment]
@vittekk wszystko co jest na temat importu i eksportu z MSa znajdziesz [tutaj](https://ms.allegro.pl/pomoc/import-danych-o-szablonach-ID959.html). Ewentualnie możesz w jego sprawie pytać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
Niestety, MS nie ma wersji testowej, także nie potestujesz na sandboxie.
