### ISSUE TITLE
Weryfikacja płatności - REST API

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#1099]
Czy istnieje jakaś możliwość w REST API aby zweryfikować płatność danego zamówienia?

Aktualnie korzystam jeszcze z WebAPI i co jakiś czas zapisuje zamówienia  do XML i dopiero później importuje je do swojego systemu np: po 10 minutach. W pliku XML mam taki parametr:
<postBuyFormPayStatus>Rozpoczęta</postBuyFormPayStatus> 
który po tych 10 minutach może być już inny np: "Zakończona".

A ja bym chciał taka bramkę na którą wyśle requesta z wartoscią np:
<dealId>1973808759</dealId>
lub
<postBuyFormId>962810811</postBuyFormId>

i mi zwróci status płatności.

**Comment by MartaNowaczyk** [comment]
@SoftWareMG Nie ma takiej bezpośredniej metody, która zwróci sam status. Metoda [DoGetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703), gdy podasz transactionsId zwraca status płatności w polu postBuyFormPayStatus. 

Poza tym zgodnie z naszymi [informacjami](https://github.com/allegro/allegro-api/issues/1043), nie planujemy już rozwijać WebAPI, także nowych metod już pewnie nie zrobimy.
