### ISSUE TITLE
Uwierzytelnianie OAuth powoduje automatyczne zalogowanie do Allegro

### ISSUE THREAD

**Issue by dtarczynski** [allegro/allegro-api#11]
Napotkałem na problem podczas uwierzytelniania OAuth dla zewnętrznej aplikacji. Mam zarejestrowaną aplikację, dajmy na to App1.

Problem:
1. Z zewnętrznej aplikacj App1, Użytkownik_1 loguje się za pomocą OAuth. Przechodzi pełne logowanie do Allegro i otrzymuje token.
2. Na tej samej przeglądarce, w tej samej aplikacji App1 Użytkownik_2 loguje się za pomocą OAuth -  ale od razu otrzymuje token właściwy dla Użytkownika_1 (nie ma procesu logowania do Allegro na konto Uzytkownik_2).

Rozwiązanie:
Po uwierzytelnieniu zewnętrznej aplikacji przez OAuth użytkownik **nie powinien być automatycznie zalogowany do Allegro** (nie powinno być przechowywane Auth Cookie w przeglądarce) i powinien przejść pełne logowanie do Allegro.
Użytkownik jest nieświadomy, że zostawia przeglądarkę z zalogowaną sesją do Allegro.

**Comment by AniaMalinowska** [comment]
Dziękujemy za sygnał.
Sugestię w tej kwestii przekazałam do właściwych osób.

**Comment by dtarczynski** [comment]
Czy coś wiadomo odnośnie zgłoszenia? @AniaMalinowska

**Comment by AniaMalinowska** [comment]
Przekazałam ten temat do właściwych osób. Jeśli coś się zmieni w tej kwestii, damy znać. Na ten moment pozostajemy bez zmian w tej sprawie.

**Comment by MartaNowaczyk** [comment]
Odpowiedziałam Ci w wątku #789. 

Na przyszłość, jeśli wątek jest tak stary (lata temu zamknięty), dodaj proszę nowy wątek, opisz swoją sytuację i powołaj się na ten wątek.
