### ISSUE TITLE
doAddPackageInfoToPostBuyForm  - usuwanie numeru

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#1100]
:bulb: **Pytanie/pomysł**
Mam pytanie powiązane z doAddPackageInfoToPostBuyForm - czy planujecie możliwość usuwania nr. przesyłek przez API? Identycznie jak jest po zalogowaniu się na konto i przy zamówieniu usunięcie numeru przesyłki (np. w przypadku gdy ktoś walnie się w adresie wysyłki i trzeba wybić nową etykietę)?
Ewentualnie macie jakiś pomysł jak by to można było zautomatyzować (usunąć zły numer przesyłki)?

**Comment by MartaNowaczyk** [comment]
@magik092 dla podanej metody pewnie nie, bo WebAPI już nie rozwijamy, ale w REST API dlaczego nie. Sugestia przekazana do odpowiedniego zespołu.

**Comment by magik092** [comment]
Wiem że zachciało mi się spojlerów, ale znacie może jakieś przybliżone daty kiedy w REST będzie obsługa numerów paczek?

**Comment by MartaNowaczyk** [comment]
@magik092 zgodnie z zapowiedzią w #1043 chcemy udostępnić dodawanie paczek do końca pierwszego kwartału.
