### ISSUE TITLE
[REST-API] Twój wewnętrzny identyfikator

### ISSUE THREAD

**Issue by mack3d** [allegro/allegro-api#1101]
Dzień dobry,
czy pole "Sygnatura (opcjonalnie)" jest/będzie zwracane w wypełnionych fod-ach?

mack3d

**Comment by MartaNowaczyk** [comment]
@mack3d w REST API sygnatura powinna się pojawić w polu external.id

**Comment by lukasnet** [comment]
Dołączę się do tematu: 
Brak zwracanego pola external.id w offers/listing w aukcjach zalogowanego sprzedającego oraz większych możliwości związanych z tym polem, np. wyszukiwania wg tego pola, aby prosto połączyć aukcję z własnym systemem.

Potrzebuje wyszukiwać aukcję zgodne z własnym ID, ale w metodzie /sale/offers brak filtra, więc szukam  metodą offers/listing w opisie swojego kodu ID, ale wyniki bywają różne i czasem nie dokładne (mimo fallback=false), a brak tam zwracanego pola external.id aby zweryfikować znalezione aukcje.

**Comment by lukasnet** [comment]
Widzę że zwraca te same dane, ale mogłoby zwracać właśnie dodatkowo pole external.id w ofertach zalogowanego sprzedającego.

Cały czas mówię o polu external.id które jest zewnętrzny identyfikatorem sprzedającego czyli własnym ID i o taki filtr chodzi.

**Comment by lukasnet** [comment]
Zgłaszam jeszcze błędne działanie metody offers/listing, pomimo wyłączenia fallback=false i tak wyszukuje podobne aukcje przy wyszukiwaniu w opisie, jeśli zastosuje cudzysłowy "abcd" to nic nie znajduje przez restapi, podczas gdy na www działa to (cudzysłowy) prawidłowo. 
Czyli, czy jest możliwe zastosowanie dodatkowo cudzysłowów w zapytaniu jak poniżej?
GET offers/listing?seller.id=ALLEGRO_ID&phrase="abcd"&searchMode=DESCRIPTIONS&fallback=false

**Comment by MartaNowaczyk** [comment]
@lukasnet fraza w cudzysłowie powinna działać, sprawdziłam u siebie na innym przykładzie i wyniki takie jak na froncie. 
Najlepiej by było, gdybyć dla tych problematycznych zapytań podesłał przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełne cURL-e z requestem i responsem z dopiskiem GitHub #1101. Sprawdzę w czym jest problem.

**Comment by MartaNowaczyk** [comment]
@lukasnet udało się - udostępniliśmy filtr i pole external.id w moich ofertach #1197
