### ISSUE TITLE
[WebAPI] Error Fetching http headers

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1102]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Od dnia 21 stycznia 2019r , od około godziny 9:00, zaczęły lawinowo pojawiać się błędy typu

 `Error Fetching http headers`

W normalnych warunkach, pojawiają się one kilka razy na dobę, ale od wspomnianego momentu występują one w interwałach od kilku minut, do nawet kilku sekund.

Jest to o tyle problematyczne, że wpływa to znacznie na dostępne zasoby systemowe.

Z REST API nie ma problemów - więc wykluczam problem z połączeniem sieciowym.

Załączam logi jednego z procesów, czasy w GMT. 
Jak widać problem nasila się w godzinach szczytu.

[error-fetching-headers.log](https://github.com/allegro/allegro-api/files/2787268/error-fetching-headers.log)

**Comment by MartaNowaczyk** [comment]
@mindc sprawdzimy i damy znać.

**Comment by Radeq** [comment]
@mindc w WebAPI dla błędów soap.faultcode 

```
HTTP
ERR_INTERNAL_SYSTEM_ERROR
ERR_WEBAPI_NOT_AVAIL
ERR_YOU_NOT_SOLD_THIS_ITEM
```

Proponuję poczekać 1 sekundę i ponowić zapytanie. Jeśli wystąpi to 3 raz to wtedy przerwać skrypt.

**Comment by MartaNowaczyk** [comment]
@mindc po wstępnym sprawdzeniu wszystko wygląda dobrze po naszej stronie. Nie zmienialiśmy niczego w tym temacie w ostatnim czasie. Do lepszej weryfikacji potrzebujemy adresu IP.

**Comment by mindc** [comment]
@MartaNowaczyk 
Publicznie nie podam swoich adresów IP, to chyba oczywiste :)

Niestety, wiarygodnego testu na innej maszynie nie byłem w stanie zrobić... 
Ale idąc tropem adresów ip, zrobiłem coś takiego: każdą z moich "wymagających" aplikacji zbindowałem na osobne adresy ip (ten sam serwer, ten sam ISP) i obecnie moje logi z około 30 procesów wyglądają tak jak z tego jednego dla którego załączyłem logi.

Moje wnioski:
- Być może Wasz moduł do "rozliczania" limitów per adres ip zamiast dawać bana, odsyła uszkodzone odpowiedzi, bo jest dość prawdopodobne, że zbliżyłem się do tych limitów.
- Być może brak zasobów po Waszej stronie, w co osobiście wątpię, ale od pewnego czasu sporadycznie dostaję urwane odpowiedzi z WebAPI, tzn. dostaję niepełnego XMLa. SOAP nie może tego sparsować.

Kolejny trop to dziwne odpowiedzi z SOAP, które dostałem od kolegi
`SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl/service.php?wsdl' : Start tag expected, '<' not found`

a zamiast XML'a coś takiego: https://gist.github.com/mindc/4e4050cf7a36d872a170519dbf3ea5c4

Widać hexy co drugą linijkę, a jest to długość następującego po nim łańcucha.
Może ktoś jakiś debug włączył, więc raczej coś musiało być zmieniane w Waszym kodzie :)

**Comment by MartaNowaczyk** [comment]
@mindc zawsze możesz podać IP przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1102

**Comment by MartaNowaczyk** [comment]
@mindc potrzebujemy jeszcze takich informacji:
- czy jesteś w stanie ustalić na jaki adres IP idzie połączenie, które kończy się błędem? Czy wszystkie połączenia z błędami idą na ten sam IP czy na różne?
- czy jesteś w stanie ustalić po jakim czasie dostajesz ten błąd? Czy jest to od razu czy po jakimś dłuższym czasie?

**Comment by mindc** [comment]
@MartaNowaczyk 
Spróbuję podpiąć dodatkowe logowanie do requestów SOAP. Na ich podstawie zrobię zestawienie.

**Comment by mindc** [comment]
@MartaNowaczyk 
Dane zbierałem od północy 27 stycznia, nie ma wyróżniającego się hosta, 
185.31.27.144 - 1969 błędów
5.134.213.77 - 1961 błędów
Występowanie błędów nie zależało od metody, po ponowieniu requestu, otrzymywałem prawidłową odpowiedź.
Nie zauważyłem jakichś charakterystycznych momentów występowania błędów, rozkładały się w czasie dość równomiernie.

Doszukałem się informacji, że błędy w SoapClient (PHP) `Error Fetching http headers` związane są ze zbyt długim czasem oczekiwania na odpowiedź.
Jednak czasy odpowiedzi zwracające błędy wahały się od 20-90 ms.

Co ciekawe, **od 2019-01-27 21:19:26 GMT nie obserwuję już błędów**, poza jedną "czkawką" ok. godz. 2019-01-28 01:55, obejmującą 11 requestów, gdzie rzeczywiście, czasy odpowiedzi przekraczały 500 ms (czyli błąd wygenerowany został raczej prawidłowo)

Zbieram dane dalej.

**Comment by MartaNowaczyk** [comment]
@mindc ok, to czekamy na informacje

**Comment by mindc** [comment]
@MartaNowaczyk 
Ostatnią "czkawkę" obejmującą 32 requesty, zaobserwowałem ok. 2019-01-28 18:47 GMT (tak samo jak przy ostatniej, przekroczone czasy odpowiedzi)

Od tamtej pory, wszystko wygląda prawidłowo, czyli pojedyncze błędy co kilka godzin.

Jednak nie wynikają one z przekroczenia czasu - błąd następuje po 7-30ms od wysłania requestu.
Więc prawdopodobnie otrzymuję uszkodzone odpowiedzi...

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację. My po swojej stronie sprawdziliśmy i u nas nie widać problemów z połączeniem.
