### ISSUE TITLE
Sprawdzanie poprawności zapłaty - dopłaty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1103]
Piszecie tutaj https://developer.allegro.pl/images/surcharges.png jak można sprawdzić poprawność wpłaty. A jeśli klient będzie dopłacał czyli pojawią się dodatkowe dane w strukturze **surcharges** to po dopłacie te pola na powyższym obrazku się same zaktualizują i wyjdzie wszystko OK czy muszę sobie dodawać wartości ze struktury  **surcharges** do payment_price_amount i porównywać z totalToPay_amount ?

**Comment by MartaNowaczyk** [comment]
@pietrach surcharges to oddzielny byt, który nie aktualizuje wartości pierwszej wpłaty od kupującego. W tym przypadku tak jak piszesz musisz brać pod uwagę dodatkowo wartość wpłaty. 
Poza tym zauważyłam, że podajemy tam pierwotną nazwę pola, a poprawnie powinno być summary.totalToPay.amount == payment.paidAmount.amount. Dzięki! Poprawimy przy okazji kolejnego wdrożenia na portalu.
