### ISSUE TITLE
Nick sprzedającego w /offers/listing

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#1104]
:bulb: **Sugestia**

Moja sugestia jest taka, aby /offers/listing zwracał dodatkow dla każdej oferty nick sprzedającego, tak jak zwraca to doGetItemsList. W tym momencie zwracane jest:

[seller] => Array
 (
 [id] => 41392506
 [company] =>
 [superSeller] =>
)

Jesli pobieram wszystkie aukcje z danej kategorii bez sensu jest sprawdzanie np. kilkaset, czy kilka tysiecy razy nazwy użytkowanika dla daneg ID (w zalezności od ilości ofert w kategorii), aby dla każdej oferty poznać nicka sprzedającego. Dla zwykłego człowieka, nick sprzedającego jest bardziej wymowny niż jego ID.

**Comment by juhacz** [comment]
Tak, nazwa użytkownik jest dla mnie ważna.
Dziękuję

**Comment by kfijalko** [comment]
@juhacz jak pobierasz wszystkie oferty w danej kategorii ? 
Chodzi mi o obejście ograniczenia 6000 zwracanych ofert.

**Comment by juhacz** [comment]
Pobieram za pomocą GET /offers/listing używając offset i limit zgodnie z dokumentacją 
https://developer.allegro.pl/documentation/#/offers-listing/getListing
Nic nie wiem o żadnym ograniczeniu do 6000 ofert.

**Comment by kfijalko** [comment]
poprzednia kategoria była za mała ta jest lepsza category.id=257361&limit=100&offset=6000

    "searchMeta": {
        "availableCount": 6000,
        "totalCount": 236343,
        "fallback": false
    },
powyżej 6000 nie da się pobrać

**Comment by juhacz** [comment]
Invalid offset parameter value. Offset should be multiplier of limit and less than searchMeta.availableCount

Źle tego używasz, limit może być maksymalnie 100, więc żeby pobrać porcję aukcji od 5900 do 6000, offset ma wynosić 59, czyli 59*100 = 5900.

**Comment by kfijalko** [comment]
A jak pobrać powyżej 6000? w kategorii jest 200k ofert.

**Comment by juhacz** [comment]
Tak jak Ci wcześniej napisałem, jeśli chcesz pobrać 100 aukcji począwszy od 124500 do 124600 w kategorii, w której jest 200k aukcji, to offset musi być 1245.

**Comment by kfijalko** [comment]
niestety nie

**Comment by kfijalko** [comment]
offset oznacza pozycję oferty od której chcesz zacząć pobierać, nie numer strony
offset - Index of first returned offer from all search results. Must be multiple of limit.

**Comment by juhacz** [comment]
:) upieraj się dalej.
Offset nie jest pozycją, od której chcesz pobrać 100 aukcji, jest przesunięciem, porcją.
offset * limit nie może być większe searchMeta.availableCount

**Comment by kfijalko** [comment]
w postmanie puszczam: https://api.allegro.pl/offers/listing?category.id=257361&limit=100&offset=1245&sort=-popularity&sellingMode.format=BUY_NOW&parameter.11323=1

wynik:
{
    "errors": [
        {
            "code": "InvalidOffsetException",
            "message": "Invalid offset parameter value. Offset should be multiplier of limit and less than searchMeta.availableCount.",
            "details": null,
            "path": null,
            "userMessage": "Zapytanie sformułowane nieprawidłowo. Popraw zapytanie i spróbuj ponownie."
        }
    ]
}

**Comment by juhacz** [comment]
availableCount - Number of results available for navigation. If this number is less than the total count, search criteria (categories, filters) should be narrowed down to make all results available.
totalCount - number of search results for given parameters

Wychodzi na to, że musisz zastosować filtry, aby zawęzić ilość zwracanych danych

**Comment by kfijalko** [comment]
Zgadza się, myślałem że znalazłeś sprytny sposób na pobranie wszystkich ofert z kategorii.
Manipulowanie filtrami i sortowaniem, żeby pobrać ~wszystkie oferty w tej kategorii jest niewykonalne.
Teraz pobieram dane sprzedawców i ciągle łapię blokadę za przekroczenie limitu zapytań na adres ip.

**Comment by mapet241** [comment]
Wracając do wątku jaki jest w temacie czyli dodanie nicku sprzedawcy do infomracji o ofercie: Czy znacie jakiś inny sposób na wydobycie nazwy sprzedawcy, mając jego ID?

**Comment by MartaNowaczyk** [comment]
@mapet241 mamy a planach stworzenie do tego odpowiedniego zasobu. Jeśli się pojawi na pewno poinformujemy o tym w oddzielnym komunikacie.

**Comment by juhacz** [comment]
Póki co: doGetUserLogin
https://allegro.pl/webapi/documentation.php/show/id,104

i odpytywać kilkaset, lub kilka tysięcy razy, jak chcesz pobrać np. nick sprzedającego do każdej z aukcji zwróconej przez offers/listing

**Comment by mapet241** [comment]
@MartaNowaczyk i @juhacz dzięki za informacje.  Pozdrawiam.
