### ISSUE TITLE
Statusy zamówienia

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1105]
Pobierając informacje o zamówieniach poprzez metody **GET /order/checkout-forms** lub **GET /order/checkout-forms/{id}** mamy pole **status**. Jakie są wszystkie możliwe wartości dla pola **status** ? Jest gdzieś to opisane ?

**Comment by MartaNowaczyk** [comment]
@pietrach Możesz poczytać więcej w naszym [poradniku](https://developer.allegro.pl/orders/#01), ale pewnie chodzi ci o te statusy:

- BOUGHT - klient kupił, ale jeszcze nie zapłacił za zamówienie;

- FILLED_IN - zdarzenie z takim statusem może pojawić się więcej niż raz, jeśli klient wypełni FOD kilka razy np. gdy nie zakończy płatności lub doszło do jej anulowania; Pamiętaj, że przy tym statusie mogą zmienić się dane, aż do czasu zakończenia płatności.
- READY_FOR_PROCESSING - klient wypełnił FOD i sfinalizował płatność (status: zakończona), albo wybrał płatność za pobraniem lub odbiór osobisty.

**Comment by LukaszCierocki** [comment]
@MartaNowaczyk Hm. Sądzę, że powinny być jeszcze zasoby umożliwiające zmianę statusu zamówienia na "obsłużone/zrealizowane", bo jeśli mój klient obsługiwał zamówienia po stronie Allegro (lub innej aplikacji) a później zaczął korzystać z mojej aplikacji, to skąd mam wiedzieć, które zamówienia zostały już obsłużone skoro wszystkie mają status READY_FOR_PROCESSING? 

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
@LukaszCierocki rozumiem, jednak checkoutForm to coś w co nie ingerujemy. Zawsze będą tam dane, które wybrał kupujący dla danej transakcji. Pracujemy już nad oddzielnymi zasobami, które w tym pomogą. Więcej o tym w najbliższych tygodniach, w oddzielnym komunikacie.

**Comment by LukaszCierocki** [comment]
@MartaNowaczyk , czekam z niecierpliwością. 

Pozdrawiam
