### ISSUE TITLE
Brak daty startedAt przy pobieraniu pojedynczej oferty

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1106]
sale/offers daje dla oferty rezultat:
      "publication": {
        "status": "ACTIVE",
        "startingAt": null,
        "startedAt": "2019-01-24T10:53:26.706Z",
        "endingAt": null,
        "endedAt": null
      },

podczas gdy sale/offers/{offerId} daje rezultat:
  "publication": {
    "duration": null,
    "endingAt": null,
    "startingAt": null,
    "status": "ACTIVE"
  },

dla oferty do wyczerpania zapasu

Możecie dodać startedAt również do odpowiedzi /sale/offers/{offerId}, żeby nie trzeba było odpytywać sale/offers o ta datę?

**Comment by MartaNowaczyk** [comment]
@neldh dziękujemy za sugestię, sprawdzamy możliwości dodania tego pola.

**Comment by MartaNowaczyk** [comment]
@neldh postaramy się to uspójnić, nie jest to jednak takie proste jakby się wydawało. Potrzebujemy na to jeszcze trochę czasu.

**Comment by MartaNowaczyk** [comment]
@neldh okazało się, że poprawnie nie wyświetlaliśmy tych wartości dla konkretnej oferty i tak samo powinno być dla listy ofert. W takim przypadku, żeby nie pokazywać danych, które mogą nie być zgodne z rzeczywistością postanowiliśmy usunąć je również z widoku listy. Po wdrożeniu zmian w żadnym z tych zasobów nie będzie pól startedAt i endedAt.

**Comment by deneb-k** [comment]
No właśnie. I tak się kończą tego typu kombinacje, o których wspominałem w tym wątku https://github.com/allegro/allegro-api/issues/1047.

**Comment by neldh** [comment]
znaczy wogole nie bedzie ani started ani starting ani ended ani ending? po prostu mam sobie zapomniec ze wyswietle sprzedawcy informacje o tym i poinformowac, ze ma sobie pojsc na strone allegro jak chce to zobaczyc?

**Comment by neldh** [comment]
Czyli żeby zobaczyc kiedy oferta wystartowała/zakończyla się, można teraz zrobić to tylko z poziomu panelu allegro i nie bedziecie tego w zaden sposob przekazywac przez api?

Znaczy się: ending i starting tez znika?

**Comment by MartaNowaczyk** [comment]
1/ W panelu allegro też nie ma widocznych tych dat, dlatego API będzie spójne z widokiem ofert w allegro. 

2/ Nie, endingAt i startingAt zostają.

**Comment by imper86** [comment]
@MartaNowaczyk kiedy będzie wdrożona ta zmiana?

**Comment by MartaNowaczyk** [comment]
@imper86 wraz z wersją public zasobu, która jest w przygotowaniu. Jak się pojawi poinformujemy o tym w oddzielnym komunikacie.

**Comment by imper86** [comment]
@MartaNowaczyk czy możecie jeszcze rozważyć usuwanie tych informacji? IMO to żadna tajemnica kiedy aukcja się rozpoczęła i kiedy została zakończona (wstrzymana). 

Problem polega na tym, że wiele systemów pracujących na Waszym API używa tych dat na różne sposoby i tylko niepotrzebnie generujecie nam dodatkową pracę. Zrozumiałbym gdyby chodziło o jakieś tajne informacje, ale to?

**Comment by MartaNowaczyk** [comment]
@imper86 już rozważaliśmy i jak pisałam...

>okazało się, że poprawnie nie wyświetlaliśmy tych wartości dla konkretnej oferty i tak samo powinno być dla listy ofert. W takim przypadku, żeby nie pokazywać danych, które mogą nie być zgodne z rzeczywistością postanowiliśmy usunąć je również z widoku listy. Po wdrożeniu zmian w żadnym z tych zasobów nie będzie pól startedAt i endedAt.

myślę, że taka niepewna informacja też by was nie satysfakcjonowała.

**Comment by neldh** [comment]
Lepszy rydz niż nic, ale nie każdy rydze lubi...
