### ISSUE TITLE
Pobieranie zamówień GET /order/checkout-forms

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1109]
Co się stanie gdy pobierając zamówienia **GET /order/checkout-forms** podamy zakres dat np. **lineItems.boughtAt.lte=2018-07-31T08%3A48%3A14.889Z&lineItems.boughtAt.gte=2018-08-03T08%3A48%3A14.888Z** i będzie zamówienie gdzie klient zakupił np. 4 różne produkty. Jeden z produktów będzie miał datę zakupu spoza podanego zakresu a reszta będzie się mieściła w podanym zakresie. Czy metoda ta wtedy zwróci tylko 3 produkty czy całe zamówienie ?

**Comment by MartaNowaczyk** [comment]
@pietrach jako data zakupu dla całego zamówienia jest brana najświeższa data zakupu danego lineItems, czyli np. masz 3 zakupy: 1 kupileś tydzień temu, 2 kupileś wczoraj, 3 kupileś dzisiaj - łączysz te 3 zakupy do jednej płatności i masz nowe zamówienie z data zakupu z dzisiaj. 

Odpowiadając na pytanie. Jeśli najświeższy zakup mieści się w zakresie to zwrócimy ci całe zamówienie. Jeśli się nie mieści nie zwrócimy go wcale - nie zwracamy niepełnych zamówień.
