### ISSUE TITLE
Błąd metody pricing/fee-preview na sandboxie

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#111]
Wywołanie metody na endpoincie /pricing/fee-preview powoduje błąd. W środowisku produkcyjnym wszystko działa.

Request:

```
curl https://sandbox.allegroapi.io/pricing/fee-preview -i \
-H "Accept-Language: pl-PL" \
-H "Accept: application/vnd.allegro.public.v1+json" \
-H "Content-Type: application/vnd.allegro.public.v1+json" \
-H "Api-Key: <REDACTED>" \
-H "Authorization: bearer <REDACTED>" \
-d "{\"offer\":{\"type\":\"SHOP\",\"category\":{\"id\":\"250884\"},\"duration\":\"PT720H\",\"unitPrice\":\"208.99\",\"quantity\":\"1\",\"soldQuantity\":\"1\",\"numberOfPhotos\":\"1\",\"bold\":false,\"highlight\":false,\"emphasized\":false,\"departmentPage\":false,\"emphasizedHighlightBoldPackage\":false},\"includeQuotingBundles\":true}"
```

Response:

```
HTTP/1.1 500 Internal Server Error
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 3acda50b9ecf8031
Date: Wed, 04 Apr 2018 11:05:45 GMT
X-RateLimit-Remaining: 8999
X-Content-Type-Options: nosniff
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-Length: 144
X-RateLimit-Limit: 9000
```

`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal Server Error","details":null,"path":null,"userMessage":"Internal Server Error"}]}`

Próbowałem również na adresie podanym w dokumentacji:

```
curl https://api.allegro.pl.allegrosandbox.pl/ -i \
-H "Accept-Language: pl-PL" \
-H "Accept: application/vnd.allegro.public.v1+json" \
-H "Content-Type: application/vnd.allegro.public.v1+json" \
-H "Api-Key: <REDACTED>" \
-H "Authorization: bearer <REDACTED>" \
-d "{\"offer\":{\"type\":\"SHOP\",\"category\":{\"id\":\"250884\"},\"duration\":\"PT720H\",\"unitPrice\":\"208.99\",\"quantity\":\"1\",\"soldQuantity\":\"1\",\"numberOfPhotos\":\"1\",\"bold\":false,\"highlight\":false,\"emphasized\":false,\"departmentPage\":false,\"emphasizedHighlightBoldPackage\":false},\"includeQuotingBundles\":true}"
```

Response:

```
HTTP/1.1 404 Not Found
Trace-Id: 4def00a081d7caf3
Content-Type: application/json; charset=utf-8
Content-Length: 165
Date: Wed, 04 Apr 2018 11:06:40 GMT
```

`{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}`

**Comment by KrzysztofLukanowski** [comment]
Sprawdziłem przed chwilą, nie potwierdziłem błędu, jest okej. Poniżej znajdziesz prawidłowy CURL:
`curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/pricing/fee-preview \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'accept-language: PL' \
  -H 'api-key: eyJjbGllbnRJZCI6IjgzZDE2ZTA5LTk5MGUtNDk4My04YTQ0LTM3MjU0NzlmMDI3YSJ9.Z8LyuEg6wsW6TQPkKrC3lpIZmgWJOs6rbjcf_u5v5dY=' \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjI4ODgyNDgsInVzZXJfbmFtZSI6IjQzNDczNzcwIiwianRpIjoiMTZhYzM2MjMtN2U3ZS00YWQ5LTgxNzItM2ViYmFkZmUyZjAxIiwiY2xpZW50X2lkIjoiODNkMTZlMDktOTkwZS00OTgzLThhNDQtMzcyNTQ3OWYwMjdhIiwic2NvcGUiOlsiYWxsZWdyb19hcGkiXX0.YUi-QExgebIwSsmsszkdjOdT5FYqoc-V0iZx16N5TTAxDB-MFp7J_s2H8fpO666dDXEyOkeig57re5u_I_enFAeC9imYh1kJ9CkyiXwkpxW-H6OgX3-h7nwwINsG5zMOLiG0A9x8NMBiIie64kmixxli6kWmvOF86O1i0B0sKSftyOR0mSJSCChLVYF1xo_DwW4svogEIW_NbOL5fmjuuSjOc95gDKghmg3iDnIf9HhDqUR1iYqftWe1pPvPTaV9dEeFZr7DWLJAUfMJCAclI_yULx6m3givkL6wG-0b_Qy2x1Q1Se32P_bzFMxFsb5IYX1RmhMM-zaqvA7ow' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -H 'postman-token: 59125c50-09a3-7002-50b5-65423ae01307' \
  -d '{  
   "offer":{  
      "shop":true,                           
      "category":{                            
         "id":"250884"
      },
      "duration":"PT720H",                    
      "unitPrice":"208.99",                     
      "quantity":"1",                         
      "soldQuantity":"1",                  
      "numberOfPhotos":"1",                 
      "bold":false,                          
      "highlight":false,                       
      "departmentPage":false,               
      "emphasized":false,                     
      "emphasizedHighlightBoldPackage":false  
   },
   "includeQuotingBundles":true               
}'`
