### ISSUE TITLE
Błąd /order/checkout-forms

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1110]
Próbuje wywołać metodę **/order/checkout-forms** i cały czas dostaję poniższy błąd. Inne metody działają.

[errors] => Array
        (
            [0] => Array
                (
                    [code] => NotAcceptableException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
                )

        )

**Comment by kfijalko** [comment]
Jak mam taki błąd to pierwsze co sprawdzam to "Accept header" w tym wypadku application/vnd.allegro.beta.v1+json

**Comment by pietrach** [comment]
Pomogło dzięki
