### ISSUE TITLE
GET /order/checkout-forms - zmiana danych

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1111]
Metoda GET /order/checkout-forms.
Piszecie, że jeśli zamówienie ma status FILLED_IN lub BOUGHT to dane się mogą zmienić jeszcze.
Pytanie czy zawartość struktury "lineItems" też się może zmienić czy chodzi tylko o dane klienta ?

**Comment by MartaNowaczyk** [comment]
@pietrach nic nie powinno się zmienić. W przypadku, gdy klient kupi coś jeszcze poza tym zamówieniem, a potem łącznie zapłaci za to co maiał w poprzednim zamówieniu + dodatkowy zakup, tworzymy nowe zamówienie pod innym id.

**Comment by kfijalko** [comment]
@MartaNowaczyk czyli utworzy nowy checkout-form z tymi samymi line-item-id? Poprzednie check-out-forms zostaną w statusie Filled_id lub BOUGHT?

**Comment by kfijalko** [comment]
Dodatkowo nowy check-out-form przyjdzie z event->status 'READY-FOR-PROCESSING' bez poprzedzających statusów filed i bouhgt?

**Comment by MartaNowaczyk** [comment]
@kfijalko 

> czyli utworzy nowy checkout-form z tymi samymi line-item-id? Poprzednie check-out-forms zostaną w statusie Filled_id lub BOUGHT?

poprzednie w checkout-form zostaną nadpisane (usunięte - zostanie tylko ostateczne prawidłowe zamówienie)

> Dodatkowo nowy check-out-form przyjdzie z event->status 'READY-FOR-PROCESSING' bez poprzedzających statusów filed i bouhgt?

będzie nowe zdarzenie w events z 'READY-FOR-PROCESSING', które będzie kierowało do checkout-forma z innym id. Stare statusy bought i filled_inn pozostaną bez zmian.

**Comment by pietrach** [comment]
Czyli w końcu zmieniają się jednak wartości w strukturze lineItems czy nie ? Czy jakakolwiek daba z tej struktury ulega zmianie czy nie ? Czy od samego początku od zakupu jest niezmienna ?

"lineItems": [
        {
          "id": "62ae358b-8f65-4fc4-9c77-bedf604a2e2b",
          "offer": {
            "id": "3213213",
            "name": "Name of purchased offer",
            "external": {
              "id": "string"
            }
          },
          "quantity": 1,
          "originalPrice": {
            "amount": "123.45",
            "currency": "PLN"
          },
          "price": {
            "amount": "123.45",
            "currency": "PLN"
          },
          "selectedAdditionalServices": [
            {
              "definitionId": "string",
              "name": "string",
              "price": {
                "amount": "123.45",
                "currency": "PLN"
              },
              "quantity": 1
            }
          ],
          "boughtAt": "2018-01-01T10:23:43.123"
        }
      ],

**Comment by MartaNowaczyk** [comment]
@pietrach w przypadku, gdy ktoś kupi wiele przedmiotów oddzielnie, nie zapłaci i później wypełni dla nich wspólny FOD zmienia się id checkoutForm i liczba lineItemów w tablicy lineItems, a struktura każdego aktu zakupowego pozostaje bez zmian

1. Kupujący zrobił 2 zakupy (u tego samego sprzedawcy, dwa oddzielne akty zakupowe)--> checkoutFormId: "X" - w tablicy lineItems masz 2 oddzielne akty zakupowe, gdzie każdy ma swój lineItemId: lineItemId: "1", lineItemId: "2"
2. Kupujący robi kolejny zakup u tego samego sprzedającego co w pkt. 1 --> dostajesz checkoutFormId: "Y", lineItemId: "3"
3. Kupujący zaznacza wszystkie powyższe nieopłacone zakupy i wypełnia do nich wspólny FOD --> dostajesz checkoutFormId: "Z"; dla tablicy lineItemsId zwrócimy lineItemId: "1", lineItemId: "2", lineItemId: "3" 

Mam nadzieję, że udało mi się to jakoś zrozumiale napisać. Jeśli nie, daj proszę znać.

**Comment by pietrach** [comment]
Czyli to oznacza, że jest tworzone całkowicie nowe zamówienie Z ? A co z zamówieniami X i Y ? Mam nadzieje, że nie są kasowane. Czyżby zostały w statusie BOUGHT albo FILLED_IN i tak już będą wisieć ?

**Comment by pietrach** [comment]
Widzę, że powyżej jest odp. czyli jednak są kasowane :-)

**Comment by pietrach** [comment]
Ale skoro tak to czy jest gdzieś w API informacja, że dane zamówienie powstało na bazie innych ? Albo, że dane zamówienie zostało usunięte ?

**Comment by pietrach** [comment]
Z tego co piszesz to oznacza, że lineItemId się nie zmienia. Ono przechodzi z tą samą wartością do nowego zamówienia ? Jeśli tak to czy mogę przyjąć zasadę że jeśli mam zamówienie w statusie READY_FOR_PROCESSING to wszystkie inne zamówienia gdzie występują lineItemId z tego obecnego mogę usunąć / anulować ?

**Comment by MartaNowaczyk** [comment]
@pietrach tak, możesz usunąć, bo jeżeli w danym checkoutFormId masz status READY_FOR_PROCESSING to jest to ostateczne zamówienie kupującego (no chyba, że się mailowo ze sprzedającym skontaktuje ;) 

To w /order/events znajdziesz wszystkie etapy zamówienia

**Comment by pietrach** [comment]
A jak to jest w panelu Allegro. Tam takie zamówienia są usuwane i pojawia się to ostateczne prawidłowe czy może te stare pozostają ze statusem anulowane ?

**Comment by MartaNowaczyk** [comment]
w panelu też dostajesz tylko to prawidłowe, ostateczne zamówienie.

**Comment by kfijalko** [comment]
Przepraszam, że się tak wtrącam ale ten wątek mnie bardzo zaciekawił. Nie chcę zaczynać nowego, żeby info było w jednym miejscu.
Czy może być taka sytuacja:
1) Klient kupuje O1 (oferta-1) i ma CF1 (checkout-form-1)
2) Klient kupuje O2 i ma CF1
3) Klient kupuje O3 i ma CF2
Czy musi dokończyć wszystkie czy może teraz wypełnić CF3 tylko dla O1 i O3 ?

**Comment by pietrach** [comment]
To ja jeszcze mam takie pytanie. Czy jest w ogóle taka możliwość:

Klient A kupuje towar X (1 szt.) oraz Y (1 szt.) od sprzedawcy B => tworzy się checkout form = 1
Klient A kupuje towar Z (1 szt.) od sprzedawcy B => tworzy się checkout form = 2

Czyli mamy 2 zamówienia tego samego klienta od tego samego sprzedawcy. Czy klient ma możliwość zapłacić tylko za 1 towar z checkout form 1 oraz za cały checkout form 2 ? Czy jeśli się płaci to tylko za całe checkout formy i nie ma możliwości płacić za pojedyncze produkty z jakiegoś checkout forma ?

**Comment by MartaNowaczyk** [comment]
@kfijalko może np. zaznaczyć w panelu allegro O1 i O3, wybrać opcję zapłać i wypełnicć dla nich wspólny CF3

@pietrach nie można rozdzielać zamówienia na pojedyncze akty zakupowe. 
Czyli odp. na pytanie: nie ma możliwości płacić za pojedyncze produkty z jakiegoś checkoutForma.

**Comment by pijablonski** [comment]
> W przypadku, gdy klient kupi coś jeszcze poza tym zamówieniem, a potem łącznie zapłaci za to co maiał w poprzednim zamówieniu + dodatkowy zakup, tworzymy nowe zamówienie pod innym id.

Wasz poradnik (https://developer.allegro.pl/orders/ ) sugeruje kontakt z klientem, gdy zamówienie przez dłuższy okres czasu nie zmienia statusu na READY_FOR_PROCESSING. Kontakt ten nie będzie jednak potrzebny, jeśli utworzone zostało nowe zamówienie w cytowany powyżej sposób. 

Czy istnieje obecnie możliwość jednoznacznego odróżnienia sytuacji "z zamówieniem nic się nie dzieje" i "zamówienie porzucono i utworzono nowe", aby wiedzieć, kiedy należałoby skontaktować się z kupującym?

Sugestia:
Zmiana statusu poprzedniego zamówienia na "CANCELLED" lub podobny.

**Comment by MartaNowaczyk** [comment]
@pijablonski w przypadku, gdy klient opłaci więcej niż jeden zakup dostaniesz nowe zdarzenie ze zmienionym checkoutForm.id i nowe zamówienie z tym nowym id. Opublikowany schemat pokazuje ogólne zasady postępowania z obsługą zamówień. Pojedyncze przypadki trzeba ograć sobie logiką po swojej stronie. Przy zamówieniach nie zmieniają się identyfikatory pojedynczych aktów zakupowych lineItems.id, co może być pomocne przy identyfikacji zamówień.
W zdarzeniach zobaczysz wszystko co działo się od zakupu do statusu READY_FOR_PROCESSING (RFP), a w zamówieniach zobaczysz tylko ostateczny wygląd zamówienia. Gdy np. nie znajdziesz w zamówieniach odpowiedniego checkoutForm.id ze zdarzeń to jest to sygnał, że klient mógł zapłacić łącznie za różne akty zakupowe. To tylko taki przykład, a podejść do tematu może być wiele.

Jeśli chodzi o sugestię, to przekażę ją do odpowiedniego zespołu, który zajmuje się tym obaszarem. Jednak jeśli chodzi ci o same zamówienia (/order/checkoutForm) to po prostu zastępujemy je innym (w tym przypadku inny checkoutForm.id) i nie zwracamy poprzedniego.

**Comment by pijablonski** [comment]
> Przy zamówieniach nie zmieniają się identyfikatory pojedynczych aktów zakupowych lineItems.id, co może być pomocne przy identyfikacji zamówień.

To mogłoby faktycznie wystarczyć, jednak obserwujemy coś innego:
Przykład: ten sam kupujący, ta sama aukcja (zakupiony jeden produkt), ta sama ilość, odstęp kilkunastu minut: 
checkoutFormId - lineItemId - dealId - status
41cc06b2-f330-11e8-a3ae-cf533b1552e1 - 41cc06b0-f330-11e8-a3ae-cf533b1552e1 - 1929738215 - READY_FOR_PROCESSING
e95f07f2-f32c-11e8-a324-6b04d022ed12 - e95f07f0-f32c-11e8-a324-6b04d022ed12 - 1929717444 - FILLED_IN
fa373f52-f32e-11e8-b490-751898cc8c92 - fa373f50-f32e-11e8-b490-751898cc8c92 - 1929730780 - FILLED_IN

W tej chwili muszę zakładać że dwa formularze checkoutForm ze statusem FILLED_IN nadal mogą zostać sfinalizowane. Jedyną możliwością sprawdzenia, że klient prawdopodobnie zakupił już to, czego potrzebował, jest porównanie identyfikatora aukcji i zakupionej liczby sztuk towaru.
Algorytm ten zakłada jednak z góry, że klient nie chciał złożyć i opłacić dwóch identycznych zamówień.

**Comment by MartaNowaczyk** [comment]
@pijablonski bo to pewnie trzy oddzielne zakupy. To czy klient kupi to już zagadka, dlatego można realizować te RFP, a tamte zostawić, dać czas i określić czas kontaktu z klientem lub po jakimś czasie wystąpić o zwrot prowizji. Dopiero na tej podstawie można coś stwierdzić, bo założenie, że nie chciał kupić dla wszystkich takich przypadków nie będzie prawdziwe.
