### ISSUE TITLE
sellformId 13 

### ISSUE THREAD

**Issue by danmckp** [allegro/allegro-api#1113]
otrzymuje od dzis odpowiedz ale nie na wszystkich ofertach z allegro. W czym jest problem ?

Opcja 'Zgadzam się na wysłanie przedmiotu za granicę' dla formularza 'Opcje dot. transportu' (sellformId 13) jest niedostępna

**Comment by MartaNowaczyk** [comment]
@danmckp pole fid 13, o którym piszesz już dawno nie jest widoczne w ofercie ani na formularzu wystawiania, stąd teraz zwracamy taką informację.

**Comment by szymon-convertis** [comment]
A czy jest sposób aby przez API zablokować wysyłkę za granicę? 
W tym momencie przy zakupie na aukcji, która nie ma podanej ceny dla wysyłek za granicę można podać kraj wysyłki inny niż Polska

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości, ani przez front, ani przez API. Możesz jedynie dodać w polu "additionalInfo" przy wysyłce, że nie wysyłasz za granicę, ale nie zablokuje to i tak takiej możliwości.
