### ISSUE TITLE
Pobieranie kategorii SOAP API vs REST API

### ISSUE THREAD

**Issue by grojanteam** [allegro/allegro-api#1114]
Dlaczego w REST API nie mogę jednym zapytaniem pobrać wszystkich kategorii tak jak to było w SOAP używając tej metody https://allegro.pl/webapi/documentation.php/show/id,46 ? 

Jak mam pobrać wszystkie kategorie jeśli ich jest mnóstwo? 

Mam za każdym razem pytać API o każdą kategorię podając rodzica? 

Jak to się ma do oszczędności zasobu, skoro będę odpytywać wasz serwer za każdym razem gdy ktoś będzie mapować kategorię i atrybuty?

Chyba że jest jakaś metoda w REST, której nie ma w dokumentacji albo nazywa się inaczej niż powinna?

**Comment by MartaNowaczyk** [comment]
@grojanteam tak jak piszesz - nie pobierzesz od razu całego drzewa. Sposób w jaki mamy to zrobione pozwala, a nawet rekomenduje wywołanie większej ilości małych zapytań zamiast jednego dużego.

**Comment by mindc** [comment]
@MartaNowaczyk 
Dużo małych zapytań jest OK przy wystawianiu ofert, ale pobranie całego drzewa (czasami jest to potrzebne) zajmuje sporo czasu.
WebAPI - ok. 10-20 minut
REST API - ok. 2-3 godziny 
Dla każdej możliwej kategorii osobny request + dodatkowy request dla każdego z liści gdy pobieramy parametry = niepotrzebne zużywanie Naszych i Waszych zasobów.

**Comment by MartaNowaczyk** [comment]
@mindc dzięki za sugestię.

**Comment by grojanteam** [comment]
@MartaNowaczyk @mindc 
jak dla mnie pobranie całego drzewa z kategorii WebAPI zajmowało 1 - 2 minut (nie pobierałem atrybutów)
dla REST API dramat, ale sprawę sobie rozwiązałem, jak ktoś próbuje zlistować dzieci jakiejś kategorii do w locie pobieram i zapisuje do bazy ( następnym razem nie triggeruje ponownego pobierania )

**Comment by j4r3kb** [comment]
Ja mam jeszcze pytanie odnośnie id zwracanych kategorii.
Widzę, że na REST mamy nowe kategorie z id nie jako integer ale UUID. Np. "Moda" - ea5b98dd-4b6f-4bd0-8c80-22c2629132d0
Czy obecnie tych kategorii SOAP nie zwraca, czy mają one id typu integer?

**Comment by MartaNowaczyk** [comment]
Tak na REST są UUIDY. Z upływem czasu powinno ich być u nas mniej.
Obecnie UUIDy są tylko w identyfikatorach części kategorii pierwszego rzędu, do których nie można dodawać ofert. Nigdzie indziej nie powinno ich być. Liście nigdy nie mają UUID'ów.
Jeśli chodzi o SOAP, to tam powinny być tylko id typu integer.

**Comment by j4r3kb** [comment]
Nie lepiej było by dla zasobu '/sale/categories' dodać przy każdej kategorii głównej property "children" gdzie była by lista id jej dzieci zamiast dodatkowo odpytywać '/sale/categories?parent.id={categoryId}'?

**Comment by MartaNowaczyk** [comment]
Przekażę twoją sugestię do odpowiedniego zespołu.

**Comment by j4r3kb** [comment]
Przy okazji dobrze było informację o ' '/sale/categories?parent.id={categoryId}' dodać do dokumentacji bo jest jedynie w tutorialu.

**Comment by MartaNowaczyk** [comment]
Sprawdzimy i jak co dodamy.
