### ISSUE TITLE
Allegro REST / order / checkout-forms, separate between sent and not sent orders?

### ISSUE THREAD

**Issue by lintonmack** [allegro/allegro-api#1116]
Hello,

I wonder if anyone can help me out with a question. I am trying to integrate a system with the Allegro REST api.
Currently, we deal with our orders manually through the Allegro admin panel and once finished we mark them as Sent, which is displayed as "You Sent".

I have pulled the last 100 orders in from Allegro using / order / checkout-forms. All of these orders have previously been dispatched and have been marked on the admin panel as "You Sent" but when I have retrieved the orders using REST there is nothing to suggest these have been dispatched.

I have looked at the events section of the documentation but this also does not provide the information I require. 

Can anyone advise on how I can separate orders that have been marked as sent from those, which have not been?

Many Thanks,

**Comment by MartaNowaczyk** [comment]
@lintonmack you can't do this by API Allegro. This option is available only in the allegro panel. 
If we add something like that, we will send information about it in a separate message.

**Comment by lintonmack** [comment]
Thank you for your replies.

@kfijalko  your English is a lot better than my Polish ;)
I didn't know about the "doGetPostBuyFormsDataForSellers", I've read the documentation and this will help me a lot. Thank you for recommending it.

@MartaNowaczyk if it somethign that is added at a later date please let me know. :)
