### ISSUE TITLE
Brak informacji o opłatach utrzymaniowych w nadchodzących opłatach

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1117]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mimo, że opłata utrzymaniowa jest naliczana, REST API zwraca wyłącznie opłaty za wystawienie. Brak na liście opłat typu INEFFECTIVE_LISTING_FEE, czyli opłat utrzymaniowej oferty.

**Comment by MartaNowaczyk** [comment]
@aktywnitu podaj proszę przykład takiej oferty do weryfikacji. Możesz tu, możesz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1117

**Comment by aktywnitu** [comment]
Przepraszam. Jednak problem wynikał po mojej stronie - podczas pobierania ofert offfset zwiększany kolejno 1,2,3 zamiast 1*limit, 2* limit, ...
