### ISSUE TITLE
Metoda GET /order/checkout-forms - offset i limit

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1118]
Piszecie "Suma offset i limit nie może przekroczyć 10 000."
Co to oznacza ? Że nie mogę zrobić ?offset=10000&limit=100 ? Jeśli tak to skąd takie ograniczenia ?
To znaczy, że jak będę chciał pobrać wszystkie zamówienia od początku a zamówień jest 20 000 to nie mogę ?

**Comment by kfijalko** [comment]
Tak jak napisali w dokumentacji:
Skorzystaj z filtrów:
**Status zamówienia** - np. https://api.allegro.pl/order/checkout-forms?status=BOUGHT
**Data zamówienia** - zakres czasu przekazujesz zgodnie z przyjętym standardem, ale chcąc przekazać datę w url, pamiętaj, aby wykorzystać encode, np. https://api.allegro.pl/order/checkout-forms?lineItems.boughtAt.lte=2018-07-31T08%3A48%3A14.889Z&lineItems.boughtAt.gte=2018-07-31T08%3A48%3A14.888Z

**Comment by pietrach** [comment]
OK

**Comment by neldh** [comment]
Pozwolę sobie odkopać.
Czy jest jakaś szansa na zwiększenie tego limitu?
Tweakowanie filtrów, żeby czasem nie przekroczyć 10000 jest bardzo toporne, a zdarza się to szczególnie w czasie sezonu jak ktoś ma duży obrót...

**Comment by PatrykBocian** [comment]
@neldh Zgłosiłem twoją sugestię do odpowiedniego zespołu.
