### ISSUE TITLE
ERR_WEBAPI_KEY when using sandbox WebAPI

### ISSUE THREAD

**Issue by boobiq** [allegro/allegro-api#112]
Hello,

I'm trying to make some requests through WebAPI in sandbox environment and I always get ERR_WEBAPI_KEY error. I generated both keys on "Ustawienia klucza WebAPI" page, but when I make a request to sandbox URL and use any keys (production or sandbox), I get this ERR_WEBAPI_KEY error.
When I try production key on production URL, that works fine.

Account username is: **autodiely**

Request looks like this:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoQueryAllSysStatusRequest>
         <ser:countryId>1</ser:countryId>
         <ser:webapiKey>[MY SANDBOX KEY]</ser:webapiKey>
      </ser:DoQueryAllSysStatusRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

Response is:
```xml
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_WEBAPI_KEY</faultcode>
         <faultstring>Niepoprawna wartość klucza WebAPI lub klucz został zablokowany.</faultstring>
         <faultactor>doQueryAllSysStatus - Invalid webapi key</faultactor>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

I'm not sure what is wrong, I tried to press "zresetuj hasło" button few times to no avail :)

Thanks for any help!

**Comment by MarcinLuczak** [comment]
@boobiq 

When you are at https://allegro.pl.allegrosandbox.pl/myaccount/webapi.php/settings you should user only from "Środowisko produkcyjne (Prod/live environment)". Here you have a screen with this:

![klucz_sandbox](https://user-images.githubusercontent.com/16252414/38309070-421b86b8-3819-11e8-828f-757d8139e9e0.png)

This situation (two WebAPI keys in https://allegro.pl.allegrosandbox.pl/myaccount/webapi.php/settings) its something which was appriopriate for old test environment, but it have no connection to new test environment. Soon we will delete second key and possibility to generate it.

**Comment by boobiq** [comment]
@MarcinLuczak 

I see. But this account I'm using is production one, I can't login with it on sandbox page, that's how it's supposed to be, right? I should create new user through sandbox page (which I did already) and wait for my account to be activated after I "paid" through payment simulator, is that right?

If so, I will just wait for activation and try again with sandbox user.

Thank you!

**Comment by boobiq** [comment]
@MarcinLuczak 

thank you again!

Can you maybe speed up my activation somehow? 3 days passed and it's still awaiting activation and I would like to test and develop my application :)

If not, that's okay, I just don't want to wait and maybe there is some issue preventing my activation.

Thanks

**Comment by MarcinLuczak** [comment]
@boobiq No problem. There was a problem with your activation, so I activate your account manualy.

**Comment by boobiq** [comment]
@MarcinLuczak hi again, is it possible to activate account `samo.woolk@gmail.com` as well? It was registered long time ago, but it's not activated yet, not sure why, maybe same problem.

Thanks

**Comment by MarcinLuczak** [comment]
@boobiq Hi. Your account is now active.
