### ISSUE TITLE
Błąd ERR_CAPTCHA_REQUIRED

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#1120]
Dzień dobry,

W pewnych momentach przy próbie logowania api zwraca następujący błąd

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_CAPTCHA_REQUIRED</faultcode>
         <faultstring>Dostęp przez API dla użytkownika został zablokowany z powodu zbyt dużej liczby błędnych logowań na konto. Odblokowanie dostępu nastąpi dopiero po poprawnym zalogowaniu się wskazanego Użytkownika z poziomu serwisu WWW: https://allegro.pl/enter_login.php?captcha=1.</faultstring>
         <faultactor>doLoginEnc - The WebAPI access for this User has been blocked due to too high number of unsuccessful login attempts. The access will be restored only after the User successfully logs in to the account using the WWW service (https://ssl.allegro.pl/enter_login.php?captcha=1).</faultactor>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

Po zalogowaniu się blokada jest zdejmowana i możliwe jest uzyskanie sesji przez webapi, lecz po pewnym czasie bez wykonywania żadnych ponownych requestów o uzyskanie sesji problem powraca.

Czy ta blokada jest zakładana na ip z którego wykonywana jest błędna próba logowania czy globalnie?
Czy ktoś wykorzystując metodę brute force znając login może wywołać taką blokadę?

**Comment by MartaNowaczyk** [comment]
Jest to właśnie zabezpieczenie przed tego typu działaniami. O blokadach i limitach znajdziesz więcej informacji [tutaj](https://allegro.pl/webapi/faq.php#faq_1).

**Comment by pawelosajda** [comment]
Dobrze rozumiem? Ktoś może wziąć mój publiczny login zalogować się przez API błędnie 4 razy i w ten sposób zablokować globalnie dostęp do API, wymagając zalogowania się przez interfejs webowy? Co w przypadku gdyby ktoś umyślnie wysyłał błędne requesty i blokował aplikacje, jak można się przed tym zabezpieczyć? Czy taka blokada nie powinna być nakładana na IP z którego jest wykonywane błędne logowanie?

**Comment by deneb-k** [comment]
Dokładnie tak jest. Błąd znany od wielu lat.

Mieliśmy kiedyś sytuację, że klientowi non stop dostęp blokował jakiś skrypt panelu miniaturek, którego autorowi chyba się zmarło czy coś, w każdym razie nie było możliwości wyłączenia tego. Rozwiązanie problemu było takie, że Allegro zmieniło mu nazwę użytkownika :D

**Comment by MartaNowaczyk** [comment]
Tak, tak to działa. Natomiast każdy integrator może korzystać z metody do logowania doLoginWithAccessToken, która wymaga uzyskania accessTokena, czyli użytkownik i tak będzie musiał się zalogować na Allegro i ewentualną captchę wypełnić, jednak trzeba też pamiętać, że jeżeli aplikacja ma już sesję, albo token, to będzie nadal działać.
