### ISSUE TITLE
Rest API - brak odpowiedzi na requesty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1121]
Zauważyłem, że RestAPI często nie odpowiada np. ostatnio zawiesiło się na tym requeście **GET /sale/offers/7769436514**. Chwilę potem wywołałem sobie ręcznie ten pojedynczy request i było ok. Mam aplikację, która pobiera zamówienia a następnie do każdego produktu jest pobierany EAN za pomocą GET /sale/offers/{id}. I za którymś razem jest brak odpowiedzi co powoduje, że aplikacja czeka aż serwer rzuca błędem 500 lub 502. Być może RestAPI nie radzi sobie jak jest dużo requestów w małym odstępie czasu. Errorów, że limity są wyczerpane nie dostaje.

Korzystam z biblioteki CURL

```
$headers = array(
			'Accept: application/vnd.allegro.public.v1+json',
			'Content-Type: application/vnd.allegro.public.v1+json',
			'Authorization: Bearer <access-token>',
			'Accept-Language: pl-PL'
		);
$connection = curl_init();
curl_setopt($connection, CURLOPT_URL, '<adres>');
curl_setopt($connection, CURLOPT_HTTPHEADER, $headers);
curl_setopt($connection, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($connection, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($connection, CURLOPT_SSLVERSION, 6);
curl_setopt($connection, CURLOPT_RETURNTRANSFER, 1);
$response = curl_exec($connection);
```

**Comment by pietrach** [comment]
Dosłownie przed chwilą ten błąd wystąpił znów tym razem na **GET /sale/offers/7632307581**

**Comment by PawelTaberski** [comment]
Podeślij proszę trace-id przypadków w których nie otrzymujesz odpowiedzi wraz z statusem jaki otrzymujesz, sprawdzimy w czym jest problem.

**Comment by pietrach** [comment]
To jest przykład. Musiałem ustawić timeouty w CURL bo inaczej bym nie uzyskał tego loga

```
*   Trying 185.31.27.150...
* TCP_NODELAY set
* Connected to api.allegro.pl (185.31.27.150) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
*  start date: Jan 24 00:00:00 2018 GMT
*  expire date: Jan 29 12:00:00 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-18T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-24T23%3A59%3A59.000Z&offset=650&limit=50 HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer <token>
Accept-Language: pl-PL

< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: 5d8af58c01e6b5ea
< Date: Mon, 28 Jan 2019 10:58:27 GMT
< X-RateLimit-Remaining: 8944
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 58484
< X-RateLimit-Limit: 9000
< 
* Operation timed out after 20004 milliseconds with 2450 out of 58484 bytes received
* Closing connection 0
```

**Comment by pietrach** [comment]
OK, zmieniłem, dam znać teraz. Tutaj nie ma znaczenia konkretny request. Po prostu tak jakby Wasz serwer przestał odpowiadać w pewnym momencie na jakieś tam żądanie.

**Comment by pietrach** [comment]
Kolejny przykład błędu:

```
*   Trying 185.31.27.150...
* TCP_NODELAY set
* Connected to api.allegro.pl (185.31.27.150) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
*  start date: Jan 24 00:00:00 2018 GMT
*  expire date: Jan 29 12:00:00 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /order/checkout-forms?lineItems.boughtAt.gte=2018-12-06T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2018-12-12T23%3A59%3A59.000Z&offset=1250&limit=50 HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
Authorization: Bearer <token>
Accept-Language: pl-PL

< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: c6ebd36b205d11ea
< Date: Mon, 28 Jan 2019 12:37:40 GMT
< X-RateLimit-Remaining: 8889
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 58764
< X-RateLimit-Limit: 9000
< 
* Operation timed out after 20003 milliseconds with 8168 out of 58764 bytes received
* Closing connection 0
```

**Comment by pietrach** [comment]
Nic nie blokuje.

**Comment by pietrach** [comment]
Myślałem, że może to wina zbyt niskiej wersji PHP ale zmieniłem na 5.6 i dalej to samo. Poniżej błąd:

```
*   Trying 5.134.213.11...
* TCP_NODELAY set
* Connected to api.allegro.pl (5.134.213.11) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
*  start date: Jan 24 00:00:00 2018 GMT
*  expire date: Jan 29 12:00:00 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-03T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-09T23%3A59%3A59.000Z&offset=450&limit=50 HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
Authorization: Bearer <token>
Accept-Language: pl-PL

< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: e3a86f4cc1536987
< Date: Mon, 28 Jan 2019 14:23:24 GMT
< X-RateLimit-Remaining: 8934
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 57523
< X-RateLimit-Limit: 9000
< 
* Operation timed out after 20007 milliseconds with 32723 out of 57523 bytes received
* Closing connection 0
```

**Comment by PawelTaberski** [comment]
Miałbym do Ciebie dwa pytania:

- Czy próbowałeś wykonywać requesty z innej sieci i innego serwera?
- Czy 20 sekund to jest twój timeout, czy masz ustawione wyższe, a mimo to zrywa połączenie?

**Comment by pietrach** [comment]
1. Tak wczoraj byłem zalogowany na telefonie i było to samo, dziś jestem w firmie i też to samo. Jeśli chodzi o serwer to jest home.pl
2. Tak 20 sekund to mój timeout gdyż jakbym go nie ustawił to curl by mi nic nie zwrócił tylko wisiałby do momentu aż serwer rzuci błędem 500 lub 502. Dzięki temu timeoutowi mogłem Wam podesłać te powyższe logi.

**Comment by PawelTaberski** [comment]
Sprawdziliśmy i po naszej stronie wszystko wygląda poprawnie, nagłówki i body zostały zwrócone. Może problem jest z jakimś serwerem proxy? Widać, że nagłówki do Ciebie docierają, ale jest problem z pobraniem body responsa.

**Comment by pietrach** [comment]
Zgłosiłem sprawę do administratora serwera. Zobaczymy czy uda im się znaleźć przyczynę.

**Comment by rtnet-pl** [comment]
1. zamknij curl po wykonaniu requestu
2. ewentualnie sprawdź opcję CURLOPT_FORBID_REUSE

Chodzi o to, że pod spodem zostaje otwarte połączenie (keep-alive) z którego curl sobie korzysta, ale w pewnym (złym) momencie zostaje ono zamknięte przez serwer.

**Comment by pietrach** [comment]
@rtnet-pl Tak robię. Po prostu zapomniałem tego wkleić w kodzie powyżej => curl_close($connection);

**Comment by pietrach** [comment]
@PawelTaberski home.pl twierdzi, że nic nie blokuje

**Comment by pietrach** [comment]
Może opiszę jak działa moja aplikacja. Bo to jest w tej chwili najważniejszy problem do rozwiązania. Mam jakiś zakres dat i chcę sobie pobrać zamówienia. Zamówienia pobieram na ajaxie po 50 w jednym żądaniu. Jak jedno żądanie ajaxowe się zakończy to wywołuje za 3 sekundy następne i tak aż wszystko pobierze. Poniżej przykłady kolejnych wywołań:

GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=0&limit=50

GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=50&limit=50

GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=100&limit=50

.........

GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=700&limit=50

Często jest tak, że wszystko się wykonuje OK ale często jest ten error, o którym piszę. I w tym powyższym przypadku na tym ostatnim żądaniu się wywaliło:

```
*   Trying 5.134.213.11...
* TCP_NODELAY set
* Connected to api.allegro.pl (5.134.213.11) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
*  start date: Jan 24 00:00:00 2018 GMT
*  expire date: Jan 29 12:00:00 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=700&limit=50 HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
Authorization: Bearer <token>
Accept-Language: pl-PL

< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: d138d1d374af0e98
< Date: Tue, 29 Jan 2019 17:33:57 GMT
< X-RateLimit-Remaining: 8828
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 60740
< X-RateLimit-Limit: 9000
< 
* Operation timed out after 20004 milliseconds with 11027 out of 60740 bytes received
* Closing connection 0
```
Po tym błędzie przygotowałem sobie skrypt, w którym wywołałem sobie to żądanie, na którym się wywalił i teraz wszystko ok. Poniżej log.

```
*   Trying 185.31.27.150...
* TCP_NODELAY set
* Connected to api.allegro.pl (185.31.27.150) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
*  start date: Jan 24 00:00:00 2018 GMT
*  expire date: Jan 29 12:00:00 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-09T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-15T23%3A59%3A59.000Z&offset=700&limit=50 HTTP/1.1
Host: api.allegro.pl
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
Authorization: Bearer <token>
Accept-Language: pl-PL

< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: 9813a8a993d72cc1
< Date: Tue, 29 Jan 2019 17:48:54 GMT
< X-RateLimit-Remaining: 9000
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 60740
< X-RateLimit-Limit: 9000
< 
* Connection #0 to host api.allegro.pl left intact
```

**Comment by pietrach** [comment]
Przeniosłem aplikację na inny serwer i tam działa :-)

**Comment by PawelTaberski** [comment]
@pietrach Czyli jednak coś blokowali na tamtym serwerze.

**Comment by pietrach** [comment]
A jeszcze mam takie pytanie bo zauważyłem, że np. przy wywołaniu **GET /sale/offers/7638120791** zwracany jest m.in. nagłówek **Transfer-Encoding: chunked**
 ale jak pobieram listę zamówień np. **GET /order/checkout-forms?lineItems.boughtAt.gte=2019-01-23T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2019-01-29T23%3A59%3A59.000Z&offset=0&limit=50** to już tego nie ma.

**Comment by PawelTaberski** [comment]
Zależy to od implementacji danej usługi po naszej stronie, w zależności od tego przy niektórych zasobach zwracamy nagłówek Transfer-Encoding: chunked, albo Content-Length.

**Comment by pietrach** [comment]
Z drugiej strony zastanawiam się dlaczego ten błąd występuje tylko w tej metodzie do pobierania zamówień a w innych nie. Może coś specyficznego tam zwracacie jakieś nagłówki itp. ? Jesteście pewni że nie blokujecie nic ?

**Comment by PawelTaberski** [comment]
@pietrach Tak, sprawdzaliśmy i nie widzimy żadnych problemów. Ponadto nikt więcej nie zgłasza takich błędów, jeśli nagle zaczęlibyśmy blokować to zdecydowanie więcej osób miałoby taki problem.

**Comment by pietrach** [comment]
A może nie ma odpowiedzi wystarczająco szybko i dlatego ten błąd ? Możecie sprawdzić czas odpowiedzi na zapytania dotyczące listy zamówień ?

**Comment by PawelTaberski** [comment]
Sprawdziłem i średni czas odpowiedzi na GET /order/checkout-forms przy "totalCount": 60 to na 100 wywołaniach od 130 ms do 230 ms

**Comment by pietrach** [comment]
A sprawdź przy totalCount = 1300

**Comment by PawelTaberski** [comment]
Rożnica będzie niewielka bo maksymalny limit to 100 także więcej danych nie pobierzesz jednym requestem musisz wtedy korzystać z offseta, chodziło mi tylko o ilość danych, to w sumie powinienem podać "count": 60, a nie total.

**Comment by pietrach** [comment]
Ja to testuje gdzie totalCount = 1300 i przesuwam offset o 50 i jest limit = 50

**Comment by PawelTaberski** [comment]
W takim wypadku czasu są jeszcze krótsze do około 200 ms
