### ISSUE TITLE
Brak cennika dostaw w szczegółach oferty pobranych przez REST API.

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1122]
:bulb: **Sugestia**

Najprawdopodobniej to nie bug, ale taki właśnie sposób działania.
Pobierając dla niektórych ofert szczegóły poprzez REST API brak w danych informacji o koszcie dostawy / cenniku dostaw (NULL).
Niestety nie można stworzyć nowego cennika / dopasować istniejący, gdyż brak informacji o kosztach dostawy w danej ofercie. 
Jeśli potrzebny id przykładowej oferty, to proszę napisać, chociaż jest to zbędne, o ile działa to w ten sposób jak opisałem.

**Comment by aktywnitu** [comment]
Rozumiem ten problem wynikający z rozbieżności API.
Rozdądne jednak wydawałoby się udostępnienie Sprzedawcy narzędzia typu Uzupełnij brakujące parametry, tylko dedykowane do cenników i ewentualnie lokalizacji, które też nie są wszędzie ustawione, a jednak wymagane. Wówczas Sprzedawca sam mógłby uzupełnić brakujące dane.

**Comment by aktywnitu** [comment]
Można by to zrobić dodając dodatkowy filtr w Moje oferty - "Oferty bez podpiętego cennika dostaw".

**Comment by aktywnitu** [comment]
Albo jeszcze inaczej - dodając możliwość filtrowania ofert po więcej niż jednym ID w polu szukaj ofert.
Wówczas programiści odesłali by Sprzedawcę linkiem z parametrem GET do odfiltrowanej części ofert, w których masowo lub wybiórczo może podpiąć cenniki.

**Comment by aktywnitu** [comment]
Prosiłbym o info, czy któraś z tych propozycji przejdzie, czy jednak trzeba kombinować.

**Comment by PawelTaberski** [comment]
@aktywnitu Przekazałem Twoje sugestie odnośnie cenników, czy wdrożymy takie rozwiązanie niestety nie jestem na chwilę obecną powiedzieć. Obecnie możesz na jednym koncie mieć nawet 250 cenników także wydaje mi się że jesteś w stanie ogra każdy warunek zarówno dla małych jak i dużych części.

**Comment by manoos** [comment]
Czy cenniki dostaw to jedyna możliwość ustawienia ceny dostawy dla oferty? Czy będzie możliwe tak jak teraz ustawienie indywidualnej ceny dla oferty nie wykorzystując cennika?

**Comment by PawelTaberski** [comment]
W REST API jest możliwość dodawania przy tworzeniu oferty tylko cenników, ale możesz mieć cennik z 1 metodą dostawy, jednakże zalecamy większy wybór dla kupujących.

**Comment by manoos** [comment]
To wiem :) Pytanie czy będzie możliwe ustawianie cen dostawy bez cenników, tak jak jest to teraz w WebApi ?

**Comment by PawelTaberski** [comment]
@manoos  Obecnie nie przewidujemy takiej możliwości, idziemy w stronę cenników, dzięki czemu zmiana danej metody dostawy nie wymaga edycji x ofert tylko 1 cennika który jest do nich przypisany.

**Comment by manoos** [comment]
Właśnie takiej informacji potrzebowałem, bo w dokumentacji nie było napisane, że nie będzie już takiej możliwości :)
Dzięki.

**Comment by manoos** [comment]
A jeszcze takie pytanie czy znana jest już data wyłączenia metod WebApi umożliwiających aktualizację cen dostawy ?

**Comment by PawelTaberski** [comment]
Tak, metody do wystawiania i edycji ofert przez WebAPI wygasimy 3 czerwca, więcej informacji znajdziesz tutaj #1043

**Comment by manoos** [comment]
Dzięki
