### ISSUE TITLE
Pytanie dotyczące metody doNewAuctionExt

### ISSUE THREAD

**Issue by BusterLodz** [allegro/allegro-api#1123]
Witam,
Dzisiaj odkryłem, że metoda doNewAuctionExt otrzymała status deprecated. Co to dokładnie oznacza? Bo z moich doświadczeń wynika, że ma status do usunięcia, ale powinna jeszcze działać. Natomiast metoda na chwilę obecną nie działa.

**Comment by PawelTaberski** [comment]
Metoda powinna jeszcze działać normalnie, jaki masz z nią problem?
Jej wygaszenie zapowiedzieliśmy m.in. tutaj. #1043
