### ISSUE TITLE
Limit ofert przy operacjach grupowych

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1124]
Jakie są limity ilości ofert przy wysyłaniu:
PUT /sale/offer-publication-commands/{commandId}
PUT /sale/offer-modification-commands/{commandId}
PUT /sale/offer-price-change-commands/{commandId}
PUT /sale/offer-quantity-change-commands/{commandId}

**Comment by PawelTaberski** [comment]
Dla wszystkich tych komend limit wynosi 1000.
