### ISSUE TITLE
Problemy z pobieraniem jpg-ów

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1126]
Kwestia pośrednio tylko związana z API: Wydaje mi się, czy ostatnio częściej niż zwykle są problemy z pobieraniem zdjęć z allegrowskiego serwera?

**Comment by PawelTaberski** [comment]
Aby, zbadać sprawę potrzebowałbym jakiś konkretów :-) jeśli zauważyłeś jakieś nieprawidłowości podeślij nam trace-id takich przypadków, sprawdzimy w czym jest problem

**Comment by lukada4100** [comment]
Tego typu sprawy...
[1881_Full.txt](https://github.com/allegro/allegro-api/files/2831955/1881_Full.txt)

**Comment by lukada4100** [comment]
Kurcze, czy tylko u mnie to tak słabo działa? Dzisiaj praktycznie nic nie daje się zrobić...

**Comment by lukada4100** [comment]
A czemu właściwie WebApi zwraca stary adres zdjęcia, pod którym dopiero dostaje się przekierowanie na nowy adres? To przekierowanie jest spowalniaczem.
W Rest widzę, są aktualne adresy.
