### ISSUE TITLE
Problem na produkcji - eventy

### ISSUE THREAD

**Issue by ifiszu** [allegro/allegro-api#1127]
Występuje problem: <ze środowiskiem produkcyjnym>
 
Dziś, z naszej aukcji sprzedało się zamówienie, zawierające trzy produkty. Zamówienie jest jedno, zaś eventów ze statusem READY_FOR_PROCESSING jest 10... Proszę o podpowiedź, skąd takie zajście. Dodam, że pozostałych statusów jest: BOUGHT: 1, FILLED_IN: 2.

**Comment by PawelTaberski** [comment]
Potrzebowałbym do zbadania sprawy więcej konkretów, podeślij proszę responsa przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) z zaznaczonymi danymi, które budzą Twoją wątpliwość, sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1127 na GitHub-ie.
