### ISSUE TITLE
Problem przy pobieraniu listy komentarzy

### ISSUE THREAD

**Issue by dgloo** [allegro/allegro-api#1128]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-Id 2416ef2caa86aa5d

Witam, mam problem z pobraniem listy komentarzy. Na chwile obecną korzystam z Postmana do ogarnięcia zapytań. Posiadam ważny `access_token` utworzony przy użyciu device flow. Jestem w stanie pobrać np. listę wystawionych przedmiotów (trace-id tego zapytania 6ae7d60efeaccdcd).

Przy próbie wywołania endpointu `https://api.allegro.pl/sale/user-ratings` bez żadnych parametrów (pomijając nagłówki) zwraca mi błąd 400
`{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "path": "/sale/user-ratings"
        }
    ]
}`

Dodając parametr `user.id=<moj_login_allegro>`. Zwraca mi błąd 403 bez żadnej wiadomości. Jakieś rady?

Dodatkowo czy jest możliwość pobierania listy komentarzy + pobierania listy zamówień bez ciągłego odświeżania tokena (t.j. co 12h)?

Dzięki

**Comment by PawelTaberski** [comment]
@dgloo Czy nie korzystasz czasem z autoryzacji typu client credentials? Ona nie ma kontekstu usera dlatego jest przeznaczona tylko do zasobów publicznych typu listingi, bądź wywołanie dostępnych metod dostawy itp.

**Comment by PawelTaberski** [comment]
Podsumowanie ich jest publiczne /users/{userId}/ratings-summary natomiast /sale/user-ratings jest niepubliczny. 
Czy na pewno wbijasz poprawnie tzn:
/sale/user-ratings?user.id=
możesz odpytać tylko o id usera na którego masz token, inaczej również otrzymasz 403

**Comment by dgloo** [comment]
Dzisiaj podrzucę Wam cały proces krok po kroku na kontakt.

**Comment by PawelTaberski** [comment]
Dostałem Twoje dane i już widzę w czym jest problem, w zasobach:
GET /users/{userId}/ratings-summary
GET /sale/user-ratings?user.id=xxxxxx
Powinieneś podać jako userId id klienta a nie login czyli w Twoim wypadku 4233xxxx
Id klienta na jakiego jesteś zalogowany otrzymasz np. przy rozkodowaniu tokena dostępowego.

**Comment by PawelTaberski** [comment]
Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/auth/#checkApp), wszystkie tokeny dostępowe są w technologi JWT.

**Comment by dgloo** [comment]
Dzięki za pomoc. Dzisiaj postaram się sprawdzić czy działa. Mała sugestia. Może zmienicie w dokumentacji https://developer.allegro.pl/documentation/#/user-ratings/getUserRatingsUsingGET typ zmiennej ze stringa na integer?

**Comment by PawelTaberski** [comment]
Faktycznie może to wprowadzać drobne zamieszanie sprawę zgłosiłem poprawimy 👍
