### ISSUE TITLE
RestAPI - pobieranie danych użytkownika

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1129]
Czy jest jakaś metoda w RestAPI, która pozwala na pobranie danych klienta mając jego id (id zalogowanego użytkownika) albo login ? Jakoś nie mogę się doszukać więc pewnie nie ma.

**Comment by pietrach** [comment]
W takim razie jak mogę pobrać dane użytkownika (jego adres itp.) za pomocą starego WebAPI mając jego id lub login ?

**Comment by PawelTaberski** [comment]
Możesz pobrać tylko publiczne dane, bądź wszystkie dostępne dane danego usera, jeśli jesteś na niego obecnie zalogowany. Nie możesz pobrać danych adresowych dowolnego użytkownika. Wszystkie dostępne w tym zakresie metody znajdziesz [tutaj](https://allegro.pl/webapi/documentation.php/theme/id,64).

**Comment by pietrach** [comment]
Znalazłem już. Jest coś takiego jak **doGetPostBuyData**

**Comment by PawelTaberski** [comment]
To się zgadzam sądziłem, że chodzi Tobie o dane jakiegokolwiek usera niekoniecznie związanego z zakupem.
