### ISSUE TITLE
[REST API]  Jak wyszukiwać oferty po słowie kluczowym lub kategorii?

### ISSUE THREAD

**Issue by anadoba** [allegro/allegro-api#113]
Cześć,

Chciałbym osiągnąć coś na wzór listy ofert, jaką otrzymujemy po wpisaniu po prostu "długopis" na przeglądarkowym allegro.pl
Jednak nie jestem w stanie nigdzie tego znaleźć, a dokumentacja REST API ogranicza się do https://developer.allegro.pl/documentation/

Sam dotarłem jedynie do listowania ofert danego sprzedawcy: https://api.allegro.pl/offers?seller.id=20906092&offset=0&limit=100
jednak interesują mnie oferty z całego serwisu.

Kiedy wywołuję po prostu gołe https://api.allegro.pl/offers to dostaję error code `NoSignificantQueryParamException`

Pytanie do Was:
- jak mogę wyszukać listę ofert po słowie kluczowym? i to najlepiej z danej kategorii produktów?

**Comment by anadoba** [comment]
> Wszystkie dostępne na REST API metody opisaliśmy na wskazanym przez Ciebie portalu developerskim.

Niestety to nie jest prawda...

W REST API istnieją przynajmniej 2 działające endpointy, które nie są w żaden sposób opisane w dokumentacji.
https://api.allegro.pl/offers?seller.id=20906092&offset=0&limit=100
https://api.allegro.pl/categories/2

Pierwszy z nich to listowanie ofert ograniczone do 1 sprzedawcy, czyli w REST API jednak taka metoda istnieje. 
Co więcej, metoda akceptuje konkretne query paramy typu `seller.id`, `offset`, `limit`.

Skoro powyższe listowanie ofert przez REST działa to podejrzewałem, że jesteście w stanie udostępnić nam tutaj inne query paramy pozwalające na wyświetlanie ofert.

**Comment by AniaMalinowska** [comment]
Na ten moment nie udostępniamy tej metody do publicznego wykorzystania. Tym samym nie gwarantujemy, że to, z czego korzystasz będzie stabilne, będzie zwracać prawidłowe dane itp.
Wszystkie metody, które udostępniamy do publicznego wykorzystania na REST API opisaliśmy na wspomnianym [portalu developerskim](https://developer.allegro.pl/documentation/).

Jak już wspomniałam, pracujemy nad tym, aby w niedalekiej przyszłości udostępnić metodę dla list ofert w REST API.

**Comment by anih** [comment]
A czy jest możliwość wylistowania nawet tych niepublicznych metod albo jakiegoś pliku swagger opisującego co tam się znajduje? Oczywiście bez gwarancji stabilności czy to że API nie zniknie za dzień czy dwa.

**Comment by AniaMalinowska** [comment]
Nie, nie ma takiej możliwości.

**Comment by DINK74** [comment]
@AniaMalinowska to chociaż usuńcie te metody z poradnika, bo widzę że nie jestem pierwszym userem który bezskutecznie poszukuje dokumentacji :-)

**Comment by AniaMalinowska** [comment]
Rozumiem :) i dziękuję za sugestię, niemniej jest to tylko przykładowa struktura.
Wszystkie metody, które udostępniamy do publicznego wykorzystania na REST API opisaliśmy w [dokumentacji](https://developer.allegro.pl/documentation/) na portalu developerskim.
