### ISSUE TITLE
RestAPI - adres dostawy

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1130]
W panelu allegro do zamówienia o id = 64bd5492-1e4f-11e9-b5eb-315ef70d5453 istnieje adres dostawy, natomiast jeśli chcę pobrać dane za pomocą metody GET /order/checkout-forms/64bd5492-1e4f-11e9-b5eb-315ef70d5453 to tam nie ma żadnego adresu dostawy. Dlaczego ?

**Comment by PawelTaberski** [comment]
Witam serdecznie sprawdziłem i rzeczywiście wygląda to dziwnie, sprawę przekazałem do sprawdzenia przez zespół, który odpowiada za te zasoby, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
@pietrach Dopiero teraz zauważyłem, że jest status "FILLED_IN" a nie "READY_FOR_PROCESSING", to w takim wypadku wszystko się zgadza, bo dopiero w statusie "READY_FOR_PROCESSING" zobaczysz adres dostawy jaki klient podał na FOD. Wszystko opisaliśmy w [naszym poradniku](https://developer.allegro.pl/orders/#01).

**Comment by pietrach** [comment]
A dlaczego w panelu Allegro jest pokazany ?

**Comment by PawelTaberski** [comment]
Są to dane na ten czas jaki podał user, w fod ale nie są to dane ostateczne i mogą ulec zmianie, ponadto user nie przeszedł pozytywnie jeszcze płatności tzn, towar nie jest jeszcze opłacony.
