### ISSUE TITLE
RestApi Zwrot Prowizji

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#1131]
Witam,
kiedy planowane jest udostępnienie metod dla zwrotu prowizji na RestApi?

**Comment by PawelTaberski** [comment]
Niestety nie mam jeszcze takich informacji, wiem że takie funkcjonalności są planowane do wdrożenia na REST API. Jak tylko będziemy znali konkretne daty to poinformujemy o tym w dedykowanym komunikacie.
