### ISSUE TITLE
problem z /sale/offers/{offerId}

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#1132]
Mam problem z /sale/offers/{offerId} - wiesza się.
Wygląda to tak:

pętla
  operacja1
  /sale/offers/{offerId}
  operacja2

operacja1 jest wykonana w bazie, operacja2 nie. Skrypt stoi w miejscu, przeglądarka mieli przez co najmniej kilka minut, potem ją zamykam. Czasami pętla wykona się 100 razy, czasem 500, czasem wszystkie 1200 obrotów, jest to niezależne od offerId.
Czy można to jakoś obsłużyć? Kodu błędu nie zwraca.

**Comment by PawelTaberski** [comment]
Sprawdziłem, i nie widzę po naszej stronie jakiegoś wzrostu błędów, przetestowałem sam zasób i odpowiedzi dochodzą w normalnym czasie. Potrzebowałbym od Ciebie informacji o konkretne trace-id z którymi masz problem.

**Comment by Mihalis76** [comment]
Dzięki! 
Trace-Id mogę pobrać tylko dla tych wywołań, które działają, np: Trace-Id: cf72bd8041f771e1.
Kiedy to się powiesi to nic nie zwraca.
Czy przyczyny problemu należy szukać po stronie serwera?

**Comment by pietrach** [comment]
Bardzo podobne zachowanie jak w przypadku #1121. Nawet dokładnie to samo tylko, że u mnie dzieje się to w przypadku pobierania zamówień

**Comment by PawelTaberski** [comment]
@Mihalis76 Wygląda podobnie, ale w Twoim wypadku wydaje mi się, ze problem jest z nagłówkami, czy masz, nagłówki accept i content-type o wartości application/vnd.allegro.public.v1+json

**Comment by Mihalis76** [comment]
nagłówek dla tej metody wygląda tak:

        $headers = array(
            "Authorization: Bearer $token",
            "Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );

To jest pętla
do {
  operacja1
  /sale/offers/{offerId}
  operacja2
  }
while ();

Tak, na oko wiesza się średnio raz na 1000 razy. 999 razy jest OK.

**Comment by Mihalis76** [comment]
Doprecyzuję. Chodzi o GET /sale/offers/{offerId}

**Comment by Mihalis76** [comment]
Nie próbowałem.

**Comment by pietrach** [comment]
@Michalis76 jak uda Ci się rozwiązać problem to napisz co zrobiłeś bo do tej pory ja u siebie nie rozwiązałem. Najprawdopodobniej wina leży po stronie serwera

**Comment by Mihalis76** [comment]
@PawelTaberski 
U mnie też praktycznie wszystkie kończą się poprawnie.

Spróbowałem na innym serwerze i póki co działa, nie zawiesiło się ani razu. Większy test będzie można zrobić dopiero wtedy, kiedy człowiek mający dostęp do konta allegro zarejestruje nowy adres.

Problem łatwo by się dało rozwiązać, gdyby działał timeout, tymczasem, mimo ustawienia:
ini_set('default_socket_timeout', 30);
albo
$options = array(
    'http' => array(
    'method' => $method,
    'header' => implode("\r\n", $headers),
    'content' => $data,
    'ignore_errors' => true,
    'timeout' => 30  
    )
);
$context = stream_context_create($options);
return file_get_contents($url, false, $context);

Wiesza się i wisi przez kilkanaście minut (w webapi ta funkcja trwała 2-3 minuty). Po tym czasie zamykam przeglądarkę. Rozumiem że ten timeout to także kwestia serwera?

**Comment by Mihalis76** [comment]
@pietrach 
Oczywiście, dam znać.
Dziwi mnie to, że u Ciebie nie działa na home.pl, u mnie na domeny.pl.
Działa z kolei na klatka.pl.
Ja nie używam curla i nie działa mi timeout -  w tym konkretnym przypadku.

**Comment by Mihalis76** [comment]
Pomogła zmiana php z 5.4 na 5.6. 
Pomogła w tym sensie że zaczęły działać timeouty. Pobieranie danych bez zmian.
Na tą chwilę mi to wystarczy.
