### ISSUE TITLE
Duplikaty eventów

### ISSUE THREAD

**Issue by ifiszu** [allegro/allegro-api#1133]
Podczas pobierania eventów, które sortowane są od najstarszych do najnowszych, dwa ostatnie z nich, to duplikaty eventów z zamówienia sprzed tygodnia. Z czego to wynika? Skrypt wyłapuje mi najnowsze eventy ze statusem READY_FOR_PROCESSING, i ten, zduplikowany (drugi to FILLED_IN), łapie się w kryteria.

**Comment by PawelTaberski** [comment]
Nie wiem jak masz ustawione te kryteria, jednakże czasem zdarza się, że późniejsze zdarzenie w dzienniku pojawi się niezgodnie z kolejnością, np najpierw w dzienniku pojawi się READY_FOR_PROCESSING a potem FILLED IN. Są to bardzo rzadkie przypadki, ale zdarzają się, jeśli są to ewidentne duplikaty i 2 razy otrzymałeś dokładnie te same dane podeślij je proszę, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1133 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Sprawdziłem dane jakie podesłałeś i wygląda to dziwnie bo nawet czas wystąpienia jest identyczny, a id-ki są różne. Sprawę przekazałem do zespołu, który odpowiada za te zasoby, jak tylko będę miał jakieś konkretne informacje to dam znać.

**Comment by ifiszu** [comment]
Cześć, czy coś udało się ustalić?

**Comment by PawelTaberski** [comment]
Jeszcze badamy temat proszę o jeszcze trochę cierpliwości.
