### ISSUE TITLE
offer-publication-commands - Nieczytelne komunikaty błędów

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#1134]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mimo wysłania nagłówka Accept-Language: pl-PL, komunikat błędu jest po angielsku z wysypanymi polskimi znakami.

```
REQUEST headers: Array
(
    [0] => Api-Key: [cyk]
    [1] => Accept-Language: pl-PL
    [2] => Accept: application/vnd.allegro.public.v1+json
    [3] => Content-Type: application/vnd.allegro.public.v1+json
    [4] => Authorization: Bearer [cyk]
)

RESPONSE: 
HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: fb624022f102d15f
Date: Wed, 30 Jan 2019 12:35:48 GMT
X-RateLimit-Remaining: 8852
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000

{"tasks":[{"offer":{"id":"[cyk]"},"message":"Could not change offer publication status. Missing required parameters: DÅugoÅ wkÅadki.","status":"FAIL","scheduledAt":"2019-01-30T13:31:07.134+01:00","finishedAt":"2019-01-30T13:34:15.133+01:00","field":"publication"}]}
```

**Comment by FromAnyHole** [comment]
A to tylko problem kodowania znaków (po każdej ze stron musi być UTF-8), ale może są i jakieś wyjątki...

**Comment by PawelTaberski** [comment]
@deneb-k Jakby rada @FromAnyHole nie pomogła daj znać, będziemy szukać dalej.

**Comment by deneb-k** [comment]
Dokładnie taką samą odpowiedź dostaję wykonując zapytanie w PHPStormie. To jedyna metoda, która zwraca mi krzaki, więc u mnie raczej wszystko jest OK. W dodatku zabawy z kodowaniem nie pomogą na komunikat po angielsku.

**Comment by PawelTaberski** [comment]
@deneb-k Przetestowałem jeszcze raz dwie wersje nagłówków:
-H 'accept-language: en-EN' \
-H 'accept-language: pl-PL' \
I w obu wypadkach dostaję prawidłową odpowiedź wraz z polskimi znakami np:
"userMessage": "Missing required parameters: Długość wkładki."
Także po naszej dane są zwracane poprawnie, musi być jakiś problem u Ciebie z kodowaniem polskich znaków.

**Comment by deneb-k** [comment]
userMessage to ja w ogóle nie dostaję. 

Ale chyba zamieszanie wprowadziłem tytułem - chodzi o 
/sale/offer-publication-commands/{commandId}/tasks, czyli sprawdzanie wyniku aktywacji.

![image](https://user-images.githubusercontent.com/45093789/52040639-6090a800-2538-11e9-8ddd-50776f3e62b7.png)

**Comment by PawelTaberski** [comment]
@deneb-k A to zmienia postać rzeczy :-) sprawdziłem i u siebie też nie mam polskich znaków, sprawę zgłosiłem do zespołu odpowiedzialnego za te zasoby, prośba o cierpliwość.

**Comment by FromAnyHole** [comment]
... i co tam ustalono ??

**Comment by PawelTaberski** [comment]
Komunikat zostanie poprawiony, sprawę przekazałem do zespołu odpowiedzialnego za tą funkcjonalność i się tym zajmą. Proszę o jeszcze trochę cierpliwości.
