### ISSUE TITLE
Błąd w /users/{userId}/ratings-summary

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1136]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Sprzedający nie posiada ratings-summary.

https://allegro.pl/uzytkownik/42538884/oceny

**Comment by kfijalko** [comment]
to samo:
55670929
55858155
45509022

**Comment by PawelTaberski** [comment]
@kfijalko Widzę, że to się zgadza, bo nawet przez front userzy o takich id nie mają ocen od kupujących.

**Comment by kfijalko** [comment]
Konto od 3 lat na allegro, 66k ofert i nie ma żadnej oceny?

**Comment by PawelTaberski** [comment]
@kfijalko O którym dokładnie id-ku mówisz może jest jakiś problem nie tyle w API co już w samej usłudze, daj znać o którym koncie mówisz, zgłoszę prośbę o zbadanie tej sprawy, bo po stronie API jest poprawnie.

**Comment by kfijalko** [comment]
Zerknijcie na pierwszy, ale w zasadzie oprogramowałem możliwość braku ratings-summary. Przyjmuje, że to nie jest błąd.

**Comment by PawelTaberski** [comment]
@kfijalko Zlecę zweryfikowanie, czy dane na pewno są zbierane prawidłowo 👍

**Comment by PawelTaberski** [comment]
@kfijalko Sprawdziliśmy i dane są poprawne, jeden z tych sprzedawców ma już 1 ocenę wystawioną wczoraj.

**Comment by kfijalko** [comment]
ok, pozdrawiam
