### ISSUE TITLE
PUT /sale/offers/{offerId} zwraca 400

### ISSUE THREAD

**Issue by pgorka** [allegro/allegro-api#1138]
Występuje problem: 
 - [X] z zasobem REST API
 
:beetle: **Opis**
Przy próbie update'u draftu oferty używając załączonego JSONa (problematyczny JSON.txt)
dostaję zwrotkę 400:
{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offers/6206148050",
            "userMessage": null
        }
    ]
}

JSON podobny do tego z aukcji wystawionej przez Web (poprawny JSON.txt):

URI: https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206148050
header("Accept", "application/vnd.allegro.public.v1+json")
header("Authorization", token)
header("content-type",  "application/vnd.allegro.public.v1+json")

Token jest poprawny.
[poprawny JSON.txt](https://github.com/allegro/allegro-api/files/2817461/poprawny.JSON.txt)
[problematyczny JSON.txt](https://github.com/allegro/allegro-api/files/2817462/problematyczny.JSON.txt)

**Comment by PawelTaberski** [comment]
Z tego co widzę w przypadku problematycznego JSON-a problem nie jest w JSON-ie, a w samym opisie oferty i powinieneś otrzymywać status 422. M.in. nasz zamknięcie pogrubienia bez rozpoczęcia i tak samo zaczyna się druga lista a brak jej otwarcia.

**Comment by pgorka** [comment]
Poprawiłem, nadal 400.

Dodatkowo pytanie - czy to normalne, że zasób https://upload.allegro.pl.allegrosandbox.pl/sale/images zwraca jeden URI dla dwóch wysłanych zdjęć? Być może tu jest problem?
[poprawiony JSON.txt](https://github.com/allegro/allegro-api/files/2817615/poprawiony.JSON.txt)

**Comment by PawelTaberski** [comment]
@pgorka Tak, to najprawdopodobniej będzie to, powinieneś przesyłać zdjęcia pojedynczo, zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/#step-3-images).

**Comment by pgorka** [comment]
@PawelTaberski niestety, to nie to - poprawiłem linki (każdy przesłany osobno):
    {
      "url": "https://a.allegroimg.allegrosandbox.pl/original/119a4b/73b1ed5746e6a31ba3f6efa81c01"
    },
    {
      "url": "https://a.allegroimg.allegrosandbox.pl/original/11d8d5/01e4633e460bb417f09462eae50c"
    }
I nadal w zwrotce dostaję 400.
@up w poradniku nie ma informacji żeby przesyłać pliki pojedynczo, poza tym utworzony link poprawnie otwiera pierwszy przesłany obrazek

**Comment by PawelTaberski** [comment]
@pgorka Czy czasem przed wysłaniem requesta gdzieś nie dodajesz jakiegoś znaku, przecinka cokolwiek?
Bo przekopiowałem całe Twoje body zmieniając cennnik itp i normalnie wszystko przechodzi bez problemu.

**Comment by pgorka** [comment]
@PawelTaberski ciężko powiedzieć, bo JSON wychodzi nieposortowany
[json z requestu.txt](https://github.com/allegro/allegro-api/files/2820894/json.z.requestu.txt)

**Comment by pgorka** [comment]
Teraz widzę że w headerze dodaje mi charset=ISO-8859-1 - to może być to ?

**Comment by pgorka** [comment]
Pomogła zmiana .header("content-type",  "application/vnd.allegro.public.v1+json;charset=UTF-8")
