### ISSUE TITLE
Pole "unit" w parametrach kategorii

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#1139]
Na zasobie /sale/categories/{categoryId}/parameters w odpowiedzi jest pole "unit". Tylko nie zawsze jest ono uzupełnione. Rozumiem że przy parametrach słownikowych mija się to z celem ale dla wartości int czy float jest pomocne. 
Za przykład posłużę się kategorią o id 252276. Tylko waga ma wpisaną jednostkę. 
Oczywiście można posłużyć się nazwą parametru, no ale po coś to pole jest

**Comment by AssAssIn1909** [comment]
hmm, ciekawe
u mnie to wygląda troche inaczej 
```
{
   "id": "128678",
   "name": "Moc [kW]",
   "type": "float",
   "required": true,
   "unit": null,
   "options":
   {
      "variantsAllowed": true,
      "variantsEqual": false
   },
   "restrictions":
   {
      "min": 0,
      "max": 1000,
      "range": false,
      "precision": 2
   }
},
{
   "id": "128674",
   "name": "Pojemność zbiornika [l]",
   "type": "float",
   "required": true,
   "unit": null,
   "options":
   {
      "variantsAllowed": true,
      "variantsEqual": false
   },
   "restrictions":
   {
      "min": 0,
      "max": 1000,
      "range": false,
      "precision": 2
   }
},
```

**Comment by PawelTaberski** [comment]
@AssAssIn1909 Już wiem w czym ta rozbieżność ja sprawdzałem na produkcji, a ty działasz na środowisku testowym i widocznie jest na nim starsza wersja parametrów, zgłosiłem prośbę o ich odświeżenie.

**Comment by AssAssIn1909** [comment]
Miałem właśnie dopisać że to na developerskim. A na produkcyjnym nie sprawdzałem

**Comment by AssAssIn1909** [comment]
Jak duże są różnice między środowiskiem testowym a produkcyjnym? Bo dziś rano stwierdziłem, że skoro na prodzie są jednostki to sobie pobiorę. Tylko mój program zaczął wywalać błędy. Wyszło na to, że kategorie które chce pobrać nie istnieją na prodzie (19035). To też nie zostało odświeżone?

**Comment by PawelTaberski** [comment]
@AssAssIn1909 Zleciłem odświeżenie całego drzewa, drzewo na produkcji zmienia się praktycznie nawet 2 razy dziennie, na sandboxie nie wiem jak często jest aktualizowane ale raczej jest to kilka razy w tygodniu.

**Comment by AssAssIn1909** [comment]
Rozumie. A czy takie zmiany są gdzieś dokumentowane? 
W senie , że na przykład 
Kategoria (19035) "Motoryzacja - Części i akcesoria motocyklowe - Części motocyklowe - Silniki i osprzęt - Chłodnice" została przeniesiona na 
Kategorie (260443)  "Motoryzacja - Części i akcesoria motocyklowe - Części motocyklowe - Układ chłodzenia - Chłodnice"
Ja nie potrzebuje całego drzewka dlatego takie coś przyśpieszyło by wprowadzanie ewentualnych zmian

**Comment by PawelTaberski** [comment]
Nie nigdzie nie publikujemy takich zmian.

**Comment by AssAssIn1909** [comment]
Wiadomo może kiedy nastąpi odświeżenie drzewa na sandboxie?
W sumie dobrym pomysłem byłoby odświeżanie go chociaż raz w tygodniu albo raz na 2 tygodnie, żeby był w miarę spójny z produkcyjnym.

**Comment by PawelTaberski** [comment]
Zgłosiłem prośbę o automatyczne odświeżanie w określonych odstępach czasu, i przypomniałem się z prośba o pilne odświeżenie. Proszę o jeszcze trochę cierpliwości.
