### ISSUE TITLE
[REST]Access_token przez 365 dni? Stworzenie nowej aukcji?

### ISSUE THREAD

**Issue by hannibalpl** [allegro/allegro-api#114]
Cześć, 
na wstępie określę, że jestem mega początkującym programistą, staram się po prostu zrobić szybkie wstawianie ofert na allegro(i później inne serwisy). Pytania:
1/
Zacząłem kodzić w PHP RESTie, na razie uzyskuję przez RESTa access_token i refresh_token. Chciałbym aby php działał całkowicie bez użytkownika. O ile z waszej dokumentacji wynika, że access_token jest ważny 12h, o tyle chciałbym się dopytać o refresh_tokena. 
Cyt. z waszego tutka REST:

> (...)Token taki jest jednorazowego użytku, a po jego użyciu wygenerowany zostaje nowy token dostępowy **(ważny kolejne 12h)** i nowy refresh token.
Ważność refresh tokena nie ulega przedłużeniu - niezależnie od liczby wygenerowanych tokenów dostępowych na podstawie kolejnych refresh tokenów, autoryzację użytkownika dla aplikacji można przedłużyć do maksymalnie 365 dni od momentu wygenerowania pierwszego tokena. (...)

Czy planujecie stworzyć opcję umożliwiającą stworzenie tokena ważnego nie 12h tylko 365 dni?

2/ Czy uzyskując ww. access_token mogę stworzyć nową aukcję? Bo z tego co ostatecznie doczytałem w waszej dokumentacji potrzebuję metody doLogin, i właściwie wszystkiego co jest osadzone w WebAPI, ergo cała moja robota jest nieważna... Chyba że nie doczytałem i jest możliwość zrobienia w REST nowej aukcji Kup Teraz, wspomagając się tokenem.

**Comment by AniaMalinowska** [comment]
1/ Nie mamy takich planów.
2/ Niedługo udostępnimy możliwość tworzenia ofert przez REST API. Poinformujemy o tym na githubie oraz [portalu developerskim](https://developer.allegro.pl/news/).

**Comment by hannibalpl** [comment]
A mógłbym jeszcze prosić o małą pomoc? Ja w tym momencie ogłupiałem. Powiedzmy że mamy kod (z waszej strony głównie), chciałbym zwykłe zapytanie zrobić z logowaniem:
(...)
parent::__construct('https://webapi.allegro.pl/uploader.php?wsdl');
(...)
$request = [
	'userLogin' => WEBAPI_USER_LOGIN,
	'userHashPassword' => WEBAPI_USER_ENCODED_PASSWORD,
	'countryCode' => COUNTRY_CODE,
	'webapiKey' => WEBAPI_KEY,
	'localVersion' => $versionKeys[COUNTRY_CODE]->verKey,
];
$session = $soapClient->doLoginEnc($request);
(...)

Gdzie ja robię błąd że nie czyta mi w ogóle tej tablicy $request?
Plus jak później mogę poszczególne składniki $session wyświetlić na ekranie?
Przy manualnym wprowadzaniu danych, $session = $soapClient->doLoginEnc(dane, dane, dane); działa
