### ISSUE TITLE
Błędy przy edycji  zasobem /sale/offers/ metodą PUT 

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#1140]
Występuje problem: 
 - [X] z zasobem REST API
 
Próba edycji aukcji zasobem jak w tytule zwraca błędy odmowy  edycji z uwagi na brak obowiązkowych parametrów (wklejone poniżej)
Tymczasem w panelu administracyjnym konta Allegro jest informacja : 
Nie masz ofert w kategoriach, w których są do uzupełnienia parametry obowiązkowe.

to prowadzi do istotnego konfliktu , między mną (programistą) a właścicielem konta , bo ten wychodzi z błędnego założenia , że Allegro jest wspaniałe i nieomylne Kto ma wyprowadzić klienta z błędu ?

poniżej lista błędów zwróconych przez  metodę przy braku informacji w panelu o nie zdefiniowanych parametrach

7515162320{"errors":[{"code":"VALIDATION_ERROR","message":"","details":"","path":"compatibilityList","userMessage":"rawItems: Please do not use forbidden words: marka."}]}
7503040602{"errors":[{"code":"VALIDATION_ERROR","message":"","details":"","path":"compatibilityList","userMessage":"rawItems: Please do not use forbidden words: marka."}]}
7245807292{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7028809591{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Liczba sztuk.","details":"","path":"","userMessage":"Missing required parameters: Liczba sztuk."}]}
6906354516{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
6905915239{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Producent czÄĹci.","details":"","path":"","userMessage":"Missing required parameters: Producent czÄĹci."}]}
6864773011{"errors":[{"code":"VALIDATION_ERROR","message":"","details":"","path":"compatibilityList","userMessage":"rawItems: Please do not use forbidden words: marka."}]}
6781763855{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj filtra powietrza.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj filtra powietrza."}]}
6114078957{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Marka, Rodzaje odtwarzanych noĹnikĂłw, Radio, Komunikacja, MontaĹź.","details":"","path":"","userMessage":"Missing required parameters: Marka, Rodzaje odtwarzanych noĹnikĂłw, Radio, Komunikacja, MontaĹź."}]}
5586984110{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7352280765{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7352244743{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7316546127{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7264251957{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7260604284{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7260585261{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7251143305{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7224305488{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7224198384{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7195483416{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Stan.","details":"","path":"","userMessage":"Missing required parameters: Stan."}]}
7164255964{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7153307883{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7047292151{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7035923772{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7034027348{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
7014287764{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
6993555854{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
6965244422{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
6964545151{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}
5692193339{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Rodzaj zawieszenia.","details":"","path":"","userMessage":"Missing required parameters: Rodzaj zawieszenia."}]}

**Comment by PawelTaberski** [comment]
@11mszot Uwagi dotyczące tego narzędzia zgłoś przez formularz kontaktowy, tutaj zajmujemy się tylko API. 
Jednakże z tego co widzę dużo wrzuciłeś tutaj błędów których te narzędzie nie obsługuje jak np. zakazane słowa, liczba sztuk itd.
Natomiast wszystkie oferty w których brak obowiązkowych parametrów (Missing required parameters) są już zakończone nie są aktywne.

**Comment by 11mszot** [comment]
Jakie to ma znaczenie że nie są aktywne ?  Metoda PUT na zasobie /sale/offers zgodnie z dokumentacją pozwala edytować także oferty ze statusem ENDED
Temat jest we właściwym miejscem , bo  skoro metoda API zwraca informacje inne niż Frontend Allegro , to osoby odpowiedzialne za Api w Allegro powinni uzgodnić z tymi od frontendu  gdzie występuje problem , a nie odbijać piłeczkę

**Comment by PawelTaberski** [comment]
@11mszot Oczywiście tym zasobem możesz edytować i zakończone i aktywne, a nawet drafty, ale to narzędzie do uzupełniania na froncie jest tylko do aktywnych ofert i tylko do parametrów obowiązkowych, także wszystko jest ok.
