### ISSUE TITLE
Metoda WebAPI doAddPackageInfoToPostBuyForm => parametr transactionId

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1141]
Czy za pomocą metody RestAPI **GET /order/line-item-id-mappings** gdy jako parametr przekaże lineItemId to otrzymam dealId. Czy ten dealId przekazuje jako transactionId w metodzie doAddPackageInfoToPostBuyForm ? Jeśli nie to w jaki sposób mogę wysłać nr przesyłki do Allegro ściągając zamówienia za pomocą RestAPI.

**Comment by PawelTaberski** [comment]
Przykład wykorzystania zasobu do mapowania znajdziesz w [naszych aktualnościach](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/). Jednakże w metodzie 
[doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744) powinieneś dodać transactionId, który pobierzesz przy pomocy metody [doGetTransactionsIDs](https://allegro.pl/webapi/documentation.php/show/id,121). Pracujemy nad zasobem do dodawania numerów przesyłek w REST API powinna pojawić się już w lutym.

**Comment by pietrach** [comment]
W lutym ale mniej więcej, którego lutego ?

**Comment by PawelTaberski** [comment]
@pietrach Oj niestety dokładnej daty nawet tygodnia nie znam, jak tylko będę miał konkretne dane to damy dedykowany komunikat.
