### ISSUE TITLE
Brak informacji o limitach w np https://api.allegro.pl/sale/offer-variants

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1142]
Brakuje informacji jaka jest maksymalna wartość `limit` pewnie nie tylko w `https://api.allegro.pl/sale/offer-variants`

`In [12]: response.text
Out[12]: '{"errors":[{"code":"VALIDATION_ERROR","message":"must be less than or equal to 50","details":"Invalid value: 100","path":"getVariantSets.limit","userMessage":"must be less than or equal to 50"}]}'
`

**Comment by FromAnyHole** [comment]
Ejno, przecież masz - sam podałeś ! ;-)

**Comment by PawelTaberski** [comment]
@anih Zachęcam do zapoznania się z [naszymi poradnikami](https://developer.allegro.pl/multi_variant_offers/#6) znajdziesz tam m.in. informacje o zakresie limitu, który otrzymałeś również w responsie.
