### ISSUE TITLE
[REST API] Jak sprawdzić czy oferta trafiła do archiwum

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1143]
GET na /sale/offers/{id} w przypadku zakończonej aukcji:    

```
[...]
'publication' => array(
                'duration' => null,
                'status' => 'ENDED',
                'startingAt' => null,
                'endingAt' => null
),
...
```
Czy to wygląda tak samo dla oferty zarchiwizowanej? 
Istnieje jakaś opcja sprawdzenia czy ofertę można jeszcze wznawiać/edytować przed próbą wykonania tej operacji?

**Comment by PawelTaberski** [comment]
Nie, dopiero otrzymasz szczegółowe informacje, czy udało się wystawić daną ofertę, bądź nie w GET /sale/offer-publication-commands/{commandId}/tasks i tam również znajdziesz informacje dlaczego nie udało się wystawić danej oferty.

**Comment by Sojtin** [comment]
Planujecie coś zmienić w tym aspekcie? Jeśli nie nowy status to chociaż w publication->endingAt podawać datę do której oferta pozostanie jeszcze do wznowienia/edycji, później null. Strasznie się to wydaje nie optymalne :/ PUT sale/offers/{id} co mi zwróci jeśli będę próbował edytować ofertę z archiwum? Jakiś inny status dla takiego błędu czy też trzeba sprawdzać error message żeby wiedzieć czy edycja nie przeszła bo oferta jest w archiwum czy z jakiegoś innego powodu?

**Comment by PawelTaberski** [comment]
Przy PUT otrzymasz komunikat:
```
{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "You cannot change an archived offer.",
            "details": "",
            "path": "",
            "userMessage": "You cannot change an archived offer."
        }
    ]
}
```
Jednakże nie pobierzesz numeru oferty z archiwum przy pomocy zasobu GET /sale/offers czyli wśród ofert sprzedawcy. Także takie numery możesz mieć tylko zapisane w systemie. Przez front sprzedawca też nie widzi w swoich ofertach archiwalnych.
