### ISSUE TITLE
operatorId dla "Allegro Poczta Polska Odbiór w Punkcie"

### ISSUE THREAD

**Issue by szymon-convertis** [allegro/allegro-api#1145]
Dzień dobry,
proszę o informację, jaki operatorId  powinien zostać przesłany  metodą doAddPackageInfoToPostBuyForm dla formy przesyłki "Allegro Poczta Polska Odbiór w Punkcie". 
W dokumentacji są osobne ID:
6 - Poczta Polska
15 - Pocztex
a nie znalazłem nigdzie jednoznacznej informacji, który ID powinien być użyty dla odbioru w punkcie.

**Comment by PawelTaberski** [comment]
Pocztex odnosi się do przesyłek kurierskich, także w tym przypadku Poczta-Polska

**Comment by szymon-convertis** [comment]
Dziękuję
