### ISSUE TITLE
Brak danych do faktury w WEBAPI.

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#1146]
Ostatnio już drugi raz dane do faktury nie zostały przekazane przez WebAPI.
Proszę o naprawienie tej usterki. 
Dodatkowo w jednym mailu dane są, w drugim nie ma.
Tutaj nie ma:
Allegro Finanse - Kupujący xxx wybrał sposób zapłaty i dostawy w ofercie (7736341705) 
Tutaj są:
Nowa wpłata od Kupującego xxx

**Comment by MartaNowaczyk** [comment]
@kris86k Dziękujemy za zgłoszenie. Wiemy już o tym problemie i pracujemy nad jego rozwiązaniem.

**Comment by kris86k** [comment]
OK, radzę przyśpieszyć z pracami bo niedługo wchodzą przepisy uniemożliwiające wystawienie faktury do paragonu!
