### ISSUE TITLE
GET /sale/shipping-rates zwraca błąd w "path"

### ISSUE THREAD

**Issue by lewekleonek** [allegro/allegro-api#1148]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
cURL request:
curl -X GET \
  https://api.allegro.pl/sale/shipping-rates \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: Bearer ey*******' \
  -H 'Postman-Token: 10cb89e6-8b0a-4881-be69-4b1ce148c0a0' \
  -H 'cache-control: no-cache'

Response:

Headers:
Expires →0
Cache-Control →no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection →1; mode=block
Pragma →no-cache
X-Frame-Options →DENY
Trace-Id →af46abd3c791bce3
X-RateLimit-Remaining →8999
X-RateLimit-Limit →9000
Date →Wed, 06 Feb 2019 10:10:36 GMT
X-Content-Type-Options →nosniff
Content-Length →230
Content-Type →application/json

Body:
{"errors":[{"code":"ConstraintViolationException","message":"An error has occurred","details":null,"path":"PublicShippingRatesResource$$EnhancerBySpringCGLIB$$88edb76c.getList.arg0","userMessage":"Transferred data is incorrect"}]}

Trace-Id →af46abd3c791bce3

Zasób /sale/shipping-rates zwraca błąd zamiast listy cenników dostaw dla użytkownika.

**Comment by MartaNowaczyk** [comment]
@lewekleonek udało mi się powtórzyć błąd. Sprawdzamy co jest przyczną.

**Comment by MartaNowaczyk** [comment]
@lewekleonek już widzę, to nie jest błąd. Nie podałeś seller.id. Poprawne wywołanie GET:

https://api.allegro.pl/sale/shipping-rates?seller.id={Seller_ID}

**Comment by lewekleonek** [comment]
Dzięki.
Nawet czerwona gwiazdka z "required" mi nie pomogła.

**Comment by KrzychuWalek** [comment]
Jak pobrać id cennika dostaw, jeżeli był zdefinowany poprzez stronę ?

**Comment by KrzychuWalek** [comment]
Próbuję wysłać:
https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=a7b3bb5b-329a-4d82-a853-8270c2895a26` i otrzymuję:

403 Forbidden

identyfikator a7b3bb5b-329a-4d82-a853-8270c2895a26 odczytałem z ręcznie wystawianej sprzedaży na mym koncie.

https://api.allegro.pl.allegrosandbox.pl/'account/additional-emails' otrzymuję prawidłowa odpowiedź
