### ISSUE TITLE
[PUT] /sale/offers/{offerId} zwraca 406

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#1149]
Zapytanie PUT na w/w zasób zwraca 406. Nagłówki poprawne: application/vnd.allegro.public.v1+json. 

```
var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://api.allegro.pl/sale/offers/"+id+"");
            httpWebRequest.ContentType = "application/vnd.allegro.public.v1+json";
            httpWebRequest.Accept = "application/vnd.allegro.public.v1+json";
            httpWebRequest.Method = "PUT";
            httpWebRequest.Headers.Add("Authorization", "Bearer " + Token + "");
```
Dla jednych produktów zwraca 406, inne publikuje poprawnie. W czym może leżeć problem?

**Comment by MartaNowaczyk** [comment]
@ponowemu Jesteś pewny, że za każdym razem przekazujesz poprawne nagłówki?  Dla tych samych danych raz masz 406, a raz status 200 OK?

**Comment by ponowemu** [comment]
@MartaNowaczyk Tak jest. Nagłówki zawsze są stałe dynamicznie generowany jest tylko Json z modelu.

**Comment by ponowemu** [comment]
Poniżej przesyłam dwa dynamicznie wygenerowane Json'y. Jeden przechodzi i zwraca 200, drugi 406. 
[incorrect.txt](https://github.com/allegro/allegro-api/files/2836283/incorrect.txt)
[correct.txt](https://github.com/allegro/allegro-api/files/2836284/correct.txt)

**Comment by MartaNowaczyk** [comment]
@ponowemu to dziwna sytuacja. W przypadku błednego statusu podeślij pełnego requesta i trace-id z nagłówka.

**Comment by ponowemu** [comment]
Błąd spowodowany przesyłaniem compatibilityList. Czemu więc możliwość przesyłania listy pasuje do nie działa? Po wrzuceniu pustej tablicy do compatibilityList wszystko przechodzi dobrze. Format zgodny z wymogami.
```
\"compatibilityList\": {
    \"items\": [
      {
        \"text\": \"sss\"
      },
      {
        \"text\": \"sss\"
      }
    ]
  },
```

**Comment by ponowemu** [comment]
@PawelTaberski Dzięki za informację. W takim razie czekamy.

**Comment by PawelTaberski** [comment]
@ponowemu Problem nie powinien już występować.

**Comment by ponowemu** [comment]
@PawelTaberski Teraz wszystko jest ok.
