### ISSUE TITLE
REST API problem - wiele kont

### ISSUE THREAD

**Issue by SoftSolid** [allegro/allegro-api#115]
Jest problem z przełączaniem się miedzy kontami.
Jeśli aplikacja obsługuje kilka różnych kont allegro to np. zmiana cena a aukcjach jest możliwa tylko dla konta które aktualnie jest zalogowane https://apps.developer.allegro.pl
Próba zmiany ceny na innym koncie skutkuje pojawieniem się FORBIDDEN.
Kiedy zostanie to poprawione ?

**Comment by TimothyKoval** [comment]
> zmiana cena a aukcjach jest możliwa tylko dla konta które aktualnie jest zalogowane

A gdzie tu jest błąd? Co tu naprawiać?

**Comment by SoftSolid** [comment]
To jest źle, że jak chcę zrobić zmianę cen na drugim koncie przy aukcji która jest z drugiego konta to mam FORBBIDEN. Mimo, że łączę się z REST  API z danymi z drugiego konta.

**Comment by SoftSolid** [comment]
Zróbcie możliwość WYLOGOWANIA się przez REST API.

**Comment by TimothyKoval** [comment]
To znaczy że używasz tokena i/lub klucza z jednego konta w celu przeprowadzenia operacji na drugim. Po kiego grzyba chcesz się wylogowywać? Po prostu przestań używać nieaktualnych poświadczeń, lub lepiej - trzymaj zestaw klucz/token dla każdego konta i korzystaj z nich w razie potrzeby

**Comment by SoftSolid** [comment]
Mam zestaw kluczy dla każdego konta oraz aktualne tokeny.
I używam prawidłowych danych podczas komunikacji.
Czy próbowałeś zmieniać cenę przez REST API najpierw w aukcji na jednym koncie allegro a następnie na innym koncie allegro w innej aukcji ?
W zależności od tego na którym koncie się ostatnio autoryzowałeś przez oauth tam Ci się uda zmienieć cenę a na tym drugim nie.

**Comment by TimothyKoval** [comment]
Tak, robię to 24/7 na kilkudziesięciu kontach

**Comment by TimothyKoval** [comment]
Zrób jakiegoś trace-a swojego klienta REST. Nie wiem z jakiego języka korzystasz, może np. używasz tego samego obiektu do komunikacji z różnymi kontami - spróbuj utworzyć osobną instancję obiektu (klasy) dla każdego klienta.

**Comment by SoftSolid** [comment]
W takim razie może ja coś źle robię. Za każdym razem tworzę nowy obiekt połączenia z REST API mimo tego mam właśnie taki efekt o jakim piszę. Aplikacja jest napisana w PHP.
Wydaje mi się, że w tym wątku https://github.com/allegro/allegro-api/issues/93 kolega ma ten sam problem.
https://github.com/allegro/allegro-api/issues/89 i tym też mi się wydaje jest ten sam problem.
Spróbuję jeszcze raz zrobić testy.

**Comment by TimothyKoval** [comment]
Prześlij kod - zobaczymy

**Comment by kormichu** [comment]
Nie próbujesz czasem ustawić nagłówka Authorization za każdym razem bez wcześniejszego jego wyczyszczenia ? Możesz mieć wiele nagłówków z taką samą nazwą, a serwer Allegro parsuje pewnie tylko pierwszy. Zrób sobie zrzut request / response

**Comment by SoftSolid** [comment]
kormichu dziękuję za sugestię. Sprawdzę to  dziś.

**Comment by SoftSolid** [comment]
Podaję taki header
Array
(
    [0] => Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjM0MDg3NzYsInVzZXJfbmFtZSI6IjQzOTU1Nzg2IiwianRpIjoiMWJjNjljM2QtMTQ2NC00NWEyLWFlNGItNGNlMDBiMWI3MTJkIiwiY2xpZW50X2lkIjoiNmExMDUzMzYtNmM5Yy00MTBjLTg1M2QtYWQ4MTc2ZmJhODQzIiwic2NvcGUiOlsiYWxsZWdyb19hcGkiXX0.TljMdfByjZvaYMHYugzd9xRvBA7nxs5aA82lI35Qy0oJaRj9MSaIBLnaAF0SmXOLZ-cfwiDOGXA1Wj45h-Xot53OlBmJYxOPMxIJgKj11pqEuXEGHxXHkHJQJVGIrynNeW2qUi3L9toux49EQKsoAGC_InYtx_ouJlt5EJGZwvI6DrX4sx48Z2RRCI1yIuT2irtnrHApgPOq-s4e-bgvPkhiORSYzKV0W7HaVc__FOA7BPXxXJ--BwunUuA9I554Hv5i1HxEmg5gnDcQFX4bFJTNXqk8q3iDm9bzYy1MHGD3JXfRHWhGNHBKW86X7rjGR6-7VSMIua1Q2vje7g9QCQ
    [1] => Api-Key: eyJjbGllbnRJZCI6IjZhMTA1MzM2LTZjOWMtNDEwYy04NTNkLWFkODE3NmZiYTg0MyJ9.p0dWgbWgRrixsTn61E9-URhe4flYF0Vp4rwaexmabso=
    [2] => Content-Type: application/vnd.allegro.public.v1+json
    [3] => Accept: application/vnd.allegro.public.v1+json
)

I dostaję Forbidden
file_get_contents(https://api.allegro.pl.allegrosandbox.pl/offers/6203937495/change-price-commands/526941ed-51a7-4124-b4d4-c2c4db2e99c4/): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden

Dla innego konta i innej aukcji wszystko działa bez problemu.
Token jest ważny sprawdzałem timestamp.

**Comment by TimothyKoval** [comment]
Co podajesz w post-ie?

**Comment by SoftSolid** [comment]
Próbuję metodą PUT zmienić cenę na aukcji. 

[http] => Array
        (
            [method] => PUT
            [header] => Expires: 0
Pragma: no-cache
Cache-Control: no-cache,no-store,max-age=0,s-maxage=0,must-revalidate
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MjM0MDg3NzYsInVzZXJfbmFtZSI6IjQzOTU1Nzg2IiwianRpIjoiMWJjNjljM2QtMTQ2NC00NWEyLWFlNGItNGNlMDBiMWI3MTJkIiwiY2xpZW50X2lkIjoiNmExMDUzMzYtNmM5Yy00MTBjLTg1M2QtYWQ4MTc2ZmJhODQzIiwic2NvcGUiOlsiYWxsZWdyb19hcGkiXX0.TljMdfByjZvaYMHYugzd9xRvBA7nxs5aA82lI35Qy0oJaRj9MSaIBLnaAF0SmXOLZ-cfwiDOGXA1Wj45h-Xot53OlBmJYxOPMxIJgKj11pqEuXEGHxXHkHJQJVGIrynNeW2qUi3L9toux49EQKsoAGC_InYtx_ouJlt5EJGZwvI6DrX4sx48Z2RRCI1yIuT2irtnrHApgPOq-s4e-bgvPkhiORSYzKV0W7HaVc__FOA7BPXxXJ--BwunUuA9I554Hv5i1HxEmg5gnDcQFX4bFJTNXqk8q3iDm9bzYy1MHGD3JXfRHWhGNHBKW86X7rjGR6-7VSMIua1Q2vje7g9QCQ
Api-Key: eyJjbGllbnRJZCI6IjZhMTA1MzM2LTZjOWMtNDEwYy04NTNkLWFkODE3NmZiYTg0MyJ9.p0dWgbWgRrixsTn61E9-URhe4flYF0Vp4rwaexmabso=
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
            [content] => {"input":{"buyNowPrice":{"amount":"467.00","currency":"PLN"}}}
            [ignore_errors] => 
        )

**Comment by SoftSolid** [comment]
Mogę prosić o jakieś sugestie ?

**Comment by AniaMalinowska** [comment]
Tak jak pisał @TimothyKoval, token jest związany z konkretnym użytkownikiem. Czyli jeśli chcemy zmieniać ofertę sprzedawcy A, to musimy wysyłać token dla sprzedawcy A, a jak ofertę sprzedawcy B, to token dla sprzedawcy B.

Jeśli mimo wszystko problem nadal występuje, prosimy [podeślij](https://allegro.pl/pomoc/kontakt?appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) nam przykładowe wartości oraz ID ofert, które zmieniasz (w nagłówkach odpowiedzi jest nagłówek Trace-Id). Jeśli wyślesz info przez [formularz](https://allegro.pl/pomoc/kontakt?appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422), podaj tutaj numer Ticketa.

**Comment by AniaMalinowska** [comment]
Przepraszam, nie zauważyłam tego IDka. 
Zweryfikowaliśmy sprawę i nie zgadzają się IDki:
wysłany token jest wygenerowany dla użytkownika o ID z końcówką 86.
natomiast oferta należy do użytkownika o ID z końcówką 87.

**Comment by SoftSolid** [comment]
To, że mam źle wygenerowane tokeny wynika z tego,  że jeśli zautoryzuję się dla jednego konta na https://apps.developer.allegro.pl.allegrosandbox.pl i uzyskam prawidłowy token, to jeśli robię za chwilę to samo dla innego konta allegro to dostaję zły token mimo tego, że w requescie są prawidłowe dane.
Dopiero jak się wyloguję manulanie z https://apps.developer.allegro.pl.allegrosandbox.pl i spróbuję ponownej autoryzacji dla uzyskania tokena to otrzymuję prawidłowy token.
Wydaje się, że powinna być opcja wylogowania po pobraniu tokena tak, żeby kolejna autoryzacja z dla innego konta mogła przebiec prawidłowo i otrzymać token dla konta dla którego faktycznie wysyłamy dane a nie dla konta z poprzedniej autoryzacji.

**Comment by dtarczynski** [comment]
Być może powiązane
https://github.com/allegro/allegro-api/issues/11#issuecomment-381321929
-- 
Pozdrawiam
Dariusz Tarczyński

**Comment by AniaMalinowska** [comment]
W tej chwili nie, niemniej sugestię w tej kwestii przekazałam do właściwych osób.

**Comment by SoftSolid** [comment]
Na pewno warto by było podczas zawracania danych z tokenem/kodem zwrócić informację dla jakiego konta jest to token/kod. W ten sposób wiedzielibyśmy o wiele szybciej w czym jest problem. Duża strata czasu. Bardzo duża.

**Comment by dtarczynski** [comment]
@SoftSolid Nie do końca, bo podczas występowania o token nie wiesz jaki użytkownik go żąda. A przynajmniej nie powinieneś wiedzieć.

**Comment by mindc** [comment]
@dtarczynski Zgadzam się, że takie dane nie powinny być przekazywane razem z tokenem, ale powinna być  jakaś opcja aby pobrać podstawowe dane użytkownika.

**Comment by AniaMalinowska** [comment]
Dodam, że token można rozkodować - wówczas otrzyma się ID użytkownika.

**Comment by mindc** [comment]
@AniaMalinowska nie pomyślałem o tym, a to przecież standardowy token JWT, a w nim `user_name`. Dzięki!
