### ISSUE TITLE
Przypisanie metod wysyłki z interfejsu użytkownika do nazw w API

### ISSUE THREAD

**Issue by lukasz-mainka** [allegro/allegro-api#1150]
Czy przesyłki w interfejsie Allegro:
"Punkty Poczta, Żabka, Orlen, Ruch" -> "opłata z góry" należy przyporządkować do nazwy przesyłki a API "Punkty Poczta, Żabka, Orlen, Ruch"
a 
"Punkty Poczta, Żabka, Orlen, Ruch" -> "opłata przy odbiorze" do "Punkty Poczta pobranie" ?
Jeżeli nie proszę o podanie poprawnego przyporządkowania dla tych przesyłek.

**Comment by lukasz-mainka** [comment]
![odbiory w punkcie](https://user-images.githubusercontent.com/34099642/52341692-925fae00-2a13-11e9-8466-7ca13a14ee3f.jpg)

**Comment by MartaNowaczyk** [comment]
@lukasz-mainka zgadza się, bo w Żabce, Ruchu i na Orlenie nie ma pobraniówek.
