### ISSUE TITLE
Problem uwierzytelniania.

### ISSUE THREAD

**Issue by mateuszkawiak** [allegro/allegro-api#1151]
Adres przekierowujący mnie do zalogowania się w allegro(https://allegro.pl/auth/oauth/authorize) z mojej aplikacji zostawia mnie z następującym błędem.
" 
Nie możemy wyświetlić strony

Numer błędu: 54685c101a9e1d63
"

**Comment by mateuszkawiak** [comment]
{"error":"Unauthorized","error_description":"Full authentication is required to access this resource"}

przy próbie autoryzacji do sandboxa


konto na sandboxie: mateusz.kaw974@gmail.com

**Comment by MartaNowaczyk** [comment]
Konto jest już aktywne.
