### ISSUE TITLE
doAddPackageInfoToPostBuyForm brak informacji na koncie 

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#1152]
Witam,
wykonuję  operacje doAddPackageInfoToPostBuyForm

 `<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
    <SOAP-ENV:Body><ns1:DoAddPackageInfoToPostBuyFormRequest>
            <ns1:sessionId>....</ns1:sessionId>
            <ns1:transactionId>968158401</ns1:transactionId>
            <ns1:packageInfo>
                <ns1:item>
                    <ns1:operatorId>6</ns1:operatorId>
                    <ns1:packageId>00259007738572143959</ns1:packageId>
                </ns1:item></ns1:packageInfo>
        </ns1:DoAddPackageInfoToPostBuyFormRequest>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

w odpowiedzi dostaję informację `
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
    <SOAP-ENV:Body>
        <ns1:doAddPackageInfoToPostBuyFormResponse>
            <ns1:postBuyFormPackageInfo>
                <ns1:packageIdsAdded>
                    <ns1:item>00259007738572143959</ns1:item>
                </ns1:packageIdsAdded>
                <ns1:packageIdsNotAddedIncorrectOperatorId/><ns1:packageIdsNotAddedIncorrectPackageId/>
            </ns1:postBuyFormPackageInfo></ns1:doAddPackageInfoToPostBuyFormResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

jak mniemam to wskazuje na to że udało się dodać informacje o wysyłce. ALE po wejściu na koncie allegro w "Lista nadanych przesyłek" lista jest pusta.
Czy to powinno tak wyglądać ?

**Comment by lukada4100** [comment]
Wydaje mi się, że mam ten sam problem. Mniej więcej 2-3 procent wszystkich dodawanych za pomocą doAddPackageInfoToPostBuyForm informacji nie zostaje zapisanychw systemie, mimo, że metoda nie zwraca żadnego błędu. Nigdy jednak nie udało mi się złapać konkretnego przypadku niezrealizowanego wywołania, więc nie mogę być pewny.

**Comment by MartaNowaczyk** [comment]
@mzawodzinski numer przesyłki został poprawnie dodany. Jeśli chodzi o zakładkę "lista nadanych przesyłek" - tam znajdziesz tylko te przesyłki, które wysłałeś za pomocą narzędzia nadawczego Allegro. Czyli tylko wtedy, gdy wejdziesz w "Zamówienia" i na karcie przedmiotu skorzystasz z "Nadaj przesyłkę kurierem".

@lukada4100 u ciebie to raczej inny problem. Daj znać jeśli uda ci się złapać konkretnyy przykład.
