### ISSUE TITLE
oferty zakańczają się bez powodu po zakupie

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#1153]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ X] inny

Mam taki problem, że oferty automatycznie zakańczają się po zakupie, choć nie powinny.
Wystawiam 3 sztuki towaru, ktoś kupuje jedną sztukę i oferta się automatycznie zakańcza.
Problem dotyczy wszystkich ofert.

przykładowy nr oferty 7619042134

**Comment by dostawcaopon** [comment]
Zauważyłem jeszcze dziwniejsze rzeczy, np wczoraj zakończyły mi się oferty z powodu sprzedaży, choć nie powinny, z tym że sprzedaż była np tydzień temu, albo kilka dni temu

np taka oferta 7618894165
były wystawione 3 sztuki
23 stycznia była sprzedaż jednej sztuki
a wczoraj (7 luty, godz 0:41) ta oferta się zakończyła z powodu sprzedaży, choc zadnej nowej sprzedazy nie było i dostepne byly dwie sztuki jeszcze

**Comment by MartaNowaczyk** [comment]
@dostawcaopon jeśli korzystasz z oprogramowania zewnętrznego sprawdź czy problemem nie jest samo działanie aplikacji. Z tym zestawem danych nie widzę bezpośredniego związku zakończenia oferty ze sprzedażą. Nie zgadzają się czasy. Jeśli byłoby tak jak piszesz oferta powinna zakończyć się w podobnym czasie. Tutaj mamy jednak duże różnice czasowe i to nie są godziny tylko np. w przypadku drugiej oferty tygodnie.
Możesz potwierdzić w jakiś sposób kwestię, że oferta zakończyła się po sprzedaży? Taką dostajesz informacje na maila, czy to twój wniosek? Potrzebuję więcej informacji do weryfikacji.

**Comment by dostawcaopon** [comment]
korzystam ze swojego oprogramowania, już sprawdziłem dokładnie - wszystkie oferty w których była jakakolwiek sprzedaż (nawet jeśli nie wyprzedały się wszystkie sztuki) zostały zakończone automatycznie. 
W mailu potwierdzającym zakończenie oferty podany jest powód SPRZEDAŻ

np mail **sprzed 7 godzin** 
Zakończenie Kup Teraz - nr: 7618890966 (Sprzedaż)

Nazwa	4x YOKOHAMA Geolandar A/T G015 205/70R15 96H RPB (numer: 7618890966)
Data rozpoczęcia	wto, 16 paź 2018, 09:57:08
Zakończenie sprzedaży	czw, 7 lut 2019, 00:36:27
Ofert kupna	1
Liczba kompletów	4

a sprzedaż tej jednej sztuki była 2-giego lutego

**Comment by dostawcaopon** [comment]
kolejna ciekawostka, mail od was sprzed kilku minut:

Zakończenie Kup Teraz
Nazwa	2x HANKOOK Winter i*cept RS2 W452 185/60R15 84T (numer: 7619119630)
Data rozpoczęcia	wto, 16 paź 2018, 12:11:12
Zakończenie sprzedaży	czw, 7 lut 2019, 08:01:22
Nie było ofert kupna. 

Nasz program nie zakańczał tej oferty, w ogole oprogramowanie API jest wyłączone od wczoraj wieczora.
Dlaczego oferta została zakończona?

**Comment by MartaNowaczyk** [comment]
@dostawcaopon tytuł "Zakończenie Kup Teraz - nr: 7618890966 (Sprzedaż)" nie świadczy o tym, że oferta zakończyła się, bo coś się sprzedało. Tylko o tym, że w danej ofercie była sprzedaż. Dla podanych przez ciebie ofert w naszym systemie jest informacja, że oferty zakończył sam sprzedający.

**Comment by dostawcaopon** [comment]
Dziękuę za informacje, można zamknąć temat.
