### ISSUE TITLE
offers/listing - sortowanie po cenie

### ISSUE THREAD

**Issue by kamaz08** [allegro/allegro-api#1154]
Cześć, 

Metoda **doGetItemsList** w **webapi** umożliwiała mi pobieranie produktów w podanym przedziale cenowym. 
Czy jest taka możlwość w **rest api** metoda **offers/listing**? 
Próbuje dodać parametr `sellingMode.price.amount.lte=10 `jednak nie daje on efektów.

Pozdrawiam ;)

**Comment by kamaz08** [comment]
Dobra mam ; ) Gdyby ktoś potrzebował to
price.from
price.to

**Comment by MartaNowaczyk** [comment]
@kamaz08 Cześć, zgadza się :) wszystko jest [tutaj](https://developer.allegro.pl/listing/).
