### ISSUE TITLE
Aktywowanie konta firmowego sandbox

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1155]
Chciałbym aktywować konto firmowego w środowisku testowym (login: sojtin)
Po przejściu na https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php/convertAccount, dostaje informacje "Aby przekształcić konto w firmowe, musisz się najpierw zweryfikować, robiąc przelew z rachunku firmowego." przechodzę linkiem do aktywacji i mam "
Sprzedaż aktywna - wpłata online." i żadnych dodatkowych opcji. Coś jeszcze muszę zrobić po swojej stronie?

**Comment by MartaNowaczyk** [comment]
Aby w pełni aktywować konto firmowe musisz przejść do zakładki moje konto i wysłać do nas dowolne 2 pliki.

**Comment by Sojtin** [comment]
@MartaNowaczyk  "Dane przedsiębiorstwa na koncie Allegro zostały wyedytowane. Zmiana musi jeszcze zostać zatwierdzona przez pracownika Allegro."
