### ISSUE TITLE
doAddPackageInfoToPostBuyForm i ERR_IP_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by Gecco** [allegro/allegro-api#1156]
Dzień dobry, posiadamy serwis w którym klienci mogą pobierać masowo swoje aukcje. Związku ze zmianami wprowadzonymi od lutego dodaliśmy opcję uzupełniania numerów listów przewozowych dla swoich aukcji. 

Po dodaniu obsługi uzupełniania listów poprzez doAddPackageInfoToPostBuyForm dostajemy ERR_IP_LIMIT_EXCEEDED. Są to setki jak nie tysiące listów przewozowych, które nasi klienci próbują jednocześnie dodać do swoich transakcji. Limit 120 jest jednak trochę mały. Czy można go jakoś zwiększyć. Wprowadzanie limitu akurat na ten endpoint w przypadku kiedy można wrzucić naraz tylko dane dot. jednej transakcji jest trochę mały.

W/w to są nasze przypuszczenia. Pewności nie mamy.

Inna sprawa w jaki sposób możemy odblokować nasze ip.

**Comment by MartaNowaczyk** [comment]
Zgodnie z informacją [na naszej stronie](https://allegro.pl/webapi/faq.php#faq_1) "Aby zdjąć blokadę, ustaw serwer proxy na swojej maszynie z zablokowanym IP i z tego serwera, wypełnij CAPTCHA pod adresem: http://allegro.pl/blocked/index.php."

Jeśłi chodzi o wielkość limitu to nie będziemy go zmieniać.

**Comment by Gecco** [comment]
Ja rozumiem, tylko to są serwery na których ciężko wejść na jakąś stronę a tym bardziej przepisać captche. Druga sprawa, że z jednej strony wymuszacie na klientach uzupełnianie listów przewozowych a z drugiej strony za to blokujecie.

**Comment by MartaNowaczyk** [comment]
Możesz skontaktować się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by Gecco** [comment]
Ok, dzięki.

**Comment by MartaNowaczyk** [comment]
@Gecco dodaj tylko, że to do zgłoszenia na GitHubie #1156 i od razu przekierują do nas.

**Comment by MartaNowaczyk** [comment]
@Gecco z tego co widzę, 72% requestów jest odbijanych z powodu błędnego ID transakcji. W piku widać tylko średnio 3,5 requesta poprawnego. Najpierw zalecam optymalizację i wyeliminowanie błędnych zapytań, a z limitem nie powinno być problemu. Twój standardowy ruch mieści się ze spokojem w limitach, ale od czasu jak pojawiają się te błędy ilość zapytań znacznie wzrosła przez co wpadłeś w limity. 
Jeśli chodzi o blokadę IP nie możemy jej za was zdjąć.

**Comment by Gecco** [comment]
Trochę głupia sprawa, bo wydawało nam się, że wysyłamy poprawne numery. Poprawiliśmy parę rzeczy. Resztę zrobimy na nowym API.

**Comment by MartaNowaczyk** [comment]
OK. Jeśli w tym temacie wszystko jasne proszę o zamknięcie.
