### ISSUE TITLE
Lista kategorii w pliku XLS lub CSV

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1157]
Witam,
Czy mają Państwo listę kategorii w pliku XLS lub CSV ?
Tak aby w jednej kolumnie było id_kategorii a w drugiej pełna nazwa kategorii
np.:
121212;Kultura i rozrywka / Instrumenty / Gitary i akcesoria / Akustyczne

Potrzebuje takie coś by przypisać do Państwa kategorii nasze kategorie ze sklepu.

Pozdrawiam
Aleksy

**Comment by MartaNowaczyk** [comment]
Witam,
drzewo kategorii zmienia się praktycznie codziennie, dlatego powinieneś je sam pobierać przez udostępnione przez nas zasoby. Znajdziesz je [w naszym poradniku](https://developer.allegro.pl/sale/#step-2).

**Comment by TimothyKoval** [comment]
Rozumiem, że jest problem "praktycznie codziennie" robić dump do json-a i publikować go na serwerze?

**Comment by AleksyZajac** [comment]
W przedstawionym przykładnie nie ma możliwości pobrania jednym zapytaniem całego drzewa kategorii.

Jeżeli macie gotowy taki przykład to prosiłbym o przesłanie.

Pozdrawiam
Aleksy

**Comment by AleksyZajac** [comment]
Dzięki za pomoc już sobie sam poradziłem.

Pozdrawiam
Aleksy

**Comment by saviano72** [comment]
Czy możesz mi powiedzieć jak sobie poradziłeś?

**Comment by AleksyZajac** [comment]
Witam,
Nie jest to pewnie najlepszy kod, ale był robiony na szybko i wygląda jak poniżej.
Skrypt na standardowe wyjście STDOUT wyrzuca w kodowaniu iso-8859-2 następujące dane:

$categories_parent;$categories_id;$categories_nazwa;

#!/usr/bin/perl

use LWP::UserAgent;
use HTTP::Request::Common qw(GET POST);
use HTTP::Cookies;

use Encode;
use XML::Simple;
use Data::Dumper;
use XML::Simple;
use HTML::Entities;
use String::Random;
use JSON;

####
#### NAJPIERW MUSISZ WYKONAĆ WSZYSTKO CO ZWIĄZANE Z AUTORYZACJĄ
####

$ALLEGRO_CONFIG_URL_API = 'https://api.allegro.pl.allegrosandbox.pl';
$ALLEGRO_CONFIG_URL_CATEGORIES=$ALLEGRO_CONFIG_URL_API.'/sale/categories/?parent.id=122640';

$socket = LWP::UserAgent->new;
$request = GET("$ALLEGRO_CONFIG_URL_CATEGORIES", "Authorization" => "Bearer $ALLEGRO_access_token", "Accept"=> "application/vnd.allegro.public.v1+json","Accept-Language"=>"pl-PL");
$dane_json = $socket->request($request);

if ($dane_json->is_success) {
$odpowiedz_json=$dane_json->content;
} else {
print "ERROR\n";
exit 0;
}


$ilosc_kategorii=$#{$data->{'categories'}};
undef %categories;
for ($i=0; $i<($ilosc_kategorii+1); $i++) {
$categories_id='';
$categories_nazwa='';
$categories_parent='';

$categories_id=$data->{'categories'}[$i]{'id'};
$categories_parent=$data->{'categories'}[$i]{'parent'}{'id'};
$categories_nazwa=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));

$categories{"$categories_id"}=$categories_id;
$kategorie{$categories_id}=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));
print "$categories_parent;$categories_id;$categories_nazwa;\n";
}

START:
undef %categories1;

$licznik=0;
foreach $element (sort keys %categories) {
$licznik++;
}

if (!$licznik) {
exit 0;
}

foreach $element (sort keys %categories) {
$error=0;
$error=&allegro_restapi_funkcje_pobierz_categories($element);
$error=0;
$error=&allegro_restapi_funkcje_parsuj_odpowiedz();


$ilosc_kategorii=$#{$data->{'categories'}};
for ($i=0; $i<($ilosc_kategorii+1); $i++) {
$categories_id='';
$categories_nazwa='';
$categories_parent='';

$categories_id=$data->{'categories'}[$i]{'id'};
$categories_parent=$data->{'categories'}[$i]{'parent'}{'id'};
$categories_nazwa=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));

$categories1{"$categories_id"}=$categories_id;

$kategorie{$categories_id}=$kategorie{$categories_parent}.' / '.encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));

print "$categories_parent;$categories_id;$kategorie{$categories_id};\n";
}
}

undef %categories;
%categories=%categories1;
goto START;
exit 0;

**Comment by saviano72** [comment]
Dziękuję,

A bardziej łopatologicznie, czy mógłbyś wyjaśnić jak to uruchomić/wdrożyć?

Niestety mam małe pojęcie jeśli chodzi o programowanie...

Z góry dziękuję...

pon., 4.03.2019, 08:00 użytkownik AleksyZajac <notifications@github.com>
napisał:

**Comment by Dawidek990** [comment]
Witam, potrzebuje wlasnie drzewa kategori takie jak pan ma... czy mogl by mi pan wyslac plik z taki drzewem jednorazowo? byl bym wdzieczny.
dejwtabor@gmail.com

**Comment by Dawidek990** [comment]
> 
> 
> Witam,
> Czy mają Państwo listę kategorii w pliku XLS lub CSV ?
> Tak aby w jednej kolumnie było id_kategorii a w drugiej pełna nazwa kategorii
> np.:
> 121212;Kultura i rozrywka / Instrumenty / Gitary i akcesoria / Akustyczne
> 
> Potrzebuje takie coś by przypisać do Państwa kategorii nasze kategorie ze sklepu.
> 
> Pozdrawiam
> Aleksy

Witam, potrzebuje wlasnie drzewa kategori takie jak pan ma... czy mogl by mi pan wyslac plik z taki drzewem jednorazowo? byl bym wdzieczny.
dejwtabor@gmail.com

**Comment by karaczun** [comment]
> Witam, Nie jest to pewnie najlepszy kod, ale był robiony na szybko i wygląda jak poniżej. Skrypt na standardowe wyjście STDOUT wyrzuca w kodowaniu iso-8859-2 następujące dane:
> 
> $categories_parent;$categories_id;$categories_nazwa;
> 
> #!/usr/bin/perl
> 
> use LWP::UserAgent; use HTTP::Request::Common qw(GET POST); use HTTP::Cookies;
> 
> use Encode; use XML::Simple; use Data::Dumper; use XML::Simple; use HTML::Entities; use String::Random; use JSON;
> 
> #### NAJPIERW MUSISZ WYKONAĆ WSZYSTKO CO ZWIĄZANE Z AUTORYZACJĄ
> $ALLEGRO_CONFIG_URL_API = 'https://api.allegro.pl.allegrosandbox.pl'; $ALLEGRO_CONFIG_URL_CATEGORIES=$ALLEGRO_CONFIG_URL_API.'/sale/categories/?parent.id=122640';
> 
> $socket = LWP::UserAgent->new; $request = GET("$ALLEGRO_CONFIG_URL_CATEGORIES", "Authorization" => "Bearer $ALLEGRO_access_token", "Accept"=> "application/vnd.allegro.public.v1+json","Accept-Language"=>"pl-PL"); $dane_json = $socket->request($request);
> 
> if ($dane_json->is_success) { $odpowiedz_json=$dane_json->content; } else { print "ERROR\n"; exit 0; }
> 
> ilosckategorii=#{$data->{'categories'}}; undef %categories; for ($i=0; $i<($ilosc_kategorii+1); $i++) { $categories_id=''; $categories_nazwa=''; $categories_parent='';
> 
> $categories_id=$data->{'categories'}[$i]{'id'}; $categories_parent=$data->{'categories'}[$i]{'parent'}{'id'}; $categories_nazwa=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));
> 
> $categories{"$categories_id"}=$categories_id; $kategorie{$categories_id}=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'})); print "$categories_parent;$categories_id;$categories_nazwa;\n"; }
> 
> START: undef %categories1;
> 
> $licznik=0; foreach $element (sort keys %categories) { $licznik++; }
> 
> if (!$licznik) { exit 0; }
> 
> foreach $element (sort keys %categories) { $error=0; $error=&allegro_restapi_funkcje_pobierz_categories($element); $error=0; $error=&allegro_restapi_funkcje_parsuj_odpowiedz();
> 
> ilosckategorii=#{$data->{'categories'}}; for ($i=0; $i<($ilosc_kategorii+1); $i++) { $categories_id=''; $categories_nazwa=''; $categories_parent='';
> 
> $categories_id=$data->{'categories'}[$i]{'id'}; $categories_parent=$data->{'categories'}[$i]{'parent'}{'id'}; $categories_nazwa=encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));
> 
> $categories1{"$categories_id"}=$categories_id;
> 
> $kategorie{$categories_id}=$kategorie{$categories_parent}.' / '.encode("iso-8859-2", decode("utf8", $data->{'categories'}[$i]{'name'}));
> 
> print "$categories_parent;$categories_id;$kategorie{$categories_id};\n"; } }
> 
> undef %categories; %categories=%categories1; goto START; exit 0;

czy mógłbyś to ubrać w jakiś skrypt i dać publicznie? Nie znam się na programowaniu, a takie narzędzie by się przydało nie tylko mi. Postawię dobrego browarka :)

**Comment by Pawikoski** [comment]
Posiadam wszystkie kategorie (id + breadcrumb). Mogę przekonwertować do dowolnego formatu pliku, wedle potrzeb.
Przykład jednego rekordu w JSON:
`{"breadcrumb": "Elektronika > Fotografia > Akcesoria fotograficzne > Akcesoria wodoszczelne", "category_id": "28155"}`
Łącznie plik zawiera 25669 rekordów.
Mogę również przygotować listę kategorii z wybranej kategorii głównej, np. tylko z kategorii 'Elektronika'

Zapraszam do kontaktu: pawikoski@gmail.com
