### ISSUE TITLE
W podanej kategorii możesz wystawiać tylko ogłoszenia.

### ISSUE THREAD

**Issue by landweb** [allegro/allegro-api#1158]
Występuje problem: 
 - [ doNewAuctionExt] z metodą WebAPI
 - [tak ] ze środowiskiem produkcyjnym
 - [ nie] ze środowiskiem testowym
 - [ nie] z logowaniem lub autoryzacją
 - [ nie] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ nie] inny

Podczas wystawiania oferty za pomocą metody doNewAuctionExt webApi otrzymuję komunikat "W podanej kategorii możesz wystawiać tylko ogłoszenia.". Oferta dotyczy kategorii o id = 5557 (motocykle i quady). Niestety nie mogę dla tej oferty pozyskać xml. Jakie są najczęstsze przyczyny występowania tego błędu?

**Comment by MartaNowaczyk** [comment]
Nie widzę co wysyłasz - brak requesta, ale pewnie masz błędną strukturę. Jeśli chcesz wystawić w danej kategorii pobierz listę pól metodą doGetSellFormFieldsForCategory. Możesz też pobrać daną ofertę metodą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842), a następnie na tej podstawie wystawić.

Przypominamy, że stopniowo będziemy wygaszać WebAPI o czym szeroko informowaliśmy np. na [GitHubie](https://github.com/allegro/allegro-api/issues/1043). W związku z tym zalecamy migrację na [REST API](https://developer.allegro.pl/about/).

**Comment by landweb** [comment]
Z innymi aukcjami nie ma problemu. Wystawiają się bez problemu. Tylko z tą. Myślałem może że są jakieś restrykcje dotyczące tej konkretnej kategorii.

**Comment by MartaNowaczyk** [comment]
@landweb udało się wystawić ofertę?

**Comment by landweb** [comment]
niestety nie :(

**Comment by MartaNowaczyk** [comment]
@landweb w jaki sposób wystawiasz tę ofertę, że nie możesz podać requesta?

**Comment by deneb-k** [comment]
> Z innymi aukcjami nie ma problemu. Wystawiają się bez problemu. Tylko z tą. Myślałem może że są jakieś restrykcje dotyczące tej konkretnej kategorii.

Są. https://allegro.pl/webapi/tutorials.php/tutorial/id,100461
