### ISSUE TITLE
WebAPI vs RestAPI - różne ID parametrów kategorii

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1159]
Witam,
przykład dla kategorii "Odzież, Obuwie, Dodatki \ Odzież męska \ T-shirty" 87913:
- WebAPI
https://gist.github.com/PhotoSoft/7a172e47266e3692d7dcdf8cf1a30237
- RestAPI
https://gist.github.com/PhotoSoft/60e7b63d1a97caf53bea87dfd931e944

Proszę powiedzieć, że różne ID parametrów oraz ich wartości to błąd, a nie feature?

Bo jak teraz sprzedawca mający kilka tysięcy aukcji zapisanych w zewnętrznej aplikacji z wypełnionymi parametrami kategorii dla WebAPI ma wystawić aukcję poprzez RestAPI? Ma ręcznie od nowa ustawiać parametry?

Pomijam już wymóg stosowania cenników utworzonych w Moim Allegro, bo przecież WebAPI ich nie obsługiwało, więc to kolejny element do ręcznej poprawy.

Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
@PhotoSoft Analizujemy opisaną sytuację. Dam znać gdy coś ustalimy.

**Comment by MartaNowaczyk** [comment]
@PhotoSoft Uspójnimy parametry - poprawkę mamy już przygotowaną. Czekamy na wdrożenie.

**Comment by PhotoSoft** [comment]
Kiedy będzie ta poprawka? Stoję z integracją w miejscu, a terminu nie chcecie przesunąć...

**Comment by PhotoSoft** [comment]
Albo dodajcie jak najszybciej metodę, która będzie konwertować parametry WebApi -> RestApi.

Bo widzę, że po wystawieniu aukcji przez WebApi, a potem pobraniu jej przez RestApi parametry są już zwracane z innymi ID.

**Comment by MartaNowaczyk** [comment]
ID parametrów powinny być już uspójnione. Jeśli nadal masz problemy podaj przykłady niespójności parametrów.

Trzeba pamiętać tylko, że:

ID parametru w webAPI jest w polu: <ns1:sellFormParamId>206002</ns1:sellFormParamId>

<ns1:sellFormId>29660</ns1:sellFormId> - to ID formularza webAPI, a nie parametru.

**Comment by PhotoSoft** [comment]
Bardzo dziękuję za uświadomienie :) Nigdy nie korzystałem z sellFormParamId, ponieważ nie było nigdzie używane. Wygląda na to, że jest ok.

Więc moje zgłoszenie błędu okazało się całkowicie przypadkowe.

**Comment by PhotoSoft** [comment]
Jeszcze przy okazji spytam, czy parametry zwracane przez RestApi mogą być w takiej samej kolejności jaką definiowało w WebApi pole sellFormPos? Tak samo są sortowane przy edycji przez www.

Na chwilę obecną RestApi zwraca je chaotycznie i użytkownicy na pewno będą marudzić, dlaczego są w innej kolejności :)

**Comment by MartaNowaczyk** [comment]
Rozumiem, że chodzi o parametry z multipleChoices. Jeśli tak, to nie mamy w planach zmian w tej kwestii.

**Comment by PhotoSoft** [comment]
Nie. Wytłumaczę na przykładzie kategorii 4633.

Przez www parametry są tak posortowane:

![image](https://user-images.githubusercontent.com/11736155/54447837-ac935700-474a-11e9-9668-d06bf63e75b0.png)

W WebApi dzięki zapytaniu ORDER BY sellFormOpt, sellFormPos można uzyskać tą samą kolejność:

![image](https://user-images.githubusercontent.com/11736155/54448024-157acf00-474b-11e9-97bc-9b6387af815c.png)

W RestApi jest to już niemożliwe, ponieważ brakuje odpowiednika sellFormPos, natomiast same parametry są zwracane w innej kolejność: Stan, Waga, Producent, itd.:
https://gist.github.com/PhotoSoft/d93a05130822cf1a234ce4b6a6b5966d

**Comment by MartaNowaczyk** [comment]
@PhotoSoft napisz proszę dlaczego kolejność tych parametrów jest dla ciebie tak istotna.

**Comment by PhotoSoft** [comment]
Przede wszystkim dla zachowania 100% zgodności z formularzem www.

A druga sprawa, że teraz jest misz-masz. Parametry obowiązkowe są wymieszane z nieobowiązkowymi. Przy kategoriach z odzieżą, gdzie jest ich bardzo dużo jest straszny bałagan:

![image](https://user-images.githubusercontent.com/11736155/54535925-e6a16a80-498f-11e9-845c-31cb6da60ec4.png)
![image](https://user-images.githubusercontent.com/11736155/54535955-f9b43a80-498f-11e9-9773-b93b01031ed7.png)

**Comment by MartaNowaczyk** [comment]
@PhotoSoft dzięki za opisanie potrzeby. Nie mogę obiecać, że to zmienimy, ale przekażę to do zespołu, który zajmuje się tym obszarem.
