### ISSUE TITLE
Promowane aukcje

### ISSUE THREAD

**Issue by mbx88** [allegro/allegro-api#116]
Witam,

chcę pobrać ofert promowane:
dla metody doGetItemsList (własciwość promotionInfo ) jest 8 promowanych aukcji (prawidłowo
a sprawdzając aukcje za pomocą metody doGetItemsInfo (maska itOptions) liczba promowanych jest duzo wieksza, dlaczego?

**Comment by AniaMalinowska** [comment]
W polach [promotionInfo](https://allegro.pl/webapi/documentation.php/show/id,1342#method-output) i [itOptions](https://allegro.pl/webapi/documentation.php/show/id,52#method-output) otrzymujesz rodzaj promowania. W metodzie [doGetItemsList](https://allegro.pl/webapi/documentation.php/show/id,1342) liczbę promowanych ofert w danej paczce otrzymasz w polu [itemsFeaturedCount](https://allegro.pl/webapi/documentation.php/show/id,1342#method-output).

**Comment by mbx88** [comment]
Witam,

być może źle się wyraziłem.

Dla tego samego konta pobieram dane:
doGetItemsList - zwraca aukcje wszystkie i po sprawdzeniu promotionInfo otrzymuję 8 promowanych.
Gdy mam listę aukcji dla tego konta, pobieram dla nich dane za pomoca metody doGetItemsInfo.   Sprawdzając właściwośc itOptions (maska bitowa, 1,2,4 - bo te wartosci są oznaczają promowanie)
wychodzi na to, że promowanych jest dużo więcej.
Podsumowując - zwracane dane są niespójne.
Pytanie - dlaczego?

**Comment by AniaMalinowska** [comment]
Podeślij nam proszę pliki *.XML z request i response:
https://pomoc.allegro.pl/kontakt/#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422
i podaj tutaj numer Ticketa - zweryfikujemy to.
