### ISSUE TITLE
Żywotność świeżo przesłanych zdjęć

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#1160]
Witam,

jak długo "żyje" zdjęcie przesłane przez api i nie wykorzystane w ofercie?

Ostatnio wrzucone zdjęcie 6.02.2019 o 1:45 wskazało  [expiresAt] => 2019-02-06T06:45:44.047572Z a jest widoczne dalej pomimo braku wykorzystania w ofercie.

**Comment by MartaNowaczyk** [comment]
Wstarczy, że masz je w szkicu i wtedy jest oznaczone jako wykorzystane.

**Comment by dlis2010** [comment]
W tym wypadku zdjęcie nie było dodawane do żadnego szkicu.

Pytanie o ten czas życia, jest dla mnie bardzo ważne, mamy do wystawienia większą ilość aukcji. najpierw chciałbym wrzucić zdjęcia potem aukcje i tu moja obawa czy do tego czasu zdjęcia mi "przeżyją" ;)

**Comment by MartaNowaczyk** [comment]
Radzę przyjąć zwracaną datę.
