### ISSUE TITLE
{Seller_ID} skąd mam go pobrać ?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1161]
Witam,
Skąd mogę pobrać {Seller_ID} które jest wymagane w shipping-rates ?
Chciłbym pobrać identyfikatory wszystkich swoich cenników dostaw.

Pozdrawiam
Aleksy

**Comment by MartaNowaczyk** [comment]
Wszystkie tokeny sa w technologi JWT także możesz je rozkodować i w ten sposób otrzymasz m.in. identyfikator użytkownika {seller_id}

**Comment by AleksyZajac** [comment]
Witam,
Proszę w takim razie wskazać mi miejsce w dokumentacji gdzie jest opisane w jaki sposób mogę pobrać swój seller_id, bo prawdę mówiąc nigdzie tego nie widzę lub zostało inaczej nazwane.

**Comment by AleksyZajac** [comment]
Dla sprecyzowania korzystam z dokumentacji https://developer.allegro.pl/sale/

**Comment by AleksyZajac** [comment]
Wystarczy napisać w dokumentacji że "user_name" w zdekodowanym tokenie to seller_id.

**Comment by AleksyZajac** [comment]
Problem w tym że po rozkodowaniu tokena nie mam user_name :-)

**Comment by AleksyZajac** [comment]
Ponowie pytanie jak w REST API mam uzyskać seller_id.

**Comment by AleksyZajac** [comment]
Po zdekodowaniu mam:
{
  "scope": [
    "allegro_api"
  ],
  "exp": 1549592657,
  "jti": "ecc736d9-fca7-4e4b-ab92-0e42de0ebe27",
  "client_id": "a92c8455eafc40c3bac8041bc6369b39"
}

**Comment by AleksyZajac** [comment]
Czy saller_id mogę pobrać z linnku https://allegro.pl.allegrosandbox.pl/login/user
gdzie po zalogowaniu mam coś takiego jak userId.

**Comment by AssAssIn1909** [comment]
Chyba zły token dekodujesz
```
  "exp": 1549593902,
  "user_name": xxxxxxxxx,
  "jti": xxxxxxxxxxx,
  "client_id": "xxxxxxxxx,
  "scope": []
```
Ja normalnie z tego dekoduje
Mowie oczywiście o access tokenie

**Comment by AleksyZajac** [comment]
Dekoduje poprawny token "access_token" dla tzw. Device flow dla Allegro OAuth bo takiego używam.
Aplikacja która się łączy jest całkowicie pozbawiona interfejsu użytkownika i nie ma możliwości zalogowania się użytkownika.

**Comment by MartaNowaczyk** [comment]
ten sam temat poruszany był w #841

**Comment by AleksyZajac** [comment]
Dziękuję za informację.

**Comment by runaway90** [comment]
Dzień dobry. 
Dlaczego w tokienie {{SELLER_ID}} jest parametrem {user_name}?

**Comment by MartaNowaczyk** [comment]
@runaway90 to jest standardowa nazwa claim'a -> ona jest bardzo ogólna i w JWT można wstawić jakiś identyfikator użytkownika/login/e-mail - my wstawiamy ID a nie login bo to jest bardziej przydatne

**Comment by runaway90** [comment]
@MartaNowaczyk a czy nie ma innej możlywośći pobierania SELLER_ID, naprzykład, jak ja chce pobrać wszystki dane(kilkanaście accountów) na jednej applikacje bez wysylania/ruszania ACCESS_TOKEN, a wylącznie ten identyfikator? 
Może być będzie jakaś metoda dla applikacij z welu uzytkownikami?

**Comment by MartaNowaczyk** [comment]
@runaway90 na ten moment skupiamy się na najważniejszych zasobach by można przejśś bez problemu na REST API z webAPI. Jeśli powstanie taki zasób na pewno o tym poinformujemy w oddzielnym newsie.

> i w JWT jest padameter {client_id}, czy go też trzeba urzywać w przyślości?

możesz to rozwinąć?

**Comment by runaway90** [comment]
Mam takie zawartośći w token-ie:
{"alg":"...","typ":"JWT"}{"exp":...,"user_name":"...","jti":"...","client_id":"231072000f124f1486c58e07d964b377","scope":........

chodzi mi o "client_id":"231072000f124f1486c58e07d964b377"...

co to jest za id? i co z nim póżnej robimy?

**Comment by MartaNowaczyk** [comment]
to client_id, który otrzymujesz przy rejestracji aplikacji. Znajdziesz go [tutaj](https://apps.developer.allegro.pl/). Nic nie musisz z nim robić.  Potrzebny jest wcześniej do [autoryzacji aplikacji](https://developer.allegro.pl/auth/).

**Comment by runaway90** [comment]
@MartaNowaczyk 
Dzień dobry żeby rozkodować sellerID z tokiena urzywam takiego kodu w PHP.

```
$code = base64_decode($token);
$changeCode = substr($code, strpos($code, "}", 2) + 2);
$lastVersion = explode(',', substr($changeCode, 0, strpos($changeCode, "scope") - 1));
$sellerId = substr($lastVersion[1], 13, 8);
```

Czy jest możlywość wyniesienia SELLER_ID do responsu na poziomie otrzymania access tokiena za routem _https://allegro.pl/auth/oauth/token?grant_type=client_credentials_?
![q12134131234](https://user-images.githubusercontent.com/20610334/52559264-24d9c600-2df5-11e9-81a5-2c966c4fa0b0.png)

+ja cały czas aktualizuję access_token do refresh_tokena, czy nie będzie możlywośći zmiany SELLER_ID w zakodowanych refresh tokienach(co może spowodować blęd, jak zapisze go 1 raz na początku do swojej BD)?
Dziękuję.

**Comment by runaway90** [comment]
@AleksyZajac Aleksej, proszę otworzyć temat z powrotem. 
Dziękuję.

**Comment by PawelTaberski** [comment]
@runaway90 Sposób autoryzacji o którym napisałeś client credentials nie ma kontekstu usera tzn. możesz go użyć tylko przy publicznych metodach np. GET /offers/listing. Przy pomocy tej autoryzacji nie pobierzesz danych jakiegoś sellera (np. jego cenników dostaw), bo ten token jest tylko na aplikację nie na danego usera. Aby skorzystać z takich zasobów musisz użyć autoryzacji typu device albo code flow. Więcej na ten temat [tutaj](https://developer.allegro.pl/auth/).

**Comment by runaway90** [comment]
@PawelTaberski przepraszam, shodziło mi o device_flow, zrobilem nie tem skrin.
![gsdfgsfdghsfghdfgh](https://user-images.githubusercontent.com/20610334/52561959-34f5a380-2dfd-11e9-900b-282c2f5d72a3.png)

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem o co dokładnie pytasz. Jak już raz user się zautoryzuje to wtedy tylko [odświeżasz sobie token](https://developer.allegro.pl/auth/#refresh-token), nie musi on przechodzić jeszcze raz całego flow. A jeśli chodzi Tobie o device_code to za każdym razem jest inne otrzymujesz je w[ kroku pierwszym](https://developer.allegro.pl/auth/#userDeviceFlow), nie możesz go zaszyć na stałe. Natomiast client_id jest to id aplikacji, które otrzymałeś przy jej rejestracji. To jest swoistego rodzaju login aplikacji, a client secret jest jakby hasłem.

**Comment by runaway90** [comment]
@PawelTaberski ogarnułem to wszystko za dokumentacja i nie mam problemów, ale proponowałem ustalić user_name(to co mamy w tokienie i póżnej będziemy to urzywać jako seller_id) w responsie, kiedy pobieramy tokien dla konta Allegro, żeby nie rozkodowywać go.

**Comment by PawelTaberski** [comment]
Rozumiem, ale ze względów bezpieczeństwa nie planujemy wprowadzać w responsie takiego pola. Wszystkie tokeny są w technologi JWT także, tak jak pisałeś wystarczy go rozkodować i masz id-ka.
