### ISSUE TITLE
Allegro Smart w REST API - czy jest i ilość paczek

### ISSUE THREAD

**Issue by redwingecommerce** [allegro/allegro-api#1162]
1. Kiedy planowane jest przeniesienie na wersję produkcyjną parametru „smart” w metodach:
GET  /order/checkout-forms
GET  /order/checkout-forms/{id}

2. Oprócz parametru mówiącego o tym, czy smart jest czy go nie ma w zamówieniu, przydałaby się informacja, ile przesyłek smart finalnie naliczono do zamówienia.
Wynika to z faktu, że algorytm naliczający koszty dostawy w Allegro w wielu przypadkach, zwłaszcza w zamówieniach "wieloaukcyjnych" różni się od sposobu wyliczania ilości paczek w logistyce.

Przykładowo jeśli klient składa zamówienie złożone z 3 aukcji, gdzie każda ma inny cennik dostawy, możemy mu jedynie ustawić koszt dostawy wg strategii łączenia cenników dostaw, np. sumowanie kosztów dostawy. Co nie oznacza, że klient otrzyma trzy paczki. Jest to jedynie kompromis wynikający z różnych sposobów naliczania kosztów dostawy w systemach oraz różnych cennikach (przykładowo jednej z tych aukcji nie mogę wysłać Pocztą z powodów formalnych - i już mam różne cenniki).

W rzeczywistości podczas pobierania zamówień z Allegro sposób wysłania u wielu klientów opiera się o wagę, wymiary i cenę dostawy, a nie ilość przedmiotów w paczce. Może się więc zdarzyć, że w powyższym przypadku klient otrzyma trzy razy naliczony smart, podczas gdy w rzeczywistości paczkę można wysłać jedną przesyłką. Odwrotne sytuacje też są możliwe.

W związku z tym, aby kontrolować koszty wysyłki oraz rozliczenia z Allegro, przydałaby się informacji, ile przesyłek smart system Allegro naliczył klientowi do danego zamówienia. Mogłoby to być np. pole „smart_quantity” o wartości int w metodzie GET  /order/checkout-forms/{id}.

Czy jest planowane dodanie takiego pola? Jeśli tak, to jaki jest horyzont czasowy?

**Comment by MartaNowaczyk** [comment]
Pole smart jest w szczegółach zamówienia. Pisaliśmy o tym w naszym newsie #842. Nie ma jednak informacji o liczbie przesyłek. Taką sugestię przekaże do odpowiedniego zespołu, jednak nie mogę na ten moment stwierdzić czy i kiedy taka opcja będzie dostępna.

**Comment by redwingecommerce** [comment]
Witam, dziękuję za przekazanie sugestii dalej.

Odnośnie pola "smart" - we wskazanym wątku jest informacja o wersji beta. Kiedy pole pojawi się na wersji public?
Jeśli już jest, to przepraszam, akurat nie mam dostępu do konsoli. Proszę o potwierdzenie.

**Comment by MartaNowaczyk** [comment]
Na ten moment jest jeszcze w wersji beta. Public mamy w planach na luty/marzec. Plany opisaliśmy #1043.
