### ISSUE TITLE
checkout forms i dopłaty

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1163]
1. Klient kupuje kilka przedmiotów, wypełnia formularz, płaci. Dostajemy checkout-form ze statusem READY-FOR-PROCESSING.
2. Klient stwierdził sobie, że kupił za mało i zrobił dopłatę. 

Co się dzieje w takim wypadku?
Dostaniemy nowy checkout-form? Czy może w starym pojawi się po prostu surcharges?
Jeśli pojawi się nowy checkout-form, to czy jest jakiś sposób na podglądnięcie id starego checkout-forma, czy tylko poprzez przeanalizowanie order/events?

**Comment by MartaNowaczyk** [comment]
Informacja o dopłacie pojawi się w surcharges.

**Comment by neldh** [comment]
Rozumiem.
A jeszcze dla pewności: jeśli klient za pierwszym razem nie zapłaci pełnej kwoty (z różnych względów), to mimo wszystko checkout form będzie w statusie READY_FOR_PROCESSING?

**Comment by MartaNowaczyk** [comment]
tak

**Comment by neldh** [comment]
Jeszcze w nawiązaniu: Jeśli dopłata jest zrobiona dużo po pierwotnym checkout formie to czy w odpowiedzi na order/checkout-forms przyjdzie mi ten checkout form, jeżeli żaden kupiony przedmiot nie mieści się w widełkach dat do których zawężam, ale mieści się te dopłata?

Przykładowo:
1. Klient kupuje kilka przedmiotów, wypełnia formularz, płaci. Dostajemy checkout-form ze statusem READY-FOR-PROCESSING. Data 2019-01-01.
2. Klient stwierdził sobie, że kupił za mało i zrobił dopłatę. Data 2019-02-01.
3. Jest 2019-02-01. Korzystam z zasobu order/checkout-forms i ustawiam lineItems.boughtAt.gte tak, żeby obejmowalo 2 dni wstecz. 

Czy w takim wypadku otrzymam tego checkout-forma? Czy ratuje mnie tylko nasluchiwanie order/events (patrząc na nazwę parametru pewnie to drugie ale wolę się upewnić)?

Jeśli mam rację i pozostaje mi tylko dodatkowe skanowanie order/events, to czy moglibyście dodać filtr który sprawdziłby również daty surcharges (coś w stylu "events.date.gte"), czy nie ma opcji?

**Comment by neldh** [comment]
W nawiązaniu jeszcze: po testach wychodzi mi na to, że omawiana sytuacja nie jest wyłapywana przez order/checkout-forms i jedynym sposobem na to, by pobrać dopłaty z np ostatniego dnia, jest odpytywać orders/events, podając from=id ostatniego eventu, które sobie musimy gdzieś zapisać i sprawdzając, czy nie pojawiają się tam nowe zdarzenia. Następnie, jeśli coś nowego się pojawi, powinnismy pobrać konkretnego checkout-forma z orders/checkout-form i jesli w środku jest surcharge, to znaczy, że mamy dopłatę.

Czy jest to jedyne wyjście?

Liczyłem na to, że bede w stanie pobierać dopłaty na zasadzie pobierania listy orders/checkout-forms z ostatniego dnia (lub dwóch) i potem ewentualnie konkretne checkout formy z order/checkout-form wg potrzeb, co znacznie zmniejszaloby liczbe żądań, lecz widzę, że w ten sposob mogę nie dostać informacji o dopłacie ktora przyszła pozniej niz te 2 dni od ktorych pobieram. Gdyby istnial jakiś filtr, obejmujący nie tylko boughtAt ale rownież datę dopłaty, nie byloby tego problemu. Ewentualnie jeszcze przychodzi mi do głowy sortowanie od najnowszego w orders/events, co byloby pomocne (moglbym wylapywac w ten sposob doplaty np z dwoch ostatnich dni w prosty sposob). Można liczyć na wdrożenie czegokolwiek z tego?

**Comment by MartaNowaczyk** [comment]
@neldh rzeczywiście w takim wypadku pozostaje bazować na zdarzeniach. Na ten moment nie planujemy wprowadzenia takich rozwiązań, ale przekazałam twoje uwagi do odpowiedniego zespołu, żeby poznali opisane przez ciebie potrzeby i problemy napotkane podczas integracji przez REST API.
