### ISSUE TITLE
REST API wielowariantowość => pole name

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1164]
PUT /sale/offer-variants/{setId}, czy pole "name" gdziekolwiek jest wyświetlane ? Czy ma to duże znaczenie co tam wpiszemy ?

**Comment by MartaNowaczyk** [comment]
nazwa oferty wielowariantowej - pole "name" jest widoczna tylko dla sprzedającego w zakładce "wielowariantowość" i oczywiście przy pobraniu jej przez API.
