### ISSUE TITLE
Program na PC a redirect_uri - jak najlepiej to rozwiązać

### ISSUE THREAD

**Issue by lcdk2012** [allegro/allegro-api#1165]
Interesuje mnie jakbyście rozwiązali taką sprawę. Mamy napisany od podstaw program do zarządzania sprzedażą ( dla systemu windows oraz android ) m.in allegro na webapi a teraz chcemy to wszystko przenieść na rest api.  Program jest przeznaczony dla wielu użytkowników ( różnych firm ) i zastanawiamy się jak rozwiązać problem z podaniem redirect_uri podczas rejestracji programu na allegro.  Co lepiej?

-  Czy dla każdego kto ma kopię naszego programu tworzyć unikatowy redirect_uri np. "ip serwera/uzytkownik_nr1:port" 

- Czy zastosować jeden adres np "ip serwera:port" po otrzymaniu kodu kod php przekaże ją do np bazy mysql a program komputerowy połączy się z nią i odczyta wartość dla określonego użytkownika.

- Inne propozycje?

**Comment by neldh** [comment]
A nie lepiej zrobić to bez redirect_uri i zarejestrować aplikacje typu DEVICE, skoro to są programy nie-przeglądarkowe (o ile dobrze Cię zrozumiałem)?

**Comment by lukada4100** [comment]
Wszystkiego przenieść na RestApi nie dasz rady, bo nie wszystkie funkcjonalności WebApi działają pod Rest, więc trzeba się przygotować na długi okres że aplikacja będzie łączyła się zarówno po Rest jak i API.
Mam aplikację desktopową i jak dodawałem dla niej komunikację po Rescie to kazdej aplikacji wygenerowalem access token i refresh token i mając to za każdym razem gdy klient się loguje to sam sobie generuje nowy access token, bez konieczności łączenia się z aplikacją webową. Póki co jakoś działa.

**Comment by AleksyZajac** [comment]
Aplikacja typu DEVICE i tak wymaga ręcznej autoryzacji. Jak dobrze rozumiem dokumentację to nie można dokonać autoryzacji bez konieczności ręcznego zalogowania się na stronie.

**Comment by neldh** [comment]
Tak, ale nie wymaga tego na zasadzie przekierowań. Możesz url do weryfikacji wysłać komu trzeba dowolną drogą. On go odpali np na telefonie i voila. Od tej pory twoja aplikacja ma zezwolenie na dzialanie

**Comment by PawelTaberski** [comment]
Tak, zgadza się wszystko opisaliśmy [tutaj krok po kroku](https://developer.allegro.pl/auth/#userDeviceFlow), i pamiętaj że autoryzujesz się tylko raz, potem tylko przedłużasz ważność tokena przy pomocy refresha,

**Comment by lcdk2012** [comment]
> 
> 
> Tak, zgadza się wszystko opisaliśmy [tutaj krok po kroku](https://developer.allegro.pl/auth/#userDeviceFlow), i pamiętaj że autoryzujesz się tylko raz, potem tylko przedłużasz ważność tokena przy pomocy refresha,

Refresh token do odświeżenia mogę wykorzystać w dowolnym momencie np po 36h  czy przed wygaśnięciem tokena podstawowego?

**Comment by PawelTaberski** [comment]
W dowolnym momencie i przed i po wygaśnięciu access-a
