### ISSUE TITLE
Kategorie w środowisku produkcyjnym a środowisko testowe ?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1166]
Witam,
Czy kategorie ze środowiska testowego pokrywają się ze środowiskiem produkcyjnym ?
Czy identyfikatory kategorii są identyczne ?

Dlaczego w środowisku produkcyjnym jest kategoria:

Kultura i rozrywka  / Gitary i akcesoria / Ukulele

a w środowisku testowym jej nie ma ?

Czy oba środowiska są spójne czy każde żyje sobie swoim życiem ?

**Comment by AssAssIn1909** [comment]
Polecam #1139

**Comment by MartaNowaczyk** [comment]
@AleksyZajac jeśli podany przez AssAssIn1909 wątek wszystkiego ci nie wyjaśnia, daj znać.

**Comment by AleksyZajac** [comment]
Dziękuje.
