### ISSUE TITLE
RestAPI / WebAPI - parametry dla kategorii

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1167]
Czy parametry pobierane poprzez WebAPI i RestAPI są takie same ? Czy różnią się np. id ? Czy jestem w stanie wystawiać oferty mając dane na temat parametrów kategorii, które zostały pobrane starym WebAPI ?

**Comment by deneb-k** [comment]
Całkowicie inne, nawet po nazwach niespecjalnie da się zmapować, bo w jednym API masz np. kolor "błękitny", w drugim "odcienie niebieskiego".

**Comment by MartaNowaczyk** [comment]
@pietrach tak jak napisał daneb-k nie wszystko się zgadza. W tej chwili analizujemy różne ID parametrów #1159

**Comment by kieliszek85** [comment]
@MartaNowaczyk czy udostępniacie jakikolwiek zasób pozwalający na zmapowanie starych parametrów (webapi) do nowych (restapi)?
jeden z klientów chciałby migrować do rest api już teraz (a nie na ostatnią chwilę), ale posiada wystawionych kilka tysięcy produktów.... oczywistym jest, że ustawianie wszystkich pól "od zera" jest niewykonalne w sensownym czasie

**Comment by PawelTaberski** [comment]
@kieliszek85  Obecnie jest dostępny tylko jeden zasób do mapowania [dealId i lineItemId](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/). Chwilowo nie planujemy wdrażać ich więcej. Pamiętaj, że zawsze jeśli potrzebujesz skorzystać z jakiś zasobów, których jeszcze nie ma na REST API a są na Web API możesz użyć [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582) w miejscu webapiKey podal Client_ID.
