### ISSUE TITLE
Device flow dla Allegro OAuth // access_token // dostęp do shipping-rates

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1168]
Witam,
Przy próbie dostępu do zasobu shipping-rates używając access_token z Device flow dla Allegro OAuth za każdym razem otrzymuje:

403 Forbidden
Access denied. Please retry, or restart application.

czy coś powinienem załączyć aby mieć dostęp do tej części ?

**Comment by AleksyZajac** [comment]
Witam,
Już sobie poradziłem brakowało powiązania aplikacji z mojego konta z moim kontem.

**Comment by AleksyZajac** [comment]
Jednak mimo powiązania nadal otrzymuje "Dostęp zabroniony. Uruchom ponownie aplikację.".

**Comment by MartaNowaczyk** [comment]
Jak wygląda twój request?

**Comment by AleksyZajac** [comment]
Witam,

Dump reqquesta:

$VAR1 = bless( {
                 '_content' => '',
                 '_uri' => bless( do{\(my $o = 'https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=%7B44108242%7D')}, 'URI::https' ),
                 '_headers' => bless( {
                                        'content-type' => 'application/vnd.allegro.public.v1+json',
                                        'accept' => 'application/vnd.allegro.public.v1+json',
                                        'accept-language' => 'pl-PL',
                                        'authorization' => 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NDk2Njk2MzcsImp0aSI6IjljMDkwMjAxLWNmZjMtNDU5NS04YWZlLWU5ZTdjYTcwNzIzNSIsImNsaWVudF9pZCI6ImE5MmM4NDU1ZWFmYzQwYzNiYWM4MDQxYmM2MzY5YjM5In0.mvuzryycRHJqKhe21DEEo2WN8Y4GsB0GR-K0aJWDD6ne_lL6VVbJH0BJiK3WBE_wr01N2C_j2ciq8XGCLI10jrVqmvYIC8orTSJ8BxW5PyMV97woi5VuInBnyQbV3TrSMO17HTaKZkMgG3FwwiUTvt3C2nPOXBefJ59VD2EqWh_CQcq2-Bs2v2V1KWmwJbFWgw9o3u6Sz4pj3aYMZyd2imrgz50DHNrHqqyn7o4HqqoeJJHRRrxDtsWDrZfC3CNnG29uxVcmPyPLJ6SJmqtef3PKSwyfZqobOWwAqQTxGzj4lpn5ATr-Vbv0VONfVOsILpk414sUZGUDf2CakWNF6A'
                                      }, 'HTTP::Headers' ),
                 '_method' => 'GET'
               }, 'HTTP::Request' );

**Comment by AleksyZajac** [comment]
I druga wersja która też zwraca 403 Forbidden
Access denied. Please retry, or restart application.

$VAR1 = bless( {
                 '_content' => '',
                 '_uri' => bless( do{\(my $o = 'https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=44108242')}, 'URI::https' ),
                 '_headers' => bless( {
                                        'content-type' => 'application/vnd.allegro.public.v1+json',
                                        'accept' => 'application/vnd.allegro.public.v1+json',
                                        'accept-language' => 'pl-PL',
                                        'authorization' => 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NDk2Njk4NTUsImp0aSI6ImEzNDRlNTk5LTFkMmItNGEzMy1iZDQ4LTM0NGU4ZjViNTUwMCIsImNsaWVudF9pZCI6ImE5MmM4NDU1ZWFmYzQwYzNiYWM4MDQxYmM2MzY5YjM5In0.E63-YQaD7uLDCBNRIZiRespOce4DXHWWZIYpHciwTq2cB7ZEYSfp1-TCZWynOOHZS0hI8B09GXBO3PpXNt-6oD0GqBGfBZxMGwE013nMy1Qj4igZAvDV7Hg3GIoiM-rhj1WHEifY50V922cofk-vC2Ctd4pgU5_ySO4tQ4FhLjWtCZmkKHl30ejaWGC4c2_pKKls_JdrcwxTrUVIdnsane4GbCXbzbg033zrdptZvjkE2YyiOEgd_mvTUU3qYhtKBIVuQUpqPk_pcoipJVyzkiocQgWCqGo8EsJS_WGGmXDYFAPxeeqKoYL0MJFEAU9OwRT2qMbLZYWk7OJeeOl_mA'
                                      }, 'HTTP::Headers' ),
                 '_method' => 'GET'
               }, 'HTTP::Request' );

**Comment by MartaNowaczyk** [comment]
Nie korzystasz czasem z autoryzacji client_credentials dla zasobów, które nie potrzebują autoryzacji użytkownika? Aby pobrać cenniki trzeba być zautoryzowany jako sprzedający.

**Comment by AleksyZajac** [comment]
Ok, to jak mam dokonać autoryzacji jako sprzedawca. Cenniki są na moim koncie testowym o nazwie "muzyczny".

**Comment by AleksyZajac** [comment]
Zgodnie z Państwa opisem: https://developer.allegro.pl/auth/ opisują Państwo tylko autoryzację "client_credentials".
Opis jest następujący: "W ramach Allegro OAuth2 udostępniliśmy ścieżkę, dzięki której możesz autoryzować się bez zgody użytkownika na działanie. ".

Inna autoryzacja takiego typy nie jest opisana.

**Comment by MartaNowaczyk** [comment]
@AleksyZajac tak ale to tyczy się tylko zasobów, dla których nie trzeba się autoryzować jako użytkownik np. dla metody GET na zasobie /offers/listing, dla cenników trzeba się zautoryzować czyli skorzystać z authorization code flow lub device code flow.

**Comment by AleksyZajac** [comment]
A może mi Pani jak w device code  lub device code flow może Pani się autoryzować bez konieczności wpisywania loginu i hasła u Was na stronie ?

Brak takiego rozwiązania uniemożliwia całkowite automatyzowanie procesu obsługi zdarzeń w Państwa serwisie aukcyjnym.

Żaden z moich pracowników nie będzie siedział 24/h aby autoryzować się w Państwa systemie...

Nie bardzo rozumie takie podejście. W webapi było to możliwe bez większego problemu...

**Comment by neldh** [comment]
Możesz skorzystać z device flow na takiej zasadzie, że konto zautoryzujesz tylko raz, poprzez wpisanie kodu na stronie allegro (bez przekierowań żadnych - np wyślesz url do logowania na email lub w inny sposób zaalarmujesz kogo trzeba), a potem przy każdym żądaniu (albo np raz na godzinę) będziesz przedłużać ważność tokenów. Tak to powinno wtedy działać w nieskończoność
Da się z tym żyć, choć nie jest to idealne rozwiązanie i wymaga dodania odpowiedniej logiki, która będzie tego pilnować po swojej stronie.

**Comment by PawelTaberski** [comment]
Dokładnie tak jak napisał @neldh informacje jak przedłużać ważność tokena znajdziesz w naszym poradniku [tutaj](https://developer.allegro.pl/auth/#refresh-token).
