### ISSUE TITLE
RestAPI a WebAPI ?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1169]
Witam,
Czy na waszym RestAPI da się uzyskać wszystko to co na WebAPI ?
Chodzi mi o dostęp do danych klienta, do cenników dostaw itd. bez konieczności logowania się fizycznie osoby.

W WebAPI było można uzyskać taką funkcjonalność bez większego problemu.

**Comment by MartaNowaczyk** [comment]
Nie wszystko co było w webAPI znajdziesz w REST. Na pewno nie przeniesiemy możliwości 1:1, ale cały czas rozwijamy REST API i jego zakres będzie się powiększał.

**Comment by AleksyZajac** [comment]
Ale nadal nie odpowiedziała Pani na moje pytanie. Czy da się napisać aplikację która pobiera dane od Państwa bez konieczności fizycznego logowania osoby w  dowolnym GUI ?

**Comment by PawelTaberski** [comment]
Dany user allegro w imieniu którego Twoja aplikacja ma dokonywać zmian na jego koncie musi się zautoryzować tylko raz. Następnie możesz sobie sam odświeżać tokena, bez konieczności ingerencji usera. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/auth/).
