### ISSUE TITLE
[WebApi] Fid 60 i 61

### ISSUE THREAD

**Issue by goliatek86** [allegro/allegro-api#117]
Czemu jak dostaje dane odnośnie pół ( doGetSellFormFieldsForCategory ) 
Dla Allegro Paczkomaty InPost dostaje fid 60.

` [sellFormId] => 60 [sellFormTitle] => Odbiółr w punkcie - Allegro Paczkomaty InPost (pierwsza sztuka) [sellFormCat] => 0 [sellFormType] => 3 [sellFormResType] => 3 [sellFormDefValue] => -1 [sellFormOpt] => 8 [sellFormPos] => 0 [sellFormLength] => 10 [sellMinValue] => -1.00 [sellMaxValue] => 1000000.00 [sellFormDesc] => [sellFormOptsValues] => [sellFormFieldDesc] => 20023 [sellFormParamId] => 0 [sellFormParamValues] => [sellFormParentId] => 0 [sellFormParentValue] => [sellFormUnit] => [sellFormOptions] => 0 )`

Natomiast jak przesyłam koszty wysyłki w fid 60, to na aukcji traktowane to jest jako "Allegro Kurier InPost" które defakto jest jako fid 61 ??

**Comment by KrzysztofLukanowski** [comment]
FID 60, czyli Allegro Paczkomaty Inpost, którą można uzyskać przez doGetSellFormFieldsForCategory , po wystawieniu oferty przez doNewAuctionExt to rzeczywiście ten format przesyłki, dopiero FID 61 to Allegro Kurier Inpost. Przed chwilą przesłałem wartości w FID 60, 160 oraz 260 (odpowiednio: cena pierwszej sztuki, cena kolejnej sztuki oraz ilość w paczce).
