### ISSUE TITLE
[REST] [INPOST] BRAK MOŻLIWOŚCI INTEGRACJI Z ALLEGRO INPOST

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#1171]
Odświeżam temat, ponieważ wszystkie wątki na tym forum dot. tego tematu zostały już po cichu zamknięte ("z braku aktywności w temacie") a problem nadal (o ile mi wiadomo) nie został rozwiązany. 

Dokładniejszy opis problemu jest w tym wątku : https://github.com/allegro/allegro-api/issues/872

**Comment by PawelTaberski** [comment]
Tak jak odpisałem Tobie w #872 
Pracujemy wspólnie nad nowym zasobem w tym miesiącu powinien już być gotowy.
Pisaliśmy o planach m.in. z tym zasobem tutaj #1043

**Comment by aktywnitu** [comment]
> Tak jak odpisałem Tobie w #872
> Pracujemy wspólnie nad nowym zasobem w tym miesiącu powinien już być gotowy.
> Pisaliśmy o planach m.in. z tym zasobem tutaj #1043

Mamy już kwiecień. Kiedy zamierzacie umożliwić zlecanie paczek do InPostu na podstawie danych z REST API?

**Comment by PawelTaberski** [comment]
Zmiana nie jest tylko zależna od nas wiemy o tym problemie i trwają rozmowy z InPostem w sprawie tej zmiany. Mamy nadzieję, że do końca kwietnia uda się definitywnie to rozwiązać.

**Comment by aktywnitu** [comment]
@PawelTaberski, jak tam postępy?

**Comment by PawelTaberski** [comment]
W maju powinno udać się rozwiązać problem. Jak tylko będziemy mieli pewne potwierdzone informacje, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by aktywnitu** [comment]
Powinno? Podobnie jak w kwietniu miałeś nadzięję.

**Comment by PawelTaberski** [comment]
Z informacji jakie na tamten czas otrzymywałem wynikało, że powinno się udać, jednakże okazało się inaczej.

**Comment by MartaNowaczyk** [comment]
@pijablonski  tak jak napisał niedawno Paweł Taberski 
>Jak tylko będziemy mieli pewne potwierdzone informacje, to poinformujemy o tym
