### ISSUE TITLE
/sale/categories - "Full authentication is required to access this resource"

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1172]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] z logowaniem lub autoryzacją

:beetle: **Opis**
Logi: https://gist.github.com/PhotoSoft/9168314c2be7c7116b0c052eec276831

Dlaczego do pobrania kategorii oraz ich parametrów wymagana jest autoryzacja?

**Comment by MartaNowaczyk** [comment]
Dla kategorii i parametrów wystarcza autoryzacja client_Credentials flow.
