### ISSUE TITLE
Przekierowanie do formularza logowania allegro.pl z uzupełnionym użytkownikiem

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1173]
Mam takie pytanie:

Czy da się tak przekierować na formularz logowania allegro.pl, żeby od razu uzupełnić pole na wpisanie użytkownika (jego loginem)?

Przydałoby się, żeby uniknąć sytuacji, gdy ktoś uwierzytelnia aplikację typu DEVICE dla swojego konta, że uwierzytelni ją dla niewłaściwego konta allegro.

Gdybym dał znać użytkownikowi, żeby najpierw zalogował się na konkretne konto allegro.pl i dał linka przekierowującego do formularza z wypełnionym użytkownikiem (oczywiście o ile mam jego login), a w kroku drugim dopiero żeby kliknął na link weryfikacyjny, uniknąłbym nieporozumień.

**Comment by neldh** [comment]
Jeszcze tak dodam: samo wyświetlanie potwierdzenia po akceptacji kodu weryfikacyjnego, że użytkownik jest zalogowany na konto X wydaje się po prostu jednak za mało odporne, bo ludzie mają tendencję do klikania "Dalej" bez czytania, więc wymuszenie zalogowania na konto w pierwszej kolejności wydaje mi się dobrym pomyslem.

Co więcej, widziałem, że czasami wyświetlane jest tam po prostu coś w stylu "Client:1234567". Nie możnaby tego zamienić przynajmniej na mail w takiej sytuacji?

**Comment by FromAnyHole** [comment]
Moim zdaniem błądzisz w lesie... Poczytaj jak realizowane jest tu całe OAuth.

**Comment by PawelTaberski** [comment]
@neldh Client:1234567 jest loginem usera, do czasu aż nie zmieni go na inny. A odnośnie tego co napisałeś , to nie możemy odpowiadać za to, że user nie doczytał komunikatu :-)

**Comment by neldh** [comment]
@FromAnyHole 
Tutaj nie chodzi o oauth... W ogóle to nie chodzi o integrację w tym momencie, tylko o przekierowanie przez link z instrukcji włączenia integracji dla aplikacji typu DEVICE, żeby czasem user nie uwierzytelnił jej nie z tego konta co trzeba. Poza tym na aplikacji typu DEVICE nie zrobisz tego tak jak w tradycyjnym oauth po przekierowaniach, a nam potrzeba DEVICE, bo aplikacja jest stricte backendowa (intstrukcja przychodzi inną ścieżką - trochę by tu tłumaczyć trzeba...)
@PawelTaberski 
Jasne, że nie możemy, ale wiadomo jak ludzie czytają instrukcje.
No niby jest to loginem, ale jest mało czytelne.
W sumie trudno. Poradziłem sobie inaczej. W każdym razie mail obok tego loginu byłby pomocny.

**Comment by PawelTaberski** [comment]
@neldh Rozumiem, przekazałem sugestię, ze w przypadku braku ustawionego loginu (kiedy jest ten automatyczny client123) to warto zamiast niego dać maila, kórego user podał podczas rejestracji konta.
