### ISSUE TITLE
Refresh_token - działa tylko 12 godzin

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#1174]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Zgodnie z instrukcją na stronie ( https://developer.allegro.pl/auth/#refresh-token )  próbuję zrobić token który będzie ważny 3 mc.

Wszystko jest bez błędów tylko że taki odświeżony token jest ważny 12 godzin. W odpowiedzi zawsze dostaję expires_in = 43199 sek.

  ["expires_in"]=>   int(**43199**)
  ["jti"]=>   string(36) "e7a71070-5d7c-4bb5-9ef5-1629ece7275c"

Co trzeba zrobić żeby taki access token działał 3 mc ? Czy używam tokena czy nie to po 12-stu godzinach muszę go generować ponownie.

**Comment by FromAnyHole** [comment]
Hej, poczytaj jeszcze raz o całym mechanizmie przydzielania tokenów, akurat tego żeśmy tu dopilnowali i działa to (zwykle) poprawnie - teraz każdy TOKEN ma ważność do 12 godzin, zapomnij generalnie o innych okresach, to jest w sumie bez znaczenia jakie są deklaracje czasu dla ważności samych refresh-token'ów...

**Comment by AssAssIn1909** [comment]
Access token jest wazny zawsze 12H, a refresh token jest zawsze wazny 3 miesiące. Access token słuzy do dostepu do zasobów, a resfresh token do odświeżenia tego pierwsze.

**Comment by PawelTaberski** [comment]
Pamiętaj również, że przy każdym odświeżeniu otrzymujesz nową parę access i refresh i za każdym razem korzystaj z najnowszego refresha. Za każdym razem zeruje się jego czas ważności także znów ma 3 miesiące (refresh). Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/auth/#refresh-token).

**Comment by Raafal78** [comment]
To dla potwierdzenie czy dobrze rozumiem: 
- Access Token jest ważny 12 h od wygenerowania
- Refresh jest ważny 3 mc.
Jeżeli będę robił migrację klientów i system nie będzie działał  np : 3 dni to nawet jeżeli Access Token już wygasł to nadal mogę użyć Refresh Token żeby przywrócić działanie aplikacji i uzyskać aktualny Access Token ?

**Comment by PawelTaberski** [comment]
@Raafal78 Dokładnie tak i przy każdym odświeżeniu dostajesz nową parę access i refresh w której refresh znów ma ważność 3 miesiące.

**Comment by Onixarts** [comment]
> Pamiętaj również, że przy każdym odświeżeniu otrzymujesz nową parę access i refresh i za każdym razem korzystaj z najnowszego refresha.

Jak w takim razie obsłużyć sytuację, że odświeżanie tokenów się nie powiedzie z winy łącza, timeoutu, obciążenia serwerów Allegro, problemów z zapisaniem nowych tokenów po stronie aplikacji użytkownika itd. Nie ma przecież żadnej gwarancji, że klient otrzyma odpowiedź po wywołaniu odświeżenia tokena. A wtedy stary refresh token przestaje działać i użytkownik musi ponownie autoryzować aplikację w Allegro. Przy wszelkiego rodzaju komunikacjach z serwisami zewnętrznymi pierwsze założenie jest takie, że każdy request może się nie udać... i to na 10 sposobów ;).

Czy jest na to jakieś rozwiązanie? Z naszych obserwacji wynika, że ten problem występuje u użytkowników co jakiś czas.

**Comment by PawelTaberski** [comment]
Jeśli z jakiegoś powodu przepadnie Tobie najnowszy token musisz przejść flow jeszcze raz. Mógłbyś podać jakiś konkretny przykład kiedy to wysłałeś requesta o odświeżenie tokena i nie otrzymałeś nowej pary, a stara przestała działać? Jeśli tak to podeślij proszę takie dane przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1174 na GitHub-ie

**Comment by Onixarts** [comment]
Ja taki problem napotkałem przy implementacji nowej wersji "synchronizatora z API", gdy jeszcze nie mam zapisu tokenów po refreshu. Natomiast nasi użytkownicy okresowo piszą do nas w sprawie wygaśniętego tokena, pomimo, że w starszej wersji programu jest jego odświeżanie i zapisywanie - stąd wniosek, że takie sytuacje mają miejsce, ale złapać ich nie jesteśmy w stanie. Wiadomo tylko, że któreś ogniowo po drodze zawiodło i refresh token nie nadaje się już do niczego. Użytkownik świadomy zrobi ponowną autoryzację, ten mniej świadomym będzie walczył z tematem pół dnia i w końcu do nas napisze. A praca stoi.

Wśród użytkowników aplikacji w danej firmie nie każdy pracownik zna hasła do kont Allegro, więc nawet odświeżenie takiego tokena ręcznie nie zawsze jest takie proste, bo trzeba skontaktować się z kimś kto taki dostęp ma. Są również sytuacje, że w firmach program chodzi 24h/dobę i synchronizacuje tylko maszyna serwerowa. Jak się zatka w nocy, tak do rana nie będzie danych - do póki ktoś tego ręcznie nie popchnie.

Stąd pytanie, czy invalidowanie refresh tokena zaraz po jego użyciu nie jest zbyt restrykcyjne.

**Comment by PawelTaberski** [comment]
Nie przewidywaliśmy zmiany tego flow, a jak byś chciał aby to działało, bo jeśli poprzednia para mimo wygenerowania nowej była by ciągle aktualna mogłoby to spowodować na rozwidlenie ścieżek jakby ktoś teraz na starej parze chciał odświeżyć i na nowej.

**Comment by marcinja2** [comment]
w takim razie zapytam jaki to jest "flow" skoro przy odświeżaniu tokena potrzebny jest redirect_uri. Co mam robić bo mój IP jest zmienny do tego za bramą NAT jest sieć prywatna w której ustawiony jest serwer. Odpowiedź wykupienia stałego ip mnie nie satysfakcjonuje i nie chodzi tu o koszty tylko o właściwe bezpieczeństwo

**Comment by marcinja2** [comment]
Nie chodzi mi o publiczne dane tylko o wystawianie aukcji

**Comment by neldh** [comment]
jak jesteś za NATem, to może DEVICE_FLOW będzie lepszym rozwiązaniem?

**Comment by PawelTaberski** [comment]
@marcinja2 dokładnie jak napisał @neldh możesz skorzystać z [device flow](https://developer.allegro.pl/auth/#DeviceFlow) wtedy nie potrzebujesz redirect_uri.

**Comment by marcinja2** [comment]
Tak device flow jest właściwym rozwiązaniem ale czegoś tu nie rozumiem. nie jest opisane jak odświeżyć token właśnie w tym przypadku

**Comment by marcinja2** [comment]
mam wysłać pole redirect_uri puste?

**Comment by PawelTaberski** [comment]
@marcinja2 Przed chwilą jeszcze przetestowałem i nie wprowadzasz w ogóle parametru redirect_uri

**Comment by marcinja2** [comment]
oki mam nadzieje ze nie strace refresh_tokenu. Ale ile w końcu on jest ważny? raz piszecie ze rok innym razem ze 3 miesiące?

**Comment by PawelTaberski** [comment]
Obecnie 3 miesiące, ale przy każdym odświeżeniu otrzymujesz nową parę access i refresh i zawsze korzystaj z najnowszego i przy każdym odświeżeniu znów ma ważność 3 miesiące. Także nie ma już potrzeby, aby user po jakimś czasie musiał znów się uwierzytelnić.

**Comment by anih** [comment]
Czy po odświeżeniu poprzedni access_token zachowuje ważność? Bo może zdarzyć się, czy to po naszej stronie czy to po stronie allegro, że coś nie zadziała i nowy access_token nie zostanie zapisany albo po prostu nie będzie działać i czy możemy korzystać z poprzedniego?

**Comment by marcinja2** [comment]
musisz od nowa przejść autoryzację tego co czytałem w postach

**Comment by anih** [comment]
No właśnie tego się obawiam, może jednak nieinvalidowanie ostatnich X access_tokenów byłoby ułatwieniem?

**Comment by neldh** [comment]
od niemal miesiąca działam na device flow i aplikacja sama sobie odswieza tokeny i nie mialem do tej pory problemow. Jednakże mam zabezpieczenie, ktore zglosi błąd w wypadku kiedy  tokeny sa nieprawidlowe i poprosi od razu o ponowne uwierzytelnienie, wiec bedzie mozna szybko zareagować.
Moim zdaniem i tak powinnismy miec dłuzsze te czasy aktywnosci tokenow. Przynajmniej dla device flow. Token wazny jest zaledwie 12 h, ale refresh jest juz na 3 mc, a  to tylko niepotrzebnie wymaga ciaglego odswiezania tokenow.

**Comment by marcinja2** [comment]
a wogóle to poco ten cyrk dla sytuacji takiej jak moja gdy piszę aplikację sam dla siebie i dla własnego konta allegro i niepotrzebna mi żadna zgoda od samego siebie ale cóż tego raczej nie przewidziano

**Comment by PawelTaberski** [comment]
Uwierzytelnienie i autoryzacja jest niezbędna m.in. ze względów bezpieczeństwa, z tego powodu również nie przewidujemy wydłużenia czasów ważności access tokenów.

**Comment by neldh** [comment]
@PawelTaberski 
Sęk w tym, że jeżeli aplikacja jest zarejestrowana i powiązana z danym kontem, to bezsensowny wydaje się proces uwierzytelniania tej aplikacji dla tego samego konta, a takie aplikacje też powstają i to zapewne niektórzy mają na myśli.

W takiej sytuacji nikt tak nie robi, żeby wymagać jeszcze uwierzytelniania, skoro sama aplikacja i tak musi być powiązana z danym kontem, a to można zrobić tylko po zalogowaniu się na konto, a chociażby po to, żeby ustawić odpowiednie linki przekierowań (a przynajmniej nie robi tak żadna z wielkich platform, które miałem do tej pory przyjemność integrować, ale może jeszcze wszystko przede mną...)

**Comment by PawelTaberski** [comment]
Teraz rozumiem, chodzi o sytuacje kiedy Tworzę klucz i przy jego pomocy chce na własnym koncie na którym utworzyłem ten klucz dokonywać zmian po API tak? 
Oczywiście wtedy uwierzytelnianie i przydzielanie dostępu wydaje się bezcelowe, ale przydzielenie dostępu na stałe i z automatu takim kluczą do konta jest mało bezpieczne. W przypadku wycieku danych dostępowych każdy mógłby dokonywać zmian na takim koncie.
Pamiętaj, że jeśli chcesz korzystać tylko z danych publicznych to zawsze możesz skorzystać z flow client-credentials.

**Comment by neldh** [comment]
No nie po to się dodaje klucz do własnego konta, żeby korzystać z danych publicznych.

Natomiast jeżeli chodzi o wyciek danych dostępowych to fakt - taka bariera wydaje się dodatkowym zabezpieczeniem. Tylko że jak dane wyciekły to i tak ktoś może wejść mi na konto i mocno napsuć.

Mi bardziej chodziło o to, żeby wasz system nie wymagał autoryzacji tylko w przypadku, kiedy klucz, którego używam jest przypisany do konta od którego chcę informacji (albo lepiej: zapytał się mnie czy ma dożywotnio uwierzytelnić dla mnie tą aplikację, bo jest ona przypisana do mojego konta). Jeżeli natomiast ktoś się uwierzytelnia z nie-swoją aplikacją, to jak najbardziej taki proces powinien istnieć.

W zasadzie nie jest to (przynajmniej dla mnie) jakiś mocny problem, ale wydaje się lekko bezcelowy.

**Comment by PawelTaberski** [comment]
Rozumiem sugestię przekazałem, jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym w dedykowanym komunikacie.

**Comment by anih** [comment]
Czy na własnych kontach jeśli dojdzie do rozpięcia tokena to mogę ponownie autoryzować aplikację automatem, np. wykorzystując selenium? Tzn czy takie sposoby będą blokowane?

**Comment by PawelTaberski** [comment]
Jeśli ograsz sobie po jego stronie autoryzacje i uwierzytelnienie to sądzę, że nie powinno być problemu.
