### ISSUE TITLE
Dziwny Bład przy integracji

### ISSUE THREAD

**Issue by Natsonikk** [allegro/allegro-api#1175]
Witam,
Przy integracji produktow z pewnej hurtowni napotkałem taki błąd, który uniemożliwia mi wystawienie aukcji: "Podany identyfikator nie istnieje. | doNewAuctionExt Given id does not exist". Możliwe, że to coś banalnego ale w takich tematach nie jestem za mocny i nie wiem jak sobie z tym poradzić.
Z góry dziekuje za pomoc :)
Pozdrawiam

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta i responsa w formacie XML przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 1175 na GitHub-ie. 
Ponadto pamiętaj, że 3 czerwca usuniemy tą i inne metody w zarządzania ofertami w WebAPI, o czym informowaliśmy m.in. tutaj #1043.
