### ISSUE TITLE
Dodawanie zdjęć - RestAPI

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1177]
Jeśli będę próbował dodać zdjęcie, które już wcześniej zostało dodane to metoda POST https://upload.allegro.pl/sale/images rozpozna to i zwróci tylko link i datę ważności do zdjęcia czy doda ponownie to samo zdjęcie ?

**Comment by KrzysztofLukanowski** [comment]
Nie wiemy, czy w pliku nie wprowadziłeś jakiejś zmiany, dlatego w takim przypadku zdjęcie dodasz raz jeszcze.

**Comment by pietrach** [comment]
Powinniście robić base64 z zawartości zdjęcia i po tym porównywać i tyle

**Comment by PawelTaberski** [comment]
@pietrach Możesz wielokrotnie dodać to samo zdjęcie i za każdym razem będzie dodane ponownie i otrzymasz inny link i nową datę ważności
