### ISSUE TITLE
ERR_OBLIGATORY_ATTRIB_NOT_SET

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#1178]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Podczas aktualizacji dowolnej aukcji w kategorii Obuwie Damskie/Męskie
zwracany jest błąd o braku wymaganego atrybutu, który w rzeczywistości jest został podany podczas tworzenia aukcji.
Konkretnie chodzi o ID 2083 i 2081 (Materiał zewnętrzny) oraz 20147 (Stan), przypuszczam że system "nie
widzi" żadnych atrybutów podczas walidacji aukcji.
Zauważyłem że metoda DoGetItemFields dla aukcji obuwia nie zwraca żadnych pól powyżej ID 341.

Przykładowy timestamp błędu 2019-02-11T12:06:58+01:00

**Comment by lukada4100** [comment]
Ten sam problem. DoGetItemFieldsRequest nie zwraca fidów powyżej 341.

**Comment by rtnet-pl** [comment]
Mamy to samo, dotyczy change-price-commands

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem, zgłosiłem do zespołu odpowiedzialnemu za te funkcjonalności proszę o cierpliwość.

**Comment by rtnet-pl** [comment]
Podbijam, problem nadal występuje 😥

**Comment by PawelTaberski** [comment]
@rtnet-pl Problem zgłosiłem z dużym priorytetem, jeszcze dałem znać teraz że sprawa pilna. Mam nadzieję że niedługo uda się rozwiązać problem.

**Comment by rtnet-pl** [comment]
@PawelTaberski Czy możesz podać jakieś ramy czasowe kiedy to zostanie naprawione? Bo robi się nerwowo

**Comment by PawelTaberski** [comment]
Jeszcze raz prosiłem o sprawne usunięcie zespołu. który odpowiada za tę funkcjonalność. Niestety nie jestem w stanie podać dokładnego czasu, kiedy uda się im usunąć usterkę.

**Comment by PawelTaberski** [comment]
@rtnet-pl Udało nam się usunąć problem, nie powinien już występować.

**Comment by rtnet-pl** [comment]
Cześć, niestety problem dalej występuje. Podsyłam kilka ofert, które dostałem od Klienta:
7101428715
7788554383
7777727029
7133720629
7785121444
7785402634
7108963097

**Comment by PawelTaberski** [comment]
@rtnet-pl Przekazałem identyfikatory ofert z którymi jest problem, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
@rtnet-pl Otrzymałem prośbę o przykładowego nowego pełnego requesta i responsa. Podeślij proszę te dane przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i zaznacz, że dane są potrzebne do ticketa numer 1178 na GitHub-ie.

**Comment by rtnet-pl** [comment]
@PawelTaberski Wysłałem. Klient zauważył, że komunikat o błędzie się zmienił i obecnie jest to

> Niepoprawna wartość w polu formularza sprzedaży (np. zbyt duża ilość znaków w tytule oferty). Odbiór osobisty w punkcie sprzedawcy (pierwsza sztuka) - fid: 404

Zapewne jest to związane z https://github.com/allegro/allegro-api/issues/1079

Natomiast aplikacja próbuje używać fida 404, ponieważ taki FID zwraca doGetItemFields

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem te informacje, obecnie powoli migrujemy odbiór osobisty zastępujemy go odbiorem osobistym w punkcie sprzedawcy. #1259 
Kwota za pierwszą sztukę powinna wynosić zero tak jak na froncie:
![image](https://user-images.githubusercontent.com/36262735/53498104-ef480480-3aa5-11e9-83a7-cc59cecb1186.png)
