### ISSUE TITLE
Zbyt długa wartość dla parametru Numery katalogowe zamienników(215941).

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#1179]
Próba wystawienia przedmiotu w kategorii Motoryzacja > Części 
samochodowe > Silniki i osprzęt > Recyrkulacja spalin EGR > Zawory EGR 
(255456) kończy się błędem:

Zbyt długa wartość dla parametru Numery katalogowe zamienników(215941).

podczas gdy "Numery katalogowe zamienników" ma id 39623. W tym polu 
przekazywana jest wartość:

NTYEGR-AU-008
EGR-AU-008
038131501AD
5902048037220
038131501BF
038131501BH
7.00365.06.0
700365060
E07-0093
ENT500068

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) swojego pełnego requesta  i responsa w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu dodaj, że informacje są potrzebne do ticketa numer 1179 na GitHub-ie.
