### ISSUE TITLE
WebAPI - doGetSellFormFieldsForCategory zwraca błędną wartość dla fid 26131

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#118]
Metoda WebAPI `doGetSellFormFieldsForCategory` dla kategorii `250442` zwraca fid `26131` (_Strona zabudowy_) jako opcjonalny (`sellFormOpt == 8`) podczas gdy faktycznie parametr ten jest wymagany

**Comment by KrzysztofLukanowski** [comment]
Parametr jest wymagany podczas wystawiania oferty przez GUI, przez WebAPI będziemy go wymagać od 9 kwietnia. Zgodnie z informacją na stronie o [zmianach w parametrach](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).
