### ISSUE TITLE
Odpowiednik doGetItemsInfo w REST API

### ISSUE THREAD

**Issue by mtumtu** [allegro/allegro-api#1181]
Witam.

Mam ID oferty. Chciałbym pobrać szczegółowe informacje o tej ofercie. 
W WebAPI robiłem to za pomocą doGetItemsInfo.
Jak zrobić to za pomocą REST API ?
"https://api.allegro.pl/offers//listing" nie daje (?) możliwości wyszukiwania po ID oferty.

**Comment by PawelTaberski** [comment]
W przypadku zasobu do listingu nie możesz odpytać o konkretną ofertę. Dokładne dane o danej ofercie pobierzesz przy pomocy zasobu [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)

**Comment by mtumtu** [comment]
Przy próbie użycia "GET /sale/offers/{offerId}" dostaję:

{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "Forbidden",
            "details": null,
            "path": "/sale/offers/7669501936",
            "userMessage": null
        }
    ]
}

**Comment by PawelTaberski** [comment]
Sprawdź czy nie używasz tokena uzyskanego przy pomocy autoryzacji client-credentials jest on przeznaczony tylko dla zasobów publicznych. W przypadku tego zasobu powinieneś użyć flow code albo device.

**Comment by mtumtu** [comment]
Pewnie w tym tkwi problem.
Używam tego samego tokena jak przy "GET https://api.allegro.pl/offers//listing"

Ale można używać "GET /sale/offers/{offerId}" dla nie swojej aukcji ?

**Comment by PawelTaberski** [comment]
Nie, ta metoda służy tylko do pobrania ofert, które należą do usera na którego masz token. Nie możesz pobrać nie swoich ofert.

**Comment by mtumtu** [comment]
W taki razie wracamy do punktu wyjścia:

Mam ID oferty (nie swojej). Chciałbym pobrać szczegółowe informacje o tej ofercie.
W WebAPI robiłem to za pomocą doGetItemsInfo.
Jak zrobić to za pomocą REST API ?

**Comment by PawelTaberski** [comment]
Jeszcze w REST API nie ma takiej metody, jak tylko wdrożymy takie rozwiązanie to poinformujemy o tym w dedykowanym komunikacie. Jeśli potrzebujesz takie informacje pozostaje obecnie korzystanie z WebAPI.

**Comment by mtumtu** [comment]
Chętnie korzystałbym dalej z WebAPI, ale 1 kwietnia ma zniknąć doGetItemsList, więc i tak muszę się przesiąść na REST. Rozumiem, że zanim wygaszone zostanie doGetItemsInfo pojawi się REST-owy odpowiednik tej funkcji ?

**Comment by PawelTaberski** [comment]
Nie jestem w stanie tego zagwarantować, ale jeśli chodziło Tobie o konkretną ofertę to możesz korzystać z [doShowItemInfoExt ](https://allegro.pl/webapi/documentation.php/show/id,342). podobne funkcje jak doGetItemsList daje GET /offers/listing.
