### ISSUE TITLE
[REST] OfferRepository error

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#1182]
Dzień dobry 
status: FAIL
info: OfferRepository error 

przy próbie wznowienia oferty ze statusu ENDED

pozdrawiamy wwwfactory

**Comment by wwwfactory** [comment]
id 7813554431
może się przyda

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i trace-id. W zgłoszeniu prosze napisac, że dane sa potrzebne do ticketa numer 1182 na GitHub-ie. Sprawdzimy w czym jest problem.

**Comment by wwwfactory** [comment]
Oferta trafia do publikacji i otrzymuje status NEW. do tego momentu żadnych błędów.
Po kilku minutach po sprawdzeniu statusu pojawia się OfferRepo Error.
To już się zdarzyło nie tylko u nas...

**Comment by wwwfactory** [comment]
Operacja z dnia 2019-02-11  20:50:58 id oferty: 7813554431
UUID: 12f99324-f523-48da-b6b4-5cce2e7b84e2 w kategorii: 255099
to wystarczy ? 
/sale/offer-publication-commands/12f99324-f523-48da-b6b4-5cce2e7b84e2/tasks

**Comment by PawelTaberski** [comment]
@wwwfactory Prosiłbym jednak o podesłanie przez nasz formularz kontaktowy pełnego cURL-a wraz z responsem z zasobu GET /sale/offers/{offerId} sprawdzimy w czym jest problem.

**Comment by wwwfactory** [comment]
to potrwa, na produkcji nikt nie budował systemu logowania, co jak widać w przypadku Allegro nie ma uzasadnienia. 
tymczasem następne aukcje mają RepoError.

**Comment by PawelTaberski** [comment]
To bardzo przyspieszy wykrycie problemu, przede wszystkim jeśli to możliwe podeślij trace-id zadania publikacji oferty.

**Comment by wwwfactory** [comment]
Okey, mamy już pełne logowanie na produkcji z detalami o które pytacie. 
Dodam że dziś sytuacja wygląda inaczej, 
po zleceniu publikacji oferty, nie pojawiają się błędy RepoError, aukcja po prostu trafia  z NEW w status ENDED.
zaraz podeśle via formularz...

taka sytuacja
pozdrawiamy wwwfactory

**Comment by wwwfactory** [comment]
Przepraszam - nadal OfferRepository error

**Comment by PawelTaberski** [comment]
Problem zgłosiłem z dużym priorytetem, więc mam nadzieję że w miarę szybko da się go usunąć. Proszę o cierpliwość.

**Comment by FreelinePL** [comment]
Czy wiadomo coś? Mamy podobny problem. Za którymś razem przejście oferty zakończonej w ACTIVATE udaje się. Ale jest to na prawdę rzadki przypadek.

**Comment by PawelTaberski** [comment]
@FreelinePL Podeślij proszę trace-id przypadków aktywacji oferty które się nie powiodły.

**Comment by FreelinePL** [comment]
W /sale/offer-publication-commands/{commandId}/tasks jest status NEW i po niedługim czasie jest FAIL OfferRepository error.

**Comment by deneb-k** [comment]
Dodam, że ofert z OfferRepository error nie da się aktywować też przez panel Allegro, to nie tylko w API siedzi. Zgłaszałem kiedyś ten błąd przez formularz. Doszedłem tam wtedy do tego, że jeden z cenników dostaw nie działa - jak go przypiszę do oferty, to mam właśnie OfferRepository error. Sprawa zakończyła się niczym, przestano mi odpisywać.

API lubi też w nocy rzucić tym błędem. Np. między 01:00 a 01:02 wszystkie próby aktywacji się wysypują. Ponowienie po kilku minutach "rozwiązuje" problem.

Mam wrażenie, że to taki odpowiednik Internal Sever Error z WebAPI, musimy się przyzwyczaić ;)

**Comment by PawelTaberski** [comment]
@FreelinePL  Podeślij tak jak pisałem trace-id zadania publikacji takiej oferty ( PUT /sale/offer-publication-commands/{commandId}), sprawdzimy w czym jest problem.

**Comment by PawelTaberski** [comment]
@deneb-k Co rozumiesz prze cennik nie działał? Przypisany do oferty cennik został usunięty?

**Comment by FreelinePL** [comment]
request:
{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"7843478640"}],"type":"CONTAINS_OFFERS"}]}

response:
{"id":"7430b731-0e8c-4f04-b7da-b4fb4974595d","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by deneb-k** [comment]
Mam utworzony taki sobie testowy cennik, w którym uzupełniłem wszystko co się dało. Po prostu oferta, w której go użyję, nie chce się aktywować (ani przez API, ani przez panel) i rzuca OfferRepository error. Po zmianie cennika na inny jest ok. Błąd w pełni reprodukowalny, przetestowałem przed chwilą - nadal istnieje.

Cennik 9b0ca2a0-133c-40be-a869-f037bf103606, Ticket#1254259552 z 4 grudnia.

**Comment by FreelinePL** [comment]
zeby bylo smieszniej dla tego co poniżej

{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"7843478640"}],"type":"CONTAINS_OFFERS"}]}

{"id":"868d5d78-c277-4dd6-bd17-b3caa2bcbbba","taskCount":{"total":0,"success":0,"failed":0}}

przeszło przed chwilą nie wiedzieć czemu, po kilkunastu albo kilkudziesieciu probach :D

**Comment by PawelTaberski** [comment]
@deneb-k Ciekawa sprawa. Podeślij proszę [przez formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) id sprzedawcy na jakim masz ten cennik. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 1182 na GitHub-ie

**Comment by PawelTaberski** [comment]
@deneb-k Otrzymałem Twoje dane i przekazałem, do zespołu odpowiedzialnego za tą usługę, aby sprawdzili rozwiązali tą sprawę z tym cennikiem.

**Comment by PawelTaberski** [comment]
@wwwfactory Problemem w tej ofercie jest fakt, że do oferty zostało puszczone zadanie publikacji, a zanim zdążyła się wystawić wysłałeś requesta o jej zakończenie. Obecnie nie da się wznowić już takiej oferty. Planujemy pracę, aby zapobiega takim sytuacją.

**Comment by FreelinePL** [comment]
A czy z moim problem, który zgłosiłem wyżej, to coś wiadomo?

**Comment by PawelTaberski** [comment]
@FreelinePL Podeślij proszę pełnego cURL-a i trace-id najnowszych przypadków przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) i zaznacz, że informacje są potrzebne do zgłoszenia numer 1182 na GitHub-ie. Pierwszy problem udało się wyśledzić, jednakże jeśli u Ciebie dalej występuje ten problem przyczyna musi być inna.

**Comment by FreelinePL** [comment]
Ok, czyli przypadek "wwwfactory" tu miał zastosowanie? Póki co nie mam nowszych zdarzeń tego typu. Jak się pojawią, to podeślę.

**Comment by PawelTaberski** [comment]
Udało nam się wychwycić tamten problem i rozwiązać sądziłem że u Ciebie problem dalej występuje i dlatego pytasz. Wtedy byłaby to inna przyczyna. Daj znać jeśli problem u Ciebie się powtórzy i podeślij nam wtedy te informacje o których pisałem.
