### ISSUE TITLE
doChangeItemFields => stan magazynowy

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1183]
Czy dalej w metodzie **doChangeItemFields** trzeba dla fid = 5 przekazywać ilość magazynową + ilość złożonych ofert ? Bo jakoś są problemy ostatnio

**Comment by PawelTaberski** [comment]
Tak dokładnie jest to ilość sprzedanych sztuk przez cały okres życia oferty + ilość magazynowa.

**Comment by pietrach** [comment]
A ta metoda doChangeQuantityItem ? Tutaj też trzeba przekazywać ilość magazynową + ilość złożonych ofert ?

**Comment by PawelTaberski** [comment]
Tak, natomiast w REST API podajesz już tylko docelową ilość przedmiotów i nie patrzysz na to ile się sprzedało. Chcesz wystawić 5 podajesz 5 nie jest istotne, że np kiedyś już sprzedałeś  10 sztuk na tej ofercie.
