### ISSUE TITLE
Obsługa zamówień przez REST API i wysyłka trackingu przez WebAPI.

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#1184]
Pogodzona z faktem, że najpierw wygaszacie zanim napiszecie zabrałam się do przenoszenia na REST API.

Planowałam zgodnie z [dokumentacją]( https://developer.allegro.pl/orders/) pobrać dziennik, zamówienia i wszystkie potrzebne dane, bo mechanizm jest dość podobny do WebAPI, ale nie wiem jak potem miałabym dodać tracking do zamówienia.

W jaki sposób w REST API uzyskać "transactionId" potrzebny w WebAPI do metody [doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744)?

**Comment by PawelTaberski** [comment]
Zasoby do obsługi zamówień są jeszcze w wersji beta wygaszamy inne metody, które się pokrywają funkcjonalnościami i są już w wersji public. Tak jak pisalismy tutaj #1043 . Obecnie nie ma jeszcze metody do wysyłania numerów przesyłek, ale jeszcze w tym miesiącu ma się pojawić w REST API. Numeru transactionId nie otrzymasz przez REST API.

**Comment by neldh** [comment]
Jest może znana planowana data wdrożenia tego zasobu do REST?

**Comment by PawelTaberski** [comment]
Dokładnej daty jeszcze niestety nie znamy, jednakże możliwe że jeszcze w tym tygodniu. Jednakże nie mogę tego zagwarantować.

**Comment by kamilak23** [comment]
Jestem w tej samej sytuacji. Przeniosłam całą integrację z WebApi na REST API po czym  okazało się że nie mogę nadać etykiety bo nie posiadam allegro_transaction_id
Czekam z niecierpliwością!!!!!

**Comment by PawelTaberski** [comment]
Dostałem informacje, że zasób do dodawania numerów przesyłek ma być wystawiony na początku przyszłego tygodnia.

**Comment by pietrach** [comment]
To co dzisiaj się uda udostępnić tą metodę ? :-)

**Comment by PawelTaberski** [comment]
Powinna dziś się pojawić dedykowany zasób w REST API. Jak tylko wdrożymy to również poinformujemy o tym w dedykowanym komunikacie.

**Comment by PawelTaberski** [comment]
I jest #1217 :-)

**Comment by mjag8** [comment]
Nawiązując do "transactionId"...

W menu Allegro finanse -> Lista moich wypłat można pobrać zestawienia transakcji dla różnych okresów.
Wszystko fajnie, tylko że w wygenerowanym zestawieniu dostajemy transakcje, dla których kluczem jest "stary" "transactionId", którego nijak nie da rady powiązać z checkoutForm.id, payment.id, "starym" "dealId", czy czymkolwiek innym. Czy jest jakaś inna możliwość?

**Comment by PawelTaberski** [comment]
Pracujemy nad wdrożeniem takiego zasobu na REST. niestety nie wiem kiedy on pojawi się publicznie.
Jeśli chodzi o samo mapowanie obecnie dostępny jest jeden zasób do mapowania dealId i lineItemId. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/).

**Comment by mjag8** [comment]
Mapowanie dealId i lineItemId w tym przypadku nie jest użyteczne, będę czekał na nowe zmiany w takim razie
