### ISSUE TITLE
doChangeItemFields -> zmiana kategorii

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1185]
Czy dalej w WebAPI obowiązuje zasada, że 12h po wystawieniu aukcji nie można zmieniać kategorii w ofercie ?

**Comment by PawelTaberski** [comment]
Tak, jednakże pamiętaj, że powoli wychodzimy z WebAPI o czym pisaliśmy tutaj #1043

**Comment by pietrach** [comment]
Wiem, że wychodzicie ale to wszystko nie jest takie proste żeby przejść na nie w tak krótkim czasie

**Comment by darimshae** [comment]
A co w przypadku, kiedy allegro rozbiło jedną kategorie na 5 podkategorii i stare aukcje wpadły do złej podkategorii? Można jakoś zmienić kategorie starych aukcji na allegro?

**Comment by PawelTaberski** [comment]
Możesz zmienić kategorie do 12 godzin od publikacji, w ofertach bez złożonych ofert kupna.
