### ISSUE TITLE
Moje zakupy (my orders)

### ISSUE THREAD

**Issue by fero-sk** [allegro/allegro-api#1186]
Hello,
is it possible to get my orders (Moje zakupy) in REST API (or WebApi)?
The orders are on this address https://allegro.pl/dashboard/myorders/#/
Thank you for your response.

**Comment by PawelTaberski** [comment]
You can use this method [doGetMyWonItems](https://allegro.pl/webapi/documentation.php/show/id,1270)

**Comment by fero-sk** [comment]
Thank you. I can try it. But the problem is, that on that Allegro account we don't have old WebApi key...
It would be better if it worked in new REST API...

**Comment by PawelTaberski** [comment]
Now we don't have that option in REST API, but you can use access token to get retrieve an allegro session by method [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101602)

**Comment by fero-sk** [comment]
OK, but the webapiKey is required (with doLoginWithAccessToken)... How to get it now?

**Comment by PawelTaberski** [comment]
You can enter there Client ID now this is the same as WebAPI Key.

**Comment by fero-sk** [comment]
Fine. It works. Thanks... But there are 2 more problems with "doGetMyWonItems"...
1. cannot sort by date/time of purchase, not even view the date and time
2. cannot get address of the seller (sprzedający - adres), not even with "doShowUser"

**Comment by PawelTaberski** [comment]
Please send us full complete request and response in XML format[ via the contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) we will check what is the problem. Mark in the application that it concerns the ticket number 1186.

**Comment by usteile24** [comment]
Hi there,
Kindly I want to know how can I use "doGetMyWonItems" is new api ?
Thank you

**Comment by MaciejFrackowiak** [comment]
@usteile24 In the REST API we do not have resources to support the [Purchase History](https://allegro.pl/moje-allegro/zakupy/kupione) tab.
