### ISSUE TITLE
Sandbox aktywacja konta

### ISSUE THREAD

**Issue by bherczyk** [allegro/allegro-api#1188]
Dzień dobry,
proszę o aktywacje konta w Sandbox
mail: support@sellbee.pl
login: support_sellbee

Pozdrawiam

**Comment by PawelTaberski** [comment]
Jesteś pewny, że podajesz właściwy login i maila bo nie widzę takiego usera na środowisku testowym

**Comment by bherczyk** [comment]
Przepraszam, faktycznie przez pomyłkę konto zostało stworzone na allegro.

Teraz jest już stworzone na środowisku testowym. Dane takie same:
mail: support@sellbee.pl
login: support_sellbee

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto, aby zakończyć proces podeślij do nas w zakładce moje konto jakieś dowolne dwa pliki.

**Comment by pawellen** [comment]
@PawelTaberski Poprosze o aktywacje konta:
userId | "44048588"
userName | "pawel"

W nawiązaniu do poprzednich odpowiedzi "aby zakończyć proces podeślij do nas w zakładce moje konto jakieś dowolne dwa pliki" nie bardzo widzę tam opcji aby takie pliki podsyłać - chyba że opcja dopiero się pojawi po Państwa akcji.

**Comment by PawelTaberski** [comment]
@pawellen Aktywowałem Twoje konto, podesłanie plików jest potrzebne przy koncie firma, ty założyłeś zwykłe także nie trzeba.
