### ISSUE TITLE
ID transakcji / numer obcy

### ISSUE THREAD

**Issue by danmckp** [allegro/allegro-api#1189]
otrzymujemy cos takiego da527913-2ee4-11e9-96be-8fed05773a34 
ten numer nie mozna przypisac do niczego czy mozna pobrac inny numer w restapi dla zamowienia po ktorym jakos w panelu bedziemy mogli znalezc dana transakcje lub wystapic o zwrot prowizji po tym numerze ?

**Comment by PawelTaberski** [comment]
Obecnie jest dostępny jeden zasób do [mapowania dealId i lineItemId](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/). Jednakże większość numerów w REST API jest już w nowym formacie.

**Comment by mjag8** [comment]
Daną transakcję wartałoby znaleźć po id transakcji, dealId mało tu daje niestety

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię do zespołu, który pracuje nad tymi zasobami, jeśli zdecydują się wdrożyć takie rozwiązanie, to poinformuję o tym w dedykowanym komunikacie.
