### ISSUE TITLE
Jaki URL jest akceptowalny przy rejestracji Aplikacji ?

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#119]
Chcę zarejestrować apkę w sanbox na moim lokalnym srodowisku gdzie pracuje z URL app.test, ale nie mogę zarejestrować takiej apki

![image](https://user-images.githubusercontent.com/6499144/38416402-e19df4c4-3994-11e8-9e49-721c07e2c904.png)

Jakiś workaround ?

**Comment by KrzysztofLukanowski** [comment]
Jeżeli testujesz, proponuję wprowadzić http://app.localhost, ew. http://app.localdomain.
