### ISSUE TITLE
oferty kończą się samoczynnie po sprzedaży pomimo dostępności

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#1190]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X ] inny

:beetle: **Opis**

Oferty zakańczają się same po sprzedaży, pomimo dostępności

przykład:
oferta numer : 7832582245 
sprzedaż nastąpiła: 2019-02-12 godzina 17:57:11 (sprzedała się 1 sztuka z 3 dostępnych)
25 sekund później tj 2019-02-12, 17:57:36 otrzymujemy wiadomość mailową , że oferta zostąła zakończona

przez te 25 sekund nie było żadnego działania użytkownika, program komunikujący się przez API Rest był wyłączony, nie było również logowania na panelu webowym.

**dzieje się tak z każdą kolejną ofertą w której nastąpiła sprzedaż**

jaka jest przyczyna automatycznego zamykania ofert?

**Comment by PawelTaberski** [comment]
@dostawcaopon Sprawdziłem i nie widzę w logach nic niepokojącego, napisałeś, że kolejny raz przy jakich jeszcze ofertach i kiedy zauważyłeś taki problem.

**Comment by dostawcaopon** [comment]
proszę, sprzedaż z przed chwili

oferta 7620306450
2019-02-13 godz. 12:12:52 sprzedała się jedna sztuka z trzech
2019-02-13 godz. 12:14:38 przychodzi od Was wiadomość o zakończeniu sprzedaży

nie zakańczaliśmy tej oferty ani poprzez API, ani ręcznie przez panel WWW
dlaczego oferta się zakończyła?

**Comment by dostawcaopon** [comment]
problem dotyczy wszystkich ofert, w których była sprzedaż

jeśli np wzowię przez REST zakończoną ofertę, w której była sprzedaż, ale są nadal dostępne sztuki
to owszem, oferta się wznowi, ale po kilku-kilkunastu minutach sama, bez naszej ingerencji się zakończy

**Comment by PawelTaberski** [comment]
Zgłosiłem sprawę do dokładnej weryfikacji przez osoby odpowiedzialne za ta usługę, proszę o cierpliwość.

**Comment by dostawcaopon** [comment]
kolejna sprzedaż sprzed chwili i ten sam problem
oferta 7620307542
sprzedała się jedna sztuka z trzech, po chwili oferta sama się zakończyła, bez naszego udziału
tak tylko dodaję dla statystyki, żeby było wiadomo, że problem jest powtarzalny

**Comment by PawelTaberski** [comment]
Przekazałem również te dane do zadania.

**Comment by dostawcaopon** [comment]
Wygląda na to, że naprawiliście, oferty w których była sprzedaż, przestały się zakańczać się bez powodu.

**Comment by dostawcaopon** [comment]
a jednak nie naprawione, pół godziny temu wszystkie oferty w których była jakakolwiek sprzedaż zakończyły się bez powodu (jakieś 1500 ofert)

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, proszę o cierpliwość.

**Comment by marcinja2** [comment]
i co w końcu? jest jakiś progres?

**Comment by PawelTaberski** [comment]
@dostawcaopon  Sprawdziliśmy i udało się wyśledzić powód zamykania ofert, przykładowo dla oferty 7832582245
otrzymaliśmy request o zakończenie offerty o godzinie 2019-02-12 17:57:37.323
/sale/offer-publication-commands/e0c26d82-d130-45fb-8db0-e74126ca9b02
