### ISSUE TITLE
/sale/loyalty/promotions - błąd pobierania ofert z offsetem powyżej 19900

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1192]
Występuje problem: 
 - [x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Problem był opisany w tym wątku:
https://github.com/allegro/allegro-api/issues/812

ale do dzisiaj nie został rozwiązany.
A tak na marginesie, to może by było warto podać informację dodatkową w ofertach pobieranych przez
/offers/listing, dotyczących, czy dana oferta jest powiązana z jakąś inną i podać uuid takiej oferty, oczywiście tylko tej, która ma flagę PromotionEntryPoint=true, wtedy można by było wyszukać takie oferty po listingu, który działa.
Bo w tej chwili nie mam żadnych możliwości zmodyfikowania oferty "kup w zestawie", no chyba, że zawrze się w tych 20000 tysiącach, które mogę pobrać, bo filtru żadnego też nie ma do dyspozycji.

**Comment by PawelTaberski** [comment]
Zespół odpowiedzialny za tą usługę pracuje nad zwiększeniem limitu. Zwiększyłem priorytet zadania, mam nadzieję, że niedługo uda się rozwiązać problem, proszę jeszcze o trochę cierpliwości.
