### ISSUE TITLE
ERR_IP_LIMIT_EXCEEDED Stare API

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#1193]
W wyniku błędu na serwerze doszło do wielokrotnych odpytań waszego starego API (WEBAPI). Jak zdjąć blokadę poprzez www - https://allegro.pl/blocked/index.php, kiedy requesty wykonywane są z poziomu serwera?? Jest jakieś sensowne rozwiązanie?

**Comment by PawelTaberski** [comment]
Aby zdjąć blokadę, ustaw serwer proxy na swojej maszynie z zablokowanym IP i z tego serwera, wypełnij CAPTCHA pod adresem: http://allegro.pl/blocked/index.php. Więcej o limitach i jak zdjąć blokady znajdziesz [tutaj](https://allegro.pl/webapi/faq.php#faq_1).

**Comment by mjag8** [comment]
A przez formularz kontaktowy, coś, gdzieś, sensowniej?
Tak jak tutaj: https://github.com/allegro/allegro-api/issues/1156
