### ISSUE TITLE
Wymagane cenniki dostawy przy wznawianiu aukcji

### ISSUE THREAD

**Issue by adamzimnyy** [allegro/allegro-api#1194]
W opisie wznawiania aukcji https://developer.allegro.pl/my_offers/#6 podana jest informacja: 

> Poza tym do pierwszej połowy 2019 roku możesz edytować i wznawiać oferty bez cennika dostawy. Po tym terminie będzie to obowiązkowe - jak w przypadku wystawiania nowych ofert.

Czy ten wymóg jest już aktywny? Lub jeżeli nie, to czy jest znana dokładna data od kiedy będzie?

**Comment by PawelTaberski** [comment]
Jeszcze jest możliwość edycji ofert bez przypisanych cenników, tak jak w komunikacie w pierwszej połowie roku 2019 będzie to jeszcze możliwe. Jak tylko będziemy znali konkretny termin wygaszenia takiej możliwości, to poinformujemy o tym w dedykowanym komunikacie.
