### ISSUE TITLE
Odpowiednik doGetSiteJournal

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#1195]
Witam
Czy jest jakaś funkcja analogiczna do doGetSiteJournal bo do doGetSiteJournalDeals jest, a mi chodzio to by dowiedzieć się, o zdarzeniu że jakaś aukcja np. wystawiona z opóźnionym startem zmieniła status na aktywny lub inny

**Comment by PawelTaberski** [comment]
Status oferty po jej opublikowaniu, bądź zakończeniu sprawdzisz przy pomocy zasobu /sale/offer-publication-commands/{commandId}/tasks
Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/sale/#step-10-tasks).

**Comment by WGRINGO** [comment]
OK tylko jak klient będzie miał np 1000 aukcji, część będzie oczekujących, cześć aktywnych a część zakończonych  to jak potem w programie będzie mógł sprawdzić, które aukcje zmieniły status? W przypadku doGetSiteJournal można było się dowiedzieć, które aukcje się zmieniły, a teraz nie ma jak to osiągnąć.

**Comment by PawelTaberski** [comment]
Teraz rozumiem, chodzi Tobie o już aktywowane oferty, wtedy możesz użyć GET na zasobie /sale/offers i ustawić odpowiednie filtry, więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/my_offers/).

**Comment by WGRINGO** [comment]
Niby ok ale nie do końca ;)
Proszę o rozwianie moich wątpliwości - np. sytuacja taka, że ktoś zajmujący się aukcjami po tygodniu nieobecności chce zaktualizować u siebie informacje o obsługiwanych przez siebie aukcjach (a ma ich nawet 1000) by sprawdzić, które już są aktywne, które się zakończyły itd. Podanym rozwiązaniem da się to zrobić ale trzeba odpytać w tym momencie za każdym razie wszystkie aukcje jakie się ma.
A mi chodziło raczej o coś takiego jak w przypadku zdarzeń w zamówieniach - funkcje
/order/events oraz  /order/event-stats , dzięki którym wystarczy tylko odpytać tylko to co się faktycznie zmieniło od ostatniego razu. Taką funkcję robiło właśnie doGetSiteJournal. Rozumiem, że w RESTapi już czegoś takiego dla aukcji nie ma i jest tylko dla zdarzeń-zamówień?

**Comment by PawelTaberski** [comment]
W REST API nie ma czegoś takiego jak dziennik na ofertach tzn. abyś miał taką listę zmian typu wystawienie oferty, zakończenie oferty. Jednakże tak jak pisałem na zasobie sale/offers możesz to ograć podobnie filtrami.

**Comment by WGRINGO** [comment]
Ok dziękuję za wyjaśnienia.

**Comment by pietrach** [comment]
Ewidentnie brakuje **doGetSiteJournal** bo jak na bieżąco pobierać informacje np. o ostatnio zakończonych aukcjach ? Brakuje metody z filtrem **changeDateFrom**, **changeDateTo** gdzie było by odpowiednikiem daty ostatniej zmiany w aukcji a zmiana mogła być taka:
 
- rozpoczęcie oferty,
- zakończenie oferty,
- złożenie oferty kupna, 
- zmiana w ofercie, 
- odwołanie oferty kupna,

**Comment by PawelTaberski** [comment]
Dodaj proszę taką sugestię do wątku #1191 gdzie zbieramy informacje co byłoby przydatne/pomocne do szybszego przejścia na REST API.

**Comment by PrzemyslawLukanowski** [comment]
Odpowiednikiem metody doGetSiteJournalDeals jest zasób [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET). Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#02).
