### ISSUE TITLE
"error":"invalid_grant","error_description":"Invalid refresh token: 

### ISSUE THREAD

**Issue by darekwaw** [allegro/allegro-api#1198]
Witam

Dostaję błąd którego treść przytoczyłem w temacie.
Nie jestem już pewien czy używaj "ostatniej" pary kluczy

Czy jest jakaś możliwość by uzyskać nową parę kluczy refresh_token i access_token ?

**Comment by AssAssIn1909** [comment]
Jedynym wyjściem jest chyba tylko przejście autoryzacji od początku

**Comment by PawelTaberski** [comment]
@darekwaw Tak, jak napisał @AssAssIn1909 w takim wypadku musisz jeszcze raz przejść całe flow.

**Comment by darekwaw** [comment]
Ok dzięki Wam za odpowiedź
