### ISSUE TITLE
Przypisywanie external.id za pomocą REST API

### ISSUE THREAD

**Issue by ChrupekV2** [allegro/allegro-api#1199]
Witam,
Czy istnieje lub jest planowana w przyszłości metoda przypisywania sygnatur za pomocą REST API?
W dokumentacji doszukałem się jedynie metody GET.
Pozdrawiam,
Jacek

**Comment by PawelTaberski** [comment]
Już możesz to zrobić do tego służy pole external, możesz przypisać wartość w ofercie jak poniżej:
```
    "external": {                               -- niewymagany, zewnętrzny ID,
        "id":"4131asdsad40011"                  który nadaje sprzedający, np. aby powiązać ofertę 
                },                              z produktem w swoim magazynie. Możesz wprowadzić 
                                                tutaj dowolny ciąg znaków - będzie on dostępny 
                                                również po wznowieniu oferty.
```
Więcej na ten temat znajdziesz w[ naszym poradniku](https://developer.allegro.pl/sale/#new-offer).

**Comment by ChrupekV2** [comment]
Dziękuję za odpowiedź, działa. Szkoda tylko, że razem z sygnaturą należy puścić cały zestaw informacji, co przy kilkunastu tysiącach aukcji komplikuje sprawę. Czy ma ktoś sprytną metodę na obejście tego albo chociaż pobranie danych aukcji do pliku aby móc je potem edytować?

**Comment by PawelTaberski** [comment]
Są dostępne grupowe edycje, ale nie do externala i tu by się nie sprawdziło bo grupowo przypisuje się jedną wartość :-) Niestety pozostaje edycja pojedynczo ofert.
