### ISSUE TITLE
Aplikacja Server Side z użyciem REST

### ISSUE THREAD

**Issue by haloween** [allegro/allegro-api#12]
W jaki magiczny sposób mam korzystać z API z użyciem REST dla apek server side ?
Po co całe API key i access tokeny skoro nie ma tego jak wykorzystać ?

**Comment by awronski** [comment]
@haloween Da radę, ale miło nie jest. Ja korzystam, ale przekazuje swojej apce access tokena, a potem apka sama tylko go odświeża i działa server side.

Upierdliwe.

**Comment by haloween** [comment]
@awronski no tak, ale to jest jakaś partyzantka :)

**Comment by awronski** [comment]
@haloween jak jesteś hardcorem to możesz pobierać access tokena korzystając z Chrome Headless i [Puppeteer](https://github.com/GoogleChrome/puppeteer). Wtedy da się taki proces całkowicie zautomatyzować. Chyba, że allegro da jakąś captchę.

**Comment by haloween** [comment]
@awronski zrobie via SOAP, nie będę rzeźbić w g...ie

**Comment by awronski** [comment]
@haloween Niestety niektóre rzeczy dostępne są tylko przez Resta. Jak zmiana cen w aukcjach ze sprzedażą.

Możesz zobaczyć na moje dzieło ;) Może się przyda. Wersja 3 obsługuje resta.

https://github.com/awronski/allegro-nice-api/tree/allegro-nice-api-3.0.0

**Comment by AniaMalinowska** [comment]
@haloween czy możesz doprecyzować, jaka jest architektura Twojej aplikacji? Może będziemy w stanie coś zaproponować. 
Zdajemy sobie sprawę, że OAuth2 jest trudny w przypadku aplikacji desktopowych oraz konsolowych/batchowych. Analizujemy ten temat po naszej stronie. Niemniej, użytkownik Allegro będzie musiał zawsze wyrazić zgodę na dostęp dla danej aplikacji - albo na naszej stronie logowania albo w naszej aplikacji mobilnej.

W REST API, w którym udostępniamy coraz więcej metod, korzystamy i będziemy korzystać z OAuth2, dzięki czemu użytkownik wpisuje swoje hasło w zaufanym przez nas miejscu. Docelowo nie będzie możliwości, aby przechowywać hasła użytkownika Allegro po stronie aplikacji.

Chciałabym też zaznaczyć, że proponowane obejście problemu (Chrome Headless i Puppeteer) zadziała tylko dlatego, że aplikacja ma zapisany login i hasło użytkownika, a także dlatego - jak słusznie zauważył @awronski - w sytuacjach gdy nie ma tam np. Captchy. Czyli jest to rozwiązanie bardzo krótkofalowe.

**Comment by awronski** [comment]
@AniaMalinowska 

Pozwolę sobie też dodać uwagi od siebie. W pełni zgadzam się z @haloween 

Dlaczego nie dacie użytkownikom wyboru jak chcą korzystać z Waszego API?
Amazon nie widzi problemu i daje wiele możliwości ustawienia dostępu. Jeżeli ktoś chce łączyć się z ich serwisami przez wygenerowane klucze zamiast oauth to może tak sobie to ustawić.

Architektura mojej aplikacji:

1. Użytkownik instaluje aplikacje na serwerze
2. Aplikacja w pełni automatycznie aktualizuje ilości na allegro na podstawie stanów magazynowych klienta.

**Problem:**
- Jeżeli token wygaśnie lub np. serwer zostanie zrestartowany to synchronizacja przestaje działać.
Klient dostaje co prawda email z aplikacji o konieczności ponownego zalogowania, ale jak np. jest weekend, urlop, czy nie przeczyta emaila to stany na allegro rozjadą się.

Dlatego Wasze podejście to uszczęśliwianie wszystkich na siłę. IT ma ułatwiać prowadzenie biznesu a nie utrudniać.

Nikt nie każe by użytkownik przekazywał API swój login i hasło. Wystarczałyby klucze które użytkownik może w każdej chwili anulować. Można tak jak na AWS zdefiniować jakie metody API dany klucz może wywołać.

**Comment by anih** [comment]
Ciekawie ma też to rozwiązane ebay, mianowicie można dla swojego użytkownika wygenerować specjalny typ tokena, który ma ważność kilka lat(nie pamiętam dokładnie). Takie podejście powoduje, że dalej można token odwołać, login/hasło nie jest przekazywane poza allegro, a jednocześnie np. 10 lat nie trzeba tego robić.

**Comment by haloween** [comment]
@anih 
No dokładnie, tak to się robi w cywilizowanych organizacjach / aplikacjach. Generujesz token, nim autoryzujesz operacje, możesz go odwołać. 

Ale po co ?

**Comment by AniaMalinowska** [comment]
Pytamy o architekturę, ponieważ jest szansa, że taka aplikacja zainstalowana na serwerze i chodząca w tle, mimo wszystko może wystawić jeden endpoint. Taki endpoint - otwarty w przeglądarce:

- przekieruje na stronę logowania Allegro
- po powrocie pobierze token.

Taki access token razem z refresh token może być zapisany w bazie (albo gdzieś w pliku) i potem odświeżany automatycznie. Nie ma potrzeby tworzenia jakichkolwiek frontendów.
Oczywiście to nie zadziała, jeżeli:

- nie ma dostępu do serwera z poziomu przeglądarki
- lub nie ma możliwości zapisania tokenów.

Tak jak napisałam wcześniej, zdajemy sobie sprawę, że OAuth2 jest trudny w przypadku aplikacji desktopowych oraz konsolowych/batchowych.
Generowanie tokenów z odpowiednimi dostępami przez samego użytkownika (jak na wspomnianym AWS i eBay) jest jedną z możliwości, które analizujemy. Chcemy ten problem rozwiązać jak najszybciej.
Natomiast wspomniany wyżej eBay w nowym REST API zablokował możliwość generowania tokenów OAuth2 przez użytkownika. Taka opcja jest tylko dostępna dla starego Auth'n'Auth.

**Comment by awronski** [comment]
@AniaMalinowska Ale to co w tej chwili robicie to ma efekt jak generowanie tokenów na AWS. Jedyna różnica, że jest to super niewygodne.

Nie widzę żadnych korzyści z Waszego rozwiązania.

AWS:
- generuje się token jednorazowo i nadaje się mu czas ważności
- potem z tokena można korzystać np. na serwerze bez obaw czy działa

Allegro:
- generuje się token poprzez zalogowanie do Allegro i zapisuje gdzieś w bazie
- potem można korzystać tak samo jak na amazonie tylko że token trzeba odświeżać, plus ma ograniczoną żywotność.

Po co robić to tak na około.

**Comment by AniaMalinowska** [comment]
AWS to zupełnie inny byt. Ciężko porównywać ich API z naszym. 
Mówimy tutaj o tokenach, które w proponowanej postaci nie możemy zaimplementować po naszej stronie ze względu na szereg różnych wewnętrznych wymagań.
W związku z tym, autoryzacja w REST API Allegro jest ograniczona do specyfikacji OAuth2 i rozszerzeniach do tej specyfikacji. Poruszając się w tych ramach, chcemy jak najszybciej dostarczyć rozwiązanie ułatwiające pracę aplikacjom desktopowym i batchowym.

**Comment by haloween** [comment]
@AniaMalinowska 

> Mówimy tutaj o tokenach, które w proponowanej postaci nie możemy zaimplementować po naszej stronie ze względu na szereg różnych wewnętrznych wymagań.

To może przedstaw nam te wymagania - chętnie o tym porozmawiamy.

**Comment by AniaMalinowska** [comment]
Są to nasze wewnętrzne wymagania związane z bezpieczeństwem i infrastrukturą.

**Comment by haloween** [comment]
Super wyjaśnienie, naprawdę 🥇 Bezpieczeństwo 🛡 i infrastruktura 💻 ... 
Dodajmy do listy powodów imię biurowej maskotki 🐈  i kod do kibla 🚽

Ja obstawiam 2 rzeczy:
- pisze to jakiś Junior i tylko tak umie
- macie gotową biblioteczkę do autoryzacji i inaczej nie umiecie

Bo niech mi ktoś wyjaśni - czym różni się token Oauth2 i jego odwołanie etc od jakiegoś innego tokena pod kątem wdrożenia ? 

Mamy jakiś dodatkowy nagłówek w zapytaniu i w obu przypadkach mamy jedno zapytanie SQL/NoSQL do spasowania go z kontem.

Jakie to implikuje różnice w bezpieczeństwie / infrastrukturze to jest dla mnie niepojęte. 
Tu jest token i tu jest token, tylko w jendym wariancie trzeba się narzeźbić żeby go dostać w innym nie trzeba.

Przyjmijmy że nie chcecie aby userzy przekazywali L/P do konta - bo Bezpieczeństwo.

To teraz przedstawiam pani tzw. klasyczny scenariusz pracy z p. Halinką.  p. Halinka chce żeby jej zintegrować API, i mamy 2 opcje: 
A) p. Halinka sama klika w link i klika TAK 
B) p. Halinka śle L/P do integratora który musi to zrobić

Zapewniam że przypadek A będzie stanowić 3% z próby a loginy i hasła będą latać mailem jak nasi rodacy Ryanairem na Stansted. 

Ale będzie BEZPIECZNIE.

**Comment by k4pit4n** [comment]
@AniaMalinowska 

> W związku z tym, autoryzacja w REST API Allegro jest ograniczona do specyfikacji OAuth2 i rozszerzeniach do tej specyfikacji. Poruszając się w tych ramach, chcemy jak najszybciej dostarczyć rozwiązanie ułatwiające pracę aplikacjom desktopowym i batchowym.

Coś się zmieniło w tej kwestii? Tzn. czy pojawiło się jakieś rozwiązanie ułatwiające pracę aplikacjom desktopowym i batchowym poprzez REST API?

**Comment by AniaMalinowska** [comment]
Na ten moment nie wdrożyliśmy zmian w tym zakresie. Jeśli coś się zmieni - zakomunikujemy to.

**Comment by BusterLodz** [comment]
@AniaMalinowska
Wy się zastanówcie nad tym całym REST API. Ja rozumiem, bezpieczeństwo przede wszystkim. Ale w chwili obecnej dajecie rozwiązanie, które ma się nijak do bardzo dobrze rozwiniętego Webapi. Tak jak wcześniej było zauważone, przy REST API jest rzeźbienie w g.... A kolejna sprawa? Czemu chcecie wygasić Webapi??? Nie róbcie tego. Nie idźcie tą drogą. Chcecie uruchomić REST API, ok. Ale zostawcie Webapi, tym bardziej, że na rynku jest mnóstwo aplikacji desktopowych, które z tego korzystają.

**Comment by AniaMalinowska** [comment]
Od pewnego czasu intensywnie rozwijamy REST API. Udostępniliśmy w nim wiele nowych zasobów, które dotychczas uzupełniały możliwości WebAPI. Nowe funkcjonalności będziemy udostępniać tylko w REST API. 

Proces wygaszania WebAPI będzie rozłożony w czasie. Zachęcamy, aby stopniowo przechodzić na REST API.

**Comment by omecon-allegro** [comment]
Też się za głowę złapałem jak zobaczyłem logowanie.
Mamy kilka środowisk dev, test, pre_prod, probe i prd i teraz wiekszość z nich wogóle nie jest wystawiona i nie będzie wystawiona na świat. W jaki sposób się tam zalogować? Pomijam już, że przekierowanie z naszej app do allegro zupełnie nie ma sensu ze wspomnianych wyżej powodów. Chcielibyśmy aby nasz klient allegro był realizowany przez microservice zewnetrzny w stosunku do aplikacji do której ma dostęp logujący się klient. Jak już wspomnieli poprzednicy to niewykonalne.

**Comment by haloween** [comment]
Oni i tak nie zrozumieją... na kursie nie było.
#januszesoftware

W dniu pt., 24.08.2018 o 09:36 omecon-allegro <notifications@github.com>
napisał(a):

**Comment by AniaMalinowska** [comment]
Przekierowanie odbywa się w przeglądarce, dlatego może być na adres localhost. Środowiska nie muszą być dostępne publicznie, więc jest to jak najbardziej wykonalne.
Pracujemy nad rozwiązaniem dla narzędzi, które działają 'headless' - nie mające frontendu.

**Comment by awronski** [comment]
Póki co polecam spróbować
https://github.com/GoogleChrome/puppeteer

**Comment by AleksyZajac** [comment]
Coś się zmieniło w tej kwestii? Czy pojawiło się jakieś rozwiązanie ułatwiające pracę aplikacjom desktopowym i batchowym poprzez REST API?

**Comment by MartaNowaczyk** [comment]
@AleksyZajac w listopadzie wprowadziliśmy [device flow](https://developer.allegro.pl/auth/#DeviceFlow) oraz wydłużyliśmy czas ważności refresh_tokena do 365 dni.

**Comment by szebrowski** [comment]
Btw. strona dokumentacji nie wyświetla się poprawnie na Chrome na Androidzie.

**Comment by PawelTaberski** [comment]
@szebrowski Obecnej stronie wiele brakuje do ideału, na mobilnych urządzenia nie wygląda najlepiej pracujemy nad nowszą wersją strony 👍

**Comment by haloween** [comment]
Zatrudniliście już kogoś kompetentnego kto potrafi rozwiązać ten issue ??

**Comment by haloween** [comment]
Jak jest z tym problem to wam to ogarnę w dobrej stawce ....
