### ISSUE TITLE
NotAllowedException - OAuth2

### ISSUE THREAD

**Issue by adrian282** [allegro/allegro-api#1200]
Mam problem z pobraniem czegokolwiek przez GET.  Używam metody OAuth2 i dostaję access_token pomyślnie. 
Natomiast na jakiekolwiek żądanie to dostaję _NotAllowedException_

Np dla adresu: `https://api.allegro.pl/offers/listing?seller.id=XXX`
nagłówki:

```
	function prepare_headers($token) {
		return [
			'Accept: application/vnd.allegro.public.v1+json',
			'Content-Type: application/vnd.allegro.public.v1+json',
			'Accept-Language: PL',
			'Authorization: Bearer ' . $token
		];
	}
```

**Comment by PawelTaberski** [comment]
Jesteś pewny, że używasz metody GET? Jaki status odpowiedzi dostajesz 405?

**Comment by adrian282** [comment]
okazało się, że ustawienie CURLOPT_POSTFIELDS na NULL było problemem
Dziwne, ale jednak...

**Comment by adrian282** [comment]
a takie dwa pytania dodatkowe dot. /offers/listing
1) Da się pobrać od razu nazwę użytkownika (a nie jego ID) ?
2) Data publikacji/zakończenia. Rzadko kiedy jest dostępne, ale to pewnie przez to, że są to `wieczne aukcje`?

**Comment by PawelTaberski** [comment]
Obecnie nie ma zasobu w REST API do pobrania loginu usera na podstawie ID. Jest taka metoda w WebAPI - [doGetUserLogin](https://allegro.pl/webapi/documentation.php/show/id,104)
Co do drugiego pytania to taka data jest dostępna przy ofertach o wystawionych na określony czas np 10, 20, 30 dni.

**Comment by adrian282** [comment]
hmm, dziwne. Wypadałoby oprócz ID również wystawić login od razu... Dziwne
