### ISSUE TITLE
Wyciągnięcie opisu oferty w pierwotynym kształcie

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#1201]
Czy jest jakaś możliwość wyciągnięcia opisu oferty w postaci takiej jak została ona dostarczona przez metodę doNewAuctionExt? Muszę zmienić opisy wszystkich moich aukcji jest ich parę tysięcy- chodzi o usunięcie numerów telefonów. Wpadłem na pomysł że odczytam opisy przy pomocy metody doGetItemsInfo a później zastosuję str_replace() [PHP] a później metodą doChangeItemFields ostatecznie potwierdzę nowy opis podając fid 341. Ale to oczywiście nie zadziała bo metoda doGetItemsInfo zwraca opis niedostosowany do nowych warunków opisu oferty ponieważ podaje linki bezpośrednie i style CSS. Co tu robić? Jestem początkujący więc jeśli pytanie jest nieambitne to z góry przepraszam ;)

**Comment by manhunto** [comment]
@marcinja2 Użyj `doGetItemsInfo` Opis znajduje się w `{item-info}->{it-standardized-description}` O ile dobrze pamiętam to aby pobrać ten opis jako trzeci parametr metody musisz przekazać 1. Zgodnie z tym co jest w dokumentacji. https://allegro.pl/webapi/documentation.php/show/id,52#method-input
No i potem tak jak napisałeś.. użyj `doChangeItemFields` żeby to wysłać

**Comment by marcinja2** [comment]
wielkie dzięki, minimalna modyfikacja i wszystko działa. Czasem człowieka coś zaślepi a przecież rozwiązanie było linijkę niżej (itDescription a pod nim it-standardized-description) choć nie do końca to było intuicyjne ale cóż nieintuicyjne kwiatki to raczej normalka.
