### ISSUE TITLE
czas aktualizacji danych

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#1206]
Czy po dodaniu nowej aukcji przez interfejs użytkownika lub dokonaniu tam zmian - zmiany te od razu są widocze w REST API, czy po jakimś czasie? Jeżeli nie od razu to ile trzeba odczekać?
Chodzi mi o metody:
GET /offers/listing
GET /sale/offers/{offerId}

Dodatkowo: czy są plany, żeby dodać do API zarządzanie monetami?

**Comment by PawelTaberski** [comment]
Każda zmiana na ofercie może się procesować do godziny czasu, także może nie pojawić się od razu zmiana.

**Comment by sheerun** [comment]
A czy nowo dodane aukcje są od razu widoczne tak samo jak na WWW?

**Comment by PawelTaberski** [comment]
Każda zmiana na ofercie także publikacja może zająć do godziny czasu.
