### ISSUE TITLE
Sandbox nie działa

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1207]
Hej!
Od piątku albo od soboty nie mogę wystawić aukcji na sandboxie. Wydaje mi się że ani przez REST ani przez interfejs WWW. Niby wszystko w porządku, GetOfferPublicationStatus zwraca success, a w serwisie aukcja wisi jako "W trakcie aktywacji".
Możecie coś z tym zrobić?

**Comment by MartaNowaczyk** [comment]
@jakubmaguza dzięki za informację, sprawdzam.

**Comment by MartaNowaczyk** [comment]
Co prawda po dłuższym czasie niż zwykle, ale i z poziomu www i przez REST API udało mi się wystawić oferty.

**Comment by jakubmaguza** [comment]
No właśnie teraz wszystkie które nie chciały wystawić się przez weekend zmieniły status na aktywna :)
Dzięki!
