### ISSUE TITLE
RestAPI - kolejność wariantów

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1208]
Na listingu po najechaniu na ofertę jest problem z kolejnością rozmiarów [https://allegro.pl/kategoria/obuwie-trzewiki-i-polbuty-25960?string=Trzewiki%20BARTEK%20dla%20ch%C5%82opc%C3%B3w%20czarno-szary%2040&order=m&bmatch=baseline-n-dict-sort-sqm-bab-1-3-0131](https://allegro.pl/kategoria/obuwie-trzewiki-i-polbuty-25960?string=Trzewiki%20BARTEK%20dla%20ch%C5%82opc%C3%B3w%20czarno-szary%2040&order=m&bmatch=baseline-n-dict-sort-sqm-bab-1-3-0131), aukcja nr 7842622952

**Comment by MartaNowaczyk** [comment]
@pietrach jeśli problem nie dotyczy API Allegro zgłoś go proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)
