### ISSUE TITLE
Jak pobrać zakończone aukcje?

### ISSUE THREAD

**Issue by sheerun** [allegro/allegro-api#1209]
Chciałbym wiedzieć z jaką finalną ceną skończyła się dana aukcja na Allegro parę godzin po zakończeniu kiedy z powrotem jestem dostępny online. Jest to możliwe do zobaczenia na WWW po prostu przez wejście na stronę oferty: https://allegro.pl/oferta/apple-7-7830928992

Z tego co widzę przez REST API nie jest możliwe ani pobieranie zakończonych ofert ani pobierania informacji po pojedynczej zakończonej ofercie, chyba że coś przeoczyłem? Planujecie dodać taką możliwość?

**Comment by lukada4100** [comment]
Właśnie przy tym siedzę:  get /sale/offers i jako parametr dajesz publication.status=ENDED

**Comment by sheerun** [comment]
Nie chodzi o moje oferty tyle o oferty jakie licytowałem albo obserwowałem i nie koniecznie muszą być moje. Chciałbym mieć możliwość sprawdzenia o ile przegrałem aukcje oraz obserwowania ile były warte zakończone licytacje żeby dobrze zalicytować w przyszłych.

W skrócie chodzi o dodanie opcji publication.status=ENDED do /offers/listing albo udostępnienie API /offers/listing/:id dla zakończonych aukcji w celu sprawdzenia jak zakończyła się licytacja

**Comment by MartaNowaczyk** [comment]
@sheerun będziemy rozwijać kwestie pobierania publicznych danych ofert, ale czy wszystko o czym piszesz będzie dostępne poinformujemy w oddzielnym komunikacie, gdy dodamy nowe możliwości. Na ten moment przyjmuję twoje zapytanie jako sugestię.

**Comment by sheerun** [comment]
podbijam

**Comment by sheerun** [comment]
prosze o otworzenie i niezamykanie tego wątku

**Comment by MartaNowaczyk** [comment]
@sheerun zamyka go automat. Masz jeszcze jakieś pytania w tej sprawie, że wątek ma pozostać otwarty.

**Comment by sheerun** [comment]
skoro nie ma znaczenia czy ten wątek jest otwarty czy nie dla wprowadzenia tej funkcjonalności to proszę zamknąć..

**Comment by MartaNowaczyk** [comment]
Wszystkie sugestie z tego wątku mamy już zaadresowane, więc możemy spokojnie zamknąć.
