### ISSUE TITLE
Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!

### ISSUE THREAD

**Issue by awronski** [allegro/allegro-api#121]
Od piątku 6 kwietnia od około godziny 20:00 dostajemy przy wywoływaniu niektórych metod (zmiana ilości, wystawienie aukcji) błąd: `Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!`

Błąd nie wyskakuje za każdym razem ale bardzo bardzo często.

Co dziwne błąd pojawia się w szczególności dla nowych sesji. Czyli takich które zostały stworzone ułamek sekundy wcześniej. 

Czyli robimy `DoLoginEncRequest`, a potem `DoChangeQuantityItemRequest` i dostajemy wyjątek.

Tak jakby jakiś problem z propagacją sesji u Was. Że jest stworzona, ale inne Wasze serwery jeszcze o niej nie wiedzą.

Proszę o info czy znacie temat?

**Comment by TimothyKoval** [comment]
Z tego co wiem to takich limitów nie ma. Jeżeli są, to chętnie się o nich dowiem

**Comment by TimothyKoval** [comment]
Ja tak mam od zawsze. Kilkanaście do kilkudziesięciu razy dziennie.

**Comment by rtnet-pl** [comment]
Potwierdzam, zdarza się często i chyba "od zawsze", tak jak np. przerywanie połączenia w api soap.
Implementujemy w aplikacjach powtarzanie requestu po odczekaniu kilku sekund, bo nie udało się doczekać poprawki :)

**Comment by awronski** [comment]
Ale ostatnio ten problem się nasilił. Trzeba pisać jakieś workaroundy, typu łapanie wyjątku złej sesji, albo odczekiwanie z requestami po zalogowaniu jak kolega wyżej zauważył. To jakaś porażka.

**Comment by awronski** [comment]
@KrzysztofLukanowski label to by się przydał błąd a nie pytanie. Jak działają sesję to wiem z dokumentacji. Przynajmniej jak powinny działać.

 Proszę sprawdzić u siebie co dzieje się z tymi numerami sesji. Dzięki!

**Comment by KrzysztofLukanowski** [comment]
@awronski sprawdzam temat - z tego co wyżej piszecie, to nie jest odosobniony problem. Potrzebowałbym trochę więcej szczegółów - przede wszystkim login usera, który otrzymuje taki błąd.

**Comment by TimothyKoval** [comment]
@KrzysztofLukanowski np. `Apisys`

**Comment by KrzysztofLukanowski** [comment]
Proszę jeszcze o informację, czy wywołanie każdej metody do operacji na ofercie lub transakcjach poprzedzacie zalogowaniem się? Jeżeli tak, istnieje duże prawdopodobieństwo, że to jednak 11 sesja z kolei  i ta najstarsza jest kończona.

Jeżeli jednak korzystacie z tego samego id sesji do różnych zapytań, czy na pewno to zapytanie, do którego poszedł request mieści się w godzinie od wywołania poprzedniej metody?

**Comment by rtnet-pl** [comment]
Dzień dobry!

Aktualna wersja zawsze dostępna jest do pobrania w tym miejscu:

Pozdrowienia,
Tomasz Rakowski

RTNET Sp. z o.o. sp. k./ Lusówko, Wiązowa 14, 62-080 Tarnowo Podgórne / 
NIP 781-193-02-74
*Biuro:* 62-080 Sady, ul. Rolna 9. Tel. *61 641 6234*

http://rtnet.pl
PriceWizard.pl <https://pricewizard.pl/> (fb.com/pricewizard 
<https://www.facebook.com/pricewizard/>) | Integratory.pl 
<https://integratory.pl> (fb.com/integratory 
<https://www.facebook.com/integratory/>)


W dniu 2018-04-09 o 17:09, awronski pisze:

**Comment by awronski** [comment]
@KrzysztofLukanowski Błędy pojawiają się w sposób niedeterministyczny.
Tak jak pisałem wyżej trzymamy tylko ostatnią sesję więc nie ma problemu z jej wygaśnięciem.

**Problemem było raczej tworzenie zbyt często nowych sesji. W takim wypadku tak jakby tablice aktualnych sesji nie odświeżały się u Was na czas. I nie było w nich najnowszej sesji.**


Ja rozwiązałem problem w ten sposób, że mamy scheduler który co 30 minut tworzy nową sesję. Starą porzuca. Dzięki temu u Was w tablicy sesji są maksymalnie 3 (bo ubijace stare po godzinie) a ja korzystam tylko z tej najnowszej.


Przy tym podejściu od kilku dni ani razu nie miałem wyjątku. Więc wydaje mi się, że problem rozwiązałem. A wcześniej pojawiał się wiele razy dziennie. Wydaje mi się, że też zależało to od obciążenia u Was (w niedziele niehandlowe najwięcej).

**Comment by KrzysztofLukanowski** [comment]
Nie znalazłem podobnych błędów dla nowych sesji, dlatego proszę o zgłoszenie w tickecie, na jakim kluczu i kiedy wystąpił taki błąd. Proszę przesłać zgłoszenie przez ten [formularz](https://allegro.pl/pomoc/kontakt#subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422).
