### ISSUE TITLE
get /sale/offers/

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1210]
Dobrze widzę, że informacje, kiedy oferta się zaczęła i zakończyła (startedAt i endedAt)  można pobrać za pomocą listingu  get /sale/offers  a nie można za pomocą  get /sale/offers/{offerId}?
Czemu właściwie "publication" zwracane tu i tam mają różne formaty?

Wkurzające jest to, że gdy coś się sprzeda, obiekt zwracany przez get /sale/offers/{offerId} ma przez jakiś czas stock.available=0, a status wciąż jest ACTIVE. Dopiero po jakimś czasie status zmienia się na ENDED. Czy to celowy zabieg?

A przy okazji, skoro już marudzę, to wyskakują mi takie kwiatki (patrz załącznik):
[391_Full.txt](https://github.com/allegro/allegro-api/files/2876930/391_Full.txt)
[392_Full.txt](https://github.com/allegro/allegro-api/files/2876931/392_Full.txt)
[1316_Full.txt](https://github.com/allegro/allegro-api/files/2876932/1316_Full.txt)

**Comment by MartaNowaczyk** [comment]
@lukada4100 na przyszłość proszę otwieraj oddzielne wątki jeśli pytania/problemy nei są zesobą powiązane. 

1. startedAt i endedAt - wiemy o tym i jesteśmy w trakcie ustalania by to uspójnić.
2. czasem status musi się odświeżyć stąd taka różnica.
3. Sprawdzimy i dam znać.

**Comment by lukada4100** [comment]
Ok. Będę pamiętał. Po prostu wszystko dotyczyło jednej metody, stąd pomysł na połączenie.
ad 2) nie ma szans żeby to było równocześnie?

**Comment by MartaNowaczyk** [comment]
@lukada4100 masz jakiś response z takim przypadkiem:
> get /sale/offers/{offerId} ma przez jakiś czas stock.available=0, a status wciąż jest ACTIVE

**Comment by lukada4100** [comment]
Hej, wysłałem właśnie dwa pliki przez formularz kontaktowy (nr zgłoszenia 04731602).

**Comment by MartaNowaczyk** [comment]
dzięki, sprawdzam

**Comment by MartaNowaczyk** [comment]
@lukada4100 potwierdziłam jeszcze, że te informacje mogą się różnić do około 5 minut, także trzeba to mieć na uwadze. Dzięki za zgłoszenie.
