### ISSUE TITLE
Zamykanie aukcji z licytacją

### ISSUE THREAD

**Issue by Ontr** [allegro/allegro-api#1211]
Czy jest możliwość (lub jest planowana) zamknięcia aukcji z licytacją z jednoczesnym odwołaniem ofert?

**Comment by KrzysztofLukanowski** [comment]
Na tę chwilę nie ma takich planów.

**Comment by qls-api** [comment]
Czy jest jakakolwiek możliwość odwołanie złożonych ofert w licytacji ?

**Comment by KrzysztofLukanowski** [comment]
W API nie ma takiej możliwości.

**Comment by qls-api** [comment]
Czy planowane jest dodanie takiej metody ?

**Comment by KrzysztofLukanowski** [comment]
Nie mamy tego w najbliższych planach, ale chcemy przenieść funkcjonalności serwisu na REST API, więc w dalszej perspektywie powinno pojawić się podobne rozwiązanie.
