### ISSUE TITLE
Metoda `doGetPostBuyFormsDataForSellers` i jedna problematyczna transakcja

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#1212]
Występuje problem: 
 - [X] z metodą WebAPI

:beetle: **Opis**
Witam, klient zgłosił nam problem z pobieraniem danych dla transakcji
`945656334`

Po sprawdzeniu okazuje się że dla każdej innej transakcji klienta metoda `doGetPostBuyFormsDataForSellers` zwraca poprawne dane a dla tej jednej "wyjątkowej" zwraca kompletne głupoty włącznie z kodem kraju równym `0`, zerową ceną i innymi kwiatkami. Będę bardzo wdzięczny za przyjrzenie się sprawie.

![image](https://user-images.githubusercontent.com/568207/52968732-61399300-33ae-11e9-98a1-5d1b0a6e2ecd.png)

**Comment by KrzysztofLukanowski** [comment]
Sprawdzamy dlaczego dla wskazanej transakcji, w tych polach, otrzymałeś takie dane. Napisz jak tylko namierzymy przyczynę problemu.

**Comment by Uriziel01** [comment]
Czy udało się już czegoś dowiedzieć?

Rozumiem że sprawdzenie tego dokładnie wymaga czasu, ale uważam że 4 dni od zgłoszenia błędu to jednak zdecydowanie zbyt długi okres oczekiwania.

**Comment by KrzysztofLukanowski** [comment]
Przepraszam, że musiałeś tyle czekać. Kwota w polu postBuyFormItPrice jest zawsze ustawiona na 0, ponieważ z czasem wprowadziliśmy zmiany ceny po tym, jak pojawią się kliencie w ofercie. Informacja w tym polu byłaby myląca. 

Co do kraju, nie znaleźliśmy przyczyny tego błędu, aczkolwiek w tym polu zawsze powinna zostać zwrócona wartość 1 - Polska. W innych krajach nie prowadzimy już serwisów. 

Zachęcam do korzystania  z [REST API do obsługi zamówień](https://developer.allegro.pl/orders/).

**Comment by Uriziel01** [comment]
Ale wystarczy spojrzeć na screen powyżej  i widzimy że kraj jest tutaj najmniejszym problemem, wszystkie oferty w powyższej transakcji mają całkowicie pusty tytuł, zgłaszam więc błąd w działaniu metody `
doGetPostBuyFormsDataForSellers`. W tym system nie mogę przejść też na REST API więc jestem raczej w sytuacji patowej.

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem z tym zakupem. Przekazałem sprawę do zespołu, który odpowiada za tą usługę. Proszę o cierpliwość.

**Comment by Uriziel01** [comment]
Równy miesiąc to było by chyba zbyt dużo cierpliwości z naszej strony, na szczęście klient rozwiązał problem poprzez ręczne przetworzenie tych transakcji.

**Comment by PawelTaberski** [comment]
Błąd jak się w końcu okazało wynikał z tego, że podane transakcje dotyczyły oferty archiwalnej i dlatego metoda zwraca niekompletne informacje. Przepraszam, że musiałeś tak długo czekać na odpowiedź.
