### ISSUE TITLE
Informacje o złożonych ofertach w licytacjach

### ISSUE THREAD

**Issue by Ontr** [allegro/allegro-api#1213]
Czy jest lub jest planowany dziennik zdarzeń dla ofert składanych w aukcjach z licytacją?
Kiedyś pojawiła się koncepcja używania Webhook, czy jest rozwijana?

**Comment by KrzysztofLukanowski** [comment]
Aktualnie nie rozwijamy takiej koncepcji.

**Comment by Ontr** [comment]
Czyli nie będzie żadnego dziennika zdarzeń dla aukcji z licytacjami? Aby być na bieżąco z ilością licytujących i ceną trzeba będzie w kółko sprawdzać każdą aukcję?

**Comment by KrzysztofLukanowski** [comment]
Dziękuję za sugestię. Skontaktuję się z osobami odpowiedzialnymi za rozwój licytacji i poinformuję o zgłoszonych potrzebach.
