### ISSUE TITLE
GET /offers/listing - podwójne aukcje

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#1214]
Mam jakiś problem z pobieranie aukcji za pomocą GET /offers/listing

Przykład:
Jest sprzedawca, mający około 3000 aukcji, pobieram to poprzez:

$offset=0;
while ($offset<$ilosc_wszystkich_aukcji) 
{
$params = array('seller.id' => IDSPRZEDAWCY,'offset' => $offset,'limit' => 100,'sort'=>'startTime','fallback'=>false);
$resource=$api->offers->listing()->get($params);
.....
$offset+=100;
}
Petla jest mocno uproszczona na potrzeby tego przykładu

Przeprowadziłem 5 prób, 3 razy było dobrze, 2 razy źle. Źle polegało na tym że aukcje się powtarzały. Za pierwszym złym razem było około 30 powtórzonych aukcji, za drugim 5. Przy czym sumaryczna ilość pobranych aukcji zawsze się zgadzała, przez co domyślam się że jakieś aukcje nie zostały pobrane. Są także zmiany w kolejności zwracanych aukcji.

Poproszę o jakieś wskazówki. Jeżeli to w czymś pomoże to mogę przygotować excela z dokładnymi wynikami,

**Comment by KrzysztofLukanowski** [comment]
Doprecyzuj proszę. Oferty mogły się powtarzać, bo część ofert mogła zakończyć się. Sprzedający mógł też wystawić w tym czasie nowe oferty.

Czy oferty, które powtórzyły się, otrzymałeś zduplikowane w ramach jednej odpowiedzi, czy zostały zwrócone w kilku kolejnych odpowiedziach?

**Comment by Mihalis76** [comment]
Na pewno nikt nie pracował w tym czasie - specjalnie usiadłem do tego w nocy.
Na 99% wszystkie aukcje są ustawione "do wyczerpania zapasów" a ilość sztuk ustawiona na 9999.

Załączam plik xls z dokładnymi wynikami . 
[wyniki.zip](https://github.com/allegro/allegro-api/files/2883738/wyniki.zip)

Błędne próby to 3 i 4.
W czwartej powtórzenia były na następujących pozycjach:
1191 -> 1215
1195 -> 1200
1297 -> 1300
1298 -> 1301
1299 -> 1302
Czyli były to kolejne pobierane paczki

Za trzecią próbą powtórzyły się aukcje o indeksach: 2382 - 2419, 3261- 3263. Powtórzenia ich były na pozycjach: 3265 - 3303

**Comment by KrzysztofLukanowski** [comment]
Bardzo ciężko powtórzyć błąd, jeśli występuje on nieregularnie. Musimy zweryfikować tę konkretną sytuację, w której otrzymałeś dla kolejnych paczek te same numery ofert. Podeślij proszę dla takich przypadków request + response. W przypadku response podaj również trace-id, dzięki temu będziemy mogli namierzyć sytuację po naszej stronie. Zrobisz to przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), w zgłoszeniu podaj nr tematu na githubie #1214.

**Comment by Mihalis76** [comment]
Mam opóźnienie w projekcie, więc na razie wziąłem to dodatkową pętlę która na koniec sprawdza poprawność i w razie czego powtarza pobieranie. Do dokładnej analizy wrócę później. Dzięki za pomoc.

**Comment by mindc** [comment]
Też zauważyłem taki problem, nawet przy ustawieniu sortowania i fallback=false, wyniki potrafią się zmieniać przy każdym pobraniu listy ofert... Jedyne rozwiązanie na tą chwilę, to tak jak napisał @Mihalis76 , dodatkowe filtrowanie wyników i pozbywanie się duplikatów...

Raz zauważyłem nawet coś takiego: pobieram listę, pobieram listę drugi raz - brakuje dwóch aukcji (na kilkadziesiąt tysięcy niby nic), pobieram listę trzeci raz, mam to samo co przy pierwszym pobieraniu - brakujące dwie aukcje "magicznie" wróciły (przy każdym pobieraniu filtrowałem duplikaty)...

Siedziałem i sprawdzałem to kilka godzin, bo myślałem, że kod mam zły...

**Comment by KrzysztofLukanowski** [comment]
@mindc Tak jak pisałem wcześniej, musimy mieć konkretne dane, aby namierzyć źródło problemu, przede wszystkim trace-id. 

Dlatego podeślij proszę request i response. Zrobisz to przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu podaj nr tematu na githubie #1214.

**Comment by lwodniak** [comment]
też mam taki problem nie da się pobrać wszystkich aukcji spełniających kryterium zapytania, dodatkowo w wyniku powielają się aukcje (czyli zapytanie pobiera taką ilość jak trzeba ale część aukcji się powtarza a innych brak)
pobieram najpierw ilość aukcji i później pętlą po 100 aukcji

while(True):
			oile=oile+100
			if(oile>total): break
                        response = session.get(self.DEFAULT_API_URL +'/offers/listing'
				,params={'seller.id':seller_id,'offset':str(oile),'limit':'100','include':'-filters'})
