### ISSUE TITLE
Jak pobrać załączniki do dyskusji

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1215]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Próbuje pobrać załącznik do dyskusji za pośrednictwem zasobu` GET /sale/dispute-attachments/{attachment.Id}`

W dokumentacji widnieje 

> {attachment.Id} znajdziesz w danych o dyskusji

Pobierając wszystkie wiadomości dla danej dyskusji (`GET/sale/disputes/{dispute.Id}/messages`) dostaję coś takiego: 

> "message": {
        "id": "e75d97ba-18a7-4d1b-a7ee-d02ba1a21bba",
        "text": "...",
        "attachment": {
            "fileName": "Zdjęcie0007.jpg",
            "url": "https://upload.allegro.pl/sale/dispute-attachments/ecc0ab1a-8cff-4ffc-8e25-29dde7f07f18"
    }
}

Rozumiem że id załącznika trzeba sobie wyciągnąć z urla?
Więc próbuje `GET /sale/dispute-attachments/ecc0ab1a-8cff-4ffc-8e25-29dde7f07f18`
W odpowiedzi dostaję: 
> An error has occurred - Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
Z kodem `406`.

**Comment by Sojtin** [comment]
Czy `GET /sale/dispute-attachments/ecc0ab1a-8cff-4ffc-8e25-29dde7f07f18` ma być zapytane na `https://api.allegro.pl/` czy `https://upload.allegro.pl/`?
W dokumentacji jest:

> curl -X GET \
  https://api.allegro.pl/sale/dispute-attachments/66377da8-eee2-4094-8dcf-3540e51c307f \
  -H 'Authorization: Bearer {token}'

A w wiadomościach mam jak wyżej.

Btw. w https://developer.allegro.pl/documentation/#operation/getAttachmentUsingGET, nie ma kodu odpowiedzi `406`

**Comment by MartaNowaczyk** [comment]
@Sojtin na api.allegro i na upload.allegro powinno zadziałać. Wystarczy, że wyślesz zapytanie dokładnie w takiej postaci jak dostajesz linka w odpowiedzi: 

`https://upload.allegro.pl/sale/dispute-attachments/ecc0ab1a-8cff-4ffc-8e25-29dde7f07f18`

w dokumentacji nie podaliśmy wartości dla accept:

`curl -X GET \
  https://api.allegro.pl/sale/dispute-attachments/6fd7dc1d-de31-4fcc-92d3-557dd3fd7076 \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer {token]' `

**Comment by Sojtin** [comment]
@MartaNowaczyk Ok, kwestia nagłówka, dzięki.
