### ISSUE TITLE
GET  /sale/offers

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1218]
Mam parę pytań odnośnie końcówek GET sale/offers oraz GET sale/offers/{offerId}

1. czy stock.sold podawane przez sale/offers jest jakoś limitowane (np do ostatnich 30 dni czy coś)?
2. Jeśli tak, to czy można gdzieś wydobyć ilość wszystkich sprzedanych sztuk od początku trwania aukcji (szczegolnie interesuje mnie typ BUY NOW)?
3. Czemu nie podajecie tej danej przy pobieraniu sale/offers/{offerId}. IMO te dane powinny być bardziej szczegółowe...

**Comment by neldh** [comment]
Kolejne pytanie:
4. Czy planujecie dodać do którejkolwiek z tych końcówek zwracanie linka do thumbnaila głównego obrazka?

**Comment by neldh** [comment]
5. Czy stats.visitsCount także dot. tylko ostatnjich 30 dni (albo podobnie)? jesli tak, to czy planujecie udostepnić daną która będzie ekwiwalentem dla  itemViewsCounter z WEBAPI?

**Comment by MartaNowaczyk** [comment]
1. z 30 dni
2. na ten moment nie ma takiej możliwości i nie mamy w planach dodania takiej opcji, ale mogę zgłosić taką potrzebę do odpowiedniego zespołu.
3. nie zgłaszano nam takiej potrzeby
4. pierwszy link to miniaturka. Nie do końca rozumiem co byś chciał otrzymąć/zrobić...
5. powinna być z 30 dni

**Comment by neldh** [comment]
2. -> prosiłbym zatem o zgloszenie
4. -> podczas testowania zawsze dostawałem urle do pełnowymiarowych obrazków, a nie do miniaturki. Stąd to pytanie
5. -> czy również można prosić o zgloszenie potrzeby wydobycia tych danych od poczatku?

**Comment by MartaNowaczyk** [comment]
ad. 2 i 4 możesz nakreślić bardziej szczegółowo do czego potrzebne są te dane? Argumenty ważna rzecz ;)

**Comment by neldh** [comment]
2 i 5 potrzebne mi są do tego, żebym wyświetlił ogólne dane statystyczne w aplikacji. Wcześniej (w WEBAPI) taka opcja była dostępna, co dawało możliwość wyświetlenia tego. Teraz mogę to robić tylko z ostatnich 30 dni, co jest dla mnie totalnie bezużyteczne. Da się żyć bez tych danych, lecz aplikacja traci kolejną rzecz przez to po przejściu na REST.

Co do 4 to nadal otrzymuję link do pełnowymiarowego obrazka, a nie do miniaturki. Zawsze, niezależnie od oferty. Jakiś błąd u was może?

**Comment by MartaNowaczyk** [comment]
@neldh dzięki za wyjaśnienie

**Comment by MartaNowaczyk** [comment]
Co do miniaturki to zwracamy ją w pełnym formacie (wersję oryginalną). Przepraszam nie doprecyzowałam wcześniej, gdy pisałam, że pierwsze zdjęcie jest miniaturką.

**Comment by neldh** [comment]
aaa... czyli chodzi o zdjęcie główne (miniaturka zazwyczaj oznacza zdjęcie ze zmniejszonym rozmiarem...)

Czyli nie ma żadnej możliwości, żeby dostać od was linka do faktycznie zmniejszonego zdjęcia, czyli to co webapi zwracało w itemThumbnailUrl ?

**Comment by MartaNowaczyk** [comment]
w REST API nie ma takiego pola, które by to zwracało.

**Comment by mkaluszka** [comment]
Podpinam się pod punkt 2 - wczoraj przepisałem pobieranie informacji o aktualnie trwających aukcjach na REST i chciałem wykorzystać te pobrane informacje aby sterować ilościami sztuk na aukcjach. Niestety bez ilości sprzedanych sztuk od poczatku jest to niemożliwe, bo aby zmienic ilość na aukcji muszę do swojego stocku dodać swoją sprzedaż od początku trwania aukcji. A teraz tych danych tu nie jestem w stanie pobrać poprzez API - muszę albo nadal korzystać ze starego API, albo muszę te dane przetwarzać po swojej stronie, co może powodować i tak rozjazd z Waszymi danymi. Ew. jak to pobrać w REST inaczej - choć bez sensu byłoby robić to na 2 metody.

**Comment by MartaNowaczyk** [comment]
Na ten moment nie pobierzesz tego przez REST API. Musiałbyś zbierać to po swojej stronie. Tak jak pisałam wcześniej zgłosiłam taką potrzebę, także dzięki za kolejne argumenty.

**Comment by imper86** [comment]
@mkaluszka przecież w REST jak chcesz uaktualnić stan na aukcji to podajesz tylko aktualnie dostępną ilość, nie musisz już obliczać sumy ze sprzedanymi do tej pory.

**Comment by mkaluszka** [comment]
A którą metodą, bo wczytanie oferty i ustawienie stock->available w mojej ocenie wymaga jednak ustawienia sumy aktualnej ilosci + sprzedanej

**Comment by MartaNowaczyk** [comment]
@mkaluszka imper86 ma rację. W REST API w metodach do zmiany liczby przedmiotów możesz wpisać wartość docelową, którą chcesz zobaczyć w ofercie:

- PUT /sale/offer-quantity-change-commands/{commandId} - [grupowa edycja](https://developer.allegro.pl/my_offers/#3g) - wybierz "changeType":"FIXED"
- GET na zasobie sale/offers/{offerId} - [edycja pojedynczej oferty](https://developer.allegro.pl/my_offers/#2) - po prostu dla pola stock.available wpisz liczbę przedmiotów, która ma być dostępna w allegro.
