### ISSUE TITLE
PUT sale/offer-variants - błąd 500

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1219]
Czasem występują błędy tj. poniżej
`
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"\/sale\/offer-variants\/cb7f08b3-e568-45b9-ad46-9e0c7154fc91","userMessage":null}],"http_code":500}`

**Comment by MartaNowaczyk** [comment]
@pietrach dzięki za informację sprawdzimy czy coś jest na rzeczy.

**Comment by pietrach** [comment]
Przed chwilą dwa razy:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"\/sale\/offer-variants\/308db835-a85c-44a6-8a59-021b99e738ad","userMessage":null}],"http_code":500}`

**Comment by MartaNowaczyk** [comment]
@pietrach podaj proszę trace-id dla tych wywołań

**Comment by MartaNowaczyk** [comment]
@pietrach czasami zdarza się, że nie odpowiemy na czas. Sprawdziliśmy i nie odnotowaliśmy wzrostu błędów ze statusem 500, także nic złego nie powinno się dziać. Dzięki za zgłoszenie.

**Comment by pietrach** [comment]
Na przykład: 517b1f1a4ed37a2f

**Comment by MartaNowaczyk** [comment]
@dziękuję tak jak pisałam wcześniej, sprawdziliśmy i nie widzimy zwiększonej ilości błędów tego typu.

**Comment by pietrach** [comment]
Kolejne przykłady: 36f96f263d1e512, 57d5231dbc473a7e, 180eb3022fb8e011, aaf2f242d0d26c93, f9f0eb68b9d94389, 69d0aef8a09efe45, c45fa254bb1155e9, 3c03e7c603d4eac9, c13084ec2a733224, 7d6ff03ade5bb8e

**Comment by MartaNowaczyk** [comment]
@pietrach dzięki za kolejne przykłady, ale w tym przypadku również nie widzimy zwiększonej ilości błędów tego typu.
