### ISSUE TITLE
Nie potrafię zmienić parametru oferty wysyłka z polski, 

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#122]
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
<SOAP-ENV:Body>
<ns1:DoChangeItemFieldsRequest><ns1:sessionId>...</ns1:sessionId><ns1:itemId>6203937571</ns1:itemId>
<ns1:fieldsToModify>
   <ns1:item>
      <ns1:fid>24453</ns1:fid><ns1:fvalueString></ns1:fvalueString><ns1:fvalueInt>1</ns1:fvalueInt><ns1:fvalueFloat>0</ns1:fvalueFloat><ns1:fvalueImage></ns1:fvalueImage><ns1:fvalueDate></ns1:fvalueDate><ns1:fvalueRangeInt><ns1:fvalueRangeIntMin>0</ns1:fvalueRangeIntMin><ns1:fvalueRangeIntMax>0</ns1:fvalueRangeIntMax></ns1:fvalueRangeInt><ns1:fvalueRangeFloat><ns1:fvalueRangeFloatMin>0</ns1:fvalueRangeFloatMin><ns1:fvalueRangeFloatMax>0</ns1:fvalueRangeFloatMax></ns1:fvalueRangeFloat><ns1:fvalueRangeDate><ns1:fvalueRangeDateMin></ns1:fvalueRangeDateMin><ns1:fvalueRangeDateMax></ns1:fvalueRangeDateMax></ns1:fvalueRangeDate></ns1:item></ns1:fieldsToModify></ns1:DoChangeItemFieldsRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>`

Dlaczego to zapytanie przez SOAP zgłasza:

`Nie Udało się !. Kod Błędu: ERR_INVALID_VALUE_IN_ATTRIB_FIELD%`

Przy wysyłaniu tylko vartości FID który faktycznie jest istotny jest to samo:

`string(536) "<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl.allegrosandbox.pl/service.php"><SOAP-ENV:Body><ns1:DoChangeItemFieldsRequest><ns1:sessionId>...</ns1:sessionId><ns1:itemId>6203937571</ns1:itemId><ns1:fieldsToModify><ns1:item><ns1:fid>24453</ns1:fid><ns1:fvalueInt>1</ns1:fvalueInt></ns1:item></ns1:fieldsToModify></ns1:DoChangeItemFieldsRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
"
Nie Udało się !. Kod Błędu: ERR_INVALID_VALUE_IN_ATTRIB_FIELD%`

Co jest tutaj niepoprawne ?

**Comment by cieplik206** [comment]
Sprawdziłem jeszcze faultstringa i wychodzi że mam problem z tytułem, jednak nie wysyłam fid 5
`Niepoprawna wartość w polu formularza sprzedaży (np. zbyt duża ilość znaków w tytule oferty). Liczba sztuk - fid: 5`

**Comment by TimothyKoval** [comment]
Prawdopodobnie zmieniły się zasady dotyczące pól formularza, które już znajdują się w ofercie. Allegro - w swojej świetności - nie pozwala na edycję oferty, jeżeli wszystkie pola nie spełniają obecnych wymagań.

**Comment by TimothyKoval** [comment]
Czy aby na pewno ten id aukcji jest prawidłowy?

**Comment by cieplik206** [comment]
Rozumiem, ofertę wystawiłem przez WWW w sanboxie wczoraj, edycja przez WWW działa ale z prawdopodobieństwem 50% (raz wywala dziwne błędy a raz nie). Wiec raczejto nie jest sprawa pól wymaganych. FID 5 o który się pluje to ilość towaru.


własnie zmodyfikowałem przez WWW FID 24453 trzy razy, dwa razy poszło a za trzecim o taki błąd:

![image](https://user-images.githubusercontent.com/6499144/38470222-e88f1da4-3b5f-11e8-93d7-958a302d3dd8.png)


Pomimo tego że jest i był ustawiony

![image](https://user-images.githubusercontent.com/6499144/38470242-3e5088ea-3b60-11e8-8fa0-798a4ee02e22.png)

**Comment by TimothyKoval** [comment]
Czyli "nowe lepsze stabilniejsze" nie działa :) Jakoś mnie to nie dziwi...

**Comment by cieplik206** [comment]
Po zmiane ilości z 10k na 100 wszystko poszło ok, czy konto "nie firma" ma jakieś limity na ilosć ?,ale jesli tak to dlaczego mogłem wystawić ofertę przez WWW i ją edytować, a przez API nie poszło.

**Comment by TimothyKoval** [comment]
Z tego co wiem to takich limitów nie ma. Jeżeli są, to chętnie się o nich dowiem.

**Comment by cieplik206** [comment]
na to wygląda to jest maks co mi przechodzi:

 $fields = [$account->makeField([

                'fid' => '24453',
                'fvalueInt' => 2
            ]),
            $account->makeField([

                'fid' => '5',
                'fvalueInt' => 999
            ])
        ];

**Comment by rtnet-pl** [comment]
@cieplik206 z tego co widzę, to w tej kategorii (1494) stan=fid 20147

**Comment by cieplik206** [comment]
> z tego co widzę, to w tej kategorii (1494) stan=fid 20147

Hehe, no to jeszcze śmieszniej, bo ten error to WWW allegro mi zgłosiło.... LOL

**Comment by rtnet-pl** [comment]
@cieplik206 Ten numerek widoczny na zrzucie (11323) to inne pole  - sellFormParamId.
```
 [113] => stdClass Object
                                (
                                    [sellFormId] => 20147
                                    [sellFormTitle] => Stan
                                    [sellFormCat] => 1487
                                    [sellFormType] => 4
                                    [sellFormResType] => 2
                                    [sellFormDefValue] => 0
                                    [sellFormOpt] => 1
                                    [sellFormPos] => -1000
                                    [sellFormLength] => 4
                                    [sellMinValue] => 0.00
                                    [sellMaxValue] => 1639.00
                                    [sellFormDesc] =>  -- Wybierz -- |Nowy|Używany
                                    [sellFormOptsValues] => 0|1|2
                                    [sellFormFieldDesc] => globalny "Stan"
                                    [sellFormParamId] => 11323
                                    [sellFormParamValues] => 0|1|2
                                    [sellFormParentId] => 0
                                    [sellFormParentValue] => 0
                                    [sellFormUnit] => 
                                    [sellFormOptions] => 0
                                )
```

**Comment by cieplik206** [comment]
Web pozwolił mi wystawić aukcje niezgodną z zasadami dlatego API nie mogło jej wyedytować
