### ISSUE TITLE
GET sale/shipping-rates/{id}

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1221]
Cytując dokumentację:

shippingTime | object Custom shipping time for the given delivery method. If not set the default shipping time for the method is used.

Można jakoś pobrać te defaultowe wartości, jeśli w shippingTime mam null?

**Comment by MartaNowaczyk** [comment]
@neldh wartości dla shippingTime to wielokrotność 24H zgodnie z formatem [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Durations) np. PT24H

**Comment by neldh** [comment]
Nie chodzi mi o standard formatu, tylko o to, jaką wartość ma to pole podczas gdy wasze api zwraca null.

Napisałem wcześniej:
"Można jakoś pobrać te defaultowe wartości, jeśli w shippingTime mam null?"

Innymi słowy:
Jakie są defaultowe wartości dla poszczególnych metod dostaw i czy można je jakoś pobrać przez api?

**Comment by MartaNowaczyk** [comment]
@neldh przepraszam nie zrozumiałam od razu o co ci chodzi. Rzeczywiście, nie można nigdzie pobrać tych danych, które są domyślne ani nie zwracamy ich w responsie pytając o dany cennik dostawy. 
Czy zwracanie wartości domyślnych tutaj:
``` 
"shippingTime": {
                "from": "PT24H",
                "to": "PT72H"```

wystarczy? Nie mówię, że uda nam się to od razu zrobić, ale chciałabym określić na początek potrzeby.

**Comment by neldh** [comment]
tak, to by mi calkowicie wystarczylo w takim wypdaku

**Comment by MartaNowaczyk** [comment]
@neldh dzięki za informację. W takim razie zgłoszę taką potrzebę do odpowiedniego zespołu.
