### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by mercheo** [allegro/allegro-api#1222]
Proszę o aktywację konta sprzedawcy w Sandboksie: login **mercheo**.

**Comment by MartaNowaczyk** [comment]
Twoje konto powinno być już aktywne. Aby w pełni aktywować konto firmowe musisz przejść do zakładki moje konto i wysłać do nas dowolne 2 pliki.

**Comment by mercheo** [comment]
Wysłałem prawie dobę temu i nic...

**Comment by MartaNowaczyk** [comment]
sprawdź teraz :)

**Comment by chryssalid** [comment]
@MartaNowaczyk u mnie podobnie, napisane jest: "Nieaktywne - trwa weryfikacja Twoich danych." - i tak trwa sobie od 14 dni... Login **KsiazkiNieGryza**

**Comment by MartaNowaczyk** [comment]
@chryssalid aktywowałam ci konto. Teraz prześlij dwa dowolne pliki (zakładka moje konto)

**Comment by chryssalid** [comment]
Poszło. Macie pełno takich wątków - nie można tego jakoś zautomatyzować?

**Comment by PawelTaberski** [comment]
Pracujemy nad tym, ale obecnie musimy sobie jakoś radzić :-)

**Comment by Cupik83** [comment]
Można prosić o aktywację konta TestTiO :)

**Comment by PawelTaberski** [comment]
@Cupik83 Aktywowałem Twoje konto

**Comment by daareck** [comment]
Proszę o aktywację konta: Client:44120377

**Comment by MartaNowaczyk** [comment]
@daareck uzupełnij jeszcze proszę dane dla konta:

- Imię i nazwisko  
- Telefon(y)
- Ulica
- Kod, Miasto
- Województwo
Jeśli chcesz mieć aktywowane konto firma prześlij do nas dowolne dwa pliki (musisz przejść do zakładki moje konto).

**Comment by daareck** [comment]
Przy próbie uzupełnienia numeru telefonu otrzymuję komunikat "Coś poszło nie tak. Odczekaj chwilę i spróbuj ponownie.". Przy poprzednich próbach wyskakiwało okno do wpisania kodu sms, ale ten do mnie nie docierał.

**Comment by daareck** [comment]
Wygląda na to, że można zmienić telefon przez zakładkę Ustawienia->Dane konta Allegro.

**Comment by MartaNowaczyk** [comment]
Konto jest już aktywne

**Comment by gggep** [comment]
Proszę o aktywację konta: gepard

**Comment by MartaNowaczyk** [comment]
@gggep konto zwykłe aktywowane.

**Comment by magik092** [comment]
Czołem!
Coś się podziało dziwnego na sandboxie? Przy próbie logowania na oba konta dostaję błąd **Login, e-mail lub hasło są nieprawidłowe** pomimo, że godzinę temu te dane działały. Przelogowałem się w momencie jak w zakładce Wpłaty od kupujących nic się nie wyświetlało.
Przy próbie resetu hasła dostaję w konsoli błąd 500 (https://ibb.co/Kb9rSGN).

Owe konta to: SMA-Asport oraz magik092.

**Comment by MartaNowaczyk** [comment]
@magik092 tak jak pisałam w podłączonym wątku: wiemy o problemie i pracujemy nad jego rozwiązaniem.

**Comment by qrczak0** [comment]
Prosze o aktywację sprzedaży konta **qrczak0**

**Comment by PawelTaberski** [comment]
@qrczak0 Gotowe, konto aktywne
