### ISSUE TITLE
"ClientId does not match authenticated client"

### ISSUE THREAD

**Issue by bartosz-macczak** [allegro/allegro-api#1224]
Stworzyłem poniższą metodę w celu uwierzytelnienia aplikacji (zwracać ma min. device_code). Niestety, dostaję informację o złym client_id. Czy jest ona umieszczona w requescie w poprawnym formacie?
 ```
public string login()
        {
            var client = new RestClient("https://allegro.pl");
            var request = new RestRequest
            {
                Method = Method.POST,
                Resource = "/auth/oauth/device"
            };
            request.AddHeader("Authorization","Basic MjA1M2...mVaNg==");
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");

            Body body = new Body()
            {
                client_id = "2053....351"
            };
            string json = JsonConvert.SerializeObject(body, Formatting.Indented);
            request.RequestFormat = DataFormat.Json;
            request.AddJsonBody(json);

            IRestResponse response = client.Execute(request);
            var content = response.Content;

            MessageBox.Show(content);
            return content;
        }
```

**Comment by MartaNowaczyk** [comment]
Prowadzimy wsparcie dla języków w jakich dochodzi do ostatecznej komunikacji z naszymi serwerami, dlatego jeśli chcesz podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1224. Sprawdzę w czym jest problem.

**Comment by MartaNowaczyk** [comment]
@bartosz-macczak wysyłasz JSON-a, a powinieneś użyć x-www-form-urlencoded [#userDeviceFlow](https://developer.allegro.pl/auth/#userDeviceFlow)

**Comment by bartosz-macczak** [comment]
Problem rozwiązałem wysyłając client_id przez AddParameter, a nie AddJsonBody.

**Comment by martasobota** [comment]
Proszę o pomoc przy tym samym błędzie, domyślnie idzie `x-www-form-urlencoded`, a `client_id:client_secret` są domyślnie kodowane w `base64`:

```
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

client = BackendApplicationClient(client_id=client_id)
oauth = OAuth2Session(client=client)
token = oauth.fetch_token(token_url='https://allegro.pl/auth/oauth/device', client_id=client_id, client_secret=client_secret)
```

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełen request w formacie danych cURL wraz z response z dopiskiem GitHub #1224.

**Comment by amazur31** [comment]
Request jaki wychodzi:
`POST https://allegro.pl.allegrosandbox.pl/auth/oauth/device HTTP/1.1
Authorization: Basic <base64 z clientid:clientsecret>
Content-Type: application/x-www-form-urlencoded
Accept: application/json, text/json, text/x-json, text/javascript
User-Agent: RestSharp/106.0.0.0
Host: allegro.pl.allegrosandbox.pl
Content-Length: 48
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{"client_id": "<clientid>"}`

Otrzymuję zwrotkę z kodem 400 - Bad Request
`{"error":"invalid_request","error_description":"ClientId does not match authenticated client."}`
Fiddler normalnie pokazuje zdekodowanego Authorization, gdzie clientId zgadza się z tym który przesyłam w body.

Kod C# którego używam:
`
            string BaseURL = "https://allegro.pl.allegrosandbox.pl";
            var client = new RestClient(BaseURL);
            client.UseJson();
            client.UseNewtonsoftJson();
            
            var request = new RestRequest("/auth/oauth/device");
            request.RequestFormat = DataFormat.Json;
            request.AddHeader("Content-type", "application/json");
            request.AddHeader("Authorization", "Basic "+ Base64Encode("<clientId>:<clientSecret>"));
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddJsonBody(new { client_id = "<clientId>" });
            var zwrotka = client.Post(request);`

**Comment by amazur31** [comment]
Naprawione. Próbowałem wcześniej przez AddParameter tak jak autor tematu napisał, ale problem ciągle występował. Zmieniłem kolejność dodawania parametrów i zwraca kod autoryzacyjny. Wrzucam kod który działa.

> 
>            var request = new RestRequest("/auth/oauth/device");
>             request.RequestFormat = DataFormat.Json;
>             request.AddHeader("Content-type", "application/json");
>             request.AddHeader("Authorization", "Basic "+ Base64Encode("[clientid]:[clientsecret]"));
>             request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
>             request.AddParameter("client_id", "[clientsecret]");

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się naprawić problem. Dziękuję za udostępnienie przykładu dla innych użytkowników.
