### ISSUE TITLE
Filtrowanie /offers/listing

### ISSUE THREAD

**Issue by pmacialek** [allegro/allegro-api#1225]
Witam,

Mam pytanie dotyczące REST API, metody /offers/listing.
Jakie są możliwości filtrowania rezultatów pod względem wartości podczas konstruowania zapytania?
Przykładowo, filtrowanie przy użyciu &sellingMode.format=BUY_NOW działa prawidłowo; Czy jest gdzieś dostępna dokumentacja, które pola są a które nie są dostępne do filtrowania? (Czy są to pola zawarte w odpowiedzi, w sekcji filters?)

W szczególności interesuje mnie pole sellingMode.popularity i filtrowanie względem jego wartości.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
@pmacialek coś tam się znajdzie ;) zerknij do naszej [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListing) i [poradnika](https://developer.allegro.pl/listing/)
