### ISSUE TITLE
Problem z publikacją oferty

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#1226]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nie ma możliwości poprawnego opublikowania aukcji, podczas gdy tworzy się prawidłowy szkic (przykłady: 7855655595, 7855642581, 7855634699). Szkice nie zawierają błędów walidacji, podczas publikacji aukcji z użyciem zasobu /sale/offer-publication-commands/{commandId} nie pojawia się żaden błąd.

Zasób GET /sale/offer-publication-commands/{commandId} zwraca status FAIL dla wszystkich ww. aukcji.

Przykładowy command ID: 6ee2ee2a-61ed-4c25-a901-10b78a604581 
Myślę, że same requesty nie są tutaj potrzebne, ponieważ nie występuje problem w komunikacji, a w samym działaniu wewnątrz.

Proszę o informację, co może być powodem przekazania statusu FAIL dla publikacji oferty, podczas gdy szkic nie zawiera błędów.

**Comment by MartaNowaczyk** [comment]
@ikowol czasem warto podesłać requesty, bo w nich są wszystkie informcje. Napisałeś, że walidacja nie zgłasza błędów, a w szkicu 7855655595 brakuje czasu wysyłki. Sprawdź pozostałe i spróbuj ponownie wystawić. Jeśli nie dostałeś  błędu walidacji dla PUT /sale/offers/{offerId} lub nadal będzie problem podeślij requesty i responsy.

**Comment by lkowol** [comment]
Rzeczywiście, brakuje czasu wysyłki. Niemniej jednak walidacja tej informacji nie zawiera. Załączam wynik odpytania o ofertę:

`{"id":"7855655595","name":"Testowa aukcja","category":{"id":"122618"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null}],"ean":"4007630000116","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>tekst</p>"}]}]},"compatibilityList":null,"images":[{"url":"https://a.allegroimg.com/original/119ff2/1c2900b441ea8991a6d553887ca2"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"123","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":"PT168H","status":"INACTIVE","startingAt":null,"endingAt":null},"delivery":{"shippingRates":{"id":"0ed2e1e2-e79b-4e7b-b28e-2fd094ca3c0b"},"handlingTime":null,"additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT_MARGIN"},"afterSalesServices":{"impliedWarranty":{"id":"e949e494-34e1-450b-86df-228617c6ec29"},"returnPolicy":{"id":"dae09f3a-d240-4d09-bba2-b955789156f0"},"warranty":{"id":"1d9cc64e-3f4d-465f-96cd-2fb5d8c19e3a"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"SLASKIE","city":"Gliwice","postCode":"44-100"},"external":{"id":"testtestasdf"},"attachments":[],"contact":null,"validation":{"errors":[],"validatedAt":"2019-02-20T10:58:36.123Z"},"createdAt":"2019-02-20T10:58:36Z","updatedAt":"2019-02-20T10:58:36.124Z"}`

Domniemywam, że problem wynika z faktu, że wartość pola handlingTime dla określonych warunków (format ADVERTISEMENT) jest opcjonalna i pole nie jest poprawnie walidowane. Jeśli się mylę, proszę o wyprowadzenie mnie z błędu, w przeciwnym wypadku sugeruję naprawę problemu, bo to dosyć mylące :)

Niemniej jednak, dodanie czasu wysyłki problem rozwiązało dla nowej aukcji. Dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Dzięki, problem z walidacją może być dlatego, że kiedyś ten parametr nie był wymagany. Przetestuję to jeszcze i zgłoszę poprawkę, bo taka sytuacja nie może mieć miejsca.

**Comment by chryssalid** [comment]
@MartaNowaczyk To może ja przy okazji dorzucę takie spostrzeżenie - jeśli walniemy się w akcji i damy np. ACTIVE zamiast ACTIVATE to dostaniemy piękny, nic nie mówiący nam komunikat "An error occured." :D Warto by odnieść się do nieprawidłowej wartości w tym polu.

**Comment by MartaNowaczyk** [comment]
@chryssalid dzięki, przekażę do zespołu, który zajmuje się zasobami do publikacji oferty.
