### ISSUE TITLE
Identyfikator danych kontaktowych dla ogłoszeń ?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1227]
Witam,
Zgodnie z dokumentacją aby uzyskać identyfikator danych kontaktowych muszę wykonać GET na 
/sale/offer-contacts?seller.id={Seller_ID}

po wykonaniu operacji dostaję:
$VAR1 = {
          'contacts' => []
        };

co przypuszczalnie oznacza że nie jest zdefiniowany kontakt dla ofert, jeżeli tak to prosiłbym o informację gdzie się go definiuje w panelu na stronie ?

Generalnie mam wszystko ustawione co można ustawić w zakładce: Ustawienia sprzedaży
Id sprzedawcy: 44108242.

**Comment by AssAssIn1909** [comment]
Jedyne miejsce gdzie znalazłem ustawianie kontaktów to na ofertach o typie "Ogłoszenia" (Kategoria "ogloszenia i uslugi"). Też dość długo tego szukałem

**Comment by MartaNowaczyk** [comment]
@AleksyZajac tak jak pisze AssAssIn1909 na froncie możesz je dodać wypełniając formularz wystawiania ogłoszenia. Przez API masz metodę POST. Więcej znajdziesz [tutaj](https://developer.allegro.pl/news/2018-01-17-news_zarzadzanie_kontaktami/).
