### ISSUE TITLE
Opcje faktury dla kont Firma 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#123]
Zgodnie z informacja https://allegro.pl/pomoc/aktualnosci/opcje-faktury-w-formularzu-wystawiania-obowiazkowe-dla-kont-firma-z8nnDnvDMUW
pole 
<img width="505" alt="zrzut ekranu 2018-04-08 o 23 49 33" src="https://user-images.githubusercontent.com/1530496/38472929-9248885e-3b87-11e8-80ec-2e2bf5e8bf91.png">
jest obowiazkowe, przy czym UI allegro pozwala na wybranie opcji 'nie wystawiam faktury' 

W fid 14 brak takiej opcji. Definicja fida wyglada tak:
Zwykły przelew|-|-|-|Inne rodzaje płatności|Wystawiam faktury VAT|Wystawiam faktury VAT-marża|Wystawiam faktury bez VAT
1|2|4|8|16|32|64|128

W jaki zatem sposób przesłać przez api opcje 'nie wystawiam faktury' dla kont typu firma ?

**Comment by MarcinLuczak** [comment]
@yncki W tym fidzie możesz wybrać więcej niż jedną wartość. Aby to zrobić, podaj sumę bitową, czyli sumę wartości poszczególnych opcji. Czyli jeśli chcesz wybrać dwie opcje, np. Zwykły przelew oraz Inne rodzaje płatności, musisz przekazać wartość 16 (odpowiednio 1 + 16).

Jeśli nie chcesz zaznaczać żadnych opcji dot. faktury, po prostu nie korzystaj z wartości przypisanych do opcji faktury.
