### ISSUE TITLE
Dziennik zmian oferty?

### ISSUE THREAD

**Issue by MasterSlynx** [allegro/allegro-api#1230]
Zgodnie z dokumentacją na stronie [https://developer.allegro.pl/my_offers/#3](url) jest możliwość masowej zmiany kilku opcji w ofertach - to samo można wykonać z poziomu interfejsu. Zgodnie z informacją "skądś" wykonanie zadania może zająć do godziny. Czy jest jakaś możliwość pobrania informacji dotyczących wszystkich zmian wprowadzonych w ramach danej oferty?
Przykładowo, zmiany ilości towaru z poziomu API, zmiany ceny przez użytkownika z poziomy portalu, etc.
Rozwiązanie jest potrzebne w przypadku dużych klientów u których zmiany w ramach danej oferty (rabaty/uzupełnianie ilości) wprowadzają różne osoby i czasami niezbędny jest taki log.
Pytam, bo jestem trochę zdziwiony, że nie ma nic takiego w dokumentacji - albo przeoczyłem:roll_eyes:

**Comment by MartaNowaczyk** [comment]
nie przeoczyłeś, nie ma takiej opcji na ten moment i nie planujemy jej w najbliższym czasie. JEdnak cały czas rozwijamy REST API, także jeśli miałaby się pojawić taka opcja na pewno damy znać w oddzielnym komunikacie. Dzięki za opisanie potrzeby - przekażę do odpowiedniego zespołu.

**Comment by pietrach** [comment]
@MartaNowaczyk skoro nie planujecie wdrożenia dziennika zmian w najbliższym czasie to jak mogę pobrać aukcje, które zostały ostatnio zakończone lub ktoś złożył w nich ofertę ?

**Comment by MartaNowaczyk** [comment]
@pietrach to że teraz nie mamy tego w planach, nie znaczy, że nie mamy tego na uwadze. W #1191 też zgłaszano nam taką potrzebę.  Obserwuj proszę wątek, bo zamieścimy tam odpowiedzi dotyczące zgłaszanych potrzeb.

**Comment by MartaNowaczyk** [comment]
by pobrać zakończone licytacje dla GET  /sale/offers wybierz filtr AUCTION i ENDED Więcej [tutaj](https://developer.allegro.pl/my_offers/)

**Comment by pietrach** [comment]
Ja wiem jak pobrać zakończone ale mi chodzi aby pobrać zakończone w ciągu załóżmy ostatnich 3h a nie wszystko naraz za każdym razem

**Comment by MartaNowaczyk** [comment]
Rozumiem, po prostu chciałam ci dać pełną odpowiedź.
