### ISSUE TITLE
[REST API] "Panther Kallista" => rawItems: Please do not use forbidden words: lista.

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1232]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zbyt "luźne" sprawdzanie słów "zakazanych". 
Nie można dodać do `compatibilityList` auta "Panther Kallista"

**Comment by MartaNowaczyk** [comment]
@mindc potwierdzam problem z walidacją, zgłosiłam to do zmiany.

**Comment by MartaNowaczyk** [comment]
@mindc zrobione, sprawdź czy możesz dodać.

**Comment by mindc** [comment]
@MartaNowaczyk 
Nie było to dla mnie krytyczne, ale dziękuję, działa...

Jednak jak już jesteśmy w temacie tego auta... Front wyświetla to niepoprawnie, nie rozpoznaje marki samochodu i podpina do istniejących wpisów (w tym przypadku do Forda)

![screenshot_154](https://user-images.githubusercontent.com/1355190/53169957-18b4ec00-35df-11e9-8f35-6932d04c4597.png)

**Comment by MartaNowaczyk** [comment]
@mindc potwierdzam problem. Działamy w tym temacie.

**Comment by MartaNowaczyk** [comment]
@mindc wdrożyliśmy poprawkę.

**Comment by mindc** [comment]
@MartaNowaczyk 
potwierdzam usunięcie problemu
dziękuję
