### ISSUE TITLE
[RestAPI] Limity dla przesyłanych zdjęć

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1234]
Przy próbie wysłania zdjęć przez `POST sale/images` dostaje na przemian 
`ilość pikseli w obrazie jest zbyt duża`
z `An error occured` z kodem 415

Jaki jest limit rozmiaru zdjęcia (2560x2560?) ale [tutaj](https://allegro.pl/dla-sprzedajacych/zasady-dla-pierwszego-zdjecia-miniaturki-w-ofercie-vKgeLv4YXi4) piszecie że zdjęcia są automatycznie skalowane, czy to się tyczy również zdjęć wysyłanych przez API? Jeśli tak do dlaczego dostaję błąd `ilość pikseli w obrazie jest zbyt duża` Co to w ogóle znaczy? Chodzi o dpi czy co? Jaka jest maksymalna dopuszczalna waga dla zdjęć przesyłanych przez api i czy te wartości są inne w zależności od sposobu przesyłania zdjęć (url/content).

**Comment by Sojtin** [comment]
może np. na przykładzie, dlaczego załączone zdjęcie nie może być przesłane? Próbuje wysłać przez przeglądarkę, dostaje info
"Nie udało się dodać zdjęcia"
"Wystąpił błąd podczas dodawania obrazka."

Wymiary 1886x2559 96dpi
Rozmiar: 1,49MB

![rtmcrlnqw](https://user-images.githubusercontent.com/8439069/53163339-231aba00-35ce-11e9-8ac4-e44607ec292e.jpg)

**Comment by MartaNowaczyk** [comment]
@sojtin maksymalny rozmiar zdjęcia to po prostu 2560 x 2560 pikseli

Udało mi się dodać przykładowe zdjęcie. Zerknij czy w nagłówku w content-type masz dla tej fotki image/jpeg

**Comment by Sojtin** [comment]
@MartaNowaczyk Czyli automatycznie skalowanie nie działa przy dodawaniu zdjęć przez api?
Wagowego ograniczenia nie ma?
To konkretnie zdjęcie akurat nie przechodzi przez przeglądarkę jak pisałem.

**Comment by MartaNowaczyk** [comment]
@Sojtin tak, nie mamy automatycznego skalowania w API. Wagowego ograniczenia nie ma. Przez przeglądarkę też mi przeszło.

**Comment by Sojtin** [comment]
@MartaNowaczyk a mi nie, próbuje na sandboksie, niektóre zdjęcia przechodzą a to cały czas nie.
![eeee](https://user-images.githubusercontent.com/8439069/53166554-e94db180-35d5-11e9-9c03-9bb8213c257f.jpg)

**Comment by MartaNowaczyk** [comment]
@Sojtin ja dodawałam na produkcji. Sprawdzę i dam znać.

**Comment by MartaNowaczyk** [comment]
Rzeczywiście na sandboxie też mam ten problem. Możliwe, że walidacja zdjęć nie odzwierciedla tej z produkcji. Sprawdzimy.

**Comment by MartaNowaczyk** [comment]
@Sojtin teraz powinno być ok. Sprawdź proszę.

**Comment by Sojtin** [comment]
@MartaNowaczyk dalej to samo przez przeglądarke

**Comment by MartaNowaczyk** [comment]
@Sojtin oj, niedobrze. Wczoraj dodałam. Sprawdzamy dalej.

**Comment by MartaNowaczyk** [comment]
@Sojtin sprawdź proszę. Udało mi się dodać, więc mam nadzieję, że u ciebie też będzie ok.
