### ISSUE TITLE
Usuwanie zaufanych urządzeń przez REST ?

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1235]
cześć,
czy istnieje metoda która przez REST mogę kasować zaufane urządzenia ? (dwuetapowe logowanie)

teraz takich userów kasuję ręcznie, kneflem z poziomu mojego allegro, ale jest to bardzo upierdliwe, zwłaszcza przy 12 kontach.

**Comment by MartaNowaczyk** [comment]
@centrumelektroniki nie ma takiej możliwości. Na ten moment nie mamy też tego w planach. Zgłoszę to jako sugestię.

**Comment by centrumelektroniki** [comment]
Raczej nie powinno to być skomplikowane ? skoro istnieje już w moim allegro :)

**Comment by MartaNowaczyk** [comment]
:)

**Comment by centrumelektroniki** [comment]
Będę wdzięczny jeśli coś ruszy w temacie tej propozycji, nie śledzę na bieżąco Państwa aktualności niestety.

**Comment by centrumelektroniki** [comment]
podbijam

**Comment by MartaNowaczyk** [comment]
Nie ma jeszcze konkretnej decyzji w tej sprawie. Na ten moment skupiamy się na funkcjonalnościach, które pozwolą przejść z webAPI na REST API.
