### ISSUE TITLE
ID płatności w mailu w przypadku zakupu za pobraniem

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#1236]
Czy w niedalekiej przyszłość pojawi się nowy identyfikator płatności w mailach od Allegro w przypadku zakupów za pobraniem? Obecnie  jest tylko stare 'transId'
W przypadku płatności z góry payment.Id można wyciągnąć z maila, w przypadku pobrania niestety nie.

albo (jeszcze lepsza opcja)

Czy w mailach od Allegro będzie w przyszłość podawany nowy identyfikator zamówienia checkoutForm.id - zarówno w przypadku płatności z góry jak i za pobraniem?

Z góry dziękuje za odpowiedź

**Comment by MartaNowaczyk** [comment]
W przypadku zakupu za pobraniem o jaki mail chodzi? Z potwierdzeniem wypełnienia formularza dostawy i wybraniem płatności? Gdy nie ma płatności, nie może być ID płatności. 

Nie wiem czy cię dobrze zrozumiałam, dlatego w razie czego doprecyzuj pytanie.

Jeśli chodzi o checkoutForm.id to zgłoszę to do odpowiedniego zespołu jako sugestię, bo w najbliższym czasie nie mamy tego w planach.

**Comment by Draken79** [comment]
Jak najbardziej jest numer płatności w przypadku zakupu za pobraniem. Jest nawet widoczny w szczegółach w zakładce zamówienia. Dziękuję za zgłoszenie sugestii odnośnie checkoutForm.id. W systemach opartych na mailach bardzo ułatwi to pracę.

**Comment by MartaNowaczyk** [comment]
Zgłosiłam się z tym do zespołu, który zajmuje się tym tematem. Na ten moment nie będzie nowego identyfikatora. Wezmą to pod uwagę, gdy w przyszłości będą coś w nich zmieniać.
