### ISSUE TITLE
Pytanie do sprzedającego przez API

### ISSUE THREAD

**Issue by bbankowski** [allegro/allegro-api#1237]
Witam,

1. Czy da się pobierać przez API wiadomości, które klienci wysyłają w ramach funkcjonalności "Pytanie do sprzedającego"?

2. Zastanawiam się, jak po zmianach w tej funkcji w związku z https://allegro.pl/dla-sprzedajacych/zabezpieczamy-wasze-adresy-e-mail-MMyz9qbL2u0 będę mógł zidentyfikować klienta - wcześniej robiłem to po jego adresie e-mail, który był w nagłówku Reply-to. Czy są jakieś sugestie jak można to robić po w.w. zmianach?

**Comment by MartaNowaczyk** [comment]
1. Przez API w tej chwili nie ma takiej możliwości. Na najbliższy czas nie mamy też tego w planach. Zgłoszę to jako sugestię.

2. Nie znam innej możliwości, jednak w sprawach niezwiązanych z API najlepiej pisać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)
