### ISSUE TITLE
Rest API - pytanie o filtry do order/checkout-forms

### ISSUE THREAD

**Issue by lkeska** [allegro/allegro-api#1239]
W dokumentacji do checkout-forms mamy informacje, ze mozna wyniki filtrowac wg daty. Mam zestaw eventow o statusie READY_FOR_PROCESSING i chce do tych konkretnych eventow wybrac formularze pozakupowe. Wykonuje request na adres:

https://api.allegro.pl/order/checkout-forms?status=READY_FOR_PROCESSING&lineItems.boughtAt.lte%3D2019-02-21T14%3A56%3A43.647Z%26lineItems.boughtAt.gte%3D2019-01-16T11%3A08%3A26.662Z

I dostaje liste 10 formularzy. Niestety, jesli chce zawezic te liste, nic sie nie zmienia - niezaleznie od tego, czy zamienie daty miejscami (dam wczesniejsza tam gdzie jest lte a pozniejsza tam gdzie gte), czy wpisze np daty z roznica jednego dnia, zawsze dostaje te same 10 formularzy, wlacznie z tymi transakcjami ktore byly zrealizowane przed lub po danym zakresie dat. 
W jaki sposob dzialaja te filtry po datach? Jak tego uzywac?

**Comment by Draken79** [comment]
na pierwszy rzut oka to bym zmienił '%26' na '&' przed lineItems.boughtAt.gte.. ale pewnie próbowałeś. 
U mnie działa to całkiem dobrze, z tym że ja korzystam tylko z lte

**Comment by MartaNowaczyk** [comment]
@lkeska no i jeszcze %26 na "=" i powinno działać. Poprawnie masz tak:
```/order/checkout-forms?status=READY_FOR_PROCESSING&lineItems.boughtAt.lte=2019-02-21T14%3A56%3A43.647Z&lineItems.boughtAt.gte=2019-01-16T11%3A08%3A26.662Z```
