### ISSUE TITLE
Sandbox AppDevice auth

### ISSUE THREAD

**Issue by LickityPero** [allegro/allegro-api#1240]
Hello, I'm starting with Allegro and I created a test account to try to get working with the sandbox environment. My account in the sandbox doesn't have the papers/payment done since I can't yet provide them for the company I work for.

I followed the tutorials for an application of type "device" that doesn't present a login screen, I created the application and got the client id and client secret.

I'm trying to connect to the sandbox endpoint https://allegro.pl.allegrosandbox.pl/auth/oauth/device which i suppose is the correct one. I send my petition with postman (putting in "my_client_id" my data, etc):

curl -X POST \
  'https://allegro.pl.allegrosandbox.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(my_client_id:my_client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={my_client_id}'

However, no matter how i make the petition, I always get the same answer:
    "error": "Unauthorized",
    "error_description": "Full authentication is required to access this resource"

Am I missing anything in my petition? Do I need further authorization in my account to do this?
I also tried with the url https://allegro.pl.allegrosandbox.pl/auth/oauth but the results are the same.

Thank you very much, and excuse me about the message being in english since I don't speak polish.

**Comment by KrzysztofLukanowski** [comment]
Hello, are you sure you encrypted client_id and client_secret with ":" sign to base64? You should encrypt "client_id:client_secret".

**Comment by LickityPero** [comment]
Thank you for your answer, I have encoded with all the possible combinations:

I tried with "my_client_id" encoded in base 64, then the : remain, and then putting "my_client_secret" in base 64. Did not work.

Also tried with "my_client_id:my_client_secret" encoded to base 64, it did not work either.

I also tried with putting the my_client_id in the -d parameter both encrypted and not in both cases, neither worked.

Maybe I need to do any previous step that I don't know?

Thank you.

**Comment by KrzysztofLukanowski** [comment]
Do you remember about: 
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'client_id={client_id}'
? 

These informations you should not encode.

**Comment by KrzysztofLukanowski** [comment]
Be sure that you  have added "basic" before "my_client_id:my_client_secret".

**Comment by LickityPero** [comment]
Thank you for the help Krzysztof and excuse me for the delay in my answer. 

I have done as you indicated, as I indicated in my first message, the text
-H 'Content-Type: application/x-www-form-urlencoded' 
-d 'client_id={client_id}'
is already present in my petition to the server.

The only encoded information is "clientid;clientsecret" and the text Basic is also present in my message.

I also tried to log to different urls:
https://allegro.pl.allegrosandbox.pl/auth/oauth/ and https://allegro.pl.allegrosandbox.pl/auth/ but with the same results.

As the application is only in the test environment and I can delete it later, would it be fine if I post this application client_id and client_secret? That way I can show you the actual petition i'm putting in postman.

About my test environment account, could you please check if a need further activation?

Thank you kindly.

**Comment by LickityPero** [comment]
I have checked the forum for similar problems, it looks like everyone who got the same message:
    "error_description": "Full authentication is required to access this resource"
had the issue because the sandbox account was not activated. Could you please check if I need any further activation?

Thank you very much.

**Comment by KrzysztofLukanowski** [comment]
Please, give me the name of yours account or e-mail address on allegrosandbox.

**Comment by LickityPero** [comment]
Indeed, it is the following address jorgetadeo.a4b@gmail.com

**Comment by KrzysztofLukanowski** [comment]
Ask for the full account activate in this [tab](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php), please. You should click button i "Aktywacja konta" tab and go to the next steps.

**Comment by LickityPero** [comment]
I did as you indicated, now i'll have to wait for the verification of the account, i'll indicate you if i can do the authentication so the thread can be closed.

Thank you very much Krzysztof.

**Comment by LickityPero** [comment]
Hello Krzysztof, yesterday I did as you indicated but I still got no answer even though is only for the sandbox environment.

Do I need to do something else? Can you activate my account?

Thank you.

**Comment by PawelTaberski** [comment]
What is the login of account you try to activate?

**Comment by LickityPero** [comment]
Hello Pawel, the account is in sandbox, the account name is Testing_BB and the address is jorgetadeo.a4b@gmail.com

**Comment by PawelTaberski** [comment]
I had pre-activate your account, now you should send by Moje Allegro any 2 files.
