### ISSUE TITLE
Odświeżenie drzewka kategorii na środowisku testowym

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#1241]
:bulb: **Sugestia**
Wspominałem już o tym ( #1139  ). Jednak temat tamtego wątku był troche inny. Postanowiłem, więc utworzyć osobny do tego.
Proszę o odświeżenie drzewka kategorii na sandboxie. Dalej jest bardzo nieaktualne, co utrudnia nam oraz klientowi testowanie aplikacji.

**Comment by MartaNowaczyk** [comment]
@AssAssIn1909 zgłosiłam taką potrzebę. Będziemy pracować nad automatycznym odświeżaniem, jednak nie jest to najbliższa przyszłość. Raczej kilka miesięcy.  Na ten moment możecie zgłaszać to, co się nie zgadza, a my odświeżymy te dane. Jeśli natrafiłeś na nieaktualne dane podaj je proszę.
