### ISSUE TITLE
offer-listing build filter query request

### ISSUE THREAD

**Issue by HalasPavlo** [allegro/allegro-api#1242]
I need to send two filters belonging to the same group in the request. To do this, I need to create the following request: offers/listing?category.id=258786&offset=0&limit=16&sort=relevance&**parameter.209158=320201& parameter.209158=238094&parameter.209158=320209.**

Is it possible to change so that the filters are grouped into a filter group in the request: offers/listing?category.id=258786&offset=0&limit=16&sort=relevance&**parameter.209158=320201,238094,320209.**

This will simplify the writing of queries a lot, there will be no duplication of keys in the array of parameters.

**Comment by MartaNowaczyk** [comment]
At the moment, we do not plan to change it. Although thank you for your suggestion, we will consider it in our development plans for public API. But keep in mind that implementing this isn't certain.
