### ISSUE TITLE
Rest API - Search offers

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#1243]
Witam
proszę o informacje czy metoda Search offers będzie zwracać   
- nick sprzedającego do oferty w formie tekstowej a nie "id" 
- rozmiar z parametru np. XL (w przypadku odzieży) lub 44 (w przypadku obuwia) - aktualnie zwraca dł. wkładki w cm.
Aktualnie wymaga to tworzenia dodatkowego zapytania do każdej oferty w oparciu o dostępne biblioteki.
pozdr

**Comment by MartaNowaczyk** [comment]
@MichalOmega dla zasobu offers/listing, bo rozumiem, że o nim mówimy nazwy sprzedającego nie pobierzesz, jest tylko ID.  

Nie oznaczamy ofert rozmiarami (parametrami), ale dla każdego wyszukiwania podajemy w odpowiedzi filtry jakich można użyć. Przykładowo wyszukiwanie można ograniczyć do obuwia damskiego w rozmiarze 42 i 2/3 korzystając z zapytania:
/offers/listing?category.id=531&parameter.26388=221517

dla sukienek w rozmiarze XL:
/offers/listing?category.id=124264&parameter.3806=6

Analogicznie trzeba skorzystać z filtrów dla innych kategorii.
