### ISSUE TITLE
Problem z założeniem konta w Sandbox

### ISSUE THREAD

**Issue by ebartlomiej89** [allegro/allegro-api#1244]
Witam

Chciałem założyć konto w Sandbox na firmę. Niestety po przeslaniu formularza zwracany iest napis Upss... na żółtym tle. Proszę o informację w jaki sposób mam założyć konto.

**Comment by MartaNowaczyk** [comment]
@ebartlomiej89 znamy problem i pracujemy nad jego rozwiązaniem.
