### ISSUE TITLE
[Rest API] Shipping rate

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1245]
W dokumentacji do metody https://api.allegro.pl/sale/shipping-rates, obiekt rates wskazuje na pojedynczy element natomiast API akceptuje tablicę obiektów

https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST

Należy poprawić przykładowy json i opis pola

**Comment by MartaNowaczyk** [comment]
@michcio19923 dzięki, sprawdzimy i poprawimy.

**Comment by michcio19923** [comment]
W dokumentacji obiekt rates nie jest oznaczony jako wymagany a przy próbie wysyłki pustego otrzymuję błąd
 
Authorization: Bearer  ...
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json; charset=utf-8
Host: api.allegro.pl.allegrosandbox.pl
x-ms-request-root-id: E8iz2GqrH4g=
x-ms-request-id: |E8iz2GqrH4g=.214a8124_1.
Request-Id: |E8iz2GqrH4g=.214a8124_1.
Content-Length: 59
Expect: 100-continue
Connection: Keep-Alive

{"id":null,"name":"Test5","rates":null,"lastModified":null}

{"errors":[{"code":"ConstraintViolationException","message":"An error has occurred","details":null,"path":"PublicShippingRatesResource$$EnhancerBySpringCGLIB$$c3da8573.update.arg1.rates","userMessage":"Transferred data is incorrect"}]}

**Comment by MartaNowaczyk** [comment]
@michcio19923 dzięki jeszcze raz, poprawimy wszystko przy kolejnym wdrożeniu zmian na stronie.
