### ISSUE TITLE
Metoda płatności w REST API i zamówieniach

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#1246]
Czy jest jakiś sposób aby pobrać lub podejrzeć metodę płatności w nowym systemie?
W starym systemie, na karcie płatności była taka informacja (np. karta płatnicza, BZWBK24, itd).
Nietstey w zakładce zamówienia nie ma takiej informacji, nie znalazłem również takiego zasobu w REST API.
Jest to o tyle ważne, że jeśli kupujący wybrał np. 'kartę płatniczą' i wpłata nie dotarła w przeciągu godziny to wiemy, że coś było nie tak z płatnością i można się skontaktować z kupującym, który często nie zdaje sobie sprawy z tego, że płatność nie przebiegła prawidłowo. Jeśli natomiast kupujacy wybrał 'przelew tradycyjny' to wtedy wiemy, że należy spokojnie czekać na wpłatę. 
Tak czy inaczej informacja o wybranej metodzie płatności jest niezbędna do prawidłowej i przede wszystkim szybkiej i skutecznej obsługi zamówień.

**Comment by MartaNowaczyk** [comment]
@Draken79 dzięki za opisanie potrzeby. Sprawę zgłaszam jako sugestię do zespołu, który zajmuje się zamówieniami. Jeśli taką zmianę wdrożymy damy znać w oddzielnym komunikacie.
