### ISSUE TITLE
email dot. nowej wpłaty

### ISSUE THREAD

**Issue by StworPaszczaty** [allegro/allegro-api#1247]
Wiem że nie dotyczy api tylko maili od Was wysyłanych ale nie ma innego miejsca gdzie można by to opisać aby uzyskać "techniczną" odpowiedź. 
Email dot. nowej wpłaty od klienta nie zawiera nazwy użytkownika tylko jego adres mailowy co generuje dezorientację. Dotyczy to klientów niezarejestrowanych. Nastąpiło to w ostatnich dniach (bodajże od 22.02.2019r.) wraz ze zmianą formatu (szaty i treści) maili wysyłanych do sprzedawców. Dla zarejestrowanych komplet maili zawiera nazwę użytkownika, czyli tak samo jak przed zmianą formatu maili.
Nie wiem czemu miała służyć ta zmiana... 
Czy jest to błąd i będzie to zmieniane czy to celowa zmiana?

**Comment by Draken79** [comment]
dodatkowo mail o wybraniu sposobu płatności "Allegro Finanse - Kupujący xxxxx wybrał sposób zapłaty..." zaczął teraz przychodzić dopiero po wpłacie, a nie wtedy kiedy faktycznie kupujący wypełnił FOD. Innymi słowy przychodzi kiedy status zamówienia zmieni się na 'READY_FOR_PROCESSING' a nie kiedy jest FILLED_IN - z tym też do https://allegro.pl/pomoc/kontakt? czy możecie to sprawdzić?

**Comment by MartaNowaczyk** [comment]
maile nie przychodzą w zależności od API, to API bazuje na statusach allegro, także z tym też przez formularz.
