### ISSUE TITLE
Status FILLED_IN i brak adresu dostawy

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#1250]
Dlaczego w przypadku FILLED_IN nie ma podanego adresu dostawy? Przecież kupujący musiał wypełnić FOD i podać adres dostawy.
Sytuacja z dzisiaj - od jutra jesteśmy na urlopie i chcieliśmy wysłać wszystkie zamówienia, nawet jeśli kupujący wybrał 'przelew tradycyjny', który jeszcze nie dotarł. Ale niestety nie mamy adresów dostawy.
Dodatkowo email z informacją, że kupujący wypełnił FOD też nie dochodzi (dochodzi w chwili wpłaty) - może te dwie sprawy są jakoś powiązane. W każdym razie coś się posypało w związku z ostatnimi zmianami - brak adresu w przypadku FILLED_IN, brak maili o FOD. Proszę o sprawdzenie, bo bardzo utrudnia to pracę.

**Comment by PawelTaberski** [comment]
Zgodnie z [naszym poradnikiem](https://developer.allegro.pl/orders/#01) dane odnośnie adresu dostawy otrzymasz w zamówieniach o statusie READY_FOR_PROCESSING.

**Comment by Draken79** [comment]
Czyli przyjęliście, że świat jest idealny i płatności zawsze przechodzą bez problemu?  Często jest tak, że płatność nie przechodzi i kupujący nawet o tym nie wiem. W takich sytuacjach kontaktujemy się z kupującym aby uświadomić go, że płatność nie przeszła.. Teraz po zmianach właściwie nie wiadomo co się dzieje jeśli nie ma płatności, bo nawet nie ma info o tym jaką metodę płatności wybrał kupujący. Co więcej, nie mamy jego adresu, więc po kontakcie telefonicznym i ustaleniu, że kupujący jednak chce wysyłkę za pobraniem, bo zapomniał, że nie ma na koncie pieniędzy trzeba zanotować i wprowadzić ręcznie jego adres - rozwiązanie godnego nowego REST API ;)
Nie wiem jak u innych sprzedających, ale my mamy w tygodniu przynajmniej kilka sytuacji jak wyżej.
Proszę o poważne rozważenie ww. uwag ponieważ znacząco utrudniają pracę i ostatnie zmiany są wyraźnie na gorsze, a nie na lepsze.

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem Twoje sugestie do zespołu który zajmuje się tymi zasobami, jeśli zdecydujemy się wdrożyć zmianę poinformujemy o tym w dedykowanym komunikacie.

**Comment by kuli-g** [comment]
@PawelTaberski ogólnie lepiej gdyby allegro zdecydowało się między dwoma sposobami, albo api zwraca kompletne dane/adresy nawet przy samym BOUGHT jak to robi w webapi albo zróbcie formularze dostawy obowiązkowe by zakup został w ogóle zarejestrowany. W samym lutym mam ponad 30 kliknięć "kup teraz" które w restapi mają tylko mail i numer telefonu najczęściej nieprawidłowy bo nikomu się nie chce aktualizować danych.

Teraz się dowiaduję że jeszcze przy FILLED_IN nie przekazujecie danych z formularzy...? No super, stoi za tym jakiś racjonalny powód inny niż "sprzedający używają programów które nie odróżniają adresu kontrahenta od adresu wysyłki" co jest oczywistą nieprawdą?

**Comment by PawelTaberski** [comment]
Rozumiem planujemy wdrożyć rozwiązanie, które uniemożliwi zatwierdzenie zakupu bez uzupełnienia formularza dostawy, jednakże kiedy wdrożymy takie rozwiązanie na chwilę obecną nie jestem w stanie powiedzieć.

**Comment by PawelTaberski** [comment]
Rozumiem planujemy wdrożyć rozwiązanie, które uniemożliwi zatwierdzenie zakupu bez uzupełnienia formularza dostawy, jednakże kiedy wdrożymy takie rozwiązanie na chwilę obecną nie jestem w stanie powiedzieć.

**Comment by alekskuc** [comment]
Dzień dobry, czy wiadomo już kiedy będzie dostępny adres dostawy na zamówieniach FILLED_IN?

**Comment by PatrykBocian** [comment]
@alekskuc Na tę chwilę zbieramy sugestie i potrzeby. Jeżeli zdecydujemy się na udostępnienie tych informacji dla statusu **FILLED_IN**, poinformujemy o tym w odpowiednim komunikacie.
