### ISSUE TITLE
RestAPI token expired

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1251]
W jaki sposób zarządzać odświeżaniem tokena aby on nie wygasł ?
Odświeżam token na 2h przed wygaśnięciem ale wraz pojawiają się błędy typu "Access token expired"

**Comment by PawelTaberski** [comment]
Informacje o tym jak odświeżyć token znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#refresh-token).
