### ISSUE TITLE
Sytuacje związane z brakiem możliwości edycji oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1252]
Z tego co wiem to:

1. Zmiana kategorii jest możliwa do 12 godzin od momentu wystawienia i jeśli nie ma oferty kupna
2. Tytuł oferty można zmienić jeśli nie ma ofert kupna
3. Cenę w ofercie możemy zwiększyć maksymalnie o 50 zł jeśli obecna cena oferty jest do 50 zł.
4. Cenę możemy zwiększyć maksymalnie o 100% jeśli obecna cena oferty jest większa od 50 zł

Czy te powyższe ograniczenia dalej istnieją na RestAPI ?
Czy są jeszcze jakieś ograniczenia na starym WebAPI / nowym RestAPI o których tu nie napisałem ?

Jak to rozwiązać na nowym Rest API ? Czy w takim wypadku należy zakończyć ofertę, zmienić kategorię, cenę, tytuł i wznowić ją ponownie ?

**Comment by PawelTaberski** [comment]
Ofertę przez REST API zawsze możesz wznowić pod tym samym id dlatego jeśli chcesz zmienić np. kategorie to musisz wystawić nowy przedmiot pod nowym id, ze względu m.in. na naliczoną już popularność w danej kategorii.
Oczywiście możesz zakończyć ofertę i uzupełnić stock, możesz to zrobić również w trakcie trwania oferty. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-8-complete).

**Comment by pietrach** [comment]
@PawelTaberski nie do końca uzyskałem odpowiedź na powyższe pytania.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem czego brakuje :-) Ograniczenia o których wspomniałeś jak najbardziej są, są jeszcze np obowiązkowe parametry, warunki oferty i wiele innych. Jeśli chcesz zmienić np kategorię oferty musisz wystawić nową, ze względu m.in. na zliczoną popularność. Takie rzeczy jak cenę, stock możesz edytować nawet w trakcie trwania oferty.

**Comment by pietrach** [comment]
Załóżmy że jest sytuacja, że wystawił się produkt na Allegro ale ma błędną kategorię. Od wystawienia minęło więcej niż 12h. Czy mogę zrobić tak, że zakończę tą aukcję, zmienię kategorię produktu i przypisze na nowo parametry i wznowię ją a może to można zrobić bez zakańczania ? Czy mogę zmienić tytuł oferty jeśli są złożone oferty kupna ? Jeśli nie to też na takiej samej zasadzie to robię, że zakańczam ofertę zmieniam  tytuł i wznawiam ją ponownie ?
