### ISSUE TITLE
Klucz Web API SOAP

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#1253]
Witam,
Jak wygenerować klucz do SOAP?
Na stronie https://apps.developer.allegro.pl/ mam tylko możliwość generowania do resta.
Do SOAP zniknęło.
Konto na którym to tworzę jest nowe, na starszych kontach klucz już mam.
Czyżby "nowi" nie mieli już tej możliwości?
 
![rest](https://user-images.githubusercontent.com/48016962/53411109-ef70d300-39c5-11e9-945f-3d09fdba0d13.jpg)
![rest2](https://user-images.githubusercontent.com/48016962/53411111-ef70d300-39c5-11e9-8f14-220953896c46.jpg)

**Comment by PawelTaberski** [comment]
Klucz do WebAPI znajduje się w kolumnie Client ID / WebAPI key :-)
Jest on dłuższy i nie składa się tylko z cyfr, ale jak najbardziej działa :-)

**Comment by jaceklodz** [comment]
> Klucz do WebAPI znajduje się w kolumnie Client ID / WebAPI key :-)
> Jest on dłuższy i nie składa się tylko z cyfr, ale jak najbardziej działa :-)

Mówisz o SOAP? Ja potrzebuję soap a nie Client ID z Resta. 
U mnie wygląda to tak:

![api](https://user-images.githubusercontent.com/48016962/53421301-b9d7e400-39dd-11e9-9770-7d4f320cc3a3.png)

**Comment by PawelTaberski** [comment]
Tak, jak napisałem jak najbardziej będą działały SOAP-owo, po prostu te utworzone jeszcze przed zmianą, które są w innym formacie umieściliśmy na samym końcu listy.
