### ISSUE TITLE
RestAPI Problem z metodą PUT /sale/offer-quantity-change-commands/

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#1254]
Witam, mam problem z wywołaniem metody PUT /sale/offer-quantity-change-commands/

Zapytania:
{"modification": {"changeType": "FIXED","value": 50},"offerCriteria": [{"offers": [{"id": "123456"}],"type": "CONTAINS_OFFERS"}]}

W odpowiedzi serwera otrzymuje następujący komunikat: 
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-quantity-change-commands/02e41750-4c2b-4adc-aa6b-6a2e42420356","userMessage":null}]}

Kod błędu 400 co z dokumentacji oznacza źle przygotowane zapytanie, jednak struktura tabeli jest dokładnie taka sama jak w dokumentacji.

**Comment by PawelTaberski** [comment]
Przekopiowałem Twoje body i wszystko wygląda poprawnie jesteś pewny, że na wyjściu nie dodajesz jakiś dodatkowych znaków do body.

**Comment by Troian1337** [comment]
var_dump:
["content"]=>
    string(155) ""{\"modification\": {\"changeType\": \"FIXED\",\"value\": 50},\"offerCriteria\": [{\"offers\": [{\"id\": \"123456789\"}],\"type\": \"CONTAINS_OFFERS\"}]}""

oraz print_r:
[content] => "{\"modification\": {\"changeType\": \"FIXED\",\"value\": 50},\"offerCriteria\": [{\"offers\": [{\"id\": \"123456789\"}],\"type\": \"CONTAINS_OFFERS\"}]}"

**Comment by Troian1337** [comment]
Znalazłem rozwiązanie problemu, dzięki za nakierowanie okazało się że 2 razy pakowałem dane przez json_encode
