### ISSUE TITLE
Web API nowy opis - zdjęcie wysłane na serwer allegro

### ISSUE THREAD

**Issue by skozuchowicz** [allegro/allegro-api#1255]
Czy wystawiając aukcję poprzez WEB API można użyć  zdjęć dodanych na serwer allegro poprzez 
POST-a na  /sale/images?

Przy próbie wystawienia  dostaję komunikat, że: Opis zawiera zdjęcia spoza galerii: https://a.allegroimg.com/original/115f5e/b3f74368430c9f7b2f4ac856fe30

Kopiując powyższy link widzimy, że zdjęcie występuje na serwerze allegro.
Korzystam z web api z nowym opisem w którym zdjęcie zawarłem :

{"items": [{"type": "IMAGE","url": "https://a.allegroimg.com/original/115f5e/b3f74368430c9f7b2f4ac856fe30"}]}

Bez tej linii działa.

**Comment by PawelTaberski** [comment]
W przypadku WebAPI zdjęć muszą być one zakodowane w postaci base64Binary, nie możesz tam korzystać z linków. Pamiętaj, że niedługo wygaszamy metody do dodawania ofert przez WebAPI, więcej na ten temat znajdziesz tu: #1043

**Comment by skozuchowicz** [comment]
Dziękuję
