### ISSUE TITLE
RESTAPI zmiana statusu publikacji

### ISSUE THREAD

**Issue by chryssalid** [allegro/allegro-api#1256]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Zmiana statusu publikacji nie zwraca informacji w taskCount. Niezależnie od akcji ACTIVATE, END, etc. w polach taskCount są same zera (mimo, że akcje te wykonują się poprawnie i oferta jest publikowana lub zamykana). Niezależne jest to także od ilości przetwarzanych ofert.

Przykładowa odpowiedź:
`{"id":"a6cd5ab9-aea5-4720-84c9-3998dbe8f38c","taskCount":{"total":0,"success":0,"failed":0}}`

**Comment by Troian1337** [comment]
A nie chodzi tutaj o taki sam przypadek jak np z PUT /sale/offer-quantity-change-commands/{commandId} 
gdzie na początku zwraca 0 i trzeba odpytać 2 raz serwer po commandId o status zmian?

**Comment by chryssalid** [comment]
@Troian1337 wg dokumentacji nie trzeba tego robić drugi raz dla samej informacji o tym, ile było udanych operacji.

**Comment by Troian1337** [comment]
@chryssalid możliwe, ale może też być tak że w dokumentacji jest błąd, może warto spróbować drugi raz odpytać serwer, jeżeli zwróci ci informację to zgłosić to jako błąd metody/dokumentacji.

**Comment by PawelTaberski** [comment]
@chryssalid W dokumentacji wszystko jest poprawnie jeśli otrzymałeś przy publikacji same zera to poprawna odpowiedź, bo nie jesteśmy w stanie od razu stwierdzić ile ofert się opublikuje, a ile nie. Aby sprawdzić status zadania skorzystaj z GET-a. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-10-tasks).
