### ISSUE TITLE
Edycja wystawionej oferty REST API

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#1257]
Witam przychodzę z pytaniem dotyczący rest api a dokładnie PUT /sale/offers/{offerId}
Chciałem zmienić sygnaturę aukcji
`$params = array(
	'external' => array(
		'id' => 'nowa sygnatura'
	)
);
`

Jednak po wykonaniu polecenia otrzymałem komunikat o błędnym numerze oferty, więc z ciekawości zacząłem podawać kolejne parametry takie jak ID, NAME, CATEGORY i po dodaniu każdej z nich otrzymywałem komunikat o braku kolejnego parametru, moje pytanie jest takie czy aby dokonać zmiany parametru muszę podać wszystkie parametry aukcji? Czy może po prostu ja coś źle robię?

**Comment by mjag8** [comment]
Na pewno należy przesłać pełną strukturę oferty:

https://developer.allegro.pl/sale/

Uwaga! Jeżeli chcesz zaktualizować trwającą ofertę, pobierz jej dane metodą GET na zasobie /sale/offers/{offerId}. Następnie, gdy aktualizujesz ofertę, prześlij analogiczną strukturę jaką wcześniej otrzymałeś w odpowiedzi. Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty.

**Comment by Troian1337** [comment]
Idiotyczne rozwiązanie moim zdaniem, dzięki za informację.
