### ISSUE TITLE
WebApi - Zamówienia - "Oznacz jako wysłane"

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#126]
Czy istnieje funkcja która pozwoli mi zmienić status zamówienia na "Wysłane"?

**Comment by MarcinLuczak** [comment]
@SoftWareMG nie ma takiej metody w WebAPI oraz REST API. Obecnie taka możliwość jest dostępna tylko w zakładce "Moje zamówienia"

**Comment by SoftWareMG** [comment]
Czy z czasem zostanie taka funkcjonalność dodana? Wysłane ze smartfona w T-Mobile, sieci największych możliwości.-------- Wiadomość oryginalna --------Temat: Re: [allegro/allegro-api] WebApi - Zamówienia - "Oznacz jako wysłane" (#126)Od: MarcinLuczak Do: allegro/allegro-api DW: SoftWareMG ,Mention @SoftWareMG nie ma takiej metody w WebAPI oraz REST API. Obecnie taka możliwość jest dostępna tylko w zakładce "Moje zamówienia"

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/allegro/allegro-api","title":"allegro/allegro-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/allegro/allegro-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MarcinLuczak in #126: @SoftWareMG nie ma takiej metody w WebAPI oraz REST API. Obecnie taka możliwość jest dostępna tylko w zakładce \"Moje zamówienia\""}],"action":{"name":"View Issue","url":"https://github.com/allegro/allegro-api/issues/126#issuecomment-379715880"}}}

**Comment by MarcinLuczak** [comment]
@SoftWareMG W WebAPI na pewno się taka możliwość nie pojawi. Jednak na bieżąco rozwijamy REST API więc możliwe, że docelowo taka opcja się tam pojawi. Proszę [obserwować aktualności](https://developer.allegro.pl/news/) na stronie REST API.

**Comment by adamTynski** [comment]
Od dłuższego czasu nikt nie pytał... Czy coś w powyższym temacie (oznaczanie zamówień jako wysłane) się zmieniło? Brak tej możliwości wymusza na użytkowniku konieczność logowania się do Allegro wyłącznie po to, by oznaczyć zamówienie jako wysłane i jest ostatnią przeszkodą zmierzającą ku pełnej automatyzacji procesu.

**Comment by MartaNowaczyk** [comment]
@adamTynski odpowiedziałam Ci w #185. Proszę, nie pisz wszędzie gdzie jest o tym mowa, tylko w otwartym wątku lub otwórz nowy. Wystarczy raz napisać - my to widzimy.
