### ISSUE TITLE
produktyzacja

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#1260]
:bulb: **Sugestia**

Widzę, że w ramach "produktyzacji" uruchomiliście mechanizm porównujący, na podstawie jak się domyślam kodu EAN, parametry produktu podane przez sprzedającego w ofercie z parametrami "wzorca" z jakiejś Waszej wewnętrzej bazy produktów. Widoczne jest to przy ręcznej edycji oferty, kiedy mechanizm porównawczy rozpozna różnicę pomiędzy waszym "wzorcem" a parametrami podanymi przez sprzedawcę, zadawane jest przez system pytanie czy uzupełnić/zaktualizować parametry tak aby były one zgodne z waszym wzorcem. 
Z tego co dziś widziałem, usuwacie też EAN z ofert, które wg Was mają parametry niezgodne z parametrami Waszego "wzorca". Jest to tzw powiązanie oferty z "produktem". I wszystko fajnie, ta idea jest słuszna, porządkuje i standaryzuje pod kątem jakości opisu oferty, mam tylko jedno pytanie.

Czy macie w planach (a może już istnieje) mechanizm, który pozwalałby w sposób masowy "zgodzić się" na automatyczne zaktualizowanie parametrów w już istniejących ofertach tak aby były one zgodne z Waszym "wzorcem"?
Jeśli ktoś, tak jak my, ma kilkadziesiąt tysięcy ofert to było by dobre rozwiązanie, nie sposób robić tego ręcznie.
Dodatkowo, dobrze byłoby gdyby sprzedający już podczas stworzenia nowego draftu oznaczał, że z góry zgadza się na zsynchronizowanie parametrów w ofercie tak aby były one zgodne z Waszym wzorcem.

**Comment by TomekKaczmarek** [comment]
@dostawcaopon nad API, które pozwala łączyć ofertę z produktem aktualnie pracujemy.

Zdecydowaliśmy się, że przez API należy przesłać pełen zestaw danych o parametrach w ofercie, proces będzie wyglądał tak:

1. Znajdź produkt
2. Pobierz jego dane (id.produktu, kategoria, wartości parametrów)
3. Dodaj te dane to oferty 

Zdecydowaliśmy się na takie podejście z dwóch powodów:
1. Chodzi o odpowiedzialność za poprawność danych - gdybyśmy przez API automatycznie uzupełniali parametry i z jakichś powodów będą one niepoprawne (bo my mieliśmy błąd w danych albo sprzedawca coś źle wskazał), mogą pojawić się sporty transakcyjne, kupujący z jakichś powodów mogą twierdzić i oskarżać sprzedawcę, że sprzedał im produkt nie zgodny z opisem.
2. Rozwiązujemy temat - co zrobić, gdy chcesz odpiąć ofertę od produktu - skoro za każdym razem przekazujesz nam pełne dane o ofercie, usunięcie z niej id.produktu nie będzie problemem.

Więcej informacji opublikujemy już wkrótce.

**Comment by dostawcaopon** [comment]
Jeśli będzie taki zasób API za pomocą którego sprzedawca będzie mógł połączyć ofertę z "produktem" -  to załatwi sprawę ale pod warunkiem, że przypadku takiego "połączenia" automatycznie nastąpi również aktualizacja/uzupełnienie (a więc również zmiana) parametrów podanych przez sprzedawcę. 
Czy tak to będzie działało?
Ewentualnie można zrobić tak, że sprzedawca otrzymuje zwrotny komunikat o błędzie przy próbie połączenia z produktem (jeśli parametry są niezgodne z Waszym wzorcem). Wtedy sprzedawca będzie mógł chociaż łatwo wyodrębnić oferty z niepełnym lub nieprawidłowym zestawem parametrów dla produktu o określonym EAN.

**Comment by TomekKaczmarek** [comment]
W modelu oferty dojdzie nowe pole product.id, w którym możesz wskazać produkt. Produkt najpierw powinieneś wyszukać osobnym zasobem i pobrać informacje na jego temat:

- product.id
- EAN
- wartości parametrów
- kategorię

Następnie wszystkie te dane podajesz w ofercie. Sprawdzamy ich spójność, czyli nie da się przypisać do oferty product.id, jeśli wartości parametrów są różne między ofertą, a produktem - zwrócimy wtedy komunikat błędu w sekcji o walidacji.

**Comment by rtnet-pl** [comment]
@TomekKaczmarek jak Wam idzie, czy znacie jakąś datę udostępnienia tych funkcjonalności w API? Mamy bardzo dużo zapytań.

**Comment by TomekKaczmarek** [comment]
@rtnet-pl prowadzimy ostatnie testy - nowe zasoby, poradnik i product.id w modelu oferty najprawdopodobniej pojawią się jeszcze w tym albo w następnym tygodniu.
