### ISSUE TITLE
Allegro Sandbox

### ISSUE THREAD

**Issue by MBorasinski** [allegro/allegro-api#1261]
Dzień dobry,

Chciałbym użyć request do pobrania dyskusji z Allegro Sandbox.

Jako, że poradniki i wszystkie requesty są pokazane do allegro to wystarczy po https://allegro.pl dopisać allegrosandbox.pl ? 

Przykład : 

curl -X GET \
  https://api.allegro.pl/sale/disputes \ - oryginał
  https://api.allegro.pl.**allegrosandbox.pl**/sale/disputes \ - po zmianie
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: Bearer {token}'

Z góry dziękuję za odpowiedź.

Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Adresy wywołań do sandboxa znajdziesz [tutaj](https://developer.allegro.pl/about/#Sandbox).
W tym wypadku: 
https://api.allegro.pl.allegrosandbox.pl/

**Comment by MBorasinski** [comment]
@PawelTaberski dzięki za szybką reakcje.

Używam w postmanie metody - https://api.allegro.pl.allegrosandbox.pl/sale/disputes

Dodałem : 
-H 'Accept: application/vnd.allegro.public.v1+json'
oraz użyłem Basic Auth.

Po wywołaniu przycisku "SEND" otrzymuję błąd : 
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}

Proszę o pomoc.
Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
@MBorasinski Nie korzystasz czasem z flow credentials? Bo jest ono przeznaczone tylko do publicznych zasobów, bo token nie ma kontekstu usera.

**Comment by MBorasinski** [comment]
@PawelTaberski Używam Basic Auth.
[https://imgbbb.com/image/10wur](url)
Zerknij na ustawienie na screenshocie. 

Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i trace-id. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1261 na GitHub-ie

**Comment by MBorasinski** [comment]
Dzień dobry,
Zmieniłem wczoraj authorization na (TYPE - Bearer Token).

Po wciśnięciu Send zwróciło status - 200 OK ale niestety nie zwróciło żadnej dyskusji mimo, że na koncie mamy otwartą jedną dyskusje.

@PawelTaberski - jakieś pomysły co może być nie tak?

Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Jesteś pewny, że masz tokena na usera, który ma jakieś dyskusje. Rozkoduj token i upewnij się, czy masz go na właściwego usera.

**Comment by MBorasinski** [comment]
@PawelTaberski 
Na chwilę obecną miałem ustawiony token na aplikacje (clientid:clientsecret).
Teraz próbuję wygenerować token dla usera (user:haslo) ale po wciśnięciu przycisku send dostaję błąd : Bad Credentials.
Token powinienem zakodować w formie "user:hasło" ?

**Comment by PawelTaberski** [comment]
Obecnie mamy kilka flow autoryzacji, więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/), wybierz najbardziej odpowiednie do swojego systemu.

**Comment by MBorasinski** [comment]
Wspominasz o tokenie na usera to które flow powinienem użyć? 
Chcemy przez POSTMANA pobrać dyskusje z danego konta. 

Generowanie tokenu: 
POST : https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials
H - Authorization - zakodowany (user:haslo).
Po próbie uzyskania tokenu zwraca "Bad Credentials".

**Comment by PawelTaberski** [comment]
No tak, ale najpierw musisz zautoryzować danego użytkownika i do tego masz dostępne dwa rodzaje flow device i code, całość krok po kroku opisaliśmy w poradniku. User musi się zgodzić na powiązanie swojego konta z daną aplikacją i się uwierzytelnić.
