### ISSUE TITLE
Rest API - get offers/listing

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#1262]
Witam
czy dla metody get offers/listing udostępnią Państwo informacje o ilości sprzedanych sztuk? 
Jest wprawdzie "bidcount" ale zwraca "0"
W  zasobach get /sale/offers jest pole "sold" które zwraca ilość sprzedanych.
W webapi metoda doGetItemsList  pole "bidsCount" umożliwia pobranie ilości sprzedanych.
pozdrawiam

**Comment by PawelTaberski** [comment]
Zasób offers/listing ma pole:
```
                    "popularity": 0                 -- popularność oferty. W przypadku oferty
                                                    typu BUY_NOW jest to liczba zakupów od 
                                                    unikalnych użytkowników z ostatnich 
                                                    30 dni. W przypadku oferty typu AUCTION 
                                                    jest to liczba użytkowników, 
                                                    którzy biorą udział w licytacji. 
```
Więcej na temat tego zasoby znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).  Obecnie na REST API nie ma innej metody, która zwracałaby publiczne informacje o danej ofercie.
