### ISSUE TITLE
metoda PATCH do niektórych zasobów?

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#1263]
:bulb: **Sugestia**
Hej,
Czy macie w planach, lub moglibyście zasugerować odpowiednim zespołom, aby rozważyć wdrożenie metody PATCH dla niektórych zasobów? Głównie mam na myśli /sale/offers/{offerId}.

Zaoszczędziłoby to ilość przesyłanych danych oraz w ogóle ilość requestów, bo na tą chwilę aby zaktualizować cokolwiek na trwającej aukcji to muszę pobierać jej pełną strukturę GETem, a potem PUT po naniesieniu zmian.

**Comment by PawelTaberski** [comment]
Rozumiem, z tego co wiem w najbliższym czasie nie jest planowana taka zmiana, ale jak najbardziej sugestię przekażę. Jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym w dedykowanym komunikacie.
