### ISSUE TITLE
Problem z wykorzystaniem zdjęć w opisie.

### ISSUE THREAD

**Issue by qls-api** [allegro/allegro-api#1264]
Dodaję kompletną ofertę przez zasób sale/offers -POST walidacja poprawna. Mamy draft. Wchodzimy przez www i mamy brak zdjęć w opisie oferty. Zdjęcia są dostępne w galerii, a w opisie mamy na czerwono „wybierz zdjęcie”. W czym jest problem ?

Czy draft można usunąć przez API ?

**Comment by PawelTaberski** [comment]
Na pewno podajesz takie same zdjęcia w opisie jak w tabeli "images"? Draft jak najbardziej możesz usunąć przy pomocy [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE)

**Comment by qls-api** [comment]
Problem chyba się rozwiązał. Zauważyłem ze zdjęcia pojawiają z pewnym opóźnieniem.
