### ISSUE TITLE
Problem z doGetSellFormFieldsForCategory

### ISSUE THREAD

**Issue by PawelSzGit** [allegro/allegro-api#1265]
Witam pobierając pola dla kategorii w odpowiedzi otrzymuje wartości wszystkich pól do oferty allegro.
Kod w załączniku.
[allegro_parameters.txt](https://github.com/allegro/allegro-api/files/2918910/allegro_parameters.txt)

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta i responsa w formacie XML przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1265 na GitHub-ie. Sprawdzimy w czym jest problem.

**Comment by FromAnyHole** [comment]
Przecież tak ta metoda działa, zwraca wszystko w kontekście danej kategorii...
Problemem jest to, że metodę tą zamierzają za chwilę całkowicie wyłączyć !!

**Comment by PawelTaberski** [comment]
@FromAnyHole Rozumiem, że chodzi Tobie o wątek #1191 wiem że trwają rozmowy co i kiedy jesteśmy w stanie wdrożyć i najdalej w przyszłym tygodniu pojawią się konkretne informacje z przewidywanymi terminami.
