### ISSUE TITLE
Sandbox - problem z płatnościami

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#1266]
Czy tylko ja mam problem z płatnościami w Sandboxie? Zakup jako gość, po kliknięciu "Płacę" (ostatni etap, po wybraniu metody płatności) - nic się nie dzieje.
Screen z konsoli: https://scr.hu/92hi/tg0hc

#edit: poprawiłem link do screena.

**Comment by PawelTaberski** [comment]
Przetestowałem i płatność na sandboxie działa prawidłowo a próbowałeś w inne przeglądarce, bądź w trybie incognito, możliwe że jest problem z jakimiś ciasteczkami.

**Comment by xemix** [comment]
Jest OK, faktycznie jakiś problem miałem z przeglądarką.
