### ISSUE TITLE
Problem z ładowaniem parametrów do ktegorii

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#1267]
Jest problem z podczas walidacji oferty przed jej wystawieniem. 

Problem dotyczy kategorii odzieżowych, jeden przykład poniżej:
Odzież, Obuwie, Dodatki > Odzież damska > Spodnie > Casual (na co dzień)

Parametr: Stan (obowiązkowy)
Wartości parametru: 
- Nowy
- Używany
- Nowy bez metki
- Nowy z defektem

Po wybraniu parametru:
- Nowy bez metki
lub
- Nowy z defektem

Zwraca komunikat: 
"Niepoprawna wartość w polu formularza sprzedaży (np. zbyt duża ilość znaków w tytule oferty). Stan - fid: 19971 "

Na parametrze:
- Nowy
- Używany
Jest OK. 
Problem pojawił się wczoraj około 15:00. Wcześniej było OK.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 1267 na GitHub-ie. Pamiętaj, że 3 czerwca wygaszamy metody do zarządzania ofertami W WebAPI, więcej na ten temat #1043

**Comment by mkaluszka** [comment]
Podbijam - coś jest nie tak z nowymi Fidami (dodanymi ostatnio, mającymi wysokie numery) - część aukcji nie wystawia się i zgłasza poprawne fidy jako nie istniejące, część wystawia sie jako inne. Wystawiając ofertę w kategorii 259397 ustawiłem FID 41665 na wartość 255202 a ustawił się ten parametr na aukcji 7877983557 na 307577

**Comment by PawelTaberski** [comment]
@mkaluszka Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML, pozwoli nam to szybciej namierzyć problem. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 1267 na GitHub-ie.

**Comment by PawelTaberski** [comment]
@mirkosmuz Przetestowałem Twoje requesty i wszystko wygląda poprawnie, czy problem u Ciebie dalej występuje?

**Comment by mirkosmuz** [comment]
rozumiem że coś poprawiliście :) bo teraz zaczęło działać.
