### ISSUE TITLE
Sandbox - stabilność/błędy

### ISSUE THREAD

**Issue by MasterSlynx** [allegro/allegro-api#1268]
Mam pytanie, bo zaczyna to być uciążliwe przy testowaniu. Regularnie dostaje błędne odpowiedzi od serwera, gdzie ten sam (chyba) prawidłowy request raz działa, a następnym razem już zwraca błąd. Dla przykładu podaje przed chwilą złapany request/response.
```
GET https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?limit=1&offset=0 HTTP/1.1
Accept-Language: pl-PL
Accept: application/vnd.allegro.public.v1+json, application/vnd.allegro.beta.v1+json, application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTE1MDg3NDYsInVzZXJfbmFtZSI6IjQzOTk5Mzg0IiwianRpIjoiMGViZDY0N2MtOTU3Yi00OTI5LWJiMWMtOTZiNzZhMjBmYzY4IiwiY2xpZW50X2lkIjoiNjU0NzlmMmMwMmI1NGFkOGIzNWY1ZTZkOWE1NjhiN2MiLCJzY29wZSI6W119.rv05DP0uUdWrXMfKQu9rSgZCXrWxZ5grO9dirnMbIovC9c6Ni6HeoNkGSVixIaXHEwWRko1BEiiWaSVAppqtHDw2X2tO398swXL2HEyiqQWV1SLtJ6I3_2sRdtaDtQT3xyPMPOKfsYfduc_K-jGLzi3L88E-8OUTwS-z12QuHfiJFUOp0VNtb978SInpKenHJWr3gcOaZN-oWA65-C9CzOROIe11vT1tFikcYgu-GN_zmPTJTUB2NjT3zr9oVr2trlvrlfosfR76fsLvQjTIHnCkwdpk0WPjSEkCtRLs6a6U6ckZobSF3uQNoSgagq0L0EPzOMOQuCio0tPAaCBVMQ
Host: api.allegro.pl.allegrosandbox.pl
Connection: Keep-Alive
```

```
HTTP/1.1 500 Internal Server Error
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 463e9d1e21332ed9
Date: Fri, 01 Mar 2019 18:42:21 GMT
X-RateLimit-Remaining: 9000
X-Content-Type-Options: nosniff
Content-Type: application/json
Content-Length: 94
X-RateLimit-Limit: 9000

{"errors":[{"code":"ERROR","message":"An error has occurred","path":"/order/checkout-forms"}]}
```

Ja rozumiem, że to środowisko testowe, ale mam wątpliwości czy to czasem nie będzie działało tak samo na serwerze produkcyjnym. Czy to jakiś błąd po mojej stronie czy takie regularnie błędne odpowiedzi od serwera powinienem uwzględnić w logice programu. Nie ma żadnego info nigdzie (a przynajmniej je nie znalazłem) że "wprowadzamy zmiany - mogą wystąpić problemy z serwerem", więc zakładam, że to po prostu tak działa.
Nawet jeśli to błąd z mojej strony to odpowiedź od serwera nie pozwala ustalić w czym mógłby być problem. Proszę o jakieś słowo komentarza, bo nie wiem jak do tego podchodzić.

W momencie jak skończyłem pisać to znowu zaczęło działać, więc zakładam, że to nie błąd po mojej stronie tylko ogólna stabilność serwera testowego.
Jeśli jest to efekt wprowadzanych przez was zmian to dobrze by było gdyby w takim momencie po wejściu na stronę https://allegro.pl.allegrosandbox.pl/ pojawiała się prosta notka, że "Wprowadzamy zmiany - mogą wystąpić błędy ze stabilnością serwera". 15 minut roboty, a oszczędza odpowiedzi na pytania "co zrobiłem nie tak".

**Comment by arcziii** [comment]
Problem jest raczej po stronie serwera, u mnie jest identycznie, program raz działa, za chwilę przestaje i zwraca błędy gdzie na produkcji taka sytuacja nie ma miejsca. W sandboksie mam także problem z otrzymywaniem e-maili na konta testowe, przy składaniu zamówienia niby jest ono sfinalizowane lecz na koncie sprzedającego nie ma śladu po zakupie.

**Comment by MasterSlynx** [comment]
Tak, zauważyłem, chwilę potem znowu przestało działać. To trochę przegięcie. W końcu to ma być sandbox, a nie serwer testowy, więc powinien zapewniać podobną stabilność. 
Denerwujące, gdy jest się "na flow", starasz się coś przetestować i... błąd, błąd... i trzeba czekać 5 minut aż znowu zacznie działać...
No nic, chciałem tylko zwrócić uwagę, że taki problem występuje i jest on bardzo zauważalny.

**Comment by PawelTaberski** [comment]
Starałem się powtórzyć błąd jednakże wydaje się, że wszystko działa prawidłowo. Czy problem u Ciebie dalej występuje? Na środowisku testowym zmiany wdrażamy praktycznie kilka razy dziennie, także mogą zdarzać się przerwy w działaniu niektórych metod.

**Comment by arcziii** [comment]
U mnie problem występował kilka dni, aktualnie wszystko działa prawidłowo.
