### ISSUE TITLE
description.sections[0].items[1].content: Invalid HTML subset

### ISSUE THREAD

**Issue by Sojtin** [allegro/allegro-api#1269]
Występuje problem: 
 - [x ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym

:beetle: **Opis**

Dlaczego dostaje:
`        (int) 0 => array(
                'code' => 'VALIDATION_ERROR',
                'message' => '',
                'details' => '',
                'path' => '',
                'userMessage' => 'description.sections[0].items[1].content: Invalid HTML subset'
        )`

Na takim opisie:

```
        'sections' => array(
                (int) 0 => array(
                        'items' => array(
                                (int) 0 => array(
                                        'type' => 'IMAGE',
                                        'url' => 'https://a.allegroimg.allegrosandbox.pl/original/1127d5/576f078a4f73a69c4cb151f0f9f7'
                                ),
                                (int) 1 => array(
                                        'type' => 'TEXT',
                                        'content' => '<h1>Canpol Babies Szczotka i grzebyk ZIELONY KONIK</h1><p><strong>HOLOGRAPHIC HALO CREAM EYELINER marki NYX Professional Makeup.</strong> Eyeliner. Zawiera formułę mocno napigmentowaną perłami, wypełnionymi po brzegi kolorem. Pozwala na tworzenie gładkich kresek z lśniącym finiszem, które idealnie podkreślą każde spojrzenie. Ponadto produkt może być używany jako cień do powiek z holograficznym wykończeniem. Dostępny w 5 zjawiskowych, perłowo-pastelowych, dobrze blendujących się odcieniach. Nie zaleca się używania na linii wodnej.</p>'
                                )
                        )
                )
        )
```

...

`<h1>Canpol Babies Szczotka i grzebyk ZIELONY KONIK</h1><p><strong>HOLOGRAPHIC HALO CREAM EYELINER marki NYX Professional Makeup.</strong> Eyeliner. Zawiera formułę mocno napigmentowaną perłami, wypełnionymi po brzegi kolorem. Pozwala na tworzenie gładkich kresek z lśniącym finiszem, które idealnie podkreślą każde spojrzenie. Ponadto produkt może być używany jako cień do powiek z holograficznym wykończeniem. Dostępny w 5 zjawiskowych, perłowo-pastelowych, dobrze blendujących się odcieniach. Nie zaleca się używania na linii wodnej.</p>`

**Comment by 07adityasingh** [comment]
Hey @Sojtin 
How did you solve this?

**Comment by PrzemyslawLukanowski** [comment]
@07adityasingh We don’t support < strong > tag in description, You should use < b > instead. You can find more information in [our guide.](https://developer.allegro.pl/sale/#step-5-description)
