### ISSUE TITLE
Nowe formy dostawy

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#127]
Czy przypadkiem nie wkradla sie literowka do dokumentacji ? 
Zawsze stosowaliscie roznice + 100 miedzy pierwsza sztuka a nastepnymi, a tutaj prawie wszedzie sie zgadza , poza 

Kurier Raben pobraniowy | 110 | 201 | 310
-- | -- | -- | --

<img width="664" alt="zrzut ekranu 2018-04-09 o 08 48 55" src="https://user-images.githubusercontent.com/1530496/38483390-07edc79a-3bd3-11e8-8b87-11dcf63b4cc4.png">

Jest rzeczywiscie 201 czy powinno byc 210 ? 
via https://allegro.pl/webapi/news.php#news_100600

**Comment by MarcinLuczak** [comment]
@yncki Tak, dokładnie, masz rację. To literówka. Zaraz poprawimy to w komunikacie. Dzięki!
