### ISSUE TITLE
Refresh token - autoryzacja tylko raz?

### ISSUE THREAD

**Issue by janzdanowski** [allegro/allegro-api#1270]
Rozumiem, że dzięki refresh tokenowi, przy korzystaniu z Authorization Code flow, mogę tylko raz zalogować się przez przeglądarkę, żeby otrzymać kod autoryzacyjny w celu pozyskania po raz pierwszy access tokena z refresh tokenem, i co 12h korzystać z refresh tokena, żeby pozyskać nową parę access/refresh token.
I tak w kółko mogę odświeżać access token czy jednak po jakimś czasie będę musiał ponownie zgłosić się po kod autoryzacyjny (np. gdy przez 3 miesiące nie użyję refresh tokena), angażując przeglądarkę?

**Comment by PawelTaberski** [comment]
Refresh przy każdej nowej parze jest ważny 3 miesiące, także jeśli 3 miesiące byś nie odświeżał tokena dostępowego, to musiałbyś na nowo angażować usera aby się uwierzytelnił. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/auth/#refresh-token).
