### ISSUE TITLE
Warunki gwarancji

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1271]
Kiedy chcę pobrać warunki gwarancji i wywołuję poniższy url

/after-sales-service-conditions/implied-warranties?seller.id={seller ID}

to podając seller ID konta sandbox otrzymuję "You do not have permission to request this resource". Kiedy podam seller ID prawdziwego konta wówczas zwraca dane poprawnie. Analogiczna sytuacja dla metody

 /sale/shipping-rates?seller.id=

**Comment by PawelTaberski** [comment]
Sprawdziłem i zasób działa poprawnie. Powodów błędu może być co najmniej kilka, czy:

- podajesz właściwy adres przy wywołaniu - [sandbox](https://developer.allegro.pl/about/#Sandbox)
- masz token na właśnie tego usera, od którego chcesz pozyskać warunki, tokeny są w technologii JWT, także możesz je rozkodować
