### ISSUE TITLE
Błąd w czasie kończenia oferty zaplanowanej do wystawienia w przyszłości

### ISSUE THREAD

**Issue by squasher83** [allegro/allegro-api#1272]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,
Problem występuje zarówno w rest API jak i środowisku produkcyjnym i sandboxie oraz w czasie używania ALLEGRO GUI. W momencie zaplanowania oferty do wystawienia z zaplanowanym czasem do wystawienia scheduledFor zasobu offer/publication, bądź też poprzzez GUI Allegro zaplanowanie aukcji do wystawienia, a następnie (kiedy jeszcze aukcja się nie wystawiła status ACTIVATING) zakończenie oferty, nie jest już możliwe ponowne jej wznowienie. Komunikat z GUI (oferta w trakcie kończenia....) i tak non-stop.

**Comment by PawelTaberski** [comment]
Tak, jeśli zakończysz ofertę przed jej opublikowaniem i będziesz próbował ją wznowić dostaniesz błąd. W takim wypadku aktywacja takiej oferty powinna być możliwa przez front.

**Comment by squasher83** [comment]
Próba wznowienia tej oferty przez front, dostaję taki komunikat: 
"Podczas wznowienia oferty wystąpiły błędy
Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie."
To już jest około doba od zakończenia

**Comment by PawelTaberski** [comment]
Rozumiem, czy problem masz z jedną czy większą ilością ofert? Podeślij proszę numer tel oferty, bądź ofert.

**Comment by squasher83** [comment]
Witam,
Problem występuje z każdą ofertą zarówno na sandboxie jak i na produkcyjnym, testuję teraz tylko jedną ofertę, jej numer w linku poniżej. Link z ofertą podczas próby wznowienia: 
https://allegro.pl.allegrosandbox.pl/offer/6206180772/start

**Comment by PawelTaberski** [comment]
Rozumiem rozmawiałem z zespołem odpowiedzialnym za tą usługę, pracujemy nad tym problemem. Obecnie jedyne co mogę zalecić to wystawienie podobnej oferty, bo tej na chwilę obecną nie można wystawić tamtej ponownie. Problem pojawia się własnie przy zakończeniu nieaktywowanej jeszcze oferty.

**Comment by squasher83** [comment]
OK, nie ma problemu, poradzę sobie w inny sposób, natomiast proszę o informację, jak problem zostanie już rozwiązany.
Pozdrawiam

**Comment by PawelTaberski** [comment]
Ok, postaram się pamiętać, ale jakbym nie dawał znaka przez dłuższy czas jak najbardziej przypomnij się z tematem :-)

**Comment by squasher83** [comment]
Problem został częściowo rozwiązany, teraz dostaję taki błąd na frontendzie (ta sama oferta co ostatnio 4 posty wyżej) "Podczas wznowienia oferty wystąpiły błędy Data wystawienia oferty nie może być z przeszłości.", co jest w 100% prawdą, gdyż z tego co pamiętam oferta ta była zaplanowana do wystawienia na 10 marca. Nie ma jednak możliwości zmiany tej wartości, gdyż podczas wznawiania oferty brakuje bloku "Opcje wystawienia ->  Oferta pojawi się na Allegro -> od razu".

**Comment by PawelTaberski** [comment]
Problem występuje wtedy, gdy zakończysz jeszcze nie opublikowaną ofertę i potem chcesz ją wznowić, i wiemy o tym i pracujemy nad poprawą tego mechanizmu. W takiej sytuacji na chwilę obecną nie da się ożywić takiej oferty trzeba wystawić podobną.

**Comment by Arturxyz** [comment]
Ten sam problem wystąpił u mnie na ofercie, która była już opublikowana od 2 tygodni, ale ją na pewien czas zakończyłem, potem wznowiłem ale się nie chciała wznowić, przy kolejnych próbach wznowienia wyskakuje właśnie komunikat "Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie"

**Comment by PawelTaberski** [comment]
Jeśli próbowałeś wznowić ofertą, gdy ta jeszcze się nie skończyła zakańczać to niestety obecnie nie można wznowić taką ofertę przez API, możesz jedynie wystawić podobną, tak jak pisałem wiemy o tym problemie, niestety nie wiem ile zajmie jeszcze jego poprawa.

**Comment by Arturxyz** [comment]
Właściwie ja nie korzystam z API, wystawiam przez formularz. Chronologia była taka, że w piątek o godzinie 00:29 przyszedł mail potwierdzający zakończenie oferty. Natomiast o godzinie 1:41 "wznowiłem" ofertę. Od tego momentu oferta jest dostępna w wynikach wyszukiwania, wyświetla się jako pierwsza według trafności wśród promowanych w kategorii startery. Natomiast oczywiście nikt nie może nic kupić przez tą ofertę, bo widnieje jako zakończona, klienci się mnie pytają czemu jest zakończona, śmieszna sytuacja.  

Wystawiłem już w sobotę podobną ofertę, tym bardziej, że podobny problem pojawił się już na tym forum w październiku i jak widać nie został rozwiązany do dzisiaj.

**Comment by PawelTaberski** [comment]
@Arturxyz Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) numer tej oferty. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1272 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Zbadałem i rzeczywiście dziwnie to wygląda, sprawę przekazałem do rozwiązania do zespołu, który odpowiada za te funkcje. Proszę o cierpliwość.

**Comment by Arturxyz** [comment]
Oferta została prawidłowo zakończona i mogłem ją wreszcie wznowić :)

**Comment by PawelTaberski** [comment]
Dzięki za informacje w takim razie zamykam wątek.

**Comment by laleczkajoleczka** [comment]
Proszę o pomoc , dokładnie mam ten sam problem od dwóch dni :
"Od momentu wystawienia oferta jest dostępna w wynikach wyszukiwania, wyświetla się jako pierwsza według trafności wśród promowanych w kategorii startery. Natomiast oczywiście nikt nie może nic kupić przez tę ofertę, bo widnieje jako zakończona, klienci się mnie pytają czemu jest zakończona, śmieszna sytuacja."
Podczas wznowienia oferty wystąpiły błędy
Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.

**Comment by laleczkajoleczka** [comment]
I tak juz dwa od dwóch dni tkwi w zawieszeniu i nie mozna nic zrobić :(

**Comment by laleczkajoleczka** [comment]
Nikt a Allegro do tej pory nie pomógł ....

**Comment by laleczkajoleczka** [comment]
bardzo proszę o ewentualna pomoc w temacie i pozdrawiam

**Comment by PawelTaberski** [comment]
@laleczkajoleczka Podaj proszę numer oferty sprawdzimy w czym jest problem.

**Comment by laleczkajoleczka** [comment]
Jasne juz podaje : oferta  7287562895, ta jest dla nas najwazniejsza

ale jeszcze i oferta 7628907449 tez ma podobnie .

Było by fajnie jakbyście mogli pomóc zwłaszcza jesli chodzi o ofertę
7287562895.
Pozdrawiam i wielkie dzięki Jolina🤗

czw., 23 maj 2019 o 12:17 PawelTaberski <notifications@github.com>
napisał(a):

**Comment by PawelTaberski** [comment]
@laleczkajoleczka Dzięki za numery ofert, sprawdziłem i rzeczywiście jest problem. Przekazałem numery do odpowiedniego zespołu. Prośba o cierpliwość.

**Comment by laleczkajoleczka** [comment]
oczywiście, wielkie dzięki piekne

czw., 23 maj 2019 o 13:10 PawelTaberski <notifications@github.com>
napisał(a):

**Comment by laleczkajoleczka** [comment]
Witam,aukcje nadal w zawieszeniu niestety , pozdrawiam serdecznie .

**Comment by PawelTaberski** [comment]
@laleczkajoleczka Otrzymałem informacje, że problem powinien być rozwiązany, czy u Ciebie teraz jest ok?

**Comment by laleczkajoleczka** [comment]
niestety nie, jest to samo , nie da się wznowić oferty i wyskakuje ten sam
błąd

pon., 27 maj 2019 o 10:00 PawelTaberski <notifications@github.com>
napisał(a):

**Comment by laleczkajoleczka** [comment]
7287562895   Oferta nie może zostać wznowiona, ponieważ jest w trakcie
kończenia. Poczekaj chwilę i spróbuj ponownie,

Wystawienie przedmiotu przy wystawieniu oferty 0,00 zł / 10 dni
Pakiet Wyróżnienie + Pogrubienie + Podświetlenie przy wystawieniu oferty
2,90 zł / 1 dzień

pon., 27 maj 2019 o 10:04 CENTER_WHITE24 <centerwhite24@gmail.com>
napisał(a):

**Comment by laleczkajoleczka** [comment]
myslałam ze jak się zakończy wystawienie przedmiotu do 0 dni to moze bedzie mozliwosc wznowienia oferty, a tu się zakonczyło , jest 0 dni i niestety , pewno dltego ze sie odliczaja jakies dni przy ofercie 
, takze problem nadal istnieje cały czas :(

**Comment by PawelTaberski** [comment]
@laleczkajoleczka Rozumiem, zgłosiłem to do zespołu, który pracuje nad tym problemem. Proszę o cierpliwość.

**Comment by laleczkajoleczka** [comment]
Oferta została prawidłowo zakończona i mogliśmy  ją wreszcie wznowić :)7287562895, za co bardzo dziękujemy ,  jedynie nadal nie da się wznowić oferty tej drugiej nadal jest bład 7628907449, jesli nie uda się jej wznowić to nie tragedia , a jak się uda to mega , bardzo dziękuję pięknie raz jeszcze za wszystko  :)

**Comment by laleczkajoleczka** [comment]
oferta juz zakonczyła się w dniu wczorajszym wiec mogliśmy ja wznowić ,za wszystko bardzo dziękuje serdecznie i pozdrawiam:)
