### ISSUE TITLE
LOGOWANIE REST Device flow

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#1273]
po zarejestrowaniu nowej aplikacj typu device flow i wysłaniu requesta z przykładu na stronie https://developer.allegro.pl/auth/#DeviceFlow tj. curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(client_id:client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}' otrzymuję następujący błąd
 {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}] raczkuje w temacie REST proszę o pooc. Jesli bedzie potrzebny pełny request to jak mogę go uzyskać? (piszę w PHP)
 oczywiście pamiętałem o dwukropku i zmianie {client_id} na faktyczny id i o zakodowaniu base64

**Comment by marcinja2** [comment]
po zarejestrowaniu nowej aplikacj typu dewice flow i wysłaniu requesta z przykładu na stronie https://developer.allegro.pl/auth/#DeviceFlow otrzymuję następujący błąd {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}] raczkuje w temacie REST proszę o pooc. Jesli bedzie potrzebny pełny request to jak mogę go uzyskać? (piszę w PHP)

**Comment by PawelTaberski** [comment]
Jaki status ma odpowiedź jaki otrzymujesz 415?

**Comment by marcinja2** [comment]
Tak treść : HTTP/1.1 415 Unsupported Media Type Cache-Control: no-cache, no-store, max-age=0, must-revalidate Pragma: no-cache Date: Mon, 04 Mar 2019 09:07:23 GMT Content-Type: application/json X-Backend: auth_1193245_dc5_19_83_31201 Vary: Accept-Encoding Age: 0 X-Req-Counter: 1 Content-Security-Policy: block-all-mixed-content; report-uri https://allegroapi.io/seclog/csp; X-Hit: HIT 0 X-Origin: s50797 X-Content-Type-Options: nosniff grace: none X-XSS-Protection: 1; report=https://allegro.pl/seclog/xss Transfer-Encoding: chunked X-Frame-Options: SAMEORIGIN Strict-Transport-Security: max-age=15552000 Set-Cookie: _cmuid=cstgesr3-n7t5-5s3c-yxuk-7fdzdwkj1mbz; Expires=Wed, 03 Mar 2021 09:07:23 GMT

**Comment by PawelTaberski** [comment]
W takim wypadku problem musi być w body, które przesyłasz jest ono w nieodpowiednim formacie. Powinieneś przesyłać je w formacie x-www-form-urlencoded

**Comment by marcinja2** [comment]
rzeczywiście była literówka przy Content-Type:
