### ISSUE TITLE
Wygaszenie doGetItemsList  - brak 'userLogin'  w GET/offers/listing

### ISSUE THREAD

**Issue by mtumtu** [allegro/allegro-api#1274]
W danych zwracanych przez doGetItemsList  jest pole 'sellerInfo.userLogin' zawierające login sprzedawcy.
Niestety w REST-owym 'GET/offers/listing' jest tylko ID sprzedawcy.
Czy przed wygaszeniem WebAPI odpowiednik 'sellerInfo.userLogin' pojawi się w 'GET/offers/listing' ?
Jeśli nie, to w jaki sposób za pomocą REST API pobrać 'userLogin' na podstawie ID sprzedawcy ?

**Comment by MartaNowaczyk** [comment]
@mtumtu na ten moment nie ma takiej możliwości przez REST API, ale będziemy pracować nad tym. Jeśli udostępnimy taki zasób damy znać w oddzielnym komunikacie.

**Comment by 19bartek92** [comment]
@MartaNowaczyk a czy jest szansa na odwrócenie tej kolejności? Tj najpierw zbudowanie zasobów a później wygaszanie "starego" rozwiązania? Wchodzi w grę przesunięcie wygaszenia tej metody?

**Comment by MartaNowaczyk** [comment]
@19bartek92 nie chcemy przesuwać wygaszenia tej metody. userLogin na REST chcemy udostępnić w najbliższych dwóch kwartałach #1191
