### ISSUE TITLE
Zapytanie o device code

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1275]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy poniższym zapytaniu POST dla aplikacji utworzonej na sandboxie

/auth/oauth/device 
Content-Type: application/x-www-form-urlencoded
Host: allegro.pl.allegrosandbox.pl
Authorization: Basic ...

otrzymuję komunikat "Client does not have the device_code grant"

**Comment by MartaNowaczyk** [comment]
@michcio19923 nie wiem czy to przypadkowe dane, czy pełne dane które do nas wysyłasz, w każdym razie nie wygląda to poprawnie. Polecam nasz [poradnik](
https://developer.allegro.pl/auth/#DeviceFlow). Poza tym upewnij się, że zakodowałeś całość danych client_id:client_secret wraz ze znakiem “:”
Poza tym najlepiej podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1275. Sprawdzę w czym jest problem.

**Comment by michcio19923** [comment]
Przesłałem, wstawiłem tylko fragment żądania, jest poprawne, bo dla adresu produkcyjnego zwraca deviceCode

**Comment by MartaNowaczyk** [comment]
@michcio19923 sprawdź proszę czy czasem nie masz zarejestrowanej aplikacji jako typ WEB na sandboxie. Powinna mieć typ DEVICE.
