### ISSUE TITLE
Wartości parametrów ofert zwracane w offers/listing

### ISSUE THREAD

**Issue by CraneSenior** [allegro/allegro-api#1276]
Cześć!
Mam małe pytanie, czy w tej chwili jest jakaś możliwość uzyskania wartości parametrów ofert zwracanych z offers/listing ?
Żeby nakreślić dokładniej posłużę się przykładem :)
Mamy na przykład zapytanie _/offers/listing?category.id=4029_ (kategoria z ogłoszeniami sprzedaży samochodów osobowych), którego wynikiem jest przykładowe ogłoszenie zawierające takie właściwości jak: _id, name, seller, promotion, delivery_ .... 
Czy można zapytanie skonstruować w taki sposób aby dostać właściwości parametrów specyficznych dla danej kategorii(wartości po których można filtrować)? W tym wypadku _przebieg, pojemność silnika, rok produkcji_ .... dla każdej zwróconej oferty.
W dokumentacji nic się nie doszukałem na ten temat.

Pozdrawiam!

**Comment by MartaNowaczyk** [comment]
Cześć, takim zapytaniem 
/offers/listing?category.id=4029&include=-all&include=filters
dostaniesz wszystkie filtry z których możesz skorzystać dla podanej kategorii.

Następnie filtrowanie po parametrach można wywołać w ten sposób:
/offers/listing?category.id=4029&parameter.11323=1 (stan nowy)

**Comment by CraneSenior** [comment]
Myślę, że trochę źle mnie zrozumiano.
Chodziło mi o to aby zwracane oferty miały te własności. Dla przykładu aby odpowiedź z tej ścieżki wyglądała mniej więcej tak:
```
.
.
.
"items": {
  "promoted": [
    {
      ...
    }
  ],
  "regular": [
    {                    // obiekt jednej ze zwroconych ofert
      "id": "string",
      "name": "string",
      "seller": {
      },
      "promotion": {
      },
      "delivery": {
      },
      "images": [
      ],
      "sellingMode": {
      },
      "stock": {
      },
      "vendor": {
      },
      "category": {
      },
      "publication": {
      }
      "properties":[ //takiego pola nie zauwazylem w zwrotkach ze sciezki offers/listing
       {
        "name":"parameter.1234," // nazwa parametru uzywanego w filtrach oznaczająca rok produkcji, nie znam na pamiec wiec wymyslilem :)
        "value":"2010"   // faktyczny rok produkcji podany w ofercie
        },
        .
        .// inne parametry specyficzne dla kategorii motoryzacja
        .
      ]
    }
  ]
.
.
.
```

**Comment by MartaNowaczyk** [comment]
zasób o którym piszemy odzwierciedla listę ofert na froncie, nie widok oferty, dlatego możesz zawęzić wyświetlaną listę według dostępnych filtrów. Dla tego zasobu nie planujemy zmian w tej kwesti. Prawdopodobnie pojawią się takie możliwości dla zasobu, który będzie odzwierciedlał publiczne dane oferty. Jeśli taki zasób się pojawi damy o tym znać w oddzielnym komunikacie.

**Comment by CraneSenior** [comment]
Dzięki za wyjaśnienia!
