### ISSUE TITLE
Wielowariantowość - Własny identyfikator  grupy

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1277]
:bulb: **Sugestia**

Czy jest możliwość dodania własnego identyfikatora grupy wielowariantowej?
Przykład posiadam produkty:
ABC-1
ABC-2
ABC-3
wszystkie spełniają wymagania grupy, jednak brakuje mi pola w którym mógłbym nadać grupie identyfikator "ABC", docelowo chciałbym po tym polu móc sprawdzać zawartość grupy (po externalID i auctionID produktu, dodawac/usuwać)

**Comment by MartaNowaczyk** [comment]
@pfunkowski nie wiem czy dobrze rozumiem, ale podczas tworzenia oferty wielowariantowej ustawiasz dla niego identyfikator {setId}, dzięki któremu możesz potem pobrać listę wszystkich ofert wchodzących w skład oferty wielowariantowej.

> docelowo chciałbym po tym polu móc sprawdzać zawartość grupy (po externalID i auctionID produktu, dodawac/usuwać)

Opisz proszę potrzebę takiego rozwiązania.

**Comment by pfunkowski** [comment]
w swojej bazie produktowej posiadam już określone identyfikatory alfanumeryczne na potrzeby grupowania ofert. Chciałbym uniknąć przechowywania dodatkowych UUID wyłącznie na potrzeby Waszego API co byłoby dla mnie dużym ułatwieniem.

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak nie planujemy takiego rozwiązania. W tym momencie mogę przekazać taką sugestię do odpowiedniego zespołu.
