### ISSUE TITLE
Checkout Form ID w panelu sprzedawcy

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1278]
:bulb: **Sugestia**

Przydatnym byłoby wyświetlanie CheckoutFormId na liście zamówień od strony panelu sprzedawcy - wyszukiwarka sprawdza się świetnie, niestety pole nie jest widoczne, podobnie productExternalId nie jest widoczny od strony ofert, ani zamówień

**Comment by MartaNowaczyk** [comment]
@pfunkowski nie mamy w tym momencie tego w planach. Napisz proszę do czego ci to potrzebne, żebyśmy mieli szerszy obraz. Poza tym externalId to zewnętrzny identyfikator, który z założenia nie miał być widoczny.

**Comment by neldh** [comment]
Jeśli chodzi o checkout form id, to przydalby się, żeby odnaleźć się dzięki niemu w panelu (znaleźć transakcje ktorych dotyczy). Całe restowe api (jeśli mówimy o zamowieniach) dziala w oparciu o to id, więc dobrze by bylo je uwidocznić.

**Comment by MartaNowaczyk** [comment]
@neldh dzięki za szerszy kontekst - przekazałam sugestię.
