### ISSUE TITLE
data i godzina zamówienia w RestApi

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1279]
:bulb: **Sugestia**

korzystając z metody order/checkout-forms/{id} przydatnym byłoby pobieranie daty i godziny zamówienia

**Comment by MartaNowaczyk** [comment]
@pfunkowski dla danego lineItems.id dostajesz "boughtAt" - to nie wystarczy? O jaką datę zamówienia chodzi? Ostatnia data zakupu, czy może pierwsza? Czasami ktoś kupuje kilka przedmiotów oddzielnie, a później wspólnie za nie płaci, wtedy jedyną datą wspólną jest data płatności. Dlatego warto opierać logikę na lineItems.id.

**Comment by neldh** [comment]
zapewne chodzi wlasnie o date platnosci.

Co do opierania logiki o lineItems.id - REST api ma doslownie 1 końcowkę która po tym gada, więc to dość dziwna sugestia

**Comment by MartaNowaczyk** [comment]
@neldh chodziło mi o logikę obsługi zamówień, patrząc na wszystkie przypadki jakie mogą tam występować, bo np. jest możliwa zmiana id chckoutForma, gdy ktoś połączy dwa oddzielne zakupy, także zależy od której strony na to patrzysz...

**Comment by neldh** [comment]
aha, ok

**Comment by neldh** [comment]
Jeszcze tak w nawiązaniu i celem upewnienia się: zmiana tego id checkout forma jest możliwa tylko zanim wejdzie on w stan READY_FOR_PROCESSING? Czy może są mozliwe jakieś sytuacje zmiany tego id już po tym jak wejdzie on w ten status?

**Comment by MartaNowaczyk** [comment]
@neldh zmiana chckoutForm.id jest możliwa przed statusem READY_FOR_PROCESSING

**Comment by vendoremo** [comment]
Proszę o informację czy od chwili zmiany statusu zamówienia na READY_FOR_PROCESSING coś poza działem surcharges może ulec zmianie? Jeżeli tak to które pola i w jakiej sytuacji?

**Comment by vendoremo** [comment]
I jeszcze drugie pytanie - czy bezpośrednio po wykonaniu dopłaty do zamówienia złożonego załóżmy 2 miesiące wcześniej, zamówienie to będzie wyświetlane jako pierwszy wynik w zasobie /order/checkout-forms? Jeżeli nie, to w jaki sposób znaleźć najnowsze dopłaty bez przekopywania się przez wszystkie istniejące zamówienia?

**Comment by AssAssIn1909** [comment]
W zasadzie filtr daty powinien brać pod uwagę również daty płatności, ewentualnie filtr powinien brać ostatnią datę, 
Daty na liniach są spoko, ale według mnie powinno pojawić się pole updatedAt na zamówieniu i to po nim filtrować. A pole by się aktualizowało po płatnościach

**Comment by neldh** [comment]
@up Mogę od razu Ci powiedzieć, że takie coś nie będzie wyświetlane. Żeby zbierać tego typu dopłaty musisz żeglować po orders/events. Już to sprawdzałem.

**Comment by MartaNowaczyk** [comment]
@vendoremo 

> czy od chwili zmiany statusu zamówienia na READY_FOR_PROCESSING coś poza działem surcharges może ulec zmianie?
Nie, tylko dochodzi surcharges.

Co do drugiego pytania, to tak jak pisze neldh - trzeba to wychwycić z /orders/events.

**Comment by MartaNowaczyk** [comment]
@AssAssIn1909 dzięki za sugestię

**Comment by vendoremo** [comment]
Sugestia @AssAssIn1909 jest bardzo trafna. O ile dobrze pamiętam dane o zamówieniach są zwracane za ostatnie 6 miesięcy. A zatem stwierdzenie czy była dopłata może odbyć się poprzez przekopanie się przez zamówienia w bazie danych klienta i sprawdzenie czy do każdego z nich była dopłata albo przekopanie się przez zamówienia z ostatnich 6 miesięcy z rest api. Tak czy inaczej jest to dużo niepotrzebnych zapytań.
