### ISSUE TITLE
Jak sprawdzić ile mam obrazków w ofercie?

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#128]
Jak najlepiej sprawdzić ile obrazków jest dodanych do oferty ?

```
foreach (WSZYSTKIE_FIDY_OBRAZKOWE as FID) {
    sprawdzCzyFidWypełnionyCzyPusty(FID) ?
}
```

Czy jest jakiś inny lepszy sposób na to ?

Potrzebuje dodać obrazek i muszę się upewnić czy nie podmienie przez przypadek już istniejącego

**Comment by MarcinLuczak** [comment]
@cieplik206 nie pomożemy Ci w wybraniu odpowiedniej pętli/algorytmu (świadczymy wsparcie na poziomie protokołu SOAP), ale możemy CI wskazać odpowiednią metodę w WebAPI - za pomocą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842) możesz pobrać wszystkie wykorzystane w danej ofercie fidy, czyli także te odpowiedzialne za zdjęcia.

**Comment by cieplik206** [comment]
Nie chodzi mi o algorytm, ale policzenie FIDów obrazkowych wiąże się z pobraniem tych fidów  z ich wartością, co w przypadku kilku tysięcy ofert może spowodować wygenrowanie wielu dziesiątek megabajtów niepotrzebie

**Comment by rtnet-pl** [comment]
@cieplik206 doGetItemsInfo z getImageUrl =1 zwraca url-e do zdjęć, wystarczy policzyć niepuste url-e

**Comment by MarcinLuczak** [comment]
@cieplik206 no to rozwiązanie zaproponowane wyżej przez @rtnet-pl powinno Ci pomóc.

> doGetItemsInfo z getImageUrl =1 zwraca url-e do zdjęć, wystarczy policzyć niepuste url-e

**Comment by cieplik206** [comment]
Jest lepszy sposób

doGetItemsInfo zwraca takie parametry:

+"arrayItemListInfo": {#1122
    +"item": {#1123
      +"itemInfo": {#1124
        **"itFotoCount": 10**
