### ISSUE TITLE
Zmiana checkoutFormsId

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1280]
Dwukrotnie zdarzyła się zmiana wartości pola checkoutFormsId, przez co system zdublował zamówienia klientów.

**Comment by MartaNowaczyk** [comment]
@pfunkowski możesz opisać to szerzej. Jak się zmieniła?

**Comment by pfunkowski** [comment]
@MartaNowaczyk wyczerpująco odpowiedziałaś na to pytanie w https://github.com/allegro/allegro-api/issues/1279 gdzie zaznaczasz że wartość checkoutFormID może ulegać zmianie.

**Comment by MartaNowaczyk** [comment]
@pfunkowski nie wiedziałam do końca czy to ten przypadek ;)
