### ISSUE TITLE
Zamknięcie nie wznowionej oferty

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1281]
Czy istnieje możliwość zamknięcia nie wznowionej oferty? Zdarza się błąd wznawiania, przez co system wystawia aukcje ponownie, po czym posiadam dwie identyczne aukcji (jedna aktywna, druga nie). Stwarza to problem podczas grupowania ofert.

**Comment by MartaNowaczyk** [comment]
> Czy istnieje możliwość zamknięcia nie wznowionej oferty?

skoro się nie wznowiła to jest zakończona, prawda? Co dokładnie chcesz z nią zrobić? Dlaczego masz jedną zakończoną, a drugą aktywną. Powinieneś wznowić ofertę z tym samym numerem, wtedy nie ma takiego problemu. Jak wznawiasz oferty?

**Comment by pfunkowski** [comment]
oferty wznawiam poprzez /sale/offer-publication-commands
w większości wywołań problem nie występuje, sporadycznie oferta nie jest wznawiana, wtedy wystawiana jest z nowym id - postaram się prześledzić to zdarzenie

finalnie w panelu widzę z duplikowane oferty ze statusem aktywna i zakończona, w przypadku ręcznego wiązania ofert wielowariantowych należy odpiąć duplikowane

**Comment by MartaNowaczyk** [comment]
@pfunkowski ponawiacie próbę wznawiania, czy od razu wystawiacie na tej podstawie nową? Jeśli nie ponawiacie, to nie jest to dobre rozwiązanie. Takie oferty tracą popularność.
Poza tym nie można usunąć takiej oferty, także będzie widoczna na liście dla wielowariantowości.
