### ISSUE TITLE
Resp API - dwa formularze pozakupowe

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1282]
Czy możliwe jest aby klient wypełnił raz formularz pozakupowy a później drugi raz i za pierwszym razem zamówienie już było w statusie READY_FOR_PROCESSING ?
Screen ze zdarzeń tutaj
![screen_allegro](https://user-images.githubusercontent.com/5420924/53790367-116ad800-3f27-11e9-8f46-c345bcaf498c.png)

**Comment by MartaNowaczyk** [comment]
@pietrach nie powinno, kupujący może wtedy zrobić dopłatę, ale nic innego nie powinno się zmienić jeśli było zapłacone. Poza tym dałeś zrzut z Menedżera Sprzedaży, gdzie tam masz READY_FOR_PROCESSING - te zdarzenia są jeszcze po starym API ;)
