### ISSUE TITLE
Dostęp do kont środowiska testowego

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#1283]
Czy nagle zostały usunięte wszystkie konta z środowiska testowego / nastąpiła awaria logowania? Nie mogę się zalogować, na żadne z kont które założyłem. Dane na pewno poprawne.

**Comment by magik092** [comment]
Coś się chyba posypało, również mam z tym problem - oba konta mi zniknęły (#1222)

**Comment by LukaszCierocki** [comment]
@magik092 , dzięki. Już myślałem, że tylko u mnie występuje problem.

**Comment by MartaNowaczyk** [comment]
@all tak, mamy problem z logowaniem i samym sandboxem. Pracujemy nad tym.

**Comment by MartaNowaczyk** [comment]
@ALL logowanie działa. Dajcie znać, gdyby coś jeszcze nie działało.

**Comment by LukaszCierocki** [comment]
@MartaNowaczyk , niektóre zasoby nie zwracały prawidłowych wyników. Pobieranie zamówień zwracało tylko podstawowe dane, a nie zwracane były dane adresu itp.

**Comment by MartaNowaczyk** [comment]
@LukaszCierocki dzięki za info.
