### ISSUE TITLE
bulk create of offers drafts

### ISSUE THREAD

**Issue by SavanovicN** [allegro/allegro-api#1284]
Is there a way to create a multiple offers through api because we have couple of hundred of products so if we call your api per product to create offer it is costly and may leade to rate limit throtling maybe?

**Comment by magik092** [comment]
I think you have to implement all "loop logic" on your side. But using Create a draft offer method you can do some nice group auction form (call POST /sale/offers in loop).

**Comment by SavanovicN** [comment]
Thanks, will do
