### ISSUE TITLE
[SANDBOX] Status response 422 in GET-method /order/line-item-id-mappings

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1286]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://developer.allegro.pl/documentation/#operation/findMapping

Mam 422, jak nie daję parametrów:

 Narazie wysyłam request za pomocą Guzzle:
 $response = $client->createClientRequest()->get($this->getApiUrl() . '/order/line-item-id-mappings', [
                'headers' => [
            'Authorization' => "Bearer " . $token,
            'Accept' => 'application/vnd.allegro.beta.v1+json',
        ],
      ]);
i dostaję response 
![q2](https://user-images.githubusercontent.com/20610334/53798423-8266bb80-3f38-11e9-8e8e-36c0343c0a5f.png)

**Comment by MartaNowaczyk** [comment]
@runaway90 zawsze musisz podać parametr /order/line-item-id-mappings?lineItemId=2a75c8d0-fcc1-11e8-9a8c-5f5261db9f87 lub /order/line-item-id-mappings?dealId=1402007941

**Comment by runaway90** [comment]
@MartaNowaczyk  Dziękuję, ale w dokumentacji, nie uwidziałem że jest to jako wymagane parametrzy.

**Comment by MartaNowaczyk** [comment]
@runaway90 rozumiem, w takim razie dokumentacja do poprawy :)
