### ISSUE TITLE
Zdjęcia ?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1287]
Witam,
Czy w RestAPI jest możliwość sprawdzenia czy dane zdjęcie które było wcześniej dodane jest nadal na serwerze ? 

Jak długo są przechowywane zdjęcia które były związane z jakąś ofertą ?

**Comment by MartaNowaczyk** [comment]
@AleksyZajac czy chodzi ci o to jak długo zdjęcie przechowywane jest po zakończeniu oferty (gdy nie jest już nigdzie używane, nawet w drafcie)?

**Comment by AleksyZajac** [comment]
Chodzi mi o to jak długo mam dostęp do zdjęcia które raz było już w ofercie X.

Czy przy wystawianiu kolejnej za kilka dni mogę z skorzystać z tego zdjęcia do którego znam link bo już raz je do Was wysyłałem czy mam sobie wysłać ponownie ?

Oczywiście mając link mogę odpytać się o zasób HTTP i zobaczyć czy zwrócicie 404 czy może 200, ale to takie obejście tematu na około.

**Comment by AleksyZajac** [comment]
Aby przybliżyć temat to mamy część towaru rotującego który potrafi się nam skończyć a kolejną dostawę mam np. za 4 czy 5 dni. I na ten czas aukcja będzie zdejmowana a jak towar pojawi się na stanie wystawiana ponownie. 

I do takiego towaru przesyłamy zdjęcia do Was i potrzebuje wiedzieć kiedy takie zdjęcia usunięcie jak były w ofercie która się zakończyła a nowej do tego zdjęcia jeszcze niema.

**Comment by MartaNowaczyk** [comment]
zdjęcie, które nie jest użyte w żadnej aktywnej ofercie ani w drafcie trzymamy u nas 7 miesięcy. Jeśli masz kilka dni różnicy między wystawieniem kolejnych ofert to nie powinno być problemu.
