### ISSUE TITLE
Zdarzenia w doGetSiteJournal

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1288]
Hej!
Czy zmieniliście coś niedawno w doGetSiteJurnal?
Prawdopodobnie od dzisiaj pobrane ID oferty nie są dostępne na allegro.
Przykład: doGetSiteJurnal zwraca mi zmianę typu "start" i itemID: 7883491715

Wchodzę w link: https://allegro.pl/show_item.php?item=7883491715

I dostaję informację że oferta nie istnieje. Pojawia się dopiero po jakimś czasie. Mam wrażenie że to ID draftu który nie jest jeszcze dostępny w serwisie. Czy możecie to sprawdzić?

PS, podany Item ID prawdopodobnie będzie już istniał w momencie czytania przez was.

**Comment by MartaNowaczyk** [comment]
@jakubmaguza widocznie oferta jeszcze nie była widoczna w serwisie. Taka oferta powinna pojawić się maksymalnie do 1h, ale zazwyczaj trwa to kilka minut. Trzeba mieć to jednak na uwadze.

**Comment by jakubmaguza** [comment]
@MartaNowaczyk 
Hmm.. To nie jest jednorazowy przypadek. Dla każdego nowego zdarzenia typu "start" sytuacja się powtarza. Do dzisiaj nie było tego problemu. Myślę, że jeśli danej aukcji nie ma w serwisie, to nie powinno pojawiać się takie zdarzenie. Pytanie czy zmienialiście coś, czy to może być chwilowy problem?

**Comment by jakubmaguza** [comment]
Dobra, to były chwilowe problemy :)
