### ISSUE TITLE
Problem z logowanie do RestAPI

### ISSUE THREAD

**Issue by repmic** [allegro/allegro-api#1289]
Mam problem z zalogowaniem się do RestAPi,
Rejestruję aplikację pod adresem: https://apps.developer.allegro.pl/ logując się danymi allegro.
Otrzymuję Client ID /Klucz WebAPI, Client Secret, Adresy przekierowań, Opis.
Po zalogowaniu się do allegro w zakładce: Moje konto, Powiązane aplikacje. Mam informację nie masz powiązanych aplikacji.
Próba autoryzacji użytkownika przez wywołanie adresu: 
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21...6be&redirect_uri=http://exemplary.redirect.uri
zawraca błąd.
Co może być tego powodem?

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, co robisz po kolej. User powinien się uwierzytelnić, przydzielić dostęp i wtedy otrzymujesz specjalny kod, który jest ważny 10 sek i z nim przechodzisz do kroku 5. Zgodnie z [dokumentacją](https://developer.allegro.pl/auth/#user). Dopiero po poprawnym przejsciu tego kroku otrzymasz komplet danych dostępowych tzn access i refresh token.

**Comment by repmic** [comment]
Zaczynam od rejestracji pod adresem https://apps.developer.allegro.pl/ 
Następnie loguję się do allegro i przejdę na zakładkę Moje konto ->Logowanie i bezpieczeństwo konta -> Powiązane aplikacje 
to mam tam pusto nie mam żadnych powiązanych aplikacji.
Wcześniej miałem jeszcze stary klucz WebAPI z którego korzystałem kilka lat pewnie przez przypadek go usunąłem i teraz nie mogę korzystać nawet z WebApi. które do dziś działało bezbłędnie.

**Comment by PawelTaberski** [comment]
Wszystko się zgadza bo dopiero rejestruje Pan aplikacje, ale jeszcze nie powiązał Pan swojego konta z nią, wszystkie informacje jak to zrobić znajdzie Pan w [naszym poradniku](https://developer.allegro.pl/auth/).
