### ISSUE TITLE
Ilość obrazków i ich FIDY - SANDBOX nie wspiera pełnej funkcjonalności API

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#129]
Witam, zgodnie z dokumentacją można dodać 16 obrazków, przez WWW udaje się maks 10,a przez API tylko i wyłącznie 8.

Jak więc przez API zmienić/usunąć/dodać zdięcie nr 9 lub 10 ?

https://developer.allegro.pl/new_desc/
zgodnie z dokumentacją wyżej powinno być w ofercie 16 fidów.

`PHOTO_FID_16 - zdjęcie dodane pod FID 16
PHOTO_FID_17 - zdjęcie dodane pod FID 17
PHOTO_FID_18 - zdjęcie dodane pod FID 18
PHOTO_FID_19 - zdjęcie dodane pod FID 19
PHOTO_FID_20 - zdjęcie dodane pod FID 20
PHOTO_FID_21 - zdjęcie dodane pod FID 21
PHOTO_FID_22 - zdjęcie dodane pod FID 22
PHOTO_FID_23 - zdjęcie dodane pod FID 23
PHOTO_FID_342 - zdjęcie dodane pod FID 342
PHOTO_FID_343 - zdjęcie dodane pod FID 343
PHOTO_FID_344 - zdjęcie dodane pod FID 344
PHOTO_FID_345 - zdjęcie dodane pod FID 345
PHOTO_FID_346 - zdjęcie dodane pod FID 346
PHOTO_FID_347 - zdjęcie dodane pod FID 347
PHOTO_FID_348 - zdjęcie dodane pod FID 348
PHOTO_FID_349 - zdjęcie dodane pod FID 349`

Metoda doGetSellFormFieldsForCategory dla kategorii 1494 nie zwraca fidów 342-349, a jedynie 16-23,

Przez WWW da się dodać 2 zdięcia więcej czyli 10 z czego dwa ostatnie nie występują wogóle w w metodzie doGetItemFields

uploadowanie obrazka do FID 342 zgłasza taki błąd:

`string(77) "Wyniknęły problemy podczas przesyłania zdjęć. Request body not readable."
Nie Udało się !. Kod Błędu: ERR_OTHER_PHOTO_ERROR%`

WTF???

**Comment by MarcinLuczak** [comment]
@cieplik206 
> Metoda doGetSellFormFieldsForCategory dla kategorii 1494 nie zwraca fidów 342-349, a jedynie 16-23

Metoda doGetSellFormFieldsForCategory jak najbardziej zwraca informacje o fidach od 342 do 349. Tak samo za pomocą metody doChangeItemFields można edytować te fidy, czyli w ten sposób zmienić/usunąć zdjęcie.

Jeśli dodajesz nowe zdjęcie, upewnij się, że jest prawidłowe. Fidy od 342 do 349 działają tak samo jak fidy od 16 do 23.

**Comment by cieplik206** [comment]
Mowa o produkcyjnym API czy sandbox?

**Comment by cieplik206** [comment]
SANDBOX:

tests/Unit/AllegroAccountTest.php --filter=test_get_all_fields_for_category |grep Zdj -B 3 |grep sellFormId -A 1
  ["sellFormId"]=>
  int(16)

  ["sellFormId"]=>
  int(17)

  ["sellFormId"]=>
  int(18)

  ["sellFormId"]=>
  int(19)

  ["sellFormId"]=>
  int(20)

  ["sellFormId"]=>
  int(21)

  ["sellFormId"]=>
  int(22)

  ["sellFormId"]=>
  int(23)


A to jest produkcyjne API:

pu tests/Unit/AllegroAccountTest.php --filter=test_get_all_fields_for_category |grep Zdj -B 3 |grep sellFormId -A 1
  ["sellFormId"]=>
  int(16)

  ["sellFormId"]=>
  int(17)

  ["sellFormId"]=>
  int(18)

  ["sellFormId"]=>
  int(19)

  ["sellFormId"]=>
  int(20)

  ["sellFormId"]=>
  int(21)

  ["sellFormId"]=>
  int(22)

  ["sellFormId"]=>
  int(23)

  ["sellFormId"]=>
  int(342)

  ["sellFormId"]=>
  int(343)

  ["sellFormId"]=>
  int(344)

  ["sellFormId"]=>
  int(345)

  ["sellFormId"]=>
  int(346)

  ["sellFormId"]=>
  int(347)

  ["sellFormId"]=>
  int(348)

  ["sellFormId"]=>
  int(349)


Dlaczego API w SANDBOX != PRODUKCJA

**Comment by cieplik206** [comment]
a może to ma związek z tym:
![image](https://user-images.githubusercontent.com/6499144/38501532-8a044a8a-3c0d-11e8-90cf-eaa870fc053d.png)

**Comment by MarcinLuczak** [comment]
@cieplik206 na Sandboxie też wraca, tylko, jak słusznie zauważyłeś, musisz mieć konto firmowe.
