### ISSUE TITLE
"/sale/offers" zwracał wypełniony obiekt "delivery"?

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1291]
Czy jest możliwe aby zasób "/sale/offers" zwracał wypełniony obiekt "delivery"? Aktualnie zwraca 'null'.

Pozdrawiam
Wojtek, prawdopodobnie najlepszy koder!

**Comment by MartaNowaczyk** [comment]
@centrumelektroniki w tej chwili prawidłowe jest korzystanie z wersji beta dla GET /sale/offers, a tam takiego pola nie ma.

**Comment by centrumelektroniki** [comment]
Tzn, że aby pobrać informację o cenniku "shippingRates" dla oferty, należy w przypadku 4000tyś. ofert wywołać 4000 tyś. razy "/sale/offers/{offerId}"?
Gdyby informacja ta była zawarta w "/sale/offers" znacznie zoptymalizowało by to nasz kod do czterech requestów. Czy można by ją dołączyć do zwracanego obiektu?

**Comment by MartaNowaczyk** [comment]
@all ok, rozumiem potrzebę, przekazałam sugestię do odpowiedniego zespołu.

**Comment by centrumelektroniki** [comment]
Dzień dobry, jest szansa, że nasz sugestia zostanie wprowadzona w życie ?

**Comment by MartaNowaczyk** [comment]
Na ten moment nie mamy w planach zmian w tym zakresie. Czy kiedykolwiek się to zmieni, tego nie wiem, dlatego nie mówię nie.
