### ISSUE TITLE
Rest API => Zdjęcia limity

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1292]
Czy nadal są jakieś limity w ilości dodawanych zdjęć do oferty ?

**Comment by MartaNowaczyk** [comment]
@pietrach według naszych [zasad](https://allegro.pl/dla-sprzedajacych/nowe-zasady-dla-zdjec-w-galerii-i-w-opisie-YLlAAa2oXf7) do oferty dodasz:

-   na koncie zwykłym - 10 zdjęć
-   na koncie firmowym - 16 zdjęć.
