### ISSUE TITLE
Czas wystawienie oferty

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1293]
W jaki sposób przygotować draft oferty, która ma zostać "odpalona" o określonej godzinie.  Wydawałoby się, że w publication trzeba ustalić wartość startingAt. Tyle tylko, że gdy wysyłam
POST /sale/offers:
...
publication:{"duration":"PT168H","status":"INACTIVE","startingAt":"2019-03-06T18:00:00Z","endingAt":null}
...

otrzymuję w odpowiedzi:
...
publication":{"duration":"PT168H","status":"INACTIVE","startingAt":null,"endingAt":null}
...

**Comment by MartaNowaczyk** [comment]
@lukada4100 Zasób o którym piszesz pozwala stworzyć draft. Do zaplanowania godziny wystawiania utworzonego draftu masz metodę  PUT /sale/offer-publication-commands/{commandId}. [Więcej w naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

**Comment by lukada4100** [comment]
Nie chodzi mi o czas kiedy szkic zamieni się w aktywną ofertę. Komendą o której piszesz chciałbym zamienić szkic w ofertę zaplanowaną i ustawić moment, kiedy ta zaplanowana oferta zamieni się w ofertę aktywną.
Innymi słowy, pytanie brzmi, jak stworzyć ofertę, która w panelu Allegro widoczna będzie w sekcji "Zaplanowane".

**Comment by lukada4100** [comment]
Dzięki.
