### ISSUE TITLE
Rest API - get /sale/offers

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#1294]
Witam
W jaki sposób można pobrać z zasobów get /sale/offers całkowitą ilość sprzedanych sztuk od początku trwania oferty, która konieczna jest do wyliczenia ilości sztuk którą podajemy w sytuacji uzupełnienia ilości szt w ofercie? Z zasobów publicznych nie ma takiej możliwości - była w starym api.
W ofertach wielowariantowych get /sale/offers pole "sold" zwraca dane tylko z ostatnich 30 dni a pole "popularity" z metody get /offers/listing sumę z wszystkich wariantów rozmiarowych z ostatnich 30 dni.
pozdrawiam

**Comment by rtnet-pl** [comment]
Nie pobierzesz tej ilości, natomiast możesz podać ilość dostępną https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT
