### ISSUE TITLE
/sale/offers - szczegóły oferty

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#1295]
Witam

Czy jest możliwe za pomocą jednego zapytania /sale/offers pobranie całej listy przedmiotów wraz ze szczegółami tej oferty? bez zbędnego odwoływania się do każdej z osobna poprzez konkretny ID? /sale/offers/{id}

**Comment by MartaNowaczyk** [comment]
Witam, nie wiem na ile te szczegóły będą dla ciebie wystarczające, ale jest taka możliwość. Skorzystaj z metody GET na zasobie /sale/offers. [Więcej tutaj](https://developer.allegro.pl/my_offers/#1).

**Comment by slawomir-kudla** [comment]
Hmm... chyba nie do końca się zrozumieliśmy chodzi o to że /sale/offers nie pobiera pełnej informacji (głównie chodzi mi o ogłoszenia) jak podaje dokładnie /sale/offers/id to mam wszystko odnośnie tego ogłoszenia ile samochód ma drzwi, jaki kolor etc. a takich informacji brakuje przy zwykłym zapytaniu /sale/offers są tam jedynie takie podstawowe informacje jak: id, czas trwania kilka statusów

**Comment by MartaNowaczyk** [comment]
@slawomir-kudla nie ma innego sposobu. To prawda, lista ofert nie zawiera wszystkich informacji, które możesz pobrać przy pojedynczej ofercie.

**Comment by pietrach** [comment]
Dobrze by było aby dodać pole "sold" do metody GET /sale/offers/{offerId}, natomiast w metodzie GET sale/offers jest.

**Comment by MartaNowaczyk** [comment]
@pietrach dziękujemy za sugestię. Przekazałam ją do odpowiedniego zespołu.
