### ISSUE TITLE
Dublowanie aukcji WebAPI

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#1296]
Witam,

czy istnieje możliwość sprawdzenia czy dana oferta została wystawiona 2 razy poprzez WebAPI,
czy może została zdublowana przez jakiś błąd po stronie WebAPI ?

Oferta: 7886797839 została wystawiona przez WebAPI - znajduję się w naszych logach
Oferta: 7886667564 - Zdublowana - brak jakichkolwiek informacji w naszych logach 

Czy jest możliwe że WebAPI zwraca błąd w momencie wywołania doNewAuctionExt - a tak naprawdę oferta zostaje wystawiona, a potem nasz system po ponownej próbie wystawia ofertę ponownie ?

W ostatnich paru dniach jest wiele takich przypadków a do tej pory nie było - nic nie było zmienne z logiką wystawiania po naszej stronie. 

Proszę o szybką odpowiedz.

**Comment by MartaNowaczyk** [comment]
Tak nie powinno być, dlatego podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pliki z requestem i responsem, gdzie widać błąd podczas wystawiania, a oferta i tak jest wystawiona. Napisz tylko, że dotyczy GitHuba #1296. Sprawdzę w czym jest problem.

**Comment by joe1d83** [comment]
Witam,
okazało się że jednak był to problem po naszej stronie.

Zamykam temat i przepraszam za kłopot.
