### ISSUE TITLE
ResAPI - zmiany w aukcjach trwających - ograniczenia

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1298]
Gdzie mogę znaleźć wszelkie informacje o ograniczeniach dotyczących zmian w trwających ofertach np. tak jak tutaj https://allegro.pl/dla-sprzedajacych/edycja-ceny-w-trwajacych-ofertach-zmiana-zasad-od-24-wrzesnia-wq0rgbzEqhL. Chodzi mi kiedy mogę zmienić cenę, kiedy kategorię itd. Już kiedyś o to pytałem ale nie uzyskałem odpowiedzi do końca

**Comment by MartaNowaczyk** [comment]
Ogólne zasady znajdziesz [w naszej pomocy.](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn). Czy o takie zestawienie ci chodziło?

**Comment by pietrach** [comment]
@MartaNowaczyk dokładnie tak :-)

**Comment by MartaNowaczyk** [comment]
:)

**Comment by pietrach** [comment]
A co z tytułem oferty ? Nic tutaj nie zostało wspomniane. Czy to jest podpięte jako opis oferty ?

**Comment by MartaNowaczyk** [comment]
Rzeczywiście, nie ma tam tego. Tytuł możesz zmienić jeśli nie było sprzedaży w ofercie.
