### ISSUE TITLE
Uzupełnianie numeru przesyłki z poziomu API 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#13]
Kiedy można się spodziewać zarządzania zakładką zamówienia, lub chociaż uzupełniania numeru listu przewozowego ?

**Comment by AniaMalinowska** [comment]
Sprawdź, czy metoda [doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744) odpowiada na te potrzeby.

**Comment by yncki** [comment]
Jak najbardziej, dzieki!
