### ISSUE TITLE
Metoda doGetSiteJournalDeals przestała zwracać dane

### ISSUE THREAD

**Issue by dtarczynski** [allegro/allegro-api#130]
Metoda doGetSiteJournalDeals przestała zwracać dane dla nowych transakcji. Ostatnie zdarzenie jakie do mnie przychodzi jest z 05.04.2018, czyli z czwartku.

SellerId: 43942144

Coś w tej kwestii się znieniło? Proszę o pomoc.

**Comment by MarcinLuczak** [comment]
@dtarczynski Nic nie zmienialiśmy. Czy problem nadal występuje?

**Comment by dtarczynski** [comment]
Ruszyło w pewnym momencie i teraz juz działa.
