### ISSUE TITLE
GET /sale/offer-publication-commands/{commandId}/tasks - statusy

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1300]
Metoda ta zwraca statusy dla każdej przetworzonej oferty: SUCCESS, FAIL, NEW.
Czy status NEW oznacza, że jeszcze żądanie dezaktywacji / aktywacji oferty nie zostało przeprowadzone.
Natomiast statusy SUCCESS - oznacza, że dana akcja powiodła się dla danej oferty, natomiast FAIL, że dana akcja nie powiodła się dla danej oferty ?

**Comment by MartaNowaczyk** [comment]
SUCCESS  - publikacja zakończyła się pomyślnie
FAIL - wystąpiły błędy przy publikacji i oferta nie jest aktywna w serwisie
NEW - trwa publikacja oferty w serwisie / akcja nie została jeszcze zakończona

**Comment by pietrach** [comment]
@MartaNowaczyk a jaki status będzie w przypadku trwa jeszcze zakańczanie oferty / akcja nie została jeszcze zakończona ?

**Comment by MartaNowaczyk** [comment]
w takim wypadku powinno być NEW
