### ISSUE TITLE
Telefon kontaktowy - wysyłka do punktu odbioru Poczty, Orlen...

### ISSUE THREAD

**Issue by mack3d** [allegro/allegro-api#1301]
Pewnie to już było gdzieś wspomniane iż poczta polska do obsługi zamówień wysyłanych do punktów odbioru wymaga podania numeru telefonu komórkowego.
Niestety dość często zdarza się iż klient podaje numer stacjonarny co uniemożliwia zaadresowanie prawidłowo paczki.
Dodam że nie chcemy wysyłać przesyłki bez prawidłowego numeru gdyż poczta wysyła sms-a o informacji na temat statusu paczki co wpływa na skuteczność doręczenia/odebrania paczki przez klienta.

Sugeruję wprowadzenie walidacji numeru telefonu przy wyborze tej formy wysyłki.

Maciej

**Comment by MartaNowaczyk** [comment]
Jeśli sugestie dotyczą działania samego allegro, a nie zmiany w API proszę przekazuj je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Zajmują się tym całkiem inne zespoły.
