### ISSUE TITLE
Rest API - get /sale/offers/{offerId} 

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#1302]
Witam
Czy metodą get /sale/offers/{offerId}  lub get /sale/offers jestem w stanie pozyskać pole "sygnatura" które zostało ostatnio dodane w ofertach ? Nie mogę znaleźć tego w dokumentacji

pozdrawiam

**Comment by MartaNowaczyk** [comment]
@MichalOmega Tak możesz. Sygnatura znajduje się tutaj:

"external": {
                "id": "sygnatura"
            }

[Więcej w naszym poradniku](https://developer.allegro.pl/my_offers/).
