### ISSUE TITLE
Konto firma - tagi

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1305]
Czy użytkownik nie będący w Strefie Marek może korzystać z tagów ? Chodzi mi o konto firma.

**Comment by pietrach** [comment]
I od razu dodatkowe pytanie => czy jak dany sprzedawca na Allegro będzie należał do programu Tob Brand Partner to będzie mógł korzystać z mechanizmu tagów poprzez API itp. ?

**Comment by kfijalko** [comment]
Tagi są dostępne w ramach abonamentu sklepowego dla kont firma.
Możesz sprawdzić w panelu allegro:
moja sprzedaż->usługi dla sprzedających->abonamenty jeżlei masz aktywne to w menu
moja sprzedaż->sklep allegro masz tagi + dostęp przez api
