### ISSUE TITLE
ERR_ITEM_NAME_TOO_LONG

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1306]
Dlaczego taki tytuł:
[1szt] AN87C196KN INTEL uPC 16Bit , B58244 => AN87

Nie jest poprawny?
Przy próbie wprowadzenia takiej aukcji dostaję błąd:
ERR_ITEM_NAME_TOO_LONG

Tytuł ma dokładnie 50 znaków. Próbwałem nawet skrócić go o jeden znak i dalej jest ten sam error.

**Comment by jakubmaguza** [comment]
![image](https://user-images.githubusercontent.com/24191650/53972564-4fbaef80-40ff-11e9-90ea-0123a49a16e7.png)

Tak to wygląda na szkicu. Nie ma żadnych spacji na końcu ani w środku. Jest dokładnie taki jak wyżej wysłałem czyli 50 znaków.

**Comment by MartaNowaczyk** [comment]
@jakubmaguza niektóre znaki zamieniane są na encje. W tym przypadku znak ">" to rzeczywiście 4 znaki ("&gt;"), stąd to zamieszanie.

**Comment by jakubmaguza** [comment]
@MartaNowaczyk 
Dziękuję za odpowiedź. Czy planujecie coś z tym zrobić, czy tak zostanie? Jeśli zostanie, to proszę o listę znaków które 'kradną' 3 dodatkowe znaki :)

**Comment by MartaNowaczyk** [comment]
@jakubmaguza  nie palnujemy tego zmienić. [Tu](https://developer.allegro.pl/sale/#step-4-title) znajdziesz znaki, które możesz użyć w tytule. Poniższe znaki zamieniamy na encje i zajmują one:

  & - 5 znaków   |    > - 4 znaki    |    < - 4 znaki    | " - 6 znaków.

**Comment by jakubmaguza** [comment]
Dzięki!
Stronę widziałem, nie widziałem informacji o encjach :)
