### ISSUE TITLE
UpdatedAt na liście ofert

### ISSUE THREAD

**Issue by MasterSlynx** [allegro/allegro-api#1307]
:bulb: **Sugestia**
Zdecydowanie przydałaby się informacje o czasie ostatniej aktualizacji oferty z poziomu listy ofert ("sale/offers"). Jest to informacja, która tam powinna być od samego początku. Na chwilę obecną zmuszacie mnie do nieustannego "bombardowania" serwera koniecznością pobierania szczegółów ("sale/offers/{guid}") KAŻDEJ oferty by ustalić czy zostały wprowadzone jakieś zmiany. Szukałem jakiejś alternatywy czy filtru ale nic.
Na serwerze testowym dla 50 ofert to nie robi specjalnie wrażenia, ale jak to pójdzie na serwery produkcyjne na konto na którym jest 1000+ ofert... ciężko będzie wytłumaczyć dlaczego usługa generuje taki duży ruch 😕 
Aż dziwne, że nikt wcześniej o tym nie wspomniał...
Wolałbym usłyszeć, że czegoś nie zauważyłem i szybko wprowadzić zmianę nić czekać kilka(naście) dni na potencjalną zmianę 🙄

**Comment by pijablonski** [comment]
Chętnie zobaczyłbym podobną informację także na /offers/listing

**Comment by MartaNowaczyk** [comment]
@MasterSlynx przekazałam tę sugestię do odpowiedniego zespołu.

**Comment by grzegorzjj** [comment]
Generalnie 50% zgłoszeń dotyczących /offers/listing dotyczy braku parametrów dostępnych do tej pory w doGetItemsList, co nie jest dziwne, bo skoro wygasza się metodę z klasy A to należy udostępnić metodę o porównywalnych własnościach w klasie B. 
Większość tych zgłoszeń kończy się 'przekazałam/em tę sugestię do odpowiedniego zespołu'.
A zostało 2 tygodnie.

**Comment by MartaNowaczyk** [comment]
@grzegorzjj tak jak pisaliśmy w #191 będziemy pracować nad zasobem, który zwróci publiczne dane o użytkowniku. Udostępnimy go w ciągu najbliższych dwóch kwartałów.
