### ISSUE TITLE
Pobranie Marki / Modelu / Wersji pojazdu

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#1308]
Witam

Mam listę ogłoszeń i chcę pobrać ów listę na stronę i wrzucić dane w odpowiednie miejsca niestety napotkałem trochę trudny problem w przypadku gdy pobieram dany model który ma wersję, wersja ma parent_id który prowadzi do modelu, model ma parent_id który prowadzić do marki niestety nie wszystkie oferty mają swoje wersje więc wstawiając do bazy dane trochę głupoty mogą wyjść... co Państwo polecacie jak pobrać faktyczną markę/model pojazdu?

**Comment by MartaNowaczyk** [comment]
@slawomir-kudla możesz doprecyzować o co dokładnie chodzi? Z jakiej metody korzystasz, czy chodzi o "pasuje do" czy może jeszcze o coś innego...

**Comment by slawomir-kudla** [comment]
Pobieram aktualną listę wystawionych ogłoszeń metodą GET /offers/listing?seller.id=44028170
Następnie posiadając listę na podstawie ID pobieram szczegóły oferty metodą: GET /sale/offers/6206216889

Dostaję prawie wszystkie szczegóły od "absu" po kolor, wszystkie zdjęcia, nazwę itp... ale w całej liście brakuje takiej informacji jak: marka, model, wersja

**Comment by slawomir-kudla** [comment]
tak wygląda wynik zwrócony

    [id] => 6206216889
    [name] => Moje ogłoszenie
    [category] => Array
        (
            [id] => 18153
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 1
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 1999
                        )

                    [rangeValue] => 
                )

            [2] => Array
                (
                    [id] => 4
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 222333
                        )

                    [rangeValue] => 
                )

            [3] => Array
                (
                    [id] => 5
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 2000
                        )

                    [rangeValue] => 
                )

            [4] => Array
                (
                    [id] => 14
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 300
                        )

                    [rangeValue] => 
                )

            [5] => Array
                (
                    [id] => 16
                    [valuesIds] => Array
                        (
                            [0] => 16_5
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [6] => Array
                (
                    [id] => 13
                    [valuesIds] => Array
                        (
                            [0] => 13_246586
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [7] => Array
                (
                    [id] => 12
                    [valuesIds] => Array
                        (
                            [0] => 12_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [8] => Array
                (
                    [id] => 128789
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 5
                        )

                    [rangeValue] => 
                )

            [9] => Array
                (
                    [id] => 128791
                    [valuesIds] => Array
                        (
                            [0] => 128791_4
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [10] => Array
                (
                    [id] => 128793
                    [valuesIds] => Array
                        (
                            [0] => 128793_1
                            [1] => 128793_2
                            [2] => 128793_4
                            [3] => 128793_8
                            [4] => 128793_64
                            [5] => 128793_128
                            [6] => 128793_16384
                            [7] => 128793_8192
                            [8] => 128793_4096
                            [9] => 128793_2097152
                            [10] => 128793_67108864
                            [11] => 128793_1048576
                            [12] => 128793_524288
                            [13] => 128793_262144
                            [14] => 128793_131072
                            [15] => 128793_65536
                            [16] => 128793_32768
                            [17] => 128793_16
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [11] => Array
                (
                    [id] => 3
                    [valuesIds] => Array
                        (
                            [0] => 3_10
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [12] => Array
                (
                    [id] => 128792
                    [valuesIds] => Array
                        (
                            [0] => 128792_3
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [13] => Array
                (
                    [id] => 128790
                    [valuesIds] => Array
                        (
                            [0] => 128790_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [14] => Array
                (
                    [id] => 178
                    [valuesIds] => Array
                        (
                            [0] => 178_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [15] => Array
                (
                    [id] => 128788
                    [valuesIds] => Array
                        (
                            [0] => 128788_14
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [16] => Array
                (
                    [id] => 200
                    [valuesIds] => Array
                        (
                            [0] => 200_1
                            [1] => 200_8
                            [2] => 200_2
                            [3] => 200_128
                            [4] => 200_1024
                            [5] => 200_16
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [17] => Array
                (
                    [id] => 211062
                    [valuesIds] => Array
                        (
                            [0] => 211062_246554
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [18] => Array
                (
                    [id] => 199
                    [valuesIds] => Array
                        (
                            [0] => 199_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [19] => Array
                (
                    [id] => 211066
                    [valuesIds] => Array
                        (
                            [0] => 211066_246566
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [20] => Array
                (
                    [id] => 211070
                    [valuesIds] => Array
                        (
                            [0] => 211070_64
                            [1] => 211070_128
                            [2] => 211070_2
                            [3] => 211070_4
                            [4] => 211070_32
                            [5] => 211070_1
                            [6] => 211070_16
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [21] => Array
                (
                    [id] => 215882
                    [valuesIds] => Array
                        (
                            [0] => 215882_272070
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [22] => Array
                (
                    [id] => 215886
                    [valuesIds] => Array
                        (
                            [0] => 215886_272078
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [23] => Array
                (
                    [id] => 215898
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 123456789012
                        )

                    [rangeValue] => 
                )

        )

    [ean] => 
    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => OPIS
                                        )

                                )

                        )

                )

        )

    [compatibilityList] => 
    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.allegrosandbox.pl/original/030de2/3c18bcef43c19ccb02372e3e3746
                )

            [1] => Array
                (
                    [url] => https://a.allegroimg.allegrosandbox.pl/original/0377c1/a57cbcb344c6aaf73d2eed3fce66
                )

            [2] => Array
                (
                    [url] => https://a.allegroimg.allegrosandbox.pl/original/03907c/158d24604a8bb4585e8604589d2b
                )

        )

    [sellingMode] => Array
        (
            [format] => ADVERTISEMENT
            [price] => Array
                (
                    [amount] => 35000
                    [currency] => PLN
                )

            [startingPrice] => 
            [minimalPrice] => 
        )

    [stock] => 
    [publication] => Array
        (
            [duration] => 
            [status] => ACTIVE
            [startingAt] => 
            [endingAt] => 
        )

    [delivery] => Array
        (
            [shippingRates] => 
            [handlingTime] => 
            [additionalInfo] => 
            [shipmentDate] => 
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => 
    [additionalServices] => 
    [sizeTable] => 
    [promotion] => 
    [location] => Array
        (
            [countryCode] => PL
            [province] => MAZOWIECKIE
            [city] => Radom
            [postCode] => 26-600
        )

    [external] => 
    [attachments] => Array
        (
        )

    [contact] => Array
        (
            [id] => f771f5bd-c1c1-4a3f-9a30-1cff663adad2
        )

    [validation] => Array
        (
            [errors] => Array
                (
                )

            [validatedAt] => 2019-03-08T14:23:20.637Z
        )

    [createdAt] => 2019-03-07T21:40:19Z
    [updatedAt] => 2019-03-08T14:23:21.397Z

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak tego nie ma w parametrach, określa to kategoria, którą wybierasz.

**Comment by slawomir-kudla** [comment]
tak zgadza się ale tak jak wcześniej napisałem nie jestem w stanie stwierdzić czy dana kategoria jest marką wersją czy modelem a nie chcę błędnie wprowadzać dane mogę wykonać dodatkowy request aby ściągnąć dodatkowe informacje tylko potrzebuje mieć pewność że marka jest marką

czy jest możliwość by taka funkcja w najbliższym czasie doszła? klienci bardzo naciskają na taką opcję planują zrezygnować z otomoto na rzeczy allegro

bardzo proszę o odpowiedź
pozdrawiam

**Comment by MartaNowaczyk** [comment]
@slawomir-kudla tak to w naszym serwisie działa i na ten moment nie mamy w planach zmiany w tym zakresie. Oczywiście przekażę twoją sugestię do odpowiedniego zespołu.
