### ISSUE TITLE
Mapowanie numeru płatności

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#1309]
Czy istnieje jakiś sposób aby zmapować numer płatności z checkoutForm (przykład "abd30d72-9583-11e8-96ed-27298c74ae02") na numer karty płatności (przykład 777936345)?
Potrzebuję jakoś połączyć te dane, w systemie mam inne wartości niż na wyciągach. W zestawieniu wypłaty są tylko wartości z Allegro i przy imporcie nie mam jak tego połączyć. Korzystam tylko z REST api.

Wiem że temat był już poruszany, jednak nie widzę żadny zmian, a może coś się jednak zmieniło. Ewentualnie jakie macie plany do zmiany tego

**Comment by MartaNowaczyk** [comment]
W tej chwili nie mamy bezpośredniego mapowania tych pól. Jest tylko [mapowanie lineItemId na dealId](https://github.com/allegro/allegro-api/issues/731) i odwrotnie. Rozumiem potrzebę, dlatego zgłosiłam taką sugestię do odpowiedniego zespołu.

**Comment by AssAssIn1909** [comment]
Tyle że na podstawie dealId jestem w stanie coś więcej wyciągnąć z RestAPI?
Albo czy to gdzieś jest wyświetlane na stronie Allegro?

**Comment by neldh** [comment]
Możesz sobie sam coś takiego ogarnąć wykorzystując mapowanie po lineItemId <-> dealId.
Ja to robie tak, że korzystam z obu api  i zbieram rownolegle informacje o zamowieniach, a dla każdego dealId/lineItemId zapamiętuje ich powiązanie ze wspomnianego mapowania i wtedy mogę dojść do powiązania na wyższym poziomie. Męczący workaround, masa żądań w obu api, ale w moim wypadku potrzebuje tego tylko w okresie przejściowym i to raz dziennie, więc mogę sobie na to pozwolić.

**Comment by AssAssIn1909** [comment]
Dziękuje za informacje.
Rozumiem, że macie dużo pracy podczas migrowania i tworzenia REST Api, ale nie rozumiem dlaczego tak dużo rzeczy jest różnych w stosunku do interfejsu w przeglądarce. Brak mapowania numerów płatności z kartą płatności ( w sytuacji kiedy oba te numery są obok siebie w przeglądarce, przez co rozumiem że dokopanie się do nich nie stanowi problemu ) stanowi bardzo duży problem przy automatyzacji zatwierdzania przelewów. Nie wymagam dużo. Nawet prosty zasób który przyjmuje numer płatności a zwraca numer karty płatności (potem można to rozszerzyć  o jakieś pola) lub pole w obiekcie "payment" na checkoutForm.
Wykorzystywanie drugiego interfejsu tylko po to aby móc pobrać te numery trochę mija się z celem.
W jakim czasie można by było spodziewać się  wprowadzenia takiej funkcjonalności?

**Comment by MartaNowaczyk** [comment]
@AssAssIn1909 takie rozwiązanie jest już przekazane do odpowiedniego zespołu. Nie mogę jednak obiecać czy i kiedy się pojawi. Będziemy o tym informować w oddzielnym komunikacie.

**Comment by AssAssIn1909** [comment]
Dziękuje za informacje.
Takie pytanko jeszcze, bo dostałem zrzut ekranu z zamówienia ze środowiska produkcyjnego na którym widnieje informacja, że numer płatności w formie 12665ba2-3e4e-11e9-a06f-d9b9782d1fa8 niedługo będzie dostępny w całym systemie. Czy to oznacza że za niedługo zacznie się on pojawiać na wyciągach zamiast tego krótkiego numeru? (Plik z zestawienie wypłaty wraz z numerami płatności)

**Comment by MartaNowaczyk** [comment]
@AssAssIn1909 tak, długoterminowo planujemy zmiany numerów płatności na nową formę (UUID) w całym serwisie, również w zestawieniach, natomiast na ten moment nie mamy sprecyzowanego terminu. Na pewno poinformujemy o tym w komunikacie.
