### ISSUE TITLE
Pytanie: Pełna rejestracja konta firma, jaka procedura ?

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#131]
Witam, 

Jak wygląda procedure na sandbox aby w pełni zweryfikować i dokończyć rejestracje konta firma?

W statusie widze:

![image](https://user-images.githubusercontent.com/6499144/38501805-203ba372-3c0e-11e8-9882-ffc7ab228c72.png)

Na produkcji wysyła się dokumenty firmowe a jak w piaskownicy ?

**Comment by MarcinLuczak** [comment]
@cieplik206 jaki jest login tego konta? Czy aktywowałeś już to konto?

**Comment by cieplik206** [comment]
Tak konto aktywowane. Ale status firma nie. Mam wam podać tutaj wszystkie ID/ loginy ?

**Comment by MarcinLuczak** [comment]
@cieplik206 podaj loginy tych kont na Sandboxie, które rejestrowałeś jako firmowe lub które przekształacasz na firmowe.

**Comment by cieplik206** [comment]
43955772 oraz 43955789

**Comment by MarcinLuczak** [comment]
@cieplik206 dzięki, sprawdzamy.

**Comment by cieplik206** [comment]
I co jak z tym statusem firma ?

**Comment by MarcinLuczak** [comment]
@cieplik206 dam znać, gdy będę wiedział coś więcej. Na chwilę obecną nie jestem w stanie ręcznie zmienić tych kont na firmowe.

**Comment by MarcinLuczak** [comment]
@cieplik206 Konto 43955772 jest już kontem firma. W przypadku konta 43955789 nie przeszedłeś procesu dalej, dlatego po naszej stronie nie możemy go przeprocesować.
