### ISSUE TITLE
ResAPI - zarządzanie tagami w ofertach ze statusami END, ENDING, ACTIVATING, INACTIVE

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1311]
Czy mogę przypisywać tagi do ofert ze statusami END, ENDING, ACTIVATING, INACTIVE ?

**Comment by MartaNowaczyk** [comment]
Zmiany w ofercie możesz robić w chwili gdy jest zakończona i gdy jest aktywna dlatego nie powinno być problemu.

**Comment by FromAnyHole** [comment]
@pietrach - hejka, spotykasz status ENDING w ofertach ? Jak często ??

**Comment by pietrach** [comment]
Niespotykam, tak zapytałem :) 
            
          
     
      
       
        Dnia 10 marca 2019 20:21 FromAnyHole &lt;notifications@github.com&gt; napisał(a):
       
    
       
         github.com @pietrach  - hejka, spotykasz status ENDING w ofertach ? Jak często ??

**Comment by FromAnyHole** [comment]
@pietrach - Ok, bo już szukałem po poradniko-dokumentacji, a tam porządek... ! ;-)
