### ISSUE TITLE
Kalkulator opłat - niejasne pola

### ISSUE THREAD

**Issue by pijablonski** [allegro/allegro-api#1312]
Proszę o bardziej szczegółowe informacje dotyczące pól:

- numberOfPhotos i numberOfBigPhotos - skąd dwie wartości, co oznaczają i czym się różnią?
- hasAnyQuantity - w kontekście istniejącego obok quantity
- type - czy wartości "shop", "offer", "advertisement" to odpowiednik offer.sellingMode.format "BUY_NOW","AUCTION","ADVERTISEMENT", czy może coś innego?

**Comment by MartaNowaczyk** [comment]
1/ te opcje nie są w tej chwili dostępne - nie ma opłat za zdjęcia
2/ liczba przedmiotów w ofercie nie ma znaczenia, jest ważna kwota początkowa
3/ nie jest to ten odpowiednik. Dla "shop" i "offer" mamy te same opłaty w tym momencie. Nowe wystawione oferty będą na ten moment typu "offer" lub "advertisement", w zależności czy to oferta czy to ogłoszenie.
