### ISSUE TITLE
wyszukiwanie nowych ofert w zasobie offers/listing

### ISSUE THREAD

**Issue by atmdevnet** [allegro/allegro-api#1313]
dzień dobry,
pytanie jest takie: 
czy w zasobie offers/listing możliwe jest wyszukiwanie wszystkich nowych ofert w wybranej kategorii na zasadzie podobnej jak w wygaszanej metodzie webapi doGetItemsList ?

W metodzie webapi doGetItemsList, żeby wyszukać wszystkie nowe oferty w wybranej kategorii, ustawiam w parametrze typu FilterOptionsType wartości filterId na "special" oraz filterValueId na "new".

W odpowiadającym zasobie rest api offers/listing, zgodnie z jego dokumentacją, żeby osiągnąć wspomniany cel, mam możliwość ustawienia parametru "sort" na "-startTime", czyli pobrać oferty z wybranej kategorii posortowane wg czasu wystawienia oferty począwszy od najnowszych. Kierując się zatem wskazówkami z dokumentacji i poradnika odwołuję się do zasobu offers/listing w taki sposób:

`https://api.allegro.pl/offers/listing?category.id=1454&sort=-startTime&fallback=false&limit=100&offset=0&include=-categories&include=-sort&include=-filters`

Innej możliwości osiągnięcia mojego celu w rest api niestety nie widzę posługując się dokumentacją i poradnikiem. (swoją drogą, obecnie dostępna dokumentacja jest wyjątkowo skromna, co jest dość frustrujące wziąwszy pod uwagę fakt, że metoda doGetItemsList już za 3 tygodnie zostanie usunięta).

Ale do rzeczy, porównując wyniki obu odpowiadających sobie zasobów doGetItemsList w webapi i offers/listing w rest api, od razu zwraca uwagę kolosalna różnica w liczbie zwracanych ofert. Wyniki z dzisiejszego wieczora dla przykładowej kategorii id=1454 (odzież...): 
- doGetItemsList w ciągu zaledwie niespełna 10 minut zwróciło około 1200 nowych ofert (co jest rzeczą normalną),
- offers/listing, natomiast, o tej samej porze dnia, w ciągu aż 2 godzin zwróciło zaledwie około 160 ofert (sic!).
Wnioskuję na podstawie tych wyników, że zasób offers/listing nie zwraca wszystkich nowych ofert. Mam nadzieję jednak, że moje wnioski są błędne i istnieje jakiś sposób aby otrzymać prawidłowe wyniki

Na koniec pytanie pomocnicze:
Jak należy odwołać się do "nowego" zasobu offers/listing aby otrzymać takie wyniki jak w usuwanej starej metodzie doGetItemsList ?

pozdrawiam,
Adam.

**Comment by gslpro** [comment]
offers/listing sortowane po -startTime zwróci Ci najpierw wszystkie aukcje promowane, a dopiero później zwykłe. Dodaj do tego limit na 6000 wyników w wyszukiwaniu i pewnie nawet nie dotarłeś do "regularnych" ofert. Czyli zwróciło Ci tylko nowe promowane.

**Comment by MartaNowaczyk** [comment]
Jest tak jak pisze gslpro - zwracamy tylko do 6000 wyników, tak jak wyświetlamy to na froncie, a to duża kategoria, dlatego wyniki mogą się różnić. Jedyna możliwość to zawężenie wyników wyszukiwania.

**Comment by atmdevnet** [comment]
rozumiem, że w zasobie offers/listing odbywa się __niejawne__ sortowanie po rodzaju oferty (promoted | regular) a dopiero po tym uwzględniane jest kryterium wywołującego dotyczące sortowania. Myślę, że warto by ujawnić ten mechanizm w dokumentacji ponieważ otrzymywane wyniki diametralnie różnią się w takiej sytuacji od oczekiwanych, zdefiniowanych w zapytaniu (jak w powyższym poście), gdzie nie ma nic na temat rodzaju oferty. Uniknęli byśmy też frustracji tracąc czas na poszukiwanie przyczyny a zdaje się, że to api jest dla nas użytkowników, nieprawdaż?

**Comment by MartaNowaczyk** [comment]
@atmdevnet Wyszukiwanie przez API ma odzwierciedlać działanie frontu, a więc zwracamy dane tak samo jak przy wyszukiwaniu ofert w allegro. Zastanowimy się nad dodaniem takiej informacji w poradniku/dokumentacji.

**Comment by atmdevnet** [comment]
Dziękuję za wyjaśnienie i liczę na to, że tego typu wskazówki znajdą się w dokumentacji nie tylko w dyskutowanym przypadku ponieważ to co dla Was twórców być może jest oczywiste, to dla nas użytkowników już niekoniecznie.

**Comment by rafalkrupinski** [comment]
Pozwolę sobie podłączyć się pod temat.

https://api.allegro.pl/offers/listing?category.id=46088&sort=%2BstartTime
https://api.allegro.pl/offers/listing?category.id=46088&sort=+startTime
https://api.allegro.pl/offers/listing?category.id=46088&sort=startTime

Trudno mi zweryfikować czy oferty są rzeczywiście posortowane, bo te nie zawierają daty wystawienia, ale klucz sort wygląda zawsze tak samo:

```json
  "sort": [
    {
      "value": "-relevance",
      "name": "trafność",
      "order": "największa",
      "selected": true
    },
...
    {
      "value": "-startTime",
      "name": "czas dodania",
      "order": "najnowsze",
      "selected": false
    }
  ]
```

**Comment by MartaNowaczyk** [comment]
@rafalkrupinski to co napisałeś można różnie interpretować. Napisz jakie dokładnie jest twoje pytanie i w czym jest problem?

**Comment by rafalkrupinski** [comment]
@MartaNowaczyk Miałem problem bo nie działał parametr sort=+startTime ale już się zorientowałem, że to nie jest prawidłowa wartość. Tak na prawdę potrzebuję -startTime, więc wszystko OK.
Było by super gdyby API zwracało błąd dla niedozwolonej wartości. Pozdrawiam

**Comment by michcio19923** [comment]
Czy jest możliwość w REST filtrowania po stanie jak to miało miejsce w SOAP (parametr "condition")?

**Comment by MartaNowaczyk** [comment]
Tak, po wysłaniu zapytania otrzymasz wszystkie dostępne w danych kategoriach filtry i na ich podstawie możesz rozbudować swoje zapytanie. Jest tam również parametr stan.

**Comment by michcio19923** [comment]
Jak bez filtrowania po parametrze 'stan' można określić stan oferty?

https://paste.ofcode.org/Td6KEq257wbCEBa9MkJ3Wg

**Comment by michcio19923** [comment]
"popularity": 0    -- popularność oferty. W przypadku oferty typu BUY_NOW jest to liczba zakupów od  unikalnych użytkowników z ostatnich 30 dni.

Czy jest możliwość uzyskania liczby wszystkich zakupów na danej ofercie nawet jeśli miały one miejsce więcej niż 30 dni temu?

**Comment by MartaNowaczyk** [comment]
@michcio19923 
ad. 1. Nie widzisz tego parametru. Jeśli skorzystasz z filtrów dodatkowych np. zrobisz wyszukiwanie dla danej kategorii, na końcu dostaniesz dodatkowe filtry, z których możesz skorzystać. Tam też dostaniesz filtr ze stanem przedmiotu. 
ad. 2 Nie ma możliwości uzyskania wszystkich zakupów od początku trwania oferty (jeśli trwa więcej niż 30 dni)

**Comment by michcio19923** [comment]
searchMode - wartość "CLOSED" wyszukuje w tytułach zakończonych a jest opcja żeby w tytułach i opisach tak jak dla aktualnych jest wartość "DESCRIPTIONS"

**Comment by PawelTaberski** [comment]
Nie ma możliwości zastosowania 2 takich sortowań jednocześnie. W zakończonych ofertach możesz wyszukiwać tylko po tytule.

**Comment by michcio19923** [comment]
ad. 1. Ale filtry są dla kategorii. Czemu nie ma parametru ze stanem dla każdej oferty, w wersji SOAP był

**Comment by PawelTaberski** [comment]
Ta metoda odwzorowuje możliwości wyszukiwarki na froncie i ma takie same możliwości.

**Comment by michcio19923** [comment]
Wyszukałem oferty dla frazy 'Ikony Biliński'. REST API zwróciło 28 wyników, na allegro wyszukałem ręcznie i wyświetla 10 wyników

/offers/listing?offset=0&searchMode=DESCRIPTIONS&limit=100&phrase=Ikony%20Bili%C5%84ski
https://paste.ofcode.org/JQmUxkEPb2RfQdsvYChQfP

**Comment by PawelTaberski** [comment]
Sprawdziłem na froncie również zwraca 28 ofert.
Aby szukać w opisach ofert kliknij na froncie tutaj:
![image](https://user-images.githubusercontent.com/36262735/55551067-27141e80-56da-11e9-8b5f-3861474d1494.png)
