### ISSUE TITLE
Kiedy pole Sygnatura będzie widoczne przy wystawianiu w sandboxie?

### ISSUE THREAD

**Issue by mokumek** [allegro/allegro-api#1314]
Jak w tytule - pole to nie pojawia się w formularzu wystawiania oferty w środowisku sandbox (https://allegro.pl.sallegrosandbox.pl/offer/), na środowisku produkcyjnym oczywiście jest widoczne.

**Comment by MartaNowaczyk** [comment]
Czasem środowisko testowe różni się od produkcyjnego. Zgłoszę brak tego pola do odpowiedniego zespołu, ale nie mogę obiecać, że szybko się pojawi.

**Comment by MartaNowaczyk** [comment]
@mokumek konto na którym sprawdzasz na pewno jest kontem firmowym? Założyłam konto firma i jest sygnatura.

**Comment by mokumek** [comment]
Konto jest kontem firmowym, przesyłam poniżej status z weryfikacji - może nie jest ten status w pełni potwierdzony.
![obraz](https://user-images.githubusercontent.com/48394278/54122519-89d90980-43fd-11e9-9218-2f70d1f259a9.png)

**Comment by MartaNowaczyk** [comment]
Podaj proszę nazwę konta

**Comment by mokumek** [comment]
Konto niuniolandia

**Comment by PawelTaberski** [comment]
@mokumek Gotowe zatwierdziłem Twoje konto.

**Comment by mokumek** [comment]
Dzięki, wszystko jasne.

**Comment by marcinek1312** [comment]
prosiłbym również o zatwierdzenie konta marcinek1313

**Comment by PawelTaberski** [comment]
@marcinek1312 Gotowe, konto powinno już być w pełni aktywne.
