### ISSUE TITLE
doGetTransactionsIDs

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1315]
Czegoś nie rozumiem. Mam numer postBuyFormId, za pomocą DoGetPostBuyFormsDataForSellersRequest mogę pobrać cały postBuyFormData. Jest w nim jeden item. Tyle, że jak wpiszę ten postBuyFormItId do metody doGetTransactionsIDs, to niczego mi nie znajduje. Nie powinien zwrócić mi tego właśnie postBuyFormData?
wysłałem dwa requesty/responsy w zgłoszeniu 04872787

**Comment by lukada4100** [comment]
Chodzi oczywiście o WebApi...

**Comment by MartaNowaczyk** [comment]
Metoda zwraca jedynie identyfikatory transakcji, dla których - w ramach danej oferty - wypełnione zostały przez kupujących formularze pozakupowe - nie mogą być anulowane jak w przypadku podanej w przykładzie ofercie - zwraca tylko zapłacone i za pobraniem.

**Comment by lukada4100** [comment]
A w  jaki sposób mogę powiązać sprzedany przedmiotu z formularzem pozakupowym, który ma anulowaną płatność?

**Comment by MartaNowaczyk** [comment]
Wszystko o monitorowaniu sprzedaży znajdziesz [tutaj](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421). 

Przypominamy, że stopniowo będziemy wygaszać WebAPI o czym szeroko informowaliśmy np. na [GitHubie](https://github.com/allegro/allegro-api/issues/1043). W związku z tym zalecamy korzystanie z [REST API](https://developer.allegro.pl/about/).
