### ISSUE TITLE
PUT /sale/offers/{offerId} i odpinanie aukcji od produktu

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#1316]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Po wykonaniu zmiany na jakiejkolwiek aukcji (np. zmiany ilości sztuk) metodą PUT na zasobie /sale/offers/{offerId} aukcja jest automatycznie odpinana od "produktyzacji" (znika z aukcji zakładka "Opinie o produkcie"). Zakładam, że jest to błąd. Odpięcie aukcji od produktu powoduje, że jest on mniej widoczny dla kupującego. A to powstrzymuje nas przed przełączeniem się z zarządzaniem ofertami z WebAPI na REST API. Kiedy możemy spodziewać się naprawy?  

Pozdrawiam serdecznie

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego pełnego requesta i responsa wraz z trace-id po którym nastąpiło odpięcie oferty od produktu. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1316 na GiyHub-ie. Sprawdzimy w czym jest problem.

**Comment by tomylee0** [comment]
Przykładowy Trace-Id: 4260f3bc011e7782. Szczegóły wysłałem przez formularz kontaktowy.

Pozdrawiam

**Comment by PawelTaberski** [comment]
Czekam jeszcze na dane jakie podesłałeś, jak tylko je otrzymam i zapoznam się nimi dam znać.

**Comment by PawelTaberski** [comment]
Przekazałem sprawę do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by tomylee0** [comment]
Czekając na odpowiedź i póki co podtrzymując, że faktycznie istnieje problem z odpinaniem produktów spróbuję napisać o moich obawach co do zarządzania ofertami przez REST API dla kont których oferty są regularnie aktualizowane. 

1. Przygotowanie się do produktyzacji w postaci wpisania EAN i wartości pozostałych parametrów podczas wystawiania oferty spowoduje, że oferta będzie podpięta do produktu jedynie na pewien czas. Przy pierwszej aktualizacji (np. ilości sztuk) oferta zostanie odpięta od produktu a co za tym idzie będzie dużo mniej widoczna dla kupującego bo będzie gdzieś na końcu listy.

2. Jeszcze gorzej wygląda sytuacja z kontami które działają teraz w WebAPI i wszystkie oferty mają wystawione przez WebAPI. Przypomnę, że w WebAPI nie ma możliwości skorzystania z identyfikatora cennika dostaw i każda oferta ma swój unikalny cennik. W REST API jest odwrotnie. Zatem żeby móc aktualizować cenniki dostaw to po przełączeniu na REST API musimy ustawić delivery.shippingRates.id w każdej ofercie. Co z kolei prowadzi do natychmiastowego odpięcia oferty od produktu. W wyniku czego od razu mamy wszystkie oferty odpięte od produktów.

Podsumowując rozumiem to w ten sposób, że przejście na REST API w tym momencie może przyczynić się do spadku sprzedaży dla kont których aukcje są regularnie aktualizowane.

Pozdrawiam

**Comment by PawelTaberski** [comment]
Opinanie jest jak najbardziej problemem i pracujemy nad jego rozwiązaniem, nie będzie to tak funkcjonować, że cokolwiek zmienisz to oferta odepnie się od produktu. Poprawimy to. Zespół już namierzył powód takiego działania i pracuje nad jego rozwiązaniem. Ponadto pamiętaj, że w czerwcu wygasimy metody do zarządzania ofertami przez WebAPI więcej znajdziesz tutaj #1043

**Comment by tomylee0** [comment]
Proszę zatem o umieszczenie tutaj informacji gdy tylko poprawka zacznie działać na środowisku produkcyjnym.

Pozdrawiam

**Comment by PawelTaberski** [comment]
Oczywiście jak tylko otrzymam informacje, że poprawka została wdrożona dam znać :-)

**Comment by tomylee0** [comment]
Czy zespół zajmujący się problemem odpinania może potwierdzić, że problem został już naprawiony na środowisku produkcyjnym?

Pozdrawiam

**Comment by PawelTaberski** [comment]
Otrzymałem informacje, że zmiana została wdrożona i problem powinien być naprawiony.
