### ISSUE TITLE
Współdzielenie jednego konta a REST API

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#1317]
Cześć,

Przy autoryzacji typu device flow otrzymujemy parę token i refresh token i w danej chwili istnieje tylko jedna taka para. 
Co w przypadku, gdy chciałbym aby z jednego konta korzystało w tym samym momencie więcej niż jedna osoba/maszyna, a nie chcę generować i dystrybuować  tej pary przez centralne rozwiązanie? Przewidujecie jakieś rozwiązanie na taką okoliczność?

**Comment by PawelTaberski** [comment]
W takim przypadku musiałbyś ograć po swojej stronie jakiś system zarządzania tokenami, aby je odpowiednio stosować, nie przewidujemy wdrażania jakiś dodatkowych rozwiązań w tym zakresie. Pamiętaj, że do jednej aplikacji może się podpiąć wielu userów.
Jednakże może ktoś z użytkowników napotkał już na taki problem i rozwiązał go i da Tobie znać jak to ograł.

**Comment by dol1234** [comment]
Tak myślałem, dzięki
