### ISSUE TITLE
Dodać pole o informacji co do możliwości wystawiania wariantów przy pobieraniu kategorii 

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1318]
:bulb: **Sugestia**
Dodać do responsa
 GET  /sale/categories?parent.id={categoryId}

"variantsByColorPatternAllowed": true/false    -- informacja, czy w tej kategorii można łączyć
                                                     po kolor/wzór w wielowariantowości 

Trzymam aktualne kategorii w BD. Teraz dlatego żeby dowiedić się o wielowariantowości, muszę wysylać dodatkowy request dla koznej kolejnej kategorii na GET z zasobu /sale/categories/{categoryId}..
Proponuję dodać taki zmiany, żeby można było jednym reauestem pobrać kategorii z i informację o wielowariantowości.
Pozdrawiam.

p.s. a extra-klasą byłobym dodawanie zmian w kategoriach do dziennika zdarzeń... żeby "device" nie sprawdzał cronem zmiany w kategoriach co jakis czas...

**Comment by PawelTaberski** [comment]
Rozumiem, że chciałbyś mieć dedykowany zasób którym pobierzesz kategorie w jakich jest dopuszczalne łączenie po danym parametrze np po rozmiarze, kolorze/wzorze itp?

**Comment by runaway90** [comment]
@PawelTaberski tak =)

**Comment by runaway90** [comment]
@PawelTaberski i czy można tą informację o łączenie po danym parametrze np po rozmiarze, kolorze/wzorze itp dodać w response z GET /sale/categories?parent.id={categoryId}, kiedy pobieram dzieci-kategorii od rodiców? [też by się przydało].
żeby odrazu wiedzić czy kategoria ma wielowariantowość?

**Comment by PawelTaberski** [comment]
Ale taka informacja już jest jak wywołasz leaf to dostajesz informacje po czym możesz łączysz. Zajrzyj do [naszego poradnika](https://developer.allegro.pl/multi_variant_offers/#1).

**Comment by runaway90** [comment]
@PawelTaberski rozumiem, ale tego nie ma, jak pobieram wszystkich dzieci od rodziców, GET /sale/categories?parent.id={categoryId}.
Czyli uwarzam, że też można byłoby to dodać tą informację.

![cat1](https://user-images.githubusercontent.com/20610334/54122523-8c3b6380-43fd-11e9-9b66-31977ac9a6e1.png)

**Comment by PawelTaberski** [comment]
Rozumiem, ale jak dana kategoria nie jest liściem to może mieć pod sobą wiele liści z których przy jednych łączenie po color/pattern jest możliwe, a przy jednych nie. Wtedy taka informacja będzie myląca. A w liściu jest już taka informacja:
![image](https://user-images.githubusercontent.com/36262735/54122745-32876900-43fe-11e9-840d-310df8090192.png)

**Comment by runaway90** [comment]
O, dziękuję! Niezauwarzyłem tego, przepraszam, no i nie znałazlem informacji że mogę czekać na ten parametr dla liścia.(https://developer.allegro.pl/sale tu).

**Comment by PawelTaberski** [comment]
Rozumiem do wielowariantowości stworzyliśmy [dedykowany poradnik](https://developer.allegro.pl/multi_variant_offers/).
