### ISSUE TITLE
Wykorzystując zasób "/sale/offers/{offerId} "  - dostajemy błąd 

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1319]
Wykorzystując zasób "/sale/offers/{offerId} " do modyfikowania istniejącej oferty otrzymujemy error z wiadomością "Offer id cannot be changed".

**Comment by PawelTaberski** [comment]
A pamiętasz, aby identyczne id było przy wywołaniu i w body?

**Comment by centrumelektroniki** [comment]
Odpowiedź: wg dokumentacji nie przekazujemy offerId w "Request Body" tylko w "Path Parameters" o ile dobrze zrozumiałem pytanie.

**Comment by PawelTaberski** [comment]
Chodzi mi o to, że jeśli chcesz wyedytować ofertę 1234 i pobierasz ją GET /sale/offers/1234 i przekazujesz w PUT pełne body z GET-a jakie otrzymałeś to id przy PUT powinno byc takie samo tzn. PUT /sale/offers/1234
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#similar-offer).
