### ISSUE TITLE
Kiedy nowe ID w doGetMyIncomingPayments?

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#132]
W otrzymanym emailu z Allegro można przeczytać:

> Oprócz odświeżonej szaty graficznej, powiadomienia zyskają nowy numer płatności - w przyszłości zastąpi on dotychczasowy numer płatności. Do tego czasu w powiadomieniu zobaczysz obie wersje numeru dla tej samej płatności - obecną i nową.

Chciałbym zapytać kiedy nastąpią zmiany w doGetMyIncomingPayments. Obecnie w specyfikacji jest nadal napisane: "payTransId | long", a z otrzymanego w emailu screena wynika, że będzie to string.

**Comment by KrzysztofLukanowski** [comment]
Tak jak poinformowaliśmy, sam proces wdrażania nowych powiadomień będzie przebiegał stopniowo. Na jakiekolwiek zmiany w API musisz jeszcze trochę poczekać - poinformujemy o tym ze stosownym wyprzedzeniem.
