### ISSUE TITLE
Offer parameters using offer id

### ISSUE THREAD

**Issue by kislukacs** [allegro/allegro-api#1320]
Hi,

is it possible to read all parameters of an offer (same, what I get when I am using https://developer.allegro.pl/en/listing/) using the offer ID as search variable instead of search phrase? 

Thanks!

**Comment by PawelTaberski** [comment]
In this resource you can't use offer id in request. More about this resource you will find in our [tutorial](https://developer.allegro.pl/en/listing/).

**Comment by kislukacs** [comment]
@PawelTaberski Thank you for your answer! In this case, do you have an other endpoint, where I can use offer ID to get offer parameters?

**Comment by PawelTaberski** [comment]
only in [GET sale/offers/{offerId}](https://developer.allegro.pl/en/my_offers/#2)

**Comment by kislukacs** [comment]
But this is only for offers where I am the seller, isn't it?

**Comment by PawelTaberski** [comment]
Yes, only by this resource you can get offer by it ids.

**Comment by kislukacs** [comment]
Thank you. Are you planning to create an endpoint to get offer by its id? Or if you can add a new query parameter to [GET /offers/listing](https://developer.allegro.pl/en/listing/) for offer id, it would be nice.

**Comment by PawelTaberski** [comment]
I know that we are working on new resource for public information about single offer, but I don't know when it will be ready. When we will get information we will inform.

**Comment by kislukacs** [comment]
Thank you! I am looking forward to the update.

**Comment by kislukacs** [comment]
Hi,

@PawelTaberski do you have any update about the new resource to read single offers by its id? Thanks!

**Comment by PawelTaberski** [comment]
Sorry but not yet. When we will have that information we will create dedicated news.
