### ISSUE TITLE
Problem z pobraniem listy zamówień

### ISSUE THREAD

**Issue by atomisko** [allegro/allegro-api#1321]
Tworzę skrypt, który pozwoli mi pobrać zamówienia złożone na allegro, i zapisać je do bazy po stronie "naszego" systemu płatności, Założenie jest takie, że będzie to realizowane cronem po stronie serwera:

Robiłem tak:
1. na stronie https://apps.developer.allegro.pl/new zarejestrowałem nową aplikację
wybrałem opcję:
"Aplikacja będzie działać w środowisku bez dostępu do przeglądarki albo klawiatury (np. aplikacja konsolowa albo na urządzeniu typu telewizor)"

2. następnie według https://developer.allegro.pl/auth/#DeviceFlow
wykonałem request na https://allegro.pl/auth/oauth/device z wymaganymi danymi
otrzymałem response z device_code, expires_in, user_code, verification_uri, verification_uri_complete
przeszedłem na link: verification_uri_complete
i pod linkiem:
https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje
mam powiązaną aplikację (id jest takie samo jak klient id na stronie https://apps.developer.allegro.pl/)

Teraz chciałbym pobrać złożone zamówienia.

3. pobieram token wykonując requesta na
https://allegro.pl/auth/oauth/token?grant_type=client_credentials 
z wymaganymi danymi
dostaje w odpowiedzi klucze access_token, token_type, expires_in, scope, jti

4. próbuję pobrać zamówienia requestem na 
https://api.allegro.pl/order/event-stats
lub
https://api.allegro.pl/order/events

i za każdym razem dostaje w odpowiedzi:
[code] => ERROR
[message] => An error has occurred
[details] => 
[path] => 
[userMessage] => 

Co robię źle / co pomijam że dostaję dostaję błąd?

**Kod do pkt. 3**
`    
    $client_id = 'idstring';
    $client_secret = 'secretstring';
    $clientBaseEncode = base64_encode($client_id . ':' . $client_secret);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://allegro.pl/auth/oauth/token?grant_type=client_credentials');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    $headers = array();
    $headers[] = 'Authorization: Basic ' . $clientBaseEncode;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $response = (array) json_decode($result);
    return $response['access_token'];`

**Kod do pkt. 4** 
`    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.allegro.pl/order/event-stats');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    $headers = array();
    $headers[] = 'Authorization: Bearer ' . $accessToken;
    $headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
    
    print_r($headers);
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    $response = (array) json_decode($result);
    die(print_r($response)); //i tu zawsze mam ten blad
`
Będę wdzięczny za pomoc / sugestie

Sprawdziłem jeszcze - przy wywołaniu w 4 pkt.
/order/checkout-forms
dostaje odp
```
    [error] => access_denied
    [error_description] => Access is denied

```

**Comment by PawelTaberski** [comment]
Token uzyskany na podstawie client-credentials nie ma kontekstu usera czyli możesz skorzystać tylko z publicznych zasobów. Abyś mógł pobrać dane przypisane do danego usera musisz mieć na niego token, czyli wtedy musisz przejść całe flow i user musi się uwierzytelnić i przydzielić Twojej aplikacji dostęp do swojego konta. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#userDeviceFlow).

**Comment by atomisko** [comment]
Pawle, to inaczej zapytam,
czy da się pobrać zamówienia automatycznie czy ingerencji użytkownika? skrypt sie autoryzuje pobiera zamówienia i już.
w poradniku jest info o linkach verification_uri / verification_uri_complete 
co sugeruje że user musi kliknąc w link itd. Chyba że ja coś źle rozumiem.
A ja potrzebuje podpiąć api allegro pod mechanizm, który sam co jakiś czas będzie pobierał nam zamówienia.

**Comment by PawelTaberski** [comment]
User musi tylko raz się zautoryzowac potem refreshem sobie odświeżysz token jak będziesz potrzebować i potem już user nie musi nic robić. Możesz w nieskończoność sobie odświeżać taki token, więcej na ten temat[ tutaj](https://developer.allegro.pl/auth/#refresh-token).
