### ISSUE TITLE
Historia opłat w ofercie

### ISSUE THREAD

**Issue by pijablonski** [allegro/allegro-api#1322]
Planujemy wykonanie kalkulatora rentowności aukcji porównującego opłaty Allegro z zyskiem ze sprzedaży produktu. W związku z tym pojawia się konieczność uzyskania informacji o naliczonych **W PRZESZŁOŚCI** (historia opłat):
- prowizjach od sprzedaży
- kosztach aukcji (wystawienie, promowanie itp.)

Obecne zasoby /pricing/offer-quotes oraz /pricing/fee-preview reprezentują jedynie potencjalne opłaty w przyszłości.

Czy, a jeśli tak, kiedy, planowane jest wprowadzenie zasobów umożliwiających pobranie tych informacji?

Sugestia 1:
Wprowadzenie możliwości pobrania informacji o naliczonej prowizji sprzedaży - bezpośrednio w strukturze checkoutForms.lineItems zasobu /order/checkout-forms lub poprzez nowy zasób, przyjmujący jako parametry np. lineItem.id i quantity.

Sugestia 2:
zasób /pricing/offer-quotes mógłby występować w wariancie umożliwiającym pobranie informacji również o ostatnio naliczonych, a nie tylko nadchodzących, opłatach za daną aukcję.

**Comment by PawelTaberski** [comment]
Rozumiem, że interesują cię dane jakie dotychczas możesz pobrać przy pomocy metody [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301#method-output) w WebAPI? I chciałbyś mnie taki zasób w REST API. Raczej informacja o opłatach nie bardzo pasuje do danych do zarządzania zamówieniami.
Pamiętaj, że z takich zasobów ciągle możesz korzystać dzięki metodzie [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582)

**Comment by pijablonski** [comment]
Nie do końca. Jeśli dobrze czytam dokumentację doMyBillingItem, zasób ten nie pozwala na powiązanie kosztu prowizji z zamówieniem, nie oferuje nawet daty naliczenia opłaty.

Interesuje mnie możliwość zestawienia opłat i prowizji związanych z daną aukcją w wybranym przeze mnie okresie czasu (oczywiście mogą to być ograniczone ramy, np. z ostatnich 2 miesięcy) - nawet wtedy, gdy w tym okresie wysokość lub sposób naliczania opłat uległy zmianie i kalkulator opłat oraz lista opłat nadchodzących mogą nie reprezentować poprawnie naliczonych już opłat.

Poza tym nie muszę chyba Was cytować?
> WebAPI to stare rozwiązanie, które utrzymujemy głównie z uwagi na kompatybilność wsteczną z istniejącymi aplikacjami. Nie rozwijamy go już i planujemy jego wygaszenie.

**Comment by PawelTaberski** [comment]
Jasne masz rację WebAPI powoli wygaszamy, o czym informowaliśmy m.in. tu #1043 jednakże chciałem poznać jak najdokładniej czego potrzebujesz jakich informacji, aby przekazać jak najtrafniejszą sugestię do zespołu, który pracuje nad zasobami związanymi z opłatami. 
Przekażę im Twoją sugestie jak tylko otrzymamy informacje o konkretnych planach wdrożenia takich zasobów poinformujemy o tym  w dedykowanym komunikacie.

**Comment by pijablonski** [comment]
Dzięki. Rozumiem, że na obecną chwilę nie ma takich planów i do ewentualnego pojawienia się komunikatu 
taką informację mogę przekazywać swoim klientom.

**Comment by PawelTaberski** [comment]
Obecnie nie mam takich informacji, jak tylko będziemy znali dokładne plany co do takich zasobów poinformujemy o tym w dedykowanym komunikacie.
