### ISSUE TITLE
Komunikaty błędów związane ze składnią

### ISSUE THREAD

**Issue by chryssalid** [allegro/allegro-api#1323]
:bulb: **Sugestia**

Zwrotnie dostajemy nic nie mówiące komunikaty "An error has occured." w przypadku, gdy walniemy się w konstrukcji żądania - pominiemy gdzieś jakiś poziom tablicy, wstawimy klucze tekstowe, zamiast indeksów etc. Przydałaby się wskazówka, że konstrukcja żądania jest nieprawidłowa. Przyspieszyłoby to szukanie błędów.

**Comment by PawelTaberski** [comment]
Jasne rozumiem tylko musiałbyś mi podać jakieś konkretne przykłady kiedy czego brakowało i jaki komunikat otrzymałeś, przetestuje i w razie potrzeby założę zadanie do odpowiedniego zespołu, aby to poprawili.

**Comment by chryssalid** [comment]
Przykładowo, gdy zmieniasz status i zamiast:

`{
    "publication": {
        "action": "ACTIVATE",
        "scheduledFor":"2018-03-28T12:00:00.000Z"
    },
    "offerCriteria": [
        {
            "offers":[
                {
                    "id": "7276377308"
                }
            ],
            "type": "CONTAINS_OFFERS"
        }
    ]
}`

wysyłasz

`{
    "publication": {
        "action": "ACTIVATE",
        "scheduledFor":"2018-03-28T12:00:00.000Z"
    },
    "offerCriteria": [
        {
            "offers": { "id": "7276377308"},
            "type": "CONTAINS_OFFERS"
        }
    ]
}`

**Comment by PawelTaberski** [comment]
@chryssalid Nie wysłałeś czasem 2 razy tego samego?

**Comment by chryssalid** [comment]
Nie, nic z tych rzeczy. Walnąłem się w nawiasach i dostałem, że wystąpił błąd i tyle. A czasami nie tak łatwo dojść do tego, gdzie i jakie nawiasy ;-).

**Comment by PawelTaberski** [comment]
a fakt teraz widzę :-) i jaki komunikat wtedy dostajesz, 400 czyli Wysłano niepoprawne dane JSON. A jaki uważasz za bardziej stosowny .
