### ISSUE TITLE
Pobranie draftu

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1324]
Dlaczego nie ma metody GET, która zwróciłaby dane przesłanego draftu?

**Comment by PawelTaberski** [comment]
Przetestowałem przed chwilą na produkcji i jak najbardziej pobranie drafta nawet niekompletnego działa normalnie, a jaki komunikat dostajesz i czy masz ustawione nagłówki na wersję public nie beta?

**Comment by michcio19923** [comment]
Nie widziałem w dokumentacji metody pozwalającej pobrać draft

**Comment by PawelTaberski** [comment]
Draft jak i wystawioną ofertę pobierzesz przy pomocy GET /sale/offers/{offerId}, więcej na ten temat znajdziesz m.in. w [naszym poradniku.](https://developer.allegro.pl/sale/#step-8-complete)

**Comment by pijablonski** [comment]
Zamieszanie może być też spowodowane przez parametr publication.status zasobu /sale/offers - jego wartość domyślna nie obejmuje statusu "INACTIVE" 😉
