### ISSUE TITLE
Czy lineItems zawiera unikalne id ofert w szczegółach zamówienia?

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1325]
Dzień dobry,

czy metoda https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET
w lineItems zawsze grupuje te same oferty ID pod tym samym lineItem i wyświetla łączną ilość w polu quantity?

**Comment by PawelTaberski** [comment]
Nie wiem cz dobrze rozumiem Twoje pytanie w tabeli lineItems otrzymasz informacje o przedmiotach wchodzące w skład zamówienia  są tam numery ofert cena itp. Jest to unikatowy numer takiego zamówienia. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#04).

**Comment by aktywnitu** [comment]
To rozumiem. Ale, czy zakupione przez Kupującego te same przedmioty zawsze są pogrupowane w jeden lineItem?

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem co masz na myśli te same jest on unikatowy i dotyczy danego zamówienia, czyli pod danym lineitemid będziesz miał dane unikatowe zamówienie.

**Comment by pijablonski** [comment]
W związku z obsługą zamówień mogą się nasuwać takie pytania:
1. Czy w strukturze checkoutForm.lineItems[] zasobu GET /order/checkout-forms/{id} mogą wystąpić dwa elementy zawierające to samo lineItem->offer->id? Np. jeśli klient dwa razy dodawał element z tej samej aukcji do koszyka i złożył jedno zamówienie etc.?

2. Czy dany lineItem->id powiązany jest jednoznacznie z checkoutForm->id, to znaczy nigdy nie wystąpi sytuacja, by dwa checkoutForms miały w swej strukturze elementy lineItem o tym samym id?

I od razu odpowiem z własnych obserwacji:
1. Nie, mogą wystąpić powtórzenia (znalazłem już kilka wystąpień)
2. Nie, ten sam lineItem->id może wystąpić dla wielu checkoutForms.id, chociaż będą to raczej zamówienia tego samego klienta.

Brak w 100% pewnej unikalności jest frustrujący. Czy możemy zakładać chociaż, że wewnątrz danego checkoutForm nie dostaniemy dwóch struktur lineItem o tym samym id?

**Comment by PawelTaberski** [comment]
Pisaliśmy o tym w [poradniku](https://developer.allegro.pl/orders/#02):
Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).
