### ISSUE TITLE
Błąd http 502 doQueryAllSysStatus - WebAPI Sandbox

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1326]
Występuje problem: 
 - [x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DoQueryAllSysStatusRequest xmlns="https://webapi.allegro.pl.allegrosandbox.pl/service.php"><countryId>1</countryId><webapiKey>**********</webapiKey></DoQueryAllSysStatusRequest></soap:Body></soap:Envelope>`

Witam, powyższy request na sandboxie WebAPI kończy się błędem „HTTP 502: Bad Gateway.”

Problem zaobserwowany od 8.03.2019.

Proszę o weryfikację.

**Comment by PawelTaberski** [comment]
Rzeczywiście jest jakiś problem na sandboxie sprawę już zgłosiłem do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by SebastianOzdoba** [comment]
Kiedy możemy spodziewać się poprawy?

**Comment by PawelTaberski** [comment]
Problem udało się rozwiązać i nie powinien już występować, czy dziś również miałeś problem z tą metodą?

**Comment by alekskuc** [comment]
Witam, w dalszym ciągu metoda zwraca błąd HTTP 502

INFO 2019-03-19 11:22:36
Request: 
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DoQueryAllSysStatusRequest xmlns="https://webapi.allegro.pl.allegrosandbox.pl/service.php"><countryId>1</countryId><webapiKey>*************</webapiKey></DoQueryAllSysStatusRequest></soap:Body></soap:Envelope>`

**Comment by PawelTaberski** [comment]
Wydaje mi się, że problem może być w Twoim requeście, a w takim stylu Tobie przechodzi:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoQueryAllSysStatusRequest>
         <ser:countryId>1</ser:countryId>
         <ser:webapiKey>.....</ser:webapiKey>
      </ser:DoQueryAllSysStatusRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by alekskuc** [comment]
Requesty soap są od lat u nas generowane automatycznie przy użyciu frameworka .NET w niezmienionej formie.

Od 8.03.2019 przestała działać jedna metoda i tylko na sandboxie.

Na produkcji ta metoda działa prawidłowo. Jednoznaczny wniosek jest taki, że jest problem z Waszą metodą na sandboxie.

Ta metoda nie działa:

```
/// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#doQueryAllSysStatus", RequestElementName = "DoQueryAllSysStatusRequest", RequestNamespace = "https://webapi.allegro.pl.allegrosandbox.pl/service.php", ResponseNamespace = "https://webapi.allegro.pl.allegrosandbox.pl/service.php", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("sysCountryStatus")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public SysStatusType[] doQueryAllSysStatus(int countryId, string webapiKey)
        {
            object[] results = this.Invoke("doQueryAllSysStatus", new object[] {
                        countryId,
                        webapiKey});
            return ((SysStatusType[])(results[0]));
        }
```

Natomiast ta metoda już działa prawidłowo:

```
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("#doQueryAllSysStatus", RequestElementName = "DoQueryAllSysStatusRequest", RequestNamespace = "https://webapi.allegro.pl/service.php", ResponseNamespace = "https://webapi.allegro.pl/service.php", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("sysCountryStatus")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable = false)]
        public SysStatusType[] doQueryAllSysStatus(int countryId, string webapiKey)
        {
            object[] results = this.Invoke("doQueryAllSysStatus", new object[] {
                        countryId,
                        webapiKey});
            return ((SysStatusType[])(results[0]));
        }
```

**Comment by PawelTaberski** [comment]
@alekskuc A próbowałeś może po innej sieci, albo z innej maszyny wysłać requesta. Sprawdzałem u siebie na wiele sposobów i w logach i wydaje się, że wszystko działa poprawnie.

**Comment by alekskuc** [comment]
> @alekskuc A próbowałeś może po innej sieci, albo z innej maszyny wysłać requesta. Sprawdzałem u siebie na wiele sposobów i w logach i wydaje się, że wszystko działa poprawnie.

Sprawdzane było na różnych serwerach. Aktualnie metoda zaczęła działać przed chwilą na serwerach produkcyjnych bez żadnych zmian po naszej stronie.

**Comment by SoftSolid** [comment]
Witam
Mam dziś to samo na sandbox i na produkcyjnym.

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda działa poprawnie, czy problem u Ciebie dalej występuje?

**Comment by SoftSolid** [comment]
Fatal error: Uncaught SoapFault exception: [Sender] Invalid XML in /home/users/softsolid/public_html/demo301.cs-cart.pl/app/addons/ss_allegro/func.php:332 Stack trace: #0 /home/users/softsolid/public_html/demo301.cs-cart.pl/app/addons/ss_allegro/func.php(332): SoapClient->__soapCall('doQueryAllSysSt...', Array) #1

**Comment by PawelTaberski** [comment]
Z komunikatu wynika, że możliwe iż u Ciebie jest jakiś problem z samym XML-em. Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem. W tickecie zaznacz proszę, że dane potrzebne są do zgłoszenia numer 1326 na GitHub-ie.

**Comment by SoftSolid** [comment]
Dziś nagle zaczęło działać a nic nie zmieniałem.
