### ISSUE TITLE
Ilość sprzedanych sztuk w ofercie

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#1328]
Witam,
Czy będzie dodana ilość sprzedanych sztuk w ofercie dostępne przez nowe API dla ofert nienależących do zalogowanego użytkownika? Takie dane mamy dostępne w starym API i liczę że to również zostanie przeniesione do nowego.

**Comment by PawelTaberski** [comment]
Pracujemy nad zasobem, który będzie zwracał publiczne informacje o danej ofercie, przekazałem Twoją sugestię, aby znalazły się w nim informacje o ilości sprzedanych sztuk.
Obecnie możesz skorzystać z zasobu offers/listing, gdzie otrzymasz w polu popularity informacje:
```
                    "popularity": 0                 -- popularność oferty. W przypadku oferty
                                                    typu BUY_NOW jest to liczba zakupów od 
                                                    unikalnych użytkowników z ostatnich 
                                                    30 dni. W przypadku oferty typu AUCTION 
                                                    jest to liczba użytkowników, 
                                                    którzy biorą udział w licytacji. 
```
Oczywiście wiem, że to nie są dokładnie dane o które prosisz, ale obecnie przez REST API udostępniliśmy tylko takie dane w tym zakresie dla oferty, której nie wystawiłeś.

**Comment by expondo** [comment]
Czy wiadomo kiedy ten zasób będzie dostępny? Orientacyjnie? Czy będzie to np drugi kwartał 2019 roku?

**Comment by PawelTaberski** [comment]
Jak tylko będziemy znać przybliżony termin wdrożenia takich zasobów, to poinformujemy o nim w dedykowanym komunikacie. O naszych ostatnich planach wspominaliśmy m.in. tutaj. #1043
