### ISSUE TITLE
[WebAPI] doGetSiteJournalDeals

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1329]
Chciałbym się dowiedzieć o przyszłość tej metody. 
Niejednoznaczna jest informacja na temat jej statusu `deprecated`. 
W aktualnościach jest na liście do wygaszenia od kwietnia 2019, ale w dokumentacji nie ma wzmianki o tym (w przeciwieństwie do metod modyfikujących oferty).

**Comment by PawelTaberski** [comment]
Najnowszy komunikat odnośnie planowanych metod do wygaszenia znajdziesz tutaj #1043.
Niedługo oznaczymy metody do obsługi zamówień w REST API jako public i dopiero wtedy będziemy planowali wygaszenie tych metod w WebAPI. Jednakże już dziś zasoby do obsługi zamówień w REST API są stabilne i zachęcam do ich używania. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by mindc** [comment]
Dzięki za info. Jakiś czas temu sprawdzałem zasoby REST związane z eventami ale nie dostawałem żadnych danych (pomimo braku błędów), sprawdziłem przed chwilą, wszystko wygląda już ok.
