### ISSUE TITLE
description musi być podane

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#133]
Wysyłam ofertę.
Opis podaję w parametrze fid=341. Oto struktura:
...
[
	'fid'=>341,
	'fvalueString'=>['sections'=>
			['items'=>['type'=>'IMAGE','url'=>'PHOTO_FID_16']],
			['items'=>['type'=>'TEXT','content'=>$content1]],
			['items'=>['type'=>'TEXT','content'=>$content2]],
		],
],
...
$content1,$content2 to zmienne tesktowe.
Wysyłam i otrzymuję komunikat jak w temacie.
W czym problem?

**Comment by TimothyKoval** [comment]
fvalueString powinien być w formacie JSON, nie array

**Comment by AniaMalinowska** [comment]
Informacje o tym jak wystawić ofertę zgodnie z nowymi zasadami zamieściliśmy tutaj: [Jak przygotować nowy opis (FID 341)](https://developer.allegro.pl/new_desc/#03).

**Comment by drzemik** [comment]
Bingo. Przeoczyłem w dokumentacji. Dzięki
