### ISSUE TITLE
Problem z zasobem /offers/listing?

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1330]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Problem występuje kiedy pobieram duże ilości danych.
Dajmy na to, konkurencja ma podobny asortyment do mojego i ma bardzo dużo wystawionych ofert na allegro np. kilkaset tysięcy, oczywiście w SearchMeta dostaję informację, że np:
TotalCount=345049
AvailableCount=120000
Rozumiem, że mogę przejrzeć tyle ofert, co podaje AvailableCount?
Lecz niestety mogę przejrzeć tylko połowę tej wartości czyli 60000 ofert, powyżej dostaję błąd 422.

**Comment by PawelTaberski** [comment]
W serwisie wyświetlamy maksymalnie 6000. Liczba 6000 to availableCount. Na pewno nie pomyliła się Tobie ilość zer? Więcej na temat tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by Gerston** [comment]
To prawda, wyświetlacie 6000, ale jeśli ustawi się w filtrze idAllegro, zawęzi się do kategorii o którą nam chodzi, to wyniki są dużo większe! Widzę, że sami nie wiecie co robicie.
Poniżej zamieszczam zrzut z ekranu: 
TotalCount, AvailableCount i rozmiar pobranej listy ofert.

![image](https://user-images.githubusercontent.com/44425976/54207279-2bce2400-44da-11e9-95cd-ea82cc144e4c.png)

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego requesta i responsa sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1330 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Dzięki za przesłanie danych rzeczywiście jest jakiś problem sprawę przekazałem do zespołu, który pracuje nad tym zasobem.
