### ISSUE TITLE
Co się faktycznie zmieni 18 marca ?? Podajecie nieprawdę...

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1331]
W komunikacie z 15 lutego została przedstawiona tabela z listą zmian, które mają dotyczyć dwóch metod WebAPI, z czego jedna z tych metod i tak zostanie za chwilę wyłączona (od 1 kwietnia). Ale pytanie jest inne - kiedy i gdzie do tej pory, w polu 'itStandardizedDescription', podawane były niby dane zamknięte w dodatkowej formule <![CDATA[ ... ]]> ?? Podajecie (w kolumnie "Przed zmianą"), że bywało raz tak a innym razem inaczej - to gdzie i kiedy było to podawane w <![CDATA[ ... ]]> ???

**Comment by FromAnyHole** [comment]
W komunikacie z 15 lutego została przedstawiona tabela z listą zmian, które mają dotyczyć dwóch metod WebAPI, z czego jedna z tych metod i tak zostanie za chwilę wyłączona (od 1 kwietnia). Ale pytanie jest inne - kiedy i gdzie do tej pory, w polu 'itStandardizedDescription', podawane były niby dane zamknięte w dodatkowej formule [ CDATA [ ... ]] ?? Podajecie (w kolumnie "Przed zmianą"), że bywało raz tak a innym razem inaczej - to gdzie i kiedy było to podawane w [ CDATA [ ... ]] ???

**Comment by PawelTaberski** [comment]
Rozumiem, że chodzi Tobie o komunikat #1202 ? Przed zmianą 'itStandardizedDescription' nie zawsze był prezentowany jako sekcja CDATA teraz już zawsze będzie to prezentowane w jednolitej formie.

**Comment by FromAnyHole** [comment]
@PawelTaberski - to proszę o przykład - gdzie i kiedy był używany sub-węzeł [CDATA] w wypluwanych kopertach XML, bo sobie nie mogę przypomnieć jakoś...  ALE NIE BYŁ !!

**Comment by PawelTaberski** [comment]
Zwracaliśmy 'itStandardizedDescription' jako sekcja CDATA wtedy , gdy było to konieczne. Obecnie, tak jak pisałem ujednolicimy sposób zwracania tych danych.

**Comment by FromAnyHole** [comment]
@PawelTaberski - NIE PRAWDA !!
Nigdzie nie było do tej pory podawania danych w dodatkowym 'sub-node' typu [CDATA].
Zmiana dopiero wejdzie - proszę więc o jakiś konkretny RESPONS z dzisiaj, nie mieszajcie !!

**Comment by PawelTaberski** [comment]
Respons z dziś metoda DoShowItemInfoExt Date | Wed, 13 Mar 2019 09:42:02 GMT oferta 7634911064:
`<ns1:itStandardizedDescription><![CDATA[{"sections":[{"items":[{"type":"IMAGE","url":"PHOTO_FID_347"}]},{"items":[{"type":"IMAGE","url":"PHOTO_FID_16"},{"type":"TEXT","content":"&lt...............`

**Comment by FromAnyHole** [comment]
@PawelTaberski - ta sama metoda, na miliony zapytań - nigdy nie odpowiedziała w ten sposób. Nie było o tym słowa w dokumentacji WebAPI, więc nie wiem skąd nagle takie odpowiedzi z innym enkodowaniem tego pola - to przecież zasadnicza różnica w obsłudze tego pola i całej metody !!

**Comment by PawelTaberski** [comment]
Z tego powodu zdecydowaliśmy się na ujednolicenie, ze względu na rozbieżne wyniki. Zmiana spowodowana m.in. już całkowitym przejściem na nowy opis.

**Comment by FromAnyHole** [comment]
Czyli robiliście sobie "po cichu" to i tamto, dopuszczona była po drodze wersja wysyłki treści nowego opisu w znaczniku [CDATA] - bez encjowania zawartości, no i bez żadnego komunikatu w tej sprawie...
Kolejnym razem piszcie jak jest, a nie jak niewielu mogło tylko wiedzieć, że niby jest.

**Comment by FromAnyHole** [comment]
@PawelTaberski - jest piątek, no i nadal jest fura niejasności, co się więc zmieni w poniedziałek ???
W podanym przez Pana przykładzie mamy NADAL encjowanie treści nowego opisu:
'{"type":"TEXT","content":"&lt;p...'
w komunikacie o zmianie podane zostało, że będzie tak:
'{"type":"TEXT","content":"<p...'
a ten przedmiot odpowiada jednak ciągle tak:
'{"type":"TEXT","content":"&amp;lt;p...'

Pytam ponownie: NA CZYM STOIMY ?? CO SIĘ ZMIENI W PONIEDZIAŁEK ???

**Comment by FromAnyHole** [comment]
@PawelTaberski - jest piątek, no i nadal jest fura niejasności, co się więc zmieni w poniedziałek ???
W podanym przez Pana przykładzie mamy NADAL encjowanie treści nowego opisu:
'{"type":"TEXT","content":"& l t ; p ...'
w komunikacie o zmianie podane zostało, że będzie tak:
'{"type":"TEXT","content":"< p ...'
a ten przedmiot odpowiada jednak ciągle tak:
'{"type":"TEXT","content":"& a m p ; l t ; p ...'
(spacje powyżej są zamierzone)

Pytam ponownie: NA CZYM STOIMY ?? CO SIĘ ZMIENI W PONIEDZIAŁEK ???

**Comment by PawelTaberski** [comment]
Odpowiedź znajdziesz w wątku #1202
