### ISSUE TITLE
API Key -> Client ID / klucz WebAPI

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#1332]
Witam,
Na koncie pachnij_pl przestał mi działać klucz WEB API. Zmieniłem na Client ID / klucz WebAPI
 ze strony https://apps.developer.allegro.pl/ ale nadal mam komunikat "Nieprawidłowy kod dostępowy".
Co mam zrobić żeby odzyskać dostęp do webapi?

**Comment by mareklemur** [comment]
Teraz na koncie Lemur_24 też przestał działać.

**Comment by PawelTaberski** [comment]
Widzę, że do tego konta przypisany jest tylko jeden klucz już w nowym formacie. Co to znaczy, że klucz przestał działać? Otrzymałeś jakiś błąd i usunąłeś klucz z listy?

**Comment by mareklemur** [comment]
Błąd w mojej aplikacji, błędnie obliczałem ważność tokenu. Nie było tematu.
