### ISSUE TITLE
UWAGA! Od 31.03 nie będziesz już mógł wystawić ogłoszenia przez Allegro WebAPI.

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#1333]
Taka informacja z datą **07.03.2019r.** widnieje na tej stronie: https://developer.allegro.pl/news/

Jak to się ma do informacji z **09.01.2019r.**:
**3 czerwca 2019** usuniemy metody do obsługi i zarządzania ofertami, które już dziś oznaczamy jako deprecated.

To jest skrócenie czasu na przepisanie kodu o 3 miesiące!

**Comment by PawelTaberski** [comment]
Zmiana o której piszemy dosyć dokładnie tutaj #1303 dotyczy tylko ogłoszeń nie dotyczy kup teraz ani licytacji. I jest spowodowana innym flow wystawiania, a dokładnie pakietami. Więcej na ten temat znajdziesz we wcześniej wspomnianym komunikacie.
