### ISSUE TITLE
Pakiety

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1334]
Hej!
Czy moglibyście wytłumaczyć dokładniej (albo odesłać do jakiegoś źródła) o co chodzi z tymi pakietami?
POST /sale/offer-classifieds-packages/{offer-id}

Załóżmy że nie chcę w żaden sposób dodatkowo promować żadnej z moich aukcji. Czy w takiej sytuacji muszę:
1. Pobrać pakiet typu BASE dla danej kategorii
2. Wysłać draft do serwisu
3. Wysłać wybrany pakiet do serwisu
4. Opublikować ofertę

Czy to się zgadza? Jeśli tak, to według mnie, jest tu kilka requestów za dużo. Czy nie możecie automatycznie przypisywać bazowego, bezpłatnego pakietu do każdej aukcji?
Co z aukcjami które już są w serwisie? Czy te z automatu dostaną bezpłatny, podstawowy pakiet?

**Comment by PawelTaberski** [comment]
Całą instrukcję jak wystawić ogłoszenie znajdziesz [tutaj](https://developer.allegro.pl/advertisement/), linkujemy do niej m.in. z komunikatu #1303 .
W skrócie nie musisz korzystać oczywiście z dodatkowych promowań, możesz skorzystać z samego pakietu podstawowego, który przypisujesz do drafta przed jego opublikowaniem.

**Comment by jakubmaguza** [comment]
Tak, to widziałem, tak jak napisałem wyżej. Pytania są dwa:
1. Czy możecie automatycznie przypisać bezpłatny, podstawowy pakiet do aukcji, jeśli ja nie przypiszę żadnego? Zakładam, że to będzie ponad 90% przypadków w całym serwisie, więc zaoszczędzicie bardzo dużo wywołań.
2. Co z aukcjami które już są w serwisie? Czy te z automatu dostaną bezpłatny, podstawowy pakiet?

**Comment by PawelTaberski** [comment]
1/ Nie opublikujesz ogłoszenia bez przypisania chociażby bazowego pakietu;
2/ Planujemy migrację istniejących ofert na pakiety

**Comment by krzysztofpawlik** [comment]
Co zrobić gdy GET /sale/classifieds-packages zwraca zawsze:
`{"packages":[]}`
próbowałem zarówno głównych kategorii jak i najniższych.

**Comment by jakubmaguza** [comment]
Okej, jeszcze raz..
Rozumiem to co piszesz. Rozumiem że nie opublikuję. Pytam czy nie możecie tego zmienić, skoro zdecydowana większość ofert będzie ze standardowym cennikiem. Taka sugestia, żeby oszczędzić baaaaaaaardzo dużo mocy obliczeniowej.

**Comment by PawelTaberski** [comment]
Zmiana dotyczy tylko ogłoszeń nie ofert i oczywiście mamy świadomość że migracja istniejących ogłoszeń zajmie trochę zasobów

**Comment by jakubmaguza** [comment]
Aha, to zmienia postać rzeczy :) Dziękuję za odpowiedź. Nie chodziło mi o migrację, tylko o to, że przy wystawianiu nowych ogłoszeń, jeśli nie doda się ręcznie bazowego pakietu, żeby został przypisany automatycznie.

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem Twoją sugestię.
