### ISSUE TITLE
RestAPI - pole sold - zakończenie i wznowienie oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1335]
Załóżmy mam sobie ofertę gdzie było 3 oferty kupna, po jakimś czasie zakańczam ofertę np. w celu zmiany tytułu po czym ją wznawiam, czy nadal pole "sold" przy pobieraniu ofert będzie zwracać dla tej danej oferty wartość 3 ?

**Comment by PawelTaberski** [comment]
Powiedz mi tylko o jakiej metodzie mówisz, obecnie w REST API nie ma zakończenia oferty jest jej wstrzymanie (oczywiście możesz jej nie wznowić i uznać taką ofertę za zakończenie). Po wznowieniu przy ofercie liczba sprzedanych nie powinna ulec zmianie, chyba, że chodzi Tobie o pole popularity to jest ono liczone z ostatnich 30 dni także maleje wraz z czasem w którym oferta nie jest aktywna.

**Comment by pietrach** [comment]
A jeśli ustawię w polu publication.status = END to jest to wstrzymanie czy zakończenie ? Bo rozumiem, że teraz to END oznacza wstrzymanie a zakończenie jest wtedy jeśli po wstrzymaniu mija 60 dni i nic się z ofertą dalej nie dzieje ? To wtedy ona znika i trzeba nową utworzyć pod nowym id ?

**Comment by PawelTaberski** [comment]
Tak, bo oferta trafia wtedy do archiwum. Ale do tego momentu jest cały czas wstrzymana i możesz ją w dowolnym momencie aktywować. Przed aktywacją warto sprawdzić, czy masz uzupełnione wszystkie wymagane pola, bo w międzyczasie mogą się pojawić jakieś nowe wymagane parametry. Również nie aktywujesz oferty ze stockiem zerowym wtedy też pamiętaj go wcześniej uzupełnić.
