### ISSUE TITLE
prowizja

### ISSUE THREAD

**Issue by webdachu** [allegro/allegro-api#1336]
cześć
nie mogę znaleźć w dokumentacji, ani nigdzie uzyskać odpowiedzi odnośnie zwrotu prowizji w **Rest API**:
czy jest możliwość w Rest API  uzyskanie listy prowizji do zwrotu, + z jakiego konta są zamówienia ?

widze, że w WebApi coś jest :
https://allegro.pl/webapi/documentation.php/theme/id,341

dzięki za pomoc
Pozdrawiam

**Comment by PawelTaberski** [comment]
Jeszcze nie ma takiej funkcjonalności w REST API, pracujemy nad tym aby uzupełnić braki, informacje o naszych ostatnich planach znajdziesz tutaj #1043 
Pamiętaj, że dzięki metodzie [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582) ciągle możesz korzystać ze starych metod.

**Comment by webdachu** [comment]
ok dzięki

> Jeszcze nie ma takiej funkcjonalności w REST API, pracujemy nad tym aby uzupełnić braki, informacje o naszych ostatnich planach znajdziesz tutaj #1043
> Pamiętaj, że dzięki metodzie [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582) ciągle możesz korzystać ze starych metod.

**Comment by webdachu** [comment]
a kiedy można spodziewać się tych prowizji, jest jakiś przybliżony termin ? mniej więcej oczywiście :)

**Comment by PawelTaberski** [comment]
Obecnie nie znam przybliżonego terminu jak tylko będziemy mieli takie informacje, poinformujemy o tym w dedykowanym komunikacie.

**Comment by webdachu** [comment]
czy już coś wiadomo w tej sprawie ? :)

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [naszym harmonogramem](https://developer.allegro.pl/schedule/) zasób powinien zostać udostępniony w pierwszym kwartale 2020.
