### ISSUE TITLE
doGetMySellItemsAsync

### ISSUE THREAD

**Issue by mltr1** [allegro/allegro-api#1338]
Dzień dobry,

używając webservice metody: doGetMySellItemsAsync

przy sprawdzaniu aktywności oferty, przykładowo:

5719159556

pytam:

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">

  <s:Header>

    <Action s:mustUnderstand="1" xmlns="http://schemas.microsoft.com/ws/2005/05/addressing/none">#doGetMySellItems</Action>

  </s:Header>

  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <DoGetMySellItemsRequest xmlns="https://webapi.allegro.pl/service.php">

      <sessionId>4b70a0cbd4de6e239d764a414c2c95cb1e407e98846f2f//03_1</sessionId>

      <categoryId>0</categoryId>

      <itemIds>

        <item>5719159556</item>

      </itemIds>

      <pageSize>0</pageSize>

      <pageNumber>0</pageNumber>

   </DoGetMySellItemsRequest>

  </s:Body>

</s:Envelope>

otrzymuję:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">

  <s:Header xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" />

  <SOAP-ENV:Body>

    <ns1:doGetMySellItemsResponse>

      <ns1:sellItemsCounter>0</ns1:sellItemsCounter>

      <ns1:sellItemsList />

    </ns1:doGetMySellItemsResponse>

  </SOAP-ENV:Body>

</SOAP-ENV:Envelope>

mimo, że oferta jest aktywna. Kolejna odpytanie może dać już inny wynik, dlaczego tak jest i jak się przed tym można bronić? Generuje to powstawanie zdublowanych ofert.

pozdrawiam

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem z tą metoda. pamiętaj że zawsze w tym zakresie możesz skorzystać z nowych zasobów w REST API, więcej na en temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).
