### ISSUE TITLE
Od 26 marca zaczniemy maskować e-maile w całej korespondencji prowadzonej w ramach Allegro

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1339]
Do pracowników Allegro.
Poproszę o informację jak maskowanie emaili klientów wpłynie na restapi?
Na "Zjednoczonych sprzedawcach" zaczął się ciekawy wątek "Od 26 marca zaczniemy maskować e-maile w całej korespondencji prowadzonej w ramach Allegro".

**Comment by PawelTaberski** [comment]
Jak tylko będziemy mieli informacje w jaki sposób dokładnie ta zmiana wpłynie na API Allegro poinformujemy o tym w dedykowanym komunikacie.

**Comment by kfijalko** [comment]
Panie Pawle,
Padło też stwierdzenie, że adresy mailowe będą generowane dynamicznie dla transakcji a nie dla klientów. To brzmi trochę strasznie ;)
Pamiętajcie, żeby dać dużo czasu na dostosowanie bo 26 jest całkiem blisko.

**Comment by PawelTaberski** [comment]
Oczywiście jak tylko otrzymam informacje jak zmiana wpłynie na API poinformuję o tym.

**Comment by PawelTaberski** [comment]
Właśnie otrzymałem potwierdzenie i opublikowałem dedykowany komunikat #1340

**Comment by neldh** [comment]
Trochę mało informacji w tamtym wątku. Mamy nadzieje na szybkie doprecyzowanie.

**Comment by PawelTaberski** [comment]
Jakbyś miał jakieś pytania/wątpliwości to zadawaj proszę w tamtym wątku postaram się doprecyzować.
