### ISSUE TITLE
[REST API] problem z tokenem

### ISSUE THREAD

**Issue by MarosR** [allegro/allegro-api#134]
Pobieram sobie token według opisu na Waszej stronie, a następnie próbuję pobrać warunki oferty.
Wedle przykładu ze strony https://developer.allegro.pl/new_desc/#02
Oto kawałek kodu jaki wykonuje:
`$headers = [
      "Accept: application/vnd.allegro.public.v1+json;charset=UTF-8",
      "Content-Type: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer [wymoderowano]",
      "Api-Key: [wymoderowano]",
      "Accept-Language: PL"
    ];`
   ` $curl = curl_init("https://api.allegro.pl/after-sales-service-conditions/implied-warranties?sellerId=48169096");`
  
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    $html = curl_exec($curl);
    echo $html;`

Odpowiedź jaką dostaję:
`{
    "error": "invalid_token",
    "error_description": "Cannot convert access token to JSON"
}`

Co powinienem zrobić aby metoda zwróciła wynik?
Czy ktoś byłby w stanie pomóc?

**Comment by SoftSolid** [comment]
Witam
Spróbuj usunąć kropkę z końca tokena.
Pozdrawiam
Robert.

**Comment by MarosR** [comment]
Dziękuję. Pomogło.

Pozdrawiam

**Comment by pmielcza** [comment]
Mam podobny problem - kod:
```
$userID='4719211'; //wymyślony
$uri='https://api.allegro.pl/users/{'.$userID.'}/ratings-summary';
$headers = [
      'Accept: application/vnd.allegro.public.v1+json;charset=UTF-8',
      'Content-Type: application/vnd.allegro.public.v1+json',
      'Authorization: Bearer ['.$tokenA.']',
	  'Accept-Language: PL'
];

$curl = curl_init($uri);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
   
$wynik = curl_exec($curl);
$status = curl_getinfo($curl,CURLINFO_HTTP_CODE);
```

wynik daje 1
status daje 400 - czyli Wysłano niepoprawne dane JSON

Token nie ma kropki na końcu.

Token otrzymuję z klasy podawanej w przykładach
$auth = new AllegroOAuth2Client();

**Comment by TimothyKoval** [comment]
Poważnie? Wywal klamrowe nawiasy z URL-a

**Comment by pmielcza** [comment]
teraz mam:
`{"error":"invalid_token","errorDescription":"Cannot convert access token to JSON"}`
kurcze ale token wydaje się poprawny

**Comment by TimothyKoval** [comment]
Poważnie? Wywal kwadratowe nawiasy z header-a

**Comment by pmielcza** [comment]
JESTEŚ WIELKI !!! taki bzdet a 2h poszło :-)
A nie wiesz czy na "swoim" tokenie wyciągnę opinie i komentarze innego Allegrowicza ?
Mam konto Allegro (kolegi) i chcę wyciągnąć z niego opinię i zapisać do bazy MySQL aby później wykorzystać na stronie www.

**Comment by TimothyKoval** [comment]
Kiedy umarł Twój ostatni niewolnik?

Spróbuj to się dowiesz, jak będziesz we wszystkim liczyć na pomoc innych to do niczego nie dojdziesz...

**Comment by pmielcza** [comment]
403 Forbidden: Użytkownik jest uwierzytelniony, ale nie ma praw do danego zasobu.

Czyli się nie da z mojego poziomu... ale i tak wielkie dzięki.
Nigdzie nie doczytałem bo najlepiej jak by była możliwość na moim tokenie,
podaje np. login i hasło w nagłówku usera i wtedy mam dostęp ... było by prościej.

**Comment by maxprihodko8** [comment]
I have the same problem and don't understand the solution. Here is my code: 

```
        $headers = [
            "Accept: application/vnd.allegro.public.v1+json;charset=UTF-8",
            "Content-Type: application/vnd.allegro.public.v1+json",
            'Authorization: Bearer eyJhbQw.......',
            "Api-Key: dde....",
            "Accept-Language: PL"
        ];
        $curl = curl_init("https://api.allegro.pl/after-sales-service-conditions/implied-warranties?sellerId=12313424");
        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        $html = curl_exec($curl);
        echo $html;
        die();
```
The result is 
`{"error":"invalid_token","errorDescription":"Cannot convert access token to JSON"}1`

Could you tell me where is the problem? 
Also why there is a need to make some functions only work on old api, some only on new and make old api dependant on new?

**Comment by pmielcza** [comment]
OK, wszystko przeszedłem ale teraz stoję nad dość banalnym i dla mnie upierdliwym problemem.
Mianowicie mam kod (końcówka):

```
....
$headers = ['Accept: application/vnd.allegro.public.v1+json;charset=UTF-8',
'Content-Type: application/vnd.allegro.public.v1+json',
'Authorization: Bearer '.$tokenA.'', 'Accept-Language: PL'
];
$curl = curl_init($uri);  
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

wynik = curl_exec($curl);
$wynik = json_encode($wynik, true);

print_r($wynik); 
```

i na ekran dostaje tylko TRUE. Czemu nie ma tutaj tablicy. 
Podczas wykonywania "wynik = curl_exec($curl);" na ekran dostaje poprany wynik:
{"ratings":[{"id":"5b58267810188f002c3c568c","createdAt":"2018-07-25T09:27:52.824","recommended":true,"buyer":{"id":"15880525","login":"allehity-polsan"},"comment":"Krzesło świetne. Szybka wysyłka.","rates":{"delivery":5,"description":5,"service":5,"........ itd.

**Comment by pmielcza** [comment]
wydaje mi się że coś mam z tymi opcjami nie tak:

`curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);`

jak dodałem curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
to tera w wyniki po zdekodowaniu mam:

`"{\"ratings\":[{\"id\":\"5b58267810188f002c3c568c\",\"createdAt\":\"2018-07-25T09:27:52.824\",\"recommended\":true,\"buyer\":{\"id\":\"15880525\",\"login\":\"allehity-polsan\"},\"comment\":\"Krzes\u0142o \u015bwietne. Szybka wysy\u0142ka.\",\"rates\":{\"delivery\":5,\"description\":5,\"s ......`

**Comment by maxprihodko8** [comment]
PMielcza, could you give the full request code?

**Comment by LukaszKorek** [comment]
Abyśmy mogli w pełni zweryfikować zgłoszenie podeślij proszę pełne curle z request i response , za pomocą formularza https://allegro.pl/pomoc/kontakt

**Comment by xemix** [comment]
@LukaszKorek - w jaki sposób mogę się skontaktować? W podanej zakładce nie widzę formularza kontaktowego (albo jest schowany gdzieś głęboko :) Mam podobny problem, w metodzie _order/events_:

```
...
$headers = [
    'Content-Type: application/vnd.allegro.beta.v1+json',
    'Authorization: Bearer '.$this->accountSession->access_token,
    'Accept: application/vnd.allegro.beta.v1+json',
];

$ch = curl_init($this->restApiBase.$endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$response = curl_exec($ch);
curl_close($ch);
...
```

Otrzymuję:
```
object(stdClass)#11 (2) {
  ["error"]=>
  string(13) "invalid_token"
  ["error_description"]=>
  string(35) "Cannot convert access token to JSON"
}
```

To całość kodu odpowiedzialnego za połączenie z zasobem.

**Comment by jackoslash** [comment]
Mam dokładnie taki sam problem - udało się to może rozwiązać? Próba wywołania metod typu /sale/categories działa (testuję na sandboxie), ale już metody takie jak /order/events zwraca dokładnie taki sam błąd. Czy jest na to jakieś uniwersalne rozwiązanie? Czy ta metoda na sandboxie działa poprawnie?

**Comment by jackoslash** [comment]
Możecie pomóc? Podobny problem:

$headers = array(
            "Authorization: Bearer $token",
            "Content-Type: application/vnd.allegro.beta.v1+json",
            "Accept: application/vnd.allegro.beta.v1_json;charset=UTF-8"
);

$curl = curl_init($url);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($curl);

W odpowiedzi: 

{"errors":[{"code":"NotAcceptableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

Dane z curla:

* TCP_NODELAY set
--
  | * Connected to api.allegro.pl (5.134.213.11) port 443 (#0)
  | * ALPN, offering http/1.1
  | * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
  | * successfully set certificate verify locations:
  | *   CAfile: /etc/ssl/certs/ca-certificates.crt
  | CApath: /etc/ssl/certs
  | * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
  | * ALPN, server accepted to use http/1.1
  | * Server certificate:
  | *  subject: C=PL; L=Poznan; O=Allegro.pl sp. z o.o.; OU=IT; CN=api.allegro.pl
  | *  start date: Jan 24 00:00:00 2018 GMT
  | *  expire date: Jan 29 12:00:00 2020 GMT
  | *  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
  | *  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
  | *  SSL certificate verify ok.
  | > GET /order/event-stats HTTP/1.1
  | Host: api.allegro.pl
  | Authorization: Bearer XXXXXXXXX
  | Content-Type: application/vnd.allegro.beta.v1+json
  | Accept: application/vnd.allegro.beta.v1_json;charset=UTF-8
  |  
  | < HTTP/1.1 406 Not Acceptable
  | < Trace-Id: 3bc8921ec4ce1077
  | < Content-Type: application/json; charset=utf-8
  | < Content-Length: 193
  | < Date: Wed, 23 Jan 2019 17:22:03 GMT
  | <
  | * Curl_http_done: called premature == 0
  | * Connection #0 to host api.allegro.pl left intact

Chciałem uderzyć przez kontakt na stronie allegro, ale nie ma tam odpowiedniej kategorii do problemów z api. Inne metody takie jak /sale/delivery-methods działają i zwracają dane.

**Comment by SoftSolid** [comment]
Jaką metodę wywołujesz ? Czy ta metoda jest na pewno w wersji beta ?

**Comment by jackoslash** [comment]
Dobra, już wiem. 
Miałem błąd w | Accept: application/vnd.allegro.beta.**v1_json**;charset=UTF-8

**Comment by Kobietakoala** [comment]
Witam mam problem z wysyłaniem zapytania postmanem:

> curl -X POST \
  https://api.allegro.pl/sale/disputes/642ddf76-2b41-4f80-a7b6-2181a5648e03/messages \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: Bearer token' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Postman-Token: d24311e8-412d-49b2-af45-7fdc94e06a70' \
  -H 'cache-control: no-cache' \
  -d '{
"text": "Odpowiedz",
"type": "REGULAR" 
}'

i otrzymuje taki response

> {
    "error": "invalid_token",
    "error_description": "Cannot convert access token to JSON"
}

ktos cos?

**Comment by AssAssIn1909** [comment]
-H 'Authorization: Bearer token' pod słowe "token" masz "token" czy twój token dostępowy?
Taka pierwsza myśl mnie naszła

**Comment by Kobietakoala** [comment]
token dostępowy :P

**Comment by MartaNowaczyk** [comment]
@Kobietakoala czy na pewno nie masz w tokenie dodatkowych znaków?

**Comment by Kobietakoala** [comment]
na pewno nie mam, metody get działają

**Comment by MartaNowaczyk** [comment]
w takim razie podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełne cURL-e z requestem i responsem z dopiskiem GitHub #134 dla GET i POST

**Comment by Kobietakoala** [comment]
Po zmianie pogody, nagle zaczęło działać. Powód: nieznany. Klikałam "send" w postmanie cały dzień, zmieniając wysyłane dane z application/json na text i w drugą strone.  Magic

**Comment by MartaNowaczyk** [comment]
Wiosennie i magicznie aż miło :) Pozdrawiam i zamykam.
