### ISSUE TITLE
Problem z DoGetItemsInfo

### ISSUE THREAD

**Issue by pap7tomek** [allegro/allegro-api#1341]
Występuje problem:
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

`<?xml version="1.0" encoding="utf-8"?>
    <SOAP-ENV:Envelope
        xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:main="https://webapi.allegro.pl.allegrosandbox.pl/service.php"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <SOAP-ENV:Body>
            <main:DoGetItemsInfoRequest>
                <main:sessionHandle>xxxxxxxxxxx</main:sessionHandle>
                <main:itemsIdArray>
                <main:item>111111111</main:item>
                </main:itemsIdArray>
            </main:DoGetItemsInfoRequest>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>`
nie działa a wcześniej (miesiąc temu działało). Czy to moja wina?

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda działa poprawnie, a jaką odpowiedź dostajesz, na pewno masz ważny identyfikator sesji?

**Comment by pap7tomek** [comment]
`{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/services/service.php",
            "userMessage": null
        }
    ]
}`
identyfikator jest ważny bo jeżeli nie jest ważny to wychodzi inny błąd,
nadal nie działa

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta i responsa w formacie XML przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1341 na GitHub-ie. Sprawdzimy w czym jest problem.

**Comment by pap7tomek** [comment]
Wystąpił błąd. Pracujemy nad jego rozwiązaniem. Odczekaj chwilę i spróbuj ponownie. W międzyczasie możesz też poszukać rozwiązania w Artykułach pomocy.
formularz wam też nie działa
![postman](https://user-images.githubusercontent.com/31967746/54364284-dbd39680-466c-11e9-835e-813f9ed68039.png)
to screen z postmana

**Comment by PawelTaberski** [comment]
Nie bardzo Ciebie rozumiem link do formularza Tobie nie działa?
Sprawdziłem na Twoim requeście podmieniłem tylko identyfikator sesji i odpowiedź pojawiła się poprawnie. Czy problem jest przy każdym wywołaniu, czy tylko na co którymś?
Podeślij proszę ClientID klucza z jakiego korzystasz na testówce.

**Comment by pap7tomek** [comment]
![Nowy obraz mapy bitowej](https://user-images.githubusercontent.com/31967746/54375652-c026bb00-4681-11e9-9ef6-0225c00e36f8.png)
nie działa formularz
ClientID: d82d9998dde24061b8731cc2a0f4ee5f

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest problem z formularzem sprawę zgłosiłem

**Comment by pap7tomek** [comment]
a udało się coś ustalić czemu nie działa mi DoGetItemsInfo?

**Comment by PawelTaberski** [comment]
Testowałem na wiele sposobów i nie udało mi się powtórzyć Twojego błędu, a próbowałeś po innej sieci?
Ponadto tak, jak pytałem wcześniej:
Czy problem jest przy każdym wywołaniu, czy tylko na co którymś?
Do weryfikacji potrzebowałbym jeszcze Twoje ClientID i IP z jakiego korzystasz.
Skorzystaj z [tego formularza](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) i podeślij te dane. Zaznacz, że są potrzebne do ticketa numer 1341 na GitHub-ie.

**Comment by pap7tomek** [comment]
nic nie zmieniałem i zaczęło działać
