### ISSUE TITLE
Czy i kiedy udostępnicie zasób o kosztach związanych z korzystaniem z Allegro 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1342]
Chodzi mi ogólnie o poniesione koszty, tzn koszty wystawień, koszty utrzymania stałych ofert, koszty promowań itp.

**Comment by PawelTaberski** [comment]
Już jakiś czas udostępniliśmy zasób dzięki któremu możesz sprawdzić takie koszty, więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/charges/).

**Comment by yncki** [comment]
Nie o to mi chodziło, gdzie znajdziemy doMyBilling skoro mamy się przesiadać na nowe API  ?

**Comment by PawelTaberski** [comment]
Tej metody jeszcze nie ma w REST API, pracujemy nad uzupełnieniem brakujących metod.
