### ISSUE TITLE
Czy KATEGORII i PARAMETRY mogą się zmianiać?

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1343]
@PawelTaberski @MartaNowaczyk Dzień dobry! Potrzebuję następnej informacji.

Czy KATEGORII i PARAMETRY mogą się zmianiać? (Naprzykład nazwa, Allegro ID, parent-category, słownik i tp.)Jerzeli tak, jak często?(codzień, cotyd.,comiesiąc)

Może jest jakiś zasob żeby to uwidzieć(np. dzięnnik zdarzeń lub coś innego)?
p.s. rozumiem że nowi kategorii i parametry dodajecie "chaotycznie"? lub też jest jakiś grafik(co 2 wtorek i tp)?

**Comment by PawelTaberski** [comment]
Oczywiście takie zmiany są wcześniej planowane, na temat tych zmian informacje znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).

**Comment by runaway90** [comment]
@PawelTaberski dziękuję! 
I coś nie ma tam informacji co do kategorij. może gdzieś jest?

a o której + - aktualizujecie parametry.

**Comment by PawelTaberski** [comment]
Parametry są odświeżane w nocy i zazwyczaj dodatkowo raz dziennie, ale o różnych godzinach zazwyczaj w południe. Odnośnie kategorii powinieneś aktualizować swoje drzewo najlepiej w nocy.

**Comment by runaway90** [comment]
@PawelTaberski Dziękuję!
ostatnie pytanko z tego tematu... czy planowali zmiany typu zdarzenie aktualizacji kategorij/parametrów dodawać w dziennik zdarzeń? Może coś podobnego będzie w przyszłości?

**Comment by PawelTaberski** [comment]
Obecnie nie mamy nic takiego w planach.
