### ISSUE TITLE
[Sandbox] Brak kategorii Kody i doładowania

### ISSUE THREAD

**Issue by docc46** [allegro/allegro-api#1344]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry, przy wystawianiu oferty na sandboxie zauważyłem, że tutejsze kategorie nie odzwierciedlają drzewa kategorii z produkcji: [Kultura i rozrywka -> Kody i doładowania] nie ma swojego odpowiednika na sandboxie.

Brak tej kategorii w formularzu wystawiania jak i pod https://allegro.pl.allegrosandbox.pl/dzial/kody-i-doladowania

Edit: Jest taka kategoria w formularzu wystawiania ale w starej wersji: jako kategoria główna i z innymi podkategoriami. Jeśli dobrze pamiętam zmieniali to Państwo w zeszłym roku.

**Comment by PawelTaberski** [comment]
Środowisko testowe jest odrębne od produkcyjnego i jego drzewo kategorii jak i parametry mogą się różnić od tych na produkcji.

**Comment by AssAssIn1909** [comment]
Te nie "mogą się różnić" tylko BARDZO się różnią.

**Comment by PawelTaberski** [comment]
Parametry i kategorie nie są na bieżąco aktualizowane na środowisku testowym, także mogą występować w niektórych kategoriach duże różnice.
