### ISSUE TITLE
RestAPI - błąd poczas próby aktualizacji oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1345]
Wystąpiły dzisiaj poniższe błędy. Aukcje są już zakończone od dłuższego czasu. W czym problem ?

```
7825669791 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"4d938a9262968177"}

7825629619 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"d5fbb4a00907b04f"}

7811967813 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"25b9b7c41bf4c397"}

7811951135 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"8828a20a47440ce0"}

7811943988 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"7ce99d1479a657a"}

7811891940 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"f9e4d7176d609534"}

7782877886 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"dcc68a6799cad9f4"}

7782877239 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"87b0be5c2d7776e9"}

7782559489 => {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mo\u017ce zosta\u0107\u00a0wznowiona, poniewa\u017c jest w trakcie ko\u0144czenia. Poczekaj chwil\u0119 i spr\u00f3buj ponownie."}],"http_code":422,"trace_id":"7003b8fd5341bdb2"}
```

**Comment by PawelTaberski** [comment]
Czy te oferty były wcześnie wystawione w serwisie, czy cały czas miałeś je jako drafty?

**Comment by pietrach** [comment]
Te oferty były wystawione wcześniej przez stare API. A wczoraj wszystkie oferty z konta aktualizowałem pod względem external.id. I te powyższe tylko nie przeszły.

**Comment by PawelTaberski** [comment]
Dziwnie to wygląda nie mogę wyszukać Twoich ofert, jeszcze się tylko upewnię problem występuje na środowisku produkcyjnym nie testowym?

**Comment by pietrach** [comment]
Na produkcyjnym. Nigdy nic nie robiłem na testowym

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem sprawę do zbadania do zespołu, który odpowiada za te zasoby, proszę o cierpliwość.

**Comment by pietrach** [comment]
Te błędy się powtarzają notorycznie np. teraz

**oferta: 7831305568**
`{"code":"VALIDATION_ERROR","message":"ERR_ITEM_CAN_NOT_BE_RENEW","details":"","path":"","userMessage":"Oferta nie mou017ce zostau0107u00a0wznowiona, poniewau017c jest w trakcie kou0144czenia. Poczekaj chwilu0119 i spru00f3buj ponownie."}]`
**trace ID: 375710e97486a272**

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem te dane do zespołu, który bada ten przypadek.

**Comment by pietrach** [comment]
Kolejny błąd jaki znalazłem. Oferta 7684369130. Zwraca pole sold = 0 po czym przy próbie aktualizacji tytułu krzyczy błędem, że nie można zmieniać nazwy oferty jeśli ktoś zakupił towar

`[{"code":"VALIDATION_ERROR","message":"You cannot modify the name  for offer with bids.","details":"","path":"","userMessage":"Nie  mou017cesz zmieniu0107 nazwy, gdy su0105 juu017c oferty kupna."}]`

trace ID: 76bf56ab5a9b4b89

**Comment by PawelTaberski** [comment]
Widzę, że było na tej ofercie kupno już co prawda dosyć dawno bo ostatnie 30 grudnia, a jaka metoda zwraca Tobie sold 0. Przy reszcie też była sprzedaż w styczniu.
Także metoda reaguje poprawnie, tylko w jakiej dostajesz zwrotkę z sold=0.

**Comment by pietrach** [comment]
W meotdzie do pobierania listy ofert GET /sale/offers

**Comment by pietrach** [comment]
Po czym w takim razie mam rozpoznać że byłą oferta kupna ?

**Comment by pietrach** [comment]
Interesuje mnie metoda GET /sale/offers jak i GET /sale/offers/<offerId>

**Comment by pietrach** [comment]
Poprawienie błędu z sold to w tej chwili kluczowa rzecz. Bez tego słabo bo nie jestem w stanie zapanować nad zmianami w aukcjach z ofertami kupna

**Comment by PawelTaberski** [comment]
Ta metoda zwraca ilość sprzedanych ofert z ostatnich 30 dni. Także nie zwraca sprzedaży od początku. Jest to odzwierciedlenie moich ofert na froncie.

**Comment by pietrach** [comment]
To w jaki sposób ja mam badać możliwość aktualizacji tytułu, kategorii itp. w ofertach ?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiego zasobu, który zwracałby taką informację przez REST API o sprzedaży od początku trwania oferty. Zgłosiłem to jako sugestię do odpowiedniego zespołu. Jeśli wdrożymy taką informacje poinformujemy o tym w dedykowanym komunikacie.

**Comment by anih** [comment]
I jak wygląda kwestia zasobu do sprawdzania czy była sprzedaż żeby można zmienić lub nie tytuł?

**Comment by PawelTaberski** [comment]
Sugestię przekazałem i jak tylko wdrożymy taki zasób na pewno poinformujemy o tym w dedykowanym komunikacie.
