### ISSUE TITLE
REST-API offers-listing

### ISSUE THREAD

**Issue by ronek22** [allegro/allegro-api#1346]
Cześć,

Próbuje wyszkukiwać produkty po danej kategorii.
Moim celem jest przejrzenie wszystkich produktów w danej kategorii.
Domylslnie wyswietla sie 60 ofert. Limit maksymalnie z tego co zauwazyłem daję się ustawić na 100. Rozumiem, aby otrzymać wszystkie oferty muszę zapuścić pętle z offsetem i limitem. Tylko teraz takie pytanie mogę w prosty sposób otrzymać liczbę aktualnych ofert dla danej kategorii, zeby ustawic limity dla pętli?

**Comment by jakubmaguza** [comment]
W searchMeta masz te informacje. Maksymalnie pobierzesz 6000 ofert.

**Comment by PawelTaberski** [comment]
Dokładnie tak więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by ronek22** [comment]
Czyli mimo, że ofert jest 28647, to mogę uzyskać dostęp tylko do 6000, bo offsetu większego nie mogę ustawić, tak? W takim razie chyba tylko istnieje przegladanie po podkategoriach, w ktorych mam mniej ofert niz 6000 i pozniej to skleic w calosc

**Comment by PawelTaberski** [comment]
Metoda GET /offers/listing  odzwierciedla wyszukiwarkę na froncie, gdzie również maksymalnie sprawdzisz 100 stron z czego na każdej jest 60 ofert, mimo iż pokazujemy że ofert spełniających Twoje zapytanie jest np 800 tys.

**Comment by jakubmaguza** [comment]
Albo filtr po cenie ;)
