### ISSUE TITLE
Wprowadzenie na białą listę adresu IP

### ISSUE THREAD

**Issue by Magdalenanieckula1** [allegro/allegro-api#1347]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ x] inny

:beetle: **Opis**

 Dzień dobry,
Jesteśmy na etapie wdrażania rozwiązania u jednego z Naszych klientów, dużego e-commercu z tysiącem punktów w całej Polsce na pewnym etapie testowania pojawił się problem w postaci limitu zapytań. Tysiąc punktów będzie korzystało z jednego rozwiązania (sklepu) za jego pomocą będzie wystawiało u Państwa produkty jest to jednak ten sam adres IP. Czy jest szansza abyście Państwo dodali IP tego klienta na białą listę by nie narzucać limitu zapytań?
Pozdrawiam,
Magdalena Nieckula

**Comment by PawelTaberski** [comment]
Prosiłbym, o kontakt w tej sprawie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/dla-sprzedajacych). W zgłoszeniu prosiłbym o informacje: 

- na jakim adresie, bądź adresach IP Państwo działają;
- z jakiego klucza, bądź kluczy korzysta aplikacja;
- czy aplikacja korzysta z obu środowisk WebAPI i REST API;
- nazwę aplikacji, i jeśli jest to adres strony internetowej opisującej zakres jej działania.

W zgłoszeniu proszę zaznaczyć, że dane potrzebne są do ticketa numer 1347 na GitHub-ie.

**Comment by Magdalenanieckula1** [comment]
Dzień dobry,
Czy mógłby mi Pan podpowiedzieć w którym dokładnie miejscu znajduje się ów formularz? Niestety nie mogę go zlokalizować.

**Comment by Magdalenanieckula1** [comment]
Już zlokalizowany:)

**Comment by MagdalenaNieckula** [comment]
Dzień dobry,
Czy  możemy powrócić do tematu wprowadzenia na białą listę? Czy ponownie  muszę kontaktować się przez formularz?

**Comment by MagdalenaNieckula** [comment]
Wysłała niezbędne informacje w formuarzu

**Comment by PawelTaberski** [comment]
@MagdalenaNieckula dziękuję, zapoznamy się z informacjami i odpowiemy.
