### ISSUE TITLE
Get the value of parameter "stan" (even item in offers/listing)

### ISSUE THREAD

**Issue by jkdw** [allegro/allegro-api#1348]
Hi!
Is it possible to get the value of `parameter.11323` (stan) in RestAPI for each item in `offers/listing` answer?
Thanks.

**Comment by PawelTaberski** [comment]
By this resource not, because this resource reflects the capabilities of the search engine through the front, more about this you will find in our [tutorial](https://developer.allegro.pl/en/listing/.)
