### ISSUE TITLE
RestAPI: Filter by numer katalogowy części, numery katalogowe zamienników, faktura

### ISSUE THREAD

**Issue by jkdw** [allegro/allegro-api#1349]
Is it possible or will be possible in future to get data (maybe filter) by these parameters?
- Numer katalogowy części
- Numery katalogowe zamienników
- Faktura
I could not find this information in tutorial, so I had to ask.
Thanks!

**Comment by PawelTaberski** [comment]
We're working on extensive capabilities of "compatibilityList".Pracujemy nad zasobami, aby uzyskać publiczne informacje o ofercie innego sprzedawcy, ale nie wiem, kiedy to wdrożymy. When we will have information about that we will inform about it.
