### ISSUE TITLE
Zmiana ceny z jednoczesną zmianą czasu dostawy

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#135]
Witam ,

Chcąc zmienić cenę i czas wysyłkidostaję odpowiedź "ERR_YOU_CANT_CHANGE_ITEM_EDIT_IN_PROGRESS"

Zmieniam cene za pomocą restapi, następnie za pomocą webapi zmieniam czas wysyłki.
Jak obejść ten problem? Czy restapi udostepnia już zasób, który umożliwia zmianę więcej fidów, w tym przypadku czasu wysyłki?

Ewentualnie jaki założyć "bezpieczny" czas po którym zmieni się cena po restapi i bedę mógł zmienić czas po webapi?

**Comment by LukaszKorek** [comment]
Dzień dobry. Błąd ERR_YOU_CANT_CHANGE_ITEM_EDIT_IN_PROGRESS' zwracamy dopóki poprzednie zlecenie zmiany nie zostanie do końca przetworzone. Zmiany powinny przetworzyć się do 60 minut.

**Comment by martacronic** [comment]
Jeśli korzystasz w WebApi z metody [doChangeItemFields](https://allegro.pl/webapi/documentation.php/show/id,922) to możesz przy jednym wywołaniu zmienić fid od ceny i fidy od kosztów wysyłki. Niestety gdy zmieniam w ten sposób aukcje, to często pojawia się błąd "Error fetch header".

**Comment by dlis2010** [comment]
Niestety w ten sposób nie zmienisz ceny na aukcji która juz ma zakup

**Comment by DINK74** [comment]
ten problem występuje nawet w MS :-) workaround jest taki, żeby NAJPIERW zmieniać coś po WebAPI a dopiero POTEM po REST :-) w MS działa, w skrypcie jeszcze nie próbowałem.

**Comment by dlis2010** [comment]
niestety, próbował i tak i tak - bez znaczenia kolejność i tak kończy się na: "ERR_YOU_CANT_CHANGE_ITEM_EDIT_IN_PROGRESS"
próbowałem zrobić pauze miedzy zmianami, ale to jak gra w ruletke, do tego ta informacja:

>  Zmiany powinny przetworzyć się do 60 minut.

Panowie z Allegro możemy liczyć na sensowne odpowiedzi na zadane pytania?

**Comment by LukaszKorek** [comment]
Problem rozwiążą nowe zasoby, które udostępniami. Mianowicie wczoraj oddaliśmy nowe zasoby w Allegro REST API do wystawiania i zarządzania ofertami w wersji beta: https://developer.allegro.pl/sale/ Metody w wersji beta, to zasoby w których mogą pojawić się jeszcze zmiany, ale już teraz zachęcamy abyście je przetestowali. Natomiast w wersji public w tej chwili nie mamy zasobu, który pozwoli w jedneym momencie zmienić cenę w ofercie z zakupem jak i inne opcje w ofercie za pomocą Webapi.
