### ISSUE TITLE
Get detail of seller

### ISSUE THREAD

**Issue by ronek22** [allegro/allegro-api#1350]
Mam seller.id
Istnieje jakiś endpoint dzięki, któremu otrzymam szczegółowe informacje na jego temat jak:
email, telefon, miasto?

**Comment by PawelTaberski** [comment]
Pracujemy nad zasobem do pozyskania informacji na podstawie id usera w REST API. Obecnie możesz takie informacje pobrać przez [WebAPI](https://allegro.pl/webapi/documentation.php/theme/id,64).
Aby użyć tych metod skorzystaj z [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582).
