### ISSUE TITLE
Problem z dodaniem cennik

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1351]
Witam, mam problem dodaniem cennika

`$_config = [
		'ClientId' => $row->ClientId,
		'ClientSecret' => $row->ClientSecret,
		'accessToken' => $row->accessToken
	];

	$headers = [
		'Accept: application/vnd.allegro.public.v1+json',
		'content-type: application/vnd.allegro.public.v1+json',
		'Authorization: '. $_config['accessToken']
	];
	
	$url = 'https://api.allegro.pl/sale/shipping-rates';
	
	$post = [];
	$post['name'] = 'Cennik test';
	$post['rates']['deliveryMethod']['id'] = '7203cb90-864c-4cda-bf08-dc883f0c78ad';
	$post['rates']['maxQuantityPerPackage'] = '10';
	$post['rates']['firstItemRate']['amount'] = '16.00';
	$post['rates']['firstItemRate']['currency'] = 'PLN';
	$post['rates']['nextItemRate']['amount'] = '0.00';
	$post['rates']['nextItemRate']['currency'] = 'PLN';
	$post['rates']['shippingTime']['from'] = 'PT24H';
	$post['rates']['shippingTime']['to'] = 'PT72H';

	
	$post_data = json_encode($post);
	
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $url);
	
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
	
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = ($result = curl_exec($ch)) === false ? false : json_decode($result, true);

	curl_close($ch);
	
	echo json_encode($post);
	
	echo'<pre>';
	print_r($post);
	echo'</pre>';
	
	if ($result === false){
		throw new Exception('Unrecognized error');
	}
	elseif(!empty($result->error)){
		throw new Exception($result->error . ' - ' . $result->error_description);
	}
	else{
		if($showInfo)
		{
			echo'<pre>';
			print_r($result);
			echo'</pre>';
		}
	}`

dostaje komunikat
`Array
(
    [error] => unauthorized
    [error_description] => Full authentication is required to access this resource
)`

**Comment by PawelTaberski** [comment]
A z jakiego flow autoryzacji korzystasz nie masz czasem tokena uzyskanego przy pomocy client credentials? Taki token nie ma kontekstu usera i możesz korzysta tylko z publicznych zasobów jak listing, parametry, kategorie itp. Aby zrobić jakąś akcję w imieniu usera potrzebujesz tokena na usera i musisz przejść wtedy całe flow z autoryzacją i udzieleniem zgody. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/).

**Comment by mskiba03** [comment]
tokena uzyskuje za pomoca

`$headers = [
	'Authorization: Basic '. base64_encode($_config['ClientId'] . ':' . $_config['ClientSecret'])
  ];

$url = "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=".$_GET['device_code']."";
`

loguje sie na konto, kojarze aplikacje i uzyskuje tokena

**Comment by mskiba03** [comment]
a dokladniej najpier wykonuje to

`$_config = [
	'ClientId' => 'id klienta',
	'ClientSecret' => 'secret klienta'
];



$headers = [
	'Content-Type: application/x-www-form-urlencoded',
	'Authorization: Basic '. base64_encode($_config['ClientId'] . ':' . $_config['ClientSecret'])
  ];

$ch = curl_init('https://allegro.pl/auth/oauth/device');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query([
      'client_id' => $_config['ClientId']
    ])); 

$result = ($result = curl_exec($ch)) === false ? false : json_decode($result, true);

curl_close($ch);


if ($result === false){
	throw new Exception('Unrecognized error');
}
elseif(!empty($result->error)){
	throw new Exception($result->error . ' - ' . $result->error_description);
}
else{
	//return '<pre>'.print_r($result).'</pre>';
	
	echo "<a href='".$result['verification_uri_complete']."'>".$result['verification_uri_complete']."</a><br />";
	
	echo "<a href='./token.php?device_code=".$result['device_code']."'>Pobierz token</a>";
}
`

**Comment by PawelTaberski** [comment]
Rozumiem w takim wypadku, brakuje Tobie tutaj: 
`'Authorization: '. $_config['accessToken']`
Słówka Bearer :-)

**Comment by mskiba03** [comment]
i ja tak wczesniej pomyslalem i testowalem, ale byl inny blad ktorego nie umielem zdiagnozowac. A dodatkowo w dokumentacji u Was jest autoryzacja bez Bearer ;)

Po dodaniu mam taki blad

`Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => MismatchedInputException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Unexpected error
                )

        )

)`

**Comment by mskiba03** [comment]
I jak, jest jakis pomysl czmu tak sie dzieje? Bo ja juz nie mam pomyslow.

**Comment by PawelTaberski** [comment]
A o jakim statusie masz odpowiedź?

**Comment by mskiba03** [comment]
Właściwie to nie mam statusu, result zwraca tylko ta tabele

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => MismatchedInputException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Unexpected error
                )

        )

)

**Comment by mskiba03** [comment]
Juz znalazlem problem, ale nie wiem jak go rozwiazac;)

Problem lezy w danych wysylanych

Wysylam

        $post = [];
	$post['name'] = 'Cennik test';
	$post['rates']['deliveryMethod']['id'] = '7203cb90-864c-4cda-bf08-dc883f0c78ad';
	$post['rates']['maxQuantityPerPackage'] = '10';
	$post['rates']['firstItemRate']['amount'] = '16.00';
	$post['rates']['firstItemRate']['currency'] = 'PLN';
	$post['rates']['nextItemRate']['amount'] = '0.00';
	$post['rates']['nextItemRate']['currency'] = 'PLN';
	$post['rates']['shippingTime']['from'] = 'PT24H';
	$post['rates']['shippingTime']['to'] = 'PT72H';

$post_data = json_encode($post);

w efekcie wychodzi cos takiego
{"name":"Cennik test","rates":{"deliveryMethod":{"id":"7203cb90-864c-4cda-bf08-dc883f0c78ad"},"maxQuantityPerPackage":"10","firstItemRate":{"amount":"16.00","currency":"PLN"},"nextItemRate":{"amount":"0.00","currency":"PLN"},"shippingTime":{"from":"PT24H","to":"PT72H"}}}

a musze wyslac to tak
{"name":"Cennik test","rates":[{"deliveryMethod":{"id":"7203cb90-864c-4cda-bf08-dc883f0c78ad"},"maxQuantityPerPackage":"10","firstItemRate":{"amount":"16.00","currency":"PLN"},"nextItemRate":{"amount":"0.00","currency":"PLN"},"shippingTime":{"from":"PT24H","to":"PT72H"}}]}

brakuje mi kwadratowego nawiasu po rates i na koncu ;)

Jak przekonwertowac tablice ta z gory na ta odpowiednia?

**Comment by PawelTaberski** [comment]
Czyli jednak otrzymywana przez Ciebie odp była ze statusem 400. Nie prowadzimy wsparcia w kodowaniu, ale może ktoś z reszty użytkowników forum Tobie pomoże.

**Comment by neldh** [comment]
$post['rates'] = [];

i w pętli jesli masz wiele, a jak jeden to jeden:
$rate['deliveryMethod']['id'] = '7203cb90-864c-4cda-bf08-dc883f0c78ad';
$rate['maxQuantityPerPackage'] = '10';
$rate['firstItemRate']['amount'] = '16.00';
$rate['firstItemRate']['currency'] = 'PLN';
$rate['nextItemRate']['amount'] = '0.00';
$rate['nextItemRate']['currency'] = 'PLN';
$rate['shippingTime']['from'] = 'PT24H';
$rate['shippingTime']['to'] = 'PT72H';
$port['rates'][] = $rate;

**Comment by mskiba03** [comment]
neldh Wielkie dzieki ;) Działa
PawelTaberski rowniez dziekuje za pomoc

Pozdrawiam
