### ISSUE TITLE
RestAPI - zmiana tytułu nieaktywnej oferty z ofertami kupna

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1352]
Czy można zmienić tytuł nieaktywnej oferty, na której ktoś coś kupił ? Oczywiście później ją wznowić ?

**Comment by pietrach** [comment]
I od razu kolejne pytania czy mogę zmienić kategorię oferty zakończonej po upływie 12h i ją wznowić ?

**Comment by PawelTaberski** [comment]
Nie możesz zmienić tytułu w ofercie z kupnem, i kategorii po 12h. Jest to związane m.in. z popularnością oferty. Więcej o rzeczach jakie możesz zmienić w aktywnej ofercie znajdziesz [tutaj](https://allegro.pl/webapi/faq.php#faq_7).

**Comment by pietrach** [comment]
Ja mówię o zakończonej ofercie

**Comment by PawelTaberski** [comment]
Również, bo obecnie oferta nie jest zakończona a wstrzymana możesz ją później wznowić. I w takim wypadku istniało by m.in. ryzyko nabicia popularności w danej kategorii wstrzymania oferty zmiany kategorii i tytułu i wznowienie jej.

**Comment by pietrach** [comment]
Czyli innymi słowy mogę jedynie zakończyć ofertę i wystawić nową ?

**Comment by PawelTaberski** [comment]
Musisz wystawić nową ofertę pod nowym id, ale możesz pobrać tą na której chcesz się oprzeć GET-em i zmienić co potrzebujesz tylko musisz ją wystawić pod nowym id.

**Comment by pietrach** [comment]
A co z ograniczeniami cenowymi ? Jeśli towar do 50 zł i jeśli powyżej 50zł

**Comment by PawelTaberski** [comment]
Co masz na myśli przez ograniczenia cenowe? Jeśli wstrzymasz ofertę możesz edytować cenę dowolnie przez REST API.
