### ISSUE TITLE
Błąd parsowania WSDL

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#1353]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Cześć. Czy Wasze aplikacje również mają od wczoraj problem z parsowaniem WSDLa allegro? W PHP otrzymuję taki wyjątek: "SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl/service.php?wsdl' : Premature end of data in tag definitions line 2".

Nie miałem jeszcze czasu sprawdzić dokładniej czy problem jest po mojej stronie, czy jednak nie, ale cała sprawa wydaje się dziwna, tak jakby struktura XMLa była w którymś miejscu nieprawidłowa.

**Comment by FromAnyHole** [comment]
A może... coś w związku z tym wątkiem i zmianami od poniedziaUku ?
https://github.com/allegro/allegro-api/issues/1202

**Comment by imper86** [comment]
@FromAnyHole wątpię, błędem sypie w momencie inicjowania klienta Soap (przynajmniej tyle udało mi się ustalić, ale nie jestem w pracy, więc mogę się mylić).

**Comment by PawelTaberski** [comment]
@imper86  Sprawdziłem i wsdl pobiera się normalnie a próbowałeś na innym łączu, bądź innej maszynie. Zastanawiam się jeszcze czy może nie masz ustawionych zbyt krótkich timeoutów, nikt inny nie zgłaszał tego typu problemów.

**Comment by imper86** [comment]
@PawelTaberski czy timeout 120 sekund to może być za krótki? Domyślam się, że odpowiesz, że to zależy od łącza, ale sprawa odbywa się na dedyku OVH z (teoretycznie) gwarantowanym łączu 100mbit.  Na innej maszynie i innym łączu miałem podobny błąd, ale to było 2 dni temu i zdarzyło się raz, więc tak czy inaczej szukam przyczyny u siebie.

Pytanie jeszcze jakby poza konkursem - czy Wasz wsdl często się zmienia? I czy są jakieś stałe godziny aktualizacji pliku? Być może dobrym pomysłem byłoby trzymać Wasz wsdl lokalnie i go po prostu aktualizować co jakiś czas.

**Comment by PawelTaberski** [comment]
@imper86 Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) konkretne timestampy w których zaobserwowałeś problem i na czym czy np. metoda X. Podaj również IP na jakim występuje taki problem.
Sprawdzimy to. W zgłoszeniu zaznacz, że informacje są potrzebne do ticketa numer 1353 na GitHub-ie.

**Comment by imper86** [comment]
@PawelTaberski IP wysłałem przez formularz kontaktowy. Resztę danych podaję tutaj, ze względu na to, że to żadna tajemnica.

Jeżeli chodzi o błąd, o którym napisałem to powstaje on w momencie inicjowania obiektu klienta, więc nie wiąże się on wtedy z żadną konkretną metodą. Timestampy:
2019-03-18 11:51:10
2019-03-18 11:52:39
2019-03-18 11:56:39
2019-03-18 13:17:48
2019-03-18 13:49:51
2019-03-18 14:03:14
2019-03-18 14:15:54
2019-03-18 14:51:12

Natomiast zauważyłem, że ogólnie mam sporo odpowiedzi z WebApi, które są niekompletne. Przykłady wrzuciłem tutaj https://drive.google.com/drive/folders/16eWN5tvffLaDnORNo0EXYr-OnZEfF9WW?usp=sharing

**Comment by PawelTaberski** [comment]
@imper86 Rozumiem, że podane timestampy dotyczą problemów z WSDL-em nie timeoutów na metodach jeśli dotyczą metod to jakich.

**Comment by imper86** [comment]
Zgadza się, problem dotyczy wsdla.

Problem z niekompletnymi responseami też mam, wrzucę później przykłady.

**Comment by PawelTaberski** [comment]
Nie udało mi się powtórzyć Twojego błędy, ale przekazałem sprawę do głębszej analizy, proszę o cierpliwość.

**Comment by msorys** [comment]
Tutaj tak naprawdę problem nie polega na konkretnej metodzie, a na pobierani wsd'la od Allegro

Start - Oznacza moment zaczęcia pobierania wsdla i jak widzimy w załączniku w pewnym momencie Allegro przestaje nam go zwracać i wisi. Lista błędów przy pobieraniu wsdl'a:
- Connection reset by peer
- Operation timed out 

Przykładowa komunikacja 
`2019-03-19 10:15:58 Allegro_data-03-2019: 
2019-03-19 10:15:59 Allegro_data-03-2019: ========START==========
2019-03-19 10:15:59 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:15:59
)

2019-03-19 10:15:59 Allegro_data-03-2019: ========REQUEST==========
2019-03-19 10:15:59 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:15:59
)

2019-03-19 10:15:59 Allegro_data-03-2019: 
2019-03-19 10:15:59 Allegro_data-03-2019: ========RESPONSE==========
2019-03-19 10:15:59 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:15:59
)

2019-03-19 10:15:59 Allegro_data-03-2019: 
2019-03-19 10:15:59 Allegro_data-03-2019: ========REQUEST==========
2019-03-19 10:15:59 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:15:59
)

2019-03-19 10:15:59 Allegro_data-03-2019: 
2019-03-19 10:16:01 Allegro_data-03-2019: ========RESPONSE==========
2019-03-19 10:16:01 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:16:01
)

2019-03-19 10:16:01 Allegro_data-03-2019: <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:typens="urn:AllegroWebApi" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<typens:doChangeQuantityItemResponse><item-id xsi:type="xsd:long">7863389172</item-id>
<item-info xsi:type="xsd:string">-</item-info>
<item-quantity-left xsi:type="xsd:int">16</item-quantity-left>
<item-quantity-sold xsi:type="xsd:int">0</item-quantity-sold>
</typens:doChangeQuantityItemResponse></SOAP-ENV:Body>
</SOAP-ENV:Envelope>

2019-03-19 10:16:01 Allegro_data-03-2019: ========START==========
2019-03-19 10:16:01 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:16:01
)

2019-03-19 10:16:01 Allegro_data-03-2019: ========REQUEST==========
2019-03-19 10:16:01 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:16:01
)

2019-03-19 10:16:01 Allegro_data-03-2019: 
2019-03-19 10:16:02 Allegro_data-03-2019: ========RESPONSE==========
2019-03-19 10:16:02 Allegro_data-03-2019: Array
(
    [time] => 2019-03-19 10:16:02
)
`

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem te informacje, dzięki za dokładne rozpisanie na pewno pomoże to namierzyć problem 👍

**Comment by msorys** [comment]
Czy cokolwiek wiadomo? Kiedy można spodziewać się, że problem zostanie rozwiazany?

to już 4 dni - kiedy nie możemy realizować zamówień.

**Comment by PawelTaberski** [comment]
Sprawę przekazałem do zespoły, który odpowiada za tą funkcjonalność, pracują nad zdiagnozowaniem przyczyny problemu i jej rozwiązaniem. proszę o cierpliwość.

**Comment by imper86** [comment]
@PawelTaberski po sprawdzeniu logów z serwera OVH uznało, że problem może (ale oczywiście nie musi) wynikać z uszkodzonego kabla ethernet, lub karty sieciowej. Dziś w nocy mają wymienić, dam znać czy cokolwiek się zmieniło.

**Comment by msorys** [comment]
Odnośnie powyższego mam informacje o występowaniu problemu dla użytkowników z różnych platform. 
Dodatkowo trzymałem @ info z Allegro - cytuję:

Zespół techniczny potwierdził występowanie opisanego błędu i pracuje nad jego rozwiązaniem.

**Comment by msorys** [comment]
Czy cokolwiek wiadomo? Problem od piątkowego popołudnia - mamy środę!
m.

**Comment by imper86** [comment]
@PawelTaberski @msorys kabel wymieniony, niestety sytuacja bez zmian. Potwierdzam, że mamy ten sam problem od piątkowego popołudnia, w związku z czym coraz mocniej zaczynam wierzyć w to, że jednak problem jest gdzieś po stronie allegro

**Comment by PawelTaberski** [comment]
Rozumiem ja sprawę zgłosiłem do odpowiedniego zespołu z wysokim priorytetem, najbardziej pomocne są oczywiście konkretne dane jeśli macie konkretne timestampy wraz z metodą w jakiej występuje problem to podsyłajcie. Dodatkowo przyda się IP i klucz na jakim wystąpił problem. Takie dane przesyłajcie przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Zaznaczcie w nim, że dane są potrzebne do zgłoszenia numer 1353 na GitHUb-ie.

**Comment by imper86** [comment]
@PawelTaberski podesłałem więcej danych przez formularz kontaktowy

**Comment by PawelTaberski** [comment]
Rozumiem, jak tylko je otrzymam dodam do zadania.

**Comment by msorys** [comment]
Czy będzie jakaś informacja oficjalna odnośnie występujacych problemów?

**Comment by msorys** [comment]
W dniu wczorajszym zamówienia w miarę przechodziły, niestety dzisiaj znód od 11-tej nie pobierają się zamówienia 
m.

**Comment by klejor** [comment]
Również potwierdzam istnienie problemu. Wysłałem szczegóły w formularzu kontaktowym.

**Comment by PawelTaberski** [comment]
@klejor Dzięki otrzymałem i dodałem do zadania
@msorys Powiesiłem info przed chwilą #1393
