### ISSUE TITLE
Przypisanie tagów do oferty

### ISSUE THREAD

**Issue by gemsnet** [allegro/allegro-api#1354]
Po jakim czasie od opublikowania oferty można przypisać do niej tagi za pomocą "sale/offers/{offerId}/tags"?

Najpierw próbowałem przypisać tagi do draftu. Otrzymałem komunikat zwrotny o braku oferty o podanym ID. Następnie opublikowałem ofertę i odczekałem na potwierdzenie jej aktywacji za pomocą "offer-publication-commands/{commandId}/tasks". Po odebraniu statusu SUCCESS próbowałem ponownie przypisać tagi, ale nadal pojawia się komunikat o braku oferty.

Przypisanie tagów działa, ale po dłuższym bliżej nieokreślonym czasie. Czasami po kilku minutach od opublikowania. Czy jest jakiś  sposób, aby określić, kiedy można przypisać już tagi do oferty?

ERROR 404
[message] => Offer XYZ not found
[details] => OfferNotFoundException

**Comment by FromAnyHole** [comment]
Check - Wait - Sleep - Check - Wait... ;-)

**Comment by PawelTaberski** [comment]
@gemsnet  Wykonanie każdej operacji na ofercie może zająć do godziny czasu, wszystko zależy od łącza i od ilości zadań na naszych kolejkach. Zazwyczaj jest to kwestia kilku minut, ale ten czas może się wydłużyć.

**Comment by gemsnet** [comment]
W instrukcji wystawiania aukcji na stronie:
https://developer.allegro.pl/sale/
powinna znaleźć się informacja, że dodanie tagów nie jest możliwe od razu przy tworzeniu aukcji lecz dopiero w późniejszym bliżej nieokreślonym czasie.

**Comment by PawelTaberski** [comment]
@gemsnet  Jasne dzięki za sugestię dodamy taką informację.
