### ISSUE TITLE
REST API /offers/listing bałagan ze zdjęciami

### ISSUE THREAD

**Issue by grzegorzjj** [allegro/allegro-api#1355]
Jako że offers/listing ma jakoś tam zastępować DoGetItemsList to jak wygląda sytuacja z udostępnianiem linka do zdjęć ofert z aukcji? 
W WEB Api URL do zdjęcia zwracany jest z innego miejsca ( z uwzględnieniem formatowania zdjęcia - dostępne są 3 wielkości do wyświetlenia mała/średnia/duża z zachowaniem inteligentnego resize'owania, to znaczy, jak ktoś ustawi duża, a nie ma dużego obrazka - zwracany jest największy dostępny o rozmiarach poniżej 400x300 ) niż w REST API - tu chyba zwracany jest wgrywany obrazek przez sprzedającego - bez formatowania, bez ustawiania wielkości. Próba wyświetlenia obrazka po pobraniu oferty w jakimś tool-tipie to koszmar....

Konkretnie i z przykładami:
Mamy 3 przykładowe aukcje numer:
1. 7909315982 	
2. 7909039750
3. 7908995024

WEBApi ( z dokumentacji ):
photosInfo | PhotoInfoType[]
Tablica struktur zawierająca informacje o zdjęciach w ofercie.
    photoSize | string
    Rozmiar zdjęcia: small - małe (64x48), medium - średnie (128x96), large - duże (400x300).
    photoUrl | string
    Odnośnik do zdjęcia.
    photoIsMain | boolean
    Informacja o tym czy dane zdjęcie jest głównym w ofercie (i miniaturką na listingu): true/false.

pozyskanie URL:
$zdjecie_aukcji=$A->{'itemsList'}->{'item'}[$f]->{'photosInfo'}->{'item'}[2]->{'photoUrl'};

Wybieram zawsze 2 ( jak mniemam LARGE - 400x300 )

Dostaję z tych aukcji zdjęcia
1. https://a.allegroimg.com/s400/01be9e/1e5d5a57471eb37ddefc9ee7a9d1
2. https://a.allegroimg.com/s128/032ba8/f0c4f8d645f6a744829e14c689f9
3. https://c.allegroimg.com/s64/03076d/7a2132794dd5993c6c2d19e6ea5c

A teraz REST Api ( dokumentacja - bardzo skromniutka ):
"images": [
    {
        "url": "string"
    }
],

Pozyskanie URL:
 $zdjecie_aukcji=$response['items']['regular'][$f]['images'][0]['url'];

Nie wiem, co wybrać? 
0 - jest zawsze, czasem tablica ma 2 zdjęcia, czasem 4 

Zerowe zdjęcie zwraca mi:
1. https://a.allegroimg.com/original/01be9e/1e5d5a57471eb37ddefc9ee7a9d1
2. https://a.allegroimg.com/original/032ba8/f0c4f8d645f6a744829e14c689f9
3. https://f.allegroimg.com/original/031eb0/1e37f53c4f2b8a2b27175dd3886f

ad. 1 ( tu jest tylko 1 zdjęcie )
Array ( 
[0] => Array ( [url] => https://a.allegroimg.com/original/01be9e/1e5d5a57471eb37ddefc9ee7a9d1 ) 
)
ad. 2 ( tu są 2 zdjęcia )
Array ( 
[0] => Array ( [url] => https://a.allegroimg.com/original/032ba8/f0c4f8d645f6a744829e14c689f9 ) 
[1] => Array ( [url] => https://a.allegroimg.com/original/033f4c/76a3ac404f738ab9e041df738b81 ) 
)
ad. 3 ( tu jest 5 zdjęć )
Array ( 
[0] => Array ( [url] => https://f.allegroimg.com/original/031eb0/1e37f53c4f2b8a2b27175dd3886f ) 
[1] => Array ( [url] => https://9.allegroimg.com/original/03183c/4381cf2547b188a017f4e0541ef9 ) 
[2] => Array ( [url] => https://c.allegroimg.com/original/03076d/7a2132794dd5993c6c2d19e6ea5c ) 
[3] => Array ( [url] => https://4.allegroimg.com/original/038b6a/4c3ea5e14f9fa72d002f3c4ef584 ) 
[4] => Array ( [url] => https://1.allegroimg.com/original/03d94b/9faa65724ae6914527fef4774891 ) 
)

Ponieważ to jest pytanie to:
a) Czy można zostawić w REST API formę identyczną do WEB Api - skoro to jest to wystarczy w nowe miejsce wstawić te same URL'e ( raczej nikt nie będzie narzekał bo do tej pory tak było )
b) Jeśli to niemożliwe ( bo na przykład nie ) to czy można prosić o opis, co trafia do tego responsa
c) jeśli (a) jest niewykonalne, to czy można np. zerowy respons ( ['images'][0]['url'] ) wstawiać identyczny z tym wyświetlanym na front-end'zie w wielkości tej z front-end'u ?

GrzegorzJJ

(edit: gdy się przegląda linki załączone w poście w części REST API - przeglądarka je automatycznie zmniejsza , w rzeczywistości są dużo większe i trzeba by je zmniejszać przed wyświetleniem )

**Comment by PawelTaberski** [comment]
Z tego co napisałeś rozumiem, że chciałbyś mieć możliwość pobrania zdjęć w różnej rozdzielczości, a powiedz mi tylko jeszcze do czego potrzebujesz zdjęcia o różniej rozdzielczości.

**Comment by jakubmaguza** [comment]
Use case jest pewnie prosty. Żeby wyświetlić miniaturkę zdjęcia bez potrzeby pobierania dużego i resizowania.

**Comment by grzegorzjj** [comment]
@PawelTaberski Rozwiązanie przyjęte do tej pory w WebApi mi pasuje. W aplikacji wyświetlam w tool-tipie zdjęcie z aukcji. Do tej pory było znormalizowane. Jeśli byłoby tak dalej - byłoby OK.

**Comment by grzegorzjj** [comment]
@jakubmaguza To prawda - posiedziałem i da się wymusić mniejszy rozmiar wyświetlanego obrazka bez pobierania go. Pobiera się jednak całe zdjęcie i resize wykonuje przeglądarka. Nie ma jednak info o rozmiarze zdjęcia i jak pisałem dostępne są chyba zdjęcia w postaci wrzuconej przez wystawiającego aukcję. W innym miejscu serwis ma jednak zdjęcia pozmniejszane - w trosce o pasmo lepiej je wyświetlać zamiast ściągać tłusty oryginał.

**Comment by rafalkrupinski** [comment]
Na mniejszych rozmiarach i transferach skorzystaliby zarówno użytkownicy jak i Allegro

**Comment by neldh** [comment]
Dokładnie. Już gdzieś kiedyś był poruszany temat miniaturek na tym forum.

**Comment by PawelTaberski** [comment]
Zgłosiłem sugestię dodania dedykowanego linka dla grafiki z miniaturką. Jeśli zdecydujemy się dodać takie dane, to poinformujemy o tym w dedykowanym komunikacie.
