### ISSUE TITLE
Jak otrzymać aktualny "access_token", kiedy applikacja nie ma aktualnych tokenów, ale ma uprawnienia do konta?

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1356]
@PawelTaberski Dzień dobry, Pawieł!
Mam takie pytanie:
Co robić w tej setuacji kiedy DEVICE(applikacja) z kilkoma akauntami refreszuje access token -> request idzie dobrze i normalnie dostaję nowe dane z nowym access i refresh tokenami, ale z przyczyn niezalerzych od applikacjii w procesie po pobieraniu responsa(czyli mam response) przez przypadek nie zapisuje się nowa informacja do bazy(czyli są stare tokeny). I teraz mamy sytuację kiedy nie mam aktualnych access i refresh tokenów. Jak wstawiam stary refresh token - mam error. Jak wtedy można z powrotem otrzymać access token dla takiego akkaunta?

Dziękuję z góry.

**Comment by PawelTaberski** [comment]
Można, ale user znów musi przejść całe flow i się uwierzytelnić, wtedy znów dostaniesz nową parę.

**Comment by runaway90** [comment]
Dziękuję. 
Proponuję dodać zasob pobieranie wszystkich access_tokenów dla device(applikacji). Który się przyda w podobnej sytuacji. I zo pomocą takiego zasobu urzytkownik nie musiał by jesze raz przechodzić case flow...
Pozdrawiam.

**Comment by PawelTaberski** [comment]
Rozumiem, obecnie nie mamy takiego zasobu w planach, ale zgłosiłem Pana sugestię do odpowiedniego zespołu, jeśli zdecydujemy się wdrożyć takie rozwiązanie, to poinformujemy o tym.
