### ISSUE TITLE
Oferty, którymi nie można już zarządzać, wciąż zwracane przez GET /sale/offers

### ISSUE THREAD

**Issue by pijablonski** [allegro/allegro-api#1357]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zasób GET /sale/offers zwraca w odpowiedzi niektóre oferty, których zwracać chyba nie powinien, np. ofertę zakończoną 4 (sic!) lata temu. Oczywiście nie ma możliwości edycji ani wznowienia takich ofert.

Wygląda to na błąd przetwarzania po stronie Allegro.
Lista numerów aukcji zostanie przesłana przez formularz kontaktowy.

**Comment by MartaNowaczyk** [comment]
Dziękuję za przesłane dane. Jaki status mają te oferty w otrzymanym responsie?

**Comment by pijablonski** [comment]
Wszystkie oferty mają publication.status ENDED 
Powinienem raczej napisać "miały", gdyż cztery z przesłanych ofert nie są już zwracane w GET /sale/offers

Wszystkie oferty są typu BUY_NOW, a publication.endedAt dla dziewięciu z nich wskazuje na czas ponad 60 dni wstecz (od 2018-08-07).

**Comment by MartaNowaczyk** [comment]
@pijablonski odświeżyliśmy statusy i już nie powinieneś dostawać tych ofert w responsie.
