### ISSUE TITLE
Zwiększona ilość timeoutów

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1358]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Od piątku obserwujemy więcej timeoutów np na metodach `doChangeItemFields` czy `doGetPostBuyFormsDataForSellers`, czy jest jakiś problem z wydajnością?

**Comment by MartaNowaczyk** [comment]
Na ten moment nie widać, żeby to był problem globalny. Potrzebujemy więcej informacji - możesz podać jakie dostajesz timestampy dla tych metod i jakiego klucza to dotyczy. Podeślij dane przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1358.

**Comment by mariobros6** [comment]
Ja także obserwuję w różnych usługach i na róznych kluczach problemy z wywołaniami api, zwłaszcza doGetItemsInfo. Występują od piątku.

**Comment by mariobros6** [comment]
SoapFault exception: [Client] looks like we got no XML document in 
SoapClient->__call('doGetItemsInfo', Array)

**Comment by maciej-domski** [comment]
Potwierdzam. Problem występuje głównie dla metody "doGetSiteJournalDeals", ale nie tylko. Część połączeń przechodzi normalnie, a część dostaje timeout'y. Pierwsze oznaki zaczynały się pojawiać w piątek po południu.

**Comment by MartaNowaczyk** [comment]
Dziękujemy za informacje. Staramy się ustalić co może być przyczyną.

**Comment by pietrach** [comment]
Nie tylko dla WebAPI. Problem z timeout dotyczył też RestAPI

**Comment by pietrach** [comment]
Coś złego się dzieje z RestAPI. Nic się nie da zrobić. Skrypty wiszą. Same timeouty

**Comment by MartaNowaczyk** [comment]
@pietrach czy problem nadal występuje?

**Comment by pietrach** [comment]
Narazie chyba jest ok

**Comment by anih** [comment]
Dla WebAPI problem dalej występuje, podesłałem api key i przykładowe daty wystąpienia przez formularz: `zgłoszenie numer "04940485" ref:_00D24aE05._5001o3OiB9h:ref`

**Comment by MartaNowaczyk** [comment]
@anih dzięki za dane - dla jakich metod dostałeś timeouty

**Comment by anih** [comment]
Dziś to chyba tylko `doChangeItemFields`, `doShowItemInfoExt` i `doGetPostBuyFormsDataForSellers` widziałem.

`doChangeItemFields` przykładowo 19 Mar 2019 12:35:25 +0100 i 19 Mar 2019 12:39:42 +0100

**Comment by mariobros6** [comment]
Potwierdzam, problem nadal występuje doGetItemsInfo

**Comment by MartaNowaczyk** [comment]
Cały czas zajmujemy się tematem.
