### ISSUE TITLE
brak "Przesyłki elektronicznej" jako osobny FID

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1359]
Występuje problem:
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Czy i kiedy do metod dostawy zwracanych przez WebApi zostanie dodana przesyłka elektroniczna jako osobny FID? Tak jak zostało to zrobione z odbiorami osobistymi.

**Comment by MartaNowaczyk** [comment]
W FID 35 znajdziesz przesyłkę elektroniczną

**Comment by PhotoSoft** [comment]
Czyli nie jest planowane rozbicie tej formy dostawy na 3 FIDY, czyli "pierwsza sztuka", itd.?

**Comment by MartaNowaczyk** [comment]
Nie mamy w planach takich zmian.
