### ISSUE TITLE
[SANDBOX] Przy aktywacji oferty ERROR z handlingTime

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1360]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: 
Jak aktywuję ofertę an SADNBOX, mam error 
![error_3](https://user-images.githubusercontent.com/20610334/54522629-01fb7e00-496e-11e9-8dc5-04ee5d87068d.png)

w dokumentacji 
![error_3_2](https://user-images.githubusercontent.com/20610334/54522651-0c1d7c80-496e-11e9-8e31-9165eca79b00.png)

Proszę sprawdzić.

**Comment by MasterSlynx** [comment]
W innej dokumentacji...
-- czas wysyłki, obecnie dostępne są
                                            wartości: PT0S (natychmiast), PT24H (24 godziny), 
                                            P2D (2 dni), P3D (3 dni), P4D (4 dni), P5D (5 dni), 
                                            P7D (7 dni), P10D (10 dni), P14D (14 dni), 
                                            P21D (21 dni), P30D (30 dni), P60D (60 dni).   
                                            Można również podać te wartości 
                                            w godzinach, np. PT72H (3 dni). 
                                            Niewymagane dla formatu sprzedaży 
                                            typu ADVERTISEMENT (ogłoszenie).
🙄

**Comment by runaway90** [comment]
@MasterSlynx dziękuję. 
Gdzie to opisali leppej niż w dokumentacji REST API?

**Comment by MasterSlynx** [comment]
Oni mają trochę tu trochę tam - i uważaj, bo czasami tu jest źle, a tam dobrze. Najlepiej sprawdzać obydwa
https://developer.allegro.pl/sale/#step-9-offer-publication-commands

**Comment by runaway90** [comment]
@MasterSlynx dziękuję bardzo.
