### ISSUE TITLE
 kopiowania aukcji z jednego konta na Allegro.pl na drugie

### ISSUE THREAD

**Issue by Andrey230** [allegro/allegro-api#1361]
Potrzebuje stworzyć skrypt do kopiowania aukcji z jednego konta na drugie. Jaki jest proces i jakie metody muszę użyć ?

**Comment by FromAnyHole** [comment]
No, no... Jeśli to ma działać ze wszystkim i w sposób pewny, to potrzebujesz kilku lat doświadczeń z Allegro-API i co najmniej kilkunastu metod na dwóch API na raz, powodzenia !

**Comment by jakubmaguza** [comment]
Myślę że potrzebowałbyś pobrać najpierw GUIDy zwrotów, wysyłek itp (załóżmy że masz po jednym z każdego).
Logujesz się na oba konta, żeby mieć dwa bearer tokeny.
Pobierasz wszystkie swoje oferty na koncie A.
Iterujesz przez wszystkie oferty i wystawiasz je przy użyciu danych autoryzacyjnych konta B.

Podsumowując (zakładając ze znasz GUIDy wysyłek, zwrotów itp)
1. Autentykacja
2. Get seller's offers
3. Get all fields of the particular offer
4. Create a draft offer
5. Publish offer

To tak na szybko :)

**Comment by kfijalko** [comment]
;) nie rób tego. Chyba, że to pierwsze chcesz zamknąć ;)
1) Konto 1:
a) pobierasz id warunków: zwroty, gwarancje, reklamacje
b) pobierasz id cenników i ich definicje
c) pobierasz listing ofert + zdjęcia
2) Konto 2:
a) ręcznie tworzysz warunki: zwroty, gwarancje, reklamacje
tworzysz mapowanie id warunki konto 1-> warunki konto 2
b) na podstawie pobranych definicji cenników tworzysz cenniki na koncie 2
tworzysz mapowanie id cenników konto 1 -> konto 2
c)
a. iterujesz po ofertach, wgrywasz zdjęcia, podmieniasz id warunków i cenników, tworzysz drafty, w external.id możesz wstawić id oferty z konta 1
b. jeszcze jedna iteracja aktywująca i już

zakładam, że po drodze się wyłoży, więc musisz sprawdzić które oferty z konta 1 już są na koncie 2 i w jakim statusie (tutaj z pomocą przyjdzie external.id)

to tak na szybko :)
