### ISSUE TITLE
Metoda doGetSiteJournalDeals dla wszystkich ofert w serwisie

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#1362]
Czy istnieje możliwość pobrania przez rest api albo webapi dla danej oferty podobnych informacji które zwraca metoda doGetSiteJournalDeals?

**Comment by MartaNowaczyk** [comment]
Zasoby dla zamówień:
    GET /order/events - [dziennik zdarzeń](https://developer.allegro.pl/orders/#02)
    GET /order/checkout-forms - lista zamówień
    GET /order/checkout-forms/{id}) - szczegóły zamówienia
