### ISSUE TITLE
Pobranie informacji przez /sale/offers

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1363]
Gdzie można znalezc informacje w RestApi podczas wywolywania zasobu /sale/offers/{offer_id} na temat tego jakie ma byc zachowanie oferty po 10 dniach ? Tzn w webapi podczas wystawiania podawalismy Automatyczne wznowienie oferty w sklepie : wznów z pełnym.... etc 

<img width="1095" alt="Zrzut ekranu 2019-03-19 o 00 25 36" src="https://user-images.githubusercontent.com/1530496/54570109-9bae4400-49dd-11e9-9e2c-2bf3b378f704.png">

**Comment by MartaNowaczyk** [comment]
@yncki nie ma tej opcji w REST API.

**Comment by yncki** [comment]
@MartaNowaczyk to w jaki sposób możemy się dowiedzieć czy oferta się automatycznie przedłuży czy wygaśnie ?

**Comment by MartaNowaczyk** [comment]
@yncki
Opcja 1 - to standardowa oferta w duration znajdziesz wartości P3D (3 dni); P5D (5 dni); P7D (7 dni);                                                P10D (10 dni); P20D (20 dni)lub odpowiednik godzinowy np. P72H (3 dni)
Opcja 2 - tej nie pobierzesz i nie planujemy zmian w tym zakresie
Opcja 3 - to oferta do wyczerpania przedmiotów, w duration ma wartość null

**Comment by yncki** [comment]
@MartaNowaczyk dzieki, nie rozumiem tylko 2 opcji, czy ona zniknie po prostu całkowicie ? Czy po prostu nie będzie jej obsługi przez API ? Jest to bardzo ważna informacja dla nas, może warto zakomunikować to szerzej ? 

I jeszcze jedno pytanie, rozumiem że zarówno 2 i 3 opcja pozostawia ten sam numer oferty?

**Comment by MartaNowaczyk** [comment]
@yncki jeżeli będziemy mieć konkretne plany, co do 2 opcji, to na pewno to zakomunikujemy.

Tylko opcja 3 pozostawia ten sam numer. Chyba, że przez REST API aktywujesz zakończoną ofertę, która nie przeszła jeszcze do archiwum - ta też nie zmieni numeru.

**Comment by yncki** [comment]
Ok,
ostatnie pytanie 
wynik z sale/offers niema pola duration, chodzi o endingAt? :

<img width="625" alt="Zrzut ekranu 2019-03-27 o 14 45 09" src="https://user-images.githubusercontent.com/1530496/55080780-0119c900-509f-11e9-873f-a3cf2660aec0.png">
