### ISSUE TITLE
Nie działa zmiana ceny 0.51

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1364]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
`array (
  'id' => '1ac23e52-b071-4bea-98a9-40e87f23f49c',
  'input' => 
  array (
    'buyNowPrice' => 
    array (
      'amount' => '0.51',
      'currency' => 'PLN',
    ),
  ),
)
`
**response**:
`array (
  'body' => 
  array (
    'errors' => 
    array (
      0 => 
      array (
        'code' => 'ConstraintViolationException.Price',
        'path' => 'arg4.input.buyNowPrice',
        'details' => 'Invalid value: PLN 0.51000, Annotation: @pl.allegro.offercore.service.validation.constraints.Price(message={pl.allegro.offercore.offer.price.incorrectFormat}, groups=[], payload=[])',
        'message' => 'Enter a correct price. Make sure that the specified price does not contain letters. Recommended price format: 0.00.',
        'userMessage' => 'Enter a correct price. Make sure that the specified price does not contain letters. Recommended price format: 0.00.',
      ),
    ),
  ),
  'code' => 422,
  'headers' => 
  array (
    0 => 'HTTP/1.1 422 Unprocessable Entity',
    'Date' => 'Tue, 19 Mar 2019 10:36:50 GMT',
    'Pragma' => 'no-cache',
    'Expires' => '0',
    'Trace-Id' => '2de5f5cf04c7aa9',
    'Content-Type' => 'application/json',
    'Cache-Control' => 'no-cache, no-store, max-age=0, must-revalidate',
    'Content-Length' => '544',
    'X-Frame-Options' => 'DENY',
    'X-XSS-Protection' => '1; mode=block',
    'X-RateLimit-Limit' => '9000',
    'X-RateLimit-Remaining' => '8961',
    'X-Content-Type-Options' => 'nosniff',
  ),
)`

**Comment by rtnet-pl** [comment]
Minimalna cena to 1 PLN

**Comment by MartaNowaczyk** [comment]
zgadza się

**Comment by yncki** [comment]
o rany, faktycznie :) zmylil mnie 'Enter a correct price. Make sure that the specified price does not contain letters. Recommended price format: 0.00.'

- nic się nie marnuje, komunikat błędu powinien być doprecyzowany
