### ISSUE TITLE
[SANDBOX] Jak odswierzyć token applikacji? 

### ISSUE THREAD

**Issue by runaway90** [allegro/allegro-api#1365]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją

:beetle:
Dzień dobry!
Potrzebuję pomocy, jak odswierzyć token do applikacji, jeżeli nie mam refresh tokena? 
![ref1](https://user-images.githubusercontent.com/20610334/54603752-6d644f00-4a45-11e9-9c20-e44c60eb6b41.png)

**Comment by MartaNowaczyk** [comment]
refresh_token masz tylko przy Code flow i Device flow.

**Comment by runaway90** [comment]
@MartaNowaczyk dziękuję bardzo, mam applikacje która nie potrzebuje dostęp do akkaunta z Allegro, a musi pobrać aktualne kategory i parametry do nich. jak w tedy być? co 12 godzin tworzyć nowego tokena?

**Comment by MartaNowaczyk** [comment]
@runaway90 tak, jednak nie powinien to być problem, zamiast robić refresha generujesz nowy token.
