### ISSUE TITLE
Problem z wystawianim aukcji?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1366]
Witam,
Mam problem z wystawieniem aukcji gdzie zawartość jej wygląda następująco:
{
    "name": "3M 1100 zatyczki do uszu stopery wkładki",
    "category": {
        "id": "122751"
   },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        }

    ],
"ean": "4001895874802",

    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Zatyczki 3M 1100
Praktyczne, wygodne i przede wszystkim tanie - profesjonalne stopery do uszów. Wykonane zostały z miękkiej gąbki poliuretanowej, więc świetnie przylegają do małżowiny nie tracąc przy tym nic na komforcie użytkowania. Nadaje się świetnie wszędzie tam, gdzie poziom hałasu może być groźny dla słuchu. Dla maksymalnej higieny stoperów nie powinno używać się więcej niż jeden raz. Można je stosować na stanowiskach pracy, na których poziom dźwięku A nie przekracza: 106 dB - gdy hałas zawiera silne składowe w zakresie małych, 109 dB - gdy hałas zawiera silne składowe w zakresie średnich częstotliwości, 113 dB - gdy hałas zawiera silne składowe w zakresie dużych częstotliwości - pod warunkiem prawidłowego ich stosowania. Przed zastosowaniem wkładek należy wykonać pomiary hałasu i sprawdzić czy w danych warunkach akustycznych zapewniają one właściwą ochronę narządu słuchu. Wkładki umożliwiają równoczesne używanie innego sprzętu ochronnego, np. okularów, maski.

Specyfikacja:
 Kształt stożka
 Wykonane z gąbki poliuretanowej
 Jednorazowego użytku

</p>"
                    }
                ]
            }
        ]
    },

 "images": [
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/11a611/677ce92b407c835dfc52108eaa5b"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/11147c/91cb06d1491296a7b3009d30e831"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/1140d6/b84c90034f46bf04d77cc6ba1f11"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/112bdd/b4fb9beb4ba7a8bad276fe185f12"
}
 ],

    "sellingMode": {                        
        "format": "BUY_NOW",
        "price": {
            "amount": "1.00", 
            "currency": "PLN"
        },
        "startingPrice": null,
                            
        "minimalPrice": null            
    },
    "stock": {
        "available": 1016,
        "unit": "SET"
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "97c6979f-626e-4ded-b5d8-d885c5392230"
        },
        "returnPolicy": {
            "id": "4e353ca5-b57e-4222-a16f-4dc18aa40cce"
        },
        "warranty": {
            "id": "261e4e86-c2d9-41ab-b2b3-bd8a1afa789e"
        }
    },

    "delivery": {
        "shippingRates": {
            "id": "a18dfcbc-eed0-4f6a-820d-823649ece028"
        },
        "handlingTime": "PT24H",
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null
    },
    "location": {                             
        "countryCode": "PL",
        "province": "DOLNOSLASKIE",
        "city": "Wrocław",
        "postCode": "50-541"      
    },
    "external": {          
        "id":"104937"
    },      
    "contact": {
	"id":"00a89012-a46b-43d1-a24c-35c4dfd70987"
    }
}
}

otrzymuje błąd 400  Bad Request

natomiast jak zmodyfikuje zawartość skracając opis to aukcja się wystawia bez problemu.
{
    "name": "3M 1100 zatyczki do uszu stopery wkładki",
    "category": {
        "id": "122751"
   },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        }

    ],
"ean": "4001895874802",

    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Zatyczki 3M 1100

</p>"
                    }
                ]
            }
        ]
    },

 "images": [
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/11a611/677ce92b407c835dfc52108eaa5b"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/11147c/91cb06d1491296a7b3009d30e831"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/1140d6/b84c90034f46bf04d77cc6ba1f11"
},
{
"url": "https://a.allegroimg.allegrosandbox.pl/original/112bdd/b4fb9beb4ba7a8bad276fe185f12"
}
 ],

    "sellingMode": {                        
        "format": "BUY_NOW",
        "price": {
            "amount": "1.00", 
            "currency": "PLN"
        },
        "startingPrice": null,
                            
        "minimalPrice": null            
    },
    "stock": {
        "available": 1016,
        "unit": "SET"
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "97c6979f-626e-4ded-b5d8-d885c5392230"
        },
        "returnPolicy": {
            "id": "4e353ca5-b57e-4222-a16f-4dc18aa40cce"
        },
        "warranty": {
            "id": "261e4e86-c2d9-41ab-b2b3-bd8a1afa789e"
        }
    },

    "delivery": {
        "shippingRates": {
            "id": "a18dfcbc-eed0-4f6a-820d-823649ece028"
        },
        "handlingTime": "PT24H",
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null
    },
    "location": {                             
        "countryCode": "PL",
        "province": "DOLNOSLASKIE",
        "city": "Wrocław",
        "postCode": "50-541"      
    },
    "external": {          
        "id":"104937"
    },      
    "contact": {
	"id":"00a89012-a46b-43d1-a24c-35c4dfd70987"
    }
}
}

Co może być przyczyną ?

**Comment by AleksyZajac** [comment]
Wygląda na to że "content" w sekcji description musi być w jednej linii.
"description": {
    "sections": [
        {
            "items": [
                {
                    "type": "TEXT",
                    "content":

proszę o potwierdzenie że tak musi być.

**Comment by MartaNowaczyk** [comment]
Tak, musi być w jednej lini.

**Comment by AleksyZajac** [comment]
A mogę wiedzieć czy jest to podyktowane ?

**Comment by AssAssIn1909** [comment]
Parsowanie zapytania przez system który wysyłasz. Na przykład w postamanie gdzie testuje, wstawienie "entera" z klawiatury skutkuje błędem bad request. Tak samo w aplikacji nie możesz sobie ot tak wstawić entera w stringu bo program sie nie skompiluje ( tak wiem są wyjątki ale zazwyczaj potrzebne są + w nowych liniach albo jakieś znaki przed stringiem.
W html aby mieć nową linie najlepiej to zrobić poprzez <br />, ale allegro go nie obsługuje więc trzeba używać <p>
