### ISSUE TITLE
Gdzie moge zobaczyć jak aukcja wygląda?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1367]
Witam,
w jaki sposób mogę podejrzeć jak wygląda aukcja którą wystawiłem w środowisku testowym?

Jak wrzucam INACTIV to widzę je w panelu jako szkice ale nie mogę kliknąć w nią aby zobaczyć jak będzie się finalnie prezentowała.

Jak daję ACTIV to nie pojawia się wcale w aukcjach aktywnych. Dla przykładu numer aukcji: 6206237100.

**Comment by PawelTaberski** [comment]
Ofertę możesz podejrzeć dopiero po jej publikacji metodą PUT /sale/offer-publication-commands/{commandId}
Wiecej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

**Comment by AleksyZajac** [comment]
To jeszcze może mnie oświecisz i powiesz skąd mam wytrzasnąć {commandId} ?

**Comment by PawelTaberski** [comment]
Identyfikator w formacie UUID po którym później możesz śledzić wykonanie danego zadania generujesz samodzielnie. Więcej na temat tego identyfikatora znajdziesz w [naszym poradniku](https://developer.allegro.pl/about/#ids).
