### ISSUE TITLE
zasób /offers/listing

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#1368]
:bulb: **Sugestia**

sugerowałbym umieścić stan przedmiotu w tym zasobie ponieważ jeśli nie nałożę filtru muszę odpytywać każdą aukcje z listingu i ta sama kwestia dotyczy miniatur i medium zdjęć. No chyba że o czymś nie wiem to proszę mnie oświecić. Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Po to właśnie są filtry, żeby wybrać odpowiedni stan i dostać listę ofert, która nam odpowiada. 
Jeśli chodzi o zdjęcia, to zwracamy tylko listę z oryginalnym rozmiarem zdjęć, gdzie pierwsze to miniaturka (też w oryginalnym rozmiarze). Nie planujemy na ten moment zmian w tym temacie, jednak przekażę twoją sugestię do odpowiedniego zespołu by wzięli ją pod uwagę.

**Comment by jakubmaguza** [comment]
Ja też popieram sugestię dodania stanu produktu, szczególnie że zasób ma odwzorowywać wyszukiwarkę na froncie :)

**Comment by marcinja2** [comment]
no właśnie problem się robi jak przeszukujemy kategoriami lub po frazie bo jestem zmuszony do używania filtrów, a czasem pracownicy moi wyszukują używane czasem nowe przedmioty i teraz muszę najpierw szukać frazę potem włączyć jeden filtr potem znów przeładować i dać drugi. Ustawianie najpierw filtrów a potem frazy jest nieintuicyjne i niewygodne w szczególności gdy chcesz zobaczyć obie opcje razem ale z rozróżnieniem.Aa w ogóle to niektóre przedmioty nie miały opisu stanu do niedawna (nie wiem jak jest teraz) wiec te co nie mają określonego stanu nie wyświetlają się ani w nowych ani używanych. Mam rację?

**Comment by marcinja2** [comment]
poza tym żeby pokazać miniaturkę trzeba zasysać całe duże zdjęcie np teraz na moim koncie antykwariat-lubl są wystawione drzeworyty i zdjęcie są ogromne. Wgranie miniaturek trwa kilka sekund. Rozwiązanie moim zdaniem jest nieekonomiczne i spowalniające działanie systemów. Może czegoś nie wiem a może warto to przemyśleć

**Comment by MartaNowaczyk** [comment]
ad 1) rozumiem, mogę tylko przekazać taką sugestię
ad 2) sprawa była już zgłaszana, ale nie ma jeszcze ustaleń czy zmienimy coś w przypadku pobierania miniaturek

**Comment by marcinja2** [comment]
przydałby się też catParent czyli numer kategorii nadrzędnej żeby swobodnie przełączać się między kategoriami

**Comment by MartaNowaczyk** [comment]
dodam do zgłaszanych potrzeb
