### ISSUE TITLE
offer-price-change-commands

### ISSUE THREAD

**Issue by bluesoftware** [allegro/allegro-api#1370]
Przy edycji ceny dostaje błąd

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-price-change-commands/db636be1-d79b-45c4-acae-84245984e0b8","userMessage":null}]}`

mam autoryzacje (Device flow) użytkownika z którego jest wystawiony produkt

```
PUT /sale/offer-price-change-commands/db636be1-d79b-45c4-acae-84245984e0b8 HTTP/1.1
--
  | Host: api.allegro.pl
  | Transfer-Encoding: chunked
  | Accept: application/vnd.allegro.public.v1+json
  | content-type: application/vnd.allegro.public.v1+json
  | Authorization: Bearer {}
  | Expect: 100-continue
-d {"modification":{"type":"FIXED_PRICE","price":{"amount":"78.92","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6070373699"}]}]}
```

**Comment by MartaNowaczyk** [comment]
Jaki dostałeś status?

**Comment by bluesoftware** [comment]
Dostaje taki błąd nie ma tam statusu:

> {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-price-change-commands/db636be1-d79b-45c4-acae-84245984e0b8","userMessage":null}]}

**Comment by MartaNowaczyk** [comment]
Musisz dostawać jakiś status np. 400 Bad Request

**Comment by bluesoftware** [comment]
> HTTP/1.1 400 Bad Request
> --
>   | Expires: 0
>   | Cache-Control: no-cache, no-store, max-age=0, must-revalidate
>   | X-XSS-Protection: 1; mode=block
>   | Pragma: no-cache
>   | X-Frame-Options: DENY
>   | Trace-Id: 9883440384f6342a
>   | Date: Thu, 21 Mar 2019 22:58:56 GMT
>   | X-Content-Type-Options: nosniff
>   | Transfer-Encoding: chunked
>   | Content-Type: application/json

**Comment by MartaNowaczyk** [comment]
Nie wiem jak to masz ograne pod spodem, ale może masz nieodpowiednio oznaczone body, bo błąd  świadczy o niepoprawnym kodzie JSON. U mnie twój JSON dział a(oczywiście nie z twoim id oferty). U mnie wygląda to tak:

`curl -X PUT \
  https://api.allegro.pl.allegrosandbox.pl/sale/offer-price-change-commands/db636be1-d79b-45c4-acae-84245984e0b8 \
  -H 'Authorization: Bearer {Token}' \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -d '{"modification":{"type":"FIXED_PRICE","price":{"amount":"78.92","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6070373699"}]}]}
'`

**Comment by bluesoftware** [comment]
Problem rozwiązała zmiana z:
`curl_setopt($curl, CURLOPT_PUT, true); `
na 
`curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');`

**Comment by marcinja2** [comment]
@bluesoftware a jak przekazujesz ciało -d (curl PHP) ja daję  curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($myJSON)) i mi to nie działa
