### ISSUE TITLE
Sandbox - problem z płatnościami?

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#1371]
Cześć, mam problem z płatnościami w Sandboxie - ktoś może potwierdzić?
Dokonuje symulacji płatności - na podstronie podsumowania (gdzie przekierowuje po płatności) mam status zakończona, jednak po wejściu w moje zakupy - mam status "nieopłacone".

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i nie mam problemów. Napisz przy jakiej płatności i opcji występuje problem.

**Comment by xemix** [comment]
Ok, nie wiem, być może jakiś "chwilowy" problem był, płatności przeszły i wszystko gra.
