### ISSUE TITLE
Aktywacja sprzedaży na koncie sandbox

### ISSUE THREAD

**Issue by jakub-dev271719** [allegro/allegro-api#1373]
witam, prosze o aktywacje konta "brajt-firma" na sandboxie.

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto, aby zakończyć proces prześlij dowolne dwa pliki w zakładce moje konto i daj znać to wtedy będę mógł dokończyć proces aktywacji.

**Comment by domin97** [comment]
Witam, również proszę o aktywację (nie mogę testować wystawiania aukcji z zewnętrznego sklepu), moje konto: Client:44142147

**Comment by PawelTaberski** [comment]
@domin97 Gotowe

**Comment by domin97** [comment]
@PawelTaberski  wielkie dzięki.

**Comment by jakub-dev271719** [comment]
@PawelTaberski wrzuciłem jpgi jako skan NIP i CEIDG.

**Comment by PawelTaberski** [comment]
@jakub-dev271719 Gotowe konto jest już w pełni aktywne.

**Comment by ospiotr** [comment]
Proszę o aktywację sprzedaży na koncie sandbox:
Client:44223714

Dziękuję.
