### ISSUE TITLE
[ sandbox ] nie można wywołać metody doGetItemsList

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#1375]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] inny

:beetle: **Opis**

Jeśli wywołamy metodę doGetItemsList na sandboxie to wyrzuca komunikat:

`Minutowy limit wywołań dla tego klucza WebAPI został przekroczony. Proszę spróbować później. [ERR_MINUTE_LIMIT_EXCEEDED]`

Wiem, że metoda ta zostanie usunięta 01.04 jednak potrzebujemy przetestować poprawki w porównaniu ze starym rozwiązaniem

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) klucz z jakiego korzystasz. W zgłoszeniu podaj, że dane są potrzebne do ticketa numer 1375 na GitHub-ie

**Comment by PawelTaberski** [comment]
@kormichu Gotowe powinno już być ok.
