### ISSUE TITLE
DeliveryMethods

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1379]
Czy jest jakiś sposób na powiązanie metod dostaw z WebApi i RestApi czy też jedne nie mają nic wspólnego z drugimi?

**Comment by neldh** [comment]
Trzeba sobie samemu zmapować:
   1     => '2b6ca59d-1e4c-426c-82a9-efcbd730846b',
            2     => '1fa56f79-4b6a-4821-a6f2-ca9c16d5c922',
            3     => '45309171-0415-49cd-b2cf-89e9143d20f0',
            4     => 'bc2a5eb6-921f-4c1e-ab96-3a1b747ff9f6',
            5     => '97286096-eb28-40f9-9efc-95ecbb8624ea',
            6     => '773167b1-feec-4ae9-b20f-1ed8ccb7b1ed',
            7     => 'b90c6295-b69a-4cb4-a308-7126a02aea47',
            8     => '758fcd59-fbfa-4453-ae07-4800d72c2ca5',
            9     => '7203cb90-864c-4cda-bf08-dc883f0c78ad',
            10    => 'a6e4845b-9ace-48ea-b232-918eaf11ba6c',
            11    => '845efe05-0c96-47c3-a8cb-aa4699c158ce',
            12    => 'd1aa489b-baf3-4f9d-a96e-2c4e497dc7e5',
            13    => '57b987de-ce2d-4e73-9b9f-a7c9ebe9611d',
            16    => '9081532b-5ad3-467d-80bc-9252982e9dd8',
            17    => '98f86f81-0018-41c5-ac83-073a56fc7021',
            18    => '85c3ad2f-4ec1-446c-866e-63473ed10e26',
            19    => '98f86f81-0018-41c5-ac83-073a56fc7021',
            21    => 'f7e952b5-9ae8-40a9-90dd-e71ab9da29dd',
            22    => '8cc6e982-0af4-4e12-be96-5387db79a166',
            24    => '4dd9c904-e892-4649-bdec-5454d6b53d28',
            25    => 'b6bf5f9c-6cc8-4a0e-ab2f-bd49e76528f5',
            26    => '6eced786-aee4-47ba-9cb6-e24f8b1d3182',
            27    => 'ec0e7fff-8233-4869-99ce-fe2b67a7de84',
            28    => 'aa1d05e0-943b-47cb-a759-9d8c16707129',
            30    => '74bc07eb-552f-4581-b68c-da46716d4a9a',
            31    => 'ffb2643b-4b90-4925-9d29-0d93ad9488a6',
            33    => '1a228763-c17a-4b2d-88b0-63b082b04da6',
            34    => '999f8753-6340-48a0-8eba-46096f9749aa',
            73    => '496c5d07-a095-4cf3-bc3a-2217e01172a3',
            74    => 'b4525da7-fe10-4e89-af86-70479d3f251e',
            75    => '1205bb4a-7d74-46a4-b7de-1cb66a3d0c03',
            76    => '059c0d58-6cdb-4955-ab79-9031518f80f3',
            77    => '8de8c002-9f06-4e91-b8bc-aebcae3b9fe7',
            78    => 'c8be0338-63f9-42d8-bc78-ee2bd45980b6',
            79    => '259b5c7a-9056-4c74-80ec-8bdc50cb0413',
            80    => 'c3066682-97a3-42fe-9eb5-3beeccab840c',
            81    => 'ba32c220-71e1-4df6-ab2b-7d5ff19a952d',
            82    => '881504b1-13e5-4280-b453-f1211164778e',
            83    => '25d687d5-5aab-41ef-afb6-c12ac1603c17',
            84    => 'e4d44e17-d107-447b-bebf-d82c636fe739',
            85    => 'ec6f7e1f-dda2-4ef3-bd34-deac136e0b4b',
            86    => 'ca225f8e-f5c5-42e9-a234-49fb629cd912',
            89    => 'c9091ffb-727e-4a88-bd7c-b17dddbefb4a',
            90    => 'd1744bea-fb26-49d4-a2b9-2b59c25132e1',
            98    => '6a0f88ba-8f25-44fc-b1cf-25f45cbe8e72',
            99    => '3ca09a1f-11f2-4763-974e-ae80404062c3',
            120   => 'd9616816-9a79-11e5-8994-feff819cdc9f',
            122   => 'd9616a6e-9a79-11e5-8994-feff819cdc9f',
            124   => 'd9616b72-9a79-11e5-8994-feff819cdc9f',
            126   => 'd9616e1a-9a79-11e5-8994-feff819cdc9f',
            128   => 'd9616f0a-9a79-11e5-8994-feff819cdc9f',
            130   => 'd9616fd2-9a79-11e5-8994-feff819cdc9f',
            132   => 'd961709a-9a79-11e5-8994-feff819cdc9f',
            134   => 'd9617388-9a79-11e5-8994-feff819cdc9f',
            136   => 'd9617464-9a79-11e5-8994-feff819cdc9f',
            138   => 'd961752c-9a79-11e5-8994-feff819cdc9f',
            140   => 'd96175f4-9a79-11e5-8994-feff819cdc9f',
            142   => 'd9617928-9a79-11e5-8994-feff819cdc9f',
            144   => 'd96179f0-9a79-11e5-8994-feff819cdc9f',
            146   => 'd9617aae-9a79-11e5-8994-feff819cdc9f',
            148   => 'd9617d4c-9a79-11e5-8994-feff819cdc9f',
            150   => 'd9617ee6-9a79-11e5-8994-feff819cdc9f',
            152   => 'ef2005d0-9a7a-11e5-8994-feff819cdc9f',
            154   => 'ef201386-9a7a-11e5-8994-feff819cdc9f',
            156   => 'b12a0156-9a7b-11e5-8994-feff819cdc9f',
            158   => 'b12a0158-9a7b-11e5-8994-feff819cdc9f',
            160   => 'b12a0160-9a7b-11e5-8994-feff819cdc9f',
            162   => 'b12a0162-9a7b-11e5-8994-feff819cdc9f',
            164   => 'b12a0164-9a7b-11e5-8994-feff819cdc9f',
            166   => 'b12a0166-9a7b-11e5-8994-feff819cdc9f',
            168   => 'b12a0168-9a7b-11e5-8994-feff819cdc9f',
            170   => 'b12a0170-9a7b-11e5-8994-feff819cdc9f',
            172   => 'b12a0172-9a7b-11e5-8994-feff819cdc9f',
            174   => 'b12a0174-9a7b-11e5-8994-feff819cdc9f',
            176   => 'b12a0176-9a7b-11e5-8994-feff819cdc9f',
            178   => 'b12a0178-9a7b-11e5-8994-feff819cdc9f',
            180   => 'b12a0180-9a7b-11e5-8994-feff819cdc9f',
            10001 => 'afa68f62-0154-4556-9ee4-3f97c3c5bdca',
            10006 => 'b715fac1-8ec2-4f5c-8fdf-0f9cec9085ad',
            10007 => '574d1c9e-9903-4626-903f-f72441d520d5',
            10012 => '7e113f1c-301a-406b-aa7a-b8654bc8c762',
            10022 => '685d8b40-2571-4111-8937-9220b1710d4c',
            10023 => '2488f7b7-5d1c-4d65-b85c-4cbcf253fd93',
            10060 => '7b45d0c7-5e22-46ac-824e-f0384e9aab52',
            10061 => 'd44995ed-edd2-4abb-999f-a56bd0f12a68',
            10062 => '849a8308-240d-4045-ab30-f8207815bce4',
            20001 => 'b6d6e4cf-67b3-4a4f-a38d-724335e9734f',
            20006 => '121981e4-a14b-450b-b9fe-718df1dc3cd1',
            20007 => '2503b262-e08c-4c2b-8598-38e0603d0d70',
            20012 => 'bfe96673-283f-40b3-b6ba-70940b16f7a4',
            20022 => '2653ca13-67c8-48c3-bbf8-ff9aa3f70ed3',
            20023 => 'b20ef9e1-faa2-4f25-9032-adbea23e5cb9',
            20060 => 'b9e02dd2-6e91-4d13-901c-5e56ab0d1cd7',
            20061 => 'e36c9ccf-e341-49a9-8fa0-f073dcd61210',
            20062 => '88f677d9-c125-45e0-bdf0-f965826542a9',

**Comment by lukada4100** [comment]
Dzięki. Właśnie o to mi chodziło.
