### ISSUE TITLE
error in msg parsing: XML error parsing SOAP payload on line 3: No memory

### ISSUE THREAD

**Issue by Thomas-RC** [allegro/allegro-api#138]
Podczas wystawiania:
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>Server</faultcode><faultstring></faultstring><faultactor>error in msg parsing:
XML error parsing SOAP payload on line 3: No memory</faultactor><detail><soapVal xsi:type="xsd:string"></soapVal></detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by MaciejPotepa** [comment]
Potrzebuję pełnej treści requestu i response w XML żeby to zweryfikować.  Potrzebne też będą dane konta, z którego próbowałeś coś zmienić w ofercie. W tym co podałeś nie ma nawet nazwy metody. 

Potrzebujemy pełnego zestawu informacji, żeby Ci pomóc.

**Comment by Thomas-RC** [comment]
Czy jest możliwość przesłania paczek na email?

**Comment by TomekKaczmarek** [comment]
@Thomas-RC wyślij je najlepiej przez [formularz kontaktowy](https://allegro.pl/pomoc/faq/problem-w-api-allegro-D5VjMgEdGha) i podaj nam tu w odpowiedzi nr ticket.

**Comment by Thomas-RC** [comment]
Rozmiar przekracza 2MB.

**Comment by PawelTaberski** [comment]
Możesz dodać 3 pliki o wielkości 2MB każdy, podziel w takim wypadku swoje zapytania. I osobno podeślij przykładowe wywołania od metod z którymi masz problem.

**Comment by Thomas-RC** [comment]
req zajmuje 10MB

**Comment by cieplik206** [comment]
może link do dropboxa przejdzie

**Comment by PawelTaberski** [comment]
Powiedz mi bo nie widzę tutaj nigdzie z jakimi metodami masz problem i jaki komunikat się pojawia? Domyślam się, że musi to być założenie nowej oferty skoro taka duża paczka? Jeśli paczka jest tak duża to oczywiście możesz wrzucić ją na jakiś zewnętrzny serwis i podesłać do nas linka w formularzu kontaktowym.

**Comment by Thomas-RC** [comment]
Paczki przesłane na kontakt@allegro.pl Re: [Ticket#1245814315] Występuje problem techniczny

**Comment by PawelTaberski** [comment]
Sprawdziłem i problem jest w tym, że przekraczasz maksymalną wielkość requesta.

**Comment by Thomas-RC** [comment]
Ok, wreszcie jakiś konkret, dzięki. Jaka jest max. wielkość reqesta? Będziemy ograniczać opis w fed341.

**Comment by PawelTaberski** [comment]
Sprawdziłem jeszcze u siebie na Twoich zdjęciach i opisie, przechodzi normalnie taki request. Jesteś pewny, że po stronie swojego klienta z którego korzystasz nie masz nałożonego jakiegoś ograniczenia?

**Comment by Thomas-RC** [comment]
Ale resp. jest od allegro. Próbowałem wystawic równiez z inego konta tą samą aukcję również doNewAuctionExt i ten sam błąd: XML error parsing SOAP payload on line 3: No memory. Proszę wystawić aukcje której req. przekracza 10MB.

**Comment by PawelTaberski** [comment]
Przetestowałem na 12MB requeście i większych. Oferty wystawiają się bez problemu, po prostu request przechodzi trochę dłużej.

**Comment by TimothyKoval** [comment]
Niech zgadnę; używasz starego WSDL-a [https://webapi.allegro.pl/uploader.php?wsdl](https://webapi.allegro.pl/uploader.php?wsdl)

**Comment by Thomas-RC** [comment]
tak jest ta sama  zwrotka z soapui:
<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>Server</faultcode>
         <faultstring/>
         <faultactor>error in msg parsing:
XML error parsing SOAP payload on line 3: No memory</faultactor>
         <detail>
            <soapVal xsi:type="xsd:string"/>
         </detail>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by TimothyKoval** [comment]
Spróbuj z nowym WSDL-em [https://webapi.allegro.pl/service.php?wsdl](https://webapi.allegro.pl/service.php?wsdl)

**Comment by PawelTaberski** [comment]
Maksymalny request w starym wsdl-u jaki udało mi się przesłać miał 10 zdjęć. Wielkość requesta niecałe 8MB.

**Comment by Thomas-RC** [comment]
Ok. Dziękuję zatem za informacje.
