### ISSUE TITLE
/order/checkout-forms/{id}/shipments - lineItems

### ISSUE THREAD

**Issue by nukotel** [allegro/allegro-api#1380]
Dzień dobry,
Jakie informacje należy przekazać w lineItems i w jaki sposób można je wcześniej uzyskać?

**Comment by MartaNowaczyk** [comment]
Dzień dobry,

pobierzesz je np. za pomocą [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET). Więcej o pobieraniu zamówień znajdziesz [w naszym poradniku](https://developer.allegro.pl/orders/#03).
