### ISSUE TITLE
Get contact phone from offers listing

### ISSUE THREAD

**Issue by ronek22** [allegro/allegro-api#1381]
Cześć,
Jak pobrac numer telefonu sprzedawcy? 
Teoretycznie ta metoda powinna zwracac dla sellera blok contact
![Screenshot from 2019-03-21 12-51-31](https://user-images.githubusercontent.com/5845876/54750588-7afe0e00-4bd8-11e9-9219-b5b52ca88ec2.png)
Niestety go nie dostaje
![Screenshot from 2019-03-21 12-55-40](https://user-images.githubusercontent.com/5845876/54750650-b6004180-4bd8-11e9-98ac-6fa943e70bf4.png)

**Comment by MartaNowaczyk** [comment]
Za pomocą GET /offers/listing nie pobierzesz telefonu sprzedającego. W tym zasobie nie planujemy zwracać takich danych.

**Comment by ronek22** [comment]
W takim razie istnieje jakis inny zasob, w ktorym moglbym pobrac dane o telefonie sprzedającego?
Jeśli nie to czy macie to w planach?

**Comment by ronek22** [comment]
Na przyklad z web api, dostaje takie pole
'itContact': 'e3dc47ed-4855-463a-9365-089525dda4e0'
Moge na podstawie tego, otrzymac numer telefonu?

**Comment by MartaNowaczyk** [comment]
swoje dane możesz pobrać, ale nie mamy zasobu, który pozwoli ci pobrać dane innego (niezautoryzowanego) sprzedającego.
