### ISSUE TITLE
Problem z zasobem /sale/classifieds-packages?category.id=

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1382]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-Id: 590e4eb2bc140d72

Nie mogę pobrać informacji o pakietach i opcjach dodatkowych dla wybranej kategorii, oczywiście wszystkie id kategorii mają flagę "Leaf=true". W response otrzymuję:
{"packages":[]}

Przykładowe kategorie:

147905
77803
77805
260288

**Comment by MartaNowaczyk** [comment]
Podane kategorie nie należą do ogłoszeń, stąd problem.

**Comment by Gerston** [comment]
To może jakiś komunikat by się przydał, a nie pusty response?

**Comment by MartaNowaczyk** [comment]
@Gerston zgłoszę brak komunikatu do odpowiedniego zespołu.
