### ISSUE TITLE
Znaki łamania wiersza w oryginalnym zrzucie aktywnej oferty pobranej z Allegro

### ISSUE THREAD

**Issue by Masterboreq** [allegro/allegro-api#1383]
Dzień dobry,

[Problem]
Napotkałem problem z aktualizacją opisu istniejącej oferty w zakresie FID 341 (nowy opis) po zmianie treści rzeczonego opisu.

[Opis podjętych działań]
1. Ze zrzutu aukcji wybierane są dane typu: nr oferty, tytuł, nowy opis, cena i one zapisywane są w bazie danych. Zapisywana jest też w formie pliku .jpg na dysku tzw. miniaturka (FID 16).  Zapisywany jest także plik zrzutu danych oferty: jest to zserializowany obiekt (to będzie za chwilę istotne!). Do pobrania danych oferty używam metody WebAPI doGetItemFields().
2. Następnie opis danej oferty w bazie danych jest zmieniany: dla potrzeb tego przykładu załóżmy, że muszę wyrzucić z opisu frazę "Ala ma kota". Skrypt więc wycina w/w frazę i nadpisuje rekord w BD.
3. Gdy już skrypt przetworzy cały zasób ofert klienta, inny skrypt stara się zaktualizować przetworzone w pkt. 2 oferty wysyłając je do serwisu Allegro.

I w części ofert pojawia się błąd: ERR_STANDARDIZED_DESCRIPTION_INCORRECT — description musi być podane. 

[Podejrzenie i rozpoznanie]
Mamy np. ofertę: https://allegro.pl/oferta/tunel-podlokietnik-schowek-vw-passat-b8-3g0864207a-7365507229. Okazuje się, że treść opisu oferty z BD zawiera znaki łamania wiersza LF (kod ASCII 10).
Pierwsze co, to wykluczyłem możliwość dodania znaków łamania wiersza przez mój skrypt. Następnie spojrzałem do FID-a nr 341 w pliku zrzutu i "co ja pacze?!":
"fid";i:341;s:12:"fvalueString";s:1246:"{"sections":[{"items":[{"type":"TEXT","content":"<p>Przedmiotem jest</p>**\n**<p>Tunel podłokietnik ze schowkiem</p>**\n**<p>Stan Nowy </p>**\n**<p>Orientacja (przód/tył) Przód</p>...itp, itd...},{"type":"IMAGE","url":"PHOTO_FID_17"}]},{"items":[{"type":"TEXT","content":"<p>Wystawiony przedmiot jest unikatowy, a fotografia przedstawia przedmiot, którego dotyczy aukcja.</p>**\n**<p>Przedmiot posiada nadrukowany oryginalny numer OEM producenta (VW lub AUDI; w zależności od marki) i pochodzi od licencjonowanego fabrycznego sprzedawcy.</p>**\n**<p>(tutaj wycinane kocopoły typu Ala ma kota")</p>"}]}]}";

W zasadzie chyba to powinienem zgłosić jako błąd. Możecie mi Państwo to jakoś wyjaśnić, jak to się stało, że w waszych bazach danych przetrzymywany jest niepoprawny formalnie opis? Mój klient używa wyłącznie webowego GUI do edycji opisów w wystawianych aukcjach. Gross z ofert **nie zawiera znaków LF (\n)** w opisie oferty. Moim zdaniem **nie jest** to problem:
 - transkrypcji opisu do mojej lokalnej BD, bo pobierałem ponad 4k zrzutów ofert i gross z nich jest OK,
 - "zabrudzania" opisu znakami LF poprzez deamona API na Państwa backendzie z przyczyn opisanych w punkcie powyżej.

<ochrzan;)>
Aktualizuję ponad 4k ofert mojego klienta i szlag mnie może trafić, gdy się okazuje, że serwis, który co rusz odgraża się swoim klientom (sic!), że im poubija oferty, bo np. dane zdanie z opisu oferty im się nie podoba, sam dopuszcza zapisywanie formalnie błędnych opisów w swoich bazach danych. Oczywiście odesłanie Wam na serwer takiego wujowego opisu (pobranego z Allegro!) skutkuje wywaleniem "ERR_STANDARDIZED_DESCRIPTION_INCORRECT". Jak to w ogóle wygląda, że mój klient drży przez ostatnie dni, czy mu dziś wywalicie 20 czy 100 aukcji, a tymczasem samo Allegro łamie swoje własne zasady? Brak mi słów! Proszę naprawić błąd polegający na dopuszczalności zapisu znaków specjalnych w opisach oferty. Mój klient właśnie traci kolejne pieniądze za czas, który poświęcam na hackowanie mojego skryptu i potencjalnie traci przychód, bo kolejne aukcje są ubijane z powodu opisu, którego nie da się poprawić przez błędy w Państwa serwisie.
</ochrzan;)>

**Comment by MartaNowaczyk** [comment]
@Masterboreq po pobraniu metodą doGetItemFields twój opis wygląda tak:
`<![CDATA[{"sections":[{"items":[{"type":"TEXT","content":"<p>Przedmiotem jest</p><p>Tunel podłokietnik ze schowkiem</p><p>Stan Nowy</p><p>Orientacja (przód/tył) Przód</p><p>Strona (lewo/prawo)</p><p>Kod części 3G0864207A</p><p>Marka/Model Volkswagen Passat B8</p><p>Uwagi do przedmiotu Nie montowany w aucie</p> "},{"type":"IMAGE","url":"PHOTO_FID_17"}]},{"items":[{"type":"TEXT","content":"<p>Wystawiony przedmiot jest unikatowy, a fotografia przedstawia przedmiot, którego dotyczy aukcja.</p><p>Przedmiot posiada nadrukowany oryginalny numer OEM producenta (VW lub AUDI; w zależności od marki) i pochodzi od licencjonowanego fabrycznego sprzedawcy.</p><p>Jeśli nie jesteś pewny, czy właśnie ten przedmiot jest tym właściwym dla Twojego pojazdu, skonsultuj zakup z serwisem lub z nami</p><p>Gwarantujemy, że wszystkie zakupione na naszych aukcjach podzespoły, które wymagają zaprogramowania w serwisie VW lub Audi (np. lampy, czujniki, kamery itp.) bez przeszkód zostaną przyjęte w takim serwisie, zostaną zaprogramowane do działania w Państwa samochodzie i będą bez przeszkód w nim działać tak, jakby były w Państwa samochodzie od nowości.</p>"}]}]}]]>`

Bez problemu mogę wystawić nową ofertę z tym opisem, także na ten moment nie widzę problemu po naszej stronie.

Podeślij pełny request i response, a nie tylko wycięte kawałki oraz opisz co zmieniasz.

**Comment by FromAnyHole** [comment]
@Masterboreq - chyba dopiero zaczynasz zabawę z Allegro-API ;-)
Znaki [LineFeed] w treści opisu są jak najbardziej poprawne, wręcz wskazane dla poprawnej pracy przeglądarek, a to że nie pojawiają się regularnie - no cóż, taki mamy klimat ;-) Jak przelecisz kilka milionów opisów trafisz na zupełnie inne niespodzianki, spodziewaj się w treści wszystkiego ! ;-)

**Comment by Masterboreq** [comment]
@MartaNowaczyk, teraz to już jest "po ptakach" - przedstawiłaś mi zasób oferty po mojej jej (oferty) aktualizacji. Sprawdziłem to dwukrotnie. Nie znajdziesz więc tam znaków \n, które engine MySQL-a przetransponował do postaci znaku LF w rekordzie bazy danych. Rozminęliśmy się po prostu w czasie:)
Piszesz: 

> Bez problemu mogę wystawić nową ofertę z tym opisem, (..)

Oczywiście, że teraz już tak, gdy odfiltrowałem to dziadostwo (znaki LF) przy pomocy skryptu i... wysłałem aktualizację opisu, który to opis (w poprawnej już wersji) nomen omen mi wkleiłaś w odpowiedzi powyżej.

> (...) także na ten moment nie widzę problemu po naszej stronie."

Załączam Ci za to pełny dump oryginału przedmiotowej oferty nr [7365507229

](https://allegro.pl/oferta/tunel-podlokietnik-schowek-vw-passat-b8-3g0864207a-7365507229), który zawiera oryginalny zestaw danych pobranych z BD Allegro: [7365507229.zip](https://github.com/allegro/allegro-api/files/2995939/7365507229.zip)
Odfiltruj sobie frazę `"fid";i:341;s:12:"fvalueString";s:1246:`, to wraz z kolejnym znakiem rozpocznie się opis, który zawiera znaki "\n". To jest wystarczający i ostateczny dowód na to, żeby rozpocząć poszukiwania, dlaczego w ogóle w BD Allegro zapisują się znaki "\n", które - w przypadku zaciągnięcia do oprogramowania klienckiego - transponują się na znaki LF. To właśnie obecność znaków LF (oraz pewnie CR czy innych znaków, w tym sterujących znaków ASCII) jest bezpośrednią przyczyną, dla której zwrotne żądanie wychodzące z oprogramowania klienckiego (np. w celu poprawienia opisu), odbija się i zwracany jest błąd.

Zbadajcie to, bo może jest mechanizm na przemycenie jakichś znaków do pól rekordów BD, a od tego już niedaleko do wstrzykiwania kodu.

**Comment by Masterboreq** [comment]
@FromAnyHole

> chyba dopiero zaczynasz zabawę z Allegro-API ;-)

tośmy się pośmiali, a teraz do rzeczy:

> Znaki [LineFeed] w treści opisu są jak najbardziej poprawne, wręcz wskazane dla poprawnej pracy przeglądarek (...)

Nie mówimy o przeglądarkach, tylko formacie przesyłu ciągu znaków do deamona obsługującego API SOAP w Allegro, który łaskawie albo zaakceptuje ciąg zawierający dany znak, lub nie. I nie - w tym przypadku znaki LF powodują wywalenie błędu protokołu. 
Jeśli już się uczepić przeglądarek, to znaki łamania nie są "wskazane", lecz wymagane w nagłówkach HTTP. I tyle. W samej treści HTML przeglądarkę ani ziębi ani parzy, czy napiszesz kod ciurkiem, w jednej linii, czy rozbijesz go na wiersze przy użyciu LF, CR, czy CRLF razem wzięte. Nie pisz więc następnym razem, proszę, takich nic nie wnoszących bzdur.

**Comment by MartaNowaczyk** [comment]
@Masterboreq lepiej by było, jakbyś podesłał mi numer aktualnie trwającej oferty z tym problemem. Masz może taką? 
Tak poza tym, to nie zmienia się danych oferty, w której zgłasza się błąd, bo wtedy jest jak napisałeś "po ptakach".

**Comment by FromAnyHole** [comment]
@Masterboreq - uważasz się za takiego znawcę tematu... A wymiękłeś na banalnej sprawie kodowania treści opisów, które dopuszczają obecnie aż 7 znaczników ;-) Znaki z zakresu Hex 00-0F po prostu występują, w historii zmian były podawane w formie enkodowanej lub nie, to nie był nigdy wielki problem...

**Comment by Masterboreq** [comment]
@MartaNowaczyk widzisz Marto, gdyby może:
- Allegro traktowało klientów prowadzących sklepy jak partnerów, a nie intruzów, dając im czas na rozgryzienie tematu vel. poprawienie błędów, które klient ewidentnie popełnił, albo
 - gdyby za formularzami kontaktowymi stała jakaś świadoma, myśląca osoba, a nie bot/skrypt rzucający  kilkoma głodnymi formułkami, albo
 - gdybyście mieli dział wsparcia dla klienta biznesowego z prawdziwego zdarzenia, w którym ludzie myślą nad sensem swoich działań, a nie działają odcinkowo (tzn. do granicy działu, w którym pracują), fragmentarycznie rozpatrując sprawę,
to rzeczywiście bym poczekał. A tak - może powinniście to wiedzieć, bo może wam tego (Drogi Teamie Allegro) nikt wcześniej nie powiedział? - mój klient dwoi się i troi, by poprawić swoje błędy, koresponduje z Allegro, prosi o wsparcie i... kolejnych 100 aukcji jest ubijane, bo żaden geniusz nie wpadł na pomysł żeby klientowi dać dwie doby czasu na poprawienie ponad 4k ofert. Na wyraźną prośbę klienta o takie 2 doby, ktoś z Allegro odpowiada, że nie może zagwarantować takiego moratorium.
Efekt jest taki, że ja - będąc wsparciem technicznym mojego, ale i waszego klienta, nie mogę czekać, aż wasze boty ubiją klientowi kolejne aukcje, albo kolejny admin wpadnie na pomysł zatwierdzenia aukcji klienta do ubicia; bez zastanowienia się, czy jakiekolwiek ustalenia czy rozmowy z klientem były prowadzone. Dennie to, niestety, wygląda.

To jest jednak kanał wsparcia technicznego, a ja nie mam czasu poprawiać waszego "user experience". Co  z dumpem aukcji? Czy nalazłaś znaki, o których mówiłem? Bo bezsprzecznie tam są. Pytam zatem: czemu serwer Allegro zwraca mi treść opisu ze znakami LF, ale wysyłając treść w druga stronę, z tymi samymi znakami, Allegro już takiego payloadu nie przyjmuje? Przecież to bez sensu!

Zwykle, zanim zarzucę wam błąd, sprawdzam, czy może mój skrypt czegoś nie zepsuł lub może ja coś przeoczyłem. Sprawdziłem więc sobie **raz jeszcze**, czy gdziekolwiek w otrzymanym z Allegro dumpie danych z aukcji 7365507229 w jakimkolwiek innym polu występuje znak sekwencja znaków "\n" **i nie występuje. Występuje tylko w kodzie JSON FID-u 341.** 
W jednym z wątków ktoś z was wspominał, że wszelkie znaki łamania linii i pary pustych znaczników <p/> są wycinane na backendzie. Jak zatem się stało, że zapisaliście sobie w bazie znaki LF jako \n?

Kolego/koleżanko @FromAnyHole: proszę, zrozum, że to nie jest miejsce leczenia swojego ego. Piszesz nie na temat, nie rozumiesz przedstawionej problematyki tego wątku i generalnie nie pomagasz. Za to mądrzysz się o pierwszych 15 znakach tablicy ASCII, gdy tutaj w ogóle nie o to chodzi. Nie mam potrzeby ci niczego udowadniać; ty mi również, więc może bądź łaskaw zacząć się wypowiadać na temat. W przeciwnym razie zacznę ignorować twoje wypowiedzi.

@MartaNowaczyk: gdy znajdę jakąś nową aukcję zawierającą takie anomalia, podeślę request++response i kolejny dump takiej aukcji.

**Comment by FromAnyHole** [comment]
@Masterboreq - wierszem: piszesz tu elaboraty, na nie istniejące tematy ;-)
A ten support API-Allegro, nie prowadzi kursów gimnazjalnych z kodowania...

**Comment by MartaNowaczyk** [comment]
@Masterboreq jak podeślesz świeży przykład to sprawdzę.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - Pani Marto, wszystko działa tu poprawnie, człowiek się pogubił w prostej rzeczy... Od piątku puszczone zostało kilkadziesiąt tys. najróżniejszych opisów, czasem tylko konieczna jest redukcja znaków kontrolnych (o ile występują), ale z banalnego powodu: około-progowej długości całego opisu.
