### ISSUE TITLE
Niepoprawna wartość klucza WebAPI lub klucz został zablokowany.

### ISSUE THREAD

**Issue by ronek22** [allegro/allegro-api#1384]
Aplikacja w REST API dobrze działa z kluczami aplikacyjnymi, 
jednak gdy staram się uruchomić aplikację napisaną w WebAPI dostaje informacje zwrotna:
Niepoprawna wartość klucza WebAPI lub klucz został zablokowany.

Oczywiscie jako API KEY w WebAPI używam ClientID

**Comment by Gerston** [comment]
Do WebApi powinieneś użyć klucza ApiKey, a klucz ClientID jest kluczem do RestApi

**Comment by ronek22** [comment]
![Screenshot from 2019-03-21 13-59-27](https://user-images.githubusercontent.com/5845876/54753543-93bef180-4be1-11e9-932b-216febef858f.png)
O jakim ApiKey mówisz?
Na screenshocie chyba jasno jest wyszczegolnieno, ze w webapi jako apikey uzywam clientID

**Comment by MartaNowaczyk** [comment]
@ronek22 tak, możesz używać Client ID jako klucz dla WebAPI. Wsześniej ta aplikacja działała, czy od początku są jakieś problemy. Używasz tego samego klucza?

**Comment by ronek22** [comment]
Wcześniej działała, dzisiaj już nie działa :(
Rozumiem, ze klucz moze zostac zablokowany, ale czemu wtedy dla REST działa, a dla WebApi nie?

**Comment by Gerston** [comment]
Masz rację, faktycznie oba klucze działają i ten wygenerowny wcześniej dla WebApi i ten ClientID z Rest Api.

**Comment by MartaNowaczyk** [comment]
@ronek22 potrzebuję klucz, żeby zobaczyć czy jest ok. Ale jeśli w jednym dział, a w drugim nie, to nie powinien być zablokowany. Na pewno nic nie zmieniałeś?

**Comment by ronek22** [comment]
Przepraszam, za problem. 
Okazalo się, że w pliku konfiguracyjnym dodałem niepotrzebne cudzysłowy, teraz wszystko dziala
