### ISSUE TITLE
Opcje promowania ofert

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1385]
Mam pytanie, w jaki sposób i czy jest już taka możliwość, aby w RestApi włączyć opcje promowania w pakiecie?

**Comment by Gerston** [comment]
Chyba już wiem, należy włączyć flagę EmphasizedHighlightBoldPackage?

**Comment by PawelTaberski** [comment]
Hej dokładnie tak musisz uzupełnić tą sekcję:
```
    "promotion": {                              --  niewymagane, opcje promowania,
                                                przy każdej z opcji należy wybrać 
                                                jedną z wartości: false (opcja nieaktywna); 
                                                true (opcja aktywna)
        "emphasized": true,                     -- wyróżnienie
        "bold": false,                          -- pogrubienie
        "highlight": false,                     -- podświetlenie
        "departmentPage": false,                -- oferta promowana na stronie kategorii
        "emphasizedHighlightBoldPackage": false -- pakiet promowania: wyróżnienie,
                                                podświetlenie i pogrubienie oferty
    },
```
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-8-complete).

**Comment by Gerston** [comment]
Ale mi chodziło o wypromowanie oferty w pakiecie czyli "Wyróżnienie, Podświetlenie i Pogrubienie w pakiecie", więc wczoraj spróbowałem tak jak napisałem i działa:

"promotion": {      
                                           
        "emphasized": false,                   
        "bold": false,                        
        "highlight": false,                   
        "departmentPage": false,               
        "emphasizedHighlightBoldPackage": true 
                                                
    },

**Comment by Gerston** [comment]
https://allegro.pl/pomoc/dla-sprzedajacych/promowanie-ofert/czym-sa-opcje-promowania-ofert-i-jak-z-nich-korzystac-YLKol7EM6CY

**Comment by PawelTaberski** [comment]
Dokładnie tak możesz skorzystać z osobnych opcji, albo od razu z pakietu.
