### ISSUE TITLE
Zła data (godzina) doGetItemsInfo

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#1386]
Występuje problem: 
 - [x ] z metodą WebAPI
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Raz na jakiś czas API zwraca czas w systemie 12 godzinnym zamiast 24.

Przykład aukcji: 7920318995
Zazwyczaj zwracany jest czas zakończenia:
2019-03-28 13:07:21
ale czasem (np. kilka minut temu)
2019-03-28 01:07:21

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) kilka przykładowych requestów i responsów z datą w takim formacie. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1386 na GitHub-ie
