### ISSUE TITLE
"Przeskakujące dzienniki"?

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1387]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [X] inny

Czy ktoś z Was spotkał się z takim problemem
1. doGetSiteJournal JournalID = 0
2. pobieramy deals, transakcje
3. zapisujemy LastID =10  i LastDealsID = 10
4. doGetSiteJournal LastID = 10, LastDealsID =10
5. zapisuje deals, transakcje które dostałem od LastDealsID > = 10 do ostatniego zwróconego
6. zapisujemy ostatnie zwrócone LastID =20  i LastDealsID = 30
7. doGetSiteJournal LastID = 20, LastDealsID =30
8. zapisuje deals, transakcje które dostałem od LastDealsID > = 30 jak w punkcie 5
9. zapisujemy LastID =20  i LastDealsID = 40
10. doGetSiteJournal LastID = 20, LastIdDeals =40

Okazuje się że czasami zdarza się sytuacja że nie ma określonej transakcji która powinna być i wpada "automagicznie", np. jeśli cofniemy się i podamy LastIdDeals wcześniejsze  lub 0 to dostajemy ją w API  a wcześniej jej tam nie było, np pobierając w dniu 5.03.2019 transakcje mam ich przykładowo 100 z tego dnia, a za tydzień nagle pojawia się dodatkowe 5, ale obecne LastID, LastIDDeals które mam już tego nie "chwyta" i  muszę cofnąć liczniki by zadziałało
Jest to irytujące bo występuje losowo, a nie jestem zwolennikiem pobierania wszystkiego :)

Np mam zapisane LastDealID = 20178xxxx a nagle dostaję (po wyzerowaniu albo cofnięciu się) deale o idenfyfikatorach: 20075xxxx, których wcześniej nie pobrało mi

**Comment by yncki** [comment]
Witaj w klubie, niestabilne, chaotyczne, znienawidzone przez developerów api którego nikt nie ogarnia (nawet allegro). Ogólnie powodzenia. 

Powinien być jakiś bojkot tego badziewia, ale business is business. No way out.

**Comment by SebastianOzdoba** [comment]
@yncki heh
Przykłąd z wczoraj:
21.03.2019 godz 18, GetJournalId z parametrem 0  - teoretycznie dostanę wszystkie
mam transakcje
21.03.2019 godz 20, GetJournalId z parametrem 0
Bach, wpada transakcja z 20.03.2019, z godz 20:44 :)
Co się w z tym wiąże:
- brak stabilności i pewności że pobrałem wszystko
- Klient straci status SuperSprzedawcy, bo wysyła paczki w 24h
- takich transakcji które w ten sposób wpadają jest więcej, czasami zdarza się transakcja sprzed kilku dni
- pobieranie różnicowe z użyciem dzienników NIE jest pewne, pobieranie pełne jak widać też NIE jest
- pobieranie pełne trwa długo, webAPI ostatnio ograniczyło ilośc strzałów z 25 do 10

@MartaNowaczyk @MarcinLuczak @TomekKaczmarek - prośba o komentarz jak zamierzacie nam pomóc?

**Comment by yncki** [comment]
@SebastianOzdoba w ktorej zmienili na 10 ? 
tutaj nadal jest 25 ( według docsów ) https://allegro.pl/webapi/documentation.php/show/id,703#method-input

**Comment by SebastianOzdoba** [comment]
@yncki skrót myślowy, miałem na myśli to inną metodę
https://allegro.pl/webapi/documentation.php/show/id,52

**Comment by MartaNowaczyk** [comment]
@SebastianOzdoba sprawdzimy opisany problem z dziennikami.

**Comment by Onixarts** [comment]
Ten problem występuje od zawsze. My profilaktycznie skanujemy okresowo dziennik z kilku dni wstecz. Teraz przynajmniej mam pewność, że nie tylko u nas tak się dzieje.

**Comment by SebastianOzdoba** [comment]
@Onixarts zgadza się, ten problem występuje od zawsze. Jednak teraz jest dużo bardziej odczuwalny bo na podstawie czasu realizacji zamówienia liczony jest status sprzedawcy, a jak zamówienia się gubią to i status się może szybko zgubić :)
