### ISSUE TITLE
Jak pobrać oferty archiwalne?

### ISSUE THREAD

**Issue by MasterSlynx** [allegro/allegro-api#1388]
Tak jak w temacie, jak pobrać z konta oferty archiwalne?
Przy pobieraniu poprzez /sale/offers można wybrać jak publication.status tylko inactive/active/activating/ended. Nie widzę opcji "archived".

Klient chce mieć w systemie dane dotyczące wszystkich ofert i zamówień od początku roku, a tymczasem do nich nie ma dostępu, bo już są w archiwum.
Jak pobrać takie oferty? Archiwalne oferty nie są już zmieniane, więc jest to jednorazowa operacja.
Kilkukrotnie na sandboxie udało się wczytać takie oferty - pewnie w wyniku błędu.
Kolejna bardzo istotna rzecz, która powinna być w API od początku. 
To normalne, że jak ktoś dużą sprzedaż prowadzi przez Allegro to może potrzebować dostępu do archiwum sprzedaży...

**Comment by PawelTaberski** [comment]
Nie ma możliwości pobrania przez API archiwalnej oferty. Po tym jak ona zostanie przeniesiona do archiwum nie możesz już jej pobrać.
