### ISSUE TITLE
Create Command for Batch publish offers

### ISSUE THREAD

**Issue by SavanovicN** [allegro/allegro-api#1389]
Hi,

I'm having trouble with command when I want to batch publish offers. Read documentation but do not quite understand the process of creating command and how should I handle it?

Or is it something that i need to fetch from somwhere as a list of command names and ids?

Any help is welcome.
Thanks.

**Comment by PawelTaberski** [comment]
I dont fully understand you. The simplest way to understand how the complete offer should look like is to create publish by Moje Allegro and then use GET sale/offers/{offerId}.
Have you read our guide, which is available [here](https://developer.allegro.pl/en/sale/)?

**Comment by SavanovicN** [comment]
Yes I read but it lead me to idea that i need to create my own unique command.
"If the offer is already complete and correctly validated, you can publish it on the website using the PUT / sale / offer-publication-commands / {commandId} method . This is an asynchronous method. 
In the commandId field, enter the value in the UUID (universally unique identifier) ​​format. It is a globally unique identifier, which consists of 32 hexadecimal numbers (eg: 21ae4ed1-eab7-34ea-b605-cf2e22b5eed3). "

So this is comand Id for publishing action? 21ae4ed1-eab7-34ea-b605-cf2e22b5eed3

**Comment by PawelTaberski** [comment]
No you should have generated your own UUID and on this number you can track your task for example in: GET /sale/offer-publication-commands/{commandId}/tasks

**Comment by SavanovicN** [comment]
I Read again docs and can you please confirm this flow for creating command and publishing offers:
get my offers -> foreach offer from response -> call (PUT /zasób-biznesowy/{offerId}/{publish}-commands/{randomGeneratedUUID}) ->got response -> call batch publish endpoint with command id from response?
Thanks and sorry for late reply.
