### ISSUE TITLE
POST /sale/offers Internal Server Error 500

### ISSUE THREAD

**Issue by Ontr** [allegro/allegro-api#1390]
POST /sale/offers
Przy nieustawionym sellingMode w odpowiedzi serwer zwraca Internal Server Error 500 zamiast błędów walidacji.

Trace-Id 53b11b1bdf50a6ca

**Comment by MartaNowaczyk** [comment]
Przy POST /sale/offers  wymagamy tylko tytułu i kategorii najniższego rzędu. Czy ponowienie requestu daje ciągle ten sam efekt? Podeślij proszę  request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1390
