### ISSUE TITLE
Skąd wytrzasnąć {commandId} dla PUT /sale/offer-publication-commands/{commandId}

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1391]
Witam,
skąd można pobrać {commandId} dla PUT /sale/offer-publication-commands/{commandId}

Mam draft zrobiony i zweryfikowany i nie widzę tam podanego  {commandId}.

**Comment by Gerston** [comment]
commandId generujesz sobie sam :)

**Comment by Gerston** [comment]
https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by Gerston** [comment]
nie wiem w czym programujesz, ale w c# jest to banalnie proste:
var commandID=Guid.NewGuid();

**Comment by AleksyZajac** [comment]
Dzięki za informację.

**Comment by PawelTaberski** [comment]
Więcej na temat tych identyfikatorów znajdziesz również na [naszej stronie](https://developer.allegro.pl/about/#ids).

**Comment by AleksyZajac** [comment]
Dziękuje za wszystkie informacje.
