### ISSUE TITLE
Internal Server Error na doGetBidItem2()

### ISSUE THREAD

**Issue by szczeles** [allegro/allegro-api#1392]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Od godziny 9:20 wszystkie żądania do `doGetBidItem2()` w [WebAPI](https://allegro.pl/webapi/documentation.php/show/id,44)  rzucają HTTP 500 oraz faultcode `ERR_INTERNAL_SYSTEM_ERROR`. Przykład:

żądanie:
```
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:DoGetBidItem2Request xmlns:ns0="https://webapi.allegro.pl/service.php">
      <ns0:sessionHandle>_________________</ns0:sessionHandle>
      <ns0:itemId>7262949180</ns0:itemId>
    </ns0:DoGetBidItem2Request>
  </soap-env:Body>
</soap-env:Envelope>
```

odpowiedź (HTTP status code: 500)
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode><faultstring>Wewnętrzny bład systemu.</faultstring><faultactor>doGetBidItem2 - Internal System Error.</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i nie ma problemu. Zobacz proszę czy u ciebie też jest ok.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - Aaaaajaj ! Piontek ;-)
W nocy było wszystko Ok, teraz sypie się ta metoda kompletnie !

**Comment by szczeles** [comment]
@MartaNowaczyk ok. 9:58 wróciło do normy i od tej pory u mnie wszystko działa jak należy :-)

**Comment by FromAnyHole** [comment]
@szczeles - a to proponuje sprawdzić, jakie daty (UT) zwracane są dla poszczególnych transakcji ;-)

**Comment by szczeles** [comment]
@FromAnyHole Daty są OK, w środę wieczorem kupiłem item 7757151082 i wszystko się zgadza w odpowiedzi:
```
<ns1:bidsArray>
  <ns1:item>7757151082</ns1:item>
  <ns1:item>0</ns1:item>
  <ns1:item>s...s</ns1:item>
  <ns1:item>0</ns1:item>
  <ns1:item>0</ns1:item>
  <ns1:item>1</ns1:item>
  <ns1:item>6.9</ns1:item>
  <ns1:item>1553118103</ns1:item>
  <ns1:item>1</ns1:item>
  <ns1:item></ns1:item>
  <ns1:item></ns1:item>
  <ns1:item>0</ns1:item>
</ns1:bidsArray>
```

**Comment by FromAnyHole** [comment]
@szczeles - spoko, ja nie twierdzę tutaj, że zawsze i na każdym użytkowniku, ale dzisiaj grzebią ! ;-)

**Comment by SebastianOzdoba** [comment]
@FromAnyHole @szczeles 
Ja mam z dziś: 2019-03-22 15:00:26.857 -  Internal system error - doGetItemsInfo

**Comment by szczeles** [comment]
U mnie śmigają obie metody - `doGetItemsInfo` i `doGetBidItem2` :tada: , musiała być jakaś 40-minutowa czkawka systemu z rana. Problem rozwiązany, więc zamykam to zgłoszenie. 
@FromAnyHole  @SebastianOzdoba jeśli Wasze problemy wciąż się pojawiają to polecam zrobić nowe zgłoszenie, żeby nie mieszać wątków.
@MartaNowaczyk  dzięki za sprawdzenie!
