### ISSUE TITLE
doGetSellFormFieldsForCategory - wolne działanie

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#1394]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Przykład: 
kategoria: 110136
data wysłania: 2019-03-22 10:04:57 (1553245497)
data odpowiedzi: 2019-03-22 10:05:38

Zaobserwowałem, iż w ostatnim tygodniu metoda WebAPI 'doGetSellFormFieldsForCategory' znacznie wolniej odpowiada. Zdarza się, że odpowiedź nie przychodzi nawet przez 120s.

Proszę o informację jaka jest przyczyna?

**Comment by MartaNowaczyk** [comment]
Sprawdzamy co może być przyczyną spowolnienia.

**Comment by vitapak** [comment]
Czy sytuacja się wyjaśniła?

**Comment by MartaNowaczyk** [comment]
Tak, informacja pojawiła się w #1393
"Udało się nam zlokalizować przyczynę problemu i od 26.03 ok 15:00 problem nie powinien już utrudniać korzystania z API. Jego przyczyna leżała poza infrastrukturą Allegro.pl - problem występował w komunikacji do API z serwerów zlokalizowanych u jednego z dostawców usług hostingowych."
