### ISSUE TITLE
Problem z publikacją oferty

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1395]
Przy próbie odwołania się
https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/94c50875-354f-4628-9af9-9493c96fb255

{
    "publication": {
        "action": "ACTIVATE",
    },
    "offerCriteria": [
        {
            "offers":[
                {
                    "id": "6206239231"
                }
            ],
            "type": "CONTAINS_OFFERS"
        }
    ]
}

dostaje 400 Bad Request

$VAR1 = {
          'errors' => [
                        {
                          'userMessage' => undef,
                          'path' => '/sale/offer-publication-commands/94c50875-354f-4628-9af9-9493c96fb255',
                          'details' => undef,
                          'message' => 'An error has occurred',
                          'code' => 'ERROR'
                        }
                      ]
        };

Czy mogę prosić o informację dlaczego.

**Comment by AleksyZajac** [comment]
Dobra znalazłem, przepraszam za zamieszanie. Wszystko działa.

**Comment by runaway90** [comment]
@AleksyZajac można opisać w czym był probłem i poznej zamkneć ten issue?

**Comment by AleksyZajac** [comment]
Tak oczywiście.
Problem polegał na błędnej składni, a dokładnie jeden przecinek za dużo.
Było "action": "ACTIVATE", a powinno być "action": "ACTIVATE"
