### ISSUE TITLE
createOrderShipmentsUsingPOST zwraca błąd

### ISSUE THREAD

**Issue by nukotel** [allegro/allegro-api#1396]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Endpoint: createOrderShipmentsUsingPOST
Po wysłaniu requesta:

>  {
>     "carrierId": "RUCH",
>     "waybill": "2100197297684",
>     "lineItems": [
>         {
>             "id": "140238924"
>         },        
>         {
>             "id": "140238925"
>         }
> 
>     ]
>  }

Zwraca w odpowiedzi:

> {
>     "errors": [
>         {
>             "code": "NotAcceptableException",
>             "message": "An error has occurred",
>             "details": null,
>             "path": null,
>             "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
>         }
>     ]
> }

**Comment by MartaNowaczyk** [comment]
Nie podałeś konkretnej ścieżki z zapytania, a wygląda na to, że w niej jest problem. Możesz ją podać?
Poza tym jeśli ją poprawisz wyrzuci ci błąd, bo masz niepoprawne lineItemsId. Pobierzesz je za pomocą GET /order/checkout-forms .

**Comment by nukotel** [comment]
⁣Wysłano z Blue ​

W dniu 22.03.2019, 13:14, o 13:14, użytkownik MartaNowaczyk <notifications@github.com> napisał:

**Comment by nukotel** [comment]
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/727938977/shipments

**Comment by MartaNowaczyk** [comment]
Na początek upewnij się czy  nie mieszasz produkcji z sandboxem, a potem zmień jeszcze to 727938977 na poprawny chckoutForm.Id (GET /order/checkout-forms)
