### ISSUE TITLE
[sandbox] przypomnienie hasła

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#1397]
Jest jakiś problem z przypomnieniem hasła na allegro.sandbox.pl

Cały czas przy próbie ustawienia nowego hasła wyskakuje Twój link stracił ważność nawet po kolejnych próbach przypomnienia.

Można prosić o reset hasła dla konta TestTiO ?

**Comment by MartaNowaczyk** [comment]
Nie mamy ręcznego resetu hasła na sandboxie. Poza tym bez problemu zmieniłam hasło za pomocą  odnośnika "nie pamiętasz hasła". Link w wysłanej wiadomości wyświetlił poprawnie stronę do zmiany hasła + z jego zmianą też nie było problemów. Czy problem nadal występuje?

**Comment by Cupik83** [comment]
Tak dalej wyskakuje ten sam komunikat: Twój link stracił ważność

W załączniku w mailu z przypomnieniem hasła klikam w link:
https://allegro.pl.allegrosandbox.pl/password-reminder/#/changePassword?hashCode=xxx

I pokazuje się formularz do zmiany hasła ale za każdym razem nie zmienia się hasło tylko wyskakuje komunikat jak wyżej.

**Comment by Cupik83** [comment]
Ok źle odczytany link z pliku .eml ... nie wiem czemu to jest wysyłane jako załącznik w każdym razie spróbowałem innym programem i zadziałało
