### ISSUE TITLE
UWAGA !! Zmiany w [doShowItemInfoExt] - znowu bez uprzedzenia !!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1398]
Po pierwsze - metoda zwraca nagle (na sesji sprzedawcy) ZERO w polu [itStartingTime] !!
Po drugie - miał być podany faktyczny termin wprowadzenia zmian przesuniętych z 18.03.2019, a tu nagle dzisiaj - każdy opis leci sobie (niezależnie od właściciela sesji) w sub-node [CDATA[ ... ]] !!!

**Comment by FromAnyHole** [comment]
Po trzecie - metoda [doGetItemsInfo] zwraca pole nowego opisu bez sub-node [CDATA[ ... ]] !!!

Pytanie dodatkowe - czy ktoś się tu autorytatywnie wypowie, że jak już w końcu wejdzie nowy sposób podawania treści opisów (bez ich encjowania), to metody WebAPI odpowiedzialne za wystawianie i edycję przedmiotów - będą oczekiwały jakiegoś nowego sposobu podawania danych w polu opisu (FID:341) ???

**Comment by MartaNowaczyk** [comment]
@FromAnyHole jak wdrożymy na 100% w obu metodach na pewno zmienię info w newsie.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - super, hiper, ale o tym co poniżej nie było ani słowa:
- metoda zwraca nagle (na sesji sprzedawcy) ZERO w polu [itStartingTime] !!

**Comment by MartaNowaczyk** [comment]
Nie zmenialiśmy nic w polu [itStartingTime]. Podaj id oferty z którą jest problem w tej kwestii.

**Comment by MartaNowaczyk** [comment]
> Pytanie dodatkowe - czy ktoś się tu autorytatywnie wypowie, że jak już w końcu wejdzie nowy sposób podawania treści opisów (bez ich encjowania), to metody WebAPI odpowiedzialne za wystawianie i edycję przedmiotów - będą oczekiwały jakiegoś nowego sposobu podawania danych w polu opisu (FID:341) ???

Możesz powiedzieć wprost, bo nie rozumiem o co ci chodzi.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - potwierdzam, nie na każdym koncie, ale jednak:
Z dwóch różnych kont podaję:
1) 6885779882: 1970-01-01 01:00:00 CET
2) 6740349111: 1970-01-01 01:00:00 CET

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - co do metod WebAPI obsługujących FID'a-341:
- czy nic się nie zmieni, no i zachowane będzie dotychczasowe encjowanie treści opisów ?
- czy dozwolona będzie wysyłka treści opisu w sub-node [CDATA[ ... ]] w wersji bez encji ?

**Comment by FromAnyHole** [comment]
6885779882: Ok !
6740349111: Ok !

**Comment by MartaNowaczyk** [comment]
@FromAnyHole w FIDzie 341 będzie tak jak dotychczas, nic nie zmieniamy w tym zakresie. CDATA bez encji powinna normalnie przejść.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - sprawdzone w weekend, no i na razie - w metodach WebAPI obsługujących FID'a-341 obsługiwane są obydwa scenariusze, oby tak pozostało i nic się nie zmieniło do końca ich życia ;-))
