### ISSUE TITLE
Wystawianie oferty - znaki w description?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1399]
Witam,
w jaki sposób mają być zakodowane znaki specjalne w części content ?
czy ma to być html entities czy może jak jest znak " to ma być zaprezentowany jako \"?

    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content":

**Comment by FromAnyHole** [comment]
Patrz - wątek wcześniej !!

**Comment by PawelTaberski** [comment]
@AleksyZajac W jaki sposób konstruować opis znajdziesz w [naszym poradniku ](https://developer.allegro.pl/sale/#step-5-description).
natomiast odnośnie znaków specjalnych musisz je zaencjować, tak jak podpowiada komunikat, jeśli tego nie zrobisz:
```
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "",
            "details": "",
            "path": "",
            "userMessage": "description.sections[0].items[0].content: In order to put & character into description use &amp; entity. Other allowed entities are: &nbsp; &quot; &amp; &apos; &lt; &gt; &#160;"
        }
    ]
}
```
Czyli np & przedstawiasz jako `&amp;`

**Comment by AleksyZajac** [comment]
Ok, wszystko jasne. Ale jak już jesteśmy w tej części to w jaki sposób mogę wymusić nową linię ?
Chciałbym uzyskać coś takiego:

Nowa odsłona jednej z najlepszych, jak nie najlepszej gitary klasycznej w swojej klasie cenowej. Yamaha C30M od wielu lat była jedną z najczęściej wybieranych instrumentów do nauki. Popularność zasłużona jak najbardziej bo jakość wykonania, brzmienie i komfort gry są po prostu bezkonkurencyjne. 

Yamaha C 30MII oferuje to samo wspaniałe brzmienie i ″grywalność″ co jej poprzedniczka. Instrument przyciąga uwagę nie tylko dźwiękiem, ale także eleganckim i klasycznym wyglądem. Matowe wykończenie doskonale koresponduje z ciemnymi bokami i gryfem.

Specyfikacja techniczna:
Praworęczna / Leworęczna: praworęczna
Rozmiar: 4/4 (powyżej 10 lat)
Płyta wierzchnia: świerk
Spód / boki: meranti

?

**Comment by PawelTaberski** [comment]
Wtedy że dasz w osobnych znacznikach <p></p> to będziesz miał w osobnej linii.
A do specyfikacji to możesz dodać listę wypunktowana np:
```
    <ul> 
        <li><b>Nulla eu justo ut velit pellentesque porta.</b></li> 
        <li>Pellentesque eget arcu id ligula consequat fermentum at nec velit. Maecenas vitae nunc 
        non ante aliquet facilisis nec id leo.</li> 
        <li>Sed vitae metus vel lorem iaculis rhoncus.</li> <li>Nullam nec felis felis.</li> 
    </ul> 
```

**Comment by AleksyZajac** [comment]
Dzięki wszystko jasne.
