### ISSUE TITLE
Sugestia. Możliwość symulacji płatności w Sandbox.

### ISSUE THREAD

**Issue by dtarczynski** [allegro/allegro-api#14]
Myślę, że w Sanboxie brakuje podstawowej funkcjonalności, a mianowicie symulacji płatności.
Widziałbym to tak, że użytkownik otrzymuje listę predefiniowanych sposobów płatności oraz przycisk 

- "Odpowiedź  pozytywna" 
- "Odpowiedź negatywna"

które symulowałaby płatność. Podobnie to wygląda na niektórych środowiskach testowych płatności internetowych (np. Dotpay).

**Comment by AniaMalinowska** [comment]
Dziękujemy za sugestię. Sandbox pozwala na [przeprowadzenie symulowanych płatności](https://webapisandbox.pl/) w systemie PayU. Zdajemy sobie jednak sprawę, że ta funkcjonalność nie zawsze działa. Już wkrótce udostępnimy nowe środowisko testowe, które powinno być wolne od tego problemu.

**Comment by gorgotluk** [comment]
Chciałbym zapytać kiedy mniej więcej będzie dostępne nowe środowisko testowe lub zostanie naprawiona zakładka MOJA SPRZEDAŻ (http://allegro.pl.webapisandbox.pl/myaccount/sell.php) w panelu sandboxa?

**Comment by AniaMalinowska** [comment]
Nowe środowisko testowe planujemy udostępnić w tym miesiącu. Na pewno o tym poinformujemy. 
Jeśli chodzi o niedogodności w Sandboxie, to prosimy o cierpliwość - weryfikujemy problemy.
