### ISSUE TITLE
Niebezpieczne linkowanie nowego Sandboxa

### ISSUE THREAD

**Issue by konradziczek** [allegro/allegro-api#140]
Nowy Sandbox miał być dopracowany, a znowu otrzymaliśmy towar marnej jakości. Już nie chce mi się pisać o niedochodzeniu linków aktywacyjnych, białych stronach na co trzecim przedmiocie po kliknięciu na Kup teraz i innych podobnych historiach.

Jest istotniejsza sprawa, która występowała również na starym Sandboxie i nadal nie została naprawiona. Połowa linków w sandboxie kieruje do prawdziwego Allegro (!). Dzisiaj nieświadomie prawie sprezentowałem sobie laptopa za 20 tysięcy bo podkategorie w elektronice są podpięte do prawdziwego Allegro, po każdym najdrobniejszym kroku trzeba sprawdzać url na górze przeglądarki, żeby nie wpakować się w problemy. Czy wy jesteście poważni? Nawet zakładając, że od strony backendu nie możecie podmienić domeny, to tak ciężko dodać jakiś JS który globalnie wykryje na stronie linkowanie do prawdziwego Allegro i je zablokuje?

**Comment by rtnet-pl** [comment]
https://github.com/allegro/allegro-api/issues/91#issuecomment-379699804

**Comment by PawelTaberski** [comment]
Tak, jak w wyżej wspomnianym wątku. Wiemy o tym problemie i pracujemy nad usunięciem tego.
