### ISSUE TITLE
Witam, bład od rana jaki mi wyświetla przy próbie pobrania sprzedaży: Błąd - doGetBidItem2 ERR_INVALID_ITEM_ID: Niepoprawny identyfikator oferty lub wskazana oferta została przeniesiona do archiwum.

### ISSUE THREAD

**Issue by AlekKlepacz** [allegro/allegro-api#1400]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ x] inny

:beetle: **Opis**

**Comment by AlekKlepacz** [comment]
Od rana.
Błąd - doGetBidItem2
ERR_INVALID_ITEM_ID: Niepoprawny identyfikator oferty lub wskazana oferta została przeniesiona do archiwum.

**Comment by PawelTaberski** [comment]
Sprawdziłem i metoda działa prawidłowo. podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1400 ma GitHub-ie.

**Comment by AlekKlepacz** [comment]
dzięki. ale komunikacja mojego sklepu nie opiera się na xml tylko bezpośrednio. Jakie dane wam podesłać klucz i IP?

**Comment by PawelTaberski** [comment]
W takim wypadku podeślij proszę id usera na jaki masz identyfikator sesji, numer oferty jaki chcesz sprawdzić w tej metodzie i klucz na jakim działasz.

**Comment by AlekKlepacz** [comment]
wysyłałem przez formularz. A zapytanie dotyczy wszystkich ofert jakie mam.

**Comment by PawelTaberski** [comment]
Sprawdziłem i metoda działa jak najbardziej poprawnie a w polu itemId nie podajesz czasem zamiast id oferty sygnatury?

**Comment by AlekKlepacz** [comment]
W sobotę problem ustał. Dziękuje za zajęcie się problemem. Pozdrawiam
