### ISSUE TITLE
Kilka pytań odnośnie końcowek w wersji BETA

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1401]
1. Czy zmiana końcówek z wersji BETA na PUBLIC będzie wcześniej ogłoszona?
2. Czy powyższa zmiana spowoduje, że od razu wersja BETA przestanie działać, czy będzie może okres przejściowy, gdzie obie wersje (chodzi o content-type [application/vnd...]), zarowno BETA, jak i PUBLIC będą działały?

Szczególnie interesują mnie poniższe końcówki:
GET order/checkout-forms/{id}
GET order/checkout-forms
GET order/events
GET sale/offers

**Comment by PawelTaberski** [comment]
Poinformujemy w dedykowanym komunikacie o dacie przejścia z bety na public i jak w przypadku zasobów do wystawiania ofert zamierzamy zastosować okres przejściowy, w którym to będziemy przyjmowali oba nagłówki.
