### ISSUE TITLE
Problem sieciowy

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1402]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Problem jest dość dziwny, w momencie wysyłania requestu, otrzymuję nagłówki i albo otrzymuję content albo nie i następuje "zwis" połączenia. Klient "sądzi" że jeszcze otrzyma jakieś dane i czeka (zapewne przez nagłówek `Transfer-Encoding: chunked` i brak nagłówka `Content-Length`). Występuje to losowo, po pierwszym requeście, po 3 po 24...

Po analizie ruchu sieciowego tcp, klient wysyła potwierdzenie odebrania (ack) ale już nie ma odpowiedzi z api (sprawdzałem dla różnych hostów api.allegro.pl). Taki "zwis" może trwać nawet 24 godziny - dłużej nie sprawdzałem - aplikacja czeka po prostu na odpowiedź.

Ten sam kod działa bez problemu na innym serwerze, co ciekawe, jak uruchomię aplikację przez socks proxy na innym serwerze, to działa wszystko prawidłowo.

Więc raczej jakieś błędy w bibliotekach odpadają. Problem na pewno dotyczy połączeń stricto z mojego głównego serwera, ale chciałbym abyście zobaczyli to ze swojej strony.
Doślę za chwilę w formularzu adresy ip z których mam takie problemy.

przykładowy Trace-Id: 54c911b10c3a05f2

**Comment by rtnet-pl** [comment]
Ja natrafiłem na takie problemy, rozwiązaniem okazało się ustawienie httpWebRequest.KeepAlive = false;

**Comment by mindc** [comment]
@rtnet-pl 
Od tego zacząłem, czyli dodanie `Connection: close`, a także `CURLOPT_FORBID_REUSE => 1` i `CURLOPT_FRESH_CONNECT => 1`

podsumowanie testów z proxy:
serwer produkcyjny => allegro = zwis
serwer produkcyjny => proxy (serwer testowy) => allegro = prawidłowo
serwer testowy => allegro = prawidłowo
serwer testowy => proxy (serwer produkcyjny) => allegro = zwis

więc ewidentnie coś nie tak jest z serwerem produkcyjnym na poziomie sieciowym.
Być może przyczyna błędu jest taka sama jak w #1102 , gdzie także miałem dziwne problemy sieciowe i otrzymywałem jedynie nagłówki bez contentu (problem zniknął samoistnie po kilku dniach)

**Comment by MartaNowaczyk** [comment]
@mindc dzięki za IP. Jak sprawdzimy, dam znać.

**Comment by pietrach** [comment]
To chyba jest to samo co miałem prawie 2 miesiące temu. Ten sam problem:

#1121

**Comment by mindc** [comment]
@pietrach 
Potwierdzam, u Ciebie zachowywało się to dokładnie tak jak u mnie - tylko u mnie na zasobie `GET /offers/listing`.

Po dokładnym sprawdzeniu wszelkich możliwości przyczyn problemu i sprawdzeniu ruchu sieciowego, zauważyłem, że któraś tam z ramek ACK wysyłana przy odbieraniu danych nie dociera do Allegro, wtedy Allegro oczywiście nie wiem co z nami i czeka na potwierdzenie, połączenie wisi...

Po dalszych testach okazało się, że dzieje się tak tylko na serwerach umieszczonych w Roubaix we Francji z innych lokalizacji wygląda to prawidłowo.

Zgłosiliśmy to do supportu naszego dostawcy.

**Comment by MartaNowaczyk** [comment]
Daj znać czy udało się wyjaśnić ten problem.

**Comment by pietrach** [comment]
Ja miałem z tym problem na serwerze home.pl a na OVH nie. Po zgłoszeniu do home.pl problem został naprawiony po jakichś 3 tygodniach ale oni twierdzili, że nic nie poprawili i to Allegro musiało coś poprawić po swojej stronie i teraz OK. Ale nie wiem komu wierzyć :-)

**Comment by mindc** [comment]
@MartaNowaczyk 
Awaria zniknełą kilka minut przed odpowiedzią od supportu. Nie przyznali się do niczego, chcieli albo dane z traceroute albo listingi mtr i to w dwie strony. Jestem ciekaw czy zrobilibyście (Allegro) dla mnie takie zestawienia :)

Prawdopodobnie zrestartowali jakiegoś problematycznego switcha i odpisali...

Dzięki za pomoc.
