### ISSUE TITLE
Wiadomość od kupującego

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1403]
Witam, mam pytanie jak za pomoca rest api pobrac wiadomosc od kupujacego.

Wiem ze jest ona w /order/checkout-forms, ale jak biore checkoutForm_id z eventu i pobieram dane zamowienia z /order/checkout-forms/checkoutForm_id a tam juz nie ma wiadomosci :/

**Comment by PawelTaberski** [comment]
Przetestowałem i wiadomość jest widoczna w zasobie GET /order/checkout-forms jak i GET /order/checkout-forms/{id}
Jeśli w Twoim wypadku tak nie jest, to podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa z obu metod wraz z trace-id. Sprawdzimy w czym jest problem.
W zgłoszeniu zaznacz, ze dane są potrzebne do ticketa numer 1403 na GitHub-ie.

**Comment by mskiba03** [comment]
Ok, ja tez sprawdzilem i jest widoczna, po prostu w dokumentacji nie bylo i myslalem ze nie ma ;) Dzieki

**Comment by PawelTaberski** [comment]
Jeśli chodzi Tobie o poradnik to przykładowa transakcja w zasobie GET /order/checkout-forms/{id} akurat nie ma informacji, a jeśli chodzi o dokumentacje wszystkich zasobów, to w przykładowym responsie jest [widoczne takie pole.](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)
