### ISSUE TITLE
doGetPostBuyData - błąd wywołania - Wewnętrzny błąd systemu

### ISSUE THREAD

**Issue by karolus888** [allegro/allegro-api#1404]
Witam,

Od wczoraj (24.03), od godziny 19 zaczął się pojawiać Wewnętrzny błąd systemu przy próbie wywołania zasobu doGetPostBuyData.

Problem dotyczy środowiska produkcyjnego.

Problem występuje dla wielu kont Allegro / użytkowników. Proszę o pilne wyjaśnienie przyczyn jego występowania.

Pozdrawiam,
Karol Sikora

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda działa poprawnie. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego pełnego requesta i responsa w formacie XML w którym napotkałeś na taki błąd. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane potrzebne są do ticketa numer 1404 na GitHub-ie.

**Comment by NorthonPomocny** [comment]
Witam serdecznie 
Mamy ten sam problem od 23 marca

**Comment by PawelTaberski** [comment]
@NorthonPomocny Podeślij również dane o których wspominałem powyżej przez nasz formularz, sprawdzimy to.

**Comment by neldh** [comment]
Także mamy ten sam problem od 22 marca

**Comment by PawelTaberski** [comment]
@neldh Rozumiem, jeśli to duży problem, to tak podeślij id ofert, na których masz problem.

**Comment by SoDaUser** [comment]
doGetPostBuyData 

Miałem ten problem kilka dni temu, wydawało się, że faktycznie wywala na konkretnych aukcjach.
Ale:
- od zawsze wywołanie miałem w postaci:  ser.doGetPostBuyData(sessionId, lista,  null)  
czyli nie było to najtrafniejsze rozwiązanie i aukcja, która wywalała miała dużą sprzedaż, inne przechodziły

Problem rozwiązałem poprawiając kod i dodając listę kupujących na której mi zależy: 
 ser.doGetPostBuyData(sessionId, lista1,  lista2)  

do dzisiaj działa :)

BTW notuję jeszcze jakiś problem z pustymi danym UserData problem też wystąpił pierwszy raz 22 marca ale jest sporadyczny choć odnotowałem go już kilka razy

**Comment by karolus888** [comment]
> doGetPostBuyData
> 
> Miałem ten problem kilka dni temu, wydawało się, że faktycznie wywala na konkretnych aukcjach.
> Ale:
> 
> * od zawsze wywołanie miałem w postaci:  ser.doGetPostBuyData(sessionId, lista,  null)
>   czyli nie było to najtrafniejsze rozwiązanie i aukcja, która wywalała miała dużą sprzedaż, inne przechodziły
> 
> Problem rozwiązałem poprawiając kod i dodając listę kupujących na której mi zależy:
> ser.doGetPostBuyData(sessionId, lista1, lista2)
> 
> do dzisiaj działa :)
> 
> BTW notuję jeszcze jakiś problem z pustymi danym UserData problem też wystąpił pierwszy raz 22 marca ale jest sporadyczny choć odnotowałem go już kilka razy

Dzięki za podpowiedź, właśnie testuję czy ograniczenie wywołania na określonych użytkowników rozwiąże mój problem.

**Comment by neldh** [comment]
Tak - to rozwiązuje problem. Niemniej jednak prosiłbym o rozwiązanie po stronie Allegro. Najwyraźniej macie problem z brakiem pamięci.

**Comment by SoDaUser** [comment]
Poszła na haszowanie adresów email :)

**Comment by neldh** [comment]
Jednak rozwiązanie nie jest ostateczne - nadal wystepują sporadyczne problemy

**Comment by PawelTaberski** [comment]
Otrzymałem dane i rzeczywiście jest błąd zapewne spowodowany zbyt dużą ilością danych. Sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by neldh** [comment]
Jeszcze tylko dodam, że po zastosowaniu obejścia, jak wspomniałem, dalej trafiał się błąd (choć już rzadziej), ale ponowna próba zakończyła się już pomyślnie.

**Comment by damianz5** [comment]
mam taki sam problem, ostatnie poprawne pobranie danych było 2019-03-22 15:50:00
dane request/response przesłane w zgłoszeniu nr 04990828

**Comment by Onixarts** [comment]
Ten sam błąd w losowych momentach przy wywołaniu  doGetCatsDataLimit

```<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:webapi="https://webapi.allegro.pl/service.php">
	<SOAP-ENV:Body>
		<webapi:DoGetCatsDataLimitRequest>
			<webapi:countryId>1</webapi:countryId>
			<webapi:localVersion>1553564665</webapi:localVersion>
			<webapi:webapiKey>*************************</webapi:webapiKey>
			<webapi:offset>21</webapi:offset>
			<webapi:packageElement>50</webapi:packageElement>
		</webapi:DoGetCatsDataLimitRequest>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
	<SOAP-ENV:Header/>
	<SOAP-ENV:Body>
		<SOAP-ENV:Fault>
			<faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode>
			<faultstring>Wewnętrzny bład systemu.</faultstring>
			<faultactor>Internal System Error.</faultactor>
		</SOAP-ENV:Fault>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>```

Zaraz klienci zaczną pisać!

**Comment by magik092** [comment]
U nas nadal co chwilę dostajemy błędy wewnętrzne i błędy nagłówków (Error Fetching http headers).
Nie możemy przez te problemy obsługiwać zakupów ...

**Comment by SebastianOzdoba** [comment]
U nas to samo, jak jeszcze wczoraj występowało 1 na 100 przypadków to dziś leci seryjnie na różnych kontach naszych Klientów
2019-03-26 10:12:59.627	-1	Wewnętrzny bład systemu.
2019-03-26 10:12:33.057	-1	Wewnętrzny bład systemu.
2019-03-26 10:12:14.580	-1	Wewnętrzny bład systemu.
2019-03-26 10:11:48.410	-1	The operation has timed out
2019-03-26 10:11:23.877	-1	Wewnętrzny bład systemu.
pobieranie ofert, pobieranie transakcji
Więcej problemów zaczęło się dokładniej od : 2019-03-26 08:19:30.143- Wewnętrzny bład systemu.

**Comment by MartaNowaczyk** [comment]
@SebastianOzdob jakie metody? Tylko webAPI czy REST API też?

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk 
webAPI -najpierw: doGetSiteJournal, potem na podstawie dzienników: doGetItemsInfo
błąd leci na doGetItemsInfo
Natomiast wygląda na to że u nas samoczynnie ustąpiło o 11:29, od tego czasu nie ma błędów

**Comment by MartaNowaczyk** [comment]
@SebastianOzdoba rozumiem, że u ciebie problem wcale nie dotyczył metody doGetPostBuyData?

**Comment by SebastianOzdoba** [comment]
Dokładnie tak, chociaż zastrzegam że wszystkich logów nie weryfikowałem

**Comment by MartaNowaczyk** [comment]
@karolus888 jak u ciebie z problemem doGetPostByData?

**Comment by karolus888** [comment]
Obszedłem go przez wywoływanie metody pojedynczo dla każdego userId. Błąd póki co nie występuje, ale rozwiązaniu daleko do optymalnego

**Comment by magik092** [comment]
Dopowiadając - z naszej strony widzimy że sytuacja wygląda na opanowaną - metody doGetSiteJournal, doGetPostBuyData, doGetSiteJournalDeals (i ogólnie WebAPI) przestało sypać błędami.
Wygląda na to, że już po burzy

**Comment by PawelTaberski** [comment]
W przypadku gdyby jednak błędy się znów pojawiały zalecam w metodzie doGetPostBuyData odpytać o konkretnych userów.
