### ISSUE TITLE
Powtarzające się ID

### ISSUE THREAD

**Issue by KTKPolska** [allegro/allegro-api#1405]
Witam,

Czy to możliwe, żeby "journal start" w metodzie doGetSiteJournalDeals() się powtórzyło?

Taka sytuacja miała u mnie miejsce już 3x, tzn w przeciągu kilku/nastu dni w wyniku powyższego zapytania dostałem "dealEventId" które już wcześniej miałem zapisane w bazie, przypisane do zupełnie innego klienta nawet z innym produktem.

Czy pole "dealEventId" jest unikalne?

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) dane, które są zapisane z tym samym dealEventId sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1405 na GitHub-ie.
