### ISSUE TITLE
[REST API] W jaki sposób mogę pobrać informacje o konkretnej ofercie 

### ISSUE THREAD

**Issue by robert0770** [allegro/allegro-api#1406]
W jaki sposób mogę pobrać informacje o konkretnej ofercie mając ID tej oferty w REST API allegro?

**Comment by PawelTaberski** [comment]
Wystarczy, że skorzystasz z metody GET sale/offers/{offerId} więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/my_offers/).

**Comment by robert0770** [comment]
Tylko że mi zależy na tym aby pobrać informacje o nie swojej ofercie (tak jak w przypadku ShowItemInfoExt w webapi)
do tej pory korzystałem z webapi ale 1 kwietnia nie będzie metody doGetItemsList więc chce przejść w całości do REST API,

rozumiem że nie jest to możliwe na ten moment? i muszę korzystać z rest + web api?

**Comment by PawelTaberski** [comment]
Zamiast korzystać z doGetItemsList udostępniliśmy zasób do wyszukiwania i przeglądania ofert przez REST API GET /offers/listing który opisaliśmy szerzej w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by robert0770** [comment]
Przecież sam o tym wyżej napisałem.
Nie dostałem odpowiedzi nadal na moje pytanie.
Czy w REST API mogę pobrać informacja o ofercie po jego ID? (oferta o tym ID nie koniecznie musi być moją oferta)

**Comment by PawelTaberski** [comment]
Pisałeś o usunięciu doGetItemsList i w jego miejsce jest inna metoda w REST API odnośnie pobrania publicznych danych o nie swojej ofercie, to pracujemy jeszcze nad takim zasobem i obecnie nie ma go w REST API.

**Comment by krekhovetskyi** [comment]
I also interested in this possibility for get offer detail information by offer id in case if I am not a owner of this offer. when it is going to be implemented in REST API, any time estimation?

**Comment by robert0770** [comment]
ok, bardziej chodziło mi o to że z tym się już zapoznałem i raczej jest to powód dlaczego potrzebuje odpowiednika ShowItemInfoExt  w REST API.
Dzięki za info, czyli jak na razie bez korzystania z 2 kanałów API się nie obejdzie.

Wiadomo kiedy mniej więcej taka metoda w REST dojdzie? kwestia dni/tygodni/miesięcy?

**Comment by PawelTaberski** [comment]
@krekhovetskyi We are working on resource in REST API to get public data about the offer but I don't know exact time. When I will have that information we will inform about this in the appropriate message.

@robert0770 Pracujemy nad takim zasobem, ale obecnie nie mam informacji kiedy będzie wdrożony. Jak tylko będziemy mieli takie informacje na pewno poinformujemy o tym w dedykowanym komunikacie.

**Comment by akustra** [comment]
@PawelTaberski A czy jest jakiś sposób, aby pobrać chociaż podstawowe dane o ofercie po id np. opis albo parametry?

**Comment by PawelTaberski** [comment]
Obecnie przez REST API możesz pobrać po id informacje tylko o swojej ofercie zasobem sale/offers/{offerId}. Podstawowe informacje o ofertach, które nie należą do ciebie możesz pobrać zasobem /offers/listing który odzwierciedla możliwości wyszukiwarki na froncie, ale nie posiada wyszukiwania po id oferty. Więcej o możliwościach tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/listing/).

**Comment by qls-api** [comment]
Czy w REST API  jest możliwość uzyskania informacji dla własnej oferty typu licytacja o ilości złożonych ofert, odpowiednik pola itBidCount dla metody doShowItemInfoExt

**Comment by PawelTaberski** [comment]
Obecnie w zasobie offers/listing jest pole popularity:
```
                    "popularity": 0                 -- popularność oferty. W przypadku oferty
                                                    typu BUY_NOW jest to liczba zakupów od 
                                                    unikalnych użytkowników z ostatnich 
                                                    30 dni. W przypadku oferty typu AUCTION 
                                                    jest to liczba użytkowników, 
                                                    którzy biorą udział w licytacji. 
```
To jedyne co jest bliskie temu o co pytasz, wiemy o takich brakach i pracujemy nad nimi i staramy się systematycznie rozbudowywać ilość zasobów w REST API.

**Comment by qls-api** [comment]
W dokumentacji zasobu offers/listing nie doszukałem  nie znalazłem filtru  aby wyszukać ofertę na podstawie jej numeru. Czy coś przeoczyłem ?

**Comment by PawelTaberski** [comment]
Nie w tym zasobie nie ma możliwości wyszukiwania po id oferty, więcej na temat jego możliwości znajdziesz [tutaj](https://developer.allegro.pl/listing/).

**Comment by aktywnitu** [comment]
Skoro nie ma zamiennika, to po co wyłączanie metodę doGetItemsList?
Czy jest jakaś inna metoda w webapi, która pozawala pobrać szczegóły publicznej oferty po ID?

**Comment by qls-api** [comment]
Czyli nic nie przeoczyłem. A czy informację jaką szukam nie uzyskam z pola sellingMode-> bidCount ?
Tak na marginesie oba pola mogłyby być uzupełniane na zasobie sale/offers/

**Comment by PawelTaberski** [comment]
Jeśli mówimy o swoich ofertach to możesz jeszcze skorzystać własnie z zasobu sale/offers znajdziesz tam pole:
`"biddersCount": 0             -- liczba osób licytujących`
