### ISSUE TITLE
aktywacja sprzedazy i przelewy24

### ISSUE THREAD

**Issue by bartkovek** [allegro/allegro-api#1407]
witam, czy moglbym prosic o aktywacje sprzedazy i uslugi przelewy24 na moim koncie? czekam juz wiecej niz 3 dni a chcialbym miec mozliwosc sprzedawania rzeczy.

login: bartkovek

**Comment by PawelTaberski** [comment]
Tutaj zajmujemy się tylko problemami związanymi z API Allegro w tej sprawie napisz proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=86e88a9d-ecb9-4cbf-b103-de466d010d1b&kategoria=4b9531bc-1c7f-488f-9b10-4a7888ea5bdf).

**Comment by neldh** [comment]
@bartkovek pewnie chodzi o aktywacje konta na sandboxie

**Comment by PawelTaberski** [comment]
@neldh Nie bo nie ma na sandboxie konta o takim loginie - też tak początkowo pomyślałem :-)
