### ISSUE TITLE
[ERR_INTERNAL_SYSTEM_ERROR] doGetPostBuyData

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#1410]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym

Od piątku występuje problem z wybranymi aukcjami. Dostajemy już z tym w głowę. Pobierając dziennik dostajemy id aukcji, po czym podajemy to id po to, aby odebrać dane nabywcy (tylko nie mówcie, że tak się tego nie robi, albo, ze mam to robić w REST API - robimy to od wielu lat i to działało od zawsze i zawsze - jak przyjdzie termin na REST będzie REST, póki co niech to działa). Do sedna. Kiedy odpytujemy o dowolną naszą aukcję na której jest sprzedaż dostajemy w odpowiedzi dane o sprzedaży (nabywcach). Brawo!
```
	$dupa=array('7904970425');
	$kom2 = $client->doGetPostBuyData($session['session-handle-part'],$dupa);
```
w odpowiedzi:
```
Array
(
    [0] => stdClass Object
        (
            [item-id] => 7904970425
            [users-post-buy-data] => Array
                (
                    [0] => stdClass Object
                        (
                            [user-data] => stdClass Object
                                (
                                    [user-id] => 21123649
                                    [user-login] => xxxxxxxxxx
                                    [user-rating] => 0
                                    [user-first-name] => Dawid
                                    [user-last-name] => xxxxxxxxxx
[...]itd
```
Wszystko pięknie do momentu, gdy odpytamy o aukcję: 5237785773. Wówczas to samo pytanie w tym samym skrypcie i w tym samym pliku, odpalone z tego samego serwera z tym samym IP...
```
	$dupa=array('5237785773');
	$kom2 = $client->doGetPostBuyData($session['session-handle-part'],$dupa);
```
Powoduje, że w catch(SoapFault) dostajemy:
`SoapFault exception: [ERR_INTERNAL_SYSTEM_ERROR] Internal system error in /home/tomek/skrypty/dziennik2.php:78 Stack trace: #0 /home/tomek/skrypty/dziennik2.php(78): SoapClient->__call('doGetPostBuyDat...', Array) #1 /home/tomek/skrypty/dziennik2.php(78): WebAPISoapClient->doGetPostBuyData('a3aa9e9c8a64d4e...', Array) #2 {main} `

No i to koniec historii. Takich aukcji jest kilka. Na kilkanaście tysięcy jest ich kilka. Nie jest to duże pocieszenie, bo całą zabawę szlag trafia, bo dziennik staje. Odbieramy go na takiej zasadzie, że po przerobieniu danego row-id insertujemy id tego rekordu u siebie w bazie i w pętli wywoływany jest kolejny rekord od miejsca >row-id to chyba normalne. Ale skoro wpada nam taki babol w catch no to cały skrypt wpizd*&)^& i cały misterny plan też wpizd)*(&&*%. Musimy wtedy pomijać ręcznie w bazie wpisując, że ten felerny rekord na którym wyskoczył babol już niby przeszedł i wtedy nie mamy sprzedaży tej jednej pozycji, a dziewczyny w handlowym dostają kurwicy od piątku bo ręcznie muszą wyłapywać braki w sprzedaży... Proszę pomóżcie drodzy informatycy i sprawdźcie co się spierd(&%^* z tymi aukcjami, bo to ewidentnie jest babol tej (i kilku innych) konkretnej aukcji. Jako ciekawostka gdy podam nieistniejący item-id np. "dupa" dostaję pustą strukturę. Gdy podam nie swój item-id też dostaję jakieś tam dane. A gdy podam ten jeden numer aukcji - INTERNAL SYSTEM ERROR... HELP!

**Comment by SoDaUser** [comment]
Ten sam temat:  https://github.com/allegro/allegro-api/issues/1404#issuecomment-476195427

**Comment by partyumarty** [comment]
Dzięki, ale czy mógłby ktoś się tym zająć ? Lista aukcji wciąż rośnie. Robi się jakaś masakra... 5208409920

**Comment by MartaNowaczyk** [comment]
Sprawa jest w trakcie weryfikacji, także proszę o jeszcze trochę cierpliwości. 
Oczywiście wszelkie informacje o nasilaniu się, bądź poprawie są jak najbardziej mile widziane.

**Comment by partyumarty** [comment]
Fajnie, że ktoś się tym interesuje. Nie chce robić burzy w szklance wody tylko od razu nasuwa się pytanie... kto zapłaci za dosyłanie produktów od aukcji z błędami, które się nie importują... nasz handlowy nie wszystkie przypadki wyłapał i już pojawiły się pierwsze maile z informacjami o brakach w paczce - zgodne z prawdą bo chodzi o produkty do wysypanych aukcji opisanych wyżej wymienionym problemem :(

**Comment by vitapak** [comment]
> Sprawa jest w trakcie weryfikacji, także proszę o jeszcze trochę cierpliwości.
> Oczywiście wszelkie informacje o nasilaniu się, bądź poprawie są jak najbardziej mile widziane.

Przed momentem wysłałem do Państwa mailowe zgłoszenie, nr 04998911.

**Comment by MartaNowaczyk** [comment]
Doraźnie na ten moment może pomóc ograniczenie pobierania danych do danego kupującego.

**Comment by partyumarty** [comment]
Doraźnie informuję, ze problem wciąż występuje i jest coraz bardziej irytujący. Kolejna problematyczna aukcja: 5213699295

**Comment by MartaNowaczyk** [comment]
@partyumarty dzieje się tak w ofertach, w których jest bardzo dużo zakupów, stąd zalecamy użycie filtra i ograniczenie pobieranych danych.
