### ISSUE TITLE
Pytanie o GET /offers/listing

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1411]
Witam,
Czy wynik zwracany przez GET /offers/listing podlega jakimś "remarketingom" czy innym personalizacjom listy zwracanych ofert. Czy zależy ona od użytych kluczy aplikacji lub konta allegrowego, które pyta? Czy jest identyczny bez względu na to kto zapyta?
KF

**Comment by PawelTaberski** [comment]
Ta metoda odzwierciedla wyszukiwarkę na froncie, odnośnie Twojego pytania wyniki bez względu na klucz jaki używasz powinny być takie same.

**Comment by grzegorzjj** [comment]
Warto wspomnieć, że zwracane są najpierw itemy 'promoted' , a potem 'regular' . Jak w wyszukiwarce na froncie.

**Comment by walik92** [comment]
Witam, czy jest możliwość pobrania wszystkich dostępnych opcji dla filtrów? Zauważyłem że np. filtr stan przedmiotu zawiera opcje tylko te która mają oferty. Np dla kategorii [kategoria](https://allegro.pl/kategoria/land-rover-range-rover-evoque-110832) w filtrze stan mamy tylko jedną opcję -> używane, natomiast przechodząc do wystawiania oferty w tej samej kategorii, filtr stan zawiera więcej opcji. Dla niektórych filtrów np. kolor samochodu zwracane są wszystkie opcje, nawet te które nie posiadają ofert. Są też rozbieżności w filtrze rodzaj oferty, np. dla powyższej kategorii wystawiając ofertę mamy tylko opcję ogłoszenie natomiast w filtrze przy wyszukiwaniu mamy 2 opcje (licytacja i kup teraz). Czy te rozbieżności są celowo zastosowane? Czy można liczyć na uporządkowanie tego w najbliższym czasie?

**Comment by walik92** [comment]
Tak rozumiem, że nie ma metody do pobrania wszystkich filtrów oraz że są zależne od kategorii. Moje pytanie jest takie, dlaczego lista dostępnych opcji w filtrach jest zależna od listy ofert? Np. w dwóch sąsiednich kategoriach (z tym samym rodzicem) mamy różne opcje dla filtra STAN.

**Comment by PawelTaberski** [comment]
Wynika to m.in. z innych dostępnych w danej kategorii parametrów.

**Comment by tomeatoes** [comment]
podłączę się - czy tą metodą offers/listing zwrócę wszystkie oferty czy tylko część? Mam wrażenie, żę zwraca to tylko cześć ID.... bo nieustannie pojawiają się duplikaty nawet jak dodam &sort=+endTime czy mam rację??

**Comment by PawelTaberski** [comment]
Obecnie zasób może nie zwracać wszystkich ofert jeśli te są połączone w warianty z innymi ofertami. Już pracujemy nad tym problemem.
Sprawdź proszę, czy w Twoim wypadku właśnie to nie jest problemem.
