### ISSUE TITLE
oAuth authorizaction_code i device_code WebApi -> RestApi

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1412]
Dzień dobry, proszę o pomoc jak można zrealizować automatyczną i transparentną dla użytkowników migrację autoryzacji z WebApi do RESTapi oAuth tysięcy kont allegro posiadając login i hasło dotychczas używane w WebApi?

Upatrywałem szansy na taką migrację w wykorzystaniu device_code do pobrania tokenów loginem i hasłem jednak nie można zarejestrować aplikacji, aby jednocześnie używać device_code do migracji i authorizaction_code do zakładania nowych kont przez użytkowników.

**Comment by PawelTaberski** [comment]
Nie do końca rozumiem Twoje pytanie. Jeśli dobrze rozumiem o co chodzi to, aby korzystać z zasobów na REST musisz przejść każdym userem ścieżkę device lub code flow, które opisaliśmy [tutaj](https://developer.allegro.pl/auth/). Później dzięki access tokenowi na danego usera możesz dzięki metodzie [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582) korzystać z zasobów w WebAPI. I teraz nie bardzo rozumiem co masz na myśli z jednoczesnym korzystaniem? Jeśli user zakłada nowe konto na allegro musi przejść ścieżkę i się uwierzytelnić i dać dostęp do Twojej aplikacji. Klucz do aplikacji powinien być jeden na Twoim koncie i powinieneś do niego podpiąć swoich userów. Każdy user nie powinien na swoim koncie tworzyć nowego klucza.

**Comment by alekskuc** [comment]
Faktycznie każdy user musi jawnie przejść ścieżkę device lub code flow. To co miałem na myśli to było password credentials flow https://tools.ietf.org/html/rfc6749#section-1.3.3 gdzie login i hasło można wymienić bezpośrednio na token bez konieczności udziału użytkowników, którzy już wcześniej podali hasło do WebAPI.

Tak jak istnieje wspominania metoda łącząca oba API doLoginWithAccessToken mogła by funkcjonować odwrotna metoda w WebAPI zwracająca token RestAPI żeby ułatwić migrację i zapewnić ciągłość działania.

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości i nie przewidujemy wdrożenia takich rozwiązań .
