### ISSUE TITLE
PUT /sale/offers/{offerId} DELETE [images]

### ISSUE THREAD

**Issue by bluesoftware** [allegro/allegro-api#1415]
W jaki sposób mogę skasować jakieś zdjęcie jak daje pusty [url] to mam błąd:

> Array
--
  | (
  | [errors] => Array
  | (
  | [0] => Array
  | (
  | [code] => VALIDATION_ERROR
  | [message] => Invalid image URL. Image must be present on allegro server.
  | [details] => Invalid value:
  | [path] => images[5].url
  | [userMessage] => Invalid image URL. Image must be present on allegro server.
  | )

**Comment by PawelTaberski** [comment]
Nie mamy zasobu do usuwania zdjęć, jeśli ich nie użyjesz same wygasną. Zgodnie z datą jaką otrzymujesz w responsie.

**Comment by bluesoftware** [comment]
Dziękuje za odpowiedź.
