### ISSUE TITLE
REST API GET /offers/listing - nick

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#1416]
Czy jest możliwość pobrania NICKA sprzedawcy z listingu wyszukiwarki ? Dzieki!

**Comment by FromAnyHole** [comment]
Dopóki istnieją w Allegro nazwy kont, to zawsze zadziała parsowanie z adresu, np.:
https://allegro.pl/uzytkownik/13390545/oceny
;-)

**Comment by PawelTaberski** [comment]
@Adam1610 Jeśli pytasz o zasób GET /offers/listing to tam zwracamy tylko id. Pracujemy nad zasobem w REST API, który zwróci publiczne dane o danym userze, obecnie możesz skorzystać z zasobu w WebAPI [doGetUserLogin](https://allegro.pl/webapi/documentation.php/show/id,104), aby na podstawie id pobrać login usera.

**Comment by Adam1610** [comment]
Chodzi właśnie o to by uniknąć już starego WebApi/parsowania url i uzyskać nazwę w Rest Api w wynikach wysxukiwania (tak bylo w starym webapi) lub odpowiednik metody doGetUserLogin w nowym RestApi. Jsk rozumiem na razie nie ma takiej mozliwosci, wiec nie ma innego wyjscia jak czekac.

**Comment by PawelTaberski** [comment]
Tak, obecnie jeszcze nie ma takiej możliwości, jak tylko będziemy wiedzieli kiedy wdrożymy takie rozwiązanie poinformujemy o tym w dedykowanym komunikacie.

**Comment by Adam1610** [comment]
Panowie, błagam - wprowaddźcie jak najszybciej aby oprócz numeru sprzedawcy REST api zwracało jego nick, podejrzewam że to banalna sprawa a technicy robią problem :)))  Zaproponowane rozwiązanie - użycie metody doGetUserLogin, to masakra :( spowalnia straszliwie wyniki wyszukiwania, gdy trzeba odpytywać każdy numer sprzedawcy starym webapi. Rozwiązanie to jest o wiele gorsze i przede wszytskim - wolne, niepotrzebnie obciąża serwer, itd.  Za chwilę ktoś się do mnie przyczepi (z Allegro) o nieoptymalne użycie api... szach - mat.

**Comment by PawelTaberski** [comment]
Wiemy o tym problemie i pracujemy nad metodą, która zwróci informacje o danym userze nie tylko jego login. Jak tylko będę miał dokładne informacje, kiedy wdrożymy taką metodę, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by painter10** [comment]
Czy są jakieś newsy w sprawie nazwy usera?
Metoda doGetUserLogin została wygaszona, a odpowiednika w REST API nie widać....

**Comment by PawelTaberski** [comment]
Dane użytkownika możesz pobrać przy pomocy zasobu /me ,więcej na ten temat znajdziesz tutaj: #2286

**Comment by Adam1610** [comment]
...ale chodzi nam o login dowolnego użytkownika o podanym numerze, a nie tylko swoje dane :)

**Comment by PawelTaberski** [comment]
Rozumiem, powiedz proszę do czego potrzebna jest Tobie taka funkcjonalność w aplikacji. Twoją sugestię oczywiście przekażę.

**Comment by Adam1610** [comment]
na przykład podczas analizy wyników wyszukwiania - mam ID sprzedającego, ale nie ma nazwy przez co funkcjonalność wyszukiwarki jest trochę upośledzona ;) póki są nazwy sprzedających na Allegro, myślę że API powinno także zapewniać taką opcję

**Comment by PawelTaberski** [comment]
@Adam1610 Dzięki za opis - sugestię przekazałem.

**Comment by grojanteam** [comment]
@PawelTaberski 
18 dni mija, zero odzewu w temacie

sugestia kolejna... jak na podstawie nicku dowolnego użytkownika poznać jego ID

do wyszukiwarki (request'u) 

https://developer.allegro.pl/documentation/#tag/Public-offer-information

potrzebny jest seller.id który nie może być podany jako login allegro dowolnego użytkownika, ale na podstawie loginu nie można rozpoznać jego ID... wyszukując na allegro po użytkowniku podajemy jego nick więc może fajnie byłoby gdyby działał filtr seller.id po ID jak i po loginie?

Sugestia jest taka, że albo dodać zasób do rozpoznania ID dowolnego usera po jego loginie, albo dodać możliwość użycia seller.id jako loginu allegro

**Comment by Adam1610** [comment]
Tak, bardzo przydała by się możliwość wyszukiwana w obie strony :  ID->login i login->ID.

**Comment by PawelTaberski** [comment]
Pracujemy już nad wdrożeniem loginu do zasobu GET /offers/listing. Jak wdrożymy taką zmianę poinformujemy o tym w odpowiednim komunikacie.
@grojanteam Sugestię odnośnie dodania wyszukiwania po login-ie sprzedawcy oczywiście przekażę.

**Comment by Adam1610** [comment]
Super, a kiedy orientacyjnie można się spodziewać tej fukncjonalności? tak Pi razy oko ;) tydzień, miesiąc, kwartał , rok ? :)

**Comment by PawelTaberski** [comment]
Niestety nie znam dokładnej daty wdrożenia, jak tylko wdrożymy taką możliwość to poinformujemy o tym.

**Comment by grojanteam** [comment]
Jak już wdrożycie to będzie elegancko :) przynajmniej zmienię u siebie tylko typ pola i wypuszczę aktualizację ! :)

Mam nadzieję, że sztab programistów ogarnie to szybko i sprawnie... 

Trzymam kciuki!

**Comment by Adam1610** [comment]
I jak, są może jakieś postępy w tej sprawie? :)

**Comment by PrzemyslawLukanowski** [comment]
@Adam1610 Na tę chwilę nie możemy przedstawić więcej szczegółow. Opublikujemy odpowiedni komunikat przy okazji wdrożenia.

**Comment by dzoudzou3** [comment]
Pojawiły się nowe informacje na temat uzyskiwania nazw sprzedawców???

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze nie, na pewno opublikujemy komunikat w tej kwestii.

**Comment by grojanteam** [comment]
Serio tak ciężko jest to wprowadzić? :D
