### ISSUE TITLE
Odpowiednik doSendRefundForm w REST API

### ISSUE THREAD

**Issue by sledz19** [allegro/allegro-api#1417]
Witam, zgodnie z tematem pytania czy jest odpowiednik w nowym API? Jeśli nie to czy przewidujecie wprowadzenie, jeśli tak to czy możliwe jest okreslenie ~kiedy?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej metody w REST API pracujemy nad wdrożeniem nowych metod, niestety nie mam informacji, kiedy dokładnie wdrożymy taki zasób. Jak tylko będziemy mieli konkretne informacje, to poinformujemy o tym w dedykowanym komunikacie.
