### ISSUE TITLE
Device flow dla Allegro OAuth - Różnica między Sandbox a Produkcyjną

### ISSUE THREAD

**Issue by Daczek** [allegro/allegro-api#1418]
Witam,
Chciałbym zapytać czy są jakieś różnice między wersją produkcyjną a wersją sandbox jeśli chodzi o powiązanie aplikacji (Autoryzacja użytkownika typu Device flow) - cały proces opisany tutaj: https://developer.allegro.pl/auth/#userDeviceFlow
Mam taki problem że na wersji sandbox działa to bez problemu - natomiast po zmianie na wersję produkcyjną identyczna metoda nie działa.
Oczywiście po zmianie na wersję produkcyjną zmieniłem:
const API_URI = 'https://api.allegro.pl/';
const TOKEN_URI = 'https://allegro.pl/auth/oauth/device/';
const AUTHORIZATION_URI = 'https://allegro.pl/auth/oauth/';
Dodałem nową aplikację tutaj (typ device): https://apps.developer.allegro.pl/
użyłem wygenerowanych tam client id i client secret

Krok "1,2/ Skorzystaj z zasobu POST https://allegro.pl/auth/oauth/device, aby otrzymać" 
działa bez problemu również na produkcyjnej - dostaję link do powiązania aplikacji w wersji produkcyjnej-> zatwierdam na swoim koncie allegro i w 'Powiązane aplikację' widzę że się udało.
Następnie korzystając z pozyskanego device_code przechodzę do tego:
"4b/ Równocześnie twoja aplikacja powinna zacząć odpytywać zasób:
POST https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}"
I właśnie w tym puncie otrzymuję błąd:
"file_get_contents(https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&amp;device_code=5(...)U): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request"

->Oczywiście (...) użyłem aby nie wyświetlać pełnego kodu ale dane te na pewno są takie jakie zwraca poprzednia funkcja.

Zaznaczam że wszystkie funkcje działają identycznie dla wersji sandbox jak i produkcyjnej (zmieniają się jedynie link i dane autoryzacyjne) - na sandbox wszystko działa. 
Na wersji produkcyjnej działa funkcja do pobrania linku do powiązania aplikacji - więc -H 'Authorization: Basic base64(clientId:secret)' też musi być prawidłowy. 

Bardzo proszę o pomoc w czym może być problem - czym może różnić się wersja sandbox od produkcyjnej.
Pozdrawiam serdecznie.

**Comment by PawelTaberski** [comment]
Sprawdź czy problemem nie jest to że zaencjowałeś znak &
Powinno być: Adevice_code&device_code=

**Comment by Daczek** [comment]
Przy zwrocie błędu rzeczywiście jest pokazana encja ale przy przesyłaniu jest ta znak & - czyli jest:
https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=5(...)U

**Comment by PawelTaberski** [comment]
Otrzymujesz może jakiś dokładny komunikat co jest powodem błędu chodzi mi o error_description.

**Comment by Daczek** [comment]
Niestety nawet po 'wyprintowaniu' całej tablicy z błędem nie ma nic istotnego poza tym właśnie błędem:
[message:protected] => file_get_contents(https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=w(...)H): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a z obu wywołań do otrzymania user_code i device_code oraz do uzyskania tokena wraz z pełnymi responsami. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1418 na GitHub-ie.

**Comment by Daczek** [comment]
Korzystałem z gotowych klas gdzie komunikacja odbywała się przez funkcję file_get_contents() (oczywiście używałem wcześniej stream_context_create aby przesłać nagłówki i pozostałe wymagane dane) która o dziwo działa wszędzie na wersji sandbox oraz na w każdym innym miejscu na produkcyjnym (przynajmniej tam gdzie teraz sprawdzałem) oprócz tej jednej jedynej https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=5(...)U

W każdym razie przerobiłem to na funkcje curl i działa. Nie spodziewałem się że to może być przyczyną skoro na sandbox działa ale widocznie są jakieś różnice między tymi wersjami - to tak informacyjnie dla potomnych jakby mieli podobne problemy :) 

Pozdrawiam.
