### ISSUE TITLE
Dostępne biblioteki PHP / Laravel / Composer ?

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#142]
Czy macie wiedzę czy jest jakaś gotowa biblioteka do allegro dostępna na PHP /Laravel ?

Sam mam napisanego wrapera na API, ale z uwagi że nie jestem zawodowym programistą nawet nie wiem jak stworzyć paczkę do composera, chętnie bym pouczestniczył nawet w jakimś projekcie opensource ale sam go nie ogarnę aby stworzyć własny i opublikować

**Comment by SoftSolid** [comment]
Można z tego skorzystać:
https://github.com/Wiatrogon/php-allegro-rest-api
Pozdrawiam
Robert.

**Comment by imper86** [comment]
@cieplik206 możesz też spróbować mojej biblioteki - https://github.com/imper86/allegroapi
Nie jest idealna i trochę pisana na prędce, ale działa ;)

**Comment by ircykk** [comment]
I ja dodam coś od siebie: https://github.com/ircykk/allegro-api
We wczesnym stadium ale będzie rozwijana.

**Comment by cieplik206** [comment]
written with PHP5??

**Comment by Bitnalstream** [comment]
@cieplik206 5 is an old, write with 7 :)

**Comment by ircykk** [comment]
I would like to write with 7 :) I had to keep compatibility for one of my projects.
