### ISSUE TITLE
Jak podpiąc formy płatności?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1421]
Witam,
jak podpiąć pod daną aukcję dane formy płatności?
Aktualnie mam sytuację że aukcja się wystawia ale w zakładce płatności nie mam żadnej formy.

Nie pojawia się nawet konto które jest zdefiniowane na koncie.

![platnosci](https://user-images.githubusercontent.com/39444659/55078241-fd377800-5099-11e9-8f8a-f199c5fb7a09.png)

**Comment by kfijalko** [comment]
Musisz zdefiniować cenniki dostaw i podpiąć pod oferty.
https://developer.allegro.pl/sale/#shipping-rates
