### ISSUE TITLE
Problem z zamykaniem ofert

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#1422]
Nie zamyka mi ofert przy pomocy metody "offer-publication-commands", wczoraj jeszcze wszystko działało. Wywołanie zwraca
`stdClass Object ( [id] => f13addaa-ba6f-4afd-a4e9-cbd4abc20004 [taskCount] => stdClass Object ( [total] => 0 [success] => 0 [failed] => 0 ) )`, a potem nic się nie dzieje. (oferta nr 7915569750).

Coś popsuliście?

**Comment by PawelTaberski** [comment]
Czy sprawdzałeś status zadania przy pomocy zasobu GET /sale/offer-publication-commands/{commandId}/tasks jaką odpowiedź otrzymujesz?
Przy wywołaniu PUT /sale/offer-publication-commands/{commandId} zawsze w responsie otrzymasz zestawienie z 0 to poprawny wynik, gdyż jeszcze nie wiadomo w momencie wysłania ile przeprocesuje się poprawnie a ile nie. Pełną informacje otrzymasz w zasobie do sprawdzania statusu zadania.

**Comment by holospl** [comment]
[offer] => stdClass Object ( [id] => 2147483647 ) [message] => Could not change offer publication status. [status] => FAIL [scheduledAt] => 2019-03-27T15:49:48.788+01:00 [finishedAt] => 2019-03-27T15:49:49.028+01:00 [field] => publication )

Nic mi to nie mówi, trochę takie "nie bo nie".

**Comment by holospl** [comment]
Dobra, już widzę, nie ma takiej oferty, złe id. Sam namieszałem, ale wstyd :D
