### ISSUE TITLE
Error Fetching http headers - tylko dla wybranych aukcji

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1423]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Metoda: `doGetItemsInfo`
Otrzymuję ten błąd tylko dla pewnych aukcji, są to zawsze te same aukcje (o.O)
Pomimo ponowień zapytań (nawet po 24 godzinach), mam ciągle ten sam błąd.
Pierwsza problematyczna aukcja pojawiła się 2019-03-26 11:55:59 (rowId w journalu 38319925666)
Przykładowe numery aukcji 5917307407, 6736932152, 5961740019, 6447655983

**Comment by PawelTaberski** [comment]
@mindc Przetestowałem i metoda działa poprawnie dla wszystkich ofert jakie podesłałeś otrzymałem prawidłowy wynik. Podeślij proszę pełnego requesta i responsa w formacie XML przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1423 na GitHub-ie. Sprawdzimy w czym jest problem.

**Comment by mindc** [comment]
@PawelTaberski 
Bardzo przepraszam, podałem nie tą metodę (rzadko zaglądam do tego kodu)
chodzi o metodę `doGetBidItem2`

**Comment by mindc** [comment]
@PawelTaberski 
Jeszcze znalazłem jeden trop. Zmieniłem wtedy logowanie z `doLoginEnc` na `doLoginWithAccessToken`.
Po sprawdzeniu logów SOAP, błąd niby zwracany jest podczas wykonywania `doQueryAllSysStatus`  (zaraz przed wykonaniem metody `doGetBidItem2`) i tam podawany jest `clientId` zamiast starego klucza Web API - ale dlaczego błąd jest tylko dla wybranych aukcji?

**Comment by PawelTaberski** [comment]
Przetestowałem metodę DoGetBidItem2 zarówno jako właściciel ofert jak i nie i metoda działa prawidłowo. Co prawda ze względu na to, że są to dosyć długo aktywne oferty i kupujących jest wielu na dane trzeba trochę poczekać :-)
Trochę pogubiłem się w tym co teraz napisałeś, z jaką dokładnie metodą masz problem i jaki respons w niej otrzymujesz. Bo tak jak pisałem przetestowałem DoGetBidItem2 i wydaje się wszystko ok.

**Comment by mindc** [comment]
@PawelTaberski 
Ok, wszystko jasne... rzeczywiście, danych bardzo dużo, musiałem tylko wydłużyć czas przetwarzania requestu.
