### ISSUE TITLE
Wymagalność shipping time

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1424]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Według dokumentacji pole czasu dostawy 'shipping time' nie jest wymagane. Przy próbie opublikowania oferty otrzymuję komunikat

"Could not change offer publication status. Estimated shipping time may not be empty."

**Comment by PawelTaberski** [comment]
Z tego co widzę mamy oznaczone, ze to pole jest wymagane m.in. [tutaj](https://developer.allegro.pl/sale/#shipping-rates).

**Comment by michcio19923** [comment]
![11](https://user-images.githubusercontent.com/7282897/55140429-5b1a9d00-5138-11e9-9cbf-3a2e39432fdc.png)
tutaj nie, https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST

**Comment by michcio19923** [comment]
Który parametr informuje czy dana metoda wysyłki ma stałą wartość czy wymaga podania?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiego parametru jeśli będziesz chciał wyedytować ten parametr przy ofercie przy której nie możesz zmieniać jego otrzymasz stosowny komunikat. W dosłownie kilku metodach można ustawić ten czas. Możesz to zobaczyć m.in. przez front.
