### ISSUE TITLE
Metody do pobierania informacji o kryteriach SuperSprzedawcy

### ISSUE THREAD

**Issue by daslinker** [allegro/allegro-api#1425]
:bulb: **Sugestia**

Codzienny przegląd kilkunastu kont w celu sprawdzenia i spisania warunków do programu, statusu weryfikacji i daty następnej zajmuję mnóstwo czasu. Do momentu gdy warunek zrealizowane zamówienia był liczbą komentarzy za ostanie 30 dni nie było problemu z pobraniem tych informacji z komentarzy i policzenia średniej - co oczywiście i tak było okrężną drogą. Czy planujecie rozwinięcie metod dotyczących user information o moduł super sprzedawcy?

**Comment by PawelTaberski** [comment]
W najbliższym czasie nie planujemy wdrożenia tego typu metod, ale jak najbardziej zgłosiłem Twoją sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć takie rozwiązania to poinformujemy o tym w dedykowanym komunikacie.
