### ISSUE TITLE
ERR_OBLIGATORY_ATTRIB_NOT_SET

### ISSUE THREAD

**Issue by baniolek** [allegro/allegro-api#1426]
Bardzo proszę o pomoc w ustaleniu jakiego parametru brakuje podczas wystawiania aukcji, otrzymuję następujący error:

Opis błędu: Nie podano parametru wymaganego dla wybranej kategorii. (Stan - fid: 50216)
Kod błędu: ERR_OBLIGATORY_ATTRIB_NOT_SET
Przyczyna błedu: doNewAuctionExt - One or more obligatory attributes have not been set.

Czy mogę prosić o informację czego dotyczy fid: 50216?

**Comment by daslinker** [comment]
Przecież masz napisane "fid:50216 - stan" czyli podstawowy wymagany parametr oferty w wszystkich katergoriach.

**Comment by baniolek** [comment]
Niemożliwe, stan jest uzupełniony i jeszcze przedwczoraj wszystko działało.

**Comment by daslinker** [comment]
Możesz się upewnić doGetSellFormFieldsForCategory na swoją kategorii. Chyba, że już próbowałeś.

**Comment by marcinja2** [comment]
Pamiętaj że stan w różnych kategoriach ma inne numery fid

**Comment by marcinja2** [comment]
od dziś są wymagane także jakieś inne pola (np przy wystawianiu książek) ale jakie nie pisze w zwracanym błędzie. gdzie można znaleźć jakieś informacje na ten temat?

**Comment by PawelTaberski** [comment]
Informacje o planowanych zmianach w parametrach znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).

**Comment by marcinja2** [comment]
szkoda tylko że doGetSellFormFieldsForCategory nie zwraca obowiązkowości wszskich nowowymaganych parametrów

**Comment by PawelTaberski** [comment]
@marcinja2  Metoda nie zwróciła Tobie, że dla danej kategorii jakiś parametr jest obowiązkowy? Jeśli tak podeślij proszę dla jakiej kategorii jaki parametr jest w niej błędnie oznaczony. Sprawdzimy to.

**Comment by anih** [comment]
Nie dla jednej to się dzieje, znowu niezsynchronizowaliście listy wymaganych parametrów w WebAPI. Przykładowe kategorie: 18014, 18015, 121808, 148836. Domyślam się, że cały Sport macie do przejrzenia.

**Comment by marcinja2** [comment]
to chyba było 89288

**Comment by PawelTaberski** [comment]
Rzeczywiście jest jakiś problem, przetestowałem na kolorze dominującym. Sprawę zgłosiłem do odpowiedniego zespołu z wysokim priorytetem. Proszę o cierpliwość.

**Comment by marcinja2** [comment]
pytanko: Nie dało by się urządzić tak by FID w W każdej kategorii np Autor miał taki sam numer? co inna kategoria np w książkach to ten sam autor ma dziesiątki różnych numerów fid. Tak jest z wydawnictwem i tp itd. na dodatek to parametry obowiązkowe.  To bardzo utrudnia prace. po co nam 100 000 fidów jak może zamknęło by się to może nawed w jednym tysiącu.

**Comment by PawelTaberski** [comment]
W REST API stosujemy właśnie podejście że dany parametr ma taki sam numer, a różny zestaw wartości np. parametr stan w kategorii książki wygląda tak:
```
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy"
                },
                {
                    "id": "11323_2",
                    "value": "Używany"
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```
,a w sukienkach ma już więcej wartości:
```
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy"
                },
                {
                    "id": "11323_2",
                    "value": "Używany"
                },
                {
                    "id": "11323_246510",
                    "value": "Nowy bez metki"
                },
                {
                    "id": "11323_246514",
                    "value": "Nowy z defektem"
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```
W WebAPI nie przewidujemy już wprowadzania zmian oprócz jakiś technicznie niezbędnych. Wszelkie nowości wdrażamy już tylko na REST API.

**Comment by marcinja2** [comment]
rzeczywiście, nie doszedłem jeszcze w rest do tego etapu dziękuję
