### ISSUE TITLE
ZMIANA CENY różne opisy i błąd

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#1427]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Na stronie https://developer.allegro.pl/my_offers/ zmiana ceny po wywołaniu PUT dla zasobu https://api.allegro.pl/sale/offer-price-change-commands/ zaś na stronie https://developer.allegro.pl/command/  zmiana ceny po wywołaniu PUT dla zasobu
/offers/numer aukcji/change-price-commands/

Na dodatek w obu przypadkach dostąję HTTP/1.1 400 Bad Request Content-Length: 0

przekazywany JSON {"modification":{"type":"FIXED_PRICE","price":{"amount":"4.20","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"7924962157"}]}]}

Co jest grane?

**Comment by PawelTaberski** [comment]
Ten zasób /offers/numer aukcji/change-price-commands/ służy do zmiany ceny w 1 ofercie, 
natomiast /sale/offer-price-change-commands/{commandId} służy do grupowej zmiany ceny i jednoczśnie możesz przypisać cenę X do 1000 ofert.

**Comment by marcinja2** [comment]
ok błąd 400 wyeliminowałem niepotrzebne były nawiasy w uuid

**Comment by marcinja2** [comment]
a gdy cena jest KT + licytacja to którą cenę zmieni. w webapi było rozróżnienie...

**Comment by PawelTaberski** [comment]
Są to zasoby do zmiany ceny kup teraz.

**Comment by marcinja2** [comment]
rozumiem ze do licytacji nie istnieją?

**Comment by PawelTaberski** [comment]
Licytacje możesz wyedytować przy pomocy zasobu PUT /sale/offers/{offerId}, pamiętaj jednak, aby nawet jak zmieniasz tylko cenę wysłać całą składnię. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#2).

**Comment by marcinja2** [comment]
ośmielę się skrytykować wprowadzone rozwiązania:
- to co mogło by z powodzeniem być zrobine po stronie klienta w dwóch linijkach kodu czyli obniżanie podwyższanie o procent lub o jakąś kwotę to macie w REST zrobione żeby było ciut ciut wygodniej dla programisty a jak trzeba zmienić cenę na licytacji to już nikt nie pomyślał by cokolwiek udogodnić to trzeba całą aukcję ściągać i jeszcze raz wysyłać (może nawet ze zdjęciami -nie wiem nie sprawdzałem). Reasumując wchodzicie w pierdoły a podstawa wykonana w 50% 
- kolejna sprawa poco tworzyć osobny zasób (czy metodę -jak zwał tak zwał) do zmiany jednej aukcji ceny jeśli opcja wieloaukcyjna załatwia sprawę także dla jednej aukcji. Czy aby nie marnujecie czasu? Sprawa nie dotyczy tylko Was ale także i nas użytkowników. Chciałem przejść całkowicie na REST skoro Webapi wyłączacie, a to taka lipa że program musi się na dwóch technologiach opierać bo są udostępnione przez Was jakieś pierdoły a sztandarowe zasoby - brak. Wiem że świat nie jest idealny ale jakieś podstawowe elementy kolejności można było by zachować. 
- kwestia dokumentacji (forma) ciągłe przewijanie i przeskakiwanie przypadkowe między opisami, ogromne litery, odstępy - skrajnie nieczytelna. Wykonywanie strony w 3 kolumnach było modne 15 lat temu. Po prostu bebechy mi się wywracają jak mam tam zaglądać.

Tyle żalów, nie mam czasu dalej wyrzutów czynić i nie oczekuje że się będziecie tłumaczyć. Proszę to potraktować jako sugestie. Może nie mam dużego doświadczenia w programowaniu ale patrząc zdroworozsądkowo to wydaje mi się że mam rację. Pozdrawiam i nie zajmuję więcej czasu

**Comment by PawelTaberski** [comment]
Zasób do zmiany pojedynczej ceny jest można powiedzieć historyczny był to pierwszy dostępny zasób na REST API 1 sierpnia 2016. Metody do bulkowej zmiany pojawiły się 22 listopada 2018. I oczywiście teraz ten zasób wydaje się nadwymiarowy, wtedy był to jedyny zasób pozwalający na zmianę ceny w trwającej ofercie.

Nad nową stroną dla naszej dokumentacji już pracujemy wiemy, że daleko jej do ideału i nam również ciężko się z nią pracuje.

Zapotrzebowanie na zmianie ceny w licytacji w wygodny sposób zgłosiłem jako sugestię. Jeśli zdecydujemy się na wdrożenie takiego zasobu to poinformujemy o tym.

**Comment by marcinja2** [comment]
Dziękuję za wyczerpującą wypowiedź. Zamykam temat.

**Comment by frankii91** [comment]
szkoda zę nie można zbiorczo zmienic cen na 1000 aukcji (rózne ceny, różne aukcje) jednym putem

**Comment by frankii91** [comment]
price > amount 
Gdzie znajdę informację jaki standard zapisu jest stosowany ?
Jakoś nie moge znaleźć ... ale ceny zwracanę są bardzo dzwinie  jełśi nie ma grodzy to pełne zł. a jak są grosze to jeszcze dziwniej bo nie ma pełnych 2 miejsc po przecinku/kropcke....

**Comment by PawelTaberski** [comment]
Zasób do grupowej zmiany ceny opisaliśmy w [naszym poradniku](https://developer.allegro.pl/my_offers/#3f). Jednakże nie możesz nim zmienić na różne ceny w różnych ofertach.
