### ISSUE TITLE
Funkcja niedostępna. Skontaktuj się z autorem aplikacji 

### ISSUE THREAD

**Issue by tomekbyd** [allegro/allegro-api#1428]
Witam!

Mam problem z logowaniem przez Sandboxa. Otrzymuję błąd "Funkcja niedostępna. Skontaktuj się z autorem aplikacji." Przy wersji produkcyjnej nie ma takiego problemu. Czy do logowania jest potrzebne aktywne konto? Jeśli tak to niestety od wczoraj dwa konta które stworzyłem w Sandboxie wiszą jako nieaktywne. Jeden z ticketów to f5f883119fceb930. Client ID to 541f8abbba894e30895c2ff0d90fe511 oraz ad491c3a1ab74e6182d829eb931cfdc4 dla drugiego konta z tym samym problemem.

**Comment by PawelTaberski** [comment]
Podaj proszę loginy tych kont, które są nieaktywne na sandboxie.

**Comment by tomekbyd** [comment]
Loguję się mailami kontakt@softom.pl i test@softom.pl

**Comment by PawelTaberski** [comment]
Konto test@softom.pl aktywowałem w pełni przy drugim niezbędne jest abyś wysłał dowolne dwa pliki przez zakładkę moje konto w Moim Allegro. Wtedy będę mógł je w pełni aktywować.

**Comment by tomekbyd** [comment]
Wysłane

**Comment by tomekbyd** [comment]
Witam!
Jak wygląda sprawa z tym błędem i brakiem aktywacji bo nie mogę przeprowadzać testów bez wyeliminowania tego błędu.

**Comment by PawelTaberski** [comment]
Widzę, że przesłałeś dokumenty do konta kontakt@softom.pl i aktywowałem je do końca natomiast te pierwsze widzę jako w pełni aktywne.

**Comment by tomekbyd** [comment]
Dla pewności wylogowałem się i zalogowałem ponownie na obu kontach. Na test@softom.pl widzę:
> Status konta
> Nieaktywne - trwa weryfikacja Twoich danych.
> Weryfikacja Twoich danych może potrwać do 3 dni. O jej wyniku poinformujemy Cię e-mailem.

Dla konta kontakt@softom.pl widzę: 
>     Status konta
>         Nieaktywne - trwa weryfikacja Twoich danych.
>         Uzyskaj dostęp do wszystkich funkcji Allegro w kilka chwil. 

Dla obu wygenerowałem linki do logowania i otrzymuję w obu przypadkach:
> {"errors":[{"code":"NotFoundException","message":"An error has occurred","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}
Trace-id dla ostatniej próby: 655d563033530a0f

**Comment by PawelTaberski** [comment]
Zgłosiłem ten problem do zespołu, który odpowiada za tą funkcjonalność. Proszę o cierpliwość.

**Comment by tomekbyd** [comment]
Jak wygląda sytuacja bo oba konta nadal są nieaktywne i nadal mam ten sam błąd?

**Comment by PawelTaberski** [comment]
Czekam ciągle na informacje, proszę jeszcze o trochę cierpliwości.

**Comment by PawelTaberski** [comment]
Udało się zdiagnozować problem, jest on najprawdopodobniej w adresie jaki masz w linku:
powinno być: 
https://allegro.pl.allegrosandbox.pl/....
a stosujesz
https://api.allegro.pl.allegrosandbox.pl/....
Więcej na temat adresów znajdziesz [tutaj](https://developer.allegro.pl/about/#Sandbox).

**Comment by tomekbyd** [comment]
Ok, mój błąd. W linku do API i autoryzacyjnym miałem tą samą domenę tylko z inną dalszą ścieżką. Niestety zasugerowałem się brakiem aktywacji konta. Teraz już wszystko działa. Dziękuję.
