### ISSUE TITLE
Zaplanowanie daty wznowienia aukcji

### ISSUE THREAD

**Issue by Ontr** [allegro/allegro-api#1429]
1. W dokumentacji nie ma informacji, że pole scheduledFor jest ignorowane - "Date and time for scheduling ACTIVATE action, will be ignored for another actions" a wznawianie to przecież komenda "ACTIVATE".
2. Po co takie ograniczenie? Czemu nie można zaplanować wznowienia?

**Comment by PawelTaberski** [comment]
W REST API nie ma opcji wystaw ponownie także nie możesz zaplanować wystawienia oferty, która jest aktywna, jeśli dobrze Ciebie rozumiem. Możesz zaplanować wystawienie nieaktywnej oferty.

**Comment by PawelTaberski** [comment]
Przetestowałem i masz racje, sprawę zgłosiłem do odpowiedniego zespołu. Proszę o cierpliwość.
