### ISSUE TITLE
Stan konta

### ISSUE THREAD

**Issue by dxsoftware** [allegro/allegro-api#1430]
Witam,
Która metoda API zwraca stan konta, czyli koszta do zapłaty łącznie?

**Comment by PawelTaberski** [comment]
W REST API nie mamy jeszcze takiej metody obecnie możesz pobrać te dane przez WebAPI metodą  [doMyBilling](https://allegro.pl/webapi/documentation.php/show/id,109).

**Comment by dxsoftware** [comment]
Kiedy planujecie dodać taką metodę?

**Comment by PawelTaberski** [comment]
Obecnie nie mam informacji kiedy wdrożymy taki zasób, jak tylko będziemy mieli takie informacje to poinformujemy o tym w dedykowanym komunikacie. Obecnie możesz skorzystać z metod w WebAPI przy pomocy metody [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582).
