### ISSUE TITLE
doQuerySysStatus zgłasza błąd: faultActor: Invalid parameters has been passed to 'doQuerySysStatus' operation - Value  in field sysvar (int) is incorrect

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#1431]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [X] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Problem występuje mniej więcej od: 2019-03-27 15:06

Aby zalogować się za pomocą doLoginEnc, muszę podać klucz wersji, który odczytuję za pomocą doQuerySysStatus. Jest tam parametr sysvar, pod który do tej pory zawsze podstawiałem 1 i zawsze to działało. Nagle dostałem info zwrotne: 

faultActor: Invalid parameters has been passed to 'doQuerySysStatus' operation - Value  in field sysvar (int) is incorrect

W dokumentacji do doQuerySysStatus  przeczytałem, że:
sysvar | int | wymagany
Komponent, którego wartość ma być pobrana (3 - struktura drzewa kategorii, 4 - pola formularza sprzedaży).

Ale nie działa ani wartość 3, ani wartość 4. Za każdym razem mam błąd jak powyżej. Co robić? Mój login Allegro to sbrzezin. Proszę pilnie o pomoc, bez tego nic mi nie działa.
 
pozdrawiam

Sergiusz

**Comment by PawelTaberski** [comment]
Przetestowałem dla różnych wartości i metoda działa poprawnie, pamiętaj, że klucz wersji możesz również pobrać przy pomocy metody [doQueryAllSysStatus](https://allegro.pl/webapi/documentation.php/show/id,61). Podeślij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do zgłoszenia numer 1431 na GitHub-ie.

**Comment by sbrzezin** [comment]
Czy coś już wiadomo w temacie? System stoi. Przesłałem przez formularz xml-e.

**Comment by PawelTaberski** [comment]
Przetestowałem na Twoim kluczu, i po przesłaniu danych w formie:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoQuerySysStatusRequest>
         <ser:sysvar>3</ser:sysvar>
         <ser:countryId>1</ser:countryId>
         <ser:webapiKey>.....</ser:webapiKey>
      </ser:DoQuerySysStatusRequest>
   </soapenv:Body>
</soapenv:Envelope>
```
Otrzymuje poprawną odpowiedź sprawdź czy masz najnowszego wsdl-a, jeśli tak, to problem musi występować w kodowaniu w sposobie w jaki dodajesz zmienne w polu country i sysvar. Sprawdź czy podanie wartości na sztywno rozwiąże sprawę.

**Comment by sbrzezin** [comment]
Problem w tym, że to nie ja generuję te xml-e lecz biblioteka, a konkretnie axis z Javy. Nie mam wpływu na treść xml-a. Zbudowałem oczywiście najnowsze biblioteki na podstawie WSDL-a. Ale efekt był ten sam. Tak jak pisałem wcześniej - to mi działało przez kilka lat, i nagle bam... Coś się zmieniło u Was... Pracuję już nad Rest Api ale to nie taka szybka sprawa... Możecie jeszcze coś dla mnie zrobić?

**Comment by PawelTaberski** [comment]
Nie udało mi się powtórzyć Twojego problemu wszystkie requesty kończą się prawidłowa odpowiedzią, ponadto nic nie zmienialiśmy w działaniu tych metod, a przesłanie requesta z Twoim kluczem i ustawionymi na sztywno parametrami kończy się powodzeniem, także problem musi leżeć w treści xml-a jaki ostatecznie od Ciebie wychodzi.
