### ISSUE TITLE
ERR_INVALID_VERSION_CAT_SELL_FIELDS

### ISSUE THREAD

**Issue by lekerpl** [allegro/allegro-api#1432]
Dzień dobry,

Od wczoraj od godziny 12:50 mamy problem z API. Program, który odpowiada u nas za integrację to TaskCentre.

Od wczoraj w logu generują się błędy **ERR_INVALID_VERSION_CAT_SELL_FIELDS** oraz **Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!**

Czy ze strony Allegro została wprowadzona jakaś zmiana, przez którą może występować ten problem?

**Comment by PawelTaberski** [comment]
Nie nic nam o tym nie wiadomo jednakże problem sugeruje że korzystasz ze starego klucza wersji. Upewnij się przy pomocy metody doQueryAllSysStatus bądź, doQuerySysStatus czy używasz najnowszy.

**Comment by TimothyKoval** [comment]
Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!

Wersja struktury drzewa kategorii: 1.9.92
Wersja pól formularza sprzedaży: 1.44.50

**Comment by PawelTaberski** [comment]
A jaką otrzymujesz wartość klucza wersji? Parametry są zawsze odświeżane min. raz dziennie w nocy.

**Comment by TimothyKoval** [comment]
1504485292

**Comment by PawelTaberski** [comment]
To może być ten problem widzę, że nie jest on najświeższy:
```
            <ns1:item>
               <ns1:countryId>1</ns1:countryId>
               <ns1:programVersion>1.0</ns1:programVersion>
               <ns1:catsVersion>1.9.92</ns1:catsVersion>
               <ns1:apiVersion>1.0</ns1:apiVersion>
               <ns1:attribVersion>1.0</ns1:attribVersion>
               <ns1:formSellVersion>1.44.53</ns1:formSellVersion>
               <ns1:siteVersion>1.0</ns1:siteVersion>
               <ns1:verKey>1554377355</ns1:verKey>
            </ns1:item>

```

**Comment by TimothyKoval** [comment]
Tak, bo teraz już się zmienił. Problem nie jest absolutnie nowy, zdarza się to nagminnie - walidacja czegoś wymaga, a podawane przez api dane są stare. Do tego dochodzi jeszcze ten komunikat `Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!`, co sugeruje naszym klientom, że wina jest po naszej stronie!!!

**Comment by PawelTaberski** [comment]
Zmiany w parametrach następują stosunkowo często, także może zdarzać się taki komunikat. Komunikatu błędu nie zmienialiśmy. Jedyne co mogę zalecić to przejście na REST API, tam nie ma problemów z tym związanych, bo uwierzytelnianie i autoryzacja przebiega w inny sposób.
Oczywiście jeśli zauważysz jakiś problem z tą metodą daj nam znać, jeśli pojawia się taki komunikat powinieneś pobrać najnowszy klucz wersji.

**Comment by TimothyKoval** [comment]
Znowu do samo, na jednym koncie działa, na drugim nie. Puknijcie się mocno w łeb...
