### ISSUE TITLE
nadchodzące opłaty

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1433]
Witam, czy jest zasób umożliwiający pobranie nadchodzących opłat?

**Comment by PawelTaberski** [comment]
Nadchodzące opłaty możesz sprawdzić przy pomocy zasobu POST /sale/loyalty/promotions sprawdzisz kiedy dany cykl się kończy i naliczymy kolejną opłatę, więcej na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/charges/#1).
