### ISSUE TITLE
zmiana statusu zamówienia

### ISSUE THREAD

**Issue by jchodubska** [allegro/allegro-api#1434]
Dzień dobry,

Czy istnieje możliwość ustawienia statusu z PŁATNOŚĆ ROZPOCZĘTA na PŁATNOŚĆ ZAKOŃCZONA (FILLED_IN -> READY_FOR_PROCESSING)?

**Comment by PawelTaberski** [comment]
Jako sprzedawca nie masz możliwości na zmianę statusu po swojej stronie, zmieni się on automatycznie po tym jak:
"**READY_FOR_PROCESSING** - klient wypełnił FOD i sfinalizował płatność (status: zakończona), albo wybrał płatność za pobraniem lub odbiór osobisty. Dopiero w tym statusie zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni. Dlatego możesz:

- pobrać jego szczegóły,
- sprawdzić czy zgadza się kwota płatności,
- przejść do kolejnych kroków realizacji zamówienia."

Więcej na temat obsługi zamówień przez REST API znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).
