### ISSUE TITLE
Usunięcie shipping rate

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1435]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Czy jest możliwość usunięcia shipping rate? W dokumentacji brak jest metody delete na tym zasobie

**Comment by PawelTaberski** [comment]
Nie ma zasobu do usunięcia, bo cenniki automatycznie aktualizują się po zmianie we wszystkich przypisanych ofertach, a nie może zostać oferta bez formy dostawy. Jednakże zawsze możesz skorzystać z zasobu PUT /sale/shipping-rates/{id} i dowolnie wyedytować taki cennik.
