### ISSUE TITLE
Odpowiednik doGetPostBuyData w REST API, czy jest?

### ISSUE THREAD

**Issue by sledz19** [allegro/allegro-api#1436]
Witam, pytanie jak w temacie. Potrzebujemy pobrać bardziej szczegółowe dane o koncie z którego został zrobiony zakup (nie chodzi o adresata dostawy). Potrzebujemy dane np. Imię, Nazwisko, adres.

Ewentualnie czy jest jakiś odpowiednik aby pobrać powyższe dane dla konkretnego użytkownika? - niestety nie widzę takiego zasobu.

**Comment by PawelTaberski** [comment]
Obecnie w REST API nie ma takiego zasobu możesz skorzystać z zasobu W WebAPI, jeśli potrzebujesz takich danych. Pracujemy nad metoda do pobrania informacji o danym userze. Jednakże nie mam informacji kiedy wdrożymy taki zasób. Jak tylko będziemy mieli takie informacje, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by sledz19** [comment]
a może dałoby radę dodać dodatkowe pola do zwracanej odpwoiedzi przez zasób GET /order/checkout-forms/{id} - mam na myśli pola do obiektu "buyer": imię, nazwisko, adres. To praktycznie rozwiązałoby sprawę - przynajmniej z naszej perspektywy :)

**Comment by PawelTaberski** [comment]
Oczywiście sugestie przekaże, powiedz mi tylko jeszcze do czego są Tobie niezbędne takie informacje, w jakim przypadku będą one dla Ciebie użyteczne?

**Comment by sledz19** [comment]
nie wszytsko mogę zdradzić gdyż jest to objęte umową o zachowaniu poufności z klientem. Jednym z takich przykładów jest tworzenie kontrahenta w systemie ERP w momencie złożenia zamówienia przez klienta - bez tych danych musielibyśmy wpisywać fikcyjne imie nazwisko lub powielać konto emalowe w te pola. Kolejną rzeczą jest używanie już istniejącego kotrahenta do kolejnych zamówień, nie możemy porównywać czy kontrahent jest zgodny tylko na podstawie konta email - porówanie musimy zrobić na podsatwie większej liczby pól (taka polityka firmy).

**Comment by PawelTaberski** [comment]
Rozumiem dodałem te informacje do sugestii. Jeśli otrzymam informacje, że wdrożymy takie rozwiązanie, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by sbrzezin** [comment]
Dołączam się do prośby. Sprzedaję produkty, które wymagają podania imienia i nazwiska. W starym webapi korzystałem doGetPostBuyData aby pozyskać te dane. Niestety stare webapi przestało działać (przynajmniej z mojego punktu widzenia) i zostałem zmuszony na przejście na nowe. A tu niespodziana. Tak jak poprzednik dołączam się do sugestii: uzupełnienie obeiktu "buyer" o dodatkowe informacje rozwiązałoby problem.

**Comment by PawelTaberski** [comment]
Rozumiem dodałem również Twoje wyjaśnienie dlaczego jest to niezbędne, jak tylko otrzymam informacje, że wdrożymy takie informacje to przygotujemy dedykowany komunikat.

**Comment by Radeq** [comment]
Szanowny Panie @PawelTaberski , dołączam się do prośby - dane zamawiającego (w starym API doGetPostBuyData.userFirstName oraz userLastName ) są widoczne w MS Allegro i widać wyraźnie, iż klienci korzystający z dedykowanych aplikacji również chcieliby mieć do nich dostęp.

**Comment by PawelTaberski** [comment]
@Radeq Sekcja buyer będzie rozbudowana o dane użytkownika z ustawień konta, takie dane będziemy wysyłać już w statucie BOUGHT. Natomiast adres do wysyłki dalej pojawi się dopiero po opłaceniu zamówienia bądź uzupełnieniu fod-a i wybraniu płatności za pobraniem

**Comment by neldh** [comment]
kiedy możemy spodziewać się ogarniętej sekcji buyer?

**Comment by PawelTaberski** [comment]
Jeszcze nie znam dokładnej daty wdrożenia. Jak tylko będziemy mieli konkretne informacje to poinformujemy o tym w dedykowanym komunikacie.
