### ISSUE TITLE
[REST API] filtering/sorting 

### ISSUE THREAD

**Issue by DevPartner** [allegro/allegro-api#1437]
Hi, 

I tried to use filtering and sorting to get outdating offers but wasn't successful
1. I tried https://api.allegro.pl/offers/listing?category.id=57967&offset=0&publication.status=ENDED
but I recieved the same results as without publication.status filter. 
Also I tried https://api.allegro.pl/offers/listing?category.id=57967&offset=0&publication.status=ACTIVE but also got 4 results.
2. do you have lastModified att or something like this for offers? Actually I tried two requests
https://api.allegro.pl/offers/listing?category.id=4029&limit=100&offset=100&sort=lastModified
https://api.allegro.pl/offers/listing?category.id=4029&limit=100&offset=100&sort=-lastModified
I expected to see different output for defferent sort requests but I got the same results for those requests. 
3. Also I tried to use sorting sort=publication.endingAt, sort=-publication.endingAt but got the save output results.
4. Filter https://api.allegro.pl/offers/listing?category.id=57967&offset=0&sellingMode.price.amount.gte=12200 doesn't work for me also
etc

Could you please help me? what do i do wrong?

Best regards, Konstantin.

**Comment by PawelTaberski** [comment]
If you want for example get closed offer you should use parameter:

searchMode | stringSearch mode. Allowed values: REGULAR - searching for a phrase in the title of offers; DESCRIPTIONS - searching for a phrase in titles and offers descriptions; CLOSED - searching for a phrase in titles of closed offers. Default REGULAR.

as it is in the [documentation](https://developer.allegro.pl/documentation/#operation/getListing)
More examples how to use this resource you will find[ here](https://developer.allegro.pl/en/listing/),
