### ISSUE TITLE
Rest API: Invalid_grant. Invalid authorization code

### ISSUE THREAD

**Issue by jkdw** [allegro/allegro-api#1438]
Hi everyone!

I have some strange issue with getting a new Rest API token.

First of all, I'm going to the link:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=[my client id here]&redirect_uri=https://[my site address]/api/refresh-token/

And Allegro returns me an url with authorization code, like this:
https://[my site address]/api/refresh-token/?code=8y5j0e90euhov8dropvots8qz8vdftcd

Then I send a POST request to:
https://allegro.pl/auth/oauth/token
with headers:
Authorization: Basic [here my clientId:clientSecret encoded in Base64]
Content-Type: application/x-www-form-urlencoded
And body:
grant_type=authorization_code&code=[here a code from allegro]&redirect_uri=https%3A%2F%2F[my site address]%2Fapi%2Frefresh-token%2F

And then Allegro returns me this error:
"{"error":"invalid_grant","error_description":"Invalid authorization code: <here a code from allegro>"}"

Please, I need help with this problem!
On other projects, I use the same algorithm and it works fine.

**Comment by PawelTaberski** [comment]
I see you have mixed 2 flows of authorization you start with code flow and then you add few think from device flow. You should't add Content-Type: application/x-www-form-urlencoded and send parameters in body, they should be in params. Check our [documentation](https://developer.allegro.pl/en/auth/#user).

**Comment by jkdw** [comment]
> I see you have mixed 2 flows of authorization you start with code flow and then you add few think from device flow. You should't add Content-Type: application/x-www-form-urlencoded and send parameters in body, they should be in params. Check our [documentation](https://developer.allegro.pl/en/auth/#user).

Ok. I done all by documentation, but the result is not changed:
```
curl -X POST -H 'Authorization: Basic MD...SdA==' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=evisdw0ztngenpqhlz1ihnioodquxgxl&redirect_uri=https://.../api/refresh-token/'
{"error":"invalid_grant","error_description":"Invalid authorization code: evisdw0ztngenpqhlz1ihnioodquxgxl"}
```

Is it possible whether I have the problem with my account or Konto and it create the problems to use Rest API?

**Comment by PawelTaberski** [comment]
You remember to user code in maximum 10s? Becouser it is valid for 10 seconds.

**Comment by jkdw** [comment]
> You remember to user code in maximum 10s? Becouser it is valid for 10 seconds.

Yes, I remember. 10 seconds is enough.
Can you see the authorization logs, for determine the exact cause of error? Because I'm trying to find the cause already the second day. But vain.

**Comment by PawelTaberski** [comment]
Please send to us via [contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) step after step the full requests and responses, we will check it. Please mark that the details are needed for the ticket number 1438 on GitHub.

**Comment by jkdw** [comment]
Thank you.

**Comment by jkdw** [comment]
I used the device type of authorization. It works good.
