### ISSUE TITLE
Zmiana cennika dla istniejącej ofert

### ISSUE THREAD

**Issue by mbx88** [allegro/allegro-api#144]
Witam,
czy da się zmienić cennik dla istniejącej już ofert? Chodzi mi dokładnie o podpięcie innego cennika dostaw.

**Comment by kormichu** [comment]
Ja bym to widział tak:
1) pobierz oferte: https://developer.allegro.pl/documentation/#!/offer/getOfferUsingGET i przetwórz jsona do tablicy / obiektu
2) zmodyfikuj pole shippingRates
3) zamień tablicę / obiekt do formatu jsona i wyślij PUT'em: https://developer.allegro.pl/documentation/#!/offer/updateOfferUsingPUT

Tutaj masz dokładniejszy opis poszczególnych pól: https://developer.allegro.pl/sale/ . Niestety nie da się przez REST API skorzystać z PATCH żeby zmodyfikować tylko jedno wybrane pole

**Comment by PawelTaberski** [comment]
Obecnie cenniki możesz modyfikować tylko przez Moje Allegro. Jeśli zmodyfikujesz dany cennik zaktualizuje się on automatycznie przy wszystkich ofertach, przy których jest przypisany. Dodatkowo przez Moje Allegro możesz masowo przypisać wybrany cennik do ofert.

**Comment by PawelTaberski** [comment]
Jeśli nie chcesz nic zmieniać w cenniki tylko przypisać utworzony cennik do wybranych ofert to jak najbardziej. Tylko pamiętaj aby przesyłać całą ofertę, mimo iż zmieniasz tylko jedno pole.

**Comment by mbx88** [comment]
Witam,
robię dokładnie w taki sposób:
1. Pobieram ofertę za pomocą zasobu GET /sale/offers/{offerId}, metoda zwraca json z danymi (wszystko ok)
2. Wywołuję metodę do edycji: PUT /sale/offers/{offerId}
 Dodaje następujące nagłówki:
-Authorization
-API-Key
-Content-Type 
-Accept
Do tego dodaję content zwrócony z metody GET (beż zadnych modifikacji).
Po wywołaniu dostaję błąd 
"StatusCode: BadRequest, Content-Type: application/json, Content-Length: -1)"
"{\"errors\":[{\"code\":\"ERROR\",\"message\":\"An error has occurred\",\"details\":null,\"path\":\"/sale/offers/7260511964\",\"userMessage\":null}]}"

Próbowalem również wywołac ten zasób za pomocą Advanced REST Client z tymi samymi parametrami - jednak bład jest ten sam. Co robię nie tak? Nagłówki raczej są ok ponieważ get przechodzi bez problemu

**Comment by mbx88** [comment]
Witam,
chciałem zedytować ofertę w następujący sposób:
1. Pobrałem dane za pomoca metody GET /sale/offers/{offerId
2. Zmieniłem Cennik zmieniając wartość shippingRates
3. Podczas zapisu za pomocą metody PUT dostaję taki błąd:

"{\"errors\":[{\"code\":\"VALIDATION_ERROR\",\"message\":\"ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM\",\"details\":\"\",\"path\":\"\",\"userMessage\":\"\"}]}"

**Comment by PawelTaberski** [comment]
Możesz skorzystać również do metody do grupowych zmian w REST i przy jej pomocy przypisac dany cennik do wielu ofert naraz. W tym celu skorzystaj z metody [PUT na zasobie /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation/#!/offer/modificationCommandUsingPUT)

**Comment by mbx88** [comment]
Dziękuję za odpowiedź.
Postaram sie skorzystać z tej metody.
A dlaczego dostawałem tamten błąd? ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM

**Comment by PawelTaberski** [comment]
Najprawdopodobniej produkt nie był oznaczony jako sklepowy, a zmieniłeś czas dostawy na 30 dni. Dodaj w polu duration P30D.

**Comment by dlis2010** [comment]
Witam, mam podobny problem jak kolega wyżej.
konto firmowe, aukcje wystawiona do wyczerpania produktów.
Chce edytować aukcje, pobierajac ja GET'em  otrzymuje publication->duration puste przez co podczas metody PUT otrzymywałem komunikat "ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM".
Po zmianie publication->duration na  P30D zgodnie z Waszą sugestią wyżej edycja przeszła bez problemu. Niestety teraz mam 30-dniową aukcję. Jak ponownie ustawić aukcje do wyczerpania produktów? 
Ustawiając NULL ponownie otrzymuję  ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM
ustawiając jakikolwiek inny czas otrzymuję ERR_CANT_CHANGE_ITEM_STARTING_TIME_OR_DURATION

Czy ja robię coś źlę, czy macie problem z przyjęciem przez publication->duration  wartości NULL?
Jak teraz zmienić ponownie wyżej wymieniona aukcje na aukcje do wyczerpania zapasów? (nr aukcji: 7192448831)

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest problem z ofertą sklepową w REST, sprawę przekazałem do odpowiedniego zespołu, zajmiemy się tym.

**Comment by mbx88** [comment]
Witam.

Czy udało się coś w tej kwestii juz poprawić?
Jeśli nie to czy ponowna edycja oferty tak aby zmienić aukcje na "do wyczerpania zapasów" jest możliwa? Jeśli tak to jaką wartość trzeba podać w polu duration?

**Comment by PawelTaberski** [comment]
Pracujemy nad tym, proszę o jeszcze trochę cierpliwości. Odnośnie Twojego pytania nie wiem czy dobrze ciebie zrozumiałem, ale aby wystawić ofertę "do wyczerpania zapasów" wystarczy w polu duration podać wartość null. (https://developer.allegro.pl/sale/#new-offer)

**Comment by dlis2010** [comment]
Panie Pawle czy wiadomo coś już w powyższej sprawie?
Jest szansa, ze do weekendu majowego problem zostanie naprawiony?

Proszę mnie poprawić, jeżeli napiszę źle. 
Na chwilę obecną nie ma możliwości edycji żadnej oferty sklepowej wystawionej do wyczerpania zapasów za pomocą metody PUT /sale/offers/ ze względu na problem z przyjęciem wartości null w publication->duration, zgadza sie?

**Comment by PawelTaberski** [comment]
Zgadza się obecnie jest problem z ofertami sklepowymi na 30 dni do wyczerpania zapasów, odpowiedni zespół pracuje już nad tym problemem. Ciężko mi powiedzieć kiedy problem zostanie rozwiązany. Obecnie zasoby do edycji i wystawiania oferty są w wersji beta, dlatego mogą pojawiać się takie problemy.

**Comment by mbx88** [comment]
Witam,
super, dziękuje bardzo, wydaje się że wszystko działa.

**Comment by dlis2010** [comment]
Witam ponownie,

niestety muszę odkopać temat.
@PawelTaberski jak w takim razie aktualnie wystawić ofertę sklepową do wyczerpania przedmiotów?
przesyłając null wystawie do wyczerpania zapasów ale ofertę zwykłą - czy na chwilę obecną jest jakaś różnica między ofertą zwykłą, a sklepową?

**Comment by PawelTaberski** [comment]
Jest to zabieg docelowy, mamy w planach w przyszłości ujednolicenie formatu oferty. Obecnie oferta sklepowa i zwykła nie różnią się ani wyglądem ani technicznie.
