### ISSUE TITLE
Dokumentacja brak nagłówków

### ISSUE THREAD

**Issue by kerog** [allegro/allegro-api#1440]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X ] inny

:beetle: **Opis**
Przy opisie metod w dokumentacji brakuje nagłówków wymaganych do wysłania, by działało całe żądanie. Przykładowo w zasobie: sale/delivery-methods według poradników należy wysłać:
'accept: application/vnd.allegro.beta.v1+json' - co skutkuje 406,
dopiero zmiana na 'accept: application/vnd.allegro.public.v1+json' daje 200.

**Comment by PawelTaberski** [comment]
Gdzie zauważyłeś taką nieścisłość, z tego co widzę [w poradniku](https://developer.allegro.pl/sale/#shipping-rates) są poprawne nagłówki:
```
curl -X GET \
https://api.allegro.pl/sale/delivery-methods \
-H 'Authorization: Bearer {token}' \
-H 'accept: application/vnd.allegro.public.v1+json'
```
Podaj proszę, gdzie jest błędnie, oczywiście poprawimy.
