### ISSUE TITLE
Lista aukcji z moje allegro -> kupione?

### ISSUE THREAD

**Issue by zagnagaspo** [allegro/allegro-api#1441]
W jaki sposób nowym pięknym rest api wyciągnąć oferty z zakładki moje allegro -> kupione?

**Comment by PawelTaberski** [comment]
Przy pomocy zasoby /sale/offers np /sale/offers?sort=-stock.sold. Zasób ten dzwierciedla własnie możliwości tej zakładki. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by zagnagaspo** [comment]
Nie za bardzo rozumiem jak to działa.
Cytat:
"Aby otrzymać listę wszystkich ofert danego użytkownika, wywołaj metodę GET na zasobie /sale/offers. Musisz być zautoryzowanym jako sprzedawca, który utworzył te oferty."

To nie są moje oferty. Ja jestem kupującym w nich, nie sprzedającym.

**Comment by PawelTaberski** [comment]
Ah to się nie zrozumieliśmy myślałem że pytasz jako sprzedawca. Jeśli nie jesteś właścicielem danej oferty to w REST API możesz skorzystać z zasobu listing. Więcej o nim [tutaj](https://developer.allegro.pl/listing/).

**Comment by zagnagaspo** [comment]
Nie no bij mnie laciem.
Czy wy czytacie co ludzie piszą?
Chcę dostać tę listę: https://allegro.pl/moje-allegro/zakupy/kupione
Ty mi dajesz linka do listingu w którym czytamy:
"WAŻNE! Pamiętaj, że ta metoda jest odzwierciedleniem wyszukiwarki w wizualnej wersji serwisu, przykładowo w pierwszej kolejności otrzymasz promowane oferty."

Od kiedy wyszukiwarka pozwala szukać komuś w kupionych? Nawet swoich?

Jeśli masz (pewnie nie) konto allegro to do niego się zaloguj i wejdź na ten adres https://allegro.pl/moje-allegro/zakupy/kupione i powiedz mi jak mam dostać tę listę przez piękne nowe super hiper allegro rest api. 
Ok?

**Comment by PawelTaberski** [comment]
Tak, jak napisałem źle Ciebie na początku zrozumiałem. I tak jak napisałem jeśli nie jesteś właścicielem oferty nie ma innego zasobu do przeglądania ofert jak /offers/listing. Nie ma zasobu, który umożliwiałby takie same możliwości jak zakładka kupione.

**Comment by zagnagaspo** [comment]
Dobra, już znalazłem na to sposób :)

Nie wiem czy tworzyć nowy ticket ale w właśnie w metodzie doMyAccount2 macie błąd i nie ściąga wszystkich aukcji. 
Np. kupiłem 3 przedioty i przeważnie jednej z nich metoda mi nie zwróci. (accountType='won')

**Comment by PawelTaberski** [comment]
Nie musisz podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) tylko requesta i responsa w formacie XML z opisem czego brakuje. Sprawdzimy w czym jest problem.

**Comment by dzoudzou3** [comment]
> Dobra, już znalazłem na to sposób :)
> 
> Nie wiem czy tworzyć nowy ticket ale w właśnie w metodzie doMyAccount2 macie błąd i nie ściąga wszystkich aukcji.
> Np. kupiłem 3 przedioty i przeważnie jednej z nich metoda mi nie zwróci. (accountType='won')

jak to zrobiłeś?
