### ISSUE TITLE
Przeszukiwanie aukcji zakonczonych z uzyciem REST api

### ISSUE THREAD

**Issue by dave7280** [allegro/allegro-api#1442]
Chcialem zapytac, czy mozliwe jest przeszukiwanie aukcji znajdujacych sie w kategorii "zakonczone" z uzyciem REST API. Chociaz nie jestem pewien czy w ogole jest to zdefiniowane jako kategoria.

Jest to bardzo przydatna rzecz przy szacowaniu wartosci przedmiotu.

**Comment by PawelTaberski** [comment]
Tak możesz wyszukiwać w zakończonych ofertach zasobem /offers/listing przykładowe zapytanie:
https://api.allegro.pl/offers/listing?phrase=czerwona+sukienka&searchMode=CLOSED
Więcej informacji na temat tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by dave7280** [comment]
Dziekuje za szybka odpowiedz :)
