### ISSUE TITLE
Modyfikacja oferty i 'Nie możesz zmienić nazwy, gdy są już oferty kupna'

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#1443]
Witam,
W jaki sposób mogę pobrać informację o tym czy na danej ofercie mogę zmienić tytuł?
Enpoint https://api.allegro.pl/sale/offers/{offerId} nie zwraca informacji o tym czy na danej aukcji zostały dokonane jakieś zakupy.

**Comment by PawelTaberski** [comment]
Te informacje możesz pobrać przez REST API zasobem /sale/offers jednakże otrzymasz tam liczbę sprzedanych tylko z 30 dni. Przez REST API obecnie nie ma możliwości pobrania liczby sprzedanych przedmiotów od początku istnienia oferty.

**Comment by Himon-SYNCRAFT** [comment]
Czyli rozumiem, że nie ma takiej metody, która podaje ilość sprzedanych dla konkretnej oferty? Trochę to kłopotliwe. Moim zdaniem ta informacja powinna być w /sale/offers/{offerId}.

**Comment by PawelTaberski** [comment]
Tak wiemy o tym problemie zgłaszałem już go do odpowiedniego zespołu, oczywiście otrzymasz stosowny komunikat jak będziesz chciał zmienić tytuł w ofercie która ma sprzedaż, ale to oczywiście nie rozwiązuje tego problemu z ofertami, które miały sprzedaż dawniej niż 30 dni.
