### ISSUE TITLE
Problem z czasem dostawy dla oferty

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1445]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

1. Błąd przy wystawianiu oferty na podstawie draftu

Draft Id: **6206243725**
https://paste.ofcode.org/33kayRmcXtPMTQCJDz3rU6z

Przy próbie wystawienia oferty zwraca poniższy błąd

**Could not change offer publication status. Estimated shipping time may not be empty.**

Shipping rate przypisany do Id ma ustawiony shippingTime

https://paste.ofcode.org/ULLUGWfJp2DLLwFVpQGthd

2. Czemu zawsze zamienia czas dostawy z dni na godziny, wysyłam dni zwraca godziny

Request: https://paste.ofcode.org/hNAn7kW8N28hMJBttm5wpA
Response: https://paste.ofcode.org/SFx2UAMiggJB5LdpJwxNEC

**Comment by rtnet-pl** [comment]
Nie chodzi przypadkiem o delivery.handlingTime?

**Comment by michcio19923** [comment]
Jeśli ustawię delivery.handlingTime to mam błąd już na drafcie 

**ERR_IF_YOU_WANNA_SELL**

Request: https://paste.ofcode.org/3aD285JU4iR3xGQSPuX49U6
Response: https://paste.ofcode.org/bG7bXbcWK5UzCXEpEfVkJU

**Comment by rtnet-pl** [comment]
Użytkownik bez pełnej aktywacji konta nie może wystawiać ofert w serwisie.

**Comment by michcio19923** [comment]
Od kilku miesięcy mam komunikat 'Nieaktywne - trwa weryfikacja Twoich danych.'

**Comment by PawelTaberski** [comment]
@michcio19923 Problem występuje u Ciebie na Sandboxie tak? Podaj proszę login swojego konta sprawdzimy czy wszystko jest ok.

**Comment by michcio19923** [comment]
ms.sukiennik@wp.pl

**Comment by PawelTaberski** [comment]
@michcio19923 Aktywowałem Twojego usera daj znać czy teraz jest ok.

**Comment by michcio19923** [comment]
Ad.2. Czemu zawsze zmienia czas dostawy z dni na godziny, jest sens wysyłać dni?

Request: https://paste.ofcode.org/hNAn7kW8N28hMJBttm5wpA
Response: https://paste.ofcode.org/SFx2UAMiggJB5LdpJwxNEC

**Comment by PawelTaberski** [comment]
Możesz wysyłać i tak i tak:
```
        "duration": null,                       -- wymagane, czas trwania oferty, dostępne
                                                wartości: null (do wyczerpania zapasów), 
                                                P3D (3 dni); P5D (5 dni); P7D (7 dni); 
                                                P10D (10 dni); P20D (20 dni); P30D (30 dni), czas 
                                                możesz podać też w godzinach - np.: P72H (3 dni). 
                                                Dla oferty typu AUCTION (licytacja) nie możesz 
                                                podać wartości null i dostępne są wartości:
                                                P3D (3 dni); P5D (5 dni); P7D (7 dni); P10D (10 dni);
                                                Natomiast dla ofert typu ADVERTISMENT (ogłoszenia) 
                                                dostępne są wartości: null (na czas nieokreślony - 
                                                opłaty naliczane co 10 dni); P10D (10 dni); 
                                                P20D (20 dni); P30D (30 dni)
```
Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#new-offer).

**Comment by michcio19923** [comment]
To czemu skoro wysłałem wartość w dniach zwraca mi draft z wartością w godzinach?

**Comment by PawelTaberski** [comment]
System po przetworzeniu zwraca wartość w swojej podstawowej jednostce, ale wartość jaka za nią idzie jest dokładnie taka sama jak przesłana przez Ciebie.

**Comment by Nemanja-Lima** [comment]
@PawelTaberski

Hi mate. I think that i have the same problem. Can u check my acc on sandbox? 
vlp@mytrendyphone.eu

**Comment by PawelTaberski** [comment]
@Nemanja-Lima Hi to verify this account you need to send any to files by tab [My settings](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).
