### ISSUE TITLE
Błąd przy pobieraniu.

### ISSUE THREAD

**Issue by AlekKlepacz** [allegro/allegro-api#1446]
Występuje problem: 
 - [ x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

30-03-2019

Błąd - doGetBidItem2
ERR_INVALID_ITEM_ID: Niepoprawny identyfikator oferty lub wskazana oferta została przeniesiona do archiwum.

**Comment by FromAnyHole** [comment]
Wow !
Nie podawaj tu klucza, nawet w formie okrojonej ;-)

**Comment by PawelTaberski** [comment]
@AlekKlepacz Podaj proszę id oferty, z którą masz problem sprawdzimy to.

**Comment by AlekKlepacz** [comment]
Cześć. Problem był w sobotę i niedzielę to już drugi raz w przeciągu 7 dni. Niestety nie mam możliwości wychwycenia nr oferty wyświetla mi tylko komunikanta o błędzie. Połączenie jest w czasie rzeczywistym. Mogę podać klucz IP jak chcesz sprawdzić konto.

**Comment by PawelTaberski** [comment]
Do zbadania tego problemu niezbędne jest id ofert bo sam błąd wskazuje, że problemem jest to iż oferta o którą pytasz najprawdopodobniej została przeniesiona do archiwum.

**Comment by AlekKlepacz** [comment]
Nie wiem jak to wyłapać wyświetla mi komunikat i się przeładowuje na nowe pobierania. Podpytam inżynierów od sklepu. Ale pewnie jak zawsze odbiją piłeczkę że to winna allegro. I tak do bramki do bramki...

**Comment by AlekKlepacz** [comment]
Cześć.połączenie działa w czasie rzeczywistym i pobiera pakietami oferty. Mogłem jedynie wyłuskać końcowy pakiet w który wyświetla komunikat błędu.  Nr ofert: 7241825920 / 7239034008 / 72366974451  7236665083 / 7236642267 / 7236635832 / 7236577503 / 7236189271 / 7236188211 / 72361255793 / 
Po sprawdzeniu wytypowałem te trzy: 72366974451 / 7236642267 / 72361255793 /

**Comment by PawelTaberski** [comment]
Sprawdziłem i niektóre id oferty są niepoprawne np:
72366974451 / 7236642267 / 72361255793 /
Czyli te które wytypowałeś i dlatego otrzymujesz taki komunikat.

**Comment by AlekKlepacz** [comment]
Dwie już eliminowałem pozostała jedna 7236642267 u was jest w archiwum. Możesz ją sprawdzić?

**Comment by PawelTaberski** [comment]
Sprawdziłem, ta oferta została zakończona 3 lutego, także też już jest archiwalna.

**Comment by AlekKlepacz** [comment]
Cześć. I nic się nie zmieniło. Może podam Tobie klucz i sprawdzisz u źródła problemu?

**Comment by PawelTaberski** [comment]
Jasne podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa już bez tych archiwalnych ofert, dodatkowo załącz login usera na jakiego masz identyfikator sesji. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1446 na GitHub-ie.

**Comment by AlekKlepacz** [comment]
Witam, wysłałem dane do konta pojawił się problem nowy i  wyświetla: ERR_INTERNAL_SYSTEM_ERROR: Wewnętrzny bład systemu.

**Comment by MartaNowaczyk** [comment]
Czy ten błąd pojawia się w pojedynczych przypadkach, czy wręcz odwrotnie?

**Comment by AlekKlepacz** [comment]
Witam, problem jest gdzieś od czwartku.  I wczoraj pod wieczór udało mi się zaktualizować sprzedaż a tak cały dzień był problem i to na różnych etapach aktualizacji.

**Comment by AlekKlepacz** [comment]
Dziś już za każdym razem ERR_INTERNAL_SYSTEM_ERROR: Wewnętrzny bład systemu.

**Comment by MartaNowaczyk** [comment]
Potrzebujemy zweryfikować ten problem na przykładzie, dlatego proszę prześlij przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1446 klucz API na którym działasz i dostajesz te błędy oraz podaj wszystkie metody na których napotykasz aktualnie błąd ERR_INTERNAL_SYSTEM_ERROR

**Comment by MartaNowaczyk** [comment]
@AlekKlepacz dostajesz jeszcze te błędy? jeśli tak podeślij dane o które prosiłam.

**Comment by AlekKlepacz** [comment]
Cześć, wysłałem klucz login. Na dzień dzisiejszy działa. Nie zamykaj wątku żebym mógł powrócić.

**Comment by MartaNowaczyk** [comment]
@AlekKlepacz dzięki za informację.
