### ISSUE TITLE
Numer płatnosci

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#1447]
Witam
"Ujednolicamy sposób prezentacji numeru płatności. Już niedługo w całym serwisie będzie dostępny tylko ten numer"
Kiedy planują Państwo wyłączyć krótkie nr płatności ?
Czy maja Państwo informacje od firm kurierskich czy identyfikują już transakcje po nowych numerach (inpost, Ruch)?

pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam
w webAPi będzie po staremu, a wszystkie firmy są poinformowane o zmianach w naszym API. Niektóre testują już nowe integracje, inne są w trakcie migracji.
