### ISSUE TITLE
Encountered end of file

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1448]
U mnie cały czas występuje błąd "Encountered end of file".
Metody:
https://api.allegro.pl/order/events?user.id=4854XXXX&limit=1000&from=1553861444294084 komunikat:Encountered end of file  
https://api.allegro.pl/sale/disputes/?limit=100&offset=0 komunikat:Encountered end of file  
https://api.allegro.pl/sale/user-ratings?user.id=344XXXX&limit=100&offset=0 komunikat:Encountered end of file  
https://api.allegro.pl/order/line-item-id-mappings?lineItemId=afd52XXX-534d-11e9-b853-459b6b861f67 komunikat:Encountered end of file
https://api.allegro.pl/order/checkout-forms/1f774XXX2-5204-11e9-9bbf-b9492e307c73 komunikat:Encountered end of file 

Niestety nie potrafię przeprowadzić analizy ruchu sieciowego.

**Comment by kfijalko** [comment]
Gdy wywołuję te metody w programie Postman to odpowiedź jest prawidłowa. Zwracana jest pusta tablica obiektów ale nie ma żadnych błędów. Czy to jest tak, że powinienem obsłużyć ten błąd jako standardowe działanie metody i uznać, że nie ma nic do zwrócenia, czy jednak jest to błąd po stronie metody?

**Comment by MartaNowaczyk** [comment]
> https://api.allegro.pl/order/events?user.id=4854XXXX&limit=1000&from=1553861444294084 komunikat:Encountered end of file 
tutaj powinieneś dostać pustą tablicę jeśli 1553861444294084 to ostatnie zdarzenie

> https://api.allegro.pl/sale/disputes/?limit=100&offset=0 komunikat:Encountered end of file
jeśli masz jakieś dyskusje to nie powinieneś dostać pustej tablicy, tylko odp. dane

> https://api.allegro.pl/sale/user-ratings?user.id=344XXXX&limit=100&offset=0 komunikat:Encountered end of file
jeżeli masz oceny, to w responsie powinieneś dostać dane

>https://api.allegro.pl/order/line-item-id-mappings?lineItemId=afd52XXX-534d-11e9-b853-459b6b861f67 komunikat:Encountered end of file
dla poprawnego id powinieneś dostać dealId, dla niepoprawnego błąd

>https://api.allegro.pl/order/checkout-forms/1f774XXX2-5204-11e9-9b
dla poprawnego id zamówienia powinieneś dostać jego szczegóły, dla niepoprawnego błąd

**Comment by kfijalko** [comment]
Pani Marto, zgadza się, tak było do tej pory. Od paru tygodni dostaję błąd wywołania curla (piszę w php) z komunikatem "Encountered end of file". Myślałem, że to wynika z ogólnych problemów. Teraz skoro problemy ogólne nie występują to nie wiem jak mam traktować ten błąd.

**Comment by kfijalko** [comment]
Pani Marto @MartaNowaczyk od wczoraj nie otryzmuję już błędów "Encountered end of file". Coś się u Was poprawiło. Ja na razie po swojej stronie nic nie ruszam.

**Comment by kfijalko** [comment]
Właśnie jak pisałem poprzedni w pis to się zaczęło:
```
[2019-04-03 09:45:27] local.CRITICAL: App\Allegro\AllegroClient:App\Allegro\AllegroClient::getAccountDisputesPageData:1094Wystąpił błąd podczas wywoływania https://api.allegro.pl/sale/disputes/?limit=100&offset=0 komunikat:Encountered end of file  
[2019-04-03 09:45:27] local.EMERGENCY: App\Allegro\AllegroClient:App\Allegro\AllegroClient::getAccountDisputes:1191 Nie dostałem danych z AllegroClient::getAccountDisputesPageData.  
```

Trudo, w takim wypadku obsłużę to po swojej stronie.
