### ISSUE TITLE
Problem - Uzupełnij adres e-mail na swoim koncie Allegro

### ISSUE THREAD

**Issue by sw69** [allegro/allegro-api#1449]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**

Cześć,
od piątku otrzymuję od Was zwrotki z tytułem "Uzupełnij adres e-mail na swoim koncie Allegro".
Wszystko świetnie, tylko jak mam zidentyfikować o jaką wiadomość i konto chodzi, gdy codziennie z systemu wychodzi kilka tysięcy wiadomości? Wydaje mi się, że wszystko jest wysyłane poprawnie. Czy można w tym mailu zawrzeć chociaż adresata wiadomości? Ostrzegacie, że niebawem te wiadomości przestaną dochodzić, a ja nawet nie jestem w stanie zdiagnozować, który kupujący nie otrzyma maila.

**Comment by MartaNowaczyk** [comment]
Cześć,
w takiej sprawie napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Tutaj skupiamy się na tematach związanych z API allegro.
