### ISSUE TITLE
Brak płatności w doGetMyIncomingPayments

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#1453]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Metoda: **doGetMyIncomingPayments**
Request: https://pastebin.com/YS1adDn8
Response: https://pastebin.com/ZeEi6Qy0

Czas wykonania requestu: 1554191597 (wto  2 kwi 09:53:17 2019 CEST)

W panelu na stronie allegro.pl widzę, że płatność dla użytkownika o id *7396258* została wykonana i ma id 9309fc59-4ef5-11e9-b942-03eda70412df natomiast przez web api nie mogę jej pobrać. Formularz dostawy jest dostępny i ma id  *991464163*. Proszę o informację o niedostępności płatności przez web api.

**Comment by MartaNowaczyk** [comment]
@manhunto sprawdzamy opisany przypadek

**Comment by manhunto** [comment]
@MartaNowaczyk Minęło już trochę czasu.. czy w temacie pojawiły się jakieś wnioski?
Pojawił się kolejny przypadek pasujący do tego problemu. Brakująca płatność **997373658** dla aukcji **7314244735** i użytkownika o id **10880351**. Próbowałem manipulować requestem, nie podając id użytkownika, numeru aukcji to płatność mimo to nie pojawiała się w odpowiedzi.

Request: https://pastebin.com/3w8WP1VS
Response: https://pastebin.com/7xCy6iFR

W allegro płatność jest oznaczona jako zakończona mimo to nie można jej pobrać.

Proszę o informację czy request jest poprawny i ewentualnie co mogę w nim zmienić, żeby pobrać płatność.

**Comment by PawelTaberski** [comment]
@manhunto Zbadałem to i wygląda na jakiś problem po naszej stronie. Sprawę zgłosiłem do zespołu odpowiedzialnego za tą metodę. Proszę o cierpliwość.

**Comment by manhunto** [comment]
@PawelTaberski Bardzo dziękuję za odpowiedź. Czekam więc na rozwiązanie problemu :)

**Comment by manhunto** [comment]
@PawelTaberski Minął już prawie miesiąc od ostatniej wiadomości. Czy coś wiadomo na temat ewentualnego rozwiązania?

**Comment by MartaNowaczyk** [comment]
@manuhunto niestety sprawa nadal nie rozwiązana. Postaram się przyspieszyć sprawę.

**Comment by manhunto** [comment]
Proszę nie zamykać bo nie dostałem jeszcze odpowiedzi

pt., 14.06.2019, 09:46 użytkownik stale[bot] <notifications@github.com>
napisał:

**Comment by manhunto** [comment]
Proszę nie zamykać bo nie dostałem jeszcze odpowiedzi

**Comment by manhunto** [comment]
@MartaNowaczyk 3 miesiące bez odpowiedzi. Czy coś wiadomo w wątku?

**Comment by PrzemyslawLukanowski** [comment]
@manhunto Niestety nie, poinformujemy, gdy dostaniemy odpowiedź.
