### ISSUE TITLE
Warianty allegro - zakończone oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1454]
Co się dzieje gdy mam połączone oferty w warianty i część z tych ofert po jakimś czasie zostaje zakończona po czym znów po jakimś czasie wznowiona ? Czy na nowo trzeba przypisywać takie oferty do wariantów czy one nadal są połączone ? Z moich obserwacji wynika, że chyba trzeba na nowo przypisywać albo takie oferty zakończone nie są po prostu widoczne w metodzie `GET /sale/offer-variants/{setId}`

**Comment by MartaNowaczyk** [comment]
Jest tak jak piszesz, ale sprawdzę jeszcze dokładnie i dam ci znać.

**Comment by MartaNowaczyk** [comment]
@pietrach dostałam informację, że jeśli oferty nie zmieniły numeru, powinny być nadal połączone w ofertę wielowariantową.
