### ISSUE TITLE
[WebAPI] - doShowItemInfoExt: znowu błędy daty (itStartingTime) !!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1455]
Błędy zaczęły się ujawniać wtedy, kiedy zaczęliście grzebać przy tej metodzie...
Przykłady z kilku kont (na ich sesjach oczywiście):
[1.]
6033095469: 2018-12-05 15:35:10 CET ??
6033095826: 2019-03-12 13:34:55 CET ??
[2.]
5431881405: 2019-01-28 11:42:20 CET ??
5434279469: 2019-03-12 13:36:36 CET ??
[3.]
5970777478: 2019-02-26 08:42:44 CET ??
5976058027: 2019-03-12 13:38:13 CET ??

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - a tak przy okazji, miała Pani zakomunikować zmianę dotyczącą "opakowania" zawartości pola nowego opisu - znacznikiem CDATA, wczoraj to weszło na kolejną metodę po 13:00, no i cisza... ??

**Comment by MartaNowaczyk** [comment]
@FromAnyHole problem z itStartingTime już naprawialiśmy. Sprawdzimy. 
ad. 2 zminiłam informację na poprawną. Od 18 marca stopniowo wprowadzamy zmiany, co oznacza, że nie od razu 100% użytkowników, którzy korzystali z tych metod mogli zobaczyć wprowadzone zmiany.

**Comment by MartaNowaczyk** [comment]
@FromAnyHole podaj proszę jakie wyniki powinny być zwracane.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - tak, naprawialiście problem z błędami w polu 'itStartingTime', ale on zwyczajnie powrócił - po poprzednim zgłoszeniu było przez krótki czas Ok, ale teraz znowu są błędne daty... Moim zdaniem, nagle i znowu bez żadnego komunikatu - zaczęły tam wpadać najróżniejsze daty, a to pole od zawsze transmituje datę PIERWOTNEGO wystawienia przedmiotu (a nie ostatniego wznowienia, albo systemowego odtworzenia - np. po zawieszeniu konta). Nie kombinujcie, bo wiem o co Wam chodzi...

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne requesty wraz z responsami w formacie XML i zaznacz w nich, które daty są błędne i jakie powinny być. Sprawdzimy w czym jest problem.

**Comment by MartaNowaczyk** [comment]
@FromAnyHole Dostałam informację, że problem nie powinien się już pojawiać. Sprawdź jeszcze raz i daj znać.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - teraz jest w porządeczku, to bardzo ważne pole ! Kiedy pojawiały się tam błędne daty dochodziło do kuriozalnych sytuacji, w których inne metody - dla tego samego ID przedmiotu - podawały wcześniejsze daty złożonych ofert kupna, od pierwotnej daty wystawienia przedmiotu. Nie dotykać ;-)
