### ISSUE TITLE
Błędna obligatoryjność parametrów

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#1456]
Występuje problem: 
 - [X ] z metodą WebAPI
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Kategoria z ID: 19640
Metoda: doGetSellFormFieldsForCategory zwraca obligatoryjność jedynie dla pola "Stan".

Data: 2019-04-02 14:42:38 (1554208958)
Wypłeniając, doNewAuctionExt zwraca odpowiedź:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_OBLIGATORY_ATTRIB_NOT_SET</faultcode><faultstring>Nie podano parametru wymaganego dla wybranej kategorii. ()</faultstring><faultactor>doNewAuctionExt - One or more obligatory attributes have not been set.</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>`

Skąd programista ma wiedzieć, które pole "obowiązkowe" nie zostało wybrane?

**Comment by marcinja2** [comment]
coś im te parametry dzisiaj szwankują, tez nie moge wystawic zadnej aukcji

**Comment by mareklemur** [comment]
"Opakowanie" - jak się uzupełni, to przechodzi:)

**Comment by dol1234** [comment]
Czy ktoś z Allegro mógłby do tego zajrzeć? Na chwilę obecną też nie mogę wystawić aukcji przez API ("doNewAuctionExt - One or more obligatory attributes have not been set." - "Nie podano parametru wymaganego dla wybranej kategorii. ()"). Wypełniam wszystkie pola zaznaczone jako wymagane zwracane dla kategorii 79432 (oprócz 24 z wiadomych względów). CheckNewAuctionExt przechodzi bez błędów

**Comment by PawelTaberski** [comment]
Metoda CheckNewAuctionExt nie gwarantuje, że oferta jest kompletna zgodnie z dokumentacją:
"Metoda pozwala na sprawdzenie ogólnych oraz szczegółowych kosztów związanych z wystawieniem oferty przed jej faktycznym wystawieniem."
Aby zweryfikować wasz problem potrzebowałbym pełnego requesta w formacie XML z metody doNewAuctionExt wraz z responsem. Jednakże sprawdziłem i metoda doGetSellFormFieldsForCategory zwraca w polu <ns1:sellFormOpt>1</ns1:sellFormOpt> wartość 1 czyli obowiązkowe, w więcej niż jednym parametrze. Podeślijcie proszę te dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), i zaznaczcie w zgłoszeniu, że dane dotyczą zgłoszenia 1456 na GitHub-ie.

**Comment by dol1234** [comment]
Zgodnie z poleceniem wrzuciłem kompletne logi z komunikacji.

**Comment by marcinja2** [comment]
@dol1234 jak ci cos odpowiedza napisz tu

**Comment by PawelTaberski** [comment]
Sprawdziłem otrzymane dane i rzeczywiście jest jakiś problem z metodą doGetSellFormFieldsForCategory sprawę zgłosiłem z wysokim priorytetem do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by marcinja2** [comment]
Na stronie https://assets.allegrostatic.com/popart-attachments/att-2b46b79b-684f-4391-b04f-caaac681fcb0 w kategorii biografie wspomnienia wymagany jest tajemniczy "rodzaj" metoda doGetSellFormFieldsForCategory nie zwraca żadnych rodzajów a parametr wg w/w listy jest wymagany. Co ciekawe nawet na froncie Allegro nie ma do wypełnienia "rodzaju". O co w tym chodzi?

**Comment by marcinja2** [comment]
na dodatek aukcje wystawiają się bez wymaganego parametru "rodzaj"

**Comment by PawelTaberski** [comment]
Widzę, że w kalendarzu rodzaj jest wpisany jako kwiecień także jeszcze zapewne pojawi się na formularzu i w API.

**Comment by dol1234** [comment]
Nadal nie mogę wystawić aukcji - czy udało się znaleźć przyczynę?

**Comment by dol1234** [comment]
W błędzie zaczęło zwracać pole Autor jako brakujące, jednak pole te nie jest zwracane przez doGetSellFormFieldsForCategory.

**Comment by mareklemur** [comment]
U mnie zgłasza błąd z marką, mimo że pole jest wypełnione.

**Comment by PawelTaberski** [comment]
Dostałem informacje, że parametry zostały odświeżone i problem nie powinien już występować. Czy teraz u was wszystko już działa? Czy nadal są problemy z jakimiś parametrami?

**Comment by marcinja2** [comment]
CYTAT: ERR_OBLIGATORY_ATTRIB_NOT_SET] Nie podano parametru wymaganego dla wybranej kategorii. () KONIEC CYTATU.  NIE PODANO JAKIEGO FID BRAKUJE dotyczy kategorii nr 91438 temat przerabiany wcześniej i większość już zwracanych błędów działało prawidłowo ale w tym przypadku

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa sprawdzimy co brakuje (chyba, że już wiesz o jaki parametr chodzi to napisz proszę) i zgłoszę poprawę komunikatu błędu. W zgłoszeniu zaznacz, że dane dotyczą tiketa numer 1456 na GitHub-ie

**Comment by marcinja2** [comment]
zbadam i prześlę

**Comment by marcinja2** [comment]
to był autor ale fid nie sprawdzałem

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta i responsa w formacie XML (z tym błędem) i słowną informację co brakowało, przetestuje u siebie i zgłoszę sprawę do odpowiedniego zespołu.

**Comment by marcinja2** [comment]
ok ale nie jestem super biegły (piszę tylko na własne potrzeby) w programowaniu, może jakaś podpowiedź o fukcji w php jak zmienić requesta na xml? i resp na xml?

**Comment by PawelTaberski** [comment]
Jakiegoś prostego tłumaczenia nie widzę wszystko zależy jak masz to ograne, jeśli ta oferta jest aktywna to podaj mi jej id postaram się spreparować odpowiedni request bez parametru autor i sprawdzę, czy otrzymam taki sam błąd jak ty.

**Comment by marcinja2** [comment]
8001288839

**Comment by PawelTaberski** [comment]
Zbadałem i zasób /sale/offers/{offerId} zachowuje się jak najbardziej poprawnie otrzymałem informację:
```
    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Missing required parameters: Autor.",
                "details": "",
                "path": "",
                "userMessage": "Missing required parameters: Autor."
            }
        ],
```
**Przetestowałem również w WebAPI** i wydaje się ok:
```
      <SOAP-ENV:Fault>
         <faultcode>ERR_OBLIGATORY_ATTRIB_NOT_SET</faultcode>
         <faultstring>Nie podano parametru wymaganego dla wybranej kategorii. (Autor - fid: 50421)</faultstring>
         <faultactor>doNewAuctionExt - One or more obligatory attributes have not been set.</faultactor>
      </SOAP-ENV:Fault>
```
