### ISSUE TITLE
Brak zdjęć w ofercie, nie ładują się zdjęcia podczas przygotowywania oferty

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1457]
Dzień dobry,
średnio trzy razy dziennie, na różny okres czasu od kilku minut nawet do pół godziny, nie ładują się zdjęcia w ofertach. Podczas podglądu oraz wystawiania oferty. Problem występuje od około 3 miesięcy, będę wdzięczny za informację czy mamy się przyzwyczajać do takiego działania allegro ? 

![image (1)](https://user-images.githubusercontent.com/40828332/55407357-1a6abb80-555e-11e9-9d6d-3fda5b1c9090.png)
![image (2)](https://user-images.githubusercontent.com/40828332/55407358-1b035200-555e-11e9-8632-df6cd6c339dc.png)

**Comment by PawelTaberski** [comment]
Tutaj zajmujemy się tylko sprawami związanymi z API Allegro problemy z formularzem zgłoś proszę przez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)
