### ISSUE TITLE
Problem z edycją parametru

### ISSUE THREAD

**Issue by patrys666** [allegro/allegro-api#1458]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuję edytować parametr (stan produktu) aczkolwiek otrzymuję taki komunikat:

> {
> "errors":[
> {
> "code":"VALIDATION_ERROR",
> "message":"modification should contain exactly 1 element",
> "details":"Invalid value: ModificationDto{additionalServicesGroup=null, afterSalesServiceConditions=null, delivery=null, promotion=null, sizeTable=null, payments=null}",
> "path":"modification",
> "userMessage":"modification should contain exactly 1 element"
> }
> ]
> }

Moje zapytanie wygląda następująco:
`{
"modification":{
"parameters":[
{
"id":11323,
"valuesIds":[
"11323_2"
],
"values":[
],
"rangeValue":null
}
]
},
"offerCriteria":[
{
"offers":[
{
"id":"ID_OFERTY"
}
],
"type":"CONTAINS_OFFERS"
}
]
}`

Siedzę już trochę czasu nad tym i nie mogę dojść co robię nie tak. Będę wdzięczny za wszelką pomoc.

**Comment by PawelTaberski** [comment]
Tak, jak otrzymałeś w opisie tym zasobem przypiszesz grupowo tylko: usługi dodatkowe, promocje, tabele rozmiarów, faktury. Aby wyedytować parametr skorzystaj z PUT na zasobie /sale/offers/{offerId}
Pamiętaj aby podać całą strukturę oferty. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#2).
