### ISSUE TITLE
wyszukiwarka allegro

### ISSUE THREAD

**Issue by mmfreq** [allegro/allegro-api#1459]
od piątku 29.marca  nie działa wyszukiwanie ofert po opisie aukcj,i na stronie allegro.pl jak i w metodzie GET /offers/listing np. w opisie aukcji mam kilkanaście słów i jedne znajduje innych nie, sprawdziłem na różne sposoby efekt jest ten sam mam wrażenie że jeżeli tekst w opisie jest nagłówkowy to nie widz,i już wcześniej bywały takie problemy ale po kilkunastu godzinach wracało do normy.

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda zwraca prawidłowe wyniki. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i zaznacz, jakie dane Twoim zdaniem się nie zgadzają. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1459 na GitHub-ie

**Comment by mmfreq** [comment]
wysłałem, ale tu nie chodzi tylko o rest api ale i na stronie www.allegro.pl jest ten sam problem:
numer aktywnej aukcji 7948445814 i jest w opisie "Aukcja dotyczy: Kołpak koła - indeks-560763" szukam tego tekstu lub fragmentu tego tekstu z opcją szukania w opisach i nic nie znajduje, a np. szukam tekstu "Nr vin pochodzenia części: VF1KG0G0625249771" który też jest w tym opisie i bez problemu znajduje tą aukcję.

**Comment by PawelTaberski** [comment]
Jak tylko otrzymam dane zapoznam się z nimi i dam znać.

**Comment by PawelTaberski** [comment]
Zbadałem sprawę i rzeczywiście fraza ta nie jest wyszukiwana mimo, że słowa obok Kołpak+koła już tak. Zgłosiłem to do odpowiedniego zespołu. Prośba o cierpliwość.

**Comment by mmfreq** [comment]
Jaki może być czas rozwiązania problemu, potrzebuję tą informację do dalszej pracy, nawet jak będzie to 3 miesiące to dobrzy byłoby wiedzieć.

**Comment by PawelTaberski** [comment]
Widzę, ze zespół pracuje nad tym zadaniem, proszę o jeszcze trochę cierpliwości.

**Comment by mmfreq** [comment]
Jak sytuacja, bo widzę że coraz bardziej rozjeżdża się wyszukiwanie?

**Comment by PawelTaberski** [comment]
Poprawka jest przygotowana, niedługo powinna zostać wdrożona.
