### ISSUE TITLE
[WebAPI] Tabela rozmiarów

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#146]
Czy istnieje możliwość przy tworzeniu nowej lub modyfikacji aukcji ustawić utworzoną w panelu allegro tabelę rozmiarów ?

**Comment by KrzysztofLukanowski** [comment]
Nie zrobisz tego w WebAPI, ale tabelę rozmiarów możesz za pośrednictwem [REST API](https://developer.allegro.pl/sale/).

**Comment by hjgtutgb** [comment]
Ciekawe jak
"sizeTable": null,                          -- niedostępne, identyfikator tabeli 
                                                rozmiarów, opcja jeszcze niedostępna

**Comment by KrzysztofLukanowski** [comment]
Przepraszam, dopiero udostępnimy taką możliwość - poinformujemy o tym.
