### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by ololower** [allegro/allegro-api#1460]
Dzień dobry Załóż konto na [allegrosandboxI](https://allegro.pl.allegrosandbox.pl)

Oczekuję aktywacji 4 dnia. Czy możesz aktywować moje konto

Login: barbercompany1

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto, abym mógł zakończyć aktywację podeślij przez zakładkę moje konto jakieś dowolne dwa pliki i daj znać jak to zrobisz.

**Comment by ololower** [comment]
Dodano nowy produkt z dwoma obrazami, ale nie mogę go opublikować. Czy to wystarczy, czy dodać pliki w inny sposób?

**Comment by ololower** [comment]
> Я предварительно активировал вашу учетную запись, чтобы завершить активацию, отправить любые два файла через вкладку своей учетной записи и сообщить мне, как вы это сделаете.

**Comment by PawelTaberski** [comment]
W tej zakładce [ustawienia konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php). Musisz wysłać dowolne dwa pliki jako:

- Skan nadania NIP *
- Skan zaświadczenia o wpisie do ewidencji działalności gospodarczej *

**Comment by ololower** [comment]
Dzięki za napiwek!
Przesłane pliki.

**Comment by PawelTaberski** [comment]
@ololower Konto już aktywowałem w pełni.
