### ISSUE TITLE
/order/checkout-forms?limit=50&status=READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by bluesoftware** [allegro/allegro-api#1461]
Witam

Zauważyłem problem podczas pobierania zamówień dla ['payment']['type']="ONLINE" czasem w ogóle nie pojawia się operator: ['payment']['provider'] jeśli ta zmienna jest pusta to czym jest robiony przelew?

```
/order/checkout-forms/0619f440-5511-11e9-8519-3fab1fe0362d
/order/checkout-forms/dc4836a2-5267-11e9-a485-7babe1b9d8c8
```

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i trace id, z informacją jakiego pola brakuje. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1461 na GitHub-ie.
