### ISSUE TITLE
Braki w dokumentacji /sale/offers

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#1462]
Czy mogę prosić o uzupełnienie i utrzymywanie aktualności dokumentacji tego zasobu (pozostałych z resztą też).
Brakuje np. attachments, w description sekcji które mają obrazek i powiązany identyyfikator obrazka itd.
W aplikacjach gdzie stosuje się silne typowanie takie braki powodują, że albo dostajemy przy aktualizacji 400-tkę albo usuwamy część informacji z oferty. Np. wywalamy załączniki.

**Comment by PawelTaberski** [comment]
Widzę, że w naszym [poradniku odnośnie wystawiania ofert](https://developer.allegro.pl/sale/#step-1) są opisane załączniki, ale w przykładowych requestach pełnej oferty rzeczywiście brak struktury:
`    "attachments": [],`
Oczywiście uzupełnimy to, czy jeszcze gdzieś widzisz taki brak.
