### ISSUE TITLE
Blokada ip

### ISSUE THREAD

**Issue by sense6** [allegro/allegro-api#1464]
Przy każdym zapytaniu o access_token (code flow), dostaję zwrotkę 403 forbidden oraz html'a, w którym jest informacja o zablokowaniu zapytania z powodu zakwalifikowania go jako złośliwe.
Parę poprzednich zapytań działało poprawnie.

ostatni kod błędu: 9788da49c4c8fe73
login: Client:44149082
sandbox

Proszę o odblokowanie.

**Comment by PawelTaberski** [comment]
Nie podałeś jaki dokładnie dostałeś komunikat blokady, jednakże informacje o rodzaju blokad i w jaki sposób je zdjąć znajdziesz [tutaj](https://allegro.pl/webapi/faq.php#faq_1).
