### ISSUE TITLE
Pobranie daty wystawienia dla wszystkich aukcji zautoryzowanego użytkownika.

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#1465]
Chciałabym otrzymać przez REST API daty rozpoczęcia wszystkich aukcji zautoryzowanego użytkownika.

Wydawało mi się zgodnie z dokumentacją, że wystarczy na zasobie GET /sale/offers sterując limitem i offsetem porcjami wszystko pobrać i będę miała pola startingAt lub startedAt (swoją droga nie wiem czym się różnią). Jednak pobierając dane dla trwających aukcji, response nie zawiera publication z tymi datami.

W takim razie nasuwa się myśl, że mając numery wszystkich tych aukcji z zasobu GET /sale/offers za pomocą zasobu GET/sale/offers/{offerId} sprawdzić szczegóły każdej aukcji po kolei i pobrać pole createdAt. Tylko to jest mnóstwo zapytań, bo aukcji jest dużo...

Czy to jedyny sposób? Czy być może te pola się pojawią, tak jak opisuje to dokumentacja?

**Comment by PawelTaberski** [comment]
Różnica między tymi polami jest taka, że jedno oznacza planowaną datę wystawienia a drugą datę w której oferta została wystawiona:
```
                "startingAt": null,                     -- data zaplanowanego wystawienia 
                "startedAt": "2018-10-11T12:16:02Z",    -- data wystawienia oferty
```
Przetestowałem i metoda zwraca te pola dla ofert aktywnych, może szukasz w ofertach typu INACTIVE.
Jak wygląda zapytanie jakie wysyłasz?
Poradnik w jaki sposób korzystać z tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#1).
