### ISSUE TITLE
doBidItem problem

### ISSUE THREAD

**Issue by Lipq1** [allegro/allegro-api#1466]
Od paru dni nie działa licytowanie za pomocą doBidItem.

Po wysłaniu requesta dostaję:
`org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not alowed in prolog.
Axis Fault
faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.userException ......`

Coś nie tak z api? nie widzę żadnych zmian które miałyby wpłynąć na licytacje.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1466 na GitHub-ie.

**Comment by Lipq1** [comment]
Samo znów zaczęło działać.
Zamykam
