### ISSUE TITLE
[REST] Kalkulator opłat vs koszt oferty vs wyszukiwanie ofert promowanych

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#1467]
Dzień dobry, 

proszę o kilka wyjaśnień dotyczących metod RESTowych: 

POST /pricing/fee-preview 
Metoda ta zwraca coś takiego - [ Pozostałe opłaty  - Wystawienie oferty - 0,30 PLN / 10 dni ],
pomimo tego że klient ma inne warunki.

Metoda ta również informuje klienta że - [ Wyróżnienie - 19,00 PLN / 10 dni ]
podczas gdy klient za to nie płaci 19 PLN, co widać na stronie Allegro. Tam widoczna jest inna kwota ?

Dalej pojawia się pytanie, czy poprzez REST można pobrać informację o tym ile pakietów promocyjnych zostało jeszcze do wykorzystania ? Na stronie allegro.pl taka informacja jest widoczna.

Następne pytanie dotyczy wyszukiwania 
metoda  POST /sale/offers/ - chcę wyszukać promowane oferty tak jak to mam możliwość zrobić na stronie serwisu [opcje promowania - wyróżnienie], nie widzę tego w REST API ?

Następnie Metoda GET /pricing/offer-quotes
Metoda ta zwraca informację że o określonej dacie zostanie pobrana określona kwota w wysokości 19 PLN podczas gdy na stronie serwisu przy tej aukcji mamy:
[ Opłata za wyróżnienie | 13.04.2019 (za 9 dni) | 0,00 zł / 10 dni ]

Tak oto dobrnęliśmy do końca, choć nie jest łatwo. Pytanie które się pojawia - do czego służą te metody skoro nie do końca mówią prawdę ? 

Pozdrawiamy www factory

**Comment by PawelTaberski** [comment]
Datę naliczenia kolejnej opłaty powinieneś sprawdzać zasobem POST /sale/loyalty/promotions, więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/charges/).
Czy w zasobie POST /pricing/fee-preview uzupełniłeś parametr:
`"includeQuotingBundles": true,                -- niewymagane, uzwględnij pakiety z Centrum Zniże`
Zasób POST /sale/offers/ służy do utworzenia draftu oferty. Zapewne masz na myśli GET /sale/offers/ i obecnie w tym zasobie nie ma możliwości sortowania po opcji promowania. Więcej informacji na temat możliwości tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#1).

**Comment by wwwfactory** [comment]
Dzień dobry, 
Oczywiście pytanie dotyczyło metody GET na tym zasobie. Pytanie pojawiło się ponieważ nie znalazłem tego w dokumentacji. 
W tym miejscu pojawia się pytanie czy macie w planach rozwojowych  dodanie możliwości wyszukiwania po promowanych ofertach w przyszłości ? 

i jeszcze jedno,
 "duration":"PTxxH",                      -- wymagane, czas trwania oferty, możliwe wartości:
jak to się ma do ofert które są do wyczerpania zapasów ?

**Comment by wwwfactory** [comment]
Panie Pawle ale to pierwsze zdanie to chyba nie dotyczy POST /sale/loyalty/promotions ? 

Mam wrażenie że nie wyraziłem się jasno, nie chcę sprawdzać swoich pakietów promocyjnych tylko chcę poprzez REST dowiedzieć się o to co widzę w
Moja Sprzedaż -> Centrum zniżek -> Przyznane Pakiety .....

**Comment by PawelTaberski** [comment]
Rozumiem, nie ma obecnie zasobu, którym można by pobrać takie dane. Jeśli wdrożymy taki zasób to poinformujemy o tym w dedykowanym komunikacie.
