### ISSUE TITLE
[WebAPI] doSendRefundForm nie działa 

### ISSUE THREAD

**Issue by Bobson1** [allegro/allegro-api#147]
Witam, 
Mam problem z funkcją "doSendRefundForm". Kiedy próbuję wysłać formularz zwrotu prowizji dostaję taki komunikat: 
"Client: Function ("doSendRefundForm") is not a valid method for this service". 

kod php:
```
<?php

try
{
	#połoączenie z allegro
	$client = new SoapClient($config['url'], array('trace' => 1));
	$version = $client->doQuerySysStatus(1, $config['kraj_pl'], $config['webapi_key']);
	$session = $client->doLoginEnc($config['login'], base64_encode(hash('sha256', $config['pass'], true)),$config['kraj_pl'] , $config['webapi_key'], $version['ver-key']);
	$session_id = $session['session-handle-part'];
	
	$deals = $client->doGetRefundsDeals($session_id, array(), 'asc', 100);
	$deals = $deals['deals-list']; 
	
	foreach($deals as $deal)
	{
		if($deal->{'payment-status'} != 'complete' && $deal->{'time-left'} < 37)
		{
			$refund = $client->doSendRefundForm($session_id, $deal->{'deal-id'}, 1, $deal->{'bids-count'});
			print_r($refund);
		
		}	
	}
}
catch(SoapFault $error)
{
	echo $error->faultcode.': '.$error->faultstring.' line: '.$error->getLine(); 
}
```
Coś nie tak z kodem czy coś po stronie Allegro?

**Comment by AniaMalinowska** [comment]
Na wstępie zwracam uwagę, aby korzystać z najnowszej wersji [WSDL](https://webapi.allegro.pl/uploader.php?wsdl) dla Allegro WebAPI.
Sprawdziliśmy i metoda działa prawidłowo. Nie wspieramy API na poziomie kodu PHP.  Abyśmy mogli zweryfikować zgłoszenie, prosimy o [podesłanie](https://pomoc.allegro.pl/kontakt/#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) plików *.XML z request i response z komunikatem błędu. Prosimy podać tutaj numer Ticketa.
