### ISSUE TITLE
Zamykanie lub usuwanie szablonu?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1470]
Witam,
Czy na ofercie która jest w statusie INACTIVE mogę wykonać operację END? Jeżeli nie to w jaki sposób mogę usunąć taką ofertę by nie wisiała w systemie bez sensu?

**Comment by PawelTaberski** [comment]
Oferty nie aktywowanej nie możesz dezaktywować. Jednakże jak najbardziej możesz ją usunąć zasobem: [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE)
