### ISSUE TITLE
[webAPI] Typy płatności

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1471]
Metoda: doGetPostBuyFormsDataForSellers, postBuyFormPayType - zwraca typ płatnośći
Co oznacza: jp
od razu odpowiadam na pytanie , nie ma tutaj: https://allegro.pl/webapi/tutorials.php/tutorial/id,100441
Prośba o aktualizację

I od razu sugestia by w restAPI dało się to pobrać jako słownik

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) numer oferty, login kupującego i datę sprzedaży w której widzisz takie dane, sprawdzimy to. W zgłoszeniu dodaj, że dotyczy ono ticketa numer 1471 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Sprawdziłem i jest to metoda Apple Pay. Dokumentację uzupełniłem.

**Comment by SebastianOzdoba** [comment]
Dzięki!
