### ISSUE TITLE
[REST API] Pobieranie liczby odwiedzin i obserwowanych

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#1472]
Zasobem GET /sale/offers pobieram dane na temat liczby odwiedzin i obserwowanych na aukcjach, pola watchersCount i visitsCount.
Potrzebuję się upewnić czy wartości w tych polach dotyczą całego czasu trwania oferty i czy nie ulegają kasowaniu np. po wznowieniu aukcji lub innych operacjach.

**Comment by PawelTaberski** [comment]
Ten zasób jest odzwierciedleniem zakładki Moje oferty, i podaje tak jak na froncie dane z ostatnich 30 dni. Obecnie oferty na zakańczasz a ją wstrzymujesz, ale dane w dalszym ciągu są z ostatnich 30 dni. Także jak wstrzymasz ją na 30 dni i wznowisz to dane się wyzerują.
