### ISSUE TITLE
/order/events nie zwraca wszystkich zdarzeń?

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#1475]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Za pomocą /order/events?from=1551262605672525 nie mogę pobrać zdarzenia dotyczącego pewnego zamówienia. Są zdarzenia poprzednie i następne (chronologicznie), a tego nie ma. A chodzi o zdarzenie, które w starym webapi lokalizuję tak: journalId=4427017877 dealid=2006288479. Dlaczego?

pozdrawiam

Sergiusz Brzeziński

**Comment by PawelTaberski** [comment]
Podeślij proszę, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) id oferty, login kupującego i datę sprzedaży sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1475 na GitHub-ie.
