### ISSUE TITLE
REST /offers/listing searchMeta/totalCount nie zgadza się z wyszukiwarką

### ISSUE THREAD

**Issue by rafalkrupinski** [allegro/allegro-api#1476]
Wysyłam zapytanie:
https://api.allegro.pl/offers/listing?fallback=false&category.id=257753&starting_time=P2D&parameter.215882=272070&parameter.11323=2&178=178_1

w searchMeta/totalCount dostaje 1400 (przypadkiem okrągła liczba , wczoraj miałem 1409)
Jednocześnie w wyszukiwarce wysyłam te same parametry i dostaję 87 wyników.

<img width="709" alt="Screenshot 2019-04-04 at 19 26 31" src="https://user-images.githubusercontent.com/3732079/55575623-95270880-570f-11e9-9ddb-e48fc0dbaa0f.png">

**Comment by rtnet-pl** [comment]
Wydaje mi się, że w rest nie działa parametr starting_time, zatem otrzymujesz wszystkie oferty (także te wystawione wcześniej)

**Comment by PawelTaberski** [comment]
@rafalkrupinski Dokładnie tak jak napisał @rtnet-pl w tym zasobie nie ma takiego parametru do sortowania/filtrowania wszystkie filtry oprócz tych podstawowych znajdziesz w strukturze filters w wywołaniu. 
Więcej informacji na temat tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by rafalkrupinski** [comment]
@PawelTaberski 
Słuszna uwaga, parametr nazywa się startingTime i jest zdefiniowany jako parametr (filters) dla tej kategorii.

```json
    {
      "id": "startingTime",
      "type": "SINGLE",
      "name": "wystawione w ciągu",
      "values": [
...
        {
          "value": "P2D",
          "name": "2 dni",
          "selected": true
        },
```

Po poprawieniu zapytania REST otrzymuję 893 wyniki.
Jednocześnie to samo wyszukiwanie na stronie daje 87 wyników wystawionych w ciągu ostatnich dwóch dni oraz 1363 wystawione bez limitu daty.

Pozdrawiam

**Comment by rafalkrupinski** [comment]
Wydaje mi się, że pozmieniały się wartości niektórych parametrów. Zaktualizowałem i dostaję taką samą liczbę wyników.
