### ISSUE TITLE
Error: Missing required parameters: Złącza

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#1477]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

 Trace-Id=[d719fc3e1d4616fd]

Chcę zaktualizować aukcję metodą /sale/offers/7494349964  . Pobieram aktualną aukcję  /sale/offers/7494349964 zmieniam np ilość i odpowiedzi otrzymuje:

{"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Złącza.","details":"","path":"","userMessage":"Missing required parameters: Złącza."}]}

Co ciekawe ten sam kod na 10 prób zrobi to 3 razy a kolejne 7 wyrzuca powyższy błąd.
Prośba o weryfikację co może być nie tak. Trace-Id powyżej.

Pełen curl przekazany przez formularz kontaktowy.

**Comment by PawelTaberski** [comment]
Przetestowałem na danych jakie podesłałeś i zgodnie z komunikatem brak obowiązkowego parametru, który jest wymagany w tej kategorii:
```
        {
            "id": "212938",
            "name": "Złącza",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false
            },
            "dictionary": [
                {
                    "id": "212938_1",
                    "value": "microUSB"
                },
                {
                    "id": "212938_2",
                    "value": "czytnik kart pamięci"
                },
                {
                    "id": "212938_4",
                    "value": "nanoSIM"
                },
                {
                    "id": "212938_8",
                    "value": "microSIM"
                },
                {
                    "id": "212938_16",
                    "value": "brak"
                }
            ],
            "restrictions": {
                "multipleChoices": true
            }
        },
```
Po dodaniu tego parametru brak już komunikatu o błędach.

**Comment by Raafal78** [comment]
A który to był parametry jeżeli można zapytać?

I gdzie można sprawdzić dla jakiej kategorii które parametry są wymagane? 

Dnia 5 kwietnia 2019 12:01:21 CEST, PawelTaberski <notifications@github.com> napisał(a):
>Przetestowałem na danych jakie podesłałeś i zgodnie z komunikatem brak
>obowiązkowego parametru, który jest wymagany w tej kategorii:>
>```>
>        {>
>            "id": "212938",>
>            "name": "Złącza",>
>            "type": "dictionary",>
>            "required": true,>
>            "unit": null,>
>            "options": {>
>                "variantsAllowed": false,>
>                "variantsEqual": false>
>            },>
>            "dictionary": [>
>                {>
>                    "id": "212938_1",>
>                    "value": "microUSB">
>                },>
>                {>
>                    "id": "212938_2",>
>                    "value": "czytnik kart pamięci">
>                },>
>                {>
>                    "id": "212938_4",>
>                    "value": "nanoSIM">
>                },>
>                {>
>                    "id": "212938_8",>
>                    "value": "microSIM">
>                },>
>                {>
>                    "id": "212938_16",>
>                    "value": "brak">
>                }>
>            ],>
>            "restrictions": {>
>                "multipleChoices": true>
>            }>
>        },>
>```>
>Po dodaniu tego parametru brak już komunikatu o błędach.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/allegro/allegro-api/issues/1477#issuecomment-480219588

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PawelTaberski** [comment]
Można to sprawdzić przy pomocy zasobu /sale/categories/{categoryId}/parameters więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#parameters).

**Comment by Raafal78** [comment]
W dokumentacji jest tak:
" Edycja pojedynczej oferty
Na początek możesz pobrać ofertę, którą chcesz edytować za pomocą metody GET na zasobie sale/offers/{offerId}. **Następnie metodą PUT na zasobie /sale/offers/{offerId} prześlij ofertę z wprowadzonymi zmianami.** Zmiany możesz wprowadzać w każdej ofercie - tej trwającej i tej zakończonej. Jeśli prześlesz niekompletne dane, to w polu validation wyświetlimy:

    co powinieneś uzupełnić,
    błędy, jakie pojawiły się w twojej ofercie

**Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty.**
"

**To czy nie powinno być tak że jak pobieram dane o danej aukcji: GET na zasobie sale/offers/{offerId}, 
to ta metoda powinna zwrócić mi dane  potrzebne do modyfikacji oferty ?**

Ja już używam do modyfikacji oferty  PUT na zasobie /sale/offers/{offerId} i to działa tak ok 3 na 10 przypadków. Więc widzę jakąś niespójność w walidacji. Raz informacje szczegółowe o kategoriach są potrzebne a raz nie.

**Comment by Raafal78** [comment]
W dokumentacji jest tak:
" Edycja pojedynczej oferty
Na początek możesz pobrać ofertę, którą chcesz edytować za pomocą metody GET na zasobie sale/offers/{offerId}. Następnie metodą PUT na zasobie /sale/offers/{offerId} prześlij ofertę z wprowadzonymi zmianami. Zmiany możesz wprowadzać w każdej ofercie - tej trwającej i tej zakończonej. Jeśli prześlesz niekompletne dane, to w polu validation wyświetlimy:

co powinieneś uzupełnić,
błędy, jakie pojawiły się w twojej ofercie

Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty.
"

To czy nie powinno być tak że jak pobieram dane o danej aukcji: GET na zasobie sale/offers/{offerId},
to ta metoda powinna zwrócić mi dane potrzebne do modyfikacji oferty ?

Ja już używam do modyfikacji oferty PUT na zasobie /sale/offers/{offerId} i to działa tak ok 3 na 10 przypadków. Więc widzę jakąś niespójność w walidacji. Raz informacje szczegółowe o kategoriach są potrzebne a raz nie.

**Comment by PawelTaberski** [comment]
Metoda GET zwraca Tobie wszystkie pola danej oferty, ale nie waliduje jej. Dopiero przy PUT przebiega walidacja i dostajesz informacje o np. brakujących wymaganych parametrach.

**Comment by Raafal78** [comment]
Pytanie dla konkretnej aukcji: 7494349964
Aukcja ta nie ma wartości parametrów 'Złacza' , mogę się domyślać że aukcja jest dawno wystawiona.
Allegro nie wymusza też ręcznej modyfikacji tej aukcji żeby dodać te parametry.

Metoda GET na zasobie sale/offers/{offerId} nie zwraca wartości tego parametru - Dlaczego ?  . Skoro 'Złacza' są jako parametr Required według: /sale/categories/{categoryId}/parameters.  Widzę że jak bym chciał wystawić aukcję w tej kategorii to musiałbym teraz podać te wartości. 

Chyba GET na zasobie sale/offers/{offerId} powinien zwracać wartość tego parametru jeżeli później jest on walidowany / wymagany ?

Dodatkowo po co jest walidacja, jeżeli żeby update zadziałał to trzeba przesłać defaultowe wartości parametrów?. Nie dodaje to żadnych dodatkowych informacji dla aukcji i dla klienta. 

Mam setki aukcji które są dawno wystawione i teraz dużej części aukcji nie mogę zaktualizować.

**Comment by PawelTaberski** [comment]
Tak, jak pisałem metoda GET nie waliduje oferty. Możesz śledzić zmiany w parametrach i od kiedy staną się obowiązkowe na [dedykowanej stronie](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach). Jeśli masz ofertę z brakami to przy jakiejkolwiek próbie edycji, ceny, opisu itp. dostaniesz informacje o braku danego parametru. Parametr powinieneś uzupełnić zgodnie z tym jakie cechy ma produkt jaki sprzedajesz. Dzięki czemu kupujący łatwiej go znajdą i jest większa szansa na sprzedaż.

**Comment by Raafal78** [comment]
Prawie ok ale, ja robię aktualizacje ofert dla klientów. Ich aukcje są dawno wystawione.
Teraz nie mogę ich zaktualizować przez ten brakujący parametr.

Sam nie mogę dodać tej wartości bo to nie moje produkty i nie znam ich właściwości. 
Zatem jeżeli chce dodać np: Ean do aukcji to nie mogę tego łatwo zrobić. 
Ewentualnie wysyłam pusta tablice dla brakującego parametru. To nic nie wnosi do aukcji ale żeby znaleźć ten brakujący parametr to się trzeba będzie się sporo  na kombinować. Jeszcze nawet nie wiem jak to zrobić :( 

Widzę w naszym systemie że temat dotyczy setek aukcji. 

Czy rozważaliście zwracania dla aukcji wymaganych parametry by umożliwić łatwiejsze aktualizowanie aukcji. Ewentualnie dla klientów jakieś notyfikacje w portalu że dla danych aukcji trzeba uzupełnić nowe parametry? 








Dnia 10 kwietnia 2019 09:17:31 CEST, PawelTaberski <notifications@github.com> napisał(a):
>Tak, jak pisałem metoda GET nie waliduje oferty. Możesz śledzić zmiany
>w parametrach i od kiedy staną się obowiązkowe na [dedykowanej
>stronie](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).
>Jeśli masz ofertę z brakami to przy jakiejkolwiek próbie edycji, ceny,
>opisu itp. dostaniesz informacje o braku danego parametru. Parametr
>powinieneś uzupełnić zgodnie z tym jakie cechy ma produkt jaki
>sprzedajesz. Dzięki czemu kupujący łatwiej go znajdą i jest większa
>szansa na sprzedaż.>
>>
>-- >
>You are receiving this because you modified the open/close state.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/allegro/allegro-api/issues/1477#issuecomment-481565757

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PawelTaberski** [comment]
Parametry na froncie stają się około miesiąca wcześniej obowiązkowe niż w API, dodatkowo sprzedający ma udostępnione narzędzie, aby grupowo uzupełnić brakujące parametry. Więcej na ten temat znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/dowiedz-sie-kiedy-i-ktore-parametry-beda-obowiazkowe-5VXXwP0P2C9). 
Obecnie nie mamy w planach zwracania wymaganych parametrów z jakąś defaultową wartością, bo takie wartości mogłyby wpłynąć negatywnie na wyszukanie takiej oferty.

**Comment by Raafal78** [comment]
Ok dzięki za info, przydatny artykuł. 
Proszę jednak o weryfikację aukcji:  7494349964

Według tego dokumentu (https://assets.allegrostatic.com/popart-attachments/att-1ee243a7-9a7c-487f-bf2b-05019e602029 ) dla tej kategori nie mam nowego nowego wymaganego parametru 'Złacza'
Dodatkowo aukcja była wznawiana na początku kwietnia i system do automatycznego wznawiania ją 'puścił' .

**Comment by PawelTaberski** [comment]
Widzę, że w rozpisce rzeczywiście zabrakło dodania tej kategorii. Dlatego zawsze najlepiej sprawdzać obowiązkowość parametrów w zasobie GET /sale/categories/{catId}/parameters
