### ISSUE TITLE
Order/markAsSent 

### ISSUE THREAD

**Issue by bluesoftware** [allegro/allegro-api#1478]
Czy w jakiś sposób mogę oznaczyć zamówienie jako wysłane?

**Comment by PawelTaberski** [comment]
Jeśli mówisz o opcji jaka jest dostępna w zakładce zamówienia w Moim Allegro, to oznaczenie służy tylko do sortowania danych na froncie. Obecnie nie ma możliwości oznaczenia zamówień jako wysłane przez API.
