### ISSUE TITLE
Częsty bład 422 przy aktualizacji

### ISSUE THREAD

**Issue by mistrz7** [allegro/allegro-api#1479]
Około połowa przesyłanych aktualizacji kończy się błędem: 422 i komunikatem: {"errors":[{"code":"VALIDATION_ERROR","message":"Missing required parameters: Złącza.","details":"","path":"","userMessage":"Missing required parameters: Złącza."}]}
Co ciekawe nie przesłam żadnego stringu "Złącza". Wysyłany jest json, który wcześniej jest pobrany po zmodyfikowaniu ilości i jak pisałem na początku błąd dotyczy ok połowy zapytań,

**Comment by Maczuga** [comment]
Zapewne doszedł do kategorii nowy parametr, który jest oznaczony jako wymagany.

**Comment by Maczuga** [comment]
Swoją drogą - aktualizacje ofert są trochę nieprzemyślane. Podam na naszym przykładzie:

Mamy 1500+ ofert. Synchronizacja zmian co 5-10 minut. Przychodzi moment, że trzeba dla 100+ produktów zmienić stan lub ceny - w każdej ofercie na inną wartość. 

Pojedynczy update przy próbie wykonania w powyższym przypadku zwróci validation error - jak mniemam zmiana ceny lub ilości nie zostanie w takim przypadku zatwierdzona?

/sale/offer-price-change-commands/{commandId} - (+ do edycji ilości przedmiotów) niby jest masowa edycja, ale zakłada ona, że dla każdego produktu nowa wartość będzie taka sama. Jak chcę zaktualizować te 100 produktów to i tak muszę robić 100 requestów do ilości i 100 requestów do ceny zamiast ograniczyć się do 1 requesta z edycją cen (podanie ID oferty + nowej ceny w tablicy) i 1 requesta do ilości (jak wcześniej) - bez triggerowania błędów o parametrach, bo w tym przypadku byśmy ich nie podawali.

**Comment by PawelTaberski** [comment]
Nawet jak tylko chcesz zmodyfikować w ofercie stock to musi być ona kompletna w tym przypadku widzę, że brakuje parametru, który jest obowiązkowy:
```
        {
            "id": "212938",
            "name": "Złącza",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false
            },
            "dictionary": [
                {
                    "id": "212938_1",
                    "value": "microUSB"
                },
                {
                    "id": "212938_2",
                    "value": "czytnik kart pamięci"
                },
                {
                    "id": "212938_4",
                    "value": "nanoSIM"
                },
                {
                    "id": "212938_8",
                    "value": "microSIM"
                },
                {
                    "id": "212938_16",
                    "value": "brak"
                }
            ],
            "restrictions": {
                "multipleChoices": true
            }
        },
```
