### ISSUE TITLE
Zmiana typu bazowego fValueDateTime

### ISSUE THREAD

**Issue by AniaMalinowska** [allegro/allegro-api#148]
Zmieniliśmy typ bazowy **fValueDateTime** w [WSDL](https://webapi.allegro.pl/uploader.php?wsdl) dla Allegro WebAPI. Zmiana dotyczy wartości pola dla dat: **fvalueDatetime** - zmieniliśmy typ **float** na **long**.

Zmianę wdrożyliśmy, ponieważ zależało nam, aby uspójnić typ danych.

**Comment by Onixarts** [comment]
Zmiana zasadna, ale jednak wsteczna kompatybilność została złamana i mamy przez to wiele zgłoszeń od użytkowników i trzeba wypuszczać nową wersję programu. Czy możecie założyć, że każda zmiana w API jest **zawsze istotna** i nigdy więcej nie robić jakichkolwiek zmian, nawet poprawy literówki bez ogłoszenia tego wcześniej?

**Comment by AniaMalinowska** [comment]
W przyszłości postaramy się komunikować takie zmiany z wyprzedzeniem, przepraszamy za zamieszanie.
