### ISSUE TITLE
[RestAPi] Pobranie oferty z dnia zakupu

### ISSUE THREAD

**Issue by damianSzechlicki** [allegro/allegro-api#1480]
Jak się wejdzie przez panel w opcje zamówienia i kliknie jakąś ofertę to wyświetla się komunikat:
Sprzedawca zmienił tę ofertę.
Widzisz stan z dnia zakupu (wtorek 2 kwietnia, 11:52:16).

Czy podczas pobierania zamówienia można uzyskać dostęp do takiej oferty korzystając z RestApi?

**Comment by PawelTaberski** [comment]
Nie ma takiej możliwości, ale w zamówieniu będziesz miał wszystkie dane typu cena itp. które były ustawione w dniu jaki kupujący dokonał zakupu.
