### ISSUE TITLE
doGetMyIncomingPayments - Opóźnienie w pojawianiu się danych

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1481]
Takie pytanie. Czy jest możliwe, żeby płatności pobierane w WebApi za pomocą doGetMyIncomingPayments pojawiały się w systemie, nie w momencie, kiedy została zrealizowana płatność (czy parę minut później) ale z opóźnieniem kilkugodzinnym?
Pobieram kolejne płatności ustalając transRecvDateFrom i transRecvDateTo i nigdy nie miałem z tym większych problemów. Od początku kwietnia gdy zaciągam dane z samego rana, nie pobierają się transakcję z nocy, wpadają dopiero gdy powtórzę requesta z tym samym zakresem czasowym jakiś czas później. Ponieważ zawsze dotyczy to godzin nocnych, pomyślałem, że może chodzić o jakieś prace serwisowe...

**Comment by PawelTaberski** [comment]
Wszystko zależy od ilości zadań na kolejce oczywiście również mogły mieć wpływ jakieś prace serwisowe. Czy problem u Ciebie występuje cały czas codziennie, czy tylko w niektóre dni.

**Comment by lukada4100** [comment]
Dotyczy niektórych płatności w niektóre dni. Po prostu bywają dni, gdy kilka płatności z nocy nie wpada. W szczególności dotyczyło to 3-5 kwietnia. Chciałbym po prostu wiedzieć czy jest to możliwe, czy może jakiś problem po mojej stronie, a jeśli tak to ile takie opóźnienie może wynosić. Odpowiednio zwiększę zakres czasowy i po sprawie, a nie chcę ciągnąć z 2 dni wstecz bo to jednak trochę marnotrawstwo.

**Comment by PawelTaberski** [comment]
Oczywiście jest to możliwe zwłaszcza wieczorem, ze względu na jakieś prace konserwacyjne. Najlepszym rozwiązaniem, tak jak sam napisałeś będzie wydłużenie tego czasu o kilka godzin.
