### ISSUE TITLE
payment.finishedAt.gte & payment.finishedAt.lte

### ISSUE THREAD

**Issue by skrux1** [allegro/allegro-api#1482]
:bulb: **Sugestia**
Cześć, sugestia dotyczy **/order/checkout-forms**, czy moglibyście przemyśleć sprawę i dodać możliwość filtracji zamówień nie tylko po parametrze boughtAt, a właśnie po zakończonej płatności (**payment.finishedAt.gte** & **payment.finishedAt.lte**)- ułatwi to o tyle sprawę, że od złożenia zamówienia do dokonania płatności może minąć nawet pare dni, nie jesteśmy w stanie wyłapać takich zamówień, bo boughtAt pokazuje nam czas przeszły. Moglibyśmy ewentualnie zapisywać zamówienie którego status wisi i potem odpytywać co chwile api czy status się zmienił jednak to powoduje zbędny ruch, myślę że tak zaawansowane API powinno posiadać te parametry.

Pozdrawiam.

**Comment by PawelTaberski** [comment]
A czy w takim wypadku nie wystarczy Tobie filtracja zamówień po statusie? Jak ustawisz status READY_FOR_PROCESSING to jest równoznaczne z tym, że dane zamówienie zostało opłacone?

**Comment by skrux1** [comment]
> A czy w takim wypadku nie wystarczy Tobie filtracja zamówień po statusie? Jak ustawisz status READY_FOR_PROCESSING to jest równoznaczne z tym, że dane zamówienie zostało opłacone?

Oczywiście, filtrujemy również po statusie, ale co mi z samego statusu, skoro zamówienie może zostać opłacone po tygodniu? Logika aplikacji pobiera zamówienia z całego dnia. Idąc tym tokiem myślenia musiałbym pobierać zamówienia z całego miesiąca i sprawdzać czy w końcu zostało opłacone. Chyba nie muszę tłumaczyć jak loopowanie takiego zrzutu wpłynie na serwer?

**Comment by PawelTaberski** [comment]
Teraz rozumiem w jakim celu potrzebne Tobie sortowanie po tej dacie. Oczywiście, taką sugestię zgłosiłem, jeśli otrzymam informacje, że wdrożymy taką zmianę to poinformujemy o tym w dedykowanym komunikacie.

**Comment by bepropl** [comment]
Nie ukrywam że taka opcja przydałaby się bardzo - dziennie potrafi przepaść kilka transakcji.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski niedługo chcecie wyłączyć WEBAPI, a co tu dużo mówić RESTAPI ma sporo niedociągnięć, które uniemożliwiają sprawną integrację. Czy można liczyć na szybsze rozwiązywanie najważniejszych tematów? Moim zdaniem to kolejny temat pilny do rozwiązania, pobieranie w kółko danych spowoduje tylko problemy wydajnościowe.

**Comment by PawelTaberski** [comment]
Tak, jak pisałem sugestię zgłosiłem, dodatkowo właśnie dodałem, że zapotrzebowanie na takie rozwiązanie zgłasza większa ilość użytkowników.

**Comment by skrux1** [comment]
Coś wiadomo?

**Comment by MartaNowaczyk** [comment]
Jeśli pojawią się zmiany w tym zasobie na pewno poinformujemy o tym  w odpowiednim komunikacie.

**Comment by skrux1** [comment]
Odświeżam

**Comment by MartaNowaczyk** [comment]
@skrux1 mamy ten temat na uwadze i jest on analizowany. Nie ma jeszcze jednoznacznej decyzji w tej sprawie.

**Comment by neldh** [comment]
W aktualnej wersji dostępna filtracja dla statusu READY_FOR_PROCESSING nie ma najniejszego sensu (z powodu opisanego już wyżej). Chyba że chcecie żebyśmy za każdym razem jak mamy filtr na status READY FOR_PROCESSING przekopywali się przez wszystkie wyniki. Bez tego filtra ten zasób nie jest po prostu spójny z własną logiką.

**Comment by PawelTaberski** [comment]
@neldh Przekazałem Twoje spostrzeżenie do zespołu, który pracuje nad tym zasobem i dodałem, że większa liczba użytkowników oczekuje takiego filtru.

**Comment by neldh** [comment]
Czy wiadomo już czy filtr zostanie dodany?

**Comment by PawelTaberski** [comment]
Przekazałem sugestię, jeśli wdrożymy taką zmianę, to na pewno o tym poinformujemy.

**Comment by neldh** [comment]
Czy wiadomo coś nowego w tej kwestii?

**Comment by PawelTaberski** [comment]
Tak, jak pisałem sugestię przekazałem i jeśli otrzymam informację, że wdrażamy taką zmianę to oczywiście poinformujemy o tym w dedykowanym komunikacie.

**Comment by skrux1** [comment]
Refresh.
