### ISSUE TITLE
Przelew tradycyjny i pobieranie danych do wysyłki przez REST API

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1483]
Dzień dobry,

Allegro udostępnia dane do wysyłki w przypadku zamówień o statusie:
READY_FOR_PROCESSING - klient wypełnił FOD i sfinalizował płatność (status: zakończona), albo wybrał płatność za pobraniem lub odbiór osobisty.

W jaki sposób mamy obsługiwać zamówienia, w przypadku kiedy Klient wybiera płatność przelewem? Skąd mamy pobrać dane do wysyłki? Jakiś poradnik?

**Comment by MartaNowaczyk** [comment]
Jeżeli płatność zostanie zakończona, to taka płatność też też będzie mieć status READY_FOR_PROCESSING

**Comment by jakubmaguza** [comment]
W Managerze Paczek jest możliwość zmiany statusu zamówienia na 'opłacone'. Dlaczego ta zmiana nie jest potem widoczna na froncie i w REST API? Czy możecie to naprawić?

**Comment by MartaNowaczyk** [comment]
Jeżeli jest status READY_FOR_PROCESSING to dane się nie zmieniają, niezależnie od tego czy to dane paczkomatu czy adres. W innym statusie nie dostaniesz adresu, tak jak pisał Paweł w podlinkowanym wątku. Wszystkie płatności powinny przechodzić przez allegro i to właśnie w ten sposób powinieneś uzyskać odpowiedni status zamówienia, by je zrealizować.

**Comment by SebastianOzdoba** [comment]
To jest błąd.
Przykład: klient kupuje, wybiera odbiór osobisty i płatność przy odbiorze. 
Zatem nie będzie płatności przez Allegro, takie zamówienie powinno mieć ready_for_ processing

**Comment by jakubmaguza** [comment]
@MartaNowaczyk 
Rozumiem wasze stanowisko, ale nie jest ono ani logiczne, ani spójne.
Nie jest logiczne, bo tak jak pisałem -> jeśli klient wybrał płatność zwykłym przelewem (przez PayU), wysłał mi potwierdzenie, to i tak muszę czekać aż ten przelew do was dojdzie i go przetworzycie. Zdarza się, że to duże zamówienie i chciałbym móc zacząć je przygotowywać.

Nie jest spójne, bo w przeglądarce widać dane adresowe. W REST widać też dane paczkomatu.

Jeśli dalej jesteście nastawieni na głos dewelopera, to bardzo proszę o dodanie adresu przy tym statusie. W moim przypadku, w 100% ten adres już się nie zmienia, myślę że inni mają podobnie. Oczywiście można w dokumentacji oznaczyć, że ten adres może się zmienić.

PS. Nigdy nie miałem okazji podziękować za dodanie pola external przy pobieraniu zamówień. Dziękuję serdecznie, jest to nieopisana pomoc.

**Comment by MartaNowaczyk** [comment]
@SebastianOzdoba płatności przy odbiorze czy odbiór osobisty to inna kwestia. One z góry są odpowiednio oznaczone jako READY_FOR_PROCESSING.

@jakubmaguza rozumiem, jednak nie planujemy wprowadzać zmian w tym zakresie tzn. nie przewidujemy zwracania danych do wysyłki w innych statusach.

**Comment by Draken79** [comment]
Sytuacja z życia:

klient wypełnił FOD, ale płatność nie przeszła. Kontaktujemy się z klientem i okazuje się, że zapomniał, że nie ma środków na koncie i prosi o wysyłkę za pobraniem. Pytamy na jaki adres wysłać - klient mówi, że na ten co wypełnił w formularzu dostawy. Skąd zatem pobrać ten adres? 

to wcale nie jest jakas nietypowa i rzadka sytuacja, nam się zdarza kilka razy w miesiącu. Często też po nieudanej płatności klienci proszą o numer konta do przelewu - w takiej sytuacji również nie mam danych do wysyłki.

Rozumiem, że nie mieliście w planach podawać adresu dla FILLED_IN, ale może warto zmienić zdanie wobec argumentów, które tu przytaczamy. A jeśli nie to wypadałoby chociaż podać jakie są powody dla których tego nie robicie, a nie tylko 'nie, bo nie'.

**Comment by Draken79** [comment]
Mamy też sporo stałych klientów, którym ufamy, a płacą przelewem tradycyjnym. W takich sytuacjach chcielibyśmy wyslać przesyłkę niezwłocznie po zakupie, ale w tym przypadku również nie możemy, bo nie mamy danych do wysyłki.

**Comment by MartaNowaczyk** [comment]
@Draken79 właściwym torem jest anulowanie niedokończonej płatności przez klienta i wybranie odpowiednich opcji dostawy przez formularz. Wtedy adres i dane są poprawne i gotowe do pobrania. 
Nie chcemy podawać adresu wcześniej ze względu na to, że dane mogą się zmienić.
---------------------------
Wszelkie wasze sugestie i zgłoszenia są zbierane, dlatego nie zamykam tematu i nie mówię nigdy, choć na ten moment w planach tego nie mamy. Dla nas ważne są wasze argumenty i dobrze, że mówicie o przypadkach jakie napotykacie w tej kwestii. To daje zawsze inny punkt widzenia. Nie mogę jednak na ten moment obiecać, że coś się zmieni.

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk 
Postaw się proszę w sytuacji developera.
Jest taka transakcja, loguję się na swoje konto sprzedawcy i widzę dane. Dane nie da się pobrać w restAPI, więc co robi sprzedawca, dzwoni do developera i mówi że w Allegro jest więc to błąd w aplikacji developera. Co może developer, nic :)
Powinnio być zatem to także ukryte po stronie konta sprzedawcy by tych danych nie widział :)

@Draken79

**Comment by jakubmaguza** [comment]
@MartaNowaczyk 
Właściwym torem byłoby anulowanie niedokończonej transakcji ale..
Niektórzy ludzie nie potrafią nawet wrzucić przedmiotów do koszyka i klikają przy każdym przedmiocie 'Kup Teraz'.  W idealnym świecie ta opcja nie byłaby potrzebna. Problem jest taki, że kupujący nie zachowują się idealnie. Jeśli jedynym argumentem jest to, że ten adres może się zmienić, to ja ten argument podważyłem już wyżej.
Developerzy wiedzą że adres może się zmienić, więc używają go na własne ryzyko.

**Comment by PawelTaberski** [comment]
Planujemy wprowadzić zmianę dzięki, której nie będzie można dokonać zakupu bez uzupełnienia formularza dostawy. Sugestię o dodaniu adresu w innych statusach przekazałem, jeśli zdecydujemy się wdrożyć taką zmianę o poinformujemy o tym w dedykowanym komunikacie.

**Comment by jakubmaguza** [comment]
Tylko że taka zmiana ma się nijak do tego o czym tu rozmawiamy. Jeśli ktoś zrobi zakup bez wypełnienia formularza, to otrzymuje status BOUGHT. Jeśli nie poda adresu, to logiczne że go nie pokażecie.
Cały ten wątek mówi o statusie FILLED_IN, czyli **po wypełnieniu** formularza dostawy.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski należy zatem UKRYĆ wyświetlanie danych w panelu sprzedawcy albo dać w restAPI
Nie może być że na interfejsie widać, a w restAPI nie ma. Czy mamy odsyłać naszych Klientów do Was, przecież znając Klientów będziemy mieli takie zgłoszenia jako błąd do poprawy

**Comment by PawelTaberski** [comment]
Rozumiem jak najbardziej chcemy ten proces ujednolicić. Przekazałem wasze spostrzeżenia do zespołu, który odpowiada za te zasoby.

**Comment by copyact** [comment]
Czy po tym czasie coś się wyklarowało w tej sprawie? Własnie zmieniam stare API na REST i w starym działało to tak jak opisuje @jakubmaguza 

Jak przez API przetworzyć zamówienie, gdy płatność automatyczna nie powiodła się i klient zrobił tradycyjny przelew?
