### ISSUE TITLE
webAPI nie pobiera fodów i wpłat

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#1484]
od około godz 14 nie pobiera fodów i wpłat

**Comment by PawelTaberski** [comment]
Sprawdziłem i fod-y spływają tak samo pojawił się poprawnie event, czy dostajesz jakiś błąd, jak zauważyłeś problem, czym się objawia?

**Comment by Lebioda** [comment]
Nie działały aplikacje korzystające z API (m.in. Easyuploader, dpd, inpost) oraz moje skrypty. FODy i wpłaty zostały już pobrane.

**Comment by PawelTaberski** [comment]
Czyli już wszystko wróciło do normy tak?

**Comment by Lebioda** [comment]
Tak, pobiera już na bieżąco.
