### ISSUE TITLE
Brak adresu dla FILLED_IN

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1485]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

(Tak wiem, podobne pytanie już się pojawiło, chcę dodać coś)
Hej!
Przy pobieraniu zamówień ze statusem "FilledIn" nie zwracacie adresu dostawy.
Brakuje pola "address" (jak na załączonym zrzucie ekranu). Jeśli jest wybrany paczkomat, to wszystko działa jak należy. Problem jest w momencie wyboru dostawy w której trzeba podać adres. Filled_In oznacza że kupujący wypełnił formularz, więc dlaczego nie chcecie podać danych adresowych, a z wybranym paczkomatem nie ma problemu?
![image](https://user-images.githubusercontent.com/24191650/55794000-7b494500-5ac4-11e9-9c39-0b453ffd8707.png)

EDIT: Oczywiście dane dostawy są dostępne w przeglądarce...

**Comment by PawelTaberski** [comment]
Dopiero w zamówieniu o statusie READY_FOR_PROCESSING zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni. 
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by jakubmaguza** [comment]
Tak, czytałem poradnik i wiem o tym. Moje pytanie w ogóle tego nie dotyczyło.
W sytuacji gdy np. Klient złoży zamówienie, zrobi przelew tradycyjny, wyśle potwierdzenie przelewu - chciałbym móc przygotować zamówienie. Przez brak danych o adresie dostawy jest to uciążliwe. 
1. Skoro podajecie te dane w przeglądarce, to dlaczego pomijacie je w REST?
2. Jeśli tak się martwicie o sprzedających, że pomylą adresy dostaw, to dlaczego w przypadku pokazujecie dane paczkomatu? Czym one się różnią od adresu dostawy?

**Comment by PawelTaberski** [comment]
Obecnie tak, jak pisałem nie przewidujemy zwracania danych do wysyłki w innych statusach.
