### ISSUE TITLE
[Rest] Problem z usuwaniem oferty

### ISSUE THREAD

**Issue by damianSzechlicki** [allegro/allegro-api#1486]
Czy występuje obecnie jakiś problem z usuwaniem oferty?
Wywołuje według dokumentacji metodę DELETE na https://api.allegro.pl/sale/offers/123123123.

W odpowiedzi dostaję: Serwer zdalny zwrócił błąd: (400) Złe żądanie.
Z innymi zasobami nie mam problemu, tylko z tym :/

**Comment by PawelTaberski** [comment]
Ten zasób służy do usuwania draftu oferty, czy na pewno próbujesz usunąć draft a nie aktywną ofertę?

**Comment by damianSzechlicki** [comment]
Oferta była aktywna ale przed wywołaniem DELETE zakończyłem ją.
Jeżeli ta metoda odnosi się tylko do draftu to jest jakaś inna możliwość usunięcia zakończonej oferty?

**Comment by PawelTaberski** [comment]
Ta metoda służy tylko do usuwania draftow, czyli ofert o statusie INACTIVE. Jak zakończysz ofertę to obecnie ona jest zawieszona i do czasu, aż nie zostanie przeniesiona do archiwum możesz ją aktywować pod tym samym id. Jeśli wstrzymasz ofertę np na 5 dni to nie tracisz całej popularności, która jest liczona z ostatnich 30 dni.

**Comment by damianSzechlicki** [comment]
W takim razie dla potwierdzenia, limit 100 000 ofert tyczy się tylko tych aktywnych tak?

**Comment by PawelTaberski** [comment]
Tak, jest to limit aktywnych ofert na koncie, limit dotyczy też ofert, w których ustawiłeś datę wystawienia w przyszłości.

**Comment by damianSzechlicki** [comment]
Ok, dziękuje za odpowiedzi. Temat do zamknięcia.
