### ISSUE TITLE
GetPostBuyFormsDataForSellersResponse - zwraca niepełne dane #969

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1487]
4 miesiączki minęły. Wątek automatycznie się zamknął, a problemu nie udało się rozwiązać...

**Comment by PawelTaberski** [comment]
Dostałem informacje, że problem nie powinien już występować. Jeśli problem nadal u Ciebie się pojawia podeślij koniecznie pełne requesty w raz z odpowiedziami i login usera na jaki masz identyfikator sesji przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Dodatkowo dodaj, że dane potrzebne są do ticketa numer 1487 na GitHub-ie. Sprawdzimy to.

**Comment by lukada4100** [comment]
Wysłałem Ci w formularzu request/response dla zapytania zbiorczego i dla pojedynczego. W zbiorczym w postBuyFormGdAddress brakuje wartości postBuyFormAdrId. Fakt, w postBuyFormAdrFullName jest wartość: "Paczkomat BLABLA", czego zdaje się wcześniej nie było, więc teoretycznie żeby dostać id punktu odbioru mógłbym sobie wykroić stringa, tyle że zdaje się nie o to chodzi.

**Comment by PawelTaberski** [comment]
Dzięki, jak tylko otrzymam informacje zapoznam się z nimi i przekażę do zespołu, który odpowiada za tą metodę.

**Comment by bozydarlelutko** [comment]
U mnie występuje ten sam problem - często w postBuyFormGdAddress brakuje pola postBuyFormAdrId. Jest to szczególnie problematyczne w przypadku Poczty Polskiej - nie mam wtedy identyfikatora punktu odbioru przez co nie mogę później nadać paczki przez API Poczty Polskiej.

**Comment by MartaNowaczyk** [comment]
@bozydarlelutko  podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1487. Sprawdzimy opisaną sytuację.

**Comment by lukada4100** [comment]
Jako autor wątku poczuwam się do przypomnienia, że sprawa w nim poruszona wcale nie została rozwiązana. Miesiąc temu, gdy próbowałem odświeżyć temat, zostałem poproszony o ponowne dosłanie zapytania/odpowiedzi co od razu zrobiłem. Minął kolejny miesiąc bez żadnego odzewu, a wątek znów zamknął się automatycznie.

**Comment by MartaNowaczyk** [comment]
@lukada4100 sprawdziłam i masz rację, coś tu poszło w tej komunikacji nie tak i przez to mam błędne informacje. Przez to potrzebuję świeżego przykładu, który będzie widoczny w naszych logach. Jeśli masz takie, to podeślij proszę, bez przykładu nic nie zrobimy, bo to pojedyncze przypadki.

**Comment by lukada4100** [comment]
@MartaNowaczyk 
Wysłałem jeszcze raz. Potwierdź proszę, że doszlo.
I przypomnienie: w odpowiedzi na zapytanie z wiekszą ilością id, brak jest postBuyFormAdrId

**Comment by MartaNowaczyk** [comment]
Dotarły do mnie pliki. Sprawdzimy.
