### ISSUE TITLE
rejestracja api

### ISSUE THREAD

**Issue by GosiaBEPPE** [allegro/allegro-api#1488]

**Comment by GosiaBEPPE** [comment]
Dzień Dobry, chciałabym się zarejestrować w restapi. Ale nie wiem jaka ma być nazwa aplikacji, jaki adres uri. niestety jestem jestem biegła w tym temacie i bardzo proszę o pomoc krok po kroku. Moje drugie pytanie, mamy dwa konta na allegro, które będą miały pobierane oferty z dedykowanych stron (każda oddzielna do oddzielnego konta w Allegro). Całość będziemy obsługiwać przez IAI Shop.
Pozdrawiam 
Gosia BEPPE

**Comment by PawelTaberski** [comment]
Nie wiemy w jaki dokładnie sposób IAI korzysta z naszego API (tzn. jak wygląda kod samej aplikacji), jednakże powinni oni korzystać z jednego klucza do którego podpinają nowych userów. W takim wypadki przede wszystkim powinnaś skontaktować się z IAI i dopytać ich co jest niezbędne, aby przeprowadzili Ciebie przez proces weryfikacji i autoryzacji, aby aplikacja mogła w Twoim imieniu dokonywać zmian na koncie.
