### ISSUE TITLE
sugestie kategorii na podstawie nazwy produktu

### ISSUE THREAD

**Issue by kamilhark** [allegro/allegro-api#1489]
:bulb: **Sugestia**

Przy ręcznym wystawianiu oferty, po podaniu nazwy produktu wyświetlają się sugestie kategorii, czy jest szansa na udostępnienie tego w formie api?

**Comment by PawelTaberski** [comment]
Nie planujemy zwracania parametrów uzupełnionych jakimiś defaultowymi danymi. Wszelkie informacje o parametrach znajdziesz w dedykowanym zasobie GET /sale/categories/{catId}/parameters.

**Comment by Maczuga** [comment]
@PawelTaberski nie bardzo rozumiem co Twoja odpowiedź ma wspólnego z pytaniem. Kolega chyba pyta o jakąś metodę API, która będzie zwracała sugerowane kategorie pasujące do nazwy oferty jak tu:

![image](https://user-images.githubusercontent.com/544349/55950916-4bca4200-5c56-11e9-8b73-b2ea88503736.png)

@kamilhark Istnieje takie coś: https://allegro.pl/suggestions/?country=pl&sortByElementType=true&phrase=telefon%20samsung%20s10
Nie wiem na ile Ci to się przyda.

Jest jeszcze takie coś:
curl -X GET \
  https://allegro.pl/offer-api/categoriesSuggestions/Telefon%20Samsung%20S10 \
  -H 'Cookie: QXLSESSID=XXXXXXXXXXXXXXXXXXX;' \
  -H 'Referer: https://allegro.pl/offer/'

Problemem jednak jest posiadanie QXLSESSID, a szkoda, bo zwraca wszystko co potrzeba:

`{
    "matching_categories": [
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled"
                ],
                "ca_id": "165",
                "ca_name": "Smartfony i telefony komórkowe"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled",
                    "shippingFromFilterEnabled"
                ],
                "ca_id": "435",
                "ca_name": "Samsung"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled",
                    "shippingFromFilterEnabled"
                ],
                "ca_id": "260666",
                "ca_name": "Galaxy S10"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "348",
                "ca_name": "Akcesoria GSM"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "353",
                "ca_name": "Etui i pokrowce"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "348",
                "ca_name": "Akcesoria GSM"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "95595",
                "ca_name": "Uchwyty"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "348",
                "ca_name": "Akcesoria GSM"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "19354",
                "ca_name": "Ładowarki"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "147162",
                "ca_name": "Bezprzewodowe"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled"
                ],
                "ca_id": "165",
                "ca_name": "Smartfony i telefony komórkowe"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled",
                    "shippingFromFilterEnabled"
                ],
                "ca_id": "435",
                "ca_name": "Samsung"
            },
            {
                "ca_options": [
                    "productListingEnabled",
                    "variantsByImages",
                    "productNavigationEnabled",
                    "shippingFromFilterEnabled"
                ],
                "ca_id": "260667",
                "ca_name": "Galaxy S10+"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "348",
                "ca_name": "Akcesoria GSM"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "10532",
                "ca_name": "Folie i szkła ochronne"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "3919",
                "ca_name": "Sport i turystyka"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "147262",
                "ca_name": "Bieganie"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "260747",
                "ca_name": "Słuchawki"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "ca_name": "Elektronika"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "4",
                "ca_name": "Telefony i Akcesoria"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "348",
                "ca_name": "Akcesoria GSM"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "8539",
                "ca_name": "Atrapy i telefony demonstracyjne"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "3919",
                "ca_name": "Sport i turystyka"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "147262",
                "ca_name": "Bieganie"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "260742",
                "ca_name": "Etui, opaski na ramię"
            }
        ],
        [
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "3",
                "ca_name": "Motoryzacja"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "253498",
                "ca_name": "Akcesoria samochodowe"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "253613",
                "ca_name": "Uchwyty, wieszaki"
            },
            {
                "ca_options": [
                    "variantsByImages"
                ],
                "ca_id": "253617",
                "ca_name": "Do telefonów"
            }
        ]
    ]
}`

**Comment by kamilhark** [comment]
@Maczuga super, wielkie dzięki

**Comment by PawelTaberski** [comment]
@Maczuga Sądziłem, że chodzi o zwrot oferty ze wszystkim polami uzupełnionymi już danymi. Te zasobu, które podałeś nie są przez nas wspierane publicznie. Wszelkie wystawione publicznie zasoby znajdziesz [tutaj](https://developer.allegro.pl/documentation/).
@kamilhark Czy chodziło Tobie o taki zasób jak podał @Maczuga Jeśli tak oczywiście przekażę sugestię, aby wystawić publicznie taki zasób.

**Comment by kamilhark** [comment]
tak, chodziło mi dokładnie o taki zasób jak podał @Maczuga.

**Comment by PawelTaberski** [comment]
Rozumiem przekażę sugestię, aby wystawić taki zasób publicznie.

**Comment by kamilhark** [comment]
wracająć do tego linka, https://allegro.pl/suggestions/?country=pl&sortByElementType=true&phrase=telefon%20samsung%20s10 

czym jest ten zasób, nie wygląda jak część Rest Api, czy mogę go używać w swojej aplikacji?

**Comment by PawelTaberski** [comment]
@kamilhark  Nie jest to zasób udostępniony publicznie, wszystkie zasoby jakie udostępniliśmy publicznie i wspieramy znajdziesz w [naszej dokumentacji](https://developer.allegro.pl/documentation/). Nie gwarantujemy stabilności i kompatybilności innych metod.
