### ISSUE TITLE
doLogin - Niepoprawna wersja kategori lub pol sprzedazy.

### ISSUE THREAD

**Issue by delvier** [allegro/allegro-api#149]
Metoda  logujaca z api **doLogin**, poprostu odmawia mi posluszenstwa (tydzien temu wszystko gralo) rzucajac takim bledem:

Reply:
![image](https://user-images.githubusercontent.com/1397476/38866518-6ad11f5a-4241-11e8-9ed7-b72699640da4.png)

Request:
![image](https://user-images.githubusercontent.com/1397476/38866755-37434752-4242-11e8-82c5-362e6665851f.png)

Co robie niepoprawnie ?

**Comment by AniaMalinowska** [comment]
[Problemem](https://allegro.pl/webapi/faq.php?cod=OGZkZlVlNmJk#faq_2) jest to, że w parametrze wywołania metody podany został niepoprawny (nieaktualny) klucz wersji. [Klucze wersji są zmiennie](https://allegro.pl/webapi/general.php?cod=OGZkZlVlNmJk#version_keys) - dlatego należy sprawdzić, czy wartość klucza jaką przekazujesz zgadza się z jego aktualną wartością. 
Aby sprawdzić wartość kluczy wersji możesz użyć metod: [doQuery(All)SysStatus](https://allegro.pl/webapi/documentation.php/theme/id,61?cod=OGZkZlVlNmJk).
