### ISSUE TITLE
Pobieranie cen dostawy dla oferty

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#1490]
W związku z potrzebą migracji ofert ze starego systemu opartego na WebAPI na nowy, korzystający z RESTa, pojawia się również konieczność przeniesienia cen/cenników transportu.

Oferty, które zostały wystawione poprzez WebAPI i nie mają przypisanego cennika dostawy, zasób "/sale/offers" (jak i żaden inny weryfikowany) nie zwraca kosztów dostawy, a jedynie w tym wypadku puste pole z cennikiem. 

Proszę o informację, w jaki sposób, poprzez REST API, mogę pobrać informację o cenach transportu dla ofert nie posiadających przypisanego cennika. Za pomocą tych cen chcemy utworzyć i i przypisać nowy cennik dostawy (ew. skorzystać z istniejącego, mającego identyczne ceny).

W nowym rozwiązaniu chcemy całkowicie uniezależnić się od WebAPI stąd odpytywanie przez nie o konkretne FIDy odpada.

**Comment by PawelTaberski** [comment]
Przez REST API nie ma możliwości pobrania przypisanych do oferty przez WebAPI pojedynczych metod dostawy. REST API zwraca tylko cenniki.

**Comment by lkowol** [comment]
> Przez REST API nie ma możliwości pobrania przypisanych do oferty przez WebAPI pojedynczych metod dostawy. REST API zwraca tylko cenniki.

Nie sądzi Pan w takim razie, że w celu zachowania kompatybilności wstecznej i umożliwienia pełnego zarządzania ofertami poprzez REST API, powinno zostać wdrożone jedno z dwóch rozwiązań?:
- automatyczne przypisywanie istniejącego odpowiadającego cennika dostawy do ofert, gdzie tego cennika nie ma, na podstawie "pojedynczych metod" lub generowanie takiego cennika i przypisywanie, jeśli nie istnieje,
- możliwość pobrania "pojedynczych metod" poprzez REST API, co umożliwi wykonanie ww. procesu manualnie?

**Comment by PawelTaberski** [comment]
Tak, jak pisałem obecnie nie ma takiej możliwości i z tego co wiem nie przewidujemy wdrażania mechanizmu do zwracania przypisanych przez WebAPI metod dostawy. Jednakże zgłosiłem jako sugestię Twoje pomysły, do poradzenia sobie z tym problemem. Jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym.

**Comment by lkowol** [comment]
Dlaczego brak odpowiedzi powoduje zamknięcie zagadnienia? To, że nikt nie poruszył tematu przez miesiąc, czyni go bezwartościowym?

**Comment by MartaNowaczyk** [comment]
@lkowol wszystkie czynności z tym zagadnieniem zostały wykonane. Zgłosiliśmy opisana sugestię do odpowiedniego zespołu i tam będzie brana pod uwagę jeśli będziemy robić jakieś zmiany w tym obszarze. Jeśli wdrożymy taką opcję na pewno poinformujemy o tym w oddzielnym komunikacie. Zamykamy wątki automatycznie dla porządku, jednak zawsze można je wyszukać niezależnie od statusu.

**Comment by makerlabs** [comment]
@MartaNowaczyk wydaje mi się, że problem jest nieco szerszy w przypadku, gdy aktualnie utworzymy aukcję po stronie allegro i wybierzemy opcję dla cennika dostaw "wypełnij sposoby dostaw ręcznie." to po pobraniu takiej aukcji otrzymujemy wartość null dla delivery -> shippingRates, poniżej wklejam response dla aukcji utworzonej z poziomu serwisu allegro:
```
stdClass::__set_state(array(
   'id' => '6206367261',
   'name' => 'Rower',
   'category' => 
  stdClass::__set_state(array(
     'id' => '86414',
  )),
   'product' => NULL,
   'parameters' => 
  array (
    11323 => 
    stdClass::__set_state(array(
       'id' => '11323',
       'valuesIds' => 
      array (
        0 => '11323_1',
      ),
       'values' => 
      array (
      ),
       'rangeValue' => NULL,
    )),
    213254 => 
    stdClass::__set_state(array(
       'id' => '213254',
       'valuesIds' => 
      array (
      ),
       'values' => 
      array (
      ),
       'rangeValue' => 
      stdClass::__set_state(array(
         'from' => '20',
         'to' => '30',
      )),
    )),
  ),
   'ean' => NULL,
   'description' => 
  stdClass::__set_state(array(
     'sections' => 
    array (
      0 => 
      stdClass::__set_state(array(
         'items' => 
        array (
          0 => 
          stdClass::__set_state(array(
             'type' => 'TEXT',
             'content' => '
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque pretium nisl id quam vehicula, ac feugiat tellus rhoncus. Cras porta dictum dui ac porttitor. Duis sodales arcu sit amet vestibulum placerat. Donec lectus mi, placerat eget orci porta, feugiat rhoncus magna. Vivamus pulvinar enim vel ornare dictum. Ut varius a dui a euismod. Quisque placerat hendrerit quam, a suscipit lorem ornare eu. Aliquam erat volutpat. Vestibulum venenatis odio erat, nec ultricies velit iaculis cursus. In vitae massa pellentesque, eleifend mauris ut, lobortis tortor. Proin elementum, elit id iaculis placerat, ex magna luctus quam, eu vulputate urna lacus a odio. Praesent auctor orci sed quam pellentesque facilisis. Nullam ante risus, interdum eu mauris sit amet, elementum tempor quam.

',
          )),
        ),
      )),
    ),
  )),
   'compatibilityList' => NULL,
   'images' => 
  array (
    0 => 
    stdClass::__set_state(array(
       'url' => 'https://a.allegroimg.allegrosandbox.pl/original/03b0aa/6d312e81468fb7e571d9d888b89d',
    )),
  ),
   'sellingMode' => 
  stdClass::__set_state(array(
     'format' => 'BUY_NOW',
     'price' => 
    stdClass::__set_state(array(
       'amount' => '20',
       'currency' => 'PLN',
    )),
     'startingPrice' => NULL,
     'minimalPrice' => NULL,
  )),
   'stock' => 
  stdClass::__set_state(array(
     'available' => 15,
     'unit' => 'SET',
  )),
   'publication' => 
  stdClass::__set_state(array(
     'duration' => 'PT720H',
     'status' => 'ACTIVE',
     'startingAt' => NULL,
     'endingAt' => '2019-06-23T08:54:34Z',
     'endedBy' => NULL,
  )),
   'delivery' => 
  stdClass::__set_state(array(
     'shippingRates' => NULL,
     'handlingTime' => 'PT48H',
     'additionalInfo' => NULL,
     'shipmentDate' => NULL,
  )),
   'payments' => 
  stdClass::__set_state(array(
     'invoice' => 'NO_INVOICE',
  )),
   'afterSalesServices' => NULL,
   'additionalServices' => NULL,
   'sizeTable' => NULL,
   'promotion' => NULL,
   'location' => 
  stdClass::__set_state(array(
     'countryCode' => 'PL',
     'province' => 'WIELKOPOLSKIE',
     'city' => 'Poznań',
     'postCode' => '61-450',
  )),
   'external' => NULL,
   'attachments' => 
  array (
  ),
   'contact' => NULL,
   'validation' => 
  stdClass::__set_state(array(
     'errors' => 
    array (
    ),
     'validatedAt' => '2019-05-26T17:29:43.05Z',
  )),
   'createdAt' => '2019-05-24T08:27:33Z',
   'updatedAt' => '2019-05-26T17:29:43.6Z',
))
```

**Comment by PawelTaberski** [comment]
@makerlabs Jeśli dobrze Ciebie rozumiem to jak edytujesz ofertę i wybierasz ręczne wybranie sposobów wysyłki, to odpinasz od takiej oferty cennik dostawy i przypisujesz tylko jakieś wybrane metody dostawy. Dlatego w polu delivery otrzymujesz null. Dokładnie tak samo jak w przypadku wystawienia oferty po WebAPI (tam nie ma cenników) jak wybierzesz dane metody dostawy to po pobraniu takiej oferty przez REST API w polu delivery również otrzymasz null, bo w tym polu zwracamy tylko id cennika dostawy.

**Comment by makerlabs** [comment]
@PawelTaberski no tak ale gdzie tutaj logika. Jeżeli umożliwiacie podawanie własnego cennika po stronie allegro dla danej aukcji tak samo powinno być to udostępnione od strony API. Inaczej przy integracji z istniejącym API dochodzi do sytuacji, że sprzedawca edytując daną aukcję nie będzie, ani widział utworzonego przez siebie cennika dostaw ani miał możliwości zmian cennika. W tym momencie mam wyświetlić komunikat klientowi, że ze względu na ograniczenia w REST API nie ma możliwości edycji cennika dostaw?

**Comment by neldh** [comment]
@makerlabs. Oni chyba chcą wyrzucić w przyszłości to "ręczne" dodawanie cen (bez cenników) i dlatego nie ma tego w rest api. Ja bym na twoim miejscu informował użytkownika, że aby w aplikacji było widać ceny dostaw, to powinien wybrać gotowy cennik przy edycji/tworzeniu aukcji na stronie. Niemniej wydaje mi się, że limit na cenniki rzędu 250 jest mocno za niski. No chyba, że ambicją Allegro jest uwalenie dużych sprzedawców...

**Comment by PawelTaberski** [comment]
@makerlabs Tak jak pisałem jeśli do oferty dodajesz ręcznie bądź przez WebAPI kilka wybranych metod wysyłki to to nie jest równoznaczne z utworzeniem cennika dostawy. Więcej na temat cenników dostawy znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#shipping-rates).
@neldh Jeśli limit jest Twoim zdaniem zbyt niski daj proszę znać w jakim przypadku (w przypadku jakiego asortymentu) i dlaczego 250 cenników to zbyt mało i oczywiście przekażę Twoją sugestię. Dodatkowo daj proszę znać ile Twoim zdaniem powinno ich być.

**Comment by neldh** [comment]
@PawelTaberski 
Limit jest zbyt niski w przypadku, kiedy sprzedawca sprzedaje więcej niż 250 przedmiotów, każdy w innych cenach dostawy. Owszem. Dla małych sprzedawców jest na pewno wystarczający, ale jak ktoś ma 10000 ofert to już niekoniecznie. Ciężko określić ile powinno być. Ja mogę napisać, że w moim wypadku 500 by było ok, ale wydaje mi się, że nietrudno będzie znaleźć sprzedawce, dla którego ok to np dopiero 1000.

**Comment by PawelTaberski** [comment]
@neldh Rozumiem, sugestię oczywiście przekazałem, jeśli zdecydujemy się wdrożyć takie rozwiązanie, to poinformujemy o tym w dedykowanym komunikacie.
