### ISSUE TITLE
Zmiana w cenniku dostaw

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#1491]
Po dokonaniu zmian w cenniku dostaw podpitym do aukcji, na stronie aukcji nadal widoczne są stare ceny dostaw. Co trzeba coś zrobić aby w istniejących aukcjach odświeżyły sie ceny dostaw?

**Comment by PawelTaberski** [comment]
Zmiany na ofertach mogą zająć do godziny czasu, ponadto czy jesteś pewny, że do danej oferty jest przypisany właśnie ten cennik który zmieniłeś? Ponadto jeśli dokonałeś jakiejś zmiany w ofercie przez WebAPI cennik mógł się odpiąć.

**Comment by SlawomirMizerski** [comment]
Cennik zmieniany był kilka dni temu a przy każdej modyfikacji oferty wysyłany jest kompletny draft wraz z cennikiem.

**Comment by PawelTaberski** [comment]
Wystarczy, że zmienisz dane w cenniku, nie musisz nic więcej robić w ofercie, dane powinny się zaktualizować automatycznie w ofertach, które mają przypisany dany cennik. Nie bardzo rozumiem co masz na myśli przez draft? Oferta powinna być aktywna, aby dane na ofercie się zaktualizowały i były widoczne dla kupujących.
