### ISSUE TITLE
Kategorie - parametry typy "dictionary"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1492]
Czy parametr  przypisany do kilku kategorii może mieć różne zestawy wartości w zależności od kategorii, czy zestaw wartości jest niezmienny i przypisany do parametru?

**Comment by PawelTaberski** [comment]
Jak najbardziej wszystko zależy od charakterystyki danej grupy produktów. Mogą mieć one różne zestawy wartości dla danej cechy.

**Comment by kfijalko** [comment]
Dopytam:
Konkretny parametr id=127511 nazwa="Producent części" może mieć różny zestaw wartości w zależności od tego do której kategorii jest przypisany?

**Comment by PawelTaberski** [comment]
Może przedstawię na podstawie parametru Stan np w kategorii z Elektroniki 8875 będzie miał 5 wartości i wyglądał tak:
```
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy"
                },
                {
                    "id": "11323_2",
                    "value": "Używany"
                },
                {
                    "id": "11323_238066",
                    "value": "Po zwrocie"
                },
                {
                    "id": "11323_238058",
                    "value": "Powystawowy"
                },
                {
                    "id": "11323_238062",
                    "value": "Uszkodzony"
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```
a w kategorii Supermarket 90034, tylko 2 wartości i wyglądał tak:
```
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy"
                },
                {
                    "id": "11323_2",
                    "value": "Używany"
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```

**Comment by kfijalko** [comment]
Bardzo dobry przykład. Dziękuję i pozdrawiam.

**Comment by j4r3kb** [comment]
Czy parametry innego typu, czyli np. integer, float ale o tym samym ID mogą mieć inne restrykcje np. min, max dla różnych kategorii?

**Comment by MartaNowaczyk** [comment]
@j4r3kb dla tego samego ID powinny być te same założenia niezależnie od kategorii

**Comment by j4r3kb** [comment]
Kolejne pytanie:
czy parametry int, float typu zakresowego (range), mogą przyjmować wiele wartości na raz?
Np. mam zakres 1-10, czy mogę wysłać 2, 5, 8?

Patrząc na https://developer.allegro.pl/sale/#step-2 i przykład
"dla parametrów w których samodzielnie uzupełniasz ich wartość"
```
{
    "id": "216325",
    "valuesIds": [],
    "values": [
        "zielony",
        "żółty",
        "czerwony"
    ],
    "rangeValue": null
}
```

sprawdziłem ten parametr, są to "Cechy dodatkowe", typ string oraz maximum number of values = 10.
min 1 max 40 - są to restrykcje długości pojedynczej wysłanej wartości czy wszystkich razem?
Czy tylko pola typu string mogą się tak zachowywać?

**Comment by j4r3kb** [comment]
"/sale/offers?limit=1000&offset=0&sort=&name=&sellingMode.format=&sellingMode.price.amount.gte=100000&sellingMode.price.amount.lte="

powoduje błąd 400
`400 Error when searching seller offer (sellerId: 43962322, searchCriteria: {"sellingMode.price.amount.gte":"100000","sellingMode.format":""}).`

w dodatku nie jest zwracana ta odpowiedź jako json

**Comment by MartaNowaczyk** [comment]
zakresowe przyjmują tylko zakres, nie wiele wartości.

długość powinna dotyczyć pojedynczej wartości.
