### ISSUE TITLE
Detailed report - brak opisów dla kodów tasków

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#1493]
Zauważyłem, że niektóre zadania zmian cen dla ofert zwracają mi taki kod: **PRICE_UPDATES_COUNT_EXPIRED**. Status był oczywiście FAIL, ale co ten błąd oznacza?

Nie ma nigdzie opisów dla zwracanych przez szczegółowe raporty tasków kodów błędów. Wpisanie w Google nie zwraca zupełnie nic. 

ID tasków: 

- 8d45453a-b6ef-425b-924c-b4021130b27d
- ac97d90e-d63f-43ab-8b9b-82459a4f2077

Robiona była zmiana ceny z 364,46 na 295,20.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i traceid. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1493 na GitHub-ie.

**Comment by Maczuga** [comment]
@PawelTaberski poszło.

Zgłoszenie nr. 05151664.

**Comment by Maczuga** [comment]
Co z moją odpowiedzią? Dostałem w piątek rano informację, że takowa ma się pojawić tutaj. W tym czasie zaczęło mi wysypywać jeszcze więcej błędów.

PRICE_UPDATES_COUNT_EXPIRED:
- 7a99fbea-b956-4a7b-9ed4-074ea3e02f6b
- 5d92b72c-c0e2-422d-9d2f-67687a71bdc6
- 0f6ff05e-7328-4988-8b00-dd2c7d447a8c
- 44ecb746-b264-4a05-bbb3-d58ac58880d5
- 6fc1b880-3a3b-44e5-9f91-17c9228ed1dd
- 225b8214-35bd-46aa-8e33-47fd37058214
- 07118a57-42ec-4498-9da4-0241aedb012c
- 9904620c-a731-4617-a4bc-fb44b8d53e6b
- 195c646e-8456-4a2f-94db-3d136541bfc2
- 87f00262-55f3-4f7e-98fe-b606b239e1e0
- bba6ffa1-7482-4903-9535-ccad8a788fda
- 3c3b11ba-4810-466b-9438-6fbc3bffa96e
- f59d4355-82e5-4296-a1da-d9edb3d0516b
- 05f2421c-9e0d-4d01-b44c-48ff32145dad
- a0978747-df2f-477e-bf40-2e410e49776f
- a7786816-e782-4ddc-a01e-32b231704914
- 52194b49-49dd-4ede-9954-f8e1ede9de2d
- 14694523-c54e-4f88-bf75-6534144d007e
- 587f9adb-25e3-46e5-bb4b-ea8af6599266
- f45c4510-bc6e-42b5-a47b-8de3cec38aff
- 4bfe1160-8eac-4d49-a3e0-3443ced416bf
- 966e9827-7241-45c1-b4ee-90836f7790f2
- 9110d227-3703-4474-95eb-683285a743e9
- edf45a3b-1b5b-477a-8b11-f887a0f41d0e
- 81db047d-398c-499f-be59-d8fff78949ea
- 75bb9bde-6d8f-4a27-b8e5-e9a438102234
- dada9849-5165-4128-b2eb-3a1ba643168d
- e44ef7bf-f4a2-4969-b801-37bd2aa12eb1
- 5a6dec95-c7be-4983-9568-c2b42d7fbc65

EXCEPTION_DURING_OFFER_QUANTITY_UPDATE:
- e6b0742b-b5cf-403e-ae7a-fd11542d2bd5
- 4a5ea468-a156-434f-85a7-4265fd0eedac
- b683e537-8078-4137-8e61-d12a4612ff33
- 6489e0ae-fbf3-46ac-98ef-f24a9f35c8e2
- 3b5736fa-51bd-4f83-90b6-eadd26bce37b
- 18019beb-a62d-4485-b048-838e4ef815d0
- 3402776a-dcac-42d0-b229-2033be297516
- 82bacb6f-893b-4c96-bc58-33ffd44244a8
- 4b2063da-47e1-4dc0-b4ab-bb7cf910ef51
- dcf23667-5d50-4950-b40c-a78a8728069c
- 45079b66-6df7-4315-bd38-af562845fa05
- 4acc8761-f135-4fe0-a2a5-09b0c8a77cb1
- 338f9e6a-dbee-401f-9a5c-25a842431f3a
- 92d19aff-dd06-4c9f-a9d5-1a974fef81f5
- 547e8711-8615-418e-81a2-40280406ee9e
- bce0c4de-a2d9-4215-8088-bd15cd9f1229
- 0e87b7a9-7ec7-47ef-9cf4-67445faf7c2d
- 694e7076-1c7b-4f4b-a4e0-8b09775b76da
- 473044f4-e1f5-4a9e-8bde-2a02fd4986f1
- 4941d5b4-0de3-4914-afb6-73510c565e7a
- a01af0b4-6e34-43b9-b8ee-4311266930a3
- 54309b2d-1780-459a-a6e3-0db2f9cb24a4
- 14edc0b7-ece7-46d5-99fb-bee9384388e0
- cfd733f0-ccca-410a-9071-7ce5cf62f44d
- 7881ca27-69e5-4174-917a-021a896646ed
- 73d8643f-00c9-48d2-9474-94dc25c26487
- edb2da9d-66ce-425e-9dee-faec488f1ca6
- c3440a6f-8a0d-4090-aef9-301fd7ae2ce6
- 77588d9c-ec7f-421b-8cbe-ba411ce85d73
- a5167331-72a8-4b86-a12a-e830170eff0d
- dbc85efb-0b9f-4fc4-9086-28cd31732d59
- 5f1ccc6a-f33c-4b81-97f8-68e853637f79
- 29fc08a6-c7c6-4b5b-a884-1ced832b1674
- b348bcf8-0f44-403f-8c25-cec8b3ea38fd

Co więcej - gdy chcę wznowić produkt, który po waszej stronie miał stock = 0 zaczynam proces od aktualizacji ilości (status = END). Potem puszczam metodę do publikacji produktu oraz zmiany ceny. Niestety, zmiana stocku zwraca mi EXCEPTION_DURING_OFFER_QUANTITY_UPDATE po czym pada cała procedura wznawiania oferty.

**Comment by PawelTaberski** [comment]
Przetestowałem metodę na Twoim requeście i działa poprawnie, sprawę zgłosiłem do zespołu, który pracuje nad tymi zasobami. Podeślij proszę jeszcze kilka przykładowych trace-id z problemem zmiany ceny. Odnośnie stocku i publikacji musiałbyś podesłać pełne cURL-e i responsy z trace-id abym mógł zbadać sprawę.
Zadania jak najbardziej są kolejkowane, ale możliwe że jedna czynność wystartowała i jeszcze się nie zakończyła i wpadła następna.

**Comment by Maczuga** [comment]
Ze zmianą ceny:
4778b8c456abd6de - FID polecenia zmiany ceny
6e1c93e9375f443d - FID taska ze statusem FAIL i PRICE_UPDATES_COUNT_EXPIRED

Z FIDami do zmian stoku to teraz ciężko z tym będzie, ponieważ te produkty się wystawiły i gdy status był w nich już = ACTIVE to ceny i ilości również się poaktualizowały (w oddzielnych requestach niż te wadliwe). Czyżby nie można było zmieniać cen i ilości zanim produkt ma status = ACTIVE? Bo jak tak to nie mam jak wznowić ofert, które miały na stanie 0 przez błąd "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE".

**Comment by avello** [comment]
Też mam problemy z aktualizacją ceny. Błąd jak powyżej "PRICE_UPDATES_COUNT_EXPIRED" 
task ID:
 c54e0f46-cbd7-4957-6a99-5ab7bd0f492a
21f2f5a4-3358-e9f9-efbe-2128e0f84d51
8efc93b3-38e5-80b2-1ae5-6c3002463eb2
79887205-7884-2dd1-5aed-f43cd810faa6
f1777efa-af52-a864-3ddd-71c19a78a972
i dużo jeszcze, nie będę wszystkich wypisywał

**Comment by PawelTaberski** [comment]
@Maczuga  Przekazałem dodatkowe dane do zadania. Odnośnie samych zmian to nie możesz dokonywać tymi metodami zmian w ofercie, która jest w trakcie aktywacji, ale możesz jak najbardziej zarówno w zakończonych jak i aktywnych.
@avello Przekazałem Twoje dane również do zadania.
Prośba o cierpliwość.

**Comment by Maczuga** [comment]
Półtora miesiąca bez zmian a jutro ostatni dzień roboczy na integracje...

**Comment by PawelTaberski** [comment]
@Maczuga Otrzymałem informację, że udało się wdrożyć zmianę i jeśli nie uda się wyedytować ceny w danej ofercie otrzymasz komunikat informujący co konkretnie się nie udało. Sprawdź proszę zasobem GET /sale/offer-price-change-commands/{commandId}/tasks  status tego zadania. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/my_offers/#3f).

**Comment by Maczuga** [comment]
A co z EXCEPTION_DURING_OFFER_QUANTITY_UPDATE zgłaszanym tutaj? https://github.com/allegro/allegro-api/issues/1493#issuecomment-482782031

**Comment by PawelTaberski** [comment]
Tak jak odpisałem Tobie wcześniej:
Otrzymałem informację, że udało się wdrożyć zmianę i jeśli nie uda się wyedytować ceny w danej ofercie otrzymasz komunikat informujący co konkretnie się nie udało. 
Zmiana w ofertach jakie przesyłałeś wcześniej była niemożliwe bo były one niekompletne. Aby można było zmienić np cenę, stock w ofercie musi być ona kompletna m.in. zawierać wszystkie wymagane parametry.

**Comment by Maczuga** [comment]
Tak jak odpisałem Tobie wcześniej (bo widzę, że czytanie leży. Ja piszę o QUANTITY, Ty piszesz o PRICE...):
A co z EXCEPTION_DURING_OFFER_QUANTITY_UPDATE zgłaszanym tutaj? https://github.com/allegro/allegro-api/issues/1493#issuecomment-482782031

Taski dalej zwracają EXCEPTION_DURING_OFFER_QUANTITY_UPDATE

**Comment by PawelTaberski** [comment]
Dokładnie tak samo, tak jak pisałem niezależnie co chcesz zmienić w ofercie musi być ona kompletna inaczej nie dokonasz zmian.

**Comment by Maczuga** [comment]
Widzę, że ignorowania tematu ciąg dalszy. Wszystkie te oferty były kompletne, ponieważ błąd ten występuje jedynie podczas publikacji oferty (proces dokładnie opisany tutaj: https://github.com/allegro/allegro-api/issues/1493#issuecomment-482782031). Jakby oferta była niekompletna, to nie można byłoby jej opublikować, a publikacja idzie, wywala tylko aktualizacja ilości...

**Comment by PawelTaberski** [comment]
Otrzymałem informacje od zespołu odpowiedzialnego za tę funkcjonalność, że przy większości przypadków błąd u Ciebie był spowodowany tym, że oferty miały błędy uniemożliwiające wprowadzenie zmian m.in. brak wymaganych parametrów. Odnośnie przypadków o których napisałeś każda zmiana w ofercie może zająć do godziny czasu i oczywiście zadania są kolejkowane, ale jeżeli system wykryje brak tej oferty jako aktywnej wyrzuci błąd.

**Comment by Maczuga** [comment]
> Najpierw musi zakończyć się akcja np. publikacji oferty i dopiero wtedy powinieneś wrzucić taska zmiany w ofercie.

No i na tą jedną informację czekałem. Tylko czemu nie można takiej informacji wstawić do zwrotu z błędem zamiast "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE"?

**Comment by PawelTaberski** [comment]
Dostałem informację, że dodaliśmy komunikat informujący jak sprawdzasz task-a dlaczego operacja się nie powiodła. Czy w dalszym ciągu masz w takim wypadku tą samą informację co do nowszych zadań?

**Comment by avello** [comment]
Mam problem podczas aktualizacji ceny.
Kod błędu to OPERATION_FAILED mam wiele takich błędów.
Wcześniej dla wielu aukcji gdzie mam ten błąd miałem inny błąd PRICE_UPDATES_COUNT_EXPIRED który chyba już został naprawiony.
Przykładowy TaskId: cd88b5a2-5f8c-44af-9833-137aa3b29f8f
Proszę o sprawdzenie gdzie jest problem.

**Comment by Maczuga** [comment]
@PawelTaberski EXCEPTION_DURING_OFFER_QUANTITY_UPDATE w dalszym ciągu jest zwracane zamiast poprawnego komunikatu. Wczoraj o 12:40 mieliśmy wysyp tego błędu.

ID tasków:
- a09087f2-9e00-4233-a3e3-1fa6505b0af6
- a66bdcfb-fcd7-433a-8432-3fa9d4f247ca
- f8c0dcb9-f5c4-4ae2-9e61-88abc83d63d6
- 510952e6-8d07-4e96-a995-9d28e539c873
- fc5b92a1-8330-44cf-b30b-fa106dda2029
- 522eb834-a5d5-4b9c-9c6a-66b1a099a678
- 732b14f4-fafc-4c04-aad3-7b58c2b9795a
- d56266ea-1cb0-42f0-8472-3b51222b134d
- 68da2c69-910e-4068-94ce-9003bed8741e
- cf917415-2fd9-4176-ab61-cd31e5cb141b
- bb721254-c1f2-4c99-ab81-36497b5d5c93
- 120cf8b7-0a90-43b6-94d1-c9024bd434ec
- 362ec367-bb39-491d-9124-e4df997e6340
- 2e9d1f35-f83f-4073-8fa7-c8a76f2923cf
- a1528ac9-0e82-4071-8c06-148838dab105
- 5ede38c2-c40f-42b5-b5fe-c6e5a7a1bcc2
- 332d3640-8e90-4e84-ab81-dec29bf021c2
- d19b2235-a665-481e-86ef-9cce6fba856f
- 74217e84-15e0-4106-a5c5-60545d9e8f20
- 34e33be7-9b35-46a4-97e2-26f34d33f1ed
- 675fa8f0-7368-4824-b736-94d6c98eb4d0
- 8b83c0c9-2ce0-46a6-b792-1919590da65f
- 1cab1e3b-b43b-4dbc-950a-9fbf85c328fb

**Comment by PawelTaberski** [comment]
@avello Mógłbyś podesłać trace-id zadania przy jakim otrzymałeś taki błąd

**Comment by avello** [comment]
Ja już sobie poradziłem z tym błędem aktualizacji ceny.
Okazało się że błąd pojawia się ponieważ nie miałem uzupełnionych pól wymaganych w ofercie.

1. Nie wiem co ma wspólnego cena z innymi polami w ofercie, przecież to jest dedykowany zasób do zmiany ceny więc nie wiem po co sprawdza inne pola.
2. Komunikat ze szczegółami znajduje się w task->errors a nie ma tego w dokumentacji https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET, i nie ma nigdzie informacji że coś takiego zostało dodane, więc skąd miałem wiedzieć co jest nie tak, bazowałem tylko na task->message

**Comment by PawelTaberski** [comment]
Pracujemy nad poprawą komunikatów błędów. Odnośnie samych zmian w ofercie to wszystko się zgasza, aby dokonać jakiejś edycji w ofercie w Twoim wypadku zmiany ceny, to musi być ona kompletna.

**Comment by Maczuga** [comment]
Podbijam, żeby nie zostało zamknięte, ponieważ niektóre komunikaty nadal nic nie mówią o swoim znaczeniu.
