### ISSUE TITLE
Błąd tablicy zwracającej cenniki dostaw - czas dostawy

### ISSUE THREAD

**Issue by pokash** [allegro/allegro-api#1495]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Pobierana tablica z cennikiem dostawy nie zwraca informacji o przedziale czasowym. Obiekt posiada wartość null:

- Kurier DPD
{
  "deliveryMethod": {
    "id": "c3066682-97a3-42fe-9eb5-3beeccab840c"
  },
  "maxQuantityPerPackage": 1,
  "firstItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "nextItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "shippingTime": null
}

- Kurier DPD pobranie
{
  "deliveryMethod": {
    "id": "259b5c7a-9056-4c74-80ec-8bdc50cb0413"
  },
  "maxQuantityPerPackage": 1,
  "firstItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "nextItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "shippingTime": null
}

- Allegro Paczkomaty 24/7 InPost
{
  "deliveryMethod": {
    "id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93"
  },
  "maxQuantityPerPackage": 1,
  "firstItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "nextItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "shippingTime": null
}

- Paczka w RUCHu
{
  "deliveryMethod": {
    "id": "b715fac1-8ec2-4f5c-8fdf-0f9cec9085ad"
  },
  "maxQuantityPerPackage": 1,
  "firstItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "nextItemRate": {
    "amount": "0.00",
    "currency": "PLN"
  },
  "shippingTime": null
}

Czy błąd w postać braku poprawnego zwrócenia informacji o czasie dostawy jest zamierzony, czy też nieprzewidziany?

Proszę o info.

Dziękuję i pozdrawiam,

Łukasz Gabrysiak

**Comment by PawelTaberski** [comment]
Jest tam zwracana informacja tylko przy metodach dostawy w których jest możliwa edycja tego parametru i tylko jeżeli go wyedytujesz.

**Comment by pokash** [comment]
To co mówisz jest niezgodne z informacją w dokumentacji...
według opisu w dokumentacji, jeżeli nie jest wyedytowana ma zostać zwrócona wartość domyślna
(Custom shipping time for the given delivery method. If not set the default shipping time for the method is used.)

To albo dokumentacja jest niedokładnie opisana w tym punkcie, albo bug w informacjach zwracanych. W WebApi te dane zwracane są pięknie, niestety w RestApi... nie.

**Comment by PawelTaberski** [comment]
Rozumiem ta metoda z tego co kojarzę od zawsze tak działa, czy te dane są dla Ciebie potrzebne? Jeśli tak to do czego byś ich użył? Chciałem zgłosić Twoje zapotrzebowanie na te dane jako sugestię dlatego dopytuję.

**Comment by pokash** [comment]
Witam,
dziękuję za analizę problemu :) oczywiście mógłbym się obyć bez tych informacji, jednakże dobrze gdyby były, gdyż na podstawie tych danych odpytywanie do API firm kurierskich, aby pobierać informacje o statusie było by ograniczone w czasie wskazanym poprzez informacje zapisane w tym obiekcie. Tzn, system mógłby pozwolić na wcześniejsze reagowanie na opóźnione przesyłki z winy firm spedycyjnych. Niestety klienci w dużej mierze za opóźnienia winią sprzedającego (mimo iż to nie jego wina). Czy więc jest możliwość wprowadzenia tych informacji?

Pozdrawiam,
Łukasz Gabrysiak

**Comment by PawelTaberski** [comment]
Zgłosiłem Twoją sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć takie rozwiązanie poinformujemy o tym.

**Comment by pokash** [comment]
Super ;) Dziękuję 👍
