### ISSUE TITLE
doGetItemInfo zwraca nieaktualne dane

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#1496]
Występuje problem: 
 - [ x] z metodą WebAPI
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: 
Dla części aukcji API zwraca błędne dane, np.:
aukcja: 7955083736
API zwraca cenę: 1,5
tymczasem aukcja ma cenę końcową 18,50 i zakończyła się 2 godziny temu

**Comment by PawelTaberski** [comment]
Sprawdziłem i widzę, że zwraca prawidłową cenę:
```
                  <ns1:itId>7955083736</ns1:itId>
                  <ns1:itCountry>1</ns1:itCountry>
                  <ns1:itName>Zestaw mat do grilla int!rend</ns1:itName>
                  <ns1:itPrice>18.5</ns1:itPrice>
                  <ns1:itBidCount>4</ns1:itBidCount>
```
Sprawdź czy u Ciebie problem dalej występuje.

**Comment by mariobros6** [comment]
Problem występował od 18 do 2 w nocy wczoraj.
Teraz jest ok.
Problem cyklicznie wraca w różnej skali.

**Comment by PawelTaberski** [comment]
Jak znów napotkasz na taki problem, to podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa w formacie XML wraz z konkretnym timestampem kiedy wysłałeś takiego requesta i info na jakim kluczu i na jakiego usera masz klucz sesji.

**Comment by mariobros6** [comment]
Od godziny ponownie masowo dostaję nieaktualne dane: 
7985522996 - zwraca 30 zł, a jest 47

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda zwraca 47 jednakże już sporo czasu minęło od Twojego zgłoszenia. Pamiętaj, ze każda zmiana na ofercie może się procesować do godziny czasu.
Jeśli kiedyś znów napotkasz na taki problem koniecznie podeślij kiedy dokonałeś zmiany ceny (najlepiej jak się da wraz z requestem i responsem) dodatkowo respons z DoGetItemsInfo z konkretnym timestamp-em.
