### ISSUE TITLE
[REST API] Dlaczego nie mogę wznowić aukcji?

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#1497]
Mam problem z jedną aukcją, nie mogę jej wznowić. Mogę normalnie ją aktualizować. Po próbie wznowienia otrzymuje komunikat `An error occurred while trying to change the publication of the offer. Please try again later.`. Proszę o pomoc w zdiagnozowaniu przyczyny.

Dane oferty oraz command_id przesyłam przez formularz...

**Comment by PawelTaberski** [comment]
Jak tylko otrzymam dane, to zapoznam się z nimi i dam znać.

**Comment by PawelTaberski** [comment]
@mindc Zobacz czy teraz uda się Tobie wznowić ofertę.

**Comment by mindc** [comment]
@PawelTaberski 
Niestety, oferta się nie aktywuje, a po sprawdzeniu `tasks` dla komendy mam ten sam błąd...

**Comment by PawelTaberski** [comment]
Zgłosiłem problem do zespołu, który odpowiada za te zasoby, podeślij jeszcze tylko proszę trace-id zadania publikacji.

**Comment by mindc** [comment]
@PawelTaberski 
przekazałem jakiś czas temu przez formularz...

**Comment by PawelTaberski** [comment]
Otrzymałem tylko commandId przesyłałeś również Trace-Id?

**Comment by mindc** [comment]
@PawelTaberski 
przekazałem także Trace-ID

**Comment by PawelTaberski** [comment]
Dzięki, jak tylko otrzymam to dodam do zadania.
