### ISSUE TITLE
Brakujące pola oferty w obiekcie Offer /sale/offers/{offerId} vs OfferListingDtoV1 /sale/offers

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1498]
:bulb: **Sugestia**

Dzień dobry, zgodnie z [dokumentacją](https://developer.allegro.pl/sale/#similar-offer):

> Metodą GET na zasobie /sale/offers/{offerId} pobierzesz wszystkie pola wskazanej oferty.

Zwracam się zatem z prośbą aby uzupełnić dane zwracane przez zasób [/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) obiekt do edycji **Offer** o dodatkowe informacje zwracane przez zasób [/sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) obiekt na liście **OfferListingDtoV1**.

Lista brakujących danych w Offer vs OfferListingDtoV1:
- Offer:images -> OfferListingDtoV1:primaryImage nie wiadomo, który url obrazka jest główny, edycja zwraca listę obrazków
- Offer:sellingMode:?? -> OfferListingDtoV1:saleInfo:biddersCount brak danych odpowiadających ilości licytujących w Offer
- Offer:stock:?? -> OfferListingDtoV1:stock:sold brak danych odpowiadających ilości sprzedanych towarów w Offer (wspomiane w [tym wątku](https://github.com/allegro/allegro-api/issues/1295))
- Offer:??:?? -> OfferListingDtoV1:stats:watchersCount brak danych odpowiadających ilości użytkowników obserwujących aukcję w Offer
- Offer:??:?? -> OfferListingDtoV1:stats:visitsCount brak danych odpowiadających ilości wyświetleń w Offer
- Offer:publication:?? -> OfferListingDtoV1:publication:startedAt brak danych odpowiadających dacie rozpoczęcia w Offer
- Offer:publication:?? -> OfferListingDtoV1:publication:endedAt brak danych odpowiadających dacie zakończenia w Offer

[/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) obiekt do edycji **Offer**
```
{
  "additionalServices": {
    "id": "string"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "string"
    },
    "returnPolicy": {
      "id": "string"
    },
    "warranty": {
      "id": "string"
    }
  },
  "category": {
    "id": "string"
  },
  "compatibilityList": {
    "items": [
      {
        "text": "string"
      }
    ]
  },
  "contact": {
    "id": "string"
  },
  "createdAt": "2019-04-12T07:17:54Z",
  "delivery": {
    "additionalInfo": "string",
    "handlingTime": "PDT12H30M5S",
    "shipmentDate": "2018-04-01T08:00:00Z",
    "shippingRates": {
      "id": "string"
    }
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "string"
          }
        ]
      }
    ]
  },
  "ean": "string",
  "external": {
    "id": "string"
  },
  "id": "string",
  "images": [
    {
      "url": "string"
    }
  ],
  "location": {
    "city": "string",
    "countryCode": "string",
    "postCode": "string",
    "province": "string"
  },
  "name": "string",
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "string",
        "to": "string"
      },
      "values": [
        "string"
      ],
      "valuesIds": [
        "string"
      ]
    }
  ],
  "payments": {
    "invoice": "string"
  },
  "product": {
    "id": "string"
  },
  "promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
  },
  "publication": {
    "duration": "PDT12H30M5S",
    "endingAt": "2019-04-12T07:17:54Z",
    "startingAt": "2019-04-12T07:17:54Z",
    "status": "string",
    "endedBy": "USER"
  },
  "sellingMode": {
    "format": "string",
    "minimalPrice": {
      "amount": "123.45",
     "currency": "PLN"
    },
    "price": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "sizeTable": {
    "id": "string"
  },
  "stock": {
    "available": 0,
    "unit": "string"
  },
  "updatedAt": "2019-04-12T07:17:54Z",
  "validation": {
    "errors": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "validatedAt": "2019-04-12T07:17:54Z"
  }
}
```
[/sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) obiekt na liście **OfferListingDtoV1**
```
{
  "offers": [
    {
      "id": "string",
      "name": "string",
      "category": {
        "id": "string"
      },
      "primaryImage": {
        "url": "string"
      },
      "sellingMode": {
        "format": "BUY_NOW",
        "price": {
          "amount": "123.45",
          "currency": "PLN"
        },
        "minimalPrice": {
          "amount": "123.45",
          "currency": "PLN"
        },
        "startingPrice": {
          "amount": "123.45",
          "currency": "PLN"
        }
      },
      "saleInfo": {
        "currentPrice": {
          "amount": "123.45",
          "currency": "PLN"
        },
        "biddersCount": 0
      },
      "stock": {
        "available": 0,
        "sold": 0
      },
      "stats": {
        "watchersCount": 0,
        "visitsCount": 0
      },
      "publication": {
        "status": "INACTIVE",
        "startingAt": "2019-04-12T07:17:54Z",
        "startedAt": "2019-04-12T07:17:54Z",
        "endingAt": "2019-04-12T07:17:54Z",
        "endedAt": "2019-04-12T07:17:54Z"
      },
      "afterSalesServices": {
        "impliedWarranty": {
          "id": "string"
        },
        "returnPolicy": {
          "id": "string"
        },
        "warranty": {
          "id": "string"
        }
      },
      "additionalServices": {
        "id": "string"
      },
      "external": {
        "id": "string"
      }
    }
  ],
  "count": 0,
  "totalCount": 0
}
```

**Comment by PawelTaberski** [comment]
Odnośnie Twoich sugestii:
Zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/#new-offer), zawsze pierwsze zdjęcie z tablicy jest głównym.
Odnośnie pozostałych, metoda GET /sale/offers/{offerId} służy do pobrania wszystkich pól oferty dzięki którym możesz np wystawić podobną ofertę, wszystkie te które wspomniałeś byłyby nad wymiarowe. 
Te informacje znajdziesz m.in, ilość obserwujących, liczbę sprzedanych, datę wystawienia itp. znajdziesz w zasobie GET na zasobie /sale/offers. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by SebastianOzdoba** [comment]
@PawelTaberski  to potrzeba zrobić to: https://github.com/allegro/allegro-api/issues/1414
Wyszukiwanie po numerze aukcji jest ważnym tematem

**Comment by PawelTaberski** [comment]
Sugestię zgłosiłem jeśli zdecydujemy się na wdrożenie po poinformujemy o tym w dedykowanym komunikacie. Dodatkowo oznaczyłem, że zapotrzebowanie jest zgłaszane przez większą liczbę userów.
