### ISSUE TITLE
[Rest] Zdarzenia po numerze aukcji

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#1499]
Czy jest możliwość aby na podstawie numeru aukcji pobrać tylko zdarzenia dotyczące tej konkretnej aukcji?

Mam listę aukcji i np. mam informację, że kupiono np. 3 przedmioty i po kliknięciu pokaż szczegóły chcę pokazać informację kto kupił itd. dla tej konkretnej aukcji.

Jedynie co znalazłem, że mogę wyświetlić zdarzenia ale nie ma jak ich pofiltrować po numerze aukcji.

**Comment by PawelTaberski** [comment]
Nie ma dostępnego takiego filtru, jeśli chciałbyś w ten sposób prezentować te informacje musiałbyś obecnie zaimplementować go po swojej stronie. Więcej o możliwościach tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/orders/).
