### ISSUE TITLE
[REST] Pytania dot. wzorca command

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#1500]
Mam pytania dot. implementacji wzorca Command. Niektóre komendy są masowe (np. `offer-price-change-commands`), a niektóre pojedyncze (`change-price-commands`). Proszę o wyjaśnienie działania tych komend przez pryzmat:

- zasobu `/tasks/ `(dla których komend jest dostępny, dla których i nie i dlaczego),
- odwołania się do komendy metodą GET (podając ofc `commandId`) - czemu w niektórych komendach jest taka możliwość, a w innych nie,
- zwracanych statusów (w dokumentacji zauważyłem zależność (pytanie czy poprawną): dla "pojedynczych" zwracane są 
` QUEUEING RUNNING VALIDATED_AND_RUNNING RUNNING_BUT_WITH_ERRORS SUCCESSFUL PARTIAL_SUCCESS ERROR` a dla masowych w `/tasks/` `NEW, SUCCESS, FAIL`)
- komendy masowe jak i pojedyncze mają różne sposoby deklaracji danych wejściowych i wyjściowych (pola input/output w przypadku `change-price-commands` i o różnorodnych nazwach w przypadku masowych).

**Comment by PawelTaberski** [comment]
Zasób /offers/{offerId}/change-price-commands/{commandId} jest dosyć historyczny wdrożony w 2016 roku dlatego jego sposób działania może trochę odbiegać od tych obecnie wprowadzanych, które już mają możliwość sprawdzenia statusu zadania itp. 
Wszystkie zasoby m.in. do grupowej zmiany opisaliśmy [tutaj](https://developer.allegro.pl/my_offers/#3f).  Co do sensu to wywołujesz daną grupową zmianę i następnie możesz GET-em pobrać zestawienie ile zmian zakończyło się sukcesem, błędem bądź są w trakcie, jeśli występuje błąd korzystasz z /task , aby sprawdzić jego powód.
