### ISSUE TITLE
[REST]: GET /offers/listing?searchMode=REGULAR... zwraca bzdury !!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1501]
Jeśli to ma być to nowe "wspaniałe" API, to gratuluję !
Przykład zweryfikowany z użytkownikiem zalogowanym na koncie:
https://allegro.pl/uzytkownik/TM-FACTORY
- aktywnych ofert jest ponad 4 tys.
- zasób /offers/listing?searchMode=REGULAR... zwraca ciągle 3515
- podobnie zresztą jak liczba (3515) podawana na listingu sprzedawcy
Kiedy będzie to PRODUKCYJNA i stabilna wersja interfejsu - za 2-3 lata ??

**Comment by PawelTaberski** [comment]
Wynika to z faktu, że oferty wielowariantowe są grupowane i liczone jako 1, a widzę, że takich user ma sporo. Liczba po API zgadza się z tą widoczną na froncie, także wszystko działa prawidłowo.
Wersja produkcyjna jest jak najbardziej stabilna i możesz z niej bezpiecznie korzystać.

**Comment by FromAnyHole** [comment]
@PawelTaberski - no ale od kiedy taka zmiana zaszła ???
Przecież do niedawna było zupełnie inaczej, a Wy nawet o tym słowem, NIC ?!?

**Comment by FromAnyHole** [comment]
Czy na tym zrzucie też się niby wszystko zgadza ??

**Comment by FromAnyHole** [comment]
@PawelTaberski - jak Pan tego nie widzi (albo udaje), to teraz wprowadzacie ludzi w błąd:
- inna jest sumaryczna ilość ofert w nagłówku listingu (obok nazwy konta)
- inne są wszystkie sumy ofert z poszczególnych kategorii na listingu
- inna jest łączna ilość przedmiotów "kup teraz / licytacje" z tego listingu

Po co takie kombinacje znowu, no i nie komunikujecie o tak istotnej zmianie - a jak taki absurd ma się utrzymać, to trzeba będzie odpytywać wszystkie kategorie po kolei, aby znać wszystkie ID przedmiotów.

**Comment by PawelTaberski** [comment]
Zasób listing jest odzwierciedleniem wyszukiwarka na froncie. Zmiana była wdrażana w kilku krokach, informowaliśmy o tym m.in. tutaj:

- [Moda: nowy sposób wyświetlania ofert wielowariantowych w wynikach wyszukiwania](https://allegro.pl/dla-sprzedajacych/moda-nowy-sposob-wyswietlania-ofert-wielowariantowych-w-wynikach-wyszukiwania-85P8PaRBkT8)
- [Zmiany w sposobie wyświetlania ofert wielowariantowych na listach ofert](https://allegro.pl/dla-sprzedajacych/zmiany-w-sposobie-wyswietlania-ofert-wielowariantowych-na-listach-ofert-gRZ5yrRXwsG)

Jeśli potrzebujesz liczbę pojedynczych ofert jakie ma wystawiony dany sprzedawca skorzystaj z zasobu /sale/offers
W tym danym przypadku wywołaj na tokenie danego usera: /sale/offers?publication.status=ACTIVE

**Comment by FromAnyHole** [comment]
@PawelTaberski - pitu, pitu... Komunikat z końca marca z jakiegoś poradnika, to nie jest to samo co zmiana w sposobie działania metody czy zasobu na API. Może jeszcze trzeba będzie niedługo Wyborczą czytać, żeby dowiedzieć się o zmianach, zwyczajnie każdą tego typu zmianę powinniście komunikować tutaj albo w aktualnościach API. Kolejna głupia i nielogiczna zmiana...

**Comment by PawelTaberski** [comment]
Tak, jak pisałem metoda odzwierciedla możliwości wyszukiwarki na froncie i działa zgodnie z tym jak wyszukiwarka na froncie. Żadne pole w API nie uległo zmianie.

**Comment by FromAnyHole** [comment]
@PawelTaberski - wielka mi łaska, że na publicznych zasobach REST powtarzacie to, co sobie można w prostym zapytaniu po http(s) i beż większych ceregieli (oraz żadnych autoryzacji i tokenów) uzyskać...
Fakt jest taki, że zarówno na tym Waszym "froncie" jak i w REST - odpowiedzi dają błędne wyniki !!

**Comment by FromAnyHole** [comment]
@PawelTaberski - i jeszcze jedno, bo wcale nie odwzorowujecie w tym zasobie wszystkich informacji - jakie zwraca wyszukiwarka "na froncie", czyli danych dotyczących istnienia i dostępności innych wariantów. Dane listingu niosą informacje o grupie wariantowej, a rzeczony zasób już NIE, czyli jest nawet gorzej:

Array
                        (
                            [id] => 7151645688
                            [name] => Zatyczki do uszu Stopery UVEX WHISPER na sznurku
                            [seller] => Array
                                (
                                    [id] => 41666847
                                    [company] => 1
                                    [superSeller] => 1
                                )

                            [promotion] => Array
                                (
                                    [emphasized] =>
                                    [bold] =>
                                    [highlight] =>
                                )

                            [delivery] => Array
                                (
                                    [availableForFree] =>
                                    [lowestPrice] => Array
                                        (
                                            [amount] => 8.99
                                            [currency] => PLN
                                        )

                                )

                            [images] => Array
                                (
                                    [0] => Array
                                        (
                                            [url] => https://c.allegroimg.com/original/01ec5b/ca82acde4dc48599b5843d3a69bc
                                        )

                                )

                            [sellingMode] => Array
                                (
                                    [format] => BUY_NOW
                                    [price] => Array
                                        (
                                            [amount] => 3.97
                                            [currency] => PLN
                                        )

                                    [popularity] => 12
                                )

                            [stock] => Array
                                (
                                    [unit] => UNIT
                                    [available] => 2326
                                )

                            [category] => Array
                                (
                                    [id] => 110252
                                )

                        )

**Comment by FromAnyHole** [comment]
W tak okrojonej wersji to możecie sobie wyłączyć ten zasób całkowicie, mam już pełny zestaw przedmiotów każdego user'a po http - bez autoryzacji, bez takiego czy innego token'a, i zwyczajnie bez łaski...
