### ISSUE TITLE
Zmieniony parametr aukcji - EAN

### ISSUE THREAD

**Issue by zbigniewkuras** [allegro/allegro-api#1502]
Witam,
Czy istnieje możliwość, w której system Allegro sam od siebie zmienia parametr EAN w danej aukcji?

Ostatnio napotkaliśmy problem, w której EAN'y były pomieszane na aukcji, lub kompletnie nie zgadzały się z produktami w innym systemie, z którego aukcje były wystawiane.

**Comment by TomekKaczmarek** [comment]
Dzień dobry,

Nie, taka sytuacja nie powinna mieć miejsca. Proszę podać kilka przykładowych identyfikatorów ofert - sprawdzimy.

**Comment by zbigniewkuras** [comment]
Aukcje w których zauważyliśmy problem:
7787214973
7853114475

**Comment by TomekKaczmarek** [comment]
@zbigniewkuras dziękuję, w żadnych z tych przypadków zmiana nie mogła być zlecona przez nas, gdyż obie oferty są w kategoriach, w których nie łączymy ofert z produktami. Sprawdziłem historię zmian:
7787214973 data zlecenia zmiany EANu 2019-04-05T08:33:44.281Z -  5908309132628 > 5908309108197
7853114475 - EAN jest taki sam, jak w momencie wystawienia oferty.

**Comment by zbigniewkuras** [comment]
@TomekKaczmarek Bardzo dziękuję za informację. 
Czyli, jeśli dobrze rozumiem, aukcja 7787214973 w trakcie wystawienia posiadała EAN 5908309132628, i dopiero 5.04 został zmieniony na 5908309108197.

**Comment by PawelTaberski** [comment]
Zgadza się oferta początkowo miała dodany inny numer EAN, który został później zmieniony.

**Comment by zbigniewkuras** [comment]
@PawelTaberski  Dziękuje bardzo, temat można uznać za zamknięty.
