### ISSUE TITLE
Jak sprawdzić login aktualnie zalogowanego konta?

### ISSUE THREAD

**Issue by tomekbyd** [allegro/allegro-api#1503]
Logując się na różne konta może dojść do pomyłki. Może być aktualne zalogowane inne konto i dochodzi do bałaganu. Jak mając numeryczne user_name z access_token sprawdzić jaki login ma to konto?

**Comment by FromAnyHole** [comment]
Celowo tego "nie przewidziano" w REST, bo nazwy też niebawem zabiorą sprzedawcom, CorpoKomuna...

**Comment by rtnet-pl** [comment]
Musisz użyć metody ze starego api (doGetUserLogin)

**Comment by PawelTaberski** [comment]
Tak, jak napisał @rtnet-pl obecnie musisz użyć metody z WebAPI doGetUserLogin. Nie ma takiej metody w REST API, ale pracujemy nad metodą, którą zwrócić nie tylko login, a także inne dane dotyczące danego usera. Jak tylko będę miał jakieś informacje kiedy wdrożymy taką metodę, to poinformujemy o tym w dedykowanym komunikacie.
