### ISSUE TITLE
Publikacja oferty z drafu

### ISSUE THREAD

**Issue by michcio19923** [allegro/allegro-api#1505]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Stworzyłem draft, opublikowałem na jego podstawie ofertę, ma ona taki sam Id jak Id draftu. Próbowałem utworzyć dla tego samego draftu kolejną ofertę, ale kolejne się nie tworzą chociaż przekazuję nowe commandId. Czy dla jednego draftu można utworzyć tylko jedną ofertę?

**Comment by PawelTaberski** [comment]
Jak najbardziej 1 draft to 1 oferta, bo jak sam zauważyłeś jak tworzysz draft od razu dostajesz id oferty pod jakim będzie widoczna w serwisie, a każda oferta musi być unikatowa, także nie możesz 2 razy opublikować oferty pod takim samym id.
