### ISSUE TITLE
[REST] [od dzisiaj] /sale/offers zwraca zły stock.available

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#1507]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzisiaj od godziny 9 rano stock.available nie zmienia się po aktualizacji stanu. Na stronie zmiany są odzwierciedlane poprawnie.

Trace-Id: 3ee3bd920caebe35, c201b56b34572ebc

ID ofert: 
- 7561567576
- 7991942068
- 7809354684
- 7991960304
- 7991993685
- 7487585593
- 7470906603
- 7991953904
- 7991985314
- 7490784554

**Comment by Maczuga** [comment]
Dla przykładu: oferta 7797048167 przez REST API zwraca stock sprzed godziny 11:30 (wtedy zostało zmienione na 7 sztuk). O 12:55 została wywołana zmiana z 7 na 6 - od tej pory dla tej oferty w stock.available zawsze jest zwracana ilość = 7, mimo, że na stronie wyświetlana jest ilość 6.

Urywek JSONa dla tej ofery z godziny 13:25:

`      {
         "id":"7797048167",
         "name":"LCD + ekran dotykowy Huawei Mate 20 lite",
         "category":{
            "id":"19302"
         },
         "primaryImage":{
            "url":"https://0.allegroimg.com/original/01a3a0/3f72c6464bc1a25cd37477a9e330"
         },
         "sellingMode":{
            "format":"BUY_NOW",
            "price":{
               "amount":"199.0",
               "currency":"PLN"
            },
            "minimalPrice":null,
            "startingPrice":null
         },
         "saleInfo":{
            "currentPrice":null,
            "biddersCount":0
         },
         "stats":{
            "watchersCount":0,
            "visitsCount":3
         },
         "stock":{
            "available":7,
            "sold":0
         },
         "publication":{
            "status":"ACTIVE",
            "startingAt":null,
            "startedAt":"2019-01-23T09:20:08Z",
            "endingAt":null,
            "endedAt":null
         },
         "afterSalesServices":{
            "warranty":{
               "id":"7056923c-50f9-4521-b0a5-b53f49be4e9e"
            },
            "returnPolicy":{
               "id":"2cada474-8262-4221-bf8b-dee2056cb29f"
            },
            "impliedWarranty":{
               "id":"43d3738b-cbb4-4eda-87d3-4122f15e1193"
            }
         },
         "additionalServices":null,
         "external":{
            "id":"38325"
         }
      },`

**Comment by PawelTaberski** [comment]
Sprawdziłem i zarówno na froncie jak i w bazie widzę, że jest obecnie dostępnych 6 sztuk. Pamiętaj, że w zależności od ilości zadań na kolejce zmiana może się procesować nawet do godziny czasu.

**Comment by Maczuga** [comment]
No niestety, ale u nas dalej stany sprzed godziny 10tej są zwracane przez REST API.

**Comment by PawelTaberski** [comment]
Sprawdziłem ofertę zasobem /sale/offers?limit=100&offset=100 i widzę że ma:
```
            },
            "stock": {
                "available": 6,
                "sold": 0
            },
```
Także jak najbardziej poprawnie.
a przy ofercie 7951635070 widzę, że jest zakończona co również się zgadza:
```
            },
            "publication": {
                "status": "ENDED",
                "startingAt": null,
                "startedAt": "2019-04-03T07:19:17Z",
                "endingAt": null,
                "endedAt": "2019-04-15T13:45:08Z"
            },
```
Tak, jak pisałem zmiany na ofercie mogą się procesować do godziny.

**Comment by Maczuga** [comment]
Do godziny, jasne. Tylko dlaczego was zasób od 7 godzin zwraca nam ciągle to samo i to tylko w listingu? Wszelki caching jest wyłączony, problem występuje raptem od dzisiaj, żadnych zmian w kodzie nie było.

**Comment by Maczuga** [comment]
Podesłałem zgłoszenie przez formularz z załącznikiem. Nr. zgłoszenia 05184546, zawiera wszystkie wadliwe requesty/response - dump wykonany o 17:23.

**Comment by Maczuga** [comment]
Tak jak myślałem, masowe opóźnienia po waszej stronie. Stocki z poprzedniej listy właśnie się naprawiły w REST API i listing zwraca poprawne wartości. W momencie pisania są jeszcze ~10-15 minute opóźnienia między REST a tym, co jest na stronie lub przez /sale/offers/{id}, ale zawsze to nie 7-8 godzin.

Szkoda tylko, że tak ciężko wam się przyznać do tego, że problem leży po waszej stronie.
