### ISSUE TITLE
Błąd 404 -  GET /order/checkout-forms/{id}/shipments

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#1508]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Korzystając z zasobu GET /order/checkout-forms/, sterując offsetem, aż do totalCount pobieram zamówienia i do każdego sprawdzam zasobem GET /order/checkout-forms/{id}/shipments. Dla prawie wszystkich zamówień  jest ok, ale w ostatniej setce mam response:

`Client error: `GET https://api.allegro.pl/order/checkout-forms/365debb3-d0ab-11e8-836e-2b88285043e4/shipments` resulted in a `404 Not Found` response:{"code":null,"message":"Order not found","path":null}
`

I teraz zastanawiam się czy to możliwe, że metoda GET /order/checkout-forms zwraca zamówienie jako jeszcze możliwe do pobrania,  a metoda GET /order/checkout-forms/{id}/shipments już tego zamówienia nie widzi?

Dokumentacja mówi, że jeśli zamówienie jest w GET /order/checkout-forms, to jego wszelkie szczegóły są nadal dostępne.

**Comment by PawelTaberski** [comment]
Taka sytuacja może wystąpić w wystąpić w wypadku, gdy np. dany numer checkoutForma jest już nieaktywny. Taki przypadek opisaliśmy w poradniku:
"...Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to oznacza, że mamy do czynienia z połączeniem zakupów przez kupującego)..."
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by PawelTaberski** [comment]
Taka sytuacja może wystąpić w przypadku, gdy kupujący zaznaczył kilka zakupów do wspólnej zapłaty. Opisaliśmy taki przypadek w poradniku:
"...Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to oznacza, że mamy do czynienia z połączeniem zakupów przez kupującego)...."
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).
