### ISSUE TITLE
Brak wpisu w JournalDeals

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#1509]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Dla deal-a 2037817025 mam tylko event 1, pomimo iż klient wypełnił formularz dostawy zaraz po zakupie

**Comment by deneb-k** [comment]
Przyłączam się, klienci nas właśnie zasypują skargami na niepobrane zamówienia.

**Comment by PawelTaberski** [comment]
Podeślijcie proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) dane odnośnie tych transakcji tj:

- ID oferty, 
- login bądź id kupującego
- datę zakupu

Sprawdzimy to. W zgłoszeniu zaznaczcie, że dane są potrzebne do ticketa na GitHub-ie numer 1509.

**Comment by TimothyKoval** [comment]
Długość fiuta też wysłać?

**Comment by PawelTaberski** [comment]
Prosiłbym o zachowanie kultury. Informacje, o które prosiłem pozwolą nam namierzyć problem. Bez konkretnych danych - przy obecnej ilości transakcji w serwisie - wychwycenie błędów pojawiających się tylko u kilku użytkowników jest bardzo trudne i długotrwałe.

**Comment by TimothyKoval** [comment]
Podałem deal id który jest unikalny. Brakiem kultury jest wasze lenistwo.

**Comment by PawelTaberski** [comment]
Większa ilość informacji pozwoli Tobie szybciej uzyskać rozwiązanie problemu, tak jak pisałem potrzebuje jeszcze co najmniej numer oferty jakiej dotyczy transakcja, której numer podesłałeś.

**Comment by TimothyKoval** [comment]
7721144935

**Comment by PawelTaberski** [comment]
@TimothyKoval Widzę, że zwróciliśmy również status o uzupełnieniu formularza dostawy dla tej konkretnej transakcji:
dealEventId - 4551185080
Jednakże rzeczywiście z dosyć sporym opóźnieniem, sprawę zgłosiłem do zbadania.
