### ISSUE TITLE
Czy TimeOuty powróciły?

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1510]
Czy problem przypadkiem nie powrócił?
Od jakiegoś czasu dostaję timeouty (standardowy czas oczekiwania mam ustawiony na 10 sekund).
Praktycznie jedyna metoda której używam to doGetItemsInfo.
Wysyłam dość sporo zapytań (oczywiście w limitach).

Raczej nie występuje przy każdym zapytaniu, ale co kilka-kilkanaście-kilkaset zapytań jest cała seria timeoutów.

**Comment by Maczuga** [comment]
Dzisiaj ogólnie niezła padaka chyba w ich API. Nie wiem jak WebAPI, ale na REST cały dzień dzisiaj timeouty, błędy 50x (wstaw dowolną cyfrę w miejsze x), opóźnienia w niektórych metodach wielogodzinne.

**Comment by PawelTaberski** [comment]
@jakubmaguza Przetestowałem i rzeczywiście co któreś wywołanie na tej metodzie dostaję pustą odpowiedź, sprawę przekazałem do zespołu, który odpowiada za te metody. Proszę o cierpliwość.
