### ISSUE TITLE
Publikacja draftu oferty

### ISSUE THREAD

**Issue by cisekdan** [allegro/allegro-api#1511]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próba publikacji dodanego draftu przez REST API kończy się niepowodzeniem - nie znajduje aukcji o danych id. Przy wystawieniu tego samego drafta przez panel działa.

Request:
```
> PUT /sale/offer-publication-commands/2deedc46-1b8b-463c-93bd-d14e0937fae2 HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer <token>
Api-Key: 94f3b8f2
User-Agent: GuzzleHttp/6.3.3 curl/7.47.0 PHP/7.1.17-1+ubuntu16.04.1+deb.sury.org+1
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 293
Body: {"offerCriteria":[{"offers":[{"id":"7988442909"},{"id":"7988442946"},{"id":"7988442961"},{"id":"7988442986"},{"id":"7988442996"},{"id":"7988443028"},{"id":"7988443048"},{"id":"7988443095"},{"id":"7988443130"},{"id":"7988443150"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}
```

Response:
```
{#786
  +"id": "2deedc46-1b8b-463c-93bd-d14e0937fae2"
  +"taskCount": {#781
    +"total": 0
    +"success": 0
    +"failed": 0
  }
}
```

**Comment by PawelTaberski** [comment]
A jaką odpowiedź otrzymujesz na zasobie /sale/offer-publication-commands/{commandId}/tasks
Więcej na temat statusu publikacji znajdziesz [tutaj](https://developer.allegro.pl/sale/##offer-publication-commands-commandId-tasks).

**Comment by cisekdan** [comment]
Ok, dostaję komunikat `Could not change offer publication status. Size table identifier may not be blank.` aczkolwiek czy tabela rozmiarów jest obowiązkowa dla każdego produktu, niezależnie od kategorii? Np. id szkicu `7988442946` i kategoria `98317`.

Swoją drogą czemu `total` w takim razie pokazuje 0? No i dziś nie jestem w stanie wysłać dokładnie takiego samego requesta (ze zmienionym uuid) gdyż dostaję zwrotkę:
```{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/8837f334-b7ec-4773-81b4-6031a4ebd2ee","userMessage":null}]}```

**Comment by PawelTaberski** [comment]
Total przy wywołaniu metody do zmiany statusu oferty zawsze jest 0 również przy bulkowych zmianach. Wynika to z faktu, że maszyna od razu nie wie ile z zadań przejdzie, ile skończy się sukcesem itp. Jest to prawidłowa odpowiedź. Do sprawdzenia statusu jak i konkretnych informacji co poszło nie tak udostępniliśmy dodatkowe zasoby.
Odnośnie błędu jaki teraz otrzymujesz możliwe, że jest jakiś problem w składni musiałbyś podesłać pełnego cURL-a, abym mógł sprawdzić co jest nie tak. 
Odnośnie tabeli rozmiarów widzę, że na pewno nie jest wymagana w tej kategorii, możliwe, że źle ją wprowadziłeś. Przykład poniżej:
`"sizeTable": null,`

**Comment by cisekdan** [comment]
Co do błędu przesyłam curla:
```
curl 'https://api.allegro.pl/sale/offer-publication-commands/c1ce7f29-a995-4f50-85b4-d69b5c6dc493' -H 'Authorization: Bearer <token>' -H 'Api-Key: <apiKey>' -H 'Content-Type: application/vnd.allegro.public.v1+json' -X PUT -d '{"offerCriteria":{"offers":[{"id":"7996129740"},{"id":"7996129763"}],"type":"CONTAINS_OFFERS"},"publication":{"action":"ACTIVATE","scheduledFor":"2019-04-16T13:51:35Z"}}'
```

`sizeTable` poprawiłem, ale z powodu błędu powyższego wywołania nie mogę przetestować

**Comment by PawelTaberski** [comment]
"offerCriteria": powinno być tablicą czyli powinno to wyglądać tak:
```
{
	"offerCriteria": [{
		"offers": [{
			"id": "7996129740"
		}, {
			"id": "7996129763"
		}],
		"type": "CONTAINS_OFFERS"
	}],
	"publication": {
		"action": "ACTIVATE",
		"scheduledFor": "2019-04-16T13:51:35Z"
	}
}
```

**Comment by cisekdan** [comment]
Ok, działa więc zamykam. Dzięki @PawelTaberski 👍
