### ISSUE TITLE
Jak pobrać produkt ustawionymi dla niego filtrami (atrybutami)

### ISSUE THREAD

**Issue by zetgm** [allegro/allegro-api#1512]
Poprzednia wersja API pozwalała na pobranie listy produktów, ale każdy z produktów zawierał tablicę atrybutów (filtrów). Obecnie wraz z pobraniem listy produktów otrzymuje się listę dostępnych filtrów dla całej kategorii, ale nie przypisanych do poszczególnych produktów.
Czy istnieje możliwość pobrania listy produktów tak by do każdego [items] była przypisana tablica ustawionych dla niego atrybutów filtrów?

Czyli np pobieramy np jakiś telefon i mamy dla niego listę ustawionych atrybutów: np: 
Kolor srebrny
Przekątna ekranu 4"
Wbudowana pamięć 4 GB
Pamięć RAM 512 MB

**Comment by PawelTaberski** [comment]
Obecnie takie dane możesz pobrać tylko jeśli jesteś właścicielem danej oferty przy pomocy zasobu sale/offers/{offerId}
Pracujemy nad zasobem do pobrania publicznych danych o ofercie, ale jeszcze nie znam dokładnej daty wdrożenia takiej metody.

**Comment by zetgm** [comment]
Kiedy przewidujecie dodanie takiej opcji w API? Czy można poznać chociaż przybliżony termin?

**Comment by PawelTaberski** [comment]
Niestety obecnie nie znam takiego terminu, jak tylko będziemy mieć jakieś dane o czasie wdrożenia takiego zasobu to poinformujemy o tym w dedykowanym komunikacie.

**Comment by zetgm** [comment]
W poprzedniej wersji API taka opcja była dostępna, czy istnieje możliwość ponownego włączenia tej opcji w starym API do momentu pojawienia się jej w nowym?

**Comment by MartaNowaczyk** [comment]
Nie planujemy przywracania czegoś, co już usunęliśmy.

**Comment by zetgm** [comment]
Czy cokolwiek zmieniło się w tej kwesti? lub czy jakoś zaplanowane jest dodanie do nowego API informacji publicznej o danym produkcie wraz z ustawionymi dla niego filtrami?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [harmonogramem wygaszania WebAPI Allegro](https://developer.allegro.pl/schedule/) zasób dotyczący pobierania publicznych danych o ofercie mamy zaplanowany na trzeci kwartał.

**Comment by zetgm** [comment]
> Zgodnie z [harmonogramem wygaszania WebAPI Allegro](https://developer.allegro.pl/schedule/) zasób dotyczący pobierania publicznych danych o ofercie mamy zaplanowany na trzeci kwartał.

Czy mogę dowiedzieć się kiedy będzie to dostępne, bo trzeci kwartał się zakończył, a funkcjonalności nadal nie ma.

**Comment by PrzemyslawLukanowski** [comment]
Zasób powinien zostać opublikowany w czwartym kwartale, w najbliższym czasie zaktualizujemy nasz harmonogram. O wdrożeniu zasobu poinformujemy w odpowiednim komunikacie.

**Comment by zetgm** [comment]
Czyli realnie nic w tej kwestii się nie dzieje, gdyż początkowo miało to być zrobione w drugim kwartale, było przeniesione na 3 a teraz na 4 kwartał. Jest to dość niepoważne podejście jeśli chodzi o współpracę na zasadach których oczekujecie, gdyż zabraliście opcję ze starego API nie dając nic w zamian, a co za tym idzie, jeśli ktoś z tego korzystał, musi łaskawie czekać, aż w końcu ktoś coś z tym zrobi. Czy to naprawdę takie trudne, by dać taką opcję?

**Comment by zetgm** [comment]
Witam ponownie w tym temacie, podobnie jak poprzednio kolejny kwartał minął a nic się nie zmieniło, bo nadal usunięta funkcjonalność nie jest dostępna. Czy możemy chociaż dowiedzieć się kiedy REALNIE będzie dostępna?

**Comment by PatrykBocian** [comment]
Prace wciąż trwają - do końca miesiąca postaramy się przekazać jednoznaczne informacje.
