### ISSUE TITLE
Błąd w dokumentacji swagger.yaml PUT /sale/offer-attachments/{attachmentId}

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1513]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, na stronie portalu https://developer.allegro.pl/about/ można pobrać całą dokumentację zasobów w formie swagger.yaml https://developer.allegro.pl/swagger.yaml

Zarówno w dokumentacji na portalu jak i w pliku swagger.yaml jest błąd składniowy w strukturze danych. W metodzie dodającej plik z załącznikiem [PUT /sale/offer-attachments/{attachmentId}](https://developer.allegro.pl/documentation/#operation/uploadOfferAttachmentUsingPUT) brakuje całej sekcji "responses" wraz z kodami HTTP.

Poproszę o uzupełnienie brakującej sekcji responses przykładowo w linii 2722 pliku swagger.yaml (stan na dzień 16-04-2019) celem wyeliminowania błędów generatora open api (swagger).

Podobna metoda [PUT /sale/dispute-attachments/{attachmentId}](https://developer.allegro.pl/documentation/#operation/uploadDisputeAttachmentUsingPUT) dodająca załącznik ma następującą sekcję responses:
```
      responses:
        '201':
          description: File uploaded correctly
        '400':
          description: Syntactically incorrect request
        '401':
          description: Invalid or missing bearer token
        '413':
          description: File is too big
        '415':
          description: Unsupported media type

```

**Comment by PawelTaberski** [comment]
Dzięki za zwrócenie uwagi, przekazałem sprawę do odpowiedniego zespołu, oczywiście uzupełnimy braki.

**Comment by alekskuc** [comment]
Witam, dodatkowo dodam, że to nie jest jedyny błąd w strukturze pliku dokumentacji Allegro REST API swagger.yaml, a jedynie taki uniemożliwiający generowanie kodu.

Pozostałe błędy można zaobserwować chociażby przy użyciu darmowego narzędzia online dostępnego pod adresem https://editor.swagger.io/ gdzie wklejając zawartość pliku swagger.yaml (stan na 19-04-2019) występują następujące błędy według specyfikacji openapi: 3.0.0:

```
Semantic error at paths./sale/offer-attachments/{attachmentId}
Declared path parameter "attachmentId" needs to be defined as a path parameter at either the path or operation level
Jump to line 2693
Structural error at paths./sale/offer-attachments/{attachmentId}.put
should have required property 'responses'
missingProperty: responses
Jump to line 2694
Semantic error at paths./sale/dispute-attachments/{attachmentId}
Declared path parameter "attachmentId" needs to be defined within every operation in the path (missing in "put"), or moved to the path-level parameters object
Jump to line 3218
Structural error at components.securitySchemes.bearer-token-for-application
should NOT have additional properties
additionalProperty: flows
Jump to line 3709
Structural error at components.securitySchemes.bearer-token-for-application.type
should be equal to one of the allowed values
allowedValues: apiKey, http, openIdConnect
Jump to line 3710
Structural error at components.securitySchemes.bearer-token-for-application.flows.clientCredentials
should NOT have additional properties
additionalProperty: authorizationUrl
Jump to line 3713
Structural error at components.schemas.CheckoutFormOrderWaybillResponse
should have required property '$ref'
missingProperty: $ref
Jump to line 7253
Structural error at components.schemas.CheckoutFormOrderWaybillResponse
should match exactly one schema in oneOf
Jump to line 7253
Structural error at components.schemas.CheckoutFormOrderWaybillResponse
should be string
Jump to line 7253
```

Proszę o poprawę.

**Comment by PawelTaberski** [comment]
Jasne przekazałem sprawę do odpowiedniego zespołu.

**Comment by danielu78** [comment]
Witam,
Jaki jest postęp poprawy pliku swagger.yaml , bo błędy nadal występują po imporcie w http://editor.swagger.io/

**Comment by MartaNowaczyk** [comment]
Poprawka dokumentacji w tym temacie jest w trakcie prac. Proszę o jeszcze trochę cierpliwości

**Comment by MartaNowaczyk** [comment]
Poprawki powinny być już widoczne w dokumentacji.

**Comment by alekskuc** [comment]
Witam, na początek:
1. Jest literówka w słowie kluczowym "descritpion" w kliku miejscach.
2. Dodatkowe flow oAuth zgodnie ze specyfikacja open api 3.0 powinno być zdefiniowane jako x-clientCredentials
https://swagger.io/specification/#oauthFlowsObject
https://swagger.io/specification/#specificationExtensions

Reszta zmian jest w trakcie sprawdzania.

```
Errors

Structural error at paths./sale/categories.get.responses.404
should NOT have additional properties
additionalProperty: descritpion
Jump to line 1484
Structural error at paths./sale/categories.get.responses.404
should have required property 'description'
missingProperty: description
Jump to line 1484
Structural error at paths./sale/categories/{categoryId}.get.responses.404
should NOT have additional properties
additionalProperty: descritpion
Jump to line 1517
Structural error at paths./sale/categories/{categoryId}.get.responses.404
should have required property 'description'
missingProperty: description
Jump to line 1517
```

**Comment by MartaNowaczyk** [comment]
1. zmiana jest już przygotowana do wdrożenia
2. sprawdzimy
