### ISSUE TITLE
Nie działa wyszukiwanie w opisie na Sanboxie

### ISSUE THREAD

**Issue by tomarshal** [allegro/allegro-api#1514]
Mamy problemy z wyszukiwaniem fraz w opisach aktualnych aukcji (opcje DESCRIPTIONS) na Sandboxie REST API, wyszukiwane frazy nie są znajdowane, pomimo, że na pewno występują w opisach. Problem dotyczy zarówno REST API jak i wyszukiwarki www.

Na wersji produkcyjnej (wyszukiwarka www) problemów nie ma (przy wyszukiwaniu identycznych fraz).

Proszę o informacjęczy ten problem jest do rozwiązania, jeśli tak, to kiedy.

**Comment by PawelTaberski** [comment]
Podeślij proszę jakiś przykład Twojego zapytania i w jakiej przykładowej ofercie jest takie słowo/wyrażenie (jeśli jest ono jakieś bardzo charakterystyczne). Sprawdzimy to.

**Comment by tomarshal** [comment]
Aukcja: https://allegro.pl.allegrosandbox.pl/oferta/podlaczacz-dwustronnie-odlaczalny-6206268515
Fraza: SWBRSAW18GHAZAIgrape
Zapytanie: https://api.allegro.pl.allegrosandbox.pl/offers/listing?limit=100&offset=0&seller.id=44067436&searchMode=DESCRIPTIONS&phrase=SWBRSAW18GHAZAIgrape

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest problem zarówno wyrażenia wspomnianego przez Ciebie jak i pełnego w nawiasach nie wyszukuje poprawnie. Sprawę zgłosiłem do zespołu, który odpowiada za ten zasób.

**Comment by tomarshal** [comment]
Dziękuję, ile może - mniej więcej - potrwać naprawa?

**Comment by PawelTaberski** [comment]
Nie jestem w stanie podać jakiś ram czasowych, wszystko zależy jak bardzo problem okaże się skomplikowany.

**Comment by tomarshal** [comment]
W przypadku rozwiązania mogę liczyć na informację w tym wątku?

**Comment by PawelTaberski** [comment]
Oczywiście, jak tylko dostanę informacje, że problem jest rozwiązanym dam Tobie znać.

**Comment by mmfreq** [comment]
probem jest juz od dawna, zglaszałem to 29 marca i do dziś nic...
https://github.com/allegro/allegro-api/issues/1459

**Comment by PawelTaberski** [comment]
Dostałem informacje, że najnowsze oferty powinny się już normalnie wyszukiwać na sandboxie, problem może występować już tylko ze starszymi ofertami.

**Comment by mmfreq** [comment]
Dziś sprawdzałem, nic się nie zmieniło, dalej nie wyszukuje, nawet w dziś wystawionych aukcjach.

**Comment by PawelTaberski** [comment]
Podeślij proszę jakiś przykład oferty i zapytania przekażę je do zespołu, który nad tym pracuje.
