### ISSUE TITLE
doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1515]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Metoda webAPI: doGetPostBuyFormsDataForSellers, zgodnie z dokumentacją: postBuyFormAdrId jest to id punktu odbioru. Prośba o info czy tam są tylko punkty odbioru czyli punkty Poczty, Żabki, Paczkomaty?
Czy coś jeszcze?
<ns1:postBuyFormGdAddress>
            <ns1:postBuyFormAdrCountry>1</ns1:postBuyFormAdrCountry>
            <ns1:postBuyFormAdrStreet>Henryka Sienkiewicza 17A</ns1:postBuyFormAdrStreet>
            <ns1:postBuyFormAdrPostcode>05-080</ns1:postBuyFormAdrPostcode>
            <ns1:postBuyFormAdrCity>Izabelin B</ns1:postBuyFormAdrCity>
            <ns1:postBuyFormAdrFullName>Sklep Żabka</ns1:postBuyFormAdrFullName>
            <ns1:postBuyFormAdrCompany></ns1:postBuyFormAdrCompany>
            <ns1:postBuyFormAdrPhone></ns1:postBuyFormAdrPhone>
            <ns1:postBuyFormAdrNip></ns1:postBuyFormAdrNip>
            <ns1:postBuyFormCreatedDate>2019-04-08 11:18:52</ns1:postBuyFormCreatedDate>
            <ns1:postBuyFormAdrType>0</ns1:postBuyFormAdrType>
            **<ns1:postBuyFormAdrId>905554</ns1:postBuyFormAdrId>**
          </ns1:postBuyFormGdAddress>

**Comment by PawelTaberski** [comment]
Jeśli chodzi Tobie o przykładowo fid 51, to tak jak otrzymujesz w DoGetSellFormFieldsForCategory:
```
<ns1:item>
                  <ns1:sellFormId>51</ns1:sellFormId>
                  <ns1:sellFormTitle>Punkty Poczta, Żabka, Orlen, Ruch (pierwsza sztuka)</ns1:sellFormTitle>
```

**Comment by SebastianOzdoba** [comment]
@PawelTaberski  to chciałbym doszczegółowić. Czy ten identyfikator w buyFormAdrId, jeśli jest to punkt PP, Żabki itp to jest identyfikator umożliwiający automatycznie nadanie do tego punktu?
Chodzi mi o to że przyjdzie mi przykładowa wartość: 905554 i wiem że to punkt Żabki, zatem mogę założyć że ten identyfikator jasno identyfikuje ten punkt w samej żabce. Reasumując nie jest to wewnętrzny identyfikator Allegro :)

**Comment by PawelTaberski** [comment]
To identyfikator z systemu przewoźnika, który wskazuje dany punkt.
