### ISSUE TITLE
Nieaktywne konto sandbox

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#1516]
Dlaczego na sandboxie aktywacja konta nie jest z automatu? Tylko trwa werfyfikowanie danych od 24 h.. Nie mogę wystawić testowych ofert. Proszę o aktywację konta z podanym mailem cyranmarcin [at] gmail.com

**Comment by PawelTaberski** [comment]
Również i nam to sprawia problemy, i zależy nam aby zautomatyzować ten proces. Mam nadzieję, że niedługo da się rozwiązać tą kwestię.
Konto aktywowałem :-)
