### ISSUE TITLE
Automat Poczty Polskiej - wybrano pobranie, a nie powinno być to możliwe

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#1517]
Dzień dobry,
W jednym z zakupów klient wybrał **Allegro Punkty Poczta pobranie**:
> lst Automat Pocztowy
> (117028)
> Icchoka Lejba Pereca 13/19
> 00-800 Warszawa
Jednak ten punkt nie obsługuje pobrania. Przez to nie dało się z automatu zrealizować wysyłki przez API Poczty (była wymagana zmiana metody wysyłki).

Czy w jakiś sposób weryfikujecie punkty odbioru pod kątem pobrań?

**Comment by PawelTaberski** [comment]
Wiemy o tym problemie i pracujemy nad tym, ale jego rozwiązanie nie leży do końca po naszej stronie a również przewoźników.

**Comment by magik092** [comment]
W takim razie póki problem istnieje będziemy to ręcznie obsługiwać. Dzięki za info.

Btw. Nie chcąc zakładać nowego wątku - znamy już jakieś przybliżone daty kiedy zasoby /order wyjdą z wersji beta?

**Comment by PawelTaberski** [comment]
Najprawdopodobniej w lipcu wystawimy w wersji public.
