### ISSUE TITLE
Typy danych

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1518]
Mam pytanie odnośnie typów danych zwracanych przez REST API. Często zdarza się, że dwa różne zasoby zwracają niemal identyczne dane a mają w dokumentacji dwa różne typy. Czy to jest zamierzone działanie? Czy może powinien być jeden wspólny typ?

Dla przykładu:
[Get seller's offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)
[Get all fields of the particular offer](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)

Pierwszy z nich zwraca 
`sellingMode` jako object (`OfferListingDtoV1.SellingMode`) 
w którym są zawarte pola:

```
{ 
  format: string (OfferListingDtoV1.OfferType), ENUM
  price:
  minimalPrice:
  startingPrice:
}
```

Drugi zwraca:
`sellingMode` jako object (`SellingMode`) 

```
{
  format: string
  minimalPrice:
  price:
  startingPrice:
}
```

Takich podobieństw jest więcej. Pytam, bo jsony zwracane z API są u nas mapowane na obiekty C++ i niepotrzebne nadmiarowe typy tylko komplikują sprawę :).

**Comment by PawelTaberski** [comment]
W tym wypadku tak, te obiekty niczym się nie różnią, zleciłem ujednolicenie. Jednakże nie zawsze możemy to ujednolicić ze względu na logikę działania systemu. W tym konkretnym przypadku jak najbardziej jest to możliwe i tak jak mówiłem zleciłem ujednolicenie.
Jeśli jeszcze gdzieś zauważysz takie sytuacje to jak najbardziej zbadamy to i damy znać, czy możemy to ujednolicić.
