### ISSUE TITLE
Dodawanie załącznika PDF przez API

### ISSUE THREAD

**Issue by adi5497** [allegro/allegro-api#152]
Czy jest lub będzie możliwość dołączania przez API załączników PDF do ofert nowych lub istniejących?

**Comment by adi5497** [comment]
Widzę że opcja dodawania załącznika jest dostępna przy wystawianiu aukcji przez Allegro. Czy opcja ta jest już udostępniona przez API?

**Comment by MaciejPotepa** [comment]
@adi5497 Na ten moment załączniki jeszcze nie są dostępne w API. Mamy plan, aby je dodać w przyszłości. 
O zmianach będziemy informować z odpowiednim wyprzedzeniem.

**Comment by adi5497** [comment]
@MaciejPotepa Proszę o informację czy została wprowadzona już może obsługa załączników przez API?

**Comment by MaciejPotepa** [comment]
@adi5497 Jeszcze nie. Tak jak pisałem w poprzednim poście. O zmianach będziemy informować z odpowiednim wyprzedzeniem

**Comment by frasiek** [comment]
Czy ten temat jest zamknięty bo się już da, czy nie będzie się dało?

**Comment by PawelTaberski** [comment]
Przez REST API można już jak najbardziej dodawać załączniki. Więcej na ten temat znajdziesz[ tutaj.](https://developer.allegro.pl/news/2018-09-24-Tagi-zalaczniki/)
