### ISSUE TITLE
[Rest Api] Edycja cennika dostaw

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#1520]
Czy jest możliwość usunięcia wybranego cennika dostawy bo w dokumentacji nie znalazłem?

I mała sugestia czy nie warto dodać jakiegoś zabezpieczenia, żeby nie było możliwości dodania cennika z istniejącą nazwą.

Zmiany w cenniku dostaw się zapisują, znalazłem błąd u siebie.

**Comment by PawelTaberski** [comment]
Nie ma możliwości usunięcie cenniku, bo m.in. nie mogę zostać oferty bez żadnego sposobu dostawy. 
A odnośnie id to nie bardzo rozumiem w metodzie PUT musi być w adresie id cennika jaki chcesz zmienić. W POST nie musisz podawać w adresie id cennika, ale wtedy oczywiście utworzysz nowy cennik.

**Comment by Cupik83** [comment]
Ok dziękuje za odpowiedź, a co do PUT to już sobie poradziłem.
