### ISSUE TITLE
Obowiązakowe wydawnictwo w książkach

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#1521]
:bulb: **Sugestia**

PODAWANIE WYDAWNICTWA W POLU SELECT OPTION JEST NONSENSOWNE:
Jak ktoś chce to niech się męczy ale efekt tej polityki jest taki że np przy wyborze wydawnictwa najlepiej wskazać "inne" bo znaleźć właściwe to bardzo dużo czasu schodzi. Poza tym brakuje masę wydawnictw: np "Nowa Matura", GWO które ma dziś książki w każdej księgarni podręcznikowej (innych księgarni prawie nie ma). Rozwiązanie alfabetyczne nie jest prawidłowe bo np PWN jest grupą wydawnictw i może mieć różne nazwy i na przestrzeni dziejów miało także różne nazwy oto przykłady,Wydawnictwo szkolne PWN ,PWN DEMART, wydawnictwo PWN, Państwowe Wydawnictwo Naukowe, PWN NOWA ERA itd. Na dodatek niektóre z podanych przez Was wydawnictw są podawane skrótami a niektóre pełnymi nazwami a niektóre jeszcze z przedrostkiem Wydawnictwo więc szukaj wiatru w polu. Szukanie jest nieprzyjemne i baaardzo długo trwa. Może by chociaż jakiś podpowiadacz zrobić.....

**Comment by PawelTaberski** [comment]
Rozumiem, braki i wszelkie niejasności w parametrach dany sprzedawca powinien zgłosić swojemu opiekunowi, bądź przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Taka sprawa zostanie rozpatrzona, czy należy dodać taką wartość, bądź może jakąś należy wyedytować.
Odnośnie podpowiadaczki w jaki sposób widziałbyś takie rozwiązanie?

**Comment by marcinja2** [comment]
Zadje się że macie bazę książek EAN (lub isbn -tam gdzie są) dlaczego nie miały by się pola tytuł i autor wydawnictwo rok wydania nie miały wypełniać automatycznie (tak jak na froncie a przecież do tego dążycie). Dla osób takich jak ja że mają zdefiniowane swoje nazwy wydawnictwa we własnej bazie to jest poważny problem bo muszę kazać pracownikom wybierać wydawnictwa w mojej i Waszej bazie. Mam 50tyś szablonów książek ze zdefiniowanym wydawnictwem wg mojej listy. Obligatoryjność waszego parametru wydawnictwo powoduje kłopoty bo są inne. Mam siedzieć i zmieniać? Do tego dochodzą problemy które opisałem powyżej. Pole typu text było by rozwiązaniem lepszym z mojego punktu widzenia choć z Waszego niekoniecznie (z racji możliwości wyszukiwarki po wydawnictwach). Nie wiem jest Was wielu myślcie jak temat można ugryźć. Częściowym rozwiązaniem było by jak już pisałem autouzupełnianie na podstawie ean lub udostępnienie zasobu numerów i danych na podstawie EAN

**Comment by PawelTaberski** [comment]
Taki zasób już jak najbardziej jest:
/sale/products?ean={numerEAN}
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/productization/#search_details).

**Comment by marcinja2** [comment]
ok a jak jest w wykorzystaniem zdjęć tego zasobu i prawami autorskimi? jak szybko są aktualizowane zasoby np nowości wydawnicze?

**Comment by PawelTaberski** [comment]
Zgodnie z informacją w [FAQ](https://developer.allegro.pl/productization/#faq):
**Czy mogę wykorzystać zdjęcia z danych o produkcie w ofercie?**
Nie - wynika to z praw autorskich do zdjęć w naszej bazie danych. Zdjęcia mają charakter poglądowy - mają pomóc sprzedawcy upewnić się, że wskazuje odpowiedni produkt w ofercie.

Co do szybkości staramy się na bieżąco rozbudowywać bazę produktów. Jeśli zauważysz jakiś brak w kategoriach w których ta funkcjonalność jest dostępna, to zgłoś proszę taką informację przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
