### ISSUE TITLE
sellFormId w zasobie GET /sale/categories/{categoryId}/parameters

### ISSUE THREAD

**Issue by grola** [allegro/allegro-api#1522]
Zgłaszam zapotrzebowanie aby zasób `GET` `/sale/categories/{categoryId}/parameters` zwracał wartość `sellFormId` tak jak `doGetSellFormFieldsForCategory` zwraca zarówno `sellFormId` jak i `sellFormParamId`. Dziękuję za pozytywne rozpatrzenie zapotrzebowania :)

**Comment by PawelTaberski** [comment]
Powiedz mi tylko jeszcze do czego potrzebne są Tobie takie dane i w jaki sposób będziesz z nich korzystał? Jak to ułatwi Tobie działanie.

**Comment by grola** [comment]
W aplikacji (wtyczce) podstawowym identyfikatorem dla pól jest `sellFormId`. Np. używamy go do mapowania atrybutów produktów w sklepie na pola aukcji. Bez konwersji nie zrobimy przejścia na rest api. A konwersja będzie kłopotliwa.

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze Ciebie rozumiem, powiedz mi czy dobrze myślę. Chciałbyś aby w REST API w zasobie /sale/categories/{categoryId}/parameters było przy danym parametrze dodatkowe pole sellFormId, które zwracałoby numer fid-a w WebAPI tak?

**Comment by grola** [comment]
Tak.

**Comment by PawelTaberski** [comment]
Rozumiem przekażę taką sugestię, jeśli zdecydujemy się wdrożyć takie rozwiązanie to poinformujemy o tym  w dedykowanym komunikacie

**Comment by grola** [comment]
Dzięki. Kiedy można spodziewać się decyzji?

**Comment by FromAnyHole** [comment]
@grola - hejka, obstawiam jednak, że się nie doczekasz, bo wyłączą wszystko wcześniej...

**Comment by Onixarts** [comment]
FIDy były stworzone na potrzeby identyfikatorów pola w formularzu wystawiania aukcji. Potem wprowadzono identyfikatory parametrów i wątpi aby w nowym API komuś chciało się utrzymywać nic nieznaczący już identyfikator pola.

My u nas również po FIDach rozróżniamy parametry, a wraz z nowym API trzeba to zmienić a nie odtwarzać zbędne byty. Weź potem wytłumacz komuś po co w tej strukturze jest FID i czym się różni od identyfikatora parametru.

**Comment by PawelTaberski** [comment]
Sugestię przekazałem, kiedy otrzymam jakąś informacje nie jestem w stanie powiedzieć. Tak jak pisałem jeśli zdecydowalibyśmy się na takie wdrożenie na pewno o tym poinformujemy.

**Comment by mareklemur** [comment]
Też mam ten problem. W aplikacji parametry są zapisane po sellFormId. Teraz żeby wystawić aukcję w RESTAPI trzeba podać id parametru, którego nie ma. W jaki sposób można to obejść?

**Comment by mareklemur** [comment]
Jeszcze jedno pytanie - czy można w webapi przekazać sellFormParamId zamiast sellFormId?

**Comment by mareklemur** [comment]
Tak, wiem, ale w aplikacji mam wszystkie parametry są zapisane dla klucza sellFormId.

**Comment by PawelTaberski** [comment]
Rozumiem, tak jak pisałem przekazałem taką sugestię aby dodać takie pola, dodam w niej, że więcej osób zgłasza taką potrzebę. Jeśli otrzymam informację, że zdecydujemy się wprowadzić taką zmianę, to oczywiście poinformujemy o tym w dedykowanym komunikacie.

**Comment by Kite4FunPL** [comment]
Witam. Chciałbym odświeżyć wątek - z integracją do REST nieco się spóźniliśmy i jesteśmy w trakcie nadrabiania. Natknąłem się właśnie na ten sam problem, jednak jest już po 03.06.2019, zatem metody webApi zostały wyłączone. Cała nasza baza danych zbudowana pod webApi opiera się na sellFormId zamiast na sellFormParamId.

Obecnie webApi jest już wyłączone i nie mamy możliwości w żaden sposób "przetłumaczyć" sellFormId na sellFormParamId. Bardzo, ale to bardzo potrzebujemy sposobu na przetłumaczenie sellFormId na CategoryParameter.id (lub jak kto woli sellFormParamId). Może to być w formie dodatkowego zasobu w REST, który służy do tego tłumaczenia, albo udostępnienie w webApi jakiejś metody która nam to umożliwi. Na chwilę obecną jesteśmy w kropce, przecież nie będziemy tego robili ręcznie.

**Comment by PawelTaberski** [comment]
@Kite4FunPL Looknij tutaj #1786 właśnie przygotowaliśmy takie gotowe mapowanie.

**Comment by Kite4FunPL** [comment]
@PawelTaberski Super, dziękuję! Problem solved :)
