### ISSUE TITLE
Aktywacja konta na sandboxie

### ISSUE THREAD

**Issue by patrykb15580** [allegro/allegro-api#1523]
Proszę o aktywacje konta na sandboxie: sandbox.allegro@gmail.com

**Comment by PawelTaberski** [comment]
Aktywowałem Twoje konto.

**Comment by patrykb15580** [comment]
Dziękuję :)

**Comment by axzx** [comment]
@PawelTaberski a czy jest inny sposób aktywowania konta czy każdy musi napisać issue na githubie?;)
Jest napisane, że do 3 dni powinno być aktywowane, ale czy faktycznie tak jest?

**Comment by PawelTaberski** [comment]
@axzx  Mamy z tym flow problem przez co wielokrotnie kończy się to na ręcznej aktywacji, jednakże już dedykowany zespół pracuje nad tym. Mam nadzieję, że niedługo da się w pełni zautomatyzować te flow i ograniczyć do minimum potrzebę ręcznego klepnięcia.

**Comment by axzx** [comment]
@PawelTaberski dzięki za info, ale nadal nie wiem czy mam czekać (i jak długo) czy jednak gdzieś trzeba napisać, żeby aktywować;)
tutaj na github chyba nie ma prywatnych wiadomości

**Comment by PawelTaberski** [comment]
To się nie zrozumieliśmy :-) myślałem że pytasz o sam proces. Podeślij proszę login i postaram się go aktywować. Jeśli chcesz możesz go podesłać przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu zaznacz, że dane dotyczą zgłoszenia numer 1523 na GitHub-ie.
