### ISSUE TITLE
[Rest Api] Lista tagów

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#1525]
Na koncie na Sandbox-ie po próbie wejścia na listę tagów dostaję informacje:
Numer błędu: 8e20bf9192b4cd45

Przez Rest Api tag niby się dodaje bo dostaję id nowo utworzonego tagu ale lista tagów nic nie zwraca.

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem z tagami na sandboxie. Sprawę zgłosiłem do odpowiedniego zespołu. prośba o cierpliwość.

**Comment by Cupik83** [comment]
Czy już wiadomo coś w tym temacie?

**Comment by PawelTaberski** [comment]
Widzę, że zespół pracuje już nad tym zadaniem. Jednakże jeszcze nie wiadomo ile to dokładnie zajmie. Proszę o cierpliwość.

**Comment by Cupik83** [comment]
Kiedy będzie informacja o rozwiązaniu problemów bo to już dużo czasu upłynęło a dalej ta funkcjonalność nie działa ?

**Comment by MartaNowaczyk** [comment]
Na rozwiązanie będzie trzeba poczekać z racji priorytetów czeka w kolejce.

**Comment by MartaNowaczyk** [comment]
@Cupik83 problem nie powinien już występować
