### ISSUE TITLE
Aukcje widmo

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#1526]
Witam,
nie do końca wiem jak opisać nasz problem ale czy możliwym jest że przez przeprowadzaną teraz migrację z szablonów na szkice posiadamy aukcji widmo które możemy po ID oferty pobrać z `sale/offers/` ale interfejs graficzny Allegro dla takiego identyfikatora zwraca `Brak wyników`. 

Próbowałem wyszukać tę aukcję po ID, tytule, sygnaturze etc. jednak wynik jest zawsze ten sam, według API Allegro taka aukcja istniała a według interfejsu klient nigdy nie miał wystawionej takiej aukcji.

Przykładowy ID: 7896584414

EDIT:
Nie jest to z pewnością kwestia przeniesienia do archiwum gdyż aukcja pochodzi z marca 2019, jednak podejrzewam że problemem może być fakt że pierwotnie została ona wystawiona z szablonu w menadżerze sprzedaży.

**Comment by rtnet-pl** [comment]
Ten zasób zwraca też szkice (drafty) ofert, jeśli kiedyś zacząłeś tworzyć ofertę ale jej nie wystawiłeś, to będzie widoczna w tym zasobie.

**Comment by Uriziel01** [comment]
Ale ta aukcja się odbyła i zakończyła bez kupujących, jednak gdy w panelu administracyjnym allegro próbuje wyszukać po dowolnym jej parametrze to ona wg. Allegro nigdy nie istniała na koncie klienta :D

**Comment by PawelTaberski** [comment]
@Uriziel01 Sprawdziłem i u danego usera w zakładce moje oferty jest widoczna ta oferta, a pamiętałeś aby przełączyć na licytacje bo to nie było kup teraz.

**Comment by Uriziel01** [comment]
Hmmm, no nie wiem jak powiedzieć coś więcej na temat tego problemu. Klient zgłasza że nie może wyszukać kilku aukcji i po zalogowaniu się na jego konto potwierdzam taki problem.

![image](https://user-images.githubusercontent.com/568207/56417193-6ffbd380-6293-11e9-9286-94c3f5eaaa53.png)

**Comment by PawelTaberski** [comment]
Ciekawe przed sekundą sprawdzałem i oferta była ale szukałem po tytule a teraz rzeczywiście jej brak :-)
Sprawę zgłosiłem do zespołu, który odpowiada za tę funkcjonalność prośba o cierpliwość.

**Comment by PawelTaberski** [comment]
@Uriziel01 Dostałem informację, że user ukrył tą ofertę dlatego nie jest widoczna w tej zakładce.
