### ISSUE TITLE
Procesowanie zamówień - brak danych nabywcy

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1527]
:bulb: **Sugestia**

Cześć
Scenariusz który potrzeba obsłużyć w restAPI
Metoda: GET /order/checkout-forms 

1. Sprzedawca wystawia zawsze faktury Klientom, niezależnie czy Klient na Allegro chce fakturę czy nie, bo korzysta ze zwolnienia z wystawiania paragonów (Dz.U. rok 2017 poz. 2454)
2. Klient  na Allegro kupuje u tego sprzedawcy i nie zaznacza "faktury", zamówienie ma status READY_FOR_PROCESSING
3. w JSON brak jest sekcji INVOICE bo Klient nie wybrał faktury, są tylko dane do wysyłki - to jest zrozumiałe
4. Prośba by w sekcji {Buyer} pojawiły się imię i nazwisko/nazwa oraz dane teleadresowe Klienta
5.W takim przypadku brak tych danych powoduje że nie da się wystawić faktury dla Klienta, a wystawienie jej na dane dostawy jest niepoprawne.  Fakturę wystawia się na osobę która nabyła towary a nie na dane do wysyłki. A dane do wysyłki mogą się różnić od danych nabywcy

@PawelTaberski @MartaNowaczyk

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wdrożyć taką zmianę to poinformujemy o tym w dedykowanym komunikacie.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski , to jest potrzebne przed usunięciem starych metod webAPI. 
Obecnie NIE da się procesować zamówień w przypadku korzystania z ww zwolnienia. Taki sprzedawca będzie działać niezgodnie z prawem, a przeciez nie będzie ręcznie przepisywał tych faktur.

**Comment by PawelTaberski** [comment]
Rozumiem sprawę przekazałem jak tylko otrzymam jakieś informacje bądź dodatkowe pytania to oczywiście dam znać.

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Mały update właśnie rozmawiałem w sprawie tej zmiany i już sprawa jest w toku i w najbliższym czasie będziemy zwracali adres z ustawień konta w statusie BOUGHT. Jak tylko będę miał dokładne dane kiedy wdrożymy taką zmianę to poinformujemy o tym w dedykowanym komunikacie.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski dzięki, natomiast dla upewnienia się te dane bedą kompletne:  imie, nazwisko, ewentualnie nazwa, adres bo tylko komplet pozwoli na wystawienie faktury. 
I także dla READY_FOR_PROCESSING?

**Comment by PawelTaberski** [comment]
Z tego co się dowiedziałem będzie rozbudowana cała sekcja buyer i będzie ona zwracana w rozbudowanej formie we wszystkich statusach łącznie z READY_FOR_PROCESSING. I dane o które pytasz mają się w niej znaleźć.
