### ISSUE TITLE
Zmiana duration na null (do wyczerpania zapasów)

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1528]
Witam,
Mam problem ze zmianą czasu trwania oferty. Podczas wysyłania:
{
    "modification": {
    "publication": {
        "duration": null
    }
},
    "offerCriteria":[
    {
        "type":"CONTAINS_OFFERS",
        "offers":[
        {
        "id":"7949924503"
        }
        ]
    }
    ]
}

zwrotnie dostaje:
          'errors' => [
                        {
                          'userMessage' => 'may not be null',
                          'path' => 'publication',
                          'details' => 'Invalid value: null',
                          'message' => 'may not be null',
                          'code' => 'VALIDATION_ERROR'
                        }
                      ]
        };

W jaki sposób mogę to wykonać ?

**Comment by rtnet-pl** [comment]
Robisz prawidłowo ,pewnie chodzi o to że po 12 godzinach lub po pierwszym zakupie nie możesz zmienić tego pola

**Comment by PawelTaberski** [comment]
@AleksyZajac Dokładne informacje co i kiedy możesz zmienić znajdziesz w [naszej pomocy](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz).
