### ISSUE TITLE
sale/delivery-methods a panel allegro

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1529]
:bulb: **Sugestia**

W/w zasób nie zwraca kompletnych danych, które potrzebne są do odwzorowania działania kreatora cenników tak jak to wygląda w panelu Allegro.
Konkretnie chodzi o:
* nie każda metoda dostawy pozwala na zdefiniowanie ceny za kolejną sztukę
* nie każda metoda dostawy pozwala na zdefiniowanie czasu dostawy od-do

dane zwracane z api podają tylko id, nazwę metody oraz możliwe sposoby płatności (z góry, za pobraniem).
Jak teraz mam odwzorować kreator w aplikacji zewnętrznej skoro nie ma pełnych informacji? Jedyne wyjście obecnie to ręczne mapowanie istniejących metody dostawy (100!), która co może mieć zdefiniowane tak aby klient przez api nie mógł wysłać niepoprawnych requestów.

**Comment by PawelTaberski** [comment]
Rozumiem, i jak najbardziej sugestię przekażę powiedz mi tylko w jaki sposób chciałbyś otrzymać takie informacje, aby były dla Ciebie najwygodniejsze?

**Comment by j4r3kb** [comment]
Obecnie wygląda to tak:

```
[
  {
    "id": "758fcd59-fbfa-4453-ae07-4800d72c2ca5",
    "name": "List polecony priorytetowy",
    "paymentPolicy": "IN_ADVANCE"
  }
]
```

mogło by być tak:
```
[
  {
    "id": "758fcd59-fbfa-4453-ae07-4800d72c2ca5",
    "name": "List polecony priorytetowy",
    "paymentPolicy": "IN_ADVANCE",
    "canSetNextItemPrice": true/false,
    "canSetCustomDeliveryTime": true/false
  }
]
```

**Comment by PawelTaberski** [comment]
Dzięki za doprecyzowanie oczywiście sugestię przekazałem. Jeśli otrzymam informacje, że wdrożymy taką zmianę, to poinformujemy o tym w dedykowanym komunikacie.

**Comment by j4r3kb** [comment]
Dodatkowo dana metoda transportu może mieć maksymalny koszt określony - w panelu Allegro to jest pokazywane np. Allegro Kurier24 13.41 - i takiej informacji brakuje w response z API. Będzie to powodowało wysyłanie błędnych kwot i zwrotki błędu z API.

**Comment by MartaNowaczyk** [comment]
Rozumiem, przekazałam twoje spostrzeżenia do odpowiedniego zespołu.
