### ISSUE TITLE
Długośc nowego opisu FID 341

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#153]
Witam,
Jaki jest limit na długość nowego opisu oferty?
Czy sa  jeszcze jakieś ograniczenia?
W dokumentacji jest wzmianka, że może być max 100 sekcj, czy coś jeszcze?

KF

**Comment by MaciejPotepa** [comment]
Nowy opis nie może ważyć więcej niż 40kb. Ilość znaków bywa zmienna, m.in. z uwagi na to, że treść opisu możesz podzielić pomiędzy różnymi sekcjami. Wspomniana waga dot. zarówno treści opisu, jak i znaczników wykorzystywanych w ramach opisu.
