### ISSUE TITLE
Modyfikacja skryptu php. Metoda change-price-commands -> offer-price-change-commands

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#1530]
Witam.
Mam prośbę, nie koniecznie do pracowników allegro ale chyba jest to obecnie forum dotyczące REST API więc pozwolę sobie poprosić o pomoc. Mam skrypt napisany według starej metody change-price-commands , skrypt działa ale jako, że jest nowsza metoda chciałbym go zmodyfikować do offer-price-change-commands. Niestety moje wiedza jest zbyt ograniczona. Skrypty wykorzystuję dla siebie. Mam też inne skrypty jeszcze na WebApi dlatego ten przykład posłużyłby mi również do innych zmian. Skrypt zmienia ceny na podstawie pliku ceny.csv, w pliku jest tylko nr aukcji i nowa cena. Zmiany dokonuję maksymalnie w kilkunastu aukcjach na raz więc super wydajność nie jest tu wymagana. Z góry bardzo dziękuję, za pomoc.

`

    function commandRequest($uri, $generatedKey, array $params = []) {
    $headers = [
      'Accept: application/vnd.allegro.public.v1+json',
      'Content-Type: application/vnd.allegro.public.v1+json',
      'Authorization: Bearer '.file_get_contents('./.verkey1', FILE_USE_INCLUDE_PATH).'',
      'Api-Key: xxx'
    ];
    

    $curl = curl_init($uri);
 
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
 
    $data = json_encode($params);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);    
 
    return curl_exec($curl);
  }

$plik1 = file_get_contents('./.verkey1', FILE_USE_INCLUDE_PATH);

include 'uid.php';
$v5uuid = UUID::v5('1546058f-5a25-4334-85ae-e68f2a44bbaf', 'SomeRandomString');  //generuje GUID jednorazowy kod do komunikacji wymagany w REST

$filename = "ceny.csv";

$plik = file($filename);
for( $i=1  ;  $i<count($plik)  ;  $i++){
    $wiersz = explode(",",chop($plik[$i]));
     $itemId = str_replace('"', '', $wiersz[0]);
	$cena = str_replace('"', '', $wiersz[1]);
echo "<br>Nr aukcji $itemId ";
echo "<br>Cena $cena";

  
  $data = array (
    'input' => [
      'buyNowPrice' => [
        'amount' => $cena,
        'currency' => 'PLN'
      ]
    ]
  );
  
  commandRequest('https://api.allegro.pl/offers/' . $itemId . '/change-price-commands/' . $v5uuid, $generatedKey, $data);

}
`

**Comment by martacronic** [comment]
Moim skromnym zdaniem metoda, której używasz jest idealna dla Twoich potrzeb, bo rozumiem, że chcesz zmieniać ceny pojedynczo zgodnie z danymi w pliku csv. Metoda, o którą pytasz pozwala jednorazowo zmienić więcej niż jedną aukcję. To, że jest nowsza, znaczy tylko tyle, że jest później napisana, ale służy do zmiany cen trochę pod innym kątem niż ty potrzebujesz. Spokojnie możesz korzystać z dotychczasowego rozwiązania. (Odpowiadam na podstawie dokumentacji, więc jeśli się mylę, to niech ktoś mnie poprawi)

**Comment by kris86k** [comment]
Rozumiem. Właściwie tutaj nie ma problemu jeśli nie ma planów wycofania tej metody. 
Problem jest gdzie indziej. Ponieważ mam skrypt działający na podobnej zasadzie ale zmieniający ilość, napisany jeszcze w WebApi, które w czerwcu ma być wycofane i dlatego chciałem zmodyfikować ten skrypt aby posłużył mi jako przykład do "offer-quantity-change-commands". Niestety do zmiany ilości nie ma prostego sposobu w REST. Jak to ogarnąć?

**Comment by martacronic** [comment]
W [dokumentacji](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT) jest metoda do zmiany ilości. A [tutaj](https://developer.allegro.pl/my_offers/#3g) poradnik

**Comment by kris86k** [comment]
Znam, czytałem, próbowałem ale niestety jest to dla mnie zbyt trudne. Robię to tylko na własne potrzeby, nie zajmuję się programowaniem.
Próbowałem zmodyfikować skrypt zmiany ceny ale to niestety nie działa:

`  
$filename = "ilosc.csv";

$plik = file($filename);
for( $i=1  ;  $i<count($plik)  ;  $i++){
    $wiersz = explode(",",chop($plik[$i]));
     $itemId = str_replace('"', '', $wiersz[0]);
	$ilosc = str_replace('"', '', $wiersz[1]);

  $data = array (
    'input' => [
      'modification' => [
	'changeType' => 'FIXED',
        'value' => $ilosc
      ]
    ]
  );
  
  commandRequest('https://api.allegro.pl/offers/' . $itemId . '/offer-quantity-change-commands/' . $v5uuid, $generatedKey, $data);

}

`
