### ISSUE TITLE
[BUG] - Parametry kat. 110290 - definicje wartości

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1531]
Kod oznaczenia ochronnego:
sellFormOptsValues: 1|2|4|8|16|32|64|128|256|512|1024|2048
sellFormParamValues: 1|2|4|8|16|32|64|128|256|512|1024|8192

**Comment by PawelTaberski** [comment]
Powiedz mi proszę o jaki numer fid masz na myśli? Jeśli chodzi Tobie o same wartości to przy wystawianiu ofert mają znaczenie wartości z Pola sellFormOptsValues. [Zgodnie z dokumentacją](https://allegro.pl/webapi/documentation.php/show/id,782#method-output):
sellFormOptsValues | string
Wskazanie konkretnych wartości (odpowiednich dla opisów wyżej), które można ustawić dla danego pola (dot. pól typu combobox/radiobutton/checkbox, dla pól typu checkbox kolejne wartości można sumować).
Natomiast wartości z pola sellFormParamValues są już niewykorzystywane.

**Comment by FromAnyHole** [comment]
@PawelTaberski - a co według Pana oznacza 'sellFormParamValues' ?? Czy nie jest to skrót od "Wartości Parametru Formularza sprzedaży" ? Od zawsze się to zgadzało, no i nagle przestało - od kiedy niby ??

**Comment by FromAnyHole** [comment]
@PawelTaberski - w dokumentacji nie ma nawet słowa, że coś tu jest "niewykorzystywane"...

**Comment by PawelTaberski** [comment]
Zgodnie z dokumentacją:
sellFormParamValues | string
Unikalne i niezmienne identyfikatory wartości parametru (dot. pól typu combobox/radiobutton/checkbox).
Może źle się wyraziłem nie są one wykorzystywane ani potrzebne do wystawienia/edycji oferty.
