### ISSUE TITLE
[BUG] - Parametry kat. 89517 - żadnych definicji ??

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1532]
Rozmiar:
obowiązkowy - i kompletnie nie wiadomo czego tam oczekujecie...
sellFormOptsValues: ??
sellFormParamValues: ??

**Comment by PawelTaberski** [comment]
Dokładnie tak jak odpowiedziałem Tobie w poprzednim wątku:
Powiedz mi proszę o jaki numer fid masz na myśli? Jeśli chodzi Tobie o same wartości to przy wystawianiu ofert mają znaczenie wartości z Pola sellFormOptsValues. Zgodnie z dokumentacją:
sellFormOptsValues | string
Wskazanie konkretnych wartości (odpowiednich dla opisów wyżej), które można ustawić dla danego pola (dot. pól typu combobox/radiobutton/checkbox, dla pól typu checkbox kolejne wartości można sumować).
Natomiast wartości z pola sellFormParamValues są już niewykorzystywane.
Nie zakładaj proszę z bardzo podobnymi pytaniami kilku wątków.

**Comment by FromAnyHole** [comment]
@PawelTaberski - to jest ewidentny BUG, jest inny niż z wcześniejszego wątku, no i tutaj ma on swoje miejsce - proszę mnie nie pouczać co gdzie mogę zamieszczać, a tym bardziej nie grozić mi tu co chwila blokadami. Podałem wystarczającą ilość informacji: numer kategorii docelowej (89517), unikalną nazwę parametru (Rozmiar) dla tej kategorii, no i odwalam za Was kawałek roboty - zgłaszając kolejny błąd. Czy tak powinna odpowiadać metoda 'doShowItemInfoExt' dla obowiązkowego parametru zakresowego ? Oto adekwatny kawałek zwracany po zapytaniu na sesji sprzedającego (ItemID: 6120540225):
`...<ns1:item><ns1:attribName>Rodzaj</ns1:attribName><ns1:attribValues><ns1:item>pozostałe</ns1:item></ns1:attribValues></ns1:item><ns1:item><ns1:attribName>Rozmiar</ns1:attribName><ns1:attribValues/></ns1:item></ns1:itemAttribList>`

**Comment by PawelTaberski** [comment]
Sprawdziłem i parametr jest parametrem zakresowym jest prawidłowo opisany w metodzie DoGetSellFormFieldsForCategory. Jednakże rzeczywiście brak dla niego wartości w metodzie DoShowItemInfoExt sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by FromAnyHole** [comment]
Ok, ale wspomniana przez Pana powyżej metoda komunikuje tylko w taki sposób, sugerując wysyłkę jednej wartości typu 'int' o szerokości pola 3 znaków, no i to kończy się potem błędem edycji:
`<ns1:item><ns1:sellFormId>37929</ns1:sellFormId><ns1:sellFormTitle>Rozmiar</ns1:sellFormTitle><ns1:sellFormCat>89517</ns1:sellFormCat><ns1:sellFormType>2</ns1:sellFormType><ns1:sellFormResType>2</ns1:sellFormResType><ns1:sellFormDefValue>0</ns1:sellFormDefValue><ns1:sellFormOpt>1</ns1:sellFormOpt><ns1:sellFormPos>2</ns1:sellFormPos><ns1:sellFormLength>3</ns1:sellFormLength><ns1:sellMinValue>0.00</ns1:sellMinValue><ns1:sellMaxValue>200.00</ns1:sellMaxValue><ns1:sellFormDesc></ns1:sellFormDesc><ns1:sellFormOptsValues></ns1:sellFormOptsValues><ns1:sellFormFieldDesc>Dziecko&gt; Nakrycia głowy</ns1:sellFormFieldDesc><ns1:sellFormParamId>212878</ns1:sellFormParamId><ns1:sellFormParamValues></ns1:sellFormParamValues><ns1:sellFormParentId>0</ns1:sellFormParentId><ns1:sellFormParentValue>0</ns1:sellFormParentValue><ns1:sellFormUnit>cm</ns1:sellFormUnit><ns1:sellFormOptions>8</ns1:sellFormOptions></ns1:item>`

**Comment by PawelTaberski** [comment]
Wartość w polu sellFormOptions jednoznacznie wskazuje na parametr zakresowy. Zgodnie z dokumentacją:

sellFormOptions | int
Dodatkowe własności parametru: 1 - parametr zależny; 2 - parametr typu checkbox z wykorzystaniem operatora OR (z możliwym wyborem jednej lub wielu wartości), w przypadku gdy ta wartość nie jest ustawiona działanie parametru opiera się na operatorze AND; 6 - parametr typu checkbox z możliwym wyborem pojedynczej wartości (w praktyce combobox); **8 - parametr zakresowy**.

**Comment by FromAnyHole** [comment]
Jest jednak tak, że nie znamy w ogóle wartości zakresowych tego parametru, bo w konkretnym przypadku (6120540225) albo nawet każdym innym (7874180286) z tej kategorii - zwracane jest wielkie NIC ! Wracam więc do początku tego wątku - co powinno być wysłane przy edycji oferty i w jakim zapisie ? Dwie wartości typu 'int' z zakresu '0.00-200.00' (tu inna szerokość pola 'float') w zapisie tablicowym ?

**Comment by FromAnyHole** [comment]
To tak dla innych wrzucę, bo tego nie ma w dokumentacji:
====================================
fvalueRangeFloat | RangeFloatValueStruct
fvalueRangeFloatMin | float
fvalueRangeFloatMax | float
====================================
fvalueRangeInt | RangeIntValueStruct
fvalueRangeIntMin | int
fvalueRangeIntMax | int
====================================
