### ISSUE TITLE
[REST]: GET /offers/listing?searchMode=REGULAR - brak odwzorowania FRONTU

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1533]
Nie odwzorowujecie w tym zasobie wszystkich informacji - jakie zwraca wyszukiwarka "na froncie", czyli danych dotyczących istnienia i dostępności innych wariantów. Dane listingu niosą informacje o grupie wariantowej, a rzeczony zasób już NIE - więc naprawcie to zwyczajnie !
p.s.
Przestańcie ogłaszać kolejne terminy wygaszania WebAPI po kawałku !
Wszystko musi najpierw działać bez zarzutu, potem rok na adaptacje !!

**Comment by PawelTaberski** [comment]
Rozumiem brak wariantów zgłaszałem już jako sugestię do odpowiedniego zespołu, oczywiście poinformuje ich, że większość osób oczekuje takich informacji.
