### ISSUE TITLE
[Praca i pieniądze] - Przestańcie tak traktować ludzi - STOP wygaszaniu API !!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1534]
Pytanie na święta - dla kogo Wy to wszystko tam niby robicie ??
Czy Wy macie w ogóle świadomość, że ludzie nie mają PENSJI jak Wy ??
Ile osób u Was pracuje przy wszystkich projektach, jakieś 80 ludzi na etatach ??
Czy uważacie, że Wasze "plany rozwojowe" i narzucane terminy łykniemy z marszu ??
--
Koniec pitolenia, że się nie da... Najpierw ma wszystko działać jak należy, potem można wyłączać starsze rozwiązania. Przełóżcie te absurdalne terminy na czas po wakacjach, albo będzie ciekawie !

**Comment by PawelTaberski** [comment]
To jest forum jak najbardziej masz prawo do swojego zdania, ale proszę nie dodawaj niepotrzebnych informacji do wielu wątków. Inaczej będziemy musieli Ciebie zablokować.

**Comment by TimothyKoval** [comment]
@FromAnyHole Trochę się pomyliłeś kolego z tymi 80 etatami :)

**Comment by FromAnyHole** [comment]
@TimothyKoval - jeśli masz konkretne dane, to się pochwal, ale nie chodzi tu oczywiście o cały stan zatrudnienia - tylko o zespoły powiązane w taki czy inny sposób z całym zamieszaniem wokół API.

**Comment by SebastianOzdoba** [comment]
@TimothyKoval  widze, że kolega nie wytrzymał :)
Dyplomatycznie powiem że też mamy sporo zastrzeżeń do restAPI i czekamy na wprowadzenie zgłoszonych tutaj sugestii. Cóż jednak zrobić realizujemy przejście na restAPI i wydamy wersję w 3.cim tygodniu maja z tym co będzie, by Klienci się zaczęli migrować
Mam jednak nadzieję i tutaj apeluję do @PawelTaberski  @MartaNowaczyk  by rozważyć na poważnie przesunięcie wygaszenia i podać tą informację jak najszybciej a nie dzień przed. Wiem też,  że @PawelTaberski @MartaNowaczyk mają na tym forum niewdzięczną rolę :)
Ułatwi to pewnie wszystkim planowanie prac 

Wesołych Świąt :)

**Comment by yncki** [comment]
@SebastianOzdoba true. Ciężka rola @PawelTaberski i @MartaNowaczyk , ale to da się wyprostować żeby wszyscy byli happy. Smacznego jaja.

**Comment by FromAnyHole** [comment]
@yncki - bo trudno jest teraz bronić blisko dwóch lat kłamstw na temat WebAPI, które miało przecież pozostawać podstawowym interfejsem obsługowym. Dopiero w zeszłym roku (i to tuż przed wakacjami) oznajmiono łaskawie - o całkiem nowych planach rozwojowych i wygaszaniu wszystkiego na wariata...

**Comment by Uriziel01** [comment]
@FromAnyHole pełna zgoda z naszej strony że to nie powinno wyglądać tak że współbieżnie tworzymy nowe API które czeka jeszcze na ogrom poprawek i nie spełnia funkcjonalności starych metod oraz wygaszamy stare API `na wariata` mimo że jasno widać że obecna sytuacja jest niestabilna i nie wszystko działa tak jak działać powinno, wszystko postawione zostało na głowie aby spełnić czyjeś nierzeczywiste postanowienia za wszelką cenę.

Jednocześnie chcielibyśmy zachowania pewnego poziomu kultury w tych dyskusjach, ciężko oczywiście bronic tezy że w Allegro wszystko gra i ich działania są zgodne z tym co było wcześniej komunikowane (nie jest i zdecydowanie wiele kwestii leży) ale ściągnięcie poziomu tej dyskusji w dół niczego tutaj nie poprawi.
