### ISSUE TITLE
Wystawione oferty a dodawanie pozycji w cenniku dostaw?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1535]
Witam,
dokonuje zmian w cenniku dostaw przez stronę WWW, cennik ten jest aktualnie podpięty w 5 000 aukcji. Czy w akcjach zmiany wykonają się same czy może należy coś jeszcze zrobić?

Jeżeli powinny się wykonać same to po jakim czasie będzie to widoczne? Aktualnie miło już 1,5h i zmian nie widzę.

**Comment by PawelTaberski** [comment]
Zmiany w ofertach w których jest podpięty dany cennik powinny się dokonać automatycznie. Upewnij się, czy w danej ofercie cennik nie odpiął się ze względu na jej edycję np. przez WebAPI. 
Jeśli cennik jest podpięty a mimo to dane odnośnie wysyłki się nie zmieniły to podaj proszę nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) id cennika i numer oferty. Sprawdzimy w czym jest problem. Dodatkowo dodaj, że dane potrzebne są do zgłoszenia na GitHub-ie numer 1535.
 Każda zmiana na ofercie może zająć do godziny, także z tego co mówisz już powinny być dawno widoczne.
