### ISSUE TITLE
Przyszłość doGetSiteJournalInfo

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1536]
Jak wygląda przyszłość doGetSiteJournalInfo ze starego webApi i jakie są plany, metoda będzie wygaszana bez odwzorowania w rest, czy docelowo jest w planie restowym ?

**Comment by FromAnyHole** [comment]
@yncki - API nie rozwija się już pod potrzeby użytkowników czy zewnętrznych programistów, będzie tylko inną drogą obsługi sprzedaży i to wyłącznie w taki sposób, aby nie naruszyć tego "świętego interesu"...

**Comment by PawelTaberski** [comment]
@yncki  Wiem, że trwają pracę nad dziennikiem zdarzeń odnośnie zmian w ofertach danego sprzedawcy. Jednakże szczegółowych danych kiedy taka metoda się pojawi, nie jestem w stanie podać. Jak tylko będziemy mieli więcej informacji na ten temat na pewno o tym poinformujemy.

**Comment by yncki** [comment]
@PawelTaberski dzięki, chodzi mi generalnie o to, że nie mamy jeszcze obsługi dziennika zdarzeń, ale widzimy dużą szansę na optymalizację systemu dzięki właśnie dziennikowi. 

Jak rozumiem, będzie w rest odzwierciedlenie tego zasobu więc możemy poświęcić pieniądze na implementację teraz w webapi, a później migrację do rest.
