### ISSUE TITLE
Publikacja oferty

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1537]
Witam, mam juz oferte po poprawnej walidacji, zatrzymalem sie na publikacji oferty

PUT na zasob

`https://api.allegro.pl/sale/offer-publication-commands/{commandId} `

skad mam wziac commandId ?

**Comment by FromAnyHole** [comment]
UUID (ver.4) generujesz sam, zależnie od środowiska znajdziesz w sieci furę generatorów, ja sam napisałem, masz tu poniżej jeden nie użyty do testu - nówka sztuka ;-)
05f03413-719b-4061-9748-879f7fa0d02e

**Comment by mskiba03** [comment]
Cały czas dostaje
ERROR - An error has occurred - /sale/offer-publication-commands/05f03413-719b-4061-9748-879f7fa0d02e

**Comment by j4r3kb** [comment]
Używasz https://packagist.org/packages/ramsey/uuid ?

**Comment by mskiba03** [comment]
Uzywam:

`function gen_uuid() {
    return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        // 32 bits for "time_low"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        // 16 bits for "time_mid"
        mt_rand( 0, 0xffff ),

        // 16 bits for "time_hi_and_version",
        // four most significant bits holds version number 4
        mt_rand( 0, 0x0fff ) | 0x4000,

        // 16 bits, 8 bits for "clk_seq_hi_res",
        // 8 bits for "clk_seq_low",
        // two most significant bits holds zero and one for variant DCE1.1
        mt_rand( 0, 0x3fff ) | 0x8000,

        // 48 bits for "node"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    );
} `

**Comment by j4r3kb** [comment]
Spróbuj tego vendora wyżej.
