### ISSUE TITLE
sale/offer-publication-commands/ zwracane dane

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1538]
:bulb: **Sugestia**

endpoint: https://api.allegro.pl/sale/offer-publication-commands/
używając tej metody można wykonać "ACTIVATE" lub "END". Metoda ma ograniczenie do 1000 ofert.
Używając jej hurtowo np. dla 500 ofert, bez względu na czy aktywuję/kończę ofertę w odpowiedzi dostaję

```
[▼
  "id" => "0cc86022-62a6-11e9-8121-0242ac120007"
  "taskCount" => array:3 [▼
    "total" => 0
    "success" => 0
    "failed" => 0
  ]
```

i co przepraszam mam zrobić z taką informacją? Skąd mam wiedzieć ile (i które dokładnie) z tych 500 ofert zakończono z powodzeniem, których nie udało się zakończyć?
Na prawdę chcecie abym orał po API 500 razy pytając o status pojedynczo?
Jako odbiorca API oczekiwałbym w odpowiedzi otrzymać id ofert zakończonych z powodzeniem i tych których nie udało się zakończyć, aby móc odpowiednio zareagować w swojej aplikacji.

Jestem w stanie sobie wyobrazić, że zamknięcie 1000 ofert nie odbywa się w takim systemie ot tak, tylko możliwe że przez kolejkę i API nie jest w stanie zwrócić takiej informacji od razu w odpowiedzi.
Ale wtedy po co taka struktura zwracanych danych?

**Comment by PawelTaberski** [comment]
To poprawny respons metoda od razu nie jest w stanie stwierdzić ile zadań publikacji skończy się powodzeniem, ile failem itd. Do sprawdzenia tych informacji wystawiliśmy 2 zasoby:

- GET na zasobie /sale/offer-publication-commands/{commandId}
- GET na zasobie /sale/offer-publication-commands/{commandId}/tasks

Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-10-tasks).
