### ISSUE TITLE
problem z uzyskaniem tokena - getAccessToken() zwraca HTTP 400

### ISSUE THREAD

**Issue by carridar** [allegro/allegro-api#1539]
Zacząłem przygodę z API i poległem już na pierwszym przykładowym skrypcie umieszczonym na https://developer.allegro.pl/getting_started/#jak-uzyska%c4%87-token-dost%c4%99powy-do-api 
$resultCode w getAccessToken() przyjmuje wartość 400 (Bad Request). Oczywiście aplikacja zarejestrowana ID: 'aed4f2f0661544dab9bde1d30fecd15d'. $clientId oraz $clientSecret wypełnone.
Próbowałem uruchomić u 2 różnych providerów (PHP 7.0). Bez zmian.

`<?php
function getAccessToken(): String
{
    $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "aed4f2f0661544dab9bde1d30fecd15d";
    $clientSecret = "clientSecret z rejestracji aplikacji";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
	                                                              echo $resultCode;
	exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

function main()
{
    echo "access_token = ", getAccessToken();
}

main();
 
?>`

**Comment by PawelTaberski** [comment]
Czy pamiętałeś aby dołączyć nagłówek Authorization w formacie Basic base64 i zakodować  ciąg "client_id:client_secret" wraz ze znakiem ":" pomiędzy wartościami?

**Comment by JMLnet** [comment]
Czy kod powinien wyglądać tak jak poniżej?
`curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Authorization: '.base64_encode($clientId.':'.$clientSecret)
		));
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);`

**Comment by PawelTaberski** [comment]
Nie prowadzimy wsparcia w kodowaniu, jednakże z tego co widać masz tam kilka drobnych błędów, powinno być:
```
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Authorization: Basic '.base64_encode($clientId.':'.$clientSecret)
));
curl_setopt($ch, CURLOPT_USERNAME, $clientId);
curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
```

**Comment by JMLnet** [comment]
> Nie prowadzimy wsparcia w kodowaniu, jednakże z tego co widać masz tam kilka drobnych błędów, powinno być:
> 
> ```
> curl_setopt($ch, CURLOPT_POST, 1);
> curl_setopt($ch, CURLOPT_HTTPHEADER, array(
> 'Authorization: Basic '.base64_encode($clientId.':'.$clientSecret)
> ));
> curl_setopt($ch, CURLOPT_USERNAME, $clientId);
> curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> ```

Dziękuję za korektę jednakże czego bym nie robił, za każdym razem zwracany jest błąd 400 co sugeruje wysyłanie złych danych - zweryfikowałem klucze z sandboxa i wszystko wygląda ok. Zweryfikowałem również klucze wywołując 'ręcznie' w przeglądarce adres https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials i logując się odpowiednimi danymi - wszystko jest popranie - czy może występować jakakolwiek blokada po stronie środowiska testowego?

**Comment by JMLnet** [comment]
Kod który zadziałał:
`		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $authUrl);
		curl_setopt($ch, CURLOPT_POST, TRUE);

		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		curl_setopt($ch, CURLOPT_USERNAME, $clientId);
		curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_POSTFIELDS, array(
			'client_id' => $clientId,
			'client_secret' => $clientSecret,
			'redirect_uri' => $redirect_uri,
			'grant_type' => 'client_credentials'
		));

		$tokenResult = curl_exec($ch);
		$resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);`

**Comment by carridar** [comment]
JMLnet dziękuje Ci bardzo - ruszyło! Szanowny Panie Pawle proszę poprawić Wasz kod na [developer.allegro](https://developer.allegro.pl/getting_started/) (pierwszy listing), niech inni początkujący nie mają problemów. Jeszcze raz dziękuje wszystkim za pomoc.

**Comment by PawelTaberski** [comment]
@carridar Nie bardzo rozumiem, w którym miejscu w dokumentacji jest błąd, oczywiście poprawimy.

**Comment by zherelevich** [comment]
> Zacząłem przygodę z API i poległem już na pierwszym przykładowym skrypcie umieszczonym na https://developer.allegro.pl/getting_started/#jak-uzyska%c4%87-token-dost%c4%99powy-do-api
> $resultCode w getAccessToken() przyjmuje wartość 400 (Bad Request). Oczywiście aplikacja zarejestrowana ID: 'aed4f2f0661544dab9bde1d30fecd15d'. $clientId oraz $clientSecret wypełnone.
> Próbowałem uruchomić u 2 różnych providerów (PHP 7.0). Bez zmian.
> 
> `<?php
> function getAccessToken(): String
> {
> $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";
> $clientId = "aed4f2f0661544dab9bde1d30fecd15d";
> $clientSecret = "clientSecret z rejestracji aplikacji";
> 
> ```
> $ch = curl_init($authUrl);
> 
> curl_setopt($ch, CURLOPT_POST, 1);
> curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
> curl_setopt($ch, CURLOPT_USERNAME, $clientId);
> curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> 
> $tokenResult = curl_exec($ch);
> $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
> curl_close($ch);
> 
> if ($tokenResult === false || $resultCode !== 200) {
>                                                               echo $resultCode;
> exit ("Something went wrong");
> }
> 
> $tokenObject = json_decode($tokenResult);
> 
> return $tokenObject->access_token;
> ```
> }
> 
> function main()
> {
> echo "access_token = ", getAccessToken();
> }
> 
> main();
> 
> ?>`

Remove curl_setopt($ch, CURLOPT_POST, TRUE);

**Comment by sdarmofal** [comment]
Na początku przepraszam za ponowne otwarcie tematu. 

W instrukcji jak zacząć (https://developer.allegro.pl/getting_started/) w sekcji *Jak uzyskać token dostępowy do API* na listingu pojawia się `curl_setopt($ch, CURLOPT_POST, 1);`. Przez tą instrukcję otrzymujemy informację `400 Bad Request`. Nie dzieje się tak na wszystkich konfiguracjach serwerowych. W moim przypadku problem pojawił się na 2 z 4 serwerów.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przykładowy request w formacie cURL, na który otrzymujesz błąd 400, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #1539.

**Comment by sdarmofal** [comment]
@PrzemyslawLukanowski problemem jest błąd w instrukcji, a dokładnie w kodzie PHP, który się w niej znajduje. Zapytanie wywoływane z konsoli (czyli te w formacie cURL) działa poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
@sdarmofal Wspomniałeś, że kod działa na części serwerów. Czy możesz doprecyzować zgłoszenie - w pozostałych przypadkach otrzymujesz błąd, napisz proszę, jaki jest komunikat błędu.

**Comment by sdarmofal** [comment]
@PrzemyslawLukanowski Ten, którego dotyczy wątek – 400 Bad Request. Mogę tylko zakładać, że na części moich serwerów działa ze względu na konkretną wersję cURL.

**Comment by PrzemyslawLukanowski** [comment]
@sdarmofal Zweryfikuj proszę, czy poniższy kod zadziała na wszystkich Twoich maszynach:

```
<?php
function getAccessToken(): String
{
    $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token";
    $clientId = "...";
    $clientSecret = "...";
    $ch = curl_init($authUrl);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    $tokenObject = json_decode($tokenResult);
    return $tokenObject->access_token;
}
function main()
{
    echo "access_token = ", getAccessToken();
}
main();
```

**Comment by sdarmofal** [comment]
@PrzemyslawLukanowski Tak jak pisałem, problem udało się rozwiązać poprzez usunięcie `curl_setopt($ch, CURLOPT_POST, 1);` ze swojego kodu. Taki fragment pojawia się w instrukcji https://developer.allegro.pl/getting_started/ i wprowadza osoby integrujące się z REST API Allegro w błąd.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, dziękuję, ale czy kod wklejony wyżej zadziałał poprawnie w Twoim przypadku?
