### ISSUE TITLE
Jak odczytać poszczególne opcje z maski

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#1542]
mógłby ktoś podać krok po kroku jak odczytać poszczególne opcje z maski np. dla 50364838 informację z https://allegro.pl/webapi/faq.php#faq_4 nie pomogły

**Comment by MartaNowaczyk** [comment]
dla maski 50364838 wartość w systemie dwójkowym to 11000000001000000110100110 ([przykładowy kalkulator](http://www.webmaster.net.pl/narzedzia_online/konwersja_liczb.php))
W systemie dwójkowym od końca mamy wartości 1,2,4,8,16,32... czyli patrząc na maski w naszym [FAQ](https://allegro.pl/webapi/faq.php#faq_4) i porównując z ustawieniem kolejnych bitów (od końca) mamy:
0 dla wartości 1
1 dla wartości  2
1 dla wartości 4
0 dla wartości 8
0 dla wartości 16
1 dla wartości 32
0 dla wartości 64
1 dla wartości 128
1 dla wartości 256
0 dla wartości 512
0 dla wartości 1024
0 dla wartości 2048
0 dla wartości 4096
0 dla wartości 8192
0 dla wartości 16384
1 dla wartości 32768
0 dla wartości 65536
0 dla wartości 131072
0 dla wartości 262144
0 dla wartości 524288
0 dla wartości 1048576
0 dla wartości 2097152
0 dla wartości 4194304
0 dla wartości 8388608
1 dla wartości 16777216
1 dla wartości 33554432 
Oferta zawiera te opcje przy których masz 1.  Jak zsumujesz wszystkie wartości, gdzie masz 1: 2+4+32+128+256+32768+16777216+33554432 dostaniesz swoją maskę 50364838

Jeśli chcesz sprawdzić czy w danej masce jest jakaś wartość, która cię interesuje możesz skorzystać z [kalkulatora](http://bitwisecmd.com/). Wystarczy wpisać 50364838&16777216 - tym samym sprawdzisz czy w otrzymanej masce masz opcję "wybrana opcja dostawy: przesyłka kurierska
"

**Comment by dark774** [comment]
Dzięki
