### ISSUE TITLE
order/events - nieobsłużony komunikat błędu

### ISSUE THREAD

**Issue by hoobert89** [allegro/allegro-api#1543]
Zgodnie z dokumentacją: https://developer.allegro.pl/orders/#02, wywołanie

> curl -X GET \\
> 'https://api.allegro.pl/order/events' \\
> -H 'Authorization: Bearer eyJhbGci*********' \\
> -H 'Accept: application/vnd.allegro.beta.v1+json'

powoduje otrzymanie następującej zwrotki:

```
{"errors":[
    {
        "code":"ERROR","
        "message":"An error has occurred",
        "details":null,
        "path":null,
        "userMessage":null
    }
]}
```
Czy można prosić o naprowadzenie, dlaczego taki response?

**Comment by MartaNowaczyk** [comment]
Jaki dostajesz status HTTP?
