### ISSUE TITLE
tylda ~ w redirect_uri

### ISSUE THREAD

**Issue by szuuuu** [allegro/allegro-api#1544]
jeżeli w redirect_uri jest tylda ~ to strona autoryzacji nie działa mimo że nigdzie nie napisaliście że nie można tego znaku używać. czy to błąd?
w imieniu apacza i katalogu public_html stanowczo protestuję przeciwko takiej dyskryminacji!

**Comment by MartaNowaczyk** [comment]
@szuuuu rozumiem, że podać redirect_uri z ~ możesz, tylko jest problem z użyciem tego adresu. Sprawdzimy ten przypadek.

**Comment by szuuuu** [comment]
tak, na przykład:

to działa:
`https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=..........&redirect_uri=http://localhost/user/alle_auth/`

to nie działa:
`https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=..........&redirect_uri=http://localhost/~user/alle_auth/`

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację. Gdy coś ustalimy dam znać.

**Comment by MartaNowaczyk** [comment]
Jeszcze nie powiedzieliśmy nie w tej sprawie. Nie zamykamy - czekamy na ustalenia.

**Comment by MartaNowaczyk** [comment]
@szuuuu dodaliśmy możliwość redirect_uri z tyldą ~ 
Sprawdź proszę czy wszystko działa.
