### ISSUE TITLE
sale/categories/{categoryId} - błąd w dokumentacji

### ISSUE THREAD

**Issue by damianSzechlicki** [allegro/allegro-api#1545]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

/sale/categories/{categoryId}

W poradniku dotyczącym wielowariantowości w przykładowym requescie jest napisane, że ten zasób jest w wersji beta a według mnie powinno tam być public

![image](https://user-images.githubusercontent.com/25161593/56645866-c6478880-667e-11e9-8357-95c40eea1772.png)

**Comment by MartaNowaczyk** [comment]
@damianSzechlicki dziękujemy bardzo za zgłoszenie. Przy najbliższym wdrożeniu na stronę poprawimy ten błąd.
