### ISSUE TITLE
pobranie ogłoszeń użytkownika z wybranej kategorii

### ISSUE THREAD

**Issue by axzx** [allegro/allegro-api#1547]
Jak pobrać wszystkie ogłoszenia użytkownika z wybranej kategorii? Chodzi o usera, który utworzył access token. 

W dokumentacji https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET nie widzę parametru category. 

Tak przy okazji, w dokumentacji jest przykładowy response gdzie jest `Offers`, natomiast ten endpoint zwraca `items`. 
Kolejny błąd to info, że parametr `seller.id` jest `required`, ale jak się go nie poda to zwracane są ogłoszenia zalogowanego usera. Trochę mylące.

**Comment by axzx** [comment]
Jeszcze jedno pytanie. Załóżmy, że user ma 95 ogłoszeń. Chcąc pobrać ich dane, muszę zrobić 96 requestów? Najpierw jedno pobierające wszystkie ogłoszenia (tam nie ma wszystkich danych), dopiero później dla każdego ogłoszenia osobny request pobierający więcej danych?

Później pewnie jeszcze kolejne requesty pobierające parametry.

**Comment by rtnet-pl** [comment]
> Jak pobrać wszystkie ogłoszenia użytkownika z wybranej kategorii?

Musisz skorzystać z /sale/offers i odpytać każdą ofertę z osobna przez /sale/offers/id.
Alternatywnie można użyć /offers/listing (umożliwia określenei sellers.id i category.id) oraz potem dodatkowo dopytać brakujące elementy sposobem podanym powyżej (w /offers/listings będzie brakowało wariantów).




> ałóżmy, że user ma 95 ogłoszeń. Chcąc pobrać ich dane, muszę zrobić 96 requestów? Najpierw jedno pobierające wszystkie ogłoszenia (tam nie ma wszystkich danych), dopiero później dla każdego ogłoszenia osobny request pobierający więcej danych?

Tak, dodatkowo musisz uwzględnić stronicowanie.

> Później pewnie jeszcze kolejne requesty pobierające parametry.

parametry będą w /sale/offers/id

**Comment by MartaNowaczyk** [comment]
@axzx endpoint /sale/offers zwraca tablicę offers, tak jak jest to w dokumentacji. 
Jeśli chodzi o seller.id required poprawimy, bo tak jak piszesz nie jest to wymagane.

**Comment by axzx** [comment]
@MartaNowaczyk różnic w stosunku do dokumentacji jest więcej:

![obraz](https://user-images.githubusercontent.com/1436016/56716215-06b80c80-673a-11e9-9690-086dbf1d466a.png)

tak jakby w dokumentacji był przykładowy response z innego endpointa;)

**Comment by axzx** [comment]
Wracając do pierwotnego tematu - czy dałoby się zrobić filtr, który umożliwi pobranie ofert z wybranej kategorii? Tylko nie chodzi o dokładne dopasowanie, ale żeby pobrać również oferty z podkategorii. 

Teraz gdy chcę pobrać wszystkie ogłoszenia z Nieruchomości to muszę przelecieć wszystkie oferty i dla każdej sprawdzać całą ścieżkę kategorii w górę. Wychodzi, że dla każdej oferty będzie po kilka dodatkowych requestów. Dla 1000 ofert, może to być 5000 requestów, żeby zawęzić ilość ofert do np. 2, bo dany user wystawia przeważnie w motoryzacji, ale ma też 2 ogłoszenia w nieruchomościach.

**Comment by MartaNowaczyk** [comment]
@axzx twój response jest chyba z innego endpointu. 
Mój response dla GET /sale/offers:

```{
    "offers": [
        {
            "id": "7922151005",
            "name": "PROCESOR Intel , Hexa Core",
            "category": {
                "id": "257222"
            },
            "primaryImage": {
                "url": ""
            },
            "sellingMode": {
                "format": "BUY_NOW",
                "price": {
                    "amount": "1199.0",
                    "currency": "PLN"
                },
                "minimalPrice": null,
                "startingPrice": null
            },
            "saleInfo": {
                "currentPrice": null,
                "biddersCount": 0
            },
            "stats": {
                "watchersCount": 0,
                "visitsCount": 1
            },
            "stock": {
                "available": 1,
                "sold": 0
            },
            "publication": {
                "status": "ENDED",
                "startingAt": null,
                "startedAt": "2019-03-22T07:19:26Z",
                "endingAt": null,
                "endedAt": "2019-03-22T07:29:07Z"
            },
            "afterSalesServices": {
                "warranty": {
                    "id": "2d15741b-93b1-4d24-989c-dc2d412d91ff"
                },
                "returnPolicy": {
                    "id": "cf5f8e7a-4488-4420-810d-259bd84b745f"
                },
                "impliedWarranty": {
                    "id": "de2ad368-2682-47ab-9868-d813d968846a"
                }
            },
            "additionalServices": null,
            "external": {
                "id": "5"
            }
        }

**Comment by MartaNowaczyk** [comment]
> Wracając do pierwotnego tematu - czy dałoby się zrobić filtr, który umożliwi pobranie ofert z wybranej kategorii? Tylko nie chodzi o dokładne dopasowanie, ale żeby pobrać również oferty z podkategorii.

> Teraz gdy chcę pobrać wszystkie ogłoszenia z Nieruchomości to muszę przelecieć wszystkie oferty i dla każdej sprawdzać całą ścieżkę kategorii w górę. Wychodzi, że dla każdej oferty będzie po kilka dodatkowych requestów. Dla 1000 ofert, może to być 5000 requestów, żeby zawęzić ilość ofert do np. 2, bo dany user wystawia przeważnie w motoryzacji, ale ma też 2 ogłoszenia w nieruchomościach.

Nie planowaliśmy takiego filtra, jednak zgłoszę taką sugestię do odpowiedniego zespołu.

**Comment by axzx** [comment]
ok, już wiem. 
nie miałem nagłówków
```
'Accept' => 'application/vnd.allegro.public.v1+json',
'Content-type' => 'application/vnd.allegro.public.v1+json',
```
