### ISSUE TITLE
niespójności w nazwach pól

### ISSUE THREAD

**Issue by axzx** [allegro/allegro-api#1548]
:bulb: **Sugestia**

W `sale/offers` jest pole `photoUrl`, a w `sale/offers/{offerId}` jest pole `images`. Można by to ujednolicić - albo photo albo image. 

Podobnie jest z nazwą i id. Raz jest `offerTitle`, a raz `name`. Raz jest `offerId`, a raz `id`.

**Comment by MartaNowaczyk** [comment]
Dziękujemy za sugestie - zgłoszę je do odpowiednich zespołów.

**Comment by axzx** [comment]
po tym jak dodałem nagłówki
```
'Accept' => 'application/vnd.allegro.public.v1+json',
'Content-type' => 'application/vnd.allegro.public.v1+json',
```

sytuacja trochę się zmieniła - nazwy pól pokrywają się (przynajmniej w tym zakresie o którym pisałem).
