### ISSUE TITLE
refresh Tokena a powiazane aplikacje na koncie Allegro

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#1549]
Sytuacja jest nastepujaca. Mam uzytkownika, ktory juz w 2017 roku powiazal moja aplikacje ze swoim kontem Allegro. AccessToken zostal nadany i od tego czasu jest regularnie odswiezany przez automatyczne skrypty. Natomiast przy probie pobrania informacji o uslugach pozakupowych (np. https://api.allegro.pl/after-sales-service-conditions/return-policies) dostaje odpowiedz o kodzie 403 FORBIDDEN: `{"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":null,"userMessage":"You do not have permission to request this resource"}]}`

Zaczalem zatem grzebac, zalogowalem sie na konto klienta i rzeczywiscie - brak mojej aplikacji na liscie powiazanych. Wychodzi na to, ze mimo iz moja aplikacja nie ma juz dotepu do konta uzytkownika to nie przeszkadza to RestAPI pozwolic mi odswiezyc access tokena. Czy tak jest w istocie? Czy nie mozna tego zmienic? W jaki sposob moja aplikacja ma sie zorientowac, ze nie ma juz potrzebnych uprawnien? 

Oczywistym rozwiazaniem wydawaloby sie oznaczac konto klienta jako bez dostepu/powiazania z aplikacja na podstawie otrzymanej odpowiedzi 403 z RestAPI, jednak doswiadczenie WebAPI jasno uczy - NIGDY PRZENIGDY nie odcinaj na twardo klienta na podstawie exceptionu mowiacego ze cos nie istnieje, badz nie ma uprawnien. Bo to moze byc tylko "stan przejsciowy". Tutaj pytanie do innych - dostajecie odpowiedzi 403 _pomimo_ faktu, ze uprawnienia sa?

**Comment by MartaNowaczyk** [comment]
@barthoos mamy jeszcze inne przypuszczenia, ale potrzebujemy danych żeby to wyjaśnić. Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1549 dane:
1) Client id i login/id usera, który nie widzi tego client id na liście
2) Jakiś przykładowy trace-id, takiego requestu

**Comment by barthoos** [comment]
Witam,

Poszlo - zgloszenie 05262525.

**Comment by MartaNowaczyk** [comment]
Dziękujemy za dane, zweryfikujemy opisaną sytuację.

**Comment by MartaNowaczyk** [comment]
Sprawę ze statusem 403 sprawdziliśmy i userId z tokena jest inny niż ten, który podajesz w parametrze zapytania, stąd ten błąd.

Kwestię uprawnień jeszcze sprawdzamy.

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o powiązanie aplikacji, to według naszych danych powinno być ono widoczne na liście u klienta. Sprawdzamy dlaczego go nie widać.

**Comment by barthoos** [comment]
Jezeli token jest powiazany z innym sellerId niz podalem to bardzo duzo wyjasnia. Bez bicia sie przyznam, ze tego id nie bralem z dekodowania tokena, tylko na podstawie informacji jaki login allegro byl podpiety po moja aplikacje (sellerId bralem z WebAPI). Rzeczywiscie teoretycznie moze byc tak, ze uzytkownik powiaze aplikacje z innym loginem, niz ten ktory ma wpisany w moich ustawieniach. Jest to bez sensu, ale co poradzic na kreatywnosc usera ;)

Skoro token jest innego uzytkownika, to fakt ze nie widzialem mojej apki na liscie jest bez znaczenia. Bo patrzylem nie na ta liste.

**Comment by barthoos** [comment]
No dobrze, ale otwartym pozostaje pytanie w jaki sposob mam sie zorientowac, ze uzytkownik cofnal mi uprawnienia to dzialania w jego imieniu (usunal moja aplikacje z powiazanych)?

**Comment by PawelTaberski** [comment]
@barthoos Jeśli user cofnie uprawnienia, to przy próbie odświeżenia przy użyciu najnowszego refresha jakiego posiadasz otrzymasz błąd:
```
{
    "error": "invalid_grant",
    "error_description": "Invalid refresh token:........................
}
```

**Comment by barthoos** [comment]
To jest jasne, pytanie czy randomowo nie wyplujecie takim komunikatem nawet jesli uprawnienia sa w porzadku? Pytam, bo w przypadku WebAPI zdarzaja sie "okresowe" exceptiony ERR_USER_PASSWD, czy ERR_BLOCK_SELL_SELL, ktore dostaje, mimo ze wszystko jest w porzadku. Jak bezkrytycznie przyjmowalem to za blad i odcinalem dostep uzytkownikowi to mialem mase zgloszen, ze przeciez wsio jest OK, a ja odcinam.. Radze sobie z tym tak, ze odcinam dostep dopiero przy N-tym wystapieniu danego wyjatku w _ciagu dnia_. 


Pytanie jak to jest z RESTem? Takie rzeczy tylko przy sklali, wiec pytanie do tych co skale maja :)

**Comment by PawelTaberski** [comment]
Nie kojarzę przypadku, aby przy odświeżeniu (przy użyciu najnowszego refresha) user otrzymał informację, że jest on nieprawidłowy. Jeśli napotkałbyś taki problem to oczywiście koniecznie daj znać.
