### ISSUE TITLE
Pusta odpowiedź w metodzie doAddPackageInfoToPostBuyForm

### ISSUE THREAD

**Issue by btragarz** [allegro/allegro-api#155]
Nie mogę wysłać numeru paczki przez webAPI. Metoda zwraca pustą tablicę:

[
    postBuyFormPackageInfo" => [
        "packageIdsAdded" => [],
        "packageIdsNotAddedIncorrectOperatorId" => [],
        "packageIdsNotAddedIncorrectPackageId" => []
    ]
]
Nie ma żadnego komunikatu o błędzie. Jak wysyłam błędne dane to dostaję wtedy komunikaty np. o nieprawidłowym ID transakcji.
Wysyłam taką tablicę:

array:2 [
  "transactionId" => "727870756"
  "packageInfo " => array:1 [
    0 => array:2 [
      "operatorId" => 5
      "packageId" => "636062279754610014205062"
    ]
  ]
]

**Comment by MaciejPotepa** [comment]
Żebyśmy mogli Ci pomóc potrzebujemy pełnej treści requestu i response w XML.

**Comment by btragarz** [comment]
Okazało się, że jednak mam błąd w przekazywanej tablicy. Po sprawdzeniu xml'a okazało się, że wycina parametr packageInfo.
