### ISSUE TITLE
Mam problem z metodą doGetMySellItems

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1550]
Na koncie mam 30k ofert, pobieram po 1000 szt.
Zwraca mi losowo kilka stron wyników, potem zero.
Czasami zwraca wszystkie.
Wiem, że mogę przejść na rest'a.
Jednak do czasu wygaszenia moglibyście ją naprawić.
KF

**Comment by MartaNowaczyk** [comment]
@kfijalko podobny błąd mamy już zgłoszony. Możesz podesłać przykładowy request i response z brakiem lub niepełnymi wynikami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1550

**Comment by kfijalko** [comment]
Błąd jest powtarzalny w tym sensie, że wycina strony w 9 przypadkach na 10.
Jednak wycięte strony są losowe.
Teraz wykonałem skrypt kilka razy. Za pierwszym razem wyciął mi stronę 5, za drugim 16, za trzecim wykonał się prawidłowo, za czwartym wyciął stronę 10. Poniżej Req/Res.
Request:
`
<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><soap-env:body><ns1:dogetmysellitemsrequest><ns1:sessionid>108c6bbdb73a0172e7XXXXXXXXXcc68//00_1</ns1:sessionid><ns1:sortoptions><ns1:sorttype>1</ns1:sorttype><ns1:sortorder>1</ns1:sortorder></ns1:sortoptions><ns1:pagesize>1000</ns1:pagesize><ns1:pagenumber>10</ns1:pagenumber></ns1:dogetmysellitemsrequest></soap-env:body></soap-env:envelope>`

Response:
`
<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><soap-env:body><ns1:dogetmysellitemsresponse><ns1:sellitemscounter>0</ns1:sellitemscounter><ns1:sellitemslist></ns1:sellitemslist></ns1:dogetmysellitemsresponse></soap-env:body></soap-env:envelope>`

**Comment by kfijalko** [comment]
Skrypt zmodyfikowałem tak, że jak dostaje zero to o daną stronę pyta ponownie (5 razy). W powyższym czwartym przebiegu. Stronę 10 pobrał prawidłowo za 3 razem. Liczba aktywnych ofert zgadza się co do sztuki.

**Comment by MartaNowaczyk** [comment]
Dzięki za informacje.
