### ISSUE TITLE
Bad credentials przy próbie uzyskania tokenu dostępowego

### ISSUE THREAD

**Issue by gogolon** [allegro/allegro-api#1551]
Witam, to moja pierwsza styczność z REST API Allegro. Niestety utknąłem na samym początku. Zgodnie z dokumentacją (https://developer.allegro.pl/getting_started/#jak-zarejestrowa%C4%87-now%C4%85-aplikacj%C4%99) próbuję zdobyć token dostępowy, niestety jako odpowiedź na request dostaję błąd - bad credentials. Dodaję nagłowek Authorization i podaję prawidłowy clientId i clientSecret, zakodowany razem z dwukropkiem w Base64. Co jest nie tak? Poniżej kod C#, RestSharp:
```
            RestRequest tokenRequest = new RestRequest("https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials", Method.POST);
            tokenRequest.AddHeader("Authorization", "Basic " + Base64Encode(clientId + ':' + clientSecret));
            IRestResponse response = restClient.Execute(tokenRequest);
            string res = response.Content;
```

**Comment by kfijalko** [comment]
Skorzystaj z tego poradnika:
https://developer.allegro.pl/auth/
W pkt 5 masz wspomniane parametry, których nie widzę w Twoim kodzie:

> 

Authorization | Nagłówek HTTP: Authorization. Autoryzacja typu Basic, z zawartością w formie client_id:client_secret (dane otrzymane przy rejestracji aplikacji) w postaci Base64
-- | --
https://allegro.pl/auth/oauth/token | Endpoint Allegro pozwalający na uzyskanie tokena OAuth
grant_type | Rodzaj dostępu potrzebny do uzyskania tokena (w tym przypadku authorization_code)
code | Kod autoryzujący (uzyskany w kroku 4)
redirect_uri | Adres powrotu (musi być zgodny z tym podanym przy rejestracji aplikacji)

**Comment by kfijalko** [comment]
Możesz też zerknąć na #1539
