### ISSUE TITLE
GET /sale/categories błąd: Unable to communicate securely with peer

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1552]
We wczorajszym logu znalazłem poniższy błąd. Wystąpił w czasie wykonania "GET /sale/categories":

> [2019-04-24 00:10:10] local.CRITICAL: App\Allegro\AllegroClientCategories::getCategories:75Wystąpił błąd podczas wywoływania https://api.allegro.pl/sale/categories?parent.id=26104 komunikat:Unable to communicate securely with peer: requested domain name does not match the server's certificate.

Niestety nie loguję Req/Res dlatego nie jestem w stanie ich przesłać.

**Comment by MartaNowaczyk** [comment]
Czy błąd wystąpił tylko raz czy się powtarza? Potrzebujemy więcej informacji, żeby zweryfikować opisaną sytuację.

**Comment by kfijalko** [comment]
Mam logi od 2019-04-17 i nie znalazłem ponownego wystąpienia. Nie jestem w stanie nic więcej powiedzieć. Jeżeli nie macie u siebie informacji w logach to ...
Dla mnie ten błąd nie miał znaczenia. Możemy zamknąć ten wątek.
