### ISSUE TITLE
order/events

### ISSUE THREAD

**Issue by bjatwork** [allegro/allegro-api#1553]
Mam pytanie, czy dla eventów typu BOUGHT, FILLED_IN, READY_FOR_PROCESSING dla tego samego zakupu mogą być różne zakupione przedmioty - tzn. czy jest jakaś możliwość aby klient edytował to co początkowo pojawiło się w BOUGHT? 

Drugie pytanie w jaki sposób mogę za symulować zakup bez wypełnionego formularza po zakupowego (tak aby pojawił się tylko event BOUGHT), przy testach zawsze muszę ostatecznie wypełnić formularz, aby złożyć zamówienie i zawsze mam trzy.

Czasami dla danego zakupu mam eventy, źle posortowane wg daty mam np.  
0 FILLED_IN
1 BOUGHT
2 READY_FOR_PROCESSING 
To chyba błąd po Waszej stronie. 
Przez ten błąd musimy sortować tablice eventów wg daty po naszej stronie.

**Comment by MartaNowaczyk** [comment]
Status BOUGHT uzyskasz przy zakupie przez "Kup Teraz". Wybierz "Kupuję i Płacę" i nie wypełniaj formularza.

[W poradniku](https://developer.allegro.pl/orders/) w sekcji Ważne w ostatnim punkcie opisaliśmy sytuację, w której kupujący może opłacić za jednym razem dwa oddzielne zakupy (BOUGHT) przez co tworzy się inne zamówienie (statusy FILLED_IN, READY_FOR_PROCESSING). Pojedynczego zakupu w statusie BOUGHT nie zmieni.

Jeśli chodzi o kolejność, zgodnie z informacją [w sekcji Ważne](https://developer.allegro.pl/orders/) jest taka możliwość i nie traktujemy tego jako błąd..
