### ISSUE TITLE
RestApi - brak wersjonowania kategorii i parametrów?

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1554]
Nawiązując do tej wypowiedzi: https://github.com/allegro/allegro-api/issues/1506#issuecomment-486129917

> W REST API nie ma wersjonowania drzewa, także trzeba je pobierać na bieżąco.

Czyli parametry kategorii też nie będą wersjonowane? Jeśli tak, to robi się z tego RestApi co raz większy niewypał.

Może przy wystawianiu aukcji przez frontend wersjonowanie nie jest potrzebne, ale nie w aplikacjach, które służą do masowego zarządzania aukcjami, gdzie każda zaoszczędzona sekunda ma dla użytkownika znaczenie! Po to mam zapisane w bazie drzewo kategorii i ich parametry, aby użytkownik nie marnował czasu na czekanie, aż je API zwróci.

Dla przykładu mam funkcję do hurtowej modyfikacji parametrów kategorii i teraz przy edycji 10000 aukcji 90% czasu zajmie pobieranie z API aktualnych parametrów dostępnych dla danej kategorii!

Czy wyobraźnia osoby odpowiedzialnej za projekt RestApi sięga dalej niż frontend?

**Comment by MartaNowaczyk** [comment]
Parametry też nie są wersjonowane. Na ten moment zgłoszę taką potrzebę do odpowiedniego zespołu.
