### ISSUE TITLE
REST API - dodatkowe informacje o ofertach

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#1556]
Witam,

szukałem w dokumentacji ale nie mogę znaleźć
w jaki sposób można uzyskać  poniższe informacje o ofertach:
- Ilość wyświetleń oferty,
- ilość złożonych ofert kupna w licytacjach 
- ilość użytkowników obserwujących ofertę

W WebApi w/w informacje są dostępne w metodach doGetMySellItems, doGetMySoldItems, doGetMyNotSoldItems

**Comment by PawelTaberski** [comment]
Wszystkie te informacje otrzymasz w zasobie /sale/offers.
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by joe1d83** [comment]
Witam,

faktycznie jest tak opisane w dokumentacji, tylko że te dane nie są zwracane dla ofert pojedynczych (aktywnych oraz zakończonych)  /sale/offers/{offerId}
Pola "stats" oraz "saleInfo" które zawierają potrzebne dane nie są zwracane w tym przypadku.

Pozostaje pytanie jak uzyskać te informacje dla pojedynczych ofert ?

**Comment by PawelTaberski** [comment]
W tym wypadku możesz skorzystać z dostępnych [filtrów na zasobie](https://developer.allegro.pl/my_offers/) /sale/offers aby wyszukać interesującą Ciebie ofertę.
Powiedz mi czy dobrze myślę, dla Ciebie najwygodniejsze byłoby wyszukanie oferty w zasobie /sale/offers po jej identyfikatorze tak? Obecnie nie ma takiej możliwości, ale jeśli dobrze rozumiem Twoją potrzebę daj znać dodam Ciebie do tej sugestii bo inni userzy zgłaszali już potrzebę takiej możliwości.

**Comment by joe1d83** [comment]
Tak dokładnie o to chodzi. 
Dodam jeszcze że aktualna cena dla trwających licytacji lub cena końcowa dla zakończonych też by się przydała na tym zasobie.

**Comment by PawelTaberski** [comment]
Aktualną cenę jak i początkową już masz w tym zasobie:
```
                "price": {
                    "amount": "133.0",        -- cena dla oferty w formacie BUY_NOW (Kup 
                                              Teraz), ADVERTISEMENT (ogłoszenie)
                    "currency": "PLN"
                },
                "minimalPrice": null,         -- cena minimalna, dostępna w formacie 
                                              sprzedaży AUCTION (licytacja)
                "startingPrice": null         -- cena początkowa licytacji, dostępna w 
                                              formacie sprzedaży AUCTION (licytacja)
            },
            "saleInfo": {
                "currentPrice": null,         -- cena zakupu w licytacji
                "biddersCount": 0             -- liczba osób licytujących
            },
```
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#1).
