### ISSUE TITLE
doAddPackageInfoToPostBuyForm - 2 problemy

### ISSUE THREAD

**Issue by solokazama** [allegro/allegro-api#1557]
Występuje problem: 
 - [X ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Witam, mam 2 problemy z ta metoda (jest juz tak od jakiegos czasu, odczekalem):

- na ta chwile metoda zawsze zwraca mi pusta odpowiedz (obojetnie czy dodalo paczke czy nie), przyklad:
object(stdClass)#1 (1) {
  ["postBuyFormPackageInfo"]=>
  object(stdClass)#2 (3) {
    ["packageIdsAdded"]=>
    object(stdClass)#5 (0) {
    }
    ["packageIdsNotAddedIncorrectOperatorId"]=>
    object(stdClass)#4 (0) {
    }
    ["packageIdsNotAddedIncorrectPackageId"]=>
    object(stdClass)#3 (0) {
    }
  }

I tu pojawia sie drugi problem - nie dodaje nam paczek INPOST z numerami zaczynajacymi sie od 52 (kurier inpost). Paczki INPOST paczkomaty z numerami zaczynajacymi sie od 65 dodaje.

**DODA PACZKE:**
$doaddpackageinfotopostbuyform_request = array(
   'sessionId' => 'xxx',
   'transactionId' => 1006035571,
   'packageInfo' => array(
      array (
         'operatorId' => 5,
         'packageId' => '658200588904549119212132'),
);

**NIE DODA PACZKI:**
$doaddpackageinfotopostbuyform_request = array(
   'sessionId' => 'xxx',
   'transactionId' => 1004315679,
   'packageInfo' => array(
      array (
         'operatorId' => 5,
         'packageId' => '521000016243512024028187'),
);

jako, ze response mamy zawsze puste - nie jestesmy w stanie ocenic czy to bledne rozpoznanie packageId. Niestety nie mozemy (jeszcze) uzyc metod z restapi (dopiero jestesmy w trakcie refactoringu systemu).

nie dodaje tez paczek gdy podamy operatorId=0 ("inny kurier"), problowalismy na szybko tak obejsc ten problem.

To czy paczka zostala dodana/nie dodana sprawdzamy przez panel allegro - gdy z reponse zawsze mamy puste. 

Cos sie zmienilo? do niedawna wszystko dzialalo OK, przez w/w problem mamy sporo nie dodanych numerow paczek i <50% wszystkich dodanych co powoduje utracenie statusu allegro smart.

Generalnie wystarczyloby, aby zwracany response cos zawieral, jest pusty wiec nic nie potrafimy okreslic co sie dzieje.

**Comment by PawelTaberski** [comment]
Przetestowałem i normalnie udało mi się dodać do zamówienia taki numer. Twoją sprawę przekazałem do głębszej analizy przez zespół, który odpowiada za tą metodę. Proszę o cierpliwość.

**Comment by solokazama** [comment]
Cos wiadomo?

metoda dalej zwraca pusta strukture, obojetnie czy dodalo czy nie. nie wiemy wiec co sie dzieje, a nie dodaje w wielu przypadkach, kolejny przyklad (mam ich dziesiatki, moge podeslac z deal_ids):

$doaddpackageinfotopostbuyform_request = array(
'sessionId' => 'xxx',
'transactionId' => 1013534369,
'packageInfo' => array(
array (
'operatorId' => 5,
'packageId' => '523000014576270007980320'),
);

**response:**
object(stdClass)#1 (1) {
["postBuyFormPackageInfo"]=>
object(stdClass)#2 (3) {
["packageIdsAdded"]=>
object(stdClass)#5 (0) {
}
["packageIdsNotAddedIncorrectOperatorId"]=>
object(stdClass)#4 (0) {
}
["packageIdsNotAddedIncorrectPackageId"]=>
object(stdClass)#3 (0) {
}
}

jak paczke doda to response tez jest pusty.

refactoring na restapi dopiero mamy wtrakcie, a allegro WYMAGA obecnie numerow paczek (inaczej traci sie status SMART) wiec bardzo prosze o sprawdzenie dlaczego metoda zwraca puste odpowiedzi. W przypadku bledu. Response powinno byc wg. dokumetnacji takie (i jaki czas bylo):

$doaddpackageinfotopostbuyform_response = array(
   'postBuyFormPackageInfo' => array(
      'packageIdsAdded' => array('1Z7E09X67746525354'),
      'packageIdsNotAddedIncorrectOperatorId' => array('2812050417473'),
      'packageIdsNotAddedIncorrectPackageId' => array())
);

**Comment by solokazama** [comment]
gdy prawidlowo doda (dodalo paczke) reponse tez jest pusty:


$doaddpackageinfotopostbuyform_request = array(
'sessionId' => 'xxx',
'transactionId' => 1013561712,
'packageInfo' => array(
array (
'operatorId' => 5,
'packageId' => '658200078943382110531851'),
);

**response:**
object(stdClass)#3 (1) {
  ["postBuyFormPackageInfo"]=>
  object(stdClass)#4 (3) {
    ["packageIdsAdded"]=>
    object(stdClass)#5 (0) {
    }
    ["packageIdsNotAddedIncorrectOperatorId"]=>
    object(stdClass)#6 (0) {
    }
    ["packageIdsNotAddedIncorrectPackageId"]=>
    object(stdClass)#7 (0) {
    }
  }
}

**Comment by MartaNowaczyk** [comment]
Przepraszam, że tak długo czekasz na rozwiązanie problemu. Sprawa cały czas w toku. Gdy będziemy mieć jakieś informacje damy znać.

**Comment by zulus** [comment]
Mi dla odmiany ta metoda wisi. Serwer nic nie zwraca po prostu czekam na odpowiedź. Po 3 minutach zrywam połączenie (taki mam ustawiony kaganiec).

**Comment by solokazama** [comment]
> Przepraszam, że tak długo czekasz na rozwiązanie problemu. Sprawa cały czas w toku. Gdy będziemy mieć jakieś informacje damy znać.

Minal juz prawie miesiac (!), za 10 dni (mam nadzieje, ze termin zostanie przesuniety) ma byc odlaczone czesc starego SOAPa (wiec obecnie robimy refaktoringi tam gdzie trzeba; ta metoda jest nowa i w tym roku nie ma w planach jej porzucania), a nie moge dostac odpowiedzi na w/w metode zwracajaca ciagle pusta odpowiedz. 

Allegro WYMAGA obecnie podawania nr paczki (aby utrzymac status smart).

Moglby w koncu ktos cos napisac? Nie byloby problemu gdyby metoda zwracala jakas informacje (z ew. bledem).

@MartaNowaczyk

**Comment by MartaNowaczyk** [comment]
Sprawa powinna być rozwiązana w ciągu kilku dni.

**Comment by solokazama** [comment]
czy wiadomo juz cos w tej sprawie? 
Bo nie mozemy dodawac przez RESTAPI, bo nie mozemy zintegrowac formularzy pozakupowych via restapi, bo INPOST nie bedzie dzialac (stad w/w i tak musimy przez SOAPa)

a allegro wymaga nr paczki albo odlaczaja od uzytkownika SMART

@MartaNowaczyk

**Comment by PawelTaberski** [comment]
@solokazama Pamiętaj, że metody doGetPostBuyFormsDataForSellers nie wygaszamy 3 czerwca, przy jej pomocy możesz pobrać dealTransactionId. Ponadto InPost w najbliższym czasie powinien już wprowadzić zmiany.

**Comment by solokazama** [comment]
Jakies informacje dotyczace tej metody? Ja rozumiem, ze wygaszamy SOAPa, ale dla niektorych klientow musimy trzymac jeszcze hybryde.

Problem zglosilem 25 kwietnia, mamy 11 czerwca i zadnej informacji dlaczego metoda **doAddPackageInfoToPostBuyForm zwraca pusty response** (dokladniej **pusta strukture**, bez danych) - nie jestesmy wiec w stanie okreslic czy dodalo paczke, a jezeli nie dodalo - to dlaczego.

**Comment by PawelTaberski** [comment]
Jeszcze zwiększyłem priorytet tego zadania i zaznaczyłem, że sprawa jest już pilna i mocno utrudnia działanie, prośba o jeszcze trochę cierpliwości.

**Comment by PawelTaberski** [comment]
@solokazama Daj proszę znać, czy problem dalej u Ciebie występuje.
