### ISSUE TITLE
Jak pobrać order id w REST API mając form id z WEB API. 

### ISSUE THREAD

**Issue by SENSBIT** [allegro/allegro-api#1559]
Dzień dobry,

Pilnie potrzebuję informacji w jaki sposób pobrać order id, który jest dostępu w REST, a którego nie ma w WEB API.

Innymi słowy mam to co zwraca doGetTransactionsIDs z web api, i za pomocą tego potrzebuję uzyskać checkoutForm_id by uzyskać dane z rest api /order/checkout-forms/{checkoutForm_id}

Dziękuję za każdą pomoc.

**Comment by PawelTaberski** [comment]
Nie ma obecnie prostej możliwości zmiany numeru transactionsId na numer checkoutForms bądź eventId w REST API. Obecnie jest jeden zasób do mapowania dealId na lineItemId i odwrotnie. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2018-10-09_mapowanie_lineitemid_dealid/).
Natomiast więcej o tym jak obsługiwać zamówienia w REST API znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by neldh** [comment]
W skrócie: Musisz pobrać sobie wszystkie checkout formy. Możesz uzyc   get /order/checkout-forms, ale po użyciu filtra boughtAt.lte/gte to ci nie zwroci checkout formow dla ktorych byla jedynie doplata w zadanym przedziale czasu. Jeśli potrzebujesz i tego, to dodatkowo należy uzyć  get /order/events a potem pobierac checkout formy już po id przez  get /order/checkout-forms/{id}. Podczas calego tego procesu gromadzisz lineItems.id dla kolejnych checkout formów i następnie używasz końcowki do mapowania dealId na lineItemId. W ten sposob uzyskasz numery dealId dla kolejnych checkout formow.
Teraz musisz przy pomocy dealId dokopać się po WEBAPI do danych id z którymi chcesz polączyć checkout formy.

Masa roboty - wiem. Zupelnie nieergonomiczne - wiem. Ale zostalo już to wielokrotnie wypomniane na github.com/allegro/allegro-api/issues i poki co nie ma innego wyjscia.
