### ISSUE TITLE
REST API - Skąd wziąć seller.id ?

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#156]

**Comment by MaciejPotepa** [comment]
seller.id to nic innego niż identyfikator konta użytkownika. 

Jak będziesz zalogowany na docelowym koncie to wpisz adres https://allegro.pl/login/user i dostaniesz ID. To jeden z wielu sposobów.

**Comment by gustawdaniel** [comment]
Inna metoda to jeśli masz nazwę użytkownika, np: `gustawdaniel` to po wejściu na stronę

> https://allegro.pl.allegrosandbox.pl/uzytkownik/gustawdaniel?order=m

Po kliknięciu `Oceny i komentarze` zostaniesz przekierowany na: 

> https://allegro.pl.allegrosandbox.pl/uzytkownik/43967138/oceny

Gdzie `43967138` jest wartością `seller.id`.

Mimo to, wciąż pozostaje otwarte pytanie o to jak wydobyć `seller.id` z `API REST`.

W moim przypadku mam JWT token. Po rozkodowaniu payloadu z JWT dostałem taki obiekt:

```
{
  "exp": 1524342679,
  "user_name": "21553921",
  "jti": "9bb7fd0c-9429-434e-9ade-091fc6f87d30",
  "client_id": "______uuid_of_client_id_______",
  "scope": [
    "allegro_api"
  ]
}
```

Proponuję doprecyzować pytanie @adampajak do formy:

# Jak w REST API przejść od `user_name` z JWT z `access_token` do `seller.id`?

**Comment by kormichu** [comment]
Co prawda nie wiem jak przejść z samego user_name do seller.id w API, ale wiem jak w prosty sposób mając access token dostać id zalogowanego. Niestety wymaga to połączenia z WebAPI:

Zamieniasz access token na session id:
https://allegro.pl/webapi/documentation.php/show/id,101582

Pobierasz informacje o userId/seller.id:
https://allegro.pl/webapi/documentation.php/show/id,102#method-output

**Comment by adampajak** [comment]
@gustawdaniel  Nie zgadzam się z tym że numer pokazujący się w URLu po wejściu na Oceny i komentarze to seller.Id. W moim przypadku zadziałał userId zwrócony w response z doLoginWithAccessToken i wykorzystany jako seller.Id w metodach REST

**Comment by TimothyKoval** [comment]
A nie możecie zdekodować samego tokenu? ID użytkownika tam jest z tego co pamiętam.

**Comment by marcinc81** [comment]
Najłatwiej `seller.id` wyjąć z tokena przez regex. To może się przydać każdemu: 
```
preg_match('/\"user_name\":\"([0-9]+)\"/', base64_decode($access_token), $matches);
$seller_id = $matches[1];
```

**Comment by malbrandt** [comment]
A skąd można wziąć `username` (nazwa użytkownika allegro)?

I gdzie klient (użytkownik Allegro) może sprawdzić `seller.id` (numeryczne)? 

Chcę umożliwić dodawanie kilku kont Allegro w celu synchronizacji zamówień i chciałbym je w prosty sposób rozróżniać, aby klienci wiedzieli które jest które - najlepiej po `username`. Widziałem, że konkurencyjna strona rozróżnia konta po `username` ale nie wiem, skąd mogę to wziąć.

Czy jest jakiś odpowiednik endpointa `https://allegro.pl/login/user` w REST API?
Lub czy można jakoś użyć tego endpointa z innej strony niż allegro.pl będącym zalogowanym użytkownikiem (oznaczałoby to konieczność złamania polityki `Access-Control-Allow-Origin`).
