### ISSUE TITLE
Aukcja sklepowa

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1560]
Jaki jest status prac w REST odnośnie "aukcji sklepowej" dostępnej przez SOAP?
Z dokumentacji wynika, że nie jest możliwe wystawienie takiej oferty obecnie.

**Comment by PawelTaberski** [comment]
Jako że już praktycznie nie było różnicy pomiędzy ofertą zwykłą a sklepową zarówno w czasach trwania jak i innych elementach w REST API nie ma już takiego rozgraniczenia. 
Nie wiem, czy dobrze rozumiem Twoje pytanie jeśli chodziło Tobie o coś innego to daj znać.

**Comment by j4r3kb** [comment]
Co z takim scenariuszem:
* mamy aukcję wystawioną przez SOAP jako sklepową, załóżmy że do wyczerpania towaru
* czy będzie możliwość zmiany przez REST lub SOAP na aukcję normalną bez utraty ciągłości trwania
* czy takie aukcje trzeba będzie pozamykać i utworzyć nowe?
