### ISSUE TITLE
Błędy w dokumentacji RestApi

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1561]
Znalazłem nieścisłości w dokumentacji, a mianowicie:

SellerCreateRebateRequestDto{
		benefits*	[Benefit{
		specification*	BenefitSpecification{
		type*	string
 	
			}
 	
				}]
		offerCriteria*	[OfferCriterion{
			type*	string
 	
		}]
 	
		}
Chodzi mi o referencję do „OfferCriterion”, według dokumentacji OfferCriterion zawiera tylko jedno pole „type”,a według przykładu:

{
  "benefits": [
    {
      "specification": {
        "type": "ORDER_FIXED_DISCOUNT",
        "value": {
          "amount": "10",
          "currency": "PLN"
        }
      }
    }
  ],

  "offerCriteria": [
    {
      "type": "CONTAINS_OFFERS",
      "offers": [
        {
          "id": "1122334455",
          "quantity": 2,
          "promotionEntryPoint": true
        },
        {
          "id": "2233445566",
          "quantity": 1,
          "promotionEntryPoint": false
        }
      ]
    }
  ]
}

Powinny być jeszcze inne pola między innymi referencja do „OfferId” gdzie referencję do tego pola ma „OfferCriterium”:

OfferCriterium{
		offers	[
 
			OfferId{
			id	string
			 
			}]
		type	string
		Criteria type: CONTAINS_OFFERS
		Enum:
		[ CONTAINS_OFFERS ]
 	
	}

Oczywiście „OfferId” także nie zawiera wszystkich potrzebnych pól, bo brakuje jeszcze:

„quantity”
„promotionEntryPoint”

To tyle jeśli chodzi o pole „offerCriteria”, teraz jeszcze kolejne pole, a właściwie referencja do „BenefitSpecyfication”

Według dokumentacji zawiera również tylko jedno pole „type”
A brakuje jeszcze sporo:

Pola „value”, które powinno mieć referencję do „Price”
Pola „configuration”, które powinno mieć referencję np.: do „BenefitConfiguration”,
	BenefitConfiguration powinno zawierać pole „percentage”.
Pola „trigger”, które powinno mieć referencję np: do „BenefitTrigger”.
	BenefitTrigger powinno zawierać pola "forEachQuantity" i "discountedNumber"

**Comment by PawelTaberski** [comment]
Dzięki za precyzyjne info jak najbardziej zweryfikujemy to i poprawimy.
