### ISSUE TITLE
Działanie order/checkout-forms

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#1562]
Moje pytanie dotyczy zasobu order/checkout-forms

Sytuacja jest następująca:
-klient dokonuje zamówienia 3 moich przedmiotów, widzę to w zakładce "zamówienia"
https://allegro.pl/seller-orders/

- zasób order/checkout-forms dostarcza mi łącznie 4 inne formularze (o różnych id) dotyczące tegoż zakupu
-wywołując ten sam zasób z każdym z otrzymanych id otrzymuję
```
      ["code"]=>
      string(5) "ERROR"
      ["message"]=>
      string(21) "An error has occurred"
```
- jeden z nich (tym razem najpóźniejszy akurat) zawiera poprawne dane dotyczące zamówienia, które jestem w stanie obsłużyć

Czy to oznacza, że usunęliście poprzednie formularze tworząc kolejny, poprawny ( o nowym id )? Czy dotyczy to ostatniego punktu w sekcji "Ważne" poradnika obsługi zamówień? 

Proszę o informację, czy tak to faktycznie działa. W tym momencie z dystansu wygląda to jakby identyfikator transakcji się ciągle zmieniał, co nie pozwala na jednoznaczne zidentyfikowanie zamówienia.

EDIT: czym dokładnie jest checkoutForm.lineItemId?
Czy jest to całkowicie unikatowy identyfikator, innymi słowy - lineItemId ma tę samą wartość wtedy i tylko wtedy, gdy produkt będzie związany jednym zakupem? Kupując drugi raz to samo wartość ta będze inna, (inny akt zakupowy) dobrze rozumiem?

**Comment by PawelTaberski** [comment]
lineItems jest to unikatowy identyfikator pozycji zamówienia. Także jest on przypisany do danej pozycji zamówienia.
A przypadek jaki opisujesz wygląda jakby user kupił kilka przedmiotów, a następnie opłacił je za jednym razem. Czyli tak jak napisałeś to co oznaczyliśmy jako ważne w poradniku:
"...Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to oznacza, że mamy do czynienia z połączeniem zakupów przez kupującego)..."
Możesz to zbadać właśnie za pośrednictwem lineItem.id tak jak to opisaliśmy powyżej w [naszym poradniku](https://developer.allegro.pl/orders/#01).

**Comment by pokash** [comment]
@PawelTaberski ja mam jednak problem w tym, że API nie zwraca mi wcale danych z formularza. API pokazuje jakby wcale nie istniał... Event zwrócił mi poprawny identyfiaktor. Zakup otrzymał flagę "READY", a checkoutForm nie znajduje formularza po podanym identyfikatorze. Co w takiej sytuacji mam zrobić? Czy to kolejny bug, czy też kłopot leży gdzie indziej? Mam podać ID checkoutForm, aby namierzyć problem?

Pozdrawiam,
Łukasz

**Comment by PawelTaberski** [comment]
@pokash Jak najbardziej podeślij nam proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619): 

- ID checkoutForm
- id bądź login usera na którego masz access token
- i jeśli dasz radę to numer oferty i id bądź login kupującego, którego dotyczy ten zakup. 

Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1562 na GitHub-ie.

**Comment by pokash** [comment]
Witam @PawelTaberski zgłoszenie zostało wysłane. Liczę na szybą odpowiedź, bo jesteśmy teraz trochę zblokowani przenoszeniem obsługi zamówień z WebAPI na RestAPI :)

Pozdrawiam,
Łukasz

**Comment by MartaNowaczyk** [comment]
Witam, 
sprawdziłam i pierwsze dwa checkoutFormy (a i b), które podesłałeś są prawidłowe i powinieneś uzyskać poprawną odpowiedź. Jeśli nadal masz z tym problem podeślij request i response.

Jeśli chodzi o przypadek kupującego z c i d tutaj sprawdzimy co się stało, bo wygląda to na błąd po naszej stronie. Mimo tego, że doszło do sytuacji połączenia dwóch oddzielnych zakupów, nie widzę zdarzenia z nowym checkoutForm.id, a jest taki d3a4a2e1-3f70-11e9-9974-b753d8ba9c82.  Przekazałam do głębszej analizy, do zespołu, który zajmuje się zamówieniami. Jak tylko będę miała jakieś informacje dam znać.

Pozdrawiam.

**Comment by pokash** [comment]
Witam @MartaNowaczyk w a i b rzeczywiście błąd był po mojej stronie :) złą agregację danych miałem w bazie :) Już wszystko działa (a i b) poprawnie mi się pobrały i zapisały. Czekam w takim razie na odpowiedź na problemy z c i d :) Bo może to jednostkowy przypadek, ale wolałbym, żeby jednak później (na wersji produkcyjnej) nie miał miejsca :)

Pozdrawiam,
Łukasz

**Comment by MartaNowaczyk** [comment]
Jasne, jak tylko będę miała jakieś informacje dam znać.

**Comment by MartaNowaczyk** [comment]
@pokash Ten błąd to pojedynczy przypadek z tego co sprawdziliśmy i nie powinien już wystąpić. Niestety nie znajdziesz tego eventu w dzienniku, ale udało nam się dodać dla chckoutFormId d3a4a2e1-3f70-11e9-9974-b753d8ba9c82 status BOUGHT.
