### ISSUE TITLE
Pole handlingTime - aktualizacja ofert

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1563]
Czy można zaktualizować zbiorowo pole **handlingTime** czy trzeba każdą aukcję pojedynczo ?
Jeśli jest taka możliwość to prośba o przykład. Jakie można tam wartości wpisywać.

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości. Wartości jakie możesz podać znajdziesz [w naszym poradniku](https://developer.allegro.pl/sale/#new-offer) w przykładowym requeście.

**Comment by pietrach** [comment]
A w jaki sposób mogę zmienić tą wartość ? Dla każdej aukcji pojedynczo się da ?

**Comment by MartaNowaczyk** [comment]
@pietrach tak możesz według tej instrukcji z naszego poradnika [Edycja pojedynczej oferty](https://developer.allegro.pl/my_offers/#2)

**Comment by pietrach** [comment]
A można ten parametr zmieniać jeśli są oferty sprzedaży w danej aukcji ?

**Comment by MartaNowaczyk** [comment]
Tak, można.
