### ISSUE TITLE
różne ID parametrów kategorii 

### ISSUE THREAD

**Issue by bjatwork** [allegro/allegro-api#1564]
Klient który korzystał z WebApi twierdzi że na RestApi ma pomieszane kolory, ale tylko dla niektórych produktów.  Podaję przykład. 

Dla **451_128** w tej chwili kolor to "szary, srebny", a wcześniej (gdy używaliśmy webApi, 128 był przyporządkowany do koloru "zielony". 

proszę o odpowiedź czy to możliwe, aby w allegro zmieniły się id dla wartości parametrów, czy to błąd w naszym systemie?

**Comment by PawelTaberski** [comment]
O wszystkich zmianach w parametrach informujemy na [dedykowanej stronie](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).
Oczywiście mogą występować różnice między WebAPI a REST API. Prosiłbym o podanie numeru kategorii i nazwy parametru (rozumiem, że to kolor). Sprawdzimy to.

**Comment by Onixarts** [comment]
Czy można poczynić takie założenie, że dla danego parametru, powiedzmy 451, wartość 128 która była w SOAP będzie tym samym parametrem o identyfikatorze 451_128 w REST?

Musimy jakoś zmapować dane użytkowników ze starego API na nowe i nie wiem czy można się oprzeć na tych inentyfikatorach.

**Comment by PawelTaberski** [comment]
@Onixarts id wartości się nie zmieniają, ale  kolejność wartości w słowniku może być różna między WebAPI a REST API. 
@bjatwork Błąd może wynikać z tego że jest to parametr wielokrotnego wyboru i w WebAPI jako wartości wykorzystujemy potęgi 2, w REST API po prostu są to identyfikatory.

**Comment by bjatwork** [comment]
@PawelTaberski chodzi o kategorię  nr 87893 
W rest api webapi przekazywaliśmy dla parametru 451 wartość 128, w rest przekazujemy dla parametru 451 przekazujemy 451_128  i otrzymujemy różne kolory.  
Przy innych cechach wielokrotnego wyboru nie mamy tych problemów, są to jednostkowe przypadki.

**Comment by PawelTaberski** [comment]
@bjatwork Rzeczywiście jest błąd widzę, że wartości w WebAPI są przesunięte o 1 wartość i szary w takim wypadku to 64. Zgłosiłem sprawę do odpowiedniego zespołu, prośba o cierpliwość.

**Comment by mareklemur** [comment]
Potwierdzam błąd. Wystawiła się aukcja nr 8055555392 z kolorem "wielokolorowy", a zdefiniowany jest "inny".

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, prośba o cierpliwość.

**Comment by mareklemur** [comment]
Cierpliwość cierpliwością, ale cały czas wystawiają się aukcje z błędnymi parametrami. Aukcja 8062379804 - kolor zamiast "inny" jest "wielokolorowy" (parametry WEBAPI są przesunięte o jeden względem RESTAPI). A potem kupujący mają pretensje, że wprowadzamy w błąd.

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak proszę dać nam jeszcze trochę czasu.

**Comment by rafalkrupinski** [comment]
Może zaproponuję obejście tego problemu, bo mi też zmieniły się identyfikatory wartości: w ogóle nie przechowuję tych identyfikatorów, pobieram codziennie i tłumaczę z opisów ('zielony') na identyfikatory. Oczywiście będzie działać dopóki allegro nie zmieni zielonego na szmaragdowy ;)
