### ISSUE TITLE
[REST] Problem z zakonczeniem aukcji.

### ISSUE THREAD

**Issue by Filip4223** [allegro/allegro-api#1565]
Witam, mam problem z REST API Allegro, ponieważ nie działa mi kod na zakończenie aukcji na Allegro. Cały czas pokazuje mi się: `{"id":"638bc539-8b30-4f7d-8b44-a208bafb396f","taskCount":{"total":0,"success":0,"failed":0}}`

Oto mój kod:
gen_uuid generuje unique_id w wersji v4, natomiast $auction przechowuje id aukcji.

`    function finishAuction($auction) {
        try {
            $c = curl_init();

            $token = getNewToken();

            $headers = array();
            $headers[] = sprintf('Authorization: Bearer %s', $token);
            $headers[] = 'Accept: application/vnd.allegro.public.v1+json';
            $headers[] = 'Content-type: application/vnd.allegro.public.v1+json';

            echo $auction;

            $json = sprintf('  
            {  
               "offerCriteria":[  
                  {  
                     "offers":[  
                        {  
                           "id":"%d"
                        }
                     ],
                     "type":"CONTAINS_OFFERS"
                  }
               ],
               "publication":{  
                  "action":"END"
               }
            }
            ', $auction);

            curl_setopt($c, CURLOPT_URL, sprintf("https://api.allegro.pl/sale/offer-publication-commands/%s", gen_uuid()));
            curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($c, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($c, CURLOPT_CUSTOMREQUEST, "PUT");
            curl_setopt($c, CURLOPT_POSTFIELDS, $json);

            $response = curl_exec($c);
            echo $response;

        } catch(Exception $e) {}
    }`

**Comment by PawelTaberski** [comment]
To dobra odpowiedź, zasób przy publikacji albo zakończeniu oferty od razu nie wie ile zadań zakończy się powodzeniem, bądź nie, aby sprawdzić status zadania powinieneś skorzystać z jednego z 2 zasobów:
GET na zasobie /sale/offer-publication-commands/{commandId}
GET na zasobie /sale/offer-publication-commands/{commandId}/tasks
Więcej na ten temat znajdziesz w [naszym poradniku.](https://developer.allegro.pl/sale/#step-10-tasks)
