### ISSUE TITLE
Kończenie oferty

### ISSUE THREAD

**Issue by ghost** [allegro/allegro-api#1567]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o sprawdzenie dlaczego wywołanie poniższego kodu nie kończy oferty

[Request]
PUT /sale/offer-publication-commands/1bb0f4b0-7fae-464b-8804-dcdb8157b75a
{"publication":{"action":"END","scheduledFor":null},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6206296022"}]}]}

[Response]
201 Created
{"id":"1bb0f4b0-7fae-464b-8804-dcdb8157b75a","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by PawelTaberski** [comment]
Powiedz mi proszę jaki otrzymujesz respons w zasobie /sale/offer-publication-commands/{commandId}/tasks
Więcej na temat sprawdzenia statusu zadania znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-10-tasks).

**Comment by michcio19923** [comment]
{"tasks":[{"offer":{"id":"6206296022"},"message":"","status":"SUCCESS","scheduledAt":"2019-04-27T19:24:32.773Z","finishedAt":"2019-04-27T19:24:36.999Z","field":"publication","errors":[]}]}

**Comment by michcio19923** [comment]
Miała już status zakończona

**Comment by michcio19923** [comment]
Przykład innej umowy aktywnej obecnie
https://allegro.pl.allegrosandbox.pl/oferta/adapter-dla-psa-6206296192

PUT /sale/offer-publication-commands/cab4fefb-f57c-43b3-9e13-779773f96777
{"publication":{"action":"END","scheduledFor":null},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6206296192"}]}]}

201 Created
{"id":"cab4fefb-f57c-43b3-9e13-779773f96777","taskCount":{"total":0,"success":0,"failed":0}}

Taski:
GET /sale/offer-publication-commands/cab4fefb-f57c-43b3-9e13-779773f96777/tasks

{"tasks":[{"offer":{"id":"6206296192"},"message":"","status":"SUCCESS","scheduledAt":"2019-04-28T14:29:33.272Z","finishedAt":"2019-04-28T14:29:38.074Z","field":"publication","errors":[]}]}

**Comment by PawelTaberski** [comment]
Przetestowałem i niby wszystko działa poprawnie, ale widzę w Twojej ofercie że jest jakiś problem. Sprawę przekazałem do odpowiedniego zespołu. Prośba o cierpliwość.

**Comment by PawelTaberski** [comment]
@michcio19923 Sprawdziliśmy i zarówno aktywacja jak i zakończenie oferty wysłałeś pod tym samym ID komendy (UUID-em), dlatego została przetworzona tylko aktywacja.

**Comment by michcio19923** [comment]
Zakończenie działa, lecz teraz wznowienie już nie, przesyłam też nowy UUID dla wznowienia (inne niż dla zakończenia)

PUT /sale/offer-publication-commands/711713ae-510e-4d7d-816d-3f508761dac7
{"publication":{"action":"ACTIVATE","scheduledFor":null},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6206299925"}]}]}

{"id":"711713ae-510e-4d7d-816d-3f508761dac7","taskCount":{"total":0,"success":0,"failed":0}}


W jaki sposób mogę sprawdzić aktualny stan oferty? Widzę, że pobierając draft w sekcji publication -> status jest aktualny stan oferty

**Comment by MartaNowaczyk** [comment]
Jaki otrzymujesz respons dla tego UUIDa korzystając z GET /sale/offer-publication-commands/{commandId}/tasks?

**Comment by michcio19923** [comment]
GET /sale/offer-publication-commands/711713ae-510e-4d7d-816d-3f508761dac7/tasks

{"tasks":[{"offer":{"id":"6206299925"},"message":"Could not change offer publication status. You cannot activate an ended offer.","status":"FAIL","scheduledAt":"2019-05-03T13:38:01.188Z","finishedAt":"2019-05-03T13:38:01.965Z","field":"publication","errors":[]}]}

Drugie pytanie, w jaki sposób mogę sprawdzić aktualny stan oferty?

**Comment by michcio19923** [comment]
@MartaNowaczyk coś wiadomo?

**Comment by MartaNowaczyk** [comment]
Oferta, którą podałeś to licytacja. Licytacji nie wznowisz w ten sposób. Trzeba ją wystawić jeszcze raz, czyli pobrać szczegóły GET /sale/offers/6206299925 (tam też zobaczysz jej aktualny stan) i potem skorzystać z POST i PUT. Więcej w naszym [poradniku](https://developer.allegro.pl/sale/).
