### ISSUE TITLE
allegrosandbox

### ISSUE THREAD

**Issue by kammario** [allegro/allegro-api#1568]
Witam
w środowisku testowym dostaje takie info przy próbie wystawienia przedmiotu. 

"Nie możesz jeszcze sprzedawać.
Poczekaj na weryfikację swoich danych. O jej wyniku poinformujemy Cię e-mailem w ciągu 3 dni roboczych"

A przy probie stworzenia draftu oferty:
object(stdClass)#1 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#2 (5) { ["code"]=> string(9) "FORBIDDEN" ["message"]=> string(9) "Forbidden" ["details"]=> NULL ["path"]=> string(12) "/sale/offers" ["userMessage"]=> NULL } } }

Pojawiające sie błędy przy tworzeniu draftu oferty spowodowane sa tym, ze konto testowe nie jest w pełni aktywne?

**Comment by Maczuga** [comment]
Najprościej wg. mnie to zaloguj się na konto sandboxa i wejdź tam na stronę, gdzie wystawia się oferty. Na samej górze będziesz miał podobny komunikat z linkiem do dalszej aktywacji / weryfikacji. Uzupełnisz dane i powinieneś mieć w zasadzie od razu (tak było w moim przypadku) możliwość wystawiania ofert zarówno przez API jak i stronę.

**Comment by MartaNowaczyk** [comment]
@kammario jeśli masz problem z aktywacją podaj swój login na sandboxie. Sprawdzimy jak to wygląda na tym koncie.

**Comment by kammario** [comment]
Witam
 
login:siwy_28
 
Pozdrawiam
Mariusz
 
 
 
 
W dniu 2019-04-29 09:48:24 użytkownik MartaNowaczyk <notifications@github.com> napisał:
@kammario jeśli masz problem z aktywacją podaj swój login na sandboxie. Sprawdzimy jak to wygląda na tym koncie.

**Comment by MartaNowaczyk** [comment]
konto jest aktywne. Po twojej stronie pozostało aktywować konto firma. Skorzystaj z zakładki Moje konto.

**Comment by kammario** [comment]
Przy probie stworzenia draftu oferty komunikat jak poniżej, 

object(stdClass)#1 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#2 (5) { ["code"]=> string(9) "FORBIDDEN" ["message"]=> string(9) "Forbidden" ["details"]=> NULL ["path"]=> string(12) "/sale/offers" ["userMessage"]=> NULL } } }


a tak wyglada funkcja

function getDane($token) {

	
	$data = array("name" => "Oferta testowa", "category" => array ("id" => "257691" ) );
	$postdata = json_encode($data);	


    	$getCategoriesUrl = "https://api.allegro.pl.allegrosandbox.pl/sale/offers";

    	$ch = curl_init($getCategoriesUrl);
   	curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Content-Type: application/vnd.allegro.public.v1+json",
                 "Accept: application/vnd.allegro.public.v1+json"
   	]);
   	
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
	curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);
	

	
	$DaneResult = curl_exec($ch);
	curl_close($ch);

	$daneList = json_decode($DaneResult);
	return $daneList;
}

**Comment by kammario** [comment]
W zakładce aktywacja konta pojawia się tylko taki komunikat:

Status konta
Nieaktywne - trwa weryfikacja Twoich danych.

Uzyskaj dostęp do wszystkich funkcji Allegro w kilka chwil.

**Comment by MartaNowaczyk** [comment]
z tego co widzę konto powinno być już aktywne. Podeślesz zrzut tego komunikatu i status HTTP tego błędu, który dostajesz?

**Comment by kammario** [comment]
![image](https://user-images.githubusercontent.com/50085594/56946612-df42b480-6b2a-11e9-9c10-749a4aa366b5.png)

**Comment by MartaNowaczyk** [comment]
Dziękuję za zrzut. Przekazałam sprawę do zespołu, który zajmuje się tym obszarem. 
Proszę jeszcze byś sprawdził czy możesz wystawić oferty ręcznie, bezpośrednio na sandboxie i podesłał status http jaki dostajesz przy pojawiającym się błędzie.

**Comment by kammario** [comment]
http - 403

**Comment by MartaNowaczyk** [comment]
@kammario wygląda na to, że próbujesz pobrać dane z innego konta niż jesteś uwierzytelniony. 
Z jakiego [sposobu autoryzacji](https://developer.allegro.pl/auth/) korzystasz?

**Comment by kammario** [comment]
Korzystam  z REST API, próbuje pobrać dane z tego samego konta na jakie jestem uwierzytelniony.

**Comment by kammario** [comment]
Dzięki już jest ok. Nie autoryzowałem użytkownika, korzystałem z tokena dającego dostęp tylko do informacji ogólnie dostępnych.

**Comment by MartaNowaczyk** [comment]
@kammario dziękuję za informację.
