### ISSUE TITLE
Błąd w doBidItem - could not reserve stock for offer

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#1571]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

W losowych momentach zamiast złożyć ofertę (doBidItem) pojawia się błąd:
could not reserve stock for offer 8025923820 and stock c00a1ea4-f565-4d89-9ac5-1dfc933d50ba

<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/xmlschema" xmlns:xsi="http://www.w3.org/2001/xmlschema-instance" soap-env:encodingstyle="http://schemas.xmlsoap.org/soap/encoding/"><soap-env:body><soap-env:fault><faultcode>err_cannot_bid_item</faultcode><faultstring>could not reserve stock for offer 8025923820 and stock c00a1ea4-f565-4d89-9ac5-1dfc933d50ba</faultstring></soap-env:fault></soap-env:body></soap-env:envelope>

**Comment by mariobros6** [comment]
I jeszcze jeden rodzaj błędu przy doBidItem:

{"errors":[{"code":"error","message":"an error has occurred","details":null,"path":"/services/uploader.php","usermessage":null}]}

**Comment by PawelTaberski** [comment]
Przetestowałem i funkcja działa poprawnie. Widzę, że oferta zakończyła się w niedzielę, a kiedy wywoływałeś to zapytanie?

**Comment by mariobros6** [comment]
Tak jak napisałem, błąd jest losowy.
Oczywiście wywołanie metody było w czasie, gdy aukcja trwała.

**Comment by mariobros6** [comment]
Polecam testować w godzinach szczytu (np. ok. godz. 20:00, 20:15, 20:30, 21:00)

**Comment by PawelTaberski** [comment]
A czy znasz może konkretnego timestampa, kiedy otrzymałeś taki błąd?

**Comment by mariobros6** [comment]
17:47:26 1556466446
Paczka wywołania:

<ns1:dobiditem xmlns:ns1="urn:allegrowebapi" soap-env:encodingstyle="http://schemas.xmlsoap.org/soap/encoding/">
                <session-handle type="xsd:string">9094083589953a24b75e2ad5be45bbf1b59b8a6d846f2f//03_1</session-handle>
                <bid-it-id type="xsd:long">8025923820</bid-it-id>
                <bid-user-price type="xsd:float">77.99</bid-user-price>
                <bid-quantity type="xsd:long">1</bid-quantity>
                
                
                </ns1:dobiditem>

**Comment by mariobros6** [comment]
Dzisiaj o 21 doszedł jeszcze jeden typ błędu przy doBidItem:

<soap-env:envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/xmlschema" xmlns:xsi="http://www.w3.org/2001/xmlschema-instance" soap-env:encodingstyle="http://schemas.xmlsoap.org/soap/encoding/"><soap-env:body><soap-env:fault><faultcode>err_webapi_not_avail</faultcode><faultstring/></soap-env:fault></soap-env:body></soap-env:envelope>

**Comment by PawelTaberski** [comment]
@mariobros6 Dzięki za informacje, podeślij proszę jeszcze tylko klucz z jakiego korzystasz, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), i login usera. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1571 na GitHub-ie.
