### ISSUE TITLE
Problem z autryzacją na IE10

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#1573]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [] inny

:beetle: **Opis**

Wchodząc na stronę
https://apps.developer.allegro.pl/
z poziomu InternetExplorer 10 otrzymujemy błąd - strona się nie ładuje. Strona działa tylko na IE 11, którego nie możemy na naszym serwerze zainstalować bo zgodnie z :
https://social.technet.microsoft.com/Forums/ie/en-US/193b638a-2e49-4357-9885-57e003298b60/can-i-get-internet-explorer-11-for-windows-server-2012-
w tej wersji nie można zainstalować ie11 a taki mamy i świadczymy na nim usługi zdalnego pulpitu i nasza aplikacja jest na nim udostępniana.

Z powyższych powodów klienci nie mogą samodzielnie generować sobie tokenów autoryzacyjnych w naszej aplikacji w prosty sposób.
Czy jest szansa na jakąś poprawkę by strona działała poprawnie również na IE10?

Poza tym jakiś bug na stornie powoduje, że okienko popup:
"Droga Klientko/Drogi Kliencie,
Możemy lepiej dopasować treści reklamowe do Twoich potrzeb. Potrzebujemy na to Twojej zgody...."
rozjeżdza się przy zmianie rozmiarów głównego okna IE11.

**Comment by PawelTaberski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu, zweryfikujemy to i poprawimy. Prośba o cierpliwość.

**Comment by rtnet-pl** [comment]
IE10 nie obsługuje domyślnie TLS 1.2.

**Comment by p3ch** [comment]
Obsługa TLS 1.0 została wyłączona na Allegro 30 czerwca 
https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/protokol-tls-w-twojej-przegladarce-z8Dmgz12xTA

Czy próbowałeś włączyć TLS 1.1 ?
https://warwick.ac.uk/services/its/servicessupport/web/sign-on/help/tls1-eol/ie/

**Comment by WGRINGO** [comment]
Ustawienia IE10 są takie jak w przesłanej instrukcji:
SSL 2.0, 3.0 - wyłączone
TLS 1.0, 1.1, 1.2 - włączone
Niestety dalej nie działa :(

**Comment by rtnet-pl** [comment]
TLS 1.0 i 1.1 też wyłącz.

**Comment by WGRINGO** [comment]
Nie pomogło. Mam wrażenie, że problemem są javaskrypty chociaż online javascript tester pokazuje, że są włączone.

**Comment by rtnet-pl** [comment]
A tutaj w sekcji protocols na pewno jest TLS 1.2? https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by WGRINGO** [comment]
Tak jest :

SSL/TLS Capabilities of Your Browser

User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)

Protocol Support

Your user agent has good protocol support.

Your user agent supports TLS 1.2, which is recommended protocol version at the moment.

**Comment by PawelTaberski** [comment]
@WGRINGO  W Allegro nie wspieramy przeglądarki IE 10, więc możliwe, że niektóre strony nie będą pod nią działały.

Natomiast jeśli chodzi o stronę https://apps.developer.allegro.pl to jest to strona przeznaczona dla integratorów. Integrator może z jej poziomu zarejestrować swoją aplikację i otrzymać dla niej unikatowe clientId i secret, które potem są wykorzystywane do pozyskiwania tokenów dostępowych dla użytkowników. Państwa klienci nie powinni korzystać z tej strony, nie jest ona dla nich przewidziana. Ponadto operację rejestracji aplikacji wykonuje się raz i można ją wykonać z dowolnego komputera, z dowolnej przeglądarki. Prosimy zweryfikować proces korzystania ze strony apps.developer.allegro.pl.
