### ISSUE TITLE
WebApi doFinishItem

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1574]
Czy jest jakiś problem z metodą doFinishItem? Dostaję taki response:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doFinishItemsResponse><ns1:finishItemsSucceed/><ns1:finishItemsFailed><ns1:item><ns1:finishItemId>8xxxxxxxx9</ns1:finishItemId><ns1:finishErrorCode>ERR_WEBAPI_NOT_AVAIL</ns1:finishErrorCode><ns1:finishErrorMessage>W tej chwili nie można skorzystać z Allegro API! Proszę spróbować później!</ns1:finishErrorMessage></ns1:item></ns1:finishItemsFailed></ns1:doFinishItemsResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda działa prawidłowo, podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) numer oferty z jaką masz problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1574 na GitHub-ie.

**Comment by lukada4100** [comment]
Wydaje mi się, że problem zaczął się około 24.04. Od tego czasu mniej więcej co czwarte wywołanie metody kończy się błędem. Dotyczy chyba konkretnych ofert, bo jeśli mają się zamknąć, zamykają się od razu, a jeśli nie, nawet zapętlenie i wielokrotne wywoływanie metody nie pomaga.
Nie mam pod ręką gotowego przykładu. Pracuję na bazie produkcyjnej i nie mam aż tak dużo ofert do zamknięcia, a tą ostatnią problematyczną zamknąłem w panelu. 
Jak coś mi wpadnie to podeślę.

**Comment by szymon-convertis** [comment]
Mamy ten sam problem z tym, że z funkcją doFinishItems. Przesłałem numery ofert przez formularz kontaktowy. Proszę o szybką odpowiedź.

**Comment by MartaNowaczyk** [comment]
@szymon-convertis dostajesz dokładnie ten sam błąd co lukada4100?

**Comment by MartaNowaczyk** [comment]
zgłosiłam problem do odpowiedniego zespołu.

**Comment by szymon-convertis** [comment]
tak, problem "magicznie" zniknął wczoraj o godz 21:30 a o 21:50 otrzymałem odpowiedź z formularza kontaktowego z prośbą o przesłanie XMLi z requestami i responsami. Przypadek czy coś zostało poprawione lub zresetowane?

**Comment by pawelwitkowicz** [comment]
Mamy ten sam problem z funkcją doFinishItems.
Przesłałem numery ofert przez formularz kontaktowy oraz email.
Obsługuje 3 rózne konta i tylko na jednym jest taki problem z API.
