### ISSUE TITLE
Błąd doGetMySoldItems

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#1577]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Metoda doGetMySoldItems nie zwraca danych dla sprzedanej oferty 8030994161
natomiast dane oferty są zwracane w metodzie doGetMyNotSoldItems.

W załączeniu request / response dla obydwóch metod

[blad.zip](https://github.com/allegro/allegro-api/files/3131296/blad.zip)

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście wygląda to na jakiś błąd, sprawę przekazałem do odpowiedniego zespołu, prośba o cierpliwość.

**Comment by joe1d83** [comment]
Witam ponownie,
czy już coś wiadomo w sprawie tego błędu ?

Problem występuje przy coraz większej liczbie ofert co uniemożliwia obsługę zamówień.

**Comment by MartaNowaczyk** [comment]
Weryfikacja trwa. Proszę o jeszcze trochę cierpliwości.

**Comment by joe1d83** [comment]
Witam,

w/w metody periodycznie zwracają błąd **Internal system error** a teraz jeszcze i 
metoda **doGetPostBuyData** zaczeła zwracać błąd **Internal system error**

w załączeniu request i response **doGetPostBuyData**
[reqres_doGetPostBuyData.zip](https://github.com/allegro/allegro-api/files/3146806/reqres_doGetPostBuyData.zip)

**Comment by MartaNowaczyk** [comment]
Dziękuję za kolejne informacje. Jak uda nam się coś ustalić dam znać.

**Comment by MartaNowaczyk** [comment]
@joe1d83 oferta 8030994161 poprawiona. Kwestie Interna system error wyjaśniamy globalnie.

**Comment by joe1d83** [comment]
Witam,

dziękuję za informacje, 
jednak błąd nadal występuje przy wielu innych ofertach np:
8064682981
8064696588
8064696870
8064697669
8064700010
8064700967
8064702560
8064702831
8064715138

**Comment by MartaNowaczyk** [comment]
@joe1d83 rozwiązanie jest w trakcie przygotowań, także na ten moment poprosiłam o poprawę sytuacji dla podanych przez ciebie ofert.

**Comment by MartaNowaczyk** [comment]
@joe1d83 sprawdź proszę czy problem ustąpił.

**Comment by joe1d83** [comment]
Dziękuję, na tą chwilę mam obejście problemu także proszę się nie przejmować w/w
ofertami, podałem je tylko dla przykładu.
Tylko bardzo proszę o informacje zwrotną jak już wszystko zostanie naprawione z metodą doGetMySoldItems

**Comment by MartaNowaczyk** [comment]
Pierwsze poprawki poszły, dlatego prosiłam o sprawdzenie czy już działa :)

**Comment by joe1d83** [comment]
8064715138 - problem nadal występuje

**Comment by Uriziel01** [comment]
Niestety problem występuje także u nas (dość masowo).
Czy wiemy cokolwiek o postępach prac nad poprawką? Jest to ogromny problem bo klient zaczął ponownie wystawiać przedmioty zwrócone przez metodę `doGetMyNotSoldItems` po czym okazało się że są to tak naprawdę sprzedane już przedmioty, wygeneruje to bardzo szybko falę negatywnych komentarzy i straty finansowe.

**Comment by MartaNowaczyk** [comment]
@Uriziel01 posatram się nadać temu większy priorytet.

**Comment by MartaNowaczyk** [comment]
@Uriziel01 @joe1d83 Mamy przygotowaną poprawkę, czeka na wdrożenie. Staramy się by dzisiaj jeszcze weszła.

**Comment by joe1d83** [comment]
@Uriziel01 Jako szybkie rozwiązanie proponuję weryfikować każdą ofertę która zostanie zwrócona "pomyślnie" przez metodę `doGetMyNotSoldItems` za pomocą metody `doGetPostBuyData`. Jeżeli `doGetPostBuyData` zwróci dane, oferta została sprzedana.

**Comment by Uriziel01** [comment]
@joe1d83 podobne rozwiązanie tymczasowe właśnie wdrożyliśmy, nie chcieliśmy czekać na fix od serwisu (który też może dzisiaj nie wejść na produkcję), problem w tym że problem zauważyliśmy po jakimś czasie więc prawdopodobnie ponownie pojawi się fala negatywnych komentarzy i ocen bez naszej winy. No cóż.

**Comment by MartaNowaczyk** [comment]
Poprawkę wdrożyliśmy w piątek, teraz powinno być ok.

**Comment by Uriziel01** [comment]
Jeszcze w sobotę rano widziałem powyższy błąd dla jednej z aukcji ale teraz wszystko wydaje się poprawione więc z naszej strony uznajemy błąd za poprawiony.

**Comment by MartaNowaczyk** [comment]
@Uriziel01 Dziękuję za informację.
