### ISSUE TITLE
[REST] - Autoryzacja / od dzisiaj mamy "zasięg" ?

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1578]
Czemu nikt tu nawet nie wspomni, że zaszła taka zmiana ?
`Array
(
    [exp] => 1564408802
    [user_name] => 123456789
    [jti] => 21956c68-...
    [client_id] => 0c14e...
    [scope] => Array
        (
            [0] => allegro_api
        )

    [ati] => 94165b35-...
)`

**Comment by PawelTaberski** [comment]
To pole jest od zawsze, upewniłem się jeszcze w odpowiednim zespole i otrzymałem informacje, że niedawno występował chwilowy problem i to pole nie było zwracane. Teraz już powróciło.

**Comment by FromAnyHole** [comment]
@PawelTaberski - he, he... Pole było od zawsze, ale od zawsze PUSTE !
Od dzisiaj jest zmiana i propagujecie we wszystkich tokenach wartość typu (string) === 'allegro_api'

**Comment by rafalkrupinski** [comment]
Żeby to była jedyna aka cicha zmiana...

https://github.com/mattesilver/allegro-swagger
