### ISSUE TITLE
 modification should contain exactly 1 element

### ISSUE THREAD

**Issue by zherelevich** [allegro/allegro-api#1579]
Hello! I'm trying sent request PUT /sale/offer-modification-commands/20f70da5-470e-42f1-b2f9-ad501a92cacfstd
{"modification":{"changeType":"FIXED","value":10},"offerCriteria":[{"offers":[{"id":"7924756366"},{"id":"7920594681"},{"id":"7920620845"},{"id":"7920646366"}],"type":"CONTAINS_OFFERS"}]}

RESPONSE
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => VALIDATION_ERROR [message] => modification should contain exactly 1 element [details] => Invalid value: ModificationDto{additionalServicesGroup=null, afterSalesServiceConditions=null, delivery=null, promotion=null, sizeTable=null, payments=null} [path] => modification [userMessage] => modification should contain exactly 1 element ) ) )

**Comment by MartaNowaczyk** [comment]
It's a bad endpoint. To change quantity try call  PUT /sale/offer-quantity-change-commands/{commandId}. More [here](https://developer.allegro.pl/en/my_offers/#3g).
