### ISSUE TITLE
[REST] 409 CONFLICT

### ISSUE THREAD

**Issue by KluseG** [allegro/allegro-api#1580]
Witam.

Chciałbym zapytać jak reagować na błąd 409: Conflict. Brak w odpowiedzi od serwera jakichkolwiek informacji o błędzie. Błąd zwracany jest przy okazji aktualizacji draftu. Co może być przyczyną wystąpienia takiego błędu?

Pozdrawiam!

**Comment by MartaNowaczyk** [comment]
Sprawdź czy czasami nie próbujesz zrobić PUTa ze starymi danymi. Najlepiej jakbyś podesłał nr oferty i trace-id.
