### ISSUE TITLE
Błędy: doGetTransactionsIDs, doGetPostBuyData, doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by runny10** [allegro/allegro-api#1583]
Występuje problem: 
 - [x ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

od 1 maja 2019 pojawiają się błędy przy imporcie zamówień poprzez system shopgold. zamówienia są importowane częściowo, większość z nich jednak wcale nie jest importowana.

błędy mają komunikaty: 

https://i.imgur.com/jvHtC2J.png
https://i.imgur.com/2O6Aljt.png
https://i.imgur.com/f1AsvoV.png

suport shopgold poinformował mnie, że jest to błąd po stronie webapi allegro.

**Comment by MartaNowaczyk** [comment]
Podeślij proszę paczki XML z responsem i requestem do weryfikacji przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1583

**Comment by MartaNowaczyk** [comment]
Potrzebowałabym jeszcze klucza webAPI i listę metod, których to dotyczy. Jeśli można podeślij proszę te dane przez formularz.

**Comment by runny10** [comment]
Witam, jeżeli chodzi o plik xml z request i response to ten system tego
nie generuje, tak się dowiedziałem od suportu oprogramowania shopgold.  

klucz webapi: a3f0f653903e449f967f743058a96c1d 

pozdrawiam
Tomasz Nguyen
hrocks.pl 

W dniu 2019-05-07 07:38, MartaNowaczyk napisał(a):

> Potrzebowałabym jeszcze klucza webAPI i listę metod, których to dotyczy. Jeśli można podeślij proszę te dane przez formularz. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/allegro/allegro-api/issues/1583#issuecomment-489915640
[2]

**Comment by MartaNowaczyk** [comment]
czy problem jeszcze występuje?

**Comment by runny10** [comment]
Witam, podczas próby pobrania informacji o aukcjach wyskakuje teraz błąd: https://i.imgur.com/YLnABxB.png

pomimo, iż wszystkie aukcje są aktywne

**Comment by MartaNowaczyk** [comment]
Podaj proszę dla jakiej metody i dla jakiej oferty występuje ten błąd.

**Comment by rafalkrupinski** [comment]
Swoją drogą ciekawe, że integrator, który bierze pieniądze za oprogramowanie wysyłała swoich klientów, żeby zgłaszali błędy do Allegro. Przecież to oni dysponują wszystkimi danymi na poziomie komunikacji API a nie klient. Czyżby Allegro nie przyjmowało zgłoszeń błędów od integratorów?
