### ISSUE TITLE
Invalid device code po wpisaniu kodu na stronie

### ISSUE THREAD

**Issue by nediam** [allegro/allegro-api#1584]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuje zautoryzować aplikacje jako device, robie wszystko tak jak opisano na stronie https://developer.allegro.pl/auth/#DeviceFlow ale po kolei:

Najpierw robie request:
```
curl -X POST \                                                                                                                                              
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic MG.....==' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=0...'
```

jako response dostaje:
```javascript
{"device_code":"6E....","expires_in":3600,"user_code":"l...","interval":5,"verification_uri":"https://allegro.pl/skojarz-aplikacje","verification_uri_complete":"https://allegro.pl/skojarz-aplikacje?code=l...."}
```

dalej zanim klikne w link (lub przepisze kod) robie request:
```
curl -X POST \                                                                                                                                              
'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=6E...' \
  -H 'Authorization: Basic MG...=='
```

Odpowiedź:
```javascript
{"error":"authorization_pending","error_description":"User has not authorized the device code yet."}
```

Do tej pory wszytko się zgadza, jednak gdy klikne w link https://allegro.pl/skojarz-aplikacje?code=l.... i zrobię ponownie zapytanie takie jak wyżej:
```
curl -X POST \                                                                                                                                              
'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=6E...' \
  -H 'Authorization: Basic MG...=='
```

Nagle zaczynam dostawać:
```javascript
{"error":"invalid_request","error_description":"Invalid device code"}
```

Testowane zarówno na środowisku sandbox jak i produkcyjnym.

Pomysły co robię źle?

**Comment by MartaNowaczyk** [comment]
@nediam podeślij proszę pełne curle przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1584 sprawdzimy w czym problem.

**Comment by nediam** [comment]
@MartaNowaczyk dziękuję za odpowiedz, okazuje się że problem był tylko w majówkę ;) Automagicznie zaczęło działać dobrze, wiec zamykam ticket. ;)
