### ISSUE TITLE
WEBAPI zwraca błędny kod UTF w opisie oferty

### ISSUE THREAD

**Issue by rafalkrupinski** [allegro/allegro-api#1585]
Występuje problem:
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym

do_get_items_info(itemIdArray=[8071505963], getDesc=1)

zwraca niepoprawnie zakodowany ciąg bajtów, który nie daje się sparsować jako UTF.
Ten sam problem dla tej oferty występuje w interfejsie allegro.pl

<img width="709" alt="Screenshot 2019-05-04 at 22 19 30" src="https://user-images.githubusercontent.com/3732079/57184468-5a55f300-6ebc-11e9-9030-f49bdf6482f1.png">

**Comment by MartaNowaczyk** [comment]
@rafalkrupinski zweryfikujemy opisaną sytuację. Gdy uda nam się coś ustalić dam znać.

**Comment by rafalkrupinski** [comment]
bump

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, prośba o cierpliwość.

**Comment by MartaNowaczyk** [comment]
@rafalkrupinski Poprawiliśmy i klient PHP już nie zwraca błędu. Co do kodowania znaków, to taki opis dostajemy, czyli wygląda na to jakbyś taki opis wklejał wystawiając ofertę.

**Comment by rafalkrupinski** [comment]
@MartaNowaczyk Nie wiem o co chodzi z klientem PHP. Ja mam kod w Pythonie i trudno mi to obejść bo błąd dekodowania znaków jest kilka warstw bibliotek niżej, daleko zanim mój kod dostaje jakiekolwiek dane.

Mój program jedynie wyświetla oferty i w tym momencie zwyczajnie te z błędami są pomijane.
Z mojej perspektywy problem polega na tym, że allegro pozwala na przesłanie niepoprawnej treści podczas wysyłania oferty do portalu.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Takie oferty nie powinny już się pojawiać. Te o których piszesz były dodane przez API i tylko w specyficznych przypadkach taki opis przechodził.
