### ISSUE TITLE
REST przy wystawianiu przedmiotu wymaga parametrów, które nie są wymagane

### ISSUE THREAD

**Issue by techjaw** [allegro/allegro-api#1586]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,
w środowisku testowym wystawiam przedmiot w podanej kategorii;
    [id] => 6206300612
    [name] => test mag żółw łąka
    [category] => Array
        (
            [id] => 258705
        )
Pobierając wymagane parametry uzupełniam je:
Niestety nie przechodzę validacji bo REST każe mi uzupełniać parametry które nie są wymagane
np: 
Assigned valueId  for dictionary parameter 202853 is not found.
Assigned valueId  for dictionary parameter 202713 is not found.
Assigned valueId  for dictionary parameter 202745 is not found.
Assigned valueId  for dictionary parameter 202873 is not found.
Assigned valueId  for dictionary parameter 202757 is not found.
Assigned valueId  for dictionary parameter 202857 is not found.
Assigned valueId  for dictionary parameter 202825 is not found.
Expected numeric parameter value for parameter: Szerokość produktu (mm)(202693).

żaden z tych parametrów nie ma ustawione [required] => 1

Jam mam doprowadzić do pozytywnego przejścia validacji???
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Przetestowałam i nie mam problemu z wystawieniem oferty przez REST API w podanej kategorii bez wymienionych parametrów. Walidacja nie zwróciła błędów, dlatego podeślij proszę swój request i response do weryfikacji.

**Comment by techjaw** [comment]
To inaczej, wystawiam produkt poprzez rest, wypełniam wszystkie parametry obowiązkowe, nie ma problemu ze stworzeniem szkicu ale nie będę w stanie aktywować takiego szkicu. Dla przykładu końcowa kategoria "KAMERY" wymaga stanu i marki, dodatkowo można ustawić rozdzielczość, i wodoszczelność oraz wagę. Jeśli nie wypełnie wagi taki szkic się stworzy ale nie będę go w stanie aktywować przez REST. 

Array
(
    [id] => f61d300e-ae84-4b65-bdf9-cc88b5f4ce4a
    [taskCount] => Array
        (
            [total] => 1
            [success] => 0
            [failed] => 1
        )

) 

wchodząc przez www bez dopisywania czegokolwiek wybieram edytuj szkic i bez problemu aktywuję taki szkic. Jeśli wypełnię wszystkie pola taki szkic się stworzy i będę go mógł aktywować bez problemu.

**Comment by techjaw** [comment]
Widzę 
[validation] => Array
    (
        [errors] => Array
            (
                [0] => Array
                    (
                        [code] => VALIDATION_ERROR
                        [message] => Expected numeric parameter value for parameter: Waga (z opakowaniem)(17448).
                        [details] => 
                        [path] => 
                        [userMessage] => Expected numeric parameter value for parameter: Waga (z opakowaniem)(17448).
                   
Ale dlaczego skoro parametr nie jest obowiązkowy

**Comment by MartaNowaczyk** [comment]
Dziś przetestowałam i bez problemu wystawiłam ofertę bez parametru waga dla category.id=250946

**Comment by techjaw** [comment]
Dobrze, zaraz spróbuję raz jeszcze.

**Comment by techjaw** [comment]
bez wystawionej wagi, category.id=250946
Array
(
    [id] => cf48b236-80dc-4568-8d01-265cb15365e9
    [taskCount] => Array
        (
            [total] => 1
            [success] => 0
            [failed] => 1
        )

)

Dokładnie wszystko to samo co poprzednio ale z dodaną wagą :
Array
(
    [id] => 4264dddb-aee5-4859-b131-539f19a8a404
    [taskCount] => Array
        (
            [total] => 1
            [success] => 1
            [failed] => 0
        )

)

Proszę o pomoc, bo stwierdzenie że u mnie działa trochę jest nie poważne

**Comment by MartaNowaczyk** [comment]
@techjaw niczego nie udało mi się znaleźć. Podeślij proszę pełne curle z responsem i requestem błędnego wywołania bez wagi.

**Comment by techjaw** [comment]
Już sam wyjaśniłem, macie dobry sposób, przetrzymać klienta tydzień może zmięknie.
Dla potomnych:
rest api nie pozwoli uaktywnić aukcji kiedy parametr nieobowiązkowy będzie pusty. Czyli albo dodajemy przykładową wagę z wartością albo w ogóle nie uwzględniamy jej.
