### ISSUE TITLE
[REST API] - załączniki

### ISSUE THREAD

**Issue by masztan** [allegro/allegro-api#1587]
Dodawanie załączników, przypisywanie i tak dalej to wszystko jest opisane w dokumentacji. Gdy przypisze sobie jakieś załączniki, to po pobraniu oferty lista załączników jest w postaci identyfikatorów, np:

```
[attachments] => Array
(
	[0] => stdClass Object
		(
			[id] => 44160600_MANUAL_a7d9408450097a0a1edbf9948be2bf8290587c28b046380dd38e0d12e5789518
		)

	[1] => stdClass Object
		(
			[id] => 44160600_SPECIAL_OFFER_RULES_a7d9408450097a0a1edbf9948be2bf8290587c28b046380dd38e0d12e5789518
		)

)
```

Na jakiej zasadzie można pobrać nazwy tych plików z identyfikatorów?

**Comment by MartaNowaczyk** [comment]
Jeśli pytasz o to, czy jest jakiś zasób, który zwracałby nazwy tych plików, to nie ma takiego.

**Comment by masztan** [comment]
Ale będzie? Bo to bez sensu dodawanie plików do oferty. I jak je mam pokazywać w postaci identyfikatorów? :)

**Comment by MartaNowaczyk** [comment]
Zgłoszę takie zapotrzebowanie do zespołu, który zajmuje się tym obszarem.
