### ISSUE TITLE
Zakończone aukcje i filtrowanie po stanie przedmiotu

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#1588]
Dwa pytania
1. Czy jest w REST Api w ogóle możliwość filtrowania po stanie Nowy/Używany w kontekście zakończonych aukcji? Przykład, chce sprawdzić po jakiej cenie sprzedawał się np., Samsung Galaxy S5000 jako nowy i używany telefon.

Odpytuję /offers/listing&searchMode=CLOSED&category.id=xxx podając jako xxx numer kategorii oraz jako parametr:
parameter.11323=1 (Nowe)
parameter.11323=2 (Uzywane)

i zawsze otrzymuję przedmioty wszystkie. To mi wygląda na błąd REST Api, ponieważ z poziomu Allegro, kiedy wejdę w daną kategorię w zakończonych aukcjach, mogę filtrować przedmioty po stanie.

2. Drugie pytanie, dotyczy tego samego, ale kontekście całego Allegro czyli category.id=0 .  Wpisuję np. "Philips" i chcę sprawdzić w każdej kategorii Allegro w jakich cenach sprzedawał się każdy sprzęt tej firmy jako nowy i jako używany, np. głośniki, słuchawki, kina domowe itd.
Tu nie mam pewności, czy to powinno działać.

**Comment by MartaNowaczyk** [comment]
1. Wszystkie filtry, które są dostępne znajdziesz w strukturze filters po wywołaniu zapytania. Podeślij link do wyszukiwanej przez ciebie listy ofert na allegro.

2. Pamiętaj, że zwracamy tylko listę 6000 ofert w wyszukiwaniu. Bezpieczniej jest zawęzić wyszukiwanie do danej frazy. Jeśli w odpowiedzi w sekcji filters dostaniesz filtry określające stan możesz po nich wyszukać w innym wypadku nie.

**Comment by juhacz** [comment]
Mój link:
/offers/listing?&searchMode=CLOSED&include=+filters&offset=0&limit=100&fallback=false&phrase=bose lifestyle&category.id=10

W filtrach nie widzę filtra stanu przedmiotu, mimo, że strona Allegro umożliwia filtrowanie zakończonych po stanie, a offers/listing jest podobno odpowiednikiem tego co jest dostępne na stronie ....

**Comment by MartaNowaczyk** [comment]
podeślij tak jak prosiłam linka - adres z paska wyszukiwarki ze strony allegro, gdzie masz ustawione wszystkie filtry jakie chcesz uzyskać przez REST API.

**Comment by juhacz** [comment]
Nie mogę podesłać linka, bo  już go nie mogę uzyskać..... Chyba zgłupiałem, albo mam jakąś schizofrenię.
Jak tworzyłem ten wątek 2 dni temu, to DAŁO SIĘ się filtrować dane po stanie przedmiotu, niestety w filtrach zwracanych przez rest api, nie było takiej możliwości, dlatego rozpoczałem ten wątek.
Teraz wchodzę na allegro aby wygenerować ten link i nie da się już filtrować po stanie przedmiotu nawet na allegro.
Dostępne jest rodzaj oferty, zakres cen, lokalizacja, filtrowanie po fakturze i Strefa Marek oraz Super Sprzedawca.

**Comment by MartaNowaczyk** [comment]
dokładnie, dlatego prosiłam o ten link. Może to nie schizofrenia, tylko oferty nie były zakończone ;)
