### ISSUE TITLE
Ustawianie innej firmy wysyłkowej nie chce zadziałać

### ISSUE THREAD

**Issue by sq9atk** [allegro/allegro-api#1589]
Występuje problem: 
 - [*] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Jest jakiś problem z ustawianiem numeru przesyłki dla innej firmy wysyłkowej.
Wysłanie żądania o takich parametrach nie powoduje ustawienia numeru przesyłki:

2019-05-06 10:28:02 CURL https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/38e1ba82-6fd7-11e9-9081-af3d77ca0e6a/shipments
2019-05-06 10:28:02 CURL {"carrierName":"TEST S.A.","waybill":"002342","lineItems":[{"id":"38e1ba80-6fd7-11e9-9081-af3d77ca0e6a"}]}

W odpowiedzi schodzi błąd  {"errors":[{"code":"CarrierIdValidationException","message":"Carrier id cannot be null","path":"carrierId"}]}

Żądanie ustawiające numer przesyłki gdy jako firmę wybieram z listy dostępnych, działa poprawnie. Np. takie:

19-05-06 10:26:39 CURL https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/a199e4d1-6294-11e9-8eba-b1caa90ec834/shipments
2019-05-06 10:26:39 CURL {"carrierId":"POCZTA_POLSKA","waybill":"789678","lineItems":[{"id":"a199bdc0-6294-11e9-8eba-b1caa90ec834"}]}

**Comment by MartaNowaczyk** [comment]
Trzeba ustawić jeszcze "carrierId": "OTHER", tylko w takim przypadku działa dodanie innego przewoźnika w polu "carrierName".

**Comment by sq9atk** [comment]
Faktycznie, nie zauważyłem. Od razu zadziałało. Dziękuję.

**Comment by sq9atk** [comment]
Rozwiązane
