### ISSUE TITLE
Czy w REST API można pobrać wszystkie oferty danego użytkownika?

### ISSUE THREAD

**Issue by gustawdaniel** [allegro/allegro-api#159]
Widzę, w dokumentacji

> https://developer.allegro.pl/documentation/#!/sale-endpoint/getFlatParametersUsingGET_2

że można utworzyć ofertę

```
POST /sale/offers
```

pobrać konkretną ofertę

```
GET /sale/offers/{offerId}
```

Ale potrzebuję po prostu listy aktywnych ofert danego użytkownika, czegoś jak

```
GET /sale/offers
```

który zwrócił by tablicę obiektów takich jak daje `GET /sale/offers/{offerId}` albo chociaż tablicę identyfikatorów ofert.

**Comment by TimothyKoval** [comment]
Możesz skorzystać z endpoint-a `/offers?seller.id=xxx`, musisz jednak mieć na uwadze, że nie jest to "publiczna" metoda - nie jest udokumentowana, a jej działanie może się zmienić bez zapowiedzi.

Dodatkowe parametry to `dpp` i `offset`

**Comment by gustawdaniel** [comment]
Nie do końca wiem czy dobrze Cię zrozumiałem. Chodzi o taki request?

```
http GET https://api.allegro.pl/offers?seller.id=10657099
```

On daje 

```
HTTP/1.1 406 Not Acceptable
Content-Length: 186
Content-Type: application/json; charset=utf-8
Date: Sat, 21 Apr 2018 16:49:16 GMT
Trace-Id: 84f31542cbb5ca22

{
    "errors": [
        {
            "code": "NotAcceptableException", 
            "details": null, 
            "message": "Not Acceptable", 
            "path": null, 
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}
```

**Comment by TimothyKoval** [comment]
Spróbuj z `https://allegroapi.io/offers?seller.id=xxx&dpp=180&offset=0`

**Comment by gustawdaniel** [comment]
Doszedłem do tego, że zgodnie opisem błędów na stronie

> https://developer.allegro.pl/about/

musiało mi brakować `Accept` lub `Content-Type`

Daję więc

```
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/json
```

I dostaję 

```
HTTP/1.1 422 Unprocessable Entity
Content-Encoding: gzip
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
Date: Sat, 21 Apr 2018 17:45:55 GMT
Trace-Id: 9d6b7fd4a0961e17
Transfer-Encoding: chunked

{
    "errors": [
        {
            "code": "UserAgentParseException", 
            "details": null, 
            "message": "An error has occurred", 
            "path": null, 
            "userMessage": "Communication error. Please check for an update."
        }
    ]
}
```

Bez nagłówka `Accept` mam 406. Dodanie nagłówka Api-Key nie wpływa na te błędy, jedynie brak lub obecność `Accept` decyduje o wyświetleniu 422 lub 406.

Przy okazji jeśli metoda "nie jest udokumentowana" to jak się jej nauczyłeś? :)

**Comment by TimothyKoval** [comment]
Spróbuj dodać kolejny nagłówek w formacie:

`User-Agent: Application-Package-Name_BundleId/ApplicationVersion (Client-Id CMDeviceUUID) OSName/OSVersion (Manufacturer Model)`

np.:

`MyApp/1.0 (Client-Id: xxx) Linux/x86_64 (CentOS)`

Client-Id odpowiada wartości na [https://apps.developer.allegro.pl/](https://apps.developer.allegro.pl/)

**Comment by gustawdaniel** [comment]
Wow! Zadziałało. Jesteś super! Napisz jeśli mogę Ci się jakoś odwdzięczyć. Bez Twojej pomocy pewnie stracił bym na to wiele dni. Jest dostępna jakaś dokumentacja wyjaśniająca nagłówek `User-Agent`? Nigdy nie spotkałem się z tym, żeby Client Id pakować do User Agenta...

Można zamknąć to issue. Zostawiam jedynie w celu znalezienia dokumentacji tego co napisałeś w komentarzu.

**Comment by TimothyKoval** [comment]
> Napisz jeśli mogę Ci się jakoś odwdzięczyć.

Wisisz piwo

> Jest dostępna jakaś dokumentacja wyjaśniająca nagłówek User-Agent?

Przed sprzedażą Allegro (bóg jeden raczy wiedzieć komu) pracowali tam mądrzy ludzie. Za tych czasów zaczęło powstawać nowe API, a jako jego podstawę ktoś (mądry) stworzył [guideline](https://github.com/allegro/restapi-guideline)
