### ISSUE TITLE
Access token expired

### ISSUE THREAD

**Issue by bjatwork** [allegro/allegro-api#1590]
Dostajemy  "Access token expired:"  mimo że każdym połączeniu odświeżamy token. Błąd pojawia się tylko raz na jakiś czas.

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację. Nie mamy narastających zgłoszeń z takim problemem. Jeśli konieczna jest weryfikacja tego przypadku podeślij proszę odpowiednie wywołania tego błędu przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1590

**Comment by sq9atk** [comment]
Mam ten sam problem. Co jakiś czas pojawia sie ten problem pomimo odświeżania tokenu. Korzystam z autoryzacji "device".

**Comment by neldh** [comment]
Ten problem był już zgłaszany jakiś czas temu i więcej osób go zgłaszało. Może nadal występuje po prostu.

**Comment by MartaNowaczyk** [comment]
Dlatego proszę o podsyłanie danych do weryfikacji. W innym przypadku takie pojedyncze zdarzenia trudno będzie wyśledzić. 
Każdy kto ma z tym problem, niech podeśle responsy i requesty przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1590

**Comment by MartaNowaczyk** [comment]
Dostałam dane do tego wątku przez formularz. Sprawdzimy i dam znać.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy podany przykład i token wygasł. Data wygaśnięcia (pole exp) podesłanego tokena to Thursday, May 9, 2019 8:21:19 PM GMT+02:00 DST, a podesłany request wsyłano po tym czasie (wg daty z nagłówka Date: Thu, 09 May 2019 06:25:28 GMT, ale tak naprawdę to +2h czyli 2019-05-09 08:25:28.697).

**Comment by bjatwork** [comment]
wysłałem ponownie formularz

**Comment by MartaNowaczyk** [comment]
@bjatwork sprawdziliśmy dokładnie logi i wychodzi na to, że używasz tokena A, później używasz refresh_tokena  i zamiast następnym razem użyć nowego tokena nazwijmy go B używasz tokena A, stąd ten błąd.
