### ISSUE TITLE
sandbox - aktywacja

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#1591]
witam,

prosze o aktywacje konta "absa" na sandbox'ie. 

dziekuje i zycze automatyzacji procesu :)

**Comment by MartaNowaczyk** [comment]
Witam,
niedawno wprowadziliśmy automatyzację tego procesu. 

Przejdź do zakładki [Moje konto](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) > Aktywacja konta i kliknij w "Chcę aktywować konto aby zacząć sprzedawać". 
Wybierz jakikolwiek bank (nie trzeba robić prawdziwego przelewu) i kliknij ACCCEPT. 
Konto powinno być już aktywne, a na maila podanego przy rejestracji konta powinieneś dostać potwierdzenie.

Jeśli wystąpią jakieś problemy daj proszę znać.

**Comment by barthoos** [comment]
> Nieaktywne - trwa weryfikacja Twoich danych.

**Comment by MartaNowaczyk** [comment]
Po wybraniu ACCEPT przy płatności masz taki status? Aktywowałam przed chwilą i nie było problemu. Przy zakładaniu konta wybrałeś od razu firmowe czy najpierw zwykłe i dopiero potem zmieniałeś?

**Comment by barthoos** [comment]
Zakladalem od razu konto firma. Zrobilem zgloszenie, poniewaz pierwszy mail z linkiem do aktywacji byl niekatywny/bledny, dopiero po jakims czasie przyszedl drugi mail z poprawnym linkiem. Po Twojej sugestii wybralem bank, kliknalem accept i od tego czasu w zakladce "Aktywacja konta" mam komunikat jak powyzej.

Nie wiem gdzie mialbym sprawdzic status platnosci (ktorej fizycznie nie robilem ofc).

**Comment by MartaNowaczyk** [comment]
aktywowałam ręcznie twoje konto. Co teraz masz na froncie?

**Comment by barthoos** [comment]
Przy statusie konta dalej mam

> Nieaktywne - trwa weryfikacja Twoich danych.

Natomiast wczesniej byla dodatkowa informacja w formie ramki na gorze, ze moje konto jest nieaktywne i teraz jej nie ma. Probowalem recznie wystawic aukcje przez front i dostalem komunikat:

> Podczas tworzenia oferty wystąpiły błędy
> Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert.

**Comment by barthoos** [comment]
Wciaz brak aktywacji. Nie mam mozliwosci testowania..

**Comment by MartaNowaczyk** [comment]
Wejdź proszę w Moje konto i Dane firmy lub przedsiębiorstwa. Zrób zastosuj  i zobacz czy nie pojawi ci się możliwość dodania plików. Jeśli tak dodaj dowolne dwa pliki i daj mi znać.

**Comment by barthoos** [comment]
Przeslane

**Comment by MartaNowaczyk** [comment]
Konto jest już aktywne i zweryfikowane jako firmowe.

**Comment by barthoos** [comment]
Dzieki sliczne. Co prawda dalej jest info, ze trwa weryfikacja danych, ale oferte przez front udalo mi sie juz wystawic ;)
