### ISSUE TITLE
[REST Api] - typ konta

### ISSUE THREAD

**Issue by masztan** [allegro/allegro-api#1593]
W wielu operacjach pewne dane są wymagane lub są inne ograniczenia na konta typu firma i konta prywatne. Jak za pomocą Rest API można się dowiedzieć czy dana osoba loguje się z konta firmowego czy prywatnego?

**Comment by MartaNowaczyk** [comment]
Na ten moment nie zwracamy nigdzie takiej informacji, ale przy tworzeniu zasobu, który zwróci dane użytkownika (powinien pojawić się w III kwartale 2019) planujemy dodać status konta.

**Comment by de57c** [comment]
Zlikwidowano: doShowUser. Poproszę więc o sposób na sprawdzenie czy dane konto (po id uzytkownika) jest kontem firmowym (ewentualnie dane konta firmowego - które można pobrać prasując stronę), junior, zamknięte, zamieszone etc. Też tak jak wcześniej pytano: czy można wyciągnąć po id - nazwę użytkownika. 

Czy ww. jest aktualnie możliwe?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedź w wątku #2287.
