### ISSUE TITLE
Status aukcji i dokumentacja

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1594]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Czy ja mógłbym, bardzo prosić o uzupełnianie dokumentacji RESTa. Nie ma dnia, abyśmy nie natrafili na coś zupełnie nowego, nieopisanego w dokumentacji.

Tym razem, okazało się, że aukcja może być w stanie, który nie jest opisany, dla zasobu /sale/offers/{offerId}
Tak mówi dokumentacja:
status | string Publication status, one of: INACTIVE, ACTIVATING, ACTIVE, ENDED

zaś program nam się w testach wywala, a tutaj cyk, status ARCHIVED.

Tak nie może być. W ten sposób się nie da pracować! Nie możemy się dowiadywać o wartościach danego pola w jakiejś konkretnej sytuacji bo skąd mamy to wcześniej przewidzieć, skoro dokumentacja _przeznaczona dla nas_ o tym nie wspomina. Przecież bez takiej wiedzy program może zachować się nieprzewidywalnie i potem to my odpowiadamy przed klientami za to jak to działa.

W mojej ocenie API REST, wraz z dokumentacją nie są gotowe na przejęcie tego, co realizuje do tej pory SOAP. Wyłączenie metod do zarządzania aukcjami w starym API w czerwcu *absolutnie nie wchodzi w grę* i proszę o poważne potraktowanie tej sugestii, bo to będzie istna rzeź na nas, twórcach jak i na sprzedających korzystających z naszego oprogramowania a także na klientach tychże sprzedawców.
Jest tak wiele niewiadomych w nowym REST, nie ma bardzo wielu danych, które wcześniej SOAP zwracał (chociażby słowniki państw, województw). Teraz dane te trzeba zapewnić samemu, więc istniejące rozwiązania korzystają z danych zwracanych przez stare API trzeba przerabiać jedno po drugim.

**Comment by MartaNowaczyk** [comment]
@Onixarts Rozumiem. Zwróciłam się do odpowiedniego zespołu w sprawie zwracania statusu ARCHIVED. Przekazałam też sugestię przesunięcia daty wygaszenia metod WebAPI do wystawiania i obsługi ofert.
