### ISSUE TITLE
Aktualizacja cennika starych aukcji przy pomocy RestAPI

### ISSUE THREAD

**Issue by adamzimnyy** [allegro/allegro-api#1596]
Na potrzeby budowy nowej funkcjonalności w aplikacji potrzebuję zaktualizować stare aukcje wystawione przez WebAPI o cenniki dostaw (aktualizacja przez RestAPI). Czy taka operacja spowoduje usunięcie danych, które były możliwe do ustawienia tylko przez WebAPI i już nie są? np. udostępnienie formy płatności przelew tradycyjny dla aukcji

**Comment by MartaNowaczyk** [comment]
@adamzimnyy Informacji o formach płatności nie ma już w ofercie i cenniki dostaw też ich nie zawierają, więc w teorii nie powinno się to zmienić. Proponuję jednak na początek przetestować na jednej ofercie, bo to przypadek, którego nie sprawdzę na aktualnej ofercie.
