### ISSUE TITLE
Darmowe koszty dostawy, a wyświetlanie informacji na listingu

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#1599]
Witam,
Nie jestem pewien czy to właściwie miejsce na pytanie.
Na koncie allegro mamy ustawioną darmową wysyłkę w przypadku zamówienia powyżej 400 zł. Dlaczego produkty, których cena przekracza to 400 zł, nie są oznaczone na listach jako 'darmowa dostawa" skoro de facto te produkty zostaną wysłane za darmo?
Klient przeglądając listę produktów nie widzi tego, że te produkty zostaną wysłane za 0zl i co więcej, na liście produktów pojawi się informacja o cenie z dostawą, która jest nieprawdziwa. Nie mówiąc już o tym, że z tego co mi wiadomo, ma to wpływ na pozycjonowanie.

Korzystając z WebAPI omijaliśmy ten problem ustawiając wszystkie koszty dostawy na darmowe przy dodawaniu/modyfikacji produktu. W RestApi, żeby uzyskać ten sam efekt musielibyśmy utworzyć nowe szablony kosztów dostawy, co uważam za kiepskie rozwiązanie.

**Comment by Himon-SYNCRAFT** [comment]
Skorzystałem z formularza, ale jedyna informacja jaką uzyskałem sprowadza się do:
"Udostępnienie darmowej dostawy od określonej kwoty zakupów nie skutkuje wyświetlaniem ikony darmowa dostawa na liście transakcji." - co już wiedziałem (trudno nie odnieść wrażenia jakby się rozmawiało z botem).

Dalej nie rozumiem dlaczego tak jest, skoro to wprowadza klienta w błąd. Moim zdaniem powinno to zostać zmienione.

**Comment by MartaNowaczyk** [comment]
Chętnie bym pomogła, ale to nie mój obszar działań.  Skieruj proszę swoją odpowiedź do osoby, od której otrzymałeś taką informację.
