### ISSUE TITLE
Bug w doGetSiteJournal

### ISSUE THREAD

**Issue by dfranczuk** [allegro/allegro-api#16]
Dzień dobry,
Przy wywołaniu metody doGetSiteJournal z raw_id = 31091175141 otrzymuję listę zdarzeń z raw_id mniejszymi niż podane raw_id. W efekcie nie jestem w stanie otrzymać większego raw_id niż 31091175141 i dziennik się zapętla.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Żebym mógł przeanalizować problem, który napotkałeś - podeślij proszę request i response zapisane w pliku XML.

**Comment by dfranczuk** [comment]
Hmm... faktycznie w request jest zły starting point.

       
        echo json_encode($requestData).PHP_EOL;

        $result = $this->client->__soapCall("doGetSiteJournal", array(
            [
                'sessionHandle' => 'fdae19335(***)30b7b//02_1',
                'startingPoint' => 31101404806
            ]
        ));

        echo $this->client->__getLastRequest().PHP_EOL;


Gdy wyświetlam $this->client->__getLastRequest() otrzymuję [https://drive.google.com/file/d/1oBCgo5RoaosVblHtM7SiOl1RIexHcSq0/view](url)
