### ISSUE TITLE
[Rest API] Niepoprawny opis bledu, przy wygasnieciu RefreshTokena

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#160]
Witam,

Moze pierdola, ale chcac byc swietszy od papieza odswiezam tokena tylko gdy opis bledu o kodzie "invalid_token" zawiera test "token expired". Tak wlasnie bylo do 19 kwietnia. Po tym czasie opsi bledu zmienil sie na "...". Przez co przestalo mi odswiezac tokeny. Zmienilem kod aplikacji, zeby odswiezal za kazdym razem gdy otrzymam wyjatek "invalid_token".

**Comment by KrzysztofLukanowski** [comment]
Dzięki za zgłoszenie. Poprawimy to.
