### ISSUE TITLE
[REST API] - /pricing/fee-preview

### ISSUE THREAD

**Issue by Strosx** [allegro/allegro-api#1601]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

```
 curl -X POST \
  https://api.allegro.pl/pricing/fee-preview \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR...' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{
  "offer": {
    "category": {
      "id": "5"
    },
    "duration": "PT720H",
    "quantity": 5,
    "type": "SHOP",
    "unitPrice": 131
  }
 }
'
```

Witam, powyższe zapytanie zwraca 400 Bad Request:

```
 {
    "errors": [
        {
            "code": "BAD_REQUEST",
            "message": "Bad Request",
            "details": null,
            "path": null,
            "userMessage": "Bad Request"
        }
    ]
}
```

W którym miejscu robię coś źle?

@Edit: sprawdzone na środowisku testowym i produkcyjnym. Na obu metoda /pricing/fee-preview nie odpowiada. 
Spróbowałem odpytać z przykładowym requestem podanym pod tym linkiem: 
https://developer.allegro.pl/news/2017-09-19-kalkulator_oplat/
Również rest api odpowiada błędem

**Comment by MartaNowaczyk** [comment]
Request wygląda na poprawny. Na pewno podczas wywołania nie dodajesz gdzieś na początku czy końcu jakiegoś znaku?

**Comment by Strosx** [comment]
Wysyłam dokładni taki request jak podany wyżej (jedyne co zmieniam to token autoryzacyjny), bez żadnych dodatkowych znaków. Wysyłałem request przy pomocy Postmana/Insomnia request sender i prostego skryptu w linqpadzie. Za każdym razem dostaje 400 i ten sam błąd.

Co ciekawe sprawdziłem odpowiedź dla requestu z błędnym jsonem (dodałem przecinek za ostatnią wartością) i otrzymałem odpowiedź:

```
{
  "errors": [
    {
      "code": "BAD_REQUEST",
      "message": "Bad Request",
      "details": null,
      "path": null,
      "userMessage": "Request body was not readable"
    }
  ]
}
```
Zatem gdyby problem był z złym request body to otrzymałbym taki błąd.

Sprawdziłem również request z błędnym id kategorii (5222). W takim wypadku dostaję odpowiedź:
```
{
    "errors": [
        {
            "code": "UNPROCESSABLE_ENTITY",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "offer.category.id",
            "userMessage": "Invalid category id"
        }
    ]
} 
```

Według mnie nie wygląda to jak problem z requestem, tylko z mapowaniem id kategorii po stronie kontrolerów rest api. Ale to są tylko moje domysły, bez wglądu do kodu ciężko to określić. Ewentualnie może nie każde konto ma dostęp do metody /pricing/fee-preview i tutaj jest problem. Chociaż w takim wypadku spodziewałbym się jakiejś 403/401.

**Comment by MartaNowaczyk** [comment]
To nie to, bo twój request mogę bez problemu wywołać i dostaję 200 OK, no i odpowiedni response oczywiście, także ciekawe. Zobacz jeszcze to samo, tylko dla type:OFFER

```
{
  "offer": {
    "category": {
      "id": "5"
    },
    "duration": "PT720H",
    "quantity": 5,
    "type": "OFFER",
    "unitPrice": 131
}
}

**Comment by Strosx** [comment]
Też nie działa. Dokładnie taki sam response. 

Korzystająć z autoryzacji typu device flow (poprzednio Client_credentials flow) z nowym tokenem request przeszedł. Zachowanie pewnie zamierzone, ale kody błędu mogłyby trochę bardziej nakierowywać na źródło problemu. W każdym razie wielkie dzięki za pomoc :)

**Comment by MartaNowaczyk** [comment]
To rzeczywiście nieodpowiedni błąd.  Podeślę to do zespołu, może uda nam się to poprawić. 
Pozdrawiam :)

**Comment by j4r3kb** [comment]
Obecnie mamy podobne problemy.
Podczas odpytywania API na końcówkę `/pricing/fee-preview` dostajemy błąd z mało czytelną wiadomością "Request body was not readable". Dotyczy to tylko kilku kategorii, przykładowa ma ID `260041`, trace-id `2a6711c2b26800f2`. Na innych kategoriach wszystko działa prawidłowo.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem Twoje zgłoszenie, problemem jest wartość, którą przekazałeś w polu duration - "0". Usunięcie tej wartości eliminuje błąd.
