### ISSUE TITLE
Warianty problem z wartościami w parametrach

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#1604]
Dotyczy środowiska testowego, ale na produkcyjnym pewnie też jest taki problem
W wariancie nie odświeżyło wartości w parametrach dodatkowych po których łączyłem oferty.

Dodałem kilka ofert w kategorii "Kabiny prysznicowe". Połączyłem oferty w wariant po parametrach "Dłuższy bok" i "Krótszy bok".
Następnie na kilku aukcjach zmieniłem wartości w tych parametrach ("Dłuższy bok" i "Krótszy bok") i wszystko przebiegło poprawnie bez błędów, wartości te zmieniły się w ofertach, ale wartości w wariantach pozostały bez zmian.
Teraz wygląda to tak że mam niezgodne oznaczenie wariantu na kafelkach z tym co jest w sekcji "Parametry"

**Comment by MartaNowaczyk** [comment]
Dzieje się tak tylko w przypadku zmiany przez API czy zmiana na frocie daje te same skutki?

**Comment by avello** [comment]
Wszystkie operacje wykonuję poprzez RestAPI

**Comment by MartaNowaczyk** [comment]
Przetestowałam i tak jak myślałam, nie jest to błąd samego API, tylko ogólne błędne działanie tej opcji. Tak czy inaczej zgłosiłam problem do odpowiedniego zespołu.
