### ISSUE TITLE
offer-publication-commands

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#1607]
Czy jeśli draft jest prawidłowy to coś może spowodować to że się nie aktywuje?

**Comment by MartaNowaczyk** [comment]
Błędne wywołanie metody do publikacji oferty lub jakiś problem techniczny może być problemem jeśli draft jest poprawny.

**Comment by lukada4100** [comment]
A przy okazji. Metoda aktywująca ofertę sale/offer-publication-commands PUT nie zwraca od razu wyniku. Żeby się dowiedzieć się czy wszystko jest w porządku i nie pojawił się "jakiś problem techniczny" muszę wysłać jeszcze raz sale/offer-publication-commands GET z tym samym numerem guid.
Fajnie byłoby, gdyby odpowiedź pojawiała się po, nie mówię milisekundach, ale kilku, niech będzie kilkunastu sekundach od pierwszej komendy. Niestety zdarza się, że metoda nie zwraca odpowiedzi po kilku minutach, mimo że oferta, której dotyczy zapytanie jest już dawno aktywna. Wystawiam setkę ofert i potem cholera wie, jak długo mam czekać, żeby się dowiedzieć czy wszystkie się wystawiły.

**Comment by MartaNowaczyk** [comment]
Do momentu rozpoczęcia przetwarzania pokazujemy wartość 0, dopiero po jakimś czasie pojawią się właściwe liczby ofert do przetworzenia Nie gwarantujemy, że będzie to kilka sekund. Do sprawdzania statusu mamy [dedykowane zasoby](https://developer.allegro.pl/sale/#step-10-tasks) i z nich należy korzystać.

**Comment by solokazama** [comment]
@lukada4100 
w REST API wszystko leci asynchronicznie, nie dostaniesz po wywolaniu metody PUT odpowiedzi. Czy to wystawiajac aukcje, czy zamykajac, wznawiajac (ACTIVATE). Powoduje to, ze trzeba przebudowac gruntownie cala logike aktualnego softu, ktory dzialal na produkcji lub pisac od nowa cale restapi, ale nei da sie plynnie przejsc (mapowania, problemy z metodami).

nie wiem co to bedzie po 3 czerwca.

**Comment by lukada4100** [comment]
@MartaNowaczyk @solokazama 
Ale napiszcie proszę, bo albo się nie rozumiemy, albo ja czegoś nie łapię mimo, że dość uważnie przestudiowałem instrukcje.
Bo tak. Mam drafta z pozytywną walidacją, czyli teoretycznie gotowego do aktywacji. Wysyłam osobno dla każdego draftu sale/offer-publication-commands PUT. To mi nic nie powie czy się udało czy może coś nie zadziałało, a jakoś to muszę sprawdzić (możliwie szybko zanim skończy mi się sesja czy użytkownik się wyloguje), żeby w razie czego ponownie próbować aktywować. Więc sprawdzam czy aktywacja się udała przez sale/offer-publication-commands GET i w 95 procentach to się sprawdza. Tyle, że jak piszę, sporadycznie zdarza się, że oferta jest już aktywna a ja wciąż dostaję success:0, fail:0.

O jakich dedykowanych zasobach mówisz? Mogę jeszcze wysłać /sale/offer-publication-commands/{commandId}/tasks GET, ale to chyba da taki sam efekt. Czy się mylę?

**Comment by MartaNowaczyk** [comment]
Do sprawdzenia statusu publikacji korzystaj z GET  /sale/offer-publication-commands/{commandId}

**Comment by lukada4100** [comment]
Czy my się w ogóle rozumiemy? Żeby sprawdzić czy aktywacja draftu się udała korzystam właśnie z wymienionej przez Ciebie metody. 
Problem polega na tym, że po kilkudziesięciu minutach od próby aktywacji, oferta jest już aktywna, a GET /sale/offer-publication-commands/{commandId} wciąż zwraca total:1,success:0, fail:0.

**Comment by MartaNowaczyk** [comment]
@lukada4100 racja, nie zrozumieliśmy się, wybacz cały czas myślałam, że piszesz o responsie po PUT. Jeśli masz konkretny przykład podaj request i response z trace-id . Sprawdzimy.

**Comment by skozuchowicz** [comment]
mam to samo. Oferty dawno są aktywne w serwisie (40 minut), a ja wciąż dostają "NEW" na /sale/offer-publication-commands/{commandId}/tasks

Po około godziny odpytywania w pętli zaczyna zwracać "SUCCESS"-y.

Czy można potraktować, że jeżeli po poprawnym walidzie draftu response na zasobie /sale/offer-publication-commands/{commandId}/tasks zwraca "NEW" , a nie "FAIL", to zamykamy proces wystawiania oferty w naszym programie z informacją, że oferta niebawem pojawi się w serwisie?

Oczekiwanie 40 minut na "SUCCESS" jest nie do przyjęcia.

**Comment by PawelTaberski** [comment]
Każda operacja na ofercie może zająć do godziny czasu, także najbezpieczniej byłoby odpytać o status kilkukrotnie, do momentu otrzymania "SUCCESS"
