### ISSUE TITLE
Jak zmieniają się zdjęcia po wysłaniu przez rest api?

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#1608]
Czy da się jakoś porównać czy zdjęcie wysłane przez rest api nie zostało już pobrane?

**Comment by MartaNowaczyk** [comment]
Nie wiem czy dobrze rozumiem, ale nie można sprawdzić czy zdjęcie dodane przez REST zostało użyte.

**Comment by KrzysztofStachyra** [comment]
Nie w tym rzecz - w starym API mieliśmy mechanizm, który w momencie importu aukcji wystawionej poza aplikacją (np. przez Allegro lub inny system), w trakcie importu do systemu pobierał zdjęcia do aplikacji lokalnej celem wykorzystania w przyszłości.
W trakcie importu porównywaliśmy sumy kontrolne pliku i ich rozmiar żeby określić czy w repozytorium już takie zdjęcie jest zapisane. Obecnie efekt jest taki, że pobierając zdjęcia z nowego API ciągle się dublują co wskazuje, że zdjęcie jest po Waszej stronie modyfikowane (kompresowane, dodawane coś cyfrowego).
Pamiętam, że jak dodawaliście nowy edytor i wprowadzaliście akcję wymiany zdjęć to była informacja, że zabezpieczacie zdjęcia cyfrowe pytanie czy to ingeruje w postać pliku (sumy kontrolne, rozmiar).

**Comment by kfijalko** [comment]
Allegro nakłada na zdjęcie "cyfrowy podpis", to są "mało widoczne szlaczki". Dlatego zawartość zdjęcia jest zmieniana i jego sumy kontrolne również.
W którymś wątku było , że allegro nie zaleca re-użycia zdjęć pomiędzy ofertami tylko nowe uploady.
Nie da się też pobrać oryginalnego zdjęcia przesłanego na allegro.
Jeżeli macie duble to znaczy, że zdjęcie przy każdym wgraniu dostaje inne "szlaczki".
Bez ingerencji użytkownika nie da się wyeliminować dubli.
Jeżeli biznesowo, usuwanie dubli, jest uzasadnione. To pozostaje tylko porównywanie ręczne.

**Comment by KrzysztofStachyra** [comment]
A czy Allegro ma może jakiś zasób, w którym zapisane jest jaki GUID/linki był dodany do danej oferty aby na tej podstawie porównywać co mamy a co by trzeba było dobrać?
Często klienci wystawiają z innego miejsca a pobierają transakcje w inne miejsce, więc teraz dla nas to odcięcie jakiejś funkcjonalności bo teraz nie ma jak tego binarnie porównać.

**Comment by MartaNowaczyk** [comment]
Przepraszam, że tak długo czekałeś na odpowiedź. 
Tak, do zdjęcia dodawane są dodatkowe informacje, więc jeśli ktoś oblicza sumę kontrolną ze zdjęcia, które mamy w Allegro, to suma za każdym razem będzie inna. 
Poza tym nie mamy żadnego zasobu, który pozwoli ci to kontrolować. W takim wypadku pozostaje liczyć po swojej stronie sumę kontrolną przed dodaniem do nas zdjęcia i zapisywać, a potem przy dodawaniu kolejnych to porównywać.

**Comment by KrzysztofStachyra** [comment]
Oryginalne zdjęcie mam, więc tu problemu nie ma, problem jest z procesem odwrotnym żeby określić czy to co ściągam to już przypadkiem u mnie nie jest zapisane. No ale jak nie ma to będę się głowił w późniejszym terminie czy jest jakieś obejście.
