### ISSUE TITLE
Zablokowane konto na serwerze produkcyjnym 

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#1609]
Wystawiałem na serwerze produkcyjnym aukcje testowe i moje konto zostało z tego powodu zablokowane. Czy mógłbym prosić o jego odblokowanie?

**Comment by MartaNowaczyk** [comment]
Z takim problemem zgłoś się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Proponuję w przyszłości korzystać z sandboxa.
