### ISSUE TITLE
Grupowa edycja ofert - poszerzamy możliwości zasobu

### ISSUE THREAD

**Issue by MaciejPotepa** [allegro/allegro-api#161]
Poszerzyliśmy możliwości zasobu do grupowej edycji ofert i draftów.

Obecnie dzięki zasobowi możesz grupowo przypisać:

wysyłkę od
cenniki dostaw
wysyłkę w ciągu

**informacje związane z dostawą:**
wysyłkę od
cenniki dostaw
wysyłkę w ciągu
dodatkowe informacje o dostawie

**opcje promowania:**
pogrubienie
wyróżnienie
podświetlenie
oferta promowana na stronie kategorii
pakiet promowania: wyróżnienie, podświetlenie i pogrubienie oferty

Więcej informacji znajdźcie [tutaj](https://developer.allegro.pl/news/2018-04-19-News_grupowa_edycja_ofert_update/).

**Comment by pgasidlo** [comment]
Mam problem z użyciem tej metody. Postępowałem wg. https://developer.allegro.pl/news/2018-04-19-News_grupowa_edycja_ofert_update/

To mój payload:

`{"modification":{"delivery":{"shipmentDate":"2018-05-25T08:00:00Z"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":7272412288}]}]}`

Do wywołania:

`PUT /sale/offer-modification-commands/f8a66912-f9e1-4cc0-a8a4-d605b6df91c7`

Dodatkowo ustawione wszystkie potrzebne nagłówki.

W odpowiedzi otrzymuję:

```
object(stdClass)#26 (2) {
  ["id"]=>
  string(36) "f8a66912-f9e1-4cc0-a8a4-d605b6df91c7"
  ["taskCount"]=>
  object(stdClass)#27 (3) {
    ["total"]=>
    int(0)
    ["success"]=>
    int(0)
    ["failed"]=>
    int(0)
  }
}
```

Wygląda, że total jest 0, a oczekuje 1. Ten sam wynik mam jak wywołuję:

`GET /sale/offer-modification-commands/f8a66912-f9e1-4cc0-a8a4-d605b6df91c7`

W przypadku wywołania:

`GET /sale/offer-modification-commands/f8a66912-f9e1-4cc0-a8a4-d605b6df91c7/tasks/`

Mam timeout.

O co chodzi?

**Comment by pgasidlo** [comment]
Dobra, już wiem. W nagłówku użyłem `application/vnd.allegro.public.v1+json` zamiast `application/vnd.allegro.beta.v1+json`. Po zmianie wszystko działa.
