### ISSUE TITLE
Problem z cachowaniem 

### ISSUE THREAD

**Issue by KrzysztofStachyra** [allegro/allegro-api#1610]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mam taki problem, aplikacja desktopowa obsługuje wiele kont Allegro danego użytkownika. W momencie zmiany konta można uruchomić proces autoryzacji aplikacji w REST API. Problem polega na tym, że strona autoryzacji jest utrzymywana w cache przez co strona ładowana do komponentu .netowego webbrowser próbuje powiązać aplikację z innego konta do tego nowego, na które klient się przelogował. 
Jeśli użytkownik nie zwróci na to uwagi to robi się mega fakap bo pobiera się berare z innego konta (wszystko zaczyna frafiać na inne konto).
Rozwiązaniem problemu jest czyszczenie cookies przez IE (ten komponent na tym bazuje) ale oczywiście klient nie będzie o tym pamiętał.
Sama aplikacja też nie powinna tego w ciemno zawsze czyścić bo się użytkownicy wkurzą.

Żeby odebrać prawidłowo token muszę wywołać okno w aplikacji a nie zewnętrzny browser np. IE czy chrome bo potem nie ma jak w aplikacji odebrać code do pozyskania bearera.

Czy ktoś ma może pomysł jak to ugryźć?

**Comment by rtnet-pl** [comment]
Zawsze przekieruj użytkownika na stronę wylogowania (https://allegro.pl/logout.php), ustawiasz event Navigated, w nim sprawdzasz czy trafił na adres https://allegro.pl/?logout=1 i dopiero potem przekierowujesz do strony logowania

**Comment by KrzysztofStachyra** [comment]
Zawsze powtarzam, że mądrych warto słuchać:)
Dzięki - działa jak należy (przynajmniej na roboczo:))
