### ISSUE TITLE
Data zamówienia i pobieranie zamówień

### ISSUE THREAD

**Issue by sq9atk** [allegro/allegro-api#1611]

**Comment by sq9atk** [comment]
Jak to się dzieje że RestApi umożliwia pobieranie zamówień z filtrowaniem po przedziale dat, a w zamówieniach które schodzą w odpowiedzi na to żądania nigdzie nie ma tej daty. Wszak to dzięki niej zamówienie załapało się do wyników żądania.

**Comment by yncki** [comment]
prosimy o dodanie takiego pola

**Comment by MartaNowaczyk** [comment]
Przecież po wyświetleniu listy zamówień cały czas zwracamy datę pojedynczego zamówienia, która jest brana pod uwagę przy zakresie dat - to lineItems.boughtAt
Czy chodzi wam o coś zupełnie innego?

**Comment by sq9atk** [comment]
Gdy kupujemy u jednego sprzedawcy na kilku różnych aukcjach to lineItems.boughtAt ma za każdym razem inną wartość. Aktualnie za datę zamówienia pobieram sobie najstarsze lineItems.boughtAt ale uważam, że to jest proteza bo tam na prawdę to nie jest data złożenia zamówienia.

**Comment by MartaNowaczyk** [comment]
@sq9atk tak, daty te nieznacznie się różnią, ale przy jednym zakupie w wielu ofertach na raz, różnią się minimalnie. Opisz proszę co chcesz otrzymać. Nie wiem jak działasz i nie do końca mogę ci pomóc.

**Comment by sq9atk** [comment]
Chcę aby w danych zamówienia schodziła ta data, która determinuje fakt zakwalifikowania lub odrzucenia zamówienia z wyników żądania.

**Comment by MartaNowaczyk** [comment]
Dziękuję za wyjaśnienie, choć bardziej miałam na myśli jak wygląda u ciebie cały proces pobierania zamówień z wykorzystaniem otrzymanych wyników.
