### ISSUE TITLE
Błędy ServiceTimeoutException

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1612]
Od kilku dni zaobserwowałem pojawianie się błędów typu:

`{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Przekroczono czas wykonania zapytania. Spru00f3buj ponownie."}`

Przykładowy trace id: 3bc69f7461c943b1

**Comment by pietrach** [comment]
I podczas przesyłania zdjęć czasem błąd:


`{"message":"Operation timed out after 20000 milliseconds with 0 bytes received"}`

**Comment by MartaNowaczyk** [comment]
Dziękujemy za zgłoszenie. Gdy coś ustalimy dam znać. 

Jeśli chodzi o drugi błąd, możesz podać jeszcze trace-id?

**Comment by MartaNowaczyk** [comment]
@pietrach potwierdzamy, że mieliśmy wydłużone czasy odpowiedzi w tym okresie. Na ten moment problem nie powinien występować. Za utrudnienia przepraszamy.

**Comment by pietrach** [comment]
Dziś też są takie błędy:

`{"message":"Operation timed out after 20000 milliseconds with 0 bytes received"}`

Występuje podczas wysyłania zdjęć metodą` POST /sale/images`. Nietsety nie ma trace-id. Kod błędu to 500

**Comment by pietrach** [comment]
Dodatkowo dzisiaj bardzo częsty błąd:

`[{"code":"ServiceUnavailableException","message":"An error occurred","details":null,"path":null,"userMessage":"Serwer nie jest w stanie zrealizowau0107 zapytania. Spru00f3buj ponownie za kilka minut."}]`

**Trace ID:**
e62d99aaff879d51
6af1c787a939e4d5
a199a8f844c57eec
9f59d8d0eb730b9d

**Comment by pietrach** [comment]
`[{"code":"COMMAND_ACCESS_FORBIDDEN","message":"","details":null,"path":"","userMessage":"Nie masz uprawnieu0144 do tego zlecenia"}]`

**Trace ID:**
e35390851f67e617

**Comment by MartaNowaczyk** [comment]
@pietrach podesłałam te błędy do odpowiednich zespołów do weryfikacji.

**Comment by pietrach** [comment]
Dalej występuje czasem błąd przy dodawaniu zdjęć:

`{"message":"Operation timed out after 20000 milliseconds with 0 bytes received"}`

**Comment by PawelTaberski** [comment]
Podeślij proszę trace-id tego zadania.

**Comment by pietrach** [comment]
Niestety te błędy nie posiadają trace id 
            
          
     
      
       
        Dnia 27 maja 2019 15:27 PawelTaberski &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Podeślij proszę trace-id tego zadania.

**Comment by PawelTaberski** [comment]
A mógłbyś podesłać przykładowego pełnego requesta z jakim masz problem i załączyć grafikę jaką chcesz przesłać. Podeślij te dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu zaznacz, że dane dotyczą zgłoszenia 1612 na GitHub-ie.
