### ISSUE TITLE
Format zwracanych błędów - błąd w dokumentacji

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#1613]
Witam
Dla szeregu metod jest błąd w dokumentacji dla formatu zwracanych błędów
Przykład:
https://developer.allegro.pl/documentation/#operation/createChangePriceCommandUsingPUT
Jest:

[
  {
    "code": "string",
    "details": "string",
    "message": "string",
    "path": "string",
    "userMessage": "string"
  }
]

Powinno być:
{
  "errors": [
    {
      "code": "string",
      "details": "string",
      "message": "string",
      "path": "string",
      "userMessage": "string"
    }
  ]
}

Przejrzyjcie proszę inne metody bo wygląda to na powszechny błąd

**Comment by MartaNowaczyk** [comment]
Dziękujemy za zgłoszenie. Pracujemy nad poprawą.
