### ISSUE TITLE
Wysyłanie zdjęć na serwer

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1614]
Witam dostaje błąd podczas wysyłania zdjęcia na serwer.

422
Unprocessable entity
Invalid URL

Co dziwne dodawało bez problemu w pewnym momencie przestało i zaczęło sypać błędami.

Jakieś pomysły czemu ?

Z góry dziękuje za odpowiedź.

**Comment by jzskyshop** [comment]
Mam ten sam problem - przy próbie wrzucenia obrazka za pomocą url-a cały czas dostaję komunikat "Image from the given address can not be downloaded. Connection error." mimo, że url jest prawidłowy.

**Comment by solokazama** [comment]
3 czerwca ma byc wygaszone stare API.

a codziennie cos z RESTem jest. jpd!

**Comment by MartaNowaczyk** [comment]
Nie mogę powtórzyć błędu. Czy błąd cały czas występuje? JEśli tak to czy dla wszystkich zapytań czy tylko dla wybranych?

**Comment by mskiba03** [comment]
Witam, bad nadal wystepuje dla wszystkich zapytan.
Mam jeszcze pytanie czy adres do obrazka moze byc w postaci adresu IP, bo napewno tak dzialalo, ale moze cos zostalo zmienione.

**Comment by MartaNowaczyk** [comment]
@mskiba03 nie powinno działać wcale - trzeba podać adres domeny, nie adres IP

**Comment by mskiba03** [comment]
No dobra to przynajmniej problem sie rozwiazal;) Dzieki

**Comment by jzskyshop** [comment]
@MartaNowaczyk błąd ewidentnie był - wczoraj od rana próbowałem wgrać to samo zdjęcie (za każdym razem wspominany błąd), przeszło dopiero po 16.
