### ISSUE TITLE
Problem z pobieraniem usług dodatkowych poprzez REST API

### ISSUE THREAD

**Issue by Anch0rOne** [allegro/allegro-api#1617]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym

:beetle: **Opis**

Trace-Id=[9a9e047d55b86630]

Na podstawie pliku openapi.yaml pobranego z waszej strony wygenerowałem źródła w Java za pomocą narzędzia openapi-generator. Testowo dodałem kod do importu informacji o gwarancjach ('/after-sales-service-conditions/warranties'), importu polityk zwrotów ('/after-sales-service-conditions/return-policies'). Dane się importują poprawnie.
Mam jednak problem z pobraniem danych z kolejnego słownika Usług dodatkowych ('/sale/offer-additional-services/groups'). Podczas wywołania tej metody dostaję błąd:
'{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-additional-services/groups","userMessage":null}]}'

Proszę o wskazówkę, co może być przyczyną błędu.

**Comment by Cupik83** [comment]
Ok znalazłem przyczynę w powielonych nagłówkach. Niestety komunikaty o błędach nie ułatwiają sprawy.

Można zamknąć.

**Comment by MartaNowaczyk** [comment]
Z tego co wstępnie widzę to 500 i na ten moment te błędy występują tylko dla twojego id i tylko na tym zasobie. Widzę też, że co któryś request dostajesz status 200. Komunikat błędu jest jednak zastanawiający. Zmieniasz coś w requeście czy ciągle jest ten sam?

**Comment by Anch0rOne** [comment]
Dane z tego słownika pobierałem na dwa sposoby, mam stary kod który działał i dlatego widzicie czasami 200, chciałem teraz przejść na nowy sposób integracji, przy pomocy klienta API wygenerowanego w openapi i dla niego mi nie działa, dlatego pewnie widzicie, że czasami dostaję 200.

**Comment by Anch0rOne** [comment]
Wczoraj sukcesywnie przechodziłem w kolejnych słownikach na pobieranie danych przy pomocy openapi i na razie wszystko mi działa, oprócz tego wyżej wymienionego zasobu. Możliwe że jest spowodowane błędem openapi.yaml i przez klient API wygenerowany w openapi jest błędny ?

**Comment by Anch0rOne** [comment]
Widzę, że została zaktualizowana dokumentacja w pliku yaml. Po wygenerowaniu nowego klienta w opeapi błędu już nie ma
