### ISSUE TITLE
Walidacja draftu - nieprawidłowe zdjęcie

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#1618]
Przesyłam zdjęcie za pomocą url-a zasobem sale/images. Otrzymuję location, czyli wszystko okej. Tworzę opis oferty:
`{  
   "sections":[  
      {  
         "items":[  
            {  
               "type":"TEXT",
               "content":"<p>Drugi Przyk\u0142adowy produkt"
            }
         ]
      },
      {  
         "items":[  
            {  
               "type":"IMAGE",
               "url":"https:\/\/a.allegroimg.com\/original\/115d91\/6f3ae89448b2b86fc9bd5c379f49"
            }
         ]
      },
      {  
         "items":[  
            {  
               "type":"TEXT",
               "content":"<h1>Parametry<\/h1><ul><li><b>Stan<\/b>: Nowy<\/li><\/ul>\n"
            }
         ]
      }
   ]
}
`
...i otrzymuję błąd:
`           [code] => VALIDATION_ERROR
            [message] => Description images are not valid.
            [details] => Invalid value: unknown
            [path] => offerDto
            [userMessage] => Description images are not valid.`

Co robię źle?

**Comment by partyumarty** [comment]
Mógłbyś się pochwalić co było źle :) ?

**Comment by retrowaver** [comment]
@partyumarty u mnie brakowało użytego URLa w strukturze `images` przesyłanego draftu
