### ISSUE TITLE
Błąd HTTP 500 w metodzie GET /sale/offers

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1619]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, od dzisiaj na sandboxie losowo nie działa (kilka razy jest błąd kilka razy zwróci listę ofert) lista aukcji według seller.id, dla następującego requesta:

```
server →envoy
trace-id →9246e9e59f03dc5a
content-type →text/plain; charset=utf-8
content-length →213
date →Tue, 14 May 2019 09:33:13 GMT
x-envoy-upstream-service-time →155
```
Request:
```
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers?publication.status=INACTIVE%2CACTIVATING%2CACTIVE%2CENDED&sellingMode.format=BUY_NOW%2CADVERTISEMENT%2CAUCTION&limit=25&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer {token}' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
```
W response zwracany jest błąd:
```
500 Error when searching seller offer (sellerId: {sellerId}, searchCriteria: {"publication.status":"INACTIVE,ACTIVATING,ACTIVE,ENDED","sellingMode.format":"BUY_NOW,ADVERTISEMENT,AUCTION","limit":"25","offset":"0"}).
```
Czyżby [problem z tego zgłoszenia](https://github.com/allegro/allegro-api/issues/971#issue-389230554) powrócił?

**Comment by MartaNowaczyk** [comment]
Mam nadzieję, że nie powrócił. W każdym razie sprawdzimy te błędy.
