### ISSUE TITLE
Odpowiednik doGetTransactionsIDs w REST API

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1620]
:bulb: **Sugestia**
Witam, zwracam się z prośbą o umożliwienie pobrania transakcji (checkout-forms) dla konkretnych identyfikatorów ofert przez REST API.

Chodzi o funkcję odpowiadającą metodzie [doGetTransactionsIDs](https://allegro.pl/webapi/documentation.php/show/id,121) w WebApi, przyjmującej za parametr tablicę identyfikatorów ofert:

itemsIdArray | long[] | wymagany
Tablica identyfikatorów ofert (maks. 25).

@MartaNowaczyk @PawelTaberski proszę o informację czy będziemy zmuszeni zrezygnować z funkcji opartej na w/w metodzie WebAPI dostarczanej Klientom w naszym oprogramowaniu.

**Comment by MartaNowaczyk** [comment]
@alekskuc nie planujemy udostępniać takiego rozwiązania. Tak jak już wcześniej pisaliśmy REST API nie będzie odwzorowaniem WebAPI. Mogę zgłosić jedynie taka sugestię.
