### ISSUE TITLE
Wyciąganie tylko ofert z fv

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#1622]
Witam, wyszukuję sobie ofert tylko z wskazaną nazwą, aczkolwiek chciałbym do tego mieć filtr, żeby wyciągał tylko oferty z Faktura VAT, w otrzymanym json nie ma tej opcji. 
Kawałek kodu:
`$uri2="https://api.allegro.pl.allegrosandbox.pl/offers/listing?phrase=".$new_product_name."&searchMode=REGULAR";`
Próbowałem dodawać &include=filters aczkolwiek to nie działa. 
Co mogę jeszcze zrobić ?

**Comment by MartaNowaczyk** [comment]
Możesz skorzystać z filtrów, które dostajesz po każdym zapytaniu np.
GET /offers/listing?category.id=257199&option=VAT_INVOICE

Samo wyszukiwanie najlepiej sprawdzać na produkcji. Na sandboxie może nie być wielu ofert do wyświetlenia.

**Comment by kubaszy** [comment]
Dziękuję bardzo własnie o to mi chodziło.

________________________________
Od: MartaNowaczyk <notifications@github.com>
Wysłane: środa, 15 maja 2019 11:24
Do: allegro/allegro-api
DW: kubaszy; Author
Temat: Re: [allegro/allegro-api] Wyciąganie tylko ofert z fv (#1622)


Możesz skorzystać z filtrów, które dostajesz po każdym zapytaniu np.
GET /offers/listing?category.id=257199&option=VAT_INVOICE

Samo wyszukiwanie najlepiej sprawdzać na produkcji. Na sandboxie może nie być wielu ofert do wyświetlenia.
