### ISSUE TITLE
Wybór wersji językowej

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1624]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W pomocy do REST API czytamy:

# Wersja językowa
Jeżeli chcesz być pewny, że wszystkie teksty zwracane będą w języku polskim, wysyłaj z każdym żądaniem nagłówek:
```
Accept-Language: pl-PL
```
No więc wysyłam:

```
Method: GET, RequestUri: 'https://api.allegro.pl/after-sales-service-conditions/return-policies?seller.id=niepoprawnyId&limit=100&offset=0', 
Headers:
{
  Accept: application/vnd.allegro.public.v1+json
  Accept-Language: pl-PL
  Authorization: Bearer qweasd
}
```
Otrzymuję odpowiedź:
```json
{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "Forbidden",
      "details": null,
      "path": null,
      "userMessage": "You do not have permission to request this resource"
    }
  ]
}
```
To tak ma nie działać czy robię coś źle?

**Comment by MartaNowaczyk** [comment]
@Onixarts masz rację, powinno być po polsku. Zaraz zgłoszę to do poprawki.

**Comment by MartaNowaczyk** [comment]
poprawiliśmy
