### ISSUE TITLE
Restapi i zmiana handlingTime w trwającej ofercie?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#1625]
Witam,
Mam problem ze zmianą czasu wysyłki w trwającej ofercie. Wysyłam:
{
"modification": {
"delivery": {
    "handlingTime": "P14D"
}
},
    "offerCriteria":[
    {
        "type":"CONTAINS_OFFERS",
        "offers":[
        {
        "id":"8031463627"
        }
        ]
    }
    ]
}

i otrzymuje cały czas: 422 Unprocessable Entity
$VAR1 = {
          'errors' => [
                        {
                          'userMessage' => 'may not be null',
                          'path' => 'publication',
                          'details' => 'Invalid value: null',
                          'message' => 'may not be null',
                          'code' => 'VALIDATION_ERROR'
                        }
                      ]
        };
co może być przyczyną.

**Comment by MartaNowaczyk** [comment]
"handlingTime" zmienisz tylko przez [edycję pojedynczej oferty](https://developer.allegro.pl/my_offers/#2). Edycja wielu ofert nie obejmuje zmiany dla tej wartości.

**Comment by AleksyZajac** [comment]
Czy dobrze rozumiem że przesyłam całą ofertę tak jak bym ją wystawiał tylko używam PUT?
Nie mam możliwości zmiany jednego elementu tak jak to ma miejsce w edycji wielu ofert?

**Comment by MartaNowaczyk** [comment]
dokładnie tak
