### ISSUE TITLE
Brak możliwości dodania własnych parametrów (cech produktu) do oferty prze REST API ?

### ISSUE THREAD

**Issue by Nateck** [allegro/allegro-api#1626]
W jaki sopsób można dodać własne parametry dla produktu w ofercie?
Tak samo przy pobieraniu oferty, której są parametry dodatkowe, nie pojawiają się w liście.

**Comment by MartaNowaczyk** [comment]
Na ten moment testujemy tą funkcjonalność na formularzu. Nie wiem czy czy i kiedy będzie dostępna na REST API. To wszystko zależy od tego, czy ostatecznie zdecydujemy się na jej pełne wdrożenie.

**Comment by Nateck** [comment]
Bardzo przydatna funkcja. Dla nas osobiście bardzo ważna. W przypadku gdy nie ma do wyboru w kategorii Serwery opcji "odnowiony" ten dodatkowy paramter służyłby do takiej informacji

**Comment by MartaNowaczyk** [comment]
Dziękujemy za argument.

**Comment by Radeq** [comment]
Witam,

Czy coś się zmieniło w kwestii parametrów dodatkowych i ich widoczności w API? Czy i kiedy taka opcja będzie dostępna?

https://allegro.pl/dla-sprzedajacych/od-dzis-sprzedajacy-w-kilkunastu-kategoriach-moga-tworzyc-wlasne-parametry-ofert-9darPr5kyIZ#sprawdz-w-ktorych-kategoriach-mozesz-dodac-parametry

W czerwcu 2019 dodatkowe kategorie otrzymały możliwość dodawania własnych parametrów.

**Comment by MaciejFrackowiak** [comment]
@Radeq Nie, na razie parametry te nie pojawiły się w API. Sugestia ich wprowadzenia została przekazana do działu odpowiedzialnego za rozwój REST API.
