### ISSUE TITLE
Zmiana hasła Allegro? 

### ISSUE THREAD

**Issue by Lechu85** [allegro/allegro-api#1627]
Witam.
Ostatnim czasie pracownik zmienił hasło Allegro i hasła do aplikacji przestały działać również. 
Czy jest to zamierzone Allegro?

Jeżeli zmieniam hasło to muszę wygenerować nowe dane do RestAPI również? Nowy token?

**Comment by MartaNowaczyk** [comment]
Tak to działa. Zmiana hasła unieważnia token, dlatego trzeba wygenerować nowy.
