### ISSUE TITLE
/offers/<id>/change-price-commands/ rzuca błędem 422 a za 4 razem jednak przechodzi

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1628]
Jak to mogło się stać? Ja rozumiem jakby 500 poleciała co by było sygnałem dla nas że trzeba powtórzyć takiego tasks, ale czemu przy problemach z api zwracany jest wiele mówiący błąd
422: Unprocessable Entity for url: https://allegroapi.io/offers/<id>/change-price-commands/7661deb9-9428-441e-8445-e0c01959df08 ? Czy na każdy błąd mamy reagować, że ponowić X razy i a nuż się uda wstrzelić w czas kiedy api działa?

Dokładnie takie same problemy są z WebAPI, walić do skutku a może się uda, tylko tam jest synchroniczne api więc od razu wiemy czy jednak się wszystko udało czy jednak coś się zwali za godzinę przy procesowaniu taska po waszej stronie.

Jako że 3 czerwca jest deadline na przeniesienie, więc teraz z najmniejszym problemem będę walił do was i będę waszym osobistym sentry, bo chyba nie dorobiliście się monitoringu ;)

**Comment by MartaNowaczyk** [comment]
Z tego co widzę url jest niepoprawny - //. 

Przypominam też, że 30 lipca nie wspieramy domeny allegroapi.io o czym już informowaliśmy #1555 .
