### ISSUE TITLE
Zbiorowa zmiana ilości w ofertach

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1629]
Czy jest jakaś możliwość aby w wielu ofertach naraz zmienić ilość ?
Przykład: mam załóżmy 800 ofert, dla każdej oferty mam jakąś określoną ilość sztuk i chce to zaktualizować.

Znalazłem taką metodę poniżej. Ale mam wrażenie że ona ma sens tylko wtedy jeśli aktualizuje pewną liczbę aukcji tą samą ilością. Tak to działa ? Tylko proszę nie odsyłajcie mnie do żadnych poradników tylko wytłumaczcie co i jak.

PUT /sale/offer-quantity-change-commands/{commandId}

**Comment by MartaNowaczyk** [comment]
@pietrach masz rację można dla wielu ofert zmienić cenę, ale na tą samą. Nie można wysłać listy ofert z informacją jaka ma być cena dla każdej z nich w jednym zapytaniu.

**Comment by pietrach** [comment]
Ale mi chodzi o ilości ale pewnie tak samo jest ? 
            
          
     
      
       
        Dnia 16 maja 2019 15:28 MartaNowaczyk &lt;notifications@github.com&gt; napisał(a):
       
    
       
         github.com @pietrach  masz rację można dla wielu ofert zmienić cenę, ale na tą samą. Nie można wysłać listy ofert z informacją jaka ma być cena dla każdej z nich w jednym zapytaniu.

**Comment by MartaNowaczyk** [comment]
dokładnie tak
