### ISSUE TITLE
Rest API - nick po seller id 

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#1630]
Witam. 
Czy istnieje możliwość wyciągnięcia nicku sprzedającego znając seller_id ? 
W pobieranym json ofert jest tylko pole z seller_id. 
Pozdrawiam serdecznie.

**Comment by MartaNowaczyk** [comment]
Nie mamy jeszcze dedykowanego zasobu do pobierania nazwy sprzedającego po id. Mamy to jednak w planach. Już niedługo opublikujemy więcej informacji na temat planowanych zmian.
