### ISSUE TITLE
Problem z pobraniem danych zamówienia z Allegro SandBox

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#1631]
Witam,

Proszę o weryfikację mojego kodu , mimo po przeczytaniu dokumentacji i zastosowaniu się do zaleceń, otrzymuję błąd z If'a:

`<?php

include("allegro-api.php");

function getOrders(String $token): stdClass
{
    $getOrdersUrl = "https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms";
    $ch = curl_init($getOrdersUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_ENCODING, "");
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST,"GET");
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json",
				 "Content-Type: application/vnd.allegro.public.v1+json"
    ]);

    $getOrdersResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($getOrdersResult === false || $resultCode !== 200) {
        exit ("Linijka 22 , tutaj!");
    }
    $orderslist= json_decode($getOrdersResult);
    return $orderslist;
}
function main() {
	$token = getAccessToken();
    var_dump(getOrders($token));
	echo $token;
}
main();
?>`

**Comment by MartaNowaczyk** [comment]
Zmień wartości nagłówków Accept i Content-Type z public na beta.

**Comment by allmat** [comment]
@MartaNowaczyk 
Dziękuje , ale mimo to dalej jest problem dokładnie dostaje to:
object(stdClass)#1 (2) { ["error"]=> string(13) "access_denied" ["error_description"]=> string(16) "Access is denied" } 

Dodam, że alegro-api jest dokładnie z waszego szablonu na stronie wraz z authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials"

**Comment by MartaNowaczyk** [comment]
@allmat autoryzacja client credentials jest tylko dla zasobów publicznych, w których nie trzeba autoryzować się jako sprzedawca. Do pobrania zamówień musisz skorzystać z [Code flow lub Device flow](https://developer.allegro.pl/auth/).

**Comment by allmat** [comment]
@MartaNowaczyk Dobrze, czyli rozumiem że jeśli poprawnie stworzę kod typu Code flow , to powyższe zapytanie odnośnie zamówień zwróci mi dane?

**Comment by MartaNowaczyk** [comment]
@allmat tak, powinien działać

**Comment by allmat** [comment]
mam pytanie do do function getOrders(String $token): stdClass , mam przekazywać token czy kod dostępowy który wygenerował mi się przy url: http://127.0.0.1/allegro_api.php?code=tUqln4gwLhqDh2l4Nz8**** ??

**Comment by MartaNowaczyk** [comment]
Token. Kod, który wkleiłeś musisz wymienić na token zgodnie z tym co napisane jest tutaj: https://developer.allegro.pl/auth/#user punkt 5.
