### ISSUE TITLE
Allegro SandBox - zakup bez zalogowania

### ISSUE THREAD

**Issue by Cupik83** [allegro/allegro-api#1633]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Jest jakiś problem z zakupem w środowisku testowym na Sandbox-ie.

Przy próbie zakupu bez zalogowania wyskakuje co chwilę komunikat o próbie weryfikacji numeru telefonu oraz o wystąpieniu błędu. Bez wybrania faktury czasem da się dokończyć zakup chodź komunikat o błędzie wyskakuje kilka razy i następuje odświerzanie formularza i trzeba wpisywać po kilka razy to samo. Z wybraniem faktury nie da się dokończyć zakupów bo co chwilę dostaję komunikat o błędzie.

**Comment by MartaNowaczyk** [comment]
@Cupik83 problem z zakupem na sandboxie zgłoś przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)
