### ISSUE TITLE
Długie czasy odpowiedzi podczas odpytywania bazy produktowej

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#1635]
Zauważyłem, że podczas wykonywania kilkudziesięciu po kolei zapytań (requestów) o produkty w bazie produktowej tylko pierwsze kilkanaście odpowiedzi przychodzi po akceptowalnym czasie. Kolejne przychodzą już średnio po 5 sekundach na jedno zapytanie. Co daje 10 sekund podczas próby pobrania wszystkich informacji dotyczących jednego produktu.

Poniżej podsyłam przykłady Trace-Id podczas wykonywania szeregowo dwóch zapytań:

GET https://allegroapi.io/sale/products?ean=9788375191912
GET https://allegroapi.io/sale/products/306ad200-6694-48d5-8356-1968ba4618c7

Wykonywałem je kilkadziesiąt razy po kolei czekając za każdym razem na odpowiedź poprzedniego zapytania zanim wyślę kolejne zapytanie. I tylko pierwsze kilkanaście odpowiedzi przyszło  w akceptowalnym czasie. Na kolejne kilkadziesiąt odpowiedzi musiałem czekać średnio po 5 sekund na jedno zapytanie.

Czy takie czasy odpowiedzi podczas obsługi produktyzacji pozostaną na zawsze?

Przykłady Trace-Id z akceptowalnymi czasami odpowiedzi mniejszymi niż 50 milisekund:

Trace-Id: e10913b4999f176c
Trace-Id: b0d4446da76225cc
Trace-Id: 9345f12d58354f16

Przykłady Trace-Id z czasami odpowiedzi między 4 a 7 sekund:

Trace-Id: 4e632652f828249e
Trace-Id: a47dbae7703d063e
Trace-Id: 964f7a70129daab

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Sprawę przekazałam do przeanalizowania przez zespół, który zajmuje się tym tematem.

**Comment by MartaNowaczyk** [comment]
Chciałabym jeszcze dopytać o szczegóły. Interesuje nas potrzeba wysyłania tak częstych zapytań do bazy produktowej. Proszę określić swoje potrzeby. Czy jest to potrzebne, bo wystawiacie tysiące ofert na allegro? Jakiego konta to dotyczy. Chcielibyśmy określić skalę problemu.

**Comment by tomylee0** [comment]
Dla konta z 70 tysiącami ofert potrzebuję pobrać 70 tysięcy produktów z bazy produktowej. Samo pobranie zajmie więc około 8 dni bez przerwy. Zakładam też, że baza produktowa będzie się zmieniać, tzn. będą uzupełniane nowe parametry oraz będą poprawiane błędy w już istniejących parametrach w bazie produktowej więc powinniśmy wszyscy aktualizować ją regularnie. A przy obecnych czasach odpowiedzi podpinanie ofert do produktów jest w praktyce bardzo kłopotliwe.

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację.

**Comment by barthoos** [comment]
Zeby potwierdzic, ze tomylee0 nie jest w tym osamotniony - ja tak samo rozwiazalem to po swojej stronie. Juz na froncie w tle odpytuje restapi o produkt, zeby uzytkownikowi podpowiedziec kategorie allegro + wartosci parametrow w przypadku wybrania tej kategorii. Przy wystawianiu paczek setek produktow nie wyobrazam sobie tak dlugich czasow odpowiedzi. Plus tak jak wskazal przedmowca - my po naszej stronie musimy w miare na biezaco odswiezac te informacje produktowe, bo parametrow jest tyle, ze trzeba zalozyc ze moze sie to zmienic w kazdym momencie. 

A sensowe cache'owanie tego nie jest mozliwe, bo nie mamy przeciez wersjonowania parametrow (ktore moglibysmy sobie powiazac z info dot. produktu). 

Tak w ogole to ja tutaj nawet zapostowalbym o funkcjonalnosc parowania wielu produktow jednoczesnie na podstawie przeslanej tablicy EANow. Bo bez tego i "standardowe" czasy odpowiedzi moga okazac sie zdecydowanie za dlugie.

**Comment by MartaNowaczyk** [comment]
@barthoos Zbieramy zapotrzebowania w tym temacie, także dziękuję za informację. Przekazałam gdzie trzeba.

**Comment by tomylee0** [comment]
W obawie przed zamknięciem wątku chciałbym zapytać czy możemy liczyć na poprawę szybkości odczytywania danych z bazy produktowej?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Nie, dla wybranych zasobów REST API stosujemy dodatkowy mechanizm, który ogranicza liczbę zapytań dla danego użytkownika. Już niedługo opublikujemy o tym informację w dokumentacji. Proszę o trochę cierpliwości.

**Comment by barthoos** [comment]
No to w druga strone - czy udostepnicie mozliwosc odpytywania o wiele EANow jednoczesnie?

**Comment by MartaNowaczyk** [comment]
Nie udostępniamy takiej możliwości i nie mamy tego w planach.
