### ISSUE TITLE
get seller offers (sandbox)

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1636]
https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

Próbuję wyszukać oferty na koncie po nazwie (parameter name), mimo wpisania wyrazu, który na pewno wstępuje w tytule oferty nie otrzymuję żadnych wyników.
Kolejna rzecz to sortowanie, zgodnie z dokumentacją używam np. `sellingMode.price.amount (ASC)` przepuszczonego przez `urlencode`, wyniki są zwracane ale nie są posortowane.

Url wygląda następująco: `https://api.allegro.pl.allegrosandbox.pl/sale/offers?sort=sellingMode.price.amount+%28ASC%29`

Tak na marginesie to dało by się to zrobić lepiej, jednen parametr odpowiedzialny za pole po którym wyszukujemy, drugi za kierunek sortowania, np. `sortField=price&sortOrder=asc`.

**Comment by MartaNowaczyk** [comment]
@j4r3kb tworzysz błędne url z sotowaniem. Powinno być:
- sellingMode.price.amount - sortowanie po cenie rosnąco,
- -sellingMode.price.amount - sortowanie po cenie malejąco, 

GET https://api.allegro.pl.allegrosandbox.pl/sale/offers?sort=sellingMode.price.amount 

Do wyszukiwania po nazwie skorzystaj z:

https://api.allegro.pl.allegrosandbox.pl/sale/offers?name=test

Jeśli nadal dostajesz błąd podaj pełne zapytanie.

**Comment by j4r3kb** [comment]
Ok tyle, że jeszcze wczoraj w dokumentacji https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET była tam informacja ENUM i cały tekst był wrzucony razem z (ASC) i (DESC) po spacji, widzę że już poprawiliście ;]

**Comment by j4r3kb** [comment]
"/sale/offers?limit=1000&offset=0&sort=&name=&sellingMode.format=&sellingMode.price.amount.gte=100000&sellingMode.price.amount.lte="

powoduje błąd 400
`400 Error when searching seller offer (sellerId: 43962322, searchCriteria: {"sellingMode.price.amount.gte":"100000","sellingMode.format":""}).`

w dodatku nie jest zwracana ta odpowiedź jako json

**Comment by MartaNowaczyk** [comment]
> Ok tyle, że jeszcze wczoraj w dokumentacji https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET była tam informacja ENUM i cały tekst był wrzucony razem z (ASC) i (DESC) po spacji, widzę że już poprawiliście ;]
Jak i wyszukiwanie po nazwie...

Prawda, akurat wczoraj mieliśmy poprawkę tych elementów. Przepraszamy za wprowadzenie w błąd. Pracujemy nad dopracowaniem dokumentacji

**Comment by MartaNowaczyk** [comment]
bo jest błędne zapytanie. Polecam [nasz poradnik](https://developer.allegro.pl/my_offers/) z przykładami. Jak się z nim zapoznasz i nadal będziesz miał problemy, napisz postaram się pomóc.
