### ISSUE TITLE
Czy istnieję możliwość usunięcia aplikacji api z konta allegro?

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#1637]
Przykładowo jeśli stworzę nową aplikacje na koncie allegro i wygeneruje kod Api, czy mam możliwość usunięcia tej aplikacji i stworzenia nowej , zakładając np. że wybrałem zły rodzaj aplikacji itp.

**Comment by MartaNowaczyk** [comment]
Możesz dodać wiele różnego typu, możesz też usuwać:

https://apps.developer.allegro.pl/
