### ISSUE TITLE
Sandbox - Zmiana numeru telefonu komórkowego

### ISSUE THREAD

**Issue by sq9atk** [allegro/allegro-api#1638]
:bulb: **Sugestia**

We właściwościach konta allegro jest pole na numer telefonu komórkowego. Jakimś cudem przy zakładaniu konta w tym polu udało mi się kilkakrotnie wpisać numer, który formatem nie pasuje do numeru komórki. 

A w mojej aplikacji: 
1. Pobieram nowe zamówienie poprzez RestApi do mojego systemu. 
2. Po obsłużeniu zamówienia w moim systemie próbuję utworzyć nową wysyłkę dla e-nadawcy Poczty Polskiej.
3. Numer komórki jest wymagany - numer z zamówienia nie pasuje bo ma inny format
4. Wchodze na allegro we właściwości testowego konta, z którego dokonałem zakupu na aukcji celem poprawienia numeru komórkoweo. 
5. Próbuję zmienić ten numer na jakiś komórkowy. Wymagane jest potwierdzenie kodem SMS. Podaję mój prawdziwy numer i czekam na esemesa z kodem, i czekam, i czekam, i czekam, i czekam... 

Może by tak zrezygnować tam z walidacji tego kodu albo sprawic żeby te esemesy docierały?

**Comment by MartaNowaczyk** [comment]
Jeśli błędne działanie dotyczy formularzy sandboxa zgłoś to proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)
