### ISSUE TITLE
[RestApi] tagi ofertowe przy wystawianiu aukcji - kto to wymyślił...

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1639]
:bulb: **Sugestia** Dlaczego w **POST /sale/offers/{offerId}/tags** nie można podać nazwy tagu jak to było w WebApi? 

Wymuszacie niepotrzebne przerabiane obecnego zapisu po stronie aplikacji.

I największe kuriozum, które aby dodać tagi do oferty nakazuje poczekać, aż ta fizycznie pojawi się w serwisie?! To jest niepotrzebne wydłużenie procesu wystawiania aukcji...

:bulb: **Sugestia** Dlaczego nie można podać tagów bezpośrednio w **PUT /sale/offers/{offerId}** ?

:bulb: **Sugestia** I w drugą stronę, dlaczego nie mogą być zwracane bezpośrednio w **GET /sale/offers/{offerId}** ?

**Comment by MartaNowaczyk** [comment]
nie można podać w ten sam sposób, bo REST API nie jest odzwierciedleniem 1:1 WebAPI.
To zarządzania i przypisywania tagów są [oddzielne zasoby](https://developer.allegro.pl/news/2018-09-24-tagi-zalaczniki). Po to by było wszystko w jednym miejscu i dlatego by nie łamać kompatybilności wstecznej.

**Comment by PhotoSoft** [comment]
Dlaczego RestApi nie odzwierciedla frontendu? Tam tagi podaje się od razu w formularzu, więc dodanie stosownego pola do **/sale/offers/{offerId}** nie jest chyba dużym problemem, a będzie ogromnym ułatwieniem.

I druga sprawa skąd mam wiedzieć czy do aukcji są przypisane tagi, żeby je pobrać? Wywołanie na ślepo **GET /sale/offers/{offerId}/tags** w przypadku, gdy konto nie ma aktywnego abonamentu wyrzuca wyjątek. To chyba nie oto chodzi, aby wywołać jakiś zasób i dopiero sprawdzić co się stanie - albo zwróci dane albo błąd.

**Comment by aktywnitu** [comment]
To by znacznie uprościło kodowanie.
@MartaNowaczyk, to jak Pani Marto, będzie tutaj jakaś zmiana, czy trzymać się aktualnego sposobu?

**Comment by MartaNowaczyk** [comment]
REST API nigdy nie będzie całkowitym odzwierciedleniem frontendu 1:1. 
Nie planujemy zmiany w tym temacie, także trzymajcie się aktualnego sposobu zarządzania tagami.

**Comment by aktywnitu** [comment]
To w sumie dobrze, bo już zaprogramowane. Proste.
