### ISSUE TITLE
Inne FIDy dla wymiarów w kategorii dywany

### ISSUE THREAD

**Issue by Radziasss** [allegro/allegro-api#164]
Czy dobrze widzę, że zmieniliście numery FIDów dla pól:

- **grubość** zamiast 20996 -> teraz 38627
- **długość** 21494 -> 37563
- **szerokość** 21495 -> 37439

w kategorii: Dom i zdrowie -> Dom i Ogród -> Wyposażenie -> Dywany i dywaniki -> Dywany pokojowe??

Czy ta zmiana była gdzieś wcześniej przez Was ogłaszana? Czy macie w planach zmianę kolejnych FIDów dla innych pól? Czy to normalne w API Allegro, że ot tak zmienia się numery FIDów?

**Comment by AniaMalinowska** [comment]
Tak, zmieniamy numery FIDów. Skorzystaj z metody [doGetSellFormFieldsForCategory](http://allegro.pl/webapi/documentation.php/show/id,782), dzięki której pobierzesz najświeższe dane.

**Comment by SoftSolid** [comment]
Po co to zmieniacie ?
Ja ma taki problem 24453 -> 34858 ?
Jeśli jest kilka tysięcy aukcji to potem trzeba kombinować żeby to jakoś hurtowo zmienić.

**Comment by AniaMalinowska** [comment]
O zmianach w parametrach informujemy [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).  Strukturę należy za każdym razem pobrać za pomocą metody, jaką wcześniej podałam ([doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782?cod=OGZkZlVlNmJk)).
