### ISSUE TITLE
Produktyzacja i zmiana domyślnych parametrów

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#1640]
Chciałbym się dowiedzieć jaki jest prawidłowy sposób wystawiania oferty z produktem, jeżeli potrzebuję zmienić jeden lub więcej domyślnych dla tego produktu parametrów?

Przykład: pobrałem za pomocą REST API i zasobu /sale/products?ean=XXXXXXXX szczegóły produktu, jednym z nich jest STAN: NOWY. Ja chciałbym wystawić ofertę z identycznymi ustawieniami produktu, ale ze stanem USZKODZONY. Czy powinienem więc wystawić ofertę bez podpiętego pod nią produktu, czy ofertę z produktem (czyli sposobem zalecanym na stronie https://developer.allegro.pl/productization/#important) i z dodatkowo zmienioną wartością parametru STAN na USZKODZONY?

Na Sandboksie, za pomocą REST API udało mi się  bez problemu wystawić ofertę tym drugim sposobem, ale gdy loguję się do panelu Allegro i wchodzę w edycję oferty widzę informację "Parametry w Twojej ofercie nie odpowiadają wybranemu produktowi" (załączam screenshot), według której powinienem usunąć produkt z oferty lub skorygować parametry na domyślne dla tego produktu - stąd moje pytanie, jak prawidłowo powinien wyglądać ten proces?

Z góry dziękuję.

![Screenshot_2](https://user-images.githubusercontent.com/13535917/57927568-b2262e00-78ae-11e9-93c9-ca0233cb7c57.jpg)

**Comment by TomekKaczmarek** [comment]
To błąd po naszej stronie, stan nie powinien być wypełniony przy produkcie. Zgłosiłem problem, wkrótce usuniemy ten parametr z tego produktu.

**Comment by alapnet** [comment]
Dziękuję za informację. Rozumiem, że zdefiniowany produkt, powinien zawierać w bazie Allegro tylko niezmienne właściwości (np. rozmiar, wagę), tak więc podobny przypadek jak ze stanem nie powinien się już powtórzyć. Natomiast gdyby wystąpił będzie to bug?

**Comment by TomekKaczmarek** [comment]
Tak, parametry przy produkcie powinny dotyczyć tylko produktu, jeśli zwracamy przy produkcie parametr typu Stan lub Dostawa z Polski - to jest to błąd, proszę go zgłaszać.
