### ISSUE TITLE
Brak oferty na aukcji - licytacji Sandbox

### ISSUE THREAD

**Issue by marta7142** [allegro/allegro-api#1641]
[Sandbox]

**Opis**
Aukcja w sandboxie: https://allegro.pl.allegrosandbox.pl/oferta/lodowka-do-zabudowy-electrolux-ern1300fow-6206320913 
sprzedaż została odnotowana, jednak w Koncie nie ma informacji o zakupie produktu - nie można więc wypełnić formularza dostawy i finalizować transakcji.

**Comment by MartaNowaczyk** [comment]
Jeśli problem nie dotyczy API allegro, a samego działania serwisu testowego zgłoś swój problem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt)
