### ISSUE TITLE
Dodanie trackingu do zamówienia

### ISSUE THREAD

**Issue by Filip4223** [allegro/allegro-api#1642]
Witam, próbuję zrobić webhooka integrującego ClickShop (shoper) z Allegro; potrzebuję dodać numer śledzenia paczki do zamówienia przez API Allegro, jednak API ClickShopu nie udostępnia id zamówienia w formacie UUID a jedynie deal_id (np. 2061235596) i transaction_id (np. 1017164670). Czy mogę na podstawie tych danych przesłać żądanie do tego zasobu? https://developer.allegro.pl/orders/#addTracking

**Comment by MartaNowaczyk** [comment]
Na podstawie deal_id i transaction_id nie dodasz numeru przesyłki tym zasobem
