### ISSUE TITLE
id parametrów SOAP a REST

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1644]
Czy jest jakiś sposób na zmapowanie parametrów po id, które były zwracane przez SOAP z tymi które są zwracane przez REST?
Z tego co widzę to nie pokrywają się one.

**Comment by MartaNowaczyk** [comment]
Parametry powinny być spójne i pole WebAPI:

<ns1:sellFormParamId>129278</ns1:sellFormParamId>

powinno odpowiadać zwracanym wartościom przez REST API.

**Comment by j4r3kb** [comment]
OK sądziłem że to `sellFormId`
