### ISSUE TITLE
Pobranie informacji o wizytach w danej ofercie

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#1645]
Proszę o naprowadzenie w jaki sposób poprzez REST API możemy pobrać ilość wizyt w danej ofercie. Nie chodzi o ilość sprzedanych przedmiotów tylko o ilość odsłon danej oferty. W WebAPI służyła do tego metoda doGetMySellItems (zwracała parametr itemViewsCounter). Nie mogę odnaleźć odpowiednika w REST API - proszę o pomoc

**Comment by MartaNowaczyk** [comment]
Nie ma takiego odpowiednika i nie planujemy go wprowadzać. Poza tym taka informacja nie jest już dawno widoczna w ofercie.

**Comment by kaki1979** [comment]
Witam, w dokumentacji (https://developer.allegro.pl/my_offers/) jak Byk jest informacja:

"visitsCount": 0              -- liczba odwiedzonych

Zarówno nazwa parametru, jak i jego 'opis' wyraźnie wskazuja na 'liczbę odwiedzin'.
Niestety nie jest to rzeczywista liczba odwiedzin, w wielu aukcjach widuję tam wartość mniejszą niż liczba 'obserwujących' co kompletnie nie ma sensu.

Prosze o dokładne wyjaśnienie wartości tego parametru oraz jego działanie (oraz poprawkę w dokumentacji)
Statystyki odwiedzin są bardzo ważnym parametrem podczas sprzedaży, pozwalają na ocenę zainteresowania produktem czy też opisem

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Dla visitsCount zwracamy dane tylko z 30 dni, także nie są to informacje o wszystkich wizytach w danej ofercie. Pisałam o tym w poprzednim wątku, tylko inaczej opisałam to pole.
