### ISSUE TITLE
Publish Command Dosen't Always Work

### ISSUE THREAD

**Issue by tvr121** [allegro/allegro-api#1646]
There is an issue with the publish command I think. I was trying to publish newly created offers in the following way:

payload = {
                    "offerCriteria": [
                        {
                            "offers": [
                                {
                                  "id": allergoID
                                }
                            ],
                            "type": "CONTAINS_OFFERS"
                        }
                    ],
                    "publication": {
                        "action": "ACTIVATE",
                    }
                }
request put url =https://api.allegro.pl/sale/offer-publication-commands/{commandID}

It works sometimes perfectly fine and sometimes it dosen't work for the new products. I tried this with previously created (published and ended) products, it work just fine without any issue.

Even for the new products (listed using API) which were not publishing using API call can be easily published using the website. So I can say there is no problem with the product settings.

Another thing as it works sometimes and work fine for the previous products, I can say my code is ok. 

Please check this from your end. Thank you.

**Comment by MartaNowaczyk** [comment]
I need more information. Could You send me file with request and response with your error call by [contact form](https://allegro.pl/pomoc/kontakt). Add issue number from GitHub #1646 in that message.
