### ISSUE TITLE
[REST API] brak możliwości uzyskania URL do wystawionej aukcji?

### ISSUE THREAD

**Issue by alananh** [allegro/allegro-api#165]
Zerknałem na dokumentację, ale nie widziałem nigdzie możliwości uzyskania linku do utworzonej i aktywowanej aukcji. Nie ma?

Nawiasem, wdrożenie aktywacji pojedyńczej aukcji było okrutne

[https://i.imgur.com/b0ZVeio.png](https://i.imgur.com/b0ZVeio.png)

**Comment by AniaMalinowska** [comment]
Nie ma jeszcze metody do pobrania listy swoich ofert w REST. Pracujemy nad tym, aby udostępnić taką metodę. 

Co do drugiej kwestii: możesz jednocześnie opublikować więcej ofert - nie tylko jedną. Nie jesteśmy, aż tak okrutni ;-)
