### ISSUE TITLE
Pytanie dotyczące autoryzacji - token dla danych prywatnych

### ISSUE THREAD

**Issue by montowniastron** [allegro/allegro-api#1650]
Robię importer aukcji z Allegro do Sklepu, wszystko już działa ładnie, mam jeden problem i nie wiem czy dobrze zrozumiałem dokumentację.

Za każdym połączeniem dostaję jeden token i za pomocą niego mogę pobierać "publiczne" dane.

Po zalogowaniu i autoryzacji (przekierowanie do Allegro, klikam, że udostępniam dane aplikacji XXX) dostaje drugi token do "prywatnych" danych.

I teraz pytanie chce żeby to leciało cronem automatycznie, a manualne kilkanie po token prywatny blokuję mi to... czy da się jakoś jednorazowo na stałe lub dłuższy okres czasu to uwierzytelnić?

**Comment by MartaNowaczyk** [comment]
Zapoznaj się proszę z naszym [poradnikiem](https://developer.allegro.pl/auth/). Aby uniknąć ciągłego autoryzowania użytkownika udostępniliśmy możliwość [przedłużenia ważności konta](https://developer.allegro.pl/auth/#refresh-token) za pomocą refresh_tokena.
