### ISSUE TITLE
Problem z aktualizacją pól w /sale/offers

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#1651]
Zauważyłem, że w /sale/offers nie są aktualizowane na bieżąco dane dla parametru visitsCount. Wygląda na to, że nie są aktualizowane informacje o wyświetleniach ofert, albo są aktualizowane z bardzo dużym opóźnieniem. Proszę o informację w jaki sposób można pobrać aktualną wartość tego parametru??

**Comment by MartaNowaczyk** [comment]
@mateuszcom Zwróć uwagę, że każda wizyta oznacza unikalnego klienta, który wyświetla ofertę w ciągu 24 godzin. Jeśli odwiedzisz tę ofertę kilka razy w ciągu dnia to wartość się nie zmieni.
