### ISSUE TITLE
Zapytanie o sposób autoryzacji Device flow dla Allegro OAuth

### ISSUE THREAD

**Issue by zulugula08** [allegro/allegro-api#1652]
Witam,

Mam zapytanie o sposób autoryzacji Device flow dla Allegro OAuth
Rozumiem że na początku powinienem sparować swój driver id z kontem poprzez wejście na stronę i autoryzacje poprzez kod i to właśnie uczyniłem. Jeśli już mój driver id jest autoryzowany to mogę sobie pobrać tokena na 12h. Jak już czas przydatności tokena minie to znowu muszę autoryzować kolejny driver id, czy na tym samym pobieram nowy token?

jeśli mogę na tym samym pobrać nowy token to dlaczego mam komunikat zwrotny?

`stdClass Object
(
    [error] => invalid_request
    [error_description] => Invalid device code
)
`

Jeśli muszę autoryzować nowy driver id to co 12 h musiałbym otwierać przeglądarkę i rejestrować mój kod? To trochę bez sensu jeśli aplikacja miałaby działać na serwerze w konsoli o robić coś cyklicznie.

**Comment by mateuszcom** [comment]
Rest API umożliwia przedłużenie ważności tokeny dzięki parametrowi refresh_token. Tutaj masz wszystko opisane: https://developer.allegro.pl/auth/#refresh-token

**Comment by zulugula08** [comment]
Dzięki kolego, bardzo trafna uwaga :) (co prawda pod koniec dokumentacji i po kolejnym rodzaju autoryzacji, który już mnie za bardzo nie interesował). Ale teraz mam inny problem, mianowicie gdy próbuję odświeżać token to dostaję błąd "Error decoding access token"

Oczywiście koduję client id i secret z dwukropkiem a refesh_token daję w url próbowałem go dać w url też jako base64_encode lub base64_decode i to samo :/

**Comment by gslpro** [comment]
Słabo już pamiętam, bo to dawno było, ale ja chyba miałem podobny problem, bo wysyłałem złe nagłówki,
chodziło o "content-type" w prawie całym api ma być "*json" a tylko przy autoryzacji "application/x-www-form-urlencoded".

**Comment by zulugula08** [comment]
Próbuje bez tego i to samo zastanawiam sie czy dobrze pobrałem token refresh mam ustawiony typ varchar(2000) wiem ze access token jest mniejszy jak 1000 znaków wiec raczej zmieścił mi sie cały

**Comment by MartaNowaczyk** [comment]
@zulugula08 jak chcesz możesz podesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1652 pełne curle z requestem i responsem. Sprawdzimy i damy znać.

**Comment by zulugula08** [comment]
Dziękuję wszystkim serdecznie za pomoc. Faktycznie miałem problem z odświeżeniem tego tokena, nie potrafię sobie wytłumaczyć dlaczego, ale wygenerowałem zupełnie nowy token i device id, sparowałem z swoim kontem i odświeżyłem kilka razy z powodzeniem. Gdyby podobna sytuacja zdarzyła mi się w przyszłości to będę zgłaszał problemy.
