### ISSUE TITLE
Problem z autoryzacją na sandboxie ("Nie możemy wyświetlić strony")

### ISSUE THREAD

**Issue by retrowaver** [allegro/allegro-api#1653]
Mam zarejestrowaną aplikację. Chcę zalogować się do niej jako użytkownik.

Wchodzę zatem na adres:
`https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=...&redirect_uri=...`

wpisuję login/hasło i otrzymuję błąd `Nie możemy wyświetlić strony` wraz z numerem błędu (ostatni to `9311915bb9dc4f0d`).

Dodatkowe informacje:

* konto sandboxowe założone kilkadziesiąt minut temu (login `jfdgjdifugdfj`, aktywowane przez link w mailu i "płatność" - w `Aktywacja konta` jako `Status konta` wyświetla się `Sprzedaż aktywna - wpłata online`,
* redirect_uri jest zgodny z tym w aplikacji
* gdy robię to samo w serwisie produkcyjnym (`https://allegro.pl/auth/oauth/authorize`, reszta linku dokładnie taka sama), autoryzacja działa bez zarzutu, tj. otrzymuję response z access tokenem

**Comment by MartaNowaczyk** [comment]
Na pewno korzystasz z danych z aplikacji dla sandboxa?

**Comment by retrowaver** [comment]
Heh, nie. Oczywiście teraz wszystko działa, przepraszam za kłopot.
