### ISSUE TITLE
GET /sale/offers => filtrowanie po EAN

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#1654]
Czy zamierzacie dodać filtrowanie po EAN do metody `GET /sale/offers` ? Czy może jest już takie filtrowanie tylko w jakiejś innej metodzie ?

**Comment by MartaNowaczyk** [comment]
@pietrach możesz uzasadnić twoją potrzebę, żebym mogła przekazać konkretne argumenty do zespołu, który zajmuje się tym obszarem?

**Comment by pietrach** [comment]
W celu aktualizacji ilości szt. w danej ofercie. Mam np. produkt w swoim systemie, który jest powiązany EANem z ofertami Allegro i chce wyszukać takie oferty i zaktualizować im ilości

**Comment by MartaNowaczyk** [comment]
Dziękuję, przekazałam sugestię do odpowiedniego zespołu.

**Comment by rtnet-pl** [comment]
@pietrach od jakiegos czasu mozna wyszukiwac w /offers/listing po ean. Co prawda nigdzie oficjalnie nie jest to udokumentowane, byc moze jest to ograniczone tylko do pewnych kategorii, ale dziala.
