### ISSUE TITLE
Prośba o dodane w parametrach kategorii "Serwery" - Stan - "Odnowiony"

### ISSUE THREAD

**Issue by Nateck** [allegro/allegro-api#1655]
:bulb: **Sugestia**
Dodanie tej opcji jest moim zdaniem bardzo niezbędne, w ofercie jest dużo sprzętu odnowionego, który różni się funkcjonalnością i sprawnością praktycznie wcale od nowego (nieużywanego), a podpinanie pod "używany" to już może sugerować, że sprzęt jest nie sprawdzony, nie przetestowany, nie wyczyszczony i z ograniczoną funkcjonalnością. Ewentualnie proszę o uruchomienie w REST API możliwości własnej parametryzacji

**Comment by MartaNowaczyk** [comment]
@Nateck najpierw taka możliwość musi znaleźć się w samym allegro, dopiero później w API. W takim wypadku zgłoś to na początek jako opcję na allegro przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by yncki** [comment]
@MartaNowaczyk 
masakra, sama niech Pani zgłosi przecież pracuje Pani w Allegro.

**Comment by Nateck** [comment]
@yncki korporacja

**Comment by Nateck** [comment]
@MartaNowaczyk zespół dodał już dodatkowe opcje parametru, proszę zaimplementować je do REST API

**Comment by MartaNowaczyk** [comment]
@Nateck parametr jest też dostępny w REST API. Możesz to sprawdzić przez wywołanie GET /sale/categories/258709/parameters

**Comment by Nateck** [comment]
Wszystko zrobione, dzięki. Można wątek zamykać
