### ISSUE TITLE
Powrót problemu złej ceny - doGetItemsInfo

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#1657]
8098752383 - zwraca 70 zł, a na aukcji: 262,98 - zakończona ponad godzinę temu
i tak się dzieje z co drugą aukcją

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i zwracamy poprawnie aktualną cenę w <ns1:itPrice>262.98</ns1:itPrice>

Jeśli nadal masz problemy podeślij proszę request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1657
