### ISSUE TITLE
Oferta nie istnieje mimo braku błędów

### ISSUE THREAD

**Issue by damianholak** [allegro/allegro-api#1658]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od pewnego czasu nie jestem w stanie wystawić żadnej z moich ofert. Wszystkie drafty tworzone są bezproblemowo. Tak samo ma się sprawa z ich aktywacją.

Trace id aktywacji:
46ee066c-91e9-52df-eb40-793fe5ffb69d

Draft oraz jego aktywacja przebiegają bez przeszkód. W tym momencie (do jutra) nie posiadam dostępu do pełnego zarządzania kontem więc nie mogę podać innych danych aniżeli wynik sprawdzenia statusu aktywacji oraz pliku JSON zwracanego po utworzeniu szkicu. Kształt żądania CURL niezmieniany od początku roku.
Wynik aktywacji /sale/offer-publication-commands/ (46ee066c-91e9-52df-eb40-793fe5ffb69d) dla konta 42014627:

array(1) {
  ["tasks"]=>
  array(1) {
    [0]=>
    array(7) {
      ["offer"]=>
      array(1) {
        ["id"]=>
        string(10) "8115985817"
      }
      ["message"]=>
      string(0) ""
      ["status"]=>
      string(7) "SUCCESS"
      ["scheduledAt"]=>
      string(23) "2019-05-20T17:05:00.45Z"
      ["finishedAt"]=>
      string(24) "2019-05-20T17:10:00.323Z"
      ["field"]=>
      string(11) "publication"
      ["errors"]=>
      array(0) {
      }
    }
  }
}

Czy istnieje możliwość wstępnego sprawdzenia na podstawie konta oraz guid co może być przyczyną braku publikacji?

**Comment by MartaNowaczyk** [comment]
Z tego co widzę oferta jest aktywna. Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem draftu oferty, którego nie możesz aktywować. Dodaj informację, że zgłoszenie dotyczy GitHub #1658. Sprawdzę w czym jest problem.

**Comment by damianholak** [comment]
Dziękuję za przyjrzenie się problemowi. Niestety przez bardzo długi czas
oferta nie była widoczna w serwisie i stąd moje zgłoszenie. Teraz
rzeczywiście jest już widoczna i problem sam się rozwiązał. Jeżeli zauważę
problem w przyszłości - niezwłocznie zbiorę request oraz response.
Zgłoszenie na chwilę obecną do zamknięcia.

wt., 21 maj 2019 o 10:33 MartaNowaczyk <notifications@github.com>
napisał(a):
