### ISSUE TITLE
Sporadyczny błąd "Could not change offer publication status" bez szczegółów

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1660]
Po utworzeniu draftu oferty i natychmiastowej zmianie statusu na ACTIVE otrzymuję czasem w rezultacie zadania publikacji informację "Could not change offer publication status"  bez dodatkowych szczegółów o przyczynie niepowodzenia zmiany statusu.
Przypuszczam, że powodem jest błąd wewnętrzy Allegro, gdyż ponowienie tych dwóch operacji kończy się sukcesem. Czy moglibyście uzupełnić szczegóły błędów dla mogącego tutaj wystąpić wyjątku?

**Comment by MartaNowaczyk** [comment]
Możemy, tylko podeślij proszę request i response z tym błędem, żebyśmy mogli sprawdzić przyczynę powstania tego błędu. Podeślij przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1660

**Comment by aktywnitu** [comment]
A mogą być przykładowe task uuids (produkcja):
6d6311b2-7bc6-414f-a8c4-f23400cbc4cf
3c0f3a70-eb21-4645-93ef-57ebfb69f8c2
bc9d523d-1a9b-4d23-b48b-e149f22fb5b2
da7dcfaa-d76a-45ab-a36f-1e213a0d087f

**Comment by MartaNowaczyk** [comment]
lepiej chociaż trace-id
