### ISSUE TITLE
Dodatkowe filtry:  GET /order/checkout-forms

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#1661]
Sprawa dotyczy końcówki GET /order/checkout-forms
Mamy tu już 2 filtry:
lineItems.boughtAt.lte
lineItems.boughtAt.gte

Jednak status READY_FOR_PROCESSING może pojawić się znacznie później niż data w boughtAt.
Przykladowo jak klient zapłaci sobie np 3 dni po czasie kupienia przedmiotu.

Z tego powodu powstaje problem, bo np jak chcialbym pobierać checkout formy tylko ze statusem READY_FOR_PROCESSING i ustawię sobie np filtr na 24 godziny, to mogę w powyższej sytuacji pominąć checkout form takiego klienta (najpierw będzie w innym statusie a potem nie załapie się na filtr na boughtAt). Zatem limit czasowy należałoby wydłuzyć, np do 72 godzin. Problem jednak w tym, że równie dobrze klient może sobie zaplacić np po miesiącu, a wydłużając limit w nieskończoność automatycznie zwiększam liczbę żądań do api (bo paginacja jest po max 100 wynikow na raz).

Zatem czy moglibyście dodać filtry payment.finishedAt.lte i payment.finishedAt.gte by uniknąć tego problemu? Oczywiście mam nadzieję, że jak jest status READY_FOR_PROCESSING  to zawsze jakiś payment.finishedAt będzie?

**Comment by AssAssIn1909** [comment]
Gdzieś to już było poruszane. 
Aktualnym rozwiązaniem jest przelecenie po eventach, bo tam wskoczy event z kiedy klient zapłacił i zmienił się status zakupu na READY_FOR_PROCESSING.

**Comment by MartaNowaczyk** [comment]
@neldh Zgadzam się z AssAssIn1909 pobieranie kolejnych eventów na pewno wyeliminuje problem zmienności danych przy tym samym zapytaniu ze względu na filtr i zmienne statusy.

Jeśli chodzi o nowy filtr, przekazałam twój pomysł do odpowiedniego zespołu.

**Comment by neldh** [comment]
ech..... Przelatywanie po eventach wymaga podania id eventu od którego zaczynamy przelatywanie i szybko robi się jeszcze więcej żądań (eventy w końcu nie zwracając wszystkich danych, które zwraca ta końcówka). Ja wiem że tak się da (no i nawet robię podobnie), ale mi raczej chodziło o to, żeby dodać ten filtr, żeby zmniejszyć ilość żądań. W obecnej konfiguracji pobieram i eventy i checkout formy i  uzupełniam braki pobierając pojedyncze checkout formy. Niemniej jednak i tak generuje to dużo żądań. A nie mogę sobie pozwolić na robienie tego raz dziennie.

Obecnie ustawienie na zasobie GET /order/checkout-forms statusu READY_FOR_PROCESSING nie ma najmniejszego sensu bez filtrów takich jak payment.finishedAt.lte i payment.finishedAt.gte.

Dziękuję za przekazanie mojej sugestii.

**Comment by skrux1** [comment]
https://github.com/allegro/allegro-api/issues/1482 było poruszane i do dziś brak odpowiedzi, programiści Allegro wolą wylać kawę na serwer niż zrobić coś sensownego :-)

**Comment by MartaNowaczyk** [comment]
Analizujemy możliwość uruchomienia takiego filtra.

**Comment by neldh** [comment]
podbijam. Jak tam analiza?

**Comment by PawelTaberski** [comment]
Jeśli otrzymamy informacje o wdrożeniu takiego filtra to poinformujemy o tym w dedykowanym komunikacie.

**Comment by neldh** [comment]
Ponownie podbijam. Ostatnio też ktoś o to pytał tutaj. Niepotrzebnie zmuszacie nas do dodatkowych zapytań do waszego api. Jest szansa, że dodacie te filtry?

**Comment by PawelTaberski** [comment]
Niedawno dodaliśmy do odpowiedzi z zasobu GET /order/checkout-forms payment.finishedAt dla zamówień opłaconych z góry. Jednakże do obsługi zamówień zalecamy przede wszystkim zapięcie się na GET /order/events aby nie pominąć żadnego zdarzenia. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#02).

**Comment by neldh** [comment]
No ja rozumiem. Już niejednokrotnie o tym pisałem zresztą... Do pobierania transakcji używam w tej chwili obu końcówek, bo GET /order/events nie zwraca wszystkich danych które zwraca GET /order/checkout-forms i po obu koncówkach zaciągam jeszcze brakujące GET /order/checkout-forms/{uuid} i zapisuje id eventu sobie w bazie, ale naprawdę filtr finishedAt na GET /order/checkout-forms byłby zbawieniem. I chodzi mi o filtr, a nie o to kiedy to zwracacie a kiedy nie. I wydaje się po pojawiających się tu issues, że naprawdę nie jestem jedynym potrzebującym. Czy dodanie tego filtru to naprawdę takie ciężkie zadanie?

**Comment by PawelTaberski** [comment]
Rozumiem, oczywiście sugestię przekazałem, jeśli otrzymam informacje, że wdrożymy taką zmianę, to poinformujemy o tym w odpowiednim komunikacie.
