### ISSUE TITLE
Obsługa błędów

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#1662]
:bulb: **Sugestia**
Dlaczego obsługa błędów nie jest ujednolicona? [Tutaj](https://developer.allegro.pl/about/#errors) napisaliście, że zawsze błędne wywołanie API zwraca tablicę błędów _errors_, natomiast jeżeli wywołam jakiś zasób bez podania _access_tokena_ to mam odpowiedź:
`{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}`

**Comment by MartaNowaczyk** [comment]
W takich przypadkach jak autoryzacja, odpowiedź błędu jest taka, bo jesteśmy zgodni ze specyfikacją oauth2 -> https://tools.ietf.org/html/rfc6749#page-22 paragraf 4.1.2.1.  Error Response.
