### ISSUE TITLE
Uszkodzone konta sandbox

### ISSUE THREAD

**Issue by marmizg** [allegro/allegro-api#1663]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją

URI         : https://api.allegro.pl.allegrosandbox.pl/sale/offers/6205698051
Response body: {"errors":[{"code":"NOT_FOUND","message":"Not Found","details":null,"path":"/sale/offers/6205698051","userMessage":null}]}

URI         : https://api.allegro.pl.allegrosandbox.pl/sale/offers/6205660578
Response body: {"errors":[{"code":"NOT_FOUND","message":"Not Found","details":null,"path":"/sale/offers/6205660578","userMessage":null}]}

Dla w/w kont na sandbox po wyklikaniu kilku aukcji i zakupie przez nie zarejestrowanego użytkownika przy próbie pobrania... zawsze pojawia się błąd 404

**Comment by MartaNowaczyk** [comment]
Oferty są widoczne na sandboxie, dlatego nie powinno być takiego błędu. Sprawę zgłosiłam do odpowiedniego zespołu.

**Comment by marmizg** [comment]
Czekam z utęsknieniem ;-)

**Comment by marmizg** [comment]
> 
> 
> Oferty są widoczne na sandboxie, dlatego nie powinno być takiego błędu. Sprawę zgłosiłam do odpowiedniego zespołu.

Jakieś wieści z frontu ?

**Comment by MartaNowaczyk** [comment]
sprawa w toku

**Comment by marmizg** [comment]
Wygląda jakby "odpowiedni zespół" zadziałał... konta ożyły.
Dziękuje za pomoc
