### ISSUE TITLE
Zmiany w układzie kategorii i używanie starych identyfikatorów kategorii w REST API

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#1664]
Zauważyłem, że po zmianie w układzie kategorii wg informacji z https://allegro.pl/dla-sprzedajacych/zmiany-w-ukladzie-kategorii-ksiazki-i-komiksy-WEVme4xk2I4 wciąż możemy w REST API używać nieistniejących już identyfikatorów kategorii. 

Np. wystawiając nowego drafta z nieistniejącym już identyfikatorem kategorii 91849 (Kultura i rozrywka > Książki i Komiksy > Literatura piękna, popularna i faktu > Biografie, wspomnienia > Duchowni) Allegro wewnętrznie zamienia identyfikator na nową kategorię 261197 (Kultura i rozrywka > Książki i Komiksy > Literatura piękna > Biografie, wspomnienia).

I tak to wygląda teraz. Ale czy tak będzie zawsze? Tzn. czy jest planowany dzień w którym Allegro nie przyjmie starych identyfikatorów kategorii jak np. 91849 i podczas wystawiania nowego drafta zwróci błąd o nieistniejącym identyfikatorze?

Potrzebuję tej informacji, żeby wiedzieć czy muszę zmieniać swoje wewnętrzne mapowanie kategorii.

**Comment by MartaNowaczyk** [comment]
Jeśli ktoś próbuje wystawić w kategorii która została skasowana to podmieniamy ją na poprawną - kiedyś zwracaliśmy 404 i było to uciążliwe. NA ten moment nie zamierzamy zmieniać tego zachowania.
Najlepiej jednak sprawdzać i dbać o poprawne id kategorii.

**Comment by tomylee0** [comment]
Dziękuję za odpowiedź. Pozdrawiam.
