### ISSUE TITLE
Jak pobrać informacje o produkcie

### ISSUE THREAD

**Issue by adriantalaga** [allegro/allegro-api#1665]
Mam dostęp do listy ofert z zasobu 
`GET https://api.allegro.pl/offers/listing?phrase=xiaomi`

Tam mam widzę jest coś takiego np:

`{
  "items": {
    "promoted": [],
    "regular": [
      {
        "id": "8018878572",
        "name": "Etui wsuwka XIAOMI BLACK SHARK",
        "seller": {
          "id": "33576545",
          "company": true,
          "superSeller": false
        }`

Więc mam id oferty.

Jak pobrać dane tej oferty? W zasadzie potrzebuje tylko url oferty.

Próbowałem 
`GET https://api.allegro.pl/sale/products/8018878753`

ale dostaję
`"error": "insufficient_scope",
  "error_description": "Insufficient scope for this resource",
  "scope": "offercore-service product-facade offer-product-suggester"`

`Response code: 403 (Forbidden); Time: 107ms; Content length: 156 bytes`

Bardzo proszę o nakierowanie. Przeczytałem całą dokumentację i nigdy nie udaje mi się dostać do zasobów oferty inaczej niż przez listing. Nie jestem sprzedawcą chce mieć dostęp tylko ogólny taki jak do:

``GET https://api.allegro.pl/offers/listing?phrase=xiaomi``

**Comment by adriantalaga** [comment]
Wiem już jak dostać url oferty:

`https://allegro.pl/oferta/{id}`

Ale pytanie nadal aktualne. Jak dostać szczegóły oferty znając id?

**Comment by MartaNowaczyk** [comment]
@adriantalaga nie udostępniliśmy jeszcze zasobów w REST API do pobierania szczegółów oferty. Mamy to w planach, ale nie mamy dokładnego terminu.

**Comment by mbiernatek** [comment]
Czy w dalszym ciągu nie ma możliwości pobrania szczegółów oferty przy pomocy REST API?

**Comment by PrzemyslawLukanowski** [comment]
@mbiernatek Szczegóły dot. przyszłości tej funkcjonalności podamy w Q3, zgodnie z naszym [harmonogramem](https://developer.allegro.pl/schedule/).
