### ISSUE TITLE
Zamówienia nie są widoczne po ukończeniu

### ISSUE THREAD

**Issue by lruszkie** [allegro/allegro-api#1667]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od wczoraj jest problem na środowisku sandbox - po zakupie z oferty, wypełnieniu formularza, dokończeniu płatności - zamówienie nie pojawia się na liście zamówień. 
Nie jest również pobrane poprzez dziennik zdarzeń REST API.
Przykładowy numer płatności:
8776cb30-7c53-11e9-93a9-275d0798d97d
lub wczorajsza - fa0c4670-7be0-11e9-93a9-275d0798d97d

**Comment by MartaNowaczyk** [comment]
Rzeczywiście mieliśmy taki błąd. Wczoraj udało nam się poprawić działanie sandboxa i zamówienia powinny się już pojawiać w panalu allegro i przez REST API.

**Comment by lruszkie** [comment]
Zamówienia faktycznie pojawiły się w panelu Allegro.Sandbox.
Jeśli chodzi o REST API - zdarzenia są zwrócone niekompletnie.
Np. dla zamówienia: 46876ba1-7c87-11e9-ba3b-e5154fe59643 - utworzonego wczoraj około 13:50, API zwraca wyłącznie zdarzenie READY_FOR_PROCESSING.
Nie ma zdarzenia BOUGHT i FILLED_IN.
W dalszym ciągu testowanie nie przebiega poprawnie. 
Przykładowy url żądania: /order/events?from=1558519812910565
Zwraca jedno zdarzenie dla tego zamówienia.
Poproszę o weryfikację problemu.

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o wczorajsze zdarzenia z okresu, w którym występowały problemy dane mogą być niekompletne.
