### ISSUE TITLE
Migracja webAPI -> RestAPI - błędy

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1668]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

1. Wystawiam ofertę przez WEBAPI, wypełniam tam pole AdditionalInfo
2. Migruję się z WEBAPI do RestAPI, pole nie jest zwracane przez RestAPI

 https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206360773 \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json'
  
trace-id →72d7323d880a40e1
date →Mon, 20 May 2019 12:36:24 GMT
content-type →application/vnd.allegro.public.v1+json;charset=UTF-8

  "delivery": {
        "shippingRates": null,
        "handlingTime": "PT48H",
        "additionalInfo": "",
        "shipmentDate": null
    },

**Comment by MartaNowaczyk** [comment]
@SebastianOzdoba w ofercie https://allegro.pl.allegrosandbox.pl/oferta/komplet-black1-6206360773#shippingInfo nie widzę w sekcji Dostawa i płatność dodatkowych informacji. Jeśli je dodałeś, a ich nie ma prześlij proszę XMLa z requestem i responsem.

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk  faktycznie masz rację, to w webAPI jest błąd

W XML jest: field id="27" val="Dodatkow informacje o przesyłce i płatności" />
aukcja webAPI -> https://allegro.pl.allegrosandbox.pl/oferta/halowki-dzieciece-6206364442?item=6206364442 (nie ma na GUI)
aukcja restAPI -> https://allegro.pl.allegrosandbox.pl/oferta/so-komplet-black-6206364445?item=6206364445 (jest poprawnie na GUI)
