### ISSUE TITLE
W jaki sposób pobrać listę etykiet

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#1669]
Tak jak w tytule próbuję pobrać listę etykiet danego użytkownika jednak nigdzie w dokumentacji nie potrafię znaleźć informacji na ten temat.

**Comment by PawelTaberski** [comment]
Co masz na myśli mówiąc o etykietach masz na myśli tagi ofertowe, jeśli tak informacje o tym jak nimi zarządzać znajdziesz w [naszym poradniku.](https://developer.allegro.pl/sale/#tags)

**Comment by mikllero** [comment]
Gdzie znaleźć w API listę przypisanych etykiet do danej oferty? (Nie chodzi o tagi, chodzi o etykiety).
