### ISSUE TITLE
ERR_OBLIGATORY_ATTRIB_NOT_SET - Allegro Paczka w RUCHu (kolejna sztuka) - fid: 214

### ISSUE THREAD

**Issue by emesio** [allegro/allegro-api#167]
Dzień dobry,

od około godz. 15 próbując wystawiać lub edytować aukcje otrzymuję błąd:

ERR_OBLIGATORY_ATTRIB_NOT_SET</faultcode><faultstring>Nie podano parametru wymaganego dla wybranej kategorii. (Allegro Paczka w RUCHu (kolejna sztuka) - fid: 214)

Tymczasem:
a) w tych aukcjach nie używam takiej metody wysyłki (Allegro Paczka w RUCHu).
b) dla kilku kategorii które sprawdziłem pola (np. 19004) pobierając doGetSellFormFieldsForCategory - i taki FID (214) w ogóle w nich nie występuje. Jest 213 a potem 236.

Mogą Państwo na to rzucić okiem?

**Comment by pgasidlo** [comment]
Mam ten sam problem - nagle jest oczekiwane pole, które nigdzie nie jest opisane.

**Comment by artzie92** [comment]
U mnie to samo ;/

**Comment by imper86** [comment]
u mnie ten sam problem :|

**Comment by AniaMalinowska** [comment]
Weryfikujemy ten problem, przepraszamy za zamieszanie.

**Comment by jovand** [comment]
U mnie to samo, dodam jeszcze że w ogóle niema takiego parametru w danych pobranych za pomocą metody **doGetSellFormFieldsExt**

**Comment by emesio** [comment]
Szybko przyszło, szybko poszło. Dziękuję za poprawkę.

**Comment by AniaMalinowska** [comment]
Przepraszamy za utrudnienia. Jak wspomniał @emesio problem nie powinien już występować. 
Dziękujemy za czujność.
