### ISSUE TITLE
[WebAPI->REST]: Nowy termin wygaszania kluczowych metod - CZYTAJ !

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1670]
:bulb: **Sugestia**
W tym wątku: https://github.com/allegro/allegro-api/issues/1597
... jest chyba wystarczająca ilość argumentów za tym, że NIE WOLNO wyłączać kluczowych elementów WebAPI do obsługi ofert i sprzedaży, dopóki nie zostaną spełnione rzeczy jak niżej:
- pełna, stabilna i produkcyjna wersja zasobów REST-API - zastępująca wszystkie dotychczasowe funkcjonalności WebAPI oraz pozwalająca na kompleksowe przejście aplikacji na jeden, nowy API
- ujednolicenie składni / logiki i semantyki / nazw wartości, pól i argumentów, a także naniesienie tego wszystkiego do jednolitego systemu obsługi błędów REST wraz z poprawną dokumentacją
- wykonanie wszelkich testów wydajnościowych i optymalizacja systemu REST pod obciążeniem.

Jak to wszystko zostanie spełnione - dopiero możecie wyznaczyć nowy termin wygaszania metod WebAPI, z minimalną karencją 3-6 miesięcy, inaczej wszyscy (również Wy) poniosą duże straty !!

**Comment by solokazama** [comment]
ja nie wiem jak to bedzie, jezeli nie zostanie data przesunieta.
niektore metody w REST dzialaja z blednami.
o nowej (jednakze s tarym API) metodzie i jej bledzie (dodawanie nr paczki kurierskiej i pustym response zawsze) czekam informacje od 27 dni i ciagle tylko "prosze jeszcze poczekac".

MASAKRA, az sie chce to rzucic calkowicie.

**Comment by swift13** [comment]
ostnio wyłączyli parametry jak paramtry pobierasz przez rest api do nie można ich uzyć w webapi . bo system placze ze nie podano paramteru stan fid-x a resta api mam stan jako fid-y. poprostu zajebiście

**Comment by MartaNowaczyk** [comment]
@swift13 podaj proszę przykład
