### ISSUE TITLE
doGetSiteJournalDealsInfo nie działa !

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1671]
obojetnie jaki deal_event_it ustawimy jako startowy, to zawsze zwraca:

stdClass Object
(
    [deal-events-count] => 0
    [deal-last-event-time] => 0
)

**Comment by centrumelektroniki** [comment]
Wysłaliśmy opiekunowi XML-a, proszę o pilne zajęcie się problemem, klienci czekają na swoje paczki.

**Comment by TomekKaczmarek** [comment]
Dzień dobry,

Nie mogę powtórzyć błędu - otrzymałem nazwę użytkownika mailowo i sprawdziłem nastepujęce wywołania:

DoGetSiteJournalDealsInfo - bez punktu startowego
Request 
`      <ser:DoGetSiteJournalDealsInfoRequest>
         <ser:sessionId>{sessionId}</ser:sessionId>
      </ser:DoGetSiteJournalDealsInfoRequest>
`
Response
`      <ns1:doGetSiteJournalDealsInfoResponse>
         <ns1:siteJournalDealsInfo>
            <ns1:dealEventsCount>18</ns1:dealEventsCount>
            <ns1:dealLastEventTime>1558527888</ns1:dealLastEventTime>
         </ns1:siteJournalDealsInfo>
      </ns1:doGetSiteJournalDealsInfoResponse>
`

DoGetSiteJournalDealsInfo - z punktem startowym
Request 
`      <ser:DoGetSiteJournalDealsInfoRequest>
         <ser:sessionId>4d99be140a56c0212d6dd504f36a05a35da6012a0bcc68//00_1</ser:sessionId>
         <ser:journalStart>4660076858</ser:journalStart>
      </ser:DoGetSiteJournalDealsInfoRequest>
`
Response
`      <ns1:doGetSiteJournalDealsInfoResponse>
         <ns1:siteJournalDealsInfo>
            <ns1:dealEventsCount>11</ns1:dealEventsCount>
            <ns1:dealLastEventTime>1558527888</ns1:dealLastEventTime>
         </ns1:siteJournalDealsInfo>
      </ns1:doGetSiteJournalDealsInfoResponse>
`

Proszę się upewnić, czy odpytujecię metodą dla odpowiedniego użytkownika, który na pewno ma zakupy,
