### ISSUE TITLE
Rozliczenia z Allegro - historia opłat

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#1673]
Potrzebujemy pole "numer operacji" lub inny unikalny identyfikator rekordów generowanych w raporcie rozliczenia z allegro. Taki jak co najmniej od 2007-12-06 do 2019-02-18 był dodawany do generowanego raportu CSV przez stronę https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro

**Comment by MartaNowaczyk** [comment]
Przekazałam twoją sugestię do zespołu, który zajmuje się tematem opłat.

**Comment by centrumelektroniki** [comment]
Jaki czas operacyjny żeby uzyskać odpowiedź ?

**Comment by MartaNowaczyk** [comment]
Dostałam informację, że nie planujemy dodania takiego ID. Możesz opisać do czego ci on jest potrzebny?

**Comment by centrumelektroniki** [comment]
po tym numerze identyfikujemy unikalność rozliczenia, żeby podczas dodawania do bazy nie było duplikatów

**Comment by centrumelektroniki** [comment]
Będę wdzięczny za sugestię jak rozwiązać nasz problem, to Państwo zmieniliście strukturę pliku.

**Comment by PawelTaberski** [comment]
Przekazałem Twoją sugestię do zespołu, który pracuje nad tą funkcjonalnością.

**Comment by centrumelektroniki** [comment]
Dzięki Paweł, w takim razie czekamy na info z niecierpliwością.

**Comment by centrumelektroniki** [comment]
Witam ponownie,
ruszyło coś w temacie ?

**Comment by MartaNowaczyk** [comment]
Otrzymałam potwierdzenie, że nie planujemy przywrócenia tego identyfikatora, także będzie potrzebna zmiana logiki w państwa aplikacji.

**Comment by centrumelektroniki** [comment]
Kiedy będzie można pobierać "te dane" przez API ? a może już się da ?

**Comment by PrzemyslawLukanowski** [comment]
@centrumelektroniki  Tak jak MartaNowaczyk wcześniej napisała - nie planujemy dodania takiej funkcjonalności, będzie potrzebna zmiana logiki w Państwa aplikacji.

**Comment by centrumelektroniki** [comment]
trudno o logikę, skoro podajecie w tych zestawieniach tylko:
Data;Nazwa oferty;Id oferty;Typ operacji;Uznania;Obciążenia;Saldo;ID operacji

proszę o informację czy "numer operacji" definitywnie jest skasowany z tych zestawień ? oraz proszę o wskazanie w którym komunikacie informowaliście o tych zmianach.

**Comment by PrzemyslawLukanowski** [comment]
@centrum W tym kwartale planujemy wystawić na API nowu zasób - historię operacji bilingowych. Gdy go udostępnimy, sprawdź czy otrzymasz potrzebne dane.

**Comment by centrumelektroniki** [comment]
Przemek, możesz uchylić rąbka tajemnicy co będzie zawierać ten zasób ? do końca kwartału jeszcze trochę czasu zostało, więc znów musimy czekać, tylko dalej nie wiemy czy rozwiąże to nasz problem.

**Comment by PawelTaberski** [comment]
Jeszcze nie znamy ostatecznego kształtu tego zasobu. Jak tylko będzie to możliwe opiszemy go i poinformujemy o jego wdrożeniu w dedykowanym komunikacie.

**Comment by mojeq** [comment]
> 
> 
> Jeszcze nie znamy ostatecznego kształtu tego zasobu. Jak tylko będzie to możliwe opiszemy go i poinformujemy o jego wdrożeniu w dedykowanym komunikacie.

Czy jest lub będzie dostęp przez REST API do Historii operacji aby możliwe było po numerze aukcji sprawdzić opłaty i prowizje dotyczące konkretnego przedmiotu?

**Comment by PrzemyslawLukanowski** [comment]
@mojeq Aktualnie nadchodzące opłaty dotyczące konkretnej oferty możesz sprawdzić za pomocą zasobu GET /pricing/offer-quotes/{offerId}. W trzecim kwartale planujemy wdrożyć zasoby związane z historią operacji billingowych oraz sprawdzaniem kosztów oferty.Więcej na temat planowanych zmian znajdziesz w naszym [harmonogramie wygaszania WebAPI](https://developer.allegro.pl/schedule/).

**Comment by centrumelektroniki** [comment]
Czy już coś wiadomo kiedy dokładnie te zasoby i w jakiej formie będą udostępnione przez API ?

**Comment by mojeq** [comment]
ściągania opłat i prowizji jest zasób https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST

**Comment by PrzemyslawLukanowski** [comment]
@centrumelektroniki Zasoby, o których piszesz, powinny zostać udostępnione w REST API do końca września 2019.

**Comment by Bodzix** [comment]
Czyli będzie można pobrać wysokość naliczonej prowizji od sprzedaży przy użyciu ID oferty, podobnie jak przy korzystaniu z zasobu GET /pricing/offer-quotes ?
Pytam ponieważ zastanawiam się czy jest sens pisania obsługi przy użyciu /pricing/offer-fee-preview które jest niezbyt wygodnym rozwiązaniem do ustalenia wysokości faktycznych opłat dla istniejącej oferty.

**Comment by PrzemyslawLukanowski** [comment]
@Bodzix Weryfikuję ten temat, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@Bodzix Masz świadomość, że GET /pricing/offer-quotes to nie historia opłat, ale szacunkowa wycena na ten moment?

**Comment by Bodzix** [comment]
Tak, oczywiście. Właśnie tego potrzebuje, jednak nie znalazłem zasobu, który wprost informowałby mnie o prowizji od sprzedaży dla danego produktu. /pricing/offer-quotes oferuje jedynie sprawdzanie kosztów wystawienia, promocji itp.

**Comment by PrzemyslawLukanowski** [comment]
@Bodzix Aktualnie nie mamy w planach takiego zasobu. Twoją sugestię zgłosiłem do odpowiedniego zespołu.

**Comment by centrumelektroniki** [comment]
> @centrumelektroniki Zasoby, o których piszesz, powinny zostać udostępnione w REST API do końca września 2019.

Paweł miesiąc się kończy, zdążycie ?

**Comment by PrzemyslawLukanowski** [comment]
@centrumelektroniki Wciąż nad tym pracujemy, zasób powinien pojawić się w ciągu kilku najbliższych miesięcy.

**Comment by centrumelektroniki** [comment]
> @centrumelektroniki Wciąż nad tym pracujemy, zasób powinien pojawić się w ciągu kilku najbliższych miesięcy.

według Waszego harmonogramu miało być skończone na koniec września, skąd te opóźnienia skoro piszesz kilka miesięcy ?  skoro to tyle trwa, przywrócicie stary zasób na web API do tego czasu ?

**Comment by PrzemyslawLukanowski** [comment]
Wciąż nad tym pracujemy, określone przeze mnie kilka miesięcy to górna granica wprowadzenia zasobów. Metody WebAPI są wciąż dostępne:
- [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301) - sprawdzenie kosztów oferty,
- d[oMyBilling](https://allegro.pl/webapi/documentation.php/show/id,109) - saldo,
- zbiór metod dot. [Allegro Finanse](https://allegro.pl/webapi/documentation.php/theme/id,65).

**Comment by centrumelektroniki** [comment]
> Wciąż nad tym pracujemy, określone przeze mnie kilka miesięcy to górna granica wprowadzenia zasobów. Metody WebAPI są wciąż dostępne:
> 
> * [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301) - sprawdzenie kosztów oferty,
> * d[oMyBilling](https://allegro.pl/webapi/documentation.php/show/id,109) - saldo,
> * zbiór metod dot. [Allegro Finanse](https://allegro.pl/webapi/documentation.php/theme/id,65).

Przemku, przekopiuję pierwszego naszego posta o co nam dokładnie chodzi:

"Potrzebujemy pole "numer operacji" lub inny unikalny identyfikator rekordów generowanych w raporcie rozliczenia z allegro. Taki jak co najmniej od 2007-12-06 do 2019-02-18 był dodawany do generowanego raportu CSV przez stronę https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro"

ta informacja została skasowana i nie jest aktualnie nigdzie udostępniona, w żadnym zasobie.

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie mogę poinformować, że zasób będzie zwracać unikalny identyfikator każdego rekordu. O wdrożeniu zasobu poinformujemy w odpowiednim komunikacie.
