### ISSUE TITLE
Problem z /sale/offer-publication-commands/

### ISSUE THREAD

**Issue by mushira** [allegro/allegro-api#1676]
Dzień dobry,

Mam utworzony draft, validatory nie zwracają żadnych błędów, a przy próbie publikacji otrzymuję zwrotkę PUT:

  object(stdClass)#45 (1) {
    ["errors"]=>
    array(1) {
      [0]=>
      object(stdClass)#84 (5) {
        ["code"]=>
        string(5) "ERROR"
        ["message"]=>
        string(21) "An error has occurred"
        ["details"]=>
        NULL
        ["path"]=>
        string(69) "/sale/offer-publication-commands/usunieto-46a2-572b-9899-5da4142d3ca9"
        ["userMessage"]=>
        NULL
      }
    }
  }

Przy próbie odczytania statusu/błędów GET ('/sale/offer-publication-commands/usunieto-46a2-572b-9899-5da4142d3ca9', '/sale/offer-publication-commands/usunieto-46a2-572b-9899-5da4142d3ca9/tasks') otrzymuję:

  object(stdClass)#36 (1) {
    ["errors"]=>
    array(1) {
      [0]=>
      object(stdClass)#41 (5) {
        ["code"]=>
        string(17) "COMMAND_NOT_FOUND"
        ["message"]=>
        string(0) ""
        ["details"]=>
        NULL
        ["path"]=>
        string(0) ""
        ["userMessage"]=>
        string(23) "Nie znaleziono zlecenia"
      }
    }
  }

**Comment by MartaNowaczyk** [comment]
Potrzebuję pełnych danych do weryfikacji. Możesz podesłać pełne curle z requestem i responsem  przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1676

**Comment by mushira** [comment]
@MartaNowaczyk właśnie wysłałem. Dziękuję za szybką odpowiedź i pomoc!

**Comment by mushira** [comment]
@MartaNowaczyk zgłoszenie: "05483040"

**Comment by mushira** [comment]
Znalazłem błąd składniowy w danych wysyłanych metodą /sale/offer-publication-commands/
