### ISSUE TITLE
[REST API} Problem z usunięciem oferty INACTIVE - pomimo usunięcia wciąż jest na liście

### ISSUE THREAD

**Issue by Nateck** [allegro/allegro-api#1677]
Na stronie (panel użytkownika allegro.pl) usunąłem z listy INACTIVE (draft) ofertę przez opcję "USUŃ". Po tym zdarzeniu wciąż jest widoczna na liście, nie da się jej ponownie usunąć ani edytować, a jednak przez REST API jest na liście /sale/offers?publication.status=INACTIVE&limit=100.
Dla przykładu: 8114054488

Co mam zrobić by się nie listowała?

**Comment by Nateck** [comment]
Gdy wywołuję w REST API przez DELETE to komunikat jest: {"errors":[{"code":"NOT_FOUND","message":"Not Found","details":null,"path":"/sale/offers/8114054488","userMessage":null}]}

jednak jak odpytuje o liste INACTIVE to się pojawia na niej.

**Comment by PawelTaberski** [comment]
Podeślij proszę id-ki draftów z którymi masz taki problem, czy tylko z tym jednym (8114054488)? Sprawdzimy to.

**Comment by dziuba** [comment]
Problem zauważyłem u siebie również. Szkice usunięte z poziomu allegro i rest pozostają na liście.
Jednocześnie ich edycja lub powtórna próba usunięcia nie działa. 
W przypadku, gdy szkic jest dostępny do edycji a zostanie usunięty przez api zwracany jest status 204, czyli niby ok. 

Przykładowe szkice, które nie reagują:

- 8118667598

- 8115724882

- 7960103925

**Comment by PawelTaberski** [comment]
@dziuba Dzięki za dane zgłosiłem numery ofert do odpowiedniego zespołu, prośba o cierpliwość.

**Comment by damianholak** [comment]
Jeżeli problem będzie wymagał zewnętrznej, manualnej interwencji to proszę o informację dla reszty użytkowników - dziś mogę już usuwać (przynajmniej ręcznie) szkice, co było niemożliwe w ostatnich dniach. Nadal jednak mam masę draftów usuwanych wcześniej poprzez REST API, i tych właśnie za nic nie można usunąć z listy szkiców - ani z poziomu portalu (brak reakcji), ani też z poziomu api (code":"NOT_FOUND")

**Comment by PawelTaberski** [comment]
@damianholak Dostałem informację, że problem udało się rozwiązać, daj znać, czy u Ciebie teraz jest ok.

**Comment by damianholak** [comment]
@PawelTaberski Wpisy o usuniętych szkicach zniknęły więc problem w moim przypadku jest rozwiązany. Dziękuję za informację i rozwiązanie problemu.

**Comment by Nateck** [comment]
Wszystko ok
