### ISSUE TITLE
Dokumentacja swagger

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1678]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

Prośba o dodanie do dokumentacji informacji jakie wartości min - max przyjmują dane pola liczbowe np. cena, ilość. Tak byśmy mogli w naszych aplikacjach automatycznie walidować pola, a nie hardkodować

**Comment by MartaNowaczyk** [comment]
Zgłoszone do dodania tych informacji w dokumentacji

**Comment by alekskuc** [comment]
Dzień dobry, ponawiam prośbę o uzupełnienie dokumentacji swagger.yaml o wartości minimalne i maksymalne dla cen i ilości.
