### ISSUE TITLE
Oferty: webAPI -> restAPI - niewidoczne

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1679]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

1. Wystawiam aukcję przez webAPI
https://allegro.pl.allegrosandbox.pl/show_item.php?item=6206364913
2. Próbuję pobrać listę ofert przez restAPI - w restAPI brak tej oferty

curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers?publication.status=ACTIVE&sellingMode.format=BUY_NOW%2CADVERTISEMENT%2CAUCTION&limit=25&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer CIACH' \

{
    "offers": [
        {
            "id": "6206364442",
            "name": "Halówki dziecięce",
            "category": {
                "id": "120"
            },
        CIACH,
            "publication": {
                "status": "ACTIVE",
                "startingAt": null,
                "startedAt": "2019-05-23T06:25:45Z",
                "endingAt": "2019-05-30T06:25:45Z",
                "endedAt": null
            },
CIACH
        },
        {
            "id": "6206364088",
            "name": "Chłodnica",
            "category": {
                "id": "253533"
CIACH,
            "publication": {
                "status": "ACTIVE",
                "startingAt": null,
                "startedAt": "2019-05-22T16:04:54Z",
                "endingAt": null,
                "endedAt": null
            },
CIACH
],
    "count": 2,
    "totalCount": 2
}

4. Natomiast metoda od szczegółów już zwraca tą aukcję:

curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206364913' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer CIACH' \
{"id":"6206364913","name":"Pasek pleciony AD mobile_comarchesklep","category":
CIACH
validation":{"errors":[],"validatedAt":"2019-05-23T10:55:16.589Z"},"createdAt":"2019-05-23T10:55:16Z","updatedAt":"2019-05-23T10:55:51.671Z"}

Proszę o pilną poprawę
@MartaNowaczyk

**Comment by MartaNowaczyk** [comment]
Sprawdzamy dlaczego na liście ofert nie ma oferty z paskiem.
