### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by MagdalenaNieckula** [allegro/allegro-api#1680]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzisiaj od około północy pojawiły się błedy w związku z wystawianiem produktów. Produkty wystawiane są jak do tej pory, wszystkie niezbędne dane (atrybuty) są uzupełnione. Niestety nie możemy wystawiać aukcji dla wielku kategorii, pomimo aktualizacji drzewa kategorii. Tutaj przykład komunikatu, który się pojawia
![image](https://user-images.githubusercontent.com/36264517/58256928-2742a900-7d70-11e9-93da-1a9a1a010dc6.png)

**Comment by MartaNowaczyk** [comment]
proszę o więcej informacji. Na początek podaj chociaż kategorię w jakiej próbujesz wystawić ofertę i występuje dokładnie ten błąd ze zrzutu.

**Comment by MagdalenaNieckula** [comment]
Czy kategorie na sandoboxie są odbiciem lustrzanym tych produkcyjnych? Bo jeśli tak nie jest to znaleźlismy przyczynę problemu:)

**Comment by MartaNowaczyk** [comment]
Tak, na środowisku testowym mogą występować różnice w kategoriach w porównaniu do produkcji.  Możesz podać przykład?

**Comment by MagdalenaNieckula** [comment]
Zatem już wiem skąd wczorajsze błedy. Pobieralismy kategorie real time z komta produkcyjnego wystawają na sandbox:) Wszystko jasne:)
