### ISSUE TITLE
Zmiana id niektórych kategorii?

### ISSUE THREAD

**Issue by Iapeace** [allegro/allegro-api#1681]
Dzień dobry,
ostatnio dostaję następujące zwrotki z API Allegro:
`Category '89750' not found`
Kategorię o takim id znajduje pod adresem:
[https://allegro.pl/kategoria/89750](url), a w linku widnieje nowe id czyli 261100. Nie dotyczy to oczywiście tej jednej kategorii. Czy ta zmiana id niektórych kategorii jest na stałe, a jeśli tak, to czy jest możliwość udostępnienia listy mapowań ze starych kategorii na nowe?
Z góry dziękuję za odpowiedź.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Nie udostępniamy mapowania kategorii. W takiej sytuacji najlepiej jednak sprawdzać i dbać o poprawne id kategorii.
