### ISSUE TITLE
Cannot convert access token to JSON

### ISSUE THREAD

**Issue by pwaszkis** [allegro/allegro-api#1683]
Wiem że podobne przypadki były zgłaszane wcześniej, ale w odpowiedziach nie udało mi się znaleźć rozwiązania dla mojego problemu. Próbuję na różne sposoby połączyć się z interfejsem Allegro (przez CURL i aplikację) i za każdym razem otrzymyję odpowiedź:

`{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}`

Przykładowe zapytanie wygląda następująco:

`curl -X GET 'https://api.allegro.pl/order/events' -H 'authorization: Bearer eyJ...7rC(tutaj pełen access_token otrzymany po uwierzytelnieniu)' -H 'accept: application/vnd.allegro.beta.v1+json'`.

Będę wdzięczny za wszelkie wskazówki co może być przyczyną mojego problemu.

**Comment by PawelTaberski** [comment]
Wygląda jakbyś korzystał z tokena na sandboxie i chciał go wykorzystać na produkcji. Rozkoduj token i upewnij się, że korzystasz z właściwego.

**Comment by pwaszkis** [comment]
@PawelTaberski trafiłeś w sedno. Dzięki za rozwiązanie mojego problemu :)
