### ISSUE TITLE
wprowadzenie na białą liste

### ISSUE THREAD

**Issue by MagdalenaNieckula** [allegro/allegro-api#1685]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,
Piszę w imieniu mojego klienta sieci sklepów posiadającej blisko tysiąc punktów w całej Polsce.
Potrzebujemy by Państwo dodali Nasz adres IP na białą listę, ponieważ te  tysiąc punktów korzysta z jednego adresu IP i szybko wyczerpią limit zapytań . Przenosimy się w całości na REST API, jakich jeszcze Państwo informacji potrzebujecie by nam pomoc?

**Comment by PawelTaberski** [comment]
Tak jak odpisałem Tobie w #1347 jak tylko otrzymam informacje zapoznamy się z nimi i odpowiemy.

**Comment by MagdalenaNieckula** [comment]
Dzień dobry,
Czekamy już blisko dwa tygodnie od pierwszego zgłoszenia. W ubiegłym tygodnio potwierdzono mi mailowo, że zostaliśmy wprowadzeni na białą listę- jednak nie! Dzisiaj mamy z tego powodu pierwsza awarię, gdyż przekroczyliśmy limit zapytań. Kiedy możemy spodziewać się Państwa interwencji w tej sprawie. Dla Nas to na prawde bardzo istotna rzecz.

**Comment by PawelTaberski** [comment]
@MagdalenaNieckula Czy problem dalej występuje sprawdziłem i widzę obecnie na bieżąco prawidłowe odpowiedzi. Ponadto upewniłem się w odpowiednim zespole czy klucz został poprawnie przypisany.

**Comment by MagdalenaNieckula** [comment]
Panie @PawelTaberski  potrzebujemy wprowadzić jeszcze jeden adres, gdyż nasza aplikacja ma architekturę mikroserwisową  i mikroserwis znajduje się na innym serwerze. Przesłałam do Państwa adres ip mikroserwisu wraz ze wszystkimi niezbędnymi informacjami. Kiedy możemy spodziewać się dodania?

**Comment by PawelTaberski** [comment]
Przyjrzymy się temu zgłoszeniu i oczywiście odniesiemy się do niego. Czy w tym zgłoszeniu zaznaczyła Pani, że dotyczy wcześniej podanego IP, klucza i aplikacji? Jeśli nie prosiłbym dodać takie informacje.

**Comment by MagdalenaNieckula** [comment]
Ddoszedł Nam jeszcze jeden adres IP, który niezwłocznie musimy dodać:) Zaznaczyłam to w zgłoszeniu podałam tez wszelkie niezbędne informacje o które Państwo prosiliście. Co jeszcze moge zrobić by przyspieszyć proces?

**Comment by MagdalenaNieckula** [comment]
Ostatnio trwało to blisko 2 tygodnie tym razem nie możemy sobie pozowlić na taki czas oczekiwania, gdyż punkty pracują na tym rozwiązaniu

**Comment by PawelTaberski** [comment]
Gotowe :-)

**Comment by MagdalenaNieckula** [comment]
Rozumiem, że do  60 minut będzie widoczne?:)

**Comment by MagdalenaNieckula** [comment]
Narazie jeszcze otrzymujemy błąd mówiący o przekroczeniu liczby zapytań:(

**Comment by Magdalenanieckula1** [comment]
Dostałam niestety potwoerdzenie drogą mailową,że adres IP nie został dodany na białą listę. Czy można przysiepszyć proces?

**Comment by MagdalenaNieckula** [comment]
Panie @PawelTaberski  mamy niestety całą komunikację sparaliżowaną. Czy możemy liczyć na wsparcie, ostatnio czekaliśmy 2 tygodnie, aż Państwo zaakceptowali Nasz prośbe.

**Comment by PawelTaberski** [comment]
Dostałem informacje, od zespołu odpowiedzialnego za tą listę, że adres został dodany, sprawę wyjaśniam, proszę o cierpliwość. Odpowiemy mailowo.
