### ISSUE TITLE
informacja na temat sprzedanej ilości w /offers/listing

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#1686]
:bulb: **Sugestia**

Witam,
Wyszukując na Allegro widzę ile sztuk danego produktu zostało sprzedane. Niestety, przy wyszukiwaniu przez API za pomocą /offers/listing taka informacja nie jest dostępna, a powinna być jako stock.sold. 

Np. przy /sale/offers ta ilość jest właśnie dostępna jako stock.sold. 

Da radę dorzucić tą informcję do /offers/listing?

Sergiusz

**Comment by MartaNowaczyk** [comment]
@sbrzezin taka informacja nie jest widoczna na liście ofert, dlatego jeśli już, to może się pojawić w zasobach publicznego widoku oferty.

**Comment by sbrzezin** [comment]
Jak to nie jest widoczna? Informacja o sprzedanej ilości widoczna jest przy każdym produkcie w wynikach wyszukiwania na Allegro np. "158 osób kupiło". Wieć mogłaby też być dostępna w /offers/listing, który jest odpowiednikiem takiego wyszukiwania przez API.

**Comment by PawelTaberski** [comment]
@sbrzezin Taką informację znajdziesz w polu popularity:
```
                    },
                    "popularity": 0                 -- popularność oferty. W przypadku oferty
                                                    typu BUY_NOW jest to liczba zakupów od 
                                                    unikalnych użytkowników z ostatnich 
                                                    30 dni. W przypadku oferty typu AUCTION 
                                                    jest to liczba użytkowników, 
                                                    którzy biorą udział w licytacji. 
                },
```
Więcej informacji na temat tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by MartaNowaczyk** [comment]
@sbrzezin na liście ofert widzisz ile osób kupiło w ciągu 30 dni, a pytałeś o liczbę sprzedanych przedmiotów. Nie widzisz tam liczby zakupionych przedmiotów w danej ofercie, a 1 osoba mogła kupić więcej niż 1 przedmiot.
