### ISSUE TITLE
Sandbox POST sale/offers

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#1687]
request:
{
	"name": "cokolwiek",
	"publication": {
		"endingAt": "2019-05-24T09:00:30Z",
		"startingAt": "2019-06-24T09:00:30Z",
		"status": "INACTIVE",
		"endedBy": "USER"
	}
}

response:
{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "Forbidden",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
}
Proszę o odpowiedź dlaczego response jest forbidden

**Comment by MartaNowaczyk** [comment]
Nie korzystasz czasem z autoryzacji typu client credentials?

**Comment by adamTynski** [comment]
curl -X POST 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' -H 'authorization: Bearer eyJhbGcurl -X POST 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' -H 'authorization: Bearer {tutaj_poprawny_token_bo_w_getach_dziala}'   -H 'accept: application/vnd.allegro.public.v1+json' -H 'content-type: application/vnd.allegro.public.v1+json' -d '{"name":"cokolwiek","category":{"id":"15984"}}'

odpowiedź:

{"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by PawelTaberski** [comment]
@adamTynski Podaj proszę login swojego usera na sandboxie, sprawdzimy w czym jest problem.

**Comment by adamTynski** [comment]
po prostu: adamtynski

**Comment by PawelTaberski** [comment]
Konto nie było w pełni aktywowane, sprawdź proszę, czy teraz jest ok.

**Comment by adamTynski** [comment]
Bez zmian. Nadal jest forbidden

**Comment by adamTynski** [comment]
Utworzyłem na szybko nowe konto (user grafftest) i na nowym koncie jest dokładnie to samo. Czy w związku z powyższym oraz w związku z późnym poinformowaniem o wyłączeniu części WebAPI (17 maj) planowanym na 3.06 jest możliwe przesunięcie terminu wyłączenia WebAPI?

**Comment by adamTynski** [comment]
Ten sam błąd pojawia się dla https://api.allegro.pl/sale/offers Dodam tylko, że użytkownik SMA-Dekoria istnieje od dawna, podobnie jak od dawna jest wykorzystywane SOAP WebAPI dla tego użytkownika

**Comment by MartaNowaczyk** [comment]
@adamTynski Jeśli chodzi o poinformowanie o wyłączeniu WebAPI do obsługi ofert, to 17 maja było wysłane ostatnie przypomnienie w sprawie wygaszania. Informacje podajemy już od dawna i nie powinno być to dla nikogo zaskoczeniem.

Podeślij mi proszę pełne curle bez edycji treści przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1687, żebym mogła sprawdzić co jest nie tak.

**Comment by adamTynski** [comment]
Jeśli chodzi o poinformowanie o wyłączeniu WebAPI - informacja dotarła do mnie 17 września. I to zupełnie przez przypadek, gdyż osoby nietechniczne, otrzymujące informacje od Państwa drogą mailową nie są w stanie same określić czy informacje w mailu są na tyle ważne, by przekazać je programistom czy nie. W związku z powyższym proszę o pełną listę kanałów informacyjnych, którymi informujecie Państwo o zmianach, bym mógł z nich w przyszłości korzystać

**Comment by PawelTaberski** [comment]
@adamTynski  Wszelkie informacje o zmianach są publikowane na:

- GitHub-ie z labelką NEWS;
- Na stronie https://developer.allegro.pl/news/
- Na stronie https://allegro.pl/webapi/news.php
- a także w przypadku wygaszania danych metod mailowo do użytkowników/kluczy którzy korzystają z danych metod

**Comment by adamTynski** [comment]
kwestia 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' wyjaśniła się już - chodziło o niepoprawną metodę autoryzacji - https://developer.allegro.pl/auth/ (i w konsekwencji niewłaściwy token)

Jeśli chodzi o kanały komunikacyjne - dodałem sugestię:
https://github.com/allegro/allegro-api/issues/1729
