### ISSUE TITLE
[doGetSellFormFieldsForCategory] - Komu przeszkadza ta Metoda WebAPI ??

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#1688]
:bulb: **Sugestia**
Jak w temacie - czy po całej Waszej akcji namawiania do przejścia i korzystania z tej https://allegro.pl/webapi/documentation.php/show/id,782 metody, gdzie miało to być takim SUPER-Stabilnym i SUPER-Szybkim rozwiązaniem dla obsługi kategorii i parametrów, teraz znowu karzecie wyrzucić furę roboty do kosza ?? A co jest SENSOWNEGO w zamian na tym REST ??

**Comment by PawelTaberski** [comment]
W jaki sposób zarządzać kategoriami i parametrami przez REST API [znajdziesz w naszym poradniku](https://developer.allegro.pl/sale/#step-2).

**Comment by FromAnyHole** [comment]
@PawelTaberski - jest takie pojęcie "wsteczna kompatybilność", w tej sugerowanej przez Was do niedawna metodzie tylko numery FID przestają mieć znaczenie - reszta jest bardzo ważna, a pytanie brzmi:
- co by się stało, gdyby ta metoda była nadal dostępna przez 3-4 mies. ??

**Comment by PawelTaberski** [comment]
Zgodnie z informacjami jakie otrzymałeś w wątku #1682 na chwilę obecną nie planujemy przedłużenia terminu wygaszenia.

**Comment by GreGo69** [comment]
A ja mam pytanie: jaki ma sens wyłączanie dokumentacji bez podanawania odnośnika do odpowiadających web api - rest api metod? Współpracuję z programistą z Francji i po wyłączeniu metody chciałem znaleźć mu odpowiadającą metodę w rest api ale jak mam to zrobić skoro nawet nie wiem co stara metoda robiła bo już nie ma dostąpu do dokumentacji? Jaki to ma sens?

**Comment by PawelTaberski** [comment]
@GreGo69  Odpowiedniki metod znajdziesz w naszym poradniku [Jak zmigrować się na REST API](https://developer.allegro.pl/migration_guide/)

**Comment by neldh** [comment]
@PawelTaberski Odpowiedniki to nie dokumentacja webapi. Naprawdę nie widzicie różnicy?
