### ISSUE TITLE
checkout-forms przy payment=>status=>'FILLED_IN'

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#1689]
Występuje problem: /order/checkout-forms/ dla REST API

Podczas pobierania szczegółów zamówienia dla płatności rozpoczętej payment=>status=>'FILLED_IN'
w odpowiedzi nie ma danych klienta do zamówienia (mam tylko maila, login i numer telefonu.) Brak danych teleadresowych
W panelu na stronie Allegro dane są widoczne. W jaki sposób mogę pobrać te dane ?

checkoutForm_id = '217b2791-7e0b-11e9-875c-71ab62f6b3c6'

**Comment by MartaNowaczyk** [comment]
w tym momencie takie dane zwracamy tylko, gdy transakcja jest opłacona czyli przy statusie READY_FOR_PROCESSING. Mamy jednak na uwadze dodanie danych z konta dla podanego przez ciebie statusu, ale na pewno nie w ciągu najbliższych tygodni.
