### ISSUE TITLE
Różnice w kategoriach oraz parametrach pomiędzy REST i SOAP API

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#169]
Zauważyłem, że przy pobieraniu kategorii z wykorzystaniem REST API: https://developer.allegro.pl/documentation/#!/sale-endpoint/getCategoriesUsingGET dostaję inną strukturę drzewa niż przy SOAP API. Przykładowo w przypadku REST API zwracanych jest 9 kategorii głównych podczas gdy dla SOAP API jest ich aż 30. Dodatkowo cześć kategorii zamiast identyfikatora liczbowego ma uuid. Wygląda więc na to że utrzymujecie 2 drzewa. 

1) Czy identyfikatory liści (kategorii) z tego drzewa będą identyczne w obu przypadkach ? 
2) Czy lista parametrów dla danej kategorii będzie identyczna ? Czy są jakieś typy pól przeznaczone tylko dla określonego API (chodzi mi po głowie parametr string który zamierzacie wprowadzić) ?
3) W jaki sposób mam zmapować stare parametry: https://allegro.pl/webapi/documentation.php/show/id,782#method-output do nowych https://developer.allegro.pl/documentation/#!/sale-endpoint/getFlatParametersUsingGET_2

Z tego co zauważyłem wygląda to mniej więcej w ten sposób:
```
{
    id: <int> // wartość pola sellFormParamId
    ...
    dictionary: [
         {
             id: <int_1>_<int_2> // int_1 -> wartość pola sellFormParamId, 
                                 // int_2 -> jedna z wartości pola sellFormParamValues
             ...
         },
         ...
    ]
}
```
Czy dany sposób mapowania wartości jest poprawny ?

4) Co mam wrzucać do pól valuesIds, values oraz rangeValue podczas tworzenia aukcji ? Domyślam się, że valuesIds przeznaczone jest dla pól z typem dictionary, a values dla integer i float. Czy rangeValue ma swoją reprezentacje w SOAP API ? Czy istnieją pola w REST API gdzie konieczne jest uzupełnienie rangeValue ?

**Comment by kormichu** [comment]
5) Czy parametry sellFormParentId oraz sellFormParentValue są jeszcze używane w SOAP / REST API ? Nie widze żadnej reprezentacji tych pól w REST API

**Comment by kormichu** [comment]
6) Widzę że wartości parametrów różnią się dla SOAP i REST API. Chcąc zmapować obecnie zapisane musiałbym porównać pole sellFormOptsValues (dla SOAP API) z sellFormParamValues (REST API) https://allegro.pl/webapi/documentation.php/show/id,782#method-output :(

**Comment by PawelTaberski** [comment]
Poniżej odpowiedzi na Twoje pytania:

1. Tak - identyfikatory kategorii liści są identyczne (ale są reprezentowane jako string a nie liczba).
Drzewo kategorii w Rest API jest takie samo jak w Web API - z wyłączeniem tego, że zawiera dodatkowo działy główne Allegro (których w Web API brakuje)

2. Tak, listy parametrów w kategoriach są takie same (parametr stringowy wprowadzimy w obu API)

3. Tak, podany sposób mapowania na wartości słownikowe jest poprawny.
Parametry w Web API i Rest API są tymi samymi parametrami i posiadają takie same słowniki wartości (różnica jest tylko w identyfikatorach wartości, które w Web API są pozbawiane prefixu z identyfikatorem parametru)

4. valuesIds -> tutaj uzupełnij jeżeli atrybut jest słownikowy i podaj idki wybranych wartości
values -> tutaj podaj wartości int/float/i parametr stringowy
rangeValue -> tutaj podaj wartości dla parametrów zakresowych "od" "do"

5. Te pola nie są używane w REST API

6. sellFormId to identyfikator pola w formularzu w danej kategorii - jest to zaszłość, która nie jest używana w REST API.
W Web API identyfikator parametru znajduje się w polu sellFormParamId.
Identyfikatory wartości w Web API (z pominięciem prefixu parametru) znajdują się w polu sellFormParamValues.
Pole z web sellFormOptsValues jest zaszłością i nie jest już używane w REST API (łatwo zobaczyć różnice w kategorii 257248 parameterId 202833)
