### ISSUE TITLE
Czy mozna edytowac cene/ilosc zakonczonej oferty przed wznowieniem?

### ISSUE THREAD

**Issue by solokazama** [allegro/allegro-api#1690]
chce zaktualizowac cene oraz ilosc przed publikacja zakonczonej aukcji
**PUT /sale/offers/{offerId}.**

**JSON:**
{"id":xxxyy,"stock":{"available":10,"unit":"UNIT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":174,"currency":"PLN"}}}

**w response otrzymuje:**
code; VALIDATION_ERROR
message: Proszę podać nazwę oferty

jak podam nazwe, to dostaje blad o braku mozliwosci edycji kategorii po 12h (i tak dalej zapewne)

interesuje mnie zmiana tylko tych dwoch parametrow w aukcji, ktora jest zakonczona (status: ENDED)

Jest w ogole taka mozliwosc?

**tl;dr:**
Jak zmienic cene oraz ilosc sztuk zakonczone aukcji przed (ponowna) publikacja?

Czy musze pobrac cala strukture zamknietej aukcji, zmienic w/w 2 parametry (cene, ilosc) i wyslac znow cala strukture aukcji? (probowalem, ale INVALID_JSON, pomimo, ze walidatory twierdza, ze ok)

**Comment by PawelTaberski** [comment]
Edycję pojedynczej oferty opisaliśmy w [naszym poradniku tutaj](https://developer.allegro.pl/my_offers/#2). Powinieneś pobrać ofertę przy pomocy metody GET na zasobie sale/offers/{offerId} zmienić stock i price, a następnie opublikować ofertę ponownie jeśli jest kompletna. Czy w takim wypadku pojawia się Tobie błąd INVALID_JSON?

**Comment by solokazama** [comment]
> Edycję pojedynczej oferty opisaliśmy w [naszym poradniku tutaj](https://developer.allegro.pl/my_offers/#2). Powinieneś pobrać ofertę przy pomocy metody GET na zasobie sale/offers/{offerId} zmienić stock i price, a następnie opublikować ofertę ponownie jeśli jest kompletna. Czy w takim wypadku pojawia się Tobie błąd INVALID_JSON?

Dziekuje za informacje. Wszystko gra wg. w/w informacji - dzieki:)
Wczesniejszy INVALID_JSON wynikal z tego, ze jedna wartosc powinna byc jako tablica.
Bardzo pomocna bylaby informacja (zapewne kazdemu) aby rozdzielac kod bledu "INVALID_JSON" vs "INVALID_JSON_STRUCTURE" (bo json jest valid, tylko ma zle pole w strukturze)

Dla kogos kto bedzie ew. na tym etapie:
- pobieramy strukture aukcji **get /sale/offers/xxyyzz**
- podmieniamy wartosci ktore nas interesuja
- wysylamy CALA (pobrna wczesniej+podmiany) strukture put **/sale/offers/xxyyzz**

'typowe' ktore moga sie pojawic:
- INVALID_JSON - sam json ma poprawna strukture, ale jakas wartosc jest zle wpisana (np. ma byc glebiej w tablicy)
- "an error occured" - to pojawialo sie jak przypadkowo wyslany byl objekt zamiast stringa z jsonem (czyli bez json_encode) - czyli jak robilismy PUT z jakimis "smieciami"
