### ISSUE TITLE
Menedżer sprzedaży w Allegro Sandbox

### ISSUE THREAD

**Issue by sikorag** [allegro/allegro-api#1692]
Czy można uruchomić Menedżera Sprzedaży na Allegro Sandbox?

Chciałbym przetestować nadawanie oraz pobieranie przez REST API sygnatur (external_id) przypisanych do ofert.

**Comment by PawelTaberski** [comment]
Nie ma możliwości aktywowania Menedżera sprzedaży na środowisku testowym, ale w formularzu wystawiania oferty przez Moje Allegro jest również możliwość wprowadzenia sygnatury.

**Comment by sikorag** [comment]
Dziękuję za odpwiedź, nie widzę jednak takiej opcji przy wystawianiu oferty.
W jaki sposób mogę to zrobić?

**Comment by PawelTaberski** [comment]
Sygnaturę możesz wprowadzić przez formularz wystawiania odpowiednie pole jest zaraz pod tytułem oferty.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski  moim zdaniem pole było, od kilku dni jednak tego pola nie ma na sandbox na edycji oferty.

**Comment by PawelTaberski** [comment]
Sprawdziłem przed sekundą i pole sygnatura jest dostępne zarówno przy edycji jak i wystawieniu nowej oferty przez Moje Allegro na środowisku testowym.
Poniżej zrzut gdzie je znajdziesz:
![image](https://user-images.githubusercontent.com/36262735/58467646-5ecc9f00-813c-11e9-8e72-7c89fc63672c.png)

**Comment by SebastianOzdoba** [comment]
![image](https://user-images.githubusercontent.com/47886399/58468044-16fa4780-813d-11e9-87b4-26ab2f909ef0.png)

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Nie masz w pełni aktywnego konta. Wstępnie je aktywowałem, prześlij teraz jakieś dwa dowolne pliki przez zakładkę moje konto, aby zakończyć proces.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski dzięki, wysyłałem pliki

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Konto jest już w pełni aktywne teraz powinno być ok.

**Comment by sikorag** [comment]
Ja także nie widzę tego pola.
Proszę sprawdzić czy moje konto jest w pelni aktywowane. Login grzessik.

**Comment by PawelTaberski** [comment]
@sikorag Sprawdź proszę teraz konto również nie było w pełni aktywne

**Comment by sikorag** [comment]
@PawelTaberski Niestety nadal nie widzę tego pola.

**Comment by PawelTaberski** [comment]
@sikorag Musisz zmienić status konta na konto firma.

**Comment by sikorag** [comment]
Dziękuję, teraz już jest to pole :)
