### ISSUE TITLE
Problem z aktywacją ofert

### ISSUE THREAD

**Issue by damianholak** [allegro/allegro-api#1693]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas aktywacji niektórych ofert otrzymuję błąd:

An error occurred while trying to change the publication of the offer. Please try again later.

Przy aktywacji kilkuset (kilku tysięcy) ofert zdarza się że ich część (najczęściej poniżej 10, ale zdarza sie też znacznie więcej) nie mogą zostać aktywowane z takim właśnie statusem.

9ad01c72-4e82-edb0-e38f-e3564bec2a04 / d81a5d59-1d29-68fa-29f3-2dffc75468d1

Kilkunastokrotne wywoływanie zasobu nie pomaga, ciągle występuje ten sam problem. Request, response oraz status dołączam mailowo.

**Comment by PawelTaberski** [comment]
Czy sprawdzałeś zadanie przy pomocy zasobu:
/sale/offer-publication-commands/{commandId}/tasks
Jaką informacje tam otrzymujesz?
Więcej na temat tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/##offer-publication-commands-commandId-tasks).

**Comment by damianholak** [comment]
Tak, wynik przesłałem w załączniku formularza kontaktowego.

array(1) {
  ["tasks"]=>
  array(1) {
    [0]=>
    array(7) {
      ["offer"]=>
      array(1) {
        ["id"]=>
        string(10) "xxxxxxxxxx"
      }
      ["message"]=>
      string(94) "An error occurred while trying to change the publication of the offer. Please try again later."
      ["status"]=>
      string(4) "FAIL"
      ["scheduledAt"]=>
      string(24) "2019-05-24T19:05:45.646Z"
      ["finishedAt"]=>
      string(24) "2019-05-24T19:05:56.451Z"
      ["field"]=>
      string(11) "publication"
      ["errors"]=>
      array(0) {
      }
    }
  }
}

**Comment by PawelTaberski** [comment]
Jeszcze nie otrzymałem danych jakie przesłałeś, a jesteś pewny że oferta jaką próbujesz aktywować jest kompletna? Przy jej edycji nie otrzymujesz żadnych informacji w sekcji errors?

**Comment by damianholak** [comment]
Tak, oferta jest kompletna i nie zawiera żadnych błędów.

Zapytanie poprzez formularz wysłałem 24.05.2019 21:28

Otrzymałem odpowiedź 25.05 o godzinie 15:37. Numer zgłoszenia to 05497868.

**Comment by damianholak** [comment]
W wiadomości po wywołaniu zasobu aktywacyjnego widniej standardowa zwrotka:

{"id":"9ad01c72-4e82-edb0-e38f-e3564bec2a04","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by PawelTaberski** [comment]
@damianholak Mógłbym prosić, abyś jeszcze raz podesłał te dane przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Bo ich nie otrzymałem. Zaznacz proszę, że dane są potrzebne do ticketa numer 1693 na GitHub-ie.

**Comment by Rebellious83** [comment]
Czy coś wiadomo już dlaczego nie działa aktywacja ofert przez rest Api ? 
Środowisko testowe.

Przesyłam Body i Response do zapytania
PUT
https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/d7df2a45-d541-4375-9c23-0698f5a5e649

Body :
{
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "6206440184"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ],
  "publication": {
    "action": "ACTIVATE",
    "scheduledFor": "2019-07-03T15:10:00Z"
  }
}

Response

{
    "id": "d7df2a45-d541-4375-9c23-0698f5a5e649",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}

Wynik 201 Created , lecz sprawdzając w sekcji moje oferty , status oferty to "szkic " zamiast już "w trakcie aktywacji" , wykonując publikacje oferty przez stronę wszystko działa .

**Comment by PawelTaberski** [comment]
@Rebellious83 Sprawdzałeś może status tego zadania przy pomocy zasobu GET /sale/offer-publication-commands/{commandId}/tasks
Co otrzymujesz w odpowiedzi?

**Comment by Rebellious83** [comment]
Pustą tablicę

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem. Sprawę zgłosiłem do odpowiedniego zespołu do naprawy.
