### ISSUE TITLE
Problem z uzyskaniem tokenu dostępowego do API

### ISSUE THREAD

**Issue by SHOPPING-CASE** [allegro/allegro-api#1694]
Witam Mam problem z uzyskaniem tokenu dostępowego do API , zarejestrowałem już aplikację , mam CLIENT ID oraz CLIENT SEECRET  Nie wiem dokładnie jak napisać skrypt, który pobierze token i gdzie skopiować kod do pliku o którym mowa w instrukcji. Bardzo proszę o pomoc Dziękuję i pozdrawiam

**Comment by PawelTaberski** [comment]
Nie prowadzimy wsparcia w kodowaniu, jednakże nie wiem czy zapoznałeś się już może z [naszym poradnikiem z przykładami gotowych fragmentów kodu](https://developer.allegro.pl/getting_started/).
Dodatkowo więcej informacji o samym procesie uwierzytelniania i autoryzacji znajdziesz [tutaj](https://developer.allegro.pl/auth/).
