### ISSUE TITLE
PUT /sale/offers/{offerId} wymaga "id"

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1696]
Niepodanie "id" w json body powoduje poniższy błąd, niestety w dokumentacji jest informacja o nie wymagalności, a doświadczenie pokazuje, że ten parametr jednak jest wymagany :trollface:  
{'errors': [{'code': 'VALIDATION_ERROR',
   'message': 'Offer id cannot be changed.',
   'details': '',
   'path': '',
   'userMessage': 'Offer id cannot be changed.'}]}

**Comment by yncki** [comment]
no jak to, przecież zarządzanie ofertami jest w wersji public i gotowe do implementacji od roku. 🗡 
Allegro ?

**Comment by PawelTaberski** [comment]
Zgodnie z naszym poradnikiem:
"..Na początek możesz pobrać ofertę, którą chcesz edytować za pomocą metody GET na zasobie sale/offers/{offerId}. Następnie metodą PUT na zasobie /sale/offers/{offerId} prześlij ofertę z wprowadzonymi zmianami. Zmiany możesz wprowadzać w każdej ofercie - tej trwającej i tej zakończonej. Jeśli prześlesz niekompletne dane, to w polu validation wyświetlimy:

- co powinieneś uzupełnić,
- błędy, jakie pojawiły się w twojej ofercie

**Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty...**"
Także numer oferty również należy przesłać przy jej edycji.

**Comment by Onixarts** [comment]
Również się na to dzisiaj natknąłem, nie jest to jasno opisane, może warto o tym wspomnieć w dokumentacji.

**Comment by AssAssIn1909** [comment]
Założeniem REST api jest trzymanie się ogólnie przyjętych reguł. 1 z nich jest że metody PUT służą do pełnej aktualizacji zasobu. Pełnej czyli wysyłamy cały obiekt. Więc wszystko jest wymagane, jak tego nie ma to jest "usuwane" ( powinno byc nadpisane przez nic, pusty ciąg znaków itd). Z tym że jednak niektóre pola muszą być wymagane tak na prawdę. Ciężko coś zaktualizować gdy wyśle się obiekt bez identyfikatora.

Jednak warto jednak w dokumentacji mieć zaznaczone ze niektóre pola są "wymagane tak bardziej".

**Comment by PawelTaberski** [comment]
@Onixarts Cytat:
Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty..."
Pochodzi właśnie z poradnika :-)
Czy przez dokumentacje masz na myśli?:
https://developer.allegro.pl/documentation/

**Comment by AssAssIn1909** [comment]
@PawelTaberski 
Obstawiam że warto by było, tak dla świętego spokoju. Tym bardziej że z tego co teraz patrze, to "name" jest oznaczony jako wymagany. Więc dlaczego by nie oznaczyć tak samo "id".

**Comment by Onixarts** [comment]
Mam otwarty zarówno poradnik jak i dokumentację i wertuję to w kółko. Wiem, że trzeba przesłać całość ale najwyraźniej z tym idem oferty nie trafiło to do mnie, tym bardziej że pochodzę ze świata Soapowego :).

Jak się już o tym wie to spoko.

**Comment by PawelTaberski** [comment]
Oki dodamy taką informację przy najbliższym wdrożeniu 👍
