### ISSUE TITLE
Dyskusje allegro - nie działają

### ISSUE THREAD

**Issue by MBorasinski** [allegro/allegro-api#1697]
Dzień dobry,

Po zalogowaniu na konto allegro.pl.allegrosandbox.pl wchodzę w zakładkę 'moje konto', następnie klikam 'Dyskusje z kupującymi' i po załadowaniu strony otrzymuję komunikat 'Coś poszło nie tak
Nie mogliśmy wyświetlić tej strony'. Czy jest jakaś informacja o takim błędzie i ewentualnymi krokami podjętymi które mogą naprawić ten błąd? 

Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Widzę, że rzeczywiście jest jakiś problem z tą zakładką. Sprawę zgłosiłem do odpowiedniego zespołu. Prośba o cierpliwość.

**Comment by MBorasinski** [comment]
Dziękuję za reakcję. Proszę o informacje kiedy ewentualnie ten problem może zostać rozwiązany. 

Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Oczywiście, jak tylko otrzymam jakieś informacje dam znać.
