### ISSUE TITLE
Parametryzacja, produkty testowe w sandboksie

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#1698]
Witam,

Chciałbym zapytać czy na środowisku testowym znajdują się jakieś przykładowe produkty, które można podpinać pod wystawiane oferty w związku z parametryzacją? Znalazłem taki wykaz produktów pod adresem https://developer.allegro.pl/productization/#sandbox, problem polega jednak na tym, że REST API odnajduje tylko produkt z EAN 9780000000002. W dodatku jest to książka, a nie smartfon.

Fajnie byłoby dodać jeszcze kilka produktów, tak aby można było przetestować nadpisywanie różnych typów parametrów ich produktowymi wartościami podczas wystawiania oferty.

**Comment by TomekKaczmarek** [comment]
@AlpanetPL faktycznie, coś nie działa. Zgłosiłem do odpowiedniego zespołu.

**Comment by AlpanetPL** [comment]
Widzę, że testowe produkty zostały już naprawione - dziękuje. Dwie sprawy, z tym związane:

1. Produkty znajduję przez REST API, natomiast jaki testowy EAN nie wprowadziłbym do formularza wystawiania oferty na Allegro to system nie znajduje produktów.

2. Czy można by dodać jakiś testowy produkt, aby miał on w sobie parametr typu: from-to, a także parametr składający się z kilku pól tekstowych (taki np. jest w ubraniach gdzie określa się skład tkaniny)?

 Z góry dziękuję.

**Comment by TomekKaczmarek** [comment]
@AlpanetPL 

Ad 1/ Problem zgłosiłem.
Ad 2/ Produkty na środowisku testowym mają Tobie pomóc w przetestowaniu procesu wystawiania. Mają dane spójne z tym czego wymagamy w ofercie, dzięki temu możesz wystawić ofertę powiązaną z tym produktem.

Jeśli chcesz przetestować opcje wyszukiwania i filtrowania bazy produktów - polecam to robić na bazie produkcyjnej, które jest aktualna i powinna zawierać więcej parametrów. Nie wszystkie parametry są już używane i dostępne. from-to sprawdzisz w książkach na roku wydania.

**Comment by AlpanetPL** [comment]
Rozumiem. Dzięki za pomoc.
