### ISSUE TITLE
Brak logów dla aukcji w JournalDeals

### ISSUE THREAD

**Issue by Michaell65** [allegro/allegro-api#17]
Z wykorzystaniem "doGetSiteJournalDeals" pobieram dziennik ostatnich akcji na moim koncie.

Przy każdym następnym pobraniu dziennika, ustawiam jako startowy "journalStart" ostatni pobrany wcześniej log.

Czasami zdarza się jednak, że przy pobraniu dziennika nie ma pojedynczej akcji informującej o utworzeniu "Aktu Zakupowego". Dane są wybiórcze. 

Ostatnio tak było dla aukcji nr 7187182934.

Przy pobraniu dziennika, nie został zarejestrowany log informujący o utworzeniu aktu zakupowego.
Dlatego też został edytowany "journalStart" w mojej bazie (na ostatni z ostatnio pobranych).

Jednak prze kolejnych kilka dni (pobieranie dziennika) nadal nie zarejestrowano logu dla tej aukcji.

Dopiero trzeba było cofnąć się w logach ręcznie (ustawić starszy "journalStart") i wtedy się już pobrało.

Wygląda to tak jakby logi w dzienniku aktualizowały się z opóźnieniem.

O co chodzi?

**Comment by PawelTaberski** [comment]
Sprawdziliśmy i na podstawie numeru oferty, którą podesłałeś wszystko wygląda prawidłowo. Jest zachowana kolejność id-ków. Z tego co napisałeś wygląda to na błąd, jeśli taka sytuacja się powtórzy, podeślij nam: 
- request i respons w którym brak danego aktu zakupowego
- request i respons w którym już się pojawił.
Na podstawie tych danych będziemy w stanie sprawdzić, czy występują jakieś problemy. Na tą chwilę wszystko wygląda prawidłowo.
