### ISSUE TITLE
doGetRefundsList

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#170]
Korzystając z Allegro WebApi i WSDLa https://webapi.allegro.pl/service.php?wsdl usiłuję w C# pobrać listę wniosków o zwrot prowizji. Odpalam doGetRefundsList, serwer odpowiada, tyle że w sytuacji, gdy na liście są wnioski nierozpatrzone (W TRAKCIE) z refundStatus "5" i brakiem considerDate, WSDL wywala problem zwiazany z serializacją Daty (tej brakującej). W efekcie mogę pobierać wyłącznie rozpatrzone wnioski, ale że filtrowanie po statusie wniosków jest niemożliwe, w zasadzie nie mogę pobrać niczego. Siedzę i kwiczę...

**Comment by MaciejPotepa** [comment]
Żebym mógł przeanalizować problem, który napotkałeś - podeślij proszę request i response zapisane w pliku XML.

**Comment by lukada4100** [comment]
Wysyłam request i response w pliku txt. To chyba nie będzie duży problem. Dodatkowo wstawiłem jeszcze BaseException który mi wyrzuca metoda doGetRefundList.
[RefundList.txt](https://github.com/allegro/allegro-api/files/1955490/RefundList.txt)

**Comment by MaciejPotepa** [comment]
@lukada4100, nigdzie nie ma plików, o których piszesz.

**Comment by lukada4100** [comment]
Wisiały przez jakiś czas, ale zdjąłem ze względu na ochronę danych. Można na priv?

**Comment by lukada4100** [comment]
[RefundList.txt](https://github.com/allegro/allegro-api/files/1973052/RefundList.txt)

**Comment by MaciejPotepa** [comment]
Dzięki za podesłanie pliku. Pracujemy nad rozwiązaniem problemu.

**Comment by lukada4100** [comment]
Odpowiedź serwera jest oczywiście prawidłowa. Pole o którym mówisz jest pustę. Tyle że nie obsłużę tego bez modyfikowania kodu wygenerowanego na podstawie dokumentu WSDL, który powinien działać poprawnie: metoda nie radzi sobie z parsowaniem odpowiedzi serwera po prostu.
