### ISSUE TITLE
Problem z aktywacją konta firma na sandboxie

### ISSUE THREAD

**Issue by fredzi** [allegro/allegro-api#1700]
Dzień dobry,
mam prośbę o aktywację konta na sandboxie.
W panelu widoczna jest cały czas informacja "Nieaktywne - trwa weryfikacja Twoich danych.".
Login: trustnet

**Comment by PawelTaberski** [comment]
Wstępnie aktywowałem Twoje konto podeślij teraz przez zakładkę moje konto jakieś dowolne dwa pliki, aby zakończyć ten proces.

**Comment by AptusShop** [comment]
Poproszę to samo dla aptusshop.

**Comment by PawelTaberski** [comment]
@AptusShop Gotowe :-) wstępnie aktywowałem Twoje konto podeślij teraz przez zakładkę moje konto jakieś dowolne dwa pliki, aby zakończyć ten proces.

**Comment by AptusShop** [comment]
Zrobione, chyba działa(?) - przynajmniej da się wystawiać. Zobaczymy co z API. Dziękuję i pozdrawiam.
Piotr Ryś

**Comment by aqualatus** [comment]
Dzień dobry,

Proszę o aktywację konta: megusta

Rozumiem, że nie muszę w sandboxie robić weryfikacji, wysyłając przelew?

**Comment by alikoli** [comment]
Ja również poproszę, konto allegrotest

**Comment by PawelTaberski** [comment]
@alikoli Aktywowałem wstępnie Twoje konto, aby zakończyć proces podeślij teraz przez zakładkę moje konto jakieś dowolne dwa pliki.

**Comment by myszaq99** [comment]
Również poproszę o aktywację konta alucenter

**Comment by PawelTaberski** [comment]
@myszaq99 Wstępnie aktywowałem Twoje konto, aby zakończyć proces podeślij przez zakładkę moje konto jakieś dowolne dwa pliki.

**Comment by Liberko** [comment]
Dzień dobry, mam problem z kontem JanJan, (Nieaktywne - trwa weryfikacja Twoich danych).

**Comment by PawelTaberski** [comment]
@Liberko Aktywowałem Twoje konto.

**Comment by Rebellious83** [comment]
Prosze o Aktywacje konta 
Login : Rebellious83

**Comment by PrzemyslawLukanowski** [comment]
@Rebellious83  Aktywowałem Twoje konto.

**Comment by Rebellious83** [comment]
Prosze o aktywacje konta
Login :  testowaczek

**Comment by PrzemyslawLukanowski** [comment]
@Rebellious83  Aktywowałem konto.
