### ISSUE TITLE
Nieprawidłowe kategorie w produkcie

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#1701]
Witam,

Mam taki produkt `518216b7-81c1-4a87-b688-5737fb2a4d67`. Pobierając najaktualniejsze dane o nim, dowiaduje się, że jest przypisany do kategorii: `79433`. Mam aukcję, która kiedyś szła i chciałbym ją wznowić: `8038570865`. Pobieram dane aukcji przez `GET /sale/offer/8038570865`. Poprawiam stosowne dane (akurat teraz nic nie mam do poprawienia). Następnie aktualizuje ofertę `PUT /sale/offer/8038570865`. I dostaję:

VALIDATION_ERROR / ERR_CATEGORY_NOT_FOUND.

Dlaczego? Z tego co ustaliłem, kategoria nie jest kategorią najniższego rzędu, lecz taka jest w produkcie.

**Comment by PawelTaberski** [comment]
Sprawdziłem i na produkcji kategoria: 79433, jest kategorią najniższego rzędu. Jesteś pewny, że nie pobierasz czasem produktu z produkcji i nie próbujesz go wystawić tymi danymi na sandboxie?
Między produkcją a sandboxem mogą występować różnice w kategoriach jak i parametrach.
