### ISSUE TITLE
Cenniki dostaw

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1702]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie można skasować Cennika dostaw przez rest api , można tylko utworzyć i edytować. 

Sugestia - kasowanie cenników dostaw powinno być możliwe tylko gdy nie jest on użyty w jakiejś ofercie.

**Comment by PawelTaberski** [comment]
Obecnie na jednym koncie możesz utworzyć do 250 różnych cenników.
I tak jak napisałeś obecnie nie ma możliwości usunięcia cennika, a jedynie jego edycja. Chwilowo nie planujemy wprowadzenia funkcji usunięcia cennika, bo tak jak napisałeś mogłoby to wpłynąć na oferty które z niego korzystają zarówno te aktywne jak i drafty, a także oferty zakończone.
