### ISSUE TITLE
sandbox GET sale/shipping-rates?seller.id={some_user}

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#1703]
1) utworzyłem konto {some_user} na allegro.pl.allegrosandbox.pl
2) przeszedłem na stronę apps.developer.allegro.pl.allegrosandbox.pl i uzyskałem dane potrzebne do wygenerowania tokena
3) wygenerowałem poprawny token, gdyż dla "ogólnych" GET-ów działa poprawnie

W przypadku żądania GET https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id={some_user}

dostaję błąd:

{
    "errors": [
        {
            "code": "ERROR",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "Access denied. Please retry, or restart application."
        }
    ]
}

czy {some_user} w requeście  https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id={some_user} to ten sam string co login / adres email w momencie logowania do sandboxa? Jeśli nie - jak mam określić identyfikator sprzedawcy (wartość seller.id) ?

**Comment by PawelTaberski** [comment]
Jest to wartość w formie liczby całkowitej, otrzymasz ją m.in. po rozkodowaniu tokena (wszystkie tokeny są w technologii JWT).

**Comment by adamTynski** [comment]
Po rozkodowaniu tokena mam tylko to: {"alg":"RS256","typ":"JWT"}{"scope":["allegro_api"],"exp":1559082005,"jti":"{some_string}","client_id":"{sandbox_client_id}"}
czyli id klienta w sandboxie, który nie jest integerem. Czy jest jakiś inny sposób na określenie seller.id?

**Comment by PawelTaberski** [comment]
@adamTynski  Oznacza to że korzystasz z tokena uzyskanego przy pomocy flow client credentials, który służy do obsługi tylko publicznie dostępnych zasobów jak wyszukiwanie ofert itp. Nie ma on kontekstu usera i nie możesz nim pobrać danych przypisanych do danego użytkownika. Musisz skorzystać z code bądź device flow. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/). Jak będziesz miał token z kontekstem usera wtedy po rozkodowaniu otrzymasz również "user_name" z id usera.

**Comment by adamTynski** [comment]
Jeśli się nie mylę - z opisu z 'waszego poradnika' wynika, że chcąc w pełni korzystać z REST API użytkownik musi się fizycznie zalogować na stronie Allegro. W takim razie jak obsłużyć te odwołania do REST API, które odbywają się bez udziału człowieka? Tzn. inicjowane są przez serwer, np. w cron-ie?

**Comment by adamTynski** [comment]
Jeśli dobrze rozumiem z 'waszego poradnika' wynika, że nawet jeśli zastosuję autoryzację 'device flow' - użytkownik i tak musi zautoryzować działanie aplikacji korzystając z 'verification_uri'. W takim razie co zrobić w sytuacji, w której system odpytuje API w cron-ie, np. co 30 minut? 'device_code' wygasa po 3600 sekundach. Zatem, by cron mógł działać poprawnie - użytkownik co godzinę musi autoryzować działanie aplikacji, tak? Czy jest możliwość zwiększenia wartości 'expires_in' np. do nieskończoności?

**Comment by adamTynski** [comment]
Jeśli dobrze rozumiem z 'waszego poradnika' wynika, że nawet jeśli zastosuję autoryzację 'device flow' - użytkownik i tak musi zautoryzować działanie aplikacji korzystając z 'verification_uri'. Uzyskany w ten sposób token ma ważność 12 godzin, po czym trzeba wygenerować nowy 'device_code' i powtórzyć autoryzację. W takim razie co zrobić w sytuacji, w której system odpytuje API w cron-ie, np. co 3 godziny? Zatem, by cron mógł działać poprawnie - użytkownik co 12 godzin musi autoryzować działanie aplikacji? Czy jest możliwość zwiększenia wartości 'expires_in' np. do nieskończoności?

**Comment by neldh** [comment]
w device flow mozesz odswiezac tokeny
refresh token wazny jest az 3 miesiace. Cały czas odswiezajac, autoryzujesz przez strone tylko raz i moze to oczywiscie zrobić na dowolnym sprzęcie (niekoniecznie na maszynie ktora potrzebuje uwierzytelnienia). Ja to robie tak, że aplikacja sama odswieza tokeny raz na jakis czas i pilnuje dostepu, a jak go jakims cudem straci, to od razu idzie mail, zeby ktos ponownie autoryzowal.

użycie refresha masz w poradniku. poszukaj "https://allegro.pl/auth/oauth/token?grant_type=refresh_token"

**Comment by PawelTaberski** [comment]
@adamTynski Przy device flow musisz wybrać taki typ przy rejestracji aplikacji i nie podaje się redirecta. Usera musisz tylko raz przeprowadzić przez flow później wystarczy, że będziesz korzystał z metody do odświeżenia tokena. Więcej na ten temat [znajdziesz tutaj](https://developer.allegro.pl/auth/#refresh-token).

**Comment by adamTynski** [comment]
ok, wszystko już wiem w tym temacie, dzięki!
