### ISSUE TITLE
Problemy z REST API

### ISSUE THREAD

**Issue by grojanteam** [allegro/allegro-api#1704]
Witam,

chciałbym się dowiedzieć czy z REST API są problemy ? Chciałbym przetestować funkcjonalności, które napisałem, ale nie jestem w stanie z powodu dużej ilości błędów na każdym żądaniu, 

np. wczoraj na /sale/images ten sam produkt wystawiając na allegro przeszedł bez problem dzisiaj sypie błędem http code 422, jestem pewny że nie jest to problem związany z moim zdjęciem, a z waszym API

proszę o ustabilizowanie waszego API, bo jest to uciążliwe... albo chociaż o to aby ktoś wasze zmiany testował porządniej

**Comment by PawelTaberski** [comment]
A w jaki sposób przesyłasz zdjęcia w postaci binarnej czy linku? Jesteś pewny, ze podajesz właściwą wartość w nagłówku content-type? 
Informacje o tym jak poprawnie przesyłać zdjęcia znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-3-images).
Jeśli jesteś pewny, że wszystko robisz poprawnie, a mimo to otrzymujesz błąd podeślij proszę pełnego cURL-a i responsa przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu zaznacz, że dane dotyczą zgłoszenia 1704 na GitHub-ie.

**Comment by grojanteam** [comment]
Tak jestem pewny, przesyłam w postaci linka, dzisiaj już widzę że problemu nie ma.
