### ISSUE TITLE
Problem z zasobem /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by gskowera** [allegro/allegro-api#1705]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę pobrać danych zamówienia da9f4ac1-808c-11e9-b346-636d18da5aa6:

**https://api.allegro.pl/order/checkout-forms/da9f4ac1-808c-11e9-b346-636d18da5aa6**

Otrzymuję:

_{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "path": "/order/checkout-forms/da9f4ac1-808c-11e9-b346-636d18da5aa6"
        }
    ]
}_

Choć inne dane z tym wywołaniem otrzymuję bez problemu.

Proszę o info, czy problem leży po mojej, czy po Waszej stronie. Z góry dziękuję.

**Comment by PawelTaberski** [comment]
Możliwe, że user kupujący zrobił oddzielne zakupy, a następnie zaznaczył je do wspólnej zapłaty. Opisaliśmy taki przypadek w poradniku:
"..Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to oznacza, że mamy do czynienia z połączeniem zakupów przez kupującego)..."
Dlatego nie możesz wyszukać danego id.

**Comment by neldh** [comment]
@PawelTaberski 
W takim wypadku treść blędu powinna wyraźnie wskazywać na to, że checkout form nie istnieje...

**Comment by PawelTaberski** [comment]
Wskazuje na to status HTTP, w takim wypadku otrzymujesz 404.

**Comment by neldh** [comment]
Status statusem, ale chodzilo mi o "message": "An error has occurred". Wystarczyłoby 
"message": "An error has occurred: Checkout form doesn't exist" i nie byłoby tego issue.

**Comment by PawelTaberski** [comment]
@neldh Przekazałem Twoją sugestię odnośnie komunikatu błędu.
