### ISSUE TITLE
czy w rest api są zdarzenia z konczącymi sie aukcjami?

### ISSUE THREAD

**Issue by swift13** [allegro/allegro-api#1706]
W webapi bylo takie zdarzenia a jak jest w rest czy poprostu mam sie cały czas odpytywać tu
/sale/offers?publication.status=ENDED
czy coś nowego sie nie pojwiło

**Comment by PawelTaberski** [comment]
Obecnie nie ma takich zdarzeń, ale pracujemy nad dziennikiem zdarzeń w ofercie, gdzie otrzymasz takie informacje. Jeszcze nie znamy konkretnej daty wdrożenia. Jak będziemy mieli więcej informacji poinformujemy o tym w dedykowanym komunikacie.

**Comment by swift13** [comment]
a jest możliwośc dodania do GET /sale/offers  stortowania chociaż po 
sort=publication.endedAt

**Comment by PawelTaberski** [comment]
Jest oczywiście taka możliwość wystarczy wywołać:
/sale/offers?publication.status=ENDED&sort=-endDate - sortowanie od najnowszych
bądź
/sale/offers?publication.status=ENDED&sort=endDate - sortowanie od najstarszych

**Comment by Cupik83** [comment]
A czy są jeszcze inne metody sortowania bo w dokumentacji jest tylko:

sellingMode.price.amount - sortowanie po cenie rosnąco,
-sellingMode.price.amount - sortowanie po cenie malejąco,
stock.sold - sortowanie po liczbie sprzedanych przedmiotów rosnąco,
-stock.sold - sortowanie po liczbie sprzedanych przedmiotów malejąco,
 stock.available - sortowanie po liczbie dostępnych przedmiotów rosnąco,
 -stock.available - sortowanie po liczbie dostępnych przedmiotów malejąco. 

Więc zastanawiam się gdzie mi umknęło sortowanie endDate?

**Comment by PawelTaberski** [comment]
@Cupik83 Zgadza się w dokumentacji jej brakuje oczywiście uzupełnimy.
