### ISSUE TITLE
Produktyzacja i wybór kategorii

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#1707]
Gdy przydzielam produkt do oferty wraz z danymi znalezionego produktu zwracany jest ID kategorii. Czy oferta (z podpiętym produktem) powinna zostać dodana właśnie do tej kategorii (kategoria ze znalezionego produktu, nadpisuje kategorię, którą wcześniej u siebie w systemie wybrał użytkownik) czy też może być dodana do innej kategorii (czyli priorytet ma kategoria wybrana przez użytkownika)? Jak prawidłowo powinno przebiegać publikowanie takiej oferty? Oczywiście nie chodzi o to, aby np. telewizor przydzielić do kategorii książki ;-), ale czasem kategorie są dość podobne, stąd pytanie.

**Comment by TomekKaczmarek** [comment]
@AlpanetPL założenie jest takie, że bierzesz wszystkie dane, które dostałeś w produkcie i wprowadzasz je w ofercie. Na tym etapie zwracamy kategorie, parametry i EAN - nie zmieniaj ich i na ich podstawie utwórz ofertę.

Jeśli dla jakiegoś produktu mamy błędne dane - daj nam proszę znać poprawimy je.

Aktualnie pracujemy nad procesem, który pozwoli sprzedawcom dodawać i aktualizować dane o produktach - wtedy ten proces będzie można również uwzględnić w API. Więcej informacji na ten temat już wkrótce.
