### ISSUE TITLE
Ustawianie parametrów przez REST API

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#1708]
Gdy Allegro wprowadza obowiązkowe parametry to daje możliwość masowego ich ustawienia z zakładki https://allegro.pl/moje-allegro/sprzedaz/uzupelnij-parametry

Czy przez REST API można ustawiać same parametry? Z dokumentacji wnioskuję, że trzeba pobrać całą ofertę, zmienić parametr i wysłać całą z powrotem. Po co tyle roboty.

**Comment by PawelTaberski** [comment]
Nie ma możliwości grupowej zmiany parametrów po API. Wszystkie zasoby do grupowej edycji opisaliśmy [w naszym poradniku](https://developer.allegro.pl/my_offers/#3).

**Comment by Lebioda** [comment]
To nie musi być grupowa zmiana. Czy pojedynczo można zmienić tylko jeden parametr bez wysyłania całej oferty?

**Comment by PawelTaberski** [comment]
W tym przypadku przy edycji musisz przesyłać wszystkie pola oferty. Nie ma możliwości wysłania tylko elementów, które chcesz zmienić.
