### ISSUE TITLE
Ujednolicenie błędów walidacji

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1709]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Prosiłbym o ujednolicenie błędów zwracanych w strukturze validation przy aktualizacji aukcji.
Przykładowy response:

```json
"validation": {
    "errors": [
      {
        "code": "VALIDATION_ERROR",
        "message": "Payments may not be empty.",
        "details": "",
        "path": "",
        "userMessage": "Podaj dane dotyczące płatności. Dane dotyczące płatności nie mogą być puste."
      },
      {
        "code": "VALIDATION_ERROR",
        "message": "Location may not be empty.",
        "details": "",
        "path": "",
        "userMessage": "Podaj lokalizację. Lokalizacja nie może być pusta."
      },
      {
        "code": "VALIDATION_ERROR",
        "message": "Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny.",
        "details": "",
        "path": "",
        "userMessage": "Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny."
      },
      {
        "code": "VALIDATION_ERROR",
        "message": "Uzupełnij brakujące parametry obowiązkowe: Stan, Bohater, Kolor, Marka, Płeć, Typ.",
        "details": "",
        "path": "",
        "userMessage": "Uzupełnij brakujące parametry obowiązkowe: Stan, Bohater, Kolor, Marka, Płeć, Typ."
      }
    ],
```

Widać, że pisały to dwie różne osoby, inna forma zdań. Do tego, jeśli chciałbym błędy wypisać użytkownikowi i prócz userMessage użyć jeszcze message, to w drugim przypadku dostanę dwa razy tego samego stringa - będzie to wyglądać niechlujnie, jak błąd w aplikacji. 
Również jeśli chcę otrzymywać opisy w PL-pl to powinno być w języku polskim.
Nie wiem jakie założenia były co do message, ale zdecydujmy się na jedno rozwiązanie :)

**Comment by PawelTaberski** [comment]
Pracujemy nad ujednoliceniem komunikatów błędów, dzięki za podesłanie konkretnych przykładów.
