### ISSUE TITLE
Jest jakis problem z WebAPI? ERR_NO_SESSION 

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#1710]
Występuje problem: 
 - [x ] ze środowiskiem produkcyjnym
 - [x ] z logowaniem lub autoryzacją

Od 20 maja obserwuje zwiekszone wystepowanie wyjatku ERR_NO_SESSION w godzinach 9-17. Natomiast od 26go od godzin wieczornych (22:00+) problem jeszcze bardziej zwiekszyl swoja skale (od 3x do 20x czesciej wystepuje). Zmniejszylem nawet czas zycia sesji po swojej stronie do 35min (z 55min), ale nie pomoglo. 

Ciezko dac mi konkrety, bo problem jest globalny i widze go po prostu przy pomocy moich "sieci o grubych oczkach" :)

**Comment by PawelTaberski** [comment]
Zgodnie z [naszą stroną](https://allegro.pl/webapi/faq.php#faq_5):

Błąd ERR_NO_SESSION może być wynikiem jednego z zabezpieczeń, które stosowane jest w WebAPI. Podczas wywoływania metody wykorzystującej identyfikator sesji, sprawdzane jest czy IP z którego wywoływana jest metoda jest tym samym IP z poziomu którego sesja była uprzednio utworzona. Należy upewnić się, że obie metody wywoływane są z poziomu tego samego IP.

Sprawdź proszę, czy to nie jest powód Twojego problemu.

**Comment by barthoos** [comment]
:) Moja aplikacja chodzi przeszlo 10 lat. Mam odseparowane ID sesji po IPkach.. Przed 20 maja byla plaza w temacie przez dobrych kilka-kilkanascie miesiecy.

**Comment by PawelTaberski** [comment]
Rozumiem podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) klucz z jakiego korzystasz i IP jeśli dasz radę to również konkretne timestampy i metody na jakich wyskakuje ci za pierwszym razem taki błąd. Sprawdzimy to. W zgłoszeniu dodaj, że dane są potrzebne do ticketa numer 1710 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Otrzymałem dane i przekazałem je do dokładnej weryfikacji. Prośba o cierpliwość.
