### ISSUE TITLE
metoda offers/listing z parametrami sellingMode.format=BUY_NOW&price.to=100

### ISSUE THREAD

**Issue by zulugula08** [allegro/allegro-api#1711]
Witam,
Przepytuje resta metodą /offers/listing/ z parametrami sellingMode.format=BUY_NOW&price.to=100 i otrzymuję ceny kup teraz w wysokości grubo ponad 100 zł. Co robię źle?

Rest zwrócił mi np.:
`
[sellingMode] => stdClass Object
                (
                    [format] => BUY_NOW
                    [price] => stdClass Object
                        (
                            [amount] => 1.00
                            [currency] => PLN
                        )

                    [fixedPrice] => stdClass Object
                        (
                            [amount] => 2099.00
                            [currency] => PLN
                        )

                    [bidCount] => 0
                )`

Ja chciałbym żeby cena kup teraz nie przekraczała 100zł nie koniecznie interesują mnie licytację i  że ktoś wstawił licytację od 1zł. Przecież po to dodaje parametr BUY_NOW .

**Comment by PawelTaberski** [comment]
Sprawdziłem i wydaje się, że metoda działa poprawnie. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne zapytanie wraz z responsem i informacją, które dane są Twoim zdaniem niepoprawne. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1711 na GitHub-ie

**Comment by zulugula08** [comment]
Informacje wysłałem poprzez formularz, ale myślę że warto jeszcze w skrócie sprawę nakreślić tutaj. Sytuacja z przez paru minut, pełne zapytanie

`https://api.allegro.pl/category.id=491&parameter.11323=1&parameter.11323=2&parameter.11323=238066&parameter.11323=238058&parameter.11323=246534&parameter.11323=246538&sellingMode.format=BUY_NOW&price.to=500&parameter.4474=211457&parameter.4474=211461&parameter.4474=211465&parameter.4474=211469&parameter.4474=211473&parameter.4474=211477&parameter.4474=211481&parameter.4474=211485&parameter.4474=211489&parameter.4474=211493&parameter.4474=211497&parameter.4366=280181&parameter.4366=10&parameter.4366=20&parameter.200941=2177&parameter.200941=2181&parameter.200941=2185&parameter.200941=2189&parameter.200941=2193&parameter.200941=2197&parameter.200941=2201&parameter.200941=2205&parameter.200941=2209&parameter.82.from=100`

fragment odpowiedzi:

`                    [10] => stdClass Object
                        (
                            [id] => 8197331296
                            [name] => Laptop lenovo ideapad 330 i5-8300 2.3 inny wydatek
                            [seller] => stdClass Object
                                (
                                    [id] => 10397374
                                    [company] => 
                                    [superSeller] => 
                                )

                            [promotion] => stdClass Object
                                (
                                    [emphasized] => 
                                    [bold] => 
                                    [highlight] => 
                                )

                            [delivery] => stdClass Object
                                (
                                    [availableForFree] => 1
                                    [lowestPrice] => stdClass Object
                                        (
                                            [amount] => 0.00
                                            [currency] => PLN
                                        )

                                )

                            [images] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [url] => https://a.allegroimg.com/original/038abd/5b5dd5d24263ac3027c0dcb9160e
                                        )

                                    [1] => stdClass Object
                                        (
                                            [url] => https://a.allegroimg.com/original/03100b/66fe0736478ba71f11b850ba23c9
                                        )

                                    [2] => stdClass Object
                                        (
                                            [url] => https://a.allegroimg.com/original/0318fe/24f082dc4619b911bcc42b747aa7
                                        )

                                    [3] => stdClass Object
                                        (
                                            [url] => https://a.allegroimg.com/original/0327e2/5ac703a342b3ba737de6260a971b
                                        )

                                    [4] => stdClass Object
                                        (
                                            [url] => https://a.allegroimg.com/original/030e11/8e4302c64ba49355e8b6a8172869
                                        )

                                )

                            [sellingMode] => stdClass Object
                                (
                                    [format] => BUY_NOW
                                    [price] => stdClass Object
                                        (
                                            [amount] => 202.52
                                            [currency] => PLN
                                        )

                                    [fixedPrice] => stdClass Object
                                        (
                                            [amount] => 2600.00
                                            [currency] => PLN
                                        )

                                    [bidCount] => 5
                                )

                            [stock] => stdClass Object
                                (
                                    [unit] => UNIT
                                    [available] => 1
                                )

                            [category] => stdClass Object
                                (
                                    [id] => 77920
                                )

                            [publication] => stdClass Object
                                (
                                    [endingAt] => 2019-06-22T07:30:50.000Z
                                )

                        )`

wartość oferty 2600PLN tak więc niezgodna z parametrem

**Comment by MartaNowaczyk** [comment]
Sortuje po cenie osiągniętej w licytacji czyli jest to 202.52, bo masz w zapytaniu price.to=500. 2600 to cena Kup teraz dla licytacji czyli fixedPrice.

**Comment by zulugula08** [comment]
OK, rozumiem. Ja chciałbym osiągnąć taki efekt żeby kombinacja tych dwóch parametrów sellingMode.format=BUY_NOW&price.to=100 pokazała mi wynik cen kup teraz do 100PLN, czy jest to w ogóle możliwe? Jeżeli nie tym sposobem to jakimkolwiek. Gdybym chciał listę filtrować ręcznie nie w rest api, ale serwisie to ten wynik nie pokazałby się.
Po drugie to że jest możliwość wyboru parametr sellingMode.format = BUY_NOW, a ceny filtrują się po sellingMode.format = AUCTION jest trochę nielogiczne.

**Comment by MartaNowaczyk** [comment]
jeżeli jakieś oferty spełniają te krytareia to jest to możliwe. Licytacja pojawiła się dlatego, bo jest  opcją Kubp Teraz. Niefortunnie jednak bierze pod uwagę aktualną cenę w licytacji, zamiast jak by się wydawało KT, stąd te nieścisłości. Na ten moment tak to działa. Zgłosiłam już to do odpowiedniego zespołu i sprawa będzie przeanalizowana.

dla parametrów category.id=491&sellingMode.format=BUY_NOW&price.to=100 też nie pojawi się ten wynik. W poprzednim był bo miałeś price.to=500

Chyba, że to już inny przypadek...

**Comment by zulugula08** [comment]
To był już inny przypadek, ale dzięki za dodanie do sugestii tym czasem będę wyrzucał w swoim kodzie te wyniki 

Wysłane z iPhone'a
