### ISSUE TITLE
Tworzenie draftu - brak informacji o wysyłce, automatycznym wznowieniu oraz typ aukcji "Licytacja + Kup teraz"

### ISSUE THREAD

**Issue by hoobert89** [allegro/allegro-api#1712]
Witam, posiadam taki payload

`{"name":"123456 NR1 M\u00d3J TESTOWY PRODUKT__","afterSalesServices":{"impliedWarranty":{"id":"1c0b3b5a-a744-4372-8125-123edd5385af"},"warranty":{"id":"434435b7-2c30-4ad1-9e59-9bdb0dbe4206"},"returnPolicy":{"id":"12c1456d-a2c4-4df4-a71a-f56c716d657d"}},"payments":{"invoice":"VAT"},"delivery":{"handlingTime":"PT0S","additionalInfo":"aaa","shippingRates":{"id":"3b762b75-e2b9-4e54-894c-52c7e8b176b8"}},"category":{"id":"124264"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>M\u00d3J TESTOWY PRODUKT<\/h1>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/111591\/c25a33854593b1a829799dac9acc"},{"type":"TEXT","content":"<h2>Opis Produktu<\/h2><ul><li><b>Marka<\/b> Inna marka<\/li><li><b>Kolor<\/b> W\u0119giel drzewny<\/li><li><b>Sk\u0142ad<\/b> G\u0142\u00f3wny: 100% Akryl<\/li><li><b>Metka papierowa<\/b> Tak<\/li><li><b>Cena katalogowa<\/b> 159z\u0142<\/li><li><b>Modelka nosi rozmiar<\/b>  UK 8\/ EU 36\/ US 4<\/li><li><b>Wzrost modelki<\/b>   173 cm\/5'8\u201d<\/li><\/ul>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f5b0\/fa46ba8a43df8a99ca2e567b595a"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/114780\/12a0a3e14484883fda9ff8ecbbb0"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1133b6\/61880af1438d9de734adf384d707"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/115b6f\/30623ffb495081fac52da81886ae"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11da77\/1cc4e4004c89bfc586c4af1f88b4"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11c2f2\/534bc222424986597e3286444f78"},{"url":"https:\/\/a.allegroimg.com\/original\/111591\/c25a33854593b1a829799dac9acc"},{"url":"https:\/\/a.allegroimg.com\/original\/11f5b0\/fa46ba8a43df8a99ca2e567b595a"},{"url":"https:\/\/a.allegroimg.com\/original\/114780\/12a0a3e14484883fda9ff8ecbbb0"},{"url":"https:\/\/a.allegroimg.com\/original\/1133b6\/61880af1438d9de734adf384d707"},{"url":"https:\/\/a.allegroimg.com\/original\/115b6f\/30623ffb495081fac52da81886ae"},{"url":"https:\/\/a.allegroimg.com\/original\/11da77\/1cc4e4004c89bfc586c4af1f88b4"}],"sellingMode":{"format":"BUY_NOW","startingPrice":{"amount":1000,"currency":"PLN"},"price":{"amount":2000,"currency":"PLN"}},"stock":{"available":1},"publication":{"duration":"P7D"},"location":{"city":"aaa"}}`

i w związku z tym mam kilka pytań:

1. Dlaczego klucz `delivery` jest pomijany? Po utworzeniu draftu nie mam zaznaczonego cennika dostaw, czasu wysyłki i dodatkowych informacji.
2. W jaki sposób utworzyć aukcje typu "Licytacja + Kup teraz"?
3. W jaki sposób przekazać przez REST API informację o automatycznym wznowieniu aukcji po jej zakończeniu?

**Comment by PawelTaberski** [comment]
Odnośnie Twoich pytań:
1/ Nie bardzo rozumiem, widzę, że w przykładzie masz już id cennika dostawy
2/ W takim wypadku powinieneś przesłać przykładowo:
```
    "sellingMode": {
        "format": "AUCTION",
        "price": {
            "amount": "11",
            "currency": "PLN"
        },
        "startingPrice": {
            "amount": "2",
            "currency": "PLN"
        },
        "minimalPrice": null
    },
```
3/ Nie ma możliwości automatycznego wznowienia oferty, możesz ją ponownie aktywować jak się zakończy.

**Comment by hoobert89** [comment]
Paweł, dzięki za odpowiedź.

Co do pytania pierwszego - chodzi o to, że mam zdefiniowany cennik dostaw na Allegro. Mam wygenerowany identyfikator, który wysyłam i jest to w takiej właśnie formie:

```
[delivery] => Array
(
    [handlingTime] => PT0S
    [additionalInfo] => aaa
    [shippingRates] => Array
        (
            [id] => 3b762b75-e2b9-4e54-894c-52c7e8b176b8
        )
)
```
i potem jak wchodzę na Allegro i widzę ten draft, to wszystko jest uzupełnione poza właśnie opcjami dostawy. Nie mam uzupełnionego cennika dostawy, czasu wysyłki i informacji dodatkowych. A zaznaczę, że <select> z cennikami zawiera taką opcję `3b762b75-e2b9-4e54-894c-52c7e8b176b8`

**Comment by MartaNowaczyk** [comment]
@hoobert89 uzupełnij poprawnie strukturę location w swoim requeście:

```
 "location": {
        "countryCode": "PL",
        "province": "LODZKIE",
        "city": "Łódź",
        "postCode": "93-129"
    }

**Comment by hoobert89** [comment]
Dzięki Marta, działa :)
