### ISSUE TITLE
Domyślny status przy wyszukiwaniu ofert użytkownika

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#1713]
W dokumentacji dla wyszukiwania ofert użytkownika podane jest, że domyślnie status ustawiony jest na _INACTIVE,ACTIVE,ACTIVATING,ENDED_ co nie jest prawdą, ponieważ wtedy nie wyszukuje ofert nieaktywnych (_INACTIVE_).

Dopiero ustawienie statusu na wartość _INACTIVE,ACTIVE,ACTIVATING,ENDED_ wyszukuje wszystkie oferty.

Dokumentacja, której dotyczy:
https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście brak szkiców/draftów sprawę zgłosiłem do odpowiedniego zespołu.
