### ISSUE TITLE
REST API i pobieranie ilości zakupionych sztuk przedmiotu 

### ISSUE THREAD

**Issue by FelixEL** [allegro/allegro-api#1714]
Witam

W WebAPI istniała możliwość sprawdzenia ilość zakupionych sztuk danego przedmiotu po ID. 

Jak w REST API można uzyskać informację o ilości zakupionych **sztuk** przedmiotu wyszukując po ID? 

Nie chodzi mi o parametr "popularity", ponieważ dotyczy on tylko zakupów od unikatowych użytkowników a nie ilości kupionych sztuk. Parametr "stock" też nie jest dobrym parametrem ponieważ może być aktualizowany przez sprzedawcę. 

  

Parametr ten jest publiczny w aukcji stąd moje duże zdziwienie że nie ma go w REST API.

**Comment by PawelTaberski** [comment]
Informacje o liczbie sprzedanych przedmiotów otrzymasz w zasobie GET /sale/offers
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by FelixEL** [comment]
Ok, ale GET /sale/offers dotyczy tylko aukcji wystawionych z własnego konta. Mi chodzi o uzyskanie informacji o dowolnej aukcji mając jej ID (np. mam konto A a sprawdzam ilość sprzedanych przedmiotów kont A,B,C,D itp. ). W WEB-API była taka opcja. 
Te pola są publicznie dostępne przez stronę internetową więc nie widzę powodu dla czego nie ma tej informacji w REST API

**Comment by PawelTaberski** [comment]
Jeśli chodzi o publiczne oferty to pozostaje tylko zasób listing. Obecnie nie ma innego który pozwala pobrać informacje o nie swojej ofercie.
