### ISSUE TITLE
Wznawianie ofert zakańczanych poprzez restApi

### ISSUE THREAD

**Issue by sq9atk** [allegro/allegro-api#1715]
Temat dotyczy oferty 6206372006 na sandboxie i  7918107335 na prodzie.

[sandbox]
Próba ustawienia na aukcji aktualnego stanu towaru w magazynie. W magazynie jest 0 więc chcę taką samą ilość ustawić na aukcji:

2019-05-29 11:32:53 CURL https://api.allegro.pl.allegrosandbox.pl/sale/offer-quantity-change-commands/94ce714b-67f5-4339-acc8-76771be813b6
2019-05-29 11:32:53 CURL {"modification":{"changeType":"FIXED","value":0},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6206372006"}]}]}

Odpowiedź:
{"errors":[{"code":"INCORRECT_QUANTITY_VALUE","message":"Incorrect value of quantity","details":null,"path":"modification.value","userMessage":"Niepoprawana liczba sztuk"}]}

Wobec tego chce zakończyc aukcję:
2019-05-29 11:32:53 CURL https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/02011156-c43e-42b5-b76b-8b0b3759d6cb
2019-05-29 11:32:53 CURL {"publication":{"action":"END"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"6206372006"}]}]}

Odpowiedź
2019-05-29 11:32:53 CURL {"id":"02011156-c43e-42b5-b76b-8b0b3759d6cb","taskCount":{"total":0,"success":0,"failed":0}} czyli niby wszystko OK.

Aukcji tak potraktowanej  nie da się już wznowić ręcznie.
Przy każdej próbie wznowienia wyświetla się taki komunikat.
"Podczas wznowienia oferty wystąpiły błędy. Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie."

Takiemu samemu działaniu została poddana na produkcji aukcja 7918107335 z tym że po podniesieniu ilości sztuk z 0 na 1 aukcja sama się wznowiła.

1. Czy aukcje same się wznawiają po zwiększeniu przez restApi ilości sztuk ze stanu zerowego?
2. Jak powinna być potraktowana aukcja gdy zabraknie towaru bo się sprzedał innym kanałem? Mówimy cały czas o działaniach poprzez restApi.

**Comment by PawelTaberski** [comment]
Każda akcja na ofercie może zająć do godziny czasu, także możliwe, że akurat te oferty były w trakcie kończenia. Jak oferta się zakończy z powodu braku towaru, to powinieneś uzupełnić na ofercie stock, a następnie ją aktywować. Natomiast jak skończy się Tobie stock  to powinieneś zakończyć ofertę jeśli sprzedałeś te towary innym kanałem.

**Comment by krychu90** [comment]
> Jak oferta się zakończy z powodu braku towaru, to powinieneś uzupełnić na ofercie stock, a następnie ją aktywować. 

Jak za pomocą REST API wyłapać takie oferty jeżeli nie ma w nim odpowiednika doGetSiteJournal z WebAPI?

**Comment by PawelTaberski** [comment]
@krychu90 Pracujemy nad wystawieniem dziennika zdarzeń w ofertach. Wtedy podobnie jak w WebAPI będziesz mógł otrzymać informacje, że dana oferta się zakończyła. Obecnie pozostaje odpytanie zasobu sale/offers z zastosowaniem filtra ze statusem oferty.
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by makerlabs** [comment]
@PawelTaberski czy rozważaliście dodać webhooki do Allegro?
Dzięki nim aplikację integrujące się z allegro będą mogły być powiadamiane bezpośrednio z allegro o danym zdarzeniu zamiast odpytywać cyklicznie zasoby, aby pobrać te zdarzenia.

**Comment by PawelTaberski** [comment]
Braliśmy pod uwagę wiele rozwiązań, jednakże oczywiście sugestię przekażę.
