### ISSUE TITLE
Nowe Api Rest a Inpost

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#1716]
1. Korzystając z nowego API REST ściągnięcie ID_Transakcji jest możliwe tylko w nowej dłuuuugiej wersji (cyfry, litery - kilkanaście znaków). Niestety to ID nie umożliwia nam automatycznego adresowania przez API paczkomatów allegro. Czy jest jakaś opcja aby przez nowe API REST pobrać ID transakcji w starej wersji?

2. Korzystając ze starego API (które jest wyłączane jak mniemam od początku czerwca) uzyskujemy ID_Transakcji w starej formie czyli samych cyferek i taka forma pozwala nam adresować Paczkomaty Allegro przez API.

¶

Może jednak przesuniecie termin wyłączenia starego API?

**Comment by SebastianOzdoba** [comment]
@areklal  musisz działać dualnie czyli miec i rest i web. Nie ma opcji w rest by mieć ID transakcji takie jak było w webAPI, temat wielokrotnie przerabiany w innych wątkach :)

**Comment by areklal** [comment]
@SebastianOzdoba @PawelTaberski Nie bardzo rozumiem co to znaczy w tym przypadku dualnie. Aby zaadresować przez Api paczkomat allegro potrzebuję stary numer id transakcji którego od 3 czerwoca nie będę w stanie pobrać w żaden sposób. Możecie mnie oświecić :)

**Comment by Maczuga** [comment]
doGetSiteJournalDeals / doGetPostBuyFormsDataForSellers nie są wygaszane 3 czerwca, dealTransactionId pobierasz tą drugą. Niestety jak większość korzystających z InPost nie możesz się przenieść całkowicie na nowe API z tego jednego durnego powodu, że Allegro potrafi tylko nas ponaglać, zaś nie swoich partnerów biznesowych.

**Comment by areklal** [comment]
@Maczuga Dzięki - nam oprogramowanie robi zewnętrzna firma i stąd jestem "niedoinformowany". Mamy przygotowane nowe oprogramowanie i zaczęliśmy z neigo korzystać dzień po terminie marcowym dla inpostu i była masakra organizacyjna. Dlatego wróciliśmy do starego...

**Comment by kuli-g** [comment]
@areklal ja mam system pod REST przygotowany od października mniej więcej tylko czekam na te identyfikatory transakcji i czekam i czekam... niedługo zaczną wygaszać obsługę zamówień webapi a do inpostu dalej nie będzie można wysyłać danych

**Comment by jaceklodz** [comment]
Jakieś nowe wieści w tym temacie? Kiedy nowy rest całkowicie obsłuży komunikację z Inpost?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować pytanie? [Jakiś czas temu informowaliśmy](https://github.com/allegro/allegro-api/issues/2121), że aby nadać przesyłkę nie trzeba już przekazywać transactionId, wystarczy podać poprawny adres email.

**Comment by kuli-g** [comment]
@PrzemyslawLukanowski on nie pytał o smart tylko o to kiedy inpost będzie przyjmował UUID zamiast transactionId, poza tym nigdzie w dokumentacji inpostu nie widzę że podawanie transactionId przestało być obowiązkowe przy przesyłkach allegro inpost...

**Comment by PrzemyslawLukanowski** [comment]
Nie znamy dokładnej daty przejścia Inpost na REST API. W obecnej sytuacji sugerujemy korzystanie z [mapowania](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping) płatności.

**Comment by kuli-g** [comment]
@PrzemyslawLukanowski czy jeśli inpost nie zrobi pełnej integracji REST do stycznia co jest raczej pewne to po wyłączeniu webapi mapowanie na transactionId zostanie zachowane?

**Comment by PrzemyslawLukanowski** [comment]
@kuli-g Nie planujemy usuwać zasobu do mapowania płatności  [GET /payments/payment-id-mappings](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping).
