### ISSUE TITLE
Sandbox - problemy z logowaniem

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1717]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś występują problemy ze środowiskiem testowym, przy próbie logowania mamy:
 Identyfikator błędu: b6aa84269331575

![image](https://user-images.githubusercontent.com/47886399/58553200-9444bb80-8214-11e9-89b2-0aa8c0638203.png)

**Comment by PawelTaberski** [comment]
Czy problem dalej u Ciebie występuje, bo przetestowałem kilkoma userami i logowanie działa prawidłowo. Sprawdzałeś może na innej przeglądarce i wyczyściłeś ciasteczka?
