### ISSUE TITLE
[Draft] Seryjne tworzenie draftów ofert

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1718]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Seryjne tworzenie draftów ofert jest mega niewydajne
W naszej aplikacji tworzę na raz 10 ofert, czas stworzenia wszystkich 10 to 2 minuty i 5 sekund.

Przykładowe czasy pojedyncze:
Duration: 3569,1761ms (nr 6206375332)
Duration: 3147,183ms (nr 6206375335)
Duration: 4342,198ms  (nr 6206375336)

Wymaga to optymalizacji, jeśli tak samo działa na produkcji to nie jest to akceptowalne. Klient chcąc dodać seryjnie 100 draftów spędzi 20 minut :)

**Comment by PawelTaberski** [comment]
Co rozumiesz przez Tworzenie drafta, czy od razu wysyłasz kompletną ofertę, czy tworzysz pustego i następnie go uzupełniasz?

**Comment by SebastianOzdoba** [comment]
Wrzucamy kompletną ofertę od razu tak że można ją wystawić
url -X PUT \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206375670' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2019-05-29 16:50:10.1826587 Duration: 3281,239ms
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "100979f4-e2d0-40e8-b54b-f62f35397166"
      },
      "ReturnPolicy": {
        "Id": "1bc94464-37e7-42d0-8bf1-94b11e537f2f"
      },
      "Warranty": {
        "Id": "e7e3ce30-171b-4b4e-a85a-de05779efde8"
      }
    },
    "Category": {
      "Id": "258215"
    },
    "CompatibilityList": {
      "Items": null
    },
    "Contact": null,
    "CreatedAt": "2019-05-29T14:51:04Z",
    "Delivery": {
      "AdditionalInfo": "qwerty",
      "HandlingTime": "PT24H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "a2f41b15-8499-4a0c-9e38-e79ce862d7c8"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "TEXT",
              "Content": "<p>qwerty</p>\r\n"
            }
          ]
        }
      ]
    },
    "Ean": null,
    "External": {
      "Id": "13"
    },
    "Id": "6206375670",
    "Images": [],
    "Location": {
      "City": "Kudowa - Zdrój",
      "CountryCode": "PL",
      "PostCode": "28-133",
      "Province": "WARMINSKO_MAZURSKIE"
    },
    "Name": "Chlapacze z filmem AD",
    "Parameters": [
      {
        "Id": "213554",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "213554_261074"
        ]
      },
      {
        "Id": "217177",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "217177_276945"
        ]
      },
      {
        "Id": "217181",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "217181_276969"
        ]
      },
      {
        "Id": "217189",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "217189_276997"
        ]
      },
      {
        "Id": "213102",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "213102_259418"
        ]
      }
    ],
    "Payments": {
      "Invoice": "NO_INVOICE"
    },
    "Product": null,
    "Promotion": null,
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": null,
      "EndingAt": null,
      "StartingAt": null
    },
    "SellingMode": {
      "Format": "BUY_NOW",
      "MinimalPrice": null,
      "Price": {
        "Amount": "62",
        "Currency": "PLN"
      },
      "StartingPrice": null
    },
    "SizeTable": null,
    "Stock": {
      "Available": 5,
      "Unit": "UNIT"
    },
    "UpdatedAt": "2019-05-29T14:51:12.227Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-05-29T14:51:12.227Z"
    }
  },
  "Validation": null,
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Sprawdziłem i rzeczywiście na POST przesłanie kompletnej oferty na środowisku testowym zajmuje około 3000ms natomiast na produkcji czasy te są o wiele krótsze około 500 do 700 ms.
