### ISSUE TITLE
Task wisi od ponad godziny

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#1719]
```
GET /sale/offer-publication-commands/b4238611-b462-5d28-9728-dc793169d304/tasks HTTP/1.1
Host: api.allegro.pl
User-Agent: ...
Accept-Language: pl-PL
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Api-Key: ...
Authorization: bearer ...
```

```
HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: b5d47bb9458d450e
Date: Wed, 29 May 2019 13:10:12 GMT
X-RateLimit-Remaining: 8617
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
```

```
{"tasks":[{"offer":{"id":"7859818215"},"message":null,"status":"NEW","scheduledAt":"2019-05-29T12:05:55.326Z","finishedAt":null,"field":"publication","errors":[]}]}
```

Pomijam fakt, że zwracany message jest w języku angielskim...

**Comment by PawelTaberski** [comment]
@TimothyKoval Widzę, że oferta została niedawno zakończona, czy problem miałeś z jej zakończeniem, czy chciałeś ją teraz aktywować?

**Comment by swift13** [comment]
sprawdz metode wczesniej sale/offers
napewno masz błedy jak robisz update to 'validation':{'errors'}
a jak creat
'errors'
miałem tak samo publisz zwracał ze sie udało a błedy byly z drafcie

**Comment by TimothyKoval** [comment]
@PawelTaberski przekazałem Pana pytanie do odpowiedniego działu. Jak tylko będę miał jakąś odpowiedź poinformuję o tym w osobnym wątku.

**Comment by dostawcaopon** [comment]
U mnie od wczoraj a może nawet i dłuższego czasu, to samo

np
https://api.allegro.pl/sale/offer-publication-commands/d9a82a98-4283-429b-a2bc-379b48885848

task zmienia status publikacji 1000 ofert - zatrzymał sie na liczbie 395 i stoi, pewnie bedzie tak stał dwie godziny albo i dłużej

{\"id\":\"d9a82a98-4283-429b-a2bc-379b48885848\",\"taskCount\":{\"total\":1000,\"success\":395,\"failed\":0}}

**Comment by PawelTaberski** [comment]
@dostawcaopon Sprawdź proszę zasobem sale/offers czy oferty nie są aktywne pomimo iż w tasku masz, że są w trakcie. Jeśli tak to podeślij mi proszę jeśli dasz radę trace-id zadania publikacji i sprawdzenia statusu zadania.

**Comment by PhotoSoft** [comment]
Dodam, że mnie również Klienci zgłaszają problemy z zawieszonymi taskami w przypadku kończenia aukcji.

**Comment by PawelTaberski** [comment]
Wiemy o tym problemie i pracujemy już nad jego rozwiązaniem. Prośba o cierpliwość.

**Comment by FromAnyHole** [comment]
@PawelTaberski - no jak tam sprawy na dobę przed wyłączeniem WebAPI ??
Sami widzicie, że ewidentnie dajecie ciała, a blokowanie mnie nic tu nie pomoże...
