### ISSUE TITLE
Pytanie o parametry w przyszłości w rest api 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1720]
Otrzymując dane o parametrach kategorii i wysyłając dane dla typu dictionary mamy coś takiego:

![image](https://user-images.githubusercontent.com/1530496/58577214-4ea0e680-8246-11e9-81a7-8541519ecfc4.png)

gdzie id to stary paramid a w valuesIds to polaczenie paramid + podkreslnik + idvalue (paramid_idvalue) ze starego webapi 

Na razie póki migrujecie do resta to pewnie ten idvalue leci w gore z tabeli w webapi, moje pytanie brzmi czy zawsze taka struktura bedzie zachowana (czyli paramid_idvalue) czy dla nowych parametrow ( ktore dodawac bedziecie juz tylko w rest api ) nie bedzie sytuacji ze nagle w tym polu nie dostaniemy paramid_idvalue tylko na przyklad 4343bb-342342-222232 lub cokolwiek innego? 

Pomogło nam to w mapowaniu, ale nasuwa się pytanie jak to będzie dalej wyglądać i jakie problemy moze to za sobą pociągnąć.

**Comment by TimothyKoval** [comment]
Nie ufałbym zależności rest id === soap id. Widziałem że były przypadki kiedy wartości były np. przesunięte o jedną pozycję. Sugerowałbym napisać w miarę możliwości jakiś skrypt który porównuje id i ich odpowiadające wartości.

**Comment by PawelTaberski** [comment]
@yncki Nie planujemy obecnie zamieniać sposobu przedstawiania wartości na jakiś inny typ np. jak wspomniałeś na UUID-y.

**Comment by grola** [comment]
No niestety, ale id parametrów z webapi nie odpowiadają parametrom z rest api. Np. kategoria: sport i turystyka -> siłownia i fitness -> odzież -> koszulki, parametr Właściwości. 
1. Webapi: https://wpdesk.me/gr/7071365.png
2. Restapi: https://wpdesk.me/gr/d4f0914.png

Czy zamierzacie ujednolicić te wartości? Czy wystawiając aukcje przez webapi wystawię aukcję z koszulką szybkoschnącą a przez REST api koszulkę oddychającą?

Czy jedynym wyjściem jest ściągnięcie i zapisanie bazy wszystkich parametrów i próba ich konwersji nie poprzez id a wartości? I czy mam gwarancję, że wartości chociaż są identyczne? Bo być może nie ma sensu próbować konwertować w ten sposób?

**Comment by yncki** [comment]
@PawelTaberski możemy prosić o szybką reakcję w tym przypadku ? My założyliśmy że rest api odpowiada webapi , może to Pan potwierdzić lub zanegować ? Lub wskazać w dokumentacji miejsce o tym jak to działa w rest api ??

**Comment by radoslawkoziol** [comment]
@PawelTaberski a czy w każdym wypadku to nowe ID wartości po podkreślniku pokrywa się ze starym ID wartości?
tj, nowe ID są w formacie (jak dobrze rozumiem) paramId_Idwartości, czyli xxx_555
i czy zawsze to "555" będzie się pokrywało ze starym "555"? W większości przypadków to sie pokrywa, ale nie mam pewności czy zawsze. 
Chodzi tutaj o kwestie wstecznej kompatybilności, nie chcielibyśmy, żeby nasi klienci zmieniali 500k produktów ;)

**Comment by dyszczo** [comment]
Wydaje mi się, że ten issue to deal breaker tylko chyba nie wszyscy, którzy implementują przejście na rest api już się zorientowali.

**Comment by PawelTaberski** [comment]
Odnośnie spójności wartości między Web a REST API to występują różnice - id wartości z WebAPI nie zawsze odpowiadają id wartości z REST API. Nie zamierzamy uspójniać tych wartości.

**Comment by PawelTaberski** [comment]
@grola W Twoim przypadku powinieneś patrzeć w WebAPI na sellFormParamValues wtedy wartości między REST a WebAPI będą poprawne.

**Comment by radoslawkoziol** [comment]
@PawelTaberski możesz się odnieść do swoich dwóch ostatnich komentarzy? 

> Odnośnie spójności wartości między Web a REST API to występują różnice - id wartości z WebAPI nie zawsze odpowiadają id wartości z REST API. Nie planujemy uspójniać tych wartości.

> @grola W Twoim przypadku powinieneś patrzeć w WebAPI na sellFormParamValues wtedy wartości między REST a WebAPI będą poprawne.

Nie wydaje Ci się, że tutaj jedno przeczy drugiemu?

**Comment by PawelTaberski** [comment]
@radoslawkoziol  Mogą występować drobne rozbieżności jednakże jeśli chodzi o przypadek jaki podał @grola to wartości w REST API powinny być identyczne z sellFormParamValues (identyfikatorami wartości słownikowej).

**Comment by j4r3kb** [comment]
> No niestety, ale id parametrów z webapi nie odpowiadają parametrom z rest api. Np. kategoria: sport i turystyka -> siłownia i fitness -> odzież -> koszulki, parametr Właściwości.
> 
> 1. Webapi: https://wpdesk.me/gr/7071365.png
> 2. Restapi: https://wpdesk.me/gr/d4f0914.png
> 
> Czy zamierzacie ujednolicić te wartości? Czy wystawiając aukcje przez webapi wystawię aukcję z koszulką szybkoschnącą a przez REST api koszulkę oddychającą?
> 
> Czy jedynym wyjściem jest ściągnięcie i zapisanie bazy wszystkich parametrów i próba ich konwersji nie poprzez id a wartości? I czy mam gwarancję, że wartości chociaż są identyczne? Bo być może nie ma sensu próbować konwertować w ten sposób?

Akurat źle patrzysz na to, liczy się sellFormParamValues, dla szybkoschnące masz tam 16,
w REST API również jest 129278_16, czyli OK w tym przypadku.
