### ISSUE TITLE
The stock level of items to be listed may not be lower than 1 mimo podawania stock.available = 1 

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#1721]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
`{"name": "Wl574esm Pastel Pack Green r.40,5", "category": {"id": 257903}, "parameters": [{"id": 203089, "valuesIds": ["203089_1"], "values": [], "rangeValue": null}, {"id": 203093, "valuesIds": [], "values": ["26"], "rangeValue": null}, {"id": 128188, "valuesIds": ["128188_1"], "values": [], "rangeValue": null}, {"id": 215926, "valuesIds": [], "values": ["wiosna-lato 2018"], "rangeValue": null}, {"id": 451, "valuesIds": ["451_256"], "values": [], "rangeValue": null}, {"id": 7108, "valuesIds": ["7108_57"], "values": [], "rangeValue": null}, {"id": 217481, "valuesIds": [], "values": ["gumowa"], "rangeValue": null}, {"id": 22728, "valuesIds": ["22728_215177"], "values": [], "rangeValue": null}, {"id": 64, "valuesIds": ["64_3"], "values": [], "rangeValue": null}, {"id": 215918, "valuesIds": [], "values": ["WL574ESM PASTEL PACK"], "rangeValue": null}, {"id": 6828, "valuesIds": ["6828_1"], "values": [], "rangeValue": null}, {"id": 15851, "valuesIds": ["15851_1"], "values": [], "rangeValue": null}, {"id": 26388, "valuesIds": ["26388_131072"], "values": [], "rangeValue": null}, {"id": 11323, "valuesIds": ["11323_1"], "values": [], "rangeValue": null}, {"id": 17448, "valuesIds": [], "values": ["0.6"], "rangeValue": null}, {"id": 127848, "valuesIds": ["127848_1"], "values": [], "rangeValue": null}, {"id": 68, "valuesIds": [], "values": ["2.0"], "rangeValue": null}, {"id": 3766, "valuesIds": ["3766_1"], "values": [], "rangeValue": null}, {"id": 203085, "valuesIds": ["203085_4"], "values": [], "rangeValue": null}], "ean": "739655529795", "description": {"sections": [{"items": [{"type": "TEXT", "content": "<h1>Wl574esm Pastel Pack Green</h1><p>Rozmiar buta to <b>40,5</b> a d\\u0142ugo\\u015b\\u0107 wk\\u0142adki to <b>26 cm</b></p><h2>Promocja! Poprzednia cena wynosi\\u0142a 539.66 z\\u0142</h2>"}]}, {"items": [{"type": "TEXT", "content": "<ul><li>Klasyczny model New Balance z serii 574.</li><li>Wzorowane na obuwiu biegowym.</li><li>Wykonane z zamszu najwy\\u017cszej jako\\u015bci.</li><li>Siatka na cholewce zapewnia stopie prawid\\u0142ow\\u0105 wentylacj\\u0119.</li><li>Jeszcze lepsza amortyzacja i stabilno\\u015b\\u0107 dzi\\u0119ki zastosowaniu technologii ENCAP w \\u015brodkowej podeszwie.</li><li>Wzmocnienie pi\\u0119ty.</li></ul>"}, {"type": "IMAGE", "url": "https://a.allegroimg.com/original/11d211/21533d664b83b3cc9fd845390e8a"}]}, {"items": [{"type": "IMAGE", "url": "https://a.allegroimg.com/original/11d0c9/3482ee124423a3e02f402b6f3dc7"}]}, {"items": [{"type": "IMAGE", "url": "https://a.allegroimg.com/original/118404/fc708d174e9197bf7ca9937c1a11"}]}]}, "images": [{"url": "https://a.allegroimg.com/original/11d211/21533d664b83b3cc9fd845390e8a"}, {"url": "https://a.allegroimg.com/original/11d0c9/3482ee124423a3e02f402b6f3dc7"}, {"url": "https://a.allegroimg.com/original/118404/fc708d174e9197bf7ca9937c1a11"}], "sellingMode": {"format": "BUY_NOW", "price": {"amount": "302.20", "currency": "PLN"}}, "stock": {"available": 1, "unit": "UNIT"}, "publication": {"duration": null, "status": "ACTIVE"}, "delivery": {"shippingRates": {"id": "d9ab7dc1-dbfc-48ac-b6d0-1ff53b2a98b7"}, "handlingTime": "PT168H"}, "payments": {"invoice": "VAT"}, "afterSalesServices": {"impliedWarranty": {"id": "38e81e0f-23b5-41e1-ae12-2007d4934a19"}, "returnPolicy": {"id": "59e96e7a-3d20-47ca-97be-f4004bb1dff5"}, "warranty": {"id": "b2b37460-db13-4adc-9ccc-f4e5cfba16fc"}}, "location": {"countryCode": "PL", "province": "LODZKIE", "city": "Skierniewice", "postCode": "96-100"}, "external": {"id": 410696}, "attachments": [], "id": 8125392976}`

`'Trace-Id': 'ec9c1283179be9cc'`

Mimo podawania stock.available = 1 dostaję błąd:
`{"errors":[{"code":"VALIDATION_ERROR","message":"The stock level of items to be listed may not be lower than 1.","details":"","path":"","userMessage":"The stock level of items to be listed may not be lower than 1."}]}`

Błąd podobny do #763

**Comment by anih** [comment]
Zapomniałem dopisać, że chodzi o `PUT /sale/offers/{auction_id}`

**Comment by anih** [comment]
kolejny `'Trace-Id': '6c0a6c35c73268c0'` dotyczy aukcji 7789795546, `GET /sale/offers/{auction_id}` zwraca:
`{'available': 778, 'unit': 'UNIT'}`
a nie da się ustawić:
`{'available': 389, 'unit': 'UNIT'}`

**Comment by PawelTaberski** [comment]
@anih Widzę, że przy ofercie 7789795546 wielokrotnie zleciłeś zmianę stocku na różne wartości i ta zmiana się procesowała widzę, że teraz stock się zmienił.
Pamiętaj, że każda zmiana na ofercie może procesować się do godziny czasu.
Co do 8125392976 oferty wygląda to na błąd sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by anih** [comment]
zmiany faktycznie mogły być na różne stocki, bo mamy dość dynamiczny system i w przypadku tej oferty mogły być wywołane kilka razy taski z różnymi stockami, ale niestety najnowsza aktualizacja dla tej oferty dalej nie działa:
`'Trace-Id': 'cb38b2acec21efc6'`
Wysyłamy:
`{'available': 389, 'unit': 'UNIT'}`
I z tego co widzę przy pobieraniu oferty to dalej jest stara wartość stocku:
`{'available': 778, 'unit': 'UNIT'}`
Tak więc dla 7789795546 nie potwierdzam, że działa

**Comment by PawelTaberski** [comment]
Masz rację sprawdzałem ofertę przez front i w dostępnych narzędziach, a zasób GET /sale/offers/id zwraca niepoprawne dane sprawę również zgłosiłem. Dzięki za informacje 👍

**Comment by anih** [comment]
I kolejna aukcja: 8111263266
`'Trace-Id': '999500854bba0cc3'`
Próba zmiany stock z 2 na 1

**Comment by PawelTaberski** [comment]
Przekazałem te dane do zespołu, który już pracuje nad tym problemem. Prośba o cierpliwość.

**Comment by anih** [comment]
Dzięki, jeśli potrzeba kilku dodatkowych przykładów to dam radę znaleźć ;)
