### ISSUE TITLE
Pobranie ID płatności PayU

### ISSUE THREAD

**Issue by Przem4S** [allegro/allegro-api#1722]
Dzień dobry,

Czy istnieje możliwość pobrania identyfikatora płatności z PayU po którym można go powiązać w PayU? W integracji REST'owej znalazłem tylko identyfikator UUID płatności, i jak rozumiem jest to identyfikator wewnętrzny Allegro.

**Comment by PawelTaberski** [comment]
Jest to stary numer płatności możesz go pobrać jeszcze po WebAPI w REST API są już tylko numery w nowym formacie.
