### ISSUE TITLE
Adresowanie przesyłek Poczta odbiór w Punkcie

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#1723]
Dzisiaj dostałem z API e-nadawcy dziwny błąd: `Sposób dostawy Allegro nie wskazuje na odbiór w punkcie, a przesyłka ma ustawiony punktu odbioru.` Pojawił się on przy próbie adresowania zamówienia z Allegro z Odbiór w Punkcie z maskowanym e-mailem. Na stronie e-nadawcy pojawia się komunikat:

```
Informujemy, że wdrożenie nowej wersji Elektronicznego Nadawcy 10.1 zostało zakończone.

Po aktualizacji systemu, mogą wystąpić trudności z pobieraniem i obsługą danych transakcji przesyłek z grupy Allegro Dostawa z serwisu Allegro. Pracujemy nad wyeliminowaniem tej niedogodności. 

Szczegółowe informacje dotyczące współpracy w oparciu o architekturę REST API znajdą Państwo na stronie https://developer.allegro.pl/about/.
```

Jakiś komentarz z Państwa strony?

**Comment by Radeq** [comment]
Mam podobny problem, wina leży po stronie Poczty Polskiej (wraz z wdrożeniem aktualizacji 10.1) przy próbie nadania przesyłki biznesowej za pobraniem. Zgłosiłem to Poczcie, odpisali o 9:36, że "problem nie powinien już występować." ale nadal występuje.

**Comment by pgasidlo** [comment]
Wygląda że już działa.
