### ISSUE TITLE
Wyszukiwanie po kilku wartościach w filtrze external.id

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#1724]
:bulb: **Sugestia**
Dodanie możliwości podania tablicy z wartościami dla filtra _external.id_ w wyszukiwaniu ofert użytkownika _sale/offers_. Aktualnie można wyszukiwać tylko po jednym ID.
https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

**Comment by PawelTaberski** [comment]
Mamy w planach wdrożenie wyszukiwania po więcej niż jednym external.id w najbliższym czasie powinna pojawić się taka możliwość.
