### ISSUE TITLE
INVALID_JSON, offerDraft

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#1728]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przykładowy trace id: 6fc8bc0d5df84fa7

----
Szanowni Państwo,

W ostatnim czasie widzę częściej odpowiedź: "Invalid request. (INVALID_JSON)" dla zasobu oferty https://api.allegro.pl/sale/offers.

Proszę o informację, skąd programista ma wiedzieć co DOKŁADNIE w ofercie rzekomo zostało przesłane nieprawidłowo?

Zaobserwowałem, iż np. wysłanie opisu bez sekcji choć z 1 zdjęciem skutkuje w/w komunikatem. Natomiast przez serwis Allegro.pl, manualnie można dodać aukcję z takim schematem, więc mamy tutaj niespójność...

Proszę o wyjaśnienia.

**Comment by Maczuga** [comment]
Potwierdzam, również w tym tygodniu otrzymuję taki response.

**Comment by PawelTaberski** [comment]
Komunikat ten oznacza zazwyczaj nieprawidłowy format JSON-a. Jeśli macie przykład oferty która jest poprawna np. wystawiona przez front, pobrana przez API i otrzymujecie taki błąd, to podeślijcie proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a i responsa wraz z trace-id sprawdzimy to. W zgłoszeniu zaznaczcie proszę, że dane są potrzebne do ticketa numer 1728 na GitHub-ie.

**Comment by szado** [comment]
@PawelTaberski 

> Komunikat ten oznacza zazwyczaj nieprawidłowy format JSON-a.

Tak się właśnie domyśliliśmy, że "INVALID_JSON" będzie znaczyć nieprawidłowy JSON. Dziękujemy, captain obvius, chuja się znacie na temacie :P

**Comment by Onixarts** [comment]
A jak wkleisz jsona do jakiegoś validatora online to jest poprawny?

**Comment by jzskyshop** [comment]
Mam ten sam błąd i tak - wysyłany JSON jest poprawny składniowo.

**Comment by PawelTaberski** [comment]
@jzskyshop Podeślij proszę tego JSON-a przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), sprawdzimy co w nim jest nie tak. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1728 na GitHub-ie.

**Comment by PawelTaberski** [comment]
Sprawdziłem i problemem jest Id cennika nie powinieneś przesyłać go tak:
`		"shippingRates": "62cec73e-ba9.......................",`
a w taki sposób:
```
		"shippingRates": {
                            "id": "62cec73e-ba9......................."
                 },
```

**Comment by lukasx21** [comment]
> Sprawdziłem i problemem jest Id cennika nie powinieneś przesyłać go tak:
> `	"shippingRates": "62cec73e-ba9.......................",`
> a w taki sposób:
> 
> ```
> 		"shippingRates": {
>                             "id": "62cec73e-ba9......................."
>                  },
> ```

Zgadza się, moja pomyłka, bardzo dziękuję za pomoc... ale niestety nadal ten sam komunikat...

**Comment by kazz3m** [comment]
@PawelTaberski  Czy jest szansa, że w niedalekiej przyszłości resp będzie bardziej rozbudowany. Zmuszacie ludzi do przejścia na nowe API a mam wrażenie, że to nawet nie zasługuje na miano "bety"...  Ciekawe ile czasu support przepala na walidacje zgłoszeń? 
Również podesłałem przykład req dla którego otrzymuje taką lakoniczną zwrotkę.

**Comment by PawelTaberski** [comment]
REST API jest cały czas rozbudowywany, więcej informacji o planowanych zmianach i nowych zasobach znajdziesz w naszym [harmonogramie](https://developer.allegro.pl/schedule/).
