### ISSUE TITLE
Niewystarczające kanały informacyjne

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#1729]
:bulb: **Sugestia**

Wydaje mi się, że kanały informacyjne, w których można dowiedzieć się o zmianach (planowanych włączeniach, wyłączeniach i aktualizacjach API) są niewystarczające; Aby dowiedzieć się czegoś ze stron

- GitHub z labelką NEWS;
- https://developer.allegro.pl/news
- https://allegro.pl/webapi/news.php

należy pamiętać o tym, że od czasu do czasu trzeba na nie wejść. W przypadku dużych systemów i wielu integracji pamiętanie o tym jest kłopotliwe

W przypadku wygaszania danych metod informacja jest wysyłana mailowo do użytkowników, którzy korzystają z danych metod. Problem w tym, że tego typu emaile trafiają do osób nietechnicznych, nie potrafiących obiektywnie ocenić wagi zawartych w emailach informacji. W konsekwencji informacja nie trafia do programistów.

W związku z powyższym brakuje mi mechanizmu bezpośredniego informowania mnie o ważnych zmianach. Może jakiś newsletter bezpośrednio dla developerów, do którego można by się zapisać?

**Comment by Maczuga** [comment]
Newsletter albo chociaż jakiś oficjalny RSS byłby dobry.  

Newsy z WebAPI miały swój RSS: http://allegro.pl/rss.php?feed=webapi_news&gen=1&all=1 jednak brakuje tam informacji, które są tutaj z labelem NEWS.

Póki co korzystam z usług stron trzecich, żeby wyciągać z tego githuba zgłoszenia z labelem NEWS: https://rsshub.app/github/issue/allegro/allegro-api?filter_title=NEWS - jednak działa to kiedy chce.

**Comment by imper86** [comment]
@adamTynski od siebie mogę zasugerować po prostu notyfikacje o nowych postach z githuba, w gmailu można sobie elegancko przefiltrować to w taki sposób żeby dostawać tylko informacje o newsach.

**Comment by adamTynski** [comment]
Przetestuję notyfikacje - dziękuję za sugestię
