### ISSUE TITLE
 Jak uzyskać datę kiedy zostaną kolejny raz naliczone opłaty za wystawienie aukcji?

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#173]
Mam aukcje wystawione na czas nieokreślony, oferta sklepowa. Chce je zakończyć przed kolejnym naliczeniem opłat. Jak uzyskać datę kiedy zostaną kolejny raz naliczone opłaty za wystawienie aukcji?

**Comment by KrzysztofLukanowski** [comment]
Możesz to zrobić za pomocą REST API. [Przeczytaj jak to zrobić.](https://developer.allegro.pl/news/2018-02-14-Zasob_do_sprawdzania_daty_oplaty/)

**Comment by Jarzebowsky** [comment]
Funkcja nie działa poprawnie, zwraca zawsze
`object(stdClass)[12]
  public 'count' => int 0
  public 'quotes' => 
    array (size=0)
      empty`

**Comment by Jarzebowsky** [comment]
@KrzysztofLukanowski wszystkie aukcje, których to dotyczyło są oponami używanymi ciężarowymi. Opłaty są naliczane co 10 dni za przedłużenie aukcji. Jeżeli chodzi o numery, to dla tych aukcji, które sprawdzałem zostały już zamknięte ręcznie, ale dla przykładu np. **6340922942**

**Comment by KrzysztofLukanowski** [comment]
Spróbuj wywołać metodę dla tej konkretnej, wskazanej oferty. Przed chwilą otrzymałem prawidłową odpowiedź dla oferty wystawionej w tej kategorii z tymi samymi parametrami:

{
    "count": 1,
    "quotes": [
        {
            "type": "LISTING",
            "name": "Wystawienie",
            "nextDate": "2018-05-14T06:45:06.992Z",
            "fee": {
                "amount": "0.6",
                "currency": "PLN"
            },
            "offer": {
                "id": "000000000"
            },
            "enabled": false
        }
    ]
}

**Comment by Jarzebowsky** [comment]
@KrzysztofLukanowski u mnie dla tej oferty dalej zwraca pustą tablicę.

**Comment by KrzysztofLukanowski** [comment]
Sprawdź proszę raz jeszcze tę metodę dla trwającej oferty wystawionej do wyczerpania zapasów, jeżeli problem powtórzy się - podaj request i response.

**Comment by Jarzebowsky** [comment]
```
GET /pricing/offer-quotes?offer.id=["7272340312"] HTTP/1.1
Host: allegroapi.io
Expect:
User-Agent: Httpful/0.2.20 (cURL/7.50.3 PHP/7.0.12 (WINNT) Apache/2.4.23 (Win32) OpenSSL/1.0.2h .0.12 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36)
Content-Type: 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Api-Key: Api-key
Authorization: Bearer Token
Content-Length: 0
```

`{"count":0,"quotes":[]}' (length=23)`

**Comment by KrzysztofLukanowski** [comment]
Sprawdź w ten sposób:

```
GET /https://api.allegro.pl/pricing/offer-quotes?offer.id=7272340312

Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Api-Key: Api-key
Authorization: Bearer Token

**Comment by Jarzebowsky** [comment]
Problem rozwiązany, przy wysyłaniu nagłówka przez curl zmieniłem:

```
        $headers = array(
            'Accept' => 'application/vnd.allegro.public.v1+json',
            'Content-Type' => 'application/vnd.allegro.public.v1+json',
            'Api-Key' => $this->providerSettings['ApiKey'],
            'Authorization' => 'Bearer ' . $access_token
        );
```

na

```
        $headers = array(
            'Accept: application/vnd.allegro.public.v1+json',
            'Content-Type: application/vnd.allegro.public.v1+json',
            'Api-Key: ' . $this->providerSettings['ApiKey'],
            'Authorization: Bearer ' . $access_token
        );
```

**Comment by KJtTGHAK** [comment]
Da się to zrobić za pomocą **SOAP** ?

**Comment by KrzysztofLukanowski** [comment]
Nie. Jest to możliwe wyłącznie w REST API.
