### ISSUE TITLE
Komunikaty walidacji czytelne dla Klientów

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#1731]
:bulb: **Sugestia**
Dzień dobry. Proszę o zwracanie komunikatu czytelnego dla Klienta przy próbie zmiany ilości na ofercie z licytacją.

```
REQUEST 2019-05-31 08:53:15.9261517
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/############/tasks?limit=1&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ########' \

RESPONSE 2019-05-31 08:53:16.0381052 Duration: 111,9535ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2019-05-31T06:51:21.566Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "6206375683"
        },
        "ScheduledAt": "2019-05-31T06:51:19.41Z",
        "Status": "FAIL"
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```

**Comment by PawelTaberski** [comment]
@alekskuc Czy te wywołanie jest na pewno od tego responsa? Bo widzę, że wywołujesz metodę do sprawdzenia statusu aktywacji/zakończenia oferty, a responsa masz od /sale/offer-quantity-change-commands/{commandId}/tasks 
Nad komunikatami błędu jak najbardziej pracujemy zarówno nad ich poprawą jak i doprecyzowaniem w wielu wypadkach.

**Comment by alekskuc** [comment]
> @alekskuc Czy te wywołanie jest na pewno od tego responsa? Bo widzę, że wywołujesz metodę do sprawdzenia statusu aktywacji/zakończenia oferty, a responsa masz od /sale/offer-quantity-change-commands/{commandId}/tasks
> Nad komunikatami błędu jak najbardziej pracujemy zarówno nad ich poprawą jak i doprecyzowaniem w wielu wypadkach.

@PawelTaberski Jak najbardziej od tego responsa. Raporty rest api są najwyraźniej fikcyjnie rozbite na różne metody, bo z odpowiednimi commandId dostaje prawidłowe responsy dla wszystkich requestów z jednej i tej samej metody /sale/offer-publication-commands/

Zmienię te wywołania na adekwatne. 

W rest api zatem tez to jest do poprawienia. Jedna metoda pobierająca wszystkie raporty według UUID była dla mnie intuicyjna.

**Comment by Maczuga** [comment]
Ten sam błąd zgłaszany półtora miesiąca temu tutaj - dalej bez poprawy: https://github.com/allegro/allegro-api/issues/1493#issuecomment-482782031

**Comment by PawelTaberski** [comment]
@alekskuc Sprawdziłem i rzeczywiście masz rację, sprawę zgłosiłem do zespołu odpowiedzialnego za te zasoby. Odnośnie samego komunikatu oczywiście pracujemy nad tym aby były precyzyjniejsza.
Błąd EXCEPTION_DURING_OFFER_QUANTITY_UPDATE wynika najprawdopodobniej z tego, że oferta nie jest kompletna tzn. np. nie ma jakiś obowiązkowych parametrów dlatego cena nie może być zmieniona.

**Comment by Maczuga** [comment]
> Błąd EXCEPTION_DURING_OFFER_QUANTITY_UPDATE wynika najprawdopodobniej z tego, że oferta nie jest kompletna tzn. np. nie ma jakiś obowiązkowych parametrów dlatego cena nie może być zmieniona.

Chyba masz na myśli ilość a nie cenę (błąd tyczy się quantity). Jeżeli to co mówisz jest prawdą to jest to bezsensowna logika. Czemu? Spieszę z przykładem.

Mamy na stanie 10 sztuk produktu, wy dodajecie jakiś nowy wymagany atrybut, u nas w sklepie ktoś kupi 9 sztuk - także musimy zmienić stan u was na = 1. Wg. Twojej logiki nie możemy zmienić, bo doszedł nowy atrybut a o tym nie wiemy, także wywala błąd (a proces synchronizacji chodzi w tle). W tym samym czasie ktoś z Allegro kupuje 10 sztuk - bo nie dało się zmienić stanu.

**Comment by alekskuc** [comment]
> 💡 **Sugestia**
> Dzień dobry. Proszę o zwracanie komunikatu czytelnego dla Klienta przy próbie zmiany ilości na ofercie z licytacją.
> 
Na samym początku napisałem dlaczego mam taki błąd EXCEPTION_DURING_OFFER_QUANTITY_UPDATE. Nie harkoduje w swojej aplikacji walidacji i zdaje się na walidacje z rest api.

Celowo tez zostawiłem numer aukcji w requescie: 
[https://allegro.pl.allegrosandbox.pl/show_item.php?item=6206375683](https://allegro.pl.allegrosandbox.pl/show_item.php?item=6206375683)

> > Błąd EXCEPTION_DURING_OFFER_QUANTITY_UPDATE wynika najprawdopodobniej z tego, że oferta nie jest kompletna tzn. np. nie ma jakiś obowiązkowych parametrów dlatego cena nie może być zmieniona.
> 
> Chyba masz na myśli ilość a nie cenę (błąd tyczy się quantity). Jeżeli to co mówisz jest prawdą to jest to bezsensowna logika. Czemu? Spieszę z przykładem.
> 
> Mamy na stanie 10 sztuk produktu, wy dodajecie jakiś nowy wymagany atrybut, u nas w sklepie ktoś kupi 9 sztuk - także musimy zmienić stan u was na = 1. Wg. Twojej logiki nie możemy zmienić, bo doszedł nowy atrybut a o tym nie wiemy, także wywala błąd (a proces synchronizacji chodzi w tle). W tym samym czasie ktoś z Allegro kupuje 10 sztuk - bo nie dało się zmienić stanu.

Natomiast jeżeli teraz zmiana ilości tak działa, że nie można jej zmienić dla oferty bez dodatkowych parametrów które będą dochodziły z czasem, to jest to **poważny problem**.

Korzystamy z tego samego scenariusza, o którym pisał @Maczuga do aktualizacji stanów magazynowych, które się zmieniają z **wielu kanałów sprzedaży, allegro jest jednym z nich**. Taka aktualizacja ilości niezależnie od pól formularza dla kategorii była możliwa w web api.

Proszę zatem o umożliwienie zmiany ilości na aukcjach niezależnie od nowych parametrów dla kategorii, które będą się zmieniały z czasem.

**Comment by PawelTaberski** [comment]
Jeśli wywołasz grupową edycję np stanu magazynowego to w zasobie do sprawdzenia statusu do zadania otrzymasz teraz informację, czy udało się dokonać zmiany jeśli nie to z jakiego powodu.
Tak jak wspominałem, aby dokonać zmian w ofercie np ceny, stocku itp musi być ona kompletna czyli również uzupełniona o nowe już wymagane parametry. Nie planujemy zmiany tego mechanizmu.

**Comment by Maczuga** [comment]
@PawelTaberski Czytacie czasem co ludzie piszą, czy po prostu odpisujecie stałymi formułkami? 
Idąc Twoim tokiem rozumowania - jakiś nowy atrybut w kategorii jest ważniejszy niż aktualny rzeczywisty stock **AKTYWNYCH** już ofert? Tak nie było w WebAPI jak pisał @alekskuc. 

Wyczuwam, że support tutaj jest sam niedoinformowany...

**Comment by SebastianOzdoba** [comment]
@PawelTaberski przecież to jest głupie!
Mam 5000 aukcji w 20 różnych kategoriach. Automat co 30 minut zmienia mi stan magazynu, z uwagi na pracę z wieloma różnymi marketplace, chcecie by user śledził czy nie wystąpiły błędy i poprawiał oferty które są np wystawione np rok temu. Gdzie tu automatyzacja po stronie Klienta? @alekskuc, @maczuga

**Comment by yncki** [comment]
@SebastianOzdoba, @PawelTaberski  true - głupie. 

Podstawowe parametry jak nagłówki ( stock, price , title ) powinny mieć możliwość aktualizacji nawet gdy parametry nie przechodzą. Nasi klienci na bank będą zgłaszali skargi że w allegro się stocki nie aktualizują. Straci Allegro bo w oczach sprzedawców inne marketplace'y nie stwarzają takich problemów i dziwnych warunków. Już teraz niektórzy z nich mają większą sprzedaż na ebay niż na allegro. A to dopiero początek drogi multichannel. 

@PawelTaberski - uprzejmie proszę - rzućcie to jeszcze raz na "tapetę" - nie życzę wam źle i znajdźmy jakiś kompromis.

**Comment by PawelTaberski** [comment]
Parametry są bardzo istotną częścią oferty mają bardzo duży wpływ na trafne wyszukanie oferty przez kupującego, dlatego nie planujemy zmiany tego mechanizmu.

**Comment by TimothyKoval** [comment]
Istotniejszą niż nazwa, cena czy ilość?

**Comment by PawelTaberski** [comment]
Są one równie istotne, gdyż mają duży wpływ tak jak wspomniałem m.in. na wyszukanie oferty.

**Comment by TimothyKoval** [comment]
Czyli parametry są ważne dla was, bo kupujący łatwiej znajdzie ofertę i sprzedający zapłaci prowizję. Cena czy ilość jest ważna dla sprzedających, bo nie mogą sprzedawać powyżej dostępności czy dopuszczalnej ceny.

Te pierwsze są oczywiście ważniejsze (W waszym mniemaniu), co po raz kolejny pokazuje jak głęboko macie sprzedających. Gratulacje.

**Comment by TimothyKoval** [comment]
https://allegro.pl/regulamin/pl#artykul-5-rozpoczecie-transakcji

> 5.2.
> 
> Treść Oferty powinna być rzetelna i kompletna oraz nie może wprowadzać w błąd innych Użytkowników, w szczególności co do właściwości Towaru, takich jak: jego **STAN**, jakość, pochodzenie, marka czy producent.

O parametrach nic w regulaminie nie znalazłem. Ponawiam pytanie; brakujące parametry są ważniejsze, mniej ważne czy równie ważne jak stan czy ilość?

**Comment by yncki** [comment]
Nie rozumiem, @PawelTaberski . 

W obu przypadkach traci kupujący, a w jednym przypadku traci sprzedawca.  Fajnie że jesteście pro consumer ale :

**Gdy sprzedawca sprzeda coś czego nie dopilnował automat (stock się nie zaktualizował) przez brak jednego parametru - to kupujący tego towaru nie otrzyma. Więc to KUPUJĄCY będzie poszkodowany przez taką decyzję ( sprzedawca of cors też ) **

**Comment by SebastianOzdoba** [comment]
Podbijam by się nie zamknął, no temat jest ważny

**Comment by PawelTaberski** [comment]
Przekazałem sugestię odnośnie nie brania pod uwagę braków oferty, przy zmianie stocku bądź ceny. Są obecnie rozważane różne scenariusza. Jeśli zdecydujemy się na zmianę mechanizmu to poinformujemy o tym.

**Comment by Maczuga** [comment]
Ponowne podbicie, niektóre komunikaty jak były tak dalej są niezrozumiałe.

**Comment by PawelTaberski** [comment]
Cały czas pracujemy nad ich ulepszeniem, a czy mógłbyś podać jakiś przykład nieczytelnego komunikatu i kiedy on występuje?

**Comment by Maczuga** [comment]
@PawelTaberski już zgłaszałem w maju, od tej pory nic się nie zmieniło w czytelności komunikatów.
https://github.com/allegro/allegro-api/issues/1731#issuecomment-497685100

**Comment by PawelTaberski** [comment]
@Maczuga Rozumiem, w niektórych zasobach do grupowej zmiany już rozbudowaliśmy komunikat błędu, ale jeszcze nie we wszystkich pracujemy nad tym.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski 
Kiedy możemy liczyć na rozbudowę tego: EXCEPTION_DURING_OFFER_QUANTITY_UPDATE
Nic nie mówi użytkownikowi a potrzeba jasnego przekazu dlaczego się nie udała zmiana ilości

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Mógłbyś podesłać przykładowy trace-id w którym obecnie otrzymujesz taki błąd.

**Comment by alekskuc** [comment]
> @SebastianOzdoba Mógłbyś podesłać przykładowy trace-id w którym obecnie otrzymujesz taki błąd.

```
REQUEST 2019-07-25 15:27:47.4102715
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offer-quantity-change-commands/fe130ab1-b1ef-4575-b4f8-8464e18cd9d0/tasks?limit=1&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ###' \

RESPONSE 2019-07-25 15:27:47.4883724 Duration: 78,1009ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2019-07-25T13:26:18.599Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "6206493669"
        },
        "ScheduledAt": "2019-07-25T13:26:15.638Z",
        "Status": "FAIL"
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "eacd647115de0fe2",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```

**Comment by PawelTaberski** [comment]
@alekskuc Jest to błąd z sandboxa i już otrzymany jakiś czas temu, czy w chwili obecnej również trafiają się wam błędy z takim komunikatem zwłaszcza na produkcji?

**Comment by Maczuga** [comment]
@PawelTaberski U nas na produkcji są często. Ostatni wysyp 2 dni temu. 

ID tasków:
- eeb856cd-70c0-4af9-83a8-31af0346b695
- 8c7806e3-81d7-41c7-ae2a-187fdce90101
- f661b9d9-4b22-49e2-86bc-ea8e1fa58fea
- 8da574b8-11d3-44d3-905a-cabfe8eff75e
- 67d5c260-736b-49aa-87a5-7f7cab0bc19d
- e41471bc-e5d9-48e3-abb5-4166dd1cf81d
- b69d1d45-bcec-4878-aac5-4f211fe04892
- 3fcdbea4-dde7-437e-9f3f-b3aaf8dd50b7
- fa2de7c2-bfde-4391-ac93-270a54762bd8
- e6fe65d7-e362-4993-97af-f83514c42732
- 64ba2101-d747-4571-ae4f-6be8b7152cd1
- d00e2f11-902c-4f7c-b71f-fc1656ebe54d

**Comment by PawelTaberski** [comment]
@Maczuga Struktura błędu jest już rozbudowana, ale sam komunikat rzeczywiście w tym przypadku niewiele pomaga. Zgłosiłem go do uszczegółowienia.
