### ISSUE TITLE
Błąd 502 Bad Gateway

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#1733]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Na środowisku testowym występuje problem z uploadem zdjęć próba pobrania zdjęcia kończy się błędem 502

https://a.allegroimg.allegrosandbox.pl/original/11ca66/76a17f584299a126e140e1467a0f

**Comment by PawelTaberski** [comment]
Przetestowałem i widzę, że metoda działa prawidłowo, czy dalej masz z nią problem? I  jaką grafiką masz problem czy przesyłasz ja po linki? Tutaj widzę, że dodałeś link ale już załączonej grafiki na środowisku testowym.

**Comment by AlpanetPL** [comment]
Jeśli mogę się podłączyć, u mnie też wywołanie linka do grafiki, który zwróciło REST API kończyło się błędem 502, jednak zauważyłem, że po pewnym czasie link zaczął działać prawidłowo. Być może grafiki są pobierane w jakimś odstępie czasowym? Jeśli tak mógłbym prosić o informację, jaki to jest czas na sandboksie i na produkcji?

**Comment by PawelTaberski** [comment]
Grafika powinna być od razu załączona, czy u Ciebie problem dalej występuje?

**Comment by AlpanetPL** [comment]
Nie, teraz są od razu tak jak Pan napisał, ale przez dość długi czas zwracało 502. W każdym bądź razie teraz u mnie jest OK. Dzięki.

**Comment by p-pawel** [comment]
Podbijam, bo doświadczam tego samego błędu. Dotyczy to również zdjęć do aukcji wystawionych kilka dni temu, np. tych tutaj: https://allegro.pl.allegrosandbox.pl/kategoria/akcesoria-etui-opaski-na-ramie-147270.

Co ciekawe 502 pojawia się również przy dostępie do listingu aukcji wystawionych przez tego użytkownika (`Wszystkie przedmioty sprzedającego` z aukcji).

Problem dotyczy zdjęć dodawanych zarówno jako binary-data jak i tych z URLa.

Przykładowy URL powodujący 502: https://a.allegroimg.allegrosandbox.pl/original/11bdba/80740a82487fb2de36a4b017577b


Kroki:
1. Uploadujemy zdjęcie (token wycięty z nagłówków)
```
curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/images \
  -H 'authorization: Bearer ....................................................' \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -d '{ "url":"https://developer.allegro.pl/images/icon-info.png" }'
```

2. Otrzymujemy response:
```
{
    "expiresAt": "2019-06-12T18:08:44.386639Z",
    "location": "https://a.allegroimg.allegrosandbox.pl/original/11bdba/80740a82487fb2de36a4b017577b"
}
```

3. Odwiedzamy powyższy adres https://a.allegroimg.allegrosandbox.pl/original/11bdba/80740a82487fb2de36a4b017577b i zamiast zdjęcia jest 502.

**Comment by PawelTaberski** [comment]
Przetestowałem na innych zdjęciach i zasób działa poprawnie, ale wymieniony przez Ciebie plik po zaciągnięciu wygląda niepoprawnie. Sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by p-pawel** [comment]
Dzięki. Zauważyłem jeszcze że dotyczy to tylko Sandboxa, na środowisku produkcyjnym uploadowane obrazki wyświetlają się bez problemów.
