### ISSUE TITLE
Długość nazwy oferty

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#1736]
Dzień dobry, ma miejsce następująca sytuacja:
- zlecamy utworzenie szkicu oferty z nazwą `XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX 12"` (X - małe i duże litery),
- szkic tworzy się poprawnie bez żadnych komunikatów o błędach,
- zlecamy jego publikację,
- oferta jest publikowana,
- w opublikowanej ofercie nazwa wygląda następująco: `XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX 1`

**Comment by PawelTaberski** [comment]
Maksymalna długość tytułu to 50 znaków niektóre znaki są encjonowane i zajmują więcej niż jeden znak jak np " który to zaencjonowany zajmuje aż 6 znaków. Po przesłaniu requesta w responsie powinieneś otrzymać informacje:
```
    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "ERR_ITEM_NAME_TOO_LONG",
                "details": "",
                "path": "",
                "userMessage": ""
            },
```

**Comment by jzskyshop** [comment]
Jak opisałem, powtórzę: wysyłam konkretny tytuł (48 znaków nieencjonowanych) - szkic zapisuje się poprawnie (w podglądzie na Allegro wygląda poprawnie). PO publikacji jest ucinany do postaci jak opisałem.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) GET-a z drafta jaki publikujesz i obcina tobie tytuł. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1736 na GitHub-ie.
