### ISSUE TITLE
Odczyt stanu ilościowego produktów na aukcji

### ISSUE THREAD

**Issue by web3promagraco** [allegro/allegro-api#1737]
Witam,
chciałbym zapytać, czy nowe REST API Allegro będzie umożliwiało deweloperom odczytywanie stanu ilościowego z aukcji internetowej Allegro? Mam na uwadze automatyczną zmianę stanu magazynowego produktów powiązanych z aukcjami Allegro, na skutek ręcznej zmiany ilości produktów na aukcji od strony Allegro. Bardzo ułatwiłoby to zarządzanie stanami magazynowymi ludziom przyzwyczajonym do pracy w obrębie platformy Allegro i jednocześnie budującym inne kanały dystrybucji.
Pozdrawiam,
Michał

**Comment by PawelTaberski** [comment]
Nie wiem, czy dobrze rozumiem Twoje pytanie, ale jeśli dokonasz jakiejś zmiany w ilości, cenie to oczywiście jest to widoczne w Moim Allegro i można również zmienić tam ilość cenę i pobrać zmienione dane przez front po API.
