### ISSUE TITLE
GET sale/offers zwraca inne dane bez nagłówka Accept

### ISSUE THREAD

**Issue by karolus888** [allegro/allegro-api#1738]
Dzień dobry,
Dziś zauważyłem, że metoda GET sale/offers zwraca inne dane jeżeli nie przekażę nagłówka Accept: application/vnd.allegro.public.v1+json.
Z nagłówkiem Accept:application/vnd.allegro.public.v1+json
"offers": [],
"count": 20,
"totalCount": 499
Bez nagłówka Accept:
"items": [{
...
"eventsVersions": {
"offerDataTimestamp": "2019-05-30T21:13:34.896Z",
"currentPriceTimestamp": null,
"inSaleAmountTimestamp": "2019-05-31T22:13:22.514Z",
"soldAmountTimestamp": null,
"offerRebatesTimestamp": null,
"offerBadgesTimestamp": null,
"watchersCountTimestamp": "+51382-04-11T03:35:47Z",
"visitsCountTimestamp": "2019-05-31T22:56:17.538Z",
"productVersion": null,
"offerLabelsTimestamp": null,
"productIdInternalChangedTimestamp": null
}
..
}],
"totalItems": 499

Nie ukrywam, że te informacje otrzymane po wywołaniu bez nagłówka Accept są dużo bardziej wartościowe, bo pozwalają rozpoznać oferty, które uległy zmianie od ostatniego pobrania.
Jaką wartość nagłówka Accept należy przekazać, aby otrzymać zawsze odpowiedź w tej formie?
Próbowałem v2, beta.v2, ale bez skutku.

**Comment by PawelTaberski** [comment]
Jaką informację przekazujesz w tym nagłówku? Przetestowałem i jeśli nie prześlesz żadnej wartości otrzymasz:
```
{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "Not acceptable representation requested. Please check 'Accept' request header",
            "details": null,
            "path": null,
            "userMessage": "The request contains incorrect data. Contact the author of the application."
        }
    ]
}
```

**Comment by karolus888** [comment]
Nie przekazuję w ogóle nagłówka Accept. Jeżeli przekażę pusty to dostaję ten sam błąd co wysłałeś.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i trace-id. Testowałem zarówno z pustym jak i brakiem tego nagłówka i za każdym razem otrzymuje ten sam błąd.
