### ISSUE TITLE
draft oferty - dostęp przez przeglądarkę

### ISSUE THREAD

**Issue by collector1871** [allegro/allegro-api#1739]
dzień dobry,

będę się przymierzał do zaprogramowania całego procesu związanego z wystawianiem oferty: https://developer.allegro.pl/sale/

aktualnie nasze oferty nie są całkowicie uzupełnione, mianowicie chcielibyśmy brakujące parametry wystawić i uzupełnić **bezpośrednio przez przeglądarkę, np. firefoxa**

stąd moje teoretyczne pytanie:

jeżeli utworzę draft oferty (krok 7: https://developer.allegro.pl/sale/ ) i dostanę response, że draft został poprawnie utworzony (czyli dostanę ID drafta), to mogę później bezpośrednio sobie np. wejść przez firefoxa i dokonczyć ofertę już manualnie (uzupełnić brakujące parametry) ?

czyli cały flow wystawienia byłby taki:
- parsujemy dane przedmiotu z bazy danych do JSON
- rest api POST tworzymy draft oferty
- otrzymujemy response z ID drafta
- układamy z tego URL i wchodzimy bezpośrednio przez firefoxa
- uzupełniamy braki ręcznie
- publikujemy ofertę

da się coś takiego osiągnąć?

**Comment by PawelTaberski** [comment]
Oczywiście można tak zrobić, draft pojawi się w zakładce moje oferty jako szkic. Należy wybrać z rozwijanej listy status oferty jako szkic.

**Comment by collector1871** [comment]
Tak myślałem.

szkic we front-end = draft w back-end

Dziękuję.

Można zamknąć.

PS. możecie uzupełnić dokumentację, bo tej informacji nie ma bezpośrednio w doc. A jest bardzo pomocna jeżeli ktoś ma niepełne dane i chce uzupełnić braki przez przeglądarkę (tak jak naszej sytuacji).

pozdrawiam !
