### ISSUE TITLE
doGetSiteJournal nie zwraca danych - tylko u mnie?

### ISSUE THREAD

**Issue by kaminiak23** [allegro/allegro-api#174]
doGetSiteJournal 
tylko dla mnie nie zwraca danych czy może jest z tym jakiś kłopot? sprawdzałem dla zalogowanego i całego serwisu i dostaję cały czas:
stdClass Object
(
    [siteJournalArray] => stdClass Object
        (
        )

)
Może mam jakiegoś bana (ale chyba dostałbym błąd wtedy a nie puste wyniki)?
Sprawdzałem to na allegro i tam jest zwracane ok., jest jakiś kłopot czy może tu trzeba inaczej jakoś wywołać? Ma ktoś może podobną trudność?

Pytanie drugie. Zabezpieczacie się na wypadek zwracania takich pustych wartości (pobierając dane innymi metodami jeśli tu jest pusto)?

**Comment by MaciejPotepa** [comment]
Nie mamy ogólnych problemów z dziennikami. Żebym mógł przeanalizować problem, który napotkałeś - podeślij proszę request i response zapisane w pliku XML.

Dokładne dane, które udostępniamy w doGetsiteJournal są dostępne tylko w tej metodzie.

**Comment by kaminiak23** [comment]
Dziękuję za odpowiedź. Wybacz ale niestety nie wiem (nie umiem ale bardziej nie rozumiem) jak to jest z tym XML (jak miałbym podać)
Sprawdziłem jeszcze raz dokładnie i na allegro działa to poprawnie, dzienniki wpadają a tu dostaje pusty wynik. 
sprawdziłem teraz jeszcze metodę doGetSiteJournalDeals i ta zwraca mi wyniki poprawnie. Sprawdzałem to na moim logowaniu i kilku klasach pobranych od innych. :)

**Comment by MaciejPotepa** [comment]
Musisz zapisać treść request i response, który do nas wysyłasz i otrzymujesz za pośrednictwem protokołu [SOAP ](https://pl.wikipedia.org/wiki/SOAP) w jego podstawowej formie czyli XML. Bez tego nie jesteśmy zbytnio w stanie zdiagnozować lub sprawdzić gdzie leży problem.

**Comment by Tomash667** [comment]
Mam ten sam problem, sprzedałem 2 przedmioty a doGetSiteJournal nic nie zwraca.

Request:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoGetSiteJournalRequest>
         <ser:sessionHandle>...</ser:sessionHandle>
         <ser:startingPoint>0</ser:startingPoint>
         <ser:infoType>0</ser:infoType>
      </ser:DoGetSiteJournalRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

Response:
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <SOAP-ENV:Body>
      <ns1:doGetSiteJournalResponse>
         <ns1:siteJournalArray/>
      </ns1:doGetSiteJournalResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

doGetSiteJournalDeals zwraca wpisy.

**Comment by MaciejPotepa** [comment]
@Tomash667 pracujemy nad rozwiązaniem problemu.

**Comment by MaciejPotepa** [comment]
@kaminiak23, @Tomash667 Czy problem nadal u Was występuje?

**Comment by Tomash667** [comment]
@MaciejPotepa tak, bez zmian. Założyłem nową aukcję i kupiłem z drugiego konta a w odpowiedzi pusto.

**Comment by MaciejPotepa** [comment]
@Tomash667 Dzięki za odpowiedź. Czy możesz podać numer oferty?

**Comment by Tomash667** [comment]
@MaciejPotepa  http://allegro.pl.allegrosandbox.pl/laptop-asus-i6205372039.html

**Comment by PawelTaberski** [comment]
Przekazałem numer oferty do zespołu zajmującego się rozwiązaniem tego problemu, proszę o cierpliwość.

**Comment by MaciejPotepa** [comment]
@kaminiak23 @Tomash667 problem nie powinien już występować. Dzięki za cierpliwość.
