### ISSUE TITLE
Czas realizacji w /sale/offers/

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#1740]
:bulb: **Sugestia**

Dla firm sprzedających produkty w różnych czasach realizacji, które zarządzają tym czasem także z poziomu API byłoby dużym ułatwieniem, gdyby metoda /sale/offers/ zwracała także informację o delivery->handlingTime
Pomogłoby to synchronizować czasy realizacji z aktualnym stanem magazynowym bez konieczności sięgania przy każdym przebiegu po metodę /sale/offers/{{offerId}}

**Comment by PawelTaberski** [comment]
Rozumiem sugestię oczywiście przekazałem. Jeśli zdecydujemy się wdrożyć taką zmianę, to poinformujemy o tym w dedykowanym komunikacie.
