### ISSUE TITLE
Pobranie swoich aukcji promowanych

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#1741]
Czy jest opcja pobrania **swoich** ofert promowanych? Zarządzam promowaniami przez Allegro a nie api i muszę cyklicznie pobierać do analiz informację o ofertach promowanych, aby dobrze liczyć wysokosć prowizji. Niestety te dane są dostępne dopiero w danych szczegółowych, co oznacza, że pobierając je cyklicznie muszę wiele tysięcy razy pytać o każdy numer oferty osobno i dopiero wtedy mam potrzebne informacje - może ktoś coś wymyślił, ew. może dałoby się wrzucić te dane w dane zwracane w /sale/offers/?filters

**Comment by PawelTaberski** [comment]
Zgłosiłem sugestię dodania odpowiedniego filtra do zasobu sale/offers z wartościami jak na froncie. Jeśli wdrożymy taką zmianę, to poinformujemy o tym w dedykowanym komunikacie.
