### ISSUE TITLE
Lista transakcji do wypłaty

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#1742]
Czy metoda
/payments/payment-operations
Będzie zawierała docelowo listę transakcji dla grupy Outcome? Bez tego nie jesteśmy w stanie pobrać listy transakcji z UUID powiązanych do wypłaty. Stara metoda doGetMyPayouts zwraca ID Transakcji nie RESTowe - więc bez mapowania (które z odpowiedzi w jednym wątku związanym z mapowaniem dealID na LineItemId nie jest planowane) lub dodania tej listy tu (lub nowej metody) nie będziemy w stanie automatyzować rozliczania rozrachunków do wystawionych setek dokumentów.

**Comment by MartaNowaczyk** [comment]
Zgłosiłam sugestię do odpowiedniego zespołu. Czekam na informacje. Dam znać, gdy coś ustalę.

**Comment by MartaNowaczyk** [comment]
Dostałam informację, że nie planujemy takiej listy ze względu na to, że w historii operacji obowiązuje trochę inna sytuacja. Wszystkie operacje, które są między jedną a drugą wypłatą składają się na daną wypłatę. Ważne jest także saldo po danej operacji.

**Comment by Zbigniew-L** [comment]
Czy dobrze rozumiem, że w ogóle nie zrobicie w RestAPI odpowiednika metod doGetMyPayouts i  doGetMyPayoutsDetails (które wygaszacie do końca roku)? Będziemy zatem musieli sobie te metody sami zrobić analizując rekordy uzyskane z payment-operations ?

**Comment by MartaNowaczyk** [comment]
Na ten moment właśnie tak to wygląda.
