### ISSUE TITLE
Poprawny sposób wznawiania aukcji

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#1743]
W webapi była możliwość przesłania pola fid_30 co skutkowało tym, że aukcja po upłynięciu czasu wznawiała się ponownie.
W REST API z tego co widze nie można przesłać tego pola, poprawnym sposobem wznawiania ofert Kup Teraz jest wznawianie jeśli dobrze rozumiem, ale aukcji nie można wznowić w ten sposób stąd pytanie jak powinien wyglądać poprawny proces wznawiania niesprzedanych aukcji? Czy należy taką aukcje skopiować i wystawić jako nową?

**Comment by qls-api** [comment]
Od siebie dodam ze za pomocą metody PUT /sale/offer-publication-commands/{commandId}, wystawienie ponowne licytacji kończy się niepowodzeniem. Mamy błąd "Nie można aktywować zakończonej oferty."
Zatem jaki powinien być prawidłowy algorytm w tym przypadku?

**Comment by pawelosajda** [comment]
Dokładnie o ten problem chodzi to działa tylko dla ofert Kup Teraz

**Comment by MartaNowaczyk** [comment]
@pawelosajda W ciągu 60 dni od zakończenia oferty każdą ofertę można aktywować lub pobrać i wystawić jako nową. Poza tym w tej chwili najlepszą opcją jest wystawienie oferty do wyczerpania przedmiotów. 

@qls-api  zgadzam się z pawellosajda. W twoim przypadku trzeba wystawić nową licytację.

**Comment by pawelosajda** [comment]
@MartaNowaczyk Wystawiam licytacje na 7 dni po zakończeniu bez sprzedaży mam wystawić taką samą ofertę której zostanie przydzielone nowe id? To będzie równoważne z tym jak by allegro wznawiało ofertę?
Nie zostaną naliczone dodatkowe opłaty i za każdym razem mam przesyłać zdjęcia dobrze rozumiem?

**Comment by MartaNowaczyk** [comment]
Tak, trzeba wystawić nową ofertę z licytacją nawet gdy nie było sprzedaży. Za każdym razem trzeba przesłać wszystkie dane oferty, jak opis, zdjęcia, kategorie itp. jednak w łatwy sposób można je pobrać. Więcej o wystawianiu ofert przez REST API znajdziesz[ w naszym poradniku](https://developer.allegro.pl/sale/#similar-offer). Opłaty powinny być naliczane tak jak wcześniej.

**Comment by michalstaniul** [comment]
Dzień dobry,

Pani Marto, w lutym były takie informacje od jednego z pracowników Allegro:

PawelTaberski commented on 26 Feb
Licytacje możesz wystawić tylko na określony czas przez REST API 3, 5 7 i 10 dni. Pamiętaj, że po jej zakończeniu zawsze możesz ją aktywować przy pomocy metody PUT /sale/offer-publication-commands/{commandId} więcej na ten temat znajdziesz w naszym poradniku.



Teraz słyszymy coś rewolucyjnie innego - przecież jest gigantyczna różnica między wznawianiem tysięcy aukcji jednym PUTem a wysyłaniem ich od nowa (idea licytacji jest też przecież taka, żeby rekurencyjnie wznawiały się o nie co X dni o tej samej porze - a takie wysyłanie aukcji będzie się wiązać z rosnącym przesunięciem wznowienia na coraz późniejszą godzinę). 

Prosimy o spójną informację. Prośba jeszcze o potwierdzenie, co się stanie ze starszymi aukcjami, które mają zapisany fid_30 - czy one już dzisiaj nie zostaną wznowione przez Allegro?

**Comment by pawelosajda** [comment]
W webapi wystarczyło ustawić pole fid_30, w restapi należy:

- Sprawdzać czy oferta jest wznawiana przez allegro i jej nie wznawiać

- Wysyłać każdego dnia dodatkowo kilka tysięcy requestów więcej by wznowić oferty, czy w nowej ofercie można wykorzystać adresy zdjęć z poprzedniej bez ponownego uploadowania zdjęć?

- Dlaczego w formularzu wystawiania oferty jest opcja wznawiania a w api jej nie ma?

**Comment by mirkosmuz** [comment]
Przyłączam się do pytań. Ten problem dotyczy także nas

**Comment by MartaNowaczyk** [comment]
Dziękujemy za argumenty. Przedyskutowaliśmy to dzisiaj i sprawdzimy możliwość dodania opcji wznawiania w REST API. Jeśli taka opcja się pojawi damy znać.

**Comment by michalstaniul** [comment]
A czym można wiedzieć o jakich ramach czasowych tutaj mówimy?

**Comment by mirkosmuz** [comment]
Bardzo nas to cieszy... Jednak w takim razie chcielibyśmy prosić o jakąś konkretną odpowiedź jak najszybciej ponieważ jeśli państwo nie dadzą takiej informacji to musimy szybko pisać moduły które to obsłużą. Jeśli będziemy wiedzieć że na pewno nie zrobicie tego przez najbliższy miesiąc to i tak musimy to zrobić. W naszym przypadku to jest masakra.
Podsumowując:
1. Mamy około 40 000 tysięcy aukcji z licytacją. 
2. Musimy upewnić się że nie będą się wznawiać automatycznie. (wystawione były po staremu i musimy wyłączyć - mam nadzieje że znajdziemy na to sposób bo robić to ręcznie będziemy kilka miesięcy i zrobi się bałagan w ofercie)
3. Każdego dnia o określonej porze trzeba sprawdzić - co się skończyło, czy miało sprzedaż lub czy nie skończyło się przed czasem z powodów administracyjnych.
4. Aukcje które są ok powinny zostać pobrane w pełni.
5. Po pobraniu powinny zostać wystawione z nowymi numerami.

Przy dużej ofercie jest to całkiem spory proces. Jakiekolwiek problemy po drodze wprowadzą narastanie bałaganu w ofercie. 
Dlatego dla nas problem jest spory.

**Comment by ppart** [comment]
Również podczepiam się pod powyższy post, kończy nam się każdego dnia dziesiątki tysięcy aukcji na licytacji. Jeśli w ciągu najbliższych dni nie zostanie wprowadzone wznawianie trzeba pisać kosztowne dodatkowe moduły. Rozumiemy, że nie wszystko zależy od Was, ale możliwość puszczenia sprawy priorytetem na pewno jesteście w stanie. Licytacje na allegro to wciąż bardzo duży procent ofert, zwłaszcza w odzieży.

**Comment by ppart** [comment]
Rozumiem, jednak musimy ustalić jakiś deadline oczekiwania, bo tworzenie tak skomplikowanego modułu (jeśli wznawianie nie zostanie dodane w najbliższych dniach) nie może dłużej czekać. Czy moglibyśmy się umówić na odpowiedź do końca dzisiejszego dnia?

**Comment by MarcinSetr** [comment]
@MartaNowaczyk  Podłączam się do tematu. Dodam jak to wygląda z naszej strony. Posiadamy w ofercie około 60 tysięcy licytacji. Średnio wznawiają się około 10 tysięcy ofert dziennie. Jak można się domyśleć wystawiane są na zewnętrznym oprogramowaniu przez api. Na ten moment "zwykły" użytkownik dodający aukcje bezpośrednio na Allegro ma możliwość zaznaczenia automatycznego wznawiania, my niestety już nie gdyż w api tego nie ma. Proszę nas zrozumieć i wysłuchać. Ten parametr musi być widoczny w api jak każdy inny widoczny podczas wystawiania. Pierwsza tura aukcji wystartowała u nas już 03.06.19r. około 3 tysiące nowych ofert. Proszę o rzetelną informację i profesjonalne podejście do tematu, gdyż jak już ktoś wspominał informacja podana w luty była zupełnie inna.

**Comment by MartaNowaczyk** [comment]
@ppart postaramy się przekazać ustalenia w dniu jutrzejszym

@MarcinSetr rozumiem, od razu podjęliśmy temat, teraz jeszcze czekamy na końcowe ustalenia.  Wszystko dzieje się w odpowiednim i możliwie krótkim czasie.

**Comment by ppart** [comment]
Piszę, aby przypomnieć o temacie, bo zapewne wiele osób oczekuje na odpowiedź aby podjąć konkretne działania.

**Comment by MarcinSetr** [comment]
W dalszym ciągu czekamy na odpowiedź ze strony Allegro.

**Comment by MartaNowaczyk** [comment]
@ppart tak, można wykorzystać dodane wcześniej zdjęcia.

@MarcinSetr przykro mi, ale prawdopodobnie dzisiaj nie będzie jeszcze tej odpowiedzi.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - nie chcieliście słuchać ludzi, to teraz macie - wszystko się sypie !!

**Comment by mirkosmuz** [comment]
Czy coś już wiadomo?

**Comment by MartaNowaczyk** [comment]
W temacie wznawiania konkretne informacje będziemy mogli wam przekazać dopiero w przyszłym tygodniu.

**Comment by ppart** [comment]
Dzień dobry

Jak aktualnie wygląda sprawa? Jakiś update?

**Comment by mirkosmuz** [comment]
Podbijam pytanie. Jest ono dla nas kluczowe.

**Comment by MartaNowaczyk** [comment]
Jak tylko będę miała informacje na pewno dam znać.

**Comment by ppart** [comment]
Z logicznego punktu widzenia, dziwne żeby zachowała Pani tą wiedzę tylko dla siebie. Bardziej interesuje nas czas oczekiwania, aby móc zaplanować sobie projektowanie systemów.  Przepraszam za złośliwość ale jest wysoce niepoważne brak decyzji dot. głównej funkcjonalności w ofertach licytacji, już tydzień po przepięciu się na rest'a - zwłaszcza, że plan aktywacji draftów nie był podzielony na KUP TERAZ  i LICYTACJĘ, wszędzie była mowa o aktywację OFERTY, a teraz karzecie tworzyć nowy draft dla licytacji, która się nie sprzedała...
Ok, będziemy czekać nadal....

**Comment by mirkosmuz** [comment]
Zaczynają pojawiać się różne informacje na ten temat. Proszę udzielić jednoznacznego komunikatu z podaniem dat.

**Comment by MartaNowaczyk** [comment]
Wstępnie prace mamy zaplanowane na najbliższe dwa tygodnie, ale jest to zależne od wielu czynników, więc trzeba mieć na uwadze, że termin może się wydłużyć. Będę was informować, gdyby coś się zmieniło.

**Comment by qls-api** [comment]
Mija prawie 2 tygodnie,  czy mamy jakieś nowe informacje ?

**Comment by MartaNowaczyk** [comment]
Tak,  sprawa jest już na ukończeniu. Jeśli nie wyjdą jakieś problemy po drodze, to przyszły tydzień jest realny.
