### ISSUE TITLE
Jak zmienić status zamówienia przez api

### ISSUE THREAD

**Issue by wolodzkom** [allegro/allegro-api#1744]
W dokumentacji nie mogę znaleźć informacji w jaki sposób za pomocą api zmienić status zamówienia na wysłany. Czy można to zmienić przez api, czy zmienia się to automatycznie np. po dodaniu numerów paczek?
Chodzi o funkcję dostępną w lokalizacji:
Moja sprzedaż → Zamówienia → lista zamówień → opcje → oznacz jako wysłane

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości w tej chwili przez REST. Zamówienia, które możesz pobrać przez REST pokazują działania tylko ze strony kupującego. Jeśli chodzi o zasoby do nadawania statusów zamówień, to pracujemy już nad pewnym rozwiązaniem. Jak tylko będą gotowe na pewno go udostępnimy. Najpierw jednak pojawią się w samym allegro.

**Comment by Zbigniew-L** [comment]
Na początek wystarczyłaby nam prosta metoda do zmiany na 'wysłane' - dzięki temu na liście zamówień pozostawałyby tylko te, z którymi trzeba coś zrobić. W momencie gdy obsługujemy setki zamówień dziennie zmiana statusu na wysłanie na każdym zamówieniu to po prostu bezsensowna robota, nasz system w backoffice wie które zamówienia są wysłane i mógłby odpowiednio zmieniać status przez API. 

Prosimy o szybsze zrobienie dla nas tak małej poprawki w API, a potem sobie możecie obmyślać inne rozwiązania... :)

**Comment by MartaNowaczyk** [comment]
Działania będziemy prowadzić kompleksowo, dlatego trzeba będzie poczekać na takie możliwości. 
O tym jak, jakie i kiedy wprowadzimy takie zmiany poinformujemy w oddzielnym komunikacie.

**Comment by LukaszCierocki** [comment]
@MartaNowaczyk, a wiadomo mniej więcej kiedy będzie taka funkcja dostępna?

**Comment by MartaNowaczyk** [comment]
@LukaszCierocki Nie, na ten moment nie znamy nawet przybliżonego terminu.

**Comment by Zbigniew-L** [comment]
Mogę prosić o potwierdzenie, że w dalszym ciągu nie ma żadnej metody RestAPI, która umożliwi zmianę statusu zamówienia na 'Wysłane'? Nasi klienci ciągle nas pytają dlaczego nie możemy zmienić dla nich statusu zamówień w Allegro...

**Comment by PrzemyslawLukanowski** [comment]
@Zbigniew-L Na tę chwilę nie ma takiego zasobu. Sugestia została już przekazana do odpowiedniego zespołu. Jeśli zdecydujemy się na jej wdrożenie, poinformujemy w odpowiednim komunikacie.

**Comment by Zbigniew-L** [comment]
Szanowni Państwo, czy nie zapomnieliście o metodzie na którą czekają klienci Allegro? Proszę uwierzyć, że przy dużej liczbie wysyłek ręczna zmiana statusów jest bardzo uciążliwa, prosimy o prostą metodę umożliwiającą chociaż zmianę na 'wysłane'...

**Comment by PrzemyslawLukanowski** [comment]
@Zbigniew-L Nie zapomnieliśmy, oznaczenie zamówienia jako “wysłane” wciąż jest jedną z sugestii do wdrożenia w REST API.

**Comment by rtarnowski** [comment]
@PrzemyslawLukanowski  czy coś już wiadomo w temacie?  Czy w REST API będzie opcja oznaczenia zamówienia jako “wysłane”?

**Comment by PrzemyslawLukanowski** [comment]
@rtarnowski Pracujemy nad tym, w ciągu najbliższych kilku miesięcy powinna pojawić się taka funkcjonalność.

**Comment by Zbigniew-L** [comment]
prosimy nie zamykać wątku z powodu braku odpowiedzi - ta funkcjonalność jest potrzebna naszym klientom!

**Comment by teddyjm** [comment]
Też się podpinam, podobnie jak u kolegów nasi klienci cały czas pytają o tę funkcję.

**Comment by PawelTaberski** [comment]
Tak jak pisał Przemek pracujemy nad wdrożeniem tej funkcjonalności, jeszcze nie znamy dokładnej daty wdrożenia.

**Comment by Zbigniew-L** [comment]
Tradycyjnie jak co miesiąc kiedy wątek ma być zamknięty przypominam się, że nasi klienci czekają na tą wydaje się niezbyt skomplikowaną funkcjonalność więc prosimy o update?

**Comment by PatrykBocian** [comment]
@Zbigniew-L  Prace nad tą funkcjonalnością wciąż trwają, gdy tylko będziemy gotowi na wdrożenie takiej zmiany poinformujemy o tym w odpowiednim komunikacie.

**Comment by Zbigniew-L** [comment]
ciągle czekamy na tą funkcjonalność, prosimy nie zamykać wątku

**Comment by Zbigniew-L** [comment]
ciągle czekamy na tą funkcjonalność, prosimy nie zamykać wątku

**Comment by PrzemyslawLukanowski** [comment]
@Zbigniew-L Zapraszam do wątku #2775, znajdziesz tam niezbędne informacje na temat zmiany statusu realizacji zamówienia.
