### ISSUE TITLE
GET sale/offers/{id} - NOT_FOUND a istnieje w sale/offers 

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#1745]
Witam,

Mam problem z zasobem REST produkcja

Pobieram listę aukcji zakończonych poprzez GET sale/offers?publication.status=ENDED

Następnie pobieram szczegóły aukcji

GET sale/offers/7558285141

I otrzymuję

`      +"code": "NOT_FOUND"
      +"message": "Not Found"
      +"details": null
      +"path": "/sale/offers/7558285141"
      +"userMessage": null
`

W zasobie OfferListingDtoV1 nie mam żadnych informacji, że nie będę mógł pobrać szczegółów oferty.

Dotyczy to różnych kont Allegro i wielu ofert np. 7558285141, 7558281695, 7391195414

**Comment by MartaNowaczyk** [comment]
Oferty można pobrać 60 dni po jej zakończeniu. Te które podajesz są starsze i nie powinny się tam pojawić. To błąd po naszej stronie. Poprawimy to, by takie oferty nie były zwracane.
