### ISSUE TITLE
We can not publish on sandbox

### ISSUE THREAD

**Issue by supportbb** [allegro/allegro-api#1748]
Hello,

We are trying to publish some offer but we can not do it.

We have tried from webinterface https://allegro.pl.allegrosandbox.pl/offer/ and by API.

We got from the api this message: 

` Client error: `POST https://api.allegro.pl.allegrosandbox.pl/sale/offers` resulted in a `415 Unsupported Media Type
  ` response:
  {"errors":[{"code":"NotSupportedException","message":"Unsupported content type. Please check 'Content-Type' request
   head (truncated...)
`

From web interface we got this message:

![Formularz wystawiania](https://user-images.githubusercontent.com/51234275/58810950-356db080-861f-11e9-8aa6-11f90ddd312b.png)

**Comment by supportbb** [comment]
Now we got 405 error

{
    "errors": [
        {
            "code": "NotAllowedException",
            "message": "The HTTP method is not allowed",
            "details": null,
            "path": null,
            "userMessage": "An error occurred"
        }
    ]
}

**Comment by MartaNowaczyk** [comment]
Send me a login from the sandbox and a full request and response with this error.

**Comment by supportbb** [comment]
> Send me a login from the sandbox and a full request and response with this error.

The issue is that we can not publish in sandbox by grafic interface. We have block the sell. See the screenshot

**Comment by supportbb** [comment]
We are trying with POSTMAN this request:

POST https://api.allegro.pl.allegrosandbox.pl/account/additional-emails/

We send this data in the body of the request:
`{
"email": "string"
}`

We got 405 method not allowed:

`{
    "errors": [
        {
            "code": "NotAllowedException",
            "message": "The HTTP method is not allowed",
            "details": null,
            "path": null,
            "userMessage": "An error occurred"
        }
    ]
}`

**Comment by MartaNowaczyk** [comment]
Try without a sign '/ ' at the end of the path:

`https://api.allegro.pl.allegrosandbox.pl/account/additional-emails`

**Comment by supportbb** [comment]
> Try without a sign '/ ' at the end of the path:
> 
> `https://api.allegro.pl.allegrosandbox.pl/account/additional-emails`

Where can we get a basic model of json to the request https://api.allegro.pl.allegrosandbox.pl/sale/offers

**Comment by supportbb** [comment]
We already have the sandbox account active because we have been able to publish an offer from the graphical interface.

But we try to publish an offer, get the list of offers or a certain offer and we always get error 403 forbidden.

https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206383765

**Comment by gogi** [comment]
@supportbb I've noticed some issues with your request. Maybe that's the problem?
- you shouldn't pass `'id'` when creating an offer - it will be given to you in api response
- i think you can pass `'product'` only for selected categories
- `'minimalPrice' `and `'startingPrice'` are only available for `'AUCTION'` format - for `BUY_NOW` both values should be empty
- you shouldn't send `'validation' `and `'validatedAt'` params - they will be returned by api response to notice you about validation errors that concern your new offer
- do not send `'updatedAt'` - it will also be set automatically and returned by api response
- and maybe set `'available'` inside `'stock'` parameter as number greater than 0

Hope it helps. Cheers

**Comment by MartaNowaczyk** [comment]
@supportbb 403 HTTP status - The user is authenticated, but has no rights to a particular resource - You must be logged as a seller account.  

Please find more details regarding the API integration on our [website](https://developer.allegro.pl/en/about/). Documentation you can find [here](https://developer.allegro.pl/en/documentation/).

I suggest to read the following articles to start working on the integration:

- [Getting started with the REST API](https://developer.allegro.pl/en/getting_started/)
- [Basic informations](https://developer.allegro.pl/en/about/)
- [HTTP status codes](https://developer.allegro.pl/en/about/#http-statuses)
- [Authentication and authorization](https://developer.allegro.pl/en/auth/)
- [Listing offers](https://developer.allegro.pl/en/sale/)
- [List of offers](How to process list of offers via REST API)

**Comment by supportbb** [comment]
> @supportbb 403 HTTP status - The user is authenticated, but has no rights to a particular resource - You must be logged as a seller account.
> 
> Please find more details regarding the API integration on our [website](https://developer.allegro.pl/en/about/). Documentation you can find [here](https://developer.allegro.pl/en/documentation/).
> 
> I suggest to read the following articles to start working on the integration:
> 
> * [Getting started with the REST API](https://developer.allegro.pl/en/getting_started/)
> * [Basic informations](https://developer.allegro.pl/en/about/)
> * [HTTP status codes](https://developer.allegro.pl/en/about/#http-statuses)
> * [Authentication and authorization](https://developer.allegro.pl/en/auth/)
> * [Listing offers](https://developer.allegro.pl/en/sale/)
> * [List of offers](https://developer.allegro.pl/en/my_offers/)

We have seller account and we can create offers from allegro sandbox panel but we can not create it by the API

**Comment by supportbb** [comment]
> @supportbb I've noticed some issues with your request. Maybe that's the problem?
> 
> * you shouldn't pass `'id'` when creating an offer - it will be given to you in api response
> * i think you can pass `'product'` only for selected categories
> * `'minimalPrice' `and `'startingPrice'` are only available for `AUCTION` format - for `BUY_NOW` both values should be empty
> * you shouldn't send `'validation' `and `'validatedAt'` params - they will be returned by api response to notice you about validation errors that concern your new offer
> * do not send `'updatedAt'` - it will also be set automatically and returned by api response
> * and maybe set `'available'` inside `'stock'` parameter as number greater than 0
> 
> Hope it helps. Cheers

I can create an offer from my panel but i can not get it by API (With postman)

GET /sale/offers

or 

GET /sale/offers/{offer_id}

I get 403 with both request

**Comment by MartaNowaczyk** [comment]
403 HTTP status  - The user is authenticated, but has no rights to a particular resource.
Check the authorization data. Maybe you're using data from production or data to another account.

**Comment by supportbb** [comment]
> 403 HTTP status - The user is authenticated, but has no rights to a particular resource.
> Check the authorization data. Maybe you're using data from production or data to another account.

@MartaNowaczyk we get our credentials to generate the token from this url https://apps.developer.allegro.pl.allegrosandbox.pl/

**Comment by MartaNowaczyk** [comment]
I need more information. Could You send me file with request and response with your error call by [contact form](https://allegro.pl/pomoc/kontakt). Add issue number from GitHub #1748 in that message.

**Comment by supportbb** [comment]
> issue number from GitHub #1748

We have sent the message. Thanks

**Comment by MartaNowaczyk** [comment]
Thank you for your message. Your token has no user context. Use Device or Code flow to autorization. You can decode token by https://jwt.io/
