### ISSUE TITLE
Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#175]
Wysyłam request do https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/{guid} w celu aktywacji oferty i dostaję w odpowiedzi ServiceUnavailableException. Wczoraj miałem tak samo. Czy rzeczywiście serwis jest niedostępny (w co wątpię bo inne żądania przechodzą) czy mam źle skonstruowane żądanie?

**Comment by kaminiak23** [comment]
przepraszam :), ja w webapi robię, resta jeszcze nie patrzyłem to nie pomogę

**Comment by MaciejPotepa** [comment]
@adampajak Podaj proszę pełną treść requesta i response. 

W pozostałych zapytaniach wszystko na środowisku testowym działa dla Ciebie prawidłowo?

**Comment by adampajak** [comment]
Tak, pozostałe są ok - np. tworzenie i uzupełnianie draftu.
W załączeniu sekwencja 3 kroków które wykonuję.
[Kroki.txt](https://github.com/allegro/allegro-api/files/1959941/Kroki.txt)

**Comment by MaciejPotepa** [comment]
Dzięki za podesłanie i kontakt z nami. Musimy namierzyć i rozwiązać problem. Proszę o cierpliwość.

**Comment by MaciejPotepa** [comment]
@adampajak problem nie powinien już występować.

**Comment by adampajak** [comment]
Jest ok
