### ISSUE TITLE
GET /order/line-item-id-mappings?lineItemId={uuid} zwraca 404 dla zamówień po 2 czerwca

### ISSUE THREAD

**Issue by karolus888** [allegro/allegro-api#1750]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przykład:
Request
https://api.allegro.pl/order/line-item-id-mappings?lineItemId=1a5efab3-863d-11e9-97a7-578f61f8f2ef
Response:
404 Not Found
{
"errors": [
  {
"code": "ERROR",
"message": "An error has occurred",
"details": null,
"path": null,
"userMessage": null
}
],
}

Jak w temacie, dla nowych zamówień (po 2 czerwca, choć nie wiem czy to reguła) zasób /order/line-item-id-mappings zwraca 404 Not Found. Proszę o pilne zajęcie się problemem, niestety musimy używać tego zasobu, żeby przemapować się na stare TransactionId na potrzeby API Inpost.

**Comment by MartaNowaczyk** [comment]
Na pewno podajecie poprawną wartość dla lineItemId? Sprawdzam i nie mam takich problemów.

**Comment by karolus888** [comment]
Mea culpa, przekazywałem id z checkout form zamiast line item...
