### ISSUE TITLE
Spadła wydajność metody do pobierania nadchodzących opłat [GET pricing/offer-quotes : Błąd 504]

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1752]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Wzrosła liczba 504'ek z metody nadchodzących opłat z GET pricing/offer-quotes.
Pobieram nadchodzące opłaty dla 200k ofert, w paczkach po 20 sztuk. Dziś, na 10k wywołań błąd wystąpił około 500 razy. (Do wczoraj to było po 5-10 błędów.)

`[2019-06-04 08:08:28] local.CRITICAL: Allegro\AllegroClientOffersQuotes::getOffersQuotesPage:74:Wywołanie allegro https://api.allegro.pl/pricing/offer-quotes?offer.id=xxxx zakonczyło się błędem. HTTP_CODE:504  
[2019-06-04 08:08:28] local.CRITICAL: AllegroClientOffersQuotes::getOffersQuotesPage:77Wystąpił błąd podczas wywoływania https://api.allegro.pl/pricing/offer-quotes?offer.id=xxx komunikat allegro:ServiceTimeoutException - An error occurred - Execution of the request timed-out. Try again.`

**Comment by MartaNowaczyk** [comment]
Sprawdzamy problem.

**Comment by kfijalko** [comment]
Pani Marto @MartaNowaczyk 
Statystyka z dzisiejszego poranka:

GET /offers/listing = HTTP_504 i 503 x 20 sztuk 
GET /sale/offers = HTTP_504 x 1 sztuka
GET /pricing/offer-quotes = HTTP_504 x 30sztuk

**Comment by MartaNowaczyk** [comment]
@kfijalko przekazałam twoje statystyki  do odpowiednich zespołów

**Comment by kfijalko** [comment]
@MartaNowaczyk 
Metody jak wyżej.
Dziś: około 100 błędów 502, 503 i 504.
Pojawił się też nowy komunikat (już kiedyś go zgłaszałem):
Metoda GET https://api.allegro.pl/pricing/offer-quotes?offer.id=xx 
"Unable to communicate securely with peer: requested domain name does not match the server's certificate."

**Comment by MartaNowaczyk** [comment]
@kfijalko dodałam tę informację do przeanalizowania

**Comment by kfijalko** [comment]
Pani Marto @MartaNowaczyk 
Dziś 503 i 504 idą w tysiące.
Chyba serwery Wam się przegrzały ;)

**Comment by MartaNowaczyk** [comment]
@kfijalko jaki endpoint i jaki timestamp?

**Comment by kfijalko** [comment]
Wczoraj zaczęło się o [2019-06-25 07:35:31] i trwało cały dzień do 22:00.
Endpointy:
https://api.allegro.pl/sale/offers? - większość błędów
https://api.allegro.pl/pricing/offer-quotes?
https://api.allegro.pl/offers/listing?

Dziś jest kilka od 7:00.

**Comment by MartaNowaczyk** [comment]
@kfijalko jeśli chodzi o https://api.allegro.pl/sale/offers to wczoraj rzeczywiście był problem z tym endpointem. Dziś jednak wszystko powinno być w normie. Rozumiem, że dla pozostałych to pojedyncze przypadki, czyli mieszczą się w normie dla tego typu zachowania.

**Comment by kfijalko** [comment]
Pani Marto @MartaNowaczyk 
Wczoraj 2500 błędów 504 na https://api.allegro.pl/pricing/offer-quotes
Już czas żebyście ją poprawili.

**Comment by MartaNowaczyk** [comment]
> Wczoraj 2500 błędów 504 na https://api.allegro.pl/pricing/offer-quotes 
Już czas żebyście ją poprawili.

Pracujemy nad tym.
