### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#1753]
Witam,
Czy mógłbym prosić o aktywację konta "ania" wykonaliśmy wszystkie kroki, ale wciąż oczekuje na weryfikację.

Pozdrawiam
Marcin Butlak

**Comment by PawelTaberski** [comment]
Twoje konto powinno już być w pełni aktywne.

**Comment by makerlabs** [comment]
Dzięki
