### ISSUE TITLE
INTERNAL_SERVER_ERROR w sale/offers

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#1754]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Podczas dodawanie towaru dostaję** 
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal Server Error","details":null,"path":"/sale/offers","userMessage":null}]}'

**Comment by MartaNowaczyk** [comment]
Obecnie mamy problemy z wystawianiem i edycją ofert. Pracujemy nad poprawą sytuacji.
