### ISSUE TITLE
Awaria?

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1755]
Macie jakąś awarię? Dla każdej oferty dostaję internal server error.

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal Server Error","details":null,"path":"/sale/offers/XXXXX14917","userMessage":null}]}

**Comment by MartaNowaczyk** [comment]
Obecnie mamy problemy z wystawianiem i edycją ofert. Pracujemy nad poprawą sytuacji.
