### ISSUE TITLE
Różnice w zapisie adresu e-mail dla metod doGetPostBuyData oraz doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#1758]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Problem dotyczy zapisu maskowanych maili przy pobieraniu zakupów metodą doGetPostBuyData - w response otrzymuję w polu user-email adres e-mail tylko do plusa (np. ea011aea11@allegromail.pl), natomiast zarówno w metodzie doGetPostBuyFormsDataForSellers jak i przez panel Allegro prawidłowy adres e-mail to ea011aea11+11111ea11@allegromail.pl -> wszystko od plusa w prawo jest obcięte. 

Ponieważ nasz skrypt zapisywał właśnie pole z metody doGetPostBuyData, większość maili klientów jest nieprawidłowa - przy próbie kontaktu z klientem dostajemy w zwrotce maila z informacją, że adres mailowy jest nieprawidłowy.

Pytanie czy taki mail świadomie zwracacie taki obcięty czy to przypadek? Dalej, mamy łatać to u nas czy poprawicie pole?

**Comment by MartaNowaczyk** [comment]
@magik092 Sprawdzimy opisaną sytuację. Dam znać.

**Comment by neldh** [comment]
"Ponieważ nasz skrypt zapisywał właśnie pole z metody doGetPostBuyData, większość maili klientów jest nieprawidłowa - przy próbie kontaktu z klientem dostajemy w zwrotce maila z informacją, że adres mailowy jest nieprawidłowy."

Jak to nieprawidłowy? adres bez tego co po + jest jak najbardziej prawidłowy, więc przyczyna musi leżeć gdzie indziej. To co po znaku + to tylko tag określający transakcję. Nie powinno być żadnych problemow z kontaktowaniem się na adres bez plusa.

**Comment by magik092** [comment]
@neldh skoro przy wysyłaniu wiadomości otrzymujemy zwrotkę o następującej treści

> Wiadomość wysłana na adres: ea011aea11@allegromail.pl nie mogła zostać dostarczona.
> 
> Wystąpił techniczny problem ze skrzynką pocztową odbiorcy Twojej wiadomości. Prosimy spróbować ponownie w późniejszym terminie.

oznacza to, że nie jest do końca prawidłowy. Jeszcze pal licho jeśli by to był jeden taki przypadek na dzień, ale jest ich cała masa ...

PS: Poniżej kilka dodatkowych szczegółów ze zwrotki:

> Temat: Delivery Status Notification (Failure)
> Nadawca: "Mail Delivery System" <MAILER-DAEMON@smtpfarm5.allegro.pl>
> Data: 2019-06-03, 17:40
> Adresat: ea011aea11@allegromail.pl
> 
> The following message to <[adres e-mail]> was undeliverable.
> The reason for the problem:
> 5.1.0 - Unknown address error 550-'"[adres e-mail]": Podane konto jest zablokowane administracyjnie lub nieaktywne / This account is disabled or not yet active (#5.1.1)'
> 
> 
> Reporting-MTA: dns; smtpfarm5.allegro.pl
> 
> Final-Recipient: rfc822;<email>
> Action: failed
> Status: 5.0.0 (permanent failure)
> Remote-MTA: dns; [212.77.101.4]
> Diagnostic-Code: smtp;
>  5.1.0 - Unknown address error 550-'"<email>": Podane konto jest zablokowane
>  administracyjnie lub nieaktywne / This account is disabled or not yet active
>  (#5.1.1)' (delivery attempts: 0)

**Comment by MartaNowaczyk** [comment]
@magic092 potwierdzam to co pisze neldh. Poza tym sprawdziłam i dla metody doGetPostBuyData zawsze będzie zwracany mail bez części transakcyjnej, bo nie ma w nim kontekstu zamówienia/transakcji. To w szczególności oznacza, że jeżeli wykorzystujesz ten endpoint do pobierania danych po sprzedaży, to musisz się przepiąć na inny.

Jeśli chodzi o zwrotkę, to potrzebuję prawidłowego maila do weryfikacji, a nie wypełniacza. Takie dane możesz przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1758

**Comment by magik092** [comment]
@MartaNowaczyk w sumie takie info mi wystarczy, trzeba będzie przerobić skrypt. Temat do zamknięcia
