### ISSUE TITLE
Sposób obliczania kosztów dostawy przez restAPI

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1759]
Gdzie dokładnie można przez API rest  zarządzać tymi danymi ? 
![image](https://user-images.githubusercontent.com/1530496/58875868-ec743580-86cc-11e9-8d41-64e096dbe4b3.png)

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości przez API. Mamy to w planach, ale terminu dokładnego nie mamy ustalonego.
