### ISSUE TITLE
Przekazanie dodatkowych danych do przekierowania przy autoryzacji

### ISSUE THREAD

**Issue by gustawdaniel** [allegro/allegro-api#176]
Mamy następujący przepływ danych:

1) Na froncie tworzymy adres url na który użytkownik ma przejść, żeby się zalogować i autoryzować aplikację

2) Po zalogowaniu i kliknięciu "zgadzam się" użytkownik zostaje przekierowany na adres backendowy do którego trafia wysłany w url code - 10 sekundowy kod do uzyskania tokena.

Problem polega na tym, że w żądaniu wysyłanym przez allegro wysyłany jest tylko ten `code` i nic więcej. Później kiedy uzyskuję ten token to mogę go używać, ale nie wiem jak połączyć go z informacją, który użytkownik mojej aplikacji wykonał integrację z Allegro.

Frontend i Backend stroją na innych domenach, więc cookie odpada.

Google rozwiązuje ten problem przez dodatnie parametru `state`

> https://stackoverflow.com/questions/7722062/google-oauth2-redirect-uri-with-several-parameters

Chciał bym, żeby przycisk z frontu mógł zawierać informację o tym który użytkownik jest zalogowany i tą informację przekazać obok `code` przy przekierowaniu.

Jak to zrobić w Allegro?

Co nie działa (zakładamy, że `http://example.com/allegro` to adres przekierowania):

+ przekazywanie przez dodanie parametru do ścieżki `http://example.com/allegro/:userId`
+ przekazywanie przez dodanie parametru do GET `http://example.com/allegro?userId=XXX`

W obu przypadkach mamy błąd:

```
{
   status: "error",
   message: "Allegro refused request",
   data: {
      error: "invalid_grant",
      error_description: "Redirect URI mismatch."
   }
}
```

+ Dodanie `state` tak jak w Google

Daje błąd

```
408 Request Time-out
Your browser didn't send a complete request in time.
```

**Comment by kormichu** [comment]
U mnie opcja z dodaniem dodatkowego parametru do adresu powrotu jak najbardziej działa:
http://example.com/allegro/:userId

Być może aplikacja którą zarejestrowałeś: https://apps.developer.allegro.pl/ na inny protokół niż ten który chcesz przekazać (https / http). Sam miałem z tym problem i musiałem rejestrować na nowo aplikacje dla https.

**Comment by gustawdaniel** [comment]
Rzeczywiście działa. Pomógł reset komputera. Nie udało mi się ustalić co był nie tak wcześniej...
