### ISSUE TITLE
Problem z zasobem REST API /order/checkout-form

### ISSUE THREAD

**Issue by mm01984564** [allegro/allegro-api#1760]
Witam,
czy planujecie dodać do zasobu GET /order/checkout-forms możliwość filtrowania po dacie zakończenia płatności? 

Pobierając zamówienia z filtrem status=READY_FOR_PROCESSING i lineItems.boughtAt.gte 
nie pobiera mi zamówień, które zostały zakupione przed datą z filtra a płatność została zakończona po dacie z filtra.

**Comment by neldh** [comment]
3 raz pojawia się ta prośba tutaj. Dokładnie te same argumenty. Czy moglibyście w Allegro podjąć decyzję w tej sprawie jak najszybciej?

**Comment by MartaNowaczyk** [comment]
Tak jak już pisałam, mamy ten temat na uwadze. Sprawdzamy różne możliwości. Problematyczne są zamówienia np. za pobraniem, gdzie daty płatności po prostu nie ma. Sprawdzamy jak możemy mimo to zwrócić wam odpowiednie dane, dlatego proszę o jeszcze trochę cierpliwości. Jak tylko będziemy mogli wam przekazać informacje w tej sprawie, na pewno to zrobimy.
