### ISSUE TITLE
https://upload.allegro.pl/sale/images

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#1761]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas dodawania zdjęć w postaci binarnej, co jakiś czas wyrzuca błąd. Ponowna próba przesłania tego samego kończy się powodzeniem. Raz można dodać 20 zdjęć, innym razem 35, losowo wyświetla te błędy.
CURLOPT_HTTPHEADER, array('Authorization: Bearer ' . $token, 'accept: application/vnd.allegro.public.v1+json', 'content-type: image/jpeg', 'accept-language: pl-PL'));

errors' => 
    array (size=1)
      0 => 
        array (size=5)
          'code' => string 'VALIDATION_ERROR' (length=16)
          'message' => string 'Invalid image URL. Image must be present on allegro server.' (length=59)
          'details' => string 'Invalid value: false' (length=20)
          'path' => string 'images[1].url' (length=13)
          'userMessage' => string 'Invalid image URL. Image must be present on allegro server.' (length=59)

"https://upload.allegro.pl/sale/images" zwraca wartość null

**Comment by barthoos** [comment]
Wujek dobra rada radzi: losowo zwracane bledy przez API allegro uznaj za pewnik i projektuj aplikacje majac to na wzgledzie. Zakladaj ze wszystko moze nie wyjsc, to sie nie rozczarujesz.

**Comment by MartaNowaczyk** [comment]
@KJtTGHAK podaj proszę trace-id dla zapytania z błędem

**Comment by SoftSolid** [comment]
Przepraszam za podpięcie się do wątku.
W środowisku testowym jest taki sam adres do serwera zdjęć ? https://upload.allegro.pl czy inny ?

**Comment by MartaNowaczyk** [comment]
@SoftSolid dla sandboxa użyj https://upload.allegro.pl.allegrosandbox.pl
