### ISSUE TITLE
Brak EAN w response z /sale/offers/{offerId}

### ISSUE THREAD

**Issue by hryniak** [allegro/allegro-api#1762]
Witam
W specyfikacji response dla metody /sale/offers/{offerId} jest pole
ean	string <= 18 characters.
Ja jednak nie dostaję tego pola w response.
Dodam, że autoryzuję się jako właściciel oferty.
Czy coś robię nie tak ?

Poniżej mój request i response jaki otrzymuję:

request:
curl.exe -X GET "https://api.allegro.pl/sale/offers?offer.id=7535344939"  
 -H "Accept: application/vnd.allegro.public.v1+json" 
 -H "content-type: application/vnd.allegro.public.v1+json" 
 -H "Authorization: Bearer  xxx" 

response:

{"offers":[
 {"id":"7535344939",
  "name":"LAMPA NAFTOWA LAMPION LATARENKA TURYSTYCZNA 250mm",
  "category":{"id":"15961"},
  "primaryImage":{"url":"https://4.allegroimg.com/original/03647c/b3970f6740faa2d310cac7d60234"},
  "sellingMode":{"format":"BUY_NOW",
                 "price":{"amount":"40.0","currency":"PLN"},
                 "minimalPrice":null,
                 "startingPrice":null
                 },
  "saleInfo":{"currentPrice":null,
              "biddersCount":0},
              "stats":{"watchersCount":1,
                       "visitsCount":17},
                       "stock":{"available":998,
                                "sold":1},
              "publication":{"status":"ACTIVE",
                             "startingAt":null,
                             "startedAt":"2018-08-29T07:08:57Z",
                             "endingAt":null,
                             "endedAt":null},
              "afterSalesServices":{"warranty":{"id":"e0e5fe29-1cee-4415-a8cb-6d5f9cb24633"},
              "returnPolicy":{"id":"7716b8a9-ab67-41d2-bad1-faff7192229d"},
              "impliedWarranty":{"id":"57dbb936-b363-425b-af6b-b60cd70be230"}},
              "additionalServices":null,
              "external":null}],
  "count":1,
  "totalCount":1}

**Comment by MartaNowaczyk** [comment]
jeśli masz "external":null to znaczy, że nie dodałeś takiego pola do oferty.

**Comment by hryniak** [comment]
Ale pobierając dane tej oferty 1 czerwca jeszcze metodą doGetItemFields dostałem w odpowiedzi wartość "8585023390458" dla pola fid = 337 (czyli wg specyfikacji pól Europejski Kod Towarowy)

**Comment by MartaNowaczyk** [comment]
@hryniak przepraszam piszę o external.id a ty piszesz o kodzie EAN. Sprawdziłam i dla tej oferty zwracane jest pole "ean": "8585023390458".

**Comment by sikorag** [comment]
Zrobiłeś zapytanie:
"https://api.allegro.pl/sale/offers?offer.id=7535344939"

A pytasz o "https://api.allegro.pl/sale/offers/7535344939"

To pierwsze to zapytanie na listę ofert, wyfiltrowane po jej id, które zwraca mniej szczegółów oferty niż zapytanie o pojedynczą ofertę (to drugie)
