### ISSUE TITLE
Niemożliwość pobrania informacji o produkcie po ID

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#1764]
Czy jest jakiś problem z pobieraniem danych o produktach, znając ich ID? Przykładowo: `GET /sale/products/ffc7d80c-251d-4c4e-b965-f9e1a2723620` zwraca mi:

```
  array(1) {
    [0]=>
    object(stdClass)#24 (5) {
      ["code"]=>
      string(28) "ConstraintViolationException"
      ["message"]=>
      string(21) "An error has occurred"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(17) "Invalid category."
    }
```

Mam tak w przypadku 1880 produktów o które pytam. Mogę podesłać listę.

**Comment by MartaNowaczyk** [comment]
Potwierdzam, również dostaję taki błąd dla podanego ID produktu. Sprawę zgłosiłam do odpowiedniego zespołu.

**Comment by MartaNowaczyk** [comment]
Pracujemy nad rozwiązaniem problemu.
