### ISSUE TITLE
Parametry dla kategorii

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#1765]
Witam,

Czy moglibyście podać identyfikatory kategorii na produkcji i sandboxie gdzie parametry są typu zakresowego (range) zarówno dla float jak i integer. Najlepiej jakbyście podali przykłady kategorii dla wszystkich wariantów parametrów, abyśmy mogli sprawdzić czy poprawnie wdrożyliśmy funkcjonalność

**Comment by alekskuc** [comment]
Cześć, kategorie PROD i TEST pobierałem kiedyś przez noc z tego samego powodu. Stan na 2019-05-16.

Po rozpakowaniu PROD json 305MB, TEST json 205 MB.

[categoriesAllegroRESTjson.zip](https://github.com/allegro/allegro-api/files/3252927/categoriesAllegroRESTjson.zip)
