### ISSUE TITLE
W jaki sposób można pobrać login sprzedawcy?

### ISSUE THREAD

**Issue by alikoli** [allegro/allegro-api#1767]
Autoryzacja jest poprzez device flow. Użytkownik chce dodać kilka swoich kont allegro. Generuje linki do potwierdzenia każdego z nich. SellerId można wyciągnąć z tokena, jak wyciągnąć login?

**Comment by mindc** [comment]
@alikoli 
Bezpośrednio się nie da, ja robię to tak:
- otwieram link `https://allegro.pl/uzytkownik/{SellerId}/oceny`
- login mamy w `span.user-info__name`

**Comment by alikoli** [comment]
> @alikoli
> Bezpośrednio się nie da, ja robię to tak:
> 
> * otwieram link `https://allegro.pl/uzytkownik/{SellerId}/oceny`
> * login mamy w `span.user-info__name`

Dzięki, o to chodziło!
