### ISSUE TITLE
Problemy z wystawianiem pobranych aukcji.

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#1768]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam mam problem z tworzeniem nowych aukcji, mianowicie pobrałem z allegro za pomocą metody GET sale/offers/auctionId/ wszystkie dane dotyczące oferty i zapisałem je do bazy.
Następnie z danych w bazie chcę utworzyć nowe aukcję więc za pomocą metody POST sale/offers/ przesyłam tylko tytuł oferty i oczekuje na utworzenie, w informacji zwrotnej otrzymuje dane że draft został utworzony zawiera tytuł oferty oraz ID, w tym momencie uzupełniam pozostałe dane tymi z bazy danych jednak co którąś aukcję przy próbie wysłania danych do allegro metodą PUT sale/offers/auctionId otrzymuję następujące komunikat:
file_get_contents(https://api.allegro.pl/sale/offers): failed to open stream: HTTP request failed! HTTP/1.1 422 Unprocessable Entity

Walidacja danych jest prawidłowa bo są one z aukcji które były wystawione i aktywne w momencie zapisywania ich do bazy

**Comment by mindc** [comment]
@Troian1337 
Sprawdź wszystkie pola. czy rzeczywiście masz komplet danych bo API zwraca wtedy lakoniczne komunikaty błędów (422 - zero informacji). W niektórych ofertach, zwłaszcza starszych, nie są zwracane wszystkie pola, np.: `location`, `afterSalesServices` albo `shippingRates`

**Comment by Troian1337** [comment]
@mindc 
Sprawdzałem, wszystkie dane są prawidłowe po kolei każdy element, afterSalesServices oraz shippingRates mam na sztywno podawane a nie z aukcji. Co gorsza nie otrzymuje komunikatu błędu, bo jak nie podałem jakichś danych to z metody PUT sale/offers/auctionId otrzymywałem w zwrocie informację czego brakuje, a tutaj nic brak jakichkolwiek informacji.

**Comment by MartaNowaczyk** [comment]
@Troian1337 w takim razie podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1768. Sprawdzę w czym jest problem.

**Comment by Troian1337** [comment]
@MartaNowaczyk Znalazłem przyczynę problemu, leży to po stronie REST, dane jakie pobrało mi, nie zgadzały się ze stanem aukcji. Pobrało mi jak by starsze wersję niektórych aukcji a zwróciłem na to uwagę bo copyright jaki mi pobrał z szablonu były inne niż te na zakończonych aukcjach (starsza wersja szablonu).

**Comment by MartaNowaczyk** [comment]
@Troian1337 tym bardziej podeślij proszę dane do weryfikacji, chociaż numer takiej oferty.
