### ISSUE TITLE
Eksport zamówień do zewnętrznego systemu wysyłkowego

### ISSUE THREAD

**Issue by polodeus** [allegro/allegro-api#1769]
Szanowni Państwo,

Chcielibyśmy skorzystać z Państwa REST-API do odczytu zamówień gotowych do wysyłki z naszego konta i wyeksportować je do naszego specjalnie opracowanego systemu wysyłkowego. Po wysyłce wysyłalibyśmy odpowiedź na nasze konto i aktualizowali status wysłanych zamówień.

W tym celu musielibyśmy być w stanie odczytać następujące dane:

-Nazwa, adres dostawy, adres e-mail klienta
-Numer produktu
-Nazwa produktu
-Zamówiona ilość
-Data zamówienia
-Numer zamówienia
-Jeśli to konieczne, dodatkowe dane, których potrzebujemy do API

Czy możemy wykonać te kroki za pośrednictwem interfejsu API REST, jeśli tak, z jakich funkcji musielibyśmy skorzystać, lub która część dokumentacji API dotyczy naszego przypadku?

Czy możemy to wcześniej przetestować w waszym środowisku Sandbox. Jeśli tak, czy można użyć środowiska w języku angielskim?

API powinno być w stanie samodzielnie odczytywać i aktualizować dane odnośnie zamówień. Przy rejestracji użylibyśmy wtedy typu przyznania OAuth-Grant-Typ "device_code”.

Jeśli nie jest to możliwe w przypadku API REST, co jeszcze mogliby nam państwo zaoferować, aby gotowe do wysyłki zamówienia wyeksportować do naszego systemu zamówień?

Będziemy wdzięczni za szybką odpowiedź.  Pozdrawiam,

**Comment by polodeus** [comment]
PS. Czy mogę wysyłać zapytania w języku Niemieckim?

**Comment by MartaNowaczyk** [comment]
Na początek proszę zapoznać się z naszym poradnikiem [PL](https://developer.allegro.pl/orders/) i [EN](https://developer.allegro.pl/en/orders/). 

Możecie skorzystać z naszego [środowiska testowego](https://allegro.pl.allegrosandbox.pl/), jednak nie ma opcji języka angielskiego.

> API powinno być w stanie samodzielnie odczytywać i aktualizować dane odnośnie zamówień. Przy rejestracji użylibyśmy wtedy typu przyznania OAuth-Grant-Typ "device_code”.

[Tutaj](https://developer.allegro.pl/auth/) znajdziecie informacje dotyczące autoryzacji.

Nie prowadzimy supportu w języku niemieckim.
