### ISSUE TITLE
Komunikaty błędów

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1770]
Pozwoliłem sobie założyć ten wątek, w którym będę umieszczał znalezione problemy związane z komunikatami błędów zwracanymi z RESTa. Jeśli można, prosiłbym bez zbędnych dyskusji, tylko błąd - sugestia, ewentualnie łapki ;)

`code: VALIDATION_ERROR` - czy tutaj mógłby się pojawiać jakiś sensowny kod, tak aby aplikacja mogła odpowiednio na niego zareagować? Przykład: wystawiam ofertę z przeterminowanym zdjęciem, dostaję:

```json
{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Provided image address is incorrect: https://a.allegroimg.allegrosandbox.pl/original/110202/203ec0754d78a0367e564a8cf951.",
            "details": "",
            "path": "",
            "userMessage": "Podany adres obrazka jest nieprawidłowy: https://a.allegroimg.allegrosandbox.pl/original/110202/203ec0754d78a0367e564a8cf951."
        }
    ]
}
```
Gdybym wiedział, że `code` to powiedzmy INVALID_IMAGE_URI to aplikacja mogła by z automatu wysłać zdjęcie ponownie, tak, że użytkownik nawet by tego nie zauważył. W chwili obecnej pozostaje parsowanie stringa `message` lub `userMessage`, który w każdej chwili może się zmienić, bo ktoś tam uzna, że wstawi przecinek. 
Dotyczy to wszystkich komunikatów walidacji, w których kod jest wszędzie taki sam i w zasadzie można powiedzieć, że potencjał tego pola jest w ogóle nie wykorzystany, żeby nie powiedzieć zmarnowany. Z tego co zauważyłem to cały zasób POST i PUT na sale/offers zwraca `VALIDATION_ERROR` w każdej możliwej sytuacji.

**Comment by Onixarts** [comment]
Niespójność komunikatów i różne języki przy `accept-language: pl-PL`.
Przykład: tworzenie cennika dostaw:

Ustawiona wartość inna niż 1, np 12:
```json
{
  "errors": [{
    "code": "INVALID_PACKAGE_SIZE",
    "message": "Invalid package size (min: 1, max: 1)",
    "details": null,
    "path": "rates[6].packageSize",
    "userMessage": "Rozmiar przesyłki dla wybranej metody dostawy musi mieścić się w przedziale 1 - 1 sztuk"
  }]
}
```
Komunikat dla użytkownika po polsku 👍.
Ustawiam 0 sztuk:
```json
{
  "errors": [{
    "code": "ConstraintViolationException",
    "message": "Unprocessable entity",
    "details": null,
    "path": "rates[6].maxQuantityPerPackage",
    "userMessage": "The number of items per package must be greater than 1."
  }]
}
```
Komunikat po angielsku 👎.
Do tego warto też zwrócić uwagę na pole `code`: raz jest ładnie `INVALID_PACKAGE_SIZE` a raz, już mniej spójnie: `ConstraintViolationException`. Rozumiem, że mogą za to odpowiadać różne warstwy serwera, ale albo zróbmy z tym porządek teraz, albo do końca istnienia REST API będą takie kwiatki dziwiły kolejnych developerów.

**Comment by MartaNowaczyk** [comment]
@Onixarts wszystkie zgłoszone komunikaty błędów do poprawki przekazałam do odpowiednich zespołów. W przypadku kolejnych przykładów napisz konkretny endpoint, którego problem dotyczy, żeby nie było niejasności.
