### ISSUE TITLE
Jak zmienić liczbę przedmiotów w ofercie?

### ISSUE THREAD

**Issue by piotr-madej** [allegro/allegro-api#1772]
Próbuje przez https://api.allegro.pl/sale/offer-quantity-change-commands/[commandid] i dostaje taką zwrotkę później przez /tasks/. Gdzie jest problem?

{"tasks":[{"offer":{"id":"6981366036"},"message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","status":"FAIL","scheduledAt":"2019-06-05T09:07:01.64Z","finishedAt":"2019-06-05T09:07:02.097Z","field":"quantity","errors":[{"code":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","message":"Exception when update offer quantity.","details":null,"path":null,"userMessage":"Exception when update offer quantity."}]}]}

**Comment by MartaNowaczyk** [comment]
Błąd pojawił się pojedynczo, czy występuje za każdym razem?  
Podeślij proszę request dla zmiany liczby przedmiotów w przypadku tego błędu.

**Comment by piotr-madej** [comment]
PUT /sale/offer-quantity-change-commands/5fb1ad13-f76a-478f-ad29-c34b22df57b9 HTTP/1.1
Host: api.allegro.pl
content-type: application/vnd.allegro.public.v1+json
accept: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJhbGciOiJSUzI(...)

HTTP/1.1 201 Created
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 31cfdf33d6808aef
Date: Wed, 05 Jun 2019 13:50:03 GMT
X-RateLimit-Remaining: 8978
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000

{"id":"5fb1ad13-f76a-478f-ad29-c34b22df57b9","taskCount":{"total":0,"success":0,"failed":0}}

------------

{"tasks":[{"offer":{"id":"6981366036"},"message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","status":"FAIL","scheduledAt":"2019-06-05T13:50:05.107Z","finishedAt":"2019-06-05T13:50:05.426Z","field":"quantity","errors":[{"code":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","message":"Exception when update offer quantity.","details":null,"path":null,"userMessage":"Exception when update offer quantity."}]}]}

**Comment by MartaNowaczyk** [comment]
@piotr-madej sprawdzamy twój przypadek.

**Comment by MartaNowaczyk** [comment]
@piotr-madej to bardzo stara oferta i nie masz w niej ustawionego parametru stan. U?supełnij go proszę i nie powinno być problemu.

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk @PawelTaberski 

Statystyka z dziś 14.06.2019, godz 9:00 do teraz czyli 14:18 -> błędów 3137 EXCEPTION_DURING_OFFER_QUANTITY_UPDATE 
wynikających z tego, że oferty są stare i nie mają parametrów ustawionych. 

Czyli dla mniej więcej tylu ofert stany magazynowe się nie zaktualiowały z powodu kurozialnego pomysłu powiązania parametrów ze stanem.
Kiedy to rozwiążecie?

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk  @PawelTaberski 
Statystyka na dziś 19.06 błędów > 35 000 u różnych Klientów
Dostajemy reklamacje na brak aktualizacji liczby przedmiotów, z uwagi na to że ręce mamy związane a Klienci nie chcą ręcznie poprawiać tysięcy swoich ofert  jesteśmy zmuszeni odsyłać tych Klientów do Was, celem wyjaśnienia tych zmian.

**Comment by MartaNowaczyk** [comment]
@sebasitanOzdoba sprawę przekazałam do odpowiedniego zespołu. Zakładaj proszę inny wątek jeśli zgłaszasz inny/nowy problem.

**Comment by SebastianOzdoba** [comment]
@MartaNowaczyk @PawelTaberski 
Wiemy coś w temacie więcej?

**Comment by PawelTaberski** [comment]
Czy problem występuje ciągle z takim natężeniem? 
Jeśli tak, to mógłbyś proszę podesłać kilka najnowszych trace-id z tym problemem.

**Comment by yncki** [comment]
up
ab1bf5b4-cbca-4631-8c34-4562da257837

**Comment by PawelTaberski** [comment]
@yncki Sprawdziłem status zadania zasobem GET /sale/offer-quantity-change-commands/{commandId}/tasks i w odpowiedzi widzę, że otrzymałeś informacje czemu zmiana nie mogła być wykonana:
`"message": "Missing required parameters: Marka.",`

**Comment by SebastianOzdoba** [comment]
Otwieram, bo się zamknęło :)
Jeśli nie zamierzacie tego poprawić napiszcie jasno że nie zamierzacie, przynajmniej będziemy mieli gdzie kierować niezadowolonych Klientów :) 
W takim razie przydałaby się  metoda umożliwiającą sprawdzenie dla danego sprzedającego czy ma jakieś niewypełnione paramtry na trwających aukcjach, to przynajmniej wyświetlimy mu komunikat (takie coś jest na GUI w Allegro)

**Comment by barthoos** [comment]
@SebastianOzdoba 
Osobiscie to ograniczenie rowniez doprowadza mnie do szewskiej pasji, ale z drugiej strony jak inaczej Allegro ma wymusic na sprzedajacych aktualizacje oferty o nowe parametry? Liczy sie koncowy i jego wygoda, a nie sprzedajacy i jego wygoda. A koncowy, chce moc filtrowac w kategorii po parametrach.

**Comment by SebastianOzdoba** [comment]
@barthoos true :) Dlatego tez postuluję o metodę która umożliwi dla danego UserID odpytanie o to czy mam oferty z nieaktualnymi parametrami i zwróci taką listę nieaktualnych numerów ofert, to przynajmniej pozwoli na przygotowanie raportu dla sprzedających.
Teraz przy kilku tysiącach aukcji to jest masakra by sprawdzać, a nie ma dnia byśmy nie dostawali takie zgłoszenia : )

**Comment by barthoos** [comment]
@SebastianOzdoba 
Szczerze w ta watpie, aby taka metode udostepnili. Takze moje podejscie jest takie, ze koncze aukcje na froncie, cofam oferte do drafta a tego recznie przeklikac musi juz user. Przy zaktualizowanej bazie parametrow w mojej aplikacji bedzie widzial, co, gdzie ma uzupelnic.

Gorzej jak problem dotyczy kategorii, ktora przestala byc lisciem, bo dopiero wtedy robi sie pod gorke, ale co poczac..

**Comment by SebastianOzdoba** [comment]
@barthoos jest taka opcja w mojeAllegro więc dlaczego nie :)
Masz tam Uzupełnij parametry i zwraca Ci listę aukcji które mają nieuzupełnione, więc nie widzę przeciwwskazań by to było w restAPI

**Comment by PawelTaberski** [comment]
Sugestię oczywiście przekazałem, jeśli wdrożymy taki zasób, to poinformujemy o tym w dedykowanym komunikacie.
