### ISSUE TITLE
Pobieranie kategorii po nazwie

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#1774]
:bulb: **Sugestia**

Przydałaby się możliwość pobrania kategorii po ich nazwie, aktualnie klienci, aby znaleźć daną kategorię mogą podać wyłącznie jej ID (numer) co raczej nie jest zbyt wygodne.

**Comment by MartaNowaczyk** [comment]
Dziękujemy za sugestię. Przekazuję ją do odpowiedniego zespołu. Jeśli zdecydujemy się na taką zmianę poinformujemy o tym w odrębnym komunikacie.
