### ISSUE TITLE
GET /sale/offers/

### ISSUE THREAD

**Issue by marlemiesz** [allegro/allegro-api#1775]
Witam,

Odpytując GET /sale/offers/7872906524 otrzymuję nieprawidłowy stan magazynowy.
Api => 4
Aukcja => 29

**Comment by MartaNowaczyk** [comment]
Sprawdzamy w czym jest problem.

**Comment by pkrzemo** [comment]
REST Api podaje dane tylko z ostatnich 30 dni (niestety). Nie wiem gdzie patrzysz ale może być tak że patrzysz na stronie Allegro na dane "od początku świata" (czyli od wystawienia oferty). ;-)

**Comment by marlemiesz** [comment]
Tutaj jest rozbieżność jeżeli chodzi o ilość dostępną, a nie ilość wystawioną (stock.available) https://allegro.pl/oferta/sluchawki-douszne-jbl-t110-mikrofon-blue-7872906524.
 
Zresztą ten sam problem jest podczas aktualizacji aukcji
- wysyłam do Api stock.available => 5, na aukcji pojawia się 30
- wysyłam 3 => aukcja 28 itd.

Gdzieś te 25 sztuk jest ukryte w Allegro :)

**Comment by MartaNowaczyk** [comment]
@marlemiesz tak, tą rozbieżność staramy się namierzyć.

**Comment by marlemiesz** [comment]
Coś się z tematem dzieje ?

**Comment by MartaNowaczyk** [comment]
Jako pojedynczy przypadek czeka w kolejce na weryfikacje, dlatego nie mam jeszcze żadnych informacji.

**Comment by PawelTaberski** [comment]
@marlemiesz Wprowadziliśmy poprawkę, stock powinien już być prawidłowy.
