### ISSUE TITLE
nie pobiera sprzedaży 

### ISSUE THREAD

**Issue by AlekKlepacz** [allegro/allegro-api#1777]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

nie pobiera sprzedaży z kont. Aplikacja działa w czasie rzeczywistym. Jakie mam podać dane do zbadania sytuacji.

**Comment by MartaNowaczyk** [comment]
Dostajesz jakieś błędy? Podaj request i response, dla endpointu, który stanowi problem. Możesz podać je tutaj lub podesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1777
