### ISSUE TITLE
Problem z powiązaniem konta do aplikacji w trybie device

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#1778]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam
Mam problem z powiązaniem konta z aplikacji w trybie device. W wielkim skrócie rzadko kiedy działa.
Pobieram adres do autoryzacji i przekierowuje na niego użytkownika (aktualny Chrome, tryb incognito, użytkownik niezalogowany)

1. Użytkownik ląduje na: https://allegro.pl/skojarz-aplikacje?code=XXXXX
2. Kod autoryzacyjny jest wpisany, klikamy Dalej
3. I teraz bywa rożnie - czasem pokazuje pola do logowania, ale częściej ostatnio zalogowanego użytkownika ("Potwierdź swoje konto. Jesteś zalogowany jako ABC. Czy chcesz kontynuować jako ten użytkownik?" Co ciekawe wg menu użytkownik nie jest zalogowany vide zdjęcie. Przypominam, że jesteśmy wylogowani i w trybie incognito:))
4a. Po wybraniu Kontynuuj wpadamy w pętle i zostajemy przekierowani do https://allegro.pl/skojarz-aplikacje
4b Po wybraniu "Zmien konto" również lądujemy na https://allegro.pl/skojarz-aplikacje

Url które udało mi się podejrzeć:
https://allegro.pl/skojarz-aplikacje?code=aaiewrbaa			
https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=aaiewrbaa
https://allegro.pl/login/form?authorization_uri=https:%2F%2Fallegro.pl%2Fauth%2Foauth%2Fheadless%2Fauthorize%3Fuser_code%3Daaiewrbaa&oauth=true

Pod IE są jeszcze większe cyrki bo często po logowaniu przekierowuje na stronę główną

https://ibb.co/Ydf5bmS
https://ibb.co/1zhHP66

**Comment by MartaNowaczyk** [comment]
@dol1234 sprawdzamy

**Comment by dol1234** [comment]
Dziekuję. Dzisiaj problem już nie występował (przed chwilą udało mi się dodać kilka kont - wszystkie w trybie incognito na Chromie)

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy device-flow 4 krotnie. Czy działa przy różnych momentach odpalenia karty incognito (czyli nowo otwarta karta, dopiero zalogowany, dopiero wylogowany) i to samo w zwykłym trybie. Za kazdym razem wszystko działało poprawnie.
