### ISSUE TITLE
doGetRefundsList - filtrowanie po id oferty

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#1779]
Witam,

próbuję pobrać informacje dot. statusu zwrotów prowizji dla wielu ofert jednocześnie.
W tym celu używam dynamicznego filtru 'itemId' oraz listę identyfikatorów ofert - 100 szt..

W odpowiedzi zawsze otrzymuję tylko informacje o jednej ofercie. 
Czy jest to normalne działanie tej metody ?

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i jest to poprawne działanie. Dla tego filtru zwracamy tylko jeden element, więc jeśli podałeś ich więcej zawsze zwróci ten pierwszy.

**Comment by joe1d83** [comment]
Dziękuję za odpowiedz
