### ISSUE TITLE
Dostęp do statystyk sprzedaży przez API

### ISSUE THREAD

**Issue by gustawdaniel** [allegro/allegro-api#178]
Była w allegro możliwość płatnego obserwowania statystyk sprzedaży. To narzędzie ma zostać wyłączone:

> https://allegro.pl/pomoc/aktualnosci/30-kwietnia-wylaczymy-statystyki-sprzedazy-w-zakladce-moje-allegro-gRKne18XeC2

Czy informacje o sprzedanych sztukach z danej oferty można uzyskać za pomocą API?

**Comment by MaciejPotepa** [comment]
W WebAPI takie informacje pobierzesz dzięki metodom [doShowItemInfoExt](https://allegro.pl/webapi/documentation.php/show/id,342) i [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,52). Informacje odnośnie popularności zwracamy w polu **itBidCount**.
