### ISSUE TITLE
Zmiana ceny w ofercie - problem z kodem

### ISSUE THREAD

**Issue by Allecart** [allegro/allegro-api#1780]
Problem dość prozaiczny, jednak mi zajmuje on 3 dzień, a wy pewnie zweryfikujecie problem w minutę.
Posiadam kod do zmiany ceny, jednak wywala mi błąd 400 - zły format json
Proszę o podpowiedź jak to ugryźć

                          `$GUID = getGUID();
                          $url = 'https://api.allegro.pl/sale/offer-price-change-commands/'.$GUID;
                          $ch = curl_init($url);

                          $headers = array(
                              'Accept: application/vnd.allegro.public.v1+json',
                             'Content-Type: application/vnd.allegro.public.v1+json',
	                             'Accept-Language: PL',
                                'Authorization: Bearer '.$access_token
                          );
                          $postData = '{
                                        "modification": {
                                                        "type": "FIXED_PRICE",
                                                        "price": {
                                                          "amount": "31",
                                                          "currency": "PLN"
                                                        }
                                        },
                                        "offerCriteria": [
                                          {
                                          "type": "CONTAINS_OFFERS",
                                            "offers": [
                                              {
                                                "id": "123456789"
                                              }
                                            ]
                                          }
                                        ]
                                        }';
                          curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
                          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                          curl_setopt($ch, CURLOPT_POST, true);
                          curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
                          $response = curl_exec($ch);
                          echo 'Status-Code: ' . curl_getinfo($ch, CURLINFO_HTTP_CODE);
                          echo '<pre>';print_r(json_decode($response, true));echo'</pre>';
                          curl_close($ch);
`

**Comment by kfijalko** [comment]
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");

https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT

**Comment by Allecart** [comment]
Faktycznie brakowało tego - edytowana funkcja i linijka została pominięta.
Jednak błąd 400 wciąż istnieje.

**Comment by Patryk27** [comment]
Wysyłasz zły nagłówek `Content-Type` - powinien być `application/json; charset=utf-8`.

**Comment by Allecart** [comment]
Problem leżał w generowaniu guid, który nie został tu pokazany.
Temat zamykam i dziękuję chętnym za wypowiedź! ;)
