### ISSUE TITLE
INTERNAL_SERVER_ERROR przy tworzeniu określonej oferty

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#1781]
Występuje problem: 
 - [ X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Brak szczegółów o przyczynie niepowodzenia utworzenia oferty.
Pola oferty mogą Państwo pobrać z oferty wzorcowej o ID: 7154015802
W innych przypadkach otrzymuję informację o błędach np. brak obowiązkowych parametrów, ale w tym szczególnym przypadku nieustannie otrzymuję:
`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal Server Error","details":null,"path":"/sale/offers","userMessage":null}]}`

Oprócz tego content-type odpowiedzi to nie json.

**Comment by PawelTaberski** [comment]
Przetestowałem na ofercie jaką podesłałeś i wszystko wygląda poprawnie. W ofercie brak niektórych obowiązkowych parametrów, ale nie otrzymałem Internal Server Error.
Sprawdź proszę, czy u Ciebie problem dalej występuje.

**Comment by aktywnitu** [comment]
Dobrze, sprawdzę i dam znać.

**Comment by PhotoSoft** [comment]
Moi Klienci co chwilę zgłaszają problemy, że coś nie działa. Nie mogą normalnie pracować. **RestApi nie jest w ogóle przygotowane na taki duży ruch!** Nie mam logów, ale zrzut mówi wszystko. Do tego notoryczne błędy 408, 503, 504, InternalServerError, itd.

![](https://snag.gy/Wzue5L.jpg)

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tych problemów.
