### ISSUE TITLE
Generate files from swagger.yaml with maven

### ISSUE THREAD

**Issue by AndwariAciel** [allegro/allegro-api#1782]
Hi there, I have a question:
I am currently trying to generate Java files for my project from your swagger.yaml with the swagger-codegen-maven-plugin, but I am getting a lot of errors when compiling the generated files. Is there something I have to look out for? Or is there a better way to generate those files?

(I also tried to generate a java project from the online editor.swagger.io but it too would not compile)

Thanks in advance,
Markus

**Comment by PawelTaberski** [comment]
You can try to use [openapi-generator](https://github.com/OpenAPITools/openapi-generator) should be ok.

**Comment by AndwariAciel** [comment]
I am sorry but it somehow doesn't work. I am using the latest openapi-generator version (4.0.1) and try to generate it with this command:
java -jar {path}\openapi-generator-cli-4.0.0.jar generate -i {path}\swagger.yaml -g java -o {path}\test

It generates the project but has a lot of code errors like mixing up classes TypeEnum and String (eg in BenefitSpecifaction) or having strange imports of the class AnyOfCorrectionOperationContributionOperationPayoutOperationPayoutCancelOperationRefundIncreaseOperationRefundCancelOperationRefundChargeOperationSurchargeOperation (eg in PaymentOperations)

Am I missing options or parameters in the generation? I am a bit lost

**Comment by PawelTaberski** [comment]
Try to use -g spring

**Comment by AndwariAciel** [comment]
Thanks, but still the same errors. PaymentOperations is red all over:

AnyOfCorrectionOperationContributionOperationPayoutOperationPayoutCancelOperationRefundIncreaseOperationRefundCancelOperationRefundChargeOperationSurchargeOperation cannot be resolved to a type	PaymentOperations.java	/openapi-spring/src/main/java/org/openapitools/model

**Comment by PawelTaberski** [comment]
Thank for information we will check it.

**Comment by AndwariAciel** [comment]
Are there any news?

**Comment by PawelTaberski** [comment]
Not yet. I am waiting for information. I will inform you.

**Comment by RomanKuzyk** [comment]
hi dear Allegro team,
do you have some ETA for fixing production swagger.yaml issues
so it will be possible generate valid client based on it ?

**Comment by PawelTaberski** [comment]
We are still working to fix this, I will let you know.

**Comment by PawelTaberski** [comment]
@RomanKuzyk We have fixed this errors, now should be ok.
