### ISSUE TITLE
WSDL Sandbox - Internal System Error

### ISSUE THREAD

**Issue by wotekPL** [allegro/allegro-api#1783]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Przy próbie pobrania WSDL dla sandboxa otrzymuję wewnętrzny błąd systemu.

https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
<SOAP-ENV:Header/>
<SOAP-ENV:Body>
<SOAP-ENV:Fault>
<faultcode>ERR_INTERNAL_SYSTEM_ERROR</faultcode>
<faultstring>Wewnętrzny bład systemu.</faultstring>
<faultactor>Internal System Error.</faultactor>
</SOAP-ENV:Fault>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem. Sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by Onixarts** [comment]
Da rady coś z tym zrobić bo już 3 dzień jak sandbox leży i nie można sprawnie działać.

**Comment by PawelTaberski** [comment]
Wsdl powinien już normalnie się pobierać, czy problem u Ciebie dalej występuje?

**Comment by Onixarts** [comment]
Jest ok.
