### ISSUE TITLE
Podawajcie w komunikatach nazwy parametrów, które trzeba poprawić

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1784]
Skąd ludzie mają wiedzieć co poprawić jak widzą taki komunikat?

![](https://snag.gy/NjFsdw.jpg)

**Comment by PhotoSoft** [comment]
Tak w ogóle jeszcze raz gratuluję projektantowi API idiotycznego pomysłu zrezygnowania z wersjonowania zmian.

Parametry zapisuję w lokalnej bazie i teraz przy jakichkolwiek zmianach nie wiadomo kiedy wymusić ich odświeżenie. A pobieranie aktualnych parametrów z serwera przy każdym wczytaniu aukcji do edycji jest bez sensem, bo trwa dłużej, niż wyświetlenie całej aukcji w mojej aplikacji! Ludzie zjedli by mnie żywcem jak by mieli tyle czekać.

Przemyślcie temat wersjonowania kategorii/parametrów jeszcze raz.

**Comment by Onixarts** [comment]
Wersjonowanie niekoniecznie, ale dziennik zdarzeń systemowych by się jak najbardziej przydał. Taki, aby były w nim informacje o zmianie w konkretnych poddrzewach kategorii, w parametrach dla kategorii. Pozwoliło by to aktualizować tylko to co jest konieczne. Pobieranie za każdym razem całego drzewa kategorii i parametrów już przerabialiśmy i jest to bardzo frustrujące dla użytkownika aplikacji desktopowej.

**Comment by PawelTaberski** [comment]
Przekazałem wasze sugestie odnośnie parametrów i kategorii.
Odnośnie samych błędów @PhotoSoft mógłbyś proszę podesłać pełnego responsa (chodzi mi o dokładny opis błędu jaki otrzymujesz). Sprawdzimy to, na bieżąco staramy się poprawiać te komunikaty by były bardziej czytelne.

**Comment by PhotoSoft** [comment]
To akurat z innej kategorii dla przykładu, ale o te błędy walidacji chodzi:

>          {  
>             "code":"VALIDATION_ERROR",
>             "message":"Assigned valueId 129591_0 for dictionary parameter 129591 is not found.",
>             "details":"",
>             "path":"",
>             "userMessage":"Przydzielony identyfikator wartości 129591_0 nie został znaleziony dla parametru słownikowego 129591."
>          }

Ostatnio coś zmieniacie/usuwacie w parametrach i te, które wcześniej były dobrze wypełnione teraz już nie są i ludzie nie wiedzą co mają poprawić.

**Comment by PawelTaberski** [comment]
Dziękuje za przykład postaramy się to poprawić w najbliższym czasie.

**Comment by Himon-SYNCRAFT** [comment]
Dorzucę przykład od siebie:

`
{
  "code": "VALIDATION_ERROR",
  "message": "",
  "details": "",
  "path": "",
  "userMessage": "description.sections[5].items[0].content: Invalid HTML subset"
}
`

**Comment by PawelTaberski** [comment]
@Himon-SYNCRAFT Dzięki oczywiście również przekazałem do zmiany.
