### ISSUE TITLE
Ilość sprzedanych przedmiotów w ofercie

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#1785]
Mam problem z aktualizacją ofert z powodu sprzedanych przedmiotów - tak wynika z komunikatu.

Aktualizowana oferta: 7074434451
Trace-Id: 14a5943e4eea2ee1
Błąd: ERR_CANT_CHANGE_ITEM_TYPE_AFTER_BID

Jak pobieram dane ofert tym zasobem https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET 
to w polu sprzedane mam 0, stock.sold = 0
Innego sposobu na pobranie tych informacji nie znalazłem.

Druga sprawa to że wcale nie zmieniam typu oferty podczas aktualizacji.

**Comment by PawelTaberski** [comment]
Jeśli chcesz dokonać edycji oferty zasobem PUT /sale/offers/{offerId} to musisz przesłać pełną ofertę pobraną zasobem GET /sale/offers/{offerId} oczywiście po wprowadzeniu swoich zmian. Czy tak robisz a mimo to otrzymujesz błąd?

**Comment by avello** [comment]
Jak aktualizować ofertę i jakim zasobem to wiem.
Potrzebuję informacji o ilości sprzedanych przedmiotów w ofercie, po to aby nie aktualizować pól których nie można jak już jest sprzedaż.
Obecnie nie wiem skąd taką informację pobrać.
Podałem tylko jako przykład że mam błąd związany z tym że aktualizuję pole którego nie można bo był zakup, a zasób którym mogę to sprawdzić zwraca mi stock.sold = 0

**Comment by PawelTaberski** [comment]
Obecnie nie ma w REST API zasobu, który zwróci ci sprzedaż od początku trwania oferty. W zasobie sale/offers dane odnośnie sprzedaży są z ostatnich 30 dni.

**Comment by pkrzemo** [comment]
@PawelTaberski  to że nie ma to wiemy. To że jest potrzebny to widać. 
Pytanie jest czy coś z tym zrobicie?

**Comment by PhotoSoft** [comment]
Też się pod tym podpisuję. Klienci mi się denerwują, że jest im potrzebna taka informacja.

:bulb: **Sugestia** Dodajcie nowe pole, gdzie będzie sprzedaż od czasu wystawienia aukcji.

To chyba nie jest trudne, a jak widać po kolejnym temacie **pilnie potrzebne**.

**Comment by PawelTaberski** [comment]
Sugestię przekazałem, odnośnie najbliższych planów wszelkie informacje znajdziecie w [naszym harmonogramie](https://developer.allegro.pl/schedule/).
