### ISSUE TITLE
"404 Object not found" po wgraniu zdjęcia do oferty.

### ISSUE THREAD

**Issue by rafalkrawiec** [allegro/allegro-api#1787]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry, mam problem z wgraniem zdjęć do oferty w środowisku testowym. Po wysłaniu zapytania ze zdjęciem dostaję prawidłową odpowiedź `200` oraz URL do zdjęcia. Mogę ten URL też ustawić w ofercie, i jest zwracany zarówno w parametrze `primaryImage` jak i w tablicy `images`. Natomiast przy próbie odczytu zdjęcia zwracana jest odpowiedź `404 Object not found.`

**trace-id: 984dd386ff6563ab**

Zrzut informacji o zapytaniu (w tym trace-id):
```
#
# [POST] https://upload.allegro.pl.allegrosandbox.pl/sale/images 
#
# Request Headers:
# [
#     Transfer-Encoding: chunked
#     Expect: 100-Continue
#     User-Agent: GuzzleHttp/6.3.3 curl/7.63.0 PHP/7.2.14
#     Host: upload.allegro.pl.allegrosandbox.pl
#     Authorization: Bearer [...]
#     Accept: application/vnd.allegro.public.v1+json
#     Content-Type: image/jpeg
#     Accept-Language: pl-PL
# ]
#
# Request Body:
# [
#     -- binary data sent --
# ]
#
# Response Status:
# [201]
#
# Response Headers:
#
# [
#     expires: 0
#     cache-control: no-cache, no-store, max-age=0, must-revalidate
#     x-xss-protection: 1; mode=block
#     server: envoy
#     pragma: no-cache
#     x-frame-options: DENY
#     location: https://a.allegroimg.allegrosandbox.pl/original/117f25/5a8a301f41a28fc48d9692880aff
#     trace-id: 984dd386ff6563ab
#     date: Thu, 06 Jun 2019 13:41:50 GMT
#     x-ratelimit-remaining: 8993
#     x-content-type-options: nosniff
#     content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
#     x-ratelimit-limit: 9000
#     x-envoy-upstream-service-time: 899
#     transfer-encoding: chunked
# ]
#
# Response Body:
# [
#     {"expiresAt":"2019-06-06T19:41:50.634286Z","location":"https://a.allegroimg.allegrosandbox.pl/original/117f25/5a8a301f41a28fc48d9692880aff"}
# ]
```
**EDIT** Dodam że nie zmieniałem mechanizmu wgrywania zdjęć do Allegro i wcześniej ten sam mechanizm działał prawidłowo. Problem zauważyłem dopiero dzisiaj w trakcie testów.

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście na froncie na środowisku testowym zdjęcie się nie wyświetla prawidłowo. Zgłosiłem problem do zespołu, który odpowiada za te funkcjonalności.

**Comment by Himon-SYNCRAFT** [comment]
Problem pojawia się też na produkcji, nie tylko w serwisie testowym. Teraz przynajmniej przy aktualizacji aukcji przez api zwracany jest błąd o niepoprawnych obrazkach. Wcześniej po prostu znikały obrazki z opisu.

**Comment by PawelTaberski** [comment]
@Himon-SYNCRAFT Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego pełnego requesta i komunikat jaki otrzymujesz. Sprawdzimy to. W zgłoszeniu zaznacz, że dotyczy ticketa numer 1787 na GitHub-ie.

**Comment by lukasz-mainka** [comment]
Dzień dobry, mam ten sam problem.
Dodam, że dodanie obrazka przez formularz w sandbox przy wystawianiu oferty powoduje równie ten sam efekt.

**Comment by PawelTaberski** [comment]
@lukasz-mainka Jeśli chodzi o problem na produkcji to podeślij proszę, tak jak pisałem wyżej [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego pełnego requesta i komunikat jaki otrzymujesz. Sprawdzimy to. W zgłoszeniu zaznacz, że dotyczy ticketa numer 1787 na GitHub-ie.
Jeśli natomiast chodzi o sandboxa to już pracujemy nad rozwiązaniem tego problemu.

**Comment by Onixarts** [comment]
Sytuacja sprzed  chwili

```
POST https://upload.allegro.pl.allegrosandbox.pl/sale/images
{
Accept: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Authorization: Bearer xxx
content-type: image/jpeg
}
{
 [binary data...] 
}
RESPONSE 201 (Created) ----------------------------------------------------------------- 14:25:00:479 (41ms)
{
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: e999a1b4b169cde
x-ratelimit-remaining: 9000
x-content-type-options: nosniff
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 950
transfer-encoding: chunked
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Sat, 08 Jun 2019 12:25:00 GMT
Location: https://a.allegroimg.allegrosandbox.pl/original/11ef9b/fd7249064968b951c1dd0ebccac4
Server: envoy
Content-Type: application/vnd.allegro.public.v1+json; charset=UTF-8
Expires: 0
}
{"expiresAt":"2019-06-08T18:25:00.704874Z","location":"https://a.allegroimg.allegrosandbox.pl/original/11ef9b/fd7249064968b951c1dd0ebccac4"}
```
Pod wskazanym adresem nie ma zdjęcia. Wejście przez przeglądarkę: **Object not found.** i 404.

**Comment by PawelTaberski** [comment]
Pracujemy już nad rozwiązaniem tego problemu, prośba o cierpliwość.

**Comment by rafalkrawiec** [comment]
Wygląda na to że zdjęcia zaczęły już działać w środowisku testowym.
Dziękuję za pomoc.

**Comment by shambo666** [comment]
Problem powrócił (środowisko produkcyjne). Zdjęcia dodają się poprawinie po czym nie da się ich otworzyć - błąd "Object not found."

`{
    "expiresAt": "2023-01-17T15:18:45.796238Z",
    "location": "https://a.allegroimg.com/original/11bb4a/b52f3a07425b8a4cb22960bfcf8b"
}`

**Comment by Lukasz-Zurek** [comment]
@shambo666 Zdjęcie jest już widoczne. Jeśli jednak masz nowe przykłady - sprawdzimy je.
