### ISSUE TITLE
Czy drafty mają termin ważności?

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#1788]
Jak w temacie. Czy załadowane drafty mają termin ważności po którym są usuwane?

**Comment by MartaNowaczyk** [comment]
Dla draftu przyjmij 60 dni.

**Comment by FromAnyHole** [comment]
@mirkosmuz - przyjmij również, że poprawnie wysłany zasób zdjęciowy (lub inny) do użycia wyłącznie w ramach draft'ów - ma czas przechowywania 6-7 miesięcy, ale to wszystko i tak jest "na oko"...
