### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by kczechowski** [allegro/allegro-api#1789]
Proszę o aktywację sprzedaży na koncie sandbox:

arris_test

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktywowałem twoje konto. Aby w pełni aktywować konto firmowe musisz przejść do zakładki moje konto i wysłać do nas dowolne 2 pliki.

**Comment by kczechowski** [comment]
Wysłane.

**Comment by PrzemyslawLukanowski** [comment]
Konto powinno być w pełni aktywne.
