### ISSUE TITLE
Jak pobieracie sprzedane przedmoty?

### ISSUE THREAD

**Issue by kaminiak23** [allegro/allegro-api#179]
Jakich metod używacie do pobierania sprzedanych przedmiotów? Szukam już dłuższy czas i nie znajduję sensownego rozwiązania aby pobrać w jakąś listę wszystkie zakupy i sprawdzać nowe co X czasu. Jest ich kilka ale jak nie wypełni formularza to zakup nie trafia do listy, jak jest oplacony to nie widać go w metodzie ... jest jakaś jedna która zwróci wszystkie?

**Comment by LukaszKorek** [comment]
Do monitorowania sprzedaży zalecamy korzystanie z dzienników. Tutaj podsyłam link do poradnika jak z nich dokładnie korzystać: https://allegro.pl/webapi/tutorials.php/tutorial/id,100421
