### ISSUE TITLE
GetPostBuyFormsDataForSellers - ERR_NEW_PAYMENT_INTERNAL_ERROR (dla 1 tranzakcji)

### ISSUE THREAD

**Issue by solokazama** [allegro/allegro-api#1790]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

W naszych logach od wczoraj ok. 22:50 (do teraz) za kazdym razem gdy wywolywana jest metoda doGetPostBuyFormsDataForSellers z nr tranzakcji:  1027317075 , otrzymujemy:

**ERR_NEW_PAYMENT_INTERNAL_ERROR - Wewnetrzny blad PayU**

pierwszy raz widzimy taki blad, w kodzie na produkcji po naszej stronie nic sie nie zmienilo
zreszta blad sugeruje "wewnetrzny blad" po stronie api, cokolwiek oznacza.

czyli to co podajemy tu na wejsciu:
https://allegro.pl/webapi/documentation.php/show/id,703

na prosbe klienta recznie mu pchnelismy ten formularz, jednakze moglibysmy dostac informacje co jest przyczyna wewnetrznego bledu dla tej tranzakcji? nigdy sie z takowym nie spotkalismy i via webapi nie ma opcji, aby to obsluzyc.

**Comment by MartaNowaczyk** [comment]
To bardzo rzadki i ogólny błąd który zwracamy. Potrzebujemy dokładne czasy występowania błędu, czyli czasy requestów. Podeślij request i response z datą i godziną przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1790 do weryfikacji.

**Comment by solokazama** [comment]
Blad wystepuje zawsze dla tej jednej transakcji: 1027317075

Prawdopodobnie system Poczty Polskiej wyklada sie tez na tym (nie pomija) i dokladnie od tego zamowienia klientowi w systemie Poczty Polskiej (https://e-nadawca.poczta-polska.pl/) nie pobiera dalszych zamowien allegro - zakladamy

Mozna cos z tym zrobic? Bo o ile po naszej stronie potrafilismy skipnac to zamowienie (aby kolejne pobieralo) tak nie mamy zadnego wplywu na system Poczty Polskiej i na obecna chwile nic nie pobiera (klient ma 60 paczek do wyslania, a elektroniczny nadawcza Poczty Polskiej nie pozwala recznie dodawac - tylko via API automatycznie).

Bardzo prosze o reakcje, bo klient nie ma jak wyslac paczek (doslownie - bo nie mozna nawet recznie dodac) - wszystko przez tą ferelna tranzakcje: 1027317075

dla pewnosci - wykonujac: 
doGetPostBuyFormsDataForSellers dla tranzakcji 1027317075

zawsze jest:
ERR_NEW_PAYMENT_INTERNAL_ERROR - Wewnetrzny blad PayU

i tym sposobem klient nie moze wyslac paczek Poczta Polska (dokladniej klienci wybieraja Odbior w Punkcie Zabka, Orlen - dla Smarta)

@MartaNowaczyk

**Comment by mroocoo** [comment]
Podepnę się pod problem bo u nas też występuję,
Dla transakcji o id: 1023582087, 1023584138, 1023584589, 1027605379 doGetPostBuyFormsDataForSellers zwraca błąd ERR_NEW_PAYMENT_INTERNAL_ERROR: Wewnętrzny błąd PayU

**Comment by PawelTaberski** [comment]
Dane przekazałem do zespołu, który bada ten problem, prośba o cierpliwość.

**Comment by solokazama** [comment]
@PawelTaberski 
Jest szansa na rozwiazanie tego problemu? Generalnie nie da sie przetworzyc takich tranzakcji - wiec nie da sie teoratycznie wyslac (klient moze probowac recznie, ale to chyba nie o to chodzi, bo naweet moze nie wiedziec, ze ma takie zamowienie przez w/w blad).

Bardzo bym prosil, aby to nie poszlo jak moja ostatnia prosba to dev/null:
https://github.com/allegro/allegro-api/issues/1557

:|

jak nie bedzie trzeba trzymac hybrydy (soap+rest; inpost story) to nie bedzie zapytan o soap;). 
Z gory dzieki za **rozwiazanie problemu**. W teorii nie powinnismy w ogole w/w bledu dostawac, bo po naszej stronie nie ma jak tego obejsc i obsluzyc tej tranzakcji.

**Comment by PawelTaberski** [comment]
Cały czas badamy tą sprawę i szukamy rozwiązania, przekazałem do zespołu, który pracuje nad tym, że sprawa jest pilna. Proszę o jeszcze trochę cierpliwości.

**Comment by mroocoo** [comment]
Czy już coś wiadomo? - bo błąd nadal występuje - i jak ja jestem cierpliwy, tak nasi klienci już jakby mniej.

**Comment by PawelTaberski** [comment]
Nie mam jeszcze żadnych nowych informacji pracujemy nad wykryciem i usunięciem tego problemu.
