### ISSUE TITLE
[Rest API] dodawanie tagów

### ISSUE THREAD

**Issue by amaksymiuk** [allegro/allegro-api#1791]
Czy jest jakiś ważny powód rozjazdu w dodawaniu tagów: w panelu Allegro mogę dodawać tagi do szkicu oferty, a za pomocą Rest API nie mogę dodawać do szkicu (oferta musi być aktywna)?

**Comment by PhotoSoft** [comment]
Dziwny wymysł projektanta. Już to zgłaszałem, nie zmienią tego...
