### ISSUE TITLE
Failed to decode basic authentication token

### ISSUE THREAD

**Issue by oflospzoo** [allegro/allegro-api#1792]
Mam zarejestrowaną apikację typu DEVICE.
Próbuję się zalogować do REST API za pomocą przykładu z https://developer.allegro.pl/auth/#DeviceFlow:
curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(client_id:client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'

,ale cały czas pomimo wypełnienia danych w (client_id:client_secret) i {client_id} mam response:
{"error":"Unauthorized","error_description":"Failed to decode basic authentication token"}.

Co jest tego przyczyną?

**Comment by PawelTaberski** [comment]
A czy pamiętałeś, aby zakodować całość danych client_id:client_secret wraz ze znakiem “:” pomiędzy wartościami. Jeśli tak a mimo to jest błąd to jaki status http dostajesz?

**Comment by autornet** [comment]
Podepnę się pod temat.
Delphi 10.1 Berlin, dane są zakodowane, a komunikat mam ciągle ten sam:
Unauthorized - kod 401

var Base64: TBase64Encoding;
begin

  Base64 := TBase64Encoding.Create(5000,'');

  RestClient1.BaseURL := 'https://allegro.pl';
  RestRequest1.Resource := 'auth/oauth/device';
  RestRequest1.AddParameter('Authorization','Basic '+ Base64.Encode( client_id+':'+client_secret ), pkHTTPHEADER);
  RestRequest1.AddParameter('Content-Type','application/x-www-form-urlencoded', pkHTTPHEADER);
  RestRequest1.AddParameter('client_id',client_id, pkREQUESTBODY);
  RestRequest1.Execute;

Może ktoś cokolwiek ?

**Comment by PawelTaberski** [comment]
Nie prowadzimy wsparcia w kodowaniu, jednakże pewnie ktoś z forum miał już podobny problem i Tobie coś podpowie.
Odnośnie samego uzyskania tokena umieściliśmy jeden przykład na stronie może Tobie pomoże:
https://developer.allegro.pl/getting_started/

**Comment by autornet** [comment]
Ten przykład niestety także nie działa - próbowałem.

Cały czas mam zwrotkę:

Something went wrong

**Comment by wisensane** [comment]
@oflospzoo
Spróbuj w miejsce `base64(client_id:client_secret)` wstawić ciąg wygenerowany np. w [tym](https://www.base64encode.org/) narzędziu (nie zapomnij o znaku ":" między wartościami). W miejsce `{client_id}` podstaw oczywiście wartość _client_id_.

Przykładowe zapytanie mogłoby wyglądać następująco:

`curl -X POST 'https://allegro.pl/auth/oauth/device' -H 'Authorization: Basic NTNlYmVjMDBmOWNiNDZhNzhkZjljMzJmMGM1MmE3MDU6Y2x3eVVsbkhvbHNyV0Q0bU1oaXRLU1lWclVKWGgzVlJiMTI1djNRWm5DN1h0TTFaeDZ5NFh4eTZHQlhRSDJRQw==' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id=78fafa12f8bf46d76df7c32f0b52e705'`
