### ISSUE TITLE
Nie działa nam wystawianie aukcji od początku czerwca.

### ISSUE THREAD

**Issue by zosanka** [allegro/allegro-api#1793]
Od początku czerwca wystawia nam się przez api tylko co któraś oferta. Zwraca błędy "usunięcie szkicu oferty w wyniku porzucenia wystawiania" oraz "Usunięcie szkicu oferty w wyniku działania kontroli synchronizacji". 
Sklep jest na sky-shopie.

**Comment by solokazama** [comment]
chyba nie tutaj - skontaktuj sie ze sky-shope (itd)

**Comment by PawelTaberski** [comment]
@zosanka w takim wypadku jedyne co możemy zalecić, to tak jak napisał Tobie @solokazama skontaktuj się z autorem tego oprogramowania z którego korzystasz.

**Comment by zosanka** [comment]
Oni twierdzą, że to wina allegro i nowego api. U nich jest podobno ok. Odesłali mnie tutaj. Mam już trochę dość tego przerzucania piłeczki, a doszły jeszcze kolejne problemy. Aukcja potrafi się wystawić ale bez zdjęć. To jest jakiś koszmar.

**Comment by PawelTaberski** [comment]
@zosanka Jeśli Sky-shop ma jakiś problem z naszym API to poproś ich, aby skontaktowali się z nami w tej sprawie. Oni mają dostęp do wszelkich niezbędnych danych jak wywołania, responsy itp. które są niezbędne do zdiagnozowania przyczyny problemu. Odnośnie zdjęć niedawno mieliśmy problem z długimi czasami przesyłania zdjęć, ale obecnie już udało się znacząco skrócić te czasy.
