### ISSUE TITLE
[compatibilityList] type=ID, a walidacja sugeruje użycie formy text

### ISSUE THREAD

**Issue by autobizpl** [allegro/allegro-api#1794]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym

Przy przesłaniu typu pojazdu poprzez ID w compatibilityList wg. https://developer.allegro.pl/compatibility_list/#id - przykład:
```
"compatibilityList": {
  "items": [{
    "id": "e3278ed6-9022-4135-b03f-e5e8d03accd7",
    "type": "ID",
    "additionalInfo": []
   }]}
```
Zwraca błąd, jakoby należało wstawić text, a nie ID!

`[{"code":"VALIDATION_ERROR","message":"","details":"","path":"compatibilityList","userMessage":"rawItems[0].text: must not be empty"}]`

**Comment by psos** [comment]
Mieliśmy to samo, zwróc uwagę, aby ustawić namespace beta.**v2**

Czy działa Wam pobieranie samochodów po kTypeNr ? 

 /sale/compatible-products?type=CAR&tecdoc.kTypNr=10376

Zwraca:
object(stdClass)#86 (3) {
  ["count"]=>
  int(0)
  ["totalCount"]=>
  int(0)
  ["compatibleProducts"]=>
  array(0) {
  }
}

A jeszcze dwa dni temu zwracało uuid.

**Comment by autobizpl** [comment]
> Mieliśmy to samo, zwróc uwagę, aby ustawić namespace beta.**v2**

Przy beta.v2 przechodzi, bo w odpowiedzi jest typ pojazdu (text):
`"compatibilityList":{"items":[{"text":"NISSAN PRIMERA Hatchback (P11) 1999/08-2002/07 1.8 16V 114KM/84kW","id":"29a55b29-7908-4d60-b795-d1f436904a58","type":"ID","additionalInfo":[]}`

ale zwraca błąd:
{"code":"VALIDATION_ERROR","message":"**Selected compatibility table has different input type than supported in offer category.**"

...jakoby kategoria 250405 klocków hamulcowych nie obsługiwała tego typu, a przecież w instrukcji pisze o wszystkich kategoriach części samochodowych.

> 
> Czy działa Wam pobieranie samochodów po kTypeNr ?
> /sale/compatible-products?type=CAR&tecdoc.kTypNr=10376

2 tygodnie temu działało z beta.v1

**Comment by PawelTaberski** [comment]
Wersja beta jeszcze nie jest wdrożona, jak tylko wdrożymy poinformujemy o tym.
W poradniku jest zapis:
"Na przełomie maja i czerwca 2019 roku udostępnimy wersję beta nowej wersji sekcji Pasuje do, która jest zintegrowana z bazą pojazdów TecDoc...."
Jednakże jeszcze nie zostało to wdrożone.
