### ISSUE TITLE
Timeout podczas upload zdjęć na https://upload.allegro.pl

### ISSUE THREAD

**Issue by koszar93** [allegro/allegro-api#1795]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas uploadu zdjęć metodą POST https://upload.allegro.pl/sale/images co jakiś czas dostaje błąd 504 Gateway Time-out. Do jednej aukcji dodaje cztery zdjęcia, trzy z nich się dodadzą bez problemu a np. przy czwartym zwraca time-outa. W innym przypadku, błąd otrzymuje już przy pierwszym zdjęciu. Spróbowałem po każdej operacji uploadu odczekać 1,5 sekundy, jednak nadal problem ten się pojawia.

> 504 Gateway Time-out The server didn't respond in time.

var request = CreateRequest("/sale/images", RestSharp.Method.POST, Token, "application/vnd.allegro.public.v1+json");
string json = JsonConvert.SerializeObject(images, Formatting.None);

request.AddParameter("application/vnd.allegro.public.v1+json", json, ParameterType.RequestBody);

var response = Client.Execute(request);

if (response.StatusCode == System.Net.HttpStatusCode.Created)
	return ImagesRespose.FromJson(response.Content);
else
	throw new Exception(response.Content);

Proszę o pomoc.

**Comment by PhotoSoft** [comment]
Albo ServiceUnavailableException. Zróbcie w końcu coś z tym API, bo nie da się wystawiać aukcji.

10 prób pod rząd wgrania małego zdjęcia zakończone niepowodzeniem:
https://gist.githubusercontent.com/PhotoSoft/5b01da9c79527f5f4e968def7690fa71/raw/bc40b849ee890b0135efec4b548c59c30017dae5/json.json

**Comment by PawelTaberski** [comment]
Metoda działa, ale czasy odpowiedzi są bardzo wysokie nierzadko nawet ponad 8000ms pracujemy nad tym problemem. Prośba o cierpliwość.

**Comment by mediablue** [comment]
Witam,

Kontynuuję wątek obecnie mam problem również z wystawianiem aukcji. Problematyczne jest brak interpretowania przez API w parametrze url znaków specjalnych:

-d '{
       "url":"https://imgur.com/1aOIvg3E.jpg" 
      }'     

Dla przykładu:
31717_ŚCIANA%20GRODZIOWA_1498203404725.JPG

Do 1 Czerwca - działało to bez zarzutu - od 1 niestety wywala błąd Unprocessable entity

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a jakiego wysyłasz wraz z trace-id i responsem. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do zgłoszenia numer 1795 na GitHub-ie. Chciałem przetestować na grafice jaką podałeś ale widzę, że już nie jest dostępna pod tym linkiem.

**Comment by magik092** [comment]
Nam również doskwiera ten problem, często dostajemy 504 przy uploadowaniu zdjęć. Jest jakaś nadzieja na poprawienie tego czy mamy szukać jakiegoś innego rozwiązania już na dłuższą metę?

@mediablue ogólnie nie jest dobrym pomysłem posługiwanie się takimi znakami w URL, wiele API sobie z tym nie radzi. My jak mamy jakieś stare pliki z dziwnymi znakami to sobie to proxujemy do przyjaznego URL i problem znika (nauczka po Amazon oraz Mirakl).

**Comment by pietrach** [comment]
Również się dołączam, występują częste problemy z przesłaniem zdjęć. Albo timeouty albo serwis chwilowo niedostępny.

**Comment by SebastianOzdoba** [comment]
Również, nasi Klienci zgłaszają błędy 504 - gateway timeout

**Comment by PawelTaberski** [comment]
Rozumiem, już pracujemy nad rozwiązaniem tego problemu.

**Comment by koszar93** [comment]
Dzisiaj kilkukrotnie błędy 504 dostałem przy tworzeniu oferty. Przewidziany jest jakiś termin w którym będą te podstawowe metody działać w 100%?

**Comment by PawelTaberski** [comment]
Problem ze zdjęciami nie powinien już występować, czy w dalszym ciągu macie problem z tym zasobem?
@koszar93 Czy problem u Ciebie wystąpił na produkcji czy środowisku testowym i czy dalej masz problem z tym zasobem?

**Comment by troja-3** [comment]
Mi od wczoraj nie wgrywa zdjęć, żadnej aukcji nie mogę wystawić.

**Comment by troja-3** [comment]
Zaczęło działać, zdjęcia się wgrywają

**Comment by PawelTaberski** [comment]
@mediablue Otrzymałem dane jakie przesłałeś, i odpowiedziałem Tobie w tamtym zgłoszeniu wraz z przykładem adresu. Problemem są polskie znaki.

**Comment by koszar93** [comment]
Nie zauważyłem jak na tą chwilę problemów z Time-out przy dodawaniu zdjęć. Niekiedy pojawi się podczas dodawania oferty tzn. Time-out albo brak odpowiedzi z serwera.

**Comment by PawelTaberski** [comment]
Pracujemy nad pozostałymi problemami, jeśli znów napotkasz na timeouty to podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) trace-id jeśli otrzymasz, bądź konkretny czas wystąpienia tego zdarzenia i pełnego cURL-a wraz z responsem. W zgłoszeniu zaznacz, że dane są do ticketa 1795.
