### ISSUE TITLE
Lista problemów, z którymi napotkaliśmy się podczas integracji

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#1796]
Witam, poniżej lista problemów, z którymi napotkaliśmy się podczas integracji:

1. Podczas tworzenia draftów, niemal co drugi produkt otrzymuje response exception `ServiceUnavailableException - Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.`.
2. Przesłanie klucza `location.province` (zawierającego nazwę województwa) w formacie innym niż wielko-literowy, powoduje błąd `You must select province for Poland. For other countries, leave province empty.,Invalid delivery or location part.`.
3. Wysłanie payloudu z draftem aukcji czasami powoduje błąd `INVALID_JSON - Invalid request.` po czym ponowna próba, która może nastąpić nawet chwilę później, z identycznym payloadem, takiego błędu już nie powoduje.

**Comment by PawelTaberski** [comment]
Odnośnie wspomnianych problemów:
1/ Podeślij proszę przykładowe zapytanie wraz z trace-id i responsem.
2/ Wszystkie wartości jakie możesz przesłać w tym polu znajdziesz m.in. [tutaj](https://developer.allegro.pl/sale/#new-offer).
3/ Podeślij proszę przykładowe zapytanie wraz z trace-id i responsem.
Dane podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), zaznacz, że są potrzebne do ticketa numer 1796 na GitHub-ie.

**Comment by rafalkrawiec** [comment]
Odnośnie punktu 1. problem nadal nagminnie występuje. Dane zapytania:

[2019-06-14 13:57:41] local.DEBUG: Allegro API debug information about request.
#
# [GET] https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206402495
#
# Request Headers:
# [
#     User-Agent: GuzzleHttp/6.3.3 curl/7.29.0 PHP/7.2.17
#     Host: api.allegro.pl.allegrosandbox.pl
#     Authorization: Bearer [...]
#     Accept: application/vnd.allegro.public.v1+json
#     Content-Type: application/vnd.allegro.public.v1+json
#     Accept-Language: pl-PL
#     Cache-Control: no-cache
# ]
#
# Request Body:
# [
#
# ]
#
# Response Status:
# [503]
#
# Response Headers:
#
# [
#     x-ratelimit-remaining: 8985
#     trace-id: 5bb31b43b7fd8cff
#     content-type: application/json; charset=utf-8
#     content-length: 207
#     x-ratelimit-limit: 9000
#     date: Fri, 14 Jun 2019 11:57:40 GMT
#     x-envoy-upstream-service-time: 28
#     server: envoy
# ]
#
# Response Body:
# [
#     {"errors":[{"code":"ServiceUnavailableException","message":"An error occurred","details":null,"path":null,"userMessage":"Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut."}]}
# ]

**Comment by PawelTaberski** [comment]
Sprawdziłem i jest problem z tym zasobem, zgłosiłem to do odpowiedniego zespołu. Prośba o cierpliwość.

**Comment by rafalkrawiec** [comment]
Wygląda bardziej na to że jest jakiś ogólny problem na środowisku testowym z serwerem. Przy próbie złożenia zamówienia do oferty co chwilę dostajemy błąd `503 ServiceUnavailableException`. Tak samo wyszukiwanie/przeglądanie ofert generuje masę błędów.

**Comment by MartaNowaczyk** [comment]
Dziękuję za dalsze informacje. Sprawa w toku.
