### ISSUE TITLE
Próba otwarcie strony została zablokowana

### ISSUE THREAD

**Issue by kczechowski** [allegro/allegro-api#1797]
Podczas próby autoryzacji przy pomocy authorization_code dostaję taki komunikat:

Próba otwarcie strony została zablokowana
Aby chronić naszych użytkowników stosujemy aktywną ochronę przed złośliwym ruchem. Twoje zapytanie zostało zakwalifikowane jako jedno z nich. Jeśli uważasz inaczej, zgłoś ten przypadek obsłudze klienta załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego problemu.

Kod błędu
22620c9f6abecd35

Mój url:
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=5e8ace0c6d554225bf94c2fd2a7cf60a&redirect_uri=http://10.0.0.30/app/allegro/verify/

redirect_uri zgadza się z tym przy zarejestrowanej aplikacji. Czy jako redirect_uri nie możemy używać lokalnego ip?

**Comment by p-pawel** [comment]
Up. To samo tutaj, choć w piątek działało bez problemów.

**Comment by p-pawel** [comment]
Update: utworzenie nowej aplikacji poprzez "Zarejestrują nową aplikację" kończy się dokładnie tym samym. 

Kod błędu: 0d5563df4d0b3c6c

**Comment by p-pawel** [comment]
@kczechowski U mnie pomogło wycięcie parametrów związanych z kontekstem z `redirect_uri`. Nie wiem jeszcze jaki to będzie miało wpływ na działanie aplikacji, ale przynajmniej pozwoliło na autoryzację. Może u Ciebie też jest jakiś detal w przekazywanym uri?

**Comment by kuli-g** [comment]
@kczechowski 
adres zwrotny musi być publiczny bo nie da się z zewnątrz dostać na adres z LAN-u bez kombinowania z przekierowaniem portów http/https

**Comment by p-pawel** [comment]
To jest tylko przekierowanie, i nikt nie będzie pukać z Allegro do nas, więc zwykłemu redirectowi wewnętrzny URL nie zaszkodzi. 

Nie wiem jedynie czy według wymagań Allegro adres powrotny nie musi być adresem domenowym (choćby i był to `localhost`) a nie jedynie IP (`127.0.0.1`), ale nie mogę znaleźć potwierdzenia tego w dokumentacji :D

**Comment by PawelTaberski** [comment]
@p-pawel Możesz jak najbardziej podać takie adresy.
@kczechowski Jak najbardziej możesz podawać lokal ip.
Czy problem dalej u was występuje?

**Comment by kczechowski** [comment]
@PawelTaberski 
Problem dalej występuje. Po usunięciu redirect_uri z linku działa prawidłowo, lecz ogranicza nas to do jednego adresu zwrotnego.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski  podbijam, my mamy taki komunikat z sandbox

            Aby chronić naszych użytkowników stosujemy aktywną ochronę przed
            złośliwym ruchem. Twoje zapytanie zostało zakwalifikowane jako jedno
            z nich. Jeśli uważasz inaczej, zgłoś ten przypadek obsłudze klienta
            załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego
            problemu.

Kod błędu:             f1b8a3cca68a0b46

**Comment by PawelTaberski** [comment]
Sprawę przekazałem do odpowiedniego zespołu, sprawdzimy to.
