### ISSUE TITLE
edycja trwającej oferty - Offer id cannot be changed

### ISSUE THREAD

**Issue by kuli-g** [allegro/allegro-api#1798]
Mam problem, pobrałem sobie metodą GET sale/offers/8056520289 dane oferty, zmieniłem co chciałem i jak wysyłam dane PUT sale/offers/8056520289 to dostaję błąd bez względu na to czy w JSON podaję id oferty czy nie, co robię źle?

`[code] => VALIDATION_ERROR
[message] => Offer id cannot be changed.`

poniżej JSON (wycięty opis ze względu że był długi)

`{"offers":{"id":"8056520289","name":"MANETKA PRZEŁĄCZNIK ŚWIATEŁ VW LT 28 1996-2006","category":{"id":"18892"},"product":null,"parameters":[{"id":"129591","valuesIds":["129591_2"],"values":[],"rangeValue":null},{"id":"129929","valuesIds":["129929_4","129929_256","129929_4096","129929_8192"],"values":[],"rangeValue":null},{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"214434","valuesIds":["214434_266986"],"values":[],"rangeValue":null},{"id":215858,"valuesIds":["0005407445"],"values":[],"rangeValue":""},{"id":227345,"valuesIds":["0005407445"],"values":[],"rangeValue":""}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Nowa MANETKA PRZEŁĄCZNIK ŚWIATEŁ - KIERUNKOWSKAZÓW<\/h1>"}]}]},"compatibilityList":null,"images":[{"url":"https:\/\/a.allegroimg.com\/original\/01b96f\/7a5a97304b1b863ac43d446b6202"},{"url":"https:\/\/a.allegroimg.com\/original\/01626f\/d80c79414618886cb08ce4231283"},{"url":"https:\/\/a.allegroimg.com\/original\/01ebe1\/5bb3568b4926bd1cecf836f637ed"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"157.5","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":50,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null},"delivery":{"shippingRates":null,"handlingTime":"PT24H","additionalInfo":"UWAGA - odbiór osobisty możliwy tylko po uzyskaniu informacji że towar jest już gotowy do odbioru.\r\nCzas wysyłki wynosi od 1 do 5 dni roboczych w zależności od ilości zakupionego towaru. Przy zakupie detalicznycm nie więcej niż 48h.\r\nCzas księgowania przelewów to 1 dzień roboczy, w przypadku wpłat na poczcie\/przekazem to ok 2-3 dni roboczych.\r\nDziękujemy za zakupy w naszym sklepie i zapraszamy do częstego sprawdzania naszej oferty!","shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"161097f9-c7b6-4ba7-bf7d-f6d70f777761"},"returnPolicy":{"id":"4a6fdd03-42e8-42b1-baa4-4a602ed87b83"},"warranty":{"id":"324c1cd3-7b16-45d2-939d-a6085ff4455f"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"MALOPOLSKIE","city":"Myślenice","postCode":"32-400"},"external":{"id":"1556646209"},"attachments":[],"contact":null,"validation":{"errors":[],"validatedAt":"2019-04-30T17:43:37.886Z"},"createdAt":"2019-04-30T17:43:37Z","updatedAt":"2019-04-30T17:44:29.334Z"}}`

nagłówek zapytania
`HTTP/1.1 422 Unprocessable Entity
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 9fb0f7431dee36b8
Date: Mon, 10 Jun 2019 14:52:37 GMT
X-RateLimit-Remaining: 8997
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/json
X-RateLimit-Limit: 9000`

**Comment by kczechowski** [comment]
Tak powinno wyglądać zapytanie PUT:
{
    "id": "6206387839",
    "name": "sdfsdfdsfsd"
}
Trzeba przekazać id oferty do urla i do body

**Comment by kuli-g** [comment]
@kczechowski jak już pisałem

> dostaję błąd bez względu na to czy w JSON podaję id oferty czy nie

**Comment by kczechowski** [comment]
Używasz niepoprawnej składni. Nie powinno być żadnego pola "offers". Od razu wysyłasz pola danej oferty

**Comment by kuli-g** [comment]
@kczechowski bez "offers" dostaję INVALID_JSON. To już wolę poprzedni błąd bo JSON jest poprawny składniowo, Niech się autorzy popiszą i wyjaśnią w czym jest problem.

**Comment by kuli-g** [comment]
Problem rozwiązany, po dłuuuugim żmudnym sprawdzaniu wartości po wartości z tymi z dokumentacji wyszło że jednej sekcji w JSON nie było, gdzieś się usunęła przy przetwarzaniu tablicy w php. JSON był poprawny ale RESTAPI nie potrafiło przetworzyć danych generując niewiele mówiący błąd.
