### ISSUE TITLE
Zmiana ceny zwraca błąd ERR_OBLIGATORY_ATTRIB_NOT_SET

### ISSUE THREAD

**Issue by DamianStepniewski** [allegro/allegro-api#18]
Od dzisiaj zmiana ceny oferty przez REST API zwraca błąd ERR_OBLIGATORY_ATTRIB_NOT_SET, pomimo uzupełnienia wszystkich wymaganych parametrów przedmiotu. Sprawdzone na kilku przedmiotach z kompletnie niezwiązanych ze sobą kategorii, za każdym razem występuje ten sam błąd.
Dane zwracane na przykładzie oferty 6994769016:
`{"id":"8a1618d2-64d5-4d7a-801b-7e3f3f679033","input":{"buyNowPrice":{"amount":"300","currency":"PLN"}},"output":{"status":"ERROR","errors":[{"code":"ERR_OBLIGATORY_ATTRIB_NOT_SET","message":"ERR_OBLIGATORY_ATTRIB_NOT_SET","details":null,"path":null,"userMessage":""}]}}`

**Comment by AniaMalinowska** [comment]
Sprawdziliśmy i jest nieprawidłowość po naszej stronie: parametr o ID 22482 ('do laptopów') jest oznaczony w API jako nieobowiązkowy i dlatego można wystawić ofertę bez niego, ale tak naprawdę  jest on obowiązkowy (widać to np. w formularzu wystawiania). Przepraszamy, pracujemy nad tym.

Abyś mógł zmienić cenę, uzupełnij ten parametr metodą [DoChangeItemFields](https://allegro.pl/webapi/documentation.php/show/id,922)
Następnie możesz [zmienić cenę](https://developer.allegroapi.io/documentation/#!/default/put_offers_offerId_change_price_commands_commandId) w ramach REST API.
