### ISSUE TITLE
Mapowanie starego numeru płatności do UUID

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#1801]
Czy istnieje możliwość, za pomocą akcji REST API lub WebAPI zmapowania starego numeru karty płatności do nowego UUID?

Jeśli tak - w jaki sposób mogę tego dokonać?
Jeśli nie - czy jest w planach na najbliższą przyszłość wdrożenie takiego rozwiązania?

Ewentualnie, czy jest możliwość pobrania numeru płatności w nowym formacie do zamówienia pobranego przez WebAPI?

**Comment by PawelTaberski** [comment]
Pracujemy nad zasobem do mapowania id płatności możliwe, że już w tym tygodniu się pojawi.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski przypominam że to jest za mało. W przypadku płatności poza PayU nie ma nr płatności.
Potrzeba mapować nr transakcji z webAPI do nr transakcji w restAPI

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Przekazałem Twoją sugestię, jeśli wdrożymy również takie mapowanie poinformujemy o tym.

**Comment by solokazama** [comment]
bylaby rewelacja bo rozwiazaloby to moj problem tutaj:
https://github.com/allegro/allegro-api/issues/1557

bo rozumiem majac to mapowanie bedzie mozna poprzez RESTAPI dodac nr paczki kurierskiej do tranzakcji tak?

**takie mapowanie poprosimy!** (na okres potrzeby trzymania hybrydy).

**Comment by pokash** [comment]
Mapowanie do transakcji by się bardzo przydało, gdyż całkowicie można by było zrezygnować z WebApi przy obsłudze zamówień :) aktualnie niestety trzeba jeszcze korzystać z dziennika w WebApi, aby to zmapować numery, które są niestety niezbędne do tworzenia przesyłek Allegro InPost, paczka w ruchu. Ich API nie jest nadal kompatybilne z Rest Api Allegro. Ja moge się pochwalić, że u mnie (poza mapowaniem transakcji) całość jest już obsługiwana poprzez rest api :) i póki co (odpukać) nic się złego nie dzieje :) powiem nawet, że wymiana informacji jest szybsza niż w starym API, chodź może to dziwić patrząc na niektóre metody :)

Pozdrawiam,
Łukasz

**Comment by PawelTaberski** [comment]
Przekazałem, że ta funkcjonalność jest oczekiwana przez większą liczbę użytkowników. Jeśli otrzymam informacje o wdrożeniu takiego mapowania to oczywiście poinformujemy o tym w dedykowanym komunikacie.

**Comment by MartaNowaczyk** [comment]
Udostępniliśmy mapowanie ID płatności - https://github.com/allegro/allegro-api/issues/1878
