### ISSUE TITLE
Problem z wyświetleniem zakończonych ofert

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#1802]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od początku mam problem z wyświetleniem zakończonych ofert, od początku wyświetla mi zakończone po kilku odświeżeniach.  Problem ten nie występuje przy pobieraniu listy aktywnych ofert. 

{"errors":[{"code":"UpstreamServiceFailedException","message":"Service unavailable. Please try again later.","details":null,"path":null,"userMessage":"Błąd serwera. Proszę spróbować później."}]}

**Comment by PawelTaberski** [comment]
Jakie dokładnie zapytanie wysyłasz? Bo rozumiem, że problem jest na zasobie sale/offers.
Przetestowałem na zapytaniu /sale/offers?publication.status=ENDED
i zasób działa poprawnie.

**Comment by Rnapzsih** [comment]
@PawelTaberski  - Zgodnie z informacjami z dokumentacji zapytanie wygląda tak: 
/offers/listing?seller.id=".$iUser.'&searchMode=CLOSED&offset='.$iOffset.'&limit=100&sort=name

**Comment by PawelTaberski** [comment]
@Rnapzsih przetestowałem na przykładowych danych i działa prawidłowo:
/offers/listing?seller.id=5xxxx&searchMode=CLOSED&offset=5&limit=100&sort=name
Wywoływałem wielokrotnie, ale nie udało mi się powtórzyć błędu. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z trace-id i responsa. Zaznacz, że dane są potrzebne do ticketa numer 1802 na GitHub-ie.
