### ISSUE TITLE
Zamówienia na pozostają na statusie Płatność rozpoczęta

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#1803]
Wszystkie nowe zamówienia które złożyłem na Sandboxie zostają w statusie Płatność rozpoczęta. Po dość długiej przerwie wróciłem do Allegro i chciałem przetestować zmiany na obsłudze zamówień, więc złożyłem parę zamówień i czekam aż się pobiorą, ale do tego nie dochodzi. Sprawdzam w zamówieniach w panelu i widze że na wszystkich zamówieniach ( przynajmniej te od wczoraj (10.06.2019) płatności nie są zakończone, nawet pomimo wybrania płatności przy odbiorze. Dodatkowo chciałem rozpocząć płatność na kocie z którego dokonywałem zakupu ale wyświetla się komunikat że płatność rozpoczęta.

**Comment by PawelTaberski** [comment]
Możliwe, że wczoraj był jakiś problem na środowisku testowym z symulatorem płatności. Sprawdziłem teraz i wszystko działa prawidłowo. Sprawdź proszę czy u Ciebie dalej jest z tym problem.

**Comment by AssAssIn1909** [comment]
Dziękuje, wszystko wróciło do normy
