### ISSUE TITLE
Could not change offer publication status => HTTP 404 Not Found

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1804]
Zaraz mnie szlag trafi... Chcę wystawić jedną aukcję, aby coś przetestować i nie da się:
https://gist.github.com/PhotoSoft/be770401749b7809831f507d8b8b4101

Współczuję swoim Klientom, którzy muszą wystawiać kilkaset aukcji dziennie.

**Kiedy w końcu coś z tym zrobicie?** To już przechodzi ludzkie pojęcie. Od ponad tygodnia nie można normalnie korzystać z API!

W momencie wysłania tego posta nadal zwraca cały czas ten sam błąd.

**Comment by PawelTaberski** [comment]
Na jakim koncie wystawiłeś ten draft i próbujesz go opublikować?
Przetestowałem na nowej ofercie i wydaje się, ze wszystko działa prawidłowo.

**Comment by mindc** [comment]
@PhotoSoft @PawelTaberski 
To zależy... 
Przy obciążonym Allegro zmiana statusów trochę trwa. 
Zmiana statusów przy wystawianiu następuje tak: `INACTIVE` => `ACTIVATING` => `ACTIVE`
To co zauważyłem wielokrotnie, to że w momencie zmiany statusu, istnieje pewien okres czasu (krótszy, bądź dłuższy) że oferta znika z systemu, czyli tak jak pisze @PhotoSoft `HTTP 404`

Zastanawiam się tylko, czy to jest _feature_ czy _bug_

**Comment by PawelTaberski** [comment]
Tak w zależności od długości zadań na kolejce może wystąpić taka sytuacja przy aktywacji oferty.
