### ISSUE TITLE
Losowy brak publikacji oferty

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#1805]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
Dzień dobry,

Wystawiam masowo wiele aukcji w takim samym schemacie/mechanizmie i niestety raz aukcja jest u Państwa widoczna, raz nie - dzieje się tak zupełnie losowo.

Przykład, data: 2019-06-11 8:13:42, trace id: c01d912f0f00fc81, aukcja: 8192883120. Oferta dodała się bez żadnego błędu i nadal nie jest widnoczna.

Kolejna aukcja: 8189301339, próba wystawienia wczoraj ok 9 rano i nadal nic.

Wysłałem również zgłoszenie mailowe (nr 05640291)

Prośba o podpowiedź.

**Comment by vitapak** [comment]
Krótka informacja:

Dnia 2019-06-11 8:59:19 wysłałem żądanie do Waszego serwisu ws. publikacji oferty.
task publikacji: 204b5eaa-7544-4401-964a-ba6dff6311c5, odpowiedź 201 Created, trace-id: e23b36c7379ceff.

Oferta oczywiście od 9 rano się nie opublikowała.

Sprawdzając status taska na podstawie zasobu GET _/sale/offer-publication-commands/{commandId}/tasks_ dostaję następującą odpowiedź:

[code] => COMMAND_ACCESS_FORBIDDEN
[userMessage] => Nie masz uprawnień do tego zlecenia

To jakieś nieporozumienie...

Proszę o wyjaśnienia.

**Comment by PawelTaberski** [comment]
Komunikat COMMAND_ACCESS_FORBIDDEN pojawił się bo inny użytkownik musiał wcześniej użyć dokładnie tego samego UUID-a pod którym takie zadanie zapisało się wcześniej. Jest niezwykle mała szansa na taką sytuację, ale morze się zdarzyć. Co do publikacji ofert jeszcze nie otrzymałem danych, które wysłałeś mailowo. Powiedz mi co otrzymujesz w odpowiedzi w zasobie GET /sale/offer-publication-commands/{commandId}/tasks w zadaniach w których dane oferty się nie opublikowały?

**Comment by vitapak** [comment]
204b5eaa-7544-4401-964a-ba6dff6311c5 - COMMAND_ACCESS_FORBIDDEN
539300d8-cf05-4008-8719-afc871637476 - COMMAND_ACCESS_FORBIDDEN
f11a3e71-e674-4bea-bcc6-995ef4e758ac - COMMAND_ACCESS_FORBIDDEN
b3ebf6d1-7461-4179-9247-bf21963d8892 - COMMAND_ACCESS_FORBIDDEN
bb378f28-47f3-4150-9682-784ba3bf63db - COMMAND_ACCESS_FORBIDDEN
0b35c156-c6cc-4848-b299-c1e6ef98405d - COMMAND_ACCESS_FORBIDDEN
696d910b-5cc7-403b-9c1f-c86b5db00166 - COMMAND_ACCESS_FORBIDDEN

Zawsze ten sam komunikat...

**Comment by vitapak** [comment]
publikacja oferty 2019-06-12 9:34:49: 

347e1b2e-900e-429d-b53b-23aeae6aaa4c, COMMAND_ACCESS_FORBIDDEN

Tych ofert jest mnóstwo. Podejrzewam, że macie jakiś problem z kolejkami, że uuidy się nakładają różnych użytkowników i pewną pulę nie przepuszczacie dalej. Taka sytuacja nie powinna mieć miejsa.

**Comment by PawelTaberski** [comment]
Taki błąd nie powinien pojawiać się tak często. Zgłosiłem Twój przypadek do odpowiedniego zespołu, zweryfikujemy co jest tego powodem. Prośba o cierpliwość.
