### ISSUE TITLE
Usuwanie zakończonej oferty

### ISSUE THREAD

**Issue by masztan** [allegro/allegro-api#1807]
Czy jest możliwe usunięcie zakończonej oferty tak jak usunięcie draftu?

**Comment by PawelTaberski** [comment]
Nie tylko drafty można usuwać, bo ofertę możesz aktywować pod tym samym id (nie dotyczy licytacji).

**Comment by masztan** [comment]
> 
> 
> Nie tylko drafty można usuwać, bo ofertę możesz aktywować pod tym samym id (nie dotyczy licytacji).

Nie tylko drafty można usuwać? Czyli co jeszcze można usuwać?

**Comment by PawelTaberski** [comment]
Sorka dokładnie chodziło o bramkę numer dwa czyli, że tylko drafty można usuwać :-)
