### ISSUE TITLE
Alternatywa dla doAddToBlackList w rest api

### ISSUE THREAD

**Issue by mbednarski** [allegro/allegro-api#1808]
W rozipisce jest napisane, że metoda **doAddToBlackList** zostanie wyłączona we wrześniu, brak jest informacji o dodaniu jej w rest api. Czy to oznacza, że

a) blackista zostanie usunięta z allegro w ogóle
b) blacklista zostanie ale nie będzie można jej używać z poziomu api

?

**Comment by PawelTaberski** [comment]
W REST API zostanie wdrożony odpowiedni zasób do czarnej listy, jeszcze nie znamy dokładnego terminu.
