### ISSUE TITLE
Zmiana ilości sztuk przed zakończeniem zamówienia

### ISSUE THREAD

**Issue by piotrek1555** [allegro/allegro-api#1809]
Czy jest możliwość, że ilość kupionych sztuk zmieni się przy pobieraniu szczegółów zamówienia jeśli zamówienie nie jest jeszcze w statusie READY_FOR_PROCESSING ?
W interfejsie po stronie użytkownika nie bardzo widzę możliwość takiej zmiany. W dokumentacji jest informacja, że mogą zmienić się dane, aż do czasu zakończenia płatności. Czy informacja ta dotyczy jedynie płatności i dostawy?

**Comment by PawelTaberski** [comment]
User może kupić dwukrotnie w odstępach ten sam produkt i następnie opłacić oba te produkty za jednym razem, wtedy to będą 2 zdarzenia BOUGHT, 3 zdarzenia FILLED_IN i 1 READY dla takiej transakcji.
