### ISSUE TITLE
Nie Udało się !. Kod Błędu: ERR_IP_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#181]
Witam

Przez pomyłkę ustawiłem złe limity na API i wywaliło i w/w błąd na produkcyjnym API, jak usunąć ten limit ?

Jak wygląda procedura zdięcia blokady ?

**Comment by LukaszKorek** [comment]
W takim wypadku musi Pan postępować zgodnie z instrukcją: https://allegro.pl/webapi/faq.php#faq_1
czyli:
Aby zdjąć blokadę, ustaw serwer proxy na swojej maszynie z zablokowanym IP i z tego serwera, wypełnij CAPTCHA pod adresem: http://allegro.pl/blocked/index.php.

**Comment by anih** [comment]
Czy jest możliwość podniesienie tego limitu dla konkretnych aplikacji?
