### ISSUE TITLE
Nie możemy wyświetlić strony

### ISSUE THREAD

**Issue by Olafejs** [allegro/allegro-api#1810]
Wyrzuca błąd: Nie możemy wyświetlić strony
Numer błędu: db6fe1ecdf2348fb

Adres: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=XXX&redirect_uri=XXX

client_id biorę z https://allegro.pl/login/user
redirect_uri biore z https://apps.developer.allegro.pl/ kopiując adres z kolumny Adresy przekierowań

Czy uwierzytelnianie działa ?

**Comment by Tofik1987** [comment]
Tu masz wszystko opisane
https://developer.allegro.pl/auth/#app

Client ID masz na https://apps.developer.allegro.pl/

**Comment by Olafejs** [comment]
Brałem client_id z konta Allegro a nie z Dev. Do zamknięcia.
