### ISSUE TITLE
Problem z wznowieniem aukcji

### ISSUE THREAD

**Issue by Tofik1987** [allegro/allegro-api#1811]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**
Próbuję wznowić aukcję 7538980499 przez rest API , sprawdzając stan operacji dostaję "HTTP 404 Not Found" , próbując wznowić aukcję z poziomu allegro dostaję "Coś poszło nie tak. Nie udało nam się zebrać danych potrzebnych do wyświetlenia strony. Poczekaj chwilę i spróbuj odświeżyć stronę."

PUT
REQUEST
[url] => https://api.allegro.pl/sale/offer-publication-commands/9a59116c-698c-42f0-9993-b534863dc1f6
[method] => PUT
[headers] => Accept: application/vnd.allegro.public.v1+json
	Content-Type: application/vnd.allegro.public.v1+json
	Authorization: Bearer[]
[body] => {"publication":{"action":"ACTIVATE","scheduledFor":"2019-06-11T19:21:44Z"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"7538980499"}]}]}

RESPONSE
[code] => 201
[headers] => HTTP/1.1 201 Created
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 93f83e7935bb7d95
Date: Tue, 11 Jun 2019 17:16:45 GMT
X-RateLimit-Remaining: 9000
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
[body] => {"id":"9a59116c-698c-42f0-9993-b534863dc1f6","taskCount":{"total":0,"success":0,"failed":0}}

GET
REQUEST
[url] => https://api.allegro.pl/sale/offer-publication-commands/9a59116c-698c-42f0-9993-b534863dc1f6/tasks
[method] => GET
[headers] => Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer[]
[body] => null

RESPONSE
[code] => 200
[headers] => HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: db69f28d45b46cfd
Date: Tue, 11 Jun 2019 17:24:49 GMT
X-RateLimit-Remaining: 8999
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000
[body] => {"tasks":[{"offer":{"id":"7538980499"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2019-06-11T17:16:45.018Z","finishedAt":"2019-06-11T17:16:45.385Z","field":"publication","errors":[{"code":"NotFoundException","message":"HTTP 404 Not Found","details":"NotFoundException","path":null,"userMessage":null}]}]}

**Comment by PawelTaberski** [comment]
Z tego co widzę oferta zakończyła się we wrześniu zeszłego roku, co oznacza, że już dawno trafiła do archiwum i nie można już jej wznowić.

**Comment by Tofik1987** [comment]
Oferta przed chwilą nagle zniknęła, skoro twierdzi Pan że "już dawno trafiła do archiwum" dlaczego zwracała ją metoda /sale/offers oraz była w zakładce "Moje oferty" ?

**Comment by PawelTaberski** [comment]
Nie powinna być ona widoczna w zasobach, czy w dalszym ciągu widzisz ją w responsie? Możliwe że jakieś dane się cache-owały i po odświeżeniu nie była już widoczna.

**Comment by Tofik1987** [comment]
Pisząc poprzednią wiadomość nie byłą widoczna , teraz znów się pojawia,
Sprawdziłem oferty zwracane zasobem  /sale/offers  z parametrem publication.status ustawionym na ENDED dla poniższych ofert wywołanie /sale/offers/{ID} zwraca
{"errors":[{"code":"NOT_FOUND", "message":"Not Found","details":null,"path": "/sale/offers/{ID}", "userMessage":null}]}
pojawiają się również one w zakładce "Moje oferty" po kliknięciu w ofertę przekierowuje na https://archiwum.allegro.pl/

7632038417
7623210579
7610648653
7606784778
7598529188
7580715113
7570433116
7559802696
7556718574
7538980499
7490956886
7464042257

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście u usera są widoczne oferty archiwalne, sprawę zgłosiłem do odpowiedniego zespołu, prośba o cierpliwość.
