### ISSUE TITLE
Błąd logowania do REST

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1813]
Przy próbie logowania do aplikacji REST, otrzymuję komunikat 

Nie możemy wyświetlić strony
Numer błędu: 571185430a902d8d

Proszę o pomoc co się dokładnie dzieje.
Sławek

**Comment by mindc** [comment]
@qshop123 
to działająca do tej pory aplikacja REST, czy testy nowej?

**Comment by qshop123** [comment]
Logowanie do aplikacji, już działała od jakiegoś czasu, od pół roku albo więcej. 
Założenie nowej nic nie daje, występuje ten sam błąd.

**Comment by PawelTaberski** [comment]
Wygląda to na błąd z podanym adresem przekierowania jesteś pewny, że podajesz taki sam jak przy rejestracji aplikacji?

**Comment by qshop123** [comment]
Jestem pewny, przed chwilą raz jeszcze sprawdziłem.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne zapytanie jaki wysyłasz, sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1813 na GitHub-ie.

**Comment by qshop123** [comment]
Proszę o pilną odpowiedź na moje zgłoszenie, dziękuję.

**Comment by PawelTaberski** [comment]
@qshop123 Widzę, że nadwymiarowo przesyłasz api-key prawidłowe zapytanie powinno wyglądać tak jak w naszej dokumentacji:
`https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21...6be&redirect_uri=http://exemplary.redirect.uri `
Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#user).

**Comment by qshop123** [comment]
Witam  Wysłałem zapytanie bez api-key i jest ten sam błąd.   Sławek Dnia 21 czerwca 2019 10:55 PawelTaberski &lt;notifications@github.com&gt; napisał(a):  github.com @qshop123  Widzę, że nadwymiarowo przesyłasz api-key prawidłowe zapytanie powinno wyglądać tak jak w naszej dokumentacji:    allegro.pl    Więcej informacji na ten temat znajdziesz w  developer.allegro.pl naszym poradniku .  —  You are receiving this because you were mentioned.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by PawelTaberski** [comment]
Teraz zauważyłem wprowadziłeś także niepełny Client ID zakończyłeś na ....5 a dalej masz jeszcze 9 znaków. Jak wlepisz pełny to sprawdziłem powinno być ok.
