### ISSUE TITLE
Pobranie oferty i wystawienie jej za pomocą otrzymanych danych

### ISSUE THREAD

**Issue by arasowsky** [allegro/allegro-api#1814]
Czy jest możliwe pobranie szczegółów oferty z zasobu /sale/offers/{ID} i wystawienie nowej aukcji z parametrami otrzymanej odpowiedzi ze szczegółów?

Próbuję to zrobić, zmieniając w otrzymanych danych status = INACTIVE, ale pojawia się błąd An error has been occoured.

**Comment by rtnet-pl** [comment]
Tak, musisz tylko usunąć z JSONA offer.id. Poza tym jeśli oferta zawiera braki (np. jakiś parametr kiedyś nie był wymagany, a teraz już jest) to będzie error

**Comment by arasowsky** [comment]
Zrobiłem tak, że pole id zostało usunięte, natomiast błąd nadal się pokazuje.

**Comment by PawelTaberski** [comment]
Podeślij proszę ofertę z jaką masz problem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1814 na GitHub-ie.

**Comment by kaki1979** [comment]
@arasowsky 
Miałem ten sam problem , jedyny sposob dzialajacy na 100%, to stworzenie Drafta tylko z nazwą oraz kategorią (wymagane), a później przekopiowanie wszystkich pozostałych parametrów i zaktualizowanie drafta (PUT), Status nie ma znaczenia, i tak inną metodą trzeba opublikować nową ofertę.

**Comment by rtnet-pl** [comment]
Wyedytowałem mój wcześniejszy post, z oferty trzeba usunąć więcej informacji niż sam ID.

**Comment by arasowsky** [comment]
Niestety nie działa ani usunięcie wyżej wymienionych danych z oferty, ani dodanie draftu wyłącznie z nazwą oferta oraz id kategorii.

Może jest jakiś problem na koncie?

**Comment by rtnet-pl** [comment]
A wrzuć całego JSONA który wysyłasz

**Comment by arasowsky** [comment]
> 
> 
> A wrzuć całego JSONA który wysyłasz

Podałem wyżej w edytowanym poście. W cURL POST zostaje wysłany w ten sposób:
			`curl_setopt($ch, CURLOPT_POST, true);
			curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));`

**Comment by kaki1979** [comment]
Może to głupio zabrzmi, ale http_build_query tworzy parametry, a nie JSON'a z danych, 
w POSTie masz wysłać JSON'a, 

niestety nie podales calego drzewa wykonywanych operacji i dlatego tego nie widać, ale tak 'po łebkach' to ten twój Curl jest lekko wybrakowany (brak chociazby Content-Type i Accept-Content-Type).
