### ISSUE TITLE
Róźne ceny po zmianie przez API

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#1815]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
-  za pomocą api zmieniłem cenę
- w panelu widzimy zmienioną cenę 
- na aukcji pozostaje stara

![obraz](https://user-images.githubusercontent.com/30370747/59355852-11e5ec80-8d28-11e9-871d-dea992802048.png)

![obraz](https://user-images.githubusercontent.com/30370747/59355890-20cc9f00-8d28-11e9-9da0-47ec4d381313.png)

aukcja numer: 7373340170

nie wiem czy to tak ma być ale po 40 min zmieniło się na aukcji...

**Comment by PawelTaberski** [comment]
Widzę, że cena na ofercie już się zmieniła w zależności od ilości zadań na kolejce każda zmiana na ofercie może zająć do godziny czasu. Ponadto przy sprawdzaniu ceny na froncie sprawdziłeś może czy nie cachowała się tobie stara cena, wyczyściłeś może ciasteczka?

**Comment by PiotrFerenc** [comment]
W panelu była inna i na aukcji też  inna. Tutaj raczej nie chodzi o kolejkę. Sprawdzałem status taska i nawet w innej przeglądarce. W API oraz panelu było dobrze natomiast w aukcji był błąd. Co w sytuacji jak będzie 1000zł różnicy?

**Comment by PawelTaberski** [comment]
Proszę pamiętać, że tak jak pisałem wcześniej każda zmiana na ofercie może się procesować do godziny czasu, jeśli zauważy Pan przekroczenie tego czasu to proszę nam zgłosić taką sytuacje. Potrzebowalibyśmy wtedy trace-id zadania zmiany ceny i daty kiedy zauważył Pan zmianę ceny.

**Comment by PiotrFerenc** [comment]
Rozumiem ale tak jak pisałem zmiany zastosowały się nie wszędzie. W API oraz panelu jest OK natomiast na aukcji nie. Proszę powiedzieć  co w sytuacji jak będzie 1000zł różnicy?

**Comment by PawelTaberski** [comment]
Tak, jak pisałem zmiana musi się przeprocesować, ponadto nie ma możliwości zmiany takiej ceny o ponad tysiąc złotych jednym zapytaniem. Więcej na temat zasad zmiany ceny [znajdziesz w pomocy](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz).
