### ISSUE TITLE
Nowy wygląd listy zamówień - Gdzie jest ID zamówienia???

### ISSUE THREAD

**Issue by DominikKomenda** [allegro/allegro-api#1816]
Nowy wygląd listy zamówień. Dużo danych na wierzchu, be konieczności klikania na plus. Ale gdzie jest numer identyfikacyjny zamówienia?
W poprzednim layout'cie był chociaż widoczny w nagłówku sekcji, jak się podejrzało inspektorem, a teraz co? Znalazłem go w anchor'ze podpiętym do "Nadaj przesyłkę" i ... tylko tam. A jeśli tego nie ma? Szukaj wiatru w polu.

Wyobraźmy sobie sytuację:

Klient podchodzi do zamówienia, wybiera produkty, wybiera dostawę, wybiera płatność i coś mu nie wychodzi.
Następnie robi identyczne zamówienie z innego urządzenia i przeprowadza procedurę do końca. Teraz w systemie mam dwa identyczne zamówienia. Różnią się jedynie ID. Na liście zamówień w Allegro też mam dwa zamówienia, różnią się statusem płatności. Nigdzie nie ma ID zamówienia. 
I teraz co? Jak mam określić, które zamównienie anluować, a które zrealizować? Mam rzucać monetą?

**Comment by PawelTaberski** [comment]
Możesz je zidentyfikować po danych z frontu takich jak identyfikator płatności, po dacie itp. Więcej na temat zarządzania zamówieniami znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/). No i oczywiście po statusie jeśli jedno jest opłacone to tylko ono będzie miała status READY_FOR_PROCESSING .

**Comment by pkrzemo** [comment]
> Możesz je zidentyfikować po danych z frontu takich jak identyfikator płatności, po dacie itp. Więcej na temat zarządzania zamówieniami znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/). No i oczywiście po statusie jeśli jedno jest opłacone to tylko ono będzie miała status READY_FOR_PROCESSING .

A dlaczego nie możecie po prostu pokazywać tego ID?
SOA nr 5: Nie chodzi o to by użytkownik nie mógł... chodzi o to by  mógł, ale w znoju!
;-)

**Comment by DominikKomenda** [comment]
> 
> 
> Możesz je zidentyfikować po danych z frontu takich jak identyfikator płatności, po dacie itp. 

Nie mapujemy id płatności w naszym systemie. Mnożenie pól identyfikujących element powoduje, że ID przestają być ID.
>
>
>No i oczywiście po statusie jeśli jedno jest opłacone to tylko ono będzie miała status READY_FOR_PROCESSING .

To, że jedno jest opłacone to ja wiem, tylko bez ID nie wiem które.


> 
> A dlaczego nie możecie po prostu pokazywać tego ID?

O to to. To jest bardzo dobre pytanie.

**Comment by PawelTaberski** [comment]
@DominikKomenda Powiedz mi, czy dobrze Ciebie rozumiem chciałbyś aby id checkoutForm pojawiło się na froncie userowi w zakładce Moje zakupy, aby zidentyfikować takie sytuacje, gdy user nieświadomie kupuje dwukrotnie i kontaktuje się w tej sprawie ze sprzedawcą tak?

**Comment by DominikKomenda** [comment]
Nie.
Użytkownicy generują zdarzenia, które rejestruje system nawet o tym nie wiedząc. 
Im te ID są do niczego nie potrzebne. Co innego sprzedający.

Zacząłem opisywać problem, ale zajęło mi to trochę za dużo tekstu, więc napiszę wprost.

Marzy mi się id zamówienia na widoku listy zamówień. 

Dokładniej o tu: Moje konto > Moja sprzedaż > Licytacje i Kup teraz > Zamówienia

Pozwoliłem sobie dołączyć wizualizację, dla jasności przekazu. 
![allegro_orders](https://user-images.githubusercontent.com/51774939/59510606-69b15e80-8eb4-11e9-968b-0e9274a24f66.jpg)

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem Twoją sugestię. Jeśli zdecydujemy się wdrożyć taką zmianę to poinformujemy o tym w dedykowanym komunikacie.
