### ISSUE TITLE
Jak mogę sprawdzić która aukcja została zalicytowana?

### ISSUE THREAD

**Issue by MarosR** [allegro/allegro-api#1817]
Jak mogę sprawdzić która aukcja została zalicytowana? Dziennik zdarzeń już tego nie pokazuje.

**Comment by PawelTaberski** [comment]
Obecnie w REST API nie otrzymasz informacji o podbiciu ceny, jedynie o kupnie. Pracujemy nad odpowiednimi zasobami jak tylko będą dostępne poinformujemy o tym.
