### ISSUE TITLE
FORBIDDEN You do not have permission to request this resource

### ISSUE THREAD

**Issue by myszaq99** [allegro/allegro-api#1818]
Witam,
mam problem z wywołaniem:
https://api.allegro.pl/after-sales-service-conditions/implied-warranties?seller.id=7163008
Dostaję błąd: You do not have permission to request this resource

W zgłoszeniu 05664750 przesłałem request.
Proszę o pomoc

**Comment by PawelTaberski** [comment]
Jesteś pewny, że masz token na właśnie na tego użytkownika? Bo możesz pobrać tylko warunki przypisane do konta na którego masz token. Pamiętaj, że tokeny są w technologii JWT i można je rozkodować i tam znajduje się informacja o id usera na którego masz token.

**Comment by myszaq99** [comment]
jak rozkodowuję token to widzę tylko client_id i on się zgadza

**Comment by PawelTaberski** [comment]
Jeśli widzisz tylko client_id oznacza, że musisz korzystać z autoryzacji typu client credentials ona służy tylko do pobrania danych publicznych jak metody dostawy itp. Ten typ autoryzacji nie ma kontekstu usera, dlatego nie pobierzesz nim danych przypisanych do danego użytkownika. W tym celu musisz skorzystać z code, albo device flow.
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/).

**Comment by myszaq99** [comment]
Zgadza się, Przeoczyłem to.
Dziękuję
