### ISSUE TITLE
[REST] Dane kontrahenta zwracane w checkout-forms

### ISSUE THREAD

**Issue by mmgithubpl** [allegro/allegro-api#1819]
Kiedy zostanie udostepnione zwracane dane uzytkownika? imie/nazwisko/telefon/adres/kod/miasto/kraj z zakladki dane kontahenta. 
Obecnie zapytanie https://api.allegro.pl/order/checkout-forms/{id} zwraca tylko dane do wysylki.

**Comment by PawelTaberski** [comment]
Pracujemy nad rozbudową sekcji buyer, jak tylko wdrożymy zmianę to poinformujemy o tym w dedykowanym komunikacie.

**Comment by koszar93** [comment]
Czy jest możliwość rozbicia adresu na numer domu i mieszkania? Jeśli nie, to jak radzicie sobie z integracja np. z DHL, gdzie wymagane jest wpisanie numeru domu? :) Wpisujcie pusty zbak/kropkę?

**Comment by solokazama** [comment]
> Czy jest możliwość rozbicia adresu na numer domu i mieszkania? Jeśli nie, to jak radzicie sobie z integracja np. z DHL, gdzie wymagane jest wpisanie numeru domu? :) Wpisujcie pusty zbak/kropkę?

dokladnie, kropka jest uniwersalna;)

**Comment by neldh** [comment]
@up : dopoki ktos nie waliduje tego. Można też parsować wyrażeniem regularnym (tak wiem, że nie jest to piękne wyjście, ale lepszy rydz niż nic)

**Comment by Onixarts** [comment]
> jak radzicie sobie z integracja np. z DHL, gdzie wymagane jest wpisanie numeru domu? :)

Parsujemy adres i wyciągamy z niego dane. Kilka linii kodu i działa zadziwiająco dobrze od wielu lat.

**Comment by mmgithubpl** [comment]
https://developer.allegro.pl/schedule/
Chcialem potwierdzic czy "Dodamy następujące zasoby w REST API z sekcji Dane użytkownika" na liscie harmonogramu dotycza wlasnie metody checkout-forms?

**Comment by PawelTaberski** [comment]
Dotyczy to nowego zasobu, jednakże jego wdrożenie może się opóźnić.

**Comment by lukasnet** [comment]
Podłącze się pod temat i zapytam, co to jest 'personalIdentity'??? w poradniku nie ma opisu dla tego pola

**Comment by PawelTaberski** [comment]
Jest to numer PESEL.

**Comment by mmgithubpl** [comment]
@PawelTaberski : witam / chcialbym wrocic do tematu sekcji danych kupujacego? na jakim jest to etapie?

**Comment by PrzemyslawLukanowski** [comment]
@mmgithubpl  Pracujemy nad tym, w najbliższym czasie zmiany powinny zostac wdrożone.

**Comment by romigrabarz** [comment]
Chciałbym zgłosić sugestię dodania jednak **nr domu/mieszkania** do danych adresowych zamówienia. Przy integracji z różnymi systemami ERP te dane są zwykle w osobnych polach w bazie danych. Parsowanie adresu mimo wszystko może spowodować błędy. Jaki algorytm przewidzieć na sprasowanie takich adresów na ulice, nr domu, nr mieszkania:
1. Dywizjonu 303
2. Dywizjonu 303 45/6
3. Konstytucji 3 Maja 12
4. 22 Stycznia 5/8
Jeśli allegro nie chce rozbić adresu to proszę o algorytm na poradzenie sobie z w/w nazwami ulic.

**Comment by TimothyKoval** [comment]
`\d+(\D)(\d+)$`

**Comment by Onixarts** [comment]
To proste, jeśli są 2 liczby przedzielone słowem to pierwsza jest częścią nazwy ulicy. Jeśli w ostatniej występuje / to wiadomo że chodzi o numer mieszkania.
