### ISSUE TITLE
Błędny adres URL

### ISSUE THREAD

**Issue by polo195pl** [allegro/allegro-api#182]
Witam mam problem z rejestracją aplikacji. Wyskakuje 'Adresy przekierowań powinny być poprawnymi adresami URL.' Pomimo że adres jest poprawny xD
![image](https://user-images.githubusercontent.com/22961693/39424792-a2e5b8ec-4c78-11e8-8fea-a5e6cb585cb8.png)

**Comment by LukaszKorek** [comment]
Tej domeny nie rekomendujemy jako adres URI do przekierowań. Ze względów bezpieczeństwa nie jest możliwe wprowadzenie adresów dowolnych domen dlatego proponuję skorzystanie z adresu w ramach innej domeny.

**Comment by TimothyKoval** [comment]
Aż mnie zżera ciekawość; co tld ma wspólnego z bezpieczeństwem?

**Comment by polo195pl** [comment]
@LukaszKorek kwestie bezpieczeństwa? Jaja sobie robicie? Dowiedzcie najpierw się jak rejestruje się domeny .eco a później się wypowiadajcie na temat bezpieczeństwa. Nawiasem mówiąc co tld ma wspólnego z bezpieczeństwem? Ja odpowiem KOMPLETNIE NIC. Dodatkowo w regulaminie **nie ma nic na ten temat.**

**Comment by damadorPL** [comment]
technicznie zapytam czy domeny w .pl ale znakami spoza ascii tez uwazacie za niebezpieczne ?

**Comment by polo195pl** [comment]
@LukaszKorek i jak?

**Comment by LukaszKorek** [comment]
@polo195pl W dalszym ciągu pracujemy nad rozwiązaniem problemu. Proszę jeszcze o trochę cierpliwości. Wkrótce dam znać.

**Comment by PWCH** [comment]
@LukaszKorek domena z rozszerzeniem .shop też jest rozpoznawana jako niepoprawny adres URL.

![image](https://user-images.githubusercontent.com/23063264/39955759-18dab060-55d5-11e8-8036-fff69793541e.png)

**Comment by LukaszKorek** [comment]
@PWCH tutaj podobnie, sprawę zweryfikujemy.

**Comment by polo195pl** [comment]
@LukaszKorek i jak ;) od 30 kwietnia udało się załatwić coś w tej sprawie?

**Comment by LukaszKorek** [comment]
Sprawę wyjaśniliśmy i rozwiązaliśmy. Problem nie powinien już występować.

**Comment by polo195pl** [comment]
Sprawdzę i dam znać
