### ISSUE TITLE
Początki z REST API

### ISSUE THREAD

**Issue by mleplawy** [allegro/allegro-api#1820]
Zaczynam przygodę z REST API wczesniej uzywałem WebAPI korzystam z biblioteki https://github.com/Wiatrogon/php-allegro-rest-api
chciałem zmienic cenę produktu w akcji za pomocą kodu
`$response=$api->offers(8198330586)->commands()->change_price(intval("1400"));`

ale zwracami i cały czas blad
`{"errors":[{"code":"JsonMappingException","message":"Can not construct instance of pl.allegro.offercore.service.common.msg.command.ChangePriceMessage: no int/Int-argument constructor/factory method to deserialize from Number value (1400)\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@4d1fca34; line: 1, column: 1]","details":"JsonMappingException","path":null,"userMessage":null}]}`

**Comment by solokazama** [comment]
powinienes podac (z tego co widze w w/w klasie), potrzebna dla metody rest strukture jako tablica (zamiast tylko wartosci - tutaj 1400):

$data = array(
					'input' => array(
							'buyNowPrice' => array(
									'amount' => 1400,
									'currency' => 'PLN'
							),
					),
			);

$response=$api->offers(8198330586)->commands()->change_price($data);

**Comment by mleplawy** [comment]
dzięki pomogło:)
a wiesz może jak zakończyć aukcje bo chyba nie offer-publication-commands?

**Comment by PawelTaberski** [comment]
Również zasobem o jakim wspominasz, podajesz:
```
    "publication": {
        "action": "END",
```
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

**Comment by mleplawy** [comment]
próbowałem ale mam problem:
`$data2=array (
  'publication' => 
  array (
    'action' => 'END',
  ),
  'offerCriteria' => 
  array (
    0 => 
    array (
      'offers' => 
      array (
        0 => 
        array (
          'id' => '7276377308',
        ),
      ),
      'type' => 'CONTAINS_OFFERS',
    ),
  ),
);
echo "<br/>";
$response2 = $api->offers(7952806507)->commands()->offer_publication($data2);`

daje mi błąd
`{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Function is not available. Contact the author of the application."}]}`

**Comment by mleplawy** [comment]
wydaje mi sie ze zle wywołuję metodę ale nie wiem co jest nie tak po próbowałe różenież nie przekazywać id oferty w parametrze i jest to samo
`$api->offers()->commands()->offer_publication($data2);`

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a jakiego ostatecznie wysyłasz sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1820 na GitHub-ie.

**Comment by mleplawy** [comment]
Nie sządze aby był sens zakładać ticket bo mój problem nie polega na błędzie allegro tylko mojej interpretacji biblioteki dlatego ponawiam pytanie `$data2=array ( 'publication' => array ( 'action' => 'END', ), 'offerCriteria' => array ( 0 => array ( 'offers' => array ( 0 => array ( 'id' => '7276377308', ), ), 'type' => 'CONTAINS_OFFERS', ), ), ); 
$api->offers()->commands()->offer_publication($data2);`

daje
`{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Function is not available. Contact the author of the application."}]}`

**Comment by PawelTaberski** [comment]
My nie prowadzimy wsparcia w kodowaniu, ale może ktoś z forum napotkał już na taki przypadek i Tobie coś doradzi.
