### ISSUE TITLE
Brak możliwości sortowania po popularności

### ISSUE THREAD

**Issue by alikoli** [allegro/allegro-api#1821]
Endpoint /offers/listing nie pozwala na sortowanie wg popularności. Miał to być odpowiednik wyszukiwania ofert a tam jest taka możliwość. Kiedy zostanie dodana?

**Comment by PawelTaberski** [comment]
Ten zasób ma możliwość sortowania po popularności:
```
sort	
string
Default: "relevance"
Enum:..."-popularity" .....
Search results sorting order. + or no prefix in the value means ascending order. - prefix means descending order.
```
Opis możliwości tego zasobu znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListing).
