### ISSUE TITLE
Kompletnie niejasny opis błędu. Możecie nauczyć stażystów poprawnego raportowania błędów ?

### ISSUE THREAD

**Issue by haloween** [allegro/allegro-api#1822]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
PAYLOAD:

{"publication": {"action": "END"}, "offerCriteria": [{"offers": [{"id": "8179632954"}], "type": "CONTAINS_OFFERS"}]}

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/0a8f8dd4-05b2-4acb-9912-d33b242b02d5","userMessage":null}]}

Nie mam zielonego pojęcia co jest nie tak.
To API urąga wszelakim minimalnym programowania.

**Comment by PawelTaberski** [comment]
Przetestowałem na twoim body i UUID i wszystko wydaje się, że działa poprawnie. Czy dalej masz problem z tym zasobem?
Jeśli tak to podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a wraz z responsem i trace-id. Sprawdzimy to.

**Comment by haloween** [comment]
Z tego co widzę to requestach PUT wymagane jest dodanie "Content-Type": "application/vnd.allegro.public.v1+json". Nie ma o tym info w dokumentacji ...
HTTP zwracał 415 ale opis błędu do tego był kompletnie od czapy.

**Comment by PawelTaberski** [comment]
Tak jest to wymagane stosowny opis z przykładowym wywołaniem znajduje się w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).
Ponadto w takim przypadku powinieneś otrzymać w responsie informacje o problemie z tym nagłówkiem:
```
{
    "errors": [
        {
            "code": "NotSupportedException",
            "message": "Unsupported content type. Please check 'Content-Type' request header",
            "details": null,
            "path": null,
            "userMessage": "The request contains incorrect data. Contact the author of the application."
        }
    ]
}
```

**Comment by pkrzemo** [comment]
> Ponadto w takim przypadku powinieneś otrzymać w responsie informacje o problemie z tym nagłówkiem: ....

To że serwer generuje taki error to jedna sprawa, a to co dociera do zdalnego odbiorcy to inna sprawa.
Być może serwer ma ustawione (ze względów np. bezpieczeństwa) że nie forwarduje wyjątków (Exception) i być może ten wyjątek nie jest poprawnie przechwytywany by go opakować i odesłać. Może być więc tak, że testując w sieci wewnętrznej macie inne komunikaty niż klienci z zewnątrz.

Tak strzelam, bo może przez całkowity przypadek trafiłem jakiś trop i może się to wam jakoś przyda ... ;-)

**Comment by haloween** [comment]
> Tak jest to wymagane stosowny opis z przykładowym wywołaniem znajduje się w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

Nie czytam poradnika tylko dokumentację i nie robię zapytań CURL tylko requests.

Sorry ale tworzycie jakieś swoje dziwne standardy wychodząc z pozycji siły. 
Autoryzacja aplikacji to droga przez mękę. Opisy błędów nic nie mówią. 
Ulepiliście jakiegoś totalnego kaszalota i pół Polski się z tym musi użerać. 

Hipsterska Paranoja ...
