### ISSUE TITLE
https://api.allegro.pl/order/checkout-forms

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#1824]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zasób działa poprawnie z parametrami offset i limit. Jak dodaję do parametrów: lineItems.boughtAt.gte = 2019-05-31T12:31:04.412 to zwracany jest BadRequest. Gdzie leży błąd?

**Comment by PawelTaberski** [comment]
Sprawdziłem i metoda działa poprawnie np. z zapytaniem:
/order/checkout-forms?limit=100&offset=2&lineItems.boughtAt.gte=2019-04-01T13:00:18.155Z
Problemem w twoim wypadku będzie spacja przed i po znaku "="

**Comment by mareklemur** [comment]
Teraz działa. To nie spacje tylko "Z" na końcu stringa. W dokumentacji w response jest bez "Z" - tym się sugerowałem.
