### ISSUE TITLE
Migracja webAPI -> RestAPI cześć 2 - transakcje

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1825]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Na czas migracji między webAPI a restAPI procesu pobierania zamówień potrzebujemy by w metodzie: doGetPostBuyFormsDataForSellers by pojawiły się dane dotyczące:
- UUID zamówienia
- UUID dostawy
Dlaczego? Poczta Polska w swoim API wymaga by takie dane przekazywać im dla nowego formatu.
Pytanie pomocnicze, dlaczego wasi Partnerzy wymagają używania UUID zamówienia jeśli Wy (Allegro) wspieracie zarówno webAPI jaki i restAPI w zakresie transakcji do końca 2019 roku?

**Comment by PawelTaberski** [comment]
Nie przewidujemy już wprowadzania zmian w zasobach do zarządzania zamówieniami w WebAPI, te informacje możesz pobrać przez REST API. Niedługo wdrożymy jeszcze metodę do mapowania id płatności, która może być również pomocna w wyszukaniu tych informacji.

**Comment by Zbigniew-L** [comment]
Poczta na szczęście wspiera w dalszym ciągu generowanie etykiet allegro odbiory w punkcie - trzeba podać dealId (uwaga to nie to samo co payment number (integer nie guid)) oraz placowka Id.

W każdym razie prosimy o informację kiedy pojawi się już jakaś nowa metoda w RestAPI dzięki której możemy znaleźć zamówienie w RestAPI podając np. id płatności (integer nie guid) lub ewentualnie dealId (również integer nie guid).

**Comment by MartaNowaczyk** [comment]
Tak jak pisał @PawelTaberski planujemy mapowanie, by połączyć webAPI i REST, a mianowicie paymentId (REST API) i transactionId (webAPI). Więcej o tym jeszcze prawdopodobnie w tym tygodniu.
