### ISSUE TITLE
Brak możliwości logowania BŁAD

### ISSUE THREAD

**Issue by Magdalenanieckula1** [allegro/allegro-api#1827]
Dzień dobry,
Dziś za każdym razem kiedy próbujemy połączyć aplikację z kontem użytkownika wyskakuje taki bład
![image](https://user-images.githubusercontent.com/45870723/59533440-bf552d80-8eeb-11e9-886a-65ca426a5693.png)

**Comment by MartaNowaczyk** [comment]
Sprawdź poprawność redirect_uri - czy jest na pewno taki sam jak podany podczas rejestracji aplikacji.
