### ISSUE TITLE
Zbyt długa wartość dla parametru Kolekcja(220853).

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#1828]
Cześć
Otrzumuję błąd 

> Zbyt długa wartość dla parametru Kolekcja(220853).

Jaki jest limit długości w tym polu?

Dzięki za odpowiedź.

**Comment by Tofik1987** [comment]
Przecież metoda /sale/categories/{categoryId}/parameters zwraca maksymalną długość wartości dla pola w "restrictions": {"maxLength": Integer}, nie podałeś ID kategorii więc ciężko sprawdzić...

**Comment by MartaNowaczyk** [comment]
Czy wskazówki Tofik1987 pomogły czy potrzebujesz jeszcze pomocy?
