### ISSUE TITLE
Blad autoryzacji uzytkownika PILNE

### ISSUE THREAD

**Issue by Magdalenanieckula1** [allegro/allegro-api#1829]
Dzień dobry,
Od wczoraj od godziny 17 mamy bład autoryzacji uzytkownika. Z jednego rozwiazania korzysta 1500 osób każdy z nich otrzymuje komunikat jak na ponizszym zdjeciu. 
Prosimy  o pilna interwencje
![image](https://user-images.githubusercontent.com/45870723/59551065-32a28200-8f74-11e9-8c19-0622452b808b.png)

**Comment by Tofik1987** [comment]
Polecam sprawdzić czy parametry aplikacji nie zostały zmienione, taki błąd może wywołać chociażby zmiana "Adresy URI do przekierowania" z http na https

**Comment by MagdalenaNieckula** [comment]
W srodowisku sandbox pojawia się taki komunikat przy probie zalogowania
{"status":"error","message":"RestDriver::call() returned null. Connection problem may have occured."}

**Comment by MartaNowaczyk** [comment]
@MagdalenaNieckula tak jak pisze Toffik1987 w takiej sytuacji  sprawdź poprawność redirect_uri.

Jeśli chodzi o drugą sprawę czy problem nadal występuje, bo nie mogę powtórzyć.
