### ISSUE TITLE
Pobieranie identyfikatora punktu odbioru  

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#183]
pobieranie danych dla punktu odbioru dla poczty polskiej przez funkcje  doGetPostBuyFormsDataForSellers i postBuyFormGdAddress są dane punktu, ale brakuje w nich identyfikatora punktu poczty np. 955147, jest tylko nazwa punktu np.'FUP Leszno 1', a nie jest ona jednoznaczna. Jakie dane należy pobrać by te informacje były?

**Comment by LukaszKorek** [comment]
Przy wywołaniu metody DoGetPostBuyFormsDataForSellers, otrzyma Pan w polu: 
postBuyFormAdrFullName - rodzaj punku np Kiosk Ruchu
postBuyFormGdAddress  - pełny adres danego punktu
Samego identyfikatora nie zwracamy.
