### ISSUE TITLE
Błąd 406 Not Acceptable https://api.allegro.pl/

### ISSUE THREAD

**Issue by Ab1lity** [allegro/allegro-api#1830]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-Id: 93ae822dfd348fe1

Autoryzacja przebiega poprawnie do momentu w którym chce pobrać jakiś zasób
dostaję  komunikat `406 Not Acceptable`
**na środowisku testowym wszystko śmiga poprawnie**

Metoda wywołująca zdarzenie:
```
 public function getEventsStats(){
        $client = new Client(['base_uri' =>  'https://api.allegro.pl/']);
        $primaryAuthRequest = $client->request('GET', '/order/event-stats',[
            'debug' => true,
            'headers' => $this->getBearerAuthentication()
        ]);
        return $primaryAuthRequest->getBody()->getContents();
    }
```

**Comment by MagdalenaNieckula** [comment]
Mamy to samo od piatku godziny 17.....

**Comment by mbednarski** [comment]
Ja mam to samo - od soboty jakoś (możliwe że wcześniej)

**Comment by MagdalenaNieckula** [comment]
Od piatku... Tylko u Nas pracuje na tym 1500 osob...

**Comment by MartaNowaczyk** [comment]
@Ab1lity w nagłówku accept masz na pewno wersję beta?

**Comment by MartaNowaczyk** [comment]
@MagdalenaNieckula @mbednarski też dostajecie błąd 406 dla tej metody?

**Comment by MagdalenaNieckula** [comment]
401

**Comment by MagdalenaNieckula** [comment]
Pozatym to działało do piatku... Wszystko było poprawne z Naszej strony jest wszystko w porzadku

**Comment by MagdalenaNieckula** [comment]
nawet na koncie sandbox juz jest ten sam problem:
{"status":"error","message":"RestDriver::call() returned null. Connection problem may have occured."}

**Comment by Ab1lity** [comment]
> @MagdalenaNieckula @mbednarski też dostajecie błąd 406 dla tej metody?

**Comment by Ab1lity** [comment]
> @Ab1lity w nagłówku accept masz na pewno wersję beta?

```'Accept' => 'application/vnd.allegro.public.v1+json',
    'Content-Type' => 'application/vnd.allegro.public.v1+json',```

**Comment by Ab1lity** [comment]
kolejna nie działająca rzecz nie działa endpoit na przedział datowy
```order/checkout-forms?lineItems.boughtAt.lte=2019-06-12T15%3A36%3A07.342Z&lineItems.boughtAt.gte=2019-06-17T15%3A36%3A07.342Z```

Na koncie allegro w tym przedziale znalazłem dużo zamówień a to zwraca mi 
`"{"checkoutForms":[],"count":0,"totalCount":0}"`

**Comment by MartaNowaczyk** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURL-a z requestem i responsem z dopiskiem GitHub #1830. Sprawdzę na konkretnych danych.
