### ISSUE TITLE
REST API token Authorization failure

### ISSUE THREAD

**Issue by newbeehasnoidea** [allegro/allegro-api#1831]
![QQ图片20190617090653](https://user-images.githubusercontent.com/51903258/59585234-45d26080-90e0-11e9-95bc-606a91826452.png)

Please help with the problem described in attached picture. We have been trying to obtain a token in the method of User Authorization, it didn't work

**Comment by MartaNowaczyk** [comment]
I'm sorry, we don't support programming languages. Check your Client ID and Client Secret. Try to make a curl with this call, and if you have any problems send request and response to us via the [contact form](https://allegro.pl/pomoc/kontakt)with note GitHub #1831
