### ISSUE TITLE
Błędy w trakcie wznawiania oferty 

### ISSUE THREAD

**Issue by Tofik1987** [allegro/allegro-api#1832]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję od kilku dni wznowić kilkanaście aukcji,
metoda /sale/offer-publication-commands/91fadac3-665b-4651-81bd-00841051f5fb/tasks  zwraca przy większości pozycji komunikat 

> An error occurred while trying to change the publication of the offer. Please try again later.

Próbowałem wznowić ofertę ofertę "7285370149"  z poziomu allegro, dostaje komunikat "

> Podczas wznowienia oferty wystąpiły błędy
> Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.

 
Poniżej zamieszczam listę aukcji, 
6883052971, 6673982722, 7352217995, 7471031623, 6668889498, 7294204041, 6898341878, 6902408216, 6893155965, 7135152391, 6995041093, 6901331408, 7075558708, 6875019483, 6671157419, 6884128393, 6899683656, 7095690973, 7229554467, 6901683154, 6901555178, 6994973540, 6890069999, 6902164375, 6890064981, 7681486382, 7237175495, 7593699999, 6816039288, 7681365486, 6898637625, 7274730035, 7681368755, 6900184961, 6902828991, 6959787661, 7283492996, 6901541839, 7544628239, 7414480450, 7274615095, 7557306323, 6884148093, 7350387091, 7175136300, 7180319407, 6665198874, 7469642531, 7306996549, 6737085996, 6900917534, 6898199645, 6900964918, 7681410430, 7681342145, 7021953266, 7237158141, 7681451427, 6900970813, 7308095771, 7414480280, 7134851943, 7130541757, 7012726233, 7600725988, 6884129959, 6902372893, 7285403832, 7024975348, 6902452144, 7011484039, 7471011507, 6898202091, 6886564096, 7285370149, 7401631084, 6901725646, 6875067744, 7365789827, 7813310950, 7099835936, 7350998596, 6901725885, 7136466136, 7471008198, 6893454876, 6639452052, 6900240713, 6902472522, 6902431694, 7365809305, 

Mogli byście dopracować komunikaty z błędami

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację. Zgłoszę zmianę komunikatu do odpowiedniego zespołu.

**Comment by Tofik1987** [comment]
Cieszę się, a jaka jest przyczyna tego że aukcję się nie aktywują ? 
Jak zakończona aukcja może być "w trakcie kończenia" ?

**Comment by MartaNowaczyk** [comment]
Przyczyna tego błędu jest w trakcie weryfikacji.

**Comment by MartaNowaczyk** [comment]
Problem był po naszej stronie. Zaktualizowaliśmy podane oferty. W przyszłym tygodniu planujemy globalnie usunąć ten problem. Za utrudnienia przepraszamy.

**Comment by kregielpl** [comment]
@MartaNowaczyk U mnie problem pojawia się przy próbie dodania kolejnej oferty. Id aukcji: 6206833949.

**Comment by PatrykBocian** [comment]
@kregielpl Jak rozumiem problem dotyczy Sandboxa - następnym razem proszę, wspomnij o tym przy zgłoszeniu. Nie możesz opublikować oferty, ponieważ nie przekazujesz obowiązkowych wartości (np. Opis, parametry) - wszystkie brakujące wartości widać w response w tablicy validation. Jak je uzupełnisz, będziesz mógł opublikować ofertę. 

Aby zobaczyć jak, wyglądają uzupełnione obowiązkowe pola - możesz wystawić ofertę na froncie, a następnie pobrać ją za pomocą GET /sale/offers/(offerId} - dostaniesz wtedy gotowy szablon.
