### ISSUE TITLE
ERROR: Category '19870' not found ()"

### ISSUE THREAD

**Issue by MagdalenaNieckula** [allegro/allegro-api#1833]
Dzień dobry,
W trakcie wystawiania przedmiotu ZEGAREK pojawia się taki komunikat:
ERROR: Category '19870' not found ()"
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by MartaNowaczyk** [comment]
Błąd występuje ponieważ nie ma takiej kategorii. W jakiej kategorii chcesz wystawić tę ofertę?

**Comment by MagdalenaNieckula** [comment]
Moda>Bizuteria i Zegarki>Zegarki>Damskie>Nareczne 
to ta kategoria, my zaciagamy kategorie bezpośrednio od Was w czasie rzeczywistym.

**Comment by MartaNowaczyk** [comment]
Pobrałam przez REST PI i powinna to być kategoria o id 19864. W jaki sposób pobierasz kategorię, że dostajesz takie ID? Poza tym typ zegarka jak "naręczny" jest już parametrem.
