### ISSUE TITLE
zakończenie aukcji aukcji

### ISSUE THREAD

**Issue by mleplawy** [allegro/allegro-api#1835]
Próbując zakończyć aukcje za pomocą offer_publication cały czas dostaję 
{"id":"f0f2b89e-abb1-4799-b553-c1bd863d56b9","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by MartaNowaczyk** [comment]
Sprawdź status [odpowiednią komendą](https://developer.allegro.pl/sale/#step-10-tasks)

**Comment by mleplawy** [comment]
no właśnie dostaje 
:{"total":0,"success":0,"failed":0}}

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i dla GET /sale/offer-publication-commands/f0f2b89e-abb1-4799-b553-c1bd863d56b9
REST zwraca:
{
    "id": "f0f2b89e-abb1-4799-b553-c1bd863d56b9",
    "taskCount": {
        "total": 1,
        "success": 0,
        "failed": 1
    }
}
do tego później modyfikowałeś jeszcze tę ofertę: była w statusie ENDED, a potem jeszcze ją aktywowałeś 2019-06-18T09:19:37Z.

**Comment by mleplawy** [comment]
sprawdziłem na innej aukcji które ma status trwający

zwraca
{"id":"0e8ebb8b-2535-4738-be46-5d6633904b60","taskCount":{"total":0,"success":0,"failed":0}}

przy wywołaniu

`$data2=array (
  'offerCriteria' => 
  array (
    0 => 
    array (
      'offers' => 
      array (
        0 => 
        array (
          'id' => '6966834833',
        ),
      ),
      'type' => 'CONTAINS_OFFERS',
    ),
  ),
  'publication' => 
  array (
    'action' => 'END',
  ),
);
echo "<br/>";
$response2 = $api->sale->commands()->offer_publication($data2);`

**Comment by MartaNowaczyk** [comment]
Do sprawdzania statusu korzystaj z GET /sale/offer-publication-commands/{commandId}
