### ISSUE TITLE
HTTP_USER_AGENT dla pobieranych zdjęć przez /sale/images

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1836]
Przy wysyłaniu urla do zdjęcia dostajemy komunikat o Image url redirects from url ( prawdziwy url )
 to http://www.robotstxt.org which uses a different scheme. Please use the same scheme or send request with the final URL.(HTTP ERROR 422) There was a problem with redirecting to the image. 

I generalnie słusznie ponieważ w htaccess mamy wycięte web crawlery po HTTP_USER_AGENT

Jakiego HTTP_USER_AGENT używacie do pobierania zdjęć abyśmy go odblokowali po naszej stronie ?

**Comment by TimothyKoval** [comment]
Java/11.0.3 :D

**Comment by yncki** [comment]
super
