### ISSUE TITLE
Automatyczny import zamówien

### ISSUE THREAD

**Issue by speeduppoznan** [allegro/allegro-api#1839]
Witam

Mam pytanie o logikę działania nowego API. Mamy napisany system w PHP, który automatycznie pobierał zamówienia przez WebAPI co jakiś czas.
W nowej wersji API czytam, że uruchamiając aplikację trzeba przekierować użytkownika aby uwierzytelnił się na stronie allegro gdzie aplikacja musi przekierować użytkownika po czym dopiero aplikacja/system ma dostęp do danych na koncie allegro.
Przy dużej liczbie zamówień i kilku kontach jest to mało efektywne rozwiązanie.
Czy jest rozwiązanie w nowym API, które pozwala uwierzytelnić nasz system bez interakcji z użytkownikiem?

Pozdrawiam
Dariusz Raczkowski

**Comment by neldh** [comment]
poczytaj w instrukcji o code flow. Raz musisz uwierzytelnic uzytkownika (z dowolnego urzadzenia), a potem tylko odswiezasz tokeny.

**Comment by speeduppoznan** [comment]
To ma działać tak:
skrypt php uruchamiany cronie np 3x dzienne pobiera zamówienia z allegro i wgrywa do bazy danych naszego programy magazynowo-sprzedażowego. A ma to być bez ingerencji użytkownik.
Mamy cztery konta allegro i uwierzytelniane ręcznie mija się z celem.

**Comment by neldh** [comment]
Ja Cie rozumiem, ale uwierzytelnienie w code flow mozesz zrobić jeden raz na zawsze.

1. Jakis twoj skrypt niech wygeneruje link do uwierzytelnienia dla aplikacji typu code.
2. Wysylasz ten link na maila komus, kto ma dostep do tego konta sprzedawcy.
3. Gosc wchodzi na maila, klika w link, loguje sie na konto sprzedawcy, akceptuje i gitara
4. W tym momencie jakis twoj skrypt sprawdza czy dostal akceptacje i jak tak to pobiera tokeny. 
5. Od tej pory wystarczy ze skrypt ktory chodzi 3x dzienie odswieza otrzymane przez ten wczesniejszy skrypt tokeny raz dziennie i masz spokoj az cos nie padnie. Najlepiej sprawdzić, czy nie rzuca bledami autoryzacji i jak tak, wróć do pkt. 1

**Comment by speeduppoznan** [comment]
Chyba już rozumiem,
Jeszcze pytanie, dostaję token ważny 12h, ale jest jeszcze refresh_token który jak rozumiem wydłuża ważność tokena do 3mc ?

**Comment by neldh** [comment]
nie - przedluza na kolejne 12 godzin, ale sam wazny jest 3 miesiace. Za kazdym razem jak prosisz o tokeny (czy to normalnie czy refresh), dostajesz parę: access token wazny 12 godzin i refresh token wazny 3 miesiące

**Comment by neldh** [comment]
Swoją droga byl chyba gdzieś w ktoryms issue jakis gotowy skrypt pod to - niestety nie wiem gdzie, bo sam z niego nie korzystam, ale moze jakas zyczliwa dusza znajdzie.

**Comment by speeduppoznan** [comment]
Dzięki za pomoc, póki co pobieram zamówienia.
Natomiast czy da się za pomocą api wylistować wszystkie możliwe sposoby wysyłek? W starym API była taka metoda.

PS.
zabawne jest, że nowe API jest opisane jako BETA a stare już praktycznie wyłączone.

**Comment by PawelTaberski** [comment]
@speeduppoznan Do pobrania wszystkich dostępnych sposobów dostawy skorzystaj z zasobu /sale/delivery-methods. Więcej na ten temat [znajdziesz tutaj](https://developer.allegro.pl/sale/#shipping-rates).
Odnośnie wersji to zasoby w wersji beta są jak najbardziej stabilne i dopiero po tym jak przejdą na public w ogłoszonym terminie wygaszamy ich odpowiedniki w WebAPI.
