### ISSUE TITLE
Kody EAN

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#1840]
Mam pytanie jesli mam aukcje zestawu filtrow w ktrorej sa 4 filtry, co za tym idzie 4 eany, co mam podac w polu ean wystawiajac aukcje?

**Comment by MartaNowaczyk** [comment]
EAN powinien być przypisywany do danego produktu, a zestawy tworzone za pomocą narzędzi allegro np. https://developer.allegro.pl/offer_bundles/#5
