### ISSUE TITLE
Coś nie tak z zasobem /categories

### ISSUE THREAD

**Issue by kuzminero** [allegro/allegro-api#1841]
Co się stało z zasobem api.allegro.pl/categories? Do niedawna używaliśmy go do pobierania listy wszystkich kategorii na portalu. Teraz jednak wywala taki błąd:

![image](https://user-images.githubusercontent.com/40072066/59743450-70ebba00-9270-11e9-8aca-5968444864b8.png)

Nagłówek Accept nie był zmieniany - application/vnd.allegro.public.v1+json
Authorization również poprawny

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i endpoint zwraca prawidłowo dane. Podany błąd konkretnie świadczy o problemie z nagłówkiem accept. Jeśli jest on według ciebie poprawny podeślij pełen request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1841

**Comment by kuzminero** [comment]
Tak, _/sale/categories_ działa jak należy.
Ale chodzi mi o **/categories**, który nagle przestał działać.

**Comment by arhimano** [comment]
Dołączam się do dyskusji, u nas tak samo. Korzystaliśmy z zasobu /categories (bez /sale na początku!) i nagle zaczął rzucać błędami.
Jak mamy pobierać całe drzewo kategorii??

**Comment by MartaNowaczyk** [comment]
Nie ma tego zasobu w dokumentacji, a tylko takie wam udostępniamy i weryfikujemy ich działanie. Prawidłowy to /sale/categories i z niego należy korzystać.

**Comment by arhimano** [comment]
W takim razie @MartaNowaczyk jak mamy pobierać **całe** drzewo kategorii? Rekurencyjnie?
Co pani proponuje?

**Comment by riepa** [comment]
to była możliwość pobierania całego drzewa kategorii??? wtf dobrze wiedzieć po tym jak przebiło się cały program pod rekurencyjne pobieranie

**Comment by PawelTaberski** [comment]
W jaki sposób pobierać kategorie i parametry znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-2).

**Comment by PhotoSoft** [comment]
Importuje trwające aukcje do swojej bazy. Potrzebuje pełną ścieżkę z nazwami kategorii, np. _"Komputery \ Oprogramowanie \ Biuro i zarządzanie firmą \ Zarządzanie firmą"_. Jak mam ją teraz pobrać?

Wywołując pierdyliard połączeń odczytując pole "parent"? I mam tak marnować czas użytkownika? Wczytanie pełnej ścieżki lokalnie zajmie ułamek sekundy!

Pobieranie całego drzewa rekurencyjnie to jakiś masochizm. Ile to będzie połączeń? I ile z nich zerwie serwer?

Nie róbcie sobie jaj z wyłączeniem doGetCatsData bez dania możliwości pobrania całego drzewa przez RestApi.

**Comment by PawelTaberski** [comment]
Rozumiem, sugestię odnośnie pobierania drzewa całościowo przekazałem.

**Comment by rtnet-pl** [comment]
W miarę możliwości nie przechowujcie drzewka u siebie lokalnie, bo w obecnym układzie nie ma to sensu.
U nas rozwiązujemy to tak, że lokalnie przechowujemy id kategorii i osobno ścieżkę kategorii w stringu. W praktyce rzadko kiedy występuje konieczność prezentowania userowi całego drzewka. Natomiast prawdopodobieństwo zmiany tekstowego opisu ścieżki jest bliskie zera, a nawet gdyby taka zmiana zaszła, to nie sądzę aby była to w praktyce inna kategoria niż ta którą użytkownik wybrał wcześniej.
Dodatkowo nie sądzę aby był sprzedawca który w jednej sesji pracował na co dzień z więcej niż kilkunastoma/kilkudziesięcioma kategoriami, taką ilość można spokojnie pobeirać na żądanie i cachować po stronie aplikacji w ramach sesji.
Oczywiście nie znam do końca waszych potrzeb, to tylko sugestia z mojej strony bo wydaje mi się że kluczycie.

ps. jest taki nieudokumentowany https://allegro.pl/suggestions/?phrase=pedigree&country=pl&highlights=b&sortByElementType=false którym można zrobić protezę wyszukiwania i sugestii

**Comment by j4r3kb** [comment]
Przechowywanie drzewa kategorii oraz parametrów jest konieczne w momencie kiedy aplikacja ma funkcję mapowania parametrów produktu na parametry kategorii allegro. Wtedy bez takiego cache nie da się spełnić takiej funkcji.
Metoda pozwalająca pobrać wszystkie parametry wszystkich kategorii była kiedyś w WebAPI potem zdecydowano ją usunąć.
Teraz taka aplikacja musi orać co dzień parametry ze wszystkich kategorii najniższego rzędu.

**Comment by Onixarts** [comment]
> W praktyce rzadko kiedy występuje konieczność prezentowania userowi całego drzewka.
Chyba, że masz wyszukiwarkę kategorii ;)

> Natomiast prawdopodobieństwo zmiany tekstowego opisu ścieżki jest bliskie zera
A dałbym sobie rękaw uciąć, że przesunięcia na kategoriach występują dosyć często.

> ps. jest taki nieudokumentowany
Właśnie w wątku obok przed chwilą czytałem jak kończy się używanie nieudokumentowanych zasobów :) 

Przydałby się dziennik zdarzeń serwisowych, w którym były odnotowane wszelkie zmiany w drzewie kategorii, parametrów. Wtedy można by sobie aktualizować tylko fragment poddrzewa kategorii, gdy już mamy całe przechowywane po stronie aplikacji.

>Metoda pozwalająca pobrać wszystkie parametry wszystkich kategorii była kiedyś w WebAPI potem zdecydowano ją usunąć.
Ale tego to już nie polecam. My "oramy" tylko parametry dla kategorii, które użytkownik używa i to tylko wtedy, gdy jest mu to potrzebne.

**Comment by j4r3kb** [comment]
> Ale tego to już nie polecam. My "oramy" tylko parametry dla kategorii, które użytkownik używa i to tylko wtedy, gdy jest mu to potrzebne.

Tak jak napisałem, mapowania parametrów produktów z systemu na parametry allegro nie zrobisz bez trzymania tego w bazie.

**Comment by Onixarts** [comment]
No ale trzymasz chyba tylko te, których potrzebujesz. Po co Ci parametry spławików jak zajmujesz się sprzedażą elektroniki.

P.S. Zrobię ;)

**Comment by j4r3kb** [comment]
System jest duży, wielu klientów z różnych branż, nie wiesz co, gdzie i kiedy zechcą wystawić. Wystawianie nie odbywa się tylko pojedynczo aukcja po aukcji, możliwe jest wystawianie masowo wielu produktów za jednym zamachem.

**Comment by Onixarts** [comment]
Dlatego dziennik zdarzeń informujący o zmianach kategorii i parametrow byłby tutaj idealny.

**Comment by imper86** [comment]
Hej allegro, a nie lepiej by było po prostu udostępnić kompletne drzewo kategorii np w postaci pliku XML? Po Waszej stronie taki plik generowałby się raz podczas zmiany w kategoriach, oszczędzilibyście zasoby, a przynajmniej osoby, które mają taką potrzebę żeby pobierać całe drzewko, w końcu miałyby taką możliwość.

**Comment by PawelTaberski** [comment]
Przekazałem wasze sugestie odnośnie kategorii i różnych propozycjach zmian/rozbudowy.

**Comment by Onixarts** [comment]
> Hej allegro, a nie lepiej by było po prostu udostępnić kompletne drzewo kategorii np w postaci pliku XML?

A czym to wg Ciebie różni się od udostępnienia takiego zasobu w REST?

**Comment by TimothyKoval** [comment]
Pewnie tym czym różni się 20000 requestów od jednego :)

**Comment by Onixarts** [comment]
Czym różni się zrobienie jednego zasobu, który zwraca całe drzewo w 1 requeście od udostępnienia jakiegoś lewego pliku xml, który zawiera w sobie dokładnie to samo? Kto będzie pilnował tego pliku? Kto to będzie pobierał i skąd? To już moim zdaniem lepiej niech zostanie jak jest. Pobranie wszystkich kategrii obecnie trwa kilka(naście) minut.

**Comment by imper86** [comment]
@Onixarts oczywiście masz rację, niczym się nie różni, przy czym zakładam, że allegro przyjęło jakieś odgórne założenia odnośnie wielkości requestów i response'ów, dlatego bronią się rękami i nogami przed takimi pomysłami.
Dlatego stwierdziłem, że może pomysł statycznego pliku będzie czymś, co ich ostatecznie przekona do stworzenia takiego zasobu obok całego API.

Reszty Twoich stwierdzeń typu "lewy plik" "kto będzie pilnował" "kto będzie pobierał" nie komentuję, bo szkoda klawiatury.

**Comment by rtarnowski** [comment]
@PawelTaberski  czy coś wiadomo w tym temacie? Kiedy planujecie coś takiego dostarczyć ?

**Comment by PawelTaberski** [comment]
Nie otrzymałem jeszcze żadnych informacji w tym temacie, jeśli zdecydujemy się na wdrożenie takiej zmiany, to na pewno poinformujemy o tym w dedykowanym komunikacie.
