### ISSUE TITLE
sale/offers/{offerId} 403 Forbidden

### ISSUE THREAD

**Issue by forest100** [allegro/allegro-api#1842]
I use https://developer.allegro.pl/en/documentation/#operation/getListing to search offers. Everything works fine.
Then i use https://developer.allegro.pl/en/documentation/#operation/getOfferUsingGET to get info about of the particular offer 
But i get 403 Forbidden. For example, "sale/offres/6060695474" answer is 
```
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => FORBIDDEN
                    [message] => Forbidden
                    [details] => 
                    [path] => /sale/offers/6060695474
                    [userMessage] => 
                )

        )

)
```

Both cases i use "bearer-token-for-user". What did I do wrong? Sorry for my bad english.

**Comment by MartaNowaczyk** [comment]
What [type of authorization](https://developer.allegro.pl/en/auth/) do you use? Maybe your token has no user context.  Use Device or Code flow to autorization. You can decode token by https://jwt.io/

**Comment by forest100** [comment]
I use "Authorization Code flow for Allegro OAuth". I decoded my token and saw "Invalid signature" What should i enter in "public key" field to verify it? http://oi65.tinypic.com/t62ijc.jpg

**Comment by Onixarts** [comment]
We've also encountered forbidden errors on this resource 2 days ago.

**Comment by PawelTaberski** [comment]
@forest100 @Onixarts Please send via [our contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) this tokens and full request we will check it. Write in message that  this information are needed for ticket number 1842 on GitHub.

**Comment by forest100** [comment]
What is the analogue of the WebAPI's method "doShowItemInfoExt" in REST API?

**Comment by PawelTaberski** [comment]
@forest100  Now there isn't any method to get public data about offers in REST API but will be in near future. We will inform in dedicated communication about implementation of such method.
