### ISSUE TITLE
doBidItem, odpowiednik w REST

### ISSUE THREAD

**Issue by atmdevnet** [allegro/allegro-api#1843]
dzień dobry,
czy istnieje odpowiednik metody doBidItem w nowym REST api?
W sierpniu planowane jest wygaszenie tej metody ale nie zauważyłem odpowiednika ani w dokumentacji rest api, ani w harmonogramie wygaszania web api.
Czy po wygaszeniu tej metody będzie możliwość dokonywania zakupu w opcji "kup teraz" przez rest api?

**Comment by PawelTaberski** [comment]
Odpowiednia metoda do składania ofert kupna w licytacji powinien pojawić się jeszcze w tym miesiącu.
