### ISSUE TITLE
Model danych parametrów oferty niezgodny z dokumentacją

### ISSUE THREAD

**Issue by p-pawel** [allegro/allegro-api#1844]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie utworzenia oferty z parametrami (pole `parameters` jak opisano tutaj: https://developer.allegro.pl/sale/#new-offer ) otrzymuję serię błędów `VALIDATION_ERROR`.

Na przykład:
Dla przedmiotu wystawianego w kategorii `76659` (Sandbox) przesyłam taki zestaw parametrów:
```
{
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "3991",
      "valuesIds": [
        "3991_128"
      ]
    },
    {
      "id": "3992",
      "valuesIds": [
        "3992_16384"
      ]
    },
    {
      "id": "17448",
      "valuesIds": [
        "0.123"
      ]
    }
  ]
}
```
(lub `values` w ostatnim elemencie)
i otrzymuję następujące błędy walidacji:
```
[
  {
    "code": "VALIDATION_ERROR",
    "details": "",
    "message": "You can only assign dictionary parameter by valueId for 11323.",
    "path": "",
    "userMessage": "You can only assign dictionary parameter by valueId for 11323."
  },
  {
    "code": "VALIDATION_ERROR",
    "details": "",
    "message": "You can only assign dictionary parameter by valueId for 3991.",
    "path": "",
    "userMessage": "You can only assign dictionary parameter by valueId for 3991."
  },
  {
    "code": "VALIDATION_ERROR",
    "details": "",
    "message": "You can only assign dictionary parameter by valueId for 3992.",
    "path": "",
    "userMessage": "You can only assign dictionary parameter by valueId for 3992."
  },
  {
    "code": "VALIDATION_ERROR",
    "details": "",
    "message": "You can only assign string parameter by value for 17448.",
    "path": "",
    "userMessage": "You can only assign string parameter by value for 17448."
  },
  {
    "code": "VALIDATION_ERROR",
    "details": "",
    "message": "No values given for parameter Stan(11323).",
    "path": "",
    "userMessage": "No values given for parameter Stan(11323)."
  }
]
```
Wszystkie komunikaty wyglądają na oczekiwanie podania danych o parametrach w postaci innej niż opisania w dokumentacji: 
* https://developer.allegro.pl/sale/#new-offer
* https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT <- tu proszę zwrócić uwagę że opisany model danych typu `Parameter` nie przewiduje pól `valueId` bądź `value` jak opisane w komunikatach błędu

trace id: `8d26d3ffb56788e0`

**Comment by p-pawel** [comment]
Zamykam temat - mój błąd. Nie zauważyłem, że oprócz `valuesIds` niechcący wysyłałem to samo w `values`, stąd były prawidłowej błędy walidacji w pierwszych parametrach i brak wartości w ostatnim. 

I mimo wszystko proponuję ujednolicenie nazw pól z komunikatu błędu z nazw pól z modelu danych, 
np. aby zamiast 
`You can only assign dictionary parameter by valueId for 3992."`
wyświetlało się 
`You can only assign dictionary parameters by valuesIds for 3992."`,
co by nie sugerowały one użycia innych pól niż udokumentowane.

**Comment by pkrzemo** [comment]
Zgodnie z dokumentacją powinno to wyglądać tak:
 {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
     "values": [],
            "rangeValue": null
    },

a dla wartości

{
      "id": "17448",
      "valuesIds": []
       ,"values": [ "0.123"]
 ,
            "rangeValue": null
    }
