### ISSUE TITLE
Parametry wymagane które nie są wymagane

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#1846]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

`/sale/categories/18896/parameters` zwraca m.in.:

```
{
	"id": "129591",
	"name": "Typ samochodu",
	"type": "dictionary",
	"required": true,
	"unit": null,
	"options": {
		"variantsAllowed": true,
		"variantsEqual": false,
		"describesProduct": true
	},
	"dictionary": [{
		"id": "129591_1",
		"value": "Samochody osobowe"
	}, {
		"id": "129591_2",
		"value": "Samochody dostawcze"
	}, {
		"id": "129591_4",
		"value": "Samochody ciężarowe"
	}, {
		"id": "129591_8",
		"value": "Autobusy"
	}],
	"restrictions": {
		"multipleChoices": true
	}
}
```

i niby required == true, a required nie jest...

**Comment by PawelTaberski** [comment]
Rzeczywiście przetestowałem i pomimo oznaczenia nie jest on wymagany w API, na froncie jest już wymagany także niedługo będzie również w API. Jednakże jest to jak najbardziej błąd i zgłosiłem to do odpowiedniego zespołu.
