### ISSUE TITLE
Brak wystawienia oferty od 24h

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1847]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Wczoraj jeden z naszych Klientów zgłosił nam błąd z wystawianiem aukcji
Aukcja otrzymała numer, ale cały czas ma status INACTIVE

REQUEST 2019-06-19 10:37:39.1002881 
curl -X PUT \
  'https://api.allegro.pl/sale/offer-publication-commands/299e421a-1bc9-4c71-bb92-3080324d3450' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  -d '{"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"8225895005"}]}],"publication":{"action":"ACTIVATE","scheduledFor":null}}' \

RESPONSE 2019-06-19 10:37:39.1159447 Duration: 15,6566ms
{
  "Data": {
    "Id": "299e421a-1bc9-4c71-bb92-3080324d3450",
    "TaskCount": {
      "Failed": 0,
      "Success": 0,
      "Total": 0
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "26dbca2acc6f56da",
  "Error": false,
  "StatusCode": 201,
  "Message": null
}

REQUEST 2019-06-19 11:35:34.2329639 
curl -X GET \
  'https://api.allegro.pl/sale/offers/8225895005' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

ESPONSE 2019-06-19 11:35:34.2954655 
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "7b634572-cc58-46b5-bd11-ec48bf74dd1b"
      },
      "ReturnPolicy": {
        "Id": "ce269980-4c38-4c4b-8e91-d4e931f1430b"
      },
      "Warranty": {
        "Id": "6025c9ec-2066-4e0a-9b24-f72eb6afaa2f"
      }
    },
<CIACH
  "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": null,
      "EndingAt": null,
      "StartingAt": null
    },
    "SellingMode": {
      "Format": "BUY_NOW",
      "Price": {
        "Amount": "210,00",
        "Currency": "PLN"
      },
      "MinimalPrice": {
        "Amount": "0,00",
        "Currency": "PLN"
      },
      "StartingPrice": {
        "Amount": "0,00",
        "Currency": "PLN"
      }
    },
    "SizeTable": null,
    "Stock": {
      "Available": 96,
      "Unit": "UNIT"
    },
    "UpdatedAt": "2019-06-19T08:47:47.78Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-06-19T08:47:47.78Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "6ec55eb11c4fff",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
@MartaNowaczyk  możecie sprawdzić co sie stało? Inne wystawiaja się poprawnie, a ta akurat się "zwiesiła"

**Comment by PawelTaberski** [comment]
Sprawdź proszę jaką informacje otrzymujesz po wywołaniu zasobu:
GET /sale/offer-publication-commands/{commandId}/tasks
