### ISSUE TITLE
Zlecenie aktualizacji ilości zakolejkowane i wiszące od 11.06

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#1848]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Poprawnie zakolejkowana operacja zmiany ilości w ofercie (sale/offer-quantity-change-commands) 11 czerwca. Do dziś zasób sale/offer-quantity-change-commands/2cdeadb1-c13d-4e67-aeb7-b1dd6c559c0f/tasks zwraca status NEW dla oferty.

Response:
`{"tasks":[{"offer":{"id":"xxx"},"message":null,"status":"NEW","scheduledAt":"2019-06-11T07:12:15.461Z","finishedAt":null,"field":"quantity","errors":[]}]}`

**Comment by PawelTaberski** [comment]
Jeśli masz to podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta ze zmiany ilości wraz z trace-id. Sprawdzimy w czym jest problem. Zaznacz proszę, że dane są potrzebne do ticketa numer 1848 na GitHub-ie.

**Comment by jzskyshop** [comment]
Nie logujemy wszystkich zapytań do Allegro, jest to sytuacja całkiem niespodziewana. Przesyłam info, żebyście wiedzieli, że macie zalegające taski i ewentualnie zareagowali. Liczę też na info co robić w takiej sytuacji - klient poinformował nas, że ma zaległe zadanie monitorujące, oczekujące prawie dwa tygodnie.

**Comment by pkrzemo** [comment]
PawelTaberski
> Jeśli masz to podeślij proszę przez nasz formularz kontaktowy pełnego requesta ...

 Z tego co rozumiem to błąd nie dotyczy "requesta" bo request przeszedł pomyślnie, task został utworzony,  i nie raportuje żadnych błędów... Jednym słowem "operacja się udała ale pacjent nie żyje".
Wszystkie informacje potrzebne do odpowiedzi "dlaczego" znajdują się na serwerze i dotyczą procesów serwera i tam trzeba trzeba szukać przyczyn. 
Błąd jest bardzo niepokojący bo w bardzo wrażliwym miejscu mogącym wpłynąć na realny biznes. 

Wykonanie tego samego requesta na innym środowisku i z innym stanem baz może być bezcelowe, bo szansa na odtworzenie dokładnie tego samego rezultatu (przy potencjalnie innych danych) jest mało prawdopodobna. A testowanie na produkcji mieszając w danych klienta (jeśli taka jest intencja tej prośby) też nie wygląda profesjonalnie. ;-)

**Comment by PawelTaberski** [comment]
@pkrzemo Głównie zależało mi na trace-id bo w ten sposób można jednoznacznie zidentyfikować requesta. Bo pod danym UUID-em ktoś może wywołać wielokrotnie jak ich np nie zmienia.
@jzskyshop Zgłosiłem Twój przypadek do zlokalizowania i zbadania, jeśli będę miał jakieś informacje, bądź dodatkowe pytania to dam znać.
