### ISSUE TITLE
Błąd wywołania zasobu /pricing/fee-preview

### ISSUE THREAD

**Issue by alikoli** [allegro/allegro-api#1849]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem testowym

/pricing/fee-preview

Przekazywana struktura:
{"includeQuotingBundles":false,"offer":{"category":{"id":"82287"},"condition":"NEW","duration":"PT720H","hasAnyQuantity":null,"numberOfBigPhotos":null,"numberOfPhotos":null,"quantity":5,"shop":false,"soldQuantity":2,"type":"OFFER","unitPrice":30.5,"bold":null,"highlight":null,"departmentPage":null,"emphasized":null,"emphasizedHighlightBoldPackage":null,"multiVariant":null}}

Otrzymywana odpowiedź:
{"errors":[{"code":"UNPROCESSABLE_ENTITY","message":"Unprocessable Entity","details":null,"path":"offer","userMessage":"At least one of 'quantity' or 'soldQuantity' should be defined for 'offer.type != advertisement'"}]}

**Comment by TimothyKoval** [comment]
`"hasAnyQuantity": true`

**Comment by alikoli** [comment]
> `"hasAnyQuantity": true`

Dzięki
