### ISSUE TITLE
Jak oznaczyć transakcje jako wysłaną?

### ISSUE THREAD

**Issue by fessio-software** [allegro/allegro-api#185]
Cześć,
dodaje numery listów przewozowych funkcją **doAddPackageInfoToPostBuyForm** ale zamówienia zostają na liście [zamówień](https://allegro.pl.allegrosandbox.pl/seller-orders). Jest szansa aby je oznaczać jako wysłane?

**Comment by MartaNowaczyk** [comment]
Samo dodanie numeru listu przewozowego nie oznacza, że paczka została wysłana. Istnieje możliwość, że wygenerowano tylko etykietę adresową, stąd brak automatycznego oznaczenia zamówienia jako wysłane. 
Na ten moment nie ma możliwości by przez API oznaczyć zamówienie jako wysłane, dlatego pozostaje oznaczenie ręczne w zakładce zamówień. 
W WebAPI na pewno takiej możliwości nie będzie, ale na bieżąco rozwijamy REST API więc możliwe, że docelowo taka opcja się tam pojawi. Jak coś się zmieni damy znać.

**Comment by fessio-software** [comment]
Dziękuje, będę śledził zmiany w REST API.

**Comment by mleplawy** [comment]
A czy allegro planuje dodanei tego do rest api? Bo od 17 września robicie obowiązek oznaczania a robienei recznie troche bez sensu.

**Comment by MartaNowaczyk** [comment]
Po wewnętrznych uzgodnieniach na dzień dzisiejszy planujemy udostępnić tylko dodawanie numerów przesyłek po REST API, bez możliwości uzupełnienia statusu. 
@mleplawy Jeśli chodzi o wspomnianą zmianę, to chodzi o sytuację, gdy "jeśli status przesyłki, którą dodałeś do zamówienia, **zmieni się w systemie przewoźnika na "wysłane"** więc nie chodzi o ręczne wprowadzenie statusu przesyłki, bo wtedy każdy by sobie wybrał jaki chce. J

**Comment by martacronic** [comment]
W panelu Allegro jest opcja filtrowania zamówień. Zaznaczając opcję "Do wysłania" pojawiają się wszystkie paczki, które nie mają statusu wysłane. Również te, które mają nadany numer przesyłki.

![wyslane](https://user-images.githubusercontent.com/37405655/45094039-78473a00-b11a-11e8-995a-e07ba85fab43.png)

Jeśli nie macie zamiaru tworzyć metody adekwatnej do  "Oznacz jako wysłane" w panelu, to może do planowanej metody, która ma dodawać do zamówienia numer przesyłki dodalibyście warunek polegający na tym, że przesłanie numeru oznacza paczkę jako wysłaną.

W tym momencie wygląda to tak, że dodanie nawet wszystkich numerów przesyłek i filtrowanie w panelu po "do wysłania" zwróci wszystkie przesyłki, a przecież nie o to chodzi.

**Comment by MartaNowaczyk** [comment]
@martacronic  Tak jak pisałam wcześniej:

> Samo dodanie numeru listu przewozowego nie oznacza, że paczka została wysłana. Istnieje możliwość, że wygenerowano tylko etykietę adresową, stąd brak automatycznego oznaczenia zamówienia jako wysłane.

Większość użytkowników korzystających z API filtrowanie listy zamówień rozwiązuje po stronie swojej aplikacji. 
Rozumiem, że działacie w inny sposób, dlatego zgłoszę taką sugestię, ale nic nie obiecuję.

**Comment by adamTynski** [comment]
Od dłuższego czasu nikt nie pytał... Czy coś w powyższym temacie (oznaczanie zamówień jako wysłane) się zmieniło? Brak tej możliwości wymusza na użytkowniku konieczność logowania się do Allegro wyłącznie po to, by oznaczyć zamówienie jako wysłane i jest ostatnią przeszkodą zmierzającą ku pełnej automatyzacji procesu.

**Comment by deneb-k** [comment]
Powtarzające się pytania o to oznaczają, że gdzieś w pomocy Allegro albo w innych miejscach są mylące informacje. Bo to wynika z nieporozumienia. Nie trzeba oznaczać zamówień jako wysłane - wysyłasz numer listu przewozowego, a Allegro samo już sprawdza sobie status.

My też musimy klientom to co jakiś czas tłumaczyć. Wypadałoby to wyjaśnić.

**Comment by MartaNowaczyk** [comment]
@adamTynski potwierdzam wersję daneb-k
@deneb-k podaj link do tej informacji w pomocy. Zmienimy ją jeśli wprowadza w błąd.

**Comment by Draken79** [comment]
No nie do końca nie trzeba oznaczać jako wysłane. Zgodnie z informacja w pomocy Allegro, aby uzyskać automatycznie 5 gwiazdek za czas wysylki trzeba dodać numer przesyłki na czas oraz oznaczyc zamówienie jako wyslane. Rozumiem, że jedyna opcja to oznaczyć ręcznie i zgodnie z tym co napisane wyżej to się nie zmieni?

**Comment by MartaNowaczyk** [comment]
@Draken79 w podanym artykule nie ma informacji o tym, że trzeba oznaczyć jako "wysłane" tylko 

> zamówienie ma status “wysłane”

czyli tak jak pisałam wyżej, to status, który dostaniemy od przewoźnika, a nie ustawiona opcja dostępna w panelu allegro.

**Comment by Draken79** [comment]
to bardzo myląca ta informacja w pomocy. U przewoźników nie ma czegoś takiego jak 'wysłane'.  W Poczcie Polskiej jest 'nadanie', w InPost jest 'paczka nadana paczkomacie' lub 'paczka odebrana od nadawcy' w DPD jest 'paczka odebrana przez kuriera'. Może warto zmienić tę wprowadzającą w błąd informację?

**Comment by MartaNowaczyk** [comment]
rozumiem, poproszę osobę, która tworzyła ten artykuł o poprawę.

**Comment by Draken79** [comment]
przepraszam, że drąże temat, ale tutaj: 

https://allegro.pl/pomoc/dla-sprzedajacych/oceny-i-komentarze/kiedy-otrzymam-automatycznie-5-gwiazdek-za-czas-wysylki-WEDAgb6PDSo

jest informacja, że zamówienie musi mieć status 'wysłane' oraz musi być nadane w ciągu 24 godzin (potwierdzone u przewoźników) - czyli są to dwie różne rzeczy (status zamówienia i status przesyłki)

Jak to w końcu z tym jest?
kolejna błędna informacja?

**Comment by MartaNowaczyk** [comment]
Informacja nie jest błędna, bo takiego statusu wymagamy, ale od przewoźnika, a nie tego, który możesz ustawić ręcznie w panelu Allegro.

Zleciłam doprecyzowanie tej informacji w artykule w pomocy, żeby nie było więcej wątpliwości.

**Comment by Draken79** [comment]
Wymagacie państwo od przewoźnika aby zamówienie z Allegro miało status wysłane? Przecież przewoźnik nie wie czy w danej paczce jest akurat zamówienie z Allegro czy jakieś inne? 
Informacja jest błędna, a przynajmniej błędnie zredagowana, dziękuję za zlecenie doprecyzowania

**Comment by Draken79** [comment]
Nadal będę się upierał, że u przewoźników nie ma żadnych zamowien Allegro. Są po prostu numery przesyłek, ktorych status można śledzić na ich stronach. Ale nie ma tam żadnej informacji, czy w danej przesyłce jest zamowienie Allegro czy coś innego. Integracja to jedno, a sprawdzanie statusow przesylek to drugie. Poza tym nie wszyscy korzystaja z integracji. Czy w takim przypdku nie ma szans na automatyczne 5 gwiazdek (mimo wprowadzenua numeru przesyłki Poczty Polskiej i wysłaniu w ciągu 24h)?

**Comment by MartaNowaczyk** [comment]
@Draken79 wszystko co mogłam, po swojej stronie wyjaśniłam. Jeśli masz więcej uwag związanych z tym jak ta opcja działa na allegro, a nie z samym API - napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
