### ISSUE TITLE
Błąd autoryzacji DEVICE

### ISSUE THREAD

**Issue by autornet** [allegro/allegro-api#1850]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] z logowaniem lub autoryzacją

:beetle: **Błąd autoryzacji - 401**
Zgodnie z instrukcją zarejestrowałem sobie aplikację typu DEVICE i uzyskałem client_id oraz client_secret.

Próbuję się zalogować do REST API za pomocą przykładu z https://developer.allegro.pl/auth/#DeviceFlow:
curl -X POST
'https://allegro.pl/auth/oauth/device'
-H 'Authorization: Basic base64(client_id:client_secret)'
-H 'Content-Type: application/x-www-form-urlencoded'
-d 'client_id={client_id}'

Cały czas otrzymuję odpowiedź **Unauthorized** - błąd 401
Narzędzie, z którego korzystam to Embarcadero Delphi Tokyo 10.2

W responsie otrzymuję kod HTML allegro z komunikatem w środku:
Nie możemy wyświetlić strony
Numer błędu: **8204e9afc280ca2f**
numer błędu jest za każdym razem inny.

const client_secret = 'xxx';
      client_id = 'xxx';
var Base64: TBase64Encoding;
begin

  Base64 := TBase64Encoding.Create(5000,'');
  RestClient1.BaseURL := 'https://allegro.pl';
  RestRequest1.Resource := 'auth/oauth/device';
  RestRequest1.AddParameter('Authorization','Basic '+ Base64.Encode( client_id+':'+client_secret ), pkHTTPHEADER);
  RestRequest1.AddParameter('Content-Type','application/x-www-form-urlencoded', pkHTTPHEADER);
  RestRequest1.AddParameter('client_id',client_id, pkREQUESTBODY);
  RestRequest1.Execute;

Proszę o wsparcie.

**Comment by PawelTaberski** [comment]
Czy zarejestrowałeś nową aplikację jako device_code?

**Comment by autornet** [comment]
Tak

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne zapytanie (z uzupełnionymi danymi) jakie wysyłasz. Sprawdzimy w czym jest problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 1850 na GitHub-ie.
