### ISSUE TITLE
Czas aktywacji oferty

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#1851]
Dzień dobry,
Ile trwa zmiana statusu z "W trakcie aktywacji" na "Aktywna"? Wcześniej działało to niemal błyskawicznie. Dzisiaj od kilku godzin czekam na wystawienie ofert.

**Comment by PawelTaberski** [comment]
Problem występuje u Ciebie na produkcji czy na środowisku testowym?

**Comment by LukaszCierocki** [comment]
@PawelTaberski na środowisku testowym.

**Comment by PawelTaberski** [comment]
Rozumiem, pracujemy nad tym obecnie mamy pewne prace techniczne i mogą występować problemy z edycją i wystawianiem ofert na środowisku testowym.

**Comment by LukaszCierocki** [comment]
@PawelTaberski OK. Dzięki.
