### ISSUE TITLE
Command not found - seryjnie

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1852]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś dostaliśmy ponad 240 błędów typu: Command_Not_Found

Prośba o weryfikację na przykładowym R&R (wszystkie są tego samego Klienta)

REQUEST 2019-06-24 13:11:04.0685115 
curl -X GET \
  'https://api.allegro.pl/sale/offer-publication-commands/226f1312-1ad5-41e2-ac45-412fb38424ca' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization:  \

RESPONSE 2019-06-24 13:11:04.0997616 Duration: 31,2501ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "COMMAND_NOT_FOUND",
        "Details": null,
        "Message": "Command not found.",
        "Path": "",
        "UserMessage": "Nie znaleziono zlecenia."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": null,
  "TraceId": "5135b3591c37c7d3",
  "Error": true,
  "StatusCode": 404,
  "Message": "{\"errors\":[{\"code\":\"COMMAND_NOT_FOUND\",\"message\":\"Command not found.\",\"details\":null,\"path\":\"\",\"userMessage\":\"Nie znaleziono zlecenia.\"}]}"
}

**Comment by PawelTaberski** [comment]
Czy jest Pan pewny, że wcześniej użył tego UUID-a przy zadaniu zmiany stanu publikacji oferty? Bo sprawdzałem w logach i GET z takim UUID-em został wielokrotnie wywołany przed PUT-em.
