### ISSUE TITLE
[RestAPI] Masowe uzupełnienie External.Id - słaba wydajność

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1853]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Obecnie aby uzupełnić external.id trzeba wysłać całość do API. To powoduje że czasowo jest to mega niewydajne, przykład poniżej
Prośba o rozwiązanie masowego ustawienia tego pola, Klienci potrzebują go by mogli wiązać oferty ze swoimi wewnętrznymi systemami, w momencie jeśli coś zmieniają masowo na aukcjach obecna metoda jest mało wydajna

REQUEST 2019-06-18 13:06:33.7959588 
curl -X PUT \
  'https://api.allegro.pl/sale/offers/8114803778' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"7cdc1366-e39b-4d7d-a06a-7572e2ba468a"},"returnPolicy":{"id":"2f48f8d6-458c-4abf-8858-4f56bb8a5d19"},"warranty":null},"category":{"id":"257936"},"compatibilityList":null,"contact":null,"createdAt":"2019-05-20T09:20:37Z","delivery":{"additionalInfo":"","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"d3eb3afd-2dc2-4ec8-acf5-f2040a62b3be"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>test</p>\r\n"}]}]},"ean":null,"external":{"id":"363"},"id":"8114803778","images":[],"location":{"city":"dgfs","countryCode":"PL","postCode":"22-222","province":"DOLNOSLASKIE"},"name":"Kiwi: soczyste i treściwe","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]},{"id":"212742","rangeValue":null,"values":[],"valuesIds":["212742_257110"]},{"id":"202661","rangeValue":null,"values":[],"valuesIds":["202661_212845"]}],"payments":{"invoice":"NO_INVOICE"},"product":null,"promotion":null,"publication":{"status":"INACTIVE","endedBy":null,"duration":null,"endingAt":null,"startingAt":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"4","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":44,"unit":"UNIT"},"updatedAt":"2019-06-03T12:34:38.846Z","validation":{"errors":[],"validatedAt":"2019-06-03T12:34:38.846Z"}}' \

RESPONSE 2019-06-18 13:06:36.5709071 **Duration: 2774,9483ms**
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "7cdc1366-e39b-4d7d-a06a-7572e2ba468a"
      },
      "ReturnPolicy": {
        "Id": "2f48f8d6-458c-4abf-8858-4f56bb8a5d19"
      },
      "Warranty": null
    },
    "Category": {
      "Id": "257936"
    },
    "CompatibilityList": {
      "Items": null
    },
    "Contact": null,
    "CreatedAt": "2019-05-20T09:20:37Z",
    "Delivery": {
      "AdditionalInfo": "",
      "HandlingTime": "PT24H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "d3eb3afd-2dc2-4ec8-acf5-f2040a62b3be"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "TEXT",
              "Content": "<p>test</p>\r\n"
            }
          ]
        }
      ]
    },
    "Ean": null,
    **"External": {
      "Id": "363"
    },**
    "Id": "8114803778",
    "Images": [],
    "Location": {
      "City": "dgfs",
      "CountryCode": "PL",
      "PostCode": "22-222",
      "Province": "DOLNOSLASKIE"
    },
    "Name": "Kiwi: soczyste i treściwe",
    "Parameters": [
      {
        "Id": "11323",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "11323_1"
        ]
      },
      {
        "Id": "212742",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "212742_257110"
        ]
      },
      {
        "Id": "202661",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "202661_212845"
        ]
      }
    ],
    "Payments": {
      "Invoice": "NO_INVOICE"
    },
    "Product": null,
    "Promotion": null,
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": null,
      "EndingAt": null,
      "StartingAt": null
    },
    "SellingMode": {
      "Format": "BUY_NOW",
      "Price": {
        "Amount": "4",
        "Currency": "PLN"
      },
      "MinimalPrice": null,
      "StartingPrice": null
    },
    "SizeTable": null,
    "Stock": {
      "Available": 44,
      "Unit": "UNIT"
    },
    "UpdatedAt": "2019-06-18T11:06:31.621Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-06-18T11:06:31.621Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "3552b5a33259d85c",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PawelTaberski** [comment]
Rozumiem, że potrzebowałbyś metody, którą dodawałbyś external id bez potrzeby przesyłania całej oferty?

**Comment by SebastianOzdoba** [comment]
@PawelTaberski byłoby idealnie gdybym mógł przekazać nr oferty, external.id. 
Przy masowym ustawianiu tego obecna wydajność jest niska i Klienci narzekają że długo trwa.

**Comment by ChrupekV2** [comment]
@PawelTaberski jeszcze lepiej gdyby można było edytować jakikolwiek atrybut lub zestaw atrybutów bez konieczności przesyłania całej oferty. Chętnie załączyłbym instrukcje do tysięcy swoich aukcji ale konieczność wcześniejszego pobrania tych ofert skutecznie mnie zniechęca. Takie rozwiązanie działa na eBayu gdzie można puścić np. same parametry, opis, zdjęcia, warunki dostaw, zwrotów, itp.

**Comment by PawelTaberski** [comment]
Rozumiem przekazałem wasze sugestie. Jeśli zdecydujemy się wdrożyć takie rozwiązanie to oczywiście poinformujemy o tym w dedykowanym komunikacie.

**Comment by pkrzemo** [comment]
> @PawelTaberski byłoby idealnie gdybym mógł przekazać nr oferty, external.id.

Też potrzebowałbym tego pilnie... jak pewnie i większość pracujących z REST API. Jestem ZA!

> Przy masowym ustawianiu tego obecna wydajność jest niska i Klienci narzekają że długo trwa.

No i z pewnością "zabija" serwer w tym czasie... ;-)

**Comment by pkrzemo** [comment]
.." nr oferty, external.id." ...
Czy jest jakaś szansa, w najbliższym czasie, na taką modyfikację?
Czy coś się dzieje w tym kierunku?

**Comment by PrzemyslawLukanowski** [comment]
Nie mam informacji, aby taka funkcjonalność pojawiła się w najbliższym czasie. Tak jak pisał @PawelTaberski  - jeżeli zdecydujemy się na wdrożenie, poinformujemy o tym w odpowiednim komunikacie.
