### ISSUE TITLE
REST API, 2 questions possible issue

### ISSUE THREAD

**Issue by Layer5-PaulC** [allegro/allegro-api#1854]
Dear Allegro,

We have created an app in Allegro which we want to use to update stock on our products, and manage whether the offers are paused or live. This will be a script running from our warehouse software server so we do not want any interaction with user, ideally.

We have created the application of type DEVICE

I can use API to generate a token using https://allegro.pl/auth/oauth/device, then the user will authorize using "verification_uri_complete": "https://allegro.pl/skojarz-aplikacje?code=zszwahy7q"

I have also tried to generate a token using https://allegro.pl/auth/oauth/token?grant_type=client_credentials

**Question 1.**

\When I generate a bearer token using https://allegro.pl/auth/oauth/token?grant_type=client_credentials then this REST call fails https://api.allegro.pl/sale/products?phrase=2900042

403 Forbidden {
"error": "insufficient_scope",
"error_description": "Insufficient scope for this resource",
"scope": "offercore-service product-facade offer-product-suggester seller-offer-product-suggester"

}

This same call works OK when using a bearer token using https://allegro.pl/auth/oauth/device.

Is it possible to access products and update stock level with https://allegro.pl/auth/oauth/token?grant_type=client_credentials token?

**Question 2**

Using device credentials I can get successful json data returned. But I cannot return data for products, they are not found.

Here is an offer in our live account showing title and ean:
![mgcddebapehledah](https://user-images.githubusercontent.com/14859393/60025761-329c3380-9692-11e9-8f0a-3a179c88ae59.png)

This is the result of the call https://api.allegro.pl/sale/products?ean=5055920147309 application/vnd.allegro.beta.v1+json

{
"products": [],
}

How can i find the productId of this product if the search returns nothing?

I also used https://api.allegro.pl/sale/products?phrase=2900042   (application/vnd.allegro.beta.v1+json)

0 products were returned.

{
"products": [],
"categories": { ...
},
"filters": [],
"nextPage": null

}

**Comment by PawelTaberski** [comment]
Token which you get when you use client credentials flow after you decode it don't have information about user. So this token is on application and you can use it to get public data like categories, delivery method etc. To change some data on particular user account you must use device or code flow.

**Comment by Layer5-PaulC** [comment]
OK, thank you, so to run script to update stock quantity there must always be user activity to authorize, every day?

Please advise question 2 which was using device flow.

**Comment by PawelTaberski** [comment]
No only first time, after that you can extend token validity by using refresh_token. More information about that you can find [here](https://developer.allegro.pl/en/auth/#refresh-token).

**Comment by Layer5-PaulC** [comment]
Understood. Should I close this one and create a separate question for the other item?

**Comment by PawelTaberski** [comment]
About resource sale/products you must use flow device or code. 
Information what flow to use you will find in [our documentation](https://developer.allegro.pl/documentation/#tag/Products) in  resource description (authorization section). You can user client credentials only in resources where is information: 'bearer-token-for-application'

**Comment by Layer5-PaulC** [comment]
Hi Pawel, yes I am using device flow when this problem happens:

Using device flow I cannot find data for products, they are not found.

Here is an offer in our live account showing title and ean
https://user-images.githubusercontent.com/14859393/60025761-329c3380-9692-11e9-8f0a-3a179c88ae59.png

Using device flow this is the result of the call https://api.allegro.pl/sale/products?ean=5055920147309 application/vnd.allegro.beta.v1+json

{
"products": [],
}

There is no data in the products node, but as you can see in screengrab the ean is valid.

I also used https://api.allegro.pl/sale/products?phrase=2900042 (application/vnd.allegro.beta.v1+json)

0 products were returned.

{
"products": [],
"categories": { ...
},
"filters": [],
"nextPage": null

}

**Comment by PawelTaberski** [comment]
Now I understand :-)
You can assign offers to products only in selected categories in which we group offers with the same product. You will receive product data only in categories marked productListingEnabled:true after calling GET /sale/categories.
In categories 78720 is:
`"offersWithProductPublicationEnabled": false,`
More about assigning offers to a products you will find [here](https://developer.allegro.pl/en/productization/).
