### ISSUE TITLE
Nieudokumentowane eventsVersions w REST API https://api.allegro.pl/sale/offers i inna struktura odpowiedzi.

### ISSUE THREAD

**Issue by pkrzemo** [allegro/allegro-api#1855]
W rezultatach [https://api.allegro.pl/sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)
są dane które mogą mnie potencjalnie interesować ale nie ma ich w dokumentacji. Chodzi o ten fragment:
 "eventsVersions":{  
            "offerDataTimestamp":"2019-05-26T10:12:08.711Z",
            "currentPriceTimestamp":null,
            "inSaleAmountTimestamp":"2019-05-26T10:12:27.010Z",
            "soldAmountTimestamp":"2019-05-26T10:07:10.138Z",
            "offerRebatesTimestamp":null,
            "offerBadgesTimestamp":"2019-05-02T05:01:05.510Z",
            "watchersCountTimestamp":"+51364-03-19T17:56:32Z",
            "visitsCountTimestamp":"2019-06-02T02:05:43.893Z",
            "productVersion":null,
            "offerLabelsTimestamp":null,
            "productIdInternalChangedTimestamp":null
         },
W ogóle są różnice między dokumentacją a rzeczywistością. Chciałbym wiedzieć jak i kiedy są te pola uzupełniane i co znaczą, a wolałbym się nie domyślać.
Czy można liczyć na objaśnienia lub poprawę dokumentacji?

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa. W zgłoszeniu zaznacz, że dane dotyczą zgłoszenia numer 1855 na GitHub-ie.

**Comment by pkrzemo** [comment]
W jakim celu musi być "pełny request"? Przy każdym mam to samo, jest tam eventsVersions nieopisane w dokumentacji. 
Zapytanie się powiodło i zwróciło prawdziwe dane, nie jest więc to wynikiem błędu w zapytaniu tylko ktoś celowo to tak oprogramował. W dokumentacji nie ma nic o tym że dla różnych ofert struktura odpowiedzi jest całkowicie inna. Nie ma też nic o tym że można jakoś sterować strukturą zwracaną (parametryzować rodzaj zwracanej struktury danych i ich zakres) . Z resztą dla każdej oferty mam to samo (różni się tylko zawartością a nie strukturą).
Czy innym [https://api.allegro.pl/sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) nie zwraca eventsVersions  tylko mi?

**Comment by PawelTaberski** [comment]
Wysyłasz błędnie wartość nagłówka accept przez co otrzymujesz dane jakich nie wspieramy. Prześlij nagłówek w formie:
` -H 'Accept: application/vnd.allegro.public.v1+json' \`
