### ISSUE TITLE
GET sale/offers daty

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#1856]
Dlaczego endpoint GET sale/offers zwraca daty `updatedAt` w różnych formatach?
Dla większości aukcji jest poprawnie np.
"2019-06-25T09:33:32.15Z" - format Y-m-d\TH:i:s.uT
natomiast dla pojedynczych przypadków
"2019-06-17T11:20:28Z" - format Y-m-d\TH:i:sO.
Mechanizm jest podpięty u nas pod JMS Serializer, gdzie można określić tylko jeden format zwracany przez API, można format ujednolicić?

**Comment by PawelTaberski** [comment]
Podeślij proszę przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowego responsa, w którym zauważyłeś różne formaty daty. Zaznacz proszę, że dane są potrzebne do ticketa numer 1856 na GitHub-ie. Sprawdzimy to.

**Comment by j4r3kb** [comment]
Wysłane.

**Comment by j4r3kb** [comment]
Przypominam się z tematem. Z formularz kontaktowego otrzymałem odpowiedź, że tutaj będzie kontynuowany wątek.

**Comment by PawelTaberski** [comment]
Zgłosiłem ten przypadek do zespołu który odpowiada za te funkcjonalności do zbadania, jak otrzymam jakieś informacje to wrócę do Ciebie z odpowiedzią.

**Comment by j4r3kb** [comment]
@PawelTaberski coś się dzieje w tym temacie?

**Comment by PawelTaberski** [comment]
Zgłosiłem zadanie ujednolicenia tych formatów, prośba o jeszcze trochę cierpliwości.

**Comment by j4r3kb** [comment]
Coś wiadomo? Bot wątek już oznaczył ;)

**Comment by PawelTaberski** [comment]
@j4r3kb Ujednoliciliśmy formaty, jeśli zauważysz jeszcze jakąś rozbieżność daj proszę znać.

**Comment by j4r3kb** [comment]
@PawelTaberski 
przypadek z dziś:
```
Invalid datetime "2019-08-29T07:58:18Z", expected format Y-m-d\TH:i:s.uT.
```

**Comment by PawelTaberski** [comment]
Podeślij proszę trace-id requesta na jakiego otrzymałeś taki respons.

**Comment by j4r3kb** [comment]
@PawelTaberski `7b88d2d824dd143e`

**Comment by PawelTaberski** [comment]
@j4r3kb W jakim polu otrzymałeś taką datę, sprawdziłem po tym trace-id jaki podałeś ale nie widzę tam takiej daty.

**Comment by j4r3kb** [comment]
Data już jest inna bo pochodzi z kolejnego trace-id które podałem, ale kluczowy tutaj jest jej format a nie wartość, na pewno była zakończona `:xxZ`

**Comment by PawelTaberski** [comment]
@j4r3kb Rozumiem, przekazałem te informacje do zespołu, który nad tym pracuje.
