### ISSUE TITLE
TimeOuty na sale/offers

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#1857]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Prosty request np na: sale/offers?limit=1000&offset=5000

Przy 504 nie mam trace id, przy 503 trace id: d82b4b5bac365eb5

Hej!
Próbuję pobrać wszystkie oferty z konta i częściej niż pozytywną odpowiedź dostaję jakiś timeout, albo że serwis jest niedostępny.

## Przykładowy response dla 504:

```HTML
HTTP/1.0 504 Gateway Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

## Przykładowy response dla 503:

```
HTTP/1.1 503 Service Unavailable
X-RateLimit-Remaining: 9000
Trace-Id: d82b4b5bac365eb5
Content-Type: application/json; charset=utf-8
Content-Length: 207
X-RateLimit-Limit: 9000
Date: Tue, 25 Jun 2019 10:28:37 GMT

{"errors":[{"code":"ServiceUnavailableException","message":"An error occurred","details":null,"path":null,"userMessage":"The server is not able to complete the request. Please try again in a few minutes."}]}
```

Ten sam problem jest zarówno na zasobie beta jak i na public.
Niestety nie wiem od kiedy, na pewno wczoraj wieczorem występował ten problem.

Testowane z dwóch różnych komputerów i dwóch różnych lokalizacji (dla jednego konta)

**Comment by Radeq** [comment]
Inny status błędu

`https://api.allegro.pl/sale/offers?limit=50&offset=0&publication.status=ACTIVE`

Trochę ubolewam nad userMessage

`ElasticSearch exception while searching offers. Search criteria: Criteria{sellerId='xxx', offerId='null', searchPhrase='null', name='null', priceFrom=null, priceTo=null, statuses=[ACTIVE], endingDateFrom=null, endingDateTo=null, offerTypes=[], sort=[SortCondition{sortBy='offerId', direction='DESC', missing='_first'}], offset=0, limit=50, hasStandardizedDescription=null, emphasized=null, badgeCampaignId='null', badgeStatuses=[], includeHidden=false, productSuggestionStatus='null', excludedRebates=[], excludedCampaigns=[], labelsIds=[], internalProductChangeDate=null, hasAssignedProductAfterChange=null, externalIds='[]'}, original exception: Failed to execute phase [query], all shards failed; shardFailures {[SixHYQ75SVGGIUuu8HFCIg][listing-offers][3]: RemoteTransportException[[els-seller-offers-listing-krakow6-dc4][10.71.192.246:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TcpTransport$RequestHandler@32289244 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@48e71f67[Running, pool size = 13, active threads = 13, queued tasks = 1000, completed tasks = 24687679]]]; }`

Czy można prosić o jakiś mniej techniczny w polu userMessage (w message może zostać)?

**Comment by jakubmaguza** [comment]
Jeśli w czymś to pomoże, to ostatnie 20 requestów wygląda tak:
(liczba przed myślnikiem to ilość pobranych aukcji)
```
0 - GatewayTimeout
0 - ServiceUnavailable
0 - ServiceUnavailable
0 - GatewayTimeout
0 - GatewayTimeout
0 - GatewayTimeout
0 - BadGateway
0 - GatewayTimeout
0 - GatewayTimeout
0 - ServiceUnavailable
0 - OK
1000 - ServiceUnavailable
1000 - OK
2000 - GatewayTimeout
2000 - GatewayTimeout
2000 - GatewayTimeout
2000 - BadGateway
2000 - GatewayTimeout
2000 - GatewayTimeout
2000 - GatewayTimeout
```

**Comment by PawelTaberski** [comment]
Dzięki za przykłady i dane sprawę zgłosiłem do odpowiedniego zespołu z wysokim priorytetem.

**Comment by cyfranT** [comment]
Podpinam się pod temat - od 2,5 h nasz serwis nie działa, bo nie można pobrać nowych aukcji..

**Comment by mirkosmuz** [comment]
podpinam się

**Comment by neldh** [comment]
+1. Zresztą cały czas jest to w wątku https://github.com/allegro/allegro-api/issues/1806 , tylko należałoby chyba nazwę zmienić na "Czwarty tydzień..."

**Comment by jakubmaguza** [comment]
Wygląda to na błąd po przejściu wszystkich na nowe api.
Jako developerzy nie raz prosiliśmy o drobne zmiany w metodach żeby nie wysyłać siedmiu milionów requestów.
Nawet do prostej zmiany ceny nie ma endpointa w stylu:
{id:cena,
id:cena,
id:cena...}
Dla każdego produktu trzeba wysyłać oddzielny request.

Wiem, teraz macie dużo na głowie przez przejście z jednego API na nowe, ale pomyślcie o uproszczeniu updatów.

**Comment by pijablonski** [comment]
Problemy obserwujemy od ok. godziny 9. Prawie 50% prób pobrania własnych aukcji kończy się niepowodzeniem (błędy 503 / 504 w stosunku bliskim 1:2)

**Comment by pkrzemo** [comment]
> Dla każdego produktu trzeba wysyłać oddzielny request.

To to jeszcze małe piwo... aby zmienić 1  external.id w ofercie trzeba przesłać ... całą ofertę i przejść całą walidację.. to jest dopiero "wydajne". 
;-)

**Comment by neldh** [comment]
Dzisiaj znowu 504/500 na GET https://api.allegro.pl/sale/offers/{id} ... Cała masa, a wczoraj bylo tak dobrze...

**Comment by PawelTaberski** [comment]
@neldh Czy w dalszym ciągu masz problemy z tym zasobem przetestowałem i wydaje się, ze działa prawidłowo.

**Comment by neldh** [comment]
Wczoraj były problemy, ale dzisiaj wygląda na to że już wszystko ok. Jedynie GET https://api.allegro.pl/sale/shipping-rates/{uuid} zwrocilo 7 godzin temu 503 (jeden raz).
