### ISSUE TITLE
Lista wszystkich kategorii

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1858]
Czy jest jakaś opcja aby zapytać API o liczbę wszystkich kategorii aktualnie dostępnych? Trochę to takie głupie zmuszać klienta do czekania aż system ściągnie wszystkie dane bez wyświetlania paska postępu.
Proszę o wskazówkę :)

**Comment by PawelTaberski** [comment]
Obecnie nie ma możliwości, aby pobrać informacje ile jest wszystkich kategorii. Przekazałem Twoją sugestię, aby zwracać takie dane.

**Comment by WhoCares4400** [comment]
Posiadam plik "csv" oraz "json" z aktualną listą wszystkich kategorii Allegro.
Jeśli są Państwo zainteresowani to proszę kontakt pod adresem mailowym:
whocares4400dev@gmail.com
