### ISSUE TITLE
Błędne typy danych w dokumentacji

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1859]
Witam
Po stronie API samego przychodzą dane typu "string" natomiast w dokumentacji "String single". O ile można przeboleć case sensitive o tyle "string" i "String single" to już dwie różne bajki.
Chyba nikt nie zwrócił u was na to uwagi... zmarnowałem przez to 30 minut...

**Comment by PawelTaberski** [comment]
Jest to tylko nazwa przykładu parametru, typy danych są w przykładzie podane prawidłowo.
