### ISSUE TITLE
Zasób sale/offer-price-change-commands - zmiana ceny licytacji

### ISSUE THREAD

**Issue by hoobert89** [allegro/allegro-api#1860]
Cześć, w jaki sposób mogę ustawić nową cenę licytacji dla trwającej aukcji? Uderzenie `PUT` do zasobu `sale/offer-price-change-commands` zgodnie z dokumentacją może zmienić jej cenę "Kup teraz", natomiast chciałbym w jednym requescie zmienić obie ceny. Czy jest to możliwe?

Pozdrawiam!

**Comment by PawelTaberski** [comment]
Jest to tylko nazwa przykładu parametru, typy danych są w przykładzie podane prawidłowo.

**Comment by PawelTaberski** [comment]
Obie ceny w jednym requescie możesz zmienić zasobem PUT /sale/offers/{offerId}

**Comment by hoobert89** [comment]
czy mogę prosić o przykładowy payload?

**Comment by PrzemyslawLukanowski** [comment]
@hoobert89  Za pomocą GET /sale/offers/{offerId} pobierz daną ofertę, następnie poprzez PUT sale/offers/{offerID} prześlij wcześniej pobrane dane zmieniając ceny na np.  
```
    "sellingMode": {
        "format": "AUCTION",
        "price": {
            "amount": "300",
            "currency": "PLN"
        },
        "startingPrice": {
            "amount": "150",
            "currency": "PLN"
        },
        "minimalPrice": null
    },
```

Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/sale/#step-8-complete)

**Comment by hoobert89** [comment]
czyli trzeba całą aukcję wysłać, żeby zmienić tylko cenę. A ten endpoint `sale/offer-price-change-commands` przewiduje zmianę ceny licytacji?

**Comment by PrzemyslawLukanowski** [comment]
@hoobert89 Tak, trzeba wysłać całą aukcję, żeby zmienić tylko cenę. Endpoint `sale/offer-price-change-commands` zmienia tylko oferty Kup teraz, nie przewiduje zmiany ceny licytacji.

**Comment by hoobert89** [comment]
jasne, dziękuję za odpowiedź
