### ISSUE TITLE
[REST] 500 Internal Server Error przy offset większym niż 10000 dla GET offer-variants

### ISSUE THREAD

**Issue by ChrupekV2** [allegro/allegro-api#1861]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-Id →2f8a823ee6559852

Witam,
Jesteśmy w trakcie pobierania listy naszych wariantów (mamy ponad 18000) i po przekroczeniu offsetu 9950 przy limicie 50 zwraca błąd 500 Internal Server Error.
Czyżby był maksymalni limit w zasobie GET offer-variants?

**Comment by PawelTaberski** [comment]
Badamy temat, jak tylko otrzymam jakieś informacje dam znać.
