### ISSUE TITLE
[RestAPI] Wyszukiwanie External.Id

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1862]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Umożliwić wyszukiwanie po External.Id w postaci LIKE, CONTAINS.
Scenariusz:
- klienci wpisują w to pole własny kod towaru (ma on od 5 do kilkunastu znaków)
- aby wyszukać w ten sposób trzeba wpisać cały kod towaru bo filtry w restAPI nie działają w sposób "zaczyna się", "zawiera"

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem Twoje sugestie.

**Comment by alekskuc** [comment]
Dzień dobry, ponawiam prośbę o wdrożenie wyszukiwania w polu External.Id bez konieczności każdorazowego wpisywania całej wartości.

**Comment by PrzemyslawLukanowski** [comment]
Sugestię przekazałem już wcześniej do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie takiej funkcjonalności, poinformujemy o tym we właściwym komunikacie.
