### ISSUE TITLE
Wznawianie aukcji po zmianie kategorii: ERR_CANT_CHANGE_ITEM_TYPE_AFTER_BID(HTTP ERROR 422) 

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#1863]
Oferta została wystawiona, następnie zamknięta. Po tym w jakiś sposób uległa zmianie kategoria (albo klient zmienił, albo zmieniła się lekko struktura w Allegro), następnie próbowaliśmy wznowić ale otrzymaliśmy błąd: ERR_CANT_CHANGE_ITEM_TYPE_AFTER_BID.

Czego konkretnie dotyczy ten błąd? Pierwotnie myślałem, że złożonego bida w  licytacji, ale oferta jest na "kup teraz". 

Co powinniśmy sprawdzić przed próbą wznowienia?

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę pełnego curla z requestem i responsem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem Github #1863.

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że oferta jest aktywna. Czy problem nadal występuje?

**Comment by radoslawkoziol** [comment]
@PrzemyslawLukanowski  Pytanie dotyczy tego dlaczego wystąpił ten błąd. Co dokładnie oznacza. Musimy wiedzieć przed próbą wznowienia oferty czy powinna być wznowiona, czy wystawiona na nowo.

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem sprawę do głębszej analizy do odpowiedniego zespołu. Wróce z odpowiedzią, jak tylko się czegoś dowiem.

**Comment by radoslawkoziol** [comment]
@PrzemyslawLukanowski pojawiły się jakieś informacje w tej kwestii, czy nadal czekamy?

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, prośba o cierpliwość.

**Comment by radoslawkoziol** [comment]
@PawelTaberski up, żeby bot nie zamknął wątku.
