### ISSUE TITLE
GET order/checkout-forms - access denied

### ISSUE THREAD

**Issue by bulaaa** [allegro/allegro-api#1864]
Witam.
Przy pobieraniu listy zamówień metodą GET order/checkout-forms w zwrotce dostaję komunikat:

{"error":"access_denied","error_description":"Access is denied"}

Wszystkie wartości w nagłówkach są zgodnie z tymi z dokumentacji.

Ktoś ma pomysł czym to może być spowodowane i gdzie szukać błędu?

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
[Rozkoduj token](uhttps://jwt.io/) i upewnij się, że pobierasz zamówienie do zautoryzowanego usera.
