### ISSUE TITLE
Zmiany podkategorii w kategorii Książki po stronie allegro

### ISSUE THREAD

**Issue by PrzemekTurek2017** [allegro/allegro-api#1865]
Występuje problem: związany ze zmianami kategorii allegro
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Czy planowane są w dalszym ciagu prace związane ze zmianami kategorii po stronie allegro. Problem i błędy  mogą się pojawić gdy dany portal ma wykonane mapowanie swoich kategorii z allegro. Czy kategorie beda usuwane lub dodawane nowe. ?.
Za wpisem https://allegro.pl/dla-sprzedajacych/zmiany-w-ukladzie-kategorii-ksiazki-i-komiksy-WEVme4xk2I4 czy planowane są dalsze prace czy zostały ukończone ?.

**Comment by PawelTaberski** [comment]
Zmiany w kategoriach jak i parametrach mogę się pojawiać na bieżąco, aby dostosować się do asortymentu.
O planowanych zmianach w parametrach informacje znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach).
