### ISSUE TITLE
Pobieranie danych o zamówieniach - beta?

### ISSUE THREAD

**Issue by Inwestor1234** [allegro/allegro-api#1867]
Witam.
Mam takie pytanie - czy obecne metody beta do pobierania danych zamówień działają na tyle żeby móc przejść na nie? 

Metody do pobierania płatności są oznaczone albo jako beta dla REST albo jako deprecated WEBAPI więc jeden i drugi sposób jest teraz w wersji beta :D ? 

Termin wygaszenia metod do obsługi zamówień jak nie ma pełnego RESTApi do ich obsługi nie jest za dogodny. Możemy albo przejść 1 stycznia na RESTAPI i naprawiać sobie na żywo błędy albo możemy przejść sobie na wersje beta wcześniej i mieć błędy/problemy w dużej ilości złożonych zamówień bo będzie coś nie dotestowane

**Comment by PrzemyslawLukanowski** [comment]
Metody działają stabilnie i można z nich korzystać.

**Comment by Inwestor1234** [comment]
Dzięki - to trochę mnie uspokoiliście :)

Pytanie małe - czy znacie może datę kiedy rest api do obsługi zamówień będzie w pełni produktywnym środowiskiem już nie beta?

**Comment by PrzemyslawLukanowski** [comment]
@Inwestor1234 do końca trzeciego kwartału 2019.
