### ISSUE TITLE
doShowItemInfoExt

### ISSUE THREAD

**Issue by ronek22** [allegro/allegro-api#1868]
Cześć,

Czy jest już dostępny endpoint w REST api, który udostępnia publiczne dane o ofercie dowolnego sprzedawcy, tak jak doShowItemInfoExt w webApi. 
Jeśli nie to czy jest on w planach?

**Comment by PrzemyslawLukanowski** [comment]
@ronek22 Zasób, o którym mówisz, zostanie udostępniony w REST API w trzecim kwartale 2019. Harmonogram zmian możesz śledzić [tutaj](https://developer.allegro.pl/schedule/), w najbliższym czasie zostanie on zaktualizowany.

**Comment by ronek22** [comment]
Cześć,
Czy zasób ten został już udostępniony w REST API?

**Comment by TomekKaczmarek** [comment]
@ronek22 jeszcze nie, powinien się pojawić w ciągu kilku najbliższych miesięcy. Damy o tym znać w osobnym komunikacie.

**Comment by ronek22** [comment]
Cześć,
Jak wygląda sytuacja z tym zasobem, 30 ma być wyłączony z WebApi. Jest w planach dodanie go do REST API?
