### ISSUE TITLE
WebAPI pobranie starego opisu aukcji w formie HTML

### ISSUE THREAD

**Issue by krzysiu818** [allegro/allegro-api#187]
Jakim sposobem zaimplementować w programie C# funkcję pobierającą listę aktywnych aukcji z konta allegro, a następnie pobrać sam opis w formie HTML do danej aukcji?

**Comment by KrzysztofLukanowski** [comment]
Listę wszystkich aktywnych ofert na koncie pobierzesz za pomocą metody [doGetMySellItems](https://allegro.pl/webapi/documentation.php/show/id,1202#method-output). Następnie, na podstawie wartości zwróconych w polu itemId tablicy sellItemsList, przygotuj wywołanie metody [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842#method-output). W odpowiedzi tej metody, w polach FID 24 otrzymasz stary opis oferty w html/css , w polu FID 341 nowy opis oferty w json.

**Comment by KrzysztofLukanowski** [comment]
Nowy opis w FID 341 otrzymasz tylko wtedy, gdy wcześniej wystawiłeś ofertę z nowym opisem. Jeśli tego nie zrobiłeś, przygotuje opis oferty zgodnie ze wskazówkami z tego [poradnika](https://developer.allegro.pl/new_desc/).

**Comment by krzysiu818** [comment]
Tak, to rozumiem, ale nie rozumiem dlaczego w doGetItemFields w zwrotnej tablicy, aktualny stary opis dostaję jak wspomniałem w 12 , 13 lub 14 elemencie tablicy, bez żadnej zależności w której on się znajdzie i bez względu na wprowadzony FID.
