### ISSUE TITLE
Brak wszystkich ofert w /offers/listing

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#1870]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Mam klienta o loginie: kantorgdow (seller.id: 41319011) dla którego wykonuję metodę https://developer.allegro.pl/documentation/#operation/getListing filtrując oczywiście po parametrze seller.id i sterując parametrami offset oraz limit. W wyniku działania metody nie dostaje w odpowiedzi aukcji o identyfikatorach: 7913406715, 7686364003, 7849874808 mimo że należą do danego użytkownika

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem z wyszukaniem tych ofert. Sprawę zgłosiłem już do odpowiedniego zespołu.

**Comment by PawelTaberski** [comment]
@kormichu Sprawdź proszę teraz, oferty powinny już wyszukiwać się poprawnie.

**Comment by kormichu** [comment]
@PawelTaberski nadal nie widzę żadnej z 3 aukcji na liście, a pobieram wszystkie dostępne bo się zgadza liczba identyfikatorów aukcji z polem searchMeta.totalCount

**Comment by PawelTaberski** [comment]
Dzięki, przekazałem to do zespołu, jak tylko otrzymam jakieś informacje dam znać.
