### ISSUE TITLE
Błąd przy metodzie sale/offers

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1872]
Witam
Przy próbie wystawienia aukcji metodą sale/offers występuje taki błąd

Enter province for Poland, for other countries leave province empty

W kodzie mam tak
$data = new stdClass();
...
...
...
$data->location->city = $this->city;
$data->location->countryCode = "PL";
$data->location->postCode = $this->post_code;
$data->location->province = $this->province;
		
$out = $this->post("sale/offers",$data);

Jako province podaję "zachodniopomorskie" 

Proszę o pomoc co się tutaj dzieje dziwnego.
Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Zamiast "zachodniopomorskie" spróbuj podać "ZACHODNIOPOMORSKIE".

**Comment by qshop123** [comment]
W dokumentacji technicznej rozumiem informacji o tym nie ma?

**Comment by qshop123** [comment]
O super, przechodzi, co ciekawe a nawet bardzo ciekawe
ZACHODNIOPOMORSKIE - działa
ZACHODNIOPOMORSKIe - nie działa
ZaCHODNIOPOMORSKIE - działa
ZAcHODNIOPOMORSKIE - nie działa
ZAChODNIOPOMORSKIE - działa

ale dla ŚLĄSKIE już kompletnie nie działa....WTF?

**Comment by PrzemyslawLukanowski** [comment]
Informację na temat prawidłowych wartości dla pola province znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#new-offer).

**Comment by qshop123** [comment]
Okeeeejjjj, bez polskich znaków.

¯\_(ツ)_/¯
