### ISSUE TITLE
[RestAPI] Wyszukiwanie External.Id

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1873]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Pole External.Id jest CASE SENSITIVE, komu przyszło to do głowy, proszę się przyznać? :)
Prośba o zmianę
@MartaNowaczyk @PawelTaberski @PrzemyslawLukanowski

**Comment by neldh** [comment]
niby ciezko znalezc przypadek w ktorym byloby to zasadne, ale w sumie w czym ci to przeszkadza? wystarczy zmienic case przed zapisem/szukaniem i gitara. A nóż ktoś chce mieć case sensitive...

**Comment by SebastianOzdoba** [comment]
@neldh  bo nie ma spójności, tu masz case-sensitive ale już w wyszukiwaniu po tytule nie masz case-sensitive. Więc albo wszędzie jest albo wszędzie nie ma, tak to trzeba robić pierdołowate obejścia.
A w dokumentacji nie ma o tym słowa i przypadkowo takie rzeczy wychodzą :)

**Comment by PawelTaberski** [comment]
Zgłosiłem prośbę o doprecyzowanie tej opcji w dokumentacji.

**Comment by neldh** [comment]
@SebastianOzdoba 
Chyba że tak. Nie bylem świadom tej niespojności
