### ISSUE TITLE
https://api.allegro.pl/sale/products nie zwraca produktów

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#1875]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Otrzymałem informację od Allegro, że moje oferty zostały połączone z produktami (prawie 10 tysięcy). Jak wystawiam nowe oferty, to powyższa metoda nie zwraca żadnych produktów. Jako parametr przekazuję kod EAN. Metoda działa dla przykładowego kodu EAN z książką Harrego Pottera, jednak nie znajduje żadnych produktów wśród kategorii: uroda, zdrowie, dziecko - chociaż oferty z tych kategorii zostały połączone z produktami. Czy ja dobrze rozumiem, że moje oferty zostały połączone z produktami, jednak jeszcze te produkty nie są dostępne przez rest api w moich kategoriach?

**Comment by TomekKaczmarek** [comment]
Dzień dobry, zaczynamy nieśmiałe testy automatycznego identyfikowania ofert w kolejnych kategoriach. Powiązanie tych ofert z produktem nie ma w tej chwili żadnych dodatkowych konsekwencji, a powiadomienie mailowo wysłaliśmy z powodu błędu. Wkrótce udostępnimy możliwość dodawania produktów i łączenia ofert z produktami w kolejnych kategoriach - poinformujemy o tym w osobnym komunikacie.
