### ISSUE TITLE
Rejestracja aplikacji - głupoty w tabelce

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1877]
Witam
Zgłaszam głupoty w tabelce rejestracji aplikacji. Ogarnijcie to że, przechodzimy tutaj https://apps.developer.allegro.pl/ i mamy tabelkę

Klucze aplikacyjne REST API
A w tabelce kolumny :
- Nazwa aplikacji
- Typ
- Client ID / klucz WebAPI
- Client Secret
- Adresy przekierowań
- Opis

Dzwoni do mnie klient z pytaniem "Gdzie jest klucz WebAPI w tej tabeli po slashu bo on tego nie widzi"
Wstawiliście kolumnę "Client ID / klucz WebAPI" gdzie klucz WebAPI dotyczy SOAP a nie REST. W kolumnie "Client ID" ludzie po Client ID szukają slasha aby skopiować klucz WebAPI. Oczywiście najpierw mam telefony dlaczego nie ma pola w konfiguracji REST na klucz WebAPI

Wprowadzacie w błąd użytkowników na samym starcie rejestracji aplikacji.....HELOU?????
To jest na serio?

**Comment by PawelTaberski** [comment]
Klucz powinien być jeden per aplikacja, i do tego klucza powinni być podpięci wszyscy userzy korzystający z danej integracji. Jest to strona do zarządzania kluczami aplikacji, także użytkownicy korzystający z danej aplikacji nie powinni nawet na nią wchodzić.
Nie powinieneś zlecać każdemu userowi na zakładanie własnego klucza jest to błąd.

**Comment by qshop123** [comment]
Przecież aplikacje webowe pracują pod różnymi adresami, nie będą na jednym kluczu ciągnął setki klientów przecież... Skoro ktoś ma adres aplikacji https://a.pl a inny klient https://b.pl to nie będę ich pchał na jeden klucz, bo do klucza jest przypięty adres na sztywno...

**Comment by PawelTaberski** [comment]
Jeśli problemem jest dla Ciebie adres przekierowania to pamiętaj, że możesz skorzystać z autoryzacji typu device flow nie jest tam wymagany adres przekierowania.
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#DeviceFlow).

**Comment by neldh** [comment]
@PawelTaberski 
To trochę błędne koło. Jeśli klientem dla qshop są sprzedawcy posiadające jakieś sklepy internetowe, gdzie adres przekierowania służy tez do logowania poprzez Allegro to device flow chyba nie do konca na tym polega i logiczne wydaje się podejście jakie qshop w tej chwili opisał. W takiej sytuacji raczej każdy klient bedzie tą aplikację osobno rejestrował, właśnie np po to, żeby mieć oAuth do swojej strony a nie jakieś czary mary przez serwer dostawcy oprogramowania. Jeśli wam to przeszkadza, to znak że brakuje wam kolejnego flow.

**Comment by PawelTaberski** [comment]
Pamiętaj, że w przypadku code flow możesz podać wiele adresów przekierowań każdy od nowej linii. Zgodnie z instrukcją na stronie.
