### ISSUE TITLE
RestApi + tasks = bubel

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1879]
Ponad 5 minut czekałem, żeby otrzymać potwierdzenie wystawienia aukcji:
https://gist.github.com/PhotoSoft/2aeda15f3b6fdf15f32dfb4eace5a920

Przez WebApi wystawienie takiej aukcji zajmowało kilka sekund!

**Comment by PawelTaberski** [comment]
Każda zmiana na ofercie łącznie z wystawieniem w zależności od kolejki może zająć do godziny czasu. Czy w dalszym ciągu masz problem ze statusem tego zadania?

**Comment by TimothyKoval** [comment]
To jest kwestia wstecznej kompatybilności ze starą architekturą, czy tak będzie do końca świata?

**Comment by PawelTaberski** [comment]
Oczywiście jest to czas graniczny, ale tak jak wspomniałem wszystko zależy od obecnej kolejki zadań.

**Comment by lukada4100** [comment]
Najśmieszniejsze jest, to że zdarza się, że Api wciąż nie zwraca odpowiedzi dłuygo po tym, jak wszystkie zgłaszane metodą zmiany zostały już zrealizowane i są widoczne.
