### ISSUE TITLE
[RestAPI][Sandbox] Wystawianie

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1880]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Prośba o weryfikację
Coś się zepsuło na sandbox

Wysłam json:
"delivery":{"additionalInfo":"nic","handlingTime":"PT1440H","shipmentDate":null,"shippingRates":{"id":"fd684f27-219f-4cd2-875d-d2cd2220d89b"}}

Wraca:
"Delivery": null
"TraceId": "5842b2352978870c"

Generalnie nie da się wystawić ofert przez sandboxa

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba  Jaki status HTTP dostajesz jako odpowiedź? Wyślij proszę pełen request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1880.
