### ISSUE TITLE
sale/offers - problem z "delivery->handlingTime"

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1881]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wysyłaniu danych metodą sale/offers jest problem z czasem wysyłki

$data = new stdClass();
$data->delivery->handlingTime = "PT120H"
$this->post("sale/offers",$data);

Po wejściu do piaskownicy i otworzeniu aukcji do edycji czas wysyłki jest jakby nie wybrany - jak by nie było żadnej wybranej opcji domyślnej. API nie zwraca błędu związanego z niepodaniem tego parametru.

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Aby zapisać czas wysyłki w drafcie musisz jednocześnie przesłać również informacje o identyfikatorze cennika dostawy i formacie sprzedaży. Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/sale/#step-8-complete).
