### ISSUE TITLE
Problem z metodą "sale/shipping-rates"

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1882]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam
Dodałem do piaskownicy cenniki dostaw i przy próbie wywołania metody "sale/shipping-rates"
'sale/shipping-rates?sellerId=44189**7'

Otrzymuję komunikat 

{"errors":[{"code":"ConstraintViolationException","message":"An error has occurred","details":null,"path":"PublicShippingRatesResource$$EnhancerBySpringCGLIB$$20231aa6.getList.arg0","userMessage":"Transferred data is incorrect"}]}

Proszę o pomoc co jest znowu grane....
Dziękuję.

**Comment by qshop123** [comment]
Chyba w metodzie PublicShippingRatesResource w kodzie API macie konflikt pomiędzy klasami.

**Comment by PawelTaberski** [comment]
To błąd sprawę zgłosiłem już do odpowiedniego zespołu, poprawimy to.

**Comment by qshop123** [comment]
Ok, dziękuję za informację, ile czasu to zajmie mniej więcej?
Nie ukrywam że sprawa jest pilna...

**Comment by PawelTaberski** [comment]
Już pracujemy nad tym problemem, zadania założyłem z wysokim priorytetem. Prośba o cierpliwość.

**Comment by qshop123** [comment]
Ok, dziękuję, czekam zatem na rozwiązanie problemu.

**Comment by qshop123** [comment]
Coś wiadomo w temacie? Czas nagli i wszystko stoi, proszę o reakcję.

**Comment by PawelTaberski** [comment]
Pracujemy nad tym jak tylko otrzymam informacje, że udało się rozwiązać problem, to dam znać.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 korzystasz z błędnego zapytania, posługujesz się parametrem sellerId zamiast seller.id.

**Comment by qshop123** [comment]
Panie Przemysławie, doszedł Pan do tego po zapoznaniu się z moim ostatnim POSTem :)

**Comment by PawelTaberski** [comment]
@qshop123 Sprawdziliśmy i problemem jest zapytanie w zapytaniu jest sellerid a powinno być **seller.id**
