### ISSUE TITLE
Problem z "sale/offers"

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1883]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam
Kolejny problem dziwny.
Przy wywołaniu metody 

 "sale/offers"

["location"]=>
  object(stdClass)#11 (4) {
    ["city"]=>
    string(8) "Stargard"
    ["countryCode"]=>
    string(2) "PL"
    ["postCode"]=>
    string(6) "73-110"
    ["province"]=>
    string(18) "ZACHODNIOPOMORSKIE"
  } 

API zwraca 

You have to provide shipping rates and offer's location

Co jest nieprawdą, bo "offer's location" jest podane.
Proszę o pomoc.

**Comment by pkrzemo** [comment]
a podałeś shipping rates?

**Comment by qshop123** [comment]
Nie moge podać shipping rates bo jest jakis dziwny peoblem, opisalem to w zgloszeniu.

**Comment by pkrzemo** [comment]
bez "shipping rates" (czyli odpowiedniego id) nie przepuści niestety.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123  Sprawa powiązana ze zgłoszeniem  #1882, zgłosiliśmy to do odpowiedniego zespołu.
Na tę chwilę możemy zaoferować alternatywne rozwiązanie - utwórz cennik dostawy i ofertę testową przez front, do oferty testowej przypisz cennik, następnie pobierz ją przez API za pomocą GET sale/offers/{offerID}, identyfikator cennika dostawy znajduje się w polu “shippingRates”. Zdajemy sobie sprawę, że nie jest to idealne rozwiązanie, ale do czasu usunięcie problemu powinno pomóc.

**Comment by qshop123** [comment]
1. Cennik dostawy jest gotowy.
2. Cały problem polega na tym, że ofertę testową nie mogę utworzyć poprzez front, bo cała mechanika do tworzenia aukcji działa w oparciu o system zintegrowany z programem księgowym. Są tam powiązania dokumentów, stanów magazynowych itd.

Może po prostu podacie mi IDki z bazy danych dotyczące tego co zwraca dla mojego userId metoda sale/shipping-rates?sellerId=44189787 a ja będę leciał z tematem uruchomienia integracji dalej?

Będzie szybciej i bezpieczniej a ja nie będę odpytywał API o tą metodę. Poza tym sale/shipping-rates jest tylko w konfigu więce to się przeprowadza tylko raz przy ustawieniach konta.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Nie mamy takiej możliwości w środowisku testowym.

**Comment by qshop123** [comment]
Ok, proszę zatem o informację czy na loginie "mysql_query" konta produkcyjnego na Allegro.pl (nie sandbox) mogę sobie robić wszelkie testy i wystawiać aukcje testowe do momentu do kiedy API testowe nie będzie działać poprawnie?

**Comment by qshop123** [comment]
Proszę o odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Jesteśmy w trakcie rozwiązania tego problemu. Na chwilę obecną pobranie ID cennika możliwe jest jedynie w sposób, o którym pisałem wcześniej:

> utwórz cennik dostawy i ofertę testową przez front, do oferty testowej przypisz cennik, następnie  pobierz ją przez API za pomocą GET sale/offers/{offerID}, identyfikator cennika dostawy znajduje się w ?polu “shippingRates”. Zdajemy sobie sprawę, że nie jest to idealne rozwiązanie, ale do czasu usunięcie problemu powinno pomóc.

**Comment by qshop123** [comment]
ok, dziękuję za odpowiedź. 
Normalnie bym sobie sqlmapem wszedł do bazy i pobrał identyfikatory, ale chyba byście się wtedy obrazili prawda? :D
