### ISSUE TITLE
[RestAPI] Zdjęcie niepoprawne

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1884]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mamy taki problem, załączam R&D
Ręczne dodanie aukcji w Allegro działa, przez API nie
Dlaczego API zwraca błąd że zdjęcie jest niepoprawne?

REQUEST 2019-06-27 14:38:39.6457351
curl -X POST \
  'https://api.allegro.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"additionalServices":null,"afterSalesServices":null,"category":{"id":"5355"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":null,"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11b7e8/8e415d4c4ea791cfad8c2d087137"},{"type":"TEXT","content":"<h1>EVREE KREM DO RĄK CANNABIS & KUKUI 30ml</h1>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>EAN </p>\r\n\r\n<p>44-886</p>\r\n\r\n<h2>&nbsp;</h2>\r\n\r\n<h2>Pobudzający krem do rąk Do skory spragnionej odżywienia i odrobiny ekscytacji. Sięgnij po Pobudzający krem do rąk evree z regenerującym olejkiem cannabis oraz z egzotycznym olejkiem kukui, znanym z właściwości kojących i łagodzących. Skoncentrowana formuła wystarcza na bardzo długo, a błyskawiczne wchłanianie nie krępuje wolności rąk. Składniki aktywne: Olejek Cannabis transformuje wysuszoną skórę w zdrową, odżywioną i skąpaną w nawilżeniu. Kukui to słodka kompozycja egzotycznych akordów tropikalnych orzechów, a wytwarzany z nich olejek łagodzi podrażnienia i tworzy cienką warstwę ochronną. Pojemność 30 ml.</h2>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p></p>\r\n\r\n<p>EVREE</p>\r\n\r\n<p>&nbsp;</p>\r\n"}]}]},"ean":null,"external":{"id":"44-886"},"id":null,"images":null,"location":null,"name":"EVREE KREM DO RĄK CANNABIS & KUKUI 30ml","parameters":null,"payments":null,"product":null,"promotion":null,"publication":null,"sellingMode":{"format":"BUY_NOW","price":{"amount":"10.14","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":4,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

RESPONSE 2019-06-27 14:38:39.6613611 
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "VALIDATION_ERROR",
        "Details": "Invalid value: unknown",
        "Message": "Zdjęcia zawarte w opisie są niepoprawne.",
        "Path": "offerDto",
        "UserMessage": "Zdjęcia zawarte w opisie są niepoprawne."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": null,
  "TraceId": "6b8a0f6a604e48b7",
  "Error": true,
  "StatusCode": 422,
  "Message": "{\"errors\":[{\"code\":\"VALIDATION_ERROR\",\"message\":\"Zdjęcia zawarte w opisie są niepoprawne.\",\"details\":\"Invalid value: unknown\",\"path\":\"offerDto\",\"userMessage\":\"Zdjęcia zawarte w opisie są niepoprawne.\"}]}"
}

**Comment by imper86** [comment]
@SebastianOzdoba tak na szybko to widzę że sekcję "images" masz null, więc takie coś nie przejdzie. W images musisz mieć wszystkie zdjęcia, które umieszczasz w opisie.

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba zdjęcia musisz najpierw dodać do galerii oferty (w "images"). Przykład, jak to zrobić, znajdziesz w [naszym poradniku](https://developer.allegro.pl.allegrosandbox.pl/sale/#step-8-complete).

**Comment by SebastianOzdoba** [comment]
Faktycznie, mój błąd, dzięki, zamykam
