### ISSUE TITLE
GET /order/events brak zwracanych danych, response 200

### ISSUE THREAD

**Issue by pabloseek** [allegro/allegro-api#1885]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/order/events
https://api.allegro.pl.allegrosandbox.pl/order/events?limit=1000

trace-id=3cfea48693d5c0f8

Próbuję pobrać dziennik zdarzeń przy użyciu GET/order/events
Mimo tego, że dla konta na sandboxie mam sporo zamówień (w tym niektóre utworzone zostały dziś), response w contencie zawiera pustą listę:
{"events":[]}
Api nie zwraca błędu:
StatusCode: OK, Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8, Content-Length: 13)
Nie używam parametru from, więc powinno pobrać wszystko z 60 dni. Niestety nic nie pobiera.
Co gorsza - w piątek 28.06 dane były przekazywane.
W dniu dzisiejszym GET nie pobiera niczego

**Comment by PrzemyslawLukanowski** [comment]
@pabloseek [Rozkoduj swój token](https://jwt.io/) i zweryfikuj, czy jesteś zalogowany na odpowiedniego usera.
