### ISSUE TITLE
Pytanie o zestawy 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1886]
Proszę o doprecyzowanie jako że brakuje takich informacji w dokumentacji
/sale/loyalty/promotions

Scenariusz: 
Mamy 2 oferty A (5szt) i B (3szt)
Tworzymy z tego zestaw 
A - po 2 szt
B - 1 szt 

Jak rozumiem, Allegro samo wylicza ilość zestawów które można złożyć ? 
Drugie pytanie, co w przypadku gdy zamkniemy ofertę A - czy zestawy nadal będą dostępne i mamy sami pilnować ich deaktywacji czy też po waszej stronie taki zestaw się z automatu zdeaktywuje ?

**Comment by yncki** [comment]
@PrzemyslawLukanowski ping

**Comment by PrzemyslawLukanowski** [comment]
@yncki Nie powinieneś utworzyć większego zestawu niż na podstawie ilości produktów, które masz w ofertach. W przypadku zamknięcia lub wyprzedania oferty A zestaw powinien być automatycznie dezaktywowany. 
Wykryliśmy błąd w działaniu tej usługi, zgłosiłem to do odpowiedniego zespołu. Poinformuję po otrzymaniu informacji zwrotnej.

**Comment by yncki** [comment]
@PrzemyslawLukanowski dzięki, dodatkowe pytania 

- czy po uzupelnieniu stocków , zestaw się sam ponownie aktywuje ? Brakuje mi dokładnej informacji jakie są zasady automatycznej aktywacji / deaktywacji zestawów. 

- Czy jest jakiś limit na ilość utworzonych zestawów ?

**Comment by yncki** [comment]
@PrzemyslawLukanowski up.

**Comment by PrzemyslawLukanowski** [comment]
@yncki  
Po uzupełnieniu stocków zestaw się sam ponownie nie aktywuje.
Do jednej oferty możesz dodać maksymalnie 7 zestawów. Więcej informacji znajdziesz w [naszym poradniku](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/zestawy-produktow-jak-dzialaja-i-jak-je-tworzyc-EY4g8Ox0gcL).
