### ISSUE TITLE
Błędne ID metod dostawy w zamówieniach?

### ISSUE THREAD

**Issue by TomekDuszynski** [allegro/allegro-api#1887]
Występuje problem: 
 - [X] z zasobem REST API
 - [?] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dla metody dostawy **Punkty Poczta pobranie**
otrzymujemy e36c9ccf-e341-49a9-8fa0-f073dcd61210
według dokumentacji EN powinno być 88f677d9-c125-45e0-bdf0-f965826542a9

Dla metody dostawy **Punkty Poczta, Żabka, Orlen, Ruch**
otrzymujemy d44995ed-edd2-4abb-999f-a56bd0f12a68
według dokumentacji EN powinno być 849a8308-240d-4045-ab30-f8207815bce4

![image](https://user-images.githubusercontent.com/52100383/60424628-054f0880-9bf1-11e9-93c8-1529dfc206b6.png)

**Comment by PrzemyslawLukanowski** [comment]
@TomekDuszynski  Zweryfikowałem metody dostawy poprzez GET sale/delivery-methods i API zwraca prawidłowe dane. Każdy z poniższych identyfikatorów to inna metoda dostawy.

**Allegro Punkty Poczta pobranie**
otrzymujemy: 88f677d9-c125-45e0-bdf0-f965826542a9

**Allegro Punkty Poczta, Żabka, Orlen, Ruch**
otrzymujemy:  849a8308-240d-4045-ab30-f8207815bce4

**Punkty Poczta pobranie**
otrzymujemy:  e36c9ccf-e341-49a9-8fa0-f073dcd61210

 **Punkty Poczta, Żabka, Orlen, Ruch**
otrzymujemy:  d44995ed-edd2-4abb-999f-a56bd0f12a68

**Comment by TomekDuszynski** [comment]
Dziękuję za wyjaśnienia. Teraz widzę w czym problem. Poczta stosuje inne nazewnictwo tych przesyłek w swojej dokumentacji ale rzeczywiście identyfikatory się zgadzają.

**Comment by sq9atk** [comment]
Może pora zaktualizować tablicę z metodami dostawy? Jest niepełna.
https://developer.allegro.pl/news/2019-01-30-metody_dostawy/

**Comment by PrzemyslawLukanowski** [comment]
@sq9atk Odpisałem w wątku #553.
