### ISSUE TITLE
Lista zwrotów

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1888]
Na stronie Allegro, w zakładce Zwroty, można przejrzeć listę zwrotów (odstąpień od umowy) wraz z podanym przez klienta numerem konta bankowego oraz łączną kwotą do wypłaty.
Czy jest szansa pobrania tej listy lub jakiegoś jej odpowiednika za pomocą WebApi lub restAPI?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie ma takiej możliwości przez API, tylko przez front.
