### ISSUE TITLE
RESTAPI Zmiana ilości

### ISSUE THREAD

**Issue by autornet** [allegro/allegro-api#1894]
W jaki sposób można po autoryzacji zmienić dostępną ilość na konkretnej aukcji za pomocą metod RESTAPI?

**Comment by PrzemyslawLukanowski** [comment]
@autornet Dostępną ilość zmienisz za pomocą zasobu 
[PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/my_offers/#3g).

Zmianę możesz również wykonać za pomocą zasobu GET /sale/offers/{offerID} (pobranie całej oferty), a następnie poprzez PUT /sale/offers/{offerID} (zmiana wartości dla "stock" -> "available") przesyłasz zaktualizowaną ofertę. Musisz pamiętać o tym, że pomimo zmiany dla tylko jednej wartości, należy przesłać całą ofertę. Więcej na ten temat znajdziesz w [naszym poradniku.](https://developer.allegro.pl/my_offers/#2)

**Comment by autornet** [comment]
Może to ważne, nadmienię, że mam aplikację zarejestrowaną jako DEVICE

A ta metoda działa tylko przy autoryzacji (bearer-token-for-user)

 

Ponowie pytanie: Jak zmienić ilość po autoryzacji gdy posiadam token dla aplikacji typu (bearer-token-for-application) ?

**Comment by PrzemyslawLukanowski** [comment]
Token , o którym piszesz (bearer token for application) nie ma kontekstu usera  i służy tylko do dostępu do zasobów publicznych typu kategorie, wyszukiwarka ofert. Aby móc dokonać zmiany, o którą pytasz, musisz mieć token usera, do którego należą oferty. Jak to zrobić, dowiesz się z [naszego poradnika.](https://developer.allegro.pl.allegrosandbox.pl/auth/#DeviceFlow) (autoryzacja Device Flow).
