### ISSUE TITLE
Ignorowanie filtrów lineItems.boughtAt.lte/gte w order/checkout-forms

### ISSUE THREAD

**Issue by mroocoo** [allegro/allegro-api#1895]
Występuje problem: 
 - [X] z zasobem REST API
 - [?] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zapytanie o checkout-forms ignoruje filtry lineItems.boughtAt.lte/gte - na koncie są 4 zamówienia - 3 z 06.05.2019 i 1 z 20.05.2019 a jakich bym kombinacji z filtrami nie robił zawszę dostaję 4 zamówienia w odpowiedzi, np. na poniższe zapytanie:
curl -X GET -H 'Authorization: Bearer ...' -H 'Accept: application/vnd.allegro.beta.v1+json' 'https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?lineItems.boughtAt.lte=2019-05-18T22%3A00%3A00.000Z&offset=0' -D -

Traceid: 176f1567a63973c

Wydaje mi się, że jeszcze kilka dni temu filtrowanie działało.

**Comment by PrzemyslawLukanowski** [comment]
@mroocoo Zweryfikowałem to i w środowisku testowym występuje błąd. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by vendoremo** [comment]
Ja mam ten sam problem w środowisku produkcyjnym. Właśnie zaimportowało mi 1200 zamówień z lutego..... Proszę o informację kiedy ten problem zostanie rozwiązany.

**Comment by akarasek** [comment]
U nas jest ten sam problem na produkcji. Do tej pory ściąganie zamówień z ostatnich x minut działało poprawnie, dzisiaj ściągane jest wszystko od lutego włącznie bez względu na przekazane parametry lineItems.boughtAt.lte/gte. Kiedy można spodziewać się rozwiązania problemu?

**Comment by PrzemyslawLukanowski** [comment]
@vendoremo Wyślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) swój login  oraz pełen request i response. W zgłoszeniu dopisz GitHub #1895.

**Comment by dominikworkroom** [comment]
Ja również mam ten sam problem na środowisku testowym

**Comment by akarasek** [comment]
Informuję, że od 2 godzin znowu działa u nas poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować w środowisku testowym.

**Comment by vendoremo** [comment]
A czy w środowisku produkcyjnym też już naprawione?

**Comment by PawelTaberski** [comment]
Tak, problem nie powinien już występować także a produkcji.
