### ISSUE TITLE
cenniki dostaw

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#1897]
Dzień dobry
kilka godzin temu przeedytowałem cennik dostawy o id 5672735d-0511-4f9c-ad21-29d09f019e36. Usunąłem jeden ze sposobów dostawy. Przed edycją były dwa sposoby, po edycji jest jeden.
Cennik ten używany jest w wielu moich ofertach, np w ofercie nr 7855857726.
Problem polega na tym, że mimo iż minęło kilka godzin, sposoby dostaw prezentowane w ofertach są nadal takie jak w cenniku sprzed edycji, nie uwzględniają wprowadzonych zmian.

**Comment by PrzemyslawLukanowski** [comment]
@dostawcaopon  Zweryfikowałem to i przez API zwracana jest jedna metoda dostawy, tymczasem na froncie wciąż widnieją dwie. Zgłosiłem błąd do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@dostawcaopon Widzę, że dla oferty 7855857726 cennik został zaktualizowany. Czy problem występuje jeszcze w innych ofertach?

**Comment by dostawcaopon** [comment]
w tej chwili jest już ok, we wszystkich ofertach
