### ISSUE TITLE
Czy można w jakiś sposób pobrać imię i nazwisko kupującego do zamówienia?

### ISSUE THREAD

**Issue by ircykk** [allegro/allegro-api#1898]
Czy można w jakiś sposób pobrać imię i nazwisko kupującego do zamówienia gdy ten wybrał dostawę bez adresu jak paczkomat?

W soap api było możliwość pobrania danych z konta klienta.

**Comment by PrzemyslawLukanowski** [comment]
@ircykk  Imię i nazwisko kupującego pobierzesz za pomocą zasobu GET /order/checkout-forms/{checkoutFormId}, ale tylko dla zamówień w statusie READY_FOR_PROCESSING, czyli opłaconych, z wypełnionym formularzem dostawy.
Więcej na ten temat przeczytasz w [naszym poradniku.](https://developer.allegro.pl.allegrosandbox.pl/orders/#04)

**Comment by ircykk** [comment]
Tak, wiem zgodnie z poradnikiem:
```    "status": "READY_FOR_PROCESSING",                       -- status płatności
    "delivery": {                                           -- dane adresowe klienta z formularza 
                                                            dostawy
        "address": {
            "firstName": "Tomasz",                          -- imię
            "lastName": "Nowak",                            -- nazwisko
            "street": "Bułgarska 6990",                     -- ulica
            "city": "Poznań",                               -- miasto
            "zipCode": "18-282",                            -- kod pocztowy 
            "countryCode": "PL",                            -- kod kraju
            "phoneNumber": "000333666"                      -- numer telefonu kupującego
                                                            z formularza dostawy
        }, 
```

mamy adres ale TYLKO kiedy wysyłka wymaga adresu, np. kurier, dla odbioru osobistego nie ma nazwiska. Czy można pobrać imię i nazwisko kupujące (nie to z adresu dostawy/faktury tylko to z konta allegro - imię i nazwisko kupującego)?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę jest to niemożliwe. W najbliższym czasie rozbudujemy sekcję Buyer, gdzie takie informacje będą dostępne.

**Comment by ircykk** [comment]
To super czekam zatem na update, to bardzo ważne żeby było obok loginu również imię i nazwisko.

**Comment by Radeq** [comment]
@ircykk , wszyscy czekamy już od marca 2019 https://github.com/allegro/allegro-api/issues/1436

**Comment by neldh** [comment]
W zasadzie takie dane powinny być dostępne od samego początku...
Czyżby ktoś nie wpadł na to, że kupujący może być kimś innym niż odbiorca?

**Comment by ircykk** [comment]
Nom zgadza się, mamy tylko adres dostawy w zamówieniu i to też nie zawsze. Gdyby był chociaż endpoint pozwalający pobrać dane klienta osobno np. po id czy loginie to pół biedy.

**Comment by PrzemyslawLukanowski** [comment]
@ircykk takiego endpointu nie przewidujemy, kupujacy czesto wpisywali w zamowieniu inny adres dostawy, niż ten przypisany do konta, co przy pobieraniu adresu z danych konta powodowało wysyłkę na błędy adres.

**Comment by ircykk** [comment]
Ale obecnie jeśli zamówienie jest best adresu to nie mamy żadnej informacji o kliencie, obok loginu imię i nazwisko wydaje się obowiązkowym. W respoone mamy ładnie oddzielone dane konta i adresu i w danych konta wystarczy dodać imię i nazwisko i po sprawie bo obecnie mamy takie zamówienie widmo trochę.

Nie jest potrzebny cały adres klienta ale jedynie imię i nazwisko  i będzie ok.

**Comment by mmgithubpl** [comment]
@PrzemyslawLukanowski niewazne co wpisze kupujacy w danych adresowych / wazne jest aby byl dostep do danych platnika (dane adresowe konta allegro) oraz dane odbiorcy(dane adresowe punktu dostawy). bez tego przeniesienie integracji z webapi na restapi w naszym przypadku jest niemozliwe.

**Comment by TomekKaczmarek** [comment]
@ircykk tak, jak pisaliśmy - planujemy rozbudować informacje o kupującym w zamówieniu, które nie ma jeszcze statusu READY_FOR_PROCESSING.

@mmgithubpl Dane płatnika zwracamy, gdy kupujący zaznaczył, że chce do zamówienia fakturę. Procesu w REST API nie są i z założenie nie miały być spójne z WebAPI. WebAPI udostępniliśmy wiele lat temu i procesy z tamtego interfejsu należało odświeżyć i dostosować do tego, jak obecnie działa platforma.

**Comment by mmgithubpl** [comment]
@TomekKaczmarek ja wszystko rozumiem ale to nawet nie odpowiada na pytanie w jaki sposob uzyskac informacje na temat danych platnika/kontrahenta glownego konta allegro z ktorego jest dokonywany zakup / bez wybranej opcji faktury.

**Comment by TomekKaczmarek** [comment]
@mmgithubpl tak, jak pisalismy powyżej, rozbudujemy sekcję o kupującym w odpowiedzi dla tej metody. Jakich danych potrzebujesz i w jakim celu?

**Comment by mmgithubpl** [comment]
@TomekKaczmarek dokladnie takie jak zwracane przez /order/checkout-forms/{id} 
w obiekcie CheckoutFormDeliveryAddress

**Comment by TomekKaczmarek** [comment]
@mmgithubpl dzięki, w jakim celu są Ci one potrzebne? W jakich procesach je wykorzystujesz?

**Comment by mmgithubpl** [comment]
@TomekKaczmarek zakladamy kontrahentow w rejestrze / platnik (dane kontrahenta BRAK) -> odbiorca (z fomularza dostawy OK) -> miejsce dostawy (z formularza dostawy OK)

**Comment by mmgithubpl** [comment]
@TomekKaczmarek kiedy mozna sie tego spodziewac bo nie ukrywam ze zalezy nam na czasie ?

**Comment by TomekKaczmarek** [comment]
@mmgithubpl dzięki za odpowiedź, przypominam jednak, że zgodnie z regulaminem Allegro, możecie wykorzystać dane kupujących tylko do realizacji zamówienia. Nie można ich rejestrować.

Zasób powinniśmy rozszerzyć o nowe dane w ciągu najbliższego miesiąca.

**Comment by mmgithubpl** [comment]
@TomekKaczmarek : czy jest szansa ze rozszerzenie sekcji buyer zgodnie z planowanych terminem najblizszego miesiaca ?

**Comment by TomekKaczmarek** [comment]
@mmgithubpl pracujemy nad tematem - damy znać osobnym komunikatem, jak tylko uda nam się wdrożyć tę zmianę.
