### ISSUE TITLE
Błędy walidacji parametrów na podstawie EAN

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#1899]
Witam
Zauważyłem, że walidujecie po swojej stronie podane parametry w przypadku gdy podany jest kod EAN. 
Przykładowo dla EAN 9780552173100 otrzymuję następujące:
"Validation": {
		"Errors": [{
				"Code": "VALIDATION_ERROR",
				"Details": "",
				"Message": "Invalid parameter Rok wydania (74) value for offer with product. Value should be \"2018\".",
				"Path": "",
				"UserMessage": "Invalid parameter Rok wydania (74) value for offer with product. Value should be \"2018\"."
			}, {
				"Code": "VALIDATION_ERROR",
				"Details": "",
				"Message": "Offer category doesn't match product category - 91483.",
				"Path": "",
				"UserMessage": "Offer category doesn't match product category - 91483."
			}, {
				"Code": "VALIDATION_ERROR",
				"Details": "",
				"Message": "Invalid parameter Autor (223489) value for offer with product. Value should be \"Jack Ewing\".",
				"Path": "",
				"UserMessage": "Invalid parameter Autor (223489) value for offer with product. Value should be \"Jack Ewing\"."
			}
		],
		"ValidatedAt": "2019-07-03T06:29:00.796Z"
	}
Rok wydania książki w moim przypadku to 2017 (jest to fizycznie wydrukowane w książce), autor przekazany to : jack Ewing, a kategoria to 89274. 

Po usunięciu EANa robi się jeszcze ciekawiej bo dochodzi kolejny błąd walidacji
{
				"Code": "VALIDATION_ERROR",
				"Details": "",
				"Message": "Missing EAN for offer with product.",
				"Path": "",
				"UserMessage": "Missing EAN for offer with product."
}

To dość agresywne podejście. Rozumiem matchowanie po EANie, ale wymaganie konkretnego roku wydania po samym tytule to już błąd.

**Comment by TomekKaczmarek** [comment]
Na podstawie kodu EAN i odpowiednich parametrów automatycznie łączymy oferty z produktem - piszemy o tym [artykule na stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/jak-powiazac-oferte-z-produktem-VEWrZz6n4sv).

Założenie jest takie, że dane produktu i powiązanej z nim oferty muszą być spójne, o tym piszemy w poradniku, [jak powiązać ofertę przez REST API Allegro](https://developer.allegro.pl/productization/#offer). Czyli w ofercie musisz przekazać dokładnie te same dane, które otrzymujesz przez GET /sale/products/{product.id} dla danego produktu.

Jeśli dla jakiegoś produktu mamy nieprawidłowe dane, możesz nam to zgłosić przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Docelowo udostępnimy osobny zasób w REST API, który pozwoli na zgłaszanie błedów i uzupełnianie danych o produkcie.

**Comment by dol1234** [comment]
W tym konkretnym requescie nie ma ISBN ani EAN, co oznacza że matchujecie produkt po tytule/autorze co samo w sobie jest naiwnym podejściem (chyba nie muszę tłumaczyć dlaczego).
Przykro mi, ale tego typu wymagania są nieprofesjonalne - nie jestem Waszym dostawcą treści i nie będę za darmo Wam ich poprawiał.

**Comment by TomekKaczmarek** [comment]
@dol1234 nie chodzi o request, chodzi o sam fakt tego, że oferta jest powiązana z produktem. Jeśli tak jest - występują warunki walidacyjne, o których pisałem wcześniej - dane oferty muszą być spójne z produktem. Podaj ID oferty, sprawdzę jej dane i zobaczę, czy jest powiązana z produktem.

**Comment by dol1234** [comment]
Numer oferty: 8269011857

**Comment by TomekKaczmarek** [comment]
Nie mogę znaleźć oferty o takim ID. Sprawdź proszę, czy ID jest poprawne.

**Comment by dol1234** [comment]
Tak, jest poprawne (ale oferta nie jest aktywowana)

**Comment by TomekKaczmarek** [comment]
@dol1234 czyli oferta nigdy nie była aktywna. Do nieaktywnych ofert nie przypinamy automatycznie produktów, także coś musiało się wydarzyć po Twojej stronie. Draft mogę sprawdzić dokładniej, jeśli podasz mi identyfikator sprzedawcy.

**Comment by dol1234** [comment]
Nie wiem co miałoby się wydarzyć po mojej stronie. Mam kilkadziesiąt aukcji na których  wymusiliście nawet zmianę kategorii bezpośrednio w walidacji przy wystawianiu drafta. 
Jak przesłać id sprzedawcy prywatnym kanałem?

**Comment by TomekKaczmarek** [comment]
@dol1234 Id lub login klienta nie jest poufną daną, ale jeśli nie chcesz sie nim dzielić publicznie, napisz do nas przez formularz kontaktowy, zaznacz, że sprawa dotyczy API Allegro i podaj link do tego wątku na Githubie.

**Comment by TomekKaczmarek** [comment]
@dol1234 otrzymałem id sprzedawcy, w ofercie ustawiony jest produkt - ID: cbfb84b4-6978-45cc-81e6-8c977d49899f. Sprawdziliśmy nasze mechanizmy, żaden nie ustawił w niej automatycznie produktu.

Założenie jest takie, że dane produktu i powiązanej z nim oferty muszą być spójne, o tym piszemy w poradniku, jak powiązać ofertę przez REST API Allegro. Czyli w ofercie musisz przekazać dokładnie te same dane, które otrzymujesz przez GET /sale/products/{product.id} dla danego produktu.

Możesz tez usunąć ID produktu z oferty, wtedy nie będziesz musiał wprowadzać w niej danych zgodnych z produktem.

**Comment by dol1234** [comment]
Faktycznie, nie zauważyłem w requescie podpiętego produktu, przepraszam.
Rozumie, że macie mechanizm, który automatycznie podpina produkt pod już wystawione aukcje?

**Comment by TomekKaczmarek** [comment]
@dol1234 tak - ale tylko wtedy, gdy dane oferty są spójne z produktem (czyli walidacja działa w drugą stronę - jeśli w ofercie jest inny EAN, lub parametry maja inne wartości, niż mamy przy produkcie - nie powiążemy z taka oferta produktu).

**Comment by dol1234** [comment]
Rozumiem, ale w ten sposób tworzycie ofertę która nie może być wystawiona ponownie (bez usunięcia id produktu lub ponownej walidacji, ustawienia brakujących parametrów i usunięcia nieistniejących). Wszystko jasne, dziękuję za pomoc.
