### ISSUE TITLE
Parametry kategorii pobrane metodą doGetSellFormFieldsForCategory

### ISSUE THREAD

**Issue by hoobert89** [allegro/allegro-api#19]
Szanowni Państwo,

mamy rozbieżność w kategoriach Allegro pobieranych przez API oraz wyświetlanych przez Państwa interfejs. Mam na myśli pole `sellFormOpt`. Zgodnie z dokumentacją - odpowiedź to jedna z dwóch wartości: 1 - pole obowiązkowe, 8 - pole opcjonalne.

I teraz przykładowo dla kategorii "Odzież, Obuwie, Dodatki > Odzież damska > Sukienki" są parametry takie jak np. materiał dominujący. API zwraca 8 - nieobowiązkowe, podczas gdy w Państwa interfejsie to pole jest wymagane. Jak widać to pole jest wymagane bo nie przechodzi poprawnie walidacji produktu.

Bardzo proszę o sprawdzenie.

Pozdrawiam,
Jakub Marschall

**Comment by AniaMalinowska** [comment]
Jakubie, 
[tutaj](https://allegro.pl/dla-sprzedajacych/moda-i-uroda-harmonogram-zmian-obowiazkowosci-parametrow-LvKqGRZPXi0) znajdziesz wyjaśnienie:

m.in. dla parametru 'Materiał dominujący' obowiązkowość w ofertach dodawanych i edytowanych za pomocą formularza wystawiania wprowadziliśmy 8 lutego, a dla ofert wznawianych i ofert wystawianych przez API i Menedżera Sprzedaży - 9 kwietnia.

**Comment by hoobert89** [comment]
Aniu, dziękuję za odpowiedź.

W takim razie w jaki sposób możemy określić, które parametry są wymagane? API zwraca nam informacje, że te pola są nieobowiązkowe i zgodnie z tym tworzymy szablon aukcji, a w rezultacie otrzymujemy odpowiedź, że niewymagane pola są jednak wymagane :)

musimy w takim razie ręcznie ustawiać te warunki czy jest szansa, że API zacznie zwracać prawidłowe wartości dotyczące obligatoryjności tych pól?

Pozdrawiam,
Jakub Marschall

**Comment by AniaMalinowska** [comment]
Gdy zmieniamy obowiązkowość, parametrów, to najpierw zmiany wprowadzamy w formularzu wystawiania, a dopiero później dla ofert wznawianych i wystawianych przez API i Menedżera Sprzedaży. Wówczas metoda [doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782) będzie je zwracała jako obowiązkowe. Dlatego warto przed wystawieniem oferty przez API wywołać sobie tę metodę i sprawdzić aktualny stan -  w [danych zwracanych](https://allegro.pl/webapi/documentation.php/show/id,782) jest to sellFormOpt: informacja na temat obligatoryjności pola (1 - pole obowiązkowe, 8 - pole opcjonalne).
Oczywiście może się zdarzyć, że po tym, jak wystawisz ofertę przez API, i będziesz ją edytował z poziomu Mojego Allegro, zostaniesz poproszony o uzupełnienie parametrów które są już obowiązkowe w formularzu wystawiania.

Pozdrawiam :)

**Comment by dfranczuk** [comment]
Ponawiam temat. Nadal metoda doGetSellFormFieldsForCategory nie zwraca poprawnych wartości. W zacytowanym [artykule](https://allegro.pl/dla-sprzedajacych/moda-i-uroda-harmonogram-zmian-obowiazkowosci-parametrow-LvKqGRZPXi0) jest informacja, że metoda zacznie działać od 9 kwietnia. Jest już 10. Kiedy można spodziewać się, że metoda doGetSellFormFieldsForCategory zacznie zwracać poprawne wartości odnośnie obligatoryjności pól??

**Comment by mirkosmuz** [comment]
Ponawiam również temat. Nasi klienci mają codziennie po kilka tysięcy aukcji do zmiany przez moduł na stronie Allegro dodający parametry obowiązkowe. Aktualnie jest to jeden etat robiący tylko to.... Zatem generuje to olbrzymie koszty. Termin miał być do 9 kwietnia a tymczasem mamy już 10 i nic się nie zmieniło. Proszę się ustosunkować. Przedstawiona odpowiedź będzie przekazana do naszych klientów.

**Comment by TimothyKoval** [comment]
Mi w kategorii `Odzież, Obuwie, Dodatki > Odzież damska > Sukienki` udało się bez problemu wystawić, nie podając atrybutu `materiał dominujący`

**Comment by mirkosmuz** [comment]
Ok. Teraz musisz wejść na stronę allegro do "menadżera uzupełniania parametrów obowiązkowych" i uzupełnić w tej sukience parametry brakujące. My też bez problemu wystawiamy, jednak pracownik jak nie widzi obowiązkowego parametru to go omija a to trafia do wyżej wspomnianego menadżera.... I tak codziennie po kilkaset pozycji.

**Comment by dfranczuk** [comment]
> Mi w kategorii Odzież, Obuwie, Dodatki > Odzież damska > Sukienki udało się bez problemu wystawić, nie podając atrybutu materiał dominujący

Owszem, oferta się wystawi, ale sęk w tym, że wystawiając bezpośrednio przez allegro - atrybut ten jest wymagany. W związku z tym po stronie allegro trzeba korzystać z opcji "uzupełnij parametry"

**Comment by kamilimak** [comment]
@AniaMalinowska, prosimy o informacje, dlaczego nowe wymagane parametry nie zostały jeszcze zaktualizowane w API i kiedy będą?

**Comment by PawelTaberski** [comment]
Parametry najpierw stają się obowiązkowe w formularzu wystawiania, dopiero później w API. Wszystkie terminy i informacje odnośnie nowych parametrów znajdziecie tutaj: https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach

**Comment by kamilimak** [comment]
Wierzę, że większość osób, które się tutaj wypowiedziała zapoznała się z terminami i dlatego postanowiła dodatkowo dopytać. Parametry obowiązkowe wprowadzone do formularza wystawiania w lutym miały być obowiązkowe w API od 9 kwietnia, a nie są.

**Comment by AniaMalinowska** [comment]
Przepraszamy za zamieszanie. Przekazaliśmy już tę kwestię do odpowiedniego działu.

**Comment by AniaMalinowska** [comment]
Wyjaśniam, że w tym przypadku obowiązkowość dla ofert wznawianych i ofert wystawianych przez API i MS wprowadzamy sukcesywnie od 9 kwietnia - ten proces jeszcze trwa, stąd taka sytuacja. Informację o tym uaktualnimy na naszej stronie.  Przepraszamy za zamieszanie.
