### ISSUE TITLE
Problem z checkout-forms?lineItems.boughtAt.lte

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#1900]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym

Wywołuję:
https://api.allegro.pl/order/checkout-forms?lineItems.boughtAt.lte=2018-07-31T08%3A48%3A14.889Z&lineItems.boughtAt.gte=2018-07-31T08%3A48%3A14.888Z

Zwraca mi 100 ostatnich zamówień, a powinno tylko te wg daty czyli z 2018-07-31

**Comment by dominikworkroom** [comment]
Mam dokładnie ten sam problem API ignoruje filtry które dodaję 
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?lineItems.boughtAt.gte=2019-07-01T11%3A03%3A12.967Z

Posiadam dwa zamówienia na koncie jedno z dnia 27.06.2019 i 2.07.2019
ja chce zwrócić wszystkie od daty 01.07 i dostaję w response dwa ordery a powinnienem jeden

**Comment by sipath** [comment]
Mamy dokładnie do samo. Spowodowało to u nas spory problem z duplikatami zamówień (ze starego i nowego API). Wydaje się, że filtr boughtAt jest zupełnie ignorowany.

**Comment by AdrianEltes** [comment]
Dokładnie, mam błędy z pobraniem zamówień. Pobierane są wszystkie zamówienia

**Comment by PawelTaberski** [comment]
Dziękuję za zgłoszenie, pracujemy już nad rozwiązaniem tego problemu.

**Comment by keczerad** [comment]
Fajnie że pracujecie, bo ja włąśnie się dowiedziałem że jeden klient pobrał 1200 zamówień do Subiekta, ciekawe czy ktoś od Was połączy się z kleintem i zacznie to usuwać manulanie ?! Naprawdę cały dział programistów zakrawa na jakieś jaja do kwadratu, jak można wdrożyć zmianę wcześniej nie testując tego produktu, przecież nie korzysta z tego 3 klientów ?!

**Comment by TimothyKoval** [comment]
@keczerad 

> Podane metody, mimo że są w becie, są stabilne i można z nich korzystać.

[https://github.com/allegro/allegro-api/issues/1837#issuecomment-504348285](https://github.com/allegro/allegro-api/issues/1837#issuecomment-504348285)

**Comment by KJtTGHAK** [comment]
zaczęło działać....

**Comment by keczerad** [comment]
Ciekawe czy zrobili rollbacka czy poprawili ?

**Comment by PawelTaberski** [comment]
Potwierdzam, problem nie powinien już występować.
