### ISSUE TITLE
CheckoutForms.Payment.finishedAt zmiana typu danych !

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#1902]
Dlaczego nagle zmieniacie typ danych z "DataTime" na "DateTime?" Możecie to poprawić ?

**Comment by PrzemyslawLukanowski** [comment]
@keczerad  Czy możesz doprecyzować zgłoszenie - podać przykład rozbieżności, dane przed i po zmianie typu danych?

**Comment by keczerad** [comment]
Jeżeli podajecie przykład danych zwracanych przez API w dokumenacji jak tutaj;

https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET

To proszę w przykładzie zwracanych danych podać dwa przykłady jeden rekord z datą a drugi  rekord z nullem i wtedy każdy programista będzie wiedział że dana może być nullem uwzględni to, a serializacja danych się uda. 

--- przyklad z datą finishedAt
"payment": {
"id": "0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6",
"type": "CASH_ON_DELIVERY",
"provider": "P24",
"finishedAt": "2018-10-12T10:12:32.321",
"paidAmount": {
"amount": "123.45",
"currency": "PLN"
}
},

--- przklad z nullem w finishedAt

"payment": {
"id": "0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6",
"type": "CASH_ON_DELIVERY",
"provider": "P24",
"finishedAt": null,
"paidAmount": {
"amount": "123.45",
"currency": "PLN"
}
},

**Comment by Bober95** [comment]
Ogólnie dzisiaj około godziny 11-12 odpowiedzi z RestAPI zawierały wartości null zamiast jak do tej pory ich brak.
Przykład:
`  "payment": {
    "id": "c983adf3-xxx-xxx-xxxx-a18ec24a9ab0",
    "type": "CASH_ON_DELIVERY",
    "provider": null,
    "finishedAt": null,
    "paidAmount": null
  },`
Dane które były zwracane wcześniej i są zwracane obecnie:
`"payment":{"id":"c983adf3-xxx-xxx-xxxx-a18ec24a9ab0","type":"CASH_ON_DELIVERY"},`

Oczywiście jest to to samo zamówienie. Wartości null były zwracane każdym miejscu (personalIdentity,pickupPoint itp) w którym dane nie występowały

**Comment by manoos** [comment]
Potwierdzam wczoraj przy pobieraniu zamówień zaczęliście w pola rzucać NULL'ami, a wcześniej ich nie przekazywaliście. I to tak bez uprzedzenia...

**Comment by PrzemyslawLukanowski** [comment]
Docelowo będziemy zwracać wartość null, dokumentacja w najbliższym czasie zostanie zaktualizowana.

**Comment by manoos** [comment]
fajnie że najpierw wspominacie o zmianach, a dopiero później je wdrażacie...
