### ISSUE TITLE
Zmiana publication.status na ENDED

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1904]
Taka kwestia:
Za pomocą PUT /sale/offer-publication-commands próbuję zmienić publication.status z "ACTIVE" na "ENDED" 
Odpytując następnie za pomocą GET /sale/offer-publication-commands, otrzymuję SUCCESS nawet jeśli tak naprawdę komenda wcale nie zadziałała bo oferta miała już wcześniej status "ENDED", a została zamknięta lub sprzedana dajmy na to tydzień wcześniej.

To celowe założenie czy wypadek przy pracy?

**Comment by PawelTaberski** [comment]
Tak, w przypadku zlecenia zakończenia już zakończonej oferty powinieneś otrzymać w statusie SUCCESS. Bo oferta jest już zakończona.
