### ISSUE TITLE
Błąd autoryzacji urzadzenia

### ISSUE THREAD

**Issue by kamelTrop** [allegro/allegro-api#1905]
Mam problem z autoryzacja i uzyskaniem tokena. Dostaje StatusCode: "Unauthorized"
Co jest nie tak? Albo może jest gdzies przykładowy kod w c# działający?
A to mój kod:

   private void Form1_Load(object sender, EventArgs e)
        {
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

            string url = "https://allegro.pl/auth/oauth/device";
            string client_id = "....";
            string client_secret = "....";
            
            var restclient = new RestClient(url);
            RestRequest request = new RestRequest("request/oauth") { Method = Method.POST };
            request.AddHeader("Accept", "application/json");
            request.AddHeader("Authorization", pobierzParametryAutoryzacji("cf5faa5c2fbc47ae8b8a5099a", "CnXFnyzRV3CCxrni4n4DvwTv66Uphtqzg9ei5C4OS3zPLLwK4p9zHsPzOpubMYso"));
            request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request.AddParameter("client_id", client_id);
            var tResponse = restclient.Execute(request);
            var responseJson = tResponse.Content;
        }

      
        private string pobierzParametryAutoryzacji(string idKlienta, string sekretneIdKlienta)
        {
            string idks = idKlienta + ":" + sekretneIdKlienta;
            byte[] bajty = Encoding.UTF8.GetBytes(idks);
            return "Basic " + Convert.ToBase64String(bajty);
        }

**Comment by PrzemyslawLukanowski** [comment]
@kamelTrop Nie prowadzimy wsparcia w zakresie kodowania, ale w przeszłości pojawił się [wątek](https://github.com/allegro/allegro-api/issues/935), gdzie możesz znaleźć wskazówki, które być może okażą się pomocne.

**Comment by kamelTrop** [comment]
No ale to słabo, bo generalnie tworzycie api, które dla wygenerowanych kluczy i id nie działa a teraz niech ktoś sie domyśla jak poprawnie to miało by być. Bardzo słabe to ze strony allegro.

**Comment by PrzemyslawLukanowski** [comment]
@kamelTrop źle się wyraziłem, prześlij prosze pełnego curla z requestem i responsem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1905.

**Comment by PrzemyslawLukanowski** [comment]
@kamelTrop Prześlij proszę raz jeszcze przykładowy curl (jest to oczekiwany format danych) z requestem, jaki ostatecznie trafia do naszych serwerów, zgodnie z [naszym poradnikiem](https://developer.allegro.pl/auth/#DeviceFlow). Informacje, które otrzymaliśmy zawierają zbyt dużo dodatkowych danych,.

**Comment by kamelTrop** [comment]
wysyłając curl działa ale w zaden sposób nie moge zautoryzowac sie używająć c# i
WebClient
HttpClient
WebRequest
RestClient

Ciągle dostaje brak autoryzacji

**Comment by PrzemyslawLukanowski** [comment]
Czy kod, z którym masz problem, różni się od tego z pierwszego postu? Jeśli tak, wrzuć go tutaj. Być może znajdą się użytkownicy, którzy mieli podobny problem i będą w stanie Ci pomóc.

**Comment by kamelTrop** [comment]
tutaj sa przykladowe implementacje, u góry zmienne a pozniej wywołania - zadne nie przechodzi i dostaje UnAutorization, nie wiem co jest zle - podaje takie parametry jak sa w dokumentacji wymagane 



            string url = "https://allegro.pl/auth/oauth/device";
            string client_id = "moj id klienta";
            string client_secret = "moj klucz";
            string idks = client_id + ":" + client_secret;
            byte[] bajty = Encoding.UTF8.GetBytes(idks);
            string authString = "Basic " + Convert.ToBase64String(bajty);



            //1.
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://allegro.pl");
            var request = new HttpRequestMessage(HttpMethod.Post, "/auth/oauth/device");
            var keyValues = new List<KeyValuePair<string, string>>();
            keyValues.Add(new KeyValuePair<string, string>("client_id", client_id));
            keyValues.Add(new KeyValuePair<string, string>("Content-Type", "application/x-www-form-urlencoded"));
            keyValues.Add(new KeyValuePair<string, string>("Authorization", authString));
            request.Content = new FormUrlEncodedContent(keyValues);
            var response = await client.SendAsync(request);



            //2.
            var restclient = new RestClient(url);
            RestRequest request2 = new RestRequest("request/oauth") { Method = Method.POST };
            request2.AddHeader("Authorization", authString);
            request2.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request2.AddParameter("client_id", client_id);
            var tResponse = restclient.Execute(request2);


            //3.
            WebRequest myReq = WebRequest.Create(url);
            CredentialCache mycache = new CredentialCache();
            myReq.Headers["Authorization"] = authString;
            myReq.Headers["client_id"] = client_id;
            myReq.ContentType = "application/x-www-form-urlencoded";
            myReq.Method = "POST";
            WebResponse wr = myReq.GetResponse();


            //4.
            var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://allegro.pl/auth/oauth/device");
            httpWebRequest.ContentType = "application/x-www-form-urlencoded";
            httpWebRequest.Method = "POST";
            httpWebRequest.Headers.Add("Authorization", authString);
            httpWebRequest.Headers.Add("client_id", client_id);
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
