### ISSUE TITLE
 get /order/checkout-forms

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1906]
:bulb: **Sugestia**

Wydaje mi się, że w "checkout-forms" przydało by się pole z datą kiedy formularz został skierowany do realizacj, to znaczy zmienił status na "READY_FOR_PROCESSING". (rozumiem, że w przypadku przedpłat jest to payment.finishedAt, a jak w przypadku przesyłek pobraniowych, moment gdy formularz zmienia status na "FILLED_IN"?)
Gdyby ponadto w metodzie  get /order/checkout-forms zrobić to pole query parametrem, ogromnie ułatwiłoby to zaciąganie nowych zamówień, które muszą być zrealizowane.
Istniejący obecnie query parametr z datami lineItems.boughtAt.lte i lineItems.boughtAt.gte nie jest, przynajmniej dla mnie, ani praktyczny ani szczególnie potrzebny.
Teraz sprawdzenie rano, jakie zamówienia muszę danego dnia zrealizować jest raczej problematyczne, bo muszę albo ponownie zaciągać wszystkie zamówienia i sprawdzać które są nowe, a które zmieniły status, albo tworzyć mechanizm łączący get/order/checkout-forms z get order/events. Rozwiązanie o którym piszę pozwoliłoby załatwić to jedną komendą.
No chyba, że istnieje jakieś lepsze rozwiązanie którego nie dostrzegłem - dopiero zabieram się za Order Management.

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100 Przyjęliśmy sugestię, poinformujemy o zmianie w dedykowanym komunikacie.

**Comment by lukada4100** [comment]
Przyjęliśmy w sensie "zaakceptowaliśmy" czy "przyjeliśmy do rozpatrzenia"?

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100  Przyjęliśmy do rozpatrzenia.

**Comment by lukada4100** [comment]
:D

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100 

> Wydaje mi się, że w "checkout-forms" przydało by się pole z datą kiedy formularz został skierowany do realizacj, to znaczy zmienił status na "READY_FOR_PROCESSING". (rozumiem, że w przypadku przedpłat jest to payment.finishedAt, a jak w przypadku przesyłek pobraniowych, moment gdy formularz zmienia status na "FILLED_IN"?)

W najbliższym czasie wprowadzimy funkcjonalność, dzięki której pole payment.finishedAt będzie zwracane dla każdego zamówienia "READY_FOR_PROCESSING", także dla ofert pobraniowych.

> Gdyby ponadto w metodzie get /order/checkout-forms zrobić to pole query parametrem, ogromnie ułatwiłoby to zaciąganie nowych zamówień, które muszą być zrealizowane.

Aktualnie nie planujemy wdrożenia takiej zmiany. Sugerujemy korzystanie z dziennika zdarzeń, za pomocą którego sprawdzisz informacje na temat nowych zamówień.
