### ISSUE TITLE
Nie działa sale/shipping-rates 

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1908]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam
{"errors":[{"code":"ConstraintViolationException","message":"An error has occurred","details":null,"path":"PublicShippingRatesResource$$EnhancerBySpringCGLIB$$215a7663.getList.arg0","userMessage":"Transferred data is incorrect"}]}

To samo przy metodzie sale/shipping-rates na produkcji co na testowym

**Comment by LukaszCierocki** [comment]
@qshop123 u mnie w aplikacji wszystko działa dla metod które podałeś.

**Comment by qshop123** [comment]
"U mnie działa" - a u mnie niestety nie. 
Sprawdziłem token przy karawaniarzu i url endpointa ale jest wszystko prawidłowo na produkcję. Dalej lipa.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Wyślij proszę pełen request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1908.

**Comment by szokart** [comment]
Także mam mam błąd 403
"errors":[{"code":"ERROR","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Please retry, or restart application."}]}

a inne normalnie działają

**Comment by qshop123** [comment]
Wysłano dane przez formularz, proszę o szybkie sprawdzenie bo za chwile klienci zrobią ze mnie szaszłyk na zimno :(

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Otrzymaliśmy Twój request, pracujemy nad rozwiązaniem problemu.
@szokart Rozkoduj swój token i zweryfikuj czy należy do prawidłowego usera. Prześlij także przykładowy request + response przez  nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt) z dopiskiem gitHub #1908.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Powtórzyłem wywołanie i API zwraca prawidłowe dane. Czy na pewno dodajesz parametr seller.id w zapytaniu GET?

**Comment by qshop123** [comment]
Ok, sprawdziłem wszystko raz jeszcze i nie wierzę w to co widzę.

Mój błąd, po prostu założyłem sobie że macie spójne nazwy dotyczące parametrów i tak
1) after-sales-service-conditions/implied-warranties?sellerId= 
2) after-sales-service-conditions/return-policies?sellerId=
3) after-sales-service-conditions/warranties?sellerId=

W tych trzech metodach podajemy sellerId według schematu że drugi człon nazwy jest wielką literą "Id"
To samo przyjąłem przy komunikacji z metodą sale/shipping-rates

4) sale/shipping-rates?sellerId=

Jak się okazuje powinien się odwoływać do niej tak

4) sale/shipping-rates?seller.id=

Gdzie sens i gdzie logika w ogóle stosowania różnych rodzai nazewnictwa do metod w jednym API!!!
Albo stosujcie wszędzie "seller.id" albo wszędzie "sellerId" - bo teraz to się po prostu nie trzyma kupy.
Gdyby w mojej firmie programista zrobił takie coś, to bym go wywalił na zbity ryj.

jprd.....

Inna sprawa to taka, że to wasze API jest podatne na nieprawidłowe dane wejściowe i nie ma kompletnie żadnej walidacji. Powinno wywalić przy podaniu nieprawidłowego parametru do metody coś w stylu "Wrong parameter in GET message, check your documentation, seller.id expected"

A wy podajecie stacka bezpośrednio z kodu aplikacji 

"{"errors":[{"code":"ConstraintViolationException","message":"An error has occurred","details":null,"path":"PublicShippingRatesResource$$EnhancerBySpringCGLIB$$eee7689b.getList.arg0","userMessage":"Transferred data is incorrect"}]}"

CO to komu mówi? Nic....MA SA KRA.

**Comment by qshop123** [comment]
Wstawcie to gdzieś wielkimi czerwonymi literami że funkcjonują w systemie dwa różne rodzaje nazewnictwa dla parametrów wejściowych 
1) sellerId
2) seller.id

Bo ktoś pewnie znowu się wyłoży niedługo i będzie znowu taka sytuacja jak teraz, że ani on nie będzie wiedział co jest i ani wy - bo wy też myliliście że wam się wyłożyła metoda w aplikacji....

**Comment by qshop123** [comment]
Wstawcie to gdzieś wielkimi czerwonymi literami że funkcjonują w systemie dwa różne rodzaje nazewnictwa dla parametrów wejściowych
1) sellerId
2) seller.id

Bo ktoś pewnie znowu się wyłoży niedługo i będzie znowu taka sytuacja jak teraz, że ani on nie będzie wiedział co jest i ani wy - bo wy też myliliście że wam się wyłożyła metoda w aplikacji....

A może jest gdzieś to jeszcze napisane inaczej?
- seller-id ?
- seller/id ?

Nie ma?

**Comment by PrzemyslawLukanowski** [comment]
W momencie wdrażania REST API nie mieliśmy ujednoliconego nazewnictwa parametrów wejściowych dla trzech zasobów, o których wspominasz. Aktualnie przyjęta konwencja to seller.id, jednak aby nie łamać kompatybilności wstecznej,  do zasobów after-sales-service-conditions/... wciąż można odwołać się poprzez użycie parametru sellerId.
