### ISSUE TITLE
Ponawianie aukcji

### ISSUE THREAD

**Issue by MagdalenaNieckula** [allegro/allegro-api#1909]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
Dzien dobry,
Od dwoch dni mamy problem z ponawianiem aukcji, nie mozemy wystawiac przedmiotow, ktore sie zakonczyly. Jak mozemy sobie z tym poradzic?
:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
@MagdalenaNieckula Sprawdź [status publikacji oferty](https://developer.allegro.pl/sale/#step-10-tasks) za pomocą zasobu GET /sale/offer-publication-commands/{commandId}/tasks. Zwróć uwagę czy podczas walidacji są zwracane jakieś błędy. Jeśli takich nie ma, prześlij tutaj przykładowy request i response.
