### ISSUE TITLE
Limity api - sesje

### ISSUE THREAD

**Issue by kaminiak23** [allegro/allegro-api#191]
Z tego co czytałem, mogę mieć 10 sesji na raz i kolejne beda zamykały najstarsza.
Nie wiem jak robić to poprawnie, podpowiecie? Tzn. nie wiem czy na testowym mi to nie zadziałało czy inaczej robić. Jak dostaję kluc sesji to mogę go zapisać do SESSION i używać przez godzinę? (sprawdzam czy klucz jest ok jak nie to pobieram nowy a jak tak to używam) tylko, że mi taki klucz wygasa "od razu" kolejne zapytanie na nim juz jest błędne więc cały czas pobieram nowy. Czy mogę tak robić? 

Jak jest prawidłowo?

**Comment by MaciejPotepa** [comment]
Jak sam napisałeś:
- na raz możesz mieć aktywne 10 kluczy sesji, każdy kolejny spowoduje dezaktywowanie najstarszego z nich,
- każdy z kluczy jest aktywny przez 1 godzinę

Na upartego możesz do każdego nowego zapytania generować nowy klucz sesji, ale takie rozwiązanie jest nie efektywne dla Ciebie i dla nas. Musisz opracować mechanizm, który Ci pozwoli na kontrolowanie ważności kluczy sesji i wykorzystywanie tych aktywnych zamiast generowania ciągle nowych. 

Oczywiście, takie rozwiązanie gdzie do każdego zapytania będziesz generował nowy klucz będzie działać, ale będzie zbyt niewydajne. 

Jak napisałem wcześniej musisz wypracować swój mechanizm zarządzania kluczami sesji, tu nie ma jednej gotowej metody i sposobu organizacji tego aspektu integracji. 

Dajemy możliwość posiadania 10 kluczy, gdzie każdy z nich jest ważny przez 1 godzinę od wygenerowania. Co z tym zrobisz, zależy tak naprawdę od Ciebie.
