### ISSUE TITLE
InPost - wybór paczkomatu

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#1910]
Dzień dobry,
Tworzę cennik dostaw, z metodą wykorzystującą paczkomaty i wystawiam ofertę, go wykorzystującą. 
Kiedy kupuję przedmiot z tej oferty, i chcę wybrać sposób dostawy (paczkomat) ładuje mi się okno wyboru - ale nie mam, żadnego paczkomatu do wyboru - przez co nie mogę testować funkcji związanych z obsługą zamówień z paczkomatami.

Czy w przyszłości będą udostępnione chociaż jakieś testowe wartości w oknie wyboru paczkomatu? Jeśli tak, to mniej więcej kiedy?

**Comment by PrzemyslawLukanowski** [comment]
@LukaszCierocki W środowisku testowym również masz możliwość wyboru dowolnego paczkomatu. Zweryfikowaliśmy to i nie spotkaliśmy się z opisanym problemem. Spróbuj odświeżyć ofertę.

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski ofertę odświeżyłem. Niestety dalej jak próbuję kupić przedmiot i wybrać w ofercie sposób dostawy "Paczkomaty 24/7" to otwiera się okno wyboru paczkomatu bez żadnego paczkomatu do wybrania. Poniżej screenshot. 

![image](https://user-images.githubusercontent.com/45286112/60660316-c969ac80-9e57-11e9-842b-10266c9662d8.png)

**Comment by PrzemyslawLukanowski** [comment]
@LukaszCierocki Czy na innej przeglądarce również nie ma możliwości wyboru paczkomatu?

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski Zarówno na Chrome jak i FF. Z włączonym AdBlockiem i z wyłączonym. Dalej nie ma możliwości wyboru.

**Comment by PrzemyslawLukanowski** [comment]
@LukaszCierocki Zgłosiłem problem do odpowiedniego zespołu.
