### ISSUE TITLE
[RestAPI][Draft] Tylko "name"

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1911]
Zgłaszam sugestię by "draft" miał wymóg podania tylko nazwy oferty + kategorii w której bedzie wystawiany. Jeśli jest to "oferta w buforze" to powinniśmy móc ją założyć niewielkim nakładem

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba aby wystawić draft oferty wystarczy podać:

```
{
	"name": "Nazwa oferty"
}
```

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski  sprawdzałeś tak naprawdę :) na produkcyjnym serwerze?
Zgodnie z dokumentacją (swagger.yaml) metoda przyjmuje cały pusty obiekt Offer, jeśli wysyłam tylko name dostaję błędy 

Metodą prób i błędów wyszło na to że  taki request przechodzi dopiero bezbłędnie, stąd sugestia by to usprawnić

REQUEST 2019-07-03 15:42:10.2445771 
curl -X POST \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \
  -d '{"additionalServices":null,"afterSalesServices":null,"category":{"id":"258215"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":null,"description":null,"ean":"2010000000038","external":{"id":"ANANAS"},"id":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1142a1/fe57303b4d6788bdb791ac03c43f"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/112b48/fb4d8b6343cc896cdf98647ec172"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/1144cc/0aa0fb1640e1aa92f3808fa24084"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11dbd5/97842431417aab8c4836404d0c59"}],"location":null,"name":"Ananas: słodki i wyjątkowy","parameters":null,"payments":null,"product":null,"promotion":null,"publication":null,"sellingMode":{"format":"BUY_NOW","price":{"amount":"8.99","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":1,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

**Comment by PrzemyslawLukanowski** [comment]
Sprawdzałem zarówno na produkcji, jak i na środowisku testowym. [Zgodnie z dokumentacją](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) wystarczy przekazać w strukturze tylko “name”, aby utworzyć draft oferty. Możesz nam przesłać tutaj response z błędami, jakie otrzymujesz?

**Comment by SebastianOzdoba** [comment]
W sumie masz rację :), zadziałą samo name, ja chciałem mieć name + kategoria, a to już nie zadziała
Zamykam

**Comment by alekskuc** [comment]
> Sprawdzałem zarówno na produkcji, jak i na środowisku testowym. [Zgodnie z dokumentacją](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) wystarczy przekazać w strukturze tylko “name”, aby utworzyć draft oferty. Możesz nam przesłać tutaj response z błędami, jakie otrzymujesz?

Dzień dobry przesyłam request i response z błędami walidacji pól które zgodnie z dokumentacja nie powinny być wymagane w przypadku requesta z samą nazwą (serwer produkcyjny):

Request:
```
curl -X POST \
  https://api.allegro.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: PL' \
  -H 'Authorization: Bearer ' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{"name": "Nazwa oferty"}'
```

Response:
```
{
    "id": "8334132044",
    "name": "Nazwa oferty",
    "category": null,
    "product": null,
    "parameters": [],
    "ean": null,
    "description": null,
    "compatibilityList": {
        "items": null
    },
    "images": [],
    "sellingMode": null,
    "stock": null,
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": false
    },
    "delivery": null,
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "promotion": null,
    "location": null,
    "external": null,
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Payments may not be empty.",
                "details": "",
                "path": "",
                "userMessage": "Dane dotyczące płatności nie mogą być puste."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Location may not be empty.",
                "details": "",
                "path": "",
                "userMessage": "Lokalizacja nie może być pusta."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Warunki oferty (zwroty, reklamacje) są wymagane dla kont firma.",
                "details": "",
                "path": "",
                "userMessage": "Warunki oferty (zwroty, reklamacje) są wymagane dla kont firma."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Oferta musi zawierać nowy opis.",
                "details": "",
                "path": "",
                "userMessage": "Oferta musi zawierać nowy opis."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Dodaj opis oferty.",
                "details": "",
                "path": "",
                "userMessage": "Dodaj opis oferty."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny.",
                "details": "",
                "path": "",
                "userMessage": "Musisz wybrać przynajmniej jeden sposób sprzedaży oraz podać wymagane ceny."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Identyfikator kategorii nie może być pusty.",
                "details": "",
                "path": "",
                "userMessage": "Identyfikator kategorii nie może być pusty."
            }
        ],
        "validatedAt": "2019-07-24T10:19:54.4Z"
    },
    "createdAt": "2019-07-24T10:19:54Z",
    "updatedAt": "2019-07-24T10:19:54.4Z"
}
```
Trace-Id 4c0abb42841f52e5

Skoro jest wymagane tylko name, dlaczego respons zwraca szereg błędów z walidacją pól z edycji?

Proszę o weryfikacje i poprawę działania rest api i treści dokumentacji wprowadzającej w błąd.

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Za pomocą metody POST sale/offers utworzyłeś draft oferty, możesz go teraz pobrać za pomocą GET sale/offers/{offerId}. Błędy przy walidacji informują, jakie pola musisz jeszcze uzupełnić za pomocą PUT sale/offers/{offerId} przed aktywowaniem oferty.

**Comment by alekskuc** [comment]
> @alekskuc Za pomocą metody POST sale/offers utworzyłeś draft oferty, możesz go teraz pobrać za pomocą GET sale/offers/{offerId}. Błędy przy walidacji informują, jakie pola musisz jeszcze uzupełnić za pomocą PUT sale/offers/{offerId} przed aktywowaniem oferty.

Zgłaszam zatem sugestię, żeby w takim poniższym requeście nie były walidowane żadne inne pola poza name, których Klient na tym etapie nie wypełnia i nie wysyła do rest api.

```
curl -X POST \
  https://api.allegro.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: PL' \
  -H 'Authorization: Bearer ' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -d '{"name": "Nazwa oferty"}'
```

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc W POST sale/offers możesz już na początku przesłać pełne dane, bez potrzeby ich późniejszego uzupełniania za pomocą PUT. Dlatego już w tym zasobie niezbędna jest walidacja, czy dana oferta jest kompletna.

**Comment by SebastianOzdoba** [comment]
Jeśli można wysłać sam name w drafcie to weryfikacja powinna być tylko na name.
Jasno w dokumentacji jest napisane: aby założyć draft wystarczy wysłać "name", więc w response nie powinno być żadnych błędów dotyczących innych pól, bo ich nie wysyłam.
Moim zdaniem jest to źle zrobione

**Comment by PrzemyslawLukanowski** [comment]
Aby utworzyć draft oferty wystarczyć przesłać tylko name, jednak w odpowiedzi przesyłana jest cała oferta. Jeżeli wymagane pola nie są uzupełnione, taka informacja trafia do tablicy errors w walidacji, mimo że sam request w odpowiedzi otrzymuje status 200 i draft zostaje utworzony. Tak jak wspomniałem, przy wywołaniu POST sale/offers można już przesłać całą ofertę - walidacja jest zatem konieczna już na tym etapie.
