### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#1913]
Uszanowanie!
Proszę o aktywację sprzedaży na koncie sandbox:
magik0092

**Comment by PrzemyslawLukanowski** [comment]
@magik092 Nie widzę takiego użytkownika. Czy potwierdziłeś rejestrację w otrzymanym od nas mailu?

**Comment by magik092** [comment]
Kurcze, od tego konta mail nie dotarł (nawet w spamie go nie ma) ale prewencyjnie utworzyliśmy inne konto, tutaj na inną skrzynkę dotarł mail. Konto do aktywacji:
radoslawb

**Comment by PrzemyslawLukanowski** [comment]
@magik092 Wstępnie aktywowałem konto. Aby dokończyć aktywację prześlij dwa dowolne pliki przez zakładkę Moje konto.

**Comment by magik092** [comment]
Gotowe :)
