### ISSUE TITLE
Data wznowienia

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1914]
:bulb: **Sugestia**

Prosiłbym o dodanie w `sale/offers/` daty wznowienia oferty do wyczerpania. Dla takich ofert nie jest zwracana data zakończenia a sprzedawcy potrzebują informacji, kiedy oferta się kończy lub wznawia.

**Comment by pkrzemo** [comment]
A ja poprosiłbym o shippingRatesId ...

**Comment by PrzemyslawLukanowski** [comment]
Dziękujemy za sugestię, przekazałem ją do odpowiedniego zespołu.

**Comment by Onixarts** [comment]
Można się dowiedzieć czy taka informacja będzie dostępna, bo klienci suszą nam głowę codziennie, że nie ma w programie daty wznowienia oferty. I nie wiem czy mamy czekać aż coś dodacie, czy na własną rękę rozwiązać problem.

**Comment by PrzemyslawLukanowski** [comment]
@Onixarts  Aktualnie sugestia została przekazana do odpowiedniego zespołu. Jeśli zdecydujemy się ją wdrożyć, poinformujemy w odpowiednim komunikacie.
