### ISSUE TITLE
Faktura VAT

### ISSUE THREAD

**Issue by nifrez** [allegro/allegro-api#1915]
Na stronie https://developer.allegro.pl/my_offers/

Są podane wartości VAT, VAT_MARGIN, VAT_MARGIN, NO_INVOICE

1. W jaki sposób w REST API wyszukać tylko takie przedmioty które mają fakturę VAT-marża
2. Jeżeli to niemożliwe to czy z opcją "oferta ma FAKTURA VAT" jakoś w przedmiocie są zapisane informacje jaka to faktura vat?

**Comment by PrzemyslawLukanowski** [comment]
@nifrez Nie można, dziękujemy za sugestię, zgłoszę ją do odpowiedniego zespołu.
