### ISSUE TITLE
GET /sale/offers - zmiana struktury odpowiedzi?

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#1916]
1 lipca wykrzaczyło nam się parsowanie odpowiedzi z tytułowego zasobu. Wychodzi na to, że zmieniła się struktura danych zwracanych przez ten request. Nigdzie nie widzę jednak takiej informacji, czy coś mi umknęło?

**Comment by pkrzemo** [comment]
Bo to było dostępne tylko dla wtajemniczonych... Ja odkryłem ją przypadkiem. Reszta hołoty musiała używać okrojonej struktury (bo nie chodzi o to żeby użytkownik nie mógł, tylko żeby mógł ale w znoju) wysyłając -H 'Accept: application/vnd.allegro.public.v1+json' \.
 Ponieważ nieopatrznie zapytałem o znaczenie pewnych dat #1855 to niestety zapewne domyślnie wysyłają teraz okrojoną wersję, tą dla plebsu. Niestety to moja wina. Znajomi królika używają teraz zapewne czegoś w rodzaju  -H 'Accept: application/vnd.allegro.znajomi.królika.v1+json' \.
;-)
Zapewne to dlatego że serwery allegro są zbyt wydajne, i potrzebują je jakoś dławić. Dlatego plebs musi pobierać WSZYSTKIE POLA OFERTY, wysyłając tryliony zapytań, aby  sprawdzić np. jaki cennik dostawy jest przypisany. Dzięki temu serwer ma co robić i nie stoi godzinami bezużyteczny. Znajomi królika dostają to zapewne nadal w tej bardziej użytecznej strukturze odpytując jedynie /sale/offers ... no ale żeby mieć do tego dostęp to trzeba być najpierw znajomym królika... bo przecież plebs nie może dostać czegoś wydajnego i użytecznego zarazem.
LOL
Opis "prawidłowej", "wspieranej" struktury odpowiedzi  jest dostępny w dokumentacji tego systemu beta (a w rzeczywistości preview).
