### ISSUE TITLE
GET /sale/offers - publication.status = ACTIVE zwraca oferty nieaktywne

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#1917]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Klient zgłasza mi taki problem. Dotyczy tylko jednego konta. Przykładowe oferty:
8245208161
8245173686
8244816674
Pojawiają się w powyższym zasobie pomimo filtra  publication.status = ACTIVE

**Comment by PrzemyslawLukanowski** [comment]
@rtnet-pl Zweryfikowałem to, API zwraca oferty o których piszesz. Zgłosiłem błąd do odpowiedniego zespołu.

**Comment by rtnet-pl** [comment]
@PrzemyslawLukanowski Klient zgłasza mi, że problem nadal występuje.

**Comment by PrzemyslawLukanowski** [comment]
@rtnet-pl  Pracujemy nad tym, proszę o cierpliwość.

**Comment by PrzemyslawLukanowski** [comment]
@rtnet-pl Problem został usunięty, zasób zwraca prawidłowe dane.

**Comment by rtnet-pl** [comment]
Dziękuję, mam potwierdzenie że działa.

**Comment by rtnet-pl** [comment]
@PrzemyslawLukanowski Cześć, problem powrócił tym razem na innym koncie (globtruck_eu)
Czy mogę prosić o usunięcie usterki?

**Comment by PrzemyslawLukanowski** [comment]
@rtnet-pl Mogę prosić o przykładowe numery ofert?

**Comment by rtnet-pl** [comment]
@PrzemyslawLukanowski 7537525429
7535687550
7535496768
7534229465

**Comment by PrzemyslawLukanowski** [comment]
@rtnet-pl Dzięki, zweryfikowałem to - występuje rozbieżność, Zgłosiłem problem do odpowiedniego zespołu.
