### ISSUE TITLE
Problem z walidowaniem i publikacją ofert w wybranych kategoriach

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#1918]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry
Proszę o analize problemów z walidacją przykładowych ofert

Id oferty - 8271904079
Kategoria - 5547

sekcja validation

`"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Podana wartość nie jest liczbą: Długość wkładki(203093).",
                "details": "",
                "path": "",
                "userMessage": "Podana wartość nie jest liczbą: Długość wkładki(203093)."
            }
        ],
        "validatedAt": "2019-07-04T06:49:33.884Z"
    },`

sekcja parameters

`{
    "id": "203093",
    "valuesIds": [],
    "values": [
        "30"
    ],
    "rangeValue": null
},`

zasób /sale/categories/{categoryId}/parameters

`[id] => 203093
[name] => Długość wkładki
[type] => float
[required] => 1
[unit] => cm
[restrictions] => Array
    (
        [max] => 40
        [precision] => 2
    )`

![Screenshot at 2019-07-05 12-24-55](https://user-images.githubusercontent.com/4314822/60718027-deac0d00-9f23-11e9-8121-66bde0147ae0.png)

Id oferty - 8271681936
Kategoria - 5540

sekcja validation

`"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Podana wartość nie jest liczbą: Wysokość obcasa/platformy(68).",
                "details": "",
                "path": "",
                "userMessage": "Podana wartość nie jest liczbą: Wysokość obcasa/platformy(68)."
            }
        ],
        "validatedAt": "2019-07-04T05:24:14.683Z"
    },`

sekcja parameters

`{
            "id": "68",
            "valuesIds": [],
            "values": [
                "10"
            ],
            "rangeValue": null
        },`

zasób /sale/categories/{categoryId}/parameters

`[id] => 68
    [name] => Wysokość obcasa/platformy
    [type] => float
    [required] => 1
    [unit] => cm
    [restrictions] => Array
        (
            [max] => 20
            [precision] => 2
        )`
widok w formularzu
![Screenshot at 2019-07-05 12-28-31](https://user-images.githubusercontent.com/4314822/60718193-511ced00-9f24-11e9-895e-d91db904b812.png)

Id oferty - 8271848772
Kategoria - 5540
sekcja validation
`"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Podana wartość nie jest liczbą: Długość wkładki(203093).",
                "details": "",
                "path": "",
                "userMessage": "Podana wartość nie jest liczbą: Długość wkładki(203093)."
            }
        ],
        "validatedAt": "2019-07-04T06:27:53.623Z"
    },`
sekcja parameters
`{
            "id": "203093",
            "valuesIds": [],
            "values": [
                "25"
            ],
            "rangeValue": null
        }`

zasób /sale/categories/{categoryId}/parameters

`[id] => 203093
[name] => Długość wkładki
[type] => float
[required] => 1
[unit] => cm
[restrictions] => Array
    (
        [max] => 40
        [precision] => 2
    )`

Id oferty - 8227306749
Kategoria - 78720

sekcja validation

`"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Nieprawidłowy parametr dla wybranej kategorii (17148).",
                "details": "",
                "path": "",
                "userMessage": "Nieprawidłowy parametr dla wybranej kategorii (17148)."
            }
        ],
        "validatedAt": "2019-06-30T17:59:04.319Z"
    },`

W sekcji parameters nie jest przekazywany parametr 17148, ponieważ zasób /sale/categories/{categoryId}/parameters nie zwraca takiego pola, dodatkowo takie pole nie wyświetla się w formularzu wystawiania oferty w allegro.

**Comment by PrzemyslawLukanowski** [comment]
@pawelosajda - powtórzyłem w Postmanie Twoje wywołania odnośnie trzech pierwszych przykładów i API nie zwróciło mi podanych błędów. Otrzymuję je wtedy, gdy do wartości value dodam po przecinku dwie cyfry. Upewnij się, że oprogramowanie, z którego korzystasz, automatycznie ich nie dodaje do wartości (być może tak robi ze względu na informację "[precision] => 2 ").
Jeśli chodzi o ofertę 8227306749 - podaj proszę login, do którego jest przypisana oferta.
