### ISSUE TITLE
skąd pobrać TRACE-ID

### ISSUE THREAD

**Issue by autornet** [allegro/allegro-api#1919]

**Comment by autornet** [comment]
Łączę się za pomocą Indy i Delphi
Skąd mogę pobrać TRACE-ID - nigdzie żadnych informacji na ten temat nie znalazłem.

**Comment by PrzemyslawLukanowski** [comment]
Trace-ID otrzymujesz w nagłówku wywołanego wcześniej requesta.

**Comment by imper86** [comment]
chyba raczej w nagłówku odpowiedzi :)
