### ISSUE TITLE
Punkty odbioru Poczty Polskiej

### ISSUE THREAD

**Issue by BloodRiderPL** [allegro/allegro-api#192]
Witam, czy jest możliwość aby Allegro przekazywało w punktach odbioru numer punktu? Bardzo ułatwiłoby to weryfikację adresu punktu gdyby numery zwracane przez Pocztę Polską były identyczne po stronie Allegro oraz zwracane metodą doGetPostBuyFormsDataForSellers.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Pracujemy nad wprowadzeniem takiej możliwości. Powinna się pojawić w ciągu kilku najbliższych miesięcy. 

Jak będziemy to udostępniać, poinformujemy.
