### ISSUE TITLE
Braki możliwości zmiany ilości towaru na aukcji poprzez rest api

### ISSUE THREAD

**Issue by astroskrypt** [allegro/allegro-api#1920]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
@astroskrypt Zweryfikowałem to i udało mi się zmienić ilość zarówno przez zasób PUT sale/offers/{offerId}, jak i PUT sale/offer-quantity-change-commands/{commandId}. Prześlij proszę numer oferty, z którą masz problem oraz przykładowy request, jaki wysyłasz.
