### ISSUE TITLE
Ograniczona ilość zezwolonych tagów HTML

### ISSUE THREAD

**Issue by grojanteam** [allegro/allegro-api#1921]
Pytanie mam dotyczące ofert
https://developer.allegro.pl/sale/#step-5-description

Dlaczego masę tagów HTML blokujecie? czemu nie można użyć np. `<br><h3><h4>`
Co jest powodem że jest na to blokada?

Resztę tagów rozumiem i w ogóle ale takiego `<br>` przeniesienie do nowej linii, to nie bardzo ogarniam. Zbyt często używany? SEO? Czy jak?

**Comment by PrzemyslawLukanowski** [comment]
[Ograniczyliśmy](https://allegro.pl/dla-sprzedajacych/kategoria/zasady-dla-ofert) ilość znaczników HTML po to, aby ustandaryzować wygląd oferty, tak aby była jak najbardziej przejrzysta dla kupującego. Wszystkie inne niezbędne dane dotyczące oferty, takie jak: parametry, dostawa, płatność, gwarancja, reklamacje, zwroty, znajdują się w specjalnie wyznaczonym miejscu. Sam opis powinien zawierać najważniejsze informacje o oferowanym produkcie.

**Comment by grojanteam** [comment]
Nie możecie zezwolić na <br> w środku akapitu na przykład? I jeszcze jedno pytanie mam rozumieć że <table> też będą blokowane?

**Comment by PawelTaberski** [comment]
@grojanteam Zezwalamy tylko na niektóre znaczniki html wszystkie dopuszczalne opisaliśmy w [naszym poradniku](https://developer.allegro.pl/sale/#step-5-description).
Nie zezwalamy na znacznik <table>.

**Comment by grojanteam** [comment]
Bieda że się tak wyrażę ;) kolorować też nie można... A jakieś zmiany w ogóle będą? W tym temacie?

**Comment by majdzik84** [comment]
+1 dla znacznika <br>

**Comment by grojanteam** [comment]
@PawelTaberski  swoją drogą piszesz mi o waszym poradniku mimo że w pierwszym poście dokładnie ten sam poradnik umieściłem... Mam czasem wrażenie że support nie czyta całego tematu... tylko czytacie ostatni i co rusz to ktoś inny odpisuje. Jak już ktoś zaczyna odpisywać na temat, to żądam, żeby do końca ten temat był prowadzony przez jedną osobę...

**Comment by PawelTaberski** [comment]
Nie planujemy rozbudowy ilości dostępnych znaczników.

**Comment by Onixarts** [comment]
Dasz ludziom BRy to zobaczysz co zaczną wyczyniać z opisami ;). Na początku też mi się to bardzo nie podobało, ale teraz przynajmniej opisy w Allegro są czytelne i w miarę jednakowe.
