### ISSUE TITLE
Czy token jest ważny?

### ISSUE THREAD

**Issue by autornet** [allegro/allegro-api#1922]
Czy istnieje metoda, która zwróci mi informację o ważności tokena?
Przed wywołaniem metody zmiany ilości na aukcji chciałbym mieć pewność, że token jest ważny i dopiero wtedy chcę wywołać metodę zmiany ilości.

**Comment by rtnet-pl** [comment]
Możesz rozkodować token i pobrać datę wygaśnięcia. https://jwt.io
Mimo to token może być unieważniony, wtedy najprościej odpytac np. GET /sale/offers i zobaczyć czy nie odpowie kodem 401

**Comment by autornet** [comment]
Proszę jeszcze o info.

 

Zmieniam ilość w aukcji i zwrotnie otrzymuję Kod: 201

 

expires: 0

cache-control: no-cache, no-store, max-age=0, must-revalidate

x-xss-protection: 1; mode=block

server: envoy

pragma: no-cache

x-frame-options: DENY

trace-id: 845cc877ae631f87

date: Mon, 08 Jul 2019 13:37:44 GMT

x-ratelimit-remaining: 9000

x-content-type-options: nosniff

content-type: application/vnd.allegro.public.v1+json;charset=UTF-8

x-ratelimit-limit: 9000

x-envoy-upstream-service-time: 33

transfer-encoding: chunked

 

Na aukcji fizycznie ilość się nie zmieniła – czy kod 201 oznacza, że jest ok? Czy powinien być kod 200 ?

**Comment by PawelTaberski** [comment]
Jeśli pytasz o zasób /sale/offer-quantity-change-commands/{commandId} to taki status odpowiedzi jest poprawny, aby sprawdzić status zadania skorzystaj z zasobu GET /sale/offer-quantity-change-commands/{commandId}/tasks
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#3g).

**Comment by autornet** [comment]
W odpowiedzi dostaję:

HTTP/1.1 200 OK i nic poza tym w responsie – żadnego JSOna – czy to jest ok?

Jeśli ma kod 200 i brak danych w postaci JSONa to znaczy że zadanie zostało przetworzone?

**Comment by PawelTaberski** [comment]
Powinieneś również otrzymać w body odpowiedzi coś na styl:
```
{
    "id": "e476171a-18b1-44e5-81d1-d142b86ff13d",
    "taskCount": {
            "total": 0,
            "success": 0,
            "failed": 0
    }
}
```

**Comment by autornet** [comment]
Jeśli ilość mi się jednak nie zmienia w total=1, success=0, failed=1

To dlaczego? Jak to zweryfikować?

 

Kod: 200

Aukcja: 6192272988

UUID: A3A78E57-A4FB-4974-9332-D2E8D9D9C003

 

https://api.allegro.pl/sale/offer-quantity-change-commands/A3A78E57-A4FB-4974-9332-D2E8D9D9C003

**Comment by PawelTaberski** [comment]
Sprawdź status tego zadania przy pomocy GET /sale/offer-quantity-change-commands/{commandId}/tasks dostaniesz tam informacje dlaczego dana zmiana nie przeszła pomyślnie.

**Comment by autornet** [comment]
Ok, a co to oznacza i jak ten błąd rozwiązać ?

 

{"tasks":[{"offer":{"id":"6192272988"},"message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","status":"FAIL","scheduledAt":"2019-07-09T12:06:31.347Z","finishedAt":"2019-07-09T12:06:31.629Z","field":"quantity","errors":[{"code":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","message":"Exception when update offer quantity.","details":null,"path":null,"userMessage":"Exception when update offer quantity."}]}]}

 

EXCEPTION_DURING_OFFER_QUANTITY_UPDATE

 

Zmiana ilości miała być z 20 na 19 szt.

**Comment by PawelTaberski** [comment]
Pracujemy nad poprawą i doprecyzowaniem tych błędów. Błąd ten najprawdopodobniej oznacza, że w tej ofercie brak jakiś elementów obowiązkowych i dlatego zmiana jest niemożliwa. Możliwe, że w międzyczasie jakiś parametr stał się obowiązkowy, przez co nie można dokonać zmiany, bo oferta musi być kompletna. Pobierz proszę tą ofertę zasobem GET /sale/offers/{offerId} i spróbuj dokonać zmiany zasobem PUT /sale/offers/{offerId}. Pamiętaj, aby nawet jak zmieniasz tylko stock przesłać całą strukturę oferty. Jeśli edycja nie przejdzie w sekcji error powinny być wylistowane braki.

**Comment by autornet** [comment]
Witam,

 

PYTANIE 1:

 

Aukcja: 7475241069

Ilość na aukcji pokazywało: 5939

 

A aplikacji poprzez API zmieniłem ilość na: 5954

UUID: 5D929F0C-31EF-49FF-B200-4FA4FF4AA883

Status odebrałem, że operacja wykonana poprawnie, a mimo to stan na aukcji jest o 15 sztuk mniej niż wysłano (tyle, co przed aktualizacja 5939).

 

Dlaczego taka różnica występuje czasami?

 

PYTANIE 2:

W wielu aukcjach po aktualizacji ilości otrzymuje statusy np.: "tasks": [... "message":null,"status":"NEW","scheduledAt": "2019-07-19T14:02"

Co to oznacza? Takie UUID nie zmieniają się i ciągle mam je w kolejce do weryfikowania.

 

Paweł Parzych

**Comment by PawelTaberski** [comment]
@autornet Sprawdziłem i odnośnie:
1/ oferty 7475241069 to błąd zgłosiłem sprawę do odpowiedniego zespołu.
2/ statusu NEW również wygląda to na błąd, podeślij proszę trace-id takich zadań, sprawdzimy to.

**Comment by PawelTaberski** [comment]
@autornet Udało nam się już rozwiązać problem z ofertą 7475241069 od teraz edycja stocku powinna przebiegać poprawnie.

**Comment by autornet** [comment]
Ok, był to tylko przykład jednej z kilkunastu aukcji. Czy na wszystkich będzie już ok?

**Comment by PawelTaberski** [comment]
@autornet Koniecznie podeślij proszę w jakich ofertach występuje taki problem.

**Comment by autornet** [comment]
Przykładowy trace-id który nie jest przetworzony w Allegro – jest ich coraz więcej

 

ResponseText: 

Content-Encoding: identity

Expires: 0

Cache-Control: no-cache, no-store, max-age=0, must-revalidate

X-XSS-Protection: 1; mode=block

Pragma: no-cache

X-Frame-Options: DENY

Trace-Id: 5bfa0e24f0156f0e

Date: Tue, 13 Aug 2019 08:06:18 GMT

X-RateLimit-Remaining: 9000

X-Content-Type-Options: nosniff

Transfer-Encoding: chunked

Content-Type: application/json

X-RateLimit-Limit: 9000

 

Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjU2OTU3MzIsInVzZXJfbmFtZSI6IjQwOTc3NTgyIiwianRpIjoiYzkzYjM3NGYtYjM2NS00MjUxLTg3ZmItOGNmNjZhZWU5OWEwIiwiY2xpZW50X2lkIjoiMDdlOTcwNjczZjY2NDc3NmFhNDM4MzY0M2MxZGY5YWQiLCJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdfQ.dXEpLPJ2utAeZ0CWLBZ6hNoOdXXl3dXJ_JYMu8SA1HFyZJD5hn33YZ3u6-cyOtLx1j3N4Cq_Gli1PHBOOBWE9al2UrHjOz0Xfgp9sMitp1E0vYRKq1hEe7d7I6ycPL_5s09milED2OZ-exnLRlvFdJyrU7i1kthg1HNMsY6lvmn4XtNaCpFJNEXsuGgn5Uo5d6DPUzgdGcCb67mdU5Tw70DdPhZKbPHwP2Oy1OuQLFBR3UyZtwF0eI92BelsUb97BD15iagZ8NIMuIwwEOPBl-fjvEpPVW9cmyvsmeEbGEzeQ-lcXRf3tnqEdFhdFe4Uo8BfAtx7lgMr738cuDYAhw

Host: api.allegro.pl

Accept: application/vnd.allegro.public.v1+json

Accept-Encoding: identity

User-Agent: Mozilla/3.0 (compatible; Indy Library)

 

 

Komunikat zwrotny:

{"tasks":[{"offer":{"id":"5788065248"},"message":null,"status":"NEW","scheduledAt":"2019-07-24T18:35:44.855Z","finishedAt":null,"field":"quantity","errors":[]}]}

**Comment by PrzemyslawLukanowski** [comment]
@autornet  Proszę uznać taski jako FAIL, pochodzą z czasu przed wyeliminowaniem problemu (07.08.19). Konieczne jest powtórzenie wywołania zasobu do zmiany ilości sztuk w ofercie.

Pamiętaj, aby nie przesyłać nam w requeście swojego tokena.

**Comment by autornet** [comment]
Usunąłem wszystkie wcześniejsze taski od siebie.

 

 

Response: Content-Encoding: identity

Expires: 0

Cache-Control: no-cache, no-store, max-age=0, must-revalidate

X-XSS-Protection: 1; mode=block

Pragma: no-cache

X-Frame-Options: DENY

Trace-Id: 5fcb8ebc86cfc8c4

Date: Tue, 13 Aug 2019 12:57:09 GMT

X-RateLimit-Remaining: 8999

X-Content-Type-Options: nosniff

Transfer-Encoding: chunked

Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8

X-RateLimit-Limit: 9000

 

Authorization: Bearer XXX

Host: api.allegro.pl

Accept: application/vnd.allegro.public.v1+json

Accept-Encoding: identity

User-Agent: Mozilla/3.0 (compatible; Indy Library)

 

 

Odczytując status mam takie coś:

{"tasks":[{"offer":{"id":"7734740117"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2019-08-13T12:30:32.717Z","finishedAt":"2019-08-13T12:30:32.953Z","field":"publication","errors":[{"code":"NotFoundException","message":"HTTP 404 Not Found","details":"NotFoundException","path":null,"userMessage":null}]}]}

 

Przyczyna?

**Comment by PrzemyslawLukanowski** [comment]
Oferta 7734740117 została zakończona 07.02.2019, po 60 dniach trafiła do archiwum. Nie ma możliwości edycji takiej oferty.

**Comment by autornet** [comment]
Proszę o info – jak sprawdzić status aukcji mając jej numer lub ID ?

**Comment by PrzemyslawLukanowski** [comment]
@autornet Status oferty możesz sprawdzić za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) lub [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) w polu publication.status. Musisz być autoryzowany jako sprzedawca, do którego należą oferty.

**Comment by autornet** [comment]
Kolejne aukcje i problem ze stockiem. Wysyłam zmiane ilości do allego, status jest że przetworzono, a ilość się nie zmienia.

 

KNP32 - stan 53 szt, stan minimalny dla Allegro 20 szt, a w aukcji wystawione 8 szt, ostatni wpis w logach aukcji 6.09 - https://allegro.pl/oferta/rekwizyty-gadzety-do-zdjec-slub-fotobudka-12szt-8115543040

PLRD500-007 - stan 69 szt, stan minimalny dla Allegro 50 szt, a w aukcji wystawione 6 szt, ostatni wpis w logach aukcji 06.09 - https://allegro.pl/oferta/platki-roz-czerwone-slub-wesele-walentynki-500szt-6001054806

VIP602 - stan 714, w aukcji wystawione 723 szt, ostatni wpis w logach aukcji 6.09 - https://allegro.pl/show_item.php?item=8419329077

KLEJ-11x200 10szt - stan 483, w aukcji wystawione 544 szt, ostatni wpis w logach aukcji 05.09 - https://allegro.pl/show_item.php?item=7159530033

**Comment by PrzemyslawLukanowski** [comment]
@autornet Czy mogę prosić o trace-id do powyższych komend zmian stocku?

**Comment by autornet** [comment]
8115543040

{"modification": {"changeType":"FIXED","value": 20},"offerCriteria": [{"type": "CONTAINS_OFFERS","offers": [{"id": "8115543040"}]}]}

 

{"id":"d25b7339-8808-4ed4-bb0d-0f0a070005a7","taskCount":{"total":1,"success":1,"failed":0}}

 

 

6001054806

{"modification": {"changeType":"FIXED","value": 57},"offerCriteria": [{"type": "CONTAINS_OFFERS","offers": [{"id": "6001054806"}]}]}

 

{"id":"49c07e32-a4de-4b01-8b2a-f3046209677c","taskCount":{"total":1,"success":1,"failed":0}}

 

8419329077

{"modification": {"changeType":"FIXED","value": 831},"offerCriteria": [{"type": "CONTAINS_OFFERS","offers": [{"id": "8419329077"}]}]}

 

{"id":"9c27f72b-24ee-4719-864c-7619bd37cf40","taskCount":{"total":1,"success":1,"failed":0}}

 

 

7159530033

{"modification": {"changeType":"FIXED","value": 617},"offerCriteria": [{"type": "CONTAINS_OFFERS","offers": [{"id": "7159530033"}]}]}

 

{"id":"56872ef9-f42c-4c1b-a85c-7e5d9486ba63","taskCount":{"total":1,"success":1,"failed":0}}

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadamy żadnych logów dla podanych commandId. Kiedy były wykonywane te zmiany? Czy mogę prosić o przesłanie pełnych reqestów w formacie cURL (wraz z trace-id)? Czy zauważyłeś, że problem nadal występuje dla bieżących ofert?
