### ISSUE TITLE
Błąd autoryzacji urządzenia

### ISSUE THREAD

**Issue by anitakowalczyk** [allegro/allegro-api#1923]
Witam, jest to moja pierwsza aplikacja Allegro Api z wykorzystaniem Spring Boot i Maven. Próbuję dokonać autoryzacji według poradnika "Autoryzacja Client_credentials flow" ze strony https://developer.allegro.pl/auth/#clientCredentialsFlow. Otrzymuję bez problemów token, a potem dla String responseEntity = restTemplate.exchange(url2, HttpMethod.GET, entity, String.class).getBody(); niestety otrzymuję błąd error 404. Co może być nie tak?

[EmployeeController.java.txt](https://github.com/allegro/allegro-api/files/3365675/EmployeeController.java.txt)
[pom.xml.txt](https://github.com/allegro/allegro-api/files/3365676/pom.xml.txt)
[SpringBootFormHandingApplication.java.txt](https://github.com/allegro/allegro-api/files/3365677/SpringBootFormHandingApplication.java.txt)

**Comment by Gerston** [comment]
Autoryzacja Client Credentials pozwala na dostęp do zasobów publicznych, a z tego co widzę, chcesz pobrać zamówienia, musisz autoryzować aplikację z redirect url, lub device flow

**Comment by anitakowalczyk** [comment]
Rzeczywiście. Niestety po zmianie url na  "https://api.allegro.pl/offers/listing" (chcę wykonać jedynie przykładowe zapytanie o dane z zasobów publicznych) otrzymuję błąd 422 Unprocessable Entity, a po sprawdzeniu ktora linijka wyrzuca wyjatek jest to : "String responseEntity = restTemplate.exchange(url2, HttpMethod.GET, entity, String.class).getBody();"

**Comment by PrzemyslawLukanowski** [comment]
@anitakowalczyk Aby prawidłowo wywołać zasób GET /offers/listing konieczne jest podanie przynajmniej jednego z parametrów:

- category.id - numer ID kategorii
- phrase - fraza
- seller.id - numer ID sprzedawcy

Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/listing/)
