### ISSUE TITLE
"Numer katalogowy części, oryginału, numery zamienników 

### ISSUE THREAD

**Issue by polska2019** [allegro/allegro-api#1926]
Cześć,

Gdzie w mogę wczytać poniższe dane?:

"Numer katalogowy części"
"Numer katalogowy oryginału (opcjonalnie)"
"Numery katalogowe zamienników (opcjonalnie)"

Musze wysłać dokumentację i wskazówki do programisty niemieckojęzycznego/angielkojęzycznego ;-), a sam jestem w tym zielony ...

dzięki!

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą zasobu GET /sale/compatible-products?type={type}&group.id={group.Id} pobierzesz listę dostępnych produktów danej marki. O tym, jak zarządzać sekcję Pasuje do zintegrowaną z bazą pojazdów dowiesz się z [naszego poradnika](https://developer.allegro.pl/compatibility_list/#search).

**Comment by dlis2010** [comment]
o kurczę, @PrzemyslawLukanowski weekend jeszcze trzymał? ;)

**Comment by pawliszka** [comment]
Otwieram, sam szukam dokładnej różnicy między "Numer Katalogowy Oryginału" a "Numer Katalogowy Części" nie jest to powiązane z sekcją pasuje do :)

**Comment by PrzemyslawLukanowski** [comment]
@pawliszka W przypadku części oryginalnej jest to ta sama wartość. W przypadku zamienników należy podać numer części (tą której faktycznie dotyczy oferta) oraz numer oryginału (jako referencja, po której się wyszukuje).

**Comment by pawliszka** [comment]
@PrzemyslawLukanowski dzięki za wyjaśnienie :+1:
