### ISSUE TITLE
Wznawianie/wygaszanie aukcji przez Rest Api

### ISSUE THREAD

**Issue by polska2019** [allegro/allegro-api#1927]
Cześć,

Chciałbym przez Rest Api wznawiać i wygaszać aukcje.

Muszę wskazówki/dokumentację przesłać niemieckojęzycznemu/angielskojęzycznemu programiście który stworzy apkę do wygaszania produktów których nie mamy na magazynie i wznawiania jak tylko się one pojawią,

Z góry dzięki za pomoc,

**Comment by PrzemyslawLukanowski** [comment]
Aby wygasić lub wznowić ofertę użyj zasobu 
[PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT), gdzie commandId to unikatowy numer UUID, który możesz sam wygenerować.
Szczegółowe informacje znajdziesz w naszych poradnikach - [jak wystawić ofertę](https://developer.allegro.pl/sale/) oraz [jak zarządzać ofertami](https://developer.allegro.pl/my_offers/).

**Comment by pawelosajda** [comment]
Należy pamiętać, że nie można w ten sposób wnawiać aukcji tylko oferty Kup Teraz. W takim przypadku otrzymamy błąd 

> Could not change offer publication status. Nie można aktywować zakończonej oferty.

**Comment by pkrzemo** [comment]
> Muszę wskazówki/dokumentację przesłać niemieckojęzycznemu/angielskojęzycznemu programiście 

To już taka bida nastała że programistów trzeba szukać poza granicami kraju?

LOL

**Comment by PrzemyslawLukanowski** [comment]
@pawelosajda  Dziękujemy za sugestię, zaktualizujemy treść poradnika.
