### ISSUE TITLE
Pobieranie listy zakupionych przedmiotów

### ISSUE THREAD

**Issue by repmic** [allegro/allegro-api#1928]
Jak za pomocą RestAPI pobrac dane sprzedającego podczas zakupu przedmiotu. W WebAPI była to metoda doGetPostBuyData.

**Comment by PrzemyslawLukanowski** [comment]
REST API aktualnie nie udostępnia kupującemu możliwości pobrania danych sprzedającego. Niedługo planujemy wdrożyć metodę do pobrania danych o danym userze. W jakim celu potrzebujesz tych informacji?
