### ISSUE TITLE
Problem z description.sections[0].items[0].content: Invalid HTML subset

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1931]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Proszę o wytłumaczenie dlaczego zgodnie z dokumentacją dozwolone tagi to :
```<h1> <b> <p>``` a przy wystawieniu szkicu dzieją się takie cuda 

1. Ten opis jest zły - description.sections[0].items[0].content: Invalid HTML subset
 
```<h1>RINGI LED SMD BMW E36 / E38 / E39 / E46 (reflektor soczewkowy)</h1><p><b>Kod towaru: AKAE01</b></p><p> - Cena dotyczy całego zestawu.</p><p>- W skład wchodzą: 4 ringi oraz niezbędne do montażu okablowanie.</p><p> - Ringi posiadają łączną ilość 480 diod SMD (po 131 diód na każdy ring).</p><p> - Zestaw jest fabrycznie nowy, nigdy nie zakładany i oryginalnie zapakowany.</p><p> - Ringi świecą wyjątkowo intensywnie zapewniając ich doskonałą widoczność nawet w słoneczny dzień.</p><p> - Nowoczesna technologia diód SMD powoduje atrakcyjniejszy wygląd samochodu.</p>```
 
 
2. Ten jest dobry
 
```RINGI LED SMD BMW E36 / E38 / E39 / E46 (reflektor soczewkowy)<b>Kod towaru: AKAE01</b> - Cena dotyczy całego zestawu.- W skład wchodzą: 4 ringi oraz niezbędne do montażu okablowanie. - Ringi posiadają łączną ilość 480 diod SMD (po 131 diód na każdy ring). - Zestaw jest fabrycznie nowy, nigdy nie zakładany i oryginalnie zapakowany. - Ringi świecą wyjątkowo intensywnie zapewniając ich doskonałą widoczność nawet w słoneczny dzień. - Nowoczesna technologia diód SMD powoduje atrakcyjniejszy wygląd samochodu.```
 
 
3. Ten jest zły - description.sections[0].items[0].content: Invalid HTML subset
 
```<h1>RINGI LED SMD BMW E36 / E38 / E39 / E46 (reflektor soczewkowy)</h1><b>Kod towaru: AKAE01</b> - Cena dotyczy całego zestawu.- W skład wchodzą: 4 ringi oraz niezbędne do montażu okablowanie. - Ringi posiadają łączną ilość 480 diod SMD (po 131 diód na każdy ring). - Zestaw jest fabrycznie nowy, nigdy nie zakładany i oryginalnie zapakowany. - Ringi świecą wyjątkowo intensywnie zapewniając ich doskonałą widoczność nawet w słoneczny dzień. - Nowoczesna technologia diód SMD powoduje atrakcyjniejszy wygląd samochodu.```
 
4. Ten opis jest zły - description.sections[0].items[0].content: Invalid HTML subset
 
```RINGI LED SMD BMW E36 / E38 / E39 / E46 (reflektor soczewkowy)<p>Kod towaru: AKAE01</p><p> - Cena dotyczy całego zestawu.</p><p>- W skład wchodzą: 4 ringi oraz niezbędne do montażu okablowanie.</p><p> - Ringi posiadają łączną ilość 480 diod SMD (po 131 diód na każdy ring).</p><p> - Zestaw jest fabrycznie nowy, nigdy nie zakładany i oryginalnie zapakowany.</p><p> - Ringi świecą wyjątkowo intensywnie zapewniając ich doskonałą widoczność nawet w słoneczny dzień.</p><p> - Nowoczesna technologia diód SMD powoduje atrakcyjniejszy wygląd samochodu.</p>```

Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem wywołania i wygląda to następująco:
1) API zwraca prawidłowe dane,
2) API zwraca “description.sections[0].items[0].content: Invalid HTML subset”  - brak znaczników HTML, jedyne to pogrubienie ”<b>Kod towaru: AKAE01</b>”
3) API zwraca “description.sections[0].items[0].content: Invalid HTML subset” - brak opakowania w znacznik <p></p> zawartości po <b>Kod towaru: AKAE01</b>
4) API zwraca “description.sections[0].items[0].content: Invalid HTML subset” - pierwsze zdanie nie jest opakowane w żaden znacznik HTML

Czy jesteś pewien, że wskazujesz prawidłowe przykłady dla wywołań? Prześlij tutaj przykładowy request, pozwoli nam to szybciej zlokalizować problem.

**Comment by grojanteam** [comment]
Trochę się bawiłem z parsowaniem kodu HTML dla ofert

1. jest jak najbardziej ok i **powinien** działać
2. nie jest ok bo kod nie może być bez żadnego opakowania <p><h1><ul> dodatkowo <b> nie może być bez opakowania musi być w <p> lub w <li>, użycie <b> w <h1> lub <h2> nie jest dozwolone
3. nie jest ok, bo jak w punkcie 2 <b> nie może być bez opakowania
4. kod HTML sam w sobie jest błędny, zamykasz <p> mimo że go nawet nie otwierasz

Największą zabawę jaką zajęło mi budowanie dodatku do API z allegro, był właśnie poprawnie budowany opis.

Powodzenia @qshop123

**Comment by qshop123** [comment]
Ok
Temat rozwiązany, opisy były tak
```
<p><h1>Nazwa towaru</h1>.....</p>
```

Pomogło zmiana na tak

```
<h1>Nazwa towaru</h1>.....
```

Całość była po prostu w tagach <p>
