### ISSUE TITLE
Device flow dla Allegro OAuth w MS Access.

### ISSUE THREAD

**Issue by GosiaJK** [allegro/allegro-api#1932]
Nie mogę przeskoczyć tego procesu w ms access. Czy ktoś mi pomoże? Oczywiście odpłatnie.

**Comment by pkrzemo** [comment]
A dlaczego musi to być w najbardziej nieprzydatnym do tego celu programie, czyli ms access?

**Comment by GosiaJK** [comment]
Wszystko już rozgryzłam w ms access. Pozostało jedynie logowanie na własne dane. To dziwne, że nie pozostawili takiego systemu logowania na własne dane jak w web api. Tam wszystko było prostsze.

**Comment by kfijalko** [comment]
google podpowiada taką bibliotekę:
https://vba-tools.github.io/VBA-Web/docs/

**Comment by GosiaJK** [comment]
Dzięki za wskazówkę. Przekopię się przez tę bibliotekę. Może coś się uda zrobić.
