### ISSUE TITLE
Jak zmienić shippingTime danej aukcji ?

### ISSUE THREAD

**Issue by meblehaag** [allegro/allegro-api#1933]
Dzień dobry może i słabo szukam ale chyba nie o to chodzi żeby godzinę tracić przeszukując dokumentację z każdej strony i do góry nogami. Jak zmienić shippingTime dla aukcji? Na webapi robiło się to ChangeItemFields. Teraz nie mogę znaleźć komendy, nie jest to jasno opisane na pewno.

**Comment by PrzemyslawLukanowski** [comment]
Aby zmienić czas wysyłki musisz najpierw za pomocą GET /sale/offers/{offerId} pobrać ofertę, następnie za pomocą PUT /sale/offers/{offerId} przesłać ją całą, z wyedytowaną wartością dla pola delivery.handlingTime. Więcej na temat edycji znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#2).

**Comment by pkrzemo** [comment]
A tymczasem poprawna odpowiedź to.... SIE NIE DA!  
LOL
Oczywiście mogło się coś zmienić w tym temacie. Ale z tego co wiem to musisz zdefiniować cennik dostaw i przypiąć go do oferty.  Tylko tak poprzez REST API jesteś w stanie zmienić shippingTime.
Wydaje mi się więc że  nie robi się tego przez PUT /sale/offers/{offerId} .
;-)

**Comment by meblehaag** [comment]
Uwaga wklejam wszystko z poradnika co ma pomóc przy edycji czasu:

Edycja pojedynczej oferty
Na początek możesz pobrać ofertę, którą chcesz edytować za pomocą metody GET sale/offers/{offerId}. Następnie metodą PUT /sale/offers/{offerId} prześlij ofertę z wprowadzonymi zmianami. Zmiany możesz wprowadzać w każdej ofercie - tej trwającej i tej zakończonej. Jeśli prześlesz niekompletne dane, to w polu validation wyświetlimy:

    co powinieneś uzupełnić,
    błędy, jakie pojawiły się w twojej ofercie

Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty, łącznie z numerem oferty.

Sprawdzimy, sprawdzimy i napiszemy.

**Comment by PrzemyslawLukanowski** [comment]
W zależności od zmiany shippingTime (czas dostawy) czy handlingTime (czas wysyłki) inny jest sposób edycji. Moja wcześniejsza odpowiedź dotyczyła zmiany czasu wysyłki.
Aby zmienić czas dostawy dla konkretnej metody dostawy, najpierw musisz się upewnić, czy jest to możliwe. Zrobisz to za pomocą zasobu [GET /sale/delivery-method](https://developer.allegro.pl/sale/#shipping-rates) - wartość “true” w polu “customizable” przy metodzie dostawy oznacza możliwość edycji. Następnie za pomocą [GET /sale/shipping-rates/{shippingRateId}](https://developer.allegro.pl/documentation/#operation/getShippingRatesSetUsingGET) pobierz cennik i prześlij całą jego strukturę ze zmienioną wartością dla shippingTime poprzez PUT /sale/shipping-rates/{shippingRateId}.

**Comment by premax** [comment]
Dlaczego zasób GET /sale/offers nie udostępnia informacji o handlingTime w danej aukcji?  W ten sposób muszę sledzić po swojej stronie jaki nastawiałem w każdej aukcji handlingTime, jeśli mi schodzi stock z podręcznego magazynu i muszę wydłużyć handlingTime.
