### ISSUE TITLE
Kończenie trwającej aukcji

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1934]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Niech mnie ktoś oświeci.
Podajecie w dokumentacji że można kończyć trwającą aukcję podając pod endpoint 
1. GET sale/offer-publication-commands/{uuid} podając parametr END
response " [total] => 1 [success] => 1 [failed] => 0 ) " - nie sie nie dzieje, auckja trwa

Gdzieś indziej znalazłem że aukcję się kończy tak
2. POST sale/offer-publication-commands/{uuid}/tasks podając parametr END
response " [total] => 1 [success] => 1 [failed] => 0 ) " - nie sie nie dzieje, auckja trwa

Jeszcze gdzieś indzie że tak
3. POST sale/offer-publication-commands/{uuid} podając parametr END
response " [total] => 1 [success] => 1 [failed] => 0 ) " - nie sie nie dzieje, auckja trwa

To jak w końcu mam zakończyć JEDNĄ aukcję?
Nie odsyłajcie tylko do dokumentacji, bo tam jest podany pierwszy przykład

**Comment by PrzemyslawLukanowski** [comment]
Ofertę zakończysz za pomocą zasobu [PUT sale/offer-publication-commands/{UUID}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT), przeczytasz o tym w [naszym poradniku](https://developer.allegro.pl/my_offers/#5).

Zasobem [GET sale/offer-publication-commands/{uuid}](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET) pobierzesz informacje o statusie zadania publikacji ofert w serwisie. Więcej na ten temat znajdziesz [tutaj.](https://developer.allegro.pl/sale/##offer-publication-commands-commandId)

Odnośnie:

POST sale/offer-publication-commands/{uuid}/tasks
POST sale/offer-publication-commands/{uuid}

nie ma takich zasobów, ich wywołanie kończy się błędem “The HTTP method is not allowed”.

**Comment by qshop123** [comment]
Niestety ale aukcja dalej trwa

```
$data = new stdClass();
$data->publication->action = "END";
$data->offerCriteria[0]->offers[0]->id = $uuid;
$data->offerCriteria[0]->type = "CONTAINS_OFFERS";
$this->put("sale/offer-publication-commands/$uuid",$data);
```

Jako $uuid podaję 6e0cbeac-4ade-435f-84ff-aebe372c5174 a w odpowiedzi przychodzi 
[id] => 6e0cbeac-4ade-435f-84ff-aebe372c5174 [taskCount] => stdClass Object ( [total] => 0 [success] => 0 [failed] => 0 ) 

Próbowałem jako ->id podać ID aukcji czyli 6206451534 ale jest to samo :)
Nie ważne co podam jako ID przychodzi to samo

```
stdClass Object ( [publication] => stdClass Object ( [action] => END ) [offerCriteria] => Array ( [0] => stdClass Object ( [offers] => Array ( [0] => stdClass Object ( [id] => gruszka ) ) [type] => CONTAINS_OFFERS ) ) ) stdClass Object ( [id] => 6e0cbeac-4ade-435f-84ff-aebe372c5174 [taskCount] => stdClass Object ( [total] => 0 [success] => 0 [failed] => 0 ) )
```

Podałem jako ID "gruszka" i przyszła odpowiedź że się nic nie wydarzyło.

Co robię źle?

**Comment by PrzemyslawLukanowski** [comment]
@qshop123  Sprawdź jaki response otrzymujesz na wywołanie 
GET /sale/offer-publication-commands/6e0cbeac-4ade-435f-84ff-aebe372c5174tasks

$data->offerCriteria[0]->offers[0]->id = $uuid - w tym miejscu zawsze przekazuj id aukcji (jako string)

**Comment by qshop123** [comment]
Witam
Zmiana stanu encji za pomocą metody GET - proszę o uzasadnienie DLACZEGO?

**Comment by qshop123** [comment]
Ponownie nie działa

```
$data = new stdClass();
$data->publication->action = "END";
$data->offerCriteria[0]->offers[0]->id = $draft_id;
$data->offerCriteria[0]->type = "CONTAINS_OFFERS";
$out = json_decode($this->get("sale/offer-publication-commands/$uuid/tasks",$data));
```

Request
```
stdClass Object ( [publication] => stdClass Object ( [action] => END ) [offerCriteria] => Array ( [0] => stdClass Object ( [offers] => Array ( [0] => stdClass Object ( [id] => 6206461053 ) ) [type] => CONTAINS_OFFERS ) ) ) 
```

Response
```
stdClass Object ( [tasks] => Array ( [0] => stdClass Object ( [offer] => stdClass Object ( [id] => 6206461053 ) [message] => [status] => SUCCESS [scheduledAt] => 2019-07-10T08:22:43.999Z [finishedAt] => 2019-07-10T08:22:49.371Z [field] => publication [errors] => Array ( ) ) ) )
```

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
> “Zmiana stanu encji za pomocą metody GET - proszę o uzasadnienie DLACZEGO?”

Za pomocą zasobu [GET sale/offer-publication-commands/{uuid}](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET) nie zmieniasz stanu, tylko [pobierasz informację o statusie publikacji oferty](https://developer.allegro.pl/sale/#step-10-tasks). W response otrzymasz informację, które szybciej pomogą zlokalizować problem, przez który nie możesz zakończyć oferty poprzez [PUT /sale/offer-publication-commands/{commandId} ](https://developer.allegro.pl/my_offers/#5).

Przykładowy request powinien wyglądać następująco:
```
curl -X GET \
  https://api.allegro.pl/sale/offer-price-change-commands/aacfb40c-daca-4252-91ef-244d68d28123/tasks \
  -H 'Authorization: Bearer {token}' \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'content-type: application/vnd.allegro.public.v1+json'
```
Widzę, że w Twoim przypadku wysyłasz w strukturze dodatkowe dane.

Przykładowy response:
```
[
{
            "offer": {
                "id": "7168735300"
            },
            "message": "",                      -- opis dlaczego nie udało się  opublikować 
                                                oferty w serwisie
            "status": "SUCCESS",                -- status publikacji oferty w serwisie,
                                                dostępne są trzy wartości: SUCCESS (publikacja 
                                                zakończyła się pomyślnie); FAIL 
                                                (wystąpiły błędy przy publikacji i oferta nie 
                                                jest aktywna w serwisie); NEW (trwa publikacja 
                                                oferty w serwisie, akcja nie została jeszcze zakończona)
            "scheduledAt": "2018-03-01T11:02:50.005+01:00",
            "finishedAt": "2018-03-01T11:02:51.691+01:00",
            "field": "publication"
        }
    ]
```

**Comment by qshop123** [comment]
Okej.
No to i tak mi nic nie dało

PUT 

Request
```
stdClass Object ( [publication] => stdClass Object ( [action] => END ) [offerCriteria] => Array ( [0] => stdClass Object ( [offers] => Array ( [0] => stdClass Object ( [id] => 6206461053 ) ) [type] => CONTAINS_OFFERS ) ) ) 
```

Response
```
stdClass Object ( [id] => e843189f-6dad-4b58-b02b-9e45712dc0eb [taskCount] => stdClass Object ( [total] => 0 [success] => 0 [failed] => 0 ) )
```

KOD

```
$data = new stdClass();
$data->publication->action = "END";
$data->offerCriteria[0]->offers[0]->id = $draft_id;
$data->offerCriteria[0]->type = "CONTAINS_OFFERS";
$out = json_decode($this->put("sale/offer-publication-commands/$uuid",$data));
```

**Comment by PawelTaberski** [comment]
Odpowiedź jaką otrzymałeś jest prawidłowa, bo nie wiemy od razu ile ofert jest do przetworzenia i ile z tych zadań zakończy się sukcesem. Aby to sprawdzić należy skorzystać np z zasobu GET /sale/offer-price-change-commands/{commandId}, gdzie w odpowiedzi otrzymasz:
```
{
    "id": "aacfb40c-daca-4252-91ef-244d68d28123",
    "taskCount": {
        "total": 2,                                  -- liczba ofert, w których zleciłeś edycję
        "success": 2,                                -- liczba ofert, w których zmiany zostały 
                                                        wprowadzone 
        "failed": 0                                  -- liczba ofert, w których
                                                        zmiany nie zostały wprowadzone
    }          
}
```

**Comment by qshop123** [comment]
To skoro odpowiedź jest prawidłowa i aukcja została przekazana do zakończenia, to coś strasznie długo się kończy https://allegro.pl.allegrosandbox.pl/oferta/zasilacz-modecom-micro-atx-mc-s420w-60mm-fan-6206461053

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz przesłać nam tutaj pełnego requesta w formacie danych **curl,** którym próbujesz zakończyć ofertę?
