### ISSUE TITLE
Dodawanie produktu do aukcji - may not be null

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#1935]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Aukcje wystawiają się poprawnie, ale jak próbuję dodać product-id, to mam nic nie mówiący błąd "may not be null". Przykładowy produkt:
nazwa: Pachnące patyczki Air Wick Pachnące Patyczki 30 ml
EAN: 5900627062656
produkt_id: 280933b3-4661-4fc1-902d-f201f944c14f
Czy to dlatego, że w danej kategorii nie są jeszcze udostępnione produkty?

**Comment by TomekKaczmarek** [comment]
Niestety nie widząc pełnego requestu i responsa trudno jest mi ocenić, co możesz niepoprawnie przesyłać.

Najważniejsze przy wiązaniu oferty z produktem, jest to by dane produktu były spójne z ofertą (kategoria i parametry) - upewnij się, że przesyłasz w ofercie dokładnie takie same dane, jak otrzymałeś w GET sale/products/280933b3-4661-4fc1-902d-f201f944c14f.

Więcej informacji na ten temat znajdziesz w naszym poradniku - [Jak powiązać ofertę z produktem](https://developer.allegro.pl/productization/)

**Comment by mareklemur** [comment]
Faktycznie, różne kategorie. Ale nie zmienia to faktu, że komunikat niewiele mówi.

**Comment by mareklemur** [comment]
Niestety w tej samej kategorii jest ten sam błąd.
Produkt nie ma parametrów:
nazwa: Odświeżacz powietrza wkład Air Wick Freshmatic 250 ml
EAN: 5900627057553
produkt_id: 1673e294-42f4-4f5f-a9c7-3b54b437d33f
kategoria produktu: 253354

**Comment by TomekKaczmarek** [comment]
@mareklemur podaj proszę ID konta i wklej tu culre z requestem i responsem, przyjrzę się tematowi.

**Comment by mareklemur** [comment]
konto lemur_24

https://api.allegro.pl/sale/products/46255720-37ac-49eb-b478-ddad4bdc728c

Response:
{"id":"46255720-37ac-49eb-b478-ddad4bdc728c","name":"Odświeżacz powietrza Air Wick Pure Aerozol 250 ml","category":{"id":"253354"},"parameters":[],"images":[],"eans":["5900627070378"],"offerRequirements":{"parameters":[]},"compatibilityList":{"items":[]}}

Potwierdź proszę czy ten produkt faktycznie nie ma parametrów.

**Comment by TomekKaczmarek** [comment]
@mareklemur takie produkty mogą się zdarzyć. Nie jest to błąd. W takiej sytuacji możesz dodać do oferty product.id,  category.id, oraz EAN który dla niego otrzymałeś. Pozostałe parametry wypełniasz we własnym zakresie.

**Comment by mareklemur** [comment]
OK, no to podebuguję jak się sytuacja powtórzy. Rozwińcie opis tego błędu, bo "may not be null" nic nie mów.

**Comment by TomekKaczmarek** [comment]
@mareklemur jasne, możemy poprawić komunikat błędu, tylko tak jak prosiłem, potrzebowałbym treść requestu, który wysyłasz, by zidentyfikować w jakiej sytuacji błąd występuje.

**Comment by mareklemur** [comment]
Miałem błąd w kodzie - zamiast zmiennej "id" była "product". Można zamknąć.
