### ISSUE TITLE
Dodatkowy identyfikator zdjęć

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#1936]
:bulb: **Sugestia**

Witam
dodanie do metody https://upload.allegro.pl/sale/images pola własny identyfikator (produktu), oraz przygotowanie odpowiedniego GET pozwoliłoby na pobranie listy zdjęć do konkretnego produktu. Mocno ułatwiłoby to zarządzanie zdjęciami i dopinanie ich do wystawianych ofert.

**Comment by PrzemyslawLukanowski** [comment]
@pfunkowski  Dziękujemy za sugestię, przekazałem ją do odpowiedniego zespołu. Jeśli zdecydujemy się ją ,wdrożyć poinformujemy o tym w dedykowanym komunikacie.
