### ISSUE TITLE
[restAPI] 415 UNSUPPORTED_MEDIA_TYPE

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1937]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

1. Dodaję ofertę
2. Dodaję zdjęcia, dostaję ich guidy 
3. R&R wygląda tak (poniżej)
4. dostaję błąd 415 UNSUPPORTED_MEDIA_TYPE
Prośba o sprawdzenie dlaczego zdjęcia się nie dodały

Przy okazji SUGESTIA, może jak zdjęć nie ma w serwisie dodacie lepszy komunikat

REQUEST 2019-07-09 12:28:19.0684504 
curl -X POST \
  'https://api.allegro.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"9d3cd6e6-5ab6-497f-940b-7c75d8bf2492"},"returnPolicy":{"id":"56652b76-b34e-4ce3-aa31-be353989f42a"},"warranty":{"id":"93d33136-136b-4dfe-938e-817c3ee22533"}},"category":{"id":"121489"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":{"additionalInfo":"Kupując na naszych aukcjach płacisz tylko raz za przesyłkę, jeśli waga zakupionych towarów mieści się do 30 kg i/lub paczka nie przekracza długości 200 cm . Powyżej tej wagi lub rozmiaru koszt transportu będzie ustalany indywidualnie.","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"51bbf54f-9356-47fc-b9e8-eb9821235491"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11beaf/e284e67e4736ab8c82e6251143a5"},{"type":"TEXT","content":"<h2>FREZ DIN6527L Z2-HB 6.00 x 10 x 57 x 6 VHM TiAlN</h2>\r\n\r\n<p>Kod: S545210600S</p>\r\n\r\n<p>Producent:&nbsp;<b>R. STOCK AG</b></p>\r\n\r\n<p>Frez trzpieniowy 2-ostrzowy w pokryciu TiAlN przeznaczony do frezowania stali i staliwa o wytrzymałości powyżej 900 N/mm2, żeliwa szarego, żeliwa utwardzanego, żeliwa ciągliwego, stali CrNi, brązu, mosiądzu, miedzi, aluminium o wysokiej zawartości krzemu, tworzyw abrazyjnych. #r{width:100%;border: 1px solid #A1A3A2;background-color:#EAEAEA;text-align:center;border-collapse:collapse;font-size:0.9em;}#r td{border: 1px solid #A1A3A2;}#t td{color:black;background-color:white;} Kod d1 d2 l1 l2 Z mm mm mm mm S545210600S 6 6 57 10 2</p>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/113194/a6f6a47948ddbe6b597e61bcddcf"}]}]},"ean":null,"external":{"id":"S545210600S"},"id":null,"images":[{"url":"https://a.allegroimg.com/original/11beaf/e284e67e4736ab8c82e6251143a5"},{"url":"https://a.allegroimg.com/original/113194/a6f6a47948ddbe6b597e61bcddcf"}],"location":{"city":"Koszalin","countryCode":"PL","postCode":"75-129","province":"ZACHODNIOPOMORSKIE"},"name":"FREZ DIN6527L Z2-HB 6.00 x 10 x 57 x 6 VHM TiAlN","parameters":[{"id":"11323","rangeValue":null,"values":null,"valuesIds":["11323_1"]}],"payments":{"invoice":"VAT"},"product":null,"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"PT720H","endingAt":null,"startingAt":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"65.56","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":2,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

RESPONSE 2019-07-09 12:28:19.7715867 Database: CDNeSklep_1428 Duration: 703,1363ms
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "9d3cd6e6-5ab6-497f-940b-7c75d8bf2492"
      },
      "ReturnPolicy": {
        "Id": "56652b76-b34e-4ce3-aa31-be353989f42a"
      },
      "Warranty": {
        "Id": "93d33136-136b-4dfe-938e-817c3ee22533"
      }
    },
    "Category": {
      "Id": "121489"
    },
    "CompatibilityList": {
      "Items": null
    },
    "Contact": null,
    "CreatedAt": "2019-07-09T10:28:19Z",
    "Delivery": {
      "AdditionalInfo": "Kupując na naszych aukcjach płacisz tylko raz za przesyłkę, jeśli waga zakupionych towarów mieści się do 30 kg i/lub paczka nie przekracza długości 200 cm . Powyżej tej wagi lub rozmiaru koszt transportu będzie ustalany indywidualnie.",
      "HandlingTime": "PT24H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "51bbf54f-9356-47fc-b9e8-eb9821235491"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "IMAGE",
              "Url": "https://a.allegroimg.com/original/11beaf/e284e67e4736ab8c82e6251143a5"
            },
            {
              "Type": "TEXT",
              "Content": "<h2>FREZ DIN6527L Z2-HB 6.00 x 10 x 57 x 6 VHM TiAlN</h2>\r\n\r\n<p>Kod: S545210600S</p>\r\n\r\n<p>Producent:&nbsp;<b>R. STOCK AG</b></p>\r\n\r\n<p>Frez trzpieniowy 2-ostrzowy w pokryciu TiAlN przeznaczony do frezowania stali i staliwa o wytrzymałości powyżej 900 N/mm2, żeliwa szarego, żeliwa utwardzanego, żeliwa ciągliwego, stali CrNi, brązu, mosiądzu, miedzi, aluminium o wysokiej zawartości krzemu, tworzyw abrazyjnych. #r{width:100%;border: 1px solid #A1A3A2;background-color:#EAEAEA;text-align:center;border-collapse:collapse;font-size:0.9em;}#r td{border: 1px solid #A1A3A2;}#t td{color:black;background-color:white;} Kod d1 d2 l1 l2 Z mm mm mm mm S545210600S 6 6 57 10 2</p>\r\n"
            }
          ]
        },
        {
          "Items": [
            {
              "Type": "IMAGE",
              "Url": "https://a.allegroimg.com/original/113194/a6f6a47948ddbe6b597e61bcddcf"
            }
          ]
        }
      ]
    },
    "Ean": null,
    "External": {
      "Id": "S545210600S"
    },
    "Id": "8287886057",
    "Images": [
      {
        "Url": "https://a.allegroimg.com/original/11beaf/e284e67e4736ab8c82e6251143a5"
      },
      {
        "Url": "https://a.allegroimg.com/original/113194/a6f6a47948ddbe6b597e61bcddcf"
      }
    ],
    "Location": {
      "City": "Koszalin",
      "CountryCode": "PL",
      "PostCode": "75-129",
      "Province": "ZACHODNIOPOMORSKIE"
    },
    "Name": "FREZ DIN6527L Z2-HB 6.00 x 10 x 57 x 6 VHM TiAlN",
    "Parameters": [
      {
        "Id": "11323",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "11323_1"
        ]
      }
    ],
    "Payments": {
      "Invoice": "VAT"
    },
    "Product": null,
    "Promotion": null,
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": "PT720H",
      "EndingAt": null,
      "StartingAt": null
    },
    "SellingMode": {
      "Format": "BUY_NOW",
      "Price": {
        "Amount": "65.56",
        "Currency": "PLN"
      },
      "MinimalPrice": null,
      "StartingPrice": null
    },
    "SizeTable": null,
    "Stock": {
      "Available": 2,
      "Unit": "UNIT"
    },
    "UpdatedAt": "2019-07-09T10:28:19.964Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-07-09T10:28:19.963Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "fe2963f0a104184a",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PrzemyslawLukanowski** [comment]
Błąd 415 wskazuje na błąd w nagłówku Content-Type i w takim przypadku response powinien zwrócić error. Czy jesteś pewien, że załączyłeś nam prawidłowy request i response? 
W zależności od tego, jak przesyłasz zdjęcia (link lub upload) musisz podać inne wartości, przeczytasz o tym w [naszym poradniku](https://developer.allegro.pl.allegrosandbox.pl/sale/#step-3-images).

**Comment by SebastianOzdoba** [comment]
Temat do zamknięcia, winny Klient :)
