### ISSUE TITLE
nie działa pobieranie zamówień

### ISSUE THREAD

**Issue by akxx87** [allegro/allegro-api#1938]
Od godziny 11 nie działa pobieranie listy zamówień w api produkcyjnym

$uri = 'https://api.allegro.pl/order/checkout-forms?limit=100&status=READY_FOR_PROCESSING';

object(Httpful\Response)#17 (13) {
  ["body"]=>
  string(0) ""
  ["raw_body"]=>
  string(0) ""
  ["headers"]=>
  object(Httpful\Response\Headers)#18 (1) {
    ["headers":"Httpful\Response\Headers":private]=>
    array(15) {
      ["expires"]=>
      string(1) "0"
      ["cache-control"]=>
      string(46) "no-cache, no-store, max-age=0, must-revalidate"
      ["x-xss-protection"]=>
      string(14) "1 ; mode=block"
      ["server"]=>
      string(5) "envoy"
      ["pragma"]=>
      string(8) "no-cache"
      ["x-frame-options"]=>
      string(4) "DENY"
      ["trace-id"]=>
      string(16) "8f0429d5ebdf3ea7"
      ["referrer-policy"]=>
      string(11) "no-referrer"
      ["date"]=>
      string(29) "Tue, 09 Jul 2019 12:45:02 GMT"
      ["www-authenticate"]=>
      string(6) "Bearer"
      ["x-ratelimit-remaining"]=>
      string(4) "9000"
      ["x-content-type-options"]=>
      string(7) "nosniff"
      ["content-length"]=>
      string(1) "0"
      ["x-ratelimit-limit"]=>
      string(4) "9000"
      ["x-envoy-upstream-service-time"]=>
      string(2) "22"
    }
  }
  ["raw_headers"]=>
  string(452) "HTTP/1.1 401 Unauthorized
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 8f0429d5ebdf3ea7
referrer-policy: no-referrer
date: Tue, 09 Jul 2019 12:45:02 GMT
www-authenticate: Bearer
x-ratelimit-remaining: 9000
x-content-type-options: nosniff
content-length: 0
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 22"
  ["request"]=>
  object(Httpful\Request)#16 (22) {
    ["uri"]=>
    string(81) "https://api.allegro.pl/order/checkout-forms?limit=100&status=READY_FOR_PROCESSING"
    ["method"]=>
    string(3) "GET"
    ["headers"]=>
    array(3) {
      ["accept"]=>
      string(36) "application/vnd.allegro.beta.v1+json"
      ["authorization"]=>
      string(596) "bearereyJhkg"
      ["Content-Length"]=>
      int(0)
    }
    ["raw_headers"]=>
    string(1067) "GET /order/checkout-forms?limit=100&status=READY_FOR_PROCESSING HTTP/1.1
Host: api.allegro.pl
Expect:
User-Agent: Httpful/0.2.20 (cURL/7.52.1 PHP/7.0.33-0+deb9u3 (Linux) Apache/2.4.25 (Debian) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36)
Content-Type: 
Accept: */*; q=0.5, text/plain; q=0.8, text/html;level=3;
accept: application/vnd.allegro.beta.v1+json
authorization: bearereyJhkg
Content-Length: 0
"
    ["strict_ssl"]=>
    bool(false)
    ["content_type"]=>
    NULL
    ["expected_type"]=>
    NULL
    ["additional_curl_opts"]=>
    array(0) {
    }
    ["auto_parse"]=>
    bool(true)
    ["serialize_payload_method"]=>
    int(2)
    ["username"]=>
    NULL
    ["password"]=>
    NULL
    ["serialized_payload"]=>
    NULL
    ["payload"]=>
    NULL
    ["parse_callback"]=>
    NULL
    ["error_callback"]=>
    NULL
    ["send_callback"]=>
    NULL
    ["follow_redirects"]=>
    bool(false)
    ["max_redirects"]=>
    int(25)
    ["payload_serializers"]=>
    array(0) {
    }
    ["_ch"]=>
    resource(4) of type (Unknown)
    ["_debug"]=>
    NULL
  }
  ["code"]=>
  int(401)
  ["content_type"]=>
  string(0) ""
  ["parent_type"]=>
  string(0) ""
  ["charset"]=>
  string(5) "utf-8"
  ["meta_data"]=>
  array(26) {
    ["url"]=>
    string(81) "https://api.allegro.pl/order/checkout-forms?limit=100&status=READY_FOR_PROCESSING"
    ["content_type"]=>
    NULL
    ["http_code"]=>
    int(401)
    ["header_size"]=>
    int(456)
    ["request_size"]=>
    int(1044)
    ["filetime"]=>
    int(-1)
    ["ssl_verify_result"]=>
    int(0)
    ["redirect_count"]=>
    int(0)
    ["total_time"]=>
    float(0.05907)
    ["namelookup_time"]=>
    float(0.004207)
    ["connect_time"]=>
    float(0.009733)
    ["pretransfer_time"]=>
    float(0.030962)
    ["size_upload"]=>
    float(0)
    ["size_download"]=>
    float(0)
    ["speed_download"]=>
    float(0)
    ["speed_upload"]=>
    float(0)
    ["download_content_length"]=>
    float(0)
    ["upload_content_length"]=>
    float(-1)
    ["starttransfer_time"]=>
    float(0.059045)
    ["redirect_time"]=>
    float(0)
    ["redirect_url"]=>
    string(0) ""

**Comment by thsPL** [comment]
Potwierdzam, przynajmniej od godziny 12 nie można pobrać szczegółów transakcji. Podobna sytuacja do tej, jaka miała miejsce ze 2 tygodnie temu.

**Comment by PawelTaberski** [comment]
Czy problem dalej u was występuje przetestowałem i zasób GET /order/checkout-forms działa poprawnie

**Comment by akxx87** [comment]
Tak dalej nie działa również na nowym tokenie.

**Comment by PawelTaberski** [comment]
Problemem jest błędna wielkość litery. Przesyłasz bearer a powinno być **Bearer**.

**Comment by thsPL** [comment]
Nowy token niczego nie zmienił. Transakcje spływają, ale pobieranie szczegółów transakcji (dla READY_FOR_PROCESSING) zwraca błąd 401. Przynajmniej tak jest u mnie. Efekt jest dokładnie taki sam jak tydzień temu (ktoś założył wtedy wątek tutaj: https://github.com/allegro/allegro-api/issues/1900)

**Comment by thsPL** [comment]
> 
> 
> Problemem jest błędna wielkość litery. Przesyłasz bearer a powinno być **Bearer**.

Nie grzebałem nic od miesiąca przy tych modułach, ale rzeczywiście zmiana litery pomogła. Przed 11:00 działało również z "bearer". Jest tutaj pewna nie konsekwencja, ponieważ inne funkcje z "bearer" mi działają poprawnie no i przede wszystkim o ile dobrze pamiętam funkcja autoryzująca zwraca też "bearer" (małą literą).

**Comment by PawelTaberski** [comment]
Tak, problem pojawił się niedawno, jednakże docelowo będziemy wymagali aby było to przesyłane z dużej litery.
