### ISSUE TITLE
Brak obsługi czasu trwania 20 dni na sandboxie

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#194]
Jak w tytule. API na produkcji dla metody doGetSellFormFieldsForCategory z FID 4 oraz kategorią  256627 (choć pewnie nie ma ona znaczenia) zwraca:

sellFormDesc: 3|5|7|10|14|20|30|Do wyczerpania
sellFormOptsValues: 0|1|2|3|4|6|5|99
sellFormFieldDesc: Uwaga! Jeśli w FID 4 podasz wartość 4 (14 dni), ofertę Kup teraz wystawimy na 20 dni, a licytację na 10 dni.

Czas trwania 30 dni jest dostępny tylko w formacie sprzedaży sklep. W FID 29 (Format sprzedaży) podaj wartość 1.

Podczas gdy dla sandboxa:

sellFormDesc: 3|5|7|10|14|30|Do wyczerpania
sellFormOptsValues: 0|1|2|3|4|5|99
sellFormFieldDesc: "Przy wystawieniu na 14 dni - pobierana jest opłata 0,20 zł, przy wystawieniu "do wyczerpania" opłaty pobierane cyklicznie"

Przez co nie da się wystawić oferty na 20 dni przez sandboxa.

**Comment by MaciejPotepa** [comment]
Bardzo dziękuję za zgłoszenie problemu. Dam znać jak go rozwiążemy.

**Comment by MaciejPotepa** [comment]
Przywróciliśmy wartość, której brakowało. Jeszcze raz dzięki za zgłoszenie.
