### ISSUE TITLE
Powiązanie konkretnego zamówienia z konkretnymi danymi? REST API #QUESTION

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#1940]
Witam,

Czy istnieje jakiś sposób Allegro API za pomocą którego mógłbym powiązać dane id zamówienia z konkretnym zamówieniem tj. Danymi zamówienia, danymi do faktury(jezeli jest) , danymi do wysyłki itp?
Obecnie mam tabele która przedstawia wszystkie zamówienia, ale i wszystkie dane do wysyłki itp przez co jest to nie etyczne i trudno się odnaleźć.
Myślałem o połączeniu checkoutforms ['id'] z  checkoutforms ['lineItems']['id']  i wtedy pobierać resztę danych zamówienia, ale bez skutku. Proszę o odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
W ostatnim czasie [udostępniliśmy zasób](https://github.com/allegro/allegro-api/issues/1878), dzięki któremu możesz filtrować zamówienia po payment.id. Czy takie rozwiązanie jest dla Ciebie pomocne?

**Comment by allmat** [comment]
Czy na podstawie tego , powiąże id płatności z reszta konkretnych danych z id płatności czyli : 
-FIRSTNAME
-LAST NAME -
ADDRESS , ZIPCODE  itd...

**Comment by PrzemyslawLukanowski** [comment]
Jeśli dla zasobu 
GET order/checkout-forms?payment.id={payment.id}
przekażesz konkretne id płatności, w odpowiedzi dostaniesz powiązane z płatnością zamówienie, w tym dane, które Cię interesują: firstName, lastName, invoice, itd.

**Comment by allmat** [comment]
Potrzebuję informacji w jaki sposób mogę powiązać konkretne id czyli ['checkoutForms']['id'] z wszystkimi danymi z tego id zamówienia tj.
messageToSeller
buyer
payment
status
delivery
method
smart
invoice
lineItems
summary

Czyli jeśli klikne w programie id zamówienia np. ['id'] = b1943-hn3-1fw-14gf4-662ac24 to wyskoczą mi dokładnie wszystkie dane tego zamówienia podane wyżej.

**Comment by PrzemyslawLukanowski** [comment]
Nie wiem, czy dobrze zrozumiałem, ale jeśli za pomocą zasobu
[GET /order/checkout-forms/{checkoutForm_id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET)
odwołasz się do konkretnego checkout-form id, to w odpowiedzi otrzymasz wszystkie dane konkretnego zamówienia, o których wspomniałeś. Zajrzyj do [naszego poradnika](https://developer.allegro.pl/orders/#04), gdzie ta funkcjonalność jest opisana szerzej.

**Comment by allmat** [comment]
No tak, wystarczy użyć checkoutform ['id'] i mam wszystkie dane z tego id, cudownie przemyślane rozwiązanie, dziękuję za pomoc! Już wiem jak to powiązać z resztą, 
Miłego dnia :)
