### ISSUE TITLE
[REST] Dokumentacja - beta vs public

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#1941]
Cześć,

Mam problem z Waszą dokumentacją. Czym się sugerować przy wyborze beta/public?

Takie sytuacje, brak znacznika [BETA] w tytule, ale już w Response samples jest:
https://developer.allegro.pl/documentation/#operation/getOfferShippingRatesGET
https://developer.allegro.pl/documentation/#operation/getSaleProducts
https://developer.allegro.pl/documentation/#operation/createSaleProduct
https://developer.allegro.pl/documentation/#operation/getSaleProduct

**Comment by PawelTaberski** [comment]
Powinno być zawsze również w nawiasie kwadratowym. Poprawimy ten brak. Dzięki za wylistowanie.

**Comment by imper86** [comment]
Ok, to żebyśmy mieli jasność - metody które wymieniłem są nadal w wersji beta, tak?

**Comment by PawelTaberski** [comment]
Tak, są w wersji beta.
