### ISSUE TITLE
Offers Batch Update

### ISSUE THREAD

**Issue by Peymanpn** [allegro/allegro-api#1942]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hi;

I managed to update offers through single offer update with `sale/offers` 
and `sale/offer-quantity-change-commands/` endpoints

in batch upgrade mode, it supposed to update several items at once, right?
according to the documents,[here](https://developer.allegro.pl/en/my_offers/#3g) I can only set one product quantity per command(to multiple products).
how is it possible to update, for example : 
change product 78872342 quantity to 42 and change product 928575443 to 5?

also when I want to do product update through single offer update, I get error after 2nd or 3rd one, but if I put 1-2 second delay between PUT requests, it will succeed.

can you please point me to the direction on how I can update several items ? for example 400 items?
It doesn't matter if it makes me do 400 requests or more in one go.

here is the json modification request.it has only one `value` section to put quantity value in.
I have also tried to send this json as array, but still no luck.

```json
{
    "modification":{
        "changeType":"FIXED",           -- supported values: “FIXED” (quantity), 
                                        “GAIN” (add/remove items. To remove items, 
                                        provide the value with a minus sign)
        "value":30                      -- value to be changed to (FIXED) 
                                        or by which you want to change the quantity (GAIN)       
            },
    "offerCriteria":[
    {
        "type":"CONTAINS_OFFERS",
        "offers":[                      -- a list of offers you want to edit
        {
        "id":"7660573029"
        },
        {
        "id":"7644576839"
        }
        ]
    }
    ]
}
```

here is the error message i got when trying to use `PUT` several times
```
System.Net.Http.HttpRequestException
  HResult=0x80131620
  Message=An error occurred while sending the request.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Inner Exception 1:
IOException: The server returned an invalid or unrecognized response.
```

and here is my request headers
```
{
  Accept: application/vnd.allegro.public.v1+json
  Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  User-Agent: Allegro-xxxxxx/1.2.125.0
  Content-Type: application/vnd.allegro.public.v1+json
}
```

and this is the previous response header(last time hadn't any response)
```
{
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  x-xss-protection: 1; mode=block
  Server: envoy
  Pragma: no-cache
  X-Frame-Options: DENY
  trace-id: cd1c52eb9c228fbf
  Date: Tue, 09 Jul 2019 23:44:13 GMT
  x-ratelimit-remaining: 8997
  X-Content-Type-Options: nosniff
  x-ratelimit-limit: 9000
  x-envoy-upstream-service-time: 13
  Transfer-Encoding: chunked
  Expires: 0
  Content-Type: application/vnd.allegro.public.v1+json; charset=UTF-8
}
```

**Comment by PrzemyslawLukanowski** [comment]
> “how is it possible to update, for example :
> change product 78872342 quantity to 42 and change product 928575443 to 5?”

It's not possible, you can provide only one “quantity” value to multiple offers.

Can you send response header, when you’re trying to use PUT several times?

**Comment by Peymanpn** [comment]
> > “how is it possible to update, for example :
> > change product 78872342 quantity to 42 and change product 928575443 to 5?”

When I try to `PUT` multiple times, it is fine if I create a 2 seconds delay between each request. otherwise, it won't return anything, not even headers.it throws this error. (it usually happens after 2nd or 3rd request 
Error Message: `IOException: The server returned an invalid or unrecognized response.`

> Can you send trace-id from response header, when you’re trying to use PUT several times?

sorry, it won't provide any response headers.i just wrote it's previous successful request's trace-id above.

> It's not possible, you can provide only one “quantity” value to multiple offers.

Are there any restrictions exists for requests, beside the `x-rate-limit`? If there is not, I am gonna keep trying to make it work, somehow.

Is there any way I can make server to send `Full Content` data instead of `chunked` streams? I suspect that may have something to do with it

**Comment by PrzemyslawLukanowski** [comment]
> When I try to PUT multiple times, it is fine if I create a 2 seconds delay between each request. otherwise, it won't return anything, not even headers.it throws this error. (it usually happens after 2nd or 3rd request
> Error Message: IOException: The server returned an invalid or unrecognized response.

I tried to PUT several times one after another without delay and I did’t get the error above. Does the problem still occurs?

> Are there any restrictions exists for requests, beside the x-rate-limit? If there is not, I am gonna keep trying to make it work, somehow.

In REST API we’ve got the [same restrictions as in WebAPI.](https://allegro.pl/webapi/faq.php#faq_1)

> Is there any way I can make server to send Full Content data instead of chunked streams? I suspect that may have something to do with it

Can you specify your question? You can send full content with PUT /sale/offers/{offerId} resource. More information you can find in [our guide.](https://developer.allegro.pl/sale/#step-8-complete)

**Comment by Peymanpn** [comment]
Thanks for answering;
In documents you said you only accept full contents and not streams, but you're sending back your data as stream
`Transfer-Encoding: chunked`
Iam not sure if that's the problem it may be created by this since iam using asynchronous
BTW, I couldn't fix my code this way and I had to put the delays. Maybe I could fix it when you create this feature to update quantity and prices in batches.
Good luck the entire Allegro team
