### ISSUE TITLE
Jak zaciągnąć dzienne koszty poniesione w ramach prowadzenia sprzedaży?

### ISSUE THREAD

**Issue by Xawier** [allegro/allegro-api#1943]
W jaki sposób można zaciągnąć poprzez API dzienne koszty ponoszne w ramach prowadzenia sprzedaży na allegro? Interesuje mnie sumaryczny koszt:
- Prowizji od sprzedaży
- Prowizji za wystawienie produktu
- Prowizji za promowanie produktu
- Prowizji za reklame Allegro Ads

W oknach dziennych.

**Comment by PawelTaberski** [comment]
Obecnie dane związane z opłatami możesz sprawdzić tylko przez WebAPI. Dostępne są dwa zasoby związane z opłatami i prowizjami:

- doMyBilling - Pobieranie bieżącego salda z konta.
- doMyBillingItem - Sprawdzanie kosztów związanych z ofertą.

Więcej na ten temat znajdziesz w [dokumentacji](https://allegro.pl/webapi/documentation.php/theme/id,66).

**Comment by qshop123** [comment]
Kiedy dane o opłatach będą dostępne przez RESTa?

**Comment by PawelTaberski** [comment]
W III kwartale powinny pojawić się nowe zasoby do:

- Historia operacji bilingowych i saldo
- Sprawdzenie kosztów oferty

Wszystkie planowane nowe zasoby znajdziesz w naszym [harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by pkrzemo** [comment]
@PawelTaberski 


> W III kwartale powinny pojawić się nowe zasoby do:
> 
> * Historia operacji bilingowych i saldo
> * Sprawdzenie kosztów oferty

Czy zostały już dodane?

**Comment by PawelTaberski** [comment]
@pkrzemo Jeszcze nie wszystkie już dodane odznaczamy odpowiednio w [harmonogramie](https://developer.allegro.pl/schedule/).
