### ISSUE TITLE
Nadchodzące opłaty - różnica pomiędzy rest i "moje allegro"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#1945]
Witam,
W "moje allegro" 
https://allegro.pl/moje-allegro/moje-konto/nadchodzace-oplaty
widzę opłatę utrzymaniową zaplanowaną na 09/08/2019 17:47.
Natomiast Rest tej opłaty nie zwraca.
Błąd czy tak ma być?

**Comment by PrzemyslawLukanowski** [comment]
Wyślij nam przez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt) login, do którego przypisana jest ta opłata, dopisz numer zgłoszenia GitHub #1945.

**Comment by kfijalko** [comment]
wysłałem,
moje typy:
1) rest nie pobiera wszystkich opłat jakie istnieją tylko ma sztywne ograniczenie nextDate<=now()+30dni, natomiast mechanizm naliczania ma nextDate<=now()->plusJedenMiesiąc. 
W przypadku miesiąca, który ma 31 dni: rest ma 2019-08-**09** 14:36, mechanizm ma 2019-08-**10** 14:36.
2) rozsynchronizowały się zegarki na serwerach

**Comment by PrzemyslawLukanowski** [comment]
@kfijalko Udało mi się pobrać opłaty utrzymaniowe dla użytkownika, którego przesłałeś w zgłoszeniu, za pomocą zasobu GET /pricing/offer-quotes?offer.id={offerId}. W tym także opłatę, o której wspominasz. Z jakiego zasobu korzystasz? Czy problem w dalszym ciągu występuje?

**Comment by kfijalko** [comment]
występuje i będzie występowała dopóki nie poprawicie. problem nie polega na pobieraniu tylko na różnicy w okresach za jaki opłaty są generowane i za jaki są pobierane przez rest.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, jest dwugodzinna różnica między tym, co przesłałeś za pomocą formularza, a tym, co zwraca REST. Zgłosiłem to do odpowiedniego zespołu.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski, czy problem został rozwiązany?

Przykładowo aukcja nr. 7709912701

Na stronie Allegro, w nadchodzących opłatach widać:
![Screenshot_2019-11-12 Allegro pl - Więcej niż aukcje Najlepsze oferty na największej platformie handlowej ](https://user-images.githubusercontent.com/2742214/68668735-2afa0000-0549-11ea-9933-2641403b445d.png)

Natomiast poprzez API nie:
GET pricing/offer-quotes trace-id:3149bfb6b077010d

```
#container: array:2 [
    "count" => 1
    "quotes" => array:1 [
      0 => Model\OfferQuoteDto {#1256
        #container: array:6 [
          "enabled" => true
          "fee" => Model\Fee {#1257
            #container: array:2 [
              "amount" => "0.00"
              "currency" => "PLN"
            ]
          }
          "name" => "Wystawienie"
          "next_date" => DateTime {#1258
            +"date": "2019-11-20 11:29:45.512000"
            +"timezone_type": 2
            +"timezone": "Z"
          }
          "offer" => Model\OfferId {#1259
            #container: array:1 [
              "id" => "7709912701"
            ]
          }
          "type" => "LISTING"
        ]
      }
    ]
  ]
```

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - API w tym przypadku nie zwraca wszystkich danych. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Dla tego zasobu zwracamy opłaty na kolejne 30 dni. W Twoim przypadku opłata jest zaplanowana na 2019-12-12T22:57:09. W momencie przesłania requestu liczba dni była większa niż 30, aktualnie zasób zwraca wszystkie dane.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski, dziękuję, na chwilę obecną widzę tyle samo nadchodzących opłat w API i na stronie Allegro.
