### ISSUE TITLE
Problem z Podany adres obrazka jest nieprawidłowy

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#1946]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Co jakiś czas pojawiają się problemy  z wystawianiem aukcji przez błędne (niby) obrazki, ale nie wiem kompletnie jaka jest przyczyna.

Przykład zwróconego błędu:
```
{
    'code': 'VALIDATION_ERROR',
    'message': 'Provided image address is incorrect: https://a.allegroimg.com/original/11a289/8b7e73304da2b1c5cf2580ceb0a2.', 
    'details': '',
    'path': '',
    'userMessage': 'Podany adres obrazka jest nieprawidłowy: https://a.allegroimg.com/original/11a289/8b7e73304da2b1c5cf2580ceb0a2.'
}
```
Skoro dostałem już adres na serwerze allegroimg.com zakładam, że po mojej stronie upload przebiegł pomyślnie.

W takim razie jaka jest przyczyna powyższego komunikatu? Po wejściu w link ze zdjęciem dostaje 404. Upload jeszcze raz tego samego zdjęcia, bez żadnych zmian, powoduje nadanie nowego adresu, a komunikat o nieprawidłowym adresie się nie pojawia przy próbie wystawienia aukcji ze zdjęciem...

Informacyjnie: przy uploadzie korzystam z opcji wysyłania zdjęcia, a nie podawania adresu.

**Comment by PrzemyslawLukanowski** [comment]
@Himon-SYNCRAFT Zweryfikuj, czy dla przesłanego obrazka nie minął czas ważności - pole "expiresAt" w response przy uploadzie.
Jeśli nie w tym tkwi przyczyna problemu, prześlij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) obrazek, który chcesz wysłać i Twój login. Dopisz także numer zgłoszenia GitHub #1946.

**Comment by Himon-SYNCRAFT** [comment]
@PrzemyslawLukanowski Jakie wartości przyjmuje parametr "expiresAt"? W sensie ile mamy czasu na wystawienie oferty zanim zostanie skasowany?

Moim zdaniem czas ważności nie mógł minąć, bo mechanizm, który stosuje uploaduje obrazki przy pierwszej próbie wystawienia aukcji, a to jest obrazek do produktu, który miał się dopiero pojawić, dlatego też nie zawracałem sobie głowy parametrem "expiresAt".

Nie macie logów dotyczących obrazków, które by wskazywały po adresie (tj. wyżej np. https://a.allegroimg.com/original/11a289/8b7e73304da2b1c5cf2580ceb0a2) co się zadziało? Mogę wysłać ten obrazek tylko czy ma to sens skoro przy drugiej próbie przeszło bezproblemowo dla tego samego, nie zmienionego w żaden sposób zdjęcia.

**Comment by PrzemyslawLukanowski** [comment]
Grafika zostanie usunięta z serwera po czterech godzinach, jeśli nie wykorzystasz jej w ofercie. Istnieje możliwość, że nie wykorzystałeś go w tym czasie?

**Comment by barthoos** [comment]
Mam bardzo podobny blad. Poki co tylko na sandboxie. Obrazki sa dopiero-co-wrzucone, wiec swiezynka. Rowniez po wejsciu na konkretny link obrazek sie wyswietla prawidlowo. Natomiast proba utworzenia draftu konczy sie kodem http 422 i otrzymuje w odpowiedzi:

`[{"code":"VALIDATION_ERROR","message":"Provided image address is incorrect: https://a.allegroimg.allegrosandbox.pl/original/118ac2/e35374964f9393d41531a34dba55, https://a.allegroimg.allegrosandbox.pl/original/11a8c9/148a18374830b0b7a51fa57320bb, https://a.allegroimg.allegrosandbox.pl/original/117d1c/8fdd0ed84731972f5b80efbc6b03, https://a.allegroimg.allegrosandbox.pl/original/110aa0/a975125f400d991ee05db5364f13, https://a.allegroimg.allegrosandbox.pl/original/116ff2/c8f1fb054e3483a499ce9d2be1ed, https://a.allegroimg.allegrosandbox.pl/original/11a650/58c669af4cd8b4414100da62c7a6, https://a.allegroimg.allegrosandbox.pl/original/119a31/09aa61ab46bfaed5e1218bc03151, https://a.allegroimg.allegrosandbox.pl/original/11acf6/4a105b1047b7b5cc133b0a0dee0d.","details":"","path":"","userMessage":"Podany adres obrazka jest nieprawid\u0142owy: https://a.allegroimg.allegrosandbox.pl/original/118ac2/e35374964f9393d41531a34dba55, https://a.allegroimg.allegrosandbox.pl/original/11a8c9/148a18374830b0b7a51fa57320bb, https://a.allegroimg.allegrosandbox.pl/original/117d1c/8fdd0ed84731972f5b80efbc6b03, https://a.allegroimg.allegrosandbox.pl/original/110aa0/a975125f400d991ee05db5364f13, https://a.allegroimg.allegrosandbox.pl/original/116ff2/c8f1fb054e3483a499ce9d2be1ed, https://a.allegroimg.allegrosandbox.pl/original/11a650/58c669af4cd8b4414100da62c7a6, https://a.allegroimg.allegrosandbox.pl/original/119a31/09aa61ab46bfaed5e1218bc03151, https://a.allegroimg.allegrosandbox.pl/original/11acf6/4a105b1047b7b5cc133b0a0dee0d."}]`

Trace-id: 584f872ac8143008

Jak mowilem chodzi o sandbox. Mialem podejrzenia, ze chodzi o zbyt male rozmiary zdjecia (dluzszy bok nie mial 500px), ale udalo mi sie z takimi zdjeciami poprawnie wystawic aukcje, wiec to raczej nie to.

**Comment by barthoos** [comment]
Przy okazji - dlaczego czesc bledow walidacji jest na poziomie wywolania zapytania restowego (jak powyzej kod http 422), a czesc na poprawnie przeprocesowanym wywolaniu w tablicy validation/errors ? Mocno utrudnia to zarzadzanie bledami walidacji.. Nie mozna tego ujednolicic? Zamiast 422 przekazac draft z bledem w sekcji validation/errors?

**Comment by PrzemyslawLukanowski** [comment]
@barthoos Zweryfikowałem obrazki, które podałeś i API zwraca komunikat, o którym piszesz. Zgłosiłem błąd do odpowiedniego zespołu. 

> Nie mozna tego ujednolicic? Zamiast 422 przekazac draft z bledem w sekcji validation/errors?

Dziękujemy za sugestię, ją również przekazałem do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie, poinformujemy w odpowiednim komunikacie.

**Comment by barthoos** [comment]
OK, z niecierpliwoscia zatem czekam na zwrotne info - naprawde spory % tych aukcji ma taki blad a mnie skonczyly sie juz pomysly, co moze byc jego przyczyna ;)

**Comment by PrzemyslawLukanowski** [comment]
@barthoos Poinformuję Cię, jak tylko dostanę odpowiedź zwrotną.

**Comment by barthoos** [comment]
Witam, wiadomo juz cos?

**Comment by PrzemyslawLukanowski** [comment]
@barthoos Na razie nie, wrócę z odpowiedzią, jak tylko ją otrzymam.

**Comment by deneb-k** [comment]
Czy zamierzacie coś z tym zrobić?

**Comment by PrzemyslawLukanowski** [comment]
@deneb-k Czy możesz podać nam przykładowe trace-id dla operacji POST /sale/images oraz numer oferty, do której próbowałeś załączyć obrazek? Czy jesteś pewien, że nie minął czas ważności określony w polu "expiresAt"?

**Comment by PrzemyslawLukanowski** [comment]
@deneb-k Dziękuję za sugestię. Jeśli zdecydujemy się na wdrożenie takiej funkcjonalności, poinformujemy o tym w odpowiednim komunikacie.

**Comment by deneb-k** [comment]
Dlaczego zmieniliście komunikat błędu? Wcześniej było jak w przykładzie wyżej, czyli "Podany adres obrazka jest nieprawidłowy: https://a.allegroimg.com/original/11a289/8b7e73304da2b1c5cf2580ceb0a2.", więc wiedziałem, który obrazek przesłać jeszcze raz, a teraz jest tylko "Podany adres obrazka jest nieprawidłowy.". Co ta zmiana ma na celu?

I w ogóle zamierzacie ogarnąć ten problem?

**Comment by PrzemyslawLukanowski** [comment]
Usunęliśmy adres url z komunikatu ze względów bezpieczeństwa. Na tę chwilę nie planujemy go tam udostępniać, mamy za to odnotowane na liście sugestii inną formę prezentacji, z którym zdjęciem jest problem.
