### ISSUE TITLE
grant_type=client_credentials not working

### ISSUE THREAD

**Issue by ribickas** [allegro/allegro-api#1947]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

cURL:
`
      $ch = curl_init();

      curl_setopt($ch, CURLOPT_URL, 'https://api.allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials');
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
      curl_setopt($ch, CURLOPT_HEADER, false);
      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
      curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Basic " . base64_encode(self::client_id. ":". self::client_secret),"Accept: application/vnd.allegro.public.v1+json","Content-Type: application/vnd.allegro.public.v1+json"));
      $data = curl_exec($ch);
      $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
      curl_close($ch);
      $res = json_decode($data, true);
`

So we were trying to get application access token, we will use it to get parameters without user's credentials. But nothing works, we tried adding redirect URL, didn't help, code from similar issue: 

`$ch = curl_init (); 

        curl_setopt ($ch, CURLOPT_URL, 'https://api.allegro.pl.allegrosandbox.pl/auth/oauth/token'); 
        curl_setopt ($ch, CURLOPT_POST, TRUE);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_USERNAME, self::client_id);
        curl_setopt($ch, CURLOPT_PASSWORD, self::client_secret);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, array(
        	'client_id' => self::client_id,
        	'client_secret' => self::client_secret,
        	'redirect_uri' => $redirectURL,
        	'grant_type' => 'client_credentials'
        ));
	      $tokenResult = curl_exec($ch);
        var_dump(json_decode($tokenResult))`

And the error is still the same: 
> array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(5) {
      ["code"]=>
      string(17) "NotFoundException"
      ["message"]=>
      string(9) "Not found"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(65) "Function is not available. Contact the author of the application."
    }
  }
}

Thanks for fix or help

**Comment by PawelTaberski** [comment]
Two problems:
1/ wrong address, should be https://allegro.pl.allegrosandbox.pl/auth/oauth/ more about that [here](https://developer.allegro.pl/en/about/#Sandbox).
2/ you shouldn't send headers accept and content-Type

**Comment by ribickas** [comment]
Oh okay thanks, works now. It looked like everywhere is the same adress, missed that one :)
