### ISSUE TITLE
Problem z pobieraniem READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by marpyc** [allegro/allegro-api#1948]
Do wczoraj działał poprawnie poniższy skrypt pobierający dane transakcji z przedziału dat.
W poniższej pętli while w miejscu kropek przetwarzam dane zapisując je do bazy zwiększając wartość offset tak, że offset przy kolejnych przebiegach pętli zwiększa się o 100. Dziś rano przy włączeniu skryptu przy drugim przebiegu pętli curl zwraca błąd 500. Wartość offset w pierwszym zapytaniu, to 0, a w kolejnym (zwracającym już błąd), to 100 (wpisanie na sztywno 100 w pierwszym zapytaniu działa, ale już kolejny przebieg pętli również nie działa). Czy zmieniło się wczoraj coś w kwestii pobierania danych przez Restapi? Jaki może być powód zwrócenia błędu 500?

$offset = 0;
$totalCount = 1;
$lastEvent = new DateTime(self::getLastEvent());
$lastupdate = new DateTime($token['last_update']);
while($offset<$totalCount) {
	$date_lower_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('-7 days'));
	$date_upper_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('now'));
	$curl = curl_init($auth->providerSettings['baseUri'].'order/checkout-forms?status=READY_FOR_PROCESSING&limit=100&offset='.$offset.'&lineItems.boughtAt.lte='.$date_upper_range.'&lineItems.boughtAt.gte='.$date_lower_range);
	$headers[] = 'Authorization: Bearer '.$token['access_token'];
	$headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
	curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
	$result = ($result = curl_exec($curl)) === false ? false : json_decode($result);
...
}

**Comment by PawelTaberski** [comment]
Upewnij się proszę, czy za pierwszym i drugim razem przesyłasz dokładnie taki sam token, czy nic do niego w locie nie dodajesz.

**Comment by PawelTaberski** [comment]
Udało się zdiagnozować problem, w requeście wysyłasz kilkakrotnie nagłówek Authorization wraz z wartością, co powoduje ostatecznie błąd. Przesyłaj ten nagłówek tylko raz.

**Comment by marpyc** [comment]
To niestety nie to, bo token pobierany jest raz z bazy i na pewno się nie zmienia (dla pewności przypisuję go teraz do zmiennej przed pętlą). Uprościłem pętlę while do absolutnego minimum i problem nadal występuje. Pierwszy przebieg pętli zwraca totalCount równy ponad 750 transakcji, ale do celów testowych ustawiłem jego wartość w pętli na 600. Poniższy kod nie działa:

$offset = 0;
$totalCount = 1;
$moj_token = $token['access_token'];
if($lastEvent>$lastupdate || 1==1) {
	$db->prepare('UPDATE data SET last_update = NOW();')->execute();
	while($offset<$totalCount) {
		echo $offset."<br/>";
		$date_lower_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('-7 days'));
		$date_upper_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('now'));
		$curl = curl_init($auth->providerSettings['baseUri'].'order/checkout-forms?status=READY_FOR_PROCESSING&limit=100&offset='.$offset.'&lineItems.boughtAt.lte='.$date_upper_range.'&lineItems.boughtAt.gte='.$date_lower_range);
		$headers[] = 'Authorization: Bearer '.$moj_token;
		$headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
		curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
		$result = ($result = curl_exec($curl)) === false ? false : json_decode($result);
		echo curl_getinfo($curl, CURLINFO_HTTP_CODE) . ' <- status<br/>';
		//curl_close($curl); // nie byłem pewien, czy to nie powoduje problemu, ale niezależnie od tego, czy ta linijka jest, czy też nie, problem występuje
		$offset=$offset+100;
		$totalCount=600;
	 }
}

Powyższy kod zwraca odpowiednio:
0
200 <- status
100
500 <- status
200
500 <- status
300
500 <- status
400
500 <- status
500
500 <- status

**Comment by marpyc** [comment]
Wysłałem post przed przeczytaniem drugiej odpowiedzi. Czy mógłbym prosić o podpowiedź która linijka powoduje kilkukrotne wysłanie nagłówka Authorization?
