### ISSUE TITLE
REST API C#

### ISSUE THREAD

**Issue by kamelTrop** [allegro/allegro-api#1949]
Czy może ktos podrzucić przykładowy kod działania pobrania tokena w c# bo ja próbuje na różne sposoby i za kazdym razem wywala brak autoryzacji.

**Comment by mbednarski** [comment]
Który token masz dokładnie na myśli?

**Comment by pkrzemo** [comment]
pokaż fragmenty kodu którymi próbujesz to zrobić.

**Comment by kamelTrop** [comment]
Próbuje pobrać ten pierwszy aby móc później pobierac listę aukcji, a to przykładowe kody i zadnym nie moge uzyskac dostepu. 

            string url = "https://allegro.pl/auth/oauth/device";
            string client_id = "moj id klienta";
            string client_secret = "moj klucz";
            string idks = client_id + ":" + client_secret;
            byte[] bajty = Encoding.UTF8.GetBytes(idks);
            string authString = "Basic " + Convert.ToBase64String(bajty);



            //1.
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://allegro.pl");
            var request = new HttpRequestMessage(HttpMethod.Post, "/auth/oauth/device");
            var keyValues = new List<KeyValuePair<string, string>>();
            keyValues.Add(new KeyValuePair<string, string>("client_id", client_id));
            keyValues.Add(new KeyValuePair<string, string>("Content-Type", "application/x-www-form-urlencoded"));
            keyValues.Add(new KeyValuePair<string, string>("Authorization", authString));
            request.Content = new FormUrlEncodedContent(keyValues);
            var response = await client.SendAsync(request);



            //2.
            var restclient = new RestClient(url);
            RestRequest request2 = new RestRequest("request/oauth") { Method = Method.POST };
            request2.AddHeader("Authorization", authString);
            request2.AddHeader("Content-Type", "application/x-www-form-urlencoded");
            request2.AddParameter("client_id", client_id);
            var tResponse = restclient.Execute(request2);


            //3.
            WebRequest myReq = WebRequest.Create(url);
            CredentialCache mycache = new CredentialCache();
            myReq.Headers["Authorization"] = authString;
            myReq.Headers["client_id"] = client_id;
            myReq.ContentType = "application/x-www-form-urlencoded";
            myReq.Method = "POST";
            WebResponse wr = myReq.GetResponse();


            //4.
            var httpWebRequest = (HttpWebRequest)WebRequest.Create("https://allegro.pl/auth/oauth/device");
            httpWebRequest.ContentType = "application/x-www-form-urlencoded";
            httpWebRequest.Method = "POST";
            httpWebRequest.Headers.Add("Authorization", authString);
            httpWebRequest.Headers.Add("client_id", client_id);
            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();

**Comment by pkrzemo** [comment]
Odniosę się w miarę możliwości do pkt 1.
Piszę trochę "z pamięci" więc mogą być lekkie błedy:


           var url = new Uri("https://allegro.pl/auth/oauth/device");
           client.DefaultRequestHeaders.Clear();
           client.DefaultRequestHeaders.Add("Authorization", authString );
           client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("pl-PL"));

           var content = new StringContent("client_id=" + client_id, Encoding.UTF8, "application/x-www-form-urlencoded");

            HttpResponseMessage odp = await client.PostAsync(url, content);
 
W odpowiedzi dostaniesz dane do autoryzacji w tym  url dla klienta aby zautoryzował aplikację.
Klient (sprzedawca) powinien wejść w tą stronę, wpisać hasło itp i potwierdzić autoryzację.

W międzyczasie ty (tzn. twoja aplikacja) powinieneś odpytywać (ale nie częściej niż podany w odpowiedzi interwał czasowy) zasób:
 "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=" + otrzymane_device_code;
wywołanie się powiedzie jeśli klient zautoryzuje aplikację. Wtedy otrzymasz token i refresh_token
Znajdź opis w dokumentacji allegro dla DEVICE_FLOW (bo widzę że z tego chcesz skorzystać) 
HTH

**Comment by Gerston** [comment]
w tym wątku podałem przykładowy kod do autoryzacji Device Flow, który działa:
https://github.com/allegro/allegro-api/issues/935

**Comment by kamelTrop** [comment]
No to teraz już nie wiem o co chodzi, zrobiłem tak jak pisaliscie, dostaje StatusCode:200 ale nic więcej. Ehhh rece opadają jak sie marnuje tyle czasu na takie pierdoły co powinny działać bez problemu.


     private void Form1_Load(object sender, EventArgs e)
        {
            const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
            const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;
            ServicePointManager.SecurityProtocol = Tls12;


            string url = "https://allegro.pl/auth/oauth/device";
            string client_id = "26a5ceb86255402d.....";
            string client_secret = "2Cp8HlcLAMwNLCIl..........";

            AuthenticationHeaderValue authString = ToAuthHeaderValue(client_id, client_secret);
            var response = GetResponse(authString, client_id);
           
        }

        public static AuthenticationHeaderValue ToAuthHeaderValue(string clientid, string secred)
        {
            return new AuthenticationHeaderValue("Basic", Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes($"{clientid}:{secred}")));
        }

        public static async Task<Object> GetResponse(AuthenticationHeaderValue authString, string clientid)
        {
            using (var client = new HttpClient())
            {
                var url = new Uri("https://allegro.pl/auth/oauth/device");
                client.DefaultRequestHeaders.Clear();
                client.BaseAddress = url;
                client.DefaultRequestHeaders.Authorization = authString;
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("pl-PL"));
                HttpContent context = new StringContent("client_id=" + clientid, Encoding.UTF8, "application/x-www-form-urlencoded");
                var data = await client.PostAsync(url, context);
                return data;
            }
        }

**Comment by Gerston** [comment]
Masz błąd, powinieneś to zrobić w asynchronicznej metodzie i dodać słowo kluczowe "await" przed GetResponse, czyli:
var response =await  GetResponse(authString, client_id);
