### ISSUE TITLE
sale/images - Location vs location

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1952]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry
Dzień bez jaj dniem straconym. Mam pytanie, jest sobie taki endpoint https://upload.allegro.pl/sale/images 

Wysyłamy mu pliki albo linki i zwraca URL do pliku na waszym serwerze. Zgodnie z dokumentacją techniczną dane przychodzą w obiekcie "location"

Od dzisiaj rana przychodzą jednak w obiekcie "Location"

Pytanie : Czy zmieniacie dokumentację aby było "Location" czy poprawiacie endpoint aby zwracał "location" tak jak w dokumentacji.

To co robicie to JEST SŁABE.
Serio.....

**Comment by Gerston** [comment]
Ja już w kilku obiektach zauważyłem, że np "bool" jest "null", lub "int" też jest "null" hihihihihi

**Comment by qshop123** [comment]
Myślisz Gerston że w API maczają klawiaturę programiści z Ukrainy?

**Comment by Gerston** [comment]
Nie wiem, ale wiem,, że pośpiech jest nie wskazany, bo później wychodzą takie "perełki" :)

**Comment by pkrzemo** [comment]
Myślę że nie mają żadnego oprogramowania do sprawdzenia jakości kodu. Nie mają też architekta systemu, bo wszystko wygląda jakby poszczególne zasoby projektowali różni ludzie (albo jeden  ale z problemami z pamięcią).
;-)

**Comment by PrzemyslawLukanowski** [comment]
W body zwracamy od początku “location” - nie przychodzi to w obiekcie, ale w polu. “Location” zwracane jest w nagłówku odpowiedzi, gdzie i tak nie ma różnicy między “location” a “Location”, ponieważ są case insensitive.

**Comment by qshop123** [comment]
No właśnie się nie zgadzam. Ponieważ czytam od początku z nagłówka i było "location" a teraz jest "Location"

**Comment by qshop123** [comment]
pkrzemo : No bo to piszą różni programiści. Oni nie trzymają się własnych wytycznych co do nazw encji ....tak to wygląda. I tak jest o niebo lepiej niż przy SOAP.

**Comment by PrzemyslawLukanowski** [comment]
@qshop123  To i tak nie ma znaczenia, ponieważ - tak jak wspomniałem - nagłówki odpowiedzi są case insensitive.

**Comment by pkrzemo** [comment]
> @qshop123 To i tak nie ma znaczenia, ponieważ - tak jak wspomniałem - nagłówki odpowiedzi są case insensitive.
@PrzemyslawLukanowski Jedne języki programowania są case sensitive inne case insensitive. Jeśli program automatycznie tworzy obiekty na podstawie odpowiedzi, i jest napisany w języku dla którego ma to znaczenie, to wszelkie zmiany wielkości liter mają wpływ na działanie programu. Nie powinno być tak, że sobie je zmieniacie BEZ ZAPOWIEDZI !
Wszelka obrona tego co się stało jest daremna, bo piszemy o ponoć "stabilnej" w dodatku "public" funkcjonalności na serwerze PRODUKCYJNYM.
Powinniście teraz przeanalizować dlaczego tak się dzieje i zabezpieczyć się aby tak w przyszłości już nie było. ;-)

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Po naszej stronie nic się nie zmieniało w związku ze zwracaniem nagłówka Location w /sale/images. Poleganie na wielkości liter w nagłówkach nie jest dobrą praktyką, niezależnie od języka, ponieważ ich zachowanie jest różne w zależności od użytego protokołu (HTTP1.1 vs. HTTP2).

Poniżej przykład w HTTP2:
```
curl --http2 -i 
-H 'Accept: application/vnd.allegro.public.v1+json' 
-H 'Content-Type: application/vnd.allegro.public.v1+json' 
-H "Authorization: Bearer $USER_TOKEN" 
-XPOST https://upload.allegro.pl/sale/images 
-d '{"url":"https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg"}'
HTTP/2 201
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
location: https://a.allegroimg.com/original/1136f6/fa6eec294ea2b045fb67ab1c5527
trace-id: 58feebe52ee75451
date: Fri, 12 Jul 2019 12:13:30 GMT
x-ratelimit-remaining: 8998
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
x-ratelimit-limit: 9000

{"expiresAt":"2019-07-12T18:13:30.551476Z","location":"https://a.allegroimg.com/original/1136f6/fa6eec294ea2b045fb67ab1c5527"}
```

Poniżej przykład w HTTP1.1:

```
curl --http1.1 -i 
-H 'Accept: application/vnd.allegro.public.v1+json' 
-H 'Content-Type: application/vnd.allegro.public.v1+json' 
-H "Authorization: Bearer $USER_TOKEN" 
-XPOST https://upload.allegro.pl/sale/images 
-d '{"url":"https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg"}'
HTTP/1.1 201 Created
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Location: https://a.allegroimg.com/original/1134bc/97ee1cca460cac2b2e22cb227ba0
Trace-Id: 799a137ed747469f
Date: Fri, 12 Jul 2019 12:13:24 GMT
X-RateLimit-Remaining: 8999
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
X-RateLimit-Limit: 9000

{"expiresAt":"2019-07-12T18:13:24.049373Z","location":"https://a.allegroimg.com/original/1134bc/97ee1cca460cac2b2e22cb227ba0"}
```

Czy na pewno sprawdzałeś te nagłówki na tych samych maszynach/wersjach języka/ustawieniach systemowych? Może zmieniły się jakieś ustawienia Twojego systemu i wcześniej używałeś HTTP2 a teraz HTTP1.1?
