### ISSUE TITLE
doLoginWithAccessToken - jak uzystać accesstoken?

### ISSUE THREAD

**Issue by GosiaJK** [allegro/allegro-api#1953]
Pytanie jak w temacie. Czy mogę na przykład uzyskać accesstoken logując się poprzez przeglądarkę? Czy jest jakiś inny łatwy sposób pozyskania accesstoken'a?

Dajcie żyć zwykłym użytkownikom własnych aplikacji, którzy są jednocześnie posiadają swoje jedno jedyne konto na allegro!

A może jednak zdecydujecie się uprościć model logowania do takiego, jaki jest w WebApi?

Pozdrawiam
Gosia

**Comment by Gerston** [comment]
Mogę napisać Ci plugin pod Access, tylko napisz o co Ci dokładnie chodzi, jakiego typu autoryzację?
Czy wystarczy jeden typ np. Device Flow, czy z redirectUrl? w jakiej postaci chciałabyś mieć ten token, bo raczej nie w postaci obiektu, rozumiem, że raczej w postaci stringu?

**Comment by GosiaJK** [comment]
Dziękuję za informację. Podejrzewam, że msaccess też by to potrafił, ale jak widzę nie ma na to mocnych. Chodzi mi móc edytować swoje dane przez msaccess. Czyli chyba raczej device flow wystarczy. Jak dotąd udało mi się obsłużyć "pojedynczą" autoryzację i korzystam z dostępu do danych ogólnych. Po prostu nie wiem jak przechwycić odpowiedź logując się poprzez przeglądarkę, albo wyskakujące okno w windows? access? przy wysyłaniu pierwszego kroku autoryzacji.

**Comment by Gerston** [comment]
Przy Device Flow nie musisz przechwytywać informacji z przeglądarki musisz w pętli odpytywać serwer o token metodą Post :)

**Comment by GosiaJK** [comment]
Czyli jak wyślę pierwszą autoryzację (device flow) z aplikacji, a następnie zaloguję się na swoje konto allegro w przeglądarce, to wtedy mogę odpytać serwer o token?

**Comment by Gerston** [comment]
Nie, jak wyślesz "1 autoryzację", to w odpowiedzi otrzymasz:
1. link, który musisz wkleić w przeglądarkę, a on dalej Ciebie poprowadzi.
2. kod urządzenia, który musisz dodać do odpytania serwera o token.
3. Interwał czasowy, który musisz użyć w pętli w której wysyłasz zapytanie o token.

I tak, o linku nie muszę nic pisać, bo to zrozumiałe.
Metodą POST, która ma pobrać token wysyłasz:
 "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code="+ kod urządzenia + oczywiście wszystko inne co jest potrzebne czyli clientId i secretClient Id, ale zgodnie z podanym interwałem czasowym i robisz to od razu po pierwszym zapytaniu o autoryzację, program sobie odpytuje serwer w zadanym interwale czasowym.
Ty w tym czasie robisz krok po kroku, co dostałaś w linku zwrotnym z pierwszego zapytania. Czyli wklejasz link do przeglądarki i po poprawnej weryfikacji otrzymasz token.

**Comment by Gerston** [comment]
Oczywiście źle się wyraziłem, ClientId i ClientSecret podajesz tak samo jak w przypadku pierwszego zapytania a nie w ciągu "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code="
