### ISSUE TITLE
 /sale/offer-publication-commands/{commandId} zawsze zwraca zero ?

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#1954]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Schemat działania:
Krok 1: 
Request PUT:  https://api.allegro.pl/sale/offers/123456 
Response zwraca status oki, jednak aktywnosć jest INACTIVE,

Krok 2:
PUT https://api.allegro.pl/sale/offer-publication-commands/A8C68679-0C9D-47FB-8DB9-4938A0A0FA23 

Nie zwraca błędów, jednak w opdowiedzni są same zera ?
TaskCount { failed:0, succes: 0, total: 0}

Krok 3: 

GET https://api.allegro.pl/sale/offers/123456 HTTP/1.1
Respons oki jednak publication.status=INACTIVE

Powtorzenie samego kroku 3 lub sekwencji 1,2,3 w krou 3 lub już w pierwszym zwroci status Actve, dlaczego ? Dlaczego też offer-publication-commands zwraca wszedzie zero ?

**Comment by PrzemyslawLukanowski** [comment]
PUT /sale/offer-publication-commands/{commandId} zwracas ame zera, ponieważ od momentu przesłania requesta system nie jest w stanie w tak krótkim czasie zwrócić dokładnej informacji na temat statusu wywołania. Aby sprawdzić, czy udało się aktywować ofertę, wykorzystaj zasób 
[GET sale/offer-quantity-change-commands/{UUID}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) - w odpowiedzi otrzymasz konkretne informacje na temat statusu wywołania.

> Powtorzenie samego kroku 3 lub sekwencji 1,2,3 w krou 3 lub już w pierwszym zwroci status Actve, dlaczego ?

Abyśmy mogli to dokładnie przeanalizować, prześlij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego curla z requestami i responsami wraz z trace-id, które dotyczą poszczególnych kroków. Dopisz także numer zgłoszenia - GitHub #1954.

**Comment by keczerad** [comment]
To może warto w odpowidzi dodać InProgress ?!
TaskCount { failed:0, succes: 0, total: 0, inprogress:1}

**Comment by PrzemyslawLukanowski** [comment]
@keczerad Przekazałem Twoją uwagę do odpowiedniego zespołu. Jeśli zdecydujemy się na jej wdrożenie, poinformujemy o tym w odpowiednim komunikacie.

**Comment by mjag8** [comment]
Przyłączam się do tej prośby. Skoro i tak de facto zawsze zwróci same zera, to informacja o tym, czy chociaż serwer przyjął poprawną ilość do przetworzenia już jest cenna

**Comment by PawelTaberski** [comment]
Serwer nie jest w stanie rozpoznać w momencie wysłania requesta ile zadań zostało przesłanych, także nie będzie w stanie sprawdzić ile jest inprogress. Jeśli otrzymałeś same zera oznacza, to że poprawnie przyjęliśmy to zadanie w innym wypadku otrzymałbyś odpowiedni komunikat błędu.
Aby sprawdzić status zadania skorzystaj z dedykowanych zasobów np. w przypadku publikacji oferty:  
GET /sale/offer-publication-commands/{commandId}/tasks
