### ISSUE TITLE
Offer.Promotion zwraca NULL

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1955]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziwny przypadek, tylko przy jednej aukcji, a przynajmniej tej, która była dzisiaj wystawiona, kiedy pobieram tę aukcję przez RestApi to w Offer.Promotion mam null, natomiast inne aukcje jak na razie są w porządku.
Podaję numer aukcji - 8294395652

**Comment by PrzemyslawLukanowski** [comment]
@Gerston Przetestowałem to i faktycznie zwracana wartość to null. Zgłosiłem to do odpowiedniego zespołu.
