### ISSUE TITLE
Draft oferty / Edycja oferty

### ISSUE THREAD

**Issue by Jushop** [allegro/allegro-api#1958]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Cześć. Problem jest następujący: 
Gdy tworzę drafta lub go edytuje w polu delivery oraz location w odpowiedzi dostaje null'a. 
Dane , które są uzupełniane pobrane były wcześniej z innej oferty która została stworzona "ręcznie" przez stronę. 

trace-id : 90bae72d0ac484d4

> Request:
curl -X POST \
  https://api.allegro.pl.allegrosandbox.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer *****' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 3818' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Cookie: _cmuid=a7d74np4-6qr4-5rdw-nxww-8whcttz2n6yd' \
  -H 'Host: api.allegro.pl.allegrosandbox.pl' \
  -H 'Postman-Token: 0b51d955-a4ca-4a55-ac2a-148ee0feda3a,8f906e19-4c3b-4e72-8fc0-613d1907136a' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'cache-control: no-cache' \
  -d '{
    "name": "Felga ALuminiowa test 2",
    "category": {
        "id": "257711"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "17448",
            "valuesIds": [],
            "values": [
                "9.99"
            ],
            "rangeValue": null
        },
        {
            "id": "128688",
            "valuesIds": [
                "128688_3"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127096",
            "valuesIds": [
                "127096_3"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127098",
            "valuesIds": [
                "127098_5"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "346",
            "valuesIds": [
                "346_10"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "130049",
            "valuesIds": [
                "130049_23"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127097",
            "valuesIds": [
                "127097_69"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127413",
            "valuesIds": [
                "127413_11"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "201149",
            "valuesIds": [
                "201149_150605"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "130527",
            "valuesIds": [
                "130527_9"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>test test testy Opony i felgi</p><ul><li><b>test</b></li><li><b>test 1</b></li><li><b>test2</b></li></ul>"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "images": [],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "8000",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 4,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": null
    },
    "delivery": {
        "shippingRates": null,
        "handlingTime": "PT48H",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "promotion": null,
    "location": {
        "countryCode": "PL",
        "province": "KUJAWSKO_POMORSKIE",
        "city": "bydgoszcz",
        "postCode": "85-863"
    },
    "external": null,
    "attachments": [],
    "contact": null
}'

Response: 
{
    "id": "6206464073",
    "name": "Felga ALuminiowa test 2",
    "category": {
        "id": "257711"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "17448",
            "valuesIds": [],
            "values": [
                "9.99"
            ],
            "rangeValue": null
        },
        {
            "id": "128688",
            "valuesIds": [
                "128688_3"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127096",
            "valuesIds": [
                "127096_3"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127098",
            "valuesIds": [
                "127098_5"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "346",
            "valuesIds": [
                "346_10"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "130049",
            "valuesIds": [
                "130049_23"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127097",
            "valuesIds": [
                "127097_69"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127413",
            "valuesIds": [
                "127413_11"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "201149",
            "valuesIds": [
                "201149_150605"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "130527",
            "valuesIds": [
                "130527_9"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>test test testy Opony i felgi</p><ul><li><b>test</b></li><li><b>test 1</b></li><li><b>test2</b></li></ul>"
                    }
                ]
            }
        ]
    },
    "compatibilityList": {
        "items": null
    },
    "images": [],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "8000",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 4,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": null
    },
    "delivery": null,
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "promotion": null,
    "location": null,
    "external": null,
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "You have to provide shipping rates and offer's location.",
                "details": "",
                "path": "",
                "userMessage": "You have to provide shipping rates and offer's location."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Shipping rates may not be empty.",
                "details": "",
                "path": "",
                "userMessage": "Shipping rates may not be empty."
            }
        ],
        "validatedAt": "2019-07-12T13:14:45.993Z"
    },
    "createdAt": "2019-07-12T13:14:46Z",
    "updatedAt": "2019-07-12T13:14:46.008Z"
}

**Comment by PrzemyslawLukanowski** [comment]
@Jushop Aby prawidłowo przesłać te dane, w drafcie musisz jednocześnie przesłać również informacje o identyfikatorze cennika dostawy i formacie sprzedaży. Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/sale/#step-8-complete).
Ponadto pamiętaj, aby ukryć Bearer token, kiedy wysyłasz do nas przykładowy request.

**Comment by Jushop** [comment]
Dzięki. A dlaczego w takim razie jak stworzyłam ręcznie wcześniej cała ofertę która udało się wystawić i te dane które próbowałam wrzucić do drafta pobrałam właśnie z tamtej oferty? Dlaczego lokalizacja się nie zapisuje tylko wpada null?

**Comment by PrzemyslawLukanowski** [comment]
@Jushop Czy oferta, o której mówisz, została wystawiona przez front czy przez API?
