### ISSUE TITLE
Błąd wystawiania DRAFT w Sandbox

### ISSUE THREAD

**Issue by tomaszwaszak** [allegro/allegro-api#1959]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nie mogę utworzyć draftu oferty. Otrzymuję komunikat
{"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":"/sale/offers","userMessage":null}]}

Kod PHP z CURL : 

$url="https://api.allegro.pl.allegrosandbox.pl/sale/offers";
	$postFields["name"]="Książka testowa";
	$postFields["category"]["id"]="91445";
	$postFields=json_encode($postFields);
	$ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
	"Authorization: Bearer {token}",
    "Accept: application/vnd.allegro.public.v1+json",
	"Content-Type: application/vnd.allegro.public.v1+json"
    ]);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);
    $putDraftResponse = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

Inne zapytania jak np pobranie listy kategorii czy ich parametrów, powyższym kodem działają poprawnie.

**Comment by tomaszwaszak** [comment]
Znalazłem już, iż dana kategoria mimo iż ma flagę leaf-=true to miała productCreationEnabled=false.
Znalazłem inną kategorię - 28047, która ma flagi zarówno leaf=true jak i productCreationEnabled=true.
Jednakże nadal otrzymuję ten sam komunikat błędu.

**Comment by PrzemyslawLukanowski** [comment]
@tomaszwaszak Z jakiego rodzaju autoryzacji korzystasz? Upewnij się, że nie jest to client_credentials, ponieważ nie ma ona kontekstu użytkownika i pozwala na dostęp tylko do publicznych zasobów.

**Comment by tomaszwaszak** [comment]
Faktycznie, korzystałem z client_credentials.
Dlatego teraz podjąłem próbę autoryzacji typu Authorization Code.
Wywołałem link :
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id={kod_mojego_klienta}&redirect_uri={moj_URL_przekierowania}

Pokazała się strona Allegro Sandbox z komunikatem 
"Nie możemy wyświetlić strony
Numer błędu: b24fe169a1c464ae"

Zrzut ekranu :
https://1drv.ms/u/s!AnVKTt0jIRT6gWQFZjbC-7fMTLvu

(Gdy wylogowałem się z Allegro Sandbox i powtórzyłem próbę wywołania mojego skryptu, pojawiło mi się okno do zalogowania w Allegro Sandbox. Po poprawnym zalogowaniu się ponownie ten sam komunikat błędu jak wyżej).

**Comment by tomaszwaszak** [comment]
Już jest w porządku. W ustawieniach aplikacji Allegro Sandbox wpisałem ten sam adres do przekierowań, jakiego chcę używać i już jest teraz wszystko jak należy.

**Comment by tomaszwaszak** [comment]
Dziękuję za pomoc.
