### ISSUE TITLE
GET /pricing/offer-quotes - brak zwracanych danych

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#196]
Witam,

Zauważyłem, że dla części promowanych aukcji nie jest zwracana żadna informacja z ww. metody.

Przykład aukcja 7287404242, odpowiedź wygląda tak:
{"count":0,"quotes":[]}

Jakiś pomysł dlaczego tak się dzieje?

**Comment by AniaMalinowska** [comment]
Zgodnie z [zasobem do sprawdzania daty naliczenia kolejnej opłaty w ofercie](https://developer.allegro.pl/news/2018-02-14-Zasob_do_sprawdzania_daty_oplaty/) - opłaty naliczamy w cyklach 10 dniowych. Wskazana oferta jest wystawiona na 30 dni, ale do końca zostały już tylko 3 dni i nie ma wybranej opcji przedłużenia. Dlatego dla tej oferty zasób ten nie zwróci już opłat.

Dodam, że warto także upewnić się, czy jest się zalogowanym jako sprzedawca, który wystawił tę ofertę.

**Comment by imper86** [comment]
@AniaMalinowska z tego, co ja widzę oferta jest wystawiona do wyczerpania przedmiotów. Skąd więc informacja o 30 dniach?

Sprawdzałem token:
"user_name" => Basic {#40 ▼
      -name: "user_name"
      -value: "14496974"
    }

**Comment by PawelTaberski** [comment]
Metoda nie pokazuje opłat, bo korzystasz z pakietu do wyróżnienia ofert.

**Comment by rtnet-pl** [comment]
@PawelTaberski W tym przypadku (wykorzystanie pakietu) myślę, że logiczne byłoby, gdyby metoda mimo wszystko zwracała datę wygaśnięcia pakietu. A tak się nie dzieje, response jest pusty.
Poniżej przykład.
Czy możemy liczyć na poprawkę?

GET https://allegroapi.io/pricing/offer-quotes?offer.id=5171212537&offer.id=7367312851 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer ey(....)
Api-Key: eyJ(....)
Host: allegroapi.io

HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 386e7a734ccfcc22
Date: Mon, 28 May 2018 10:38:47 GMT
X-RateLimit-Remaining: 8996
X-Content-Type-Options: nosniff
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-Length: 23
X-RateLimit-Limit: 9000

{"count":0,"quotes":[]}

**Comment by PawelTaberski** [comment]
@rtnet-pl Przekazałem Twoją sugestię do odpowiedniego zespołu, jeśli wdrożymy taką zmianę, to poinformujemy o tym.

**Comment by rtnet-pl** [comment]
@PawelTaberski ponawiam
Jak już wspominałem, ta metoda wcześniej działała prawidłowo.

**Comment by PawelTaberski** [comment]
Przekazałem Twoją uwagę do odpowiedniego zespołu, jeśli otrzymam informację, że wdrożymy taką zmianę dam znać.
