### ISSUE TITLE
GET  /sale/offers i Internal Server Error

### ISSUE THREAD

**Issue by tomeatoes** [allegro/allegro-api#1960]
Czy działa obecnie pobieranie ofert sprzedawcy?

na zadany w curl URL: https://api.allegro.pl/sale/offers

dostaję:

Response status code: 401 {"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"","details":"","path":""}]}

oznacza to brak dostępu?

natomiast na:  https://api.allegro.pl/sale/offers/

Response status code: 405 {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/","userMessage":null}]}

niedozwolona metoda?

Proszę o pomoc,

**Comment by tomaszwaszak** [comment]
Też miałem Internal Server Errory, po chwili poczekania i ponownych próbach problem sam zniknął. Co prawa nie przy pobieraniu ofert tylko kategorii ale jednak.

**Comment by PrzemyslawLukanowski** [comment]
@tomeatoes Czy problem wciąż występuje?

**Comment by tomeatoes** [comment]
dziękuję za odp. właśnie potem doczytałem potem, że do pobierania danych tą metodą potrzebny jest "bearer-token-for-user" a ja pobieralem połączeniem "bearer-token-for-application".

Czy jest gdzieś w sieci przykład PHP do takiego połączenia "bearer-token-for-user"?

Tutaj (jak rozumiem):

https://developer.allegro.pl/getting_started/#jak-wykona%c4%87-proste-zapytanie-kt%c3%b3re-pobiera-dane 

jest podane jedynie połączenie "bearer-token-for-application"

**Comment by PrzemyslawLukanowski** [comment]
@tomeatoes W przeszłości pojawił się [podobny wątek](https://github.com/allegro/allegro-api/issues/226), być może wśród odpowiedzi userów znajdziesz pomocne dane.
