### ISSUE TITLE
Jaką metodą pobiorę opis produktu o okreslonym ID?

### ISSUE THREAD

**Issue by tomeatoes** [allegro/allegro-api#1961]
Jak w temacie - proszę o pomoc.

**Comment by PawelTaberski** [comment]
Czy przez produkt masz na myśli ofertę? Jeśli tak to użyj zasobu: GET /sale/offers/{offerId}
Jeśli masz na myśli sam produkt to pełne dane o nim pobierzesz zasobem: GET /sale/products/{product.id}
Więcej na ten temat znajdziesz w naszym poradniku: [Jak powiązać ofertę z produktem](https://developer.allegro.pl/productization/#details)

**Comment by tomeatoes** [comment]
Dziękuję za sugestię. Ogólnie ta kwestia jest potomnym tematem do: 

https://github.com/allegro/allegro-api/issues/1960

Tak jak tam napisałem potrzebuję przykłądu w PHP dla połączenia przez "bearer-token-for-user"

z tego co widzę obie podane przez Ciebie metody

GET /sale/offers/{offerId}
GET /sale/products/{product.id}

tego wymagają.

**Comment by PrzemyslawLukanowski** [comment]
@tomeatoes W przeszłości pojawił się [podobny wątek](https://github.com/allegro/allegro-api/issues/226), być może wśród odpowiedzi userów znajdziesz pomocne dane.

**Comment by tomeatoes** [comment]
OK na razie wykorzystuję metodę  get /offers/listing (potem dołącze opisy).

Jednak mam problem - sprzedawca na Allegro ma 539 ofert, a mi ona zwraca 42. Z czego to może wynikać ?? :(
