### ISSUE TITLE
Sprawdzenie czy dla danej oferty są oferty kupna

### ISSUE THREAD

**Issue by mbednarski** [allegro/allegro-api#1963]
Mam następujące pytanie: czy istnieje sposób aby dla konkretnej oferty sprawdzić czy są jakieś oferty kupna? W webapi robiłem to za pomocą doShowItemInfoExtRequest i itBidCount. Z tego co zrozumiałem, to teraz muszę pobrać eventy za pomocą GET /order/events i samodzielnie sobie odfiltrować. Ewentualnie czy jeżeli wyślę request zakończenia takiej oferty to czy wtedy dostanę błąd?

**Comment by PrzemyslawLukanowski** [comment]
Obecnie sprawdzisz to za pomocą zasobu [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET), Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/orders/#02) W najbliższym czasie udostępnimy nowy zasób - dziennik zdarzeń w ofercie. Dzięki niemu będziesz mógł śledzić zmiany w ofercie oraz sprawdzisz, czy dana oferta już się zakończyła

> Ewentualnie czy jeżeli wyślę request zakończenia takiej oferty to czy wtedy dostanę błąd?

Jaką sytuację masz konkretnie na myśli? Jeżeli zakończysz aktywną ofertę poprzez zasób PUT /sale/offer-publication-commands/{commandId} to nie otrzymasz błędu.

**Comment by mbednarski** [comment]
Czy jest znany przybliżony termin udostępnienia wspomnianego zasobu?

**Comment by PrzemyslawLukanowski** [comment]
Dziennik zdarzeń dla oferty udostępnimy w wersji beta w drugiej połowie lipca. Za jego pomocą sprawdzisz takie informacje jak np. data zakończenia oferty, data wznowienia. Do sprawdzenia, czy w danej ofercie są oferty kupna, skorzystaj z zasobu GET /order/events z np. określonym parametrem “type=BOUGHT”.
