### ISSUE TITLE
zależności w ofercie DRAFT pomiędzy cennikiem / lokalizacją / czasem wysyłki

### ISSUE THREAD

**Issue by collector1871** [allegro/allegro-api#1964]
dzień dobry

zazuważyłem, że aby dodać lokalizację (location) przez PUT /sale/offers/<id> to trzeba najpierw podać ID cennika dostaw (poprawne id w shippingRates) 
Tak samo nie da się uzupełnić czasu wysyłki (np. na 3 dni)  handlingTime ; jeżeli nie będzie wstawionego cennika dostaw

chciałbym potwierdzić:
czy jest zależność pomiędzy ID cennika dostaw (id w shippingRates) a location / handlingTime ?
czy mogę uzupełnić location / handlingTime BEZ uzupełnionego cennika dostaw (NULL) ?
czy żeby uzupełnić location, to muszę równocześnie podać cennika dostaw + handlingTime ?

występuje ścisna zależność w back-end w tych trzech polach : prawda? 
W GUI WEB bezpośrednio jej nie widać

**Comment by PrzemyslawLukanowski** [comment]
Jest zależność pomiędzy tym, o czym wspominasz. Aby zapisać czas wysyłki, musisz uzupełnić cennik dostaw oraz format sprzedaży. Pole “location” nie prześle się prawidłowo, jeśli wcześniej nie przypiszesz do oferty cennika dostaw. Więcej informacji znajdziesz w[ naszym poradniku](https://developer.allegro.pl/sale/#step-8-complete).

**Comment by collector1871** [comment]
ok dziękuję, po prostu chciałem potwierdzić

pozdrawiam
