### ISSUE TITLE
Offer.Promotion zwraca NULL

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#1967]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

RequestUri: 'https://api.allegro.pl/sale/offers/8294395652'
traceId=88452540accd641d

Przy niektórych aukcjach zwracany jest NULL w Promotion.
Nie wiem czy to poprawne zachowanie? Ale skoro występuje w niewielkiej ilości aukcjach to chyba nie?

**Comment by Gerston** [comment]
Zapomniałem, że już sygnalizowałem ten problem, sorry :)

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedź w wątku [#1955](https://github.com/allegro/allegro-api/issues/1955).
