### ISSUE TITLE
INVALID_JSON podczas aktualizacji aukcji

### ISSUE THREAD

**Issue by gskowera** [allegro/allegro-api#1968]
W trakcie aktualizacji aukcji przesyłam taki request (body):

{
    "id": "8298264249",
    "name": "Czapka NIKE Z Daszkiem Bejsbolówka(943091-010)",
    "category": {
        "id": "5553"
    },
    "parameters": [
        {
            "id": "54",
            "valuesIds": [
                "54_13"
            ]
        },
        {
            "id": "451",
            "valuesIds": [
                "451_2"
            ]
        },
        {
            "id": "3766",
            "valuesIds": [
                "3766_2397"
            ]
        },
        {
            "id": "3786",
            "valuesIds": [
                "3786_48"
            ]
        },
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ]
        },
        {
            "id": "15851",
            "valuesIds": [
                "15851_2"
            ]
        },
        {
            "id": "128188",
            "valuesIds": [
                "128188_1"
            ]
        },
        {
            "id": "203637",
            "valuesIds": [
                "203637_8192"
            ]
        },
        {
            "id": "203885",
            "valuesIds": [
                "203885_218329"
            ]
        },
        {
            "id": "215918",
            "values": [
                "943091-010"
            ]
        }
    ],
    "ean": "887225037031",
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/11d2c8/0911713d4486869d5949fd4c5436"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h1>CZAPKA Z DASZKIEM NIKE</h1><p><b>KARTOTEKA PRODUKTU:</b></p><p>Model: <b>943091-010</b></p><p>Kolor: <b>Czerń</b></p><p><b>CECHY PRODUKTU:</b></p><ul> <li>Zaokrąglony daszek</li> <li>Sześciopanelowa konstrukcja</li> <li>Otwory wentylacyjne</li> <li>Regulacja obwodu</li> <li>Logo Nike</li> </ul><p><b>SKŁAD MATERIAŁOWY</b></p><p><b>Materiał główny</b></p><ul><li>Bawełna: 100%</li></ul>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p><b>OPIS PRODUKTU</b></p><p>Przedmiotem sprzedazy jest czarna <b>czapka z daszkiem</b>, pochodząca z kolekcji marki <b>Nike. </b>Czapka posiada<b> zaokrąglony daszek</b>, który zadba o osłonę przed promieniami słonecznymi lub wiatrem. </p> <p>Model składający się z <b>sześciopanelowej konstrukcji</b>, został uszyty z wytrzymałych i solidnych materiałów. Na froncie producent umieścił swój znak rozpoznawczy w postaci charakterystycznej dla marki <b>Nike łyżwy</b>.</p> <p><b>Małe, wyszywane otwory</b>, rozmieszczone w strategicznych miejscach czapki, poprawią <b>cyrkulację powietrza</b>, nawet podczas długich godzin użytkowania. Czapka podsiada <b>regulowane zapięcie</b> z <b>metalową sprzączką</b>, umieszczone z tyłu. Dzięki temu, możesz dopasować jej odwód do swoich potrzeb. <b>Uniwersalna kolorystyka</b> i ograniczona ilość detali spowoduje, że czapka sprawdzi się w każdych warunkach.</p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/116094/61d473dd4fe7938ea432edca7c82"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p><b>ZDJĘCIA SĄ NASZEGO AUTORSTWA I PRZEDSTAWIAJĄ FAKTYCZNY STAN PRODUKTU</b></p><p><b>Kolory przedmiotów mogą się nieznacznie różnić, ze względu na ustawienia komputera/monitora (np. nasycenie kolorów). Fakt ten nie może być podstawą do reklamacji.</b></p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/11415a/4badaefe425c9c5dbdc913c22420"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/112665/f7f2625c4a748f9454c4aade0356"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/11e43f/0184a5cf430681f75e3916c8cbc2"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/119dc1/c07a624d4478a4f806d2ee9eb8dc"
                    }
                ]
            }
        ]
    },
    "images": [
        {
            "url": "https://a.allegroimg.com/original/11d2c8/0911713d4486869d5949fd4c5436"
        },
        {
            "url": "https://a.allegroimg.com/original/11d2c8/0911713d4486869d5949fd4c5436"
        },
        {
            "url": "https://a.allegroimg.com/original/11415a/4badaefe425c9c5dbdc913c22420"
        },
        {
            "url": "https://a.allegroimg.com/original/112665/f7f2625c4a748f9454c4aade0356"
        },
        {
            "url": "https://a.allegroimg.com/original/11e43f/0184a5cf430681f75e3916c8cbc2"
        },
        {
            "url": "https://a.allegroimg.com/original/119dc1/c07a624d4478a4f806d2ee9eb8dc"
        },
        {
            "url": "https://a.allegroimg.com/original/116094/61d473dd4fe7938ea432edca7c82"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "58.98",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": "99",
        "unit": "UNIT"
    },
    "publication": {
        "status": "ACTIVE"
    },
    "delivery": {
        "shippingRates": {
            "id": "8a182d86-988b-4558-8960-6cd62b44c90f"
        },
        "handlingTime": "PT24H"
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "16ebcf75-382d-449a-bb6d-a5ac4101a153"
        },
        "returnPolicy": {
            "id": "238c156d-2fb2-48cc-a7bc-47976f9595c3"
        },
        "warranty": {
            "id": "8ce6d6de-1836-4002-b9ba-3510327f957d"
        }
    },
    "promotion": {
        "emphasized": "1",
        "bold": "0",
        "highlight": "0",
        "departmentPage": "0",
        "emphasizedHighlightBoldPackage": "0"
    },
    "location": {
        "countryCode": "PL",
        "province": "POMORSKIE",
        "city": "Malbork",
        "postCode": "82-200"
    },
    "external": {
        "id": "22883/61"
    },
    "validation": {
        "errors": [
            {
                "code": "x",
                "details": "x",
                "message": "x",
                "path": "x",
                "userMessage": "x"
            }
        ],
        "validatedAt": "2019-07-12T13:35:33.184Z"
    },
    "createdAt": "2019-07-12T13:32:39Z",
    "updatedAt": "2019-07-12T13:35:33.767Z"
}

i otrzymuję:

{
    "errors": [
        {
            "code": "INVALID_JSON",
            "message": "Invalid request.",
            "details": null,
            "path": null,
            "userMessage": "Invalid request."
        }
    ]
}

Sprawdziłem request body pod kątem walidacji JSON i wszystko jest OK.

Gdzie może leżeć błąd?

**Comment by PrzemyslawLukanowski** [comment]
@gskowera Dla promotion przesyłasz “1” lub “0”, podczas gdy powinny być to wartości typu boolean - true lub false. Czyli w Twoim przypadku powinno to wyglądać następująco:

```
"promotion": {
		"emphasized": true,
		"bold": false,
		"highlight": false,
		"departmentPage": false,
		"emphasizedHighlightBoldPackage": false
}
```

**Comment by Gerston** [comment]
w stock pole "available" jest typu integer czyli
 "stock": {
    "available": 99,
    "unit": "UNIT"
  },

**Comment by rafwlaz** [comment]
@PrzemyslawLukanowski pozwolę się podpiąć z identycznym problemem, gdzie póki co wszystko działało prawidłowo tylko nagle przestało.

Generalnie działam tak, że robię sobie draft oferty, zwrotkę, którą od was dostaję modyfikuję i robię PUT i ten PUT zwraca mi error `INVALID_JSON`

Moja prośba i sugestia, że jeśli gdzieś wysyłany jest zły typ danych to fajnie jak by z api przyszła zwrotka "wrong type of parameter XYZ", sprawdzałem jsona na validatorze i jest w 100% prawidłowy.

Poniżej to co wysyłam:

```json
{
	"id": "8307659688",
	"name": "Pier\u015bcionek z diamentem PXD0497 STAVIORI",
	"category": {
		"id": "123450"
	},
	"product": null,
	"parameters": [{
		"id": 11323,
		"valuesIds": ["11323_1"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 226434,
		"valuesIds": ["226434_315782"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 2205,
		"valuesIds": ["2205_16", "2205_1", "2205_2"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 15835,
		"valuesIds": ["15835_2", "15835_1"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 17088,
		"valuesIds": ["17088_8"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 15753,
		"valuesIds": ["15753_16"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 205826,
		"valuesIds": ["205826_225106"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 129129,
		"valuesIds": ["129129_246990"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 128188,
		"valuesIds": ["128188_1"],
		"values": [],
		"rangeValue": null
	}, {
		"id": 202705,
		"valuesIds": [],
		"values": ["1.70"],
		"rangeValue": null
	}, {
		"id": 206646,
		"valuesIds": ["206646_228242"],
		"values": [],
		"rangeValue": null
	}],
	"ean": null,
	"description": {
		"sections": [{
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/1149a7\/48621c214e9082172b7fc34a412a"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/1139b7\/b463384a4d57bf231a4ef593bd36"
			}, {
				"type": "TEXT",
				"content": "<p>Model: <b>PXD0497<\/b><\/p><p>Waga ok. 1,70g<\/p><p>Pier\u015bcionek.<\/p><p>\u017b\u00f3\u0142te, Bia\u0142e Z\u0142oto 0,585.<\/p><p>1 Diament, szlif brylantowy, o masie 0,07 ct., barwa J, czysto\u015b\u0107 I1.<\/p><p>Szeroko\u015b\u0107 4-1 mm.<\/p><p>Wysoko\u015b\u0107 3 mm.<\/p><p>Pier\u015bcionek zar\u0119czynowy<\/p><p>Wszystkie standardowe rozmiary (od 10 do 18) s\u0105 dost\u0119pne.<\/p>"
			}]
		}, {
			"items": [{
				"type": "TEXT",
				"content": "<p>Ka\u017cda sztuka bi\u017cuterii <b>tworzona jest z najwy\u017csz\u0105 precyzj\u0105<\/b> przez wybitnych mistrz\u00f3w w\u0142oskiej sztuki z\u0142otniczej, a diamenty i pozosta\u0142e <b>kamienie osadzane s\u0105 r\u0119cznie<\/b> przy u\u017cyciu mikroskopu (tzw. microsetting), daje to gwarancj\u0119 wyj\u0105tkowej trwa\u0142o\u015bci.<\/p>\n    <p>Zdecydowanie jest to <b>produkt na wiele pokole\u0144<\/b>. Staviori oferuje idealne produkty na niezapomniany prezent! Z pewno\u015bci\u0105 b\u0119dzie mi\u0142o przekaza\u0107 je p\u00f3\u017aniej swojej c\u00f3rce lub wnuczce...<\/p>"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/113b0f\/146b523f4f5581324393f9520075"
			}, {
				"type": "TEXT",
				"content": "<p>Oryginalna bi\u017cuteria marki Staviori to idealny prezent, kt\u00f3ry zawsze trafia do Klienta w unikalnym opakowaniu wraz z certyfikatem jako\u015bci i autentyczno\u015bci kamieni szlachetnych.<\/p>\n<p>Produkt na \u017cywo prezentuje si\u0119 rewelacyjnie! Z pewno\u015bci\u0105 ozdobi ka\u017cd\u0105 kobiet\u0119 ! Idealny na niezapomniany przecudowny prezent na lata!<\/p>\n<p><b>Do ka\u017cdego opakowania klient otrzymuje specjaln\u0105 prezentow\u0105 wst\u0105\u017ck\u0119 w wybranym przez siebie kolorze.<\/b><\/p>\n<p>Prosimy poda\u0107 kolor w komentarzu do zam\u00f3wienia.<\/p>"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11557e\/101b3e344b4eb53f2c2f75e7a5a2"
			}]
		}, {
			"items": [{
				"type": "TEXT",
				"content": "<p>Zapewniamy <b>szybk\u0105 realizacj\u0119 i opiek\u0119 nad wysy\u0142anym produktem od pierwszych chwil zam\u00f3wienia.<\/b><\/p> \n    <p>Wszystkie paczki s\u0105 starannie zapakowane i ubezpieczone. Wysy\u0142k\u0119 zawsze potwierdzamy mailem z numerem nadania.<\/p>\n    <p>Je\u015bli sobie \u017cyczysz - bez problemu zapakujemy produkt <b>na prezent<\/b> i wy\u015blemy bezpo\u015brednio do osoby obdarowywanej.<\/p>\n    <p>W\u00f3wczas dow\u00f3d zakupu otrzymasz mailowo.<\/p>\n    <p>Przesy\u0142ki mi\u0119dzynarodowe wysy\u0142amy firm\u0105 GLS.<\/p>\n    <p>Diamenty wybieramy starannie - zwykle stosujemy diamenty o najlepszym stosunku jako\u015bci do ceny czyli barwa <b>G<\/b>, czysto\u015b\u0107 <b>Si1<\/b>.<\/p>\n    <p>Wszystkie u\u017cywane przez nas kamienie szlachetne <b>po\u015bwiadczone s\u0105 certyfikatem<\/b> oraz gwarantujemy, i\u017c <b>nie pochodz\u0105 z kraj\u00f3w obj\u0119tych konfliktem<\/b>.<\/p>"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11513a\/3c85ff5c4df4908ac22b4e7e19cf"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11bfb1\/68da76944e55b047fd51311c77a1"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11d818\/c4abf1b84eb6ae97403f75ef1625"
			}]
		}, {
			"items": [{
				"type": "IMAGE",
				"url": "https:\/\/a.allegroimg.com\/original\/11e5be\/01ac84d641f6951d6a06198a62df"
			}]
		}]
	},
	"compatibilityList": {
		"items": null
	},
	"images": [{
		"url": "https:\/\/a.allegroimg.com\/original\/1139b7\/b463384a4d57bf231a4ef593bd36"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/1149a7\/48621c214e9082172b7fc34a412a"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/113b0f\/146b523f4f5581324393f9520075"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/11557e\/101b3e344b4eb53f2c2f75e7a5a2"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/11513a\/3c85ff5c4df4908ac22b4e7e19cf"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/11bfb1\/68da76944e55b047fd51311c77a1"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/11d818\/c4abf1b84eb6ae97403f75ef1625"
	}, {
		"url": "https:\/\/a.allegroimg.com\/original\/11e5be\/01ac84d641f6951d6a06198a62df"
	}],
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "1660.00",
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 1,
		"unit": "UNIT"
	},
	"publication": {
		"duration": null,
		"status": "INACTIVE"
	},
	"delivery": {
		"shippingRates": {
			"id": "a61b4d17-05d5-4e79-98ec-bd6bbbe7a817"
		},
		"handlingTime": "PT24H",
		"additionalInfo": "Produkt mo\u017cna odebra\u0107 osobi\u015bcie w Poznaniu tylko po wcze\u015bniejszym um\u00f3wieniu."
	},
	"payments": {
		"invoice": "VAT"
	},
	"afterSalesServices": {
		"impliedWarranty": {
			"id": "017ad124-d249-4bca-b900-38bd2bbc637b"
		},
		"returnPolicy": {
			"id": "e52f6f71-911f-4084-aab6-eb369107096b"
		},
		"warranty": {
			"id": "e662b559-3a9a-43b5-ac2b-20f9e6efdb09"
		}
	},
	"additionalServices": {
		"id": "cf7f1d1a-4425-46ab-a799-516a691885b2"
	},
	"sizeTable": "5f927a12-8438-11e8-a7c3-246e9680bf28",
	"promotion": null,
	"location": {
		"countryCode": "PL",
		"province": "WIELKOPOLSKIE",
		"city": "Pozna\u0144",
		"postCode": "60-321"
	},
	"external": {
		"id": "497 39236"
	},
	"attachments": [],
	"contact": null,
	"validation": {
		"errors": [],
		"validatedAt": "2019-07-15T20:42:00.441Z"
	},
	"createdAt": "2019-07-15T20:42:00Z",
	"updatedAt": "2019-07-15T20:42:00.442Z"
}
```

**Comment by PrzemyslawLukanowski** [comment]
@rafwlaz Masz nieprawidłową składnię dla pola “sizeTable”, powinno być:

```
"sizeTable”: {
	“id”: "{sizeTableId}"
}
```
