### ISSUE TITLE
Pasuje do w motoryzacji - problem z bazą TecDoc

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#1969]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Baza TecDoc w zależności od wersji posiada różne id dla poszczególnych pojazdów. Brak możliwości zmapowania id z TecDoc'a z tym z bazy Allegro.

Więcej info: https://github.com/allegro/allegro-api/issues/1874#issuecomment-511426711
#1874

**Comment by TomekKaczmarek** [comment]
@dlis2010 rozumiem, że nawiązujesz do Twojego komentarza z [tego wątku](https://github.com/allegro/allegro-api/issues/1874#issuecomment-511426711) - konsultuję temat. Odpowiedm w wątku [#1874](https://github.com/allegro/allegro-api/issues/1874#issuecomment-511426711).
