### ISSUE TITLE
SOAP-ENV Error

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#197]
Przy wywołaniu doGetMySellItems otrzymujemy komunikat SOAP-ERROR: Encoding: object has no 'itemTitle' property", 

nie wysyłamy nigdze tego parametru, czyżby jakiś problem po stronie Allegro ? 

wysyłamy w requescie 3 rzeczy 
sessionId,page num oraz per page 

W czym moze byc problem jako ze do wczoraj wszystko dzialalo ?

**Comment by yncki** [comment]
[Ticket#1247658665]

**Comment by AniaMalinowska** [comment]
Sprawdziłam metodę z wykorzystaniem Twojego request, i dane zwracane są prawidłowo.  Spróbuj ponownie wysłać zapytanie i daj znać, jeśli problem nadal występuje.

**Comment by yncki** [comment]
Nadal występuje, co ciekawe mamy wiele kont klientów i tylko na tym jednym jest taki problem. 

SOAP-ENV:Server
SOAP-ERROR: Encoding: object has no 'itemTitle' property",

**Comment by AniaMalinowska** [comment]
Dziękuję za info zwrotne, weryfikujemy ten problem.

**Comment by yncki** [comment]
@AniaMalinowska Czy coś już wiadomo ?

**Comment by AniaMalinowska** [comment]
@yncki Wysłaliśmy do Ciebie wiadomość w Ticket#1247658665. Prosimy o sprawdzenie opisanej tam kwestii.
