### ISSUE TITLE
c# Image binary upload

### ISSUE THREAD

**Issue by urbiasz911** [allegro/allegro-api#1970]
Witam,
mam problem z dodaniem zdjęcia w postaci binarnej.
Aplikacja pisana w C# przy pomocy RestSharp wygląda tak :
```

RestRequest v_request = new RestRequest();
v_request.AddHeader("Authorization", "Bearer " + v_token);
v_request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
v_request.AddHeader("Content-Type", "image/jpeg");
v_request.AddHeader("Accept-Language", "pl-PL");
v_request.Timeout = 100000;
v_request.Method = Method.POST;
v_request.AddFileBytes("--data-binary", getPhotoByte("d:\test.jpg"), "test.jpg", "image/jpeg");

var client = new RestClient("https://upload.allegro.pl/sale/images");
IRestResponse response = client.Execute(request);
var content = response.Content;
```

i w odpowiedzi dostaję komunikat:
{"errors":[{"code":"415 UNSUPPORTED_MEDIA_TYPE","message":"415 Unsupported Media Type","details":null,"path":null,"userMessage":"Niedozwolony typ zdjęcia."}]}

Czy ktoś może mi powiedzieć co jest nie tak ?

**Comment by PrzemyslawLukanowski** [comment]
Z racji dużej ilości języków programowania, nie jesteśmy w stanie prowadzić wsparcia dla każdego z nich. Być może ktoś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc. Możesz także przesłać pełnego curla z requestem przez nasz f[ormularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #1970, sprawdzimy wtedy gdzie może być źródło błędu.

**Comment by pkrzemo** [comment]
Osobiście nie używam tego, ale Pan Google twierdzi że inni też mają taki problem z tą biblioteką ...
https://stackoverflow.com/questions/54913629/restrequest-addfilebytes-posting-corrupted-files

**v_request.AddParameter(contentType, bytes, ParameterType.RequestBody);**

Warto spróbować ;-)

**Comment by urbiasz911** [comment]
Wielkie dzięki!
Dokładnie to rozwiązanie pomogło. Nie sądziłem, że ta biblioteka ma taki problem.
