### ISSUE TITLE
Response: HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#1973]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Od czasu do czasu przy synchronizacji ofert (automat leci po ofertach i updejtuje aukcje) dostaję response HTTP 429.

To jest zbyt dużo zapytań na sesję (jak tak to jaki jest limit?), czy za dużo zapytań w określonym czasie (jeśli tak to jaki jest limit?)? 

Pytam, ponieważ to jest nie do zreprodukowania;), więc nie bardzo jest jak przygotować na to jakąś recovery akcję.

**Comment by Patryk27** [comment]
https://developer.allegro.pl/about/, sekcja `Ograniczenie liczby zapytań (limity)`

**Comment by PiotrLaszczyk** [comment]
Dzięki Patryk27... faktycznie jest.

No to teraz idąc dalej problem jest inny. Ponieważ ten job w którym poleciał 429 nie generuje samodzielnie takiego obciążenia. Natomiast jobów jest n, każdy obsługuje inny sklepik (inny user id) i lecą jednocześnie na serwerze heroku. Wygląda tak jakby po stronie Allegro ten ruch był widziany jako wspólny (jedno IP???).  

A jak będziemy chcieli postawić 10*n_obecnych jobów to nam system siądzie ;)

**Comment by rtnet-pl** [comment]
W nagłówku każdej odpowiedzi z Allegro jest pole X-RateLimit-Remaining (to jest limit per client) także możesz sprawdzić czy wysycasz limit clienta czy IP.
Limit IP jest raczej trudno wysycić nawet jak masz dobre łącze.
ps. Client ID  = ID aplikacji

**Comment by PiotrLaszczyk** [comment]
Nigdy dotąd mi się to nie zdarzało więc nawet nie miałem świadomości takich ograniczeń. Dzięki!
