### ISSUE TITLE
Status zamowienia "Nowe" oraz "Wysłane"

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#1974]
Nowy interfejs na Allegro.pl prezentuje od niedawna liste rozwijana przy zamówienia z napisem "Nowe", "Wysłane".
Czy API obsługuje już tego typu statusy? jaką mają ścieżkę w checkoutForms?

**Comment by martacronic** [comment]
Jak było samo "Oznacz jako wysłane" to nie obsługiwało. Teraz też jestem ciekawa czy coś się w tym temacie zmienia. Chciałam jeszcze podpytać czy zmiana statusu na "Wysłane" sprawia, że Allegro wysyła jakiś automatyczny mail do kupującego, bo do tej pory szła informacja dopiero po dodaniu do zamówienia numeru przesyłki?

**Comment by PrzemyslawLukanowski** [comment]
@allmat - aktualnie REST API nie ma zasobu, który zwraca ten status. Sugestia została już przekazana do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie takiej funkcjonalności, poinformujemy o tym w odpowiednim komunikacie. Dodam tylko, że ten status służy tylko do filtrowania zamówień na froncie, nie ma innego zastosowania.
@martacronic - w takim przypadku mail nie jest wysyłany.

**Comment by allmat** [comment]
@PrzemyslawLukanowski - Dziękuję za odpowiedź. W takim razie , obecnie istnieje jakiś status dzięki któremu mógłbym filtrować zamówienia które zostały już wysłane i przenosić je sobie np. do zakładki Archiwum w programie? Z tego co widziałem mamy w API statusy tylko "READY_FOR_PROCESSING" oraz "FILLED_IN" którę niewiele znaczą.

**Comment by PrzemyslawLukanowski** [comment]
@allmat Na tę chwilę nie ma takiego zasobu. Tak jak wspomniałem - sugestia została już przekazana do odpowiedniego zespołu. 

> Z tego co widziałem mamy w API statusy tylko "READY_FOR_PROCESSING" oraz "FILLED_IN" którę niewiele znaczą.

Zajrzyj do naszego poradnika - [jak obsługiwać zamówienia](https://developer.allegro.pl/orders/#02). Znajdziesz tam m.in. informacje na temat tych statusów oraz być może w jakiś sposób pomoże on Tobie w zarządzaniu zamówieniami.
