### ISSUE TITLE
Offer Details vs CommandId result

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1975]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

ab1bf5b4-cbca-4631-8c34-4562da257837

Wykonujac zapytanie o szczegoly oferty 
https://api.allegro.pl/sale/offers/{offerId}

Dostajemy w validation : 
![image](https://user-images.githubusercontent.com/1530496/61292399-666e0300-a7d1-11e9-9ed4-7707931dbc8a.png)

Proszę zwrócić na datę walidacji - nie powinna być bieżąca ? 

WALIDACJA ZWRACA 0 BŁĘDÓW

natomiast commandId zmiany stanu stocku juz mowi ze jednak z walidacja jest problem 
![image](https://user-images.githubusercontent.com/1530496/61292457-83a2d180-a7d1-11e9-8dc8-c9ba39e4fe35.png)

W jaki sposób wymusić walidację ?

**Comment by PrzemyslawLukanowski** [comment]
> “Proszę zwrócić na datę walidacji - nie powinna być bieżąca ?”

Przy pobraniu oferty za pomocą GET sale/offers/offerID nie jest ona walidowana i nie zwróci błędów, dzieje się to dopiero przy wprowadzeniu zmian w ofercie, stąd taka data.

Przy skorzystaniu z commandId otrzymałeś wynik walidacji, który dotyczy błędów przy próbie  edycji oferty poprzez PUT, np za pomocą PUT sale/offer-quantity-change-commands/{UUID} próbowałeś zmienić stock, a zasób GET sale/offer-quantity-change-commands/{UUID}/tasks zwrócił informację, jakie błędy napotkał podczas wcześniejszego PUT.
