### ISSUE TITLE
Draft_id konto A i konto B

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#1977]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Proszę o informację czy jest możliwość aby draft_id stworzony na koncie "A" był widoczny na koncie "B" i był podstawą do wystawiania aukcji?

Proszę o odpowiedź lub wskazówki czy można to kopiować etc.

**Comment by barthoos** [comment]
Nie mozesz tego skopiowac za pomoca samego Rest API, ale mozesz (korzystajac z access tokena na koncie A) metoda GET pobrac dany sale/offer i za pomoca otrzymanego responsa wyslac go metoda POST na zasob sale/offer (korzystajac z access tokena na koncie B). Oczywiscie pomiedzy tymi operacjami musisz usunac/zamienic wszystkie parametry draftu, ktore sa account specific (id, opcje pozakupowe, cennik dostaw, uslugi dodatkowe, itp).

**Comment by qshop123** [comment]
Ok, dziękuję za odpowiedź.
