### ISSUE TITLE
ServiceTimeoutException / Operation timed out after 15001 milliseconds

### ISSUE THREAD

**Issue by PrzemekTurek2017** [allegro/allegro-api#1978]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzisiaj od 9:00 dostałem około 3k błędów "ServiceTimeoutException" / "Operation timed out after 15001 milliseconds" przy PUT/POST na sale/offers. Znowu jakaś awaria ?

**Comment by PrzemyslawLukanowski** [comment]
Przetestowałem te zasoby na produkcji i nie otrzymałem tego błędu, Czy problem występuje w dalszym ciągu?

**Comment by PrzemekTurek2017** [comment]
Tak, cały czas. Skala już nie ta, ale 1 na ~100 zapytań : `{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Przekroczono czas wykonania zapytania. Spróbuj ponownie."}]}`. I na order/checkout-forms też.

**Comment by PrzemyslawLukanowski** [comment]
@PrzemekTurek2017 czy możesz przesłać nam przykładowy request i trace-id? Jeśli nie otrzymujesz trace-id, podaj przykładowy timestamp.
