### ISSUE TITLE
Roznica w pobieraniu tasks danego zadania

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1979]
Sytuacja 
https://api.allegro.pl/sale/offer-price-change-commands/{commandId}

https://api.allegro.pl/sale/offer-publication-commands/{commandId}

dla tego samego commandId zwraca to samo , to bug czy poprawne zachowanie ?

**Comment by PrzemyslawLukanowski** [comment]
To nie bug, każdym zasobem do sprawdzenia statusu zadania możesz sprawdzić także inne zadanie. Np. za pomocą zasobu PUT sale/offer-price-change-commands/{commandId} zmienisz cenę, to jeśli przekażesz te konkretne commandId dla wywołania zasobu GET sale/offer-price-change-commands/{commandId}/tasks lub GET sale/offer-quantity-change-commands/{commandId}/tasks odpowiedź będzie taka sama.

**Comment by pkrzemo** [comment]
To po co jest tyle nazw na to samo?
Nie może być jedno np.:
GET sale/commands/{commandId}/tasks ?

**Comment by PrzemyslawLukanowski** [comment]
Aby uzyskać informację na temat wykonanych zmian, możesz odwołać się jednego z trzech batchowych zasobów GET lub skorzystać z dedykowanego.
