### ISSUE TITLE
Błąd - Command not found

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1980]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

b8889038-165a-4717-a0bf-b42ec7c8b660

**Request**
https://api.allegro.pl/sale/offer-price-change-commands/b8889038-165a-4717-a0bf-b42ec7c8b660/tasks/

**Response**
Command not found.(HTTP ERROR 404) Command not found. 

**CommandId mamy na podstawie requesta** 

![image](https://user-images.githubusercontent.com/1530496/61337021-e62cb980-a833-11e9-8449-702655fdbbb9.png)

via 
**docs**
https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że dokonujesz zmiany ceny za pomocą starego zasobu [PUT offers/{offerId}/change-price-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createChangePriceCommandUsingPUT). Numer commandId w tym przypadku nie jest powiązany z zasobem GET sale/offer-price-change-commands/{commandId}/tasks, dlatego też w odpowiedzi dostajesz błąd 404. 
Aby prawidłowo odpytać ten zasób, zmień cenę za pomocą [PUT /sale/offer-price-change-commands/{commandId} ](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT). Więcej na ten temat dowiesz się z [naszego poradnika](https://developer.allegro.pl/my_offers/#3f).

**Comment by yncki** [comment]
Czyli meksyk:)
https://github.com/allegro/allegro-api/issues/1975

**Comment by PrzemyslawLukanowski** [comment]
Opis batchowych zasobów znajduje się w [dokumentacji,](https://developer.allegro.pl/documentation/#tag/Batch-offer-modification) a jak z nich korzystać informujemy w [naszym poradniku poświęconym zarządzaniu ofertami](https://developer.allegro.pl/my_offers/).
