### ISSUE TITLE
Czemu metoda sale/offers nie zwraca EANów ?

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#1981]
Jak w temacie ? Kiedy zostanie to poprawione.

**Comment by PrzemyslawLukanowski** [comment]
@keczerad  sale/offers jest zgodne z frontem - tam nie wyświetlamy takiej informacji, dlatego też ten zasób tego nie zwraca.

**Comment by keczerad** [comment]
Odpowiedż mnie nie zadowale ponieważ panuje w niej chaos informacyjny. Proszę sobie zadać pytanie czy external.id jest na froncie ? Odpowiadam nie ma go a ta informacja jest w tej metodzie. Nie rozumiem dlaczego nie ma  EAN skoro jest external.id ? Natomiast mogę powiedzieć że w korporacjach panuje moda na "szastanie" requestami co skolei przekłada się na wydajność systemów, ściągają 10 tysiecy aukcji i chcą uzyskać EAN musimy strzelić do Was 10k requestów dla jedego klienta, jeżeli mamy 1000 klientów a każdy ma 10 tysiecy aukcji zaczyna robić się ciekawie, biorąc pod uwagę ze wy macie mnóstwo klientów pozostaje pytanie ile razy programiści strzelają do Was aby uzyskać EAN ?

**Comment by keczerad** [comment]
Zaznacze też że przy ściąganiu aukcji spzedanych też powien być EAN i external.id, ale niestety go nie ma, dlaczego nie wiem i nie potrafię tego logicznie wytłumaczyć, natomiast faktem jest że muszę znowu do Was strzelać ;).

**Comment by PrzemyslawLukanowski** [comment]
Mój błąd, odczytałem zgłoszenie jako zapytanie o zasób publiczny GET offers/listing . Rozumiem Twoją potrzebę posiadania takiej informacji, przekazałem sugestię do odpowiedniego zespołu. W przypadku wdrożenia tej zmiany, poinformujemy o tym we właściwym komunikacie.
