### ISSUE TITLE
REST API -Oznaczenie zamówienia jako 'wysłane'

### ISSUE THREAD

**Issue by Makzi5** [allegro/allegro-api#1982]
Witam,
czy pojawiła się już możliwość oznaczenia zamówienia jako 'wysłane' przez REST API? Jeżeli nie, to czy będziemy mogli się spodziewać takiej opcji, a jak tak to kiedy?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie ma takiego zasobu. Sugestia została już przekazana do odpowiedniego zespołu. Jeśli zdecydujemy się na jej wdrożenie, poinformujemy w odpowiednim komunikacie.

**Comment by PrzemyslawLukanowski** [comment]
@speeduppoznan Przez WebAPI nie ma możliwości nadania takiego statusu.

**Comment by PabloMD** [comment]
Podpinam się pod sugestie, ponieważ po to używamy API by przyśpieszyć process obsługi. Jaki ma sens dodawanie przesyłek w osobnej aplikacji, jak i  tak trzeba wejść na allegro i oznaczyć jako wysłane ... 😞  ?

**Comment by PrzemyslawLukanowski** [comment]
@PabloMD dołączam Twoją uwagę do wcześniejszego zgłoszenia. Chciałbym przypomnieć, że ten status służy tylko do do filtrowania danych w tej zakładce dla sprzedawcy, kupujący nie dostaje żadnego powiadomienia.

**Comment by speeduppoznan** [comment]
A czy kupujący widzi status zamówienia?
Jeśli jest opcja statusu zamówienia nawet jeśli tylko do filtrowania to i tak trzeba te statusy ustawiać, więc przydałoby się to zrobić możliwość także przez API.

**Comment by speeduppoznan** [comment]
Jeszcze jedno pytanie, czy do statusu "Super sprzedawcy" jest liczony status z allegro czy status w systemie przewoźnika? Zgodnie z opisem na stronie https://allegro.pl/pomoc/dla-sprzedajacych/super-sprzedawca/super-sprzedawca-jak-liczymy-zrealizowane-zamowienia-WEDAg6E4OhZ sprawdzacie tylko trzech przewoźników, a my wysyłamy DPD sporo..
Jeśli jednak liczy status z zamówienia z allegro to automatyzacja statusów zamówień jest potrzebna.

**Comment by PrzemyslawLukanowski** [comment]
@speeduppoznan Kupujący nie widzi statusu zamówienia. 
Status zamówienia z allegro nie jest liczony w programie Super Sprzedawca.

**Comment by speeduppoznan** [comment]
Rozmawiałem z naszym działem sprzedaży. Wprowadzenie możliwości automatycznego zaznaczania statusu zamówienia jako "wysłane" przy podawaniu numeru nadania przez API byłoby bardzo dużym plusem..
Także czekamy na metodę w API do zmiany statusu.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
@speeduppoznan Tak jak wspomniałem, sugestia została już wcześniej przekazana do odpowiedniego zespołu. Jeśli zdecydujemy się na jej wdrożenie, poinformujemy o tym we właściwym komunikacie.

**Comment by esprzedaz** [comment]
> Rozmawiałem z naszym działem sprzedaży. Wprowadzenie możliwości automatycznego zaznaczania statusu zamówienia jako "wysłane" przy podawaniu numeru nadania przez API byłoby bardzo dużym plusem..
> Także czekamy na metodę w API do zmiany statusu.
> 
> Pozdrawiam

Tak z ciekawości - po co to Waszemu działowi sprzedaży?
