### ISSUE TITLE
[Sandbox] RestAPI - brak stabilności

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#1984]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś tj 18.07.2019 działa bardzo niestabilnie środowisko sandbox, pobieranie ofert, filtrowanie, generalnie  8 / 10 requestów się wysypuje

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem zgłoszenie, problem występuje w przypadku losowych wywołań. Zgłosiłem to do odpowiedniego zespołu.
