### ISSUE TITLE
Różne wartości "naturalPerson" w przypadku wybrania faktury na firmę

### ISSUE THREAD

**Issue by marpyc** [allegro/allegro-api#1986]
Zauważyłem, że od czasu do czasu (mam przykłady konkretnych ID transakcji), w przypadku wybrania przez klienta faktury na firmę, tj. podaniu nazwy firmy i nipu (wtedy "required" przyjmuje wartość true oraz company->name oraz company->taxId posiadają przypisane wartości), wartość naturalPerson wygląda czasami tak: "naturalPerson":{"firstName":"","lastName":""}, a czasami tak: "naturalPerson":null.
Z czego wynika ten brak konsekwencji i zwracanie różnych wartości?

**Comment by PrzemyslawLukanowski** [comment]
@marpyc Prześlij za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) numery ofert oraz checkout-formów, których dotyczy problem. Dopisz także #GitHub #1986. Zweryfikujemy zgłoszenie i wrócimy z odpowiedzią.

**Comment by marpyc** [comment]
Dziękuję.Wysłałem dane przez formularz.

**Comment by PrzemyslawLukanowski** [comment]
@marpyc Dziekujemy za dane, zgłosiłem rozbieżność do odpowiedniego zespołu.

**Comment by marpyc** [comment]
Dziękuję.

**Comment by marpyc** [comment]
Świetnie, dziękuję!
