### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#1987]
Macie jakieś problemy?

dla GET /sale/offers

dostaje seryjnie:
{"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"ExternalServiceException","details":null,"path":null}]}

**Comment by PrzemyslawLukanowski** [comment]
W jakim środowisku otrzymujesz błąd? Jeżeli chodzi o sandboxa, problem został już zgłoszony do odpowiedniego zespołu.

**Comment by lukada4100** [comment]
application/vnd.allegro.public.v1+json

działa dzisiaj w kratkę: dwa zapytania ok, przy trzecim error

**Comment by PrzemyslawLukanowski** [comment]
Miałem na myśli, czy w Twoim przypadku problem występuje na produkcji czy sandboxie?

**Comment by PhotoSoft** [comment]
Występuje na produkcji. Mam trochę zgłoszeń od Klientów.

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem problem do odpowiedniego zespołu.
