### ISSUE TITLE
Typ danych w Offer Price Modification

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#1988]
https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT

Dlaczego i po co w strukturze PriceModification wprowadzone są jakieś kolejne typy danych, które wyglądają jak Price. A dodatkowo, o zgrozo, dlaczego wartości liczbowe są podawane jako stringi? Czyżby powrót do złych praktyk SOAP API? Ja wiem, że dla niektórych int, czy string, co za różnica, ale są języki oraz dobre praktyki, które jednak nakazują odróżniać liczby od wyrazów.

Czy będziecie coś z tym robić? Czy już taka lipa zostaje? 😑

**Comment by Onixarts** [comment]
```json
{
    "offerCriteria": [
        {
            "offers": [
                {
                    "id": "6206463617"
                }
            ],
            "type": "CONTAINS_OFFERS"
        }
    ],
    "modification": {
        "type": "FIXED_PRICE",
        "price": {
            "amount": "6000,39",
            "currency": "PLN"
        },
        "value": {
            "amount": "",
            "currency": ""
        },
        "percentage": ""
    }
}
```
i odpowiedź bad request. Podpowiecie dlaczego, bo z treści błędu niewiele można wyczytać.

```json
RESPONSE 400 (Bad Request) ----------------------------------------------------------------- 15:08:28:829 (154ms)
{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offer-price-change-commands/F98A8C43-61B8-484A-BF2E-09A186A7181A",
            "userMessage": null
        }
    ]
}
```

**Comment by PrzemyslawLukanowski** [comment]
Kolejne typy danych występują, ponieważ:

- price przekazujesz, jeśli zmieniasz cenę na konkretną wartość (FIXED_PRICE),
- value przekazujesz, jeśli zmieniasz cenę o konkretną wartość (INCREASE_PRICE lub DECREASE_PRICE)
- percentage przekazujesz, jeśli zmieniasz cenę o konkretny procent (INCREASE_PERCENTAGE lub DECREASE_PERCENTAGE)

Wartość liczbową możesz przekazać zarówno jako Int, jak i string.
Co do drugiego pytania - przesyłasz nadwymiarowe dane. Dla tego przypadku wystarczy wartość dla pola price. Zachęcamy do zapoznania się z [naszym poradnikiem.](https://developer.allegro.pl/my_offers/)

**Comment by Onixarts** [comment]
No ale czym się różni ustaw cenę na 3,50 od powiększ cenę o 3,50, że musi to iść osobnymi strukturami? Procenty to jeszcze mogę zrozumieć, żeby to było w osobnym polu. 
Logikę działania tej struktury rozumiem, ale w dokumentacji nie ma nic aby przekazywać tylko wybrany jej fragment. Jeśli już występuje ona w wariantach to powinna być jakoś rozdzielona na 3 różne requesty, bo tak z dokumentacji wynika, że price, value i percentage występują w jednej strukturze PriceModification.

> Wartość liczbową możesz przekazać zarówno jako Int, jak i string.

Czyli idziemy w kierunku totalnego bałaganu znowu... Nie może być albo to albo to. Wartość liczbowa to ma być liczba i koniec. Jako string to sobie można przekazać wyraz typu "stoprocent", "trzypięćdziesiąt". Poza tym prędzej Number a nie Int.

> Zachęcamy do zapoznania się z naszym poradnikiem.

Już pisałem co myślę o poradnikach, fajnie że są, ale dlaczego tych informacji nie ma w dokumentacji. Potem czytam dokumentację, widzę amount jako string, czytam poradnik a tam amount jako liczba:

```json
"amount":10.50,
```

I bądź tu mądry programisto. Jeśli sam nie sprawdzisz 5 przypadków to się nie dowiesz jak działa to API. A najgorsze, że kolejne 3 przypadki znajdą dopiero klienci u siebie... i cały czas trzeba świecić oczami przed klientami. Nie podoba mi się taki stan rzeczy. Miało być fajnie.

**Comment by Onixarts** [comment]
Czy zatem zawsze i wszędzie liczby przecinkowe można podawać jako liczbę, gdzie w dokumentacji jest string?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z naszym [guideline](https://github.com/allegro/restapi-guideline#price-and-currency) zalecamy korzystanie z typu string.
