### ISSUE TITLE
id zamówienia (web API) a checkout-forms ID

### ISSUE THREAD

**Issue by krsvsh** [allegro/allegro-api#1989]
proszę o informację jakie jest powiązanie pomiędzy zamówieniem w WebAPI oraz w REST API.
identyfikatory są różne (chyba, że coś pominąłem).
np:
checkout-forms ID    83335ac2-a7b9-11e9-8c61-999d36b43ef5
ID z WebAPI     	1046971937
dla tego samego zamówienia.

**Comment by SebastianOzdoba** [comment]
Przeczytaj ten wątek
https://github.com/allegro/allegro-api/issues/1878

**Comment by PrzemyslawLukanowski** [comment]
@krsvsh Zrobisz to za pomocą zasobu [GET /payments/payment-id-mappings?paymentID={paymentID}](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping). Zapoznaj się z [naszym newsem](https://github.com/allegro/allegro-api/issues/1878), w którym szerzej opisaliśmy tę funkcjonalność.

**Comment by krsvsh** [comment]
tak, już @SebastianOzdoba podał mi ten news... natomiast, z tego co widzę działa to z problemami... komplikujecie prostą sprawę moim zdaniem...
