### ISSUE TITLE
doShowItemInfoExt - nie zwaraca aktualnego itDescription ApiAllegro

### ISSUE THREAD

**Issue by BABYBOOM-SERWIS** [allegro/allegro-api#199]
Metoda doShowItemInfoExt zwraca stary opis aukcji, aukcja została zmieniona wczoraj ok godziny 15 a do tej pory przy wywołaniu metody doShowItemInfoExt zwrotnie dostajemy stary opis (sprzed zmiany).

proszę o informacje czemu tak się dzieje i kiedy metoda będzie działała poprawnie.

**Comment by PawelTaberski** [comment]
Przetestowałem i metoda działa prawidłowo. Jeśli w requeście zaznaczyłeś w getDesc 1 to powinieneś otrzymać 2 pola:

- itDescription ze starym opisem oferty
- itStandardizedDescription z nowym opisem oferty

Czy nie otrzymałeś tego drugiego pola

**Comment by PawelTaberski** [comment]
Podeślij proszę pełnego requesta i responsa w formacie XML z metody doShowItemInfoExt przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=1436f902-6fd9-420f-9e19-321b684cc8df) i zaznacz, że dotyczy to zgłoszenia na GitHub, a następnie wklej tutaj numer ticketa. Sprawdzimy w czym jest problem.

**Comment by BABYBOOM-SERWIS** [comment]
[Ticket#1247694250]

**Comment by BABYBOOM-SERWIS** [comment]
Kiedy uda się to naprawić? trochę utrudnia nam to pracę

**Comment by BABYBOOM-SERWIS** [comment]
nie chodzi o to ze jest start opis, API pobiera NIEAKTUALNY OPIS - niezgodny z tym co jest na allegro.
wiem że jest to stara aukcja i opis pobrany jest stary ale powinien być on AKTUALNY.
Proszę porównać HTML który zwraca API ze źródłem opisu z aukcji.

**Comment by PawelTaberski** [comment]
Teraz rozumiem zafiksowałem się i myślałem, że chodzi Tobie o nowy opis, a nie o zmieniony stary opis. Chwilowo proponuje korzystać z tej metody [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842), aby pobrać opis oferty. Sprawę odnośnie tamtej rozbiezności zgłosiłem do odpowiedniego zespołu.
