### ISSUE TITLE
Historia Płatności - Allegro Finanse, Czy API to obsługuje?

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#1990]
Cześć,

Czy API obsługuje https://allegro.pl/payments-operation-history/ ? 
Podstronę na której widzimy wpłaty naszych klientów za zamówienia w tym PayU, Przelewy24

**Comment by PrzemyslawLukanowski** [comment]
Tak, REST API obsługuje historię płatności za pomocą zasobu [GET payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory). Więcej szczegółów znajdziesz we właściwym [newsie](https://github.com/allegro/allegro-api/issues/1826).

**Comment by allmat** [comment]
@PrzemyslawLukanowski  Dziękuję za pomoc :)
