### ISSUE TITLE
https://api.allegro.pl/payments/payment-operations - wyszukiwanie po paymentID

### ISSUE THREAD

**Issue by Inwestor1234** [allegro/allegro-api#1991]
Witam - czy w metodzie 
https://api.allegro.pl/payments/payment-operations
do pobierania informacji o płatności można pobrać dane dla pojedynczej konkretnej transakcji po paymentId czy trzeba pobierać całość wpłat?

Query parametr sugeruje mi że można ale opis metody brzmi jak by można pobrać tylko całość jako listę.

**Comment by PrzemyslawLukanowski** [comment]
Możesz pobrać dane dla pojedynczej transakcji, jeśli jako parametr przekażesz payment.id, np.
GET payments/payment-operations?{payment.id}.
