### ISSUE TITLE
GET /pricing/offer-quotes - dodanie stronicowania

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#1992]
:bulb: **Sugestia**
Korzystanie z **GET /pricing/offer-quotes** poprzez podawanie numerów aukcji jest nieefektywne i czasochłonne. Jeśli Klient ma kilkadziesiąt tysięcy aukcji to można sobie darować korzystanie z tego zasobu przez śmieszny limit odpytania 20 aukcji na raz, bo **trwa to kilka godzin**.

Proszę wprowadzić stronicowanie i niech zasób zwraca opłaty wg daty rosnąco, czyli najpierw najbliższe opłaty, itd.

Na frontendzie widzę, że tak właśnie działa zakładka _"Nadchodzące opłaty"_.

**Comment by PrzemyslawLukanowski** [comment]
Dziękujemy za sugestię. Przekazałem ją do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie, poinformujemy we właściwym komunikacie.
