### ISSUE TITLE
Wyszukiwanie z  bearer-token-for-application

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#1993]
Witam,
Czy jest możliwość w jakiś sposób wykonać poniższe operacje z tokenem typu bearer-token-for-application.

1. Używam metody https://api.allegro.pl/offers/listing do wyciągania danych o ofertach. Chciałbym pobrać dane po numerze aukcji. Czy jest taka opcja? Kiedy w phrase wpisuję id aukcji nie dostaję wyników. Zależy mi aby pobrać tą jedną aukcję.

2. Pobieranie danych o sprzedawcy.
Podczas pobierania ofert z publicznych zasobów dostaję info seller.id. Czy jest sposób aby wyświetlić z tym id stronę sprzedawcy lub pobrać jego login? Widzę, że z tym ID tylko mogę pobrać informację o ocenach.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
1. Zapoznaj się z [naszym poradnikiem](https://developer.allegro.pl/listing/) dotyczącym wyszukiwania i przeglądania ofert. W parametrze phrase możesz podać frazę, która znajduje się w tytule oferty. Id aukcji w tym przypadku nie zwróci żadnych wyników. Jakie konkretnie dane chcesz wyciągnąć? Autoryzacja client-credentials ma swoje ograniczenia.
2. W tym celu możesz skorzystać z metody WebAPI [doGetUserLogin](https://allegro.pl/webapi/documentation.php/show/id,104).

**Comment by artzie92** [comment]
Chcę uniknąć Integracji że starym API. Chcę wyciągnąć podstawowe dane o ofercie znając jej allegro id bez user token. 
Jeżeli chodzi o sprzedawcę to chce chociaż jego login żeby móc przekierować na jego stronę użytkownika.

**Comment by PrzemyslawLukanowski** [comment]
Publiczny zasób GET/offers/listing jest odzwierciedleniem wyszukiwarki wizualnej serwisu. Nie możesz więc uzyskać podstawowych informacji o ofercie za pomocą jej id. 
Za pomocą seller.id nie pobierzesz jego loginu, ale możesz pobrać listę ofert poprzez GET offers/listing?seller.id={sellerId}.

**Comment by artzie92** [comment]
Chyba nie do końca ponieważ wpisując w wyszukiwarkę allegro id aukcji zostaję do niej przekierowany, a z poziomu API nie dostaję takich samych wyników w odpowiedzi. Z pobieraniem aukcji po seller.id wiem, że problemu nie ma :). Czyli nie jestem w stanie pobrać szczegółów aukcji za pomocą jej id korzystając z client token. Wszystko zostało wyjaśnione uznaję temat za zakończony. Dziękuję.
