### ISSUE TITLE
REST API lineItems w  /order/checkout-forms

### ISSUE THREAD

**Issue by Makzi5** [allegro/allegro-api#1994]
Czy lineItem ID, które jest zwracane w metodzie /order/checkout-forms jest zawsze takie same dla konkretnego produktu, czy generowane jest jednorazowo dla jednego zamówienia? 

"id": "ffc36fa0-9584-11e8-8d53-07c966f77738"
![Screenshot from 2019-07-18 16-18-12](https://user-images.githubusercontent.com/39313493/61465169-d1f1d500-a977-11e9-9e9b-67ebafac7c77.png)

**Comment by PrzemyslawLukanowski** [comment]
@Makzi5 lineItem.id jest unikatowe w każdym zamówieniu.
