### ISSUE TITLE
ATTEMPT_TO_CHANGE_OFFER_QUANTITY_TO_INVALID_VALUE

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#1996]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

command
ce55205b-8f2b-42bb-98a6-1615a8eabf4d

Trace-Id
98438eee5dac1765

![image](https://user-images.githubusercontent.com/1530496/61491246-1f3d6900-a9af-11e9-8994-6364708f63db.png)

commandDetails  response
![image](https://user-images.githubusercontent.com/1530496/61491310-4005be80-a9af-11e9-9654-b6748613a152.png)

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i nie udało mi się powtórzyć tego błędu, API zwraca prawidłowe dane. Czy problem w dalszym ciągu występuje?

**Comment by SebastianOzdoba** [comment]
To ja się podpinam, bo mam podobny błąd

REQUEST 2019-07-19 10:40:55.4634421 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/b9b9a983-9807-4e87-a9a0-fa9d0aa432c7/tasks?limit=1&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \

RESPONSE 2019-07-19 10:40:55.4946888 Duration: 31,2467ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2019-07-19T08:37:53.159Z",
        "Message": "ATTEMPT_TO_CHANGE_OFFER_QUANTITY_TO_INVALID_VALUE",
        "Offer": {
          "Id": "8288315237"
        },
        "ScheduledAt": "2019-07-19T08:37:52.865Z",
        "Status": "FAIL"
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "e7dbda4ee29c68eb",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PrzemyslawLukanowski** [comment]
@yncki @SebastianOzdoba Zgłosiłem błąd do odpowiedniego zespołu.

**Comment by yncki** [comment]
@PrzemyslawLukanowski i?

**Comment by PrzemyslawLukanowski** [comment]
@yncki Pracujemy nad tym, prośba o cierpliwość.
