### ISSUE TITLE
POST https://upload.allegro.pl/sale/images

### ISSUE THREAD

**Issue by Ab1lity** [allegro/allegro-api#1997]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

`const UPLOAD_IMAGES_URL = "https://upload.allegro.pl/";`

zdjęcie ma w linku https://
``` public function sendImagesForAllegro($image)
    {
        $client = new Client(['base_uri' => self::UPLOAD_IMAGES_URL]);

        $imageRequest=
            $client->request('POST', 'sale/images',
                [
                    'debug' => true,
                    'headers' => [
                        'Authorization' => $this->getBearerToken(),
                        'Accept' => 'application/vnd.allegro.public.v1+json',
                        'Content-Type' => 'application/vnd.allegro.public.v1+json'
                    ],
                    'json' => ['url' => $image]
                ]);

        return $imageRequest;
    }```

`POST https://upload.allegro.pl/sale/images`
<!-- podaj trace-id -->
`Trace-Id: 803790b04023482d`
<!-- dokładnie opisz problem -->
Przesyłam zdjęcia przez rest api do tej pory działało bez zarzutu 

```PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://upload.allegro.pl/sale/images` resulted in a `422 Unprocessable Entity` response:
{"errors":[{"code":"UnprocessableEntity","message":"Unprocessable entity","details":null,"path":null,"userMessage":"Imag (truncated...)```

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem, API zwraca błąd przy próbie zaladowania obrazka ze zgłoszenia. Zgłosiłem to do odpowiedniego zespołu.

**Comment by Ab1lity** [comment]
@PrzemyslawLukanowski  Czy udało się to naprawić jakiś feed back od programistów ??

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad problemem, prośba o cierpliwość.

**Comment by Onixarts** [comment]
Jeśli już o uploadzie zdjęć, to kilka osób zgłosiło nam błąd typu:

```
Niedozwolony typ zdjęcia.
HTTP Status: Unsupported Media Type (415)
```

Chwilę później inny użytkownik ma błąd:

```
Plik nie jest obrazem w formacie JPG, PNG, GIF lub SVG.
HTTP Status: Unsupported Media Type (415) 
```

Jakby były tam jakieś modyfikacje przeprowadzane. Czy przy okazji poprawek nie wycięliście jakichś MIME typu IMAGE/JPEG IMAGE/JPG?

**Comment by PrzemyslawLukanowski** [comment]
@Onixarts - problem występuje na produkcji czy sandboxie? Prześlij nam proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełnego cURLa z requestem i responsem dla wywołań, w których występuje błąd.

**Comment by Onixarts** [comment]
Użytkownicy raczej pracują w większości na produkcji ;). Dzisiaj nie mieliśmy jeszcze sygnału od użytkowników aby problem taki nadal występował. Jak będzie to dam znać.

**Comment by Ab1lity** [comment]
I wiadomo coś do słownego wątku nie sadze by przejrzenie jednego EndPointu zajmowało 3 dni

**Comment by PrzemyslawLukanowski** [comment]
Na chwilę obecną nie, prośba o cierpliwość. Wrócę z odpowiedzią, jak tylko uda sie coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
@Ab1lity Adres jest po https, jednak certyfikat zainstalowany na serwerze jest niekompletny. Brakuje certyfikatów pośrednich (Intermediate/chain certificate), które będą prowadzić do certyfikatu głównego (trusted root certificate). Dowolny online SSL checker wyjaśni problem dokładnie. Większość przeglądarek nie jest aż tak restrykcyjna, żeby odrzucić taki adres, ale nasze serwery na to nie pozwalają.
