### ISSUE TITLE
Logowanie / wylogowanie

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#1998]
Czy istnieje taki zasób w rest api zwracający informacje o tym jaki użytkownik jest aktualnie zalogowany ? 
Oraz czy jest metoda powodująca wylogowanie aktualnie zalogowanego użytkownika ?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować pytanie? Informacje o ważności tokena możesz otrzymać po jego rozkodowaniu.

**Comment by kubaszy** [comment]
Czy będąc już zalogowanym mam możliwość za pomocą np przycisku wylogować z allegro ? Czy istnieje taka metoda którą mógłbym podpiąć pod przycisk i ona by mnie wylogowała z konta allegro ?

**Comment by PrzemyslawLukanowski** [comment]
REST API nie udostępnia takich możliwości.
