### ISSUE TITLE
WebAPI nie zwraca danych na temat przesyłki

### ISSUE THREAD

**Issue by mateuszmalek** [allegro/allegro-api#2]
W nawiązaniu do posta z **1 grudnia 2016 roku** (https://www.facebook.com/AllegroAPI/posts/1609412846026721):

> Dlaczego WebAPI nie zwraca danych na temat przesyłki (poprzez metodę doGetPostBuyFormsDataForBuyers) tylko pustą tablicę pomimo faktu, iż po zalogowaniu na stronie Allegro dane na temat przesyłki przy określonych transakcjach są dostępne? Czy przyczyną takiego zachowania może być to, że posiadają one status "Dostarczone"?

Request: https://pastebin.com/CxN0gS0T
Response: https://pastebin.com/U1t8sYey

Pole PostBuyFormShipmentTracking według dokumentacji powinno zawierać "tablicę struktur zawierająca informacje o przesyłce" (w tym numer przesyłki i firmę przewozową). Tymczasem zwracana jest pusta tablica.

Błąd w dalszym ciągu (czyli już ponad rok) nie został naprawiony.

**Comment by MarcinLuczak** [comment]
Mateuszu, wiem że to długo trwa, ale do zakończenia tego tematu jest już bliżej niż dalej. Pracujemy nad wieloma kwestiami dotyczącymi przesyłek i problem z Twojego zgłoszenia jest jednym z nich.

Damy znać, gdy problem zniknie.
