### ISSUE TITLE
Promowane oferty

### ISSUE THREAD

**Issue by mbx88** [allegro/allegro-api#20]
Czy jest możliwość pobrania za pomocą Allegro Web API samych promowanych ofert dla konkretnego konta ?

**Comment by AniaMalinowska** [comment]
Nie ma takiej możliwości. 
Alternatywne rozwiązanie to zastosowanie filtra userId podczas wywołania metody [DoGetItemsList](https://allegro.pl/webapi/documentation.php/show/id,1342). Otrzymasz wówczas listę ofert danego użytkownika. Następnie możesz we własnym zakresie wysortować sobie z treści Response oferty z wartością, która Cię interesuje: 'promotionInfo'.

**Comment by mbx88** [comment]
Dziękuję za odpowiedź. A czy dla konkretnej aukcji dla się pobrać historię sprzedaży ? Tzn kiedy, ile przedmiotów zostało sprzedanych ? I kiedy zostały pobrane opłaty za promowanie ?

**Comment by AniaMalinowska** [comment]
Aby sprawdzić koszty dla danej oferty, użyj metody [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301). Pozyskanie informacji z dokładnymi datami, kiedy pobieramy opłaty, umożliwi Ci [ten zasób]( https://developer.allegro.pl/news/2018-02-14-Zasob_do_sprawdzania_daty_oplaty/) w REST.
Jeśli chodzi o informacje ile przedmiotów zostało sprzedanych - skorzystaj z metody [doGetSiteJournalDeals](https://allegro.pl/webapi/documentation.php/show/id,742).

**Comment by mbx88** [comment]
Witam
czy da się pobrać wszystkie opłaty związane z daną aukcją ale również z datami? Opłaty czyli prowizje od sprzedaży oraz opłaty za promowanie?

**Comment by AniaMalinowska** [comment]
Niestety metoda doMyBillingItem nie zwraca dat. W tym celu możesz skorzystać z Mojego Allegro - z zakładki [Rachunki > Historia > Zamów zestawienie](https://allegro.pl/billinghistory/#/history).

**Comment by mbx88** [comment]
Czyli za pośrednictwem api (web lub rest) nie da się pobrać takiego zestawienia?

**Comment by AniaMalinowska** [comment]
Możesz ewentualnie połączyć działanie poniższych dwóch metod. Ich wspólną wartością jest ID oferty:

- [doGetSiteJournal](https://allegro.pl/webapi/documentation.php/show/id,65) - zdarzenia z oferty i daty
- [doMyBillingItem](https://allegro.pl/webapi/documentation.php/show/id,301) - koszty od danej oferty
