### ISSUE TITLE
delivery price formation error

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#200]
Hello. We use GLS & DHL courier for delivering our products. And there is a problem with price formation: If basket consist products with GLS & DHL services - the delivery price is equivalent to 0.00.
Look at the linked pictures:

[image1](https://drive.google.com/open?id=14mVAYj0zUx-6GBWfbQxyqFppVX609Klh)
[image2](https://drive.google.com/open?id=1Iq5EAL-YTQG9Qtcr9kZUW7acNoQY1N2c)
[image3](https://drive.google.com/open?id=1IrGSnkdvLHBTEyQTGeYJvVXQ0lyu3svM)

p.s. shipmentPriceTypeId = 1

**Comment by PawelTaberski** [comment]
Here we deal with problems related to Allegro API. In that case please write to use [via the contact form](https://allegro.pl/pomoc/kontakt#subjectId=ba0ccf14-493c-480c-a982-f66074cf7959)

**Comment by Folganoid** [comment]
thx
