### ISSUE TITLE
Problem z tokenem

### ISSUE THREAD

**Issue by Draken79** [allegro/allegro-api#2000]
Od jakiegoś czasu wyskakuje taki błąd:

{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

zaczęło się jakieś 2 tyg temu i błąd wyskakiwał raz na jakiś czas. Teraz jest już gorzej, bo błąd wyskakuje prawie zawsze, a tylko raz na jakiś czas nie.

Proszę o usunięcie problemu
z góry dziękuję

**Comment by Draken79** [comment]
Ok, sprawdziłem i okazuje się, że problemem jest pusty token, wtedy taki błąd się pojawia. Tylko dlaczego zwraca pusty token?? Tak jak pisałem problem zaczął się ok. 14 dni temu i najpierw był sporadyczny, a w ostatnich dniach się nasilił :(

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pustego tokena powinien pojawić się błąd "Full authentication is required to access this resource". Błąd, o którym piszesz, ma miejsce wtedy, gdy chcemy np. użyć tokena sandboxowego na produkcji lub odwrotnie. Upewnij się, czy taka sytuacja nie ma miejsca.

**Comment by Draken79** [comment]
Dziękuje za odpowiedź. Problem w tym, że po swojej stronie niczego nie zmieniałem przynajmniej od 3 miesięcy. Nigdy też nie korzystałem z sandboxa. Pytanie zatem, co panstwo zmieniali w ostatnich kilkunastu dniach?
Token jest pusty, ew moge sprawdzic czy nie są to spacje.

**Comment by imper86** [comment]
@Draken79 @PrzemyslawLukanowski potwierdzam, wysłanie nagłówka dosłownie "Authorization: Bearer", czyli bez tokenu, zwraca taki właśnie błąd.

**Comment by Draken79** [comment]
ok.. to jest kod w php, który zwraca (coraz częściej) pusty token:

`$process = curl_init('https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=' . $code . '&redirect_uri=http://xxx');
	curl_setopt($process, CURLOPT_HTTPHEADER, array('Content-Type: application/xml', $additionalHeaders));
	curl_setopt($process, CURLOPT_USERPWD, 'xxx');
	curl_setopt($process, CURLOPT_TIMEOUT, 30);
	curl_setopt($process, CURLOPT_POST, 1);
	curl_setopt($process, CURLOPT_POSTFIELDS, $post);
	curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
	$return = curl_exec($process);
	curl_close($process);
	$dane = json_decode($return);
	$token = $dane->access_token;`

niczego nie zmieniałem od co najmniej 3 miesięcy, a problem z pustym tokenem pojawił się kilkanaście dni temu.

Czy mam rozumieć, że mimo iż REST API jest w ciągłym rozwoju niczego państwo nie zmieniacie? :o

**Comment by barthoos** [comment]
@PrzemyslawLukanowski Polecam sprawdzic. Wyslanie naglowka z samym Bearer (spacja) zwraca blad "invalid json". Zarowno na produkcji jak i na sandboxie. 

#2003 Zreszta to nie jedyny problem z tokenami jaki posiadam

**Comment by PrzemyslawLukanowski** [comment]
@Draken79 Prześlij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełen request w formacie danych cURL wraz z dopiskiem GitHub #2000. W jakim celu tak często generujesz nowe tokeny? Pamiętaj, że możesz korzystać z [odświeżania access tokena](https://developer.allegro.pl/auth/#refresh-token).

**Comment by Draken79** [comment]
Problem rozwiązany. Powodem był zły header i brak kodowania base64.
Pytanie dlaczego to bez problemu działało wcześniej, jakiś czas temu działało wybiórczo, a ostatnio praktycznie przestało działać??
Nikt mi nie wmówi, że informatyka to nauka ścisła ;)
