### ISSUE TITLE
Wyłączenie weryfikacj dwustopmniowej na sandboxie

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2001]
Witam,
proszę o wyłącznie weryfikacji dwustopniowej na koncie o loginie aa
na serwerze sandboxosym.

Wcześniej mogłem się logować bez weryfikacji sms, a dzisiaj wyskoczył komunikat że mam aktywowaną opcję logowania dwustopniowego. Oczywiście numer telefonu który mam podany na sandboxie jest tak bardzo prawdziwy że nie nie mogę się zalogować

**Comment by PrzemyslawLukanowski** [comment]
Dwustopniowe logowanie możesz wyłączyć przez zakładkę Moje konto -> Bezpieczeństwo - Dwustopniowe logowanie.

**Comment by mzawodzinski** [comment]
tylko żeby to zrobić muszę się zalogować, a nie mogę się zalogować bo muszę podać kod sms

**Comment by PrzemyslawLukanowski** [comment]
Kod sms na sandboxie to zawsze 1234.

**Comment by mzawodzinski** [comment]
nope,
ten kod ma mieć 6 cyfr.
123456 nie działa
000000 też nie działa 

1234 to kod do potwierdzenia zakupów, a mi chodzi o zalogowanie się na konto.

**Comment by PrzemyslawLukanowski** [comment]
Próbowałeś wpisać 1234? W tym przypadku nie sugeruj się, że kod musi mieć 6 cyfr.

**Comment by mzawodzinski** [comment]
sprawdzałem, 
wczoraj sprawdzałem kilkanaście razy nie działało 
dzisiaj zadziałało
