### ISSUE TITLE
Automatyczna aktywacja kont sandbox

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2002]
:bulb: **Sugestia**
przeglądają issues można natrafić na całą masę zgłoszeń z prośbą o aktywację konta #825 #946 #934  #1700 ...

Czy naprawdę zrobienie automatycznej aktywacji na sandboxie jest tak skomplikowana ? Od mojego zgłoszenia #449 gdzie dostałem informację że "zostało to przekazane do odpowiedniego zespołu" minął już prawie rok.

**Comment by rtnet-pl** [comment]
Dodatkowo utrudnia to bycie na bieżąco z komunikatami publikowanymi tutaj.
Opcjonalnie może warto przypiąć na górze wątek dot. aktywacji który można sobie wyciszyć?

**Comment by PrzemyslawLukanowski** [comment]
Proces aktywacji na sandboxie dla konta zwykłego został zautomatyzowany, użytkownik może aktywować sprzedaż bez potrzeby weryfikacji z naszej strony. Konto firma tego wymaga, ponieważ chcemy oddać, jak ten etap przebiega na produkcji.

**Comment by mzawodzinski** [comment]
A nie można tego przynajmniej skrócić ? Myślę że 15minut na sandboxie doskonale odda trzydniowy czas oczekiwania na produkcji.

**Comment by PrzemyslawLukanowski** [comment]
Aktywacja konta z naszej strony następuje niemalże od razu po zapoznaniu się ze zgłoszeniem usera. Po wysłaniu przykładowych plików przez Moje konto, zostaje ono już automatycznie aktywowane.
