### ISSUE TITLE
tokeny - zarzadzanie, refresh, cofniecie autoryzacji

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#2003]
Generalnie temat mam u siebie dosc sprawnie ogarniety. Natomiast zdarzaja mi sie sytuacje, gdzie pomimo poprawnego cyklu refreshy w ktoryms momencie "lancuszek sie przerywa" i przestaje byc w stanie autoryzowac sie w imieniu klienta. Jako, ze wciaz i wciaz to sie zdarza, zrobilem pelne logowanie dokonywanych przeze mnie refreshy, gdzie loguje:

typ akcji (access/refresh), stary access/refresh token, nowy access/refresh token, czas, response/response_hdr w przypadku gdy autentykacja sie nie powiodla

Tym sposobem widze, co, gdzie i kiedy robilem z odswiezaniem tokenow. I teraz mam takie przypadki, gdzie mimo poprawnego lancuszka stary/nowy token w pewnym momencie przy refresh tokenie dostaje error: invalid_grant. Jak ja mam to teraz zdebuggowac? Jedyne co moze okazac sie pomocne w naglowkach odpowiedzi to:

`"X-Backend":"auth_1488801_dc5_131_113_31990"`

Czy na tej podstawie, jestescie w stanie zweryfikowac co bylo tutaj problemem?

Dodatkowo, bo mam pewne podejrzenia, jak API bedzie mi odpowiadalo, gdy poprawnie odswiezam sobie tokeny, a uzytkownik sam cofnie zgode dla mojej aplikacji w panelu na stronie allegro??

**Comment by PrzemyslawLukanowski** [comment]
> Dodatkowo, bo mam pewne podejrzenia, jak API bedzie mi odpowiadalo, gdy poprawnie odswiezam sobie tokeny, a uzytkownik sam cofnie zgode dla mojej aplikacji w panelu na stronie allegro??

Otrzymasz wtedy error Unauthorized.

> Czy na tej podstawie, jestescie w stanie zweryfikowac co bylo tutaj problemem?

Jesteśmy w trakcie weryfikacji Twojego zgłoszenia.

**Comment by PrzemyslawLukanowski** [comment]
@barthoos Prześlij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) dwa przykładowe requesty (ten, który wywołał błąd oraz wcześniejszy, zakończony sukcesem) wraz z trace-id. Do wiadomości dopisz GitHub #2003.

**Comment by barthoos** [comment]
Niestety nie loguje sobie w pelni pomyslnego odswiezenia tokenow, a to odswiezenie "bledne" nie ma trace-id w naglowku odpowiedzi (tylko ten X-Backend, ktory wczesniej podalem). Mam natomiast pelny lancuszek access/refresh tokenow i response + response_hdr z blednego odswiezenia. Czy to wystarczy do weryfikacji po waszej stronie?

**Comment by PrzemyslawLukanowski** [comment]
@barthoos - prześlij za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #2003, spróbujemy na tej podstawie zlokalizować źródło problemu.
