### ISSUE TITLE
Kodowana wiadomość od kupujący do sprzedający . Załączniki ograniczenia ?

### ISSUE THREAD

**Issue by Chater123** [allegro/allegro-api#2006]

**Comment by Chater123** [comment]
Witam

po zakończonej sprzedaży na allegro kupujący musi dosłać plik graficznynp w formacie JPG do finalizacji zamówienia d .fotoobrazu, kubka etc.    Jak to chula w tej kodowanej wiadomości. Są jakieś ograniczenia?
Jak to klient ma robić

**Comment by PrzemyslawLukanowski** [comment]
Wiadomość email powinna dojść bez przeszkód, razem z załącznikiem. Więcej informacji znajdziesz [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL).
