### ISSUE TITLE
Błędy przy zmianie ceny, ilość i publikacji oferty

### ISSUE THREAD

**Issue by artikpl** [allegro/allegro-api#2007]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę zmienić ceny, ilości ani wznowić produktu.

Odpowiedzi z tasków:
/sale/offer-**price-change**-commands/0768c55d-75a7-1749-1ecc-66bac111e127/tasks 
zwraca **OPERATION_FAILED, ERR_ITEM_CAN_NOT_BE_RENEW**

/sale/offer-**publication**-commands/b3b19424-f803-0fd1-fe89-2b75b1bd34e9/tasks
zwraca **An error occurred while trying to change the publication of the offer. Please try again later**

/sale/offer-**quantity-change**-commands/888a5275-0188-f2cf-2afe-bcab4f7b0134/tasks zwraca **EXCEPTION_DURING_OFFER_QUANTITY_UPDATE, ERR_ITEM_CAN_NOT_BE_RENEW**

Tak od paru dni dla oferty 8111333240

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i API rzeczywiście zwraca błąd. Zgłosiłem to do odpowiedniego zespołu.

**Comment by artikpl** [comment]
I jak tam?

**Comment by PrzemyslawLukanowski** [comment]
@artikpl Oferta została poprawiona, błąd już nie powinien występować.

**Comment by anih** [comment]
@PrzemyslawLukanowski  Ja mam ten sam problem z  8355344035 i 8355343901
 i `PUT /sale/offers/{auction_id}` gdzie w `response['validation']['errors']` mam:
`{'code': 'VALIDATION_ERROR', 'path': '', 'details': '', 'message': 
 ERR_ITEM_CAN_NOT_BE_RENEW', 'userMessage': ''}`

**Comment by PrzemyslawLukanowski** [comment]
@anih Przekazałem numery ofert do zgłoszenia związanego z opisanym problemem.

**Comment by anih** [comment]
Na dzień dzisiejszy tylko 8355343901 jest aktualna, bo ta druga przeszła za którymś PUTem
