### ISSUE TITLE
Skopiowanie aukcji allegro z jednego konta na drugie

### ISSUE THREAD

**Issue by Pablossoo** [allegro/allegro-api#2008]
Jak mogę skopiować aukcję z jednego konta allegro na drugie ? 
wg opinii którą usłyszałem, poznanie (zrozumienie wraz z metodami + krokowy opis) tego zagadnienia nie powinno mi zająć więcej jak godzinę czasu. 

p.s nigdy nie małem styczności z api allegro.

**Comment by Onixarts** [comment]
Optymista :D

**Comment by FromAnyHole** [comment]
Godzinę... może tyle to w ramach gotowej aplikacji, którą też trzeba poznać ;-)

**Comment by PrzemyslawLukanowski** [comment]
@Pablossoo Wszystkie niezbędne informacje do rozpoczęcia pracy z REST API znajdziesz na [naszej stronie](https://developer.allegro.pl/about/). Aby skopiować ofertę, musisz ją najpierw pobrać za pomocą zasobu [GET sale/offers/offerID](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) (musisz być [autoryzowany](https://developer.allegro.pl/auth/) jako sprzedawca, do którego należy oferta), następnie wszystkie dane, jakie otrzymałeś, możesz przesłać za pomocą zasobu [POST sale/offer](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST), tworząc nową ofertę. Aby utworzyć ofertę na drugim koncie, musisz posiadać access token należący do tego konta. Między jedną a drugą operacją musisz wyedytować niektóre dane, przypisane do konkretnego konta, np. cennik dostaw, usługi posprzedażowe. Więcej na ten temat znajdziesz w naszym poradniku -[ jak wystawić ofertę](https://developer.allegro.pl/sale/).
