### ISSUE TITLE
Nie działa składanie zamówień na sandbozie

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2009]
Podczas próby zakupów wyskakuje błąd uniemożliwiający dokończenie procesu zakupowego 
https://youtu.be/C-2BU9kD3j8

w inspektorze obiektów widać żądania wysyłane metodą PUT na adres https://edge.allegro.pl.allegrosandbox.pl/purchases/675fe630-ad39-11e9-b97c-dd550338e1ca
>503 Service Unavailable
> {"errors":[{"code":"SERVICE_UNAVAILABLE","message":"UpdatePurchaseCommand failed and fallback disabled.","details":"failure_type=COMMAND_EXCEPTION","path":null,"userMessage":"Wystąpił błąd."}]}
powtarza się ono 6 razy i wtedy wyskakuje błąd

**Comment by Onixarts** [comment]
Potwierdzam. Od wczoraj z testami stoimy, a klienci czekają na nową wersję.

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
Błąd został usunięty, składanie zamówień działa prawidłowo.

**Comment by mzawodzinski** [comment]
Potwierdzam, działa
