### ISSUE TITLE
Konieczność podania cennika

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#201]
Niektóre moje aukcje nie mają przypisanego cennika i ceny wysyłki mają zmodyfikowane w stosunku do innych aukcji. Próbuje teraz dla tych aukcji ustawiać Czas wysyłki dla przedsprzedaży (delivery/shipmentDate) lecz dostaję (pewnie celowo) błąd, że muszę określić cennik wysyłki (tj. delivery/shippingRates/id). I teraz pytanie - da się to jakoś obejść?

Czy jedyne co mi pozostaje, to stworzenie dla tych aukcji (pewnie dla każdej z osobna) indywidualny cennik wysyłki, przypisać go i dopiero modyfikować datę przedsprzedaży?

Czy przypisane cennika do aukcji, która nie ma takiego przypisanego zmienia ceny na tej aukcji (tj. trzeba ręcznie je modyfikować?)

**Comment by PawelTaberski** [comment]
Możesz grupowo przypisać cenniki do wielu ofert na raz przez REST API, bądź Moje Allegro nie musisz tego robić ręcznie pojedynczo dla każdej oferty, następnie będziesz mógł dodać czas wysyłki dla przedsprzedaży.

**Comment by pgasidlo** [comment]
Wracając do pytania: nie da się ustawić "daty przedsprzedaży" bez ustawiania "cennika wysyłki"? Piszę o przypadku, gdy aukcje takiego cennika nie mają przypisanego (mają indywidualne ceny a zostały wystawione przez WebAPI - stąd brak).

Chyba pozostanie mi domyślnego cennika + daty wysyłki a następnie przez WebAPI ponowna korekcja dostawy dla wybranych aukcji.

**Comment by PawelTaberski** [comment]
Zgadza się przy edycji danych ofert musisz do nich przypisać cennik dostawy, aby móc edytować/dodawać inne elementy.

**Comment by expondo** [comment]
Witam, odświeżę temat,
Co w przypadku gdy nie korzystam z e zdefiniowanego cennika dostaw tylko ustalam dla konkretnej oferty koszta ręcznie. Wówczas api zwraca mi dane w metodzie /sale/offers/ID:

    [delivery] => stdClass Object
        (
            [shippingRates] => 
            [handlingTime] => PT0S
            [additionalInfo] => 
            [shipmentDate] => 
        )

Gdy próbuję to wysłać to otrzymuję błąd że mam podać ID cennika. Jak zaktualizować ofertę nie ruszając ręcznie ustalonych cen wysyłek?

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości, aby wystawić ofertę przez REST API wymagany jest cennik dostaw. Planujemy w przyszłości udostępnić zasoby do tworzenia i edycji cenników przez REST API.
