### ISSUE TITLE
Odnośnie bazy Tecdoc 

### ISSUE THREAD

**Issue by emteusz** [allegro/allegro-api#2010]
:bulb: **Sugestia**

Mam pytanie - sugestię odnośnie tecdoca zastosowanego w allegro, obecnie widzę, iż z tecdoca są pobrane tylko i wyłącznie nazwy modeli samochodów które sam sprzedający wybiera z listy, wiemy też, że w allegro jest w opisie produktu musi być wypełniony producent oraz numer katalogowy części, czyżby nie można było spiąć tego, aby tecdoc sam pobierał listę pojazdów identyfikując po numerze katologowym części oraz producencie? Oszczędziło by to bardzo dużo czasu mniejszym sprzedającym, a także również błędów popełnianym.

**Comment by kfijalko** [comment]
:) wcześniej pracownicy allegro pisali, że wkrótce poznamy szczegóły dotyczące "produktyzacji" w częściach samochodowych. Zakładam, że powyższe będzie spełnione, choć dotychczasowa produktyzacja w innych kategoriach obejmowała tylko parametry towaru bez "pasuje do". Z drugiej strony powstanie ryzyko, że mógłbyś z allegro pobrać bazę tecdoc: numery, parametry i zastosowania. Z trzeciej strony allegro przyjęło by na siebie odpowiedzialność za dopasowanie części (w tecdoc są błędy). No to teraz niech wypowie się allegro ;)

**Comment by emteusz** [comment]
jest moda na sklepy z katalogiem tecdoc, gdzie w opisie produktu wszystko jest pobierane - opis, numery zamienników/oe i zastosowanie, więc jakby allegro wprowadziło tylko zastosowanie, to nie byłoby głupim pomysłem sądzę.. 
ryzyko, że pobralibyśmy bazę? która jest można powiedzieć prawie ogólnie dostępna (dużo sklepów internetowych w tą wyszukiwarką)
też mi się wydaję, że będzie spełnione, ale sprzedający który ma np. 500 aukcji różnych produktów i w każdej aukcji, kilkanascie jak nie kilkadziesiąt kliknięć, aby wybrać dane modele, to porażka, jakie by było zdziwienie, jakby wprowadzili za miesiąc :)

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski  możesz napisać jaki jest status prac nad produktyzacją w częściach samochodowych. Najlepiej jak byś wypunktował jakie przyjęliście założenia?

**Comment by PrzemyslawLukanowski** [comment]
W ciągu najbliższych tygodni będzie to działać tak jak piszecie - w motoryzacji dla produktu dostaniemy nie tylko parametry, ale również gotową listę pasuje do. Szczegóły podamy wkrótce, prosimy o cierpliwość.

**Comment by emteusz** [comment]
dziękujemy za odpowiedź, tylko pytanie na teraz - co jeśli w niektórych aukcjach już są modele wbite ręczne? będą zastąpione automatem? Jest sens w ogóle to uzupełniać?

**Comment by PrzemyslawLukanowski** [comment]
Założenie jest takie, że dane produktu i oferty muszą byc spójne. Czyli nie będzie można zachować sekcji pasuje do, która wcześniej była dodana w ofercie. Będzie trzeba dodać treśc sekcji pasuje do z produktu.

**Comment by emteusz** [comment]
W takim razie rozumiem, ze nie ma sensu teraz uzupełniać ręcznie na aukcjach pola pasuje do ponieważ w niedługim czasie będzie to zaciągane automatycznie po kodzie produktu i producencie z tec doc?
Drugie pytanie co z produktami które nie widnieją w katalogu tec doc (np. Produkty oryginalne markowe np. Ford, VAg, generał Motors)

**Comment by TomekKaczmarek** [comment]
@emteusz niestety, nie jest to takie proste. Po pierwsze - danych z bazy TecDoc możesz użyć tylko dla nowych przedmiotów. Po drugie - tak, jak piszesz - w TecDoc nie ma produktów oryginalnych, są tylko zamienne. Pracujemy nad opcją dodawania produktów przez sprzedawców - w ten sposób będziemy dodatkowo nasycać naszą bazę danych, czy jednak ta opcja pojawi się w częściach motoryzacyjnych - ostateczna decyzja jeszcze nie zapadła. O kolejnych zmianach będziemy informować na bieżąco.

**Comment by kfijalko** [comment]
@TomekKaczmarek kiedy w częściach samochodowych zablokujecie możliwość podawania "pasuje do" w wersji textowej?

**Comment by TomekKaczmarek** [comment]
@kfijalko nie powinno być takiej możliwości. Sprawdziłem przed chwilą i przy próbie dodania do oferty wersji tekstowej Pasuje do - zwracamy błąd HTTP status 422:

`{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Selected compatibility table has different input type than supported in offer category.",
            "details": "",
            "path": "",
            "userMessage": "Selected compatibility table has different input type than supported in offer category."
        }
    ]
}`

Jeśli w ofercie jest tekstowa wersja sekcji, a w danej kategorii dopuszczamy tylko zintegrowaną z bazą pojazdów:
- Niezmienioną treść sekcji możesz przesłać przez PUT /sale/offers/ i modyfikować pozostałe dane
- Jeśli chcesz zmienić treść sekcji Pasuje do - musisz przejść na wersję zintegrowaną z bazą pojazdów.

**Comment by kfijalko** [comment]
ok, ja wszedłem na formularz wystawiania oferty allegro i tam jest pole do wklejenia wersji tekstowej - nie nacisnąłem "zapisz" może wyskoczył by błąd

**Comment by TomekKaczmarek** [comment]
@kfijalko ale chyba nie nasz formularz?

**Comment by kfijalko** [comment]
![image](https://user-images.githubusercontent.com/7058985/61945999-b737e580-afa1-11e9-8fe0-b5889d586068.png)

**Comment by kfijalko** [comment]
własnie wszedłem ponownie i jest pole

**Comment by TomekKaczmarek** [comment]
@kfijalko to nie tak :). To jest opcja, która pozwala dodać wiele modeli - ale nie do wersji tekstowej, tylko do wersji zintegrowanej z bazą pojazdów. Jeśli dysponujesz gotową listą pojazdów (np. ze swojej bazy danych lub ze sklepu internetowego), możesz skorzystać z przycisku [Wklej listę modeli]. Wyświetlimy wtedy dodatkowe okno, w którym możesz wkleić swoją listę pojazdów. Z każdego modelu z twojej listy utworzymy pojedynczą pozycję w sekcji Pasuje do.

- Jeśli rozpoznamy dany model, zaznaczymy pole na zielono
- Jeśli nie rozpoznamy modelu, zaznaczymy go na czerwono. Wszystkie nierozpoznane modele znajdziesz w górnej części listy. Gdy klikniesz w taki model, podpowiemy ci kilka modeli, z których możesz wybrać odpowiedni. Zaznaczymy też te, które zostały już poprawnie dodane.

**Comment by kfijalko** [comment]
o, no to ładnie

**Comment by emteusz** [comment]
ogólnie można by to w łatwy sposób rozwiązać, mianowicie podczas dodawania oferty/aukcji z produktem, i po wpisaniu numeru czesci oraz producenta, zeby allegro odpytywało tecdoca i warunek- jeśli widnieje w tecdocu - aby pobrał automatycznie liste zastosowania, jeśli nie, zeby zostawił pole puste.. i sprawa rozwiazana

**Comment by TomekKaczmarek** [comment]
@emteusz dzięki za sugestię - przekazuję do odpowiedniego zespołu.
