### ISSUE TITLE
Wolne działanie systemu

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#2011]
Od swojego klienta, dla którego opracowałem integrację z Allegro, otrzymałem prośbę o zgłoszenie następującego problemu:

Zauważyliśmy że proces wystawiania aukcji czy to "ręcznie" czy też za pomocą rest api przez ostatnie dni włącznie z dniem dzisiejszym jest niezwykle utrudniony. Aukcja po jej wystawieniu nie pojawia się a jak się pojawi w Moich ofertach to trwa to około 10 minut albo po tym czasie jest w szkicach.
Utrudnia to mozliwość edytowania aukcji i dodawania kolejnych. Czyszczenie historii przeglądania i plików cookies nie rozwiązują problemu.

Edit:

dodam, że komunikacja działa bez blędów, Allegro REST API przyjmuje wszystkie komendy czy to zmian cen, wznawiania, czy publikacji bez błędów, po prostu realizacja tych komend do po stronie Allegro trwa znacznie dłużej niż wcześniej.

**Comment by SebastianOzdoba** [comment]
potwierdzam, u mnie podobnie, szkice pojawią się ze znaczącym opóźnieniem nawet 30-40 minut

**Comment by kfijalko** [comment]
U mnie lecą 5xx przy pobieraniu info o ofertach https://api.allegro.pl/sale/offers?limit=500&offset=72500.
Standardowo jest <100 dziennie. na chwile obecną już jest 100.

**Comment by PrzemyslawLukanowski** [comment]
@tztztztz Zweryfikowałem to - wystawienie przez front zajęło 5 minut (zgłosiłem problem do odpowiedniego zespołu), jednak przez API oferta została aktywowana od razu. Jeśli problem wystawiania przez API nadal ma miejsce, prześlij proszę przykładowe numery ofert.
@SebastianOzdoba - czy problem wciąż występuje? 
@kfijalko - prześlij proszę za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) login usera, do którego należą oferty, zweryfikujemy to. W zgłoszeniu dopisz GitHub #2011.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski dziś nie, jeśli będzie odezwę się

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski dziś nie mam ani jednego błędu 50x. to trochę podejrzane.

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski czy możesz sprawdzić zadanie zmiany liczy sztuk w ofercie:
https://api.allegro.pl/sale/offer-publication-commands/30f34800-ae8d-11e9-b1fe-cd2b385298db/tasks
zadanie zlecone 2019-07-25T03:35:04.757Z do tej pory się nie wykonało, raport detaliczny:
```
{
    "tasks": [
        {
            "offer": {
                "id": "xxxxxxxxxxx"
            },
            "message": null,
            "status": "NEW",
            "scheduledAt": "2019-07-25T03:35:04.757Z",
            "finishedAt": null,
            "field": "quantity",
            "errors": []
        }
    ]
}
```

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski 
wywołałem https://api.allegro.pl/sale/offer-publication-commands/b19630b0-aeb6-11e9-ab46-1d47abf80a48/tasks
w polu offer_id mam uui zamiast int'a

```
{
    "tasks": [
        {
            "offer": {
                "id": "c277bb40-ae63-11e9-bc0a-71484d2c66cc"
            },
            "message": "Could not change offer publication status.",
            "status": "FAIL",
            "scheduledAt": "2019-07-25T08:32:09.974Z",
            "finishedAt": "2019-07-25T08:32:10.062Z",
            "field": "publication",
            "errors": [
                {
                    "code": "NotFoundException",
                    "message": "HTTP 404 Not Found",
                    "details": "NotFoundException",
                    "path": null,
                    "userMessage": null
                }
            ]
        }
    ]
}
```

**Comment by PrzemyslawLukanowski** [comment]
@kfijalko Zweryfikowałem to i status to w dalszym ciągu NEW. Zgłosiłem problem do odpowiedniego zespołu.
