### ISSUE TITLE
Parameter (395) is not expected.(HTTP ERROR 422) Parameter (395) is not expected.

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#2012]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

TraceID: 70778245d524d217

Przy aktualizowaniu aukcji, allegro zwraca odpowiedź:
```
array (
        'code' => 'VALIDATION_ERROR',
        'path' => '',
        'details' => '',
        'message' => 'Parameter (395) is not expected.',
        'userMessage' => 'Parameter (395) is not expected.',
      ),
```

mimo, że ten parametr jest wymagany (również przy ręcznym wystawieniu)
Szczegóły (request i response) wysłane przez formularz.

**Comment by PrzemyslawLukanowski** [comment]
@radoslawkoziol Zweryfikowałem to i wymagane parametry w tej kategorii to:
```
"id": "11323",
"name": "Stan",
```
```
"id": "127908",
"name": "Rodzaj czujnika",
```
```
"id": "17448",
"name": "Waga (z opakowaniem)",
```
```
"id": "219809",
"name": "Kod produktu",
```

Możesz to sprawdzić za pomocą zasobu [GET sale/categories/{categoryId}/parameters.](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2)

**Comment by radoslawkoziol** [comment]
@PrzemyslawLukanowski Kiedy to sprawdzałem dostawałem zwrot z "Rodzaj czujnika", ale pod ID 395. Jak rozumiem powstała jakaś zmiana?

**Comment by PrzemyslawLukanowski** [comment]
@radoslawkoziol W zgłoszeniu przesłałeś numer oferty, która wystawiony jest w kategorii Czujniki, tymczasem powyższy screen dotyczy Detektorów, gdzie parametr 395 jak najbardziej istnieje.
