### ISSUE TITLE
przykład wywołania WebAPI za pomocą CURL

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2013]
Podczas pisania aplikacji korzystam z REST API tak jak zaleca Allegro. Niestety jeszcze nie wszystko można zrobić z REST API. Nigdy nie robiłem nic z SOAP i WSDL, a w tutorialach znalazłem tylko przykłady do SDK PHP.  

Czy mógłby ktoś podesłać przykład wywołania za pomocą CURL'a jakiejś metody np. doLoginWithAccessToken i doGetItemsInfo czy doShowUser.

Niestety jeszcze przez dłuższy czas będzie trzeba używać obu API.

**Comment by Patryk27** [comment]
Wysyłanie zapytań SOAP za pomocą cURLa to samobójstwo - [tutaj](https://dasunhegoda.com/make-soap-request-command-line-curl/596/) masz ogólny przykład, lecz **nie rób tego ręcznie**.

Praktycznie każdy popularny język zawiera zestaw bibilotek, które możesz wykorzystać do komunikacji SOAP - poszukaj odpowiednich dla Twojej sytuacji.

**Comment by crazyhtm** [comment]
Bardzo dziękuję za ostrzeżenie i ogólny przykład. 
Minie bardziej chodziło o to jak wyglada przykładowy XML do metody np. doLoginWithAccessToken i doGetItemsInfo czy doShowUser. Bo nigdzie nie mogę znaleść.

Ale źle się wyraziłem przepraszam.

**Comment by crazyhtm** [comment]
Z drugiej strony, nie bardzo rozumiem dlaczego stworzenie takiego zapytania jak poniżej miałoby być samobójstwem i co trudnego w zrobieniu tego ręcznie?
Oczywiście jak sie ma jakiś przykład.  

**curl -H "Content-Type: text/xml" -d '<?xml version="1.0" encoding="utf-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:main="https://webapi.allegro.pl/service.php" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <SOAP-ENV:Body> <main:DoGetUserLoginRequest> <main:countryId>1</main:countryId> <main:userId>000000000</main:userId> <main:webapiKey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</main:webapiKey> </main:DoGetUserLoginRequest> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' https://webapi.allegro.pl/service.php**

Mam pytanie, czy można wymusić odpowiedź w formacie JSON?
Próbowałem header "Accept: application/vnd.allegro.public.v1+json" ale bez skutku.

**Comment by Patryk27** [comment]
> nie bardzo rozumiem dlaczego stworzenie takiego zapytania jak poniżej miałoby być samobójstwem i co trudnego w zrobieniu tego ręcznie?

SOAP jest relatywnie skomplikowanym protokołem (w porównaniu do np. REST po JSONie), ponieważ wszystkie żądania muszą być zbudowane zgodnie z wytycznymi zawartymi w WSDLu - daje to zwyczajnie ogrom średnio czytelnego boilerplate'u, którego niemal nie da się napisać z palca.

... co potwierdzasz sam pytaniem `jak powinna wyglądać itemsIdArray` ;-)

Ale, coby nie wyjść na niemiłego, odpowiedzią byłoby: spójrz do [WSDLa](https://webapi.allegro.pl/service.php?wsdl) i zobacz, jakiego typu jest oczekiwana wartość. W tym wypadku `itemsIdArray` to `tns:ArrayOfLong`, którego definicja prezentuje się tak:

```xml
<xsd:complexType name="ArrayOfLong">
  <xsd:sequence>
    <xsd:element name="item" type="xsd:long" minOccurs="0" maxOccurs="unbounded"/
  </xsd:sequence>
</xsd:complexType>
```
Jak to zreprezentować w żądaniu SOAP? Bóg wie - trzeba by zerknąć do standardu.

> czy można wymusić odpowiedź w formacie JSON?

Nie - SOAP komunikuje się wyłącznie po XMLach.

> Ciągle brak przykładów.

Przykładów nie ma, bo nikt nie pisze tych zapytań ręcznie.

**Comment by crazyhtm** [comment]
Próbuję wykorzystać "doGetItemsInfo" lub "doShowItemInfoExt" do pobrania opisów aukcji. "doLoginWithAccessToken" do pobrania sessionHandle i "doGetUserLogin" do pobrania userLogin już rozpracowałem i działa!

Z WebAPI potrzebuję tylko opisu aukcji,  nie ma jak tego pobrać za pomocą REST, chyba że czegoś nie doczytałem :) ale chyba nie. Nie chciałem tracić czasu na walkę z jakąś biblioteką której nigdy więcej nie będę potrzebował.   

Niestetety komplikacja pojawiła się przy "itemsIdArray", w "doGetItemsInfo".
Muszę podać id aukcji ale niestety jako tablicę, chyba się zgodzisz że uczenie się SOAP lub szukanie i uczenie się nowej biblioteki czy zmiany w aplikacji żeby wpisać jeden numer jako tablicę i zmieniać to za 3 czy 4 miesiące (bo potem i tak wyłączycie WebAPI) to strata czasu. 
Dlatego poprosiłem o pomoc. Rozumiem że nikt nie chce robić tego ręcznie i nie dziwię się.

**Comment by Patryk27** [comment]
> Nie chciałem tracić czasu na walkę z jakąś biblioteką której nigdy więcej nie będę potrzebował.

W zamian tego wolisz tracić czas na ręcznie klepanie zapytań SOAP, których nigdy więcej nie będziesz potrzebował?

Zresztą skąd ta pewność, że nigdy w życiu nie zobaczysz już soapowego API? :-)

> chyba się zgodzisz że uczenie się SOAP lub szukanie i uczenie się nowej biblioteki czy zmiany w aplikacji żeby wpisać jeden numer jako tablicę i zmieniać to za 3 czy 4 miesiące (bo potem i tak wyłączycie WebAPI) to strata czasu.

Nie, nie zgodzę się - w aktualnym projekcie tak właśnie zrobiliśmy i mamy tymczasowo obydwie integracje za pomocą automatycznie wygenerowanych klientów (jeden na podstawie WSDLa, a drugi - Swaggera).

Wygenerowanie klienta i połączenie go z resztą systemu zajęło kilka godzin - w porównaniu do kilku dni, które można stracić (i prawdopodobnie stracisz) próbując wykonać to zapytanie z palca.

Robisz sobie sam pod górkę :-P

**Comment by crazyhtm** [comment]
To możesz mi pomóc (wiesz jak napisać to zapytanie) czy nie? 
Goście z eBay'a mogli podać przykłady wywołań w XML i JSON. Nikt nie widział w tym problemu.
Ja potrzebuję napisać jedno zapytanie do WebAPI. Jakby były przykłady tak jak w REST to bym nigdy o nic nie pytał.

**Comment by Patryk27** [comment]
Niestety nie jestem w stanie pomóc.

**Comment by crazyhtm** [comment]
Szkoda, ale dziękuję za chęci!

**Comment by pkrzemo** [comment]
@Patryk27 

> Ale, coby nie wyjść na niemiłego, odpowiedzią byłoby: spójrz do [WSDLa](https://webapi.allegro.pl/service.php?wsdl) i zobacz, jakiego typu jest oczekiwana wartość. W tym wypadku `itemsIdArray` to `tns:ArrayOfLong`, którego definicja prezentuje się tak:
> 
> ```
> <xsd:complexType name="ArrayOfLong">
>   <xsd:sequence>
>     <xsd:element name="item" type="xsd:long" minOccurs="0" maxOccurs="unbounded"/>
>   </xsd:sequence>
> </xsd:complexType>
> ```
> 
> Jak to zreprezentować w żądaniu SOAP? Bóg wie - trzeba by zerknąć do [specyfikacji](https://www.w3.org/TR/2007/REC-soap12-part0-20070427/) - good luck.

A co w tym trudnego jeśli ma się xsd?

gdzieś jest zapewne użyty ten typ danych np.
 <xsd:element name="MojaTablica" type="ArrayOfLong" />

co się przekłada np. na coś takiego:

<MojaTablica>
  <item>212121</item>
  <item>223431</item>
  <item>542343</item>
  <item>212423</item>
</MojaTablica>

minOccurs="0"  oznacza że może nie być żadnego elementu "item" np. <MojaTablica></MojaTablica>
maxOccurs="unbounded" oznacza że nie ma górnego limitu elementów "item"
<xsd:sequence> oznacza listę elementów
<xsd:complexType> oznacza definicję typu złożonego (składającego się z innych elementów)

czyli element itemsIdArray skoro jest typu ArrayOfLong powinien wyglądać np. tak:
<itemsIdArray>
  <item>212121</item>
  <item>223431</item>
  <item>542343</item>
  <item>212423</item>
</itemsIdArray>

**Comment by crazyhtm** [comment]
**Super, piękne dzięki !!!**
Poniżej wywołanie cURL'a metody "DoGetItemsInfoRequest" dla jednej aukcji żeby dostać jej opis, jakby ktoś szukał tak jak ja:

`curl -H "Content-Type: text/xml" -d '<?xml version="1.0" encoding="utf-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:main="https://webapi.allegro.pl/service.php" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <SOAP-ENV:Body> <DoGetItemsInfoRequest> <sessionHandle>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</sessionHandle> <itemsIdArray> <item>123456789</item> </itemsIdArray> <getDesc>1</getDesc> </DoGetItemsInfoRequest> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' https://webapi.allegro.pl/service.php`


A sessionHandle można uzyskać za pomocą "DoLoginWithAccessTokenRequest" (oczywiście potrzebny jest access_token pozyskany przez REST API)

`curl -H "Content-Type: text/xml" -d '<?xml version="1.0" encoding="utf-8"?> <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:main="https://webapi.allegro.pl/service.php" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"> <SOAP-ENV:Body> <DoLoginWithAccessTokenRequest> <accessToken>xxxxxxxxxxxxxxxxxxxxxx</accessToken> <countryCode>1</countryCode> <webapiKey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</webapiKey> </DoLoginWithAccessTokenRequest> </SOAP-ENV:Body> </SOAP-ENV:Envelope>' https://webapi.allegro.pl/service.php`
