### ISSUE TITLE
[restAPI] Pilne nie działa sale/offers - bład 400

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2014]
Występuje problem: 
 - [ X ] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od teraz występuje błąd 400

REQUEST 2019-07-24 15:03:48.6691978
curl -X POST \
  'https://api.allegro.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"0bb1a03f-8620-40c1-80ab-57393d6552eb"},"returnPolicy":{"id":"a1321559-5034-48a9-aa6b-526c5a76fcc1"},"warranty":{"id":"6cbe0741-5318-41a4-8de7-62b399c01b02"}},"category":{"id":"111852"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":{"additionalInfo":"Przy zakupach powyżej 400 zł przesyłkę realizujemy bezpłatnie na terenie całego kraju. Możliwy jest także bezpłatny odbiór osobisty w naszym oddziale biura handlowego w Łodzi. Po uprzednich indywidualnych ustaleniach jest również możliwy odbiór osobisty w naszym oddziale biura handlowego w Warszawie.","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"dcdc7806-585b-4bb2-a42e-b13889a3c557"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>@ProductName@</h1>\r\n\r\n<p><b>Producent:</b>&nbsp;@ProducerName@ |&nbsp;<b>Marka:</b>&nbsp;@BrandName@</p>\r\n\r\n<p><b>Kod produktu:&nbsp;</b>@ProductCode@</p>\r\n\r\n<p>&nbsp;</p>\r\n"}]},{"items":[{"type":"IMAGE","url":null},{"type":"TEXT","content":"<h1>Opis</h1>\r\n\r\n<p>@ProductDescription@</p>\r\n"}]},{"items":[{"type":"TEXT","content":"<p>@ProductDescription@</p>\r\n"},{"type":"IMAGE","url":null}]}]},"ean":null,"external":{"id":"templateId"},"id":null,"images":[{"url":null}],"location":{"city":"Łódź","countryCode":"PL","postCode":"93-232","province":"LODZKIE"},"name":"draft_2019.7.24.15.3.48.606","parameters":[{"id":"11323","rangeValue":null,"values":null,"valuesIds":["11323_1"]}],"payments":{"invoice":"VAT"},"product":null,"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"100000.00","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":1,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

RESPONSE 2019-07-24 15:03:48.6847923 Duration: 15,5945ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ERROR",
        "Details": null,
        "Message": "An error has occurred",
        "Path": "/sale/offers",
        "UserMessage": null
      }
    ],
    "ValidatedAt": null
  },
  "Exception": null,
  "TraceId": "8ce4ccac3efc060b",
  "Error": true,
  "StatusCode": 400,
  "Message": "{\"errors\":[{\"code\":\"ERROR\",\"message\":\"An error has occurred\",\"details\":null,\"path\":\"/sale/offers\",\"userMessage\":null}]}"
}

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba W description dla type IMAGE jako url przekazujesz null, stąd błąd 400.

**Comment by SebastianOzdoba** [comment]
Dorzucam dodatkowy request

REQUEST 2019-07-24 15:37:16.8564434 
curl -X POST \
  'https://api.allegro.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"0bb1a03f-8620-40c1-80ab-57393d6552eb"},"returnPolicy":{"id":"a1321559-5034-48a9-aa6b-526c5a76fcc1"},"warranty":{"id":"6cbe0741-5318-41a4-8de7-62b399c01b02"}},"category":{"id":"260162"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":{"additionalInfo":"Przy zakupach powyżej 400 zł przesyłkę realizujemy bezpłatnie na terenie całego kraju. Możliwy jest także bezpłatny odbiór osobisty w naszym oddziale biura handlowego w Łodzi. Po uprzednich indywidualnych ustaleniach jest również możliwy odbiór osobisty w naszym oddziale biura handlowego w Warszawie.","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"dcdc7806-585b-4bb2-a42e-b13889a3c557"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Tork - Czyściwo papierowe w roli, 2-warstwowe, W1, premium - Białe</h1>\r\n\r\n<p><b>Producent:</b>&nbsp;Essity |&nbsp;<b>Marka:</b>&nbsp;Tork</p>\r\n\r\n<p><b>Kod produktu:&nbsp;</b>130045</p>\r\n\r\n<p>&nbsp;</p>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/119a82/60d8fe7241b1859b0411138f8361"},{"type":"TEXT","content":"<h1>Opis</h1>\r\n\r\n<p>Tork - Czyściwo papierowe w roli, 2-warstwowe, W1, premium - Białe Wysokiej jakości czyściwo papierowe marki Tork , światowego potentata na rynku profesjonalnych produktów higienicznych. Produkt zaprojektowany został przede wszystkim z myślą o fachowym zastosowaniu i kosmunentach, dla których wygoda i efektywność pracy stanowią priorytet. Skład czyściwa oparty jest na bazie najlepszej jakości celulozy oraz ekologicznej makulatury, których połączenie w nowoczesnej technologii QuickDry gwarantuje niezwykłą chłonność i wytrzymałość. Dodatkowo, oprócz wysokiej funkcjonalności czyściwo odznacza się także przyjemną w dotyku, miękką fakturą, która znacząco wpłynie na komfort pracy. Produkt cieszy się ogromnym zaufaniem klientów także przez wzgląd na wszechstronne pole zastosowań. Sprawdzi się perfekcyjnie w przypadku wszystkich zadań związanych z czyszczeniem nawet silnie zabrudzonych powierzchni czy zbieraniem rozlanych płynów, bądź również w przypadku wycierania rąk. Czyściwo może być stosowane w kontakcie z żywnością. Kompatybilne produkty Czyściwo współpracuje jedynie z dozownikami marki Tork w systemie W1 Parametry System: W1 - System naścienny/stojakowy Długość rolki: 510 m Szerokość rolki: 23,5 cm Średnica rolki: 39 cm Warstwy: 2 Liczba odcinków: 1500 Długośc odcinka: 34 cm Nadruk: nie Tłoczenie: tak Kolor: biały Opakowanie: 1 sztuka</p>\r\n"}]},{"items":[{"type":"TEXT","content":"<p>Tork - Czyściwo papierowe w roli, 2-warstwowe, W1, premium - Białe Wysokiej jakości czyściwo papierowe marki Tork , światowego potentata na rynku profesjonalnych produktów higienicznych. Produkt zaprojektowany został przede wszystkim z myślą o fachowym zastosowaniu i kosmunentach, dla których wygoda i efektywność pracy stanowią priorytet. Skład czyściwa oparty jest na bazie najlepszej jakości celulozy oraz ekologicznej makulatury, których połączenie w nowoczesnej technologii QuickDry gwarantuje niezwykłą chłonność i wytrzymałość. Dodatkowo, oprócz wysokiej funkcjonalności czyściwo odznacza się także przyjemną w dotyku, miękką fakturą, która znacząco wpłynie na komfort pracy. Produkt cieszy się ogromnym zaufaniem klientów także przez wzgląd na wszechstronne pole zastosowań. Sprawdzi się perfekcyjnie w przypadku wszystkich zadań związanych z czyszczeniem nawet silnie zabrudzonych powierzchni czy zbieraniem rozlanych płynów, bądź również w przypadku wycierania rąk. Czyściwo może być stosowane w kontakcie z żywnością. Kompatybilne produkty Czyściwo współpracuje jedynie z dozownikami marki Tork w systemie W1 Parametry System: W1 - System naścienny/stojakowy Długość rolki: 510 m Szerokość rolki: 23,5 cm Średnica rolki: 39 cm Warstwy: 2 Liczba odcinków: 1500 Długośc odcinka: 34 cm Nadruk: nie Tłoczenie: tak Kolor: biały Opakowanie: 1 sztuka</p>\r\n"},{"type":"IMAGE","url":null}]}]},"ean":"7322540182279","external":{"id":"130045"},"id":null,"images":[{"url":"https://a.allegroimg.com/original/119a82/60d8fe7241b1859b0411138f8361"},{"url":null}],"location":{"city":"Łódź","countryCode":"PL","postCode":"93-232","province":"LODZKIE"},"name":"Tork -  Czyściwo papierowe w roli, 2-warstwowe, W1","parameters":[{"id":"11323","rangeValue":null,"values":null,"valuesIds":["11323_1"]}],"payments":{"invoice":"VAT"},"product":null,"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"101.40","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":1,"unit":"UNIT"},"updatedAt":null,"validation":null}' \

RESPONSE 2019-07-24 15:37:17.1845957 Duration: 328,1523ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ERROR",
        "Details": null,
        "Message": "An error has occurred",
        "Path": "/sale/offers",
        "UserMessage": null
      }
    ],
    "ValidatedAt": null
  },
  "Exception": null,
  "TraceId": "b7026d8a8bac2eed",
  "Error": true,
  "StatusCode": 400,
  "Message": "{\"errors\":[{\"code\":\"ERROR\",\"message\":\"An error has occurred\",\"details\":null,\"path\":\"/sale/offers\",\"userMessage\":null}]}"

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba  W tym przypadku w jednym miejscu również jest przekazywany null dla url w "type": "IMAGE".

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski fakt, zdjęcia znow są niepoprawne

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski sandbox i produkcja działają inaczej
Na sandbox takie coś przejdzie walidację, na produkcji już nie

Co więcej na produkcji to też działało do dziś, więc wprowadziliście jakieś zmiany
