### ISSUE TITLE
Błąd InPost: "Niespójne identyfikatory użytkownika oraz transakcji Allegro"

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#2015]
Dzień dobry,

wiem, że to pytanie bardziej do InPost-a, ale może będą Państwo w stanie wskazać co jest nie tak.

Kiedy próbuję stworzyć paczkę w InPost przez ich API, korzystając z dostawy "Allegro InPost", podając wymagane dane:  numer użytkownika, id transakcji, oraz adres kupującego, otrzymuję w odpowiedzi błąd z InPost: "Niespójne identyfikatory użytkownika oraz transakcji Allegro"

Oto zapytanie i odpowiedź, wrażliwe dane zostały zanonimizowane:
```
https://api.paczkomaty.pl/?do=createdeliverypacks

[XML sent]:
<paczkomaty>
<autoLabels>0</autoLabels>
<selfSend>0</selfSend>
<pack><id>784843</id>
<addresseeEmail>1111111111111111111@allegromail.pl</addresseeEmail>
<senderEmail>111111@111111.pl</senderEmail>
<phoneNum>1111111111111</phoneNum>
<boxMachineName>BBI12A</boxMachineName>
<packType>A</packType>
<customerRef>1111111111111</customerRef>

<allegro>
<userId>111111111111111</userId>
<transactionId>6122a6a2-ae23-11e9-9291-2dc19f070ccc</transactionId>
</allegro>
<receiverAddress><name><![CDATA[Agnieszka]]></name>
<surName><![CDATA[Testowa]]></surName>
<street><![CDATA[testowa]]></street>
<buildingNo>3</buildingNo>
<town><![CDATA[Testowe]]></town>
<zipCode>11-111</zipCode>
</receiverAddress>
</pack>
</paczkomaty>

[XML received]:
<?xml version="1.0" encoding="UTF-8"?><paczkomaty><pack><id>784843</id><error key="basicAllegroDataMismatch">Niespójne identyfikatory użytkownika oraz transakcji Allegro</error></pack></paczkomaty>
```
Oczywiście w zawartość tagu <userId> to prawidłowy id użytkownika, jedynki to anonimizacja.

Naprawdę trudno coś innego tutaj wymyślić, bo to jedyny numer płatności i id użytkownika, jaki się pojawia w danych Checkout Form pobranych z Allegro przez REST API.

Próbowałem zamiast numerycznego id użyć loginu lub emailu, ten sam efekt - być może wie ktoś o co tutaj chodzi, w czym tkwi błąd?

**Comment by pawelosajda** [comment]
Prawdopodobnie powinieneś skorzystać z mappingu
https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping

**Comment by tztztztz** [comment]
Niestety teraz otrzymuję błąd: "allegroTransactionNotFound" używając tego indentyfikatora transactionId ktory otrzymuje w opowiedzi na komendę https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping

Od płatności minęło około 19 godzin - ale to chyba nie jest przyczyną?

**Comment by pawelosajda** [comment]
Testujesz to na sandboxach Allegro i InPostu? Jeśli tak to może to nie działać z tego co pamiętam musiałem to przetestować na produkcji jakieś pół roku temu.

**Comment by tztztztz** [comment]
Nie to jest testowane live, na produkcyjnym koncie allegro i produkcykjnym koncie inpost, z realną płatnością kartą kredytową.

**Comment by tztztztz** [comment]
Tutaj wynik komendy pobrania TransactionID:

$cmd->lastResponseCode = 200

stdClass Object
(
    [paymentId] => 6122a6a2-ae23-11e9-9291-2dc19f070ccc
    [transactionId] => 1050934335
)

**Comment by tztztztz** [comment]
Skorzystałem jeszcze ze starego WebApi aby pobrać "post-buy-form-pay-id", jego zastosowanie jako id transakcji w zapytaniu do InPost też nic nie daje, ten sam efekt. Czy jest jakiś sposób żeby to działało?

**Comment by tztztztz** [comment]
Identyfikator użytkownika allegro to 11884571, a id transakcji po konwersji z getPaymentIdMapping 1050934335, dla tej pary uzytkownika i id transakcji, InPost zwraca błąd "allegroTransactionNotFound".

Podobnie dla pary: 11884571 i 1411896485  - to id z InPostu z pola "post-buy-form-pay-id", pobrane metodą doGetPostBuyFormsDataForSellers dla transakcji 1050934335

**Comment by tztztztz** [comment]
Ok problem rozwiązany, zamiast id kupującego trzeba podać id sprzedającego. Oczywiście nigdzie się tego nie można doczytać, "dzięki wielkie" za stracony czas i nerwy.
