### ISSUE TITLE
[Na poranek]: Podajecie nieprawdę - E.P. /sale/offers vs 30 dni

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#2016]
W kilku odpowiedziach dotyczących tego zasobu i wybranych wartości przez niego zwracanych (saleInfo:biddersCount, stock:sold, stats:watchersCount, stats:visitsCount) podajecie od dłuższego nieprawdę. Jakkolwiek trzy z wymienionych wartości dotyczą faktycznie ostatnich 30 dni (dób), to wartość 'stats:watchersCount' wcale się NIE PRZEDAWNIA i nie redukuje w cyklu 30-dobowym.
p.s.
Tak przy okazji tego - kiedy można liczyć na uzupełnienie całej tablicy "offers":[...] o wartości:
- saleInfo:biddersTotalCount ?
- stock:soldTotal ?
- stats:visitsTotalCount ?
Na tym Waszym "froncie" sprzedający powinien mieć natychmiast możliwość przełączania się z aktualnego trybu "30 dni" - na tryb nielimitowany czasem, listingi dla kupujących bez zmian...

**Comment by PrzemyslawLukanowski** [comment]
Wartość stats.watchersCount jest odzwierciedleniem tego, co user widzi na froncie:
![1](https://user-images.githubusercontent.com/51473661/61864326-84beb780-aed1-11e9-9d01-c973de599bc5.png)
Ilość obserwujących nie dotyczy ostatnich 30 dni, jest to aktualna wartość.

> Tak przy okazji tego - kiedy można liczyć na uzupełnienie całej tablicy "offers":[...] o wartości:
> 
> saleInfo:biddersTotalCount ?
> stock:soldTotal ?
> stats:visitsTotalCount ?

Na chwilę obecną nie planujemy dodania takich pól, zgłosiłem to do odpowiedniego zespołu jako sugestię.

**Comment by FromAnyHole** [comment]
@PrzemyslawLukanowski - można znaleźć co najmniej trzy Wasze odpowiedzi z ostatniego okresu, w których wszystkie te wartości traktujecie tak samo, a jest inaczej i to dopiero pierwsza poprawna informacja.
p.s.
Proponowane wyżej wartości powinny dostać wysoki priorytet, a i sprzedający tego potrzebują !

**Comment by PrzemyslawLukanowski** [comment]
Tak jak pisałem, przekazałem sugestię. Jeżeli zdecydujemy się na jej wdrożenie, poinformujemy o tym w odpowiednim komunikacie.

**Comment by FromAnyHole** [comment]
Priorytet !! ;-)
