### ISSUE TITLE
Znów wracamy do FID! czyli powtórka z rozrywki dublowania tych samych wartości

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#2018]
Szanowni Państwo Allegro: chciałem zaznaczyć że twierdziliście że problem FID w WebApi zostanie rozwiązany w REST, że dla tych samych parametrów będzie ten sam numer parametru (czyli id). No i co już po 1 dniu wystawiania okazuje się że np dla kategorii 261210 parametr okładka ma id 7773 a dla kategorii 111819 parametr okładka ma id 75 z tymi samymi wartościami słownikowymi tylko w innej kolejności.
Oto przykład dla dwóch w/w kategorii: 
parametr Okładka: id:  75_  oraz id; 7773_
odpowiednio wartości słownikowe:
1 miękka		                             ;1 miękka
3 miękka +obw		             ;3 twarda	
306417 miękka ze skrzydełkami    ;305805 miękka ze skrzydełkami 
2 twarda                                       ;2 miękka z obwolutą
4 twarda z obwolutą                     ;4 twarda z obwolutą
5 zintegrowana                             ;5 zintegrowana
314838 inna                                 ;brak odpowiednika
No ja rozumiem że w książkach kryminalnych (id kat 261210)  nie może być innej okładki (a w sumie to nie rozumiem choć prowadzę antykwariat 10lat) zatem trzeba było wprowadzić nowy id i namieszać w kolejności słownikowej. 
Ja bym to rozwiązał tak: stałe id 75 i stałe wartości rozszerzane do woli lub część wartości słownikowych wykluczone. Parametr jest banalny "okładka" oprócz wersji elektronicznej to wszystkie książki mają jakąś okładkę lub niektóre używano mogą jej nie mieć. Koniec problemu filozofi okładki. Sprawa banalna a tu takie jaja. Tego nie dało się zepsuć (nie chce już pisać wulgarnych słów). Ale Wy to zrobiliście. 
 
Moja prośba jest jedna: ogarnijcie się bo już przestaje być to zabawne. Czy ktokolwiek widzi sens w tym co zostało w tym przypadku zrobione? Dla mnie również jako programisty powoduje to kolejną bezsensowną pracę analogiczną jak dodawanie fidów tylko z dwojga złego tam (webApi) jak dodałeś do requesta id:75_ i id:7773_ razem to chociaż błędu nie wywalało a tu błąd. Proszę o komentarz, może jestem w błędzie.

**Comment by TimothyKoval** [comment]
Szukaj dalej, znajdziesz parametry o identycznym id, ale przyjmujące różne wartości w zależności od kategorii :)

**Comment by marcinja2** [comment]
SEPUKU mi chyba tylko zostaje

**Comment by PrzemyslawLukanowski** [comment]
@marcinja2 Pracujemy nad tym, parametry zostaną ujednolicone.

**Comment by marcinja2** [comment]
dziękuję za odpowiedź, mam nadzieję że tak się stanie, i jakby chcieć narzekać dalej.... znów będzie robota i odwracanie wszystkiego. Czy cokolwiek wiadomo kiedy może to się stać?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie jesteśmy w stanie podać konkretnego terminu.

**Comment by marcinja2** [comment]
temat zamykam ale będę czujny :)
