### ISSUE TITLE
Hurtowa zmiana ofert - nie działa?

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#202]
Witam,

Mam problem z wywołaniem hurtowej zmiany aukcji.

Żadanie `PUT` pod `sale/offer-modification-commands/8411c3eb-da94-4de2-a944-42fb651b0c15` z body:

```
{
  "modification": {
    "delivery": {
      "shipmentDate": "2018-05-22T08:00:00Z",
      "handlingTime": "PT24H",
      "shippingRates": {
        "id": "f01fbe47-f8aa-46ac-b2d1-e40f6e17ba13"
      }
    }
  },
  "offerCriteria": [
    {
      "type": "CONTAINS_OFFERS",
      "offers": [
        {
          "id": 7272454583
        }
      ]
    }
  ]
}
```

Odpowiedź:

```
{
  "id": "8411c3eb-da94-4de2-a944-42fb651b0c15",
  "taskCount": {
    "total": 0,
    "success": 0,
    "failed": 0
  }
}
```

Czyli jakby nic nie było zlecane.

Dodatkowo, wywołanie `GET` na `sale/offer-modification-commands/8411c3eb-da94-4de2-a944-42fb651b0c15/tasks` dostaje:

```
{
  "errors": [
    {
      "code": "ServiceTimeoutException",
      "message": "Gateway Time-out",
      "details": null,
      "path": null,
      "userMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
    }
  ]
}
```

**Comment by PawelTaberski** [comment]
Przetestowałem i rzeczywiście występuje jakiś problem sprawę przekazałem do odpowiedniego zespołu proszę o cierpliwość.

**Comment by dlis2010** [comment]
Podczas próby zmiany ceny przez REST API dostaję:
>[code] => QeppoResponseProcessingException
>[message] => Failed to process response from qeppo. Probably received HTML instead of JSON
>[details] => QeppoResponseProcessingException
>[path] => 
>[userMessage] => 

to coś u Was?

**Comment by KrzysztofStachyra** [comment]
Coś się chyba zmieniło bo do tej pory u mnie w aplikacji działało wszystko dobrze, przesyłałem w nagłówku zgodnie z dokumentacją content-type jako application/vnd.allegro.public.v1+json
a teraz dostaję zwrotkę 

{"errors":[{"code":"NotSupportedException","message":"HTTP 415 Unsupported Media Type","details":"NotSupportedException","path":null,"userMessage":null}]}

**Comment by PawelTaberski** [comment]
Jeśli mówimy o tej [metodzie do zmiany ceny](https://developer.allegro.pl/documentation/#!/default/put_offers_offerId_change_price_commands_commandId) to sprawdziłem i wszystko działa poprawnie i ceny zmieniają się na produkcji.

**Comment by PawelTaberski** [comment]
@pgasidlo Zaktualizowaliśmy dokumentacje tej metody i obecnie przy jej pomocy odnośnie wysyłki można tylko grupowo przypisać cennik dostawy. https://developer.allegro.pl/documentation/#!/offer/modificationCommandUsingPUT

**Comment by rtnet-pl** [comment]
@dlis2010 Kilku klientów zgłosiło mi podobny problem, tj. błąd "Failed to process response from qeppo. Probably received HTML instead of JSON" przy change-price-commands
Zatem Twój przypadek nie jest odosobniony.

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem problemu, prosimy o cierpliwość.

**Comment by rtnet-pl** [comment]
@PawelTaberski Czy udało się Wam coś ustalić?

**Comment by PawelTaberski** [comment]
@pgasidlo @rtnet-pl  Problem powinien być rozwiązany, jeśli u Was ciągle ten błąd się pojawia, podajcie proszę numery ofert przy jakich występuje.

**Comment by rtnet-pl** [comment]
@PawelTaberski Niestety problem nadal występuje, podaję przykładowe itemy:
7032838216
7032850555
7032888835
7032890948
7033818813
7033839681
7033840689
7033905853
7033963824
7034167108
7034252912
chodzi oczywiście o change price

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem numery ofert do odpowiedniego zespołu, zbadają w czym jest jeszcze problem.

**Comment by dlis2010** [comment]
@PawelTaberski niestety u mnie problem również dalej występuje, przykładowe oferty: 7240507478, 7240510713, 7240511574, 7238506052

**Comment by KrzysztofStachyra** [comment]
Przy okazji zapytam czy jednoczesna zmiana wielu aukcji w REST API też pozwala jednocześnie przekazanie 100 ofert czy limit jest zdjęty?

**Comment by PawelTaberski** [comment]
@dlis2010 Przekazałem numery ofert do osób odpowiedzialnych za poprawkę.

Odnośnie Twojego pytania @KrzysztofStachyra nie ma sztywnego limitu wszystko zależy od wielkości requesta 10 000 ofert powinno przejść.

**Comment by rtnet-pl** [comment]
@PawelTaberski Przypominam się z tematem, klienci naciskają na nas żebyśmy nacisnęli na Was ;)

**Comment by PawelTaberski** [comment]
@rtnet-pl Dostałem informację, że udało się namierzyć problem i poprawka powinna zostać wdrożona do końca tygodnia.

**Comment by rtnet-pl** [comment]
@PawelTaberski Czy są jakieś postępy?

**Comment by PawelTaberski** [comment]
@rtnet-pl Dostałem informację, że poprawka już została wdrożona i problem nie powinien już występować. Czy działa już u Ciebie poprawnie?

**Comment by rtnet-pl** [comment]
@PawelTaberski Dziękuję, mam pierwsze potwierdzenia, że problemu już nie ma.

**Comment by pgasidlo** [comment]
@PawelTaberski Nadal mam problem z hurtowym ustawieniem cennika dla aukcji. Przykładowo aukcja: `7306838403`. Wywołuje z metodę `PUT /sale/offer-modification-commands/4eafb869-42f0-4fc7-9649-307d096df492` z takim body:

```
{
  "modification": {
    "delivery": {
      "shippingRates": {
        "id": "209e293d-7120-41d7-9975-f30116578a41"
      }
    }
  },
  "offerCriteria": [
    {
      "type": "CONTAINS_OFFERS",
      "offers": [
        {
          "id": "7306838403"
        }
      ]
    }
  ]
}
```

Dostaje:

```
{
  "id": "4eafb869-42f0-4fc7-9649-307d096df492",
  "taskCount": {
    "total": 0,
    "success": 0,
    "failed": 0
  }
}
```

I zmiana nie dochodzi do skutku (patrze w panelu Allegro używając edytuj i dodatkowo poprzez wywołanie `GET /sale/offers/7306838403`
