### ISSUE TITLE
stock command 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2020]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

commandId 
9c1ec6b4-6e0d-4658-b56f-3d11b7208093

od godziny 10:51 , caly czas status NEW 
jest 13:21

**Comment by PrzemyslawLukanowski** [comment]
Znamy problem, zgłoszenie trafiło już do odpowiedniego zespołu.
