### ISSUE TITLE
następny commandId stock wisi 6h w status new 

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2021]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

commandId
058e2e3f-cdb5-454a-ba9b-17de83ed1b35

![image](https://user-images.githubusercontent.com/1530496/61874126-e9850c80-aee7-11e9-85b5-8c391ec266a5.png)

**Comment by PrzemyslawLukanowski** [comment]
Znamy problem, zgłoszenie trafiło już do odpowiedniego zespołu.

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski  dziś nie dostałem żadnego błędu 50X z listingów i szczegółów ofert. Wygląda tak jakbyście serwery z metod modyfikacyjnych przerzucili do obsługi listingów. Moja statystyka z dzisiejszych modyfikacji ofert. W szczególności zmiana liczby sztuk:

type | status_command | status_offer | liczba_ofert
-- | -- | -- | --
ACTIVATE_OFFER | SENDED | FAIL | 50592
ACTIVATE_OFFER | SENDED | SUCCESS | 29901
CHANGE_QUANTITY | SENDED | FAIL | 3665
CHANGE_QUANTITY | SENDED | NEW | 20525
CHANGE_QUANTITY | SENDED | SUCCESS | 8474
END_OFFER | SENDED | SUCCESS | 5642

**Comment by FromAnyHole** [comment]
Tabelka klasa !!

**Comment by kfijalko** [comment]
Dziś sytuacja jest o wiele lepsza:
1) zero błędów 50x
2) realizacja modyfikacji, zleconych dziś w nocy:

type | status_command| status_offer| liczba_ofert
-- | -- | -- | --
ACTIVATE_OFFER | SENDED | FAIL | 23
ACTIVATE_OFFER | SENDED | SUCCESS | 188
CHANGE_QUANTITY | SENDED | FAIL | 30
CHANGE_QUANTITY | SENDED | SUCCESS | 24507
END_OFFER | SENDED | SUCCESS | 832

**Comment by PrzemyslawLukanowski** [comment]
@kfijalko Wczoraj mieliśmy problemy techniczne, które powodowały błąd, dzisiaj nie powinien już występować.
