### ISSUE TITLE
[RestApi] Zwrot Prowizji

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2023]
Witam,
z tego co udało mi się ustalić zwrot prowizji  nie jest obsługiwany poprzez rest api, jest jedynie w web api.
Byłby to do przeżycia gdyby nie to że rest api nie daje identyfikatorów wymaganych przez web api. Oznacza to że pobierając zamówienia poprzez rest api nie mogę ich zgłosić do zwrotu prowizji w obu wersjach api.

Czy istnieje jakikolwiek sposób na zgłaszanie zwrotów prowizji poprzez api(obojętnie które) ale przy założeniu że zamówienie jest pobierane poprze rest api ?

**Comment by PrzemyslawLukanowski** [comment]
Na początku możesz skorzystać z [mapowania płatności](https://github.com/allegro/allegro-api/issues/1878) - paymentId z zamówienia REST API zamień na transactionId. Otrzymaną wartość przekaż w polu transactionsIdsArray w metodzie [doGetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703#method-output), w odpowiedzi otrzymasz m.in. dealId (identyfikator aktu zakupowego), który następnie możesz przekazać jako parametr wejściowy w [doSendRefundForm](https://allegro.pl/webapi/documentation.php/show/id,1403).
Wymagane sessionId dla dwóch powyższych metod otrzymasz przy pomocy [doLoginWithAccessToken](https://allegro.pl/webapi/documentation.php/show/id,101582#method-input), gdzie jako parametr wejściowy przekaż access token otrzymany poprzez autoryzację w REST API.

Zarządzanie zwrotami prowizji w REST API jest zaplanowane na IV kwartał 2019, informacje na ten temat znajdziesz w naszym [harmonogramie wygaszania](https://developer.allegro.pl/schedule/) WebAPI Allegro.

**Comment by mzawodzinski** [comment]
Proste jak świński ogon ;) 
W każdym razie działa

**Comment by deneb-k** [comment]
Odgrzebię temat, bo zabrałem się za usuwanie niedobitków z kodu. 13 stycznia wyłączacie doGetPostBuyFormsDataForSellers, a zarządzanie zwrotami prowizji na REST macie wpisane na bliżej nieokreślony pierwszy kwartał 2020. Trochę się to nie spina.
