### ISSUE TITLE
Globalny dostęp do listy ofert

### ISSUE THREAD

**Issue by zbjur** [allegro/allegro-api#2024]

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować zgłoszenie? Jeżeli masz na myśli wyszukiwanie i przeglądanie ofert, zapoznaj się [naszym poradnikiem](https://developer.allegro.pl/listing/) i zasobem [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).
