### ISSUE TITLE
Pytanie: dlaczego dana oferta ma status zakończona

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2027]
Witam,
Mam ofertę, dla której zostały wydane następujące polecenia:

command_id | type | status_command | scheduled_at | status_offer | old_quantity | new_quantity | old_state | new_state | result_message1
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
da8082c0-ae62-11e9-9b35-9990cd18b333 | ACTIVATE_OFFER | SENDED | 25.07.2019 00:32 | SUCCESS |   |   | 'END' | 'ACTIVATE' |  
e6017680-ae8c-11e9-bd48-41e8a6f441d8 | CHANGE_QUANTITY | SENDED | 25.07.2019 05:32 | NEW | 2 | 5 |   |   |  
a0b25930-af51-11e9-85d5-bde5f22b2ee3 | ACTIVATE_OFFER | SENDED | 26.07.2019 05:01 | FAIL |   |   | 'END' | 'ACTIVATE' | An error occurred while trying   to change the publication of the offer. Please try again later.#   CHANGE_PUBLICATION_STATUS_ERROR \| An error occurred while trying to change   the publication of the offer. Please try again later. \| \| \| An error occurred   while trying to change the publication of the offer. Please try again later.
fac45ec0-af55-11e9-8697-9fd6dd6d8fff | CHANGE_QUANTITY | SENDED | 26.07.2019 05:32 | FAIL | 2 | 5 |   |   | EXCEPTION_DURING_OFFER_QUANTITY_UPDATE#   ERR_ITEM_CAN_NOT_BE_RENEW \| ERR_ITEM_CAN_NOT_BE_RENEW \| \| \|

aktualnie oferta jest zakończona.
Proszę sprawdzić jak do tego doszło. Moje polecenia z powyższego:
1) wczoraj - aktywacja oferty zakończona sukcesem
2) wczoraj - zmiana ilości - nie została wykonana
3) dziś - ponowna aktywacja - zakończona błędem / niestety nie zapisuję jeszcze kiedy dane polecenie została wykonane. Ale skoro mój system postanowił wznowić ofertę to znaczy że nie otrzymał informacji iż jest aktywna.
4) dziś - zmiana ilości - zakończona błędem

efekt jest taki, że oferta ma status 'ENDED'. Tylko że takiego polecenia nie było, sprzedaży też, więc co się stało? Może pierwsze polecenie aktywacji wcale nie zmieniło statusu oferty tylko dało fałszywy wynik? Może w międzyczasie przyszło jakieś polecenie, o którym nie wiem?
Poproszę o analizę. Mam takich przypadków 30 sztuk.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - problem nastąpił już przy publikacji, mimo statusu “SUCCESS” przy pierwszym wywołaniu, oferta nie uzyskała statusu “ACTIVE”. Na froncie również widnieje informacja o zakończeniu w dniu 24.05.19. Zgłosiłem problem do odpowiedniego zespołu.
