### ISSUE TITLE
[RestApi] Pobieranie danych do faktury po nie udanej płatności

### ISSUE THREAD

**Issue by bartek171020** [allegro/allegro-api#2028]
W zamówieniach które mają niedokończoną (rozpoczętą) płatność, zdarzyło się już kilka razy, że klient np. przyjeżdża odebrać towar osobiście i płaci gotówką. Chcąc wprowadzić zamówienie do naszego systemu z RestAPI pobieram dane metodą order->checkout_forms(checkout_form_id)->get() dostaje następujące dane w sekcji invoice ([required] => 1, [address] => ''). Wskazywało by to na brak danych do faktury pomimo jej żądania (czyli błąd formularza albo co) jednak po wejściu przez interfejs serwisu dane te są widoczne.

Podsumowując przy niedokończonych płatnościach nie są zwracane dane do FV, pomimo iż zostały wprowadzone.
Uważam to za błąd, gdyż metoda powinna zwracać dane które są widoczne w systemie.

**Comment by PrzemyslawLukanowski** [comment]
W opisanej sytuacji oznaczałoby to udostępnienie danych do faktury dla statusu FILLED_IN - nie zwracamy tych danych w takim przypadku. Jeśli użytkownik ostatecznie skorzystał z innej formy płatności i dostawy, może w takim wypadku anulować płatność oraz wypełnić jeszcze raz formularz dostawy z opcją płatności przy odbiorze.

**Comment by bartek171020** [comment]
Jak klient sobie nie radzi z formularzem pozakupowym i nie umie anulować płatności (a zdarzają się tacy dość często) to musze ręcznie jechać z interfejsu, aby pomóc klientowi i zrealizować jego zamówienie.
To dlaczego dane te są widoczne w interfejsie allegro?
Skoro ich nie udostępniacie to proszę o konsekwencję. Niech nigdzie ich nie będzie widać i wtedy nie ma boga, musi wypełnić klient formularz i koniec, a takto tworzycie podwójne standardy (tu damy, a tu nie). Proszę jedynie o jednolitość.

**Comment by PhotoSoft** [comment]
> W opisanej sytuacji oznaczałoby to udostępnienie danych do faktury dla statusu FILLED_IN - nie zwracamy tych danych w takim przypadku. Jeśli użytkownik ostatecznie skorzystał z innej formy płatności i dostawy, może w takim wypadku anulować płatność oraz wypełnić jeszcze raz formularz dostawy z opcją płatności przy odbiorze.

Co to za idiotyczny wymysł? Natychmiast to poprawcie, bo takich przypadków jest pełno i nie chcę później świecić oczami przed Klientami, gdy przejdę na restapi.

**Comment by SebastianOzdoba** [comment]
Ja uważam że to dobry pomysł, formularz zawsze powinien być wypełniony i odpowiednie płatności wybrane, jeśli się rozmyślił i chce zapłacić przy odbiorze, niech anuluje i zrobi to ponownie.  
Natomiast zgadzam się z tym że powinna być konsekwencja, nie ma ani w API ani w GUI. 
Potem to integratorzy świecą oczami: "bo przecież na interfejsie w Allegro jest"

**Comment by PrzemyslawLukanowski** [comment]
Będzie to ujednolicone - dane do faktury dla nieopłaconych zamówień zostaną w najbliższym czasie usunięte na froncie.

**Comment by PrzemyslawLukanowski** [comment]
Dane do faktury dla nieopłaconych zamówień zostały usunięte na froncie.
