### ISSUE TITLE
Wiszące kolejki aktualizacji ilości

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#2030]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Szanowni Państwo, 
od początku działania nowego API jest problem z przepadającymi kolejkami.

Ciągle status "NEW" - było to zgłaszane... Nadal sytuacja się powtarza nagminnie. 

Przykład:
Command_id: 8d171d6c-ecfa-4b38-929a-1784e448965e, 
aukcja: 7247759028
Kolejka ze statusem NEW wisi od 2019-07-16T10:39:22.03Z, a mamy 26 lipiec...

Nie zapisuję paczek z trace_id bo jest tego za dużo.

W czym jest znowu problem?
Proszę w końcu o **konkretne naprawienie problemu**.

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad tym problemem. Dodałem ten przypadek do zgłoszenia.

**Comment by PrzemyslawLukanowski** [comment]
Problem niestety okazał się poważniejszy. Pracujemy nad jego rozwiązaniem.

W ciągu najbliższych kilku dni wiszące taski na zmianę liczby sztuk zakończą się statusem FAIL. W międzyczasie można ponowić request o zmianę liczby sztuk. Nowe requesty powinny przechodzić poprawnie.
