### ISSUE TITLE
Zdjęcia się nie ładują

### ISSUE THREAD

**Issue by belizesklep** [allegro/allegro-api#2031]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

[res] => {"errors":[{"code":"415 UNSUPPORTED_MEDIA_TYPE","message":"415 Unsupported Media Type","details":null,"path":null,"userMessage":"Niedozwolony typ zdjęcia."}]}

Zdjęcia są ok. Wszystko działało zawsze poprawnie, nie zmieniliśmy formatu ani wielkości fotek. Natomiast przy próbie wystawienia wyskakuje błąd.

**Comment by PrzemyslawLukanowski** [comment]
@belizesklep Prześlij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełen request i response wraz z trace-id. W zgłoszeniu dopisz GitHub #2031.
