### ISSUE TITLE
offers/listing - sortowanie nie działa

### ISSUE THREAD

**Issue by dxsoftware** [allegro/allegro-api#2032]
Obsługuję 3 konta na Allegro. Robię raporty najlepszych ofert dla firmy, które obsługuję. Pomyślałem że można wygenerować takie raporty przez API.
Wywołuje metodę offers/listing, w parametrach podaję kategorię, id sprzedawcy i sortowanie po -popularity i dostaję jakieś bzdury. 
Sortowanie nie działa.

**Comment by PrzemyslawLukanowski** [comment]
@dxsoftware Zweryfikowałem to i sortowanie po popularności działa prawidłowo - przykładowe wywołanie:
GET /offers/listing?phrase={phrase}&sort=-popularity

Prześlij nam tutaj przykładowy request i response, pozwoli nam to szybciej zlokalizować źródło błędu.

**Comment by dxsoftware** [comment]
Problem jest przy takim ułożeniu, bez frazy:
zakres cenowy + kategoria + id sprzedawcy + sortowanie po popularności

**Comment by PrzemyslawLukanowski** [comment]
Zasób działa prawidłowo, zweryfikowałem to na przykładzie:
GET offers/listing?seller.id={sellerId}&category.id=146702&price.from=10&price.to=100&sort=-popularity

Otrzymałem oferty z następującą popularnością: 4, 8, 3, 1, 1  0, 0.
Pamiętaj, że zasób odzwierciedla wizualną wyszukiwarkę serwisu - stąd na pierwszym miejscu jest u mnie oferta z popularnością 4, ponieważ jest to oferta promowana.

Możesz podesłać nam swój cURL z requestem i responsem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Dopisz w nim GitHub #2032.

**Comment by dxsoftware** [comment]
Witam,
Proszę spojrzeć na taki request, ponieważ z nim mam problem:
https://api.allegro.pl/offers/listing?&limit=100&category.id=16696&offset=100&price.from=50&price.to=500&sort=-popularity&seller.id=41913190

Powinienem otrzymać wyniki takie jak na stronie:
https://allegro.pl/uzytkownik/ekowolt_pl/przemysl?bmatch=baseline-var-n-dict4-eyesa-bp-com-1-3-0619&order=qd&price_from=50&price_to=500

**Comment by PrzemyslawLukanowski** [comment]
Używasz parametru offset=100, więc zwracana listą będzie zaczynać się od setnego wyniku. 
Usuń ten parametr, aby otrzymać response, który wkleiłeś.
