### ISSUE TITLE
c# kodowanie

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2033]
Hey
Czy ktoś gdzieś widział w sieci więcej przykłądów c# i rest api allegro ? a może jakies open projekty są ? bo nic nie mogę znaleźć ...  a moze ktoś podzielił by sięswoim kodem ?

**Comment by Onixarts** [comment]
API jak każde inne, ustawiasz nagłówki, tworzysz odpowiedni request pod endpoint i wysyłasz. Możesz skorzystać np z klasy HttpClient (ma ona chyba największe możliwości) - do niej przykładów znajdziesz wiele w sieci. Alternatywnie możesz skorzystać z biblioteki RestSharp, która powstała zanim powstał HttpClient - bo to jest relatywna nowość w obsłudze Api w .NET.

HttpClient, w odróżnieniu od innych klas typu WebClient, webrequest itp obsługuje fajnie tzw. middleware, czyli kod wstawiany w łańcuch wywołania, zatem można sobie w ten sposób obsłużyć np odświeżanie tokenów, obsługę błędów, czy logowanie transmisji, ograniczając same wywołania API do kilku linijek, skupiając się tylko na biznesie. Dzięki temu kod jest o wiele bardziej czytelny.

**Comment by ponowemu** [comment]
Napisz dokładnie co chciałbyś osiągnąć to będziemy mogli pomóc. Tak jak @Onixarts wspomniał najrozsądniej będzie jeżeli użyjesz HttpClient'a, a reszta już raczej nie jest złożona.

**Comment by frankii91** [comment]
ok autoryzację  mam zrobioną typu device flow, wysyąłnei post put get itp mam ogarnięte  (wystarczająco na własne potrzeby - przynajmniej tak mi się wydaje (pobranie pełnych info o 4k aukcji jak i zakończenie np. 500 nie powoduje błędów)

Mam jednak problem z tokenem odświerzającym a bardziej z logiką jak to ma działac.

Autoryzuje aplikacje dostaej token dostepowy i odświerzający ale co dalej ?

Obecnie muszę co jakiś czas robić autoryzacje od nowa dokumentacja mów o 12h.

W zwiazku z tym kiedy powinienem robić odnowienie tokena oraz jak to robić aby nie mieć nigdy żadnego wyjątku typu braku autoryzacji/token wygasły.

Obecnie robię prostą aplikacje która ma mieć za zadanie  tylko i wyłącznie cykliczną 1-2 razy dziennie sprawdzenie aukcji czy któraś z nich jest do zakończenia lub zmiana terminu wysyłki
aukcje łacze z bazą danych po id auckji i ean informacje o aukcjach trzymam w mssql, z mssql róneiż biorę info co zrobic z daną aukcją.

Zależy mi na działaniu apki bez wieszania się i nadzoru poniewarz docelowo ma obsługiwać powyżej 60tys aukcji. (wcześniej miałem rozwiązanie firmy x działające na php jednak masa problemów i nie nadaje się do większej ilości aukcji a prośba o jakiekolwiek poprawki u autora graniczą z cudem).

Niebardzo wiem też w jaki sposób prawidłowo zapobiec/zabezpieczyć  przestrzeganie limitów nałożonych od allegro na ilości zapytań.

**Comment by pkrzemo** [comment]
@frankii91 

> Autoryzuje aplikacje, dostaje token dostepowy i odświerzający ale co dalej ?

Dostajesz też informację jak długo token dostępowy jest ważny, możesz ją sobie zapisać i sprawdzać ile czasu ci zostało. W dowolnym momencie, nawet gdy minął czas ważności tokena dostępowego, możesz wysłać żądanie odświeżenia tokenów. Do tego wywołania potrzebny ci jest ten token odświeżający. W odpowiedzi dostaniesz nowy token dostępowy, informację o czasie jego przydatności, oraz NOWY TOKEN ODŚWIEŻAJĄCY (stary token odświeżający traci wtedy swoją ważność i staje się bezużyteczny). Mając te informacje musisz sam sobie opracować politykę odświeżania tokenów (obu, bo ten odświeżający jest jednorazowego użytku). 
przeczytaj dokumentację. Tam jest to opisane. I sprawdź dokładnie co otrzymujesz w odpowiedzi - to daje czasem więcej niż tylko czytanie dokumentacji ;-)



> Obecnie muszę co jakiś czas robić autoryzacje od nowa dokumentacja mów o 12h.

Autoryzację wystarczy robić tylko raz, potem tylko odświeżasz w tle co jakiś czas, albo gdy to jest potrzebne (jeśli nie pobierasz danych przez 2 dni, to wystarczy odświeżyć tokeny i już możesz znowu działać). No chyba że stracisz ten JEDNORAZOWY token do odświeżania...


.

> Niebardzo wiem też w jaki sposób prawidłowo zapobiec/zabezpieczyć przestrzeganie limitów nałożonych od allegro na ilości zapytań.

Wystarczy że będziesz czekał na odpowiedź z poprzedniego zapytania zanim wyślesz następne... RESTAPI jest obecnie tak mało wydajne, że nie jesteś w stanie wtedy nawet zbliżyć się do tych limitów! LOL


> ... a moze ktoś podzielił by sięswoim kodem ?

pewnie jak podzielisz się najpierw swoimi pieniędzmi to znajdą się tacy co podzielą się swoim kodem...
;-)

**Comment by Onixarts** [comment]
Możesz również, korzystając z handlerów występujących w `HttpClient` sprawdzać czy odpowiedź na Twój request nie informuje o wygaśnięciu tokena, odświeżyć go i ponowić request. Z punktu widzenia kodu tworzącego i wysyłającego request będzie to przezroczyste, bo odświeżenie tokena będzie wykonane przez odpowiedni handler.

Co do limitów, to w odpowiedzi na requesty dostajesz aktualny poziom wykorzystania limitu. Możesz zrobić odpowiedni handler, który będzie spowalniał wysyłanie requestów jeśli wartość zacznie zbliżać się do limitów.

**Comment by frankii91** [comment]
thx :D

**Comment by jakubmaguza** [comment]
> W dowolnym momencie, **nawet gdy minął czas ważności tokena dostępowego**, możesz wysłać żądanie odświeżenia tokenów.

Człowiek tyle klepie w tym API i nie wiedział tego %) Dzięki!

**Comment by frankii91** [comment]
> > W dowolnym momencie, **nawet gdy minął czas ważności tokena dostępowego**, możesz wysłać żądanie odświeżenia tokenów.
> 
> @pkrzemo
> Człowiek tyle klepie w tym API i nie wiedział tego %) Dzięki!

Ja to zrobiłęm chyba ciut inaczej a dokąłdnie

przy pobieraniu tokena oraz tokana odświerzającego zapisuje sobie szas unixowy w sekundach + czas warzności tokena np. do pliku/bazy sql 

a następnie  przed wysłaniem kazdego zapytania do api sprwdzam czy czas zapisany jest większy niż obecny i wrazie potrzeby aktualizuje token przed wysłąniem zapytani.

Wydaje mi się że powinno być takie coś ok.

**Comment by imper86** [comment]
@frankii91 taką informację masz też zakodowaną w tokenie JWT, więc chyba bez sensu marnować dodatkowe pole w pliku/bazie sql ;)

**Comment by frankii91** [comment]
> @frankii91 taką informację masz też zakodowaną w tokenie JWT, więc chyba bez sensu marnować dodatkowe pole w pliku/bazie sql ;)

Spoko.... thx :) nawet bym nie pomyślał aby dekodować token :)  Szkoda że takie informacje są ukryte głęboko i nikt o tym nie przypomina obok informacji o odświeraniu tokena choćby tak jak prz tym api. 

Mimo to wtakim razie podawanie czasu warzności tokena przez allegro jest zbędne i niepotrzebnei obciąża im zasoby.. pewnie niewiele ale zawsze coś ..

**Comment by frankii91** [comment]
Czytam dokumentacje api i albo nie ma albo nie bardzo rozumiem
jest takie coś jak "Edycja wielu ofert jednocześnie"  i chodzi dokąłdnie o zmianę cen.
Z oisu wynika że można zmieić ceną (tą samą cenę) na kilku aukcjach - zbiorczo - to rozumiem
ale jak zmieić na x aukcjach cenę ale każda cena jest inna.

Czy trzeba wykonywac PUT /sale/offer-price-change-commands/{commandId}   dla każdej ceny osobno ? ( lub  GET sale/offers/{offerId} )

czy możńa jakoś zbiorczo wysłac 1000 różnych cen do 1000 różnych aukcji ?

**Comment by Onixarts** [comment]
Put na każdym zasobie to raczej normalna sprawa

**Comment by jakubmaguza** [comment]
Trzeba wywołać ten zasób dla każdej ceny osobno.

---
Pozdrawiam,
Jakub Maguza

pon., 12.08.2019, 21:40 użytkownik Onixarts <notifications@github.com>
napisał:

**Comment by jakubmaguza** [comment]
Trzeba wywołać ten zasób dla każdej ceny osobno.

**Comment by frankii91** [comment]
Mam kolejną zagwoztkę.

a chodzi o przesyłane daty przez api
w dokumentacji pisze że daty są podawane w taki sposób 2018-07-16T10:13:28.147Z
 
json parsuje za pomocą 
https://www.newtonsoft.com/json/help/html/ParseJsonArray.htm

i zawsze dotyka mi daty i ją mienia.. obcina milisekundy itp.
Ktoś coś doradzi aby problem znikł?

**Comment by PrzemyslawLukanowski** [comment]
Z racji dużej liczby języków programowania, nie jesteśmy w stanie prowadzić wsparcia dla każdego z nich. Być może ktoś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.

Znalazłem informację, według której za obcięcie milisekund odpowiedzialna jest metoda .ToString(). Spróbuj wywołać ją z argumentem “O”, jak w przykładzie poniżej:

`Console.WriteLine(((DateTime)dict["timestamp"]).ToString("O"));`

Być może ta informacja okaże się w jakiś sposób pomocna.

**Comment by frankii91** [comment]
OK

> Z racji dużej liczby języków programowania, nie jesteśmy w stanie prowadzić wsparcia dla każdego z nich. Być może ktoś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.
> 
> Znalazłem informację, według której za obcięcie milisekund odpowiedzialna jest metoda .ToString(). Spróbuj wywołać ją z argumentem “O”, jak w przykładzie poniżej:
> 
> `Console.WriteLine(((DateTime)dict["timestamp"]).ToString("O"));`
> 
> Być może ta informacja okaże się w jakiś sposób pomocna.

dzięki

**Comment by frankii91** [comment]
Nie bardzo mogę zrozumieć dokumentacje odnośnie pobierania zamówień
metoda GET /order/checkout-forms 
Z dokumentacji wynika aby logikę oprzeć na dzienniku zdarzeń jednak analizując api i robiąc testy same metody od zdarzeń nie bardzo mają sens, w moim przypadku - chyba że się mylę 
https://developer.allegro.pl/orders/#02
metody
/order/events 
oraz
 /order/event-stats 
wydaje mi się że nie muszę z nich korzystać w cale.

Chce pobierać zamówienia do swojego programu sprzedażowego.
Załóżmy że będę pobierał wszystkie zamówienia jakie są dostępne z statusem READY_FOR_PROCESSING
i traktował je jako poprawne wszystkie inne uznaje jako nie poprawne i w większości przypadków będą anulowane.

Proszę o informację czy takie podejście jest ok czy coś przeoczyłem i nie mogę zrozumieć.

**Comment by jakubmaguza** [comment]
Ma :)

**Comment by neldh** [comment]
jeśli pobierasz orders/checkout-forms z filtrem na boughtAt np 3 dni wstecz i ktoś kupił sobie 24.08.2019
(i wtedy pobrało ten checkout-form), a dzisiaj mamy 29.08.2019 i ten kupujący zrobił dzisiaj dopłatę do tego zamowienia, to orders/checkout-forms z filtrem na 3 dni już Ci tego nie zwróci (bo pierwotny zakup był ponad 3 dni temu) i jedynym wyjściem, żeby złapać informację, że przyszła ta doplata jest sprawdzanie orders/events.

**Comment by jakubmaguza** [comment]
To zależy, tak jak zauważyłeś, od tego jak daleko patrzymy wstecz.

**Comment by neldh** [comment]
No niby tak, ale jakbyś daleko nie sięgał, zawsze istnieje szansa, że doplata pojawi się  po czasie większym niż filtrujesz. Dlatego ja pobieram najpierw orders/events, potem orders/checkout-forms, a potem pobieram pojedyncze orders/checkout-forms, ktore pojawiły się w events, a nie bylo ich w masowym checkout-forms.

**Comment by jakubmaguza** [comment]
Tak jest. To wszystko zależy od tego jaki jest work-flow w firmie i dla kogo robi się oprogramowanie. Jeśli firma dość szybko wysyła do Allegro prośbę o zwrot prowizji za taką nieopłaconą transakcję, to nie powinno być problemu. Zgadzam się jednak, że bezpieczniej jest użyć events.

**Comment by frankii91** [comment]
a nie prościej pobierać wszystkie zamówienia order/checkout-forms
a w swojej bazie  zamówień jedynie aktualizować zamówienia które miały status inny niż READY_FOR_PROCESSING i odpowiednio je oznaczać ? pobranie wszystkich zamówień wcale tak długo nie trwa ...

Dodam że - dodatkowych dopłat do zamówień nie ma wcale a 98% zamówię jest od razu opłacone lub  jest pobranie i ma status READY_FOR_PROCESSING  a 1 % nie ma wybranej żadnej opcji płatności i formularz nie jest wypełniany wcale a kolejny 1% to zamówienia z rozpoczętą płatnością ale nie dokończoną z jakiego powodu

Rozumiem że to uproszczenie które może powodować problemy ale nie bardzo rozumiem jakie, jak klient nagle wypełni formularz i/lub dokończy płatność  to samo zamówienie checkoutForms.id się nie zmienia przecież ?  czy może coś źle doczytałem i zamówienie  checkoutForms.id może zniknąć i pojawić się nowe ?

**Comment by jakubmaguza** [comment]
Przy pobieraniu checkout forms, podajesz z jakiego zakresu dat chcesz wyniki. Jeśli pobierasz np.: z 3 dni, a klient opłaci zamówienie po 5 dniach, to Twój system nie złapie tego zamówienia. To jedyny problem. Jeśli pobierasz wszystkie zamówienia, to ten problem znika.

**Comment by frankii91** [comment]
ok to chyba został mi jeden problem do rozwiązania checkoutForms.id jest dość długi moje miejsce na zewnętrzny nr zamówienia to 30 znaków (nie mogę tego zmienić) .
Czy jest jakiś sposób poza tworzeniem nowych krótkich id i mapowania ich z tymi długimi checkoutForms.id 

Może w checkoutForms.id  jest zakodowane coś więcej niż tylko id zamówienia i można go skrócić ?

**Comment by pkrzemo** [comment]
> Rozumiem że to uproszczenie które może powodować problemy ale nie bardzo rozumiem jakie, jak klient nagle wypełni formularz i/lub dokończy płatność to samo zamówienie checkoutForms.id się nie zmienia przecież ? czy może coś źle doczytałem i zamówienie checkoutForms.id może zniknąć i pojawić się nowe ?

Wydaje mi się jednak że checkoutForms to formularze płatności. A takowy można anulować i wypełnić na nowo. Wtedy będzie nowy checkoutForms.id ...

**Comment by frankii91** [comment]
> > Rozumiem że to uproszczenie które może powodować problemy ale nie bardzo rozumiem jakie, jak klient nagle wypełni formularz i/lub dokończy płatność to samo zamówienie checkoutForms.id się nie zmienia przecież ? czy może coś źle doczytałem i zamówienie checkoutForms.id może zniknąć i pojawić się nowe ?
> 
> Wydaje mi się jednak że checkoutForms to formularze płatności. A takowy można anulować i wypełnić na nowo. Wtedy będzie nowy checkoutForms.id ...

no nie bardzo 
https://developer.allegro.pl/orders/#02
GET /order/checkout-forms - pozwoli ci pobrać listę zamówień.

**Comment by jakubmaguza** [comment]
CheckoutForms.id to GUID. W guidzie nic nie jest zakodowane.
Mapownie ID to jedyne rozwiązanie, bo checkoutForms.id jest potrzebne do różnych innych czynności związanych z zamówieniem. Nie chcesz go stracić.

Jeśli będziesz pobierał tylko Ready for processing, to ID się nie zmieni.

**Comment by pkrzemo** [comment]
@frankii91 
> no nie bardzo

Cytaty z dokumentacji:

>jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy.

i:

>FILLED_IN - zdarzenie z takim statusem może pojawić się więcej niż raz, jeśli klient wypełni FOD kilka razy np. gdy nie zakończy płatności lub doszło do jej anulowania; Pamiętaj, że przy tym statusie mogą zmienić się dane, aż do czasu zakończenia płatności.

**Comment by neldh** [comment]
> 
> 
> a nie prościej pobierać wszystkie zamówienia order/checkout-forms
> a w swojej bazie zamówień jedynie aktualizować zamówienia które miały status inny niż READY_FOR_PROCESSING i odpowiednio je oznaczać ? pobranie wszystkich zamówień wcale tak długo nie trwa ...
> 
> Dodam że - dodatkowych dopłat do zamówień nie ma wcale a 98% zamówię jest od razu opłacone lub jest pobranie i ma status READY_FOR_PROCESSING a 1 % nie ma wybranej żadnej opcji płatności i formularz nie jest wypełniany wcale a kolejny 1% to zamówienia z rozpoczętą płatnością ale nie dokończoną z jakiego powodu
> 
> Rozumiem że to uproszczenie które może powodować problemy ale nie bardzo rozumiem jakie, jak klient nagle wypełni formularz i/lub dokończy płatność to samo zamówienie checkoutForms.id się nie zmienia przecież ? czy może coś źle doczytałem i zamówienie checkoutForms.id może zniknąć i pojawić się nowe ?

Możesz opłacić zamówienie, a dopłatę dostać później (pomimo, że już jest zapłacone). Gwarantuje Ci że ludzie tak robią, bo np chcą 1 przedmiot więcej nagle.

Wtedy checkout form jest już w stanie READY FOR PROCESSING na samym początku. Jak zaktualizujesz tylko te, które są w innym stanie to pominiesz dopłatę

**Comment by frankii91** [comment]
to ja już nie rozumiem :(  jest to dalekie od sensowności i logiki... i nie nigdy nie może działać "na 100%" 
1. usuwanie zamówień - masakra... takie coś nie powinno mieć miejsca a co najwyżej anulowanie/zwrot prowizji itp...
2. grupowanie towarów w 1 zamówienie tym bardziej masakra skoro klient kupił specjalnie 2x oddzielnie to po co ma grupować.. zamówienia (płatność może być do dwóch i powinno  być to w niej opisane. jak kupuje przez koszyk to wtedy to jest 1 zamówienie
3. możliwość dopłaty jest bezsensowa skoro zamówienie opłacone całe to nie powinno być możliwości dokonania dopłaty do tego zamówienia.
4. zamówienia fizyczne w allegro jak płatność online wybrana ale nie zakończone (błąd problem itp)  - nie powinno być wykazywane jako sprzedaż i nie powinno być widoczne dla sprzedającego nie powinna być też pobierana prowizja itp. ułatwiło by to życie... jest totalnie lipnie rozwiązane ....

**Comment by pkrzemo** [comment]
@frankii91 
> to ja już nie rozumiem :( jest to dalekie od sensowności i logiki... i nie nigdy nie może działać "na 100%"
> 
> 1. usuwanie zamówień - masakra... takie coś nie powinno mieć miejsca a co najwyżej anulowanie/zwrot prowizji itp...

to nie usuwanie zamówienia tylko zmiana opcji dostawy i płatności...

> 2. grupowanie towarów w 1 zamówienie tym bardziej masakra skoro klient kupił specjalnie 2x oddzielnie to po co ma grupować.. zamówienia (płatność może być do dwóch i powinno  być to w niej opisane. jak kupuje przez koszyk to wtedy to jest 1 zamówienie

A po co klient ma płacić 2 razy za wysyłkę ?

> 3. możliwość dopłaty jest bezsensowa skoro zamówienie opłacone całe to nie powinno być możliwości dokonania dopłaty do tego zamówienia.

Najczęściej klienci dopłacają za zmianę rodzaju przesyłki. Po dokonaniu zapłaty allegro nie umożliwia żadnej możliwości zrealizowania takiej operacji. Pozostaje się więc tylko dogadać ze sprzedawcą i dopłacić ... Ma to sens!

> 4. zamówienia fizyczne w allegro jak płatność online wybrana ale nie zakończone (błąd problem itp)  - nie powinno być wykazywane jako sprzedaż i nie powinno być widoczne dla sprzedającego nie powinna być też pobierana prowizja itp. ułatwiło by to życie... jest totalnie lipnie rozwiązane ....

tu bym się zgodził, ALE ... ;-)

klient ma możliwość dokończenia płatności, a gdyby nie było to traktowane jako sprzedaż to ktoś w międzyczasie mógłby kupić to samo...

**Comment by jakubmaguza** [comment]
Co do punktu 2.: Mieszasz dwie różne opcje. Klient ma prawo zrobić 10 zamówień i zapłacić za każde oddzielnie -> wtedy masz 10 formularzy pozakupowych. Może też połączyć te zamówienia i zapłacić za całość.

**Comment by frankii91** [comment]
ok, ok, ok dzięi ale pewności dopytam Czyli zamówienia nigdy nie są usuwane ? jedynie zdarzenia ?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z poradnikiem:

>  Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy.

W przypadku wspólnej wpłaty w zasobie GET /order/checkout-forms usuwane są wcześniejsze zamówienia w statusie FILLED_IN. Szczegóły zamówienia w zasobie GET /order/checkout-forms/{checkoutForm_id} dostępne są do 180 dni wstecz. 
Zdarzenia w zasobie GET order/events nie są usuwane nigdy (w przypadku łączenia płatności). Możesz pobrać zdarzenia z ostatnich 60 dni.

**Comment by frankii91** [comment]
I mam kolejny temat: cz da się prosto i w jaki sposób pobrać oferty (pełne dane) ale aukcji innego/ innych użytkowników (którego aplikacja api nie ma autoryzacji)

np. Pobranie  wszystkich (pełne informacje o aukcji)  aukcji które zgadzają się z odpowiednim filtrem wyszukiwania.

**Comment by TomekKaczmarek** [comment]
@frankii91 podstawowe informacje o ofertach możesz teraz wyciągnąć za pomocą https://developer.allegro.pl/documentation/#operation/getListing.

Nad zasobem, który pozwoli pobrać publiczne dane do oferty będzie pracować, powinniśmy go udostępnić w ciągu najbliższego pół roku.

**Comment by frankii91** [comment]
> @frankii91 podstawowe informacje o ofertach możesz teraz wyciągnąć za pomocą https://developer.allegro.pl/documentation/#operation/getListing.
> 
> Nad zasobem, który pozwoli pobrać publiczne dane do oferty będzie pracować, powinniśmy go udostępnić w ciągu najbliższego pół roku.

a czy z danych uzyskanego tego zasobu będzie można prosto wystawić swoją ofertę ? Przy założeniu że opis oferty jak i foto nie są chronione prawami autorskimi ?

**Comment by TomekKaczmarek** [comment]
@frankii91 nie, publiczne dane o ofercie nie pozwolą (i nie powinny pozwolić) Tobie wystawić oferty. Dane oferty zawierają trochę informacji, które nie są dostępne publicznie, może je pobrać tylko i wyłączne osoba, która wystawiła daną ofertę - to jest poprawne i oczekiwane zachowanie systemu.

**Comment by frankii91** [comment]
Dawno tu nic nie pisałem ale zapytam o wysyłanie zdjęć
(pozostałem przy restscharp)

zdjęcie około 700kb
robię tak
1. mam taska async który odpowiada za wysyłanie zapytań do api 
2. mam taska async w którym robi się pętla która wywołuje 1 taska n razy 
3. mam taska async który uruchamia taska 2 i jak dostanie odpowiedz to przetwarza dane i zapisuje do bazy.

operacja dla 10000 zdjęć trwa około 4min (2s wysłanie zapytań potem czekanie na odpowiedz 4 min ) i zapis do bazy. ( niestety te 10k zdjęć to ten sam link wiec pewnie tu tkwi szkopuł) 
Czy to szybko czy wolno ? i czy na szybkość miało wpływ to że to ten sam link do foto wysłany 10tys razy ?

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspominamy przy okazji innych wątków związanych z konkretnym językiem programowania  - niestety, ze względu na ich dużą liczbę, nie prowadzimy wsparcia dla każdego z nich, dlatego nie możemy udzielić satysfakcjonującej odpowiedzi na Twoje pytanie. Być może któryś z użytkowników forum miał do czynienia z podobnym przypadkiem i będzie w stanie Ci pomóc.

**Comment by jakubmaguza** [comment]
Jeśli używasz tego samego zdjęcia do różnych aukcji, to wystarczy że zdjęcie wgrasz raz i wszędzie użyjesz tego samego linka.
Nie wrzucałem zdjęć już jakiś czas, ale na pewno nie trwało to 4 minuty per aukcja.

**Comment by frankii91** [comment]
> Tak jak wspominamy przy okazji innych wątków związanych z konkretnym językiem programowania - niestety, ze względu na ich dużą liczbę, nie prowadzimy wsparcia dla każdego z nich, dlatego nie możemy udzielić satysfakcjonującej odpowiedzi na Twoje pytanie. Być może któryś z użytkowników forum miał do czynienia z podobnym przypadkiem i będzie w stanie Ci pomóc.

tak wiem, ale w tym wątku jest paru ludzi co pomogło dlatego tutaj pisze...

**Comment by frankii91** [comment]
jednak większy problem robi się z  respons StatusCode = 0

**Comment by frankii91** [comment]
nikt nie ma rozwiązania na ten problem ?
