### ISSUE TITLE
/sale/products - Forbidden 403

### ISSUE THREAD

**Issue by wehrmannit** [allegro/allegro-api#2034]
Hello,

I'm facing an issue regarding the new /sale/products endpoint.

Uploading images using to the endpoint /sale/images works great - using access token A.

When trying to create a product (endpoint /sale/products) (even without payload) we receive a 403 Forbidden status, using access token A.

How is this possible? Is the endpoint still faulty? I know it's in beta but that doesn't sound right.

If it is broken, how can we bulk create products? We're selling customised phone cases that do not exist on Allegro yet, so we can't do an EAN search.

**Comment by PrzemyslawLukanowski** [comment]
I verified the POST sale/products endpoint, it works properly. Does your token has user context? What [type of authorization](https://developer.allegro.pl/en/auth/) do you use? Make sure it’s not client credentials authorization, it should be Device or Code flow.

**Comment by wehrmannit** [comment]
To get our token we use

https://allegro.pl.allegrosandbox.pl/auth/oauth/device

We receive a confirmation link that we use and confirm.

Using the device_code, we receive the access token.

I'm not sure what you mean by 'user context' though.

**Comment by PrzemyslawLukanowski** [comment]
Send us your token and cURL with full request and response via our [contact form](https://allegro.pl/pomoc/kontakt), add “GitHub #2034” to it.

> I'm not sure what you mean by 'user context' though.

Token with client credentials authorization doesn’t have user context - it means you’ve got access only to public resources, e.g. retrieving a list of categories, browsing through a list of offers.
