### ISSUE TITLE
doGetMyIncomingPayments - BŁĘDNE ODPOWIEDZI

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2035]
Zaciągam płatności z danego okresu. Pobieram po 25 sztuk, zwiększając za każdym razem wartość transOffset do momentu aż metoda przestaje zwracać wyniki. 
I co seria zapytań to inna liczba pobranych danych. Okazuje się, że co jakiś czas metoda zwraca pustą odpowiedź, mimo, że powinny zostać zwrócone dane. Gdy zaraz powtórzę to samo zapytanie, dostaję odpowiedź z danymi.
W formularzu wysłałem dwa przykłady różnych odpowiedzi dla takiego samego zapytania (zgłoszenie 06050757)

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy to - API zwraca w tym przypadku różne dane. Zgłosiłem błąd do odpowiedniego zespołu.

**Comment by lukada4100** [comment]
Problem z doGetMyIncomingPayments jest poważniejszy. Znalazłem przypadki, że niektórych płatności w ogóle nie zwraca: Pobrany za pomocą DoGetPostBuyFormsDataForSellersRequest formularz ma postBuyFormPayStatus: zakończona, ale DoGetMyIncomingPaymentsRequest nie zwraca odpowiadającej płatności, niezależnie jak ustawić filtry. Już wysyłam zestawienia request/response w formularzu.

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100 Dziękujemy za przesłane pliki. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by lukada4100** [comment]
@PrzemyslawLukanowski czym by można ją było póki co zastąpić w ramach jakiegoś workarounda bo mnie klienci zjedzą

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100 Możesz wykorzystać restowy zasób GET payments/payment-operations oraz GET order/checkout-forms, aby powiązać konkretną płatność z zamówieniem.
