### ISSUE TITLE
Brak informacji o dacie aktualizacji oferty

### ISSUE THREAD

**Issue by APICoderPL** [allegro/allegro-api#2036]
dlaczego pobierając oferty z użyciem zasobu:
https://api.allegro.pl/sale/offers

nie ma informacji o dacie aktualizacji oferty?
Czy moglibyście dodać takie pole np.: do sekcji publication?

Idealnie by było gdyby na tym zasobie można sortować oferty po dacie publikacji, aktualizacji i zakończenia.

**Comment by PrzemyslawLukanowski** [comment]
@APICoderPL Dziękujemy za sugestię, przekazałem ją do odpowiedniego zespołu. Jeżeli zdecydujemy się na jej wdrożenie, poinformujemy o tym we właściwym komunikacie.

**Comment by APICoderPL** [comment]
ok, przyznam że dzięki tej drobnej zmianie po Waszej stronie znacznie spadłaby ilość requestów do Waszych serwerów.
Obecnie data aktualizacji oferty jest wyłącznie po pobraniu jej danych.
