### ISSUE TITLE
Log nie zwraca statusu BOUGHT

### ISSUE THREAD

**Issue by romigrabarz** [allegro/allegro-api#2037]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

:beetle: **Opis**
Zauważyłem że metoda /order/events nie zwraca pierwszego wystąpienia zdarzenia (BOUGHT) w przypadku gdy klient kliknął KUP TERAZ, a następnie "porzucił zakup" np. zamykają przeglądarkę. W takim przypadku rozumiem że w logu powinno być tylko jedno wystąpienie typu BOUGHT?

Natomiast jeśli klient wybrał już formularz dostawy, kliknął KUPUJĘ i PŁACĘ, ale nie dokonał płatności to log mi zwraca już 2 pozycje typu BOUGHT oraz FILLED_IN.

Potrzebuję wiedzieć o takich "niedokończonych" zakupach przez klientów, aby ubiegać się o zwrot naliczonej prowizji przez Allegro.
Czy błąd jest po Waszej stronie czy po mojej?

**Comment by PrzemyslawLukanowski** [comment]
@romigrabarz Prześlij proszę przez nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt) pełen request w formacie cURL wraz z responsem. W zgłoszeniu dopisz GitHub #2037.

**Comment by PrzemyslawLukanowski** [comment]
> Zauważyłem że metoda /order/events nie zwraca pierwszego wystąpienia zdarzenia (BOUGHT) w przypadku gdy klient kliknął KUP TERAZ, a następnie "porzucił zakup" np. zamykają przeglądarkę. W takim przypadku rozumiem że w logu powinno być tylko jedno wystąpienie typu BOUGHT?

Status BOUGHT pojawia się dopiero w momencie, kiedy kupujący kliknie “kupuję i płacę” po wypełnieniu FOD-a. Samo wybranie “Kup teraz” nie jest ofertą kupna w ofercie, dlatego też taki status się nie pojawia.

> Natomiast jeśli klient wybrał już formularz dostawy, kliknął KUPUJĘ i PŁACĘ, ale nie dokonał płatności to log mi zwraca już 2 pozycje typu BOUGHT oraz FILLED_IN.

Zgadza się - FILLED_IN  może pojawić się więcej niż raz, jeśli klient wypełni FOD kilka razy np. gdy nie zakończy płatności lub doszło do jej anulowania. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by romigrabarz** [comment]
Dziękuje za informację.
Zatem w jaki sposób pobrać informację o aukcjach, które zostały kupione przez KUP TERAZ, ale nie został wypełniony FOD?

**Comment by PrzemyslawLukanowski** [comment]
Aktualnie przedmiot zostaje zakupiony dopiero po wypełnieniu FODa (przycisk “kupuję i płacę”). Samo kliknięcie “KUP TERAZ” nie oznacza kupna przedmiotu i nadania statusu BOUGHT, nie ma zatem możliwości pobrania takich aukcji.

**Comment by pkrzemo** [comment]
> Samo kliknięcie “KUP TERAZ” nie oznacza kupna przedmiotu i nadania statusu BOUGHT, nie ma zatem możliwości pobrania takich aukcji.

To ciekawe dlaczego w takim razie allegro pobiera za to prowizję (czy już może nie? )? 
Przecież NIE OZNACZA TO KUPNA PRZEDMIOTU , jak się tutaj dowiadujemy ... LOL

**Comment by PrzemyslawLukanowski** [comment]
@pkrzemo Zapoznaj się z naszym artykułem w sekcji [pomoc](https://allegro.pl/pomoc/dla-kupujacych/sposoby-zakupow/kup-teraz-jak-szybko-kupic-przedmiot-oGPBgzvYDc6). Drugi punkt mówi, że zakup potwierdzamy poprzez kliknięcie [kupuję i płacę]. Podobnie jak z dodaniem do koszyka - również nie oznacza to potwierdzenia zakupu.

**Comment by pkrzemo** [comment]
@PrzemyslawLukanowski Zapoznałem się i mam pewien dysonans poznawczy...
https://allegro.pl/pomoc/dla-sprzedajacych/oplaty-i-cenniki/jak-jest-obliczana-prowizja-od-sprzedazy-dykqgOq94iE

Czyli:
>Prowizję od sprzedaży naliczamy w chwili, gdy **Klient kupi w Twojej ofercie** - czyli w chwili, gdy wygra licytację lub **skorzysta z opcji _kup teraz_**.

Kupi, czyli przedmiot zostanie kupiony, czyli BOUGHT.
Co potwierdza praktyka naliczania prowizji ... w końcu to jest prowizja od sprzedaży, a nie prowizja od przewidywanej sprzedaży! Mamy więc pozycje gdzie nie ma FOD a jest naliczona prowizja.
LOL



To może należy wprowadzić nowy status "o mało co kupione" ALMOST_BOUGHT, bo informacja o tych prawie kupionych jest jak widać potrzebna ;-)

Liczymy też na zmianę sposobu naliczania prowizji aby naliczać ją dopiero gdy jest BOUGHT. Moglibyśmy wtedy zupełnie zignorować te niepotwierdzone zakupy i skupić się tylko na potwierdzonych.
:-)

> Podobnie jak z dodaniem do koszyka

Nie. Tu jest zupełnie inaczej. Dodanie do koszyka nie powoduje naliczenia prowizji, podobnie jak dodanie do obserwowanych.

**Comment by PrzemyslawLukanowski** [comment]
@pkrzemo Zapoznaj się proszę z moimi odpowiedziami w tym wątku, zwróciłem uwagę na to, kiedy i w jakim momencie pojawia się konkretny status.

> Prowizję od sprzedaży naliczamy w chwili, gdy Klient kupi w Twojej ofercie - czyli w chwili, gdy wygra licytację lub skorzysta z opcji kup teraz.

Skorzystanie z opcji kup teraz nie ogranicza się tylko do kliknięcia przycisku [kup teraz], ale także do potwierdzenia zakupu w kolejnych krokach poprzez [kupuję i płacę].

**Comment by pkrzemo** [comment]
@PrzemyslawLukanowski Zapoznałem się (wcześniej) z tymi odpowiedziami i nie były one satysfakcjonujące.

 To w którym momencie nalicza się prowizja?
Kiedy ktoś kliknie "kup teraz" czy gdy zatwierdzi FOD?

**Comment by PrzemyslawLukanowski** [comment]
@pkrzemo Prowizja nalicza się w momencie kupna przedmiotu w ofercie - czyli poprzez zatwierdzenie FOD i kliknięcie [kupuję i płacę].

**Comment by pkrzemo** [comment]
Rzeczywistość wygląda że jest inna. Mam pozycje bez FOD, front pokazuje "nie wybrano płatności", a prowizja jest już, jak widać niesłusznie, naliczona. Zgłaszam więc to jako błąd systemu naliczania prowizji!

**Comment by PrzemyslawLukanowski** [comment]
@pkrzemo Przepraszam, już wyjaśniam skąd wynika taka rozbieżność. Aktualnie, aby kupić przedmiot, oprócz kliknięcia [kup teraz], należy również wypełnić FOD oraz potwierdzić zakup przyciskiem [kupuję i płacę]. Niestety w starych aplikacjach mobilnych, kupujący nadal może kupić przedmiot, ale nie musi od razu wypełniać formularza opcji dostawy. W takim wypadku warto skontaktować się z klientem i poprosić o wypełnienie formularza płatności i dostawy. Kupujący może to zrobić przez zakładkę Kupione.
