### ISSUE TITLE
[Sandbox] Nie działa  {dodaj do koszyka}

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2039]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nie działa dodaj do koszyka, w konsoli: ERR_NAME_NOT_RESOLVED
Poprawcie proszę :)

**Comment by PrzemyslawLukanowski** [comment]
Czy problem nadal występuje? Zweryfikowałem to teraz i miałem możliwość dodania do koszyka.

**Comment by SebastianOzdoba** [comment]
tak
https://allegro.pl.allegrosandbox.pl/oferta/pasek-pleciony-6206426983?item=6206426983
Po kliknięciu dodaj i przejściu do koszyka, koszyk pusty. 
Najnowsza wersja Chrome, w konsoli lecą błędy 
![image](https://user-images.githubusercontent.com/47886399/62051322-692a1880-b213-11e9-8382-86c06dda63a6.png)

**Comment by PrzemyslawLukanowski** [comment]
Czy problem występuje też na innych przeglądarkach albo w trybie incognito? Spróbuj też wyczyścić ciasteczka. Testowałem u siebie i nie udało mi się odtworzyć tego błędu.

**Comment by SebastianOzdoba** [comment]
Bardziej to wina mojego proxy, bez niego zaczęło działać, zamykam :)
