### ISSUE TITLE
Zagubione parametry / Błędy od strony sprzedażowej

### ISSUE THREAD

**Issue by ZieGDA** [allegro/allegro-api#204]
Nie wiem czy zauważyliście, ale po waszych zmianach dotyczących parametrów obowiązkowych w części aukcji gubią się parametry. Macie zamiar to naprawić? Nie widzi nam się uzupełniać tych parametrów na nowo za każdym razem, kiedy ustawicie parametr jako obowiązkowy. Tracimy przy tym czas i pieniądze.

Możecie przetestować to w kategorii odzieżowej / majtki męskie / gubi parametr "Zestaw", "Materiał dominujący" oraz "Dostawa z polski".

Dodatkowo, gratulujemy błędu związanego ze źle uzupełnionymi parametrami. Kto zwróci nam pieniądze za paczki, które będziemy musieli ponownie nadać? Przyzwoitość nakazuje, abyście przynajmniej dali stosowny komunikat na głównej stronie allegro, a nie w mailach do sprzedawców DZIEŃ po tym jak problem wystąpił.

Tragedia, po prostu tragedia...

**Comment by PawelTaberski** [comment]
Jeśli zostanie zmieniony parametr wraz ze swoimi wartościami to w takim przypadku staje się w starszych ofertach nieuzupełniony i trzeba wybrać na nowo wartości. Informacje o planowanych zmianach w parametrach znajdziesz tutaj: https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach

**Comment by ZieGDA** [comment]
Moment. Owszem, pisaliście o tym, że więcej parametrów będzie obowiązkowych ale nie było wzmianki o tym, że będziemy musieli je na nowo uzupełniać. Jesteście niepoważni. Nie dość, że wymagacie nowych opisów, to dodatkowo w trakcie tych zmian dorzucacie nowe wymogi co do parametrów.

Czy wasi informatycy nie potrafią wprowadzić zmian tak, aby nie kasztanić nam wszystkich aukcji?

Parametry były uzupełnione, a Wy sobie je czyścicie, cholera wie czemu. Narażacie tym samym sprzedawców na dodatkowe koszty związane z ponownym uzupełnianiem tego wszystkiego. Przez Waszą niekompetencję i ciągłe zmiany, które powodują bałagan w naszych bazach danych sprzedaż na allegro staje się coraz mniej opłacalna.
