### ISSUE TITLE
Informacja o ilości sprzedanych sztuk na danej aukcji

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2042]
:bulb: **Sugestia**

Czy moglibyście zwracać informacje o ilości sprzedanych sztuk na danej aukcji przez metodę: https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET ?

**Comment by PrzemyslawLukanowski** [comment]
@kormichu Taką informację możesz zobaczyć w polu stock.sold.

**Comment by kormichu** [comment]
No nie do końca. Pole stock.sold jest dostępne w zasobie /sale/offers https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET zaś ja korzystam z danych które są dostępne w szczegółach danej oferty /sale/offers/{offerId} https://developer.allegro.pl/documentation/#operation/getOfferUsingGET . Chcąc teraz pobrać wszystkie informacje muszę skorzystać i z jednego i z drugiego zasobu, aby pobrać komplet informacji. Nonsens. Dlaczego nie ma wszystkich pól z widoku ogólnego (/sale/offers) w widoku szczegółowym (/sale/offers/{offerId}) ?

**Comment by PrzemyslawLukanowski** [comment]
Zasób GET sale/offers/{offerId} zwraca wszystkie informacje, które są podawane przy wystawianiu oferty. Podanie danych o ilości sprzedanych sztuk byłoby informacją nadwymiarową.

**Comment by kormichu** [comment]
W takim razie mam wykonywac 2x więcej requestów tylko po to, aby wyciągnąć pola, których brakuje w szczegółach oferty ? Ja rozumiem, że można pozbyć się pól które są nadmiarowe, ale tylko jeśli chodzi o listę, a nie na odwrót

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem, zasób GET /sale/offers/{offerId} zwraca wszystkie dane, które są potrzebne przy wystawianiu oferty - wszystkie zawarte tam informacje wprowadzone są przez wystawiającego. Za pomocą tego zasobu możemy również pobrać całą ofertę, celem jej edycji poprzez zasób PUT /sale/offers/{offerId}.
