### ISSUE TITLE
allegro_transaction_id - Dla allegro paczkomaty inpost

### ISSUE THREAD

**Issue by Inwestor1234** [allegro/allegro-api#2043]
Witam!
Czy znany jest przybliżony termin wprowadzenia spójnych numerów allegro_transaction_id z InPostem? Z tego co widzę to te numery to numery ze starego api a za kilka miesięcy je wygaszacie.

**Comment by PrzemyslawLukanowski** [comment]
Razem z InPostem pracujemy nad tą zmianą, obecnie zalecamy korzystanie z [mapowania](https://github.com/allegro/allegro-api/issues/1878).

**Comment by Inwestor1234** [comment]
`                RestClient client2 = new RestClient(@"https://api.allegro.pl/");
                RestRequest request2 = new RestRequest("payments/payment-id-mappings", Method.GET);
                request2.AddHeader("Authorization", "Bearer " + TokenAllegro);
                request2.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
                request2.AddParameter("paymentId", DaneWpisuAllegro.PlatnsciOnLine.First().NumerPlatnosicPayU);`

Zpytania dla PaymentId o numerze 56bfddf2-b2aa-11e9-8aee-27d2edcfab04 zwraca mi error bez opisu błędu - zwykle były komunikaty co nie tak. Kodowanie zdaje mi się poprawne bo po tym numerze płatności pobieram jej dane z waszego systemu w podobny sposób i tu gra.

**Comment by Inwestor1234** [comment]
Sprawa wyjaśniona, błąd był po mojej stronie - źle pobierany Token do allegro przez wcześniejszy który miał literówkę. Dzięki :)

**Comment by neldh** [comment]
czy sprawa z inpostem jest już rozwiązana, czy nadale trzeba korzystać z protezy i mapować id?

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad tym rozwiązaniem, więcej szczegółów wkrótce.
