### ISSUE TITLE
[SANDBOX] Nie wyświetla się lista kupionych. Jak przetestować usunięcie zamówień? 

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#2044]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Po dokonanym zakupie strona:
https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione
jest nadal pusta.
Chciałbym dowiedzieś się w jaki sposób mogę przetestować przypadek opisany w dokumentacji:

> Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to oznacza, że mamy do czynienia z połączeniem zakupów przez kupującego).
>

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - wykonałem zakup, w zakładce kupione nie pojawił się przedmiot. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by jkalina** [comment]
Wystąpił błąd usługi serwującej dane po podbiciu klienta ElasticSearcha.
Problem powinien być już rozwiązany.
