### ISSUE TITLE
Czy twórcy rest api posiadają przykłady plików php z curlem ???

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2046]
Świetnie sprawa jest przez Was opisana tu : https://developer.allegro.pl/getting_started/

zaś do tego też by sie przydały przykłady jak te metody mają wyglądać w plikach php , czy można o to prosić : https://developer.allegro.pl/orders/#02

np.  jak taka metada ma wyglądać w pliku php 
curl -X GET \
  'https://api.allegro.pl/order/event-stats' \
  -H 'authorization: Bearer {token}' \
  -H 'accept: application/vnd.allegro.beta.v1+json'

**Comment by ponowemu** [comment]
W dokumentacji masz wystarczająco informacji, a tutaj znajdziesz przykład: https://www.php.net/manual/en/book.curl.php.
-X to metoda http, -H to odpowiednio nagłówki, nie ma tutaj żadnej filozofii.

**Comment by jasiek07** [comment]
A czy dysponujesz przykładem pliku PHP , bo mnie cały czas tylko o to chodzi . 
Za cholere mi nie wychodzi umieszczenie np. tego : 
curl -X GET
'https://api.allegro.pl/order/event-stats'
-H 'authorization: Bearer {token}'
-H 'accept: application/vnd.allegro.beta.v1+json'

w curlu tak by działało

**Comment by ponowemu** [comment]
Pokaż co masz to powiem Ci dlaczego nie działa ;-)

**Comment by jasiek07** [comment]
Tak pozyskuje tokken :
<?php

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "xxx";
    $clientSecret = "xxx";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

function main()
{
    echo "access_token = ", getAccessToken();
}

main();


i nie wiem na co zmienić to : 
$authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
i całą reszte by zaimplementować to :
curl -X GET
'https://api.allegro.pl/order/event-stats'
-H 'authorization: Bearer {token}'
-H 'accept: application/vnd.allegro.beta.v1+json'

czyli pozyskanie np. 500 ostatnich zdarzeń z dziennika

**Comment by ponowemu** [comment]
Pokaż swojego curla, którym pozyskujesz chociażby ten access token. No i użyj formatowania kodu :)

**Comment by jasiek07** [comment]
$authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "xxx";
    $clientSecret = "xxx";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

**Comment by ponowemu** [comment]
Zmienna authUrl to nic innego jak adres zasobu, więc tutaj podajesz ten, który Cię w danym momencie interesuje. W przypadku zapytań do innych zasobów nie musisz już podawać clientId i clientSecret. W curlu, który wyżej zamieściłem masz info, że musisz podać token, który uzyskałeś. Nagłówki możesz dodać w chociażby ten sposób
`curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Name: Value',
    'Name: Value'
));`

**Comment by grzluk** [comment]
Polecam program Postman, który umożliwia testowanie różnych API, wysyłanie żądań i generuje również gotowe kody dla danego żądania w wielu językach w tym w PHP z wykorzystaniem cURL

**Comment by grzluk** [comment]
Wygenerowałem ten kod w 5 minut: pobiera ostatnie zdarzenie:

`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/vnd.allegro.beta.v1+json",
    "Authorization: Bearer **TutajWklejBearerToken**",
    "Cache-Control: no-cache",
    "Connection: keep-alive",
    "Content-Type: application/vnd.allegro.beta.v1+json",
    "Host: api.allegro.pl",
    "accept-encoding: gzip, deflate",
    "cache-control: no-cache"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}`

Przykładowa odpowiedź:
`{
    "latestEvent": {
        "id": "1564554927523019",
        "occurredAt": "2019-07-31T06:35:13.876Z"
    }
}`

**Comment by jasiek07** [comment]
GRZLUK po wklejeniu do twojego kodu , tokkenu , otrzymujemy błąd
{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}
Masz na to pomysł ?

**Comment by jasiek07** [comment]
a cały kod wygląda tak :
`function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "xxx";
    $clientSecret = "xxx";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);
	$AccessToken=$tokenObject->access_token;
    return $AccessToken;
}

function main()
{
    echo "access_token = ", getAccessToken();
	echo '<hr>';
		
	$curl = curl_init();

	curl_setopt_array($curl, array(
	CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "GET",
	CURLOPT_HTTPHEADER => array(
	"Accept: application/vnd.allegro.beta.v1+json",
	"Authorization: Bearer ".$AccessToken,
	"Cache-Control: no-cache",
	"Connection: keep-alive",
	"Content-Type: application/vnd.allegro.beta.v1+json",
	"Host: api.allegro.pl",
	"accept-encoding: gzip, deflate",
	"cache-control: no-cache"
	),
	));

	$response = curl_exec($curl);
	$err = curl_error($curl);

	curl_close($curl);

	if ($err) {
	echo "cURL Error #:" . $err;
	} else {
	echo $response;
	}
}

main();`

**Comment by magixneo** [comment]
Jakie jest rozwianie tego problemu? pytam poniewaz mam ten sam problem dostaje:



{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}* Closing connection #0

* About to connect() to api.allegro.pl port 443 (#0)
*   Trying 185.31.27.150...
* connected
* Connected to api.allegro.pl (185.31.27.150) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=PL; ST=Wielkopolskie; L=Poznan; OU=IT; O=Allegro.pl sp. z o.o.; CN=edge.allegro.pl
*        start date: 2019-05-28 13:20:05 GMT
*        expire date: 2020-05-28 13:20:05 GMT
*        subjectAltName: api.allegro.pl matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*        SSL certificate verify ok.
> GET /order/event-stats HTTP/1.1
> User-Agent: curl/7.26.0
> Host: api.allegro.pl
> Accept: application/vnd.allegro.public.v1+json
> Authorization: Bearer ************************************8
> Cache-Control: no-cache
> Connection: keep-alive
> Content-Type: application/vnd.allegro.public.v1+json
> accept-encoding: gzip, deflate
> cache-control: no-cache
>
* additional stuff not fine transfer.c:1042: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 403 Forbidden
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: ccc255f6a91100ca
< date: Tue, 28 Jan 2020 21:37:44 GMT
< x-ratelimit-remaining: 9000
< x-content-type-options: nosniff
< content-type: application/json
< content-length: 109
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 21
<
* Connection #0 to host api.allegro.pl left intact
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}* Closing connection #0
* SSLv3, TLS alert, Client hello (1):

**Comment by magixneo** [comment]
> 
> 
> $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
> $clientId = "xxx";
> $clientSecret = "xxx";
> 
> ```
> $ch = curl_init($authUrl);
> 
> curl_setopt($ch, CURLOPT_POST, 1);
> curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
> curl_setopt($ch, CURLOPT_USERNAME, $clientId);
> curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
> curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> 
> $tokenResult = curl_exec($ch);
> $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
> curl_close($ch);
> 
> if ($tokenResult === false || $resultCode !== 200) {
>     exit ("Something went wrong");
> }
> 
> $tokenObject = json_decode($tokenResult);
> 
> return $tokenObject->access_token;
> ```
> 
> }

mam ten sam problem co Ty jak go rozwiazales?

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}*

**Comment by PrzemyslawLukanowski** [comment]
@magixneo Błąd, który otrzymałeś w response związany jest z użytym przez Ciebie typem autoryzacji - [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Nie posiada on kontekstu użytkownika i pozwala korzystać tylko z publicznych zasobów, które w naszej dokumentacji oznaczyliśmy jako [bearer-token-for-application](https://developer.allegro.pl/documentation/#section/Authentication). Aby wywołanie zadziałało prawidłowo, musisz skorzystać z autoryzacji [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).

Z samym językiem PHP niestety nie pomożemy - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Wątek generowania tokenu w PHP dla wspomnianych wyżej typów autoryzacji przewinął się w wątkach, które załączam poniżej. Być może wśród nich znajdziesz wskazówki dotyczące rozwiązania Twojego problemu:

#2306
#708
#226

**Comment by magixneo** [comment]
Dzięki Przemek za pomoc,

powiazalem z sukcesem aplikacje typu device z kontem za pomoca verification_uri_complete za pomoca postman: faktycznie fajny programik :)

teraz mi pozostaje to ponizej i juz mam z gorki :)
curl -X POST \
'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}' \
  -H 'Authorization: Basic base64(clientId:secret)'

**Comment by magixneo** [comment]
> 
> 
> @magixneo Błąd, który otrzymałeś w response związany jest z użytym przez Ciebie typem autoryzacji - [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Nie posiada on kontekstu użytkownika i pozwala korzystać tylko z publicznych zasobów, które w [naszej dokumentacji ](https://developer.allegro.pl/documentation/#section/Authentication)oznaczyliśmy jako bearer-token-for-application. Aby wywołanie zadziałało prawidłowo, musisz skorzystać z autoryzacji [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).
> 
> Z samym językiem PHP niestety nie pomożemy - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Wątek generowania tokenu w PHP dla wspomnianych wyżej typów autoryzacji przewinął się w wątkach, które załączam poniżej. Być może wśród nich znajdziesz wskazówki dotyczące rozwiązania Twojego problemu:
> 
> #2306
> #708
> #226

Dzięki Przemek za pomoc,

powiazalem z sukcesem aplikacje typu device z kontem za pomoca verification_uri_complete za pomoca postman: faktycznie fajny programik :)

teraz mi pozostaje to ponizej i juz mam z gorki :)
curl -X POST
'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}'
-H 'Authorization: Basic base64(clientId:secret)'
