### ISSUE TITLE
Dodawanie nr przesyłki do zamówienia

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2047]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Czy tylko ja odnoszę wrażenie, że osoby projektujące API nie mają zielonego pojęcia o procesach biznesowych, które dzieją się w firmach sprzedających?
Przykład poradnika: jak obsługiwać zamówienia - dodawanie nr listu przewozowego do zamówienia
Nazwa w poradniku wskazuje, że dodajemy nr listu do zamówienia, zamówienie to akt zakupowy, w 1 zamówieniu możemy mieć wiele pozycji co jest naturalne i ogólnoprzyjętą zasadą.
I co się okazuje aby wysłać list przewozowy trzeba przekazać identyfikatory pozycji, kto to wymyślił i jaki jest w tym cel?

Postuluję zmianę, jest jeszcze na to czas,  tam powinien być identyfikator zamówienia a nie identyfikator pozycji.

**Comment by PrzemyslawLukanowski** [comment]
Przekazywany jest tam identyfikator pozycji a nie identyfikator zamówienia, ponieważ nie wszystkie przedmioty z zamówienia muszą być wysłane na jednym liście przewozowym. W najbliższym czasie wprowadzimy poprawkę w poradniku - Jak dodać numer przesyłki do **przedmiotu z** zamówienia.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski ale nadal jest to 1 zamówienie, więc do zamówienia może być więcej niż 1 list przewozowy :)

Przykład:
zamówienie na 15 pozycji
- wysyłam pierwszą paczkę w dniu D1, pakuję tam 8 pozycji
- wysyłam drugą paczkę w dniu D2, pakuję tam 7 pozycji
List przewozowy przypisany jest nadal to zamówienia, nikt nie schodzi do pozycji elementu
To jedyny scenariusz gdzie bedzie dwa listy. 

Postuluję zatem by była opcja przekazywania identyfikatora zamówienia, a tylko dla chętnych identyfikatora pozycji.

p.s.
Kupuję przez Allegro, przez ostatnie 8 lat nie dostałem nigdy dwóch listów przewozowych do jednego zamówienia

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba Przekazałem Twoją sugestię do odpowiedniego zespołu.

**Comment by neldh** [comment]
Takim sposobem i tak nie obskoczycie wszystkich możliwości. Zawsze może być taka sytuacja, że kilka sztuk którejś pozycji pójdzie jedną paczką, a pozostałe drugą. Zawsze powinniśmy dodawać nr listu do zamówienia (z możliwością dodania więcej niż jednego) i opcjonalnie podawać id pozycji, których dotyczy i opcjonalnie ilu sztuk z tych pozycji. Teraz w 99% przykładów pewnie wszyscy do was stukają na checkout-forms tuż przed wysłaniem nr listu tylko po to, żeby zebrać id pozycji potrzebne do stuknięcia z numerem listu. :]

**Comment by PawelTaberski** [comment]
@neldh Oczywiście sugestię przekazaliśmy, jeśli zdecydujemy się na zmianę, to poinformujemy o tym w odpowiednim komunikacie.
