### ISSUE TITLE
Czy twórcy rest api posiadają przykłady plików php z curlem ???

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2048]
Świetnie sprawa jest przez Was opisana tu : https://developer.allegro.pl/getting_started/

zaś do tego też by sie przydały przykłady jak te metody mają wyglądać w plikach php , czy można o to prosić : https://developer.allegro.pl/orders/#02

np. jak taka metada ma wyglądać w pliku php
curl -X GET
'https://api.allegro.pl/order/event-stats'
-H 'authorization: Bearer {token}'
-H 'accept: application/vnd.allegro.beta.v1+json'

A już najbardziej zależy mi na tym https://developer.allegro.pl/orders/  ale napisanym w CURLU umieszczonym PHP

p.s. ile dni czeka się na odpowiedź od twórców api allegro ?

**Comment by PrzemyslawLukanowski** [comment]
Duplikat #2046

**Comment by grzluk** [comment]
Polecam program Postman, który umożliwia testowanie różnych API, wysyłanie żądań i generuje również gotowe kody dla danego żądania w wielu językach.

**Comment by jasiek07** [comment]
A mnie na dadal chodzi tylko o gotowy przykład php dla curl -X GET
'https://api.allegro.pl/order/event-stats'
-H 'authorization: Bearer {token}'
-H 'accept: application/vnd.allegro.beta.v1+json'

**Comment by grzluk** [comment]
Wygenerowałem ten kod w 5 minut: pobiera ostatnie zdarzenie:

`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/vnd.allegro.beta.v1+json",
    "Authorization: Bearer **TutajWklejBearerToken**",
    "Cache-Control: no-cache",
    "Connection: keep-alive",
    "Content-Type: application/vnd.allegro.beta.v1+json",
    "Host: api.allegro.pl",
    "accept-encoding: gzip, deflate",
    "cache-control: no-cache"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}`

Przykładowa odpowiedź:
`{
    "latestEvent": {
        "id": "1564554927523019",
        "occurredAt": "2019-07-31T06:35:13.876Z"
    }
}`

**Comment by jasiek07** [comment]
Dzięki wielkie .
