### ISSUE TITLE
Błędna data zamówienia

### ISSUE THREAD

**Issue by romigrabarz** [allegro/allegro-api#2050]
Występuje problem:
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**
Pobieram log zamówienia dla CheckoutFormId='ffc01db2-b24c-11e9-8c61-999d36b43ef5' nowym REST API i ostatnia data zdarzenia to 2019-07-29 22:09:37.797.
Natomiast to samo zamówienie (TransactionId=1053199226) pobrane przez WEB API ma datę 2019-07-30 00:07:09.000, czyli zgodnie z tym co pisze w menadżerze zamówień w panelu konta.

**Comment by PhotoSoft** [comment]
Właśnie miałem to zgłosić. Wszystkie metody do pobierania zamówień mają ten sam błąd.

**Comment by PrzemyslawLukanowski** [comment]
W 'Moje Allegro' i WebAPI  prezentowana jest data z lokalnej strefy czasowej (czyli obecnie +02:00), natomiast w REST API jest data w formacie ze strefą +00:00 czyli Z, stąd różnica. W Twoim przypadku data zakupu w REST API to 2019-07-29T22:07:08.681Z, natomiast w WebAPI 2019-07-30T00:07:08+02:00.

**Comment by romigrabarz** [comment]
Dziękuję za wyjaśnienie. 
W takim razie w moim systemie importowania zamówień skoryguję datę z logu o strefę czasową.
