### ISSUE TITLE
Parametr "state" podczas autoryzacji 

### ISSUE THREAD

**Issue by konradkg** [allegro/allegro-api#2051]
:bulb: **Sugestia**

Przydałby się jakiś zarządzany przez aplikację zintegrowaną z allegro parametr, np. "_state_", wysyłany razem z requestem o autoryzację allegro, i dodawany ro redirect_uri po pomyślnym przyznaniu dostępu.

Przykład:
Wywołujemy `https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=XXX&redirect_uri=https://redirect.uri&state=SOME_STATE`

w rezultacie po poprawnej autoryzacji dostaję redirect na adres: https://redirect.uri?state=SOME_STATE&code=....

Po co to komu?
------
Np. żeby identyfikować który request wrócił, na którą instancję przekierować sobie ruch na HAProxy, trzymanie jakieś swojego stanu związanego z tą akcją - choćby id użytkownika.

**Comment by TimothyKoval** [comment]
Zostaw sobie ciastko

**Comment by imper86** [comment]
@konradkg albo rozkoduj token JWT i z tego weź sobie user_name (czyli id użytkownika allegro)

**Comment by konradkg** [comment]
> Zostaw sobie ciastko

nie zawsze i wszędzie można.

**Comment by konradkg** [comment]
> @konradkg albo rozkoduj token JWT i z tego weź sobie user_name (czyli id użytkownika allegro)

to nie rozwiązuje wszystkich problemów. Jak po swojej stronie nie masz tego user_name, albo masz podane inaczej (np. po staremu - zamiast loginu - email).

Parametr state jest praktycznie w każdej znanej mi implementacji OAuth. 
https://auth0.com/docs/protocols/oauth2/oauth-state

**Comment by pkrzemo** [comment]
@konradkg Nie bardzo rozumiem ten problem... 
Przecież to ty definiujesz co jest w redirect uri. Dodaj sobie tam parametry jakie chcesz i z takim redirect uri zarejestruj sobie aplikację w allegro aby w odpowiedzi autoryzacyjnej mieć dokładnie takie przekierowanie...

**Comment by PrzemyslawLukanowski** [comment]
@konradkg Obsługujemy możliwość przesłania requestu z parametrem state. Czy próbowałeś takie wywołanie?

**Comment by konradkg** [comment]
@PrzemyslawLukanowski: Tak, ale brak tego w specyfikacji, więc działa trochę na "słowo honoru". W tej chwili działa wszystko po znaku `?` w uri, ale nie ma żadnej podkładki, że tego nie usuniecie pewnego dnia bez słowa.

@pkrzemo adresów redirect można ustawić max 30. 
Brak informacji gwarantującej że przekazywane "query params" będą doklejane.

**Comment by imper86** [comment]
@PrzemyslawLukanowski to może po prostu dodajcie to do dokumentacji?

**Comment by PrzemyslawLukanowski** [comment]
@konradkg @imper86 Słuszna uwaga, taka informacja zostanie dodana do dokumentacji.
