### ISSUE TITLE
Pytanie o allegromail.pl

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#2054]
Jako, że support twierdzi, że nie ma problemu, a jedyny techniczny supportu jest tutaj to ja to tu zostawię, może ktoś pójdzie po rozum do głowy i adresy w zwrotkach zostaną przywrócone:

<[adres e-mail]> (expanded from <[adres e-mail]>): host
    mx.interia.pl[217.74.65.64] said: 550 5.7.0 [SPF] host 77.55.108.145 is not
    allowed to send mail from domain allegromail.pl (in reply to RCPT TO
    command)

The following message to <[adres e-mail]> was undeliverable.
The reason for the problem:
5.x.1 - Maximum number of delivery attempts exceeded. [Default] 421-'4.7.0 [TSS04] Messages from 91.207.14.248 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html'

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
@anih Prześlij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) informację, na jaki (zamaskowany) adres email wysyłałeś wiadomość, dopisz w zgłoszeniu GitHub #2054.

**Comment by anih** [comment]
Poszły razem z całym zapisanym mailem jaki otrzymałem jako zwrotkę w ramach zgłoszenia nr 06066335

**Comment by TimothyKoval** [comment]
Czy Ty w nadawcy ustawiłeś `xxx@allegromail.pl` ?

**Comment by anih** [comment]
Nie, wysyłamy maile z `From` ustawionym na  `sklep@`
