### ISSUE TITLE
Problem z wieloma zamówieniami przy statusie 'READY_FOR_PROCESSING'

### ISSUE THREAD

**Issue by jazzi12** [allegro/allegro-api#2055]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Używając GET /order/checkout-forms?status=READY_FOR_PROCESSING
można pobrać maksymalnie 100 zamówień.

26 lipca zamówienie w 'LineItems' miało wartość boughtAt: '2019-07-26T10:57:28.945Z'
lecz nie zostało ono wykryte przez powyższy call. 

Dopiero 29 lipca payment otrzymał wartość finishedAt: '2019-07-29T10:34:05.648Z'

Ale wtedy liczba zamówień przekroczyła 100 więc powyższy call nie 'sięgał' już wstecz do tego zamówienia co spowodowało, że aplikacja nie spełniła swojej roli.

W dokumentacji jest napisane o statusie:

'READY_FOR_PROCESSING - klient wypełnił FOD i sfinalizował płatność (status: zakończona)'

Czyli sugeruje to, że płatność jest zakończona ale nie wykrył tego skrypt 26 lipca.

W jaki sposób można definitywnie sprawdzić, że płatność została zakończona?
Czy trzeba np. wraz ze statusem READY_FOR_PROCESSING sprawdzać czy istnieje wartość 'finishedAt'?

Co dokładnie oznacza wartość 'finishedAt' w obiekcie 'payment'?
Jaka jest różnica między 'finishedAt' a 'boughtAt'?

W momencie kiedy mamy sytuacje, że firma dostaje np. 1200 zamówień dziennie jak można to sprawdzić wstecz skoro używając GET /order/checkout-forms można maksymalnie pobrać 100 zamówień aby uniknąć powyższego scenariusza?

Dziękuje za pomoc

**Comment by neldh** [comment]
Tam jest 100 na jedną stronę, ale masz "paginację" (offset) i inkrementujesz go o 100 za każdym razem.
boughtAt to data kupienia (wciśniecia przycisku kupuję i płacę bodajże), a finishedAt to data zapłacenia.

**Comment by AssAssIn1909** [comment]
Istnieje jeszcze coś takiego jak Eventy i tam jest w miarę posortowane w kolejności. Ja pobieram co jakiś czas zamówienia filtrowane po dacie i statusie READY_FOR_PROCESSING, a potem sprawdzam w eventach czy nie zapodziało się jakieś zamówienie w którym klient zapłacił parę dni po zakupie ( biorę wszystkie eventy od jakiegoś punktu w czasie oraz te które dotyczą statusu READY_FOR_PROCESSING i sprawdzam sobie czy wszystkie mam w bazie, jak nie to go pobieram.

**Comment by jazzi12** [comment]
Dzieki za odpowiedź,

Rozwiązałem to tak, że nie biore **boughtAt** pod uwage tylko **finishedAt** i to robi robote bo wykrywa ostetecznie kiedy osoba zapłaciła.

Też dla pewności automatycznie co jakiś czas robie loopa, który filtruje jeszcze raz ostatnie 1000 płatności.
