### ISSUE TITLE
500 Internal Server Error (GET /offers/listing)

### ISSUE THREAD

**Issue by emptycodes** [allegro/allegro-api#2056]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy filtrze wyszukiwania o typie MULTI po podaniu więcej niż jednej opcji po wysłaniu zapytania GET jest zwracany błąd HTTP 500.

`{
   "errors":[
      {
         "code":"ERROR",
         "message":"An error has occurred",
         "details":null,
         "path":"/offers/listing",
         "userMessage":null
      }
   ]
}`

Wartości filtra "deliveryMethod" podałem po przecinku
https://api.allegro.pl/offers/listing?phrase=lenovo&sort=-startTime&deliveryMethod=5b446013580ce26bb2f9960e%2C5b446031580ce26bb2f99610&parameter.11323=2&price.to=30&sellingMode.format=AUCTION&category.id=147906

**Comment by PrzemyslawLukanowski** [comment]
Błąd tkwi w parametrze deliveryMethod. Ten zasób nie został jeszcze udokumentowany, może działać niepoprawnie.
Ponadto, jeżeli chcesz wyszukać oferty dla dwóch różnych wartości jednego parametru, hipotetycznie np. sposobów dostawy, podaj ten parametr dwa razy, czyli  offers/listing?{...}&deliveryMethod={deliveryMethodId}&deliveryMethod={deliveryMethodId}&{...}.

**Comment by neldh** [comment]
"offers/listing?{...}&deliveryMethod={deliveryMethodId}&deliveryMethod={deliveryMethodId}&{...}"

wow! A cóż to za nowa notacja? Każdy szanujący się serwer używa raczej:

"offers/listing?{...}&deliveryMethod[]={deliveryMethodId}&deliveryMethod[]={deliveryMethodId}&{...}"

**Comment by PrzemyslawLukanowski** [comment]
@neldh Nie jest no nowa notacja, należy do jednej z bardziej popularnych i nie ma przeciwwskazań, żeby jej używać.

**Comment by neldh** [comment]
Ok, dokształciłem się i widzę, że zależnie od frameworka niektóre taką notację rozumieją.
Niemniej jednak większość rozumie notację z [], a z połowa może tylko bez [], więc co do tych przeciwwskazań, to bym polemizował.
