### ISSUE TITLE
Oferty filtrowane przez lokalizacje i odległość od niej

### ISSUE THREAD

**Issue by GrzegorzWalewski** [allegro/allegro-api#2057]
Nigdzie nie mogę znaleźć w dokumentacji do Rest API opcji filtrowania po lokalizacji. Czy ta opcja istnieje i jeżeli to w jaki sposób po niej filtrować?

**Comment by PrzemyslawLukanowski** [comment]
@GrzegorzWalewski Filtrować według lokalizacji w zasobie GET /offers/listing możesz za pomocą parametru location.city={city} lub location.province={province}, gdzie province musi być przekazane dużymi literami, bez polskich znaków i z podkreślnikiem w przypadku spacji.
Zwróć uwagę na koniec odpowiedzi zasobu GET /offers/listing, zobaczysz tam wszystkie dostępny filtry oraz możliwości sortowania.
