### ISSUE TITLE
[REST API] Pobranie listy transakcji w ramach oferty

### ISSUE THREAD

**Issue by censo** [allegro/allegro-api#206]
Przygotowuję integrację platformy sprzedażowej w RoR z Allegro via rest api. Na koniec potrzebowałbym wiedzieć czy coś sprzedało się po stronie allegro, aby zaktualizować stan magazynowy po swojej stronie. Czy jest taka możliwość?

**Comment by MarcinLuczak** [comment]
@censo obecnie w REST API nie udostępniamy zasobów do obsługi sprzedaży. Możesz to zrobić za pośrednictwem WebAPI. Zapoznaj się z tym tutorialem: https://allegro.pl/webapi/tutorials.php/tutorial/id,100421

**Comment by censo** [comment]
@MarcinLuczak Czy wprowadzenie takiej funkcjonalności w RestAPI jest w planach? Jeżeli tak, to w mniej więcej w jakim czasie? Drugie pytanie: jak długo jeszce WebAPI nie będzie _deprecated_?

**Comment by MarcinLuczak** [comment]
@censo sukcesywnie rozwijamy REST API, więc docelowo planujemy także udostępnić w ten sposób obsługę sprzedaży. O dalszych zmianach w REST API I WebAPI będziemy informować w aktualnościach na obu stronach (https://allegro.pl/webapi/news.php i https://developer.allegro.pl/news/). Zachęcam do ich obserwowania.
