### ISSUE TITLE
Offer Category ID change

### ISSUE THREAD

**Issue by nikosv** [allegro/allegro-api#2060]
Is it possible to change the category id of an offer on update?
I keep getting this error:
```
{
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "You cannot change category after 12 hours from publication.",
      "details": "",
      "path": "",
      "userMessage": "You cannot change category after 12 hours from publication."
    }
  ]
}
```

Is there a workaround or best practice to change the category id of an offer?

**Comment by PrzemyslawLukanowski** [comment]
You can change category for an offer up to 12 hours, after this time it’s impossible - like the message says. 
You can create similar offer with retrieving data with GET sale/offers/{offerId} and use it with POST / PUT sale/offers with changed category.id.
