### ISSUE TITLE
markAsSent

### ISSUE THREAD

**Issue by pavelion** [allegro/allegro-api#2061]
:bulb: **Sugestia**

Why is it not possible to mark order as sent via REST API? 

We fetch orders via API, physically package it & ship, POST package numbers via API but have to login to web and mark orders as sent. It quickly becomes tedious and error prone process and we do not see the reason for not having /order/checkout-forms/{id}/mark-as-sent in public API when similar clearly exists in non-public API.

**Comment by PrzemyslawLukanowski** [comment]
We’ve already accepted this suggestion (it appeared for e.g. in [#1982](https://github.com/allegro/allegro-api/issues/1982) or [#1974](https://github.com/allegro/allegro-api/issues/1974#issuecomment-512125162)). If we decide to implement this feature, we’ll inform in the appropriate message.
