### ISSUE TITLE
Pobieranie ofert

### ISSUE THREAD

**Issue by GrzegorzWalewski** [allegro/allegro-api#2064]
Witam!
Czy jest jakakolwiek opcja pobrania danych pojedyńczego produktu?
Widziałem, że taka opcja istnieje co do produktów, ale nie widzę żeby w obiekcie oferty byl parametr po ktorym mozna byloby dojsc do tego z jakim produktem oferta jest polaczona.
Chodzi mi o dane parametryzowane, bo na ten moment z listy ofert da sie zebrac tylko cene

**Comment by GrzegorzWalewski** [comment]
A i nie sa to produkty, ktorych jestem sprzedawca

**Comment by PrzemyslawLukanowski** [comment]
W tej chwili tylko sprzedawca może zobaczyć jaki produkt ma w ofercie  i sprawdzić jego szczegóły. Nie udostępniamy tych danych publicznie w API.

**Comment by GrzegorzWalewski** [comment]
Ok, dziekuje za odpowiedz
