### ISSUE TITLE
Nieprecyzyjna dokumentacja dla obsługi błedów #errors

### ISSUE THREAD

**Issue by PabloMD** [allegro/allegro-api#2066]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ?] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dla błędu  401 dostaję taką odpowiedź:
`{
 "error": "unauthorized",
 "error_description": "Full authentication is required to access this resource"
}`

Czy ta informacja nie powinna być w takim formacie jak w dokumentacji?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować zgłoszenie - w jakim konkretnym przypadku otrzymujesz taką odpowiedź, przy wywoływaniu jakiego zasobu? Odpowiedź, jaką otrzymujesz, wygląda na zgodną z [dokumentacją](https://developer.allegro.pl/documentation/).

**Comment by PabloMD** [comment]
Może nudzę, ale czytając https://developer.allegro.pl/about/#errors mógłbym przyjąć, że każda odpowiedź z statusem >= 300 będzie miała tablicę errors i tak zaimplementowałem API, okazuje się jednak, że wcale to nie jest prawdą.
Nawet nie sprawdzałem w dokumentacji dla poszczególnych metod, bo stwierdziłem, że mam już wszystko czego mógłbym potrzebować do obsługi błędów, jednak teraz sprawdzając jest tam poprawny opis.

Generalnie chodzi mi o  stwierdzenie 'Każde błędne wywołanie API...', powinno być raczej napisane, że format odpowiedzi jest różny i opisany w dokumentacji poszczególnych method.

![image](https://user-images.githubusercontent.com/7274216/62370168-de5a5e00-b531-11e9-8728-2e4b4fb0cf0e.png)

**Comment by PawelTaberski** [comment]
@PabloMD Błędy o statusie 4xx zwracamy w statusie oAuthowym, pozostałe powinny zawierać tablicę z opisem błędu.
