### ISSUE TITLE
offer-quantity-change-commands

### ISSUE THREAD

**Issue by b-360** [allegro/allegro-api#2067]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Co jest nie tak z tą metodą offer-quantity-change-commands.
Od kilku dni przestała działać

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować problem? W jakiej dokładnie sytuacji otrzymujesz jaki błąd? Prześlij proszę  przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełen cURL z requestem i responsem, w zgłoszeniu dopisz GitHub #2067.

**Comment by b-360** [comment]
{"modification":{"changeType":"FIXED","value":15},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":xxx}]}]}

Array
(
    [id] => dad6e94c-372b-5c58-bd5f-72f3e561363e
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)

**Comment by PrzemyslawLukanowski** [comment]
To nie błąd, PUT sale/offer-quantity-change-commands/ zwraca same zera, ponieważ od momentu przesłania requesta system nie jest w stanie w tak krótkim czasie zwrócić dokładnej informacji na temat statusu wywołania. Aby sprawdzić, czy udało się zmienić ilość sztuk w ofercie, wykorzystaj zasób
[GET sale/offer-quantity-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) - w odpowiedzi otrzymasz konkretne informacje na temat statusu wywołania.

**Comment by FromAnyHole** [comment]
Pisałem już o tym kiedyś - skoro wiadomo było, że "w locie" zasób nie obsłuży wyników zleconych zadań, to po co to jest w ogóle zwracane jako pola z wartością zawsze === ZERO ? ;-) Jest ciekawiej...??

**Comment by PawelTaberski** [comment]
Możliwości te są osadzone na jednym zasobie i tak jak już udzieliliśmy odpowiedzi do sprawdzenia statusu danego zadania są dedykowane metody.

**Comment by b-360** [comment]
Rozumiem, 
Może śle sformułowałem pytanie.
Chodzi mi o to dlaczego przetwarzanie zapytania trwa tak długo?
`[message] =
[status] => SUCCESS
[scheduledAt] => 2019-08-01T18:26:20.577Z
[finishedAt] => 2019-08-02T06:32:15.247Z
 [field] => quantity
 [errors] => Array`

**Comment by PawelTaberski** [comment]
@b-360 Każda zmiana na ofercie może zająć do godziny czasu. Status SUCCESS oznacza, że oferta przeszła poprawnie weryfikację i zmiana powinna pojawić się w serwisie do godziny czasu.

**Comment by b-360** [comment]
a co z tym przypadkiem?
sale/offer-quantity-change-commands/**87effe85-5fb8-550b-b525-1f72314f8720**/tasks
Array
(
    [tasks] => Array
        (
            [0] => Array
                (
                    [offer] => Array
                        (
                            [id] => 80......37
                        )

                    [message] => 
                    [status] => NEW
                    [scheduledAt] => 2019-08-01T16:49:39.675Z
                    [finishedAt] => 
                    [field] => quantity
                    [errors] => Array
                        (
                        )

                )

        )

)
to z tego co widzę trwa troszkę ponad godzinę.

**Comment by SebastianOzdoba** [comment]
Tak się przyglądam tej dyskusji i coś mi nie pasuje. Pamiętam stwierdzenie że "zmiana stanu magazynowego może zająć do 1h", teraz widzę że czym innym jest status tasku = sukces a czym innym jest zmiana na ofercie.
Z tego powyższego rozumiem tak:
- taski przetworzą się kiedy przetworzą, nie znasz dnia ani godziny
- po uzyskaniu statusu "sukces", po 1h pojawi się to w ofercie

Zatem jak to jest, prośba o jasny przekaz i precyzyjny, bo i nasi Klienci się denerwują że czas aktualizacji stanu magazynowego jest dla nich lekko mówiąc nieoptymalny, przypominijmy że w webAPI było to "od strzała" :)

**Comment by PawelTaberski** [comment]
Zmiany w większości przypadków następują o wiele szybciej niż w godzinę, jednakże zbadałem przypadek @b-360 i rzeczywiście jest jakiś problem, sprawę zgłosiłem do odpowiedniego zespołu.
@SebastianOzdoba Otrzymanie statusu Success nie jest jednoznaczne z wprowadzeniem zmiany tylko, że oferta poprawnie przeszła walidację i tak jak napisałeś po otrzymaniu tego statusu granicznym czasem jest 1h.

**Comment by Peymanpn** [comment]
Hi guyes,

**Comment by Peymanpn** [comment]
Hi guys.
I have the same problem too and offer quantity change commands are taking too long.
the most I've seen took about 20 minutes or so.
is this gonna be fixed soon or we are doing it wrong?
I just `PUT` one order at the time with a single command Id ( I don't know if it is possible to `PUT` multiple times on one command id). is it the way?

**Comment by Onixarts** [comment]
No to nasi klienci zgłaszają, że czasy te są o wiele dłuższe. Niektóre zmiany pojawiają się dopiero po 24h. Nie mam logów.

**Comment by Onixarts** [comment]
Jak wygląda sytuacja z edycją liczby sztuk poprzez PUT na `/sale/offers/{id}`? Edytując liczbę sztuk w ten sposób dostajemy od razu informację o tym czy zmiana się powiodła, ale sama zmiana faktycznie występuje w ofercie na stronie z opóźnieniem. Czy tutaj można założyć, że jeśli walidacja się powiodła to zmiana na stronie na pewno się pojawi?

**Comment by PawelTaberski** [comment]
@Peymanpn Every task which change some elements on offer could take up to 1 hour.
@Onixarts Każda zmiana na stronie również tym zasobem może zająć do godziny, czy zmiana trwa już dłużej?

**Comment by Onixarts** [comment]
Nie, trwa kilkanaście sekund (przynajmniej na sandboxie), ale o ile w przypadku komend można odpytać o ich status wykonania o tyle w przypadku modyfikacji oferty nie ma już komendy, zatem czy jest sens w ogóle sprawdzać czy modyfikacja się wykonała czy po prostu musi się wykonać.

**Comment by PawelTaberski** [comment]
@Onixarts Jeśli nie otrzymałeś w responsie żadnego błędu to zadanie powinno się wykonać.
