### ISSUE TITLE
Błąd 404 - GET order/line-item-id-mappings

### ISSUE THREAD

**Issue by mroocoo** [allegro/allegro-api#2068]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy pobieraniu mapowań line-item-id na deal-id (order/line-item-id-mappings) dostaję błąd 404 dla kilku line-item-id.
Np dla line-item-id = c1767e26-a237-11e9-bfab-a35c2230218b (traceId zapytania: 802b413f0f7b3b96)
Listę line-item-id wyciągam chwilę wcześniej za pomocą order/checkout-forms (akurat ten line-item pochodzi z checkout-forma: c1767e2f-a237-11e9-bfab-a35c2230218b, który ma 4 niedziałające line-item'y).

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, API zwraca błąd 404. Zgłosiłem problem do odpowiedniego zespołu.
