### ISSUE TITLE
Brak możliwości pobrania wpłaty PayU o numerze 1051290104 za pomocą metody doGetMyIncomingPayments

### ISSUE THREAD

**Issue by PawelOsinski** [allegro/allegro-api#2069]
Witam. Wywołuję metodę doGetMyIncomingPayments z odpoweidnimi parametrami i zwraca mi wszystkie wpłaty po za jedną o numerze 1051290104. Login konta allegro to: alleloombard709.
Taki rezultat zwraca mi ta metoda:
object(stdClass)#16 (1) {
  ["payTransIncome"]=>
  object(stdClass)#17 (1) {
    ["item"]=>
    array(7) {
      [0]=>
      object(stdClass)#18 (14) {
        ["payTransId"]=>
        int(1051268282)
        ["payTransItId"]=>
        int(8331923510)
        ["payTransBuyerId"]=>
        int(2518479)
        ["payTransType"]=>
        string(14) "Płacę z iPKO"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(124)
        ["payTransCreateDate"]=>
        int(1564046785)
        ["payTransRecvDate"]=>
        int(1564046845)
        ["payTransPrice"]=>
        float(105)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#19 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [1]=>
      object(stdClass)#20 (14) {
        ["payTransId"]=>
        int(1051774226)
        ["payTransItId"]=>
        int(8338031476)
        ["payTransBuyerId"]=>
        int(56597484)
        ["payTransType"]=>
        string(20) "Płacę z Millennium"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(339)
        ["payTransCreateDate"]=>
        int(1564146232)
        ["payTransRecvDate"]=>
        int(1564146304)
        ["payTransPrice"]=>
        float(320)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#21 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [2]=>
      object(stdClass)#22 (14) {
        ["payTransId"]=>
        int(1052560145)
        ["payTransItId"]=>
        int(8337874243)
        ["payTransBuyerId"]=>
        int(37252037)
        ["payTransType"]=>
        string(4) "BLIK"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(49)
        ["payTransCreateDate"]=>
        int(1564346992)
        ["payTransRecvDate"]=>
        int(1564347019)
        ["payTransPrice"]=>
        float(30)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#23 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [3]=>
      object(stdClass)#24 (14) {
        ["payTransId"]=>
        int(1052765464)
        ["payTransItId"]=>
        int(8338189405)
        ["payTransBuyerId"]=>
        int(13449166)
        ["payTransType"]=>
        string(29) "Płacę przelewem tradycyjnym"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(169)
        ["payTransCreateDate"]=>
        int(1564393184)
        ["payTransRecvDate"]=>
        int(1564425225)
        ["payTransPrice"]=>
        float(150)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#25 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [4]=>
      object(stdClass)#26 (14) {
        ["payTransId"]=>
        int(1053215677)
        ["payTransItId"]=>
        int(8270286873)
        ["payTransBuyerId"]=>
        int(25073641)
        ["payTransType"]=>
        string(16) "Karta płatnicza"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(153)
        ["payTransCreateDate"]=>
        int(1564457207)
        ["payTransRecvDate"]=>
        int(1564458263)
        ["payTransPrice"]=>
        float(134)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#27 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [5]=>
      object(stdClass)#28 (14) {
        ["payTransId"]=>
        int(1053496900)
        ["payTransItId"]=>
        int(8337848774)
        ["payTransBuyerId"]=>
        int(17582234)
        ["payTransType"]=>
        string(23) "Płacę z Alior Bankiem"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(99)
        ["payTransCreateDate"]=>
        int(1564492937)
        ["payTransRecvDate"]=>
        int(1564493027)
        ["payTransPrice"]=>
        float(80)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#29 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
      [6]=>
      object(stdClass)#30 (14) {
        ["payTransId"]=>
        int(1054107227)
        ["payTransItId"]=>
        int(8248397911)
        ["payTransBuyerId"]=>
        int(42883661)
        ["payTransType"]=>
        string(16) "Karta płatnicza"
        ["payTransStatus"]=>
        string(11) "Zakończona"
        ["payTransAmount"]=>
        float(639)
        ["payTransCreateDate"]=>
        int(1564585481)
        ["payTransRecvDate"]=>
        int(1564585495)
        ["payTransPrice"]=>
        float(620)
        ["payTransCount"]=>
        int(1)
        ["payTransPostageAmount"]=>
        float(19)
        ["payTransDetails"]=>
        object(stdClass)#31 (0) {
        }
        ["payTransIncomplete"]=>
        int(0)
        ["payTransMainId"]=>
        int(0)
      }
    }
  }
}

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś problem, sprawę zgłosiłem do odpowiedniego zespołu.

**Comment by PawelOsinski** [comment]
Dziękuję i czekam na więcej informacji

**Comment by PawelOsinski** [comment]
Udało się już może coś ustalić?

**Comment by PawelTaberski** [comment]
Pracujemy jeszcze nad rozwiązaniem tego problemu.

**Comment by PawelOsinski** [comment]
ok
