### ISSUE TITLE
[REST API] Doprecyzowanie polecenia Change Price Command

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#207]
Reuqest Change Price Command posiada atrybut MonetaryAmount, lecz według definicji jest on pusty. Nie bardzo rozumiem jak to interpretować. Bardzo proszę o jakis przykład requesta.

**Comment by MarcinLuczak** [comment]
@kylovile jesteś pewny, że wskazałeś dobry zasób? Nie ma w nim takiego atrybutu.

**Comment by kylovile** [comment]
Chodzi mi o atrybut buyNowPrice. Wygląda to tak jakby nie miał ciała.

![image](https://user-images.githubusercontent.com/39157522/39910566-2aa50580-54f8-11e8-9bf8-eda05ff8dc9d.png)

**Comment by MarcinLuczak** [comment]
@kylovile słuszna uwaga. Tam powinny być pola dotyczące kwoty i waluty. Przykład:

```
{
  "id": "wartość_commandId",
  "input": {
    "buyNowPrice": {
      "amount": "10",
      "currency": "PLN"
    }
  }
}
```
Przekażę zgłoszenie do odpowiedniego działu.

**Comment by kylovile** [comment]
Dziękuje za odpowiedz i poprawienie dokumentacji, lecz mam kolejny problem. Otóź response z serwera brzmi: "(405) Method Not Allowed".

**Comment by MarcinLuczak** [comment]
@kylovile udostępnij proszę curla requesta oraz response jaki dostałeś.

**Comment by kylovile** [comment]
@MarcinLuczak udało mi się problem zdiagnozować. Ruquest wyglądał na pierwszy rzut oka dobrze, poza METHOD. Mialem ustawiony na POST a powinien być PUT ;)

**Comment by MarcinLuczak** [comment]
@kylovile no i wszystko jasne. Dzięki za informację.
