### ISSUE TITLE
[Sugestia] Applikacja Sandbox bez sprawdzania URI

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2070]
:bulb: **Sugestia**

Proponuję aby w rejestracji aplikacji w środowisku testowym ( https://apps.developer.allegro.pl.allegrosandbox.pl/ ) w polu "Adresu URI do przekierowania" nie wymagać istnienia adresu URL i sprawdzać tylko poprawność URI.

Czyli np. wprowadzenie
`https://allegro.devo/listener/`
nie zwracało
`Adresy przekierowań powinny być poprawnymi adresami URL.`

Wiem, że można użyć localhost i przekierować (301 z zmienną code na swoją aplikację), ale wolę virtualhost.

**Comment by PawelTaberski** [comment]
Jeśli adres przekierowania jest dla Ciebie problemem, pamiętaj, że zawsze możesz zarejestrować aplikację jako DEVICE i skorzystać z odpowiedniego flow, które opisaliśmy [tutaj](https://developer.allegro.pl/auth/#DeviceFlow).

**Comment by neldh** [comment]
@PawelTaberski jeśli człowieka interesuje  redirect url to raczej nie chce DEVICE flow :]

**Comment by PawelTaberski** [comment]
@neldh Odebrałem to jako problem, niemniej oczywiście przekazałem Twoją sugestię @Radeq do odpowiedniego zespołu. Jeśli wdrożymy taką zmianę, to poinformujemy o niej w odpowiednim komunikacie.
