### ISSUE TITLE
Wyszukiwarka Allegro - problem z właściwością cudzysłów

### ISSUE THREAD

**Issue by array3** [allegro/allegro-api#2071]
Od około trzech dni wyszukiwarka Allegro nie działa poprawnie, zarówno poprzez stronę jak i poprzez API.

Oto przykłady, które należy wpisać w wyszukiwarce na głównej stronie:
1.  "akwarium" ("30l" "50l") wyposażenie
Zwraca wyniki (raczej ok).
2. "akwarium" ("30l" "50l") "wyposażenie"
Nie zwraca wyników.

3. taśma "matrycy" "lenovo" t400
Zwraca wyniki jak w przykładzie 1. (raczej ok).
4. "taśma" "matrycy" "lenovo" t400
Nie zwraca wyników, czyli jak w przykładzie 2.
5. taśma "matrycy" "lenovo" "t400"
Nie zwraca wyników, a tego zupełnie nie rozumiem. Jak w przykładzie 2. i 4. w cudzysłów szły wyrazy z polskimi znakami, to jest jakiś schemat błędu. Natomiast tutaj jest to zupełnie nie logiczne ponieważ w wyszukiwaniu występują wyniki z pełnymi wyrażeniami "t400".

Bardzo proszę o sprawdzenie tego problemu.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, korzystasz z odpowiednich parametrów, czy całość jest jako zapytanie? Wklej proszę tutaj przykładowe zapytanie w postaci cURL-a bez takich danych jak access token itp.

**Comment by array3** [comment]
Bez żadnych dodatkowych parametrów, na razie chodzi mi o samą frazę... Parametry działają raczej prawidłowo, przynajmniej ja nie zauważyłem jakiś nieprawidłowości.

Zawsze mogą Państwo sprawdzić podane frazy wpisując w wyszukiwarce na głównej stronie Allegro, ale jeżeli będzie taka konieczność to podam też ich cURL-e, chociaż tak jak zaznaczyłem, API zachowuje się podobnie dla GET /offers/listing i parametru phrase z przykładów 1-5.

**Comment by PawelTaberski** [comment]
Przetestowałem na:
/offers/listing?phrase="akwarium"+("30l" "50l")
i w wyniku otrzymałem 254 wyniki tak samo na froncie.
Wydaje się, że wszystko działa prawidłowo.

**Comment by array3** [comment]
Szanujmy się... To nie są poważne odpowiedzi.
Proszę sprawdzić:
1. "akwarium" ("30l" "50l") wyposażenie
2. "akwarium" ("30l" "50l") "wyposażenie"

**Comment by PawelTaberski** [comment]
Faktycznie mój błąd nie skopiowałem całego zapytania masz rację. Sprawę przekazałem do głębszej analizy do zespołu, który odpowiada za te zasoby jak tylko otrzymam jakieś informacje dam znać. Dzięki za szybką reakcję.

**Comment by array3** [comment]
Ok, zdarza się. Proszę sprawdźcie to jak najszybciej, 2-3 dni temu było OK, teraz tak nie jest. Nie chodzi tutaj wyłącznie o polskie znaki w cudzysłowie, ponieważ przykład 5. też obrazuje jakiś inny problem z tym cudzysłowem.
To jest dosyć poważny błąd, ponieważ wiele aplikacji nie może korzystać z zaawansowanego wyszukiwania.

**Comment by PawelTaberski** [comment]
Otrzymałem informację, że udało się namierzyć problem i już pracujemy nad jego usunięciem.

**Comment by array3** [comment]
Zauważyłem, że problem został częściowo rozwiązany, tj. puste wyniki nie są już zwracane. Jednak rezultaty dla wielu przykładów nie są do końca tymi jakie są oczekiwane. W skrócie, cudzysłów nie spełnia swojej funkcji.

Przykład:

5. taśma "matrycy" "lenovo" "t400"
Zwracane wyniki zawierają w treści **t400s**.
6. "t-1000"
Zwracane wyniki zawierają w treści np. **DVB-T 1000** lub **1T 1000kg**.

Jeżeli sprawa nadal jest w trakcie rozwiązywania, to proszę potraktować to informacyjnie.

**Comment by PawelTaberski** [comment]
@array3 Tak, zespół pracuje jeszcze nad tym problemem. Przekazałem im te informacje,

**Comment by PawelTaberski** [comment]
@array3 Wprowadziliśmy zmiany, dzięki którym wyszukiwanie powinno działać już poprawnie. Jeśli zauważysz jeszcze jakieś nieprawidłowości daj proszę znać.

**Comment by array3** [comment]
Rzeczywiście część problemów została rozwiązana tj. problemy opisane w punktach 1-5.
Natomiast z przykładem 6. jest bardzo dziwna sytuacja, ponieważ co prawda ten przykład działa, ale już te zwracają błędne wyniki lub wcale ich nie zwracają:

7. "15-g"
Zwraca błędne wyniki np. **15g** lub **3-15g**
8. "B156XTN02.0"
Nie zwraca wyników wcale.

**Comment by PawelTaberski** [comment]
Przekazałem te informacje do odpowiedniego zespołu.

**Comment by array3** [comment]
Czy są jakieś nowe informacje na temat postępów w pracach nad poprawą wskazanych błędów wyszukiwarki?

**Comment by PawelTaberski** [comment]
Dostałem informacje, że problem nie powinien już występować. @array3 Daj proszę znać, czy ciągle obserwujesz jakieś nieprawidłowości.

**Comment by array3** [comment]
Rozumiem, ale problem nadal występuje i niestety bardzo utrudnia nam pracę.
Pozwolę sobie rozwinąć przykłady 7. i 8., aby można było dokładnie przekazać w czym jest istota problemu.

7. "15-g"
- oczekiwane wyniki to wszystkie które w tytule zawierają wyrażenie **15-g** (bez żadnych znaków przed oraz po tym wyrażeniu oraz bez usuwania znaku "-")
- przykładowe (błędnie) zwracane wyniki:
WĘDKA JAXON ARCADIA SPINNING JIG 2,4m 3-**15g** OKOŃ // wycięty znak "-" i dodane przed "3-"
ECOCERA Fixer puder ryżowy **15g** // wycięty znak "-"
LD SYSTEMS DAVE **15G3** - 700 W // wycięty znak "-" oraz dodana cyfra "3"
KLAWIATURA HP **15-g003sw 15-g005sw 15-g013sw** // dodane 5 znaków na końcu wyrażenia

8. "B156XTN02.0"
- oczekiwane wyniki to wszystkie które w tytule zawierają wyrażenie **B156XTN02.0** (bez żadnych znaków przed oraz po tym wyrażeniu oraz bez usuwania znaku ".")
- przykładowe (błędnie) zwracane wyniki:
NOWA B156XTN01.0 **B156XTN02.6** CLAA156WA12 FV 30Pin // inna cyfra po kropce, "6" zamiast "0"
Matryca LCD 15,6 **B156XTN02 .0** HW4A Gloss 40p A- // spacja przed kropką

**Comment by PawelTaberski** [comment]
@array3 Rozumiem, przekazałem te informacje.
