### ISSUE TITLE
pobranie kategorii

### ISSUE THREAD

**Issue by tomos2105** [allegro/allegro-api#2072]
Czy istnieje możliwość pobrania całego drzewa kategorii w rest api? chciałbym pobrać całe drzewo do bazy danych w sklepie internetowym.

**Comment by PawelTaberski** [comment]
Istnieje możliwość pobrania całego drzewa serią zapytań, więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-2).
