### ISSUE TITLE
Identyfikator transakcji na stronie allegro

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2074]
Czy da się jakoś uzyskać identyfikator transakcji z poziomu allegro ?
Chodzi o to że domyślnie pobieram tylko te o statusie READY_FOR_PROCESSING ale zdarzają sytuację że trzeba pobrać zamówienie BOUGHT.
Tylko żeby pobrać jedno konkretne zamówienie muszę je jakoś jednoznacznie zidentyfikować.
Dalego byłby fajne jakby w zamówieniach  na allegro.pl dało się jakoś pobrać np. checkoutForm->id.

Nie musi to być sposób "oczywisty", przykładowo  jeśli potrzebowałbym identyfikator płatności to mogę kliknąć na akcje => zwróć wpłatę i wtedy identyfikator płatności jest w pasku adresu. Coś w tym stylu byłby dla mnie wystarczające.

Da się to jakoś zrobić ?

**Comment by PawelTaberski** [comment]
Odnośnie zarządzania zamówieniami powinieneś się zapiąć na dziennik GET /order/events aby nie przegapić żadnego zdarzenia i w nim otrzymujesz m.in. identyfikator zamówienia.
Więcej na ten temat znajdziesz w poradniku: [Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/)

**Comment by mzawodzinski** [comment]
Tak, właśnie przy pomocy  GET /order/events pobieram listę zamówień READY_FOR_PROCESSING.

Ale tak jak pisałem czasami magazyn chce żeby pobrać zamówienie BOUGHT,
w takim przypadku najłatwiej byłby wejść na allegro.pl, skopiować jego numer i wstawić na listę "do pobrania".
Obecnie robię to w taki sposób że "ręcznie" wyszukuję w eventach po loginie konkretną transakcję i dopiero przekazuję ją do pobrania. A tak mogliby robić ludzie bezpośrednio z magazynu.

**Comment by PawelTaberski** [comment]
W zakładce zamówienia nie zwracamy numeru checkoutForm-a. W przypadku zamówień tylko o statusie BOUGHT, bądź FILLED_IN warto odnotowywać takie eventy, jeśli nie przeszły na status READY_FOR_PROCESSING w określonym czasie. Może to oznaczać, że niezbędny będzie kontakt z kupującym. M.in. aby ułatwić kontakt w takich sytuacjach rozbudowaliśmy sekcję buyer #2073
