### ISSUE TITLE
awaria /sale/images upload obrazków

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#2075]
Od kilku godzin u naszych klientów otrzymujemy błąd przy próbie wgrania zdjęcia z pliku na API produkcyjnym, nic nie zmienialiśmy po naszej stronie, dla testów wywołanie curlem również nie działa:

```
curl -X POST 'https://upload.allegro.pl/sale/images' -H 'Authorization: Bearer {token}' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: "image/jpeg"' -H 'Accept-Language: pl-PL' --data-binary "/example/file/url.jpg"
```

oczywiście token i ścieżka pliku wycięte, odpowiedź:

```
{"errors":[{"code":"ERROR","message":"Unsupported Media Type","details":null,"path":"/sale/images","userMessage":null}]}
```

wgranie zdjęcia drugą metodą czyli po url działa ok.

**Comment by PawelTaberski** [comment]
Podeślij proszę trace-id przykładowego zadania w którym wystąpił taki problem.

**Comment by j4r3kb** [comment]
```
curl -i -X POST 'https://upload.allegro.pl/sale/images' -H 'Authorization: Bearer {token}' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: "image/jpeg"' -H 'Accept-Language: pl-PL' --data-binary "/home/jarek/Pictures/cat.jpg"
```

```
HTTP/2 415 
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 8fcf062d927e441b
referrer-policy: no-referrer
date: Fri, 02 Aug 2019 13:52:15 GMT
x-ratelimit-remaining: 8983
x-content-type-options: nosniff
content-type: application/json
content-length: 120
x-ratelimit-limit: 9000

{"errors":[{"code":"ERROR","message":"Unsupported Media Type","details":null,"path":"/sale/images","userMessage":null}]}
```

**Comment by j4r3kb** [comment]
jeszcze jeden trade-id d3ebaa3befc6a5bd

**Comment by PawelTaberski** [comment]
Wygląda to na błąd, sprawę przekazałem do weryfikacji do zespołu, który odpowiada za ten zasób.

**Comment by j4r3kb** [comment]
Proszę dziś o informację w temacie, blokuje to naszym klientom wystawianie aukcji.

**Comment by PawelTaberski** [comment]
@j4r3kb Pracujemy nad rozwiązaniem tego problemu, proszę podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładową grafikę z którą masz problem. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 2075 na GitHub-ie.

**Comment by j4r3kb** [comment]
Grafika jest dowolna, próbowałem jpg, png. Nic nie działa.
Proszę 
`https://upload.wikimedia.org/wikipedia/commons/2/22/Turkish_Van_Cat.jpg` to też nie działa.

**Comment by PawelTaberski** [comment]
@j4r3kb  Udał się nam wykryć co jest problemem, w nagłówku Content-Type przesyłasz wartość w cudzysłowie a powinno być bez.

**Comment by j4r3kb** [comment]
Niestety to nie to, sprawdzałem to już wcześniej.
Proszę:

```
curl -i -X POST 'https://upload.allegro.pl/sale/images' -H 'Authorization: Bearer {token}' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: image/jpeg' -H 'Accept-Language: pl-PL' --data-binary '/Pictures/1.jpg'
```

```
HTTP/2 415 
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: ae6745c8113e3c75
referrer-policy: no-referrer
date: Mon, 05 Aug 2019 08:56:30 GMT
x-ratelimit-remaining: 8932
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 135
x-ratelimit-limit: 9000

{"errors":[{"code":"415 UNSUPPORTED_MEDIA_TYPE","message":null,"details":null,"path":null,"userMessage":"Niedozwolony typ zdjęcia."}]}
```

**Comment by PawelTaberski** [comment]
@j4r3kb Podeślij proszę przez formularz kontaktowy ten konkretny obrazek z wywołania.

**Comment by j4r3kb** [comment]
To jest ten który podałem wcześniej `https://upload.wikimedia.org/wikipedia/commons/2/22/Turkish_Van_Cat.jpg` chyba nie musimy sobie tak życia utrudniać formularzami?

**Comment by PawelTaberski** [comment]
W tym wypadku problemem jest ścieżka do pliku powinno być @/Pictures/1.jpg a nie /Pictures/1.jpg
W kwestii obrazka miałem na myśli faktyczny obrazek jaki przesyła Twój klient w przypadku którego wystąpił błąd, którego trace-id z serwera produkcyjnego podałeś wcześniej.

**Comment by j4r3kb** [comment]
OK do CURLa to z @ działa.

trace id `8ca57ae22ea28e2e`
obrazek 

![zestaw-figurek-rakieta-kosmiczna-z-ramp-startow_0](https://user-images.githubusercontent.com/16531572/62457132-6468e580-b77a-11e9-8064-08c70c76fd09.jpg)

**Comment by j4r3kb** [comment]
@PawelTaberski coś wiadomo nowego w temacie?

**Comment by PawelTaberski** [comment]
@j4r3kb Badamy jeszcze ten przypadek.

**Comment by j4r3kb** [comment]
@PawelTaberski może coś się z w piątek zmieniło odnośnie tego endpointa i metdoy?
W dokumentacji jest jedynie opisana metoda przesyłania obrazków poprzez podanie 'url' to przypuszczam działa.
Sposób z wysyłaniem base64 jest opisany jedynie w poradniku i to też dość szczątkowo https://developer.allegro.pl/sale/#step-3-images
Może doszedł lub został odjęty parametr do requestu?
Nie mamy jak po naszej stronie tego już weryfikować bo API odpowiada 400 i żadnej dodatkowej wiadomości nie ma.

**Comment by PawelTaberski** [comment]
@j4r3kb Badamy ten przypadek jak tylko otrzymam jakieś dodatkowe informacje, to poinformuje Pana.

**Comment by PawelTaberski** [comment]
@j4r3kb Zasad działania samego API nie zmienialiśmy. Niestety nie udało nam się zreprodukować Twojego problemu. Czy jesteś w stanie przygotować skrypt/fragment kodu, który pozwoli nam powtórzyć problem? 
Co masz na myśli przez sposób wysyłania z base64, bo nie mamy wysyłania base64 tylko binarnie.

**Comment by j4r3kb** [comment]
@PawelTaberski wiemy prawdopodobnie co zmieniliście w piątek.
Dodana została weryfikacja nagłówka Host, z naszej strony był wysyłany nagłówek
`Host: upload.allegro.pl:`
dwukropek na końcu był naszym błędem, wysyłany był cały czas od początku naszego wdrożenia i problemów nie było także weryfikacja po stronie API doszła bez informacji o tej zmianie.

**Comment by PawelTaberski** [comment]
Rozumiem, oczywiście sugestię odnośnie walidacji błędu przekazałem.

**Comment by j4r3kb** [comment]
@PawelTaberski prosiłbym również o uzupełnienie dokumentacji https://developer.allegro.pl/documentation/#tag/Images-and-attachments jak i poradnika w tym zakresie.
Można zamknąć.

**Comment by PawelTaberski** [comment]
@j4r3kb Uszczelnienie walidacji nagłówka Host nie było naszą celową zmianą, wynikało z podbicia wersji wykorzystywanej biblioteki.

**Comment by j4r3kb** [comment]
W changelogu tej biblioteki nic nie było? :)
