### ISSUE TITLE
problem ze wznawianem ofert

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#2076]
Mam problem z aktywacją ofert. Mam co najmniej kilkaset ofert posiadających poprawną walidację, których próba wznowienia kończy się komunikatem błędu: Could not change offer publication status, may no be empty. Przy czym co niby jest empty to z tego komunikatu już nie wynika.

przykładowe numery ofert: 8358763462, 8367089792

proszę o informację co jest przyczyną błędu.

**Comment by grzluk** [comment]
Przy wznawianiu musisz wyczyścić zmienną offer->publication->status, "may no be empty" oznacza że nie jest ona pusta a musi być żeby aukcja przeszła ponownie weryfikację.

**Comment by MaciejFrackowiak** [comment]
W przypadku oferty 8358763462 próbowałeś zakończyć ofertę, która jest szkicem - a ten można tylko usunąć.
Natomiast w przypadku oferty 8367089792 problem przekazuję do weryfikacji.

Status operacji możesz zawsze sprawdzić korzystając z metody [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET)

**Comment by jakubmaguza** [comment]
Dodam od siebie, że praktycznie przy każdym wystawianiu nowych ofert, część z nich zostaje w szkicach. Niektóre mają problemy i trzeba je poprawić, ale prawie zawsze znajdzie się kilka ofert które nie mają problemów i wystarczy na froncie kliknąć "Wznów"

**Comment by dostawcaopon** [comment]
MaciejFrackowiak - ja mam problem z aktywowaniem a nie z zakańczaniem.
co do oferty 8358763462
walidacja zwraca taki ciąg:
 ,"validation":{"errors":[{"code":"VALIDATION_ERROR","message":"may not be empty","details":"","path":"","userMessage":"may not be empty"}],"validatedAt":"2019-07-31T22:12:19.094Z"},"createdAt":"2019-07-31T22:12:19Z","updatedAt":"2019-07-31T22:12:19.094Z"}

co jest nie tak z tym szkicem, dlaczego nie przechodzi walidacji? Komunikat "may not be empty" czego się dokładnie tyczy?

**Comment by dostawcaopon** [comment]
nie wiem czy ma to związek z tematem, ale teraz mam problem wiszącymi taskami
np
https://api.allegro.pl/sale/offer-publication-commands/ee031447-c912-4995-a1a9-89e1548188ff
task zawiera żądanie zmiany publikacji na END dwóch ofert, wisi już od 20 minut i podejrzewam, że prędko nie skończy.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi dla przytoczonego commandId - skuteczne zakończenie ofert nastąpiło już 2019-08-06 15:06:47 oraz 2019-08-06 15:06:59. W kolejnych próbach powtarzałeś operację END dla zakończonych już ofert.

Status operacji możesz zawsze sprawdzić metodą [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET)

**Comment by dostawcaopon** [comment]
To jeszcze tylko proszę o pomoc w odszyfrowaniu błędu walidacji "may not be empty" - czego on konkretnie dotyczy
id np 8373370180

**Comment by MaciejFrackowiak** [comment]
Kwestię pojawiającego się komunikatu przekazałem do weryfikacji, o czym wspomniałem już. Oczekuję na odpowiedź.

**Comment by grzluk** [comment]
"may not be empty" dotyczy zmiennej publication.status. "may not be empty" = "może nie być pusta" co jasno oznacza że ta zmienna MUSI być pusta. W PHP robisz to tak: unset($offer->publication->status). W innych językach nie wiem ale generalnie ten błąd oznacza w 100% właśnie to. Chcesz to czekaj dalej na odpowiedź, ale polecam spróbować wtedy zobaczysz że właśnie tak jest. źle zrozumiałeś komunikat który nie oznacza że czegoś brakuje, coś jest puste tylko właśnie to że coś co ma być puste nie jest w tym przypadku zmienna publication.status.

**Comment by TimothyKoval** [comment]
May not be empty znaczy nie może być puste. Chyba, że jesteś z Allegro, wtedy może znaczyć wszystko :)

**Comment by grzluk** [comment]
@TimothyKoval kolejny "mądry" czy wy ludzie wogóle umiecie angielski? Polecam powrót do szkoły ile można to samo powtarzać, "May not be empty" oznacza dokładnie "Może nie być pusta" = "Możliwe że nie jest pusta" = "MUSI BYĆ PUSTA". Zamknijcie już ten temat na boga bo płakać się chce, @MaciejFrackowiak to też widze "specjalista"

**Comment by TimothyKoval** [comment]
may not be empty a may be not empty to lekka różnica. Zastanów się czy może Ty nie powinieneś wrócić do szkoły, tym razem może nie siadać w ostatniej ławce.

**Comment by grzluk** [comment]
Nie chcę się kłócić ale rozwiązanie w postaci usunięcia zmiennej publication.status poprostu działa co sugeruje że ten komunikat oznacza właśnie to co napisałem. Poczekajmy może autor spróbuje tego rozwiązania i da znać jak poszło. Pracuje z API Allegro od 2 lat i znam je prawie na wylot, uwierz mi też miałem podobny problem. Przykład: funkcja klonująca aukcję i zmieniająca jej tytuł zaczyna się tak:
`function clone_auction($offer,$newTitle,$allegroApi,$cloud,$reference,$id_allegro_product)
{

unset($offer->id);
unset($offer->publication);
unset($offer->validation->validatedAt);
unset($offer->createdAt);
unset($offer->updatedAt);
$offer->name = "$newTitle";`

**Comment by TimothyKoval** [comment]
Nie chcesz się kłócić, ale obrażać obcych ludzi to już nie problem.

Nie twierdzę, że nie działa, bo wiem że działa. Problemem jest komunikat błędu, który nic mądrego nie mówi, a do tego jest błędnie napisany.

**Comment by andyen-debug** [comment]
Sprawa jest już załatwiona. Wysyłałem szkice z pustym polem 'product' a ono nie może być puste, musi posiadać wartosc id lub w ogole nie może go być . Problem polgał na tym, że komunikat błędu nie wskazywał, że chodzi o 'product', zgłosiłem to do Allegro jako coś do poprawienia i tyle.

**Comment by dostawcaopon** [comment]
Sprawa jest już załatwiona. Wysyłałem szkice z pustym polem 'product' a ono nie może być puste (may not be empty), musi posiadać wartosc id lub w ogole nie może go być . Problem polegał na tym, że komunikat błędu nie wskazywał, że chodzi o 'product', Zgłosiłem to do Allegro jako coś do poprawienia i tyle.
Temat do zamknięcia.

**Comment by neldh** [comment]
@grzluk 
Sorry że się wtrącam, ale nie wytrzymałem xD. Cytując:
<<"Możliwe że nie jest pusta" = "MUSI BYĆ PUSTA">>
Ty to chyba z logiki pałę miałeś natomiast...
0 to nie null,
ostrzeżenie to nie warunek, itd. itp
Komunikat jest po prostu przytłaczająco wręcz nieczytelny.
<<Pracuje z API Allegro od 2 lat i znam je prawie na wylot>>
To nie znaczy, że jest to API bez wad, a wady należy likwidować, jeśli można. Chyba, że chce się stać w miejscu...
@TimothyKoval 
<<Nie chcesz się kłócić, ale obrażać obcych ludzi to już nie problem. Nie twierdzę, że nie działa, bo wiem że działa. Problemem jest komunikat błędu, który nic mądrego nie mówi>>
O to to!
