### ISSUE TITLE
Szybka zmiana Czas wysyłki "handlingTime" zbiorczo

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2077]
:bulb: **Sugestia**

Jak w tytule możłiwość szybkiej zmiany Czas wysyłki "handlingTime" zbiorczo
a lub nawet przez nową metodę lub inne rozwiązanie podpieciu feeda produktowego z czasami wysyłki.

Czemu / po co ?

Czasy wysyłek dostępności towarów są pobierane z magazynu zbiorczego aktualizacje pasuje robić co godzinę (aby klienci nie kupowali towaru z info że wysyłka np. 24 a a okazuje się że za 30 dni bo partia już sięs kończyła - potem same problemy, niezadowlony kient kupił a towaru nie ma, problemy z zwrotami prowizji itp...)

Wiem że niby powinno być aukcji jak się towaru nie ma ale przy dużej liczbie aukcji i rotacji bez automatyzacji nie da się tego ogarnąć.

A jak automatyzacja to am działać szybko i sprawnie.
A edycja kilkuset aukcji codziennie będzie bardzo długo trwała oraz jest zasoborzerna...

Inne opcja to możłiwość podpięcia do całej oferty pliku z czasami wysyłki (tylko tym parametrem a idąc dalej to z całym opisem oferty tak jak pliki produktowe np. do google merchant)
I aby reszta byłą już robiona po stronie allegro w okreśłonym interwale czasowym.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię.
Przekazałem do odpowiedniego zespołu, jeśli wdrożymy takie rozwiązanie to poinformujemy o tym w dedykowanym komunikacie.
