### ISSUE TITLE
Notyfikacje mailowe dla nowości

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2079]
Hej!

Czy jest gdzieś miejsce, w którym można zostawić maila, na którego będę dostawał informacje o zmianach i nowościach? Niestety nie chcę dostawać na skrzynkę wszystkich wiadomości z zakładki issues, a github jeszcze nie pozwala na notyfikację dla wybranych labelów.

Dobrego dnia!

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy takiej funkcjonalności.
Pracujemy nad nowym portalem, w którym wdrożymy taką funkcjonalność, jednakże nie jestem w stanie powiedzieć kiedy go wdrożymy.

Każdą zmianę i informacje o nowościach oznaczamy znacznikiem [NEWS] w tytule - w kliencie pocztowym możesz stworzyć regułę na takie wiadomości.

**Comment by jakubmaguza** [comment]
> Pracujemy nad nowym portalem, w którym wdrożymy taką funkcjonalność, jednakże nie jestem w stanie powiedzieć kiedy go wdrożymy.

Na jakim etapie są prace? Minęły już prawie dwa lata.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, mamy to cały czas na uwadze, jednak na chwilę obecną nadal nie mogę wskazać jednoznacznego terminu.

**Comment by jakubmaguza** [comment]
Jeśli mogę coś zasugerować, to odpalcie zwykły prosty mailing. Nie trzeba żadnych skomplikowanych serwisów.

**Comment by MaciejFrackowiak** [comment]
Chcemy podejść do kwestii kompleksowo, dlatego nie chcemy tworzyć "doraźnych" rozwiązań. Bieżące wiadomości znajdziesz zawsze na stronie [Aktualności](https://developer.allegro.pl/news/) oraz w powiadomieniach z GitHub z tytułem [NEWS].

**Comment by jakubmaguza** [comment]
Doskonale was rozumiem, tylko że ta doraźność rozwiązałaby problem od razu,
a kompleksowość każe czekać pewnie następne dwa lata.

W każdym razie czekam niecierpliwie.

---
Pozdrawiam,
Jakub Maguza

wt., 13 kwi 2021, 14:29 użytkownik MaciejFrackowiak <
***@***.***> napisał:
