### ISSUE TITLE
[WebAPI] doGetItemFields FID: 27

### ISSUE THREAD

**Issue by bartek171020** [allegro/allegro-api#208]
Mam uparcie zwracaną nieaktualną wartość pola dodatkowej informacji o dostawie (FID: 27). Na aukcji widoczna jest właściwa (ustawiona). W danych zwracanych metodą doGetItemFields jest ten który już nie jest aktualny i jest niezgodny ze stanem aktualnym. Problem dotyczy wielu aukcji, a przykładowy numer to: 5757642881.

**Comment by bartek171020** [comment]
Aktualnie nie mogę zrzucić całego XML, ale w odpowiedzi na metodę doGetItemFields w FID: 27 mam zwracanego string o wartości: "Składając zamówienie do godziny 12:00 dnia roboczego gwarantujemy realizację tego samego dnia! Przy zakupie ilości sztuk powyżej 18 czas wysyłki może ulec wydłużeniu do 7 dni.". Aktualna wartość na aukcji jest: "Przy zakupie ilości sztuk powyżej 10 czas wysyłki może ulec wydłużeniu do 7 dni.". Skąd ta rozbieżność?

**Comment by bartek171020** [comment]
Przesyłam XML'e. Zwrócone dane są niezgodne z aktualnym stanem. FID: 27 ma już dawno inną wartość.
[SOAP_last_request.txt](https://github.com/allegro/allegro-api/files/1992597/SOAP_last_request.txt)
[SOAP_last_response.txt](https://github.com/allegro/allegro-api/files/1992598/SOAP_last_response.txt)

**Comment by bartek171020** [comment]
Czy może wiadomo już coś o planowym usunięciu problemu. Moje oprogramowanie trochę się burzy na brak aktualnej wartości i stąd moje pytanie.

**Comment by MarcinLuczak** [comment]
@bartek171020 na razie nie. Dam znać, gdy coś się zmieni.
