### ISSUE TITLE
Obsługa zwrotów

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#2080]
Witam, widzę że pojawiła się możliwość wykonania zwrotu i pobrania wykonanych zwrotów. A czy jest lub kiedy będzie możliwość pobrania zwrotów zrobionych przez klienta i pobrania danych do zwrotu?

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy jeszcze takiej metody obsługującej zwroty klientów.
Mamy ją na liście sugestii dot. rozwoju Rest API.

**Comment by Przem4S** [comment]
Jakieś nowe informacje na temat zwrotów? Kiedy będzie planowana ich osługa po stronie API?

**Comment by PatrykBocian** [comment]
Planujemy wprowadzić taką funkcjonalność w tym kwartale - gdy tak się stanie to poinformujemy o tym w odpowiednim komunikacie. Informacje o planowanych funkcjonalnościach, znajdziesz w naszym [harmonogramie](https://developer.allegro.pl/schedule/).
