### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2081]
:bulb: **Sugestia**
Hej!
Zastanawiam się, jak najłatwiej sprawdzić czy token działa. Niestety nie znalazłem żadnej metody typu "Hello". Czy moglibyście coś takiego dodać?
Dobrego dnia!

**Comment by MaciejFrackowiak** [comment]
Pracujemy nad zasobem, którego wywołanie z aktywnym tokenem zwróci podstawowe informacje o zalogowanym użytkowniku. Więcej informacji podamy wkrótce.

Każdy token jest w technologii JWT, możesz go rozkodować - w środku znajdziesz datę ważności tokena. Otrzymany token możesz wkleić np. do formularza dostępnego na [jwt.io](https://jwt.io)

**Comment by jakubmaguza** [comment]
Dziękuję za odpowiedź.
Tak, w tokenie jest informacja, dodatkowo podajecie ją przy autoryzacji.
Jakiś czas temu pojawiały się komentarze, że niektóre tokeny były losowo unieważniane. Takie coś może się zdarzyć, stąd moja troska o sprawdzenie czy token rzeczywiście działa.

**Comment by MaciejFrackowiak** [comment]
W tym celu wspomniane prace nad zasobem, który takowe dane zwróci.
