### ISSUE TITLE
Generowanie Tokenu

### ISSUE THREAD

**Issue by MLupinski** [allegro/allegro-api#2083]
Witam.
Próbuję zrobić połączenie w javie za pomocą konsoli z Państwa REST API, doszedłem już do tego, że bez przeglądarki nie bardzo uda mi się zautoryzować i uzyskać token, chyba, że jest gdzieś może jakiś poradnik to bardzo bym prosił o link.

Jednak piszę z inną sprawą, ponieważ konsola uruchamia przeglądarkę z adresem w celu autoryzacji i niestety, ale otrzymuje komunikat "Próba otwarcie strony została zablokowana kod błędu 6427fc33027b4e8c".
Zależy mi na szybkim rozwiązaniu problemu, dziękuję. Poniżej kod.

`void openBrowser() throws IOException, URISyntaxException {
        String url = "http://127.0.0.1/AllegroApi/";
        String clientId = "0ce39a2710e24f5b81ef42990c4cb5b0";

        File file = new File("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe");

        try {
            Desktop.getDesktop().browse(new URI("https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response" +
                    "_type=code&client_id=" + clientId + "&redirect_uri=" + url));
        } catch (URISyntaxException e) {
            System.out.println("Error: " + e);
        }

    }`

**Comment by SebastianOzdoba** [comment]
@MLupinski  w String url = "http://127.0.0.1/AllegroApi/";  nie możesz mieć prywatnego adresu IP 

Zmień na dowolną domenę a w plikach hosts zrób sobie wpis
mojadomenadlaallegop.pl 127.0.0.1
Do allegro przekazuj http://mojadomenadlaallegrp.pl/allegroapi/

**Comment by MLupinski** [comment]
Ok spróbuję tak zrobić dzięki. 
A czy coś się w tej kwestii zmieniło ? Bo wcześniej w php bez problemu zwracało mi token przy takim zapisie.

**Comment by jakubmaguza** [comment]
Potrzebujesz autoryzacji [Device_Flow](https://developer.allegro.pl/auth/#DeviceFlow)

**Comment by SebastianOzdoba** [comment]
U mnie przestało działać jak miałem prywatny adres, pomogła prosta zmiana
Też działało na prywatnych i nagle przestało

**Comment by MLupinski** [comment]
No dobrze, aplikacja rozumiem, że ma przenosić na https://allegro.pl.allegrosandbox.pl/auth/oauth/device i tam po zalogowaniu powinienem otrzymać kody tak ?

**Comment by jakubmaguza** [comment]
W tym poradniku masz wszystko opisane.
Ty strzelasz do -> https://allegro.pl/auth/oauth/device
Dostajesz tam DeviceCode i UserCode.
Otwierasz użytkownikowi przeglądarkę, albo prosisz go żeby wszedł na stronę i wpisał UserCode
Jak wpisze to odpytujesz 
https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}

I tutaj dostajesz tokeny.

**Comment by MLupinski** [comment]
Dobra trochę pokombinowałem (jestem początkujący w tych sprawach), ale mam taki kod:

`String authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/device";
        HttpURLConnection myURL = (HttpURLConnection) new URL(authUrl).openConnection();

        String userCredentials = "bdc22d4054c04090ae687d4e0e75a7b4:uNHKzbWhwWQYneraAU7yVWHIdLSIw7MmCHkliZOyk7QNeYeRANdQuApJqFNkADcy";
        String basicAuth = Base64.getEncoder().encodeToString(userCredentials.getBytes());

        myURL.setRequestProperty("Request Method", "POST");
        myURL.setRequestProperty("Authorization", "Basic " + basicAuth);
        myURL.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        myURL.setUseCaches(false);
        myURL.setDoInput(true);
        myURL.setDoOutput(true);

        int status =  myURL.getResponseCode(); // 200 = HTTP_OK
        System.out.println("Response    (Code):" + status);
        System.out.println("Response (Message):" + myURL.getResponseMessage());`

Coś chyba pochrzaniłem w Request bo dostaję zwrotkę **400 Bad Request.**

**Comment by jakubmaguza** [comment]
Brakuje Ci w request body:   `-d 'client_id={client_id}'`

**Comment by MLupinski** [comment]
Czy body przesyła się tak jak resztę ? Tzn. setRequestProperty ("Body", clientId)?

**Comment by jakubmaguza** [comment]
Nie piszę w Javie, ale zakładam żę będzie coś takiego:

`httpConnection.setDoOutput(true);`
`OutputStream outStream = httpConnection.getOutputStream();`
`OutputStreamWriter outStreamWriter = new OutputStreamWriter(outStream, "UTF-8");`
`outStreamWriter.write("client_id={client_id}");`
`outStreamWriter.flush();`
`outStreamWriter.close();`
`outStream.close();`
