### ISSUE TITLE
bład walidacji "may not be empty" - czego dotyczy?

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#2084]
Przy próbie aktywowania szkiców, często (powiedzmy 1:20) pojawia mi się błąd:
"Could not change publication status, may not be empty".
Czego dotyczy ten błąd? w komunikacie nie ma wskazanego elementu, który jest błędny. Szkic ma wypełnione wszystkie obowiązkowe pola. W czym jest problem?
Przykładowy nr oferty: 8373370180

**Comment by TimothyKoval** [comment]
Usuń `publication.status`

**Comment by dostawcaopon** [comment]
Usunąć publication.status w szkicu? jak?

**Comment by dostawcaopon** [comment]
Po za tym, jakim cudem przy POST draftu otrzymuję odpowiedź OK i żadnych errorów w walidacji
a kiedy chcę aktywować to nagle się pojawia błąd walidacji?
Proszę o odpowiedź kogoś z Allegro

**Comment by MaciejFrackowiak** [comment]
Opisany problem zgłosiłem już do weryfikacji - wspomniałem o tym w poście [#2076](https://github.com/allegro/allegro-api/issues/2076)
Wrócę, gdy tylko otrzymam odpowiedź.

**Comment by dostawcaopon** [comment]
Pisałem wcześniej że przy POST szkicu nie otrzymuję errorów walidacji. Pomyliłem się. Jest zwracany błąd o treści "may be not empty", przy czym nie potrafię zdiagnozować, którego elementu szkicu on dotyczy, z treści komunikatu błędu nie mogę tego wywnioskować - proszę o pomoc w tej sprawie.
id 8373370180

**Comment by MaciejFrackowiak** [comment]
To jest dokładnie problem, który skierowałem do weryfikacji - czekam na odpowiedź w tej sprawie.

**Comment by dostawcaopon** [comment]
Ok, doszedłem co oznacza ten błąd. Chodzi o element draftu - product. 
Postowałem szkic z pustym elementem product i wtedy pojawiał się ten błąd walidacji "may be not empty". Ale swoją drogą można przekazać programistom, żeby poprawili ten komunikat błędu. Tak aby wiadomo było, że chodzi właśnie o "product".

**Comment by MaciejFrackowiak** [comment]
Dziękuję za spostrzeżenie - przekazuję informacje do programistów.
