### ISSUE TITLE
500 na sandboxie przy POST /sale/offers

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#2085]
Nie idzie żaden request.
trace-id: b2c53336df1c50b6

**Comment by kczechowski** [comment]
To samo. 
{"errors":[{"type":"Exception","message":"{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal Server Error\",\"details\":null,\"path\":\"\\\/sale\\\/offers\\\/6206494789\",\"userMessage\":null}]}","file":"","line":256}]}

**Comment by MaciejFrackowiak** [comment]
To efekt problemów technicznych. Działamy już nad naprawą - przepraszam za niedogodności.

**Comment by MaciejFrackowiak** [comment]
Update - problem wyeliminowany, Sandbox funkcjonuje już prawidłowo.
