### ISSUE TITLE
READY_FOR_PROCESSING - kiedy spodziewać się wielu tych zdarzeń dla jednego zamówienia?

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#2087]
Według dokumentacji zdarzenie typu READY_FOR_PROCESSING może wystąpić wiele razy.
Czy oprócz dopłat są sytuacje, w których zdarzenie to występuje ponownie?
Muszę wiedzieć jakie dane mogą ulec zmianie, chociaż semantycznie nie powinno już się takie zamówienie zmieniać. A zdarzenie z dopłatą być może warto, aby miało swój typ np. SURCHARGE.

**Comment by MaciejFrackowiak** [comment]
Nie, tylko dopłata skutkuje ponownym pojawieniem się statusu READY_FOR_PROCESSING.
Dopłata ma swoje odzwierciedlenie w bloku “surcharges”.
Szczegóły znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/#06)

**Comment by neldh** [comment]
żadnych typów proszę już nie zmieniać. Jak Ci się ponownie pojawi READY_FOR_PROCESSING to będzie mialo ten sam uuid checkout forma i będzie miało uzupelnioną tablicę surcharges. Status nie jest dla zdarzenia tylko dla checkout forma.

**Comment by blazeyzem** [comment]
Witam. Być może czegoś nie rozumiem, ale pojawił mi się dwa razy READY_FOR_PROCESSING dla tego samego formID, bez dopłat. Żadnych różnic w danych nie dostrzegam. Jakiś błąd API, czy o czymś nie wiem?

2019-08-14 11:28:32: Znalazłem nowe zamówienie id: 6a29dbd2-be75-11e9-b7b9-7d914ad1491a
2019-08-14 11:28:33: Zapisuję ostatni event do pliku: 1565774865453316 z dnia: 2019-08-14 11:27
2019-08-14 11:50:34: Znalazłem nowe zamówienie id: 6a29dbd2-be75-11e9-b7b9-7d914ad1491a
2019-08-14 11:50:35: Zapisuję ostatni event do pliku: 1565776198560031 z dnia: 2019-08-14 11:27

**Comment by MaciejFrackowiak** [comment]
@blazeyzem Sprawdziliśmy ten przypadek - zgodnie z [informacjami](https://developer.allegro.pl/orders/#02) takie sytuacje mogą mieć miejsce - aby się upewnić, że to duplikat, trzeba porównać checkoutForm.id oraz datę occuredAt - w tym przypadku dane są identyczne.

**Comment by blazeyzem** [comment]
THX
