### ISSUE TITLE
Upłynął czas operacji dla "/sale/offer-variants/{setId}" DELETE

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#2088]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję usunąć kilkadziesiąt wariantów pod rząd. Kilka pierwszych usuwa się bezproblemowo. Na kolejnych się zawiesza. Stosuję nawet przerwy 1-2 sekundowe pomiędzy kolejnymi wywołaniami ale nic to nie pomaga. Przy kolejnej próbie wariant się usuwa bezproblemowo.
Czy odnotowujecie jakieś problemy z tym zasobem? 

/sale/offer-variants/89cf3221-6737-473b-b816-5ca4ce2ad059

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem Twoje zgłoszenie i nie odnotowaliśmy żadnych problemów z zasobem. 
Dane z metryk nie pokazują nic niepokojącego. Wspomniany set został usunięty o godz. 17:02 8 sierpnia.
