### ISSUE TITLE
Dwa obiekty Payment z różnymi polami

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#2089]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Jeden obiekt Payment zawiera pole "method" i jest używany między innymi w klasie Pos w zasobie "/points-of-service/"

 

method* | stringAvailable forms of payment: CASH - cash, CARD - card.
-- | --

Drugi obiekt Payment zawiera pole "id" i jest używany między innymi w klasie InitializeRefund w zasobie "/payments/refunds"

description: | Payment affected by refund operation.
-- | --
id | string($uuid)example: a6bee8b2-8b4e-11e9-8918-07b31163120aThe payment identifier.

**Comment by MaciejFrackowiak** [comment]
W zasobie /points-of-service występuje obiekt “payments”, natomiast w zasobie /payments/refunds obiekt “payment”. 
Tym samym pola przypisane są do unikalnych obiektów.

**Comment by Gerston** [comment]
No właśnie, że nie! Oto zrzuty z ekranu waszej dokumentacji:

![image](https://user-images.githubusercontent.com/44425976/62766912-cd5e9f00-ba93-11e9-8e57-3fe9e3e18e7d.png)


![image](https://user-images.githubusercontent.com/44425976/62766996-fd0da700-ba93-11e9-9b08-4ce74768efcc.png)

**Comment by Gerston** [comment]
Nawet nie potraficie porządnie sprawdzić tego co się do was pisze.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za spostrzeżenie. Temat przekazałem do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
@Gerston Po wstępnej analizie proszę doprecyzuj nam, gdzie obecne rozwiązanie oprócz Swagger Editor (który pokazuje title zamiast faktycznej nazwy obiektu) wprowadza Cię w błąd - czy korzystasz z jakiegoś narzędzia?

**Comment by MaciejFrackowiak** [comment]
Dokonaliśmy zmian i obecnie obiekty są już jednoznacznie możliwe do rozróżnienia.
