### ISSUE TITLE
Problemy z adresowaniem paczkomatów

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2091]
Witam,

Czy ostatnio zaszły jakieś zmiany w integracji Allegro/Inpost Paczkomaty? Pytam, bo gdy próbuje adresować przesyłkę (w API inpost) podając transactionId i userId z serwisu Allegro dostaję dziwny błąd:

`Zamówienie przesyłki jest innego rodzaju, niż wynika z metody dostawy w zamówieniu`

Dokładniej chodzi dla takich danych:

```<transactionId>1057536195</transactionId>
<userId>5174749</userId>```

**Comment by MaciejFrackowiak** [comment]
Niestety, w tej kwestii musisz skontaktować się bezpośrednio z InPost.

**Comment by pgasidlo** [comment]
Wydaje mi się że jednak coś jest związane z Allegro. Wszystkie transakcje, które wybijają ten błąd są w stanie "Rozpoczęto PAYU", "Rezygnacja PAYU" - w sensie, że PAYU nie dostało pieniędzy. My dostaliśmy pieniądze na konto od klienta, więc próbujemy adresować. Pytanie czy nagle przestaliście Państwo zgłaszać takie przypadki do InPosta.

**Comment by MaciejFrackowiak** [comment]
Dla transakcji opłacanych przez Allegro Finanse ich status musi być “Zakończona” by dane zostały przekazane do InPost. Niczego w tej kwestii nie zmienialiśmy.

**Comment by pgasidlo** [comment]
OK. Widocznie Inpost nagle zaczął to weryfikować.

**Comment by pkrzemo** [comment]
@MaciejFrackowiak:

>Dla transakcji opłacanych przez Allegro Finanse ich status musi być “Zakończona” by dane zostały przekazane do InPost. Niczego w tej kwestii nie zmienialiśmy.


dziwne... bo w managerze paczek da się wysyłać paczki do transakcji które nie są "zakończone". Wystarczy że jest wypełniony formularz dostawy (płatność "Rozpoczęta" lub "Anulowana").
Patrz na filtr statusu płatności w managerze paczek przy imporcie z allegro:
![ManagerStatusyPayU](https://user-images.githubusercontent.com/51461619/62821813-12a9cc00-bb7b-11e9-88bf-2613fd21b0be.JPG)

@pgasidlo:
>Zamówienie przesyłki jest innego rodzaju, niż wynika z metody dostawy w zamówieniu

 sprawdź wybrany sposób dostawy. Może użytkownik wybrał np. "nie allegrowy" paczkomat zamiast "allegro-inpost paczkomat" ..

**Comment by MaciejFrackowiak** [comment]
@pkrzemo  Dziękuję za spostrzeżenie.

**Comment by magik092** [comment]
@pgasidlo dzisiaj mieliśmy podobny problem. Klient zakupił towar, następnie nie opłacił formularza, utworzył drugi formularz, tego również nie opłacił ale zdecydował się ten pierwszy dokończyć.
Jak pobraliśmy zakup klienta to przez Inpost również nie chciało przejść zamówienie (błąd ten co zgłaszasz) i okazało się, że w takim wypadku dla Inpost musisz podać zarówno id transakcji tej opłaconej jak również co istotne pełny email z tej opłaconej transakcji (różnią się tą częścią na prawo od plusa).
Jak nadaliśmy paczkę z poprawionym mailem oraz id transakcji to przeszło.
Co ważne - dotychczas jak mieliśmy problem z nadaniem to po prostu nie robiliśmy tego jako Allegro Inpost tylko zwykły Inpost jednak teraz Inpost weryfikuje typ wysyłki na podstawie tego maila/identyfikatora klienta.

**Comment by lukada4100** [comment]
A od godziny InPost blokuje mi przygotowywanie przesyłek, które mają status opłacone z uwagą: message=allegro_email_invalid.

**Comment by magik092** [comment]
@lukada4100 u nas jest podobnie. W wątku #2117 problem jest już poruszony
