### ISSUE TITLE
Udostępnianie więcej szczegółów o ofercie w odpowiedzi od /offers/listing

### ISSUE THREAD

**Issue by emptycodes** [allegro/allegro-api#2092]
:bulb: **Sugestia**

Chciałbym w swojej aplikacji zawrzeć więcej szczegółów nt. ofert po wyszukiwaniu przy jak najmniejszej liczbie wykonywanych zapytań do Allegro REST API.
Np. dla kategorii "Samochody":
- **Stan:** Użwany
- **Rok produkcji:** 1997
- **Przebieg:** 270 000 km
- **Pojemność silnika:** 1900 cm³

Byłbym wdzięczny za dodanie nowego, opcjonalnego parametru który pozwalałby na uzyskanie takich danych!

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię.
Przekazałem do odpowiedniego zespołu, jeśli wdrożymy takie rozwiązanie to poinformujemy o tym w dedykowanym komunikacie.
