### ISSUE TITLE
/sale/offers - pobieranie EAN?

### ISSUE THREAD

**Issue by samilmarekrygula** [allegro/allegro-api#2093]
Pobieram całą listę ofert z konta i 7500 ofert pobiera się super szybko poprzez /sale/offers z parametrami limit i offset.

Jednak potrzebuję pobrać dla każdej oferty również kod EAN a on niestety nie jest przesyłany w /sale/offers więc dla każdej oferty pobieram szczegółowe dane /sale/offers/(numer id) tylko że to zaczyna trwać wiecznie bo muszę to pobrać dla ponad 7000 ofert.

W jaki sposób mogę to usprawnić? Czy da się pobrać EAN z listą ofert /sale/offers? Jak można to pobrać bardziej optymalnie?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma możliwości pobrania EAN przy pomocy [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)
EAN przypisany jest do konkretnej oferty, dlatego niezbędne jest jego pobieranie tak jak robisz, czyli przy pomocy [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)
