### ISSUE TITLE
How to get offer

### ISSUE THREAD

**Issue by DevPartner** [allegro/allegro-api#2094]
Hi,

I use GET /offers/listing to get offers.
Could you please let me know how I can get additional offer parameters(such as delivery, offer params)?
I tried to get those parameters by using GET /sale/offers/{offerId} but as far as I understand just sellers can use this method to get their offers. 
Can I get additional offer params somehow by using RestApi?

Best regards, Konstantin.

**Comment by MaciejFrackowiak** [comment]
When you use [GET /offers/listings ](https://developer.allegro.pl/documentation/#operation/getListing)you receive public information about offers. You can use query parameters to get more adequate results, moreover you can filter them by filter’s ID.
Please, check our [tutorial](https://developer.allegro.pl/en/listing/)

[GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) allows you to get information which parameters are available in category.

Yes, just seller can receive whole data about specific offer using [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)

We work on resource Get public data about offers - more information you will find [here](https://developer.allegro.pl/en/schedule/).

**Comment by DevPartner** [comment]
Thank you for the quick response. 
As far as I understand we should wait until March 2020
![image](https://user-images.githubusercontent.com/12186237/62868071-71a74680-bd1d-11e9-8777-a85b5221aa06.png)
