### ISSUE TITLE
GET /sale/offers/{auctionId} - timeout

### ISSUE THREAD

**Issue by dzitdesk** [allegro/allegro-api#2096]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,
mam problem z zasobem /sale/offers/{auctionId}.

Na podstawie pliku zawierającego listę aukcji, pobieram szczegóły każdej z nich z wykorzystaniem wyżej wspomnianego zasobu. Dwie pierwsze aukcje pobierają się prawidłowo, mogę dalej je przetwarzać, natomiast wszystkie pozostałe zwracają błąd o przekroczeniu czasu odpowiedzi serwera (domyślny, 60 sek). 

Plik zawiera około 3000 aukcji, w ciągu jednej sekundy przetwarzanych jest około 5, więc nie ma raczej możliwości przekroczenia limitu zapytań.

**Comment by MaciejFrackowiak** [comment]
Proszę, podaj przykładowy trace-id, dla którego otrzymałeś timeout.

**Comment by dzitdesk** [comment]
Nie dostaję w takim przypadku odpowiedzi od serwera, więc nie jestem w stanie podać Trace-Id.
Zauważyłem natomiast, że problem nie występuje stale. Uruchomiłem aplikację ponownie - wszystko zadziałało normalnie i nie było żadnego problemu. Na komputerze klienta problem występuje cały czas. W zeszłym tygodniu problem występował zarówno u mnie jak i u klienta.

**Comment by MaciejFrackowiak** [comment]
Nie odnotowaliśmy problemów z tym zasobem. 
Proszę o:
- konkretne timestampy
- klucz na jakim działa aplikacja
- id usera na jakim jest problem
