### ISSUE TITLE
GET https://api.allegro.pl/sale/offers - błędy 500 Internal Server Error

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2097]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od godziny wali 500, jak poniżej:

`GET https://api.allegro.pl/sale/offers?seller.id=XXXXXXXX&offset=0&limit=1000` resulted in a `500 Internal Server Error` response: {"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"","details":"","path":""}]}

**Comment by MaciejFrackowiak** [comment]
Proszę, podaj przykładowy trace-id, dla którego otrzymałeś błąd 500.

**Comment by neldh** [comment]
Problem już nie występuje. Widocznie mieliście jakieś chwilowe problemy. Niestety nie logujemy trace-id.

**Comment by 07adityasingh** [comment]
I have same issue  when https://api.allegro.pl/sale/offers/{offerId}
It show Internal Server Error

**Comment by MaciejFrackowiak** [comment]
Please, give us a trace-id for which you received error 500.

**Comment by vifus** [comment]
Problem nadal występuje, 

string(119) "{"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"","details":"","path":""}]}"
int(401)

`    $url = "https://api.allegro.pl/sale/offers?seller.id=7350634";

    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json",
                 "content-type: application/vnd.allegro.public.v1+json"
    ]);`

**Comment by MaciejFrackowiak** [comment]
@vifus Proszę podaj nam trace-id wywołania.

**Comment by vifus** [comment]
hmm, nie wiem czy mam możliwość to podejrzeć. mój cały kod:
`
    $token = 'token';
    $url = "https://api.allegro.pl/sale/offers?offset=0&limit=100&seller.id=7350634&publication.status=ACTIVE";

    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json",
                 "content-type: application/vnd.allegro.public.v1+json"
    ]);


    $items = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($items === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $list = json_decode($mainCategoriesResult);
`

**Comment by vifus** [comment]
coś z autoryzacją nie tak, ale token na 100% jest dobry, generowałem z 5x i próbowałem.

**Comment by MaciejFrackowiak** [comment]
@vifus Poprzez zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) pobierzesz tylko oferty zalogowanego użytkownika - query params “seller.id” nie jest dostępny w tym zasobie. Dla podanego trace-id dostałeś błąd 401, czyli problem z autoryzacją. Proszę doprecyzuj, jakie dane chcesz uzyskać wywoując zasób?

**Comment by vifus** [comment]
Chce pobrać aukcje uzytkownika, którego id jest przekazane w zapytaniu.

**Comment by MaciejFrackowiak** [comment]
@vifus Proszę skorzystaj z innego zasobu - dokładnie [GET /offers/listing](https://developer.allegro.pl/documentation/#tag/Public-offer-information) - tak pobierzesz oferty danego sprzedającego.
