### ISSUE TITLE
Co oznacza "tecdocSpecification": null

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2098]
Dzień dobry,
W wyniku GET https://api.allegro.pl/sale/offers/66633xxxxxxx
otrzymałem pole, którego nie znam:
"tecdocSpecification": null,

Co to za pole?

**Comment by MaciejFrackowiak** [comment]
To pole oznacza, że [sekcja Pasuje do](https://developer.allegro.pl/news/2018-08-08-pasuje/) jest zintegrowana z bazą pojazdów TecDoc - informowaliśmy o tym w poście [[NEWS] Pasuje do - integracja z bazą pojazdów](https://github.com/allegro/allegro-api/issues/1874)

Wartość pola “null” oznacza, że oferta nie jest zintegrowana z bazą TecDoc.
Szczegóły jak zarządzać Pasuje do znajdziesz w [tym poradniku](https://developer.allegro.pl/compatibility_list/).

**Comment by kfijalko** [comment]
Wskazane przez Ciebie wpisy znam. Nigdzie nie ma jednak informacji o tym polu. Czy ja to pole wypełniam? czy jak wypełnię compatybilityList to w tym polu coś się pojawi ?

**Comment by MaciejFrackowiak** [comment]
Już wyjaśniam - pole to będzie identyfikatorem specyfikacji technicznej TecDoc dla danej części. Na skutek rozpędu programistów pojawiło się nieoczekiwanie już na produkcji - do czasu pełnego wdrożenia funkcjonalności ukryliśmy je ponownie. Przepraszam za zamieszanie.

**Comment by kfijalko** [comment]
ok,
