### ISSUE TITLE
Flow zakupowe w sklepie - przelewy poza allegro

### ISSUE THREAD

**Issue by PrzemekTurek2017** [allegro/allegro-api#2099]
Pytanie dotyczy rozbieżności pomiędzy tym co jest w CRMie a tym co jest w Allegro.
Przykład.

Klient dokonuje zakupów przez allegro. 
Klient wykonuje np. 10 oddzielnych zakupów pobraniowych. (Zakup produktu + przesyłka)
Klient dzwoni do sklepu bezpośrednio z prośba połączenia wszystkich zamówień w jedno i wysłanie na wskazany adres za pobraniem.
Wychodząc na przeciw klientowi sklep dokonuje połączenia zamówień i wysyła na wskazany adres za pobraniem.

W ten sposób rodzą się rozbieżności pomiędzy allegro a sklepem m.in koszty przesyłki. Jak sobie radzić w takich przypadkach. Czy ktoś ma na to rozwiązanie ?.

**Comment by MaciejFrackowiak** [comment]
W takiej sytuacji możesz zasugerować klientowi połączenie zakupów poprzez wypełnienie jednego formularza pozakupowego -  koszty dostawy zostaną obliczone wg cenników dostawy i przypisanego algorytmu ich obliczania.

**Comment by PrzemekTurek2017** [comment]
Klient dla każdego z zamówień wybrał sposób wysyłki za pobraniem (formularz pozazakupowy). Nie ma możliwości po raz 2 wybrać formularza pozazakupowego. Zamówienie widnieje jako opłacone.

![Zrzut ekranu 2019-08-14 o 08 44 51](https://user-images.githubusercontent.com/51235517/63000494-990f2800-be71-11e9-9804-457588fec31d.png)

**Comment by MaciejFrackowiak** [comment]
Klient niestety wypełnił osobno formularze pozakupowe - w tym wypadku już niestety nic nie zrobi. Zgodnie z sugestią powinien wypełnić jeden łączny.
