### ISSUE TITLE
[Pytanie | REST] Jak wystawić ofertę do wyczerpania zapasów - oferta sklepowa

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#210]
Witam

Ustawiając pole duration na null oferta wystawia się jako "Do wyczerpania przemiotów - oferta zwykła" po ustawieniu "P30D" Jako oferta sklepowa na 30 dni, Nie widzę możliwości wystawienia oferty sklepowej do wyczerpania zapasów jak w załączniku

![image](https://user-images.githubusercontent.com/6499144/39882559-6ccd3320-5484-11e8-8c61-71998519c558.png)

**Comment by MarcinLuczak** [comment]
@cieplik206 w ten sposób na razie nie możesz wystawić oferty w REST API. Możesz mieć ofertę do wyczerpania zapasów, ale nie będzie ona sklepowa.

**Comment by cieplik206** [comment]
A inaczej, .. czy oferta zwykła i sklepowa do wyczerpania zapasów różni się czymść poza faktem, że u was wirtualnie się ona wznawia co 10 albo 30 dni ? Czy wpływa to na trafność ?

**Comment by MarcinLuczak** [comment]
@cieplik206 Czas trwania oferty nie wpływa bezpośrednio na trafność.

Jest kilka innych czynników, które wpływają na ten rodzaj sortowania. Opisaliśmy je [w tym artykule](https://allegro.pl/dla-sprzedajacych/trafnosc-xGmVjoPwOTo).

**Comment by kfijalko** [comment]
Witam,
Mam problem z edycją oferty; 7451222334
Jest to oferta sklepowa do wyczerpania przedmiotów.
Korzystam z webApi:
1) podaje fid[4] = 99, fid[29]=1, otrzymuję:
`{#41197 ▼
  +"status": "error"
  +"error_code": "ERR_INVALID_DURATION_TIME"
  +"error_message": "Niepoprawna wartość w polu określającym czas trwania aukcji."
}`
2) podaje fid[4] = 99, fid[29]=0, otrzymuję:
`{#41395 ▼
  +"status": "error"
  +"error_code": "ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM"
  +"error_message": "Nie można zmienić typu aukcji dla aukcji sklepowej"
}
`

Mam zablokowaną edycję ofert.
Co z tym zrobić?
Czy możecie wszystkei moje oferty zamienić na zwykłe (nie-sklepowe)?

**Comment by MarcinLuczak** [comment]
@kfijalko oferta, którą próbujesz edytować, **nie jest** sklepowa. To oferta zwykła, do wyczerpania przedmiotów.

W każdym razie problem jest nam znany. Pracujemy nad jego usunięciem.

**Comment by kfijalko** [comment]
@MarcinLuczak czy wiadomo kiedy naprawicie? ewentualnie czy jest jakies obejście? na chwilę obecną mam zabolkowaną edycję ofert.

**Comment by MarcinLuczak** [comment]
@kfijalko prace trwają. Nie jestem w stanie określić daty ich zakończenia.
