### ISSUE TITLE
Błąd Paczka w Ruchu (unknow destination code)

### ISSUE THREAD

**Issue by PrzemekTurek2017** [allegro/allegro-api#2100]
Błąd z PaczkaWRuchu przy generowaniu listów przewozowych. Poniżej widok błędu.

![image](https://user-images.githubusercontent.com/51235517/62864882-3866da80-bd0d-11e9-92e4-fc2ff3719eab.png)

Pomimo poprawnych danych, nie tworzy się etykieta.  Błędy po stronie Allegro, Paczki W Ruchu ?. Nieaktualny adres kiosku ?., Błędy z API, Inne ?. Jak sobie z tym radzić ?.

**Comment by MaciejFrackowiak** [comment]
W opisanej sytuacji sugeruję bezpośredni kontakt ze wsparciem Ruch.

**Comment by sest** [comment]
Zauważyłem podobny problem, mam takie zamówienia prawie dziennie. W API Ruchu kiosk nie jest dostępny natomiast klient na Allegro mógł wybrać kiosk!. Wydaję mi się że Powinniście to lepiej synchronizować ze sobą. Zadzwoniłem do klientki aby zmienić kiosk na inny i po sprawdzeniu okazało się że kiosk jest zamknięty od tygodnia. Drugi rodzaj błędu od Ruchu to "saved but changed DestinationCode" Okazuje się że kiosk istnieje ale id kiosku na mapce Ruchu jest inne niż to w zam od Allegro.
Problem jest spory, niektórzy klienci tego nie rozumieją :)

**Comment by MaciejFrackowiak** [comment]
Dane kiosków dostępnych na Allegro otrzymujemy bezpośrednio od Ruchu, który jest odpowiedzialny za rzetelność tych danych.
