### ISSUE TITLE
Pytanie o pole delivery->additionalInfo

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2103]
Czy to pole jest jeszcze używane/wyświetlane?

**Comment by PrzemyslawLukanowski** [comment]
Tak, na froncie są to “dodatkowe informacje w dostawie”, które można uzupełnić podczas wystawiania oferty, później widoczne w ofercie po kliknięciu na “dostawa i płatność”. W API zwracamy je poprzez zasób GET sale/offers/{offerId}.

**Comment by kfijalko** [comment]
ok, dziękuję - do zamknięcia
