### ISSUE TITLE
How to pass query parameters with Python?

### ISSUE THREAD

**Issue by artenni4** [allegro/allegro-api#2104]
I am trying to get search results with REST API with Python 3 and requests module. I already have a user access token, but I dont know how to pass parameters in my GET query.

Here is documentation page where is written all parameters, but it says that at least one phrase or ean parameter is required: https://developer.allegro.pl/en/documentation/#operation/getSaleProducts

Here is my Python code where I tried to pass parameters through data, but it seems that it doesn't work

```
def Search(access_token):
    search_products_url = 'https://api.allegro.pl/sale/products'
    get_data = {
        "phrase": "ipad"
        }
    header = {
        "Authorization": "Bearer " + access_token,
        "Accept": "application/vnd.allegro.beta.v1+json"
        }
    response = requests.get(search_products_url, headers=header, data=get_data)
    print(response)
    print(response.json())
```

**But I always get that error**:
```
<Response [422]>
{'errors': [{'code': 'ConstraintViolationException', 'message': 'An error has occurred', 'details': None, 'path': None, 'userMessage': 'Required parameters are missing.'}]}
```

_If you want to try it with token just ask and I will give you code that gets an user access token_
Help me!

**Comment by emptycodes** [comment]
In Python's requests libary to send query parameters (by GET method) use  `params` variable rather than `data`. POST method is using `data` variable. I hope I've been some help! ^^

**Comment by artenni4** [comment]
> In Python's requests libary to send query parameters (by GET method) use `params` variable rather than `data`. POST method is using `data` variable. I hope I've been some help! ^^

Yes! You helped a lot! Everything started working. Thank you
