### ISSUE TITLE
Działanie zestawów

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2106]
Czy można gdzieś przeczytać jak się zachowują zestawy w przypadku gdy:
1) jedna z ofert się zakończy
2) zakończona oferta (która była w zestawie) się wznowi
jak to wpływa na pola zestaw->status oraz zestaw->offers[]->promotionEntryPoint
?
Ogólnie: jaki jest cykl życia zestawu?

**Comment by MaciejFrackowiak** [comment]
1. W przypadku zakończenia jednej z ofert zestaw jest automatycznie usuwany.
2. W przypadku wznowienia zakończonej oferty zestaw nie przywróci się, konieczne jest stworzenie od nowa zestawu.

**Comment by kfijalko** [comment]
hmm, to trochę źle to zaimplementowałem.
W takim wypadku czy mogą wystapić inne statusy niż "ACTIVE"? w dokumentacji występują statusy: "ACTIVE" "INACTIVE" "SUSPENDED"

**Comment by MaciejFrackowiak** [comment]
Nie, dla zestawów występuje tylko status ACTIVE jeśli zestaw jest dostępny.
Dokumentacja dot. jednocześnie zestawów oraz rabatów ilościowych, stąd wymienione pozostałe statusy.
