### ISSUE TITLE
Allegro sandbox - aktywacja konta

### ISSUE THREAD

**Issue by MichalKosowski** [allegro/allegro-api#2110]
Hej,

Chciałem stworzyć testowe konta na Sandboxie do testowania API. Kliknąłem w załóż nowe konto, wprowadziłem dane, pojawił się komunikat że wysłano mail z aktywacją... i nic. Mija już kilka godzin - i cisza.

Robię coś źle czy na Sandboxie to po prostu tak długo trwa?

Michał

**Comment by MaciejFrackowiak** [comment]
Proszę podaj e-mail na jaki zarejestrowałeś konto, sprawdzę sytuację.

**Comment by MichalKosowski** [comment]
Były dwie próby:
-  kosowski.michal@gmail.com<mailto:kosowski.michal@gmail.com>
-  michal.kosowski@hotmail.com<mailto:michal.kosowski@hotmail.com>

Jeśli dobrze rozumiem, jeśli chce zasymulować sprzedaż na Sandboxie muszę mieć dwa konta – na jendym wystawiac rzeczy a drugim pozorować zakupy?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi i niestety nie mamy śladu po próbach rejestracji. Proszę podejmij ponowną próbę zarejestrowania kont.
Tak, do symulacji sprzedaży i kupna musisz posiadać osobne konta.

**Comment by MichalKosowski** [comment]
ok, dzisiaj działa!

**Comment by baza** [comment]
Prosze o aktywację konta
**apifalcon**

**Comment by PrzemyslawLukanowski** [comment]
@baza Wstępnie aktywowałem Twoje konto. Aby dokończyć proces aktywacji, prześlij dwa dowolne pliki przez zakładkę Moje konto -> dane konta.

**Comment by tomek66m** [comment]
Witam, nie wiem czy odpowiednie miejsce, ale prosiłbym o aktywację konta na sandboxie
email tomekpd@op.pl

**Comment by PrzemyslawLukanowski** [comment]
@tomek66m Aktywowałem Twoje konto.

**Comment by shambo666** [comment]
proszę o aktywację konta
magazyn@luxray.pl

**Comment by MaciejFrackowiak** [comment]
@shambo666 Twoje konto jest już aktywne.

**Comment by urszulade** [comment]
proszę o aktywację konta na sandboxie: testyita

**Comment by PrzemyslawLukanowski** [comment]
@urszulade Odpowiedź w #6190

**Comment by dudiqo** [comment]
proszę o aktywację konta: inkpad

**Comment by lasongrzegorz** [comment]
prosze o aktywacje konta **grzegorz.lason@webinterpret.com**. Z gory dzieki za szybka reakcje

**Comment by Lukasz-Zurek** [comment]
@lasongrzegorz Aktywowałem i zweryfikowałem Twoje konto.
