### ISSUE TITLE
brak payments.finishedAt

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2111]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zauważyłem, że w przypadku pobierania transakcji, gdzie mam nadpłatę od klienta, pole payments.finishedAt jest puste (pomimo, że kwota w payments jak najbardziej jest i status to READY_FOR_PROCESSING).

Czy to jest by design, czy błąd? Poniekąd skoro klient coś tam zapłacił, to fajnie by było wiedzieć kiedy to zrobił... Takie niezwracanie części encji (a dokładnie jednego pola) przy rozbieżności cen wygląda dziwnie:
```

   [payment] => Array
        (
            [id] => UUID
            [type] => ONLINE
            [provider] => PAYU
            [finishedAt] =>
            [paidAmount] => Array
                (
                    [amount] => 45.00
                    [currency] => PLN
                )

        )

```
Jeśli to jest by design, to czy możnaby prosić o kolejne pole w tej encji, która będzie zwracała datę tej płatności nawet w takiej sytuacji, albo przynajmniej opisanie tego problemu w dokumentacji?

Taka data byłaby po prostu pomocna w ustalaniu kiedy się to zdarzyło. Jej niezwracanie jest bardzo dziwne. Tak jakby klient zapłacił coś "pod stołem" i nikt nie wie kiedy.

**Comment by MaciejFrackowiak** [comment]
Brak uzupełnionego payments.finishedAt ma sugerować, że w przypadku wpłaty zaszła jakaś nieprawidłowość - zarówno nadpłata, jak i niedopłata to nie są wpłaty zgodne z zadeklarowaną wysokością wynikającą z zamówienia. 
Kombinacja REDAY_FOR_PROCESSING i brak payments.finishedAt = nadpłata.

**Comment by neldh** [comment]
Proszę: c03ecf73-bc78-11e9-a314-53159ee5abd0

**Comment by MaciejFrackowiak** [comment]
Sprawdziliśmy i rzeczywiście dla nadpłaty i niedopłaty powinniśmy zwracać payments.finishedAt - będziemy to poprawiać. Dziękuję za spostrzeżenie.

**Comment by Maciek-P** [comment]
Czy wiadomo już kiedy zostanie wprowadzona poprawka?

Podsyłam id formularza, w którym występuję ten sam problem: 94302cc3-c4e9-11e9-984d-8123aafb5ecf

Dodatkowo, w przypadku tego formularza, wartość nadpłaty różni się od wartości na zestawieniu wypłaty środków oraz na stronie zwrotu wpłaty do klienta.
Wg API nadpłata wynosi 9 zł, a do zwrotu z poziomu Allegro jest tylko 1 gr.

**Comment by MaciejFrackowiak** [comment]
Zespół odpowiedzialny za funkcjonalność zaadresował już problem, nie mam jednak jeszcze informacji co do terminu wdrożenia poprawki.
