### ISSUE TITLE
Status event'u BOUGHT

### ISSUE THREAD

**Issue by Makzi5** [allegro/allegro-api#2112]
W jakim przypadku event ma status BOUGHT? W dokumentacji jest napisane "klient kupił, ale jeszcze nie zapłacił za zamówienie" jednak, gdy na koncie sandbox klikam "kup teraz" i nie wypełniam FOD'u, to nie dostaje żadnej zwrotki z API, a gdy wypełnie FOD, ale płatność będzie nieudana, to event ma status FILLED_IN. Jak kryteria muszę spełnić, albo jakie czynności wykonać żeby dostać event o statusie BOUGHT?

**Comment by MaciejFrackowiak** [comment]
Status BOUGHT otrzymasz, gdy nie rozpoczniesz wypełniać formularza pozakupowego - obecnie kupując nawet przez Kup Teraz zostajesz przekierowany do wypełnienia jego i kliknięcie Kupuję i płacę przenosi zamówienie w stan FILLED_IN.
Jeżeli jednak kupisz coś w drodze licytacji to zamówienie otrzyma najpierw status BOUGHT. Podobny przypadek ma miejsce podczas zakupów Kup Teraz poprzez aplikację mobilną.
