### ISSUE TITLE
Integrator zewnętrzny motoryzacja

### ISSUE THREAD

**Issue by slawkus** [allegro/allegro-api#2113]
Cześć,
Chciałbym przed integracją przez API podłączyć się z Allegro testowo przez jakiś ogólnodostępny integrator. Czy możecie mi polecić jakieś rozwiązanie, które sprawdzi się w motoryzacji przy dość złożonym asortymencie? Najlepiej z jakimś darmowym trialem na przetestowanie działania.

**Comment by autoswiss** [comment]
Jak integrator to najlepszy jest chyba **baselinker**, a jeśli chodzi o asortyment części motoryzacyjnych to **bizauto** ma rozwiązanie pod allegro.
