### ISSUE TITLE
Wyłączenie metody dogetmywonitems

### ISSUE THREAD

**Issue by repmic** [allegro/allegro-api#2114]
W jaki sposób można teraz obsługiwać zakupy dokonane przez allegro? Proszę o wskazanie metody, która pozwala na pobieranie danych o zakupionych przedmiotach i danych sprzedawcy.

**Comment by MaciejFrackowiak** [comment]
W Rest API nie przewidujemy udostępnienia metody adekwatnej do doGetMyWonItems.
Zachęcam do spojrzenia w [harmonogram wygaszania WebAPI](https://developer.allegro.pl/schedule/).

**Comment by repmic** [comment]
Może nie musi to być metoda adekwatna, może jakaś podobna, która pozwoli pobrać informacje o zakupionych przedmiotach.

**Comment by MaciejFrackowiak** [comment]
Nie, takiej metody obecnie nie ma. Napisz proszę do czego chciałbyś użyć takiego zasobu w swojej integracji?

**Comment by repmic** [comment]
Dokonuje bardzo dużo zakupów na allegro (allegro ma dzięki temu znaczne korzyści z prowizji), dzięki tej funkcjonalności mogę kontrolować finalizacje transakcji. Mogę dostarczyć na priv login allegro w celu weryfikacji. Brak tej funkcjonalności znacząco utrudnia finalizację transakcji.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za doprecyzowanie. Twoje argumenty przekazuję jako sugestię rozwoju Rest API.

**Comment by repmic** [comment]
No ok, ale może jest możliwość włączenia tej metody. Rozumiem, że nie wspieracie jej w Rest API ale włączenie jej przy działającym WEB Api nic nie kosztuje.

**Comment by PrzemyslawLukanowski** [comment]
Metodę usunęliśmy 5 sierpnia. Niestety, ale - tak jak w przypadku innych usuniętych metod - nie planujemy jej ponownego włączenia. Sugestię na temat dodania jej odpowiednika w REST API przekazaliśmy do odpowiedniego zespołu.
