### ISSUE TITLE
Add a parcel tracking number - Rest

### ISSUE THREAD

**Issue by raav88** [allegro/allegro-api#2115]
https://api.allegro.pl/order/checkout-forms/{id}/shipments

W tej metodzie jest typ autoryzacji tylko bearer-token-for-user

Czy jest możliwość nadawania tych numerów trackingowych bez ingerencji użytkownika przez przeglądarkę? Tak jak to jest w webapi?

**Comment by MaciejFrackowiak** [comment]
Jest taka możliwość - niezbędne jest przejście procesu [device flow](https://developer.allegro.pl/auth/#DeviceFlow) lub [client_credentials flow](https://developer.allegro.pl/auth/#clientCredentialsFlow), wówczas będziesz mógł korzystać z zasobu bez ingerencji użytkownika.

**Comment by raav88** [comment]
Przy tej metodzie jest autoryzacja: bearer-token-for-user.
Czy  client_credentials flow nie jest autoryzacją: bearer-token-for-application ?

https://developer.allegro.pl/auth/#clientCredentialsFlow
"Autoryzacja Client_credentials flow
W ramach OAuth2 udostępniliśmy ścieżkę, dzięki której możesz zautoryzować aplikację bez zgody użytkownika na jej działanie. W ten sposób uzyskasz dostęp do zasobów, które w dokumentacji w miejscu "Authorizations" oznaczyliśmy "bearer-token-for-application". Są to zasoby, które pozwalają na dostęp do publicznych danych, np. pobieranie listy kategorii, przeglądanie listy ofert itp."

W device flow jest potrzebna ingerencja użytkownika, musi potwierdzić dostęp do aplikacji. Czy źle myślę?

**Comment by PrzemyslawLukanowski** [comment]
@raav88  Tak, client_credentials flow jest autoryzacją typu bearer-token-for-application. Aby skorzystać z tego zasobu musisz przejść autoryzację typu device flow albo code flow, przepraszamy za pomyłkę. 

> W device flow jest potrzebna ingerencja użytkownika, musi potwierdzić dostęp do aplikacji. Czy źle myślę?

Tak, użytkownik musi jednorazowo potwierdzić dostęp do aplikacji.
