### ISSUE TITLE
Serwer nie zwraca nr nadania. Proszę nadać paczkę ponownie

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#2117]
Od wczoraj jest problem z nadawaniem przesyłek Allegro Inpostu przez WebAPI Inpost ShipX. Wczoraj szło bardzo wolno. Dziś przy pierwszej próbie nadało 7 paczek z 16. Do pozostałych dostaję komunikat: "Serwer nie zwraca nr nadania. Proszę nadać paczkę ponownie". Przy każdej kolejnej próbie są nadawane kolejne przesyłki. Jak się domyślam jest problem z przekazywaniem danych do inpostu o transakcjach w związku z przyszłymi zmianami.
Kiedy to zostanie naprawione?

**Comment by anih** [comment]
Podpinam się, bo też od kilku godzin widzę ten problem.

**Comment by magik092** [comment]
Prawdopodobnie też mamy z tym problem, przy nadawaniu inpost allegro dostajemy błąd **allegro_email_invalid**, czyżby coś z komunikacją Allegro <-> Inpost?

**Comment by MaciejFrackowiak** [comment]
Weryfikujemy sprawę wraz z InPost.

**Comment by lukada4100** [comment]
Chyba coś zrobili, bo wygląda na to, że u mnie już działa.

**Comment by PrzemyslawLukanowski** [comment]
Tak, problem został naprawiony.
