### ISSUE TITLE
SMART Allegro 0zł za Inpost.

### ISSUE THREAD

**Issue by kris86k** [allegro/allegro-api#2118]
Witam.
Czy po zmianie Rest Api będzie zwracać 0zł za koszt wysyłki Inpost?

**Comment by Onixarts** [comment]
To samo pytanie ale o WebApi?

**Comment by MaciejFrackowiak** [comment]
Tak, będziemy zwracać 0 zł. Niebawem opublikujemy komunikat ze szczegółowymi informacjami.
