### ISSUE TITLE
Nie działa filtrowanie po id kategorii

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#2119]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://api.allegro.pl.allegrosandbox.pl:443 "GET /sale/offers?category.id=541&offset=1000&seller.id={wycięteSellerID}&publication.status=ACTIVE&limit=1000 HTTP/1.1" 200 38

Pobiera wszystkie oferty sprzedawcy, a nie bierze pod uwagę parametru "category.id",

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) nie wyfiltrujesz ofert wg id kategorii.
Jednocześnie napisz proszę dlaczego chciałbyś tak filtrować oferty.

**Comment by aktywnitu** [comment]
Oh, rzeczywiście pomyłka po mojej stronie z inną metodą wyszukującą oferty " /offers/listing".
Chciałbym pobrać oferty aktywne i zakończone sprzedawcy tylko z wybranych kategorii ze względu na dużą liczbę ofert na koncie - ponad 100 tysięcy.
W ofertach następnie muszę dokonać modyfikacji w opisie z czym już sobie bez problemu poradzę.
Alternatywa to pobranie wszystkich i sprawdzanie ścieżki kategorii, którą będzie trzeba samemu zbudować.

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałeś, tego filtru użyjesz dla zasobu GET /offers/listing. GET /sale/offers odzwierciedla “Moje oferty” z frontu, gdzie nie ma takiego filtru.
