### ISSUE TITLE
Pusta tablica na żądanie https://api.allegro.pl/sale/offer-publication-commands/11f95f92-09f5-4b7b-a346-e1b884ce2dd3

### ISSUE THREAD

**Issue by PawelOsinski** [allegro/allegro-api#2122]
Otrzymuję pustą tablicę przy próbie wystawienia aukcji.
https://api.allegro.pl/sale/offer-publication-commands/11f95f92-09f5-4b7b-a346-e1b884ce2dd3

Dlaczego nie można wystawić oferty?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać trace-id? Przy wyszukiwaniu po tym UUID nie otrzymuję żadnych wyników. Upewnij się, że wysyłasz poprawny.
