### ISSUE TITLE
/sale/offers - nie zwraca ofert 

### ISSUE THREAD

**Issue by sl-aw-ek** [allegro/allegro-api#2123]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl.allegrosandbox.pl/sale/offers?offer.id=XXXXXXXX&name=test&publication.status=ACTIVE&sellingMode.format=BUY_NOW&limit=1000&offset=0

Zwraca : 
trace-id=5254c21a6efdcc90
\"offers\":[],\"count\":0,\"totalCount\":0
No ale chyba powinno coś zwrócić skoro są oferty w sandbox-ie

**Comment by PrzemyslawLukanowski** [comment]
Jako pierwszy parametr podajesz konkretne offer.id, co zawęża ilość wyników do jednej pozycji. Upewnij się, że dalsze wartości parametrów nie są sprzeczne z danymi oferty. Prześlij pełen request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #2123 lub napisz tutaj id oferty.
