### ISSUE TITLE
Aktywne aukcje nie są zwracane przez sale/offers

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#2124]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam przykład dwóch aukcji, które nie są zwracane przy sale/offers pomimo tego, że spełniają warunek zapytania (8359257203, 8368311750)
Obie maja niekompletny node publication
	"publication": {
		"duration": null,
		"status": "ACTIVE",
		"startingAt": null,
		"endingAt": null,
		"endedBy": null,
		"republish": false
	}

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - GET /sale/offers nie zwraca podanych dwóch ofert, zgłosiłem problem do odpowiedniego zespołu.
