### ISSUE TITLE
Brak ilości sprzedanych przedmiotów

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#2125]
Witam, API nie zwraca ilości sprzedanych przedmiotów, jedynie ilość osób które dokonały zakupu [popularity] => 16

jak pobrać sprzedaż z ostatnich 30 dni?

używana metoda

$response=$api->offers->listing()->get($params);
$response=json_decode($response,true);
echo print_r($response,true);

**Comment by PawelTaberski** [comment]
Liczbę sprzedanych przedmiotów z ostatnich 30 dni pobierzesz przez REST API przy pomocy zasobu  GET /sale/offers ale tylko dla ofert danego sprzedawcy na którego masz tokena. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#1).
