### ISSUE TITLE
Nie można wznowić ogłoszenia - Sandbox

### ISSUE THREAD

**Issue by redwingecommerce** [allegro/allegro-api#2127]
Zgodnie z tym artykułem: https://developer.allegro.pl/advertisement/
mogę wznowić ogłoszenie ADVERTISING analogicznie do oferty "kup teraz".

Na środowisku testowym to nie działa - ogłoszenie po próbie wznowienia i oczekiwaniu ok 10 minut nadal jest ENDED (a chyba powinienem otrzymać status ACTIVATING w tym przypadku?). Czy to tylko kwestia testowego środowiska czy jednak nie można wznawiać ogłoszeń czy za krótko czekam? Proszę o informację.

REQUEST
```
Array
(
    [10002] => https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/6bdfcabf-9d46-b0a4-88e8-a9cbbd7ce234
    [10023] => Array
        ()
    [10036] => PUT
    [10015] => {"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"6206529602"}],"type":"CONTAINS_OFFERS"}]}
    [19913] => 1
    [64] => 0
)
```
RESPONSE
```
Array
(
    [id] => 6bdfcabf-9d46-b0a4-88e8-a9cbbd7ce234
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
```

**Comment by PawelTaberski** [comment]
Czy sprawdzałeś może status tego zadania zasobem GET /sale/offer-publication-commands/{commandId}/tasks jaką odpowiedź otrzymujesz?

**Comment by redwingecommerce** [comment]
Tak. Otrzymuje, że jest ENDED.
