### ISSUE TITLE
Pytanie jak pobrać statystyki aukcji od początku jej trwania.

### ISSUE THREAD

**Issue by Olafejs** [allegro/allegro-api#2128]
Witam czy któraś funkcja pozwala na pobranie pełnej historii dla danej aukcji ? Odwiedzin,sprzedanych przedmiotów ?

**Comment by PawelTaberski** [comment]
Zasobem GET /sale/offers sprawdzisz informacje o które pytasz, znajdziesz je w polach:
```
            "stats": {
                "watchersCount": 0,           -- liczba obserwowanych
                "visitsCount": 0              -- liczba odwiedzonych
            },
            "stock": {
                "available": 8,               -- liczba przedmiotów aktualnie dostępnych 
                                              w ofercie
                "sold": 0                     -- liczba sprzedanych przedmiotów w ofercie
                                              z ostatnich 30 dni
```
Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by PawelTaberski** [comment]
Obecnie w REST API nie ma zasobu, który zwracałby takie informacje dla oferty od początku jej trwania.
