### ISSUE TITLE
doChangeItemFields fid: 27

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#213]
Wygląda na to że doChangeItemFields completnie ignoruje ustawienie fid 27. Wcześniej aukcje nie miały tego pola.

Po wysłaniu odpowiedniego tekstu front nie reaguje. Nawet w panelu użyszkodnika w formularzu edycji, sekcja "dodatkowe informacje o dostawie" jest pusta.

Próbuję ustawić: "U Nas za przesyłkę płacisz tylko raz przy zakupie z różnych aukcji. Towary zakupione do godziny 13:30 wysyłamy jeszcze tego samego dnia.". Brak nawet znaku nowej linii.

Przykładowy numer aukcji: 7262322352

**Comment by LukaszKorek** [comment]
Sprawę weryfiukujemy. Gdy tylko czegoś się dowiem odezwę się.

**Comment by zulus** [comment]
Coś wiadomo? Dostajemy ostrzeżenia o nieprawidłowej stopce oferty, chcemy przenieść w-w text do pola 27, a ręcznie ~300 000 aukcji robić nie będziemy ;)

**Comment by LukaszKorek** [comment]
@zulus Proszę jeszcze o cierpliwość.  Gdy tylko czegoś się dowiem odezwę się. Możesz też skorzystać z zasobu do grupowej edycji: https://developer.allegro.pl/news/2018-04-19-News_grupowa_edycja_ofert_update/

**Comment by zulus** [comment]
Nie używamy cenników dostaw ze względu na brak obsługi w doNewAuctionExt oraz doChangeItemFields SOAP API, zaś /sale/offers wciąż ma status beta.
