### ISSUE TITLE
WebApi - Wewnętrzny błąd PayU 

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2130]
Przychodzi taka pora w ciągu dnia, że WebApi na wszystkich kompach zwraca mi błędy. Do tej pory zazwyczaj był to błędny identyfikator sesji, a teraz zaczęły pojawiać się takie rzeczy:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_NEW_PAYMENT_INTERNAL_ERROR</faultcode><faultstring>Wewnętrzny błąd PayU.</faultstring><faultactor>doGetPostBuyFormsDataForSellers - PayU internal error.</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by MaciejFrackowiak** [comment]
Występowały problemy techniczne z płatnościami - problem został rozwiązany. Proszę sprawdź ponownie sytuację u Ciebie.

**Comment by lukada4100** [comment]
Ostatni przypadek miałem koło południa.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sprawdzenie - czas pokrywa się z problemami, o których wspomniałem.

**Comment by PrzemyslawLukanowski** [comment]
@lukada4100 Nie udało mi się powtórzyć tego błędu. Czy problem występuje w dalszym ciągu?

**Comment by sikorag** [comment]
U jednego z moich klientów również przedwczoraj wystąpił ten błąd.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy to, błąd mógł wystąpić między godziną 7:00 - 12:00, po tym czasie problem został wyeliminowany.
