### ISSUE TITLE
Limit 100 pozycji w /offers/listing

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#2132]
Witam, chciałbym pobrać listę wszystkich przedmiotów danego sprzedawcy za pomocą /offers/listing, jednak limit zwraca mi tylko 100 aukcji.
Czy jest możliwość pobrania wszystkich aukcji danego sprzedawcy za jednym razem? 
Załóżmy 5000 ofert.

**Comment by crazyhtm** [comment]
Za jednym razem się nie da, ale można to zrobić w pętli :))

**Comment by mario033c** [comment]
Tak też robię :)
Przykład na 200 ofert

```
for($i=0; $i<= 200 ; $i+=100) {
$params=array('seller.id' => {numer id}, 'limit' => 100, 'offset' => $i);
$response=$api->offers->listing()->get($params);
$response=json_decode($response,true);

$num_promoted=count($response['items']['promoted']);
$num_regular=count($response['items']['regular']);

for($f=0;$f<$num_promoted;$f++) {
    echo $f."  ";
    
$id_aukcji = print_r($response['items']['promoted'][$f]['id'],true)." | ";
$tytul_aukcji = print_r($response['items']['promoted'][$f]['name'],true)." | ";
$sprzedanych = print_r($response['items']['promoted'][$f]['sellingMode']['popularity'],true)." | <br>";

}

}
```

**Comment by mario033c** [comment]
@crazyhtm ale to niestety nie działa, nadal nie wyświetla wszystkich aukcji. 
Przy wyświetlaniu aukcji typu regular również tylko ponad 100, a aukcji do pobrania jest o wiele więcej

**Comment by kfijalko** [comment]
Zmień offset:
$params=array('seller.id' => {numer id}, 'limit' => 100, 'offset' => **$i*100**);

**Comment by kfijalko** [comment]
Dodaj też sortowanie, zwiększysz szanse na "nie powtarzanie" ofert w wynikach poszczególnych zapytań.

**Comment by kfijalko** [comment]
Stop, wycofuje się z offsetu. Nie zauważyłem że jest +=100.

**Comment by kfijalko** [comment]
Zmień 
for($i=0; **$i<= 20000** ; $i+=100) {

**Comment by kfijalko** [comment]
pseudo:
wykonaj pierwsze zapytanie z parametrami:
$params=array('seller.id' => {numer id}, 'limit' => 1, 'offset' => 0);
weź liczbę ofert w wyniku "$availableCount"
$pageSize = 100; // wielkość strony
$maxOffers = min(6000,$availableCount); // maks liczba ofert w wyniku zapytania
$maxPages = floor($maxOffers/$pageSize); // maks liczba stron w wyniku
for($page=0; $page<=$maxPages; $page++){
$params=array('seller.id' => {numer id}, 'limit' => $pageSize, 'offset' => $page*$pageSize);
}

**Comment by mario033c** [comment]
@kfijalko dzięki, wszystko działa
