### ISSUE TITLE
Czy można obejść limit "availableCount: 6000" ?

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2133]
Mam pytanko,

wysyłam poniższe zapytanie:
> offers/listing?category.id=2&limit=100&option=SUPERSELLER&offset=6100

macie pomysł jak pobrać aukcje o offsecie powyżej  6000 np. 6100 czy 6500. 
Czy jest to możliwe?

searchMeta jak poniżej:

`searchMeta
    availableCount: 6000
    totalCount: 2538178
    fallback: false`

**Comment by kfijalko** [comment]
Tylko manipulowanie parametrami i sortowaniem do momentu, aż pobierzesz wszystkie oferty z danego konta. 
Najpierw kategoria + sortowanie ASC/DESC. 
Jeżeli dla, którejś kategorii (liścia) ma więcej niż 12.000 ofert to trzeba kombinować z filtrami lub frazami. Tyle że pojawią się powtórzenia ofert lub może się okazać, że nie da się pobrać ofert do których nie możesz "sięgnąć" dzięki sortowaniu ASC/DESC. Wtedy ... Ja jeszcze nie spotkałem (interesującego mnie) konta z kategorią liściem z większą niż 12k liczbą ofert.

**Comment by kfijalko** [comment]
Własnie zauważyłem, że nie pobierasz dla konkretnego konta ;)

**Comment by MaciejFrackowiak** [comment]
Listingi Allegro wyświetlają standardowo 100 stron po 60 ofert, takie samo założenie zastosowane jest w Rest API. Korzystanie z filtrów pozwala dotrzeć do szerszej grupy ofert.
