### ISSUE TITLE
wartości delivery->shippingRates

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#2134]
Dzień dobry,
skąd pobrać informacje dotyczące form dostawy w ofercie która nie ma wybranego szablonu czyli nie posiada w zasobie https://api.allegro.pl/sale/offers wartości delivery->shippingRates?

**Comment by MaciejFrackowiak** [comment]
Przy pomocy metody [GET /sale/offers/{offerId}/shipping-rates](https://developer.allegro.pl/documentation/#operation/getOfferShippingRatesGET) pobierzesz informacje o formach dostawy (ich id) przypisanych do konkretnej oferty. Natomiast korzystając z [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) dowiesz się jakie są to stricte metody dostawy.
Dodatkowe informacje znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#shipping-rates).
