### ISSUE TITLE
SOAP API DoGetPostBuyFormsDataForSellers - niepoprawny numer telefonu

### ISSUE THREAD

**Issue by redwingecommerce** [allegro/allegro-api#2135]
Notujemy od czasu do czasu dziwny sposób podawania numeru telefonu klienta.
Metoda: DoGetPostBuyFormsDataForSellers

```
<ns1:postBuyFormShipmentAddress>
            <ns1:postBuyFormAdrCountry>1</ns1:postBuyFormAdrCountry>
            <ns1:postBuyFormAdrStreet>XXX</ns1:postBuyFormAdrStreet>
            <ns1:postBuyFormAdrPostcode>XXX</ns1:postBuyFormAdrPostcode>
            <ns1:postBuyFormAdrCity>XXX</ns1:postBuyFormAdrCity>
            <ns1:postBuyFormAdrFullName>XXX XXX</ns1:postBuyFormAdrFullName>
            <ns1:postBuyFormAdrCompany/>
            <ns1:postBuyFormAdrPhone>500500500  600600600</ns1:postBuyFormAdrPhone>
            <ns1:postBuyFormAdrNip/>
            <ns1:postBuyFormCreatedDate>2019-08-19 21:10:57</ns1:postBuyFormCreatedDate>
            <ns1:postBuyFormAdrType>0</ns1:postBuyFormAdrType>
          </ns1:postBuyFormShipmentAddress>
```

Chodzi o linię:
` <ns1:postBuyFormAdrPhone>500500500  600600600</ns1:postBuyFormAdrPhone>`

Dostajemy dwa numery telefonów zlepione w taki sposób w jednym polu.

Czy ten błąd będzie naprawiony?

**Comment by MaciejFrackowiak** [comment]
Podejrzewam, że tak numer telefonu został podany przez kupującego.
Skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub [#2135](https://github.com/allegro/allegro-api/issues/2135) podając nam dane tej transakcji, wówczas zweryfikuję to.

**Comment by redwingecommerce** [comment]
Wysłane.

**Comment by PrzemyslawLukanowski** [comment]
@redwingecommerce Zweryfikowaliśmy to - numery telefonów tak zostały podane przez kupującego.

**Comment by redwingecommerce** [comment]
Ok. Dziękuję. Sugeruję w takim razie uszczelnienie tego miejsca w formularzach danych.

**Comment by PrzemyslawLukanowski** [comment]
@redwingecommerce Przekazałem sugestię do odpowiedniego zespołu.
