### ISSUE TITLE
Zgłaszanie ofert do promocji REST API 

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#2137]
Witam, czy jest możliwość zgłaszania ofert poprzez REST API do promocji prowizja nawet 0.5% ? 
Nie mogę tego znaleźć w dokumentacji, a obiło mi się o uszy, że jest taka opcja ?

**Comment by mlevvy** [comment]
Dokumentacja REST API, opis, przykłady znajdują się tutaj: https://developer.allegro.pl/badge/
