### ISSUE TITLE
Logowanie przez Allegro - nie możemy wyświetlić strony

### ISSUE THREAD

**Issue by nukotel** [allegro/allegro-api#2138]
Dzień dobry,
podczas próby wykonania logowania za pomocą Państwa platformy po stronie API zwracany nam jest w Allegro błąd 

"Nie możemy wyświetlić strony"
"Numer błędu: b67b9ce5defcd7ee"

Z czego to może wynikać?

**Comment by MaciejFrackowiak** [comment]
W jakiej dokładnie sytuacji pojawia się Tobie taki błąd, czy w trakcie uwierzytelniania w procesie autoryzacji użytkownika?

**Comment by nukotel** [comment]
Dokładnie w takiej sytuacji się pojawia. Czy coś robimy źle? :D

**Comment by MaciejFrackowiak** [comment]
W redirect_uri musisz podać taki sam adres powrotu jaki podałeś przy rejestracji aplikacji, wówczas zostaniesz przeniesiony na właściwą stronę. Możesz podać kilka adresów.

**Comment by nukotel** [comment]
W jakim formacie można podać kilka? Podczas rejestracji aplikacji która jest wykorzystywana również do innych funkcjonalności był podany jeden a chcemy kierować na inny. Jak możemy to zrobić?

**Comment by nukotel** [comment]
Zwrócić może uwagę powinienem również na fakt że ten błąd wyskakuje zanim Allegro zapyta o potwierdzenie autoryzacji przez użytkownika (tzn w ogóle nie dochodzi do etapu pytania o autoryzacje a wyrzuca tylko ten błąd).

**Comment by MaciejFrackowiak** [comment]
W trakcie [rejestracji lub edycji aplikacji](https://apps.developer.allegro.pl/) korzystającej z REST API podaj dodatkowe adresy URI do przekierowań w kolejnych liniach.
