### ISSUE TITLE
[RestAPI] Problem ze szkicami

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2139]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

1. Dodaję szkic
2. Zlecam usunięcie szkicu z GUI w moje Allegro 
3. Przez restAPI pobieram nadal ten szkic
4. Proszę o wyjaśnienia dlaczego pobiera się ale nie jest widoczny na GUI w mojeAllegro
Żeby było śmieszniej webAPI zwraca status: oferta zakończona

REQUEST 2019-08-22 14:41:38.5845589 
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206535852' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

RESPONSE 2019-08-22 14:41:38.7095582  Duration: 124,9993ms
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "100979f4-e2d0-40e8-b54b-f62f35397166"
      },
      "ReturnPolicy": {
        "Id": "1bc94464-37e7-42d0-8bf1-94b11e537f2f"
      },
      "Warranty": {
        "Id": "fe4fc622-e413-4666-a44f-aa3a8141788d"
      }
    },
    "Category": {
      "Id": "257936"
    },
    "CompatibilityList": null,
    "Contact": null,
    "CreatedAt": "2019-08-22T12:13:16Z",
    "Delivery": {
      "AdditionalInfo": "aaa",
      "HandlingTime": "PT48H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "0808c18e-55cc-49af-88c6-40a790c35b29"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "TEXT",
              "Content": "<p>test</p>\r\n"
            }
          ]
        }
      ]
    },
    "Ean": "2010000000038",
    "External": {
      "Id": "AK11-NOWY"
    },
    "Id": "6206535852",
    "Images": [
      {
        "Url": "https://a.allegroimg.allegrosandbox.pl/original/11af67/34ecbbda4be89917e13036827a3f"
      }
    ],
    "Location": {
      "City": "Kraków",
      "CountryCode": "PL",
      "PostCode": "31-000",
      "Province": "KUJAWSKO_POMORSKIE"
    },
    "Name": "Komplet Black",
    "Parameters": [
      {
        "Id": "11323",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "11323_1"
        ]
      },
      {
        "Id": "212742",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "212742_257106"
        ]
      },
      {
        "Id": "202661",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "202661_212837"
        ]
      }
    ],
    "Payments": {
      "Invoice": "VAT"
    },
    "Product": null,
    "Promotion": {
      "Bold": false,
      "DepartmentPage": false,
      "Emphasized": false,
      "EmphasizedHighlightBoldPackage": false,
      "Highlight": false
    },
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": "PT168H",
      "EndingAt": null,
      "StartingAt": null,
      "Republish": false
    },
    "SellingMode": {
      "Format": "AUCTION",
      "Price": {
        "Amount": "666,00",
        "Currency": "PLN"
      },
      "MinimalPrice": {
        "Amount": "12,00",
        "Currency": "PLN"
      },
      "StartingPrice": {
        "Amount": "11,00",
        "Currency": "PLN"
      }
    },
    "SizeTable": null,
    "Stock": {
      "Available": 5,
      "Unit": "PAIR"
    },
    "UpdatedAt": "2019-08-22T12:20:15.324Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-08-22T12:20:15.322Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "376f3885cd7239bf",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by MaciejFrackowiak** [comment]
Przed momentem przeprowadziłem test na Sandbox zgodnie z Twoimi krokami i nie potwierdziłem problemu - usunięty draft nie jest już dostępny w API. 
Czy możesz raz jeszcze przeprowadzić proces u siebie? - jeżeli problem wystąpi ponownie prosiłbym o podanie userID, dla którego problem się pojawił.

**Comment by SebastianOzdoba** [comment]
Proszę bardzo, powtarzalne 100%
1. dodałem przez restAPI
2. usunąłem przez mojeAllegro - lista pusta
![image](https://user-images.githubusercontent.com/47886399/63518045-770c4a00-c4f0-11e9-8e12-02d9561f9434.png)

3. strzelam do restAPI
REQUEST 2019-08-22 15:21:34.5572339 
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206535866' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \

RESPONSE 2019-08-22 15:21:34.7134683 Duration: 156,2344ms
{
  "Data": {
    "AdditionalServices": null,
    "AfterSalesServices": {
      "ImpliedWarranty": {
        "Id": "100979f4-e2d0-40e8-b54b-f62f35397166"
      },
      "ReturnPolicy": {
        "Id": "1bc94464-37e7-42d0-8bf1-94b11e537f2f"
      },
      "Warranty": {
        "Id": "fe4fc622-e413-4666-a44f-aa3a8141788d"
      }
    },
    "Category": {
      "Id": "257936"
    },
    "CompatibilityList": null,
    "Contact": null,
    "CreatedAt": "2019-08-22T12:25:54Z",
    "Delivery": {
      "AdditionalInfo": "aaa",
      "HandlingTime": "PT48H",
      "ShipmentDate": null,
      "ShippingRates": {
        "Id": "0808c18e-55cc-49af-88c6-40a790c35b29"
      }
    },
    "Description": {
      "Sections": [
        {
          "Items": [
            {
              "Type": "TEXT",
              "Content": "<p>test</p>\r\n"
            }
          ]
        }
      ]
    },
    "Ean": "2010000000038",
    "External": {
      "Id": "AK11-NOWY"
    },
    "Id": "6206535866",
    "Images": [
      {
        "Url": "https://a.allegroimg.allegrosandbox.pl/original/11af67/34ecbbda4be89917e13036827a3f"
      }
    ],
    "Location": {
      "City": "Kraków",
      "CountryCode": "PL",
      "PostCode": "31-000",
      "Province": "KUJAWSKO_POMORSKIE"
    },
    "Name": "[SO] 1Komplet Black",
    "Parameters": [
      {
        "Id": "11323",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "11323_1"
        ]
      },
      {
        "Id": "212742",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "212742_257106"
        ]
      },
      {
        "Id": "202661",
        "RangeValue": null,
        "Values": [],
        "ValuesIds": [
          "202661_212837"
        ]
      }
    ],
    "Payments": {
      "Invoice": "VAT"
    },
    "Product": null,
    "Promotion": {
      "Bold": false,
      "DepartmentPage": false,
      "Emphasized": false,
      "EmphasizedHighlightBoldPackage": false,
      "Highlight": false
    },
    "Publication": {
      "Status": "INACTIVE",
      "EndedBy": null,
      "Duration": "PT168H",
      "EndingAt": null,
      "StartingAt": null,
      "Republish": false
    },
    "SellingMode": {
      "Format": "AUCTION",
      "Price": {
        "Amount": "666,00",
        "Currency": "PLN"
      },
      "MinimalPrice": {
        "Amount": "12,00",
        "Currency": "PLN"
      },
      "StartingPrice": {
        "Amount": "11,00",
        "Currency": "PLN"
      }
    },
    "SizeTable": null,
    "Stock": {
      "Available": 5,
      "Unit": "PAIR"
    },
    "UpdatedAt": "2019-08-22T12:37:04.174Z",
    "Validation": {
      "Errors": [],
      "ValidatedAt": "2019-08-22T12:37:04.174Z"
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "94c35818ea24b2b",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
