### ISSUE TITLE
filtrowanie checkout-forms po statusie BOUGHT+FILLED_IN

### ISSUE THREAD

**Issue by Zbigniew-L** [allegro/allegro-api#2140]
Szanowni Państwo, jestem nowy w rest, ale proszę o informację czy jest możliwość filtrowania zasobu checkout-forms po statusie BOUGHT lub FILLED_IN ? (lub <>READY_FOR_PROCESSING? chciałbym otrzymać listę wszystkich 'problematycznych' zamówień za jednym zapytaniem - obecnie odpytuję najpierw status=BOUGHT a potem status=FILLED_IN - ale to dwa zapytania - byłoby mi wygodniej za jednym razem takie zapytanie załatwić...

w sumie pytanie dotyczy również innych filtrów np. jak przekazać kilka id w filtrze... poniższy kod nie działa:

payments/payment-id-mappings?transactionId=[111,222,333]

pozdrawiam!

**Comment by MaciejFrackowiak** [comment]
Zamówienia możesz filtrować po ich statusie tj. BOUGHT, FILLED_IN, READY_FOR_PROCESSING lub ALL zgodnie z dokumentacją zasobu [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) - aby dostać określoną grupę w danym statusie należy podać tylko jeden z nich np. BOUGHT.
Sugerowałbym, abyś korzystał z dziennika zdarzeń, ponieważ zapewnia właściwe sortowanie zdarzeń - zajrzyj do [naszego poradnika](https://developer.allegro.pl/orders/#03).
Natomiast mapowanie zamówień poprzez [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping) możliwe jest tylko poprzez pojedyncze id.

**Comment by Zbigniew-L** [comment]
Dziękuję za odpowiedź.

Wszystko fajnie z dziennikiem zdarzeń, ale proszę zwrócić uwagę, że nie do końca jest on wygodny do znalezienia 'niekompletnych' zamówień

1. na początek chcemy pobrać zamówienia READY_FOR_PROCESSING - i tylko takie nas intetesują bo wszystko z nimi OK i możemy zacząć pakować towar itp. - pobieramy zatem je dziennikiem zdarzeń - i wszystko działa 

2. niestety klienci nie zawsze decydują się na dokończenie zakupu (i nigdy nie wypełnią FOD lub wypełnią - ale coś pójdzie nie tak z zapłatą) 

wymyśliliśmy zatem, że te 'problematyczne' zamówienia będziemy pobierać dopiero gdy od zakupu upłynęły np. 3 godziny (czyli dajemy klientom te 3 godziny, aby ponownie dokonali zapłaty lub wypełnili FOD, itp.) - chcemy zatem pobrać zamówienia 'starsze' niż 3 godziny, które maja status BOUGHT lub FILLED_IN - ale na tym etapie nie interesują nas READY_FOR_PROCESSING - bo te ogarniane są przez dziennik (pkt 1)

jednak jest problem taki, że to co znajdujemy w dzienniku jako BOUGHT 3 godziny wcześniej po prostu może już być 'załatwione' i dawno temu jest w "READY_FOR_PROCESSING' - nie ma chyba sensu przeglądać ponownie wszystkich zdarzeń aby wyłuskać BOUGHT - które nie zrobiły się READY_FOR_PROCESSING (lub FILLED_IN) - wydaje nam się, że znajdziemy 'problematyczne' po prostu filtrując odpowiednio zasób checkoutForms (wydaje się to dobrze działać i zwraca nam tylko BOUGHT i/lub FILLED_IN)

'problematyczne' zamówienia są niekompletne więc kontaktujemy się z klientami, wypełniamy formularze zwrotów itp.

Czy dobrze wnioskuję, że w skrócie:  nie ma możliwości aby filtrować po statusie=BOUGHT OR FILLED_IN - po prostu możemy przekazać do filtra tylko jedną wartość? więc jak chcemy uzyskać taki OR to po prostu musimy zadać dwa zapytania?

czy te filtry to kwestia rozwojowa czy zamknięta?

czyli czy możecie rozważyć możliwość modyfikacji filtrów aby akceptowały wiele wartości (jako OR a nie AND)?

na przykład czy byłaby w przyszłości szansa aby zadziałało:

...order/events?limit=100&from=10010101&type=[FILLED_IN,READY_FOR_PROCESSING]

lub...

...order/events?limit=100&from=10010101&type=FILLED_IN&type=READY_FOR_PROCESSING&operator=OR

po przetłumaczeniu

"podaj max 100 zdarzeń od zdarzenia 10010101 dla których type jest FILLED_IN lub READY_FOR_PROCESSING"

**Comment by MaciejFrackowiak** [comment]
Dokładnie, możliwe jest filtrowanie po jednym statusie naraz. Twoją sugestię przekazuję do zespołu odpowiedzialnego za rozwój REST API.
