### ISSUE TITLE
Błąd not found dla niektórych zamówień

### ISSUE THREAD

**Issue by ircykk** [allegro/allegro-api#2141]
Pobieram zdarzenia `/order/events` a następnie zamówienie przy pomocy `/order/checkout-forms/{checkoutForm_id}` i dla niektórych zapytań nie wiem dlaczego otrzymuję status not found, np: dla zamówienia: `2a5494d2-c3f9-11e9-85d7-fd4a5986fb9f`

Czym może to być spowodowane?

**Comment by MaciejFrackowiak** [comment]
Czy jesteś pewny, że id zamówienia pobierasz z pola “checkoutForm”? Jeżeli tak, to możliwe, że kupujący połączył zakupy i wówczas powstaje nowy formularz pozakupowy.

**Comment by ircykk** [comment]
Tak, robi to skrypt w pętli i większość zamówień jest ok. Dziękuję za info sprawdzę czy to jest przyczyną problemów.
