### ISSUE TITLE
API to set order status to "sent"

### ISSUE THREAD

**Issue by hello76yu** [allegro/allegro-api#2142]
Hi , when manually operating on Allegro order manage page, there is a function allow us to set order status to "sent" .
It is a useful function to help us to display those paid order but not yet processed with shipping.

Althoug we are using API to manage order, but still we need login Allegro manually to check if there are orders need shipping.

Is there such API(set order status to "sent" or "not sent")   or just i did't find it?
Thanks

**Comment by MaciejFrackowiak** [comment]
This option is not yet available in REST API or WebAPI. It works only in My Allegro - just sort orders in WWW service.
I will add it as a suggestion for developing our API.

**Comment by hello76yu** [comment]
> This option is not yet available in REST API or WebAPI. It works only in My Allegro - just sort orders in WWW service.
> I will add it as a suggestion for developing our API.

thanks for your reply.
