### ISSUE TITLE
Dziennik zdarzeń zwraca pusty wynik mimo nowych zamówień

### ISSUE THREAD

**Issue by rafalkrawiec** [allegro/allegro-api#2144]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mam problem z pobieraniem zdarzeń dla zamówień w środowisku testowym. Wczoraj dla starszych zamówień integracja zadziałała prawidłowo. Dla zamówień złożonych dzisiaj w ogóle nie zdarzeń w dzienniku.

```
[2019-08-23 11:20:42] local.DEBUG: Allegro API debug information about request.
#
# [GET] https://api.allegro.pl.allegrosandbox.pl/order/events?type%5B0%5D=READY_FOR_PROCESSING&type%5B1%5D=FILLED_IN&from=1563530992010084 
#
# Request Headers:
# [
#     User-Agent: GuzzleHttp/6.3.3 curl/7.63.0 PHP/7.2.14
#     Host: api.allegro.pl.allegrosandbox.pl
#     Authorization: Bearer [nie pokażę tokena]
#     Accept: application/vnd.allegro.beta.v1+json
#     Accept-Language: pl-PL
#     Cache-Control: no-cache
# ]
#
# Request Body:
# [
#     
# ]
#
# Response Status:
# [200]
#
# Response Headers:
#
# [
#     expires: 0
#     cache-control: no-cache, no-store, max-age=0, must-revalidate
#     x-xss-protection: 1; mode=block
#     server: envoy
#     pragma: no-cache
#     x-frame-options: DENY
#     trace-id: 9d12713ac23230ac
#     date: Fri, 23 Aug 2019 09:20:43 GMT
#     x-ratelimit-remaining: 9000
#     x-content-type-options: nosniff
#     content-type: application/vnd.allegro.beta.v1+json;charset=UTF-8
#     content-length: 13
#     x-ratelimit-limit: 9000
#     x-envoy-upstream-service-time: 126
# ]
#
# Response Body:
# [
#     {
#         "events": []
#     }
# ]
```

**Comment by rafalkrawiec** [comment]
Wygląda na to że zdarzenia się pojawiły w systemie ale z dużym opóźnieniem bo dopiero po godzinie. Problem z wydajnością?

Dodatkowo zauważyłem że przy składaniu zamówień bez zakładania konta, nie został wysłany email z kodem do potwierdzenia.

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie zasobu na Sandbox - bezproblemowo pobrałem dzisiejsze zamówienie. Nie mam żadnej informacji o opóźnieniach. 
Natomiast problem z wysyłką kodu przy zakupach bez rejestracji potwierdziłem i przekazałem do weryfikacji.

**Comment by rafalkrawiec** [comment]
Tak, teraz pobieranie działa już normalnie na bierząco. Problem był pomiędzy godziną 11:00 i 12:00.
