### ISSUE TITLE
Rest API - Prowizje od sprzedaży 

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#2145]
Witam. 
Czy istnieje zasób w rest api, który zwróci mi prowizję w procentach w zależności od podania id kategorii / nazwy kategorii ?

**Comment by MaciejFrackowiak** [comment]
Nie, takiego zasobu nie ma - udostępniamy natomiast [POST /pricing/fee-preview](https://developer.allegro.pl/documentation/#tag/Pricing) pozwalające kwotowo określić prowizję od sprzedaży w danej kategorii.
