### ISSUE TITLE
sale/offer-publication-commands/{commandId} - Problem z wznowieniem oferty

### ISSUE THREAD

**Issue by MLupinski** [allegro/allegro-api#2147]
WItam serdecznie,
Mam lekki problem z wznowieniem oferty, która została zakończona przez użytkownika około 7 dni temu.

**Request**
`{
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "6206269517"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ],
  "publication": {
    "action": "ACTIVATE"
  }
}
`
**RESPONSE**
`{
  "id": "87c28171-243c-42df-7347-006206269517",
  "taskCount": {
    "total": 1,
    "success": 0,
    "failed": 1
  }
}`

Również podczas próby zmiany ilości dostępnych produktów dostaję 422, nie wiadomo dlaczego, przy innych ofertach jest normalnie. Zakończyłem jedną ofertę przez PUT, a później dla testów aktywowałem po około 60 minutach i przeszło bez problemu.

**Comment by MaciejFrackowiak** [comment]
Czy sprawdziłeś szczegółowy status operacji poprzez [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET)? Przed momentem wystawiłem i wznowiłem na Sandbox identyczną ofertę - proces przebiegł bezproblemowo.

**Comment by MLupinski** [comment]
```
{
  "tasks": [
    {
      "offer": {
        "id": "6206269517"
      },
      "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
      "status": "FAIL",
      "scheduledAt": "2019-08-23T17:46:41.238Z",
      "finishedAt": "2019-08-23T17:46:53.376Z",
      "field": "publication",
      "errors": [
        {
          "code": "CHANGE_PUBLICATION_STATUS_ERROR",
          "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
          "userMessage": "An error occurred while trying to change the publication of the offer. Please try again later."
        }
      ]
    }
  ]
}
```
Ofertę, którą zamknę i wznowię teraz też bez problemu przechodzi. Chodzi o oferty, które zostały zamknięte jakiś czas temu.

**Comment by MaciejFrackowiak** [comment]
W ramach testu wznowiłem właśnie ofertę zakończoną 11 sierpnia - tu również nie napotkałem na problem. Czy dla wskazanej oferty problem ze wznowieniem dalej występuje - dopytuję, ponieważ widzę, że operację wykonywałeś 23 sierpnia.

**Comment by MLupinski** [comment]
Tak występuje w dalszym ciągu, robiłem test dzisiaj. Zamknąłem ręcznie jedną z ofert, które były aktywne, przez API zmieniłem jej ilość olać wznowiłem (tutaj bez problemów przeszło).
Przeszedłem do problemowej oferty i znów przy zmianie ilości błąd 422 (prześlę niedługo jakie wysyłam zapytanie) i co wysyłam wznowienie, które skutkuje odpowiedzą jak powyżej.

**Comment by MaciejFrackowiak** [comment]
Proszę prześlij request i response dla operacji, którą wykonywałeś wczoraj.

**Comment by MLupinski** [comment]
Zapytania wykonane dosłownie z 10 minut temu.
Dla zmiany ilości

**Request**

```
{
  "id": "6206269517",
  "name": "Fairy Platinum",
  "category": {
    "id": "128"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": []
    }
  ],
  "ean": "4084500962927",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.allegrosandbox.pl/original/03e70a/d98d0d1f471aa53f882ae9353075"
          },
          {
            "type": "TEXT",
            "content": "\u003cp\u003eOpis testowy\u003c/p\u003e"
          }
        ]
      }
    ]
  },
  "images": [
    {
      "url": "https://a.allegroimg.allegrosandbox.pl/original/03e70a/d98d0d1f471aa53f882ae9353075"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "99",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 1,
    "unit": "UNIT"
  },
  "publication": {
    "status": "ENDED",
    "endedBy": "EXPIRATION",
    "republish": false
  },
  "delivery": {
    "handlingTime": "PT24H"
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {},
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "WIELKOPOLSKIE",
    "city": "Kórnik",
    "postCode": "62-035"
  },
  "attachments": [],
  "validation": {
    "errors": [],
    "validatedAt": "2019-08-16T13:59:04.935Z"
  },
  "createdAt": "2019-04-11T12:30:18Z",
  "updatedAt": "2019-08-19T12:32:28.348Z"
}
```

**Response**

``

Dla aktywacji oferty

**Request**

```
{
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "6206269517"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ],
  "publication": {
    "action": "ACTIVATE"
  }
}
```

**Response**
`422: Unprocessable Entity`
```
{
  "tasks": [
    {
      "offer": {
        "id": "6206269517"
      },
      "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
      "status": "FAIL",
      "scheduledAt": "2019-08-27T12:28:49.154Z",
      "finishedAt": "2019-08-27T12:54:45.179Z",
      "field": "publication",
      "errors": [
        {
          "code": "CHANGE_PUBLICATION_STATUS_ERROR",
          "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
          "userMessage": "An error occurred while trying to change the publication of the offer. Please try again later."
        }
      ]
    }
  ]
}
```

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przesłane dane. Po przeprowadzeniu weryfikacji okazało się, że wskazana oferta faktycznie trwa, a tylko na froncie Sandbox wygląda jak zakończona - to dlatego nie udaje się jej aktywować. Problem zgłosiłem do odpowiedniego zespołu.

**Comment by MaciejFrackowiak** [comment]
Dane zostały uspójnione i obecnie wznowienie oferty jest już możliwe.
