### ISSUE TITLE
Program 0.5% prowizji a cena aktualizowana przez REST API

### ISSUE THREAD

**Issue by netfarma** [allegro/allegro-api#2148]
Cześć,
chcemy wziąć udział w kampani:
```https://allegro.pl/dla-sprzedajacych/program-bonusowy-prowizja-nawet-0-5-WEL8e9mMyIG```
Aby nie trzeba było przesyłać nowej ceny przez API do Allegro uzgodniliśmy z Wami, że dla zgłoszonych ofert obniżycie cenę produktu na czas promocji a po zakończeniu przywrócicie ją.

Tutaj mam pewną wątpliwość:
Obecnie codziennie synchronizujemy ceny sklepowe z Allegro między innymi poprzez endpoint ```PUT /sale/offers/{offerId}. ```
Czy jeśli dokonamy takiej aktualizacji oferty (także ceny) przez API, to czy wpłynie ona na ustaloną wcześniej ofertę promocyjną?
Czy po prostu zmieni się tylko cena bazowa oferty, a ustalona cena promocyjna pozostanie?
Czy musimy wyłączyć synchronizację cen, dla ofert, które są zgłoszone do programu?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Zmiana ceny poprzez [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) odnosi się do bieżącej ceny przedmiotu. Natomiast w odniesieniu do ceny promocyjnej proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=9c85a0b2-31db-40bd-9745-818e44b5843c).

**Comment by netfarma** [comment]
Czyli mam rozumieć, że zmiana ceny przez  PUT /sale/offers/{offerId} nie zmodyfikuje ustalonej ceny promocyjnej?

**Comment by MaciejFrackowiak** [comment]
Zasób zmienia tylko aktualną cenę przedmiotu. Natomiast do obsługi kampanii i cen promocyjnych udostępniamy osobne [zasoby](https://developer.allegro.pl/badge/).

**Comment by netfarma** [comment]
Witam.
Wczoraj zgłosiliśmy produktty w związku z Black week.
Ceny produktów zostały przez Was obniżone.
Niestety dziś nasz automat zaktualizował cenę bazową. Cena z kampanii miała pozostać niezmienna jednak tak się nie stało i produkty trafiły do weryfikacji z powodu podniesienia ceny.. :(

Co powinniśmy teraz  zrobić?

**Comment by MaciejFrackowiak** [comment]
@netfarma Proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).
