### ISSUE TITLE
Błąd "Expected numeric parameter value for parameter: Długość wkładki(203093)" podczas uzupełniania draftu danymi.

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2149]
Dobry. Mam problem z uzupełnianiem draftu. Otóż, gdy wypełniam pola takie jak Długość wkładki czy Maksymalną szerokość (pola z liczbami po przecinku), wyrzuca błąd: "Expected numeric parameter value for parameter". Nie wiem, co jest nie tak. 

Parametr jest przesyłany w takiej formie:
`{"id":"203093","values":["24,5"]}`

Oferta jest wystawiana na Allegro, jednak zaokrągla sobie podaną wartość bez powodu. Próbowałem również zapisać liczbę w formie z przecinkiem zamiast kropki, żadnej różnicy.

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam pełne request i response.

**Comment by imper86** [comment]
@hahyes a w tych polach nie musisz przypadkiem podać wartości numerycznej? Jeżeli w jsonie podajesz coś pomiędzy cudzysłowami to jest to odbierane jako string. Poza tym z pewnością będzie tam kropka, nie przecinek.

**Comment by MaciejFrackowiak** [comment]
Parametr o id=203093 to Długość wkładki. Jest to parametr typu float, gdzie można wprowadzić wartość od 0.0 do 40.0 z dwoma miejscami po przecinku. Koniecznie zastosuj “kropkę” pomiędzy wartościami.
