### ISSUE TITLE
Przy wystawianiu aukcji otrzymuję błąd ERR_OBLIGATORY_ATTRIB_NOT_SET

### ISSUE THREAD

**Issue by umnierazniej** [allegro/allegro-api#215]
Witam,
Przy wystawianiu aukcji otrzymuję błąd:

> ERR_OBLIGATORY_ATTRIB_NOT_SET Nie podano parametru wymaganego dla wybranej kategorii. (Typ - fid: 26704)

Proszę o informację o co konkretnie chodzi bo wszystkie inne parametry ustawiłem, a wystawianie produktu z innej kategorii działa.

**Comment by LukaszKorek** [comment]
Abym mógł zweryfikować zgłoszenie proszę o nr kategorii, której dotyczy sprawa,

**Comment by umnierazniej** [comment]
Komputery Laptopy Apple

**Comment by LukaszKorek** [comment]
Sprawdziłem i ten parametr jest obowiązkowy w tej kategorii. Listę parametrów i pozostałych pól możesz sprawdzić metodą: https://allegro.pl/webapi/documentation.php/show/id,782

**Comment by umnierazniej** [comment]
Witam,  A jaki to jest parametr?  Wszystkie pola mi ściąga i tego akurat nie mam.

**Comment by LukaszKorek** [comment]
To parametr "typ". Ściągnij najnowszy WSDL https://webapi.allegro.pl/service.php?wsdl i ponownie pobierz pola z kategorii.
