### ISSUE TITLE
Wyszukiwanie ofert po numerze EAN

### ISSUE THREAD

**Issue by patrys666** [allegro/allegro-api#2151]
Czy są jakieś nowe informacje odnośnie wyszukiwania po ean? Minął rok od podobnego tematu lecz nie znalazłem żadnych nowych informacji.

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj, czy masz na myśli wyszukiwanie po EAN w wyszukiwarce czy w zakładce Moje oferty?

**Comment by patrys666** [comment]
@MaciejFrackowiak  Chodzi mi o wyszukiwanie ofert w serwisie.

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) pozwala na wyszukiwanie ofert po EAN - wystarczy jako query parameters “phrase” podać szukany EAN. Zasób ten odzwierciedla w pełni możliwości wyszukiwarki serwisu WWW.
