### ISSUE TITLE
Masowa edycja cen licytacji

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2153]
Dzień dobry

Do edycji cen w ofertach Kup Teraz można wykorzystać zasób /sale/offer-price-change-commands/{commandId} czy istnieje możliwość masowej edycji cen startowych w licytacjach, jeśli nie czy planują państwo udostępnić taki zasób?

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy zasobu umożliwiającego masową zmianę ceny początkowej w licytacjach. Twoją sugestię przekażę do działu odpowiedzialnego za rozwój REST API.

**Comment by ppart** [comment]
Podbijam temat, również bylibyśmy zainteresowani takim zasobem.

**Comment by MaciejFrackowiak** [comment]
@ppart Przekazałem informację o większym zainteresowaniu wdrożeniem takiego zasobu.

**Comment by ppart** [comment]
Jak wygląda sytuacja masowej zmiany ceny w licytacjach? Czy coś wiadomo w tej sprawie?

**Comment by MaciejFrackowiak** [comment]
Nie, jeszcze nie mam żadnej informacji co do ewentualnych zmian w tym zasobie.

**Comment by ppart** [comment]
Odświeżam temat bo funkcja na pewno była by przydatna. Dziękuję

**Comment by MaciejFrackowiak** [comment]
@ppart W ramach update - nie mam żadnych nowych, wiążących informacji do przekazania. W momencie, gdy wprowadzimy zmianę poinformujemy o tym w dedykowanym komunikacie na GitHub - warto śledzić te z labelką "news".

**Comment by ppart** [comment]
Dzień dobry

Chciałbym zapytać czy jest znany jakiś realny termin na wdrożenie, czy temat został tylko przekazany bez konkretnych informacji?

Dziękuję

**Comment by HMX24** [comment]
Witam. Znam wielu sprzedawców poprzez licytacje i ta funkcja musi sie pojawic w celu zwiekszenia obrotów dwóch stron. Popieram to słuszna decyzja.

**Comment by MaciejFrackowiak** [comment]
@ppart Nie, w chwili obecnej nie mogę przedstawić jednoznacznego terminu wdrożenia tego rozwiązania. Jak wspomniałem w przypadku zmiany opublikujemy news.

**Comment by MaciejFrackowiak** [comment]
@HMX24 Twój głos zapisuję również.
