### ISSUE TITLE
Problem z wydajnością https://api.allegro.pl/sale/offers/

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2154]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

od 12:09 mam już ponad 100 błędów 504 i jedną 500.
Coś się dzieje z wydajnością.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, chwilę po godz. 12 odnotowaliśmy niewielką grupę wywołań z błędem, jednak obecnie wydaje się, że wszystko wróciło do normy.

**Comment by kfijalko** [comment]
o 12:53 dostałem kilka 500 na 
https://api.allegro.pl/sale/offers/8028xxxxx/tags

**Comment by kfijalko** [comment]
cały czas lecą 500

**Comment by kfijalko** [comment]
Teraz https://api.allegro.pl/order/checkout-forms/52822482-c8b4-1XXXXX776c3002b komunikat allegro:ServiceTimeoutException

Cały czas coś się sypie.

**Comment by MaciejFrackowiak** [comment]
Poprosiłem o dokładne przyjrzenie się zauważonym przez Ciebie błędom.

**Comment by kfijalko** [comment]
@MaciejFrackowiak problemy cały czas występują (lecą 50X), dodatkowo dziś czasy odpowiedzi są jakieś masakryczne.

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj dzisiejsze zgłoszenie - na jakich zasobach odnotowałeś wymienione problemy?

**Comment by kfijalko** [comment]
Dzisiejsze logi już skasowałem, jutro rano dam znać jeżeli nadal będą błędy.

**Comment by MaciejFrackowiak** [comment]
Dobrze, czekamy na dane.

**Comment by kfijalko** [comment]
Dziś mam 17 sztuk 500 i 503 na zasobie:
https://api.allegro.pl/sale/offers/788xxxxx9/tags
pobieram dane dla 200k ofert więc dla mnie jest to pomijalne.
Zauważyłem jeszcze jeden problem, do tej pory pobranie danych ofert zajmowało mi około 1h. Od 2 dni zajmuje to około 5h. Najpierw poszukam problemu u siebie, jak nie znajdę to zacznę logować czasy odpowiedzi z usług allegro (teraz tego nie robię).

**Comment by kfijalko** [comment]
@MaciejFrackowiak pojawił się nowy - stary błąd (dawno go nie widziałem). Wystąpił ok 10 razy:
[2019-08-30 07:46:47] local.CRITICAL: App\Allegro\AllegroClientOffer::getOffer:72Wystąpił błąd podczas wywoływania https://api.allegro.pl/sale/offers/79XXXX5502 komunikat:Unable to communicate securely with peer: requested domain name does not match the server's certificate.

**Comment by MaciejFrackowiak** [comment]
Proszę prześlij pełne logi lub trace-id wywołań, gdyż tylko tak możemy to dokładnie zweryfikować.

**Comment by kfijalko** [comment]
nie mam logowania req/res

**Comment by MaciejFrackowiak** [comment]
Niestety, bez logów nie mamy jak się odnieść do konkretnych uwag. Proszę zacznij logować request i response.

**Comment by kfijalko** [comment]
Ok, zobaczę co da się zrobić. Nie chcę zbierać wszystkich wywołań bo jest tego za dużo. Sprawdzę czy jestem w stanie zbierać dla błędnych.

**Comment by kfijalko** [comment]
dziś żadnego błędu 50X

**Comment by MaciejFrackowiak** [comment]
Dziękuję za info.
