### ISSUE TITLE
Brak informacji o liczbie sprzedanych produktów i o jednostce ilości produktu

### ISSUE THREAD

**Issue by dawidcocieto** [allegro/allegro-api#2156]
Cześć,
mam pytanie, dlaczego brakuje informacji o jednostce ilości produktu (klucz 'unit') w zasobie: https://api.allegro.pl/sale/offers

Jak również dlaczego nie są zwracane informacje o liczbie sprzedanych produktów pobierając wszystkie pola oferty z zasobu:
https://api.allegro.pl/sale/offers/{offerId}

za odpowiedź z góry dziękuję.

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) bazuje na informacjach dostępnych w ramach zakładki Moje oferty w serwisie WWW - tam również podajemy tylko ilość, bez jednostek.

Natomiast zasób [GET sale/offers/{offersId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) zwraca tylko ilość dostępnych aktualnie sztuk. Twoje zgłoszenie przekażę jako sugestię rozwoju REST API.
