### ISSUE TITLE
Allegro SandBox - dodawanie warunków reklamacji, zwrotów i gwarancji

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#2157]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie dodania warunków reklamacji, zwrotów bądź gwarancji na portalu https://allegro.pl.allegrosandbox.pl/afterSalesServiceConditions/impliedWarranty/ otrzymuje zawsze taki sam komunikat.

> Próba otwarcie strony została zablokowana
Aby chronić naszych użytkowników stosujemy aktywną ochronę przed złośliwym ruchem. Twoje zapytanie zostało zakwalifikowane jako jedno z nich. Jeśli uważasz inaczej, zgłoś ten przypadek obsłudze klienta załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego problemu.

> Kod błędu
1db1feaafebfb8ba

Chciałem dodać te warunki aby sprawdzić czy poprawnie pobierają się u mnie w systemie. Próbowałem w poniedziałek 26.08 i zaczekałem w nadziei, że nastąpi jakaś poprawa - niestety, problem wciąż jest obecny.

**Comment by MaciejFrackowiak** [comment]
Problem potwierdzam - przekazuję go do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
@Bodzix Problem usunięty - możesz już dodać / edytować warunki zwrotów/reklamacji/gwarancji.
