### ISSUE TITLE
Pobranie oferty i edycja ceny minimalnej licytacji

### ISSUE THREAD

**Issue by kodowaniephp** [allegro/allegro-api#2158]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Skrypt pobiera mi ofertę.
Zmieniam wartość ceny minimalnej.

I ponownie dokonuje zapisu.

Jednak nie działa mi.

   $tokens = json_decode(file_get_contents('../../../klasy/allegroRestApi/tokens.json'));
    $accessToken = $tokens->access_token;
    $refreshToken = $tokens->refresh_token;

    $api = new \Allegro\REST\Api($clientId, $clientSecret, $apiKey, $redirectUri, $accessToken, $refreshToken);

    // odświeżamy token
    $response = $api->refreshAccessToken();
    file_put_contents('../../../klasy/allegroRestApi/tokens.json', $response);

    //pobranie aukcji
    $response = $api->sale->offers($numerAukcji)->get();
    $response = json_decode($response);

    // $this->_lista($response);

    //zmiana ceny
    // $response->sellingMode->startingPrice->amount = $cena;
    // $response->sellingMode->startingPrice->currency = 'PLN';

    $response->sellingMode->startingPrice->amount = 3.09;
    $response->sellingMode->startingPrice->currency = 'PLN';
    $response->sellingMode->minimalPrice->amount = 12.01;
    $response->sellingMode->minimalPrice->currency = 'PLN';

    // $this->_lista($response);

    //zapisanie aukcji
    $response2 = $api->sale->offers($numerAukcji)->put($response);
    $response2 = json_decode($response2);

    $this->_lista($response2);

Nie działa. Jakaś sugestia?
W przypadku edycji np tytułu. Działa bezproblemowo.

Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Z racji dużej liczby języków programowania, nie jesteśmy w stanie prowadzić wsparcia dla każdego z nich. Być może ktoś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.

**Comment by DarkStoorM** [comment]
A co otrzymujesz w response? Ceny minimalnej chyba nie można zmienić jeżeli aktualna ją przekroczy.
