### ISSUE TITLE
Brak obsługi większej ilości zdjęć na sandboxie

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#216]
Brakuje obsługi FID w zakresie 342-349. Metoda doGetSellFormFieldsForCategory na sandboxie ich nie zwraca.

**Comment by LukaszKorek** [comment]
Metoda ta zwraca te fidy, ale musisz mieć konto firmowe.

**Comment by kormichu** [comment]
A to nie jest czasem tak, że dla zwykłego konta jestem w stanie wrzucić 10 zdjęć ? Z poziomu kreatora webowego mam do wyboru 10 zdjęć. W FIDach zaś mieszczę się tylko w 8.

Czy mógłbyś zaakceptować weryfikacje konta firmowego dla "kormichu2" ?

**Comment by kormichu** [comment]
Sprawdzałem przed chwilą na produkcyjnym koncie prywatnym i FIDy 342-349 są dostępne więc to nie kwestia tego że konto musi być firmowe

**Comment by LukaszKorek** [comment]
Konto zweryfikowaliśmy i jest już firmowe. Sprawdziłem i metoda zwraca te fidy. Pobierz jeszcze raz wsdl, a jeśli problem będzie dalej występował podeśli request i response w formacie .xml https://allegro.pl/pomoc/kontakt

**Comment by kormichu** [comment]
Ok już zwraca. Dzięki
