### ISSUE TITLE
order/checkout-forms vs order/events

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#2161]
Witam,

W dokumentacji jest mowa o pobieraniu informacji o zamówieniach przez order/events i potem szczegółów, ale czy jest jakieś przeciwwskazanie, żeby pobierać zamówienia od razu z zasobu order/checkout-forms zamiast najpierw z order/events? Czy coś można zrobić źle/niedokładnie pobierając od razu order/checkout-forms ?

Przy okazji mam pytanie odnośnie statusów BOUGHT, FILLED_IN i READY_FOR_PROCESSING w order/checkout-forms .

Czy jeśli klient kontynuuje wypełnianie FOD i dokonuje wpłaty, to te rekordy z BOUGHT są ukrywane, czy modyfikowane na FILLED_IN itd.
Chodzi o to, czy jak pobiorę zdarzenie ze statusem BOUGHT o jakimś ID, to czy potem będę miał zdarzenie o tym samym ID ale z kolejnym statusem?

**Comment by MaciejFrackowiak** [comment]
Dla [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) dane zwracane w response sortujemy na podstawie daty z pola "boughtAt". Jeśli kupujący zapłaci za zakupione towary później informacja o takim zamówieniu nie pojawi się jako najnowsza, tylko zgodnie z datą zakupu. Dlatego korzystanie z [GET /order/events](https://developer.allegro.pl/orders/#02) pozwala monitorować sprzedaż i poprawnie pobierać informacje o najnowszych zamówieniach. Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#03).

**Comment by copyact** [comment]
Dziękuję. 
Rozumiem. Tylko nie wiem, czy to stwarza jakiś problem? 
Rozumiem, że np dla statusu READY_FOR_PROCESSING w /order/checkout-forms będę miał te same zamówienia, co w /order/events tylko nie będę miał daty płatności, a datę zakupu?

Chciałbym ustalić, czy to jedyna różnica?

**Comment by jakubmaguza** [comment]
Od ponad pół roku pobieram zamówienia tylko z checkout-forms i nie ma żadnego problemu. Żadne zamówienie nie zostało też pominięte.

**Comment by neldh** [comment]
jak nie patrzysz na orders/events, to możesz pominąć dopłaty (jak masz filtr na boughtAt np na 3 dni, a klient zrobi dopłate po 4 dniach od pierwotnego zakupu). Jak klienci ich nie robią, albo nie potrzebujesz informacji o dopłatach, to możesz pominąć pobieranie orders/events

**Comment by copyact** [comment]
Dzięki. Wszystko jasne:)
