### ISSUE TITLE
sale/offer-publication-commands - an error occurred?

### ISSUE THREAD

**Issue by mankovsky** [allegro/allegro-api#2162]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Dzień dobry, chciałbym się dowiedzieć co oznacza enigmatyczny opis błędu **An error occurred while trying to change the publication of the offer. Please try again later.** który niestety bardzo często się powtarza u naszych klientów podczas próby publikacji ogłoszenia

array:2 [▼
  "header" => array:26 [▼
    "url" => "https://api.allegro.pl/sale/offer-publication-commands/ea66bb80-9595-b9f5-6966-e9d80a83f83d/tasks"
    "content_type" => "application/vnd.allegro.public.v1+json;charset=UTF-8"
    "http_code" => 200
    "header_size" => 465
    "request_size" => 830
    "filetime" => -1
    "ssl_verify_result" => 0
    "redirect_count" => 0
    "total_time" => 0.255803
    "namelookup_time" => 0.060601
    "connect_time" => 0.094547
    "pretransfer_time" => 0.177392
    "size_upload" => 0.0
    "size_download" => 566.0
    "speed_download" => 2212.0
    "speed_upload" => 0.0
    "download_content_length" => -1.0
    "upload_content_length" => -1.0
    "starttransfer_time" => 0.255711
    "redirect_time" => 0.0
    "redirect_url" => ""
    "primary_ip" => "5.134.213.11"
    "certinfo" => []
    "primary_port" => 443
    "local_ip" => "149.202.166.211"
    "local_port" => 53998
  ]
  "data" => array:1 [▼
    "tasks" => array:1 [▼
      0 => array:7 [▼
        "offer" => array:1 [▼
          "id" => "8441224655"
        ]
        "message" => "An error occurred while trying to change the publication of the offer. Please try again later."
        "status" => "FAIL"
        "scheduledAt" => "2019-08-29T10:03:53.122Z"
        "finishedAt" => "2019-08-29T10:05:08.975Z"
        "field" => "publication"
        "errors" => array:1 [▼
          0 => array:5 [▼
            "code" => "CHANGE_PUBLICATION_STATUS_ERROR"
            "message" => "An error occurred while trying to change the publication of the offer. Please try again later."
            "details" => null
            "path" => null
            "userMessage" => "An error occurred while trying to change the publication of the offer. Please try again later."
          ]
        ]
      ]
    ]
  ]
]

**Comment by MaciejFrackowiak** [comment]
Czy mógłbyś podać nam trace-id wywołania?
