### ISSUE TITLE
GET /after-sales-service-conditions

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#2163]
czy coś się zmieniło w zasobie GET /after-sales-service-conditions? Moje rozwiązanie które zawsze działało przestało działać

**Comment by MaciejFrackowiak** [comment]
Nie, niczego nie zmienialiśmy. Zasób działa w pełni prawidłowo. Proszę zweryfikuj sytuację u siebie. Jeżeli dalej będziesz miał problem prześlij proszę response jaki otrzymujesz oraz trace-id.

**Comment by riepa** [comment]
po mojej stronie nic nie zmieniło się w tej metodzie od roku i zawsze działała a teraz dostaję co chwilę błąd FullExceptionMessage:Connection lost (error code is 10058)

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam trace-id oraz request / response, wówczas się przyjrzymy.

**Comment by riepa** [comment]
Identyczny błąd pojawił mi się wczoraj około 11 przy metodzie POST /sale/offers.

trace-id e16a9fd6-4991-4ba2-bde4-984e2ec8d751

`{
  "name": "Młotek gumowy 0,6 kg DEXTER",
  "ean": "3276005787650",
  "category": {
    "id": "111852"
  },
  "external": null,
  "payments": {
    "invoice": "VAT"
  },
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "delivery": {
    "shippingRates": {
      "id": "29c2a6fc-2e90-4816-8eeb-3e238ded905f"
    },
    "handlingTime": "PT24H",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "publication": {
    "duration": "PT480H",
    "status": "INACTIVE",
    "startingAt": null,
    "endingAt": null
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Producent: DEXTER\n</p><p>Waga (w kg): 0.6\n</p><p>Długość (w cm): 33\n</p><p>Długość uchwytu (w cm): 28\n</p><p>Materiał wykonania uchwytu: Drewno\n</p><p>Kolor: Biały\n</p>"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "MAZOWIECKIE",
    "city": "Piastów",
    "postCode": "05-820"
  },
  "stock": {
    "available": 5,
    "unit": "UNIT"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "7217907e-82f8-4327-8517-b7425982561a"
    },
    "returnPolicy": {
      "id": "51f931ad-17e8-43f0-82b0-163c1e328693"
    },
    "warranty": {
      "id": "b1cbe291-144a-4bba-9a64-99087f5612a0"
    }
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "34.99",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "17448",
      "valuesIds": [],
      "values": [
        "0.600"
      ],
      "rangeValue": null
    }
  ],
  "images": [
    {
      "url": "https://a.allegroimg.com/original/118a7d/4ab52a7143f8a4a3106be78ee8b7"
    },
    {
      "url": "https://a.allegroimg.com/original/112f1f/d8c467e24d6eace2b7a7d3210739"
    }
  ]
}`

`FullExceptionMessage:Connection lost (error code is 10058)`

**Comment by MaciejFrackowiak** [comment]
Podany przez Ciebie ciąg bardziej odpowiada UUID aniżeli trace-id. Proszę sprawdź jego poprawność.
