### ISSUE TITLE
REST API ALLEGRO

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2164]
Hi Team,
We have an issue while product upload it is not showing what type of Error is So that we can correct it but it is showing error Like this

[code] => ERROR
[message] => An error has occurred
[details] => 
[path] => /sale/product-proposals
[userMessage] => 

API call is https://api.allegro.pl/sale/product-proposals
While Sending correct data as in Json But not sending response please check it and send us response.
We have corporate account by email id <marcin.piechota@sportmma.pl>.

**Comment by MaciejFrackowiak** [comment]
Please, send us a request and response in cURL format with trace-id, we will check this.

**Comment by sportmma** [comment]
[12:37, 30.08.2019] +91 94554 54086: Hi marcin
[12:38, 30.08.2019] +91 94554 54086: kindly send them this curl response to them
[12:38, 30.08.2019] +91 94554 54086: please send this as soon as possible
[12:41, 30.08.2019] +91 94554 54086: curl -X POST \
 ‘https://api.allegro.pl/sale/product-proposals’ \
 -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjcyMDQ3ODYsInVzZXJfbmFtZSI6IjYzOTk2NjU4IiwianRpIjoiNjYwMGY4MWUtNDcxNy00YmUyLTk3OTAtOTRjOTkxZDVkYmZiIiwiY2xpZW50X2lkIjoiZjFjOTVhNjA1MTQzNDc2ZjgxZWE3NDE3MzJlOTJiNTEiLCJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdfQ.p6cLqENytSXZ8GUqu3ANuGpywPpUgOm5ijvx1DB5RLV9gfNBCQMsyWGpBenn81T4B_XchCoqqepAqIrPcRsh-fwC6H3c_6YfqnbavoKrWuWr5myIpZ6-tkQTdfkkZadfuXkq8kWfes4HtkVCmStQtETGupFKXrRVnN9e9IkycK1XR4mLKwODgq2bysCwLPAKL2ASMJO9PEyJfrnqs-5yAm86g0g-D7J3w5h9AaqqGHiPG9hBxTW1a7yJYvh3MIYbqvvrYTenaa42beIEz-Z6nMTbU1L9KY2xYAc9xYPnyESTfazDR8bG0qZum5dKkXY4oNeMuo42F62OwTp5Qg5Vsg' \
 -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
 -H 'accept: application/vnd.allegro.beta.v1+json' \
-d '
{"name":"Shirt","category":{"id":"84735"},"eans":["892685001003"],"images":{"url":["http:\/\/192.168.1.225\/Magento\/2.3.2\/pub\/media\/catalog\/product\/i\/m\/images.jpeg"]},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"5488","valuesIds":["5488_4"],"values":[],"rangeValue":null},{"id":"127788","valuesIds":["127788_270434"],"values":[],"rangeValue":null},{"id":"127768","valuesIds":["127768_7"],"values":[],"rangeValue":null},{"id":"4906","valuesIds":["4906_128"],"values":[],"rangeValue":null},{"id":"127789","valuesIds":["127789_1"],"values":[],"rangeValue":null}],"standardized":{"sections":[{"items":[{"type":"TEXT","content":"\u00a0wefrghjkoyuirtewqa"}]}]}}'
[13:01, 30.08.2019] +91 94554 54086: Clinet Id :f1c95a605143476f81ea741732e92b51
secret key : ESNEOfQZBmhgh3QGDHMa6K6V5gtkVBwaBm2sWBIGKP0C7dhjOdzczQXANLC1pTwH
[13:02, 30.08.2019] +91 94554 54086: please send them all by mail

**Comment by MaciejFrackowiak** [comment]
As I see you wrote to us by contact form. We will answer there.

**Comment by sportmma** [comment]
[3.09, 09:13] +91 94554 54086: please ask them about this issue
these categories we can list product what is the issue 

https://apps.developer.allegro.pl
client Id: f1c95a605143476f81ea741732e92b51
client secret:
ESNEOfQZBmhgh3QGDHMa6K6V5gtkVBwaBm2sWBIGKP0C7dhjOdzczQXANLC1pTwH 

Cannot create products in category: 259434
Cannot create products in category: 254260
[3.09, 09:14] +91 94554 54086: while creating product on allegro we can
list in these categories
[3.09, 09:15] +91 94554 54086: please ask them about your account
activation why this issue occur

**Comment by MaciejFrackowiak** [comment]
In both categories you can not create product - you can check it using resource GET /sale/categories/{categoryId} - in a field "productCreationEnabled" you will get response - false or true.
Please, remember do not post Client IdD, Client Secret, Token on GitHub.

**Comment by hengwo** [comment]
productCreationEnabled="false" category not support upload?

**Comment by MaciejFrackowiak** [comment]
Field “productCreationEnabled” means that category supports adding a product - more information you will find in [our tutorial](https://developer.allegro.pl/en/productization/).

**Comment by hengwo** [comment]
productCreationEnabled="false" mean this category not support adding a product whit allegro api?

**Comment by MaciejFrackowiak** [comment]
Yes, indeed.

**Comment by hengwo** [comment]
can you help me open this category id productCreationEnabled="true"

**Comment by MaciejFrackowiak** [comment]
Categories in REST API are similar to categories in Allegro WWW service. If there category is not enable to create product, in REST API category will not be product enable. Unfortunately, I cannot change it on request.

**Comment by hengwo** [comment]
Is there any other way to create a product in this category?

**Comment by MaciejFrackowiak** [comment]
No, it is impossible. We are slowly expanding the number of categories where products are available.
