### ISSUE TITLE
REST API - skąd wziąć username użytkownika dodawanego konta?

### ISSUE THREAD

**Issue by malbrandt** [allegro/allegro-api#2165]
1) Skąd można wziąć `username` (nazwa użytkownika allegro)?
2) Czy i gdzie klient (użytkownik Allegro) może sprawdzić `seller.id` (te numeryczne)? 

Chcę umożliwić dodawanie kilku kont Allegro w celu synchronizacji zamówień i chciałbym je w prosty sposób rozróżniać, aby klienci wiedzieli które jest które - najlepiej po `username`. Widziałem, że konkurencyjna strona rozróżnia konta po `username` ale nie wiem, skąd mogę to wziąć.

Czy jest jakiś odpowiednik endpointa `https://allegro.pl/login/user` w REST API?
Lub czy można jakoś użyć tego endpointa z innej strony niż allegro.pl będącym zalogowanym użytkownikiem (oznaczałoby to konieczność złamania polityki `Access-Control-Allow-Origin`).

Widziałem, że jest taki [endpoint w WebAPI (doGetUserLogin)](https://allegro.pl/webapi/documentation.php/show/id,104#method-input
) ale planowane jest jego wyłącznie w marciu 2020 roku, więc wolałbym się oprzeć na czymś stabilniejszym.

**Comment by MaciejFrackowiak** [comment]
Pracujemy nad zasobem umożliwiającym pobieranie danych o użytkowniku - obecnie ID konta możesz zdekodować z tokenu. Więcej o planowanych zmianach znajdziesz w [naszym harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by alekskuc** [comment]
Witam, skoro temat barku username z poziomu rest api został po raz kolejny poruszony, to przy okazji zapytam dlaczego username nie może być zakodowany w tokenie razem z seller.id?

**Comment by MaciejFrackowiak** [comment]
Username może być zmienne, natomiast ID konta jest jedno i jednoznacznie identyfikuje konto.

**Comment by malbrandt** [comment]
> Username może być zmienne, natomiast ID konta jest jedno i jednoznacznie identyfikuje konto.

W którym miejscu użytownik Allegro mógłby sprawdzić swoje ID konta?

**Comment by vbdbsoft** [comment]
karta OCENY I KOMENTARZE ujawnia id konta
