### ISSUE TITLE
allegro api

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2166]
Podczas przesyłania produktu wystąpił problem. Nie pokazuje on, jaki jest typ błędu. Abyśmy mogli go naprawić, ale wyświetla błąd.

[code] => ERROR
[message] => An error has occurred
[details] =>
[path] => /sale/product-proposals
[userMessage] =>

Wywołanie API to https://api.allegro.pl/sale/product-propozycje
Podczas wysyłania poprawnych danych jak w Json Ale nie wysyłając odpowiedzi, sprawdź to i wyślij nam odpowiedź.
Posiadamy konto firmowe na adres e-mail marcin.piechota@sportmma.pl.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem w wątku [GitHub #2164](https://github.com/allegro/allegro-api/issues/2164) proszę prześlij request i response w formacie cURL wraz z trace-id.

**Comment by sportmma** [comment]
[12:41, 30.08.2019] +91 94554 54086: curl -X POST \
'https://api.allegro.pl/sale/product-proposals' \
-H 'Authorization: Bearer
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjcyMDQ3ODYsInVzZXJfbmFtZSI6IjYzOTk2NjU4IiwianRpIjoiNjYwMGY4MWUtNDcxNy00YmUyLTk3OTAtOTRjOTkxZDVkYmZiIiwiY2xpZW50X2lkIjoiZjFjOTVhNjA1MTQzNDc2ZjgxZWE3NDE3MzJlOTJiNTEiLCJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdfQ.p6cLqENytSXZ8GUqu3ANuGpywPpUgOm5ijvx1DB5RLV9gfNBCQMsyWGpBenn81T4B_XchCoqqepAqIrPcRsh-fwC6H3c_6YfqnbavoKrWuWr5myIpZ6-tkQTdfkkZadfuXkq8kWfes4HtkVCmStQtETGupFKXrRVnN9e9IkycK1XR4mLKwODgq2bysCwLPAKL2ASMJO9PEyJfrnqs-5yAm86g0g-D7J3w5h9AaqqGHiPG9hBxTW1a7yJYvh3MIYbqvvrYTenaa42beIEz-Z6nMTbU1L9KY2xYAc9xYPnyESTfazDR8bG0qZum5dKkXY4oNeMuo42F62OwTp5Qg5Vsg'
\
-H 'Content-Type: application/vnd.allegro.beta.v1+json' \
-H 'accept: application/vnd.allegro.beta.v1+json' \
-d '
{"name":"Shirt","category":{"id":"84735"},"eans":["892685001003"],"images":{"url":["http:\/\/192.168.1.225\/Magento\/2.3.2\/pub\/media\/catalog\/product\/i\/m\/images.jpeg"]},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"5488","valuesIds":["5488_4"],"values":[],"rangeValue":null},{"id":"127788","valuesIds":["127788_270434"],"values":[],"rangeValue":null},{"id":"127768","valuesIds":["127768_7"],"values":[],"rangeValue":null},{"id":"4906","valuesIds":["4906_128"],"values":[],"rangeValue":null},{"id":"127789","valuesIds":["127789_1"],"values":[],"rangeValue":null}],"standardized":{"sections":[{"items":[{"type":"TEXT","content":"\u00a0wefrghjkoyuirtewqa"}]}]}}'
[13:01, 30.08.2019] +91 94554 54086: Clinet Id
:f1c95a605143476f81ea741732e92b51
secret key :
ESNEOfQZBmhgh3QGDHMa6K6V5gtkVBwaBm2sWBIGKP0C7dhjOdzczQXANLC1pTwH

**Comment by MaciejFrackowiak** [comment]
Jak widzę napisałeś do nas również poprzez formularz kontaktowy. Odpowiedź udzielimy w tickecie.
