### ISSUE TITLE
Problem z pobraniem danych z zamówienia

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#2167]
- [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 
Klient twierdzi, że kupujący wypełnił dane do faktury i zazanczył, że chce otrzymać fakturę, co potwierdza mail który otrzymał sprzedający (nasz klient).
Jednak po pobraniu przez API naszą aplikacją zamówienie otrzymujemy:
  "invoice": {
    "required": true,
    "address": null
  },

Checkout form zamówienia to:
  "id": "f0179c32-c8d1-11e9-bbe7-eb94b2c14bb3"
Proszę o pomoc w wyjaśnieniu gdzie jest błąd i dlaczego aplikacja nie ściąga danych do faktury.
Genertalnie zwykle nie ma takiego problemu ale zdarzyło się tak wcześniej w kilku przypadkach.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, klient wypełnił prośbę o fakturę i podał dane, jednak w REST API ich nie widać. Problem zgłosiłem do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Problem został zweryfikowany - dane do faktury w REST API i w zakładce Zamówienia zwracamy tylko dla formularzy pozakupowych w statusie “READY_FOR_PROCESSING”. W opisanym przypadku status był “FILLED_IN”. Więcej informacji na temat statusów znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).
