### ISSUE TITLE
Informacje zwracane przez offers/listing?seller.id

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2168]
Czy jest możliwośc żeby w zapytaniu: 

`offers/listing?seller.id=00000000&category.id=00000&searchMode=CLOSED`

działał:          **&parameter.11323=2**

oraz żeby odpowiedź zawierała coś w rodzaju:      **<ns1:itEndingInfo> 2 </ns1:itEndingInfo>**  
z **doGetItemsInfoResponse**  w WebApi

**Comment by PrzemyslawLukanowski** [comment]
W powyższym zapytaniu jak najbardziej można dodać filtr "&parameter.11323=2". Nie zwracamy jednak informacji o stanie oferty (w rodzaju doGetItemsInfoResponse w WebApi) - zasób odzwierciedla wizualną wyszukiwarkę serwisu.

**Comment by crazyhtm** [comment]
Tak, dodać można tylko że nie działa. 

Zadaje w rzeczywistości poniższe zapytanie, które teoretycznie powinno zwrócić zakończone aukcje przedmiotów w "Stanie - Używane"  użytkownika 11753706 posortowane w/g daty zakończenia:

`https://api.allegro.pl/offers/listing?seller.id=11753706&category.id=77801&parameter.11323=2&searchMode=CLOSED&limit=100&sort=endTime&offset=0`

W odpowiedzi dostaję listę zakończonych aukcji.
W sekcji **filters** nie ma filtru **parameter.11323**  - "Stan"

Jeżeli przyjżymy się 2 pierwszym aukcjom z listy i wywołamy dla nich **DoGetItemsInfoRequest** z parametrem **getAttribs** to:
- pierwsza ma Stan - Używany
- druga ma Stan - Nowy

To znaczy że  **parameter.11323=2** nie działa bo wtedy nie byłoby w odpowiedzi aukcji przedmiotu oznaczonego jako Nowy

**Comment by PrzemyslawLukanowski** [comment]
W przypadku searchMode=CLOSED filtry są ograniczone, tak jak ma to miejsce na froncie, [przykład](https://allegro.pl/zakonczone/rowery-dzieciece-16481?string=rower&bmatch=baseline-var-n-dict4-eyesa-bp-spo-1-3-0619). Lista dostępnych filtrów zawsze znajduje się na końcu każdego wywołania.
