### ISSUE TITLE
Błąd przy procesie wystawiania aukcji

### ISSUE THREAD

**Issue by Nebuli1** [allegro/allegro-api#217]
Witam. Od kilku dni nagminnie otrzymuję błąd=Allegro internal system error (The request timed out). Jak znowu wystawiać chociażby 10000 aukcji na godzinę, bo w obecnym momencie przyjmujecie około 200 aukcji na godzinę poprawnie.

**Comment by LukaszKorek** [comment]
Podeślij nam request i response w formacie .xml  https://allegro.pl/pomoc/kontakt Potrzebujemy go do weryfikacji problemu.
