### ISSUE TITLE
'finishedAt'  is set to None when there is excess payment

### ISSUE THREAD

**Issue by hello76yu** [allegro/allegro-api#2171]
Got an order today and found the 'finishedAt' field in Payment form is None.
Maybe it caused by excess payment, client paid extra 0.01PLN .

Payment form ID  569cc3b2-c9a2-11e9-9047-93c5fc4d76c7

**Comment by PrzemyslawLukanowski** [comment]
Yes, you’re right, it’s a bug caused by excess payment. In the near future we will provide appropriate fix.
