### ISSUE TITLE
Sandbox nie działa

### ISSUE THREAD

**Issue by sikorag** [allegro/allegro-api#2173]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Pojawia się następujący komunikat:
Próba otwarcie strony została zablokowana
Aby chronić naszych użytkowników stosujemy aktywną ochronę przed złośliwym ruchem. Twoje zapytanie zostało zakwalifikowane jako jedno z nich. Jeśli uważasz inaczej, zgłoś ten przypadek obsłudze klienta załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego problemu.

Kod błędu
3e9ff30368feb5bc

Co jest przyczyną tego komunikatu? Kiedy będzie działać?

**Comment by PrzemyslawLukanowski** [comment]
Nie zauważyliśmy problemów z działaniem Sandboxa. Czy problem występuje na innej przeglądarce lub po wyczyszczeniu ciasteczek?

**Comment by sikorag** [comment]
Na innej przeglądarce też występuje ten problem - po próbie zalogowania.

Dziękuję za odpowiedź - wyczyszczenie ciasteczek w Chrome pomogło.

**Comment by sikorag** [comment]
Ale tylko na chwilę - po zalogowaniu ponownym i próbie przejścia na inna stronę problem się powtarza.

**Comment by PrzemyslawLukanowski** [comment]
Czy problem nadal występuje? Nie odnotowaliśmy innych zgłoszeń na ten temat. Jeśli problem nadal ma miejsce - mogę prosić o login w celu weryfikacji?

**Comment by sikorag** [comment]
Tak problem nadal występuje. Niezależnie czy loguję się z komputera czy telefonu.
Mój login: grzessik

**Po zalogowaniu** pojawia się komunikat jak w pierwszym poście. Dzisiejszy kod błędu:
c2770aff1f67c019

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu. Wrócę z odpowiedzią, jak tylko uda się coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
@sikorag Problem nie powinien już występować, prośba o weryfikację.

**Comment by sikorag** [comment]
Dziękuję za pomoc.

Rzeczywiście problem już nie występuje.
