### ISSUE TITLE
GET /offers/listing i jego możliwości ciąg dalszy

### ISSUE THREAD

**Issue by meblehaag** [allegro/allegro-api#2175]
Dzień dobry. Jako że byłem oderwany od komputera prze jakiś czas a wątek:
https://github.com/allegro/allegro-api/issues/379
się samoczynnie zamknął i dalej nie znalazłem rozwiązania piszę tu.

A więc po pobraniu w najlepszym wypadku mam taką tablicę:

            [entatablica] => Array
                (
                    [id] => 7660943194
                    [name] => BIURKO B005 LEO - kolor SONOMA Producent
                    [category] => Array
                        (
                            [id] => 20293
                        )

                    [primaryImage] => Array
                        (
                            [url] => https://4.allegroimg.com/original/03be6a/fe93facb42c3b9c4558eb5900dd4
                        )

                    [sellingMode] => Array
                        (
                            [format] => BUY_NOW
                            [price] => Array
                                (
                                    [amount] => 149.0
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => Array
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => Array
                        (
                            [watchersCount] => 2
                            [visitsCount] => 18
                        )

                    [stock] => Array
                        (
                            [available] => 10000
                            [sold] => 0
                        )

                    [publication] => Array
                        (
                            [status] => ACTIVE
                            [startingAt] => 
                            [startedAt] => 2018-11-08T11:42:05Z
                            [endingAt] => 
                            [endedAt] => 
                        )

                    [afterSalesServices] => Array
                        (
                            [warranty] => Array
                                (
                                    [id] => 0f8af247-a30c-4bfe-9e63-c6314220805e
                                )

                            [returnPolicy] => Array
                                (
                                    [id] => f0281dd6-6d43-4c6c-852f-00be98a14248
                                )

                            [impliedWarranty] => Array
                                (
                                    [id] => 34a51124-748e-46d4-8e57-cb17b2a1351b
                                )

                        )

                    [additionalServices] => 
                    [external] => 
                    [delivery] => Array
                        (
                            [shippingRates] => Array
                                (
                                    [id] => ba859156-7b44-4b52-87e4-bc83e52e4771
                                )

                        )

                )

Jak widać w delivery w najlepszym wypadku zwraca tylko shippingRates jeżeli ustawione jest dla aukcji ale nie ma tutaj żadnej mowy o czasie wysyłki czyli handlingTime rozumiem.
Czemu to tak? Druga sprawa w dokumentacji jest podany handlingTime jako PDT12H30M5S. To jakiś czas pacyficzny, o co w nim chodzi bo pierwszy raz coś takiego widzę. No i w końcu jak ustawić/zmienić czas wysyłki dla aukcji ?

**Comment by PrzemyslawLukanowski** [comment]
Proszę o doprecyzowanie - w tytule jest mowa o GET /offers/listing, tymczasem response dotyczy zasobu GET /sale/offers. Pola handlingTime nie zwracamy w żadnym z powyższych zasobów, ponieważ GET /offers/listing to odzwierciedlenie wizualnej wyszukiwarki serwisu, GET /sale/offers to odzwierciedlenie zakładki Moje oferty - nie ma tam informacji o czasie wysyłki.
Czas wysyłki można zmienić przez edycję pola handlingTime - w tym celu najpierw należy pobrać całą ofertę za pomocą zasobu GET /sale/offers/{offerId}, a następnie przesłać całą strukturę poprzez PUT /sale/offers/{offerId} ze zmienioną wartością pola handlingTime.
Przykłady, jakie wartości może przyjmować to pole, znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#new-offer).
