### ISSUE TITLE
webapi dla ups

### ISSUE THREAD

**Issue by e-biokominki** [allegro/allegro-api#2176]
próbuję uruchomić w allegro opcję dostawy " allegro odbiór w punkcie ups", zarejestrowałem konto na ups.com ale aby zsynchronizować muszę podać dane do konta w allegro, w tym webapi.
Na koncie allegro nie ma już możliwości generowania webapi, czy może tutaj otrzymam informacje skąd mam wziąć ?

**Comment by Radeq** [comment]
Klucz SOAP WebAPI jest widoczny w portalu deweloperskim Allegro na samym dole
https://apps.developer.allegro.pl/

**Comment by PrzemyslawLukanowski** [comment]
@e-biokominki  Na stronie https://apps.developer.allegro.pl/ wygenerujesz również nowy klucz pod REST API, stary klucz może już nie działać w niektórych integracjach.
