### ISSUE TITLE
Identyfikacja przedmiotów w kategorii motoryzacja z zastosowaniem w pojazdach

### ISSUE THREAD

**Issue by emteusz** [allegro/allegro-api#2178]
:bulb: **Sugestia**
Witam, czy macie może przewidziane rozwiązanie na "mnożenie" przez sprzedawców zastosowania w pojazdach danych części?
Mam na myśli Pana który wystawia sobie X aukcji i do każdej to samo zastosowanie (bo łatwiej, szybciej) co prowadzi, że w wynikach wyszukiwania przez użytkownika pojawia się częściej nietrafnie, jeśli nie, proponowałbym zastosować rozwiązanie poprzez odpytanie numerem identyfikacyjnym bazy oficjalnej tecdoc i porównanie z zastosowaniem w pojazdach (bo to ta sama lista), da to użytkownikom allegro równe szanse.

Dodatkowo- moglibyście pomyśleć, o zmianie nazw nadwozi - mam na myśli caravan - > kombi (kto w Polsce posiłkuje się taką nazwą nadwozia?)

**Comment by PrzemyslawLukanowski** [comment]
Dziękujemy za sugestię, ale z racji tego, że to sprzedawca odpowiada za prawdziwość danych, które przekazuje, nie planujemy wdrożenia takiej funkcjonalności.
Odnośnie nazw nadwozi - w reprezentacji tekstowej nie podajemy rodzaju nadwozia wprost, tecdoc dokleja czasem do modelu nadwozie, żeby zróżnicować modele, np. audi a4 b8  i audi a4 b8 avant w tym przypadku avant = kombi.

**Comment by emteusz** [comment]
ad. funkcjonalności: 
a co jeśli zrobi się nieładny bałagan jak sprzedawcy z ręki będą wprowadzać zastosowanie na wszystko jak leci? (1 filtr do wszystkich modeli danej marki)
upomnienia? ostrzeżenia? 
Tak czy tak ich aukcję będą mieli lepsza trafność (z tego co allegro informowało), co dla porównania sprzedawca który ma dobrze wprowadzone zastosowanie - dobrze sklasyfikowany towar wg. zastosowania może nie pokazać się w wynikach wyszukiwania

ad. nazw nadwozi - zdajecie sobie sprawę, że użytkownicy patrzący na zastosowanie, w większości przypadków nie mają pojęcia czym się poruszają, że ich nadwozie np. kombi to jest w Tecdocu caravan?
Tecdoc nie jest ogólnie łatwy dla zwykłego przykładowego Kowalskiego(a kategorie, których co prawda jeszcze nie macie, ale może to się zmienić to już w ogóle porażka),
 sądzę, że wiele kwestii jeszcze nie przemyśleliście do końca jak to działa.

**Comment by PrzemyslawLukanowski** [comment]
> ad. funkcjonalności:

Przekazałem taką sugestię do odpowiedniego zespołu. Jeśli w przyszłości zdecydujemy się na jej wdrożenie, poinformujemy o tym we właściwym komunikacie.

> “ad. nazw nadwozi”

Ze względu na połączenie z bazą tecdoc, na tę chwilę nie ma możliwości edycji tych wartości.

**Comment by emteusz** [comment]
Dziękuję za odpowiedź

**Comment by emteusz** [comment]
Widzę, że w kategorii hamulce wprowadziliście podczas wystawiania aukcji identyfikację części z tecdoc po wprowadzeniu numeru producenta, czy znamy datę kiedy tak się stanie z resztą asortymentu? Czy to będzie w tym roku jeszcze?

**Comment by PrzemyslawLukanowski** [comment]
@emteusz Do końca Q4 chcemy wprowadzić funkcjonalność do reszty asortymentu.
