### ISSUE TITLE
Kończenie aukcji nie działa zgodnie z opisem

### ISSUE THREAD

**Issue by soquel** [allegro/allegro-api#2179]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Po wystawieniu oferty, odczekaniu aż sie pojawi na stronie, robię następujący request:

```
Array
(
    [url] => https://api.allegro.pl/sale/offer-publication-commands/ec11e032-65b8-4043-a263-b9fe5b758c3d
    [method] => put
    [headers] => Array
        (
            [0] => Authorization: Bearer ...
            [1] => Accept: application/vnd.allegro.public.v1+json
            [2] => Content-Type: application/vnd.allegro.public.v1+json
        )
    [data] => {"publication":{"action":"END"},"offerCriteria":[{"offers":[{"id":"8460047561"}],"type":"CONTAINS_OFFERS"}]}
)
```

`trace-id: 4f6a16eb9141208b`

Dostaję konfudującą (ale z tego co zrozumiałem z innych bug-reportów o tym problemie), prawidłową odpowiedź z samymi zerami:

```
Array
(
    [id] => ec11e032-65b8-4043-a263-b9fe5b758c3d
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )
)
```

I nic się nie dzieje.
A przynajmniej nie to, czego bym oczekiwał. Oferta nie zostaje zakończona.

Tutaj zrobiłem dodatkowo requesty do `/sale/offer-publication-commands/`, tak jak piszecie gdzie indziej, ale to niewiele mówi i nie przybliża do rozwiązania problemu, bo wszystko wydaje się być ok.

```
Array
(
    [url] => https://api.allegro.pl/sale/offer-publication-commands/ec11e032-65b8-4043-a263-b9fe5b758c3d
    [method] => get
    [headers] => Array
        (
            [0] => Authorization: Bearer ...
            [1] => Accept: application/vnd.allegro.public.v1+json
            [2] => Content-Type: application/vnd.allegro.public.v1+json
        )
    [data] => []
)
```

`trace-id: 18bf3e9ac3d0cb9b`

Zwraca:

```
Array
(
    [id] => ec11e032-65b8-4043-a263-b9fe5b758c3d
    [taskCount] => Array
        (
            [total] => 1
            [success] => 1
            [failed] => 0
        )
)
```

Potem szczególowo do `tasks`:

```
Array
(
    [url] => https://api.allegro.pl/sale/offer-publication-commands/ec11e032-65b8-4043-a263-b9fe5b758c3d/tasks
    [method] => get
    [headers] => Array
        (
            [0] => Authorization: Bearer ...
            [1] => Accept: application/vnd.allegro.public.v1+json
            [2] => Content-Type: application/vnd.allegro.public.v1+json
        )
    [data] => []
)
```

`trace-id: 2a0018b3e4586488`

```
Array
(
    [tasks] => Array
        (
            [0] => Array
                (
                    [offer] => Array
                        (
                            [id] => 8460047561
                        )
                    [message] => 
                    [status] => SUCCESS
                    [scheduledAt] => 2019-09-04T21:52:30.109Z
                    [finishedAt] => 2019-09-04T21:52:31.696Z
                    [field] => publication
                    [errors] => Array
                        (
                        )
                )
        )
)
```

Tutaj nie rozumiem znaczenia odpowiedzi.
Jak ją interpretować?
Domyślam się, że jest SUCCESS w ofercie o danym ID jeżeli chodzi o pole `publication`, ale nie podajecie w odpowiedzi zawartości tego pola, więc nie wiem czy to SUCCESS tego wstępnego `ACTIVATE` czy tego `END`, o które mi chodzi.

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Dla aktywacji i zakończenia oferty użyłeś tego samego UUIDa - dlatego oferta się nie zakończyła, a task zwraca SUCCESS dla pierwszego wywołania, które dotyczyło aktywacji oferty. W celu poprawnego zakończenia oferty, użyj innego UUIDa.

**Comment by soquel** [comment]
Dziękuję, to rzeczywiście był ten problem i działa.
Szkoda, że dokumentacja jest w tej kwestii niejasna i sprowadziła mnie na manowce.
