### ISSUE TITLE
problem z edycją oferty

### ISSUE THREAD

**Issue by mzreczek** [allegro/allegro-api#218]
$dochangeitemfields_request = array(
		   'sessionId' => $session->sessionHandlePart,
		   'itemId' => $arraychange[$j],
		   'fieldsToModify' => array(
			  array(
				 'fid' => 341,
				 'fvalueString' => $jsontext,
				 'fvalueInt' => 0,
				 'fvalueFloat' => 0,
				 'fvalueImage' => 0,
				 'fvalueDatetime' => 0,
				 'fvalueDate' => '',
				 'fvalueRangeInt' => array(
						'fvalueRangeIntMin ' => 0,
						'fvalueRangeIntMax ' => 0),
				 'fvalueRangeFloat' => array(
						'fvalueRangeFloatMin ' => 0,
						'fvalueRangeFloatMax ' => 0),
				 'fvalueRangeDate' => array(
						'fvalueRangeDateMin ' => '',
						'fvalueRangeDateMax ' => ''))),
		   'fieldsToRemove' => array(),
		   'previewOnly' => 0,
		
		'variants' => array(
				  'fid' => 23604,
				  'quantities' => array(
						'mask' => 256,
						'quantity' => 5)),

						'tags' => array(
				  'tagName' => 'test'),
				  			'afterSalesServiceConditions'=> array (
				 'impliedWarranty' =>$impliedWarranty,
				 'returnPolicy' => $returnPolicy,
				 'warranty' => $warranty
			
			)
		);
$result=$soapClient->doChangeItemFields($dochangeitemfields_request);

i pojawia się błąd

SoapFault exception: [ERR_OBLIGATORY_ATTRIB_NOT_SET] Nie podano parametru wymaganego dla wybranej kategorii. (Okazja - fid: 4350) in C:\wamp6431\www\allegroAPI\source\xmltoarray3.php:194 Stack trace: #0 C:\wamp6431\www\allegroAPI\source\xmltoarray3.php(194): SoapClient->__call('doChangeItemFie...', Array) #1 {main}

Co cietawe nie mogę znaleźć fid 4350

**Comment by LukaszKorek** [comment]
Abym mógł w pełni zweryfikować zgłoszenie podaj proszę id kategorii w której edytujesz ofertę.
