### ISSUE TITLE
Automatyczne wznawianie oferty i wystawianie podobnej

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2180]
Sytuacja 1:
1. Wystawiam aukcję A z opcją "Wznawianie oferty (po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów)".
2. Aukcja A kończy się z powodu sprzedaży wszystkich przedmiotów.
3. Automatycznie wystawiona zostaje aukcja B, ponieważ było ustawione automatyczne wznawianie

Sytuacja 2:
1. Wystawiono aukcję A
2. Korzystając z opcji wystaw podobną wystawiamy aukcję C na podstawie A.

Pytanie: 
Czy dla aukcji B i C można przez REST API dowiedzieć się, jaka była aukcja A?

**Comment by PrzemyslawLukanowski** [comment]
Możesz w tym celu posłużyć się polem external.id. Najstarsza oferta z tą samą wartością dla tego pola będzie pierwszą wystawioną ofertą.
