### ISSUE TITLE
nie wyszukuje produktów po frazie

### ISSUE THREAD

**Issue by yphqn** [allegro/allegro-api#2181]
Witam,

Wysyłam zapytanie o listę produktów `GET /sale/products` i gdy używam kodu ean to zapytanie zwraca wynik poprawny, ale jak używam frazy to już nic nie ma.

Mam ofertę, która jest powiązana z produktem [oferta](https://allegro.pl.allegrosandbox.pl/oferta/test-produkt-ksiazka-2-6206550144)

w parametrze phrase wpisuje "tytus internauta" i nic mi nie znajduje.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - również nie otrzymałem wyników przy użycia filtru phrase. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by TomekDuszynski** [comment]
@PrzemyslawLukanowski znasz przybliżony termin rozwiązania tego problemu?

**Comment by PrzemyslawLukanowski** [comment]
@TomekDuszynski Udało się wyeliminować problem. Wyszukiwanie po frazie działa już prawidłowo.
