### ISSUE TITLE
Brak parametru

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2182]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dla kategorii 257628 brakuje parametru "Kod producenta"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje za informację, zweryfikowałem to - na sandboxie brakuje takiego parametru. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@martacronic Dodaliśmy brakujący parametr.

**Comment by martacronic** [comment]
Dzięki
