### ISSUE TITLE
WebAPI sandbox - brak informacji o płatności w dzienniku zdarzeń

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2183]
Występuje problem: 
 - [x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Na sandboxie zrobiłem dzisiaj zamówienie koszykowe, produkty od 2 sprzedawców. Opłaciłem przez PayU (sandobox, w zeszłym miesiącu była inna strona do testowych płatności). W dzienniku zdarzeń Allegro nie widzę zdarzenia płatności (dealEventType=4), są tylko 1 i 2. Na stronie sandboxa ( Moje zakupy ) płatność "zakończona".

transactionId: 727966618
dealId: 1402094465,1402094464

**Comment by PrzemyslawLukanowski** [comment]
Czy mogę prosić o login, który dotyczy zgłoszenia? Pomoże nam to szybciej zweryfikować problem.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski magik092

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - doGetSiteJournalDeals nie zwraca wszystkich danych. Zgłosiłem ten problem do odpowiedniego zespołu.
