### ISSUE TITLE
Niemożliwośc wznowienia aukcji

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2184]
Nie potrafię wznowić przez API aukcji 8294168599.

Dostaję cały czas bład:

```
  array(1) {
    [0]=>
    object(stdClass)#72 (5) {
      ["code"]=>
      string(16) "VALIDATION_ERROR"
      ["message"]=>
      string(25) "ERR_ITEM_CAN_NOT_BE_RENEW"
      ["details"]=>
      string(0) ""
      ["path"]=>
      string(0) ""
      ["userMessage"]=>
      string(0) ""
    }
  }
```

Logowałem się do panelu Allegro i próbowałem aukcje wznowić ręcznie, lecz też bład:

```
Podczas wznowienia oferty wystąpiły błędy
Oferta nie może zostać wznowiona, ponieważ jest w trakcie kończenia. Poczekaj chwilę i spróbuj ponownie.
```

Aukcja zakończyła się około 2019-09-05 07:04:39.

Ostatnia sprzedaż była 2019-09-05 01:03:47.

Identyczny problem mam z aukcja:  8250613873

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski czy problem został rozwiązany? Od paru dni klient próbuje wznowić i ma błąd:
`An error occurred while trying to change the publication of the offer. Please try again later. `

`commandId 2e3a22f0-5607-4a71-b217-d69354733149`

```
"GET sale/offer-publication-commands/2e3a22f0-5607-4a71-b217-d69354733149/tasks"
trace-id: 4ff7d98ef447da82
```

```
  #container: array:6 [
    "field" => "publication"
    "finished_at" => DateTime {#1859
      +"date": "2019-09-09 06:16:14.253000"
      +"timezone_type": 2
      +"timezone": "Z"
    }
    "message" => "An error occurred while trying to change the publication of the offer. Please try again later."
    "offer" => ***
    "scheduled_at" => DateTime {#1861
      +"date": "2019-09-09 06:15:57.951000"
      +"timezone_type": 2
      +"timezone": "Z"
    }
    "status" => "FAIL"
  ]
}
```

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Powyższe oferty zostały poprawione. Twój przypadek dodaję do nowego zgłoszenia.

**Comment by pkrzemo** [comment]
Mam obejście tego problemu - może u was też zadziała...
Trzeba poprzez edycję grupową zwiększyć ilość, a następnie także przez edycję grupową wznowić..
U mnie zadziałało (ale może to był inny przypadek).
;-)
