### ISSUE TITLE
Jak pobrać wszystkie checkout-forms dla wskazanej oferty

### ISSUE THREAD

**Issue by Lucjan540** [allegro/allegro-api#2186]
Jak pobrać checkout-forms dla wskazanej aukcji. 
Iterowanie po wszystkich metodą https://api.allegro.pl/order/checkout-forms/?limit =100&offset =0
i filtrowanie po mojej stronie nie wchodzi w grę gdyż klient ma 500 zamówień dziennie. Czasem istnieje konieczność szybkiego pobrania zamówień dla jednej aukcji. 

W WEB API korzystałem z metody doGetTransactionsIDs do pobrania transakcji następnie doGetPostBuyFormsDataForSellers

**Comment by PrzemyslawLukanowski** [comment]
Możesz w tym celu wykorzystać:

- dziennik zdarzeń [GET /sale/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) z parametrami limit=1000&type=READY_FOR_PROCESSING

- [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) z wykorzystaniem filtrów lineItems.boughtAt.lte i lineItems.boughtAt.gte

- Odwzorowując ścieżkę z WebAPI - skorzystaj z zasobu [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory), znając login kupującego przekaż go jako wartość parametru participant.login. W odpowiedzi otrzymasz payment.id, które dalej możesz przekazać jako parametr w GET /order/checkout-forms/

Więcej informacji znajdziesz w [naszym poradniku dot. obsługi zamówień.](https://developer.allegro.pl/orders/#01)

**Comment by PrzemyslawLukanowski** [comment]
update - możesz to także skorzystać z [mapowania płatności](https://github.com/allegro/allegro-api/issues/1878), jeśli dysponujesz transactionId. Otrzymany payment.id przekaż w GET /order/checkout-forms?{payment.id}, w odpowiedzi uzyskasz checkout-form dla wskazanej oferty.

**Comment by Lucjan540** [comment]
Nie dysponuję takimi danymi. Mam jedynie nr aukcji, do którego chciał bym pobrać wszystkie zamówienie. Jak osiągnąć taki efekt?

**Comment by kfijalko** [comment]
Żaby pobrać komplet zamówień nie powinieneś wychodzić od listy ofert, tylko pobierać wszystkie i ewentualnie u siebie w bazie łączyć z ofertami. Oczywiście mowa o koncie, do którego masz dostęp, nie o transakcjach z "kont obcych".

**Comment by Lucjan540** [comment]
Wiem jak pobrać wszystkie zamówień mam już to w pełni obsłużone. 
Jednak w starej funkcjonalności mam możliwość pobrania zamówień do wskazanej aukcji. 
W systemie ERP mam tylko nr aukcji. W Web API byłem w stanie to obsłużyć. 

Chcę uniknąć pobieranie  np. wszystkich zamówień z 3 dni i filtrowania po swojej stronie.

**Comment by PrzemyslawLukanowski** [comment]
@Lucjan540  W REST API nie możesz przekazać offer.id jako query parameter w celu uzyskania powiązanych z ofertą zamówień.

**Comment by kfijalko** [comment]
Jasne. To niestety ja nie znam takiej możliwości.

**Comment by kfijalko** [comment]
Musze napisać: odpytywanie po id oferty było by bardzo nieefetywne. Lepiej odpytać o transakcje za "ostatni" okres i na podstawie offer.id/external.id przypisać do towarów w ERP.
(Poza przypadkiem kiedy wszystkie oferty sprzedają.)

**Comment by Lucjan540** [comment]
Niestety system jest już tak lata napisany i muszę się do tego dostosować. 
W starym web api dało się przez do tego dostać  doGetTransactionsIDs do pobrania transakcji następnie doGetPostBuyFormsDataForSellers. Jeśli ono jest w trakcie wygaszania funkcjonalność powinna być w jakiś sposób przeniesiona.

**Comment by kfijalko** [comment]
Na przeniesienie 1=1 nie ma co liczyć. Ja od roku przepisuje swój system pod rest'a i nawet to co wdrożyłem jakiś czas temu muszę modyfikować. Nie mówiąc o tym, że czeka mnie "starcie" z produktyzacją - pewnie jeszcze w tym roku.
