### ISSUE TITLE
przekazywanie numeru przesyłki REST API

### ISSUE THREAD

**Issue by vbdbsoft** [allegro/allegro-api#2187]
Mam obecnie 2 osobne rozwiązania obsługujące zamówienia importowane z pliku XML z Menedżera Sprzedaży, a drugie korzystające z WebApi.
Jakich metod użyć w każdym z tych wypadków, aby wykorzystać dostępne dane zwracane odpowiednio w XMLu i przez WebApi, aby uzyskać parametry potrzebne do przekazania zamówienia. W okresie przejściowym (szczególnie dla WebApi) chciałbym uniknąć pobierania pełnych informacji o zamówieniach, jak zostało to opisane w poradniku https://developer.allegro.pl/orders/
Zazwyczaj zamówienia realizowane w 99% w całości jedną przesyłką.

**Comment by PrzemyslawLukanowski** [comment]
Aby dodać numer przesyłki w REST API skorzystaj z zasobu [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST). Wymagane parametry to id zamówienia, który przekazujesz w query parametrze, w body wymagane jest carrierId (nazwa przewoźnika), waybill (numer przesyłki), lineItems.id (id przedmiotu z zamówienia).

Bardziej szczegółowo ten proces może wyglądać następująco:
- otrzymane dane z WebAPI, czyli w tym przypadku transactionId mapujesz za pomocą zasobu [GET order/line-item-id-mappings?{transactionId](https://developer.allegro.pl/documentation/#operation/findMapping)},
- w odpowiedzi otrzymasz payment.id, który przekażesz w zasobie [GET order/checkout-forms/payment.id={payment.id}](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)
- w ten sposób otrzymasz checkoutForm.id, które należy przekazać w query parametrze [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) oraz lineItem.id, które przekazujesz w body tego requestu.

**Comment by vbdbsoft** [comment]
A jak to będzie wyglądało dla danych z menedzera sprzedaży? Tam jest pole Id
<transaction>
<parentId/>
<Id>45149675</Id> 
Ono jest tożsame z transactionId z WebApi?

**Comment by PrzemyslawLukanowski** [comment]
Te dane nie są tożsame z transactionId z WebAPI. Nie da się wykorzystać danych zwracanych przez MS w REST API, nie są ze sobą w żaden sposób powiązane.

**Comment by vbdbsoft** [comment]
Nie da się jakoś sparować po adresie email? np. e7j1h31dp4+7c7e44841@allegromail.pl
Przecież on z Waszej strony identyfikuje konkretnego klienta i konkretną transakcję ;-)

**Comment by PrzemyslawLukanowski** [comment]
Proponowałbym poniższe rozwiązanie:

- login kupującego przekaż jako wartość parametru participant.login, dodatkowo przekaż także datę wpłaty kupującego dla parametrów occurredAt.gte i occurredAt.lte w zasobie [GET /payments/payment-operations, ](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory)
- w odpowiedzi pojawi się wpłata dopasowana do filtrów z wcześniejszego wywołania, która zawiera payment.id powiązane z konkretnym zamówieniem,
- dalej analogicznie do 2 i 3 punktu z mojej poprzedniej wiadomości.

**Comment by vbdbsoft** [comment]
To na pewno jakieś rozwiązanie, aczkolwiek nie wiem czy będzie w pełni skuteczne. MS zwraca tylko datę złożenia zamówienia i niekoniecznie płatność musi być tego samego dnia (nie wiem jak płatności będą widoczne w przypadku przesyłki z pobraniem).

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, powyższe rozwiązanie nie sprawdzi się, kiedy data zamówienia i data wpłaty są różne oraz w przypadku zamówień pobraniowych. Na tę chwilę nie ma sposobu na powiązanie danych, które są zwracane przez MS, z dodaniem numeru przesyłki w REST API. Sugestia dotycząca sparowania po adresie email niestety nie jest możliwa, ponieważ ta wartość nie może być przekazana w żadnym zasobie jako parametr.
MS był tworzony z założeniem, że nie jest to narzędzie, które będzie równolegle wykorzystywane z API Allegro. Lepiej sprawdzić dane, które zwracamy w zakładce Zamówienia w Moim Allegro - te dane są spójne z tymi, które zwraca API Allegro.
