### ISSUE TITLE
Ten sam produkt, różne EANy - nie można wystawić oferty przez REST API

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#2188]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję wystawić produkt z kodem EAN: 3760168591716 i mam błąd:
Missing parameter Kod producenta (224017) with value: "3760168000003" for offer with product. Provided EAN 3760168591716 is not equal with any EAN assigned to the product. Missing parameter Pojemność opakowania (219893) with value: "100" for offer with product.
Dodam, że metoda GET sale/products nie znajduje produktu po kodzie 3760168591716 - a taki właśnie produkt posiadam. Ofertę wystawiam bez id produktu.

**Comment by kfijalko** [comment]
Wygląda na to, że allegro z eanu odczytuje kod producenta i potem go wymaga. Jeżeli tak to go wyświetlcie użytkownikowi żeby wiedział czy macie rację ;)
Poniżej link do budowy eanów:
https://www.gs1pl.org/globalny-numer-jednostki-handlowej
Zgodnie z ich definicją (jedyną słuszną) kod producenta może mieć od 4 do 8 znaków.
Tylko pytanie zasadnicze, na które ta strona nie odpowiada:
Czy jeżeli istnieje producent z kodem (376 - kod kraju): 0168 to oznacza, że nie może istnieć producent:01685 lub 016859 ...
Przepraszam za wtrącenie ale chciałbym przy okazji się tego dowiedzieć.

**Comment by mareklemur** [comment]
Ja chcę tylko wystawić produkt z kodem 3760168591716 i w tej chwili to jest niemożliwe. Obejściem jest niepodawanie kodu EAN, ale chyba nie o to chodzi.

**Comment by kfijalko** [comment]
Pewnie, że nie. Poczekajmy na odpowiedź allegro.

**Comment by mareklemur** [comment]
Zamykam, to błąd w moim oprogramowaniu. Zmienił się EAN produktu, ale wystawia ofertę ze starym.
