### ISSUE TITLE
Nie mogę pobrać podkategori dla kategori Moda 

### ISSUE THREAD

**Issue by szokart** [allegro/allegro-api#2189]
Pobieram drzew kategorii poprzez  `sale/categories?parent.id='.$category`
i ogólnie działa ale mam problem z pobraniem podkategorii dla kategorii 
Moda (ea5b98dd-4b6f-4bd0-8c80-22c2629132d0) i
Kolekcja i Sztuka (a408e75a-cede-4587-8526-54e9be600d9f)
Pozostałe pobiera prawidłowo jak też niższego rzędu.

**Comment by kfijalko** [comment]
Odpytałem właśnie w postmanie:
https://api.allegro.pl/sale/categories/?parent.id=ea5b98dd-4b6f-4bd0-8c80-22c2629132d0

`{
    "categories": [
        {
            "id": "19732",
            "name": "Biżuteria i Zegarki",
            "parent": {
                "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0"
            },
            "leaf": false,
            "options": {
                "variantsByColorPatternAllowed": true,
                "advertisement": false,
                "advertisementPriceOptional": false,
                "offersWithProductPublicationEnabled": false,
                "productCreationEnabled": false,
                "productEANRequired": false
            }
        },
        {
            "id": "1454",
            "name": "Odzież, Obuwie, Dodatki",
            "parent": {
                "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0"
            },
            "leaf": false,
            "options": {
                "variantsByColorPatternAllowed": true,
                "advertisement": false,
                "advertisementPriceOptional": false,
                "offersWithProductPublicationEnabled": false,
                "productCreationEnabled": false,
                "productEANRequired": false
            }
        }
    ]
}`
Następnie "odziez obuwie"
https://api.allegro.pl/sale/categories/?parent.id=1454
też prawidłowy wynik.
Teraz "sztuka":
https://api.allegro.pl/sale/categories/?parent.id=a408e75a-cede-4587-8526-54e9be600d9f
też prawidłowy wynika (zgodny z tym co pokazuje allegro.pl).
napisz na czym polega problem, jakiś błąd/pusta odpowiedź ...
No i polecam Postmana, zawsze możesz w niezaleznym oprogramowaniu sprawdzić co allegro odpowiada.

**Comment by szokart** [comment]
Znalazłem problem w skrypcie
wartości ea5b98dd-4b6f-4bd0-8c80-22c2629132d0 i a408e75a-cede-4587-8526-54e9be600d9f
zwracały true dla zapytania
`if( $category == 0 ){`
poprawiłem na `if( $category == '0' ){` i działa prawidłowo

można zamknąć
