### ISSUE TITLE
doGetItemsList - Wyświetlanie wszystkich zakończonych aukcji z danej kategorii

### ISSUE THREAD

**Issue by Snajper315** [allegro/allegro-api#219]
Czy jest taka możliwość? 
Bo filtr closed wymaga podania kolejnego - search

**Comment by aktywnitu** [comment]
A czy istnieje możliwość pobrania zakończonych ofert użytkownika przy użyciu np. doGetItemsList?

**Comment by LukaszKorek** [comment]
Nie,  nie udostępniamy takiego zasobu.
