### ISSUE TITLE
Payment type dla pobrania

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#2190]
Czołem,
wdrażam zaciąganie zamówień po API i mam następujący problem, wartość [payment][type] może przybrać wartość ONLINE lub CASH_ON_DELIVERY. O ile rozumiem, online to PayU i P24, natomiast dostaje taką wartość przy zamówieniu za pobraniem? Przecież to nie ma nic wspólnego z płatnością online.

Fragment odpowiedzi:

` [payment] => Array
        (
            [id] => 2bd9dc42-cfe1-11e9-8f7f-779b5806c9d8
            [type] => ONLINE
            [provider] => 
            [finishedAt] => 2019-09-05T13:29:25.538Z
            [paidAmount] => 
        )
    [status] => READY_FOR_PROCESSING
    [delivery] => Array
        (
            [address] => Array
                (
                    [firstName] => Imię
                    [lastName] => Nazwisko
                    [street] =>Adres
                    [city] => Kraków
                    [zipCode] => Kod
                    [countryCode] => PL
                    [companyName] => 
                    [phoneNumber] => 123123123
                )

            [method] => Array
                (
                    [id] => 845efe05-0c96-47c3-a8cb-aa4699c158ce
                    [name] => Przesyłka kurierska pobranie
                )

            [pickupPoint] => 
            [cost] => Array
                (
                    [amount] => 22.00
                    [currency] => PLN
                )

            [smart] => 
            [time] => Array
                (
                    [guaranteed] => 
                )

        )`

**Comment by PawelTaberski** [comment]
Czy mogę prosić o trace id tego wywołania? W jakim środowisku występuje ten problem? Nie udało mi się go powtórzyć ani na produkcji, ani na sandboxie. W przypadku płatności przy odbiorze, otrzymuję typ płatności CASH_ON_DELIVERY.
