### ISSUE TITLE
Uzupełnij parametry obowiązkowe: Tytuł.

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#2191]
Problem występuje przy wystawianiu każdej aukcji (aukcje są odrzucane przez allegro) nie zależnie co wpiszemy w tytule. Wczoraj wszystko funkcjonowała prawidłowo i środowisko od tego czasu nie było zmieniane.

Co wysyłamy:
*********

Otrzymujemy:
*********

Parametr tytuł jest oczywiście uzupełniany poprawnie, ilość znaków nie ma znaczenia.

`{"errors":[{"code":"VALIDATION_ERROR","message":"Uzupełnij parametry obowiązkowe: Tytuł.","details":"","path":"","userMessage":"Uzupełnij parametry obowiązkowe: Tytuł."}]`

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nie chodzi o tytuł oferty, ale o tytuł jako parametr (id 234925) w tej kategorii - brakuje go w requescie:
![Screenshot_8](https://user-images.githubusercontent.com/51473661/64429541-8bd30b00-d0b6-11e9-8c36-9eb38f97ac2d.png)

**Comment by unkn0wn0** [comment]
Co oznacza ten parametr? Czy jest gdzieś lista wszystkim parametrów w takim razie?

Jaka to kategoria z parametrem tytuł?

**Comment by PrzemyslawLukanowski** [comment]
Parametr tytuł odnosi się tylko tytułu książki, tymczasem w tytule oferty mogą pojawić się inne, nadmiarowe dane. Dzięki temu parametrowi dużo łatwiejsze będzie automatyczne powiązanie oferty z produktem.
