### ISSUE TITLE
dealIId większy niż 2147483647

### ISSUE THREAD

**Issue by mateuszp449** [allegro/allegro-api#2192]
Witam,
W WebApi jest poważny błąd (no chyba że to ja coś robię źle)

Mianowicie chodzi o to, że, do funkcji takich jak: 
doGetRefundsReasons, 
doSendRefundForm

trzeba przekazać dealId. dealId jest typu xs:int, czyli liczba z przedziału -2147483648 do 2147483647.

A co jeżeli chcemy wystąpić o zwrot prowizji dla dealId np. 2148922201 ?
Otrzymujemy błąd:
Element '{https://webapi.allegro.pl/service.php}dealId': '2148922201' is not a valid value of the atomic type 'xs:int'.

Ponieważ liczba 2148922201 jest za duża żeby zapisać ją jako XS:INT

**Comment by esprzedaz** [comment]
Tak jest, mamy to samo.

**Comment by PhotoSoft** [comment]
Ja już im to zgłaszałem w kwietniu 2016r. (!) i odpisali, że to poprawią. Właśnie widać...

**Comment by PrzemyslawLukanowski** [comment]
Dziękujemy za informację, zgłosiłem problem do odpowiedniego zespołu.

**Comment by TomekKaczmarek** [comment]
#2209 Wdożyliśmy poprawkę
