### ISSUE TITLE
Brak refresh token w respons.

### ISSUE THREAD

**Issue by MBorasinski** [allegro/allegro-api#2193]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,
podczas wywołania requestu do autoryzacji nie otrzymujemy refresh token w response.
Proszę zobaczyć screenshot.

![Token](https://user-images.githubusercontent.com/48054615/64511629-01242300-d2e5-11e9-89b2-8b68b24e7c7c.jpg)

Proszę o pomoc.

**Comment by TomekKaczmarek** [comment]
Dla typu autoryzacji client_credentials nie zwracamy refresh tokena - nie jest on potrzebny, kolejny token można bez problemu wygenerować bez angażowania użytkownika aplikacji.
