### ISSUE TITLE
Aktywacja konta w Sandbox korzystając z Payment Simulator

### ISSUE THREAD

**Issue by browin-pziemba** [allegro/allegro-api#2194]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Aktywacja konta poprzez Payment Simylator nie działa. Proszę o aktywacje konta x(dot)x(at)x(dot)x

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem konto.

**Comment by Sharhin** [comment]
Witam
Proszę o aktywację sprzedaży na koncie: G5rsI1IZ
Pozdrawiam

**Comment by browin-pziemba** [comment]
Nadal trwa weryfikacja danych na moim koncie pomimo uzupełnienia danych firmowych.

**Comment by PrzemyslawLukanowski** [comment]
@Sharhin Wstępnie aktywowałem konto. Musisz jeszcze przesłać dwa dowolne pliki przez zakładkę Moje konto -> Dane konta.
@browin-pziemba Czy przesłałeś dwa dowolne pliki przez zakładkę Moje konto -> Dane konta?

**Comment by browin-pziemba** [comment]
tak, dodałem dwa pliki

**Comment by PrzemyslawLukanowski** [comment]
@browin-pziemba  prośba o wysłanie dwóch dowolnych plików jeszcze raz, następnie potwierdzenie przyciskiem "wyślij do weryfikacji". Czy po wysłaniu otrzymałeś odpowiedni komunikat?

**Comment by browin-pziemba** [comment]
Wysłałem kilkukrotnie uzupełniony formularz, załączając dwa dowolne pliki. Po wysłaniu danych przenosi mnie na stronę główną bez żadnego komunikatu.

**Comment by PrzemyslawLukanowski** [comment]
Proszę spróbować zmienić rodzaj przedsiębiorstwa w zakładce dane konta i wtedy przesłać dwa dowolne pliki. Po prawidłowym wysłaniu plików do weryfikacji powinien pojawić się odpowiedni komunikat. Problem z przenoszeniem na stronę główną zgłosiłem już do odpowiedniego zespołu.

**Comment by browin-pziemba** [comment]
Pojawił się komunikat "Dane przedsiębiorstwa na koncie Allegro zostały wyedytowane. Zmiana musi jeszcze zostać zatwierdzona przez pracownika Allegro.
O wyniku weryfikacji powiadomimy Cię e-mailem."

**Comment by PrzemyslawLukanowski** [comment]
Konto jest już aktywne.

**Comment by browin-pziemba** [comment]
w zakładce "Aktywacja konta" w polu "Status konta" nadal mam wartość "Nieaktywne - trwa weryfikacja Twoich danych", chociaż dodane zostały dwie zakładki "Apteka" i "Wina", korzystając z REST API nadal pojawia się odpowiedź 401 z zawartością 
`{'error': 'unauthorized', 'error_description': 'Full authentication is required to access this resource'}`

**Comment by PrzemyslawLukanowski** [comment]
Rozkoduj swój token (wszystkie tokeny są w technologii JWT) i zweryfikuj, czy jest przypisany do prawidłowego usera. Przy odpytywaniu jakiego zasobu otrzymujesz powyższy komunikat? Czy korzystasz z typu autoryzacji [code flow ](https://developer.allegro.pl/auth/#app)lub [device flow](https://developer.allegro.pl/auth/#DeviceFlow)? Autoryzacja typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow) służy tylko do zasobów publicznych.

**Comment by browin-pziemba** [comment]
nadal nie mam aktywnego konta, w zakładce "Aktywacja konta" widnieje komunikat: "Nieaktywne - trwa weryfikacja Twoich danych." ale pojawiły się za to dwie nowe zakładki: apteka i wina.

**Comment by PrzemyslawLukanowski** [comment]
Konto jest aktywne, można to zweryfikować przez wystawienie oferty na froncie. Proszę nie sugerować się komunikatem - w środowisku testowym może wystąpić taka rozbieżność. Jeżeli przy korzystaniu przez REST API nadal pojawia się błąd 401, proszę sprawdzić wskazówki, o których pisałem powyżej.
