### ISSUE TITLE
Pytanie o /payments/payment-id-mappings

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#2195]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

GET https://api.allegro.pl/payments/payment-id-mappings?paymentId=53f8aba0-c1e8-11e9-b9f8-9de33fba060a` resulted in a `404 Not Found` response: {"message":"Transaction not found for paymentId=53f8aba0-c1e8-11e9-b9f8-9de33fba060a"}

Witam, z czego wynika, że przy powyższym zapytaniu otrzymuję błąd? Podany paymentId otrzymałem z metody /order/checkout-forms Błąd pojawia się dla niektórych id zwróconych przy zastosowaniu filtru  FILLDED_IN. Na 90 zwróconych rekordów, błąd jest przy 38.
Dla READY_FOR_PROCESSING  nigdy nie miałem tego błędu.

**Comment by TomekKaczmarek** [comment]
@copyact jesteś pewien, że podajesz poprawny i istniejący w Allegro paymentId? Jesli tak - podaj proszę dla jakiego zamówienia i dla jakiej oferty go otrzymujesz. Sprawdzimy temat.

**Comment by copyact** [comment]
No taki mi zwraca inna metoda. 
[id] => 77c97113-c1e6-11e9-89f3-b9f509068d64
                [payment] => Array
                        (
                            [id] => 53f8aba0-c1e8-11e9-b9f8-9de33fba060a
                            [type] => ONLINE
                            [provider] => P24
                            [finishedAt] => 2019-08-18T18:53:19.758Z
                            [paidAmount] => 

                    [lineItems] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 77c97103-c1e6-11e9-89f3-b9f509068d64
                                    [offer] => Array
                                        (
                                            [id] => 6913007816
                                            [name] => HALLI GALLI Gra towarzyska Rodzinna Imprezowa BASA
                                            [external] => 
                                        )

                                    [quantity] => 1
                                    [originalPrice] => Array
                                        (
                                            [amount] => 40.00
                                            [currency] => PLN
                                        )

                                    [price] => Array
                                        (
                                            [amount] => 40.00
                                            [currency] => PLN
                                        )

                                    [selectedAdditionalServices] => Array
                                        (
                                        )

                                    [boughtAt] => 2019-08-18T18:33:57.096Z
                                )

                        )

**Comment by TomekKaczmarek** [comment]
Dzięki, podaj proszę inne przykłady numerów płatności, dla których otrzymujesz komunikat błędu.

**Comment by copyact** [comment]
c84c8fd2-c30e-11e9-8fa0-89c3e582ad74
53f8aba0-c1e8-11e9-b9f8-9de33fba060a
5e4f8812-8945-11e9-b114-51314551a7e6
b65bd712-87c5-11e9-937b-edfc16c2f4f1
991d4b82-7c07-11e9-976b-e50772f05eb0
f9b90df2-733b-11e9-8675-e5f0fac750d8
7fc43b82-701d-11e9-9c74-b708d7fbaddd
0c609624-6f64-11e9-815b-57f7b6f96988
cfe0f303-6c45-11e9-b828-abdff7024bea
c188d8d2-69bc-11e9-b828-abdff7024bea
95f9c982-66c0-11e9-90ed-05812bf67454
6afd6634-6425-11e9-9c74-b708d7fbaddd
8a35a932-61dd-11e9-94c4-af485c4ce24d
b7600961-60f1-11e9-9816-c5b3f6387ee2
f7f02df3-60e9-11e9-94c4-af485c4ce24d
30243833-60e8-11e9-8963-8168854be7ee
100ef9a2-5f75-11e9-b3f2-e150425d33b7
9922aaa2-5563-11e9-9165-d1255de2deaa
14fae082-4bf4-11e9-be86-63e00691e3ff
cef87522-4761-11e9-9a00-3556116b359f
4ee5e032-44b8-11e9-be86-63e00691e3ff
f5149562-43d6-11e9-b122-894fd013869d
ca74e092-4376-11e9-9a00-3556116b359f
62f96fc2-40c5-11e9-b1c6-e18816592582
77646d34-3e8a-11e9-a094-9df4ec8c2d46
4bb38522-39b9-11e9-81d1-c7d7b7f7467f
45099b02-3938-11e9-81d1-c7d7b7f7467f
a11162b2-3849-11e9-a956-8df916ed63db

**Comment by copyact** [comment]
Czy coś ustaliliście?
