### ISSUE TITLE
Nieprawidłowa informacja o najwyższej ofercie w licytacji

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2197]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Czy pole offers -> saleInfo -> currentPrice na pewno działa w prawidłowy sposób ? Wg informacji z dokumentacji pole to powinno zawierać wartość "The current highest bid in auction format.". Tymczasem zawiera ona wartość początkową. Przykładowa aukcja z tym problemem:
https://allegro.pl.allegrosandbox.pl/oferta/licytacja-z-cena-wywolawcza-minimalna-i-kup-teraz-6206561598

W polu currentPrice -> amount powinna być wartość 125.50

```
-------------------------------------
REQUEST:

GET /sale/offers?offer.id=6206561598 HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.0.0
Authorization: Bearer (...ciach...)
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

-------------------------------------
RESPONSE:

HTTP/1.1 200 OK
Server: envoy
Trace-id: 3710e1e28436ddd3
Content-type: application/vnd.allegro.public.v1+json
Content-length: 890
Date: Mon, 09 Sep 2019 09:50:44 GMT
X-envoy-upstream-service-time: 185
Connection: close

{"offers":[{"id":"6206561598","name":"licytacja z ceną wywoławczą, minimalną i kup teraz","category":{"id":"111852"},"primaryImage":{"url":"https://a.allegroimg.allegrosandbox.pl/original/036e33/0226b45449cbbb0f85b283c6d48c"},"sellingMode":{"format":"AUCTION","price":{"amount":"125.0","currency":"PLN"},"minimalPrice":{"amount":"123.0","currency":"PLN"},"startingPrice":{"amount":"12.0","currency":"PLN"}},"saleInfo":{"currentPrice":{"amount":"123.0","currency":"PLN"},"biddersCount":2},"stats":{"watchersCount":0,"visitsCount":0},"stock":{"available":1,"sold":0},"publication":{"status":"ACTIVE","startingAt":null,"startedAt":"2019-09-06T11:11:29Z","endingAt":"2019-09-09T11:11:29Z","endedAt":null},"afterSalesServices":{"warranty":null,"returnPolicy":null,"impliedWarranty":null},"additionalServices":null,"external":null,"delivery":{"shippingRates":null}}],"count":1,"totalCount":1}
```

**Comment by TomekKaczmarek** [comment]
Z tego co widzę, dane zwracamy poprawnie - aktualna cena wynosi 123,00:
https://allegro.pl.allegrosandbox.pl/oferta/licytacja-z-cena-wywolawcza-minimalna-i-kup-teraz-6206561598

i taką informacje przekazuje w currentPrice:
`		"saleInfo": {
			"currentPrice": {
				"amount": "123.0",
				"currency": "PLN"
			},
			"biddersCount": 2
		},`

**Comment by kormichu** [comment]
Nie jest prawidłowa bo licytowałem po 125.50 co widać na poniższym screenie:
https://imgur.com/a/bim5lvb

**Comment by TomekKaczmarek** [comment]
125.50 to propozycja kolejnego bida, który byłby aktywny, gdyby oferta była aktywna. 
Ostatni bid jest za 123.00 (z 9 września 2019 10:37:20.389 CEST)
