### ISSUE TITLE
sandbox

### ISSUE THREAD

**Issue by KonSla** [allegro/allegro-api#2198]
Proszę o aktywacje konta konrad(dot)slapek(at)philips(dot)pl
Standardowy proces z symulacją płatności nie działa

**Comment by TomekKaczmarek** [comment]
@KonSla sprawdziłem i symulator płatności działa. Nie mogę znaleźć konta zarejestrowanego na podany adres email. Spróbuj założyć konto jeszcze raz.

**Comment by KonSla** [comment]
Niestety nie mogę założyć kolejnego konta na ten sam adres mailowy, otrzymuję komunikat, że posiadam już konto w systemie.
Symulator płatności działa, ale konto przeszło w tryb weryfikacji zgłoszenia, która trwa już od kilku tygodni.

**Comment by TomekKaczmarek** [comment]
Przed chwilą udało mi się założyć konto na ten adres email. Proszę dokończyć aktywację i zmienić hasło.

**Comment by KonSla** [comment]
Mój błąd - adres jest w domenie .com
konrad(dot)slapek(at)philips(dot)com

**Comment by TomekKaczmarek** [comment]
@KonSla dzięki - konto jest już aktywne.
