### ISSUE TITLE
Brak sygnatury (external) w formularzu

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2199]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W formularzu tworzenia/edycji aukcji brakuje pola "Sygnatura", które jest w środowisku produkcyjnym przy każdej aukcji, a odpowiada "external" z draftu.
![external](https://user-images.githubusercontent.com/37405655/64530628-e7e39c80-d30d-11e9-9b69-95f28efea3c2.png)

**Comment by TomekKaczmarek** [comment]
@martacronic nie mogę powtórzyć błędu:

![image](https://user-images.githubusercontent.com/36262678/64531186-288fe580-d30f-11e9-8212-c2c2bf631a22.png)

**Comment by martacronic** [comment]
@TomekKaczmarek u mnie przy edycji od razu pod tytułem jest Kategoria i w całym formularzu nie mam tego pola

![external2](https://user-images.githubusercontent.com/37405655/64531498-f6cb4e80-d30f-11e9-995d-567160af96d3.png)

**Comment by TomekKaczmarek** [comment]
@martacronic żeby skorzystać z sygnatury trzeba mieć konto firmowe, konto na którym jest wystawiona oferta widoczna na zrzutach ekranu nie ma statusu firma.

**Comment by martacronic** [comment]
@TomekKaczmarek rozumiem, a w jaki sposób mogę to konto sandbox zmienić na firmowe, bo nasze produkcyjne konto jest kontem firmowym?

**Comment by TomekKaczmarek** [comment]
@martacronic tak samo jak na koncie produkcyjnym - https://allegro.pl.allegrosandbox.pl/myaccount/Settings/mysettings.php

- na dole formularza jest link "Zmień konto na konto Firma"
- wypełnij formularz
- podaj rzeczywiste dane adresowe
- załącz dowolne pliki
- daj znać, gdy prześlesz formularz - przyspieszę aktywację.

**Comment by martacronic** [comment]
@TomekKaczmarek wczoraj znalazłam i zrobiłam tak jak napisałeś, ale wisi cały czas jako w trakcie zmiany na konto firma, także proszę o "magiczne" przyspieszenie aktywacji

**Comment by TomekKaczmarek** [comment]
@martacronic jasne - podaj proszę nazwę konta.

**Comment by martacronic** [comment]
@TomekKaczmarek Client:43978688

**Comment by TomekKaczmarek** [comment]
@martacronic na sandboxie nie ma konto o takiej nazwie.

**Comment by martacronic** [comment]
@TomekKaczmarek hmm dzisiaj wyświetla się cronic_testowy

**Comment by PrzemyslawLukanowski** [comment]
@martacronic  Wstępnie aktywowałem konto. Aby dokończyć proces aktywacji, prześlij dwa dowolne pliki przez zakładkę Moje konto -> Dane konta.

**Comment by martacronic** [comment]
@TomekKaczmarek  zrobione
