### ISSUE TITLE
Wyszukiwanie produktów po EAN

### ISSUE THREAD

**Issue by krychu90** [allegro/allegro-api#22]
Witam,
czy można się spodziewać możliwości wyszukiwania produktów po kodzie EAN lub innym kodzie identyfikującym produkt? Aktualnie nie ma możliwości powiązania produktu z zewnętrznego systemu z ofertą na allegro.

Pozdrawiam.

**Comment by LukaszKorek** [comment]
Dzień dobry
W tej chwili nie ma takiej możliwości. Jeżeli coś takiego udostępnimy damy znać. Na ten moment mogę doradzić korzystanie z metody doGetItemFIelds. Za pomocą tej metody może Pan pobrać kod EAN jeśli został dodany do oferty- fid 337.
