### ISSUE TITLE
Leksykon/Słownik FID-ów wraz z ich dozwolonymi wartościami

### ISSUE THREAD

**Issue by Masterboreq** [allegro/allegro-api#220]
Witam!
Przydałaby się wyczerpująca dokumentacja z opisami kolejnych FID-ów (jakie dane przenosi, jakie ma zadanie dany FID) wraz z dozwolonymi wartościami (rodzajem wartości, ich opisem, długością, rozmiarem) dla danego FID-u. Jeśli takowa istnieje, proszę o wskazanie mi adresu takiego zasobu.
Opisy FID-ów w niektórych metodach SOAP są albo fragmentaryczne, albo niewystarczające. I o ile FID-y 1, 2, 16-23, 24, 341 każdy już zna, to naprawdę nie mam pojęcia jakie są dozwolone wartości dla np. FID-u 144.
Myślę, że taki słownik byłby wielce pomocny!

**Comment by kormichu** [comment]
Skorzystaj z metody doGetSellFormFieldsForCategory: https://allegro.pl/webapi/documentation.php/show/id,782#method-output aby pobrać pełną listę FID'ów. Te globalne mają w polu sellFormCat wartość 0, zaś dostępne wartości masz w polu sellFormOptsValues

**Comment by Masterboreq** [comment]
Dzięki, @kormichu!
Dla tych, których frapuje podobny problem dodam, że dane o numerach kategorii pozyskujemy przy użyciu metody doGetCatsData(): https://allegro.pl/webapi/documentation.php/show/id,46#method-input
Wątku na razie nie zamykam, bo być może niebawem dołożę jeszcze coś pomocnego od siebie w tym temacie.
