### ISSUE TITLE
Część zdjęć nie uploaduje się i zwraca status 0

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2200]
Występuje problem: 
 - [ X ] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,
od paru dni miewamy problemy z uploadowaniem zdjęć. Zwraca status 0 i tyle. Nagłówki są ustawione zgodnie z dokumentacją, a całość pliku przesyłana od nas (nie przez podanie linku). Dodam, że problem nie dotyczy każdego zdjęcia. Średnio po paru udanych uploadach wyskakuje na jednym status 0, przez co jest problem z poprawnym wystawianiem wielu aukcji.

Dane nagłówka i przykładowe zdjęcie wysłałem formularzem kontaktowym.

**Comment by TomekKaczmarek** [comment]
Dzięki za zgłoszenie, jak tylko otrzymamy Twoją wiadomość - przyjrzymy się tematowi.

**Comment by hahyes** [comment]
Dodam trochę informacji, które zebrałem i może to rozjaśni problem.

Problem występuje losowo, komunikaty zwracane od serwera wskazują na zerwanie połączenia przez serwer, dokładnie cytując: "Nie można zapisać danych do połączenia transportowego: Istniejące połączenie zostało gwałtownie zamknięte przez zdalnego hosta.". Time-outy też się zdarzają.

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że w nagłówku przesyłasz pole text/byte, bytes - jeżeli faktycznie dodam taki nagłówek, to otrzymuję “Could not get any response". Spróbuj usunąć to pole.
Prośba o zgłaszanie problemu za pomocą jednego kanału - nagłówki ze zgłoszenia spokojnie można przesyłać tutaj.

**Comment by hahyes** [comment]
> 
> 
> Widzę, że w nagłówku przesyłasz pole text/byte, bytes - jeżeli faktycznie dodam taki nagłówek, to otrzymuję “Could not get any response". Spróbuj usunąć to pole.
> Prośba o zgłaszanie problemu za pomocą jednego kanału - nagłówki ze zgłoszenia spokojnie można przesyłać tutaj.

Źle może to wyciąłem z kodu, wysyłam text/byte i z nim bajty zdjęcia. Co do nagłówków, dobrze wiedzieć. Zapamiętam.

Jednakże statuscode 0 dotyczy w niemal każdym wypadku niestabilności połączenia. Może temat wydaje się teraz zbędny, jednak może kiedyś ktoś będzie szukał. Można zamknąć.
