### ISSUE TITLE
Pytanie o plany dla https://api.allegro.pl/users/{userId}/ratings-summary

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2201]
Dzień dobry,
Czy w związku z wdrożeniem "Jakość mojej sprzedaży" oraz "Odznaki sprzedawcy"  planujecie rozbudowę publicznej informacji o jakości konta?

**Comment by TomekKaczmarek** [comment]
@kfijalko w najbliższym czasie nie mamy takich planów, ale dzięki za sugestię, przekazuję ją do odpowiedniego zespołu.
