### ISSUE TITLE
mapowanie postBuyFormPayId i postBuyFormId

### ISSUE THREAD

**Issue by Jushop** [allegro/allegro-api#2203]
Cześć.
 
Wcześniej po swojej stronie zapisywałam dla zamówień następujące pola:  postBuyFormPayId i postBuyFormId.

Teraz jak pobieram  dany checkout-forms to za pomocą metody /payments/payment-id-mappings  oraz  parametru paymentId otrzymuję transactionId (widzę , że jest to to samo co w polu postBuyFormId ) . Czym teraz jest wcześniejsza wartość postBuyFormPayId ?

 Pozdrawiam.

**Comment by TomekKaczmarek** [comment]
@Jushop postBuyFormPayId maper pozwala powiązać transakcję z płatnością - nie oznacza to, że te pola odpowiadają sobie 1:1. PostBuyFormPayId - to identyfikator płatności, któremu w REST API odpowiada payment.id w szczegółach zamówienia.

**Comment by Jushop** [comment]
ok, czyli zmieniony został format dla PostBuyFormPayId z long na GUID ?

**Comment by TomekKaczmarek** [comment]
@Jushop nie postawiłbym takiego twierdzenia, nowe zamówienia mają niewiele wspólnego z zamówieniami dostępnymi w ramach starych mechanizmów na WebAPI. Proces zakupowy w Allergo mocno ewoluował w ciągu ostatnich kilku lat i dane raczej były naciągane, by zachować kompatybilność wsteczną z WebAPI. Nowe API odwzorowuje po prostu aktualne procesy w Allegro, w większości przypadku może być tak jak piszesz, ale nie gwarantuję, że będzie tak zawsze.
