### ISSUE TITLE
[restAPI] Lista ofert vs warianty 

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2204]
:bulb: **Sugestia**

Cześć, 

Mam taki scenariusz: 
Chciałbym na liście ofert oznaczać, które oferty są spięte wielowariantowo, tak aby administrator mógł sobie kliknąć i podejrzeć jakie aukcje są spięte i wykonać dodatkowe akcje.
W restAPI dla listy ofert nie ma niczego co by pozwalało wiedzieć że ta oferta wchodzi w skład oferty wielowariantowej, a przynajmniej ja nie znalazłem
Zgłaszam sugestię by dodać taką funkcję

Druga sprawa: API dla wariantów, czy dokumentacja jest aktualna? https://developer.allegro.pl/multi_variant_offers/#6
Jeśli tak to kolejna sugestia by API dla wariantów zwracało także w odpowiedzi nr ofert, teraz pobranie wariantów nic nie daje, bo nie wiem co wchodzi w skład danego wariantu
Nie sprawdzałem tego na żywo, czytam tylko dokumentację, jeśli się myle proszę o aktualizację dokumentacji :)

**Comment by TomekKaczmarek** [comment]
Dzięki wielkie za sugestie - przekazuję je do odpowiedniego zespołu.
