### ISSUE TITLE
Do kiedy beta ?

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2205]
Witam,

Do kiedy zasoby tj:
1) https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST
2) https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET
3) https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET
4) https://developer.allegro.pl/documentation/#operation/findMapping
5) https://developer.allegro.pl/documentation/#operation/getOfferEvents

będą w wersji beta ? Chcielibyśmy już zacząć proces migracji z SOAP na REST API jednak nie możemy opierać się na wersji API która nie jest publiczna. Z tego co zauważyłem proces wygaszania API, który jest w fazie beta jest praktycznie natychmiastowy (około tygodnia), a my nie jesteśmy w stanie tak szybko wprowadzić zmian (cykl miesięczny)

**Comment by TomekKaczmarek** [comment]
@kormichu zasoby udostępniamy w wersji beta z kilku powodów
- by poznać wasze opinie na temat nowych procesów
- by przetestować proces
- by można było prowadzić prace developerski i wdrożyć nowy proces, gdy przejdziemy na wersję public.
Warto już na etapie wersji beta prowadzić development, dzięki temu można łatwo przejść na zasoby RESTowe, gdy wejdziemy na wersję public.

Zamówienia powinny przejść na wersję publiczną w ciągu najbliższych kilku tygodni. Żadnych zmian nie planujemy - wystarczy zmienić wersję w nagłówku.

**Comment by kormichu** [comment]
Czy wyrzucacie jakiś kod błędu w przypadku kiedy spróbujemy skorzystać z metody, która wygasła ? Chciałbym się zabezpieczyć w ten sposób, aby wysłać request najpierw na API będące w becie, a jeśli wystąpi błąd to spróbować na public

**Comment by TomekKaczmarek** [comment]
@kormichu tak naprawdę zmieni się tylko nagłówek, co więcej przez pewien czas będziemy przyjmować obie (public i beta) wersje nagłówka, by można było spokojnie przejść z jednej wersji zasobu na drugą.

Specjalnego komunikatu błędu nie przewidujemy - gdy przestaniemy wspierać nagłówek beta - otrzymasz błąd
Status: 406 - Not Acceptable
`{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "Not acceptable representation requested. Please check 'Accept' request header",
            "details": null,
            "path": null,
            "userMessage": "The request contains incorrect data. Contact the author of the application."
        }
    ]
}`
