### ISSUE TITLE
Zczytanie listy transakcji z dnia wczorajszego

### ISSUE THREAD

**Issue by grzegorzmacialek** [allegro/allegro-api#2206]
Witam,

Czy jest możliwość poprzez API na pobranie wszystkich zawartych transakcji w danej kategorii dnia poprzedniego chociażby po trawersowanie przez aukcje?

Wedle serwisu **TradeWatch.pl** "Informacje o transakcjach pobierane są z autoryzowanego przez Allegro kanału Allegro WebAPI." wiec te dane są publicznie dostępne ?

**TradeWatch.pl** monitoruje na bieżąco wszystkie transakcje dokonywane na Allegro. - czy sa dostępne metody które mówią nam o zawarciu transakcji?

**Comment by TomekKaczmarek** [comment]
Z tego co wiem tradewatch opiera się na dzienniku zdarzeń z całej platformy:

- doGetSiteJournal
- doGetSiteJournalInfo

**Comment by grzegorzmacialek** [comment]
1. Czy te metody działają tylko w kontekście użytkownika ? (Jeśli tak w jaki sposób TradeWatch.pl możne zczytywac wszystkie transakcje bez autoryzacji ?)
2.  Czy te metody dostępne są w REST API?

**Comment by TomekKaczmarek** [comment]
Ad 1 / Mogą działać w kontekście użytkownika albo w kontekście całej platformy.
Ad 2 / Nie, ale planujemy odpowiednik tych funkcji w REST API - powinien się pojawić w ciągu najbliższego półrocza.
