### ISSUE TITLE
Witam, korzystamy z programu easy uploader 3.40.2.0 do pobierania transakcji allegro oraz wysyłki przesyłek.

### ISSUE THREAD

**Issue by mokar77** [allegro/allegro-api#2207]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

**Comment by mokar77** [comment]
![EASY Bez tytułu](https://user-images.githubusercontent.com/55183903/64683570-ce646100-d483-11e9-83ff-f0dd581ef4e2.png)

**Comment by mokar77** [comment]
Mamy problem w tej postaci, że od około tygodnia nie pobiera nam części transakcji z allegro.
Nie widzimy tych transakcji w programie easy uploader

**Comment by kfijalko** [comment]
zamaż dane osobowe na zrzucie ekranu

**Comment by kfijalko** [comment]
Musisz napisać do twórców easy uploadera. Komunikat mówi, że błąd wystąpił podczas zapisywania do bazy danych. Zakładam że program pobrał dane z restapi allegro tylko nie potrafi ich zapisać. To tylko dywagacje - nie znam programu.
