### ISSUE TITLE
doGetPostBuyFormsDataForSellers: Błędny adres wysyłki 

### ISSUE THREAD

**Issue by bortosProduction** [allegro/allegro-api#221]
Witam,
Metoda doGetPostBuyFormsDataForSellers dla transakcji "848171496" zwraca inne dane do wysyłki niż można zobaczyć w zakładce "zamówienia"

**Comment by KrzysztofLukanowski** [comment]
Cześć,

zamówienie, o którym piszesz, zostało złożone w trakcie występowania problemów technicznych. 9 maja do wszystkich sprzedających, u których odnotowaliśmy wystąpienie błędu, wysłaliśmy poniższą wiadomość:
````
W części realizowanych przez Ciebie zamówień może występować nieprawidłowy adres dostawy. Problem dotyczy zakupów zrobionych od 7 maja, od godziny 11:37 do 8 maja, do godziny 12:30, dla których kupujący wskazał inny adres dostawy niż ten z ustawień konta Allegro. W wyniku błędu technicznego przekazaliśmy Ci w tych przypadkach adres z ustawień konta Allegro kupującego.

Prawidłowe adresy do wysyłki zakupów zrobionych w czasie awarii znajdziesz w zakładce Zamówienia.

Przykro nam z powodu powstałego błędu. Przepraszamy za niedogodności. Jeśli z powodu naszego błędu kupujący negatywnie oceni dostawę w Twojej ofercie, prosimy zgłoś nam tę sytuację.
````

**Comment by michalocw** [comment]
Dzięki za szybką odpowiedź, 
Poprosiłem mojego klienta żeby sprawdził dokładnie skrzynkę, twierdzi że nie dostał od Was maila, jeśli była by taka możliwość podeślijcie go jeszcze raz,

**Comment by KrzysztofLukanowski** [comment]
Niestety nie ma takiej opcji, jeśli klient zauważył nieprawidłowości, proszę aby skontaktował się z nami bezpośrednio przez [formularz](https://allegro.pl/pomoc/kontakt#subjectId=2b705de9-0c53-4b3d-9ca1-1c0baa4f23e9).
