### ISSUE TITLE
Pobieranie pytań z Zadaj pytanie

### ISSUE THREAD

**Issue by dejwid1989lkr** [allegro/allegro-api#2210]
Witam,
czy w API występuje możliwość pobrania pytań ? (zdj. poniżej). Próbowałem pobrać te dane za pomocą dyskusji (GET /sale/disputes) ale niestety nie zwracało mi danych.

![image](https://user-images.githubusercontent.com/55185919/64685761-ca3a4280-d487-11e9-97f4-58ecc75ddccf.png)

**Comment by TomekKaczmarek** [comment]
Na ten moment nie - wiadomość przekazujemy na adres email, na który sprzedawca założył konto.
