### ISSUE TITLE
Drzewo kategori plik

### ISSUE THREAD

**Issue by Dawidek990** [allegro/allegro-api#2211]
Witam potrzebuje pliku z wszystkimi kategoriami z allegro.
Cos w stylu zeby w pliku znajdowalo sie nazwa kategori i kod
np: Motoryzacja > Chemia > Oleje silnikowe > Syntetyczne 253184

Czy ktos posiada moze taki plik? i mogl by mi taki przeslac.
Ew czy jest gdzies strona gdzie moge takie dane pobrac?

Pozdrawiam.

**Comment by kfijalko** [comment]
[all_categories_20190911.xlsx](https://github.com/allegro/allegro-api/files/3600749/all_categories_20190911.xlsx)

**Comment by Dawidek990** [comment]
dzieki wielkie ;]

śr., 11 wrz 2019 o 14:27 kfijalko <notifications@github.com> napisał(a):

**Comment by Dawidek990** [comment]
Witam, potrzebuje programu/skryptu który by ściągnął liste wszystkich aukcji uzytkownika ktorego mu wskaze. Posiada pan moze takie rozwiazanie? moge ew zaplacic za taki skrypt ew program ;]

**Comment by kfijalko** [comment]
Niestety nie mam czasu.
