### ISSUE TITLE
Tagi a wystawianie nowych ofert na podstawie starych

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2212]
Nie znalazłam w dokumentacji, ani we wcześniejszych issue.

Sytuacja 1:
1. Oferta A jest wystawiona z opcją "po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów" i ma dodane tagi.
2. Oferta A kończy i automatycznie wystawia się oferta B.

Czy oferta B będzie posiadała tagi z oferty A? 
Jeśli nie, to w jaki sposób proponujecie dodać tagi do B, ponieważ oferty A i B w rest api nic ze sobą nie wiąże (w ofertach nie jest używane external, bo były wystawiane przez panel Allegro).

Sytuacja 2:
1. Oferta A jest wystawiona i ma tagi.
2. Pobieram draft oferty A i wystawiam ofertę B.
3. Oferta B nie ma tagów, bo dratf ich nie ma.

Jak dodać tagi, żeby mieć pewność, że się dodały skoro w #1354 okazuje się, że status "SUCCESS" to za mało?

**Comment by TomekKaczmarek** [comment]
Ad 1/ Tak oferta B powinna być identyczna, jak oferta A - czyli tagi również powinny być takie same.
Ad 2/ Tagi możesz dodać, dopiero gdy opublikujesz ofertę B (czyli publication.status = active).

**Comment by martacronic** [comment]
Ad1 @TomekKaczmarek super wiadomość

Ad2 @TomekKaczmarek  A czy GET /sale/offer-publication-commands/{commandId}/tasks, kiedy task->status = "SUCCESS" nie oznacza, że oferta jest aktywna? Czy w takim razie dodatkowo dla każdej oferty powinnam robić do skutku GET /sale/offers/{id}, aż otrzymam ACTIVE?

**Comment by TomekKaczmarek** [comment]
@martacronic Ad 2 - nie oznacza, że oferta jest poprawna i przyjęta do aktywacji - status aktywna zwykle pojawi się w ofercie niemal w tym samym momencie, ale w przypadku dużej liczby aktywacji ofert lub wzmożonego ruchu, akceptowalny czas, w którym może nastąpić faktyczna aktywacja oferty wynosi do 60 minut.

Na pewno nie wywoływałbym do skutku GET /sale/offers/{id} - sprawdziłbym po 5 minutach. Potem np. po 30 i po 60 (w sensie przyjąłbym jakieś interwały czasowe, żeby nie przekroczyć limitu requestów). Jeśli po 60 minutach oferta nie będzie aktywna - wtedy zgłoś to do nas jako błąd.

**Comment by martacronic** [comment]
dziękuje
