### ISSUE TITLE
/order/events  w wersji public

### ISSUE THREAD

**Issue by JanuszK2** [allegro/allegro-api#2213]
Kiedy zasoby /order/events i /order/checkout-forms będą dostępne w wersji public?
Allegro wymusza przejście na zmodyfikowaną obsługę Smart informując o rzekomej gotowości narzędzi do jego obsługi, ale póki co polega to na ręcznym przeglądaniu setek aktów zakupowych?

**Comment by TomekKaczmarek** [comment]
#2121 - o nowym sposobie rozliczania przesyłek i co zrobić, by działał poprawnie piszemy w tym wątku.

Zamówienia powinny przejść na wersję publiczną w ciągu najbliższych kilku tygodni. Żadnych zmian nie planujemy - wystarczy zmienić wersję w nagłówku.
