### ISSUE TITLE
Upload asynchroniczny zdjęć a Allegro

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2214]
Nigdzie specjalnie nie ma o tym mowy w dokumentacji, zatem mam pytanie. Czy upload zdjęć ma jakieś indywidualne limity? Chcę wystawiać aukcje asynchronicznie jednocześnie uploadując zdjęcia też asynchronicznie. Problem jest w tym, że chcę zoptymalizować wystawianie, jak najbardziej to możliwe, jednak czasy uploadu zdjęć są dość zbliżone do działań synchronicznych mimo kilku zdjęć wysyłanych na raz, a nie wygląda na to, abym wykorzystywał łącze w pełni, jest jeszcze sporo luzu. Więc jak to jest z tym uploadem? Jak on działa?

**Comment by hahyes** [comment]
Okej, zatem czy jest jakieś ograniczenie ilości aukcji, które mogą się uploadować poza tym "120 żądań na sekundę/9000 na minutę"? Przy dużej ilości aukcji wystawianych asynchronicznie bardzo często dochodzi do przeciążeń i time-outów mimo sporego zapasu na łączu. Uznaję to za bardzo dziwne.

**Comment by TomekKaczmarek** [comment]
Innych odgórnych limitów i ograniczeń nie ma. Jeśli dla jakichś zasobów często otrzymujesz timeouty - zgłoś taki problem do nas - podaj przykłady wywołań, które zakończyły się takim błędem - podaj trace-id i timestampy.
