### ISSUE TITLE
Problem z pobieraniem danych

### ISSUE THREAD

**Issue by mokar77** [allegro/allegro-api#2216]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam
 
Mamy problem z pobieraniem danych z jednego z trzech kont , próbowaliśmy naprawy bazy danych , zakładania osobnej nowej, program lokalnie i nic.
Nie działa też generowanie logu po mino ctrl+schift+L. 
Program Easyuploader w najnowszej wersji, z najnowszymi aktualizacjami.
Z załączniku komunikat błędu w jedynej możliwej formie.
 
Mokar Szamotuły
 
884-004-489
![blad12092019](https://user-images.githubusercontent.com/55183903/64776644-e823a800-d558-11e9-97da-496dc5d7f57a.png)

**Comment by kfijalko** [comment]
@mokar77 jeżeli nie jesteś programistą to będzie ciężko. Skorzystaj z rady @hahyes .
To jest forum dla programistów, którzy wykorzystują rest api allegro. Żeby pracownicy allegro byli w stanie Ci pomóc to musisz podać jakie wywołania lecą do allegro i najlepiej z trace-id (który znajduje się w odpowiedzi z allegro). 
Możesz ewentualnie zainstalować oprogramowanie śledzące ruch sieciowy. Choć ruch idzie po https więc raczej treści nie zobaczysz, ale może kod odpowiedzi. Jeżeli przychodzi 200, 201, 20X to odpowiedź z allegro jest prawidłowa i wtedy tylko kwestia co EasyU robi z tą odpowiedzią. No, ale raczej zacznij od supportu EasyU. Jeżeli z jakichś względów nie możesz skorzystać z ich supportu to poszukaj w swojej bazie EU lub w folderze aplikacji jakiegoś pliku logu. Może tam będą jakieś szczegóły.
