### ISSUE TITLE
REST API: Problem with getting orders on sandbox

### ISSUE THREAD

**Issue by martinfbluesoftcz** [allegro/allegro-api#2217]
Hello, I need to implement getting orders. My Client ID for Sandbox is: a744e55cf701491a9ea8dc0de4be967e

I am getting errors for /order/events and for /order/checkout-forms:

Request:
```
GET https://api.allegro.pl.allegrosandbox.pl/order/events
Authorization: Bearer xxxTOKENxxx
Accept: application/vnd.allegro.beta.v1+json
```

Response:
```
HTTP/1.1 403 Forbidden
{
  "errors": [
    {
      "code": "ERROR",
      "message": "An error has occurred",
      "details": null,
      "path": null,
      "userMessage": null
    }
  ]
}
```

Request:
```
GET https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms
Authorization: Bearer xxxTOKENxxx
Accept: application/vnd.allegro.beta.v1+json
```

Response:
```
HTTP/1.1 500 Internal Server Error
{
  "errors": [
    {
      "code": "CHECKOUT_FORM_EXCEPTION",
      "message": "cannot read checkout form(s)",
      "details": null,
      "path": "/order/checkout-forms",
      "userMessage": null
    }
  ]
}
```

Please help. I going to implement it for big client. Official credentials for production/sandbox going to get next week, so it's my personal test account now.

**Comment by martinfbluesoftcz** [comment]
@TomekKaczmarek Hmm this is bad, I checked it and it seems all ok. I am getting token from https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials this is right, isn't it?
I have decoded token https://jwt.io/ and client ID is ok. So I don't have idea what doing wrong.

**Comment by TomekKaczmarek** [comment]
No it is not - please read the tutorial carefully. Client credentials allows you to access resources which return public data. Orders are not public, these type of data can be returned only for merchants, which listed the offer and received an order. You should use the Authorization Code flow.

If you want to know more - please read this tutorial - https://developer.allegro.pl/en/auth/#app

**Comment by martinfbluesoftcz** [comment]
@TomekKaczmarek  Ooh, this explains everything. Thanks. 
But our client wants to reading orders from allegro automatically in scheduled task to import orders to his eshop and ERP. Is it possible? In authorization code flow user's manual action is needed if I understand correctly, but this is not convenient for us. 
Thank you.

**Comment by TomekKaczmarek** [comment]
@martinfbluesoftcz yes, at least once user needs to confirm the authorization process - and this is recommended approach for all apps with GUI which utilizes Allegro API.
