### ISSUE TITLE
DoMyContactRequest

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#222]
Dziwny problem:
Za pomocą DoMyContactRequest wysyłam listę 24 numerów aukcji (24 by w sytuacji gdy będzie 25 kontaktów w odpowiedzi, dosłać drugie zapytanie zwiększając offset). W odpowiedzi dostaję listę 23 kontaktów. Dopytywać nie ma co, bo metoda zwraca do 25 odpowiedzi na raz. Na liście brakuje kontaktu dla jednej aukcji.
Gdy w drugim requescie wyślę zapytanie tylko dla tej jednej aukcji, bez problemu otrzymuję przypisany do niej kontakt.
Wygląda na to, że metoda zwraca mniej niż 24 kontakty na raz, nawet gdy naprawdę jest ich dużo więcej (odpowiedź jest ważona?), gdy operuję offsetem, udaje się wyciągnąć wszystkie
Służę odpowiednimi XMLami. Ale, że dane są wrażliwe, nie mogę załączyć ich tutaj.

**Comment by KrzysztofLukanowski** [comment]
Podeślij proszę request i response w formacie xml. Skorzystaj w tym celu z naszego [formularza](https://allegro.pl/pomoc/kontakt#subjectId=1436f902-6fd9-420f-9e19-321b684cc8df) .

**Comment by lukada4100** [comment]
Poszło [Ticket#1247808536]

**Comment by KrzysztofLukanowski** [comment]
Weryfikujemy sprawę, tymczasem do pobierania danych proszę korzystać z [doGetPostBuyData](https://allegro.pl/webapi/documentation.php/show/id,89#method-output).
