### ISSUE TITLE
Jak pobrać name z ContactsApi w Java?

### ISSUE THREAD

**Issue by ladamski49** [allegro/allegro-api#2221]
Chciałbym otrzymać name z ContactsApi (kod restowy wygenerowany przez swagger).
W momencie gdy uruchamiam taki kod:

```
ApiClient ac = new ApiClient(ALLEGRO_CLIENT_ID.val(), ALLEGRO_CLIENT_SECRET.val(), new HashMap<>());
ContactsApi api = new ContactsApi(ac);
String id = "6912967854";
ContactResponse response = api.getContactUsingGET(id);
System.out.println(response.getName());
```

Otrzymuje:

`
java.lang.RuntimeException: Authentication undefined: bearer-token-for-user`

Wydaje mi się, że brakuje mi tokena. Dlatego też zmodyfikowałem swój kod:

```
ApiClient ac = new ApiClient(ALLEGRO_CLIENT_ID.val(), ALLEGRO_CLIENT_SECRET.val(), new HashMap<>());
//musze uzyskać token poprzez kod ale nie wiem jak to zrobić
String accessToken = "jakisAccessToken";
ac.setAccessToken(accessToken);
ContactsApi api = new ContactsApi(ac);
String id = "6912967854";
ContactResponse response = api.getContactUsingGET(id);
System.out.println(response.getName());
```

Czy mógłby ktoś napisać linijke kodu Javy do generacji tokena.

W dokumentacji:

https://developer.allegro.pl/auth/#CredentialsFlow

Jest napisane:
Punkt 5:
"Mając ważny kod, aplikacja zgłasza się po token wykonując żądanie HTTP metodą POST na adres" i jest zapytanie CURL.

`curl -X POST -H 'Authorization: Basic YTI...Hg=' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'`

Tylko tutaj jest juz zalożenie, że mamy kod wcześniej wyklikany. Moim celem jest napisanie prostego kodu w Java do pobierania name z ContactsApi.
Bardzo dziękuje za pomoc.

**Comment by TomekKaczmarek** [comment]
Niestety nie wspieramy pytań związanych bezpośrednio z programowaniem. Może ktoś z użytkowników forum podpowie Tobie jak to zrobić.

Podpowiem jedynie, że dla tego zasobu musisz skorzystać z autoryzacji typu Code flow - gdyż kontakty są utworzone i dostępne jedynie w ramach danego konta sprzedawcy. Więcej na ten temat w tym artykule: https://developer.allegro.pl/auth/#app

**Comment by jakubmaguza** [comment]
Prostego kodu w Java nie napiszesz, bo musisz zautoryzować użytkownika, a to wymaga trochę więcej zaangażowania, szczególnie na początku drogi programistycznej.
https://developer.allegro.pl/auth/#DeviceFlow
Tutaj masz opisane o co chodzi. W skrócie: nie ty sam generujesz Token, więc nie da się tego zrobić w jednej linijce. Użytkownik nie może zalogować się w Twojej aplikacji. Musi zalogować się w Allegro, a zaraz po tym, musisz poprosić allegro żeby zwróciło Ci token dla tego konkretnego użytkownika.

@TomekKaczmarek 
Czy ma znaczenie czy skorzysta z Code Flow czy z Device Flow?

**Comment by TomekKaczmarek** [comment]
@jakubmaguza @ladamski49 nie ma - aczkolwiek, jeśli aplikacja ma GUI - zalecamy Code flow, jest bardziej przyjazne użytkownikowi.

**Comment by jakubmaguza** [comment]
W przypadku aplikacji desktopowej może być problem. Nie każdy komputer pozwoli na postawienie serwera na szybko, żeby nasłuchiwać na odpowiedź od allegro.
Device Flow jest zdecydowanie łatwiejsze w takim przypadku, a jeśli użytkownikowi otworzy się przeglądarkę z wpisanym kodem, to praktycznie nie zobaczy różnicy. W każdym razie cieszę się, że obie drogi prowadzą do tego samego dostępu :)
