### ISSUE TITLE
Zmiany w restApi w związku z "Usuwamy oceny za czas wysyłki" od 2 października

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2222]
Jak ta zmiana wpłynie na api?

**Comment by TomekKaczmarek** [comment]
Dziś ustalimy szczegóły podejście do tej zmiany w API. Komunikat pojawi się jutro/pojutrze. Rozważamy dwa podejście - albo będziemy w tym polu zwracać zero, albo w ogóle nie będziemy zwracać tego pola. Wkrótce zakomunikujemy szczegóły i które podejście wybraliśmy.

**Comment by kfijalko** [comment]
Osobiście wolę zero. Wtedy nic nie muszę zmieniać, no i mamy kompatybilność wsteczną.

**Comment by TomekKaczmarek** [comment]
@kfijalko tylko oceny bardzo często są liczone do wszelkiego rodzaju średnich, 0 mogłoby wpłynąć na poprawne liczenie danych statystycznych, dlatego zdecydowaliśmy, że będziemy zwracać _null_.

#2227 -  tutaj znajdziesz szczegóły.
