### ISSUE TITLE
GET /sale/offers/{offer.id} niedostępne dla ofert spoza puli właścieciela aplikacji

### ISSUE THREAD

**Issue by kolor200** [allegro/allegro-api#2223]
Witam użycie zasobu GET /sale/offers/{offer.id} dla ofert spoza puli ofert właściciela aplikacja daje poniższy błąd:

>  {'errors': [{'code': 'FORBIDDEN', 'message': 'Forbidden', 'details': None, 'path': '/sale/offers/7476884226', 'userMessage': None}]}

W jaki sposób mogę pobrać szczegóły danych ofert od różnych sprzedawców? Na przykład parametry tych ofert? Dane te są dostępne publicznie w opisie oferty w wersji przeglądarkowej.

**Comment by hahyes** [comment]
https://developer.allegro.pl/documentation/#operation/getListing

Jest taki zasób do wyszukiwania publicznych aukcji. Jednakże nie wygląda na to, aby posiadał parametry pól i ich wartości, niestety.

**Comment by TomekKaczmarek** [comment]
@kolor200 tak, jak pisał @hahyes - podstawowe informacje o ofertach możesz teraz wyciągnąć za pomocą https://developer.allegro.pl/documentation/#operation/getListing.

Nad zasobem, który pozwoli pobrać publiczne dane do oferty będzie pracować, powinniśmy go udostępnić w ciągu najbliższego pół roku.

**Comment by kolor200** [comment]
@TomekKaczmarek  Rozumiem, dziękuje za odpowiedź i liczę na szybkie wprowadzenie zasobu.
