### ISSUE TITLE
Aktywacja konta firmowego sandbox

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2224]
Witam,
proszę o aktywowanie konta firmowego dla loginu "aa" na sandboxie.
Tak swoja drogą mam wątpliwości czy formularz w którym podaje się dane firmy działa prawidłowo. Po wypełnieniu formularza zostaję przeniesiony na stronę bez żadnego komunikatu.

**Comment by PrzemyslawLukanowski** [comment]
Tak, znamy ten problem, zgłosiliśmy go już do odpowiedniego zespołu. Prośba, aby spróbować przesłać dwa dowolne dokumenty jeszcze raz, zmieniając przy tym rodzaj przedsiębiorstwa na inny. Prawidłowe przesłanie powinno zakończyć się komunikatem.

**Comment by mzawodzinski** [comment]
Sprawdziłem działalność jednoosobową, spółkę akcyjna i spółkę z o.o 
we wszystkich trzech przypadkach przenosi na stronę główną bez komunikatu.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, pracujemy nad rozwiązaniem błędu.

**Comment by mzawodzinski** [comment]
Problem cały czas występuje,
istnieje szansa że zostanie to poprawione ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, pracujemy nad rozwiązaniem problemu.

**Comment by deartify** [comment]
Witam, 
proszę o pełną aktywację konta "cellfast" konto zakładane przez formularz jako spółka z o.o.

**Comment by PatrykBocian** [comment]
@deartify  Konto zostało wstępnie aktywowane, prześlij proszę dwa dowolne zdjęcia do "skanu odpisu z KRS" w zakładce [Dane konta.](https://allegro.pl/myaccount/mysettings.php)
