### ISSUE TITLE
Mapowanie kategorii Allegro do Tecdoc

### ISSUE THREAD

**Issue by Sharhin** [allegro/allegro-api#2225]
Czy jest możliwość pobrania kategorii na podstawie danych z bazy TecDoc i/lub pobrania kategorii z TecDoc za pomocą kategorii z Allegro?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy takiego zasobu. Jaka jest potrzeba posiadania takiej funkcjonalności? Na tę chwilę przekazałem sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie, poinformujemy o tym we właściwym komunikacie.

**Comment by Sharhin** [comment]
>  Jaka jest potrzeba posiadania takiej funkcjonalności? 

Klient chce wystawić hurtową ilość produktów z hurtowni posiadając jedynie id artykułu z TecDoc, a wybór kategorii jest wymagana przez serwis Allegro. W obecnym przypadku trzeba ręcznie połączyć każdą grupę artykułów (Generic Articles) z kategorią Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, tak jak wspomniałem - przekazałem sugestię do odpowiedniego zespołu.
