### ISSUE TITLE
Kurier wieczór

### ISSUE THREAD

**Issue by dawidcocieto** [allegro/allegro-api#2228]
Cześć,
dostałem kiedyś informację mailową o możliwości korzystania z formy dostawy - Kurier wieczór. Wraz z informacją dostaliśmy krótką informację jak zintegrować to przez WebAPI.
Korzystam aktualnie z REST API i nie znalazłem informacji o integracji przez REST.
Szukałem tu, ale odnośnik prowadzi do starej dokumentacji:
https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/kurier-wieczor-najczesciej-zadawane-pytania-vKvmg2oLzCj

Piszę z zapytaniem, czy istnieje nadal taka integracja przez REST API?
Jeżeli tak to w jaki sposób ją poprawnie wykonać?

Z góry dzięki za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Zasobem [GET na zasobie /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) pobierzesz id podanych metod dostawy:

- 6a0f88ba-8f25-44fc-b1cf-25f45cbe8e72 - kurier wieczór
- 3ca09a1f-11f2-4763-974e-ae80404062c3 - kurier wieczór pobranie

Teraz za pomocą zasobu [POST na zasobie /sale/shipping-rates/](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST)  przekaż podany id przy tworzeniu cennika dostawy lub edytuj go za pomocą [PUT /sale/shipping-rates{id}](https://developer.allegro.pl/documentation/#operation/modifyShippingRatesSetUsingPUT). Więcej szczegółów znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#shipping-rates).
