### ISSUE TITLE
doGetRefundsDeals

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#223]
Metoda doGetRefundsDeals błędnie zwraca wartość dealsCount. Zamiast zgodnie z dokumentacją wysyłać liczbę wszystkich aktów zakupowych (pasujących do danego zapytania)  przekazuje ilość RefundListType w poszczególnym responsie.

**Comment by lukada4100** [comment]
[Ticket#1247837796]

**Comment by KrzysztofLukanowski** [comment]
W podesłanych przykładach wskazałeś różny **resultOffset**. Otrzymana odpowiedź jest uzależniona od informacji wskazanych w zapytaniu.

**Comment by lukada4100** [comment]
No o to chodzi. Offset jest różny, a dealsCount zawsze zwraca, ilość RefundListType, w konkretnym responsie. W pierwszym przesłanym przykladzie dla offsetu 0, dealsCount wynosi 1000, dla tego samego zapytania z offsetem 1600, dealsCount jest 349. Rozumiem, że dla offsetu 0, dealsCount powinno zwracać łączną liczbę wszystkich RafundListType, czyli 16349.

**Comment by KrzysztofLukanowski** [comment]
dealsCount jest uzależnione od rozmiaru porcji, jaki określisz w resultSize. Jedna porcja nie może liczyć więcej niż 1000 danych.

**Comment by lukada4100** [comment]
Jeszcze raz. Wydawało mi się, ze podobnie jak w innych metodach (patrz np licznik sellItemsCounter w metodzie doGetMySellItems) pokazywać ma ile łącznie struktur jest do pobrania przy wpisanych w zapytaniu kryteriach. Nie wszystkie mogą zostać pobrane na raz, ale dzięki temu wiadomo jak w kolejnych zapytaniach sterować offsetem i ile zapytań wysłać, żeby pobrać wszystkie struktury.

Jeśli piszesz, ze obecnie dealsCount działa poprawnie, to właściwie do czego on służy? Teraz zawsze wyswietla po prostu ile struktur zostało zwróconych w konkretnym responsie. Mamy do pobrania 16349 struktur: jeśli zadam by pobierał po 1000 struktur i bedę zwiększał offset o 1000 to 16 razy dealsCount będzie miał wartość 1000 a za 17 razem 349.
Jeśli to samo będę pobierał po 100, dealsCount będzie miał 163 razy wartośc 100 i na końcu 49.
Można oczywiście przyjąć, że to poprawne funkcjonowanie, wtedy zamykamy wątek, ale jeśli tak to dealsCount nie służy właściwie do niczego.

**Comment by KrzysztofLukanowski** [comment]
Tak jak napisałem wyżej, dealsCount odpowiada liczbie zwróconych informacji w danym responsie. Nie jest możliwe, abyś podczas jednego wywołania metody otrzymał większą wartość niż 1000.

**Comment by lukada4100** [comment]
Czyli zgodzisz się, że jest po nic.
