### ISSUE TITLE
Jak pobrać ID cennika przypisanego do aukcji?

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#2230]
Jak pobrać ID cennika przypisanego do aukcji?

znalazłem tylko metodę:
sale/offers/{offerId}/shipping-rates - pobiera metody dostawy

**Comment by PrzemyslawLukanowski** [comment]
@PiotrFerenc shippingRates.id zwracamy w zasobie [GET sale/offers/{offerId](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)}, a [od 14 sierpnia](https://github.com/allegro/allegro-api/issues/2116) także dla [GET sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).

**Comment by PiotrFerenc** [comment]
nie mam takiego czegoś jak shippingRates.id w sale/offers/{offer}. Ewentualnie delivery.shippingRates

`
{
    "id": "8148020134",
    "name": "TŁUMIK ŚRODKOWY PASSAT B2 SANTANA 80-88 1.6-2.2 $",
    "category": {
        "id": "255660"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "127420",
            "valuesIds": [
                "127420_7"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p><b>PRZEDMIOTEM SPRZEDAŻY JEST:</b></p><p><b>ORYGINALNY</b>:</p><p><b>NOWY</b></p><p><b>TŁUMIK - WYDECH ŚRODKOWY</b></p><p><b>__________________</b></p><p><b>OZNACZENIE:</b></p><p><b>FERROZ 06.024</b></p><p><b>POLMOSTRÓW 30.15</b></p><p><b>___________________</b></p><p><b>NUMERY KATALOGOWE DOSTĘPNE NA STRONIE PRODUCENTA</b></p><p><b>___________________</b></p><p><b>ZASTOSOWANIE</b>:</p><p><b>VOLKSWAGEN</b></p><p><b>PASSAT B2 80-88</b></p><p><b>1.6 &nbsp;1.8 &nbsp;1.8i &nbsp;1.9 &nbsp;2.0 &nbsp;2.2</b></p><p><b>SANTANA 83-86</b></p><p><b>1.8 &nbsp;1.9 &nbsp;2.0</b></p><p><b>.</b></p><p><b>.</b></p><p>WB</p><p>LOK:SKLEP 204</p>"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://2.allegroimg.com/original/01f367/f12626694f7dbc9dad680d7ea692"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "images": [
        {
            "url": "https://b.allegroimg.com/original/01793c/7eee733f4a569926461b627cecab"
        },
        {
            "url": "https://2.allegroimg.com/original/01f367/f12626694f7dbc9dad680d7ea692"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "59.57",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 2,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": false
    },
    "delivery": {
        "shippingRates": null,
        "handlingTime": "PT24H",
        "additionalInfo": "",
        "shipmentDate": null
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "promotion": {
        "emphasized": false,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "DOLNOSLASKIE",
        "city": "Dzierżoniów",
        "postCode": "58-200"
    },
    "external": null,
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [],
        "validatedAt": "2019-08-27T21:30:29.228Z"
    },
    "createdAt": "2019-05-29T11:52:41Z",
    "updatedAt": "2019-08-27T21:30:29.731Z"
}
`

**Comment by PrzemyslawLukanowski** [comment]
Tak, chodzi o pole shippingRates.id w delivery, jak poniżej:

![Screenshot_8](https://user-images.githubusercontent.com/51473661/65040213-2a335c00-d954-11e9-8eda-8b552c238575.png)

**Comment by PiotrFerenc** [comment]
a co znaczy sytuacja którą ja mam czyli null ?

**Comment by PrzemyslawLukanowski** [comment]
Oznacza to, że do danej oferty nie został przypisany żaden cennik dostawy.

**Comment by PiotrFerenc** [comment]
Racja. Zostały przypisane opcje dostawy. Jak dodać takie opcje dostawy za pomocą REST API ?

**Comment by PrzemyslawLukanowski** [comment]
Najpierw metodą [GET na zasobie /sale/delivery-methods ](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET)pobierz identyfikatory i nazwy metod dostawy. Następnie skorzystaj z zasobu [POST /sale/shipping-rates/ ](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST), gdzie przekażesz odpowiednie, wcześniej pobrane, metody dostawy. Zapoznaj się z [fragmentem naszego poradnika](https://developer.allegro.pl/sale/#shipping-rates), tam szczegółowo opisaliśmy ten proces. Dodatkowo niedawno udostępniliśmy nowy zasób w REST API, dzięki któremu możesz [zarządzać ustawieniami dostawy.](https://github.com/allegro/allegro-api/issues/2218)

**Comment by PiotrFerenc** [comment]
Proszę powiedzieć czy jesteśmy w stanie (za pomocą api) użyć tej funkcjonalności 
![obraz](https://user-images.githubusercontent.com/30370747/65235261-8920de80-dad6-11e9-9f8e-6924ad0a53fa.png)

**Comment by PrzemyslawLukanowski** [comment]
Przez REST API jest to niemożliwe. Konieczne jest utworzenie cennika dostawy, tak jak opisałem to powyżej.

**Comment by PiotrFerenc** [comment]
Jak tworzę sobie taką aukcje to cennik który skonfiguruję za pomocą "wypełnij sposoby dostawy ręcznie" jest odejmowany z puli cenników ?

**Comment by PrzemyslawLukanowski** [comment]
Taki cennik nie jest odejmowany z puli cenników.

**Comment by PiotrFerenc** [comment]
czy opcja "wypełnij sposoby dostawy ręcznie" będzie kiedyś dostępna przez REST API ?

**Comment by PrzemyslawLukanowski** [comment]
Nie planujemy wdrożenia takiego zasobu. Chcemy, aby w przyszłości również na froncie konieczne było utworzenie cennika dostawy i dodanie go do oferty. Przypisane metody dostawy do oferty, także takiej, która nie posiada cennika dostawy, możesz sprawdzić za pomocą [GET sale/offers/{offer}/shipping-rates](https://developer.allegro.pl/documentation/#operation/getOfferShippingRatesGET).
