### ISSUE TITLE
Pobranie listy zamówień większej niż 100 / checkoutForms Question

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#2231]
Witam,

Obecnie pobierając response po stronie https://api.allegro.pl/order/checkout-forms/ , otrzymuję odpowiedź do 100 zamówień. W jaki sposób mogę zwiększyć otrzymywanie zamówień do np. 500?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [dokumentacją ](https://developer.allegro.pl/documentation/#operation/getOrderEventsStatisticsUsingGET) największa wartość dla tego parametru to 100. W zależności od potrzeby możesz skorzystać z [dziennika zdarzeń](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) z użyciem parametru "type" - limit dla tego zasobu to 1000.

**Comment by allmat** [comment]
Używając "type" muszę wiedzieć czy chce zakupione, w realizacji itp. 
Nie ma innego sposobu na pobranie wszystkich zamówień z różnymi statusami?

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem - limit liczby zamówień dla jednego wywołania w tym zasobie to 100.

**Comment by neldh** [comment]
@allmat Masz offset w żądaniu - możesz wykorzystać paginację, żeby pobrać więcej zamówień

**Comment by allmat** [comment]
neldh i to jest dobre rozwiązanie, faktycznie wystarczy dodatkowy response z offsetem 100 i będzie hulać. Chyba pomogłeś , dzięki :)
