### ISSUE TITLE
Nie działa filtr typów eventów GET /sale/offer-events

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2232]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym

:beetle: **Opis**
```
'https://api.allegro.pl.allegrosandbox.pl/sale/offer-events?limit=100&type=OFFER_ACTIVATED,OFFER_CHANGED,OFFER_ENDED,OFFER_STOCK_CHANGED,OFFER_PRICE_CHANGED' \
  -H 'Accept: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \ 
   
  RESPONSE 2019-09-17 14:40:41.5767373 Duration: 175,0066ms {
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "InvalidQueryParameterException",
        "Details": null,
        "Message": "Invalid parameter has been sent.",
        "Path": null,
        "UserMessage": "Niepoprawne zapytanie. Skontaktuj się z twórcą aplikacji."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": null,
  "TraceId": "c490533aa3de1be9",
  "Error": true,
  "StatusCode": 400,
  "Message": "{\"errors\":[{\"code\":\"InvalidQueryParameterException\",\"message\":\"Invalid parameter has been sent.\",\"details\":null,\"path\":null,\"userMessage\":\"Niepoprawne zapytanie. Skontaktuj się z twórcą aplikacji.\"}]}"
}
```
Dzień dobry, zgodnie z dokumentacją https://developer.allegro.pl/my_offers/#journal 

- type - podaj typ **eventów**, które chcesz uzyskać w odpowiedzi

chciałbym pobrać z dziennika wszystkie zdarzenia poza OFFER_ARCHIVED. Request jak wyżej nie działa tak jak to ma miejsce w przypadku listy ofert ze statusem:

`/sale/offers?publication.status=INACTIVE,ACTIVATING,ACTIVE,ENDED`

Proszę o umożliwienie użycia filtru type z wartościami po przecinku:

`/sale/offer-events?limit=100&type=OFFER_ACTIVATED,OFFER_CHANGED,OFFER_ENDED,OFFER_STOCK_CHANGED,OFFER_PRICE_CHANGED`

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie wspieramy wyszukiwania po wielu wartościach w tym zasobie. Przekazałem Twoją sugestię do odpowiedniego zespołu.
