### ISSUE TITLE
Program/skrypt do sciagania danych aukcji.

### ISSUE THREAD

**Issue by Dawidek990** [allegro/allegro-api#2233]
Witam, potrzebuje programu/skryptu który by ściągnął liste wszystkich aukcji uzytkownika ktorego mu wskaze. 

Potrzebuje tez programu ktory by umial sciagnac dane aukcji po linku, numerze, ew np wszystkie aukcje danego uzytkownika ktorego wskaze... w sensie tytul, opis, zdjecie i cene ;]
Ew bez zdjecia. 

Moze byc do pliku csv lub xml, ew jakiego kolwiek innego pliku :)

Ktos posiada moze takie rozwiazanie?

**Comment by crazyhtm** [comment]
Możemy się dogadać w tej sprawie. Kontakt [michal@crazyhtml.pl](mailto:michal@crazyhtml.pl)

**Comment by lukada4100** [comment]
Coś da się zrobić lukada4100@gmail.com
