### ISSUE TITLE
Błąd podczas próby usunięcia zestawu wariantów. DELETE /sale/offer-variants/

### ISSUE THREAD

**Issue by kamil-mazur-fpwd** [allegro/allegro-api#2234]
Witam,

Być może robię jakiś głupi błąd ale przy próbie usunięcia wariantu otrzymuję błąd:

```[errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/offer-variants/6e4b806c-ca0d-4c41-8187-543a452f990f
                    [userMessage] => 
                )

        )
```

Gdy dla tego samego linku zrobiłem GET'a to informacje o wariancie zostały zwrócone prawidłowo.

Dlaczego dla `DELETE` zwracany jest błąd? :) 

Requesty wykonywane były na `allegrosandbox`

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu. Czy występuje on tylko dla tego jednego wariantu, czy również dla innych? Czy możesz przesłać curl z requestem i responsem, jaki otrzymujesz, po wywołaniu GET?

**Comment by kamil-mazur-fpwd** [comment]
miałem głupi błąd w kodzie :) wszystko w porządku z API.

Pozdrawiam!
