### ISSUE TITLE
Obsługa zamówień

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#2235]
Mam kilka pytań co obsługi zamówień.

1. W przypadku niektórych zakupów jest kilka eventów *READY_FOR_PROCESSING* dla jednego checkout form. Co w takim przypadku może się zmienić? Jakieś dane adresowe, lista zakupionych przypadków? Pytam bo musimy jakoś reagować na ewentualne zmiany. 
2. Czy dopłata generuje jakiś event? Po przetestowaniu nie zauważyłem niczego takiego. Jak dojść do tego do których zamówień mamy dopłaty? Czy muszę wszystkie checkout form odpytywać i sprawdzać czy nie ma dopłat?
3. Czy może być więcej niż jedna dopłata dla danego zamówienia? Po dokonaniu jednej nie mam możliwości dokonania kolejnej. http://q.i-systems.pl/file/295a809c.png natomiast w api dopłaty są tablicą. ` "surcharges": [],                                        -- informacje o ew. dopłatach`

Pytania na podstawie testów w środowisku sandboxowym.

**Comment by PrzemyslawLukanowski** [comment]
1) Dane adresowe w przypadku tego statusu już nie mogą się zmienić. Allegro działa na strukturze rozproszonej, dlatego event READY_FOR_PROCESSING dla tego samego zamówienia może występować więcej niż raz. Ponadto dodatkowy event pojawia się w przypadku dopłaty. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#02),
2) Dopłata generuje dodatkowy event READY_FOR_PROCESSING. Informacja o tym, czy dane zamówienie zawiera dopłata, znajduje się w polu surcharges dla zasobów GET order/checkout-forms i GET order/checkout-forms/{checkoutFormId},
3) Na ten moment nie można wykonać więcej niż jedną dopłatę.

**Comment by manhunto** [comment]
1. Czyli reasumując..  w przypadku drugiego i kolejnego eventu *READY_FOR_PROCESSING* mogę spodziewać się zmian TYLKO w surcharges? Pytam ponieważ muszę jakoś reagować na ten event i nie wiem jakie dane mogą się zmienić. Czy coś jeszcze oprócz tego może się zmienić i powinienem jakoś na to reagować? Z poradnika wynika że trzeba tylko "sprawdzić czy zgadza się kwota płatności".

2. Przy poźniejszych testach faktycznie ten event pojawił się dla dopłat ale musiałem trochę na niego poczekać.

**Comment by PrzemyslawLukanowski** [comment]
Tak, jedyna zmiana jaka może wystapić w zamówieniu to dopłata, dane w FOD już się nie zmienią.

**Comment by manhunto** [comment]
Bardzo dziękuje za odpowiedzi. Nasuneła mi się jeszcze jedna kwestia.

4. Załóżmy że mam dwa konta sprzedających **A** i **B** oraz konto kupującego **K**. **K** kupuje na aukcjach obu sprzedających i wypełnia tylko jeden formularz dostawy dla zakupów z obu kont. Czy dla konta **A** i **B**:

- będzie jeden i ten sam id dla całego formularza czy powstaną dwa niezależne?
- jeśli będzie z tym samym ID to czy dostane takie same informacje pobierając checkout forma? chodzi mi o głównie o płatność, lineItems

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku powstaną dwa niezależne checkout formy o różnych id.

**Comment by manhunto** [comment]
@PrzemyslawLukanowski Pojawił się przypadek opisany w punkcie 4 i dostałem dwa checkout formy z tym samym id. Prośba o wyjaśnienie jak to faktycznie jest.  Różnią się one line itemami.

Przykładowe checkout formy które są stworzone dla minimum dwóch kont sprzedających.
- d3a2396c-c90e-11e9-86a8-1f443f537b68
- 75f5b999-ccf6-11e9-bbe7-eb94b2c14bb3
- a497c486-d27f-11e9-9102-f37694d5326d

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach znalazłem próby pobrania tych zamówień tylko przez jednego usera (inny dla każdego zamówienia). Czy możesz wskazać id kont, którzy są właścicielami tego samego checkout-forma?

**Comment by manhunto** [comment]
> Czy możesz wskazać id kont, którzy są właścicielami tego samego checkout-forma?

Weryfikując to nie zauważyłem, że te id są bardzo do siebie podobne.. nie dochodzi tutaj do żadnych duplikatów. Mają one jedynie wspólne transactionId

Przykład 
* d3a2396c-c90e-11e9-86a8-1f443f537b68 konto 45391386
* d3a23969-c90e-11e9-86a8-1f443f537b68 konto 12038671

**Comment by PrzemyslawLukanowski** [comment]
Tak, transactionId w WebAPI może być wspólne dla różnych zamówień.
