### ISSUE TITLE
GET /offers/listing - nieprawidłowe zachowanie filtra

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#2237]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zauważyliśmy, że w niektórych kategoriach nie działa prawidłowo filtr STAN
np. 
```
GET /offers/listing?phrase=audi&category.id=50850&searchMode=REGULAR&limit=100&sort=%2bprice&fallback=false&sellingMode.format=BUY_NOW&option=0&parameter.11323=1&price.from=1000%2c0000&include=all&offset=0 HTTP/1.1
```
 (STAN = NOWE (value=11323_1)) zwraca oferty ze stanem Używane np. 8492380246, 8492353137

https://pastebin.com/CWqUxRxK

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, filtr działa prawidłowo. Widzę, że dla filtru **parameter.11323** przekazana jest wartość **1**, tymczasem powinna być **11323_1**, jak w filtrach na końcu response:

![Screenshot_6](https://user-images.githubusercontent.com/51473661/65232419-65a76500-dad1-11e9-93f7-979b946fdb4a.png)

**Comment by rtnet-pl** [comment]
@PrzemyslawLukanowski Faktycznie działa. Co ciekawe stary format (sam ID wartości) działał do ostatnich zmian. Dzięki

**Comment by crazyhtm** [comment]
A były jakieś zapowiedzi że to zmienią?

Jeszcze wczoraj było wszystko po staremu ! A dziś rano ściągnęło mi  ponad 60 000 nowych aukcji. HAHAHA 

Co ciekawe w opisie REST API do dziś widnieją stare identyfikatory !!!  Jako główny przykład.

**Comment by PrzemyslawLukanowski** [comment]
Z racji tego, że była to poprawka, która eliminowała wcześniejsze problemy z poprawnym działaniem filtrów, zdecydowaliśmy się na komunikat bezpośrednio po wdrożeniu. W najbliższym czasie zaktualizujemy przykłady na stronach REST API. Zmiana jest kompatybilna wstecz, przede wszystkim zależało nam na szybkim rozwiązaniu problemu.
