### ISSUE TITLE
Dla metody "Poczta Polska - Odbiór w Punkcie" - walidacja, czy numer telefonu jest komórkowy.

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2238]
:bulb: **Sugestia**

Aktualnie tam są też numery stacjonarne. I później już na etapie obsługi takich zamówień trzeba się kontaktować z klientami z prośbą o podanie numeru. Fajnie, gdyby ta walidacja była po stronie Allegro, przed zatwierdzeniem formularza zakupowego. API poczty nie pozwala na pominięcie numeru mobilnego (tj. sam e-mail) w przypadku odbioru w punkcie.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię, przekazałem ją do odpowiedniego zespołu.
