### ISSUE TITLE
Compatibility list - błędnie zwracane numery ktype.

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2239]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**
Mamy pewien produktu, do którego chcielibyśmy wprowadzić dwie pozycje pasuje do. Są to dwa numery ktype: 17902 i 33361. O ile jeden z nich jest rozpoznawany poprawnie, drugi owszem zwraca id i nazwe po odpytaniu: /sale/compatible-products?type=CAR&tecdoc.kTypNr=.. . Aczkolwiek po wrzuceniu tych dwóch numerów do aukcji, tylko jeden jest rozpoznawany poprawnie. Drugi świeci się cały czas na czerwono. W czym problem?

**Comment by PrzemyslawLukanowski** [comment]
Dla GET sale/compatible-products?type=CAR&tecdoc.kTypNr=33361 nie zwracamy żadnego wyniku, dlatego występuje problem. Jaką wersję tecdoca posiadasz i jakie auto widnieje pod tym k.type w Twojej bazie?

**Comment by ponowemu** [comment]
@PrzemyslawLukanowski rzeczywiście jeden z w/w dwóch numerów nie jest obsługiwany. Seat Altea (5P1) 1.9 TDI, aczkolwiek jest to numer spoza polskiego regionu. Czy mam rozumieć więc, że obslugiwane są tylko polskie numery?

**Comment by ponowemu** [comment]
Tecodc w aktualnej wersji, na obecny kwartał.

**Comment by PrzemyslawLukanowski** [comment]
@ponowemu Tak, mamy tylko samochody dopuszczone do sprzedaży na rynku polskim.

**Comment by ponowemu** [comment]
@PrzemyslawLukanowski  Co w sytuacji gdy prowadzę sklep z częściami do aut amerykańskich? Mając na względzie, że jednocześnie nakazujecie korzystać z Pasuje Do w nowym formacie?

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli przekazanie takich numerów jest niemożliwe w sekcji "Pasuje do", pozostaje umieszczenie tych informacji w opisie oferty.
