### ISSUE TITLE
częsty błąd ERR_INVALID_ITEM_ID

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#224]
Dzień dobry, 

Przy pobieraniu wystawionej wcześniej oferty(doShowItemInfoExt) zdarza się, że dostajemy błąd:
ERR_INVALID_ITEM_ID - 'Niepoprawny identyfikator aukcji lub wskazana aukcja została przeniesiona do archiwum.'
Ostatnio od poniedziałku błąd ten pojawia się zdecydowanie częściej niż wcześniej.

Oferta oczywiście jest wystawiona i dostępna, a przy ponownej próbie pobrania za ~10min nie ma już problemu. W jakich przypadkach może taki błąd pojawiać się?
Przykład: oferta 7348403703 próba pobrania ~ 2018-05-15 11:16:53

**Comment by MartaNowaczyk** [comment]
Błąd może się pojawić w momencie kiedy oferta nie jest jeszcze widoczna w serwisie. Tak też było z podaną w przykładzie ofertą - nie minęła nawet minuta od wystawienia, gdy próbowaliście ją pobrać. Pamiętajcie, że oferta pojawia się w allegro do 60 minut od momentu jej wystawienia.
