### ISSUE TITLE
Obsługa Allegro Dostawa przez api

### ISSUE THREAD

**Issue by michalkowalik97** [allegro/allegro-api#2240]
Dzień dobry, 
Chciałbym zapytać czy istnieje możliwość obsługi funkcji Allegro Dostawa przez rest api? Najbardziej zależy mi na możliwości pobierania etykiet dla paczek.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli masz na myśli odpowiednik funkcjonalności Zamówienia -> Nadaj przesyłkę kurierem, to niestety przez REST API jest to niemożliwe.

**Comment by michalkowalik97** [comment]
Tak, mam na myśli odpowiednik tej funkcjonalności, potrzebuję pobierać etykiety paczek. Czy jest w planach wprowadzenie w przyszłości obsługi tej funkcjonalności?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy dodania takiej funkcjonalności.
