### ISSUE TITLE
Allegro zmieniło  TYP DANYCH  w odpowiedzi na GET /offers/listing

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2243]
ALLEGRO zmieniło typ danych ze STRINGA na DOUBLE (liczba):
BYŁO:

"sellingMode": {
    "price": 
{    "amount": "123.45" 

JEST:

"sellingMode": {
    "price": 
{    "amount": 123.45

To samo jest w "delivery" !!! 
Nie wiem gdzie jeszcze. Ale pewnie wyjdzie w praniu.

Ciekawe czy była zapowiedź? W dokumentacji oczywiście nic się nie zmieniło. STRINGI jak były tak są !!!

**Comment by mareklemur** [comment]
Potwierdzam, zmiana wprowadzona wczoraj po 11:00. Bez zapowiedzi, bez aktualizacji dokumentacji.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, zgłosiłem to do odpowiedniego zespołu. Wprowadzimy poprawkę, która zwraca typ danych zgodny z dokumentacją.

**Comment by mareklemur** [comment]
A kiedy? Musimy dostosować oprogramowanie.

**Comment by PrzemyslawLukanowski** [comment]
Dzisiaj wdrożymy poprawkę.

**Comment by crazyhtm** [comment]
**Czyli znowu zmienicie typ danych na STRING?**

**Comment by j4r3kb** [comment]
I to nie jedyna ninja zmiana w ostatnim czasie https://github.com/allegro/allegro-api/issues/2250

To jest API produkcyjne czy jakiś sandbox dla waszych deweloperów?

**Comment by PrzemyslawLukanowski** [comment]
@crazyhtm Zmiana typu danych była wynikiem błędu, przepraszamy, przywróciliśmy już stary typ danych.

**Comment by frankii91** [comment]
to chyba nie pierwszy raz taki przypadek :) czemu nie robicie validacji aktualizacji dokumentacją przed wprowadzeniem ?

oraz skoro sami w dokumentacji macie wersjonowanie api/metod to czemu z tego nie korzystacie ?

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem - zmiana typu danych była wynikiem naszego błędu, wprowadziliśmy już typ zgodny z dokumentacją
