### ISSUE TITLE
Nie wiem co jest grane ? [REST API]

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#2245]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Nie dziala wystawienie aukcji, zwracany jest błąd:

Assigned valueId 127511_20 for dictionary parameter 127511 is not found.

Request:

{"id":"numer","name":"KLOCKI HAMULCOWE ","category":{"id":"19043"},"parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"127511","valuesIds":["127511_20"]}], 
......}

Jeżeli wejdę w taki szkic po strnie panelu allegro to panel wystawi się bez problemu nic nie zmieniając, oczywiście producent jest ustawiony już na "Inny" ?! Skoro UI potrafi to wystawić czemu DI nie potrafi ?

**Comment by PrzemyslawLukanowski** [comment]
Komunikat wprowadza w błąd, zwróć uwagę, że w rzeczywistości w response otrzymałeś status 200, a parametr został zwrócony z nową, prawidłową wartością - 127516_13 (inny). Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by keczerad** [comment]
Można wiedzieć na czym dokłądnie polega Wasz błąd ? Rozumiem, że zmieniliście znowu ientyfiaktory producentów i blokujece poprawnie dodawanego producenta o nazwie INNY ?

**Comment by PrzemyslawLukanowski** [comment]
Po mergowaniu parametrów wartość "INNY" kryje się pod "127516_13". Nie do końca blokujemy - w odpowiedzi otrzymałeś status 200 i zaktualizowaną wartość parametru. Więcej informacji w naszym [newsie](https://github.com/allegro/allegro-api/issues/2160).  Zwracany komunikat wprowadza w błąd - "Assigned valueId 127511_20 for dictionary parameter 127511 is not found.", ponieważ w rzeczywistości nie uniemożliwia to wystawiania oferty.

**Comment by keczerad** [comment]
Nie do końca blokujecie, może i tak, ale nie pozwalacie wystawić oferty wieć jak zrobić zeby było dobrze ?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę wystarczy skopiować całą strukturę, jaką otrzymujemy w response, i przesłać ją ponownie przez PUT sale/offers/{offerId}.

**Comment by keczerad** [comment]
I tak 5000 razy ?!

**Comment by PrzemyslawLukanowski** [comment]
Problem został już zgłoszony do odpowiedniego zespołu, pracujemy nad rozwiązaniem.

**Comment by keczerad** [comment]
Teraz konkretniej kiedy to naprawicie ?

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem, pracujemy nad rozwiązaniem problemu. Poinformuję, jak tylko uda się coś ustalić.

**Comment by keczerad** [comment]
Czy zostało to już naprawione, problem się pogłębia coraz wiecej osób ma z tym problemy !

**Comment by PrzemyslawLukanowski** [comment]
Problem jeszcze nie został rozwiązany. Przekażę informację po jego wyeliminowaniu.

**Comment by keczerad** [comment]
Oki, widziałem u klienta że teraz już producenci zostają wysyłani tak jak chcecie, czyli rozumiem że podminiliście ID i teraz api już "wystawia" prawie dobrze.

Pytanie jest inne. Testowo sprawdziliśmy z klientem kilka Aukcji z tej samej kategorii i z tymi samymi identyfikatrami producentów. Efekt jest taki że po pierwszym wysłaniu z 10 aukci nie wystawiło się 3, kolejne wysłanie nic nie zmieniło czyli dalej 3 akuckje pozostawały szkicem, wszystko sprawdzałem na Fiddlerze i nie zwracaliście żadnych błędów, natomiast cały czas zwracaliście status aukcji INACTIVE, po czwartej próbie  wysyłałem to pod spodem:

Wysyłka oczywiście skrócone zapytanie:
{"id":"xxxxxx7719","name":"TARCZA HAMULCOWA PRZÓD YAMAHA XJ 600 DIVERSION 98-","category":{"id":"19046"},"parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"127511","valuesIds":["127516_13"]}],""external":{"id":"CMCBD-825-SOF"},"updatedAt":"2019-10-04T09:29:31.5856702+02:00"}

Zwrot:
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: f65bab847547dda7
date: Fri, 04 Oct 2019 07:29:31 GMT
x-ratelimit-remaining: 8977
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 636
Content-Length: 8506

{"id":"xxxx7719",""category":{"id":"19046"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"127511","valuesIds":["127516_13"],"values":[],"rangeValue":null}],,"validation":{"errors":[],"validatedAt":"2019-10-04T07:29:32.077Z"},"createdAt":"2019-10-04T06:49:33.000Z","updatedAt":"2019-10-04T07:29:32.077Z"}

Piąta próba odpowiedz:
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 384ca2a0d2ab2eac
date: Fri, 04 Oct 2019 07:31:27 GMT
x-ratelimit-remaining: 8930
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 55
Content-Length: 8530

{"id":"xxxx7719","category":{"id":"19046"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"127511","valuesIds":["127516_13"],"values":[],"rangeValue":null}],"publication":{"duration":null,"status":"ACTIVATING","startingAt":"2019-10-04T07:31:00.000Z","endingAt":null,"endedBy":null,"republish":false},"validation":{"errors":[],"validatedAt":"2019-10-04T07:29:32.077Z"},"createdAt":"2019-10-04T06:49:33.000Z","updatedAt":"2019-10-04T07:31:20.138Z"}


I nagle aukcja się aktywowała, czemu dlacego nie ma na to logicznego wytłumaczenia, losowość działania api sprawia że zwyczajnie nie działa to prawidłowo, także proszę o weryfikację ewentualnie odpowiedź dlaczego tak się dzieje. Na jeszcze dzisiaj przekazę informację czy klientowi udało sie w dniu dzisijszym aktywować 6 tysięcy aukcji, czy dalej zachowuje się to nieracjonalnie. 

Powiem tak, istnienie metody /sale/offer-publication-commands uważam za zbędną ! Metoda ta z mojej perspektywy powoduje niepotrzebne dodatkowe dwa zapytanie HTTP, przy jednym kliencie który wystawia 30 tysięcy aukcji robi się z tego 90 tysięcy teraz pytanie ile takich zapytań wykonuje reszta developerów pewnie idzie to w setkach milionów a Wasze serwery cierpią. W dodatku meteda nie zwraca wartościowych danych w zasadzie wogole nic nie zwraca danych oprócz samych zer ! Istnienie tej metody, która nic nie zwraca powoduje  odpytanie o aukcje ponownie czy czasami nie zmieniała statusu, przecież to jakaś paranoja, jakby nie można było podać statusu przy tworzeniu oferty. Zaraz powiecie, że można wysłać oferty na raz, tyle tylko że jak to tak działa jak obecnie to strach to robić, tak przyjmnie ryzyko niewystawienia aukcji obnizą sie zwiekszajać co prawda liczbe zapytań, ale to wypowinniście nad tym panować i tylko pozosaje się modlić a nuż się uda choć 5 z 10 się wystawi :). Nowe API miało działać lepiej w sumie to zmieniliście technologie na "nowocześniejszą" zmusiliście do wytworzenia tysięcy jak nie milionów godzin develoeprskich za które zapłacili klienci i to by było na tyle co się zmieniło bo obsługa tego API dalej naprawdę pozostawie dużo do życzenia. Zmieniliście nowe API tylko Wasz sposób działanie i myślenia pozostał na niezmienionym poziomie a szkoda.

**Comment by PrzemyslawLukanowski** [comment]
Czy dla pierwszych czterech prób sprawdziłeś, jaki komunikat otrzymałeś w odpowiedzi dla [GET sale/offer-publication-commands/{uuid}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) ?

**Comment by keczerad** [comment]
Sugeruje Pan, że mam wywołać jeszcze inną metodę  GET sale/offer-publication-commands/{uuid}/tasks, która to sprawdza co wywołuje metoda  /sale/offer-publication-commands ? Ja zadam pytanie poco mam ją wywoływać, czy nie możecie zwrócić komunikatu w tejże metodzie że coś poszło nie tak u Was, zeby nie trzeba było wywoływać innej metody ?

**Comment by PrzemyslawLukanowski** [comment]
PUT sale/offer-publication-commands/{uuid} działa asynchronicznie, w responsie zawsze będa same zera, ponieważ w tak krótkim czasie nie jest możliwe, aby już w odpowiedzi na request widniała informacja o statusie zadania. Dlatego też konieczne jest skorzystanie z GET sale/offer-publication-commands/{uuid}/tasks, gdzie znajduje się konkretna informacja wraz ze wskazaniem błędu (w przypadku tasków ze statusem FAIL).

**Comment by keczerad** [comment]
Skoro metoda działa asynchornicznie, to nawet jeżeli za chwilę wywołam metodę ET sale/offer-publication-commands/{uuid}/tasks to przecież i tak to nic nie da prawda ? W dodatku wywołanie metody asynchornicznej cztero krotnie nie przyniosło skutku a piąty raz przyniósl, dlatego wszystkie znaki na niebie i ziemi mówią że błąd jest po Waszej stronie, także może państwo pocylicie się nad tematem i sprawdzicie tylko tak na poważnie czyli na dużych danych a nie na jednej aukcji w sanboxie bo to zawsze się udaje !

**Comment by PrzemyslawLukanowski** [comment]
Zasób GET sale/offer-publication-commands/{uuid}/tasks zwróci aktualną informację na temat statusu zadania. Czy posiada Pan przykładowe trace-id lub numery uuid dla tasków, które nie aktywowały oferty?

**Comment by keczerad** [comment]
Komunikat z metody tasks "Could not change offer publication status. You cannot schedule activating an offer in the past.". Niestety jak dla mnie jest nie czytelny bo nie ma powodu podania dlaczego tak się dzieje, co ciekawe nie jest też prawdziwy bo za 10 minut udało mu się jednak tą aukcję aktywować.

**Comment by PrzemyslawLukanowski** [comment]
Czy mogę prosić o przykładowe trace-id lub numery uuid dla tasków, które nie aktywowały oferty?

**Comment by keczerad** [comment]
Problem w tym, że od wczoraj albo macie mniejsze obciążenie przy wystawieniu aukcji, albo nastąpiło cudowne "uzdrowienie" i trzeba czekać naprawdę sporo żeby trawfić na tą aukcję, kiedy jeszcze przed wczoraj praktycznie co druga generowała błędy.

**Comment by keczerad** [comment]
aukcji 8565914652. UUID: C51E6F05-1D85-426E-83D6-DC7F949436DA, Opis: Could not change offer publication status. You cannot schedule activating an offer in the past.

 aukcji 8527864413. UUID: B450C4CB-2E48-4FC4-BC0D-7787DB496D01, Opis: Could not change offer publication status. You cannot schedule activating an offer in the past.

 aukcji 8527806425. UUID: FD816AD3-268B-428A-BF50-B98B7B540754, Opis: Could not change offer publication status. You cannot schedule activating an offer in the past.

aukcji 8527837104. UUID: 1CE43165-BE76-4B5D-8926-FD5AC714FD0A, Opis: Could not change offer publication status. You cannot schedule activating an offer in the past.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje za przykładowe numery UUID. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
W powyższych przypadkach oferty mają być wystawione natychmiast, ale wypełnia Pan czas do wystawienia, tak jakby były zaplanowane. Czas ten jest w tej samej minucie, co wychodzi zlecenie na aktywację. W momencie wywołania komendy aktywacji oferty, data zaplanowania jest już w przeszłości. Jeśli chce Pan planować wystawianie ofert, powinien Pan wtedy ustawić datę w przyszłości. Jeżeli chce Pan wystawić ją teraz, wtedy pole scheduledFor powinno być null.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku może Pan także pominąć (usunąć) to pole, wtedy także zostanie to przekonwertowane na wartość null. Zachęcam także do zerknięcia do [naszego poradnika](https://developer.allegro.pl/sale/#step-9-offer-publication-commands), informujemy tam o tym, że pole jest niewymagane.
