### ISSUE TITLE
Pobieranie danych z zamówienia

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#2246]
Poniższe dane zostały pobrane z zamówienia Allegro, oczywiście bez "xxx".

[id] => xxx
    [email] => xxx
    [login] => xxx
    [firstName] => xxx
    [lastName] => xxx
    [companyName] => 
    [guest] => 
    [personalIdentity] => 
    [phoneNumber] => ------------------------------
    [address] => Array

Skąd pomysł by pozwalać na "------------------------------" w numerze telefonu? Dlaczego tego typu dane nie są formatowane do samych cyfr?

**Comment by kuli-g** [comment]
@unkn0wn0 allegro nie przeprowadza żadnych walidacji wprowadzonych danych (czy nawet kompletności bo często dostaję adresy bez numerów domu) czy to adresu czy telefonu, to jest dla nich za trudne więc jest na głowie sprzedającego

**Comment by PrzemyslawLukanowski** [comment]
Aktualnie przeprowadzamy walidację numeru telefonu zarówno dla danych konta, jak i przy zamówieniu. Powyższy przypadek prawdopodobie dotyczy starszych aplikacji mobilnych.
