### ISSUE TITLE
Problem z wystawianiem ofert i produktyzacją

### ISSUE THREAD

**Issue by TomekDuszynski** [allegro/allegro-api#2248]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Tworzenie oferty powiązanej z produktem zwraca ID oferty oraz informację, że została wystawiona jednak po wejściu w ofertę jest informacja, że nie istnieje. 
Oferty nie ma na sandboxie także na koncie użytkownika (nawet w szkicach).
Przykładowy numer oferty: 6206586121

**Comment by PrzemyslawLukanowski** [comment]
W przypadku wystawionej oferty (w statusie ACTIVE) nie udało mi się powtórzyć tego błędu. Czy Twój błąd nie jest tożsamy z #2241?

**Comment by TomekDuszynski** [comment]
Rzeczywiście problem jest z draftami i ich widocznością na liście.
Zatem problem mamy z tym, że oferta wpadła do drafta przez dziwny błąd:

![image](https://user-images.githubusercontent.com/52100383/65321989-f0599400-dba5-11e9-9582-2b8cbe27a667.png)

My przekazujemy podczas tworzenia drafta wartość "0.60", a dopiero po stronie allegro widać wartość "0.6".

Zgłosić to w osobnym wątku?

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, występuje taki błąd. Nowego wątku nie trzeba zgłaszać, przekażę ten problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@TomekDuszynski Zasób powinien działać już prawidłowo, prośba o weryfikację.

**Comment by TomekDuszynski** [comment]
@PrzemyslawLukanowski działa ale z tego co widzę to teraz zawsze powinniśmy przekazywać wartość "0.6" bez nadmiarowego zera.

**Comment by PrzemyslawLukanowski** [comment]
@TomekDuszynski Zgadza się, edytowaliśmy tę wartość, sprawdzisz to za pomocą GET sale/products?ean=9780000000057.
