### ISSUE TITLE
Problem z wystawianiem oferty/draftu

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#2249]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Po wystawieniu draftu (trace-id: f7b94ca994219f7e) i otrzymaniu w odpowiedzi numeru oferty próbowaliśmy ją publikować (trace-id: 789495fc8748f43d). Po sprawdzeniu statusu (UUID: 934de5e0-42f1-44c8-bdfc-105cfb0ad610) otrzymaliśmy odpowiedź:

"errors":[
   {
      "code":"OfferNotFoundException",
      "message":"[Lpl.allegro.tech.common.andamio.errors.jersey.exceptions.ErrorTemplate;@23251d66",
      "details":"OfferNotFoundException"
   }

Problem polega na tym, że po wysłaniu draftu dostaliśmy poprawną odpowiedź z numerem oferty/draftu. A chwilę potem okazuje się, że takiej oferty/draftu jednak nie ma. Dodam, że to nie jest pojedynczy problem. Takie sytuacje pojawiają się od czasu do czasu.

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by tomylee0** [comment]
Bardzo dziękuję za odpowiedź. Teraz zwróciłem uwagę na ponad minutowy odstęp pomiędzy scheduledAt a finishedAt dotyczący publikacji oferty:

{
  "id": "934de5e0-42f1-44c8-bdfc-105cfb0ad610",
...
      "scheduledAt": "2019-09-19T19:38:38.934Z",
      "finishedAt": "2019-09-19T19:39:41.085Z",
...
}

Skrótowo wyjaśnię. Wysłałem szkic. Odpowiedź o przyjęciu szkicu przyszła do mnie o:
2019-09-19 21:38:38.785 trace-id: f7b94ca994219f7e

Wysłałem zaraz potem publikację i odpowiedź o przyjęciu taska publikowania przyszła o:
2019-09-19 21:38:38.922 trace-id: 789495fc8748f43d

Wg tego co mamy w opisie taska task publikowania po stronie allegro rozpoczął się minutę po moim wysłaniu żądania do publikowania. Ten wystawiony przeze mnie szkic był ostatnim w mojej serii. Zaraz potem po mojej stronie uruchamia się funkcjonalność do usuwania ofert które są w stanie INACTIVE po to aby nie zostawiać niepotrzebnie nieużywanych szkiców. A ten szkic nie zdążył się jeszcze uaktywnić i po odpytaniu allegro o wszystkie INACTIVE numer szkicu pojawił się w odpowiedzi i tym samym został usunięty przez tą funkcjonalność.

Zatem korzystając z okazji chciałbym zapytać jak maksymalnie długo może trwać publikowanie oferty? Czyli jakiej maksymalnej różnicy pomiędzy "finishedAt" a "scheduledAt" możemy się spodziewać?

Dziękuję za pomoc i pozdrawiam serdecznie.

**Comment by PrzemyslawLukanowski** [comment]
@tomylee0 - może to potrwać do godziny.
