### ISSUE TITLE
doMyBillingItem, timestamp?

### ISSUE THREAD

**Issue by jerzakm** [allegro/allegro-api#225]
Do tej pory ręcznie ściągałęm CSV dostępne w
allegro.pl/billinghistory/#/history

doMyBillingItem oferuje prawie taką samą funkcjonalność ale niestety brakuje w odpowiedzi jakiegoś timestampa co niestety uniemożliwia odpowiedniego przypisanie danych. Czy może coś przeoczyłem czy taka funkcja nie jest obecnie dostępna?

**Comment by MartaNowaczyk** [comment]
Tak jak napisałeś, nie ma takiej możliwości w tym wypadku.
