### ISSUE TITLE
Zmiana formatu daty bez ostrzeżenia na zasobie /sale/offers

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#2250]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

trace-id: e960f7975bbde4d4

Dziś uległ zmianie format dat zwracanych w w/w zasobie, otrzymujemy daty w formacie jak niżej. Używamy JMS Serializera który w takiej sytuacji rzuca wyjątkiem. Proszę o przywrócenie poprzednich formatów lub oficjalną decyzję jak będzie od teraz.

```
  "createdAt":"2019-09-20T07:20:55.000Z",
  "updatedAt":"2019-09-20T07:56:42.877Z"
```

createdAt wcześniej było jako `Y-m-d\TH:i:sO` teraz jest adekwatnie do updatedAt czyli `Y-m-d\TH:i:s.uT`

**Comment by PrzemyslawLukanowski** [comment]
Ujednoliciliśmy format daty zgodnie z sugestią z #1856.

**Comment by j4r3kb** [comment]
Cieszymy się bardzo, szkoda że bez ostrzeżenia, teraz musimy hotfixy na produkcji wprowadzać...

**Comment by j4r3kb** [comment]
@PrzemyslawLukanowski czy poprawka dotyczyła również pól w odpowiedzi:
- validation.validatedAt
- publication.startingAt
- publication.endingAt
- delivery.shipmentDate
?

**Comment by PrzemyslawLukanowski** [comment]
Tak, poprawka objęła również te pola.

**Comment by j4r3kb** [comment]
Analogiczna sytuacja jest obecnie na zasobie: /sale/offer-events - pole `occurredAt`

traceid: `b4eb814c327ae5a7`

```
offerEvents":[{"id":"MTU3MzczMzk0NDU1MzczNQ","type":"OFFER_STOCK_CHANGED","occurredAt":"2019-11-14T12:18:52.077Z","offer":{"id":"6206650207","publication":null}},{"id":"MTU3MzczMzk1NTI4MTE0NQ","type":"OFFER_ENDED","occurredAt":"2019-11-14T12:18:51Z","offer":{"id":"6206650207","publication":{"endedBy":"EXPIRATION"}}},{"id":"MTU3MzczNDA5MjI1MzQzNg","type":"OFFER_ENDED","occurredAt":"2019-11-14T12:21:21Z"
```

**Comment by PrzemyslawLukanowski** [comment]
@j4r3kb Dziękuję za zgłoszenie - zauważyliśmy rozbieżność w formacie daty - przykładowo OFFER_ACTIVATED i OFFER_ENDED zwraca krótki format, np. 2019-11-15T08:57:32Z, natomiast OFFER_PRICE_CHANGE zwraca już format dłuższy - 2019-11-15T08:57:32Z. Weryfikujemy ten temat.

**Comment by PrzemyslawLukanowski** [comment]
Zastosowany przez nas format daty pozwala na taką rozbieżność. Dlatego przy niektórych eventach (np. OFFER_PRICE_CHANGE lub OFFER_CHANGE) otrzymasz datę wraz z nanosekundami, a przy innych (np. OFFER_ACTIVATED lub OFFER_ENDED) format będzie już krótszy.

**Comment by j4r3kb** [comment]
Nie dawno ujednolicali Państwo (komentarze wyżej) te formaty, a teraz ponownie będzie na zmianę? Używając JMS Serializer nie możemy mieć takich danych, format jest jeden możliwy do ustawienia.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten temat do odpowiedniego zespołu w celu analizy.
