### ISSUE TITLE
[REST]: Czy dla adresu powrotu dla aplikacji - zmienią się wymogi??

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#2251]
Czy przewidujecie następujące zmiany dla adresu powrotu i od kiedy:
- konieczność połączenia w warstwie SSL / TLS ?
- weryfikacja ważności certyfikatu dla domeny adresu ?

**Comment by PrzemyslawLukanowski** [comment]
Nie planujemy wprowadzać tutaj żadnych zmian.  Chcemy w ten sposób dać większą swobodę w działaniu integracji (można np. zrobić przekierowanie na localhost dla aplikacji odpalanych na desktopie).

**Comment by FromAnyHole** [comment]
@PrzemyslawLukanowski - dzięki, w sumie Ok, ale nie zmieniajcie zdania w tej sprawie.
