### ISSUE TITLE
sale/offers błąd 400

### ISSUE THREAD

**Issue by bjatwork** [allegro/allegro-api#2253]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

 
  

od dzisiaj zaczęliśmy dostawać błędy 400 dla przy próbie wystawienia ofert. 

POST /sale/offers HTTP/1.1 Host: api.allegro.pl Authorization: Bearer  XXX  accept: application/vnd.allegro.public.v1+json content-type: application/vnd.allegro.public.v1+json Content-Length: 5233 Expect: 100-continue

request json

{"name":"Buty zimowe New Balance 754 sk\u00f3ra czarne 41,5","afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"da01a198-e738-4efa-a511-0cd5623ad45a"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"category":{"id":"55207"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"delivery":{"shippingRates":{"id":"88e9e2b1-00c0-45a9-b150-b66a6576f00e"},"handlingTime":"P3D","additionalInfo":"","shipmentDate":""},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11a912\/55ea050d452ca798c9a1cac29bb8"},{"url":"https:\/\/a.allegroimg.com\/original\/11e37d\/b04dee9148d4b8697d5b9fc8e69f"},{"url":"https:\/\/a.allegroimg.com\/original\/11035f\/d5e69d2f407db0c757d72dcd1d64"},{"url":"https:\/\/a.allegroimg.com\/original\/11a7d8\/03908ee948b5bb993724b71f678c"},{"url":"https:\/\/a.allegroimg.com\/original\/118a35\/90deec984fe6b89b87015463f62c"},{"url":"https:\/\/a.allegroimg.com\/original\/11f288\/9260d2654bd48623c1e80ef30fdf"},{"url":"https:\/\/a.allegroimg.com\/original\/114887\/a72b4f3d4c92b92d4f9fef3404f7"},{"url":"https:\/\/a.allegroimg.com\/original\/11e7c2\/8a0f53834706bab45b56171a64c7"},{"url":"https:\/\/a.allegroimg.com\/original\/112422\/51465f1343419a518dadc418e5ea"}],"description":{"sections":[{"items":[{"type":"TEXT","content":"
Buty zimowe New Balance 754 sk\u00f3ra czarne 41,5 <\/h1>
Kolor czarny<\/li>
Typ obuwie, buty za kostk\u0119<\/li>
Marka New Balance<\/li>
Model 754<\/li>
Kolor producenta Black<\/li>
Kolekcja jesie\u0144\/zima 2018<\/li>
Materia\u0142 zewn\u0119trzny sk\u00f3ra naturalna<\/li>
Materia\u0142 wewn\u0119trzny tekstylia<\/li>
Materia\u0142 podeszwy tworzywo sztuczne<\/li>
P\u0142e\u0107 m\u0119skie<\/li><\/ul>
Dobra amortyzacja, wysoki komfort spacer\u00f3w. Ca\u0142oroczne obuwie trekkingowo-casualowe od marki New Balance. Model zosta\u0142 wykonany z najwy\u017cszej jako\u015bci sk\u00f3ry naturalnej. \u00a0Dzi\u0119ki amortyzowanej podeszwie buty zapewniaj\u0105 maksimum komfortu podczas codziennych spacer\u00f3w oraz g\u00f3rskich wycieczek. \u00a0Dzi\u0119ki dobrze wyprofilowanemu bie\u017cnikowi modele serii 754 idealnie sprawuj\u0105 si\u0119 r\u00f3wnie\u017c na nier\u00f3wnym, \u015bliskim pod\u0142o\u017cu. \u00a0Obuwie przeznaczone do u\u017cytku ca\u0142orocznego, ale doskonale spisuje si\u0119 zw\u0142aszcza zim\u0105. Cholewka ze sk\u00f3ry naturalnej. Amortyzowana podeszwa. Bie\u017cnik dla lepszej przyczepno\u015bci. Obuwie przeznaczone do u\u017cytku ca\u0142orocznego. Stylowa sylwetka buta. Uniwersalna kolorystyka. <\/p>

rozmiar: 41,5<\/b><\/p>

Cena: 399 z\u0142<\/h1>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11a912\/55ea050d452ca798c9a1cac29bb8"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11e37d\/b04dee9148d4b8697d5b9fc8e69f"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11035f\/d5e69d2f407db0c757d72dcd1d64"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11a7d8\/03908ee948b5bb993724b71f678c"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/118a35\/90deec984fe6b89b87015463f62c"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f288\/9260d2654bd48623c1e80ef30fdf"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/114887\/a72b4f3d4c92b92d4f9fef3404f7"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11e7c2\/8a0f53834706bab45b56171a64c7"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/112422\/51465f1343419a518dadc418e5ea"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":399,"currency":"PLN"}},"stock":{"available":"3","unit":"UNIT"},"publication":{"duration":"P30D"},"parameters":[{"id":64,"valuesIds":["64_2"],"values":[],"rangeValue":null},{"id":3766,"valuesIds":["3766_1"],"values":[],"rangeValue":null},{"id":7108,"valuesIds":["7108_252182"],"values":[],"rangeValue":null},{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":15851,"valuesIds":["15851_2"],"values":[],"rangeValue":null},{"id":22728,"valuesIds":["22728_215177"],"values":[],"rangeValue":null},{"id":127848,"valuesIds":["127848_1"],"values":[],"rangeValue":null},{"id":128188,"valuesIds":["128188_1"],"values":[],"rangeValue":null},{"id":203085,"valuesIds":["203085_4"],"values":[],"rangeValue":null},{"id":203105,"valuesIds":["203105_215377"],"values":[],"rangeValue":null},{"id":203729,"valuesIds":["203729_8"],"values":[],"rangeValue":null},{"id":219629,"valuesIds":["219629_286869"],"values":[],"rangeValue":null},{"id":219857,"valuesIds":["219857_287861"],"values":[],"rangeValue":null},{"id":451,"valuesIds":["451_2"],"values":[],"rangeValue":null},{"id":232289,"valuesIds":["232289_366645"],"values":[],"rangeValue":null},{"id":127048,"valuesIds":["127048_2048"],"values":[],"rangeValue":null},{"id":203093,"valuesIds":[],"values":["26.5"],"rangeValue":null},{"id":203097,"valuesIds":["203097_215233"],"values":[],"rangeValue":null},{"id":203101,"valuesIds":["203101_215321"],"values":[],"rangeValue":null}]}

response
HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: d224ed019b60bbf
date: Fri, 20 Sep 2019 18:32:20 GMT
x-ratelimit-remaining: 8964
x-content-type-options: nosniff
content-type: application/json
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 3
transfer-encoding: chunked

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by MariaPawlikowska** [comment]
U mnie też zaczeły się pojawiać te błędy. Jakieś zmiany w walidacji?

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, opisywany problem mógł się pojawiać za co przepraszam. Obecnie nie powinien już występować.

**Comment by bjatwork** [comment]
@MaciejFrackowiak 
u nas nadal "An error has occurred: "  bez dodatkowych komunikatów.

**Comment by MaciejFrackowiak** [comment]
@bjatwork W Twoim przypadku problemem są entery - znaki nowej linii w opisie. Format json nie przyjmuje znaku enter, jeśli chcesz zrobić nowa linię w opisie należy przesłać /n.

**Comment by bjatwork** [comment]
@MaciejFrackowiak 
nie wysyłamy enterów - przykładowy json, który powoduje błąd: 

{"name":"Buty adidas yung 1 cg7127 grey twocollegiate royal","afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"a2f5e179-fa72-4b54-9d4f-72f76ddb4889"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"category":{"id":"257929"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"delivery":{"shippingRates":{"id":"82bd8369-ebb9-480a-bd43-ec55941e95d1"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":""},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11314d\/85cb22394ffaa61610a693194a3c"},{"url":"https:\/\/a.allegroimg.com\/original\/110ffd\/9ee2beb44b6dbaea03e422db27a5"},{"url":"https:\/\/a.allegroimg.com\/original\/11e15f\/928de5bd4e27b66d2674a9460fc7"},{"url":"https:\/\/a.allegroimg.com\/original\/112540\/35fc8d2046b8a46d0532351652f7"},{"url":"https:\/\/a.allegroimg.com\/original\/1123ec\/18a97b6e4d26973b9db603cf052d"},{"url":"https:\/\/a.allegroimg.com\/original\/11f2df\/3b111dfb47539be7a4803ea8997b"},{"url":"https:\/\/a.allegroimg.com\/original\/118931\/488a3d5d4961b9b38107823fd690"}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Buty adidas yung 1 cg7127 grey twocollegiate royalscarlet 43 1\/3<\/h1><ul><li>Kolor wielokolorowy<\/li><li>Typ obuwie, sneakersy<\/li><li>Marka adidas<\/li><li>Model YUNG-1 127<\/li><li>Kolor producenta GREY TWO\/COLLEGIATE ROYAL\/SCARLET<\/li><li>Kolekcja wiosna-lato 2019<\/li><li>Technologie EVA\/Torsion System<\/li><li>Materia\u0142 zewn\u0119trzny nubuk\/materia\u0142 syntetyczny<\/li><li>Materia\u0142 wewn\u0119trzny tekstylia<\/li><li>Materia\u0142 podeszwy guma<\/li><li>P\u0142e\u0107 m\u0119skie<\/li><\/ul><p>\u200b\u200bWygodne sneakery w stylu retro. Drugi komplet sznurowade\u0142 w pude\u0142ku. Przewiewna cholewka z meshu i element\u00f3w z trwa\u0142ego nubuku. Wy\u015bcie\u0142any ko\u0142nierz. System Torsion wspieraj\u0105cy \u015br\u00f3dstopie. Podeszwa \u015brodkowa wykonana z lekkiej i amortyzuj\u0105cej pianki EVA. Odporna na \u015bcieranie gumowa podeszwa zewn\u0119trzna. Logowanie producenta.<\/p><p>rozmiar: <b>43 1\/3<\/b><\/p><h1>Cena: 499 z\u0142<\/h1>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11314d\/85cb22394ffaa61610a693194a3c"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/110ffd\/9ee2beb44b6dbaea03e422db27a5"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11e15f\/928de5bd4e27b66d2674a9460fc7"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/112540\/35fc8d2046b8a46d0532351652f7"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1123ec\/18a97b6e4d26973b9db603cf052d"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f2df\/3b111dfb47539be7a4803ea8997b"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/118931\/488a3d5d4961b9b38107823fd690"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":499,"currency":"PLN"}},"stock":{"available":"4","unit":"UNIT"},"publication":{"duration":"P30D"},"parameters":[{"id":219857,"valuesIds":["219857_287861"],"values":[],"rangeValue":null},{"id":219629,"valuesIds":["219629_286869"],"values":[],"rangeValue":null},{"id":3766,"valuesIds":["3766_2397"],"values":[],"rangeValue":null},{"id":203085,"valuesIds":["203085_4"],"values":[],"rangeValue":null},{"id":128188,"valuesIds":["128188_1"],"values":[],"rangeValue":null},{"id":15851,"valuesIds":["15851_2"],"values":[],"rangeValue":null},{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":64,"valuesIds":["64_3"],"values":[],"rangeValue":null},{"id":451,"valuesIds":["451_128"],"values":[],"rangeValue":null},{"id":7108,"valuesIds":["7108_1"],"values":[],"rangeValue":null},{"id":22728,"valuesIds":["22728_2"],"values":[],"rangeValue":null},{"id":127848,"valuesIds":["127848_1"],"values":[],"rangeValue":null},{"id":203101,"valuesIds":["203101_215333"],"values":[],"rangeValue":null},{"id":203093,"valuesIds":[],"values":["28"],"rangeValue":null},{"id":203097,"valuesIds":["203097_215257"],"values":[],"rangeValue":null},{"id":127048,"valuesIds":["127048_220917"],"values":[],"rangeValue":null}],"ean":"4060514111292"}

odpowiedź:  
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by MariaPawlikowska** [comment]
Niestety sytuacja bez zmian. Pojawia się błąd 400. SKrypt bez zmian. W ubiełgym tygodniu działało dobrze.

**Comment by MaciejFrackowiak** [comment]
@bjatwork W polach additionalInfo i shipmentDate nie może być pustych "". Po usunięciu tych pól lub przekazaniu wartości null, draft zostaje utworzony poprawnie.

@MariaPawlikowska Proszę prześlij nam request i response wraz z trace-id.

**Comment by bjatwork** [comment]
@MaciejFrackowiak 
ok, teraz poszło, ale nie wszystkie aukcje. Przy niektórych nadal dostaję: 
"An error has occurred ", przydało by się poprawić zwracanie błędów, bo nie wiemy o co chodzi. 

Przy ponownej próbie wystawienia tych aukcji z tym samym jsonem udało się wystawić.  Tak jakby było jakieś przeciążenie po stronie api, ponieważ problem występuje gdy wystawiamy wiele aukcji jednocześnie, lub jeśli wpadamy w jakieś limity przydałby się komunikat inny nic "An error has occurred ".

**Comment by MaciejFrackowiak** [comment]
@MariaPawlikowska Doszło tylko do zmiany formatu danych - mój kolega wspomniał o tym w poście [GitHub #2250](https://github.com/allegro/allegro-api/issues/2250).
