### ISSUE TITLE
Rodzaj oferty

### ISSUE THREAD

**Issue by Ostzie** [allegro/allegro-api#2254]
Witam,
korzystam o czytnika kanałów RSS, wszystko dotychczas działało popranie ale od dwóch dni nie działa parametr:
offerCondition=2
dotychczas dawał wyniki przedmiotów używanych.
Teraz niezależnie od zmiennej ładuje wszystkie oferty zarówno nowe jak i używane.

Jak należy to zmienić, aby dalej działało prawidłowo?

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj z jakich zasobów korzystasz przeglądając oferty.

**Comment by Ostzie** [comment]
Nie znam się na tym za bardzo, korzystam z poniższego rozwiązania:
https://github.com/Krukosz/Allegro_REST_RSS

**Comment by MaciejFrackowiak** [comment]
Niestety, nie jest to udostępniona przez nas aplikacja, dlatego trudno nam odnieść się do jej technicznych możliwości. Sugerowałbym kontakt z jej twórcą bądź ktoś z użytkowników forum napotkał podobny problem i będzie w stanie Tobie pomóc.

**Comment by emptycodes** [comment]
Problem tkwi w ostatniej aktualizacji frontendu w wynikach wyszukiwania ofert na Allegro. Po zapytaniu do frontendu ok. 13 dni temu można było wyciągnąć parametry wyszukiwania, które były identyczne do tych w REST API. Teraz nie ma ani śladu i o wiele trudniej skonstruować zapytanie do /offers/listing operując czasami na kompletnie niepodobnych parametrach.

**Comment by Ostzie** [comment]
Czyli na tą chwilę nie ma co liczyć na to, aby dodać sobie wyszukiwania do czytnika RSS otrzymując w pełni przefiltrowane wyniki?

**Comment by MaciejFrackowiak** [comment]
Ze swojej strony mogę zalecić korzystanie z filtrów, które dostępne są już w pierwszej odpowiedzi, bez opierania się na funkcjonalnościach z serwisu WWW. Zachęcam do spojrzenia do [naszego poradnika](https://developer.allegro.pl/listing/).
