### ISSUE TITLE
Dane na temat zamówienia

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#2255]
Kiedy wysyłany jest mail przez allegro o tym że klient wybrał sposób zapłaty i dostawy?
Mamy obecnie sytuację że otrzymaliśmy takiego maila, natomiast przez webapi jedyna akcja to utworzenie aktu zakupowego. Brak zarówno przez webapi jak i przez REST api jakichkolwiek informacji żeby to zamówienie miało utworzony formularz pozakupowy.  Jak mogę wytłumaczyć klientowi któremu robiliśmy integrację że to że otrzymał maila w którym ma napisane że klient wybrał metodę dostawy i płatności wcale tego nie oznacza?

**Comment by MaciejFrackowiak** [comment]
Powiadomienie o wypełnieniu formularza pozakupowego jest wysyłane już w momencie częściowego wypełnienia jego przez Kupującego (Kupujący porzucił wypełnianie formularza w trakcie). Może zatem dojść do sytuacji jak w tym przypadku - dane nie będą dostępne ani w REST API ani WebAPI, natomiast sam email został wysłany.
Proszę podaj nam konkretny przypadek, wówczas go sprawdzimy.

**Comment by d3stozaur** [comment]
Numer zamówienia    bb215bc0-d8d5-11e9-b95a-bb6f5fc82205

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem zamówienie - jest to przypadek, o którym wspomniałem. Kupujący porzucił w trakcie wypełnianie formularza i dlatego dane nie są dostępne. Podsumowując - w takich przypadkach formularz powinien zostać wypełniony ponownie.

**Comment by d3stozaur** [comment]
Wszystko jasne w takim razie, dziękuje za informacje
