### ISSUE TITLE
Sprawdzenie statusu aukcji z archiwum

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2256]
Chcę sprawdzić status aukcji która jest już w archiwum, w jaki sposób mogę to sprawdzić.
Próbowałem za pomocą GET /sale/offers/{offerId} ale zwraca mi błąd "Odpytywany zasób nie istnieje w API"
Czy taka odpowiedź zawsze oznacza archiwalną ofertę?

**Comment by MaciejFrackowiak** [comment]
Otrzymany przez Ciebie komunikat może oznaczać także podanie nieprawidłowego numeru oferty. Nie udostępniamy zasobów do odczytywania danych ofert archiwalnych.

**Comment by avello** [comment]
Więc w jaki sposób mogę określić czy dana oferta jest archiwalna?

**Comment by MaciejFrackowiak** [comment]
Nie ma bezpośredniej metody - podczas korzystania z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) dla takiej oferty otrzymasz komunikat “Not Found” - podobnie jak dla oferty o nieprawidłowym numerze.
Dodam, że oferty przenosimy do archiwum po 60 dniach od ich zakończenia.

**Comment by Radeq** [comment]
@avello , nie jest to idealne rozwiązanie ale można sprawdzić w archiwum Allegro
`archiwum.allegro.pl/oferta/a-i<NrAukcji>.html`

Aukcja która istnieje w Allegro powinna dostać kod odpowiedzi HTTP 404
