### ISSUE TITLE
Problem z zamykaniem ofert(aukcji) na sandbox

### ISSUE THREAD

**Issue by maczking** [allegro/allegro-api#2257]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od piątku odnotowujemy problem z zamykaniem aukcji(ofert) na środowisku testowym, problem występuje zarówno podczas próby zamknięcia aukcji po API jak i podczas prób "ręcznego" zamknięcia aukcji w poziomu sandboxa (w środowisku testowym pojawia się komunikat, że aukcja została zlecona do zamknięcia, ale w praktyce nie występuje zamknięcie). Czy były wprowadzane jakieś zmiany w tym zakresie?

**Comment by MaciejFrackowiak** [comment]
Przed momentem zweryfikowałem działanie Sandbox - zarówno poprzez REST API, jak i bezpośrednio przez WWW bez przeszkód zakończyłem oferty. Nie dokonywaliśmy żadnych zmian w tym zakresie.
Jeżeli problem nadal będzie występować u Ciebie, proszę przekaż nam request oraz response wraz z trace-id i numerem oferty.
