### ISSUE TITLE
[RestAPI] offers - Internal Server Error

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2258]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

REQUEST 2019-09-23 16:53:28.0950183
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206591714' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

RESPONSE 2019-09-23 16:53:28.3606410 Duration: 265,6227ms
{
  
  "Message": "The remote server returned an error: (500) Internal Server Error.",
  "Data": null,

Proszę o weryfikację, błąd się losowo pojawia na sandbox.
Inne numery: 6206568011, 6206375349

**Comment by MaciejFrackowiak** [comment]
Opisany problem przekazałem do weryfikacji.
