### ISSUE TITLE
Put request to modify offer

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#2259]
Hi,

I would like to change the available field of an offer with https://api.allegro.pl/sale/offers/{offerId}. I send a put request with the offer data after getting it using the url above but with a get request, modify the ['stock']['available'] = 0 and everytime I get a 422 error. 

If i try to modify the same offer with another quantity, it works fine. 

What is the problem? Is there any other field I need to change to set the available quantity to 0? 

Thank you

**Comment by MaciejFrackowiak** [comment]
It is correct response. You cannot set 0 in quantity field. If offer has 0 in quantity field, offer is unavailable for buyers. In that case if you want to end offer you should finished an offer with command [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) - just provide END in the action field.

**Comment by frenci8** [comment]
> It is correct response. You cannot set 0 in quantity field. If offer has 0 in quantity field, offer is unavailable for buyers. In that case if you want to end offer you should finished an offer with command [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) - just provide END in the action field.

Hi,

Thank you for the reply. I fixed it.

Sadly, I am having another problem now, but this one is about the price. I do the same first steps, get the full offer, and then modify only the price and send it using the put request. There are some offers which have prices 0.97 but I get  a 422 error when I send the updated data. 

Are prices lower than 1 not allowed? I am also modifying the availability to 10 of that product, but I suppose this is not the problem.

Thank you

**Comment by MaciejFrackowiak** [comment]
No, in Allegro minimum price per item is 1.00 PLN. You cannot set lower price - in other case you will receive error 422.

**Comment by frenci8** [comment]
Hi, Thank you for the reply. I fixed it. 

I am having another problem. I am trying to set the price of an offer to 233.48 after casting it to str and I get an error 422. If I try to modify any other field, it works fine. 

What is the problem in this case? Thank you

**Comment by MaciejFrackowiak** [comment]
Please, paste request and response with trace-id and I will check it.

**Comment by frenci8** [comment]
I managed to find the error. The validation error says "You cannot increase the price by more than 100%".

**Comment by MaciejFrackowiak** [comment]
OK, I will explain. If item price is less than 50,00 PLN you can increase its price maximum by 50,00 PLN. If item price is above 50,00 PLN you can increase its price maximum by 100%.
