### ISSUE TITLE
Przykład połączenia się przez restapi

### ISSUE THREAD

**Issue by migdalius** [allegro/allegro-api#226]
Witam

Mógłbym poprosić o przykład połączenia się przez REST API, o ile łączenie się przez webapi jest proste tak nie rozumiem jak zrobić to przez rest, najlepiej w php. Dziękuje

**Comment by MartaNowaczyk** [comment]
Witam,
na początek trzeba zarejestrować aplikację: https://apps.developer.allegro.pl/. Informację o uwierzytelnianiu i autoryzacji znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/auth/).

**Comment by migdalius** [comment]
Dziękuje z odpowiedź, natomiast nie pytałem jak zarejestrować aplikacje lub o link do dokumentacji tylko o przykład połączenia się przez rest api w php.

**Comment by MaciejPotepa** [comment]
API wspieramy jedynie z warstwy protokołów, czyli REST API zapisane w jsonie lub WebAPI zapisane w XML. 
Przykro mi, ale nie pełnimy wsparcia z zakresu języków programistycznych. 

Jedne co możemy zaoferować to właśnie przygotowany z myślą o osobach, które nie rozumieją autoryzacji RESTowej poradnik, który przeprowadzi Cię przez proces krok po kroku. 

[Tutaj](https://developer.allegro.pl/auth/) masz link. Ten sam, który wyżej podała Marta.

**Comment by alananh** [comment]
https://github.com/Wiatrogon/php-allegro-rest-api

**Comment by mstraczkowski** [comment]
https://github.com/zoondo/allegro-api
