### ISSUE TITLE
Błąd statusu oferty

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#2260]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym

Witam,
mam problem z ofertą: https://allegro.pl/show_item.php?item=7908392595.
Na portalu jest informacja, że jest zakończona, natomiast w rest oraz w panelu allegro jest że jest aktywna.

Dodatkowo została pobrana opłata za Wyróżnienie!!!

**Comment by MaciejFrackowiak** [comment]
Wskazaną ofertę zgłosiłem do weryfikacji technicznej.

**Comment by manoos** [comment]
czy coś wiadomo w temacie?

Mam jeszcze inną ofertę z tym samym błędem:
https://allegro.pl/show_item.php?item=7642990909

**Comment by MaciejFrackowiak** [comment]
Nie, jeszcze nie otrzymałem odpowiedzi. Nową ofertę również przekazałem do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Obie oferty zostały uspójnione - są już aktywne w Allegro.
