### ISSUE TITLE
Sandbox - Ograniczenie zakupowe

### ISSUE THREAD

**Issue by Tomash667** [allegro/allegro-api#2261]
Na sandboxie nie mogę kupić tego przedmiotu (3 sztuki) https://allegro.pl.allegrosandbox.pl/oferta/dit-darker-than-black-6206292831 . Potem całkowicie blokuje kupowanie z danego konta.

```
Ograniczenie zakupowe. Jeśli chcesz je usunąć, skontaktuj się z nami za pomocą formularza kontaktowego.
```

![image](https://user-images.githubusercontent.com/260290/65490458-7bd86b00-dead-11e9-8baa-3c8845509b42.png)

Konto kupującego: DJtest1

**Comment by MaciejFrackowiak** [comment]
Ograniczenie zakupowe ma na celu przeciwdziałanie masowym, wielokrotnym zakupom u danego sprzedającego. Opisany problem przekazałem do weryfikacji.
Jednocześnie tymczasowo sugeruję skorzystanie z alternatywnego konta do przeprowadzenia zakupu.
