### ISSUE TITLE
doGetRefundsDeals

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2262]
Coś się zepsuło z doGetRefundsDeals. Zawsze zwracała informacje o dealach dla których możliwe jest jeszcze wystąpienie o zwrot prowizji. Teraz zwraca również takie dla których wystąpiono o zwrot i dla których zwrot przyznano.

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem działanie [doGetRefundsDeals](https://allegro.pl/webapi/documentation.php/show/id,1422) na podstawie testowych ofert i nie zauważyłem błędu - zostały mi zwrócone tylko transakcje, dla których możliwe jest wystąpienie o zwrot prowizji.
Proszę prześlij nam przykładowy response i request, dla których zauważyłeś nieprawidłowość - skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) podając numer zgłoszenia z GitHub - 2262.

**Comment by lukada4100** [comment]
Wysłałem dwie pary request/response:
- DoSendRefundFormRequest dla deala 2130177092 z odpowiedzią, że "Refund form for this transaction has been already sent"
- DoGetRefundsDealsRequest z partią pobranych później dealów: 2130177092 jest wśród nich.

Potwierdź proszę, że doszły.

**Comment by MaciejFrackowiak** [comment]
Tak, otrzymałem Twoje pliki. Jednocześnie zgłoszenie przekazałem do weryfikacji.

**Comment by lukada4100** [comment]
Co by przekonać nieprzekonanych i popchnąć sprawę do przodu przesłałem jeszcze w formularzu print screena z frontendu z potwierdzeniem że wniosek o zwrot prowizji dla wybranej transakcji został złożony (i rozpatrzony pozytywnie) oraz request/response (doGetRefundsDeals) z tym właśnie dealem.

**Comment by MaciejFrackowiak** [comment]
Dziękuję - materiał dołączyłem do zgłoszenia.

**Comment by MaciejFrackowiak** [comment]
Wdrożona została poprawka rozwiązująca ostatecznie problem.
