### ISSUE TITLE
Dodawanie nowego cennika, błąd 422 przy dodaniu metody dostawy typu odbiór osobisty

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2263]
Mam pytanie odnośnie tworzenia nowego cennika dostaw. Jakie:
"maxQuantityPerPackage": 
		"firstItemRate": 
		"nextItemRate":
		"shippingTime": 
trzeba podać w przypadku metody typu odbiór osobisty, aby nie wystąpił błąd 422 ?
{
	"id": null,
	"name": "nazwacennika",
	"rates": [{
		"deliveryMethod": {
			"id": "7203cb90-864c-4cda-bf08-dc883f0c78ad"
		},
		"maxQuantityPerPackage": "6",
		"firstItemRate": {
			"amount": 11.0,
			"currency": "PLN"
		},
		"nextItemRate": {
			"amount": 11.0,
			"currency": "PLN"
		},
		"shippingTime": null
	}, {
		"deliveryMethod": {
			"id": "a6e4845b-9ace-48ea-b232-918eaf11ba6c"  //Odbiór osobisty
		},
		"maxQuantityPerPackage": null,
		"firstItemRate": null,
		"nextItemRate": null,
		"shippingTime": null
	}],
	"lastModified": null
}

**Comment by kfijalko** [comment]
Opłata 0zł, 1 szt w paczce.

id | name | payment_policy | allegro_endorsed | constraints_allowed | constraints_max_quantity_per_package | constraints_first_item_rate_min | constraints_first_item_rate_max | constraints_first_item_rate_currency | constraints_next_item_rate_min | constraints_next_item_rate_max | constraints_next_item_rate_currency | constraints_shipping_time_from | constraints_shipping_time_to | constraints_shipping_time_customizable | active | visible | required | delivery_group_id | created_at | updated_at
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
a6e4845b-9ace-48ea-b232-918eaf11ba6c | Odbiór osobisty pobranie | CASH_ON_DELIVERY | 0 | 0 | 1 | 0,00 | 0,00 | PLN | 0,00 | 0,00 | PLN | PT0S | PT0S | 0 | 1 | 0 | 0 | 5 | 08.01.2019 18:15:14 | 24.09.2019 07:00:02

**Comment by kfijalko** [comment]
Ponizej metody odbioru osobistego:


id | name | payment_policy | allegro_endorsed | constraints_allowed
-- | -- | -- | -- | --
57b987de-ce2d-4e73-9b9f-a7c9ebe9611d | Odbiór osobisty po przedp�acie | IN_ADVANCE | 0 | 0
a6e4845b-9ace-48ea-b232-918eaf11ba6c | Odbiór osobisty pobranie | CASH_ON_DELIVERY | 0 | 0
afa68f62-0154-4556-9ee4-3f97c3c5bdca | Odbiór osobisty w punkcie sprzedawcy | IN_ADVANCE | 0 | 1
b6d6e4cf-67b3-4a4f-a38d-724335e9734f | Odbiór osobisty w punkcie sprzedawcy pobranie | CASH_ON_DELIVERY | 0 | 1

**Comment by kfijalko** [comment]
Pełne rekordy z mojej bazy:
Dla odbioru osobistego: koszt 0 zł i 1 szt w paczce.

id | name | payment_policy | allegro_endorsed | constraints_allowed | constraints_max_quantity_per_package | constraints_first_item_rate_min | constraints_first_item_rate_max | constraints_first_item_rate_currency | constraints_next_item_rate_min | constraints_next_item_rate_max | constraints_next_item_rate_currency | constraints_shipping_time_from | constraints_shipping_time_to | constraints_shipping_time_customizable | active | visible | required | delivery_group_id | created_at | updated_at
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
57b987de-ce2d-4e73-9b9f-a7c9ebe9611d | Odbiór osobisty po przedp�acie | IN_ADVANCE | 0 | 0 | 1 | 0,00 | 0,00 | PLN | 0,00 | 0,00 | PLN | PT0S | PT0S | 0 | 1 | 0 | 0 | 5 | 08.01.2019 18:15:14 | 24.09.2019 07:00:02
a6e4845b-9ace-48ea-b232-918eaf11ba6c | Odbiór osobisty pobranie | CASH_ON_DELIVERY | 0 | 0 | 1 | 0,00 | 0,00 | PLN | 0,00 | 0,00 | PLN | PT0S | PT0S | 0 | 1 | 0 | 0 | 5 | 08.01.2019 18:15:14 | 24.09.2019 07:00:02
afa68f62-0154-4556-9ee4-3f97c3c5bdca | Odbiór osobisty w punkcie sprzedawcy | IN_ADVANCE | 0 | 1 | 1 | 0,00 | 0,00 | PLN | 0,00 | 0,00 | PLN | PT0S | PT0S | 1 | 1 | 1 | 1 | 5 | 18.01.2019 05:12:01 | 24.09.2019 07:00:02
b6d6e4cf-67b3-4a4f-a38d-724335e9734f | Odbiór osobisty w punkcie sprzedawcy pobranie | CASH_ON_DELIVERY | 0 | 1 | 1 | 0,00 | 0,00 | PLN | 0,00 | 0,00 | PLN | PT0S | PT0S | 1 | 1 | 1 | 1 | 5 | 18.01.2019 05:12:01 | 24.09.2019 07:00:02

**Comment by SaintRaphaelBass** [comment]
Dzięki wielkie. Masz u mnie flachę. Po prostu nie do końca zrozumiałem, że nie dozwolone.
