### ISSUE TITLE
Problem z endpointem /sale/offers

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#2264]
Dzień dobry,

Od mniej więcej zeszłego piątku mamy problem ze złożeniem oferty (endpoint: sale/offers).
Format danych, które wysyłamy nie zmienił się ostatnio, a mimo to  API zwraca (niestety nic nie mówiący) błąd.

Oto dane, które wysyłamy i treść błędu w odpowiedzi (gdzieniegdzie zastąpiłem dane znakami "X")

{
  "name": "Mini-karnisz do zazdrostki biały 2szt.",
  "category": {
    "id": "XXXXXX"
  },
  "publication": {
    "duration": null
  },
  "stock": {
    "available": "50",
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "X.X",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null
  },
  "location": {
    "city": "XXXXXX",
    "countryCode": "PL",
    "postCode": "XX-XXX",
    "province": "XXXXXX"
  },
  "images": [
    {
      "url": "https://a.allegroimg.com/original/XXXXXX"
    }
  ],
  "delivery": {
    "additionalInfo": null,
    "handlingTime": "P2D",
    "shipmentDate": "",
    "shippingRates": {
      "id": "XXXXXX"
    }
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "XXXXXX"
    },
    "returnPolicy": {
      "id": "XXXXXX"
    },
    "warranty": {
      "id": "XXXXXX"
    }
  },
  "external": {
    "id": "XXX-XXX-XX"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>Mini-karnisz do zazdrostki biały 2szt., 40 cm</h1>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/XXXXXX"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Kod produktu: <b>XXX-XXX-XX</b></p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Metalowe pręty w kolorze białym do szybkiego i prostego zawieszenia zazdrostek/W komplecie znajdują się 2 pręty w zależności od wybranej długości - poszczególne wymiary dostępne na różnych aukcjach40cm (z możliwością rozciągnięcia do długości 60cm)60cm (z możliwością rozciągnięcia do długości 90cm)80cm (z możliwością rozciągnięcia do długości 120cm)100cm (z możliwością rozciągnięcia do długości 170cm)4 haczyki z przylepcem do przyklejenia na ramę okna, 4 haczyki do wkręcania.</p>"
          }
        ]
      }
    ]
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "129377",
      "values": [
        "100"
      ]
    },
    {
      "id": "129299",
      "valuesIds": [
        "129299_32"
      ]
    },
    {
      "id": "127328",
      "valuesIds": [
        "127328_2"
      ]
    }
  ],
  "ean": "59XXXXXX19009"
}

Treść błędu w odpowiedzi:

{
  "errors": [
    {
      "code": "ERROR",
      "message": "An error has occurred",
      "details": null,
      "path": "/sale/offers",
      "userMessage": null
    }
  ]
}

Bardzo proszę o pomoc w usunięciu błędu.

**Comment by MaciejFrackowiak** [comment]
W polu “shipmentDate” nie może być pustych “”. Należy podać wartość null lub usunąć to pole.

**Comment by adamTynski** [comment]
Zadziałało, dziękuję
