### ISSUE TITLE
BŁĄD FORM DOSTAWY PRZEZ EMAIL Poczta Polska

### ISSUE THREAD

**Issue by zielulu** [allegro/allegro-api#2265]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Powtórka z rozrywki, tym razem z Pocztą Polską.

Od dzisiejszego poranka przy niektórych Pocztexach 48 pojawia się błąd podczas próby nadania ich przez API. 

Błąd w programie "EasyUploader" brzmi mniej więcej "Musisz mieć podpisaną umowę aby nadawać przesyłki Allegro Dostawa", z tym, że my w ofercie na allegro z tych waszych "łączonych" form wysyłki posiadamy jedynie Allegro Polecony. Punkty i Kurierka jest na zwykłą umowę.

Błąd pojawia się tylko w przypadku adresów email klientów, które zawierają znak "+", ostatnio powszechnie stosowany w mailingu allegro.

To samo niedawno działo się z InPostem, weźcie się porządnie do roboty i zróbcie coś z tym. Zbliża się sezon sprzedażowy, a Wy wprowadzacie takie zmiany wiedząc, że zawsze jak coś zmieniacie są jakieś problemy. Jak chcecie przeprowadzać takie operacje, to albo róbcie to w okresie wakacyjnym, albo nauczcie się robić to porządnie.

**Comment by MaciejFrackowiak** [comment]
Nie dokonywaliśmy żadnych zmian w funkcjonowaniu tego mechanizmu. W tym momencie sugeruję bezpośredni kontakt z Pocztą, która odpowiada za możliwość nadania przesyłek.
