### ISSUE TITLE
REST API modyfikacja czasu dostawy nie działa

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#2266]
Próbuję zmienić czas dostawy dla oferty o danym ID na allegro. Napisałem metodę (poniżej) której wywołanie zwraca kod: 
`{"id":"d19b8344-55af-4d24-bc58-8800b800daa2","taskCount":{"total":0,"success":0,"failed":0}}`

Mimo bezbłędnego wywołania czas dostawy nie ulega zmianie.

Czy ktoś jest mi w stanie powiedzieć, co może być nie tak w metodzie poniżej? Czy taka metoda została wycofana z API czy co?

```
public function changeOfferDeliveryTime($offerId, $deliveryTimeInHours) {
        $commandId = $this->getUuid();
        $url = "https://api.allegro.pl/sale/offer-modification-commands/{$commandId}";

        $data = array(
            "modification" => array (
                "delivery" => array(
                    "shippingRates" => array (
                        "id" => "xxx-xxx-xxx"
                    ),
                    "HandlingTime" => "PT{$deliveryTimeInHours}H"
                )
            ), 
            "offerCriteria" => array(
                array(
                    "offers" => array (
                        array("id" => $offerId)
                    ),
                    "type" => "CONTAINS_OFFERS"
                )
            )
        );        
                
        $response = $this->put($url, $data);    
}
```

**Comment by MaciejFrackowiak** [comment]
Nie, tym razem była to modyfikacja oferty przy pomocy [PUT /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT) - dokładnie zmiana cennika dostawy. Szczegółowe potwierdzenie, czy operacja się powiodła czy nie oraz co było przedmiotem zmiany możesz otrzymać korzystając z zasobu [GET /sale/offer-modification-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getTasksUsingGET).
Zajrzyj też do [naszego poradnika](https://developer.allegro.pl/my_offers/#3) dot. edycji wielu ofert jednocześnie.

**Comment by lukiopmoto** [comment]
@MaciejFrackowiak no właśnie tylko chodzi o to że przy tej aktualizacji cennika aktualizowałem parametr "HandlingTime" z 96 godzin na 48 godzin. Niestety operacja nie zmieniła dla danej oferty czasu dostawy, Czały czas klient widzi 4 dni czas dostawy. 

Chyba będę musiał pozakańczać wszystkie aukcje i powystawiać na nowo, bo nie widzę innej opcji żeby skrócić czas dostawy dla 10 000 ofert, skoro to  PUT /sale/offer-modification-commands/{commandId} nie działa.

**Comment by MaciejFrackowiak** [comment]
Zasób modyfikuje tylko przypisany do ofert cennik dostawy. Nie ma to natomiast wpływu na wartość pola “handlingTime” (w samym cenniku dostawy dostępne jest tylko pole “shippingTime”).

**Comment by lukiopmoto** [comment]
@MaciejFrackowiak  Aaa to rozumiem. To jeżeli chodzi o zmianę czasu dostawy z 4 dni na 2 dni to muszę zrobić:  GET /sale/offers/{offerId}  a następnie: PUT /sale/offers/{offerId} ?? Nie ma innego sposobu?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak, obecnie nie ma alternatywnego rozwiązania. Przekazuję to jako sugestię do działu odpowiedzialnego za rozwój REST API.

**Comment by lukiopmoto** [comment]
@MaciejFrackowiak  no byłoby super bo wówczas można by edytować czasu dostawy szybko i prosto tak jak cenę.
