### ISSUE TITLE
Allegro lokalnie i REST Api

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#2267]
Wprowadzacie jakieś Allegro lokalnie dla osób prywatnych. Czy REST Api, będzie to obsługiwało? Chodzi mi konkretnie o GET /offers/listing Czy będę mógł wyszukiwać i pobierać wystawione przedmioty? Czy przedmioty  wystawiane w Allegro lokalnie będą pojawiały się w dzienniku?

**Comment by MaciejFrackowiak** [comment]
Nie, oferty z Allegro Lokalnie nie będą dostępne w REST API. Pojawią się na listingu Allegro, jednak będą przekierowywały bezpośrednio na stronę oferty w Allegro Lokalnie.

**Comment by juhacz** [comment]
No to tragedia, zamierzacie to z czasem zmienić? Czy w takim razie będzie jakaś możliwość pobierania nowo wystawionych ofert uwzględniając jakieś kryteria np. kanały RSS, czy zostaje tylko HTML scraping?

**Comment by MaciejFrackowiak** [comment]
Nie, obecnie nie przewidujemy udostępniania ofert Allegro Lokalnie w REST API.

**Comment by juhacz** [comment]
No to wyłożycie kilkaset, jak nie więcej biznesów... w tym mój i znajomych, pięknie dziękuję.

**Comment by MaciejFrackowiak** [comment]
Allegro Lokalnie będzie stanowić osobny byt, gdzie jak wspomniałem tylko na listingu będą oferty przekierowujące bezpośrednio tam. Same oferty Allegro będą funkcjonować po API bez zmian.

**Comment by juhacz** [comment]
Podsumujmy, wchodzę przeglądarką na allegro.pl w wybraną kategorię allegro np. Allegro / Elektronika / RTV i AGD / TV i Video / Telewizory. Jest tam 1000 ofert, 500 od firm i 500 od prywatnych sprzedających. Po kliknięciu oferty od firmy, mogę go zakupić tak aj dotychczas. Po kliknięciu na ofertę od osoby prywatnej, zostaję przekierowany do Allegro lokalnie i mogę go tam zakupić.
Natomiast kiedy za pomocą GET /offers/listing będę chciał pobrać oferty z wspomnianej wyżej kategorii, otrzymam tylko 500 ofert, które wystawiają wyłącznie firmy, tak? Jeśli jestem zainteresowany zakupem używanego TV od osoby prywatnej, muszę wejść przeglądarką na Allegro i sobie takie TV wyszukać "ręcznie"?

**Comment by MaciejFrackowiak** [comment]
Allegro Lokalnie jak wspomniałem to będzie osobny serwis, częściowo niezależny od Allegro. Tym samym nadal w Allegro sprzedający prywatni będą mogli wystawiać przedmioty - Allegro Lokalnie będzie dla nich tylko alternatywą. Tym samym ich oferty nadal będą na listingu dostępnym w REST API. Tylko oferty bezpośrednio wystawione w Allegro Lokalnie nie będą dostępne po REST API.

**Comment by juhacz** [comment]
W poniedziałek dostałem maila, w którym min. jest informacja:
"Osoby prywatne, które mają zwykłe konto na Allegro i nie prowadzą profesjonalnej sprzedaży, będą mogły sprzedawać tylko na Allegro Lokalnie. Allegro.pl przeznaczone będzie dla sprzedawców z kontami firmowymi"
oraz:
"Zależy nam na ciągłości Twojej sprzedaży. Jeżeli nie przekształcisz swojego konta w konto firmowe, będziesz mógł prowadzić sprzedaż na dotychczasowych warunkach do 31 października 2019 r. Od 1 listopada nie będziesz mieć już możliwości ubiegania się o zwrot prowizji, a po 1 lutego 2020 r. będziesz miał możliwość sprzedawania tylko na Allegro Lokalnie - podobnie jak reszta osób prywatnych."

Duże rozbieżności z tym co Pan pisze i z tym, co Allegro do mnie wysyła.

**Comment by MaciejFrackowiak** [comment]
Moja odpowiedź odnosiła się w kontekście bieżącego funkcjonowania REST API - nie wybiegałem tak daleko w przyszłość tj. do lutego 2020. Patrząc na obecne oferty i listingi to już zdecydowana większość ofert na Allegro pochodzi od firm, dlatego proporcje nie są 1:1. Generalnie tak jak w otrzymanej wiadomości - jeżeli sprzedajesz w ramach prowadzonej działalności to zdecydowanie zalecamy przekształcenie konta w konto Firma, wówczas oferty zawsze będą na listingu REST API.

**Comment by Onixarts** [comment]
Konta prywatne używane przez developerów też będą bezużyteczne. Firma zajmująca się tworzeniem oprogramowania nie zajmuje się sprzedażą na Allegro też będzie musiała mieć konta firmowe a programiści/testerzy zamiast skorzystać z władnego narzędzia będą musieli klikać przez www. Znowu krok w tył.

**Comment by MaciejFrackowiak** [comment]
@Onixarts Konto Firma na Sandbox może mieć każdy - i tu bez przeszkód można testować rozwiązania.

**Comment by Onixarts** [comment]
Tylko, że sandbox i Allegro mają trochę różnic i nie wszystko da się na sandboxie sprawdzić - chociażby kategorie i parametry są inne. Jeśli klienci zgłaszają problem to weryfikowaliśmy na Allegro na własnych prywatnych aukcjach. Teraz będzie to utrudnione i trzeba będzie fejkowe aukcje wystawiać na koncie firmowym.

**Comment by Uriziel01** [comment]
`Procesy na Sandbox są identyczne jak na produkcyjnym Allegro` z całym szacunkiem ale tak być powinno, niestety rzeczywistość dalece odbiega od tego stanu. 

Systematycznie widzimy kolejne issues zakładane bo sytuacja na sandbox'ie odbiega od produkcyjnego środowiska.

Obiecaliście sobie jak i developerem że problemy z którymi kiedyś borykał się sandbox zostaną rozwiązane i odzwierciedlenie środowiska produkcyjnego będzie nareszcie w 100% skuteczne aby sandbox był wiarygodnym źródłem do testów E2E/integracyjnych czy nawet choć tych manualnych.

Osobiście rozmawiałem z waszymi developerami w 4 oczy podczas wizyty w Pixel'u i WSZYSCY zgodziliśmy się że tak być POWINNO...

**Comment by MaciejFrackowiak** [comment]
@Uriziel01 Zgadza się, mamy świadomość pewnych niedoskonałości Sandbox i dostępnych tam procesów. Staramy się możliwie na bieżąco reagować i zapewniam Cię, że wkładamy to wszelkie dostępne zasoby oraz środki.

**Comment by juhacz** [comment]
Wracając do pierwszego postu w tej konwersacji, mimo zapewnień, że nie, widzę, że oferty z Allegro lokalnie są dostępne w zasobie /offers/listing. Po prostu pole "vendor" w zwracanej strukturze identyfikuje pochodzenie ogłoszenia z Allegro Lokalnie. I tutaj moje pytanie, bo jest pewna niespójność. Ogłoszenia/aukcje z Allegro Lokalnie mają numery ofert od 1000000000, oferty allegro już ponad 8621321114. Niestety za pomocą doGetItemsInfo nie da się pobrać informacji o takiej aukcji (oferty nie znaleziono), chodzi mi konkretnie o parametry przedmiotów. Czy da się w jakiś inny sposób pobrać parametry wystawionego przedmiotu, czy będzie się dało? Czy po prostu taka niespójność, to zamierzenie?

**Comment by MaciejFrackowiak** [comment]
@juhacz Jest to prawidłowe zachowanie - na listingu Allegro są to oferty, który przekierowują do Allegro Lokalnie, w związku z tym one fizycznie nie są wystawione przez Allegro. Dlatego nie można ich pobrać przez doGetItemsInfo.

**Comment by grzegorzjj** [comment]
Moim zdaniem to porażka - firmy ( patrz SNAJPER ) zapewniają usługi również prywatnym odbiorcom. Odcięcie API ( nawet niech będzie tylko Wasze ukochane REST API ) od A Lokalnie to dla nich porażka marketingowa. Ja sam używam REST API do swoich celów i aukcje, które przeglądam to kolekcjonerstwo. Zaraz całe przejdzie do A Lokalnie i figa. 
Poza wspomnianym tu portalem jest pewnie 2^16 innych, które tego używają. Odbieracie im możliwość zarabiania pieniędzy. Pomysł REWELACJA!

**Comment by MaciejFrackowiak** [comment]
@grzegorzjj Allegro Lokalnie co do zasady to osobny serwis, dlatego trudno nam się bezpośrednio wypowiadać o jego działaniu i dostępności ichniejszego API.
