### ISSUE TITLE
Zmiana ceny w aktywnej ofercie

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2268]
Jakie warunki musi spełniać nowa cena? /nie mogę znaleźć w dokumentacji/

**Comment by rtnet-pl** [comment]
- musi być >= 1 PLN
- precyzja do 2 miejsc po przecinku
- jeśli obecna cena KT <= 50 zł to max +50 zł
- jeśli obecna cena KT > 50 zł to max +100%

dla licytacji są chyba tylko 2 pierwsze punkty.

**Comment by kfijalko** [comment]
Dziękuję
