### ISSUE TITLE
Pobranie wszystkich kategorii i parametrów

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2269]
Powstało  może jakieś rozwiązanie po stronie allegro - rest api  aby pobrać "prosto"= ZBIORCZO wszystkie kategorie i parametry  ?

Jeśli tak to jak?
Jeśli nie to kiedy będzie można ?
Jeśli nie będzie po Rest Api to allegro mogło by przynajmniej zrzucać te kategorie i parametry do np jakiegoś pliku xml co godzinę ? było by znacznie łatwiej i przyjemniej ....

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiego rozwiązania. Drzewo kategorii możesz przeglądać korzystając z zasobu [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET). Więcej na temat obecnie dostępnych zasobów do przeglądania kategorii i parametrów znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-2). Jednocześnie Twoją sugestię przekazuję do działu odpowiedzialnego za rozwój REST API.

**Comment by frankii91** [comment]
ok a jest choć jakiś parametr którym można się posługiwać aby nie pobierać wszystkich kategorii czy wszystkich parametrów tylko te które się zmieniły (po dacie zmienny czy coś innego) ?

**Comment by plegenza** [comment]
Podgrzeje kotleta, jest jakaś "dobra" praktyka pobierania tych kategorii, czy trzeba orać API od A do Z po zagnieżdżonym drzewie?
