### ISSUE TITLE
[Pytanie | REST] Możliwe powody odrzucenia aukcji

### ISSUE THREAD

**Issue by alananh** [allegro/allegro-api#227]
Witam,
jest szansa na udostępnienie listy VALIDATION_ERRORsów przy wystawianu aukcji w REST API? 

Na "Invalid HTML subset" już się natknąłem, ale dzisiaj kompletnie zaskoczył mnie "Podany kod EAN jest niepoprawny". Łatwiej byłoby zapobiec tym chochlikom, gdyby była jakaś lista.

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak nie mamy takiej listy. Jeśli kiedyś powstanie na pewno ją udostępnimy.
