### ISSUE TITLE
Sprzedaż przez KupTeraz czy licytacja

### ISSUE THREAD

**Issue by qls-api** [allegro/allegro-api#2270]
Jeśli mamy ofertę licytacyjną wraz z opcją KupTeraz ,  Jak można uzyskać informacje o sposobie zakończenia sprzedaży czy było KupTeraz czy licytacja.

**Comment by MaciejFrackowiak** [comment]
W REST API nie rozróżniamy w zamówieniach czy zakup został dokonany poprzez licytację czy Kup Teraz.
