### ISSUE TITLE
Przesyłki Allegro Poczta Polska 

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#2271]
Dzień dobry,
od wczoraj podczas próby wygenerowania numeru przewozowego dla przesyłek Allegro Poczty Polskiej odbiór w punkcie wyskakuje błąd "Nie udało się powiązać przesyłki z Allegro dla podanych atrybutów elementu relatedToAllegro". Po kontakcie z Pocztą Polską otrzymaliśmy informację że po ich stronie jest wszystko ok i problem wynika ze strony Allegro. Co mamy zrobić żeby te przesyłki były odpowiednio walidowane?

**Comment by magik092** [comment]
@d3stozaur 
Mieliśmy ten sam problem, właśnie odkryliśmy że po wczorajszym wdrożeniu PP w obiekcie Adres musisz od wczoraj podawać email (wypełnić go tym z domeny allegromail.pl).

**Comment by MaciejFrackowiak** [comment]
Ze swojej strony dodam, że nie dokonywaliśmy żadnych zmian w funkcjonowaniu tego mechanizmu. Nie dotarło też do nas żadne zgłoszenie od Poczty Polskiej informujące o jakimkolwiek problemie. Dane są przez nas udostępniane w trybie ciągłym.

**Comment by d3stozaur** [comment]
@magik092 
Dzięki faktycznie po przekazaniu emaila teraz wszystko działa
