### ISSUE TITLE
Odpowiedniki metod w nowym REST API

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2273]
W naszym systemie staramy się wykorzystywać metody z nowego REST API jednak na ten moment musimy korzystać ze starego WSDL i stąd pytanie jaki jest plan na poniższe metody:
Publiczne dane o ofertach
- doShowItemInfoExt
- doGetItemsInfo
Dane użytkownika
- doShowUser.
Na ten moment jest odpowiednik /offers/listing oraz /users/{userId}/ratings-summary, które są bardzo ograniczone. Czy do momentu wygaszenia starego WSDL zostaną one rozbudowane o dane zwracane ze starego api? Czy będzie możliwość pobierania szczegółów aukcji wszystkich użytkowników, a nie tylko swoich i pobieranie danych o userze oprócz jego ID i ratingu? 
Chcę mieć pewność, że nasz system nadal będzie miał dostęp do tych samych danych co za pomocą starego WSDL. 

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Trafiły już do nas podobne sugestie związane z rozwojem dotychczasowych zasobów REST API. W tym miejscu nie mogę obecnie jednoznacznie wskazać ewentualnych dat wprowadzenia zmian, jednak zapewniam, że zespół odpowiedzialny za rozwój REST API na bieżąco śledzi zgłaszane sugestie. Obecnie planowane zmiany znajdziesz w [naszym harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by artzie92** [comment]
W tym przypadku w harmonogramie niestety jest tylko informacja o tym, że te metody przestaną być aktywne, ale brakuje informacji jak zostaną zastąpione. Liczę, że zanim to się stanie będzie inny sposób na pobranie informacji na temat szczegółów oferty (public) oraz informacji o sprzedawcy, w przeciwnym razie wiele elementów naszego systemu przestanie spełniać swoje zadania. 
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
REST API jest obecnie w fazie ciągłego rozwoju, a co za tym idzie zgłaszane sugestie są rozpatrywane i brane pod uwagę podczas projektowania nowych rozwiązań. W miarę dokonywania zmian aktualizujemy również wspomniany harmonogram.

**Comment by artzie92** [comment]
Dzięki za informacje. Pod którym topikiem można zgłaszać sugestie?

**Comment by MaciejFrackowiak** [comment]
Nie ma jednego tematu dla zgłaszania sugestii. Po prostu, gdy pojawia się jakaś kwestia, gdzie zdanie / wizja Użytkowników jest odmienna od naszej to zapisujemy takie pomysły i przekazujemy dalej. Dlatego zawsze zachęcamy do jak najbardziej dokładnego opisania potrzeby, do jakich zasobów używałbyś danej funkcjonalności, etc.
