### ISSUE TITLE
Zwrot prowizji w przypadku zwrotu zamówienia

### ISSUE THREAD

**Issue by koszar93** [allegro/allegro-api#2274]
Czy istnieje możliwość zwrócenia się do Allegro przez API REST o zwrot prowizji w przypadku zwrotu zamówienia przez klienta?

**Comment by MaciejFrackowiak** [comment]
Nie, obecnie nie ma takiego zasobu. Pracujemy nad nim i w niedalekiej przyszłości zostanie udostępniony, o czym poinformujemy oczywiście na GitHub oraz na stronie [aktualności](https://developer.allegro.pl/news/).
