### ISSUE TITLE
Błąd :PAYLOAD_TOO_LARGE , POST na zasobie /sale/offers

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2275]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym

W pewnych sytuacjach api zwraca mi na metodzie PU na zasobie /sale/offers błęd następujący
O co chodzi ? jak to interpretować ?

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => PAYLOAD_TOO_LARGE
                    [message] => Payload Too Large
                    [details] =>.
                    [path] => /sale/offers
                    [userMessage] =>.
                )

        )

)

**Comment by MaciejFrackowiak** [comment]
Proszę sprawdź, czy nie przekraczasz ograniczenia opisu do 40960 bajtów na całego JSONa z opisem i maksymalnie do 100 sekcji.

**Comment by 11mszot** [comment]
ok wszystko jasne , 40K to trochę wyżyłowany limit
