### ISSUE TITLE
Dodanie do sale/offers parametru endedBy

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2276]
:bulb: **Sugestia**

Witam,
bardzo potrzebny w zasobie sale/offers okazałby się parametr endedBy znany z zasobu /sale/offers/{offerId}. Wiem, że zastosowanie tych zasobów jest różne, jednak endedBy zdecydowanie by się przydał w sale/offers do identyfikacji obecnego stanu aukcji. Jest jakaś szansa na wprowadzenie go? 

Dodam, że używanie /sale/offers/{offerId} jest problematyczne, ponieważ z niego dane są usuwane po pewnym czasie i endedBy przepada wtedy, kiedy mogłoby się jeszcze przydać.

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię. Przekazałem ją do zespołu odpowiedzialnego za rozwój REST API.
