### ISSUE TITLE
GET /order/checkout-forms  ,  /order/checkout-forms/{checkoutForm_id}  Dodatkowa flaga, pole - status zamówienia sprzedawcy

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2277]
:bulb: **Sugestia**
GET /order/checkout-forms  ,  /order/checkout-forms/{checkoutForm_id} 

Sugestia dotyczy aby można było ustawiać/ oznaczać zamówienia  dodatkową flagą
- tak samo w Api jak i przez www

A oznaczenia do wyboru z listy mogły by być nawet na zasadzie pola do synchronizacji aukcji z zewnętrznymi systemami sprzedaży

Tak aby można było odpowiednio oznaczać zamówienia w allegro 
2 możliwości
- pole słownikowe ( nawet 5 wartości do wyboru) - 
- pole tekstowe to długości obojętnej tak aby można było do zamówienia przypisać dowolne własne statusy - teksty

Takie coś bardzo pomogło by w uporządkowywaniu zamówień po stronie allegro od strony www a zewnętrznego systemu sprzedaży, pomogło by również w szybkim wyłapaniu problemów z importem zamówień.

Pole dla "mnie" głównie było by przydatne po to aby zlikwidować potrzebę pilnowania maili z informacjami o sprzedaży, wpłatach ( były by one w 100% zbędne).
A zalogowanie się do portalu 1-2 razy w tygodniu można by łatwo sprawdzić czy wszystkie zamówienia zostały obsłużone - zaimportowane do zewnętrznego systemu sprzedaży poprawnie i wiele innych.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię. Przekazałem ją do zespołu odpowiedzialnego za rozwój REST API.
