### ISSUE TITLE
Złe parametry dla kategorii

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#2278]
Zauważyłem, że od kilku godzin są zwracane złe parametry w fidzie Rodzaj. Próbuję wystawić produkt w kategorii 261478 i w tym parametrze dostaję opcje zupełnie nie pasujace do tej kategorii

![image](https://user-images.githubusercontent.com/43699922/65630666-28157100-dfd6-11e9-8ece-5861c5a0948c.png)

**Comment by kfijalko** [comment]
U mnie w 255119: Motoryzacja > Części samochodowe > Oświetlenie > Lampy tylne i elementy > Lampy tylne
Też pojawił się parametr:

Rodzaj | dictionary | 0 | Warianty dozwolone: 0 Parametr weryfikujący: 0 Wiele wartości: 0 | inny na butelkę na krzesło na sztućce
-- | -- | -- | -- | --

**Comment by kfijalko** [comment]
Ktoś zaszalał i dodał ten parametr do 21k kategorii.

**Comment by hahyes** [comment]
W Modzie to samo, doszło w 400 kategoriach, kompletnie bez sensu.

Ktoś chyba kliknął za dużo na produkcji i poszedł do domu. 👍

**Comment by hengwo** [comment]
Czy klasyfikacja: 257929 obsługuje przesyłanie produktów za pośrednictwem interfejsu API?

**Comment by kfijalko** [comment]
@hengwo 
jeżeli masz na myśli przesyłanie ofert to tak,
jeżeli masz na myśli produktyzację to nie.

id | name | parent_id | leaf | options_variants_by_color_pattern_allowed | options_advertisement | options_advertisement_price_optional | options_offers_with_product_publication_enabled | options_product_creation_enabled | options_product_ean_required | created_at | upadted_at | deleted_at | active | md5_category | md5_data | md5_parameters | md5_dictonaries | level | path_ids | path_names
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
257929 | Sportowe | 532 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 25.09.2019 22:10:16 | 25.09.2019 22:10:16 |   | 1 | f033ea8f792358ed91a5644dd97d5650 | fa44ef2749ad3c3f13b4c46f0f406186 | 2a78198d35913914c73642abfb1115df | bb5516ace5fc4896c2a9ba446e23b48b | 5 | /ea5b98dd-4b6f-4bd0-8c80-22c2629132d0/1454/1469/532/257929 | /Moda/Odzie�, Obuwie, Dodatki/Obuwie/M�skie/Sportowe

**Comment by hengwo** [comment]
what's means?
not support category 257929?

**Comment by kfijalko** [comment]
@hengwo 
If you mean offer creation by RestApi - answer is yes.
If you mean create products or offers_with_products - answer is no.

**Comment by hengwo** [comment]
I mean user API to create category 257929 product with api is not support?

**Comment by kfijalko** [comment]
Question is what 'product' is for you?

**Comment by kfijalko** [comment]
Allegro has:
1) offers
2) products - in simplification: offers templates

**Comment by hengwo** [comment]
shoes
category 257929

**Comment by kfijalko** [comment]
ok, i understood,
you must understand that there are two types of objects on the Allegro:
1) offers
2) products - in simplification: offers templates
use offer/product responsibly ;)

**Comment by hengwo** [comment]
use offer/product can create a product?

**Comment by kfijalko** [comment]
@hengwo 
do you want publish offer
or
do you want create product and then publish offer linked with this product
?

**Comment by MaciejFrackowiak** [comment]
@mkaluszka @kfijalko @hahyes Jak widzę nadmiarowy parametr Rodzaj został już usunięty. Przepraszam za zamieszanie.

**Comment by hengwo** [comment]
yes,I am want create product and then publish offer linked with this product

**Comment by kfijalko** [comment]
so,
category 257929 has:
1) options_offers_with_product_publication_enabled=0 - you cant publish offers linked with products
2) options_product_creation_enabled=0 - you cant create products
you can only publish offers not linked with products

**Comment by hengwo** [comment]
ok.i konw.thank you!
