### ISSUE TITLE
Zamykanie Aukcji REST API

### ISSUE THREAD

**Issue by szokart** [allegro/allegro-api#2279]
Występuje problem: 
 - [x] ze środowiskiem produkcyjnym

Wysyłam takie dane:
$date = {"publication":{"action":"END"},"offerCriteria":[{"offers":[{"id":"8507185843"}],"type":"CONTAINS_OFFERS"}]}

Mój skrypt:
curl_setopt($curl, CURLOPT_URL, 'https://api.allegro.pl/sale/offer-publication-commands/'.$aukcja->getUuid());
curl_setopt($curl, CURLOPT_VERBOSE, 1);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
$result = curl_exec($curl);
curl_close($curl);

w odpowiedzi uzyskuje:
Array ( [id] => e10967d5-8a3a-4a62-b58d-0b0850da235a [taskCount] => Array ( [total] => 0 [success] => 0 [failed] => 0 ) ) 

Niby ok, ale aukcja nadal jest aktywna.
Jak wykonuje to zadanie ale uruchamiam aukcje to działa poprawnie.

**Comment by kfijalko** [comment]
1) Zawsze w odpowiedzi otrzymasz pusta tablicę bo przetwarzanie jest asynchroniczne.
2) status wykonania zadania możesz sprawdzić:
https://api.allegro.pl/sale/offer-modification-commands/{commandId}
https://api.allegro.pl/sale/offer-modification-commands/{commandId}/tasks
3)
Używasz $aukcja->getUuid() do generowania id dla command. 
Musisz być pewny, że jest unikatowy dla każdego wywołania.
Jeżeli jest stały dla obiektu $aukcja to może powodować problemy przy wielokrotnym wysyłaniu zadania z tym samym commandId

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem Twoje zgłoszenie - ten UUID e10967d5-8a3a-4a62-b58d-0b0850da235a wykorzystałeś pierwotnie do aktywowania oferty w dniu 21 września 2019. Jeden UUID można użyć tylko jednokrotnie, dlatego kolejna operacja - zakończenie oferty już nie powiodła się. Status operacji możesz zawsze sprawdzić korzystając z zasobu [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).

**Comment by szokart** [comment]
Dziękuje za pomoc faktycznie problem leżał po stonie uzycia stałego $aukcja->getUuid()
