### ISSUE TITLE
[Sandbox] Jak włączyć Allegro Smart w ofercie

### ISSUE THREAD

**Issue by grzybsonssg** [allegro/allegro-api#2280]
Co należy zrobić. a by włączyć opcję Allegro Smart na ofercie w Sandboxie?
Męczę się już od wczoraj i skończyły mi się pomysły. Dodałem odpowiednie opcje dostawy, warunki zwrotu, wysyłkę natychmiastową. O czym jeszcze zapomniałem/nie wiem?

**Comment by MaciejFrackowiak** [comment]
Oprócz wymienionych przez Ciebie warunków konto sprzedającego musi posiadać minimum 5 pozytywnych ocen i średnią z ocen sprzedaży co najmniej 98% - spójrz proszę na [warunki programu](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV).

**Comment by grzybsonssg** [comment]
Dzięki za odpowiedź. Czytałem,ale przyznaję się, że liczyłem na to, że istnieje jakaś skrócona ścieżka, aby ułatwić sobie testowanie. Czyli nie pozostaje mi nic innego jak "nabić" sobie oceny?

**Comment by MaciejFrackowiak** [comment]
Tak, zgadza się.
