### ISSUE TITLE
Wyświetla usunięte oferty

### ISSUE THREAD

**Issue by browin-pziemba** [allegro/allegro-api#2281]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle:  
Oferty zostały usunięte za pomocą panelu i nadal się dostępne przy zapytaniu jak i na panelu, próba ich ponownego usunięcia dostarcza błąd 404.
ID ofert
6206590956
6206590955
6206590620
6206590616
6206590418
6206590417
6206590415
6206590391
6206590364
6206590267
6206590265
6206590242
6206590235
6206590232
6206590229

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi swój ID użytkownika na Sandbox, ponieważ nie mogę namierzyć wskazanych ofert.

**Comment by browin-pziemba** [comment]
SellerID: 44207306

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem sytuację obecnie - wskazane oferty nie są dostępne ani w Moje Allegro na Sandbox, ani w REST API.

**Comment by browin-pziemba** [comment]
Poniżej print screen zrobiony przed chwilą z listą ofert, które od tygodnia są "skasowane".
Zrobić dump ofert z REST API?

![Bez tytułu](https://user-images.githubusercontent.com/55081134/65682213-c9dea180-e05a-11e9-924f-3ac47bfd3277.png)

**Comment by MaciejFrackowiak** [comment]
W samej zakładce Moje oferty oraz odpytując [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) tych ofert nie ma. Twój screen pochodzi z formularza wystawiania - niestety jego “urok” powoduje, że czasami na środowisku testowym są tam widoczne drafty - niestety, nie mamy jak ich usunąć.

**Comment by browin-pziemba** [comment]
Odpytując zasób GET /sale/offers dostaje listę również tych usuniętych, jeżeli zapytam się o GET /sale/offers/{offerID} to dostaję 404.

Poniżej dump z JSONem
[offers.json.txt](https://github.com/allegro/allegro-api/files/3657770/offers.json.txt)

**Comment by MaciejFrackowiak** [comment]
Weryfikując zgłoszenie dla UID: 44207306 przy skorzystaniu z GET /sale/offers dla ofert typu INACTIVE otrzymujemy obecnie:
```
{
   "offers": [],
   "count": 0,
   "totalCount": 0
}
```

**Comment by browin-pziemba** [comment]
Naprawdę jestem ciekaw jak wy to robicie, odpytując zasób https://api.allegro.pl.allegrosandbox.pl/sale/offers?seller.id=44207306&publication.status=INACTIVE
dostaję 20 wyników a wy 0.
Może z innego allegro korzystamy?

**Comment by MaciejFrackowiak** [comment]
Wracam ponownie - korzystamy z tego samego Allegro :) - rzeczywiście, podczas kolejnego wywołania zasobu udało się powtórzyć opisany przez Ciebie problem - przekazałem go do weryfikacji.
