### ISSUE TITLE
Sugestie dotyczące publicznych zasobów

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2282]
Na dzień dzisiejszy REST API uniemożliwia pobranie podstawowych informacji na temat ofert, które zostały wystawione przez użytkowników. Dane są dostępne na allegro więc bez nich nasze oprogramowanie stanie się bezużyteczne w momencie wygaszenia starego Webapi.
Poniżej przedstawiam sugestie: 
1. Listing ofert
- informacja o sprzedanych przedmiotach w danej ofercie (na ten moment jest tylko informacja na temat popularity, która nie umożliwia ustalenia dokładnej sprzedaży, oraz ilość aktualnie dostępnych sztuk),
- obiekt category rozbudowany o nazwę kategorii. W tym momencie przychodzi tylko ID. Kiedy pobiorę 100 ofert, muszę 100 razy odpytać Wasze api o nazwę kategorii. 
- Ilość wyświetleń ofert 
- Informacja czy jest to produkt nowy czy używany. Na ten moment mogę filtorwać po parametrze "parameter.11323" i wtedy wiem czy dostaje produkty nowe czy używane, ale jest to multiselect. Jak pobieram wszystko to nie wiem nic o stanie produktu

2. Pobieranie dowolnej oferty po Id, a w niej pola takie jak description oraz inne szczegóły dostępne publicznie. Jest to KLUCZOWE. 

3. Informacje o sprzedawcy. Na ten moment dostaje tylko jego id oraz rating. Chciałbym mieć chociaż login, żeby móc userów przekierować chociaż na stronę sprzedawcy. 

4. Pobieranie drzewa kategorii. 

5. Pobieranie szczegółów kategorii rozbudowane o możliwość podania kilku id kategorii. 

Proszę pamiętać, że są to podstawowe dane bez których integracja przestanie być możliwa. 
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestie. Przekazuję je do działu odpowiedzialnego za rozwój REST API.

**Comment by marcinja2** [comment]
i jeszcze kwestia sortowania zasobu https://api.allegro.pl/offers/listing. Bardzo potrzebne sortowanie alfabetyczne używane przez wielu przedsiębiorców do wyłapywania zdublowanych aukcji. Wiem że można to zrobić po stronie klienta jednak idąc tym tropem tak można powiedzieć o każdym rodzaju sortowania. Potrzebne jest ono także do masowych choć wybiórczych zmian cen. Sortowanie alfabetyczne gwarantuje nie mieszanie się aukcji między wyświetlanymi stronami (co dawało by efekt tego że nie obniżę lub nie podwyższę niechcący 2x tej samej aukcji)

**Comment by MaciejFrackowiak** [comment]
@marcinja2 Dziękuję za zamieszczoną sugestię. Przekazuję ją dalej.
