### ISSUE TITLE
Popularity w ofertach CLOSED

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2283]
Rozumiem, że parameter popularity w aktywnych ofertach zwraca liczbę unikalnych zakupów przez użytkowników w ciągu ostatnich 30 dni. Czy w tym przypadku to oznacza, że jeżeli użytkownik na aukcji kupi np dwie sztuki to jest on liczony jako jeden unikalny zakup? 
Czy jeżeli jednego dnia kupi 1 sztukę i drugiego dnia 2 sztukę to nadal jest liczony jako jeden zakup? 

---
Popularity dla CLOSED. Jak wygląda parametr popularity dla zamkniętych ofert? Czy zwraca on liczbę zakupów w ciągu ostatnich 30 dni, czyli każdego dnia będzie spadać dla zamkniętej oferty. Czy zwraca on liczbę zakupów na 30 dni wstecz od daty zakończenia oferty? 

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak. Zakupy tego samego użytkownika w ciągu ostatnich 30 dni liczone są jako 1 do popularności. Natomiast nie zwracamy popularności dla zakończonych ofert.

**Comment by artzie92** [comment]
Chyba nie do końca ponieważ przy pobieraniu ofert CLOSED dostaje popularity wypełnione:
![image](https://user-images.githubusercontent.com/16481836/65684297-96eadc80-e05f-11e9-8d3d-d0b7296096be.png)


Request: https://api.allegro.pl/offers/listing?category.id=64477&searchMode=CLOSED&sort=-popularity&limit=1

**Comment by MaciejFrackowiak** [comment]
Sortowanie dla ofert zakończonych nie obejmuje popularności - na dole wywołania możesz znaleźć tablicę z dostępnymi opcjami:
```"sort": [
       {
           "value": "-relevance",
           "name": "trafność",
           "order": "największa",
           "selected": true
       },
       {
           "value": "+price",
           "name": "cena",
           "order": "od najniższej",
           "selected": false
       },
       {
           "value": "-price",
           "name": "cena",
           "order": "od najwyższej",
           "selected": false
       },
       {
           "value": "+withDeliveryPrice",
           "name": "cena z dostawą",
           "order": "od najniższej",
           "selected": false
       },
       {
           "value": "-withDeliveryPrice",
           "name": "cena z dostawą",
           "order": "od najwyższej",
           "selected": false
       },
       {
           "value": "+endTime",
           "name": "czas do końca",
           "order": "najmniej",
           "selected": false
       },
       {
           "value": "-startTime",
           "name": "czas dodania",
           "order": "najnowsze",
           "selected": false
```

Zatem korzystanie z “-popularity” nie gwarantuje zwrócenia poprawnych danych.
