### ISSUE TITLE
[Sandbox][RestAPI] Czy zmiany zasad Smart dla Inspotu są odzwiecieclone w RestAPI?

### ISSUE THREAD

**Issue by grzybsonssg** [allegro/allegro-api#2288]
Od września Allegro rozpoczęło zmianę rozliczania przesyłek Inpost. Czy te zmiany są włączone w Sandbox?

Testuję swoją integrację. W tej chwili scenariusz jest następujący:
* kupuję przedmiot z wysyłką do paczkomatu,kupujący ma aktywny Smart
* z zasobu /order/checkout-forms RestAPI pobieram informacje o zamówieniach:
* w odpowiedzi (mogę załączyć przykład)
  - rodzaj wysyłki to"Allegro Paczkomaty 24/7 InPost"
  - flaga smart jest ustawiona na true;
  - kwota wysyłki jest większa niż 0 zł
  - podana kwota w payment.paidAmount.amount  zawiera przedmiot + wysyłkę
  - tak samo kwota w summary.totalToPay
* tak samo odpowiedź z /payments/payment-operations zwraca kwotę towarówi przesyłki

Czy docelowo w odpowiedzi z API kwota wysyłki będzie wynosić 0zł, a kwota paymentu będzie zawierać tylko cenę towaru? 
Jeśli tak - czy możecie włączyć nowe regulacje dla mojego sprzedawcy w sandboxie już dzisiaj?

**Comment by MaciejFrackowiak** [comment]
Tak, docelowo wysyłka będzie opiewała na kwotę 0 zł. Nie mamy możliwości zarządzanią opcją per konkretne ID sprzedającego na Sandbox.

**Comment by grzybsonssg** [comment]
W takim razie kiedy nowe zasady będą dostępne i odzwierciedlone w API na Sandboxie dla wszystkich?

**Comment by MaciejFrackowiak** [comment]
W nawiązaniu do [komunikatu](https://allegro.pl/pomoc/aktualnosci/zmiana-sposobu-rozliczania-kosztow-dostawy-allegro-smart-5V9YDGoRkuO) zmiany dla wszystkich sprzedających wejdą w życie 1 listopada 2019 - od tego dnia zmiany powinny pojawić się także na Sandbox.

**Comment by grzybsonssg** [comment]
Komunikat mówi o stopniowym wdrażaniu zmiany na produkcji. Czyli jak dobrze rozumiem - przed przełączeniem zostanę o tym wcześniej poinformowany?

**Comment by MaciejFrackowiak** [comment]
Powiadomienie zapewne zostanie wysłane przed rozpoczęciem procedury - jego głównym zadaniem jest przypomnienie o zmianie, która wejdzie w życie 1 listopada 2019.

Koszty przesyłki będą wynosić 0 zł, zatem suma obejmować będzie tylko koszt przedmiotu.
