### ISSUE TITLE
Jak odczytywać ID kategorii słownych?

### ISSUE THREAD

**Issue by adrian282** [allegro/allegro-api#2289]
Np. jakie jest ID kategorii: konsole-i-automaty? Główne kategorie nie mają ID w URL...

**Comment by MaciejFrackowiak** [comment]
ID danej kategorii pobierzesz zasobem [GET /sale/category](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) podając w query params=parent.id ID kategorii nadrzędnej. ID dla konsole i automaty to “42540aec-367a-4e5e-b411-17c09b08e41f”. Zajrzyj także do [naszego poradnika](https://developer.allegro.pl/sale/#step-2).

**Comment by adrian282** [comment]
coś jest nie tak. ID jest liczbowe a nie GUID z tego co zauważyłem. I chodziło metodę na oko - bez użycia API. Tego parametru potrzebuję do offers/listing jako category.id. Poza tym rodzic również nie ma widocznej ID kategorii więc nie wiadomo jaki podać parametr.
Dajmy na to taki URL: https://allegro.pl/kategoria/sprzet-audio-dla-domu-czesci-i-podzespoly-49122
Bez użycia jakiegokolwiek API.

**Comment by MaciejFrackowiak** [comment]
Nasze forum stricte dotyczy API - WebAPI oraz REST API, dlatego w tym zakresie możemy wspomagać. Być może któryś z użytkowników będzie w stanie Ci pomóc przy Twoim rozwiązaniu.

**Comment by frankii91** [comment]
pozostaje jedynie parsowanie i xpath lub regex - jednak to rozwiązanie karkołomne ponieważ struktura stron się zmienia w czasie ... jednak innego wyjścia nie widzę...

**Comment by adrian282** [comment]
pytałem o kategorie główne - tam nie ma co parsować bo to ID jest niewidoczne :|

**Comment by frankii91** [comment]
w kodzie html strony jest :)

**Comment by adrian282** [comment]
pokaż fragment bo ja nie widziałem (ale tez mogłem przeoczyć)

**Comment by WhoCares4400** [comment]
Posiadam plik "csv" oraz "json" z aktualną listą wszystkich kategorii Allegro.
Jeśli są Państwo zainteresowani to proszę kontakt pod adresem mailowym:
whocares4400dev@gmail.com

**Comment by Pawikoski** [comment]
Również posiadam wszystkie kategorie (id + breadcrumb). Mogę przekonwertować do dowolnego formatu pliku, wedle potrzeb.
Przykład jednego rekordu w JSON:
`{"breadcrumb": "Elektronika > Fotografia > Akcesoria fotograficzne > Akcesoria wodoszczelne", "category_id": "28155"}`
Łącznie plik zawiera 25669 rekordów.

Kontakt: pawikoski@gmail.com
