### ISSUE TITLE
Błędna odpowiedź sale offer contacts seller id?

### ISSUE THREAD

**Issue by ladamski49** [allegro/allegro-api#2291]
Mam pytanie odnośnie tego fragmentu dokumentacji:

`https://developer.allegro.pl/news/2018-01-17-news_zarzadzanie_kontaktami/#3)`

Wrzuciłem dokładnie takie samo zapytanie jak jest napisane w dokumentacji (są tam drobne błędy typu nie ma zamknięcia nawiasu):

```
curl -X GET \
'https://api.allegro.pl/sale/offer-contacts/?seller.id=43967138' \
-H 'Accept: application/vnd.allegro.public.v1+json' \
-H 'authorization: Bearer {TOKEN}'
```

I dostaje response:

`{"errors":[{"code":"ACCESS_DENIED","message":"Dostęp zabroniony","details":null,"path":"/sale/offer-contacts/","userMessage":"Dostęp zabroniony"}]}
`

Coś jest raczej nie tak po stronie Allegro endpont? To nie jest wina tokena, ponieważ w innych zapytaniach wszystko działa poprawnie. Dziękuje za pomoc.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie zasobu [GET /sale/offer-contacts](https://developer.allegro.pl/documentation/#operation/getListOfContactsUsingGET) i zwraca on poprawne dane. Musisz pamiętać, że możesz pobrać kontakty tylko zalogowanego użytkownika (to jego ID podajesz w query params=seller.id).
