### ISSUE TITLE
doSendRefundForm - Internal Server Error

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2292]
[RefundRequest.txt](https://github.com/allegro/allegro-api/files/3666165/RefundRequest.txt)

Kurcze, czy tylko ja mam w ostatnim czasie problem z występowaniem o zwrot prowizji przez WebApi?

**Comment by MaciejFrackowiak** [comment]
Widzę, że w polu <dealId> podałeś wartość z “-”. Sprawdź proszę działanie metody dla dealId bez znaku “-”.

**Comment by lukada4100** [comment]
Hehe, Już wszystko jasne. W dokumentacji do doSendRefundForm dealId macie jako long, ale w pobranym od Was WSDLu to int (lub mam nieaktualnego WSDLa). Zmieniało się to może?

**Comment by MaciejFrackowiak** [comment]
Nie, żadne zmiany nie były ostatnio dokonywane w WebAPI.

**Comment by anaxagore78** [comment]
Zmiany były ok tygodnia lub dwóch temu, w metodzie doSendRefundForm
zmienili możliwość podania parametru long, wcześniej był int. Zaktualizuj
wsdl i będzie dobrze.

pon., 30 wrz 2019, 11:34 użytkownik MaciejFrackowiak <
notifications@github.com> napisał:

**Comment by MaciejFrackowiak** [comment]
@lukada4100 Mały update - o zmianie informowaliśmy w poście [GitHub #2209](https://github.com/allegro/allegro-api/issues/2209).

**Comment by lukada4100** [comment]
@anaxagore78 Dzięki. Faktycznie przegapiłem wcześniejszy wątek.
