### ISSUE TITLE
Package is unassigned to offer or category does not match to the package.

### ISSUE THREAD

**Issue by leogiouldasis** [allegro/allegro-api#2294]
Hello, we have established our creating, editing, ending and reactivating process for our adverts, but we keep having a new issue with existing adverts when we try to update them.

```
array:2 [
  "code" => 422
  "message" => {#3028
    +"errors": array:1 [
      0 => {#3029
        +"code": "VALIDATION_ERROR"
        +"message": "Package is unassigned to offer or category does not match to the package."
        +"details": ""
        +"path": ""
        +"userMessage": "Package is unassigned to offer or category does not match to the package."
      }
    ]
  }
]
```
On some existing offers we keep having this issue when updating the offer.
Recreating the offer with the same exact data ( and same package ) fixes the issue, but we don't want to recreate the offer if it is possible.

Are we doing something wrong when updating the offer?

**Comment by MaciejFrackowiak** [comment]
Please, paste full request and response with trace-id which you received. Also remember do not publish sensitive data (full token, etc.)

**Comment by leogiouldasis** [comment]
@MaciejFrackowiak params i said in the request
`array:11 [
  "name" => "Toyota  Yaris  (2017)"
  "category" => array:1 [
    "id" => "145062"
  ]
  "parameters" => array:21 [
    0 => array:4 [
      "id" => "11323"
      "valuesIds" => array:1 [
        0 => "11323_2"
      ]
      "values" => []
      "rangeValue" => null
    ]
    1 => array:3 [
      "id" => "1"
      "values" => array:1 [
        0 => 2017
      ]
      "rangeValue" => null
    ]
    2 => array:3 [
      "id" => "4"
      "values" => array:1 [
        0 => 35818
      ]
      "rangeValue" => null
    ]
    3 => array:3 [
      "id" => "5"
      "values" => array:1 [
        0 => 998
      ]
      "rangeValue" => null
    ]
    4 => array:3 [
      "id" => "14"
      "values" => array:1 [
        0 => 69
      ]
      "rangeValue" => null
    ]
    5 => array:4 [
      "id" => "16"
      "valuesIds" => array:1 [
        0 => "16_1"
      ]
      "values" => []
      "rangeValue" => null
    ]
    6 => array:4 [
      "id" => "13"
      "valuesIds" => array:1 [
        0 => "13_1"
      ]
      "values" => []
      "rangeValue" => null
    ]
    7 => array:4 [
      "id" => "3"
      "valuesIds" => array:1 [
        0 => "3_10"
      ]
      "values" => []
      "rangeValue" => null
    ]
    8 => array:4 [
      "id" => "199"
      "valuesIds" => array:1 [
        0 => "199_2"
      ]
      "values" => []
      "rangeValue" => null
    ]
    9 => array:4 [
      "id" => "12"
      "valuesIds" => array:1 [
        0 => "12_3"
      ]
      "values" => []
      "rangeValue" => null
    ]
    10 => array:3 [
      "id" => "128789"
      "values" => array:1 [
        0 => 5
      ]
      "rangeValue" => null
    ]
    11 => array:4 [
      "id" => "128791"
      "valuesIds" => array:1 [
        0 => "128791_4"
      ]
      "values" => []
      "rangeValue" => null
    ]
    12 => array:3 [
      "id" => "215898"
      "values" => array:1 [
        0 => "VNKKL3D3X0A257237"
      ]
      "rangeValue" => null
    ]
    13 => array:4 [
      "id" => "128794"
      "valuesIds" => array:5 [
        0 => "128794_1"
        1 => "128794_2"
        2 => "128794_2097152"
        3 => "128794_1024"
        4 => "128794_8"
      ]
      "values" => []
      "rangeValue" => null
    ]
    14 => array:4 [
      "id" => "128795"
      "valuesIds" => array:5 [
        0 => "128795_256"
        1 => "128795_1"
        2 => "128795_16"
        3 => "128795_2"
        4 => "128795_32"
      ]
      "values" => []
      "rangeValue" => null
    ]
    15 => array:4 [
      "id" => "128796"
      "valuesIds" => array:3 [
        0 => "128796_16384"
        1 => "128796_32768"
        2 => "128796_32"
      ]
      "values" => []
      "rangeValue" => null
    ]
    16 => array:4 [
      "id" => "128793"
      "valuesIds" => array:7 [
        0 => "128793_8192"
        1 => "128793_16384"
        2 => "128793_2048"
        3 => "128793_2097152"
        4 => "128793_524288"
        5 => "128793_64"
        6 => "128793_1"
      ]
      "values" => []
      "rangeValue" => null
    ]
    17 => array:4 [
      "id" => "211066"
      "valuesIds" => array:1 [
        0 => "211066_246562"
      ]
      "values" => []
      "rangeValue" => null
    ]
    18 => array:4 [
      "id" => "215882"
      "valuesIds" => array:1 [
        0 => "215882_272070"
      ]
      "values" => []
      "rangeValue" => null
    ]
    19 => array:4 [
      "id" => "178"
      "valuesIds" => array:1 [
        0 => "178_1"
      ]
      "values" => []
      "rangeValue" => null
    ]
    20 => array:4 [
      "id" => "128790"
      "valuesIds" => array:1 [
        0 => "128790_2"
      ]
      "values" => []
      "rangeValue" => null
    ]
  ]
  "description" => array:1 [
    "sections" => array:2 [
      0 => array:1 [
        "items" => array:1 [
          0 => array:2 [
            "type" => "TEXT"
            "content" => """
              <p>W Spotawheel sprzedajemy używane samochody w nowatorski sposób – łatwiejszy, wygodniejszy i absolutnie przejrzysty. Wierzymy w nasz proces i naszych pracowników, którzy zrobią wszystko, aby znaleźć dla Ciebie najlepsze samochody na rynku!\r\n
              \r\n
               • To auto nie wymaga kompletnie żadnego wkładu finansowego \r\n
              • Jest bezwypadkowe i z rzeczywistym przebiegiem \r\n
              • Do tego samochodu otrzymujesz raport 180+, kompleksowo informujący o stanie technicznym \r\n
              • Po zakupie masz możliwość zwrotu tego auta w ciągu 7 dni (nie przekraczając 300 kilometrów)\r\n
              \r\n
               Auto z bardzo niskim i potwierdzonym przebiegiem, nie nosi śladów użytkowania. Jego kolor sprawi, że będziesz bardziej oryginalny od swoich sąsiadów. Ekonomiczny, małolitrażowy silnik nie uszczupli Twojego budżetu. Z pewnością nie zbankrutujesz przez paliwo. \r\n
              \r\n
              Nawet do 5 lat gwarancji. \r\n
              \r\n
              Zobacz, jakie opcje posiada: bluetooth, komputer podróży, automatyczny czujnik światła i deszczu, gniazdo USB, system mocowania fotelików Isofix, przyciski do sterowania w kierownicy, teleskopowa regulacja kierownicy, odtwarzacz CD, elektryczne / podgrzewane lusterka, gniazdo Aux.</p>
              """
          ]
        ]
      ]
      1 => array:1 [
        "items" => array:2 [
          0 => array:2 [
            "type" => "IMAGE"
            "url" => "https://e.allegroimg.com/original/039ed4/aad0c83c45f4b0e95ac720df0dca"
          ]
          1 => array:2 [
            "type" => "IMAGE"
            "url" => "https://a.allegroimg.com/original/1198f9/c9dae5b444f7874c98cbb4079cd1"
          ]
        ]
      ]
    ]
  ]
  "sellingMode" => array:4 [
    "format" => "ADVERTISEMENT"
    "price" => array:2 [
      "amount" => 38900
      "currency" => "PLN"
    ]
    "startingPrice" => null
    "minimalPrice" => null
  ]
  "payments" => array:1 [
    "invoice" => "VAT"
  ]
  "location" => array:4 [
    "countryCode" => "PL"
    "province" => "MAZOWIECKIE"
    "city" => "Warszawa"
    "postCode" => "00-057"
  ]
  "external" => array:1 [
    "id" => 238
  ]
  "contact" => array:1 [
    "id" => "4aa7d20a-0534-4e98-86f8-3584ba73785e"
  ]
  "images" => array:16 [
    0 => array:1 [
      "url" => "https://a.allegroimg.com/original/112e07/706553234106bd61f9c41a0465a0"
    ]
    1 => array:1 [
      "url" => "https://a.allegroimg.com/original/115907/da9b574444e0bc8a348cb4b02ba0"
    ]
    2 => array:1 [
      "url" => "https://a.allegroimg.com/original/11319f/4c7d51ed4638a222221224302daa"
    ]
    3 => array:1 [
      "url" => "https://a.allegroimg.com/original/11efb0/e7f650fe45488533c38cec2ee15d"
    ]
    4 => array:1 [
      "url" => "https://a.allegroimg.com/original/11682a/3d7d32a2473994932f406d7e106e"
    ]
    5 => array:1 [
      "url" => "https://a.allegroimg.com/original/113400/528f32c64b34a8670f7b6aa16a2d"
    ]
    6 => array:1 [
      "url" => "https://a.allegroimg.com/original/11d107/bc71569849f6978330342e23c82e"
    ]
    7 => array:1 [
      "url" => "https://a.allegroimg.com/original/11ec09/3a10d2c2480aaa56c7b27ccd72ab"
    ]
    8 => array:1 [
      "url" => "https://a.allegroimg.com/original/110c5d/021ac8aa411eafadc098ad22fc4d"
    ]
    9 => array:1 [
      "url" => "https://a.allegroimg.com/original/111e0e/6a42e8bd4f759cf39edcc28c265b"
    ]
    10 => array:1 [
      "url" => "https://a.allegroimg.com/original/114985/bb2ba79446dabdfc4e8661a3ce7d"
    ]
    11 => array:1 [
      "url" => "https://a.allegroimg.com/original/11ed35/087621344643b643bc75bb8e0849"
    ]
    12 => array:1 [
      "url" => "https://a.allegroimg.com/original/11f008/b6e0c19e44d7b29e2e7063c8cdde"
    ]
    13 => array:1 [
      "url" => "https://a.allegroimg.com/original/118a8d/fe7b54404a4db7c021ff24f17d7b"
    ]
    14 => array:1 [
      "url" => "https://e.allegroimg.com/original/039ed4/aad0c83c45f4b0e95ac720df0dca"
    ]
    15 => array:1 [
      "url" => "https://a.allegroimg.com/original/1198f9/c9dae5b444f7874c98cbb4079cd1"
    ]
  ]
  "id" => "8505555226"
]`

**Comment by leogiouldasis** [comment]
@MaciejFrackowiak 
I also just noticed that advert ids i was getting this error from yesterday, dont produce an error today, and other random ids produce the error.

**Comment by MaciejFrackowiak** [comment]
As I see on example with offer ID 8505555226 - on September 30, 14:03 you made some changes and they were finished with response 200. Later, about 15:16 offer expired after 30 days of publication. After it,  about 16:55 you tried to make some changes but you received error “Package is unassigned to offer or category does not match to the package.” - and it was correct, because when you try to relist offer you have to assign package once again - just look into [our tutorial](https://developer.allegro.pl/en/advertisement/#step-10-offer-publication-commands). At the end, offer was relisted on September 30, 19:10:35.

**Comment by leogiouldasis** [comment]
@MaciejFrackowiak 
Thanks for the clarification, we do know the procedure and we have established a reactivating process that publishes again the package, but we have scheduled incorrectly the procedures so inactive ads where being updated before being reactivated. This is clear now.
