### ISSUE TITLE
SSL: no alternative certificate subject name matches target host name  'api.allegro.pl'

### ISSUE THREAD

**Issue by marypieroszkiewicz** [allegro/allegro-api#2297]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X ] inny

:beetle: **Opis**

Klient ma cały czas problem w wystawianiem aukcji na allegro.
Wyskakuje błąd

SSL: no alternative certificate subject name matches target host name
'api.allegro.pl'

Sklep jest postawiony na SOTE.

Dziękuję za pomoc! Pozdrawiam

**Comment by PawelTaberski** [comment]
Nie wiemy w jaki sposób to oprogramowanie korzysta z naszego API. Nie odnotowaliśmy obecnie podobnych problemów. W sprawie tego problemu skontaktuj się proszę z twórcą tego oprogramowania.
