### ISSUE TITLE
Wznawianie oferty - numer aukcji

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#2298]
Czy API Allegro po automatycznym wznowieniu oferty, gdy parametr: offer/publication/republish ustawiony został na "true" informuje w jakiś sposób o nowym numerze aukcji? Jak można poznać numer pod którym API wznowiło automatycznie ofertę?

**Comment by PrzemyslawLukanowski** [comment]
Nie informujemy wprost o nowym numerze oferty. Skorzystaj z pola external.id - dzięki temu powiążesz oferty i będziesz wiedzieć np., że oferta B, wystawiona później niż oferta A, jest wznowieniem oferty A, ponieważ posiada tę samą wartość tego pola. Możesz także skorzystać z [dziennika ofertowego](https://developer.allegro.pl/documentation/#operation/getOfferEvents) i sugerować się datami zakończenia i aktywacji oferty.
