### ISSUE TITLE
Logowanie do RestApi w C#

### ISSUE THREAD

**Issue by twardyneon** [allegro/allegro-api#23]
Witam, jak pobrać parametry AfterSalesServiceConditionsStruct w WebApi z RestAPI w aplikacji zewnętrznej C#  [nie webowej], Przy zapytaniu z RestApi jest potrzebne zalogowanie do RestApi. Przy logowaniu trzeba zarejestrować aplikację i wskazać url na który wysłany zostanie kod. Jak można by logować się do RestApi w C#? proszę o podpowiedź.

**Comment by MarcinLuczak** [comment]
@twardyneon 
Spróbuj zainstalować wtyczkę WebView - potem ustaw wtyczkę tak, aby korzystała z przeglądarki systemowej zainstalowanej na komputerze użytkownika. Następnie ustaw w swojej aplikacji adres URI do przekierowań, dzięki niemu będzie w stanie otrzymać od nas prośbę o uwierzytelnienie i odebrać kod autoryzacyjny.

Możesz też dodatkowo skonfigurować tzw. Localhost - ustaw na jakim porcie będzie on nasłuchiwał. Adres ten podaj podczas rejestracji aplikacji jako adres URI do przekierowania. Ustawienie portu serwera lokalnego pozwoli tobie otrzymać od nas prośbę o uwierzytelnienie i odebrać kod autoryzacyjny.

Instrukcję pobierania warunków oferty udostępniliśmy [tutaj](https://developer.allegro.pl/new_desc/#02).

**Comment by twardyneon** [comment]
Rozwiązałem problem troszkę inaczej, ale w sumie podobnie. Została utworzona strona[web] w PHP do wygenerowania i przekazania kodu autoryzacyjnego dla aplikacji w c# [działa]. Ale przydało by się bez takich komplikacji.

**Comment by MarcinLuczak** [comment]
@twardyneon 
Cieszę się, że udało Ci się zalogować. W tym momencie nie mamy planów na zmianę procesu logowania do REST API.
