### ISSUE TITLE
[webAPI] doChangeItemFields FID:340 i błąd ERR_SHIPMENT_DESCRIPTION_REQUIRED

### ISSUE THREAD

**Issue by bartek171020** [allegro/allegro-api#230]
Nie rozumiem dlaczego dostaje błąd o dodatkowej informacji o dostawie przy aktualizacji jedynie pola wysyłka w ciągu. Załączam XML.
[SOAP_last_request.txt](https://github.com/allegro/allegro-api/files/2006491/SOAP_last_request.txt)
[SOAP_last_response.txt](https://github.com/allegro/allegro-api/files/2006492/SOAP_last_response.txt)
Dodam, że gdy zaktualizuje aukcje poprzez zwykły formularz problem znika i aktualizacja już działa. W innych aukcjach ten problem nie występuję, a jedynie raz na tydzień jakaś aukcja w ten sposób zaczyna mi dokuczać.

**Comment by esprzedaz** [comment]
Jak edytujesz nowy opis, to i tak musisz jakieś bzdury w starym podać, bo pole o ile nie jest wymagane przy wystawianiu, to jest przy edycji. Tak to działa :D

**Comment by bartek171020** [comment]
Ale ja nie edytuje opisu, tylko pole wysyłka w ciągu.

**Comment by esprzedaz** [comment]
Źle sformułowałem, powinno być: jak edytujesz ofertę z nowym opisem. Wrzuć cokolwiek do fid 24 i sprawdź.

**Comment by bartek171020** [comment]
Niestety dane wysłane z dodatkowym FID'em 24 nic nie zmieniły. Nadał błąd o dodatkowej informacji, chociaż nic w niej nie chce zmieniać.

**Comment by rtnet-pl** [comment]
Prawdopodobnie w FID 13 masz maskę 16, a w FID 27 nie ma nic.
Spróbuj przesłać jakiś opis w FID 27 lub odjąć maskę 16 z FID 13

**Comment by bartek171020** [comment]
Według danych zwracanych poleceniem doGetItemFields w FID'ie 13 mam 48, a FID 27 jest pusty, jednakże na aukcji jest umieszczona i widoczna dodatkowa informacja o dostawie! W związku z powyższym błąd o braku informacji jest w pewnym sensie prawidłowy, ale nieprawidłowa jest rozbieżność pomiędzy danymi dostępnymi w API, a danymi które są widoczne na aukcji.

**Comment by MartaNowaczyk** [comment]
Fid 27 nie powinien być pusty w takiej sytuacji. 

Testowałam oba przypadki i nie udało mi sie powtórzyć błędów tzn. uzyskać fid 27 bez wartości jak również błędu podczas edycji (dodanie/zmiana wartości wysyłka w ciągu). 

Podeślij jeszcze request'a i response'a w którym widać pusty fid 27

**Comment by bartek171020** [comment]
Specjalnie na prośbę załączam aktualne XML'e.
[SOAP_last_request.txt](https://github.com/allegro/allegro-api/files/2015497/SOAP_last_request.txt)
[SOAP_last_response.txt](https://github.com/allegro/allegro-api/files/2015498/SOAP_last_response.txt)

Ogólnie widać na forum, że od ponad tygodnia występuje problem z FID 27, a allegro na razie nie ma czasu aby naprawić tę usterkę, bo są zajęci wymyślaniem nowych zasad: "a teraz wyłączymy stare opisy i może określimy nowe zasady tytułów aukcji, miedzy czasie powysyłamy do nich złe adresy dostaw i zablokujemy FID 27, niech się męczą i jeszcze nam za to płacą...". :) Trochę mi się ulało, ale bardzo dziękuje za wszelką pomoc, musze poczekać do rozwiązania problemu z dodatkową informacją o dostawie to wtedy na pewno inne błędy również znikną, bo są ściśle powiązane. Dziwi mnie po prostu, że taki sztab ludzi nie może rozwiązać tego problemu w takim długim czasie, przecież niedawno to działało i wystarczy poszukać kto co skaszanił!!!

**Comment by MartaNowaczyk** [comment]
Dziękuję za XML'e. Pracujemy nad rozwiązaniem tego problemu.
