### ISSUE TITLE
Parametr 128188

### ISSUE THREAD

**Issue by likrot** [allegro/allegro-api#2300]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://api.allegro.pl/sale/offers

w odpowiedzi dostaję:
`[validation] => stdClass Object
        (
            [errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [code] => VALIDATION_ERROR
                            [message] => Parameter (128188) is not expected.
                            [details] => 
                            [path] => 
                            [userMessage] => Parameter (128188) is not expected.
                        )
                )
            [validatedAt] => 2019-09-30T19:40:45.652Z
        )`

W dniu dzisiejszym w godzinach porannych (10:48) sklep wystawiał aukcje i przeszły weryfikację poprawnie (ta sama kategoria), ale już o godzinie 14:48 został zwrócony komunikat jak powyżej co skutkowało brakiem możliwości wystawienia aukcji.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz ten błąd, ponieważ usunęliśmy parametr 128188 (dostawa z Polski).

**Comment by likrot** [comment]
Dzięki za odpowiedź. Była gdzieś o tym informacja, którą ja po prostu pominąłem?

**Comment by PrzemyslawLukanowski** [comment]
Nie informowaliśmy o usunięciu tego parametru.

**Comment by frankii91** [comment]
Nie łatwiej dla wszystkich by było pomijać takie przekazane nie istniejące parametry niż blokować możliwość wystawienia?, Wystawić aukcje ale np. z od odpowiednim komunikatem..

**Comment by PrzemyslawLukanowski** [comment]
@frankii91 Masz rację, zgłosiłem to do odpowiedniego zespołu.
