### ISSUE TITLE
Przydzielony identyfikator wartości X nie został znaleziony dla parametru słownikowego Y.

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#2301]
Kiedy w końcu poprawicie te komunikaty? Skąd Klient ma wiedzieć co poprawić jak API zwraca mu takie błędy:

**Przydzielony identyfikator wartości 15468_356261 nie został znaleziony dla parametru słownikowego 15468.**

**Comment by PrzemyslawLukanowski** [comment]
Sugestię o doprecyzowanie komunikatów przekazałem do odpowiedniego zespołu. 
Sam błąd informuje o tym, że wartość 15468_356261 nie istnieje dla parametru 15468. Dostępne parametry i ich wartości  można sprawdzić za pomocą zasobu [GET /sale/categories/{categoriesId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by PhotoSoft** [comment]
To już dawno miało być poprawione...

https://github.com/allegro/allegro-api/issues/1784#issuecomment-499530317
