### ISSUE TITLE
IV kwartał 2019

### ISSUE THREAD

**Issue by gslpro** [allegro/allegro-api#2302]
O ile dobrze liczę to dziś jest pierwszy dzień 4 kwartału 2019r, a nie ma jeszcze połowy funkcjonalności rest api, która miała być udostępniona w 3 kwartale.
Szanowne Allegro, dlaczego w swoich zobowiązaniach nie jesteście tak samo konsekwentni i stanowczy jak w przypadku wielkiego wyłączenia z początku czerwca?

**Comment by PrzemyslawLukanowski** [comment]
W najbliższym czasie zaktualizujemy harmonogram. Metody WebAPI wygaszamy z odpowiednim wyprzedzeniem, dając czas na przejście na odpowiedniki w REST API.

**Comment by zetgm** [comment]
Dołączam się to pytania, harmonogram to nie wynik wdrażania tylko jego plan, a tutaj niestety wygląda to inaczej. Funkcjonalność pobierania produktów z ustawionymi atrybutami/parametrami jest niedostępna już pół roku, bo w starym API już nie ma a w nowym jeszcze nie ma. Czy macie Państwo jakiś realny plan wdrożenia zmian?

**Comment by zetgm** [comment]
> W najbliższym czasie zaktualizujemy harmonogram. Metody WebAPI wygaszamy z odpowiednim wyprzedzeniem, dając czas na przejście na odpowiedniki w REST API.

Niestety nie mogę się z tym zgodzić, bo to że wygaszacie to prawda, ale to że dajecie czas na przejście to już nieprawda, bo nie ma na co przejść!

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem - w najbliższym czasie zaktualizujemy informacje zawarte w harmonogramie. Zasób do pobierania publicznych informacji o ofercie powinniśmy udostępnić w czwartym kwartale.

**Comment by zetgm** [comment]
> Tak jak wspomniałem - w najbliższym czasie zaktualizujemy informacje zawarte w harmonogramie. Zasób do pobierania publicznych informacji o ofercie powinniśmy udostępnić w czwartym kwartale.

Czy naprawdę podejście typu: napiszemy kiedy to powinno być - załatwia sprawę?
Jest tak samo precyzyjne jak pojęcie "w najbliższym czasie" - może, dziś może za tydzień, miesiąc czy rok...i co nam zrobicie...
