### ISSUE TITLE
Dlaczego wyskakuje mi błąd , please help !

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2303]
Mój kod znajduje sie poniżej , dlaczego wyskakuje błąd : 
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}`

kod :
`<?php

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "xxxxxx";
    $clientSecret = "xxxxx";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);
	$AccessToken=$tokenObject->access_token;
    return $AccessToken;
}

function main()
{
    $AccessToken=getAccessToken();
	echo "access_token = ".$AccessToken;
	echo '<hr>';
	//var_dump(getMainCategories($AccessToken));
	
	$curl = curl_init();

	curl_setopt_array($curl, array(
	CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING => "",
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 30,
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST => "GET",
	CURLOPT_HTTPHEADER => array(
	"Accept: application/vnd.allegro.beta.v1+json",
	"Authorization: Bearer $AccessToken",
	"Cache-Control: no-cache",
	"Connection: keep-alive",
	"Content-Type: application/vnd.allegro.beta.v1+json",
	"Host: api.allegro.pl",
	"accept-encoding: gzip, deflate",
	"cache-control: no-cache"
	)));
	
	$response = curl_exec($curl);
	$err = curl_error($curl);

	curl_close($curl);

	if ($err) {
	echo "cURL Error #:" . $err;
	} else {
	echo $response;
	}
}
main();

**Comment by PrzemyslawLukanowski** [comment]
Korzystasz z autoryzacji typu client_credentials, która umożliwia dostęp do publicznych danych (np. pobieranie listy kategorii, przeglądanie listy ofert ). W przypadku GET order/event-stats konieczna jest autoryzacja typu [code_flow](https://developer.allegro.pl/auth/#app) lub [device_flow](https://developer.allegro.pl/auth/#DeviceFlow). Informację o tym, jaki rodzaj autoryzacji wykorzystuje dany zasób, znajdziesz w naszej dokumentacji, na początku opisu każdego zasobu - bearer-token-for-user (code lub device flow) lub bearer-token-for-application (client credentials).

**Comment by jasiek07** [comment]
Ok jak zatem przerobić poniższy kod by uzyskiwać dostęp do zasobów uzytkownika :
`function getAccessToken(): String
{
$authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
$clientId = "xxxxxx";
$clientSecret = "xxxxx";

$ch = curl_init($authUrl);

curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERNAME, $clientId);
curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);`

**Comment by jasiek07** [comment]
Czy mógłbym dział allegro prosić o odpowiedź na powyższe ?

**Comment by PrzemyslawLukanowski** [comment]
Z językiem PHP niestety nie pomożemy - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie pomóc.

**Comment by jasiek07** [comment]
Dobra to inaczej sformułuje zagadnienie opierając się oczywiście na dokumentacji WEBAPI. 
Czy za każdym razem do uzyskania tokenu metodą CODEFLOW LUB DEVICEFLOW , musimy używać adresu http://allegro.........   z tym przekierowaniem &redirect_uri=......
?????
Znamy przecież Client ID oraz Client Secret . 
Czy mogę od Państwa prosić przykładowy skrypt do uzyskania tokenu potrzebnego dla dostępu do informacji zalogowanego użytkownika. 
Napewno Państwo taki posiadacie , nie może być inaczej .

**Comment by PrzemyslawLukanowski** [comment]
Redirect_uri musi być przekazane w autoryzacji typu code flow - na wskazany adres powrotu zostanie przesłany kod potrzebny do uzyskania tokena oraz sam access token. Adres musi być identyczny z tym podanym przy rejestracji, możesz podać ich kilka - każdy od nowej linii.
Nie posiadamy przykładowego skryptu, ale wątek generowania tokenu w PHP przewinął się w poniższych wątkach. Być może wśród nich znajdziesz wskazówki dotyczące Twojego problemu:

https://github.com/allegro/allegro-api/issues/708
https://github.com/allegro/allegro-api/issues/226
