### ISSUE TITLE
Brak danych do faktury

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2304]
Witam,
REST API nie pobiera danych do faktury, według dokumentacji powinny one być podane w invoice => address => company => taxId, tymczasem już invoice => address => company jest NULL-em. Nie pojawiają się one również w żadnym innym polu.
WebApi dla tego samego zamówienia podaje nazwę firmy oraz NIP.
Przykładowe zamówienie  fc8e4b02-dec8-11e9-875d-111054466fe5, jest to zamówienie "produkcyjne"

**Comment by mzawodzinski** [comment]
Jest READY_FOR_PROCESSING, jeśli jest inny status to nie ma praktycznie żadnych danych - o tym akurat wiem ;)

**Comment by PrzemyslawLukanowski** [comment]
REST API zwraca informacje o fakturze. Pole company jest nullem, ale wszystkie inne pola są uzupełnione, w tym naturalPerson.firstName i naturalPerson.lastName, co świadczy o tym, że klient wybrał opcję faktury dla osoby prywatnej. Formularz zamówienia w WebAPI również zawiera puste pole company. Weryfikujemy, skąd wzięła się wartość w polu postBuyFormAdrNip.

**Comment by PrzemyslawLukanowski** [comment]
@mzawodzinski zweryfikowałem to - w tym przypadku kupujący podał nr NIP (bez podawania nazwy firmy), po czym przełączył się na zakładkę faktura dla osoby prywatnej, gdzie uzupełnił komplet danych - tak powstała rozbieżność. Wprowadzimy odpowiednią poprawkę.
