### ISSUE TITLE
Problem z wystawianiem ofert i produktyzacją

### ISSUE THREAD

**Issue by baza** [allegro/allegro-api#2305]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Występuje problem z produktyzacją
mimo otrzymania id produktu: 24a2006c-54cf-46ec-8856-5f3d6651dcca
przy próbie wystawienia otrzymuję
{"errors": [{"code": "NotFoundException", "path": null, "details": null, "message": "Not Found", "userMessage": "Invalid request. Please contact the application author."}]}

ten sam problem występuje gdy próbuję poprawić ręcznie na aukcji 
otrzymuję komunikat "Nie można pobrać danych produktu"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Zweryfikowałem to - występuje błąd przy odpytywaniu o ten produkt. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by baza** [comment]
Na dzień dzisiejszy mam ok 1000 takich produktów. Może gdzieś podeśle listę?

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę tę listę za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #2305

**Comment by PrzemyslawLukanowski** [comment]
Produkty pochodzą ze starej wersji tecdoc, usunęliśmy je.

**Comment by baza** [comment]
Mhhh to dziwne bo posługuję się najwowszą wersją tecdoc i produkty te istnieją. 
TECDOC nie usuwa produktów z bazy danych nadaje im tylko status  np.Wycofany.

W większości brakuje towarów które mają polskie znaki w nazwie.

Numer artykułu: 37858  (ABS)
Status artykułu  Normal 
Jednostka pakowania1 
Nr EAN 8717109513707 
Towar ten istnie jak najbardziej w TecDoc  przecież odpytuję o niego i dostaję odpowiedz

{"products": [{"id": "655cb85a-0b30-43b2-9245-249fa8e6da2d", "name": "Zestaw klocków hamulcowych, hamulce tarczowe A.B.S. 37858", "images": [], "category": {"id": "250405"}, "parameters": [{"id": "215858", "name": "Numer katalogowy części", "values": ["37858"], "options": {"identifiesProduct": true}, "valuesLabels": ["37858"]}]}]}

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuję - usunęliśmy podany w zgłoszeniu produkt 24a2006c-54cf-46ec-8856-5f3d6651dcca oraz inne, ze starszej wersji tecdoc. Nie otrzymaliśmy Twojej listy - czy dopisałeś w nim numer zgłoszenia z GitHuba? 
Dla produktu 655cb85a-0b30-43b2-9245-249fa8e6da2d zwracamy prawidłowe dane. Czy w przypadku powiązania oferty z tym produktem również otrzymujesz podany wcześniej błąd? Jeśli tak, prześlij proszę tutaj przykładowy request oraz response (pamiętaj o wykasowaniu informacji o tokenie).

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy listę, weryfikujemy ten temat.

**Comment by PrzemyslawLukanowski** [comment]
Produkty zostały usunięte ze względu na nieprawidłowości w powiązaniu z naszą bazą. Pracujemy nad ich przywróceniem, będa wtedy dostępne pod nowymi id.
