### ISSUE TITLE
Czy ktoś posiada przykład skryptu do uzyskiwania tokenu dostępowego dla pobierania informacji zalogowanego użytkownia???

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2306]
Czy ktoś posiada przykład skryptu do uzyskiwania tokenu dostępowego dla pobierania informacji zalogowanego użytkownika??? Poniższy kod  przekaże token ale taki za pomocą którego można sobie wyświetlić liste kategorii allegro , a mnie chodzi o token który posłuży do pobierania np. listy zamówień użytkownika  , dziennika zdarzeń itp.
`function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "xxxxxx";
    $clientSecret = "xxxx";
	
    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false) { exit ("brak tokkenu"); }
	if ($resultCode !== 200) { exit ("adres strony nie istnieje , Something went wrong"); }

    $tokenObject = json_decode($tokenResult);
	$AccessToken=$tokenObject->access_token;
    echo $AccessToken;
	return $AccessToken;
}

**Comment by imper86** [comment]
@jasiek07  skoro używasz client_credentials to nie dziw się, że nie masz dostępu do danych użytkownika, bo dostajesz token aplikacji, a nie użytkownika.

Widzę, że używasz php, więc jeśli chcesz, możesz użyć mojej biblioteki:
https://github.com/imper86/allegroapi
Informacje nt tego jak za jej pomocą uzyskać token znajdziesz [tutaj](https://github.com/imper86/allegroapi/blob/master/docs/authorization.md)

**Comment by jasiek07** [comment]
I o to mi chodziło , dziękuję za rzeczową i merytoryczną odpowiedź

**Comment by jasiek07** [comment]
no dobra nadal błądze jak mucha w maśle , pozyżej opisana metoda jest przeokrutnie rozbudowana i dla niskozaawansowanego zbyt skomplikowana , czy byłbyś tak miły i napisał mi jak to poniższe miało by wyglądać napisane pod CURL w php :
`curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(client_id:client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'`

**Comment by anaxagore78** [comment]
Poprobuj  w Insomni - https://insomnia.rest/, jak Ci sie uda mozesz w niej  wygenerowac kod dla PHP.

**Comment by imper86** [comment]
@jasiek07 z phpowego curl'a nie korzystałem x-lat i nie chce mi się w to wgłębiać :).
Jest od zarąbania gotowych klientów http, które ułatwią Ci życie - guzzle, symfony/http-client itd.

Na przykładzie guzzle wystarczy:
```php
$allegroClientId = 'xxx';
$allegroClientSecret = 'xxx';

$client = new GuzzleHttp\Client();
$response = $client->post('https://allegro.pl/auth/oauth/device', [
    'auth' => [$allegroClientId, $allegroClientSecret],
    'headers' => [
        'Content-Type' => 'application/x-www-form-urlencoded',
    ],
    'body' => http_build_query(['client_id' => $allegroClientId])
]);

var_dump((string)$response->getBody());
```
