### ISSUE TITLE
[REST API] order/events anulowane przez klienta/kupującego

### ISSUE THREAD

**Issue by madkot** [allegro/allegro-api#2307]
Dzień dobry

Zacytuję informacje ze strony "[Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/)":

> Metodą GET na zasobie /order/events pobierzesz zdarzenia, które pozwolą Ci monitorować akcje, które wykona klient, takie jak:
> zakup,
> wypełnienie formularza opcji dostawy (FOD),
> **anulowanie płatności,**
> realizacja dopłaty.

W eventach zwracane są 3 statusy (FILLED_IN, BOUGHT, READY..), jak więc rozpoznać anulowane płatności przez klienta?

**Comment by PrzemyslawLukanowski** [comment]
Anulowanie płatności wygeneruje kolejny event “FILLED_IN”. Anulowanie płatności rozpoznasz więc po tym, że dla jednego checkout-forma występuje dwa razy zdarzenie FILLED_IN.

**Comment by kulisz** [comment]
@PrzemyslawLukanowski podłącze się do pytania - a co w przypadku gdy klient wypełni kilka razy FOD czym wygeneruje kilka FILLED_IN w eventach, a na koniec jednak zrezygnuje? 
W tym przypadku zdarzenie FILLED_IN będzie występowało więcej niż 2 razy, więc w jaki sposób rozpoznać czy zamówienie/płatność zostało anulowana?

**Comment by PrzemyslawLukanowski** [comment]
Status FILLED_IN następuje dopiero w momencie wypełnienia FODa oraz rozpoczęcia płatności. Następne wypełnienie FODa może mieć miejsce dopiero po anulowaniu poprzedniej płatności. Jeżeli więc np. zauważysz 3x zdarzenie FILLED_IN dla tego samego checkout-forma, oznacza to, że kupujący rozpoczął płatność, anulował ją, a następnie ją wznowił.

**Comment by kulisz** [comment]
@PrzemyslawLukanowski poniżej mam przykład zakupu jednego z klientów, gdzie występuje dwa razy status FILLED_IN. 
Gdybym się stosował do zasady 2-krotnego wystąpienia FILLED_IN to bym musiał oznaczyć sobie to zamówienie/płatność jako anulowane co w tym przypadku nie miało miejsca, bo później i tak dostałem READY_FOR_PROCESSING

` 
{:id=>"1570350034668200", :order=>{:seller=>{:id=>"380xxxxx"}, :buyer=>{:id=>"342xxxx", :email=>"whxxxxxxxxxxxxxxxxxxx@allegromail.pl", :guest=>false, :login=>"Kxxxxxxa"}, 
  :lineItems=>[{:offer=>{:id=>"628xxxxxxx", :name=>"FILTR do XXXXXXXXX XXXXXXXX", :external=>nil}, :price=>{:amount=>"5.50", :currency=>"PLN"}, 
  :id=>"0ad1fca0-e812-11e9-9017-ff23baa93817", :quantity=>8, :originalPrice=>{:amount=>"5.50", :currency=>"PLN"}, :boughtAt=>"2019-10-06T08:20:21.705Z"}], 
  :checkoutForm=>{:id=>"0ad1fca2-e812-11e9-9017-ff23baa93817"}}, :type=>"BOUGHT", :occurredAt=>"2019-10-06T08:20:21.705Z"}, 
  
  {:id=>"1570350052065911", :order=>{:seller=>{:id=>"380xxxxx"}, :buyer=>{:id=>"342xxxx", :email=>"whxxxxxxxxxxxxxxxxxxx@allegromail.pl", :guest=>false, :login=>"Kxxxxxxa"}, 
  :lineItems=>[{:offer=>{:id=>"628xxxxxxx", :name=>"FILTR do XXXXXXXXX XXXXXXXX", :external=>nil}, :price=>{:amount=>"5.50", :currency=>"PLN"}, 
  :id=>"0ad1fca0-e812-11e9-9017-ff23baa93817", :quantity=>8, :originalPrice=>{:amount=>"5.50", :currency=>"PLN"}, :boughtAt=>"2019-10-06T08:20:21.705Z"}], 
  :checkoutForm=>{:id=>"0ad1fca2-e812-11e9-9017-ff23baa93817"}}, :type=>"FILLED_IN", :occurredAt=>"2019-10-06T08:20:37.307Z"}, 
  
  {:id=>"1570350061344793", :order=>{:seller=>{:id=>"380xxxxx"}, :buyer=>{:id=>"342xxxx", :email=>"whxxxxxxxxxxxxxxxxxxx@allegromail.pl", :guest=>false, :login=>"Kxxxxxxa"}, 
  :lineItems=>[{:offer=>{:id=>"628xxxxxxx", :name=>"FILTR do XXXXXXXXX XXXXXXXX", :external=>nil}, :price=>{:amount=>"5.50", :currency=>"PLN"}, 
  :id=>"0ad1fca0-e812-11e9-9017-ff23baa93817", :quantity=>8, :originalPrice=>{:amount=>"5.50", :currency=>"PLN"}, :boughtAt=>"2019-10-06T08:20:21.705Z"}], 
  :checkoutForm=>{:id=>"0ad1fca2-e812-11e9-9017-ff23baa93817"}}, :type=>"FILLED_IN", :occurredAt=>"2019-10-06T08:20:47.564Z"}, 
  
  {:id=>"1570350062091773", :order=>{:seller=>{:id=>"380xxxxx"}, :buyer=>{:id=>"342xxxx", :email=>"whxxxxxxxxxxxxxxxxxxx@allegromail.pl", :guest=>false, :login=>"Kxxxxxxa"}, 
  :lineItems=>[{:offer=>{:id=>"628xxxxxxx", :name=>"FILTR do XXXXXXXXX XXXXXXXX", :external=>nil}, :price=>{:amount=>"5.50", :currency=>"PLN"}, 
  :id=>"0ad1fca0-e812-11e9-9017-ff23baa93817", :quantity=>8, :originalPrice=>{:amount=>"5.50", :currency=>"PLN"}, :boughtAt=>"2019-10-06T08:20:21.705Z"}], 
  :checkoutForm=>{:id=>"0ad1fca2-e812-11e9-9017-ff23baa93817"}}, :type=>"READY_FOR_PROCESSING", :occurredAt=>"2019-10-06T08:20:47.564Z"}, 
  `

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nie miało miejsca ponowne wypełnienie FOD-a. Drugi status FILLED_IN został wygenerowany przez zakończenie płatności - zwróć uwagę, że data drugiego statusu FILLED_IN jest identyczna z datą eventu READY_FOR_PROCESSING. Przepraszam zatem za wprowadzenie w błąd, opisany przeze mnie scenariusz nie zawsze musi oznaczać anulowanie płatności. Allegro działa na strukturze rozproszonej, dlatego jeden status może pojawić się więcej niż raz. Jednak jeśli chcesz wykryć anulowaną płatność za pomocą dziennika zdarzeń - status FILLED_IN, który występuje kilka razy w ramach jednego checkout-forma jak najbardziej może na to wskazywać.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski zbyt dużo jest to domniemywań. Postuluje by pojawił się po prostu statusu Cancelled w RESTAPI dla takiego zamówienia. Inaczej nigdy nie da się że 100% pewnością stwierdzić czy zamówienie jest anulowane czy nie. A w sumie o to nam chodzi by wszystkim było łatwiej :)

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba Anulowanie płatności nie jest jednoznaczne z anulowaniem zamówienia. Ono wciąż istnieje, a samą płatność można powtórzyć, co będzie skutkować kolejnym statusem FILLED_IN. Niemniej jednak, rozumiem potrzebę posiadania konkretnego eventu dla takiego zdarzenia, dlatego też przekazuję to jako sugestię do działu odpowiedzialnego za rozwój API.
