### ISSUE TITLE
Nie można aktywować niektórych szkiców

### ISSUE THREAD

**Issue by sakowicz** [allegro/allegro-api#2308]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od kilku dni mamy problem z aktywacją szkiców. Jakieś 15% wszystkich szkiców nie zostaje aktywowana. 
Requesty są wysyłane na zasób `sale/offer-publication-commands/`. Zawsze każdy draft zostawał aktywowany jednak od kilku dni niektóre z nich nie chcą się aktywować. 
Przykład draftu: _8538542259_ i wasz response do niego: 
`{"id":"42a806b0-f4ff-470a-90b7-2236f5bb89ec","taskCount":{"total":0,"success":0,"failed":0}}`

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz same zera, ponieważ przetwarzanie jest asynchroniczne. Prawidłowy status odpowiedzi sprawdzisz za pomocą GET sale/offer-publication-commands/uuid/tasks, w tym przypadku było to FAIL. Po sprawdzeniu oferty za pomocą GET /sale/offers/{offerId} walidacja na końcu odpowiedzi zwraca konkretną informację - "Parameter (128188) is not expected.". Ten parametr (dostawa z Polski) został w ostatnich dniach usunięty. Przesłanie struktury bez tego parametru pozwoli poprawnie aktywować ofertę.
