### ISSUE TITLE
GET /sale/shipping-rates/{shippingRatesId} - z dokumentacji

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2309]
Nie mogę zrozumieć części dokumentacji od "szczegółów danego cennika"

a dokumentacji mamy:
curl -X GET \
https://api.allegro.pl/sale/shipping-rates/fde5853c-01ce-4991-a4b3-994c1a4a408e\
-H 'Accept: application/vnd.allegro.public.v1+json' \
-H 'Authorization: Bearer {token}'
        
{
"id": "fde5853c-01ce-4991-a4b3-994c1a4a408e",                   -- identyfikator 
                                                                danego cennika dostaw
"name": "Cennik dostawy dla elektroniki",                        -- nazwa 
                                                                danego cennika dostaw
{
    "id": "ed1645ab-0895-4010-bd85-bb5d92ab0d83",    -------- co to jest ? jeśli id cennika  mamy wyżej.
    "name": "Cennik dostawy test API 1",                          -------- co to jest ? jeśli nazwę cennika  mamy wyżej. 

To co niżej nie budzi wątpliwości ...
    "rates": [
        {
            "deliveryMethod": {
                "id": "9081532b-5ad3-467d-80bc-9252982e9dd8"    -- identyfikator 
                                                                danej metody dostawy.....
........
........

Proszę o pomoc w zrozumieniu. Ponieważ tworząc cennik dostawy podaję nazwę oraz deliveryMethod.... Czy to błąd w dokumentacji ?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje za zwrócenie uwagi, dwa pierwsze pola są nadmiarowe, dzisiaj poprawimy ten opis. Dokumentację dla tego zasobu znajdziesz [tutaj](https://developer.allegro.pl/documentation/#operation/getShippingRatesSetUsingGET), wspomnianiana treść pochodzi z [poradnika](https://developer.allegro.pl/sale/#shipping-rates).
