### ISSUE TITLE
Zamówienie WebApi

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#231]
Czy jest możliwość, żeby za pomocą WebApi oznaczyć zamówienie jako wysłane?

**Comment by MaciejPotepa** [comment]
Jeżeli chodzi **dokładnie** o oznaczenie zamówienia jako wysłane to na ten moment nie ma takiej możliwości w WebAPI i REST API.

**Comment by lukada4100** [comment]
ok

**Comment by PiotrLaszczyk** [comment]
Odświeżam wątek, 

Czy jest lub może czy w ogóle będzie możliwość oznaczania jako 'wysłane' za pomocą RESTa?

**Comment by MaciejPotepa** [comment]
@PiotrLaszczyk jesteśmy świadomi takiej potrzeby, natomiast nie mamy tego jeszcze w planach. Jeżeli coś się zmieni w tej kwestii to będziemy  o tym informować.
