### ISSUE TITLE
Dokumentacja błąd

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2310]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
 W dokumentacji jest:
https://developer.allegro.pl/sale/#shipping-rates

Szczegóły danego cennika sprawdzisz metodą GET na zasobie /sale/shipping-rates/{shippingRatesId}.

curl -X GET \
https://api.allegro.pl/sale/shipping-rates/fde5853c-01ce-4991-a4b3-994c1a4a408e\
**-H 'Accept: application/vnd.allegro.public.v1+json' \
-H 'Authorization: Bearer {token}'**

niżej link kierujący i wprowadzający zamieszanie 
W tym **artykule** opisaliśmy szczegółowo, jak zarządzać cennikami dostawy na koncie sprzedawcy i w jego ofertach.
https://developer.allegro.pl/news/2018-08-14-cenniki_dostawy/

a tutaj
curl -X GET \
'https://api.allegro.pl/sale/shipping-rates?seller.id={Seller_ID}' \
**-H 'Accept: application/vnd.allegro.beta.v1+json' \
-H 'Authorization: Bearer {token}' \
-H 'content-type: application/vnd.allegro.beta.v1+json'**

Aby wyłapać błąd co jest źle naprawdę stracone trochę czasu ...
Ps. Czemu nikt nie aktualizuje dokumentacji....

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję ponownie za spostrzeżenie. W [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListOfShippingRatestUsingGET) znajdziesz prawidłowy opis zasobu. Wspomniany artykuł dzisiaj zaktualizujemy.
