### ISSUE TITLE
Jak pobrać listę wyróżnionych ofert zalogowanego użytkownika ?

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2311]

**Comment by PrzemyslawLukanowski** [comment]
Przez zasób GET sale/offers jest to niemożliwe, możesz użyć zasobu [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), podając jako parametr seller.id={sellerId}. Wyróżnione oferty otrzymasz w tablicy promoted. Zgłosiłem sugestię do odpowiedniego zespołu, aby wprowadzić taki filtr w zasobie GET /sale/offers.
