### ISSUE TITLE
POST  /order/checkout-forms/{id}/shipments

### ISSUE THREAD

**Issue by Piotr1480** [allegro/allegro-api#2312]
**POST  /order/checkout-forms/{id}/shipments**
Za pomocą tego żądania będę przekazywał numer śledzenia przesyłki. W Body muszę przekazać dane poniżej:
{   "carrierId": "UPS",
    "waybill": "string",
    "carrierName": "string",
    "lineItems": 
[      {  "id": "string" }
    ]
}
LineItems są to pozycje zamówienia ale czym jest znacznik "id"? W jakim formacie go przekazywać? Ewentualnie jak pobrać informacje o "id"?

**Comment by PrzemyslawLukanowski** [comment]
Jest to id przedmiotu z zamówienia, który przekazujesz w formacie UUID - czyli takim, w jakim go otrzymujesz przy odpytaniu konkretnego zamówienia przez GET order/checkout-forms/{checkoutFormId}.

**Comment by j4r3kb** [comment]
Czy ten endpoint na sandboxie działa poprawnie?
Wykonuję testowe requesty z Postmana lub CURLem i oto co otrzymuję:
request:
```
curl -H "Content-Type: application/vnd.allegro.public.v1+json" -H "Accept: application/vnd.allegro.public.v1+json" -H "Authorization: Bearer eyJhb...fhYA" -i -X POST https://allegro.pl.allegrosandbox.pl/order/checkout-forms/e2fd38d0-06d8-11ea-b1d0-5502b900086e/shipments
```

response
```
HTTP/2 404 
date: Fri, 06 Dec 2019 15:28:37 GMT
content-length: 72
x-varnish: 574342301
x-waf: waf-1a
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000
set-cookie: _cmuid=3kxazgrs-e0c3-577p-1g89-pzzzmp9sw2xx; Expires=Sun, 05 Dec 2021 15:28:37 GMT; Path=/; Domain=.allegro.pl.allegrosandbox.pl; Secure

<!--Director transaction_orderfrontend has no backends or is disabled-->
```

**Comment by j4r3kb** [comment]
Czy ten endpoint na sandbox działa poprawnie?
W odpowiedzi otrzymuję status 200 oraz body

```
{
    "shipments": []
}
```

nic takiego w dokumentacji nie ma.

**Comment by MaciejFrackowiak** [comment]
Tak, ten zasób działa prawidłowo na Sandbox.
Dla podanego przez Ciebie trace-id i odpowiadającego mu zamówienia nie dodano numeru przesyłki, dlatego zwracamy pusty wynik.

**Comment by j4r3kb** [comment]
Obecnie na tym zasobie otrzymuję 503 
```
{
    "errors": [
        {
            "code": "SERVICE_UNAVAILABLE",
            "message": "Service unavailable.",
            "details": null,
            "path": null,
            "userMessage": "Service unavailable. Please try again in a few minutes."
        }
    ]
}
```
