### ISSUE TITLE
[WebApi] Dopłata do zamówienia - niewidoczna w dzienniku zdarzeń

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2313]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
W dzienniku zdarzeń WebApi ( DoGetSiteJournalDeals ), dla zamówienia  dealTransactionId.1082838555 nie widać informacji o dopłacie. 

Data sprzedaży: 26 wrz 2019, 03:20 [widoczne w dzienniku zdarzeń WebApi]
Data dopłaty: 2 paź 2019, 21:02

Identyfikator płatności dopłaty:
338454e2-e547-11e9-977d-3de417fd271d

Przy próbie odpytania o dopłatę w WebApi (doGetMyIncomingPayments) jest ona widoczna:
#payTransId: 1086490831
#payTransMainId: 1082838555

Dopłata jest widoczna w panelu zamówień Allegro jak również w nowym dzienniku zdarzeń (event.id 1570089170078601)

**Comment by PrzemyslawLukanowski** [comment]
Metoda DoGetSiteJournalDeals nie zwraca eventu związanego z dopłatą. Przez REST API możesz to sprawdzić za pomocą [GET /order/events](https://developer.allegro.pl/documentation/) - w przypadku dopłaty otrzymasz dodatkowe zdarzenie ze statusem “READY_FOR_PROCESSING”.
