### ISSUE TITLE
Problem z /pricing/fee-preview

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#2315]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mamy podobne problemy jak w wątku https://github.com/allegro/allegro-api/issues/1601
Podczas odpytywania API na końcówkę `/pricing/fee-preview` dostajemy błąd z mało czytelną wiadomością "**Request body was not readable**". Dotyczy to tylko kilku kategorii, przykładowa ma ID `260041`, trace-id `2a6711c2b26800f2`. Na innych kategoriach wszystko działa prawidłowo.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem Twoje zgłoszenie, problemem jest wartość, którą przekazałeś w polu duration - "0". Usunięcie tej wartości eliminuje błąd.

**Comment by j4r3kb** [comment]
ok problem u nas można zamknąć.
