### ISSUE TITLE
Pobranie danych o użytkowniku 

### ISSUE THREAD

**Issue by ArkadiuszWilQ** [allegro/allegro-api#2316]
Czy jest dostępny endpoint Rest API który zwróci adres email zalogowanego użytkownika, jak jest to możliwe przy -> https://allegro.pl/login/user ? 
Dokładnie potrzebny mi email używany do logowania, nie do kontaktu. Bez warunku posiadania aukcji na koncie.
Próbowałem szukać informacji w dekodowanym access tokenie, jak i przewertowałem całą dokumentację, ale niestety bez skutku.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie zwracamy takiej informacji. Zgłosiłem to jako sugestię do odpowiedniego zespołu, aby zasób [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) zwracał takie pole.

**Comment by neldh** [comment]
Również potrzebowalibyśmy tego maila.

**Comment by PrzemyslawLukanowski** [comment]
@neldh Dodałem Twoją prośbę do zgłoszenia.

**Comment by hYOUstone** [comment]
Również mi jest potrzebny email zalogowanego. Jest to potrzebne po naszej stronie do weryfikowania istnienia konta użytkownika. weryfikacja odbywa się po faktycznym mail'em użytkownika.

**Comment by PrzemyslawLukanowski** [comment]
@hYOUstone Przekazałem Twoje zgłoszenie do odpowiedniego zespołu.

**Comment by kylovile** [comment]
Witam, jak sytuacja pobrania emaila zalogowanego użytkownika?

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad tym, dodamy takie pole. Na tę chwilę nie mogę wskazać przybliżonego terminu, opublikujemy odpowiedni komunikat.

**Comment by kylovile** [comment]
Ok, a istnieje jakiś zasób w Rest Api w którym znajdę ten adres email?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie, udostępnimy to dopiero w GET /me.

**Comment by PrzemyslawLukanowski** [comment]
[Dodaliśmy informację ](https://developer.allegro.pl/news/#email-and-address-in-/me)o mailu i NIP w GET /me.
