### ISSUE TITLE
 GET na zasobie /sale/shipping-rates/{shippingRatesId} nieścisłość / błąd

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2317]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x ] z logowaniem lub autoryzacją
 - [x ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
 tu
https://developer.allegro.pl/sale/
GET na zasobie /sale/shipping-rates/{shippingRatesId}.

 "shippingTime": {                                   -- czas dostawy, 
                "from": "PT72H",                                wielokrotność 24H, 
                "to": "PT120H"                                  zgodnie z formatem ISO 8601
            }                               

a pobierając dane dla przykładowego cennika zrobionego ręcznie przez www
gdzie czas wysyłki mamy domyślny dla "Przesyłka kurierska" ( zwykła i pobranie)
"deliveryMethods": [
    {
      "id": "7203cb90-864c-4cda-bf08-dc883f0c78ad",
      "name": "Przesyłka kurierska",
      "paymentPolicy": "IN_ADVANCE",
      "allegroEndorsed": false,
      "shippingRatesConstraints": {
        "allowed": true,
        "maxQuantityPerPackage": {
          "max": 999999
        },
        "firstItemRate": {
          "min": "0.00",
          "max": "100000000.00",
          "currency": "PLN"
        },
        "nextItemRate": {
          "min": "0.00",
          "max": "100000000.00",
          "currency": "PLN"
        },
        **"shippingTime": {
          "default": {
            "from": "PT24H",
            "to": "PT48H"
          },**
          "customizable": true
        }
      }
    },

to po stronie www
        **"shippingTime": {
          "default": {
            "from": "PT24H",
            "to": "PT48H"
          },**

dane wyświetlają się 1-2 dni  jednak pobierając 
GET na zasobie /sale/shipping-rates/{shippingRatesId}.
Dostajemy w odpowiedzi
  "shippingTime": null

wiec coś jest tu nie tak, ... i problem występuje tylko dla wartości domyślnych np. 1-2 dni niezależnie czy zapiszemy czy nie dla wartości 1-2 dni jest ok dla 2-2 dni też jest ok

W innych sposobach dostaw problem też występuje - dla wartości domyślnych

**Comment by PrzemyslawLukanowski** [comment]
Wartość null zwracamy wtedy, gdy użytkownik nie zmodyfikował czasu dostawy w danej metodzie i jest to zachowanie naturalne. Przy pobieraniu cennika null w polu shippingTime oznacza potrzebę użycia domyślnego czasu dostawy (ponieważ użytkownik go nie zmodyfikował), który jest zapisany w  danej metody dostawy. Domyślne czasy dostawy mogą się zmieniać, dlatego tej informacji nie chcemy zapisywać w cennikach. Domyślne czasy dostawy danej metody możesz sprawdzić za pomocą zasobu [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET).

**Comment by frankii91** [comment]
To chyba tym bardziej jest niepoprawnie, ponieważ skoro domyślne czasy dostawy mogą się zmieniać. to bez wiedzy użytkownika może się zmienić czas, a to nie powinno mieć miejsca.
Skoro tworze cennik i ustawiam dany czas to tak powinno być a nie że nagle sam może się zmienić ( bo był domyślny)

Jeśli jest coś takiego jak wartości domyślne to powinno to być osobno zaznaczana przez użytkownika=sprzedawce  ( nie tylko czas ale i cena... i wszystkie inne wartości)

Najlepszą opcją by było obok czas coś takiego jak checkbox informujący czy informacje o czasie maja być zawsze brane z domyślnych czy z użytkownika

Wartość null tym bardziej jest bez sensu ponieważ jak pobieramy informacje o danym cenniku do dostaniemy nul a nie poprawne czasy i musimy korzystać z innego zasobu aby sprawdzić czas jaki jest.
Dodatkowo nie jest to spójne np.  z ceną bo skoro koszt pierwszej sztuki niby jest domyślny to również w "waszym" przypadku powinno być zwracane null.

Ale bez opcji zaznaczania by dane wartości były brane z domyślnych od (allegro) to zawsze może wystąpić przypadek że allegro samo zmieni czas lub cenę ... bez wiedzy użytkownika ponieważ nie ma opcji  aby "nie korzystać z wartości domyślnych"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za wszystkie zgłoszone uwagi. Przekazałem je jako sugestie do zespołu odpowiedzialnego za rozwój REST API.
