### ISSUE TITLE
Can not list product in category

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#2318]
I'm facing an issue while product upload there is an issue like 
Cannot create products in category: 5553 how i can upload product in categories where most of the category has productCreationEnable is false.

**Comment by PrzemyslawLukanowski** [comment]
You can’t create product in this category. Uploading a product is for now supported only in selected categories.

**Comment by 07adityasingh** [comment]
So how we can work on it ?

**Comment by PrzemyslawLukanowski** [comment]
In this category you can list only standard offer - more information you can find in [our guide](https://developer.allegro.pl/en/sale/).

**Comment by sportmma** [comment]
Co to znaczy, że w tej kategorii można wymienić tylko ofertę standardową?

**Comment by PrzemyslawLukanowski** [comment]
Oznacza to utworzenie nowej oferty, co krok po kroku opisujemy w [naszym poradniku](https://developer.allegro.pl/sale/). Tworzenie produktu jest innym procesem - w wybranych kategoriach, na podstawie wysłanych danych, możesz utworzyć nowy produkt, a następnie powiązać z nim swoją ofertę. Szczegóły tej funjconalności znajdziesz w [naszym poradniku](https://developer.allegro.pl/productization/#add).
