### ISSUE TITLE
doGetSiteJournal - brak wpisów

### ISSUE THREAD

**Issue by Tomash667** [allegro/allegro-api#232]
Po wystawieniu dwóch aukcji na sandboxie i kupieniu ich przez kup teraz z innego konta *doGetSiteJournal* nic nie zwraca. doGetSiteJournalDeals zwraca wyniki. Konto XKomAllegroSandb 

Request:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoGetSiteJournalRequest>
         <ser:sessionHandle>...</ser:sessionHandle>
         <ser:startingPoint>0</ser:startingPoint>
         <ser:infoType>0</ser:infoType>
      </ser:DoGetSiteJournalRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

Response:
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <SOAP-ENV:Body>
      <ns1:doGetSiteJournalResponse>
         <ns1:siteJournalArray/>
      </ns1:doGetSiteJournalResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by kormichu** [comment]
@MaciejPotepa u mnie ten sam przypadek. Konto: kormichu

**Comment by MaciejPotepa** [comment]
Dzięki, dodałem do zgłoszenia.

**Comment by KarolError404** [comment]
Mam ten sam problem. Czy coś już wiadomo w tym temacie? Login na sandbox: Karol

**Comment by MaciejPotepa** [comment]
Dalej pracujemy nad rozwiązaniem tematu. Proszę o cierpliwość i przepraszam za kłopot. 

@KarolError404 Dzięki za zgłoszenie. Podasz może jeszcze numery ofert, dla których występuje problem?

**Comment by Tomash667** [comment]
@MaciejPotepa Jakieś postępy w tym temacie?

**Comment by MaciejPotepa** [comment]
@Tomash667 tak jak pisałem wyżej. 

> Dalej pracujemy nad rozwiązaniem tematu. Proszę o cierpliwość i przepraszam za kłopot.
