### ISSUE TITLE
Problem ze wznowieniem aukcji - API potwierdza, aukcji nie ma 

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#2320]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mamy problem ze wznawianiem ofert. Wysyłamy zapytanie i dostajemy odpowiedź o sukcesie, weryfikacja na "offer_publication" po chwili potwierdza wznowienie.

Jednak aukcja nie zostaje wznowiona - przechodząc do numeru oferty nadal widzimy informację "aukcja została zakończona"

Nie otrzymujemy również informacji drogą mailową o wznowieniu oferty.
Co więcej przy próbie wznowienia aukcji bezpośrednio przez Allegro informacja jest następująca:

![image](https://user-images.githubusercontent.com/10725188/66191697-337c3280-e68f-11e9-9df4-f0c5b5b27270.png)

Trace-id: 48a2c67f66e721cc

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - oferta znajduje się cały czas w statusie ACTIVATING. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by mkaluszka** [comment]
To samo mam od kilku godzin z aukcją 7496245131

**Comment by PrzemyslawLukanowski** [comment]
@mkaluszka Widzę, że oferta jest już w statusie ACTIVE. W celu analizy dodałem ją do zgłoszenia.

**Comment by radoslawkoziol** [comment]
Wydaje mi się, że jest znów to samo z kolejną ofertą 8556411871
na Allegro jest widoczna i dostępna, a w panelu w "moje oferty" ma status Szkic


![image](https://user-images.githubusercontent.com/10725188/66304995-b22ad700-e8fe-11e9-8add-0b749e2035d8.png)

![image](https://user-images.githubusercontent.com/10725188/66305015-be169900-e8fe-11e9-8a4c-e6d50baaf120.png)

**Comment by PrzemyslawLukanowski** [comment]
Oferta jest już w statusie ACTIVE i nie ma rozbieżności między frontem a GET sale/offers. Aktywacja szkicu może trwać do godziny.

**Comment by yncki** [comment]
Kolejna @PrzemyslawLukanowski , 
ACTIVATING od 14:25 , jest 17:01 
8480102423

**Comment by PrzemyslawLukanowski** [comment]
@yncki Przekazalem numer oferty do zgłoszenia.

**Comment by yncki** [comment]
@PrzemyslawLukanowski 

kolejne numery które wiszą ze statusem ACTIVATING, najstarszy wpis mamy z 09-27
7449864065
7286347140
8396868415
8557616420
8556468121
8350763968
8425057862
8556658673
8473990492
8413078609
7158577895
8270010168
7930137082
8266645485
8270178652
8270087660
8270089661
8436108973
8436108787
8435969660
8334961589
8266226852
6974967578
7918395128
7915843292
8385074195
6761001028
8479572109
7930136840
8394028566
8394026449
7159210144
8333652181
8425017885
8402753943
8517981657
8407024281
7818902560
8517121845
8495002573
8270164269
8275966529
7286346901
8254426835
8307934752
8055975334
8266178480
8328517839
8266309102
8025842070
8254428051
8371522165
8512612257
7581392013
8479571992
7876232521
8257584841
8270373108
7922942064
8078107152
8270179668
7918392646
7923171680
8055774108
8359801966
8359801124
8359979022
8359732307
8360824765
8360824269
8360823838
8360823422
8360822899
8360822554
8359798331
8359797337
8359984620
8359711539
8360822058
8360821678
8501129216
8434141426
8434137242
8501128994
8501128942
8503388824
8434143730
8434422856
8434166063
8552751290
8552750734
8552756326
8552749730
8434163088
8434165421
8434166760
8434138689
8434140793
8434143122
8434163419
8434423281
8434167251
8552746598
8552745340
8434420310
8434137610
8434139077
8501109307
8517224899
8501125566
8501125501
8434059573
8434058768
8549872856
8549708730
8549706788
8549673296
8434172368
8434172812
8434057571
8434056498
8434173368
8501107648
8434058473
8434057338
8434056157
8436362088
8434055573
8549654551
8548695583
8436363103
8434059163
8434058187
8434055939
8434393247
8434055267
8436361247
8436362687
8434057920
8434056798
8434392249
8434044779
8497941147
8493450304
8501019113
8501016160
8502043837
8491004602
8491013561
8500958292
8491004060
8498018783
8498030747
8498019979
8434168707
8434424112
8434169032
8497923162
8497923219
8497941573
8500917454
7736153997
7736153953
8501175760
8555677970
8360821141
8360820587
8360820140
8360819787
8359788818
8359787604
8360819113
8358785138
8358782048
8358781874
8358781563
8358781328
8282820856
8282820922
8282821060
8506718302
8506713689
8506718445
8524459894
8524453292
8524453223
8359746534
8359745449
8358781120
8358780846
8360003306
8313347519
8290617631
8547939403
8353053871
8353081198
8414879991
8414870716
8414870361
8414869013
8414868767
8414868518
8414868253
8433885893
8498196665
8498182938
8499683359
8498184769
8499634534
8499632827
8499630204
8499629846
8506261373
8506268126
8506261501
8282854059
8282848131
8282848075
8360818721
7573805953
8414870908
8414871003
8414871099
8414887057

mamy tego więcej.

**Comment by PrzemyslawLukanowski** [comment]
@yrcki Dziękuję za przesłane numery, przekazałem je do zgłoszenia. Pracujemy nad rozwiązaniem problemu.

**Comment by yncki** [comment]
@PrzemyslawLukanowski mija tydzień i nadal 4000 tysiące ofert różnych klientów w statusie ACTIVATING

kiedy to będzie poprawione ? Przypominam że przez allegro.pl i interfejs graficzny nie idzie ich także wznowić. Straty rosną.

**Comment by PrzemyslawLukanowski** [comment]
Wszystkie oferty z wątku trafiły do odpowiedniego zgłoszenia w celu analizy problemu. Na tę chwilę nie mogę wskazać konkretnej daty usunięcia błędu. Pracujemy nad tym.

**Comment by yncki** [comment]
up.

**Comment by PrzemyslawLukanowski** [comment]
Wszystkie dotychczasowe oferty, które wiszą w statusie “ACTIVATING” w najbliższym czasie zostaną zakończone, ponieważ nie przeszły prawidłowo walidacji. W polu endedBy będzie widnieć wartość ERROR. Konieczna będzie edycja oferty w celu zlokalizowania błędu (komunikat w walidacji) oraz ponowne wystawienie.
