### ISSUE TITLE
Zasób do pobierania rodzajów przesyłki

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2322]
Dzień dobry,

ja z małym pytaniem. Otóż jak pobrać id rodzajów przesyłki np. id dla Allegro Paczkomaty 24/7 InPost (delivery_method_id)? Bardzo by mi się przydałby taki zasób. Jeżeli takowego nie ma, potraktujcie to jako sugestię. 

Pozdrawiam.

**Comment by PawelTaberski** [comment]
Takie informacje pobierzesz przy pomocy zasobu /sale/delivery-methods, więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#shipping-rates).

**Comment by hahyes** [comment]
Dziękuję za odpowiedź.
