### ISSUE TITLE
przypisanie cennika do oferty

### ISSUE THREAD

**Issue by APICoderPL** [allegro/allegro-api#2323]
czy jest jakaś możliwość przypisania cennika dostawy do obecnie wystawionej oferty.
znalazłem opcję masowej zmiany cen, ilości sztuk, ale do cennika jakoś nie.

**Comment by PawelTaberski** [comment]
Tak, przy pomocy zasobu /sale/offer-modification-commands/{commandId} przypiszesz również masowo cennik do wielu ofert, więcej informacji wraz z przykładem znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#3a).
