### ISSUE TITLE
Od tygodnia sie z tym męcze , POMOCY !!!!

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2325]
'curl -X POST \ 'https://allegro.pl/auth/oauth/device' \ -H 'Authorization: Basic base64(client_id:client_secret)' \ -H 'Content-Type: application/x-www-form-urlencoded' \ -d 'client_id={client_id}''

znam client_id , znam client_secret , dlaczego nie uzyskuję device_code

czy ktoś ma prosty skrypt PHP , do powyższego curla , jak ten powyższy ciąg zamienić pod Curl Php ?

**Comment by anaxagore78** [comment]
3 sekund w Google - https://incarnate.github.io/curl-to-php/

**Comment by anaxagore78** [comment]
<?
$ch = curl_init();

$clientid="tuWpiszClientId";
$clientSecret="tuWpiszClientSecret";

curl_setopt($ch, CURLOPT_URL, 'https://allegro.pl/auth/oauth/device');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "client_id=".$clientid);
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Authorization: Basic '. base64_encode($clientid.':'.$clientSecret);
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
?>


sprawdzone i działa



?>

**Comment by jasiek07** [comment]
Dzięki wielkie , ale teraz mam problem z tym : 
"{"error":"unauthorized_client","error_description":"Client does not have the device_code grant."}"
zapewne trzeba coś jeszcze zrobić by uzyskać prawo dostępu z przesłanego przez Ciebie skryptu

**Comment by jasiek07** [comment]
Ok udało się , podstawiałem nie to clientId i clientSecret , dzięki serdeczne za pomoc

**Comment by jasiek07** [comment]
No dobra kolejne schody :(.
W powyżej opisany przez Ciebie sposób uzyskaliśmy "device_code" . Zatem poniższym skryptem chcę teraz pozyskać tokken , ale niestety wyskakuje error : {"error":"invalid_request","error_description":"Invalid device code"}
gdzie leży problem ?
`$authUrl='https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=XXXXX';
	$clientId = "XXXXX";  
	$clientSecret = "XXXXX";   
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $authUrl);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	$headers = array();
	$headers[] = 'Authorization: Basic '. base64_encode($clientId.':'.$clientSecret);
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$tokenResult = curl_exec($ch);
	if (curl_errno($ch)) {echo 'Error:' . curl_error($ch);}
	curl_close($ch);
	print_r($tokenResult);

**Comment by anaxagore78** [comment]
https://developer.allegro.pl/auth/ 

> 3, 4a, 5/ Poproś użytkownika, aby przeszedł z poziomu dowolnego urządzenia na podany przez ciebie adres (verification_uri) i podał tam kod użytkownika (user_code).

Otworzyles w przegladarce adres zwrocony przez 'oauth/device'    -  'verification_uri_complete' ?

**Comment by anaxagore78** [comment]
sprawdzony kod:
`<?php

$clientid="tuWpiszClientId";
$clientSecret="tuWpiszClientSecret";
$deviceCode = 'tuWpiszDeviceCode';

$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://allegro.pl/auth/oauth/token?device_code=".$deviceCode."&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "",
  CURLOPT_HTTPHEADER => array(
    'Authorization: Basic '. base64_encode($clientid.':'.$clientSecret)
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

var_dump($result);`
