### ISSUE TITLE
 get /sale/offers awaria?

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2327]
Wiem, że pytanie lekko nieświeże, ale czy ktoś z forumowiczów zauważył może błędne działanie get/sale/offers wieczorem w czwartek 3.10 i piątek 4.10?
Normalnie zaciągam niesprzedane aukcje i wystawiam je ponownie jako kup teraz. Automat od zawsze działał poprawnie, a  wygląda na to że w te dwa konkretne dni zwrócone tę metodą oferty musiały mieć błędne parametry (po swojej stronie sortuje je jeszcze m.in po stock.available).
Zaciągam oferty zakończone co najmniej 15 minut wcześniej bo wiem, że jest opóźnienie w odświeżaniu danych (zgłoszenie #1210).
Czy możliwe jest, żeby w wyniku awarii(?) przez jakiś czas po zamknięciu licytacji get /sale/offers zwracało sprzedane licytacje z parametrem stock.available>0?
Pytam bo narobiło to u klienta sporego bigosu i chciałbym się zabezpieczyć przed czymś takim w przyszłości, a na razie szukam po omacku - w tym tygodniu tego typu zachowań nie udało mi się już zaobserować. Wiem jednak, że w piątek 04.10 przez cały dzień Allegro działało spowolnione i nawet wystawiane na frontendzie oferty pojawiały się z bardzo dużym opóźnieniem.
Byłbym wdzięczny za jakiekolwiek wskazówki.

**Comment by lukada4100** [comment]
@PrzemyslawLukanowski Hop hop. Wydaje mi się, że złapałem przypadek o którym pisałem wcześniej. W formularzu wysłałem printscreen z frontendu oraz request/response dla  get /sale/offers/{offerId} i  get /sale/offers. Zwróć uwagę na wartości stock.available.

**Comment by MaciejFrackowiak** [comment]
@lukada4100 Zweryfikowaliśmy wspomnianą ofertę - rzeczywiście wystąpiła tu niezgodność ilości dostępnych sztuk. Przepraszamy za niedogodności.

**Comment by lukada4100** [comment]
Dzięki. Czy jest możliwe by podobna sytuacja miała miejsce jakiś czas temu dla kilkuset ofert, które kończyły się o określonej godzinie? Mógłbyś odnieść się do mojego podstawowego zgłoszenia? Nikt mi właściwie do tej pory na nie nie odpowiedział.

**Comment by MaciejFrackowiak** [comment]
Nie odpowiadaliśmy, ponieważ założony wątek sam zamknąłeś, a później otworzyłeś go ponownie - musiał umknąć nam po takiej operacji :) 
Wyjaśniając - trudno odnieść się tak ogólnie do ofert, jednak jak widzę w dniach 3-4.10.2019 mieliśmy opóźnienia w odświeżaniu statusów ofert, jednak z samym stockiem problemu nie było.

**Comment by lukada4100** [comment]
czy podanie konkretnych numerów aukcji pozwoliłoby Wam zweryfikować czy działo się z nimi coś złego w tym okresie?

**Comment by MaciejFrackowiak** [comment]
Możemy podjąć próbę spojrzenia w logi, choć po tylu dniach może być to znacznie utrudnione. Proszę podaj kilka przykładowych numerów ofert.

**Comment by lukada4100** [comment]
8527281335
8526301381
8526110158
8525592438
8525088308
Zaciągane 04.10.2019  między 20:00 a 21:00

8522921267
8522926875
8522920777
8528255701
8528133168
Zaciągane 03.10.2019 między 19:00 a 20:00

**Comment by MaciejFrackowiak** [comment]
Niestety, nie udało nam się cofnąć do stanu ofert z dnia 3-4.10.2019 by odtworzyć Twoje wywołania z tego okresu. Jak wspomniałem w tych dniach mieliśmy pewne problemy z aktualizacją statusów ofert. Jeżeli podobny problem zauważysz w przyszłości, proszę daj nam znać od razu, co pozwoli na przeprowadzenie weryfikacji.

**Comment by lukada4100** [comment]
Niestety z doświadczenia wiem, że o ile się nie złapie nikogo za rękę, jak ja wczoraj, raczej nie jest się traktowanym poważnie :(
Tym nie mniej będę próbował...

**Comment by MaciejFrackowiak** [comment]
Zapewniam Cię, że każde zgłoszenie na GitHub nie pozostaje bez odpowiedzi i w miarę możliwości staramy się możliwie szybko reagować,

**Comment by neldh** [comment]
400 dzis rzucało na tym zasobie:

Oct 22nd, 10:14:18 UTC
do
Oct 22nd, 10:40:13 UTC
GET https://api.allegro.pl/sale/offers?seller.id=XXXXXXX&offset=0&limit=1000 resulted in a 400 Bad Request response: {"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"","details":"","path":""}]}

**Comment by PrzemyslawLukanowski** [comment]
Nie odnotowaliśmy większej liczby błędów tego typu. Czy możesz przesłać nam przykładowe trace-id? Widzę, że w parametrach przekazujesz seller.id, zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) nie wspieramy tego parametru.

**Comment by neldh** [comment]
Biblioteka, której używam dodaje parametr seller.id. Wydaje mi się, że wcześniej był wymagany. Czy jego pominięcie pobierze wszystkie oferty zalogowanego sprzedawcy? Jak nie to jak pobrać wszystkie oferty zalogowanego sprzedawcy teraz? Czy jego podanie spowoduje błąd w tej chwili?

Proszę o szybką odpowiedź. Jeśli chodzi o trace-id to niestety ich nie logujemy, dlatego podałem czas występowania.

**Comment by PrzemyslawLukanowski** [comment]
Pominięcie tego parametru pobierze wszystkie oferty zalogowanego sprzedawcy. Podanie spowoduje błąd tylko wtedy, kiedy jako seller.id przekażemy id niezautoryowanego użytkownika.
