### ISSUE TITLE
/sale/offer-variants - automatyczne zestawy

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#2328]
:bulb: **Sugestia**

Od jakiegoś czasu allegro męczy nową funkcjonalnością - automatycznymi zestawami wielowariantowości.

Sugeruję aby informację o tym, czy dany zestaw został automatycznie utworzony dodać do zasobów:
GET /sale/offer-variants
GET /sale/offer-variants/{setId}

Sugeruję również żeby do ```GET /sale/offer-variants``` dodać filtr umożliwiający wyszukiwanie zestawów, które zostały, bądź nie zostały utworzone automatycznie.

Motywuję swoje sugestie tym, że aktualnie takie ficzery są na froncie dostępne 😎

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię. Przekazuję ją do działu odpowiedzialnego za rozwój Allegro REST API.
