### ISSUE TITLE
Rozliczenie z Allegro

### ISSUE THREAD

**Issue by browin-pziemba** [allegro/allegro-api#2329]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Brak możliwości potwierdzenia płatności w dziale **Rozliczenie z Allegro**.
Wybierając zapłać i wybierając bank raz przenosi mnie do strony głównej, drugi raz do symulatora płatności. Jeżeli wylosuje mi drugi scenariusz to mimo wszystko przy wyborze pozytywnej płatności nadal mam saldo ujemne.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie. Problem przekazałem do weryfikacji.

**Comment by browin-pziemba** [comment]
Chciałem się dowiedzieć czy coś się ruszyło w sprawię czy nadal nie możecie zlokalizować błędu?
Dziś dostałem maila, że zablokowane zostało konto, sprawdziłem płatność (zmieniłem operatora) i na symulatorze nadal nie działa.
Przechodzi do strony głównej bez żadnego komunikatu.

**Comment by MaciejFrackowiak** [comment]
@browin-pziemba Tak, weryfikowaliśmy działanie symulatora i ostatni test przeszedł prawidłowo - wpłata została rozliczona, saldo zmienione.
Niestety, widzę, że ponownie coś “nie gra” - zgłaszam raz jeszcze.

**Comment by Sharhin** [comment]
Poproszę o rozliczenie płatności dla użytkownika:
login G5rsI1IZ
id: 44207401

**Comment by MaciejFrackowiak** [comment]
@Sharhin Niestety, mamy problem z działaniem symulatora płatności za rachunki w Sandbox. Sprawa jest już weryfikowana.
