### ISSUE TITLE
Autoryzacja client_credential_flow w pythonie

### ISSUE THREAD

**Issue by bstrzyga** [allegro/allegro-api#2330]
Poslugując się poniższym codem pobieram device i user_code. Które pozwalają prawidłowo zarejestrować aplikację po stronie użytkownika, jednak nie mogę autoryzować device code po stronie aplikacji (korzystając z url_b i takich samych headerów jak w przypadku requesta mającego na celu pozyskanie device i user code) - krok 4b w dokumentacji. Co więcej po ręcznym włączeniu url_b przez przeglądarke i podaniu w formularzu client_id i client secret udaje się dokonać autoryzacji i otrzymać token.

coded_data = base64.b64encode(data_to_code)  # zawiera 'client_id:client_secret'.encode('utf-8')
form_data = coded_data.decode('utf-8')
url = 'https://allegro.pl/auth/oauth/device'
headers = {
    "Authorization": "Basic {}".format(form_data),
    "Content-Type": "application/x-www-form-urlencoded"
}
data = {
        "client_id": client_id
        }
a = requests.post(url, data=data, headers=headers)
content = a.json()
device_code = content['device_code']
user_code = content['user_code']

url_b = 'https://allegro.pl/auth/oauth/token?' \
        'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={}'.format(device_code)
b = requests.post(url_b, data=data, headers=headers)

**Comment by anaxagore78** [comment]
Sprobuj przy wywolaniu url_b wysłac nagłowek wyłacznie z polem "Authorization": "Basic {}".format(form_data),
pomiń "Content-Type": "application/x-www-form-urlencoded",

**Comment by bstrzyga** [comment]
> Sprobuj przy wywolaniu url_b wysłac nagłowek wyłacznie z polem "Authorization": "Basic {}".format(form_data),
> pomiń "Content-Type": "application/x-www-form-urlencoded",

Próbowałem, dodanie Content-Type było już próbą poradzenia sobie z problemem.

**Comment by anaxagore78** [comment]
`url = "https://allegro.pl/auth/oauth/token"

querystring = {"device_code":"xxxxxxxx","grant_type":"urn:ietf:params:oauth:grant-type:device_code"}

payload = ""
headers = {
    'authorization': "Basic xxxxxx"
    }

response = requests.request("POST", url, data=payload, headers=headers, params=querystring)

print(response.text)`

**Comment by anaxagore78** [comment]
@bstrzyga i co pomogło?

**Comment by bstrzyga** [comment]
@anaxagore78 Niestety nie. Link wygenerowany Twoim sposobem jest taki sam jak mój zhardkodowany. Nadal nie otrzymuję aktualizacji odnośnie tego, że użytkownik autoryzował urządzenie.
