### ISSUE TITLE
powiazanie aplikacji

### ISSUE THREAD

**Issue by prycekk** [allegro/allegro-api#2332]
Witam
zarejestrowalem aplikacje i na allegro develop ... i co powinienem zrobic dalej aby otrzymac token

**Comment by MaciejFrackowiak** [comment]
Do otrzymania tokena niezbędne będzie Client ID i Client secret, które otrzymałeś po zarejestrowaniu aplikacji na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Następnie przy pomocy prostego wywołania otrzymasz token - zajrzyj do [naszego poradnika](https://developer.allegro.pl/getting_started/#jak-uzyska%c4%87-token-dost%c4%99powy-do-api). Warto także spojrzeć do [poradnika o uwierzytelnianiu i autoryzacji](https://developer.allegro.pl/auth/).

**Comment by prycekk** [comment]
próbowalem i mam blad

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam pełen request i response poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) podając w jego treści numer zgłoszenia z GitHub - 2332.

**Comment by prycekk** [comment]
przeslalem

**Comment by MaciejFrackowiak** [comment]
Tak, otrzymaliśmy Twoją wiadomość. Niestety, ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich, w tym dla php, który podesłałeś. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie pomóc.

**Comment by prycekk** [comment]
ok ale czy przeslany kod do pobrania tokena jest poprawny?

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem nie mamy możliwości udzielenia Tobie jednoznacznej odpowiedzi z uwagi na mnogość języków programowania - w Twoim wypadku użyty został php.

**Comment by prycekk** [comment]
rozumiem a mozecie sprawdzic czy moje konto jest aktywowane?
