### ISSUE TITLE
Brak X-press couriers w sandboxie

### ISSUE THREAD

**Issue by meron1122** [allegro/allegro-api#2333]
W sandboxie allegro nie ma możliwości wystawienia aukcji z kurierem "X-press couriers", kiedy to zostanie wprowadzone?

**Comment by MaciejFrackowiak** [comment]
Kurier X-press Couriers dostępny jest na Allegro obecnie tylko dla wybranych sprzedawców. W momencie kiedy stanie się dostępny dla każdego sprzedającego zostanie również dodany jako metoda dostawy na Sandbox.
