### ISSUE TITLE
Wznawianie aukcji, dziwny problem

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2334]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

Potrzebuję wiedzy co się stało w API Allegro
Aukcja: 7497774237, zamknięta do 2019-10-07 16:18:50

Wysyłamy request:
- zwiększamy stan magazynu - do 11 sztuk, godz 2019-10-07 godz 16:06, 
trace-id: ad5120580d75550a
- następnie w dziennik restAPI mam informację

 "Type": "OFFER_CHANGED",
        "Offer": {
          "Id": "7497774237"
        },
        "Id": "MTU3MDQ1NzkxNzM2NzU1Ng",
        "OccurredAt": "2019-10-07T14:18:26.918Z"

        "Type": "OFFER_ACTIVATED",
        "Offer": {
          "Id": "7497774237"
        },
        "Id": "MTU3MDQ1Nzk0MjYzNTEzNQ",
        "OccurredAt": "2019-10-07T14:18:50.846Z"
      },
trace-id dziennika: 9ba661b928f7b73d

- kto aktywował tą aukcję jeśli nie został wysłany request z publikacją?
Prośba o sprawdzenie

**Comment by MaciejFrackowiak** [comment]
Widzę, że przy pomocy [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT) doszło do aktywacji całej grupy ofert - UUID dla operacji to e8e25f2f-b444-4d7e-b513-ed9ccf65444b.
