### ISSUE TITLE
Status Code 400 po próbie utworzenia draft'u oferty

### ISSUE THREAD

**Issue by thisi5patrick** [allegro/allegro-api#2336]
Zgodnie z tutorialem [https://developer.allegro.pl/sale/#step-6-draft](https://developer.allegro.pl/sale/#step-6-draft) próbuję utworzyć draft oferty. Po puszczeniu go przez POST wyskakuje następujący błąd

    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]

Tak wygląda mój kod z headerami oraz data

    url = DEFAULT_ALLEGRO_URL + '/sale/offers'

    headers = {
        'Authorization': 'Bearer ' + token,
        'Accept': 'application/vnd.allegro.public.v1+json',
        'Content-Type': 'application/vnd.allegro.public.v1+json',
    }
    data = {
        "name": "Oferta 1234"
    }
    response = rqst.post(url, headers=headers, data=data)

Zaznaczam że jest to pisane w Pythonie 3.7

**Comment by MaciejFrackowiak** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Czy podałeś właściwy adres URL do wywołania request? Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie pomóc.

**Comment by qshop123** [comment]
Pokaż co masz pod DEFAULT_ALLEGRO_URL ale zrób dumpa tego co wysyłasz curlem

**Comment by thisi5patrick** [comment]
Pod DEFAULT_ALLEGRO_URL znajduje się [https://api.allegro.pl.allegrosandbox.pl](https://api.allegro.pl.allegrosandbox.pl), przez co moje `url` ma postać `https://api.allegro.pl.allegrosandbox.pl/sale/offers`

**Comment by thisi5patrick** [comment]
Znalazłem problem. Aby zadziałało POST'a trzeba wywołać w taki sposób

`rqst.post(url, headers=headers, json={"name": "Oferta 123"} `

Zamykam
