### ISSUE TITLE
Wznawianie ofert - błąd

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2337]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

1. Mam aukcję zakończoną
2. Na poziomie GUI Allegro (moje oferty widzę ją jako zakończona)
3. W tym miejscu mam funkcję: ukryj
4. Wykonuję taką funkcję ukryj, operacja powoduje że ukryta oferta nie jest widoczna na liście
5. W restAPI jednak można ją pobrać i wznawiać, przez co jest niezgodność z tym co widać na GUI Allegro a tym co jest w restAPI
Reasumując - pilnie trzeba poprawić by:
- dało się przefiltrować API po ofertach ukrytych 
- taka informacja była zwracana w restAPI
- nie dało się ich wznowić
Intencją usera jest ukrycie tej oferty całkowicie, nie chce jej wznawiać, jeśli teraz ma zapięte automaty które wykrywają ruch magazynowy to one nie wiedzą że aukcja jest ukryta, restAPI tego nie zwraca

**Comment by MaciejFrackowiak** [comment]
Opcja “ukryj” na froncie ma wyłącznie porządkowy charakter (przejrzystość Moje oferty) - ona nie wpływa na dostępność oferty w API. Ta funkcjonalność działa w ten sposób od samego początku jej wprowadzenia. Jednocześnie Twoją sugestię przekażę do działu odpowiedzialnego za rozwój REST API.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak to Klienci mają zdecydowanie inne odczucie. Jeśli ukryją aukcję to z poziomu MS Allegro nie wznowią jej, bo jej na liście nie bedzie. 
Zatem powinna być też "wiedza" restAPI że taka operacja się wykonała na aukcji i wtedy my jako integratorzy zdecydujemy czy wznawiać czy nie, teraz tego nie ma i autowznowienia idą, a iść nie powinny, bo po to Klienci ukryli by nie wznawiać :)

**Comment by MaciejFrackowiak** [comment]
Rozumiem Twoje podejście, jednak takie zachowanie względem zakładek Moje Allegro mamy od zawsze - również starsza wersja Moja sprzedaż tak samo zachowywała się - usunięte oferty były widoczne w API.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak twierdzenie że "mamy coś od zawsze" jest nie na miejscu. 
Jest to błąd, jak zatem rozwiązać to by dowiedzieć się w API że aukcja jest "ukryta". Brak jest spójności i jest to błąd do poprawy.

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Nie jest to błąd funkcjonalności, tylko prawidłowe działanie mechanizmu. Jak wspomniałem wcześniej Twoją opinię przekazałem jako sugestię dot. zmian w REST API.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak gdzie w restAPI jest informacja przy pobieraniu oferty że jest ona ukryta?

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej informacji. Ukrycie oferty jest tylko “tworem” porządkowym w serwisie WWW - chowamy ją z listy Moje oferty (o czym informujemy w komunikacie), jednak jest dostępna w zasobach - zarówno w API, jak i WWW.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak nie jest "tworem" porządkowym, jeśli ukrywam ją w serwisie to robię to w jakimś celu np. zamykam i nie chcę jej wystawiać lub wznawiać. Należy tą informację zwracać w API, inaczej jest rozbieżność między tym co widać w Moje oferty a tym co zwraca API i uważam to za błąd :)

**Comment by MaciejFrackowiak** [comment]
Pozwolę sobie odpowiedzieć raz jeszcze - Twoje zdanie przekazałem jako sugestię do działu odpowiedzialnego za rozwój REST API i obecnie pozostaje nam czekać.
