### ISSUE TITLE
Próba wystawienia drafta - błąd wartości null

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#2338]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie wystawienia drafta na koncie naszego klienta przy wybraniu "duration" jako "null" API zwraca 
"null" is not valid value for publication.duration, allowed values: ISO 8601 durations.

Proszę o pomoc. 
Dziękuję.

**Comment by hahyes** [comment]
Odpowiedź jest prosta, nie możesz wystawić aukcji z duration jako null. Ten parametr odpowiada za to, jak długo aukcja jest aktywna. Musisz zapisać, jak długo ma być aktywna w formacie ISO 8601.

**Comment by MaciejFrackowiak** [comment]
@qshop123 Proszę przedstaw nam wysyłany request oraz response (oczywiście usuń z niego dane wrażliwe - m.in. token).

**Comment by qshop123** [comment]
Temat wyjaśniony, dziękujemy.
