### ISSUE TITLE
Allero smart + inpost po nowemu

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2339]
Z tego co rozumiem, po wprowadzeniu zmian 1 listopada inpost będzie wysyłał kod do paczkomatu na email klienta powiązany z transakcją, w domenie allegromail (po tym jak sprzedawca przekaże ten mail inpostowi). W takim razie jeśli klient zamówi coś nie dla siebie, tylko dla znajomego, to będzie musiał ten kod mu samodzielnie wysłać, gdyż to jemu przyjdzie na email, a nie do znajomego? Czy zamierzacie wobec tego wprowadzić w integracji z inpostem jakiś dodatkowy mechanizm informacyjny? (żeby sprzedawca mógł poinformować inpost o tym, że klient życzy sobie dostać kod do paczkomatu na inny adres email/telefon)?

**Comment by MaciejFrackowiak** [comment]
Nie, nie przewidujemy tu żadnych zmian. Mechanizm ten działa identycznie obecnie - zamawiając przedmiot formularz pozakupowy wysyłany jest na adres email, z którego dokonano zakupu i taki adres jest przekazywany do InPost. W formularzu kupujący może natomiast podać dowolny numer telefonu, na który również wysyłany jest kod do odbioru przesyłki.
