### ISSUE TITLE
DoNewAuctionExtRequest na Sandboxie zwraca OFFER_DEFAULT_ERROR_MESSAGE

### ISSUE THREAD

**Issue by KrzysztofStachyra** [allegro/allegro-api#234]
Wewnętrzny bład systemu. OFFER_DEFAULT_ERROR_MESSAGE
Jakiś powód/potwierdzenie czy to u Wszystkich?
Sandbox nowy - zapomniałem dodać.

**Comment by MaciejPotepa** [comment]
Dzięki za zgłoszenie. Na ten moment to jedyne takie zgłoszenie. 

Żebym mógł pomóc musisz podać treść request i response w zapisane w XML. Bez tego nie jestem w stanie sprawdzić co jest dokładnie nie tak.

**Comment by KrzysztofStachyra** [comment]
Dziwne bo dzisiaj ta sama aukcja się wystawiła poprawnie, jak w najbliższym czasie pojawi się podobny temat to wrzucę do tematu.

Swoją drogą żeby nie było tak, że ciągle narzekam (pewnie ja i inni) miłe jest to, że ktoś u Was w końcu poszedł po rozum do głowy i wybrał normalne środowisko do poruszania tematów typowo integracyjnych i co najważniejsze panuje tu jako taki porządek i czas odpowiedzi z Waszej strony jest w miarę na bieżąco. **Dzięki**.

**Comment by MaciejPotepa** [comment]
Sam błąd mógł być efektem chwilowej 'czkawki', którą mieliśmy na środowisku testowym po włączeniu wymagania nowego opisu w ofertach. Prawdopodobnie trafiłeś w ten moment. 

Taki mieliśmy zamysł wybierając GitHuba na miejsce wsparcia API. Dzięki za miłe słowa, doceniamy to.
