### ISSUE TITLE
czas trwania

### ISSUE THREAD

**Issue by APICoderPL** [allegro/allegro-api#2340]
czy planujecie możliwość wystawienia oferty np.: na 60 lub 90 dni

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy takich planów. Dla dłuższych czasów trwania ofert proponujemy oferty do wyczerpania przedmiotów.

**Comment by APICoderPL** [comment]
to jest zdecydowanie za długo. Wygodniejszym rozwiązaniem byłoby możliwość wystawienia oferty na 60 i 90 dni,

**Comment by PrzemyslawLukanowski** [comment]
Możesz także wznowić ofertę przez ustawienie wartości true dla pola republish, o czym przeczytasz w [naszym poradniku](https://developer.allegro.pl/sale/#new-offer).

**Comment by APICoderPL** [comment]
to też wiem:)
ale nie da się tam ustawić na jak długo, mam duration, ale daje takie same możliwości jak podczas wystawiania oferty.

Mamy już swoje rozwiązanie na to, ale dodanie możliwości podania czasu jako wielokrotności waszego okresu rozliczeniowego byłoby super rozwiązaniem.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy takich planów, przekazuję jednak Twoje zgłoszenie jako sugestię do odpowiedniego zespołu.
