### ISSUE TITLE
Pola dodatkowe inaczej parametry.

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#2341]
:bulb: **Sugestia**

W tej chwili jest tak:

"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},
{"id":"127511","valuesIds":["127516_13"],"values":[],"rangeValue":null}]

Problem w tym, że wy producentów od dawien dawna zminiacie kilkanaście razy w roku, ostatnio już doszło do takiej paranoi że nie dość że zmieniacie identyfikator samego producenta to jeszcze zmieniacie samo ID wartości tego producenta, srawdziłem w logach dla jednej kategorii zmieniliście 3 razy id pproducenta od marca, wiec mam sugestię jak powinno to wyglądać.

"parameters":[{"id":"Stan","valuesIds":["Nowy"],"values":[],"rangeValue":null},
{"id":"Producent","valuesIds":["Inny"],"values":[],"rangeValue":null}]

Zapisa dla nas programistów jest wg mnie wygodniejszy a wy i tak to sprawdzacie, a mimo wszystko użytkownikowi lepiej jest napisać że producent INNy nie znajduje sie na "liście kompatybilności" niż wartość klucza 127516_13 nie jest prawidłowa.

Szczerze mówiąc mnie nie powinny interesować Wasze idiki, przekazuje wartości i mam to z głowy a wy sobie w środku możecie już to zmieniać nawet 3 razy dziennie.

Abstrachując już od sytuacji dlaczego dla wszystkiech kategorii nie może być jeden producent tylko musi być ich duuuużo za dużo. Dodatkowo wg mnie macie też spory kłopot z rozróżniem Producenta od Marki i może to jest też dla Was kłopotliwe ? Tylko jak już w końcu wprowadzicie Markę proszę wprowadzić jeden ID dla wszystkich kategorii.

**Comment by MaciejFrackowiak** [comment]
Allegro to żywy organizm, dlatego trudno przyjąć by raz przekazane dane były “pewne” na wieki - tak nie da się efektywnie dopasować do zmieniającego się otoczenia. Rozróżnianie przytoczonego parametru Producent ma na celu prezentowanie wybranych wartości tylko per dana kategoria - producenci dla kategorii X są jedni, a dla kategorii Y drudzy - połączenie tego w całość stworzyłoby ogromne zbiory wartości. Niemniej Twoje podejście do obsługi parametrów przekazuję do działu odpowiedzialnego za rozwój REST API.

**Comment by keczerad** [comment]
wg mnie żywy organizm polega na tym, że dodajemy nową wartośc pola producent a nie zmieniamy non-stop jego identyfikator ! Wielko zbiory danych pewnie są, ale wg mnie teraz są jeszcze większe bo muliplikujecie wartości producentów które są powtarzalne,  rozumiem że to stanowi problem przy filtrach, ale na to są inne sposoby których my programiści z innych firm nie musimy znać ani o nich wiedzieć, my natomiast  powinniśmy dostać dobrze opakowany produkt a niestety teraz dostajem co chwilę zmany od Was co gorsza różniące się tylko idikami a wartości są takie same ! API w dzisisjszych czasach powinno być inteligetniejsze od nas programistów obcych firm i zdecydowanie powinno naprawiać nasze błedy, wtedy wątków na tym forum było by mniej a wy moglibyście się skupić na programowania a nie na odpowiadniu na pytania. Wg mnie do takiej sytucaji w dużej mierze przyczyniła by się Wasza praca na API, tak żeby iterfejs allegro korzystał z API , bo wydaje mi się że strona robi swoje a API swoje. Przy takim działaniu pewnie zrozumielibyście nas i nasze problemy :).

**Comment by MaciejFrackowiak** [comment]
Naszym celem jest zapewnienie spójności pomiędzy API a stroną WWW w możliwie jak największym wymiarze. Niekiedy nie jest to proste, ani też szybkie. Niemniej podejmowane działania dążą do realizacji tego nadrzędnego celu. Jako serwis w ujęciu globalnym musieliśmy przyjąć pewną koncepcję zarządzania parametrami, kategoriami, etc., co sprawia, że każdy może mieć swój własny idealny obraz ich funkcjonowania.

**Comment by crazyhtm** [comment]
Pytanie co rozumiemy pod pojęciem spójności, bo chyba strona WWW i API spełniają zupełnie inne zadania. Strona ma zapewnić użytkownikom łatwy sposób dokonywania zakupów, API ma między innymi dostarczać programistom potrzebne dane w przejrzysty i stabilny sposób. Wydaje się że odzwierciedlenie w API funkcjonnalności strony może je ograniczać lub komplikować.

Np. trudność w pobieraniu i parsowaniu opisu aukcji.
Myślę że dobrze by było, aby zrobić odzielny zasób lub filtr. Tak żeby po podaniu ID aukcji można było otrzymać czysty tekst opisu bez znaczników HTML i innych utrudnień.

Przyczyna jest prosta, tytuł aukcji to tylko 50 znaków i wiele informacji wystawiający wpisują w opisie. Który na dzień dziesiejszy jest dość trudno dostępny przez API.

**Comment by keczerad** [comment]
Panie Macieju nie chodzi o idealizowanie a o upraszczanie co w konsekwencji prowadzi do zmiejszania ilości requestów do Was, a jak coś jest proste to zwyczajnie mniej kosztuje.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za wszystkie uwagi. Każdą sugestię odpowiednio analizujemy. Jeśli idzie za tym konkretna potrzeba większej liczby użytkowników, decydujemy się na wdrożenie danej funkcjonalności.
@crazyhtm - sugestię odnośnie pobierania i parsowania opisu oferty również przekazuję do odpowiedniego zespołu.
