### ISSUE TITLE
Błąd 422 przy wystawianiu aktywnej oferty.

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2342]
Jako INACTIVE się dodaje i można ręcznie (na stronie allegro) aktywować, ale bezpośrednio jako ACTIVE wyrzuca błąd 422. Gdyby ktoś mógł mi wskazać czego tu brakuje? Czy datę muszę sam uzupełniać, bo przy drafcie uzupełnia się sama w ofercie?

{
	"name": "nazwa",
	"category": {
		"id": "252234"
	},
	"parameters": [{
		"id": "11323",
		"rangeValue": null,
		"values": [],
		"valuesIds": ["11323_2"]
	}, {
		"id": "128491",
		"rangeValue": null,
		"values": [],
		"valuesIds": ["128491_1"]
	}, {
		"id": "128590",
		"rangeValue": null,
		"values": [],
		"valuesIds": ["128590_1"]
	}, {
		"id": "17448",
		"rangeValue": null,
		"values": ["77"],
		"valuesIds": []
	}],
	"ean": null,
	"description": {
		"sections": [{
			"items": [{
				"type": "TEXT",
				"content": "<p>hfghfghfghfghfgh</p>"
			}]
		}]
	},
	"images": [{
		"url": "https://a.allegroimg.allegrosandbox.pl/original/112802/f4a20b614a7c95c0963271e6b3ff.png"
	}],
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "50",
			"currency": "PLN"
		},
		"minimalPrice": null,
		"startingPrice": null
	},
	"stock": {
		"available": 50,
		"unit": "UNIT"
	},
	"publication": {
		"duration": null,
		"status": "ACTIVE",
		"republish": false
	},
	"delivery": {
		"additionalInfo": null,
		"handlingTime": "PT0S",
		"shippingRates": {
			"id": "d9557132-4f8d-4c8d-bef0-82827aef96bd"
		}
	},
	"payments": {
		"invoice": "VAT"
	},
	"location": {
		"city": "Częstochowa",
		"countryCode": "PL",
		"postCode": "42-200",
		"province": "SLASKIE"
	}
}

**Comment by MaciejFrackowiak** [comment]
Do aktywacji oferty z draftu służy zasób [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT). Proszę zajrzyj także do [naszego poradnika](https://developer.allegro.pl/sale/#step-9-offer-publication-commands).

**Comment by SaintRaphaelBass** [comment]
A czy nie można aktywować od razu linią "status": "ACTIVE"?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości.
