### ISSUE TITLE
Problem z pobieraniem zamówień

### ISSUE THREAD

**Issue by szokart** [allegro/allegro-api#2344]
Wcześnie działało prawidłowo a teraz przy próbie pobierania zamówień otrzymuje taką komunikat:

*   Trying 185.31.27.150...
* TCP_NODELAY set
* Connected to api.allegro.pl (185.31.27.150) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=PL; ST=Wielkopolskie; L=Poznan; OU=IT; O=Allegro.pl sp. z o.o.; CN=edge.allegro.pl
*  start date: May 28 13:20:05 2019 GMT
*  expire date: May 28 13:20:05 2020 GMT
*  subjectAltName: host "api.allegro.pl" matched cert's "api.allegro.pl"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x2bee140)
> GET /order/events?from=1570559899282313&type=READY_FOR_PROCESSING HTTP/2
Host: api.allegro.pl
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer 
Content-Length: 57

* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: 5b7d731f88975623
< date: Wed, 09 Oct 2019 12:30:02 GMT
< x-ratelimit-remaining: 9000
< x-content-type-options: nosniff
< content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
< content-length: 13
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 29
< 
* Connection #0 to host api.allegro.pl left intact
{"from":"1570559899282313","type":"READY_FOR_PROCESSING"}

**Comment by MaciejFrackowiak** [comment]
Event o ID=1570559899282313 jest ostatnim eventem tj. nic po nim już nie występuje, dlatego otrzymujesz pustą odpowiedź. Wystarczy, że cofniesz się o 1, czyli ID=1570559899282312 i już otrzymasz właściwy wynik.
Na przyszłość proszę także nie wklejaj na forum swojego tokena.
