### ISSUE TITLE
401 przy dodawaniu cennika dostawy

### ISSUE THREAD

**Issue by thisi5patrick** [allegro/allegro-api#2345]
Po ustawieniu header'ów tak jak w dokumentacji oraz tak jak w [https://developer.allegro.pl/sale/#shipping-rates](https://developer.allegro.pl/sale/#shipping-rates) dostaję w responsie kod 401. 
Kod który wykonuję

    url = 'https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates'

    headers = {
        'Accept': 'application/vnd.allegro.public.v1+json',
        'Authorization': token,
        'Content-Type': 'application/vnd.allegro.public.v1+json'
    }

    data = {
        "name": delivery_name,
        "rates": upload_dict
    }
    response = rqst.post(url, headers=headers, json=data, auth=HTTPBasicAuth(clientId, clientSecret))

Chciałbym zaznaczyć że dostaję tylko w tym miejscu response z kodem 401. Przy wykonywaniu innych czynności na ofertach używając POST lub PUT, wszystko działa bez problemu

**Comment by MaciejFrackowiak** [comment]
Do autoryzacji musisz wykorzystać bearer token, a w Twoim wywołaniu widzę tylko token. Niestety, trudno nam tu coś więcej dodać, ponieważ nie widzimy pełnego wywołania, a jak wspomniałem wcześniej ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich.

**Comment by thisi5patrick** [comment]
Jak widzimy w dokumentacji brakuje dopiski bearer [https://imgur.com/a/XFuKPba](https://imgur.com/a/XFuKPba). Nawet po dodaniu bearer, występuje response code 401

**Comment by MaciejFrackowiak** [comment]
To przykład z poradnika, w samej dokumentacji pełne info mamy [POST /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST) :) Niemniej bez pełnego wywołania ciężko nam tu coś obecnie doradzić.

**Comment by thisi5patrick** [comment]
Tak wygląda więc pełne wywołanie


    clientId = '8a0452b7dbde45b7821e11614f3d75fb'
    clientSecret = 'kQB32gTrDxuDud4Ui8URmL9NXeSc0sqMBHtTJ8QlHwkTGnEFE22CRWCwvJOGleAW'
    token = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NzA3ODU1ODUsInVzZXJfbmFtZSI6IjQ0MjE1MTE4IiwianRpIjoiMDU1MGU3ZDgtMzYyZC00MDhmLTk5MDEtODI4Nzg0MGQzNGEyIiwiY2xpZW50X2lkIjoiOGEwNDUyYjdkYmRlNDViNzgyMWUxMTYxNGYzZDc1ZmIiLCJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdfQ.l35neKv49ofptb0M4uYfizb_V5dTZZ664OvyDnxKaJHPG7xaoJCFujlfCz-RZKN40c4juQekowt1177DJziFE5usDVtmN8t7C4UVBbwujiycpet9XU7dhmnW5-yT_oIdSWenC35lx53rMOwHNBFHFKR634Za_NzyF0Y8meIT9GffH8KzUgHPnWgFh-Trw0xHQllpDszkB9sxB72FYVngIzFcpxZWHhrX9Ik965WsEjeM3IzJYxd9Rt1Cvg7T8tyJ_VuN4d-0BVj88d_Zn6QCpPT_aY1jFeJ1lc0YWNG2lwhfLpIkqhRuhNfLnSTXDnMWB_0Xc_OdrXGj7yJuP5QkWqxJSc1D62wLjrSlaxSuGZWEd6OyzqWAUcrQb-BmQSjpxViUoEYrvKWokI7dmTE8AVuYLj6l1xQR1esooZGbqeXn0yPwG-b3XJ87iy4pgONCPDfQIOIlUgvBqMKtnDxMvhlF8hm-uOYQyKGfeknOl6cWR8Hpcy5HTKdD0wAg0mmNUdgL7z4zCiq6mQKYyMRndQvmgEmXh8HX7j2SRVPRoImgNlm-9Xm-Mvk7lxAZWw-n6d3Yq0M2bs97p5a2RRHM9ViNqXLaoRoTtXTAFvjW8wWJl-KZooBmVpE55wX91dP7tQbTMJirKonIDkyaMz1rN0hWPBcGibudb287i2Hu_Sg'
    url = 'https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates'

    headers = {
        'Accept': 'application/vnd.allegro.public.v1+json',
        'Authorization': 'Bearer ' + token,
        'Content-Type': 'application/vnd.allegro.public.v1+json'
    }
    
    data ={
        "name": "Test 123",
        "rates": [
            {
                "deliveryMethod": {
                    "id": "7203cb90-864c-4cda-bf08-dc883f0c78ad"
                },
                "maxQuantityPerPackage": "1",
                "firstItemRate": {
                    "amount": "1",
                    "currency": "PLN"
                },
                "nextItemRate": {
                    "amount": "1",
                    "currency": "PLN"
                }
            },
            {
                "deliveryMethod": {
                    "id": "758fcd59-fbfa-4453-ae07-4800d72c2ca5"
                },
                "maxQuantityPerPackage": "1",
                "firstItemRate": {
                    "amount": "1",
                    "currency": "PLN"
                },
                "nextItemRate": {
                    "amount": "1",
                    "currency": "PLN"
                }
             }
        ]
    }
    response = rqst.post(url, headers=headers, json=data, auth=HTTPBasicAuth(clientId, clientSecret))

A response code wygląda tak


    {
        "error": "unauthorized",
        "error_description": "Full authentication is required to access this resource"
    }

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikuj proszę:
- czy Bearer nie przekazujesz w cudzysłowie (na to wskazuje wywołanie),
- końcówkę kodu - response = rqst.post(url, headers=headers, json=data, auth=HTTPBasicAuth(clientId, clientSecret))
czy na pewno korzystasz z OAuth 2.0 a nie z Basic.
