### ISSUE TITLE
Błąd: a0e5e9c2c0613d09

### ISSUE THREAD

**Issue by korzyniewskid2112** [allegro/allegro-api#2346]
Występuje problem: 
 - [x] z zasobem REST API
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Request path: /login/auth
Query string: origin_url=https%3A%2F%2Fapps.developer.allegro.pl.allegrosandbox.pl%2F
Message: No instance of service allegro-auth-service was found with query: tags = [], instancesDatacenter = InstancesDatacenter{type=LOCAL_WITH_FALLBACK_TO_ANY, dc=Optional.empt

Traceid : a0e5e9c2c0613d09

Brak możliwośći logowania się do sandboxa i pobierania tockena do środowiska testowego.

**Comment by MaciejFrackowiak** [comment]
Update - Sandbox funkcjonuje już prawidłowo.

**Comment by WGRINGO** [comment]
U mnie dalej nie idzie pobrać tokena do środowiska testowego Dostaję:
(HTTP/1.1 400 Bad Request)

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Przetestowałem właśnie funkcjonalność - token bez przeszkód otrzymałem. Proszę podeślij nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) pełne wywołanie - w treści wiadomości dodaj numer tematu z GitHub - 2346.

**Comment by WGRINGO** [comment]
Sprawdziłem jeszcze raz - refresh token się wywalał ale jak wygenerowałem od zera to ruszyło. Teraz jest ok.
