### ISSUE TITLE
order/checkout-forms Error Issue

### ISSUE THREAD

**Issue by wgx-precy** [allegro/allegro-api#2347]
We tried to get order list via the following request and got an ambigious error return
https://api.allegro.pl/order/checkout-forms?status=ALL&lineItems.boughtAt.lte=2019-09-26T00%3A00%3A00.000&lineItems.boughtAt.gte=2019-07-01T00%3A00%3A00.000&offset=1&limit=50

return as
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/order/checkout-forms","userMessage":null}]}

This is kind of hard for us to debug what's wrong. Could you please help to check?

**Comment by MaciejFrackowiak** [comment]
You forgot about time zone - according to ISO8601 time format is (yyyy-MM-dd'T'HH:mm:ss.SSSZ), so you should add Z to time (e.g. 2019-09-26T00%3A00%3A00.000Z).
