### ISSUE TITLE
Problem umieszczania aukcji w błędnych kategoriach, przez wystawiających

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2348]
:bulb: **Sugestia**

Chciałbym poruszyć sprawę kategorii produktów w wystawianych aukcjach.

Jak "przekonać" wystawiających żeby umieszczali swoje aukcje w odpowiednich kategoriach?  
A nie jak to się często dzieje w błędnej kategorii lub "na odczepne" w kategorii "pozostałe".

Nie twierdzę że jest to sprawa "uniemożliwiająca pracę" ale jest to jakiś problem, którego rozwiązanie bardzo by ją ułatwiło. 

Myślę że Allegro ma tu duże pole do działania. Prawidłowe kwalifikowanie produktów do kategorii przez wystawiających ułatwi proces wyszukiwania również a może głównie Wam.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, problem właściwego przypisania przedmiotów do odpowiednich kategorii to realne wyzwanie. Jako Allegro prowadzimy szereg działań edukacyjnych, których celem jest przekazanie sprzedającym wiedzy, że właściwe dopasowanie kategorii dla przedmiotu to jeden z kluczowych elementów efektywnej sprzedaży. Oczywiście podejmujemy także działania weryfikacyjne, gdy zgłaszane są nam oferty, które zostały nieprawidłowo przypisane do kategorii.

**Comment by frankii91** [comment]
Fajnie ale od prawie 10 lat nigdy nie dostałem ankiety jakich kategorii brakuje, albo które są zbędne w danym dziale gdzie sprzedajemy/czy sprzedawaliśmy, oraz nic związanego z parametrami czy jakieś są zbędę czy jakiś brakuje oraz/lub czy dane słownikowe są ok lub czegoś brakuje
Powinno dać się to szybko i prosto dodawać weryfikować... - np. jakiś panel zgłoszeń a potem szybka ankieta po zalogowaniu sprzedawcy nawet obowiązkowa  - wtedy od zgłoszenia do wdrożenia wystarczył by 1-2 a dni jak większość sprzedawców z danego działu oczywiście byłą by za lub przeciw ... taki automat do likwidacji parametrów dodawania nowych jak i wartość słownikowych.

**Comment by MaciejFrackowiak** [comment]
@frankii91 Oczywiście sugestie co do brakujących kategorii Allegro możesz przesłać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Natomiast Twoje spostrzeżenie dotyczące samej ankiety przekazuję do właściwego działu.
