### ISSUE TITLE
Wznawianie aukcji - Niepoprawna liczba sztuk

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2349]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym
 - [X] inny

:beetle: **Opis**

Dzień dobry, jest problem ze wznawianiem aukcji na sandboxie. Dlaczego nie można wznowić aukcji z liczbą sztuk 3? Wcześniej było kupione 3 sztuki, teraz chce wznowić na kolejne 3, to mam wstawić 6?

W dokumentacji nie znalazłem informacji o wymaganiach dotyczących sztuk na wznawianej aukcji:
https://developer.allegro.pl/sale/#step-9-offer-publication-commands
https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-wznowic-zakonczona-oferte-z-tym-samym-numerem-i-zachowac-jej-popularnosc-5VZxXd2rzUX

![image](https://user-images.githubusercontent.com/8465007/66568793-7431eb00-eb6a-11e9-96db-f4cc74399dda.png)

Przez rest api ten sam problem, tylko błąd nie jest "niepoprawna liczba sztuk", a jest błąd nic nie mówiący w czym problem:

```
65c982c1-9308-49ab-90c1-d599c2553ff6

{
    "tasks": [
        {
            "offer": {
                "id": "6206636295"
            },
            "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
            "status": "FAIL",
            "scheduledAt": "2019-10-10T11:55:31.863Z",
            "finishedAt": "2019-10-10T11:55:35.473Z",
            "field": "publication",
            "errors": [
                {
                    "code": "CHANGE_PUBLICATION_STATUS_ERROR",
                    "message": "An error occurred while trying to change the publication of the offer. Please try again later.",
                    "details": null,
                    "path": null,
                    "userMessage": "Wystąpił błąd podczas próby zmiany statusu publikacji oferty. Proszę spróbować później."
                }
            ]
        }
    ]
}
```
Proszę o poprawę wznawiania, tak aby dało się wznowić aukcję bez potrzeby uwzględniania liczby sprzedanych sztuk. Skoro wznawiam na 3 sztuki to tyle chce mieć dostępnych do sprzedaży po prostu.

**Comment by MaciejFrackowiak** [comment]
To nie jest błąd - tak działa ten mechanizm “od zawsze”, zarówno w API, jak i w serwisie WWW. Zmieniając liczbę sztuk należy uwzględniać liczbę dotychczas sprzedanych przedmiotów.

**Comment by imper86** [comment]
@MaciejFrackowiak serio? Tak było w WebAPI, ale w REST podjemy już tylko liczbę dostępnych przedmiotów, aktualizując stan na aukcji. Popraw mnie jeśli się mylę.

**Comment by SebastianOzdoba** [comment]
@maciejfrackowiak to jest błąd krytyczny Stwierdzenie, że tak było od zawsze nie jest prawdą, tak było w WEBApi, w RESTAPI nie miało być żadnego odejmowania.

**Comment by alekskuc** [comment]
Przy założeniu: Wcześniej było kupione 3 sztuki, teraz chce wznowić na kolejne 3.

Obejście tematu, to wysłanie FIXED przed ACTIVATE dla zakończonej aukcji metodą:
1. /sale/offer-quantity-change-commands/{commandId}
{"changeType":"FIXED","value":3}

2. PUT /sale/offer-publication-commands/{commandId}
wznowić zakończone oferty - w statusie ENDED. Przekaż dla takich ofert wartość 'ACTIVATE' w polu action. Udostępnimy je ponownie w serwisie.

3. I to nie kompletne rozwiązanie, bo w edycji na szczegółach jest 6, wysłałem 3, a sprzedaje 3.

**Comment by SebastianOzdoba** [comment]
Powinniśmy zatem robić tak
- ustawić ilość na 3 przez metodę z opcją Fixed
- potem activate
Allegro jak widać doda samoczynnie 3 do 3 i będziemy widziec 6 na ofercie, 3 sprzedane, 3 dostępne. Głupota ale cóż poradzić :)
________________________________
Od: aleks.kuc <notifications@github.com>
Wysłane: 10 października 2019 18:07:29
Do: allegro/allegro-api
DW: Sebastian Ozdoba; Comment
Temat: Re: [allegro/allegro-api] Wznawianie aukcji - Niepoprawna liczba sztuk (#2349)


Przy założeniu: Wcześniej było kupione 3 sztuki, teraz chce wznowić na kolejne 3.

Obejście tematu, to wysłanie FIXED przed ACTIVATE dla zakończonej aukcji metodą:

  1.  /sale/offer-quantity-change-commands/{commandId}
{"changeType":"FIXED","value":3}

  2.  PUT /sale/offer-publication-commands/{commandId}
wznowić zakończone oferty - w statusie ENDED. Przekaż dla takich ofert wartość 'ACTIVATE' w polu action. Udostępnimy je ponownie w serwisie.

  3.  I to nie kompletne rozwiązanie, bo w edycji na szczegółach jest 6, wysłałem 3, a sprzedaje 3.

**Comment by darjusz** [comment]
Problem wciąż występuje, testowane na produkcji. Co ciekawe w panelu Allegro w kolumnie sprzedano jest mniejsza ilość, niż minimalna, która pozwala wprowadzić formularz edycji oferty (prawdopodobnie dlatego, że w tej kolumnie jest sprzedaż z ostatnich 30 dni).

Oferta: 8411548555

Błąd:
![image](https://user-images.githubusercontent.com/15068657/100074655-4deb0f80-2e3f-11eb-9f42-aef0f8765469.png)


Dodatkowo po wprowadzeniu odpowiedniej ilości jest ona wyświetlana jako dostępna do zakupu (nie jest pomniejszana o ilość sprzedanych).

Bardzo proszę o rozwiązanie problemu.

**Comment by AureliuszBrussy** [comment]
@darjusz wątek będzie kontynuowany w nowym zgłoszeniu, które utworzyłeś: #3916
