### ISSUE TITLE
Propagowanie linków do aukcji (pytanie/idea)

### ISSUE THREAD

**Issue by KNiepok** [allegro/allegro-api#235]
Witam, przypuśćmy że chciałbym zrealizować następujący scenariusz:
1. Tworzę aukcję, na której wystawiam n produktów.
2. Propaguję URL innym (powiedzmy użytkownikowi klasy A) (np. poprzez personalizowanie URLa do aukcji poprzez doklejenie getowego parametru)
3. Użytkownik A przekazuje kolejnemu użytkownikowi (B) spersonalizowany URL do aukcji
4. Użytkownik B dokonuje zakupu
5. Jestem w stanie poprzez API prześledzić, że zakupu dokonano dzięki URLowi użytkownika A

Czy jest to technicznie wykonalne w istniejącym systemie? Jeśli jest, ale według innego mechanizmu, gdzie szukać informacji na ten temat?

**Comment by MaciejPotepa** [comment]
Dzień dobry.

Niestety nasz API nie oferuje takiej możliwości i na ten moment nie mamy takich rozwiązań w planach. 
Również nie możemy niczego polecić.

**Comment by KNiepok** [comment]
Dziękuję za szybką odpowiedź!
