### ISSUE TITLE
Integracja magento 2 z allegro

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2350]
Czy jest możliwość aby wysłać z magento 2.3.3 do allegro produkty do dowolnej kategorii?
Np. Sporty walki lub Odzież i wiadomo jakiejś docelowej podkategorii?

**Comment by pawelosajda** [comment]
Jeśli posiadasz odpowiednią integracje to tak. W samym czystym magento nie ma takiej możliwości.

**Comment by sportmma** [comment]
POSIADAM taka integrację, ale ponoć nie można wysłać produktu do każdej kategori, poniewaz nie dajecie takiej możliwości?

**Comment by sportmma** [comment]
Można przesłać ponoć produkt tylko do wybranych kategorii?

**Comment by PrzemyslawLukanowski** [comment]
Ofertę możesz wystawić w każdej kategorii, dodać nowy produkt tylko w wybranych. Musisz wiedzieć, że produkt nie jest równoznaczny z ofertą. Produkt to istniejący towar, np. o konkretnym numerze EAN, z którym może być powiązanych wiele ofert. Jaka jest dokładnie Twoja potrzeba?

**Comment by sportmma** [comment]
Mam w magento wszystkie produkty dostępne na stronie mantohurt.pl marka: manto i chce je dodać również w ofercie na allegro. Mantohurt.pl to hurtownia w której się zaopatrzam

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku możesz wystawić standardowe oferty, nie ma potrzeby dodawania nowych produktów (w kategorii moda i tak jest to niemożliwe).

**Comment by sportmma** [comment]
Co mam rozumieć przez standardowe oferty?

**Comment by sportmma** [comment]
Wystawie te standardowy eferty przez api?

**Comment by PawelTaberski** [comment]
Przez API możesz wystawić ofertę jak to Przemek napisał standardową, a także możesz taką ofertę powiązać z produktem. Możesz również od razu wystawić ofertę powiązaną z produktem. Ofertę możesz powiązać z produktem tylko w niektórych kategoriach. Na naszej stronie znajdziesz informacje:

- [Jak wystawić ofertę](https://developer.allegro.pl/sale/)
- [Jak powiązać ofertę z produktem](https://developer.allegro.pl/productization/)

**Comment by szokart** [comment]
Akutalnie trwają prace nad stworzeniem właśnie rozszerzenia do Magento 2
https://github.com/macopedia/magento2-allegro
