### ISSUE TITLE
Utrata danych po wysłaniu przez PUT [Python]

### ISSUE THREAD

**Issue by thisi5patrick** [allegro/allegro-api#2351]
Próbuję wystawić ofertę z różnymi parametrami. Parametry są tworzone jako `dictionary`, a kolejnie dodane do `list`. 

Jest tworzone w ten sposób:

    params = []
    for key, value in post_params.items():

        if value == '' or key in keys_to_exclude:
            continue

        if type(value) == list:
            val = value
        else:
            val = [value]

        tmp_dict = {
            'id': key,
            'valuesIds': val,
            'values': [None],
            'rangeValue': None
        }
        params.append(tmp_dict)

Czyli końcowy efekt wygląda tak:

    'parameters':[
        {
            'id':'11323',
            'valuesIds':[
                '11323_1'
            ],
            'values':[
                None
            ],
            'rangeValue':None
        },
        {
            'id':'130709',
            'valuesIds':[
                '130709_16',
                '130709_1'
            ],
            'values':[
                None
            ],
            'rangeValue':None
        }
    ]

Po wysłaniu requesta PUT aby dodać nową ofertę dostaję te błędy:

    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "You can only assign dictionary parameter by valueId for 11323.",
                "details": "",
                "path": "",
                "userMessage": "You can only assign dictionary parameter by valueId for 11323."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "No values given for parameter Stan(11323).",
                "details": "",
                "path": "",
                "userMessage": "No values given for parameter Stan(11323)."
            }
        ],

A moje zwrócone parametry wyglądają w taki sposób:

    'parameters':[
        {
            'id':'11323',
            'valuesIds':[],
            'values':[
                None
            ],
            'rangeValue':None
        },
        {
            'id':'130709',
            'valuesIds':[],
            'values':[
                None
            ],
            'rangeValue':None
        }
    ]

W dokumentacji `valuesIds` ma kwadratowe klamry, co ewidentnie oznacza że jest to lista.
Chciałbym również zaznaczyć, że dane są wysyłane jako `json`
Wie ktoś dlaczego tak się dzieje?

**Comment by PrzemyslawLukanowski** [comment]
Jak wspominaliśmy przy okazji innych zgłoszeń - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.

Mogę dodać, że podobny błąd udało mi się odtworzyć, jeśli w środku tablicy “values” przekazałem wartość null. Widzę, że w Twoim przypadku widnieje tam None, które - sugerując się None z rangeValue - zostało przekonwertowane z wartości null. Być może tutaj tkwi przyczyna? W takim przypadku zamiast:

```
   tmp_dict = {
        'id': key,
        'valuesIds': val,
        'values': [None],
        'rangeValue': None
    }
```
przekaż:

```
   tmp_dict = {
        'id': key,
        'valuesIds': val,
        'values': [],
        'rangeValue': None
    }
```

**Comment by thisi5patrick** [comment]
Tam tkwił problem.
Dziękuję, zamykam
