### ISSUE TITLE
REST API - Pobieranie informacji - ADRES URL

### ISSUE THREAD

**Issue by arek094** [allegro/allegro-api#2352]
Witam, potrzebuje pomocy, otóż pobieram informacje dotyczące zamówień za pomocą zapytania
https://api.allegro.pl/offers/listing?seller.id={Seller_ID} i wszystko działa natomiast nie ma tam informacji na temat adresu URL do aukcji? 

Czy ktoś wie jak można wyciągnąć tą informacje?

Z góry Dziękuje

**Comment by kfijalko** [comment]
Rozumiem, że piszesz o listowaniu ofert.
Nie wiem czy jest lepszy sposób, ja to robię tak:
Odpytuje cUrlem: 'https://allegro.pl/i'.$offer_id.'.html'
W odpowiedzi dostaję przekierowanie: http_code=301 i w nagłówku jest 'location:', który zawiera adres do oferty.

Jeżeli ktoś zna lepszy/szybszy sposób to prośba o dopisanie.

**Comment by PrzemyslawLukanowski** [comment]
@arek094 Takiego pola nie zwracamy w żadnym zasobie.

**Comment by arek094** [comment]
A jest może jakiś prosty sposób na wyciągnięcie adresu?
