### ISSUE TITLE
Kilka linii w content w sekcji

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2354]
Załóżmy, że wysyłam taki tekst w JSON:

"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
 sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, 
quis nostrud exercitation ullamco laboris 
nisi ut aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit in voluptate velit esse
 cillum dolore eu fugiat nulla pariatur. 
Excepteur sint occaecat cupidatat non proident, sunt in culpa
 qui officia deserunt mollit anim id est laborum.</p>"

Jak to powinno wyglądać w sekcji, w content, aby allegro wiedziało, gdzie kończą się linię i JSON był poprawny?
{
          "type": "TEXT",
          "content": "(?)"
}

**Comment by kfijalko** [comment]
Allegro kasuje końce linii. Jeżeli zależy Ci na podziale to musisz użyć <p> (lub innego dozwolonego) dla każdej linii.
