### ISSUE TITLE
Dodanie maila do GET /me

### ISSUE THREAD

**Issue by baambaam** [allegro/allegro-api#2355]
:bulb: **Sugestia**

Do zarejestrowania usera u siebie w serwisie potrzebowałbym adres email przekazany z allegro. Będzie taka możliwość, aby poza obecnymi danymi pojawił się tam również adres email?

**Comment by PrzemyslawLukanowski** [comment]
Podobna sugestia pojawiła się już w wątku #2316, przekazaliśmy ją do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie, poinformujemy o tym we właściwym komunikacie.
