### ISSUE TITLE
Order events -  dodatkowy event FILLED_IN pojawiający się po READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2357]
Mam zamówienie dla którego pojawiają się kolejno eventy (wg. daty wystąpienia, lub id):
1. BOUGHT
2. FILLED_IN
3. READY_FOR_PROCESSING
4. FILLED_IN
Występowanie pierwszych 3 mnie nie dziwi, nawet jak by były w różnej kolejności, ale czego dotyczy ten ostatni 4 ? według dokumentacji nie powinien się już pojawić taki status jak wystąpi READY_FOR_PROCESSING. 
Data wystąpienia dla 3 i 4 jest identyczna, id jest różne.
Dotyczy CheckoutFormId: d0713d62-ec03-11e9-8a76-354dd967f9b8

Na sandboxie też mam zamówienie gdzie występuje podobny problem.

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) numer oferty i login kupującego, którego dotyczy ta transakcja. Sprawdzimy to. W zgłoszeniu dodaj, że dane są potrzebne do ticketa numer 2357 na GitHub-ie.

**Comment by avello** [comment]
Przesłane.
Drugi przypadek mam na sandboxie.
Testowałem opcję wspólnej płatności dla 2 nieopłaconych zamówień (z poziomu zakładki "Moje zakupy" w panelu klienta).
W obu zamówieniach miałem eventy: BOUGHT i FILLED_IN.
Natomiast zamówienie połączone po opłaceniu ma eventy: BOUGHT, FILLED_IN, READY_FOR_PROCESSING, FILLED_IN.
Data wystąpienia 2 ostatnich eventów jest identyczna.

**Comment by PawelTaberski** [comment]
Sprawdziłem i zgodnie z [naszym poradnikiem](https://developer.allegro.pl/orders/#02):
"Z uwagi na uwarunkowania techniczne, w pojedynczych przypadkach zdarzenia mogą pojawić się w nieoczekiwanej kolejności; to znaczy, że jest możliwość by np. zdarzenie ze statusem READY_FOR_PROCESSING pojawiło się przed FILLED_IN; nie traktujemy tego jako błąd."

**Comment by Onixarts** [comment]
Czy w przypadku wystąpienia takiego zjawiska, oznacza to, że nie powinniśmy traktować zamówienia jako ready for processing i może się w nim jeszcze coś zmienić? Czy po prostu tak wyszło i skoro już był status READY_FOR_PROCESSING tzn. że już jest wszystko ok i można przetwarzać zamówienie?

**Comment by PawelTaberski** [comment]
@Onixarts Zgodnie z [naszym poradnikiem](https://developer.allegro.pl/orders/#01) jeśli otrzymałeś:
"READY_FOR_PROCESSING - klient wypełnił FOD i sfinalizował płatność (status: zakończona), albo wybrał płatność przy odbiorze lub odbiór osobisty. Dopiero w tym statusie zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni."
Czyli jak najbardziej możesz przetwarzać takie zamówienie.
