### ISSUE TITLE
GET /order/checkout-forms - identyfikator płatności

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2358]
Metoda przekazuje identyfikator płatności zawsze w statusie innym niż BOUGHT ?

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem Twoje pytanie możesz sobie odfiltrować po statusach jakie Ciebie interesują. Dokładny opis tego zasobu znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#03).

**Comment by pietrach** [comment]
Chodzi o poniższe dane. Czy one są wypełnione w przypadku gdy zamówienie ma status `FILLED_IN` lub `READY_FOR_PROCESSING` ?
```
"payment": {                                          
      "id": "abd30d72-9583-11e8-96ed-27298c74ae02",   
      "type": "ONLINE",                                                                              
      "provider": "PAYU"                                                                                    
}
```
