### ISSUE TITLE
Cicha awaria w allegro ze wznawianiem ofert

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2359]
Nawiązując do tego taska https://github.com/allegro/allegro-api/issues/2320 podbijam bo może to dotyczyć także innych osób tutaj.

@PrzemyslawLukanowski skoro wiecie o tym problemie - braku możliwości wznawiania ofert, dlaczego sprzedawcy nie zostali poinformowani ? Dlaczego nie ma żadnego komunikatu o tym problemie ? Dzisiaj jeden z naszych klientów dowiedział się **od nas** że w zawieszeniu ma 3800 ofert których nie może sprzedać. Ma sobie je wystawić na nowo - tracąc przy tym popularność. Po 10 dniach od momentu zgłoszenia błędu Wam on nie miał o tym zielonego pojęcia. 

I wiem wiem. Przekazał Pan moją informację do odpowiedniego działu.

Nie działa również wznawianie przez UI bezpośrednio z allegro.pl 

Wasz czat z kolei mówi sprzedawcom żeby ciasteczka pokasowali lub spróbowali w trybie incognito przeglądarki.

Czy tylko ja widzę tutaj jakiś problem ?

**Comment by PawelTaberski** [comment]
Zespół odpowiedzialny za tą funkcjonalność pracuje nad rozwiązaniem problemu ze wznawianiem ofert.
