### ISSUE TITLE
fid: 27 nie jest zwracana aktualna wartość przez API

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#236]
W polu "Dodatkowe informacje o wysyłce i płatności" zwracane są przez API nieaktualne wartości. 

Zmieniłem stary opis na nowy, **dodałem** lub **edytowałem** dodatkowe informacje. Na aukcji wszystko jest OK. Przez API fid 27 jest po staremu.

**Comment by MaciejPotepa** [comment]
Dzięki za zgłoszenie. 

Proszę podaj **numer oferty** i **treści request i response**, które otrzymujesz. Bez tego nie jestem w stanie zbadać problemu.

**Comment by Lebioda** [comment]
Ticket#1247921484

edytowałem wiele opisów, więc to nie jest pojedynczy przypadek, można reprodukować.

**Comment by MaciejPotepa** [comment]
Dzięki za podesłanie numeru oferty, ale potrzebujemy trochę więcej danych niż jedna oferta. Jeżeli problem występował masowo, podaj więcej ofert, w których pojawił się problem. 

No i proszę ponownie o załączenie request i response w XMLu.

**Comment by Lebioda** [comment]
Zmieniałem kilkaset ofert, część ręcznie, część skryptem. Teraz nie odnajdę, które były ręcznie. Problem dotyczy ustawiania ręcznego, a nie skryptem, więc XMLów nie ma.

Scenariusz był taki:
1. Jest oferta ze starym opisem -> klikam edytuj
2. wgrywam zdjęcia, dodaje nowy opis
3. dodaje lub edytuje dodatkowe informacji
4. Zapisuje, czekam na aktualizacje na www
5. Aukcja przez www wygląda OK. Przez API FID 27 jest ze starą wartością.

Czy dla podesłanego numeru oferty nie zwraca Wam pustego fid'a 27? Przez WWW coś tam jest wpisane.

**Comment by MaciejPotepa** [comment]
Dzięki za dokładne informacje. Pojawiło się więcej przypadków w innym issue na GitHubie. 
Problem wystąpił u większej ilości użytkowników. Pracujemy nad rozwiązaniem.
