### ISSUE TITLE
Sandbox Error 500 - /order/checkout-forms

### ISSUE THREAD

**Issue by anghnam** [allegro/allegro-api#2360]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms wyrzuca błąd 500 - INTERNAL_SERVER_ERROR

Trace-id : afb9f3fb67b9aeb9

GET /order/checkout-forms HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json
Authorization: Bearer XXXX

Response : 
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

**Comment by PawelTaberski** [comment]
Przetestowałem i zasób działa normalnie, czy u Ciebie dalej występuje problem?

**Comment by anghnam** [comment]
Tak, może to dlatego, że to jest nowy użytkownik bez żadnych zamówień?
Nowy trace-id: a4080fe231d62aa0

**Comment by PawelTaberski** [comment]
Sprawdziłem w takim wypadku powinieneś otrzymać informacje:
```
{
    "checkoutForms": [],
    "count": 0,
    "totalCount": 0
}
```
Jeśli w dalszym ciągu występuje u Ciebie ten problem, to podeślij proszę:

- Client_ID
- User_ID na którym nie masz żadnych zamówień i otrzymujesz błąd

**Comment by anghnam** [comment]
Już działa, dziękuję za pomoc
