### ISSUE TITLE
id = string and vs id = guid gdzie kiedy ?

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2363]
Jak wyczytać z dokumentacji że dane id z dokumentacji to dowolny string lub string w wersji guid?

np. przy wystawianiu oferty (draft)
category.id  wiem że string bo różnie bywa
"id" string z int - numerek aukcji
 parameters.id string z inta
deliveryMethod.id   string z guid

ciężko to odczytać ponieważ raz na stronach dokumentacji jest jako przykład podany przykładowy guid wtedy jest to jasne a raz jest "string" i trzeba szukać dalej jaki string :(

Ktoś ma jakiś sposób na to ?

**Comment by PawelTaberski** [comment]
Zgłosiłem sugestię, aby ujednolicić sposób podawania tych informacji.
