### ISSUE TITLE
swagger.yaml OpenAPI Generator error

### ISSUE THREAD

**Issue by michalorlinskidev** [allegro/allegro-api#2364]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Problem generacji klienta JAVA na podstawie swagger-a**

Wygenerowanie klienta JAVA i próba zbudowania biblioteki kończy się niepowodzeniem z powodu błędów podczas kompilacji:

[INFO] 10 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.554 s
[INFO] Finished at: 2019-10-13T11:12:46+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project allegro-restapi-client: Compilation failure: Compilation failure:
[ERROR] path/src/main/java/org/openapitools/client/model/CategoryProductParameter.java:[105,46] incompatible types: java.lang.String cannot be converted to org.openapitools.client.model.CategoryProductParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/FloatCategoryProductParameter.java:[57,17] getType() in org.openapitools.client.model.FloatCategoryProductParameter cannot override getType() in org.openapitools.client.model.CategoryProductParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryProductParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/CategoryParameter.java:[110,46] incompatible types: java.lang.String cannot be converted to org.openapitools.client.model.CategoryParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/DictionaryCategoryParameter.java:[65,17] getType() in org.openapitools.client.model.DictionaryCategoryParameter cannot override getType() in org.openapitools.client.model.CategoryParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/DictionaryCategoryProductParameter.java:[64,17] getType() in org.openapitools.client.model.DictionaryCategoryProductParameter cannot override getType() in org.openapitools.client.model.CategoryProductParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryProductParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/StringCategoryProductParameter.java:[57,17] getType() in org.openapitools.client.model.StringCategoryProductParameter cannot override getType() in org.openapitools.client.model.CategoryProductParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryProductParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/IntegerCategoryProductParameter.java:[57,17] getType() in org.openapitools.client.model.IntegerCategoryProductParameter cannot override getType() in org.openapitools.client.model.CategoryProductParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryProductParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/IntegerCategoryParameter.java:[58,17] getType() in org.openapitools.client.model.IntegerCategoryParameter cannot override getType() in org.openapitools.client.model.CategoryParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/StringCategoryParameter.java:[58,17] getType() in org.openapitools.client.model.StringCategoryParameter cannot override getType() in org.openapitools.client.model.CategoryParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryParameter.TypeEnum
[ERROR] path/src/main/java/org/openapitools/client/model/FloatCategoryParameter.java:[58,17] getType() in org.openapitools.client.model.FloatCategoryParameter cannot override getType() in org.openapitools.client.model.CategoryParameter
[ERROR]   return type java.lang.String is not compatible with org.openapitools.client.model.CategoryParameter.TypeEnum

Polecenie którym generuje klienta to:
java -jar lib/openapi-generator-cli-4.1.2.jar generate -i swagger/swagger.yaml -g java -o .

Uwaga!
zmiana na -g spring nie jest rozwiązaniem

**Comment by PawelTaberski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu, jak tylko otrzymam jakieś informacja dam znać.

**Comment by michalorlinskidev** [comment]
Po jakim czasie można spodziewać się jakiejś odpowiedzi?

**Comment by PawelTaberski** [comment]
Tak, jak pisałem zgłosiłem tą sprawę, jak tylko otrzymam jakieś dodatkowe informacje dam znać.

**Comment by michalorlinskidev** [comment]
Czy coś ruszyło się w temacie?

**Comment by PawelTaberski** [comment]
Zespół jeszcze pracuje nad tym zgłoszeniem.

**Comment by michalorlinskidev** [comment]
Używając najnowszej wersji swagger-a oraz openapi-generator-cli 4.2.2 problem nie występuje. Dziękuję za rozwiązanie problemu.
