### ISSUE TITLE
Informacja czy wygrałem licytacje

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#2365]
Witam,

Próbuje znaleźć metodę do sprawdzenia czy wygrałem licytacje. Metoda BID jako GET zwraca informacje czy oferta jest najwyższa, więc teoretycznie na jej podstawie można wyciągnąć taką informację, ale trzeba wiedzieć czy aukcja już się zakończyła. Jest może jakaś inna lepsza droga aby uzyskać taką informację? Jaką metodą sprawdzić czy aukcja już się zakończyła?

**Comment by PawelTaberski** [comment]
Informacje o tym, czy dana oferta się zakończyła możesz znaleźć w dzienniku ofertowym GET /sale/offer-events. Więcej na jego temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#journal).

**Comment by robsonek** [comment]
> Udostępniliśmy dziś nowy zasób w wersji beta - GET /sale/offer-events. To dziennik zdarzeń w ofertach zalogowanego sprzedawcy, który zwraca informacje z ostatnich 24 godzin o

Nie wiem czy dobrze to rozumiem, ale tą metodą sprawdzę czy aukcja się zakończyła będąc jej wystawcą. Ja poszukuję metody od drugiej strony, dzięki której jako oferent (a nawet lepiej nie) tej licytacji otrzymam informacje że aukcja dobiegła końca.

**Comment by PawelTaberski** [comment]
Obecnie nie mamy zasobu w REST API który zwróci Tobie takie informacje, jeśli nie jesteś właścicielem takich ofert. Powiedz mi do czego chciałbyś użyć takiej metody?

**Comment by robsonek** [comment]
Do powiadomienia klienta czy wygrał licytacje w aplikacji składającej automatycznie oferty w aukcjach. Do wyliczenia kiedy oferta ma być złożona (np. 3 sekundy przed końcem aukcji)

**Comment by PawelTaberski** [comment]
Rozumiem, przekazałem sugestię o wdrożeniu takiego zasobu.
