### ISSUE TITLE
Unable to communicate securely with peer: requested domain name does not match the server's certificate.

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2366]
Przy wywołaniu Api Allegro otrzymuję z curla komunikat: "Unable to communicate securely with peer: requested domain name does not match the server's certificate."
Kiedyś pisałem o tym błędzie, nie występował zbyt często i "zostawiłem" temat.
Jednak przez weekend miałem kilka tysięcy wystąpień i chciałbym się za to zabrać.
Nie znam się na sieci i nie chcę się znać ;)
moje pytanie:
Jeżeli dobrze rozumiem komunikat to otrzymuję certyfikat od serwera, następnie odwołuje się do tego serwera i okazuje się, że nazwa domeny z certyfikatu nie pasuje do nazwy domeny serwera. Czy dobrze rozumiem? Jeżeli tak to dlaczego dajecie zły certyfikat :) jeżeli źle rozumiem to co z tym zrobić? Możecie też napisać, że to jest po stronie mojego serwera, wtedy uderzę do adminów od dostawcy.

Pozdrawiam, KF

**Comment by PawelTaberski** [comment]
Podeślij proszę jeśli masz:
- pełnego cURL-a wraz z trace-id
- certyfikat jeśli go otrzymałeś
