### ISSUE TITLE
Problem z pobraniem danych oferty https://api.allegro.pl/sale/offers/

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2368]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Pobranie danych oferty trwa baaardzo dlugo, czasem konczy sie TimeOut'em.
przykładowy nr oferty: "7411303958"

przykładowy `response:`
`{
  "errors": [
    {
      "code": "ServiceTimeoutException",
      "message": "An error occurred",
      "details": null,
      "path": null,
      "userMessage": "Execution of the request timed-out. Try again."
    }
  ]
}`

**Comment by PawelTaberski** [comment]
Przetestowałem na powyższej ofercie i dostaje responsa w czasie do 60ms, czy problem u Ciebie dalej występuje?

**Comment by anaxagore78** [comment]
W tej chwili działa prawidłowo, zajmuje to milisekundy,
