### ISSUE TITLE
POST  /sale/images/ nie działa

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2369]
Występuje problem: 
 - [X ] z zasobem REST API

Próba uploadu zdjęcia kończy się błędem od kliku godzin , wczesniej wszystko działało:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => INTERNAL_SERVER_ERROR
                    [message] => Internal server error.
                    [details] =>.
                    [path] =>.
                    [userMessage] => Internal server error. Please try again in a few minutes.
                )

        )

)

**Comment by sest** [comment]
U mnie też ServiceTimeoutException od godziny
Execution of the request timed-out. Try again. 
ale w /sale/offers/

**Comment by 11mszot** [comment]
U mnie już ruszyło
