### ISSUE TITLE
seller rating and product rating via any api?

### ISSUE THREAD

**Issue by forest100** [allegro/allegro-api#2370]
How can i get seller rating and product rating via any api? It seems "doShowItemInfoExt" doesn't return such information.
![ratings](https://user-images.githubusercontent.com/51995367/66767538-5988aa80-eeb9-11e9-9ae7-a88bf4f3300f.jpg)

**Comment by PawelTaberski** [comment]
To get that information use [GET /users/{userId}/ratings-summary](https://developer.allegro.pl/documentation/#tag/Public-user-information)

**Comment by forest100** [comment]
Thanks. This way I can get a seller rating. What about product rating?

**Comment by PawelTaberski** [comment]
Currently we don't have such resources, for what purpose you need that data?
