### ISSUE TITLE
modyfikacja jednego wartości jednego parametru

### ISSUE THREAD

**Issue by APICoderPL** [allegro/allegro-api#2371]
udostępniacie zasób:
https://developer.allegro.pl/news/2018-04-19-news_grupowa_edycja_ofert_update/#1

modyfikacja parametrów przedstawiona w dokumentacji działa.
Jednak czy jest możliwe zmodyfikowanie wartości z sekcji **parameters**. Czy muszę całą ofertę przesłać od nowa?

W dokumentacji:
https://developer.allegro.pl/documentation/#tag/Batch-offer-modification
Też nic nie ma na ten temat, a potrzebujemy zmienić hurtowo tylko i wyłącznie wartość jednego parametru.

jak dodam sekcję parameters i chcę podać jego wartość to dostaję:
{"errors":[{"code":"VALIDATION_ERROR","message":"modification should contain exactly 1 element","details":"Invalid value: ModificationDto[additionalServicesGroup=null, afterSalesServiceConditions=null, delivery=null, promotion=null, sizeTable=null, payments=null, publication=null]","path":"modification","userMessage":"modification should contain exactly 1 element"}]}

a przesłałem:
{"modification":{"parameters":[{"id":"215858","rangeValue":null,"values":["WWWW"],"valuesIds":null}]},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"ukryłem id oferty"}]}]}

**Comment by MaciejFrackowiak** [comment]
Nie, ten zasób nie zmieni wartości parametrów. Musisz przesłać całą ofertę ze zmienioną wartością parametru. Warto spojrzeć do [naszego poradnika](https://developer.allegro.pl/my_offers/).

**Comment by jmarek-pl** [comment]
Standard JSON rozróżnia przypadek kiedy pola nie ma, a kiedy ma wartość null. Także powinna być możliwość modyfikacji tylko niektórych pól oferty poprzez nie zawarcie ich w ładunku zapytania.
Istnieje też inny problem, jeśli korzystać się z klas (statyczne typowanie), a nie ze zmiennych dynamicznych (C#/.NET) to pola, które nie są w klasie są ignorowane i do odpowiedzi nie trafią. Jeśli Allegro coś zmieni to nigdy nie trafi to do zapytania dopóki nie zmodyfikuję programu. Jedyne rozwiązanie to zmienne dynamiczne lub słowniki, ale w ten sposób ignoruję zalety statycznego typowania. Powinna być wyższa wydajność i kontrola kompilatora.
