### ISSUE TITLE
[REST]: Walidacja - Produktyzacja z automatu - BUG!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#2373]
Jakim cudem przedmioty aktywne i po narzuconej z automatu produktyzacji nie zgłaszają żadnych błędów w polach walidacji, a identyczny obiekt całego przedmiotu wysłany jako Draft - wywala niezgodność kodu EAN dla Produktu i tym samym nie daje się skutecznie opublikować?!?

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przykładowe pełne wywołania do opisanych przypadków wraz z trace-id. Sprawdzimy to. Zaznacz, że dane są potrzebne do zgłoszenia numer 2373 na GitHub-ie.

**Comment by FromAnyHole** [comment]
8529551729, 8529550934, 8529550858, 8529544658, 8529330483...
Powyższe przykłady dają taki efekt, są po Waszych magicznych zabiegach systemowej "produktyzacji", mają teraz poprawną walidację (pusta tablica [validation][errors]), a kopia całego obiektu przedmiotu do nowego Draftu - dopiero wtedy sypie błędem walidacji. Sami to sprawdźcie...

**Comment by FromAnyHole** [comment]
Dobra, dobra... To były problemy mniej więcej sprzed tygodnia, a w między czasie coś przy tym grzebiecie i klient zeznaje, że przed kolejnym przypisaniem do Produktu z automatu, teraz jest już przesyłane powiadomienie i konieczność akceptacji zestawu przedmiotów do tej Waszej "produktyzacji"...

**Comment by PrzemyslawLukanowski** [comment]
Proszę o zgłaszanie podobnych problemów w momencie, kiedy występuje błąd.
