### ISSUE TITLE
Czy metoda doGetSiteJournal w starym webapi przestała od wczoraj działać ?

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2374]
Czy metoda doGetSiteJournal w starym webapi przestała od wczoraj działać ?
Przestała mi to działać a czas wyłączenia miałbyć dopiero w styczniu 2020 o ile sie dobrze orientuje
`$soap->__soapCall('doGetSiteJournal',$params)`

**Comment by PawelTaberski** [comment]
Sprawdziłem i wydaje się, że metoda działa poprawnie, a jaki respons otrzymujesz?

**Comment by jasiek07** [comment]
`SoapFault Object ( [message:protected] => [string:Exception:private] => [code:protected] => 0 [file:protected] => /xxx.php [line:protected] => 611 [trace:Exception:private] => Array ( [0] => Array ( [file] => /xxx.php [line] => 611 [function] => __soapCall [class] => SoapClient [type] => -> [args] => Array ( [0] => doGetSiteJournal [1] => Array ( [session-handle] => xxx [startingPoint] => 43211510932 ) ) ) [1] => Array ( [file] => /xxx.php [line] => 17 [function] => checkEmail [class] => xxx [type] => :: [args] => Array ( [0] => 26 ) ) ) [previous:Exception:private] => [faultstring] => [faultcode] => **Server [faultcodens] => http://schemas.xmlsoap.org/soap/envelope/ [faultactor] => Invalid parameters has been passed to 'doGetSiteJournal' operation - Value in field info-type (int) is incorrect** ) `

**Comment by PawelTaberski** [comment]
@jasiek07  Rozumiem, rzeczywiście w tym wypadku jest jakiś problem. Zespół już pracuje nad jego usunięciem.

**Comment by jasiek07** [comment]
To jeszcze Pani Pawle jakby Pan mógł napisać do kiedy ta fukcja faktycznie będzie miało prawo działać , czy to będzie styczeń 2020 ?

**Comment by PawelTaberski** [comment]
Metoda doGetSiteJournal powinna zostać wyłączona w lutym 2020. Więcej na temat naszych planów znajdziesz w [harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by jasiek07** [comment]
Ok to proszę o informacje jak błąd zostanie usunięty

**Comment by jasiek07** [comment]
I ile to może potrwać ?

**Comment by PawelTaberski** [comment]
@jasiek07 Problem nie powinien już występować, dodatkowo przejdź proszę na najnowszego wsdl-a
