### ISSUE TITLE
HTTP/2 stream 0 was not closed cleanly

### ISSUE THREAD

**Issue by dchlodnicki** [allegro/allegro-api#2375]
Występuje problem:
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Request method** 
`PUT`

**URL** 
`https://api.allegro.pl.allegrosandbox.pl/offers/6206649877/change-price-commands/tajne-UUID`

**JSON** 
`{"input":{"buyNowPrice":{"amount":"200.00","currency":"PLN"}},"id":"tajne-UUID"}`

**Response**
`false`

**cURL error**
`HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)`

**cURL error code**
`92`

Podczas próby wysłania jakiegokolwiek zapytania metodą PUT do API dostaję wyżej wymieniony błąd.

**Comment by PawelTaberski** [comment]
Przetestowałem i wydaje się, że metoda działa poprawnie. Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego requesta i responsa wraz z trace-id. Sprawdzimy to. W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 2375 na GitHub-ie.

**Comment by dchlodnicki** [comment]
Problem polegał w błędnym ustawieniu nagłówka. Ustawiałem za pomocą:
`curl_setopt($ch, CURLOPT_PUT, true)`

Przez co cURL oczekiwał, że chce dostarczyć pliki.

Pomogła zmiana na:
`curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT')`
