### ISSUE TITLE
attachments brak w dokumentacji PUT /sale/offers/{offerId} oraz POST /sale/offers

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2376]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Brak w dokumentacji. Ktoś zapomniał. w poradniku jest ale nie w dokumentacji i tak naprawdę nie wiadomo ile i jakich tych załączników można podpiąć ...

**Comment by PawelTaberski** [comment]
Zarówno w dokumentacji jak i poradniku znajduje się taka informacja, przykładowo w [dokumentacji](https://developer.allegro.pl/documentation/#operation/createOfferAttachmentUsingPOST):

![image](https://user-images.githubusercontent.com/36262735/66891942-9b653e00-efea-11e9-9aed-e9df1a5ea1f5.png)

**Comment by frankii91** [comment]
chodzi o to że w metodach

PUT /sale/offers/{offerId} 
https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT

oraz POST /sale/offers
https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST

w definicjach tych metod nie jest nic wspomniane o attachments  jedynie w poradniku
https://developer.allegro.pl/sale/#attachments

Teraz jaśniej ?

**Comment by PawelTaberski** [comment]
Teraz rozumiem, dzięki :-)
Zgłosiłem prośbę o uzupełnienie tych informacji.
