### ISSUE TITLE
Zdjęcia kilka pytań

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2377]
Nigdzie nie mogę znaleźć informacji czy zdjęcia do każdej aukcji **powinny** być wysyłane osobno aby mieć unikalne linki do nich czy mogę zdjęcia wysyłać całkiem niezależnie od aukcji a potem używać w kilku aukcjach ? ( w praktyce można tak robić nawet wykorzystać nie swoje linki/zdjęcia i wystawić swoją aukcje)

Ale jakie jest docelowe założenie ?

Oraz czy jest lub będzie przewidziana opcja aktualizacji przesłanych zdjęć? bez aktualizacji opisu aukcji.

Obecnie aby zaktualizować zdjęcia należy wysłać nowe , pobrać ofertę podmienić linki do zdjęć o popisie oraz galerii i  wysłać na nowo  bardzo dużo pracy ...

lub możliwość sprawdzania np. po md5 czy czymś innym czy dane foto wysłane jest aktualne

**Comment by PrzemyslawLukanowski** [comment]
Przez zasób POST /sale/images nie wiążesz obrazków bezpośrednio z ofertą, a jedynie wysyłasz je na nasz serwer. Możesz zatem wysłać obrazki, które potem sam dowolnie wykorzystasz w swoich ofertach. Dane zdjęcie może być wielokrotnie użyte, ale tylko na koncie, na jakim zostało przesłane. Nie powinieneś używać jednego zdjęcia na wielu kontach.

> czy jest lub będzie przewidziana opcja aktualizacji przesłanych zdjęć? bez aktualizacji opisu aukcji

Na tę chwilę nie planujemy wprowadzenia takiego zasobu. Konieczne jest pobranie całej oferty i wysłanie nowej struktury z zaktualizowanymi zdjęciami. Jaka jest potrzeba takiej funkcjonalności?

**Comment by frankii91** [comment]
Potrzeba w moim przypadku aktualizacji danego zdjęcia (najlepiej bez zmiany linku):
 docelowo aukcje będę się wystawiały w 100%  z automatu wraz z wszystkimi parametrami zdjęciami (generowaniem zdjęć po mojej stronie), opisami i dynamicznym układem opisu.

i np.
Będę miał 1 zdjęcie które będzie odpowiadało za wzornik tkanin możliwy do użycia.
takie zdjęcie potrafi się często zmieniać (po swojej stronie będę wiedział że mam wysłać do allegro nowe foto) a łatwiej było by tylko foto aktualizować (zawartość) a nie całą aukcje.

założenie obecnie do wystawienia 20tys do 50tys aukcji w których w większości będzie 16 zdjęć z czego 6 zdjęć będzie mogło się zmieniać raz w tygodniu-miesiącu. ( wielkość: większości zdjęć to maksymalna jaką dopuszcza allegro)
A dodatkowo przy dodawaniu nowych produktów bardzo często się zdarza że są poprawki w zdjęciach.

Tym samym tych zdjęć do wysłania na samym początku będzie ogrom .... a nie mówiąc o aktualizacji
była by znacznie łatwiejsza.

Zapytam od razu czy  https://upload.allegro.pl/sale/images   ma takie same limity  jak https://api.allegro.pl/.... ? (ilość połączeń itp.)

PS.
1. Przy okazji sam limit ile foto jest przechowywane bez użycia w aukcji jest dość krotki....

**Comment by PrzemyslawLukanowski** [comment]
Dzięki za przekazane informacje. Na tę chwile nie mamy w planach takiej funkcjonalności, ale Twoją potrzebę zgłosiłem jako sugestię do zespołu odpowiedzialnego za rozwój API.

> Zapytam od razu czy https://upload.allegro.pl/sale/images ma takie same limity jak https://api.allegro.pl/.... ? (ilość połączeń itp.)

Tak, limity są takie same, przeczytasz o nich na [naszym portalu](https://developer.allegro.pl/about/#limits).

**Comment by frankii91** [comment]
ok to w takim razie zapytam jeszcze  wysyłanie 20 zdjęć mniej więcej  więcej powinno trwać (wysyłanie jako adres url nie binarnie)
mi wychodzi średnio 26 sekundy na 20 zdjęć i czy to norma czy coś długo ? ( jak długo to mam coś źle zrobione łącze 100mb uploadu po stronie clienta api a server zdjęć 1gb)

**Comment by PrzemyslawLukanowski** [comment]
Wszystko zależy od rozmiaru zdjęcia, prędkości połączenia oraz strony, z której przesyłasz obrazek. Jedno zdjęcie przesyła się średnio w czasie 400ms przy mniejszych obrazkach do 3.00s przy obrazkach większych.

**Comment by frankii91** [comment]
Odnośnie  POST /sale/images 

Sugestia aby dać możliwość przesyłania Dodatkowych informacji które są zwracane w raz z linkiem do zdjęcia
Te dodatkowe informacje nie musiały by być wcale zapisywane u was ale aby były w odpowiedzi

Obecnie wysyłany json ma postać 
{
"url": "string"
}

a odpowiedz
{
"expiresAt": "2019-10-20T19:34:27Z",
"location": "string"
}

i wszystko jest ok gdy wykonujemy synchronicznie 
wysyłamy jeden url i dostajemy nowy  - wiemy do czego jest

Problem robi się gdy wysyłamy asynchronicznie i wysyłamy na raz asynchronicznie więcej niż jedno zdjęcie.
Podczas wysyłania asynchronicznego odpowiedzi też dostajemy asynchronicznie i nagle nie wiemy do którego wysłanego zdjęcia dostaliśmy odpowiedz.

Jedna z opcji to przy podpowiedzi to sprawdzanie parametrów reguesta jaki link był wysłany - trochę to toporne.

Dodatkowo problem większy powstaje przy wysyłaniu np. zdjęć do 100 aukcji po 16 zdjęć do aukcji
a klika zdjęć ma taki sam url bazowy. ( jednak nie chcielibyśmy aby url allegro był jeden dla kliku aukcji - Skomplikowane(nieczytelne) zarządzanie sprawdzaniem przy aktualizacji aukcji jeśli zdjęcie się zmieniło)

Po odpowiedziach z reguesta już nie wywnioskujemy który url ma być do której aukcji.

Sugestia aby Dodać możliwość przesłania dodatkowego parametru tekstowego który byłby zwracany wraz z url zdjęcia allegro oraz aby w odpowiedzi był zawarty również oryginalny url zdjęcia jeśli zdjęcie nie było przesyłane binarnie)

np.
Wysyłamy 

{
"url": "https://domena.pl/link_do_foto.jpg"
"ref":"5rv65b7f7gg7n"   -- nasze id oznaczenie danego zdjęcia  najlepiej pole typu string
}
odpowiedz

{
"expiresAt": "2019-10-20T19:34:27Z",
"location": "link do foto w allegro."
"orgin": "https://domena.pl/link_do_foto.jpg"
"ref":"5rv65b7f7gg7n"
}

Chyba że jest inny sposób na to, to poproszę o jakieś sugestie jak sprawę rozwiązać

**Comment by PrzemyslawLukanowski** [comment]
Przez POST /sale/images nie możesz wysyłać żadnych dodatkowych informacji, dlatego Twoje uwagi przekazuję jako sugestię do działu odpowiedzialnego za rozwój API.
