### ISSUE TITLE
500 Internal Server Error na zasobie "/sale/offers"

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2378]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,
na zasobie /sale/offers pojawia się od dłuższej chwili błąd 500. Wygląda to na błąd u was. Jakaś większa awaria?

Pozdrawiam.

**Comment by neldh** [comment]
400 tez rzucało:

Oct 22nd, 10:14:18 UTC
do
Oct 22nd, 10:40:13 UTC
`GET https://api.allegro.pl/sale/offers?seller.id=XXXXXXX&offset=0&limit=1000` resulted in a `400 Bad Request` response: {"errors":[{"message":"Internal Server Error","userMessage":"Internal Server Error","code":"","details":"","path":""}]}

**Comment by PrzemyslawLukanowski** [comment]
Nie odnotowaliśmy większej liczby błędów tego typu. Czy możesz przesłać nam przykładowe trace-id? Widzę, że w parametrach przekazujesz seller.id, zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) nie wspieramy tego parametru.
