### ISSUE TITLE
About the product description

### ISSUE THREAD

**Issue by CECchina** [allegro/allegro-api#2380]
hello，we have same question about the product. we hope to get your help,thanks!

1)Can we use English to describe product information, because the Chinese sellers are not good at Polish? For example, the color includes black, blue, white, etc.
2)If we use English to describe the product information, can the system automatically translate it into Polish so that the buyer can understand the product advantages more accurately?
3)If the buyer sees the product description in English, is it possible to affect the sales of the product?

**Comment by PrzemyslawLukanowski** [comment]
1) You can list offers only with Polish description, in accordance with our [Allegro Terms and Conditions](https://allegro.pl/regulamin/en/zalacznik-2):

> “Essential content related to a Transaction should be presented as a text in the Polish language. A User may present in their Listing content saved on third-party servers (not belonging to Allegro.pl), however this shall not apply to essential content.”

2) We can’t involve into seller offer description, so we can’t automatically translate it. Here is what our Terms and Conditions says about offer description:

> “A Listing description should be accurate and complete and must not mislead other Users, in particular as regards properties of the Item such as its condition, quality, origin, brand or manufacturer. A Listing description should comply with applicable provisions of law, in particular contain information required by applicable consumer protection regulations. The User shall be fully liable for the content of their Listing, also for any mistakes or inaccuracies therein.”

3) According to point one, description should be in Polish.
