### ISSUE TITLE
Response status code: 403

### ISSUE THREAD

**Issue by shaoran2012** [allegro/allegro-api#2381]
Dzień dobry Dlaczego nie mogę uzyskać szczegółowego opisu przedmiotu. Co powinienem zrobić, aby uniknąć błędów 403?
$getCategoriesUrl = "https://api.allegro.pl/sale/products/7399389650";

**Comment by PrzemyslawLukanowski** [comment]
Odwołujesz się do nieprawidłowego zasobu - [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) związany jest z [produktyzacją ](https://developer.allegro.pl/productization/), zamiast tego użyj [GET sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by shaoran2012** [comment]
Nie działa Zapraszam czyjś produkt. Czy nie mogę wyświetlić innych produktów?
<?php

function getMainCategories(String $token): stdClass
{
    $getCategoriesUrl = "https://api.allegro.pl/sale/offers/7399389650";

    $ch = curl_init($getCategoriesUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $mainCategoriesResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($mainCategoriesResult === false || $resultCode !== 200) {
		echo "Response status code: $resultCode\n";
        exit ("Something went wrong");
    }

    $categoriesList = json_decode($mainCategoriesResult);

    return $categoriesList;
}

function main()
{
    $token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NzEyNjIwNjMsImp0aSI6IjM3Mjk1YmFiLTJlNDYtNGJhMS04NTRkLWE5MzliYWY5MTBiOCIsImNsaWVudF9pZCI6IjAwYjgwOGQyYmRiZTQyYjM5YzAyZTMwOTliODNhNzZkIn0.p4MkzFyo-aJiBgcsEFX2WN4-1kTXSqriTHuEnXCd4UxCgLu7nwomTrH194K81KejK2FthVnJsYZsWseRWCR7d4Exo_gr8NnPtbiVzaZ3Kh9vW33ZCWn_jh_E6Cwt6CwK2zAaLqbrC9S73udLGHsWjHwpWs2fEw0v-CdXGsAJ2c4ynocPBHSawnZpD45XBZVXXhsFnlpsre_o6-XjYK7TbqiovmDyJ1xoSgEojPtE4EmY5mWkrd6w6dRQ-feVP4osHArh7SrcYyGrlFdiGR6ZJbEzpbmjKBzya1TnNYNcaAe035C7qr-VT287LVXQ0iwt5CddZkmAG3U7Hndf9MfXVQ";
    var_dump(getMainCategories($token));
}
main();

**Comment by shaoran2012** [comment]
`<?php

function getMainCategories(String $token): stdClass
{
    $getCategoriesUrl = "https://api.allegro.pl/sale/offers/7399389650";

    $ch = curl_init($getCategoriesUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $mainCategoriesResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($mainCategoriesResult === false || $resultCode !== 200) {
		echo "Response status code: $resultCode\n";
        exit ("Something went wrong");
    }

    $categoriesList = json_decode($mainCategoriesResult);

    return $categoriesList;
}

function main()
{
    $token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NzEyNjIwNjMsImp0aSI6IjM3Mjk1YmFiLTJlNDYtNGJhMS04NTRkLWE5MzliYWY5MTBiOCIsImNsaWVudF9pZCI6IjAwYjgwOGQyYmRiZTQyYjM5YzAyZTMwOTliODNhNzZkIn0.p4MkzFyo-aJiBgcsEFX2WN4-1kTXSqriTHuEnXCd4UxCgLu7nwomTrH194K81KejK2FthVnJsYZsWseRWCR7d4Exo_gr8NnPtbiVzaZ3Kh9vW33ZCWn_jh_E6Cwt6CwK2zAaLqbrC9S73udLGHsWjHwpWs2fEw0v-CdXGsAJ2c4ynocPBHSawnZpD45XBZVXXhsFnlpsre_o6-XjYK7TbqiovmDyJ1xoSgEojPtE4EmY5mWkrd6w6dRQ-feVP4osHArh7SrcYyGrlFdiGR6ZJbEzpbmjKBzya1TnNYNcaAe035C7qr-VT287LVXQ0iwt5CddZkmAG3U7Hndf9MfXVQ";
    var_dump(getMainCategories($token));
}
main();`

**Comment by PrzemyslawLukanowski** [comment]
Jaka jest dokładnie Twoja potrzeba? Jaki rezultat chcesz osiągnąć? Przez zasób [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) pobierzesz konkretną ofertę, jeśli jesteś jej właścicielem - musisz być zautoryzowany jako sprzedawca. W przeciwnym przypadku zakończy się to błędem 403. Zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) odzwierciedla wizualną wyszukiwarkę ofert i umożliwi Ci przeglądanie ofert.

**Comment by shaoran2012** [comment]
Potrzebuję szczegółowego opisu produktu innej osoby. Tworzę witrynę dla firmy, która sprzedaje części samochodowe na Ukrainie. Klient ma firmę zajmującą się sprzedażą części samochodowych w Polsce i chce sprzedawać na Ukrainie. Kupuj na Allegro i sprzedawaj na Ukrainie za pośrednictwem swojej strony internetowej. Strona powie, że produkty z Allegro!

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale takie działanie jest niedozwolone, nie możemy Ci pomóc.

**Comment by shaoran2012** [comment]
W każdym razie dzięki.
