### ISSUE TITLE
Problem z uwierzytelnieniem aplikacji w allegro (RESTAPI) 

### ISSUE THREAD

**Issue by kozoo** [allegro/allegro-api#2382]
WIele kont już uwierzytelnionych. Na dwóch kontach dostajemy  błąd allegro

Numer błędu: b2ee0addb379e8ae

![image](https://user-images.githubusercontent.com/10511850/66912091-2d347180-f012-11e9-9963-270001496971.png)

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że w redirect_uri podajesz taki sam adres powrotu, jaki podałeś przy rejestracji aplikacji. Wówczas zostaniesz przeniesiony na właściwą stronę.

**Comment by jcudzich** [comment]
@PrzemyslawLukanowski Mam ten sam problem. Dodam, że autoryzacja zazwyczaj działa bez problemu, ostatnio dopiero kilku klientów napotkało ten problem.

Czy jest więc możliwe, że jest to zły redirect_uri? Skoro zazwyczaj działa, a wszyscy używają jednej aplikacji?

**Comment by PrzemyslawLukanowski** [comment]
Tak, opisany przypadek najczęściej dotyczy rozbieżności pomiędzy adresem powrotu w redirect_uri a adresem podanym przy rejestracji aplikacji. Zweryfikuj czy są one takie same. Jeżeli problem nadal będzie występować, prześlij za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) pełny request w formacie cURL z dopiskiem github #2382.

**Comment by jcudzich** [comment]
@PrzemyslawLukanowski A co jeśli jest to autoryzacja Device flow, która nie korzysta z redirect_uri?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz dla podanego przykładu przesłać nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) pełen request i response? Dopisz w nim numer zgłoszenia - #2382.
