### ISSUE TITLE
Add a parcel tracking number - OrderLineItemNotFoundException

### ISSUE THREAD

**Issue by myszaq99** [allegro/allegro-api#2383]
Dzień dobry.
Dostaję błąd jak w tytule gdy próbuję dodać numer przesyłki do zamówienia.

{
"errors": [
  {
"code": "OrderLineItemNotFoundException",
"message": "Provided line item not found",
"path": "lineItems"
}
],
}

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Komunikat wskazuje na to, że przekazujesz lineItem.id, które nie zawiera się w checkout-formie, do którego odwołujesz się w POST /order/checkout-forms/**{checkoutFormID}**/shipments. Zweryfikuj, czy przekazujesz prawidłowe dane.

**Comment by myszaq99** [comment]
Moim zdaniem przekazuję ok. Czy mogę podesłać dane, które przekazuję?

**Comment by PrzemyslawLukanowski** [comment]
Owszem, prześlij tutaj pełen request (wraz z trace-id) i response, który otrzymujesz. Pamiętaj o usunięciu tokena.

**Comment by myszaq99** [comment]
URL: https://api.allegro.pl/order/checkout-forms/9acbf792-ef63-11e9-acea-6b7831bd8e68/shipments

HEADER:
authorization: Bearer ...
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json

BODY: {"carrierId":"UPS","waybill":"1ZA180306895136556","carrierName":null,"lineItems":[{"id":"9acbf792-ef63-11e9-acea-6b7831bd8e68"}]}

RESPONSE: {"errors":[{"code":"OrderLineItemNotFoundException","message":"Provided line item not found","path":"lineItems"}]}


Zaznaczam, że wcześniej pobrałem lineItemId za pomocą: https://api.allegro.pl/order/checkout-forms/9acbf792-ef63-11e9-acea-6b7831bd8e68

I nie wiem dlaczego ale checkoutFormId jest dokłądnie takie same jak lineItemId

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, lineItem.id minimalnie róźni się od id checkoutForma: 

9acbf792-ef63-11e9-acea-6b7831bd8e68 - checkoutForm.id,
9acbf790-ef63-11e9-acea-6b7831bd8e68 - lineItem.id.

Jak przekażesz ten numer, problem powinien ustąpić.

**Comment by myszaq99** [comment]
Dziękuję, głupia pomyłka.

**Comment by BartekWroclaw** [comment]
W jaki sposób na podstawie lineItemId  mogę uzyskać w rest API checkout-forms ID tak by podać je jako parametry zasobu: Add a parcel tracking number?

Obecnie zamówienia są jeszcze zaczytywane przy użyciu web API i nie mam ani checkoutForm id ani event id z zasobu /order/events. Mam dealEventId, dealId.
Da się w jakiś sposób znaleźć powiązanie pomiędzy starym dealEventId a event id z rest api?

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą samego lineItemId nie wyszukasz konkretnego nr zamówienia, ale checkoutForm.id możesz uzyskać następująco:

- za pomocą metody [DoGetPostBuyFormsIds](https://allegro.pl/webapi/documentation.php/show/id,1362#method-output) pobierz formId dla konkretnej oferty,
- użyj mapowania transactionId na paymentId poprzez zasób [GET payments/payment-id-mappings?transactionId={formId}](https://developer.allegro.pl/documentation/#operation/findMapping),
- w odpowiedzi otrzymasz payment.id, które dalej przekaż jako parametr zasobu [GET order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)?payment.id={zmapowany numer płatności}
- w odpowiedzi otrzymasz interesujący Cię checkoutForm z konkretnym id, który możesz wykorzystać w POST /order/checkout-forms/**{checkoutFormID}**/shipments

> Da się w jakiś sposób znaleźć powiązanie pomiędzy starym dealEventId a event id z rest api?

Nie, możesz jedynie znaleźć powiązanie między dealId a lineItemId za pomocą [mapowania](https://developer.allegro.pl/documentation/#operation/findMapping).
