### ISSUE TITLE
DoGetMyIncomingPaymentsRequest

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2384]
Dziś koło 12:00 ni stąd ni zowąd, zaczęły mi się zaciągać nie zwracane wcześniej przez metodę DoGetMyIncomingPaymentsRequest płatności z 11.10.2019.
między innymi:
1091419885
1091502727
O co może chodzić?

**Comment by PrzemyslawLukanowski** [comment]
W podanych godzinach wysyłaliśmy retransmisje eventów, co mogło wpłynąć na sytuację, o której piszesz.

**Comment by lukada4100** [comment]
To wiemy czemu się pojawiły. A czemu nie były zwracane przez 5 dni od wpłynięcia?

**Comment by lukada4100** [comment]
Dziś podobny przypadek miałem z 3 płatnościami z wieczora 16.10. Nie wiem od kiedy można było je pobrać, ale na pewno nie były zwracane 17:10 o 02:00:00

**Comment by PrzemyslawLukanowski** [comment]
Opisane przez Ciebie przypadki zgłosiłem do odpowiedniego zespołu w celu analizy.
