### ISSUE TITLE
Brak nowych eventów do zamówień w sandbox

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2386]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

Chcę pobrać eventy metodą GET /order/events  ale od jakiegoś czasu nie pojawiają się nowe.
W tym czasie testowałem dopłaty, dokończenie płatności w innych zamówieniach jak i składanie nowego zamówienia. Nic się nie pojawia. Czekam już od kilku godzin.
Dotyczy środowiska testowego.

**Comment by pawelosajda** [comment]
Przed chwilą złożyłem zamówienie i też potwierdzam ten problem

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, zweryfikowałem to - API na sandboxie nie zwraca nowych eventów. Zgłosiłem problem do odpowiedniego zespołu.

**Comment by cieslix** [comment]
podpinam się pod temat, bo też u nas występuje ten problem

**Comment by PrzemyslawLukanowski** [comment]
Zespół pracuje nad rozwiązaniem, poinformuję w tym wątku po usunięciu problemu.

**Comment by PrzemyslawLukanowski** [comment]
Zasób powinien już działać prawidłowo, prośba o weryfikacje.

**Comment by cieslix** [comment]
zamówienia z wczoraj pojawiły się około 08:55:00, dzisiaj jeszcze nie składaliśmy nowych zamówień, także sprawdzimy zaraz czy nowe też się pojawią.

**Comment by cieslix** [comment]
Wszystkie testowe zamówienia wpadły zaraz po złożeniu, także wygląda, że wszystko działa jak należy dziękuję @PrzemyslawLukanowski
