### ISSUE TITLE
Kiedy REST API zamiast doGetItemsInfo?

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2387]
Czy wiadomo już kiedy dokładnie będzie można pobrać opis oferty przez REST API, a nie jak teraz przez doGetItemsInfo?

**Comment by PrzemyslawLukanowski** [comment]
Planujemy wystawić odpowiedni zasób do końca Q4. Więcej informacji znajdziesz w [naszym harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by PrzemyslawLukanowski** [comment]
@crazyhtm Czy możesz nam wskazać potrzebę pobierania opisów ofert?

**Comment by crazyhtm** [comment]
1) w opisach ofert sprzedawcy umieszczają bardzo wiele informacji na temat wystawionego produktu 
np. przy przedmiotach używanych opisują ich stan techniczny i ewentualne wady ( **BARDZO WAŻNE !!!** )

2) moim zdaniem powinien to być oddzielny zasób lub przynajmniej filtr, który umożliwi pobranie tylko opisu (w formie czystego tekstu bez znaczników HTML i inny udziwnień). Bo w doGetItemsInfo jest to dość trudne

3)  cały czas twierdzicie że API ma być odzwierciedleniem strony WWW !!!
 (a nie jest, np. nie można pobrać emaila czy telefonu osoby wystawiającej a na stronie można go zobaczyć)

4) w REST API chyba nie można w ogóle pobrać danych wystawiającego ofertę przynajmniej na razie (tak a propos odzwieciedlenia strony WWW)

4) **CZY MACIE MOŻE ZAMIAR ZLIKWIDOWAĆ ALBO UTRUDNIĆ MOŻLIWOŚĆ POBIERANIA OPISU ???**

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę działamy zgodnie z [naszym harmonogramem](https://developer.allegro.pl/schedule/). Czy możesz doprecyzować konkretną potrzebę? Do jakiego typu zadań potrzebujesz tę funkcjonalność?
