### ISSUE TITLE
GET /order/checkout-forms - pole payment.type

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2389]
Pole `payment.type` może przyjmować 3 wartości `"CASH_ON_DELIVERY" "WIRE_TRANSFER" "ONLINE"`. Czy typ `WIRE_TRANSFER` działa w taki sam sposób jak` ONLINE` i pojawia się data zapłaty w polu `payment.finishedAt` i ile klient zapłacił `payment.paidAmount.amount`. Czy w tym przypadku samemu trzeba weryfikować czy klient zapłacił ?

**Comment by MaciejFrackowiak** [comment]
Wire_transfer to przelew poza Allegro Finanse. Tym samym status wpłaty wymaga Twojego sprawdzenia, nie ma tu automatu.

**Comment by anaxagore78** [comment]
Czy w dalszym ciagu dla zamowien opłaconych przez 'Wire_transfer' nie ma mozliwosci pobrania danych adresowych kupujacego? Status pozostaje 'FILLED_IN', czyli musimy obsluzyc je po swojej stronie, ale czy po dane adresowe klienta trzeba sie z nim kontaktowac mailowo/telefonicznie?

**Comment by MaciejFrackowiak** [comment]
De facto nie ma już płatności poza Allegro poprzez przelew bankowy dostępnej w samym Allegro, dlatego status ten można praktycznie traktować jako historyczny.

**Comment by anaxagore78** [comment]
Niby tak, ale wciaz zdarzaja sie klienci, ktorym nie powiedzie sie platnosc przez Allegro i chca zapłacić zwykłym przelewem. Moze to jest promil ilosci dziennych transakcji , ale wciaz sie zdarzaja..

**Comment by MaciejFrackowiak** [comment]
Oczywiście - tylko w formularzu pozakupowym tej opcji już nie wybiorą, zatem nie pojawi się ona w API.

**Comment by anaxagore78** [comment]
OK, nie bedzie Wire_transfer, ale bedzie SplitPayment i tu tez nie bedzie mozna pobrac danych klienta z formularza o statusie 'FILLED_IN' ?

**Comment by SebastianOzdoba** [comment]
I dobrze ma wypełnić FOD. 
Osobiście uważam, że to bardzo dobry kierunek w restAPI, dane mają być tylko w jednym miejscu na zamówieniu, tylko na READY_FOR_PROCESSING.

**Comment by anaxagore78** [comment]
> I dobrze ma wypełnić FOD.
Status transakcji  'FILLED_IN'  oznacza własnie wypełniony FOD,

**Comment by SebastianOzdoba** [comment]
Wypełniony FOD to także pełna informacja o płatności, zatem jak nie opłacił nie ma READY i nie ma też danych, sytuacja jest czysta i klarowna. Jak komuś się nie udało, może przejść ponownie formularz
W przypadku SplitPayment, zakłądam że dostaniemy READY FOR bo płatności obędzie się poza PayU

**Comment by MaciejFrackowiak** [comment]
@anaxagore78 @SebastianOzdoba Tak, ostateczny status zamówienia to READY_FOR_PROCESSING - pojawi się od razu po poprawnym wypełnieniu formularza pozakupowego.

**Comment by anaxagore78** [comment]
> Wypełniony FOD to także pełna informacja o płatności, zatem jak nie opłacił nie ma READY i nie ma też danych, sytuacja jest czysta i klarowna. Jak komuś się nie udało, może przejść ponownie formularz
> W przypadku SplitPayment, zakłądam że dostaniemy READY FOR bo płatności obędzie się poza PayU
Sprzedajesz czy tylko tworzysz aplikacje?
W moim przypadku   tylko z ostatniego tygodnia mam 37 transakcji( a teraz to jest 'sezon ogórkowy'), w ktorych cos nie tak poszło z płatnością przez Allegro, transakcje maja status FILLED_IN, dzwonią tacy Janusze i mówią, że chca zapłacic zwykłym przelewem (albo zeby im wyslac za pobraniem), bo nie wiedzą jak wrócić i wypełnić FOD, czasami nie wiedzą co to jest nick na Allegro, są  i tacy co nie wiedzą jaki numer telefonu mają przypisany do konta. Chwilowo da sie to obejsc  pobierajac  dane z starego WebApi, ale po wygaszeniu tej metody w (bodajze) styczniu,  nie wyobrazam sobie zeby nasz  pracownik po kazdym takim telefonie/mailu musiał od nowa przyjmowac dane adresowe od klienta.
