### ISSUE TITLE
Zaimplementujcie głębszy i bardziej szczegółowy backtrace błędów API

### ISSUE THREAD

**Issue by Masterboreq** [allegro/allegro-api#239]
[pytanie]
Czy metoda doCheckNewAuctionExt() nie mogłaby zwracać numerów FID i/lub niepoprawnych wartości przekazanych w strukturze aukcji? Przydałoby się.
Od 4 dni próbuję zmusić API, aby wystawiło mi nową aukcję na podstawie danych istniejącej i trwającej aukcji. Aukcja docelowa pochodzi z innego konta, którego zamknięcie już zaplanowano. Pisałem o tym przypadku w #229. API wciąż zwraca błędy, z których jednak nic nie wynika. Taki wyżej wspomniany "backtrace" aż do poziomu FID-ów szalenie usprawniłby debugowanie.

**TEST**
I tak, mamy stan następujący i jego założenia:
Kategoria nr: 254581
Liczba obowiązkowych FID-ów dla tej kategorii: 8 szt. (FID-y: 1, 2, 4, 9, 11, 24*, 32, 32608)
*) FID 24: Stary opis nie będzie już akceptowany, jak to opisano #233 (w momencie pisania tego zgłoszenia jeszcze jest; nie przesłanie FID 24 lub przesłanie pustej treści w 'fvalueString' nie powoduje błędu).
Dane aukcji poprawnie sformatowane w odpowiednich polach.

**Wynik - wariant 1**
Przy przesłaniu **tylko** obowiązkowych FID-ów: ERR_OBLIGATORY_ATTRIB_NOT_SET.

**Wynik - wariant 2**
Przy przesłaniu wszystkich obowiązkowych FID-ów **jak również** 44 i 45 (odpowiednio "Przesyłka kurierska (pierwsza sztuka)" i "Przesyłka kurierska pobraniowa (pierwsza sztuka)": ERR_POSTAGE_OPTIONS_VALUES_INCORRECT

[Dokumentacja metody doCheckNewAuctionExt](https://allegro.pl/webapi/documentation.php/show/id,41#method-error-codes) mówi, że dla aukcji muszą istnieć wartości opisujące dostawę w następujących wariantach:
 - pierwsza sztuka (jeden z FID-ów z następujących zakresów: 36-113; wszystkie oznaczone jako _nieobowiązkowe_), kolejna sztuka (FID-y: 136-213), ilość w paczce (FID-y: 236-313),
 - lub _jedynie_ dla pierwszej sztuki.

Przy dowolnym wariancie przekazanych danych; tj.: po jednym z fidów dla pierwszej sztuki, kolejnej szt. i ilości w paczce LUB tylko pierwszej sztuki, API nada zwraca ERR_POSTAGE_OPTIONS_VALUES_INCORRECT.

**Wynik - wariant "na Janka, a nuż się uda?"**
Dopiero gdy wysłałem dane o przesyłce w następujących FID-ach: 44, 45, 63-80, 144, 145, 163-180, 244, 245, 263-280, API przyjęło aukcję do sprawdzenia i uznało ją za poprawną! Problem w tym, że dane w FID-ach 63-80, 163-180 i 263-280 są... zmyślone! Nie było ich bowiem w oryginalnej strukturze źródłowej aukcji! **To jest właśnie dla mnie poważny problem, który dyskwalifikuje całą włożoną w projekt pracę!**

Dziś już dałem sobie spokój. Granie w zgaduj-zgadula z API to dość wyczerpujące zajęcie, a zarabiać trzeba. Nie chcę mówić, że zachowanie API w tym przypadku jest wynikiem błędu, bo może to mi brakuje doświadczenia. Ale fakt faktem, dokumentacja metody doGetSellFormFieldsForCategory() mówi swoje, a doCheckNewAuctionExt() swoje i w przypadku obligatoryjności pól się to nie pokrywa. I na jakiego diabła mam wypełniać pola od 63-80, gdy nie chcę wysyłać przedmiotu za granicę?

Jeśli ktoś wie, jak ominąć podawanie danych z sufitu, jak to opisano w wariancie "na Janka...", to proszę o pomoc. Adminów API Allegro proszę, aby może też się przyjrzeli temu, co metoda doCheckNewAuctionExt() wyprawia gdy przesyła się tylko obowiązkowe (wg dokumentacji!) pola.

**Comment by PawelTaberski** [comment]
Metoda doCheckNewAuctionExt, nie sprawdza poprawności przesyłanej oferty, zgodnie z dokumentacją:
"Metoda pozwala na sprawdzenie ogólnych oraz szczegółowych kosztów związanych z wystawieniem oferty przed jej faktycznym wystawieniem."
Parametry, jak i opis jest walidowany przy metodzie [doNewAuctionExt](https://allegro.pl/webapi/documentation.php/show/id,113).
Odnośnie wysyłek przez Allegro WebAPI zawsze musisz przesyłać dla każdej jednej metody wysyłki 3 fidy np. 45; 145 i 245.
Odnośnie wystawiania ofert zalecam przejście na REST API, możesz wtedy m.in. przypisywać do ofert cenniki wysyłek. Więcej na ten temat [tutaj](https://developer.allegro.pl/sale/).

**Comment by Masterboreq** [comment]
Dzięki za odpowiedź.
Myślę, że jeśli już doCheckNewAuctionExt() potrafi wyrzucać takie same błędy co metoda doNewAuctionExt(), to chyba warto, aby komunikaty błędów były cokolwiek informatywne. To takie spostrzeżenie na przyszłość.
Jeśli admini Allegro API macie coś jeszcze w tym wątku do dodania, poczekam kilka dni, potem temat zamykam.
