### ISSUE TITLE
Dodanie informacji do zasobu GET /me

### ISSUE THREAD

**Issue by kajko-pl** [allegro/allegro-api#2391]
:bulb: **Sugestia**

Dzień dobry,

W zasobie GET /me brakuje informacji o e-mailu użytkownika oraz NIPie w przypadku kont firmowych.

Mamy w naszym serwisie opcję do logowania / rejestracji za pomocą konta Allegro. Aktualnie wykorzystujemy metodę "doGetMyData" z WebAPI, która zwraca to czego potrzebujemy.  Maila używamy do sprawdzenia czy w naszej bazie istnieje dany użytkownik, aby utworzyć odpowiednie powiązanie lub zarejestrować nowe konto. W przypadku ścieżki z rejestracją i kont firmowych, NIP służy nam do weryfikacji podmiotu i pobrania podstawowych informacji za pośrednictwem API GUS.

Czy jest szansa na dodanie tych informacji do zasobu GET /me? Chcielibyśmy przejść na RESTa nie zabierając przy tym naszym użytkownikom funkcjonalności cieszącej się sporą popularnością.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za szczegółowe przedstawienie potrzeby, podobne sugestie pojawiły się już w wątkach #2355 oraz #2316. Przekazuję Twoje zgłoszenie do działu odpowiedzialnego za rozwój API. W przypadku wdrożenie tych danych, poinformujemy o tym we właściwym komunikacie.

**Comment by neldh** [comment]
Odkopię trochę temat. Czy planowane jest dodanie chociażby emaila do tej końcowki? Bez tego, podobnie jak napisal @kajko-pl, także nie jesteśmy w stanie podtrzymać działania funkcji "zarejestruj przez allegro", a doGetMyData ma wygasnąć już w marcu...

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę cały czas zbieramy Wasze sugestie. Jeżeli zdecydujemy się dodać takie dane, poinformuję o tym.

**Comment by kajko-pl** [comment]
Dzień dobry,

Czy w tej kwestii została już podjęta jakaś decyzja? Od mojego pytania minęły już ponad 3 miesiące, a tutaj nadal brak konkretów.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie. Zbieramy wszystkie zgłoszenia na ten temat, zapisujemy potrzeby i bierzemy pod uwagę w kwestii dalszego rozwoju API. Jeśli zdecydujemy się na wdrożenie, poinformujemy o tym w odpowiednim komunikacie.

**Comment by baambaam** [comment]
@PrzemyslawLukanowski jest szansa, że email w GET /me pojawi się przed wyłączeniem `doGetMyData` (koniec marca)?

**Comment by baambaam** [comment]
@PrzemyslawLukanowski jest szansa, że email pojawi się w GET /me przed usunięciem metody `doGetMyData` (koniec marca)?

**Comment by PrzemyslawLukanowski** [comment]
@baambaam Jeżeli nie udostępnimy maila do tego czasu, wydłużymy odpowiednio czas wygaszenia metody doGetMyData.

**Comment by PrzemyslawLukanowski** [comment]
[Dodaliśmy informację ](https://developer.allegro.pl/news/#email-and-address-in-/me)o mailu i NIP w GET /me.
