### ISSUE TITLE
Inpost smart

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2392]
Takie pytanie:
1. Jeśli klient kupuje przedmiot z darmową wysyłką na inpost i jest to klient ze smartem, to czy w checkout formie smart będzie na true, czy na false?

2. Jeśli na true, to czy istnieje jakaś możliwość rozróżnienia tej darmowej wysyłki?

3. Jeśli nie istnieje, to czy będzie jakiś problem w tym, że w takiej sytuacji wyślemy paczkę na Inpost przez usługę smart zamiast courier/locker, zanim jeszcze uruchomicie te nowe rozliczenia smart dla sprzedawcy?

Chodzi mi o taką sytuacje:
System musi po czymś rozpoznać, z której usługi ma skorzystać.
Do tej pory cały inpost leci na courier/locker.
W momencie przejścia na rozliczanie nas ze smartów po nowemu część będzie lecieć usługą smart
Jeśli puszczę w ruch aplikację, która rozpozna smarta na podstawie tego, że w checkout form jest flaga smart i zerowa cena wysyłki i wtedy paczka ma lecieć nową usługą inpost smart, a wy jeszcze sprzedawcy nie przepniecie na rozliczenia po nowemu, to czy to się nie wysypie w przypadku darmowej wysyłki na inpost (w sensie czy się nie obrazicie wy lub inpost na sprzedawcę)?

No chyba że wysyłanie przez usługę inpost_smart bez sprzedawcy przełączonego na nowe rozliczenia nie jest żadnym problemem?

**Comment by PawelTaberski** [comment]
Nie wiem, czy dobrze rozumiem Twoje pytanie. Informacje, czy user korzysta ze smarta znajdziesz w checkout formie. Sprawdź proszę [nasz poradnik](https://developer.allegro.pl/orders/#04):
        "smart": false                                      -- przyjmuje dwie wartości: 
                                                            true (kupujący skorzystał z opcji
                                                            smart), false (kupujący nie skorzystał 
                                                            z opcji smart)
Znajduje się tam również informacja o tym jaki sposób dostawy wybrał użytkownik:
        "method": {
            "id": "85c3ad2f-4ec1-446c-866e-63473ed10e26",   -- identyfikator metody dostawy
            "name": "Allegro Kurier24 InPost"               -- nazwa metody dostawy
        },

**Comment by neldh** [comment]
To wiem.
Może trochę zamotałem.

Chodzi mi o moment przepięcia na nowe rozliczenia.
W tej chwili otrzymuję flagę smart, ale cena w cost.amount jest podana, bo rozliczenie z inpostem odbywa się po staremu.
Od 1 listopada rozumiem, że dalej bede dostawał flagę smart na true, ale cena będzie wynosić 0, ponieważ to wy rozliczacie się z inpostem.
Niektórych sprzedawców przepinacie na to wcześniej.
Powiedzmy w takim razie, że w momencie jak przepinacie jakiegoś sprzedawcę, ktorego obsluguję, mam takie transakcje:
| SMART | INPOST | COST.AMOUNT |
|TAK|TAK|8.00|
|TAK|TAK|18.00|
|TAK|TAK|21.00|
{włączacie nowe rozliczenia na sprzedawcy}
|TAK|TAK|0.00|
|TAK|TAK|0.00|
...

Jeśli skorzystam z uwarunkowania, że jeśli COST.AMOUNT = 0.0  (oprócz tego że to inpost i smart) i po tym rozpoznam, że mam na inpost wbijać na usługę inpost_locker_allegro, zamiast jak do tej pory inpost_locker_standard (https://docs.inpost24.com/pages/viewpage.action?pageId=983195), to pozostaje mi problem z darmowymi wysyłkami. Może się bowiem zdarzyć tak:

| SMART | INPOST | COST.AMOUNT |
|TAK|TAK|8.00|
|TAK|TAK|18.00|
|TAK|TAK|21.00|
|TAK|TAK|0.00| //darmowa wysyłka przed przełęczeniem się na nowe rozliczenia
{włączacie nowe rozliczenia na sprzedawcy}
|TAK|TAK|0.00|
|TAK|TAK|0.00|
...

W tym wypadku, przy takim rozpoznawaniu poprawnej usługi inpost, w 4 transakcji zostanie ustawione inpost_locker_allegro zamiast inpost_locker_standard

No i nie wiem na ile wam to przeszkadza?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten temat, wrócę z odpowiedzią.

**Comment by neldh** [comment]
Jest szansa na odpowiedz w miare szybko?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten temat, prośba o cierpliwość. Wrócę z odpowiedzią po ustaleniu konkretnych informacji.

**Comment by neldh** [comment]
Przypominam się tylko

**Comment by PrzemyslawLukanowski** [comment]
@neldh Możesz spokojnie zamawiać wszystkie przesyłki jako inpost_locker_allegro.

**Comment by neldh** [comment]
rozumiem. Dziękuję

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski czy coś się zmieniło w temacie
Inpost zwraca nam błędy dla użytkownika Smart z komunikatem że jest nowy typ: inpost_locker_allegro_smart, w dokumentacji ani słowa (inpostu)
Może Wy coś wiecie :)?
@neldh

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie posiadamy wiedzy na ten temat. W tej sytuacji musisz poczekać na kontakt ze strony Inpost.
