### ISSUE TITLE
StartingAt cannot be changed. (HTTP ERROR 422) StartingAt cannot be changed.

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#2393]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

TraceID: 6cbfca7a872c8a3d

Przy wystawianiu niektórych ofert (nie jestem w stanie powiedzieć czym się one różnia), dostaję response: 
StartingAt cannot be changed. (HTTP ERROR 422) StartingAt cannot be changed.

Mimo, że, zgodnie z dokumentacją, StartingAT ustawiam na NULL. Zarówno przy samym tworzeniu 
drafta: 
```
  'publication' => 
  array (
    'startingAt' => NULL,
  ),
```

jak i potem przy jego aktywacji w polu scheduledFor.

Dlaczego niektóre oferty na to pozwalają, a niektóre nie? Jak temu zaradzić?

**Comment by PrzemyslawLukanowski** [comment]
Przy pobraniu tej oferty w polu startingAt widnieje konkretna wartość "2019-10-07T06:57:00.000Z", dlatego PUT zwraca informacje o błędzie. Prześlij taką samą wartość w tym polu, jeśli wykonujesz zmiany poprzez PUT /sale/offers/{offerID}}.
