### ISSUE TITLE
GET /pricing/offer-quotes - błędy 504

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#2394]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**
Od wczoraj mam sporo błędów 504 na zasobie GET /pricing/offer-quotes.

Przykłady:

Request: GET https://api.allegro.pl/pricing/offer-quotes?offer.id=8485118333
Response body:
```json
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Timeout to the backend service.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}
```
Nagłówki z response:
```json
{"Cache-Control":["no-cache"],"Connection":["close"],"Content-Type":["application/json"],"X-From":["LB"],"X-Reason":["Gateway Time-out"]}
```

Request: GET https://api.allegro.pl/pricing/offer-quotes?offer.id=8334583121
Response body:
```json
{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}
```
Nagłówki:
```json
{"x-ratelimit-remaining":["8988"],"trace-id":["bfc33459b33ec6c0"],"content-type":["application/json; charset=utf-8"],"content-length":["167"],"x-ratelimit-limit":["9000"],"date":["Thu, 17 Oct 2019 11:44:08 GMT"],"x-envoy-upstream-service-time":["5026"],"server":["envoy"]}
```

Kilka trace idów / timestampów:
2019-10-17 14:02:24.840 +02:00 - brak
2019-10-17 13:44:09.012 +02:00 - bfc33459b33ec6c0
2019-10-17 13:42:24.500 +02:00 - brak
2019-10-17 13:41:14.484 +02:00 - 87e0580fba40d089
2019-10-17 13:36:25.166 +02:00 - brak
2019-10-17 13:35:24.824 +02:00 - brak
2019-10-17 12:44:25.230 +02:00 - brak
2019-10-17 12:41:24.453 +02:00 - brak
2019-10-16 15:57:08.929 +02:00 - 429f4c322e106f7f

**Comment by MaciejFrackowiak** [comment]
Zgłoszenie przekazałem do weryfikacji.
