### ISSUE TITLE
Sandbox. Brak usług dodatkowych w zamówieniu

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2395]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

Pobieram dane zamówienia GET order/checkout-forms/592d9601-f0d9-11e9-b009-2d7c82cfc22e
Przy jednym z zamówionych produktów mam usługę dodatkową "Zapakuj na prezent" i w panelu klienta widzę tą opcję. Natomiast REST API nie zwraca tej informacji.
W panelu sprzedawcy też nie ma takiej informacji.
Numer zamówienia: 592d9601-f0d9-11e9-b009-2d7c82cfc22e
Dotyczy sandboxa.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - nie udało mi się powtórzyć tego błędu. Jakiego user id dotyczy to zamówienie?

**Comment by avello** [comment]
Sprzedający UserId: 44065306
Kupujący UserId: 44102185
lineItemId którego dotyczy: c0daaeb1-f0d8-11e9-96b2-0fb846f71f7a

**Comment by PrzemyslawLukanowski** [comment]
Analiza zamówienia wskazuje na to, że jako kupujący nie wybrałeś opcji “zapakuj na prezent”. Zweryfikuj, czy taka informacja widnieje w zamówieniach na froncie:

![Screenshot_24](https://user-images.githubusercontent.com/51473661/67094069-4aed0c80-f1b3-11e9-9f96-a8690501363a.png)

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy taki scenariusz - informacje dodatkowe są zwracane prawidłowo, problem nie powinien już występować. Spróbuj proszę wykonać to jeszcze raz. Jeśli błąd się powtórzy, prześlij nam identyfikatory zamówień sprzed skorzystania z wspólnej płatności.
