### ISSUE TITLE
GET /sale/offer-events - brak informacji o złożonej ofercie

### ISSUE THREAD

**Issue by yo-tech-pl** [allegro/allegro-api#2396]
Witam, 

Mamy kilka typów parametrów które możemy przekazać do GET /sale/offer-events, nas interesuje informacja w których ofertach doszło do licytacji. Przykładowo, cena za jaki  wystawimy przedmiot to 29,90 zł. Użytkownik zalicytuje ten przedmiot za cenę startową licytacji 29,90 zł . Zdarzenie nie zwraca nam informacji o tej ofercie tylko zwróci jak cena będzie inna/wyższa. 
"zmianie ceny w ofercie ("type": "OFFER_PRICE_CHANGED");"
Jak w takim razie mogę poprzez skorzystanie z szybkiej metody dowiedzieć się w jakich ofertach doszło do licytacji. Uważam, że zdarzenie z podaniem typu OFFER_PRICE_CHANGED powinno już zwrócić jeżeli jest złożona pierwsza oferta bo wcześniej przedmiot nie miał żadnej ceny licytacji. 

Pozdrawiam,
Łukasz

Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Opisany przez Ciebie przypadek możesz zweryfikować przez zasób [GET/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - w polu saleInfo.bidderCount otrzymasz wartość 1, nawet jeżeli cena się nie zmieniła.

**Comment by yo-tech-pl** [comment]
Wiem i z tego korzystam, ale widząc że GET /sale/offer-events nie zwraca mi takiej informacji w żadnym z przesłanych parametrów to muszę sprawdzać co chwilę wszystkie 80k aukcji, a tak miałbym odpowiedź z 200-300 aukcjami  i nie obciążał waszych serwerów. Jest to niezbędne do optymalnego rozwiązania i chyba dla nas Wszystkich jest jasne że samo zalicytowanie też jest zdarzeniem, które powinna zwrócić ta metoda. Dlaczego zwraca jak ktoś podbije licytacje, a nie samo zalicytowanie? Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, przekazałem taką sugestię do działu odpowiedzialnego za rozwój API.

**Comment by qls-api** [comment]
Czy będzie wdrożona taka poprawka ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, w najbliższych tygodniach. Poinformujemy o tym w odpowiednim komunikacie.
