### ISSUE TITLE
Automatyczne zamykanie trwających aukcji oraz brak możliwości wznowienia zamkniętych aukcji ze sprzedażą lub bez

### ISSUE THREAD

**Issue by SCDSSO** [allegro/allegro-api#2397]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [X ] inny

:beetle: **Opis**

Od października

Od 3 października zaczęły nam się zamykać aukcje. Posiadamy integrację z IAI shop (skonfigurowaną w lipcu) - technicy odpowiedzieli nam, że problem nie leży po ich stronie. Mamy podpięte kilka kont i na 2 kontach występuje ten problem. 

Mamy również problem ze **wznowieniem aukcji**, wszystkie aukcje co wznawiamy pojawiają się w serwisie allegro z określoną przez nas ilością sztuk - są dostępne, ale po około 15 minutach się automatycznie zamykają.

Przesyłaliśmy screeny z przykładowymi automatycznie zamkniętymi aukcjami oraz ofert, które wznawialiśmy i się zamykały (zgłoszenie nr "06734628").

Jest sporo aukcji automatycznie zamkniętych oraz sporo, które chcemy wznowić ze względu na przyjście towaru dlatego nie wrzucam numeru ofert.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem zgłoszenie do odpowiedniego zespołu w celu analizy, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy to - zmiana na zakończenie jest zlecona komendą przez REST API na kluczu, który należy do usera 5423163.
Prośba o zgłoszenie błędu do autora aplikacji - nie wiemy, w jaki sposób oprogramowanie korzysta z naszych zasobów. Integrator sprawdzi, czy błąd jest po jego stronie - wtedy powinien go naprawić, czy po stronie API Allegro - wtedy może nam go zgłosić i dostarczyć niezbędne informacje, byśmy problem mogli naprawić.

**Comment by SCDSSO** [comment]
W jaki sposób możemy sprawdzić ID tego usera? Oraz o jaką aplikację chodzi dokładnie?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy to na przykładzie oferty 7955016505, ID należy do Państwa integratora.

> Oraz o jaką aplikację chodzi dokładnie?

Aplikację, z której Państwo korzystają do wystawiania ofert, czyli IAI Shop.

**Comment by kfijalko** [comment]
Adres do sprawdzenia do kogo należy konto:
https://allegro.pl/uzytkownik/5423163/oceny

**Comment by SCDSSO** [comment]
Prosimy o sprawdzenie oferty nr: 7128046172, ta oferta którą Państwo sprawdziliście właściwie się zamknęła.

**Comment by PrzemyslawLukanowski** [comment]
Podana oferta została zakończona poprzez przeglądarkę w dniu 07.10.19. Nie widzimy w logach, aby nastąpiła ponowna próba aktywacji. Proszę o doprecyzowanie tej daty.

**Comment by SCDSSO** [comment]
Może inaczej. Oferta nr: 7955016505 - wznowiona 10 pażdziernika i po 15 minutach się zamknęła. Spróbujmy na tej konkretnej ofercie zweryfikować, czemu nam ją zamknęło mimo wznowienia.
A jeżeli chodzi o zakończenie aukcji to np.:
- 8393405811
- 8393412625
- 8393415814
