### ISSUE TITLE
GET /order/checkout-forms - zamówienia archiwalne

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2399]
Czy jest jakaś możliwość aby jednorazowo zwrócić wszystkie zamówienia archiwalne. Bardzo zależy mi na tym. Nawet jakbym otrzymał gotowego JSON-a z takimi zamówieniami to byłoby super.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie ma takiej moliwości, zasób GET order/checkout-forms zwraca zamówienia sprzed ostatnich 180 dni.

**Comment by pietrach** [comment]
A jakbym takie zgłoszenie wysłał to wygenerowalibyście JSON-a z takimi zamówieniami ? To tylko jednorazowa prośba.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie możemy wygenerować JSON-a z zarchiwizowanymi zamówieniami.
