### ISSUE TITLE
Monety allegro

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#24]
Witam,

Czy istnieje możliwość, lub czy jest w planach dodanie obsługi monet allegro? Dokładnie chodzi o dodawanie monet do oferty. Narzędzie, które do tego służy w moim allegro jest fatalne :/

**Comment by MarcinLuczak** [comment]
Na razie nie udostępniamy możliwości zarządzania monetami przez API, ale dziękujemy za sugestię. Przyjrzymy się temu tematowi.
