### ISSUE TITLE
Podany identyfikator nie istnieje.

### ISSUE THREAD

**Issue by gantel86** [allegro/allegro-api#240]
Taki dostaje komunikat przy wystawianiu nowej aukcji. Co on dokładnie oznacza?
O jaki identyfikator chodzi?
Dodam, że taka sama aukcja na innym koncie wystawia się poprawnie.

**Comment by PawelTaberski** [comment]
@gantel86  Jeśli oferta o identycznej strukturze wystawia się poprawnie na innym koncie to najprawdopodobniej chodzi tak jak wyżej opisał to @TimothyKoval o warunki oferty. Sprawdź proszę czy masz poprawnie uzupełnione warunki od danego konta. Możesz je sprawdzić, jakie warunki są przypisane dla danego konta, przy pomocy metod opisanych [tutaj](https://developer.allegro.pl/news/2017-04-05-News_warunki_oferty/).
