### ISSUE TITLE
ERR_INVALID_ACCESS_TOKEN] Nieprawidłowy kod dostępowy

### ISSUE THREAD

**Issue by webdachu** [allegro/allegro-api#2401]
Witam
dla testu próbuje pobrać sesje allegro **doLoginWithAccessToken**, niestety wywala błąd : ERR_INVALID_ACCESS_TOKEN

funkcja getAccessToken() zwraca token więc jest OK, potem jest problem kiedy podstawiam do: 

`$token = getAccessToken();
$client = new SoapClient('http://webapi.allegro.pl/uploader.php?wsdl');
$session = $client->dologinwithaccesstoken($token, 1, 'my api key');`

wyrzuca błąd:  **ERR_INVALID_ACCESS_TOKEN: Nieprawidłowy kod dostępowy**

================ Cały kod poniżej : =============

`try
{

$webapi_key = 'my api key';

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "my api key";
    $clientSecret = "my secret key";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        echo ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

$token = getAccessToken();
$client = new SoapClient('http://webapi.allegro.pl/uploader.php?wsdl');
$session = $client->dologinwithaccesstoken($token, 1, 'my api key');

echo $session['session-handle-part'];

} 
catch(SoapFault $error)
{
echo 'Error ', $error->faultcode, ': ', $error->faultstring, "n";
}`

prosze o pomoc

**Comment by PrzemyslawLukanowski** [comment]
Z językiem PHP niestety nie pomożemy - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Wątek generowania tokenu w PHP przewinął się w poniższych wątkach. Być może wśród nich znajdziesz wskazówki dotyczące Twojego problemu lub któryś z użytkowników forum napotkał podobny problem w przeszłości:

#2306
#708
#226

**Comment by webdachu** [comment]
ok poradziłem sobie, ale mam inny błąd **ERR_INCORRECT_RESULT_SIZE: Niepoprawna wartość rozmiaru zwracanych danych.**  

` $wynik = $client->doGetRefundsList($session['session-handle-part']);
 print_r( $wynik );`

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, jaką wartość przesyłasz w polu resultSize. Zgodnie z [dokumentacją](https://allegro.pl/webapi/documentation.php/show/id,1423) typ przesyłanej wartości to int, liczba powinna być z zakresu 1 - 1000.
