### ISSUE TITLE
Błąd przy zapisie nr listów przewozowych dla zamówień przesyłanych w kilku paczkach

### ISSUE THREAD

**Issue by lkrzysiak** [allegro/allegro-api#2402]
Allegro nie przyjmuje nr listów dla zamówień przesyłanych w wielu paczkach.

Metoda **POST /order/checkout-forms/{id}/shipments** pozwala na zapisanie max 64 znaków do tego przecinki nie są przepuszczane.

Dlatego gdy próbuje zapisać nr listu dla zamówienia przesyłanego w kilku paczkach Allegro tego nie przyjmuje.

np. 
0000183923923U,0000183923924U,0000183923925U,0000183923926U,0000183923927U,0000183923928U,0000183923929U,0000183923930U

**Comment by PatrykBocian** [comment]
Medotą **POST /order/checkout-forms/{checkoutForm.id}/shipments** dodasz jeden numer przesyłki do zamówienia, jeśli chcesz ich dodać więcej musisz wywołać wielokrotnie ten zasób.

Natomiast zasobem **GET/order/checkout-forms/{id}/shipments** pobierzesz wszystkie numery listów jakie dodałeś do konkretnego zamówienia.

Więcej informacji na ten temat znajduje się w naszym poradniku [Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/#addTracking).
