### ISSUE TITLE
import danych do Selly dane do fv oraz do dostawy 

### ISSUE THREAD

**Issue by sfm83** [allegro/allegro-api#2404]
Witam 
od jakiegoś czasu mamy problem z importowaniem danych do naszego systemu Selly. Problem polega na tym, że jeśli Klient kupując na Allegro nie zaznaczy faktury, to dane do fv automatycznie wskakują z danych do dostawy. Natomiast często zdarza się tak, że Kupującym jak ktoś inny, a adres doręczenia jest na inną osobę. I tu pojawia się konflikt, ponieważ my powinniśmy wystawić fv na osobę Kupującą, a  nie osobę, która tylko jest wpisana do odbioru paczki.
Selly twierdzi, że to nie ich wina, ponieważ to Allegro uniemożliwia przesyłanie danych Kupującego do ich programu. 
Proszę o informację, czy rzeczywiście tak jest? A jeśli nie, to  w taki sposób możemy naprawić ten problem?
Dodam tylko, że obecne narzędzie, jakim jest oprogramowanie Selly naraża nas na popełnianie przestępstwa skarbowego, stąd proszę o w miarę możliwości szybką odpowiedź. 

PS. Dziś również zauważyliśmy, że w jednym zamówieniu nie zaimportował się nr NIP do faktury, mimo że Klient wpisał go ręcznie wypełniając FOD Allegro.

**Comment by SebastianOzdoba** [comment]
@sfm83 skontaktuj się z Selly, wszystkie dane są w API Allegro, kupujący to ten który się zalogował i płaci, a dostawa jest w osobnym polu i te dane są zawsze dostępne na zamówieniu w restAPI
Tutaj jest więcej informacji: https://developer.allegro.pl/orders/#04

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniał @SebastianOzdoba, skontaktuj się w tej sprawie z Selly. Przez REST API zwracamy informacje o zamówieniu poprzez zasób GET /order/checkout-forms oraz GET /order/checkout-forms/{id}, więcej informacji znajdziesz w poradniku oraz w dokumentacji. Udostępniamy komplet danych, jednak nie wiemy, w jaki dokładnie sposób zewnętrzna aplikacja wykorzystuje nasze zasoby, dlatego nie jesteśmy w stanie stwierdzić, co dokładnie oznacza uniemożliwienie przesyłania danych. Twórca aplikacji powinien zweryfikować, czy błąd leży po stronie Allegro. Jeśli tak - powinien się z nami skontaktować i dostarczyć komplet danych w celu analizy problemu.
Co do zamówienia z brakującym NIP-em - prześlij proszę nr tego zamówienia, zweryfikujemy to.

**Comment by sfm83** [comment]
Witam, dziękuję za podpowiedzi. 
Nr zamówienia, o który Pan pyta to: 8f5f77d2-f04c-11e9-a050-6704f6b6258c

**Comment by PrzemyslawLukanowski** [comment]
@sfm83 - w naszych logach nie widzę takiego zamówienia. Czy mogę prosić o id usera, którego to dotyczy?

**Comment by sfm83** [comment]
nick Klienta to: slonmloszowa, 
p. Wojciech Siudek z Warszawy

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, zweryfikowałem to - NIP zwracamy prawidłowo w polu company.taxId w zasobie GET /order/checkout-forms/8f5f77d2-f04c-11e9-a050-6704f6b6258c, dlatego również w tym przypadku prośba o kontakt z twórcą oprogramowania.
