### ISSUE TITLE
Produktyzacja - oferty konkretnego produktu

### ISSUE THREAD

**Issue by daqiu-** [allegro/allegro-api#2405]
Hej, czy istnieje możliwość zwrócenia listy ofert dla konkretnego produktu?

**Comment by PatrykBocian** [comment]
Niestety obecnie nie posiadamy takiego zasobu.
Aktualne zasoby znajdziesz w naszej [Dokumentacji](https://developer.allegro.pl/documentation/)

**Comment by daqiu-** [comment]
Rozumiem, dzięki za szybkie info. A planujecie może dodać coś takiego? Jak inaczej podejrzeć moje oferty na tle pozostałych dla tego samego produktu?

**Comment by PatrykBocian** [comment]
Niestety chwilowo nie ma takiej możliwości.
Przekazałem sugestie co do takiej możliwości do działu zajmującego się rozwojem REST API.
