### ISSUE TITLE
Historia operacji billingowych i saldo

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#2407]
A gdzie znajdę wszystkie możliwe type.id?, bo jak na razie nigdzie tego nie ma!? Dajecie nowy zasób i nie potraficie tego poprawnie udokumentować, żałosne!

**Comment by PrzemyslawLukanowski** [comment]
type.id jest powiązany z name.id. Interesującą Cię wartość sprawdzisz za pomocą wywołania GET /billing/billing-entries , którą następnie możesz przekazać jako wartość parametru. Na tę chwilę nie udostępniamy pełnej listy type.id.
