### ISSUE TITLE
sale/offer-publication-commands zwraca zawsze failed

### ISSUE THREAD

**Issue by Atospl** [allegro/allegro-api#2408]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próby aktywowania aukcji wcześniej zapisanych jako szkice kończą się za każdym razem wynikiem:
Success: 0, failed: 100, total: 100
Niezależnie od tego, czy próbuję opublikować 100 czy 5000 aukcji. Jednocześnie ponad 90% spośród tych aukcji MOŻNA aktywować ręcznie na stronie allegro.

Przykładowe GUID komend to:
aaee44ff-1b5e-4e4a-a509-c265e44e44d6
876dd2fc-3314-44f6-b6af-263706262095
4feb41ad-155a-4327-897b-126c5bae8e58
3904e558-7d5a-4146-b17f-265ebf361d99
de3f89fd-54da-468f-b41e-be38d379f5be
079e74de-0836-4fef-a442-6c544e52ca03
20d4617-a700-482f-ad43-61e9219cdad2
4089095f-55a3-4b24-805e-a4aabccf7d8c

Bardzo proszę o naprawę błędu lub wskazanie jego przyczyny

**Comment by PrzemyslawLukanowski** [comment]
Błąd, który otrzymujesz to "You cannot schedule activating an offer in the past.", ponieważ w polu scheduledFor przekazujesz czas, który jest w tej samej minucie, co wychodzi zlecenie na aktywację. W momencie wywołania komendy aktywacji oferty, data zaplanowania jest już w przeszłości. Jeśli chcesz planować wystawianie ofert, musisz wtedy ustawić datę w przyszłości. Jeżeli chcesz wystawić ją teraz, wtedy pole scheduledFor powinno być null.

**Comment by Atospl** [comment]
Dzięki!
