### ISSUE TITLE
Kategorie - typ danych

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#2409]
Cześć,
Jak to jest z typem identyfikatora kategorii? Czy jest to wciąż int czy już dowolny ciąg?
https://developer.allegro.pl/documentation/#tag/Categories-and-parameters
w przykładach wszędzie jest liczba całkowita ale w specyfikacji już jest np.

string Default: "954b95b6-43cf-4104-8354-dea4d9b10ddf"
Kategorie główne nie mają już identyfikatora w formie liczby całkowitej?

Wywraca to trochę nam system oparty na wartościach całkowitych.

**Comment by PatrykBocian** [comment]
Obydwa typy identyfikatorów kategorii są prawidłowe. Jeśli chodzi o problemy związane z państwa systemem opartym na wartościach całkowitych niestety może być konieczny jego update.
