### ISSUE TITLE
Authoryzacja OAuth czasem nie działa

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#241]
Po powrocie klienta z kodem wymaganym do uruchomienia auth/oauth/token czasem dostaje "Bad request". Jeśli odczekam 1-5s i i wywołam ten sam request to automagicznie działa.

**Comment by PawelTaberski** [comment]
Podeślij proszę całego responsa wraz z nagłówkami przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=1436f902-6fd9-420f-9e19-321b684cc8df) (zaznacz w zgłoszeniu, że to na potrzeby zgłoszenia problemu na GitHub-ie) następnie wklej tutaj numer ticketa. Sprawdzimy w czym jest problem.
