### ISSUE TITLE
Nie działają zakupy na sandboxie

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#2411]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Na sandboxie nie przychodzą zamówienia od kupujących, nie ma też eventów w zasobie /orders/events oraz nie przychodzą maile o dokonaniu zakupu. Kupujący widzi swój zakup, sprzedający nie.

**Comment by Onixarts** [comment]
Jak wchodzę w https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-ofert to strona odświeża się co 4s sama.

**Comment by PatrykBocian** [comment]
Zgłosiłem powyższy problem, jak tylko zostanie to naprawione dam znać.

**Comment by yami-five** [comment]
Czy jest możliwe, że ten problem z zamówieniami zostanie dzisiaj rozwiązany?

**Comment by PatrykBocian** [comment]
@yami-five Nie znam dokładnej daty rozwiązania tego problemu.

**Comment by Onixarts** [comment]
Póki co to nie da się zalogować na sandboxa. Nie znacie daty naprawienia problemu ale datę wygaszania API znacie. Jak my mamy się do niej dostosować, skoro przez niedziałający sandbox stoimy z robotą. Daty wygaszania powinny być przesuwane jeśli sandbox nie działa, bo na czym mamy pracować?

**Comment by PatrykBocian** [comment]
@Onixarts W momencie, w którym zgłosiłeś problem, rzeczywiście wystąpiły chwilowe problemy z Sandboxem.
Teraz logowanie działa poprawnie.

**Comment by Onixarts** [comment]
jupi 🎈😔
