### ISSUE TITLE
GET /order/checkout-forms - opóźnienie w dostarczeniu danych

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2412]
Czy mogą zdarzyć się sytuacje, że dane pojawiają się z opóźnieniem ? Tzn. ustawię sobie parametr `lineItems.boughtAt.gte` załóżmy 3 godziny wstecz od daty obecnej a po tych 3 godzinach pojawi się dopiero zamówienie, które zostało złożone z 4h wcześniej ?

**Comment by PrzemyslawLukanowski** [comment]
Takie opóźnienia nie powinny mieć miejsca. 
Gdyby taki problem kiedykolwiek wystąpił, prześlij proszę dokładne dane, a my zweryfikujemy taki przypadek.
