### ISSUE TITLE
Allegro-Inpost "Import danych z aukcji Allegro może trwać do 8h."

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2413]
Do Allegro:
Po dzisiejszych porannych problemach z integracją allegro-inpost otrzymałem od inpostu informację:
"...
Import danych z aukcji Allegro może trwać do 8h.
..."
Dla mnie to jakieś totalne nieporozumienie. Wymagacie od sprzedających szybkości/jakości ....
Czy zdefiniowaliście i rozliczacie jakieś mierniki wobec Inpostu? Czy macie jakieś SLA?

Jeżeli Inpost ma 8 godzin na pobranie danych z Allegro i wydruk etykiety to poproszę żebyście doliczyli to do czasu jaki sprzedawca ma na dodanie numeru listu przewozowego od momentu zakupu/zapłaty.

Z poważaniem,
kfijalko

**Comment by PatrykBocian** [comment]
Rozumiem że ta sytuacja może być problematyczna.
Do każdej takiej sprawy podchodzimy indywidualnie, niestety tutaj problem nie jest po naszej stronie.
Zachęcam do zgłoszenia tego przez nasz formularz kontaktowy.
Dzięki temu rozwiążesz ewentualne problemy wynikające z tej awarii.

**Comment by kfijalko** [comment]
Inpost ruszył, ale odpowiedź konsultanta podniosła mi ciśnienie.

**Comment by lukada4100** [comment]
a daj mi jakiś kontakt do inposta, nigdy nie wiem do kogo uderzać gdy coś tam się wali.

**Comment by kfijalko** [comment]
nikt nie ma takiego kontaktu :) napisałem tiket z formularza na stronie menadżera paczek
