### ISSUE TITLE
Błąd w dokumentacji Images-and-attachments

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2414]
Na stronie: https://developer.allegro.pl/documentation/#tag/Images-and-attachments

Chyba jest tutaj błąd, ponieważ nie jestem w stanie w żaden sposób przesłać poprawnie GIFa. Za każdym razem wyrzuca błąd 415. Jednak w dokumentacji Content-Type "image/gif" widnieje i teoretycznie powinno być możliwe wysłanie GIFa. 

Może ktoś zweryfikować, o co chodzi?

**Comment by PrzemyslawLukanowski** [comment]
Nie wspieramy formatu pliku .gif. Dziękuję za zwrócenie uwagi, w najbliższym czasie poprawimy informację w dokumentacji.

**Comment by frankii91** [comment]
w dokumentacji jest sporo błędów a nawet więcej niż sporo wiec powinna być opatrzona odpowiednim komentarzem że zawiera błędy i jak coś nie działa to bezpośredni klik link do tworzenia tematu na tym forum było by łatwiej :) i większej licznie ludzi chciało by się zgłaszać te błędy ..

**Comment by PrzemyslawLukanowski** [comment]
@frankii91 Jeśli zauważyłeś jakiś błąd, możesz nam go zgłosić. Zweryfikujemy to i odpowiednio poprawimy dokumentację.
