### ISSUE TITLE
GET /sale/offers nie zwraca danych

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2415]
Oferta 8548523378.

 get /sale/offers zwraca o niej informacje

/sale/offers/{offerId} nie zwraca informacji

Na frontendzie podobnie. Nie ma jej na listingu  -  jest pod adresem https://allegro.pl/oferta/...

oferta oczywiście świeża, z 04.10.2019

Żeby było ciekawiej: oferta (licytacja) jest niby zakończona przed czasem "endedBy=USER"  09.10.2019  o 05:25 ale tak naprawdę wpadła do zamówienia postBuyFormId: 1091982510

O tej samej godzinie nastąpiła walidacja innej oferty z tym samym przedmiotem. która pojawiła się jako licytacja z nowym numerem: 8562342044 tego samego dnia wieczorem.

To Wy coś mieszacie czy użytkownik zhakował Wam system?

Szczegóły w formularzu.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy to - GET /sale/offers/{offerId} prawidłowo zwraca ofertę, GET /sale/offers nie zwraca oferty, ponieważ na listingu została oznaczona jako ukryta.
Oferta została zakończona przed czasem przez usera poprzez przeglądarkę.

**Comment by lukada4100** [comment]
Hmm, jeśli została przed czasem zamknięta przez usera na przeglądarce to jakim cudem wisi jako sprzedana  (postBuyFormId 1091982510)?  Szczegóły wysyłam w formularzu.

**Comment by lukada4100** [comment]
Doszło?

**Comment by PrzemyslawLukanowski** [comment]
Zamknięcie przed czasem nie wyklucza sprzedaży. Kupujący złożył ofertę 06.10.19, zamknięcie nastąpiło 09.10.19. Użytkownik zakupił przedmiot, jego oferta była najwyższa w momencie zamknięcia.

**Comment by lukada4100** [comment]
Dzięki. Czyli user namieszał. Nie wiedziałem nawet, że takie tricki są możliwe.
