### ISSUE TITLE
An authorization code must be supplied.

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#2416]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hi,

I am trying to get the access token in order to modify offers in my account via rest api, but I get the error that "An authorization code must be supplied".

Any idea why that happens?

Thank you

**Comment by PatrykBocian** [comment]
Hi, I think you may have a problem with provided query parameter.
Please check “code” parameter, when I wrote “code” uncorrectly, I got the same error as you.

It should look like below:

/auth/oauth/token?grant_type=authorization_code&**code**={code}&redirect_uri={redirect_uri}

Please check this but if that not gonna help you can contact with us from this [contact form.](https://allegro.pl/pomoc/kontakt)
If you do this please send full request in curl format and add a ticket number **#2416**
