### ISSUE TITLE
GET /order/checkout-forms status zamowienia

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2418]
Prosze o weryfikacje formularza 86e2267b-f2ae-11e9-a2e0-815e6a3a9a54,
klient wybrał formę wysyłki kurier pobranie, a status zamowienia to wciaz "FILLED_IN".
Według dokumentacji powinno miec statuc "READY_FOR_PROCESSING".

**Comment by PatrykBocian** [comment]
Jesteśmy w trakcie werfyfikacji zgłoszenia.
Jak się czegoś dowiem wrócę z odpowiedzią.

**Comment by anaxagore78** [comment]
@PatrykBocian czy udało sie czegos dowiedzieć w mojej kwestii?
W ciagu ostatnich 6 miesięcy znalazłem jeszcze jedną taką transakcję - wybrane pobranie, a status zamowienia to wciaz "FILLED_IN".

**Comment by anaxagore78** [comment]
Znalazłem kolejne, numery poniżej:
33915a02-9673-11e9-9484-b3c95c9131b2,
e4a13df1-7b85-11e9-aac1-57c3783d24ed,

**Comment by PatrykBocian** [comment]
Dziękuje, dołączyłem te numery do zgłoszenia.

**Comment by PatrykBocian** [comment]
@anaxagore78  Formularz: 86e2267b-f2ae-11e9-a2e0-815e6a3a9a54 ma już status READY_FOR_PROCESSING. Dla niego problem już nie występuje. Jak otrzymam informacje odnośnie pozostałych formularzy dam znać.
