### ISSUE TITLE
GET https://api.allegro.pl/sale/shipping-rates - przypadki 503

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2419]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Oct 22nd, 19:11:25 UTC
Oct 23rd, 01:04:52 UTC
Oct 23rd, 07:05:39 UTC

GET https://api.allegro.pl/sale/shipping-rates/{UUID}` resulted in a `503 Service Unavailable`

Niestety nie logujemy trace-id, ale może po datach znajdziecie.

**Comment by PatrykBocian** [comment]
Próbowałeś wywołać zasób ponownie czy może problem występuje cały czas?
Przetestowałem to u siebie, nie było żadnych problemów.
Sprawdziłem to też w podanym zakresie i nie widziałem wzmożonej ilości błędów.
Gdyby znów pojawił się podobny problem proszę wyślij nam dokładny timestamp tych zdarzeń a najlepiej trace-id jeśli je otrzymałeś.

**Comment by neldh** [comment]
To były odosobnione przypadki w podanych godzinach. Czasem jest dobrze czasem 503.
Daty 503 z dzisiaj i wczoraj:
Oct 25th, 13:08:44 UTC, 
Oct 25th, 10:25:39 UTC, 
Oct 25th, 08:16:39 UTC,
Oct 25th, 07:01:22 UTC,
Oct 24th, 13:12:57 UTC
Ogólnie wygląda na to, ze problem występuje okolo pólnocy/ w okolicach 7:00

**Comment by PatrykBocian** [comment]
Dziękuje, przekazałem to do odpowiedniego zespołu w celu analizy.
