### ISSUE TITLE
Dodawanie PDF po API

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#242]
Długo wyczekiwana możliwość dodawania PDF'ów do aukcji w końcu zawitała na allegro, niestety jak zwykle połowicznie. Kiedy będziemy mogli uzupełnić aukcje po API? Nie ważne REST czy SOAP.

**Comment by PawelTaberski** [comment]
Mamy to na uwadze, ale nie znam dokładnego terminu. Jeśli będziemy planować wdrożenie takiej funkcji po Allegro API poinformujemy o tym.
