### ISSUE TITLE
refresh_token

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#2421]
.

**Comment by BartekWroclaw** [comment]
Z tego, co potestowałem wynika:
1. Odwołanie do zasobów musi dostać zawsze access_token a nie refresh_token .
2. refresh token zawsze generuje nową parę access_token i refresh_token.
3. Odwołanie do zasobów musi dostać zawsze nowy access_token.
Jak rozumiem access_token jest ważny zawsze maks 12 godzin i to jego muszę użyć zawsze przy odwołaniu do zasobów.
Czyli nie rzadziej niż co 12 godzin powinienem odświeżać access_token za pomocą ostatniego refresh_token przy założeniu, że aplikacja odpytuje api co np. 10 min?

**Comment by hahyes** [comment]
Krótko mówiąc, tak. 
Co do samych czasów, API zwraca również okres ważności wyrażony w timestampie (sekundach) i można z tego skorzystać.

**Comment by PatrykBocian** [comment]
1.Dokładnie tak, każde wywołanie zasobu wymaga podania access tokena.
2.Dzięki refresh tokenowi uzyskasz nową parę - access token + refresh token..
3.Tak, odwołanie do zasobu musi mieć miejsce zawsze przy pomocy bieżącego tokena.
Taki access token jest ważny przez 12 godzin, jest tak jak piszesz - nie rzadziej niż co 12h musisz użyć ostatniego refresh_tokena, aby odświeżyć access_token.

I tak jak wspomina @hahyes  masz dostęp do informacji o czasie ważności tokena dostępowego, podanego w sekundach.

Więcej informacji na temat autoryzacji znajdziesz w tym [poradniku.](https://developer.allegro.pl/auth/#resource)
