### ISSUE TITLE
POST /sale/blacklisted-users Internal Server Error?

### ISSUE THREAD

**Issue by Judasz121** [allegro/allegro-api#2422]
Na wstępie napomne że jestem dość świeży w cURL i REST API

Więc, próboje dodać użytkownika do czarnej listy i wywala mi błąd:

> Response status code: 500 {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

I teraz pytanie jest zasadnicze czy to rzeczywisćie jest wina po stronie serwera czy z moim kodem jest coś nie tak?

     $query = [
		"user" => [
			"login" => "$login"
		],
		"note" => "$note"
	];
	
	$blacklistUrl = "https://api.allegro.pl/sale/blacklisted-users"."?".http_build_query($query);
	$token = getAccessToken($clientId, $clientSecret);

    $ch = curl_init($blacklistUrl);
	
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
		
    $result = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	
	if ($result === false || $resultCode !== 201) {
                echo "Response status code: $resultCode\n";
                echo $result;
                exit;
    }

**Comment by Judasz121** [comment]
A dobra sorry, zapomniałem że w JSONie się wysyła dane.

**Comment by Judasz121** [comment]
Teraz dostaję kod błędu 400 i nic więcej, co jest dziwne gdyż na stronie
https://developer.allegro.pl/documentation/#operation/doAddToBlackList
piszę iż w odpowiedzi powinienem dostać tablice obiektów (błędów) 

	

	$user = array(
		"user" => array(
			"login" => "$login"
		),
		"note" => "$note"
	);
	$query = json_encode($user);
	
	
	$blacklistUrl = "https://api.allegro.pl/sale/blacklisted-users"."?".$query;

    $ch = curl_init($blacklistUrl);
	
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
		
    $result = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	
	if ($result === false || $resultCode !== 201) {
                echo "Response status code: $resultCode\n";
                echo "result: $result";
                exit;
    }`

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przykładowy request w formacie cURL wraz z responsem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopisz GitHub #2393 
Zweryfikuj także:
- co dokładnie mówi error.message,
- co przesyłasz w body, czy jest to zgodne z przykładem z [dokumentacji,](https://developer.allegro.pl/documentation/#operation/doAddToBlackList),
- do jakiego url się odwołujesz, w Twoim przykładzie widzę nadmiarowe dane po  POST sale/blacklisted-users.

**Comment by Judasz121** [comment]
Poszło.

> do jakiego url się odwołujesz, w Twoim przykładzie widzę nadmiarowe dane po POST sale/blacklisted-users.

odwołuje się do https://api.allegro.pl/sale/blacklisted-users
widać to zresztą w moim kodzie wyżej.

Co masz na myśli "nadmiarowe dane po POST sale/blacklisted-users"?

**Comment by PrzemyslawLukanowski** [comment]
@Judasz121  Zweryfikowaliśmy Twoje zgłoszenie, błąd generuje działanie, o którym wspominam powyżej. w url przekazujesz dodatkowe informacje, które musisz zawrzeć w body requestu:

POST sale/blacklisted-users?**{{"user":{"login":"{login}"},"note":"test"}}**

Powinno być:

POST sale/blacklisted-users

a w body:

```
{
  "user": {
    "login": "login"
  },
  "note": "note"
}
```

**Comment by kfijalko** [comment]
Poniżej kawałek kodu, musisz dostosować:

`
        //adres url
        $command_uuid=Uuid::generate()->string;
        $uri = 'https://api.allegro.pl/sale/offer-publication-commands/' . $command_uuid;
        // Log::info(__CLASS__.":".__METHOD__.":".__LINE__.'Wywołuję: '.$uri );
        //nagłówki
        $headers = [
            'Accept: application/vnd.allegro.public.v1+json',
            'Content-Type: application/vnd.allegro.public.v1+json',
            'Authorization: Bearer '.$token_allegro.''
        ];

        $curl = curl_init($uri);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        $params= [
            'publication' => [
              'action' => 'END',
            ],
            'offerCriteria' => [
            [
                'offers' => [
                    ['id' => $offer_id],
                ],
                'type' => 'CONTAINS_OFFERS'
            ],
            ]
          ];
        $data = json_encode($params);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data);    

        $curl_result = ($curl_result = curl_exec($curl)) === false ? false : json_decode($curl_result);
        $curl_httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        $curl_err = curl_error($curl);
        curl_close($curl);
        // dd($curl_result);
        
        //poprawna odpowiedź
        if($curl_httpcode == 201){
            // Log::info(__CLASS__.":".__METHOD__.":".__LINE__."Wysłałem żądanie. ".$uri);
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'SENDED', [$offer_id], 'ACTIVE', 'ENDED');
            return $curl_result;
        }
        elseif ($curl_httpcode == 400) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Semantically incorrect request or provided conditions not correct');
            return false;
        }
        elseif ($curl_httpcode == 401) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Unauthorized');
            return false;
        }
        elseif ($curl_httpcode == 403) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Forbidden');
            return false;
        }
        elseif ($curl_httpcode == 404) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Not Found');
            return false;
        }
        elseif ($curl_httpcode == 409) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Command id was already used');
            return false;
        }
        elseif ($curl_httpcode == 422) {
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', 'Unprocessable Entity');
            return false;
        }

        if($curl_result === false){
            Log::error(__CLASS__.":".__METHOD__.":".__LINE__.'Wystąpił błąd podczas wywoływania '.$uri .' komunikat:'.$curl_err);
            AllegroClientCommand::writeCommandIntoDB($command_uuid, $account_id, 'END_OFFER', 'ERROR', [$offer_id], 'ACTIVE', 'ENDED', $curl_err);
            return false;
        }

        Log::error(__CLASS__.":".__METHOD__.":".__LINE__.' Wystąpił błąd - nie wiem dlaczego jestem w tej linii');
        return false;`

**Comment by Judasz121** [comment]
Dobra teraz widzę jak poprzednie pytania były głupie.

Teraz jednak wziąłem i dostosowałem kod od @kfijalko,
i dalej dostaje w twarz 500tką, "internal server error".

> Response code: 500object(stdClass)#2 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#1 (5) { ["code"]=> string(21) "INTERNAL_SERVER_ERROR" ["message"]=> string(22) "Internal server error." ["details"]=> NULL ["path"]=> NULL ["userMessage"]=> string(57) "Internal server error. Please try again in a few minutes." } } }
Results:
Error:

Kod:


	

	$uri = 'https://api.allegro.pl/sale/blacklisted-users';
	$token = getAccessToken($clientId, $clientSecret);

	$headers = [
	'Accept: application/vnd.allegro.public.v1+json',
	'Content-Type: application/vnd.allegro.public.v1+json',
	'Authorization: Bearer '.$token.''
	];

    $curl = curl_init($uri);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST');
	//curl_setopt($curl, CURLOPT_POST, 1); // próbowałem również ze standardowym post
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

    $params= [
	
		"user" => [
			"login" => "$login",
		],
		"note" => "$note"
	];
	  
    $data = json_encode($params);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);   
	
    $curl_result = ($curl_result = curl_exec($curl)) === false ? false : json_decode($curl_result);
    $curl_httpcode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
    $curl_err = curl_error($curl);
    curl_close($curl);


    if($curl_httpcode == 201){
        echo "Results: ".var_dump($curl_result);
		echo "</br>";
	}
	elseif($curl_httpcode !== 201){
		echo "Response code: ".$curl_httpcode;
		echo "</br> Results: ".var_dump($curl_result);
		echo "</br> Error: ".$curl_err;
		echo "</br>";
	}

**Comment by PrzemyslawLukanowski** [comment]
Tak jak piszemy przy okazji innych zgłoszeń związanych z konkretnymi językami programowania - niestety ze względu na ich dużą liczbę, nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.
Możesz także ponownie wysłać nam pełen request w formacie danych cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) (+ dopisek GitHub #2422).

**Comment by kfijalko** [comment]
wyswietl sobie token i parametry w json,moze tu jest cos nieprawidlowego

**Comment by Judasz121** [comment]
Token jest dobry, jak go psuje to wywala mi że niepoprawna autoryzacja więc tutaj jest ok.

Co do parametrów to wysłałem requesty z obu kodów, mojego i twój@kfijalko -> (bez uuid na końcu adresu) do siebie na netcata, żeby porównać i nie widzę żeby coś było nie tak.

mój:
>POST / HTTP/1.1
Host: localhost:123
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NzE5NzAxNzAsImp0aSI6IjUxNDVlZmMwLTQyYjgtNGY5NS1hZTQwLTFiMzMzOGVkZDE5ZSIsImNsaWVudF9pZCI6Ijg3ZDk2YzBkN2M3YjQxOWFiODZhMDQzYWZmZGEzYWIwIn0.CNOatBenhaRUFEEAWJ86kkCgKlOG6-GXlTCTh2UDCBwvyJT2LYghTIfeZBxWOb8YQVTOhmbcik8t-WnwrJC2EDCa0xpjTWVAP7BZ0NGu73CQOY6ypbYKryUJ64kFILoP6R7CgIik0oZJdkat1i3jnR5A1ZO0fUSPEtg5Xx0Mx5Cj2QVXOM9c5ZTHGZc86jPrSBitN3uVmvwQIpbHdHqRYq_Yn8s8BvuXbIN119YJXrfpDd7oFrk8IujFKwqu_N5KvMfvK4SmCimZ2ZcZWF5wF0N981zuUq8kzeRdz8mU82AV1qHOrjzGiK2pEn-k6yKaUNzk815ldyRQ7-PR3IZapw
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 42
{"user":{"login":"TORX_PL"},"note":"test"}

I kfijalkowy: 
>PUT / HTTP/1.1
Host: localhost:123
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NzE5NzAxMjMsImp0aSI6ImIyN2M5NDViLWVhYzctNGE1Zi05NzMyLTMzZjFhZDFiOTNkMCIsImNsaWVudF9pZCI6Ijg3ZDk2YzBkN2M3YjQxOWFiODZhMDQzYWZmZGEzYWIwIn0.colItcqOY5Myb_yWp3X3XVjuAmIveg_pzCCCBlNKDWXr_sCqmA7IytL_YIBZeTfkl6kUjMQ8QP91udyQ52f-jkbMPYmE8qjISSJhpZBw1h-94ckhwnmNy0aaZteHcOnDMFlE_jYZjlJCdXqemS7V5FX5rcFZh1Sy1adEcjJlIJL8OYXPJx9d6V2dhhnjLLNwSTE3HtaLfCQ7P4irgxnAUUXyfR4h4mwOQbVtAjic9uZjNcuV6GeWpB068Y2yh6Ifnpx2qX00L-0ceDXKgd7kCPJGWXzEgnn45hgndLKH1ONwJ4_ozSBRYrvhSwceag0IW2TU0HunBVC7TNFh6urJlA
Content-Length: 100
{"publication":{"action":"END"},"offerCriteria":[{"offers":[{"id":null}],"type":"CONTAINS_OFFERS"}]}

**Comment by kfijalko** [comment]
skasuj token lub go uniewaznij :)

**Comment by kfijalko** [comment]
dobra jeszcze jeden pomysł
zainstaluj sobie aplikację postman
zrób sobie to wywołanie
jezeli odpowiedź allegro będzie poprawna to 
w postmanie możesz wygenerować kod php z curl'em
porównaj ze swoim

**Comment by kfijalko** [comment]
osobiście nie używam tej metody.
może zacznij od pobrania listy kategorii GET'y
POST'y możesz poćwiczyć na definiowaniu cenników dostawy
w razie błędów w kodzie będzie mniej destrukcyjna przy nauce

**Comment by Judasz121** [comment]
>skasuj token lub go uniewaznij :)

Kurde masz racje, myślałem że jest ważny 10 sekund ale pomyliłem z kodem autoryzującym redirect_uri

Co do postmana to właśnie mam go pobranego i chciałem to zrobić ale myślałem że token 10 sekund ważności ma.

Anyway dzięki za uświadomienie mi mojej głupoty :)

**Comment by Judasz121** [comment]
@PrzemyslawLukanowski Wysłałem do was zgłoszenie przez formularz kontaktowy z kodem w formacie cURL wygenerowanym w postmanie.

Jak wygląda sytuacja? Po czyjej stronie leży problem?

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na problem z Twoim tokenem - otrzymałeś go za pomocą autoryzacji client credentials. Aby skorzystać z tego zasobu, konieczne jest przejście autoryzacji typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow.

**Comment by Judasz121** [comment]
Rzeczywiście, mój błąd, teraz działa.
Dzięki za pomoc :)
