### ISSUE TITLE
zwrot prowizji

### ISSUE THREAD

**Issue by webdachu** [allegro/allegro-api#2423]
Witam
mam 2 pytania:
próbuje wyświetlić  listę zwrotów prowizji (rabaty) - to dotyczy metody: doGetRefundsDeals ?
i czy można przefiltrować listę wg:
-zamówienia z nieuzupełnionym formularzem dostawy,
-zamówienia z uzupełnionym formularzem dostawy, ale nieopłacone,
-zamówienia, które utworzone 2 tygodnie temu od obecnej daty,
-zamówienia, których data utworzenia nie przekracza 45 dni.

który atrybut dotyczy tego filtrowania, macie jakiś przykład z użyciem filtrów?
w paymentStatus widze tylko możliwość użycia: missing i without_payu? 

dziękuje
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
doGetRefundsDeals dotyczy aktów zakupowych, dla których możesz złożyć wniosek o zwrot prowizji. Listę złożonych wniosków pobierzesz za pomocą doGetRefundsList.
Dostępne filtry znajdziesz na końcu odpowiedzi:
![Screenshot_23](https://user-images.githubusercontent.com/51473661/67469770-f501e400-f64c-11e9-9fa2-a49707072fa1.png)

Jak widzisz, dostępne filtry to itemId oraz userLogin. Nie ma zatem możliwości wyfiltrowania listy w sposób, o którym piszesz.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie znamy jeszcze ostatecznego ksztatu tego zasobu. O wszystkich szczegółach poinformujemy we właściwym komunikacie.
