### ISSUE TITLE
Wystawienie aukcji w przyszłości POST sale/offers publication.startingAt

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2424]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Mam problem z wystawieniem aukcji w zaplanowanej w przyszłości.

Chodzi o zasób POST sale/offers

Przykładowy trace-id (sandbox) e94477edd9791b28
Przykładowy szkic aukcji: 6206696661

Chciałbym aby aukcja została wystawiona w przyszłości, np. jutro o godzinie 19:20. Przy publikacji oferty przesyłam

`"publication":{"startingAt":"2019-10-25T17:20:00.000Z"}`

Niestety w aukcji nie zapisują się te dane. Próbowałem również podać wymagany duration

`"publication":{"startingAt":"2019-10-25T17:20:00.000Z","duration":null}`

Jak również cały obiekt

`"publication":{"startingAt":"2019-10-25T17:20:00.000Z","duration":null,"status":"INACTIVE","endingAt":null,"endingBy":null,"republish":false}`

Bez rezultatu.

Po zapisaniu szkicu mogę edytować zasób PUST sale/offers/ - i wtedy zaplanowana data wystawienia się zmienia.

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
null w tym przypadku jest zwracane prawidłowo. Wartość startingAt możesz dopiero ustawić na endpoincie [PUT /sale/offers/{offerID} ](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT)lub przy publikacji oferty za pomocą [PUT sale/offer-publication-commands/{uuid}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) (pole scheduledFor).

**Comment by Radeq** [comment]
@PrzemyslawLukanowski, rozumiem. Czy takie zachowanie jest opisane gdzieś w pomocy/poradniku (np. Jak wystawić ofertę w Allegro REST API)?

**Comment by PrzemyslawLukanowski** [comment]
W najbliższym czasie dodamy taką informację do poradnika, w którym wspominasz.

**Comment by Radeq** [comment]
Dziękuję, na pewno się przyda.
