### ISSUE TITLE
Statusy płatności w odbieranych zamówieniach /order/checkout-forms - kiedy się zmienia i jak to wykryć?

### ISSUE THREAD

**Issue by zawadzki14** [allegro/allegro-api#2425]
Zakładam hipotetyczną sytuację kiedy klient złoży zamówienie i wypełni formularz pozakupowy i status płatności będzie widniał jako: PŁATNOŚĆ ROZPOCZĘTA .
Ja wtedy pobieram informacje o całym zamówieniu za pomocą /order/checkout-forms 
i wtedy zapisuję sobie wszystkie informacje na temat tego zamówienia, i wtedy do mojej bazy danych trafia także informacja, że płatność jest rozpoczęta.

Pytanie jest takie: kiedy i skąd mam zaczerpnąć informację o tym, że płatność została zakończona?
Jaka metoda jest najlepsza do tego, żeby to sprawdzić? 

W /order/events mogą przychodzić wielokrotnie statusy: READY_FOR_PROCESSING ale przecież nie wiadomo co się zmieniło. 

Czy aktualny status płatności (tzn chcę sprawdzić czy płatność zakończone) lepiej jest pobierać:
A) Ściągając od nowa wszystkie szczegóły formularza (/order/checkout-forms ) 
B) Czy ściągając aktualny status płatności przy pomocy: /payments/payment-operations ?

Rozwiązane A wydaje się lepsze ponieważ przy okazji będę widział ewentualne dopłaty

**Comment by PatrykBocian** [comment]
Tak jak piszesz, zasób **GET/order/checkout-forms** w tym przypadku zwraca najwięcej informacji.
Informacje o tym, kiedy płatność została zakończona, znajdziesz w polu **payment.finishedAt.**
Więcej na ten temat znajdziesz w naszym [poradniku.](https://developer.allegro.pl/orders/)
