### ISSUE TITLE
Status zamówienia widoczny w "Zamówienia" - znaczenie ? i czemu brakuje w API (nowe/wysłane/anulowane) itp)

### ISSUE THREAD

**Issue by zawadzki14** [allegro/allegro-api#2426]
Wchodząc na stronę Allegro.pl i zakładkę "Zamówienia" widać przy każdym wypełnionym formularzu pole ze statusem, które można zmienić na: NOWE, W REALIZACJI, DO WYSŁANIA, WYSŁANE, ANULOWANE. 

Czy taki status ma jakieś znaczenie w kwestii oceniania sprzedawcy?
A może taki status jest nieznaczący i służy tylko i wyłącznie dla sprzedawcy ?
Czemu takiej funkcji brakuje w API?

**Comment by PatrykBocian** [comment]
Nie ma to znaczenia w przypadku oceny sprzedawcy, pomaga to przy filtrowaniu i uporządkowaniu zamówień.
Nie ma takiej funkcji w API lecz pojawiły się odnośnie tego sugestie, dlatego jeśli zostanie to wdrożone, opublikujemy odpowiedni komunikat.
