### ISSUE TITLE
Brak wpisów w doGetSiteJournalDeals

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#2427]
Klient wybrał sposób dostawy i wypełnił formularz pozakupowy, a my dostaliśmy maila, niestety w `doGetSiteJournalDeals` brak wpisów z `dealTransactionId`.

Ostatni dotyczący tego klienta to:
{
     'dealEventId': 5142131236,
     'dealEventType': 1,
     'dealEventTime': 1571914006,
     'dealId': 2188042488,
     'dealTransactionId': 0,
     'dealSellerId': xx,
     'dealItemId': 8149771307,
     'dealBuyerId': xx,
     'dealQuantity': 1
 }

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj pobrać dane jeszcze raz, tym razem powinien już być komplet danych.

**Comment by anih** [comment]
Mam nadzieje że jak już będzie ok to będzie to nowy event, bo jak stary to on został już przetworzony i nie ma opcji przetworzenia go jeszcze raz
