### ISSUE TITLE
Nie mogę porać opłat/prowizji dla danej kategorii

### ISSUE THREAD

**Issue by plancys** [allegro/allegro-api#2428]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

ca0ac238bc8e714c

Dostaje konsekwentnie 503 po takim requescie:
curl -vvv -X POST \
  https://api.allegro.pl/pricing/fee-preview \
  -H 'accept: application/vnd.allegro.public.v1+json' \
  -H 'authorization: Bearer <mojBerer>' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/vnd.allegro.public.v1+json' \
  -d '{
  "includeQuotingBundles": false,
  "offer": {
    "category": {
      "id": "122569"
    },
    "quantity": 100,
    "soldQuantity": 10
  }
}'

< HTTP/2 503
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: ca0ac238bc8e714c
< date: Thu, 24 Oct 2019 13:08:44 GMT
< x-ratelimit-remaining: 9000
< x-content-type-options: nosniff
< content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
< content-length: 175
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 23
<
* Connection #0 to host api.allegro.pl left intact
{"errors":[{"code":"SERVICE_UNAVAILABLE","message":"Service unavailable.","details":null,"path":null,"userMessage":"Service unavailable. Please try again in a few minutes."}]}%

Dlaczego tak jest? bo powoli kończą mi się pomysły..

**Comment by PatrykBocian** [comment]
Aby zasób zadziałał prawidłowo konieczne jest dodanie w body pola “unitPrice”.
Poza tym należy także dodać pole “shop”, przyjmujące wartość “true” lub “false”, będzie ono ignorowane jeśli określimy typ oferty (“offer.type”) niemniej któreś z nich musi znaleźć się w body.
Więcej informacji na ten temat znajdziesz w naszej [dokumentacji.](https://developer.allegro.pl/documentation/#operation/previewFeesPublicAPIUsingPOST)

**Comment by plancys** [comment]
Ok, teraz już działa przez zarzutów. Dziękuję.

Według dokumentacji tylko **category** i **unitPrice** jest wymagane w body: https://developer.allegro.pl/documentation/#operation/previewFeesPublicAPIUsingPOST

**Comment by PatrykBocian** [comment]
W dokumentacji dla pola “offer” znajdziesz szczegółową informację:

“Offer type. 'type' or 'shop' fields must be provided. Takes precedence over 'shop' field. Note: if type = 'advertisement' then either 'quantity' or 'soldQuantity' field must be set.”

Odnośnie pola “shop”:

“Deprecated. Value 'true' sets the 'offer.type' field to 'shop', value 'false' to 'offer'. This field is ignored if 'offer.type' field is set.”

Nie jest to oznaczone jako “required” ponieważ tutaj masz wybór co do pola które uzupełnisz, jednak jedno z nich musi zostać podane w body.
