### ISSUE TITLE
Sugestie do dokumentacji

### ISSUE THREAD

**Issue by alananh** [allegro/allegro-api#243]
Witam, 
większość osób prawdopodobnie zaczyna pracę od przeczytania poradników https://developer.allegro.pl/sale/ i https://developer.allegro.pl/documentation/, na moje oko brakuje tam jednak paru drobnych wskazówek, które oszczędziłyby wielu z nas bólu głowy :) 

- Że EAN musi mieć 13 cyfr. Dużo sprzedawców może mieć EANy w swoich sklepach wpisane randomowo.
- Dopuszczalne formaty zdjęć (.jpg, .png, do teraz nie sprawdziłem czy ".jpeg" przejdzie...)
- Maksymalny rozmiar zdjęć (w pixelach, w kilobajtach) 
- Co to jest /sale/offer-contacts. Że tyczy się tylko ogłoszeń. Bardzo długo się zastanawiałem co to jest.
- Że parametry aukcji typu "float" tak na prawdę powinny być przesłane jako "string"  
https://developer.allegro.pl/sale/#parameters

**Comment by alananh** [comment]
Co do offer-contacts. Znam stronę ustawień na Allegro.pl na pamięć. Ale myślałem, że to jakaś nowa opcja "dodaj dane kontaktowe do oferty". Klikałem przez jakieś pół godziny po ustawieniach konta, ustawieniach aukcji i niczego takiego nie znalazłem. Bouncowałem między allegro.pl a docsami na developer.allegro.pl próbując ustalić co to jest. 
Dopiero zgooglowanie tego:
`site:developer.allegro.pl offer-contacts`
nakierowało mnie na
`https://developer.allegro.pl/news/2018-01-17-news_zarzadzanie_kontaktami/`
gdzie meta-title strony w podglądzie Googla brzmiał tylko "Aktualności - Allegro Developer Portal". Ale znalazłem, bo w desperacji klikałem każdy link.
No tak, to się tyczy ogłoszeń. Nigdy nie wystawiałem żadnych ogłoszeń ^^

**Comment by PawelTaberski** [comment]
Staraliśmy się, aby dokumentacja odnośnie wystawiania ofert przez REST API była jak najbardziej spójna, ale nie chcieliśmy jej zbyt mocno rozbudowywać, aby ciągle była czytelna.
Przykładowo dopuszczalne formaty zdjęć znajdziesz w przykładzie wywołania metody:
` -H 'content-type: "image/jpeg", "image/png", albo "image/gif”`
Odnośnie zasobu sale/offer-contacts dotyczy tak jak napisałeś ogłoszeń - dodamy taką informację w dokumentacji.
Co do EAN-u nie wystarczy podać jakichkolwiek 13 cyfr - więcej [tutaj](https://allegro.pl/dla-sprzedajacych/kod-ean-w-allegro-wqggrjgj2hR) - dodamy odnośnik do dokumentacji.
Dziękujemy za sugestie, przy najbliższej aktualizacji strony uzupełnimy te informacje.
