### ISSUE TITLE
kupujący XXX (YYY) odstąpił od umowy

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#2430]
W jaki sposób z poziomu API  WSDL/REST obsłużyć rezygnacje? 
Są jakieś metody dedykowane, ewentualnie pola w responsach?

**Comment by BABYBOOM-SERWIS** [comment]
To jeszcze pytanie kiedy planujecie takie zasoby? Byłoby to ułatwienie pracy dla dużej ilości firm.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem przydatność tego zasobu, jak najbardziej mamy to w planach rozwoju API. Na tę chwilę nie mogę określić konkretnego terminu, kiedy wprowadzimy tę funkcjonalność.
