### ISSUE TITLE
Nip dla firmy ma wartość NULL

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2431]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hej!
Dzisiaj dostałem zamówienie, które ma podane dane firmy, a nip == null. Nawet na froncie allegro to widać:
![image](https://user-images.githubusercontent.com/24191650/67553470-833d9f00-f70d-11e9-9d81-d45e4b799e8c.png)

Czy w przypadku zaznaczenia opcji Firma, nip nie powinien zawsze być podawany?

**Comment by PatrykBocian** [comment]
Podaj proszę numer zamówienia, pomoże to nam zweryfikować problem.

**Comment by jakubmaguza** [comment]
bd34fec4-f6f8-11e9-9169-239382c0ce8e

**Comment by jakubmaguza** [comment]
To dziwne:
![image](https://user-images.githubusercontent.com/24191650/67554118-fabffe00-f70e-11e9-9aed-c89608789301.png)

ID Płatności:
be1dd824-f6f8-11e9-9dad-999fc358f6a3

ID Sellera: TVSAT-SHOP

DATA SPRZEDAŻY:
25 paź 2019, 09:26

**Comment by PatrykBocian** [comment]
Zweryfikowałem ten błąd. Wynika on z tego, że kupujący wykonał zakup na starej wersji aplikacji Allegro na iOS. Występował tam błąd, który pozwalał na pominięcie kroku z podaniem numeru NIP do faktury na firmę. W nowych wersjach aplikacji jest to poprawione i problem ten nie występuje.

**Comment by jakubmaguza** [comment]
Okej, dzięki za informację.
