### ISSUE TITLE
Brak formularza w https://api.allegro.pl/order/checkout-forms

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#2434]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Brakuje jednej transakcji z dzisiaj z godz. 09:31, id aukcji: 8419494595.
Metoda zwraca wszystkie transakcje, z wyjątkiem tej jednej.

**Comment by mareklemur** [comment]
Dla ścisłości, chodzi o zamówienie nr: 2ca98eb2-f6f9-11e9-bb5a-c9ea9502b862 - pobieram wszystkie z ostatnich 14 dni - tego nie ma na liście.

**Comment by PatrykBocian** [comment]
Zweryfikowałem to - problem występuje w przypadku niektórych zamówień. Zgłosiłem to do odpowiedniego zespołu. Jak się czegoś dowiem, przekażę więcej informacji.

**Comment by PatrykBocian** [comment]
Wystąpiły chwilowe problemy z tym zasobem, wszystko już działa prawidłowo.
Zamówienia z którymi występował problem powinny pojawić się w najbliższym czasie.
