### ISSUE TITLE
Problem /offers/listing

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#2435]
Witam,

Zauważyłem problem występujący podczas wykonywania następującego zapytania:

https://api.allegro.pl/offers/listing?seller.id=XXX&offset=100&limit=100

Podczas zamiany parametru offset and limit  otrzymuję w odpowiedzi zawsze na początku te same promowane oferty i następnie dopiero pozostałe. 

Promowane oferty powielają się na każdej stronie bez względu na ustawiony offset

Wcześniej było tak że promowane oferty pojawiały się tylko raz nie były dublowane i to zakładam było prawidłowe działanie.

Proszę o sprawdzenie.

**Comment by PatrykBocian** [comment]
Zweryfikowałem to i nie wykryłem żadnych problemów z tym zasobem.
Parametr “offset” działa dla ofert promowanych, nie są dublowane przy ustawieniu wartości na inną.
Jeśli możesz prześlij nam konkretne wywołanie, jakie przekazujesz - tutaj lub przez formularz kontaktowy.

**Comment by krzysda** [comment]
Pierwsze wywołanie:

https://api.allegro.pl/offers/listing?seller.id=15051481&limit=100

Otrzymuje:

[items] => stdClass Object
        (
            [promoted] => Array
                (
                    [0] => stdClass Object
                        (
                            [id] => 8476261624
                            [name] => CZAJNIK NA GAZ CZARNY MAT Z GWIZDKIEM 3L STALOWY
                            [seller] => stdClass Object
                                (
                                    [id] => 15051481
                                    [company] => 1
                                    [superSeller] => 1
…..

Itd.

Następnie 

https://api.allegro.pl/offers/listing?seller.id=15051481&offset=100&limit=100

Otrzymuje:

    [items] => stdClass Object
        (
            [promoted] => Array
                (
                )

            [regular] => Array
                (
                    [0] => stdClass Object
                        (
                            [id] => 7696995032
                            [name] => 3 x WIESZAK HACZYK NA PRZYSSAWKĘ CHROM UCHWYT
                            [seller] => stdClass Object

Brak promowanych wszystko ok

I następnie

https://api.allegro.pl/offers/listing?seller.id=15051481&offset=300&limit=100

[items] => stdClass Object
        (
            [promoted] => Array
                (
                    [0] => stdClass Object
                        (
                            [id] => 8476261624
                            [name] => CZAJNIK NA GAZ CZARNY MAT Z GWIZDKIEM 3L STALOWY
                            [seller] => stdClass Object
                                (
                                    [id] => 15051481
                                    [company] => 1
                                    [superSeller] => 1

I znowu są promowane a na dodatek ten sam produkt 8476261624 co w pierwszym zapytaniu.

**Comment by PatrykBocian** [comment]
Występuje problem z wartością tego parametru. Gdy ustawisz offset >= 300, filtr jest ignorowany.
Zgłosiłem to do odpowiedniego zespołu.

**Comment by 11mszot** [comment]
Ten sam problem występuje na witrynie Allegro przy stronicowaniu  i przeglądaniu listingów (jak sądzę witryna korzysta z tego samego mechanizmu)  ,powyżej strony 6 zwracane są cały czas te same wyniki

**Comment by PatrykBocian** [comment]
@11mszot Czy problem nadal występuje? Próbowałem go odtworzyć i nie udało mi się.
Możesz podesłać przykładowy url gdzie ten problem występuje?

**Comment by 11mszot** [comment]
Problem ustał tego samego dnia wieczorem, występował praktycznie w każdym
listingu ofert na stronie Allegro oraz w metodzie /offers/listing w Rest Api

pon., 28 paź 2019 o 14:46 PatrykBocian <notifications@github.com>
napisał(a):

**Comment by PatrykBocian** [comment]
@11mszot  Dziękujemy za informację, dodałem to do poprzedniego zgłoszenia.

**Comment by PrzemyslawLukanowski** [comment]
Usterka związana z parametrem offset została usunięta, zasób działa prawidłowo.
