### ISSUE TITLE
/sale/offers - 401 Internal Server Error

### ISSUE THREAD

**Issue by Engazan** [allegro/allegro-api#2436]
Hi, 

i would like to know how to get seller's offers ( i got token with seller credentials ), but still cant figure out what´s wrong 

tracer-id: `27634f78ebc6f85e`

called URI: `https://api.allegro.pl/sale/offers?limit=1000&offset=0&publication.status=ACTIVE&sellingMode.format=BUY_NOW`

Status code: `401 Unauthorized` 

JSON Response 
`{
    "errors": [
        {
            "message": "Internal Server Error",
            "userMessage": "Internal Server Error",
            "code": "",
            "details": "",
            "path": ""
        }
    ]
}`

Other endpoints like `/sale/categories` works great

**Comment by PrzemyslawLukanowski** [comment]
You are using [clients credentials](https://developer.allegro.pl/en/auth/#clientCredentialsFlow) type of authorization. To get access to this endpoint, you should use token from [code flow](https://developer.allegro.pl/en//auth/#app) or [device flow](https://developer.allegro.pl/en//auth/#DeviceFlow) authorization.
In documentation you can find [information](https://developer.allegro.pl/documentation/#section/Authentication), which type of authorization you should use for selected resource:
![Screenshot_26](https://user-images.githubusercontent.com/51473661/67561795-c4d64600-f71d-11e9-83f7-f265c20bed55.png)
bearer-token-for-user - code or device flow,
bearer-token-for-application - client credentials flow - access only to public resources, without user context, e.g. GET /offers/listing.
