### ISSUE TITLE
PILNE! zamówienia niewidoczne w zasobach rest

### ISSUE THREAD

**Issue by Zbigniew-L** [allegro/allegro-api#2437]
Występuje problem: 
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
zauważylismy, że od niedawna niektóre zamówienia nie pokazują się na listingach (tak jakby nie było ich w systemie!)

nie ma ich zarówno w zasobie order/event-stats jak i order/checkout-forms

prosimy o sprawdzenie np. zam:
fccf4943-f6fe-11e9-bb5a-c9ea9502b862

5a738302-f6f9-11e9-bc15-0528b04ee3d7

nie wiemy jeszcze jak duży jest to problem - może jest związany z nowym sposobem rozliczania smart inpost w cenie 0 zł?

**Comment by mareklemur** [comment]
Potwierdzam, brakuje też zam. 2ca98eb2-f6f9-11e9-bb5a-c9ea9502b862

**Comment by PatrykBocian** [comment]
Zweryfikowałem to - problem występuje w przypadku niektórych zamówień. Zgłosiłem to do odpowiedniego zespołu. Jak się czegoś dowiem, przekażę więcej informacji.

**Comment by mareklemur** [comment]
Kolejne zamówienie na innym koncie: 3521ca72-f71d-11e9-8cfa-091beb8dde80

**Comment by mareklemur** [comment]
Forma wysyłki nie ma znaczenia: Kurier InPost czy Allegro Paczkomaty 24/7 InPost z pakietem smart.

**Comment by PatrykBocian** [comment]
Wystąpiły chwilowe problemy z tym zasobem, wszystko już działa prawidłowo.
Zamówienia z którymi występował problem powinny pojawić się w najbliższym czasie.
