### ISSUE TITLE
Full authentication is required, aktywacja?

### ISSUE THREAD

**Issue by arturm2** [allegro/allegro-api#2439]
Występuje problem:
 - [X] z logowaniem lub autoryzacją

Request nowego tokena kończy się błędem
{"error":"Unauthorized","error_description":"Full authentication is required to access this resource"}

Czy to problem z aktywacją konta?
Jeżeli tak, to proszę o aktywację.

Dzięki,

Artur M

**Comment by arturm2** [comment]
Nazwa konta w allegrosandbox.pl: arturm2

**Comment by PrzemyslawLukanowski** [comment]
@arturm2 Aktywowałem Twoje konto na sandboxie. Spróbuj ponownie wygenerować token.

**Comment by arturm2** [comment]
Utworzyłem nowa aplikacje (client id, secret)
Nadal dostaje "unauthorised, full authentication required..."

A.

pt., 25 paź 2019, 14:27 użytkownik PrzemyslawLukanowski <
notifications@github.com> napisał:

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) pełen request w formacie cURL, dopisz także nr zgłoszenia - GitHub #2439.

**Comment by arturm2** [comment]
Wysłane

A.

pt., 25 paź 2019, 14:44 użytkownik PrzemyslawLukanowski <
notifications@github.com> napisał:

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy Twój request. Widzę, że w url przekazujesz:
https://allegro.pl.allegrosandbox.pl/auth/oauth/authToken?grant_type=client_credentials 
zamiast 
https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials.  
Spróbuj zamienić nazwę authToken na token - przetestowałem to i autoryzacja przebiegła prawidłowo.

**Comment by arturm2** [comment]
Dzięki za pomoc!

A.

pon., 28 paź 2019, 08:10 użytkownik PrzemyslawLukanowski <
notifications@github.com> napisał:
