### ISSUE TITLE
Jak pobrać wszystkie oferty ze starym opisem

### ISSUE THREAD

**Issue by lukaszkinder** [allegro/allegro-api#244]
Jak pobrać wszystkie oferty ze starym opisem? Czy jakiś filtr nam w tym pomoże? czy może jedynym sposobem jest czy pole FID 341 jest puste?

**Comment by LukaszKorek** [comment]
Nie udostępniamy w API takiej funkcjonalnosci. Jest tak jak piszesz - aby sprawdzić czy oferta jest ze starym opisem pobierz fidy i te z pustym 341 to będą te.
