### ISSUE TITLE
GET order by transaction_id

### ISSUE THREAD

**Issue by dboryc** [allegro/allegro-api#2440]
W jaki sposób mogę pobrać zamówienie posiadając wyłącznie transaction_id. Potrzebuję pobrać wartość z pola calculatedNumberOfPackages.

**Comment by PrzemyslawLukanowski** [comment]
[transaction.id zmapuj na payment.id ](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping), które następnie przekaż jako parametr [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)?payment.id=**{payment.id}**. W odpowiedzi otrzymasz interesujące Cię zamówienie.

**Comment by dboryc** [comment]
Super. Dzięki za szybką odpowiedź.
Pozdrawiam
