### ISSUE TITLE
auth device?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#2441]
Witam,
dzisiaj od godziny 6 rano mamy problem z wykoanniem
https://allegro.pl/auth/oauth/device
przy wysyłaniu danych metodą POST cały czas otrzymujemy:

{"error":"Unauthorized","error_description":"Unauthorized"}

Czy macie jakiś problem?

**Comment by PrzemyslawLukanowski** [comment]
Nie odnotowaliśmy podobnych zgłoszeń. Prześlij proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) przykładowy request w formacie cURL z dopiskiem GitHub #2441.
