### ISSUE TITLE
GET /order/events - totacCount

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2443]
:bulb: **Sugestia**

Czy nie byłoby wygodniej, gdyby GET /order/events
poza gołą listą eventów zwracał również, podobnie jak w przypadku offert  wartość totalCount?
Od razu wiadomo by było ile requestów jest potrzebnych, żeby pobrać całą listę. Teraz muszę pykać jedno zapytanie po drugim i sprawdzać czy już koniec czy nie, a tak mógłbym od razu strzelić całą serią.
 Zestandaryzowanie tego pozwoliołoby też pobierać różne zasoby tą samą metodą i wyeliminowało konieczność tworzenia osobnego mechanizmu do pobierania każdego zasobu z osobna.

**Comment by PatrykBocian** [comment]
Dziękujemy za sugestie, przekazałem ją do odpowiedniego zespołu.
Jeśli zdecydujemy się na wdrożenie, to poinformujemy o tym w odpowiednim komunikacie.

**Comment by Onixarts** [comment]
> a tak mógłbym od razu strzelić całą serią

A skąd będziesz miał parametr from dla pozostałych requestów?

**Comment by lukada4100** [comment]
No fakt. Potrzebny byłby jeszcze parametr offset.

**Comment by PatrykBocian** [comment]
@lukada4100  Dziekuje za sugestie, dodałem to do zgłoszenia.
