### ISSUE TITLE
Współpraca biznesowa

### ISSUE THREAD

**Issue by asoftf** [allegro/allegro-api#2445]
Dzień dobry, 
Chcielibyśmy jako software house nawiązać współpracę i wykorzystywać api allegro. Chciałbym się dowiedzieć jakie są ograniczenia korzystania z api? Czy są jakieś opłaty?
Pozdrawiam
ASoft

**Comment by PatrykBocian** [comment]
Korzystanie z API Allegro nie jest płatne, nie pobieramy za to żadnych opłat.
Co do możliwości i funkcjonalności naszego API, więcej na ten temat dowiesz się z naszej [dokumentacji.](https://developer.allegro.pl/documentation/) Ograniczenie, jakie obowiązuje w REST API Allegro, to 9000 zapytań na minutę. Więcej informacji znajdziesz na [naszym portalu.](https://developer.allegro.pl/about/#limits)
Przygotowaliśmy także serię poradników tłumaczących pierwsze kroki z REST API:
  -[Uwierzytelnianie i autoryzacja,](https://developer.allegro.pl/auth/)
  -[Jak wystawić ofertę](https://developer.allegro.pl/sale/),
  -[Jak powiązać ofertę z produktem.](https://developer.allegro.pl/productization/)
  -[Jak obsługiwać zamówienia,](https://developer.allegro.pl/orders/)
  -[Jak zarządzać ofertami,](https://developer.allegro.pl/my_offers/)

**Comment by kfijalko** [comment]
@PrzemyslawLukanowski czy zdjęliście ograniczenia 120req/sec/ip i 120req/sec/aplikację ?

**Comment by PatrykBocian** [comment]
@kfijalko  Obecnie obowiązujące limity to ograniczenie do 9000 zapytań na minutę.
Dodatkowo wykorzystujemy algorytm Leaky Bucket.
