### ISSUE TITLE
[PILNE] doGetSiteJournalDeals nie uwzględnia zmiany czasu

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#2446]
Dzień Dobry,
metoda doGetSiteJournalDeals w polu dealEventTime zwraca czas w unix time, który po przekształceniu do datetime odpowiada czasowi o godzinę przyspieszonemu. Na przykład, deal 2190648288 (c32fe040-f952-11e9-8002-f70d393c8b0c) zwraca dealEventTime = 1572250564 (wg obecnego czasu byłaby to 9:16), a przecież obecny czas, w momencie kiedy to piszę wynosi 1572249466 (godz 8:57). Jakim cudem Wasze czasy są w przyszłości?

Kolejny raz zawaliliście i kolejny raz rozjechało mi serwis przez Wasze błędy bo klienci nie dostają powiadomień z mojego serwisu jak należy.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszamy za utrudnienia, informacje o problemie przekazaliśmy już do odpowiedniego zespołu.

**Comment by amarel123** [comment]
> Przepraszamy za utrudnienia, informacje o problemie przekazaliśmy już do odpowiedniego zespołu.

Dlaczego po tylu dniach nie rozwiązano problemu?  Jeśli nie umiecie wywołać podstawowej, systemowej funkcji time() to chociaż do tego kurnika co macie teraz dopiszcie -3600, a za pół roku zmienicie sobie ręcznie znowu na prawidłowy czas przy kolejnej zmianie czasu. Widocznie w Allegro potrzebujecie dodatkowego pracownika od zmiany czasu :D Cyrk i to nie pierwszy raz. To jest niepoważne z Państwa strony.

**Comment by PrzemyslawLukanowski** [comment]
Jesteśmy w trakcie weryfikacji. Wrócę z odpowiedzią po wyeliminowaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@amarel123 Problem ze zmianą czasu został rozwiązany.
