### ISSUE TITLE
/offers/listing powtarzające się numery aukcji

### ISSUE THREAD

**Issue by infogos** [allegro/allegro-api#2447]
Witam

Przy pobieraniu listy wszystkich aukcji danego użytkownika za pomocą /offers/listing część numerów aukcji jest zduplikowana. 
Użytkownik ma 2900 aukcji. Pobieram je w paczkach po 100. Trzy dni temu pierwsze 300 pobierały się unikalne a dalsze były powtórzeniami pierwszej paczki. Dzisiaj 2800 jest dobrych a reszta się powtarza. 
Z filtrowania ustawiam tylko seller.id.
Gdzie należy szukać rozwiązania problemu?

Pozdrawiam

**Comment by kfijalko** [comment]
Spróbuj dodać sortowanie: czas do końca albo czas dodania. Powinno pomóc.

**Comment by PrzemyslawLukanowski** [comment]
Podobny problem pojawił się w wątku #2435, pracujemy nad rozwiązaniem. Czy możesz nam podać przykład pełnego url, jaki wywołujesz?

**Comment by infogos** [comment]
Pełny url https://api.allegro.pl/offers/listing?seller.id=XXXXX&limit=100&offset=0&sort=price
Pole offset zmienia się w zależności od numeru paczki. Wcześniej nie używałem sortowania, ale jak teraz dodałem to wygląda, że się nie powtarzają.
Dzięki

**Comment by kfijalko** [comment]
Ja pobieram 200k ofert i stosuję sortowanie po dacie dodania. Większe szanse niż cena, że się nie powtórzą. Choć jak pobrałem kilka milionów ofert konkurencji to powtórzenia były. Myślę, że jest to "wada/zaleta" elastików, które siedzą pod spodem - są nastawione na szybką odpowiedź kosztem dokładności czy sortowania. [To moje luźne przemyślenia, bo z elastikiem dopiero eksperymentuję ;)]

**Comment by PrzemyslawLukanowski** [comment]
@infogos Czy możesz podać dwa przykłady zapytań z użyciem offseta, dla których otrzymujesz takie same wyniki?

**Comment by infogos** [comment]
Teraz nawet bez sorta nie widzę żeby się powtarzały.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, usterka została usunięta.
