### ISSUE TITLE
W jaki sposób zasymulować nadpłate/niedopłate?

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2448]
Dzień dobry

W jaki sposób mogę zasymulować na sandboxie nadpłate/niedopłate i w jakich okolicznościach dochodzi do wystąpienia różnicy pomiędzy kwotą zamówienia a wpłaconą kwotą?

**Comment by PatrykBocian** [comment]
Niestety nie ma takiej możliwości na Sandboxie, możesz zasymulować jedynie dopłatę.
Jeśli chodzi o niedopłaty - do takich sytuacji może dojść, gdy kupujący, wybierając jako metodę płatności przelew tradycyjny, przeleje inną kwotę.
Więcej na temat nadpłaty/niedopłaty znajdziesz w naszym poradniku.
