### ISSUE TITLE
Podzielona płatność

### ISSUE THREAD

**Issue by maczking** [allegro/allegro-api#2449]
W sandboxie metoda płatności "podzielona płatność" jest dostępna dla zamówień powyżej 15 000 zł i to nie budzi większych wątpliwości, natomiast:
-dostępna jest również jeśli kupujący nie wybrał opcji otrzymania faktury - czy to zamierzone?
-dostępna jest gdy transakcja odbywa się między kontami prywatnymi - czy to zamierzone?(podzielona płatność jest przeznaczony dla B2B - tu budzi wątpliwość przede wszystkim to, że konta są prywatne i bez zaznaczenia wymagalności faktury opcja podzielonej płatności jest nadal dostępna)?
Szykujemy wdrożenie split payment dla transakcji allegro i bylibyśmy wdzięczni za odpowiedź czy dane działania są zamierzone, czy wdrażane będą w tym zakresie dodatkowe walidacje.

**Comment by PrzemyslawLukanowski** [comment]
Tak, te działania są zamierzone.

>  dostępna jest również jeśli kupujący nie wybrał opcji otrzymania faktury

Pole "faktura" nie jest walidowane, jej wybór lub brak wyboru nie wpływa na dostępne rodzaje płatności. Jeżeli kupujący wybierze opcję split payment w ofercie, gdzie sprzedający wskazał, że nie wystawia faktury, oznacza to informację dla sprzedającego - w tym momencie musi wystawić odpowiednią fakturę lub lub wysłać kupującemu dane niezbędne do wykonania przelewu (w tym kwotę brutto i kwotę VAT).

>  dostępna jest gdy transakcja odbywa się między kontami prywatnymi

Tak, nie blokujemy tutaj funkcjonalności dla użytkowników z kontem zwykłym, ponieważ robiąc zakupy przy takim rodzaju konta, kupujący może poprosić o fakturę na firmę.

**Comment by maczking** [comment]
Dziękuje za rozwianie wątpliwości :).
