### ISSUE TITLE
Kup w zestawie

### ISSUE THREAD

**Issue by JanuszK2** [allegro/allegro-api#245]
Czy istnieje metoda w WEB API obsługująca funkcję "Kup w zestawie"? Czy jest to zaimplementowane jedynie w REST API?

**Comment by LukaszKorek** [comment]
Funkcjonalność udostępniamy jedynie w REST API https://developer.allegro.pl/news/2017-10-18-News_promocyjne_zestawy_ofert/

**Comment by aktywnitu** [comment]
@LukaszKorek czy zasoby  /sale/loyalty/promotions pozwalają na aktualizację istniejącego zestawu?

**Comment by MartaNowaczyk** [comment]
@aktywnitu jeśli spróbujesz zmienić zestaw dla takich ofert, które w tej konfiguracji już go mają - dostaniesz błąd, że istnieje już jakiś pakiet. Także najpierw usuń promocję, a później dodaj nową. [Poradnik dla porządku.](https://developer.allegro.pl/offer_bundles/#5)
