### ISSUE TITLE
doGetPostBuyFormsDataForSellers zwraca puste pole postBuyFormItTitle w postBuyFormItems/item.

### ISSUE THREAD

**Issue by pkrzemo** [allegro/allegro-api#2451]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Od kilku minut metoda doGetPostBuyFormsDataForSellers zwraca puste pole **postBuyFormItTitle** w **postBuyFormItems/item**.
Niezapowiedziana zmiana?

**Comment by bortosProduction** [comment]
Potwierdzam, u nas również problem występuje

**Comment by kylovile** [comment]
Również chciałbym potwierdzić, że pole przychodzi puste

**Comment by PatrykBocian** [comment]
Dziękujemy za zgłoszenie, przekazałem to do odpowiedniego zespołu w celu dalszej weryfikacji.

**Comment by lucastes** [comment]
Przyłączam się, u nas też występuje ten problem u 3 klientów

**Comment by bozydarlelutko** [comment]
U mnie także jest puste pole.

**Comment by xvalkyrieEE** [comment]
Mamy podobnie przy pobieraniu zamówień z API do zewnętrznych oprogramowań.

**Comment by adiego129** [comment]
U nas również wciąż puste pole, ciekawe kiedy to naprawią??

**Comment by PatrykBocian** [comment]
Błąd został naprawiony, teraz wszystko działa prawidłowo
