### ISSUE TITLE
W jaki sposób pobrać oferty Sprzedawcy zgłoszone do Strefy Okazji?

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#2452]
Chciałbym odróżnić zwykłą ofertę z ofertą zgłoszoną do Strefy Okazji.
Czy jest to możliwe? Czy można pobrać oferty zgłoszone do Strefy Okazji?

**Comment by aktywnitu** [comment]
Tylko to?
https://api.allegro.pl/sale/badges

**Comment by PrzemyslawLukanowski** [comment]
Tak, tylko za pomocą [GET /sale/loyalty/promotions?user.id={Seller_ID}](https://developer.allegro.pl/documentation/#operation/listSellerPromotionsUsingGET_1) pobierzesz informacje o swoich promocjach. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/offer_bundles/#0).

**Comment by PrzemyslawLukanowski** [comment]
@aktywnitu możesz także skorzystać z publicznego zasobu GET /offers/listing, gdzie jako parametr przekażesz seller.id oraz parametr campaign, jak poniżej:

GET /offers/listing?seller.id={seller.id}&campaign=BARGAIN
