### ISSUE TITLE
Komunikat błędu niezgodny ze stanem faktycznym.

### ISSUE THREAD

**Issue by gemsnet** [allegro/allegro-api#2453]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Proszę o przyjrzenie się raportowanym błędom. Już nie po raz pierwszy otrzymuję komunikat 

> "Could not change offer publication status. Delivery price list may not be empty."

 podczas gdy błąd tkwił w zupełnie innym miejscu. np. podanie kodu pocztowego w formacie "51411" zamiast "51-411" spowoduje pojawienie się wspomnianego błędu o braku cennika dostawy.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id? Próbowałem odtworzyć ten błąd, ale w moim przypadku otrzymałem błąd "Could not change offer publication status. You cannot activate an invalid offer.".

**Comment by gemsnet** [comment]
Trace-ID: 3696013c-53fa-4afc-a3e5-a914aadbddc4

> Error:
> Code: ConstraintViolationException.NotNull
> Message: Delivery price list may not be empty.
> Details: Invalid value: null, Annotation: @javax.validation.constraints.NotNull(message={pl.allegro.offercore.offer.deliveryPriceList.NotNull}, payload=[], groups=[])

Request zawierał wszystkie dane prawidłowe poza formatem kodu pocztowego. Jego poprawienie rozwiązało problem.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy to - błędny kod pocztowy uniemożliwił utworzenie prawidłowego  cennika dostawy. Przekazałem ten problem do odpowiedniego zespołu.
