### ISSUE TITLE
Utworzenie draftu zamówienia | błąd 422

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#2454]
Dzień dobry,

Proszę o wyjaśnienie , dlaczego otrzymuję taki błąd:

{"errors":[{"code":"VALIDATION_ERROR","message":"Podaj nazwę oferty.","details":"","path":"","userMessage":"Podaj nazwę oferty."}]}

 w momencie wystawiania draftu(szkicu) z API. Przekazując takie dane:
{'offers': [{'name': 'TestAPI', 'category': {'id': '110251'}, 'status': 'INACTIVE'}]}

Dodam, iż połączenie z Allegro API itd mam poprawne, bo poprawnie otrzymuje wszystkie dane typu GET. To moja pierwsza próba wysyłania danych do Państwa za pomocą POST.

**Comment by PatrykBocian** [comment]
Błąd powoduje nieprawidłowo uzupełnione pole category oraz description.
Dla przykładu pole description powinno wyglądać tak:

![description](https://user-images.githubusercontent.com/56817097/67685571-9cf11780-f995-11e9-9ce7-f0439995e6a7.png)

a category:

![category](https://user-images.githubusercontent.com/56817097/67685604-abd7ca00-f995-11e9-995b-2a341c764ca6.png)


Więcej na ten temat znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) oraz [poradniku.](https://developer.allegro.pl/sale/)

**Comment by allmat** [comment]
@PatrykBocian 
Poprawione.
![obraz](https://user-images.githubusercontent.com/50575559/67688066-8cdb3700-f999-11e9-9b6b-0cc21de8b279.png)

W dalszym ciągu niestety błąd 422 z usrMssg: "Podaj nazwę oferty."

**Comment by kfijalko** [comment]
Wysyłasz tablicę "offers":[.
wyślij tylko zawartość jednego draftu.

**Comment by allmat** [comment]
@kfijalko 
Temat rozwiązany :) Dziękuję!

**Comment by SoftWareMG** [comment]
Dzień dobry,
A co tutaj może powodować błąd, od kilku dni mamy z tym problem, a nic nie zmienialiśmy w kodzie.
Pobieram draft z aukcji: 7352575119 a następnie na jego podstawie chcę wystawić nową aukcję.
Błąd: Serwer zdalny zwrócił błąd: (422) Unprocessable Entity.
taki mam json:

{"name":"Zakończenie Lewe do Listwy 70mm PCV DĄB EXCLUSIVE","category":{"id":"256179"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"130152","valuesIds":["130152_64"],"values":[],"rangeValue":null},{"id":"130151","valuesIds":[],"values":["70"],"rangeValue":null},{"id":"214982","valuesIds":["214982_268434"],"values":[],"rangeValue":null},{"id":"215022","valuesIds":["215022_268842"],"values":[],"rangeValue":null},{"id":"11325","valuesIds":["11325_2"],"values":[],"rangeValue":null}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>Kolor:</h2>\n<p>Dąb exclusive</p>\n<h2>Materiał:</h2>\n<p>PCV</p>\n<h2>Ilość:</h2>\n<p>1 szt.</p>\n<p>Kupując 1 sztukę otrzymają Państwo 1 element. Jeżeli potrzebują Państwo łącznie np. 10 dodatków, proszę zakupić 10 sztuk.</p>\n<p>Przedmiotem aukcji jest wyłącznie zakończenie lewe do listew przypodłogowych PCV 70mm.</p>\n<p>Zakończenia prawe, łączniki, narożniki zewnętrzne oraz narożniki wewnętrzne znajdą Państwo na naszych pozostałych aukcjach.</p>\n<p>Kategoria produktu: LP70DABEXZL</p>"},{"type":"IMAGE","url":"https://8.allegroimg.com/original/032234/ae04459a42fc80657cb4c7e31ce8"}]},{"items":[{"type":"IMAGE","url":"https://6.allegroimg.com/original/033d7a/fa95f14c4081b557c6545ecc7836"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://8.allegroimg.com/original/032234/ae04459a42fc80657cb4c7e31ce8"},{"url":"https://6.allegroimg.com/original/033d7a/fa95f14c4081b557c6545ecc7836"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"2.75","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":9975,"unit":"UNIT"},"publication":{"duration":null,"startingAt":null,"endingAt":null,"endedBy":null,"republish":true},"delivery":{"shippingRates":{"id":"e0a0f2f2-cf7a-4e99-8e3b-d89eaa83e90a"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"85815382-d6e8-4b57-af86-dfda2f5518e7"},"returnPolicy":{"id":"df0ba005-8b86-4731-a3a2-1497ed4e7fcb"},"warranty":{"id":"2ea8b860-9033-4d57-a414-1b0c01e46a87"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"ZACHODNIOPOMORSKIE","city":"Police","postCode":"72-010"},"external":null,"attachments":[],"contact":null,"createdAt":"2018-05-17T11:31:00.000Z"}

**Comment by PatrykBocian** [comment]
@SoftWareMG Sprawdziłem twój kod, musisz usunąć pole "createdAt". Wtedy draft utworzy się prawidłowo.

**Comment by SoftWareMG** [comment]
Ok, dzieki, zweryfikuje. 
A to problem wynikal z tego ze u was cos sie zmienilo? Czy moze ze poprostu to jakos dzialalo, bo z takim json tak juz z 9 miesiecy dzialalismy. 
--
Wysłano z aplikacji myMail dla Androida środa, 30 października 2019, 07:37AM +01:00 od PatrykBocian  notifications@github.com :

**Comment by PatrykBocian** [comment]
@SoftWareMG  Nic nie zmienialiśmy. Przy tworzeniu draftu nigdy nie można było dodawać "createdAt"

**Comment by SoftWareMG** [comment]
Ok, dzięki za info. Wieczorem zweryfikuje. 
--
Wysłano z aplikacji myMail dla Androida środa, 30 października 2019, 07:56AM +01:00 od PatrykBocian  notifications@github.com :
