### ISSUE TITLE
Problem danymi klienta do fvat

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2455]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ x] inny

Piszę tutaj bo nie bardzo wiem gzie.
Problem dotyczy danych przy składaniu zamówienia przez klienta.

w sytuacji gdy klient wybiera że chce fvat i wypełnia

nazwa firmy ( swoim imieniem i nazwiskiem) nipu nie podaje a w imię i nazwisko nic nie wpisuje

Taki formularz nie powinien przejść w allegro.  

Powinno być coś takiego jak 
wpisany nip to dopiero pokazuje się możliwość wpisania nazwa firmy   jak nie poda nipu to nie może podać nazwy firmy wtedy problemu by nie było.

Dodatkowo nie lepiej wdrożyć połączenie z gus lub teraz "białą księgą "? Klient chce fvat wpisuje nip i nic więcej nie wpisze nipu ma vat na dane z dostawy a jeszcze lepiej tylko na dane takie jak założył konto w allegro - przecież nie można używać cudzego konta w allegro :D A adres dostawy to tylko adres dostawy może być do sąsiada :)

**Comment by PatrykBocian** [comment]
Twoje wątpliwości dotyczą funkcjonowania serwisu, a nie samego API. W obecnej wersji serwisu WWW dla firmy zwracamy tylko pole Firma, a dla faktury dla osoby prywatnej - Imię i nazwisko. Nie ma więcej pól. Korzystając z Allegro można zamawiać z konta A towary na adres B jakiejś firmy - nie ma tu nic niezgodnego z regulaminem.

**Comment by frankii91** [comment]
dziwne jakimś cudem api zwróciło mi nazwę firm bez nipu i bez imienia i nazwiska  może tak być ?

**Comment by PatrykBocian** [comment]
Jest to możliwe, podobny błąd może występować przy wystawianiu oferty przez starą wersje aplikacji mobilnej na iOS. Jeśli chodzi o twój przypadek, potrzebowałbym więcej danych, aby zweryfikować czy to na pewno ta sama sytuacja. Możesz potrzebne informacje przez nasz formularz kontaktowy.
