### ISSUE TITLE
Darmowa dostawa

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2456]
Czy coś się zmieniło i Darmowa dostawa od kwoty X w dalszym ciągu obowiązuje dla całego konta ?

Czy może dla danego cennika dostaw ?

Jeśli dla całego konta to czy jest przewidziana zmiana tej opcji aby była możliwość zarządzania ty parametrem? Najlepiej opcja niezwiązana z cennikami dostawy (tylko robienie grup produktów i określanie grupa x darmowa dostawa od Y,  bez limitu ilości tych grup)

**Comment by PatrykBocian** [comment]
Tutaj nic się nie zmieniło, darmowa dostawa nadal obowiązuje dla całego konta.
Pojawiły się już związane z tym sugestie, zgłosiliśmy je do odpowiedniego zespołu, dziękujemy.
