### ISSUE TITLE
Wymuszenie przelogowania w linkach do panelu Allegro

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2457]
:bulb: **Sugestia**

W naszym Panelu mamy linki do sprawdzenia zamówień/płatności w jaki sposób wyglądają w panelu Allegro. Wszystko by było dobrze, gdybyśmy nie posiadali kilku kont. Często mamy sytuację, że w przeglądarce ktoś jest już zalogowany na konto X, a klika na linka do panelu Allegro dla np. zamówienia z konta Y. Strona oczywiście się otwiera, lecz informuje o braku takiego zamówienia - co jest w tym wypadku prawdziwe. Czy nie dałoby się dodać po Państwa stronie obsługi parametru, np. loginUserId=Y - czyli sprawdzanie, czy w aktualnej sesji jest zalogowany uzytkownik Y. Jeżeli nie, to wylogowanie aktualnego użytkownika, przekierowanie (wraz z adresem powrotnym) na stronę logowania celem zalogowania się już jako inny użytkownik.

**Comment by PatrykBocian** [comment]
Dziękujemy za sugestię, przekażemy ją do odpowiedniego działu.
Jeśli wprowadzimy takie zmiany, poinformujemy o tym w odpowiednim komunikacie.
