### ISSUE TITLE
Błąd logowania na sandboxie

### ISSUE THREAD

**Issue by seph84** [allegro/allegro-api#2458]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Założyłem dziś konta na sandboxie. Niestety serwis nie pozwala mi się na nie zalogować. Cały czas dostaję "Login, e-mail lub hasło są nieprawidłowe"

**Comment by PatrykBocian** [comment]
Możesz podesłać przykładowy login na który próbujesz się zalogować?
Pomoże to zweryfikować czy konto na pewno jest aktywne.

**Comment by docc46** [comment]
W ostatnich dniach sandbox bardzo kiepsko działa. Wczoraj nie mogłem utworzyć nowego konta, dzisiaj to się udało jednak po zatwierdzeniu zakupu i formularza dostawy nie otwiera się okno symulacji płatności, przez co nie mogę dokończyć żadnego zakupu.

**Comment by seph84** [comment]
Po napotkaniu problemów z utworzeniem użytkownika postanowiłem podziękować sandboxowi i testuję na produkcji.

**Comment by PatrykBocian** [comment]
@docc46  Co do symulacji płatności, wystąpiły z tym problemy w dniu wczorajszym, lecz teraz wszystko działa prawidłowo. Czy u Ciebie taki problem nadal występuje? W temacie wystawiania oferty, prześlij proszę pełny curl takiego requesta, pomoże to nam zweryfikować ten problem.
