### ISSUE TITLE
Zasób REST API /sale/shipping-rates - brakujące metody POST i PUT

### ISSUE THREAD

**Issue by karolus888** [allegro/allegro-api#246]
Witam,

W tutorialu "Jak wystąwić ofertę", dostepnym pod adresem https://developer.allegro.pl/sale/#rest-api widzę, że w przypadku wystawiania oferty przez zasób /sale/offers można jedynie przekazać identyfikator cennika dostawy, pobranego z zasobu /sale/shipping-rates.
Problem w tym, że cenniki można obecnie tworzyć jedynie przez serwis Allegro, nie widzę metod POST i PUT dla zasobu /sale/shipping-rates.
Prośba o udostępnienie tych metod lub umożliwienie przekazania indywidualnego cennika dostawy dla oferty (bez wskazywania ID istniejącego cennika).

Pozdrawiam,
Karol Sikora

**Comment by MarcinLuczak** [comment]
@karolus888 w tej chwili w REST API nie udostępniamy takich metod ani możliwości zdefiniowania opcji dostawy osobno.

**Comment by karolus888** [comment]
Czy takie metody pojawią się w najbliższej przyszłości? Nie ukrywam, że korzystanie z nowych zasobów do wystawiania oferty będzie utrudnione bez możliwości utworzenia nowego cennika dostawy / edycji instniejącego przez REST API.

**Comment by MarcinLuczak** [comment]
@karolus888 Trudno mi powiedzieć. Jeśli takie zasoby powstaną, poinformujemy o tym w [aktualnościach](https://developer.allegro.pl/news/) na portalu developerskim.
