### ISSUE TITLE
Upload dużej ilości zdjęć jednocześnie do Allegro

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2460]
Dzień dobry, chciałbym wrócić do pytania ze zgłoszenia #2214 . Otóż tamte odpowiedzi średnio wyczerpały mój problem, a nadal się z nim borykam.

Przedstawię pokrótce sytuację. Wystawiam w formie asynchronicznych zadań aukcje do Allegro. Każde z zadań wykonuje również asynchronicznie upload zdjęć, każde jako osobne zadanie (od 2 do 7). Jednakże niezależnie od narzuconej ilości jednocześnie wystawiających się aukcji, nie jestem w stanie wysycić łącza. Jedyne, co rośnie z ilością asynchronicznych wystawień, jest długość trwania uploadów i to na dodatek dosyć proporcjonalnie. Na dodatek wykresy na naszym łączu wskazują, że około 100 zadań uploadu, które działają w tym czasie w większości się nudzi. Tak jakby tylko część zadań mogła uploadować zdjęcia, a pozostałe z kolei musiały czekać na to, kiedy na łączu jest wciąż zapas.

![obraz](https://user-images.githubusercontent.com/37104952/67764911-3a5a5300-fa4b-11e9-866e-ad6300aac903.png)

Jak widać na wykresie, na łączu widzimy pokaźne skoki prędkości uploadu, a sam upload 5 plików JPG o wielkości ok. 100 kB trwa przy obciążeniu przykładowych 100 zadań uploadu średnio około 70 sekund. Staramy się przesyłać jak najmniej, ostatnio skompresowaliśmy zdjęcia, jednak czas zmniejszył się o 10%. Zdecydowanie nie jest to normalne zachowanie. Z tego, co zauważyłem, jest nowa informacja o użyciu przez was algorytmu Leaky Bucket i jego specyfika działania bardzo przypomina obserwowane przez nas zachowanie. 

Chciałbym prosić o szczegółowe wyjaśnienia jak działa upload zdjęć w REST API, oraz jak wystawić 40.000 aukcji na dobę? W obecnym tempie nie jesteśmy w stanie wystawić 20.000 aukcji w ciągu doby.

**Comment by PatrykBocian** [comment]
Weryfikuje tę sprawę, jak tylko się czegoś dowiem przekażę odpowiednie informacje.

**Comment by PatrykBocian** [comment]
Wygląda to jakby po państwa stronie istniał limit na puli połączeń.
Trzeba pamiętać, że upload zajmuję trochę czasu, a np. mając kilka połączeń, może zaistnieć sytuacja gdy na jednym takim połączeniu może iść jeden request w danym momencie.
Co do Leaky Bucket, nie jest on wykorzystywany przy zdjęciach, aplikują się tutaj standardowe limity.

**Comment by Nebuli1** [comment]
Opisany problem występuje również przy dobrych łączach- światłowód 100Mb/s wysyłania i nie da się go wysycić więcej niż 10% łącza. Takie same piki przy uploadzie. Szybka wysyłka(pik w uploadzie na wykresie) i długie oczekiwanie na odpowiedź z waszej strony. 

        Proszę o rozwinięcie myśli i jej dokładne techniczne opisanie: "może zaistnieć sytuacja gdy na jednym takim połączeniu może iść jeden request w danym momencie."

**Comment by PatrykBocian** [comment]
@Nebuli1  
Małe sprostowanie z mojej strony. Chodzi o to że nawiązując z nami jedno połączenie w danej chwili możemy wysłać jeden request. Czyli w tym przypadku przy jednym połączeniu przesyłamy naraz jedno zdjęcie. Oczywiście można mieć z nami więcej połączeń lecz na każde osobne  połączenie przypada  tylko jeden request (pojedyncze zdjęcie).

**Comment by Nebuli1** [comment]
Dla prostoty spróbuję wyjaśnić na przykładzie: upload 10 zdjęć = 4 sek uploadu i 6 sek oczekiwania na odpowiedź, dla 100 zdjeć =40 sek uploadu i 70 sek oczekiwania na odpowiedź. Nie ma to nic wspólnego z limitem połączeń, my nie mówimy tu o 10000 połączeń, chociaż nasz Mikrotik RouterOS sobie bez problemu radzi z takim obciążeniem.

**Comment by PatrykBocian** [comment]
@Nebuli1  99% requestów i upload zdjęć kończy się u nas w czasie mniejszym niż 5s a 75% w mniej niż 800 ms.
Sprawdziłbym czy nie występuje jakiś problem po Państwa stronie, np. Odpowiedź na request już dawno przyszła ale nie ma wolnego wątka do obsługi odpowiedzi. Po naszej stronie nie obserwujemy żadnych problemów.

**Comment by Nebuli1** [comment]
Witam. Rozumiem sęk w tym, że wystawienie jednej aukcji z 6 zdjęciami zajmuje czas 4800ms co daje możliwość wystawienia 750 aukcji na godzinę/ 18 000 aukcji na dobę. W WebApi z racji braku potrzeby uploadowania zdjęć na wasz serwer wykonując upload zdjęcia na nasz serwer ftp osiągaliśmy bez problemu wydajność 10 000 aukcji na godzinę dla pojedynczego konta. Wystawiając aukcje asynchronicznie nie możemy przekroczyć progu 1000 aukcji na godzinę przy uploadzie 5 zdjęć do aukcji.

Czy może mi Pan odpowiedzieć jaki jest u Pana czas uploadu 100 zdjęć asynchronicznie?

**Comment by BABYBOOM-SERWIS** [comment]
Rozumiem że zdjęcia które pobieracie są na zewnętrznym serwerze? wg mnie to może być problem z ilością requestów do waszego serwera (jak to jakiś hosting to pewnie ma ograniczenia ustawione). 
Wystarczy ze apache lub ngix ma ustawione limity i czeka aż się zwolni wolne miejsce na request.

**Comment by Nebuli1** [comment]
Nie, zdjęcia są przechowywane lokalnie na dysku twardym. W starym Webapi używaliśmy zewnętrznych serwerów ftp. W restApi jest to niedozwolone.

**Comment by hahyes** [comment]
> Czy może mi Pan odpowiedzieć jaki jest u Pana czas uploadu 100 zdjęć asynchronicznie?

@PatrykBocian Interesuje mnie odpowiedź na zacytowane pytanie powyżej. Czy uzyskałbym odpowiedź?

**Comment by PatrykBocian** [comment]
@hahyes Sprawdzałem upload 100 obrazków, z mojego dysku zajmuje mi ok. 1,5 sekundy na allegro.pl, ok. 6-7 sekund na allegrosandbox. Upload robiłem na 25 wątkach.
Robiłem to na obrazku https://en.wikipedia.org/wiki/File:Example.jpg. Dla większych obrazków czas może być oczywiście trochę dłuższy.

@Nebuli1  W WebAPI każdy obrazek musiał zostać wgrany na nasz serwer, różnica polegała na tym, że wszystkie musiały być podane w base64 do metody doNewAuctionExt. REST API nic nie zmieniło w tym względzie oprócz tego, że dodaliśmy dodatkowo możliwość pobierania obrazka z zewnętrznego serwera poprzez podanie URL. W WebAPI nie było opcji pobierania obrazków z adresu FTP.

**Comment by dzisdobrydzien** [comment]
Czy mógłbym Pana prosić o zbadanie czasu wystawienia dla:
Wariant 1. 100 aukcji z 5 zdjęciami 400KB w jednym wątku,
Wariant 2. 100 aukcji z 5 zdjęciami 400KB w 10 wątkach. 
Wariant 3. 100 aukcji z 5 zdjęciami 400KB w 20 wątkach. 

Oraz jakich prędkości łączem test został wykonany?

**Comment by PatrykBocian** [comment]
@dzisdobrydzien   Na GitHubie wspieramy użytkowników w sprawie problemów i wątpliwości związanych z korzystaniem z naszego API. Nie prowadzimy wsparcia w sprawie testowania wydajności funkcjonalności.
W tym przypadku wyniki mogą się różnić w zależności od infrastruktury w której się poruszamy, dlatego też nie wykonujemy takich testów. Gdybyś miał kłopoty z korzystaniem z naszych zasobów lub któryś działałby nieprawidłowo, wtedy jesteśmy do twojej dyspozycji.
