### ISSUE TITLE
Powiadomienia o zdarzeniach na koncie użtkownika

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2461]
:bulb: **Sugestia**

Chciałbym zasugerować developerom Allegro możliwość wprowadzenia powiadomień wysyłanych przez Allegro do właściciela konta kiedy np. klient dokona płatności albo podobnych operacji.

**Takie powiadomienia byłyby wysyłane na ustalony wcześniej URL.**

Aktualny zasób https://api.allegro.pl/order/events musi być odpytywany przez apkę użytkownika i generuje zbędny ruch na serwerach Allegro. 

**Zamiana na powiadomienia wysyłane przez Allegro w momencie zdarzenia zwiększy wydajność po obu stronach.**

Takie rozwiązania są zaimplementowane w API [payPal](https://developer.paypal.com/docs/notifications/) oraz [eBay](https://developer.ebay.com/devzone/guides/features-guide/default.html#Notifications/Notifications.html)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię, przekazuję ją do działu odpowiedzialnego za rozwój API.

**Comment by Onixarts** [comment]
Tylko, żeby to również na desktopach mogło działać - jeśli już byście się podejmowali takiego zadania.
