### ISSUE TITLE
Wysłanie parametrów w momencie tworzenia aukcji - inactive

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#2462]
Witam,

Tworzę draft oferty na POST /sale/offers.
W jaki sposób tworząc aukcję przesłać dane do parametrów? 
W dokumentacji w JSON widzę tylko id i values parametrów, ale nie za bardzo widzę skąd moge pobrać (id), aby uzupełnić przez api np. producenta tarczy hamulcowej itp

**Comment by PrzemyslawLukanowski** [comment]
Wszystkie dostępne id parametrów oraz ich wartości w wybranej kategorii sprawdzisz za pomocą zasobu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by allmat** [comment]
Dziękuję
