### ISSUE TITLE
Problem z zamykaniem/wznawianiem aukcji

### ISSUE THREAD

**Issue by maczking** [allegro/allegro-api#2463]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
Mamy problem przy tworzeniu mechanizmu zabezpieczającego, który pilnuje aby pobrane statusy aukcji były zgodne z rzeczywistymi, jednak zauważyliśmy problem, który występuje zarówno od strony obsługi z poziomu sandboxa jak i po wysłaniu requesta z wykorzystaniem REST API. Dosyć często pojawia się problem, że nie można wznowić aukcji jak w przypadku aukcji o numerze 6206696929 czy tej 6206636211(mimo wielokrotnych prób w sandboxie i z wykorzystaniem API). Innym razem pojawia się problem z tym, że aukcja na liście jest już jako "aktywna" a przez kilka godzin sama aukcja posiada komunikat "sprzedaż zakończona". Czy jesteście Państwo w stanie odpowiedzieć co może być przyczyną?

**Comment by PrzemyslawLukanowski** [comment]
W celu weryfikacji zgłoszenia potrzebujemy więcej szczegółów. Jaki konkretnie komunikat otrzymujesz w odpowiedzi na [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET)? Możesz nam przesłać przykładowe requesty (w formacie cURL) i respone przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) wraz z dopiskiem GitHub #2463.
