### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by MarekCiecharowski** [allegro/allegro-api#2465]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuje wykonać autoryzację, niestety mam ciągle błąd taki jak w temacie.
Kod źródłowy:

            var client = new RestClient("https://allegro.pl");
            var request = new RestRequest
            {
                Method = Method.POST,
                Resource = "auth/oauth"
            };
            string idks = ClientId + ":" +ClientSecret;
            byte[] bajty = System.Text.Encoding.UTF8.GetBytes(idks);
            string auth = "Basic " + Convert.ToBase64String(bajty);
            request.AddHeader("Authorization", auth);
            request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.RequestFormat = DataFormat.Json;
            var response = client.Execute(request);

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.

Sugestia z mojej strony - w Resource zamiast auth/oauth przekaż auth/oauth/token.

**Comment by MarekCiecharowski** [comment]
Nadal błąd, tym razem: StatusCode: 401 - Unauthorized.
Czy możesz sprawdzić czy konto jest aktywne? Login to Lemonbite.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem - tak, konto jest aktywne. Status 401 wskazuje na błąd w przesłanych ClientId i ClientSecret, upewnij się, że przekazujesz prawidłowe dane. Prześlij proszę Twój request (w formacie danych cURL) za pomocą naszego [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt) z dopiskiem GitHub #2465. Pomoże to nam zweryfikować ten przypadek.
