### ISSUE TITLE
Wysyłka zdjęcia | REST API

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#2466]
Witam,

Mam przygotowaną pełną ofertę przez API do wysyłki. Brakuje mi tylko zdjęć.
W jaki sposób wysłać zdjęcie z komputera w postaci: C:/Users/uzytkownik/zdjecie.png do Allegro API?

**Comment by kfijalko** [comment]
https://developer.allegro.pl/

**Comment by PatrykBocian** [comment]
Aby dodać zdjęcie musisz je przesłać na nasz serwer i pobrać jego url.
Możesz to zrobić za pomocą zasobu POST /sale/images w postaci linku lub binarnie.
Więcej na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/sale/#step-3-images) oraz [dokumentacji](https://developer.allegro.pl/documentation/#tag/Images-and-attachments).

**Comment by allmat** [comment]
W momencie przekazania C:/Users/uzytkownik/zdjecie.png jako tekst do:
dane = {
                        "url":zdjecie
                        }
na adres: 'https://upload.allegro.pl/sale/images'

Otrzymuję błąd " {"errors":[{"code":"UnprocessableEntity","message":"Unprocessable entity","details":null,"path":null,"userMessage":"Niepoprawny adres URL."}]} "

**Comment by PatrykBocian** [comment]
Jeżeli chcesz przesłać zdjęcie, które posiadasz u siebie na dysku, musisz to zrobić w postaci binarnej. Dla sposobu, który wybrałeś, potrzebny jest konkretny link do zdjęcia a nie wewnętrzna ścieżka.

**Comment by allmat** [comment]
@PatrykBocian 
Czyli podstawiam to w ten sposób { "url":"data:image/png;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD/4QikRXhpZgAATU0AKgAAAAgABwESAA"} ?

**Comment by PatrykBocian** [comment]
Przykładowy request na wrzucenie zdjęcia: 
![pasted image 0](https://user-images.githubusercontent.com/56817097/67954487-5c8dd580-fbf1-11e9-8f6f-59c52e520957.png)

**Comment by allmat** [comment]
@PatrykBocian 
co to znaczy --data-binary ...
mogę to przekazać za pomocą json'a ? w postaci:
data = { 
            "data-binary": "@plik.png"
}
nie za bardzo rozumiem na podstawie waszego przykładu , jak mogę dołączony plik wysłać do Was.

**Comment by PatrykBocian** [comment]
Wysyłając zdjęcie w postaci binarnej musisz podać ścieżkę, gdzie znajduje się ten plik.
To jak możesz to zrobić zależy od sposobu w jaki komunikujesz się z API, czy przez program (wtedy zapewne jest tam opcja wskazania pliku, który chcesz przesłać) czy np. pisząc w konkretnym języku programowania. Dla przykładu poniżej metoda dodania zdjęcia w curlu:

```
curl -X POST \
 ’https://upload.allegro.pl/sale/images’
 -H ‘Authorization: Bearer {token}’ \
 -H ‘Accept: application/vnd.allegro.public.v1+json’ \
 -H ‘Content-Type: “image/jpeg”
 -H ‘Accept-Language: pl-PL’,
--data-binary “/example/file/url.jpg
```

**Comment by hahyes** [comment]
> 
> 
> @PatrykBocian
> co to znaczy --data-binary ...
> mogę to przekazać za pomocą json'a ? w postaci:
> data = {
> "data-binary": "@plik.png"
> }
> nie za bardzo rozumiem na podstawie waszego przykładu , jak mogę dołączony plik wysłać do Was.

Musisz wczytać plik w postaci bajtów (czyli binarnej) i w takiej właśnie postaci wysłać plik.
Nie wiem, w jakim języku to piszesz, więc więcej nie pomogę.
