### ISSUE TITLE
Automatyczne łączenie wielowariantowości po stronie Allegro koliduje z API

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#2467]
Czy jest możliwość, aby chętni Użytkownicy wyłączyli automatyczne łączenie w wielowariantowość:
https://allegro.pl/dla-sprzedajacych/wprowadzamy-automatyczne-laczenie-ofert-w-oferty-wielowariantowe-EYWkzVmdOsD#kategorie-w-ktorych-wprowadzimy-automatyczne-laczenie-ofert-kliknij-aby-rozwinac-liste-

Niestety łączenie to nie zawsze jest takie jaki oczekują tego Sprzedawcy. A połączone w wielowariant oferty blokują oprogramowania API, które mogą zrobić to lepiej.

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości. Użytkownik może jedynie rozłączyć utworzone oferty wielowariantowe.

**Comment by aktywnitu** [comment]
A po jakich dokładnie akcjach Allegro dokonuje automatycznej próby połączenia ofert?

**Comment by imper86** [comment]
@aktywnitu sugerowałem tutaj #2328 - aby zrobili chociaż filtry odpowiednie do GET /offer/variants no ale zanim się coś ruszy w temacie to się klienci zaklikają na śmierć na froncie.

**Comment by aktywnitu** [comment]
@PrzemyslawLukanowski , czy jest sposób, aby odróżnić wielowariant połączony automatycznie od wielowariantu utworzonego przez przeglądarkę lub API?

**Comment by PrzemyslawLukanowski** [comment]
Rozpoznasz je po nazwie - oferty wielowariantowe połączone automatycznie dziedziczą nazwę po jednej z ofert, która wchodzi w skład wielowariantu. Dla ofert utworzonych przez przeglądarkę lub API, nazwę nadajesz we własnym zakresie.

**Comment by aktywnitu** [comment]
Nie jest to na pewno jednoznaczne. Rozumiem, że nazwa jest ucinana do 40 znaków, tak?

**Comment by PrzemyslawLukanowski** [comment]
Limit dla nazwy oferty wielowariantowej to 50 znaków. Na froncie nie wprowadzisz dłuższej, w API otrzymasz odpowiedni błąd. Twoją sugestię przekazałem odpowiedniemu zespołowi.

**Comment by aktywnitu** [comment]
Rzeczywiście, limit jest na 50 znaków, ale zdaje się, że kiedyś był większy, gdyż otrzymuję czasem błąd: "Limit dla nazwy oferty wielowariantowej to 50 znaków."

Prosiłbym przekazać również prośbę o dodanie daty i czasu utworzenia wielowariantu
A najlepiej, gdyby jednak automat nie łączył automatycznie w wielowariant. Lepiej opracować do tego narzędzie, w którym Sprzedawca musiałby zatwierdzić propozycje zmian w wielowariantach.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem spostrzeżenia.

**Comment by PrzemyslawLukanowski** [comment]
@aktywnitu Czy możesz przedstawić nam swoją potrzebę? Jaki problem chciałbyś rozwiązać przez dodatkowe informacje o czasie utworzenia oferty i sposobie połączenia oferty wielowariantowej? Czy możesz podać konkretny przykład, w którym połączyliśmy oferty wbrew oczekiwaniom sprzedawcy?
