### ISSUE TITLE
Błąd w dokumentacji (różnie opisane dopłaty) w /order/checkout-forms

### ISSUE THREAD

**Issue by zawadzki14** [allegro/allegro-api#2468]
Witam,
Pole z kwotą **dopłaty** jest różnie opisane. W dokumentacji (https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) jest **paidAmount** , natomiast w poradniku (https://developer.allegro.pl/orders/) jest **price** .
Proszę o ujednolicenie ponieważ chciałem to zaprogramować bez symulacji i nie wiem które pole jest poprawne. Podejrzewam , że prawdę mówi dokumentacja czyli -> paidAmount

**Comment by PatrykBocian** [comment]
Dziękujemy za zgłoszenie, w poradniku faktycznie była niezgodność - już to poprawiliśmy.
