### ISSUE TITLE
Status zamówienia

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2469]
Czy istnieje możliwość zmiany statusu zamówienia poprzez rest api np. z (w realizacji) na (wysłane), a jeżeli tak to jakim requestem?

**Comment by zawadzki14** [comment]
To samo pytanie zadałem kilka dni temu: https://github.com/allegro/allegro-api/issues/2426

**Comment by SaintRaphaelBass** [comment]
Ok, dzięki
