### ISSUE TITLE
Numery katalogowe zamienników - problem podczas edycji

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#247]
1. Dodaje aukcje przez webapi, ustawiam fid 39623 (numery katalogowe zamienników) jako string "FILTRON: 12345, CUK: 58185, MANN: 54872, MAPCO - 56997875 254, VW: 96581" w rezultacie wszystko ok, na aukcji się ładnie pokazuje. Problem natomiast pojawia się jak wejdę w formularz edycji aukcji, cały powyższy string ląduję w jednym inpucie zamiast kilku w rezultacie brak możliwość edycji aukcji do momentu ręcznego podziału (przekroczona dopuszczalna ilość znaków).

2. W formularzu do wystawiania aukcji można maksymalnie wpisać 10 numerów, a każdy po 30 znaków. Następnie łączycie to w jednego stringa oddzielając wartości przecinkiem i spacją. Podczas dodawania przez api fid 39623 może przyjąć maksymalnie 310 znaków gdy powinien 318.
Same wartości 10 x 30 znaków = 300 plus 9 x 2 znaki (znak przecinka i spacji) = 18 (nie licząc ostatnich)

mam nadzieję, że w miare zrozumiale to napisałem ;) Pozdrawiam

**Comment by MarcinLuczak** [comment]
@dlis2010 
> mam nadzieję, że w miare zrozumiale to napisałem ;)

No właśnie nie bardzo :)

> 1. Dodaje aukcje...

Dla jakiej kategorii? Gdzie to się pojawia w ofercie? Masz przykładową ofertę, gdzie to widać i gdzie dzieje się to co opisałeś?

> 2. W formularzu do wystawiania...

Drugi punkt nawiązuje do pierwszego. Wytłumacz proszę dokładnie co robisz i co się dzieje, bo niestety Twój opis jest zbyt lakoniczny.

**Comment by dlis2010** [comment]
chyba to jednak błąd po mojej stronie.
niemniej jednak - kategoria motoryzacja ma możliwość ustawienia fidu 39623 (numery zamienników).
Wystawiając aukcje przez formularz mamy maksymalnie 10 inputów które łącznie lądują w powyższym fidzie.

Pytanie moje: jak dodając ofertę przez webapi porozdzielać wartości w powyższym fidzie tak aby podczas edycji oferty przez formularz pojawiały się w osobnych inputach?

**Comment by dlis2010** [comment]
Niestety to ja przekombinowałem, mój błąd - przyznaje się i przepraszam za zamieszanie.

Powyższe wynikało z faktu iż kolejne wartości w fidzie 39623 (numery katalogowe zamienników) myślałem, ze są rozdzielane przecinkami. Separatorem jednak okazał się znak końca lini.

Pomogło:
```

Powyższe wynikało z faktu iż kolejne wartości w fidzie 39623 (numery katalogowe zamienników) myślałem, ze są rozdzielane przecinkami. Separatorem jednak okazał się znak końca lini.

Pomogło poniższe (https://allegro.pl/webapi/news.php#news_100607): 

> Jak wysłać parametry typu string w metodach doNewAuctionExt i doChangeItemFields 
> 
> <item>
> <fid>27986</fid>	
> <fvalueString>1 element	
> 2 element	
> 3 element	
> </fvalueString>
> </item>

**Comment by MarcinLuczak** [comment]
Cieszę się, że wszystko się wyjaśniło.

**Comment by dlis2010** [comment]
Witam ponownie,

panie Marcinie niestety pomimo usilnych starań, żaden sposób łamania linii nie pozwala mi dodać kilku numerów. Za każdym razem wszystkie wartości lądują w jednym inpucie podczas edycji oferty per formularz.

Mówimy o fidzie 39623 (numery katalogowe zamienników) - kategorie części samochodowych

**Comment by MarcinLuczak** [comment]
@dlis2010 faktycznie jest coś na rzeczy. Analizujemy ten problem.

**Comment by dlis2010** [comment]
Witam, panie @MarcinLuczak udało się coś zdziałać?

**Comment by MarcinLuczak** [comment]
@dlis2010 jeszcze działamy, ale nie powinno to długo potrwać.

**Comment by dlis2010** [comment]
@MarcinLuczak wciąż czekamy ;)

**Comment by PawelTaberski** [comment]
Prace jeszcze trwają najprawdopodobniej do końca tego tygodnia problem powinien zostać rozwiązany.
