### ISSUE TITLE
Pytanie 

### ISSUE THREAD

**Issue by Cthulhulove** [allegro/allegro-api#2470]
Widzę, że od dziś zmuszacie do wystawiania zwykłych użytkowników przez allegrolokalnie w związku z tym mam pytanie, czemu oferty wystawiane przez Allegrolokalnie ale widoczne z opcją Kup Teraz w allegro nie są widoczne w dzienniku zdarzeń?  Natomiast oferty pobierane przez listing (od osób prywatnych) odsyłają do aukcji które nie istnieją (nadawany jest im numer aukcji która nie istnieje i dopiero ręcznie wpisanie w wyszukiwarkę odnajduje ofertę

**Comment by Cthulhulove** [comment]
Ponadto dziennik ma ponad godzinę opóźnienia. To jakaś awaria?

**Comment by MaciejFrackowiak** [comment]
Oferty wystawione przez Allegro Lokalnie nie będą widoczne w dzienniku zdarzeń Allegro, to dwa osobne serwisy. Oferty z Allegro Lokalnie mają także osobny zakres identyfikatorów i de facto na listingu Allegro są tylko zamieszczone przekierowania do Allegro Lokalnie, a nie oferty. Natomiast odnośnie dzienników - nie mam żadnych informacji o wystąpieniu opóźnień.
