### ISSUE TITLE
Propose a product gives error ConstraintViolationException 

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#2471]
Like this i'm sending a data for product listing but gives error

{"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Offer description<\/p>"}]}]},"eans":["892685001003"],"name":"Scenery","category":{"id":"91458"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1107e8\/2194c3fe432f80be7d50c67dfb3c"}],"parameters":[{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":223545,"valuesIds":[],"values":[],"rangeValue":{"from":"0","to":"J J"}},{"id":223489,"valuesIds":[],"values":[],"rangeValue":{"from":"0","to":"Chandra"}},{"id":223541,"valuesIds":["223541_302861"],"values":[],"rangeValue":null},{"id":7773,"valuesIds":["7773_1"],"values":[],"rangeValue":null},{"id":74,"valuesIds":[],"values":[],"rangeValue":{"from":"0","to":"2019"}},{"id":17448,"valuesIds":[],"values":[],"rangeValue":{"from":"0","to":"10"}}]}

errors] => Array
        (
            [0] => Array
                (
                    [code] => ConstraintViolationException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Unprocessable entity. Please contact the application author.
                )

        )

**Comment by PrzemyslawLukanowski** [comment]
There are few issues with your request:

- invalid html in description section, missing opening p tag. More information about this section you will find in [our guide](https://developer.allegro.pl/en/sale/#step-5-description),
- uncorrect parameters values (223545, 223489, 74, 17448), it should look like below:
```
{
	"id": 74,
	"values": [
		"2019"	
	],
}
```

In [our guide](https://developer.allegro.pl/en/productization/#add) you can the find right examples.

Are you sure you want to propose a new product? Or you want to list a standard offer? Take a look at our guides for these two processes:
- [how to list an offer](https://developer.allegro.pl/en/sale/#rest-api),
- [how to create a product](https://developer.allegro.pl/en/productization/#add).

**Comment by 07adityasingh** [comment]
Same issue while sending correct data
{"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>opis tekstowy<\/p>"}]}]},"name":"Scenery","category":{"id":"91458"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1107e8\/2194c3fe432f80be7d50c67dfb3c"}],"parameters":[{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":223545,"valuesIds":[],"values":["J J"],"rangeValue":null},{"id":223489,"valuesIds":[],"values":["Chandra"],"rangeValue":null},{"id":223541,"valuesIds":["223541_302861"],"values":[],"rangeValue":null},{"id":7773,"valuesIds":["7773_305805"],"values":[],"rangeValue":null}]}Array

**Comment by PrzemyslawLukanowski** [comment]
There is still missing opening p tag in your description section. Also, you need to remove all the fields: values, valuesIds and rangeValue from parameters sections, that don't contain any value. It should look like this:
```
"parameters": [
{
	"id": "11323",
	"valuesIds": ["11323_1"]
}, {
	"id": "223545",
	"values": ["J J"]
}, {
	"id": "223489",
	"values": ["Chandra"]
}, {
	"id": "223541",
	"valuesIds": ["223541_302861"]
}, {
	"id": "7773",
	"valuesIds": ["7773_305805"]
}]
```
If you want to create a product in this category, you need to provide all required parameters. In your case - parameter 74 is missing.

**Comment by 07adityasingh** [comment]
I'm sending p tag but here it is missing while paste.
But working now thank you
