### ISSUE TITLE
500 Timeout

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#2472]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie pobrania danych GET metodą after-sales-service-conditions wasz serwer testowy nie odpowiada. Logowanie przebiega poprawnie i pobranie userId.

Są jakieś limity na requesty?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie zasobów z grupy After sale services - dla każdego otrzymałem odpowiedź ze statusem 200. Mamy generalnie jeden limit - 9000 requestów na minutę. Proszę spróbuj ponownie odpytać zasoby.
