### ISSUE TITLE
Dziwne wartości ilości sprzedanych sztuk

### ISSUE THREAD

**Issue by Intuicja** [allegro/allegro-api#2473]
Witam, 
pobieram od kilku dni wyniki sprzedaży dla produktów i wrzucam je do excela. 

Proszę o pomoc w zrozumieniu danych które dostałem:

product_id | 2019-11-04 | 2019-11-03 | 2019-11-02 | 2019-11-01
8307581683 | 12 | 12 | 13 | 12
8376467655 | 7 | 8 | 7 | 7

Wynika z nich że 2 listopada produkt 8307581683 pokazywał 13 sprzedaży a następnego i poprzedniego dnia było 12, podobna sytuacja dzieje się w następnym produkcie gdzie 3 listopada jest 8 a w poprzednie dni po 7. 

Czy należy podejść do tego że ktoś kupić i zwrócił produkt czy jest to coś innego?

Chciałbym się przy okazji dowiedzieć za jaki okres są to dane?

**Comment by MaciejFrackowiak** [comment]
Bazując tylko na domyśle - nie wiemy stricte dane z jakich pól prezentujesz - to pokazujesz nam sprzedaż z ostatnich 30 dni w danej ofercie. W ilościach prezentowanych nie są uwzględniane zwroty - to wymaga ingerencji użytkownika (zmiana liczby przedmiotów w ofercie). Abyśmy coś więcej mogli napisać niezbędne jest info z jakich zasobów korzystasz, jakie dane pobierasz do swojej tabeli.
