### ISSUE TITLE
doGetRefundsList zakres danych

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2474]
Nie mogę znaleźć w dokumentacji informacji na temat tego jak daleko wstecz metoda doGetRefundsList zwraca informacje o zwrotach prowizji. Odpytałam o ostatni 1000 i otrzymałam 45 wyników. Czy istnieje możliwość uzyskania danych od początku 2019 roku?

**Comment by MaciejFrackowiak** [comment]
Lista obejmuje złożone wnioski o zwrot prowizji z ostatnich 60 dni. Nie ma możliwości wygenerowania jej dla wcześniejszych wniosków.
