### ISSUE TITLE
Oferty z allegrolokalnie w offers/listing

### ISSUE THREAD

**Issue by bartoszkurek** [allegro/allegro-api#2475]
Dzień dobry,
pobierając oferty z zasobu offers/listing otrzymuję oferty z allegro i z allegrolokalnie, jak je odróżnić, potrzebuję url ofert, o ile przy allegro nie ma problemu bo jest id oferty i allegro ładnie przekierowuje po id oferty o tyle oferta z allegrolokalnie "nie istnieje"?
Jak mogę je odróżnić lub jak mogę wykluczyć oferty z allegrolokalnie bo robi się bałagan.
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Na listingu Allegro oferty z Allegro Lokalnie występują tylko w postaci przekierowania do Allegro Lokalnie, ich ID jest z osobnej puli, dlatego otrzymujesz komunikat "nie istnieje".

**Comment by jagub2** [comment]
Cześć, sam się z tym ostatnio borykałem. Oferty z allegrolokalnie są zwracane w ten sam sposób co charytatywne aukcje -- oferty mają pole "vendor", które z kolei zawiera "url".
