### ISSUE TITLE
Pytania dot. pobierania zamówień - migracja z WebApi

### ISSUE THREAD

**Issue by jzskyshop** [allegro/allegro-api#2476]
Migruję pobieranie zamówień z WebApi i napotkałem następujące wątpliwości.

- W jaki sposób zasymulować można złożenie zamówienia bez wypełnienia formularza pozakupowego? Kliknąłem kup teraz (przeniosło mnie do formularza) jednak zamówienie nie jest odnotowane. W kontekście tej integracji, interesują mnie jedynie zamówienia z ofert typu kup teraz.
- Czy dobrze zaobserwowałem, że w WebApi obowiązują inne identyfikatory eventów zamówień? 
- Czy dobrze rozumiem: zasób order/checkout-forms jest dostępny zawsze po złożeniu zamówienia i z czasem uzupełnia się jedynie o nowe informacje?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na Twoje zapytania:

- obecnie tylko w aplikacji mobilnej można dokonać zakupu bez wypełniania formularza pozakupowego, jednak już samo kliknięcie Kup Teraz tworzy zamówienie;

- Tak, są to dwie osobne pule identyfikatorów;

- Tak, tzw. checkoutForm, czyli zamówienie ma stałe ID, zmieniają się tylko dane w jego obrębie (wyjątek to sytuacja, gdy kupujący połączy kilka zamówień w jedno, wówczas powstaje nowy checkoutForm).

Wiele cennych informacji i wskazówek znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).

**Comment by anaxagore78** [comment]
>   obecnie tylko w aplikacji mobilnej można dokonać zakupu bez wypełniania formularza pozakupowego, jednak już samo kliknięcie Kup Teraz tworzy zamówienie;

To ja sie podłączę pod ten temat, czy w aplikacji mobilnej planujecie wyeliminować mozliwość dokonania zakupu bez wypełniania formularza ?

**Comment by Radeq** [comment]
@MaciejFrackowiak , ad.1 czy jest możliwe zasymulowanie takiej sytuacji na sandbox? Może aplikacja Allegro może się przełączyć na sandbox?

Czy wygranie licytacji i nie wypełnienie formularza dostawy to taka sama sytuacja?

**Comment by MaciejFrackowiak** [comment]
@anaxagore78 Tak, chcemy by procesy z aplikacji i WWW były w pełni spójne.

**Comment by MaciejFrackowiak** [comment]
@Radeq Tak, wygranie licytacji jest adekwatne do kliknięcia tylko Kup Teraz bez wypełniania formularza pozakupowego.

**Comment by jzskyshop** [comment]
@MaciejFrackowiak - skoro ID eventów się różnią, jak zsynchronizować eventy WebApi z RestApi (określić czy konkretne zdarzenie zostało już obsłużone przez integrację, czy nie)? Mamy zapisany ostatni pobrani event z WebApi.

**Comment by MaciejFrackowiak** [comment]
@jzskyshop Możesz np. rozkodować datę zdarzenia WebAPI z pola <dealEventTime>, a następnie zamienić ją na czas obowiązujący w REST API - event.id to de facto czas wystąpienia zdarzenia podany w formacie Unix - mikrosekundowym.

**Comment by jzskyshop** [comment]
@MaciejFrackowiak metoda którą zaproponowałeś nie działa - z WebApi nie otrzymuję czasu w mikrosekundach, tylko w sekundach, przez co definicja parametru 'from' w REST Api nie działa. Nie udostępniacie jakiejś metody mapującej na okres migracji?

**Comment by MaciejFrackowiak** [comment]
@jzskyshop Czas z WebAPI rozkodowujesz na czas standardowy, a następnie ten czas zmieniasz na mikrosekundowy. Do mapowania zamówień udostępniiśmy zasób [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping).

**Comment by jzskyshop** [comment]
@MaciejFrackowiak - okej - rzeczywiście działa, dzięki za pomoc.

**Comment by jzskyshop** [comment]
@MaciejFrackowiak - spytam kontrolnie, bo widzę, że w dokumentacji dla zasobu /order/line-item-id-mappings zwracacie w polu "mappings" tablicę obiektów, ale nie da się chyba podać wielu id-ków do zmapowania - tj. trzeba wysyłać jeden request per dealId?

**Comment by PrzemyslawLukanowski** [comment]
@jzskyshop Zgadza się, w URL możesz przekazać tylko jedną wartość.

**Comment by jzskyshop** [comment]
@PrzemyslawLukanowski - kolejna wątpliwość. W dokumentacji zasobu order/checkout-form nie uwzględniliście pola updatedAt, chociaż takie przesyłacie. Mam pewność, że ono nagle nie zniknie?

**Comment by PrzemyslawLukanowski** [comment]
Nie zniknie, w najbliższym czasie zaktualizujemy dokumentację.
