### ISSUE TITLE
Godzina API

### ISSUE THREAD

**Issue by zoozool** [allegro/allegro-api#2477]
Cześć
Korzystam z integracji Shoper przez API allegro, i po zmianie czasu zamówienia w shoperze pojawiają się z godziną różnicą czasu.
Dział IT shopera sprawdził i podobno godzina jest pobierana z API allegro.
Umywają ręce i nic nie mogą zrobić.
Czy tylko u mnie ten problem występuje, czy faktycznie po stronie allegro API?

**Comment by MaciejFrackowiak** [comment]
Tak, mamy zgłoszony problem - szczegóły znajdziesz w [GitHub #2446](https://github.com/allegro/allegro-api/issues/2446)

**Comment by zoozool** [comment]
Czy jest jakaś deklaracja daty naprawienia zmiany czasu(sic!) na zimowy?
od 8 dni to trwa.

**Comment by MaciejFrackowiak** [comment]
Zdajemy sobie sprawę z uciążliwości jakie ten problem powoduje - trwają prace nad jego wyeliminowaniem. Zamieścimy info wraz z przywróceniem właściwego działania.

**Comment by MaciejFrackowiak** [comment]
@zoozool Problem dotyczący zmiany czasu został wyeliminowany.
