### ISSUE TITLE
Pytanie o dziennik zdarzeń

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2478]
Witam,
Proszę o sprawdzenie zdarzeń dla zamówienia, check_out_form_id:
d7b26ec2-ffa6-11e9-b465-6756b724ae20
dla tego zamówienia mam 47 zdarzeń.
Wiem, że duplikaty nie są błędem, ale 47 zdarzeń też nie jest standardem.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - zweryfikujemy ten przypadek. Zawsze oczywiście warto spoglądać na id checkoutForm oraz datę z occuredAt.
