### ISSUE TITLE
Wyszukiwanie ofert allegrolokalnie przez API

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2479]
Hej!
Czy jest możliwość wyszukiwania ofert przez API allegro w serwisie allegrolokalnie?
Widziałem, że oferty te pojawiają się w zasobie offers/listings, ale czy na podstawie wyniku z takiego wyszukiwania mogę przekierować użytkownika na stronę z tą ofertą?

**Comment by jagub2** [comment]
Cześć, sam się z tym ostatnio borykałem. Oferty z allegrolokalnie są zwracane w ten sam sposób co charytatywne aukcje -- oferty mają pole "vendor", które z kolei zawiera "url".

**Comment by jakubmaguza** [comment]
Okej, czyli można śmiało wchodzić w API w tym temacie. Dzięki!

**Comment by grzegorzjj** [comment]
Pomocny post. Skorzystałem - dzięki.
