### ISSUE TITLE
konto użytkownika zostało zablokowane

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2480]
Czy mogę liczyć na odwieszenie konta na sandboxie? Kiedy publikuj oferte przez api nie ma błedów ale w serwisie pozostaje szkicem. Kiedy próbuje publikować w serwisie bezpośrednio wyskakuje komunikat z lewej strony ekranu :
Podczas wznowienia oferty wystąpiły błędy
Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam login konta na Sandbox lub ID konta, wówczas sprawdzę jego status.

**Comment by SaintRaphaelBass** [comment]
Login: srb
Zapomnialem jak sprawdzic id konta?

**Comment by SaintRaphaelBass** [comment]
{"userId":"44203306","email":"adamo1997-13@tlen.pl","userName":"srb"}

**Comment by SaintRaphaelBass** [comment]
https://user-images.githubusercontent.com/38372822/68283016-069ab100-007b-11ea-956d-e356a3174575.png

**Comment by MaciejFrackowiak** [comment]
Widzę, że na koncie masz blokadę sprzedaży - skorzystaj z symulatora płatności by spłacić zadłużenie na Sandbox. Po odnotowaniu "wirtualnej" wpłaty blokada zostanie zdjęta.

**Comment by SaintRaphaelBass** [comment]
Nie mam pojęcia jak to zrobić. Gdzie znajdę to zadłużenie i jak mam je spłacić?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj ze strony [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) - tam dokonaj płatności poprzez symulator.

**Comment by SaintRaphaelBass** [comment]
Po kliknięciu zapłać dostaje pustą stronę:
Ta przestrzeń jest pusta
Strona, której szukasz, nie istnieje (błąd 404)

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie symulatora - nie natrafiłem na wspomniany błąd 404. Finalnie wpłata została zaksięgowana, a rachunek uregulowany. Proszę napisz jakie opcje wybierasz podczas realizowania płatności.

**Comment by SaintRaphaelBass** [comment]
![zaplata](https://user-images.githubusercontent.com/38372822/68291973-3d78c300-008b-11ea-90a4-dce652e934d7.png)
![404](https://user-images.githubusercontent.com/38372822/68291974-3d78c300-008b-11ea-94e4-9f1d14da02bf.png)

**Comment by MaciejFrackowiak** [comment]
Proszę skorzystaj z trybu incognito i podejmij próbę raz jeszcze.

**Comment by SaintRaphaelBass** [comment]
W trybie incognito jest to samo

**Comment by MaciejFrackowiak** [comment]
Udało nam się powtórzyć błąd - problem przekazałem do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem potwierdzenie - problem został rozwiązany.

**Comment by SaintRaphaelBass** [comment]
Ok, działa dzięki. Długo się to księguje, czy dług powinien od razu zniknąć ? Robię szybka wpłata przez payu sandbox

**Comment by SaintRaphaelBass** [comment]
Kiedy płace przez payments simulator nie księguje mi wpłaty i nadal mam dług a przy wpłacie za pomocą płatność online kartą platniczą to przyciski w odnośniku wogóle nie reagują

**Comment by MaciejFrackowiak** [comment]
Niestety, tym razem pojawił się problem z działaniem samego symulatora - problem już przekazałem do weryfikacji. Przepraszam za niedogodności.

**Comment by Sharhin** [comment]
Powyższe funkcję dalej nie działają.

Poproszę o rozliczenie płatności dla użytkownika:
login G5rsI1IZ
id: 44207401

**Comment by mstrzyzewski** [comment]
Można prosić o odblokowanie sprzedaży na kontach sandbox?

Konto1:
login: admin345

Konto2:
login:  admin456
