### ISSUE TITLE
Wylogowanie użytkownika z serwisu przy odświeżaniu tokenów

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#2481]
Dzień dobry.
Klient zgłasza nam taki problem, mianowicie jeśli odnowi z poziomu naszej aplikacji tokeny (autoryzacja zwykła), to zostanie wylogowany z aktywnych sesji w przeglądarkach. Dotyczy to różnych przeglądarek (w tym wypadku firefox i opera), doradziłem mu oczyszczenie cache ale problem nadal występuje.
Czy faktycznie odnowienie tokenów może mieć wpływ na wylogowanie z frontu?

**Comment by MaciejFrackowiak** [comment]
Obecnie jednocześnie użytkownik może mieć aktywnych 20 sesji w Allegro. Wygenerowanie nowego tokena nie powinno mieć wpływu na nie, chyba że będzie to 21 sesja - w tym momencie pierwsza zostaje zakończona, itd.
