### ISSUE TITLE
[PILNE] Opóźnienia w WebAPI oraz błędy SOAP

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#2482]
Dzień Dobry,
od kilku tygodni w API zdarzają się dość mocne opóźnienia w pojawianiu się danych. Na przykład:

- zakup/deal 2198512292 (a8097ad0-0062-11ea-849f-c7cd8a72610f) został dokonany dzisiaj o godzinie 07:57:20, ale mój serwis, które stale obserwuje API odnotował go dopiero o godzinie 08:39:21

- zakup/deal 2198519586 (8ed11c60-0064-11ea-a9be-231a6a24578a) został dokonany dzisiaj o godzinie 08:11:14, ale mój serwis, który stale obserwuje API odnotował go dopiero o godzinie 08:39:22

Tak jakby, pojawiło się jakieś ponad półgodzinne opóźnienie w API. Ze względu na specyfikę mojego serwisu, który dokonuje obsługi zakupów w ciągu 5 minut, takie coś jest niedopuszczalne! Proszę o sprawdzenie. Posiadam logi mojego narzędzia monitorującego, które na pewno przez ten czas wykonywało się prawidłowo, ale nie widziało tych transakcji w doGetSiteJournalDeals.

Dodatkowo SOAP co jakiś czas sypie błędami:
Code: ERR_INTERNAL_SYSTEM_ERROR, Desc: Wewnętrzny bład systemu.
Code: ERR_TIMEOUT, Desc: Upłynął czas połączenia! Proszę spróbować jeszcze raz.

Co wy tam robicie?

**Comment by MaciejFrackowiak** [comment]
Proszę podeślij logi poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) podając w treści zgłoszenia dopisek GitHub #2482.

**Comment by amarel123** [comment]
@MaciejFrackowiak ale jakie logi? Posiadam tylko moje wewnętrzne logi, które Państwu nic nie powiedzą, a mi mówią tyle, że monitor odpytywał regularnie doGetSiteJournalDeals i nie było tam tych zakupów przez pół godziny... Jeżeli chodzi o jakieś XML z SOAP to logiczne, że ich nie zbieram bo musiałbym gromadzić w ciągu roku terabajty danych patrząc na ilość obsługiwanych przeze klientów i wykonywanych zapytań do różnych endpointów. Teraz po fakcie to co ja Wam mogę dać? Teraz wskazane transakcje są już w dziennikach więc pozostaje Wam sprawdzić w systemie dlaczego macie opóźnienia. Z resztą nawet jeśli miałbym takie logi to co byście zobaczyli? Że dane pojawiły się z opóźnieniem, a wcześniej faktycznie ich nie było? Możecie wierzyć mi na słowo.

**Comment by MaciejFrackowiak** [comment]
Zweryfikowaliśmy dane - nie zauważyliśmy znaczących odstępstw od prawidłowego działania metody, co istotne nie dotarły do nas inne zgłoszenia użytkowników, stąd moja prośba o logi.
Obecnie WebAPI nie jest już przez nas rozwijane, główny nacisk postawiliśmy na REST API, dlatego zachęcamy do przejścia na nowe rozwiązanie.

**Comment by Onixarts** [comment]
No to ja potwierdzę, że niektórzy klienci i u nas mają problem z dużymi opóźnieniami. Nie badamy tego tematu dokładniej bo pracujemy nad RESTem, ale mamy informacje, że takie opóźnienia w WEBAPI występują.
