### ISSUE TITLE
Nie można uzyskać tokena dostępu

### ISSUE THREAD

**Issue by w4ugit** [allegro/allegro-api#2484]
Próbuję uzyskać token dostępu zgodnie z opisem tutaj - https://developer.allegro.pl/getting_started/, ale pojawia się błąd - {„error”: „Unnauthorized”, „error_description”: „Unnauthorized”}

**Comment by MaciejFrackowiak** [comment]
Z jakiego typu autoryzacji korzystasz? W jaki sposób wywołujesz swoje zapytanie?
Zajrzyj do [naszego poradnika](https://developer.allegro.pl/auth/) o autoryzacji.

**Comment by w4ugit** [comment]
`<?php

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl/auth/oauth/token";
    $clientId = "";
    $clientSecret = "";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    echo '<pre>';
    var_dump($tokenResult);exit;

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

function main()
{
    echo "access_token = ", getAccessToken();
}

main();`

po prostu zastąp moje dane

**Comment by w4ugit** [comment]
authUrl jest niepoprawny, to ja - $ authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";

**Comment by w4ugit** [comment]
masz jakieś przemyślenia na temat przyczyny błędu?

**Comment by MaciejFrackowiak** [comment]
Z językiem PHP niestety nie pomożemy - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Wątek generowania tokenu w PHP przewijał się we wcześniejszych wątkach. Być może wśród nich znajdziesz wskazówki dotyczące Twojego problemu lub któryś z użytkowników forum napotkał podobny problem w przeszłości.
