### ISSUE TITLE
RestAPI - strefa okazji, promocje

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2485]
Czy jest możliwość zarządzania ofertami na Strefie Okazji i innych zakładkach poprzez RestAPI. Jeśli tak to w jaki sposób ? Czy jest możliwość aby poprzez RestAPI ustawiać normalną cenę i przekreśloną ?

**Comment by MaciejFrackowiak** [comment]
Tak, dajemy możliwość zgłaszania ofert, pobierania dostępnych kampanii oraz listy utworzonych kampanii - szczegóły znajdziesz w [naszym poradniku](https://developer.allegro.pl/badge/).

**Comment by pietrach** [comment]
Co się stanie gdy mamy ofertę np. w Strefie okazji gdzie jest określona cena i poprzez Rest API zmienimy cenę normalną oferty ? Czy nadal ta oferta będzie miała cenę tą ustawioną w Strefie okazji i dopiero po usunięciu produktu ze strefy okazji cena będzie taka jak ustawiona poprzez RestAPI ?

**Comment by MaciejFrackowiak** [comment]
Poprzez REST API zmienisz standardową cenę przedmiotu, natomiast cena wynikająca ze Strefy Okazji jest niezależna od niej.

**Comment by pietrach** [comment]
OK czyli potwierdź ostatecznie na przykładzie. Mam ofertę w cenie 100 zł. Ustawiam ją na Strefie okazji z ceną 50 zł a przekreślona 80 zł. W trakcie gdy ta oferta jest w strefie okazji to zmieniam normalną cenę poprzez RestAPI ze 100 zł na  120 zł. Rozumiem, że dalej ta oferta będzie w cenie 50 zł i będzie widniało przekreślone 80 zł. Dopiero kiedy dobiegnie okres zakończenia prezentacji oferty w Strefie okazji to pojawi się cena 120 zł ?

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem - w REST API zmieniasz standardową cenę przedmiotu - przykładowo, jeżeli obecnie cena wynosi 100 zł i dokonasz zmian po API to cena zmieni się na 120 zł. To nijak wpływa na ustalenia ze Strefy Okazji, gdzie określasz osobne wartości. Po szczegóły funkcjonowania cen w Strefie Okazji zachęcam do kontaktu poprzez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).

**Comment by Radeq** [comment]
@pietrach , przy zmianie ceny oferty widocznej w strefie okazji może ona trafić do ponownej weryfikacji  z powodu zmiany warunków (cena oferty została zwiększona).

**Comment by pietrach** [comment]
@Radeq nie zrozumieliśmy się. Mamy tak naprawdę 3 ceny. 
1. Normalna cena oferty, która jest prezentowana gdy produkt nie jest w żadnej strefie okazji.
2. Cena w Strefie Okazji ustawiana specjalnie dla Strefy okazji
3. Cena przekreślona w Strefie Okazji ustawiana specjalnie w Strefie Okazji

Według mnie zmiana ceny nr 1 nie powinna mieć żadnego wpływu na prezentację cen nr 2 i 3 jeśli oferta jest w danym czasie w Strefie Okazji. W momencie kiedy produkt wyjdzie ze Strefy okazji pojawi się cena nr 1.

**Comment by pietrach** [comment]
Mam odpowiedź już:

> Jeżeli chodzi o zmianę cen to jeżeli automat będzie chciał zmienić cenę to zmieni aktualną cenę za jaką produkt jest aktualnie wystawiony. Mamy trzy ceny normalną, przekreśloną i cene promocyjna za jaką można nabyć produkt. To normalna już nie istnieje a przekreślona jest na sztywno ustawiona. Zmieniać można tylko promocyjną. Więc jeżeli będziecie chcieli zmienić normalna z 100 na np 120 a zgłoszony produkt jest na 60 to zmieni się cena z 60 na 120. Jeżeli macie możliwość wyłączenia automatycznej kontroli cen na konkretnej ofercie to proponuję taką ofertę wyłączyć z tej funkcji. 
> Najlepiej jest mieć zdublowane oferty jedna normalna druga w SO i kontrolować ta normalna a z strefy zostawić w spokoju ;) 
>
