### ISSUE TITLE
Pytanie o integrację z Inpost

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2486]
Czy w "allegro_transaction_id" podajemy lineItemId czy mapujemy (https://api.allegro.pl/order/line-item-id-mappings) i podajemy dealId ?

**Comment by MaciejFrackowiak** [comment]
InPost już obsługuje nowe zamówienia, czyli lineItemId.

**Comment by kfijalko** [comment]
Dziękuję
