### ISSUE TITLE
Problem z offers/listing

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2488]
Występuje problem: 
 z zasobem REST API

Query: GET "https://api.allegro.pl/offers/listing?seller.id=90645&sort=%2BstartTime&offset=120000&limit=100&sellingMode.format=BUY_NOW&searchMode=REGULAR" failed because response status code does not indicate success: 422 (Unprocessable Entity)

Od offset 120000 dla użytkownika 90645 nie jestem w stanie pobierać aukcji, ponieważ dostaję odpowiedź 422. 
Czy jest jakieś ograniczenie? Wiem, że przy innych parametrach jak category.id lub phrase można pobrać tylko 6k rekordów, ale przy podaniu Id usera powinienem być w stanie chyba pobrać wszystkie rekordy. Prawda? 

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Tak, jest ograniczenie - wyświetlamy maksymalnie 2000 stron z ofertami na stronie użytkownika, co odpowiada 120000 ofert.

**Comment by artzie92** [comment]
Czyli nie ma możliwości pobrania ofert użytkownika bez filtrowania ich - fatalnie. Zanim wyłączycie stare Web API, proszę pamiętać o przeniesieniu metod GetItemsInfo i ShowItems info do REST API, ponieważ bez tego będzie paraliż dla większości systemów.

**Comment by MaciejFrackowiak** [comment]
Sugestię wprowadzenia tych zasobów odnotowaliśmy już - dodaję Twój głos.
