### ISSUE TITLE
INVALID_JSON przy przy zmianie opisu oferty PUT /sale/offers/

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#2489]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, nie mogę zaktualizować oferty korzystając z zasobu /sale/offers/{offerId} PUT. Za każdym razem dostaję error INVALID_JSON.
1. Pobieram ofertę z zasobu /sale/offers/{offerId} GET
2. Zmieniam pole description
3. Wysyłam ofertę /sale/offers/{offerId} PUT.

Składnia JSON jest poprawna, jak również struktura pola description. Domyślam się że problem może dotyczyć jakiś niedozwolonych znaków, jednak opis błędu nie pozwala na dokładne zlokalizowanie problemu.

Pole description:
`
{
   "sections":[
      {
         "items":[
            {
               "type":"IMAGE",
               "url":{
                  "url":"https:\/\/a.allegroimg.com\/original\/11a0c5\/29375bd0403c812bdca4bdfc0b59"
               }
            },
            {
               "type":"TEXT",
               "content":"<h1>Prostownica do w\u0142os\u00f3w Shine Therapy      S8500<\/h1><h2>Producent: Remington<\/h2>"
            }
         ]
      },
      {
         "items":[
            {
               "type":"TEXT",
               "content":"<h2>W\u0142a\u015bciwo\u015bci<\/h2><ul><li>Banner <b><\/b><\/li><li>Opis <b>Prostownica do w\u0142os\u00f3w Shine Therapy      S8500Wybierz prostownic\u0119 Shine Therapy, aby uzyska\u0107 intensywnie l\u015bni\u0105ce w\u0142osy, z po\u0142yskiem wi\u0119kszym o 86%*. P\u0142ytki z pow\u0142ok\u0105 Advanced Ceramic nasycone naturalnym maroka\u0144skim olejkiem arganowym i witamin\u0105 E, po nagrzaniu r\u00f3wnomiernie wydzielaj\u0105 mikrood\u017cywk\u0119, kt\u00f3ra wnika we w\u0142osy. Produkt zosta\u0142 przetestowany na niezale\u017cnej grupie konsument\u00f3w w por\u00f3wnaniu do dotychczas u\u017cywanych prostownic. Po przeprowadzeniu testu konsumenci stwierdzili, \u017ce ich w\u0142osy s\u0105:- 94% g\u0142adsze i l\u015bni\u0105ce- 88% bardziej mi\u0119kkie, w lepszej kondycji- 88% bardziej prostsze- 86% maj\u0105 wi\u0119cej blasku<\/b><\/li><li>Pow\u0142oka <b>Ceramiczna<\/b><\/li><li>Regulacja temperatury <b>Tak<\/b><\/li><li>Temperatura (min.) <b>150<\/b><\/li><li>Temperatura (maks.) <b>230<\/b><\/li><li>Obrotowy przew\u00f3d <b>Tak<\/b><\/li><li>Nasadki <b><\/b><\/li><li>Akcesoria w zestawie <b><\/b><\/li><li>Wymiary <b><\/b><\/li><li>Pozosta\u0142e parametry <b>- 86% wi\u0119cej blasku- P\u0142ytki Advanced Ceramic nasycone maroka\u0144skim olejkiem arganowym z witamin\u0105 E- Cyfrowy wy\u015bwietlacz temperatury z 9 ustawieniami temperatury- Szybkie nagrzewanie w 15 sekund- Ruchome p\u0142ytki dla r\u00f3wnomiernego nacisku na w\u0142osy- Funkcja Turbo boost dla szybkiego osi\u0105gni\u0119cie temperatury maksymalnej- Funkcja blokady ustawionej temperatury- Automatyczne wy\u0142\u0105czenie po 60 minutach- Funkcja blokady p\u0142ytek dla \u0142atwego przechowywania- Etui odporne na wysokie temperatury- Uniwersalne napi\u0119cie umo\u017cliwia u\u017cywanie na ca\u0142ym \u015bwiecie<\/b><\/li><\/ul>"
            },
            {
               "type":"IMAGE",
               "url":{
                  "url":"https:\/\/a.allegroimg.com\/original\/117c57\/6b850a8b4151a0a1a1b07a14523e"
               }
            }
         ]
      }
   ]
}
`

Bez zmiany pola description request wykonuje się poprawnie

Trace id: 820406867952241

**Comment by PatrykBocian** [comment]
Zweryfikowałem twój request, błąd powoduje nieprawidłowe przekazanie url zdjęcia.
Podwójnie przekazujesz pole url, prawidłowo powinno to wyglądać tak: 

![1111](https://user-images.githubusercontent.com/56817097/68383283-a7f63580-0155-11ea-8201-0bb34b7d7807.png)


Więcej na temat tego jak tworzyć oferty znajdziesz w naszym [poradniku](https://developer.allegro.pl/sale/#step-5-description).

**Comment by arolznov** [comment]
Faktycznie, mój błąd i niedopatrzenie. Moją sugestią jest zwracanie przez Was dokładnej informacji o błędnym fragmencie JSON, czyli w tym przypadku komunikat: pole url jest niepoprawnym adresem url

**Comment by PatrykBocian** [comment]
Dziękuje za sugestie, przekazałem ją do odpowiedniego zespołu.
