### ISSUE TITLE
Różne produkty w jednej paczce

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2490]
Kiedy ktoś zamawia ode mnie dwa różne wystawione przeze mnie produkty to allegro automatycznie dzieli zamówienie na dwie paczki i klient musi zapłacić za dwie przesyłki kurierskie, choć ja mu to wyślę w jednej paczce. Mam mu zrobić zwrot kosztów drugiej przesyłki, czy jest jakaś możliwość sumowania moich produktów w zamówieniu do jednej paczki?

**Comment by PatrykBocian** [comment]
Możesz to rozwiązać poprzez ustawienie na swoim koncie Allegro łączenia kosztów dostawy dla ofert z różnymi cennikami.
Dzięki temu będziesz mógł ustalić metodę łączenia cenników dla kilku różnych produktów zakupionych przez jednego klienta. Więcej na ten temat znajdziesz na stronie [pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/cennik-dostawy/jak-ustawic-odpowiedni-sposob-laczenia-kosztow-dostawy-dla-ofert-z-roznymi-cennikami-4GDdXnx0LuW).

**Comment by SaintRaphaelBass** [comment]
Mając zamówienie podzielone na dwie paczki, dodając numer przesyłki w Allegro dodaje się on dla całego zamówienia i po pobraniu przez rest api w sekcji LineItem jest widoczny numer zamówienia, a w rest api mam przesyłać w sekcji LineItem id pojedynczych produktów w zamówieniu. Czy mogę w sekcji LineItem dodawać sam numer zamówienia i jak to będzie wyglądać w mailach po stronie odbiorcy?
