### ISSUE TITLE
Jak rozpoznać aukcję zakończoną przez użytkownika: odwołaną oraz zakończoną sprzedaniem?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2492]
Dzień dobry,
Zastanawia mnie, jak rozpoznawać za pomocą zasobów /sale/offers/{offerID} oraz /sale/offers aukcje, które zostały odwołane bądź sprzedane wraz z zamknięciem aukcji. Czy można rozróżniać takie sytuacje za pomocą ilości złożonych ofert tj. złożone oferty są zerowane wraz z odwołaniem ofert na froncie? Jeżeli nie, jak inaczej rozpoznawać takie sytuacje?

**Comment by PatrykBocian** [comment]
Można to sprawdzić, najlepiej zasobem GET/sale/offers.
Będzie tam widoczne pole “biddersCount” które zlicza oferty kupna, które złożyli kupujący.
Dla przykładu jak ktoś zalicytuje twój przedmiot pole te będzie wyglądało tak - “biddersCount” : 1.
W momencie kiedy zakończysz licytacje i odwołasz  oferty licznik wyzeruje się.
