### ISSUE TITLE
Pytanie o płatności, zdarzenia i formularze

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2493]
Jestem w trakcie pisania modułu obsługi zamówień, przyjąłem kilka założeń:
1) odpytuję cyklicznie /order/events
grupuję zdarzenia po checkout-form-id i raz pytam /order/checkout-forms/{id}
2) nie odpytuję o płatności /payments/payment-operations

Pytania:
1) Czy wszystkie operacje z /payments/payment-operations maja odzwierciedlenie w /order/events ?
2) Jakie rodzaje operacji mogą wystąpić w /payments/payment-operations ? (brak "poradnika" dla tych metod)
3) W /order/checkout-forms/{id} pole payment jest encją (nie tablicą) natomiast w /payments/payment-operations nie ma wskazania na transakcję. W jaki sposób pobrać informację o kilku wpłatach do zamówienia (udanych, anulowanych)?

**Comment by kfijalko** [comment]
Dodatkowe pytania:
4) Jak zachowuje się /order/events gdy wystąpią u Was opóźnienia/awarie. Czy gwarantujecie pojawienie się wszystkich zdarzeń? Czy może dojść do sytuacji, że pojawią się zamówienia w /order/checkout-forms, które nie będą miały zdarzeń w /order/events?
5) Zdarzenia pobieram przyrostowo, czyli wszystkie zdarzenia od numeru, który ostatnio odczytałem. Czy w wyniku Waszego opóźnienia w przetwarzaniu/awarii mogę pominąć jakieś zdarzenia? Może powinienem na wszelki wypadek odpytywać cyklicznie /order/checkout-forms ?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na pytania:

1. Nie, /order/events zawiera tylko zdarzenia związane z przyjętym zamówieniem - BOUGHT, FILLED_IN, READY_FOR_PROCESSING. Natomiast /payments/payment-operation obsługuje także m.in. zwroty płatności;

2. Opisy operacji umieściliśmy w grupach - opis pola “group”, i tak: INCOME - wpłata, dopłata, korekta, zwiększenie odliczenia; OUTCOME - wypłata, anulowanie wypłaty, obciążenie za odliczenie; REFUND - obciążenie z tytułu zwrotu wpłaty, anulowanie zwrotu, zwiększenie zwrotu, korekta;

3. Do zamówienia możesz otrzymać jedną główną wpłatę i ewentualnie później dopłatę. Otrzymanie wpłaty generuje status READY_FOR_PROCESSING, a dopłata pojawia się także jako READY_FOR_PROCESSING, ale z uzupełnionym polem “surcharges.id”;

4. Nie, każdy event pojawi się w /order/events;

5. Nie powinno dojść do takiej sytuacji.

**Comment by kfijalko** [comment]
1) Jednak dodałem cykliczne odpytywanie /order/checkout-forms za za okres od -24h do -1h. Weryfikuję czy jest jakieś zamówienie ,którego nie mam lub, którego "status allegro" jest starszy niż pobrany. Tak na wszelki wypadek.
2) Zwroty (statusy realizacji) mam zamiar pobierać z /payments/refunds. Czy to wystarczy, żeby obsłużyć zwroty? Czy jakieś informacje dodatkowe są w /payments/payment-operations ?
3) w /payments/payment-operations występuje 10 typów operacji. Ja znam: wpłata, dopłata, zwrot. W jakich sytuacjach występują pozostałe?

**Comment by kfijalko** [comment]
Czy może Pan rozwinąć co to za operacje i w jakich sytuacjach występują: anulowanie wypłaty, anulowanie zwrotu, korekty, odliczenia?

**Comment by MaciejFrackowiak** [comment]
Takie działania mogą zaistnieć na skutek działań administratorów, ograniczeń nałożonych na konto (blokady), itp.

**Comment by kfijalko** [comment]
ok, dziękuję
