### ISSUE TITLE
Niedziałająca definicja w swagger.yaml (/offers/listing \"A filter's ID\")

### ISSUE THREAD

**Issue by raffael-sfm** [allegro/allegro-api#2494]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [?] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W pliku `swagger.yaml` dostępnym pod adresem https://developer.allegro.pl/swagger.yaml
w sekcji `/offers/listing:` znajduje się następująca definicja:
>        - name: "\"A filter's ID\"  "
>          in: query
>          description: >-
>            You can filter and customize your search results to find exactly what you need by applying filters ids and their dictionary values to query according to the flowing pattern: id=value.
>[...]

Niestety ale generator API traktuje ją dosłownie i generuje parametr funkcji `$a_filters_id = null`, a w kodzie `$queryParams['&quot;A filter&#39;s ID&quot;'] = ObjectSerializer::toQueryValue($a_filters_id);`. Czyli, zawartość tego parametru funkcji zostaje zapakowana do query string pod nazwą `&quot;A filter&#39;s ID&quot;`.

Niestety, ale nie działa to wcale.
Można się domyślać, że intencją było zdefiniowanie tutaj 'placeholdera', czyli uniwersalnego dynamicznego parametru. Nie wiem czy format `swagger.yaml` w ogóle przewiduje taki mechanizm, ale obecnie generator sobie zdecydowanie nie radzi.

Co działa? Umieszczenie filtrów bezpośrednio w query string jako parametry zapytania GET. Np `option=SMART` a nie `%26quot%3BA%20filter%26%2339%3Bs%20ID%26quot%3B=option%3DSMART`

Oznacza to niestety konieczność ręcznej modyfikacji kodu wygenerowanego API.

Jeżeli nie da się tego zrobić porządnie w pliku `swagger.yaml`, dodajcie chociaż bardzo wyraźne ostrzeżenie w komentarzu, bo znalezienie problemu kosztowało mnie sporo czasu.

**Comment by MaciejFrackowiak** [comment]
Przyglądamy się Twojemu zgłoszeniu, wrócę z odpowiedzią.
