### ISSUE TITLE
Błąd przy uzyskiwaniu tokena

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2495]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy próbie wygenerowania tokena, klient dostaje taką informację:
![image](https://user-images.githubusercontent.com/24191650/68456862-37a3ee80-01ff-11ea-9822-ee458091cff3.png)

Czy to chwilowy problem, czy coś się zmieniło?
Redirect jest na http://127.0.0.1:2050/
Do dzisiaj wszystko działało.

b7e7e6d3836f9a71

**Comment by jakubmaguza** [comment]
Wygląda na blokadę przy wprowadzaniu bezpośrednio adresu IP. Przy podaniu 'localhost' przechodzi dalej. Błąd jest jeszcze zanim użytkownik poda swoje dane do Allegro.

**Comment by PatrykBocian** [comment]
Problem dotyczy adresu, który przekazujesz w redirect_uri. Jeżeli pochodzi z prywatnego zakresu IP, który może być potencjalnie wykorzystywany do ataków na naszą infrastrukturę, wtedy jest przez nas blokowany. W takim wypadku trzeba go zmienić. Są dwie opcje jak to zrobić - użyć publicznego adresu IP lub założyć domenę, która kieruje na 127.0.0.1 i podać ją w redirect_uri.

**Comment by jakubmaguza** [comment]
Dlaczego robicie takie zmiany bez żadnej informacji? Do wczoraj wszystko działało. Nie wiem w jaki sposób przekazanie kodu na mojego localhosta może wam zaszkodzić.

**Comment by PatrykBocian** [comment]
Allegro jest żywym organizmem, z tego też względu dbanie o bezpieczeństwo systemu i mechanizmów wymaga ciągłego udoskonalania. Podjęte działania mają na celu zwiększenie bezpieczeństwa. Nie sposób informować o wszelkich działaniach w tym zakresie, co więcej nawet czasem nie możemy mając na celu zwiększenie bezpieczeństwa.

**Comment by jakubmaguza** [comment]
Mogliście chociażby po wprowadzeniu tej zmiany podać informację, że od dzisiaj używanie prywatnych adresów IP jest zabronione.

**Comment by tomos2105** [comment]
Dzień dobry mam podobny problem, od dziś nie mogę uzyskać tokena mam 5 sklepów na tej samej aplikacji w 2 działa wszystko a w 3 jest problem z tokenem dostaje taki bład :
[error] => invalid_grant
[error_description] => Invalid authorization code: flTD19HpAOWnbchFX7XQHVxNYWlp6bjX

w redirect_Uri mam nazwy domen wszystkie mają ten sam adres ip z jednego serwera co może być przyczyną ?

**Comment by rafalkrupinski** [comment]
też mam ten problem, dzięki kochane allegro :/

**Comment by rafalkrupinski** [comment]
Dzieki @jakubmaguza za tipa z localhost
