### ISSUE TITLE
Błąd dokumentacji i swagger.yaml pricing/offer-quotes

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2498]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Występuje nieścisłość w dokumentacji i swagger.yaml

Zasób: GET/pricing/offer-quotes

Response 

> quotes[].offer

Zwraca OfferId a nie cały Offer.

swagger.yml

```
    OfferQuoteDto:
      type: object
      properties:
        enabled:
          type: boolean
        fee:
          $ref: '#/components/schemas/Fee'
        name:
          type: string
        nextDate:
          type: string
          format: date-time
        offer:
          $ref: '#/components/schemas/Offer'
        type:
          type: string
      title: OfferQuoteDto
```

Fragment przykładowego response
```
  +"count": 5
  +"quotes": array:5 [▼
    0 => {#821 ▼
      +"type": "INEFFECTIVE_LISTING_FEE"
      +"name": "Opłata utrzymaniowa"
      +"nextDate": "2019-11-15T10:24:06.505Z"
      +"fee": {#822 ▼
        +"amount": "0.15"
        +"currency": "PLN"
      }
      +"offer": {#823 ▼
        +"id": "xxx"
      }
      +"enabled": true
    }
//...
```

Przykładowy trace-id 276b8a169ac5170f

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie. Zweryfikujemy je i wprowadzimy ewentualne zmiany.
