### ISSUE TITLE
Informacje o zmianach w WebAPI w formacie RSS

### ISSUE THREAD

**Issue by zaza** [allegro/allegro-api#25]
Od dawna monituruje zmiany w WebAPI śledząc posty RSS dostepne pod tym adresem: https://allegro.pl/rss.php/webapi?all=0 Od jakiegos czasu mam wrazenie ze feed nie jest aktualizowany a zmiany mimo wszystko sie pojawiaja, tj po przegenerowaniu zrodel dla [WSDL ](https://webapi.allegro.pl/service.php?wsdl) widac roznice.

Czy moje obserwacje sie sluszne? Czy istnieje inny sposob sledzenia zmian w WebAPI? Idealnie bez koniecznosci wchodzenie na fb i czytania komentarzy. [Tutaj](https://github.com/zaza/allegro-webapi/blob/master/src/test/java/com/github/zaza/allegro/webapi/WebapiChangelogTest.java) jest przyklad w jaki sposob korzystalem z feeda do tej pory.

**Comment by MarcinLuczak** [comment]
RSS z adresu https://allegro.pl/rss.php/webapi?all=0, czyli tylko zmiany z Changeloga, rzeczywiście nie działa (zgłoszę ten problem do odpowiedniego działu). Jednak RSS z wszystkimi komunikatami na stronie WebAPI (https://allegro.pl/rss.php/webapi?all=1) zwraca wszystkie informacje.

Nowe komunikaty będą się także pojawiały tutaj - będą oznaczone etykietą "News" (https://github.com/allegro/allegro-api/issues?q=is%3Aissue+is%3Aopen+label%3Anews).

**Comment by zaza** [comment]
Dzięki za odpowiedź. RSS ze wszystkimi informacjami mnie nie urządza bo musiałbym identyfikować komunikaty o zmianach w WebAPI samodzielnie, co może się okazać nietrywialne. Proszę zaktualizować (zamknąć) to zapytanie jak tylko RSS z parametrem all=0 znów będzie działał jak poprzednio.

Innym rozwiązaniem mogłoby byc dodanie etykiety "changelog" czy coś w tym stylu do wspomnianych komunikatow publikowanych na github. Gdzie będzie ta informacja ogłoszana jest mi obojętne jak długo mogę zautomatyzowac proces jej odczytywania.

**Comment by MarcinLuczak** [comment]
> Dzięki za odpowiedź. RSS ze wszystkimi informacjami mnie nie urządza bo musiałbym identyfikować komunikaty o zmianach w WebAPI samodzielnie, co może się okazać nietrywialne. Proszę zaktualizować (zamknąć) to zapytanie jak tylko RSS z parametrem all=0 znów będzie działał jak poprzednio.

Innych zmian komunikujemy dosyć mało, więc nie powinieneś mieć problemu ze zidentyfikowaniem interesujących Cię komunikatów.

> Innym rozwiązaniem mogłoby byc dodanie etykiety "changelog" czy coś w tym stylu do wspomnianych komunikatow publikowanych na github. Gdzie będzie ta informacja ogłoszana jest mi obojętne jak długo mogę zautomatyzowac proces jej odczytywania.

Nie planujemy zmian w RSS-ach. Błędy poprawimy, ale nowych elementów raczej nie będziemy do nich dodawać.

**Comment by zaza** [comment]
> Nie planujemy zmian w RSS-ach. Błędy poprawimy, ale nowych elementów raczej nie będziemy do nich dodawać.

Czy dobrze rozumiem, to oznacza, że w kanale  https://allegro.pl/rss.php/webapi nie będzie nowych postów/wpisów?

Żebyśmy się dobrze zrozumieli, moja druga sugestia dot. etykiety "changelog", dotyczyła informacji zamieszczanych na githubie. Z taką etykietą mogłbym łatwo dowiedzieć się o zmianach w API filtrując po "news", "webapi" i proponowany "changelog".

**Comment by MarcinLuczak** [comment]
> Czy dobrze rozumiem, to oznacza, że w kanale https://allegro.pl/rss.php/webapi nie będzie nowych postów/wpisów?

Żebyśmy się dobrze zrozumieli, moja druga sugestia dot. etykiety "changelog", dotyczyła informacji zamieszczanych na githubie. Z taką etykietą mogłbym łatwo dowiedzieć się o zmianach w API filtrując po "news", "webapi" i proponowany "changelog".

No właśnie tutaj się źle zrozumieliśmy, a dokładniej to ja źle zrozumiałem. Do komunikatów na GitHub nie będziemy dodawać nowej etykiety. Zmian w RSS również nie będziemy robić, ale mam tutaj na myśli zmiany funkcjonalne w samym kanale. Komunikaty oczywiście będą się w nich pojawiać, gdy będziemy je publikować.
