### ISSUE TITLE
Błąd filtra w metodzie doGetRefundsList

### ISSUE THREAD

**Issue by Gritrax** [allegro/allegro-api#250]
Witam, mam następujący problem w wykonaniu metody doGetRefundsList, mianowicie nie jestem w statnie wykonać tej metody bez podania filtra w C#, za pomocą SoapUI ochodzi wykonanie takiej operacji, niestety visual studio zwraca mi wtedy błąd "Ciąg '' nie jest prawidłową wartością AllXsd."
A o to przykład wykonania wywołującego błąd

            serviceService service = new serviceService();
            string session = GetSession(ImportID);
            RefundListType[] rl;
            FiltersListType[] fl;
            service.doGetRefundsList(session, null , 1000, true, 0, false, out rl, out fl);

Dodam jeszcze że w miejscu filtra próbowałem przekazać pustą listę o raz listę z jednym pustym elementem i wszystkie próby kończyły się błędem.

**Comment by MartaNowaczyk** [comment]
Witam, API wspieramy jedynie z warstwy protokołów, czyli REST API zapisane w jsonie lub WebAPI zapisane w XML. Jeśli chcesz byśmy sprawdzili twoje zapytanie, prześlij proszę XML'e z request i response.

**Comment by Gritrax** [comment]
Już znalazłem rozwiązanie w polu considerDate  przekazujecie pusty string co nie bardzo parsuje się na datę ale rozwiązałem ten problem po swojej stronie.
