### ISSUE TITLE
Problem z tokenem

### ISSUE THREAD

**Issue by tomos2105** [allegro/allegro-api#2500]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam problem, od wczoraj nie mogę uzyskać tokena mam 5 sklepów na tej samej aplikacji w 2 sklepach działa wszystko ok a w 3 sklepach jest problem z tokenem dostaje taki bład :
[error] => invalid_grant
[error_description] => Invalid authorization code: flTD19HpAOWnbchFX7XQHVxNYWlp6bjX

a dziś to :
[error] => invalid_grant
[error_description] => Redirect URI mismatch.

w redirect_Uri mam nazwy domen wszystkie mają ten sam adres ip z jednego serwera co może być przyczyną ?

**Comment by PatrykBocian** [comment]
Problem dotyczy adresu, który przekazujesz w redirect_uri. Jeżeli pochodzi z prywatnego zakresu IP, który może być potencjalnie wykorzystywany do ataków na naszą infrastrukturę, wtedy jest przez nas blokowany. W takim wypadku trzeba go zmienić. Są dwie opcje jak to zrobić - użyć publicznego adresu IP lub założyć domenę, która kieruje na dany adres IP i podać ją w redirect_uri.

**Comment by tomos2105** [comment]
Adresy są z puli publicznej taka informację dostałem z serwerowni, najdziwniejsze jest to że na 5 sklepów tylko 3 nie działają a wszystkie trzy są na tym samym hostingu ten sam adres ip

**Comment by tomos2105** [comment]
I teraz najciekawsze na sklepie na którym integracja działała dodałem nowy klucz z konta allegro które nie działało i faktycznie nie działa (chciałem sprawdzić czy nie mam gdzieś błędu w kopiach aplikacji sklepu), po chwili przywróciłem dane i na tym co działało już nie działa także działa tylko 1 sklep

**Comment by PatrykBocian** [comment]
W tym przypadku prosiłbym o kontakt przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) i przesłanie tam pełnego requesta (przy zgłoszeniu dopisz proszę #2500). Pomoże to nam szybciej zweryfikować ten problem.

**Comment by tomos2105** [comment]
a jaki temat tam wybrać w tym formularzu tam nic nie ma o rest api chodzi o te pola wyboru w formularzu

**Comment by PatrykBocian** [comment]
Tutaj znajdziesz bezpośredni [link](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) do pomocy w tym przypadku.

**Comment by tomos2105** [comment]
ok dziękuję wysłałem
