### ISSUE TITLE
Zwrotka 422 przy edycji zasobu pobranego metodą `GET`

### ISSUE THREAD

**Issue by martasobota** [allegro/allegro-api#2501]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam zautoryzowaną aplikację, w której po kolei pobieram metodą `GET` informacje o produktach z `GET api.allegro.pl/sale/offers/{auction_id}`
W zwróconym obiekcie zmieniam informacje dotyczące czasu wysyłki w polu `['delivery']['handlingTime']`. 
Np. z `PT24H` na `PT1H` 
Dostaję zwrotkę:
```
"code":"VALIDATION_ERROR","message":"Invalid delivery or location part.
```

Nie zmieniam innych pól, oferty mają uzupełnione pola oraz `shippingRates` oraz wszystkie wymagane pola dla `location`: 
```
 'delivery': {
        'shippingRates': {'id': 'tutaj jest id'}, 
        'handlingTime': 'PT1H', 
        'additionalInfo': '', 
        'shipmentDate': None}, 
```
```
'location': {'countryCode': 'PL', 'province': 'WIELKOPOLSKIE', 'city': 'Poznań', 'postCode': '60-122'}
```

**Comment by kfijalko** [comment]
https://developer.allegro.pl/sale/#delivery-settings

**Comment by kfijalko** [comment]
"handlingTime": "PT168H",               -- czas wysyłki, obecnie dostępne są
                                                wartości: PT0S (natychmiast), PT24H (24 godziny), 
                                                P2D (2 dni), P3D (3 dni), P4D (4 dni), P5D (5 dni), 
                                                P7D (7 dni), P10D (10 dni), P14D (14 dni), 
                                                P21D (21 dni), P30D (30 dni), P60D (60 dni).   
                                                Można również podać te wartości 
                                                w godzinach, np. PT72H (3 dni). 
                                                Niewymagane dla formatu sprzedaży 
                                                typu ADVERTISEMENT (ogłoszenie).

**Comment by martasobota** [comment]
Dziękuję @kfijalko, rzeczywiście problem pewnie jest `PT1H` 👍
