### ISSUE TITLE
WebApi to REST API migration, missing public offers data

### ISSUE THREAD

**Issue by mhadar** [allegro/allegro-api#2502]
I am working on WebApi to REST API migration and I have a question/suggestion about missing data in public offers data.

I havent found REST API alternative to these data we need:
itemListInfoExt->itDescription
itemListInfoExt->itEndingInfo
itemPostageOptions[] // all data

I would also suggest adding seller contact email address missing in webApi too

I would suggest add these data into  /offers/listing  query or add new query returning all public data of one product only

**Comment by PatrykBocian** [comment]
Thanks for suggestions, I forward this subject to team responsible for REST API development.
