### ISSUE TITLE
Ułatwienie cachowania odpowiedzi z api

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2503]
:bulb: **Sugestia**

np.
zasób 
/sale/categories/{categoryId}/parameters

gdyby w zwracanej odpowiedzi był również categoryId o który pytamy łatwiej było by robić cache odpowiedzi po stronie klienta  bez tego trzeba robić sporo kodu aby zachować spójność poprawności danych w przypadku błędu odpowiedzi itp...

Gdyby taka informacja była wystarczyło by zapisywanie odpowiedzi a przed kolejnym zapytaniem tylko sprawdzić czy jest w odpowiedz do danego categoryId jak nie ma to pytać api.

Po co cachować ?  pobranie tych danych np. dla 5k produktów jednorazowo robi sporo zapytań  a jak chcemy pobrać te dane naraz to już robią się zbędne zapytania ( duplikacje zapytań dla tej samej kategorii które pobraliśmy np. 5 sekund temu) i możliwości wystąpienia błędy przy takiej ilości zapytać.

Sprawa Dotyczy również innych metod...

**Comment by PatrykBocian** [comment]
Dziękujemy za sugestię, przekazałem ją do odpowiedniego zespołu.
