### ISSUE TITLE
WebApi/RestApi - Email jako identyfikator?

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2504]
Podczas migracji do RestApi przez jakiś czas część formularzy będę zaciągał WebApi a część RestApi. Szukałem jakiegoś identyfikatora, który pozwoliłby mi weryfikować czy dany formularz nie został już pobrany inną metodą (aby zamówienia mi się nie zdublowały). Jedynym parametrem, który jak się wydaje mógłby do tego służyć to zhaszowany email kupującego, przypisany do konkretnego zamówienia. Mam rację czy coś przegapiłem?

**Comment by PrzemyslawLukanowski** [comment]
Oprócz wymienionego przez Ciebie pola, możesz także sprawdzić to za pomocą paymentId / transactionId. W tym celu musisz wcześniej użyć [mapowania](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping), szczegóły znajdziesz w [newsie](https://github.com/allegro/allegro-api/issues/1878).
