### ISSUE TITLE
RestApi - DealId

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2505]
W związku z migracją do RestApi nie wiem jak rozwiązać następującą kwestię:
Do tej pory, w sytuacji gdy kupujący zbyt długo zwlekał z zapłatą, anulowałem zakup, występowałem o zwrot prowizji a przedmiot wystawiałem ponownie.
Rzadko bo rzadko, ale zdarza się, że po miesiącu czy jeszcze później, klient przypomni sobie i zrobi wpłatę. Wtedy formularz pozakupowy wpada mi jako nowe zamówienie.
Ponieważ, zapisywałem sobie dla których DealId występowałem o zwrot prowizji, przy każdym nowym zamówieniu mogłem sprawdzić, czy zamówienie nie dotyczy anulowanych transakcji (DealId jest w WebApi jednym elementów PostBuyFormDataStruct).
Widzicie jakąś możliwość tego typu weryfikacji w sytuacji gdy formularze zaciagane będą za pomocą RestApi, a mechanizm występowania o zwrot prowizji wciąż bazuje na WebApi?

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku możesz użyć [mapowania lineItemId na dealId](https://developer.allegro.pl/documentation/#operation/findMapping).

**Comment by lukada4100** [comment]
Piękne dzięki. Wątek mapowania jakoś mi umknął...
