### ISSUE TITLE
Rozliczenia z Allegro

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2506]
Kiedy mogę liczyć na naprawę błędu związanego ze spłatą długu, bo mam zablokowaną sprzedaż i nie mogę testować?

**Comment by MaciejFrackowiak** [comment]
Problem przekazałem do weryfikacji jak wspomniałem we wcześniejszym poście. Zdaję sobie sprawę z utrudnień - tymczasowe obejście to skorzystanie z alternatywnego konta na Sandbox.

**Comment by SaintRaphaelBass** [comment]
Ok. Dzięki za odpowiedź
