### ISSUE TITLE
Konto Sandbox

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2507]
Nie działa link aktywacyjny po wykonaniu rejestracji konta na sandbox allegro

**Comment by avello** [comment]
Zalogować się też nie można na sandboxie
Internal Server Error 500
Trace ID: 7a9fd82b1a0e8822

**Comment by MaciejFrackowiak** [comment]
@SaintRaphaelBass  @avello Rzeczywiście, mieliśmy chwilowe problemy z działaniem Sandbox. Obecnie już wszystko działa OK. Przepraszam za niedogodności.

**Comment by SaintRaphaelBass** [comment]
Jeszcze nie działa mi zapytanie o numery przesyłek, chociaż koło 8.00 zwracało dane, teraz jest błąd 404. Zwraca mi listę zwrotów dla tych samych id, dlatego wydaje mi się to dziwne, sprawdźcie cie to.

**Comment by MaciejFrackowiak** [comment]
@SaintRaphaelBass Przed momentem sprawdziłem działanie [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/getOrderShipmentsUsingGET) - bez przeszkód pobrałem numery przesyłek dla transakcji z Sandbox.

**Comment by SaintRaphaelBass** [comment]
ok dzięki, musi być błąd po mojej stronie

**Comment by SaintRaphaelBass** [comment]
Może pan sprawdzić działanie dla mojego zamowienia nr: "44220626"?
