### ISSUE TITLE
PUT /sale/loyalty/promotions 

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2509]
Czy istnieje implementacja metody PUT na zasobie /sale/loyalty/promotions  lub czy i kiedy  planowane jest jej wdrożenie , bo w dokumentacji nic nie ma na ten temat

**Comment by PatrykBocian** [comment]
Na chwilę obecną nie ma takiej możliwości, przekazałem taką sugestię do odpowiedniego zespołu.
