### ISSUE TITLE
Tworzenie aplikacji przy pomocy api

### ISSUE THREAD

**Issue by mfederowicz** [allegro/allegro-api#2510]
Witam

Chciałbym swoim klientom umożliwić dodawanie ofert na allegro poprzez API. Ponieważ klientów mam dużo (powyżej 100) chciałbym aby każdy klient był widoczny w moim systemie jako oddzielna aplikacja

Dla każdego klienta tworzyłbym w api oddzielną aplikację (Client ID oraz Client Secret), dzięki czemu jeżeli będą problemy z wybranym klientem to odłączę jego aplikację

No i teraz pytanie, czy istniej możliwość tworzenia aplikacji z poziomu requestu do api (zakładam że taki request byłby wykonywany przy pomocy danych autoryzacyjnych z konta developerskiego)?

W tej chwili, jak mam kliku klientów to nie ma problemu z przeklikaniem formularza dodawania aplikacji, ale jak tych aplikacji będzie więcej niż 10 to już ręczna obsługa jest już ciut uciążliwa :(

Czy taka funkcja już może istnieje, bądź będzie istniała w niedalekiej przyszłości?

**Comment by mfederowicz** [comment]
#

**Comment by PatrykBocian** [comment]
API nie posiada takiej możliwości. Aby dodać nową aplikację, konieczne jest zarejestrowanie jej przez formularz.

**Comment by mfederowicz** [comment]
Szkoda @PatrykBocian a czy w przyszłości rozważacie może, taką funkcjonalność?

**Comment by PatrykBocian** [comment]
Nie planujemy takiej funkcjonalności po stronie API. Jedyną możliwością na zarejestrowanie aplikacji pozostaje przejście przez formularz.

**Comment by neldh** [comment]
daj linka klientom od razu do panelu z generowaniem kluczy, wraz z instrukcją co i gdzie mają kopiować i niech sami uzupełniają klucze w twojej apce, bez twojego udziału (weryfikuj najwyżej format kluczy). To nie powinno sprawiać im większego problemu (o ile już tak nie masz zrobione).

**Comment by rafalkrupinski** [comment]
Ale po co oddzielna apka? Przecież użytkownik i tak generuje token ze swojego konta. Próbujesz skomplikować prostą architekturę oraz swoje życie ;)

**Comment by mfederowicz** [comment]
Ok wszelkie problemy z autoryzacją userów wstępnie zostały rozwiązane, także temat uważam za zamknięty :P
