### ISSUE TITLE
Parametry klika pytań

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2511]
Witam
Pytam ponieważ natrafiłem na taki przypadek i nie wiem czy mam gdzieś błąd w kodzie czy co....

...odnośnie parametrów:

Wiem że każda z kategorii ma swój zbiór parametrów a każdy z parametrów ma swój id

ale czy jeśli napotkamy na dane id parametru to czy  jego struktura jest identyczna jak struktura parametru o tym samym id w innej kategorii ? ( logicznie patrząc to tak powinno być wg. mnie :) )

Jeśli jest inna to dlaczego?
Jeśli jest inna to czy kiedyś się to zmieni? 

np.
id kategorii

20274
251011
251029
261157

parametr "Szerokość mebla" id 18646
poza kategorią 261157  jest wymagany a w tej nie jest wymagany co jest dziwne....

Nie łatwiej było by to utrzymać w ryzach gdyby dany parametr w całym serwisie mógł przyjmować jednakowe wartości?

Dodatkowo w kategoriach związanych z Meblami - np. Nazwy i id parametrów odpowiedzialne za np. Szerokość mają rożne id różne nazwy a tak naprawdę chodzi o to samo .... 

Jak jest pole tekstowe to da się jeszcze to jakoś mapować z swoją bazą danych i zewnętrznym oprogramowaniem.
Jednak w przypadku słowników itp. jest już znacznie gorzej...

**Comment by PatrykBocian** [comment]
Allegro to żywy organizm, dlatego trudno przyjąć by raz przekazane dane były “pewne” na wieki - tak nie da się efektywnie dopasować do zmieniającego się otoczenia. Rozróżnianie przytoczonego parametru producenta ma na celu prezentowanie wybranych wartości tylko per dana kategoria - producenci dla kategorii X są jedni, a dla kategorii Y drudzy - połączenie tego w całość stworzyłoby ogromne zbiory wartości. Więcej na temat parametrów znajdziesz w tym [newsie](https://github.com/allegro/allegro-api/issues/2160).

**Comment by frankii91** [comment]
tak i nie, ponieważ w kategoriach najniższych mogli by bacy sami w danych drzewach np. mebli

a co z resztą pytań ?

**Comment by frankii91** [comment]
a co do scalania parametrów to ok ale widać ktoś nie zrobił tego poprawnie skoro jedno id miało wskazywać na jeden parametr a w rzeczywistością są dwa a różnią się np. tym że w jednej kategorii jest wymagany a w innej już nie jest wymagamy - chyba że mogą się różnić tyko tym jednym elementem a pozostałe są na pewno takie same ?

**Comment by PatrykBocian** [comment]
W kategorii 261157 parametr nie jest wymagany, ponieważ jest to nowa kategoria, w przyszłości zostanie to uspójnione. Czy zauważyłeś podobne przypadki w innych kategoriach?

**Comment by frankii91** [comment]
Bardzo dużo ... mogę podesłać excel  (jakiś email ? ) który to dość dobrze obrazuje ...   chyba wszystkich kategorii związanych z meblami.
Dodatkowo zauważyłem dzisiaj że kilka parametrów ma typ integer a unit jest null co też raczej nie powinno mieć miejsca.

**Comment by PatrykBocian** [comment]
Wartość null dla pola unit może się zdarzyć, parametr liczbowy może nie mieć jednostki.
Jeśli chodzi o przesłanie pozostałych przypadków, prześlij to proszę przez nasz formularz kontaktowy.

**Comment by frankii91** [comment]
> Wartość null dla pola unit może się zdarzyć, parametr liczbowy może nie mieć jednostki.
> Jeśli chodzi o przesłanie pozostałych przypadków, prześlij to proszę przez nasz formularz kontaktowy.

jaki link? oraz co napisać aby trafiło do odpowiednich osób...

**Comment by PatrykBocian** [comment]
@frankii91 Tutaj znajdziesz link do [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), w zgłoszeniu dopisz proszę #2511.

**Comment by frankii91** [comment]
poszło.

**Comment by PatrykBocian** [comment]
Twoja wiadomość dotarła do nas i przekazałem ją do odpowiedniego zespołu. Jednocześnie mam już odpowiedź:  

Kategoria ID 261157 jest w trakcie nadawania jej parametrów obowiązkowych, dlatego tu prace nadal są w toku. Proces zmian w kategoriach i parametrach jest długofalowy - w chwili tworzenia nowych kategorii staramy się w pierwszej kolejności podpinać istniejące już parametry, jeśli się do tego nadają.

**Comment by frankii91** [comment]
ok ale niech ktoś zwróci uwagę na resztę kategorii bo jest tego znacznie więcej
są też błędy takie jak np. różne wielkości liter w słownikach, spacje na końcu wartości, są też literówki jak np. zamiast małe x jest wielkie X są też słowniki które różnią się tylko tym że w jednym wartości są z małej litery a w innym z wielkiej

**Comment by PatrykBocian** [comment]
Wiemy że zdarzają się takie błędy, staramy się je jak najszybciej poprawiać lecz przy takiej ilości parametrów może to zająć trochę czasu.
Wiedz że zajmujemy się tym tematem i cały czas wprowadzamy kolejne poprawki w tej kwestii.
