### ISSUE TITLE
Wznawianie oferty

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2512]
Witam,
mam problem z wznowieniem aukcji, 
przykładowe żądanie 
`
{"offerCriteria":[{"offers":[{"id":"6206731957"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2019-11-13T9:12:14Z"}}
`
odpowiedź
`
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/22a73791-64f9-4a04-9ac0-08ed13cfdfa4","userMessage":null}]}
`

sam json raczej jest prawidłowy, jest identyczny z tym podanym w dokumentacji - różni się id i datą - oraz po zmianie akcji na END aukcja została zakończona, więc zakładam że sama struktura jest prawidłowa.
Oczywiście z poziomu allegro wznowienie tej aukcji jest możliwe.
Na razie sprawdzałem tylko na sandboxie.

**Comment by PrzemyslawLukanowski** [comment]
Błąd generuje wartość w polu scheduledFor, zamiast "2019-11-13T9:12:14Z" powinieneś przekazać "2019-11-13T09:12:14Z". Ponadto ten numer UUID użyłeś już do zmiany stocku. Pamiętaj, aby przy każdej komendzie korzystać z innego UUID.

**Comment by mzawodzinski** [comment]
Dalej to samo 
`
{"offerCriteria":[{"offers":[{"id":"6206731957"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2019-11-14T07:50:09"}}
`
odpowiedź 
`
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/46d9a9fe-2fee-4173-9a41-1905e931ba45","userMessage":null}]}
`

**Comment by PrzemyslawLukanowski** [comment]
W polu scheduledFor za datą dodaj Z, czyli 2019-11-14T07:50:09Z.

**Comment by mzawodzinski** [comment]
ok zadziałało
