### ISSUE TITLE
Zasób /sale/offers zwraca błędną cenę końcową w ofercie

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#2515]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Zasób /sale/offers?offer.id=8509126073 w polu saleInfo.currentPrice.amount zwraca wartość "10.5", 
 a w tym przypadku wartość powinna być "1.0"

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - występuje rozbieżność pomiędzy frontem a API. Zgłosiłem ten problem do odpowiedniego zespołu.
