### ISSUE TITLE
GET /offers/listing - wyszukiwanie nie pokrywa się z frontem

### ISSUE THREAD

**Issue by Masakrancja** [allegro/allegro-api#2516]
Witam
Sprawa dotyczy metody GET /offers/listing 
Chcę pobrać: pierwsze 100 aukcji w kategorii nr  63758 posortowane po trafności 
Wysyłam do Allegro przez GET zapytanie sparametryzowane:
https://api.allegro.pl/offers/listing?category.id=63758&sort=-relevance&offset=0&limit=100&fallback=false

Odpowiednik na froncie tego zapytania to:
https://allegro.pl/kategoria/bdsm-63758?bmatch=baseline-dict42-ero-1-4-1024

Niestety kolejność aukcji pobrana przez Rest Api wogóle nie pokrywa się z wyszukiwarką allegro. Pobrana kolejność aukcji jest całkowicie wymieszana.

Jeżeli jest coś czego nie dostrzegam i robię nie tak to proszę o wskazówkę..

Pozdrawiam..

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - zasób i parametry działają poprawnie. W response nie są jedynie uwzględnione oferty sponsorowane. Czy możesz przesłać nam za pomocą naszego [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełen request i response z dopiskiem github #2516?

**Comment by Masakrancja** [comment]
Witam.
Zostało przesłane. 
Numer "07108525" ref:_00D24aE05._5001o45ouzx:ref

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy to, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@Masakrancja Czy możesz spróbować wysłać to zapytanie z ciastkiem cookieMonsterUserId? Jeśli ustawisz to ciastko, wyniki powinny być odpowiednio posortowane.

**Comment by Masakrancja** [comment]
Witam,
Dziekuję za informacje.
Jeżeli Pan mówi o zwykłym ustawieniu ciastka w skrypcie, np u mnie w php:
setcookie('userID', 'Cookie Monster');

To niestety nie działa. 
Jeżeli przez ustawienie ciastka: cookieMonsterUserId miał Pan na myśli coś innego to proszę o wskazówkę lub link do dokumentacji restapi allegro..

Z góry dziękuję,
Pozdrawiam,

**Comment by PrzemyslawLukanowski** [comment]
Po weryfikacji udało mi się ustalić, że parametr relevance może nie zwracać na API tak samo posortowanych wyników, jak na froncie. Ustawienie ciastka cookie monster jednak nie będzie w tym przypadku rozwiązaniem problemu.

**Comment by Masakrancja** [comment]
Witam,
Dziękuje za informacje. 
Proszę zatem napisać czy jest możliwość, że w dającej się przewidzieć przyszłości to udogodnienie zacznie działać zgodnie z sortowaniem revelance tak jak to w dokumentacji opisane?
https://developer.allegro.pl/documentation/#operation/getListing

Z góry dziękuję,
Pozdrawiam,

**Comment by PrzemyslawLukanowski** [comment]
@Masakrancja Weryfikuję ten temat, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Obecna sytuacja nie jest błędem tylko jednym z możliwych podejść. Publiczne API jest odpytywane przez aplikacje pisane przez wielu developerów. Dlatego też możliwe jest stworzenie aplikacji, w której developer zahardkodował swój token w celu komunikacji z naszym api i wówczas wszyscy będą przedstawiać się tym samym użytkownikiem. W obecnej sytuacji zwracamy wyniki z jakimiś domyślnymi ustawieniami.

**Comment by Masakrancja** [comment]
Witam,
Dziękuję za informacje.
Czyli jak rozumiem sortowanie po revelance przez API (z różnych powodów) nie będzie się pokrywać z frontem, tylko wyniki w tym przypadku zawierają jakieś domyślne ustawienia sortowania?
Zaznaczam, że inne sposoby sortowania działają jednak poprawnie..

Z góry dziękuję,
Pozdrawiam,

**Comment by PrzemyslawLukanowski** [comment]
Wyniki trafności na froncie także mogą się różnić w zależności od użytkownika. Ruch jest dzielony na kilka różnych modeli trafności, użytkownicy API wpadają do jednej z grup trafności, która różni się od tej, w której user sprawdza sobie wyniki z frontem. Jest to spowodowane tym, że użytkownicy API nie wykorzystują wyników w sposób, w jaki robią to regularni użytkownicy i dlatego nie są przypisani do tych samych grup. Nie jest to "gorsza trafność", tylko jedna z wersji tego samego systemu.

**Comment by Masakrancja** [comment]
Witam,
Wyjaśnione.

Dziękuję za informacje.
Pozdrawiam,
