### ISSUE TITLE
about the API of offer management

### ISSUE THREAD

**Issue by CECchina** [allegro/allegro-api#2517]
Hello,guide: 

We have a question about the API of the offer management, and look forward to your support.

We found we can add some custom parameters when editing the offer from the website like this:
![1](https://user-images.githubusercontent.com/55833259/68820883-a7b2e880-06c7-11ea-99b5-ee1e587849eb.jpg)
![2](https://user-images.githubusercontent.com/55833259/68820898-b0a3ba00-06c7-11ea-8a66-10fba9a607b0.jpg)

But I cann't find the corresponding parameters in the API, 
Does the rest API support setting custom parameters? Looking forward to your reply. thank you!

**Comment by PrzemyslawLukanowski** [comment]
API doesn't support custom parameters, it's available only from website.

**Comment by CECchina** [comment]
OK，I got it. thank you very much!
