### ISSUE TITLE
Błędy

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2518]
Nadal nie działa, rozliczanie płatności, a nowego konta nie mogę założyć bo nie działają linki aktywacyjne. Co mam zrobić, żeby móc testować wystawianie ofert?

**Comment by MaciejFrackowiak** [comment]
Zgadza się, problem z symulatorem nadal występuje, o czym informowałem w osobnym poście. Natomiast nie potwierdzam problemu z rejestracją konta Sandbox - proszę podaj ID utworzonego konta.

**Comment by SaintRaphaelBass** [comment]
https://user-images.githubusercontent.com/38372822/68838529-10499780-06bf-11ea-9c75-c46721c64f66.png

**Comment by SaintRaphaelBass** [comment]
Nie znam id

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie rejestracji konta na Sandbox - otrzymałem email weryfikacyjny i bezproblemowo potwierdziłem jego aktywację. Proszę skopiuj adres bezpośrednio z wiadomości i wklej go do przeglądarki.

**Comment by SaintRaphaelBass** [comment]
Message from WebAPI Sandbox environment
14 lis 2019 09:10 (godzinę temu)
Allegro Sandbox no-reply@allegrosandbox.pl
domnie(więcej)
Subject: Message from allegro.pl.allegrosandbox.pl environment
From: allegro.pl.allegrosandbox.pl <no-reply@allegro.pl.allegrosandbox.pl>

Hello,

This email has been sent from allegro.pl.allegrosandbox.pl environment.
For security reasons, the original message is attached to this email in EML format.
-
Regards
https://allegro.pl.allegrosandbox.pl/

**Comment by SaintRaphaelBass** [comment]
Tak wygląda moja wiadomość w przeglądarce, a link aktywacyjny jest w zalączniku

**Comment by SaintRaphaelBass** [comment]
Jak przekleje link to wyswietla mi sie strona 404

**Comment by SaintRaphaelBass** [comment]
Podejrzewam, że to problem z pocztą o2

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy wpływu na bezpośrednie działanie serwisów pocztowych - proszę skorzystaj zatem z alternatywnego dostawcy poczty dla założenia konta testowego.
