### ISSUE TITLE
offers/offer-events 24 godziny

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#2519]
https://developer.allegro.pl/my_offers/ widnieje informacja "to dziennik zdarzeń w ofertach zalogowanego sprzedawcy, który zwraca informacje z ostatnich 24 godzin".

Jak sobie wyobrażacie sytuacje awarii systemu korzystającego z API (lub nawet samego API)?
W specyficznych przypadkach może dojść do awarii po stronie użytkownika API gdzie przerwa wyniesie więcej niż 24h, jaką wtedy ma on szansę na pobranie "zaległości"?
Dla niektórych klientów sa to setki jak nie tysiące zamówień których nie można pobrać.
W API SOAP te dane można było pobierać min. 7 dni wstecz.

**Comment by pawelosajda** [comment]
Z tego co widze dla zamówień jest 60 dni
https://developer.allegro.pl/orders/
"Możesz pobrać zdarzenia z ostatnich 60 dni"

**Comment by PatrykBocian** [comment]
Zasób **GET sale/offer-events** zawsze zwraca info sprzed ostatnich 24h. W przypadku awarii staramy się ją jak najszybciej wyeliminować, więc sytuacja gdzie będzie trwała ponad 24h nie powinna nigdy mieć miejsca.
Jeśli chodzi o zamówienia, jest tak jak pisał @pawelosajda  -  za pomocą **GET/order/events** 60 dni, a za pomocą **GET/order/checkout-forms** 180 dni.

**Comment by j4r3kb** [comment]
Pisałem nie tylko o awarii systemu Allegro. Chodzi tez o awarie w systemach korzystających z API.
Co zrobimy jeśli jakimś cudem przez 24 nikt nie wykryje awarii w procesie pobierania zdarzeń z aukcji?
Nie odzyskamy tego w żaden sposób a te informacje sa dość ważne (zamknięcie aukcji np.).
Jakieś 72h były by już przyjemniejsze.

**Comment by PatrykBocian** [comment]
@j4r3kb Zgłosiłem sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się na wdrożenie takiej zmiany, poinformujemy o tym w odpowiednim komunikacie.
