### ISSUE TITLE
Błąd przy wystawianiu aukcji - na sandboxie nie występuje.

### ISSUE THREAD

**Issue by kkraszy** [allegro/allegro-api#252]
Witam,

Przebudowałem stary moduł allegro do systemu Magento na nowego WSDL'a. Na sandboxie wszystkie testy przeszły ok, przepiołem na WSDL produkcyjny i mam taki oto komunikat przy wystawianiu aukcji: 

Element '{https://webapi.allegro.pl/service.php}fvalueImage': '0' is not a valid value of the atomic type 'xs:base64Binary'.

Moje  pole 'fields' w doNewAuctionExt wyglada tak:  https://pastebin.com/s6Rxxm8T

**Comment by MartaNowaczyk** [comment]
Witam,
Pole fvalueImage powinno być puste jeżeli fid nie dotyczy zdjęcia. Podanie wartości '0' jest błędem.
Na sandboxie taka wartość też powinna zwracać błąd. Podeślij proszę paczki XML testów na sandboxie, gdzie ta wartośc przechodzi bez problemu.

**Comment by kkraszy** [comment]
Witam, 
Wcześniej na sandboxie miałem fvalueImage ustawione jako => ' ' (string z jednym pustym znakiem) i działało dobrze, na wsdl produkcyjnym już to nie działało i kierując się różnymi opisami z internetu zmieniłem na '0'. 
Dziękuję ustawianie całkowicie pustego stringa pomogło.
