### ISSUE TITLE
Dziennik dla platformy

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#2520]
Hej!
Jest dziennik zdarzeń dla zalogowanego sprzedawcy. W którymś wątki mówiliście, że planujecie dziennik dla platformy (tak jak w webapi). Czy coś wiadomo w tej kwestii?

**Comment by PatrykBocian** [comment]
Na tę chwilę działamy zgodnie z [harmonogramem](https://developer.allegro.pl/schedule/). Czy możesz przedstawić potrzebę posiadania tego zasobu?

**Comment by jakubmaguza** [comment]
Hej,
Zgodnie z harmonogramem, taki zasób powinien pojawić się w październiku:
![image](https://user-images.githubusercontent.com/24191650/68932609-45bfb500-0793-11ea-9a5d-8cc0cb3a0352.png)

Zasób z WebApi usuniecie w Lutym.

**Comment by jakubmaguza** [comment]
Ah, widzę że nie jest to rozdzielone na miesiące. Więc pytanie: czy ten zasób pojawi się w Q4?

**Comment by PatrykBocian** [comment]
Jak wspomniałem, działamy według harmonogramu.  Gdyby w tej kwestii coś się zmieniło i pojawiłyby się opóźnienia, poinformujemy o tym.

**Comment by jakubmaguza** [comment]
Czy zgodnie z harmonogramem metoda pojawi się do końca roku?

**Comment by PatrykBocian** [comment]
Na tę chwile nie zmieniamy harmonogramu - gdyby coś się zmieniło to przekażemy osobny komunikat..

**Comment by jakubmaguza** [comment]
Kochane Allegro,
Rok się skończył, mimo waszych zapewnień nie przekazaliście żadnej informacji. Metody, o której mowa w tym temacie dalej nie ma. Możecie się określić trochę konkretniej niż "Patrz w harmonogram, a my i tak zrobimy kiedy chcemy"?

**Comment by PatrykBocian** [comment]
Daty podane w harmonogramie są wstępnymi planowanymi terminami zmian - może się zdarzyć, że powstanie opóźnienie. W takich przypadkach aktualizujemy harmonogram. Odnosząc się do dziennika zdarzeń dla platformy o ofercie - prace są w toku, do końca miesiąca postaramy się przekazać jednoznaczne informacje.
