### ISSUE TITLE
AllegroSandbox Error 500 Internal Server Error - /order/checkout-forms

### ISSUE THREAD

**Issue by giangia76** [allegro/allegro-api#2521]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

trace-id
e9a2d22914714f8d

https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms 
500 Internal Server Error

GET /order/checkout-forms
Host: api.allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json
Authorization: Bearer xxxxxxxxxxxx

{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
Czy problem występuje u Ciebie w dalszym ciągu? Zweryfikowałem to na wybranych zasobach i w żadnym przypadku nie otrzymałem statusu 500.

**Comment by giangia76** [comment]
Tak, cały czas mam ten sam problem

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że nie korzystasz z autoryzacji typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Otrzymałem podobny błąd właśnie w takim przypadku. W celu uzyskania poprawnej odpowiedzi wykorzystaj autoryzację typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).

**Comment by giangia76** [comment]
fakt.

zmieniłem na device ale teraz mam błąd 415 Unsupported Media Type

POST https://allegro.pl.allegrosandbox.pl/auth/oauth/device
Authorization Client ID / klucz WebAPI + Client Secret otrzymane po zarejestrowanie aplikacji

Response:
{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/auth/oauth/device",
            "userMessage": null
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę pełen request w formacie cURL za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) z dopiskiem GitHub #2521.

**Comment by PrzemyslawLukanowski** [comment]
@giangia76  Otrzymaliśmy Twój request. Spróbuj przekazać w URL informacje o client_id - POST https://allegro.pl.allegrosandbox.pl/auth/oauth/device?client_id={client_Id}. Zweryfikowałem to i po dodaniu tych danych otrzymuję prawidłową odpowiedź.
