### ISSUE TITLE
offers/offer-events - nie działa prawidłowo

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2522]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-id - 1c8c4c5ca1205e69

Zdaje się, że nie działa filtrowanie po eventach dla endpointu **offers/offer-events**:

Request:

> GET /sale/offer-events HTTP/1.1
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
{"from":"MTU3MzgyMTkyOTcwOTEzNQ","limit":1000,"type":"OFFER_ENDED"}

> 
za każdym razem zwraca te same wyniki, gdzie wartość **from** jest ostatnią wartością, jaka przychodzi z API, a więc nie powinienem już otrzymać nic więcej. Dodatkowo nie działa też filtrowanie po typie. Zwracane są wszystkie wpisy tak jakbym nie wpisywał nic do **from** oraz **type**.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i zasób działa prawidłowo. Otrzymuję różne wyniki w zależności od ustawionych parametrów. Jak dokładnie przekazujesz parametry? W powyższym requeście widzę, że nie znajdują się w adresie url. Przykładowe prawidłowe odpytanie zasobu:

GET sale/offer-events?from=MTU3Mzk5MjU2NDc0MTY3Mg&limit=1000&type=OFFER_ENDED

**Comment by bacok** [comment]
Ok, już wiem gdzie popełniłem błąd. 
Dziękuję za pomoc.
