### ISSUE TITLE
/sale/offer-publication-commands/{commandId} - nie można aktywować oferty

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2523]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy próbie publikacji niektórych szkiców w/w zasobem zwraca dziwny błąd: 
`{"code":"VALIDATION_ERROR","message":"must not be empty","details":"Invalid value: ","path":"offerCriteria[0].offers[].id","userMessage":"must not be empty"}`
Co ciekawe nie występuje to we wszystkich ofertach. Tylko przy niektórych. Co więcej, gdy wejdziemy w ofertę poprzez backend Allegro, jak najbardziej można ją opublikować. Nie widać także, żeby walidacja coś zwracała błędnego.

**Comment by PrzemyslawLukanowski** [comment]
Błąd wskazuje na to, że nie została przekazana żadna wartość w polu offerCritieria.offers.id. Zweryfikowałem to - udało mi się powtórzyć ten błąd. Upewnij się, że we wspomnianych requestach przekazywałeś numer id oferty. Jeśli nadal zauwyżyłeś, że błąd występuje, prześlij nam przykładowe numery draftów.
