### ISSUE TITLE
Forbidden na endpoincie /me

### ISSUE THREAD

**Issue by barttom** [allegro/allegro-api#2524]
Hej!

Pod odpytanie '/me' otrzymuję bląd o braku uprawnień (co jest mega dziwne gdy logując się tokenem nie mogę otrzymać informacji o sobie :) )
Czy powinienem dodać jakiś nagłówek, lub gdzieś dodać uprawnienie?
```
{
    "errors": [
        {
            "code": "ForbiddenException",
            "message": "Client doesn't have required roles",
            "details": "FORBIDDEN",
            "path": "",
            "userMessage": "Forbidden access"
        }
    ]
}
```

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że nie korzystasz z autoryzacji typu [client-credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow) - udało mi się powtórzyć ten błąd przy takim przypadku.  Dla tego zasobu wymagana jest autorzyacja typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow.

**Comment by barttom** [comment]
No i mamy winnego, dzięki!
