### ISSUE TITLE
(Nie)zamykanie licytacji, jeżeli ma ona już zalicytowania

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2526]
:bulb: **Sugestia**

Dobry,
chciałbym zgłosić uwagę dotyczącą zamykania aukcji. Otóż zamykanie przez API wiąże się ze sprzedaniem przedmiotu, jeżeli licytacja jest zalicytowana. Chciałbym całkowicie unikać takich sytuacji, dlatego proponuję dodanie parametru dla tej operacji, który by powstrzymywał zasób od zamykania aukcji, które ktoś zalicytował. Ewentualnie inne rozwiązanie, które pozwoli wybrać, czy aukcja ma zostać sprzedana z zamknięciem, czy pominięta ze względu na zalicytowania (np. jako dwie osobne operacje).

**Comment by PatrykBocian** [comment]
Dziękujemy za sugestie, zgłosiłem ją do odpowiedniego zespołu. Jeśli zdecydujemy się na wprowadzenie takiej zmiany, poinformujemy o tym w odpowiednim komunikacie.

**Comment by HMX24** [comment]
dołączam bardzo ważna kwestia a tak sie nie powinno wydarzyc ze sie sprzedaje przedmiot

**Comment by PatrykBocian** [comment]
@HMX24 Zgłosiłem, że więcej osób oczekuje tego typu rozwiązań.
