### ISSUE TITLE
Nie można wysłać nr przesyłki do Allegro

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#2527]
Dzień dobry,
z jakiegoś powodu podczas próby zapisania nr przesyłki do zamówienia (DPD), dzieją się..dziwne rzeczy? Przede wszystkim numer się nie zapisuje, zwraca błąd. (Z innymi przewoznikami nie zarejestrowałem jeszcze takiego problemu)

Wysłana tablica oraz nic nie mówiąca informacja zwrotna (jest błąd bo błąd)

`Array
(
    [carrierId] => DPD
    [waybill] => SimpleXMLElement Object
        (
            [0] => 0000189605718U
        )
    [lineItems] => Array
        (
            [0] => Array
                (
                    [id] => c452aa10-09d4-11ea-b997-357a186738cb
                )
        )
)
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/order/checkout-forms/c452d121-09d4-11ea-b997-357a186738cb/shipments","userMessage":null}]}
`

Żeby było śmieszniej, przed chwilą wykonałem tą samą funkcję kilka razy (różne numery paczek), za każdym razem otrzymywałem w informacji zwrotnej błąd.. aż nagle z nikąd pojawiło się kilka paczek przypisanych do zamówienia (poprzednie próby dodania numeru). Zaznaczę, że poprzednie - bieżącego, nowego numeru przesyłki nie było.

**Comment by PrzemyslawLukanowski** [comment]
Na podstawie logów, dla tego konkretnego zapytania, widzę błędną strukturę:

```
{
	"carrierId": "DPD",
	"waybill": {
		"0": "0000189605253U"
	},
	"lineItems": [{
		"id": "c452aa10-09d4-11ea-b997-357a186738cb"
	}]
}
```

Pole waybill jest obiektem, a powinno być stringiem. To generuje błąd 400.
