### ISSUE TITLE
Image upload problem CODE 415

### ISSUE THREAD

**Issue by Nemanja-Lima** [allegro/allegro-api#2528]
Hi guys, can someone help me with this problem?

        $data = ["url" => "https://www.mytrendyphone.pl//images2/Goobay-HDMI-Extension-Cable-with-Ethernet-5m-02082018-01-p.jpg"];

        $setOffers = "https://upload.allegro.pl.allegrosandbox.pl/sale/images";
        $client = new GuzzleHttp\Client(['verify' => false]);

        try {
            $res = $client->request('POST', $setOffers, [
                'headers' => ["Authorization" => 'Bearer ' . Cache::get('token_allegro'), "Accept" => "application/vnd.allegro.public.v1+json", 'Content-Type: application/vnd.allegro.public.v1+json'],
                'body' => json_encode($data)
            ]);
            $res = json_decode($res->getBody()->getContents());
            return response()->json(['data' => $res]);
        } catch (GuzzleHttp\Exception\GuzzleException $e) {
            $response = $e->getResponse();

            $result = json_decode($response->getBody()->getContents());
            return response()->json(['Photo error data' => $result]);

        }

and response is:

         {
            "Photo error data": {
                        "errors": [{
                                        "code": "415 UNSUPPORTED_MEDIA_TYPE",
                                        "message": null,
                                        "details": null,
                                        "path": null,
                                        "userMessage": "Unallowed image type."
                                     }]
                          }
        }

I think that image fits your requirement.

**Comment by PrzemyslawLukanowski** [comment]
I tried to upload this picture - in response I've received status 200 with link to the image. Due to multiple programming language we don't provide support for each of them. Could you please send us full request in cURL format via our [contact form](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) with a note - GitHub #2528.

**Comment by Nemanja-Lima** [comment]
I fixed it. Thank you anyway mate.
