### ISSUE TITLE
VALIDATION_ERROR help

### ISSUE THREAD

**Issue by Nemanja-Lima** [allegro/allegro-api#2529]
Hi guys. Can someone help me with this 2 validation error messages ERR_BLOCK_SELL_COMPANY_INFO and ERR_IF_YOU_WANNA_SELL 
I think it is about account activation but I'm not so sure. 
I use vlp@mytrendyphone.eu for login. I guess you need it to check acc.
Account is on sandbox, but u can check it on "not test environment" too
cause I will need it there too. Thank you in advance

**Comment by PrzemyslawLukanowski** [comment]
Hi, your account hasn't been fully activated - you need to upload any two files in "[Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php)" tab ("choose file" button, then "wyślij do weryfikacji"). Error shouldn't occur on production - your account is activated.
