### ISSUE TITLE
REST API oraz niespójność nazwenictwa

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#253]
Proszę o wyjaśnienie jednego drobiazgu

sellerID dla metody np. /after-sales-service-conditions/return-policies

mam już tak dużo różnych Id'ków że nie wiem który to sellerId (nie znalazłem takiej nazwy)
czy to ?
ośmio znakowy API Key: 22AAff88
czy 
Client ID / WebAPI key z resat api
a może Client Secret z rest api 

i jeszcze jedno pytanie:

czy w tej metodzie (oraz metodach powiązanych) parametr sellerId jest wymagany ?

**Comment by AniaMalinowska** [comment]
SellerID, czyli Twój nr ID na Allegro - znajdziesz go w pasku adresu, gdy wejdziesz na stronę swojego konta, na zakładkę '[oceny i komentarze](https://allegro.pl/uzytkownik/1680/oceny)' - link na przykładzie Oficjalnego sklepu Allegro.

Informacje na temat wspomnianych Client ID oraz Client Secret znajdziesz m.in. [tutaj](https://developer.allegro.pl/auth/).

Tak, SellerID jest wymagany, aby np. pobrać warunki oferty dla danego konta.

**Comment by imper86** [comment]
@wwwfactory możesz też sobie ułatwić nieco sprawę i wyciągnąć ten id z tokena, którego używasz do obsługi rest api allegro. Możesz np skorzystać z biblioteki lcobucci/jwt jeśli korzystasz z PHP.
