### ISSUE TITLE
Połączenie dziennika zdarzeń WebApi z REST

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2531]
Hej.
Jesteśmy w trakcie przechodzenia z SOAP na REST i nie jesteśmy w stanie opracować sposobu jak rozbudować aktualny mechanizm zachowując kompatybilność wsteczną.
Obecnie mamy tabelę, w której zapisujemy wszystkie dane z **doGetSiteJournalDeals** na podstawie których później procesujemy zamówienia. Do pobierania najnowszych eventów wysyłamy ostatnio otrzymaną wartość **dealEventId** przypisaną do danego konta.
Problemem jest brak kompatybilności wstecznej, ponieważ w REST na zasobie **/order/events** nie zmapujemy wartości **from** mając **dealEventId** z SOAP. Przy przepięciu potrzebujemy tej wartości aby zachować ciągłość, inaczej skutkiem będą zdublowane zamówienia, na co nie możemy sobie pozwolić przy obecnym obciążeniu u klientów, których obsługujemy.
Pobieranie nadmiarowych danych tylko po to, żeby je obrobić i sprawdzić poprzez https://github.com/allegro/allegro-api/issues/731 czy nie mamy już obsłużonego zamówienia również nie wchodzi w grę.
W skrócie - brakuje mappera pod identyfikatory zdarzeń pomiędzy SOAP a REST.
Czy jest szansa aby wprowadzić taką funkcjonalność?

**Comment by PatrykBocian** [comment]
Możesz skorzystać w tym przypadku z [GET/payments/payment-id-mappings](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping) i zmapować transactionId na paymentId i przekazujesz go jako parametr w GET order/checkout-forms?{payment.id}.
Czy takie rozwiązanie jest dla ciebie optymalne?

**Comment by bacok** [comment]
Ze względu na różne eventy transakcyjne (zakup, wypełnienie formularza dostawy i opłacenie) - każdy z nich ma swoją określoną rolę. Przykładowo event zakupu tworzy rezerwację na magazynie aby nie dopuścić do sytuacji, gdy ktoś dopiero po kilku dniach wypełni formularz dostawy i zapłaci a w międzyczasie towar wyprzeda się od strony sklepu WWW i stan produktu zejdzie poniżej zera.
Po wypełnieniu formularza dostawy tworzymy w systemie zamówienie, ale nie będę się na ten temat rozpisywał, jest to po prostu wymóg biznesowy.
Pański sposób dotyczy jedynie końcowej ścieżki gdy wszystko jest już kompletne i opłacone (wtedy dopiero mamy identyfikator płatności), a to niestety nie wyczerpuje tematu w całości.

Nawiązując do mojej pierwszej wypowiedzi - chodzi mi o zachowanie ciągłości w pobieraniu i obsłudze zdarzeń, dlatego potrzebowałbym w jakiś sposób identyfikować **dealEventId** lub **dealId** z metody **doGetSiteJournalDeals** pobranego z SOAP na identyfikator podawany w **from** dla endpointu **/order/events**.

**Comment by bacok** [comment]
@PatrykBocian czy mogę prosić o odpowiedź? Zegarek tyka, termin się zbliża i potrzebujemy przygotować optymalne rozwiązanie aby móc dalej pobierać zdarzenia przyrostowo.

**Comment by PatrykBocian** [comment]
Co do sytuacji którą opisałeś:
“Przykładowo event zakupu tworzy rezerwację na magazynie aby nie dopuścić do sytuacji, gdy ktoś dopiero po kilku dniach wypełni formularz dostawy i zapłaci a w międzyczasie towar wyprzeda się od strony sklepu WWW i stan produktu zejdzie poniżej zera.”

Obecnie użytkownik musi wypełnić formularz dostawy i wybrać “Kupuję i płacę”, aby zakupić przedmiot. Dlatego w zdecydowanej większości przypadków pojawią się dwa zdarzenia naraz - BOUGHT i FILLED_IN. Sam event BOUGHT może występować sporadycznie, dotyczy starszych, nie zaktualizowanych aplikacji mobilnych na androida.

Aby zachować ciągłość w pobieraniu zdarzeń, wykorzystaj [mapowanie dealId na lineItemId](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET). 

Obecnie nie ma innej możliwości, jednak zgłosiłem twoją sugestię do odpowiedniego zespołu.
Gdybyśmy zdecydowali się na wprowadzenie takiej funkcjonalności, poinformujemy o tym w odpowiednim komunikacie.

**Comment by bacok** [comment]
Przygotowaliśmy już takie mapowanie na podstawie https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET, jednak przeprowadzając testy na produkcyjnym koncie jednego z klientów obrabiamy ponad 22 000 eventów tylko po to, aby się dobrać do jednego identyfikatora.
Jest to spore obejście problemu zważywszy na to, że to konto miało zaledwie 600 aktywnych aukcji, a mamy klientów z ilościami rzędu kilkunastu tysięcy.

**Comment by PatrykBocian** [comment]
Odnośnie “Pański sposób dotyczy jedynie końcowej ścieżki gdy wszystko jest już kompletne i opłacone (wtedy dopiero mamy identyfikator płatności), a to niestety nie wyczerpuje tematu w całości.”

Użytkownik kupuje przedmiot poprzez uzupełnienie formularza dostawy i wybranie “Kupuję i płacę”. Na tym etapie tworzą się eventy BOUGHT i FILLED_IN oraz zamówienie otrzymuje payment.id i transactionId, mimo że płatność nie jest jeszcze zakończona. Oznacza to, że już teraz możesz skorzystać z mapowania płatności transactionID na paymentId.

Tak jak pisaliśmy wcześniej, event BOUGHT może występować sporadycznie, dotyczy starszych, niezaktualizowanych aplikacji mobilnych na androida.
