### ISSUE TITLE
Błąd dodawania numeru listu przewozowego

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2533]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

Nie mogę dodać numeru listu przewozowego do zamówienia przez REST API oraz przez panel.
Powodem jest walidacja która nie przepuszcza jak jest spacja w numerze listu.
Dodam że przez WebAPI to działało
Poprawcie to szybko

**Comment by avello** [comment]
Od razu pytanie w jaki sposób dodać taki numer listu ?

**Comment by PatrykBocian** [comment]
Weryfikuje twoje zgłoszenie, jak tylko się czegoś dowiem, wrócę z odpowiedzią.

**Comment by PatrykBocian** [comment]
Czy możesz jeszcze dopisać, u którego przewoźnika zauważyłeś numery listu z spacjami?

**Comment by avello** [comment]
Spedytor to Dachser.
Wzór numeru to: NET 99999/9/9999
Spacja jest wymagana, sprawdziłem wyszukiwanie na stronie przewoźnika czy wyszuka bez podania spacji i niestety nie.
https://elogistics.dachser.com/login/home?6

**Comment by PatrykBocian** [comment]
Czy mógłbyś z swojej strony zweryfikować czy na stronie tego przewoźnika, strona lokalizuje przesyłkę o której mówisz bez wpisywania spacji?
Jeśli tak to można by to rozwiązać w ten sposób, aby wpisywać w API te numery bez spacji.

**Comment by avello** [comment]
Proszę przeczytać komentarz wyżej

**Comment by PatrykBocian** [comment]
Weryfikuje twoją sprawę, jak tylko coś ustale, wrócę z odpowiedzią.

**Comment by avello** [comment]
Problem nadal występuje. Czekam na poprawkę.

**Comment by PatrykBocian** [comment]
Pamiętamy o twoim zgłoszeniu - pracujemy nad rozwiązaniem tego problemu.

**Comment by avello** [comment]
Witam, jak postępy w pracach?
Obecnie nie można dodawać listów przewozowych które mają spacje, za pomocą RestAPI oraz panel allegro. Jedyną opcją jest użycie metody z WebAPI doAddPackageInfoToPostBuyForm którą używam zastępczo do momentu naprawy błędu. Jednak już 13.01.2020 planujecie ją usunąć. Więc nie będzie żadnej możliwości dodawania takich listów przewozowych. 
Wyrobicie się do tego czasu z poprawkami? Bo mam obawy, bo 2 miesiące nie wystarczyły jak do tej pory.

**Comment by PatrykBocian** [comment]
Pracę w tym kierunku wciąż trwają - jak tylko otrzymam jakąś informację to dam znać.

**Comment by PatrykBocian** [comment]
Jeśli chodzi o format listu przewozowego od Dasher - czy na pewno dostałeś prawidłowy numer listu? (może został wysłany w złym formacie).
Sam przewoźnik przekazał nam informacje, że prawidłowym formatem numeracji przesyłek jest ciąg 11 cyfr bez spacji. Tutaj prośba, abyś zweryfikował poprawność numeru.

**Comment by avello** [comment]
Sprawdziłem co jest na stronie przewoźnika i zgadza się.
Przez cały czas otrzymywałem numer referencyjny przesyłki i informację że jest to numer listu przewozowego. 
Okazuje się że jest też inny numer 11 cyfr bez spacji jako numer listu. 
Oba numery działają w wyszukiwarce przewoźnika, więc przekażę informację aby używać tego drugiego. 
Problem można uznać za rozwiązany i zamknąć.
Dziękuję.
