### ISSUE TITLE
Pytanie o zasób order/events

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2534]
Przy którym statusie BOUGHT czy FILLED_IN aukcja jest oznaczana jako "zakończona"?

**Comment by PrzemyslawLukanowski** [comment]
Nie wiem, czy do końca rozumiem Twoje pytanie. W przypadku zakończenia licytacji pojawia się jeden status BOUGHT. FILLED_IN pojawia się również raz - po wypełnieniu FODa. Inna sytuacja - w ofercie jest dostępny jeden przedmiot, który kupił użytkownik, tym samym ją zakończył. Wtedy pojawi się status BOUGHT oraz FILLED_IN. Dziennik zdarzeń informuje, na jakim etapie realizacji zamówienia jest klient, nie ma tam informacji o tym, czy dana oferta jest już zakończona. Czy możesz doprecyzować swoje zgłoszenie?

**Comment by crazyhtm** [comment]
Przepraszam, powinienem od razu sprecyzować.

Tak, chodzi o przypadek kiedy w ofercie jest tylko jeden przedmiot, format aukcji BUY_NOW . 

Chodzi o sytuację kiedy klient rozpoczął płatność ale jej jeszcze nie zakończył. 
Jak rozumiem wtedy jest nadany status BOUGHT i aukcja przestaje być dostępna dla innych kupujących. 
Czyli, status BOUGHT (w tym przypadku) informuję mnie że aukcja została wycofana z obrotu i czeka na to co zrobi klient. 
 
W konsekwencji, jeżeli klient nie dokończy płatności to musimy taką aukcję wystawić ponownie.

**Czy dobrze myślę?** 

Jescze jedno pytanko, jeżeli taka "nie kupiona" aukcja zostanie przez nas wznowiona to jakie będzie jej ID stare (takie jak przed próbą zakupu) czy nowe?

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku pojawi się status BOUGHT oraz FILLED_IN - użytkownik musi uzupełnić dane w formularzu dostawy i wybrać "Kupuję i płacę", dopiero wtedy kupuje przedmiot. Mogą się zdarzyć sporadycznie sytuacje, gdzie będzie występować tylko status BOUGHT (wtedy kupno następuje już po wybraniu Kup Teraz). Dotyczy to starszych, niezaktualizowanych aplikacji mobilnych na androida.

> Jescze jedno pytanko, jeżeli taka "nie kupiona" aukcja zostanie przez nas wznowiona to jakie będzie jej ID stare (takie jak przed próbą zakupu) czy nowe?

Będzie miała takie samo ID, wcześniej musisz także zmienić stock, bo w tej sytuacji wynosi 0.

**Comment by crazyhtm** [comment]
Wszystko jasne, dziękuję bardzo
