### ISSUE TITLE
Aukcja, która została zamknięta, ale widnieje jako aktywna

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#2535]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dobry,

zgłaszam problem z aukcją o numerze 8677906988. Zarówno front Allegro, jak i API zwraca tą aukcję jako aktywną, kiedy wchodząc bezpośrednio na stronę aukcji widnieje, że została zakończona.

**Comment by PrzemyslawLukanowski** [comment]
Czy problem w dalszym ciągu występuje? Zweryfikowałem to i zarówno front, jak i API zwraca informację o zakończonej oferty.

**Comment by hahyes** [comment]
> 
> 
> Czy problem w dalszym ciągu występuje? Zweryfikowałem to i zarówno front, jak i API zwraca informację o zakończonej ofercie.

Dla zasobu `/sale/offers?offer.id=8677906988` wciąż problem występuje (zwraca status ACTIVE), tak samo aukcja jest wyszukiwana jako aktywna na portalu w Moje oferty.

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, zweryfikowałem na zasobie GET sale/offers/{offer.id}, gdzie wartość to ENDED. Użycie filtru zwraca błędną informację. Przekazałem ten problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@hahyes Wyeliminowaliśmy ten problem, oferta ma już uspójnione statusy.
