### ISSUE TITLE
Wymuszenie odpięcia produktu (złe dane w allegro)

### ISSUE THREAD

**Issue by prafinski** [allegro/allegro-api#2536]
Dotyczy niektórych produktów - dokładnie opon o EAN np.: 8411965834 - generalnie dużo opon marki WinRun. W Allegro produkty widnieją pod tym EAN jako Lanvigator Comfort I 215/60R16 95 H, my sprzedajemy WinRun R380 215/60 R16 95 H.

To produkt chiński i mogło się tak zdarzyć, że "występuje" z innymi nazwami. Nie powinna taka sytuacja mieć miejsca - ale jak widać zaistniała. 

**Problem:**
Allegro po EAN podpina produkt o innym producencie i wszystkie próby aktualizacji są odrzucane - błąd przez API - np. zmiana ilości na aukcji. Pomaga tylko wyzerowanie produktu w REST i ponowny zapis. Po jakimś czasie znowu system allegro podpina po EAN produkt i tak w kółko...

Jak rozwiązać ten problem? Czy można jakoś oznaczyć produkt, żeby nie był do niego podpinany produkt z Allegro? Czy nie powinny być podpinane tylko produkty w których producent jest zgodny?

Możemy oczywiście usunąć EAN z danego produktu, ale chyba nie o to chodzi... W taki sposób jednak działa GUI Allegro gdy wybierze się opcję "sprzedaję inny produkt" i odepnie się propozycję produktową Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to - dla produktu Lanvigator Comfort I 215/60R16 95 H zwracamy EAN 6924064100114. Czy numer, który podałeś, jest prawidłowy? Nie mamy dla niego żadnego powiązanego produktu.

Czy możesz wskazać przykładowe numery ofert, dla których nastąpiło nieprawidłowe powiązanie?

**Comment by prafinski** [comment]
![allegro-zly-ean](https://user-images.githubusercontent.com/25444623/69233841-f4963380-0b8d-11ea-86e3-ba18fd06b1ba.jpg)

Dokładnie ten numer aukcji 8411965834, załączam screen z edycji produktu z widocznym dokładnie tym EAN 6924064100114.

Patrze teraz, że dość ciekawa sytuacja, bo my nie mamy EAN wpisanego na tym produkcie u nas w bazie danych w ogóle, tylko numer SAP ... czy jest możliwe, że system Allegro powiązał część ofert nie mając EAN ? nie kojarzę, żeby ktoś ręcznie parował te produkty, a to dotyczy konkretnej marki opon - co jest podejrzane.

Jak biorę ponowne wystawienie tych produktów z naszego systemu to nie wysyłam EAN do Allegro - wiec musiał on zostać uzupełniony może tez przy automatycznym parowaniu produktów - czy jest to możliwe?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za szczegółowe dane. Przekazałem je do odpowiedniego zespołu w celu analizy.

**Comment by PrzemyslawLukanowski** [comment]
Przypięcie spowodowane było problemem w naszych mechanizmach - konfiguracją parametrów identyfikujących w kategorii, teraz problem nie powinien już występować.

Niedawno wprowadziliśmy poprawkę, która sprawia że nie będziemy wiązać automatycznie ofert z niejednoznacznymi parametrami identyfikującymi typu inna/inne, więc ponowne podpięcia nie powinny zachodzić.

Nie ma możliwości oznaczenia oferty, żeby produkt się nie podpinał, jest to zgodne z założeniami platformy.

Przy podpięciu produktu do oferty, jeśli w ofercie nie było EANu, a w produkcie był, to w ofercie zostanie on ustawiony. Sam EAN nie powoduje automatycznego podpięcia - sprawdzana jest zgodność parametrów identyfikujących.

**Comment by prafinski** [comment]
ok super, dziękuję, uczuliłem nasz mechanizm żeby w razie czego odpiął produkty błędne jeśli w przyszłości system allegro popełni błąd - żeby na pewno dane przez nas wysłane się zapisały (stan magazynowy).
