### ISSUE TITLE
Problemy z symulatorem płatności na sandboxie

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2537]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle:
Dostaję następujące błędy podczas symulacji płatności w środowisku testowym
![Screenshot at 2019-11-20 13-45-35](https://user-images.githubusercontent.com/4314822/69240544-003d2680-0b9d-11ea-824f-7c890f676960.png)
![Screenshot at 2019-11-20 13-45-46](https://user-images.githubusercontent.com/4314822/69240553-03d0ad80-0b9d-11ea-9aee-25456937fef8.png)

Dodatkowo
504 Gateway Time-out
The server didn't respond in time.

**Comment by Onixarts** [comment]
Potwierdzam i stoję z robotą ;)

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem, aktualnie symulator płatności działa dla symulatora p24.

**Comment by pawelosajda** [comment]
Jak włączyć p24? Na koncie przedawcy należy aktywować przelewy24?

**Comment by pawelosajda** [comment]
Wydaje się, że już działa.

**Comment by PrzemyslawLukanowski** [comment]
Usunęliśmy awarię, symulator płatności działa już prawidłowo.
