### ISSUE TITLE
Full integration daily verification problem

### ISSUE THREAD

**Issue by Nemanja-Lima** [allegro/allegro-api#2538]
Hi guys
I want to fully integrate with your api, but i have a problem with verification.
Do i have to do device verification on daily base over verification url or there is a way to just refresh token?
For now i go and get new device id and verification url everyday and then i take new token with device id, but i need to automatize that verification process. So do u how can i do that or how can I make the whole verification in a different way?

**Comment by crazyhtm** [comment]
You can just refresh access_token when it expired (after 12 hours) using:

**curl -X POST "https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=<refresh_token>" -H 'Authorization: Basic base64(client_id:client_secret)'**

In response, you will get new "access_token" (for next 12 hours) and new "refresh_token" for the further update.

**Comment by Nemanja-Lima** [comment]
Thanks mate :) u are a life savior :)
