### ISSUE TITLE
Pytanie odnośnie opisu, załączników oraz regulaminu

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2539]
Mam pytanie być może sprawa nie tyczy się bezpośrednio API i może ktoś pokieruje dokładnie do jakiej osoby zadać pytanie w allegro.

A mianowicie:
W planach mamy autmatyczne wystawianie aukcji produktów - meble tapicerowane które mają duże możliwości konfiguracji
np.
- wyboru tkaniny na siedzisko
- wyboru tkaniny na oparcie
- wyboru tkaniny na poduszki
- wyboru koloru nóżek

Duża część tych produktów ma znacznie więcej opcji do wyboru.

Dane  o konfiguracji mamy w naszym konfiguratowrze (on-line)  możemy wygenerować z niego zdjęcia i dodawać do opisu aukcji jednak ilość zdjęć w aukcji jest ograniczona i nie wystarczająca dla nas. 

Moglibyśmy wygenerować pdfa i podpiąć do aukcji, a w aukcji zamieścić tylko informacje że wszystkie możliwe opcje wykończenia mebla znajdują się w załączniku i aby klient sprawdził i wybrał co go interesuje.

Jednak to powoduje znaczne problemy i zużycie mocy do generowania  pdf oraz ich aktualizacji jak i aktualizacji na aukcji. - bardzo skomplikowana opcja do wdrożenia.

Łatwiej było by nam podpiąć konfigurator do aukcji aby klient mógł  otworzyć link w nowym oknie a link kierował by tylko do konfiguratora  specjalnie przygotowanego do aukcji ale to chyba by nie przeszło regulamin nie zezwala na takie coś ..

Czy może jest jakaś inna opcja aby to rozwiązać ?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma technicznej mozliwości, by podpiąć konfigurator do oferty. Na razie nie planujemy, by taka opcja pojawiła się na Allegro. Warto przyjrzeć się wielowariantowości i opcji tworzenia serii produktowych i na tej podstawie złożyć i pomóc kupującemu to skonfigurować, niestety nie mamy prostego rozwiązania dla tego typu asortymentu.

**Comment by frankii91** [comment]
a nie jest rozważana opcja aby móc podpiąć zewnętrzne kod html ? wcześniej weryfikowany przez kogoś z allegro ?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy wprowadzić takiej funkcjonalności.
