### ISSUE TITLE
Co będzie gdy numeracja aukcji dojdzie do 9999999999 ?

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2541]
Jakie macie plany w tym zakresie , numery kolejnych aukcji będą już 11 cyfrowe ?
Pytam , bo w tym tempie przybywania nowych aukcji ten problem pojawi się już za kilka miesięcy , wolę 
zawczasu przygotować strukturę baz na taką ewentualność

**Comment by PatrykBocian** [comment]
Jesteśmy przygotowani na taką sytuację, w tym przypadku zwiększymy numerację aukcji i będą to to numery 11 cyfrowe.

**Comment by 11mszot** [comment]
W to że Wy jesteście na taką sytuację przygotowani ani chwili nie wątpiłem. Zadałem to pytanie po to by autorzy aplikacji mogli się odpowiednio wcześniej przygotować , bo lubicie nas czasem zaskakiwać

**Comment by rafalkrupinski** [comment]
@11mszot chcesz powiedzieć, że przechowujesz identyfikatory w sql w string(10)? :D

**Comment by 11mszot** [comment]
Jak przechowuję identyfikatory aukcji to już moja słodka tajemnica :)
Natomiast w niektórych miejscach parsuję 10 cyfrowe stringi jak
identyfikatory aukcji i to muszę poprawić


pt., 22 lis 2019 o 20:09 Raphael Krupinski <notifications@github.com>
napisał(a):

**Comment by GosiaJK** [comment]
I stało się. Czekam już ponad godzinę na wystawienie aukcji...

**Comment by PrzemyslawLukanowski** [comment]
@GosiaJK Wczoraj w godzinach popołudniowo-wieczornych wystąpiły po naszej stronie problemy z edycją i wystawianiem ofert. Przepraszam za utrudnienia.
