### ISSUE TITLE
VALIDATION_ERROR podczas próby dodania oferty do kampanii

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2543]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas próby zgłoszenia oferty do kampanii Black Week metodą POST na zasobie /sale/offers wyrzuca tylko i wyłącznie błąd VALIDATION_ERROR: Name your offer. W czym leży problem? Na tym samym zasobie nie ma możliwości do zgłoszenia oferty do żadnej innej kampanii.

**Comment by PatrykBocian** [comment]
Zasób o którym wspominasz służy do utworzenia [draftu oferty](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST).
Aby pozbyć się tego błędu musisz uzupełnić w body pole “name”, nie może ono być puste.
Dla przykładu:  

**{
	"name": "nazwa oferty",
    "category": null,
    "product": null,
    "parameters": [],**

Kiedy uzupełnisz te pole, utworzysz draft prawidłowo.
Aby utworzyć kampanię musisz skorzystać z zasobu [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/postBadges), więcej na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/badge/#2).
