### ISSUE TITLE
PUT /sale/offer-modification-commands/{commandId} Limit 

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2544]
Jaki jest limit ofert jednocześnie zmienianych metodą PUT na tym zasobie ?

Rzecz w tym , że jakiś czas temu skonfigurowałem skrypty przypisujące cenniki dostaw do 1000 ofert równocześnie , niestety od jakiegoś czasu te skrypty przestały działać prawidłowo

Dokładnie chodzi o przypisanie cenników do szkiców , robiłem test na 3 ofertach i przypisuje prawidłowo , test na 1000 ofertach mimo że GET zwraca informację ze operacja przebiegła poprawnie , cenników nie przypisuje

**Comment by PatrykBocian** [comment]
Limit dla tego zasobu to 1000 ofert do edycji, aby zweryfikować ten problem, prosiłbym Cię o kontakt przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Podaj tam trace.id, pełny request i response w formacie cURL, oraz dopisz w zgłoszeniu #2544.

**Comment by 11mszot** [comment]
Problem wydajesię być jeszcze bardziej skomplikowany i występuje na linii DRAFT=>CENNIK
dn jednych (starszych draftów) cennik daje się przypisać bez problemu zarówno metodą PUT na zasobie /sale/offer-modification-commands/ , jak i metodą PUT na zasobie /sale/offers/

identyfikator cennika : 6991b672-dce6-41d2-8427-aede35aabe96

DRAFTY do których dał się przypisać
8505153795
8516743448
8527188904
8527191047
8527200077
8527200319
8527215350

Drafty do których nie dał się przypisać

8592927859
8593104541
8593109140
8593112574
8593115030
8593117442
8593119900
8593122990
8593134986
8593144033
8593144499

**Comment by PatrykBocian** [comment]
Upewnij się proszę, czy jesteś zautoryzowany jako sprzedawca, do którego należą oferty. Zweryfikowałem to - w odpowiedzi na **GET offer-modification-commands/{uuid}/tasks** widzę komunikat, który wskazuje na to, że nie jesteś ich właścicielem  (**“Offer doesn't belong to seller”**).

**Comment by 11mszot** [comment]
Oferty są na pewno ofertami moimi
Dziś przy sprawdzaniu poprawności przypisania cenników dostaję taki response:
jak to interpretować ?
Task : ecb6e60c-9c46-4e4d-93fe-06929dbf0012

            [0] => Array
                (
                    [offer] => Array
                        (
                            [id] => 8708496240
                        )

                    [message] => Offer '8708496240' has no delivery option defined
                    [status] => FAIL
                    [scheduledAt] => 2019-11-22T11:44:20.908Z
                    [finishedAt] => 2019-11-22T11:44:22.409Z
                    [field] => shippingRates
                    [errors] => Array
                        (
                            [0] => Array
                                (
                                    [code] => OFFER_HAS_NO_DELIVERY_OPTION
                                    [message] => Offer has no delivery option defined.
                                    [details] =>.
                                    [path] =>.
                                    [userMessage] => Offer has no delivery option defined.
                                )

                        )

                )

**Comment by 11mszot** [comment]
Dokładnie to samo dzieje się przy użyciu metody PUT na zasobie /sale/offers/{ITEM_ID}
logi : request+response w pliku http://alledemo.co.pl/zup2.txt

**Comment by PatrykBocian** [comment]
Aby rozwiązać ten problem, musisz uzupełnić pole “location” - bez niego nie dodasz cennika dostawy do oferty.
W najbliższym czasie dodamy taką informacje do poradnika.

**Comment by 11mszot** [comment]
Ok dziękuję za podpowiedź. Sprawdzę.
Wskazane by było rozbudować obsługę błędów , by z komunikatu błędu bardziej precyzyjnie wynikało o co chodzi. Oszczędziło by to czasu i nerwów , zarówno nam autorom aplikacji , jak i wam developerom api

**Comment by PatrykBocian** [comment]
Pracujemy nad tym aby komunikowane błędy były jak najbardziej precyzyjne.
Zgłosiłem twoją uwagę w tej sprawie.
