### ISSUE TITLE
Błąd dodawania listu przewozowego

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2545]
Występuje problem:
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym

Próbuję dodać list przewozowy metodą doAddPackageInfoToPostBuyForm i mam błąd, nie wiem z czego on wynika. Problem mam tylko z firmą DTS, inne działają bez problemu.
Format listu przewozowego: 9999999999/999
Odpowiedź dostaję w 'packageIdsNotAddedIncorrectPackageId'

**Comment by PrzemyslawLukanowski** [comment]
Błąd generuje "/" w numerze przesyłki. Weryfikujemy ten przypadek.

**Comment by PrzemyslawLukanowski** [comment]
13 stycznia usuniemy ten endpoint, nie zamierzamy już go rozwijać. Skorzystaj z zasobu REST API -  [POST order/checkout-forms/{checkoutFormId}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST), gdzie bez problemu dodasz taki format numeru przesyłki.

**Comment by avello** [comment]
Dodałem problematyczne numery z panelu, bo tylko 3 miałem takie.
WebAPI używam tylko do starszych zamówień pobranych jeszcze przez WebAPI więc po jakimś czasie problem sam się rozwiąże.
Dziwne jest to że w innych listach używam znaku "/" i działa np. taki format listu: NET 99999/9/9999 spedytor Dachser.

**Comment by PrzemyslawLukanowski** [comment]
Możesz podać przykładowe trace-id, gdzie udało Ci się dodać numer w takim formacie? Próbuję odtworzyć ten błąd, ale za każdym razem numer trafia do packageIdsNotAddedIncorrectOperatorId.

**Comment by avello** [comment]
No właśnie nie udało mi się dodać, dlatego zalogowałem się do panelu allegro i ręcznie dodałem te listy do zamówień.
Trace-id niestety nie mam.
Natomiast bez problemu dodaję listy przewozowe dla spedytora Dachser.
Wzór takiego numeru to: "NET 99999/9/9999" więc znak "/" też występuje.
Różnica tylko taka że tu operatorId=0 więc może to ma znaczenie.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Możesz dodać "/" po wybraniu operatorId=0 oraz wpisaniu nazwy przewoźnika, jednak ze względu na styczniowy termin wygaszenia metody nie planujemy dodać tej funkcjonalności dla pozostałych przewoźników.
