### ISSUE TITLE
Aktualizacja konkretnej oferty

### ISSUE THREAD

**Issue by KatoPl** [allegro/allegro-api#2546]
Witam,
Pobrałem informacje o ofertach z konkretnej kategorii, która jest już liściem tj. leaf = true.
Czy mając ID takiej oferty np. "id": "8637975929", mogę ją pobrać raz jeszcze?
To nie jest moja oferta, tylko oferta innego sprzedającego.
Chcę sprawdzić, dostępną ilość sztuk, czy nadal jest aktywna , itp?

Pytanie nr.2
Czy mając taką ofertę, mogę dowiedzieć o dokładanych kosztach transportu, to co jest dostępne to tylko informacja o minimalnym koszcie, a nie koszcie dostawy kurierem.
Chyba, że coś przeoczyłem w dokumentacji

Pytanie nr.3
Czy mając id oferty innego sprzedającego, mogę uzyskać informację o produkcie np. jego kod EAN?

Dziękuję i przepraszam za kłopot, jeżeli odpowiedź jest w dokumentacji, ale naprawdę szukałem i bez powodzenia.

Dziękuję,
Adam

**Comment by PatrykBocian** [comment]
[GET/offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) to odzwierciedlenie wyszukiwarki na froncie, nie możesz pobrać tym zasobem kompletu danych o nie swojej ofercie.
Można to zrobić za pomocą zasobu [GET/sale/offers/{offerid}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) lecz musisz być zweryfikowany jako sprzedawca, do którego należą oferty. 
Zasobem [/offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) pobierzesz liczbę sztuk, ale nie pobierzesz informacji o koszcie dostawy czy numerze EAN.
Więcej informacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/listing/) oraz [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListing).
