### ISSUE TITLE
Wielowariantowość - atrybuty niedostępne w REST API do tworzenia wariantu

### ISSUE THREAD

**Issue by rtarnowski** [allegro/allegro-api#2547]
Witam
 szukam odpowiedzi lecz nigdzie jej nie mogę odnaleźć. W niektórych kategoriach odpytując REST API  o parametry np. https://api.allegro.pl/sale/categories/257897/parameters występują atrybuty, które pozwalają tylko poprzez panel Allegro na utworzenie wariantu. W API natomiast atrybut zwraca false na przykład dla wyżej wymienionej kategorii . 
` {
            "id": "427",
            "name": "Zamek",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false
            }`
W API nie pozwala na utworzenie wariantu, a przez panel Allegro już tak. Dlaczego występuje taka rozbieżność ? Dodam tylko, że takich rozbieżności jest więcej w wielu kategoriach

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to  - przez panel Allegro mogę utworzyć zestaw tylko na podstawie takich samych parametrów, jak w API - czyli w przypadku kategorii 257897 jest to jedynie parametr 5251 (długość). Zrzut poniżej: 
![Screenshot_16](https://user-images.githubusercontent.com/51473661/69422653-76b86080-0d24-11ea-81cd-2b42edb2723a.png)
Czy możesz podać inne parametry w kategoriach, dla których zauważyłeś rozbieżność?
