### ISSUE TITLE
Brak transakcji w doGetTransactionsIds - nie zwraca jednej transakcji

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2549]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Klient kupił w 1 transakcji w dwóch aukcjach: 8455790857, 8203677030
Nr tej transakcji to: 1515055541
Pobierając informacje nie ma tej transakcji

Przykładowy SOAP dla: 8455790857, zwraca mi jedną transakcję, nie zwraca mi tej powyższej
Prośba o weryfikację

INFO 2019-11-22 10:56:29.4253954
Request: 
<?xml version="1.0" encoding="utf-8"?><soap:Envelope
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><DoGetTransactionsID
sRequest
xmlns="https://webapi.allegro.pl/service.php"><sessionHandle></sessionHandle><itemsIdArray><item>8455790857</item></itemsIdArray><userRole>seller</userRole></DoGetTransactionsI
DsRequest></soap:Body></soap:Envelope>

INFO 2019-11-22 10:56:29.5880349
Response: 
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doGetT
ransactionsIDsResponse><ns1:transactionsIdsArray><ns1:item>1112564580</ns1:i
tem></ns1:transactionsIdsArray></ns1:doGetTransactionsIDsResponse></SOAP-ENV
:Body></SOAP-ENV:Envelope>

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - prawidłowy numer transakcji dla tych ofert to 1112564580. Nie posiadamy w systemie informacji na temat transakcji 1515055541.
