### ISSUE TITLE
Brak klucza Soap WebAPI na apps.developer.allegro.pl.allegrosandbox.pl

### ISSUE THREAD

**Issue by krzysztofgwiazda** [allegro/allegro-api#255]
W środowisku produkcyjnym mam podany Klucz Soap WebAPI:

![allegro_pro](https://user-images.githubusercontent.com/1054403/40550411-4bd09d62-603a-11e8-94b7-0ab3f72c95f2.png)

natomiast na sandbox tylko i wyłącznie klucze aplikacyjne RestAPI:

![allegro_dev](https://user-images.githubusercontent.com/1054403/40550440-5ecd5978-603a-11e8-86df-fc0291f6e048.png)

Czy mogę prosić o wyjaśnienie skąd wziąć klucz Soap WebAPI dla sandboxa?

**Comment by AniaMalinowska** [comment]
Rozszerzyliśmy funkcję Client ID (identyfikator, który jest generowany podczas rejestracji aplikacji). Teraz, jeśli korzystasz z WebAPI, możesz go użyć zamiast webapiKey. 
Dotychczas wygenerowane klucze działają bez zmian. 

Informowaliśmy o tym [tutaj](https://github.com/allegro/allegro-api/issues/249) oraz na [portalu developerskim](https://developer.allegro.pl/news/2018-05-24-Zmiana_w_obsludze_kluczy/).
