### ISSUE TITLE
Zapis i odczyt aukcji z tablicy (PHP)

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#2550]
Witam, zapisuje aukcje do tablicy w poniższej formie do pliku tekstowego (docelowo będzie do bazy danych), chciałbym później operować na ściągniętych danych, jak mogę ponownie wyświetlić tablice z pliku tekstowego i operować na tych danych?

```
Array
(
    [nr] => 1
    [tab_id_aukcji] => numer
    [tab_tytul_aukcji] => tytul
    [tab_sprzedane] => 78
    [tab_cena] => 29.50
    [tab_promowana] => Tak
)
Array
(
    [nr] => 2
    [tab_id_aukcji] => numer
    [tab_tytul_aukcji] => tytul
    [tab_sprzedane] => 67
    [tab_cena] => 29.95
    [tab_promowana] => Tak
)
Array
(
    [nr] => 3
    [tab_id_aukcji] => numer
    [tab_tytul_aukcji] => tytul
    [tab_sprzedane] => 67
    [tab_cena] => 29.95
    [tab_promowana] => Tak
)
```

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może ktoś z użytkowników forum  będzie mógł wesprzeć Cię w tym temacie.

**Comment by juhacz** [comment]
To jest pytanie o PHP nie o api. Zainteresuj się serialize() i unserialize().
