### ISSUE TITLE
Dodawanie listu przewozowego - zwracany identyfikator przesyłki

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2551]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Dodając listy przewozowe do zamówień zauważyłem że w odpowiedzi zwracanej z allegro otrzymałem  w kilku przypadkach identyczne ID (UE9DWlRBX1BPTFNLQTowMDI1OTAwNzczODkzMDExOTYzMw==)
Numer listu przewozowego był taki sam we wszystkich przypadkach, natomiast były to osobne zamówienia - inne  ID zamówienia, oraz inne lineItemId.
Czy to poprawne działanie tego mechanizmu?

**Comment by PrzemyslawLukanowski** [comment]
Tak, to prawidłowe zachowanie - id jest powiązane z przekazanym numerem przesyłki. Jeżeli więc numer przesyłki będzie się powtarzać, tak samo będzie z wartością id w response.

**Comment by avello** [comment]
Ok. Dziękuję za odpowiedź. Można zamykać temat.
