### ISSUE TITLE
Aukcje zakończone a zwraca aktywne

### ISSUE THREAD

**Issue by michalsukiennik** [allegro/allegro-api#2552]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Żądanie:
GET /offers/listing?offset=0&searchMode=CLOSED&limit=100&phrase=alec%20casey HTTP/1.1
Odpowiedź:
https://paste.ofcode.org/6mqSvsqaHFuCUGj52TZx6

Niektóre rekordy są aktywne, choć parametr żądanie wskazuje na zakończone. Nie mają ustawionego pola Publication

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Zweryfikowałem ten przypadek - problem dotyczy oferty 7973751720. Zgłosiłem to do odpowiedniego zespołu.

**Comment by damianholak** [comment]
Dołączam się do zgłoszenia. Problem obserwuję od dłuższego czasu (co najmniej tydzień). Po ok 40 sekundach od wysłania paczki ofert do aktywacji automatycznie sprawdzam ich status. Status części z nich to ACTIVE, pozostałe są aktywowane ponownie. Problem w tym, że oferty ze statusem ACTIVE samoistnie, po jakimś czasie (sprawdzam ręcznie po kilku minutach) zmieniają status na ENDED i są widoczne jako zakończone. Problem nie występuje przy pojedynczych aktywacjach ale nie może być też związany z wyczerpaniem limitu zapytań ponieważ status aktywacji widnieje jako SUCCESS, jak również dlatego że bezpośrednio po próbie aktywacji oferty mają, jak wspomniałem, chwilowy status ACTIVE. Problem nie występuje ani podczas deaktywacji, ani też podczas zmiany cen.

**Comment by PrzemyslawLukanowski** [comment]
Zgłoszenie dotyczyło rozbieżności między tym, co zwraca GET /offers/listing, a faktycznym statusem oferty - mimo ustawionego parametru searchMode=CLOSED w wynikach znajdowała się aktywna oferta. Jak rozumiem, Twój problem dotyczy kończenia ofert już parę minut po ich aktywacji. Czy możesz podać przykładowe numery?

**Comment by damianholak** [comment]
> 
> 
> Zgłoszenie dotyczyło rozbieżności między tym, co zwraca GET /offers/listing, a faktycznym statusem oferty - mimo ustawionego parametru searchMode=CLOSED w wynikach znajdowała się aktywna oferta. Jak rozumiem, Twój problem dotyczy kończenia ofert już parę minut po ich aktywacji. Czy możesz podać przykładowe numery?

Zaliczyliśmy wczoraj problem z odświeżaniem tokena. Po aktualizacji access tokena problem jakimś cudem zniknął. Pobieranie statusów (które również dawało złe wyniki, np ENDED dla trwających ofert) jak i aktywacja ofert przebiegły w 100% pomyślnie. Także mój problem można uznać za nieaktualny, dziękuję za zainteresowanie. Będę obserwował sytuację i założę osobny temat jeśli problem się powtórzy.

**Comment by PrzemyslawLukanowski** [comment]
Ok, dziękuję za odpowiedź.
