### ISSUE TITLE
Przedłużanie ważności tokena-Nie można odświeżyć tokenu dostępu za pomocą tokenu odświeżaniania

### ISSUE THREAD

**Issue by 1196127223** [allegro/allegro-api#2553]
- [√] z zasobem REST API
 - [√] ze środowiskiem produkcyjnym
 - [√] z logowaniem lub autoryzacją

Kiedy access_tokena wkrótce wygaśnie, użyj refresh_tokena, aby odświeżyć. Pierwszy dostęp zawiera błąd, ale nie jest wyświetlany żaden komunikat o błędzie ani inne informacje.
refresh_tokena odświeżania jest ponownie używany do odświeżania i zwracany jest komunikat o błędzie:{"error":"invalid_grant","error_description":"Invalid refresh token: eyJhb....."}
Co może powodować problem?

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd świadczy o tym, że najprawdopodobniej użyłeś już wcześniej refresh_tokena, którego przekazujesz. Prześlij proszę pełen request w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) dopiskiem Github #2553

**Comment by 1196127223** [comment]
Rozumiem, że refresh_tokena jest jednorazowego użytku.
Czy refresh_tokena straci ważność, gdy zgłosi błąd?
Czy to oznacza, że uzyskuję dostęp do interfejsu API i unieważnia refresh_tokena?
Ale dlaczego nie ma informacji zwrotnych?
W takim przypadku mogę zalogować się tylko w celu ponownej autoryzacji. Powtórzenie autoryzacji logowania sprawia, że czuję się uciążliwy. Czy jest jakieś dobre rozwiązanie?

**Comment by 1196127223** [comment]
> 此错误表明您可能已经使用过之前要传输的refresh_token。请通过我们的[联系表，](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619)以cURL格式发送完整的请求[，](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619)请注意Github [＃2553](https://github.com/allegro/allegro-api/issues/2553)

Rozumiem, że refresh_tokena jest jednorazowego użytku.
Czy refresh_tokena straci ważność, gdy zgłosi błąd?
Czy to oznacza, że uzyskuję dostęp do interfejsu API i unieważnia refresh_tokena?
Ale dlaczego nie ma informacji zwrotnych?
W takim przypadku mogę zalogować się tylko w celu ponownej autoryzacji. Powtórzenie autoryzacji logowania sprawia, że czuję się uciążliwy. Czy jest jakieś dobre rozwiązanie?

**Comment by PrzemyslawLukanowski** [comment]
Tak, refresh_token jest jednorazowego użycia. Po odświeżeniu tokena otrzymasz nową parę refresh_token i access_token - wtedy stare tokeny stracą ważność. Nie musisz przechodzić ponownie całego procesu autoryzacji, wystarczy, że będziesz używał refresh_tokena. Zajrzyj do [naszego poradnika](https://developer.allegro.pl/en/auth/#refresh-token), tam znajdziesz więcej informacji na ten temat.

**Comment by 1196127223** [comment]
> 是的，refresh_token只能使用一次。刷新令牌后，您将收到一对新的refresh_token和access_token-旧令牌将过期。您不必再次执行整个授权过程，只需使用refresh_token。请查看[我们的指南，](https://developer.allegro.pl/en/auth/#refresh-token)以获取有关此主题的更多信息。

Mój problem polegał na tym, że token_odświeżania został użyty bez żadnych zwróconych danych i wygasł też token_odświeżania.
W takim przypadku mogę zalogować się tylko w celu ponownej autoryzacji. Powtórzenie autoryzacji logowania sprawia, że czuję się uciążliwy. Czy jest jakieś dobre rozwiązanie?

**Comment by PrzemyslawLukanowski** [comment]
Po użyciu refresh_tokena otrzymałeś nową parę refresh + access. Jeżeli teraz nadal chciałbyś użyć starego refresh_tokena, w odpowiedzi otrzymasz status 400, bo w tym momencie jest już nieważny. Jeśli nie masz dostępu do nowej pary refresh + access, musisz ponownie przejść proces autoryzacji. Aby uniknąć tego typu sytuacji, po otrzymaniu nowej pary korzystaj z nowego access tokena i pamiętaj, aby go odświeżać przed wygaśnięciem nowym refresh_tokenem. 
Prześlij proszę swój refresh_token, o którym wspominasz, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) dopiskiem Github #2553, przeanalizujemy, co się wydarzyło w tym przypadku.

**Comment by j4r3kb** [comment]
Przy okazji mam pytanie. W dokumentacji jest informacja że `refresh_token` jest ważny 3 miesiące.
Co się stanie jeżeli aplikacja typu device_flow nie będzie robić żadnych requestów ponad 3 miesiące i następnie w wyniku otrzymania błędu o wygaśniętym `access_token` wykonam request z przeterminowanym już `refresh_token`?
Czy w takiej sytuacji również dla device_flow trzeba od nowa przejść proces rejestracji apilkacji?

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli użyjesz przeterminowanego refresh tokena, w odpowiedzi otrzymasz status 401. Nie musisz w takim przypadku rejestrować nowej aplikacji, wystarczy, że ponownie przejdziesz proces autoryzacji, po którym otrzymasz nową parę access i refresh token.
