### ISSUE TITLE
Jak daleko wstecz dostajemy dane z zasobu /sale/offer-events ?

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2554]
Jak daleko wstecz dostajemy dane z zasobu **/sale/offer-events** ?

**24 godziny czy więcej?**

**Comment by PatrykBocian** [comment]
Dokładnie tak, [GET/sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) zwraca wydarzenia z ostatnich 24h.
Więcej na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/my_offers/).

**Comment by crazyhtm** [comment]
Dzięki za informację.

Jeszcze jedno:

Zauważyłem że zdażenie OFFER_ENDED dla danej aukcji zwracane przez  /sale/offer-events jest opóźnione o około 5 min w stosunku do czasu jego wystąpienia. 
Tzn. /sale/offer-events zwraca je dopiero 5 min po tym jak faktycznie nastąpi.
Dlaczego?

**Comment by PatrykBocian** [comment]
Zweryfikowałem to, taki problem nie występuje po mojej stronie.
Możesz podesłać przykładowe oferty, w których zauważyłeś ten przypadek?

**Comment by crazyhtm** [comment]
Jasne:

mój czas jest godzinę późniejszy od czasu API Allegro

np. zdarzenie z /order/events (w tym zdarzeniu zakupiono 5 produktów z 5 aukcji, wszystkie zakończone) Jako przykład podam 2 aukcje z tego zdarzenia:

1574687145 ( mój timestamp Mon Nov 25 14:05:45 CET 2019 ) id: 1574687140546508 , type: BOUGHT , occuredAt: 2019-11-25T13:05:27.866Z - checkoutForm: 183fb736-0f84-11ea-b127-0b73a7fb38cc
1574687145 - 0) offerId: **8069444903**
1574687145 - 1) offerId: **8069535078**

tutaj opóźnienie robi mój program do Waszego czasu ok 15 sekund (wynika z przebiegu funkcji). Ale obie aukcje zarejestrowane w tym samym zdarzeniu.

teraz zdarzenia OFFER_ENDED dotyczące tych samych aukcji z /sale/offer-events

1574687443 - (mój timestamp Mon Nov 25 14:10:43 CET 2019) id: MTU3NDY4NzQzOTA0NjA3MQ - offerId: **8069535078** , occuredAt: 2019-11-25T13:05:26Z
1574687459 (mój timestamp Mon Nov 25 14:10:59 CET 2019) id: MTU3NDY4NzQ0ODY0NjU2Nw - offerId: **8069444903** , occuredAt: 2019-11-25T13:05:26Z

tutaj różnica ok 5 min między Waszym timestampem a moim.
A zdarzenie **8069444903** było dostępne dopiero w następnym przebiegu funkcji dlatego mój timestamp jest opóźniony o 16 sek w stosunku do **8069535078**.

Oba zasoby odpytywane w ty samym przebiegu pętli programu, czyli nawet jeżeli opóźnienie robiłby mój program to byłoby ono maksymalnie 15 - 20 sek. 
Z Waszych timestampów wynika że zdarzenia OFFER_ENDED wystąpiły nawet sekundę przed zdarzeniem BOUGHT, ale w momencie w którym mój program odpytywał oba zasoby były jeszcze niedostępne i pojawiły się dopiero po ok 5 minutach. (zasób /sale/offer-events był w tym czasie pytany kilkanście razy)

Jeżeli coś zagmatwałem to przepraszamm, chętnie wyjaśnię.

**Comment by PatrykBocian** [comment]
Zweryfikowałem sprawę i w ostatnim czasie nie wystąpiły żadne opóźnienia w takim stopniu, o jakim wspominasz. Skąd wynika różnica w twoim timestampie? Być może to generuje problem.
