### ISSUE TITLE
Edycja stanu magazynowego przy wielu ofertach z różnymi wartościami.

### ISSUE THREAD

**Issue by aventez** [allegro/allegro-api#2555]
Posiadam tablicę z ~500 ofertami w formie `'offer_id' => 'quantity'`. Czy przez API Allegro mogę przesłać jednorazowe żądanie o zmianę wszystkich ofert (stan magazynowy jest różny dla każdej zmienianej aukcji)?

**Comment by kfijalko** [comment]
nie

**Comment by PatrykBocian** [comment]
@aventez  Nie ma takiej możliwości, możesz zmienić grupowo ilość jednostek w ofertach za pomocą [PUT/sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT). 
Lecz zmienia to stan magazynowy na taki sam we wszystkich ofertach, na których operujesz. Więcej na ten temat znajdziesz w tym [poradniku](https://developer.allegro.pl/my_offers/#3). Dodam, iż sugestię takiej zmiany mamy już na liście dot. rozwoju REST API.

**Comment by rtnet-pl** [comment]
My grupujemy sobie w paczki oferty z takimi samymi ilościami, to w sumie jedyne co możesz zrobić aby to przyspieszyć.
