### ISSUE TITLE
How to activate Sandbox account?

### ISSUE THREAD

**Issue by ajorzel** [allegro/allegro-api#2556]
Dzień dobry,

Chciałem wystawić kilka testowych aukcji na sandboxowym allegro, ale potrzebna jest weryfikacja konta (1). Czy jest możliwość wykonania samemu aktywacji? Czy trzeba działań ze strony allegro?

(1) https://tinyurl.com/vh3krtn

* email: adrian@sklepdomowy.pl
* client: testow

**Comment by PatrykBocian** [comment]
W tym przypadku potrzebna jest aktywacja z naszej strony. Aktywowałem już dla ciebie konto.

**Comment by ajorzel** [comment]
@PatrykBocian dziękuje.

**Comment by AssAssIn1909** [comment]
Również prosze o aktywacje
email:    milosz.lazarowicz@itpiast.com
login:     MLA

**Comment by PatrykBocian** [comment]
@AssAssIn1909  Prośba o podanie poprawnego loginu w celu aktywacji konta.

**Comment by AssAssIn1909** [comment]
Jestem przekonany że taki jest login
Konto firmowe
![obraz](https://user-images.githubusercontent.com/8657646/70632531-48e18000-1c2f-11ea-9198-d84e3244d7cd.png)

**Comment by PatrykBocian** [comment]
@AssAssIn1909 Aktywowałem twoje konto. Widzę też, że jest kontem firmowym. W celu jego weryfikacji jako konto firmowe niezbędne jest przesłanie dwóch dowolnych plików w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).
