### ISSUE TITLE
Problem z symulatorem płatności

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2557]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle:
https://merch-prod.snd.payu.com/hub/mbank/callback/ok?ServiceId=10000002&OrderId=75792620&SessionId=6028f847544940da1c8d79a14e47f0ab21eb4724177c3799413542d13389adbd&Amount=43.00&Description=XX75792620XX+Allegro+727989470&TrDate=20191125

![Screenshot at 2019-11-25 07-55-54](https://user-images.githubusercontent.com/4314822/69518998-3c83d480-0f59-11ea-8b7e-0ae5a15eb053.png)

**Comment by PatrykBocian** [comment]
Dziękujemy za zgłoszenie, przekazałem tę sprawę do odpowiedniego zespołu.

**Comment by PatrykBocian** [comment]
Chwilowo nie działa tylko symulator dla mbank, możesz na chwilę obecną spróbować PKO lub Pekao.

**Comment by PatrykBocian** [comment]
Problem został rozwiązany, wszystko działa już prawidłowo.
