### ISSUE TITLE
Dostęp do Statystyk serwisu 

### ISSUE THREAD

**Issue by KonradBroda** [allegro/allegro-api#2558]
Witam Zespół Allegro
Przymierzamy się jako zespół do stworzenia Serwisu związanego ze statystykami Allegro oraz analizą statystyczną tychże danych dla indywidualnych użytkowników. Po zapoznaniu się z Waszym regulaminem napotkaliśmy zapis o zakazie takich praktyk. 

_4.1. Oprogramowanie REST API nie może być wykorzystywane w sposób naruszający prawa Allegro.pl oraz osób trzecich, w szczególności niedozwolone jest:
_b. wykorzystywanie do prezentowania danych statystycznych dotyczących wyników sprzedaży konkretnych Użytkowników bez zawarcia odpowiedniej umowy w tym zakresie z Allegro.pl,__
 
Jednak z tego zapisu wynika, iż istnieje możliwość nawiązania współpracy w tej materii na podstawie umowy z Allegro.pl. Czy mogę uzyskać więcej szczegółów takiej umowy oraz zasad na jakich taka współpraca może przebiegać

**Comment by PatrykBocian** [comment]
W tej sprawie skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), w zgłoszeniu dopisz proszę #2558

**Comment by kfijalko** [comment]
@PatrykBocian mam ten sam problem.
Chciałbym porozmawiać o uregulowaniu tej kwestii?

**Comment by PatrykBocian** [comment]
@kfijalko W takim przypadku również zachęcam do kontaktu przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - dopisz w zgłoszeniu #[2558](https://github.com/allegro/allegro-api/issues/2558).

**Comment by kfijalko** [comment]
@PatrykBocian napisałem.

**Comment by PatrykBocian** [comment]
@kfijalko Dziękujemy, dostaliśmy twoje zgłoszenie - skontaktujemy się z tobą bezpośrednio.

**Comment by kfijalko** [comment]
Witam, @PatrykBocian mam w skrzynce xxx milionów ;) maili od allegro i nie wiem czy odpisaliście coś w tej sprawie?

**Comment by PatrykBocian** [comment]
@kfijalko  Powinieneś już widzieć odpowiedź w swojej skrzynce mailowej.
