### ISSUE TITLE
Sandbox - spam mailowy - powiadomienia

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#2559]
Od jakiegoś czasu jestem spamowany przez sandboxa mailami dot. ponownego wystawienia przedmiotów, maile dostaje około co godzinę.

Temat: Ponowne wystawienie przedmiotów
Ponowne wystawienie Twoich przedmiotów nie powiodło się.
Czas wystawienia

pią, 18 paź 2019, 18:38:37
Zakończenie
nie, 17 lis 2019, 18:38:37

Problem jest taki że jak wejdę w sandbox - nie widzę nigdzie żadnej aukcji (być może kiedyś takowa była), nie mogę w żaden sposób wyłączyć tych cholernych powiadomień.

**Comment by PatrykBocian** [comment]
Podaj proszę swój UUID lub login do Sandboxa, zweryfikujemy to.

**Comment by xemix** [comment]
Login: userek

**Comment by PatrykBocian** [comment]
Dziękuje, zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by PatrykBocian** [comment]
Poprawiliśmy zgłoszony przez ciebie problem, wszystko działa już prawidłowo.
