### ISSUE TITLE
Function ("doGetItemsList") is not a valid method for this service

### ISSUE THREAD

**Issue by MarosR** [allegro/allegro-api#256]
Pracuję na nowej wersji WSDL service.php
Wszystkie funkcje działają poza tą: **doGetItemsList()**
Dostaję w jej przypadku błąd: `Function ("doGetItemsList") is not a valid method for this service`
Czym to może być spowodowane ?

Przesyłam właściwe parametry do tej metody, poniżej wywołanie:
```
public function GetItemsList($Options) {
        return $this->_client->doGetItemsList(
                        self::COUNTRY_CODE, $this->_config['allegro_key'], $Options['filterOptions'], $Options['sortOptions'], $Options['resultSize'], $Options['resultOffset'], $Options['resultScope']
        );
    }
```

**Comment by AniaMalinowska** [comment]
Sprawdziłam i metoda działa prawidłowo. 
Proszę, [podeślij nam](https://pomoc.allegro.pl/kontakt/#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) pliki *.XML z request i response i podaj nam tutaj numer zgłoszenia.

**Comment by sz4rlej** [comment]
Czy metoda doGetItemsLists działa poprawnie w stary webapi? Wyskakuje mi dokładnie ten sam błąd.
