### ISSUE TITLE
Problem z aktualizacją aukcji

### ISSUE THREAD

**Issue by frankii91** [allegro/allegro-api#2560]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
 
Pobieram aukcje zmieniam w json **tylko** czas wysyłki i wysyłam a dostaję odpowiedz że json niepoprawny
{"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Nieprawidłowe żądanie."}]}

Jest jakiś problem czy coś ? nie chciał bym wklejać tutaj całego jsona jaki wysyłam

**Comment by PatrykBocian** [comment]
Prześlij proszę pełen request jaki wysyłasz, pomoże to zweryfikować ten problem.

**Comment by frankii91** [comment]
Wysłałem jsona jak wysyłam - program od aktualizacji czasów wysiłek nie jest nowy i działał poprawnie od dłuższego czasu jednak dopiero teraz zauważyłem że jest problem ale od kiedy to nie wiem..

Może coś zmieniło się czasami wysyłek ? Kiedyś gdzieś czytałem że w planach jest likwidacja czasów wysyłek bezpośrednio w aukcji i kiedyś będzie można to robić jedynie za pomocą cenników dostaw jednak teraz nie mogę znaleźć tej informacji nigdzie.

**Comment by PrzemyslawLukanowski** [comment]
Bez przykładowego requestu trudno będzie nam wskazać konkretny błąd. Zamaż dane, których nie chcesz przekazywać i prześlij go tutaj lub użyj naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), wtedy dopisz w zgłoszeniu GitHub #2560.

**Comment by frankii91** [comment]
Wysłałem wiadomość przez formularz.
Jednak dodam że problem występuje nawet wtedy gdy nie zmieniam nic w otrzymanym jsonie a odsyłam dokładnie taki jak dostałem wtedy też jest ten sam komunikat. {"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Nieprawidłowe żądanie."}]}

**Comment by PrzemyslawLukanowski** [comment]
@frankii91 Sprawdziłem to - błąd generuje enter dla treści w polu delivery.additinalInfo, dokładnie to fragment pomiędzy "wpłynąć. W przypadku". Po tym, jak usunę tę przerwę, otrzymuję status 200.

**Comment by frankii91** [comment]
Coś jest nie tak po waszej stronie.
To jakim cudem przez ostatnie klika tygodni/miesięcy wszystko było ok? i nie powodowało problemu?
Do tego ręczna edycja aukcji też nie powoduje problemu.
Ponadto ten enter o którym Pan pisze a dokładnie całe tyn tekst =opis był dodawane nie poprzez API a poprzez waszą stronę.

Ktoś coś u was zmienił i jest problem. Co w związku z tym ? Ktoś naprawi problem po waszej stronie pilnie czy jak ?

**Comment by frankii91** [comment]
Dodatkowo na stronie edycji aukcji formularz edycji tych informacji pozwala na wprowadzenie kilkunastu enterów i nie ma tam odgraniczeń to tym samym w Api też nie powinno mieć miejsca .

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję jeszcze ten przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Gdy dodasz nową linię przez formularz, API skonwertuje ją znaki \r\n lub \n. W przypadku oferty 7796578780 również ma to miejsce. Tak prezentuje się sekcja additionalInfo po pobraniu jej za pomocą GET /sale/offers/{offerId}: 

`"additionalInfo": "Kurierzy dostarczają towary w bardzo zróżnicowanym czasie od 1 do 5 dni roboczych nie jest to zależne od nas i nie można na to wpłynąć.\r\nW przypadku uszkodzonej przesyłki, kurier ma obowiązek spisania protokołu szkody. Jeśli kurier nie chce spisać protokołu szkody klient powinien nie odbierać przesyłki i poinformować nas.",
`

Nie ma tutaj enterów, są zamienione na \r\n. Jeśli prześlesz strukturę w takiej formie, API nie zwróci błędu. Nie wiemy, jak funkcjonuje Twoje oprogramowanie, dlatego zweryfikuj proszę, czy na którymś etapie nie podmienia \r\n na "rzeczywistą" nową linię.

**Comment by frankii91** [comment]
Jak pisał☺em wyżej oprogramowanie działało bez problemu przez dłuższy czas i nie było problemu to u was coś zostało zmienione! MASAKRA!

**Comment by frankii91** [comment]
Dodatkowo Usunięcie wszystkich widocznych enterów oraz \r\n , \r , \n pomogło tylko w części aukcji ... dalej jest ten sam komunikat. nowy json z którym jest problem wysłałem też przez formularz

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem pliki, które wysłałeś - są jak najbardziej poprawne i bez problemu na ich podstawie utworzyłem draft oferty lub zaktualizowałem aktywną. Problem prawdopodobnie występuje przy integracji. Prośba o weryfikację, czy oprogramowanie, z którego korzystasz, nie dokleja lub formatuje jakichś danych. Może miała miejsce aktualizacja softu, która teraz generuje te problemy?

**Comment by frankii91** [comment]
Niestety ale program nie był ruszany a jest własnego autorstwa a może dacie radę sprawdzić logi ?

**Comment by PrzemyslawLukanowski** [comment]
Na podstawie logów widzimy, że ostatni PUT ze zwrotną odpowiedzią 200 miał miejsce 13.11.19. Kolejne, od 29.11.19, kończą się statusem 400. W tym czasie w ofercie nie doszło do żadnych zmian. Ze względu na zwrotny status 400, nie widzimy, jaką dokładnie strukturę json przesyłasz w tym momencie. Ta, którą przesłałeś nam przez formularz, jest prawidłowa.

**Comment by frankii91** [comment]
to co mam robić ? ponieważ testuje i testuje i próbuje coś znaleźć i nie mogę. dodam że wystawanie draftu z tymi samymi danymi (json obkrojony to co nie może być przy drafcie) to draft robi się poprawnie. Myślałem że ma to związek z podpięciem cennika dostawy jednak to nie ma wpływu. Mam wrażenie że aukcje które są u was w systemie są jakoś zablokowane albo mają jakiś błąd. A może konto jest jakoś przyblokowane ?

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj za pomocą PUTa przesłać bez edycji tylko obowiązkowe pola, co powinno zwrócić status 200, czyli: id, name, category, parameters, description, sellingMode, stock, delivery, payments, afterSalesServices i location. Czy w takim przypadku również otrzymujesz status 400? Konto nie jest zablokowane, zweryfikowałem to. Czy możesz przesłać nam za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) pełnego cURLa wraz z nagłówkami dla innego przykładu?

**Comment by frankii91** [comment]
nie wiem co było nagle zaczęło działać.
