### ISSUE TITLE
Dodawanie oferty (DRAFT) sale/offers ? FORBIDDEN 

### ISSUE THREAD

**Issue by oldblackhole** [allegro/allegro-api#2561]
Witam,

Mam problem, w sumie to ciągle jakieś.
Chce dodać Nowa oferete za pomoca RestAPI jako Draft,

Z dokumentacji wynika ze wystarczy podać nazwę jako jedyny wymagany parametr i wszystko powinno być ok.
Za pomocą POSTMANA ustawiam: OAuth 2.0, Access Token za pomoca ktoreg moge np pobierac liste ofert czy kategorie.
Co robie zle ?

{ "category": { "id": "2525" }, "ean": "25525522", "external": { "id": "AH-129834" }, "id": "2525", "name": "gfgfddgf", "product": { "id": "2582525" }, "sellingMode": { "format": "BUY_NOW", "price": { "amount": "123.45", "currency": "PLN" }, "minimalPrice": { "amount": "123.45", "currency": "PLN" }, "startingPrice": { "amount": "123.45", "currency": "PLN" } }, "stock": { "available": 0, "unit": "UNIT" }, "updatedAt": "2019-06-04T06:37:04Z", "validation": { "errors": [ { "code": "string", "details": "string", "message": "string", "path": "string", "userMessage": "string" } ], "validatedAt": "2019-11-24T06:37:04Z" } }

Nagłówek ponizej
https://api.allegro.pl.allegrosandbox.pl/sale/offers
POST /sale/offers? HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Host: api.allegro.pl.allegrosandbox.pl
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6J9.eyJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdLCJleHAiOjE1NzQ3Mjg2MjAsImp0aSI6ImVkYWVlZjM5LTNmYWYtNDZmYS04MTU1LWU1MzlmZDVhZjc3ZiIsImNsaWVudF9pZCI6IjhkOTc5NjVhOTJiMjQwMjA4ZmNhNWIwODJhMTI0ZWQ3In0.vzQk8xlLobW747UOi37NteAZ9ZsWaEIH-O5x-bJDVGDiy1poxBADzT5FhX11CZAX78NCGbPzLKL8CvsCswuvVcOmuK4BdJVjmmIes4jBnhkFPQL9FjjqWuu1cYBSSHr_uEecDw2ecv-tOTVZH6PxJILMfXDK0hgPlJxyWvsMFd5bbw_AWzIA1fPb2h04ahNHz4jK1Esd1eMCoiNFZ0wPJYxKF_-kFDB3X7_WHMxGO-70nxA-UgYN-9iPnOVmLYrMQ8UuhahNqO4cktkdWkMyH7PTPftzRRUCcf7KvE_w6FN167-serttF-poAFYsomk6XHm8Jturv00tp50CuAW76jdjtNwJ6WkvIPGF9BS-J4258zAHPrLH96tcgT2uU3amsYB973xO5X2IDp90zCvLbxQr5WVnpqqFZYVBoLZ-golu126Bv4Hp88Eum2F3ELSscLydEUsigzCrE1bh4KhdTcMd_TDac48rXyCtNjNoyNIdAtJF8_U34NVEiwHeXLX3E8L0GM1eWA6iUIo96WjFymWYqm6-3L2af3sBnolF73qU_PoOrJgZlqoNvZP8i9fF64aNqj4Qz30B18BmVHUcZJMCGrme6xmCUQVY0id74LlIC9USDdbdwspzhIvkS-_59JJNh87b2cr28X19IlA0W5qBzPYiuSBaUQvVc7Cv6Tk
User-Agent: PostmanRuntime/7.15.0
Cache-Control: no-cache
Postman-Token: b677e0ed-6a45-466c-ae0e-69d511c9cdae,bc159201-0270-4075-8d19-1c9c8de083cc
cookie: _cmuid=zpa097kj-6gku-5tjy-shg7-cy3h90n1cax0; TEST_QXLSESSID=433b16b4f0d461bb2304d7baf5f4dd82f01c215c155a17//01; login_analytics=; ws3=LFoXxWZRpk6ZZhPJS5BPwdNNNGhXMDJaQ; cartUserId=2a60de46-8fa8-4d3e-80ff-0b2c82e3815c4478a984-b804-4a7b-8db8-aaf28b86d606; gdpr_permission_given=1
accept-encoding: gzip, deflate
content-length: 623
Connection: keep-alive
cache-control: no-cache

otrzymuje:
{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "Forbidden",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
}

**Comment by PatrykBocian** [comment]
Proszę dla bezpieczeństwa nie zamieszczaj na forum swoich access tokenów.
Ten akurat nie wygląda na prawidłowy, jeśli to nie problem spróbuj wygenerować nowy.
Proszę, upewnij się też - z jakiego typu autoryzacji korzystasz, jeśli z Client_credentials
to wtedy możesz jedynie przeglądać publiczne informacje o użytkowniku, ofertach itp.
Natomiast nie możesz wystawić oferty ani jej modyfikować.
Pomocne informacje dot. struktury oferty znajdziesz w naszym [poradniku](https://developer.allegro.pl/sale/) oraz [dokumentacji](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST).

**Comment by oldblackhole** [comment]
Dziękuje za odp. Token jest ucięty, więc nie jest prawidłowy. Tak korzystam z Client_credentials.

Jak za pomocą POSTMANA (i w przypadku zarejestrowanej aplikacji bez adresu zwrotnego,czyli bez dostępu do przeglądarki, app typu device) mogę dostać to co potrzebuję czyli user_credentials ?
W przypadku POSTMANA ustawienie Authorization Code w typie GranType wyświetla:
Nie możemy wyświetlić strony

Numer błędu: aa6ab7a528b7a014

(callback url wpisałem: https://localhost:8000)

Dużo czasu zostało by zaoszczędzone jeśli w dokumentacji były by po prostu przykłady typowe i częste naszego i waszego.

Czy w ramach jednego konta mogę mieć zarejestrowane 2 aplikacje ? Rozumiem że aplikacja z dostępem do przeglądarki to np dodatek do wordpress ktory laczy sklep z allegro a typu device to np aplikacja napisana w WPF która łączy sie z np aplikacja magazynową i allegro?

**Comment by PatrykBocian** [comment]
W tym przypadku masz aplikacje zarejestrowaną jako taką, która nie ma dostępu do przeglądarki - sam Postman, jest aplikacją graficzną z dostępem do przeglądarki itp. Dlatego by uzyskać redirect_uri wystarczy, że zarejestrujesz go ponownie już jako aplikację z dostępem do przeglądarki. 

Odnośnie aplikacji - tak możesz mieć zarejestrowanych kilka aplikacji na jednym koncie.
Aplikacje typu device są dla urządzeń bez interfejsu graficznego. Więcej informacji na temat autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/).

**Comment by oldblackhole** [comment]
Dziekuje za odp.
Ciągle to samo, tą dokumentacje czytałem kilka razy. Nie ma w niej tego co być powinno. Błąd:
Nie możemy wyświetlić strony

Numer błędu: 518895d07bb0cb20

Proszę napisać czy callback url może byc fakowy ? np http://locahost:8000 ?
Jaki  wybrać Grant Type:  Authorization Code ? Basic Auth ? Api Key ?
Ja ustawiłem OAuth 2.0, nastepnie grant type Authorization Code, Nastepnie callback http://locahost:8000 nastepnie 
Auth URL: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=CLIENT_ID&redirect_uri=http://localhost:8000&prompt=confirm
Nastepnie Access Token URL : https://allegro.pl.allegrosandbox.pl/auth/oauth/token

potem ClienID, Client Secret oraz Client Auth typu Send as Basic Auth header 

prosze do dokumentacji mnie nie odsylac bo tam nie ma takich infromacji. Jak by były to bym nie pytal

**Comment by oldblackhole** [comment]
Pamiętaj! Wszystkie zasoby niezbędne do autoryzacji są dostępne pod adresem https://allegro.pl. Nie są one dostepne pod adresem do wywołania zasobów https://api.allegro.pl/.

Czy ta informacja tyczy serwisu allegro oraz serwisu testowego allegrosandbox.pl ??
Jesli tak to powinno to być jasno napisane. I ta informacja powinna byc  na samym poczatku + inne adresy wymagane.

**Comment by PatrykBocian** [comment]
W tym przypadku problemem jest redirect url który podajesz, nie może to być localhost.
Jeśli chodzi o **Grant Type** - wybierz  **Authorization Code**, natomiast typ autoryzacji ustaw jako **Basic Auth** (podasz tam **Client ID** oraz **Client Secret**).
Taki sposób autoryzacji dotyczy zarówno Sandboxa jak i produkcyjnej wersji serwisu.

**Comment by PatrykBocian** [comment]
Edit: W **redirect_uri** możesz przekazać localhost. Upewnij się, że ten adres przekazałeś prawidłowo  zarówno w **redirect_uri**, jak i przy rejestracji aplikacji.

**Comment by oldblackhole** [comment]
Dziękuje za odp. Proszę się zlitować :). Określenie prawidłowo nic mi nie mówi bo jak bym wiedział co znaczy prawidłowo to by nie pisał :). Proszę o przykład prawidłowego url to wtedy będzie jasne. Podałem kilka **redirect_url** w rejestracji aplikacji. Miedzy innymi http://locahost:8000 podałem też urle do "żywego sklepu na wrodpresie" w którym odpalam scrypt php z próba połączenia się i autoryzacji. NIestety ciągle coś mi nie działa. Jeśli udaje mi się połączyć np pod zasób: **https://api.allegro.pl.allegrosandbox.pl/sale/categories** z **POSTMANA** gdzie nagłówek jest:
Host: api.allegro.pl.allegrosandbox.pl
Accept: application/vnd.allegro.public.v1+json
Authorization: Bearer token......
to przu ystawieniu identyczneg nagłówka w pliku PHP np:

  curl_setopt($curl, CURLOPT_HTTPHEADER, array(
        'Host: api.allegro.pl.allegrosandbox.pl',
        'Accept: application/vnd.allegro.public.v1+jso',
        'Authorization: Bearer token......',
    ));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

**otrzymuje:**

Array ( [errors] => Array ( [0] => Array ( [code] => NotAcceptableException [message] => Not acceptable representation requested. Please check 'Accept' request header [details] => [path] => [userMessage] => The request contains incorrect data. Contact the author of the application. ) ) ) 

to jest jakas masakra, tak jak by to samo działało różnie albo od widzi misie, więc gdzie autoryzacja dalej jak mi podstawy nie działaja.

**Comment by oldblackhole** [comment]
zadziałało w końcu, nie wiem dlaczego, podmieniłem cały nagłówek na ten z POSTMANA i zaczęło działać mimo ze wcześniej wklejałem jego cześć, po czym zmieniłem na wcześniejszy i tez działa.
Jak uzyskać CODE a potem Token ?
wołam adres: 
https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=005805b8cf24471a858ceac78ecb5141&redirect_uri=https://www.guco.pl/allegrorest/src/test_api.php&prompt=confirm

czy coś w header dodaje ?, wysyłam postem ? czy adres zwrotny musi zawierać http://www..... czy może odnosić się do pliku php z którego został wywołany ? czy tylko adres witryny ? Czy w koncu moze być localhost ? np jak używam xampa i plik php które dzwoni pod adres jest lokalnie pod adresem ip lub localhost:8000...... Prosze jasno pisać jeśli coś źle to proszę nie pisać że źle tylko co konkretnie źle. Czy za pomocą POSTMANA istnieje jakaś możliwość zalogowania się i uzyskania code oraz tokena dzięki code który pozwoli na wykonywanie operacji w imieniu użytkownika jako aplikacja/postman/server side

**Comment by PatrykBocian** [comment]
Z tego co widzę, kiedy wywoływałeś zasób sale/categories - powodem błędu była niepoprawna wartość Accept w Headers:

'Accept: application/vnd.allegro.public.v1+jso', zamiast 'Accept: application/vnd.allegro.public.v1+json'.

Odpowiadając na twoje pytania:

- Aby uzyskać Code, wklej adres URL do przeglądarki - https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}, w odpowiedzi, w adresie URL, otrzymasz 10 sekundowy kod. Na tym etapie nic nie przekazujesz w Headers;.
- Za pomocą POST https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={redirect_uri} otrzymasz access token. Jako code przekaż kod, który otrzymałeś we wcześniejszym kroku. W Headers dodaj Authorization (Autoryzacja typu Basic, z zawartością w formie client_id:client_secret - dane otrzymane przy rejestracji aplikacji -  w postaci Base64)
- Adres zwrotny nie musi zawierać www… oraz może odnosić się do pliku php.
- Możesz też użyć localhosta w redirect_uri.


Sprawdziłem też twój redirect_uri - u mnie działa poprawnie. Tutaj problem może powodować próba edycji redirect_uri w aplikacji. Jest to błąd po naszej stronie, pracujemy nad nim.
Na tę chwilę zarejestruj nową aplikację z tym redirectem i wszystko powinno działać prawidłowo.

**Comment by oldblackhole** [comment]
dziękuję za odp :). Jak dla mnie bardziej konkretna z tym że :):

A które adres był wpisany jako redirect czy adres musi być z / na końcu czy nie albo czy możne to być np plik php z którego następuje wywołanie adresu czyli? czy to musi być pełny url z www czy możne być bez www czy to nie ma znaczenia i zależny od tego co zostało podane jako adres redirect w panelu allegro ? Czyli http://www.domena.pl/access.php ?

Dlaczego w przykładzie wpisany jest allegro.pl a nie allegro.pl.allegrosandbox.pl ?
Po odpowiedzi rozumiem że bez problemu teraz powinno działać to ? wystarczy ze w URL przeglądarki wpisze co trzeba i otrzymam co trzeba ?

**Comment by oldblackhole** [comment]
ok, działa, teraz działa. W sumie redirect_url to zwykły fake url, wszystko jedno co tam będzie aby było zgodne z tym co jest w panelu allegro dodane, prawda ? Wszystko to w dokumentacji powinno być napisane trochę inaczej bo powoduje powstawanie niejasności i zbędnych pytań. Coś co powinno zając 1 minute zajęło kilka dni :(

**Comment by oldblackhole** [comment]
blad: {"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed","details":null,"path":null,"userMessage":"An error occurred"}]}

Wywoluje:
https://api.allegro.pl.allegrosandbox.pl/sale/delivery-methods

POST

W headers mam:
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXV itd .....
Accept: application/vnd.allegro.public.v1+json

**Comment by oldblackhole** [comment]
Pytanie:

jesli w dok: np : 
https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST

Nie jest podany np Content-Type to nie murze go ja podawać ?
Rozumiem ze jak jest wszędzie np application/vnd.allegro.public.v1+json to tyczy sie to tylko sekcji Accept: ??

**Comment by PatrykBocian** [comment]
Odpowiadając na pytania:

- W przypadku linków ważne jest, aby zaczynały się od http:// lub https://, mogą to być fake url.
- Content-Type - aby zasób zadziałał prawidłowo, sugerujemy podawanie określonej wartości dla tego nagłówka.
- Accept w Headers jest obowiązkowy.
