### ISSUE TITLE
[Sandbox] Płatność kartą

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2562]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Cześć, 
Nie działa symulator płatności dla kart na sandbox 

Błąd jest taki:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Nov 26 10:00:24 CET 2019
There was an unexpected error (type=Internal Server Error, status=500).
Request processing failed; nested exception is com.netflix.hystrix.exception.HystrixRuntimeException: postMessage failed and no fallback available.

Link:
https://edge.allegro.pl.allegrosandbox.pl/payments/04e9f0e0-102b-11ea-9ffc-7b67248eb06d/cvv/thankYouPageUrl?destination=<CIACH>

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, problem dotyczy kart, które wymagają dodatkowej weryfikacji w banku w procesie 3ds i 3ds2, pracujemy nad rozwiązaniem. Na tę chwilę możesz użyć kart testowych PayU, znajdziesz je poniżej:
http://developers.payu.com/pl/overview.html#sandbox,
http://developers.payu.com/en/3ds_2.html#testing.

W tabelkach znajdziesz numery kart i ich wlaściwości. Jeśli wybierzesz kartę która nie wymaga 3ds, błąd już nie powinien się pojawić.

**Comment by SebastianOzdoba** [comment]
ok dzięki
