### ISSUE TITLE
Przesunięcie godzinowe pomiędzy WEBAPI a RESTAPI

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2563]
Pobierając eventy z **order/events** zauważyłem, że ich odpowiedniki pobierane z **doGetSiteJournalDeals** są przesunięte o jedną godzinę wstecz. Dla przykładu data z SOAP to 11:00, a na REST 10:00. Z czego wynika taka rozbieżność i jak sobie można z nią poradzić?

**Comment by rtnet-pl** [comment]
REST operuje na czasie UTC, a SOAP (z tego co pamiętam) na czasie lokalnym. Zimą jest 1, a latem 2 godz. różnicy. Musisz przeliczyć sobie czas UTC na Twój czas lokalny.
