### ISSUE TITLE
How to change order status over API

### ISSUE THREAD

**Issue by Nemanja-Lima** [allegro/allegro-api#2564]
Hi guys. I'm really sorry for bothering you but can u tell me how can i change status of order to SENT, TO SEND or CANCELED over API. I wasn't able to find it in your doc. Thank you in advance

**Comment by PrzemyslawLukanowski** [comment]
This functionality is not available on API yet. We will introduce it in the near future.

**Comment by Nemanja-Lima** [comment]
Thank you so much for your speedy reply
