### ISSUE TITLE
Usuwanie wybranych opublikowanych ofert

### ISSUE THREAD

**Issue by mfederowicz** [allegro/allegro-api#2565]
Witam 

Chciałbym się dowiedzieć, czy istnieje możliwość usuwania poprzez api opublikowanych już ofert? 

Rozumiem iż zasób DELETE /sale/offers/{offerId} służy do usuwania draftów (ofert o statusie: inactive)

Natomiast czy można usunąć ofertę, której publikację chcemy zakończyć, bądź została opublikowana omyłkowo?

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, przez DELETE /sale/offers/{offerId} usuniesz draft oferty. Aktywnej oferty nie usuniesz, ale w każdej chwili możesz ją zakończyć za pomocą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT), w polu ACTION przekaż wtedy wartość END.

**Comment by mfederowicz** [comment]
Ok @PrzemyslawLukanowski rozumiem, ale taka oferta nadal będzie widoczna, ale że statusem zakończona. Czy takie działanie ma swoje inne uzasadnienie niż tylko w celach statystycznych (ilość wystawionych ofert przez klienta)? 

Czy może warto dodać taką funkcjonalność z dodatkowymi warunkami brzegowymi (może kasować oferty nie starsze niż np 24h)?

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli ukryjesz taką ofertę, wtedy przestanie być widoczna zarówno w zakładce "Moje oferty", jak i przez API:
![Screenshot_14](https://user-images.githubusercontent.com/51473661/69722860-6df6ce80-1118-11ea-97bb-96a270cecf63.png)

Na tę chwilę nie mamy w planach wprowadzenia funkcjonalności, o której napisałeś, jednak przekazałem ją jako sugestię do odpowiedniego zespołu.

**Comment by mfederowicz** [comment]
Ok fajnie, ale czy można (oraz w jakim zasobie), wykonać tą operację ukrywania ofert?
No i też pytanie jak po stronie frontendu wyfiltrować sobie tylko ukryte oferty? Czy może one stają się ukryte na zawsze?:P

**Comment by PrzemyslawLukanowski** [comment]
Oferty możesz ukryć tylko przez front, przez REST API jest to niemożliwe. Akcja ukrywania jest nieodwracalna, dlatego nie możesz filtrować ofert tego typu.
