### ISSUE TITLE
[Smart][Sandbox] Nie da się ustawić

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2566]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o pilną poprawę sandbox tak by dało się uzyskać dla sprzedawcy SMART. W tej chwili nie działają płatności, więc nie da się zrealizować tego w sposób opisany w poradniku.
Blokuje nam to testy aplikacji

**Comment by PrzemyslawLukanowski** [comment]
Problem został rozwiązany, symulator płatności powinien już działać prawidłowo.
