### ISSUE TITLE
How I can get description any offer?

### ISSUE THREAD

**Issue by artimovskiy** [allegro/allegro-api#2568]
Hi,
on our site, users are looking for offers and make an order with delivery to another country (not in Poland). So we make thousands of orders a year on Allegro. With the advent of the REST API we have several problems that we can not solve well.
1) how to get a text description of any offer (the text that is in the block "Opis")?
2) How to get a list of the shipping cost of any offer (the list that is in the block "Szczegóły dostawy")?
3) How to get a list of product parameters (the list that is in the block "Parametry". Most interested in "Stan", " Faktura")

Thank you!

**Comment by PatrykBocian** [comment]
Hi, via REST API  it’s unavailable for now. We'll post the appropriate news, if something changes in this topic.
