### ISSUE TITLE
Attribute id is not allowed - doCheckNewAuctionExt

### ISSUE THREAD

**Issue by MajkelPl55453** [allegro/allegro-api#257]
Dzień dobry,

mam problem przy próbie wywołania metody doCheckNewAuctionExt. Otrzymuję taki błąd: '{https://webapi.allegro.pl.allegrosandbox.pl/service.php}fvalueRangeInt', attribute 'id': The attribute 'id' is not allowed. Czy miał już ktoś podobny przypadek i wiadomo jak to rozwiązać?

**Comment by PawelTaberski** [comment]
Wygląda na to, że podałeś jakieś pole, którego nie obsługuje ta metoda. Podeślij przez nasz[ formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=1436f902-6fd9-420f-9e19-321b684cc8df) pełnego requesta i responsa w formacie XML, a następnie wklej tutaj numer ticketa, sprawdzimy w czym jest problem.
Przypominam, że ta metoda pozwala obecnie tylko na sprawdzenie ogólnych oraz szczegółowych kosztów związanych z wystawieniem oferty przed jej faktycznym wystawieniem.

**Comment by MajkelPl55453** [comment]
Wysłałem 
Ticket#1248214163

**Comment by PawelTaberski** [comment]
Występują błędy w strukturze jaką wysyłasz m.in. (choć nie wiem jak masz to ograne pod spodem), nie powinno się numerować:
`</item0>
		<item1>`
Ponadto nie powinieneś przesyłac dla zdjeć wartości 0:
`<fvalueImage>0</fvalueImage>`
Brak ponadto kilku obowiązkowych parametrów.
Ogólnie polecam przejście z wystawieniem ofert na REST API, więcej na ten temat tutaj: https://developer.allegro.pl/sale/

**Comment by MajkelPl55453** [comment]
Jeżeli chodzi o `<item1> <item2>...` to tak przetworzyło mi mój request w php z tablicy array na xml. Ogólnie mój request przesyła dane takie jak tutaj: 
[https://allegro.pl/webapi/documentation.php/show/id,41#method-input](https://allegro.pl/webapi/documentation.php/show/id,41#method-input) w sekcji "Orientacyjna struktura wywołania metody". I tam jako `<fvalueImage>` jest podane 0, więc tym się wzorowałem. Pola do przesłania pobieram przy pomocy doGetSellFormFieldsForCategory

**Comment by PawelTaberski** [comment]
Jeśli nie przesyłasz zdjęć struktura powinna być taka: `<ser:fvalueImage/>`
Odnośnie zapytania udało mi się wywołać Twoje zapytanie, ale brakowało fid-ów: 27229; 27247; 27291; 34508; 37589; 37593 i  27.
Ponadto musiałem usunąć numerację przy wszystkich item-ach tzn. powinno to wyglądać tak: `<ser:item>`
Do sprawdzenia kosztów wystawienia oferty polecam [kalkulator opłat](https://developer.allegro.pl/news/2018-05-11-Zmiana_w_kalkulatorze_oplat/).

**Comment by MajkelPl55453** [comment]
Hmm to dziwne. Bo ja pobieram pola do formularza przy pomocy `doGetSellFormFieldsForCategory` i zwraca mi takie pola jak w załączniku. Jak wywołuję tę metodę z webapi to podaję `webapiKey = xxxxxxxx, countryId = 1 oraz categoryId = 67525`, czyli wszystkie wymagane pola, a nie otrzymuję tych które Pan podał wyżej że ich brakuje (oprócz 27, ponieważ tego pola nie wypełniłem w formularzu
[response.txt](https://github.com/allegro/allegro-api/files/2053896/response.txt)
)

**Comment by PawelTaberski** [comment]
Przed sekundą wywołałem metodę doGetSellFormFieldsForCategory dla podanej kategorii i fidy te są wymagane - przykład poniżej.
` <ns1:sellFormId>34508</ns1:sellFormId>
                  <ns1:sellFormTitle>Kolor dominujący</ns1:sellFormTitle>
                  <ns1:sellFormCat>67525</ns1:sellFormCat>
                  <ns1:sellFormType>4</ns1:sellFormType>
                  <ns1:sellFormResType>2</ns1:sellFormResType>
                  <ns1:sellFormDefValue>0</ns1:sellFormDefValue>
                  <ns1:sellFormOpt>1</ns1:sellFormOpt>
`
Chyba już widzę w czym jest problem, testowałem Twoje zapytanie na produkcji, a ty chyba wywołujesz swoje zapytanie na Sandboxie i rozbieżność wymaganych fidów może stąd wynikać.

**Comment by PawelTaberski** [comment]
Na środowisku testowym wspomniane przeze mnie fid-y nie są wymagane, ale strukturę należy poprawić tak jak wspomniałem, wtedy zapytanie przechodzi poprawnie. Poniżej wycinek wywołania:
`         <ser:fields>
		<ser:item>
			<ser:fid>2</ser:fid>
			<ser:fvalueInt>67525</ser:fvalueInt>
		</ser:item>
		<ser:item>
			<ser:fid>9</ser:fid>
			<ser:fvalueInt>1</ser:fvalueInt>
		</ser:item>`
