### ISSUE TITLE
Usługa smart, a koszty wysyłki

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2570]
Witam,
czy może mi ktoś wyśnić dlaczego jak ktoś wybierze "smart paczkomat" to api udostępnia koszt wysyłki 0zł,
ale jak wybierze "smart punkt poczty" to koszty już są naliczane ?
Przykładowe checkoutId
39c8bae2-11c4-11ea-a192-87fae59f8851
3a4ede02-11c8-11ea-9c43-558be37c14b9
oczywiście z produkcji bo na sandboxie smart nie działa

**Comment by PatrykBocian** [comment]
W tym przypadku wszystko działa prawidłowo, API zwraca poprawne dane.
W SMART! hubowy sposób rozliczania dotyczy na razie tylko Inpostu, więcej informacji na ten temat znajdziesz na stronach [pomocy Allegro](https://allegro.pl/pomoc/artykul/allegro-smart-zmiana-sposobu-rozliczania-kosztow-przesylek-inpost-pomoc-i-kontakt-5V9rdLDOYf6?utm_source=newsletter).
Co do SMART! na Sandboxie to również jest tam dostępny, wystarczy spełnić dokładnie te same [warunki](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV), co na produkcyjnej wersji serwisu.
