### ISSUE TITLE
Skąd rozbieżność w liczbie ofert...

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#2572]
Dlaczego gdy wejdę w profil użytkownika, jego ilość ofert wynosi 799713 
ale gdy używam metody `/offers/listing` w REST, to wartość `searchMeta.totalCount` wynosi już tylko 763837
Skąd taka duża różnica = 35876 ?

I stąd moje pytanie, co pokazują te dwie wartości, czy w profilu użytkownika, przy pokazywaniu ilości ofert, uwzględniane są oferty archiwalne?

**Comment by PrzemyslawLukanowski** [comment]
GET /sale/offers zwraca informację o liczbie wszystkich ofert (w statusach ACTIVE, INACTIVE, ACTIVATING i ENDED). GET /offers/listing bierze pod uwagę tylko oferty aktywne, stąd różnica.
W profilu użytkownika nie uwzględanimy ofert archiwalnych.

**Comment by mindc** [comment]
Jeżeli chodzi o metodę `/sale/offers` to wszystko jest dla mnie jasne...

Ale chodzi mi o wartość którą widać na `https://allegro.pl/uzytkownik/NAZWA_UŻYTKOWNIKA` - co jest w niej uwzględniane, bo coś więcej niż tylko aktywne oferty

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać id usera, którego dotyczy ta rozbieżność?

**Comment by mindc** [comment]
Wysłałem ID usera przez formularz...

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - wartość, która widnieje na froncie to 796 307 i taką samą liczbę zwraca API. W związku z tym pytanie, czy zauważyłes, aby problem nadal występował?

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
Cały czas jest rozbieżność
na froncie 796 306, w metodzie `GET /offers/listing` wartość klucza `searchMeta.totalCount` wynosi 760 680
nie podaję żadnej frazy do przeszukania

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się odtworzyć tego przypadku, dlatego prześlij proszę pełen request w w formacie cURL wraz z responsem przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz Github #2572.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 

przy przygotowywaniu debuga requestu, tak sobie pomyślałem, że skoro nie mogę znaleźć problemu, to zapewne jest to coś tak oczywistego że tego nie dostrzegam... miałem rację :/

dodatkowy filtr w każdym zapytaniu `sellingMode.format=BUY_NOW`

przepraszam za zamieszanie....

**Comment by mindc** [comment]
Testów ciąg dalszy...

W `/offers/listing` (bez filtrów) mam 793 036 ofert
w `/sale/offers` z filtrami na ACTIVE i ENDED, mam 795 686 (w tym tylko jedna oferta ENDED)

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, w tym momencie wyniki dla konta ******19:
- `/offers/listing `bez filtrów zwraca 796301,
- `/sale/offers` z filtrem ACTIVE - 796301, razem z INACTIVE - 796307.

Wyniki dla drugiego konta, które wskazałeś przez formularz:

- `/offers/listing` bez filtrów zwraca 98272,
- `/sale/offers` z filtrem ACTIVE - 98272, razem z INACTIVE - 98275.

Liczby są zgodne. Czy zauważyłeś jeszcze jakieś nieprawidłowości, które możemy zweryfikować?

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
po najnowszych testach wszystko wygląda ok
dziękuję za pomoc...
