### ISSUE TITLE
Pytanie order/events i status READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2573]
Przepraszam jeżeli było.
ten sam FOD:
jeżeli dostałem zdarzenie ze statusem "READY_FOR_PROCESSING"
i przyszło kolejne zdarzenie ze statusem "READY_FOR_PROCESSING" (nie jest to duplikat)
to w FOD mogły się zmienić:
- payment
- surcharges
- updatedAt - to na pewno się zmieniło bo to nie duplikat

pozostałe pola nie mogły się zmienić?

**Comment by PrzemyslawLukanowski** [comment]
Drugie zdarzenie READY_FOR_PROCCESING pojawi się w przypadku dopłaty, czyli w FOD zmienią się surcharges i updatedAt. Obiekt payment się nie zmieni - dotyczy podstawowej, pierwszej wpłaty.
