### ISSUE TITLE
 get /order/checkout-forms

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2575]
Naprawdę nie można zwiększyć limitu 10 000 przy  get /order/checkout-forms ?
Żeby pobrać formularze z miesiąca wstecz trzeba robić jakieś alpejskie kombinacje?

**Comment by PatrykBocian** [comment]
Zgłosiłem to jako sugestie. Jeśli zdecydujemy się na taką zmianę, poinformujemy o tym w odpowiednim komunikacie.
Na tę chwilę możesz korzystać z dodatkowych filtrów przy tym zasobie:

-lineItems.boughtAt.lte
-lineItems.boughtAt.gte

Więcej informacji na temat zarządzania zamówieniami znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/#01) oraz [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET).
