### ISSUE TITLE
payments/payment-operations 422 

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2576]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od dłuższego czasu korzystam z metody payments/payment-operations bez zmian w kodzie.
Otrzymałam błąd 422 z informacją "expected date field in ISO8601 format (yyyy-MM-ddTHH:mm:ss.SSSZ)".

Wysyłam zapytanie o daty:

    occurredAt.gte => 2019-10-27T00:00:00.000Z
    occurredAt.lte => 2019-11-31T23:59:59.999Z

więc raczej zgadzają się z wymaganym formatem. Czy zmienieniło się coś po waszej stronie w tej metodzie?

**Comment by Gerston** [comment]
Listopad nie ma 31 dni chyba?
