### ISSUE TITLE
Email "Message from WebAPI sandbox environment"

### ISSUE THREAD

**Issue by neldh** [allegro/allegro-api#2577]
Witam
Dostałem wiadomość email z allegro.pl.allegrosandbox.pl typu "ureguluj rachunek w Allegro" (temat: Message from WebAPI sandbox environment).
Czy tego typu wiadomości można spokojnie olać, bo są wysyłane tylko na potrzeby testowe?
Czy może naliczacie jakieś oplaty za korzystanie z allegro sandbox? Nigdzie nie znalazlem o tym żadnej informacji...
Zdziwilo mnie to tym bardziej, że wcześniej nie dostawałem takich wiadomosci z allegro.pl.allegrosandbox.pl...

**Comment by PatrykBocian** [comment]
W tym przypadku ta wiadomość to błąd z naszej strony, zgłosiłem to już do odpowiedniego zespołu.
Na Sandbox naliczamy opłaty zgodnie z cennikiem Allegro (by zasymulować w pełni mechanizm z produkcyjnego Allegro), jednak opłaty te nie są wymagalne. Wystarczy skorzystać z 
[Symulatora płatności](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) aby uregulować należności.
