### ISSUE TITLE
problem z przekierowaniem przy autoryzacji aplikacji oauth typu WEB (code flow)

### ISSUE THREAD

**Issue by atmdevnet** [allegro/allegro-api#2579]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

dzień dobry,
mam problem z aplikacją oauth korzystającą z code flow.
Aplikacja działała bez problemów do chwili kiedy zmieniłem domenę w adresie przekierowania, w panelu "Zarządzanie aplikacjami Allegro". W efekcie, podczas próby autoryzacji wyświetlał się tylko błąd o treści "nie możemy wyświetlić strony...". Nie pomogło dodanie drugiego adresu przekierowania w tej samej aplikacji. Byłem zmuszony do utworzenia nowej aplikacji, co pozwoliło ominąć problem.
Czy możliwość edycji adresu przekierowania w istniejącej aplikacji nie powinno wystarczyć do aktualizacji przekierowań?
pozdrawiam,
Adam.

**Comment by PrzemyslawLukanowski** [comment]
Tak, edycja adresu przekierowania w istniejącej aplikacji wystarczy Ci do aktualizacji przekierowań. Upewnij się, że adres, na który zmieniłeś redirect_uri nie jest z prywatnego zakresu IP. W tym przypadku użyj publicznego adresu ip lub załóż domenę, która kieruje na to ip i podaj ją w redirect_uri.

**Comment by atmdevnet** [comment]
chyba jednak nie wystarczyło, ponieważ nowy adres z nową domeną wskazuje dokładnie na to samo IP (mam kilka domen podpiętych pod to samo IP), na który wskazywał stary adres. IP mam publiczne i nie zmieniło się ono ani przed zmianą adresu, ani po, i również po utworzeniu nowej aplikacji. W ogóle na moim serwerze nic się nie zmieniło poza domeną, którą właśnie uaktualniłem w redirect_uri więc raczej coś jest "nie halo". A po utworzeniu nowej aplikacji oauth, która nie różni się zupełnie niczym w dziedzinie przekierowań od starej zaktualizowanej problem zniknął.
Jest Pan pewien, że edycja redirect'a wystarczy?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, wygląda to na problem po naszej stronie. Wrócę z odpowiedzią po wyeliminowaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@atmdevnet Problem został wyelimowany. Jeśli teraz wyedytuje Pan adres przekierowania dla aplikacji  na stronie https://apps.developer.allegro.pl/, autoryzacja powinna przejść poprawnie.
