### ISSUE TITLE
Brak obsługi wszystkich form faktur na Sandboxie

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#258]
Nie obsługujecie faktury VAT-marża oraz faktury bez VAT w SOAP API. Metoda doGetSellFormFieldsForCategory zwraca dla produkcji:

sellFormDesc: Zwykły przelew|-|-|-|Inne rodzaje płatności|Wystawiam faktury VAT|Wystawiam faktury VAT-marża|Wystawiam faktury bez VAT
sellFormOptsValues: 1|2|4|8|16|32|64|128

Tymczasem dla sandboxa:

sellFormDesc: Zwykły przelew|-|-|-|Inne rodzaje płatności|Wystawiam faktury VAT|-
sellFormOptsValues: 1|2|4|8|16|32|64

Przesłanie 64 oraz 128 podczas tworzenia aukcji jest ignorowane

**Comment by kormichu** [comment]
"Środowisko produkcyjne jest oddzielone od testowego, dlatego mogą się zdarzać różnice w parametrach zarówno w ich numeracji, jak i zawartości."

Widziałem w innym tickecie, że wspominaliście o tym. Mam jednak do parę wątpliwości bo:
a) parametr ten jest globalny, nie jest uzależniony od kategorii
b) przez www pojawia się ta opcja

Pytanie czy REST API też tego nie obsługuje ?

**Comment by PawelTaberski** [comment]
Teraz rozumiem, brak na środowisku testowym opcji dostępnych przez formularz i REST API. Sprawę przekazałem do odpowiedniego zespołu, przez REST API na środowisku testowym są dostępne inne formy faktury.

**Comment by PawelTaberski** [comment]
@kormichu Ujednoliciliśmy formy faktur z produkcją.
