### ISSUE TITLE
 get /order/line-item-id-mappings

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2580]
Takie pytanie. Czy dealId zawsze odpowiada jednemu lineItemowi?

Przy okazji. Czy metody mapujące nie mogłyby przyjmować jako parametrów całych list a nie pojedynczych stringów? Żeby przypisać lineItems do otrzymanych przez doGetRefundsDeals dilów, mam wysyłać 50 tys requestów?

**Comment by PatrykBocian** [comment]
Jeśli chodzi o dealid - jeden dealId to zawsze jeden lineItemId.
Zgłosiłem to jako sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się na taką zmianę, poinformujemy o tym w odpowiednim komunikacie. Na chwilę obecną musisz mapować to pojedynczo.
