### ISSUE TITLE
Wygaszanie metod API

### ISSUE THREAD

**Issue by kamilak23** [allegro/allegro-api#2581]
Korzystam z nowego REST API, a dziś otrzymałam e-mail jak poniżej

"Obsługa zamówień z Allegro - Twoje oprogramowanie korzysta z metod, które wkrótce wyłączymy
Otrzymujesz tę wiadomość, ponieważ korzystasz z oprogramowania, którego metody do obsługi zamówień wyłączymy 13 stycznia 2020"

Proszę o informację do kogo mogę się zwrócić z prośbą, o wskazanie jakie metody z mojej integracji są problematyczne, zwłaszcza że korzystam z REST API.

**Comment by PatrykBocian** [comment]
Możesz sprawdzić w zakładce [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje) rozwiązania, które korzystają z metody dot. obsługi zamówień. Jeśli twoje oprogramowanie  (np. Enadawca, Menadżer Paczek Inpost, etc.) łączy się przez API za pomocą metod do obsługi zamówień, znajdziesz ją właśnie w tej zakładce. Podaj proszę swój Id - sprawdzimy to wówczas dokładnie, możesz to zrobić tutaj lub przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by Draken79** [comment]
Otrzymałem taką samą wiadomość. Korzystam tylko z REST API. Proszę zatem o informacje jakie konkretnie metody REST API zostaną wyłączone w najbliższym czasie, bo nie znalazłem żadnych informacji na ten temat.

**Comment by PatrykBocian** [comment]
@Draken79  Wiadomość dotyczyła tylko metod WebAPI, nie wygaszamy żadnych zasobów REST API.
Konkretne metody, które wygasimy 13.01.2020, to:

- doGetPostBuyData
- doGetPostBuyFormsDataForSellers
- doGetPostBuyFormsIds
- doGetTransactionsIDs
- doGetSiteJournalDeals
- doGetSiteJournalDealsInfo
- doGetShipmentData
- doAddPackageInfoToPostBuyForm
- doGetFilledPostBuyForms
- doGetPaymentMethods

Prawdopodobnie któryś z twoich kluczy korzysta z metod WebAPI, dlatego też otrzymałeś taką wiadomość.

**Comment by kamilak23** [comment]
Ja mam powiązania z dwoma aplikacjami tj.

Pierwsze to aplikacja mojego autorstwa w której korzystam tylko z REST Api
Drugie powiązanie to aplikacja firmy InPost – połączenie z menagerem paczkomatów (https://manager.paczkomaty.pl) 

Wydaje się że to aplikacja InPost jest nie poprawna, czy mają Państwo jakieś informacje na ten temat? Czy InPost korzysta ze starego WebApi?

@Draken79 Czy masz także połączenie z menagerem paczkomatów?

**Comment by PatrykBocian** [comment]
@kamilak23 Dostałeś takiego maila, ponieważ IMenager Przesyłek Inpost korzysta z metod WebAPI.

**Comment by kamilak23** [comment]
dziekuje za informacje
