### ISSUE TITLE
error http 403 /after-sales-service-conditions/implied-warranties

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2582]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

:beetle: **Opis**

1ed379193f1843c7
ec7919222ab64cc7
0cd7b03406002dff
2945bdded2bc7136
796aa3504e2fe190

Dzień dobry, raz na jakiś czas próby requestów do zasobu /after-sales-service-conditions/implied-warranties kończą się wyjątkiem z kodem http 403, a w response przychodzi html. Kody błędów jak wyżej.

W jakim przypadku powstaje taki błąd? Proszę o wyjaśnienie w czym jest problem.

Kod i screen odczytane z odpowiedzi requesta:

![Przechwytywanie1](https://user-images.githubusercontent.com/8465007/70049854-ebfe1e00-15cd-11ea-87ac-8fc606f38c64.PNG)

`<!DOCTYPE html><html>  <head>    <meta charset="UTF-8" />    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    <meta name="robots" content="noindex, noarchive" />    <meta http-equiv="X-UA-Compatible" content="ie=edge" />    <title>Allegro</title>    <meta name="robots" content="noindex, noarchive" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/heading/main-a947e8ed32.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/button/main-2f5426af0f.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/desk/main-17d976d548.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/flex/main-a4cd1b521a.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/margin/main-766502cb09.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/padding/main-dd40004e9c.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/width/main-9a736bcac8.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/align/main-393bd7b83b.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/display/main-eb2fd2e4ff.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/typography/main-6906c4325c.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/card/main-d0352e4ebf.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/brand/main-4e672809d2.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/divider/main-1aa86482d0.css" />    <link rel="stylesheet" href="https://assets.allegrostatic.com/metrum/color/main-3eb13ac13c.css" />  </head>  <body>    <header class="m-display-flex m-flex-items-center m-padding-16">      <img class="m-brand" src="https://assets.allegrostatic.com/metrum/brand/allegro-347440b030.svg" alt="Allegro" />    </header>    <div class="m-desk">      <div class="m-desk__content m-align-block-center m-width-sm ">        <div class="m-card m-color-bg-yellow">          <h4 class="m-heading m-heading--sm ">            Próba otwarcia strony została zablokowana          </h4>          <p class="m-type m-type--paragraph ">            Coś poszło nie tak.             Jeżeli sytuacja się powtarza, to zgłoś ten przypadek obsłudze klienta załączając kod błędu.             Pomoże nam to w szybszym rozwiązaniu Twojego problemu.          </p>        </div>        <div class="m-card m-card--sticky m-color-bg-white m-padding-bottom-0">          <h4 class="m-heading m-heading--sm ">Kod błędu</h4>          <p class="m-type m-margin-bottom-32">            1ed379193f1843c7          </p>          <hr class="m-divider" />        </div>        <a          href="/pomoc"          class="m-button m-button--secondary m-color-bg-white m-width-fluid"        >          skontaktuj się z obsługą klienta        </a>      </div>    </div>  </body></html>`

**Comment by PrzemyslawLukanowski** [comment]
W celu weryfikacji tego zgłoszenia będę potrzebować więcej danych, dlatego prześlij proszę numery trace id oraz user id, którego dotyczy ten problem. Możesz to zrobić tutaj lub za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (wtedy w zgłoszeniu dopisz Github #2582).

**Comment by alekskuc** [comment]
Akurat dla tych requestów nie mam zapisanych trace-id czy wystarczy samo user id 43955783 z sandboxa oraz to, że w/w requesty były z godzin:

2019-12-03 12:14:03.623
2019-12-03 12:14:05.750
2019-12-03 12:14:07.860
2019-12-03 12:14:10.000
2019-12-03 12:14:12.087

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Zlokalizowaliśmy problem po naszej stronie, statusy 403 w tym przypadku nie powinny już występować.
