### ISSUE TITLE
GET /order/checkout-forms/

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2583]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dla zamowienia abf3a352-1458-11ea-97d4-b1b764e5b934, klient wypelnił 2 formularze (pierwsza platnosc nie zostala dokonczona), drugi formularz wypelniony 10 minut pozniej, platnosc zatwierdzona 2 dni pozniej.

Karta płatności wygląda tak:
Utworzenie | 2019-12-01 17:45:13
Rozpoczęcie | 2019-12-03 11:19:02
Zakończenie | 2019-12-03 11:19:02

Natomiast /order/checkout-forms/ zwraca wciaz status "FILLED_IN",

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - zamówienie mimo zakończonej płatności nadal jest w statusie FILLED_IN. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@anaxagore78 Wyeliminowaliśmy problem po naszej stronie, zamówienie jest już w statusie READY_FOR_PROCESSING.

**Comment by anaxagore78** [comment]
@PrzemyslawLukanowski czy udalo sie problem wyeliminowac na dobre? Gdyby klient sie nie upomnial, nie wiedzielibysmy, ze zamowienie jest juz opłacone.

**Comment by PrzemyslawLukanowski** [comment]
Ten konkretny przypadek był powiązany z problemami po naszej stronie, które wystąpiły w momencie ponowienia płatności, przez co nie przetworzył się dla niej odpowiedni event. Podobne sytuacje nie powinny już występować.

**Comment by anaxagore78** [comment]
OK, dziekuje
