### ISSUE TITLE
Zdjęcia

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#2584]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 
Generalnie dodaje zdjęcia do APi a następnie mam błąd że nie nie ma zdjęc.

Provided image address is incorrect: https://a.allegroimg.com/original/119251/32bd9e81456e827063a415251baa

Zdjęcie można obejrzeć ale tylko z komputera które go dodaje. Czy to może być spowodowane ?

**Comment by keczerad** [comment]
Błąd pojawia się przy dodawaniu aukcji jako VALIDATION_ERROR.

**Comment by PatrykBocian** [comment]
Prześlij proszę trace.id, pomoże to zweryfikować problem.

**Comment by keczerad** [comment]
trace-id: 4e439f416a158101

**Comment by PatrykBocian** [comment]
Zdjęcie było wrzucone **2019-12-03 05:16:10.412Z**
z ttl-em **2019-12-03 11:16:10.410Z** , więc zostało usunięte **2019-12-03 12:16:14.601Z**. Próba wystawienia oferty była podjęta **2019-12-03 12:35:13.309**, kiedy zdjęcia już nie było.
Zdjęcia wgrywane przez API mają 6 godzinnego TTL'a, później są usuwane, jeśli nie zostaną powiązane z żadną ofertą. 

Spróbuj ponownie uploadować te zdjęcie i ponownie przypisać je do oferty.
