### ISSUE TITLE
Wystaw przedmiot

### ISSUE THREAD

**Issue by Stagiryta** [allegro/allegro-api#2585]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas próby wystawienia przedmiotu (przez zakładkę Moja sprzedaż oraz okna Moje Allegro) jesteśmy automatycznie przekierowani z https://allegro.pl.allegrosandbox.pl/offer/ na okno logowania do produkcyjnego Allegro.

**Comment by meron1122** [comment]
+1

**Comment by PatrykBocian** [comment]
Przekazałem to do odpowiedniego zespołu.

**Comment by Tomash667** [comment]
Nadal nie działa, teraz przenosi na https://staging-lokalnie.allegrogroup.com/oferty/wystaw

**Comment by PatrykBocian** [comment]
@Tomash667 Informacja o tym problemie trafiła już do odpowiedniego zespołu. Skorzystaj z linku https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, aby tymczasowo obejść ten problem.
