### ISSUE TITLE
[RestAPI] Smart a zamówienie

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2586]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mam zamówienie ze smartem, ale koszt dostawy > 0. Wydaje mi się że powinno być tak że jeśli jest smart to koszt dostawy = 0, proszę o ewentualne sprostowanie
Załączam response
{
"id": "f1b73011-14fc-11ea-bf03-6f90c7636163",
"messageToSeller": null,
"buyer": {
"id": "43955783",
<CIACH>
}
},
"payment": {
"id": "f27d6642-14fc-11ea-93d5-dd17c9b74b05",
"type": "ONLINE",
"provider": "PAYU",
"finishedAt": "2019-12-02T12:14:59.951Z",
"paidAmount": {
"amount": "128.99",
"currency": "PLN"
}
},
"status": "READY_FOR_PROCESSING",
"delivery": {
"address": {
"firstName": "Jan",
"lastName": "Nowak",
<CIACH>
},
"method": {
"id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
"name": "Allegro Paczkomaty 24/7 InPost"
},
"pickupPoint": {
"id": "KRA31A",
"name": "Paczkomat KRA31A",
"description": "Stacja paliw BP",
"address": {
"street": "Bora Komorowskiego 39",
"zipCode": "31-876",
"city": "Kraków"
}
},
**"cost": {
"amount": "8.99",
"currency": "PLN"**
},
**"smart": true,**
"time": {
"guaranteed": null
},
"calculatedNumberOfPackages": 1
},
"invoice": {
"required": false,
"address": null
},
<CIACH>
"surcharges": [],
"discounts": [],
"summary": {
"totalToPay": {
"amount": "128.99",
"currency": "PLN"
}
},
"updatedAt": "2019-12-02T12:14:59.951Z"
}

**Comment by PrzemyslawLukanowski** [comment]
Tak, to prawidłowe zachowanie, ponieważ na sandboxie nie jesteś przepięty na nowy model rozliczeń. Czy dodać Twoje konto, abyś mógł przeprowadzić testy?

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski tak poproszę, dzięki :)
Czy na produkcji może być taka dualność, czyli i smart=true i cost > 0, czy się nie zdarzy?

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem Twoją prośbę do odpowiedniego zespołu.
Tak, na produkcji taki scenariusz jest możliwy.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski rozjeżdza się to z procesowaniem zamówień

Zgodnie z poradnikiem zamówienie powinno być realizowane jeśli 
- ma status: READY, 
- wartość zapłacona = wartości zamówienia 
Jak dodamy do tego SMART to stwierdzenie powyżej nie jest prawdziwe dla niektórych przypadków
Przykład dla SMART: przesyłka pocztowa
Jest SMART, wartość zapłacona <> wartości zamówienia, koszt dostawy > 0

Prośba by to uwspólnić, bo zaczynamy znów robić protezy do działania automatycznych zamówień, że trzeba odejmować koszty dostaw

**Comment by PatrykBocian** [comment]
Nie każdy kupujący ma SMART! i ciężko w tym momencie uwspólnić całkowicie tę funkcjonalność - zawsze będzie możliwe wystąpienie sytuacji, gdzie kupujący realnie dokona zapłaty za wysyłkę. Nowy model rozliczeń z czasem będzie upowszechniany na kolejne metody dostawy.

**Comment by SebastianOzdoba** [comment]
@PatrykBocian  dlaczego i jaka to sytuacja w której realnie dokona zapłaty? 
Jeśli realnie dokona zapłaty za dostawę, oznacza to że wybrał taki sposób dostawy, który nie jest objęty smart-em to znaczy że ta konkretna transakcja "nie jest smart", zatem podsumowując:
- kupujący ma smart, wybrał dostawę wspierającą smart to oznacza na transakcji: smart = true to koszty = 0
- kupujący ma smart, wybrał dostawę niewspierającą smart to oznacza że na transakcji smart = false to koszty > 0
- kupujący nie ma smart to oznacza że na transakcji smart = false, koszty = zgodne z cennikiem
- sprzedający nie ma smart a kupujący ma, to oznacza że smart = false, koszty = zgodnie z cennikiem
- sprzedający nie ma smart, kupujący nie ma smart, co oznacza smart = false, koszty = zgodnie z cennkiem
Jakie inne scenariusze są dostępne?
Takie działanie jest jasne i przejrzyste, w tej chwili znów powstaje jakiś potworek i niepotrzebna logika

**Comment by webcarrot** [comment]
W [samej dokumentacji](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) zabawnie to  wygląda dla smart i płatność przy odbiorze: 

```json
{
  "payment": {
    "id": "0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6",
    "type": "CASH_ON_DELIVERY",
    "provider": "P24",
    "finishedAt": "2018-10-12T10:12:32.321Z",
    "paidAmount": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "status": "READY_FOR_PROCESSING",
  "delivery": {
    "address": {
      "firstName": "Jan",
      "lastName": "Kowalski",
      "street": "Grunwaldzka 182",
      "city": "Poznań",
      "zipCode": "60-166",
      "countryCode": "PL",
      "companyName": null,
      "phoneNumber": null
    },
    "method": {
      "id": "1fa56f79-4b6a-4821-a6f2-ca9c16d5c925",
      "name": "Allegro Paczkomaty InPost"
    },
    "pickupPoint": {
      "id": "POZ08A",
      "name": "Paczkomat POZ08A",
      "description": "Stacja paliw BP",
      "address": {
        "street": "Grunwaldzka 108",
        "zipCode": "60-166",
        "city": "Poznań"
      }
    },
    "cost": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "time": {
      "guaranteed": {
        "from": "2018-01-01T16:00:00Z",
        "to": "2018-01-01T18:00:00Z"
      }
    },
    "smart": true,
    "calculatedNumberOfPackages": 1
  }
}
```

Dla płatności przy odbiorze koszt dostawy to koszt całego zamówienia. Co ciekawe [w "samouczku"](https://developer.allegro.pl/orders/) wygląda to inaczej więc do tego jak działa API trzeba dochodzić po danych zwracanych przez API...

**Comment by PatrykBocian** [comment]
@SebastianOzdoba Większość sytuacji, które opisałeś jest prawidłowa.

Co do “kupujący ma smart, wybrał dostawę wspierającą smart to oznacza na transakcji: smart = true to koszty = 0” - w takim przypadku może wystąpić sytuacja, o której wspomniałem wcześniej tj. kupujący może posiadać SMART!, ale wybierze dostawę np. Poczta Polska, która - nie jest rozliczana wg nowego modelu - pisaliśmy o tym w [Newsie ](https://github.com/allegro/allegro-api/issues/2121) oraz na stronie [Pomocy Allegro](https://allegro.pl/pomoc/artykul/allegro-smart-zmiana-sposobu-rozliczania-kosztow-przesylek-inpost-pomoc-i-kontakt-5V9rdLDOYf6?utm_source=newsletter). W takiej sytuacji smart = true, ale koszt dostawy będzie >0.

@webcarrot Rzeczywiście w tym przypadku jest to błąd w dokumentacji - powinno być “**smart: false**”.

**Comment by SebastianOzdoba** [comment]
@PatrykBocian  jak kupujący mający SMART wybierze Poczta Polska to zapłaci za dostawę, kwotę > 0 czy nie zapłaci?
Tak czy Nie? 

Patrzymy z punktu widzenia poprawności wystawienia faktury dla kupującego przez sprzedającego
Jeśli odpowiedź brzmi NIE to wprowadzacie w błąd, bo wysyłając koszty > 0 i smart=true trzeba je odjąć by na paragonie/fakturze dla Klienta była rzeczywista wartość do zapłaty
Jeśli Klient NIE ponosi kosztów to powinno tam być 0

Reasumując:
- postuluję o zmianę zasady działania, by właściwość: Smart na Order odzwierciedło faktycznie to co się stało na danym konkretnym zamówieniu a nie zawsze było True bo kupujący "ma SMART'a"

**Comment by PatrykBocian** [comment]
@SebastianOzdoba Kupujący ze SMART nigdzie nie płaci za dostawę. Różnica jednak pojawia się po stronie Sprzedającego. Jeżeli jest już przepięty na nowy system rozliczeń i Kupujący wybrał InPost to do Sprzedającego trafia tylko wpłata za towar, co przekłada się jako 0 w odpowiedzi z API. Jeżeli jednak Sprzedający nie jest przepięty na nowy system albo Kupujący w ramach SMART wybrał innego przewoźnika to Sprzedający otrzymuje kwotę X, która widnieje w odpowiedzi z API jako X. Oznaczenie SMART w response ma szersze znaczenie - ma dawać Sprzedającemu też informację czy ewentualny zwrot Kupującego jest darmowy, czy będzie musiał zwracać koszt wysyłki (dla SMARTowych przesyłek tego się nie robi).
Nie możemy przyjąć Twojego założenia, ponieważ nie uwzględnia ono przypadków wyżej wymienionych, a samo pole “smart” ma dużo szerszy kontekst zastosowania.

**Comment by alekskuc** [comment]
Dzień dobry, z którego zasobu rest api można pobrać czy sprzedający jest już przepięty na nowy system rozliczeń?

**Comment by SebastianOzdoba** [comment]
@PatrykBocian dołączam się do pytania @alekskuc

**Comment by PatrykBocian** [comment]
Nie da się pobrać takiej informacji - każdy sprzedający indywidualnie otrzymuje maila z taką informacją w momencie przepięcia na nowy model rozliczeń.

**Comment by michalpokora** [comment]
@PatrykBocian mogę prosić o przełączenie na nowy sposób rozliczania Client:43974801

**Comment by PatrykBocian** [comment]
@michalpokora Kolejne przepięcia na nowy system rozliczeń odbędą się dopiero po nowym roku.

**Comment by hYOUstone** [comment]
@PatrykBocian Wspomniano wyżej, że do Allegro Smart wymagane jest podpięcie konta pod nowy system rozliczeń... Od kilku godzin na Allegro Sandbox bezskutecznie staram się sprawić aby jedna z moich Ofert stała się Smart. Moje ID na Allegro SANDBOX: 44065314; LOGIN rabben; Staram się sprawić jakoś aby moje konto testowe spełniło warunki Smart tj.: 
https://allegro.pl/pomoc/dla-kupujacych/zakupy-z-allegro-smart/kiedy-oferta-bedzie-oznaczona-ikona-allegro-smart-ey2qnaPjGse
oraz
https://allegro.pl/pomoc/dla-kupujacych/dostawa-z-allegro-smart/metody-dostawy-i-zwrotu-przesylek-w-ramach-allegro-smart-a1WrzwbOXf6
Podałem kilka cen jak w tabelce wyżej, "wykupiłem" i dla jednego konta kupującego testowego (Client:44065325) Smart i dla sprzedającego (w/w rabben), dodałem zwroty, gwarancje i wszystkie inne opcje... Dodałem opinie (rabben 100% pozytywnych)... Nie uzyskałęm jeszcze Supersprzedawcy, co również jest dla mnie kłopotem. Wciąż żadna z moich dwóch ofert testowych (6537076754 oraz 6207125743) nie otrzymała statusu Smart. Z endpoinu pobierającego oferty (/order/checkout-forms) wciąż smart=null. Na liście ofert z konta kupującego również nie ma Smart. 
Które opcje muszę jeszcze przestawić, aby Smart wskoczył dla moich ofert testowych? Albo może trzeba moje konto przepiąć na nową formę rozliczeń? 
Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
@hYOUstone Czy spełniłeś wszystkie wymagania okreśolne [w tym artykule](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV)? Sprawdziłem Twoje konto - wszystkie komentarze pochodzą od tego samego użytkownika - pamiętaj, że autorami musi być pięciu unikalnych userów.

**Comment by hYOUstone** [comment]
@PrzemyslawLukanowski Ok. Już teraz nie są tylko od jednego użytkownika. Teraz mam 5 unikalnych komentarzy. Numery listów (przypadkowe) dodane do zamówień (wszystkich aktywnych). Nadal Smart nie wskoczyło do ofert. Nadal nie mam możliwości testowania na brokerze. To jakoś samo wskoczy, czy muszę wykonać jakąś operację. Kompletnie nie mam pojęcia co może być jeszcze przyczyną. Czy Wy ze swojej strony możecie mi jakoś na tym koncie ręcznie mi to ustawić?

**Comment by hYOUstone** [comment]
@PrzemyslawLukanowski Dobra... Smart wskoczył... Po dodaniu unikalnych komentarzy trzeba było wyedytować oferty i zapisać na nowo -dopiero wtedy Udało się uzyskać Smart... Korzystając jednak z okazji... Dlaczego Supersprzedawca mi się nie chce aktywować (jak wyżej)... Krzyczy, że nie jestem firmą a w danych jest "Konto firmowe"

**Comment by PrzemyslawLukanowski** [comment]
@hYOUstone Ustawiłem status Super Sprzedawcy na Twoim koncie.

**Comment by hYOUstone** [comment]
@PrzemyslawLukanowski ... OK. Dziękuję za pomoc.
