### ISSUE TITLE
Limit redirect url na rest api

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#2587]
Dostaliśmy informację od Allegro że najlepiej jest korzystać z Api przy wykorzystaniu jednego klucza api i natkneliśmy się na problem "Przekroczono maksymalną ilość adresów". Jakie jest sugerowane działanie w takiej sytuacji? Mamy bardzo dużo kont allegro które obsługujemy i limit 30 adresów przekierowania jest trochę mały.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij swoje pytanie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz w nim proszę, jakie oprogramowanie reprezentujesz oraz numer zgłoszenia GitHub #2587.

**Comment by d3stozaur** [comment]
> Prześlij swoje pytanie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz w nim proszę, jakie oprogramowanie reprezentujesz oraz numer zgłoszenia GitHub #2587.

Tak też zrobiłem i dostałem informację żeby tam nie pisać skoro zgłoszenie już jest tutaj i mam być cierpliwy. Także poproszę o informację czy w końcu mam pisać i czekać tutaj czy jednak jeszcze raz przez formularz kontaktowy i pisać że przysyłacie mnie z githuba?

**Comment by PrzemyslawLukanowski** [comment]
@d3stozaur Skontaktujemy się z Tobą mailowo.

**Comment by d3stozaur** [comment]
> @d3stozaur Skontaktujemy się z Tobą mailowo.

Podbijam temat, trochę już minęło a nie otrzymałem żadnej wiadomości.

**Comment by PrzemyslawLukanowski** [comment]
Prośba o cierpliwość, w najbliższym czasie udzielimy odpowiedzi.

**Comment by d3stozaur** [comment]
> Prośba o cierpliwość, w najbliższym czasie udzielimy odpowiedzi.

Minal miesiąc, czy juz cos wiadomo?

**Comment by PrzemyslawLukanowski** [comment]
W najbliższych dniach udzielimy odpowiedzi.

**Comment by PrzemyslawLukanowski** [comment]
@d3stozaur Wysłaliśmy już odpowiedź w kwestii tego tematu.
