### ISSUE TITLE
Pobieranie eventów zamówień zwraca status 403

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#2588]
Występuje problem:

[x] z zasobem REST API
[x] ze środowiskiem produkcyjnym

Witam, mam problem z pobranie danych odnośnie obsługi zamówień, wykonuję następującą komendę (oczywiście token poprawny wygenerowany z device flow) 

GET na "https://api.allegro.pl/order/events" zwraca 403 Forbidden {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}

TLDR;

```
curl --request GET --verbose \
  --url https://api.allegro.pl/order/events \
  --header 'Accept: application/vnd.allegro.public.v1+json' \
  --header 'Authorization: Bearer <token>' \
  --header 'Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8'
```

w rezultacie otrzymuję

```
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}
```

```
> GET /order/events HTTP/1.1
> Host: api.allegro.pl
> User-Agent: curl/7.47.0
> Accept: application/vnd.allegro.public.v1+json
> Authorization: Bearer <token>
> Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
>
< HTTP/1.1 403 Forbidden
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: 995fd3add48802c7
< date: Wed, 04 Dec 2019 14:45:22 GMT
< x-ratelimit-remaining: 9000
< x-content-type-options: nosniff
< content-type: application/json
< content-length: 109
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 27
<
* Connection #0 to host api.allegro.pl left intact
```

Nie wiem co robię źle, próbowałem też bić na beta (ale według dokumentacji endpoint jest już w wersji public), jeśli wyślę niepoprawny token otrzymuję poprawnie Unauthorized

Ten sam problem mam odpytując endpoint biblioteką guzzle jak i czytą biblioteką curl obie z poziomu PHP

Aplikacja zarejestrowana, potwierdzona, token otrzymuję przez `/auth/oauth/token?grant_type=client_credentials&code={deviceCode}`

**Comment by PrzemyslawLukanowski** [comment]
> Aplikacja zarejestrowana, potwierdzona, token otrzymuję przez /auth/oauth/token?grant_type=client_credentials&code={deviceCode}

Autoryzujesz się dla grant_type client_credentials, to jest żródłem problemu. Więcej informacji na temat autoryzacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#DeviceFlow).

**Comment by pliszka2** [comment]
@PrzemyslawLukanowski dzięki za odpowiedź, faktycznie nie doczytałem
