### ISSUE TITLE
Pobieranie zdarzeń - zdublowane zdarzenia o statusie READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by maciekstary** [allegro/allegro-api#2589]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Pobieram zamówienia przez API zgodnie z metodą opisaną w dokumentacji REST API (https://developer.allegro.pl/orders/). Zaczynam od pobrania zdarzeń z dziennika i tu od razu jest problem... Pobieram wyłącznie zdarzenia/zamówienia o statusie READY_FOR_PROCESSING. Zgodnie z dokumentacją są to zamówienia gotowe do pobrania. Niestety, zdarza się, że dla danego zamówienia pojawiają się DWA WYDARZENIA o statusie READY_FOR_PROCESSING. Poza numerem wpisu w dzienniku NICZYM się nie różnią. Takie duble powodują, że zamówienia lecą po dwa razy do naszego systemu ERP. Czy moglibyście to poprawić? Dodam, że zdarza się to jedynie co ileś zamówień, nie na każdym.

**Comment by pliszka2** [comment]
Witam, według dokumentacji jest to OK

https://developer.allegro.pl/orders/

Dziennik zdarzeń > Ważne

> Może występować wiele zdarzeń dla jednego zamówienia (minimum jedno) np. zakup, wpłata, dopłata. Możesz np. otrzymać kilka zdarzeń READY_FOR_PROCESSING, dlatego zwróć uwagę na identyfikator zamówienia w obiekcie checkoutForm i to właśnie na nim oprzyj swoją logikę obsługi zamówień.

**Comment by maciekstary** [comment]
Ok, czyli wnioskuję, że trzeba ignorować kolejne zdarzenia READY_FOR_PROCESSING dla danego zamówienia. Trochę to zaskakujące, ale OK. Dziękuję za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
@maciekstary  Dodatkowe zdarzenie READY_FOR_PROCESSING wystąpi także w przypadku dopłaty. Zaobserwujesz wtedy dodatkowe dane w polu surcharges w zasobie GET /order/checkout-forms/{checkoutFormId}.

**Comment by maciekstary** [comment]
Hm, a czy jest jakiś czas, po którym już nic się nie zmieni? Chodzi o to, by wiedzieć, kiedy mogę mieć pewność, że w zamówieniu już nic się nie zmieni. Dotychczas myślałem, że status wystarczy.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku ponownego statusu READY_FOR_PROCCESING dojdzie tylko dodatkowe pole surcharges. Takie dane, jak adres kupującego, metoda dostawy, etc. pozostaną bez zmian. Zamówienie niedopłacone może otrzymać status READY_FOR_PROCESSING - zerknij na [fragment naszego poradnika](https://developer.allegro.pl/orders/#05), gdzie piszemy, jak obsłużyć zamówienią z niedopłatą.

**Comment by maciekstary** [comment]
Ok, dzięki, czyli podsumowując:
1. JEDYNĄ rzeczą, która może się zmienić w przypadku ponownego statusu RFP jest pole surcharges.
2. Powtórzony status RFP bez JAKIEJKOLWIEK zmiany (w którymkolwiek z pól) jest również rzeczą normalną.

Proszę o potwierdzenie.

**Comment by PrzemyslawLukanowski** [comment]
Tak, zgadza się. Co do punktu 1. - w samym checkout-formie oczywiście data w polu updatedAt również będzie zaktualizowana.

**Comment by maciekstary** [comment]
Ok, dziękuję bardzo.
