### ISSUE TITLE
doLoginWithAccessToken - błąd wywołania

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#259]
Metoda przed chwilą zwróciła mi:
Element '{https://webapi.allegro.pl/service.php}countryCode': This element is not expected. Expected is ( {https://webapi.allegro.pl/service.php}accessToken )

Prośba o diagnozę.

**Comment by LukaszKorek** [comment]
Podeślij proszę, za pomocą formularza https://allegro.pl/pomoc/kontakt request i response  w formacie .xml. Pozwoli to na pełną weryfikację zgłoszenia.

**Comment by adampajak** [comment]
Zamykam - klient zmienił hasło do konta..
