### ISSUE TITLE
Informacje o zalicytowanej ofercie

### ISSUE THREAD

**Issue by HMX24** [allegro/allegro-api#2590]
Witam serdecznie. Czy jest możliwość otrzymania informacji z API o zalicytowaniu czy złożeniu oferty w aukcji w formie licytacji ?. Pozdrawiam

**Comment by PatrykBocian** [comment]
Możesz to sprawdzić za pomocą [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents). W przypadku kiedy kupujący złoży ofertę w licytacji znajdziesz tam odpowiednią informację (“type”: “**OFFER_BID_PLACED**”). 
Niedawno dodaliśmy taką funkcjonalność, szczegóły znajdziesz w naszym [newsie](https://github.com/allegro/allegro-api/issues/2540).

Za pomocą [GET /sale/offers?offer.id={offer.id}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) w polu “biddersCount” znajdziesz informacje o liczbie złożonych ofert kupna.
