### ISSUE TITLE
List Przewozowy | Pozyskanie z Allegro API

### ISSUE THREAD

**Issue by allmat** [allegro/allegro-api#2591]
Dzień dobry,

Czy istnieje możliwość pobrać za pomocą Allegro API list przewozowy który np. uzupełniamy dla klienta za pomocą opcji "Numery przesyłek" do zamówienia na stronie allegro.pl?

Dziękuję z góry za pomoc :)

**Comment by PrzemyslawLukanowski** [comment]
Tak, zrobisz to za pomocą [GET order/checkout-forms/{checkoutFormId}/shipments](https://developer.allegro.pl/documentation/#operation/getOrderShipmentsUsingGET).

**Comment by mmgithubpl** [comment]
podlacze sie pod temat - zapytanie POST order/checkout-forms/aaaa/shipments
wykonane dla konkretnego checkoutFormId(aaaa) wykonuje sie poprawnie i zwraca obiekt w postaci 
{"waybill":"xxxx","carrierId":"DHL","lineItems":[{"id":"yyyy"}],"createdAt":"2019-12-12T12:55:55.872Z","id":"zzzz"} gdzie xxxx to przesylany numer listu przewozowego - w tym przypadku kurier DHL.
dlaczego tak wygenerowane listy przewozowe do zamowien nie sa widoczne z poziomu menadzera sprzedazy ms.allegro.pl ?
zapytanie GET order/checkout-forms/aaaa/shipments rowniez zwraca poprawnie utworzony numer przesylki.

**Comment by PatrykBocian** [comment]
@mmgithubpl  Numery przesyłek obsługiwane poprzez API są także widoczne w zakładce “Zamówienia” oraz “Kupione” na stronie WWW. Nie są przekazywane do Menedżera Sprzedaży..

**Comment by mmgithubpl** [comment]
@PatrykBocian są "także" widoczne w zakładce czy są "tylko" widoczne. czy jest szansa na przekazywania do ms.allegro a jeżeli tak to kiedy ?

**Comment by PatrykBocian** [comment]
Nie ma takiej szansy - zakładka “Zamówienia” w tym przypadku zastąpiła Menedżera Sprzedaży. Wprowadzony po API numer przesyłki jest do niej przekazywany, co generuje bezpośrednie powiadomienie email do Kupującego. Dodawanie tego do Menedżera Sprzedaży byłoby dublowaniem tego procesu.
