### ISSUE TITLE
Additional Services

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2592]
Czegoś nie rozumiem.
Po starym WebApi w PostBuyForm 1119493226 jest widoczna usluga dodatkowa za 5 zł.
Na RestApi ani na FrontEndzie tak jakby jej wcale nie było.
O co tu chodzi?

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdziłem rozbieżność. Zgłosiłem problem do odpowiedniego zespołu.
