### ISSUE TITLE
Zmiana danych dostawy na zleceniach ze statusem READY_FOR_PROCESSING 

### ISSUE THREAD

**Issue by moderatoo** [allegro/allegro-api#2593]
Pobieram zamówienia przez API zgodnie z metodą opisaną w dokumentacji REST API (https://developer.allegro.pl/orders/). Zdarzyło nam się, że dane na zleceniu pobrane ze statusem READY_FOR_PROCESSING przy pobieraniu kolejnych eventów zmieniły się w polu adres dostawy na paczkomat. Wg dokumentacji status READY_FOR_PROCESSING  gwarantuje niezmienność danych dostawy. Dlaczego tak sie dzieje? Powoduje to u nas pewne problemy - ponieważ zlecenia ze statusem READY_FOR_PROCESSING  są już procesowane i takie "podmianki" tworzą nam niespójność danych. Jednocześnie powoduje to, że nie mogę blokować zleceń ze statusem READY_FOR_PROCESSING  bo może jeszcze zmienić się adres dostawy.
Na 30tys. pobranych aukcji wykryliśmy na razie  dwa takie przypadki.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz nam podać id tych checkout-formów?

**Comment by kfijalko** [comment]
Panowie, jestem ciekaw dalszych losów tego zgłoszenia.
Występują zmiany w danych dostawy dla READY_FOR_PROCESSING  czy nie?

**Comment by PatrykBocian** [comment]
@moderatoo  Mógłbyś podać id tych checkout-formów? Pomoże nam to zweryfikować zgłoszenie. Możesz je podesłać tutaj lub przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

@kfijalko Jak tylko otrzymamy dane, udzielimy odpowiedzi.

**Comment by moderatoo** [comment]
Przepraszam, czekaliśmy na powtórzony przypadek aby mieć pewność, że tak się dzieje. Proszę o sprawdzenie  2c149ad2-1f3f-11ea-8610-336515058223
