### ISSUE TITLE
Problem z pobieraniem ofert

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2595]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Podczas pobierania ofert ma sandboxie pojawia się błąd:
Server error: GET https://api.allegro.pl.allegrosandbox.pl/sale/offers?publication.status=INACTIVE&limit=1000 
resulted in a 500 Internal Server Error
response: Converting circular structure to JSON

Po zalogowaniu na konto sandbox w zakładce "Moje oferty" przywitał mnie błąd 404:
![sandbox](https://user-images.githubusercontent.com/37405655/70239885-741a2a00-176c-11ea-817f-b3f8e95ed5cf.png)

Czy ktoś jeszcze ma takie problemy?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, zgłosilem to do odpowiedniego zespołu.

**Comment by martacronic** [comment]
@PrzemyslawLukanowski To dodam jeszcze, że jak klikam na sandboxie "Wystaw" to mnie przekierowuje do strony logowania, ale na produkcję, czyli allegro.pl/login.

**Comment by PrzemyslawLukanowski** [comment]
@martacronic Tak, dzięki wiemy o tym, pracujemy nad rozwiązaniem.

**Comment by Ontr** [comment]
Czy można oczekiwać w tym wątku wiadomości jak uda się to naprawić?

**Comment by PrzemyslawLukanowski** [comment]
Tak, poinformuję w tym wątku.

**Comment by rtnet-pl** [comment]
Problem jest także na produkcji


```
GET https://api.allegro.pl/sale/offers?seller.id=23093783&publication.status=ACTIVE&sellingMode.format=BUY_NOW&limit=1000&offset=0 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJ..............2sFijDw
Api-Key: eyJ.NiQbPM=
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Host: api.allegro.pl
Connection: Close

----------------
HTTP/1.1 500 Internal Server Error
server: envoy
trace-id: 3a6ed18d44f8f6a2
date: Thu, 05 Dec 2019 14:25:19 GMT
x-ratelimit-remaining: 8256
content-type: text/plain; charset=utf-8
content-length: 181
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 25
connection: close

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.
```

**Comment by pkrzemo** [comment]
Mam to samo dla **https://api.allegro.pl/sale/offers** niezależnie od parametrów filtrowania

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.

**Comment by SebastianOzdoba** [comment]
Potwierdzam u nas też Klienci zgłaszają ten sam problem na produkcji

**Comment by PrzemyslawLukanowski** [comment]
GET /sale/offers działa już na produkcji i sandboxie.

**Comment by alekskuc** [comment]
Dzień dobry, na sandboxie wróciło dzisiaj HTTP 500. Sandbox user id 43955785

```
2019-12-06 10:16:48.650
2019-12-06 10:15:48.350
2019-12-06 10:14:48.123
2019-12-06 10:13:47.960
2019-12-06 10:12:47.840

REQUEST 2019-12-06 10:16:48.3785895
curl -X GET \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers?limit=1' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \

RESPONSE 2019-12-06 10:16:48.6796048 Duration: 301,0153ms
{
  "ClassName": "System.Net.WebException",
  "Message": "The remote server returned an error: (500) Internal Server Error."
}
```

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację. Odnotowaliśmy dzisiaj nieznaczną liczbę błędów tego typu. Aktualnie zasób działa poprawnie, nie widzimy w logach żadnych błędów 500.
