### ISSUE TITLE
GetRefundsDeals

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2596]
Dobrze widzę, że GetRefundsDeals dla DealId 2211558114 zwraca mi inny buyerLogin niż front end?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać nam id usera, dla którego zauważyłeś tę rozbieżność? Tutaj lub przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (wtedy dopisz GitHub #2596).

**Comment by lukada4100** [comment]
4840187

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, zarówno na WebAPI i na froncie login kupującego jest taki sam - ma*******12.

**Comment by lukada4100** [comment]
problem wziął się stąd, że z query parametrem  buyer.login=ma*******12 nie wyszukiwał mi checkout form, a gdy otworzyłem zakup na frontendzie okazało się że zamiast ma*******12 jest tam Client:6*******7 patrz screen (wysłałem formularzem)

**Comment by lukada4100** [comment]
Hop, hop. Dotarł formularz?

**Comment by PatrykBocian** [comment]
Jest to prawidłowe zachowanie serwisu. W tym przypadku użytkownik mógł zmienić domyślny login typu Client_12345678 na swój własny. Oczywiście jego id pozostaje takie samo.

**Comment by lukada4100** [comment]
Git. A jak znaleźć checkout formy takiego klienta, skoro doGetRefundsDeals zwraca mi jeden login, a do query parametru żeby wyszukać checkout form potrzebuję innego? Informacja, że to ten sam clientId na niewiele mi się tu chyba przyda.

**Comment by PatrykBocian** [comment]
W takim przypadku nie ma niestety żadnego filtra, który by w tym pomógł. Możesz skorzystać z mapowania [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping), aby znaleźć odpowiedni checkout-form. Inną opcją jest też wpisanie id użytkownika na stronie WWW i sprawdzenie obecnej wersji loginu.

**Comment by lukada4100** [comment]
A jak znajdę odpowiedni checkout form? 
Mapując dostanę nie checkout_form, tylko line_item_id, które też nie jest query parametrem do wyszukiwania checkout form.

**Comment by neldh** [comment]
musisz to niestety samemu sobie wyszukiwać (masowo pobierać checkout formy i sprawdzac line item id w nich)
