### ISSUE TITLE
 get /order/line-item-id-mappings

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2597]
Macie mapowanie DealId na lineItemId. A w jaki sposób mając lineItemId można dostać się do lineItem?

**Comment by Gerston** [comment]
/order/line-item-id-mappings?deallId=

i odwrotnie

/order/line-item-id-mappings?lineItemId=

**Comment by PrzemyslawLukanowski** [comment]
> A w jaki sposób mając lineItemId można dostać się do lineItem?

Czy możesz to doprecyzować?  W [naszym poradniku ](https://developer.allegro.pl/migration_guide/#jak-zmigrowa%c4%87-zam%c3%b3wienia) znajdziesz omówienie zasobów, które pozwolą Ci na mapowanie wartości WebAPI na REST i odwrotnie.

**Comment by lukada4100** [comment]
Jedyna znana mi możliwość pobrania lineItem to razem z checkout form, a ponieważ lineItemId nie jest query stringiem to jedyny sposób dostania się do tego lineItem to zaciągnięcie wszystkich checkout form (ewentualnie z filtrami daty albo buyer.login) i sprawdzienie który z nich zawiera lineItem z odpowiednim Id.
Czy może niedoinformowany jestem?

**Comment by lukada4100** [comment]
Query parametrem oczywiście...

**Comment by PrzemyslawLukanowski** [comment]
Zgadza sie, nie przekażesz lineItemId jako query parametru, więc jedynym rozwiązaniem jest te, o którym wspomniałeś.

**Comment by lukada4100** [comment]
Nie rozpieszczacie...
