### ISSUE TITLE
[rest api] problem z logowaniem

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#2598]
Od wczoraj mam problem z zalogowaniem się do Allegro przez aplikację, komunikat jaki się pojawia to "Login, e-mail lub hasło są nieprawidłowe", logując się tymi samymi danymi przez przeglądarkę nie ma problemu.
Na kontach już podpiętych pod program mogę normalnie zarządzać ofertami. czy były wprowadzane jakieś zmiany w rest api?

**Comment by PrzemyslawLukanowski** [comment]
Wyślij proszę pełen request w formacie cURL (wraz z trace-id) oraz response przez nasz[ formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #2598.

**Comment by kamilpiech97** [comment]
też mam taki problem

**Comment by PatrykBocian** [comment]
@kamilpiech97 Mógłbyś dokładniej opisać ten problem? Możesz to zrobić tutaj lub przez f[ormularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by mlonc** [comment]
W moim przypadku, temat został rozwiązany poprzez otwieranie okna autoryzacji aplikacji bezpośrednio w przeglądarce a nie w oknie programu.
