### ISSUE TITLE
Subskrybcje / webhooki dla aukcji

### ISSUE THREAD

**Issue by mbartuzi** [allegro/allegro-api#26]
Czy jest możliwość otrzymywania informacji w momencie, gdy ktoś dokona zakupu na naszej aukcji? Najlepiej w postaci subskrybowania danej kategorii, konkretnej aukcji, lub wszystkich naszych aukcji. W dokumentacji nie widzę o tym informacji.

**Comment by MarcinLuczak** [comment]
Nie wysyłamy przez API żadnych powiadomień bezpośrednio do użytkownika, ale informacja o zakupie w ofercie są dostępne w dzienniku zdarzeń - [doGetSiteJournal](https://allegro.pl/webapi/documentation.php/show/id,65).
