### ISSUE TITLE
Błąd parametru ZESTAW w ODZIEŻY

### ISSUE THREAD

**Issue by ZieGDA** [allegro/allegro-api#260]
Po raz kolejny pojawia się jakiś problem z parametrami, które oznaczyliście jako obowiązkowe.

W kategorii Odzież, Obuwie, Dodatki / Bielizna Męska / Majtki pojawia się problem przy parametrze "ZESTAW"
Mam 8 aukcji w których kategorie i parametry są identyczne, w 2 aukcjach nie mogę aktualizować parametru poprzez nasz program, reszta się zaktualizowała.
 
Jak już sobie stwierdziliście, że okres zmiany opisów na nowe jest znakomitym momentem na to, żeby wprowadzać DODATKOWE wymagania dotyczące parametrów, to chociaż róbcie to tak, żeby nie utrudniać nam pracy. Naprawcie to jak najszybciej.

![przechwytywanie](https://user-images.githubusercontent.com/39126621/40658662-39f0dc00-634c-11e8-95c1-646f3d84c8e7.JPG)

**Comment by LukaszKorek** [comment]
Poproszę o doprecyzowanie problemu z dodaniem tego parametru - fida 29577. Sprawdziłem i w tej kategorii ten parametr jest obowiązkowy.
