### ISSUE TITLE
"Edycja wielu ofert jednocześnie"

### ISSUE THREAD

**Issue by burnburnburn123** [allegro/allegro-api#2600]
Dzień dobry.
1. jak zmienić czas realizacji (handling time) w wielu ofertach - czy da się to zrobić masowo dla wszystkich ofert? lub co najmniej dla dużych grup?
2. Czy jest prosty sposób aby szybko wyłączyć wszystkie oferty na koncie allegro(zamknąć aukcje)? Np. z panelu konta allegro lub kontaktując się z helpdesk allegro?

**Comment by PatrykBocian** [comment]
Odpowiadając na twoje pytania:

- Poprzez API możesz zmienić czas wysyłki tylko na pojedynczych ofertach, nie ma możliwości grupowej zmiany, sugestię zmiany mamy już w naszym backlogu;
- Możesz skorzystać z zasobu PUT/sale/offer-publication-commands/{commandId} i grupowo (max 1000 ofert jednocześnie) zmienić status ofert na “END”. W serwisie WWW możesz skorzystać z opcji Zakończ w zakładce Moje oferty.

**Comment by burnburnburn123** [comment]
ale czy w serwisie WWW mogę łatwo zamknąć wszystkie aukcje? Będę wdzięczny za informację jak. Przy 80 tys aukcji zaznaczanie po 500-1000 i zamykanie partiami trwa strasznie długo.

**Comment by PatrykBocian** [comment]
Niestety w tym przypadku nie ma takiej możliwości. Jedyną opcją jest zamykanie 1000 ofert jednocześnie.
