### ISSUE TITLE
Pobieranie płatności 

### ISSUE THREAD

**Issue by MatiKapka** [allegro/allegro-api#2601]
Dzień dobry,
Chcę pobrać płatności z ostatniego miesiaca. Aplikacja napisana w c#. Przypuszczam, że problem jest z datami, gdyż nie dostaję płatności z poczatku miesiacu tuż po północy, np. 01.11.2019 00:12.
Na poczatku usawiam daty dla Listopada:
     DateTime dateFrom = new DateTime(2019, 10, 31, 23, 59, 59, DateTimeKind.Utc);
      DateTime dateTo = new DateTime(2019, 11, 30, 23, 59, 59, DateTimeKind.Utc);
, a natępnie konwertuję do stringa:
     m_DateFrom = dateFrom.ToString("yyyy-MM-ddTHH:mm:ssZ");
      m_DateTo = dateTo.ToString("yyyy-MM-ddTHH:mm:ssZ");
, kolejno wykorzystuje je w ten sposob:
string address = $@"payments/payment-operations?wallet.type=AVAILABLE&occurredAt.gte={m_DateFrom}&occurredAt.lte={m_DateTo}&group=INCOME&limit=50&offset={offset}";

Proszę o pomoc.
Pozdrawiam

**Comment by Bober95** [comment]
Nie wiem czy ma to znaczenie ale według dokumentacji powinno być
`yyyy-MM-ddTHH:mm:ss.fffZ`

lub spróbuj użyć:
`dateFrom.ToString("o")`

Nie testowałem

**Comment by PatrykBocian** [comment]
Niestety ze względu na dużą ilość języków programowania, nie prowadzimy wsparcia z każdego z nich. Może któryś z użytkowników forum będzie w stanie ci pomóc. Spróbuj też, jak radzi ci @Bober95  przekazać datę w wskazanym formacie.

**Comment by MatiKapka** [comment]
Zgodnie ze wskazówką @Bober95 poprawiłem format daty, ale to nie pomogło. Tu chyba język programowania nie gra roli.
Istnieje rozbieżność między raportem excela, a danymi z rest api - w raporcie data wygląda tak: 
01.11.2019 00:12
, a odczytana z rest api: 
31.10.2019 23:12
, czyli za pomocą rest api data jest o godzinę wcześniej.

**Comment by kfijalko** [comment]
ja pisze w PHP i korzystam z biblioteki Carbon. sprawdź czy nie ma takiej dla c#. Jest bardzo pomocna.
Data/czas w Rest jest wyrażona w UTC ISO 8601.
https://pl.wikipedia.org/wiki/Uniwersalny_czas_koordynowany

na przykładzie fod
[updatedAt] => 2019-12-06T18:00:20.432Z
odczyt
$dt = Carbon::parse($fod->updatedAt,'UTC')->setTimezone('Europe/Warsaw');
Czyli odczytuję w UTC i przestawiam na Warszawę.

formatowanie na potrzeby rest:
$dt->toIso8601ZuluString();
zulu=utc

**Comment by kfijalko** [comment]
nie napisałem tego wyżej w prost:
biblioteka Carbon zapewnia mi "automatyczne" przeliczanie godzin,
w Twoim przykładzie należy to zrobić ręcznie lub znaleźć odpowiednia bibliotekę
zgodnie z linkiem powyżej:
Polska znajduje się w strefach czasowych:
UTC+01:00 (czas środkowoeuropejski (CET), w okresie zimowym) oraz
UTC+02:00 (czas środkowoeuropejski letni (CEST), w okresie letnim).

**Comment by MatiKapka** [comment]
Przy ustawianiu zakresu dat dodałem data.ToUniversalTime() i to mi odejmuję godzinę, a następnie przy pobieraniu robię data.ToLocalTime() i to mi dodaję godzine.
Teraz wszystko się zgadza.
Dziękuje za pomoc.
