### ISSUE TITLE
Zmiana statusu zamówienia API

### ISSUE THREAD

**Issue by yo-tech-pl** [allegro/allegro-api#2602]
Witam, 

W zakładce Moja sprzedaż -> Zamówienia jest lista zamówień którą można filtrować za pomocą statusu: nowe, w realizacji, do wysłania itd. 

Czy za pomocą API mogę zmienic status zamówienia, ponieważ zamówienia u nas są obsługiwane za pomocą zewnętrznego narzędzia, nie z  Menedżer Sprzedaży ms.allegro.

Proszę o pomoc jak ustawić taki status z zewnętrznego systemu. 

Pozdrawiam,

**Comment by PatrykBocian** [comment]
Poprzez API nie można zmienić statusu zamówienia. API obecnie obsługuje trzy statusy: B, FI, RFP. Pracujemy, aby w przyszłości pojawiła się możliwość edycji statusu zamówienia, podobnie jak ma to miejsce w serwisie WWW.
