### ISSUE TITLE
Problem z wystawieniem draftu oferty / oferty.

### ISSUE THREAD

**Issue by kamilpiech97** [allegro/allegro-api#2603]
Dzień dobry, piszę w sprawię problemu z wystawianiem ofert na testowym koncie ale i zapewne na normalnym koncie normalnym allegro.

Pobieranie kategorii czy opcji dostaw odbywa się normalnie lecz dodanie draftu już nie.
Jako response otrzymuje 403 Frobiden.

Prześlę poniżej mojego curl'a.

Uzyskanie tokena:

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "...";
    $clientSecret = "...";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);
    echo $tokenObject->access_token;
    return $tokenObject->access_token;}

Dodanie draftu:

```
AllegroRestApi::refreshToken(
    $tokens->refresh_token, 
    $clientId, 
    $clientSecret, 
    $redirectUri
);

// If we have our access token we can finally request REST API

$tokens = getAccessToken();
// Creating an instance of RestApi
$restApi = new AllegroRestApi($tokens);

// Getting our comments
$response = $restApi->get('/sale/user-ratings?user.id=' . $yourUserId);

// Creating 2 variants using color/pattern
$response = $restApi->put('/sale/offers/' . $restApi->getUuid(), array(
    'name'       => 'Oferta testowa'
), array(
    'Content-Type' => 'application/vnd.allegro.beta.v1+json', // Some actions needs version change from "public" to "beta"
    'Accept'       => 'application/vnd.allegro.beta.v1+json', // Some actions needs version change from "public" to "beta"
));
header('Content-Type: application/json');
print_r($response);
?>

```

**Comment by PatrykBocian** [comment]
Autoryzujesz się dla **grant_type** - **client_credentials**, to jest źródłem problemu. Aby wystawić ofertę musisz być zautoryzowany jako użytkownik korzystając z **code_flow** lub **device_code**.  Więcej informacji na temat autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/).
