### ISSUE TITLE
[WebApi] brak wpłaty w doGetMyIncomingPayments

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2604]
Występuje problem: 
 - [x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Witam, zdarza się, że w WebApi nie ma informacji o płatności do zamówienia

Zamówienie WebApi id: 1123600359
Zamówienie czas: 2019-12-03 17:39:23 
Płatność (zakończenie): 2019-12-03 17:40:01 
Typ płatności: BLIK (przelewy24)

Metoda doGetMyIncomingPayments nie zwraca informacji o płatności.

Na formularz kontaktowy przesłałem request i response

**Comment by PatrykBocian** [comment]
Rzeczywiście występuje taki błąd, przekazałem to do odpowiedniego zespołu.
Chwilowo możesz korzystać z opcji filtrowania po czasie: “**transRecvDateFrom / transRecvDateTo**” - wówczas prawidłowo widać płatność.

**Comment by PatrykBocian** [comment]
Zweryfikowaliśmy ten błąd, zostanie to naprawione.

**Comment by Radeq** [comment]
@PatrykBocian, czy udało się rozwiązać problem?

**Comment by PatrykBocian** [comment]
Trwają już nad tym prace - zostanie to naprawione.
