### ISSUE TITLE
Pytanie o dużą liczbę wywołań Rest

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2605]
W ramach projektu planuję wykonać dużą liczbę zapytań do Rest.
1) pobranie drzewa kategorii z parametrami i wartościami = około 50k req
2) pobranie listingów dla wszystkich kategorii liści = maksymalnie 21k x 60 stron = 1,26 mln req
Całość poleci w kolejkach: 20 do 50 executorów. Tego jeszcze nie wiem.
Nie przekroczą 9k req/min.

Pytanie:
Czy to jest dla restapi dużo czy nie?
Czy puścić w określonych godzinach, czy nie ma znaczenia?
Czy mnie jakiś filtr "ddos" lub inny wytnie albo doda do czarnej listy?

**Comment by PatrykBocian** [comment]
Na REST API mamy nałożony limit 9 000 requestów na minutę. Stosujemy też algorytm Leaky Bucket -  wtedy przy przekroczeniu limitu wydłużamy czas odpowiedzi. Możesz wykonać takie requesty o dowolnej godzinie. Jesteśmy przygotowani na taki ruch.
