### ISSUE TITLE
Długie czasy odpowiedzi sale/products

### ISSUE THREAD

**Issue by promsters** [allegro/allegro-api#2607]
Występuje problem:
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Czy na ten endpoint produktowy są narzucone jakieś dodatkowe limity requestów?
Przy wykonywaniu 1 requestu co 1.5s czasy odpowiedzi api nie przekraczają 0.2s i to jest jak najbardziej poprawne. Natomiast gdy request wykonuje częściej - co 0.5s to czasy odpowiedzi po kilku (czasem kilkunastu) pierwszych requestach rosną do 3-10+s.

Requesty:
(czasy odpowiedzi na samym dole)
```
> GET /sale/products/5189105a-0879-4502-9d9e-624e40f7faeb HTTP/1.1
Host: api.allegro.pl
User-Agent: Guzzle/5.3.1 curl/7.52.1 PHP/7.2.11
Content-Type: application/vnd.allegro.beta.v1+json
Accept: application/vnd.allegro.beta.v1+json
Authorization: Bearer eyJhbGciOiJSUzI1...

< HTTP/1.1 200 OK
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: 92bc084111407710
< date: Tue, 10 Dec 2019 08:50:31 GMT
< x-ratelimit-remaining: 8998
< x-content-type-options: nosniff
< content-type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< content-length: 1256
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 116
<
* Curl_http_done: called premature == 0
* Connection #1 to host api.allegro.pl left intact

=== TT 0.20016503334045 s
```
(pierwszy)

```
> GET /sale/products/5189105a-0879-4502-9d9e-624e40f7faeb HTTP/1.1
Host: api.allegro.pl
User-Agent: Guzzle/5.3.1 curl/7.52.1 PHP/7.2.11
Content-Type: application/vnd.allegro.beta.v1+json
Accept: application/vnd.allegro.beta.v1+json
Authorization: Bearer eyJhbGciOiJSUzI...

< HTTP/1.1 200 OK
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< server: envoy
< pragma: no-cache
< x-frame-options: DENY
< trace-id: ed790dd2cf3f4ff3
< date: Tue, 10 Dec 2019 08:50:41 GMT
< x-ratelimit-remaining: 8996
< x-content-type-options: nosniff
< content-type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< content-length: 1256
< x-ratelimit-limit: 9000
< x-envoy-upstream-service-time: 5234
<
* Curl_http_done: called premature == 0
* Connection #3 to host api.allegro.pl left intact

=== TT 5.3217639923096 s
```
(drugi po odczekaniu 0.5s)

**Comment by PatrykBocian** [comment]
Jest to prawidłowe zachowanie - dla wybranych zasobów REST API stosujemy dodatkowy mechanizm, który ogranicza liczbę zapytań dla danego użytkownika (user.id). Wykorzystujemy algorytm Leaky Bucket. Gdy użytkownik przekroczy dozwoloną liczbę wywołań na minutę (RPM), wydłużamy czas odpowiedzi.

**Comment by promsters** [comment]
![image](https://user-images.githubusercontent.com/6871138/70521323-4f90ca00-1b3f-11ea-8575-ebbca84f783d.png)

**Comment by promsters** [comment]
Gdzie w takim razie znajdę informację o tym jakie dodatkowe limity są narzucone na poszczególne endpointy? No i dlaczego dane w headerze odpowiedzi wskazują na to, że ratelimit nie został wykorzystany.

**Comment by PatrykBocian** [comment]
Dla zasobu, z którego korzystasz obowiązuje dodatkowy limit liczby zapytań tzw. [Leaky Bucket](https://developer.allegro.pl/about/#Leaky_Bucket).
Natomiast widoczny na screenie limit to limit główny tj. 9000 req/min dla każdego jednego zasobu REST API.  W naszym [poradniku ](https://developer.allegro.pl/productization/) informujemy o dodatkowym limicie dla [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts).
