### ISSUE TITLE
Klient płaci na koto i dane zamówienia

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#2608]
Nie znalazłem rozwiązania następującego problemu:

Zgodnie z dokumentacją i info tutaj: https://developer.allegro.pl/orders/
Status **READY_FOR_PROCESSING**
"Dopiero w tym statusie zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni..."

Co w przypadku, jeśli klient kupuje 1 rzecz i chce wpłacić za zakupy bezpośrednio na konto sprzedawcy? Mimo wykonanego przelewu, allegro nic nie wie o przebiegu płatności. API podrzuca więc zamówienie ze statusem FILLED_IN bez adresu dostawy (dane nie są w 100% pewne). Trudno jest dalej obsłużyć poprawnie tego typu zamówienie. Jak sobie poradzić w takiej sytuacji?

Wielka prośba o informacje

**Comment by Onixarts** [comment]
Po wybraniu tego zamówienie powinno się chyba ustawić na Ready_for_processing. Jesteś pewien, że nie dostajesz takiego statusu po chwili?

**Comment by PatrykBocian** [comment]
W takim przypadku nigdy nie uzyskasz statusu **READY_FOR_PROCESSING**.
Kupujący pomija płatność przez Allegro Finanse i proces kończy się tylko na statusie **FILLED_IN**. W Allegro nie ma już dostępnej opcji “zwykły przelew” jako formy zapłaty bezpośrednio na rachunek sprzedającego.

**Comment by mjag8** [comment]
@PatrykBocian 
Czyli tak w zasadzie, to należałoby uniemożliwić klientom płacenie "zwykłym przelewem" (no bo w tym przypadku de facto nie ma możliwości pozyskania danych dostawy). Drugie wyjście to każdorazowo mailować do klienta o podanie adresu do wysyłki i ręcznie uzupełniać brakujące dane. 

Jest dostępna jakaś lepsza możliwość lub może coś ulegnie zmianie po stronie API allegro?

**Comment by PatrykBocian** [comment]
Z naszej strony usunęliśmy taką możliwość (likwidacja opcji “zwykły przelew”), aby kupujący mógł zapłacić bezpośrednio na numer rachunku sprzedającego. Jeśli samemu nie przekażesz kupującemu takich danych, taka sytuacja nie będzie miała miejsca.

**Comment by bacok** [comment]
@PatrykBocian także interesuję się tym tematem, ponieważ dopóki nie zostanie opłacone zamówienie - nie mamy żadnych informacji na temat danych adresowych klienta (a w SOAP były tuż po wypełnieniu formularza dostawy).
Pozwoliłem sobie kupić coś przed momentem na środowisku produkcyjnym i to co jest napisane wyżej nie pokrywa się z rzeczywistością:
https://ibb.co/m9xfxcN
Jak widać można wykonać przelew tradycyjny, a więc kupujący może dokonać wpłaty bezpośrednio, a z API nadal będzie przychodziło **FILLED_IN**.

**Comment by PatrykBocian** [comment]
> Pozwoliłem sobie kupić coś przed momentem na środowisku produkcyjnym i to co jest napisane wyżej nie pokrywa się z rzeczywistością:

@bacok  Pokrywa się to z rzeczywistością - jest to przelew obsługiwany przez Allegro Finanse i płatność nie trafia bezpośrednio na rachunek sprzedającego, a jest procesowana przez PayU lub P24. Dla takiej płatności otrzymasz standardowe eventy: **BOUGHT**, **FILLED_IN**, **READY_FOR_PROCESSING**. 

Tak zwany “zwykły przelew” nie jest już dostępny na Allegro.

**Comment by bacok** [comment]
Ok, dziękuję za odpowiedź.
