### ISSUE TITLE
Problem przy dodawaniu zdjęć

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#2609]
Kilka dni temu coś się zmieniło w dodawaniu zdjęć do oferty i dostaje komunikat że typ image/jpg nie jest poprawny. Wcześniej wszystko działało z jpg nie trzeba było używać jpeg więc zakładam że to jakiś błąd. 

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => DownloadInvalidContentType
                    [message] => Image has invalid content type: image/jpg (supported types: [image/png, image/jpeg, image/gif]).
                    [details] => 
                    [path] => 
                    [userMessage] => Image has invalid content type: image/jpg (supported types: [image/png, image/jpeg, image/gif]).
                )

        )

)

**Comment by PatrykBocian** [comment]
Przekazałem to do odpowiedniego zespołu.

**Comment by PatrykBocian** [comment]
Wdrożyliśmy już odpowiednią zmianę - zasób działa prawidłowo.
