### ISSUE TITLE
doAddPackageInfoToPostBuyForm a email z numerem przesyłki - sandbox

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#261]
Korzystając z WebApi i metody [doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744) dodałam numer przesyłki do testowego zamówienia na sandboxie. Numer został przekazany poprawnie i jest widoczny w panelu Allegro od strony kupującego. Oczekiwałam zgodnie z informacją na stronie [tutaj](https://allegro.pl/pomoc/faq/dlaczego-warto-udostepnic-klientom-numer-przesylki-i-jak-to-zrobic-5Vq58KD6Rtn), że po po dodaniu numeru wysyłki tą metodą otrzymam na mail testowego klienta informację o numerze przesyłki, co nie nastąpiło.

Czy to jest błąd środowiska sandbox, czy również w środowisku produkcyjnym te maile nie są wysyłane (jeszcze wysyłane, bo to dopiero planujecie)?

Nie wyobrażam sobie możliwości testowania tego mechanizmu na "żywych" klientach produkcyjnych.

**Comment by PawelTaberski** [comment]
Przetestowałem i rzeczywiście metoda działa prawidłowo, ale brak powiadomienia mailowego. Sprawę zgłosiłem do odpowiedniego działu, proszę o cierpliwość.
