### ISSUE TITLE
Błąd przy metodach płatności w allegro sandbox

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2611]
Na stronie allegro sandbox nie ma możliwości wyboru metody płatności i zrobienia przelewu bo metody płatności wogóle się nie wyświetlają. Podczas zamawiania i tak samo podczas spłaty w rozliczeniach. Proszę o naprawienie błędu

**Comment by AlpanetPL** [comment]
Podłączę się pod temat, bo mam ten sam problem. Próbowałem aktywować płatności PayU albo Przelewy24, ponieważ myślałem, że wtedy pojawią się inne opcje płatności podczas składania zamówienia, ale w przypadku PayU przechodzę do sandboxowego banku i kliknięcie zielonego guzika nic nie daje, a w przypadku Przelewy24 mam ciągle status, że czeka na weryfikację. Reasumując, proszę o:
- aktywację tych płatności dla użytkownika "alpallegro"
- umożliwienie wyboru innych sposobów płatności niż raty.

**Comment by PatrykBocian** [comment]
Przekazałem sprawę do odpowiedniego zespołu.

**Comment by PatrykBocian** [comment]
Problem został rozwiązany, wszystko działa już poprawnie.

**Comment by AlpanetPL** [comment]
Potwierdzam. Dziękuję za pomoc.

**Comment by AssAssIn1909** [comment]
Na sandboxie, statusy weryfikacji usług Przelewy24 i payu mam cały czas w trakcie weryfikacji. Można coś z tym zrobić?

Konta ITPKRK oraz MLA

**Comment by PatrykBocian** [comment]
@AssAssIn1909 Wypłaty powinny już być aktywne.
