### ISSUE TITLE
Podzielona płatność (split payment) brak wyboru metody płatności

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2612]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Proszę o umożliwienie wyboru metody płatności na sandboxie tak jak to jest możliwe na produkcji. Celem przetestowania scenariusza w którym Klient wybiera płatność podzieloną i dowolną inną dla towaru o cenie >15 tys.
Poniżej różnica między sandboxem, a produkcją dla towaru o cenie >15tys.

![Przechwytywanie](https://user-images.githubusercontent.com/8465007/70530980-4c540900-1b54-11ea-86bb-d4cdbca29870.PNG)

**Comment by PatrykBocian** [comment]
Przekazałem już to do odpowiedniego zespołu w ramach [#2611](https://github.com/allegro/allegro-api/issues/2611)

**Comment by PatrykBocian** [comment]
Problem został rozwiązany, wszystko działa już poprawnie.

**Comment by alekskuc** [comment]
Dzień dobry, po wybraniu dodatkowo chęci zakupu allegro smart, znika początkowo dostępna opcja płatności podzielonej.

![image](https://user-images.githubusercontent.com/8465007/70700762-8693e680-1ccb-11ea-9786-b1215527299f.png)

**Comment by PatrykBocian** [comment]
Jest to prawidłowe zachowanie serwisu. Split payment nie jest dostępny przy kupnie SMART! - informujemy o tym na dodanym przez Ciebie zrzucie.

**Comment by alekskuc** [comment]
Dzień dobry, faktycznie nie doczytałem drobnego druczku. Widzę, że też dla każdej dostawy z wykupionym już smartem nie ma opcji podzielonej płatności. W pierwszym odczuciu wyglądało na błąd, ale skoro to prawidłowe działanie, to ok. Dziękuję za weryfikację.
