### ISSUE TITLE
Produkt z momentu zakupu

### ISSUE THREAD

**Issue by Bober95** [allegro/allegro-api#2613]
Witam,

Czy jest możliwość odwzorowania funkcjonalności z strony https://allegro.pl/moje-allegro/sprzedaz/zamowienia w REST API
Chodzi mi konkretnie o to że gdy chcemy zobaczyć produkt to jest to wersja z momentu zakupu (w linku pojawia się "snapshot" a na stronie "Sprzedawca zmienił tę ofertę.")

**Comment by PatrykBocian** [comment]
Czy mógłbyś doprecyzować w jakim celu potrzebna jest ci ta funkcjonalność w REST API?

**Comment by Onixarts** [comment]
Również mamy kilka zapytań odnośnie dostępu do snapshota z poziomu naszego softu. Sprzedawcy weryfikują nieraz jakie gratisy były w momencie zakupu wyświetlone w ofercie i co się klientom należy. Bez dostępu do snapshota muszą przeglądać historię zmian w danej ofercie, lub przechodzić do zamówienia w serwisie i dopiero stamtąd obejrzeć snapa. A tak wystarczyło by wyświetlić konkretny snapshot oferty powiązany z zakupem.

**Comment by PatrykBocian** [comment]
Zgłosiłem tę sugestie do odpowiedniego zespołu.

**Comment by pgasidlo** [comment]
Podbijam. Czy są jakieś postępy aby gdzieś uzyskać wartość parametru snapshot dla konkretnego zakupu/aukcji?

**Comment by MaciejFrackowiak** [comment]
@pgasidlo Nie, dotychczas takie rozwiązanie nie zostało wdrożone.
