### ISSUE TITLE
Błąd "Nie możesz kupić tych ofert" po kliknięciu "Kup Teraz" 

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#2614]
Po kliknięciu  "Kup Teraz" w ofercie która posiada wystarczającą ilość przedmiotu przenosi na stronę z błędem "Nie możesz kupić tych ofert" i informacją "Wybrana liczba przedmiotów jest niedostępna."  Problem występuje na wszystkich ofertach na sandbox. Przykładowa aukcja z którą jest problem https://allegro.pl.allegrosandbox.pl/oferta/spodnica-top-secret-kolekcja-slim-6206375090

**Comment by PatrykBocian** [comment]
Sprawdziłem ten problem - na chwilę obecną wszystko działa prawidłowo.
