### ISSUE TITLE
Wypłaty i wpłaty PAYU

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#2615]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

:beetle: **Opis**
W jaki sposób w RestApi można pobrać informację o tym jakie wpłaty składają się na wypłatę  (np. Payu)? Do tej pory korzystaliśmy z metody doGetMyPayoutsDetails z WebApi, ale ma ona zostać wyłączona.

**Comment by PatrykBocian** [comment]
Udostępniamy zasób [GET/payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory), który zwraca wszystkie wykonane operacje w ramach Allegro Finanse. Dane możesz filtrować, w otrzymanej odpowiedzi nie znajdziesz jednak powiązania pomiędzy wpłatami a wypłatą.

Więcej informacji na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/charges/#1).
