### ISSUE TITLE
Dziennik zdarzeń i raty

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2616]
Na środowisku sandbox chciałem odzwierciedlić przypadek zakupu na raty aby sprawdzić jakie informacje przyjdą z API.
Wybrałem dwa scenariusze - wniosek został odrzucony oraz został zaakceptowany.
Niestety z **/order/events** nie przyszedł żaden event, dodatkowo w moich zakupach nie widnieje żadna informacja o tym, że chcę kupić dany przedmiot. Również stan na aukcji pozostał ten sam.
Czy to normalne zachowanie?

**Comment by PatrykBocian** [comment]
W takim przypadku dostaniesz odpowiednią informację, dopiero gdy wniosek kupującego zostanie pozytywnie rozpatrzony. W GET /order/events znajdziesz standardowe, kolejne statusy:  **BOUGHT**, **FILLED_IN**, **READY_FOR_PROCESSING**.
W sytuacji kiedy wniosek został odrzucony nie dochodzi do kupna, zatem nie emitujemy żadnych eventów.

**Comment by bacok** [comment]
Jeszcze zasymuluję taki przypadek:
Mam aukcję na której są dwie sztuki - kupuję jedną i wybieram raty. Zakładam, że wniosek nie jest rozpatrywany natychmiastowo, więc co w przypadku gdy będzie on rozpatrywany, a inna osoba kupi dwie sztuki i je opłaci a w międzyczasie wniosek przejdzie walidację?
Czy wnioski ratalne są rozpatrywane natychmiastowo?

**Comment by PatrykBocian** [comment]
W przypadku, gdy wniosek jest wstępnie rozpatrzony pozytywnie - system najpierw zweryfikuje czy przedmiot, którego dotyczy wniosek nadal jest dostępny.
Jeśli nie, kupujący otrzyma informację o negatywnym rozpatrzeniu wniosku z powodu braku dostępności towaru.

**Comment by bacok** [comment]
Dziękuję za odpowiedź.
