### ISSUE TITLE
Pobieranie publicznych danych o ofercie

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#2617]
Cześć, mam pytanie, czy zaplanowane na Q4 wprowadzenie w REST "Pobieranie publicznych danych o ofercie" dacie radę wprowadzić do końca miesiąca?

![image](https://user-images.githubusercontent.com/36500569/70612589-7dd9dc80-1c07-11ea-8e48-ba6de808221e.png)

**Comment by PatrykBocian** [comment]
Taki jest przewidywany i nadal aktualny termin, gdyby coś się zmieniło w tej kwestii, opublikujemy odpowiedni komunikat.
