### ISSUE TITLE
Błąd w wystawianiu oferty na sandboxie

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2618]
Witam,
po kliknięciu wystaw przedmiot na sandboxie następuje przekierowanie do logowania na produkcji 
![obraz](https://user-images.githubusercontent.com/36850550/70612977-2ee07700-1c08-11ea-9920-6c052437267f.png)

**Comment by PatrykBocian** [comment]
Obecnie obejściem tego problemu jest skorzystanie z tego linku: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie
