### ISSUE TITLE
Pobieranie access tokena raz działa a raz nie działa

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#2619]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W dniu dzisiejszym obserwujemy problem z pobieraniem access tokena:
https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...&redirect_uri=...

Czasem działa a czasem dostajemy błąd HTTP 400.

**Comment by PatrykBocian** [comment]
Widzę, że skontaktowałeś się z nami także mailowo. Z uwagi na wrażliwe dane, odpowiemy na zgłoszenie mailowe.

**Comment by PatrykBocian** [comment]
Widzę, że skontaktowałeś się z nami także mailowo. Z uwagi na wrażliwe dane, odpowiemy na zgłoszenie mailowe.

**Comment by PatrykBocian** [comment]
Widzę, że skontaktowałeś się z nami także mailowo. Z uwagi na wrażliwe dane, odpowiemy na zgłoszenie mailowe.
