### ISSUE TITLE
Nowe opisy - połowa roku

### ISSUE THREAD

**Issue by mwiercioch** [allegro/allegro-api#262]
Gdzieś w jednym z artykułów na blogu poświęconym nowym opisom, znalazłem informację że w połowie roku wszystkie aukcje muszą mieć już nowy opis. Chciałbym dopytać co stanie się w połowie roku(koniec czerwca?) z aukcjami które nie mają nowego opisu.

**Comment by PawelTaberski** [comment]
Takie oferty nie będą dostępne dla kupujących, konkretną datę podamy wkrótce. Harmonogram zmian znajdzie Pan tutaj: https://allegro.pl/dla-sprzedajacych/harmonogram-kiedy-wprowadzamy-nowe-zasady-w-ofertach-mGKad6kyyH6

**Comment by mwiercioch** [comment]
Bardzo mnie interesuje ta data. W harmonogramie jest napisane, że w czerwcu wszystkie oferty będą musiały być zgodne z nowym opisem. Kiedy to może być mniej więcej? Mam nadzieję że nie 01.06.2018

**Comment by PawelTaberski** [comment]
Na pewno podamy ją z wyprzedzeniem, najprawdopodobniej będzie to koniec czerwca. Proszę śledzić nasze aktualności, jak będziemy znali konkretną datę poinformujemy o tym.

**Comment by mwiercioch** [comment]
dzięki za pomoc
