### ISSUE TITLE
Błąd autoryzacji (401 Unauthorized)

### ISSUE THREAD

**Issue by PiotrHollex** [allegro/allegro-api#2620]
Dzień dobry
od kilku tygodni nie działa nam integracja sklepu shopgold z allegro. Problem pojawił się po aktualizacji sklepu, która wymusiła przejście na REST API. 
Po utworzeniu aplikacji na apps.developer.allegro.pl i wprowadzeniu danych do shopgold wystąpił błąd autoryzacji. Pomoc techniczna sklepu stwierdziła, że wszystko jest w porządku po stronie sklepu i wprowadzonych danych. Sklep jest przetestowany  na tysiącach stron.  Pomoc allegro także nie stwierdziła błędów po stronie allegro. 
Na podstawie dokumentacji napisałem własny skrypt do logowania się do allegro ale ponownie pojawił się błąd **Response status code: 401 Unauthorized**. 
Skopiowałem gotowy skrypt z internetu (sprawdzony i na 100 % działający wg autora) ale ponownie błąd „Response status code: 401 Unauthorized”. 
Mój login to **hollex1** bardzo proszę o sprawdzenie czy coś nie stało się jednak po stronie allegro.

Mój kod:

$providerSettings = [
    'ClientId' => 'XXXX', 
    'ClientSecret' => 'XXXX',    
    'RedirectUri' => 'XXXX', 
    'AuthorizationUri' => 'https://allegro.pl/auth/oauth/authorize',
    'TokenUri' => 'https://allegro.pl/auth/oauth/token'
  ];
    $code = $_GET['code'];				
    $headers = 'Authorization: Basic '. base64_encode($providerSettings['ClientId'] . ':' . 
    $providerSettings['ClientSecret']);				
    $curl = curl_init($providerSettings['TokenUri']); 
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_POST, true);
   curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);				 
   curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query([
					'grant_type' => 'authorization_code', 
					'code' => $code,					
					'redirect_uri' => $providerSettings['RedirectUri']
				]));			
				
	$wynik = ($wynik = curl_exec($curl)) === false ? false : json_decode($wynik);				
	$resultCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
	curl_close($curl);
 
	if ($wynik === false) 
	{					
		echo "Response status code: $resultCode";
		throw new Exception('Unrecognized error');
	} 
	else if (!empty($wynik->error)) 
	{					
		echo "Response status code: $resultCode<br>";
		throw new Exception($wynik->error . ' - ' . $wynik->error_description.
		'<br><br>Użyte dane:'.
		'<br>ClientId: '.$providerSettings['ClientId'].
		'<br>ClientSecret: '.$providerSettings['ClientSecret'].
		'<br>TokenUri: '.$providerSettings['TokenUri'].
		'<br>Headers: '.$headers.
		'<br>Code: '.$code.
		'<br>RedirectUri: '.$providerSettings['RedirectUri']);
	} 

Dziękuje i pozdrawiam.

**Comment by PatrykBocian** [comment]
Widzę, że skontaktowałeś się z nami także mailowo. Z uwagi na wrażliwe dane, odpowiemy na zgłoszenie mailowe.

**Comment by PatrykBocian** [comment]
Nic się nie działo po stronie Allegro - nie mamy żadnych problemów z autoryzacją, żaden inny użytkownik nie zgłaszał nam takiej kwestii.
Trudno nam się odnieść do kwestii skryptu - jak sam przyznajesz skopiowałeś go z Internetu, dokonałeś własnych zmian - tu niewiele możemy, a ze względu na dużą ilość języków programowania, nie prowadzimy wsparcia z każdego z nich.
Może któryś z użytkowników forum będzie w stanie ci pomóc.

**Comment by DarkStoorM** [comment]
Twój kod działa u mnie prawidłowo, możesz sprawdzić czy na pewno ClientId i ClientSecret się zgadza? Tylko przy tych polach zwraca mi 401

**Comment by PiotrHollex** [comment]
Dziękuje za sprawdzenie.
ClientId i ClientSecret są prawidłowe (skopiowane z 
apps.developer.allegro.pl), wieczorem sprawdzę jeszcze logowanie z 
innego komputera z innej lokalizacji.
Czy możliwe, że adres IP strony sklepu lub mojego komputera został 
zablokowany?

W dniu 2019-12-12 14:37, Bartosz Sieprawski napisał(a):

**Comment by DarkStoorM** [comment]
W innym wątku znalazłem jeszcze takie info, lecz dotyczyło troszkę innego błędu:
https://github.com/allegro/allegro-api/issues/2500#issuecomment-552765954

Nie jestem pewien, możliwe że chodzi o adres

**Comment by PiotrHollex** [comment]
Według firmy hostingowej adresy są z puli publicznej. Zrobiłem test z innego adresu (innej domeny) dodając nową aplikacje (na apps.developer.allegro.pl) z nowym adresem powrotu ale także ten sam błąd.

**Comment by PiotrHollex** [comment]
@PatrykBocian 
Nie chodzi tylko o skrypt z internetu ale także o kod napisany przeze mnie i o sklep shopgold, który działa na wielu stronach poprawnie z allegro. Użytkownik **DarkStoorM** potwierdza, że mój kod działa z jego danymi a nie działa z danymi mojego konta. Dane na 100% są prawidłowe.  Logowanie z innych adresów IP i innych lokalizacji także nic nie zmienia.

**Comment by PatrykBocian** [comment]
@PiotrHollex Nie ma żadnych podstaw by Twój IP był blokowany. Co więcej, korzystasz z klucza do pobierania danych przez powiązane aplikacje. Proszę podeślij nam swój request i response wraz trace-id (nie usuwaj żadnych danych), które otrzymujesz podczas wywołania. Trudno nam się odnieść bezpośrednio do działania aplikacji, które nie są naszego autorstwa. Dane możesz przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), dopisz wtedy w zgłoszeniu **#2620**.

**Comment by PiotrHollex** [comment]
Problem rozwiązany. Kod, który przesłałem powyżej działał na niektórych serwerach a na niektórych pojawiał się błąd autoryzacji. Dopisanie dodatkowego nagłówka **'Content-Type: application/x-www-form-urlencoded'**  rozwiązało problem ale tylko w php 5.5. W php 7.1 oraz 7.2 spowodowało to inny błąd: **"invalid_request - An authorization code must be supplied"**. Mimo, że zmienna code była przesyłana w postfields. Problem rozwiązało przesłanie w postfields zwykłego stringa. 
Poniżej kod, który działa na naszych serwerach z php 7:

$providerSettings = [
    'ClientId' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'ClientSecret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',    
    'RedirectUri' => 'https://xxxxxxxxx', 
    'AuthorizationUri' => 'https://allegro.pl/auth/oauth/authorize',
    'TokenUri' => 'https://allegro.pl/auth/oauth/token'
  ];
$headers = ['Content-Type: application/x-www-form-urlencoded',
'Authorization: Basic '.base64_encode($providerSettings['ClientId'].':'.$providerSettings['ClientSecret'])];
							
$curl = curl_init($providerSettings['TokenUri']); 
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);						
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);							
curl_setopt($curl, CURLOPT_POSTFIELDS, 'grant_type=authorization_code&code='.$code.'&redirect_uri='.$providerSettings['RedirectUri']);
				
				
$wynik = ($wynik = curl_exec($curl)) === false ? false : json_decode($wynik); 
$wynik = ($wynik = curl_exec($curl)) === false ? false : json_decode($wynik);	
curl_close($curl);
 
if ($wynik === false) 
{					
    throw new Exception('Unrecognized error');
} 
else if (!empty($wynik->error)) 
{	
    throw new Exception($wynik->error . ' - ' . $wynik->error_description.
}

**Comment by PatrykBocian** [comment]
@PiotrHollex Świetnie, że udało Ci się rozwiązać ten problem. Dziękujemy też, że pokazałeś rozwiązanie na forum - pomoże to innym użytkownikom gdyby mieli podobny problem.
