### ISSUE TITLE
Problemy z  get /sale/offers

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2621]
W formularzu przesyłam request/response get/sale/offers z 
sold:0 mimo, że przedmiot się sprzedał.

**Comment by PatrykBocian** [comment]
Czy wysłałeś już przez formularz request/response, o którym wspomniałeś? Jeśli tak, to gdy tylko do nas dotrze odpowiedź zamieścimy w poście.

**Comment by lukada4100** [comment]
Wysłałem drugi raz, ale coś chyba nie dochodzi, bo nawet automatycznego potwierdzenia nie dostałem. Tu masz to jeszcze raz.
[sprzedana_oferta.txt](https://github.com/allegro/allegro-api/files/3954956/sprzedana_oferta.txt)

**Comment by PatrykBocian** [comment]
Zweryfikowałem twój problem, rzeczywiście występuje taki błąd. Zgłosiłem to do odpowiedniego zespołu.

**Comment by lukada4100** [comment]
problem jest częstszy. Ta sama sytuacja dotyczy:
8744992548
8742185617

**Comment by PatrykBocian** [comment]
Dopisałem to do poprzedniego zgłoszenia.
