### ISSUE TITLE
Błąd autoryzacji (401 Unauthorized) 

### ISSUE THREAD

**Issue by PiotrHollex** [allegro/allegro-api#2622]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od kilku tygodni nie jesteśmy w stanie zalogować się do allegro. 
**Response status code: 401 Unauthorized**
Pełny kod prześlę w formularzu kontaktowym.

$providerSettings = [
'ClientId' => 'XXXX',
'ClientSecret' => 'XXXX',
'RedirectUri' => 'XXXX',
'AuthorizationUri' => 'https://allegro.pl/auth/oauth/authorize',
'TokenUri' => 'https://allegro.pl/auth/oauth/token'
];
$code = $_GET['code'];
$headers = 'Authorization: Basic '. base64_encode($providerSettings['ClientId'] . ':' .
$providerSettings['ClientSecret']);
$curl = curl_init($providerSettings['TokenUri']);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query([
'grant_type' => 'authorization_code',
'code' => $code,
'redirect_uri' => $providerSettings['RedirectUri']
]));

$wynik = ($wynik = curl_exec($curl)) === false ? false : json_decode($wynik);				
$resultCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
curl_close($curl);

if ($wynik === false) 
{					
	echo "Response status code: $resultCode";
	throw new Exception('Unrecognized error');
} 
else if (!empty($wynik->error)) 
{					
	echo "Response status code: $resultCode<br>";
	throw new Exception($wynik->error . ' - ' . $wynik->error_description);
}

**Comment by PatrykBocian** [comment]
Prosimy nie dublować wątków. Odpowiemy w [#2620](https://github.com/allegro/allegro-api/issues/2620).
