### ISSUE TITLE
Synchronizacja API

### ISSUE THREAD

**Issue by aleksandersowiak** [allegro/allegro-api#2623]
Dzień dobry.

Planuję stworzyć regularną synchronizację mojego API z Państwa
1.	Po pierwszym logowaniu przez użytkownika uzyskać access_token, oraz refresh_token
2.	Później za pomocą refresh_token utrzymywać synchronizację, tj. odświeżanie tokena co 5 godzin.
3.	Dodatkowo co najmniej raz dziennie przeprowadzać synchronizację ogłoszeń z Allegro

Chciałbym uzyskać potwierdzenie, że jest to poprawne rozwiązanie z punktu widzenia Allegro.

**Comment by PatrykBocian** [comment]
Nie będzie problemów z rzeczami o których piszesz - musisz jedynie pamiętać o:

- W REST API mamy nałożony limit 9000 zapytań na minutę - jeśli go nie przekroczysz wszystko będzie w porządku.
- Dla niektórych zasobów wykorzystujemy dodatkowy algorytm algorytm Leaky Bucket. Gdy użytkownik przekroczy dozwoloną liczbę wywołań na minutę (RPM), wydłużamy czas odpowiedzi. W przypadku zbyt dużej liczby równoległych zapytań w imieniu tego samego użytkownika serwer odpowie błędem HTTP: 429 Too Many Requests.
- Access Token jest ważny 12 godzin.
- Refresh token pozwala na uzyskanie nowego tokena dostępowego dla danego użytkownika w sposób dla użytkownika przezroczysty (bez konieczności ingerencji z jego strony). Token taki jest jednorazowego użytku, a po jego użyciu wygenerowany zostaje nowy token dostępowy (ważny kolejne 12h) i nowy refresh token.

I na sam koniec - Twoje działania muszą pozostawać w zgodzie z [Regulaminem REST API](https://developer.allegro.pl/rules/).
