### ISSUE TITLE
Dziwny błąd walidacji blokujący zapis przy dodawaniu/edycji szkicu oferty w kategorii Alkomaty

### ISSUE THREAD

**Issue by Qenozis** [allegro/allegro-api#2625]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
* Zasób: PUT /sale/offers/{offerId}
Przy próbie dodania lub edycji szkicu aukcji w kategorii "Alkomaty" (zarówno w dziale Motoryzacja jak i Elektronika), za każdym razem po wysłaniu danych formularza poprzez PUT, nawet tych samych co otrzymuję przez GET, w polu z błędami walidacji pojawia się dziwny komunikat błędu:

            [code] => ERROR
            [message] => An error has occurred
            [details] => 
            [path] => /sale/offers/{tutaj-numer-oferty}
            [userMessage] => 

Niezależnie od tego, czy dokonam jakichkolwiek zmian na formularzu oferty czy nie, przy próbie wysłania do zapisu na Allegro - ten błąd występuje.
Ten dziwny błąd występuje tylko na szkicach w kategoriach "Alkomaty", w innych kategoriach problemu nie stwierdzono.

Zmiana kategorii z "Alkomaty" na jakąkolwiek inną i wysłanie formularza w PUT powoduje poprawne zapisanie się wszystkich danych na Allegro bez żadnego komunikatu błędu. Ponowna zmiana kategorii na "Alkomaty" powoduje wystąpienie w/w błędu i brak zapisu wysyłanych danych na Allegro.
Wypełnienie wszystkich pól formularza dla kategorii "Alkomaty", nawet tych niewymaganych, nie pomaga. Występowanie błędu zauważyliśmy od dnia wczorajszego. Edycja szkicu w kategorii "Alkomaty" bezpośrednio na Allegro odbywa się bez problemu, co najprawdopodobniej wskazuje na problem z walidatorem tylko po stronie RestAPI.

Podsumowując: edycja jakichkolwiek ofert czy szkiców w innych kategoriach niż "Alkomaty", poprzez wspomniany wyżej zasób w RestAPI, odbywa się bez najmniejszych problemów. Problem wykryto tylko w kategoriach "Alkomaty" i napotykamy go od dnia wczorajszego.

**Comment by PatrykBocian** [comment]
Prześlij proszę pełen request - pomoże to zweryfikować zgłoszenie - sam nie napotkałem na żaden problem.

**Comment by Qenozis** [comment]
Przeanalizowałem raz jeszcze wysyłane dane w request i w końcu zauważyłem, że dla parametru z zakresem wartości przypadkiem usuwało mi się pole z 'ID' tego parametru. Najwyraźniej API nie jest przygotowane na otrzymanie wartości parametru bez pola 'ID' parametru i wówczas wyrzuca z siebie taki dziwny komunikat błędu.
Bug z mojej strony został usunięty i już problemu nie ma, więc zamykam.
