### ISSUE TITLE
Jak zamienić odpowiedź serwera na czytelny dla ludzi format?

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#2626]
Jak zamienić długiego, jednolinijkowego stringa, którego zwraca serwer na stringa, którą da się czytać w np. notatniku?
Konwertery json, które znalazłem nie umieją parsować Waszego stringa do czytelnej dla człowieka postaci.

**Comment by PatrykBocian** [comment]
Jeśli występuje u Ciebie problem z którymś response - prześlij go proszę wraz z trace.id, przyjrzymy się temu. Przesyłamy dane w formacie JSON, inni użytkownicy nie zgłaszali podobnych problemów.

**Comment by BartekWroclaw** [comment]
> Jeśli występuje u Ciebie problem z którymś response - prześlij go proszę wraz z trace.id, przyjrzymy się temu. Przesyłamy dane w formacie JSON, inni użytkownicy nie zgłaszali podobnych problemów.

Tu nie chodzi o to, że jest problem z response. Nie ma. Chodzi o to, że reposnse jest w jednej linijce;
{ "latestEvent": { "id": "1532603898317497", -- identyfikator najnowszego zdarzenia "occurredAt": "2018-07-26T11:18:06.715Z" -- data wystąpienia tego zdarzenia } }
a chciałbym czytać response jako strukturę wielolinijkową, 
np. {
    "latestEvent": {
        "id": "1532603898317497",                 -- identyfikator najnowszego zdarzenia
        "occurredAt": "2018-07-26T11:18:06.715Z"  -- data wystąpienia tego zdarzenia
    }
}

**Comment by hmkdbsw** [comment]
> 
> 
> > Jeśli występuje u Ciebie problem z którymś response - prześlij go proszę wraz z trace.id, przyjrzymy się temu. Przesyłamy dane w formacie JSON, inni użytkownicy nie zgłaszali podobnych problemów.
> 
> Tu nie chodzi o to, że jest problem z response. Nie ma. Chodzi o to, że reposnse jest w jednej linijce;
> { "latestEvent": { "id": "1532603898317497", -- identyfikator najnowszego zdarzenia "occurredAt": "2018-07-26T11:18:06.715Z" -- data wystąpienia tego zdarzenia } }
> a chciałbym czytać response jako strukturę wielolinijkową,
> np. {
> "latestEvent": {
> "id": "1532603898317497", -- identyfikator najnowszego zdarzenia
> "occurredAt": "2018-07-26T11:18:06.715Z" -- data wystąpienia tego zdarzenia
> }
> }

https://jsonformatter.curiousconcept.com/

**Comment by BartekWroclaw** [comment]
> > > Jeśli występuje u Ciebie problem z którymś response - prześlij go proszę wraz z trace.id, przyjrzymy się temu. Przesyłamy dane w formacie JSON, inni użytkownicy nie zgłaszali podobnych problemów.
> > 
> > 
> > Tu nie chodzi o to, że jest problem z response. Nie ma. Chodzi o to, że reposnse jest w jednej linijce;
> > { "latestEvent": { "id": "1532603898317497", -- identyfikator najnowszego zdarzenia "occurredAt": "2018-07-26T11:18:06.715Z" -- data wystąpienia tego zdarzenia } }
> > a chciałbym czytać response jako strukturę wielolinijkową,
> > np. {
> > "latestEvent": {
> > "id": "1532603898317497", -- identyfikator najnowszego zdarzenia
> > "occurredAt": "2018-07-26T11:18:06.715Z" -- data wystąpienia tego zdarzenia
> > }
> > }
> 
> https://jsonformatter.curiousconcept.com/

a znasz coś działającego ale lokalnie a nie na czyjejś stronie www?

**Comment by BartekWroclaw** [comment]
Znalazłem wtyczkę do notepad++. Temat rozwiązany.
