### ISSUE TITLE
Dostęp do interfejsu API nie powiódł się

### ISSUE THREAD

**Issue by 1196127223** [allegro/allegro-api#2627]
Występuje problem: 
 - [ √] z zasobem REST API
 - [ √] ze środowiskiem produkcyjnym
![P7Z@%$@E{ZHMVWF1XNQ3Q_G](https://user-images.githubusercontent.com/50816024/70767052-bc53d080-1d9a-11ea-945a-bd20325bfea3.png)
![LZ9H~{C`8FO4XX7 I}32GTV](https://user-images.githubusercontent.com/50816024/70767107-ee653280-1d9a-11ea-9373-75e500856623.png)

Próbowałem uzyskać dostęp do interfejsu API.
Ale niestety nie był tak skuteczny jak inne interfejsy API.
Wypróbowałem dowolną metodę, jaką mogę wypróbować.
Teraz potrzebuję pomocy

**Comment by martacronic** [comment]
Wydaje mi się, że chciałeś pobrać informację o aukcji, a korzystasz z metody dla produktów. Spróbuj zasobu [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)

**Comment by PatrykBocian** [comment]
Błąd powoduje nieprawidłowe użycie zasobu - przesyłasz numer oferty zamiast productId. Zweryfikuj proszę poprawne id produktu. Jeżeli chcesz pobrać szczegóły danej oferty skorzystaj z zasobu [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), gdzie jako offerId podajesz identyfikator oferty - w Twoim przypadku **8676958244**.
Dodatkowe informacje o produktach znajdziesz w naszym [poradniku](https://developer.allegro.pl/productization/).

**Comment by 1196127223** [comment]
> 错误导致资源使用不正确-您正在提交商品编号而不是productId。请验证正确的产品ID。如果要下载给定报价的详细信息，请使用[GET / sale / offices / {offerId}资源](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)，其中在offerId中输入要约ID（在本例中为**8676958244）**。
> 其他产品信息可在我们的[指南中](https://developer.allegro.pl/productization/)找到。

![image](https://user-images.githubusercontent.com/50816024/70785702-fc7c7880-1dc5-11ea-9714-97483c6b5b12.png)
Próbuję używać https://api.allegro.pl/sale/offers/{offerId}.Ale productId jest pusty.
Jak więc ten productId powinien zostać wygenerowany

**Comment by PatrykBocian** [comment]
@1196127223  W tym przypadku dostajesz wartość “**null**”, ponieważ ta oferta **nie jest powiązana z produktem**. Aby **product.id** był tam widoczny musisz powiązać ofertę z produktem.
Informacje jak to zrobić znajdziesz w naszym [poradniku](https://developer.allegro.pl/en/productization/#important).
