### ISSUE TITLE
Użycie więcej niż jednego filtra publication.status wywołuje błąd

### ISSUE THREAD

**Issue by hmkdbsw** [allegro/allegro-api#2628]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Wykonuje takie zapytanie: `sale/offers?limit=1&publication.status=ACTIVE&publication.status=ENDED&publication.status=ACTIVATING`
Dzisiaj przestało ono funkcjonować i wyrzuca status code BadRequest. metodą prób i błędów wyszło, że mając więcej niż jeden publication.status otrzymuje się ten błąd. dlaczego tak jest? to błąd po waszej stronie? czy nieudokumentowana zmiana w API?

**Comment by PatrykBocian** [comment]
Zweryfikowałem ten problem - zgłosiłem to już do odpowiedniego zespołu.
