### ISSUE TITLE
Klucz WebApi

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2629]
Czy jest jeszcze mozliwosc wygenerowania klucza WEBAPI dla konta?
Strona podana w dokumentacji http://allegro.pl/myaccount/webapi.php/generateNewKey
przekierowuje na https://apps.developer.allegro.pl/,
a ja potrzebuje dostep do starego poczciwego WEBAPI, nie chce tworzyc nowej aplikacji.

**Comment by PatrykBocian** [comment]
Możesz wykorzystać klucz wygenerowany przy REST API. informacje na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/webapi/).

**Comment by anaxagore78** [comment]
Zapytanie tu na forum  było ostatecznością, 

próbowałem na różne sposoby, dla innych kont z powodzeniem korzystam z metody doLoginWithAccessToken, 
ale dla nowego konta (ma moze 1 miesiac) nie znam WebApiKey, parametru wymaganego w metodzie doLoginWithAccessToken, 
Dla tego konta konczy sie to komunikatem:
"Niepoprawna wartość klucza WebAPI lub klucz został zablokowany."

> Możesz wykorzystać klucz wygenerowany przy REST API. 
gdzie go znajde?

**Comment by PatrykBocian** [comment]
Informację na ten temat znajdziesz w [poradniku ](https://allegro.pl/webapi/general.php#keys)- jako klucz wystarczy, że podasz ClientId.

**Comment by anaxagore78** [comment]
Super, dziekuje, gdzies mi to umknęło.
