### ISSUE TITLE
Service access has been blocked - więcej informacji

### ISSUE THREAD

**Issue by dfranczuk** [allegro/allegro-api#263]
Dzień dobry,
Przy próbie komunikacji z allegro API dostaję komunikat: 

> Service access has been blocked - invocation limit for this ip address has been exceeded

Z pewnością nie przekroczyłem limitu połączeń.
Czy jest możliwość uzyskania informacji co konkretnie było przyczyną zbanowania, tak bym mógł naprawić błąd?

**Comment by PawelTaberski** [comment]
Musiałeś przekroczyć ilość zapytań na sekundę dla danego adresu ip, więcej na ten temat (również jak zdjąć taką blokadę) znajdziesz [tutaj](https://allegro.pl/webapi/faq.php#faq_1).

**Comment by PawelTaberski** [comment]
Tak jak w załączonym artykule są osobne limity na adresy IP i na klucze.
