### ISSUE TITLE
Checkoutform payment provider

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#2631]
W jakiej sytuacji to pole będzie ustawione na: "OFFLINE"?

**Comment by PrzemyslawLukanowski** [comment]
Wartość OFFLINE w polu payment.provider dla [GET order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) otrzymasz w przypadku podzielonej płatności (SPLIT_PAYMENT).
