### ISSUE TITLE
Jak długo utrzymują się zdjęcia na serwerze i jak to sprawdzić?

### ISSUE THREAD

**Issue by Hopenberg** [allegro/allegro-api#2633]
Szukałem w dokumentacji i innych issue's, ale nie znalazłem odpowiedzi. Czy jest możliwość sprawdzenia informacji o zdjęciu (głównie daty wygaśnięcia) znajdującym się już na serwerze allegro? Czy przy wznawianiu aukcji, w nowej ofercie można wykorzystać adresy zdjęć z poprzedniej bez ponownego uploadowania zdjęć?

**Comment by PatrykBocian** [comment]
Co do twoich pytań:

- Czas ważności będzie widoczny przy uploadzie zdjęcia, tzw. TTL wynosi 6 godzin - w tym czasie musisz dodać zdjęcie do draftu,
- Możesz wykorzystać później adresy zdjęć z wcześniejszych ofert - dopóki oferta jest aktywna lub od jej zakończenia nie upłynęło 60 dni takie zdjęcie jest dostępne do wykorzystania.

**Comment by Hopenberg** [comment]
To znaczy że czas ważności mogę zdobyć tylko na początku, przy uploadzie zdjęcia?

**Comment by PatrykBocian** [comment]
Tak, dostajesz taką informację w polu “**expiredAt**”. Dla zdjęć w ofertach, które pojawiły się w serwisie taki czas możesz wyznaczyć tylko na podstawie daty zakończenia oferty + 60 dni.
