### ISSUE TITLE
Czy jest możliwa zmiana ceny w aukcji z licytacja poprzez API ?

### ISSUE THREAD

**Issue by HMX24** [allegro/allegro-api#2634]
Czy jest możliwa zmiana ceny w aukcji z licytacja poprzez API ?

**Comment by PatrykBocian** [comment]
Cenę początkową zmienisz za pomocą [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) - pole **startingPrice.amount**. Nie wykonasz tego, jeżeli w licytacji znajduje się już jakaś oferta kupna. W przypadku licytacji nie zadziała zasób [PUT /offers/{offerId}/change-price-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createChangePriceCommandUsingPUT), ponieważ dotyczy zmiany cen tylko dla ofert typu “Kup teraz”.
