### ISSUE TITLE
Authorization link shows not found page

### ISSUE THREAD

**Issue by 2gracia** [allegro/allegro-api#2635]
I have tried to get authorization code and open link and i see the page : 
![Screenshot_5](https://user-images.githubusercontent.com/16926731/70884578-088f5280-1fdf-11ea-9cad-22579cd3ba7f.png)

**Comment by PatrykBocian** [comment]
Please check your **redirect_uri** - you must send the same **redirect_uri** in request which you added in [Developer Apps](https://apps.developer.allegro.pl/).

**Comment by 2gracia** [comment]
> Please check your **redirect_uri** - you must send the same **redirect_uri** in request which you added in [Developer Apps](https://apps.developer.allegro.pl/).

Thanks, I checked it, it is same. I purpose that i

**Comment by PatrykBocian** [comment]
Please check it again - I checked this and I don’t see the same redirect_uri as in your [Developer Apps](https://apps.developer.allegro.pl/).

**Comment by DarkStoorM** [comment]
Can you make sure your Client ID is correct? Also, does ~/api/categories.php handle your authorization?

**Comment by 2gracia** [comment]
> Please check it again - I checked this and I don’t see the same redirect_uri as in your [Developer Apps](https://apps.developer.allegro.pl/) - And there is no need to used **https**.

Yes I chacke it, and there was www. I remove and it work. Thanks.
