### ISSUE TITLE
Brak opcji "płatność przy odbiorze" na sandbox?

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#2636]
Witam,

Na koncie użytkownika "alpallegro" dodałem cennik ustaw o nazwie "Kurier paczka", który ma zaznaczone opcje: "Przesyłka kurierska -> opłata z góry" oraz "Przesyłka kurierska -> opłata przy odbiorze". Gdy próbuję kupić jakiś wystawiony przedmiot np. oferta id: 6206776031, to mimo iż w aukcji widnieje opcja przesyłki "Przesyłka kurierska" to w dalszych krokach zamówienia, nie mogę wybrać "opłaty przy odbiorze", mam do wyboru tylko przelewy błyskawiczne np. PayU. Chciałbym natomiast przetestować pobranie informacji przez REST API o zamówieniu opłacanym za pobraniem.

Nie jestem pewien czy jest to błąd na sandbox czy ja coś źle ustawiłem?

**Comment by PrzemyslawLukanowski** [comment]
Do oferty 6206776031 przypisałeś cennik dostawy "Kurier paleta", gdzie jedyna metodą dostawy jest przesyłka kurierska (bez pobrania). Zweryfikuj, czy w przypadku innych ofert również nie nastąpiła podobna sytuacja. Jeśli zauważysz rozbieżność, przekaż nam proszę numery ofert.

**Comment by AlpanetPL** [comment]
Racja. Nie zauważyłem. Dziękuję i przepraszam za kłopot.
