### ISSUE TITLE
Bakujące uid-y REST API dla metod dostaw występujących w WebAPI

### ISSUE THREAD

**Issue by MichalGrzybowski** [allegro/allegro-api#2637]
Potrzebuję wykonać mapowanie produkcyjnych metod dostaw z WebAPI na REST API. Mam problem z trzema dostawami, które są w WebAPI, a nie ma ich w REST API ( sale/delivery-methods ). 

100 - X-press Couriers
101 - X-press Couriers pobranie
10005 - DHL SERVICE POINT

W jaki sposób uzyskać uid-y REST API dla tych trzech metod dostawy ?

**Comment by PrzemyslawLukanowski** [comment]
Kurier X-press Couriers dostępny jest obecnie tylko dla wybranych sprzedawców, dlatego prawdopodobnie nie widzisz tych wyników w GET /sale/delivery-methods. Poniżej przesyłam uuidy:

- Kurier X-press - 04b07522-70e5-4dc3-b13b-7918ea717539,
- Kurier X-press pobranie - 17535ba6-077b-4371-ab4c-7918ea717539.

Metoda dostawy DHL SERVICE POINT nie jest już dostępna, dlatego też nie zwracamy jej w REST API.

**Comment by MichalGrzybowski** [comment]
Super. Dziękuję za pomoc.
