### ISSUE TITLE
Ustawianie lokalizacji oferty

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#2641]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy tworzeniu draftu oferty oraz aktualizacji wysyłam obiekt Location w następującej postaci:
![image](https://user-images.githubusercontent.com/43290585/70984086-27164c00-20ba-11ea-92ab-c764c82d983e.png)

W odpowiedzi dostaje 200, jednak obiekt location wraca jako null:
![image](https://user-images.githubusercontent.com/43290585/70984065-1960c680-20ba-11ea-89d7-296d614b4c47.png)

W tablicy _validation_ nie otrzymuje informacji o tym, że brakuje danych na temat lokalizacji. W panelu Allegro dane lokalizacyjne są widoczne. Nie wracają jedynie po wystawieniu oferty przez co moje wewnętrzne testy integracyjne nie przechodzą.

**Comment by PrzemyslawLukanowski** [comment]
Aby obiekt location dodał się prawidłowo, wcześniej musisz określić format sprzedaży (sellingMode) oraz przypisać do oferty cennik dostawy (delivery.shippingRates).

**Comment by Bodzix** [comment]
Dziwna sprawa, przyznam szczerze. 
Jeżeli tak jest, powinno być to opisane w dokumentacji a w tablicy validation powinna również znaleźć się taka informacja. @PrzemyslawLukanowski, nie uważasz ? Koniec końców, dane o lokalizacji zostały zapisane w ofercie.

**Comment by PrzemyslawLukanowski** [comment]
Dzięki za spostrzeżenie, w najbliższym czasie uzupełnimy nasz poradnik o taką informację. Co do tablicy validation - w przypadku kiedy nie przypiszesz cennika dostawy, otrzymasz odpowiedni komunikat ("You have to provide shipping rates and offer's location."), podobnie dla obiektu sellingMode ("You must select at least one selling mode and provide the required prices.").
