### ISSUE TITLE
Przekierowanie na produkcyjny portal po kliknięciu wystaw przedmiot

### ISSUE THREAD

**Issue by szyzak** [allegro/allegro-api#2642]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Kliknięcie na `Wystaw przedmiot` przekierowuje na https://allegrolokalnie.pl/oferty/wystaw.
Kliknięcie `Wystaw przedmiot na WOŚP` poprawnie kieruje na adres sandboxowy https://allegro.pl.allegrosandbox.pl/charityOffer/

**Comment by PatrykBocian** [comment]
Zgłosiłem już to do odpowiedniego zespołu - tymczasowym obejściem tego problemu, jest skorzystanie z linku: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie
