### ISSUE TITLE
Błędne obliczanie kosztów dostawy

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#2643]
Moje konto Client:43974801 w ustawieniach dostawy mam wybraną opcję "Przesyłki będą nadane osobno, a koszty dostawy zsumują się." . Mimo takiego ustawienia po dodaniu kilku produktów do koszyka z różnymi formami dostawy zamiast zsumowania dostaw mam opcję "INNE METODY DOSTAWY"
Dostawa i jej koszt ustalane ze sprzedającym

Przy okazji mam prośbę o aktywowanie przelewy24 na koncie Client:43974801

**Comment by kfijalko** [comment]
Sprawdź czy w cennikach są wspólne metody dostawy.
Jeżeli oferty nie mają wspólnej metody dostawy to wyświetla się "koszt ustalany ze sprzedającym".

**Comment by michalpokora** [comment]
Nie mają wspólnej metody dostawy ale nie wydaje mi się, żeby wyświetlanie w tej sytuacji "koszt ustalany ze sprzedającym" było poprawnym zachowanie. Każdy z przedmiotów ma swoją formę dostawy. Załóżmy, że wysyłany jest z innego magazynu. Jeden na palecie, jeden listem i jeden paczkomatem. Dlaczego jako kupujący miałbym ustalać coś ze sprzedającym skoro znam warunki dostawy bo podane są w każdej ofercie.

**Comment by PrzemyslawLukanowski** [comment]
To prawidłowe zachowanie - jest tak jak napisał @kfijalko, cenniki w ofertach muszą mieć wspólną metodę dostawy. Więcej na ten temat przeczytasz w [naszym artykule](https://allegro.pl/pomoc/dla-sprzedajacych/cennik-dostawy/jak-ustawic-odpowiedni-sposob-laczenia-kosztow-dostawy-dla-ofert-z-roznymi-cennikami-4GDdXnx0LuW):

> Łączenie cenników nie zadziała, jeśli nie mają one żadnej wspólnej metody dostawy - wtedy Kupujący zawsze będzie miał możliwość wpisania kosztu dostawy ręcznie, bez względu na ustawienia. W tym przypadku Kupujący powinien wcześniej ustalić ten koszt z Tobą.
