### ISSUE TITLE
Zwroty

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2644]
Mam pytanie czy taki JSON zwrotu jest prawidłowy? Jeżeli nie, to czego brakuje?
{
	"payment": {
		"id": "a4da5120-20b2-11ea-8b32-0de4fbca541f"
	},
	"reason": "PRODUCT_NOT_AVAILABLE",
	"lineItems": [{
		"id": "92297743-20b2-11ea-a296-13f8931fc130",
		"type": "QUANTITY",
		"quantity": 1,
		"value": null
	}, {
		"id": "92297743-20b2-11ea-a296-13f8931fc130",
		"type": "QUANTITY",
		"quantity": 1,
		"value": null
	}, {
		"id": "92297743-20b2-11ea-a296-13f8931fc130",
		"type": "QUANTITY",
		"quantity": 1,
		"value": null
	}, {
		"id": "92297743-20b2-11ea-a296-13f8931fc130",
		"type": "QUANTITY",
		"quantity": 1,
		"value": null
	}],
	"delivery": {
		"value": {
			"amount": "12.24",
			"currency": "PLN"
		}
	},
	"overpaid": {
		"value": {
			"amount": "0",
			"currency": "PLN"
		}
	},
	"surcharges": null,
	"additionalServices": {
		"value": {
			"amount": "0",
			"currency": "PLN"
		}
	}
}

**Comment by PrzemyslawLukanowski** [comment]
W tablicy lineItems cztery razy przekazujesz ten sam lineItemId, co w efekcie wygeneruje zwrot tylko za jeden przedmiot. Jeżeli chcesz wykonać zwrot za cztery sztuki, wtedy struktura powinna wyglądać jak poniżej:

```
	"lineItems": [{
		"id": "92297743-20b2-11ea-a296-13f8931fc130",
		"type": "QUANTITY",
		"quantity": 4,
		"value": null
	}]
```

Poza tym JSON jest prawidłowy.
