### ISSUE TITLE
Pełne drzewko kategorii dla konkretnego produktu

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#2647]
Czy da się jakoś jednym requestem pobrać pełne drzewko kategorii dla konkretnego produktu? Z tego co widzę w docsach to musiałbym począwszy od id dla kategorii zwracanego przy zapytaniu od produkt odpytywać kolejno `/sale/categories/{categoryId}` idąc w górę drzewka aż do momentu gdy `parent === null`. Przy kilku tysiącach produktów jak trzeba dla każdego taką operację wykonać to wydaje sie dosyć intensywny proces.

**Comment by kfijalko** [comment]
Allegro wielokrotnie deklarowało, że ich architektura jest przygotowana pod dużą liczbę małych zapytań.
Sprawdź https://api.allegro.pl/offers/listing dla unikatowych "category.id" z limitem=1. W odpowiedzi masz pole categories.path - może to Ci wystarczy.
Inne rozwiązanie to pobranie całego drzewa kategorii "raz na jakiś czas" (a to robię codziennie w nocy). Wtedy masz pod ręką dane kategorii.
