### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by Blaaszkovsky** [allegro/allegro-api#2648]
Witam serdecznie,
prosiłbym o aktywację konta sandbox na mail: info@silnet.pl - minęły już dawno 3 dni, żadnej informacji, zgłaszałem również się na pomoc i zero odzewu. Może tutaj szybciej zadziałacie. 

Dzięki z góry! :)

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktywowałem Twoje konto. Z racji tego, że jest to konto firmowe, prześlij jeszcze dwa dowolne pliki przez zakładkę [dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php), aby dokończyć aktywację.

**Comment by Blaaszkovsky** [comment]
@PrzemyslawLukanowski dzięki za aktywację, przesłałem dwa obrazki, sprawdź proszę.

**Comment by PrzemyslawLukanowski** [comment]
Wszystko gra, konto aktywne.

**Comment by AssAssIn1909** [comment]
Można prosić o aktywacja konta klienta?
login: DDDStore

**Comment by MaciejFrackowiak** [comment]
@AssAssIn1909 Konto jest już aktywne.
