### ISSUE TITLE
Metoda doChangePriceItem zwraca błąd ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT (Podaj poprawną walutę)

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#265]
Metoda doChangePriceItem (https://allegro.pl/webapi/documentation.php/show/id,223#method-input) nie pozwala na zmianę ceny minimalnej (newReservePrice), podanie ceny minimalnej powoduje błąd

ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT (Podaj poprawną walutę)

Pozostałe ceny są zmieniane poprawnie.

**[Edit]**
Jeszcze tytułem uzupełnienia - błąd powstaje najwyraźniej w przypadku zmiany ceny minimalnej dla aukcji, przy tworzeniu których cena minimalna nie została podana. Dla aukcji z ceną minimalną jej zmiana przebiega prawidłowo.

Tak czy inaczej, nawet jeśli takie działanie metody doChangePriceItem jest zamierzone, to komunikat błędu jest dość niefortunny.

**Comment by PawelTaberski** [comment]
Tak jak w opisie oferty, metoda ta pozwala na "Metoda pozwala na zmianę cen dostępnych w ofercie bez złożonych ofert kupna..." 
Jeśli wystawiasz np. ofertę tylko w formacie kup teraz nie możesz do niej dodać ceny minimalnej. Tylko w licytacjach możesz dodawać taką cenę.
Dodatkowo pamiętaj, że tą metodą wyedytujesz tylko ofertę bez ofert kupna.

**Comment by k4pit4n** [comment]
Problem dotyczy oferty w **formacie samej licytacji (bez opcji Kup Teraz) i bez złożonych ofert kupna**. Błąd można powtórzyć w następujący sposób:

1. Wystawiam aukcję z ceną wywoławczą 10 zł i **bez ceny minimalnej** (czas trwania 10 dni).
2. Wywołuję metodę doChangePriceItem z podaniem nowej ceny minimalnej 12 zł.
3. Otrzymuję błąd ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT (Podaj poprawną walutę).

Natomiast w scenariuszu:

1. Wystawiam aukcję z ceną wywoławczą 10 zł i **z ceną minimalną 11 zł** (czas trwania 10 dni).
2. Wywołuję metodę doChangePriceItem z podaniem nowej ceny minimalnej 12 zł.

błąd nie występuje i cena minimalne zostaje prawidłowo zmieniona z 11zł na 12zł.

Powyższe dotyczy platformy testowej.

**Comment by MaciejPotepa** [comment]
Dzięki za opisanie problemu. Wygląda to na nieprawidłowe działanie metody. 
Podeślij proszę treść request i response w XML z pierwszego scenariusza, w którym otrzymujesz błąd ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT.

**Comment by k4pit4n** [comment]
Request poniżej, niestety nie potrafię tego sensownie sformatować:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoChangePriceItemRequest>
         <ser:sessionHandle>${#Project#sessionId}</ser:sessionHandle>
         <ser:itemId>${#Project#itemId}</ser:itemId>
         
         <ser:newStartingPrice>6</ser:newStartingPrice>
         
         <ser:newReservePrice>7</ser:newReservePrice>
      </ser:DoChangePriceItemRequest>
   </soapenv:Body>
</soapenv:Envelope>
`

A jako response otrzymuję:

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT</faultcode>
         <faultstring>Podaj poprawną walutę</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

**Comment by MaciejPotepa** [comment]
Wybacz długi czas oczekiwania na odpowiedź. 

Czy jesteś może w stanie dodatkowo podać numer oferty, w którym ten problem wystąpił? 
Pomoże nam to w rozwiązaniu tego problemu.

**Comment by k4pit4n** [comment]
Dla tamtej oferty błąd już nie występuje, bo cenę minimalną zmieniłem poprzez interfejs www i kolejne wywołania metody doChangePriceItem kończą się już sukcesem.

Ale sytuacja jest powtarzalna, więc stworzyłem nową ofertę bez ceny minimalnej o numerze **6204440689**:

Request

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoChangePriceItemRequest>
         <ser:sessionHandle>${#Project#sessionId}</ser:sessionHandle>
         <ser:itemId>6204440689</ser:itemId>
         
         <ser:newStartingPrice>66</ser:newStartingPrice>
         
         <ser:newReservePrice>77</ser:newReservePrice>
     </ser:DoChangePriceItemRequest>
   </soapenv:Body>
</soapenv:Envelope>`

Response

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_JSON_MAPPINGINCORRECT_PRICE_FORMAT</faultcode>
         <faultstring>Podaj poprawną walutę</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by MaciejPotepa** [comment]
Dzięki, sprawdzamy co jest nie tak.

**Comment by k4pit4n** [comment]
Właśnie sprawdziłem i już działa, dzięki :)
