### ISSUE TITLE
/order/checkout-forms/

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#2650]
W zasobie "/order/checkout-forms/" występuje lineItems[0]->originalPrice oraz lineItems[0]->price które w sprawdzonych przeze mnie przykładach jest sobie równe. W jakim celu podawane są te dwie wartości?
![1111](https://user-images.githubusercontent.com/40828332/71096811-4347e500-21af-11ea-8e40-47b5f646d2f2.png)

**Comment by PrzemyslawLukanowski** [comment]
originalPrice to pierwotna cena w ofercie, przed zastosowaniem jakichkolwiek zniżek (rabatów  ilościowych, zestawów itp.), z kolei price to cena w chwili zakupu, ktora uwzględnia ewentualne zniżki np. rabat ilościowy, zestawy, itp.). Te i inne informacje znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/).
