### ISSUE TITLE
sale/offers/{offerId} Forbidden Error

### ISSUE THREAD

**Issue by sj-abrams** [allegro/allegro-api#2651]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hello, 
First of all thanks for the quite nice and well documented REST API, it's pleasure to work with )

I'm trying to get offer details by using `sale/offers/{offerId}` and getting following error
```js
{ errors: [{ 
  code: 'FORBIDDEN',
  message: 'Forbidden',
  details: null,
  path: '/sale/offers/8499906068',
  userMessage: null 
}]}
```
*my request uses valid access token (I have access to other 'bearer-token-for-user' apis)

**Comment by PrzemyslawLukanowski** [comment]
You're not authorized as a seller, who is the owner of this offer - your id is 740...01 and the offer belongs to seller with id 458...56.

**Comment by sj-abrams** [comment]
@PrzemyslawLukanowski , thanks for the fast response, looks like I chose the wrong api (endpoint is private for each user/seller), but how can I get any public offer details then?

**Comment by PrzemyslawLukanowski** [comment]
Right now it's impossible. You can [search through offers](https://developer.allegro.pl/en/listing/) displayed on listings with [GET /offers/listing](https://developer.allegro.pl/documentation/#tag/Public-offer-information).

**Comment by sj-abrams** [comment]
@PrzemyslawLukanowski , now it's more clear thanks, I found the task about `Get public data about offers` on the [roadmap for Q4 2019](https://developer.allegro.pl/en/schedule/) , can we expect this functionality in the nearest feature?

**Comment by PrzemyslawLukanowski** [comment]
Yes. If anything gonna change in this case, we will publish appropriate message.
