### ISSUE TITLE
Sposoby zapłaty Rest Api

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#2652]
Klient wybiera formę zapłaty Płace przelewem tradycyjnym.
Czy w takiej sytuacji zdarzenie w polu type będzie miało status "READY_FOR_PROCESSING"?

**Comment by PrzemyslawLukanowski** [comment]
Zdarzenie otrzyma type FILLED_IN. READY_FOR_PROCESSING pojawi się, kiedy PayU/P24 rozliczy ją z Allegro.

**Comment by pkrzemo** [comment]
A jak klient wpłaci na konto firmy sprzedawcy a nie na  PayU/P24?
To jak wtedy sprawić żeby było READY_FOR_PROCESSING?
Bo inaczej nie ma danych dot. adresu dostawy...
#2668

**Comment by PrzemyslawLukanowski** [comment]
Nasza ścieżka zakupowa nie przewiduje takiej sytuacji. Kupujący przed potwierdzeniem zakupu poprzez "Kupuję i płacę" wybiera określoną metodę płatności, która jest powiązana z Allegro Finanse. Jeżeli płatność z jakiegoś powodu się nie powiedzie, może nastąpić próba jej ponowienia.
