### ISSUE TITLE
Błędny styl przy wystawianiu aukcji przez Baselinker - Rest API

### ISSUE THREAD

**Issue by novy911** [allegro/allegro-api#2653]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Dzień dobry, jesteśmy połączeni z Allegro po rest api poprzez platformę Baselinker. Wdrażylismy nowy sklep pod który stworzyliśmy nowe konto na Allegro, wszystko połączyliśmy poprzez Baselinker. Nasz sklep oparty jest na Woocommerce , a produkty w nim mają dużą liczbę atrybutów i ich wartości, np. tarcza hamulcowa ma między innymi atrybut MOC SILNIKA który posiada wartości: 122, 136, 144, 160, 163, 177 ... itd

Po wystawieniu aukcji z dużą liczbą atrybutów i ich wartości, dane wyjeżdżają poza obszar opisowy w bok. Przykład znajduje się na aukcji: https://allegro.pl/oferta/tarcza-hamulcowa-55383pro-hc-hella-pagid-8dd355129-8787475854?item=8787475854

**Comment by PatrykBocian** [comment]
Zweryfikowałem twój problem - w tym przypadku, kiedy podajesz taką ilość danych bez spacji, traktowane to jest jako jeden wyraz. Nie widać wtedy w którym momencie powinien zostać rozdzielony. Możesz skorzystać z spacji lub użyć funkcji “**Pasuje do**” - wyeliminuje to twój problem.

Więcej informacji jak to zrobić znajdziesz w naszym [poradniku](https://developer.allegro.pl/compatibility_list/).
