### ISSUE TITLE
[sandbox] nie działa wystawianie aukcji

### ISSUE THREAD

**Issue by docc46** [allegro/allegro-api#2654]
Jestem zalogowany na stronie allegro.pl.allegrosandbox.pl. Niestety każda próba wystawienia nowej aukcji przekierowuje do strony logowania na produkcji allegro.pl/login, przez co nie da się obecnie wystawić oferty na sandboxie.

**Comment by michalpokora** [comment]
https://github.com/allegro/allegro-api/issues/2642 tu masz rozwiązanie a właściwie obejście

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - kiedy wybiorę "wystaw" zostaję przekierowany na stronę https://allegro.pl.allegrosandbox.pl/offer/?lokalnie - o tym problemie wiemy, informacja o nim trafiła już do odpowiedniego zespołu. Czy w Twoim przypadku dalej jesteś przekierowywany na allegro.pl/login? Skorzystaj z linku https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, aby tymczasowo obejść ten problem.

**Comment by docc46** [comment]
Mnie "Wystaw przedmiot" nadal przenosi do allegro.pl/login, ale z wskazanego linku przechodzę do właściwego formularza, dzięki.  Przy okazji proszę o aktywację sprzedaży dla konta AllebotVendor (allebotvendor@tmail2.com)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , czy można prosić o aktywowanie konta spam[at]radeq.info (na osobę prywatną)? - nie przychodzi mi e-mail aktywacyjny, próbowałem z różnych skrzynek.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq wiadomości na ten e-mail wysłaliśmy wczoraj o 10:36:15 i 16:36:17. Sprawdź: 
 - czy nie trafiły do folderu spam,
 - ustawienia swojej skrzynki pocztowej, być może z jakiegoś powodu blokuje te wiadomości.
