### ISSUE TITLE
Limity zapytań 

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#2657]
Proszę o informację jak wygląda sytuacja limitów żądań szczególnie per IP.

Czy jeśli na określonym Client ID otrzymam 429, to czy na drugim koncie będą możliwe requesty w tym samym czasie, czy jednak wraz z blokadą na Client ID jest od razu blokada na IP?

Czy w/w blokada na IP jest równoznaczna z blokadą wejścia po froncie na https://allegro.pl z tego adresu?

**Comment by PatrykBocian** [comment]
W takim przypadku blokujemy tylko Client ID, w związku z tym operacje wykonywane równolegle na drugim Client ID będą procesowane dalej. Blokada Client ID nie blokuje IP ani dostępu do serwisu WWW.

**Comment by vitapak** [comment]
Ostatnie pytanie - jak wyglądają limity po stronie frontu allegro.pl - kiedy requesty mogą sypać 429?

**Comment by PatrykBocian** [comment]
Na froncie oczywiście posiadamy odpowiednie zabezpieczenia chroniące przed takimi sytuacjami, w których nasze mechanizmy byłyby narażone na uporczywe działanie zewnętrznych programów.
