### ISSUE TITLE
Zdarzenie FILLED_IN przed  BOUGHT 

### ISSUE THREAD

**Issue by forfiter1** [allegro/allegro-api#2658]
Witam
Czy to też nie jest błąd ? W opisie piszecie, że może wystąpić READY_FOR_PROCESSING  przed FILLED_IN ale nie ma mowy o BOUGHT . Trochę to komplikuje.

A przy okazji: WebAPI zwracało dokładną metodę płatność (np mBank, ING, Blik) a tu widzę tylko PayU P24. Już nie będzie dostępnych tych informacji ?
Pozdawiam

**Comment by PatrykBocian** [comment]
Sytuacja którą opisujesz może mieć miejsce - nie jest to błąd. Opisany przypadek z **READY_FOR_PROCESSING** przed **FILLED_IN** jest podany jako przykład, może się zdarzyć analogiczna sytuacja z **BOUGHT**.

W REST API zwracamy tylko dane o operatorze płatności - informacja o sposobie płatności wybranym przez kupującego (BLIK, mBank itp.) w takich przypadkach nie jest istotną informacją dla zrealizowania zamówienia, najważniejsze są ich statusy.

**Comment by forfiter1** [comment]
Ok, rozumiem. A jeśli o statusy chodzi to rozumiem, że zasób https://api.allegro.pl/order/events nie zwraca zdarzenia anulowania płatności  ?

**Comment by PatrykBocian** [comment]
W takim przypadku pojawia się tylko status **FILLED_IN**, dopiero po poprawnie zakończonej płatności otrzymujemy status **READY_FOR_PROCESSING**. Anulowanie płatności nie ma swojego osobnego eventu.

**Comment by forfiter1** [comment]
OK, wszystko jasne. Dziękuję za odpowiedź.
