### ISSUE TITLE
Anulowana płatność

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#2659]
W jaki sposób dowiedzieć się czy w danym zamówieniu o statusie READY_FOR_PROCESSING płatność została anulowana?

**Comment by forfiter1** [comment]
Jeśli status jest READY_FOR_PROCESSING to chyba płatność została zaakceptowana i nie może być anulowana.

**Comment by PatrykBocian** [comment]
Dokładnie tak jak napisał @forfiter1 - płatność w statusie **READY_FOR_PROCESSING** nie może zostać anulowana. Nie oznaczamy anulowanych płatności w zamówieniach.
