### ISSUE TITLE
Niewypełnione formularze pozakupowe

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#266]
Pytanie z gatunku ogólnych: w jaki sposób za pomocą WebApi najlepiej wyłuskać akty zakupowe (deals) czy czy identyfikatory ofert, dla których nie zostały wypełnione formularze pozakupowe?

**Comment by lukada4100** [comment]
Ech... Pytanie uzupełniające: w jakich sytuacjach paymentStatus dla Deala ma wartość "without_payu - brak informacji o wpłacie" Przypadkiem nie właśnie wtedy, kiedy formularz pozakupowy nie został wypełniony?

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem pytanie, o jaką metodę pytasz, bo w metodzie doGetSiteJournalDeals są dostępne cztery typy zdarzeń: 
1 - utworzenie aktu zakupowego (deala), 2 - utworzenie formularza pozakupowego (transakcji), 3 - anulowanie formularza pozakupowego (transakcji), 4 - zakończenie (opłacenie) transakcji przez Allegro Finanse). 
Status 4 oznacza, że uzupełniony został formularz dostawy i opłacony.

**Comment by lukada4100** [comment]
Faktycznie się nie rozumiemy. Piszę o metodzie doGetRefundDeals która zwraca wg dokumentacji dealsList (RefundListType[]) i o polu paymentStatus dla tej struktury.

Przy okazji, dokumentacja mówi o wartości "cod" dla płatność przy odbiorze, w rzeczywistości jest to wartość "on_delivery".

**Comment by MaciejPotepa** [comment]
Wartość 'without_payu - brak informacji o wpłacie' - otrzymasz wtedy kiedy ktoś nie wypełni formularza po zakupowego. 

Dzięki za uwagę, poprawimy dokumentację.
