### ISSUE TITLE
Brak unikalności payment.id, a być może wszystkich UUID.

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#2660]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wdrażaniu eventów przez REST, napotkałem na problem, który według mnie nie powinien mieć miejsca. 
Pobieram sobie checkoutForms dla dwóch kont, interesują mnie wartości paymentId aby uzyskać trasactionId. I... co jakiś czas dostaję te same paymentId.
Przykład:
z konta A 
```
checkoutForm.id: 28fe7014-ff54-11e9-96ca-53937b43a074,
payment.id: 04c58f74-ff55-11e9-98a1-c7611b6dc049, 
paidAmount.amount: 118.94, 
finishedAt: 2019-11-04T22:50:41.615Z
```
z konta B 
```
checkoutForm.id: 28fe7015-ff54-11e9-96ca-53937b43a074,
payment.id: 04c58f74-ff55-11e9-98a1-c7611b6dc049, 
paidAmount.amount: 95.63, 
finishedAt: 2019-11-04T22:50:41.615Z
```
Jeżeli jedynym źródłem entropii przy generowaniu UUID jest czas z dokładnością do mikrosekund, to chyba trzeba to poprawić...

**Comment by mindc** [comment]
Czy payment.id jest stricto związany z checkoutForm.id?
Bo widzę, że te dwa zamówienia były dokonane przez tą samą osobę, więc wynika z tego że payment.id jest prawidłowy (jedna płatność dokonana za oba towary)

**Comment by PawelTaberski** [comment]
payment.id jest to identyfikator płatności, jest on unikatowy dla danej płatności. Jeśli user zakupił kilka przedmiotów od różnych sprzedających, ale jedna płatnością to będzie ona miało jedno id.

**Comment by mindc** [comment]
Zmyliły mnie te różne kwoty... dziękuję za pomoc.
