### ISSUE TITLE
 Próba otwarcia strony została zablokowana 

### ISSUE THREAD

**Issue by mleplawy** [allegro/allegro-api#2661]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
Token: string(164) "grant_type=authorization_code&code=iGo0rOhkVJna1hADs7jqfmPQFjhDCRVL&api-key=9c2d46b6&redirect_uri=http%3A%2F%2F10.0.1.132%2Faplikacje%2Fdostepnosc%2FrestAllegro.php" array(1) { ["http"]=> array(4) { ["method"]=> string(4) "POST" ["header"]=> string(202) "Authorization: Basic YzFjODRlODkyZjExNDgxZmI0NTFhMjkwMWY4YTU3YWY6c2dGR3VtTFdIZkhBM3NxZkJZUnhXd3RoQzRxQ3pJQ3NsMHhxc3JVUVA5Q2xpampKME1jVTg1N1NzTG1hUjJDZQ== Content-Type: application/x-www-form-urlencoded" ["content"]=> string(164) "grant_type=authorization_code&code=iGo0rOhkVJna1hADs7jqfmPQFjhDCRVL&api-key=9c2d46b6&redirect_uri=http%3A%2F%2F10.0.1.132%2Faplikacje%2Fdostepnosc%2FrestAllegro.php" ["ignore_errors"]=> bool(true) } }
Allegro
Próba otwarcia strony została zablokowana

Coś poszło nie tak. Jeżeli sytuacja się powtarza, to zgłoś ten przypadek obsłudze klienta załączając kod błędu. Pomoże nam to w szybszym rozwiązaniu Twojego problemu.
Kod błędu

6deab2708b1b1d2c
skontaktuj się z obsługą klienta

array(1) { ["http"]=> array(4) { ["method"]=> string(3) "PUT" ["header"]=> string(143) "Authorization: Bearer Api-Key: 9c2d46b6 Content-Type: application/vnd.allegro.public.v1+json Accept: application/vnd.allegro.public.v1+json" ["content"]=> string(108) "{"offerCriteria":[{"offers":[{"id":"8605183819"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END"}}" ["ignore_errors"]=> bool(true) } } {"error":"invalid_token","error_description":"Cannot convert access token to JSON"

**Comment by PawelTaberski** [comment]
Widzę, że używasz stary klucz WebAPI-owy aby korzystać z REST API zarejestruj ponownie aplikację. Otrzymasz nowy Client_ID. Nigdy nie wklejaj na forum pełnych danych swojej aplikacji.

**Comment by mleplawy** [comment]
a jak mam uzyskać restowy klucz nie na stronie mogę go tylko usunąć

**Comment by PawelTaberski** [comment]
Nową aplikację zarejestrujesz tutaj: https://apps.developer.allegro.pl/

**Comment by mleplawy** [comment]
z tego co widzę to mam zarejestrowaną aplikację poprawnie dlatego pytałem. Może problemem jest biblioteka php jaka jest teraz polecana dla PHP? im lżejsza tym lepsza

**Comment by PawelTaberski** [comment]
Masz zarejestrowaną jedną starą aplikację - oznaczona jest jako "Klucz SOAP WebAPI" i dwie nowe. Powinieneś korzystać właśnie z tych nowych. Nowe klucze oznaczone jako "Klucze aplikacyjne REST API" działają w REST i WebAPI, natomiast klucze oznaczone jako "Klucz SOAP WebAPI" działają tylko w WebAPI.

**Comment by mleplawy** [comment]
użyłem nowego API  
czy aby allegro nie zbanowało mojego IP z jakiegoś powodu?

**Comment by PatrykBocian** [comment]
Problemem tutaj jest twój **redirect_uri** - nie może on być wewnętrznym adresem IP. Zmień **redirect_uri** na adres domenowy lub localhost - zarówno w requestach, jak i w [Allegro Developer Apps](https://apps.developer.allegro.pl/), gdzie zarejestrowałeś aplikacje. Poprawny request nie zawiera też “**api-key**”, który tutaj przekazujesz. Przykładowy poprawny request:

 `curl -X POST -H 'Authorization: Basic YTI...Hg=' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'`

Więcej informacji na temat autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/).

**Comment by mleplawy** [comment]
Dzięki pomogła zmiana adresu IP na domenę. Od kiedy wprowadziliście taką zamianę bo w takiej postaci działało conajmniej rok.

**Comment by PatrykBocian** [comment]
Wprowadziliśmy tę zmianę na początku listopada.
