### ISSUE TITLE
Format łączenia publication.status w sale/offers

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#2662]
W przykładach na stronie https://developer.allegro.pl/my_offers/ podane są dwie możliwości łączenia wartości publication.status. Czy oba formaty są poprawne?

1. GET /sale/offers?publication.status=INACTIVE&publication.status=ACTIVE
2. GET /sale/offers?publication.status=INACTIVE, ACTIVATING, ACTIVE, ENDED

**Comment by PatrykBocian** [comment]
Oba formaty działają prawidłowo, lecz zalecamy korzystanie z pierwszego - zaktualizujemy poradnik, aby nie było w związku z tym żadnych wątpliwości.
