### ISSUE TITLE
HTTP/1.1 403 Forbidden przy https://api.allegro.pl/sale/offers/8766XXXXX

### ISSUE THREAD

**Issue by gigul77** [allegro/allegro-api#2663]
Występuje problem: 

Prawidłowo zalogowany, ale jak wolam oferte z wlasnego konta to mam 403! 

trace-id: 87eeecb4a42ebe23

curl -vX GET 'https://api.allegro.pl/sale/offers/8766XXXXX' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Authorization: Bearer XXXXXXXXcvA'

i mam:
{"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":"/sale/offers/8766XXXXX","userMessage":null}]}gigul@gr-nd3a:~$ 

Token dobry! Z cyklu WTF. To co z mojego konta nie moge pobrac oferty ?

**Comment by kfijalko** [comment]
Wczoraj i dziś pobrałem prawidłowo informację z 3 kont. W sumie ponad 200k operacji. Jeżeli masz kilka kont to sprawdź czy używasz prawidłowego tokena. Token możesz rozkodować https://jwt.io/.

**Comment by PatrykBocian** [comment]
@gigul77 Zweryfikowałem twoje zgłoszenie - skorzystałeś z autoryzacji **client_credentials**, czyli nie działałeś w kontekście zalogowanego użytkownika. [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) wymaga autoryzacji **code_flow** lub **device_flow**. Więcej informacji na temat autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/) i [dokumentacji](https://developer.allegro.pl/documentation/).
