### ISSUE TITLE
Błąd dodawania numeru listu przewozowego

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#2664]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

Nie mogę dodać numeru listu przewozowego do zamówienia przez REST API oraz przez panel.
Powodem jest walidacja która nie przepuszcza jak jest spacja w numerze listu.
Przez WebAPI to działała.

Problem zgłaszałem ponad miesiąc temu tu #2533 ale bez odpowiedzi, a sprawa jest banalna bo trzeba w walidacji umożliwić wpisywanie spacji.

**Comment by PatrykBocian** [comment]
Odpowiedź w wątku #[2533 ](https://github.com/allegro/allegro-api/issues/2533).
