### ISSUE TITLE
Zmiana statusu oferty

### ISSUE THREAD

**Issue by GrzegorzLewinski** [allegro/allegro-api#2666]
Występuje problem: 
 - [ X ] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym

Od kilku dni zauważyłem problem dotyczący zmiany statusu ogłoszenia z "szkic" do "aktywny". 
Część aukcji wystawianych za pośrednictwem Rest Api nie zmienia statusu na ACTIVE i zostaje w szkicach.

Po dokonaniu aktualizacji szkiców poprzez RestApi ( czyt. wprowadzenie tych samych danych ) oraz wysłaniu żądania o zmianę statusu natychmiastowo zostały opublikowane.

ID produktu który utknął jako szkic : 8811322844
ID produktów które zostały zaktualizowane i zmieniły status: 8811283249, 8811315471
ID produktu który poszedł bez problemu ( produkt prędzej utknął w szkicach i został całkowicie wysłany na nowo po usunięciu istniejącego szkicu ) : 8816303401

Moje pytanie skąd taka sytuacja ?

**Comment by PatrykBocian** [comment]
Zweryfikowałem twój problem - przekazałem to już do odpowiedniego zespołu.

**Comment by GrzegorzLewinski** [comment]
Witam czy wiadomo coś w związku ze zgłaszanym problemem ?

**Comment by PatrykBocian** [comment]
Prace wciąż trwają - gdy uzyskam więcej informacji to wrócę z odpowiedzią.

**Comment by GrzegorzLewinski** [comment]
Witam wciąż czekam na odpowiedź do zadanego pytania.
Dodatkowo ponownie pojawił się prędzej opisany błąd. Produkty wysyłane do Allegro poprzez RestApi ponownie pozostają w szkicach mimo braku błędu w response z RestApi.
ID produktów wysłane do Allegro poprzez RestApi ze statusem szkic :
- 8976861540
- 8976899991
- 8976946956
- 8977026175

**Comment by MaciejFrackowiak** [comment]
@GrzegorzLewinski Problem, który zgłosiłeś jeszcze w grudniu został rozwiązany - wdrożyliśmy odpowiednie usprawnienie mechanizmu.
Natomiast w odniesieniu do bieżących ofert - mamy opóźnienie w realizacji zleconych zadań, staramy się możliwie szybko je nadrobić.
