### ISSUE TITLE
REST API, GET checkout-forms/{id} - nadmiarowa usługa dodatkowa

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2667]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry,

Błąd polega na tym, że usunięcie usługi dodatkowej (selected additional services) nie powoduje jej skasowania w danych formularza API. Ścieżka postępowania:

1. Aukcja dostępna z dwiema usługami dodatkowymi (np. zapakuj na prezent i montaż).
2. Klient kupuje dwie usługi dodatkowe, wybiera płatność PayU, płaci z niepowodzeniem wpłaty.
3. Klient ponawia płatność ale w formularzu dostawy odznacza jedną usługę dodatkową (montaż).
4. W danych formularza REST API usługa dodatkowa dalej jest widoczna, w zakładce zamówienia sprzedającego również (nie zgadza się kwota). W szczegółach zakupu kupującego tej usługi nie ma.

Przykładowe zamówienie na sandbox: 547f2850-2ba1-11ea-93cf-09416ee750b0

`GET order/checkout-forms/547f2850-2ba1-11ea-93cf-09416ee750b0? || trace-id:be72f28cf1c8955e`

![allegro-checkout](https://user-images.githubusercontent.com/2742214/71615417-8a6fa600-2bb1-11ea-8b1c-6a84f2a3d8a4.png)

Ps: kiedyś w WebApi działało prawidłowo ;)

**Comment by PatrykBocian** [comment]
Zweryfikowałem twoje zgłoszenie - zgłosiłem to już do odpowiedniego zespołu.

**Comment by Radeq** [comment]
@PatrykBocian, czy problem został już rozwiązany?

**Comment by PatrykBocian** [comment]
Pamiętamy o twoim zgłoszeniu - prace nad nim wciąż trwają.

**Comment by Radeq** [comment]
@PatrykBocian chciałbym się przypomnieć z tematem

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad rozwiązaniem problemu.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski 

Jak idą prace?

**Comment by PrzemyslawLukanowski** [comment]
Planujemy wdrożyć odpowiednią poprawkę. O przybliżonym terminie poinformuję, kiedy uda mi się ustalić więcej szczegółów.

**Comment by Radeq** [comment]
Chciałbym się przypomnieć, czekam na poprawkę już 4 miesiące

**Comment by PrzemyslawLukanowski** [comment]
Nadal pamiętamy o Twoim zgłoszeniu. Na tę chwilę nie mogę wskazać orientacyjnego terminu wdrożenia poprawki.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Wdrożyliśmy odpowiednią poprawkę. Problem nie powinien się pojawiać w nowych zamówieniach.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , dziękuję, zrobiłem test i działa tak jak należy.

Tyle czasu już minęło, że się zastanawiałem czy wam tego przez bug bounty na hackerone.com nie zgłosić. Ps: może chociaż firmowy kubek dostanę? ;)

**Comment by TimothyKoval** [comment]
O boże...
