### ISSUE TITLE
Delivery: null przy pobieraniu  /order/checkout-forms/{checkoutForm_id}

### ISSUE THREAD

**Issue by lancer2000** [allegro/allegro-api#2668]
Dzień dobry

Czasami nie pobiera wypełnionego adresu dostawy, po pobraniu szczegółów zamówienia w odpowiedzi json widnieje delivery: null. Zaś w otrzymanej wiadomości email po zakupie jest wypełniony formularz dostawy z innym adresem. Podobnie wypełnionego adresu nie można odczytać z po zalogowaniu się na koncie allegro, w dziale "Zamówienia" . Udaję się dopiero odczytać przez menedżera sprzedaży przy karcie płatności.

Zauważyłem właśnie, że nie pobiera adresu z formularzu przy statusie "Płatność rozpoczęta"

![allegro1](https://user-images.githubusercontent.com/13968809/71617934-b2650680-2bbd-11ea-9afc-05ede4e54bc7.jpg)

![allegro2](https://user-images.githubusercontent.com/13968809/71617943-b8f37e00-2bbd-11ea-8a22-49b3c7cff437.jpg)

**Comment by PatrykBocian** [comment]
Jest to prawidłowe zachowanie - w twoim przypadku na pierwszym screenie widać, że łatność ma status rozpoczęta, czyliw API odpowiada statusowi **FILLED_IN**. Dopiero po opłaceniu zamówienia status zmienia się na **READY_FOR_PROCESSING** i wtedy zwracamy adres dostawy. Więcej informacji na temat zamówień znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/).

**Comment by lancer2000** [comment]
Przejrzałem ten poradnik już wcześniej i nie mogę doczytać w jaki sposób odczytać ten adres dostawy?. Korzystam jeszcze z oprogramowania konkurencji i tam adres dostawy jest odczytywany

**Comment by PatrykBocian** [comment]
Widzisz adres dostawy, ponieważ aplikacja z której używasz korzysta z WebAPI - od 13.01.2020 nie będziesz już mógł ich widzieć.
W REST API odczytasz go za pomocą **GET /order/checkout-forms/{id}**. Aby sprawdzić checkoutFormId, skorzystaj z **GET /order/events**. 
 
Adres dostawy jest widoczny tylko przy zamówieniach ze statusem **READY_FOR_PROCESSING**, przy poprzednich statusach adres może ulec zmianie - dlatego przekazujemy go dopiero na tym etapie.

**Comment by pkrzemo** [comment]
Czyli jeśli klient zapłaci bezpośrednio na konto firmy a nie PayU to sprzedawca nie będzie wiedział gdzie wysłać towar... ?

**Comment by pkrzemo** [comment]
I jeszcze jedno... Jaki jest sens ukrywać te dane przed zalogowaną i zweryfikowaną osobą uprawnioną do   przetwarzania tych danych, podczas gdy te same dane są przesyłane temu samemu użytkownikowi otwartym tekstem w niezakodowanym mailu przechodzącym przez publiczną sieć?

**Comment by PatrykBocian** [comment]
@pkrzemo  Odpowiadając na twoje pytania:

- Kupujący przed potwierdzeniem zakupu poprzez "**Kupuję i płacę**" wybiera określoną metodę płatności, która jest powiązana z **Allegro Finanse**. Jeżeli płatność z jakiegoś powodu się nie powiedzie, może nastąpić próba jej ponowienia. A adres dostawy będzie widoczny tylko przy zamówieniach ze statusem **READY_FOR_PROCESSING**. Kupujący nie ma możliwości wyboru płatności bezpośrednio na konto sprzedawcy.

- Dane o adresie dostawy są widoczne po poprawnym zrealizowaniu płatności - w razie problemów z realizacją zamówienia udostępniamy dane kontaktowe do kupującego.
