### ISSUE TITLE
Sprawdzenie poprawności tokena

### ISSUE THREAD

**Issue by aventez** [allegro/allegro-api#2669]
W jaki sposób mogę sprawdzić poprawność zapisanego tokena typu device_code? Chodzi o to, żeby sprawdzić, czy token jest nadal ważny i czy nie ma potrzeby wygenerowania nowego przy użyciu refresh token.

**Comment by MichalKosowski** [comment]
Hmm no przecież jest tam pole jak długo token jest ważny:

`  "expires_in":43199,                          -- czas ważności tokena dostępowego w sekundach 
                                               (token jest ważny 12 godzin)`

**Comment by PatrykBocian** [comment]
@aventez  Jest dokładnie tak jak pisze @MichalKosowski  - możesz podejrzeć pozostały czas ważności podczas pobierania nowej pary **access_token/refresh_token**:

```
{
  "access_token":"eyJ...dUA",
  "token_type":"bearer",
  "refresh_token":"eyJ...SDA",
  "expires_in":43199,
  "scope":"allegro_api",
  "jti":"2184f3be-f6de-4a66-bd8f-b11347d7ba80"
}
```

**Refresh_token** jest zawsze ważny przez **12h** - pozostały czas ważności jest podany w sekundach (możesz też rozkodować refresh_token i wtedy także dostaniesz taką informację).

**Comment by MichalKosowski** [comment]
Access token jest ważny 12h a Refresh 3 miesiące chyba? :)

**Comment by PatrykBocian** [comment]
@MichalKosowski dokładnie tak - już poprawione :)

**Comment by aventez** [comment]
Póki co opracowałem metodę bazującą na zdekodowaniu tokena JWT, natomiast zależy mi na tym by kondycję tokena sprawdzić zdalnie. Istnieje gotowa metoda, taka jak np. w Google czy muszę wykorzystać dowolne inne żądanie z API?
https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={token}

**Comment by PatrykBocian** [comment]
@aventez Nie mamy takiej metody o której piszesz - w tym przypadku pozostaje rozkodowanie tokena.
