### ISSUE TITLE
Rozpoznawanie domeny .test w URL do przekierowań

### ISSUE THREAD

**Issue by dariuszlorek** [allegro/allegro-api#267]
Po ostatnich zmianach w domenach .app, .localhost czy nawet .local zdaje się, że domena .test jest obecnie właściwym miejscem na testy lokalnych aplikacji. Allegro API nie przepuszcza jednak tego adresu.

![screen shot 2018-06-02 at 14 30 35](https://user-images.githubusercontent.com/2572481/40874655-3248ac98-6672-11e8-87fb-709e584ffd80.png)

**Comment by MaciejPotepa** [comment]
Dzień dobry

Pracujemy nad dodaniem tej domeny do listy, proszę o chwilę cierpliwości.

**Comment by dariuszlorek** [comment]
Nadal nie widać obsługi domeny .test. Kibicuję wdrożeniu bo naprawdę utrudnia to pracę.

**Comment by MaciejPotepa** [comment]
@dariuszlorek Dobre wieści! Dodaliśmy domenę test. 
Można testować!
