### ISSUE TITLE
[DeviceFlow] Używanie tego samego konta na kilku komputerach 

### ISSUE THREAD

**Issue by MichalKosowski** [allegro/allegro-api#2670]
Hej,

Pomagam portować desktopową aplikację na nowe api. Jak na razie wszystko pięknie działa, chciałbym tylko potwierdzić jedną rzecz.

**Scenariusz:**
Użytkownik ma w firmie kilka komputerów na których dokonuje różnych operacji na REST Api. Wszystkie korzystają z tego samego konta.

**Problem:**
Po 12h jedna z maszyn odpala refresh tokena. Powoduje że wszystkie kolejne maszyny przy swoich próbach refreshu dostają błąd 400, bo mają nie aktualny zarówno token dostępowy jak i refresh token.

**Pytanie:**
Jeśli dobrze rozumiem to dokładnie tak to ma działać i nie da się tego przeskoczyć w sposób inny niż dodatkowy mechanizm synchronizujący tokeny pomiędzy komputerami użytkownika?

**Comment by PatrykBocian** [comment]
Każde wygenerowanie **refresh_token** powoduje uzyskanie nowej pary access_token + refresh_token. Nie mamy mechanizmu synchronizującego access_token między różnymi komputerami pracującymi na tym samym koncie - w tym przypadku musiałbyś samemu opracować rozwiązanie.

**Comment by MichalKosowski** [comment]
Ok dzięki za potwierdzenie.
