### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zhuzhong01** [allegro/allegro-api#2671]
![image](https://user-images.githubusercontent.com/16986822/71654839-cc921680-2d6e-11ea-8231-ed943e675010.png)

**Comment by zhuzhong01** [comment]
sandbox

**Comment by PatrykBocian** [comment]
Upewnij się proszę, czy w request przekazujesz ten sam **redirect_uri**, który podałeś przy rejestracji aplikacji w [Allegro Developer Apps](https://apps.developer.allegro.pl.allegrosandbox.pl/). Adresy te muszą być takie same - inaczej otrzymasz błąd jak na zrzucie. Więcej informacji na temat autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/).
