### ISSUE TITLE
configurable product upload

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#2673]
Please help me out i'm integrating magento to allegro.
Is there api call to upload configurable products?
There is an api for simple product upload now not sure how to upload configurable products.

**Comment by PatrykBocian** [comment]
Can you explain what do you mean by “configurable product”? Do you want upload an offer or product? - **that is not the same**. If you want add offer through REST API you should use [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) - more information about this you can find in our [guide](https://developer.allegro.pl/en/sale/). You can edit your offers with [PUT sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

You can also assign offers to a products with [productization](https://developer.allegro.pl/en/productization/) or create new product via [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct).

And you can create multi-variant offer - more information about this you can find in our [guide](https://developer.allegro.pl/en/multi_variant_offers/).

**Comment by 07adityasingh** [comment]
In magento configurable products means a product with attribute size and color has been create where 
for each color and size magento create child product like simple products.
SO i would like to know how i will upload the product.
I have seen products when we click on the color and size different product will display with different price.

**Comment by PatrykBocian** [comment]
If I understand you try to create multi-variant offer?

You can do this for example:

- Create one offer with red shoes -  size 44
- Create another with blue colour, size 45 and different price (but still the same product)
- Connect this offers to one by [PUT /sale/offer-variants/{setId}](https://developer.allegro.pl/documentation/#operation/createOrUpdateVariantSet)

Please check our [guide ](https://developer.allegro.pl/en/multi_variant_offers/) and [documentation ](https://developer.allegro.pl/documentation/#operation/createOrUpdateVariantSet) - we describe how to do this.
