### ISSUE TITLE
/bidding/offers/{offerId}/bid

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#2674]
Występuje problem: [nie możemy zweryfikować twojej oferty kupna. wygląda na to, że masz starszą wersję aplikacji. zaktualizuj ją i spróbuj ponownie.]
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Taki błąd pojawia się przy niektórych wywołaniach 
/bidding/offers/{offerId}/bid
Co może być powodem?
Wynik wywołania:
errors
code: auction_bid_sms_verification_required,
message: bidvalidationexception,
usermessage: nie możemy zweryfikować twojej oferty kupna. wygląda na to, że masz starszą wersję aplikacji. zaktualizuj ją i spróbuj ponownie

**Comment by PatrykBocian** [comment]
Prześlij proszę pełen request i response w formacie cURL - pomoże nam to zweryfikować ten przypadek. Możesz to przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
