### ISSUE TITLE
Dodanie nowej tabeli rozmiarów 

### ISSUE THREAD

**Issue by sl-aw-ek** [allegro/allegro-api#2675]
Czy ja nie potrafię tego znaleźć czy REST nie pozwala na stworzenie nowej tabeli rozmiarów ?

**Comment by PatrykBocian** [comment]
Nie udostępniamy jeszcze zasobu do tworzenia tabeli rozmiarów poprzez REST API - musisz to zrobić przez stronę WWW.
Możesz pobrać istniejące tabele korzystając z **GET /sale/size-tables/{table_Id}**. Więcej informacji na ten temat znajdziesz w tym [newsie](https://developer.allegro.pl/news/2018-04-19-news_tabele_rozmiarow/).

**Comment by sl-aw-ek** [comment]
To jak pobrać już stworzone sobie znalazłem, ale nie mogłem uwierzyć w fakt, że nie ma możliwości utworzenia takiej tabeli z innego miejsca niż formularz Allegro. Przydałoby się to naprawić.

**Comment by PatrykBocian** [comment]
Dostaliśmy już taką sugestię - gdy tylko przygotujemy taką funkcjonalność, poinformujemy o tym w odpowiednim komunikacie.
