### ISSUE TITLE
Aktualny harmonogram

### ISSUE THREAD

**Issue by zetgm** [allegro/allegro-api#2676]
Mam prośbę dotyczącą harmonogramu wprowadzania zmian, chodzi o to, że jest on kompletnie nieaktualny i przez to bezużyteczny. Jak ktokolwiek ma przygotowywać coś swojego bez precyzyjnych informacji z waszej strony. Publiczne dane o ofercie wraz z atrybutami nie są zrealizowane od ponad 9 miesięcy, czy jest jakaś realna szansa na wprowadzenie funkcjonalności która została usunięta a nie ma nadal zamiennika w nowym API?

**Comment by PatrykBocian** [comment]
Daty podane w harmonogramie są wstępnymi planowanymi terminami zmian - może się zdarzyć, że powstanie opóźnienie. W takich przypadkach aktualizujemy harmonogram.. Odnosząc się do publicznych danych o ofercie - prace są w toku, do końca miesiąca postaramy się przekazać jednoznaczne informacje.

**Comment by zetgm** [comment]
Mam pytanie w czym jest problem z dodaniem informacji o ustawionych atrybutach dla danego przedmiotu aby zwracane były w odpowiedzi z API, że nie możecie tego dodać już od prawie roku.
Przecież zapytanie dotyczące danych publicznych jest obsługiwane, więc nie powinno być problemem aby do odpowiedzi dodać informacje o ustawionych atrybutach.

**Comment by PatrykBocian** [comment]
Tak jak wspomniałem wcześniej - terminy w harmonogramie są podawane w przybliżeniu, mogą się zdarzyć z różnych względów opóźnienia. Prace nad zasobami z harmonogramu są w toku - jeśli jesteśmy gotowi na wdrożenie planowanych zmian, to informujemy o tym odpowiednim komunikatem. W innych przypadkach aktualizujemy termin.
