### ISSUE TITLE
Reguły walidacji

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#2677]
Chciałbym poruszyć temat ewentualnej możliwości poznania reguł walidacji konkretnych pól wymaganych do utworzenia aukcji. Z poziomu portalu allegro aplikacja ładnie podświetla pola które są wymagane lub wprowadzono nieoczekiwaną wartość dla konkretnego pola.
Czy jest możliwość dowiedzenia się jakie są reguły walidacji dla kategorii w allegro aby móc zaimplementować podobne mechanizmy w aplikacji zewnętrznej?

**Comment by pawelosajda** [comment]
Pola restrictions, required, dictionary w https://api.allegro.pl/sale/categories/{categoryId}/parameters

**Comment by PatrykBocian** [comment]
@kylovile Jest tak jak pisze @pawelosajda  - możesz pobrać za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) wymagane parametry dla danej kategorii. W przypadku obowiązkowych parametrów znajdziesz wpis “**required”: “true”**, a także wymogi odnośnie ich wartości: **restriction**, **dictionary**, etc. Pomocny będzie tu także nasz [poradnik](https://developer.allegro.pl/sale/#rest-api), gdzie opisujemy niezbędne elementy każdej oferty.

**Comment by kylovile** [comment]
Ok, dziękuje za naprowadzenie
