### ISSUE TITLE
Odpowiedź serwera (sandbox) - Director transaction_orderfrontend has no backends or is disabled

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2678]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W środowisku testowym przy odpytywaniu zasobów np. https://allegro.pl.allegrosandbox.pl/order/event-stats
otrzymuje odpowiedź
`<!--Director transaction_orderfrontend has no backends or is disabled-->`

**Comment by PatrykBocian** [comment]
Sprawdziłem ten zasób u siebie - wszystko działa poprawnie.
Czy mógłbyś przesłać przykładowy request i response w formacie cURL? Pomoże to nam zweryfikować twoje zgłoszenie.

**Comment by pawelosajda** [comment]
Rzeczywiście. Problem mam tylko w Postmanie, coś jest nie tak po mojej stronie. Zamykam

**Comment by dominikfomicz** [comment]
@pawelosajda co było problemem?

**Comment by pawelosajda** [comment]
Jeśli dobrze pamiętam to problem był w adresie, prawidłowy to https://**api**.allegro.pl.allegrosandbox.pl/order/event-stats
