### ISSUE TITLE
Oferta nie chce się zamknąć.

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#2679]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Proszę sprawdzić sale/offer-publication-commands/3c3bdfb5-cda1-47eb-a72e-cfa6867990ba/tasks. Cały czas dostaję {"tasks":[{"offer":{"id":"[cyk wycięte]"},"message":null,"status":"NEW","scheduledAt":"2019-12-28T03:59:03.345Z","finishedAt":null,"field":"publication","errors":[]}]}. 
Chyba ta oferta nie zamierza się już zamknąć.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - status zadania to wciąż NEW. Przekazałem problem do odpowiedniego zespołu.

**Comment by x13pl** [comment]
Również mamy ten błąd.

**Comment by PrzemyslawLukanowski** [comment]
@x13pl Możesz podać przykładowy numer taska (uuid)?

**Comment by kpodemski** [comment]
@PrzemyslawLukanowski 

9802bc75cc9370eb

**Comment by PrzemyslawLukanowski** [comment]
@kpodemski trace-id wystarczy, dziękuję.

**Comment by deneb-k** [comment]
I jak postępy? Problem jest bardzo poważny, bo powtórne zgłoszenie tych samych ofert do zamknięcia nie pomaga. Zadanie się nie wykonuje i już.

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem problem do odpowiedniego zespołu, nadal pracujemy nad rozwiązaniem.

**Comment by deneb-k** [comment]
Dwa tygodnie minęły, nadal masa ofert nie chce zmienić statusu. Leży włączanie i wyłączanie ofert. Jakieś postępy?

**Comment by PrzemyslawLukanowski** [comment]
Taski po dwóch tygodniach od zlecenia są anulowane. Prośba, abyś ponowił komendy. Czy w dalszym ciągu otrzymujesz status NEW? Jeśli tak, poproszę o przykładowy numer UUID.

**Comment by deneb-k** [comment]
Oczywiście. 38e178af-a25b-4faa-ae63-cc55a0c567f6 Ta nie chce się aktywować od dwóch dni.

Anulowanie tasków nie wydaje mi się najrozsądniejszym rozwiązaniem problemu, gdy ja tu czekam na reakcję.

**Comment by PrzemyslawLukanowski** [comment]
Nadal pracujemy nad rozwiązaniem tego problemu. Na tę chwilę alternatywną opcją będzie ponowienie zadań wiszących w statusie NEW. Tak jak wspomniałem, po dwóch tygodniach zadania o tym statusie zostają anulowane.

**Comment by AssAssIn1909** [comment]
Witam, dziś również zaobserwowałem podobny problem, z tą różnicą że oferty były zamknięte a status zamknięcia NEW. Możliwe że inny task przejął zamknięcie lub oferta została zamknięta a status na zadaniu pozostał NEW
CheckoutID:
8f39165f-1e36-4474-88f1-e0a2902cfc70

Przypadek prawdopodobnie podobny tyle że już nie aktywny. Dzięki niemu zauważylem problem bo zaczął nam sypać błędy 404
088407ca-d413-4774-9d28-d6f51671c22c

**Comment by PrzemyslawLukanowski** [comment]
Task 8f39165f-1e36-4474-88f1-e0a2902cfc70 został wprowadzony 2020-01-18, tymczasem oferty były już w statusie ENDED, zamknięte wcześniejszym zadaniem, np: oferta 884***5326 została zamknięta 17.01.2020 taskiem a5883268-561f-4907-a8e4-fe864a5ef325

> Przypadek prawdopodobnie podobny tyle że już nie aktywny. Dzięki niemu zauważylem problem bo zaczął nam sypać błędy 404
> 088407ca-d413-4774-9d28-d6f51671c22c

W tym przypadku otrzymałeś błędy 404 dopiero po dacie 23.10.2020. Taska utworzyłeś 10.01.2020, po dwóch tygodniach został anulowany, nie było już go w bazie. Widzę, że do tego czasu w odpowiedzi otrzymywałeś status 200.

**Comment by AssAssIn1909** [comment]
Przypadek drugi gdzie pojawiły się błędy 404 jest mi wiadomy.
Co do przypadku drugiego,  to według mnie powinien zwrócić status failed dla ofert które już są zamknięte, ponieważ drugi raz nie da się ich zamknąć. W tej chwili wiszą mi takie zadania, a wraz z nimi całe komendy, ponieważ są w statusie NEW czyli do przetworzenia. System oczekuje że coś sie z nimi stanie więc odpytuje regularnie czy coś się zmieniło, a po 2 tygodniach zaczyna sypać błędami, bo już ich nie ma.

Więc sugestia aby przy zamknięciu aukcji, jeżeli jest już zamknięta zwrócić że oferta jest juz zamknięta. Status zadania bez znaczenia, byle by status się zmienił.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za doprecyzowanie.

> Status zadania bez znaczenia, byle by status się zmienił.

W tym przypadku status powinien zmienić się na SUCCESS. To, że taski wiszą w statusie NEW, powiązane jest z błędem opisanym w zgłoszeniu.
