### ISSUE TITLE
doLogin

### ISSUE THREAD

**Issue by FredFlinston** [allegro/allegro-api#268]
Witajcie.
Co się zmieniło z metodą doLogin?
Mam taki błąd:
'Zła nazwa użytkownika i/lub hasło. Sprawdź też, czy nie masz włączonych haseł do aplikacji. Jeśli tak - podaj hasło do aplikacji, zamiast hasła do konta.'

O co chodzi z hasłami do aplikacji?

**Comment by MaciejPotepa** [comment]
Dzień dobry

Niczego nie zmienialiśmy w działaniu metody doLogin. Upewnij się, że dane, którymi się chcesz z autoryzować są poprawne. 

Jeżeli chodzi o hasła aplikacyjne, znajdziesz je [tutaj](https://allegro.pl/myaccount/Settings/security_settings.php/applicationPasswords).

**Comment by rtnet-pl** [comment]
Pewnie Klient włączył autoryzację SMS-em

**Comment by FredFlinston** [comment]
No to teraz mam taki komunikat:
'Niepoprawny protokół TLS. Szczegóły: https://allegro.pl/pomoc/faq/szukaj?fraza=tls'

Windows 7 i VB.NET 2010.
Czy mam używać nowszej wersji VB, czy też gdzieś ten protokół ustawić?

**Comment by MaciejPotepa** [comment]
@FredFlinston Nie znam architektury Twojej aplikacji, nie mogę stwierdzić gdzie konkretnie jest stary protokół TLS.

Wersja, która ma 8 lat może korzystać ze starego protokołu TLS. Spróbuj zaktualizować.

**Comment by FredFlinston** [comment]
Dziękuję za podpowiedź. Tak zrobię.
