### ISSUE TITLE
Dziennik zdarzeń w ofertach z całej platformy

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2680]
![image](https://user-images.githubusercontent.com/26189632/71735540-05a1b800-2e4f-11ea-9745-3ca8246e60e4.png)

Funkcjonalność "dziennik zdarzeń w ofertach z całej platformy" została zaplanowana na IV kwartał 2019 roku. Mamy już styczeń i brak informacji o wprowadzeniu lub przesunięciu terminów. Proszę o informację.

**Comment by jakubmaguza** [comment]
#2520

**Comment by PatrykBocian** [comment]
Daty podane w harmonogramie są wstępnymi planowanymi terminami zmian - może się zdarzyć, że powstanie opóźnienie. W takich przypadkach aktualizujemy harmonogram. Odnosząc się do dziennika zdarzeń dla platformy o ofercie - prace są w toku, do końca miesiąca postaramy się przekazać jednoznaczne informacje.

**Comment by jakubmaguza** [comment]
Opóźnienia są naturalne, komunikacja w tej kwestii jest zła. 22 grudnia dostałem informację że nie zmieniacie harmonogramu, a teraz, że opóźnienie będzie prawdopodobnie ponad miesięczne. To spora różnica.

**Comment by zetgm** [comment]
Panie Patryku, taką samą odpowiedź napisał pan w temacie [#2676](https://github.com/allegro/allegro-api/issues/2676) czy to znaczy, że nie potraficie tego po prostu ogarnąć? gdzie jest problem?

**Comment by PatrykBocian** [comment]
@zetgm Harmonogram zawiera wstępne, planowane terminy wdrożeń nowych zasobów. Mogą zdarzyć się opóźnienia, w takich przypadkach aktualizujemy harmonogram.

**Comment by zetgm** [comment]
Jest to dla mnie jasne, że coś może nie być zrealizowane w zaplanowanym terminie, ale dane publiczne dotyczące ofert, są przesuwane już 4 raz w waszym harmonogramie. Czyli realnie od prawie roku nie jesteście w stanie wdrożyć takiej zmiany, mimo iż zostało to dawno wyłączone w starej wersji API. Gdzie jest trudność?

**Comment by PatrykBocian** [comment]
@zetgm Zasoby do pobrania publicznych danych o ofercie wciąż są aktywne w WebAPI.

Tak jak wspomniałem wcześniej na tę chwilę działamy zgodnie z harmonogramem.
Prosimy o cierpliwość - gdy tylko będziemy mieć więcej informacji, opublikujemy odpowiedni komunikat.

**Comment by zetgm** [comment]
Do dnia 01.04.2019 w WebAPI dostępnym pod adresem https://webapi.allegro.pl/service.php?wsdl istniała metoda doGetItemsList.
Metoda ta w odpowiedzi zwracała międzyinnymi zmienną parametersInfo, która zawierała informacje o atrybutach przypisanych do danej aukcji. Na dzień dzisiejszy odwołując się do wspomnianego wcześniej adresu URL i metody doGetItemsList zostaje zwrócony wyjątek „Function ("doGetItemsList") is not a valid method for this service”. W związku z tym skoro twierdzi Pan, że te zasoby są w dalszym ciągu dostępne w WebAPI to bardzo proszę o informację w jaki sposób można się do tych danych na chwilę obecną dostać, gdyż dokumentacja WebAPI została dość mocno ograniczona.

**Comment by PatrykBocian** [comment]
@zetgm  Wcześniej pytałeś o dane publiczne oferty i do tego odnosiły się moje słowa. Zasób, o którym obecnie wspominasz jest powiązany z wyszukiwarką ofert. Tak jak napisaliśmy w komunikacie w związku z wygaszeniem tej metody:

“Zgodnie z [zapowiedzią ](https://allegro.pl/webapi/news.php/page,2#news_100632 )wyłączyliśmy dziś metodę doGetItemsList.
Zachęcamy do korzystania na REST API z metody [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing)”

**Comment by zetgm** [comment]
Panie @PatrykBocian wygląda na to, że mówimy o dwóch różnych rzeczach.
W WebAPI istniała metoda doGetItemsList - która zwracała listę ofert, w każdej zaś ofercie dostępne były informacje o atrybutach danej oferty. Dzięki temu, w odpowiedzi mieliśmy listę ofert, a dla każdej z nich zestaw atrybutów ustawionych przez sprzedawcę. Są to nadal dane z obszaru publicznego oferty.
Dodatkowo istniała metoda doGetItemsInfo - która zwracała publiczne informacje o danej już ofercie.
To o czym pan mówi, w kontekście danych publicznych oferty to istnienie nadal metody doGetItemsInfo. Bo obecnie istnieje jej zamiennik w REST API ale tylko prywatny.

Z naszego punktu widzenia jednak chodzi nam o występowanie atrybutów w liście produktów, a nie w pojedynczym produkcie. Czyli w tym przypadku idealnie było by gdyby ów atrybuty były po prostu dostępne w metodzie: [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), gdyż teraz nie zawiera ona informacji o atrybutach przypisanych do danej oferty - a jedynie ilości poszczególnych atrybutów. 

Patrząc pod tym kątem w dniu 01.04.2019 została z WebAPI usunięta metoda z której korzystaliśmy a w zamian nie mamy odpowiednika w REST API.

**Comment by PatrykBocian** [comment]
@zetgm Rozumiem, lecz temat dotyczy dziennika zdarzeń i w tym kontekście odebrałem twoją wypowiedź - metody te wciąż są dostępne w WebAPI. Co do GET /listing/offers to masz racje - nie zwracamy informacji o parametrach. Możesz wskazać dokładniej - dlaczego są ci potrzebne takie informacje w tym zasobie? Przekaże wtedy twoją sugestię do odpowiedniego zespołu.

**Comment by zetgm** [comment]
@PatrykBocian obecnie metoda [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) zwraca listę ofert a wraz z nimi tylko ilości danych atrybutów w konkretnej kategorii. Chcemy agregować dane o ofertach publicznych wraz z ustawionymi atrybutami by dla każdej oferty mieć zestaw ustawionych/wybranych atrybutów, dzięki temu możemy dla naszych użytkowników prezentować zestawienia informacji o produktach z możliwością filtracji po atrybutach. Obecnie było by bardzo kosztowne aby takie informacje zdobyć, gdyż trzeba było by odpytywać o każdy produkt niezależnie, dodatkowo korzystając po części z WebAPI. Wspomniana metoda  GET /offers/listing ma dostęp do danych oferty, wystarczyło by dodać do wyniku zestaw atrybutów dla każdej oferty, lub dodać alternatywną metodę, która zwróci takie informacje.

**Comment by PatrykBocian** [comment]
@zetgm Dziękuje za odpowiedź - przekazałem twoją sugestię do odpowiedniego zespołu. Jeśli zdecydujemy się wprowadzić taką funkcjonalność, poinformujemy o tym w odpowiednim komunikacie.

**Comment by zetgm** [comment]
@PatrykBocian czy można założyć jakiś realny czas w jakim uzyskamy odpowiedź? Bo powyższe stwierdzenie choć jest bardzo politycznie poprawne nie pozwala nam niczego planować.

**Comment by PatrykBocian** [comment]
@zetgm  Na tę chwilę możesz korzystać z **GET /offer/listing** - zasób ten posiada możliwość filtrowania wyników. Gdy wywołasz ten zasób z **parametrem wymaganym** (**phrase**, **seller.id** lub **category.id**), w odpowiedzi otrzymasz sekcję “**Filters**”.
Dla przykładu - wyszukanie konsoli PS4 o pamięci wbudowanej 2TB:

- **GET /offers/listing?category.id=147130&parameter.206018=206018_225694**

Aby dostać listę parametrów dla danej kategorii, wywołaj ten zasób z dowolnym parametrem **parametrem obowiązkowym** - dostaniesz listę **podkategorii**, dzięki czemu przejdziesz do tej która cię interesuje. Jeśli chcesz w odpowiedzi otrzymać tylko filtry bez ofert, wywołaj:

- **GET /offers/listing?category.id=147130&parameter.206018&include=-all&include=filters**

Zasób ten jest odzwierciedleniem wyszukiwarki z przeglądarkowej wersji serwisu. Możesz korzystać z podobnych filtrów oraz rodzajów sortowania ofert, a w pierwszej kolejności otrzymasz promowane oferty.

Więcej informacji na temat tego zasobu znajdziesz w naszym [poradniku](https://developer.allegro.pl/listing/).
