### ISSUE TITLE
Integracja z Inpost #2486

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2681]
W nawiązaniu do wcześniejszego wątku #2486

> Czy w "allegro_transaction_id" podajemy lineItemId czy mapujemy (https://api.allegro.pl/order/line-item-id-mappings) i podajemy dealId ?

> InPost już obsługuje nowe zamówienia, czyli lineItemId.

Czy to nie pomyłka? Wydawało mi się, że jako allegro_transaction_id wpisywało się postBuyFormId: 

> Numer transakcji formularza posprzedażowego Allegro, w którym kupujący wybrał formę dostawy Allegro Paczkomaty InPost. 

więc jego odpowiednikiem w RestApi jest chyba checkout-forms.id, nie lineItemId. Czy może coś mi umknęło?

**Comment by SoDaUser** [comment]
Także proszę o uściślenie tej kwestii.

Poczta w elektronicznym nadawcy przyjmuje dla WebApi:  "DeaiId dla WEB_API"
W przypadku InPost był to numer TransactionId

W przypadku elektronicznego nadawcy dla REST API jest to już: "OrderId dla REST_API"
Co zatem należy wstawić w Inpost ???

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku prawidłową wartością będzie [checkoutForm.id](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET).

**Comment by lukada4100** [comment]
"w tym przypadku" czyli kiedy? W Inposcie czy w E-nadawcy?
