### ISSUE TITLE
Pobieranie ostatnich zdarzeń dla zamówień - parametr from

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2683]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

Zgodnie z instrukcją "Jak znaleźć najnowsze zdarzenie" pobieram najnowsze zdarzenie za pomocą:
https://api.allegro.pl.allegrosandbox.pl/order/event-stats 
W odpowiedzi otrzymuję
`{
    "latestEvent": {
        "id": "1577747854303808",
        "occurredAt": "2019-12-30T23:17:14.747Z"
    }
}`
Wywołuję metodę https://api.allegro.pl.allegrosandbox.pl/order/events?from=1577747854303808
i otrzymuję pustą tablicę 
 `{
    "events": []
}`

W waszym przykładzie jest napisane, że powinienem dostać starsze zdarzenia od tego eventu. Jak widać działa to w drugą stronę. 

Kiedy zawołam metodę bez parametru dostaję poniższy wynik:
![image](https://user-images.githubusercontent.com/16481836/71902063-8c150d00-3161-11ea-9099-5038f05944cd.png)

Następnie wybiorę któryś id (przykładowo 1577739028263297)
https://api.allegro.pl.allegrosandbox.pl/order/events?from=1577739028263297
![image](https://user-images.githubusercontent.com/16481836/71902178-c7afd700-3161-11ea-87d0-58ef40b0442e.png)

Jak widać dostaję elementy nowsze od tego ID zamiast starsze. Czyli Wasza metoda, która jest opisana w taki sposób:

> Metodą GET na zasobie /order/event-stats pobierzesz informacje o ostatnim zdarzeniu zautoryzowanego sprzedającego. Mając taki punkt odniesienia, możesz odczytywać kolejne zdarzenia, począwszy od otrzymanego identyfikatora w ramach tego zasobu. Wystarczy, że przekażesz id takiego zdarzenia wywołując metodę GET na zasobie /order/events. Dla poniższego przykładu będzie to GET /order/events?from=1532603898317497.

Nie znajduje tutaj zastosowania. Czy ja robię coś źle? Czy jest to błąd w opisie?

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, GET /order/event-stats zwraca najnowsze zdarzenie. Dziękuję za to spostrzeżenie, w najbliższym czasie poprawimy informację w naszym poradniku.

**Comment by artzie92** [comment]
To w jaki sposób pobrać ostatnie 100 zdarzeń :)?

**Comment by PrzemyslawLukanowski** [comment]
Aby pobrać listę najnowszych zdarzeń, wykorzystaj parametry from (jako wartość przekaż id ostatniego eventu z poprzedniego zapytania) oraz limit.

**Comment by artzie92** [comment]
Czyli żeby pobrać najnowsze zdarzenie muszę zaczynać od najstarszych. Co gdy użytkownik ma ich 100 tysięcy? Mam 99 razy strzelać zanim dostanę 1000 najnowszych. Patrząc na dokumentację nie tak to powinno działać, a poniższe metody nie zadzialaja prawidłowo
![20200107_170538](https://user-images.githubusercontent.com/16481836/71909372-3562ff80-3170-11ea-93e4-712ac99ccefc.jpg)

Oczywiście mogę zapisywać ostatni procesowany event żeby nie powtarzać tej operacji, lecz martwi mnie jedna rzecz.

> Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

Eventy mogą być usuwane. Co jeżeli ja zapisze ostatnio procesowany event, a on nie będzie istnieć? Dostanę błąd? Brak rekordów? Operacje pobierania zdarzeń będę musiał zaczynać od nowa.

**Comment by PrzemyslawLukanowski** [comment]
> Oczywiście mogę zapisywać ostatni procesowany event żeby nie powtarzać tej operacji, lecz martwi mnie jedna rzecz.

Zgadza się, dla parametru from możesz przekazać id eventu, który będzie punktem odniesienia. Każde zdarzenie jest powiązane z określoną datą, dlatego jeżeli zapiszesz w swojej bazie czas dla dla takich punktów, nie będziesz musiał za każdym razem pobierać wszystkich zdarzeń.  

> Patrząc na dokumentację nie tak to powinno działać, a poniższe metody nie zadzialaja prawidłowo

W pierwszym przykładzie wkradł się błąd - pobierzesz 500 najnowszych zdarzeń po danym zdarzeniu. Poprawimy to w najbliższym czasie. Drugi przyład zadziała prawidłowo.

> Eventy mogą być usuwane. Co jeżeli ja zapisze ostatnio procesowany event, a on nie będzie istnieć? Dostanę błąd? Brak rekordów? Operacje pobierania zdarzeń będę musiał zaczynać od nowa.

Taki przypadek nie wchodzi w grę, ponieważ eventy nie są usuwane. Usunięte zostaną stare zamówienia w zasobie GET /order/checkout-forms, a w ich miejsce wskoczy nowe, z innym checkoutForm.id

**Comment by artzie92** [comment]
Dzięki za odpowiedź :) 
Do zamknięcia.
