### ISSUE TITLE
Problem z limitem dla usług dodatkowych

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2684]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mamy problem z wykonaniem requestu na zasób z grupami usług dodatkowych: https://developer.allegro.pl/documentation/#operation/getListOfAdditionalServicesGroupsUsingGET

Jako parametr limit ustawiamy tak jak jest w dokumentacji wartość 1000. Niestety dostajemy od Was zwrotkę że maksymalnie można przekazać 100. Wcześniej daje sobie rękę uciąć że to działało (przynajmniej od maja 2019). Bardzo proszę o przywrócenie pierwotnego limitu na tym zasobie:

```
REQUEST:

GET /sale/offer-additional-services/groups?user.id=(...ciach...)&offset=0&limit=1000 HTTP/1.1
Host: api.allegro.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.0.0
Authorization: Bearer (...ciach...)
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

-------------------------------------
RESPONSE:

HTTP/1.1 422 Unprocessable Entity
Content-encoding: gzip
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Server: envoy
Pragma: no-cache
X-frame-options: DENY
Trace-id: b26290d3dcbe0f15
Date: Tue, 07 Jan 2020 14:26:46 GMT
X-ratelimit-remaining: 8983
X-content-type-options: nosniff
Content-type: application/json
X-ratelimit-limit: 9000
X-envoy-upstream-service-time: 31
Connection: close

{"errors":[{"code":"VALIDATION_ERROR","message":"musi być mniejsza lub równa 100","details":"Invalid value: 1000","path":"getGroups.limit","userMessage":"musi być mniejsza lub równa 100"}]}
```

**Comment by PrzemyslawLukanowski** [comment]
Zaktualizowaliśmy dzisiaj dokumentację o bieżącą maksymalną wartość dla parametru limit - 100. Czy możesz wskazać potrzebę podniesienia tego limitu? Przekażę Twoją sugestię do odpowiedniego działu.

**Comment by kormichu** [comment]
Potrzeba jest prosta, w tej chwili nie działa proces wystawiania aukcji na naszych sklepach bo się odbijamy od Was jeśli chcemy pobrać usługi dodatkowe. Jeśli chcecie zmieniać limity to informujcie o tym w osobnych komunikatach abyśmy mogli się przygotować na taką ewentualność. Aktualizacje przeprowadzamy w trybie miesięcznym. Dodam jeszcze tylko tyle że do tej pory nie było problemu z tym zasobem więc zmiana pojawiła się po Waszej stronie stosunkowo niedawno

**Comment by PrzemyslawLukanowski** [comment]
Aby pobrać większą liczbę wyników, wykorzystaj więcej zapytań, ale z wykorzystaniem parametru offset czyli ?limit=100&offset=0, ?limit=100&offset=100, ?limit=100&offset=200 itd. aż nie dostaniesz w odpowiedzi pustej tablicy, co będzie oznaczać, że pobrałeś już wszystko.

**Comment by jedi-pl** [comment]
@PrzemyslawLukanowski nie jest problem zakodzić to inaczej. 

Problemem jest brak komunikacji o takiej zmianie. 
Jak ktoś ma limit 1000 w kodzie i nagle zmieniacie dokumentacje i zachowanie API to logiczne jest, że ten kod przestaje NAGLE działać. Nie daliście czasu na to, żeby dostosować się do zmiany co spowodowało incydent na produkcji. Brak komunikacji - to jest problem.

**Comment by PrzemyslawLukanowski** [comment]
@kormichu @jedi-pl Zwiększyliśmy limit ponownie do wartości 1000.
