### ISSUE TITLE
Produktyzacja - problem z pobieraniem produktów

### ISSUE THREAD

**Issue by TomekDuszynski** [allegro/allegro-api#2685]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dla zapytania o produkty w oparciu o frazę oraz ID kategorii API sandbox zwraca zawsze pustą tablicę mimo, że przez front sandbox są dostępne w danej kategorii produkty. Problem nie dotyczy środowiska produkcyjnego.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, potwierdziłem ten problem. Przekazałem informację do odpowiedniego zespołu.

**Comment by kormichu** [comment]
Ten sam problem zgłaszałem już jakiś czas temu: https://github.com/allegro/allegro-api/issues/2514

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad rozwiązaniem problemu.

**Comment by AnimalDEV** [comment]
Dla ean 9780000000101 (Telewizor SAMSUNG UE55NU8042 for Integration Testing) działa. Nie sprawdzałem wszystkich z tej listy [https://developer.allegro.pl/productization/#sandbox](url), ale większość nie działa.

**Comment by PrzemyslawLukanowski** [comment]
@AnimalDEV Przed chwilą to przetestowałem i wyszukiwanie po EAN działa dla każdego produktu ze wspomnianej listy. Czy w Twoim przypadku problem nadal występuje?

**Comment by AnimalDEV** [comment]
Wyszukiwanie po ean działa, ale po phrase nie działa.  Na przykład dla książki 9780000000064 nazwa zwracana to "Umorzenie Remigiusz Mróz for Integration Testing" a wyszukanie po phrase jako nazwa zwraca pustą tablicę produktów i count 0 w każdej z kategorii.

```js
{
    "products": [],
    "categories": {
      "subcategories": [{
        "id": "258833",
        "name": "Advertisements and Services",
        "count": 0
      }, {
        "id": "3",
        "name": "Automotive",
        "count": 0
      }, {
        "id": "1429",
        "name": "Beauty",
        "count": 0
      }, {
        "id": "257900",
        "name": "Codes and Vouchers",
        "count": 0
      }, {
        "id": "5",
        "name": "Dom i Ogród",
        "count": 0
      }, {
        "id": "42540aec-367a-4e5e-b411-17c09b08e41f",
        "name": "Elektronika",
        "count": 0
      }, {
        "id": "4bd97d96-f0ff-46cb-a52c-2992bd972bb1",
        "name": "Firma",
        "count": 0
      }, {
        "id": "121882",
        "name": "Health",
        "count": 0
      }, {
        "id": "11763",
        "name": "Kids",
        "count": 0
      }, {
        "id": "a408e75a-cede-4587-8526-54e9be600d9f",
        "name": "Kolekcje i sztuka",
        "count": 0
      }, {
        "id": "38d588fd-7e9c-4c42-a4ae-6831775eca45",
        "name": "Kultura i rozrywka",
        "count": 0
      }, {
        "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0",
        "name": "Moda",
        "count": 0
      }, {
        "id": "3919",
        "name": "Sport i turystyka",
        "count": 0
      }, {
        "id": "258832",
        "name": "Supermarket",
        "count": 0
      }],
      "path": [{
        "id": "954b95b6-43cf-4104-8354-dea4d9b10ddf",
        "name": "Allegro"
      }]
    },
    "filters": [],
    "nextPage": null
  }
```

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, odebrałem to jako problem z wyszukiwaniem według parametru EAN. Odnośnie problemu z phrase przekazałem już informację do odpowiedniego zespołu.
