### ISSUE TITLE
Waga paczki / produktów

### ISSUE THREAD

**Issue by MichalKosowski** [allegro/allegro-api#2686]
Hej,

Od klienta któremu pomogłem przepisać się na REST API wiem, że w starym API była możliwość zczytania wagi przedmiotów (o ile została podana). Wygląda na to że w nowym API nie można zczytać wagi (albo ja coś pominąłem).

Czy jest w planach dodanie takiej funkcjonalności?

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli masz na myśli wagę przedmiotu w ofertach zautoryzowanego sprzedawcy, to zwracamy taką informację jako parametr w zasobie GET /sale/offers/{offerId}. Poniżej przykład, wyciągnięty z zasobu GET /sale/categories/64519/parameters:

![Screenshot_15](https://user-images.githubusercontent.com/51473661/71968559-778a5080-3205-11ea-96f5-5d724c8478da.png)

**Comment by MichalKosowski** [comment]
Hej, działa. Dzięki!
