### ISSUE TITLE
Czy sandbox Allegro jest powiązany z sandboxem Inpostu?

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#2687]
Pracuje nad zintegrowaniem naszego systemu z inpostem oraz inpostu z Allegro.
Wysyłam zapytanie do inpostu o przesyłke i dostaje ze adress email allegor jest nie poprawny. Wiem, moge wyslać maila do inpostu z podobnym pytanie ( bo chyba nie mają innej formy kontaktu??), ale tutaj zazwyczaj szybciej otrzymam odpowiedź. 
Więc:

Czy sandbox Allegro jest powiązany z sandboxem Inpostu?

To pytanie raczej do ludzi którzy już się zintegrowali
Czy mam olać ten błąd (unavailability_reasons: allegro_email_invalid) i skoro "przechodzi" wysyłka to uznać że wszystko działa?

Z góry dziękuje za odpowiedzi.

**Comment by PrzemyslawLukanowski** [comment]
Nasze środowiska nie są ze sobą powiązane, jednak - jak sam napisałeś - być może użytkownicy forum będą w stanie Ci pomóc.

**Comment by SebastianOzdoba** [comment]
@AssAssIn1909 środowiska nie są zintegrowane i nie jesteś w stanie przetestować poprawności integracji Sandbox Allegro -> Sandox Inpost. 
Jeśli chcesz przetestować na sandbox inpostu cokolwiek (abstrahując od Allegro) to dodatkowo musisz zmieniać ręcznie kod paczkomatu, bo nie wszystkie paczkomaty na produkcyjnej wersji są na wersji sandboxowej.
Generalnie testowanie tego scenariusza my robiliśmy na serwisie produkcyjnym :)
