### ISSUE TITLE
Rest Api typu Device czas trwania dostępu do zasobów przez użytkownika

### ISSUE THREAD

**Issue by PrzemyslawZa** [allegro/allegro-api#2688]
Witam, 
Proszę o informacje czy po poprawnej, jednorazowej autoryzacji konta przez użytkownika, aplikacja będzie miała dostęp do zasobów allegro na nieograniczony czas (czy użytkownik po jakimś czasie będzie musiał powtórzyć proces wyrażenia zgody na dostęp aplikacji).

Chodzi mi o to czy w punkt autoryzacji typuDevice 
https://developer.allegro.pl/auth/#appCredentials
- Autoryzacja użytkownika typu Device flow
1,2)numer -> 1, 2/ Skorzystaj z zasobu POST https://allegro.pl/auth/oauth/device, aby otrzymać:
będzie musiał być powtarzany po jakimś czasie.

**Comment by PatrykBocian** [comment]
Gdy prześlesz poprawnie żądanie, otrzymasz odpowiedź token dostępowy - jest on ważny **12 godzin**. Aby nie wykonywać ponownej autoryzacji aplikacji raz na dobę, udostępniamy też **refresh_token** - pozwala on na uzyskanie nowego tokena dostępowego. **Refresh_token** jest jednorazowego użytku, a po jego użyciu otrzymujesz nową parę **access_token** (ważny kolejne 12h) i r**efresh_token**.
Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/auth/#refresh-token).
