### ISSUE TITLE
Kiedy sandbox będzie działał poprawnie ?

### ISSUE THREAD

**Issue by SoftSolid** [allegro/allegro-api#269]

**Comment by LukaszKorek** [comment]
Proszę o więcej szczegółów. Z jaką funkcjonalnością występuje problem? Czym się objawia?

**Comment by SoftSolid** [comment]
Wczoraj wieczorem nie było żadnych ofert i nie można było zobaczyć żadnej oferty. Dziś działa już dobrze.
Do zamknięcia.
