### ISSUE TITLE
Menedzer Sprzedazy

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2690]
A można Was o Menedzera Sprzedazy podpytać? Użytkownicy donoszą, że od wczoraj nie działa tam filtrowanie. Nie wiem czy to chwilowa awaria czy może początek jakiś zmian.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę swoje zgłoszenie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by lukada4100** [comment]
Sprawa załatwiona.
