### ISSUE TITLE
Numery trackingowe paczek

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#2691]
Czy planujecie wprowadzić jakiś sposób śledzenia zmian na liście numerów przesyłek w zamówieniach? Np. w postaci zdarzeń (jak dla FOD)?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz wskazać potrzebę posiadania takiej funkcjonalności?

**Comment by jzskyshop** [comment]
Występuje potrzeba synchronizacji listy numerów przesyłek - klienci wpisują je zarówno przez Allegro jak i naszą aplikację. Masowe pobieranie numerów przesyłek dla historycznych zamówień to często marnotrawienie zasobów.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za wskazanie potrzeby, przekazałem zgłoszenie do odpowiedniego zespołu. Jeśli zdecydujemy się na wprowadzenie takiej funkcjonalności, poinformujemy o tym w odpowiednim komunikacie.

**Comment by vitapak** [comment]
Również oczekuję na taką funkcjonalność

**Comment by PatrykBocian** [comment]
@vitapak Przekazałem także twoje zgłoszenie.
