### ISSUE TITLE
messageToSeller z podziałem na wiersze

### ISSUE THREAD

**Issue by lancer2000** [allegro/allegro-api#2692]
Istnieje możliwość aby z zapytania https://api.allegro.pl/order/checkout-forms,
odpowiedź "messageToSeller" była z podziałem na wiersze tak jak klient napisał?
W wiadomość email pozakupowej, wiadomość dla sprzedającego jest ładnie podzielona i czytelna, a w Rest API zlepia wiersze

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem Twoją sugestię do odpowiedniego zespołu. Czy możesz wskazać potrzebę takiego formatowania tekstu?

**Comment by lancer2000** [comment]
Przede wszystkim tekst jest czytelniejszy. Przykład otrzymanej wiadomości z dzisiaj:

W wiadomości email z podziałem na wiersze:
"Kolor Srebrny szczotkowany/czarny 
Imię psa: ARES 
A na drugiej stronie: tel. XXX-XXX-XXX, ZGUBIŁEM SIĘ"

W Rest API
"Kolor Srebrny szczotkowany/czarnyImię psa: ARESA na drugiej stronie: tel. XXX-XXX-XXX, ZGUBIŁEM SIĘ"

Szczególnie proszę zwrócić na imię psa

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, na tę chwilę nie planujemy wprowadzić takiej funkcjonalności. Jeżeli coś w tej kwestii się zmieni, opublikujemy odpowiedni komunikat.

**Comment by pkrzemo** [comment]
To nie jest nowa funkcjonalność tylko błąd. W polu messageToSeller powinien być przekazany tekst jaki wpisał kupujący. Tymczasem jest przekazywany tekst zniekształcony i to na tyle że użyteczność tego pola staje się wątpliwa.
Czyli jak rozumiem "Na tę chwilę nie planujemy naprawy tej funkcjonalności. Jeżeli coś w tej kwestii się zmieni, opublikujemy odpowiedni komunikat."
:-(

**Comment by PrzemyslawLukanowski** [comment]
To nie błąd, wartość dla messageToSeller w response jest odpowiednio sformatowana i zawiera znaki ("/n"), które informują o pojawieniu się nowej lini, jak poniżej:

![Screenshot_13](https://user-images.githubusercontent.com/51473661/72141361-05477680-3393-11ea-9af6-e3e9a55979d6.png)

**Comment by pkrzemo** [comment]
Jeśli tak jest to nie jest błąd allegro tylko lancer2000, i nie ma mowy o nowej funkcjonalności bo tekst już jest sformatowany...
;-)
