### ISSUE TITLE
orders API problem z external id

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#2693]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/order/events?from=1578224681332788

API w większości przypadków zwraca lineItems->offer->external->id = "1" pomimo, że w ofertach złożonych przy użyciu API owe external->id jest ustawione. Przykładowe oferty: 7534121901, 7521860164

Problem jest dość palący, gdyż bez tego external id nie jestem w stanie w łatwy sposób powiązać produktów z zamówienia Allegro z produktami w naszym sklepie internetowym

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - dla tych dwóch ofert zasób GET /sale/offers/{offerId} również zwraca wartość "1" w polu external.id, podobnie wygląda to na froncie. Prośba o weryfikację, jaką wartość przekazujesz w tym polu w momencie tworzenia draftu.

**Comment by adamTynski** [comment]
Sprawa się chyba wyjaśniła; kwestia external.id = "1" dotyczy starych ofert, utworzonych jeszcze przed momentem wprowadzenia tego pola do ofert. Podejrzewam, że w momencie wprowadzenia pól external.id do starych ofert ich zawartość została uzupełniona wartością domyślną, równą "1". Proszę o poprawienie, jeśli się mylę.

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku wartość external.id powinna wynosić null.
