### ISSUE TITLE
checkoutForm

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2694]
Ktoś ma jakiś pomysł jak mając numer oferty znaleść checkoutFormy w którym ta oferta została kupiona?

**Comment by pkrzemo** [comment]
W każdym checkoutForms masz lineitems. Każdy lineitem dotyczy jednej oferty w zamówieniu. Więc w lineitems masz ten twój numwer oferty = [offer_id]

**Comment by lukada4100** [comment]
No tak. Tylko, żeby sprawdzić w którym checkoutformie jest lineItem z moją ofertą muszę najpierw zaciągnąć wszystkie checkoutformy, a są ich tysiące i wyfiltrować to u siebie.

**Comment by PrzemyslawLukanowski** [comment]
W wątku #2186 pojawiło się podobne pytanie. Znajdziesz tam sugestie, które być może naprowadzą Cię na odpowiednie rozwiązanie.

**Comment by lukada4100** [comment]
Nie moglibyście pomyśleć nad jakimś ułatwieniem? Zaciąganie wszystkich GET /sale/events, żeby wyszukać lineItem i wykorzystać je jako query parametr jest przecież absolutnie kosmicznym i nieracjonalnym rozwiązaniem.

**Comment by kfijalko** [comment]
Przepraszam za wtrącenie ale jestem ciekaw: jak operacyjnie wygląda proces obsługi zamówień ? Czy nie ściągacie wszystkich i nie realizujecie ich po kolei? W jakim przypadku przy realizacji zamówienia wychodzicie od aukcji/oferty?
Twój wpis brzmi tak, jakbyś na liście checkut-forms miał "obce" zamówienia.
U mnie wygląda to tak, że co 5 minut czytana jest kolejka checkout-forms: tworzę nowe lub aktualizuje istniejące zamówienia. w każdej linii zmówienia mam powiązanie do towaru w magazynie i oferty na allegro.
Teraz wyciągnięcie zamówień do oferty jest banalnie proste?

**Comment by lukada4100** [comment]
Z zaciąganych co kilka godzin checkoutForm zapisuję do bazy tylko dane ogólne: dane klienta, sposób wysyłki, kwota pobrania plus id zamówienia.
Szczegóły tj informacje jakie przedmioty zostały zamówione, ich zdjęcia itp za każdym "otwierając" dane zamówienie razem zaciągam z Allegro.

**Comment by kfijalko** [comment]
No to nie pozostaje Ci nic innego jak pobierać pozycje zamówienia.

**Comment by pkrzemo** [comment]
@lukada4100 : Czyli jak coś padnie chwilowo w Allegro to nie można nic robić także w twoim systemie, bo większość istotnych danych jest niedostępna.. ;-)

**Comment by lukada4100** [comment]
No nie da się ukryć.
