### ISSUE TITLE
Załączniki

### ISSUE THREAD

**Issue by SaintRaphaelBass** [allegro/allegro-api#2696]
Mam pytanie odnośnie załączników. Stworzyłem postem obiekt załącznika, ale nie mam pojęcia jak przekazać putem plik, co oznacza zawartość pliku z załącznikiem w postaci binarnej?

**Comment by PrzemyslawLukanowski** [comment]
W nagłówkach odpowiedzi znajdziesz adres URL, na który musisz przesłać teraz zdjęcie za pomocą metody PUT. Zawartość pliku z załącznikiem w postaci binarnej oznacza, że musisz wczytać plik w postaci bajtów. To, w jaki sposób to zrobisz, zależy już od języka, w którym programujesz.

**Comment by SaintRaphaelBass** [comment]
Dzięki
