### ISSUE TITLE
Rany julek! na sandboxie przy pobieraniu zdjęć do ofert

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#2697]
Zamiast zdjęcia otrzymujemy 503 i html z Rany Julkiem, dla każdej oferty.

**Comment by SaintRaphaelBass** [comment]
normalka :-)

**Comment by Onixarts** [comment]
Na froncie tak, ale w API? ;)

**Comment by PrzemyslawLukanowski** [comment]
Czy problem nadal występuje? Udało mi się dodać nowe zdjęcie oraz je pobrać, podobnie z obrazkami z aktywnych ofert.

**Comment by Onixarts** [comment]
Jest już ok.
