### ISSUE TITLE
Co jest nie tak z tym zapytaniem do wstawiania numeru przesyki

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2699]
`$access_token='xxxxxxxxxxxxxxxxx';
		$authUrl="https://api.allegro.pl/order/checkout-forms/f9e4f921-2dfd-11ea-b072-edaa15cf81b4/shipments";
		//$authUrl="https://api.allegro.pl/order/checkout-forms/".$numer_zakupu."/shipments";
		$headers = array();
		$headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
		$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
		//$headers[] = 'Content-Type: application/vnd.allegro.beta.v1+json';
		$headers[] = 'Authorization: Bearer $access_token';
		$data = array(
			'carriedId' => 'DHL',
			'waybill' => '12345678910PL',
			'lineItems' => array('id'=>'f9e4f915-2dfd-11ea-b072-edaa15cf81b4'));
					
		$requestjson = json_encode($data, JSON_UNESCAPED_UNICODE);
		$ch  = curl_init($authUrl);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $requestjson);
	
		$response = curl_exec($ch);
		$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		echo $httpCode.'<br>';
		curl_close($ch);
		$response = json_decode($response);
		print_r($response);
`
zwracany request to :
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => NotSupportedException [message] => Unsupported content type. Please check 'Content-Type' request header [details] => [path] => [userMessage] => The request contains incorrect data. Contact the author of the application. ) ) )

**Comment by rtnet-pl** [comment]
accept: beta, content-type: public?

**Comment by jasiek07** [comment]
Nie pomogło :(

**Comment by PrzemyslawLukanowski** [comment]
Błędna nazwa pola - zamiast carriedId wpisz carrierId.

**Comment by jasiek07** [comment]
Ok po poprawieniu nadal to samo , teraz mój kod wygląda tak jak poniżej , nadal prosze o pomoc
`$access_token='xxxxxxxxxxxxxxxxxxxxxx';
		$authUrl="https://api.allegro.pl/order/checkout-forms/f9e4f921-2dfd-11ea-b072-edaa15cf81b4/shipments";
		//$authUrl="https://api.allegro.pl/order/checkout-forms/".$numer_zakupu."/shipments";
		$headers = array();
		$headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
		$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
		$headers[] = 'Authorization: Bearer $access_token';
		$data = array(
			'carrierId' => 'DHL',
			'waybill' => '12345678910PL',
			'lineItems' => array('id'=>'f9e4f915-2dfd-11ea-b072-edaa15cf81b4'));
			
		
		$requestjson = json_encode($data, JSON_UNESCAPED_UNICODE);
		$ch  = curl_init($authUrl);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $requestjson);
	
		$response = curl_exec($ch);
		$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		echo $httpCode.'<br>';
		curl_close($ch);
		$response = json_decode($response);
		print_r($response);
`
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => NotSupportedException [message] => Unsupported content type. Please check 'Content-Type' request header [details] => [path] => [userMessage] => The request contains incorrect data. Contact the author of the application. ) ) )

**Comment by PrzemyslawLukanowski** [comment]
Dla nagłówków Accept i Content-Type przekaż **application/vnd.allegro.public.v1+json**. W tej chwili jest tam rozbieżnośc.

**Comment by jasiek07** [comment]
Kolejny błąd , teraz nieco inny , a kod wygląda teraz tak : 
`$access_token=Profito::AccessToken($user_id);
		$authUrl="https://api.allegro.pl/order/checkout-forms/f9e4f921-2dfd-11ea-b072-edaa15cf81b4/shipments";
		//$authUrl="https://api.allegro.pl/order/checkout-forms/".$numer_zakupu."/shipments";
		$headers = array();
		$headers[] = 'Accept: application/vnd.allegro.public.v1+json';
		$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
		$headers[] = 'Authorization: Bearer '.$access_token;
		$data = array(
			'carrierId' => 'DHL',
			'waybill' => '12345678910PL',
			'lineItems' => array('id'=>'f9e4f915-2dfd-11ea-b072-edaa15cf81b4'));
			//array(array('id'=>'15313350-5145-11e9-a9f3-b32ec7a30bb2'), array('id'=>'15313351-5145-11e9-a9f3-b32ec7a30bb2'))  //gdy jest wiecej numerów
		
		$requestjson = json_encode($data, JSON_UNESCAPED_UNICODE);
		$ch  = curl_init($authUrl);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $requestjson);
	
		$response = curl_exec($ch);
		$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		echo $httpCode.'<br>';
		curl_close($ch);
		$response = json_decode($response);
		print_r($response);
`
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => ERROR [message] => An error has occurred [details] => [path] => /order/checkout-forms/f9e4f921-2dfd-11ea-b072-edaa15cf81b4/shipments [userMessage] => ) ) )

**Comment by PrzemyslawLukanowski** [comment]
Przekaż poprawną strukturę body, powinno to wyglądać jak poniżej:

```
{
	"carrierId": "DHL",
	"waybill": "12345678910PL",
	"lineItems": [{
		"id": "f9e4f915-2dfd-11ea-b072-edaa15cf81b4"
	}]
}
```
W Twoim przypadku wartośc pola lineItems to obiekt, poprawnie powinna być tablica obiektów.

**Comment by jasiek07** [comment]
Troche sie pogubiłem , czy możesz mi to wpisać w zmienną $data.
Czy to ma wyglądać może tak : 
$data='
{
	"carrierId": "DHL",
	"waybill": "12345678910PL",
	"lineItems": [{
		"id": "f9e4f915-2dfd-11ea-b072-edaa15cf81b4"
	}]
}
';
Jeśli tak to nic to nie zmienia

**Comment by jasiek07** [comment]
ok poradziłem sobie ma to wyglądać tak : 
$data = array(
			'carrierId' => 'DHL',
			'waybill' => '12345678910PL',
			'lineItems' => array(array('id'=>'f9e4f915-2dfd-11ea-b072-edaa15cf81b4')));
Dzięki serdeczne za pomoc ! :)
