### ISSUE TITLE
doGetPostBuyFormsDataForSellers - nieaktualna dokumentacja

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#270]
Pobierając przez WebAPI dane o zamówieniu metodą [doGetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703#method-input) w response postBuyFormShipmentTracking->postBuyFormOperatorId API zwaraca wartość 7, co oznacza wg Państwa dokumentacji "Siódemkę" tymczasem od strony panelu allegro widnieje "DPD", które jest pod numerem 9 w dokumentacji. 

Numer przesyłki był nadawany nie przez API, ale przez panel na stronie Allegro i została wybrana przesyłka "DPD", więc wg dokumentacji OperatorId powinien zostać dodany jako 9.

Czy istniej możliwość uzyskana aktualnych informacji o tym jakie OperatorId nadajecie dla danego operatora?

**Comment by LukaszKorek** [comment]
Dziękujemy za zgłoszenie. Sprawę weryfikujemy.
