### ISSUE TITLE
Czy jest możliwość pobrania danych parametru po jego id

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#2701]
Witam posiadam id parametru (np. 211398).
Czy jest możliwość pobrania danych tego parametru przez rest api podając ten id nie znając id kategorii .
W dokumentacji nie znalazłem takiego sposobu.
Jedynym rozwiązaniem było wzięcie danych z zapytania o parametry kategorii `/sale/categories/{categoryId}/parameters`

**Comment by PrzemyslawLukanowski** [comment]
Dane parametru pobierzesz tylko za pomocą zasobu, o którym wspomniałeś - GET sale/categories/{categoryId}/parameters.

**Comment by AnimalDEV** [comment]
OK dziękuje.
