### ISSUE TITLE
Jak poyskać liste przesortowanych ofert wg tego czy są one wyróżnione?

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#2702]
Witam nie mogę znależć odpowiedniej komendy i filtru do powyższego zagadnienia. 
Myślę że do tego powinna służyć ta komenda :
GET /sale/offers?sort={value}
ale co wprowadzić w pole value by pozyskać tylko te ofery które są wyróżnione.
Z góry dziękuję za pomoc

**Comment by PrzemyslawLukanowski** [comment]
Dla zasobu GET /sale/offers nie ma takiego parametru, ale możesz w tym celu użyć GET /offers/listing z parametrem ?seller.id={sellerId}. Wyróżnione oferty otrzymasz w tablicy promoted.
