### ISSUE TITLE
zwroty prowizji w restAPI

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#2703]
Witam, czy mnie coś ominęło, czy za 2 dni wyłączacie zwroty prowizji w WebAPI a narzędzia do składania wniosków w restAPI nie ma ?

**Comment by PrzemyslawLukanowski** [comment]
Dzisiaj wyłączyliśmy metody dot. obsługi zamówień. Zwroty prowizji w WebAPI nadal działają, planowana data wyłączenia to marzec 2020.
