### ISSUE TITLE
Problem z order/checkout-forms

### ISSUE THREAD

**Issue by procod** [allegro/allegro-api#2704]
Mam problem z najprostszym możliwym kodem pobierającym listę zamówień:

    $getCheckoutForms = "https://api.allegro.pl/order/checkout-forms";
    $ch = curl_init($getCheckoutForms);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $getCheckoutFormsResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($getCheckoutFormsResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $categoriesList = json_decode($getCheckoutFormsResult);

    return $categoriesList;

Niewiedzieć czemu, zwraca mi to błąd 403:
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

Podobnie jest z /order/events (tam jest błąd ERROR)

Klucz mam dobry, bo kilka innych prostych metod, np pobranie typów dostawy, kategorie działają poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
Z jakiego typu[ autoryzacji](https://developer.allegro.pl/auth/) korzystasz? Upewnij się, że nie jest to [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która daje dostęp tylko do publicznych danych, jak właśnie metody dostawy, listing, itp. Jeśli chcesz pobrać zamówienia, użyj zautoryzacji typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow). W naszej dokuemtnacji znajdziesz [odpowiednie oznaczenie](https://developer.allegro.pl/documentation/#section/Authentication), jakiego flow wymaga dany zasób:
- bearer-token-for-user - autoryzacja code lub device,
- bearer-token-for-application - autorzyacja client_credentials.

**Comment by procod** [comment]
Ok, faktycznie coś jest na rzeczy. Wygląda na to, że potrzebuję bearer-token-for-user.
Tylko w jaki sposób mogę w takim razie zrobić taką aplikację, która po prostu pobierze z mojego konta allegro ostatnio zamówienia, bez etapu logowania się przez przeglądarkę. Będzie to w ogóle możliwe teraz?

**Comment by PrzemyslawLukanowski** [comment]
Tak, w tym przypadku wymagany jest token, który posiada kontekst usera - bearer-token-for-user. Nie pobierzesz zamówień, jeśli wcześniej nie zautoryzujesz się jako sprzedawca, do którego należą zamówienia. Etap logowania jest zatem konieczny.

**Comment by zagnagaspo** [comment]
@PrzemyslawLukanowski do czego tyczy się to "Tak"? Chyba powinno być "Nie". Nie da się dostać do tych informacji bez logowania z albo poza aplikacją! Tak jak było ze starym api, że dało się to zrobić bez interakcji usera!

**Comment by PrzemyslawLukanowski** [comment]
@zagnagaspo 

> Ok, faktycznie coś jest na rzeczy. Wygląda na to, że potrzebuję bearer-token-for-user.

Dotyczyło to tej kwestii. W dalszej części rozwijam wypowiedź, która wyjaśnia, czy etap logowania jest konieczny. Faktycznie, mogło to początkowo budzić wątpliwości, dziękuję za spostrzeżenie.

**Comment by procod** [comment]
Dziękuję bardzo za odpowiedź.
