### ISSUE TITLE
Jak autoryzować aplikację raz na zawsze?

### ISSUE THREAD

**Issue by Dingo64** [allegro/allegro-api#2705]
Moja aplikacja korzysta z WebAPi i muszę ją szybko przepisać na REST. Co jakiś czas aplikacja automatycznie odpytuje allegro najnowsze oferty. Robi to oczywiście bez zawracania głowy użytkownikowi.
Jak mam ją przepisać na REST Api, skoro w Rest aplikacja za każdym razem musi być autoryzowana przez użytkownika?

**Comment by TimothyKoval** [comment]
https://developer.allegro.pl/auth/#refresh-token

**Comment by Dingo64** [comment]
@TimothyKoval Dzięki, w ten sposób się udało.
