### ISSUE TITLE
id transakcji w nowym REST API - które pole przekazywać teraz do INPOST?

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#2706]
Cześć, 

jakie pole należy obecnie przekazywać z REST API allegro do INPOST, aby prawidłowo generować przesyłki SMART?

obecnie przy starym webapi przekazywało się id transakcji, czy obecnie jest to 

z metody : order/checkout-forms/{checkoutForm_id}
np. dla statusu READY_FOR_PROCESSING :

 "payment": {
        "id": "1e5c8911-9585-11e8-96ed-27298c74ae02",       -- identyfikator płatności

pytam ponieważ nie jestem pewny a pola różnią się formatem (wcześniej numeryczy).

Jeśli tak jest to proszę o potwierdzenie, a jeśli nie to o sprostowanie i podpowiedź jakie pole z id transakcji należy przesyłać do Inpost w celu wygenerowania nalepki bez kosztów? (smart).

Dzięki!

**Comment by SoDaUser** [comment]
Cześć, 

pytałem InPost otrzymałem taką odpowiedź:

Parametry allegro_transaction_id oraz allegro_user_id należy pominąć, wystarczający jest adres @ maskowany w danych odbiorcy, po nim następuje weryfikacja. 

...proszę nie przekazywać tych parametrów, wystarczy podanie maskowanego adresu email allegro.


Tym samym odpowiedź udzielona w:  Integracja z Inpost #2486 #2681 wydaje się błędna.

**Comment by Adam1610** [comment]
Dziękuję Ci za podpowiedź! CheckoutForm.id też wydawało mi się błędne - ponieważ otrzymujemy je nawet gdy klient nie zapłaci za zamówienie tak więc byłby to krok w tył... Gdy mamy zapłacone zamówienie (lub pobranie) to jedyne co otrzymujemy to właśnie payment.id, (identyfikator zakończonej  płatności) dlatego zapytałem.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zaktualizowanie tej informacji.
