### ISSUE TITLE
"/offers/listing" parametr "include"

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2707]
Potrzebuje informacji w jaki sposób pobrać listę możliwych opcji (takich jak: all, filters, sort), które możemy załączyć lub wyłączyć w parametrze include, w metodzie /offers/listing (search offers).
Nie rozumiem z dokumentacji tego elementu:
![image](https://user-images.githubusercontent.com/26189632/72223611-151cb180-3571-11ea-8e3e-0e97fe101d42.png)

Z góry dziękuję za pomoc!

**Comment by PrzemyslawLukanowski** [comment]
Podkreślony przez Ciebie fragment oznacza to, że jako wartość include musisz przekazać nazwę pola obiektu najwyższego rzędu, np. sort, filters, categories, etc. Dlatego, żeby w odpowiedzi otrzymać tylko listę np. możliwych opcji sortowania w danej kategorii, wywołaj GET /offers/listing?category.id={categoryId}&include=-all&include=sort; jeżeli chcesz otrzymać tylko listę kategorii, w których wystawia wskazany przez Ciebie sprzedawca, użyj GET /offers/listing?seller.id=45334546&include=-all&include=categories.

**Comment by 4sp3ll** [comment]
Dziękuję za odpowiedź. To jest dla mnie jasne. Moje pytanie powinno brzmieć: (a) skąd pobrać listę nazw obiektów najwyższego rzędu i  (b) czym są obiekty najwyższego rzędu.

**Comment by PrzemyslawLukanowski** [comment]
> Moje pytanie powinno brzmieć: (a) czym są obiekty najwyższego rzędu

W tym przypadku to obiekty, które znajdują się bezprośrednio w głównym obiekcie "items".

> skąd pobrać pełną listę nazw obiektów najwyższego rzędu, które mogę wykorzystać w parametrze include

Taką listę znajdziesz na końcu odpowiedzi tego zasobu, są to: searchMeta, categories, filters, sort.
