### ISSUE TITLE
"/offers/listing" parametr "sort"

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2708]
![image](https://user-images.githubusercontent.com/26189632/72224048-32a04a00-3576-11ea-9796-7d0aed5e5591.png)

Czy możliwe jest (w zależności od metody autoryzacji), że różni użytkownicy albo różne aplikację będą widziały różną kolejność wyników przy sortowaniu po trafności korzystając z "/offers/listing" oraz paramentru "sort=relevance" **dla takich samych zapytań, wykonanych w tym samym czasie**? Krótko mówiąc: czy zachowania pojedynczego użytkownika mogą mieć wpływ na wyświetlane mu wyniki, czy znaczenie ma tylko ogół użytkowników i ich zachowania na platformie?

**Comment by PrzemyslawLukanowski** [comment]
Wyniki mogą się różnić, szczegóły znajdziesz w wątku #2516.
