### ISSUE TITLE
Błąd w przykładzie wywołania metody GET /sale/delivery-settings

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#2709]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

[Przykładowy request](https://developer.allegro.pl/sale/#delivery-settings) podaje `/delivery-settings` zamiast `/sale/delivery-settings`

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za to spostrzeżenie, w najbliższym czasie poprawimy ten fragment.
