### ISSUE TITLE
Jak Allegro wprowadza zmiany w drzewie kategorii

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#271]
Dzień dobry,
mam taką sytuację:
oferta (7330144292) była wystawiana "jakiś czas temu" w kategorii:
Motoryzacja > Części samochodowe > Ogrzewanie, wentylacja, klimatyzacja > Ogrzewanie, wentylacja > Dmuchawy
teraz znajduje się w kategorii:
Motoryzacja > Części samochodowe > Układ wentylacji > Dmuchawy
nastąpiła zmiana "kategoria_id".

Nie wiem czy przeoczyłem jakiś komunikat czy nie czytam/śledzę odpowiednich komunikatów/usług....

Czy taka zmiana jest zapowiadana?
Jak jest przeprowadzana z punktu widzenia oferty?
[Moje skrypty się wyłożyły bo posługują się starymi kategoria_id]
KF

**Comment by LukaszKorek** [comment]
Zdarza się, że dokonujemy zmian w kategoriach. Skorzystaj z metody [doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782?cod=OGZkZlVlNmJk), dzięki której pobierzesz najświeższe dane.

**Comment by kfijalko** [comment]
Tak zrobiłem, tylko chwilę zajęło mi zdiagnozowanie co się stało.
Zasadniczo mogę sobie wersjonować kategorie i będę widział, która "wypadła" (dziś 3 z moich kategorii nie dostały danych zwrotnych). Mój mechanizm prawidłowo reaguje na zmiany parametrów dla kategorii, ale nie zakładałem do tej pory zmiany identyfikatora kategorii (mój błąd ;)).
Jednak było by "bardziej koszernie" gdyby były komunikaty, takie jak w przypadku parametrów dla kategorii. Wiele zmian komunikujecie z wyprzedzeniem może takie też?
