### ISSUE TITLE
wypłata środków doRequestPayout

### ISSUE THREAD

**Issue by vbdbsoft** [allegro/allegro-api#2711]
Nie doszukałem się odpowiednika w REST. Jeśli jest proszę o naprowadzenie, Jeśli nie ma kiedy można się spodziewać?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [naszym harmonogramem](https://developer.allegro.pl/schedule/) planowana data wprowadzenia odpowiednika w REST API to pierwszy kwartał tego roku.
