### ISSUE TITLE
Błąd dodawania oferty na Sandbox-ie

### ISSUE THREAD

**Issue by sikorag** [allegro/allegro-api#2712]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją

:beetle: **Opis**

Nie da się wystawić nowej oferty na Sandbox-ie.
Klikam "Moje oferty" -> "DODAJ NOWĄ" i następuje próba przekierowania na stronę [https://staging-lokalnie.allegrogroup.com/oferty/wystaw](https://staging-lokalnie.allegrogroup.com/oferty/wystaw), gdzie pojawia się następujący komunikat:

![image](https://user-images.githubusercontent.com/38217009/72239723-3964a680-35e2-11ea-90bf-5f753111d34b.png)

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę możesz skorzystać z obejścia w postaci linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by SylwesterZarebski** [comment]
Błąd sandboksa ciągle występuje.

**Comment by PrzemyslawLukanowski** [comment]
@SylwesterZarebski Ofertę powinieneś móc wystawić za pomocą linku https://allegro.pl.allegrosandbox.pl/offer/?lokalnie. Sprawdziłem to przed chwilą i nie otrzymałem błędu.

**Comment by SylwesterZarebski** [comment]
Tak, zgadza się, ale ciężko jest co chwilę wklejać link w trakcie testów. Znacznie lepiej byłoby, gdyby funkcja z menu działała poprawnie - jakby nie było, to jest do błąd do poprawy.

**Comment by PrzemyslawLukanowski** [comment]
Nie udaje nam się powtórzyć Twojego błędu - każda próba prawidłowo przenosi do formularza. Rozumiem, że nieważne, czy ofertę próbujesz wystawić z poziomu "Mojego Asortymentu", czy z opcji "Wystaw przez formularz", to za każdym razem od razu otrzymujesz błąd widoczny w pierwszym poście tego wątku?

**Comment by PrzemyslawLukanowski** [comment]
Widzę w wątku #1046, że Twoje konto firmowe zostało aktywowane. Czy możesz spróbować ponownie skorzystać z formularza?
