### ISSUE TITLE
Złe działanie /bidding/offers/{offerId}/bid

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#2713]
Złożono ofertę w wysokości 140,4 zł w aukcji 8833262602.
Została przyjęta. 
Wynik:
o:8:"stdclass":4:{s:9:"maxamount";o:8:"stdclass":2:{s:6:"amount";s:6:"140.40";s:8:"currency";s:3:"pln";}s:10:"highbidder";b:1;s:15:"minimalpricemet";b:1;s:7:"auction";o:8:"stdclass":1:{s:12:"currentprice";o:8:"stdclass":2:{s:6:"amount";s:5:"54.01";s:8:"currency";s:3:"pln";}}}
Dlaczego zatem aukcja zakończyła się wygraną innej osoby za cene 82,01?
Skoro przyjęto kwotę 140,40, to powinno przebić te 82,01.

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów użytkownik 14****31 zabidował za kwotę 140,40 zł, ale sekundę później obniżył swoją ofertę do 81,01. Następnie, kolejną sekundę później, ktoś inny dał 137,01 zł, przebijając tego użytkownika. 2 sek później oferta zakończyła się.

**Comment by mariobros6** [comment]
Dziękuję za wyjaśnienie. Wydawało mi się, że nie można zalicytować mniejszej kwoty niż się już złożyło.
