### ISSUE TITLE
Brak publikacji oferty

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#2715]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Aukcja nr: 8846008804
Status aukcji wg Państwa zasobu: INACTIVE
Data draftu: 2020-01-10 11:08:18

Publikacja była w podobnym terminie. Minęło 3 dni i nadal zasób sprawdzenia statusu publikacji (66b90b33-1936-4439-ade7-a4de0bd0d1ec) zwraca nam status => NEW

Ile taka publikacja może trwać, gdzie znajdę informację dlaczego aukcja nie została opublikowana aż 3 dni?

Niestety requestów jest zbyt dużo i paczki request/response nie są logowane.

**Comment by PrzemyslawLukanowski** [comment]
Publikacja oferty powinna trwać do godziny czasu. Przekazałem Twoje zgłoszenie do odpowiedniego zespołu. Jeżeli problem dotyczy także innych ofert, prośba przekazanie numerów id.
