### ISSUE TITLE
Pytanie o metody "Widok i opcje oferty"

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2717]
Witam,
Zbliża się czas wygaszenia metod: 
- doGetBidItem2
- doGetItemsInfo
- doShowItemInfoExt.
Czy będą one wygaszone zgodnie z harmonogramem, czy mogę mieć pewność, że będą ich odpowiedniki w REST API? Kiedy będą wersje beta żebym zdążył przemigrować to w systemie. 
Na dzień dzisiejszy klienci korzystają z tego dosyć mocno, a nie ma zasobów na publicznym tokenie, które są w stanie zastąpić te metody.
Proszę o informację co planujecie i jakieś zapewnienie, że nie zostaniemy jako programiści z niczym w tej sytuacji.

Pozdrawiam

**Comment by PatrykBocian** [comment]
Prosimy o cierpliwość. Gdy tylko będziemy mieć więcej informacji, opublikujemy odpowiedni komunikat. Napisz proszę, do czego są Ci potrzebne dane z tych zasobów?

**Comment by artzie92** [comment]
Moja aplikacja działa w opraciu o publiczny token. Na ten moment muszę logować się do starego API w momencie kiedy chcę pobrać wszystkie szczegóły oferty, ponieważ nie są one zwracane na listingu. Druga rzecz nie ma opcji szukania w offers/listing po numerze aukcji. Muszę szukać tak długo aż trafię na daną ofertę. Chciałbym też mieć możliwość jak do tej pory pobierania informacji na temat tego kiedy przedmiot był sprzedany, czyli jaka jest historia danej aukcji. Mogę to teraz uzyskać za pomocą doGetBidItem2.

**Comment by PatrykBocian** [comment]
Dziękuje za wskazanie potrzeby. Tak jak wspomniałem wcześniej - gdy tylko będziemy mieć więcej informacji opublikujemy odpowiedni komunikat.
