### ISSUE TITLE
Problem z uwierzytelnianiem w php

### ISSUE THREAD

**Issue by arturpuck** [allegro/allegro-api#2721]
Próbuję otrzymać token dostępowy dla mojej aplikacji w php. Z powodzeniem jestem w stanie otrzymać kod autoryzujący. Problem pojawia się później gdy metodą POST wysyłam rządanie i otrzymuję informacje, że autoryzacja nie powiodla się. Wydaje mi się, że zrobiłem wszystko jak w instrukcji, nie wiem dlaczego cały czas zwraca mi błąd. Oto kod 

``$authenticationCode = request()->get('code');
    
    $curl = curl_init("https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&redirect_uri=http://localhost/redirect&code=$authenticationCode");
     curl_setopt($curl, CURLOPT_HTTPHEADER, array("Authorization:".base64_encode("bc0315a6b0cb46f4998b74d30ecbbfbf:CyGfs2HETf8Y0f3NIm2JsatiN8uXchorznSc1hQGVlw52q0pMaLlB76bUt7iO6Zh")));

     curl_setopt_array($curl, [
       CURLOPT_RETURNTRANSFER => 1,
       CURLOPT_POST => 1
     ]);

   $response = curl_exec($curl);
   curl_close($curl);
   dd($response);

**Comment by arturpuck** [comment]
Lol, problem rozwiązany. W nagłówku zabrakło słowa Basic, czyli powinno być tak.     curl_setopt($curl, CURLOPT_HTTPHEADER, array("Authorization:Basic ".base64_encode("bc0315a6b0cb46f4998b74d30ecbbfbf:CyGfs2HETf8Y0f3NIm2JsatiN8uXchorznSc1hQGVlw52q0pMaLlB76bUt7iO6Zh")));          Nie ma to jak precyzyjna i jasna dokumentacja.....:/

**Comment by PatrykBocian** [comment]
Sposoby autoryzacji opisaliśmy w naszym [poradniku ](https://developer.allegro.pl/auth/)- jest tam podany przykładowy request z Basic:
```

curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(client_id:client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'
```

 W [dokumentacji ](https://developer.allegro.pl/documentation/)także umieściliśmy odpowiedni link :)
