### ISSUE TITLE
Błędny status Smart przy transakcjach z darmową dostawą

### ISSUE THREAD

**Issue by vendoremo** [allegro/allegro-api#2722]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W przypadku, gdy sprzedający ma ustawioną darmową dostawę od określonej kwoty, np. 400 zł, a kupujący dokona zakupu za ponad 400 zł i ma smarta, cała transakcja otrzymuje status smart.

Inpost tymczasem dla takiej transakcji generuje etykietę nie-smart.

Kto się myli? Czy taka transakcja powinna mieć status smart? Nie do końca jest to logiczne.

**Comment by PatrykBocian** [comment]
Zweryfikowałem twoje zgłoszenie - w moim przypadku wszystko działa prawidłowo i otrzymuje pole  **"smart": false**.

Wyślij proszę pełen request i response w formacie cURL lub **trace-id** - pomoże to nam zweryfikować twój przypadek. Możesz to przesłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - w takim przypadku przy zgłoszeniu dopisz #2722.

**Comment by vendoremo** [comment]
Sprawdź proszę zamówienie ID ed39c0f6-35fb-11ea-9980-3fbc568ff720. Mi funkcja checkout-forms zwraca smart=true, a powinno być false dla tego zamówienia. A przynajmniej inpost wygenerował dla niego etykietę na zwykłą przesyłkę.

**Comment by vendoremo** [comment]
@PatrykBocian kontaktowałem się w tej sprawie z InPost - uzyskałem taką odpowiedź "allegro nie przekazało nam tagu chargeAllegro, w związku z tym paczka nie została stworzona jako SMART!. Klient powinien się skontaktować w tej sprawie z Allegro".

**Comment by PatrykBocian** [comment]
W przypadku, gdy sprzedający deklaruje darmową wysyłkę od konkretnej kwoty , a kupujący wybiera metodę dostawę, dla której przypisana jest opcja“SMART” to sprzedający pokrywa koszt takiej przesyłki, ponieważ tak zadeklarował wcześniej (ustalając darmową wysyłkę). Stąd też jednocześnie widzimy pole **“smart”: true**, ale etykieta będzie bez SMART.

**Comment by SebastianOzdoba** [comment]
Zatem moim zdaniem potrzeba funkcjonalności by ustawić, że darmowa wysyłka dostępna jest dla konkretnego sposobu dostawy. 
Wtedy sprzedawca, który ma SMART dla takich nie ustawi darmowej, a dla takich dla których nie ma SMART ustawi.

**Comment by vendoremo** [comment]
@PatrykBocian a Twoim zdaniem jest logiczne, że zamówienie jest smart, a etykieta nie-smart? Nie przekazujecie parametru, który pozwala odróżnić taki rodzaj przesyłki, a potem Inpost generuje etykiety w ZIP zamiast PDF. Czyli z jednej strony mam informację, że zamówienie jest smart, ale Inpost twierdzi, że nie i powstaje problem na etapie przesyłania danych do inpostu, bo podaję Inpostowi dane przesyłki, która jak sądzę jest smart, a tu niespodzianka - Inpost informuje mnie, że nie.

**Comment by PatrykBocian** [comment]
@SebastianOzdoba @vendoremo Przekazałem wasze sugestie do odpowiedniego zespołu - jeśli zdecydujemy się na taką zmianę to poinformujemy o tym w odpowiednim komunikacie.
