### ISSUE TITLE
Zakańczanie pojedynczej oferty i taskCount":{"total":0,"success":0,"failed":0}

### ISSUE THREAD

**Issue by Kokoscanfly** [allegro/allegro-api#2723]
Witam,
mam pytanie dotyczące zakańczania pojedynczej aukcji. Używam php i RestAPI allegro.
Posiadam następujący kod, który tak naprawdę działa mi tak po drugi raz (ale to już problem na inny temat)
```

  function ZakonczAukcje($aukcja, $token) {
    $wsa = new WyszukiwanieAllegro();
   $headers = [
       'accept: application/vnd.allegro.public.v1+json',
       'content-type: application/vnd.allegro.public.v1+json',
       'Authorization: Bearer '.$token.''
   ];
   $obj = new stdClass();
   $obj->offerCriteria[0] = new stdClass();
   $obj->publication = new stdClass();
   $obj->offerCriteria[0]->offers[0] = new \stdClass();
   $obj->offerCriteria[0]->offers[0]->id = $aukcja;
   $obj->offerCriteria[0]->type = "CONTAINS_OFFERS";
   $obj->publication->action = "END";

   $obj1 = json_encode($obj);
   $guid = $wsa->getGUID();
   $uri = 'https://allegroapi.io/sale/offer-publication-commands/' . $guid;
   $ch = curl_init();
   curl_setopt($ch, CURLOPT_URL, $uri);
   curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
   curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
   curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
   curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
   curl_setopt($ch, CURLOPT_HEADER, 1);
   curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
   curl_setopt($ch, CURLOPT_POST, 1);
   curl_setopt($ch, CURLOPT_POSTFIELDS, $obj1);
   //curl_setopt($ch, CURLOPT_HEADERFUNCTION, "HandleHeaderLine");
   $output = curl_exec($ch);
   $curl_info = curl_getinfo($ch);
   $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
   curl_close($ch);

    if ($output === false || $resultCode !== 200) {
        echo "Response status code: $resultCode\n";
        echo $output;
    }
  }
  ZakonczAukcje($_POST['id'], $wsa->pobierzToken());
}

```
Po wykonaniu kodu otrzymuję następująca odpowiedź.
`Response status code: 201 HTTP/1.1 201 Created expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block server: envoy pragma: no-cache x-frame-options: DENY trace-id: e76b3265a9c80a35 date: Tue, 14 Jan 2020 14:09:15 GMT x-ratelimit-remaining: 8995 x-content-type-options: nosniff content-type: application/vnd.allegro.public.v1+json;charset=UTF-8 content-length: 92 x-ratelimit-limit: 9000 x-envoy-upstream-service-time: 17 {"id":"9356f687-3c92-42fd-b328-167b357cc417","taskCount":{"total":0,"success":0,"failed":0}}`

I teraz pytanie. Dlaczego taskCount":{"total":0,"success":0,"failed":0}} jest 0 i dlaczego zdarza się, że taki kod działa tylko w około 50% przypadków.

**Comment by kfijalko** [comment]
Ta metoda jest asynchroniczna.
Żeby sprawdzić status musisz odpytać:
https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET
https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET

**Comment by PatrykBocian** [comment]
Jest tak jak napisał @kfijalko - dziękuje za odpowiedź.

**Comment by Kokoscanfly** [comment]
Nie wiem czy dobrze rozumiem. 
Aby sprawdzić status wysłanego polecenie o zakończeniu aukcji muszę pobrać status zadania poprzez GET sale/offer-publication-commands/{commandId} gdzie jako {commandId} podaje $guid sprawdzanego zadania. 

Natomiast poprzez /sale/offer-publication-commands/{commandId}/tasks uzyskać już dokładne informację o zadaniu (np. data wykonania zadania)

Dobrze rozumiem ?

Pytanie następne. Czy istnieje inna możliwość zakańcza ofert? oraz dlaczego nie zawsze powyższa metoda działa?

**Comment by PatrykBocian** [comment]
> Nie wiem czy dobrze rozumiem.
> Aby sprawdzić status wysłanego polecenie o zakończeniu aukcji muszę pobrać status zadania poprzez GET sale/offer-publication-commands/{commandId} gdzie jako {commandId} podaje $guid sprawdzanego zadania.
> Natomiast poprzez /sale/offer-publication-commands/{commandId}/tasks uzyskać już dokładne informację o zadaniu (np. data wykonania zadania)
> Dobrze rozumiem ?

 Tak, jest dokładnie tak jak piszesz.

> Pytanie następne. Czy istnieje inna możliwość zakańcza ofert? oraz dlaczego nie zawsze powyższa metoda działa?

Jest to jedyna opcja zakańczania ofert poprzez API. Możesz dokładniej wyjaśnić kwestię tego, że powyższa metoda nie zawsze działa? Możesz podać przykładowy request i response w formacie cURL.

**Comment by Kokoscanfly** [comment]
Dzisiaj wieczorem zmodyfikuję skrypty i zacznę rejestrować odpowiedzi. W momencie wystąpienia problemu rozpocznę nowy wątek. 

Na chwilę obecną dziękuje za pomoc oraz rzeczowe wyjaśnienie.

**Comment by bugproof** [comment]
![image](https://user-images.githubusercontent.com/3116731/104855291-29298a80-590c-11eb-8437-e982757e179e.png)

Czy taskCount nie powinien od razu zwrócić 1 przy total i success? Jeśli zawsze zwraca to 0 po co jest w odpowiedzi?

**Comment by MaciejFrackowiak** [comment]
Dla części przypadków pojawi się tam liczba - m.in. gdy zadanie jest w trakcie i część operacji już się wykonała. Pole "total" w kontekście istnienia obok "success" oraz "failed" pełni rolę porządkową sumującą łączną liczbę zmian.

**Comment by bugproof** [comment]
@MaciejFrackowiak jak często najlepiej odpytywać allegro aby upewnić się że wszystkie taski się już zakończyły? powiedzmy że modyfikuje 1000 ofert naraz w 1 batch request po jakim mniej więcej czasie mogę być pewny że wszystkie te 1000 ofert zostało przetworzone? czy gdy połowa została przetworzona to total będzie miało wartość 500?

**Comment by MaciejFrackowiak** [comment]
@bugproof Na wykonanie operacji mamy 60 minut - oczywiście w zdecydowanej większości przypadków zadania wykonywane są znacznie szybciej, jednak nie ma jednego stałego czasu. Raz może to zająć przykładowo minutę, a raz np. 30 - wiele jest tu zmiennych, jak choćby łączna liczba zleconych zmian w tym samym czasie przez użytkowników. Total będzie zawierało łączna liczbę zmian, a konkretne wartości pojawiają się w success i failed.
