### ISSUE TITLE
Problem z propozycją produktu

### ISSUE THREAD

**Issue by arturpuck** [allegro/allegro-api#2724]
Próbuję dodać nowy produkt poprzez php. Posiadam token dostępowy i robię tak :
``
$curl = curl_init('https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals');
         $tokenValue = $this->tokenInformation->access_token;
         
         curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($curl, CURLOPT_HTTPHEADER, [
                 "Authorization:Bearer $tokenValue",
                 "Accept:application/vnd.allegro.public.v1+json",
                 'Content-Type:application/vnd.allegro.public.v1+json'
             ]);
         curl_setopt($curl, CURLOPT_POSTFIELDS, '{
  "name": "iPhone 5s",
  "category": {
    "id": "string"
  },
  "eans": [
    "0019062113399",
    "0000007905193"
  ],
  "images": [
    {
      "url": "string"
    }
  ],
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "string",
        "to": "string"
      },
      "values": [
        "string"
      ],
      "valuesIds": [
        "string"
      ],
      "valuesLabels": [
        "string"
      ],
      "unit": "string",
      "options": [
        {
          "identifiesProduct": true
        }
      ]
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  }
}');
          
         $result = curl_exec($curl);
         curl_close($curl);
         dd($result);

No i dostaję {"error":"access_denied","error_description":"Access is denied"}. 
Dlaczego tak się dzieje? Przecież chyba wszystko podałem jak należy, prawda?

**Comment by arturpuck** [comment]
Dodałem też 
``curl_setopt($curl, CURLOPT_POST, 1);
Nic nie pomogło.

**Comment by PrzemyslawLukanowski** [comment]
Problem tkwi w rodzaju autoryzacji, prawdopodobnie korzystasz z client_credentials. Zacytuję moją odpowiedź z innego wątku:

> Z jakiego typu autoryzacji korzystasz? Upewnij się, że nie jest to client_credentials, która daje dostęp tylko do publicznych danych, jak właśnie metody dostawy, listing, itp. Jeśli chcesz pobrać zamówienia, użyj zautoryzacji typu code lub device. W naszej dokumentacji znajdziesz odpowiednie oznaczenie, jakiego flow wymaga dany zasób:
> 
> - bearer-token-for-user - autoryzacja code lub device,
> - bearer-token-for-application - autorzyacja client_credentials.

**Comment by arturpuck** [comment]
Korzystam z autoryzacji opisanej w krokach od 1 do 6 na tej stronie  https://developer.allegro.pl/auth/  . Jeżeli to zrobiłem to jaki to jest typ?

**Comment by PrzemyslawLukanowski** [comment]
Opisaliśmy tam code_flow, czyli w Twoim kontekście prawidłowy typ autoryzacji. Prosiłbym o przykładowe trace-id, dla którego otrzymujesz ten response. Dodatkowo prześlij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) request i response w formacie cURL, jaki wykonałeś w pkt. 5 poradnika dot. autoryzacji.

**Comment by arturpuck** [comment]
Poniekąd problem sam się rozwiązał. Tzn to o czym tu napisałem dalej nie działa, ale okazuje się, że zakładka propose product nie dodaje nowego produktu a o to właśnie mi chodzi....
