### ISSUE TITLE
Pobranie nadchodzących opłat?

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2725]
Proszę o informację w jaki sposób można pobrać informację dot. nadchodzących opłat, które normalnie są widoczne w UI? Czy któryś zasób wgl to umożliwi?

**Comment by kfijalko** [comment]
https://developer.allegro.pl/news/2018-07-18-aktualizacja_zasob_do_sprawdzania_daty_oplaty/

**Comment by PrzemyslawLukanowski** [comment]
Informacje znajdują się w linku, który podał @kfijalko - dziękuję.
