### ISSUE TITLE
incydent - błędnie przekazana wartość

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#2726]
Występuje problem: 
 - [x] z zasobem REST API

Obawiam się, że Wasze synchronizujące się wiecznie serwery się nie zsynchronizowały... Dostałem transakcję w RESTApi z checkoutForm c916e7f5-377e-11ea-8d16-0deb3b7eecf4. W polu delivery->cost->amount dostałem 8,99 zł, w polu summary->totalToPay->amount 50,18 zł i w payment->paidAmount->amount także 50,18 zł. Jak nie trudno się domyśleć, Klient kupił towaru za 41,19 zł więc wszystko prawie jest OK, bo 41,19 + 8,99 = 50,18. 
Dlaczego PRAWIE ? Bo w mailu od Allegro przyszła informacja o wpłacie 41,19 zł i zero jako koszt dostawy, bo to SMART. Dodam, że pozostałe kilka tysięcy transakcji jak najbardziej zwraca poprawnie albo ZERO gdy SMART, albo kwotę za transport, gdy ten transport występuje itd. i wszystko jest OK. Tu w tym konkretnym przypadku jest ewidentny babol - RestAPI zwróciło nieprawidłowe dane, jakby serwer, który je przekazał nie zdążył się zsynchronizować, że to smart i koszt się ma wyzerować :( Proszę o weryfikację.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, występuje rozbieżność. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by partyumarty** [comment]
Jestem pod wrażenie. A czy dowiem się chociaż jakie dane są zatem prawdziwe, czyli jaką kwotę nam faktycznie przekazaliście ? Czy mam szansę dowiedzieć się w ilu przypadkach wystąpiła "rozbieżność" ? Wydaje się to być niepokojące, przy dużej skali zamówień... Ponadto pytanie co zostało przekazane do InPostu jako płatnik ?

**Comment by Lebioda** [comment]
Czy pole SMART było wtedy false czy true? Czy formularz zaktualizował się po jakimś czasie?

**Comment by partyumarty** [comment]
> 
> 
> Czy pole SMART było wtedy false czy true? Czy formularz zaktualizował się po jakimś czasie?

Smart było True, ale to raczej niczego nie przesądza, bo z nieznanych nam przyczyn mimo, że od 2 miesięcy jesteśmy w nowej wersji rozliczania usługi smart średnio co 2h zmienia nam się sposób rozliczania. Jednego dnia dostajemy za smarta 0 zł po nowemu, po kilku godzinach dostajemy pełną kwotę 8,99 zł, potem znowu zero i tak od samego początku. Zawsze jednak była zgodność między WebAPI, a mailami, czyli jak nas rozliczało bezgotówkowo - to w mailu i w WebAPI było 0,00 zł. Jak nas przełączyło na rozliczenie za 8,99 zł to i w mailach i w WebAPI było 8,99 zł a teraz zonk - mail swoje a API swoje...
Odpowiadając na pytanie Lebioda -. nie, RestAPI cały czas wskazuje te same (błędne??) dane, to znaczy przed chwilą odpytany zwrócił mi w dalszym ciągu 8,99 zł mimo iż MS wskazuje, że dostałem 0,00 zł. Jak dla mnie to jakaś tragedia normalnie :(

**Comment by PrzemyslawLukanowski** [comment]
@partyumarty REST API pokazuje błędne dane - kwota, jaką przekazaliśmy to 0zł. Do Inpostu został przekazany maskowany mail, jest zamówienie smart.

> Czy mam szansę dowiedzieć się w ilu przypadkach wystąpiła "rozbieżność"?

> z nieznanych nam przyczyn mimo, że od 2 miesięcy jesteśmy w nowej wersji rozliczania usługi smart średnio co 2h zmienia nam się sposób rozliczania. Jednego dnia dostajemy za smarta 0 zł po nowemu, po kilku godzinach dostajemy pełną kwotę 8,99 zł, potem znowu zero i tak od samego początku

Nie otrzymaliśmy więcej zgłoszeń związanych z tych problemem. Przekaż nam proszę przykladowe numery zamówień, dla których występuje sytuacja, o której napisałeś.

**Comment by partyumarty** [comment]
Z całym szacunkiem Panie Przemysławie jak mam niby je ustalić, skoro API zwraca mi, że to SMART za 8,99 zł, a w mailu jest SMART za 0,00 zł. Ponownie odpytane API o ten sam formularz nadal zwraca uparcie te same dane, więc nie ma z czym ich porównać. Przypadkiem pracownik wychwycił. Nikt normalny nie czyta i nie sprawdza, czy przypadkiem ten sam serwis nie zwraca dwóch różnych sprzecznych kompletów danych dla tej samej transakcji. Od momentu implementacji RestAPI, czyli od minionej soboty 11 stycznia mam 2470 transakcji na paczkomaty. Serio Pan zakłada, ze poświęcę jakieś 40 godzin na porównywanie każdej transakcji i wyszukiwanie Waszych błędów - ot tak w czynie społecznym ? To Pan powinien mi powiedzieć dlaczego wystąpił taki błąd, ile razy, w jakich transakcjach i kiedy zostanie naprawiony. Ja podałem jeden przykład - wyłapany przypadkiem. Pan potwierdził, ze faktycznie ten błąd to błąd, teraz piłka jest po Waszej stronie.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem zgłoszenie do odpowiedniego zespołu w celu analizy problemu. Wrócę z wyjaśnieniem po otrzymaniu odpowiedzi.

**Comment by PrzemyslawLukanowski** [comment]
Sprostowanie - kwota 8,99 w REST API to prawidłowa wartość. Do pewnego momentu był Pan rozliczany w nowy sposób, jednak z racji tego, że nie wszystkie maile były przekazywane poprawnie, od 15.01.20 został Pan przepięty na stary system rozliczeń. Informacja, o której Pan wspomina "Jednego dnia dostajemy za smarta 0 zł po nowemu, po kilku godzinach dostajemy pełną kwotę 8,99 zł, potem znowu zero i tak od samego początku." wynika z faktu, że część maili wygenerowanych przed 15.01.20 przekazywał Pan poprawnie (nowy system rozliczeń), część natomiast nie (stary system rozliczeń). Dzisiaj zostanie Pan przepięty na nowy system rozliczeń, lecz jeśli maile do InPostu będzie Pan przekazywać niepoprawnie, będzie Pan chwilowo przełączany na stary system.
