### ISSUE TITLE
Czym jest commandID?

### ISSUE THREAD

**Issue by Cybertron2030** [allegro/allegro-api#2727]
Próbuję dodać zakończenie oferty poprzez endpoint        PUT /sale/offer-publication-commands/{commandId}    no i czytam dokumentację i nie rozumiem co to jest commandID i co mam tam podać. Nie widzę tego nigdzie w dokumentacji. Ktoś objaśni?

**Comment by pawelosajda** [comment]
Musisz sobie samemu wygenerować UUID i zapisać gdzieś u siebie, potem będziesz mógł sprawdzić status operacji podając ten identyfikator.

**Comment by Cybertron2030** [comment]
Nie rozumiem. UUID to jest ten commandID? Gdzie to jest w dokumentacji? Więcej szczegółów?

**Comment by PrzemyslawLukanowski** [comment]
Więcej szczegółów znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-9-offer-publication-commands). Poniżej wklejam fragment, który dotyczy zgłoszenia:

> Jeśli oferta jest już kompletna i poprawnie zwalidowana, to za pomocą metody PUT /sale/offer-publication-commands/{commandId} możesz ją opublikować w serwisie. Jest to metoda asynchroniczna.
> W polu commandId podaj wartość w formacie UUID (universally unique identifier). Jest to globalnie unikatowy identyfikator, który składa się z 32 liczb szesnastkowych (np.: 21ae4ed1-eab7-34ea-b605-cf2e22b5eed3). Identyfikator generujesz we własnym zakresie.
