### ISSUE TITLE
W jaki sposób zastąpić metodę doGetPostBuyData?

### ISSUE THREAD

**Issue by zagnagaspo** [allegro/allegro-api#2728]
Jak w temacie.
Potrzebuję dane sprzedającego. (users-post-buy-data)

**Comment by PrzemyslawLukanowski** [comment]
Jakie konkretne dane chcesz otrzymać? Możesz skorzystać z zasobu [GET /me](https://developer.allegro.pl/en/documentation/#operation/meGET), aby otrzymać dane użytkownika, na którego posiadasz token.

**Comment by zagnagaspo** [comment]
Kupiłem rzecz A na aukcji użytkownika B. Chciałbym dane użytkownika B. Wcześniej używałem doGetPostBuyData i z obiektu users-post-buy-data brałem nazwe, adres, maila itp. Te dane chciałbym.

**Comment by PrzemyslawLukanowski** [comment]
W REST API skupiamy się na funkcjonalnościach dla sprzedających, dlatego nie zwracamy takich informacji. Stale rozwijamy zakładkę [Kupione](https://allegro.pl/moje-allegro/zakupy/kupione), gdzie znajdziesz wszelkie niezbędne dane.

**Comment by zagnagaspo** [comment]
Wyłączacie COŚ I NIE DAJECIE NIC W ZAMIAN?
Po jakiego wafla to wyłączaliście? 
Jak mam skrypty w php to co mi da zakładka Kupione?

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspomniałem, w REST API koncentrujemy się na funkcjonalnościach dla sprzedających, np. dzięki GET /order/checkout-forms/{id} pobierzesz dane kupującego, co również umożliwiała metoda doGetPostBuyData. Przekażę Twoje zgłoszenie do działu odpowiedzialnego za rozwój API, wcześniej proszę o wskazanie konkretnej potrzeby.

**Comment by zagnagaspo** [comment]
Skąd wziąć te {id}?

**Comment by PrzemyslawLukanowski** [comment]
Jest to id checkoutForma, który pobierzesz za pomocą [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET). Więcej szczegółów znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#03).

**Comment by zagnagaspo** [comment]
/order/checkout-forms nie jest od SPRZEDAŻY???
Do sprzedanych przeze mnie rzeczy? Bo to zwraca mi NIC.

**Comment by zagnagaspo** [comment]
HALO. W jaki sposób uzyskać informacje o sprzedającym po skasowaniu przez was metody w starym api?

**Comment by PrzemyslawLukanowski** [comment]
Zgadza się, przeznaczony jest dla sprzedających, a napisałem o nim w kontekście częściowego odpowiednika doGetPostBuyData, jak poniżej:

> Tak jak wspomniałem, w REST API koncentrujemy się na funkcjonalnościach dla sprzedających, np. dzięki GET /order/checkout-forms/{id} pobierzesz dane kupującego, co również umożliwiała metoda doGetPostBuyData. 

Aktualnie nie mamy w planach zasobu, który zwróci informacje o sprzedającym.

**Comment by zagnagaspo** [comment]
To DLACZEGO wyłączacie coś dla czego nie macie odpowiednika w nowym api?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedź znajdziesz we wcześniejszych wpisach - w REST API koncentrujemy się na funkcjonalnościach dla sprzedających. Czy możesz wskazać konkretną potrzebę - w jakim celu są Ci potrzebne te dane?

**Comment by zagnagaspo** [comment]
1 rzecz jest "w REST API koncentrujemy się na funkcjonalnościach dla sprzedających".
Ale wyłączacie coś i nie dajecie nic w zamian. Co to ma do nowego api. Miejcie w nim co chcecie...
Co to za pytanie po co mi są potrzebne. Po jajco.

**Comment by pkrzemo** [comment]
@zagnagaspo : Jeśli tego jeszcze nie zauważyłeś, to WebAPI jest obecnie wycofywane z allegro. Może ci się to podobać, lub nie, ale utrzymanie starego api kosztuje i choć mnie też się to nie podoba to nie nasza sprawa na co ta firma chce albo nie chce wydawać swoje pieniądze. Jeśli tak bardzo tego potrzebujesz to zaproponuj allegro że będziesz opłacał koszty utrzymania starego api - z pewnością wtedy specjalnie dla ciebie to zrobią ;-)
 Pytanie "po co?", jak się domyślam,  zostało zadane aby móc rozważyć czy warto dorabiać w nowym api taką funkcjonalność. Jeśli ich nie przekonasz odpowiedzią na to pytanie, to nic nie zrobią w tym kierunku. A na razie słabo ci idzie... LOL

**Comment by zagnagaspo** [comment]
> @zagnagaspo : [...]

serio myślisz, że ja albo ktoś do czegokolwiek allegro może przekonać? no nie bądź śmieszny. 
Spokojnie, wezmę to skąd indziej. 
O kosztach "utrzymania api" nie będę się wypowiadać.
