### ISSUE TITLE
GET /sale/offers , metoda dziś nie działa ?

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2729]
Występuje problem: 
 - [ ] z zasobem REST API

Jak w temacie , metoda przestała dziś dzialać w moich skryptach i zwraca komunikat błędu całkiem z dupy , bez żadnych szczegółów

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] =>.
                    [path] => /sale/offers
                    [userMessage] =>.
                )

        )

)

**Comment by anaxagore78** [comment]
Zmien application/vnd.allegro.beta.v1+json
na application/vnd.allegro.public.v1+json
u mnie taki blad jak u Ciebie pojawia sie kiedy mam allegro.beta.v1

**Comment by 11mszot** [comment]
ale ja od dawna już nie mam beta tylko public , przecież to metoda od dawna publiczna
używam tej metody ponad pół roku i do dzisiaj wszystko działało jak należy

**Comment by anaxagore78** [comment]
@11mszot ok, taki był moj pierwszy trop, 
przed chwila jeszcze sprawdzałem i beta dokładnie zwraca taki błąd jak podałeś:
`{
  "errors": [
    {
      "code": "ERROR",
      "message": "An error has occurred",
      "details": null,
      "path": "/sale/offers",
      "userMessage": null
    }
  ]
}`

**Comment by 11mszot** [comment]
anaxagore78 mam na pewno  public , na public ci działa w tej chwili ? Możesz sprawdzić ?

**Comment by anaxagore78** [comment]
działa, sprawdzałem

**Comment by 11mszot** [comment]
a  u mnie jest sytuacja taka
w dwóch aplikacjach na dwóch serwerach działa , a w dwóch najstarszych instalowanych jeszcze na samym początku działania REST API gdy generowane klucze apli były bardzo długie ( po jakimś czasie zaczeli generowac już krótsze klucze api) , działać przestało, więc może przyczyny należy szukać w mechanizmach autoryzacji , dzięki za testy muszę posprawdzać w/g aplikacji

**Comment by PrzemyslawLukanowski** [comment]
Nie odnotowaliśmy wczoraj zwiększonej liczby podobnych błędów. Jeśli problem wciąż występuję, przekaż nam proszę przykładowe trace-id, zweryfikujemy to.
