### ISSUE TITLE
Skąd zdobyć nowy klucz WebAPI w sandbox

### ISSUE THREAD

**Issue by MaciekABC1** [allegro/allegro-api#273]
Problem polega na tym: "Niepoprawna wartość klucza WebAPI lub klucz został zablokowany."
Konto na sandbox'ie miałem już z wcześniej i klucz sobie zapisałem. Niestety przestał działać, a link:  https://apps.developer.allegro.pl, działa w przypadku zwykłego allegro. Czy jest jakiś sposób na wygenerowanie nowego klucza?

**Comment by LukaszKorek** [comment]
Poproszę o login konta na środowisku testowym. Problem może powodować brak aktywacji.

**Comment by MaciekABC1** [comment]
Audiotechnic

**Comment by MaciekABC1** [comment]
Właśnie ten klucz posiadam. To konto założyłem w kwietniu. Nie mam problemu z logowaniem się na Allegro. Sandbox mimo tego samego kodu zgłasza błąd. Używałem tego adresu: https://webapi.allegro.pl.allegrosandbox.pl/uploader.php?wsdl

**Comment by LukaszKorek** [comment]
Spróbuj za pomocą https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl

**Comment by MaciekABC1** [comment]
Robię według przykładowego wywołania (Java) podanego przy opisie doLogin. 
Dla:
ServiceService allegroWebApiService = new ServiceService();
pojawia mi się błąd: "Cannot instantiate the type ServiceService"
Próbowałem paru rzeczy, ale dalej nie mogę się zalogować

**Comment by Daniel820** [comment]
Jak dla mnie to link jest źle podlinkowany bo z sandboxa linkuje na produkcję, do linku z zakładki generowanie klucza webApi trzeba dodać allegro sandbox
http://prntscr.com/jw7ae3
Powinno być https://apps.developer.allegro.pl.allegrosandbox.pl/

**Comment by LukaszKorek** [comment]
@MaciekABC1 podeślij proszę request i response w formacie .xml za pomocą formularza https://allegro.pl/pomoc/kontakt Pozwoli to na pełną weryfikację problemu.

**Comment by LukaszKorek** [comment]
@Daniel820 Dzięki za zgłoszenie. Poprawimy to.

**Comment by manhunto** [comment]
Pozwolę się dopisać tutaj.
Mam problem z zalogowaniem się na sandboxa webapi. Zauważyłem, że klucze web api są pomylone pomiędzy środowiskami. Klucz z sandboxa wygenerowałem sobie na https://apps.developer.allegro.pl.allegrosandbox.pl/ lecz nie chce on działać i response metody `doQuerySysStatus` otrzymuje, że klucz jest niepoprawny. Dopiero klucz wygenerowany na produkcyjnym koncie allegro (czyli tutaj https://apps.developer.allegro.pl/) dostaję poprawną odpowiedź. Powyższa metoda przechodzi, teraz jest problem z zalogowaniem się do konta. Metoda `doLogin` zwraca `Kod błędu: ERR_CAPTCHA_REQUIRED Dostęp przez API dla użytkownika został zablokowany z powodu zbyt dużej liczby błędnych logowań na konto. Odblokowanie dostępu nastąpi dopiero po poprawnym zalogowaniu się wskazanego Użytkownika z poziomu serwisu WWW: https://allegro.pl/enter_login.php?captcha=1.` Wcześniej zwracało, że podaje niepoprawne hasło. Próbowałem hasła głównego jak i stworzyłem sobie hasła do aplikacji (da się to zrobić tylko na koncie produkcyjnym, na sandboxie dostaje 404 na tej podstronie). Captchy nie widzę nigdzie do przepisania i już nie wiem kiedy wpisuje poprawne dane.. prosiłbym o jakieś wskazówki jak mogę się zalogować.

**Comment by LukaszKorek** [comment]
W tej sytuacji zaloguj się na graficznej wersji sandboxa i następnie za pomocą API zaloguj się podając hasło do konta, które zarejestrowałeś na Sandboxie. Kwestię komunikatu zweryfikujemy,

**Comment by manhunto** [comment]
@LukaszKorek niestety próbowałem to już wcześniej. Dalej mam komunikat `ERR_CAPTCHA_REQUIRED`. Próbuję zalogować się na konto `lab-dex-test` hasło takie jakim loguje się do wersji graficznej.

**Comment by LukaszKorek** [comment]
W tej sytuacji ustal nowe hasło dla konta w graficznej wersji, zaloguj się na graficznej i następnie zaloguj się za pomocą API.
