### ISSUE TITLE
Podczas dodawania nowego produktu przykład z dokumentacji zostaje uznany za nieprawidłowy JSON

### ISSUE THREAD

**Issue by arturpuck** [allegro/allegro-api#2730]
Usiłuję dodać przedmiot na aukcję i dla celów testowych do ciała(body) rządania http dodałem poprzez skopiowanie przykład z dokumentacji, mianowicie ten : 

`{
  "additionalServices": {
    "id": "string"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "returnPolicy": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "warranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    }
  },
  "attachments": [
    {
      "id": "1928302_MANUAL_45d7a0f543e1b0d05e12a1aef5642efe63389a1d419fe9286d0f158044391fdce"
    }
  ],
  "category": {
    "id": "string"
  },
  "compatibilityList": {
    "type": "MANUAL"
  },
  "contact": {
    "id": "string"
  },
  "createdAt": "2020-01-15T16:07:04Z",
  "delivery": {
    "additionalInfo": "string",
    "handlingTime": "PDT12H30M5S",
    "shipmentDate": "2018-04-01T08:00:00Z",
    "shippingRates": {
      "id": "string"
    }
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  },
  "ean": "string",
  "external": {
    "id": "AH-129834"
  },
  "id": "string",
  "images": [
    {
      "url": "string"
    }
  ],
  "location": {
    "city": "string",
    "countryCode": "string",
    "postCode": "string",
    "province": "string"
  },
  "name": "string",
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "string",
        "to": "string"
      },
      "values": [
        "string"
      ],
      "valuesIds": [
        "string"
      ]
    }
  ],
  "payments": {
    "invoice": "string"
  },
  "product": {
    "id": "string"
  },
  "promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
  },
  "publication": {
    "duration": "PDT12H30M5S",
    "endingAt": "2020-01-15T16:07:04Z",
    "startingAt": "2020-01-15T16:07:04Z",
    "status": "INACTIVE",
    "endedBy": "USER",
    "republish": false
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "minimalPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "sizeTable": {
    "id": "string"
  },
  "stock": {
    "available": 0,
    "unit": "string"
  },
  "tecdocSpecification": {
    "id": "470b8513-b786-b7b9-9e7e-2f848729cfd6",
    "items": [
      {
        "name": "Wersja TecDoc",
        "values": [
          "0319"
        ]
      }
    ]
  },
  "updatedAt": "2020-01-15T16:07:04Z",
  "validation": {
    "errors": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "validatedAt": "2020-01-15T16:07:04Z"
  }
}`

Po wysłaniu rządania POST na https://api.allegro.pl.allegrosandbox.pl/sale/offers   dostaję odpowiedź : 

`{"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Invalid request."}]}`

Rządania wysyłałem poprzez php jak i postmanem z tym samym efektem

**Comment by PrzemyslawLukanowski** [comment]
Wartości oznaczone jako "string" wskazuje jakiego typu musi być dana wartość. Musisz je uzupełnić zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/), a problem ustąpi.

**Comment by arturpuck** [comment]
W poradniku nie ma żadnego działającego przykładu. Wypełniłem JSON w sposób następujący 
`{
  "additionalServices": {
    "id": "876544"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "returnPolicy": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "warranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    }
  },
  "attachments": [
    {
      "id": "1928302_MANUAL_45d7a0f543e1b0d05e12a1aef5642efe63389a1d419fe9286d0f158044391fdce"
    }
  ],
  "category": {
    "id": "bikes"
  },
  "compatibilityList": {
    "type": "MANUAL"
  },
  "contact": {
    "id": "907655"
  },
  "createdAt": "2020-01-15T11:17:46Z",
  "delivery": {
    "additionalInfo": "string",
    "handlingTime": "PDT12H30M5S",
    "shipmentDate": "2018-04-01T08:00:00Z",
    "shippingRates": {
      "id": "string"
    }
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  },
  "ean": "string",
  "external": {
    "id": "AH-129834"
  },
  "id": "string",
  "images": [
    {
      "url": "https://img6.dmty.pl//uploads/201003/1268777162_by_janosiks_600.jpg"
    }
  ],
  "location": {
    "city": "Puck",
    "countryCode": "1940987",
    "postCode": "84-100",
    "province": "Puck"
  },
  "name": "Bike",
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "189",
        "to": "240"
      },
      "values": [
        "2390765"
      ],
      "valuesIds": [
        "9876543"
      ]
    }
  ],
  "payments": {
    "invoice": "cash"
  },
  "product": {
    "id": "string"
  },
  "promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
  },
  "publication": {
    "duration": "PDT12H30M5S",
    "endingAt": "2020-01-15T11:17:46Z",
    "startingAt": "2020-01-15T11:17:46Z",
    "status": "INACTIVE",
    "endedBy": "USER",
    "republish": false
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "minimalPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "sizeTable": {
    "id": "string"
  },
  "stock": {
    "available": 0,
    "unit": "string"
  },
  "tecdocSpecification": {
    "id": "470b8513-b786-b7b9-9e7e-2f848729cfd6",
    "items": [
      {
        "name": "Wersja TecDoc",
        "values": [
          "0319"
        ]
      }
    ]
  },
  "updatedAt": "2020-01-15T11:17:46Z",
  "validation": {
    "errors": [
      {
        "code": "98765477",
        "details": "something",
        "message": "somethingelse",
        "path": "/var/www/",
        "userMessage": "something"
      }
    ],
    "validatedAt": "2020-01-15T11:17:46Z"
  }
}`

Nadal dostaję informację, że jest nieprawidłowy JSON, co jest źle? Jest gdziekolwiek jakiś działający przykład?

**Comment by PrzemyslawLukanowski** [comment]
Najlepszym rozwiązaniem będzie, jeśli utworzysz przykładową ofertę przez front, a następnie pobierzesz ją za pomocą [GET /sale/offer/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Następnie usuniesz pola id, publication, createdAt, updatedAt, validatedAt. Taką strukturę będziesz mógł przesłać za pomocą POST sale/offers.

**Comment by arturpuck** [comment]
Mam rozumieć, że nie dysponujecie żadnym działającym przykładem? Skąd mam wziąć id oferty? Gdzie jest zapisane? Próbowałem znaleźć i założyłem, że np. tutaj https://allegro.pl/oferta/20-x-zestaw-pedzli-do-makijazu-unicorn-jednorozec-8266311968   offerID to 8266311968, ale dla wymienionego zapytania dostaję informację "not found".

**Comment by PrzemyslawLukanowski** [comment]
Testowe API (sandbox) jest odrębnym środowiskiem, dlatego nie pobierzesz oferty, która znajduje się na produkcji. W tym celu wystaw nową za pomocą linka -https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

> Mam rozumieć, że nie dysponujecie żadnym działającym przykładem? 

Najszybszą drogą, aby otrzymać taki przykład jest właśnie wystawienie oferty przez naszą stronę internetową. Poniżej załączam przykładową strukturę, dzięki której utworzysz draft oferty:

```
{
    "name": "oferta testowa",
    "category": {
        "id": "55203"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "17448",
            "valuesIds": [],
            "values": [
                "100"
            ],
            "rangeValue": null
        },
        {
            "id": "26388",
            "valuesIds": [
                "26388_4096"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "203093",
            "valuesIds": [],
            "values": [
                "40"
            ],
            "rangeValue": null
        },
        {
            "id": "451",
            "valuesIds": [
                "451_131072"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "7108",
            "valuesIds": [
                "7108_160"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "219629",
            "valuesIds": [
                "219629_286873"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "3766",
            "valuesIds": [
                "3766_14"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "64",
            "valuesIds": [
                "64_302409"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "22728",
            "valuesIds": [
                "22728_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "203509",
            "valuesIds": [
                "203509_217245"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "203105",
            "valuesIds": [
                "203105_215377"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "203089",
            "valuesIds": [
                "203089_4096"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "203097",
            "valuesIds": [
                "203097_215201"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>oferta testowa</p>"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "images": [],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "200",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 10,
        "unit": "UNIT"
    },
    "delivery": {
        "shippingRates": null,
        "handlingTime": "PT24H",
        "additionalInfo": null,
        "shipmentDate": null
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "additionalServices": null,
    "sizeTable": null,
    "promotion": {
        "emphasized": false,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "60-166"
    },
    "external": null,
    "attachments": [],
    "contact": null
}
```
W response, w polu validation.errors otrzymasz informację, które pola należy jeszcze uzupełnić, aby aktywować ofertę. Wypełnij je zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/).

> Skąd mam wziąć id oferty? Gdzie jest zapisane?

Po wystawieniu oferty otrzymasz informację na ten temat, numer znajduje się w adresie URL oraz w zakładce [Moje oferty](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty).

**Comment by arturpuck** [comment]
W polu response rzeczywiście otrzymałem informacje jakie należy uzupełnić i tak np. po uzupełnieniu shiping rates
`"delivery": {
        "shippingRates": {"id" : "1"},
        "handlingTime": "PT24H",
        "additionalInfo": null,
        "shipmentDate": null
    }`

Wyskakuje 

> Selected shipping rates does not exist

To jakie kryteria muszę spełnić aby to się zgadzało? Gdzie jest jakiś szczegółowy opis? W dokumentacji jest podane tylko   

> 

shippingRates | object (JustId)
-- | --
idstring | id | string
id | string

To jest naprawdę taki wielki problem podać jeden działający przykład?

**Comment by PrzemyslawLukanowski** [comment]
Każda oferta zawiera unikalne informacje powiązane z kontem sprzedającego, np.  informacje o gwarancjach, warunki reklamacji, polityka zwrotów lub właśnie cennik dostawy - dlatego nie ma uniwersalnego przykładu z uzupełnionymi wartościami dla tych pól, musisz to zrobić samodzielnie. Cennik dostawy dodasz przez zakładkę [ustawienia dostawy](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy) - jego id, które musisz przekazać w ofercie, pobierzesz za pomocą [GET sale/shipping-rates?seller.id={TwojSellerId}](https://developer.allegro.pl/documentation/#operation/getListOfShippingRatestUsingGET). Jak to zrobić przez API, opisaliśmy w [naszym poradniku](https://developer.allegro.pl/sale/#step-1).

**Comment by arturpuck** [comment]
`"parameters": [                             -- wymagane, parametry oferty, aktualne parametry 
                                                dostępne w danej kategorii 
                                                sprawdzisz za pomocą metody 
                                                GET na zasobie /sale/categories/{categoryId}/parameters
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        }`

Co to jest id, valuesIds i values?`

**Comment by PawelTaberski** [comment]
Przykładowy parametr np stan wygląda następująco:
```
        {
            "id": "11323",
            "name": "Stan",
            "type": "dictionary",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": true
            },
            "dictionary": [
                {
                    "id": "11323_1",
                    "value": "Nowy"
                },
                {
                    "id": "11323_2",
                    "value": "Używany"
                },
                {
                    "id": "11323_246510",
                    "value": "Nowy bez metki"
                },
                {
                    "id": "11323_246514",
                    "value": "Nowy z defektem"
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```
I tak jak widzisz id to numer parametru, dictionary.Id to dana wartość parametru, a values to jej słowny odpowiednik. Więcej na temat parametrów i ich rodzajów znajdziesz [tutaj.](https://developer.allegro.pl/sale/#parameters)
