### ISSUE TITLE
Jak pobrać koszt przesyłki dla wybranej rzeczy? Aktualne rozwiązanie nie działa.

### ISSUE THREAD

**Issue by forthewind** [allegro/allegro-api#2731]
W dokumentacji na stronie:
https://developer.allegro.pl/sale/#shipping-rates

Aby otrzymać koszt wysyłki jest metoda, w której jest błąd:

curl -X GET \ 
  'https://api.allegro.pl/sale/offers/8151913057/shipping-rates' \
  -H 'Accept: application/vnd.allegro.beta.v1+json’ 

Powinno być:

curl -X GET \
  'https://api.allegro.pl/sale/offers/8151913057/shipping-rates' \
  -H 'Accept: application/vnd.allegro.beta.v1+json'

Ale i tak nie działa. Nawet jak doda się parametr:

-H 'authorization: Bearer {TOKEN}'
  
To dalej nie działa. Proszę o odpowiedź jak pobrać za pomocą metody narzedzia curl koszt wysyłki dla wybranej rzeczy o np. identyfikatorze:

8681425444

Podsumując ja bym widział to w ten sposób:

curl -X GET \
  'https://api.allegro.pl/sale/offers/8681425444/shipping-rates' \
  -H 'Accept: application/vnd.allegro.beta.v1+json'

Z tym, że aktualnie to nie działa więc proszę to naprawić i napisać jak pobrać koszt przesyłki. Dziękuje za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to, zasób działa poprawnie. Otrzymujesz błąd, poniewaz nie jesteś zautoryzowany jako właściciel oferty 8151913057. Spróbuj wystawić ofertę przez front, ustaw przy tym wybrane metody dostawy (bez zdefiniowanego cennika dostawy), a następnie jeszcze raz odpytaj ten zasób - jako offerId przekaż numer oferty.

**Comment by forthewind** [comment]
A czy jest możliwość pobrania przez rest API allegro koszt wysyłki przedmiotu którego się nie wystawiło? Na zasadzie wrzucam do zapytania id oferty i w odpowiedzi otrzymuje koszty wysyłki dla przedmiotu którego nie jestem właścicielem? Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie. Aby korzystać z zasobu do sprawdzenia kosztów wysyłki, musisz być zautoryzowany jako sprzedawca, do którego należy oferta. W naszej [dokumentacji](https://developer.allegro.pl/documentation/) znajdzies zodpowiednie oznaczenia dla takich sytuacji, świadczy o tym oznaczenie bearer-token-for-user w polu authorization:
![Screenshot_11](https://user-images.githubusercontent.com/51473661/72523498-3b3b9d80-3860-11ea-9d71-2ca75940d157.png)
