### ISSUE TITLE
REST API - orderEvent.type FULFILLMENT_STATUS_CHANGED

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2732]
Witam,

Drogie Allegro, chciałbym się dowiedzieć, co to za nowy typ **FULFILLMENT_STATUS_CHANGED** przy przetwarzaniu dziennika zdarzeń zamówień?

GET order/events?from=1579161600697036 || trace-id:31e6d141ca0fff56

`
        +"checkoutForm": {#1212
          +"id": "03878792-3834-11ea-9980-3fbc568ff720"
        }
      }
      +"type": "FULFILLMENT_STATUS_CHANGED"
      +"occurredAt": "2020-01-16T07:49:08.121Z"
`

1. Nie ma go w dokumentacji
2. Nie ma go w swagger.yml
3. Nie widziałem zapowiedzi zmian

**Comment by PrzemyslawLukanowski** [comment]
Szczegóły znajdziesz już w naszym [newsie](https://github.com/allegro/allegro-api/issues/2733), przepraszamy za drobny poślizg w publikacji komunikatu.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski dziękuję, byłbym bardzo wdzięczny gdyby informacje takie pojawiały się przynajmniej 5 dni roboczych przed.

**Comment by PrzemyslawLukanowski** [comment]
Ponieważ jest to zmiana kompatybilna wstecz, tak jak w przypadku komunikatów o innych nowych eventach, opublikowaliśmy komunikat wraz z wdrożeniem funkcjonalności.

**Comment by barthoos** [comment]
> Ponieważ jest to zmiana kompatybilna wstecz, tak jak w przypadku komunikatów o innych nowych eventach, opublikowaliśmy komunikat wraz z wdrożeniem funkcjonalności.

Zdecydowanie nie byla to zmiana kompatybilna wstecz. Mam dziennik utrzymywany tak, ze przechowuje tylko ostatnie zdarzenie w lancuszku. (BOUGHT > FILLED IN > READY_FOR_PROCESSING). Dzieki temu w SQL join'uje sie z dziennikiem 1:1. Wprowadzenie nowego typu zdarzenia sprawilo, ze zaczalem pokazywac duplikaty na froncie.

Takze prosba na przyszlosc - nie zakladajcie, ze cos jest kompatybilne wstecz, jak de facto nie jest.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za opis, weźmiemy to pod uwagę w przypadku wdrażania nowych typów eventu w przyszłości.

**Comment by pkrzemo** [comment]
@barthoos : IMHO Masz coś nie tak z logiką aplikacji...
Dziennik zdarzeń powinien tylko wskazywać moment w którym powinieneś zaktualizować dane zamówienia (checkoutForm). Nie ma sensu "joinować" cały czas zamówień z eventami, a nawet jeśli to robisz to i tak musisz eliminować duplikaty, bo np.  FILLED IN może się pojawić kilka razy...

**Comment by Onixarts** [comment]
U nas tylko klienci otrzymują tysiące warningów przez ten nowy status, a tak to stabilnie...
