### ISSUE TITLE
Przewidywany czas dostawy w REST API 

### ISSUE THREAD

**Issue by kamil-lewandowski** [allegro/allegro-api#2734]
Witam,

Czy istnieje możliwość pobrania przewidywanego czasu dostawy dla konkretnego zamówienia, który uwzględnia weekendy, święta i urlopy sprzedających poprzez REST API?
Taka funkcjonalność bardzo by się przydała i  jeżeli nie ma takiej możliwości, to czy będzie w przyszłości dostępna?

Pozdrawiam

**Comment by PatrykBocian** [comment]
Nie posiadamy takiego zasobu w API. Przekazałem twoją sugestie do odpowiedniego zespołu - jeśli zdecydujemy się na wprowadzenie takiej funkcjonalności to poinformujemy o tym w odpowiednim komunikacie.

**Comment by tomasz-grzesik** [comment]
Prosiłbym o dodanie - przewidywanego czasu dostawy. Potrzebne chociażby do przekazania takiej informacji na chacie prowadzonym przez AI.

**Comment by Lukasz-Zurek** [comment]
@tomasz-grzesik Swego czasu udostępniliśmy czas dostawy i wysyłki w ramach nowego pola **“delivery.time”** w zamówieniach - wspominaliśmy o tym w [tym newsie](https://developer.allegro.pl/news/zamowienia-wprowadzimy-czas-dostawy-i-wysylki-wwemeokPzF1). Nie wiem jednak czy taka funkcjonalność jest dla Ciebie wystarczająca. Ewentualnie jak moglibyśmy usprawnić to pole - tu ewentualnie zachęcam do przesłania propozycji na [Discussions](https://github.com/allegro/allegro-api/discussions), by nie umknęło uwadze innym :)

**Comment by tomasz-grzesik** [comment]
Dziękuję za informację. Zobaczę jak w praktyce sprawdza się to pole i ewentulanie dam znać.
