### ISSUE TITLE
Offers listing 503 - service unavailable

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2736]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Przy request:
GET "https://api.allegro.pl/offers/listing?category.id=79168&include=-all&include=filters&include=searchMeta"

Dostaję zwrotkę:
"failed because response status code does not indicate success: 503 (Service Unavailable)."

I tak kilka razy. Czekam jakiś czas i nagle jest wszystko ok dostaję prawidłową odpowiedź. Czym to może być spowodowane? Przy wysokiej ilości requestów powinienem dostać 429, a jednak jest 503.

**Comment by PrzemyslawLukanowski** [comment]
Czy problem w Twoim przypadku dalej występuje? Zweryfikowaliśmy ostatnie logi i udział błędów tego typu w skali całości jest minimalny. Powtórzyłem również Twoje wywołanie i w żadnym przypadku nie otrzymałem błędu 503.

**Comment by artzie92** [comment]
Takie wystąpiły - czasy UTC:
2020-01-16 12:20:36.977 - https://api.allegro.pl/offers/listing?category.id=260051&include=-all&include=filters&include=searchMeta
2020-01-16 12:20:37.223 - https://api.allegro.pl/offers/listing?category.id=260050&parameter.11323=11323_1&sort=-popularity&limit=100&sellingMode.format=BUY_NOW
2020-01-16 13:24:21.023 - https://api.allegro.pl/offers/listing?category.id=115273&include=-all&include=filters&include=searchMeta
2020-01-16 13:24:24.050 - https://api.allegro.pl/offers/listing?category.id=115272&include=-all&include=filters&include=searchMeta

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję precyzyjne dane, zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by artzie92** [comment]
Ok dzięki. Ogólnie co jakiś czas lecą kolejne i nie ma na to reguły.


2020-01-17 10:27:54.413
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=114768&sort=-popularity&limit=100&sellingMode.format=BUY_NOW" failed because response status code does not indicate success: 503 (Service Unavailable).

2020-01-17 10:37:52.350
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=116745&include=-all&include=filters&include=searchMeta" failed because response status code does not indicate success: 503 (Service Unavailable).


2020-01-17 10:57:51.620
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=28413&parameter.11323=11323_1&sort=-popularity&limit=100&sellingMode.format=BUY_NOW" failed because response status code does not indicate success: 503 (Service Unavailable).


2020-01-17 11:04:12.487
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=258690&include=-all&include=filters&include=searchMeta" failed because response status code does not indicate success: 503 (Service Unavailable).
   
   
2020-01-17 11:04:12.780
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=258683&parameter.11323=11323_1&sort=-popularity&limit=100&sellingMode.format=BUY_NOW" failed because response status code does not indicate success: 503 (Service Unavailable).
  
  
2020-01-17 11:04:13.357
RestEase.ApiException: GET "https://api.allegro.pl/offers/listing?category.id=258688&parameter.11323=11323_238062&sort=-popularity&limit=100&sellingMode.format=BUY_NOW" failed because response status code does not indicate success: 503 (Service Unavailable).

**Comment by PrzemyslawLukanowski** [comment]
Dzięki, przekazuję logi do zgłoszenia.
