### ISSUE TITLE
Problem z ostatnimi zamówieniami

### ISSUE THREAD

**Issue by ddaapp** [allegro/allegro-api#2738]
Występuje problem: z ostatnimi zamówieniami na allegro. Nie wyświetlają się w API. Wyświetlają się tylko starsze

**Comment by arolznov** [comment]
U mnie też problem występuje. Nowe zamówienia (po 13:10 16.01.2020) nie są zwracane przez zasoby /order/events oraz /order/checkout-forms

**Comment by MaciejFrackowiak** [comment]
@ddaapp @arolznov Czy możecie podać przykładowe id zamówienia, które nie jest widoczne w API?

**Comment by arolznov** [comment]
da716ca9-385a-11ea-aedb-af41b8f8db9f
068493c2-385c-11ea-9852-9382b54aa877

**Comment by MaciejFrackowiak** [comment]
@arolznov Dziękuję za przykłady. 

Rzeczywiście, pojawiło się opóźnienie w przetwarzaniu zdarzeń - nadrabiamy już zaległości, przepraszamy za niedogodności.

**Comment by mojosoft** [comment]
U nas obecnie API zwraca te informacje z opóźnieniem około 30 minutowym

**Comment by mapsi-fixi** [comment]
Problem nadal występuje

**Comment by PrzemyslawLukanowski** [comment]
@mapsi-fixi Czy możesz podać przykładowe numery zamówień, których nie widzisz przez API?

**Comment by mapsi-fixi** [comment]
np takie
d65b6930-389c-11ea-b3a1-8784b55d1505
016e4d70-3895-11ea-b3a1-8784b55d1505

**Comment by PrzemyslawLukanowski** [comment]
@mapsi-fixi Rozumiem, że sytuacja dotyczy sandboxa? Sprawdziłem to i rzeczywiście API nie zwraca danych, o których piszesz. Weryfikujemy ten temat.

**Comment by PrzemyslawLukanowski** [comment]
@mapsi-fixi Usunęliśmy usterkę, zasoby zwracają już komplet danych. Prosiłbym w przyszłości o wzmiankę, że błąd dotyczy sandboxa, dzięki temu szybciej uda nam się rozwiązać problem.

**Comment by kregielpl** [comment]
@PrzemyslawLukanowski Problem z sandboxem dalej występuję. Proszę o sprawdzenie np. zamówienia:
e7f8e8c1-3b85-11ea-b3a1-8784b55d1505

**Comment by PrzemyslawLukanowski** [comment]
@kregielpl Zasób działa prawidłowo. zweryfikowałem to - udało mi sie pobrać powyższe zamówienie.  Podaj proszę trace-id dla wywołań, gdzie nie znajduje Twoich zamówień. Jaki otrzymujesz komunikat?

**Comment by kregielpl** [comment]
@PrzemyslawLukanowski Teraz sandbox poprawnie zwraca listę zamówień.

**Comment by manhunto** [comment]
Od godziny 2020-01-21 13:04:30  nie otrzymuje nowych eventów. Czy aktualnie występuje jakiś problem z tymi danymi?

Ostatni event jaki dostałem to 1579608493505290 (id zamówienia b381ce22-3c45-11ea-abce-cf39aa2d4a9c)
Środowisko produkcyjne.

**Comment by PrzemyslawLukanowski** [comment]
@manhunto Sprawdziłem to i ostatni event, jaki otrzymałem to 1579613669250252 z 13:34. Wygląda na to, że zasób działa poprawnie. Prośba o ponowną weryfikację z Twojej strony.
