### ISSUE TITLE
Opłaty allegro/prowizja od sprzedaży

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2739]
Czy jest metoda na pobranie wysokości % prowizji dla wybranej kategorii?
W sposób widoczny na 
[https://allegro.pl/regulamin/pl/zalacznik-4](https://allegro.pl/regulamin/pl/zalacznik-4)
 Część III. Prowizje od sprzedaży

Jeśli nie czy planujecie cos w tym kierunku?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy i nie planujemy takiego zasobu. Za pomocą [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) możesz sprawdzić prowizję dla danej oferty.

**Comment by fabianpodlecki** [comment]
Witam, jeszcze nie znalazłem takich informacji stąd moje pytanie: prowizja jest zwracana netto czy brutto?

**Comment by PrzemyslawLukanowski** [comment]
Zwracamy kwotę brutto.

**Comment by fabianpodlecki** [comment]
Świetnie, rozumiem że kwota zwracana przez metodę pricing/fee-preview jest kwotą brutto czyli tą samą która wystąpi na fakturze i ma już naliczony podatek VAT?

**Comment by PrzemyslawLukanowski** [comment]
Tak, to są kwoty brutto, chybam że Partner jest zagraniczny. Wtedy na jego fakturze pojawi się korekta związana z inną stawką VAT poza Polską.
