### ISSUE TITLE
Offer Management - Jak to robicie

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2741]
Jeśli można chciałbym podpytać jak rozwiązujecie problem, że metody do zarządzania ofertami działają asynchronicznie a informacja o tym czy dana operacja się udała jest dostępna dopiero po jakimś czasie, bywa, że jest to kilka, kilkanaście minut? Przecież nie mogę kazać użytkownikowi czekać kilkanaście minut, żeby się upewnił, czy operacja, którą zrobił się udała?
Każdą jedną operację zapisywać do bazy czy co?

**Comment by partyumarty** [comment]
Tak, musisz zapisywać UID, a userowi dać komunikat, że zlecono. W tle pracuje cron, który odpytuje o status i jak jest OK - uzupełnia przy danej operacji te informacji. Potem userowi wyświetlasz w odpowiednim miejscu raporty albo tylko informacje o niepowodzeniach... Inaczej tego nie zrobisz, bo jak sam zauważyłeś, czasem to trwa nawet kilkanaście minut :(

**Comment by lukada4100** [comment]
Żeby tylko UID, trzeba zapisywać jeszcze czego to UID dotyczyło...
