### ISSUE TITLE
dziennik zwraca losowe puste rekordy REST API order/events

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#2742]
Występuje problem: 
 - [X] z zasobem REST API

:beetle: **Opis**
Zasób order/events, czyli dziennik sporadycznie, co jakieś czas zrwca kwiatki w postaci danych, w których brakuje id usera i maila. Niby nic strasznego, ale biorąc pod uwagę, że nasz system updejtuje dane Klientów, to trochę trwało ustalenie dlaczego nagle mamy zamówienie z pustymi danymi. Otóż dziennik zapodał id usera 0. Najgorsze jest to, że skrypt w kolejnym kroku po odczytaniu nowego rekordu robi to co powinien, czyli odpytuje order/checkout-forms/ i tam też dostaliśmy pustą tablicę z danymi Klienta. Tym samym - ponieważ było to ostatnie odpytanie, bo już ze statusem READY_FOR_PROCESSING wyzerował nam dane klienta w bazie i mamy zamówienie widmo. Poniże screen co zwracał dziennik kolejno. Rekordy z krzyżykiem to jedno zamówienie. W kolumnie occuredAt jest data zdarzenia z dziennika, a kolumna "kiedy" wskazuje czas, w którym Wasz serwer zwrócił nam takie kwiatki. 
![dziennik](https://user-images.githubusercontent.com/38914331/72563931-fbe86d80-38ae-11ea-81fb-a056d6b764b7.jpg)

Zasadniczo nie ma wielkiej tragedii, bo wiedząc, że możecie nam zwrócić zera dorabiam właśnie ifa, zeby nie udpatować klienta jak jest zero w ID, ale sam fakt - coś jest nie tak :(

p.s. po wykryciu błędu, gdy odpytuje kolejny raz o ten sam formularz dane w nim są już poprawne... ich po prostu nie było o godzinie 22:01:03. W logach katalogu klientów, mamy dodanie rekordu z danymi o 22:00:02 - wtedy był komplet informacji i Panu Ziembickim, po czym o 22:01:03 dostaliśmy pustą tablice, a w dzienniku kwiatek jak na screenie :(

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem logi dla eventów, które zwróciły buyer.id=0, każdy z nich zawiera prawidłową wartość w tym polu. W przypadku, gdyby problem pojawił się ponownie, proszę o informację w tym wątku, będziemy weryfikować jakie dane zwraca nasze API.
