### ISSUE TITLE
[x] opóźnienie przy zwracaniu paczek z zamówieniami które są opłacone !!! 

### ISSUE THREAD

**Issue by Wezyr666** [allegro/allegro-api#2743]
[x]
:beetle: **Opis**
**pytanie mam czy przy zwracaniu paczek z zamówieniami nie macie opóźnienia i to dużego, korzystam z WAPRO AUKCJE  i po godz 13tej cisza żadne opłacone zamówienie nie wchodzi, odświeżanie tokenów nie pomaga, jeśli tak kiedy zamierzacie zoptymalizować spływanie zamówień po całkowitym wyłączeniu starego api 13-go ze spływaniem zamówień normalnie dramat w cały świat to chodzi a synchro mamy co 15minut a zamówienia są zwracane albo po kilku godzinach albo po godzinie,po kontakcie z programistami nie dowiedziałem się nic, nie mają od was żadnych informacji na temat opóźnień**

**Comment by PrzemyslawLukanowski** [comment]
Opóźnienia wystąpiły wczoraj w okolicach godziny 13:00, szczegóły znajdziesz w wątku #2738. Aktualnie problem nie występuje. Jeżeli w dalszym ciągu nie widzisz jakichś zamówień w swoim oprogramowaniu, podaj proszę przykładowe id, będziemy weryfikować dane, jakie zwraca API.

**Comment by Wezyr666** [comment]
Ok dzięki za odpowiedź będziemy monitorować na bieżąco w razie czego wkleję nr zamówień jeśli będzie potrzeba z wczoraj popołudniu zamówienia dopiero weszły UWAGA RANO DZISIAJ masakra normalnie a synchro co 15min

**Comment by Wezyr666** [comment]
nie weszło mi zamówienie : 13cb2ef2-3919-11ea-b740-5f347debe724
możecie to sprawdzić no 15min a 1,5h to troszkę różnicy ;-)

dzwonilismy do programistów wapro aukcje nie mają zgłoszen od użytkowników że coś nie działa ani od was żadnego kontaktu
bardzo proszę o pomoc, dzieje się tak od poniedziałku 13-go działamy oczywiscie na nowym API
podaję nasze id allegro: bejbis83  , zabawkropeczka , kraina_plastusia

**Comment by PawelTaberski** [comment]
@Wezyr666 napisz mi tylko jeszcze proszę, do którego z tych sellerów należy do zamówienie.

**Comment by Wezyr666** [comment]
zabawkropeczka

a tu jeszcze kolejne też nie wchodzi:  14dd9712-391e-11ea-8333-d1f95e797c51

**Comment by Wezyr666** [comment]
i jeszcze zauważyłem co jakiś czas podczas synchronizacji api zwraca błąd " 
Analiza kodu XML: wiersz 1, znak 249, nielegalny znak w kodzie XML.
na pewno to nie jest po stronie wapro aukcje, synchronizują się ilości i zamykają aukcje jedynie transakcje nie wchodzą lub bardzo bardzo długo

**Comment by PawelTaberski** [comment]
Sprawdziłem i te zamówienie poprawnie pobiera się zasobem GET /order/checkout-forms/{id}. Jednakże czy Twoje oprogramowanie korzysta już z RestAPI? Bo w poniedziałek wygasiliśmy zgodnie z zapowiedzią zasoby do zarządzania zamówieniami po WebAPI #2716 . Godzina od jakiej widzisz problemy zgadzałaby się z wygaszeniem.

**Comment by Wezyr666** [comment]
Tak korzysta zaktualizowalismy w poniedziałek z rana samego

⁣Pobierz aplikację BlueMail dla systemu Android ​

W dniu 17.01.2020, 15:39, o 15:39, użytkownik PawelTaberski <notifications@github.com> napisał:

**Comment by Wezyr666** [comment]
napisałem do programistów wapro żeby jeszcze raz to sprawdzili a co może oznaczać ten błąd który zwraca api ?? Analiza kodu XML: wiersz 1, znak 249, nielegalny znak w kodzie XML.
pod koniec sychronizacji programowej lub jak mam uruchomiona usługę synchronizacyjną w usługach windowsa (można wybierać miedzy tymi dwoma sposobami synchronizacji) a pracujemy na serwer sql standard

**Comment by PawelTaberski** [comment]
Przetestowałem i po naszej stronie wygląda, że dla tych zamówień wszystko działa prawidłowo. Prosiłbym o podesłanie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) pełnego requesta i responsa w formacie JSON, w którym występuje problem.  W zgłoszeniu proszę dodać, że dane są potrzebne do ticketa z GitHuba numer 2743. Sprawdzimy to.
