### ISSUE TITLE
Stany magazynowe - błędy

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2744]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Cześć,
Proszę o weryfikację aktualizacji stanów magazynowych:

Pierwszy przypadek:
{"Zlecenie":{"Nr":"9f20e69e-61ee-4fd9-ab2c-02b90b2cb14b","Operacja":{"Modification":{"ChangeType":"**FIXED","Value":65**},"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"7307182585"}]}]},"Response":{"Data":{"Id":"9f20e69e-61ee-4fd9-ab2c-02b90b2cb14b","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"830adabd57b81867","Error":false,"StatusCode":201,"Message":null}}}
{"RaportZlecenia":{"Nr":"13e8f3d7-e514-40f6-95c9-e91de27cbe0c","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-01-16T15:23:52.62Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"7307182585"},"ScheduledAt":"2020-01-16T15:23:44.012Z","Status":"FAIL","Errors":[{"Code":"ERR_INVALID_QUANTITY","Details":null,"Message":"ERR_INVALID_QUANTITY","Path":null,"UserMessage":"Nieprawidłowa liczba sztuk."}]}]},"Validation":null,"Exception":null,"TraceId":"5254df60f4e8f323","Error":false,"StatusCode":200,"Message":null}}}

Stan w API na aukcji, właściwość: Stock.available: **-81**, jak to możliwe że jest ujemny stan?

Drugi przypadek:
{"Zlecenie":{"Nr":"99428904-7c1e-419d-9da1-24a89c0ad9c8","Operacja":{"Modification":{"ChangeType":**"FIXED","Value":2**},"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"7920097402"}]}]},"Response":{"Data":{"Id":"99428904-7c1e-419d-9da1-24a89c0ad9c8","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"ca5393c52affdd83","Error":false,"StatusCode":201,"Message":null}}}
{"RaportZlecenia":{"Nr":"99428904-7c1e-419d-9da1-24a89c0ad9c8","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-01-16T15:38:14.699Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"7920097402"},"ScheduledAt":"2020-01-16T15:38:14.16Z","Status":"FAIL","Errors":[{"Code":"ERR_INVALID_QUANTITY","Details":null,"Message":"ERR_INVALID_QUANTITY","Path":null,"UserMessage":"Nieprawidłowa liczba sztuk."}]}]},"Validation":null,"Exception":null,"TraceId":"cc53548176ae462f","Error":false,"StatusCode":200,"Message":null}}}

Stan w API na aukcji, właściwość: Stock.available: **1**

Trzeci przypadek:
{"Zlecenie":{"Nr":"bf9666ad-fcc0-453a-b441-2e78ea0c5f09","Operacja":{"Modification":{"ChangeType":**"FIXED","Value":2**},"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"7920280333"}]}]},"Response":{"Data":{"Id":"bf9666ad-fcc0-453a-b441-2e78ea0c5f09","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"a7c579cc3d2dd4e5","Error":false,"StatusCode":201,"Message":null}}}
{"RaportZlecenia":{"Nr":"bf9666ad-fcc0-453a-b441-2e78ea0c5f09","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-01-16T15:38:14.814Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"7920280333"},"ScheduledAt":"2020-01-16T15:38:14.191Z","Status":"FAIL","Errors":[{"Code":"ERR_INVALID_QUANTITY","Details":null,"Message":"ERR_INVALID_QUANTITY","Path":null,"UserMessage":"Nieprawidłowa liczba sztuk."}]}]},"Validation":null,"Exception":null,"TraceId":"21da2a4620cb5ea3","Error":false,"StatusCode":200,"Message":null}}}

Stan w API na aukcji, właściwość: Stock.available: **1**

Dzięki :)

**Comment by PatrykBocian** [comment]
Zweryfikowałem twoje zgłoszenie - rzeczywiście wystąpił tu błąd. Przekazałem to do odpowiedniego zespołu.

**Comment by SebastianOzdoba** [comment]
@PatrykBocian  jeszcze jeden przypadek

{"Zlecenie":{"Nr":"95bb78ad-5648-4be2-9586-d9d4d9e3329c","Operacja":{"Modification":{"ChangeType":"FIXED","Value":3},"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"7873827251"}]}]},"Response":{"Data":{"Id":"95bb78ad-5648-4be2-9586-d9d4d9e3329c","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"fcc92aad73947742","Error":false,"StatusCode":201,"Message":null}}}
{"RaportZlecenia":{"Nr":"95bb78ad-5648-4be2-9586-d9d4d9e3329c","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-01-21T07:40:28.818Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"7873827251"},"ScheduledAt":"2020-01-21T07:40:17.837Z","Status":"FAIL","Errors":[{"Code":"ERR_INVALID_QUANTITY","Details":null,"Message":"ERR_INVALID_QUANTITY","Path":null,"UserMessage":"Nieprawidłowa liczba sztuk."}]}]},"Validation":null,"Exception":null,"TraceId":"50a664de15ba7c71","Error":false,"StatusCode":200,"Message":null}}}

**Comment by PatrykBocian** [comment]
Dziękuje, dodałem to do zgłoszenia.
