### ISSUE TITLE
REST API okresowe problemy z połączeniem

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#2745]
Witam,

Mam skrypt PHP, który działa według następującego schematu:

1. Sprawdzam czy access token jest aktualny, jeżeli nie to odświeżam go za pomocą /auth/oauth/token?grant_type=refresh_token.
2. Pobranie ostatniego eventu poprzez zasób /order/event-stats - pobrany event zapisuję do bazy.
3. Odpytuję zasób /order/events i pobieram eventy typu READY_FOR_PROCESSING.
4. Na ich podstawie pobieram szczegóły zamówienia poprzez /order/checkout-forms/CHECKOUT_FORM_ID i na jego podstawie tworzę zamówienie w swojej  bazie danych.

Skrypt ten odpalany jest za pomocą crona co 5 minut. Generalnie wszystko działa prawidłowe, ale zdarzają się przerwy w połączeniu z REST API - dostaję błąd: invalid_token "Access token expired". Przykład jak działało połączenie w dniach 16.01.2020 - 17.01.2020:

16.01. 16:00 - 20:00 OK
16.01. 20:00 - 21:00 invalid_token
16.01. 21:00 - 00:00 OK
17.01. 00:00 - 01:00 invalid_token
17.01. 01:00 - 10:00 OK
17.01. 10:00 - 11:00 invalid_token
17.01. 11:00 - obecnie OK

Zastanawia mnie dlaczego w godzinach 20:00 - 21:00 oraz 00:00 - 01:00, nie udało się odświeżyć access tokena, natomiast o 21:05 i 01:05 już tak, bo skrypt zwracał brak nowych eventów lub pobierał zamówienia jeżeli się one pojawiły? Z tego co wiem, klient nie odświeżał ręcznie access tokenów w panelu administratora sklepu. Problem dotyczy dwóch kont, poniżej podaję ich loginy:

1. AGD-MASTERS
2. wyprzedazepl

Z góry dziękuję za pomoc.

**Comment by PatrykBocian** [comment]
Podeślij proszę pełny **request i response** w przypadkach kiedy dostałeś **invalid_token**. Pomoże nam to zweryfikować twoje zgłoszenie. Ze względów bezpieczeństwa, prześlij to przez formularz kontaktowy. W zgłoszeniu dopisz **#2745**.

**Comment by AlpanetPL** [comment]
Requesty zostały wysłane przez formularz kontaktowy.

**Comment by arcziii** [comment]
Ja natomiast mam problem z aplikacją, która również zwraca invalid_token z wiadomością **Cannot convert access token to JSON** po 12 godzinach - utracie ważności tokena, wcześniej otrzymywałem wiadomość **Access token expired** po której sobie odświeżałem token. Proszę o informację czy jest to problem globalny gdyż w moim przypadku problem pojawił się z dnia na dzień.

**Comment by PrzemyslawLukanowski** [comment]
@AlpanetPL Zweryfikowaliśmy Twoje logi. Pierwsze co rzuca się w oczy, to różnica czasu, w Twoim przypadku czas jest cofnięty o ok. 55 minut. Same requesty po przeanalizowaniu wyglądają następująco:

1) 10:20 - używasz refresh tokena, w odpowiedzi otrzymujesz nową parę, stare tokeny tracą ważność.
10:30 - próbujesz odpytać zasób GET /order/events, jednak używasz w tym celu starego access tokena, który przez odświeżenie o 10:20 jest już nieważny.

2) 10:16:02 - otrzymujesz parę access i refresh token.
10:17:01 - od razu używasz refresh tokena, stare tokeny tracą ważność, w odpowiedzi dostajesz nowe.
10:18:36 - próbujesz odświeżyć token za pomocą refresha z 10:16, który w tej chwili jest już nieważny.

3) podobnie jak przypadek wyżej,
10:20:02 - otrzymujesz parę access i refresh token.
10:21:01 - od razu używasz refresh tokena, stare tokeny tracą ważność, w odpowiedzi dostajesz nowe.
10:21:37 - próbujesz odświeżyć token za pomocą refresha z 10:20, który w tej chwili jest już nieważny.

Prośba o zweryfikowanie działania mechanizmu po swojej stronie, na podstawie logów widać nieprawidłowe działanie.

@arcziii Prześlij nam proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Przeanalizujemy to i wrócimy z odpowiedzią. W zgłoszeniu dopisz GitHub #2745.

**Comment by AlpanetPL** [comment]
@PrzemyslawLukanowski dziękuję za analizę problemów i pomoc. Wygląda na to, że faktycznie problem był po naszej stronie - w związku ze wcześniejszymi implementacjami REST API, w tle cyklicznie działał skrypt to przedłużania access tokenów, co jakiś czas uruchamiał się on w tym samym czasie co skrypt do pobierania zamówień.
