### ISSUE TITLE
Kolejność sortowania ofert - offers/listing

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2746]
Witam,
Mam pytanie odnośnie sortowania ofert w zasobie offers/listing. 

Przykładowo mam takie zapytanie
https://api.allegro.pl/offers/listing?category.id=257550&parameter.11323=11323_1&sort=-popularity&limit=100&sellingMode.format=BUY_NOW

Czyli pobieram 100 ofert, których popularność jest posortowana malejąco. Co kiedy te 100 ofert ma parameter popularity wynoszący 0. 
W jaki sposób sortowane są oferty dla danej kategorii? Datą utworzenia, datą do zakończenia, według relevance? 
Jeżeli według relevance to w jaki sposób to działa?

Pozdrawiam

**Comment by PatrykBocian** [comment]
W przypadku sortowania po popularności - jeśli popularność ma tą samą wartość to sortujemy po czasie zakończenia oferty (czyli najnowsze oferty najwyżej).

Więcej informacji na ten temat możesz znaleźć w tym [poradniku](https://allegro.pl/pomoc/dla-kupujacych/wyszukiwanie-i-obserwowanie/jak-korzystac-z-wyszukiwarki-i-znalezc-przedmiot-mGwAg2jRrU7).
