### ISSUE TITLE
Pobranie Id płatności

### ISSUE THREAD

**Issue by MarekCiecharowski** [allegro/allegro-api#2747]
W jaki sposób, przy użyciu REST API, pobrać id płatności, mając id transakcji?
W załączniku zrzut ekranu - oznaczyłem na nim id transakcji (które posiadam) i id płatności (które muszę uzyskać).

![1](https://user-images.githubusercontent.com/57184341/72667911-2a865580-3a21-11ea-8fc1-352a8c3e7d5b.png)

**Comment by PatrykBocian** [comment]
W tym celu skorzystaj z tego zasobu - [GET /payments/payment-id-mappings](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping). Opis zasobu znajdziesz w tym [wątku](https://github.com/allegro/allegro-api/issues/1878).

**Comment by MarekCiecharowski** [comment]
Nie działa, podaje transactionId i dostaje błąd: "Transaction not found for paymentId=".
Moje wywołanie:
            UriBuilder builder = new UriBuilder($"{API_LINK}payments/payment-id-mappings");
            var paramValues = HttpUtility.ParseQueryString(builder.Query);
            paramValues.Add("transactionId", doc.Id);
            builder.Query = paramValues.ToString();
            var json = await GetRequestAndParseAsync(builder.Uri);

**Comment by PatrykBocian** [comment]
Zweryfikowałem Twój przypadek, przesyłam zmapowane **transactionId** (1151603353) na **paymentId** -  e23b1b12-388d-11ea-9f0f-2b135ef65782. Najprawdopodobniej użyłeś nieprawidłowego numeru **transactionId** - w moim przypadku przesłałem to, co na załączonym obrazku z NMSa widnieje jako "**płatność**".

**Comment by MarekCiecharowski** [comment]
Przepraszam, chyba źle to opisałem:
1. Posiadam to co jest na górze obrazka, czyli "Karta transakcji nr 73704252"
2. Potrzebuje uzyskać za pomocą API to co na dole obrazka, czyli płatność 1151603353

**Comment by PatrykBocian** [comment]
Karta transakcji jest przypisana do **Menedżera Sprzedaży** - nie jest on powiązany z API. Dlatego nie ma możliwości mapowania ID płatności na kartę transakcji.

**Comment by MarekCiecharowski** [comment]
Ok, rozumiem.
To od innej strony: pobieram wszystkie płatności dla danego loginu za pomocą payments/payment-operations: https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory

Jako parametr muszę podać login klienta (participant.login).  Tylko nie zawsze klient jest zarejestrowany na allegro, tzn. mam jego email a nie mam loginu. Czy można pobrać wszystkie płatności przypisane do danego emaila?

**Comment by PatrykBocian** [comment]
Nie ma takiej możliwości - nie możesz pobrać takich informacji na podstawie maila.
