### ISSUE TITLE
Płatności opłacone mają cały czas status rozpoczęta

### ISSUE THREAD

**Issue by klagowski** [allegro/allegro-api#2748]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Płatności opłacone mają cały czas status rozpoczęta, nie zmienia im się status na zakończona.

Przykład płatności:
f6fa4812-3ae9-11ea-b9d6-89bb6a711015

**Comment by PatrykBocian** [comment]
Zweryfikowałem twoje zgłoszenie - obecnie Sandbox funkcjonuje prawidłowo. Czy problem jeszcze u Ciebie występuje?

**Comment by klagowski** [comment]
Już działa prawidłowo.

**Comment by AssAssIn1909** [comment]
Witam,
Problem znowu występuje.
Przykładowa płatność: 2c7886e2-3db6-11ea-9159-f1cd505eda37

**Comment by PatrykBocian** [comment]
@AssAssIn1909 Na tę chwilę Sandbox działa prawidłowo - prześlij proszę swój user.id (powiązany ztą płatnością), pomoże to zweryfikować ten problem.
