### ISSUE TITLE
GET /payments/payment-id-mappings - brak mapowań

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#2749]
Mam problem z tym zasobem, dla pewnych paymentId nie mam mapowań na transactionId.
Przykładowe paymentId bez mapowań:
14e553f3-3afa-11ea-9105-071eede14ac2
69a62752-3ac0-11ea-99e3-252f137e61fd
c7c7c9b4-37e1-11ea-99e3-252f137e61fd

Czym to jest spowodowane?

**Comment by PatrykBocian** [comment]
Upewnij się proszę, czy korzystasz z tokena usera do którego przypisana jest płatność - widzę, że dostajesz w response błąd o statusie 404.

**Comment by mindc** [comment]
@PatrykBocian 
tak, upewniłem się...

**Comment by PatrykBocian** [comment]
Płatności, które podesłałeś zostały anulowane -  dlatego dostajesz status 404 (nie odnajduje takich płatności).
