### ISSUE TITLE
Redirect URI mismatch - problem z autoryzacja RestAPI

### ISSUE THREAD

**Issue by MajkelPl55453** [allegro/allegro-api#275]
Witam.
Na początku wspomnę, że narazie testuję tylko integrację na sandboxie. 
Wygenerowałem sobie dane aplikacji w panelu developerskim. Kod autoryzujący zwraca mi poprawnie. Następnie od razu moja aplikacja zgłasza się do sandboxa o token. W tym momencie otrzymuję taką odpowiedź w json:
`{
"error": "invalid_grant",
"error_description": "Redirect URI mismatch."
}`
Podczas wywoływania tego adresu: `https://allegro.pl.allegrosandbox.pl/auth/oauth/token` z parametrami 
`{
"grant_type": "authorization_code",
"code": "73gjOqJlwKQ9v16N6M4EOCp3YbuZSiyX",
"redirect_uri": "https://www.ukrytyadres.pl"
}`
oraz headerem `Autorization: Basic OTJ...w==`
Jeżeli chodzi o Redirect URIs to jest ustawiony https://www.ukrytyadres.pl (czyli taki sam jak w requescie)

Co może być problemem?

**Comment by MartaNowaczyk** [comment]
Na początek jeśli masz możliwość, zarejestruj apkę i sprawdź autoryzację na innym Redirect URI. Jeśli problemy będą nadal występować daj znać.

**Comment by MajkelPl55453** [comment]
Zrejestrowałem kilka nowych aplikacji, za bardzo zmienić nie mogłem adresu Redirect URI, pokombinowałem z http/https, www oraz z / na końcu adresu ale nic to nie dało, nadal ten sam błąd.

**Comment by MartaNowaczyk** [comment]
@MajkelPl55453 podaj proszę swój client_id z [Developer Apps](https://apps.developer.allegro.pl/). Najlepiej ten z pierwszej próby.

**Comment by MajkelPl55453** [comment]
Proszę oto mój client_id: 92f55618053843e4b6621d7a875ce5af

**Comment by jakubmaguza** [comment]
Zwróć uwagę, czy nie masz slasha na końcu. Miałem podobny problem, gdy w jednym requeście przekazywałem www.test.pl/ a w drugim www.test.pl.

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i dla podanego client_id zarejestrowany redirect_uri to https://www.beta.apollo.pl. Czy z tego adresu korzystasz?

**Comment by MajkelPl55453** [comment]
Tak z tego adresu korzystam, ponieważ to jest nasze środowisko testowe. Jeżeli chodzi o / na końcu adresu to utworzyłem sobie drugą aplikację w które adres powrotu był z / na końcu a i tak otrzymywałem ten sam błąd

**Comment by MartaNowaczyk** [comment]
Sprawdź jeszcze to dokładnie, bo masz złego redirecta ustawionego - w aplikacji masz innego i w kliencie innego. W obu podaj redirect_uri=https://www.beta.apollo.pl

**Comment by MajkelPl55453** [comment]
Teraz nawet ręcznie w kodzie ustawiłem redirect na https://www.beta.apollo.pl i nic to nie dało. Użyłem tego client_id co podałem wyżej. Przesyłam także plik z logiem ostatniego wykonanego zapytania czyli endpoint, request oraz response
[allegro.txt](https://github.com/allegro/allegro-api/files/2076299/allegro.txt)

**Comment by MartaNowaczyk** [comment]
redirect_uri masz https://beta.apollo.pl. 
Sprawdź z www => https://www.beta.apollo.pl

**Comment by MajkelPl55453** [comment]
Ustawiłem z www i też nic nie dało dokładnie ten sam błąd

**Comment by MajkelPl55453** [comment]
Już rozwiązałem problem. Przy rejestracji aplikacji podałem https://www.beta.apollo.pl/. Podczas autoryzacji aplikacji jako adres zwrotny podałem https://www.beta.apollo.pl/autoryzuj/allegro. A gdy próbowałem pobrać token podawałem https://www.beta.apollo.pl/. Teraz dodałem nową aplikację do testowania lokalnie u mnie na komputerze i ustawiłem redirect url na https://www.beta.apollo.pl/autoryzuj/allegro i wszystko działa. Do zamknięcia
