### ISSUE TITLE
Jak pobrać informacje o produkcie mając jego ID oraz url do tego produktu?

### ISSUE THREAD

**Issue by forthewind** [allegro/allegro-api#2750]
Chciałem zapytać jak pobrać jak największą ilość informacji o produkcie mając jego ID oraz url do tego produktu? W dokumentacji:

https://developer.allegro.pl/productization/#details

Jest coś takiego:

curl -X GET \
  https://api.allegro.pl/sale/products/634238b1-4385-4de7-9c00-dfa49fce16ab \
  -H 'Authorization: Bearer {token}' \
  -H 'accept: application/vnd.allegro.public.v1+json'

Natomiast to nie jest produkt ID? Mi głównie chodzi o coś następującego, mam produkt ID, np. 6728221402 oraz jeszcze dodatkowo url, np.

https://allegro.pl/oferta/kawa-ziarnista-lavazza-pienaroma-1-kg-6728221402?bi_m=mpage&

Pytanie jak pobrać jak największą ilość informacji na podstawie ID oraz url (url niekoniecznie, natomiast ID na pewno). Dziękuję.

**Comment by PatrykBocian** [comment]
ID o którym wspominasz to ID oferty, nie produktu (oferta nie oznacza produktu - więcej informacji znajdziesz w tym [poradniku](https://developer.allegro.pl/productization/)). W takim przypadku możesz użyć takiego ID, aby pobrać ją za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - wtedy możesz podejrzeć informacje o takiej ofercie (musisz być zautoryzowany jako sprzedawca, do którego należy oferta).

**Comment by Aryak2099** [comment]
Musisz zrobić tak jak ja parsowanie strony a potem przez json wyciągasz wszystko co Cię interesuje , obecnie nie ma innej metody na poznanie szczegółów nie swojej aukcji. Wtedy sobie sprawdzasz np cenę , koszt wysyłki . Ja tylko pokaże cześć kodu po zassaniu aukcji : "firstItemCost":{"price":{"amount":"12.49","currency":"PLN","active":true} i tak działasz.
