### ISSUE TITLE
Wnioski o zwrot prowizji

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#2753]
Witam,
nie widzę nigdzie w REST API możliwości wystąpienia o zwrot prowizji (czyli funkcjonalności dostępne w webapi przez doGetRefundsDeals, doGetRefundsList, doGetRefundsReasons, doSendRefundForm).
Kiedy planowane jest zaimplementowanie tych funkcjonalności w REST API?

Póki co chcąc zrobić to przez web api potrzebujemy znaleźć transakcje przez doGetRefundsDeals filtrując je po loginie kupującego, ale nie ma nigdzie opisu jakie wartości może przyjmować filterId,a podana strona z opisem filtrów nie działa: https://allegro.pl/webapi/tutorials.php/tutorial/id,281
Gdzie można aktualnie znaleźć opis dla tych filtrów ?

**Comment by holospl** [comment]
Harmonogram prac:
https://developer.allegro.pl/schedule/

Wg. tej rozpiski planują wprowadzić funkcjonalność dot. zwrotów prowizji w I kwartale tego roku, czyli już za momencik. Oby.

**Comment by cyfranT** [comment]
Dzieki za informacje o harmonogramie. 
Ale pokusilibysmy sie o zrealizowanie tej funkcjonalnosci nawet na 2-3 miesiace w web api. Tylko gdzie znajdziemy opisy mozliwych wartosci dla wspomnianych filtrow?

**Comment by PatrykBocian** [comment]
Obecnie nie posiadamy takiego zasobu w REST API - planujemy go wdrożyć w tym kwartale. Oczywiście poinformujemy o tym w odpowiednim komunikacie. Co do korzystania z filtrów - przykład znajdziesz w tym [wątku](https://github.com/allegro/allegro-api/issues/2423).
