### ISSUE TITLE
Wyświetlanie aukcji o okeślonym czasie dostawy. 

### ISSUE THREAD

**Issue by kubaszy** [allegro/allegro-api#2754]
Witam, 
Potrzebowałbym wyświetlić aukcje swojego użytkownika, o czasie wysyłki większym niż 24h tzn takie które mają czas wysyłki: 2 dni, 3 dni, 5 dni itp. 
Próbowałem zrobić vardump i przeglądnąć informacje, ale nie widziałem tam nigdzie czasu wysyłki. 
Czy jest to możliwe ? 
Dziękuje, pozdrawiam.

**Comment by PatrykBocian** [comment]
Nie mamy zasobu dla masowego uzyskania takiej wartości. Czas dostawy dla pojedynczej oferty możesz sprawdzić za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
