### ISSUE TITLE
Sprawdzenie czy został wystawiony komentarz/ocena do zamówienia

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#2755]
Dzień dobry :)
Czy istnieje aktualnie jakaś możliwość sprawdzenia czy do zamówienia został wystawiony komentarz/ocena?

**Comment by PatrykBocian** [comment]
Nie przekazujemy takich informacji w zamówieniu -  oceny pobierzesz za pomocą [GET  /sale/user-ratings](https://developer.allegro.pl/documentation/#operation/getUserRatingsUsingGET), więcej informacji na ten temat znajdziesz w tym [newsie](https://developer.allegro.pl/news/2017-10-09-news_informacje_o_ocenach/). Jeśli chciałbyś odpowiedzieć na oceny, lub wysłać prośbę o jej usunięcie, to także udostępniliśmy odpowiedni zasób. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2020-01-13-nowe_zasoby_do_zarz%C4%85dzania_ocenami_sprzeda%C5%BCy/).

**Comment by sumo23** [comment]
Odkopuję temat. Chodzi o sytuację, kiedy nie wiadomo czy klient wystawił komentarz. W moje Allegro trzeba by się przekopać przez tysiące stron.
Jak sprawdzić czy i jaki komentarz został wystawiony przez danego usera lub do danej transakcji?

**Comment by MaciejFrackowiak** [comment]
Nic się w tej kwestii nie zmieniło - nie zwracamy takich informacji w danych zamówienia.

**Comment by holospl** [comment]
Ja wprawdzie porzuciłem ten temat, ale wydaję mi się, że jedyny możliwy scenariusz, który to umożliwi to pobranie listy wszystkich komentarzy dla danego użytkownika. Następnie na jej podstawie potrzebna jest dalsza walidacja czy komentarz do zamówienia znajduje się na ww. liście.
