### ISSUE TITLE
[Sandbox] Nie da się dodać ofery

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2756]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o poprawę :)

REQUEST 2020-01-21 15:58:26.2898762 
curl -X PUT \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/6206834474' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"85e8afff-acbc-4be7-856c-664d8f629b93"},"returnPolicy":{"id":"6ab07755-a4a7-49e2-9118-eae910ab29e5"},"warranty":{"id":"215ade76-2835-4b2c-893a-da3d52b4d4de"}},"attachments":null,"category":{"id":"147745"},"compatibilityList":null,"contact":null,"createdAt":null,"delivery":{"additionalInfo":"Aukcja demonstracyjna","handlingTime":"PT1440H","shipmentDate":null,"shippingRates":{"id":"0d5fce48-15a7-47b5-9723-a2ae0252df8b"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Witamy na naszej aukcji! Oferujemy na sprzedaż towar:</p>\r\n\r\n<h1>Czarne rękawiczki</h1>\r\n\r\n<p>AD2</p>\r\n\r\n<p>Producent: <b>Buczetti</b>&nbsp; Marka: <b>Elit</b></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Ekskluzywne czarne rękawiczki, które pasują do wszystkiego. Idealne na chłodne jesienne dni i wieczory. Wykonane z najlepszej świńskiej skóry. W tym produkcie dodana została waga, kod EAN, Jednostka miary, Film youtube, załącznik. Ten produkt zawiera przykładowy atrybut typu liczba &quot;ilość w opakowaniu&quot;, atrybut typu data &quot;data produkcji&quot;, a także atrybuty typu lista &quot;kolor&quot;, &quot;materiał&quot;, &quot;przeznaczenie&quot;.</p>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/115a21/0d30607840e699f306d6fc4800c7"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/113103/792db54c4d3f9cb34697a981a2b8"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/118cb2/5ee1c50a49c0a13e7cdc17ad586c"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/116559/ad59a6b74cbc9e1df4baf489dd99"}]},{"items":[{"type":"TEXT","content":"<p>Zapraszamy na nasze pozostałe aukcje.</p>\r\n"}]}]},"ean":"1697237464","external":{"id":"AD2"},"id":"6206834474","images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/115a21/0d30607840e699f306d6fc4800c7"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/113103/792db54c4d3f9cb34697a981a2b8"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/118cb2/5ee1c50a49c0a13e7cdc17ad586c"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/116559/ad59a6b74cbc9e1df4baf489dd99"}],"location":{"city":"Kraków","countryCode":"PL","postCode":"30-149","province":"MALOPOLSKIE"},"name":"Czarne rękawiczki","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]},{"id":"127768","rangeValue":null,"values":[],"valuesIds":["127768_72"]},{"id":"129626","rangeValue":null,"values":[],"valuesIds":["129626_2"]},{"id":"127789","rangeValue":null,"values":[],"valuesIds":["127789_1","127789_2"]},{"id":"17448","rangeValue":null,"values":["0.4"],"valuesIds":[]},{"id":"5389","rangeValue":null,"values":["22"],"valuesIds":[]},{"id":"295","rangeValue":null,"values":["10"],"valuesIds":[]},{"id":"5390","rangeValue":null,"values":[],"valuesIds":["5390_178"]},{"id":"5391","rangeValue":null,"values":[],"valuesIds":["5391_20"]},{"id":"5392","rangeValue":null,"values":[],"valuesIds":["5392_4"]},{"id":"18461","rangeValue":null,"values":[],"valuesIds":["18461_2"]},{"id":"451","rangeValue":null,"values":[],"valuesIds":["451_32"]}],"payments":{"invoice":"VAT"},"product":null,"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"138.00","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"sizeTable":null,"stock":{"available":95,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-01-21 15:58:27.1180088 Duration: 828,1326ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (500) Internal Server Error.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "f57f05410af6c966",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**Comment by PatrykBocian** [comment]
Na chwilę Sandbox działa prawidłowo - czy problem nadal u ciebie występuje?

**Comment by hYOUstone** [comment]
Chciałbym się podpiąć pod temat. Mi akurat chodzi o to, że nie działa dodawanie ofert z poziomu panelu Sandbox (Wystaw przedmiot). Po kliknięciu w link składania nowej oferty przekierowuje na adres: 
https://staging-lokalnie.allegrogroup.com/oferty/wystaw
który nie działa.

**Comment by PatrykBocian** [comment]
@hYOUstone W takim przypadku skorzystaj z tego linku -  https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

**Comment by SebastianOzdoba** [comment]
@PatrykBocian dziś już działa

**Comment by hYOUstone** [comment]
Dziękuję. Faktycznie ten (https://allegro.pl.allegrosandbox.pl/offer/?lokalnie) link działa. Prosiłbym o podpięcie również prawidłowego linku na stronie w wolnym czasie.

**Comment by PatrykBocian** [comment]
@hYOUstone Użytkownicy już zgłaszali ten problem - w najbliższej przyszłości zajmiemy się tą sprawą.
