### ISSUE TITLE
Brak parametru offer.publication.endedAt w /sale/offer-events 

### ISSUE THREAD

**Issue by hmkdbsw** [allegro/allegro-api#2757]
Witam,

mogę wiedzieć, dlaczego dla eventu `OFFER_ENDED` w zasobie `/sale/offer-events` parametr `offer.publication.endedAt` nie jest w ogóle zwracany? W dokumentacji taki parametr istnieje. To chwilowy błąd? Od paru dni widzę, że go w ogóle nie ma.

Pozdrawiam.

**Comment by PatrykBocian** [comment]
Nie zwracamy takiego parametru w tym zasobie. W dokumentacji wcześniej występował błąd - poprawiliśmy go 17.12.2019, było to zgłoszone w tym [wątku](https://github.com/allegro/allegro-api/issues/2639).

**Comment by hmkdbsw** [comment]
> Nie zwracamy takiego parametru w tym zasobie. W dokumentacji wcześniej występował błąd - poprawiliśmy go 17.12.2019, było to zgłoszone w tym [wątku](https://github.com/allegro/allegro-api/issues/2639).

https://developer.allegro.pl/documentation/#operation/getOfferEvents
Z tym, że go nie poprawiliście.

**Comment by PatrykBocian** [comment]
Masz rację, rzeczywiście występuje błąd w dokumentacji. Poprawiliśmy informacje w payload, a zapomnieliśmy o tym miejscu ;) Poprawimy to w najbliższym czasie. Dziękujemy za czujność.
