### ISSUE TITLE
Dane zwrotu, lista zwrotów - zwroty

### ISSUE THREAD

**Issue by Przem4S** [allegro/allegro-api#2758]
Witam, kiedy będzie możliwość pobrania zwrotów zrobionych przez klienta i pobrania danych do zwrotu?

**Comment by PatrykBocian** [comment]
Na chwilę obecną nie mamy tego w planach. Pojawiły się już takie sugestie, dodam też Twoje zgłoszenie.

**Comment by mpysz** [comment]
Dzień dobry,
chciałbym dołączyć do prośby. Już 2 firmy pytały w ostatnim czasie o możliwość pobrania danych o zwrotach z Allegro.

**Comment by PatrykBocian** [comment]
@mpysz Dopisałem także twoje zgłoszenie.

**Comment by pokash** [comment]
Dołączam się do prośby :) widziałem, że sugestie pojawiały się już od dawna :) ciężko jest już zapanować na obsługą zwrotów, który jest dostępny w panelu Allegro :)

**Comment by PawelTaberski** [comment]
Dodałem również Twój głos :-)
