### ISSUE TITLE
Data kolejnej weryfikacji przy Super sprzedawcy

### ISSUE THREAD

**Issue by Gerston** [allegro/allegro-api#2759]
Czy jest możliwość pobrać przez RestApi daty kolejnej weryfikacji Super sprzedawcy?
Jeśli nie ma takiej możliwości, to czy jest szansa, że będzie udostępniona?
Mogła by się pojawiać wtedy kiedy konto ma super sprzedawcę i pobiera się oceny użytkowników
GET  /sale/user-ratings?user.id=

**Comment by PatrykBocian** [comment]
Nie ma obecnie takiej funkcjonalności w API - przekaże twoją sugestię do odpowiedniego zespołu.
