### ISSUE TITLE
Brak danych do faktury

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2760]
Takie zamówienie: https://allegro.pl/moje-allegro/sprzedaz/zamowienia/9c0ae3d5-3d0d-11ea-b547-a96145675d6a

Wg. API jest w stanie FILLED_IN wraz z:

```
  "invoice": {
    "address": null,
    "required": true
  }
```

Na maila dostałem jednak, że:
- wybrał `Płacę przelewem tradycyjnym`
- oraz pełne dane do faktury, łącznie z NIP

Czy można już te dane prezentować przy FILLED_IN? Tych danych też nie ma w panelu Allegro - są jedynie w e-mailu. Więc dane są znane - kwestia prezentacji.

Dodatkowo - jak ktoś ma SMARTa, to wolałbym aby nie było opcji `Płacę przelewem tradycyjnym`. Klienci się mylą, wpłacają na nasze konto i efekt jest taki, że SMART nie działa - jedyne co możemy prosić to o odpłatę za wysyłkę (już słyszę "ale dlaczego?") albo anulujemy zamówienie.

**Comment by Radeq** [comment]
Zobacz sobie dyskusję #2073 , niestety wygląda na to, że sugestia nie zostanie na razie zrealizowana..

**Comment by PatrykBocian** [comment]
Odpowiadając na twoje pytania:

- Dane te będą zawarte przy **READY_FOR_PROCESSING**, po tym jak płatność przejdzie przez Allegro Finanse,
- Taka sytuacja nie będzie miała miejsca - płatność przelewem tradycyjnym, odbywa się w ramach Allegro Finanse. Kupujący nie mają już możliwości płacenia bezpośrednio na rachunek kupującego.

**Comment by pgasidlo** [comment]
> Odpowiadając na twoje pytania:
> * Taka sytuacja nie będzie miała miejsca - płatność przelewem tradycyjnym, odbywa się w ramach Allegro Finanse. Kupujący nie mają już możliwości płacenia bezpośrednio na rachunek kupującego.

Jak to nie ma? Zawsze jest możliwość znalezienia numeru konta kupującego (czy to na stronie aukcji, czy to na stronie o sprzedającym, czy szukając sam NIP w internecie i idąc do sklepu). I kupujący tak robią. Tekst "płacę przelewem tradycyjnym" to właśnie oznacza. Pytanie co Allegro z tym zrobi? 

Wracając do problemu - kiedy to będzie w `FILLED_IN`.

**Comment by pkrzemo** [comment]
Niestety osoby "zAllegroWięcJestemNieomylny" wiedzą "lepiej" ...
Pozostaje tylko kontakt z klientem i uzupełnianie danych "z palca". AllegroWiemLepiej działa sobie w ten sposób na własną szkodę. W końcu kontakt ze sprzedawcą  (wymuszony tymi działaniami przez Allegro) może być przyczynkiem do zawierania kolejnych transakcji już bez tych upierdliwości - czyli poza Allegro ...

**Comment by pkrzemo** [comment]
Dodam jeszcze że często jest: "Nie umiem zapłacić, proszę wysłać za pobraniem..." ;-)

**Comment by PatrykBocian** [comment]
@pgasidlo  W przypadku płatności przelewem tradycyjnym, przechodzi ona przez Allegro Finanse - kupującemu generujemy link ze wzorem przelewu, na którym znajduje się numer identyfikujący płatność, dzięki czemu przelew będzie zrealizowany w ramach Allegro Finanse i zamówienie otrzyma odpowiedni status **READY_FOR_PROCESSING**.
