### ISSUE TITLE
POST /sale/offers - błąd zdjęcia ?

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#2761]
Występuje problem: 
 - [ X ] z zasobem REST API

Dziś skrypt który od dawna używam do wystawiania nowych ofert zgłasza debilny błąd
link który wskazywany jest jako nieprawidłowy , prowadzi do zdjęcia prawidłowo wgranego na serwer alllegro i bez problemu otwiera się w przeglądarce
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Invalid image URL. Image must be present on allegro server.
                    [details] => Invalid value:  https://a.allegroimg.com/original/11bb09/ba27f9d5484289acacea1f0dd8b9

                    [path] => images[0].url
                    [userMessage] => Invalid image URL. Image must be present on allegro server.
                )

        )

)

**Comment by MaciejFrackowiak** [comment]
Zweryfikowałem przekazane przez Ciebie zdjęcie - nie jest ono dostępne na serwerze do pobrania. Jego wyświetlanie w przeglądarce to efekt jego dostępności w cache. Proszę wgraj ponownie zdjęcie na serwer, a następnie wykorzystaj je w ofercie.

**Comment by 11mszot** [comment]
@MaciejFrackowiak 

Panie Macieju , zbyt długo pan przetwarzał to zgłoszenie , w chwili gdy pisałem zgłoszenie zdjęcie było na serwerze. Chyba nie muszę panu tłumaczyć że skoro czas życia nowo wgranego zdjęcia na waszych serwerach to 4 godziny , a pan reaguje na zgłoszenie po 12 godzinach , to nie ma szans by zdjęcie było jeszcze aktualne. Jak mam panu udowodnić że nie jestem żyrafą ? Wgrywać co cztery godziny nowe zdjęcie i  publikować nowy post w tym wątku aż złapiemy synchronizację ?

**Comment by 11mszot** [comment]
proszę , kolejny ten sam błąd , zdjęcie wgrane na wasz serwer o 10:40

(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Invalid image URL. Image must be present on allegro server.
                    [details] => Invalid value: https://a.allegroimg.com/original/11458d/8ccfa59f4b478ff03fce2cf422f2

                    [path] => images[0].url
                    [userMessage] => Invalid image URL. Image must be present on allegro server.
                )

        )

)

**Comment by 11mszot** [comment]
kolejny :
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Invalid image URL. Image must be present on allegro server.
                    [details] => Invalid value: https://a.allegroimg.com/original/110dfb/9df8794d4960bc80eda2acd0b0fc

                    [path] => images[0].url
                    [userMessage] => Invalid image URL. Image must be present on allegro server.
                )

        )

)

**Comment by 11mszot** [comment]
Zdjęcie uploadowane o 12:20

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Invalid image URL. Image must be present on allegro server.
                    [details] => Invalid value: https://a.allegroimg.com/original/118d6e/4c35aebc494f9d89c6043bce65b5

                    [path] => images[0].url
                    [userMessage] => Invalid image URL. Image must be present on allegro server.
                )

        )

)

**Comment by MaciejFrackowiak** [comment]
@11mszot Przed momentem zrobiłem test ze zdjęciem z ostatniego postu - końcówka url = 65b5.
Bez przeszkód dodałem je do draftu - jest widoczne także na froncie. Także ponownie je przesłałem poprzez POST /sale/images - tu również wynik pozytywny.
Proszę prześlij nam pełen request i response wraz z trace-id poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) - sprawdzę wówczas konkretne wywołanie.

**Comment by 11mszot** [comment]
@MaciejFrackowiak 

W opie błędu bardzo wyraźnie napisałem , że chodzi o metodę POST z wykorzystaniem świeżo uploadowanego zdjęcia
Ty natomiast najpierw zrobiłeś PUT , a później dopiero POST , i być może w ten sposób to zadziałało , natomiast POST jako pierwszy nie działa , choć wcześniej działał , bo wystawiłem w ten sposób setki tysięcy aukcji. Teraaz sprawdziłeś i POST z tym obrazkiem który użyłeś już działa. Wygląda więc na to , że na nowo uploadowanym obrazku , żeby wasz system go skojarzył trzeba najpierw wykonać PUT , a później dopiero można POST - moim zdaniem jest to chore , i to jakiś bug po ostatnich zmianach

Zrobiłem teraz test POST na nowym obrazku i jest dokładnie ten sam problem
Wysyłanie tego przez formularz kontaktowy jest o kant dupu rozbić , bo zanim zareagujecie , zdjęcie znowu się przeterminuje u was

Response:

{"errors":[{"code":"VALIDATION_ERROR","message":"Invalid image URL. Image must be present on allegro server.","details":"Invalid value: https:\/\/a.allegroimg.com\/original\/11fdeb\/5c58a34c4947a73f42c5791011f9\n","path":"images[0].url","userMessage":"Invalid image URL. Image must be present on allegro server."}]}

Request:

{"name":"HART AMORTYZATOR NACI\u0104GU PASKA AUDI A4 1.8T 00-02","category":{"id":"255481"},"parameters":[{"id":"127415","valuesIds":["127415_22"]},{"id":"215858","values":["364 386"]},{"id":"129591","valuesIds":["129591_1"]},{"id":"215941","values":["AUTOKIT 03.80431","AUTOKIT 03.81666","AUTOTEAM A03596","BEHR HELLA SERVICE 9XU 376 818-551","FEBI BILSTEIN 22347","FLENNOR FD99199","GATES T43028","MAGNETI MARELLI 331316170340","PROCODIS FRANCE AM260","REPKIT RKT2147","REPKIT RKT3382","RUVILLE 55712","RUVILLE 56365","TOPRAN 109 142","WILMINK GROUP WG1253098","WILMINK GROUP WG1428567"]},{"id":"227345","values":["AUDI 06B 109 477 A","SEAT 06B 109 477 A","SKODA 06B 109 477 A","VW 06B 109 477 A"]},{"id":"11323","valuesIds":["11323_1"]}],"ean":"5901219462243","description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>HART AMORTYZATOR NACI\u0104GU PASKA AUDI A4 1.8T 00-02<\/h1>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11fdeb\/5c58a34c4947a73f42c5791011f9\n"},{"type":"TEXT","content":"<h2>\u2713 Podstawowe parametry<\/h2><ul><li>\u015brednica [mm]: <b>28.5 <\/b><\/li><li>Szeroko\u015b\u0107 [mm]: <b>27 <\/b><\/li><li>Typy referencyjne: <b>wymienialny <\/b><\/li><\/ul>"}]},{"items":[{"type":"TEXT","content":"<h2>\u2713 Wyst\u0119puje w pojazdach<\/h2><ul><li>Audi A4 (8D2, B5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1995\/01-2000\/11, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8D2, B5) 1.8 T quattro (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1995\/01-2000\/11, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T (AVJ) 1781ccm 150KM\/110kW 2000\/11-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T quattro (AVJ) 1781ccm 150KM\/110kW 2000\/11-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T quattro (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8E2, B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2000\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8EC, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8EC, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 (8EC, B7) 2.0 (ALT) 1984ccm 130KM\/96kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8D5, B5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1996\/03-2001\/09, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8D5, B5) 1.8 T quattro (AEB ANB APU ARK ATW AWT) 1781ccm 150KM\/110kW 1996\/01-2001\/09, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T (AVJ) 1781ccm 150KM\/110kW 2001\/09-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T quattro (AVJ) 1781ccm 150KM\/110kW 2001\/09-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T quattro (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8E5, B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/09-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole, Sterowanie rolk\u0105 napinacza: hydrauliczny<\/li><li>Audi A4 Avant (8ED, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8ED, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 Avant (8ED, B7) 2.0 (ALT) 1984ccm 130KM\/96kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 kabriolet (8H7, B6, 8HE, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2009\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A4 kabriolet (8H7, B6, 8HE, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2003\/05-2009\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A6 (4B2, C5) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/08-2005\/01, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Audi A6 Avant (4B5, C5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1997\/12-2005\/01, szczeg\u00f3\u0142y: Numer podwozia od: 4B-1-040 001, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A6 Avant (4B5, C5) 1.8 T quattro (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1997\/12-2005\/01, szczeg\u00f3\u0142y: Numer podwozia od: 4B-1-040 001, Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Audi A6 Avant (4B5, C5) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/08-2005\/01, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Seat EXEO (3R2) 1.8 T (CFMA) 1781ccm 150KM\/110kW 2008\/12-2010\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Seat EXEO ST (3R5) 1.8 T (CFMA) 1781ccm 150KM\/110kW 2009\/06-2010\/05, szczeg\u00f3\u0142y: Kod silnika: CFMA, Strona zabudowy: z lewej na dole<\/li><li>Skoda SUPERB I (3U4) 1.8 T (AWT) 1781ccm 150KM\/110kW 2001\/12-2008\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Volkswagen PASSAT (3B3) 1.8 T 20V (AWL AWT) 1781ccm 150KM\/110kW 2000\/11-2005\/05, szczeg\u00f3\u0142y: Kod silnika: AWT, Strona zabudowy: z lewej na dole<\/li><li>Volkswagen PASSAT (3B3) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Volkswagen PASSAT Variant (3B6) 1.8 T 20V (AWT) 1781ccm 150KM\/110kW 2000\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><li>Volkswagen PASSAT Variant (3B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole<\/li><\/ul>"}]},{"items":[{"type":"TEXT","content":"<h2>\u2713 Numery OE<\/h2><ul><li>AUTOKIT 03.80431<\/li><li>AUTOKIT 03.81666<\/li><li>AUTOTEAM A03596<\/li><li>BEHR HELLA SERVICE 9XU 376 818-551<\/li><li>FEBI BILSTEIN 22347<\/li><li>FLENNOR FD99199<\/li><li>GATES T43028<\/li><li>MAGNETI MARELLI 331316170340<\/li><li>PROCODIS FRANCE AM260<\/li><li>REPKIT RKT2147<\/li><li>REPKIT RKT3382<\/li><li>RUVILLE 55712<\/li><li>RUVILLE 56365<\/li><li>TOPRAN 109 142<\/li><li>WILMINK GROUP WG1253098<\/li><li>WILMINK GROUP WG1428567<\/li><li>AUDI 06B 109 477 A<\/li><li>SEAT 06B 109 477 A<\/li><li>SKODA 06B 109 477 A<\/li><li>VW 06B 109 477 A<\/li><\/ul>"}]}]},"compatibilityList":{"id":"fec77d5b-083b-4a27-8502-be4a93572be6-910773b9742b587b6e3cdb768d3c1e05f454878bb227c678db47bfb6b2e36603-2","type":"PRODUCT_BASED","items":[{"text":"Audi A4 (8D2, B5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1995\/01-2000\/11, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8D2, B5) 1.8 T quattro (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1995\/01-2000\/11, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T (AVJ) 1781ccm 150KM\/110kW 2000\/11-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T quattro (AVJ) 1781ccm 150KM\/110kW 2000\/11-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T quattro (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8E2, B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2000\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8EC, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8EC, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 (8EC, B7) 2.0 (ALT) 1984ccm 130KM\/96kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8D5, B5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1996\/03-2001\/09, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8D5, B5) 1.8 T quattro (AEB ANB APU ARK ATW AWT) 1781ccm 150KM\/110kW 1996\/01-2001\/09, szczeg\u00f3\u0142y: Rok prod. od: 2000\/01, Numer podwozia od: 8D-1-042 385, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T (AVJ) 1781ccm 150KM\/110kW 2001\/09-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T quattro (AVJ) 1781ccm 150KM\/110kW 2001\/09-2002\/07, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T quattro (BEX) 1781ccm 190KM\/140kW 2002\/11-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2002\/07-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8E5, B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/09-2004\/12, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole, Sterowanie rolk\u0105 napinacza: hydrauliczny"},{"text":"Audi A4 Avant (8ED, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8ED, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 Avant (8ED, B7) 2.0 (ALT) 1984ccm 130KM\/96kW 2004\/11-2008\/06, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 kabriolet (8H7, B6, 8HE, B7) 1.8 T (BFB) 1781ccm 163KM\/120kW 2002\/07-2009\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A4 kabriolet (8H7, B6, 8HE, B7) 1.8 T quattro (BFB) 1781ccm 163KM\/120kW 2003\/05-2009\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A6 (4B2, C5) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/08-2005\/01, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Audi A6 Avant (4B5, C5) 1.8 T (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1997\/12-2005\/01, szczeg\u00f3\u0142y: Numer podwozia od: 4B-1-040 001, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A6 Avant (4B5, C5) 1.8 T quattro (AEB ANB APU ARK AWT) 1781ccm 150KM\/110kW 1997\/12-2005\/01, szczeg\u00f3\u0142y: Numer podwozia od: 4B-1-040 001, Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Audi A6 Avant (4B5, C5) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/08-2005\/01, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Seat EXEO (3R2) 1.8 T (CFMA) 1781ccm 150KM\/110kW 2008\/12-2010\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Seat EXEO ST (3R5) 1.8 T (CFMA) 1781ccm 150KM\/110kW 2009\/06-2010\/05, szczeg\u00f3\u0142y: Kod silnika: CFMA, Strona zabudowy: z lewej na dole"},{"text":"Skoda SUPERB I (3U4) 1.8 T (AWT) 1781ccm 150KM\/110kW 2001\/12-2008\/03, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Volkswagen PASSAT (3B3) 1.8 T 20V (AWL AWT) 1781ccm 150KM\/110kW 2000\/11-2005\/05, szczeg\u00f3\u0142y: Kod silnika: AWT, Strona zabudowy: z lewej na dole"},{"text":"Volkswagen PASSAT (3B3) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Volkswagen PASSAT Variant (3B6) 1.8 T 20V (AWT) 1781ccm 150KM\/110kW 2000\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"},{"text":"Volkswagen PASSAT Variant (3B6) 2.0 (ALT) 1984ccm 130KM\/96kW 2001\/11-2005\/05, szczeg\u00f3\u0142y: Strona zabudowy: z lewej na dole"}]},"tecdocSpecification":null,"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11fdeb\/5c58a34c4947a73f42c5791011f9\n"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"67.55","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":20,"unit":"UNIT"},"delivery":{"shippingRates":{"id":"05b27bd4-5364-492d-951b-a6b947ae44cd"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"09070613-d1e8-4fa3-807c-fe81a7418aae"},"returnPolicy":{"id":"70b9c812-0e50-4c09-ba88-37c626820482"},"warranty":null},"additionalServices":null,"sizeTable":null,"location":{"countryCode":"PL","province":"DOLNOSLASKIE","city":"Wroc\u0142aw","postCode":"50-515"},"external":{"id":"HAR364386"},"attachments":[],"contact":null}

**Comment by MaciejFrackowiak** [comment]
@11mszot Mój test - jak wspomniałem zrobiłem dwojako - zarówno poprzez bezpośredni POST /sale/offers z Twoim zdjęciem (https://a.allegroimg.com/original/118d6e/4c35aebc494f9d89c6043bce65b5), jak i z przejściem całego flow - POST /sale/images, a następnie wykorzystanie tego zdjęcia przy dodaniu do draftu oferry. Obie ścieżki zakończyły się pomyślnie. Niestety, nie przekazałeś nam trace-id - prośba o jego podanie.

**Comment by 11mszot** [comment]
@MaciejFrackowiak , sory ale nadal nie rozumiesz problemu

Więc po kolei 
1) Wgrywam na wasz serwer nowe zdjęcie metodą POST na zasobie /sale/images
W odpowiedzi dostaję link do zdjęcia na serwerze allegro 

2) jeśli po wgraniu zdjęcia użyję metodę PUT na zasobie /sale/offers z użyciem linku do tego zdjęcia
to zdjęcie jest przypisywane do Draftu i można je wykorzaystywać także przy tworzeniu nowego draftu metodą POST na tym zasobie

3) Jeśli natomiast po uploadzie zdjęcia chcę utworzyć nowy draft z użyciem metody POST na zasobie /sale/offers , pojawia się błąd który opisałem. Aby błąd się nie pojawiał ,  musze zanim użyję metody POST z wykorzystaniem tej metody , najpierw wykorzystać link w metodzie PUT , kojarząc zdjęcie z dowolnym istniejącym draftem

4) Wcześniej , przed 13 stycznia , nie było tego problemu i uploadowane zdjęcie można było wykorzystać od razu w strukturze POST. Problem pojawił się w chwili gdy zaczęliście limitować
ilość draftów na koncie. Jest to duży problem nie tylko dla mnie ale także dla was bo powoduje konieczność wykonywania dodatkowych żądań do api w postaci PUT na /sale/offers tylko po to by zdjęcie mogło być użyte w metodzie POST na tym zasobie

Jeśli dalej zgłoszenie jest niezrozumiałe mogę je napisać w języku angielskim , niemieckim lub rosyjskim. Tylko nie piszcie proszę ,  że nikt wam nie będzie w obcych językach mówił , jak ma działać wasze api

**Comment by 11mszot** [comment]
Odwołuję alarm , dziś po południu już znowu działa jak poprzednio

**Comment by MaciejFrackowiak** [comment]
@11mszot Cieszę się, że sytuacja jest już opanowana.
