### ISSUE TITLE
Api REST

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2762]
Hi
Allegro Team
I have a situation that i want to delete my all the products which has been uploaded till now using my account.If you do this i'm very thankful to you.
If there is any way that i can delete my product by myself please send me the procedure.

**Comment by PawelTaberski** [comment]
Hi, by products you mean your offers? I have checked account sportmma and you have there 0 offers. 
If you mean products proposals, which you add by calling POST /sale/product-proposals you can't delete them.

**Comment by sportmma** [comment]
Czy mozecie usunąć wszystkie produkty, które były wysłane za pomoca api. Poniewaz mój moduł allegro dla magento 2 otrzymuje odpowiedz z waszego api, że produkt jest już przesłany, ale w panelu allegro nie wyświetla się.

**Comment by sportmma** [comment]
Nie wiem w jaki sposób rozwiązać ten problem

**Comment by sportmma** [comment]
Dlaczego, jeżeli przesłali się produkt za pomoca api, a później ręcznie go usunęli, nie można drugi raz to przeslac przez api, tylko wyskakuje informacja, że produkt jest już przesłany?

**Comment by PawelTaberski** [comment]
Produkt, a oferta to dwie osobne sprawy. Ofertę "podpinasz" do produktu, może być wiele ofert, w których oferujemy ten sam produkt. Produktu nie można usunąć, bo już ktoś inny może mieć go podpiętego. Nie wiem w jaki sposób twórca twojej aplikacji korzysta z naszego API. Powinieneś jemu zgłosić ten problem. I jeśli ma on jakiś problem z naszym API, to poproś go aby skontaktował się z nami. Tylko on posiada wgląd do wszelkich niezbędnych requestów itp. abyśmy mogli mu pomóc.
