### ISSUE TITLE
fail to get getMainCategories

### ISSUE THREAD

**Issue by tan133** [allegro/allegro-api#2763]
hi engineer 
what's the correct CURL HEADER looks like when getMainCategories
I am try to make my own api 

I am succes to get token  as below
{"access_token":"eyJXXXXXX","token_type":"bearer","expires_in":43199,"scope":"allegro_api","jti":"247648ba-383d-4af7-846c-ae97922c8e71"}

but I am fail everytime when use  getMainCategories
the code was used as below

curl -X GET \
https://api.allegro.pl/sale/categories \
-H 'Authorization: Bearer eyJXXXXXX' \
-H 'accept: application/vnd.allegro.beta.v1+json'

and I try to do it in php as api show（code as below show），but failed too
<?php
function getMainCategories(String $token)
{
    $getCategoriesUrl = "https://api.allegro.pl/sale/categories";

    $ch = curl_init($getCategoriesUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $mainCategoriesResult = curl_exec($ch);
    curl_close($ch);
    return $mainCategoriesResult;  //return false every time
}

function main()
{
    $token=;
    var_dump(getMainCategories($token));
}

main();

**Comment by PawelTaberski** [comment]
Hi, I see you want to call resources on sandbox, but you try use token from production. Token on production expires in 43199, on sandbox only 3599.

**Comment by tan133** [comment]
> Hi, I see you want to call resources on sandbox, but you try use token from production. Token on production expires in 43199, on sandbox only 3599.

Tanks for reply ,but in fact the test on both sandbox and production,are all fail

**Comment by PawelTaberski** [comment]
Please send me by [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) your request and response which fail, add information that this data are needed for ticket number 2763 on GitHub. We will check this.
