### ISSUE TITLE
Informacja o możliwej wielowariantowości

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2764]
Witam,
na stronie z opisem jak wystawiać oferty z wielowariantowością https://developer.allegro.pl/multi_variant_offers/
mamy taką informację  
>Parametry, dzięki, którym możesz tworzyć oferty wielowariantowe pobierzesz metodą GET z zasobu /sale/categories/{categoryId}/parameters.
>Tym zasobem pobierzesz listę parametrów, które są dostępne w kategorii, którą wskazałeś. **Informacje o tym, czy z danym parametrem możesz utworzyć ofertę wielowariantową znajdziesz w polu ‘variantsAllowed’**, które jest w słowniku ‘options’

W kategorii Moda/Odzież, Obuwie, Dodatki/Obuwie/Damskie/Trekkingowe (55205)
jedynym polem które ma ustawioną tą wartość jest rozmiar(26388)

Tymczasem na tej aukcji https://allegro.pl/oferta/nagaba-052-szary-trekking-nowosc-rozmiar-36-7515048799  która jest wystawiona we wskazanej powyżej kategorii dodatkowo jest łącznie po parametrze kolor/wzór.

Dlatego chciałbym się dowiedzieć jakim cudem można łączyć aukcje po kolorze skoro jest dostępne tylko po rozmiarze ?

**Comment by 11mszot** [comment]
Color/Patern jest połaczeniem niezależnym od parametrów , Aby sprawdzić czy w danej kategorii jest możliwy color/patern wywołaj GET na zasobie https://api.allegro.pl/sale/categories/{category}

W uzyskanej odpowiedzi sprawdź wartość zmiennej  options->variantsByColorPatternAllowed] => 1

jeśli przyjmuje wartość 1 , color /patern jest możliwy dla tej kategorii
         

Array
(
    [id] => 50772
    [name] => Przewody zapłonowe
    [parent] => Array
        (
            [id] => 50761
        )

    [leaf] => 1
    [options] => Array
        (
            [variantsByColorPatternAllowed] => 1
            [advertisement] =>.
            [advertisementPriceOptional] =>.
            [offersWithProductPublicationEnabled] => 1
            [productCreationEnabled] =>.
            [productEANRequired] =>.
        )

)

**Comment by mzawodzinski** [comment]
Rozumiem że jeśli wystawię jedną "serie" złączoną po rozmiarze i podanym paternem, 
a następnie wystawię kolejną "serie" złączoną po rozmiarze i podanym tym samym paternem to aukcje nie połączą się automatycznie ?
https://allegro.pl.allegrosandbox.pl/oferta/model-408-pomarancz-campari-rozmiar-41-6206837670
https://allegro.pl.allegrosandbox.pl/oferta/model-408-pomarancz-campari-rozmiar-42-6206837671
https://allegro.pl.allegrosandbox.pl/oferta/model-408-jasny-zielony-crazy-rozmiar-41-6206837686
https://allegro.pl.allegrosandbox.pl/oferta/model-408-jasny-zielony-crazy-rozmiar-42-6206837687

**Comment by 11mszot** [comment]
Za każdym razem gdy dodajesz lub modyfikujesz ofertę wielowariantową , musisz  przesłać kompletną strukturę , zawierającą wszystkie aukcje i parametry po których je chcesz powiazać metodą PUT na zasobie : https://api.allegro.pl/sale/offer-variants/{setId}

Przykładowe struktury masz w tym przykładzie
https://developer.allegro.pl/multi_variant_offers/#1

**Comment by PatrykBocian** [comment]
Jest dokładnie tak jak pisze @11mszot  - dziękujemy za pomoc innym użytkownikom.
