### ISSUE TITLE
Could not change the Offer publication status from sketch to active

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#2765]
Hi the offer publication status is not changing from sketch to active please help me out if this is an api issue

**Comment by PatrykBocian** [comment]
Please send us offer.id and your id - this will help us to find a solution to this issue.

**Comment by sportmma** [comment]
Product already exists. Please contact the application author.
--

**Comment by 07adityasingh** [comment]
This is the offer id :8895666675 and seller id is : 63996658

**Comment by PatrykBocian** [comment]
Please check your draft before activating - you have added wrong **EAN code** (provided EAN is not equal with any EAN assigned to the product) you can check valid EAN for your product via:

- **GET /sale/products/{productId}**

You have also added incorrect value for parameter “**Marka**” (id: 237190) - value should be “**MANTO VICTORY**”.

If you change it - offer will activate correctly. Remember to activate your offer via **PUT /sale/offer-publication-commands/{commandId}** - for now you have used the wrong resource for this. You will find more information about create offer in our [guide ](https://developer.allegro.pl/en/sale/) and [documentation](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST).

**Comment by sportmma** [comment]
Why does he send me only one product? A message appears with the rest:

Product already exists. Please contact the application author.
--

**Comment by sportmma** [comment]
Can the brand value be the name itself: MANTO?

**Comment by 07adityasingh** [comment]
if i need to update status of offer then "https://api.allegro.pl/sale/offers/{offerId}" this api call will not work ?

**Comment by PatrykBocian** [comment]
@sportmma About your questions:

- You received this message because you try to add product instead of get existing product (and then assign it to the offer).
  -  you will receive more information about product via  [GET /sale/products/{product.id}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)
  - If you want to propose a new product use [POST/sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct).
  - More information about products you will find in our [guide](https://developer.allegro.pl/en/productization/).
- If you check this offer via [GET /sale/offer/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - You can see in error validation information about incorrect value for this parameter (should be “**MANTO VICTORY**”).

@07adityasingh  No, you can activate your offer only via  [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT).

**Comment by 07adityasingh** [comment]
how we get CommadId ? What is the procedure ?

**Comment by PatrykBocian** [comment]
@07adityasingh It is a globally unique identifier that consists of 32 hexadecimal numbers (e.g. **21ae4ed1-eab7-34ea-b605-cf2e22b5eed3**). You can generate UID for example on this website - https://www.uuidgenerator.net/

More information about UID You will find in our [guide](https://developer.allegro.pl/en/about/#ids).

**Comment by 07adityasingh** [comment]
https://api.allegro.pl/sale/offer-publication-commands/8c7e4642-4298-11ea-b77f-2e728ce88125
Sending data
-------------------- 
{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"8905359936"}],"type":"CONTAINS_OFFERS"}]}

Response 
-------------
{"id":"8c7e4642-4298-11ea-b77f-2e728ce88125","taskCount":{"total":0,"success":0,"failed":0}}

But offer is still in sketch status it is not active

**Comment by 07adityasingh** [comment]
This is the offer data

Array
(
    [id] => 8905359936
    [name] => Szczerbaty
    [category] => Array
        (
            [id] => 121816
        )

    [product] => Array
        (
            [id] => 82385845-1933-427f-83c8-1c32c2335071
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 130411
                    [valuesIds] => Array
                        (
                            [0] => 130411_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [2] => Array
                (
                    [id] => 237190
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => MANTO VICTORY
                        )

                    [rangeValue] => 
                )

        )

    [ean] => 6783254789764
    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 
- Ochraniacz górnych zębów
- Silikon dopasowujący się do kształtu zębów pod wpływem temperatury
- Pudełko gratis


                                        )

                                )

                        )

                )

        )

    [compatibilityList] => 
    [tecdocSpecification] => 
    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/110adb/f327f1fb467194c15eff2e765ac0
                )

            [1] => Array
                (
                    [url] => https://a.allegroimg.com/original/11e238/d8976295425c99c744f12f661b8d
                )

        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 12
                    [currency] => PLN
                )

            [startingPrice] => 
            [minimalPrice] => 
        )

    [stock] => Array
        (
            [available] => 10
            [unit] => UNIT
        )

    [publication] => Array
        (
            [duration] => PT720H
            [status] => INACTIVE
            [startingAt] => 
            [endingAt] => 
            [endedBy] => 
            [republish] => 
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => 378d5570-3ab4-4a25-b5d1-fde0b48d4761
                )

            [handlingTime] => PT96H
            [additionalInfo] => 
            [shipmentDate] => 
        )

    [payments] => Array
        (
            [invoice] => WITHOUT_VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => 5e74440f-8869-4768-a87c-0711f07a7468
                )

            [returnPolicy] => Array
                (
                    [id] => d0b63355-777f-44e1-b935-08b757756179
                )

            [warranty] => Array
                (
                    [id] => eb7b61f4-1d66-467c-b317-7e671d20f035
                )

        )

    [additionalServices] => 
    [sizeTable] => 
    [promotion] => Array
        (
            [emphasized] => 
            [bold] => 
            [highlight] => 
            [departmentPage] => 
            [emphasizedHighlightBoldPackage] => 
        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => OPOLSKIE
            [city] => Dobrzeń Wielki
            [postCode] => 46-081
        )

    [external] => 
    [attachments] => Array
        (
        )

    [contact] => 
    [validation] => Array
        (
            [errors] => Array
                (
                )

            [validatedAt] => 2020-01-30T06:07:35.470Z
        )

    [createdAt] => 2020-01-30T05:55:31.000Z
    [updatedAt] => 2020-01-30T06:07:35.470Z
)

**Comment by PatrykBocian** [comment]
As I see you used commandId **8c7e4642-4298-11ea-b77f-2e728ce88125** first at **2020-01-30 06:20:49.666** - you got error: error='**Could not change offer publication status. Provided EAN is not equal with any EAN assigned to the product**”. Then, you used the same commandId 5 times - it was wrong, because **commandId could be used only once**. You activate offer with commandId **8a001250-cc2a-4624-9319-5c2146633813** on **2020-01-30 07:13:57.381**.

**Comment by 07adityasingh** [comment]
i have an issue when getting https://api.allegro.pl/sale/shipping-rates/63996658 error occur
access token 
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODA0OTEyNTMsInVzZXJfbmFtZSI6IjYzOTk2NjU4IiwianRpIjoiODAzZjRlNDAtZjUzMy00YTA4LWI5YzgtMzcwNmZmNDZjODgzIiwiY2xpZW50X2lkIjoiYjU4N2M2ZWIwYWUzNDNiYzk5Zjk1YjE1MzA2YWY1NjYiLCJzY29wZSI6WyJhbGxlZ3JvX2FwaSJdfQ.QM3lx-A__Ni-VxEdLmZleXeZuB4oHykkHo6SVqIX_Bmar6WYr_y7MQb23UQUgM_D-cdidAsEAeQmUVtCUNImWnMGFrNNBJYqJK2LCpqEW_Lp33wqIop_xLsoKDkAq1cu6t5knj2H6d2ZFII7Z5GiZPiD_rxxjrHJGtX_TdlwYiOJcVSC_5cvBLr8482GlgqqHTVelsQAEzoE3sgA4guqC3HG1p5hbWl35MTT4DMTl7Ld6CZT1ihZ2jq86i6R5o99PnOjQCBkBavFNIE_zp-7NTX32ti6KJjTrKmJKxtUEK6BH4mDpeyCcAi0YsF4WrfT0kFOhyUcIFSGsL_R2Co2rA
