### ISSUE TITLE
jeden Client Id  i wiele instancji sklepu 

### ISSUE THREAD

**Issue by goliatek86** [allegro/allegro-api#2766]
Witam

mam pytanie czy istnieje możliwość korzystania z jednego client id client secret ( czyli jednego konta na koncie głównym ) w celu by wielu klientów posiadaczce swoje strony ( i konta na allegro ) mógłby bezpośrednio ze swoich stron z niego korzystać ?

Dokładniej:

Posiadamy swoja platformę sklepową z których korzysta wiele klientów. W zamyśle jest to by oni ze swoich sklepowych serwerów mogli bezpośrednio łączyć się przez naszą aplikację z Allegro.
Kwestia jest taka ze wszystkie żądania  wystawianie aukcji pobieranie dziennika miało by miejsce od strony serwera klienta. czyli 

My rejestrujemy aplikacje podaję adres zwrotny do naszego severa, nasz server przesyła akcces token i refresh token do servera klienta, a ten już bezpośrednio wykonuje operacje ( pobierani aukcji pobieranie offers itp ) więc nasz serwer tylko uczestniczy z tym by uzyskać te tokeny i ew w tym by otrzymać refresh token

czy jednak musi być tak. ze każdy z naszych klientów musi utworzyć swoją aplikacje ( by mieć client id ) i od strony swoich serwerów muszą dokonywać autoryzacji i dopiero wtedy mogą wystawiać itp. ( w przypadku WEBAPI tak było )

patrząc na formę requesta gdzie podajemy tylko token podejrzewam ze w tym wypadku każdy klient będzie musiał osobno sobie wygenerować client id i secret id ?

Moi programiści mówią ze w przypadku gdy każdy sklep z osobna u siebie obsługuje allegro to nie ma możliwości korzystania tylko z jednego client id i client secret bo jest kontrola po ip czy domenie do tych danych, a ja chciałbym uniknąć tego by każdy klient musiał by tworzyć tą aplikacje i generować dane
( Zależało by mi na tym ze po prostu na swojej instancji sklepu. klikał powiąż sklep z allegro i działa, i ze wszystkie operacje odbywają się na ich serwera, bez obciążania naszego serwera pośredniego

jeżeli coś zbyt lakonicznie napisałem to proszę o informacje

**Comment by pskz** [comment]
Jeśli nie pasuje Ci wykorzystanie serwera pośredniczącego do "code flow", w którym trzeba podać adres zwrotny, to zostaje autoryzacja typu "device flow", korzystam z tego samego powodu i zdaje egzamin.

https://developer.allegro.pl/auth/#DeviceFlow

**Comment by PatrykBocian** [comment]
@goliatek86  Z jednego klucza (**clientId**) może korzystać wielu userów. Jednak jeśli sposób autoryzacji opisany w [naszym poradniku](https://developer.allegro.pl/auth/#app) nie spełni oczekiwań - to co napisał @pskz  także będzie rozwiązaniem dla twojej sytuacji.

**Comment by PrzemyslawLukanowski** [comment]
@goliatek86 Prześlij dodatkowo swoje zgłoszenie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) oraz napisz, jaką aplikację reprezentujesz. W tickecie dopisz numer zgłoszenia - GitHub #2766. Wrócimy do Ciebie z odpowiedzią.
