### ISSUE TITLE
Problem z wygenerowaniem opisu i wystawieniem aukcji z poziomu sklepu internetowego.

### ISSUE THREAD

**Issue by SCDSSO** [allegro/allegro-api#2767]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

description.sections[0].items[1].content: Invalid HTML subset - problem
Przy próbie uproszczenia opisu utworzonego na stronie sklepu podczas wygenerowania opisu na allegro wyrzuca nam błąd. 
W 2 stronę, jeżeli wystawimy na allegro i opis zaciągamy na stronę to działa poprawnie.
![response_allegro_20200124_103526](https://user-images.githubusercontent.com/56715818/73060167-90e2fc00-3e97-11ea-8bdf-1746d1a78bdc.png)
![błąd](https://user-images.githubusercontent.com/56715818/73060168-90e2fc00-3e97-11ea-81e8-76a4800ff592.png)
![request_allegro_20200124_103526](https://user-images.githubusercontent.com/56715818/73060169-90e2fc00-3e97-11ea-831c-eba4fb224933.png)

**Comment by PatrykBocian** [comment]
Przekazujesz błędnie zawartość w **description** np. przekazujesz niedozwolone tagi - div, article oraz wartości dla CSS itp. Możesz tam przesłać tylko niektóre z [znaczników HTML](https://developer.allegro.pl/sale/#step-5-description). Przykładowy opis:
```
 "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>TEST<b>TEST</b>, TEST<b>TEST</b> TEST <b>OPIS</b> TEST.</p>"
                    }
                ]
            },
}
```
 
 Więcej informacji na ten temat znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST).

**Comment by SCDSSO** [comment]
Hmmm, taki kod nam się tworzy po zaimportowaniu opisu z allegro na stronę. I na stronie wszystko wygląda w porządku. Z kolei jak chcemy tego opisu użyć do ponownego wystawienia aukcji to nie przepuszcza nas do wystawienia na allegro. Dodam, że opisy na stronie wyglądają identycznie jak mamy na allegro.

**Comment by PatrykBocian** [comment]
Jeśli próbujesz skopiować kod prosto ze strony i w takiej postaci przesłać go poprzez API - taki sposób nie zadziała, możesz wykorzystać tylko te znaczniki HTML, o których wspomniałem wcześniej. Pobierz ofertę za pomocą zasobu **GET /sale/offers/{offerId}**, zobaczysz, w jakiej formie zaprezentowany jest opis. Następnie prześlij całą ofertę za pomocą zasobu **PUT /sale/offers/{offerId}**.
