### ISSUE TITLE
Jak użyć /pricing/offer-fee-preview ???

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#2768]
Chcę sprawdzić jaka jest prowizja dla poszczególnych wystawionych moich aukcji.
Gdzie znajdę jakiś przykładowy kod jak użyć tego zasobu. Szukałem i nic nie znalazłem? Czytam dokumentację i nie bardzo rozumiem jakie parametry mam podać? Name - name of the offer. Tytuł oferty? Tytuł swojej aukcji, czy dowolnej z Allegro? Co jeśli mam 2 identyczne aukcje o takim samym tytule, chętnie zobaczę jakiś przykład to wtedy może mi się coś rozjaśni.
Dzięki za wszelkie podpowiedzi

**Comment by PatrykBocian** [comment]
Przykładowy kod znajdziesz w [dokumentacji](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST). Aby najprościej skorzystać z tego zasobu, możesz najpierw pobrać ofertę, którą chcesz sprawdzić za pomocą **GET /sale/offers/{offerId}**. Wtedy w body przekazujesz:

```
{
"offer": 
W tym miejscu wklejasz to, co otrzymałeś w response z zasobu GET /sale/offers/{offerId}
}
```

**Comment by juhacz** [comment]
> najpierw pobrać ofertę, którą chcesz sprawdzić za pomocą **GET /sale/offers/{offerId}**. 

To była informacja kluczowa. Dziękuję.

**Comment by nowyyy31** [comment]
Udało mi się pobrać informacje o aukcji i dodałem { "offer": \\dane \\ } 

I mam taki ciąg znaków

```
{ "offer": {"id":"7680552280","name":"TELEFON KOMÓRKOWY BRIO TOUCH","category":{"id":"170"},"product":{"id":"1c403f1b-a3c2-4f1b-9ef1-875899b08acd"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["TEOLIKBRIOTOUCH"],"rangeValue":null},{"id":"202685","valuesIds":["202685_212933"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["5903978376243"],"rangeValue":null},{"id":"127448","valuesIds":["127448_14"],"values":[],"rangeValue":null},{"id":"202749","valuesIds":[],"values":["12"],"rangeValue":null},{"id":"202869","valuesIds":["202869_233054"],"values":[],"rangeValue":null},{"id":"202865","valuesIds":["202865_214157"],"values":[],"rangeValue":null},{"id":"4388","valuesIds":["4388_4"],"values":[],"rangeValue":null},{"id":"202717","valuesIds":[],"values":["1234"],"rangeValue":null},{"id":"219","valuesIds":["219_2"],"values":[],"rangeValue":null},{"id":"202821","valuesIds":["202821_213909"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"

etest
"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1159a8/0d0987f34863a6bbf639ef9c557b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"100","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":{"percentage":null,"rate":null,"subject":"GOODS","exemption":null,"id":"ca6761f0-d7eb-4831-b809-6debbd957686"},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"4ea10621-2edc-4ece-b2f8-136b61306bf3"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"cfd66b12-86ca-4161-8093-861461e80c2e"},"returnPolicy":{"id":"ea60b889-dedc-44e9-9701-62da7b733958"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":true,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"POMORSKIE","city":"Sianowo","postCode":"83-328"},"external":null,"attachments":[],"contact":null,"validation":{"errors":[],"warnings":[],"validatedAt":"2021-07-02T12:15:02.696Z"},"createdAt":"2021-07-02T12:11:53.000Z","updatedAt":"2021-07-02T12:15:02.698Z"}}
```


I jak wysyłam go przez curl to otrzymuję komunikat: 
`{"errors":[{"code":"NotSupportedException","message":"Unsupported content type. Please check 'Content-Type' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}`

Gdzie popełniam błąd w kodzie:

`    $getUrl = "https://api.allegro.pl.allegrosandbox.pl/sale/offers/7680552280";

    $ch = curl_init($getUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
 //   var_dump($mainResult);
  /*  if ($mainResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }*/
	print_r($mainResult);
	$data='{
	"offer": '.$mainResult.'}';
    //$data = json_decode($mainResult);
echo '<hr>';
print_r($data);
    $getUrl = "https://api.allegro.pl.allegrosandbox.pl/pricing/fee-preview";

    $ch = curl_init($getUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	echo '<hr>';
		print_r($mainResult);`
