### ISSUE TITLE
Jakość sprzedaży w REST

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#2769]
Witam, czy planowana jest możliwość pobrania raportu Jakości sprzedaży?

**Comment by PatrykBocian** [comment]
Pojawiły się już sugestie w tej sprawie - dopisze także twoje zgłoszenie. Jeśli zdecydujemy się na taką funkcjonalność to oczywiście poinformujemy o tym na forum.

**Comment by podniesm** [comment]
Podbijam temat. Czy i kiedy będzie możliwość pobierania przynajmniej całościowej ilości punktów dopowiadającej jakości sprzedaży?

**Comment by AureliuszBrussy** [comment]
@podniesm na tę chwilę nie mamy tego w planach. Mamy już [taką sugestię](https://github.com/allegro/allegro-api/discussions/4399) w zakładce Discussions. Zachęcam do oddania swojego głosu, jeżeli jesteś zainteresowany taką funkcjonalnością.

**Comment by pliszka** [comment]
Propsuję pomysł, nam też by się mega przydało by nie trzeba było co jakiś czas przeglądać słupków tylko mieć je w apce po naszej stronie

**Comment by AureliuszBrussy** [comment]
@pliszka planujemy w przyszłości wdrożenie zasobów do śledzenia Jakości Sprzedaży. Aktualnie nie jestem jednak w stanie podać konkretnego terminu. Oczywiście zakomunikujemy to wdrożenie.

**Comment by mskiba03** [comment]
Czy ta przyszłość może już nadeszła?

**Comment by AureliuszBrussy** [comment]
Niestety, ale jeszcze nie - jak pewnie wiesz, wciąż nie udostępniliśmy tych funkcjonalności w publicznym API. Jeżeli coś się zmieni, będziemy to oczywiście komunikować i damy znać [w sugestii](https://github.com/allegro/allegro-api/discussions/5341).
