### ISSUE TITLE
Format zwracanego błedu

### ISSUE THREAD

**Issue by blitzerpl** [allegro/allegro-api#2771]
W dokumentacji (https://developer.allegro.pl/about/#errors) możemy przeczytać, że błędy zostaną zwrócone w formacie:
`{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}`

natomiast w odpowiedzi na błędny request np dla endpointa: https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?limit=100&offset=0&lineItems.boughtAt.gte=2019-10-05T13:44:40.456Z

dostaję następujący json:
`{
    "error": "invalid_token",
    "error_description": "Cannot convert access token to JSON"
}`

Jaki więc jest poprawny format błedu, który mamy obsłużyć i odczytać?

**Comment by PatrykBocian** [comment]
W przypadku kiedy otrzymujesz taki błąd, najprawdopodobniej korzystasz z tokena Sandboxowego i próbujesz użyć go na produkcji.  Rozkoduj ten token i upewnij się, że korzystasz z właściwego. 

Co do formatu odpowiedzi z błędami - jest to prawidłowe zachowanie. Format, który przesłałeś dotyczy błędnego wykorzystania zasobów, a nie błędów na etapie autoryzacji. Więcej informacji na temat tego przypadku znajdziesz [tutaj](https://developer.allegro.pl/faq/#autoryzacja).

**Comment by blitzerpl** [comment]
Nie chodzi mi o samą wiadomość w przypadku tego błedu, to tylko przykład, aby pokazać różnicę formatów. Wiem co oznacza. Czyli rozumiem, że w przypadku błędów autoryzacji dostanę błąd w formacie:
`{ "error": "invalid_token", "error_description": "Cannot convert access token to JSON" }`
natomiast w pozostałych przypadkach:
`{ "errors": [ { "code": "NotAcceptableException", "message": "An error has occurred", "details": null, "path": null, "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji." } ] }`

Nie widzę tego szczegółu nigdzie w dokumentacji, może warto byłoby to doprecyzować.

**Comment by PatrykBocian** [comment]
Dziękujemy za uwagę, przyjrzymy się temu bliżej.

**Comment by Onixarts** [comment]
Tylko nie zmieniajcie tych formatów bo się nam kod prezentujący błędy wywali ;)
