### ISSUE TITLE
order/event-stats

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#2772]
Występuje problem: 
 - [X] z zasobem REST API

Od 1,5h w order/event-stats mam tę samą wartość: _1580070816730063_
Sprzedaż w tym czasie leci. Zamówienia się pojawiają na mailu. Natomiast event-stats stanąl jak zaklęty. A jak odpytać order/events?from='1580070816730063'&limit=10 zwraca pustą tablicę bez błędów:
```
stdClass Object
(
    [events] => Array
        (
        )

)

```
Czy mógłby ktoś z Allegro sprawdzić dlaczego dzienniki stanęły ? Dotyczy wszystkich moich kont, pozycja dziennika z konta _mARTa-project_

**Comment by creative-pl** [comment]
Problem dotyczy również /orders/checkout-forms, nie zwraca formularzy od 20:05 (j.w od półtorej godziny)

**Comment by najdek** [comment]
Problem wciąż występuje.
U mnie /order/checkout-forms nie zwraca formularzy złożonych po 21:01 (już 3 godziny)

**Comment by mPiter2019** [comment]
Bez zmian. Będzie wesoła noc.

**Comment by creative-pl** [comment]
Zdaje się że po północy (00:50) wróciło do normy, u was też?

**Comment by PatrykBocian** [comment]
Wystąpiły problemy techniczne w nocy z dnia 26.01-27.01 - około godziny 00.40 wszystko wróciło do normy. Przepraszamy za utrudnienia.
