### ISSUE TITLE
Problem z aktywacją auckji

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#2773]
U jednego z naszych klientów mamy problem z aktywowaniem aukcji. U innych ta sama aplikacja i ten problem nie występuje. Po wysłaniu requesta np:
"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"8895972328"}],"type":"CONTAINS_OFFERS"}]}
Dostajemy odpowiedź
{"id":"3266ec02-7050-4783-a3c0-3e33f1728f96","taskCount":{"total":0,"success":0,"failed":0}}
W kodzie błędu mamy przeważnie jedną z odpowiedzi:

10054 - Connection reset by peer
lub też 
Connection closed gracefully.

Potem jeszcze 
https://api.allegro.pl/sale/offer-modification-commands/3266EC02-7050-4783-A3C0-3E33F1728F96/tasks
, który nie zwarca odpowiedzi.

U innych klientów nigdy nie pojawia się taki problem tylko u jednego.
Problem nie pojawia się niestety za każdym razem tylko losowo i bywa często, że aktywacja przebiega prawidłowo, co może być przyczyną ? Czy możecie sprawdzić o co chodzi bym mógł to poprawić lub coś odpisać klientowi na zgłoszenie? Czy może jego antywirus ESET ucinać połączenia co by dawało takie objawy?

**Comment by PatrykBocian** [comment]
Zweryfikowałem Twój przypadek - nie wykryłem żadnych błędów, związanych z tą ofertą po naszej stronie, oferta ma status “**ACTIVE**”.  Zasób ten działa asynchronicznie, dlatego może zaistnieć sytuacja, gdzie otrzymujesz w odpowiedzi same 0 i nie należy tego traktować jako błąd.
W twoim przypadku widać, że **2020-01-27T08:28:21.406** przy odpytaniu zasobu  o status taska - został zwrócony status “**SUCCESS**”.

**Comment by WGRINGO** [comment]
W takim razie skoro żądanie jest ok, po stronie Allegro jest ok to skąd może brać komunikat  w odpowiedzi:
10054 - Connection reset by peer
lub też
Connection closed gracefully.
Czyżby coś ucinało połączenie przed odebraniem jej w całości ?

**Comment by WGRINGO** [comment]
Kolejny przykład,
{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"8899001652"}],"type":"CONTAINS_OFFERS"}]}
Tym razem w odpowiedzi pusto przez aplikacja zwróci błąd. Podjerzewam, że po wyskoczeniu błędu klient probuje ponownie i w końcu aukcja się aktywuje prawidłowo, ale widać że nie są to rzadkie przypadki, a ja po prostu potrzebuję wskazówki gdzie szukać przyczyny.

**Comment by PatrykBocian** [comment]
Po dalszej weryfikacji pierwszego przypadku zauważyliśmy dodatkowe dane binarne, przekazywane do JSON-a podczas wysyłania requestu. Prawdopodobnie problem jest po stronie aplikacji, stąd też otrzymane błędy. W drugim zgłoszeniu występuje ten sam problem. Przyczyny mogą być różne, być może jakiś wirus na komputerze.

**Comment by WGRINGO** [comment]
Ok dziękuję za informację, sprawdzę dokładniej co jest wysyłane w reuqueście.
