### ISSUE TITLE
Formularz dostawy ze statusem FILLED_IN CASH_ON_DELIVERY

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2774]
Dzień dobry,

Mam pytanie odnośnie zamówienia 11c9b051-3d50-11ea-83da-5f347debe724 w jaki sposób użytkownik może wypełnić formularz dostawy z kilkoma ofertami status formularza to FILLED_IN i typ płatności to CASH_ON_DELIVERY. W jakim momencie status zmienia się na READY_FOR_PROCESSING? W jaki sposób mogę odtworzyć taki przypadek?
Dodam, że są to licytacje

**Comment by PatrykBocian** [comment]
Zweryfikowałem Twoje zgłoszenie - zamówienie jest w statusie **READY_FOR_PROCESSING**,  user zakupił dodatkowe przedmioty w ramach jednego zamówienia dlatego powstał nowy checkout-form o id **7c8ddcb1-4073-11ea-b0de-3d78ba51d6cf,** a próba odpytania **11c9b051-3d50-11ea-83da-5f347debe724** kończy się **statusem 404** .

Zamówienie 1**1c9b051-3d50-11ea-83da-5f347debe724** zawierało przedmioty z czterech ofert, user wypełnił formularz i wskazał metodę dostawy, ale nie sfinalizował transakcji. Następnie udało mu się wygrać trzy kolejne licytacje, po czym połączył wszystkie wygrane oferty i dokończył realizację zamówienia. 

W tym momencie wspomniany przez Ciebie checkout-form ze statusem **FILLED_IN** przestaje istnieć,a  powstaje nowy **7c8ddcb1-4073-11ea-b0de-3d78ba51d6cf** w statusie **READY_FOR_PROCESSING**.
Takie sytuacje mogą się zdarzyć gdy:

- Kupujący złoży ofertę np. w dwóch różnych licytacjach,
- Po zakończeniu licytacji, dla jednej wybierze sposób dostawy i formę płatności (nie sfinalizuje jej),
- Połączy oba zakupy w jedno zamówienie - każde z nich wcześniej miało swój **checkout-form**, w tym momencie jest on usuwany i nadany nowy.

Status **READY_FOR_PROCESSING** pojawia się w momencie sfinalizowania płatności - mamy wtedy pewność, że dane dostawy nie zostaną zmienione. Więcej informacji na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/).
