### ISSUE TITLE
Odpowiednik itStartingQuantity w REST API

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#2776]
W wygaszanej funkcji doGetItemsInfo jest pole itStartingQuantity zawierające ilość początkową w ofercie. Czy planujecie dodać jego odpowiednik do REST Api? Jeśli nie, to rozumiem, że jedyną alternatywą by otrzymać tę wartość to dodanie liczby zakupionych sztuk, pobierając wcześniej zamówienia?

**Comment by PatrykBocian** [comment]
Zgłosiłem twoją sugestię do odpowiedniego zespołu - jeśli wprowadzimy taką funkcjonalność, poinformujemy o tym na forum. Sposób, o którym wspominasz może nie wystarczać. Trzeba uwzględniać jeszcze np. zmianę liczby sztuk.

**Comment by jzskyshop** [comment]
W takim razie spytam też o odpowiednik pola itBidCount - zwracało ilość ofert dla aukcji/zamówień.

**Comment by PatrykBocian** [comment]
Możesz sprawdzić liczbę ofert za pomocą **GET /sale/offers** - podaj w parametrze wyszukiwania **offer.id.** W odpowiedzi w polu **saleInfo.biddersCount** znajdziesz liczbę osób, które licytują przedmiot, a w polu **saleInfo.stock.sold** sprzedaż z ostatnich 30 dni. Więcej informacji na temat tego zasobu znajdziesz w naszym [poradniku](https://developer.allegro.pl/my_offers/).
