### ISSUE TITLE
Payment mapping zwraca 404 dla istniejącej płatności

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#2777]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Wywołanie `payments/payment-id-mappings?paymentId=b0555339-3faf-11ea-b2ce-eb955504df93` zwraca 404 mimo istniejącej płatności. Taka płatność istnieje i jest w zamówieniu `3ba6387a-3fae-11ea-8333-d1f95e797c51`

Czy to poprawne zachowanie? Zamówienie jest w statusie *FILLED_IN* i płatność nie doszła do skutku (paidAmount = null). Czy transactionId będzie dostępny dopiero po poprawnym opłaceniu?

**Comment by PatrykBocian** [comment]
Weryfikuje Twoje zgłoszenie - wrócę z odpowiedzią, gdy tylko się czegoś dowiem.

**Comment by PatrykBocian** [comment]
W Twoim przypadku nie dało się zmapować tej płatności, ponieważ została anulowana przed jej sfinalizowaniem i porzucona na rzecz kolejnej płatności. **PaymentId**, które powinno się zmapować to **55b42470-3fae-11ea-b2ce-eb955504df93**.

W przypadku kiedy płatność nie jest rozliczona mogą się zdarzać takie przypadki.
