### ISSUE TITLE
Allegro smart na sandbox

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#2778]
Witam, mam problem z aktywacją Allegro Smart na koncie.
Postepuje według wytycznych które są podane [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV)
Nie mam dostępu do panelu z jakością sprzedaży, oceny mam powystawiane, mam dodane 2 metody dostawy smart (Allegro paczkomaty oraz DPD)
ID allegro-sandbox 44089269.
Jest jakaś możliwość weryfikacji?

**Comment by PatrykBocian** [comment]
Sprawdziłem Twój przypadek - masz tylko jeden unikalny komentarz, a potrzeba ich 5. U Ciebie wszystkie są od tego samego użytkownika.

**Comment by AssAssIn1909** [comment]
ehh,
pod słowami unikalne komentarze skrywa się hasło komentarze od unikalnych użytkowników. A już myślałem ze to będzie takie proste
