### ISSUE TITLE
NIP na paragonie

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#2779]
Witam,
Czy istnieje możliwość podania numeru nip bez faktury?
Aktualnie z tego co testuje, aby podać nip muszę zaznaczyć pole że chce fakture VAT. Jednak jak wiemy, zmieniły się przepisy i numer NIP może też znaleźć się na paragonie, w celu późniejszej możliwości otrzymania faktury.
Czy jest jakieś pole podczas zakupu do którego to można podać oraz później jakieś pole w API skąd mogę to pobrać? Aktualnie nic takiego nie widzę.
Z góry dziękuje.

**Comment by PatrykBocian** [comment]
Nie ma takiej możliwości zarówno poprzez API jak i w przeglądarkowej wersji serwisu.

**Comment by AssAssIn1909** [comment]
A czy planujecie taką możliwość? Możliwość dodania numeru nip bez faktury?

**Comment by pkrzemo** [comment]
@AssAssIn1909 A czy na pewno potrzebujesz? Faktury uproszczonej (paragon z NIPem) nie można stosować do sprzedaży wysyłkowej...

**Comment by AssAssIn1909** [comment]
@pkrzemo hmm, chyba muszę doczytać co nieco na ten temat. W każdym razie, klient strasznie o to zabiega mimo że nie jest to dostępne w Allegro. Więc szukam informacji wszędzie

**Comment by PatrykBocian** [comment]
Tak jak napisał @pkrzemo - nie można stosować do sprzedaży wysyłkowej faktury uproszczonej, dlatego nie planujemy takiego rozwiązania.

**Comment by lukaszzborek** [comment]
Witam,
niestety wracam z tematem
Rozumiem ze nie ma opcji podania nipu na paragonie, ale dostałem kolejny raz pytanie o niego.

Dostaje sprzeczne informacje na temat pojęcia sprzedaży wysyłkowej.. Chciałbym to raz na zawsze rozwiązać. 

1.  Sprzedaż wysyłkowa -> sprzedaż, po której następuje wysyłka towaru do klienta w dowolne miejsce (kraj i zagranica)
2.  Sprzedaż wysyłkowa  -> sprzedaż po której następuje wysyłka towaru do klienta, ale tylko jeżeli paczka zostanie wysłana do innego kraju( jeżeli paczka wysłana zostanie w obrębie kraju to nie jest to sprzedaż wysyłkowa)

Proszę o wskazanie pojęcia które w tutaj obowiązuje.

**Comment by MaciejFrackowiak** [comment]
Niestety, wkraczamy tu w zakres interpretacji prawa, a jako Allegro nie jesteśmy podmiotem do tego uprawnionym. Być może któryś z użytkowników miał już podobne wątpliwości i podzieli się z nami uzyskaną odpowiedzią.
