### ISSUE TITLE
Swagger.json

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#278]
Hej!
Czy jest możliwość pobrania pliku typu swagger.json? Według informacji na waszym githubie
"Documentation should be compatible with swagger spec 2.0 and should be accessible under a well-known endpoint (e.g. service-host/swagger.json)."

Niestety nie mogę znaleźć linka z takim plikiem.

**Comment by MaciejPotepa** [comment]
Cześć 

Niestety nie pobierzesz tego pliku w rozszerzeniu .json ponieważ korzystamy już ze swaggera w wersji 3.0, ale za to dostępny jest  .yaml - do pobrania [tutaj](https://developer.allegro.pl/swagger.yaml).

**Comment by adamczykjac** [comment]
Byłoby super trafić do tego `.yaml`'a prosto z dokumentacji :)

**Comment by PawelTaberski** [comment]
@adamczykjac  Ok, dodamy taką informację przy najbliższym wdrożeniu na naszej stronie. Czy Twoim zdaniem dodanie takiej możliwości tutaj --> https://developer.allegro.pl/about/#rest-api ,będzie ok?

**Comment by adamczykjac** [comment]
Dokładnie, w tym miejscu byłoby ok. Tak jak kolega powyżej zauważyłem
użycie docs'ów Swaggera i myślę - 'o, nie będę musiał przepisywać modeli
ręcznie tylko wygeneruję przez `OpenAPITools/openapi-generator`'. Tym
sposobem dotarłem tutaj.

**Comment by PawelTaberski** [comment]
@adamczykjac Ok, to przy najbliższym wdrożeniu na stronę dodamy taką informację.

**Comment by Arkowsky** [comment]
Odnośnie swaggera to zrobiliśmy paczkę z wygnerowanymi modelami i authenticator-em. Wcześniej szukaliśmy takiej biblioteki bezskutecznie ale nie mogliśmy znaleźć.

Może komuś okaże się pomocne:
[](https://packagist.org/packages/coffeedesk/allegro-api-client-php)
