### ISSUE TITLE
Sandbox - zakładanie konta w serwisie

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#2780]
Zmieniły się jakoś zasady zakładania konta w Sandboxie? Po wypełnieniu formularza jest info zęby sprawdzić pocztę i na tym koniec. Nie przychodzi żaden mail, Wydaje mi się że kiedyś szło to konto założyć normalnie na stronie

**Comment by PatrykBocian** [comment]
Sprawdź proszę folder ze spamem - może tam trafił Twój link. Podaj też swój mail do Sandboxa, pomoże to zweryfikować wysyłkę wiadomości.

**Comment by przemoo83** [comment]
Nie nic z tych rzeczy. Sprawdzałem SPAM i odczekałem sporo zanim napisałem. Dodatkowo próbowałem zakładać konto z 3 różnych maili. Jeden z nich to przemekmisztal@poczta.fm

**Comment by PatrykBocian** [comment]
W tym przypadku to problemy techniczne po naszej stronie - zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją, jak tylko zostanie to naprawione.
