### ISSUE TITLE
Wygaszanie doGetItemsInfo

### ISSUE THREAD

**Issue by mtumtu** [allegro/allegro-api#2781]
W związku z wygaszaniem doGetItemsInfo mam pytanie:
Jak za pomocą REST API pobrać szczegółowe informacje o aukcji mając jej ID ?
Chodzi mi o aukcję dowolnego sprzedawcy

**Comment by PatrykBocian** [comment]
Możesz skorzystać z **GET /offers/listing** - skorzystaj z parametru wyszukiwania **seller.id** i znajdź interesującą Cię ofertę. To jedyna opcja w przypadku ofert innego użytkownika.

**Comment by mtumtu** [comment]
To rozwiązanie rodzi 2 problemy:
1. Jak uzyskać seller.id mając tylko ID Aukcji ?
2. Jak (mało) wydajne będzie takie rozwiązanie w przypadku sprzedawców mających tysiące (miliony?) aukcji ?

**Comment by PatrykBocian** [comment]
Nie możesz przekazać samego offer.id jako parametr. Aby otrzymać seller.id przekaż dodatkowe parametry, np. category.id lub phrase. Identyfikator sprzedawcy znajdziesz wtedy w polu seller.id. Wydajność to kwestia indywidualnych rozwiązań, musisz tylko pamiętać o [obowiązujących limitach](https://developer.allegro.pl/about/#limits).

**Comment by pkrzemo** [comment]
@PatrykBocian Myślę że pytającemu bardziej chodziło o wydajność WASZEGO serwera zasypywanego dodatkowymi i zbędnymi zapytaniami ...

**Comment by artzie92** [comment]
Widzę, że na marzec planowane są odpowiedniki tych metod:
Publiczne dane o ofertach
doShowItemInfoExt
doGetItemsInfo
w REST api. Rozumiem, że za pomocą publicznego tokena będę mógł skorzystac z nich i nie przechodzić po kolei po listingu.

**Comment by PatrykBocian** [comment]
@artzie92 W nawiązaniu do https://github.com/allegro/allegro-api/issues/2717 - już niebawem opublikujemy stosowny komunikat w tej kwestii, proszę o jeszcze chwilę cierpliwości.
