### ISSUE TITLE
Zasób do "ukrywania" zakończonych aukcji w REST API

### ISSUE THREAD

**Issue by hmkdbsw** [allegro/allegro-api#2782]
:bulb: **Sugestia**

Przydałby się zasób w REST API będący odpowiednikiem frontendowej funkcji "Ukryj" dla zakończonych aukcji. Obecnie, jeżeli chce się sprzątnąć aukcje z jednego miesiąca, a ma się ich sporo, trzeba kilkać przez dobre parę godzin. To jest okropne wręcz. Wnioskuję, że jakiś zasób do tego istnieje, skoro front go ma. Miło by było, gdyby i sprzedawcy uzyskali do niego dostęp.

**Comment by PatrykBocian** [comment]
Pojawiły się już takie sugestie - dopisałem także twoje zgłoszenie. Jeśli wprowadzimy taką funkcjonalność, opublikujemy odpowiedni komunikat.

**Comment by jakubmaguza** [comment]
Czy są jakieś informacje na ten temat?

**Comment by AureliuszBrussy** [comment]
@jakubmaguza opublikujemy odpowiedni komunikat, gdy tylko wprowadzimy taką funkcjonalność. Obecnie nie jest ona dostępna.
