### ISSUE TITLE
Problem z zasobem sale/blacklisted-users

### ISSUE THREAD

**Issue by pkrzemo** [allegro/allegro-api#2783]
Występuje problem: z zasobem sale/blacklisted-users
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie wiem dlaczego wywołanie jakiegokolwiek innego zasobu kończy się sukcesem natomiast zasób  **sale/blacklisted-users** zwraca nieopisany w dokumentacji błąd: StatusCode: 415, ReasonPhrase: 'Unsupported Media Type'

Czyli jeśli w wywołaniu:
 **odp = await klient.GetAsync(url);**
w zmiennej **url** przekazuję np. **https://api.allegro.pl/billing/billing-entries**
to wszystko działa poprawnie i dostaję dane zwrotne zgodnie z oczekiwaniem.

Natomiast jeśli zmienię zawartość zmiennej na **https://api.allegro.pl/sale/blacklisted-users**
to dostaję błąd 415 - 'Unsupported Media Type'

   _Headers: {x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
**trace-id: bf6bca0288907e06**
x-ratelimit-remaining: 9000
x-content-type-options: nosniff
x-ratelimit-limit: 9000
x-envoy-upstream-service-time: 27
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Wed, 29 Jan 2020 12:24:50 GMT
Server: envoy
}
    IsSuccessStatusCode: false
    ReasonPhrase: "Unsupported Media Type"
    RequestMessage: {Method: GET, RequestUri: 'https://api.allegro.pl/sale/blacklisted-users', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer eyxxxxxxxXXXXXXxxxxxx
  Accept: application/vnd.allegro.public.v1+json
  Accept-Language: pl-PL
}}_

Jestem "w kropce" bo wedle dokumentacji nie ma w tym wywołaniu, wedle tejże dokumentacji, czegokolwiek specjalnego co wymagało by innego procedowania tego wywołania.
A jednak inne działają a to nie... :-(

**Comment by PatrykBocian** [comment]
@pkrzemo Dodaj w **Headers - Content-Type: application/vnd.allegro.public.v1+json**. Rozwiąże to Twój problem.

**Comment by pkrzemo** [comment]
OK. To rozwiązuje problem... ale to jest błąd po waszej stronie.
Zasób jest typu GET. W żądaniach GET nie przesyłamy "Content", więc większość środowisk programistycznych blokuje "Content-Type". 
Np. żeby w c# ustawić Content-Type w żądaniu typu GET trzeba "zhakować" system uciekając się do "reflection":

                    var field = typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                 .GetField("invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
                             ?? typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                 .GetField("s_invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                    if (field != null)
                    {
                        var invalidFields = (HashSet<string>)field.GetValue(null);
                        invalidFields.Remove("Content-Type");
                    }
                    klient.DefaultRequestHeaders.TryAddWithoutValidation("Content-Type", "application/vnd.allegro.public.v1+json");

Bo to jest **"Invalid Header"** dla żądania typu GET.

Zresztą zachodzi pytanie.... dlaczego tylko dla zasobu **GET sale/blacklisted-users** trzeba ustawiać ten nagłówek? 
A dla innych typu GET nie trzeba ..

**Comment by PatrykBocian** [comment]
Zgłosiłem to do odpowiedniego zespołu - w najbliższym czasie to zmienimy i Content-Type nie będzie już wymagany.

**Comment by pkrzemo** [comment]
Dzięki.
Jest jeszcze problem rozbieżności pomiędzy dokumentacją a rzeczywistością.
Chodzi o "limit". W dokumentacji jest że maksymalnie **100** (

limit | integer [ 1 .. 100 ]
-- | --


) a w rzeczywistości (i w poradniku w części dot. wersji beta) jest że **25**.
**Wywołanie zasobu z limitem 100 generuje błąd**, wywołanie z limitem 25 przechodzi poprawnie.
Trzeba by to uzgodnić w tą czy inną stronę...

    IsSuccessStatusCode: false
    ReasonPhrase: "Unprocessable Entity"
    RequestMessage: {Method: GET, RequestUri: 'https://api.allegro.pl/sale/blacklisted-users?limit=100&offset=0', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer eyXXXXYYYYYYYYYYYYYYYYXXXXXXXXXXXXXXX
  Accept: application/vnd.allegro.public.v1+json
  Accept-Language: pl-PL
  Content-Type: application/vnd.allegro.public.v1+json
}}
    StatusCode: 422

**Comment by PatrykBocian** [comment]
Zasób działa już prawidłowo bez podawania Content-Type. Co do limitu - zmieniliśmy wartość na zgodną z dokumentacją.
