### ISSUE TITLE
jaki zasób otwierać by znaleźć EAN sprzedanego u siebie produktu 

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#2784]
Witam serdecznie! Pytanie jak w tytule, czy jest jakiś zasób umożliwiający pobranie numeru EAN uzupełnionego przy wystawieniu aukcji? Chodzi o aukcje zakończone sprzedane na moim koncie. Jakoś nie mogę się tego doszukać w dokumentacji.

**Comment by pkrzemo** [comment]
GET /sale/offers/{offerId}

https://developer.allegro.pl/documentation/#operation/getOfferUsingGET

**Comment by PatrykBocian** [comment]
@marcinja2 Jest tak jak pisze @pkrzemo - w response dostaniesz pole: **"ean": "string"**.

**Comment by marcinja2** [comment]
dzięki Panowie, jakiegoś zamroczenia chyba dostałem albo chyba juz za duzo pracy... :/
