### ISSUE TITLE
Pytanie o popularity

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2785]
Na stronie w dokumentacji jest napisane, że dla parametru popularność sortowanie odbywa się na poniższej zasadzie.
**O kolejności wyników wyszukiwania decyduje liczba złożonych ofert kup teraz i liczba licytujących w ostatnich 30 dniach. Jeżeli kilka przedmiotów ma ich tyle samo, wtedy sortowanie odbywa się po czasie, jaki pozostał do zakończenia oferty.**

Jak wyliczane są ostatnie 30 dni? Od godziny 00:01 do godziny 23:59. Czyli czy dokładność jest do jednego dnia, do jednej godziny, do jednej minuty, brane pod uwage są dokładne czasy zakupów? 

Pozdrawiam

**Comment by PatrykBocian** [comment]
Pod uwagę brane są dokładne daty  zakupu (co do sekundy) - na bieżąco przeliczamy popularność.

**Comment by artzie92** [comment]
A czy jest jakaś opcja żeby sprawdzić na nowym API ile użytkownik sprzedał towaru w ciągu dnia? Czy jedynym parametrem opisującym sprzedaż jest popularity?
Czy nowa metoda: **Dziennik zdarzeń w ofertach z całej platformy** będzie miała opcje pobrania audytu oferty za pomocą public token? 
Pozdrawiam

**Comment by PatrykBocian** [comment]
Odpowiadając na Twoje pytania:

- Nie posiadamy takiej funkcjonalności,
- na tę chwilę nie znamy kształtu tego zasobu w REST API. Zaktualizowaliśmy nasz [harmonogram ](https://github.com/allegro/allegro-api/issues/2796)w tym temacie.

**Comment by artzie92** [comment]
Ok czyli metody 
Lista kupujących w ofercie
doGetBidItem2
Publiczne dane o ofertach
doShowItemInfoExt
doGetItemsInfo

Będą dostępne mniej więcej do końca roku. Dzięki za informację.
