### ISSUE TITLE
Błędne dostępne ilości na aukcji

### ISSUE THREAD

**Issue by AssAssIn1909** [allegro/allegro-api#2788]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

Podczas sprawdzania dostępnych ilości na sandbox, trafiłem na ciekawe rozbieżności przy 2 requestach.
w ofercje 6206816073 dostępne ilości to 2
/sale/offers/6206816073 zwraca dostępne ilości 2
/sale/offers zwraca dostępne 4, sprzedane 2

W pierwszej wchwili myślałem ze w drugim przypadku to odejmuje się te 2 ilości jednak porównałem z aukcją produkcyjną i tam ilości dostępne były takie same, mimo sprzedaży.

Powoduje to kolejny problem gdy chce zaktualizować ilość z 2 na 1 poprzez zasób /sale/offer-quantity-change-commands, ponieważ dostaje informacje że Liczba sztuk nie może być mniejsza od liczby sprzedanych przedmiotów. ( przykładowy commandId d54cd002-3652-40d4-9d91-f57489986acf)
Co ciekawe jeżeli zmienie na ilość 5 (fixed) to ilość dostępna na aukcji to 3.

**Comment by PatrykBocian** [comment]
Weryfikuje Twoje zgłoszenie - jak się czegoś dowiem wrócę z odpowiedzią.

**Comment by AssAssIn1909** [comment]
Witam, jakieś wieści?

**Comment by PatrykBocian** [comment]
Zweryfikowałem Twoje zgłoszenie - rzeczywiście występuje tu rozbieżność danych. Przekazałem to do odpowiedniego zespołu w celu dalszej weryfikacji.
