### ISSUE TITLE
Rozszerzenie pola externalId do 256 znaków

### ISSUE THREAD

**Issue by haloween** [allegro/allegro-api#2789]
:bulb: **Sugestia**

Stosujemy pole externalId do parowania indeksów z systemu ERP z aukcjami allegro, zazwyczaj trzymamy w nim formulacje produktów w oparciu o EAN, jednakże przy niektórych produktach złożonych ilość miejsca jest zbyt mała. Jedna pozycja prod złożonego to u nas 18-19 znaków, przy 7 indeksach w karcie  ze znakami separacji kończy się nam miejsce po 5 .... 

Przykład sprawdźcie w aukcji 7858337547
Tam mamy limit do 100, a formulacja ma ~130 znaków ..

**Comment by pkrzemo** [comment]
Znając prawo Murphiego to i 256 znaków będzie wam za mało...
LOL
A nie możecie trzymać sobie tabelki z "formulacjami" u siebie?
Wówczas wystarczy wam zwykły "int" w external-id ....
;-)

**Comment by haloween** [comment]
> Znając prawo Murphiego to i 256 znaków będzie wam za mało...
> LOL

"Murphy'ego" ROTFL

> A nie możecie trzymać sobie tabelki z "formulacjami" u siebie?
> Wówczas wystarczy wam zwykły "int" w external-id ....
> ;-)

Dzięki Sherlocku. Że ja na to nie wpadłem. Jakby tak było to bym trzymał tam INT. Ale tak nie jest.

Long story short: kluczujemy po EAN. A dla zestawów nie mamy kart towarowych tylko je robimy "w locie".

Typowa formulacja wygląda tak:
5903246220858-1-16;5903246222036-1-14;5902232619355-1-14;5903246222074-1-14;5903246222227-1-14;5903246222067-1-14;5903246222166-1-14

Do tego korzystamy z 3 róznych aplikacji (systemy obsługi zamówień / system zarządzania stanami synchronizujące stocki dla paru innych aplikacji / desktopowy soft do zarządzania). I nie - nie możemy mieć jednej.

Ale za to - w ten magiczny sposób mamy jednolity format danych towaru dla rónych systemów i każdy soft umie to sobie rozłożyć na czynniki 1 bez dostępu do innego oprogramowania.

**Comment by pkrzemo** [comment]
A może Łotsonie zakodujesz sobie np. w base 64, czy innym kodem i ci się string "zszortuje"...
LOL

**Comment by haloween** [comment]
> A może Łotsonie zakodujesz sobie np. w base 64, czy innym kodem i ci się string "zszortuje"...

Jak nie masz nic ciekawego do dodania to zajmij się swoimi sprawami.
Pozdrawiam

**Comment by haloween** [comment]
> LOL

132 znaki
5903246220858-1-16;5903246222036-1-14;5902232619355-1-14;5903246222074-1-14;5903246222227-1-14;5903246222067-1-14;5903246222166-1-14

To w base 64

NTkwMzI0NjIyMDg1OC0xLTE2OzU5MDMyNDYyMjIwMzYtMS0xNDs1OTAyMjMyNjE5MzU1LTEtMTQ7NTkwMzI0NjIyMjA3NC0xLTE0OzU5MDMyNDYyMjIyMjctMS0xNDs1OTAzMjQ2MjIyMDY3LTEtMTQ7NTkwMzI0NjIyMjE2Ni0xLTE0

176 znaków

**Comment by pkrzemo** [comment]
To są moje sprawy, bo baza mi spuchnie jak zwiększy się to pole...
;-)
A może HEX?
5903246220858=55E74E4DE3A

**Comment by haloween** [comment]
> To są moje sprawy, bo baza mi spuchnie jak zwiększy się to pole...

int trzymaj...

**Comment by pkrzemo** [comment]
Nie mogę bo klienci wpisują co chcą bezpośrednio w Allegro i muszę im to pokazywać w systemie, jak będę to trzymał w dodatkowej tabelce to baza spuchnie mi jeszcze bardziej...
;-)

**Comment by rtnet-pl** [comment]
Pewnie się z tym nie przebijesz.
My robimy tak że po stronie erp (subiekt, wapro) operator zakłada produkt o rodzaju "zestaw"/"komplet" ze składnikami z paczki. Ten zestaw ma w ERP swój indeks (możesz wygenerować sobie swój ean wirtualny), ilości do wysłania są wyliczane na podstawie ilości składników. Dodatkowo możesz dać inną cenę na taki produkt niż wynika z sumy składników.

**Comment by PatrykBocian** [comment]
@haloween Zgłosiłem Twoją sugestię do odpowiedniego zespołu. Gdybyśmy zdecydowali się na taką zmianę, opublikujemy newsa na forum.

**Comment by haloween** [comment]
> @haloween Zgłosiłem Twoją sugestię do odpowiedniego zespołu. Gdybyśmy zdecydowali się na taką zmianę, opublikujemy newsa na forum.

Dzięki, czekamy na info.
