### ISSUE TITLE
Kod błędu: ERR_BLOCK_SELL_COMPANY_INFO

### ISSUE THREAD

**Issue by FioreFresco** [allegro/allegro-api#279]
Na moim koncie allegro mam informacje, że konto jest firmowe i jest potwierdzone, niestety kiedy próbuje wystawić aukcje wyskakuje mi taki komunikat:
Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert. doCheckNewAuctionExt - If you wish to use Allegro without limitations, we have to verify the details of your business.

Kod błędu: ERR_BLOCK_SELL_COMPANY_INFO

Dodam, że korzystam ze sklepu na platformie skyshop i integracja z API allegro przebiegła pomyślnie

**Comment by MaciejPotepa** [comment]
Podaj login lub ID konta. Bez tego nie jestem w stanie sprawdzić co jest nie tak.

**Comment by FioreFresco** [comment]
Login konta: FioreFresco

06.06.2018 15:47 "MaciejPotepa" <notifications@github.com> napisał(a):

**Comment by MaciejPotepa** [comment]
Proszę zgłoś się do nas przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt) i opisz swój problem.
