### ISSUE TITLE
Paramtery części TecDoc

### ISSUE THREAD

**Issue by Sokol26** [allegro/allegro-api#2790]
Wystawiając ofertę poprzez formularz allegro wystarczy podać numer katalogowy (część samochodowa, np GDB1330) co wypełnia wszystkie parametry i przypisuję kategorie. Ze strony Rest API wygląda to trochę inaczej.  Da się powiązać produkt tak aby nie trzeba było podawać parametrów i kategorii?

**Comment by PatrykBocian** [comment]
Na tę chwilę nie ma rozwiązania, które automatycznie wypełni te pola. Jako rozwiązanie użyj zasobu **GET /sale/products?phrase=phrase=GDB1330**. W odpowiedzi otrzymasz listę produktów powiązanych z przekazaną frazą. Wybierz id produktu, które odpowiada Twojej ofercie i przekaż je w zasobie **GET /sale/product/{productId}**. W response znajdziesz:

- identyfikator produktu (product.id),
- identyfikator kategorii,
- parametry i ich wartości parametrów,
- sekcję images,
- numer ean powiązany z produktem,
- sekcję “compatibilityList” i “tecdocSpecification”

Przekaż te dane za pomocą zasobu **PUT /sale/offers/{offerId}**.
Więcej informacji na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/productization/).
