### ISSUE TITLE
Authorization: get access_token only with refresh token? 

### ISSUE THREAD

**Issue by sj-abrams** [allegro/allegro-api#2791]
According to oauth best practices to get new access token you have to send valid refresh token.
But according to https://developer.allegro.pl/auth/ beside sending refresh token (which is required) you need to provide 'Basic auth' with client:secret. Does it make sense in general?

**Comment by PrzemyslawLukanowski** [comment]
Yes, as we wrote in our guide - "Client ID and Client Secret are needed for communication in the OAuth, protocol which – in - version 2.0 - is supported by Allegro REST API as a standard", so you need to be authorized to use refresh token.
