### ISSUE TITLE
Invalid response received from Authorization Server. Expected JSON.

### ISSUE THREAD

**Issue by krzysztofgwiazda** [allegro/allegro-api#2792]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Client error: `POST https://allegro.pl/auth/oauth/token` resulted in a `400 Bad Request` response

Problem występował od godziny 13:19 do około 15:50.
Zapytanie budowane były w poprawny sposób, dopiero za którymś razem API odpowiedziało zwracając access_token. Zapytania i odpowiedzi przesyłam przez formularz

PS. Przydałby się formularz dedykowany dla zgłoszeń API bo w obecnym trzeba wybierać jakąś kategorię niezwiązaną za bardzo z problemem

**Comment by PatrykBocian** [comment]
Jak tylko otrzymamy Twoje zgłoszenie to zweryfikujemy ten przypadek. Jeśli chodzi o formularz - kiedy zgłoszenie dotyczy API, dopisz proszę np. jak w tym przypadku **#2792**. Wtedy zgłoszenie szybciej do nas trafi. Jeśli przy obecnym zgłoszeniu, nie dopisałeś tego w opisie - możesz je przesłać jeszcze raz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by PrzemyslawLukanowski** [comment]
@krzysztofgwiazda Otrzymaliśmy Twój przykładowy request i response, jednak ilość danych jest zbyt mała, aby wskazać żródło błędu. Jaką informację otrzymałeś w polu error_description? Czy zauważyłeś, aby problem występował po dacie, którą wskazałeś?

**Comment by krzysztofgwiazda** [comment]
@PrzemyslawLukanowski Serwer odpowiadał kodem HTTP 400, nie wiem czy miało to zapytanie body czy nie bowiem biblioteka nadrzędna już wyrzucała, że nie zwracacie JSONa więc raczej również nie było w tym response wskazanego pola:
`Invalid response received from Authorization Server. Expected JSON.`

Ostatnie wystąpienie błędu:
31-01-2019 3:40 rano

**Comment by PrzemyslawLukanowski** [comment]
Jeśli błąd wystąpi po raz kolejny, prześlij proszę ponownie przykładowy request wraz z dokładnym timestampem. Na tę chwilę nie zauważyłem w naszych logach wspomnianego błędu - widzę, że 2020-01-31 o 05:16:56 udało się uzyskać prawidłowy token dla użytkownika, którego dotyczył request z formularza.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
od dzisiaj mam taki sam błąd przy wywołaniu `POST /auth/oauth/token`

```
POST /auth/oauth/token HTTP/1.1
Host: allegro.pl
content-type: application/x-www-form-urlencoded
Authorization: Basic ...

redirect_uri=.......
```

w odpowiedzi mam:

```
"HTTP/1.1 400 Bad Request
Date: Wed, 05 Feb 2020 11:20:10 GMT
Content-Length: 0
x-envoy-upstream-service-time: 3
X-Backend: captcha_frontend_2024889_dc5_56_191_31540
Age: 0
X-Req-Counter: 1
Content-Security-Policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp;
X-Hit: HIT 0
X-Origin: s50118
X-Content-Type-Options: nosniff
grace: none
X-XSS-Protection: 1; report=https://allegro.pl/seclog/xss
Set-Cookie: trace_id=ff93462e67c05238;Path=/;Max-Age=5;Secure, _cmuid=8h48fyf7-c298-5zth-y6b8-6m36k396hr0w; Expires=Fri, 04 Feb 2022 11:20:10 GMT; Path=/; Domain=.allegro.pl; Secure
X-Waf: s53131
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000
```
i puste body

**Comment by mindc** [comment]
@PrzemyslawLukanowski 

ech... i zaczęło działać....

**Comment by PrzemyslawLukanowski** [comment]
W przypadku dalszych błędów prześlij proszę pełen request, wraz z uzupełnionymi danymi, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Ułatwi to nam weryfikację zgłoszenia. Co do powyższego response - nie udało mi się powtórzyć tego błędu, w naszych logach również nie widzę powiązanego wywołania.

**Comment by krzysztofgwiazda** [comment]
@PrzemyslawLukanowski może nie w te logi patrzycie? HTTP 400 Bad Request to raczej nie zwrotka z Waszych instrukcji try/catch tylko może problem wyżej - może przeciążenie serwera, limity, coś innego... Tym bardziej że zawsze do wywołania tej metody używamy jednego i tego samego zestawu danych, nie ma tam jakiejś magii.

Ustawcie supervisora -> pytajcie zasób co 1 sek. napewno też złapiecie HTTP 400.
Jak wszystko działa to robicie test? Wtedy to i u Nas działa co nie znaczy że problem nie występuje.

**Autoryzacja kont** jest używana na tyle rzadko, że my nie jesteśmy w stanie łapać każdej niedostępności tej usługi. Konta mają działać a nie będziemy je co chwilę autoryzować - dostajemy token to robimy refresh jak wygasa a nie co sekundę. @PrzemyslawLukanowski Wy macie większe zasoby i możliwości aby ten błąd wywołać (czyt. wyżej). Macie napewno konta testowe, My nie będziemy odświeżać tokenów przy każdym request-cie w aplikacjach produkcyjnych.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten temat do odpowiedniego zespołu w celu analizy.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
od kilku minut kolejna "przerwa", czyli pusta odpowiedź z  POST /auth/oauth/token

**Comment by PrzemyslawLukanowski** [comment]
Analizujemy ten temat. Prześlij proszę przykładowy request i response przez [nasz formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dołączę je do zgłoszenia.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
przecież wrzuciłem pełny request i response w komentarzu....

BTW. o 12:32:58 wróciło do normy...
przychodzi mi jedna rzecz do głowy, może nie można odświeżać `refresh_token`, zanim rzeczywiście straci ważność?

**Comment by krzysztofgwiazda** [comment]
@mindc Raczej nie tędy druga. Jak miałeś awarię ja miałem tokeny ważne - bez błędów. Poprawiło się u Ciebie a u mnie jest błąd tuż po pierwszej próbie odświerzenie tokenu.

@PrzemyslawLukanowski Token na jednym z kont klienta wygasł o 2020-02-07 12:56:24 i tak serwer rzuca teraz pustym body.

Różne konta
Różne klucze aplikacyjne
Jedyne co łączy moje aplikacje z @mindc to jeden i ten sam serwer dedykowany. Może w tym leży problem i blokujecie jakiś ruch od Nas? My sporo danych i odbieramy i wysyłamy do Was. Może za dużo kont autoryzujemy/odświeżamy tokenów w ciągu doby?

**Comment by PrzemyslawLukanowski** [comment]
@mindc Rozumiem, tamte dane oczywiście przekazałem, miałem na myśli bieżące. Refresh_token możesz odświeżyć przed wygaśnięciem. W odpowiedzi otrzymasz nową parę access_token i refresh_token a stare utracą ważność - jeżeli spróbujesz użyć nieaktualnego refresha, w odpowiedzi otrzymasz błąd 400.
@krzysztofgwiazda Dziękuję ze spostrzeżenia, przekazuję je do zespołu, który zajmuje się analizą zgłoszenia.

**Comment by PrzemyslawLukanowski** [comment]
Problem był powiązany blokowaniem adresów IP, z których pochodziły requesty. Na narzucenie blokady wpływ miało m.in. odpytywanie masowo o GET /sale/offers/{offerId}, gdzie w odpowiedzi zwracaliśmy błąd 404. Prośba, aby nie requestować o dane, które już nie istnieją. Jeśli są to identyfikatory dawnych ofert, warto je zaktualizować lub usunąć.

**Comment by krzysztofgwiazda** [comment]
@PrzemyslawLukanowski prosiłbym o uściślenie: 
- której aplikacji dotyczy ten problem bo jest ich kilka
- jakie są te limity (ile odpowiedzi 404 musimy dostać aby otrzymać bana) i jak długi jest czas karencji
Proszę przesłać te dane w odpowiedzi na moje wiadomości wysłane do Was lub na adres allegro.api@agsystems.pl

**Comment by PrzemyslawLukanowski** [comment]
Dotyczy to klucza 30c36473e5ad*****f8283199b436ac0. Co do drugiego pytania - ze względów bezpieczeństwa nie możemy udostępnić takich informacji.

**Comment by krzysztofgwiazda** [comment]
Sprawdziłem podany klucz i akurat ta wskazana aplikacja odpytuje tylko i wyłączenie zasób: `/order/events`. W tej wskazanej nic Nam więcej nie potrzeba, więc nawet w kodzie nie mamy implementacji. Nie odpytała ona napewno zasobu /sale/offers/{offerId}. Przegrepowałem serwer pod kątem przypadkowego użycia klucza - brak innych miejsc.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za pomyłkę z mojej strony, prawidłowy klucz to 257ca89d9ba****2bc1bf272509a5697. Dzisiaj odnotowaliśmy 799 odpytania o oferty, które nie istnieją lub których user nie jest właścicielem. Miało to miejsce od 03:01 do 05:09. 
W przypadku klucza, o którym wspomniałem wcześniej, jest tak jak napisałeś - dotyczy tylko zasobu GET /order/events.

**Comment by krzysztofgwiazda** [comment]
@PrzemyslawLukanowski domyślam się o co chodzi. Również odnotowaliśmy błędy w nocy.
Czy te aukcje z dzisiejszej nocy może dotyczą jakiegoś zablokowanego przez Was sprzedawcy? 

Nie wiem jak odbywa się procedura ale jeśli robicie tak (a pewnie tak jest) to się tego nie pozbędziemy:
- blokujecie sprzedawcę i usuwacie mu aukcje
- następnie wszystkie wpisy lecą do journala
- nasza aplikacja pyta o aukcje do wpisów w journalu -> i dostaje 404. Bo skąd ma wiedzieć, że ściągnęliście z portalu jakiegoś sprzedawcę z setkami/tysiącami aukcji.
?

W takim wypadku allegro po zablokowaniu sprzedawcy z dużą ilością aukcji powinno na ten czas nieco zwiększyć limit odpytań na które dostajemy 404.

**Comment by PrzemyslawLukanowski** [comment]
Sprzedawca nie jest zablokowany. Według logów widzę, że konto *****450 próbuje pobrać zarchiwizowane oferty, które zakończyły się w różnych miesiącach ubiegłego roku, dlatego kończy się to błędem 404.
