### ISSUE TITLE
Brak zamówienia w https://api.allegro.pl/order/checkout-forms

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#2793]
Pobieranie zamówień z ostatnich 14 dni nie zwraca zamówienia nr 88be70a4-4378-11ea-8333-d1f95e797c51 z godz. 16:53 dla oferty nr 8278663706. Ktoś może to sprawdzić?

**Comment by mareklemur** [comment]
Inne zamówienia się pobierają, tego jednego nadal brakuje...

**Comment by pkrzemo** [comment]
Być może klient połączył 2 transakcje płacąc razem za nie. Wtedy jeden checkoutform znika (jest usuwany). Jak rozumiem znalazłeś to id w eventach. Znajdź dowolne lineitem w tym evencie i poszukaj checkoutform z takim samym lineitem_id w pozycjach zamówienia (checkoutForms ->lineItems). To będzie wtedy to nowe checkoutform_id

**Comment by mareklemur** [comment]
To jest pojedyncze zamówienie. Dlaczego nie ma żadnego zamówienia dla tej oferty wśród wszystkich pobranych zamówień z ostatnich 14 dni pobieranych metodą https://api.allegro.pl/order/checkout-forms?

**Comment by pkrzemo** [comment]
Może źle cię zrozumiałem...
Próbowałeś pobrać ten formularz osobno  https://api.allegro.pl/order/checkout-forms/88be70a4-4378-11ea-8333-d1f95e797c51 ?

**Comment by mareklemur** [comment]
Dobra, to chyba jednak coś u mnie, bo ten sam klient kupił to samo 2019-09-27 i chyba mi się coś źle łączy.

**Comment by PatrykBocian** [comment]
@mareklemur Zweryfikowałem twoje zgłoszenie - zasób **GET /order/checkout-forms/88be70a4-4378-11ea-8333-d1f95e797c51** zwraca prawidłowe zamówienie.

**Comment by mareklemur** [comment]
Tak, już się sprawa wyjaśniła, błąd był u mnie. Kolejny zakup tego samego użytkownika na tej samej aukcji traktował jako dubel. Już jest OK.
