### ISSUE TITLE
Czy w REST jest odpowiednik doGetMyPayoutsDetails?

### ISSUE THREAD

**Issue by Albin-88** [allegro/allegro-api#2794]
Witam, 

Nie widzę takiej możliwości przy obecnych metodach API.
Zaciągam listę:
`/payments/payment-operations/?group=OUTCOME`

I w żaden sposób nie mogę dobrać się na składowych, które zawierają się w danej wypłacie.

Klienci:
`Janek 100zł`
`Franek 100zł`
`Dzbanek 50zł`

Przykład:
`paymentOperations->type = PAYOUT`
`paymentOperations->value->amount = 250zł`
`paymentOperations->payout->id = 123`

Co mi daje to ostatnie ID?
W jaki sposób mając `paymentOperations->payout->id` mogę pobrać dane Janka Franka i Dzbanka?

Księgowość w każdej firmie potrzebuje takiej funkcjonalności - nawet w firmach, w których jeszcze o tym nie wiedzą :D

**Comment by PrzemyslawLukanowski** [comment]
Podobnie jak na froncie, nie zwracamy składowych danej wypłaty.  Jeśli chcesz uzyskać takie informacje, możesz ustawić interesujący Cię przedział datowy i porównać, jakie wpłaty zostały wykonane do momentu zlecenia wypłaty.

> Co mi daje to ostatnie ID?

Jest to unikatowy numer wypłaty, który możesz wykorzystać w swojej bazie.
