### ISSUE TITLE
Duration for offer

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2795]
Jaką wartość wpisać, aby oferta była do wyczerpania zapasów?

**Comment by sportmma** [comment]
Mój moduł magento 2 do allegro automatycznie nie ściąga wszystkich wymaganych parametrów i muszę na chybił trafił je dodawać ręcznie. Czy istnieje możliwośc, aby wszystkie wymagane parametry automatycznie się uzupełniały?

**Comment by PatrykBocian** [comment]
Aby oferta była aktywna do wyczerpania zapasów - w polu “**publication.duration**” podaj wartość “**null**”. 
Czy możesz doprecyzować pytanie “Czy istnieje możliwość, aby wszystkie wymagane parametry automatycznie się uzupełniał”? Jeżeli masz na myśli wiązanie oferty z produktem, nie da się zrobić tego automatycznie - parametry, które otrzymasz w odpowiedzi dla **GET /sale/products/{productId}** musisz następnie przekazać przez **PUT /sale/offers/{offerId}**. Opisz proszę dokładniej Twój przypadek.

**Comment by sportmma** [comment]
Z poziomu modułu allegro w mapowaniu wybieram docelową kategorię i powiedzmy, ze na koncu wybrana jest kategoria "saszetki i nerki" Automatycznie wyskakują mi do uzupełnienia wymagane atrybuty. Gdy chcę przesłać produkt przychodzi mi informacja, ze wymaganych atrybutów wypełniono np. 6/9. I muszę resztę recznie dodawać i metodą prób i błedów domyslać się ktore 3 z pozostałych są wymagane.

**Comment by PrzemyslawLukanowski** [comment]
Skorzystaj z zasobu [GET /sale/categories/{categoryId}/product-parameters](https://developer.allegro.pl/documentation/#operation/getFlatProductParametersUsingGET). W odpowiedzi, w polu required, znajdziesz informację, czy dany parametr jest obowiązkowy przy dodawaniu produktu. Na tej podstawie porównaj wymagane parametry z tymi, które przesłałeś.
