### ISSUE TITLE
Jak wgrac zdjęcia do draftu z poziomu tworzenia draftu

### ISSUE THREAD

**Issue by LeszekWroblowski** [allegro/allegro-api#2797]
Witam
Jak poprawnie powinny wyglądać dane przesyłane przez POST do sale/offers, tak żeby móc wgrać zdjęcie? Da się to w ogóle zrobić z poziomu draftu czy muszę je najpierw wgrać przez sale/images?
Używam tego skryptu do tworzenia draftów (pomijam logowanie i autoryzacje bo to działa)

> $zapytanie = "https://api.allegro.pl/sale/offers";
>     $ch = curl_init($zapytanie);
>     curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
>     curl_setopt($ch, CURLOPT_HTTPHEADER, [
>         "Authorization: Bearer $token",
>         "Accept: application/vnd.allegro.public.v1+json",
>         "Content-Type: application/vnd.allegro.public.v1+json",
>     ]);
>     curl_setopt($ch, CURLOPT_POST, true);
>     curl_setopt($ch, CURLOPT_POSTFIELDS,
>         json_encode(array(
>             'name' => $wiersz[nazwa_pl],
>             'external' => array('id' => $wiersz[id]),
>             'afterSalesServices' => array(
>                 'impliedWarranty' => array('id'=>"xxx"),
>                 'returnPolicy' => array('id'=>"xxx"),
>                 'warranty' => array('id'=>"xxx")),
>             'delivery' => array(
>                 'shippingRates' => array('id'=>"xxx"),
>                 'handlingTime' =>"P2D"),
>             'location' => array(
>                 'city' => 'xxx',
>                 'countryCode' => 'PL',
>                 'postCode' => 'xxx',
>                 'province' => 'SLASKIE'),
>             'payments' => array(
>                 'invoice' => 'NO_INVOICE'),
>             'sellingMode' => array(
>                 'format' => "BUY_NOW",
>                 'price' => array('amount'=>waluta($wiersz[cena],4),'currency'=>'PLN')),
>             'stock' => array(
>                 'available' => '1000',
>                 'unit'=> 'UNIT'),
>             'images'=>array(
>                 'https://xxx.pl/obrazki/obrazek_4_1.jpg?time=1580495339',
>                 'https://xxx.pl/obrazki/obrazek_4_2.jpg?time=1580495339'),
>             //'category' => array('id' => 'xxx'),
>             //'description'=>array($obrazki_a),
>             //'parameters'=>array($obrazki_a),
>         ))
>     );

**Comment by PrzemyslawLukanowski** [comment]
Zanim wykorzystasz zdjęcia w drafcie, musisz je przesłać za pomocą [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST). Następnie, będziesz mógl je wykorzytać w ofercie. W [naszym poradniku](https://developer.allegro.pl/sale/#new-offer) znajdziesz przykładową strukturę oferty.
