### ISSUE TITLE
Jak użyć zdjęcia w opisie Draftu, wgrywając zdjęcie z poziomu tego draftu

### ISSUE THREAD

**Issue by LeszekWroblowski** [allegro/allegro-api#2798]
witam
Dodaje draft w rest Api, dodaje go wraz ze zdjęciami. Teraz jednak mam problem bo chciałbym wykorzystać te zdjęcia dodane w drafcie w opisie tego samego draftu. Jak można to zrobić?

**Comment by PrzemyslawLukanowski** [comment]
1) Dodaj zdjęcia za pomocą [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST).,
2) Kiedy tworzysz draft przez [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST), w polu images prześlij link do obrazka, który otrzymałeś w odpowiedzi w kroku 1, jak poniżej:
```
    "images": [{
    	"url": "url"
    }],
```
3) Dodaj link także w sekcji description, przykład niżej:
```
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "url"
                    }
                ]
            }
        ]
    }
```

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#new-offer).
