### ISSUE TITLE
Polskie znaki nie są akceptowane w wiadomościach do dyskusji

### ISSUE THREAD

**Issue by foxbyte-pl** [allegro/allegro-api#2799]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas dodawania odpowiedzi w dyskusjach otrzymujemy informację o nieprawidłowych znakach w treści wiadomości. Dotychczas bezproblemowo zamieszczaliśmy odpowiedzi z polskimi znakami. Problem zauważyliśmy dzisiaj. Mało profesjonalnie wyglądają odpowiedzi do klientów bez polskich znaków.

Przesyłam odpowiedź serwera i trace-id.

`{"errors":[{"code":"VALIDATION_ERROR","message":"Pole zawiera niedozwolone znaki: ę","details":"Invalid value: xxxxxxx","path":"text","userMessage":"Pole zawiera niedozwolone znaki: ę"}]}
`

trace-id: 7e09688382e441fd

**Comment by PrzemyslawLukanowski** [comment]
Rzeczywiście miał miejsce taki problem, jednak na tę chwilę nie powinien już występować.

**Comment by foxbyte-pl** [comment]
Potwierdzam, na ten moment wygląda w porządku.
