### ISSUE TITLE
Zmiana pól aukcji związanych z wysyłką poprzez API

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#28]
Czy poprzez Allegro API da się zmienić cennik wysyłki (poprzez podanie jego ID) dla kilku aukcji jednocześnie?

Czy pozostaje ustawianie poszczególnych pól aukcji związanych z cennikiem (cena, sztuki) z osobna?

Czy można zmienić jednocześnie określone pole na konkretną wartość dla kilku aukcji, przy pomocy jednego wywołania API? Czy pozostaje wywoływanie doChangeItemFields dla każdej aukcji z osobna?

**Comment by KrzysztofLukanowski** [comment]
Aktualnie nie udostępniamy możliwości zmiany cennika wysyłki przez API. Jeżeli chodzi o zmianę cen dostawy przez WebAPI - pozostaje zmiana poszczególnych pól formularza. Możesz również szybko przypisać wybrany cennik dostawy do całej grupy ofert z poziomu Moje Allegro, wystarczy że pod listą ofert w [Sprzedaję](https://allegro.pl/myaccount/sell.php), klikniesz w Zmień cennik dostawy.

Jeżeli chodzi o API, nie ma możliwości jednoczesnej zmiany poszczególnych pól w kilku ofertach.

Intensywnie pracujemy nad udostępnieniem cenników w [REST API](https://developer.allegro.pl/). Jak tylko będzie taka możliwość, damy znać.
