### ISSUE TITLE
Type not found: 'ns1:postBuyFormAdrId'

### ISSUE THREAD

**Issue by Szczepaniak1A** [allegro/allegro-api#280]
Wywołując doGetPostBuyFormsDataForSellers web api zwraca błąd: Type not found: 'ns1:postBuyFormAdrId'. Wg #264 dzisiaj to pole miało zostać dodane i przez nie są problemy. Proszę o szybką odpowiedź.

**Comment by MaciejPotepa** [comment]
Możliwe, że wywołałeś metodę przed wejściem zmiany. Czy możesz spróbować ponownie? 
Dodatkowo, piszesz o środowisku testowym czy produkcyjnym?

**Comment by Szczepaniak1A** [comment]
Wciąż bez zmian.
Na środowisku produkcyjnym.

**Comment by MaciejPotepa** [comment]
Dzięki za szybką odpowiedź, zgłosiłem problem.

**Comment by MaciejPotepa** [comment]
@Szczepaniak1A Czy nadal błąd nadal występuje?
