### ISSUE TITLE
REST API i hasła do aplikacji

### ISSUE THREAD

**Issue by radek87urban** [allegro/allegro-api#2800]
Czy możliwe jest uwierzytelnianie w REST API poprzez hasła do aplikacji?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować swoje zgłoszenie? Zajrzyj do naszego poradnika - [Uwierzytelnienie i autoryzacja](https://developer.allegro.pl/auth/), znajdziesz tam wszystkie niezbędne informacje.

**Comment by radek87urban** [comment]
Precyzuję - klient chciałby logować się poprzez "hasła do aplikacji" https://allegro.pl/moje-allegro/moje-konto/hasla-do-aplikacji, zamiast używać "standardowego" hasła do swojego konta allegro. Mówimy tu o łączeniu się z Państwa serwisem poprzez REST API.

**Comment by PrzemyslawLukanowski** [comment]
Tak, klient może logować się w ten sposób. Więcej szczegółów znajdziesz w [naszym artykule.](https://allegro.pl/pomoc/dla-sprzedajacych/logowanie-i-haslo/hasla-do-aplikacji-najczesciej-zadawane-pytania-LvP7abA8atq)

**Comment by radek87urban** [comment]
Dziękuję za odpowiedź.

Wygenerowałem hasło do aplikacji, jednak przy próbie logowania przez metodę uwierzytelniania REST API https://allegro.pl/auth/oauth/authorize (które przekierowuje na stronę logowania allegro) otrzymuję komunikat o błędnym haśle.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, źle się zrozumieliśmy. Hasło do aplikacji nie jest związane z etapem, o którym napisałeś. Dotyczy sytuacji, w której użytkownik loguje się już w samej aplikacji zewnętrznej. Aby je wykorzystać, musisz opracować odpowiedni mechanizm po swojej stronie.
