### ISSUE TITLE
doRequestPayout    - 'WebAPI method does not exist'

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#2801]
Występuje problem: 
 - [x] z metodą WebAPI
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Po wywołaniu metody .doRequestPayout(..) leci:
Server raised fault: 'WebAPI method does not exist'

Zgodnie z harmonogramem ta metoda miała być usunięta w III kwartale 2020:
https://developer.allegro.pl/schedule/?utm_source=notification&utm_medium=wygaszenieZamWebAPI&utm_campaign=wygaszenie-zamowien-webapi

ps. do 6:36 dziś rano jeszcze działało.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy to, wrócę z odpowiedzią po wyeliminowaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
Metoda działa już poprawnie.

**Comment by PiotrLaszczyk** [comment]
Ano działa ;)
