### ISSUE TITLE
REST API - problem z typem i czasem dostawy

### ISSUE THREAD

**Issue by xVinniVx** [allegro/allegro-api#2803]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

https://api.allegro.pl/sale/offers

Przy wystawianiu **draftu** nie są zapisywane informacje o typie dostawy i czasie dostawy, mimo iż dane te są przekazywane przez API. Każde jedno inne ustawienie działa bez problemu.

Jednakże przekazanie:
```
    "delivery": {
        "shippingRates": {
            "id": "694a5eea-4c85-44c9-95a6-b24717b6dea6"
        },
        "handlingTime": "P2D"
    },
```

Nie przynosi żadnego skutku. Pola wyboru Cennika dostawy i Czasu przesyłki są puste. W czym tkwi przyczyna?

ID ShippingRates pobrałem poprzez https://api.allegro.pl/sale/shipping-rates?seller.id=xxxxxxxxx i to ID przekazuję w "shippingRates" wyżej

**Comment by pkrzemo** [comment]
Może spróbuj ustawić "handlingTime": "PT48H"
Nie wiem czy to pomoże ale tak formatuje to allegro w przypadku 2 dni...

**Comment by xVinniVx** [comment]
@pkrzemo Oczywiście próbowałem również formatu, z Twojej wiadomości.
Efekt taki sam - brak automatycznie zaznaczonego wyboru na karcie tworzenia draftu.

**Comment by PrzemyslawLukanowski** [comment]
@xVinniVx Aby dodać prawidłowo sekcję delivery, w tym samym wywołaniu musisz przekazać także pole location, np:

```
    "location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "60-166"
    },
```

**Comment by xVinniVx** [comment]
@PrzemyslawLukanowski 
Bardzo dziękuję. Faktycznie, to był powód. Jest to co prawda opisane w komentarzu w kodzie, przy location, ale może warto do dokumentacji dać, że ten wpis jest wymagany? 

Tak czy owak - problem rozwiązany. Bardzo dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że mogłem pomóc. Aby utworzyć draft oferty, wymagamy tylko pola name, dlatego w dokumentacji location nie ma takiego oznaczenia. Odpowiednią informację zamieściliśmy w naszym poradniku [Jak wystawić ofertę - Krok 8. Uzupełnij draft oferty.](https://developer.allegro.pl/sale/#new-offer)
