### ISSUE TITLE
Problem z wywołaniem zapytań w środowiksu sandbox

### ISSUE THREAD

**Issue by taksanski-widelec** [allegro/allegro-api#2804]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zapytanie Postman:

GET /sale/offers HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Authorization: Bearer <TUTAJ_TOKEN>
Accept: application/vnd.allegro.public.v1+json
User-Agent: PostmanRuntime/7.20.1
Cache-Control: no-cache
Postman-Token: 2d2e5384-7c55-476f-a4c9-4ac0fc975932,c32b540c-ab56-4195-8547-6f671a2cdb4d
Host: api.allegro.pl.allegrosandbox.pl
Accept-Encoding: gzip, deflate
Cookie: _cmuid=2gh5f1mc-r281-5a19-h19k-nx1ejuee31ze; TEST_QXLSESSID=7d64092ced435877b4b90bccb2bafb444d3e78350bcc68//00
Connection: keep-alive
cache-control: no-cache

Zwraca odpowiedź:

{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
}

na innych zasobach natomiast wyskakują inne błędy typu np
 "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Access is denied",
            "details": "org.springframework.security.access.AccessDeniedException: Access is denied\n\tat org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)\n\tat org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)\n\tat 

itp itd

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobnie korzystasz z autoryzacji client_credentials, przytoczę moją odpowiedź z innego wątku:

> Błąd, który otrzymałeś w response związany jest z użytym przez Ciebie typem autoryzacji - [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Nie posiada on kontekstu użytkownika i pozwala korzystać tylko z publicznych zasobów, które w [naszej dokumentacji ](https://developer.allegro.pl/documentation/#section/Authentication)oznaczyliśmy jako bearer-token-for-application. Aby wywołanie zadziałało prawidłowo, musisz skorzystać z autoryzacji [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).

Jeżeli mimo to w dalszym ciągu będziesz otrzymywać błędy, podaj nam wtedy przykładowe trace-id.
