### ISSUE TITLE
dostęp z starszej wersji biblioteki openssl

### ISSUE THREAD

**Issue by LeszekWroblowski** [allegro/allegro-api#2805]
Witam
Czy jest jakaś szansa na dostęp do Rest Api po starszej wersji OpenSSL
Przy próbie dostępu z mojego serwera dostaje komunikat: 
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Z tego co wyczytałem to z powodu przestarzałej biblioteki OpenSSL która nie wspiera TSL 2.0
Niby wszystko fajnie, pisze do firmy u której mam hosting, a oni mi wyjeżdżają że za upgrade openSSL ponad 3 tys zł...
Z góry dziękuje za pomoc

**Comment by pskz** [comment]
Z tego co mi wiadomo, Allegro obecnie wspiera jeszcze TLS v1.1 a niedługo już tylko v1.2
Obie wersje TLS (1.1 oraz 1.2) są obsługiwane przez OpenSSL od wersji 1.0.1 - która wyszła w 2012 roku!!!

Oczywiście polecam aktualizacje do nowszej wersji, ale...
Jeśli Twój usługodawca rzuca takimi tekstami i kisi starą wersję na swoich serwerach, a za błahą aktualizację oprogramowania open source (odpowiedzialnego za szyfrowanie i bezpieczeństwo) żąda niestworzonych rzeczy, to uciekałbym jak najszybciej... i nawet się nie oglądał

Że też takie rzeczy jeszcze na tym świecie...
