### ISSUE TITLE
Error "invalid_grant", dlaczego rzuca error 400 zamiast 401?

### ISSUE THREAD

**Issue by pskz** [allegro/allegro-api#2806]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] z logowaniem lub autoryzacją

:beetle: **Opis**

Podczas próby przedłużenia ważności tokena w autoryzacji typu Device Flow (możliwe że Code Flow także), zasób "auth/oauth/token" rzuca "w pewnych okolicznościach" error 400 invalid_grant.
To samo jeśli próbuje odpytać jakikolwiek zasób wymagający autoryzacji.

Z tego co udało mi się ustalić dzieje się tak w momencie jak podam stary (tzn. poprzedni) refresh_token, w każdym innym przypadku (nieprawidłowy refresh, wygasły refresh, brak refresh) rzucany jest error 401.
Ta sytuacja nastąpiła w momencie wystąpienia błędu w mojej aplikacji. Nowe zwrócone tokeny nie zapisały się w lokalnej bazie, więc aplikacja odpytywała API nadal po starych tokenach.

Czy jest to zamierzone działanie? Spodziewałbym się tutaj jednak kodu 401, zamiast 400 który trzeba dodatkowo sprawdzać pod kątem typu błędu jaki wystąpił.

**Comment by PrzemyslawLukanowski** [comment]
Tak, to zamierzone działanie, które jest zgodne ze [specyfikacją OAuth 2.0](https://tools.ietf.org/html/rfc6749#page-45). Znajdziesz w niej więcej szczegółow na ten temat.
