### ISSUE TITLE
błąd 422

### ISSUE THREAD

**Issue by oponika** [allegro/allegro-api#2807]
podczas POST sale/offers w odpowiedzi podaje błąd walidacji 422

{"errors":[{"code":"VALIDATION_ERROR","message":"Provided image address is incorrect: https://a.allegroimg.com/original/11f058/80c87fa34613829dadf9ee5f8980.","details":"","path":"","userMessage":"Provided image address is incorrect: https://a.allegroimg.com/original/11f058/80c87fa34613829dadf9ee5f8980."}]}

a pod adresem pokazuje sie zdjecie i można je pobrać, wiec nie jest to kwestia cache

**Comment by PrzemyslawLukanowski** [comment]
Próbuję pobrać ten obrazek - w odpowiedzi otrzymuję błąd 404 z komunikatem Object not found, co wskazuje na to, że link do obrazka wygasł. Spróbuj przesłać go ponownie, a następnie zmień link w drafcie oferty. Jeśli w dalszym ciągu będziesz otrzymywać błąd, podaj nam proszę przykładowe trace id do POST /sale/offers oraz link do oryginalnego obrazka. Możesz to zrobić tutaj lub przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - dopisz wtedy w zgłoszeniu GitHub #2807.
