### ISSUE TITLE
500 Internal Server Error przy wystawianiu aukcji powiązanej z produktem

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#2808]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Podczas wystawiania aukcji powiązanej z produktem występuje 500 Internal Server Error.
Sytuacja dotyczy tylko aukcji powiązanych z produktem.
Możecie potwierdzić czy macie problem z zasobem czy problemu szukać u siebie?

trace-id: 84898ab7021a9de8

**Comment by PrzemyslawLukanowski** [comment]
Przy wiązaniu oferty z produktem musisz także podać odpowiednią kategorię w polu category.id.  W przypadku produktu z Twojego wywołania jest to 50846. Przekażę informację o doprecyzowaniu komunikatu błędu do odpowiedniego zespołu.

**Comment by dlis2010** [comment]
Zgadza się, błąd był po naszej stronie.
Wkradła się literówka związana z kategorią.

Dziękuję bardzo za szybką reakcję.
