### ISSUE TITLE
Próba otwarcia strony została zablokowana

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2809]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy różnych operacjach na środowisku testowym pojawiają się następujące błędy. Aktualnie nic nie działa.
Występuje też problem z brakiem wyświetlania się metod płatności.
![Screenshot at 2020-02-05 15-11-27](https://user-images.githubusercontent.com/4314822/73849478-4d3ea980-482a-11ea-8c0e-5adbdb8fa08a.png)

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem zgłoszenie do odpowiedniego zespołu.

**Comment by pawelosajda** [comment]
Wydaje się już działać.
