### ISSUE TITLE
Jakie znaczenie ma pole location w drafcie?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#2810]
Jakie znaczenie dla kupującego ma pole "location" wypełniane podczas wystawiania draftu oferty?

Pozdrawiam

**Comment by pkrzemo** [comment]
Bo może wziąć pod uwagę odbiór osobisty?
Albo czy towar wysyłany jest z Chin ?

**Comment by tomylee0** [comment]
Jeśli założymy, że służy wyłącznie do filtrowania produktów (filtr "lokalizacja") to jak zachowa się mechanizm filtrowania jeśli **location** sprzedający w konkretnym produkcie ustawił na np. Katowice a w **punktach odbioru** ma 2 inne adresy, np. jeden we Wrocławiu a drugi w Warszawie?

**Comment by PrzemyslawLukanowski** [comment]
Oprócz filtrowania, wartość, którą przekażesz w polu location, będzie widoczna w sekcji "Dostawa i płatność" w ofercie, np. "Odbierz osobiście w..." lub "Wysyłka z...".

> jak zachowa się mechanizm filtrowania jeśli location sprzedający w konkretnym produkcie ustawił na np. Katowice a w punktach odbioru ma 2 inne adresy, np. jeden we Wrocławiu a drugi w Warszawie?

W tym przypadku pod uwagę również weźmiemy wartość z pola location.

**Comment by tomylee0** [comment]
Dzięki za odpowiedź. Pozdrawiam.
