### ISSUE TITLE
Sandbox - nie działają linki do wystawiania przedmiotu

### ISSUE THREAD

**Issue by KarolBank** [allegro/allegro-api#2811]
Próbuję wystawić przedmiot korzystając ze strony internetowej sandboxa. Jestem zalogowany na aktywowanym koncie.

Oba linki:
Moje Allegro -> Wystaw przedmiot
Moja sprzedaż -> Wystaw

przekierowują do strony:
https://staging-lokalnie.allegrogroup.com/oferty/wystaw
która nie istnieje.

W jaki sposób mam wystawić przedmiot?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę skorzystaj z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by KarolBank** [comment]
Dziękuję, działa.

**Comment by cyfranT** [comment]
Witam, kiedy zostanie to naprawione, żeby nie trzeba było szukać po forach alternatywnych linków?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mogę wskazać konkretnego terminu. Poinformuję w tym wątku po usunięciu problemu.
