### ISSUE TITLE
Problem z wyszukiwaniem ofert.

### ISSUE THREAD

**Issue by Kokoscanfly** [allegro/allegro-api#2812]
Witam, 
nie do końca wiem czy to tutaj jest miejsce na zgłaszanie takiego problemu, ale dzisiaj odkryliśmy jeden problem z wyszukiwaniem oferty.

Problem dotyczy oferta 8680871111 BMW E46 COMPACT LICZNIK 0263606342

Po wpisaniu numeru oferty [8680871111] w wyszukiwarce to pokazuje się aukcja. 
Po wpisaniu nazwy przedmiotu [BMW E46 COMPACT LICZNIK 0263606342] oferta nie jest znaleziona. Nawet jak wpisze np część nazwy [0263606342] to również nie mogę odnaleźć oferty. 

**Sprawdzałem to zarówno poprzez allegro.pl jak i rest api allegro.**

ps. Mogłem gdzieś popełnić błąd bo lekko człowiek się zdenerwował ponieważ płacimy zarówno za wystawienie jak i utrzymanie ofert, a nasuwa się pytanie ile takich przypadków występuje.

**Comment by PatrykBocian** [comment]
Zweryfikowałem Twoje zgłoszenie - rzeczywiście występuje problem z tą ofertą. Przekazałem to do odpowiedniego zespołu.

**Comment by Kokoscanfly** [comment]
15 dni minęło bez odpowiedzi, czy znamy jest już powód ?

**Comment by MaciejFrackowiak** [comment]
@Kokoscanfly Tak, w momencie wystawiania oferty zdarzenie to nie zostało poprawnie rozpropagowane. Odświeżyliśmy status, oferta jest już dostępna. Przepraszam za niedogodności.

**Comment by Kokoscanfly** [comment]
Dobrze, ale ogłoszenie zostało wystawione w listopadzie. W lutym zauważyliśmy problem. Proszę powiedzieć jak sprawa z naliczanymi opłatami za takie ogłoszenie ? 
Czy istnieje narządzie do zweryfikowania czy wystawiona oferta jest wyświetlana na allegro ?

**Comment by MaciejFrackowiak** [comment]
Oferta była dostępna w Allegro od momentu jej wystawienia (np. przeglądając kategorię), to specyficzne odpytanie wyszukiwarki tylko jej nie zwracało. Natomiast w kwestii opłat proszę o kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=7f980b3b-184b-4f4a-9ad4-7e833245df10).
