### ISSUE TITLE
Wylogowywanie z panelu

### ISSUE THREAD

**Issue by szymon-convertis** [allegro/allegro-api#2815]
Witam,
Podczas korzystania z allegro przez http dochodzi do wylogowywania po kilku minutach i podejrzewam, że jest to związane z tym, że w tym samym czasie działają procesy restApi. O ile wcześniej, w webApi było to dosyć jasne bo były sesje i stworzenie sesji nr 21 kończyło najstarszą sesję tak aktualnie nie ma opisu jak rest api może korelować z sesjami http. Czy taka zależność istnieje i jeśli tak to w jaki sposób można przeciwdziałać wylogowywaniu użytkownika z panelu w przeglądarce. 

pozdrawiam
Szymon

**Comment by DarkStoorM** [comment]
Chodzi dokładnie o wylogowanie na froncie czy expired token?

Token można odświeżać, a jeśli chodzi o front, to od wielu miesięcy prowadziłem maile z Allegro na temat ciągłego wylogowania i nikt nie wie co się dzieje 🤷‍♂

**Comment by szymon-convertis** [comment]
Chodzi dokładnie o wylogowanie na froncie. 
Tokeny działają bezproblemowo.

**Comment by kfijalko** [comment]
Też zauważyłem wylogowywanie na forncie (z "moje allegro"). 
Wcześniej (nie jestem w stanie dokładnie umiejscowić w czasie, powiedzmy 1-2 miesiące temu) sesja była aktywna przynajmniej cały dzień. Teraz występuje wylogowanie w ciągu dnia.

**Comment by DarkStoorM** [comment]
To w takim razie dołączam się do problemu, może ktoś w końcu ogarnie co się dzieje.

Ja posiadam trzy konta o identycznej konfiguracji, z czego jedno posiada wykupiony abonament allegro (o to jest jedyna różnica między nimi).
Konto, które posiada abonament potrafi mnie wylogować nawet po minucie, czasami do pięciu, resztę nawet na cały tydzień zostawiam i ani śladu wylogowania i nie jest to kwestia ustawień maszyny, bo wszędzie dzieje się to samo.

**Comment by kfijalko** [comment]
@DarkStoorM coś w tym może być:
u mnie
- jedno konto (bez abonamentu) zalogowane na Microsoft Edge - sesje trzyma od 7 dni na stronie SS (codziennie sprawdzałem czy już przyznali SS i nie musiałem się logować)
- drugie konto (z abonamentem) zalogowane na Chorme - sesja wygasa w ciągu dnia

**Comment by PatrykBocian** [comment]
Obecnie jednocześnie użytkownik może mieć aktywnych 20 sesji w Allegro (ten limit dotyczy jednocześnie API, jak i strony WWW). Wygenerowanie nowego tokena nie powinno mieć wpływu na sesje, chyba że będzie to 21 sesja - w tym momencie pierwsza zostaje zakończona. Proszę podeślijcie swoje ID przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - zweryfikujemy Wasze przypadki.

**Comment by szymon-convertis** [comment]
Czyli wygenerowanie nowego tokena powoduje zwiększenie licznika sesji? Czy jeszcze jakieś działania przez rest api powodują zwiększenie liczby sesji?

**Comment by kfijalko** [comment]
@PatrykBocian w moim przypadku ma to sens. Pomijając abonament i przeglądarkę.
Na pierwszym koncie mam niecałe 10k ofert i tam po API idzie mniej operacji. Na tym koncie sprawdzałem tylko SS.
Na drugim koncie mam niecałe 100k ofert i tam idzie dużo więcej operacji. Dodatkowo jest to konto główne, na którym działa ms.allegro oraz ja codziennie sprawdzam SS,rozliczenia,dyskusje, ads'y... Drugie konto musi w ciągu doby wielokrotnie tworzyć sesje: 
- restAPI
- ms.allegro (3 stanowiska)
- moje sprawdzanie rozliczeń , ss, dyskusji..
- Ads'y
w sumie może się uzbierać 20 sesji.

**Comment by PatrykBocian** [comment]
W nawiązaniu do kontaktu poprzez formularz kontaktowy - dla użytkownika o ID 2194**** widzimy ciągłe logowania poprzez WebAPI w odstępach co 1-2 sekundę. W tej sytuacji przekroczenie 20 otwartych sesji to kwestia niecałej minuty. Niezbędne jest tu zoptymalizowanie działania oprogramowania, które łączy się z naszym serwerem. 

@szymon-convertis Każde rozpoczęcie nowej sesji kolejnym tokenem zmniejsza limit 20 sesji. Pamiętaj, że wliczane do limitu są wszelkie logowania - WWW, API, a także logowania aplikacji zewnętrznych.

**Comment by DarkStoorM** [comment]
# Uwaga
Jeżeli posiadacie integrację z hurtowniami Dropshippingowymi, w których podawaliście dane do swojego konta Allegro/klucz webapi i z nich nie korzystacie, **usuńcie te integracje lub podane dane logowania na stronach hurtowni**. Obsługa Allegro właśnie pomogła mi znaleźć aplikację z pewnej hurtowni, która jeszcze korzystała z webapi i niepotrzebnie zapychała sesję, przez co ciągle wylogowywało mnie na Froncie. Jeżeli nadal korzystacie z tych hurtowni, zalecam napisać do nich z sugestią optymalizacji...

Jeżeli problem nadaj występuje, sprawdźcie wszystkie hurtownie, które posiadają integrację z Allegro czy nie widnieją tam wasze dane logowania albo upewnijcie się, że ich aplikacje są pod tym kątem jakoś sensownie zoptymalizowane.

Problem ustał jak tylko odłączyłem hurtownie. 👌

**Comment by PrzemyslawLukanowski** [comment]
@szymon-convertis W Twoim przypadku widzę, że operacja logowania pojawia się co 1s. Adres dns przesyłam w odpowiedzi na zgłoszenie z formularza.
