### ISSUE TITLE
Mogę wgrać zdjęcie ale nie mogę go użyć w opisie

### ISSUE THREAD

**Issue by LeszekWroblowski** [allegro/allegro-api#2816]
Witam
Mam problem ze zdjęciami. 
Za pomocą sale/images wgrywam sobie zdjęcia produktów. Dostaje zwrotnie linki do tych zdjęć, wszystko fajnie działa.
Teraz robię drafta i jeśli w opisie chce użyć tych zdjęć to dostaje error

> [code] => VALIDATION_ERROR
> [message] => Description images are not valid.
> [details] => Invalid value: unknown
> [path] => offerDto
> [userMessage] => Description images are not valid.

Link do zdjęcia: https://a.allegroimg.com/original/117104/d7226581479591993c047b44319a

Tak wygląda mój kod PHP do tworzenia opisu:
```
$opis=array('sections'=>array(
        array('items'=>
            array(array('type'=>'TEXT','content'=>('<p>'.$opis_produktu.'</p>')))),
        array('items'=>
            array(array('type'=>'TEXT','content'=>parametry_produktu($id,$wiersz[wysokosc])))),
        array('items'=>   
array(array('type'=>'IMAGE','url'=>"https://a.allegroimg.com/original/119801/f7cc8623478b96f78913b4233e8a")))
));
```

**Comment by kfijalko** [comment]
Możesz zrzucić jsona, który jest wygenerowany na podstawie $opis.

**Comment by PatrykBocian** [comment]
Pamiętaj, że obrazek należy dodać także w tablicy "**images**". Dopiero wtedy możesz go wykorzystać w sekcji description. Zajrzyj do naszego [poradnika](https://developer.allegro.pl/sale/#step-3-images), gdzie prezentujemy przykładowy request. 

Jeżeli mimo to nadal otrzymujesz błąd, wyślij proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz **GitHub #2816**.
