### ISSUE TITLE
REST API - /order/events - duplikaty

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#2818]
Witam serdecznie, 

chciałem dopytać się jak dokładnie wygląda wykrywanie duplikatów ?
według informacji zawartej na https://developer.allegro.pl/orders/ wystarczy sprawdzać pole "occurredAt" - **Lista zdarzeń posortowana jest według czasu wystąpienia - od najstarszych do najnowszych - duplikaty zdarzeń możesz ustalić na podstawie pola occurredAt.** Niestety dostaję wtedy wiele duplikatów, które posiadają różne dane (np. inny checkoutFormId), czy zatem duplikat występuje tylko w przypadku gdy pole occurredAt oraz jakieś inne pole (np checkoutFormId) są identyczne ? 

Dziękuję za informację.

**Comment by MaciejFrackowiak** [comment]
Różne wartości checkoutForm.Id świadczą, że kupujący dokonał np. dwóch oddzielnych zakupów u tego samego sprzedającego, a następnie opłacił je jedną płatnością - w takim przypadku powstaje nowe checkoutForm.Id. Duplikat to zdarzenie, które charakteryzuje się tymi samymi danymi w korelacji z polem occuredAt.

**Comment by pliszka2** [comment]
@MaciejFrackowiak super dziękuję za informację temat do zamknięcia :)

**Comment by pliszka2** [comment]
@MaciejFrackowiak, jeszcze chciałem otworzyć temat gdyż jestem w trakcie ustalania duplikatów i prosił bym tylko o weryfikację dwóch kwestii:

1) czy jest możliwość by jeden element wystąpił aż 7 razy ? (różnią się tylko polem event_id (reszta pól odpowiedzi identyczna łącznie z checkout_form_id)
2) czy jest możliwe by na około 28 tysięcy wpisów było aż 4 tysiące duplikatów ?

**Comment by MaciejFrackowiak** [comment]
@pliszka2 Odpowiadając na pytania:

1. Tak, jest to możliwe;
2. I tu jest to również możliwe.

**Comment by pliszka2** [comment]
@MaciejFrackowiak super dziękuję za informację zamykam :)
