### ISSUE TITLE
Brak aktualizacji ceny aukcji

### ISSUE THREAD

**Issue by mxdzi** [allegro/allegro-api#2819]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W piątek (2020.02.07) wysłałem aktualizację cen i stanów dla około 200 aukcji. Dla wszystkich aukcji po paru sekundach otrzymałem odpowiedź o poprawnej zmianie cen ale część aukcji na allegro do teraz ma starą cenę.

Przykład zapytania:
```
{"modification":{"type":"FIXED_PRICE","price":{"amount":"149.99","currency":"PLN"}},"offerCriteria":[{"offers":[{"id":"8921167677"}],"type":"CONTAINS_OFFERS"}]}
``` 

command-id: `0dffe2d3-d41e-40e2-8017-b07a07f84941`

odpowiedz z command-id/tasks
```
[offer] => stdClass Object
	(
		[id] => 8921167677
	)
[message] =>
[status] => SUCCESS
[scheduledAt] => 2020-02-07T13:21:47.913Z
[finishedAt] => 2020-02-07T13:21:48.809Z
[field] => price
[errors] => Array
	(
	)
```
na aukcji cena jest 104.99 zamiast 149.99.

Problem dotyczy jeszcze aukcji:
`8889013333` / command: `272717c5-eda2-4f16-a985-bca35161e02e`
jest 125.99, powinno być 179.99.

`8906597962` / command: `8f06ad2d-a72b-4437-9929-1ae11af5196c`
jest 139.99, powinno być 199.99.

**Comment by MaciejFrackowiak** [comment]
Zweryfikowaliśmy opisany przez Ciebie przypadek - oprócz zmiany ceny jednocześnie zleciłeś zmianę ilości sztuk w ofercie. W tym momencie zadania się zakolejkowały. W logach widzimy, że zmiana ceny została wykonana - zmieniliśmy cenę na właściwą i dokładnie po niecałej sekundzie druga operacja nijako nadpisała wcześniejszą zmianę przywracając cenę pierwotną zmieniając ilość, stąd wniosek, że zmiana ceny nie wykonała się. 
Sugeruję byś zmiany wykonywał w pewnym odstępie czasu by uniknąć podobnych sytuacji w przyszłości, my ze swej strony postaramy się także dodać odpowiedni mechanizm zabezpieczający.

**Comment by mxdzi** [comment]
W api soap takie zmiany działały bez problemu dlatego w nowym api tak samo chciałem aktualizować aukcje. Czy te okres czasu to sekundy, minuty? Czy może lepiej poczekać na potwierdzenie poprzedniego zadnia i nie kolejkować następnych zmian?

**Comment by MaciejFrackowiak** [comment]
Jeżeli zastosujesz rozwiązanie z oczekiwaniem na potwierdzenie wykonania zadania to masz pewność co do jego finalnego rezultatu. Odstęp bardziej liczony w sekundach - w opisanym przypadku zlecenie wyszło praktycznie jedno po drugim, stąd taki szczególny przypadek.
