### ISSUE TITLE
Pobranie informacji o zamówieniach z innego konta

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#2820]
Witam.
Mam do ogarnięcia 4 konta allegro jeśli chodzi o zamówienia. Mam dostęp do wszystkich tych kont. To już było poruszane w tym wątku 
[Logowanie do allegro - dane z wielu kont](https://github.com/allegro/allegro-api/issues/680)
Ale ja mam kompletnie inny błąd. Mając ID zamówienia z konta B, próbuje pobrać jego szczegóły tokenem, clientId, device_code z konta A i dostaję 
```
{
	"errors": [
		{
			"code": "CheckoutFormNotFoundException",
			"message": "checkout form of id [id_zamowienia] not found",
			"details": null,
			"path": "/order/checkout-forms/[id_zamowienia]",
			"userMessage": null
		}
	]
}
```
[id_zamowienia] - w tym miejscu jest prawdziwe ID, nie wiem czy powinienem takie dane tutaj wklejać, stąd takie oznaczenie.

Jak pobrać informacje o zamówieniach z innego konta? Czy jest to w ogóle możliwe?

**Comment by MaciejFrackowiak** [comment]
Będąc zalogowanym na koncie A pobierzesz zamówienia tylko z konta A, B z B, i tak analogicznie dalej. Nie ma możliwości pobierania danych z pozostałych kont jednocześnie.

**Comment by troncomputers** [comment]
Tak też myślałem. Dzięki za info
