### ISSUE TITLE
Error Object not found dla grafiki użytej w ofercie

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2821]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

:beetle: **Opis**
Dzień dobry, na sandboxie posiadam ofertę:
https://allegro.pl.allegrosandbox.pl/oferta/6206423334 

dla której nie działa dodana wcześniej grafika:
https://a.allegroimg.allegrosandbox.pl/original/111c2a/d768f26a447c8c0e174df42e7d10 

Zgodnie z [dokumentacją](https://developer.allegro.pl/sale/#step-3-images) grafiki użyte w ofertach nie powinny być usuwane z serwera. 

Proszę o weryfikację i informację czy taka sytuacja może wystąpić na produkcji.

![image](https://user-images.githubusercontent.com/8465007/74240935-39d48800-4cdb-11ea-9412-e5050dd756ff.png)

**Comment by MaciejFrackowiak** [comment]
Potwierdzam problem z grafiką dołączoną do wymienionej oferty - powinna być nadal dostępna. Co do zasady, zdjęcia przechowujemy do 60 dni od dnia zakończenia oferty (do czasu archiwizacji oferty). Jeżeli taki problem powtórzyłby się na produkcji to byłby to błąd.
