### ISSUE TITLE
Obsługa kilku kont w jednej aplikacji - Cannot convert access token to JSON

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#2822]
Byłem zmuszony stworzyć oprogramowanie, które będzie w stanie obsłużyć cztery konta Allegro jednocześnie. Wczoraj udało mi się wszystko powiązać z odpowiednim kontem, otrzymałem dla każdego konta 4 różne tokeny (oraz refresh_tokeny) i aplikacja wykonała swoje zdanie poprawnie. Dzisiaj już nie działa. 
```
{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}
```
Aplikacja automatycznie próbuje odświeżyć token, ale twierdzi, że:
```
{"error":"invalid_grant","error_description":"Invalid refresh token: [token]"}
```
Nie korzystam z piaskownicy, nigdy z niej nie korzystałem. 
Czy to jest jakaś blokada? Czy ja mogę co 5 minut odpytywać API z czterech kont jednocześnie? 

Zapytań do API jest więcej, ponieważ nie mam żadnej informacji z jakiego konta przyszło zamówienie, więc muszę odpytać wszystkie konta i te, które nie zwróci `StatusCode.NotFound` zrealizować.

**Comment by MaciejFrackowiak** [comment]
Komunikat "Cannot convert access token to JSON" świadczy, że korzystasz z tokena ze środowiska testowego na produkcji lub odwrotnie. Rozkoduj token i sprawdź jego poprawność.

**Comment by troncomputers** [comment]
Tak jak pisałem wyżej, nie korzystam z piaskownicy i nigdy nie korzystałem. Token rozkodowałem i client_id jest prawidłowe w nim

**Comment by MaciejFrackowiak** [comment]
Raz wykorzystany refresh_token powoduje konieczność wygenerowania nowej pary access_token + refresh_token. Bez konkretnych danych nie mam możliwości zweryfikowania jak przebiega u Ciebie proces autoryzacji. Jeżeli nie uda Ci się rozwiązać problemu, proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) przesyłając swój request i response (w wiadomości proszę dodaj numer postu z GitHub - 2822).

**Comment by troncomputers** [comment]
Nie doszło do odświeżenia tokena, ponieważ przez ten błąd nie otrzymałem nowej pary. Jeśli dobrze rozumiem, wszystko sprowadza się do wygenerowania pary tokenów na nowo?

**Comment by MaciejFrackowiak** [comment]
Tak, raz użyty refresh_token nie może zostać wykorzystany ponownie - konieczne jest wygenerowanie nowej pary access + refresh.

**Comment by Onixarts** [comment]
Zapewne dokonałeś ponownej autoryzacji. Wtedy stare tokeny tracą ważność.

**Comment by troncomputers** [comment]
@Onixarts 
No właśnie problem polega na tym, że do ponownej autoryzacji nie doszło. Od wczoraj jest ten sam access_token oraz refresh_token, które generują powyższe błędy. Druga sprawa, to tylko ja mam dostęp i możliwość wygenerować wszystko od nowa, aplikacja ma za zadanie tylko odświeżyć token jeśli zapytanie o zamówienie zwróci `StatusCode.Unauthorized`. 

Dostaje błąd `Cannot convert access token to JSON`, więc aplikacja próbuje odświeżyć token, a podczas odświeżenia dostaje, że refresh_token jest niepoprawny i program się zapętla...

**Comment by Onixarts** [comment]
To może refreshtoken jest niepoprawnie zapisany, ucięty itp.

**Comment by troncomputers** [comment]
refresh_token jest poprawny, ponieważ również po odkodowaniu pokazuje proprawny client_id i poprawnie zostaje odkodowany

**Comment by troncomputers** [comment]
Po wygenerowaniu na nowo tokenów problemu nie ma. Możliwe, że tokeny były pomieszane.
