### ISSUE TITLE
Opóźnienie między eventem a statusem oferty

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2823]
Czy w momencie gdy otrzymujemy event sale->offer-events

na przykład OFFER_ENDED

natychmiast po tym jeśli zapytamy o /sale/offers/ to dla tej oferty będzie status ENDED/INACTIVE 
Czy jest jakiś interwał czasowy ?

**Comment by MaciejFrackowiak** [comment]
Tak, wystąpienie eventu przekłada się bezpośrednio na ofertę - jej odpytanie powinno po tym fakcie zwrócić zaktualizowany status.
