### ISSUE TITLE
Sandbox - zablokowanie konto do sprzedaży

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#2824]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
Komunikat: 

Dla funkcji sale/offers

"code": "VALIDATION_ERROR",
"message": "Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).",

Na koncie: SandboxInvestmag
Na https://allegro.pl.allegrosandbox.pl nie mam żadnych komunikatów

Proszę o odblokowanie.

**Comment by MaciejFrackowiak** [comment]
Na koncie widnieje blokada sprzedaży - ureguluj proszę należności poprzez symulator płatności dostępny na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by KrzychuWalek** [comment]
Bardzo dziękuję za pomoc, pomogło.
