### ISSUE TITLE
Nie można przesłać zdjęcia z AWS S3

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#2825]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: `f550fe1e0c8853c7`

Witam podczas próby przesłania zdjęcia umieszczonego na AWS S3:  

[link do zdjęcia](http://s3-eu-west-3.amazonaws.com/droplo/allegro_P8ZYyNHXFKhzVJYLfWLMXVj6g1QEX512JTiXejhR07DGStrKaOKLUEYHfspBvOSM.jpeg)

dostaje error:
```js
{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}
```
Kiedy to samo zdjęcie wysyłam z tego linku(i innych różnych od AWS) wszystko działa:

[link do zdjęcia](https://static4.redcart.pl/templates/images/thumb/0/0/0/pl/0/templates/images/allegro_P8ZYyNHXFKhzVJYLfWLMXVj6g1QEX512JTiXejhR07DGStrKaOKLUEYHfspBvOSM.jpeg)

Próbowałem z innymi zdjęciami, przez http i przez https ale nic to nie daje.

**Comment by MaciejFrackowiak** [comment]
Zweryfikowaliśmy Twój przypadek - zdjęcie zostało wgrane z niepoprawnym "content-type: jpeg" - prawidłowa wersja to "content-type: image/jpeg". Jednocześnie ze swojej strony poprawimy zwracany komunikat - otrzymałeś błąd 500, a dla porządku powinien być 400 z tłumaczeniem błędu.

**Comment by AnimalDEV** [comment]
Dziękuję za pomoc, rozwiązało to problem.
