### ISSUE TITLE
Wyszukiwarka

### ISSUE THREAD

**Issue by bodzimierz** [allegro/allegro-api#2826]
1. Czy można wyszukiwać oferty dodane w podanym przedziale czasowym?

2. Czy można wyszukiwać aukcje, które są / nie są zestawami?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na pytania:
1. Nie, nie ma takiej opcji, oferty możesz tylko posortować wg najnowszych ("-startTime");
2. Nie ma takiej możliwości.
