### ISSUE TITLE
After Sale Services

### ISSUE THREAD

**Issue by Peymanpn** [allegro/allegro-api#2827]
Hello Allegro team

I was wondering when will we be able to create after-sale services such as warranty, return policy and implied warranty?

Is there any specific time for these to be ready so we can do CRUD operations on these Items through REST ?

Kind Regards!

**Comment by MaciejFrackowiak** [comment]
Hi @Peymanpn 

We have it in our backlog for developing REST API - it should be available in near future, but unfortunately I cannot give you exact date.

**Comment by Peymanpn** [comment]
thanks for the reply
I am very keen to see it working.

good luck

**Comment by Peymanpn** [comment]
Hello again
sorry for bothering you again.
is there any estimated time? 
I just wanted to know the raw estimated time table, like is it possible to be ready in weeks, a month or more?
this is going to affect our design timeline, and application features.

Kind Regards

**Comment by MaciejFrackowiak** [comment]
I can write only - it will be available sooner than later - but no exact date is known.
