### ISSUE TITLE
Ocena produktu z poziomu API

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#2828]
Dzień dobry,
istnieje, a może jest w planach metoda która pokaże oceny (gwiazdkowe) które lajkują lub nie inni użytkownicy serwisu. Na tej podstawie moglibyśmy decydować o sprzedaży konkretnego produktu, zliczanie tego ręcznie jest bardzo kłopotliwe.

**Comment by MaciejFrackowiak** [comment]
Takie rozwiązanie mamy odnotowane na liście sugestii dalszego rozwoju zasobów REST API Allegro - Twój głos dodaję do pomysłu.

**Comment by 4sp3ll** [comment]
Popieram, taki zasób jest potrzebny.

**Comment by MaciejFrackowiak** [comment]
@4sp3ll Twój głos również zapisuję.
