### ISSUE TITLE
CheckoutFormNotFoundException - /order/checkout-forms/{checkoutFormId}

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#2829]
Witam serdecznie,
po odpytaniu /order/checkout-forms/{checkoutFormId} otrzymuję błąd 404 z informacją CheckoutFormNotFoundException.
Czy taka sytuacja jest normalna (i należy ją po swojej stronie jakoś obsłużyć) czy wystąpił jakiś błąd w Allegro?
Dziękuję za informację

**Comment by MaciejFrackowiak** [comment]
Taki komunikat zwracamy, gdy dany checkoutForm.id nie jest dostępny na danym koncie (np. zamówienie dotyczy pochodzi z innego konta lub połączono kilka zamówień w jedno, z nowym checkoutForm.id).

**Comment by pliszka2** [comment]
@MaciejFrackowiak dziękuję za szybką reakcję, przy okazji można poprosić o informację jak poprawnie obsłużyć taki przypadek ? Przyjdzie kolejny event z /order/events z nowym ID i nowym checkoutFormId ?

**Comment by MaciejFrackowiak** [comment]
@pliszka2 Dokładnie tak - pojawi się nowy event i nowy checkoutForm.id. Zajrzyj proszę do [naszego poradnika](https://developer.allegro.pl/orders/#02), gdzie opisaliśmy taki przypadek.

**Comment by pliszka2** [comment]
@MaciejFrackowiak dziękuję czytałem nie raz :) ale nie do końca wszystkie zdarzenia jak i ich chronologia oraz sposób działania są dla mnie jasne :) 

Z jednej strony mamy diagram na którym widać wprost: jest status READY_FOR_PROCESSING to działamy ale następnie w informacjach jest "Możesz np. otrzymać kilka zdarzeń READY_FOR_PROCESSING" stąd też zostało wszystko oparte o "identyfikator zamówienia" i on tak defakto jest pobierany do przetwarzania zamówień ale właśnie obiekt "zniknął" co jest w sumie zgodne z "W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy" ale nie sądziłem że przedtem otrzymam je w postaci eventu do przetworzenia :) 

W takim przypadku pobrałem eventy przez /order/event-stats następnie chciałem pobrać dane klienta niestety nie były one dostępne (błąd 404)

Jest może gdzieś dostępna cała rozpiska w postacji grafu w jaki sposób przy jakich akcjach użytkownika wysyła odpowiednie eventy ? czy jedyna opcja to założenie konta na sandboxie i wygenerowania sobie takich specyficznych przypadków ?

**Comment by pliszka2** [comment]
@MaciejFrackowiak może jeszcze zapytam dla pewności bo może tutaj robię błąd "dlatego zwróć uwagę na identyfikator zamówienia w obiekcie checkoutForm i to właśnie na nim oprzyj swoją logikę obsługi zamówień." to pole "id" przekazywane jako parametr /order/checkout-forms/{id} czy "id" dostępne w lineItems[{nr}].id czyli w pojedynczym przedmiocie zamówienia ?

**Comment by MaciejFrackowiak** [comment]
Jeżeli w zdarzeniach ujrzysz status READY_FOR_PROCESSING oznacza to, że w danym zamówieniu nic się już nie zmieni (zostało opłacone lub kupujący wybrał przesyłkę za pobraniem). Zmiana checkoutForm.id (czyli stworzenie nowego łącznego zamówienia) może nastąpić tylko, gdy dane pojedyncze zamówienia są w statusie BOUGHT lub FILLED_IN.
W dzienniku możesz znaleźć kilka razy to samo zdarzenie np. READY_FOR_PROCESSING - to nic "złego", jeśli checkoutForm.id będzie to samo, to dotyczy tego samego zamówienia, czyli możesz łatwo znaleźć duble - tu warto także spojrzeć na pole occuredAt.

**Comment by pliszka2** [comment]
@MaciejFrackowiak na razie zamykam (jeszcze troszkę pracy przede mną żeby przypisać akcje użytkownika do otrzymanych zdarzeń, poszedłem w kierunku sandboxa i prześledzenia jakie eventy faktycznie są wysyłane i jakie mają dane (z tego co aktualnie widzę to nie jestem w stanie pobrać danych jeśli ktoś nie wypełni FOD więc zakładam że dane kupującego trzeba będzie pobrać przez inny endpoint).
Jeśli coś by nie szło po mojej myśli to pozwolę sobie otworzyć to zgłoszenie ponownie z nowymi pytaniami dotyczącymi problemu :)
