### ISSUE TITLE
deep of category tree?

### ISSUE THREAD

**Issue by damiankrawiec** [allegro/allegro-api#283]
Can I check max deep of whole category tree in allegro?

**Comment by PawelTaberski** [comment]
If you want to loading a full tree of categories available in a selected country use[ doGetCatsData ](https://allegro.pl/webapi/documentation.php/show/id,1101)data.

**Comment by damiankrawiec** [comment]
Yes yes, i got it:) i've already "looped" through the array. Thank!!
