### ISSUE TITLE
Co oznacza product.pmd.id?

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2830]
Przy próbie aktualizacji aukcji można odczytać zwrotkę z następującym błedem: ConstraintViolationException.NotBlank i jako path: product.pmd.id? 
Na jakie pole wskazuje ta ścieżka?

**Comment by MaciejFrackowiak** [comment]
Komunikat ten odnosi się do pola "product.id".

**Comment by ponowemu** [comment]
Dzięki, problem rozwiązany!
