### ISSUE TITLE
Brak numeru telefonu/niepoprawny numer READY_FOR_PROCESSING / PACZKOMAT (i inne odbiory w punktach)

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2831]
W otrzymanym formularzu zakupowym w statusie `READY_FOR_PROCESSING`, w którym klient wybrał Paczkomat (`delivery.method.name` = `Allegro Paczkomaty 24/7 InPost`) brakuje telefonu klienta. NULL zarówno w `delivery.address.phoneNumber` jak i `buyer.phoneNumber`. O co chodzi?

Formularz do wglądu: `02d0fe56-4d68-11ea-a91f-cdb7375fc965`

Dodatkowo dlaczego Allegro NIE sprawdza numery telefonów dla Paczkomatów/PaczkaWRuchu/PocztaOdbiorWPunkcie? Mam transakcje, gdzie są numery zagraniczne, np. `53ac3f34-4d93-11ea-9ebb-af41b8f8db9f` lub stacjonarne.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem opisany przypadek - mamy tu do czynienia ze splotem wypadków niestety. Zakup został dokonany przez kupującego, który uzupełnił swoje dane na koncie dopiero w momencie zakupu. Dodatkowo cała operacja była wykonywana przez aplikację mobilną. I tu w pewnym kroku walidacja pozwoliła na zapisanie danych bez uzupełnionego numeru telefonu. Kolejne kroki, czyli przejście do koszyka i zakup to już konsekwencja wcześniejszego zdarzenia.
Co do zasady to obecnie wymagamy podania numeru telefonu przy zakupach - liczymy, że kupujący podaje prawidłowy numer - nie mamy sposobności walidowania czy każdy podany numer jest prawidłowy.
