### ISSUE TITLE
Obsługa wielu kont

### ISSUE THREAD

**Issue by MichalKosowski** [allegro/allegro-api#2832]
:bulb: **Sugestia**

Hej,

Nasz produkt ma wielu klientów którzy posiadają kilka kont na Allegro oraz kilka komputerów pracowniczych. W miarę ogarnęliśmy temat synchronizacji tokenów pomiędzy komputerami.

Pozostaje nam tylko jeden problem - niewłaściwa autoryzacja klienta. Klienci to często osoby nietechniczne, dlatego w momencie autoryzacji aplikacji nie sprawdzają, dla którego konta pobierają token. Często zdaża się że klient myśli iż dodał aplikację do wszystkich n kont a tak naprawdę zautoryzował jedno konto wielokrotnie.

Czy moglibyście dodać:
- jakiś parametr w url który wymusiłby użycie danego konta?
- informacje o koncie (email bądź nazwa używkotnika) w JWT tokenie?
- cokowliek innego ;)

Wydaje mi się że dodanie informacji o użytkowniku do tokena to bardzo mała zmiana i dość powszechna w tego typu tokenach... Osobiście ździwiliłem się że token takowej nie posiada...

Pozdrawiam,
Michał Kosowski

**Comment by MaciejFrackowiak** [comment]
Jeżeli zdekodujesz zawartość tokena znajdziesz tam pole "user_name", gdzie zwracamy id konta użytkownika, dla którego dany token został wygenerowany.

**Comment by MichalKosowski** [comment]
Ok, i co ja mogę z tym zrobić? Sam nie znam i nigdy nie używałem tego id, normalnie uzytkownik operuje na poziomie loginu / maila... szczerze nawet nie wiem gdzie mój user Id znaleźć w ustawieniach allegro? Nie ma go w danych konta...

**Comment by MaciejFrackowiak** [comment]
Korzystając z zasobu [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) otrzymasz zarówno id konta, jak i login. Natomiast na stronie WWW id konta możesz łatwo odczytać poprzez wyszukanie danego użytkownika i przeklikanie się na zakładkę Oceny i komentarze - w adresie URL zobaczysz: https://allegro.pl/uzytkownik/id_konta/oceny

**Comment by MichalKosowski** [comment]
Ok, czyli to co sugerujesz to np.:
1. Po pobraniu Tokena wysłać zapytanie GET / me używając nowo otrzymany token
2. Z odpowiedzi pobrać dane użytkownika i porównać je z tymi które klient wprowadził w aplikacji lub wyświetlić klientowi to potwierdzenia.

Faktycznie, w ten sposób można w jakiś sposób wykryć niewłaściwą autoryzację. Problem polega na tym że dzieje się to już po fakcie. Tzn. jeśli użytkownik dokonał aktywacji dla KontaA a potem chciał aktywować KontoB, ale nie przelogował się w aplikacji, to dostaje nowy token dla KontaA, tym samym unieważniając poprzednią autoryzację. W takim wypadku musimy albo nowym tokenem dla KontaB nadpisać poprzedni token KontaA i ponowić aktywację dla KontaB, albo rozpocząć aktywację obu kont od nowa... Szkoda że nie da się wymusić autoryzacji pod konto w momencie przesyłanie rządania :/

**Comment by foxbyte-pl** [comment]
@MichalKosowski wydaje mi się, że możesz weryfikować to, czy klient autoryzuje właściwe konto, zanim zapiszesz pobrany token do bazy. Wtedy sprawa jest prosta.

Klient powinien autoryzować konto B, loguje się na konto A, system pobiera token.

Zapisujesz token do zmiennej, dekodujesz go i sprawdzasz czy ID konta z tokenu zgadza się z ID konta B, które zapisałeś przy wcześniejszej autoryzacji. Jeżeli tak -> wysyłasz nowo pobrany token do bazy, jeżeli nie -> pokazujesz klientowi info że zautoryzował się na niewłaściwym koncie.

**Comment by MichalKosowski** [comment]
Tak, ale z tego co zaobserwowałem, to przy ponownym żądaniu autoryzacji, dostaję nowy token, który jest inny niż ten przy poprzenim requescie i nowy refresh token.
To oznacza, że tokeny do KontaA, jeśli nie zostaną nadpisane, to przestaną działać... chyba że źle zrozumiałem flow?

**Comment by MaciejFrackowiak** [comment]
Dobre rozwiązanie podajesz - jednocześnie powinieneś skorzystać z funkcjonalności prompt=confirm, aby użytkownik był pewien na jakie konto autoryzuje się.
