### ISSUE TITLE
Sandbox. Prawdopodobnie zły status zamówienia po dokonaniu pozytywnej płatności dla punktów odbioru

### ISSUE THREAD

**Issue by hYOUstone** [allegro/allegro-api#2833]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Po zakupie (Dla punktów odbioru: Paczka24 Odbiór w Punkcie, Punkty Poczta, Żabka, Orlen, Ruch, Paczka w RUCHu) i dokonaniu (testowej) POZYTYWNEJ płatności (szybki przelew/mBank) statusy zamówienia powinny ustawiać się raczej na READY_FOR_PROCESSING/NEW a wskakuje FILLED_IN/NEW (nie sprawdzałem na produkcji)

**Comment by MaciejFrackowiak** [comment]
Problem udało mi się powtórzyć na testowych transakcjach na Sandbox - przekazałem go już do weryfikacji. Dzięki za zgłoszenie @hYOUstone

**Comment by MaciejFrackowiak** [comment]
@hYOUstone Problem na Sandbox został wyeliminowany - nowe transakcje będą miały już właściwy status.
