### ISSUE TITLE
doLoginWithAccessToken 

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2835]
Witam,
Mam kilka pytań odnośnie webapi. W przypadku logowania za pomocą doLoginWithAccessToken dostaję sessionHandlePart.

1. Jak długo jest ważna sesja? Tak długo jak ważny jest token, który ją stworzył?
2. Czy generowanie kolejnej sesji deaktywuje starą? Jeżeli nie, to ile sesji mogę mieć utworzonych w jednym momencie.
3. Jakie podejście jest proponowane. Do każdego request generowanie nowej sesji? Czy cache sesji i używanie jej tak długo, aż jest ważna.

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na Twoje pytania:

1) w Allegro mamy tzw. niekończącą się sesję tj. wykonanie danej operacji przedłuża jej ważność o kolejne 30 dni;
2) naraz można mieć otwartych 20 sesji, kolejna sesja - 21 zamyka sesję nr 1 itd.;
3) sugerujemy zoptymalizowanie wysyłania kolejnych requestów - tym bardziej, że dana operacja przedłuża ważność sesji.

**Comment by artzie92** [comment]
Dzięki za odpowiedź
Czyli wystarczy, że za pomocą tokenu, raz ustanowię sesję i będę pilnować tego aby co minimum 30 dni ją wykorzystać? I nawet kiedy wygaśnie token z oAuth, który ją autoryzował to sesja nadal będzie aktywna?

**Comment by MaciejFrackowiak** [comment]
Pamiętaj jednak, że każde logowanie przez WWW, kolejny token, itd. wlicza się w pulę 20 sesji.

**Comment by artzie92** [comment]
Mam konto, które jest wykorzystywane tylko w jednej aplikacji i nie następuje nigdzie logowanie, a i tak dostaję komunikat
**System.ServiceModel.FaultException: Sesja wygasła! Proszę zalogować się jeszcze raz!**
Więc chyba nie działa to do końca tak jak powinno.

**Comment by MaciejFrackowiak** [comment]
Sprawdzam dokładnie funkcjonowanie metody, wrócę z odpowiedzią.

**Comment by artzie92** [comment]
Taką informację znalazłem tutaj: https://allegro.pl/webapi/tutorials.php/tutorial/id,121 
**Klucz sesji - to klucz identyfikujący naszą sesję logowania. Dostajemy go po wywołaniu metody doLogin(Enc). Jest wymagany do wszystkich operacji dotyczących konta. Jest to klucz krótko trwały (czas trwania sesji wynosi 1 godzinę) i generowany jest każdorazowo podczas logowania.**

Jeżeli doLoginWithAccessToken działa analogicznie do tej metody, to czy ważność nie jest 1h?

**Comment by MaciejFrackowiak** [comment]
Trochę to trwało, jednak wracam z wiążącymi informacjami. Wywołanie doLogin otwiera obecnie sesję, która trwa 6 godzin - i wszelkie kolejne wywołania nie przedłużają jej. Dokonaliśmy też update informacji w [FAQ](https://allegro.pl/webapi/faq.php#faq_0).
