### ISSUE TITLE
Jak pobrać oferte z parametrami. 

### ISSUE THREAD

**Issue by mmasztalerczuk** [allegro/allegro-api#2836]
Czy istnieje jakiś sposób żeby podczas wyszukiwania aukcji /offers/listing dostać informacje o parametrach produktu?Albo żeby móc sprawdzić te informacje dla konkretnej oferty? 
Próba użycja /sale/offers/{offers_is} dla nie swojej aukcji zwraca brak dostępu. 

Czy istniałaby możliwość dodania filtru do kategorii po "id": "201105", ("name": "Numer produktu") dla kategorii 17865 (Klocki Lego)? Jest to chyba jedyny parametr po którym nie można filtrować dla tej kategorii.

**Comment by MaciejFrackowiak** [comment]
Nie, dla zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) nie zwracamy struktury parametrów dla ofert. Możesz je tylko pobrać odpytując o swoje oferty poprzez [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

Parametr "Numer produktu" to parametr opcjonalny, w który sprzedający de facto może wpisać "wszystko", zatem filtrowanie po nim może rodzić nieprecyzyjne wyniki.

**Comment by mmasztalerczuk** [comment]
Czy będzie implementowany endpoint który umożli pobieranie publicznie dostepnych informacji o  ofercie która nie nalezy do nas?

**Comment by MaciejFrackowiak** [comment]
Szczegóły dot. przyszłości tej funkcjonalności podamy na początku Q4 zgodnie z [harmonogramem](https://developer.allegro.pl/schedule/).
