### ISSUE TITLE
Koszty prowizji w poszczególnych kategoriach

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2837]
Witam,
czy istnieje możliwość pobrania np. obiektu z prowizjami które obowiązują aktualnie w poszczególnych kategoriach Allegro. Np.

CategoryID: 010101
Fee: 10%
itd.

Chodzi mi o wykaz wszystkich kategorii ALBO wybrane kategorii. Wartości te, jak wiadomo, mogą się dynamicznie zmieniać.
Chciałbym aby moje oprogramowanie wykonywało sprawdzenie aktualnej stawki dla wybranej kategorii.

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy wprost takiego zasobu. Korzystając z [POST /pricing/fee-preview](https://developer.allegro.pl/documentation/#operation/previewFeesPublicAPIUsingPOST) możesz natomiast sprawdzić jakie opłaty naliczymy dla konkretnych warunków danej oferty. Zasób szczegółowo opisaliśmy w [naszym poradniku](https://developer.allegro.pl/charges/#2).

**Comment by 4sp3ll** [comment]
Super, dziękuję za odpowiedź :)
