### ISSUE TITLE
Wyróżnienia na aukcji - historia

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2838]
Witam,
potrzebuje pobrać informację o historii wyróżnień/pogrubień/podświetleń/str. działu dla konkretnej aukcji, tj. miałoby wyglądać to tak (dla cykli 10 dniowych):
cykl1 wyróżnienie: tak, pogrubienie: nie, podświetlenie: nie, str. działu: nie
cykl2 wyróżnienie: tak, pogrubienie: nie, podświetlenie: tak, str. działu: nie.
cykl3 ....

ilość cykli wstecz może być ograniczona, np. do ostatnich 10. Wiem, że można zrobić coś takiego.
Jeżeli wymagane jest połączenie REST API z SOAP API to nic nie szkodzi.
Z góry dziękuję za odpowiedź!

**Comment by MaciejFrackowiak** [comment]
Takie możliwości posiada zasób [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) - zajrzyj do [naszego poradnika](https://developer.allegro.pl/charges/#0), gdzie opisaliśmy jego działanie.

**Comment by 4sp3ll** [comment]
Nie chodzi o biling zalogowanego użytkownika, tylko historię opcji dodatkowych dla **dowolnej** oferty w całym serwisie.

**Comment by 4sp3ll** [comment]
Na pewno da się to zrobić, ponieważ widziałem już coś takiego w innym programie.

**Comment by MaciejFrackowiak** [comment]
Nie, nie posiadamy w REST API takiego zasobu by pobrać taką historię dla dowolnej oferty w serwisie.
