### ISSUE TITLE
Błąd z ilością w REST API

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#2839]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dla aukcji 8531607932 metoda

/sale/offers/8531607932

zwraca mi w sekcji stock->available

    [stock] => stdClass Object
        (
            [available] => 10
            [sold] => 2
        )
Ilość 10, a poprawną wartościa jest 4, co jest widoczne na aukcji

![image](https://user-images.githubusercontent.com/43699922/74604065-9e685c00-50ba-11ea-9361-361047473db0.png)

Dlatego niepotrzebnie mój system wykonuje co chwilę próbę naprawy ilosci na aukcji.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, stock dla tej oferty wymaga ujednolicenia - przekazałem już problem do właściwego działu.

**Comment by mkaluszka** [comment]
Czy jeśli mam takie inne oferty mam je tu wkleić czy to się poprawi we wszystkich moich ofertach?

**Comment by MaciejFrackowiak** [comment]
Potrzebujemy konkretne identyfikatory ofert - nie mamy możliwości masowego odświeżenia stocków wszystkich ofert.

**Comment by mkaluszka** [comment]
7542691447
7652073163
7849113876
8503691582

**Comment by MaciejFrackowiak** [comment]
Oferty z obu postów mają już zsynchronizowane stocki.

**Comment by WGRINGO** [comment]
U naszego klienta też są problemy ze stanami magazynowymi:
Niektóre stany idą dobrze, a niekiedy wywala np. coś takiego:

400 {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/8920445032","userMessage":null}]}

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Sprawdziłem stock oferty 8920445032 - jest zgodny (taki sam) dla GET /sale/offers/{offerId} oraz GET /sale/offers.

**Comment by WGRINGO** [comment]
Tylko, że po wywołaniu powinno być sztuk 1, a na aukcji widnieje 2. Pytanie dlaczego aktualizacja stanu się nie powiodła. W szczegółach błędu jest tylko null, a nieraz wywołanie przechodzi bo na większości aukcji nie ma problemu.

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Proszę pokaż nam swój request i response wraz z trace-id - najlepiej będzie, gdy prześlesz je nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) - w treści wiadomości dodaj numer posta #2839

**Comment by WGRINGO** [comment]
400 {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/8920445032","userMessage":null}]}

REQ:

{"id":"8920445032","name":"ETI Blok rozdzielczy 125A 4x11 zacisków","category":{"id":"46107"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"11325","valuesIds":["11325_2"],"values":[],"rangeValue":null}],"ean":"3838895633389","description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Blok rozdzielczy 125A (4x11 zacisków) EDB-411 (001102304) renomowanej firmy ETI POLAM</h1> <p><b>Dane techniczne:</b></p> <ul> <li>Prąd znamionowy In: 125 A  </li><li>Rodzaj połączenia elektrycznego 1: Połączenie śrubowe  </li><li>Liczba biegunów: 4  </li><li>Sposób montażu: Szyna montażowa DIN 35 mm  </li><li>Wysokość przy najniższym sposobie montażu: 50 mm  </li><li>Wymagana płytka zamykająca: Tak  </li><li>Przezroczysty: Tak  </li><li>Napięcie znamionowe: 400 V  </li><li>Pozycja połączenia: Z boku / boczny  </li><li>Liczba zacisków na biegun: 11  </li><li>Materiał elementu izolacyjnego: Tworzywo termoplastyczne  </li><li>Długość: 100 mm  </li><li>Kolor: Szary</li></ul>
<p>Zdjęcie jest zdjęciem poglądowym</p>"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/11501a/77a1e5b9418c9c5daca63172a77f"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"44.46","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":2,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"a323caa9-8aac-4fa8-9b7b-128f18fb9baa"},"handlingTime":"PT0S","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"2bbeff01-3491-44d0-9a02-fc97297c4345"},"returnPolicy":{"id":"0429e8b6-428e-423b-8d60-4fafd3487a99"},"warranty":{"id":"d3c88676-b2bb-43ae-9837-3cdd1dc9d0b0"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"MAZOWIECKIE","city":"Sierpc","postCode":"09-200"},"external":{"id":"ETI-001102304"},"attachments":[],"contact":null,"validation":{"errors":[],"validatedAt":"2020-02-04T08:11:26.689Z"},"createdAt":"2020-02-04T08:08:24.000Z","updatedAt":"2020-02-04T08:13:21.979Z","stock":{"available":1,"unit":"UNIT"}}

**Comment by WGRINGO** [comment]
Chyba widzę jedną rzecz co jest nie tak - stock jest dwa razy wpisywany z dwoma wartościami. Zobaczę czy to to.

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Czy potwierdziłeś źródło problemu, którym był dwukrotnie podawany stock?

**Comment by WGRINGO** [comment]
Niestety, przyczyna leży gdzieś indziej:

Taki request metodą PUT powoduje błąd 400:

{
  "id": "8920445032",
  "name": "ETI Blok rozdzielczy 125A 4x11 zacisków",
  "category": {
    "id": "46107"
  },
  "product": null,
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "11325",
      "valuesIds": [
        "11325_2"
      ],
      "values": [],
      "rangeValue": null
    }
  ],
  "ean": "3838895633389",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>Blok rozdzielczy 125A (4x11 zacisków) EDB-411 (001102304) renomowanej firmy ETI POLAM</h1> <p><b>Dane techniczne:</b></p> <ul> <li>Prąd znamionowy In: 125 A  </li><li>Rodzaj połączenia elektrycznego 1: Połączenie śrubowe  </li><li>Liczba biegunów: 4  </li><li>Sposób montażu: Szyna montażowa DIN 35 mm  </li><li>Wysokość przy najniższym sposobie montażu: 50 mm  </li><li>Wymagana płytka zamykająca: Tak  </li><li>Przezroczysty: Tak  </li><li>Napięcie znamionowe: 400 V  </li><li>Pozycja połączenia: Z boku / boczny  </li><li>Liczba zacisków na biegun: 11  </li><li>Materiał elementu izolacyjnego: Tworzywo termoplastyczne  </li><li>Długość: 100 mm  </li><li>Kolor: Szary</li></ul>'#$A'<p>Zdjęcie jest zdjęciem poglądowym</p>"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tecdocSpecification": null,
  "images": [
    {
      "url": "https://a.allegroimg.com/original/11501a/77a1e5b9418c9c5daca63172a77f"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "44.46",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null
  },
  "publication": {
    "duration": null,
    "status": "ACTIVE",
    "startingAt": null,
    "endingAt": null,
    "endedBy": null,
    "republish": false
  },
  "delivery": {
    "shippingRates": {
      "id": "a323caa9-8aac-4fa8-9b7b-128f18fb9baa"
    },
    "handlingTime": "PT0S",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "2bbeff01-3491-44d0-9a02-fc97297c4345"
    },
    "returnPolicy": {
      "id": "0429e8b6-428e-423b-8d60-4fafd3487a99"
    },
    "warranty": {
      "id": "d3c88676-b2bb-43ae-9837-3cdd1dc9d0b0"
    }
  },
  "additionalServices": null,
  "sizeTable": null,
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "MAZOWIECKIE",
    "city": "Sierpc",
    "postCode": "09-200"
  },
  "external": {
    "id": "ETI-001102304"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [],
    "validatedAt": "2020-02-04T08:11:26.689Z"
  },
  "createdAt": "2020-02-04T08:08:24.000Z",
  "updatedAt": "2020-02-04T08:13:21.979Z",
  "stock": {
    "available": 1,
    "unit": "UNIT"
  }
}

**Comment by MaciejFrackowiak** [comment]
Widzę, że Twoje dwa requesty z godz. 9:55 zakończyły się statusem 200.

**Comment by WGRINGO** [comment]
Znalazłem przyczynę:
W opisie jest coś takiego:

'#$A'
Zdjęcie jest zdjęciem poglądowym 

Po usunięciu z opisu znaku '#$A' który odpowiada za następną linię czyli <LF> problem ustąpił.

**Comment by MaciejFrackowiak** [comment]
W opisie oferty możesz używać tylko ściśle określonych znaczników - proszę zapoznaj się z [ich listą](https://developer.allegro.pl/sale/#step-5-description).

**Comment by WGRINGO** [comment]
Tak zgadza się, tylko opis ten dostałem razem z enterami po użyciu funkcji GET na /sale/offers/.
Jakimś cudem się tam znalazły wiec albo walidator puścił te znaki wcześniej choć nie powinien albo funkcja get powinna wyfiltrować te znaki jeśli mimo wszystko się tam znalazły. Myślę, że nie zaszkodziłoby dodatkowo to zabezpieczyć.
Dziękuje i pozdrawiam :)

**Comment by MaciejFrackowiak** [comment]
Przyjrzymy się tej kwestii :)

**Comment by WGRINGO** [comment]
Czy bug zgłoszony przez mkaluszka jest już rozwiązany? Aukcja o ID 8977333911 powinna mieć stan=8 a pokazuje 1

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Problem, który @mkaluszka zgłaszał dotyczył konkretnych ofert i tylko ich stocki zostały ujednolicone.
Dla oferty, którą zgłaszasz (8977333911) stock jest tożsamy przy odpytywaniu GET /sale/offers oraz GET /sale/offers/{offerId} - 1 - nie ma tu nieprawidłowości.

**Comment by mkaluszka** [comment]
8672818641

Proszę jeszcze sprawdzić ta ofertę. Na teraz powinna być ilość 3 dostępną. Nie jestem w stanie takiej ustawić ani przez formularz ani przez api. Przez formularz ustawiam 3 + sprzedane 8 czyli 11 a dostępne mam po zmianach 12

**Comment by PrzemyslawLukanowski** [comment]
@mkaluszka Przekazałem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@mkaluszka Uspójniliśmy stock dla tej oferty. Możesz już prawidłowo edytować liczbę sztuk.

**Comment by WGRINGO** [comment]
U naszego klienta dalej jest problem:
https://allegro.pl/oferta/ospel-gniazdo-antenowe-typu-f-pojedyncze-9028621195

Dnia 05.03.2020 09:01:12 został wysłany request ze zmianą stanu, nie było żadnego błędu.
Stan powinien pokazywać 20 a jest 1.

Czy możecie sprawdzić o co chodzi ?

**Comment by MaciejFrackowiak** [comment]
@WGRINGO Wskazana oferta została po raz pierwszy aktywowana dzisiaj tj. piątek, 6 mar 2020, 09:41:48, zatem wczoraj nie mógł być dla niej wysłany request ze zmianą.

**Comment by WGRINGO** [comment]
Ok rozumiem teraz gdzie leży błąd. Dziękuję za informację.
