### ISSUE TITLE
mail o ocenę zakupów

### ISSUE THREAD

**Issue by Krzysztof1324** [allegro/allegro-api#2840]
Witam.
W jaki sposób można wysłać mail do klienta z prośbą o wystawienie ozeny zakupu?
Chodzi o mail z poniższą treścią

![mail o ocene zakupów](https://user-images.githubusercontent.com/61137403/74634958-4aff1800-5165-11ea-89b2-31239f7eb78d.jpg)

**Comment by MaciejFrackowiak** [comment]
To jest email automatycznie wysyłany przez Allegro, nie jest to efekt działań sprzedającego.
