### ISSUE TITLE
Compatibility list - pusty wynik

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#2841]
Korzystając z metody GET sale/compatible-products?type=CAR&tecdoc.kTypNr= próbuje pobrać informację dla ktypów: 133248, 133249 ,133993, 135053, 135058. Za każdym razem zwracany jest pusty wynik. W moje wersji TecDoc istnieją takie ktypy. Jaki może być powód, że po stronie Allegro ich nie ma?

**Comment by MaciejFrackowiak** [comment]
Podejrzewam, że problemem może być wersja bazy, z której korzystasz - u nas są dostępne tylko samochody dopuszczone do sprzedaży na rynku polskim.

**Comment by martacronic** [comment]
![tecdoc](https://user-images.githubusercontent.com/37405655/74650864-e6eb4c80-5182-11ea-9204-940bb7f750fe.png)

Normalne auto, tylko, że dość nowe. Możliwe, że nie macie go jeszcze w swojej bazie?

**Comment by MaciejFrackowiak** [comment]
Z jakiej wersji TecDoc korzystasz?

**Comment by martacronic** [comment]
wersja 2.4

**Comment by MaciejFrackowiak** [comment]
Oznaczenie Twojej wersji różni się od naszej (0919), dlatego trudno jednoznacznie je porównać.

**Comment by martacronic** [comment]
Napisałam jaką mam wersję TecDoc. Oznaczenie 0919, to oznaczenie wskazujące na to, że macie dane TecDoc z września 2019. Ja posługuje się już wersją 0120 w tej nomenklaturze, czyli styczeń 2020. Mamy nowy rok, więc i w tej wersji jest sporo nowych rzeczy. TecDoc w naszym wypadku aktualizujemy kwartalnie. Czy macie jakiś harmonogram kiedy planujecie aktualizować dane TecDoc po Waszej stronie, tak, żebyśmy mogli się do tego dostosować?

**Comment by MaciejFrackowiak** [comment]
Staramy się możliwie często aktualizować nasze źrodło danych, jednak tu musimy działać w szerszym kontekście - nasze zmiany w rezultacie mogą dotknąć znacznej ilości ofert w serwisie,  szeregu sprzedających, dlatego nie jest to działanie ad hoc i dopiero po zapewnieniu pełnej zgodności względem ofert taką zmianę wprowadzamy. Wyprzedzając pytanie - na chwilę obecną nie mam możliwości wskazania terminu kiedy przeprowadzimy kolejny update bazy.

**Comment by martacronic** [comment]
Lista brakujących aut jest dość obszerna. Jak dodacie auta do Waszej bazy, to będę wdzięczna za taki komunikat.

**Comment by MaciejFrackowiak** [comment]
Obecnie pracujemy nad rozwiązaniem, które umożliwi wprowadzanie nowej wersji bazy bezpośrednio po jej udostępnieniu nam przez TecDoc.

**Comment by martacronic** [comment]
@MaciejFrackowiak bot przypomina, że minął miesiąc. Jak tam postępy w aktualizacja bazy TecDoc?

**Comment by MaciejFrackowiak** [comment]
@martacronic Prace w nadal w toku.

**Comment by martacronic** [comment]
Odświeżam wątek, żeby nie zakładać nowego. Czy w kwestii aktualizacji po Waszej stronie TecDoc się coś zmieniło, czy nadal wersja bazy 0919?

**Comment by MaciejFrackowiak** [comment]
W ostatnim czasie zaktualizowaliśmy bazę - obecnie jest to wersja 2019.
