### ISSUE TITLE
Get transactionId by paymentId

### ISSUE THREAD

**Issue by lechpol-devs** [allegro/allegro-api#2842]
W jaki sposób można pobrać nowy id transakcji mając id płatnośći?
ex. transactionId: 0ec9bde2-5174-11ea-9bc7-f1128cba612c
ex. paymentId: 0f82ada2-5174-11ea-82e1-3394180a29cf
Wcześniej korzystaliśmy z metody [getPaymentIdMapping](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping)
ale ona zwraca numer transkacji, a nie Id.

**Comment by MaciejFrackowiak** [comment]
Udostępniamy tylko dwa mapowania:

1) [GET /payments/payment-id-mappings](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping), gdzie podając paymentId otrzymasz transactionId i vice versa;
2) [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping), gdzie lineItemId zamienisz na dealId i vice versa.

**Comment by lechpol-devs** [comment]
> 1. [GET /payments/payment-id-mappings](https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping), gdzie podając paymentId otrzymasz transactionId i vice versa;

I otrzymam transactionId w postaci alfanumerycznej czy ten hash, tak jak podałem wyżej?

**Comment by MaciejFrackowiak** [comment]
W postaci numerycznej - tak jak zwracalśmy w WebAPI - przykładowo:

`{
  "paymentId": "2e2fe432-2115-32f9-82ae-e350e7aa9ed0",
  "transactionId": "1016873349"
}`

**Comment by lechpol-devs** [comment]
A jak mogę otrzymać tą [https://i.imgur.com/7YQYM5T.png](url) postać?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z GET /order/checkout-forms/?payment.id=xxxxxxx (gdzie xxxxx to paymentId), wówczas otrzymasz checkoutForm.id przypisany do tej płatności (czyli nr zamówienia z Twojego zrzutu).

**Comment by lechpol-devs** [comment]
Super, dzięki za pomoc ;)

**Comment by kowal0821** [comment]
Skorzystałem ze wskazówek i niestety metoda zwróciła mi null. Czy mój link jest poprawny?
https://api.allegro.pl/payments/payment-id-mappings?paymentId=xxxxx

**Comment by lechpol-devs** [comment]
Panie Mateuszu,Moim zdaniem link błędny :Skorzystaj z GET /order/checkout-forms/?payment.id=xxxxxxx18 lut 2020 15:21 Mateusz Kowalczyk <notifications@github.com> napisał(a):Skorzystałem ze wskazówek i niestety metoda zwróciła mi null. Czy mój link jest poprawny?

https://api.allegro.pl/payments/payment-id-mappings?paymentId=xxxxx

**Comment by kowal0821** [comment]
Już znalazłem problem, link był poprawny. Zmienił się model JSON.
