### ISSUE TITLE
/offers/listing a polskie znaki

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#2843]
Witam,
Proszę o informację odnośnie używania polskich znaków podczas pobierania ofert
Przykład:
https://api.allegro.pl/offers/listing?phrase=świecznik&limit=100
Nie działa
Natomiast:
https://api.allegro.pl/offers/listing?phrase=swiecznik&limit=100
Działa poprawnie

Zauważyłem, że wpisując w wyszukiwarkę zarówno swiecznik jak i świecznik daje te same wyniki.

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem wyszukiwanie dla obu fraz - otrzymałem identyczne wyniki:

`"searchMeta": {
        "availableCount": 6000,
        "totalCount": 43941,
        "fallback": false
    },`

**Comment by krzysda** [comment]
Tak tylko nie wiem dlaczego po wywołaniu zapytania przez API z polskimi znakami nie otrzymuję wyników. 

https://api.allegro.pl/offers/listing?phrase=świecznik&limit=100
400 Bad request

**Comment by MaciejFrackowiak** [comment]
To wygląda na problem narzędzia, z którego próbujesz wywołać zapytanie - nasze API bezproblemowo przyjmuje polskie znaki i jak wskazałem wyżej zwraca poprawną odpowiedź.
