### ISSUE TITLE
Uzyskanie parametrów dodatkowych metodą GET /sale/offers/{offerId}

### ISSUE THREAD

**Issue by ChrupekV2** [allegro/allegro-api#2844]
Witam,
Czy metoda GET /sale/offers/{offerId} nie obsługuje obecnie parametrów dodatkowych oferty widocznych na froncie? Przy pobieraniu takich ofert w "parameters" widoczne są tylko parametry Allegro.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, w REST API nie zwracamy parametrów własnych utworzonych przez sprzedającego.

**Comment by ChrupekV2** [comment]
Czy jest planowane dodanie takiej funkcjonalności?

**Comment by MaciejFrackowiak** [comment]
Takie rozwiązanie mamy już na liście sugestii dot. dalszego rozwoju REST API Allegro.

**Comment by ChrupekV2** [comment]
Dziękuję za pomoc, wszystko już wiadomo.
