### ISSUE TITLE
Shipping Rate access the limit to 250

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#2846]
Hi we have an issue we are using this API https://api.allegro.pl/sale/shipping-rates
And post delivery methods and firstItemRate and nextItemRate.
But not it is showing your limit has been acceded.
I want to delete that and upload it again.
Please help me.

**Comment by MaciejFrackowiak** [comment]
According to [our documention](https://developer.allegro.pl/documentation/#tag/Delivery) there is no resource to delete shipping rate - you can only edit it by [PUT /sale/shipping-rates/{id}](https://developer.allegro.pl/documentation/#operation/modifyShippingRatesSetUsingPUT) and the limit of existing shipping rates is 250.

**Comment by 07adityasingh** [comment]
we are getting this array 
Array
(
    [id] => 11f3dcf1-8847-4bee-ae19-b84b203f1f4c
    [name] => Jet Helmet Otwarty Twarz Motocykl Skuter
    [rates] => Array
        (
            [0] => Array
                (
                    [deliveryMethod] => Array
                        (
                            [id] => c9091ffb-727e-4a88-bd7c-b17dddbefb4a
                        )

                    [maxQuantityPerPackage] => 1
                    [firstItemRate] => Array
                        (
                            [amount] => 25.99
                            [currency] => PLN
                        )

                    [nextItemRate] => Array
                        (
                            [amount] => 24.99
                            [currency] => PLN
                        )

                    [shippingTime] => 
                )

        )

    [lastModified] => 2020-02-18T12:05:14.668+01:00
)

**Comment by MaciejFrackowiak** [comment]
As I wrote before you can only edit existing shipping rate - please, look into [our tutorial](https://developer.allegro.pl/en/sale/#shipping-rates).

**Comment by bugproof** [comment]
> no resource to delete shipping rate

So what. I created accidentally 100 shipping rates with the same name and now I have to delete them manually? Great.

**Comment by MaciejFrackowiak** [comment]
@bugproof You can delete them in the [Sales Center tab](https://salescenter.allegro.com/delivery-settings) now.

**Comment by bugproof** [comment]
Yup I did that but I had to do it manually. Kinda curious why it's not supported by the official API when it's supported by internal "edge" API.

**Comment by MaciejFrackowiak** [comment]
@bugproof On the WWW, when you remove a shipping rate, which is assigned to the offers, you have to choose another one - such an operation is impossible to provide if we add DELETE method to the shipping rate resources in the API.

**Comment by bugproof** [comment]
> such an operation is impossible to provide if we add DELETE method to the shipping rate resources in the API.

Logically DELETE would return an error, so it would be possible to programmatically change shipping rate of chosen offers and then DELETE.

**Comment by MaciejFrackowiak** [comment]
@bugproof Thank you for your suggestion, but we do not plan to introduce such a solution.
