### ISSUE TITLE
itStartingQuantity czy Quantity

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2847]
Witam,
Czy jak użytkownik modyfikuje ilość sztuk dostępnych w ofercie to aktualizowane jest pole itStartingQuantity czy Quantity? 
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Aktualną - dostępną w ofercie ilość sztuk określa "itQuantity".

**Comment by artzie92** [comment]
Tylko może się zmienić ponieważ ktoś kupił przedmiot. Chciałbym wiedzieć kiedy stan oferty jest aktualizowany przez użytkownika. Czy jest taka opcja?

**Comment by MaciejFrackowiak** [comment]
W przypadku tego pola nie ma takiej opcji.

**Comment by artzie92** [comment]
Czyli za pomocą globalnego event loga + szczegółów o ofercie nie da się tego sprawdzić. Jedyna opcja to doGetBids dla oferty? Czasami przez 5 mint przychodzi kilka tysięcy zdarzeń. Strzelanie do doGetBidItem2 po każdą ofertę z eventu jest trochę słabe. Proponuję aby jakoś to rozsądnie rozwiązać w REST.

**Comment by MaciejFrackowiak** [comment]
Tak, przy pomocy doGetBidItem2 uzyskasz informację o liczbie zakupionych przedmiotów. Jednocześnie dziękuję za Twoją sugestię w kontekście REST API.
