### ISSUE TITLE
metoda order/events nie zwraca statusu READY_FOR_PROCESSING dla PayU

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#2848]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
trace-id: bbd8b46496a4aadc, konto SandboxInvestmag

Problem występuje tylko przy sandboxowym zakupie przez **PayU**, 

dla zakupu gotówkowego ( 1b3fd5c2-5249-11ea-875e-a14b8f6a3728) otrzymuje kolejno event z type: BOUGHT, FILLED_IN, READY_FOR_PROCESSING

dla zakupu przez PayU (c8be21f0-524b-11ea-875e-a14b8f6a3728) wysyłam: order/events z parametrami from=1582029044450475&limit=100 i otrzymałem tylko FILLED_IN oraz BOUGHT, natomiast nie przychodzi typ READY_FOR_PROCESSING dla tego zamówienia.

jeżeli zresetuje from i wyślę order/events tylko limit=100 to wśród otrzymanych  eventów nadal nie ma READY_FOR_PROCESSING  dla c8be21f0-524b-11ea-875e-a14b8f6a3728, natomiast przychodzą kolejno z typem FILLED_IN oraz BOUGHT. Po stronie kupującego jest informacja, że zakup się powiódł (konto Investmag)

Pozdrawiam, Krzysztof.

**Comment by MaciejFrackowiak** [comment]
Tak, to podobny problem jak w poście #2833 - błąd występuje tylko na Sandbox, na produkcji jest OK. Trwają prace nad wyeliminowaniem niezgodności.

**Comment by KrzychuWalek** [comment]
Bardzo dziękuję za informację. będę maił spokojną noc. :)

**Comment by MaciejFrackowiak** [comment]
@KrzychuWalek Problem na Sandbox został wyeliminowany - nowe transakcje będą miały już właściwy status.

**Comment by KrzychuWalek** [comment]
Dziękuję.
