### ISSUE TITLE
Nie można wznowić ofert - pytanie o otrzymane błędy

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#2849]
Witam,
po odpaleniu:
POST /sale/offer-publication-commands - publication.action = ACTIVATE
i zweryfikowaniu stanu komendy oraz błędów otrzymuję następujące komunikaty błędów:

- "Could not change offer publication status. Given compatibility table is outdated, use the current one."
- "Could not change offer publication status. Selected compatibility table has different input type than supported in offer category." 

Mogę prosić o informację co i w jaki sposób powinienem zmodyfikować w ofercie by aktywacja przeszła pomyślnie ? (aktywacja ręczna poprzez panel allegro działa OK) problem dotyczy tylko wywoływania aktywacji poprzez REST API i nie dotyczy wszystkich ofert a tylko około 20%

**Comment by MaciejFrackowiak** [comment]
Już wyjaśniam:

1) "Could not change offer publication status. Given compatibility table is outdated, use the current one." - oznacza, że zmieniła się lista Pasuje do, a co za tym idzie compatibilityList.id -> należy podać aktualne compatibilityList.id by móc aktywować ofertę;

2) "Could not change offer publication status. Selected compatibility table has different input type than supported in offer category." - oznacza, że użyta została compatibilityList innego typu niż jest wspierana w danej kategorii. Mamy dwa typy list - tekstowa, gdzie wpisujesz samodzielnie marki i model pojazdów oraz opartą na identyfikatorach, gdzie pojazdy pochodzą z bazy. Podsumowując - albo próbowałeś użyć tekstowej compatibilityList w kategorii, gdzie wspierana jest identyfikatorowa albo próbowałeś użyć identyfikatorowej tam, gdzie wspierana jest tekstowa.

**Comment by pliszka2** [comment]
@MaciejFrackowiak dziękujęza informację, czy w takim układzie na stronie zarządzania ofertą (wznawianie) allegro samo dokonuje jakiejś konwersji starej oferty na nową ? Pytam gdyż ofertę o tym ID jestem bez problemu w stanie wznowić za pomocą panelu a REST API wywala właśnie takie informacje i nie do końca wiem czego ode mnie oczekuje bym mu zrobił "ekstra" :) A mam takich różnego rodzaju aukcji do przerobienia kilkadziesiąt tysięcy i zdecydowanie wolał bym wykombinować jakieś automatyczne wznawianie lub przynajmniej pół automatyczne z generowaniem raportu który ktoś kto zna temat biznesowo mógł by przejrzeć i potwierdzić że jest OK :) zakładam że w takim wypadku powinienem zmienić to pole compatibilityList poprzez edycję oferty ? (i tu pytanie czy jestem w stanie odtworzyć ten mechanizm "auto zmiany" która następuje teraz na panelu allegro całkowicie przeźroczyście (nie ma żadnej informacji że coś zostało podmienione)?

**Comment by MaciejFrackowiak** [comment]
@pliszka2 Tak, na formularzu wystawiania na WWW zmianę robimy w tle, nijako niezauważalnie dla użytkownika. Natomiast w REST API wymaga to już ingerencji poprzez edycję oferty i zmianę compatibilityList.

**Comment by pliszka2** [comment]
@MaciejFrackowiak ok dziękuję zamykam ! :)
