### ISSUE TITLE
Pytanie o id produktu (produktyzacja)

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#2850]
Witam,
Czy produkt może zmienić swoje ID?
Moje obecne rozwiązanie zakłada, że jak wyszukam w bazie allegro dany produkt to przypisuję do mojego towaru ID z bazy allegro. Zakładam, że to ID się nie zmieni.
KF

**Comment by MaciejFrackowiak** [comment]
ID danego produktu jest stałe.
