### ISSUE TITLE
Brakujące wartości dla parametru kondycja w kategori 6089

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#2851]
Witam,

W Sandboxie dla kategori 6089 do 6097 brakuje trzech wartości dla parametru kondycja
        Excellent = 11326_318393,
        Good = 11326_318397,
        LightPlayed = 11326_318401,

W środowisku produkcyjnym parametry istnieją i mają się dobrze, ale proszę o uzupelnienie ponieważ utrudnia to testy ;)

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, potwierdzam rozbieżność - dziękuję za spostrzeżenie. Problem przekazałem już do właściwego działu.

**Comment by Troom** [comment]
Kiedy mniej więcej można się spodziewać poprawki ?
Praktycznie wszystkie artykuły mam z kondycją do której brakuje wartości, więc moge testować tylko na środowisku produkcyjnym 🤕

**Comment by MaciejFrackowiak** [comment]
Temat został już zaadresowany do właściwego zespołu - to stan obecny. W tym momencie dokładnego terminu wskazać jednak nie mogę, nastąpi to możliwie szybko.
