### ISSUE TITLE
Problem z pobraniem załącznika do dyskusji

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#2852]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W naszej integracji do obsługi dyskusji występuje problem z pobraniem załącznika. Co dziwne, problem występuje tylko w przypadku jednej, konkretnej dyskusji, podczas gdy wszystkie inne otwierają się prawidłowo.

W panelu dyskusji Allegro na Waszej stronie, wszystko działa prawidłowo, ale API zwraca `upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Nie jestem w stanie podać trace-id, gdyż nie jest ono zwracane.

Załącznik, którego dotyczy problem: e4537a0f-c517-46f2-be0c-5a989262f9f4

**Comment by MaciejFrackowiak** [comment]
Proszę podaj id dyskusji oraz id konta, na którym występuje problem - sprawdzimy Twoje spostrzeżenie.

**Comment by shivson1337** [comment]
Id dyskusji: e5a9b73b-07b5-4011-aaf7-5c801466c23b
Id konta: 63196280

**Comment by MaciejFrackowiak** [comment]
Sprawdziliśmy nasze logi - w ciągu ostatnich 24 godzin 260 na 267 prób pobrania tego załącznika zakończyło się powodzeniem (status 200). Pozostałe to błędy 401 i 406. Nie widzimy u nas żadnych nieprawidłowości.

**Comment by shivson1337** [comment]
Dziwna sytuacja.
W dalszym ciągu pojawiają się dwa załączniki w tej dyskusji, których nie jesteśmy w stanie pobrać. 
![image](https://user-images.githubusercontent.com/60777356/74928043-067bb280-53d9-11ea-9204-17cbf6343478.png)

**Comment by MaciejFrackowiak** [comment]
@shivson1337 Proszę wykonaj request z próbą pobrania tego załącznika raz jeszcze.

**Comment by shivson1337** [comment]
W dalszym ciągu to samo.

Podsyłam dodatkowo ID drugiego załącznika, z którym jest problem. Może mają ze sobą coś wspólnego. 

ID: 4d5cbd73-76b2-47c5-9a3c-f0c26a329002

**Comment by MaciejFrackowiak** [comment]
Dziękuję - sprawdzamy logi, powrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@shivson1337 Dokonaliśmy niezbędnych poprawek - i tu prośba o sprawdzenie, czy już bezproblemowo możesz pobrać wspomniane załączniki.

**Comment by shivson1337** [comment]
Wygląda na to, że wszystko działa, dziękuję. ;)
