### ISSUE TITLE
pobieranie tokena z sandboxa

### ISSUE THREAD

**Issue by mobiipl** [allegro/allegro-api#2853]
Mam problem z pobieraniem tokena z sandboxa, na produkcji działa bez problemu, z sandboxa nie dostaję odpowiedzi. Korzystam z tego rozwiązania:

https://github.com/Wiatrogon/php-allegro-rest-api

**Comment by MaciejFrackowiak** [comment]
Widzę, że podana jest tam domena allegroapi.io, która obecnie nie jest już przez nas wspierana. Do wywołań na Sandbox korzystaj proszę z adresu: https://api.allegro.pl.allegrosandbox.pl/
Natomiast adres do autoryzacji to: https://allegro.pl.allegrosandbox.pl/auth/oauth/
Zajrzyj też do [naszego poradnika](https://developer.allegro.pl/about/), gdzie stworzyliśmy zestawienie kluczowych adresów.

**Comment by mobiipl** [comment]
Tak wiem, adresy pozamieniałem na aktualnie

**Comment by mobiipl** [comment]
Czy poza adresami, które miałem wprowadzone poprawne, coś jeszcze może powodować problem? Już mi się pomysły pokończyły.

**Comment by mobiipl** [comment]
temat rozwiązany
