### ISSUE TITLE
Dodanie numeru przesyłki do zamówienia

### ISSUE THREAD

**Issue by tomzara** [allegro/allegro-api#2854]
Witam,
mam mały problem z dodaniem informacji o przesyłce do zamówienia.
Serwer zwraca mi błąd: Serwer zdalny zwrócił błąd: (415) Unsupported Media Type.
W nagłówku Accept podaję wartość application/vnd.allegro.public.v1+json.
Co może być powodem błędu?

**Comment by MaciejFrackowiak** [comment]
Proszę pokaż nam swój request.

**Comment by tomzara** [comment]
Authorization: Bearer token
Accept-Language: pl-PL
Accept: application/vnd.allegro.public.v1+json


{"carrierId": "DPD", "waybill":""0000207893430U", "lineItems":"{\"id\":\"7c8b0271-51ca-11ea-b7c5-cb9519716228\"},{\"id\":\"7c8b0270-51ca-11ea-b7c5-cb9519716228\"}}

**Comment by MaciejFrackowiak** [comment]
Widzę, że przy "waybill":""0000207893430U" masz dwa razy "" przed numerem przesyłki, a ponadto lineItems nie są ujęte w [] - przykładowy prawidłowy request:

`{
    "carrierId": "DPD",
    "waybill": "1234561000789",
    "carrierName": "string",
    "lineItems": 
[
        {
            "id": "4607e5a0-5252-11ea-83af-b1a57a91a48b"
        }
    ]
}`

**Comment by tomzara** [comment]
Mimo poprawki nadal jest ten sam błąd Serwer zdalny zwrócił błąd: (415) Unsupported Media Type.

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę dokładnie, czy korzystasz z [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST), gdzie w payload musisz podać dane jak z mojego przykładu.

**Comment by deneb-k** [comment]
Od której strony by nie patrzeć, to ten Twój string nie jest prawidłowym jsonem. Ty go ręcznie rzeźbisz?

**Comment by tomzara** [comment]
json robię za pomocą JsonConvert.SerializeObject

**Comment by tomzara** [comment]
tak to wygląda:

var client = new WebClient();
client.Headers[HttpRequestHeader.Authorization] = "Bearer " + this.token.access_token;
client.Headers[HttpRequestHeader.AcceptLanguage] = "pl-PL";
client.Headers[HttpRequestHeader.Accept] = "application/vnd.allegro.public.v1+json";
client.QueryString.Add("carrierId", carrierId);
client.QueryString.Add("waybill", number);
client.QueryString.Add("carrierName", "");
client.QueryString.Add("lineItems", JsonConvert.SerializeObject(itm));

**Comment by deneb-k** [comment]
Całe body powinno być jsonem. Ty tworzysz jsonowe lineitems i później wrzucasz to do ponownej serializacji przy wysyłaniu requestu, dlatego Ci nie działa.

**Comment by pkrzemo** [comment]
W metodzie POST oprócz nagłówka Accept (mówiącego o formacie w jakim chcesz uzyskać odpowiedź) MUSISZ podać jeszcze ContentType (mówiące o formacie danych jaki przesyłasz do serwera). Ten błąd to w 99% brak ContentType="application/vnd.allegro.public.v1+json"
No i "Content" powinien zawierać prawidłowe dane....

**Comment by tomzara** [comment]
problem rozwiązany, nagłówki były poprawne.
Zmieniłem na client.UploadString i wysłąłem Json i jest ok :)
