### ISSUE TITLE
Problem z zmianą oferty POST /sale/offers

### ISSUE THREAD

**Issue by playzino** [allegro/allegro-api#2855]
Próbuje przesłać aktualziacje oferty na https://api.allegro.pl/sale/offers/ i otrzymuję błąd 

> {"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed","details":null,"path":null,"userMessage":"An error occurred"}]}

token generuje i odświeżam poprawnie, dane pobieram (zapytanie GET), ale jak próbuję "pogrzebać" w ofertach to ciągle to samo. Co robię źle? (poniżej przykładowy kod)

> 	$ch = curl_init('https://api.allegro.pl/sale/offers/');
> 	curl_setopt($ch, CURLOPT_POST, 1);
>     curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer '.$token,
> 		'Accept: application/vnd.allegro.public.v1+json',
> 		'Content-Type: application/vnd.allegro.public.v1+json'));
> 	curl_setopt($ch, CURLOPT_POSTFIELDS,'{ "name": "Oferta testowa" }');
> 	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

**Comment by MaciejFrackowiak** [comment]
W adresie masz nadmiarowy "/" - powinno być https://api.allegro.pl/sale/offers - wówczas wszystko zadziała.

**Comment by playzino** [comment]
Faktycznie pomogło, dziękuję bardzo.
