### ISSUE TITLE
Adress unavailable - czy to wina API?

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#2856]
W moim skrypcie zaciągającym dane z Allegro API do Google Data Studio raz na jakiś czas występuje taki błąd:
`
 [Exception: Address unavailable: https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms] name: 'Exception' } 
` 
Nie chodzi tylko o ten url bo błąd raz na jakiś czas pojawia się dla różnych adresów. Błąd pojawia się najczęściej kiedy następuje wiele odwołań do API w krótkim odstępie czasu. Nie znalazłem opisu takiego błędu w Waszych docsach więc zgaduję że to mi wyrzuca googlowy `UrlFetchApp`, którym pobieram dane ale wolę dopytac :)

**Comment by MaciejFrackowiak** [comment]
Tu niestety potrzebne byłyby konkretne wywołania byśmy mogli spojrzeć na to - końcowy komunikat to już "przetworzona" wersja naszej odpowiedzi, dlatego trudno ją interpretować. Wspominasz o wielu wywołaniach - w REST API mamy [limity](https://developer.allegro.pl/about/#limits), które trzeba brać pod uwagę odpytując zasoby.
