### ISSUE TITLE
Brak wizyt i obserwowanch

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#2857]
W środowisku sandboxowym dodałem kilka ofert i po kilka razy wchodziłem na nie i dodawałem do obserwowanych z innych kont. Przy ofertach w panelu oraz przez API cały czas pokazuje mi 0. Robię coś nie tak?
![alelgro](https://user-images.githubusercontent.com/7765836/74970560-da832000-541e-11ea-9122-c0de3c2ce6e3.png)

**Comment by MaciejFrackowiak** [comment]
Problem potwierdzam - zgłosiłem już do właściwego działu.

**Comment by MaciejFrackowiak** [comment]
Błąd wyeliminowany - obecnie dodając ofertę do obserwowanych z innego konta zauważysz zmianę wartości.

**Comment by przemoo83** [comment]
Potwierdzam dodanie do obserwowanych się zlicza. A na jakiej zasadzie są zliczane wizyty aukcji? Bo tu nadal mam wszędzie 0.

**Comment by MaciejFrackowiak** [comment]
Tu sprawdzane jest m.in. to czy wizyty nie mają miejsca np. z tego samego adresu IP. Ponadto dane te odświeżają się z pewnym opóźnieniem.
