### ISSUE TITLE
Zablokowane konto - nie mogę dodać ofert

### ISSUE THREAD

**Issue by blaskognia** [allegro/allegro-api#2858]
Witam,

Z nieznanych mi przyczyn w sandboxowej wersji Allegro dla konta ambicode nie mam możliwości wystawiania ofert, a jest to niezbędne w celu wykonania testów nowej wersji modułu integrującego się z Allegro. Czy mogę prosić o odblokowanie funkcjonalności dodawania ofert dla tego konta?

**Comment by MaciejFrackowiak** [comment]
Jak widzę na tym koncie masz blokadę sprzedaży z powodu nieuregulowanych należności. Proszę skorzystaj z naszego symulatora płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) - tak uregulujesz należności, a blokada zniknie.
