### ISSUE TITLE
Problem z kończeniem aukcji

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#2859]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Wejście
PUT /sale/offer-publication-commands/uuid

`
{ 
   "offerCriteria":[ 
      { 
         "type":"CONTAINS_OFFERS",
         "offers":[ 
            { 
               "id":"8976195983"
            }
         ]
      }
   ],
   "publication":{ 
      "action":"END"
   }
}
`
Wyjście
`{"id":"74caa2ee-ec91-429f-bcc3-7c6dd8e89ed8","taskCount":{"total":0,"success":0,"failed":0}`

Kolejne sprawdzenia na GET /sale/offer-publication-commands/uuid zwracaja total, succes i failed = 0

**Comment by MaciejFrackowiak** [comment]
Mamy opóźnienie w wykonywaniu zleconych zadań - staramy się możliwie szybko je nadrobić. Szczegóły zleconej operacji możesz sprawdzić poprzez [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) - tak otrzymasz precyzyjne info.

**Comment by lukada4100** [comment]
Potwierdzam, że problem wciąż występuje.

**Comment by ppart** [comment]
Również potwierdzam problem, duże opóźnienia

**Comment by MaciejFrackowiak** [comment]
@lukada4100 Widzę, że wspomniana operacja (f3f41324-eb03-427a-9eeb-b9e6a9294e06) wykonała się.
@ppart Mam nadzieję, że u Ciebie również zdecydowana większość zadań już się przeprocesowała.

**Comment by ppart** [comment]
Tak jest już na bieżąco wszystko

**Comment by lukada4100** [comment]
Tak jest. Koło 13:00 wszystko wróciło do normy.
