### ISSUE TITLE
doGetUserItems - nowa metoda alternatywna.

### ISSUE THREAD

**Issue by FredFlinston** [allegro/allegro-api#286]
Witajcie.

Nie mogę sobie poradzić z jedną sprawą.
Pisze od nowa program do pobierania danych z Allegro. Na początku miałem pewne trudności, które już pokonałem.
Mój zamysł jest następujący:
- zalogować się,
- pobrać listę moich aukcji, (wcześniej była to metoda doGetUserItems),
- pobrać dane o sprzedaży,
- dane kontrahentów i FOD.

Nie wiem czy jestem ślepy, ale nie widzę w obecnej dokumentacji metody do pobrania identyfikatorów moich aktualnych aukcji.
Pytanie brzmi: jaka jest obecnie metoda, która zwróci mi identyfikatory moich  aktualnych aukcji?

Pozdrawiam.

**Comment by AniaMalinowska** [comment]
Jeśli chodzi o WebAPI to metoda [doGetItemsList](https://allegro.pl/webapi/documentation.php/show/id,1342) pozwala pobrać komplet informacji o ofertach dostępnych na listach ofert - także danego użytkownika. 

Jeśli chodzi o REST API - wkrótce udostępnimy nowy zasób, który pozwoli wyszukiwać i przeglądać oferty na listach. 
Docelowo nie będziemy wspierać, ani rozwijać metody doGetItemsList.

**Comment by FredFlinston** [comment]
Dziękuję Aniu.
O to właśnie mi chodziło.

**Comment by FredFlinston** [comment]
'Docelowo nie będziemy wspierać, ani rozwijać metody doGetItemsList'
Mam rozumieć, że jak dzisiaj napisze program, to niedługo przestanie działać?

**Comment by AniaMalinowska** [comment]
Docelowo REST API Allegro będzie jedynym interfejsem aplikacyjnym, który pozwoli zarządzać ofertą i zamówieniami. Pisaliśmy o tym m.in. [tutaj](https://developer.allegro.pl/news/2018-06-06-Wygaszamy_webapi/). 
Warto już łączyć się z Allegro za pomocą protokołu REST. 
Wkrótce udostępnimy nowy zasób w REST API, który pozwoli wyszukiwać i przeglądać oferty na listach. Docelowo nie będziemy wspierać, ani rozwijać metody doGetItemsList (w pierwszym kroku oznaczymy ją jako [deprecated](https://en.wikipedia.org/wiki/Deprecation#Software_deprecation)) - poinformujemy o tym w stosownym komunikacie.

**Comment by AniaMalinowska** [comment]
@apiallegro Przepraszam, że wcześniej nie odpisałam.

Nie jestem w stanie podać dokładnej daty, pracujemy nad tym.
Gdy już udostępnimy nowy zasób w REST API, poinformujemy o tym w stosownym komunikacie. 
Prawdopodobnie zadzieje się to w najbliższych tygodniach.
