### ISSUE TITLE
Delivery methods

### ISSUE THREAD

**Issue by kislukacs** [allegro/allegro-api#2860]
Hello,

Is there a way to read other users offer's delivery methods in REST?

Thank you!

**Comment by PawelTaberski** [comment]
Hi, you can only check some basic information about delivery in other users offers, by calling GET /offers/listing. More information about this resource you will find [here](https://developer.allegro.pl/en/listing/).

**Comment by kislukacs** [comment]
Hi, thank you for the answer! I saw, WebAPI uses other id for delivery methods as REST. For example _Przesyłka kurierska pobranie_ has in WebAPI id **11** and in REST **845efe05-0c96-47c3-a8cb-aa4699c158ce**. Am I right? Do you have a table with both identificators?

**Comment by PawelTaberski** [comment]
We don't have resource for mapping delivery methods ids. But by call GET on /sale/delivery-methods you can retrieve IDs and names of shipping methods offered by Allegro. More about that you will find [here](https://developer.allegro.pl/en/sale/#shipping-rates).

**Comment by kislukacs** [comment]
Thank you! And what about the WebAPI delivery methods? Where can I find these?

**Comment by PawelTaberski** [comment]
Method to get this data from WebAPI is deactive (https://developer.allegro.pl/en/schedule/). You can get only id of delivery methods from REST API.

**Comment by kislukacs** [comment]
In this case do you have any active methods in WebAPI, what contains the name of delivery methods too?

**Comment by PawelTaberski** [comment]
Shipping ids for WebAPI has been mainly used to listing offers and process orders in WebAPI. Now it is only possible in REST API.

**Comment by kislukacs** [comment]
Thank you!
