### ISSUE TITLE
REST GET /pricing/offer-quotes c.d.

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#2861]
Powraca temat pobierania nadchodzących opłat 
ostatnie informacje jakie znalazłem na GitHub'ie są dość stare więc odświeżam.

Jak pobrać nadchodzące opłaty - np utrzymaniowe - tak jak to widzę w na waszej stronie?
Nie interesuje mnie dłubanina po 20 aukcji tak jak to jest opisane w ww metodzie!
Możliwe czy nie ?

pozdrawiam www factory

**Comment by PawelTaberski** [comment]
Nie wiem, czy dobrze Ciebie zrozumiałem, ale datę naliczenia kolejnej opłaty sprawdzisz zasobem GET /pricing/offer-quotes. Możesz tutaj podać za jednym wywołaniem do 20 ofert. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/charges/#3).

**Comment by wwwfactory** [comment]
Panie Pawle, Zanim napisałem to sprawdziłem stare wątki na GitHub i poczytałem dokumentację. 
Dobrze mnie Pan zrozumiał. 
Ale ja nie chcę odpytywać po 20 aukcji. Chcę zapytać o najbliższe nadchodzące opłaty "utrzymaniowe"  dla mojego konta - tak jak to widzę na Waszej stronie.

Jeżeli nie ma takiej możliwości to zamykamy zgłoszenie.............

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiego zasobu, zapisałem sugestię o wdrożeniu odpowiednika funkcji na froncie.

**Comment by wwwfactory** [comment]
Dziękuje. W starych zgłoszeniach ten wątek się przewijał. Zamykamy.
