### ISSUE TITLE
Qeppo returned an error response in an incorrect format

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#2862]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dostajemy ostatnio sporo błędów jak poniżej:

```
  | [message] => Could not change offer publication status.
  | [status] => FAIL
  | [scheduledAt] => 2020-02-21T21:02:30.454Z
  | [finishedAt] => 2020-02-21T21:02:37.633Z
  | [field] => publication
  | [errors] => Array
  | (
  | [0] => stdClass Object
  | (
  | [code] => QeppoResponseException.IncorrectErrorResponseFormat
  | [message] => Qeppo returned an error response in an incorrect format. Because of this we cannot give you more detail information about the error
  | [details] =>
  | [path] =>
  | [userMessage] =>

```

Przykładowe guidy:
60eca36b-303a-4cea-85b6-a7ed6d97bf39
ce2a8eca-a201-480e-828b-53206fd9eee7

**Comment by PawelTaberski** [comment]
Sprawdziłem oferty i widzę, że wszystkie problematyczne - oprócz 2 zakończonych później są aktywne. Czy problem u Ciebie dalej występuje?

**Comment by dlis2010** [comment]
Witam,

myślę, że problem nie dotyczył oferty. Dostawaliśmy takie komunikaty losowo do różnych ofert. Powtórzenie operacji kończyło się natomiast statusem SUCCESS. 
Brakuje informacji czego problem dotyczył i czy jest to sytuacja normalna z Waszej strony?
Musimy wsiąść odpowiednio pod uwagę powyższe przypadki.

Niestety w dalszym ciągu otrzymujemy niezrozumiałe komunikaty:

1.  Error when update offer price
`[message] => OPERATION_FAILED
  | [status] => FAIL
  | [scheduledAt] => 2020-02-24T07:33:53.613Z
  | [finishedAt] => 2020-02-24T07:41:09.791Z
  | [code] => OFFER_PRICE_CHANGE_ERROR
  | [message] => Error when update offer price.
  | [userMessage] => Error when update offer price.`
Przykładowe guidy: 
5300e012-c847-4a63-909f-9181e1de0779
0c0fe24f-4172-42ea-8822-fc89427a846f
6c0d6e03-de0a-4549-9367-674ac5e8ff03
48c32ed5-4f20-462b-961e-de75ccd97e9e


2. Edycja ceny jednocześnie dla 2 ofert, jedno zadanie kończy się niepowodzeniem (invalid_token), podczas gdy reszta przechodzi bez problemu (nie mieliśmy w tym czasie aktualizacji tokena) 
guid: ede952b2-a85e-4085-9ca3-23d7c4081d86

2 sekundy później na drugim koncie również dochodzi do takiej sytuacji (tym razem 1 na 5 - invalid_token)
guid: 482a8e94-12b5-4d4c-b71e-ec50cc1784a2

Czy powyższe błędy związane są z problemami po Waszej stronie?

**Comment by PrzemyslawLukanowski** [comment]
> Dostawaliśmy takie komunikaty losowo do różnych ofert. Powtórzenie operacji kończyło się natomiast statusem SUCCESS.
> Brakuje informacji czego problem dotyczył i czy jest to sytuacja normalna z Waszej strony?
> Musimy wziąć odpowiednio pod uwagę powyższe przypadki.

Przekazaliśmy problem do odpowiedniego zespołu. Po dalszej analizie będziemy w stanie określić źródło błędu.

> Error when update offer price

Widzę w logach, że przekazujesz kwotę jako wartość float. [Udokumentowany](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) format, zgodny z naszym [guidelinem](https://github.com/allegro/restapi-guideline#price-and-currency), to string. Inny typ może wiązać się z błędami.

> Edycja ceny jednocześnie dla 2 ofert,

Ten temat również przekazałem do weryfikacji, ponieważ dalsze żądania za pomocą tych tokenów kończyły się prawidłową odpowiedzią.

**Comment by dlis2010** [comment]
Witam ponownie,

dzisiaj rano mieliśmy znowu wysyp powyższych błędów.
Nanieśliśmy poprawki odnośnie zamiany ceny na stringa - zobaczymy czy wyeliminuje to problem.

Niestety problemy z tokenem pojawiają się dalej.
Przykład: 049f0ef6-ce5f-47bf-b758-b1b2cf709817

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za kolejny przykład, dodałem go do zgłoszenia.

**Comment by dlis2010** [comment]
@PawelTaberski  @PrzemyslawLukanowski  niestety Panowie, ale problem z zmianą ceny nie ustał po zmianie ceny na stringa.

Podsumowując mamy 3 poprzednio zgłaszane problemy i jeden nowy:

1.  W dalszym ciągu podczas zmiany cen pojawia się:
```
[code] => OFFER_PRICE_CHANGE_ERROR
[message] => Error when update offer price.
```
Przykłady: 
> ba8c3f1f-73ec-40c8-85c9-d32da02189ad
> 56b18023-87e2-460e-9808-ed26981fdd0d
> f1437253-e450-4c4b-8ac6-e6eb0fe8334a

2. Znowu pojawiają się problemy z Qeppo
```
[code] => QeppoResponseException.IncorrectErrorResponseFormat
[message] => Qeppo returned an error response in an incorrect format. Because of this we cannot give you more detail information about the error
```
Przykłady:
> e094060e-7093-4280-87c2-4cc276807cfa
> 74ff62d6-cae2-42fc-9c70-efd0c8e12562
> a32bc500-e6e5-41de-bf5b-756f219da8b2
> w powyższych przykładach są również inne błędy - zdajemy sobie sprawę z ich faktu, proszę zwrócić uwagę tylko na problem z Qeppo

3.  W dalszym ciągu jest problem z autoryzacja aktywnego tokena:
```
[code] => Unauthorized
[message] => invalid_token
```
Przykłady:
> 482a8e94-12b5-4d4c-b71e-ec50cc1784a2
> ede952b2-a85e-4085-9ca3-23d7c4081d86

4. Nowy odkryty przez nas problem, podsumowanie zadania nie zwraca wszystkich danych.
> [id] => 28932787-b7ce-4c0a-beb9-58c3b6029cd7
> [taskCount] => stdClass Object
>    [total] => 20
>    [success] => 16
>    [failed] => 0
natomiast po odpytaniu _28932787-b7ce-4c0a-beb9-58c3b6029cd7/tasks_ dostajemy 20 razy SUCCESS

Kolejne przykłady:
> b5f61dee-39a1-4d4d-a665-d3731ca39e9c
> ab1a19bc-33ae-4142-841b-9e0db774ee0d
> 702bfeb9-939e-44d9-ac3f-2ac0f036d22b

Sporo tego się zebrało, dość inwazyjnie wpływa to na nasze konta.
Bardzo proszę o nadanie odpowiedniego priorytetu.

**Comment by PrzemyslawLukanowski** [comment]
Problem ze zmianą ceny przekazałem do odpowiedniego zespołu. Kolejne zostały już zaadresowane. 
Co do pkt 4 - taka sytuacja może mieć miejsce. Zasób działa asynchronicznie, w momencie kiedy otrzymujesz odpowiedź, nie wszystkie zadania muszą już zostać ukończone. Dlatego, aby otrzymać dokładną odpowiedź, używaj GET sale/{odpowiedni_zasób/{uuid}/tasks.

**Comment by dlis2010** [comment]
Zerknijcie jeszcze raz proszę na punkt 4.

Zadania już dawno ukończone...

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, występuje rozbieżność. Ten problem również przekazuję dalej.

**Comment by dlis2010** [comment]
@PrzemyslawLukanowski , @PawelTaberski 

Witam ponownie Panowie, jak sytuacja?

Błędy związanie z Qeppo oraz OFFER_PRICE_CHANGE_ERROR wydaje się, że ustały.
Niestety w dalszym ciągu dostajemy masę pozostałych błędów w taskach.

problem z invalid_token pojawia się u nas naprawdę bardzo często.
Dziś doszedł kolejny problem:
```
[message] => Could not change offer publication status.
  [status] => FAIL
  [scheduledAt] => 2020-03-10T08:18:51.604Z
  [finishedAt] => 2020-03-10T08:18:52.109Z
  [field] => publication
  [errors] => Array
  (
  )
```
proszę zwrócić uwagę, że tablica errors jest pusta.

Kumulacje takich sytuacji mamy w guidzie d7c12db6-b3df-42df-889b-8b9dbb954e85
Spotkamy tam powyższe błędy, błędy z invalid_token jak i zadania zakończone SUCCESS

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedzialny zespół pracuje nad rozwiązaniem problemów, prośba o cierpliwość.  GUUID d7c12db6-b3df-42df-889b-8b9dbb954e85 także przekazuję do zgłoszenia, wraz z informacją o pustej tablicy errors. W odpowiedzi zadania dla niektórych ofert zauważyłem także komunikat "Given compatibility table is outdated, use the current one." - oznacza to że zmieniła się wartość compatibilityList.id (sekcja Pasuje do),  należy podać aktualne compatibilityList.id przypisane do produktu powiązanego z ofertą.

**Comment by dlis2010** [comment]
Dziękuje za informację, czekamy zatem dalej.

Zdajemy sobie sprawę z problemu "Given compatibility table is outdated, use the current one." - jest on sukcesywnie eliminowany. Za dużo zmian w tych listach i nie nadążamy ;)

Tutaj przyłączę się do sugestii która już tutaj się pojawiła, aby w przypadku aukcji powiązanej z produktem i odświeżeniu przez Was listy dochodziło do automatycznej podmiany listy w aukcji po Waszej stronie.
