### ISSUE TITLE
how to delete a product or modify product's price by use API

### ISSUE THREAD

**Issue by tan133** [allegro/allegro-api#2864]
hi,allegro's engineer
there are some questions i have to ask you

1.  how can I modify my price by use API?
if I have publish a product by use API
after that,I find that I have set a wrong price(set a price $9,but it's real price is $999,for example)
in this case,how can I modify my price by use API?

2.how can I delete product by use API ?
if I have publish a product by use API
after that,I find that Virus break in my country(just like you know,virus-2019 in china)
in this case,I have to delete my product in order to Donate them,
how can I delete them by use API ?

**Comment by pliszka2** [comment]
1. in case when You want to modify price by more than 100% you must do it in loop (up 100% then up 100% and so on) -  https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT

2. https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE

**Comment by tan133** [comment]
question2.               how can I delete a selling product by use API ?

**Comment by tan133** [comment]
thanks for reply
