### ISSUE TITLE
TypeId opcji promowania przedmiotu

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#2867]
Każda opcja promowania ma swoje TypeId. Czy mogę prosić o wypisanie Type'ów?
O ile mi dobrze wiadomo to opcja Wyróżnienia ma TypeId FEA

**Comment by PrzemyslawLukanowski** [comment]
Załączam poniżej:

Oplata za pogrubienie - BLD,
Opłata za stronę kategorii - CPG,
Opłata za oznaczenie Hit -BQH,
Opłata za Okazje dnia - BQD,
Opłata za promowanie na stronie działu - DPG.,
Płatność za pakiet: pogrubienie, podświetlenie - BOH,
Płatność za pakiet: pogrubienie, podświetlenie, wyróżnienie - FHB,
Płatność za pakiet: wyróżnienie, promowanie na stronie działu - FDP.

**Comment by kylovile** [comment]
Dziękuje za odpowiedź. A samo podświetlenie jakie ma Id?

**Comment by PrzemyslawLukanowski** [comment]
> Dziękuje za odpowiedź. A samo podświetlenie jakie ma Id?

To będzie HLI.
