### ISSUE TITLE
REST API różny offer.publication.status przy planowanej dacie rozpoczęcia

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#2868]
Witam,

Mam pytanie dotyczące oferty Allegro dla której ustawimy datę wystawienia aukcji w przyszłości, np. 2020-03-13 20:00:00

Na sandbox oferta otrzymuje status "ACTIVATING"

> GET sale/offers/6206931547? || trace-id:37fc417535a3b8d5
```
    "publication" => Publication {#3205 ▼
      #container: array:6 [▼
        "duration" => null
        "ending_at" => null
        "starting_at" => DateTime {#3206 ▼
          +"date": "2020-03-13 20:00:00.000000"
          +"timezone_type": 2
          +"timezone": "Z"
        }
        "status" => "ACTIVATING"
        "ended_by" => null
        "republish" => false
      ]
    }

```

Natomiast na produkcji oferta otrzymuje status "ACTIVE"

> GET sale/offers/{offerId}? || trace-id:7d3780d3f5577604

```
    "publication" => Publication {#4365 ▼
      #container: array:6 [▼
        "duration" => null
        "ending_at" => null
        "starting_at" => DateTime {#4366 ▼
          +"date": "2019-03-13 21:00:00.000000"
          +"timezone_type": 2
          +"timezone": "Z"
        }
        "status" => "ACTIVE"
        "ended_by" => null
        "republish" => false
      ]
    }
```

Który status jest prawidłowy? Pytam, ponieważ w swojej aplikacji pole "startingAt" przesyłam tylko w zapytaniu PUT jeśli oferta nie ma statusu "ACTIVE". Powoduje to błąd przy edycji "StartingAt cannot be changed.. Nie można zmienić planowanej daty wystawienia."

> PUT sale/offers/{offerId} || trace-id:edaf7c16ebd3945b

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy status to ACTIVATING i otrzymasz go także na produkcji. Twoja oferta cały czas jest w statusie ACTIVE, dlatego jeśli przekażesz jakąkolwiek wartość w polu startingAt, otrzymasz błąd "StartingAt cannot be changed.".

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , czy możesz zerknąć na moją próbę aktualizacji? Nie przekazuję nic w polu publication.startingAt a dalej ten błąd

> PUT sale/offers/{offerId} || trace-id:f340a485ea79ee13
> "publication\":{}

> PUT sale/offers/{offerId} || trace-id:9ecea3650ba25fcf
> "publication":{"status"\"ACTIVE"}

A co do statusu aukcji ACTIVE - to jest OK - przeoczyłem, że już jest 2020 rok ;)

**Comment by PrzemyslawLukanowski** [comment]
Ta oferta miała już ustawioną wartość w polu startingAt na 2019-12-10T22:00:00Z, nie możesz jej nadpisać wartością null - to generuje błąd.

**Comment by Radeq** [comment]
Dziękuję, poprawiłem swoje warunki:

- przy tworzeniu nowego szkicu nie przekazuj czasu rozpoczęcia
- oferta nieaktywna/w trakcie aktywacji - można zmienić czas rozpoczęcia
- oferta aktywna/zakończona - nie można zmienić czasu rozpoczęcia - przekazać obecny
