### ISSUE TITLE
Swagger.json

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#287]
Witam,
W dokumentacji technicznej do REST API widzę, że korzystacie ze Swaggera, czy jest możliwość z Waszej strony udostępnienia pliku json z jego strukturą? 
Ułatwiłoby to zautomatyzowanie generowania klas (kontraktów) do Waszego RESTa :)
Pozdrawiam

**Comment by jakubmaguza** [comment]
https://github.com/allegro/allegro-api/issues/278
