### ISSUE TITLE
Problem z mapowaniem usług dodatkowych

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2870]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Pojawił się dzisiaj u nas problem ze zwracanym przez Was typem dla pola selectedAdditionalServices w zasobie https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET . Wg dokumentacji powinniście zwracać tam zawsze tablicę jednak w odpowiedzi dostajemy wartość null na co nasz kod nie był przygotowany i wywala wyjątek na sklepach produkcyjnych. Bardzo proszę o przywrócenie dotychczasowego działania i trzymanie się jednolitej konwencji w przyszłości

**Comment by kormichu** [comment]
Przykład zamówienia:
```
2020-02-24T11:11:56+01:00 INFO (6): 
-------------------------------------
REQUEST:

GET /order/checkout-forms/f7c6de4d-5671-11ea-be6e-cfb13a12089b HTTP/1.1
Host: api.allegro.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.0.0
Authorization: Bearer (...ciach...)
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

-------------------------------------
RESPONSE:

HTTP/1.1 200 OK
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Server: envoy
Pragma: no-cache
X-frame-options: DENY
Trace-id: 49abcb9e3d3f5c61
Date: Mon, 24 Feb 2020 10:11:56 GMT
X-ratelimit-remaining: 19680
X-content-type-options: nosniff
Content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-length: 5054
X-ratelimit-limit: 20000
X-envoy-upstream-service-time: 21
Connection: close

(...) "lineItems":[{"id":"f7c6de46-5671-11ea-be6e-cfb13a12089b","offer":{"id":"8819872804","name":"BRELOK DO KLUCZY 12 KLUCZE SMART KEY ORGANIZER","external":null},"quantity":1,"originalPrice":{"amount":"10.99","currency":"PLN"},"price":{"amount":"10.99","currency":"PLN"},"selectedAdditionalServices":null,"boughtAt":"2020-02-23T19:24:32.208Z"} (...)
```

**Comment by bacok** [comment]
Potwierdzam, u nas dzieje się to samo. Zamiast pustej tablicy zwracany jest null, pierwszy taki przypadek zanotowaliśmy około godziny 9:44.

**Comment by kormichu** [comment]
U nas podobnie, pierwszy przypadek: 9:42

**Comment by PrzemyslawLukanowski** [comment]
Przywróciliśmy poprzedni format, przepraszamy za związane z tym utrudnienia.
