### ISSUE TITLE
Problem ze zmianą ceny

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#2871]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy zmianie ceny z 33.04 na 83.04 API zwraca błąd.
PUT /sale/offers/offerid
BAD_REQUEST Enter a correct price. Make sure that the specified price does not contain letters. Recommended price format: 0.00.

Nową cenę wysyłam jako float (83.04). Żądanie wykonało się poprawnie jeśli wysłałem cenę jako string. Dotychczas ceny wysyłałem jako float i nie było problemów.  Przestrzegam zasad co do maksymalnej różnicy ceny. Dziwne jest to że akurat problem wystąpił dla różnicy równej 50 i nowej ceny wysłanej jako float. Myślę, że należy to sprawdzić :)

**Comment by PrzemyslawLukanowski** [comment]
[Udokumentowany](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) przez nas typ wartości, zgodny także z [guidelinem](https://github.com/allegro/restapi-guideline#price-and-currency), to string. Jeśli przesyłasz dane w innym formacie, możesz w odpowiedzi otrzymać błędy.
