### ISSUE TITLE
doGetSiteJournal

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2872]
Witam mam pytanie do działania metody doGetSiteJournal.
Widzę, że zwraca następujace eventy:
Typ zdarzenia (start - rozpoczęcie oferty; end - zakończenie oferty; bid - złożenie oferty kupna w licytacji; now - zakup przez Kup Teraz!; change - zmiana w ofercie; cancel_bid - odwołanie oferty kupna w licytacji przez sprzedającego lub administratora).
Interesuje mnie śledzenie opcji now, czyli zakup przedmiotu.
Kiedy dany event jest tworzony? W momencie kiedy ktoś dokona zakupu i zapłaci, czy jeszcze przed płatnościa. Czy jestem w stanie monitorować czy dana oferta KUP TERAZ została odwołana i np. nieopłacona ?
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Event pojawi się w momencie zakupu, jeszcze przed opłaceniem - płatność nie musi zostać zrealizowana. Nie możesz odwołać oferty KUP TERAZ, dlatego nie otrzymasz takiego zdarzenia. Możesz to [zrobić tylko w określonych przypadkach](https://allegro.pl/pomoc/dla-sprzedajacych/zasady-i-regulamin/kiedy-jako-sprzedajacy-moge-odwolac-oferte-kupna-w-trwajacej-licytacji-VEB4ORKEBUB), wtedy otrzymasz event typu cancel_bid.

**Comment by artzie92** [comment]
I rozumiem, że odwołanie jest tylko w ofertach typu: Licytacja. Te bez opcji licytacji czyli tylko Kup teraz, eventu cancel_bid nie dotycza?

**Comment by PrzemyslawLukanowski** [comment]
@artzie92 Dokładnie tak.

**Comment by artzie92** [comment]
@PrzemyslawLukanowski  Ok dzięki, a czy w metodzie doGetBidItem2 dla ofert kup teraz, od razu po zakupie status zakupu (-1 - oferta odwołana, 0 - oferta nie zakończona sprzedażą, 1 - oferta zakończona sprzedażą) jest ustawiany od razu na 1? Czy też dopiero po płatności. 
Chodzi mi o scenariusz kiedy dostaje event now i strzelam do getbiditem2 to status tego rekordu jest na 1? 

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
@artzie92 Ponownie potwierdzam - jeżeli użytkownik zakupi przedmiot przez KUP TERAZ, ale nie dokończy płatności, dla doGetBidItem2 w polu **status zakupu** zwrócimy 1.

**Comment by artzie92** [comment]
Ok świetnie dzięki za dokładne wytłumaczenie mechanizmu działania. 
W ramach sugestii miejcie świadomość, że doGetBidItem2 używa ogromna ilość aplikacji, które służa do analizy danych. Nie widzę jej odpowiednika w harmonogramie do rest api. Jeżeli jej nie planujecie to przy event logu publicznym zagwarantujcie informację o tym ile produktów zakupiono podczas transakcji. W przeciwnym razie wiele systemów nie ma prawa bytu :)

**Comment by artzie92** [comment]
Czy jeżeli ktoś kupi np 2 sztuki to event z typem 'now' jest wywoływany raz czy tyle razy ile zakupiono sztuk? Dzisiaj dla oferty za id: 8990882316. Przyszło do mnie 90 eventów, a widzę, że jedna osoba kupowała ten przedmiot.

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli kupujący za jednym razem zakupi 2 sztuki (czyli FOD wypełni tylko raz), otrzymasz tylko jedno zdarzenie. W Twoim przypadku każdy zakup miał miejsce osobno - czyli kupujący zakupił przedmiot, zapłacił za niego, po czym wracał na stronę przedmiotu i wykonywał tę czynność x razy. Dlatego otrzymałeś taką liczbę eventów.

**Comment by artzie92** [comment]
Ok dzięki
