### ISSUE TITLE
Pobranie kodu autoryzującego

### ISSUE THREAD

**Issue by Elrcx** [allegro/allegro-api#2874]
Jak automatycznie pobrać kod autoryzujący do zmian ofert na koncie do aplikacji?

Próbuje autoryzować aplikację do wykonywania zmian na aukcjach użytkownika jednak mam problem z automatyzacją tej operacji.
W tej chwili po kliknięciu loginu w domyślnej przeglądarce wyskakuje strona:
"https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=" + CLIENTID + "&redirect_uri=http://localhost:8000"
Tam klikam że zgadzam się i w adresie dostaje kod który muszę w ciągu 10 sekund przepisać do aplikacji. Ok, działa.

Ale chciałbym ten ostatni krok zautomatyzować - jak to zrobić? Tak żeby aplikacja odpytywała coś i automatycznie wiedziała że klient się zgodził i pobrała sobie kod.
Dodam że potrzebuje tego w C# przez RestSharp, ale wystarczy mi ogólny przykład a już sam sobie to przetłumaczę na C#.

Zdaje sobie że pytanie jest podstawowe (sam nie jestem zaawansowany w tych sprawach), jednak nawet po przeczytaniu poradników nie mogę tego ogarnąć.

**Comment by Onixarts** [comment]
Odpal stronę nie w domyślnej przeglądarce tylko w kontrolce HTML w swojej aplikacji i zaczaj się na zdarzenie załadowania nowej strony. Wtedy sobie odczytasz adres i wyciągniesz kod, który następnie wyślesz do API.
A jeśli ktoś zna sposób na zrobienie tego z zewnętrznej przeglądarki bez angażowania własnego webserwisu to chętnie bym się zapoznał ;).

**Comment by PrzemyslawLukanowski** [comment]
Taką możliwość daje parametr redirect_uri. Jeśli posiadasz aplikację z adresem przekierowania np. `http://mojaaplikacja.pl/exchange` , to po wykonaniu przekierowania przez przeglądarkę, użytkownik dostanie się na `mojaaplikacja.pl/exchange?code=xxx`. Twój serwer musiałby nasłuchiwać pod /exchange i zczytywać query-param `code`.

**Comment by Elrcx** [comment]
Dzięki, niestety nie mam serwera więc szukałem innego rozwiązania (ale wiedza przyda się na przyszłość).

Ostatecznie skorzystałem z podpowiedzi @Onixarts  chociaż winformowy WebBrowser nie potrafił niczego wyświetlić prawidłowo. Na szczęście po przełączeniu się na CefSharp wszystko poszło bez problemu.

**Comment by Onixarts** [comment]
Webbrowser domyślnie działa chyba w trybie IE7, można to przestawić w rejestrze Windows, aby działał jako IE11. Z Cefem będzie mniej problemów :).
