### ISSUE TITLE
Ustalanie domyślnych wartości wymaganych parametrów oferty

### ISSUE THREAD

**Issue by DaveCocieto** [allegro/allegro-api#2875]
Cześć,
pobieram wymagane parametry kategorii przez REST API '**/sale/categories/{categoryId}/parameters**', otrzymuję listę wartości.
Chciałbym zapytać, jak ustalić która wartość z wymaganych parametrów jest domyślna?
Domyślną wartość mam na myśli wartości typu: 'inny', 'inna', 'brak informacji'.
Czy jest jakaś zasada typu, że domyślna wartość ląduje na końcu listy?
Jeżeli nie ma na to reguły, czy jest możliwość uzyskania pełnej listy wartości domyślnych wymaganych parametrów?
Pozdrawiam, Dawid

**Comment by PrzemyslawLukanowski** [comment]
Wartości, o których wspominasz nie traktujemy jako domyślne, ale jako jedne z dostępnych. W przypadku w kategorii, np. 254779 dla parametru 3766 "inny wzór" jest wartością przedostatnią, ale prócz tego jest jeszcze "bez wzoru", jako ostatnia. Inny przykład - w kategorii 20274, wartość "Brak" dla parametru jest pierwsza na liście, "Inne" ostatnia. Wartości typu "inne", itp. trafiają na koniec listy, jednak nie jest to udokumentowana reguła, co oznacza, że w przyszłości może się to zmienić.
Prócz wspomnianego przez Ciebie zasobu nie ma innej możliwości, aby pobrać te wartości.

**Comment by PrzemyslawLukanowski** [comment]
@DaveCocieto Spójrz na naszego [newsa](https://github.com/allegro/allegro-api/issues/2968). W polu ambiguousValueId znajdziesz informację o interesującej Cię wartości parametru.

**Comment by DaveCocieto** [comment]
@PrzemyslawLukanowski dzięki za informację, przyda się na pewno.
