### ISSUE TITLE
Błąd podczas aktywacji oferty

### ISSUE THREAD

**Issue by ponowemu** [allegro/allegro-api#2876]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas próby aktywacji oferty dostaję błąd: 
You cannot activate an invalid offer.
Jednocześnie pole details jest nullem, path tak samo, a code: UnknownError.
Oferta bez problemu daje się aktywować przez UI.

Trace ID: 2948ae0f-9d85-4ea8-aa1f-b6dce89c22bf

**Comment by PrzemyslawLukanowski** [comment]
Na podstawie logów widzę, że był problem z parametrem 227345. Podawałeś go w strukturze oferty, jednak nie określałeś dla niego żadnej wartości, jak poniżej:

```
{
	"id": "227345",
	"valuesIds": [],
	"values": [],
	"rangeValue": null
}
```

Dla tego odpowiedź w sekcji validation.errors dla zapytania GET /sale/offers/{offerId} brzmiała:

```
	"errors": [{
		"code": "VALIDATION_ERROR",
		"message": "You can only assign string parameter by value for 227345.",
		"details": "",
		"path": "",
		"userMessage": "You can only assign string parameter by value for 227345."
	}, {
		"code": "VALIDATION_ERROR",
		"message": "Empty parameter: Numer katalogowy oryginału (227345).",
		"details": "",
		"path": "",
		"userMessage": "Empty parameter: Numer katalogowy oryginału (227345)."
	}], 
```
