### ISSUE TITLE
Metoda doGetBidItem2

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2877]
Występuje problem:
 - [X ] z metodą WebAPI
 - [ X] ze środowiskiem produkcyjnym

Witam,
Pobierajac transakcje dla jednej z oferty zauważyłem dziwna rzecz. W jednej z transakcji przychodzi ilość 51. Co raczej jest niemożliwe, tym bardziej, że na Waszej stronie również nie widać aby taki zakup został dokonany.
Request:
Dla oferty z id: 8718356829

Response
![image](https://user-images.githubusercontent.com/16481836/75246045-41158e80-57cf-11ea-96c4-e2d21b9b058f.png)

Moje struktury:
![image](https://user-images.githubusercontent.com/16481836/75246141-6bffe280-57cf-11ea-8141-bd9a224f7a50.png)

Jest jeszcze kilka innych ofert. Gdzie widzę podobne zachowanie.

**Comment by PrzemyslawLukanowski** [comment]
25-02-2020 to data ostatniego zakupu przez wskazanego usera, a te miały miejsce już parę miesięcy wcześniej. 51 jest sumą wszystkich przedmiotów, od pierwszego zakupu.
