### ISSUE TITLE
Zasób /sale/offers

### ISSUE THREAD

**Issue by mw3e21a** [allegro/allegro-api#2878]
Zasób /sale/offers ( lista ofert ) zwraca oferty ze starym opisem, czy jest możliwość przekazania w parametrach żądania informację, że chcemy uzyskać tylko oferty z nowym opisem, lub jest jakaś informacja po której możemy rozpoznać, która oferta ma stary opis? Bo wyciągnięcie jakichkolwiek szczegółów oferty ze starym opisem poprzez zasób /sale/offers/{{offer.id}} kończy się błędem 404.

**Comment by PrzemyslawLukanowski** [comment]
Co masz na myśli przez "stary opis"? Czy możesz podać konkretny przykład sytuacji, o której napisałeś? Status 404 zwracamy dla ofert, które zostały zarchiwizowane lub usunięte (szkice).

**Comment by mw3e21a** [comment]
Rzeczywiście oferta była zarchiwizowana.
Dziękuję za wytłumaczenie.
