### ISSUE TITLE
W tej chwili nie można skorzystać z Allegro API! Proszę spróbować później!

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#2879]
Wywołanie doGetItemsInfo na id 8982898871 kończy się błędem ERR_WEBAPI_NOT_AVAIL - W tej chwili nie można skorzystać z Allegro API! Proszę spróbować później!

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to przed chwilą na wskazanej ofercie i udało mi się otrzymać prawidłową odpowiedź. W logach metoda również zwraca poprawne dane. Jeżeli w dalszym ciągu otrzymujesz błąd, prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu dopisz GitHub #2879.

**Comment by nxgo** [comment]
@PrzemyslawLukanowski 
Mam dokładnie ten sam błąd przy doGetItemsInfo. Moja aplikacja od wczoraj sieje takimi błędami, nie wiem czy się udało choć raz tą metodę użyć. Za każdym razem przy próbie wywołania tworzę nową sesję ale to też nic nie daje. 

Czy dla tej metody są jakieś dodatkowe limity, wymagania? 
Z tego co wiem w rest api nie ma jeszcze odpowiednika dla publicznych ofert? Czy jest jakiś sposób na obejście tego problemu?

**Comment by PrzemyslawLukanowski** [comment]
@nxgo Wczoraj udało mi się odtworzyć ten problem, przekazałem go już do odpowiedniego zespołu. Czy w Twoim przypadku błąd występuje dla ofert w wybranych kategoriach czy wszystkich? Czy, jeżeli dla parametru getAttribs ustawisz 0, otrzymujesz prawidłową odpowiedź?

**Comment by nxgo** [comment]
Witam,
Na pewno ustawiam getAttribs na 1, spróbuję następnym razem jak się wywali spróbować z 0, czy przejdzie. Niestety nie wiem dla jakich kategorii problem się objawia, gdyż używam różnych kategorii. a przy odpytywaniu o 10 aukcji (bo taki jest limit) nie jestem w stanie łatwo sprawdzić która to aukcja. Jeśli jest to bardzo potrzebne to mogę spróbować zapisać 10 aukcji problematycznych i jedna za drugą je sprawdzać.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przykładowe logi przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), dopisz w wiadomościGitHub #2879. Dołączę je do zgłoszenia.

**Comment by AdamskyGt** [comment]
Witam, od wczoraj mam podobny problem. 
doGetItemsInfo zwraca ERR_WEBAPI_NOT_AVAIL dla wielu roznych itemid z roznych kategorii. W przyblizeniu problem sprawia jedna aukcja na kilka tysiecy. Np 8519773721

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykład, pracujemy nad rozwiązaniem problemu.

**Comment by smarthub-il** [comment]
Problem występuje nadal.
Kilka problemowych aukcji:
9002673506
8973761916
8373965737
8554135591
8742710899
8373965960
Wszystkie pochodzą z kategorii Allegro -> Elektronika -> RTV i AGD -> Zasilanie,
8519773721 <- ta również

**Comment by PrzemyslawLukanowski** [comment]
Dodałem podane oferty do zgłoszenia.

**Comment by smarthub-il** [comment]
Czy wiadomo już coś w tym temacie? Kiedy można spodziewać się poprawnego działania dla wszystkich ofert? Informacje będą pomocne w podjęciu decyzji.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu, na tę chwilę nie mogę wskazać przybliżonego terminu naprawy. Po wyeliminowaniu błędu poinformuję o tym w wątku.

**Comment by betonmix** [comment]
Minęło już kolejne 5 dni a błąd nadal występuje, czy można wiedzieć kiedy zostanie on usunięty ?

**Comment by smarthub-il** [comment]
U mnie błędy przestały pojawiać się w nocy 9.03. Informacje o wszystkich ofertach wypisanych powyżej zostały pobrane.
Pytanie: czy problem może powracać, czy został definitywnie rozwiązany?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, problem został dzisiaj rozwiązany, metoda działa już prawidłowo.
