### ISSUE TITLE
WebAPI vs REST API.

### ISSUE THREAD

**Issue by FredFlinston** [allegro/allegro-api#288]
Witajcie.

Czy to prawda, że programy napisane w oparciu o wsdl przestaną działać?

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
To jest kolejny SKANDAL - ponieważ jeszcze całkiem niedawno, pracownicy korporacji Amazollegro, zarzekali się w oficjalnych wypowiedziach i komunikatach, że WebAPI pozostanie PODSTAWOWYM interfejsem komunikacji oraz dostępu do danych serwisu. Allegro nie jest już polskim serwisem, teraz będzie tylko gorzej i gorzej... Nadchodzi KorpoSYF !!

**Comment by AniaMalinowska** [comment]
[Tutaj](https://developer.allegro.pl/news/2018-06-06-Wygaszamy_webapi/) zamieściliśmy informacje na ten temat.

**Comment by kfijalko** [comment]
:) nie wiem czy kiedykolwiek było tak, że można napisac "soft' i odcinać kupony.
Od roku ciagle coś modyfikuję w interfejsie z allegro, a jeszcze nie przeszedłem całkowicie na REST'a.
Czekam na jak najbardziej ustabilizowaną wersję.
Allegro długo stało na SOAP'ie, w którym niewiele się zmieniało i teraz za to "pokutuje". Konkurencja mocno rozwija usługi dla kupujących/sprzedających i allegro musi gonić, choć pewnie chciało by mieć pozycję lidera technologicznego. Zapewne po pełnym wdrożeniu REST'a (zarzędzanie ofertami, promocjami (w tym monety), warianty, zestawy, zarządzanie sprzedażą, dyskusajmi, zwrotami, wysyłkami) będą na równi z konkurencją. Tylko że w tym czasie konkurencja już wdroży coś "nowego" i dalej ...
Myślę, że najbliższy rok bedzie bardzo intensywny pod względem programowania.
Taki tam wpis zainspirowany @FredFlinston "I tak co 6 lat?".

**Comment by kfijalko** [comment]
@KoniecWebAPI-KoniecAllegro niepotrzebnie się emocjonujesz, a już na pewno nie powinieneś sobie pozwalać na osobiste wycieczki.

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
Ale o co chodzi - napisałem przecież "... za bardzo", więc rób Pan sobie jak chcesz ;-)
