### ISSUE TITLE
Zablokowane konto w allegro sandbox

### ISSUE THREAD

**Issue by arturito-93** [allegro/allegro-api#2880]
Czy można prosić o odblokowanie konta w allegro sandbox? Nazwa użytkownika to **akraw93env**, nie mogę wystawić żadnej oferty. Komunikat aplikacji :

> Podczas wznowienia oferty wystąpiły błędy
> Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).

[REST API](https://developer.allegro.pl/)y
[Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/auth/)
[Jak wystawić ofertę](https://developer.allegro.pl/sale/)
[Jak zarządzać ofertami](https://developer.allegro.pl/my_offers/)
[Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/)
[Jak zarządzać zestawami i rabatami](https://developer.allegro.pl/offer_bundles/)
[Jak utworzyć ofertę wielowariantową](https://developer.allegro.pl/multi_variant_offers/)
[WebAPI](https://allegro.pl/webapi)
-->

**Comment by PrzemyslawLukanowski** [comment]
Wejdź proszę w zakładkę [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i wybierz "Zapłać". Po tej czynności Twoje konto powinno zostać odblokowane.

**Comment by arturito-93** [comment]
Zadzaiałało, dziękuję

**Comment by slawomir-zaziablo** [comment]
Witam, ja niestety nie mogę dokonać płatności w Sandbox i widzę informację "Wystąpił błąd". Mogę prosić o sprawdzenie? Login slawek1151 - Dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
@slawomir-zaziablo otrzymaliśmy już podobne zgłoszenie w wątku #3959 i #3960, weryfikujemy to.
