### ISSUE TITLE
Błąd http 400 odświeżenia tokenu /auth/oauth/token?grant_type=refresh_token Invalid refresh token

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2881]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] z logowaniem lub autoryzacją

:beetle: **Opis**
Dzień dobry przy próbie odświeżenia tokenów serwer zwraca wyjątek http 400. Refresh token jest ważny do kwietnia 04/19/2020 @ 4:59am (UTC). Pełny request i response przesłałem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

```
REQUEST 2020-02-26 04:55:12.4280060
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=#&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-02-26 04:55:12.4748822 Duration: 46,8762ms
{
  "Data": null,
  "Validation": {
    "Errors": null,
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request."
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": "{\"error\":\"invalid_grant\",\"error_description\":\"Invalid refresh token: #\"}"
}
```

**Comment by kfijalko** [comment]
refresh token jest jednorazowy.

**Comment by alekskuc** [comment]
> refresh token jest jednorazowy.

Tak, wiem o tym, dlatego po każdym odświeżeniu w/w metodą aktualizuje obydwa tokeny w bazie danych. Z jakiegoś powodu ten refresh token nie zadziałał w ogóle.

**Comment by kfijalko** [comment]
1- inny skrypt go użył 
2- obecny skrypt puścił dodatkowe odświeżenie tokena Bez zapisania w bazie
3- coś innego, Allegro może sprawdzić historie odświeżania tokena

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Ten refresh_token musiał być wykorzystany wcześniej. Widzę w logach, że status 400 zwracaliśmy już 13.02.2020.

**Comment by alekskuc** [comment]
@PrzemyslawLukanowski a jest w logach informacja kiedy ten refresh token zadziałał prawidłowo i zwrócił nową parę token i token refresh?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to - ostatnie logi, jakimi dysponujemy zwracają już informację o invalid_refresh_token. Nie mamy możliwości pobrania starszych danych.

**Comment by alekskuc** [comment]
Dzień dobry, problem występował u mnie w monecie jak wiele serwerów na raz próbowało odświeżyć token, a do bazy zapisał jeden który miał http 200. Pozostałe jednorazowo zwracały http 400 dla wielu baz. 
Dziękuję za sprawdzenie.
