### ISSUE TITLE
422 error when i need to add image to the description

### ISSUE THREAD

**Issue by sepehrbg** [allegro/allegro-api#2882]
Hello guys
I am have stuck on a problem, anyone has any idea how i can get ride of error 422?
here is my json code which i am trying to pass it to post method to make new draft offer:

"{\"additionalServices\":{\"id\":\"123456\"},\"afterSalesServices\":{\"warranty\":{\"id\":\"09f0b4cc-7880-11e9-8f9e-2a86e4085a59\"}},\"category\":{\"id\":\"25959\"},\"description\":{\"sections\":[{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>Tekstowy opis przedmiotu</p>\"},{\"type\":\"IMAGE\",\"url\":\"https://a.allegroimg.com/original/1186f5/eb3a374345b08ac98c50710bb6ac\"}]},{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>Tekstowy opis przedmiotu</p>\"}]}]},\"images\":[{\"url\":\"https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80.jpg\"},{\"url\":\"https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80.jpg\"}],\"location\":{\"city\":\"Poznań\",\"countryCode\":\"PL\",\"postCode\":\"60-166\",\"province\":\"WIELKOPOLSKIE\"},\"name\":\"białe buty sportowe\",\"parameters\":[{\"id\":\"11323\",\"valuesIds\":[\"11323_1\"]},{\"id\":\"127789\",\"valuesIds\":[\"127789_1\"]},{\"id\":\"127768\",\"valuesIds\":[\"127768_1\"]},{\"id\":\"5389\",\"values\":[\"12\"]},{\"id\":\"5390\",\"valuesIds\":[\"5390_6\"]},{\"id\":\"451\",\"valuesIds\":[\"451_1\"]}],\"payments\":{\"invoice\":\"VAT\"},\"publication\":{\"republish\":true},\"sellingMode\":{\"format\":\"BUY_NOW\",\"price\":{\"amount\":\"100000\",\"currency\":\"PLN\"}},\"stock\":{\"available\":10}}"

please note that, when i clear the item which is containing image in the **description** part (type=IMAGE, url=blob...) i am getting no errors but when i add the item with image it is throwing 422 error. so i am 100% sure that the problem is in this line. i am trying to do it exactly like whatever in documentation. please help me with this problem, cheers.

**Comment by PrzemyslawLukanowski** [comment]
In the images array provide the same value as in description.sections.items.url -> https://a.allegroimg.com/original/1186f5/eb3a374345b08ac98c50710bb6ac. You should upload all images via [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST) and in the next step use the address you received. You can find more information in [our guide](https://developer.allegro.pl/en/sale/#step-3-images).

**Comment by sepehrbg** [comment]
Thank you for your reply, unfortunately even after adding this url in images array, it gives the same error (422)

"{\"additionalServices\":{\"id\":\"123456\"},\"afterSalesServices\":{\"warranty\":{\"id\":\"09f0b4cc-7880-11e9-8f9e-2a86e4085a59\"}},\"category\":{\"id\":\"25959\"},\"description\":{\"sections\":[{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>Tekstowy opis przedmiotu</p>\"},{\"type\":\"IMAGE\",\"url\":\"https://a.allegroimg.com/original/1186f5/eb3a374345b08ac98c50710bb6ac\"}]},{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>Tekstowy opis przedmiotu</p>\"}]}]},\"images\":[{\"url\":\"https://a.allegroimg.com/original/1186f5/eb3a374345b08ac98c50710bb6ac\"}],\"location\":{\"city\":\"Poznań\",\"countryCode\":\"PL\",\"postCode\":\"60-166\",\"province\":\"WIELKOPOLSKIE\"},\"name\":\"białe buty sportowe\",\"parameters\":[{\"id\":\"11323\",\"valuesIds\":[\"11323_1\"]},{\"id\":\"127789\",\"valuesIds\":[\"127789_1\"]},{\"id\":\"127768\",\"valuesIds\":[\"127768_1\"]},{\"id\":\"5389\",\"values\":[\"12\"]},{\"id\":\"5390\",\"valuesIds\":[\"5390_6\"]},{\"id\":\"451\",\"valuesIds\":[\"451_1\"]}],\"payments\":{\"invoice\":\"VAT\"},\"publication\":{\"republish\":true},\"sellingMode\":{\"format\":\"BUY_NOW\",\"price\":{\"amount\":\"100000\",\"currency\":\"PLN\"}},\"stock\":{\"available\":10}}"

**Comment by PrzemyslawLukanowski** [comment]
There are two issues:
1. In description  -> "Tekstowy opis przedmiotu" - put this text into one of the html tags, eg. < p >Example< /p > (without whitespace)
2.  Images from address https://a.allegroimg.com/original/1186f5/eb3a374345b08ac98c50710bb6ac is not anymore on our server, try to use this one instead - https://a.allegroimg.com/original/119d4b/f54104b14567a83b5a3066327aed
