### ISSUE TITLE
Formularz zakupowy bez podanego pola phoneNumber w adresie przesyłki

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#2883]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Klient wyklikał zakup z metodą wysyłki:
**Allegro Paczkomaty 24/7 InPost**

Formularz nie zawiera informacji o telefonie dla dostawy.
{'id': 'e6427212-58c4-11ea-baeb-87340f5b5d8d', 'messageToSeller': None, 'buyer': {'id': '###', 'email': 'jht97euqju+25550f085@allegromail.pl', 'login': '###', 'firstName': '###', 'lastName': '###', 'companyName': None, 'guest': False, 'personalIdentity': None, 'phoneNumber': None, 'address': {'street': '###', 'city': '###', 'postCode': '###', 'countryCode': 'PL'}}, 'payment': {'id': 'bbdb45e2-58c6-11ea-815e-63bd711e799c', 'type': 'ONLINE', 'provider': 'PAYU', 'finishedAt': '2020-02-26T18:37:19.696Z', 'paidAmount': {'amount': '62.48', 'currency': 'PLN'}}, 'status': 'READY_FOR_PROCESSING', 'fulfillment': {'status': 'NEW', 'shipmentSummary': {'lineItemsSent': 'NONE'}}, 'delivery': {'address': {'firstName': '###', 'lastName': '###', 'street': '###', 'city': '###', 'zipCode': '###', 'countryCode': 'PL', 'companyName': None, '**phoneNumber**': **None**}, 'method': {'id': '2488f7b7-5d1c-4d65-b85c-4cbcf253fd93', 'name': 'Allegro Paczkomaty 24/7 InPost'}, 'pickupPoint': {'id': 'TUR07N', 'name': 'Paczkomat TUR07N', 'description': 'Przy Aptece Alba', 'address': {'street': 'Konińska 24', 'zipCode': '62-700', 'city': 'Turek'}}, 'cost': {'amount': '8.99', 'currency': 'PLN'}, 'smart': False, 'time': {'guaranteed': None}, 'calculatedNumberOfPackages': 1}, 'invoice': {'required': False, 'address': None}, 'lineItems': [{'id': 'e6427210-58c4-11ea-baeb-87340f5b5d8d', 'offer': {'id': '###', 'name': '###', 'external': None}, 'quantity': 1, 'originalPrice': {'amount': '53.49', 'currency': 'PLN'}, 'price': {'amount': '53.49', 'currency': 'PLN'}, 'selectedAdditionalServices': [], 'boughtAt': '2020-02-26T18:24:27.637Z'}], 'surcharges': [], 'discounts': [], 'summary': {'totalToPay': {'amount': '62.48', 'currency': 'PLN'}}, 'updatedAt': '2020-02-26T18:37:19.696Z'}

Wiadomo że Inpost nie przyjmie formularza bez telefonu:
2020-02-26 21:56:58.298276 :: InpostDeliveryNoteHandler: error: transaction failed with status: **400**
2020-02-26 21:56:58.298546 :: InpostDeliveryNoteHandler: error: error status: There are some validation errors. Check details object for more info.
{'status': 400, 'error': 'validation_failed', 'message': '**There are some validation errors. Check details object for more info.**', 'details': {'receiver': [{'phone': ['required', 'invalid']}]}}

**Comment by PrzemyslawLukanowski** [comment]
Podobny przypadek opisaliśmy w zgłoszeniu #2831. Użytkownik zarejestrował swoje konto w czasie, kiedy starsza wersja aplikacji mobilnej pozwoliła zapisać dane bez uzupełnionego numeru telefonu. Sam zakup również odbył się przez aplikację mobilną.

**Comment by PiotrLaszczyk** [comment]
No coś się wam rozszczeliniło bo inny przypadek co wpadł na bęben to:

Dane dostawy: **Pocztex Kurier48**, 12,99 zł, 1 przesyłka

mohammad alo***
18-21 Pulborough Way
*** *** Hounslow GB
0-800-520-****

Listonosze może i na skasach ale czy doręczą, śmiem wątpić ;)

(Numer zamówienia: b5953428-58e9-11ea-9a3d-4f2c9cefb2f4)
