### ISSUE TITLE
Przyjazna nazwa dla payment.id

### ISSUE THREAD

**Issue by marcinek1312** [allegro/allegro-api#2884]
Witam

w jaki sposób można pobrać słownik nazw sposobów płatności tak żebym wiedział że np. payment.id=5a51bfe2-4e3d-11ea-a192-db8aafa023f4 odpowiada zapłata gotówką przy odbiorze itp.? oczywiście chodzi o REST API.

**Comment by PrzemyslawLukanowski** [comment]
Taką informację zwracamy w polu payment.type, dostępne wartości to “ONLINE”, "CASH_ON_DELIVERY" lub "SPLIT_PAYMENT".
