### ISSUE TITLE
BundleAlreadyExistsException

### ISSUE THREAD

**Issue by bodzimierz** [allegro/allegro-api#2885]
Przy POST https://api.allegro.pl/sale/loyalty/promotions otrzymuję BundleAlreadyExistsException. Czy jest szansa dodać promotionId do odpowiedzi? Chciałbym usunąć promocję jeżeli taka istnieje (z takim zestawem aukcji) i dodać nową. Tyle że nie mogę wykonać https://api.allegro.pl/sale/loyalty/promotions/{promotionId} ponieważ w tym wypadku nie znam promotionId.

**Comment by PrzemyslawLukanowski** [comment]
Możesz użyc zasobu [GET /sale/loyalty/promotions](https://developer.allegro.pl/documentation/#operation/listSellerPromotionsUsingGET_1), gdzie jako query parametr, prócz wymaganego user.id, przekaż także offer.id={offer.id}. Możesz skorzystać także z filtru promotionType, aby zawęzić wyniki.  W odpowiedzi, w polu promotions.id, otrzymasz interesującą Cię informację. Czy takie rozwiazanie jest dla Ciebie wystarczające?
