### ISSUE TITLE
Problem z powracającym task-publication-command

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#2886]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mamy problem z powtarzającym się taskiem w procesie synchronizacji w naszym module, oto kilka informacji:

```
[offer] => stdClass Object
        (
            [id] => 7664881902
        )

    [message] => 
    [status] => SUCCESS
    [scheduledAt] => 2020-02-27T09:06:03.759Z
    [finishedAt] => 2020-02-27T09:06:04.321Z
    [field] => publication
    [errors] => Array
        (
        )
```

otrzymujemy `SUCCESS` więc czyścimy task po naszej stronie, niestety on nadal do nas wraca

traceid: `6cf18c08d162bf56`

**Comment by PrzemyslawLukanowski** [comment]
Oferta ze zgłoszenia została zakończona w dniu 10.02.2020.  Od 2020-02-26 17:54:26 zarejestrowaliśmy 640 żądań zakończenia oferty , która jest cały czas w statusie ENDED - dlatego kończy się to odpowiedzią SUCCESS. Prośba o weryfikację mechanizmu po Państwa stronie, przykładowe uuidy:

4bd80a0b-719e-4aa1-abfa-4259cfe57bda
f4a55494-7127-43d6-b1d0-7afb270bf8e1
f80a5f36-39f9-417d-adcb-ba364aa79e01
