### ISSUE TITLE
Zamówienia "za pobraniem" dostają status płatności "nieudana"

### ISSUE THREAD

**Issue by maczking** [allegro/allegro-api#2887]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy dokonywaniu zamówień w sandboxie na potzreby testów i wyborze opcji wysyłki pobraniowej, proces płatności za takie zamówienie kończy się statusem "nieudana". Blokuje to też pobranie po API danych dostawy dla takich zamówień.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to dla wybranych pobraniowych metod dostawy i za każdym razem płatność przechodzi prawidłowo. Jako sprzedający mam informację w polu payment.finishedAt w odpowiedzi zasobu GET /order/checkout-forms/{id}. Czy w takim razie problem dalej występuje? Jeśli tak, podaj proszę przykładowy numer zamówienia.
