### ISSUE TITLE
Problem z otrzymaniem tokenu

### ISSUE THREAD

**Issue by MacDon99** [allegro/allegro-api#2888]
Dzień dobry,
korzystając z allegro sandbox nie było żadnego problemu, lecz gdy chciałem pobrać token już ze strony allegro.pl pokazuje mi error "missing grant type"
Zalogowany jestem, client_id i client_secret aplikacji podałem.

Jak zdobyć ten token?

**Comment by PrzemyslawLukanowski** [comment]
missing grant type wskazuje na to, że nie przekazujesz tego parametru w requescie. Poniżej znajdziesz przykład prawidłowego żądania:

`https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={redirect_uri}`

Jeżeli mimo to, nadal otrzymujesz błąd, prześlij przykładowy request w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu dopisz GitHub #2888.

**Comment by MacDon99** [comment]
a skąd mogę wziąć  "code" oraz "redirect_uri"?

**Comment by PrzemyslawLukanowski** [comment]
Zapoznaj się z [naszym poradnikiem](https://developer.allegro.pl/auth/#app). Opisaliśmy tam wszystkie kroki procesu autoryzacji. Redirect_uri jest to adres przekierowania, na który wyślemy 10 sekundowy kod, musi być zgodny z adresem określonym dla aplikacji na stronie https://apps.developer.allegro.pl/. Code otrzymasz za pomocą żądania:

`https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={clinet_id}&redirect_uri={redirect_uri}`

**Comment by MacDon99** [comment]
Kod udało mi się uzyskać, lecz z tokenem wciąż jest problem

https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=tSElBjX6lfgzAM7hiRHlno7RMr6H5ULH&redirect_uri=http://www.google.com

odpowiedź: "Unauthorized grant type: authorization_code"

**Comment by PrzemyslawLukanowski** [comment]
Czy to na pewno dokładna treść błędu? Widzę w logach, że używasz tego samego code w różnym przedziale czasowym. Pamiętaj, że kod jest ważny tylko 10 sekund, potem musisz wygenerować kolejny.

**Comment by PrzemyslawLukanowski** [comment]
Czy to na pewno dokładna treść błędu? Widzę w logach, że używasz tego samego code w różnym przedziale czasowym. Pamiętaj, że kod jest ważny tylko 10 sekund, potem musisz wygenerować kolejny.
