### ISSUE TITLE
Problem z odświeżaniem tokenów

### ISSUE THREAD

**Issue by yd6d7hhds** [allegro/allegro-api#2889]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
curl -X POST -H 'Authorization: Basic xxx' 'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=xxx' -v
* About to connect() to allegro.pl port 443 (#0)
*   Trying 5.134.213.82...
* Connected to allegro.pl (5.134.213.82) port 443 (#0)

> POST /auth/oauth/token?grant_type=refresh_token&refresh_token=xxx HTTP/1.1
> User-Agent: curl/7.29.0
> Host: allegro.pl
> Accept: */*
> Authorization: Basic xxx
>
< HTTP/1.1 400 Bad Request
< Date: Fri, 28 Feb 2020 02:36:51 GMT
< Transfer-Encoding: chunked
< Set-Cookie: trace_id=d99551d28f506d32;Path=/;Max-Age=5;Secure
< X-Waf: s43842
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000
< Set-Cookie: _cmuid=sqsdcqct-u0jx-5rqc-f9pe-aj2jp015ykpk; Expires=Sun, 27 Feb 2022 02:36:51 GMT; Path=/; Domain=.allegro.pl; Secure
<
* Connection #0 to host allegro.pl left intact

d99551d28f506d32

Działało sobie sporo czasu bezproblemowo i wczoraj wieczorem/dziś w nocy takie kwiatki.
Stare tokeny do 8.00 ważne, reszta zapytań śmiga.
Zanim uzupełniłem to zgłoszenie już się odświeżyły te tokeny.
Pytanie czy to chwilowa niemoc API czy może coś narozrabiałem bo nieco wcześniej puściłem sporo zapytań choć do 150/sek to jeszcze trochę brakowało.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę cały request wraz z response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619), w zgłoszeniu dopisz GitHub #2889.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem request, który nam przesłałeś - powodem odpowiedzi ze statusem 400 była chwilowa blokada adresu ip. w związku z odpytywaniem zasobu GET /sale/offers/{offerId} o nieistniejące oferty.
