### ISSUE TITLE
Błedy: 500, 504 - produkcja

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2891]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Obserwujemy od paru dni zwiększoną ilość błędów związanych z timeoutami

Przykładowe requesty:

REQUEST 2020-02-28 09:42:46.5240004 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU4MjgyMTgwMjY0MjQ1MA&limit=1000' \
  -H 'Accept: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \

RESPONSE 2020-02-28 09:42:49.5397075  Duration: 3015,7071ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (504) Gateway Timeout.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "WatsonBuckets": null
  },
  "TraceId": "e1154b7f3e152d7b",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

REQUEST 2020-02-28 09:42:50.5084839 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU4MDk0NjE5NjcwMTkzOQ&limit=1000' \
  -H 'Accept: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-02-28 09:42:53.5241869  Duration: 3015,703ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (504) Gateway Timeout.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "b81e6c7703cb57e2",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

REQUEST 2020-02-28 10:02:18.7324246 
curl -X GET \
  'https://api.allegro.pl/sale/offers?offer.id=8917379880&limit=20' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-02-28 10:02:18.7480502 Duration: 15,6256ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (500) Internal Server Error.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
     "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "1700878c4d4c4c83",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

REQUEST 2020-02-28 10:35:32.9826872 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU4Mjg4MTY3NDUwOTk1MA&limit=1000' \
  -H 'Accept: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-02-28 10:35:36.0139585 Duration: 3031,2713ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (504) Gateway Timeout.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "92f7ede8bee5f8a5",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na problem związany z danymi ze zgłoszenia #2719. Analizujemy te odpowiedzi.
