### ISSUE TITLE
Offer ID / identyfikator oferty w allegro - czy zawsze jest i będzie liczbą?

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#2892]
Pytanie - czy identyfikator oferty to zawsze jest/będzie liczba? 

Jak dotychczas wszystkie identyfikatory ofert w systemie allegro są liczbami, z drugiej strony w dokumentacji REST API dla komendy GET /sale/offers:

https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

pisze, iż parametr offer.id do wyszukiwania to string.

Ma to dla mnie o tyle znaczenie, że jest różnica w wydajności wyszukiwania w bazie danych między zapisem id oferty jako np. big int, a zapisaem id oferty jako string - chodzi chociażby o wielkość danych/indeksów.

**Comment by PrzemyslawLukanowski** [comment]
Identyfikator zawsze jest liczbą i na tę chwilę nie planujemy tego zmieniać.

**Comment by tztztztz** [comment]
Dziękuję za odpowiedź.
