### ISSUE TITLE
Dziwne zachowanie eventów

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2893]
Cześć.

Mamy ciekawy przypadek odnośnie endpointu https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET (/order/events). Mianowicie dotyczy to checkoutFormId **71a0dee2-5952-11ea-aca2-897335364668** oraz **95719262-5952-11ea-92ad-89387a43f9a8**.
Wczoraj w godzinach południowych dla obu przypadków otrzymaliśmy typ BOUGHT, a dzisiaj w podobnym czasie otrzymaliśmy poraz kolejny taki sam event BOUGHT wskazujący na tą samą aukcję z tym samym checkoutFormId.
Kiedyś pisaliście o tym, że jest to możliwe aby dostać sam event BOUGHT w przypadku jeśli ktoś posiada niezaktualizowaną wersję mobilnej aplikacji, jednak z mojej wiedzy wynika, że ta osoba z niej nie korzystała.
Jak to możliwe, że w przeciągu 24h dostaliśmy drugi raz to samo?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to i dla obu zamówień zwracamy pojedyncze eventy każdego z poniższych typów:

checkoutForm.id - 95719262-5952-11ea-92ad-89387a43f9a8
event.id: 1582802208297449- BOUGHT - 2020-02-27T11:16:36.202Z
event.id: 1582889646753525- FULFILLMENT_STATUS_CHANGED - 2020-02-28T11:33:53.960Z

checkoutForm.id - 71a0dee2-5952-11ea-aca2-897335364668
event.id: 1582802153133614- BOUGHT - 2020-02-27T11:15:41.939Z
event.id: 1582889653083466- FULFILLMENT_STATUS_CHANGED - 2020-02-28T11:34:01.416Z

W dniu dzisiejszym nie pojawił się status BOUGHT, ale FULFILLMENT_STATUS_CHANGED związany ze zmianą statusu realizacji zamówienia na "CANCELLED"

**Comment by bacok** [comment]
Dziękuję za odpowiedź. Po prostu nie obsługujemy jeszcze nowego statusu FULFILLMENT_STATUS_CHANGED i stąd moje podejrzenia :smiley:
