### ISSUE TITLE
Błędne odpowiedzi w  /sale/offers

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#2894]
Znów pojawił się problem błędnych danych na zasobie /sale/offers
Na licytacji wystawiona była jedna sztuka, która się sprzedała.
W responsie mam "stock":{"available":1,"sold":1},"
Błędne dane są wyświetlane też na frontendzie: ofert 1, zakończona, niesprzedana.

/sale/offers/id  podaje poprawne dane: available:0

`HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 36c1450a961d63e
date: Fri, 28 Feb 2020 17:14:18 GMT
x-ratelimit-remaining: 19999
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 1044
x-ratelimit-limit: 20000
x-envoy-upstream-service-time: 33

{"offers":[{"id":"8973680218","name":"wAO3871 LISA CAMPIONE czarna bluza z zamkiem 44","category":{"id":"76035"},"primaryImage":{"url":"https://a.allegroimg.com/original/03f20a/47cae3e94f518ae6d8324784550e"},"sellingMode":{"format":"AUCTION","price":null,"minimalPrice":null,"startingPrice":{"amount":"36.9","currency":"PLN"}},"saleInfo":{"currentPrice":{"amount":"36.9","currency":"PLN"},"biddersCount":1},"stats":{"watchersCount":2,"visitsCount":15},"stock":{"available":1,"sold":1},"publication":{"status":"ENDED","startingAt":null,"startedAt":"2020-02-20T19:42:29Z","endingAt":"2020-02-27T19:42:29Z","endedAt":"2020-02-27T19:42:29Z"},"afterSalesServices":{"warranty":{"id":"8c07edbd-808b-41f3-9541-b0668f319000"},"returnPolicy":{"id":"68b78027-c9de-453f-a68f-0c11f08a26bf"},"impliedWarranty":{"id":"515d3b8c-32cf-4531-8c52-b43b2a51b178"}},"additionalServices":{"id":"5d98870b-f604-4809-9e7a-c070de4dd394"},"external":{"id":"NOWETANIE02"},"delivery":{"shippingRates":{"id":"6d5e12e1-fb0c-4ef0-9a99-836ee93ba0b8"}}}],"count":1,"totalCount":1}`

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to i potwierdzam rozbieżnosć. Przekazałem problem do odpowiedniego zespołu.
