### ISSUE TITLE
[REST] Sandbox umarł - logowanie nie jest możliwe.

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#2895]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Allegro Sandbox umarł - nie działa.... logowanie, autoryzacja nie jest możliwa !

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę Sandbox działa prawidłowo. Czy w dalszym ciągu nie możesz się zalogować?

**Comment by wwwfactory** [comment]
Dzień dobry - Sandbox nie działał od niedzieli do poniedziałku. około godziny 12 już działał. Zamykamy
