### ISSUE TITLE
Błąd struktury danych json na produkcji /sale/offers

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#2897]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Na produkcji z zasobu /sale/offers zwracane są niepoprawne dane dla aukcji 9003114224 powodujące błędy deserializacji json.

Proszę o poprawę danych.

TraceId
cead6b47c6e15f28

```
curl --location --request GET 'https://api.allegro.pl/sale/offers?publication.status=INACTIVE%2CACTIVATING%2CACTIVE%2CENDED&sellingMode.format=BUY_NOW%2CADVERTISEMENT%2CAUCTION&limit=25&offset=0' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL' \
--header 'Authorization: Bearer #' \
```

```
"additionalServices": {
                "id": "null"
            }
```

Dla pozostałych aukcji jest prawidłowo null

`"additionalServices": null,`

Dodatkowo jest błędne

```
"afterSalesServices": {
                "warranty": {
                    "id": "null"
                },
```

Zamiast prawidłowo w innych aukcjach:
```

"afterSalesServices": {
                "warranty": null,
```

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście występuje rozbieżność. Zgłosiłem to do poprawy.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski poprawicie to globalnie? Bo dotyczy to wielu Klientów i wielu różnych aukacji

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Podeślij proszę przykłady ofert w których zauważyłeś również taki problem w tym zasobie.

**Comment by SebastianOzdoba** [comment]
@PawelTaberski 
To nie są wszystkie, wyłapanie ich jest dla nas czasochłonne
9003199775, 9003194757, 9003191209, 9003189255, 9003187419, 9003185680, 9003178576, 9003009898, 9003088292, 9002948036, 8995147663, 8994681711, 8987010932, 8977421009, 8966554359, 8963376732, 8954799539, 8951575763, 8947796485, 8947746345, 8944534628, 8940980592, 8938420778, 8938405290, 8930988782, 8860048827, 8859874000, 8845936647
8843143168, 8799705526

**Comment by PawelTaberski** [comment]
@SebastianOzdoba Dzięki za przykłady, przekazałem je do zespołu, który zajmuje się tą sprawą.
