### ISSUE TITLE
doGetSiteJournal - brak danych

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2898]
Czy macie jakiś problem z metodą doGetSiteJournal?
Od kilkunastu minut nie dostaję danych. Tablica siteJornalArray jest pusta. Row id: 46481371331.
Nie dostaję błędów ani nic.

**Comment by artzie92** [comment]
Na logowaniu dostaję puste wartości:
![image](https://user-images.githubusercontent.com/16481836/75668589-d2767c00-5c79-11ea-8620-77ebe560802d.png)

**Comment by PawelTaberski** [comment]
Udało nam się namierzyć i rozwiązać problem. Czy teraz u Ciebie metoda działa prawidłowo?

**Comment by artzie92** [comment]
Tak zaczęło działać. Dzięki

**Comment by PawelTaberski** [comment]
@artzie92 Jeśli to nie problem, to podeślij jeszcze tylko proszę klucz jakiego używasz przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu zaznacz, że dane są potrzebne do ticketa numer 2898 na GitHub-ie.

**Comment by artzie92** [comment]
Wysłane :)
