### ISSUE TITLE
Jak zidentyfikować kategorię pozwalającą wystawiać tylko ogłoszenia

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#2899]
Czy jest jakiś sposób aby jednoznacznie stwierdzić, czy dana kategoria wspiera wystawianie tylko ofert typu `ADVERTISEMENT`. 

W dokumentacji jest napisane , że pole `options.advertisement` zwracane z `/sale/categories/{categoryId}` oznacza, że kategoria wspiera wystawnie ogłoszeń. Nie oznacza to, że nie wspiera licytacji itp.

> Indicates whether offers of type ADVERTISEMENT can be listed in this category.

```json
{
    "categories": [
        {
            "id": "12",
            "leaf": true,
            "name": "Pozostałe",
            "options": {
                "advertisement": true,
                "advertisementPriceOptional": true,
                "variantsByColorPatternAllowed": true,
                "offersWithProductPublicationEnabled": true,
                "productCreationEnabled": true,
                "productEANRequired": true
            },
            "parent": {
                "id": "709"
            }
        }
    ]
}
```

**Comment by PawelTaberski** [comment]
Zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/#step-2), to pole informuje:
    "advertisement": false,                     -- informacja, czy w danej kategorii
                                                lub jej podkategoriach można wystawić ofertę 
                                                ogłoszeniową.
Wartość true nie oznacza, że w takiej kategorii można wystawiać tylko ogłoszenia.
Napisz proszę do czego potrzebna jest Tobie informacje, że w danej kategorii można wystawić tylko ogłoszenie.

**Comment by AnimalDEV** [comment]
W aplikacji którą piszę nie będzie możliwości wystawiania ogłoszeń do Allegro. Kiedy użytkownikowi wyświetlam drzewko kategorii chcę, aby nie widział tych kategorii w których można wystawiać tylko ogłoszenia, ponieważ to powoduje zwróceniem błędu w stylu "W tej kategorii możesz wystawiać tylko ogłoszenia" przy próbie wystawiania.

**Comment by PawelTaberski** [comment]
Rozumiem - przekazałem Twoją sugestię do odpowiedniego zespołu.
