### ISSUE TITLE
problem z metodą doGetRefundsList

### ISSUE THREAD

**Issue by YpsilonSH** [allegro/allegro-api#290]
Witam, mam program w VB.net w oparciu o WSDL obsługujący dużą część funkcjonalności udostępnianych przez WebApi i do tej pory nie miałem takiego problemu jaki występuje z metodą doGetRefundsList. Zwraca mi ciągle błąd: Wystąpił błąd podczas deserializacji treści komunikatu odpowiedzi dla operacji „doGetRefundsList”. Probowałem ustawiać filtr na wejściu i z filtrem pustym, komunikat ciągle ten sam, a na koncie na którym dokonuję testów są złożone i nierozpatrzone wnioski o zwrot prowizji, złożone metodą doSendRefundForm bez żadnych problemów. Czy problem może być u Państwa na serwerach, może wsdl wymaga aktualizacji?

**Comment by KrzysztofLukanowski** [comment]
Cześć, podeślij proszę request i response w xml. Sprawdzimy.

**Comment by YpsilonSH** [comment]
walczyłem, aby przechwycić te request i response w xml za pomocą implementacji SOAP Extension w VB.NET (podobnie jak opisano tutaj: https://blogs.msdn.microsoft.com/kaevans/2007/08/06/programmatically-insert-soapheader-into-soap-request-with-asmx-soapextensions/), aby zapisało mi te xml do pliku przy wywoływaniu metody, niestety bezskutecznie, nie ma innego sposobu sprawdzenia gdzie może tkwić błąd?

**Comment by KrzysztofLukanowski** [comment]
Sprawdziliśmy i metoda działa prawidłowo, dlatego jeśli problem nadal występuje, potrzebowałbym danych do weryfikacji, a więc wglądu w request, który jest do nas wysyłany.

**Comment by YpsilonSH** [comment]
OK, dzięki za odp., jak tylko uda mi się przechwycić request w xml to podeślę

**Comment by YpsilonSH** [comment]
Problem nadal występuje, aplikacja pisana w MS VS2012.
Zwraca taki kod i opis błędu
5:Wystąpił błąd podczas deserializacji treści komunikatu odpowiedzi dla operacji „doGetRefundsList”.
o dziwo błąd jest tylko gdy jest zapytanie o status zwrotu prowizji dla oferty, który jest w trakcie (refundStatus 5). Gdy zwrot został przyznany do innej oferty, to wtedy błędu już nie było i odpowiedź została zdeserializowana prawidłowo. Wklejam xml request i response otrzymany przez https://wsdlbrowser.com, dla zapytania, które w MS VS generuje błąd jak wyżej.
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
  <SOAP-ENV:Body>
    <ns1:DoGetRefundsListRequest>
      <ns1:sessionId>ec36e489f7ec79718794910c614381096f42ca95846f2f//03_1</ns1:sessionId>
      <ns1:filterOptions>
        <ns1:item>
          <ns1:filterId>itemId</ns1:filterId>
          <ns1:filterValueId>
            <ns1:item>7420146555</ns1:item>
          </ns1:filterValueId>
          <ns1:filterValueRange>
            <ns1:rangeValueMin>?</ns1:rangeValueMin>
            <ns1:rangeValueMax>?</ns1:rangeValueMax>
          </ns1:filterValueRange>
        </ns1:item>
      </ns1:filterOptions>
      <ns1:resultSize>100</ns1:resultSize>
      <ns1:resultOffset>0</ns1:resultOffset>
    </ns1:DoGetRefundsListRequest>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:ns1="https://webapi.allegro.pl/service.php">
    <SOAP-ENV:Body>
        <ns1:doGetRefundsListResponse>
            <ns1:refundsCount>1</ns1:refundsCount>
            <ns1:refundsList>
                <ns1:item>
                    <ns1:dealId>1828211301</ns1:dealId>
                    <ns1:dealDate>2018-06-25T09:00:46+02:00</ns1:dealDate>
                    <ns1:buyerId>1268298</ns1:buyerId>
                    <ns1:buyerLogin>zori</ns1:buyerLogin>
                    <ns1:itemId>7420146555</ns1:itemId>
                    <ns1:itemTitle>Simba Steffi w ciąży wózek rower Kevin Evi Barbie</ns1:itemTitle>
                    <ns1:bidsCount>1</ns1:bidsCount>
                    <ns1:quantityType>PIECE</ns1:quantityType>
                    <ns1:refundDetails>
                        <ns1:refundId>54821173</ns1:refundId>
                        <ns1:refundStatus>5</ns1:refundStatus>
                        <ns1:refundQuantity>1</ns1:refundQuantity>
                        <ns1:createdDate>2018-06-25T14:00:16+02:00</ns1:createdDate>
                        <ns1:considerDate></ns1:considerDate>
                    </ns1:refundDetails>
                </ns1:item>
            </ns1:refundsList>
            <ns1:filtersList>
                <ns1:item>
                    <ns1:filterId>itemId</ns1:filterId>
                    <ns1:filterName>Identyfikator oferty</ns1:filterName>
                    <ns1:filterType>country</ns1:filterType>
                    <ns1:filterControlType>textbox</ns1:filterControlType>
                    <ns1:filterDataType>long</ns1:filterDataType>
                    <ns1:filterIsRange>false</ns1:filterIsRange>
                    <ns1:filterValues/>
                    <ns1:filterRelations>
                        <ns1:relationExclude>
                            <ns1:item>userLogin</ns1:item>
                        </ns1:relationExclude>
                    </ns1:filterRelations>
                </ns1:item>
                <ns1:item>
                    <ns1:filterId>userLogin</ns1:filterId>
                    <ns1:filterName>Nazwa użytkownika</ns1:filterName>
                    <ns1:filterType>country</ns1:filterType>
                    <ns1:filterControlType>textbox</ns1:filterControlType>
                    <ns1:filterDataType>string</ns1:filterDataType>
                    <ns1:filterIsRange>false</ns1:filterIsRange>
                    <ns1:filterValues/>
                    <ns1:filterRelations>
                        <ns1:relationExclude>
                            <ns1:item>itemId</ns1:item>
                        </ns1:relationExclude>
                    </ns1:filterRelations>
                </ns1:item>
            </ns1:filtersList>
        </ns1:doGetRefundsListResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by KrzysztofLukanowski** [comment]
Nie mogę potwierdzić błędu. Przed chwilą wystąpiłem o zwrot prowizji dla przypadku, który jak napisałeś, jest w trakcie, otrzymałem prawidłową odpowiedź. Zwróć proszę uwagę czy przesyłasz prawidłowo zbudowany request. W Twoim przypadku powinien wyglądać następująco:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoGetRefundsListRequest>
         <ser:sessionId>[SessionId]</ser:sessionId>
          <ser:filterOptions>
            <ser:item>
               <ser:filterId>itemId</ser:filterId>
               <ser:filterValueId>
                  <ser:item>7420146555</ser:item>
               </ser:filterValueId>
            </ser:item>
          </ser:filterOptions>
      </ser:DoGetRefundsListRequest>
   </soapenv:Body>
</soapenv:Envelope>`
