### ISSUE TITLE
Automatyczne przeniesienie / usunięcie / zarchiwizowanie przez Allegro

### ISSUE THREAD

**Issue by kowalikus** [allegro/allegro-api#2900]
Czy da się przez API pobrać informację o tym, że oferta została usunięta lub przeniesiona do innej kategorii przez Allegro lub została zarchiwizowana?

Czy zasób `sale/offer-events` zwraca eventy tylko z ostatnich 24h?

**Comment by PawelTaberski** [comment]
Tak, ten zasób zwraca dane z ostatnich 24h.
Jeśli w ofercie wystąpiły jakieś zmiany, została zakończona, bądź przeniesiona do archiwum to w dzienniku zdarzeń otrzymasz odpowiedni status.
Więcej na temat statusów znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).

**Comment by kowalikus** [comment]
Czyli automatyczna zmiana kategorii przez Allegro będzie zdarzeniem typu: `OFFER_CHANGED`?

**Comment by PawelTaberski** [comment]
Tak, w takim wypadku powinieneś otrzymać zdarzenie typu OFFER_CHANGED.
