### ISSUE TITLE
Do kiedy beta dziennika aukcji ?

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#2901]
Witam,

Kiedy zasób https://developer.allegro.pl/documentation/#operation/getOfferUsingGET wyjdzie z bety ? Chcielibyśmy już się przełączyć w całości na REST API i praktycznie tylko to nam zostało. Według harmonogramu metoda w SOAP API doGetSiteJournal wygaśnie w kwietniu https://developer.allegro.pl/schedule/

**Comment by PawelTaberski** [comment]
Najprawdopodobniej jeszcze w tym tygodniu te zasoby wyjdą z bety, jednakże już teraz można z nich bezpiecznie korzystać.
