### ISSUE TITLE
Wznawianie oferty

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#2902]
Witam,
proszę o weryfikację dla czego oferta nie została wznowiona 
```
PUT {"offerCriteria":[{"offers":[{"id":"8908940338"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2020-03-02T13:18:46Z"}}

PUT {"modification":{"changeType":"FIXED","value":"4"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"8908940338"}]}]}
```

W obu przypadkach odpowiedź jest następująca 

>  object(stdClass)#33 (2) {
>   ["id"]=>
>   string(36) "58b7a30c-9c29-4c82-b4b9-f6e82f817690"
>   ["taskCount"]=>
>   object(stdClass)#34 (3) {
>     ["total"]=>
>     int(0)
>     ["success"]=>
>     int(0)
>     ["failed"]=>
>     int(0)
>   }
> }
>

**Comment by PawelTaberski** [comment]
Sprawdziłem status publikacji zasobem: GET /sale/offer-publication-commands/{commandId}/tasks
i otrzymałem informację: 
`"message": "Could not change offer publication status. Incorrect initial quantity of stock.",`
Sprawdziłem Twoją ofertę i masz w niej stack równy 0. Musisz najpierw ją wyedytować i zwiększyć zapas towaru, następnie będziesz mógł ją aktywować.

**Comment by mzawodzinski** [comment]
Dobrze czyli rozumiem że najpierw mam robić aktualizację statu, a później wznowienie. 
Tak również sprawdzałem i nie działa

```
PUT: https://api.allegro.pl/sale/offer-quantity-change-commands/8265d626-9bb5-4fe9-82be-d2861248bb98
Req: {"modification":{"changeType":"FIXED","value":"3"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"8908940338"}]}]}
Res: {"id":"8265d626-9bb5-4fe9-82be-d2861248bb98","taskCount":{"total":0,"success":0,"failed":0}}
```

```
GET: https://api.allegro.pl/sale/offer-quantity-change-commands/8265d626-9bb5-4fe9-82be-d2861248bb98
{"id":"8265d626-9bb5-4fe9-82be-d2861248bb98","taskCount":{"total":0,"success":0,"failed":0}}
```

```

PUT: https://api.allegro.pl/sale/offer-publication-commands/8265d626-9bb5-4fe9-82be-d2861248bb98
Req:{"offerCriteria":[{"offers":[{"id":"8908940338"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2020-03-03T08:02:45Z"}}
Res:{"id":"8265d626-9bb5-4fe9-82be-d2861248bb98","taskCount":{"total":0,"success":0,"failed":0}}
```

```

GET: https://api.allegro.pl/sale/offer-publication-commands/8265d626-9bb5-4fe9-82be-d2861248bb98
{"id":"8265d626-9bb5-4fe9-82be-d2861248bb98","taskCount":{"total":0,"success":0,"failed":0}}
```

```
GET: https://api.allegro.pl/sale/offer-publication-commands/8265d626-9bb5-4fe9-82be-d2861248bb98/tasks
{"tasks":[]}

```

**Comment by PawelTaberski** [comment]
@mzawodzinski Cały czas używasz jednego UUID-a pamiętaj, że powinien być unikatowy do każdego zadania, aby móc śledzić jego wykonanie. W Twoim wypadku cały czas widzisz status z zadania zmiany stock-u.
