### ISSUE TITLE
Pobieranie wszystkich wgranych zdjęć - adresy lokalizacji nadawane w procesie POST /sale/images

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#2903]
Witam, chciałem zapytać się jak pobrać wszystkie wgrane na allegro zdjęcia, 
GET /sale/images nie działa (405 Method Not Allowed)

metodą: "POST /sale/images" - przesyłam nowe zdjęcie i dostaję jego lokalizację którą używam przy wystawianiu oferty ale jak pobrać później te identyfikatory nie listując wszystkich swoich ofert jedna po drugiej metodą GET /sale/offers/{offerId} ?

Dodatkowe pytanie o PUT /sale/images/{id} - bo tego też nie widzę w dokumentacji czy jeśli chcę zmienić zdjęcie i jest ono użyte w 20 aukcjach to muszę wykonaćn następujący flow: 

1) wgrać nowe foto za pomocą POST /sale/images
2) otrzymany uri lokalizacji wykorzystać do modyfikacji oferty za pomocą PUT /sale/offers/{offerId} dla każdego offerId z tych 20 które posiadam do zmiany ? 

Jeśli tak to kiedy allegro decyduje o usunięciu zdjęć które są przypisane do kilku ofert ? (opisy / miniatury etc.)

Dziękuję za informacje.

**Comment by PawelTaberski** [comment]
Nie mamy zasobu do pobierania przesłanych zdjęć. Tak, długo jak zdjęcie jest przypisane do jakiejś choć 1 oferty nie zostanie usunięte. Jeśli chcesz zmienić zdjęcie to dokładnie - tak jak napisałeś przesyłasz nowe zdjęcie i dodajesz je do oferty.

**Comment by pliszka2** [comment]
@PawelTaberski thx zamykam :)
