### ISSUE TITLE
Ilość ofert zwracanych przez: /sale/loyalty/promotions

### ISSUE THREAD

**Issue by PiotrLaszczyk** [allegro/allegro-api#2905]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Jak się zrobi odpowiedno dużo promocji zasobem /sale/loyalty/promotions to w responsie nie pojawiają sie już wszystkie aktualnie stworzone. Wydaje się że by się przydał jakiś offset w tej metodzie do pobieranie fragmentami tej listy.

**Comment by PawelTaberski** [comment]
W zasobie GET /sale/loyalty/promotions możesz korzystać z offset-u i limitu-u więcej na ten temat znajdziesz w [naszej dokumentacji.](https://developer.allegro.pl/documentation/#operation/listSellerPromotionsUsingGET_1)

**Comment by PiotrLaszczyk** [comment]
Słusznie...To nie doczytałem.
