### ISSUE TITLE
/offers/listing w wersji testowej allegro nie zwraca wyników

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#2906]
Występuje problem: 
 - [x] ze środowiskiem testowym

W wersji testowej allegro zostało stworzonych kilka ofert (przez użytkownika o id 44026697), które są aktywne i widoczne w testowym allegro, ale niestety nie wyświetlają się kiedy korzysta się z metody /offers/listing.

Przykładowy URL:

https://api.allegro.pl.allegrosandbox.pl/offers/listing?seller.id=44026697&limit=40&sort=-startTime&offset=0

Zwracane dane (response):

{"items":{"promoted":[],"regular":[]},"searchMeta":{"availableCount":0,"totalCount":0,"fallback":false},"categories":{"subcategories":[],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[{"id":"sellingMode.format","type":"MULTI","name":"rodzaj oferty","values":[{"value":"BUY_NOW","name":"kup teraz","count":0,"selected":false},{"value":"AUCTION","name":"licytacje","count":0,"selected":false}]},{"id":"price","type":"NUMERIC","name":"cena","values":[{"idSuffix":".from","name":"od","selected":false},{"idSuffix":".to","name":"do","selected":false}],"minValue":0,"maxValue":1000000000,"unit":"zł"},{"id":"deliveryMethod","type":"MULTI","name":"sposoby dostawy","values":[{"value":"5b445fa0580ce26bb2f99602","name":"Kurier","count":0,"selected":false},{"value":"5b445fd9580ce26bb2f99608","name":"Kurier wieczór","count":0,"selected":false},{"value":"5b445fe6580ce26bb2f9960a","name":"Paczkomaty InPost","count":0,"selected":false},{"value":"5b446004580ce26bb2f9960c","name":"Odbiór w punkcie","count":0,"selected":false},{"value":"5b446013580ce26bb2f9960e","name":"List","count":0,"selected":false},{"value":"5b446031580ce26bb2f99610","name":"Paczka","count":0,"selected":false},{"value":"5b44606c580ce26bb2f99616","name":"Ekspresowa dostawa","count":0,"selected":false},{"value":"5b446044580ce26bb2f99612","name":"Odbiór osobisty","count":0,"selected":false},{"value":"5b44605c580ce26bb2f99614","name":"Przesyłka elektroniczna","count":0,"selected":false}]},{"id":"location.city","type":"TEXT","name":"miejscowość","values":[{"name":"miejscowość","selected":false}]},{"id":"location.province","type":"SINGLE","name":"województwo","values":[{"value":"DOLNOSLASKIE","name":"z dolnośląskiego","selected":false},{"value":"KUJAWSKO_POMORSKIE","name":"z kujawsko-pomorskiego","selected":false},{"value":"LUBELSKIE","name":"z lubelskiego","selected":false},{"value":"LUBUSKIE","name":"z lubuskiego","selected":false},{"value":"LODZKIE","name":"z łódzkiego","selected":false},{"value":"MALOPOLSKIE","name":"z małopolskiego","selected":false},{"value":"MAZOWIECKIE","name":"z mazowieckiego","selected":false},{"value":"OPOLSKIE","name":"z opolskiego","selected":false},{"value":"PODKARPACKIE","name":"z podkarpackiego","selected":false},{"value":"PODLASKIE","name":"z podlaskiego","selected":false},{"value":"POMORSKIE","name":"z pomorskiego","selected":false},{"value":"SLASKIE","name":"ze śląskiego","selected":false},{"value":"SWIETOKRZYSKIE","name":"ze świętokrzyskiego","selected":false},{"value":"WARMINSKO_MAZURSKIE","name":"z warmińsko-mazurskiego","selected":false},{"value":"WIELKOPOLSKIE","name":"z wielkopolskiego","selected":false},{"value":"ZACHODNIOPOMORSKIE","name":"z zachodniopomorskiego","selected":false}]},{"id":"option","type":"MULTI","name":"oferta ma","values":[{"value":"FREE_SHIPPING","name":"darmowa dostawa","selected":false},{"value":"FREE_RETURN","name":"darmowy zwrot","selected":false},{"value":"VAT_INVOICE","name":"faktura VAT","selected":false},{"value":"COINS","name":"Monety Allegro","selected":false},{"value":"BRAND_ZONE","name":"Strefa Marek","selected":false},{"value":"SUPERSELLER","name":"Super Sprzedawca","selected":false},{"value":"CHARITY","name":"Allegro Charytatywni","selected":false},{"name":"tylko przecenione","selected":false},{"value":"SMART","name":"Allegro Smart!","selected":false}]},{"id":"campaign","type":"MULTI","name":"kampania","values":[{"value":"BARGAIN","name":"Strefa Okazji","selected":false},{"value":"BARGAIN_REBATE","name":"rabaty","selected":false}]}],"sort":[{"value":"-relevance","name":"trafność","order":"największa","selected":false},{"value":"+price","name":"cena","order":"od najniższej","selected":false},{"value":"-price","name":"cena","order":"od najwyższej","selected":false},{"value":"+withDeliveryPrice","name":"cena z dostawą","order":"od najniższej","selected":false},{"value":"-withDeliveryPrice","name":"cena z dostawą","order":"od najwyższej","selected":false},{"value":"-popularity","name":"popularność","order":"największa","selected":false},{"value":"+endTime","name":"czas do końca","order":"najmniej","selected":false},{"value":"-startTime","name":"czas dodania","order":"najnowsze","selected":true}]}

Podobne zapytanie / URL na systemie produkcyjnym dla innego użytkownka zwraca prawidłowo listę ofert.

**Comment by PawelTaberski** [comment]
Sprawdziłem i ten użytkownik nie ma aktywnych ofert na [środowisku testowym](https://allegro.pl.allegrosandbox.pl/uzytkownik/tomek3kropki?bmatch=product-test-best-cl-uni-1-2-0906).

**Comment by tztztztz** [comment]
To dość dziwne bo, po pierwsze, oferta stworzona przez tego użytkownika jest widoczna:

https://allegro.pl.allegrosandbox.pl/oferta/total-war-warhammer-ii-the-hunter-and-the-6206768343

po drugie, w momencie kiedy towrzyłem ten issue, po wejściu na https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty, ta oferta do której podałem link wyżej, oraz kilka innych było widoczne, nie są widoczne dopiero teraz - mimo, że [rzekładowa oferta jest widoczna w środowisku testowym dla niezalogowanego i ma opcję "kup teraz", więc jest aktywna

**Comment by PawelTaberski** [comment]
Rzeczywiście - wygląda to na błąd. Zgłosiłem sprawę do odpowiedniego zespołu.

**Comment by tztztztz** [comment]
Ponownie w panelu allegro sandboxa pojawiło się 9 aktywnych ofert.

Na tych dziewięć aktywnych ofert teraz w listingu (GET /offers/listing) pojawia się jedna, to jakiś postęp, jednak dobrze by było to naprawić, potrzebuję zrobić różne testy i wolę ich nie robić na wersji produkcyjnej. 

Co prawda te oferty zostały dodane już dość dawno, no ale mają status aktywnych w panelu allegro, więc powinny się również pojawić w danych pobieranych metodą /offers/listing

Tyle dobrze, że pobierając ofertę metodą /sale/offers/{$oferer_id} każda z tych 9 ofert ma odpowiedni status, jednak bug z listą nadal jest.

**Comment by PawelTaberski** [comment]
Zespół jeszcze pracuje nad rozwiązaniem tego problemu, prośba o cierpliwość.

**Comment by PawelTaberski** [comment]
@tztztztz Niestety te oferty są dosyć historyczne i mamy problem z ich zaindeksowaniem. Wyedytuj je proszę - wtedy powinny się pojawić.

**Comment by tztztztz** [comment]
Tak, po edycji, nawet bez dokonania żadnych zmian po chwili pferta pojawia się na listingu. Przy czym i tak dla mnie najważniejsze jest, że można pobrać dane tych ofert przez /sale/offers/{nr oferty} - dlatego zamykam, i dziekuję za pomoc.
