### ISSUE TITLE
REST Sandbox HTTP 422

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#2907]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem testowym
 - [ ] ze środowiskiem produkcyjnym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

na Sandboxie mam ofertę, chcę ją przeedytować i nie mogę - podczas modyfikowania oferty wystąpiły błędy

to w takim razie próba przez API, np kopia na nowe id, 
HTTP 422 :)

trace ID : fbe116c75eaa8fdb

więc o co chodzi tym razem ?

**Comment by MaciejFrackowiak** [comment]
Sprawdziliśmy opisany przez Ciebie przypadek - oferta, którą chciałeś wystawić (a wcześniej wyedytować) posiada zdjęcie, którego adres URL pochodzi z produkcyjnej wersji serwisu - obecnie zdjęcie musi być dodane na Sandbox by móc je wykorzystać w Sandbox'owej ofercie.

**Comment by wwwfactory** [comment]
Okey. Puściliście do obiegu ankietę w której zawarliście wiele pytań o to czy to co robicie jest czytelne, fajne,  cudowne itd :)
Pytanie :
dlaczego nie jesteście w stanie zwrócić pierwszego napotkanego błędu który powoduje brak możliwości zrobienia tego czy owego? Ten temat poruszałem ponad rok wstecz.
Wracając do zdjęć - gdzie taka wiedza jest dostępna ? Co przeoczyłem ? Czy jest jeszcze jakieś miejsce na waszych stronach które trzeba zgłębiać codziennie ? 
W ankiecie również o to pytaliście. O dokumentację etc.

**Comment by MaciejFrackowiak** [comment]
Wraz z błędem 422 zwróciliśmy komunikat “Podany adres obrazka jest nieprawidłowy.“ - i jest on w tym przypadku całkowicie zasadny - wykorzystanie obrazka z produkcji na Sandbox nie jest możliwe (i vice versa). Wcześniejsza taka możliwość była de facto naszą niedoskonałością, dlatego ją wyeliminowaliśmy. Nadal również pracujemy, aby zwracane przez nas komunikaty były możliwie precyzyjne i oddawały sedno problemu.

**Comment by wwwfactory** [comment]
Panie Macieju, Bardzo dziękuję za wyjaśnienia i poświęcony czas. Zamykamy.
