### ISSUE TITLE
Co się stanie jeśli usuniemy jedną z ofert połączonych w warianty

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#2909]
Chciałbym się zapytać czy jak mam połączonych kilka ofert w warianty, to co się stanie jak usunę/zdezaktywuję jedną z nich. Czy oferta wielowariantowa wciąż będzie działać i czy trzeba ręcznie aktualizować zestaw wariantów?

**Comment by MaciejFrackowiak** [comment]
W takim przypadku zestaw wariantów nadal będzie aktywny bez tej jednej oferty - gdy ją ponownie aktywujesz "powróci" do zestawu.
