### ISSUE TITLE
Metoda doNewAuctionExt i problem z fid 2566

### ISSUE THREAD

**Issue by kalif1981** [allegro/allegro-api#291]
Witam,

Podczas wystawiania aukcji przez WebAPI doNewAuctionExt, API zwraca błąd o niepoprawnej wartości parametru fid 2566 "Klasa efektywności energetycznej". Aukcja jest dodawana do kategorii ID: 67430. Podczas pobierania informacji o dodatkowych parametrach produktu/kategorii otrzymuję następujące dane dot. tego parametru:

[247]=>
    object(stdClass)#253 (20) {
      ["sell-form-id"]=>
      int(2566)
      ["sell-form-title"]=>
      string(33) "Klasa efektywności energetycznej"
      ["sell-form-cat"]=>
      int(67430)
      ["sell-form-type"]=>
      int(4)
      ["sell-form-res-type"]=>
      int(2)
      ["sell-form-def-value"]=>
      int(0)
      ["sell-form-opt"]=>
      int(1)
      ["sell-form-pos"]=>
      int(10)
      ["sell-form-length"]=>
      int(6)
      ["sell-min-value"]=>
      string(4) "0.00"
      ["sell-max-value"]=>
      string(9) "209997.00"
      ["sell-form-desc"]=>
      string(46) " -- Wybierz -- |A++|A+|A|B|C|Inne|A+++|D|E|F|G"
      ["sell-form-opts-values"]=>
      string(43) "0|1|2|3|4|5|6|7|209985|209989|209993|209997"
      ["sell-form-field-desc"]=>
      string(7) "rtv/agd"
      ["sell-form-param-id"]=>
      int(575)
      ["sell-form-param-values"]=>
      string(43) "0|1|2|3|4|5|6|7|209985|209989|209993|209997"
      ["sell-form-parent-id"]=>
      int(0)
      ["sell-form-parent-value"]=>
      string(1) "0"
      ["sell-form-unit"]=>
      string(0) ""
      ["sell-form-options"]=>
      }

W momencie wystawiania wysyłana jest wartość 2 (czyli klasa A+) typ: integer (zgodnie z wartością sell-form-res-type):

  [36]=>
  array(10) {
    ["fid"]=>
    string(4) "2566"
    ["fvalue-string"]=>
    string(0) ""
    ["fvalue-int"]=>
    int(2)
    ["fvalue-float"]=>
    float(0)
    ["fvalue-image"]=>
    int(0)
    ["fvalue-datetime"]=>
    int(0)
    ["fvalue-date"]=>
    string(0) ""
    ["fvalue-range-int"]=>
    array(2) {
      ["fvalue-range-int-min"]=>
      int(0)
      ["fvalue-range-int-max"]=>
      int(0)
    }
    ["fvalue-range-float"]=>
    array(2) {
      ["fvalue-range-float-min"]=>
      int(0)
      ["fvalue-range-float-max"]=>
      int(0)
    }
    ["fvalue-range-date"]=>
    array(2) {
      ["fvalue-range-date-min"]=>
      string(0) ""
      ["fvalue-range-date-max"]=>
      string(0) ""
    }
  }

Niestety ciągle zwracany jest ten sam błąd. Dodam, że inne produkty wystawiają się bez problemu. Co może być przyczyną problemu?

**Comment by KrzysztofLukanowski** [comment]
Cześć, czy możesz wkleić pełną treść request i response?

**Comment by kalif1981** [comment]
Witam,

Tak, oczywiście. Załączam je w plikach. Pewne dane, typu nr konta, ścieżki do moich skryptów, implied-warranty, return-policy, warranty pozwoliłem sobie ukryć. Usunąłem też kod base64 zdjęć, aby łatwiej było przejrzeć kod requestu i response.
[request.txt](https://github.com/allegro/allegro-api/files/2093007/request.txt)
[response.txt](https://github.com/allegro/allegro-api/files/2093008/response.txt)

**Comment by KrzysztofLukanowski** [comment]
Dziękuję za pliki. Z tego co widzę, wartości dla FID 2566 przesyłasz kilkukrotnie. Spróbuj wystawić ofertę przez GUI, a następnie pobierz ją za pomocą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842). Otrzymasz komplet pól odpowiadających wystawionej ofercie, następnie wykorzystaj te same pola do nowej oferty.

**Comment by kalif1981** [comment]
Rozumiem, spróbuję w ten sposób.
Dziękuję za pomoc.

**Comment by kalif1981** [comment]
Witam,

Miał Pan rację, parametry w requeście się nadpisywały stąd informacja o niepoprawnej wartości dla fid2566. Serdecznie dziękuję za pomoc.
