### ISSUE TITLE
jak odczytać dane użytkownika allegro?

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#2910]
Jak w temacie. Podając id użytkownika chcę poznać jego dane, a przynajmniej jego nick Allegro. Da się?

SB

**Comment by MaciejFrackowiak** [comment]
W REST API nie mamy zasobu zwracającego takie dane dla dowolnego użytkownika. Login użytkownika podając jego ID możesz odczytać poprzez WWW - wystarczy w odnośniku: https://allegro.pl/uzytkownik/xxxxxx/oceny pod xxxxxx podstawić właściwe id konta.

**Comment by sbrzezin** [comment]
Dzięki za odp. Byłoby jednak fajnie, gdyby takie dane można było odczytać przez API zamiast z WWW, które dzisiaj ma taką treść, a jutro inną. Przwidujecie taką możliwość?

**Comment by MaciejFrackowiak** [comment]
Tak, mamy to odnotowane na liście sugestii dot. rozwoju REST API - Twój głos również dopisuję.
