### ISSUE TITLE
Czy jest szansa na funkcję filtrowania aukcji wg jej id w /offers/listing?

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#2911]
Pytałem kiedyś o to, inni też pytali. Czy jest szansa na realizację tej funkcji?

pozdrawiam

SB

**Comment by MaciejFrackowiak** [comment]
Mamy to zapisane na liście sugestii zgodnie z postem #540 - w momencie wprowadzenia zmiany na pewno o tym poinformujemy.

**Comment by sbrzezin** [comment]
Temat czeka już prawie 2 lata. No to będziemy czekali dalej :)
pozdrawiam
SB
