### ISSUE TITLE
Raty Allegro

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#2912]
Witam
W wątku https://github.com/allegro/allegro-api/issues/2616
piszecie, ze transakcja dochodzi do skutku w momencie pozytywnego wniosku.
Co w przypadku jeśli w trakcie weryfikacji wniosku cena ulegnie zmianie?
scenariusz: 
-klient widzi cenę 900pln, wrzuca do koszyka, wybiera raty, 
-po 2 dniach wniosek jest zaakceptowany, 
-przed akceptacja sprzedawca zmienił cenę na 1000pln, 

Transakcja dochodzi do skutku w cenie z dnia akceptacji wniosku czy z dnia kiedy wrzucił produkt do koszyka?

**Comment by MaciejFrackowiak** [comment]
W opisanym przypadku transakcja nie dojdzie do skutku - warunki rat (cena przedmiotu) zmieniły się, zatem wniosek jest odrzucany i niezbędne jest ponowne wystąpienie z wnioskiem ratalnym.
