### ISSUE TITLE
Zestawienie transakcji dla wypłaty / przelewu

### ISSUE THREAD

**Issue by mack3d** [allegro/allegro-api#2913]
Dzień dobry,
gdzie / w jaki sposób / z pomocą której metody mogę otrzymać zestawienie transakcji wpłat od kupujących do których został wykonany przelew środków na konto firmowe.
W SOAP API  było to możłiwe z pomocą metody "doGetMyPayoutsDetails"

Maciej

**Comment by MaciejFrackowiak** [comment]
Szczegóły operacji płatniczych zapewnia [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory). Nie zwracamy tu jednak składowych danej wypłaty (podobnie jak na stronie WWW). Jeśli chcesz uzyskać takie informacje, możesz ustawić interesujący Cię przedział datowy i porównać, jakie wpłaty zostały wykonane do momentu zlecenia wypłaty.

**Comment by mack3d** [comment]
Metoda dostępna w RESTapi nie do końca zastępuje poprzednią funkcjonalność.
Proponuję dać możłiwość wyboru ram czasowych z dokładnością do godzin i minut, wtedy będzie można wygenerować zestawienie dla danego przelewu.
