### ISSUE TITLE
Smart i koszt transportu

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#2916]
Cześć, podczas pobierania zamówienia dostaję poniższą informację:
            "pickupPoint": null,
            "cost": {
              "amount": "16.00",
              "currency": "PLN"
            },
            "smart": true,

czyli klient wybrał dostawę ze smart więc powinien zapłacić 0 zł za transport, jednak wysyłany koszt transportu wynosi 16 zł  i został on doliczony do wartości zamówienia i klient to już opłacił.

Pytanie, jak takie coś obsłużyć?  

Jeżeli wszystko jest poprawnie (przypominam klient wybrał smarta a i tak zapłacił za koszt transportu!) to może nalezy zmienić nazwę smart! na np. fool! :)

**Comment by mlonc** [comment]
Dodam tylko ze kupujący posiada smarta i sprzedający także

**Comment by mlonc** [comment]
Dodam jeszcze jedną zabawną informację. Transakcja o której mowa zawierała zakup 3 towarów z 1 oferty, kupujący posiada smart tak jak sprzedający, kupujący wybrał dostawę wspierającą smart, smart został naliczony do 1 towaru a do pozostałych 2 towarów naliczono koszt transportu zgodny z cennikiem. Nie wydaje się to Wam bezsensu? Niezależnie od ilości paczek, gdy kupujący ze smartem wybierze płatność wspierającą smart to kupujący nie powinien mieć naliczanej dodatkowej opłaty za transport.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj id zamówienia, wówczas będę mógł się odnieść do tego konkretnego przypadku.

**Comment by mlonc** [comment]
e64969c2-5e10-11ea-b05e-5dcb7f03e93d

**Comment by MaciejFrackowiak** [comment]
Ten przypadek kwalifikuje się do opisanej w poście #2896 zmiany - w polu "cost.amount" zwracamy kwotę wysyłki, którą współfinansuje Allegro - taką kwotę dostał sprzedający na zrealizowanie przesyłki (kupujący nabył 3 sztuki, cennik mówił o wysyłce 2 sztuk w 1 paczce, zatem całość wysłana zostać powinna w 2 paczkach - max kwota dopłaty to 8 zł na paczkę, łącznie 16,00 zł).

**Comment by mlonc** [comment]
ok to dlaczego klient zapłacił za towar + koszt przesyłki?

Trochę się pogubiłem. Parametr smart  oznacza że kupujący wybrał transport wspierający smart czy też oznacza że kupujący posiada smart?

**Comment by MaciejFrackowiak** [comment]
Proszę zapoznaj się z [artykułem](https://allegro.pl/dla-sprzedajacych/allegro-smart-z-kurierem-warunki-finansowania-MMG0grZYeT0) - oznaczenie Smart mówi, że Kupujący skorzystał z takiej formy dostawy, która jest gwarantowana w ramach Smart. My w polu cost.amount zwracamy kwotę, którą dostaniesz od nas w ramach współfinansowania - maksymalnie 8 zł per 1 paczka. Tu były dwie paczki, czyli 16 zł. Tu mamy do czynienia z wysyłką kurierem, a nie paczkomatami, gdzie Sprzedający tylko dostaje kwotę za towar, a przesyłkę może nadać za darmo.

**Comment by mlonc** [comment]
dobra czyli wartość w pozycji cost.amount to wartość jaka ma znaleźć się na dokumencie sprzedaży + tą kwotę pokrywa kupujący tak?  Przynajmniej tak wyszło przy tym zamówieniu

**Comment by MaciejFrackowiak** [comment]
Ta kwota to pieniądze jakie Sprzedający dostaje na poczet wysyłki od Allegro (Kupujący de facto nie płaci, ponieważ jest to przekazywane w ramach Smart).

**Comment by mlonc** [comment]
Ok, podsumowując:
cost.amount - tyle sprzedający dostaje za przesyłkę
smart - parametr mówi nam czy kupujący ma smarta czy to że wybrał dostawę ze smartem?

**Comment by MaciejFrackowiak** [comment]
1) zgadza się;
2) smart: true - Kupujący skorzystał z opcji Smart.

**Comment by mlonc** [comment]
1. Ok, dziękuję za informację. rozumiem że wartość z cost.amount powinna pojawić się na dokumencie sprzedaży(?)
2. "smart: true - Kupujący skorzystał z opcji Smart." rozumiem że skoro skorzystał to ma smarta wykupionego, zgadza się? Co w przypadku gdy klient nie ma smarta a wybierze dostawę która obsługuje smart? Czy wtedy też parametr smart będzie miał wartośc true?

**Comment by MaciejFrackowiak** [comment]
1. Tak;
2. Tak, Kupujący musi mieć Smart by następnie pojawiło się w zamówieniu smart: true - jeśli nie ma Smart nie wybierze dostawy Smart'owej, pojawi się smart: false.

**Comment by mlonc** [comment]
ok dziękuję ale jeszcze Pana pomęczę :)
dlaczego na dokumencie sprzedaży musi pojawić się koszt transportu jeżeli kupujący zapłacił tylko za towary?

I ostatnie pytanie kupujący ma smart ale wybrał dostawę nie wspierającą smart czy parametr smart wyniesie wtedy true?

**Comment by MaciejFrackowiak** [comment]
1) Sprzedający otrzymał realne środki (warość z cost.amount), zatem powinny być one uwzględnione na dokumencie sprzedaży. 
2) Taka dostawa nie jest Smart, zatem będzie false.

**Comment by mlonc** [comment]
ok dziękuję i miłego dnia życzę
