### ISSUE TITLE
Kategoria zmieniła Id?

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#2917]
- [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Witam,
mam problem z ketegoriamii. 
Dostałem ofertę z id kategorii: 76378 
Ta kategoria z tego co widzę nie istnieje. Przekierowuje mnie na kategorię 305585. Czy zmieniacie Idki swoich kategorii? To jest dziwna sytuacja tym bardziej, że ta oferta przyszła do mnie 2 marca.
data: "2020-03-02 23:49:34.003978"
kategoria: "76378"	
id oferty: "8869653456"
W jaki sposób mam sobie z tym radzić skoro oferty były zapisane z kategoriami, których de fakto nie ma.

**Comment by MaciejFrackowiak** [comment]
Potwierdzam zmianę - dokładnie 3 marca 2020 usunęliśmy dotychczasowy podział kategorii Elektronika > RTV i AGD > Zasilanie > Baterie na podkategorie. Oferty trafiły do kategorii nadrzędnej - 305585.
Niezbędne jest odpytywanie [zasobów](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters) o aktualne drzewo kategorii i parametrów - tylko tak będziesz na bieżąco.

**Comment by artzie92** [comment]
Metoda doGetItemsInfo od razu ma zaktualizowana kategorię? Czy oferta ma wpisana caly czas stara kategorię?

**Comment by MaciejFrackowiak** [comment]
doGetItemsInfo zwraca id kategorii po zmianie.

**Comment by artzie92** [comment]
OK. Czy gdzieś udostępniacie change loga zmian kategorii? Często takie zmiany sa wykonywane?

**Comment by MaciejFrackowiak** [comment]
Kategorie i parametry podlegają ciągłym zmianom, dlatego niezbędne jest by na bieżąco dbać o ich aktualizację. Nie udostępniamy zasobu, w którym byśmy prezentowali zmiany.
