### ISSUE TITLE
Invalid upload image request. Please contact the author of the application.

### ISSUE THREAD

**Issue by juansiwei-li** [allegro/allegro-api#2918]
Hello, I returned an error when using / sale / images

{"errors":[{"code":"RequestNotReadable","message":"Unable to parse request body.","details":null,"path":null,"userMessage":"Invalid upload image request. Please contact the author of the application."}]}

this is my code : 

                public function uploadImg($img)
		{
			$header = array(
				'Content-Type:application/vnd.allegro.public.v1+json',
	                        'Accept:application/vnd.allegro.public.v1+json',
	                        'Authorization:Bearer '.$this->data['a_secretkey']
	                );
	                $url = 'https://upload.allegro.pl/sale/images';
	                $this->ch->setHeader($header);
	                $this->ch->setPost(true);
	                $this->ch->setUrl($url);
	                $this->ch->setPostData($img);
	                $content = $this->ch->execute();
	                return $content;
		}

$product->uploadImg('https://img-alt.joomcdn.net/8fe613fd7d1c31400492d46dda1998e4dba1a8cb_original.jpeg');

**Comment by MaciejFrackowiak** [comment]
If you want to upload a file in a binary format you have to change Content-Type to "image/jpeg" - please, look into our [documentation](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST).

**Comment by juansiwei-li** [comment]
I uploaded the image path, not the binary file

**Comment by MaciejFrackowiak** [comment]
Due to the large number of programming languages, we do not support each one. Perhaps one of the forum users has encountered a similar problem in the past and will be able to help you.
