### ISSUE TITLE
Produkty na Allegro Sandbox

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#2919]
Czy będą dostępne produkty dla kategorii z częściami samochodowymi? Potrzebujemy przetestować dokładnie tą funkcjonalność a nie mamy takiej możliwości przez brak produktów. Gdyby były dostępne chociaż 1-2 produkty, to by nam wystarczyło.
Czy planujecie rozszerzyć ilość produktów dostępnych na środowisku testowym?

**Comment by MaciejFrackowiak** [comment]
Taką sugestię mamy już na liście dot. rozwoju REST API - dodaję Twój głos.

**Comment by lukaszzborek** [comment]
Otwieram dość stary wątek, ale chciałbym dowiedzieć się jak się sprawy mają 😁
Nie ukrywam że gdyby nawet przykładowe, nieprawidłowe dane były w nich podane to bardzo by ułatwiło życie oraz testowanie niektórych rozwiązań

**Comment by MaciejFrackowiak** [comment]
Pamiętamy o tej kwestii - jesteśmy o krok bliżej, ale jeszcze produktów z motoryzacji nie ma na Sandbox. Jak tylko coś się zmieni, zamieszczę w tym poście info.

**Comment by MaciejFrackowiak** [comment]
Dzisiaj dodaliśmy trzy testowe produkty z kategorii Motoryzacja na Sandbox:

1) Klocki hamulcowe TRW COTEC GDB3482 TECDOC (id: ddf052fd-57d2-44d6-aa24-0ba811999982) 
2) Klocki hamulcowe BREMBO P 85 146X TECDOC (id: e8edc281-789d-4721-aa92-864770430e55)
3) Klocki hamulcowe 0 986 494 643 TECDOC (id: f1714e50-032b-4b77-902e-223e5a35f201)
