### ISSUE TITLE
Mapowanie metod dostaw GUID na FID - usługi dodatkowe

### ISSUE THREAD

**Issue by Greg0** [allegro/allegro-api#292]
Cześć,
Mam pytanie czy istnieje jakiś sposób pozwalający zmapować metody dostaw (poza porównaniem nazw), a konkretnie RESTowe GUID (akcja `/sale/delivery-methods`) na SOAPowy `shipmentId` uzyskiwany z metody  `doGetShipmentData`?
Dodatkowo interesuje mnie również utworzenie mapy GUID - FID uzyskiwany z `doGetSellFormFieldsForCategory`.

Pytanie wynika z posiadania już zbudowanych struktur obiektów allegro uzyskanych z SOAPa, a obecnie wdrażam istniejące w REST Usługi Dodatkowe, korzystające przy metodach dostawy tylko z GUID. https://developer.allegro.pl/news/2017-10-25-News_uslugi_dodatkowe/#6

Mam też pytanie czy planujecie umożliwić klientowi usuwanie swoich pakietów usług dodatkowych (ofc. pod warunkiem, że nie ma żadnych aukcji, które z nich korzystają itp)

**Comment by KrzysztofLukanowski** [comment]
Cześć,

w REST API wszystkie metody dostawy pobierzesz za pomocą GET na zasobie [/sale/delivery-methods](https://developer.allegro.pl/documentation/#/offer-management/get_sale_delivery_methods). Z kolei w WebAPI musisz pobrać wszystkie pola formularza dla danej kategorii za pomocą [doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782). W odpowiedzi znajdziesz wszystkie dostępne metody dostawy - każda metoda dostawy w WebAPI ma 3 pola, cena pierwszej sztuki, cena kolejnej sztuki oraz ilość w paczce.
