### ISSUE TITLE
Problem z pobraniem tokenu

### ISSUE THREAD

**Issue by stkds** [allegro/allegro-api#2920]
Witam,
Posiadamy Comarch e-sklep i niestety aplikacja nie może pobrać tokena. Przy logowaniu wyskakuje błąd "Nie można wyświetlić strony". Redirect_uri mamy ustawiony na "https://allegro.pl/auth/oauth/authorize"

**Comment by MaciejFrackowiak** [comment]
Adres przekierowania musi być dokładnie taki sam jak podany na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/) przy danej aplikacji.

**Comment by stkds** [comment]
Taki też jest. Otrzymuje błąd "5f8559ca2e7ea390"

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę dokładnie - komunikat "Nie można wyświetlić strony" to efekt różnicy w adresie, który znajduje się na stronie ustawień a danymi podanymi w aplikacji.
