### ISSUE TITLE
Zmiany Allegro - traktujmy poważnie integratorów

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2921]
Dzień dobry,
Od 6 kwietnia 2020 w większości kategorii dojdą nowe parametry obowiązkowe:  kod producenta, marka i model, cytat z informacji do sprzedawców:
(..)
Od 6 kwietnia jeśli nie uzupełnisz tych parametrów, nie wznowisz oferty, nie wystawisz nowej, ani nie wprowadzisz zmian w trwającej ofercie. **Obowiązkowe uzupełnienie parametrów dotyczyć będzie również ofert wystawianych przez API i Menedżera Sprzedaży.**
(..)

Co to oznacza dla integratorów:
- brak poprawnego działania automatów zmieniających ceny, stany magazynowe po 6 kwietnia dla wszystkich ofert, które tego nie mają 

Panowie traktujmy się poważnie, wszyscy robimy razem biznes i rzucacie kłody po nogi takimi zmianami, nie dając możliwości przejścia przez to w miarę automatycznie

Postuluję do tego czasu takie zmiany:
- uwolnienie zmiany stanu magazynowego od kompletności aukcji
- uwolnienie zmiany ceny od kompletności aukcji
- dodanie do API funkcji która pozwoli na zwrócenie informacji o braku odpowiednich parametrów dla aukcji (jest taka funkcja na interfejsie w sekcji Moje oferty po zalogowaniu do konta Allegro)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przedstawione przez Ciebie spostrzeżenia dotyczące API w kontekście zapowiedzianych zmian.

**Comment by yncki** [comment]
Dołączam nasze poparcie dla propozycji @SebastianOzdoba 
Przydałby się jakiś okres przejściowy. Rozwiązanie podobne do tego co ma np. ebay. 
Dostajemy tam jasną informację, że coś jest nie tak przez status błędu - warning zamiast tego co proponujecie - czyli fatal error.

**Comment by tomylee0** [comment]
I ja podłączę się do wątku żeby dodać znaczenia sprawie i podkreślić, że **uniemożliwienie zmiany ilości sztuk oraz ceny dla ofert które już zostały opublikowane** jest najłagodniej rzecz ujmując kłopotliwe dla sprzedającego. Działa to też na szkodę kupującego gdyż ten w takiej sytuacji często widzi nieaktualną ofertę.

**Comment by MaciejFrackowiak** [comment]
@yncki @tomylee0 Dziękuję za Wasze głosy - przekazuję je do osób odpowiedzialnych za zmianę.

**Comment by MaciejFrackowiak** [comment]
Ostatnie dni pozwoliły na nam na wypracowanie pierwszych rozwiązań - w odpowiedzi na Wasze zgłoszenia (za które raz jeszcze dziękuję):

- udostępniamy już teraz publicznie [plik](https://github.com/allegro/allegro-api/files/4338460/spis-kategorii-paramterow-obowiazkowych.xlsx) - zawiera on listę wszystkich parametrów (ze wskazaniem na kategorie, w których występują), które staną się obowiązkowe 6 kwietnia - możecie go wykorzystać w swoich aplikacjach oznaczając te wybrane parametry (co pozwoli Sprzedającym na określenie ich wartości przed wdrożeniem obowiązkowości);
- w najbliższych tygodniach udostępnimy endpoint, dzięki któremu pobierzecie listę parametrów, które w najbliższym czasie oznaczymy jako obowiązkowe.

Jednocześnie nadal pracujemy nad rozwiązaniami, które docelowo mają za zadanie ułatwienie Wam codziennej pracy z zarządzaniem ofertami poprzez Allegro REST API.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak  
My działamy online, budując formularze na podstawie tego co zwróci restAPI dla poszczególnych kategorii, nic nie przechowywujemy offline.
Prosimy o co innego, a dostarczacie zupełnie co innego. Postuluję o rzeczywiste zmiany, które opisałem powyżej. 
Dajcie przynajmniej ostatni punkt, jak pisałem na GUI to jest, idźcie do tego zespołu i weźcie know how a potem zróbcie endpoint do tego.
Mam wrażenie, że pracujecie w różnych firmach, nie ma przepływu wiedzy miedzy zespółem X a Y, jeden robi coś a drugi który odpowiada za podobne rzeczy tylko na poziomie API tego nie wdraża
