### ISSUE TITLE
INVALID_JSON

### ISSUE THREAD

**Issue by juansiwei-li** [allegro/allegro-api#2922]
hi
when i used  /sale/offers  Create a draft offer 

{"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Invalid request."}]}

Here are 1 json examples that we get the specific error

`
{
    "additionalServices": null,
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "5318db62-ab1f-43a1-89f7-2e2c9c79179c"
        },
        "returnPolicy": {
            "id": "e13714ee-4948-4960-ad71-c544856edf72"
        },
        "warranty": null
    },
    "attachments": [],
    "category": {
        "id": "251128"
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "contact": null,
    "createdAt": "2020-03-06T12:44:00Z",
    "delivery": {
        "additionalInfo": null,
        "handlingTime": null,
        "shipmentDate": null,
        "shippingRates": null
    },
    "description": {
        "sections": {
            "items": [
                {
                    "type": "string",
                    "content": "<p>Rozmiar Obuwie: 43\n\nproducent: Nike\nmodel: AH8050-007\nsk\u0142ad surowcowy: sk\u00f3ra\/tekstylia\nlogo producenta po boku, na j\u0119zyku oraz z ty\u0142u\ngumowa podeszwa logowana mark\u0105\nobuwie wi\u0105zane na sznurowad\u0142a\nzapakowane w oryginalny karton<p>"
                }
            ]
        }
    },
    "ean": null,
    "external": null,
    "id": null,
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/s512\/037a2d\/2c07e94c44ea9cf8818bf40b1c20\/Buty-meskie-Nike-Air-Max-270-AH8050-007-R43"
        }
    ],
    "location": {
        "city": "shenzhenshi",
        "countryCode": "CN",
        "postCode": "518000",
        "province": null
    },
    "name": "Buty m\u0119skie Nike Air Max 270 AH8050-007 R43",
    "parameters": [
        {
            "id": "11323",
            "valuesIds": "11323_1",
            "values": "Nowy",
            "rangeValue": null
        }
    ],
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "product": null,
    "promotion": {
        "bold": false,
        "departmentPage": false,
        "emphasized": false,
        "emphasizedHighlightBoldPackage": false,
        "highlight": false
    },
    "publication": {
        "duration": null,
        "endingAt": null,
        "startingAt": null,
        "status": "ACTIVE",
        "endedBy": null,
        "republish": false
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "300",
            "currency": "PLN"
        },
        "minimalPrice": null,
        "startingPrice": null
    },
    "sizeTable": null,
    "stock": {
        "available": "100",
        "unit": "UNIT"
    },
    "updatedAt": "2020-03-06T12:44:00+0800Z",
    "validation": {
        "errors": [],
        "validatedAt": "2020-03-06T12:44:00+0800Z"
    }
}
`

**Comment by MaciejFrackowiak** [comment]
As I see your description is incorrect - in some places you used "{}" instead "[]".
Sections should look:

`{
    "sections": [
        { section1 },
        { section2 },
         ...
        ]
}`

and items:

`{
      "items" : [
     { item1 }
     ]
}`

Please, check [our tutorial](https://developer.allegro.pl/en/sale/#step-5-description).

**Comment by juansiwei-li** [comment]
Submit after modification
     {
		"name": "Nike Air Max 270 AH8050-007 R43",
		"category": {
			"id": "251128"
		},
		"parameters": [
			{
			       "id": "11323",
				"valuesIds": ["11323_1"],
				"values": ["Nowy"],
				"rangeValue": null
			}
		],
		"description": {
			"sections": [
				{
					"items": [
						{
							"type": "TEXT",
						        "content": "<p>Rozmiar Obuwie: 43\n\nproducent: Nike\nmodel: AH8050-007\nsk\u0142ad surowcowy: sk\u00f3ra\/tekstylia\nlogo producenta po boku, na j\u0119zyku oraz z ty\u0142u\ngumowa podeszwa logowana mark\u0105\nobuwie wi\u0105zane na sznurowad\u0142a\nzapakowane w oryginalny karton<p>"
					         }
					 ]
				}
			]
		},
		"sellingMode": {
			"format": "BUY_NOW",
			"price": {
			         "amount": "300",
			         "currency": "PLN"
		          },
		          "minimalPrice": null,
		          "startingPrice": null
		},
		"payments": {
			"invoice": "NO_INVOICE"
		},
		"location": {
			"city": "shenzhenshi",
			"countryCode": "CN",
			"postCode": "518000",
			"province": null
		},
		"external": null,
		"contact": null,
		"images": [
			{
			       "url": "https://a.allegroimg.com/s512/037a2d/2c07e94c44ea9cf8818bf40b1c20/Buty-meskie-Nike-Air-Max-270-AH8050-007-R43"
			}
		],
	}

error:
    {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by MaciejFrackowiak** [comment]
You received error because JSON is invalid --> please, delete last coma from your draft.
After it, you will receive another error - your description has HTML subset which is also invalid - you can use only these HTML tags:

- h1 - title
- h2 - subtitle
- p - paragraph
- ul - unordered (bulleted) list
- ol - ordered list
- li - list item
- b - bold

**Comment by juansiwei-li** [comment]
thank you
