### ISSUE TITLE
Checkout-forms

### ISSUE THREAD

**Issue by creative-pl** [allegro/allegro-api#2923]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, od godziny jest problem z eventem /checkout-forms, api nie zwraca formularzy zakupow.

**Comment by esprzedaz** [comment]
U nas tak samo.

**Comment by przemoo83** [comment]
Sandbox też się posypał. Tak z ciekawości. Supportuje ktoś to API przez weekend? Wydaje mi się że nie ale mogę się mylić...

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, w sobotę ok. godz. 16 pojawiły się problemy ze spływaniem zamówień. Na szczęście podjęte działania szybko opanowały sytuację i już przed godz. 18 wszystko wróciło do normy. Przepraszam za niedogodności.

@przemoo83 Czuwamy nad funkcjonalnościami i ich działaniem również w weekendy.
