### ISSUE TITLE
Brak informacji o nowych zamówieniach

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#2924]
Jak w temacie brak informacji o nowych zamówieniach, pozostałe funkcje działają,
Prosze o informacje czy sa opóżnienienia

**Comment by mojosoft** [comment]
Jest postęp zaczynają sie przetwarzać około 90 minut opóźnienia

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, w sobotę ok. godz. 16 pojawiły się problemy ze spływaniem zamówień. Na szczęście podjęte działania szybko opanowały sytuację i już przed godz. 18 wszystko wróciło do normy. Przepraszam za niedogodności.
