### ISSUE TITLE
Skąd pobrać id dostępnych filtrów?

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2925]
Pytanie dotyczy zasobu public offer information > Search offers:
![image](https://user-images.githubusercontent.com/26189632/76161861-a5254480-6137-11ea-887c-a0983d167173.png)
Możliwe jest wyszukiwanie przy pomocy filtrów o określonym id.
Skąd mogę pobrać id wszystkich dostępnych pól po których można wyszukiwać?

**Comment by MaciejFrackowiak** [comment]
Musisz przede wszystkim na wstępie podać minimum jedną wartość dla wyszukiwania:

- category.id - numer ID kategorii
- phrase - fraza
- seller.id - numer ID sprzedawcy

Gdy to określisz po skorzystaniu z zasobu otrzymasz listę wyników, a pod nią listę dostępnych filtrów dla danego, wybranego wyszukiwania.

Zerknij również na [nasz poradnik](https://developer.allegro.pl/listing/) dotyczący wyszukiwania ofert.
