### ISSUE TITLE
Filtrowanie ofert po parametrze zawierającym wartość true/false

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2926]
Chciałbym uzyskać następujący efekt korzystając z zasobu public offer information > search offers:
Zapytanie: czerwona sukienka
Oferty TYLKO: SuperSeller
ORAZ
Oferty TYLKO: Różne od SuperSeller
To samo dotyczy ofert SMART (czyli: SMART oraz różne od SMART)

O ile wiem jak odwołać się do obiektu filters, który pozwala na pobranie ofert zawierających status super sprzedawcę oraz smart, o tyle nie wiem jak odwołać się do wartości przeciwstawnej (tj. wszystkie oferty które NIE zawierają tych statusów (i tylko takie)).

Z góry dziękuję za pomoc!

**Comment by MaciejFrackowiak** [comment]
Wyszukiwarka w REST API jest odzwierciedleniem wyszukiwarki z serwisu WWW - tam spośród dostępnych opcji filtrowania można wybrać tylko wartości "true" - oferta ma dany filtr i dlatego korzystając z GET /offers/listing w opcjach filtrowania wybierając te filtry otrzymujesz domyślnie je z wartością "true".
Jeżeli nie skorzystasz z danego filtra otrzymasz łączne wyniki, czyli "false" + "true".

**Comment by 4sp3ll** [comment]
Dziękuję za odpowiedź, rozumiem.
Czy można się odwołać bezpośrednio przez API do parametrów obiektu seller, tak jak w seller.id={ID}?
Na przykład: [...]&seller.superSeller=true?
![image](https://user-images.githubusercontent.com/26189632/76216398-d32a8780-6210-11ea-903f-6480e41fbb61.png)

**Comment by MaciejFrackowiak** [comment]
Nie, taki filtr nie jest dostępny.
