### ISSUE TITLE
Błędy związane z wygenerowaniem tokenu

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2927]
Od 7 marca od godz. 18:00 otrzymuje błąd najpierw:

`{"error":"invalid_grant","error_description":"Invalid refresh token: XXXXXXXX","http_code":400}`

A teraz:

`{"error":"invalid_token","error_description":"Cannot convert access token to JSON","http_code":401}`

Proszę o szybką odpowiedź co może być tego przyczyną. Nigdy wcześniej to nie występowało.

**Comment by PrzemyslawLukanowski** [comment]
Pierwszy błąd oznacza, że chcesz odświeżyć token za pomocą nieprawidłowego refresh tokena. Taka sytuacja może mieć miejsce, gdy:
- minie czas ważności dla refresh tokena;
- refresh token zostanie wykorzystany już wcześniej, co wygeneruje nową parę access + refresh, stare tokeny w tym momencie tracą ważność;
- użytkownik zmieni hasło;

Drugi błąd oznacza, że używasz nieważnego access token lub tokena z sandboxa na produkcji.

Przeslij proszę przykładowe logi (request i respone w formacie cURL) za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w zgłoszeniu dopisz GitHub #2927. Wtedy będziemy w stanie wskazać, co dokładnie wydarzyło się w Twoim przypadku.

**Comment by pietrach** [comment]
Wygenerowałem wszystkie tokeny od nowa i poszło. Pierwszy raz mi się taka sytuacja zdarzyła. Użytkownik nie miał zmienianego hasła.

**Comment by Troom** [comment]
Potwierdzam taki błąd, napewno na Sandboxie coś takiego występuje co jakiś czas.
I właśnie dwie godziny temu miałem ten sam błąd.

**Comment by PrzemyslawLukanowski** [comment]
@Troom Jeżeli zauważysz taki błąd, przeslij proszę przykładowe logi przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w zgłoszeniu dopisz GitHub #2927. Będziemy to analizować.

-----
[Jak oceniasz API Allegro? ](https://github.com/allegro/allegro-api/issues/2904) - weź udział w naszej ankiecie
