### ISSUE TITLE
Błąd 500 /sale/offers

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#2928]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próba pobrania ofert
`
GET https://api.allegro.pl/sale/offers
Authorization: Bearer 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
`

Zwrotnie
Response status code: 500
`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}`

Na koncie testowym nie mogę też dodać żadnych ofert przez portal. Mieli długo potem staje na białym ekranie

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem działanie zasobu GET /sale/offers, przy każdym zapytaniu otrzymuję prawidłowe wyniki. Z jakiego rodzaju autoryzacji korzystasz? Upewnij się, że nie jest to [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Błąd 500 udało mi się odtworzyć właśnie w przypadku, gdy wybrałem ten rodzaj autoryzacji. 
Nie udało mi się również powtórzyć błędu z wystawieniem oferty - spróbuj proszę usunąć ciasteczka.

**Comment by DanielMiara** [comment]
Tak, używam https://allegro.pl/auth/oauth/token?grant_type=client_credentials
Owszem dopiero zaczynam ale gdy odwołuje się do https://api.allegro.pl/sale/offer-events

Otrzymuję
`
object(stdClass)#1 (1) {
  ["offerEvents"]=>
  array(0) {
  }
}
`

Więc wnoskuję, że autoryzacja działa prawidłowo

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku zawsze otrzymasz pustą tablicę, ponieważ autoryzacja client_credentials nie posiada kontekstu użytkownika. W najbliższym czasie zmienimy odpowiedź na inny status. 
Aby otrzymać prawidłową odpowiedź z GET /sale/offers, skorzystaj z autoryzacji [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow). W naszej [dokumentacji znajdziesz odpowiednie oznaczenie](https://developer.allegro.pl/documentation/#section/Authentication) dla każdego zasobu i wymaganego rodzaju autoryzacji:
- bearer-token-for-user - code lub device,
- bearer-token-for-application - client credentials.

-----
[Jak oceniasz API Allegro ?](https://github.com/allegro/allegro-api/issues/2904) - weź udział w naszej ankiecie

**Comment by DanielMiara** [comment]
Jak to na początku jestem trochę zdezorientowany. Wymacz mi moje pytania.

1. dodałem aplikacje do konta typ DEVICE + device_code
2. pozyskalem access_token i token_type

Gdy staram się przy użyciu tego tokena pozyskać dane o ofertach mam info, że token wygasł.
Czy przy "device" musze pozyskująć token zawsze używać 
-H 'Authorization: Basic base64(client_id:client_secret)'

**Comment by PrzemyslawLukanowski** [comment]
> Czy przy "device" musze pozyskująć token zawsze używać 
> -H 'Authorization: Basic base64(client_id:client_secret)'

Tak, zawsze musisz przekazać takie dane.

> Gdy staram się przy użyciu tego tokena pozyskać dane o ofertach mam info, że token wygasł.

Prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Taką sytuacja może wystąpić, gdy:
- używasz nieprawidłowego access tokena (np. zawiera dodatkowe znaki);
- wygasł termin jego użyteczności;
- access token został odświeżony za pomocą refresh_tokena - wtedy w odpowiedzi otrzymujesz nową parę, a stare tokeny tracą ważność;
- zmienisz hasło użytkownika.

-----
[Jak oceniasz API Allegro ?](https://github.com/allegro/allegro-api/issues/2904) - weź udział w naszej ankiecie

**Comment by DanielMiara** [comment]
Wysłałem

**Comment by PrzemyslawLukanowski** [comment]
Czy w wysłanym zgłoszeniu dopisałeś numer ticketa GitHub #2928? Jeśli nie, prześlij proszę dane ponownie.

**Comment by DanielMiara** [comment]
Nie napisałem. Już wysyłam

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem Twój plik. Niestety na temat samego kodu w języku PHP nie mogę pomóc - ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Jednak dane zawarte w pliku pomogły mi odnaleźć konkretne wywołania i przyczyny błędów:

2020-03-09 12:58:28 - GET /sale/offers - odpowiedź 401 - tym przypadku otrzymałeś błąd, ponieważ jako access tokena użyłes refresh tokena.

2020-03-09 12:58:44 - GET /sale/offers - odpowiedź 200 - użyłeś prawidłowego access tokena.

2020-03-09 13:00:24 - GET /sale/offers - odpowiedź 500 - w parametrach przekazałeś grant_type=client_credentials, czyli autoryzacja bez kontekstu użytkownika, której nie możesz użyć przy tym zasobie.

**Comment by DanielMiara** [comment]
Udało się więc myśle, że temat zamknięty. Dziękuję
