### ISSUE TITLE
Message = Parameter (237194) is not excepted.

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#2929]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem testowym

Podczas próby wystawienia aukcji na sandbocie, zgodnie z nowymi wytycznymi które mają obowiązywać od 6 kwietnia, otrzymuje konunikat błędu:
message = Parameter (237194) is not excepted.
Prosiłbym o dodanie parametru nazwy dla wszystkich kategorii związanych z MTG:
        "Bezkolorowe": "261207",
        "Artefakty": "6089",
        "Białe": "6090",
        "Czarne": "6091",
        "Czerwone": "6092",
        "Lądy": "6093",
        "Multikolor": "6094",
        "Niebieskie": "6095",
        "Zielone": "6096",
        "Zestawy kart": "6097",
        "Pozostałe": "6087",

I dodatkowo jeszcze dopytam, co wpisywać w samej nazwie? Nazwe konkretnej karty, czy poprostu "karta MTG"?  Pytam, bo nie do końca rozumiem jaki jest sens tego rozwiązania.

Na koniec, przy okazji jak już pisze posta to prosiłbym o dodanie do kategorii pozostałe (6087) parametru kondycja(11326) i rzadkość (5175)- problem pojawia się na środowisku produkcyjnym i testowym.

**Comment by PrzemyslawLukanowski** [comment]
Problem z brakiem parametrów przekazałem do odpowiedniego zespołu. Jako wartość wpisz to, co najbardziej pomoże zidentyfikować ten przedmiot jako określony, np. "Wizards of the Coast".

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę podpięliśmy parametr 237194 pod wymienione kategorie, poza"Bezkolorowe": "261207", która nie jest dostępna na środowisku Sandbox.
