### ISSUE TITLE
REST API - Przesyłki Smart

### ISSUE THREAD

**Issue by arekk-collab** [allegro/allegro-api#2932]
Dzień dobry.
Czy REST API zwraca ID metod dostawy dla przesyłek Smart?

**Comment by PrzemyslawLukanowski** [comment]
Dostępne metody dostawy pobierzesz za pomocą [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET). W przypadku zamówień, w zasobie [GET /order/checkout-forms/{checkoutFormId}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), zwracamy informację o: 
- skorzystaniu przez kupującego z opcji smart - w polu delivery.smart.
- wybranej przez kupującego metodzie dostawy - w polu delivery.method.id,
