### ISSUE TITLE
Chciałbym odczytać ilość sprzedanych produktów (popularity) z mojej oferty (/sale/offers/{offerId})?

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#2933]
W przeciwieństwie do /offers/listing, w którego wynikach obiekt sellingMode ma pole popularity, w /sale/offers/{offerId} tego pola ma. Ktoś zapomniał? Aby poznać popularity, muszę więc odszukać moją własną aukcję z publicznych ofert (/offers/listing), a to wcale nie jest takie proste, bo np brakuje funkcji odwołania się do konkretnego id publicznej oferty. 

NIby taka drobna informacja, a jak trudno ją uzyskać :(

Da się coś z tym zrobić?

Sergiusz

**Comment by kfijalko** [comment]
popularity to liczba unikatowych klientów z ostatnich 30 dni

**Comment by sbrzezin** [comment]
Źle się wyraziłem, ale chodzi mi właśnie o popularity i brak informacji na ten temat w /sale/offers/{offerId}.

**Comment by PrzemyslawLukanowski** [comment]
Informację na temat sprzedanych przedmiotów z ostatnich 30 dni w GET /sale/offers znajdziesz w polu stock.sold.

**Comment by sbrzezin** [comment]
Wg. dokumentacji dla stock są tylko atrybuty available i unit. Nie widzę sold. Czy to nieudokumentowana funkcjonalność?

**Comment by PrzemyslawLukanowski** [comment]
Atrybuty, o których piszesz, dostępne są dla /sale/offers/{offerId}, stock.sold znajdziesz w /sale/offers lub dla konkretnej oferty /sale/offers?offer.id={id}

**Comment by sbrzezin** [comment]
Podsumowując:

sellingMode.popularity:
- jest tylko w /offers/listing
- nie ma w /sale/offers/{offerId} ,o którym autorzy dokumentacji piszą "Get all fields of the particular offer" oraz nie ma w /sale/offers (choć w obu jest obiekt sellingMode)

stock.sold
- jest tylko w /sale/offers
- nie ma w /sale/offers/{offerId} ,o którym autorzy dokumentacji piszą "Get all fields of the particular offer" oraz nie ma w /offers/listing (choć w obu jest obiekt stock)
 
Mega niekonsekwencja, a najbardziej boli to, że tam gdzie powinniśmy odczytać wsyzstko (/sale/offers/{offerId}), nie możemy odczytać ani jedno, ani drugie.

**Comment by PrzemyslawLukanowski** [comment]
Wspomniane zasoby są odzwierciedleniem odpowiednich zakładek z frontu. GET /sale/offers/{offerId} zawiera wszystkie informacje potrzebne do wystawienia oferty, widoczne po wybraniu "Akcje -> Edytuj" w zakładce [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty). Dane o liczbie sprzedanych sztuk byłyby w tym przypadku informacją nadmiarową. Natomiast sama zakładka [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty) to właśnie odpowiednik GET /sale/offers, w obu miejscach zwracamy stock.sold. Konsekwencja jest zachowana względem funkcjonalności ze strony internetowej.
