### ISSUE TITLE
Offer variants

### ISSUE THREAD

**Issue by kislukacs** [allegro/allegro-api#2935]
Hi,

which method contains offer's variants id? For example if I need color variants of this [t-shirt](https://allegro.pl/oferta/t-shirt-meski-4f-tsm004-aw19-antracyt-xxl-8399641847), how can I get them? WebAPI's DoShowItemInfoExt method doesn't contains these information.

Thanks!

**Comment by PrzemyslawLukanowski** [comment]
You can use [GET /sale/offer-variants](https://developer.allegro.pl/documentation/#operation/getVariantSets)?user.id=user.id to retrieve multi-variant offers you created using current account. Provide user ID in user.id. You can also download an multi-variant offer by specify parameter **query** - name of the multi-variant offer or one of the IDs, which is included in the multi-variant offer.

**Comment by kislukacs** [comment]
Yes, but this works only for my offers. What about other seller's products?

**Comment by PrzemyslawLukanowski** [comment]
You can retrieve variants ids and different variants of product only for offers which you created.

**Comment by kislukacs** [comment]
Are you planning to create methods for this information? It would be great!

**Comment by PrzemyslawLukanowski** [comment]
Right now we don't have plans to introduce such functionality. More information about our future resources can be found in [our schedule](https://developer.allegro.pl/en/schedule/).
