### ISSUE TITLE
Dokumentacja - create draft

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#2936]
![image](https://user-images.githubusercontent.com/1530496/76364240-f6def200-6324-11ea-9e07-b6aa45df161d.png)

kiedy 200 kiedy 201 ?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku prawidłowej odpowiedzi zawsze otrzymasz status 200. W najbliższym czasie zaktualizujemy naszą dokumentację.
