### ISSUE TITLE
Smart z kurierem

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#2937]
Dzień dobry

Czy jest możliwość pobrania informacji, czy sprzedawany przedmiot jest dostępny w opcji "Allegro Smart z kurierem" ?
Lub też czy można przefiltrować oferty pod kątem tej opcji, tak jak to można zrobić w przypadku ofert "Smart" tylko konieczne "Smart z kurierem" ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz to zrobić za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Oprócz [obowiązkowych parametrów](https://developer.allegro.pl/listing/) przekaż także &option=SMART&deliveryMethod=5b445fa0580ce26bb2f99602, np. 
GET /offers/listing?phrase=szukany produkt&option=SMART&deliveryMethod=5b445fa0580ce26bb2f99602

**Comment by Mihalis76** [comment]
Dziękuję.

Ale czegoś tu nie ogarniam. 
Skąd wartość 5b445fa0580ce26bb2f99602? GET /sale/delivery-methods nie zwraca takiej wartości.

Rozumiem, że mam wyszukać oferty, gdzie jest opcja SMART dla konkretnego kuriera, np Pocztex Kurier 48 ma id f7e952b5-9ae8-40a9-90dd-e71ab9da29dd

Próbuję wyszykiwać: 
&option=SMART&deliveryMethod=5b445fa0580ce26bb2f99602 - nie wyszukał niczego
&option=SMART&deliveryMethod=f7e952b5-9ae8-40a9-90dd-e71ab9da29dd - nie wyszukał niczego
&option=SMART&delivery.shippingRates.id=f7e952b5-9ae8-40a9-90dd-e71ab9da29dd - wyszukał oferty, które mają dostawę Pocztex Kurier 48, bez znaczenia czy ta konkretna przesyłka ma Smart czy nie

**Comment by PrzemyslawLukanowski** [comment]
W przypadku wyszukiwarki na stronie, jak i GET /offers/listing, filtry dla metod dostawy nie są identyczne z identyfikatorami metod dostawy. Znajdziesz je na końcu wywołania zasobu:
```
        {
            "id": "deliveryMethod",
            "type": "MULTI",
            "name": "sposoby dostawy",
            "values": [
                {
                    "value": "5b445fa0580ce26bb2f99602",
                    "name": "Kurier",
                    "count": 300,
                    "selected": true
                },
                {
                    "value": "5b445fe6580ce26bb2f9960a",
                    "name": "Paczkomaty InPost",
                    "count": 468,
                    "selected": false
                },
                {
                    "value": "5b446004580ce26bb2f9960c",
                    "name": "Odbiór w punkcie",
                    "count": 294,
                    "selected": false
                },
                {
                    "value": "5b446013580ce26bb2f9960e",
                    "name": "List",
                    "count": 148,
                    "selected": false
                },
                {
                    "value": "5b445fd9580ce26bb2f99608",
                    "name": "Kurier wieczór",
                    "count": 0,
                    "selected": false
                },
                {
                    "value": "5b446031580ce26bb2f99610",
                    "name": "Paczka",
                    "count": 0,
                    "selected": false
                },
                {
                    "value": "5b44606c580ce26bb2f99616",
                    "name": "Ekspresowa dostawa",
                    "count": 0,
                    "selected": false
                },
                {
                    "value": "5b446044580ce26bb2f99612",
                    "name": "Odbiór osobisty",
                    "count": 0,
                    "selected": false
                },
                {
                    "value": "5b44605c580ce26bb2f99614",
                    "name": "Przesyłka elektroniczna",
                    "count": 0,
                    "selected": false
                }
            ]
        },
```

Przykład, którego użyłem, jest tożsamy z poniższym zachowaniem na stronie:
![Screenshot_25](https://user-images.githubusercontent.com/51473661/76404791-5f5ebb00-6387-11ea-92c9-b19ab6472e7b.png)

**Comment by Mihalis76** [comment]
Dziękuję, działa!
