### ISSUE TITLE
Nowe parametry obowiązkowe - Kod producenta, Marka i Model - braki

### ISSUE THREAD

**Issue by grzesiekm86** [allegro/allegro-api#2938]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W otrzymanym mailu informujecie że pola w wybranych kategoriach będą obowiązkowe.
Pobierałem przed chwilą wymagane pola na środowisku testowym jak i produkcyjnym.
Według otrzymanego xls'a np. dla kategorii Dom i Ogród - Meble - Sypialnia - Szafy powinny być pola Kod produktu, Marka, Kolekcja. Na produkcji mam dostęp do pól Marka, Kod produktu ale już Kolekcji nie ma. Na sandboxie jest jeszcze gorzej - jest pole Producent zamiast Marka, ale ani Kodu produktu ani pola kolekcji nie ma. 
Podobna sytuacja jest na innych kategoriach (praktycznie na każdej związanej z meblami, które sprawdzałem).

Wymagacie, aby pola były dostępne ale faktycznie to nawet ich nie ma.

Prośba o rozwiązanie problemu

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie. Weryfikujemy ten temat, uzupełnimy brakujące wartości.

**Comment by kormoranmen** [comment]
Dzień dobry,

chciałem zapytać kiedy można spodziewać się wprowadzenia tych pól?

Pozdrawiam

**Comment by grzesiekm86** [comment]
Witam serdecznie,

chciałem zapytać kiedy można spodziewać się wprowadzenia tych pól.

**Comment by PrzemyslawLukanowski** [comment]
Na produkcji wszystkie pola są już zgodne z danymi z pliku. W przypadku kategorii  Dom i Ogród - Meble - Sypialnia - Szafy nie widnieje parametr Kolekcja. 
Pracujemy nad uzupełnieniem parametrów na Sandboxie.
