### ISSUE TITLE
Device Flow - wygasł token

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#2939]
Witam.

Mieliśmy przypadek, że dla konta opartego o autoryzację Device Flow (Client Id 52ae0a3ee4e749729e84cc1b5f7d4f02) wygasł nam Refresh Token, który w teorii wygasnąć nie powinien. Spowodowało to zerwanie komunikacji z API dotyczącej obsługi całego konta, o czym dowiedzieliśmy się dopiero na następny dzień.
Konto na ten typ autoryzacji było przepięte pod koniec stycznia wraz z innymi kontami na których zachodzą te same procesy (lecz w mniejszym stopniu niż wymienione konto) i tam takiego problemu nie było.
Czy można poznać przyczynę dlaczego token wygasł i musieliśmy przegenerować Refresh Token  ręcznie?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi:
- 2020-03-10 08:28:12.750 - została wygenerowana para access + refresh token,
- 2020-03-10 20:28:18.970 - refresh token zostaje użyty, w związku z czym wcześniejsza para traci ważność, a wygenerowana zostaje nowa,
- dalej w logach widzę kolejne próby odświeżenia tokena za pomocą starego, nieaktywnego refresh tokena.

**Comment by bacok** [comment]
Ok, dziękuję za informację.

**Comment by j4r3kb** [comment]
Mam pytanie jak się zachowuje API w następującym przypadku:
* system użytkownika API potrafi działać wielowątkowo
* zostają wysłane prawie jednocześnie dwa identyczne requesty o odświeżenie Access Token (A) przy pomocy Refresh Token (B), różnica w czasie jest powiedzmy rzędu mili/mikrosekund

Co teraz się stanie po stronie API? Osobiście wyobrażam sobie dwa scenariusze:
1. API rozpoznaje oba requesty jako prawidłowe gdyż zapisanie nowych tokenów po stronie API nie zdążyło się jeszcze wykonać. W efekcie oba procesy otrzymują parę nowych Tokenów, ale każdy z nich inną (w momencie requestu tokeny A i B były aktualne).
2. API jest w stanie poprawnie obsłużyć taką sytuację i pierwszy request otrzymuje nową parę a drugi błąd wskazujący na użycie niepoprawnych tokenów A i B do odświeżenia.

Oczywiście "pierwszy" request (od strony klienta) nie musi wcale dotrzeć/zostać wykonany jako pierwszy, wiadomo mamy sporo zmiennych warunków, t.j. delay na sieci, czas wykonywania kodu po obu stronach (wielowątkowo), itd.
Chodzi tutaj o typowy race condition, proszę szczegółową odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
@j4r3kb Weryfikuję taki przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@j4r3kb W zaprezentowanym przez Ciebie scenariuszu zachowanie systemu na chwilę obecną będzie niedeterministyczne. W odpowiedzi dla każdego requestu możesz otrzymać nową parę tokenów (z których każda będzie działać prawidłowo) lub jeden z requestów zakończy się kodem błędu 400. Nie ma pewności, że zachowanie systemu w przyszłości nie ulegnie zmianie. Dodatkowo próby tworzenia race condition traktujemy jako zjawisko niepożądane, które może prowadzić do zablokowania danej aplikacji.

**Comment by j4r3kb** [comment]
Dziękuję za szczegółową odpowiedź. Race condition nie jest u nas celowe. Zadałem pytanie trochę z ciekawości. Będziemy implementować zmiany aby wykluczyć race condition.
