### ISSUE TITLE
Przestańcie rozwalać to co działało - blokada edycji zdjęć ??

### ISSUE THREAD

**Issue by KoniecWebAPI-KoniecAllegro** [allegro/allegro-api#294]
Jak nie potraficie skutecznie i nieinwazyjnie nanosić na WebAPI przeróżnych ograniczeń i blokad (edycji starego rekordu opisowego), to lepiej tego nie róbcie w ogóle...
http://allegro.pl/jbl-propond-spring-m-6l-pokarm-na-wiosne-premium-i6780975392.html - tu są edytowalne zdjęcia (stary opis)
http://allegro.pl/jbl-propond-spring-m-1-1kg-pokarm-na-wiosne-jakosc-i6780976586.html - a tutaj już NIE można ??
W sposób całkiem przypadkowy lecą błędy, które są przewidziane dla próby edycji pola starego opisu:
ERR_ILLEGAL_OFFER_UPDATE_EXCEPTION_DESCRIPTION_ID => Nie możesz edytować starego opisu...
p.s.
Nie będzie żadnych paczek XML, powyższe wystarcza do naprawienia tego co schrzaniliście.

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem Twoje pytanie i problem zgodnie ze wcześniejszymi zapowiedziami od 22 maja konta firmowe nie mogą już edytować starego opisu, z końcem czerwca wszystkie oferty w serwisie będą musiały już być zgodne z nowymi zasadami opisu ofert. Więcej na ten temat [tutaj](https://allegro.pl/dla-sprzedajacych/harmonogram-kiedy-wprowadzamy-nowe-zasady-w-ofertach-mGKad6kyyH6).

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
Uo matko... Blokując edycję FID-24 spowodowaliście przypadkowe blokady - ale przy próbie edycji innych FID'ów, które miały być nadal edytowalne - co tu jest niezrozumiałe ??

**Comment by PawelTaberski** [comment]
Jakie fid-y zauważył Pan że są obecnie nieedytowalne przez tą zmianę? Do zweryfikowania zgłoszenia potrzebowałbym pełnego requesta i responsa w formacie XML. Prosiłbym go podesłać przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=1436f902-6fd9-420f-9e19-321b684cc8df). W treści proszę wpisać, że przesyła go Pan na potrzeby zweryfikowania zgłoszenia na GitHub, a następnie wkleić tutaj numer ticketa

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
Skoro piszę od początku o problemach z edycją zdjęć, to oczywiste chyba jest, że chodzi o FID'y z zakresów: [16-23] oraz [342-349]. W podanym na początku przykładzie:
http://allegro.pl/jbl-propond-spring-m-1-1kg-pokarm-na-wiosne-jakosc-i6780976586.html
- blokowane są też inne rzeczy, choćby edycja parametrów / warunków oferty...
Najzwyczajniej trzeba odświeżyć rekordy na całym użytkowniku (ID: 5715233) i podobnie jest na drugim koncie (ID: 7219098). Dosyłanie XML'i jest bez sensu, bo są na 100% poprawne, a tylko komunikaty błędów są zwyczajnie NIEADEKWATNE do zlecanych akcji, proszę sobie zasymulować próbę edycji jednego zdjęcia i wszystko się wyjaśni.

**Comment by PawelTaberski** [comment]
Tak jak wcześniej napisałem niezbędne do zweryfikowania tego zgłoszenia jest podesłanie requeta i responsa w formacie XML.
