### ISSUE TITLE
Problem z wysyłką zdjęć gdzie w linku jest adres IP

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#2940]
Mam taki problem, że wywołania metody wysyłającej zdjęcia otrzymuje taki błąd:

` [{"code":"DownloadInvalidUrl","message":"Invalid URL  'http://37.187.138.146/foto/produkty/big/gal_120975_img_28322832jpg.jpg'.","details":null,"path":null,"userMessage":"Niepoprawny  adres URL:  'http://37.187.138.146/foto/produkty/big/gal_120975_img_28322832jpg.jpg'."}]`

Jak widać pod tym adresem znajduje się zdjęcie.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się zlokalizować źródło błędu, przekazałem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [naszym poradnikiem](https://developer.allegro.pl/sale/#step-3-images) nie pozwalamy przesyłać zdjęć, które mają w adresie adres ip:

> UWAGA! Pamiętaj aby podać adres domeny, nie podawaj adresu IP.

Dodamy taką informację także do naszej dokumentacji.
Przepraszam za wprowadzenie w błąd ostatnim wpisem, nie miało to ostatecznie związku ze zgłoszonym problemem.
