### ISSUE TITLE
Próba dodania trackingu do przesyłki zwraca engimatyczny błąd "An error has occurred"

### ISSUE THREAD

**Issue by haloween** [allegro/allegro-api#2941]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Było by naprawdę SUPER, jakby wasi przekwalifikowani budowlańcy po weekendowych kursach programowania, których zatrudniacie do pisania tego potworka - który nazywacie API nauczyli się jakoś ładnie formułować informacje o błędach.

Wybaczcie za poruszenie tego drażliwego tematu, ale "czołowy serwis e-komers w Wolsce" wyrzuca komunikat "An error has occurred". No i fajnie. Wiemy że jest błąd. 

TO JEST SŁABE 
Ogarnijcie wyjątki. Wypadało by.

P.S.
Taki error jest wywalany jak chce się 2x dodać ten sam numer trackingu.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id dla takiego błędu? Sprawdziłem to, w przypadku kiedy drugi raz dodam taki sam numer, otrzymuję status 201.

**Comment by haloween** [comment]
Nie chce mi się, serio. Ręce mi opadły.
Request był ok, bo trackingów ślemy po 200 dziennie i czasami któegoś nie zeżre.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć błędu, który opisałeś w zgłoszeniu, dlatego aby zweryfikować jego źródło, potrzebuję konkretne dane. W przyszłości, w przypadku kiedy otrzymasz taki błąd, prześlij przykładowe logi za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by Onixarts** [comment]
Ale tutaj nie trzeba daleko szukać. Codziennie przychodzą do nas od użytkowników zapytania co jest nie tak z requestem do wystawienia/aktualizacji oferty. Jakikolwiek błąd w którymś z pól tekstowych powoduje błąd 400, który w treści nie informuje co się stało. I teraz żmudne przeglądanie całego requesta co z nim nie tak. Skoro jakiś fragment walidatora stwierdza, że coś jest nie tak to niech doda informacje co. Są w strukturze z errorami odpowiednie pola na komunikat dla użytkownika, który powinien być czytelny a jest w nim to samo co w drugim polu.

```
{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
}
```
Skąd użytkownicy mają coś z tego się dowiedzieć, jak nawet programista nic z tego nie wie ;)

**Comment by PrzemyslawLukanowski** [comment]
@Onixarts Jeżeli natrafisz na taką sytuację, możesz wysłać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) przykładowe logi. Przekażę wtedy problem do odpowiedniego zespołu w celu doprecyzowania komunikatu błędu w odpowiedzi.

**Comment by haloween** [comment]
> @Onixarts Jeżeli natrafisz na taką sytuację, możesz wysłać przykładowe logi. Przekażę wtedy problem do odpowiedniego zespołu w celu doprecyzowania komunikatu błędu w odpowiedzi.

Weźcie że się nie wydurniajcie. I zwracajcie normalne komunikaty o błędach. 
To jest dobry standard prowadzenia projektów informatycznych.
Ludzie nie mają czasu żeby co błąd API wklejać kilometry requestów i odpowiedzi do nich.
Naprawcie ten problem.  To urąga standardom programowania.

**Comment by Onixarts** [comment]
Wystarczy wkleić niepoprawny znak w opis, tytuł, lub jakiekolwiek pole tekstowe, jakiś tabulator, znak nowej linii. Użytkownicy dane biorą z bardzo różnych miejsc, od plików worda, pdfa, poprzez strony HTML i pliki tekstowe z różnym kodowaniem. Wszystko to umieszczają w programie a potem my analizujemy całe requesty eliminując kolejno fragment po fragmencie aby namierzyć o które miejsce chodzi.
Nawet niby taki błąd jak Invalid HTML subset gdy w opisie znajduje się jakiś niepoprawny html też użytkownikowi nic nie mówi. Nawet jeśli rozumie on czym jest section[3].item[1] to nieraz trudno odszukać problem, który polega na tym, że zagnieżdżone są np pogrubienia.
Gdyby tam pojawiła się informacja, że jest pogrubienie w pogrubieniu (w końcu któryś walidator musiał to wykryć) to mógłby dopisać choćby fragment tekstu wokół którego występuje błąd.

My nie mamy bezpośrednio dostępu do tego co robią użytkownicy na swoich komputerach i samo pobranie od nich logów to jest kawałek procedury do wykonania - zależnie od umiejętności użytkownika. Natomiast wydaje się, że Wy jako serwis macie dostęp do wszystkich błędów i można by je monitorować, pogrupować, zobaczyć których jest najwięcej i się nimi zająć zwiększając ich czytelność, tak aby losowa osoba wybrana z korytarza wiedziała o co chodzi po przeczytaniu treści ;).

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za szczegółowe informacje i merytoryczne przedstawienie potrzeby. Problem z precyzyjnością komunikatów przekażę do odpowiedniego zespołu.
