### ISSUE TITLE
ALLEGRO_LOKALNIE w /offers/listing

### ISSUE THREAD

**Issue by rafalkrupinski** [allegro/allegro-api#2942]
Czy nowe oferty zaczęły zwracać vendor "ALLEGRO_LOKALNIE"? swagger dopuszcza jedynie "CHARYTATYWNI_ALLEGRO" a mam taki wyni w /offers/listing?category.id=4036

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Tak, zwracamy taką wartość. W najbliższym czasie zaktualizujemy naszą dokumentację.

**Comment by rafalkrupinski** [comment]
To chyba odwrotnie powinno być... 
swagger to nie dokumentacja, tylko definicja interfejsu, kontrakt. Ze swaggera można wygenerować klienta serwisu, potem klient waliduje wiadomość i zwraca błąd, że odpowiedź nie zgodna z kontraktem

**Comment by rafalkrupinski** [comment]
Na wypadek gdyby ktoś jeszcze miał ten sam problem, tutaj jest poprawiona wersja:
https://github.com/mattesilver/allegro-swagger/tree/bugfix/allegro_lokalnie

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje za link dla innych użytkowników, Twoją uwagę przekażę do odpowiedniego zespołu.

**Comment by rafalkrupinski** [comment]
Pozdrawiam

**Comment by rtnet-pl** [comment]
@PrzemyslawLukanowski co z tą dokumentacją - czy możemy przyjąć że każda oferta z AL ma vendor=ALLEGRO_LOKALNIE?
oraz dlaczego nie ma tego parametru w dostępnych filtrach?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możecie przyjąć takie założenie, uzupełnimy także dokumentację. Na tę chwilę nie planujemy udostępnić tego parametru w filtrach - zwracamy te oferty, ponieważ zależało nam, aby wyniki były tożsame z tymi, które są wyświetlane na stronie i w aplikacji.

**Comment by rafalkrupinski** [comment]
Problem nie został rozwiązany

**Comment by PrzemyslawLukanowski** [comment]
Pamiętamy o tym zadaniu, w najbliższej przyszłości zmienimy informację w dokumentacji.

**Comment by rafalkrupinski** [comment]
Post wisi już dwa miesiące więc domyślam się, że ta aktualizacja dokumentacji to nie jest trywialny problem dla zespołu :P

**Comment by PrzemyslawLukanowski** [comment]
Zmieniliśmy informację w dokumentacji.

**Comment by rafalkrupinski** [comment]
@PrzemyslawLukanowski  Dzięki za info. Sporo zmian, ograniczenie limitów zapytań przy okazji
