### ISSUE TITLE
Błąd 406 Not Acceptable przy wywołaniu metody /sale/products

### ISSUE THREAD

**Issue by sawaropl** [allegro/allegro-api#2943]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas wywoływania metody

` https://api.allegro.pl/sale/products?phrase=26-0193 `

otrzymujemy błąd 406 Not Acceptable, 

> code=InternalServerError
> details=(null)
> message=Internal Server Error
> path=(null)
> userMessage=Internal server error. Please retry in a few minutes.

Nagłówek 'Accept' to: application/vnd.allegro.public.v1+json

Błąd nie występuje gdy ilość wyszukanych produktów jest równa 0.
Dodam że błąd zaczął występować dzisiaj od rana (11.03), wcześniej działało wszystko poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się zlokalizować źródło tego błędu. Przekazałem problem do odpowiedniego zespołu, który w najbliższym czasie wdroży odpowiednią poprawkę.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy poprawkę.

**Comment by sawaropl** [comment]
Dziękuję, wszystko już działa.
