### ISSUE TITLE
min/max sprzedaż

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#2944]
Czy istnieje możliwość aby odfiltrować na poziome zapytania do API oferty które spełniają warunek min/max sprzedaż?
Np. API zwróć oferty z kategorii XYZ które spełniają warunek min. sprzedaż = 10, max. sprzedaż = 100.

Pytanie uzupełniające: 
1. Czy jest taka możliwość w odniesieniu do sprzedaży z ostatnich 30 dni?
2. Czy jest taka możliwość ze sprzedaży od początku trwania oferty?

Note: chodzi o oferty z całego serwisu.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie. GET /offers/listing odzwierciedla wyszukiwarkę ze strony internetowej, gdzie nie ma takiej możliwości. Listę dostępnych filtrów znajdziesz na końcu odpowiedzi.

**Comment by 4sp3ll** [comment]
Ok, dziękuję za szybką odpowiedź.
