### ISSUE TITLE
Rest Api -  Get order events

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#2945]
Przy pobieraniu zdarzeń metodą Get order events brakuje zdarzenia BOUGHT (1) jest tylko READY_FOR_PROCESSING (4), dotyczy to średnio jednej transakcji na tysiąc, z czego to może wynikać ?
Np zamówienia 
de06c333-61ed-11ea-804e-2f164b71cdff 
c907ae72-63ac-11ea-8a4f-8d8f157aa2a1

pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Taka sytuacja może mieć miejsce, wspominamy o tym [naszym poradniku](https://developer.allegro.pl/orders/):

> Dla każdego zamówienia musi wystąpić przynajmniej jedno zdarzenie (np. wypełnienie formularza opcji dostawy [FILLED_IN]).
