### ISSUE TITLE
Checkout-forms - An error has occurred

### ISSUE THREAD

**Issue by skmaksio** [allegro/allegro-api#2948]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Integracja działała, działała, aż dzisiejszego dnia się wysypała i wyskakuje:
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /order/checkout-forms
                    [userMessage] => 

Całego curla wysłałem przez formularz podając ID ticketu.

**Comment by PrzemyslawLukanowski** [comment]
Bład generuje nieprawidłowo zakodowana data dla parametrów lineItems.boughtAt.gte i lineItems.boughtAt.lte.
W przykładzie wysyłasz: 
 `lineItems.boughtAt.gte=2020-03-10T00%3A00%3A00+00%3A00&lineItems.boughtAt.lte=2020-03-13T12%3A59%3A00+00%3A00`
 a prawidłowa wartość to:
 `lineItems.boughtAt.gte=2020-03-10T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2020-03-13T12%3A59%3A00.000Z`
