### ISSUE TITLE
błąd An error has occurred przy zasobie POST /sale/offers

### ISSUE THREAD

**Issue by lukasx21** [allegro/allegro-api#2950]
Ciągle otrzymuję błąd object(stdClass)#64 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#63 (5) { ["code"]=> string(5) "ERROR" ["message"]=> string(21) "An error has occurred" ["details"]=> NULL ["path"]=> string(12) "/sale/offers" ["userMessage"]=> NULL } } }

 json request:

{
    "id": null,
    "name": "KRZESE\u0141KO PRYSZNICOWE UCHYLNE DLA NIEPE\u0141NOSPRAWNYC",
    "category": {
        "id": "260752"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "229837",
            "valuesIds": [
                "229837_344257"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "229173",
            "valuesIds": [
                "229173_340085"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "221549",
            "valuesIds": [],
            "values": [
                "PSP\/25\/503"
            ],
            "rangeValue": null
        },
        {
            "id": "229841",
            "valuesIds": [
                "229841_344277"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "229845",
            "valuesIds": [
                "229845_344293"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "229197",
            "valuesIds": [],
            "values": [
                "120"
            ],
            "rangeValue": null
        },
        {
            "id": "229853",
            "valuesIds": [
                "229853_2",
                "229853_16"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "222093",
            "valuesIds": [],
            "values": [
                "40"
            ],
            "rangeValue": null
        },
        {
            "id": "221965",
            "valuesIds": [],
            "values": [
                "40"
            ],
            "rangeValue": null
        }
    ],
    "ean": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https:\/\/a.allegroimg.com\/original\/0322ad\/c5e2bd7143d7b611d9d1bcbd9c2e"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Przedmiotem aukcji jest: KRZESE\u0141KO PRYSZNICOWE UCHYLNE Z PODPORAMI \u2013 STAL NIERDZEWNA PO\u0141YSK<\/h1><p><\/p><p>Krzese\u0142ko u\u0142atwia codzienne czynno\u015bci higieny osobistej w kabinie prysznicowej, zw\u0142aszcza osobom niepe\u0142nosprawnym oraz obni\u017conej sprawno\u015bci ruchowej. Produkt odporny na korozj\u0119, wykonany zestali nierdzewnej AISI 3040 (wyko\u0144czenie typu po\u0142ysk). Stanowi doskona\u0142y wyb\u00f3r dla os\u00f3b poszukuj\u0105cych wysokiej jako\u015bci rozwi\u0105za\u0144.<\/p><p><b>Zastosowanie: strefa prysznicowa.<\/b><\/p><p><\/p>"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https:\/\/a.allegroimg.com\/original\/0340f0\/791369f74d3382e64644a2f473cc"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https:\/\/a.allegroimg.com\/original\/03abab\/0498ee2e40c9a66e5ac234006552"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>Dane techniczne:<\/h2><ul><li>Typ: prysznicowe<\/li><li>Model: PSP\/25\/503<\/li><li>W zestawie: wkr\u0119ty, ko\u0142ki, podk\u0142adki, za\u015blepki<\/li><li>\u015arednica rurki: \u00d8 25 mm<\/li><li>Wyko\u0144czenie: stal nierdzewna po\u0142ysk<\/li><\/ul>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Na innych aukcjach dost\u0119pne s\u0105 <b>inne rozmiary<\/b>, grubo\u015bci rurek, r\u00f3wnie\u017c ze <b>stali nierdzewnej<\/b> w wyko\u0144czeniu po\u0142ysk lub mat.<\/p><h2>Informacje dodatkowe:<\/h2><ul><li><b>produkt polski wysokiej jako\u015bci<\/b><\/li><li>wystawiamy faktury VAT<\/li><li><b>gwarancja 12 miesi\u0119cy<\/b><\/li><\/ul>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https:\/\/a.allegroimg.com\/original\/03b28c\/0a8a1ff040d484ec1675d78e7142"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/035628\/c670ceb74bd5afdf0514e3e7ef29"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/03abab\/0498ee2e40c9a66e5ac234006552"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/0340f0\/791369f74d3382e64644a2f473cc"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/03239c\/b236aa1043a1a2a2558a645715f5"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/0304f6\/1f9c59214d3f9f911c44ef8cd4d8"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/0322ad\/c5e2bd7143d7b611d9d1bcbd9c2e"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/03b28c\/0a8a1ff040d484ec1675d78e7142"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "587.41",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null
    },
    "stock": {
        "available": 97,
        "unit": "UNIT"
    },
    "publication": {
        "duration": "P3D",
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": "",
        "endedBy": null,
        "republish": true
    },
    "delivery": {
        "shippingRates": {
            "id": "6af2980a-b060-4ad2-9e30-ff9adbbac061"
        },
        "handlingTime": "PT24H",
        "additionalInfo": "Je\u017celi Klient z\u0142o\u017cy zam\u00f3wienie jednocze\u015bnie na produkty standardowe (najd\u0142u\u017cszy bok do 1,50 m) i produkty d\u0142u\u017cycowe, zam\u00f3wienie zostanie wys\u0142ane w dw\u00f3ch paczkach.\n\nJe\u017celi produkty nie b\u0119d\u0105 mog\u0142y by\u0107 bezpiecznie spakowane do jednej przesy\u0142ki, lub je\u017celi jej waga przekroczy 31 kg, pracownik sklepu zaproponuje indywidualnie dobran\u0105 form\u0119 wysy\u0142ki.\n\nPrzesy\u0142ki realizujemy za po\u015brednictwem firmy kurierskiej DPD.",
        "shipmentDate": ""
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "8a9d3b2a-ecbc-4ecf-baa2-fffd2a49b1e7"
        },
        "returnPolicy": {
            "id": "3c93b94c-d2ee-4d26-ba2b-b7e335b11863"
        },
        "warranty": {
            "id": "e9510805-b340-433a-9a19-3ff6ab872ca8"
        }
    },
    "additionalServices": null,
    "sizeTable": null,
    "promotion": {
        "emphasized": true,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "ZACHODNIOPOMORSKIE",
        "city": "Szczecinek",
        "postCode": "78-400"
    },
    "external": {
        "id": "PSP\/25\/503"
    },
    "attachments": [],
    "contact": null,
    "validation": {
        "validatedAt": ""
    },
    "createdAt": "",
    "updatedAt": ""
}

**Comment by PrzemyslawLukanowski** [comment]
Błąd generują puste stringi w polach validation, createdAt i updatedAt. Po usunięciu tych pól draft utworzy się prawidłowo. Przekażę informację do odpowiedniego zespołu o doprecyzowanie tego komunikatu.

**Comment by lukasx21** [comment]
Dziękuję za pomoc. Co ciekawe, użyłem tego samego oprogramowania co 3 tygodnie wcześniej do kopiowania aukcji między kontami. W tamtym przypadku, mimo pustych stringów w tych polach, wszystko hulało aż miło:-) Nieważne, bardzo dziękuję za pomoc, już wszystko jest OK.
