### ISSUE TITLE
Transakcje z płatnością przelewem tradycyjnym nie pobierają się

### ISSUE THREAD

**Issue by MichalKosowski** [allegro/allegro-api#2951]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

:beetle: **Opis**
Hej,

Klient zgłosił że nie wszystkie transakcje mu się wyświetlają. Problem dotyczy transakcji w których klient wybrał jako formę płatności przelew tradycyjny (nie online). Dla tych transakcji istnieją eventy:
- BOUGHT
- FILLED IN
- FILLED IN

Ale nie ma READY_FOR_PROCESSING. Z tego powodu nie pobierają się w naszej aplikacji.

Czy te transakcje trzeba jakoś inaczej obsługiwać czy to jest jakiś błąd systemu?

Co ciekawe, obie mają w CheckoutForm json zaznaczone następujące formy płatności:

`"payment": {
        "id": "457bcaf2-62a8-11ea-afe9-eb7958b06886",
        "type": "ONLINE",
        "provider": "P24",
        "finishedAt": "2020-03-10T08:26:42.868Z",
        "paidAmount": null
    },`

`"payment": {
        "id": "d1d89c02-5fb3-11ea-95ea-451eba02e73f",
        "type": "ONLINE",
        "provider": "PAYU",
        "finishedAt": null,
        "paidAmount": null
    },`

Mimo iż klient wybrał inną opcje. W jednej widzę nawet wiadomość do sprzedawcy:

`"messageToSeller": "Witam , proszę o padanie nr konta do wpłaty za tą listwę",`

Proszę o pomoc i rozwiązanie problemu.

Michał

**Comment by PrzemyslawLukanowski** [comment]
Aby zamówienie otrzymało status READY FOR PROCESSING w ramach przelewu tradycyjnego, musi być zrealizowane przez Allegro Finanse. Kupujący po tym, jak wybierze "Kupuję i płacę", otrzymuje link do wzoru przelewu, na którym znajdują się dane, które pomogą powiązać płatność z zamówieniem w naszym systemie. 
Dane w pliku json są poprawne - jest to przelew realizowany za pośrednictwem P24/PAYU. Płatność 457bcaf2-62a8-11ea-afe9-eb7958b06886 została anulowana przez kupującego, stąd data w polu finishedAt.

**Comment by MichalKosowski** [comment]
Ok, a moglibyście zerknąć okiem na te transakcje, czy to właśnie ten problem czy coś innego się stało. Bo to pierwszy raz kiedy klient (i to nie jeden) zgłasza taki problem. Wcześniej działało bez problemów.
CheckoutFormIds:
* d1994912-5fb3-11ea-9781-c5d0be452f6f
* 24c24282-62a8-11ea-8c0e-5f55fb53cad1

I jeszcze raz aby zrozumieć proces. 
1. Jeśli ktoś wybiera przelew tradycyjny, musi wybrać Kupuję i Płacę i formę przelew tradycjny (gdzieś  tam coś takiego powinno być)
2. Jeśli to zrobi to dostanie link w który musi kliknąć, dzięki temu system załapie że taka sytuacja ma miejsce i oznaczy zamówienie jako READY FOR PROCESSING

Pytania:
1. Jak informacja o takiej płatności będzie wyglądać w pliku json?
2. Czy możecie zasugerować jakiś sposób aby wychwycić te nie udane zaplaty? Zrobić np. alternatywną ścieżkę w aplikacji która pobierze wszystkie zlecenia którę nie są READY_FOR_PROCESSING a którę mają jakoś Payment zarejestrowant (jak w przykładach wyżej?)

**Comment by PrzemyslawLukanowski** [comment]
Te dwa checkoutFormy powiązane są z płatnościami, które udostępniłeś w pierwszym wpisie.

Co do pytań:

1. Przelew tradycyjny wybiera kupujący w "Metodzie płatności" -> Szybki przelew -> Przelew Tradycyjny. Następnie, aby potwierdzić zakup, każdy kupujący musi wybrać "Kupuję i płacę". 
2. Nie do końca tak, użytkownik zostanie przekierowany na poniższy widok:

![Screenshot_31](https://user-images.githubusercontent.com/51473661/76738351-c0610700-676a-11ea-8e1e-6885ead319cb.png)


Po wybraniu "wzór przelewu" może wydrukować ten dokument, który następnie opłaci np. na poczcie lub przelewem internetowym. Ważne, aby wszystkie dane zostały zachowane - przelew z odpowiednim tytułem musi iść na konto PAYU/P24. Po tym, jak pieniądze trafią na rachunek, zamówienie otrzyma status RFP.

3. Podobnie jak w przypadku innych przelewów dostępnych w metodzie płatności jako "zwykłe przelew".

4. Nieudane płatności możesz wygenerować za pomocą parametru ?status=FILLED_IN - będzie to oznacząć, że kupujący zakupił przedmiot, jednak płatność nie została zrealizowana.

**Comment by MichalKosowski** [comment]
Dzięki za pomoc!

Mam jeszcez jedno pytanie. Dla powyższych transakcji pole delivery address jest puste, podczas gdy transakcje w stanie READY_FOR_PROCESSING mają to pole wypełnione. 
W tym przypadku odbiór jest w punkcie, ale i tak dane odbiorcy mogą być różne niż dane kupującego z pola buyer. Dlaczego te dane nie są wypełnione?

**Comment by PrzemyslawLukanowski** [comment]
Dane dla delivery.address zwracamy dopiero dla zamówienia w statusie RFP. Podobnie jak na froncie - w zakładce Zamówienia adres dostawy w "Dane dostawy" zobaczysz dopiero po tym, jak kupujący opłaci zamówienie.
