### ISSUE TITLE
Błędna data boughtAt zamówienia w response

### ISSUE THREAD

**Issue by dominikworkroom** [allegro/allegro-api#2952]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem testowym

:beetle: **Opis**

Cześć,

Testuję sobie integrację na środowisku testowym **https://allegro.pl.allegrosandbox.pl/**
usługę:  **order/checkout-forms**

Złożyłem zamówienie o godzinie 17:27 tak jak widać na zdjęciu, data sprzedaży to : 
**14 mar 2020, 17:26** a data płatności **14 mar 2020, 17:27** 
![image](https://user-images.githubusercontent.com/25220809/76686521-32770600-661c-11ea-86fc-1baf0aca470a.png)

problem jest taki że w momencie kiedy bije do zasobu z godziną np: 17:25 to dostaję wynik 0 orderów. 
a dzieje się to dlatego że REST API zwraca ordery z godziną do tyłu. poniżej wysyłam response który dostaję 

`{
    "checkoutForms": [
        {
            "id": "3961c4c2-6610-11ea-8b61-39de406e79a5",
            "messageToSeller": null,
            "buyer": {
                "id": "44274419",
                "email": "ut6lh8gf9p+3c730c3c2@user.allegrogroup.pl",
                "login": "!g_44274419",
                "firstName": "Piotr",
                "lastName": "Powolny",
                "companyName": null,
                "guest": true,
                "personalIdentity": null,
                "phoneNumber": "+48 12 312 31 23",
                "address": {
                    "street": "dsadas",
                    "city": "Warszawa",
                    "postCode": "00-001",
                    "countryCode": "PL"
                }
            },
            "payment": {
                "id": "59f3a0f0-6610-11ea-bf36-5d8e97507618",
                "type": "ONLINE",
                "provider": "PAYU",
                "finishedAt": "2020-03-14T16:27:03.140Z",
                "paidAmount": {
                    "amount": "168.99",
                    "currency": "PLN"
                }
            },
            "status": "READY_FOR_PROCESSING",
            "fulfillment": {
                "status": "SENT",
                "shipmentSummary": {
                    "lineItemsSent": "NONE"
                }
            },
            "delivery": {
                "address": {
                    "firstName": "Piotr",
                    "lastName": "Powolny",
                    "street": "dsadas",
                    "city": "Warszawa",
                    "zipCode": "00-001",
                    "countryCode": "PL",
                    "companyName": "Corona",
                    "phoneNumber": "+48 123 123 123"
                },
                "method": {
                    "id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
                    "name": "Allegro Paczkomaty 24/7 InPost"
                },
                "pickupPoint": {
                    "id": "WAW24M",
                    "name": "Paczkomat WAW24M",
                    "description": "Przy budynku Sensorium",
                    "address": {
                        "street": "Mrówcza 33B",
                        "zipCode": "04-857",
                        "city": "Warszawa"
                    }
                },
                "cost": {
                    "amount": "8.99",
                    "currency": "PLN"
                },
                "smart": false,
                "time": {
                    "guaranteed": null
                },
                "calculatedNumberOfPackages": 1
            },
            "invoice": {
                "required": false,
                "address": null
            },
            "lineItems": [
                {
                    "id": "3961c4c0-6610-11ea-8b61-39de406e79a5",
                    "offer": {
                        "id": "6206425756",
                        "name": "Białko 2400g Truskawkowe",
                        "external": null
                    },
                    "quantity": 1,
                    "originalPrice": {
                        "amount": "160.00",
                        "currency": "PLN"
                    },
                    "price": {
                        "amount": "160.00",
                        "currency": "PLN"
                    },
                    "selectedAdditionalServices": [],
                    "boughtAt": "2020-03-14T16:26:42.032Z"
                }
            ],
            "surcharges": [],
            "discounts": [],
            "summary": {
                "totalToPay": {
                    "amount": "168.99",
                    "currency": "PLN"
                }
            },
            "updatedAt": "2020-03-14T16:27:03.140Z"
        }
    ],
    "count": 1,
    "totalCount": 1
}`

Jak widać w powyższym kodzie JSON są złe daty 
"boughtAt": "2020-03-14T16:26:42.032Z" - **powinna być 17:26**
"finishedAt": "2020-03-14T16:27:03.140Z", - **powinna być 17:27**

Proszę o pomoc :) pozdrawiam

**Comment by Bober95** [comment]
Wszystko jest ok, po prostu api zwraca czas GMT

**Comment by dominikworkroom** [comment]
@Bober95 no to nie jestem pewien czy wszystko jest ok skoro składam zamowienie z godziną gtm+1 a zwraca mi gtm, mam się sam domyślić jaki czas mi zwróci? :)

**Comment by Bober95** [comment]
@dominikworkroom  zakładasz że czas który otrzymałeś od allegro jest GMT. Później jeśli potrzebujesz konwertujesz go sobie na czas lokalny

**Comment by dominikworkroom** [comment]
@Bober95 "zakładam"? czyli składam zamówienie w polskim ecommerce w GTM+1, natomiast api zwraca mi zamówienia w czasie GTM, więc twoim zdaniem kiedy wysyłam żądanie do api z przedziałem dat konwertuję daty w żądaniu na gtm a potem wszystkie np. 100 zamówienie którę dostaję z api konwertuję z gtm na gtm+1? to dziwne podeślij link do dokumentacji z tym co mówisz proszę

**Comment by TimothyKoval** [comment]
Format daty zawiera strefę czasową, niczego tu się nie trzeba domyślać

**Comment by Bober95** [comment]
@dominikworkroom https://developer.allegro.pl/about/#datetime

**Comment by dominikworkroom** [comment]
@Bober95 ok dzieki jutro poczytam 🙏
