### ISSUE TITLE
Pobieranie handlingTime dla wszystkich ofert użytkownika

### ISSUE THREAD

**Issue by martasobota** [allegro/allegro-api#2953]
By aktualizować czasy wysyłki aukcji, potrzebuję porównać obecny czas wysyłki do pliku z aktualizacjami. 

W tym celu chciałabym pobierać informacje o wszystkich aukcjach, jednak w metodzie [GET sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) nie ma informacji o czasie dostawy dla danej aukcji. 

Czy jest metoda zwracająca informacje wszystkich aukcji łącznie z ich czasem dostawy? 

Sprawdzanie informacji dla pojedynczej oferty nie rozwiązuje mojego problemu.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie ma takiej możliwości. GET /sale/offers odzwierciedla dane z zakładki [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty). Przedstaw proszę odpowiednią potrzebę, a przekażę to zgłoszenie jako sugestię do działu odpowiedzialnego za rozwój API.

**Comment by martasobota** [comment]
Ok, obecnie aktualizujemy czasy wg pliku, który zwraca, jaki powinien być czas wysyłki.

Ponieważ aukcji jest bardzo dużo, aktualizacja wszystkich trwa kilka kilka godzin, a nie ma też sensu wysyłać `PUT`, jeśli czas wysyłki się nie zmienił.

Obecne rozwiązanie wygląda tak:
* Porównywane są czasy wysyłki, które się zmieniły między kolejnymi plikami i tylko te różnice są aktualizowane. Tu zdarzają się "przecieki", mimo, że w logach aukcje są zaktualizowane, zdarza się, że mają stary czas. Prawdopodobnie podejście "różnic" między kolejnymi plikami z czasami nie jest w 100% bezpieczne. 

Chciałabym, żeby było tak:
* Pobranie czasów wysyłki dla wszystkich aukcji i porównać różnice z plikiem z czasami wysyłek (całym). Jeśli czasy są różne, zaktualizować aukcję. 
Widzę, że mogę sprawdzić czasy dla poszczególnych aukcji pojedynczo, ale to zajmie za dużo czasu, równie dobrze mogę za każdym razem wysyłać `PUT` z aktualizacją dla wszystkich aukcji, nawet jeśli czas się nie zmienił.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Jeżeli zdecyduejmy się na wdrożenie dodatkowego pola, poinformujemy o tym w odpowiednim komunikacie.

**Comment by martasobota** [comment]
To będzie ogłoszone w aktualizacjach, czy poinformujecie mnie też tutaj? 😊 🙏

**Comment by PrzemyslawLukanowski** [comment]
Jeśli zdecydujemy się na wdrożenie - na stronie aktualizacji oraz stronie głównej naszego forum.
