### ISSUE TITLE
POST /sale/images zwraca 401

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#2955]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

```
POST /sale/images HTTP/1.1
Host: upload.allegro.pl
Accept-Language: pl-PL
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: bearer eyJhbGciOi ... YNnNBvZLmA
Content-Length: 87
```

`{"url":"https://dar ... 92ac.jpg"}`

```
HTTP/1.1 401 Unauthorized
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 3d197a526fe299d3
referrer-policy: no-referrer
date: Mon, 16 Mar 2020 08:34:35 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 101
x-envoy-upstream-service-time: 56
```

`{"errors":[{"code":"401 UNAUTHORIZED","message":null,"details":null,"path":null,"userMessage":null}]}`

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, mieliśmy problemy z tym zasobem. Dokonaliśmy już niezbędnej poprawki i funkcjonalność wróciła do normy. Przepraszam za niedogodności.
