### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#2956]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,
Proszę o aktywację konta na sanbox, login - allegro@perfumesco.pl

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już w pełni aktywne oraz zweryfikowane jako konto Firma.

**Comment by pawelosajda** [comment]
Dziękuje
