### ISSUE TITLE
API documentation suggestion..

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#2957]
In the API documentation, every single example of an error response seems to be the same error

`{
  "errors": [
    {
      "code": "NotAcceptableException",
      "details": null,
      "message": "Not acceptable representation requested. Please check 'Accept' request header",
      "path": null,
      "userMessage": "The request contains incorrect data. Contact the author of the application."
    }
  ]
}`

It would be nice to get some examples of more specific errors that can occur

**Comment by MaciejFrackowiak** [comment]
In our responses, we try to return possible accurate error messages. Of course, we are constantly working on their accuracy, as well as updating when the case requires it. Unfortunately, it is not possible for us to present all available error messages.
