### ISSUE TITLE
POST sale/offers

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#2958]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Problem ze stworzeniem DRAFT. Poniżej co generuje i wysyłam.
`{
    "additionalServices": {
        "id": "support"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59\""
        },
        "returnPolicy": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59\""
        },
        "warranty": {
            "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59\""
        }
    },
    "attachments": [
        {
            "id": "1928302_MANUAL_45d7a0f543e1b0d05e12a1aef5642efe63389a1d419fe9286d0f158044391fdce"
        }
    ],
    "category": {
        "id": "257150"
    },
    "compatibilityList": {
        "type": "MANUAL"
    },
    "contact": {
        "id": "string"
    },
    "createdAt": "2020-03-13T14:02:04Z",
    "delivery": {
        "additionalInfo": "string",
        "handlingTime": "PDT12H30M5S",
        "shipmentDate": "2018-04-01T08:00:00Z",
        "shippingRates": {
            "id": "string"
        }
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
Tekstowy opis przedmiotu<\/p>"
                    },
                    {
                        "type": "IMAGE",
                        "content": "url\": \"https:\/\/e.allegroimg.com\/original\/01fd60\/4ea8d18e4275b0878b7f0562067e"
                    }
                ]
            }
        ]
    },
    "ean": "6901443187416",
    "external": {
        "id": "AH-129834"
    },
    "id": "test",
    "images": [
        {
            "url": "string"
        }
    ],
    "location": {
        "city": "string",
        "countryCode": "string",
        "postCode": "string",
        "province": "string"
    },
    "name": "Test product",
    "parameters": [
        {
            "id": "string",
            "rangeValue": {
                "from": "string",
                "to": "string"
            },
            "values": [
                "string"
            ],
            "valuesIds": [
                "string"
            ]
        }
    ],
    "payments": {
        "invoice": "string"
    },
    "product": {
        "id": "string"
    },
    "promotion": {
        "bold": true,
        "departmentPage": true,
        "emphasized": true,
        "highlight": true,
        "emphasizedHighlightBoldPackage": true
    },
    "publication": {
        "duration": "PDT12H30M5S",
        "endingAt": "2020-03-12T15:18:35Z",
        "emphasized": "2020-03-12T15:18:35Z",
        "status": "INACTIVE",
        "endedBy": "USER",
        "republish": "false"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "123.45",
            "currency": "PLN"
        },
        "minimalPrice": {
            "amount": "123.45",
            "currency": "PLN"
        },
        "artingPrice": {
            "amount": "123.45",
            "currency": "PLN"
        }
    },
    "sizeTable": {
        "id": "string"
    },
    "stock": {
        "available": 10,
        "unit": "string"
    },
    "tecdocSpecification": {
        "id": "470b8513-b786-b7b9-9e7e-2f848729cfd6",
        "items": [
            {
                "name": "Wersja TecDoc",
                "values": [
                    "values"
                ]
            }
        ]
    },
    "updatedAt": "2020-03-13T15:18:35Z",
    "validation": {
        "errors": [
            {
                "code": "string",
                "details": "string",
                "message": "string",
                "path": "string",
                "userMessage": "string"
            }
        ],
        "validatedAt": "2020-03-12T15:18:35Z"
    }
}`

Odpowiedzią jest 

Response status code: 400
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

Kolejna sprawa gdzie w Allegro znajdę te stworzone drafty lub jak pobrać listę już istniejących bo szukam po API i nie mogę tego znaleźć.

**Comment by MaciejFrackowiak** [comment]
Stworzone drafty znajdziesz w zakładce [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty?offerType=BUY_NOW&statuses=INACTIVE&page=1&pageSize=60). Natomiast w REST API pobierzesz je przy pomocy GET /sale/offers/?publication.status=INACTIVE

Twój zamieszczony JSON zawiera wiele niepoprawnie wypełnionych pól - proszę spójrz do [naszego poradnika](https://developer.allegro.pl/sale/), gdzie krok po kroku przedstawiamy proces wystawienia oferty.

**Comment by DanielMiara** [comment]
Przykład brałem z https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST. Czyli lepiej zostawić pole pustym nić dawać tam błędną wartość?

**Comment by MaciejFrackowiak** [comment]
Oczywiście lepiej zostawić puste pole, ale proszę spójrz także na [poradnik](https://developer.allegro.pl/sale/). 
Pomocne może być także dla Ciebie wystawienie oferty przez stronę WWW, a następnie pobranie jej przez REST API przy pomocy [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - tak poznasz pełną jej strukturę.

**Comment by DanielMiara** [comment]
Tak właśnie zorbię. Chciałem trochę na skróty
