### ISSUE TITLE
Nieprawidłowe działanie pól typu textarea

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#296]
Przy wystawianiu aukcji przez Web API pola typu textarea nie respektują więcej niż jednej linii. Fragment przesyłanego XML-a:

```
<ns1:item><ns1:fid>39623</ns1:fid><ns1:fvalueString>NTYBMO-TY-010
BMO-TY-010
1210231030
12102-31030
I35040YMT
V70-0408
NTYSDK-MS-040
SDK-MS-040
NTYSDK-M</ns1:fvalueString></ns1:item>
```
Na aukcji widnieje tylko pierwsza linia. Po edycji przez interfejs webowy i pobraniu pól przez `doGetItemFields` dane rozdzielone są prawidłowo - dokładnie tak jak powyżej.

**Comment by kormichu** [comment]
Podpinam wątek #281

**Comment by PawelTaberski** [comment]
@TimothyKoval Tak zauważyliśmy taki problem pracujemy nad jego rozwiązaniem, a w jakiej kategorii (numer kategorii) próbujesz wystawić ofertę?
