### ISSUE TITLE
Jak pobrać listę możliwych metod płatności przez REST API

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#2961]
Jest możliwość pobrania listy metod dostaw przez GET /sale/delivery-methods, ale nie widzę niczego podobnego w dokumentacji API dla metod płatności. 

Czy istnieje jakiś sposób na pobranie możliwych metod płatności przez REST API?

**Comment by tztztztz** [comment]
Doprecyzuję, że chodzi jedynie o właściwość payment->type, która pojawia się w checkout form.

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiego zasobu.
Dostępne metody płatności wymieniliśmy m.in. w [poradniku](https://developer.allegro.pl/orders/#04):

> 
rodzaj płatności, przyjmuje wartości:
                                                            “ONLINE”, "CASH_ON_DELIVERY", "SPLIT_PAYMENT"

**Comment by tztztztz** [comment]
Okay, dzięki za informację, zamykam.
