### ISSUE TITLE
Aktywacja konta Sandbox

### ISSUE THREAD

**Issue by pawelkatny** [allegro/allegro-api#2962]
Hej,

Prośba o aktywację konta w Sandbox.

mail: pawel.katny@gmail.com

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Konto aktywowałem!

**Comment by jguthriedodax** [comment]
Is it possible to activate mine too?

jamie.guthrie@myworld.com

**Comment by MaciejFrackowiak** [comment]
@jguthriedodax Of course - your account is active now.

**Comment by grupaluksor** [comment]
Hej,

Prośba o aktywację konta w Sandbox.

mail: a.jasinska@grupaluksor.pl 

Pozdrawiam,

**Comment by MaciejFrackowiak** [comment]
@grupaluksor Konto aktywowałem. Jest to konto Firma, dlatego w celu jego weryfikacji proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by valery-zuev** [comment]
Hej,
Proszę aktywować konto testowe: gp@wapi.com
Dziękuję Ci.

**Comment by AureliuszBrussy** [comment]
@valery-zuev aktywowałem Twoje konto.

**Comment by mainfreme** [comment]
Cześć,
można prosić o aktywowanie konta testowego 
dhpoczta@protonmail.com
Dzięki

**Comment by Lukasz-Zurek** [comment]
@mainfreme Aktywowałem konto. Z uwagi na to, że jest to konto Firma - w celu jego weryfikacji - prześlij proszę dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by MartaNowaczyk** [comment]
@Mateusz-Nejman aktywowałam podane konto. Pozdrawiam.

**Comment by exploIF** [comment]
Cześć, prośba o aktywację konta testowego
i.furgala@3mk.pl
Dzięki ;)

**Comment by MaciejFrackowiak** [comment]
@exploIF Twoje konto jest już aktywne.

**Comment by Rikko28** [comment]
Hello, may I ask please to activate sandbox account, so I could upload offers with my own items? T.Y. in advance. sklep@daviva.lt

**Comment by PrzemyslawLukanowski** [comment]
@Rikko28 I've pre-activated your account. Please provide name and surname and upload any two files ("Choose file" button) via [this tab](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) to complete the activation process.

**Comment by Rikko28** [comment]
@Orzen
Done. When you said "ANY" two files, I actually uploaded 
 random files. 😄

**Comment by PrzemyslawLukanowski** [comment]
Yes, it could have been random files :) Your account is fully active right now.

**Comment by Rikko28** [comment]
Thank you for such a fast response.

**Comment by Rikko28** [comment]
Hello, please help https://github.com/allegro/allegro-api/issues/7947#issue-1987515574

**Comment by Lukasz-Zurek** [comment]
@Rikko28 I have already helped you in https://github.com/allegro/allegro-api/issues/7947#issue-1987515574.

**Comment by rytisOvoko** [comment]
Hello, today I created new sandbox account, but did not receive confirmation letter.
Could you please activate account and sales for this email: rytis.backiravicius@ovoko.com ?
Thank you.

**Comment by MaciejFrackowiak** [comment]
@rytisOvoko As I see you received an email, so I was able to activate your account.

**Comment by namlongvuGetSix** [comment]
Hello, I created new sanbox account, please active account for me to sell product for this email: wnamlong.9@gmail.com
Thank you

**Comment by Lukasz-Zurek** [comment]
@namlongvuGetSix I see that you have already activated your account, but it is a regular account, so you won't be able to test offer creating process, etc. You should convert your account to business, which you can do [here](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) and then [set the payouts](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) with fictional data and use our payment simulator.

Please let me know as soon as you finish this process.

**Comment by namlongvuGetSix** [comment]
Hello, I have changed my account to business

**Comment by Lukasz-Zurek** [comment]
@namlongvuGetSix Ok. Please [set the payouts](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-wyplat) with fictional data and use our payment simulator.

**Comment by namlongvuGetSix** [comment]
I have enter fictional data but it said that: The details assigned to the bank account must be the same as those of your company
If your business name, address, and VAT number are different, you'll need to re-verify. Do i need to enter real data of my company?

**Comment by Lukasz-Zurek** [comment]
@namlongvuGetSix No, only fictional data. You can generate some of them via one of the online generators.

**Comment by namlongvuGetSix** [comment]
Hello, I have enter fictional data, it's verifying my bank account detail and company detail. Question is do I have to pay 1zl to this account: PL86652441225054465340758589. And if I paid by my real bank account, my account in sandbox will be verified right?

**Comment by Lukasz-Zurek** [comment]
@namlongvuGetSix On the Sandbox environment you do not have to make real payments, there is a payment simulator, you just accept the payment (when you activate your account or when you "pay" for the product).

I have already activated your account.

**Comment by namlongvuGetSix** [comment]
Thank you very much. My account is active

**Comment by PiotrPisz** [comment]
Prośba o aktywowanie konta piotr_appstar
