### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by feomazyt** [allegro/allegro-api#2963]
Witam,

Czy mógłbym prosić o aktywacje konta na allegro sandbox, chce przetestować wystawianie aukcji

konto1: adamtestns@gmail.com
konto2: tkbylo@gmail.com

Z góry dziękuję

**Comment by MaciejFrackowiak** [comment]
Przed momentem aktywowałem Twoje konta.

**Comment by slawomir-zaziablo** [comment]
Witam, również proszę o aktywację konta, próbuję przetestować wystawianie aukcji z zewnętrznego sklepu.
Login: Client:44287808

**Comment by PrzemyslawLukanowski** [comment]
@slawomir-zaziablo Aktywowałem Twoje konto.
