### ISSUE TITLE
Verifying sandbox account

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#2964]
Hi,

I'd like to upload some test offers to the Allegro sandbox, but am getting the error:

```
"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "ERR_IF_YOU_WANNA_SELL",
                "details": "",
                "path": "",
                "userMessage": ""
            }
        ]
}
```

I read that it might be because my account is not verified. ( https://github.com/allegro/allegro-api/issues/1445 )

How can I go about verifying my account so that I can start adding offers? (I've been through the process at https://github.com/allegro/allegro-api/issues/2529#issuecomment-554987371 and received a message that I need to wait for verification confirmation by email, but its been some time now)

Thanks

**Comment by MaciejFrackowiak** [comment]
Yes, you received that error because your account wasn't active - I did it for you a moment ago as I wrote [here](https://github.com/allegro/allegro-api/issues/2962).
Now, you can list offers on Sandbox.
