### ISSUE TITLE
Produkty w kategorii 79205

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#2965]
W załączniku podsyłam listę produktów w Allegro, które są wg. API w kategorii 79205. Kategoria ta jednak nie jest wybieralna (nie jest najniższa). Proszę o poprawę kategorii na właściwą - inaczej nie da się podpiąć aukcji pod te produkty.

[invalid_groups.20200317230434.zip](https://github.com/allegro/allegro-api/files/4346060/invalid_groups.20200317230434.zip)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spostrzeżenie - sprawę przekazałem już do właściwego działu.

**Comment by pgasidlo** [comment]
Widzę, ze poprawione. Jeszcze jeden produkt `12e97f05-84e3-4047-b195-4a6be86d638a` - to klocki LEGO, lecz są w kategorii `17863`, czyli `Dziecko / Zabawki / Klocki / Pozostałe`.

**Comment by pgasidlo** [comment]
Dodatkowo proszę o sprawdzenie tych produktów. Nie mają EANu LEGO `5702....` a są w kategoriach pod `LEGO`. Cześć z nich to książki, więc może tak ma być.

[invalid_groups.20200318131530.zip](https://github.com/allegro/allegro-api/files/4348862/invalid_groups.20200318131530.zip)

**Comment by MaciejFrackowiak** [comment]
Tak, produkty z pierwszego posta zostały edytowane. Kolejne produkty również przekazałem do weryfikacji.

**Comment by pgasidlo** [comment]
Proszę jeszcze raz o weryfikację produktów. Sprawdziłem z API i nadal są produkty w kategorii 79205.
[invalid_groups.20200323163546.zip](https://github.com/allegro/allegro-api/files/4370366/invalid_groups.20200323163546.zip)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za update listy - przekazałem do właściwego działu.
