### ISSUE TITLE
Zmiany Allegro - możliwość anulowania / edycji zamówień przez kupującego

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2966]
Cześć
Dostaliśmy takie informacje
(..)
Łatwiejsze zakupy i obsługa zamówień - kupujący może anulować omyłkowo złożone zamówienie, dopóki sprzedający nie zacznie go realizować
**W najbliższych miesiącach udostępnimy nową opcję, dzięki której kupujący będą mieli możliwość anulowania omyłkowego zakupu lub zmiany adresu wysyłki i danych do faktury - dopóki sprzedawca nie zacznie realizować zamówienia. O anulowaniu zamówienia sprzedawca dowie się z powiadomienia oraz z informacji w samym zamówieniu**. Obecnie, w przypadku pomyłki czy zmiany zdania, kupujący może poinformować o tym sprzedającego za pomocą formularza zwrotów lub mailowo.

Nowa opcja ułatwi sprzedającym zarządzanie niedokończonymi lub nieudanymi zamówieniami. Dodatkowo, anulowanie zamówienia przez kupującego będzie oznaczać łatwiejszy zwrot prowizji, gdy nie doszło do płatności i sprzedający nie musi oddawać pieniędzy.

Więcej szczegółów o tej zmianie podamy już wkrótce.

(..)

Prośba o informację jak API będzie do tego przygotowane, przynajmniej zgrubnie

**Comment by j4r3kb** [comment]
Dołączam się, bez zmian w API się nie obejdzie.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, planujemy wprowadzenie takich funkcjonalności, pewne prace są już w toku. Na pewno zmiany w API są niezbędne by odpowiednio obsłużyć takie opcje. Nie mamy jeszcze gotowych rozwiązań, z którymi mógłbym się z Wami podzielić, jednak na pewno niezbędne będzie dodanie eventu/ów świadczących o zmianie na zamówieniu, być może także w samym zamówieniu.

**Comment by SebastianOzdoba** [comment]
Z reguły procesy są zautomatyzowane czyli 
READY_FOR -> automat pobiera -> automat robi FA -> automat generuje list przewozowy  -> czas całego procesu to nie dłużej niż 30 min od zdarzenia READY_FOR

Jeśli po tym czasie lub w trakcie Klient anuluje, zmieni dane to mamy pasztet :)
Potrzebujemy tych konkretów szybko i co ważniejsze czasu na wdrożenie zmian w systemach

**Comment by krzyc** [comment]
Jak rozumiem wystarczy zmienić status na PROCESSING i od tego momentu kupujący już zamówienia nie może zmieniać/anulować z poziomu Allegro. Czy dobrze rozumiem?

Jeżeli tak to z chwilą gdy automat ma robić fakturę najpierw zmienia status. Pytanie, czy zmiany nie będą wchodzić z opóźnieniem i czy się nie okaże, że wystawimy fakture do zamówienia sprzed dokonania zmiany lub już anulowanego.

**Comment by SebastianOzdoba** [comment]
Być może tak, natomiast potrzeba dokładnego opisu jak to będzie realizowane i co oznacza [rozpoczęcie realizacji zamówienia]

**Comment by MaciejFrackowiak** [comment]
Gdy tylko będziemy mieli gotowe założenia funkcjonalności opublikujemy komunikat, który mam nadzieję rozwieje wszelkie wątpliwości.
