### ISSUE TITLE
Zmiany Allegro - Allegro UPS Odbiór w Punkcie, UPS Odbiór w Punkcie

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#2967]
Cześć
Od 2.kwietnia mają się pojawić na produkcji
Kiedy będą dostępne na sanbox by można zweryfikować poprawność danych?

**Comment by MaciejFrackowiak** [comment]
Metody Allegro UPS Odbiór w Punkcie (id: "7e113f1c-301a-406b-aa7a-b8654bc8c762") jest dostępna dla kont Firma od dłuższego już czasu - po prostu od 2 kwietnia 2020 zaliczać się będzie ona do metod dostawy Smart (Kupujący posiadający pakiet Smart będzie mógł taką formę dostawy również wybrać).
Natomiast UPS Odbiór w Punkcie zostanie udostępniona dla wszystkich sprzedających dopiero 2 kwietnia 2020 - i od tego dnia pojawi się na produkcji oraz Sandbox. Zasady jednak oznaczania ofert Smart, czy też zamówienia ze Smart oparte na niej będą procesowane tak samo jak każda inna oferta w Allegro ze Smart.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak , dzięki, natomiast jaki będzie guid tego UPS Odbiór w Punkcie?

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Identyfikatory nowych metod:

c576dc1d-4046-4b53-94de-47fc5b6913d4 -UPS Odbiór w Punkcie
e6d9d675-c8cb-4c0f-bcd2-febebfbac3d5	- UPS Odbiór w Punkcie pobranie
