### ISSUE TITLE
Niedozwolone słowo w tekście. O co chodzi?

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#2970]
O co chodzi z tymi niedozwolonymi słowami w tekście opisu?
W trakcie tworzenia "szkicu" dostaję taką informację 
**Czy jest gdzieś jakaś lista takich niedozwolonych słów?**

![Screenshot from 2020-03-18 11-34-37](https://user-images.githubusercontent.com/39965246/76953444-fd65fe80-690e-11ea-9eb5-a80f83013aae.png)

**Comment by MaciejFrackowiak** [comment]
Opis oferty zawierać ma stricte dane dotyczące oferowanego przedmiotu.
Wyrażenie "Przedmiotem aukcji jest" jest sformułowaniem, które nie opisuje przedmiotu, a wyłącznie stanowi wstęp do konkretnej informacji - dlatego zgodnie z pojawiającą się informacją prosimy o jego usunięcie. Nie mamy dostępnej publicznie takiej listy, po prostu na froncie zwracamy w takiej sytuacji odpowiedni komunikat.

**Comment by crazyhtm** [comment]
Aha, rozumiem.

**A jaki komunikat dostanę przez API?**

Bo szkice zostały utworzone przez API i żadnych błędów nie zwróciliście.
Dopiero podczas ręcznego sprawdzenia (czego robić nikt nie będzie) wyświetlacie takie info.

Nie chciałbym żebyście potem mi zdejmowali aukcje, bo nie spodoba Wam się jakiś zwrot którego użyjemy w opisie. 
Albo nie będę mógł wystawić aukcji w ogóle z nieznanych powodów.

**Comment by MaciejFrackowiak** [comment]
Mechanizm ten zaimplementowany jest tylko na stronie WWW - skierowany jest on przede wszystkim do osób, które korzystają z tradycyjnego formularza wystawiania.

**Comment by crazyhtm** [comment]
Ok, rozumiem.

To mam pytanie:

**Czy NIE zdejmiecie nam kilkunastu tysięcy aukcji z powodu tych tzw. "niedozwolonych słów"?**

Bo nie wiem co mam robić.

**Comment by MaciejFrackowiak** [comment]
To pytanie to już kwestia wychodząca poza ramy API - proszę skontaktuj się w tej sprawie poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380).

**Comment by crazyhtm** [comment]
Pozwolę się nie zgodzić, że to pytanie nie dotyczy API. Wszystkie kwestie dotyczące aukcji i ich obsługi dotyczą również API.
Jeżeli wystawiamy kilka, kilkanaście czy kilkadziesiąt tysięcy aukcji to konieczność sprawdzania ich pod jakimkolwiek kątem poprzez stronę WWW jest **"kuriozalna"**. 
A w tym przypadku dochodzi jeszcze brak jasno spisanych zasad. 
Czyli dzisiaj jest tak a jutro może być inaczej. W zależności co się urodzi w głowach Waszych programistów i uda im się zaimplementować. A potem zdejmiecie nam aukcje i koniec.

**Comment by MaciejFrackowiak** [comment]
Dlatego też w przypadku wątpliwości proszę napisz poprzez formularz kontaktowy - otrzymasz wiążącą odpowiedź co do treści, które można zawierać w opisie oferty. Jeżeli się zastosujesz do nich - niezależnie czy to w serwisie WWW, czy wystawiając po API - oferty nie będą usuwane.

**Comment by crazyhtm** [comment]
Ok, dziękuję.
Miłego dnia
