### ISSUE TITLE
brak wypelnionego pola invoice.address dla order/checkout-forms

### ISSUE THREAD

**Issue by mmgithubpl** [allegro/allegro-api#2972]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/order/checkout-forms?status=FILLED_IN

id: "3b1e7107-6912-11ea-bdcf-fbdd22d7ebe3"

pomimo wypelnionych danych dotyczacych faktury rest api zglasza address = null
  "invoice": {
    "required": true,
    "address": null
  },

**Comment by MaciejFrackowiak** [comment]
Jest to prawidłowe zachowanie - dane do faktury zwracamy dopiero, gdy zamówienie przejdzie w status READY_FOR_PROCESSING. Spójrz proszę również do [naszego poradnika](https://developer.allegro.pl/orders/#04) dot. zamówień.

**Comment by mmgithubpl** [comment]
ok - prosze o informacje jak w takim razie mam pobrac dane klienta ktory zazyczyl sobie faktury a jego zamowienie jest caly czas w statusie FILLED_IN? dodam ze na formularzu ms.allegro.pl widac te wszystkie informacje.
moze jest przewidziany mechanizm na podbranie danych dotyczacych karty platnosci (na podstawie id platnosci w tym przypadku zmapowany paymentID na transactionID) ?

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości - jak wspomniałem w REST API dane do faktury zwracamy dopiero, gdy zamówienie jest w statusie READY_FOR_PROCESSING. Dopiero przy statusie RFP zamówienie powinno być realizowane (żeby mieć pewność, że kluczowe dane nie zmienią się).
MS korzysta jeszcze ze starego rozwiązania opartego na WebAPI, gdzie dane do faktury, podobnie jak dane wysyłkowe były od razu dostępne po wypełnieniu formularza pozakupowego.
