### ISSUE TITLE
Problem ze stock['unit'] w sale/offers/{id}

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#2974]
dzień dobry,
Mam dwie oferty o identyfikatorach 8931242841 oraz 9043537299. W pierwszej z nich jednostką sprzedaży jest sztuka, w drugiej paczka. Tymczasem w obu przypadkach endpoint sale/offers/{id} zwraca stock['unit'] = UNIT. Zatem w jaki sposób mogę rozróżnić jednostkę sprzedaży w ofertach?

**Comment by MaciejFrackowiak** [comment]
Jak widzę w ofercie 9043537299 jako jednostka sprzedaży podane jest "sztuka". Słowo "paczka" pojawia się wyłącznie jako parametr dodakowy oferty.
W Allegro jako główne jednostki sprzedaży mamy - sztuka, para, komplet (odpowiednio w API: unit, pair, set).
Tym samym działając w oparciu o API musiałbyś pobrać daną ofertę poprzez GET /sale/offers/{offerId} i następnie w parametrach oferty znaleźć parametr 227441 (Jednostka sprzedaży) i przypisaną do niego wartość ze zbioru dostępnęgo:

```
            "dictionary": [
                {
                    "id": "227441_320781",
                    "value": "sztuka"
                },
                {
                    "id": "227441_320785",
                    "value": "paczka"
                },
                {
                    "id": "227441_320789",
                    "value": "m2"
                },
                {
                    "id": "227441_381561",
                    "value": "brak informacji"
                }
```

**Comment by adamTynski** [comment]
Dziękuję
