### ISSUE TITLE
Usunięcie wymaganego parametru seller.id dla endpoint /sale/offer-contacts

### ISSUE THREAD

**Issue by LompiSystems** [allegro/allegro-api#2977]
Endpoint `/sale/offer-contacts` zwraca listę kontaktów przypisaną do zalogowanego użytkownika.
Jakie w takim wypadku jest sens wymagania parametru `seller.id` który bezpośrednio wynika z `auth_token` przekazanego w nagłówku żądania?
Przecież i tak nie ma możliwości pobrania listy kontaktów przypisanych do innego konta?
Jakie jest logiczne wytłumaczenie na to, że użytkownik najpierw musi pobrać token, zdekodować go żeby wyłuskać `seller.id` a następnie wykonać request z wyłuskanym `seller.id` oraz tokenem z którego go wyłuskał?

**Comment by MaciejFrackowiak** [comment]
Takie podejście do tego zasobu wynika z zakresu danych, które są zwracane - są to dane wrażliwe, dlatego zastosowano tu rozwiązanie zgodnie z [rekomendacją](https://allegro-restapi-guideline.readthedocs.io/en/latest/Resource/#urls-for-users-collections).

**Comment by LompiSystems** [comment]
Ale jaki to ma sens, skoro żeby zrobić request muszę mieć token, a jak mam token to mam też `seller.id`? To już bezpieczniej by było przy formularzu logowania prosić o podanie loginu i maila- bo w części przypadków login nie zawsze będzie zawierał się w mailu.

No ale nawet uznając że ma to jakikolwiek wpływ na bezpieczeństwo (nie wiem w jaki sposób, z chęcią się dowiem), to z poziomu którego endpointa mogę pobrać id właściciela tokenu?

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) zwraca podstawowe informacje o zalogowanym użytkowniku, w tym id konta.

**Comment by LompiSystems** [comment]
Co nie zmienia faktu, ze wymaganie tego parametru jest jak proszenie w formularzu logowania 2 razy o hasło: raz o całe, a drugi raz tylko 3 pierwsze znaki.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem - opieraliśmy się tutaj wyłącznie na rekomendacji jak podchodzić do tego typu zasobów.

**Comment by LompiSystems** [comment]
No ja rozumiem, ale to jest wasza rekomendacja. Może warto by było poddać pod rozważanie zmianę rekomendacji w tym zakresie ;)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje zdanie - przekażę je do osób odpowiedzialnych za rozwój REST API.

**Comment by LompiSystems** [comment]
Co na tą sugestię powiedziały osoby odpowiedzialne za rozwój REST API?

**Comment by MaciejFrackowiak** [comment]
Nie została podjęta dotychczas żadna decyzja - jeżeli w tym zasobie pojawi się jakakolwiek zmiana poinformujemy o niej w osobnym newsie.

**Comment by LompiSystems** [comment]
Skoro już minął przeszło miesiąc, może już wiadomo jak do wspominanej propozycji ustosunkowały się osoby odpowiedzialne za rozwój REST API?

**Comment by MaciejFrackowiak** [comment]
Nie, jeszcze takiej informacji zwrotnej nie ma - jeżeli dokonamy jakiejkolwiek zmiany w tym zasobie to opublikujemy osobny news oraz komunikat.
