### ISSUE TITLE
Tecdoc update date

### ISSUE THREAD

**Issue by miodeusz** [allegro/allegro-api#2978]
Jaki jest harmonogram update dla bazy tecdoc, obecna baza jeszcze jest z 2019 i duzo nowych marek dla czesci jest w ogole niedostepnych.

**Comment by MaciejFrackowiak** [comment]
Staramy się możliwie często aktualizować bazę TecDoc, jednak musimy działać w szerszym kontekście - nasze zmiany w rezultacie mogą dotknąć znacznej ilości ofert w serwisie, szeregu sprzedających, dlatego nie jest to działanie ad hoc i dopiero po zapewnieniu pełnej zgodności względem ofert taką aktualizację wprowadzamy. Wyprzedzając pytanie - na chwilę obecną nie mam możliwości wskazania terminu kiedy przeprowadzimy kolejny update bazy.

**Comment by miodeusz** [comment]
Dziekuje za odpowiedz, prosze zatem za informacje ile razy byla aktualizowana baza tecodc w zeszlym roku?

**Comment by MaciejFrackowiak** [comment]
W 2019 roku pojawiła się jako dostępna w serwisie wersja 0919.

**Comment by miodeusz** [comment]
czyli 1?

**Comment by MaciejFrackowiak** [comment]
Tak.

**Comment by miodeusz** [comment]
dziekuje , do zamkniecia
