### ISSUE TITLE
/sale/images przesyłanie kliku zdjęć na raz

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#2979]
Czy można wysłać wszystkie 10 ( 16) zdjęć odrazu czy każde w osobnym zapytaniu?
Pojedyncze wysyłam bez problemu ale z klikoma dostaję błąd

`[
   {
        "url": "https:....jpg"
    },
    {
        "url": "https:....jpg"
    }
]
`

**Comment by MaciejFrackowiak** [comment]
Zdjęcia przesyłamy pojedynczo, dla każdej operacji uzyskasz osobny adres URL zdjęcia z naszego serwera.

**Comment by DanielMiara** [comment]
Dzięki, wyjaśnione
