### ISSUE TITLE
how to get my auth code in right way?

### ISSUE THREAD

**Issue by tan133** [allegro/allegro-api#2981]
I am a new allegro devoloper
I have register a app account by my account 
I want to get auth code by use the below url
###  _https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=xxxxxxxxxxxxxxxxxx&redirect_uri=https://www.tg61.com/allegro_

I have 4 questiones to ask

------question 1-------about get auth code--------->
at the begin,it works well,
but if I have more than one accout
when I get a cdoe,how I can know this code  belong to which accout?
I have to save my account twice? 
one  in my application,and one in web login page?
is there a better way?

------question 2-------about add product--------->
if I add a product on the web,there is a optinal field named  Sygnatura (opcjonalnie)
but I don't find any api document about it,
if I want set it in by API,how can I do?

------question 3------about change Multiple proudcts's state by use  Multiple ids in one time------>
if I want list the  2 or 3 or more product by use them ids in one time
is there  some way like this:
(allegro.pl/{action=delete or list}?ids={id1,id2,id3,id4})

------question 4--------about get auth code--------->
after many time test in serval days ,
it redirct to  the below url instead,
is my application account or my shop account get some wrong?how can I correct it?
### _https://allegro.pl/uzytkownik/bezpieczenstwo/dwustopniowe-logowanie_

by the way,the above url finally show text as end of this issue,
I had search them under issue,and can't get any
but when I write this ,it says 4 existing issues with mine,
if have ,please show them to me ,thanks

in the end,the wrong redirect page content
Chcesz mieć bezpieczniejsze konto?
Skorzystaj z dodatkowej ochrony.

Podczas logowania na nowym urządzeniu, pojawi się dodatkowe
pole na wpisanie kodu z Twojego telefonu. Dowiedz się więcej

**Comment by MaciejFrackowiak** [comment]
I will try to give some answers for you questions:

1) in that case you should use parameter "state" - when you use it in request, you will receive it also in response - so you will be able to identify account. Please, look into [our tutorial](https://developer.allegro.pl/en/auth/#user) about authorization;

2) in API "Sygnatura" is available in a field "external.id";

3) in that case you should use resource [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT), offerCriteria consists array of objects with offer IDs (max 1000).  Here check [our tutorial](https://developer.allegro.pl/en/sale/#step-9-offer-publication-commands) too;

4) Dwustopniowe logowanie (Two Factor Authentication) allows to protect your Allegro account more securly with SMS code when you log into account. We describe it in [Allegro General Help](https://allegro.pl/pomoc/dla-kupujacych/logowanie-i-haslo/dwustopniowe-logowanie-najczesciej-zadawane-pytania-dykqg9nMKSZ).

**Comment by tan133** [comment]
got them,thanks about that,

**Comment by tan133** [comment]
more question about question1
 when user  use my application and visit the page
 https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=XXXX&redirect_uri=XXXX&
state=somestring
user have to login a account by keyboard input
if success,responce url like  
........?code=xxxxx&state=somestring
right?

but now ,i still don't know user use which account login 
that means i don't know the reply code relate to which account?
how to deal this problem?
i don't think use code to get what user input in username textbox is a good way
that make applition actions like a thief.

can it use some way like this:
........client_id=XXXX&redirect_uri=XXXX&&username=base64(a@b.pl)
and the webpage force only username a@b.pl can be use this time
or can responce like this
.......code=xxxxxx&username=base64username

**Comment by MaciejFrackowiak** [comment]
Maybe you should use PKCE mechanism - it allows protect your application against the use of authorization_code by malicious software - we describe it our tutorial which link I added in earlier post.
