### ISSUE TITLE
Czy jest możliwość filtrowania /offers/listing po wartości Model, Rok? 

### ISSUE THREAD

**Issue by lukassoft** [allegro/allegro-api#2983]
Witam

Jak w tytule, czy można odfiltrować listę zamówień po roku lub modelu, podaje 
np. {parameter.1=2019}, ale niestety lista zamówień nie uwzględnia tego filtra. 

Może należy to jakoś inaczej zapisać?

**Comment by MaciejFrackowiak** [comment]
Podajesz adres do zasobu od listingów, a wspominasz o zamówieniach - proszę doprecyzuj.

**Comment by lukassoft** [comment]
Przepraszam oczywiście chodzi mi o listing ofert.

**Comment by MaciejFrackowiak** [comment]
Dla zasobu GET /offers/listing dostępne są dynamiczne filtry, które są zależne od tego czego szukasz, w jakiej jesteś kategorii, etc.

Przykładowo, dla kategorii 12525 wśród dostępnych filtrów pojawia się:

```
{
            "id": "parameter.1",
            "type": "NUMERIC",
            "name": "Rok produkcji",
            "values": [
                {
                    "idSuffix": ".from",
                    "name": "od",
                    "selected": false
                },
                {
                    "idSuffix": ".to",
                    "name": "do",
                    "selected": false
                }
            ],
            "minValue": 1900,
            "maxValue": 2100,
            "unit": ""
        }
```

**Comment by lukassoft** [comment]
Zgadza się pobieram sobie listę parametrów dla danej kategorii i staram się wyszukać wg. wybranych filtrów. 

np. 
![parametry](https://user-images.githubusercontent.com/62422516/77153757-a8ef8a00-6a9a-11ea-8bb1-055179d58045.png)

W odpowiedzi dostaję listę ofert spełniających wszystkie powyższe parametry poza rokiem produkcji (ostatni parametr), dlatego zastanawiam się czy działa filtrowanie po roku, czy powinienem inaczej wysłać zapytanie ?

**Comment by MaciejFrackowiak** [comment]
Rok produkcji to parametr zakresowy, stąd niezbędne jest użycie .from lub/i .to, wówczas filtr wygląda tak:

parameter.1.from=dana wartość
parameter.1.to=dana wartość

Dla Twojej kategorii:

```
GET /offers/listing?category.id=257691&parameter.1.from=2019&parameter.1.to=2019
```

**Comment by lukassoft** [comment]
Super, o to chodziło, dziękuje bardzo, może warto dopisać do dokumentacji przy parametrach dynamicznych bo nie znalazłem tam informacji. 

Panie Maciej może udał się jeszcze rozwiązać problem z modelem bo też mam z nim problem (nie zawęża mi listy do podanego modelu) - zaznaczyłem na żółto. 
 
![parametry2](https://user-images.githubusercontent.com/62422516/77156630-00442900-6aa0-11ea-89a5-1eff5d8b7e01.PNG)

**Comment by MaciejFrackowiak** [comment]
Informacja znajduje się przy parametrze np. **"idSuffix": ".from"**

Natomiast odnośnie parametru 217737 - listing dla kategorii 257689 nie zwraca go jako dostępny filtr, dlatego podanie wartości nie zwróci wyników.
Wyszukiwarka jednak zwraca wartości dla parametru Model, gdy poda się je w "phrase" - identyczny mechanizm działa na stronie WWW.

**Comment by lukassoft** [comment]
Ok. Już wszytko jasne. Dziękuje za pomoc.
