### ISSUE TITLE
GET /sale/offer-variants/{setId}

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#2984]
:bulb: **Sugestia**

Dodajcie w węźle **offers** dodatkowo tytuł aukcji. Sam numer to za mało. Później jest kombinowanie z wyświetleniem użytkownikowi jakie aukcje wchodzą w skład oferty co wszystko wydłuża.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię - przekazuję do działu odpowiedzialnego za rozwój REST API.
