### ISSUE TITLE
Dlaczego nadal mogę pobrać dane o niektórych aukcjach przeniesionych do archiwum?

### ISSUE THREAD

**Issue by Masakrancja** [allegro/allegro-api#2985]
Witam,
Dlaczego nadal mogę pobrać dane o niektórych aukcjach przeniesionych do archiwum?

https://api.{environment}/sale/offers?offer.id=8155108511
https://api.{environment}/sale/offers?offer.id=7915603245

Aukcja 8155108511 została zakończona: 2019-06-01T15:58:22Z
Aukcja 7915603245 została zakończona: 2019-06-03T11:29:07Z

Pozdr.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - problem przekazałem już do właściwego działu.
