### ISSUE TITLE
API sale/images zwraca kod 500

### ISSUE THREAD

**Issue by MikeFDye** [allegro/allegro-api#2986]
podczas próby przesłania obrazów przez interfejs API do adresu URL https://upload.allegro.pl/sale/images  bardzo często
Otrzymujemy odpowiedź HTTP z kodem 500 i opisem błędu:
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}
Z czym jest to związane i co powinniśmy zrobić, aby wysyłanie odbywało się bez błędów?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam przykład takiego requestu wraz z trace-id. Sprawdziłem działanie zasobu - bez najmniejszych problemów przesłałem zdjęcie ze statusem 201.

**Comment by MikeFDye** [comment]
nie każdy request zwraca błąd, zwykle okazuje się, że około 20 requestów, a następnie zaczyna zwracać błąd. 
Oto przykład odpowiedzi, gdy zwrot nie jest udany
("trace-id":"69d453595e63feca")

{"http_status":"HTTP\/2 500","expires":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":"1 ; mode=block","server":"envoy","pragma":"no-cache","x-frame-options":"DENY","trace-id":"69d453595e63feca","referrer-policy":"no-referrer","date":"Fri, 20 Mar 2020 12:18:12 GMT","x-content-type-options":"nosniff","content-type":"application\/json; charset=utf-8","content-length":"181","x-envoy-upstream-service-time":"2132"}

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład - weryfikujemy go.

**Comment by MaciejFrackowiak** [comment]
Problem okazał się bardziej złożony aniżeli wykazała wstępna analiza, dlatego musimy zaangażować większe środki - wrócę z odpowiedzią, gdy będę mógł już dać konkretne info.
