### ISSUE TITLE
Zgłaszanie ofert do kampanii

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#2987]
Zgłosiłem sobie ofertę do kampanii COMMISSION_DISCOUNT_17032020, id zgłoszenia 70be1c3b-4046-4f8d-ac20-8516a16dde72. Wszystko ok, status zgłoszenia PROCESSED, kampania ma status WAITING_FOR_PUBLICATION.

Przy odświeżaniu danych oferty pobieram jej zawartość (GET
/sale/offers/), wprowadzam swoje zmiany, pobieram kampanie (GET /sale/badge-campaigns) i jeśli mam kampanię status === ACTIVE i jakąś zawartość w polu price, to przywracam cenę Kup Teraz do stanu, który otrzymałem od REST API (żeby jej nie nadpisać niezrabatowaną wartością). W testach na sandboksie nawet to działało.

Więc teraz najpierw dostałem WAITING_FOR_PUBLICATION i puste prices (a kampania typu DISCOUNT, podawałem cenę bargain). Przy kolejnej aktualizacji dostałem już status ACTIVE, ale nadal puste prices, czyli tak jakby kampania była typu STANDARD. Więc mój skrypt podał w strukturze standardową, niezrabatowaną wartość Kup Teraz. Przy kolejnych próbach status kampanii to IN_VERIFICATION, prices nadal puste. Zapewne chodzi o to, że zmieniłem zrabatowaną cenę na oryginalną i dlatego kampania poleciała do weryfikacji.
W żadnym momencie nie widziałem na frontendzie Allegro, by cena w ofercie się zmieniła.

Tak więc:
1. Jak powinienem teraz postępować z tą ofertą, żeby nie wyleciała z kampanii? 
2. Czy puste prices w GET /sale/badge-campaigns dla kampanii typu DISCOUNT to nie błąd?

**Comment by MaciejFrackowiak** [comment]
W kwestii funkcjonowania kampanii proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022).

**Comment by deneb-k** [comment]
No OK, ale jak tam mi odpiszą, że nie mogą mi odpisać, bo nie piszę z konta, które wystawiło ofertę, to będę bardzo zły.

**Comment by MaciejFrackowiak** [comment]
Rozumiem, jednak w kwestii konkretnej kampanii zgłaszanej na danym koncie powinna kontaktować się z nami osoba zarządzająca danym kontem.

**Comment by deneb-k** [comment]
No to zapomnijmy, że podałem przykład. Proszę o ogólną odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Ogólna odpowiedź:

1) Aby oferta pozostała w kampanii należy na niej nie zmieniać ceny po zgłoszeniu do kampanii;
2) Nie, to nie błąd - [GET /sale/badge-campaigns](https://developer.allegro.pl/documentation/#operation/badgeCampaigns_get_all) nie ma pola "prices".

**Comment by deneb-k** [comment]
1. Czyli nawet gdy kampania ma status WAITING_FOR_PUBLICATION, to nie mogę zmieniać ceny oferty? 
2. Podałem zły endpoint. Chodziło mi oczywiście o GET
/sale/badges, czyli pobieranie kampanii przypisanych do danej oferty. Tu dla kampanii DISCOUNT dostaję pole prices, ale jest puste.

**Comment by MaciejFrackowiak** [comment]
1. Cena została zmieniona minutę po tym jak system nadał jej oznaczenie, dlatego nie powinno dokonywać się żadnych zmian;

2. Dla kampanii w stanie FINISHED, DECLINED cena nie jest zwracana - wszak kampania zakończona bądź odrzucona.

**Comment by deneb-k** [comment]
1. Zmieniona, bo...
2. Dla kampanii w stanie ACTIVE też nie jest zwracana. Sprawdzałem czy status jest ACTIVE i czy mam coś w prices, jeśli oba warunki spełnione, to nie zmieniałem ceny. Ale skoro prices nie działa, to przerobiłem, by sprawdzało typ aktywnej kampanii (konieczne było kolejne zapytanie do API) i jeśli jest ona typu DISCOUNT lub SOURCING, to wtedy nie zmieniam ceny. I jak na razie działa.

**Comment by MaciejFrackowiak** [comment]
1. Chcąc by oferta pozostała w kampanii nie należy na niej dokonywać żadnej zmiany ceny po zgłoszeniu do kampanii. W tym konkretnym przypadku dokonano zmiany ceny minutę po tym jak system badge’owy dokonał zmiany;

2. Dla kampanii typu "discount" i "sourcing" zmieniamy cenę i dla tych typów kampanii GET /sale/badges będzie zwracało fragment z uzupełnioną wartością "prices". W skrócie - jeżeli kampania oparta jest na cenie to pole "prices" będzie wypełnione wartością.

**Comment by deneb-k** [comment]
Ale nie jest.

**Comment by MaciejFrackowiak** [comment]
Zgłoszenie o id="70be1c3b-4046-4f8d-ac20-8516a16dde72" zostało przeprocesowane - dla oferty, której dotyczy przy odpytaniu GET /sale/badges zwracamy status DECLINED z komunikatem:                          

```
 "text": "The proposed offer price is incorrect. The maximum price is on the list of products for this campaign",
```
Jeżeli masz aktualny przykład oferty, która wg Ciebie jest nieprawidłowo zwracana to proszę podaj go nam - najlepiej poprzez formularz kontaktowy, ponieważ szczegóły dot. zgłaszanej ceny są w jej kontekście danymi wrażliwymi.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem przesłany przez Ciebie nowy przykład - zgłoszona kampania to kampania typu SOURCING. I rzeczywiście, w odpowiedzi dla GET /sale/badges nie ma dla niej uzupełnionej wartości w polu "prices" - jest to prawidłowe. Z naszej strony poprawimy dokumentację, cena powinna być zwracana tylko dla kampanii typu DISCOUNT.

**Comment by esprzedaz** [comment]
OK, dzięki.
