### ISSUE TITLE
Best way to get the advertised delivery time

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#2988]
What is the best way to get the delivery estimation details for a given checkoutForm? (i.e. when the advert says "Kurier DHL - 9,95 zł - wt. 24 mar. u Ciebie")

Is there an easy way to get that information, rather than having to make an API call to `GET https://api.allegro.pl/sale/delivery-methods`, and then traversing through the list for the matching delivery-method?

**Comment by MaciejFrackowiak** [comment]
No, there is no easy way to get this data. When you call GET /sale/delivery-methods you will receive only name of the delivery method, but no time. From March 5, 2020 we show estimated delivery time based on our statistics, not directly from offer description - please, check [our article](https://allegro.pl/pomoc/aktualnosci/od-dzis-wszyscy-kupujacy-zobacza-czas-wysylki-i-dostawy-na-podstawie-naszych-obliczen-68RglMwL4ia).

**Comment by jguthriedodax** [comment]
Is it possible to make a request to the API design team to include the handling time and estimated time of delivery in the checkoutForm response

**Comment by MaciejFrackowiak** [comment]
Could you give us a reason why do you want this information in checkoutForm?

**Comment by jguthriedodax** [comment]
I need to basically get a record of how long our dispatch team has to process the order before shipping it, and so we know if we're taking too long etc.

I don't think the final arrival date is relevant, but the PT24H or PT48H etc information would be really useful!

**Comment by MaciejFrackowiak** [comment]
handlingTime (in delivery section) which you set to offer you can retrieve by GET /sale/offers/{offerId} - but as I wrote before - from March 5, 2020 we show on offer handlingTime based on history records from yours shipments.
