### ISSUE TITLE
GET offers/listing  jak dodać FILTR: Nowe/używane

### ISSUE THREAD

**Issue by rydzyk184** [allegro/allegro-api#2989]
Witam. 
Korzystam z generatora RSS https://github.com/Krukosz/Allegro_REST_RSS
Parametr offerCondition=2 dotychczas dawał wyniki przedmiotów używanych.
Teraz niezależnie od zmiennej ładuje wszystkie oferty zarówno nowe jak i używane. 
Problem występuje już od dość dawna.
Bardzo proszę o pomoc jak naprawić lub na nowo dodać do w/w skryptu który używam ja i wiele innych osób możliwość filtracji wyszukiwanych ofert: Nowe/Używane.

**Comment by MaciejFrackowiak** [comment]
Aplikacja, z której korzystasz używa nadal starego rozwiązania do pobierania danych o stanie przedmiotu. Obecnie parametr "Stan" posiada swoje parameter.id=11323 i to na nim powinna zostać oparta logika aplikacji. W tym miejscu niezbędne jest dokonanie zmian przez autora oprogramowania.

**Comment by rydzyk184** [comment]
Dziekuje za zainteresowanie. Słabo sie znam ale z tego co widze w kodzie aplikacji wywołując polecenie ''offerCondition'' odnosze sie do ''parameter.11323''
  
 159 linia kodu `'parameter.11323' => $offerCondition`

Czyli w/w linka kodu ma wyglądac następująco ?? `'parameter.id=11323' => $offerCondition`  
Jeśli nie to prosze mnie poprawic.

**Comment by MaciejFrackowiak** [comment]
Fajnie, że udało Ci się dokonać zmiany i oprogramowanie poprawnie już zwraca wyniki.
