### ISSUE TITLE
Błędne dane dla produktu bf9aa013-25d1-4c00-b725-05879d9bb039

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#2990]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wyszukiwaniu produktu po frazie "MAXGEAR 47-0052" otrzymuję produkt o w/w id.
Jest to pompa wody, ale w otrzymanych danych jest to:
name: "Filtr powietrza MAXGEAR 47-0052"
category.id: 49241 (Filtry powietrza)

Reszta danych, czyli "Numery katalogowe zamienników", "Numer katalogowy oryginału", dane z tecdoc wyglądają już prawidłowo (czyli dotyczą pompy wody)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - przekazałem je do właściwego działu.

**Comment by MaciejFrackowiak** [comment]
Wracam z informacją zwrotną - dane produktu pochodzą z TecDoc, dlatego rozbieżność zgłosiliśmy bezpośrednio do dostawcy danych.
