### ISSUE TITLE
Jak pobrać informację o dacie ostatniej sprzedaży oferty?

### ISSUE THREAD

**Issue by pokrz26** [allegro/allegro-api#2991]
Czy istnieje możliwość, aby jakoś pobrać informacje o dacie ostatniej sprzedaży oferty lub ofert, które nie sprzedały się od podanej daty?
Jeżeli nie ma takiej możliwości to jak pobrać oferty, którym zostanie naliczona opłata utrzymaniowa?

Nie mogę znaleźć w API niczego dedykowanego tym funkcjonalnościom.

**Comment by pokrz26** [comment]
Dziękuję za informacje ale mam jeszcze jedno pytanie.
W opisie /pricing/offer-quotes wystepują takie rodzaje płatności:

```
...
"type": "LISTING",                                    -- rodzaj opłaty, dostępne są wartości: 
    LISTING, 
    BOLD, 
    HIGHLIGHT, 
    EMPHASIZED, 
    EMPHASIZED_HIGHLIGHT_BOLD_PACKAGE, 
    DEPARTMENT_PAGE, MIN_PRICE, 
    BARGAIN
"name": "Wystawienie",                                -- nazwa opłaty, dostępne są wartości: 
    Wystawienie, 
    Pogrubienie, 
    Podświetlenie, 
    Wyróżnienie, 
    Pakiet promo, 
    Strona działu, 
    Cena minimalna, 
    Okazja
...
```

Nie widzę tutaj odpowiednika opłaty utrzymaniowej. Jak więc nazywa się typ dla takiej opłaty?

**Comment by MaciejFrackowiak** [comment]
Nazywa się "INEFFECTIVE_LISTING_FEE" - opublikowaliśmy osobny [news](https://developer.allegro.pl/news/2018-07-18-aktualizacja_zasob_do_sprawdzania_daty_oplaty/) w związku z wprowadzeniem tej opłaty.

**Comment by pokrz26** [comment]
Dziękuję bardzo za informacje.
