### ISSUE TITLE
Na stronie aukcji wyświetlana jest inna wartość czasu wysyłki niż zwracana w `API`

### ISSUE THREAD

**Issue by martasobota** [allegro/allegro-api#2992]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Problem znaleźliśmy narazie dla dwóch aukcji, ale najprawdopodobniej jest ich więcej. 

Przy zapytaniu `https://api.allegro.pl/sale/offers/<auction_id>` dostaję zwrotkę o innym czasie dostawy `delivery handlingTime` niż jest wyświetlany na stronie aukcji.

**Przykład 1:**
'https://api.allegro.pl/sale/offers/8940305401` zwraca poprawnie `"handlingTime": "PT0S",`, natomiast na stronie aukcji wyświetla się `Czas wysyłki zwykle do 3 dni roboczych`.

Czas został zaktualizowany 19 marca o 22:07

<img width="640" alt="Oferta 1 handling time" src="https://user-images.githubusercontent.com/22544944/77255423-8f4f6d80-6c67-11ea-996f-91b8ec44b78a.png">

<img width="1072" alt="Zrzut ekranu 2020-03-22 o 17 51 15" src="https://user-images.githubusercontent.com/22544944/77255301-a6da2680-6c66-11ea-80e2-acbc54f08df4.png">

**Przykład 2:**
`https://api.allegro.pl/sale/offers/8631752456` - Do wczoraj wyglądał tak samo jak powyższy. Czas wysyłki został zaktualizowany 19 marca o 23:59 na `PT0S` i tak zwracało `API`, w na stronie aukcji wyświetlał się `Czas wysyłki zwykle do 3 dni roboczych`.
Aukcja została zaktualizowana dziś rano na inny czas, stąd `API` zwraca to samo, co strona aukcji.

<img width="480" alt="Noz " src="https://user-images.githubusercontent.com/22544944/77255386-4f888600-6c67-11ea-8105-770af0ebffb0.png">

Dziś aukcja wygląda tak samo, ale to jest akurat printscreen z wczoraj, kiedy `API` zwracało `"handlingTime": "PT0S",`:

![Noz nowy](https://user-images.githubusercontent.com/22544944/77255343-e739a480-6c66-11ea-9c58-31012fd9f41f.png)

**Comment by MaciejFrackowiak** [comment]
Zmiana w wyświetlaniu czasu wysyłki związana jest ze zmianą, którą wprowadziliśmy w Allegro 5 marca - od teraz w ofercie wyświetlamy czas na podstawie zebranych danych statystycznych dla konkretnego sprzedającego. Szczegółowy opis znajdziesz na stronie [dla sprzedających](https://allegro.pl/dla-sprzedajacych/od-dzis-wszyscy-kupujacy-zobacza-czas-wysylki-i-dostawy-na-podstawie-naszych-obliczen-YL4ynrxVafe).
