### ISSUE TITLE
Ukrywanie ofert

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#2993]
Witam
Nie znalazłem w dokumentacji metody do ukrywania ofert, czy planowane jest udostępnienie takiego zasobu ?
pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Zgadza się, nie mamy obecnie takiego zasobu. Znajduje się on natomiast na liście sugestii dot. rozwoju REST API Allegro - dodaję także Twój głos.
