### ISSUE TITLE
How to request details of the offer

### ISSUE THREAD

**Issue by koticik** [allegro/allegro-api#2994]
How to request details of the offer

According to your instructions, I managed to request a list of categories
https://api.allegro.pl/sale/categories
and a list of offers in the category upon my request.
https://api.allegro.pl/offers/listing?category.id=3&phrase=Audi+wentylator
I did all this with authorization
"Authorization: Bearer $ token",
"Accept: application / vnd.allegro.public.v1 + json"

But as I am not trying to get the details of a specific proposal, it does not work out for me.
https://api.allegro.pl/sale/offers?offer.id=7955642316 resultCode = 500

Actually the question is whether it is possible to somehow obtain a detailed description of the proposal by its ID
Using bearer-token-for-application authorization
I don’t want to create or change offers on the site, I just need to get the information that the user sees when he clicks on a specific offer.
What is in the section Parametry and Opis on the site.

**Comment by MaciejFrackowiak** [comment]
No, you won't get offer details if you use client_credentials authorization (bearer-token-for-application).
That data is only available for authorized user using code_flow or device_code.
Please, check [our tutorial](https://developer.allegro.pl/en/auth/#CredentialsFlow).

**Comment by koticik** [comment]
Hello.
I created a new application and received a token as you recommended.
curl -X POST -H 'Authorization: Basic YTI ... Hg =' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'
I search for offers and get an answer
[0] =>
  array (9) {
    ["id"] =>
    string (10) "7955642316"
    ["name"] =>
    string (44) "Wentylator Lampy Led Audi A6 4G0 Lift Matrix"
    ["seller"] =>
    array (3) {
      ["id"] =>
      string (8) "45294287"
      ["company"] =>
      bool (true)
      ["superSeller"] =>
      bool (true)
    }

Now I want to see additional options for this offer.
But I can’t do this:
https://api.allegro.pl/sale/offers/7955642316 "
 "{" errors ": [{" code ":" FORBIDDEN "," message ":" Forbidden "," details ": null," path ":" / sale / offers / 7955642316 "," userMessage ": null}] }

https://api.allegro.pl/sale/offers?offer.id=7955642316 
"string (38)" {"offers": [], "count": 0, "totalCount": 0} "int (200)

in the first case I get a ban, in the second I get an empty array.
Tell me how I can see what a simple UNAUTHORIZED caller sees after he has used the search on your site and selected a specific offer in the list of search results.

**Comment by MaciejFrackowiak** [comment]
You cannot see details of an offer if you are not an owner (seller) of this offer.
So when you called GET /sale/offers{offerId} you received 403 and it is correct - you are not a seller of that offer.

**Comment by koticik** [comment]
I understand that I am not the owner of this offer.
But if this mechanism does not work, I do not understand how otherwise I can see information about the product.
I need to get the information that all site visitors see at the bottom of the page under the photo.
If we talk about the proposal ID which I wrote in the last message, I want to get a description of the Parametry section
Status, catalog number and so on.
Please answer if the opportunity to get this information, without it searching the site does not make sense.
Is the only possibility is parsing the entire page of the site?

**Comment by MaciejFrackowiak** [comment]
Via REST API it is impossible now - we don't have any resource yet to get this data if you aren't a seller of that offer.
This data can be obtain by WebAPI methods - [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,1093) or [doShowItemInfoExt](https://allegro.pl/webapi/documentation.php/show/id,1127).

**Comment by achchu93** [comment]
I user this endpoint `https://developer.allegro.pl/auth/#app` and still face FORBIDDEN issue. Really helpful if you can help.

**Comment by PrzemyslawLukanowski** [comment]
@achchu93 If you're not the owner of these offers, you will receive 403 Forbidden. You can retrieve only your offers via GET /sale/offers/{offerId}.
