### ISSUE TITLE
Historia zmian cen

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#2995]
Chciałbym się dowiedzieć czy jest możliwość sprawdzenia zmian cen w aukcjach różnych sprzedających?
Jak rozumiem zasób /offers/listing zawiera tylko aktualną cene.

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości. Zasób GET /offers/listing zwraca tylko aktualną cenę.

**Comment by kylovile** [comment]
Dziękuje za szybką odpowiedź. To jeszcze inne pytanie, czy jest możliwość pobrania historii zakupów (kto i za ile i kiedy) w ofertach różnych sprzedających.

**Comment by PrzemyslawLukanowski** [comment]
Przez REST API nie ma takiej możliwości, sprawdzisz to za pomocą metody Web API - [doGetBidItem2](https://allegro.pl/webapi/documentation.php/show/id,44#method-output).

**Comment by kylovile** [comment]
Kiedy ta metoda ma zostać wygaszona?

**Comment by PrzemyslawLukanowski** [comment]
Z końcem roku, szczegóły znajdziesz w [naszym harmonogramie](https://developer.allegro.pl/schedule/).
