### ISSUE TITLE
Nieaktualna kategoria dla kilku produktów MAXGEAR

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#2996]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wyszukiwaniu produktów MAXGEAR o kodach:
AC154857, 10-0180, 10-0181, 10-0182, 10-0183
Otrzymuję kategorię która już nie istnieje 260950.
Obecnie zmapowana na 258684 - nie jest to już leaf i została rozbita na subkategorie
prawidłowa kategoria (według mnie) dla tych produktów to 258697

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie, przekazałem ten problem do odpowiedniego zespołu.
