### ISSUE TITLE
Błędy walidacji parametrów specyficznych

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#2997]
:bulb: **Sugestia**
Prosiłbym o zwracanie tychże błędów w bardziej czytelny sposób.

```json
"validation": {
        "errors": [{
            "code": "VALIDATION_ERROR",
            "message": "You can only assign dictionary parameter by valueId for 130411.",
            "details": "",
            "path": "",
            "userMessage": "Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 130411."
        }, {
            "code": "VALIDATION_ERROR",
            "message": "Nie podano wartości dla parametru 130411.",
            "details": "",
            "path": "",
            "userMessage": "Nie podano wartości dla parametru 130411."
        }],
```

Użytkownikowi końcowemu w zasadzie parametr 130411 niewiele mówi. Czy można by to zmienić na nazwę parametru z ewentualnie jego numerem (w sekcji details?). Bo teraz to nie wiadomo, czy mamy to po swojemu tłumaczyć na ludzki język, bo znów nie ma za bardzo sposobu aby odróżnić błąd parametru od innego błędu, więc trzeba parsować stringa - co ma znów krótkie nogi dosyć, bo lubicie też zmienić te stringi i wtedy kładzie się cały algorytm :).
W starym API parametry miały przynajmniej postać FID_130411, wiec można było ustalić, że chodzi o parametr specyficzny i jaki.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię. Przekazuję je do zgłoszenia związanego z doprecyzowaniem komunikatów błędów.

**Comment by PhotoSoft** [comment]
Pan przekazuje, a zespół, który za to odpowiada ignoruje. Już dawno było to zgłaszane...
