### ISSUE TITLE
Opłata za utrzymanie oferty - sprzedaż oferty

### ISSUE THREAD

**Issue by ircykk** [allegro/allegro-api#2998]
W jaki sposób można sprawdzić czy oferta miała sprzedaż w ostatnim roku i podlega lub będzie podlegać opłacie za utrzymanie oferty? 

Endpoint `/sale/offers/{offerId}` nie podaje nam takiej informacji.

**Comment by PrzemyslawLukanowski** [comment]
Nie zwracamy informacji, czy oferta miała sprzedaż w ciągu ostatniego roku. Opłatę utrzymaniową sprawdzisz za pomocą zasobu [GET /pricing/offer-quotes](https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET). W polu type zwracamy wtedy wartość INEFFECTIVE_LISTING_FEE.
