### ISSUE TITLE
[ sandbox] różnica pomiędzy danymi na waszej stronie a via RestAPi 

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#2999]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Trace ID
55bc0dabbd1157b

Dzień dobry, środowisko testowe via Rest
zwraca oferty których nie ma (trejs ajdi powyżej).
Na waszej stronie tych ofert nie widać :)
Jakiś błąd ? 

www factory

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem dla 9 ofert. Przekazalem problem do odpowiedniego zespołu.

**Comment by wwwfactory** [comment]
poproszę więc o wykasowanie starych - te z roku 2018, proszę zostawić tylko to co jest w tego miesiąca.
Dziękuję 
www factory

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem prośbę o usunięcie archiwalnych ofert.

**Comment by wwwfactory** [comment]
Ponawiam prośbę o usunięcie danych których "nie ma"
dziękuję

**Comment by PrzemyslawLukanowski** [comment]
Problem został już zaadresowany do odpowiedniego zespołu, prośba o cierpliwość. Po usunięciu danych poinformuję w tym wątku.

**Comment by PrzemyslawLukanowski** [comment]
@wwwfactory Usunęliśmy stare oferty.
