### ISSUE TITLE
Nieprawidłowo zwracane nulle w API

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#3]
Pozwolę sobie przenieść issue z FB tutaj, aby nam nie uciekł.
Oryginalny link: https://www.facebook.com/AllegroAPI/posts/1769524900015514?comment_id=1773083092993028&comment_tracking=%7B"tn"%3A"R7"%7D

DoGetItemsInfo w przypadku pustego EAN-u zwraca w polu itEan "NULL" jako string (<ns1:itEan>NULL</ns1:itEan>). Chyba powinien być to pusty string (<ns1:itEan></ns1:itEan>) lub wartość null (<ns1:itEan xsi:nil="true">). To samo dotyczy itStandardizedDescription, itContact..

**Jest:** `<ns1:itEan>NULL</ns1:itEan>`
**Powinno być:** `<ns1:itEan></ns1:itEan>` lub `<ns1:itEan xsi:nil="true" />`

**Comment by MarcinLuczak** [comment]
Dziękuję za zgłoszenie. Przekazałem go do innego działu do analizy. Dam znać, gdy będę miał nowe informacje na ten temat.

**Comment by MarcinLuczak** [comment]
@rtnet-pl 

Problem został usunięty.
