### ISSUE TITLE
Infromacja o płatności przelewy24

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#300]
Właczyliśmy przelewy24 na swoim koncie i teraz mamy potrzebę rozróżniania czy klient zapłacił przez payu czy przez przelewy24.
Gdzie znajdę ta infromację w API?

**Comment by LukaszKorek** [comment]
Za pomocą API nie sprawdzisz czy było to PayU czy Przelewy24. Otrzymasz informację, że płatność była za pomocą Allegro Finanse.

**Comment by gromusek** [comment]
@LukaszKorek  Wiadomo kiedy taka metoda zostanie dodana? Jest to problematyczne jak się ma P24 oraz Pay24 przy automatycznych rozliczeniach.

**Comment by LukaszKorek** [comment]
Pracujemy nad rozwojem REST API i być może takie rozwiązanie tam się pojawi. Dziękujemy za sugestię, przeanalizujemy ją.
