### ISSUE TITLE
https://api.allegro.pl/sale/offer-variants?user.id=XXXXXX zwraca error 500

### ISSUE THREAD

**Issue by robosobo** [allegro/allegro-api#3000]
Jak w temacie, ustawianie limitu na np 10 wyników nic nie zmienia.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałeś status 500, ponieważ użyłeś tokena, którego otrzymałeś za pomocą autoryzacji client credentials - bez kontekstu użytkownika. Skorzystaj z autoryzacji typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow), aby dostać prawidłową odpowiedź.
