### ISSUE TITLE
504 - Gateway timeout

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3002]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Obserwujemy problemy z metodami restAPI, zwracają nam 504. Dziś to jest kilkadziesiąt razy
Przykładowe wywołania

curl -X GET \
  'https://api.allegro.pl/sale/offers?limit=1' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: 

RESPONSE 2020-03-24 12:22:24.3522430 Duration: 20017,4013ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Timeout to the backend service.",
        "Path": null,
        "UserMessage": "Internal server error. Please try again in a few minutes."
      }
    ],
    "ValidatedAt": null

REQUEST 2020-03-24 13:34:30.3818605 
curl -X GET \
  'https://api.allegro.pl/sale/offers?offer.id=8290939858&limit=20' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \

RESPONSE 2020-03-24 13:34:50.4174858 Duration: 20035,6253ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Timeout to the backend service.",
        "Path": null,
        "UserMessage": "Internal server error. Please try again in a few minutes."
      }
    ],
    "ValidatedAt": null

REQUEST 2020-03-23 08:19:24.3289099 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU4NDk0NjM5MTY5NDkxNA&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-03-23 08:19:27.3459032 Database:Duration: 3016,9933ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (504) Gateway Timeout.",

REQUEST 2020-03-23 08:19:36.6302113 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU4NDk0NTMxNDI1ODg5NQ&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer \

RESPONSE 2020-03-23 08:19:38.1458667 Duration: 1515,6554ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },

  "TraceId": "7a726ec422f806ca",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

REQUEST 2020-03-24 14:57:46.1419880 
curl -X GET \
  'https://api.allegro.pl/sale/offers?publication.status=INACTIVE%2CACTIVATING%2CACTIVE%2CENDED&limit=200&offset=0' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

RESPONSE 2020-03-24 14:58:06.1741031 Duration: 20032,1151ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Timeout to the backend service.",
        "Path": null,
        "UserMessage": "Internal server error. Please try again in a few minutes."
      }
    ],

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za komplet danych. Przekazałem je odpowiedniego zespołu, który zajmie się analizą problemu.
