### ISSUE TITLE
Długie czasy odpowiedzi serwera

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#3003]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Czas odpowiedzi tego requesta to 20s. Czy to spowodowane jest jakimiś limitami? Ten sam request przy kolejnym wywołaniu potrafi się  wykonać w 500ms więc to chyba nie jest spowodowane ograniczeniami.

GET /sale/offers/9098144730
`
    0 => "HTTP/1.0 200 OK"
    1 => "expires: 0"
    2 => "cache-control: no-cache, no-store, max-age=0, must-revalidate"
    3 => "x-xss-protection: 1; mode=block"
    4 => "server: envoy"
    5 => "pragma: no-cache"
    6 => "x-frame-options: DENY"
    7 => "trace-id: 348e20fcd58d277"
    8 => "date: Wed, 25 Mar 2020 07:09:00 GMT"
    9 => "x-content-type-options: nosniff"
    10 => "content-type: application/vnd.allegro.public.v1+json;charset=UTF-8"
    11 => "x-envoy-upstream-service-time: 47"
`

**Comment by ddaapp** [comment]
Mamy to samo... jakiś update?

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu, który zajmie się analizą problemu. @ddaapp Podaj proszę przykładowe trace-id.
