### ISSUE TITLE
Problem z autoryzacją Wapro Aukcje

### ISSUE THREAD

**Issue by showexon** [allegro/allegro-api#3004]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam problem z autoryzacją aplikacji Wapro Aukcje 8.5.2, podczas próby autoryzacji pojawia się komunikat 
"FullExceptionMessage:Connection timeout (error code is 96270)

**Comment by KrzysztofStachyra** [comment]
Problem jest z API wywala co chwilę timeouty co widać po zgłoszeniach już z wczoraj. Dodatkowo właśnie zaobserwowałem u jednego klienta problem że próba nadania paczki z API inpost która odpytuje APi allegro o adres maskowany też wywala timoeut.

Allegro coś wie na ten temat bo od wczoraj cisza w zgłoszeniach o błędach w komunikacji z API...

**Comment by PrzemyslawLukanowski** [comment]
Podobnie jak w przypadku innych zgłoszeń, które dotyczą timeoutów - przekazałem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@showexon Czy w Twoim przypadku sytuacja się poprawiła?

**Comment by showexon** [comment]
@PrzemyslawLukanowski tak wszystko już działa, dziękuję za pomoc.
