### ISSUE TITLE
Problem z połączeniem - Timeout

### ISSUE THREAD

**Issue by mxdzi** [allegro/allegro-api#3005]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od wczoraj od 15:45 mam problem z połączeniem do api. Wszystkie zapytania kończą się timeoutem. Nawet próba wygenerowania nowego tokena Oauth po zalogowaniu przekierowanie kończy się timeoutem.

Podobny problem pojawił się 2 dni temu na sandbox. Na paru kontach większość zapytań kończy się timeoutem lub trzeba długo czekać na odpowiedz.

**Comment by PrzemyslawLukanowski** [comment]
Podobnie jak w przypadku innych zgłoszeń, które dotyczą timeoutów - przekazałem problem do odpowiedniego zespołu.

**Comment by troncomputers** [comment]
Czy jest możliwe, aby w ogóle nie było połączenia? Nasza usługa łącząca się do API zwraca `BadRequest`, a oprogramowanie Postman
![allegro_api](https://user-images.githubusercontent.com/29543667/77630437-50f9cd00-6f4b-11ea-8f95-c82c5eed71a0.png)

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się powtórzyć Twój przypadek - przekazałem ten problem do zgłoszenia.

**Comment by mxdzi** [comment]
@PrzemyslawLukanowski czy już wiadomo coś na temat tych timeoutów?

Czy jest możliwe że po stronie Allegro został zbanowany adres IP mojego serwera produkcyjnego?
Nie mogę się połączyć na żadne konto (live i sandbox) z IP 94.152.166.64.
Z innego IP połączenie działa OK.

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedni zespół pracuje już nad rozwiązaniem problemu. Jak tylko uda się go wyeliminować, poinformuję w tym wątku.

Czy możesz określić, co dokładnie otrzymujesz w odpowiedzi? Najlepiej w formie przykładowego żądania i odpowiedzi. Możesz je nam przekazać za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), dopisz wtedy w zgłoszeniu Github #3005.

**Comment by PrzemyslawLukanowski** [comment]
@mxdzi Problem, który opisałeś w zgłoszeniu, nie powinien już występować.

**Comment by mxdzi** [comment]
Odpisałem przez formularz kontaktowy. Niestety z IP 94.152.166.64 dalej nie mogę się połączyć.

**Comment by PrzemyslawLukanowski** [comment]
@mxdzi Weryfikujemy kwestię blokady.

**Comment by troncomputers** [comment]
@PrzemyslawLukanowski Coś wiadomo w mojej sprawie?

**Comment by PrzemyslawLukanowski** [comment]
@troncomputers Czy możesz jeszcze doprecyzować, czy reprezentujesz to samo oprgramowanie, co mxdzi? Chcemy ustalić, czy Twój problem jest powiązany z problemem z IP, o którym wspomina mxdzi.

**Comment by troncomputers** [comment]
Nie to nie jest to samo oprogramowanie. Raczej nie jest powiązany z IP. Usługa, która zwraca `BadRequest` jest pod innym IP. Zrzut ekrany z Postmana jest pod innym IP. Podpiąłem się pod ten wątek, ponieważ uważałem, że mój problem jest ten sam. Zresztą widziałem już dwa wpisy o timeoutach, więc jaki był sens robienia trzeciego.

**Comment by mxdzi** [comment]
@PrzemyslawLukanowski dzisiaj około godziny 10 połączenie do allegro zaczęło działać. Czy ta blokada wynikała z jakiegoś konkretnego błędu po mojej stronie (np. dużo błędnych zapytań, problemy z logowaniem)?

**Comment by troncomputers** [comment]
Z mojej strony nieaktualne. Jeśli chodzi o Postmana to mi nie zależy. Zależy mi na usłudze u klienta. Założyłem nowy wątek z czym mam "problem". #3015

**Comment by PrzemyslawLukanowski** [comment]
@mxdzi Nałożyliśmy blokadę na adres IP ze względu na to, że - pomimo otrzymania captchy - wysyłałeś do nas masowe requesty na /login/token/oauth na sandboxie (~ 300 requestów na sekundę). Aby uniknąć sytuacji tego typu, powinieneś wprowadzić w swoich narzędziach dodatkowy "sleep", jeśli wystąpią problemy, zamiast ponawiać masowo requesty. Zweryfikuj proszę działanie mechanizmu, ponieważ w przypadku kolejnej sytuacji tego typu, IP ponownie zostanie przez nas zbanowane.

**Comment by mxdzi** [comment]
OK, dziękuję za informację.
