### ISSUE TITLE
Problem occur when we authorize our app usibg client id and secret key it gives error

### ISSUE THREAD

**Issue by 07adityasingh** [allegro/allegro-api#3006]
[Występuje](url
![Allegro Issue](https://user-images.githubusercontent.com/49195898/77539170-f0c14780-6ec6-11ea-845a-cb478848d539.png)
) problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Make sure the redirect_uri parameter is the same address which you provide via https://apps.developer.allegro.pl/ for this client id. Also, you have extra mark "+" in client_id parameter.
