### ISSUE TITLE
Dane kupującego z formularza pozakupowego

### ISSUE THREAD

**Issue by omecon-allegro** [allegro/allegro-api#301]
Dotychczas wypełniając formularz pozakupowy(wskazując inny niż domyślny adres wysyłki) adres ten był widoczny w danych posprzedażowych na koncie sprzedającego. Sprzedane/Opcje/Dane kupującego tak samo dane wysyłkowe były widoczne w allegro webapi. Być może zmiana dotyczy tylko odbioru osobistego ale wcześniej nawet dla odbioru osobistego były wysyłane dane z formularza pozakupowego.

**Comment by LukaszKorek** [comment]
Doprecyzuj proszę jaką metodę masz na myśli.

**Comment by omecon-allegro** [comment]
w kolejnosci uzywam
doGetMySoldItems
doGetPostBuyData
doGetTransactionsIDs
doGetPostBuyFormsDataForSellers
ale tez nie widac tego na koncie
http://allegro.pl/wypalone-zapalki-i7400525233.html
dla tego przedmiotu wypelnilem formularz pozakupowy:
Dane odbiorcy przesyłki
Salva Mantequilla
San Jose 25
11-380 Tarifa
niestety w danych sprzedawcy na koncie sprzedawcy sa inne dane.

**Comment by LukaszKorek** [comment]
W Moim Allegro dane do wysłki z wypełnionego formularza opcji dostawy i zapłaty znajdziesz w zakładce [Zamówienia](https://allegro.pl/seller-orders/#!/) Podobnie w API powinieneś pobierać dane z fomularza opcji dostawy i zapłaty. Pobierzesz je np. za pomocą metody doGetPostBuyFormsDataForSellers

**Comment by omecon-allegro** [comment]
nie widze tych danych w tej zakladce Zamówienia. dla danej aukcji podawane sa w zakladce Sprzedane/Opcje/Dane kupującego inne dane niz te z formularza pozakupowego. wczesniej dzialalo to inaczej. W webapi staram sie to zweryfikowac
