### ISSUE TITLE
Problem z różnymi wartościami w API i w mailu do klienta

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3011]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Zgłosił się do nas klient z informacją, że integracja pobiera zupełnie inne dane adresowe w stosunku do tego które wypełnił na Allegro. Pobraliśmy informacje o danym zamówieniu przez API i okazało się że w polach invoice oraz delivery nie dostaliśmy wpisanego przez klienta adresu, zaś status zamówienia wiecznie wskazuje na wartość FILLED_IN

Numer zgłoszenia przez formularz na: https://allegro.pl/pomoc/kontakt
"08824466" ref:_00D24aE05._5001o4QKSaa:ref

Czy takie zachowanie jest pożądane ?

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem dane - płatność dla zamówienia 4b825512-6abc-11ea-9876-cb8e10f6e1ce została anulowana, dlatego jest cały czas w statusie FILLED_IN. Dane o fakturze oraz adres dostawy zwracamy dopiero dla zamówień w statusie READY_FOR_PROCCESSING.

**Comment by pkrzemo** [comment]
A czy jest jakaś szansa że dane te powrócą do API w statusie FILLED_IN?
Bo to bezsens przepisywać je z maila (bo tam te dane są) no ale wy wiecie lepiej od nas, jak zawsze, czego nam potrzeba...
:-(
A może mogło to by być tak że była by funkcjonalność "potwierdzenia zapłaty innym kanałem", którą by używał sprzedawca w celu poznania danych do wysyłki w tym statusie? No bo klient czasem płaci inaczej ...

**Comment by kormichu** [comment]
Albo może dorzucićcie do zamówienia kolejny status CANCELLED który już zawiera wszystkie potrzebne dane

**Comment by PrzemyslawLukanowski** [comment]
Taka sugestia pojawiła się już wcześniej, dopisuję Wasze głosy do zgłoszenia. Na tę chwilę nie mamy w planach udostępniać tych danych dla innych statusów niż RFP, jednak jeśli się to zmieni, będziemy o tym informować.
