### ISSUE TITLE
Problem z rejstracja w środowisku testowym

### ISSUE THREAD

**Issue by Mbif-dev** [allegro/allegro-api#3013]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam
mam problem z zarejestrowaniem konta w środowisku testowym założyłem już dwa konta na dwóch różnych pocztach i nie dostałem e maila aktywacyjnego.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdź proszę, czy mail nie trafił do folderu Spam. Jeśli nie, podaj adresy mailowe, które podałeś przy rejestracji. Sprawdzimy to po naszej stronie.

**Comment by Mbif-dev** [comment]
sandboxallegro[at]mbif[dot]pl

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi - maile zostały prawidłowo wysłane dzisiaj o 08:35:24 i 10:20:38, prawdopodobnie zostały w jakiś sposób zablokowane po Twojej stronie. Napisz proszę do nas przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), powołaj się na zgłoszenie GitHub #3013. W odpowiedzi przekażę link aktywacyjny.

**Comment by Mbif-dev** [comment]
W między czasie doszedł na drugie konto, ale pojawił się inny problem nie mogę wystawić aukcji po kliknięciu w odnośnik wystaw przedmiot jestem przekierowany do strony https://staging-lokalnie.allegrogroup.com/oferty/wystaw i dostaję komunikat że podana strona nie istnieje

**Comment by PrzemyslawLukanowski** [comment]
Skorzystaj na tę chwilę z alternatywnego linka - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.
