### ISSUE TITLE
Wystawianie oferty poprzez Sandbox nie działa.

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#3014]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Wystawianie oferty poprzez Sandbox nie działa.
Problem występuje przez API i przeglądarkę (nie można wystawić nowej i podobnej.)

W obu przypadkach otrzymuję podobny komunikat:
"Nie udało się pobrać oferty. Podany adres obrazka jest nieprawidłowy."

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to - udało mi się prawidłowo wystawić nową, jak i podobną ofertę. Jeżeli w Twoim przypadku problem nadal występuje, prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) z dopiskiem GitHub #3014.

**Comment by aktywnitu** [comment]
Przycisk Dodaj nową przekierowywuje mnie na niedostępną stronę:
https://staging-lokalnie.allegrogroup.com/oferty/wystaw

**Comment by aktywnitu** [comment]
Wystawienie ponownie po usunięciu obrazka zadziałało.

**Comment by PrzemyslawLukanowski** [comment]
> Przycisk Dodaj nową przekierowywuje mnie na niedostępną stronę:
> https://staging-lokalnie.allegrogroup.com/oferty/wystaw

Na tę chwilę możesz skorzystać z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by alekskuc** [comment]
@PrzemyslawLukanowski kiedy [wystaw przedmiot](https://allegro.pl.allegrosandbox.pl/offer/) na sandboxie będzie prawidłowo kierował do wystawiania nowej oferty?

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Poinformuję w tym wątku, kiedy problem zostanie rozwiązany. Na tę chwilę nie mogę wskazać konkretnego terminu.
