### ISSUE TITLE
token, refresh_token - ważność, odświeżanie gdy refresh_token jest niepoprawny

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#3015]
Jak to w końcu jest z tym refresh_token? Ile on jest ważny? Aplikacja pracuje miesiąc. Wszystkie odświeżania tokenów (po 12h) przechodzą poprawnie, a naglę rzuca błędem `Invalid refresh token`. Wszystko trzeba powiązać i generować na nowo? Przecież klient mnie zabije za taki system...

**Comment by AssAssIn1909** [comment]
Jeżeli dostałeś taki komunikat to raczej bez ponownego powiązania aplikacji sie nie obejdzie. Ewentualnie możesz jeszcze raz spróbować odświeżyć token.
A refresh_token ważny 3 miesiące. 
Może token się źle zapisał do bazy. U mnie co prawda na sandboxie i kontach testowych od jakiegoś czasu refresh_tokeny wpadały dłuższe niż miałem pole w bazie i to samo się działo. Na prod na szczęście są krótsze ale i tak rozszerzyłem pola.

**Comment by troncomputers** [comment]
Czy to tylko dla mnie jest chore? Obsługuje oprogramowaniem klientowi 4 konta allegro (usługa Windows), setki zamówień. Potrzebuje z zamówienia ściągnąć ilość paczek i z jakiego konta jest zamówienie i wrzucić to do systemu ERP. Chcesz mi powiedzieć, że co 3 miesiące będę musiał powiązać wszystkie 4 konta, aby to działało? 🤔🤨😑

**Comment by AssAssIn1909** [comment]
Nie. Za każdym odświeżeniem access_tokenu dostajesz nowy refresh_token, który jest ważne przez następne 3 miesiące

**Comment by troncomputers** [comment]
Ok, teraz rozumiem. Mimo wszystko aplikacja miesiąc pracuje poprawnie i przez cały miesiąc odświeża token w identyczny sposób. Nikt nic nie rusza, nikt niczego nie wyłącza, nagle refresh_token jest niepoprawny. Mam nadzieje, że to problem po mojej stronie bo te powiązania są chore... Jakby nie można było tego rozwiązać loginem i hasłem.

**Comment by PrzemyslawLukanowski** [comment]
@troncomputers Możesz wysłać refresh_token, z którym masz problem, przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - dopisz w zgłoszeniu GitHub #3015. Przyjrzę się, co wydarzyło się w tym przypadku.

**Comment by troncomputers** [comment]
Już sobie to wszystko na nowo powiązałem. Jak się znowu pojawi taka sytuacja to napiszę zgłoszenie.

**Comment by troncomputers** [comment]
Wysłałem rano refresh_token do weryfikacji. Czy długo to jeszcze potrwa? Czy mam sobie mimo wszystko na nowo powiązać i wygenerować tokeny?

**Comment by PrzemyslawLukanowski** [comment]
@troncomputers  Przeanalizowałem logi:

2020-03-28 08:51:13.206 - wygenerowałeś parę access i refresh token,
2020-03-28 20:51:13.169 - wykorzystałeś refersh token, w odpowiedzi otrzymałeś nową parę, poprzednia para w tym momencie traci ważność.

Następnie odnotowaliśmy bardzo dużę liczbę prób odnowienia tokena za pomocą nieaktualnego refresh tokena.

**Comment by troncomputers** [comment]
No zgadza się. Usługa robi to wszystko automatycznie. Jeśli dostaję zwrotkę z waszego API - `Unauthorized` to znaczy, że mam odświeżyć token i zapisuje nową parę do pliku.

Czyli ten refresh_token (nieaktualny), który wysłałem w zgłoszeniu był refresh_tokenem z 8:51?

**Comment by PrzemyslawLukanowski** [comment]
Tak, to był refresh z 08:51, aktualny do 20:51.

**Comment by troncomputers** [comment]
Dzięki za pomoc. Drążę temat dalej u siebie ;-)

**Comment by troncomputers** [comment]
Znowu to samo... To już jest dziwne. Przecież przez noc nikt nic nie robił... Poszło zgłoszenie

**Comment by pkrzemo** [comment]
Sorki że się wtrącam ale wygląda na to że to tylko problem z TWOJĄ aplikacją. Odpalasz wiele wątków bez żadnej synchronizacji w momencie pobierania nowego tokena. Te wątki rywalizują ze sobą o zasoby. Kilka zaczyna pobierać jednocześnie token ale jednemu się to tylko udaje (no bo token jednorazowy), ale czasem, z powodu zjawiska tzw. wyścigu, temu wątkowi nie udaje się zapisać tokena bo inny wątek mu to w tym czasie blokuje. Efekt powstaje więc taki że ten nowy token może się nie zapisać i jest to całkiem losowe.
;-)

**Comment by troncomputers** [comment]
Ja sobie zdaję z tego sprawę, że to leży po mojej stronie, ale za nic nie potrafię wydrążyć dlaczego. Gdyby był problem z wątkami i zapisem pliku to nigdy by nie działało. Raz działa 2 tygodnie, a raz działa tylko przez pierwsze 12h jak token jest aktywny. 
Od wczoraj poprawiłem zapisywanie tokenów i dodatkowo robię kopie poprzedniej konfiguracji, aby zachować historię. Tokeny się nie powtarzają, czyli zapisał nowe, czy jakie? To co mówisz może mieć sens. Od nowego roku zacząłem używać Quartz i dzieją się czasem niezłe cyrki z tym schedulerem... No i `Job.Execute()` jest asynchroniczne.

**Comment by Onixarts** [comment]
Już kiedyś poruszałem ten temat. Wystarczy, że response gdzieś po drodze zaginie (internet, lagi, zapis do bazy) i już masz zblokowany refresh token. Synchronizacja wątków to relatywnie proste zadanie, gorzej jeśli kilkanaście stanowisk robi własną synchronizację i zechce odświeżyć token, bo synchronizacja między nimi już nie jest taka trywialna.

**Comment by troncomputers** [comment]
Ale to jest jeden wątek. Nie robię nic więcej, ponieważ blokuje mnie system ERP. Cała aplikacja wykonuje tylko jeden Job podzielony na "sekcje", z czego jedną z tych sekcji jest API Allegro.

**Comment by PrzemyslawLukanowski** [comment]
@troncomputers Sprawdziłem logi, które do nas wysłałeś. Cyfra na początku odpowiada kolejnym tokenom:

1:
2020-03-28 08:51:13 - wygenerowano parę access i refresh token,
2020-03-28 20:51:13 - wygenerowano nową parę za pomocą poprzedniego tokena. W tej samej minucie ma miejsce bardzo duża liczba prób odświeżenia tokena za pomocą nieaktualnego refresha.

2: 
Access token wygenerowany 2020-03-30 20:03:48, który 2020-03-31 08:31:35.336 został zastąpiony przez użycie refresh tokena. Podobnie jak wyżej - W tej samej minucie ma miejsce bardzo duża liczba prób odświeżenia tokena za pomocą nieaktualnego refresha.

3:
Access token wygenerowany 2020-03-30 20:04:03.914, który 2020-03-31 08:31:35.368 został zastąpiony nowym przez użycie refresh tokena. Podobnie jak wyżej - W tej samej minucie ma miejsce bardzo duża liczba prób odświeżenia tokena za pomocą nieaktualnego refresha.

Scenariusz dla pozostałych jest identyczny, róźni je tylko czas, w którym wykonane zostały operacje.


------
Uproszczone zarządzanie ofertami - [wskaż najbardziej pożądane funkcjonalności](https://allegro.optimalworkshop.com/optimalsort/o274266h).

**Comment by troncomputers** [comment]
Ok, czyli nie dochodzi do momentu zapisu nowych tokenów. Już nie będę was dręczył. Dzięki za poświęcony czas
