### ISSUE TITLE
Kupujacy zgłosił zwrot towaru

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#3016]
Witam
1. Czy planują Państwo udostępnienie zasobu do ściągania odstąpień? Zwrotów w branży fashion jest coraz więcej, wprowadzanie ręczne mija się z celem.
2. Czy przez Rest Api można zlecić zwrot środków Klientowi ?
pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
1. Mamy to na liście naszych sugestii. Jeśli zdecydujemy się wprowadzić ten zasób, na pewno będziemy o tym informować.
2. Tak, jest to możliwe za pomocą [POST /payment/refunds](https://developer.allegro.pl/documentation/#operation/initiateRefund). Więcej informacji przeczyta Pan w [naszym poradniku](https://developer.allegro.pl/orders/#10).

**Comment by shivson1337** [comment]
Od siebie dodam prośbę o dosyć pilne rozważenie wprowadzenia takiego zasobu. Obecnie obsługa zwrotów w przypadku sprzedaży masowej jest na tyle uciążliwa, że gdyby ktoś chciał ogarnąć to w 100% to powinien zatrudnić osobę tylko od tego.

W przypadku gdy ten sam towar zwraca kilku klientów, nie jesteśmy w stanie stwierdzić, który z nich rzeczywiście odesłał zakup i zwrócić pieniędzy odpowiedniej osobie.

Niestety na nic zdają się prośby o umieszczanie na/w przesyłce numeru zwrotu lub nicku z allegro. Prowadzi to do niepotrzebnie zakładanych dyskusji, a dokłada to pracy zarówno nam, sprzedającym, jak i Wam.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za dodatkowe spostrzeżenia, załączam je do wcześniejszych sugestii.
