### ISSUE TITLE
Różnice czasu dodanie numeru przesyłki

### ISSUE THREAD

**Issue by tzji7** [allegro/allegro-api#3017]
W sklepie którym się zajmuję dodajemy numer paczki zaraz jak tylko go otrzymamy od DPD/Inpost/Poczty Polskiej ale potem w statystykach Allegro okazuje się że są zapisane czasy różne o kilka godzin a czasami nawet na drugi dzień.
Poproszę o informację skąd takie różnice?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe numery paczek i doprecyzować, w któym dokładnie miejscu widzisz rozbieżność?

**Comment by tzji7** [comment]
Oto dwa przykłady:

Numer paczki: 693192839044340131862059
Data przekazania do Allegro przez nas numeru paczki:  2020-03-02 08:42:43
Data w statystykach: 2020-03-03 01:00:00.0

Numer paczki: 693192439066400138802046
Data przekazania do Allegro przez nas numeru paczki:  2020-03-06 08:33:27
Data w statystykach: 2020-03-06 19:39:21.066

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za dane, prosiłbym jednak jeszcze raz, abyś doprecyzował, jakie statystyki masz na myśli. Jeśli nie są one powiązane z żadnym zasobem API, prześlij proszę swoje zgłoszenie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by tzji7** [comment]
Wysyłaliśmy numer paczki przy użyciu api [/order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST)
Informację do Allegro dla paczki 693192839044340131862059 wysłaliśmy o godzinie 2020-03-02 08:42:43
wg logu z Waszego sytemu otrzymanego na infolinii dla tego numeru paczki został przekazany o 2020-03-03 01:00:00.0

i analogicznie wszystkie inne.

Moje pytanie jest skąd taka różnica czasów między tym co my zrobiliśmy a tym co odnotował Wasz system?

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze weryfikuję Twoje zgłoszenie, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Dla numeru listu 693192439066400138802046 i zamówienia 62dd7ee4-5f10-11ea-a19b-7b8f9cd42454 nie mamy informacji o tym, ze numer został dodany przez REST API. Numer został przekazany do nas tylko raz, przez narzędzie nadawcze przewoźnika w 06-03-2020 o 08:32 i była to jedyna próba dodania tego numeru jakimkolwiek kanałem.
Numer listu 693192839044340131862059 przypisany do zamówienia d2783392-5b22-11ea-be6e-cfb13a12089b został dodany 02-03-2020 o 08:42, również 
przez narzędzie nadawcze przewoźnika. 
Czy możesz doprecyzować, co oznacza, że "wg logu z naszego systemu otrzymanego na infolinii numer paczki został dodany o innej godzinie". Jedyne miejsce w REST API, gdzie da się sprawdzić datę dodania, czyli odpowiedź dla GET order/checkout-forms/{id}/shipments, powinno zwracać poprawne daty.
