### ISSUE TITLE
Błąd parsowania Json'a przy odświeżaniu tokena, nowe pole allegro_api?

### ISSUE THREAD

**Issue by jsienkiewicz** [allegro/allegro-api#3018]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przestał nam się odświeżać token z błędem mówiącym o niemożności zparsowania Json'a - nieznane pole "allegro_api". Na liście zmian nie widzę żadnych zmian w mechanizmach uwierzytelniania. Od kiedy pojawiło się nowe pole?
Czy można prosić o komunikowanie zmian w tak ważnym miejscu?

**Comment by PrzemyslawLukanowski** [comment]
Nowe pole dodaliśmy 25.03.2020, zaktualizowaliśmy w związku z tym nasz artykuł o autoryzacji. Nie informowaliśmy o zmianie wcześniej, ponieważ nie jest ona niekompatybilna wstecz - integracja nie powinna "na sztywno" przyjmować zwracanych przez nas pól, w przyszłości w odpowiedzi mogą pojawiać się dodatkowe pola.

**Comment by jsienkiewicz** [comment]
Poprawimy u siebie, oczywiście.
Jak widać w naszej technologii okazało się to być niekompatybilne wstecznie, bo co innego dodawanie nowych metod i ich parametrów, a co innego lista pól podstawowego dla bezpieczeństwa typu danych. Wzmianka o tak istotnych zmianach byłaby jednak wskazana w "Aktualnościach"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie. Weźmiemy to pod uwagę w przypadku przyszłych komunikatów.
