### ISSUE TITLE
prosba o aktywacje kont na sandbox

### ISSUE THREAD

**Issue by mrGibi** [allegro/allegro-api#3019]
Wysylalem prosbe przez formularz kontaktowy, ale niestety bez odzewu, wiec sprobuje tu.
Uprzejmie prosze o aktywacje kont b.brzezinski at luclick dot com (firmowe) i bartek at puszek dot pl (prywatne)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem konta.
