### ISSUE TITLE
Autoryzacja bearer-token-for-user

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3020]
Dzień dobry,
czy wszystkie metody które wymagają bearer-token-for-user, zwracają **wyłącznie** dane zalogowanego użytkownika?
Czy istnieją również metody które wymagają tej autoryzacji, a następnie pobierają dane również innych użytkowników, np. dotyczących zdarzeń na dowolnej aukcji w serwisie?

Krótko mówiąc: czy są metody pobierające publiczne dane wymagające autoryzacji bearer-token-for-user?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takich metod. Zasoby oznaczone jako bearer-token-for-user zwracają tylko dane zautoryzowanego użytkownika.
