### ISSUE TITLE
Jak zmigrować doGetRefundsDeals do nowego REST API

### ISSUE THREAD

**Issue by siema1980** [allegro/allegro-api#3021]

**Comment by MaciejFrackowiak** [comment]
[Zasoby](https://developer.allegro.pl/documentation/#tag/Commission-refunds) wspierające rabaty transakcyjne w REST API zwracają wnioski utworzone od dnia 24.03.2020. Dane z metody WebAPI (dealId) możesz zmapować na "lineItemId" korzystając z zasobu [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping).

**Comment by siema1980** [comment]
Ok. Tylko, że doGetRefundsDeals zwraca mi całe mnóstwo innych informacji których nigdzie w api restowym nie mogę nie mogę znaleźć szukałem też w GET order/refund-claims ale to co tam znajduję dla nie odpowiada temu co zwraca mi doGetRefundsDeals.

**Comment by MaciejFrackowiak** [comment]
Jakie informacje masz na myśli? - zmapowanie dealId z lineItemId pozwala połączyć stary i nowy dziennik zdarzeń, a zatem jednoznacznie zidentyfikujesz transakcje, dla których wnioski zostały złożone.
