### ISSUE TITLE
Problem z wysyłaniem zdjęć na Sandbox

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3022]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, nie moge dzisiaj wyslać prawie żadnego zdjęcia na sandbox, a przez to nie moge wystawić żadnej oferty.
Dostaje komunikat "Internal server error. Please try again in a few minutes". Po odczekaniu chwili zdarza się że faktycznie przechodzi ale tylko raz, Potem znowu trzeba czekać lub liczyć na szczęście.

TraceId: f6825bec2ea24ba8, c61aa36c67f045c0

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, mieliśmy drobne problemy z przesyłaniem zdjęć na Sandbox - już poprawiliśmy działanie mechanizmu, przepraszam za utrudnienia.

**Comment by lukaszzborek** [comment]
Dzięki
