### ISSUE TITLE
Funkcja www Uzupełnij parametry na sandboxie

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3023]
Dzień dobry, mam prośbę o udostępnienie opisu ze screenami działania funkcji dostępnej z serwisu www "Uzupełnij parametry" https://allegro.pl/moje-allegro/sprzedaz/uzupelnij-parametry lub informację jak można dodać oferty testowe na sandboxie z nieuzupełnionymi wymaganymi parametrami w celach testowych potrzebnych do realizacji podobnej funkcji przez rest api.

**Comment by MaciejFrackowiak** [comment]
Zamieszczam poglądowy screen z produkcyjnej wersji Uzupełnij parametry: 
![obraz](https://user-images.githubusercontent.com/53566763/77907252-9d197a00-7289-11ea-831d-713e2ee384a0.png)
Jeżeli jakiś parametr staje się obowiązkowy w Allegro, wówczas wyświetlamy komunikat jak na załączonym screenie. Klikając odnośnik "uzupełnij parametr xxxx" otwiera się warstwa z listą ofert, która wymaga działania (10 ofert na stronie, stronnicowanie) - możesz ręcznie dla każdej uzupełnić wartość lub masowo przypisać taką samą.
Niestety, nie mamy możliwości skonfigurowania tak Sandbox by umożliwić wystawienie ofert bez obowiązkowych parametrów, aby później uzupełnić je w narzędziu do masowej zmiany ich wartości.

**Comment by alekskuc** [comment]
Dziękuję, za przesłane informacje. Co jeszcze można znaleźć pod widocznym na screenie linkiem "Jak uzupełnić parametry?" czy jest on ogólnodostępny?

**Comment by MaciejFrackowiak** [comment]
Znajduje się tam krótki onboarding:
![obraz](https://user-images.githubusercontent.com/53566763/77910754-f71d3e00-728f-11ea-9eef-131e22a97482.png)

**Comment by alekskuc** [comment]
Ok, to jeszcze mam ostatnie pytanie, bo nie jestem pewny. Metodą rest api z parametrami /offers/listing?seller.id=##&category.id=111852&parameter.11325=null ani żadną inną nie jestem w stanie wprost wybrać ofert z parametrami do uzupełnienia jak w powyższej funkcji?

**Comment by MaciejFrackowiak** [comment]
Nie, funkcjonalność z WWW nie ma jeszcze swojego odzwierciedlenia w REST API - mamy to jednak na uwadze i znajduje się ona na liście sugestii dot. rozwoju REST API.

**Comment by alekskuc** [comment]
Ok, dziękuje za informacje.
