### ISSUE TITLE
[RestAPI] Lepsze komunikaty restAPI

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3025]
Cześć, 

Warto rozszerzyć informacje o błędach zwracanych przez API
Przykładowy scenariusz
1. Mam konto Allegro
2. Mam dużo aukcji i aktualizuję stany na bieżąco 
3. Administracja Allegro zawiesza konto
4. Nadal automaty aktualizują stany bo restAPI zwraca status code = 200, mamy u siebie w logach 14000 błędów :)

Proponuję rozszerzyć statuscode o różne przypadki, parsowanie opisu nie jest dobrym rozwiązaniem, a gdybyśmy dostawali nowe status code moglibyśmy obsłużyć tego typu przypadki

{"RaportZlecenia":{"Nr":"46fcb268-78c7-497b-bbc0-b9a01ca782d5","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-03-27T15:05:51.044Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"XXXXXXXXX"},"ScheduledAt":"2020-03-27T15:05:50.82Z","Status":"FAIL","Errors":[{"Code":"ConstraintViolationException.ValidSeller","Details":null,"Message":"Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).","Path":"seller","UserMessage":"Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane)."}]}]},"Validation":null,"Exception":null,"TraceId":"7f18c5d8b502c8f8","Error":false,"StatusCode":200,"Message":null}}}

{"RaportZlecenia":{"Nr":"a1eb2d4d-c01a-4a04-9923-42e075d7c267","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-03-30T13:09:46.595Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"XXXXXXXXX"},"ScheduledAt":"2020-03-30T13:09:46.236Z","Status":"FAIL","Errors":[{"Code":"ConstraintViolationException.ValidOfferName","Details":null,"Message":"Zgodnie z decyzją Prezesa Rady Ministrów (www.premier.gov.pl/wydarzenia/aktualnosci/premier-olx-i-allegro-nie-beda-mogly-sprzedawac-artykulow-zwiazanych-z.html), wydaną na podstawie ustawy w sprawie szczególnych rozwiązań związanych z koronawirusem, zabroniona jest sprzedaż produktu, którego dotyczy publikowana oferta.","Path":"product.embedded.name","UserMessage":"Zgodnie z decyzją Prezesa Rady Ministrów (www.premier.gov.pl/wydarzenia/aktualnosci/premier-olx-i-allegro-nie-beda-mogly-sprzedawac-artykulow-zwiazanych-z.html), wydaną na podstawie ustawy w sprawie szczególnych rozwiązań związanych z koronawirusem, zabroniona jest sprzedaż produktu, którego dotyczy publikowana oferta."}]}]},"Validation":null,"Exception":null,"TraceId":"9cda66023ad1b687","Error":false,"StatusCode":200,"Message":null}}}

**Comment by pkrzemo** [comment]
"StatusCode":200 dotyczy komendy którą pobrałeś informacje o zadaniu asynchronicznym (którym była grupowa modyfikacja). Polecenie się powiodło i zwróciło poprawnie dane - stąd status OK ("StatusCode":200).
Natomiast w zwracanych danych jest przecież zapis błędu zakończonej modyfikacji grupowej. Patrz: "Status":"FAIL"

Oczywiście fajnie by było gdyby na poziomie StatusCode była już informacja że modyfikacja grupowa się nie powiodła, ale niestety wartości StatusCode są standardem HTTP i nie powinno się ich znaczenia dowolnie modyfikować. Przejrzałem kody odpowiedzi HTTP i znalazłem status 205 który może można by do tego na siłę użyć... a może jest jakiś lepszy sposób lub bardziej odpowiedni kod? 

Dla mnie tak jak jest może być (Status":"FAIL" dla modyfikacji które się nie powiodły), natomiast oczywiście jeśli Allegro zrobi nam lepiej to tylko będzie się można z tego cieszyć.. ;-)

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Dziękuję za przedstawienie Twojego zdania w kwestii obsługi komunikatów błędów. Przekazuję je do działu odpowiedzialnego za rozwój REST API Allegro.

@pkrzemo Tobie również dziękuję za cenne spostrzeżenia.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak dzięki 
@pkrzemo i tak nie, bo status FAIL nadal nie mówi nic o przyczynie, a przyczyna tekstowa nie jest zbyt dobra, w pierwszym przypadku byśmy automatycznie wyłaczyli konto i powiadomili Klienta o takim fakcie, tak to nie wiemy z czego ten FAIL jest. Przydałoby się zatem coś więcej a nie tylko tekst, naturalnym byłoby HttpCode, oczywiście inne też mile widziane :)

**Comment by pkrzemo** [comment]
@SebastianOzdoba Nie bardzo rozumiem.. napisałeś:
>"4.Nadal automaty aktualizują stany bo restAPI zwraca status code = 200, mamy u siebie w logach 14000 błędów :)"

Żeby nie aktualizowały wystarczy status code != 200 lub... status FAIL ;-)
Nie bardzo widzę w czym automatom miało by pomóc wprowadzenie  nieskończonej ilości statusów na każdą możliwą przyczynę teraźniejszą i przyszłą. Dla automatu powinno wystarczyć czy się powiodło czy nie i w razie niepowodzenia przedstawienie operatorowi treści komunikatu błędu.
