### ISSUE TITLE
Problemy z API - timeout

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#3026]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Request do: https://api.allegro.pl/sale/offers?limit=1000&offset=0&publication.status=ACTIVE,ACTIVATING&sellingMode.format=BUY_NOW (aukcji wystawionych 0, więc danych nie ma), otrzymuję zwrotkę:
```
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Timeout to the backend service.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}
```
lub: https://imgur.com/5SkG0TK

Dodatkowo - bardzo często pojawia się:
`{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}
`
O co chodzi? Macie jakieś problemy z API?

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - rzeczywiście, zauważyliśmy dość losowe pojawianie się błędów 504. Sprawę przekierowałem już do właściwego zespołu.
Natomist co do komunikatu z tokenem - tu nie odnotowaliśmy żadnych problemów.

**Comment by mindc** [comment]
@xemix @MaciejFrackowiak 
Jeśli chodzi o autoryzację, zauważyłem to samo, tak jakby zostały wprowadzone/zmniejszone limity na dostęp do OAuth

**Comment by MaciejFrackowiak** [comment]
@mindc Nie wprowadzaliśmy tu ostatnio żadnych zmian w kwestii limitów.

**Comment by marmizg** [comment]
Poproszę o aktualizację czy coś panie i panowie z Allegro poczynili w związku z tym problemem ?

**Comment by MaciejFrackowiak** [comment]
@marmizg Weryfikujemy źródło problemu - wrócę z odpowiedzią, gdy będę mógł przekazać wiążące informacje.

**Comment by marmizg** [comment]
> 
> 
> @marmizg Weryfikujemy źródło problemu - wrócę z odpowiedzią, gdy będę mógł przekazać wiążące informacje.

Jak wynik państwa poszukiwań ?

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się znaleźć źródło błędów, problem nie powinien już występować.

**Comment by M4GiK** [comment]
Wciąż pojawiają się losowo timeout. i landing page rany julek ... związany z 504

**Comment by MaciejFrackowiak** [comment]
@M4GiK Proszę podaj nam przykładowe trace-id takich wywołań.

**Comment by M4GiK** [comment]
Nie jestem w stanie ponowić błędu, narazie działa bez problemu.
