### ISSUE TITLE
Obrazki nie pokazują się na niektórych aukcjach

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#3027]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym

Nie wiem czy to problem API czy inny. Na niektórych aukcjach nie pojawiają się  obrazki
Najpierw wysyłałem obrazki jako linki do strony, teraz wysyłam jako body, ale błąd się powtórzył, dlatego sądzę, że to może obrazek może być odrzucany wtórnie, ponieważ API go akceptuje nie zgłaszając błędów. Czy mogę prosić o sprawdzenie dla aukcji 9114773547 podkłada obrazek zastępczy? Ponieważ nie było błędów nie mam też loga z błędami. Jeżeli okaże się niezbędny to przestawię system, żeby zapisywał też logi z prawidłowych ofert i poczekam na kolejny błąd

Aukcja bez obrazka: 

https://allegro.pl/oferta/obudowa-zegarow-mz-etz-almot-9114773547

Dziś wystawiłem tym samym algorytmem aukcję na ten sam przedmiot i obrazek się wgrał:

https://allegro.pl/oferta/obudowa-zegarow-mz-etz-almot-9117351642

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem dane dot. oferty numer 9114773547 - nie ma ona dodanych żadnych zdjęć, to nie problem z ich wyświetlaniem. Spojrzałem też w requesty z nią związane - nie widzę tam również by elementy typu IMAGE były przekazywane. Proszę sprawdź działanie Twojego mechanizmu odpowiedzialnego za dodawanie ofert.

**Comment by KrzychuWalek** [comment]
Dziękuję. Będę sprawdzał
