### ISSUE TITLE
Różnica w liczbie wpisów - lista numerów przesyłek dla zamówienia

### ISSUE THREAD

**Issue by DaveCocieto** [allegro/allegro-api#3028]
Cześć, zauważyłem w niektórych zamówieniach problem - głównie na środowisku produkcyjnym.
W szczegółach zamówienia allegro widnieje jeden wpis z numerem przesyłki z zaznaczonym typem kuriera (np. Poczta Polska).
Jednak jeżeli pobieram listę numerów przesyłek dla zamówienia przez zasób REST API:
**/order/checkout-forms/{id}/shipments**
otrzymuję dwa wpisy. Oba wpisy posiadają ten sam numer przesyłki natomiast mają inne atrybuty 'carrierId' - jeden właściwy (np. Poczta Polska) drugi 'OTHER'.
Dlaczego pojawiają się takie różnice? Pozdrawiam, Dawid

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam przykładowe id zamówienia, wówczas postaram się spojrzeć na źródło "podwójnych" danych.

**Comment by DaveCocieto** [comment]
Przykładowe: 40607682-7282-11ea-a673-974f95cbf830, 40607682-7282-11ea-a673-974f95cbf830, 40add267-72b2-11ea-8192-c7a7f36a2b95, cda4daa6-72bd-11ea-ad2c-8d66875e1e93

**Comment by MaciejFrackowiak** [comment]
Spojrzałem w logi dla zamówienia id=40607682-7282-11ea-a673-974f95cbf830:

1) o godz. 11:59 dodałeś numer trackingowy poprzez swoją aplikację opartą o REST API - i tu pojawił się wpis: "carrierName": "Poczta Polska Pocztex Pobranio" - nazwa przez Ciebie określona;

2) o godz. 12:52 numer trackingowy (ten sam) został dodany przez narzędzie nadawcze Poczty Polskiej, które numer nam przekazało:  "carrierId": "POCZTA_POLSKA".

Na froncie w przypadku, gdy sam nadajesz nazwę przewoźnikowi nazwa jest nadpisywana, gdy pojawi się dokładnie ten sam nr przesyłki - taka sytuacja miała miejsce w tym przypadku.

-----
Uproszczone zarządzanie ofertami - [wskaż najbardziej pożądane funkcjonalności](https://allegro.optimalworkshop.com/optimalsort/o274266h).
