### ISSUE TITLE
checkout-forms i filtry

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#3029]
Czy coś jest nie tak z tym zapytaniem?

lineItems.boughtAt.lte=2019-10-01T00%3A00%3A00.000Z&lineItems.boughtAt.gte=2019-11-30T00%3A00%3A00.000Z&limit=100

Wiem, że w tym okresie są dane bo bez filtra je widzę a podczas filtrowania nic nie wraca

**Comment by MaciejFrackowiak** [comment]
lineItems.boughtAt.lte -> jest górną granicą zakresu (czyli przy 2019-11-30 powinno się znaleźć).
lineItems.boughtAt.gte -> dolna granica zakresu (2019-10-01).

Jednym słowem na odwrót zastosuj daty i powinno zwrócić Tobie prawidłowo wyniki.

-----
Uproszczone zarządzanie ofertami - [wskaż najbardziej pożądane funkcjonalności](https://allegro.optimalworkshop.com/optimalsort/o274266h).

**Comment by DanielMiara** [comment]
Super, dziękuję.
Jak już jesteśmy przy filtrach.

Czy status=BOUGHT i fulfillment.status=SENT mogą być razem?
I czy są inne statusyt poza BOUGHT?

**Comment by MaciejFrackowiak** [comment]
Możesz łączyć, tylko pamiętaj, że zasób [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) zwraca ostatni dostępny status zdarzenia dla zamówienia - czyli jeżeli kupujący zapłacili to już nie zobaczysz statusu BOUGHT, a READY_FOR_PROCESSING - i dlatego wyszukiwarka zwraca zerowy wynik.

Zachęcam Cię do spojrzenia do [naszego poradnika](https://developer.allegro.pl/orders/#01) dot. zamówień.
