### ISSUE TITLE
W części pozycji dla 'checkoutForm' brakuje sygnatury produktu (external = null)

### ISSUE THREAD

**Issue by bartolomeon** [allegro/allegro-api#3030]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W zamówieniu zwracanym przez :

https://api.allegro.pl/order/checkout-forms/fdac6274-7337-11ea-8b07-c95c69b6e735

(szereg innych ma ten sam problem, to jest jeden z przykładów)

w części pozycji brakuje zewnętrznego idenyfikatora produktu (pole external jest równe null) 

Poniżej przykład, gdzie w jeden produkt ma external.id wypełnione, drugi nie:

```
....
 "lineItems" : [
      ...
      {
         "offer" : {
            "id" : "7979034292",
            "name" : "SŁOIK POJEMNIK SZKLANY HOME SWEET HOME 1000 ML",
            "external" : null
         },
         "id" : "fdac6272-7337-11ea-8b07-c95c69b6e735",
         "originalPrice" : {
            "currency" : "PLN",
            "amount" : "7.50"
         },
         "boughtAt" : "2020-03-31T10:13:03.600Z",
         "price" : {
            "currency" : "PLN",
            "amount" : "7.50"
         },
         "selectedAdditionalServices" : [],
         "quantity" : 1
      },
      {
         "quantity" : 1,
         "price" : {
            "currency" : "PLN",
            "amount" : "24.90"
         },
         "selectedAdditionalServices" : [],
         "boughtAt" : "2020-03-31T10:13:03.581Z",
         "id" : "fdac6270-7337-11ea-8b07-c95c69b6e735",
         "offer" : {
            "external" : {
               "id" : "0204009206"
            },
            "id" : "9078102052",
            "name" : "Tortownica blacha do pieczenia 26 cm z pokrywką"
         },
         "originalPrice" : {
            "amount" : "24.90",
            "currency" : "PLN"
         }
      }
   ],
...
```

Pole 'Sygnatura' w danych aukcji jest wypełnione poprawnie (ma wartość '0203018162').
W zwracanych danych z REST API część produktów ma wypełnione external.id, u pozostałych jest równe 'null' - nie rozumiem reguły.
Problem pojawił się dzisiaj (31.03.2020) ok. południa.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, pojawił się błąd w usłudze odpowiedzialnej za zwracanie danych dot. zamówień - dokładnie pomiędzy godz. 11 a 14 (31 marca 2020). Problem został już namierzony i wyeliminowany. Nowe zamówienia zawierają już sygnaturę.
Przepraszam za utrudnienia.

-----
Uproszczone zarządzanie ofertami - [wskaż najbardziej pożądane funkcjonalności](https://allegro.optimalworkshop.com/optimalsort/o274266h).

**Comment by bartolomeon** [comment]
Czy uszkodzone zamówienia zostaną skorygowane przez Allegro?

**Comment by bartolomeon** [comment]
Domyślam się, że Allegro nie zamierza niczego naprawiać, więc pytanie - w jaki sposób można dostać z REST API identyfikator produktu (external.id) mając id oferty (np. "id" : "7979034292")?
Niestety /offers/listing?seller.id=...  nie zwraca tej akurat informacji.

**Comment by anaxagore78** [comment]
Mialem podobny problem, sprobuj https://api.allegro.pl/sale/offers/7979034292

**Comment by MaciejFrackowiak** [comment]
@bartolomeon Tak, pracujemy nad tym by przywrócić brakujący external.id dla zamówień z okresu awarii.
