### ISSUE TITLE
Stany magazynowe - szczegóły

### ISSUE THREAD

**Issue by andrzejg3** [allegro/allegro-api#3031]
Dzień dobry,

Chciałbym wykorzystać API allegro do aktualizowania stanów magazynowych ofert (po ich sprzedaży w zewn. sklepie internetowym). Znalazłem w dokumentacji do tego request _PUT /sale/offer-quantity-change-commands/{commandId}_. Nie mogę jednak odnaleźć metody w API, która pobierze mi wszystkie produkty znajdujące się w danej ofercie wraz z kodami EAN? 

Znalazłem w dokumentacji metody do pobrania ofert wraz ze szczegółami, ale nie widzę tam listy produktów wraz z kodami EAN. Czy dla oferty występuje jedynie ogólna informacja o stanie magazynowym _("stock": {"available": 1,"sold": 0},)_? Jak pobrać informację o powiązanym z ofertą produkcie? Czy w allegro **jedna oferta=tylko jeden powiązany produkt**?

Jeżeli odpowiedź na moje pytania znajduję się już gdzieś w dokumentacji lub w innym issue, to przepraszam i proszę o wskazanie zasobu.

**Comment by MaciejFrackowiak** [comment]
W Allegro do jednej oferty możesz przypisać tylko jeden produkt. Sam produkt (ten sam) może być przypisany do dowolnej liczby ofert w Allegro.
Nie mamy zasobu zwracającego wszystkie oferty przypisane z danym produktem. Natomiast jak zauważyłeś pobierając oferty przez [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation//#operation/getOfferUsingGET) uzyskasz dla każdej z nich przypisany produkt (pole "product.id") i tak możesz stworzyć listę ofert z tym samym id produktu. 
Odnośnie liczb w polu stock:
1) available - zwraca dostępną ilość;
2) sold - sprzedane w ciągu ostatnich 30 dni.

Zachęcam Cię do lektury naszych poradników - [zarządzanie ofertami](https://developer.allegro.pl/my_offers/) oraz [jak powiązać ofertę z produktem](https://developer.allegro.pl/productization/).

**Comment by andrzejg3** [comment]
Dziękuję, zapoznam się szczegółowo z dokumentacją. Domyślam się jednak, że będzie problem z zestawami, chyba, że można śledzić listę produktów wraz z ich EAN w zrealizowanych zamówieniach.

**Comment by MaciejFrackowiak** [comment]
W zamówieniu, w obiekcie lineItems zwracamy "offer.id" pozwalające na zidentyfikowanie jakie oferty weszły w jego skład. W kolejnym kroku należałoby pobrać oferty i tak poznać ich "product.id".
