### ISSUE TITLE
Adresy IP serwera autoryzacyjnego

### ISSUE THREAD

**Issue by maqlec** [allegro/allegro-api#3032]
Skąd można otrzymać informacje na temat adresów IP z których otrzymywane są notyfikację od Allegro.
Nasze środowisko testowe jest schowane przed światem.

**Comment by kfijalko** [comment]
Allegro wysyła jakieś notyfikacje?

**Comment by MaciejFrackowiak** [comment]
@maqlec Proszę doprecyzuj jakie notyfikacje masz na myśli?

**Comment by maqlec** [comment]
Przepraszam, może źle się wyraziłem:) chodzi o autoryzacyjne flow. Niestety sandbox nie może wrócicić na naszego URLa z kodem autoryzacyjnym

**Comment by MaciejFrackowiak** [comment]
Adres wywołania metod: https://api.allegro.pl.allegrosandbox.pl/
Adres do autoryzacji: https://allegro.pl.allegrosandbox.pl/auth/oauth/

**Comment by maqlec** [comment]
Ok, dziękuję. W sumie naprowadziłeś mnie na oczywisty trop. Po prostu dopuściliśmy adres IP domeny autoryzacyjnej tzn allegro.pl.allegrosandbox.pl.
