### ISSUE TITLE
Weryfikacja danych konta firmowego na sandboxie

### ISSUE THREAD

**Issue by amazur31** [allegro/allegro-api#3033]
Bardzo proszę o aktywację konta firmowego o loginie ex7_test_sprz na sandboxie.

**Comment by MaciejFrackowiak** [comment]
Konto aktywowałem. W celu weryfikacji konta Firma proszę prześlij dwa dowolne pliki w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by amazur31** [comment]
Przesłałem dwa dowolne pliki. Ciągle wyświetla mi się 

> Nieaktywne - trwa weryfikacja Twoich danych.

**Comment by MaciejFrackowiak** [comment]
Widzę, że Twoje konto jest już firmowe zweryfikowane.

**Comment by amazur31** [comment]
Dzięki!
