### ISSUE TITLE
Allegro + woocommerce

### ISSUE THREAD

**Issue by ttomekb** [allegro/allegro-api#3034]
Witam
w jaki sposób zsynchronizowawszy sklep postawiony na wordpress + woocommerce z allegro?

**Comment by MaciejFrackowiak** [comment]
W tej sprawie proszę skontaktuj się z dostawcą swojego oprogramowania - niestety, z racji dużej ilości dostępnego na rynku oprogramowania nie mamy możliwości wsparcia każdego z nich. Być może także któryś z użytkowników forum będzie mógł udzielić Tobie wskazówek.

**Comment by ttomekb** [comment]
woocommerce to jest z popularniejszych rozwiązań. jak sie zabrać w ogole za połaczenie sklepu z allegro poprzez api

**Comment by ospiotr** [comment]
@ttomekb 

Na rynku istnieje kilka rozwiązań które pozwalają spiąć WooCommerce z Allegro i nie wymagają napisania ani jednej linijki kodu - cała komunikacja między platformami została przygotowana przez twórców rozwiązań:

https://www.wpdesk.pl/sklep/allegro-woocommerce/
https://linuxpl.com/blog/allegro-woocommerce/

Jeśli jednak wolałbyś rozpocząć tworzenie własnej aplikacji, zacznij od tych linków:
https://docs.woocommerce.com/document/create-a-plugin/
https://developer.allegro.pl/getting_started/

**Comment by pkrzemo** [comment]
@ttomekb , @ttomekb - zabrzmiało to zupełnie jak kryptoreklama WooCommerce ;-)
