### ISSUE TITLE
Buyer information fields

### ISSUE THREAD

**Issue by DenisTok** [allegro/allegro-api#3035]
Hi, is firstName, lastName and phoneNumber appear in buyer struct in checkout-forms every time or can be empty? 
May I register a user in my service using this information to be able to fine an order in my office to give customer?

**Comment by MaciejFrackowiak** [comment]
Yes, firstName, lastName and phoneNumber are always visible - this data is required when you register account on Allegro or buy as a guest. You can use this data only to process the order.

**Comment by DenisTok** [comment]
Thanks a lot
