### ISSUE TITLE
description - jak to działa?

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#3036]
Nie rozumiem jak description działa. Podczas tworzenia draftu

`"content"	=> '<p>Tekstowy opis przedmiotu B</p>'`
Jest OK
`"content"	=> 'Tekstowy opis przedmiotu B'`
Response status code: 422

To samo próbowałem:

```
iPhone is a revolutionary new
<p></p>
<h1>H1</h1>
<h2>H2</h2>
<li>s</li>
<li>s</li>
<li>s</li>
<p></p>
<ol>
    <li>s</li>
    <li>s</li>
    <li>s</li>
</ol>
<p></p>
<p>
    <b>to jest B</b>
</p>
```

Response status code: 422

**Comment by MaciejFrackowiak** [comment]
Treść opisu musisz umieścić w znacznikach HTML - tak jak zrobiłeś to w pierwszym przykładzie.
Proszę zajrzyj do [naszego poradnika](https://developer.allegro.pl/sale/#step-5-description), gdzie opisujemy wymagania dot. opisu oferty.

-----
Uproszczone zarządzanie ofertami - [wskaż najbardziej pożądane funkcjonalności](https://allegro.optimalworkshop.com/optimalsort/o274266h).

**Comment by DanielMiara** [comment]
No ja rozumiem ale w Waszym poradniku jest  "możesz korzystać tylko z określonych znaczników HTML:" a nie MUSISZ używać.
Co do moich przykładów co jest źle z ostatnim? Chyba, że błedem jest, że tekst "iPhone is a revolutionary new" nie jest html w <p>

**Comment by mindc** [comment]
@DanielMiara 
dokładnie, frazę "iPhone is a revolutionary new" musisz zamknąć w <p/>

**Comment by DanielMiara** [comment]
Przydnam, że to trochę dziwne, że nie można wysłać czystego tekstu no ale jak nie to nie ;)

**Comment by mindc** [comment]
@DanielMiara 
człowiek przyzwyczajony jest do HTML, który jest dość luźnym formatem... Na opisy w ofertach trzeba patrzeć raczej jak na XML, może nie strict (brak root'a), ale jednak...

**Comment by DanielMiara** [comment]
Rozumiem ale przy tworzeniu draft chyba można by użyć czystego tekstu bo specjalnie walidowanie go sprawia niepotrzebne problemy. Pozbycie się części HTML to nie problem ale zaraz może się okazać, że trzeba go dodać lub zwalidować czy są potwierane a nie pozamykane tagi itd.

**Comment by DanielMiara** [comment]
Czy możecie mi wytłumaczyć co w tym przykładzie jest źle?

```
<p>iPhone is a revolutionary new ...




<h1>H1</h1>
<h2>H2</h2>

  s
  s
  s




  s
  s
  s



<b>to jest B</b>
</p>
```

**Comment by mindc** [comment]
@DanielMiara 
nie możesz zamykać h1/h2 w p
prawidłowo powinno być:
```
<p>iPhone is a revolutionary new ...



</p>
<h1>H1</h1>
<h2>H2</h2>
<p>
  s
  s
  s




  s
  s
  s



<b>to jest B</b>
</p>
```

**Comment by DanielMiara** [comment]
@mindc czyli zakładam, że nie zamknięcie < p > jest traktowane jako błąd i zwraca Response status code: 422?
