### ISSUE TITLE
Prawidłowe wystawianie kompletów...

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#3037]
Zastanawiam się jak najbardziej prawidłowo wystawić jakiś komplet, np. komplet filtrów do samochodu. Jest na to przeznaczona osobna kategoria nawet. Ale...  
W ofercie można podać jeden EAN, tudzież jedno pole z Numerem katalogowym części.

Obecnie nie podaję EAN w takich kompletach/zestawach, za dużo błędów że produkt nie jest we właściwej kategorii.

Chyba że można inaczej...

**Comment by MaciejFrackowiak** [comment]
Niestety, obecnie dla takich zestawów nie znajdziesz dobrego rozwiązania - występują ograniczenia, o których wspominasz. Zdajemy sobie sprawę z nich - mamy to odnotowane na liście sugestii dot. rozwoju REST API.

**Comment by mindc** [comment]
Czy coś się zmieniło w tej sprawie?

**Comment by MaciejFrackowiak** [comment]
Nie, sytuacja obecnie bez zmian.
