### ISSUE TITLE
Problem z nadawaniem przesyłek dla Allegro Smart

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#3039]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od kilkunastu minut notujemy problemy z wysyłką przesyłek Smartowych do InPostu. Są one odrzucane z powodem błędny mail. W tym samym czasie występują problemy z logowaniem do API i na Waszej stronie.

Proszę o weryfikację i określenie jak duża jest skala problemu.

**Comment by MaciejFrackowiak** [comment]
Tak, mamy problemy techniczne - szczegóły w poście GH #3040

**Comment by shivson1337** [comment]
Dziękuję za informacje.
