### ISSUE TITLE
[WEBAPI] Problem z nowym kontem - Niepoprawna wartość klucza WebAPI lub klucz został zablokowany

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#304]
Dzień dobry

Założyłem nowe konto , aktywowane przelewem  itp.  jednak mamy już na wstepie problem techniczny z wystawieniem aukcji poprzez "stare" WEBAPI. Przechodzimy na RESTAPI ale to potrwa i póki co prosiłbym o aktywację WEBApi. Klucz już sobie wygenerowałem na portalu deweloperskim wg nowych wskazówek, jednak po próbie logowania pojawia się komunikat "Niepoprawna wartość klucza WebAPI lub klucz został zablokowany" , wartość klucza jest poprawna ponieważ zarejestrowałem aplikację na portalu deweloperskim wg nowych zasad i wskazówek. Znalazłem jednak podobny problem tutaj:
https://github.com/allegro/allegro-api/issues/273
i pada tam odpowiedź technika:  "LukaszKorek commented 8 days ago
Poproszę o login konta na środowisku testowym. Problem może powodować brak aktywacji. "

W takim razie uprzejmie proszę o aktywację WEB Api, ponieważ jeszcze zanim zostanie w
2019 wygaszone będziemy z niego korzystać szczególnie teraz przy wdrożeniu.
Dziękuję i proszę o możliwie szybką aktywację - dział techniczny stoi  :)

Login: Sma-PRIDE  (środowisko produkcyjne)

PS. Ten sam klucz działa poprawnie w REST API, a nie działa w WEB, także problem prawdopodobnie z aktywacją.

Dzięki!

**Comment by MartaNowaczyk** [comment]
Dzień dobry, 
widzę, że napisałeś również przez formularz. Podeślij nam tam pliki z requestem i responsem w formacie XML z opisanym błędem, a sprawdzimy co się dzieje.

**Comment by MartaNowaczyk** [comment]
Dziękuję za przesłane informacje. Przetestowałam podany klucz (Client ID) i nie otrzymuję podanego błędu. Client ID nie wymaga też aktywacji. Proszę sprawdzić działane swojego kodu.

**Comment by Adam1610** [comment]
Stawiam milion dolarów że to nie kod :) bo tego samego kodu używam z powodzeniem na starszym koncie. Zauważyłem że zmienił się format kluczy (teraz są bez myślników), konto jest założone klika dni temu - na pewno nie ma to wpływu na pracę?  
Dziwne jest to , że gdy podstawiam stary klucz z innego konta wszytsko działa jak należy. Dlatego naprawdę nie winił bym tu kodu, to musi być coś innego , dlatego się do Państwa zwracam...

**Comment by Adam1610** [comment]
Aktywowałem abonament sklepowy i poszło. Wygląda na to że miało to związek (akucje sklepowe), choć dziwne, że nie mogłem się tylko zalogować.. bez wystawiania aukcji.

**Comment by MartaNowaczyk** [comment]
Dzięki za informację. Sprawdzimy taki przypadek, bo to nie powinno mieć wpływu na możliwość logowania.

**Comment by MartaNowaczyk** [comment]
Mogę potwierdzić, tak jak pisałam nie ma to wpływu na logowanie, także musiały wystąpić inne przyczyny błędu.
