### ISSUE TITLE
Problem z aktualizacją stanu produktu [PUT sale/offers]

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3041]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W dniu dzisiejszym dla jednego z naszych klientów zaczął występować problem z aktualizacją stanu produktów. Dotyczy to około 20 aukcji na jego koncie. Komunikat 

```
    0 => {#1662
      +"code": "VALIDATION_ERROR"
      +"message": "Invalid delivery or location part."
      +"details": ""
      +"path": ""
      +"userMessage": "Błędne dane wysyłki lub lokalizacji."
    }
```

`PUT sale/offers/{id} || trace-id:e6e047e70dfe20e3`

Dodam, że podana aukcja była już aktualizowana (ostatnio 2020-03-27 11:25:09) i nie było problemów. Przebieg aktualizacji:
- pobieram aukcję z allegro GET sale/offers/{id}
- aktualizuję stock.available
- wysyłam PUT sale/offers/{id}

**Comment by MaciejFrackowiak** [comment]
Spojrzałem na Twój request - pole z "shippingRates" ma wartość null, stąd błąd 422.
Musisz w nim przekazać id cennika dostawy - dotychczas jeżeli wystawiałeś ofertę przez WWW nie musiałeś wybierać cennika dostawy z listy, a wyłącznie określić ceny poszczególnych metod dostawy - to zostało zmienione, stąd otrzymany komunikat "Błędne dane wysyłki lub lokalizacji."
Zatem dokonaj edycji oferty raz jeszcze przypisując do niej właściwy cennik - dostępne, swoje cenniki pobierzesz przy pomocy [GET /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/getListOfShippingRatestUsingGET).

**Comment by Radeq** [comment]
@MaciejFrackowiak - czy przy edytowaniu/tworzeniu takiej oferty na stronie www również jest wymagane wybranie cennika?

**Comment by MaciejFrackowiak** [comment]
@Radeq Obecnie już tak.

**Comment by Radeq** [comment]
@MaciejFrackowiak , dziękuję za informację
