### ISSUE TITLE
brak numeru telefonu

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#3042]
- [X] z zasobem REST API

:beetle: **Opis**

W formularzu b61e3c02-744d-11ea-8d8c-5902df19845f pole z numerem telefonu klienta jest puste.

**Czy klient może nie mieć numeru telefonu?**

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem zamówienie podane przez Ciebie:

1. w formularzu dostawy kupujący podał numer telefonu - widoczny jest on w obiekcie delivery, pole "phoneNumber", zatem realizacja zamówienia jest w pełni możliwa;
2. natomiast brak numeru telefonu widnieje w obiekcie buyer - konto kupującego było zarejestrowane "dłuższy" czas temu, gdy w danych konta nie wymuszaliśmy podania nr telefonu.

**Comment by Lebioda** [comment]
1. tak, zamówienie można zrealizować.
2. konto ma mniej niż 3 lata, ale skoro jesteś pewny, że numer telefonu nie był wymagany to temat do zamknięcia. Zmieniam skrypty, że to pole może być puste.

**Comment by MaciejFrackowiak** [comment]
Jeżeli obecnie użytkownik chciałby dokonać edycji swoich danych to oczywiście będziemy już nalegać do uzupełnienia nr telefonu.
