### ISSUE TITLE
brak informacji o zamówieniach

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#3043]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od godz 15.00 brak informacji o zamówieniach przekazywanych przez API (RESTAPI)
wcześniej między 12-14 nie były wysyłane wiadomości do klientów

**Comment by creative-pl** [comment]
Potwierdzam, od godziny ~15 nie zwraca nowych zamówień dla /checkout-forms/

**Comment by pliszka2** [comment]
potwierdzam nam też nie pobiera zamówień na produkcji

**Comment by mPiter2019** [comment]
U mnie też ani jednego zamówienia od 15. 
W ogóle coś majdrują, bo od trzech dni nie mogę wznowić dwóch aukcji(są dostępne przedmioty, ale system zakończył aukcję).

**Comment by arolznov** [comment]
tak samo tutaj, koło południa sytuacja była odwrotna - zamówienia były widoczne w api a na stronie allegro nie

**Comment by mojosoft** [comment]
Dokładnie, mają niezły burdel ;) nie możan też było składać wniosków o zwrot

**Comment by bacok** [comment]
Mamy to samo. Pobieramy eventy przyrostowo i wpadają ciągle te same - w sensie dublują się, np. po 16:00 wpadły eventy występujące o 13:45... szkoda gadać.

**Comment by jasiek07** [comment]
fakt nie działa ściąganie zamówień , api zwraca info że dane zamówienie nie istnieje

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście mieliśmy pewne problemy techniczne, udało nam się je rozwiązać. Zamówienia już powinny spływać normalnie.

**Comment by mojosoft** [comment]
Niestety nieprawda, zamówienia nie schodzą na bieżaco, ostatnie mamy z 15.38

**Comment by pliszka2** [comment]
potwierdzam my też nie mamy jeszcze wszystkich ruszyło pobrało jedno i stoi

**Comment by mPiter2019** [comment]
u mnie też nic nie schodzi

**Comment by mojosoft** [comment]
teraz znowu są eventy z godz 12.20 , ale sieczka

**Comment by arolznov** [comment]
dodało tylko jedno zamówienie z 15:37

**Comment by mojosoft** [comment]
dokładnie klienci już dzwonią i piszą gdzie produkt, kiedy wysyłka ;)

**Comment by PawelTaberski** [comment]
Badamy tą sytuację prośba o cierpliwość, jak tylko uda się rozwiązać problem to poinformuję tutaj.

**Comment by mojosoft** [comment]
coś ruszyło, jeszcze są opóźnienia około 40-50 minut

**Comment by ponowemu** [comment]
Zamówienia zwracane przez API mają godzinę zakończenia płatności +2h względem oryginalnej godziny widocznej w waszym UI.

**Comment by ponowemu** [comment]
Straszna lipa, nic nie działa

**Comment by mPiter2019** [comment]
Działa, działa. Prowizję Allegro zawsze zapłacisz, ten system akurat się NIGDY nie psuje.

**Comment by PawelTaberski** [comment]
@ponowemu Co do godziny wszystko się zgadza, była zmiana czasu, API zwraca w UTC, a front pokazuje w czasie lokalnym. Także jeśli w API jest np. 15:00, to na froncie pokaże się 17:00.

**Comment by PawelTaberski** [comment]
Zamówienia powinny już spływać, prosiłbym o informacje czy teraz działa u Was poprawnie.

**Comment by mojosoft** [comment]
U mnie działa prawidłowo. dziękuje za szybką reakcje.
