### ISSUE TITLE
doLoginWithAccessToken - SoapFaultClientException: null 

### ISSUE THREAD

**Issue by ekonopliov** [allegro/allegro-api#3044]
Witam,

kiedy probuje uzyskac sessionHandlePart przez doLoginWithAccessToken otrzymuje blad bez pojasnienia przyczyny: null. 

Do requestu podaje wszystko, co jest required:
1. token, otrzymany z RESTu, z https://allegro.pl/auth/oauth/token?grant_type=client_credentials
2. countryCode 121, czyli Litwa
3. oraz klucz WebAPI z https://apps.developer.allegro.pl

Jezeli jeden z wymienionych parametrow jest bledny, otrzymuje odpowiedni blad. Jednak gdy wszystkie sa takie, to otrzymuje nulla :(

Czy sa jakies porady?

**Comment by MaciejFrackowiak** [comment]
1. Token uzyskany poprzez autoryzację client_credentials nie posiada kontekstu zautoryzowanego użytkownika, dlatego wywołując metodę doLoginWithAccessToken nie uzyskasz w odpowiedzi ID konta, dla którego sessionHandlePart miałoby być - musisz zmienić autoryzację na code_flow lub device_flowe;

2. Obecnie w Allegro obsługujemy tylko jeden countryCode = 1 (Polska).
