### ISSUE TITLE
Status zamowienia /order/checkout-forms

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#3045]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Czy mozecie sprawdzic zamowienie 948ea312-71d5-11ea-bf6c-adb773c00ddd i 
f339b6c2-71d5-11ea-a5f3-017922edfaed, klient twierdzi ze wypełnil formularz zaraz po zakupie, 
Zasób  /order/checkout-forms zwraca status BOUGHT.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem oba zamówienia:
1. 948ea312-71d5-11ea-bf6c-adb773c00ddd - nie wybrano metody dostawy;
2. f339b6c2-71d5-11ea-a5f3-017922edfaed - nie wybrano metody dostawy.

Status BOUGHT jest w pełni prawidłowy.

**Comment by anaxagore78** [comment]
Bardzo dziekuje.
