### ISSUE TITLE
zamówienia

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#3046]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Większość opłaconych zamówień z 1.04.2020 i 2.04.2020 nie występuje w dzienniku zdarzeń pobieranym metodą https://api.allegro.pl/order/checkout-forms

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykład zamówienia, które nie jest dostępne podczas odpytywania ww. zasobu.

**Comment by ciaglok2** [comment]
b1fbb942-743e-11ea-bfc0-43631bc4b76e

**Comment by MaciejFrackowiak** [comment]
Bez najmniejszych problemów dotarłem do wskazanego zamówienia korzystając z GET /order/checkout-forms?buyer.login=(tu_login_kupującego) - początek response:

```
{
    "checkoutForms": [
        {
            "id": "b1fbb942-743e-11ea-bfc0-43631bc4b76e",
            "messageToSeller": null,
            "buyer": {
                "id": "78852xxxx",
                "email": "xxxx+xxxxxxx@allegromail.pl",
                "login": "Client:7885xxxx",
```

**Comment by ciaglok2** [comment]
a ja przez "https://api.allegro.pl/order/checkout-forms?lineItems.boughtAt.gte=2020-03-30T22%3a00%3a00.000Z&lineItems.boughtAt.lte=2020-04-03T22%3a00%3a00.000Z&limit=100&offset=0&status=READY_FOR_PROCESSING"
go nie dostaję

**Comment by MaciejFrackowiak** [comment]
Request: GET /order/checkout-forms?lineItems.boughtAt.lte=2020-04-03T22:00:00.000Z&lineItems.boughtAt.gte=2020-03-30T22:00:00.000Z&status=READY_FOR_PROCESSING zwraca ww. zamówienie.

**Comment by ciaglok2** [comment]
użyłem dokładnie powyższego (napisanego przez pana) request i nie dostałem tych zamówień w response

**Comment by ciaglok2** [comment]
request: https://api.allegro.pl/order/checkout-forms?buyer.login=Client:78852***
response: "{\"checkoutForms\":[],\"count\":0,\"totalCount\":0}"

**Comment by ciaglok2** [comment]
moja aplikacja posługiwała się tokenem od innego konta, niż powinna. pomieszanie tokenów nastąpiło, gdy (z niewyjaśnionego powodu) w środę REST API odrzuciło jeden z tokenów odświeżających i zażądało ponownej autoryzacji. żądanie otworzyło się w domyślnej przeglądarce, a nie tej, która używana jest z kontem, które miało zostać zautoryzowane. Do czasu, aż Allegro umożliwi przełączanie pomiędzy kontami w ramach jednej przeglądarki przydałby się mechanizm zabezpieczający przed taką sytuacją (obok kodu do autoryzacji jeszcze nazwa konta Allegro, które może się danym kodem posłużyć do autoryzacji).

**Comment by MaciejFrackowiak** [comment]
W opisanym przez Ciebie przypadku możesz skorzystać z parametru prompt=confirm, który wyświetla użytkownikowi ekran potwierdzenia konta. Szczegółowo opcję opisujemy w [naszym poradniku](https://developer.allegro.pl/auth/#user).
