### ISSUE TITLE
Brak kodu weryfikacyjnego

### ISSUE THREAD

**Issue by sikorag** [allegro/allegro-api#3047]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy zakupach bez konta na środowisku testowym, nie działa wysyłanie kodu weryfikacyjnego na podany w formularzu adres e-mail.
Nie otrzymałem żadnego kodu chociaż kilkukrotnie klikałem "Wyślij ponownie" i pojawiał się napis "Kod został wysłany".
Proszę o weryfikację.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć Twojego błędu, otrzymałem kod weryfikacyjny. Zwróć uwagę, czy wiadomość nie trafiła do folderu Spam. Jeśli nie, podaj proszę adres mailowy, na który miał trafić kod. Zweryfikuję, czy wiadomość od nas wyszła. Adres możesz podać tutaj lub wyślij go za pomocą [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - wtedy dopisz w zgłoszeniu GitHub #3047.
