### ISSUE TITLE
ERROR 400 /auth/oauth/token?grant_type=refresh_token

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3050]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] z logowaniem lub autoryzacją

:beetle: **Opis**
Dzień dobry, od dzisiaj przestało działać odświeżanie i pobieranie tokenów rest api na produkcji. Masowo jest bad request 400. U wielu różnych Klientów nie ma możliwości odświeżenia tokenu ani ponownego dodania konta. Proszę o sprawdzenie i poprawę. TraceId się nie zapisuje.

2020-04-06 08:34:56.3870101 
REQUEST 2020-04-06 08:34:56.3870101
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=#&redirect_uri=#%2FAuth' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic ' \

RESPONSE 2020-04-06 08:34:56.4495113 Duration: 62,5012ms
{
  "Data": null,
  "Validation": {
    "Errors": null,
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": "{\"error\":\"invalid_grant\",\"error_description\":\"Invalid refresh token: \"}"
}

**Comment by KrzysztofStachyra** [comment]
U nas podobnie grupa klientów zgłasza ciągle problemy z autoryzacją i timeoutami.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu. Dodatkowo prosiłbym o przykładowy refresh token, który zwrócił status 400.  [Link do formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w zgłoszeniu proszę dopisać GitHub #3050.

**Comment by alekskuc** [comment]
@PrzemyslawLukanowski przesłałem pięć przykładowych tokenów przez formularz. Klienci którym wygasł token nie mają możliwości korzystania z rest api.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski prośba o pilną analizę/poprawę, dziś z rana mamy kolejne 20 zgłoszeń o błędach z odwieżeniem tokena

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem przykładowe tokeny do zgłoszenia, analizujemy problem. Wrócę z odpowiedzią w tym wątku.

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc  Sprawdziłem przesłane tokeny:
- trzy pierwsze były już nieaktywne dwa tygodnie wcześniej. Przypadek jest bardzo zbliżony do tego, który opisałeś w wątku #2881 - możecie zweryfikować to po swojej stronie?
- pozostałe dwa refresh tokeny zostały wykorzystane odpowiednio 2020-04-06 23:43 i 2020-04-06 23:34 - w odpowiedzi zwróciliśmy status 200 z nową parą tokenów.

**Comment by alekskuc** [comment]
> * trzy pierwsze były już nieaktywne dwa tygodnie wcześniej. Przypadek jest bardzo zbliżony do tego, który opisałeś w wątku #2881 - możecie zweryfikować to po swojej stronie?

@PrzemyslawLukanowski tak starych tokenów nie jestem w stanie sprawdzić, bo już nie ma dla nich logów. W tamtym wątku zweryfikowałem, że zapis u nas do bazy par tokenów dla http 200 działa prawidłowo.

> * pozostałe dwa refresh tokeny zostały wykorzystane odpowiednio 2020-04-06 23:43 i 2020-04-06 23:34 - w odpowiedzi zwróciliśmy status 200 z nową parą tokenów.

Natomiast, tutaj udało się zweryfikować, że odświeżanie nie działało cały dzień od 2020-04-06 12:48:31.7385315 do 2020-04-06 23:43:27.6840202.

Na przykładzie przesłanego 4 refresh tokenu z końcówką JkWaIU0SUNXtU29sQ.

1. Uzyskanie pary tokenów z refresh JkWaIU0SUNXtU29sQ. Uzyskany token wygasa 2020-04-06 12:47:40

```
REQUEST 2020-04-06 00:47:40.6614465 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...9ReWEaI5LZC02zolNyA&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 00:47:40.7239453  Duration: 62,4988ms
{
  "Data": {
    "access_token": "...JqGVOFa8mDC8_ZogYV2PqAmNSEN5nrgXTP1NPCMKHFv9PmhA",
    "expires_in": 43199,
    "jti": "04d77e48-66ff-4699-893a-22a480bfe3f8",
    "refresh_token": "...JkWaIU0SUNXtU29sQ",
    "scope": "allegro_api",
    "token_type": "bearer",
    "Error": false,
    "StatusCode": 0,
    "Message": null
  },
  "Validation": null,
  "Exception": null,
  "TraceId": null,
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```

2. Aplikacja zaczyna próby odświeżenia tokenu, bo token z parą refresh wygasał 2020-04-06 12:47:40. Cały dzień leci http 400.

```
REQUEST 2020-04-06 12:48:31.6760282 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 12:48:31.7385315  Duration: 62,5033ms
{
  "Data": null,
  "Validation": null,
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": ""
}

REQUEST 2020-04-06 12:48:58.5354672 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 12:48:58.5510939  Duration: 15,6267ms
{
  "Data": null,
  "Validation": null,
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": ""
}

REQUEST 2020-04-06 17:50:35.7799493 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 17:50:35.8424504  Duration: 62,5011ms
{
  "Data": null,
  "Validation": null,
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": ""
}

REQUEST 2020-04-06 19:56:27.8777826 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 19:56:27.8942462  Duration: 16,4636ms
{
  "Data": null,
  "Validation": null,
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": ""
}

REQUEST 2020-04-06 21:49:57.2817065 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 21:49:57.3441937  Duration: 62,4872ms
{
  "Data": null,
  "Validation": null,
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": null,
  "Error": true,
  "StatusCode": 400,
  "Message": ""
}
```
3. Dopiero o 2020-04-06 23:43:27.6058692 udaje się odświeżyć token i Klienci mogą znów używać rest api. Nowe tokeny zapisały się w bazie prawidłowo.

```
REQUEST 2020-04-06 23:43:27.6058692 
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...JkWaIU0SUNXtU29sQ&redirect_uri=#' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Basic #' \

RESPONSE 2020-04-06 23:43:27.6840202  Duration: 78,151ms
{
  "Data": {
    "access_token": "...RsDd0Kah5fGh1KddFfCpiULsks5ZiLW01Eax2l3hq6J5McxCQ",
    "expires_in": 43199,
    "jti": "98476e70-07f6-4a38-91bc-63043ad6a713",
    "refresh_token": "...vaYQifAyc8TcICE4RvOAvWy0SmZNwNPmZjuuEcA",
    "scope": "allegro_api",
    "token_type": "bearer",
    "Error": false,
    "StatusCode": 0,
    "Message": null
  },
  "Validation": null,
  "Exception": null,
  "TraceId": null,
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```
Czy to jest jednorazowy błąd w rest api?
Czy może uzyskany token ...JqGVOFa8mDC8_ZogYV2PqAmNSEN5nrgXTP1NPCMKHFv9PmhA wygasa później, a nie zgodnie ze zdekodowanymi informacjami o 2020-04-06 12:47:40?
Proszę o weryfikację.

**Comment by PrzemyslawLukanowski** [comment]
Wrócę z odpowiedzią po weryfikacji.

**Comment by PrzemyslawLukanowski** [comment]
Żrodłem problemu była wzmożona liczba żądań (powyżej 60rps) do allegro.pl, co przyczyniło się do nałożenia blokady na adres.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski dziekuję, może wartałoby zmienić odpowiedź tak by można było zidentyfikować taką sytuację

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji zwracamy odpowiedź 429. W załączonych logach widnieje 400, ponieważ nie są to odpowiedzi bezpośrednio z Allegro - korzystają Państwo z jakiegoś proxy.

**Comment by alekskuc** [comment]
Dzień dobry, dziękuję za weryfikację. 

> Żrodłem problemu była wzmożona liczba żądań (powyżej 60rps) do allegro.pl, co przyczyniło się do nałożenia blokady na adres.

Wiadomo dla jakich metod został przekroczony limit?

> W takiej sytuacji zwracamy odpowiedź 429. W załączonych logach widnieje 400, ponieważ nie są to odpowiedzi bezpośrednio z Allegro - korzystają Państwo z jakiegoś proxy.

Nie ma prawidłowej odpowiedzi json z nagłówkiem 429, bo ten request kończy się błędem w postaci wyjątku.

```
"Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (400) Bad Request.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  }
```
Nie ma szansy na deserializację jsona w przypadku takiego błędu połączenia:

```
"Data": null,
"Validation": null,
```
Przykładem prawidłowej odpowiedzi z kodem 406 może być po prostu wejście na przykładowy adres przez przeglądarkę. Taki request nie powoduje wyjątków w .net.

```
Request URL: https://api.allegro.pl.allegrosandbox.pl/sale/offers?offer.id=6206822450
Request Method: GET
Status Code: 406 
Remote Address: 185.31.27.131:443
content-length: 249
content-type: application/json; charset=utf-8
date: Tue, 14 Apr 2020 10:50:10 GMT
server: envoy
status: 406
trace-id: 5c4f2acc649f19c2
x-envoy-upstream-service-time: 1

Odpowiedź jest:

{
"errors": [
{
"code": "NotAcceptableException",
"message": "Not acceptable representation requested. Please check 'Accept' request header",
"details": null,
"path": null,
"userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
}
]
}

```

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku został przekroczony limit liczby requestów do allegro.pl, nie do allegro.api.pl - czyli miały na to wpływ żądania związane z autoryzacją i przedłużeniem ważności tokena. Na allegro.pl captcha jest w formie htmla, dlatego nie zobaczycie JSON-a, możecie tylko zwrócić uwagę na kod odpowiedzi.

**Comment by alekskuc** [comment]
> **W tym przypadku został przekroczony limit liczby requestów do allegro.pl, nie do allegro.api.pl -** czyli miały na to wpływ żądania związane z autoryzacją i przedłużeniem ważności tokena. (...)

@PrzemyslawLukanowski to ja tutaj czegoś nie rozumiem. 

Za dużo requestów poszło do allegro.pl, bo przestało działać odświeżanie tokenów i nasza aplikacja próbowała w nieskończoność odświeżyć token. To według mnie jest skutek problemu, a nie źródło.

Będę zmuszony obsługiwać w mojej aplikacji losowe nie działanie odświeżania żeby nie dostać blokady, co jest minimalizowaniem skutków problemu.

W prawidłowym działaniu tokeny są odświeżane zgodnie z dokumentacją co 12 godzin, wiec nie widzę tu możliwości przekroczenia limitu 60 rps.

Pytanie jest nadal to samo: dlaczego przestało działać odświeżanie tokenów w api?

**Comment by PrzemyslawLukanowski** [comment]
Wyjaśnię to na przykładzie tokena z końcówką kN2NkZmM3NjM3In0 (nie uwzględniam końcowej sygnatury tokena): 
- 2020-04-09 11:24:47 - została wygenerowana nowa para tokenów,
- 2020-04-09 15:53:15 - ma miejsce akcja ze strony użytkownika, która usuwa powiązanie z wcześniej wygenerowaną parą tokenów, mogła to być zmiana hasła. Od tego momentu widzimy, że wywołanie jakiegokolwiek zasobu kończy się odpowiedzią 401,
- 2020-04-09 23:29:02 - nastepuje pierwsza próba użycia refresh tokena z  11:24. Ze względu na działanie z 15:53 odpowiadamy statusem 400, ponieważ refresh jest już nieważny,
- do chwili obecnej otrzymujemy próby odświeżenia tokena za pomocą refresha z 11:24.

**Comment by alekskuc** [comment]
Dzień dobry, to teraz jest wszystko jasne. Źródłem problemu jest złożeniem kilku elementów:
1. Brak obsługi odpowiedzi 401 gdzie jest akcja ze strony użytkownika, która usuwa powiązanie z wcześniej wygenerowaną parą tokenów, mogła to być zmiana hasła.
2. Występuje ogólnie zwiększony ruch do 60 rps
3. Ban na adres w allegro.pl z catcha w html zamiast json
4. Nie działają wszystkie tokeny nawet te prawidłowe.
Dziękuję za weryfikację.
