### ISSUE TITLE
ERROR 503 SERVICE_UNAVAILABLE /offers/listing

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3051]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**
Dzień dobry, czym jest powodowany błąd SERVICE_UNAVAIBLE?

```
BGWorker ERROR 2020-04-06 09:29:20.0744356 
REQUEST 2020-04-06 09:29:20.0744356 
curl -X GET \
  'https://api.allegro.pl/offers/listing?seller.id=#&searchMode=REGULAR&offset=0&limit=100&sort=relevance&fallback=True' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \

RESPONSE 2020-04-06 09:29:20.1681600 Duration: 93,7244ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "SERVICE_UNAVAILABLE",
        "Details": null,
        "Message": "Service unavailable.",
        "Path": null,
        "UserMessage": "Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (503) Server Unavailable.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "22ba57314a0c4810",
  "Error": true,
  "StatusCode": 503,
  "Message": "{\"errors\":[{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"Service unavailable.\",\"details\":null,\"path\":null,\"userMessage\":\"Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.\"}]}"
}
```

**Comment by PrzemyslawLukanowski** [comment]
Był to chwilowy problem po naszej stronie, powtórzenie żądania zakończy się prawidłową odpowiedzią. Nie odnotowaliśmy większej liczby błędów tego typu.

**Comment by meridPL** [comment]
Witam,

Widzę, że opisane jest, że problem ma się nie pokazywać niestety w niektórych sytuacja i nie zwsze wyświetla mi się taki błąd 

`
headers = {
    "Authorization": "Bearer " + access_token,
    "Accept": "application/vnd.allegro.public.v1+json",
}

list_province = [
    "DOLNOSLASKIE",
    "KUJAWSKO_POMORSKIE",
    "LUBELSKIE",
    "LUBUSKIE",
    "LODZKIE",
    "MALOPOLSKIE",
    "MAZOWIECKIE",
    "OPOLSKIE",
    "PODKARPACKIE",
    "PODLASKIE",
    "POMORSKIE",
    "SLASKIE",
    "SWIETOKRZYSKIE",
    "WARMINSKO_MAZURSKIE",
    "WIELKOPOLSKIE",
    "ZACHODNIOPOMORSKIE"
]

Pętla id i province 

req3 = requests.get("https://api.allegro.pl/offers/listing, headers=headers, params={
                    "category.id": 305601,
                    "phrase": "Lego " + str(self.id_lego),
                    "parameter.11323": "11323_1",
                    "sellingMode.format": "BUY_NOW",
                    "location.province": province,
                    "offset": offset,
                    "fallback": "false"
                })`

Jest to w pętli i nie zawsze występuje w tym samym id lego. Dodam tylko, że problem zaczął występować po dodaniu province.

**Comment by PrzemyslawLukanowski** [comment]
@meridPL Prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz, że dane dotyczą watku Github #3051. Przyjrzymy się bliżej opisanej przez Ciebie sytuacji.

**Comment by meridPL** [comment]
Napisałem nowy wątek. Niestety nie jestem w stanie wysłać konkretnego requestu, bo jest to losowe ;)

**Comment by PrzemyslawLukanowski** [comment]
@meridPL Jeżeli problem cały czas będzie się powtarzać, prześlij potrzebne dane. Twoje logi pozwolą nam dokładniej zweryfikować jego źródło.

**Comment by meridPL** [comment]
On się powtarza tylko ciężko go wychwycić.
