### ISSUE TITLE
Wysyłanie wiadomości

### ISSUE THREAD

**Issue by Mbif-dev** [allegro/allegro-api#3052]
Witam,
Wysyłam wiadomości na adresy w postaci dd7ihdg07n+49e8c6757@user.allegrogroup.pl i wiadomości wysłane zaraz po zamówieniu nie dochodzą, a te wysłane później dochodzą bez problemu. Czym może to być spowodowane?

**Comment by PrzemyslawLukanowski** [comment]
Skąd otrzymujesz adres mailowy w takiej postaci? Adresy zwracamy z końcówką ...@allegromail.pl.

**Comment by Mbif-dev** [comment]
Jest to adres pobrany przez RESTapi z adresu order/events środowiska testowego. zamówienia są pobierane co minute.

**Comment by PrzemyslawLukanowski** [comment]
Odtworzyłem opisany przez Ciebie scenariusz i nie udało mi się powtórzyć tego błędu, otrzymałem wiadomość, którą wysłałem od razu po złożeniu zamówienia. Czy problem występuje również na produkcji? Czy dzieje się tak z każdym wysłanym mailem, który wysyłasz od razu po zakupie kupującego? Sprawdź także folder Spam, być może wiadomości utknęły właśnie tam.

**Comment by Mbif-dev** [comment]
Problem cały czas występuje. Na produkcji jeszcze tego skryptu nie testowałem.  Wiadomości nie dochodzą na różne poczty i również niema ich w spamie. Nie dostaje również żadnych zwrotek o braku możliwości wysłania wiadomości. Czas po złożenia zamówienia też niema znaczenia gdyż opóźniłem wysyłanie wiadomości nawet do 15 minut. Bywa czasem że  nawet kilka wysłanych wiadomości nie dochodzi

**Comment by Mbif-dev** [comment]
A tu mam kawałek loga od administratora świadczący o tym że blokada jest po waszej stronie:
`2020-04-07 18:38:56 1jLrFY-0061dF-DJ == wgs7mxcd3e+476f572e4@user.allegrogroup.pl R=lookuphost T=remote_smtp defer (-44) H=mail1-test.user.allegrogroup.pl [178.21.155.30]: SMTP error from remote mail server after RCPT TO:<wgs7mxcd3e+476f572e4@user.allegrogroup.pl>: 450 4.2.0 <wgs7mxcd3e+476f572e4@user.allegrogroup.pl>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/user.allegrogroup.pl.html`

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z komunikatem w logach, serwer nadawczy wpadł do nas na graylistę. Jest to standardowy mechanizm większości serwerów pocztowych.
Więcej informacji możesz zobaczyć [tutaj.](http://postgrey.schweikert.ch/help/user.allegrogroup.pl.html)
Mail na początku jest odbijany, a przy kolejnych ponowieniach już jest odbierany przez nas i przesyłany dalej.
Wiadomości wysłane na ten zahashowany adres z logów zostały przez nas poprawnie dostarczone.

**Comment by Mbif-dev** [comment]
No właśnie nie zostały wysłałem 5 wiadomości w czasie 18:38 a 18:40 a doszła dopiero 5 wiadomość. Co powoduje że mail trafia na tą listę? Może wiadomości powinny być wysyłane z odpowiednimi nagłówkami aby tego uniknąć lub w odpowiednim formacie?

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobnie przyczyną może być konfiguracja po Twojej stronie. Zwróć uwagę na FAQ z wcześniejszego linka:

> If you see this error message while sending a mail, it probably means that you did something wrong: the configured mail server should trust your machine and thus not apply greylisting at all.  Make sure that you did turn on encryption and authentication for the SMTP server in your mail client. Ask your system administrator if you are not sure about how to configure it.  See this page for a description about how Greylisting works.

**Comment by Mbif-dev** [comment]
Na razie zmieniłem typ wiadomości z html na tekstowy i działa, ale to nie rozwiązuje całkiem problemu. Ponadto w tym linku co wysłałeś jest informacja że wiadomość powinna być opóźniona w dostarczeniu a nie nie dojść do nadawcy. A część wiadomość wcale nie dochodzi i to zarówno tych wysłanych przez skrypt jak i bezpośrednio z programu pocztowego. Pozatym nigdy niemiał problemów z tym aby moje wiadomości niedochodziły do nadawcy.

> it relies on Mail Servers behaving according to the standards and usually doesn't require any action by the user. Your mails should only possibly be delayed.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę, która wiadomość (message-id) wysłana przez Twój serwer, a odebrana przez nasz nie dotarła.

**Comment by Mbif-dev** [comment]
Tu masz 4 pierwsze które nie doszły:
Message-ID: <5049b6d5-b9e5-1d24-8c3e-333ff8a24390@mbif.pl>
Message-ID: <f2d07749-bece-f93e-e35b-a9b6f0493bab@mbif.pl>
Message-ID: <ca67de28-d4de-a8fd-a9db-acbced3fd2d0@mbif.pl>
Message-ID: <02c5d168-f882-fd76-10bf-9dcde296c789@mbif.pl>
A tu 5 która już doszła:
Message-ID: <b29e93ad-1971-4fdd-febd-6b5fbbbe49cd@mbif.pl>

**Comment by PrzemyslawLukanowski** [comment]
Te 5 maili wysłałeś między 18:38-18:40. Mechanizm greylistingu potrafi mieć opóźnienia rzędu kilku minut i jego główne założenie polega na tym, że MTA nadawcy będzie ponawiał wysyłkę wiadomości. Całą istotą tego mechanizmu jest założenie, że potencjalny spamer korzystający ze skryptu wykonuje dużą liczbę pojedynczych prób wysyłki wiadomości i znika z sieci - godny zaufania serwer nadawcy posiada kolejkę wiadomości i w przypadku błędu ponowi ich wysyłkę.
W tym przypadku wygląda to tak jakbyś podjął pojedynczą próbę dostarczenia różnych wiadomości skryptem i spodziewał się, że w końcu dotrą, bo w podlinkowanym komunikacie jest mowa o opóźnieniach - tyle że on jest dla użytkownika końcowego, który zaobserwuje opóźnienie wynikające z ponowień, a nie twórcy skryptu nadającego maile.
