### ISSUE TITLE
Brak możliwości uzupełnienia masowo parametrów

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#3053]
Dzień dobry,

Zgodnie z artykułem:
https://allegro.pl/dla-sprzedajacych/przesuwamy-termin-wprowadzenia-obowiazkowych-parametrow-uniwersalnych-lD9BKaw9rCg - zmienili Państwo wymagalność wielu parametrów w różnych kategoriach.

Dlaczego w/w zmiana nie jest również dokonana w nowej zakładce "uzupełnij parametry" -> https://allegro.pl/moje-allegro/sprzedaz/uzupelnij-parametry pomimo tego, że takich aukcji mam mnóstwo?
Mam tam tylko informację "_Nie masz ofert w kategoriach, w których są do uzupełnienia parametry obowiązkowe._" - co jest nieprawdą.

Jak klienci mają zaktualizować parametry z xls'a na istniejących aukcjach, skoro nawet bezpośrednio na Allegro w panelu nie mogą tego zrobić?

Ręczna zmiana na 100 000 aukcjach i różnych kontach jest niemalże niewykonalna w sensownym czasie.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - zakładka działa prawidłowo. Czy w Twoim przypadku problem dalej występuje? Jeśli tak, podaj proszę nazwę/id konta. Możesz to zrobić tutaj lub przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - wtedy dopisz w zgłoszeniu GitHub #3053.

**Comment by PrzemyslawLukanowski** [comment]
Update - Zakładka "uzupełnij parametry" jest cały czas nasycana ofertami, pracujemy nad rozwiązaniem problemu. Twoje oferty również wkrótce się tam pojawią.

**Comment by PrzemyslawLukanowski** [comment]
Problem został rozwiązany wczoraj około 17:00, sprzedawcy powinni być już w stanie uzupełniać parametry.

**Comment by vitapak** [comment]
Tak, mają państwo rację - już jest w porządku.

--
Jeszcze jedna kwestia - podobny temat jest od dłuższego czasu z zakładką: **Powiąż oferty z produktami**

Na moim koncie często podczas edycji (różnych ofert) wyskakuje okienko powiązania oferty z produktem, natomiast w rzeczonej zakładce ZAWSZE jest 0 ofert do powiązania. 

Ta zakładka nie działa, czy musi być spełniony jakiś konkretny warunek?

**Comment by PrzemyslawLukanowski** [comment]
Zakładka "Powiąż ofertę z produktami" działa prawidłowo - okienko podczas edycji nie jest równoznaczne z tym, że ten sam produkt pojawi się w zakładce. Okienko pojawia się w przypadku, kiedy parametry identyfikujące produkt zgadzają się w 100%, ale są różnice w innych parametrach. Natomiast w zakładce "Powiąż ofertę z produktami" wyświetlamy sugestie, czyli nie wszystkie (ale większość) parametrów identyfikących ofertę z produktem jest zgodna.

**Comment by vitapak** [comment]
Rozumiem, wszystko jasne ws. powiązania produktów.

--

Panie Przemysławie, 
Wracając do parametrów - 2 sprawy:

1) Czy aukcje nadal "spływają" do zakładki "Uzupełnij parametry"?

Wczoraj uzupełniłem wszelkie parametry, które miałem w tamtej przestrzeni. Aktualnie widzę "_Nie masz ofert w kategoriach, w których są do uzupełnienia parametry obowiązkowe_."

Natomiast podczas aktualizacji cen/ilości po API już widzę min 3 aukcje, z którymi jest problem na tym koncie.

2) Zauważyłem, że do w/w zakładki wpadają TYLKO aktywne oferty. 

Skoro mogę wznowić ofertę z poziomu allegro, czy też jest ona widoczna na liście jako zamknięta  - to dlaczego nie mogę zaktualizować wszystkich wymaganych parametrów dla ofert zakończonych (_przed przeniesieniem do archiwum_) w zakładce w tej zakładce?

**Comment by PrzemyslawLukanowski** [comment]
1. Czy może Pan podać przykładowe numery ofert? Będziemy ich potrzebować, aby móc zweryfikować problem.
2. Tak, do zakładki trafiają tylko aktywne oferty, wynika to z ograniczeń działania tego mechanizmu.
