### ISSUE TITLE
brak możliwości zakończenia oferty

### ISSUE THREAD

**Issue by kudel** [allegro/allegro-api#3054]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

REQUEST:
Array
(
    [url] => https://api.allegro.pl/sale/offer-publication-commands/5f196045-1747-4c45-b13f-c4c8b4759c73
    [method] => PUT
    [data] => Array
        (
            [offerCriteria] => Array
                (
                    [0] => Array
                        (
                            [offers] => Array
                                (
                                    [0] => Array
                                        (
                                            [id] => 7663333337
                                        )
                                )
                            [type] => CONTAINS_OFFERS
                        )
                )
            [publication] => Array
                (
                    [action] => END
                )
        )
)
RESPONSE:
{"id":"5f196045-1747-4c45-b13f-c4c8b4759c73","taskCount":{"total":0,"success":0,"failed":0}}
stdClass Object
(
    [id] => 5f196045-1747-4c45-b13f-c4c8b4759c73
    [taskCount] => stdClass Object
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )
)
curl_getinfo:
Array
(
    [url] => https://api.allegro.pl/sale/offer-publication-commands/5f196045-1747-4c45-b13f-c4c8b4759c73
    [content_type] => application/vnd.allegro.public.v1+json;charset=UTF-8
    [http_code] => 201
    [header_size] => 409
    [request_size] => 978
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.137849
    [namelookup_time] => 0.012327
    [connect_time] => 0.032476
    [pretransfer_time] => 0.074961
    [size_upload] => 108
    [size_download] => 92
    [speed_download] => 667
    [speed_upload] => 783
    [download_content_length] => 92
    [upload_content_length] => 108
    [starttransfer_time] => 0.137829
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 185.31.27.150
    [certinfo] => Array
        (
        )
    [primary_port] => 443
    [local_ip] => 46.29.17.228
    [local_port] => 51639
)

Od wczoraj obserwuję brak możliwości zakończenia oferty przez REST API, wszystkie dane (request, response, curl info powyżej)

**Comment by kudel** [comment]
Witam.

Oferty zakończyły się 10:08.
Czy to obsuwa REST API, czy Państwa ręczna interwencja?

**Comment by PrzemyslawLukanowski** [comment]
Nie było tutaj interwencji z naszej strony. Według naszych logów pierwszy request dot. zakończenia tej oferty miał miejsce dzisiaj o 9:17. Przetwarzanie zadania może potrwać do godziny.
