### ISSUE TITLE
Opóźnienia w publikacji ofert po API

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#3055]
Dzień dobry,

czy pusty json zwrócony z żądania zwracającego status publikacji zadania oznacza opóźnienie w publikacji?
Przykładowy id zadania: 999e4b39b96e4a16811d3e11d3660548

**Comment by kamilkozak** [comment]
U mnie ta sama sytuacja.

**Comment by Radeq** [comment]
U mnie również problemy z wystawieniem od około 10:00

cb22041e-ab47-4059-baf5-10bd1a06fce9

**Comment by PrzemyslawLukanowski** [comment]
W podanych przez Was godzinach wystąpiły opóźnienia aktywacji ofert, dlatego w odpowiedzi mógł zostać zwrócony pusty json.
