### ISSUE TITLE
Uzupełnienie pola SYGNATURA w wystawiony ofertach przez API

### ISSUE THREAD

**Issue by d-n-e** [allegro/allegro-api#3056]
Czy istnieje możliwość uzupełnienia opcjonalnego pola SYGNATURA  w wystawiony już ofertach przez API? 
Jeśli tak to proszę o wskazówki pozwalające na dokładne wyspecyfikowanie takiej funkcjonalności.

**Comment by SebastianOzdoba** [comment]
@d-n-e 
używasz metody API: PUT /sale/offers/{offerId}

**Comment by PrzemyslawLukanowski** [comment]
@d-n-e Jak powyżej. Najpierw pobierz ofertę za pomocą [GET /sale/offer/{id}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), a następnie prześlij całą otrzymaną strukturę, wraz z wyedytowanym polem external.id, przez [PUT /sale/offers/{id}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

**Comment by d-n-e** [comment]
Super. Dziękuję za informacje.
