### ISSUE TITLE
Drzewo kategorii sale/categories

### ISSUE THREAD

**Issue by DanielMiara** [allegro/allegro-api#3058]
Czy jest jakiś zasób pozwalający na pobranie drzewa kategorii czy trzeba stopniowo się zagłębiać?
Jeśli nie to trochę to niewygodne i dziwnie się, że pisząc API nikt tego nie przewidział. 
Przydało by się szukanie po nazwie i zwrotnie ID kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości, musisz stopniowo się zagłębiać za pomocą [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET). W wątku #2211 jeden z użytkowników forum udostępnił plik z kategoriami, być może będzie to dla Ciebie pomocne.
