### ISSUE TITLE
Get suggested categories

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#3059]
On the Allegro webpage, when adding a new item, putting the title into the title box gives a list of suggested categories to list the item under.

Is there any way to get this recommended list using the API?

**Comment by PrzemyslawLukanowski** [comment]
No, you can't retrieve this list via API, we return this data only on our website.

**Comment by pkrzemo** [comment]
@jguthriedodax Check this...
Method GET:
 url = "https://allegro.pl/suggestions/?phrase={REPLACE_YOUR_TITLE_TEXT_HERE}&country=pl&highlights=b&sortByElementType=false"
