### ISSUE TITLE
[Błąd] Edycja istniejącej oferty - czas trwania oferty

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#306]
Witam,
Ostatnie aktualizacje robiłem 3 dni temu i działało.
Dziś podczas edycji istniejącej oferty i przekazaniu FID[4]=99 dostaję
{#5432 ▼
  +"status": "error"
  +"error_code": "ERR_INVALID_DURATION_TIME"
  +"error_message": "Niepoprawna wartość w polu określającym czas trwania aukcji."
}

**Comment by MartaNowaczyk** [comment]
Witam,
sprawdziłam edycję oferty z FID[4]=99 i nie dostaję takiego błędu. Napisz co zmieniasz i prześlij XMLe z requestem i responsem dotyczące opisanego problemu. Możesz je wysłać [przez formularz kontaktowy](https://allegro.pl/pomoc/kontakt?appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=1436f902-6fd9-420f-9e19-321b684cc8df). W treści wpisz, że podsyłasz pliki do weryfikacji zgłoszenia na GitHubie. Później wklej tu numer ticketa.

**Comment by kfijalko** [comment]
@MartaNowaczyk masz rację, teraz działa bez zarzutu, zaktualizowałem już 17k aukcji i bez problemu.
do zamknięcia

**Comment by kfijalko** [comment]
@MartaNowaczyk jednak muszę otworzyć.
tak jak pisałem wczoraj poszło 17k aktualizacji a dziś mam znowu:
{#9960 ▼
  +"status": "error"
  +"error_code": "ERR_INVALID_DURATION_TIME"
  +"error_message": "Niepoprawna wartość w polu określającym czas trwania aukcji."
}
postaram się zrzucić req i res.
może to kwestia na który serwer trafię, albo coś miszacie/wdrażacie, albo komunikat jest nieadekwatny ...

**Comment by kfijalko** [comment]
@MartaNowaczyk 
https://allegro.pl/pomoc/kontakt?appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=1436f902-6fd9-420f-9e19-321b684cc8df
nie wiem, który to numer ticketa

**Comment by kfijalko** [comment]
fid z czasem trwania z requesta:
<ns1:item>
<ns1:fid>4</ns1:fid>
<ns1:fvalueString></ns1:fvalueString>
<ns1:fvalueInt>99</ns1:fvalueInt>
<ns1:fvalueFloat>0</ns1:fvalueFloat>
<ns1:fvalueImage>MA==</ns1:fvalueImage>
<ns1:fvalueDatetime>0</ns1:fvalueDatetime>
<ns1:fvalueDate></ns1:fvalueDate>
<ns1:fvalueRangeInt><ns1:fvalueRangeIntMin>0</ns1:fvalueRangeIntMin><ns1:fvalueRangeIntMax>0</ns1:fvalueRangeIntMax></ns1:fvalueRangeInt>
<ns1:fvalueRangeFloat><ns1:fvalueRangeFloatMin>0</ns1:fvalueRangeFloatMin><ns1:fvalueRangeFloatMax>0</ns1:fvalueRangeFloatMax></ns1:fvalueRangeFloat>
<ns1:fvalueRangeDate><ns1:fvalueRangeDateMin></ns1:fvalueRangeDateMin><ns1:fvalueRangeDateMax></ns1:fvalueRangeDateMax></ns1:fvalueRangeDate>
</ns1:item>

**Comment by kfijalko** [comment]
Zrobiłem "obejście":
1) wysyłam typ oferty fid[29]=0, do tej pory było fid[29]=1 "sklepowa"
2) czas trwania bez zmian fid[4]=99
teraz działa.

**Comment by MartaNowaczyk** [comment]
@kfijalko Zgodnie z [newsem](https://github.com/allegro/allegro-api/issues/299) i zmianami jakie wprowadziliśmy nie powinno być problemu z wystawieniem ofert, które były wystawione w formacie sklep. Docelowa wartość fidu 29 po zmianach to 0. Przeanalizujemy jeszcze tę sytuację. 
Dzięki za zgłoszenie.

**Comment by MartaNowaczyk** [comment]
@kfijalko Podeślij, jeśli masz możliwość, pełnego requesta i responsea (z występującym błędem, bez wrażliwych danych), abyśmy mogli przeanalizować tę sytuację.

**Comment by kfijalko** [comment]
Zaraz zaczynam urlop, będę dostępny za 2 tygodnie.
Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Udanego urlopu. Pozdrawiam.

**Comment by kfijalko** [comment]
Wróciłem i mam niespodziankę. Jeszcze nic nie zmeniłem i teraz dostaję:
{#1325 ▼
  +"status": "error"
  +"error_code": "ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM"
  +"error_message": "Nie można zmienić typu aukcji dla aukcji sklepowej"
}

**Comment by kfijalko** [comment]
Zmieniłem FID[29]=1 i działa. "Ktoś" tam cały czas miesza.

**Comment by kfijalko** [comment]
Minęło 3 godziny i nie działa.
Mam:
{#4593 ▼
  +"status": "error"
  +"error_code": "ERR_INVALID_DURATION_TIME"
  +"error_message": "Niepoprawna wartość w polu określającym czas trwania aukcji."
}

**Comment by kfijalko** [comment]
Zmieniłem FID[29]=0 i działa.

**Comment by kfijalko** [comment]
Cały czas trafiam na inne walidacje i komunikaty o błędach - zgodnie z powyzszym.
Mam dwa podejrzenia:
1) niestabilne oprogramowanie - np. różne wersje oprogramowania na serwerach i efekt zależy gdzie trafię z wykonaniem
2) po "likwidacji ofert sklepowych" część moich ofert jest już "zwykła" a część nadal "sklepowa" - podlegają różnym regułom walidacyjnym.
Pkt 2 to mój faworyt.
Jakiś programers powinien zernąć na te reguły.
Ostatnio mogłem zaktualizować do 20k dziennie - wczoraj 500 sztuk.
Poprawcie coś.

**Comment by kfijalko** [comment]
Piszę sam do siebie :)
Pkt 2 już nie jest moim faworytem.
Własnie przeszło mi 3k aktualizacji bez żadnego błędu.

**Comment by KrzysztofLukanowski** [comment]
Cześć,

jeżeli problem nadal występuje, podeślij proszę request o response w xml.

**Comment by kfijalko** [comment]
Wyrobiłem się z aktualizacją do końca "połowy roku". Teraz nie planuję dużych aktualizacji. Oczywiście jak się coś pojawi do zgłoszę.
