### ISSUE TITLE
  Wystawiana liczba nie może być mniejsza niż 1.

### ISSUE THREAD

**Issue by deneb-k** [allegro/allegro-api#3060]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry. Wysyłam tak:
```
    [stock] => stdClass Object
        (
            [available] => 3
            [unit] => UNIT
        )
```
Dostaję tak:

`{"errors":[{"code":"VALIDATION_ERROR","message":"Wystawiana liczba nie może być mniejsza niż 1.","details":"","path":"","userMessage":"Wystawiana liczba nie może być mniejsza niż 1."}]}
`

A trace-id mam taki: b61d4ac0b58af8c3

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - przekazuję problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@deneb-k Problem został rozwiązany.

**Comment by deneb-k** [comment]
Niestety tylko doraźnie. Ta jedna oferta przeszła edycję, ale mam jeszcze na tym samym koncie pięć innych aktualnych przykładów. Podeślę formularzem.

**Comment by PrzemyslawLukanowski** [comment]
Ok, poinformuję w tym wątku po rozwiązaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@deneb-k  Podane oferty również zostały poprawione.
