### ISSUE TITLE
Wasz przyklad otrzymania tokenu po prostu nie dziala

### ISSUE THREAD

**Issue by gosforth** [allegro/allegro-api#3062]
Macie błędy w skrypcie na stronie:
https://developer.allegro.pl/getting_started/#jak-uzyska%C4%87-token-dost%C4%99powy-do-api
`Parse error: syntax error, unexpected ':', expecting '{' in api_allegro.php on line 3`

Poprawiajac to do poprawnego kodu ciagle jest bład:

`access_token = Something went wrong`

To API po prostu nie funkcjonuje.

Swoja droga po co komplikowac dostep do tego API uzywajac jakichs tokenow - to nie daje zadnego ekstra bezpieczenstwa. Najwieksze firmy swiata uzywaja po prostu kluczy i hasel (np Google).

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj użyć nowszej wersji PHP.

> "Przykłady kodu przygotowaliśmy w czystym PHP 7, bez użycia żadnych dodatkowych frameworków czy bibliotek. Dzięki temu będą zrozumiałe dla osób, które nie korzystają na co dzień z tego języka. Jeżeli chcesz korzystać z kodu, który tutaj udostępniamy zainstaluj interpreter PHP."

Czy podmieniłeś odpowiednio wartości $clientId i $clientSecret?
