### ISSUE TITLE
Długość pola access_token w autoryzacji

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#3063]
Jaka jest maksymalna długość access_token i refresh_token? W ostatnim czasie dla nowych kont urosła ona dwukrotnie co spowodowało problemy z autoryzacją.

**Comment by SebastianOzdoba** [comment]
@riepa niehardkoduj długości na stałe, było już wcześniej że długości tokenów się zmieniają
Jak używasz zapisu w bazach realacyjnych to najlepiej varchar(max) :) 
Nic Cię nie zaskoczy wtedy

**Comment by PrzemyslawLukanowski** [comment]
@riepa Zwracane przez nas tokeny nie mają na tę chwilę ustalonej długości.
