### ISSUE TITLE
Seller details in REST API

### ISSUE THREAD

**Issue by kislukacs** [allegro/allegro-api#3064]
Hi,

until the end of March you had in WebAPI method DoShowUser, now it is deprecated. How can I get sellers information (username, registration date, email, phone, etc.) from REST API?
I tried [getListOfContactsUsingGET](https://developer.allegro.pl/documentation/#operation/getListOfContactsUsingGET) method but I got an ACCESS_DENIED error.

**Comment by PrzemyslawLukanowski** [comment]
You can check basic information about authenticated user via [GET /me](https://developer.allegro.pl/documentation/#operation/meGET). In REST API we don't provide data such as username, registration date, etc. for selected user.

**Comment by kislukacs** [comment]
That means through the newer REST API I can not access data, what was possible with WebAPI?

**Comment by PrzemyslawLukanowski** [comment]
That's right, we don't provide data you mentioned. In REST API we focus on functionalities for the sellers.
