### ISSUE TITLE
Publishing with new empty required fields/parameters

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#3065]
Hi,

What errors do I get when trying to publish an offer via with the API (https://developer.allegro.pl/en/documentation/#operation/changePublicationStatusUsingPUT using this resource) when new obligatory fields/parameters like number of lumens in lamps are created and they are empty?

Thank you

**Comment by PrzemyslawLukanowski** [comment]
Via [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/en/documentation/#operation/getPublicationTasksUsingGET) you can check the current status of your task. 

Sample response with information about missing required parameter (status 200):

```
{
    "tasks": [
        {
            "offer": {
                "id": "{offerId}"
            },
            "message": "Could not change offer publication status. Missing required parameters: {parameterName}",
            "status": "FAIL",
            "scheduledAt": "2020-04-08T13:17:46.039Z",
            "finishedAt": "2020-04-08T13:17:46.338Z",
            "field": "publication",
            "errors": [
                {
                    "code": "ConstraintViolationException.HasAllRequiredAttributes",
                    "message": "Missing required parameters: {parameterName}.",
                    "details": null,
                    "path": "attributes",
                    "userMessage": "Missing required parameters: {parameterName}"
                }
            ]
        }
    ]
}
```

**Comment by frenci8** [comment]
Hi, thank you for the reply. What status code should be returned from 

> https://api.{environment}/sale/offer-publication-commands/{commandId}

so 

> https://api.{environment}/sale/offer-publication-commands/{commandId}/tasks

returns the example you gave with the error message "Missing required parameters"? 

Thank you

**Comment by PrzemyslawLukanowski** [comment]
For PUT method status code will be 201 with body:

```
{
    "id": "{commandId}",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}
```

and for GET method it will be 200 with body:

```
{
    "id": "{commandId}",
    "taskCount": {
        "total": 1,
        "success": 0,
        "failed": 1
    }
}
```

**Comment by frenci8** [comment]
Hi, 

The 200 response for the get request `sale/offer-publication-commands/{commandId}/tasks` does not contain `taskCount`. 

I am not sure we understood each other. 

My question is, when i send a PUT request to `/sale/offer-publication-commands/{commandId}`, which response should I get from the put request so when i send a GET request to `/sale/offer-publication-commands/{commandId}/tasks` I get the example that you sent in the first response about missing required parameters. 

Thank you.

**Comment by PrzemyslawLukanowski** [comment]
If you send PUT request to `/sale/offer-publication-commands/{commandId}` in response you will receive:

```
{
    "id": "{commandId}",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}
```

Because this request works asynchronously. 
If you want to retrieve detailed report for this request, like my example with missing required parameters above, you should use GET /`sale/offer-publication-commands/{commandId}/tasks`.

> The 200 response for the get request sale/offer-publication-commands/{commandId}/tasks does not contain taskCount.

Yes, you're right, this example:

```
and for GET method it will be 200 with body:

{
    "id": "{commandId}",
    "taskCount": {
        "total": 1,
        "success": 0,
        "failed": 1
    }
}
```

was about GET `sale/offer-publication-commands/{commandId}`, not `/sale/offer-publication-commands/{commandId}/tasks.`
