### ISSUE TITLE
[SANDBOX] znikają zdjęcia z aukcji

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#3066]
Występuje problem: 
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W każdej aukcji mam jedno zdjęcie główne. Jakiś czas temu zauważyłem że wszystkie zdjęcia mi poznikały. Zadałem sobie trud i dodałem je od nowa. Teraz widzę, że poznikały ponownie. Nie chce mi się już tego robić drugi raz. Please fix :)

**Comment by PrzemyslawLukanowski** [comment]
Jest to prawidłowe działanie - zdjęcia na sandboxie automatycznie usuwamy po 7 dniach.
