### ISSUE TITLE
pomijane rekordy w checkout-forms

### ISSUE THREAD

**Issue by mmgithubpl** [allegro/allegro-api#3067]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
odpytywanie zasobu https://api.allegro.pl/order/checkout-forms z parametrami
?status=READY_FOR_PROCESSING&lineItems.boughtAt.gte=2020-04-07T00%3A00%3A00.000Z&lineItems.boughtAt.lte=2020-04-07T23%3A59%3A59.000Z&limit=50&offset=0

zwraca rekordy z pominieciem wybranych / pomimo ze kliencie wypelnili formularz zakupowy i dokonczyli platnosci / przyklady ktorych brakuje w respondzie.

http://allegro.pl/myaccount/newpayments_payment_details.php?trans_id=1206164625
http://allegro.pl/myaccount/newpayments_payment_details.php?trans_id=1206143777
http://allegro.pl/myaccount/newpayments_payment_details.php?trans_id=1206133228

dlaczego tak sie dzieje?

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to -na tę chwilę prawidłowo zwracamy powyższe zamówienia. Czy problem w Twoim przypadku dalej występuję? Jeśli tak - prześlij proszę przykładowy request wraz z respone przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) z dopiskiem GitHub #3067.
