### ISSUE TITLE
Aktywacja konta testowego allegro

### ISSUE THREAD

**Issue by faran22** [allegro/allegro-api#3069]
Proszę o aktywacje konta testowego sandbox: se......usuniete@gmail.com

**Comment by PrzemyslawLukanowski** [comment]
Nie mamy takiego użytkownika w naszej bazie. Czy zarejestrowałeś konto przez ten [link](https://allegro.pl.allegrosandbox.pl/rejestracja?origin_url=%2F%3Flogout%3D1#/)?

**Comment by faran22** [comment]
Konto zostało zarejestrowane przez wskazany link, bardzo proszę o aktywacje. Wcześniej rejestrowałem z adresu znalezionego w google.

**Comment by PrzemyslawLukanowski** [comment]
@faran22 Aktywowałem Twoje konto.

**Comment by nebuso** [comment]
Witam 

Podpinam się, żeby nie śmiecić.

Prosiłbym o aktywację na https://allegro.pl.allegrosandbox.pl/
konta zał. na maila dawid.rzepczynski@gmail.com

Dzięki!

**Comment by MaciejFrackowiak** [comment]
@nebuso Konto aktywowałem!

**Comment by nebuso** [comment]
> @nebuso Konto aktywowałem!

Dzięki! 
Wszystko super działa.

Miłego dnia
Dawid

**Comment by root1911** [comment]
Witam, również podpinam się pod wątek.
Proszę o aktywacje konta w sandboxie, 
user: parkerrr
założono na maila p.....@protonmail.com

**Comment by PrzemyslawLukanowski** [comment]
@root1911 Aktywowałem Twoje konto.

**Comment by jbulek** [comment]
Witam, proszę o aktywacje konta testowego sandbox: 
LOGIN: www_autonorma_pl
Email: info@autonorma.pl
Dzięki!

**Comment by MaciejFrackowiak** [comment]
@jbulek Konto aktywowane, wybrałeś konto Firma - proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) w celu jego weryfikacji.

**Comment by likrot** [comment]
Witam, co powinienem zrobić, żeby móc dokonywać sprzedaży na Sandboxie? Cały czas wisi mi status o weryfikacji i nie wiem co powinienem wyklikać.
Dane wysłane w zgłoszeniu nr 09439602

**Comment by PrzemyslawLukanowski** [comment]
@likrot Aktywowałem Twoje konto.

**Comment by likrot** [comment]
Super, dzięki. Działa
