### ISSUE TITLE
Składanie zamówień w środowisku testowym

### ISSUE THREAD

**Issue by Mbif-dev** [allegro/allegro-api#3071]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od wczoraj podczas próby dokonania zakupu w środowisku testowym pokazuje się następujący komunikat "Przepraszamy wsytąpił nieoczekiwany błąd"
![obraz](https://user-images.githubusercontent.com/62496192/78877310-f1261a80-7a50-11ea-9e9b-e016b70c7215.png)

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - nie udało mi się powtórzyć tego błędu, prawidłowo przeszedłem proces zakupowy. Czy problem w Twoim przypadku dalej występuje? Jeśli tak - w którym dokładnie momencie? Czy tylko dla wybranej metody dostawy i płatności, czy wszystkich?

**Comment by Mbif-dev** [comment]
Nie już nie występuje

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za potwierdzenie.
