### ISSUE TITLE
Problem z filtrowaniem wyników po numerze katalogowym części

### ISSUE THREAD

**Issue by kwachu91** [allegro/allegro-api#3072]
Występuje problem: 
 - [x] z zasobem REST API

:beetle: **Opis**
Podczas wywoływania requesta pod adresem: "/offers/listing?category.id=251124&phrase=&seller.id=&searchMode=REGULAR&offset=0&limit=100&sort=-price&include=all&fallback=0&parameter.11323=11323_1&publication.status=ACTIVE&sellingMode.format=BUY_NOW&parameter.215858=2115010482" dostaje takie same wyniki jak podczas wykonania tego samego zapytania bez parametru "parameter.215858=2115010482". Ostatni parametr oznacza numer katalogowy części.

Podczas pobierania parametrów dla kategorii: 251124, url: '/sale/categories/251124/parameters'
dostaję w odpowiedzi jako jeden z możliwych parametrów: {
"id": "215858",
"name": "Numer katalogowy części",
"type": "string",
"required": false,
"unit": null,
"options": {
"variantsAllowed": false,
"variantsEqual": false,
"ambiguousValueId": null,
"dependsOnParameterId": null
},
"restrictions": {
"minLength": 1,
"maxLength": 25,
"allowedNumberOfValues": 1
}
},

Natomiast tak jak wyżej, kiedy dołączam go do uri podczas pobierania ofert, response się nie zmienia i dostaję te same wyniki.
Kod jest testowany na środowisku produkcyjnym,
Proszę o odpowiedź, czy problem występuje po Państwa stronie, czy może źle przekazuję ten parametr? W dokumentacji nie znalazłem więcej informacji.

Z góry dziękuję za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Parametry, które pobierasz za pomocą /sale/categories/251124/parameters nie są równoznaczne z filtrami, które możesz przekazać przez /offers/listing. Listę dostępnych filtrów znajdziesz na końcu odpowiedzi, nie ma tam parametru 215858. Odzwierciedla ona filtry dostępne po lewej stronie na naszej stronie.
![Screenshot_20](https://user-images.githubusercontent.com/51473661/78890903-c8a91b00-7a66-11ea-9295-9f70405e3d9a.png)

**Comment by kwachu91** [comment]
Dziękuję za odpowiedź. Mam jeszcze jedno pytanie w związku z powyższym. Czy w ogóle istnieje  opcja, żeby pobrać listę ofert(uwzględniając ten parametr) nie wykonując szczegółowego pytania o ofertę ? Albo otrzymać ten parametr w odpowiedzi(encjach) dotyczącej listingu ?

**Comment by PrzemyslawLukanowski** [comment]
Zasób jest odzwierciedleniem wyszukiwarki ze strony internetowej, dlatego też nie udostępniamy takiej funkcjonalności.
