### ISSUE TITLE
Pytanie dotyczace obiektu DeliverySettings w requescie "PUT /sale/offers/{offerId}"

### ISSUE THREAD

**Issue by stpdeveloping** [allegro/allegro-api#3073]
Prosilbym, zebyscie aktualizowali swoja dokumentacje i podawali kompletne requesty/response'y (tak trzeba sledzic i sie domyslac)... Chodzi mi o obiekt delivery settings w requescie json. Czy ma to wygladac tak:

> offer: {
> ...
> deliverySettings: {
> ...
> }
> }

czy moze tak:

> offer: {
> delivery: {
> deliverySettings: {
> }
> }
> }

**Comment by PrzemyslawLukanowski** [comment]
Dla ustawień dostawy mamy osobny zasób - [PUT /sale/delivery-settings](https://developer.allegro.pl/documentation/#operation/putSaleDeliverySettings), nie przekazujesz tego obiektu w PUT /sale/offers/{id}, ponieważ ustawienia dostawy przypisujesz do konta, nie do oferty. 

Przykładowa struktura:

```
{
    "freeDelivery": {
        "amount": 4.04,           
        "currency": "PLN"           
    },
    "joinPolicy": {
        "strategy": "MAX"       
    },
    "customCost": {
        "allowed": true 
   },
   "updatedAt": "2019-08-21T10:13:40.036Z"
}
```

**Comment by stpdeveloping** [comment]
> Dla ustawień dostawy mamy osobny zasób - [PUT /sale/delivery-settings](https://developer.allegro.pl/documentation/#operation/putSaleDeliverySettings), nie przekazujesz tego obiektu w PUT /sale/offers/{id}, ponieważ ustawienia dostawy przypisujesz do konta, nie do oferty.
> 
> Przykładowa struktura:
> 
> ```
> {
>     "freeDelivery": {
>         "amount": 4.04,           
>         "currency": "PLN"           
>     },
>     "joinPolicy": {
>         "strategy": "MAX"       
>     },
>     "customCost": {
>         "allowed": true 
>    },
>    "updatedAt": "2019-08-21T10:13:40.036Z"
> }
> ```

Okej, tylko ze w dokumentacji widnieje to jako "niezbedne dane" do wystawienia oferty z odnosnikiem do GET (pobrania DeliverySettings). Skoro nie jest to zalaczane do oferty, po co odsylanie do GET?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za to spostrzeżenie, przenalizujemy temat poprawy tych informacji w poradniku.
