### ISSUE TITLE
Błąd UserRepresentativeException podczas pobierania informacji o ofercie

### ISSUE THREAD

**Issue by KarsenMarcin** [allegro/allegro-api#3074]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

request: https://api.allegro.pl/sale/offers/8745909645
response: {"errors":[{"code":"UserRepresentativeException","message":"An error has occurred","details":null,"path":null,"userMessage":"There was an error while trying to get related account's resources."}]}

Dzień dobry 
Podczas pobierania informacji o ofercie metodą /sale/offers/{offerId} system zwraca błąd jak powyżej. Serwis wywołujący tą operację odwołuje się do środowiska produkcyjnego Allegro. Działa już długi czas. Błąd pojawił się wczoraj (8 kwietnia) ok. godz. 17:30.

**Comment by KarsenMarcin** [comment]
Błąd się pojawia gdy zapytanie wysyła się razem z tokenem autoryzacyjnym, bez niego zapytanie zwraca poprawną odpowiedź. A dokumentacja mówi inaczej: https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się rozwiązać problem. Sprostuję jednak, w dokumentacji widnieje prawidłowa informacja - bearer-token-for-user, czyli token otrzymany drogą code lub device flow. Błąd otrzymałeś ze względu na autoryzację typu client_credentials - czyli bearer-token-for-application.
