### ISSUE TITLE
Get sales data for the last 12 months

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#3075]
Hi,

Is it possible to get the sales data for offers for the last 12 months? Either the quantity or the total amount in currency is fine.

I was checking the API, but the documentation only offers for the last 30 days.

Thank you

**Comment by PrzemyslawLukanowski** [comment]
You can check total amount via GET [/payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) using query parameters:
 - group=INCOME,
 - occurredAt.gte and occurredAt.lte,

but you will need to sum up value.amount from each income. More information about this resource you can find in [our guide](https://developer.allegro.pl/en/charges/#1).

**Comment by frenci8** [comment]
Thank you for the reply. I would like to know the sales for each offer for the last 12 months, not for all the whole account for the last 12 months. Is that possible?

**Comment by PrzemyslawLukanowski** [comment]
It's impossible, you can use only parameters mentioned in the documentation.
