### ISSUE TITLE
Cannot convert access token to JSON

### ISSUE THREAD

**Issue by jandrejczuk** [allegro/allegro-api#3077]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,
Aplikacja którą się zajmuje komunikuje się z allegro api i błąd występuje na środowisku produkcyjnym, tj. 'Cannot convert access token to JSON'
Proszę o sprawdzenie co jest przyczyną. W aplikacji nie mieliśmy żadnych zmian tylko z dnia na dzień zaczęliśmy dostawać błędy w logach tego rodzaju.
Wklejam przykład requestu/response'a z sandboxa:

**REQUEST:**

> curl -X GET 'https://api.allegro.pl.allegrosandbox.pl/sale/offers?status=READY_FOR_PROCESSING&offset=0&limit=25' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Authorization: Bearer ...'

**RESPONSE:**
> {
>    "error": "invalid_token",
>    "error_description": "Cannot convert access token to JSON"
> }

Z tego co wyszukałem w dokumentacji i w zgłoszeniach to błąd leci gdy coś jest nie tak z tokenem. Proszę o wskazówkę co jest przyczyną błędu. 
Token wysłałem z formularza kontaktowego.

**Comment by PrzemyslawLukanowski** [comment]
Token z końcówką ....jXw4w, który początkowo tutaj uwzględniłeś jest nieaktualny, stracił ważność o 05:11. Dodatkowo upewnij się, czy korzystasz z właściwego tokena na właściwym środowisku. Wspominasz, że błąd występuje na produkcji, ale w żądaniu przekazujesz curl -X GET 'https://api.allegro.pl.allegrosandbox.pl/sale/offers...

**Comment by jandrejczuk** [comment]
Podałem dane z sandboxa żeby nie przeklejać tokenów produkcyjnych. Na sandboxie dostałem taki sam błąd (tj. Cannot convert... ). Jeśli token stracił ważność to czy nie powinienem dostawać błędu typu "error_description": "Access token expired:... ?"

**Comment by jandrejczuk** [comment]
Czy mogę formularzem kontaktowym wysłać request produkcyjny do sprawdzenia? Gdzie w tym formularzu daje się dopisek z numerem ticketa ? : )

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście, dopisz to po prostu to w treści zgłoszenia, np. "dane potrzebne do zgłoszenia Github #3077". Przeanalizuję to i wrócę z odpowiedziami.

**Comment by jandrejczuk** [comment]
Ok, podesłane w zgłoszeniu 09055726.

**Comment by PrzemyslawLukanowski** [comment]
Ważność Twojego tokena produkcyjnego zakończyła się wczoraj o 01:19:59. Wszystkie tokeny są zakodowane w technologii JWT. Możesz więc go zdekodować i w polu "exp" sprawdzić datę wygaśnięcia. Co do samego komunikatu - masz rację, powinniśmy zwrócić "Access token expired". Problem powstał niedawno, pracujemy już nad przywróceniem właściwego komunikatu.

**Comment by jandrejczuk** [comment]
Super, dzięki za pomoc.
