### ISSUE TITLE
Obsługa Centrum Wiadomości przez REST API

### ISSUE THREAD

**Issue by karolus888** [allegro/allegro-api#3078]
Bardzo przydatny byłby zasób do zarządzania wiadomościami w Centrum Wiadomości, podobnie jak dla Dyskusji.
Wystarczyłyby metody GET do pobierania wiadomości w wątku i POST do wysyłania wiadomości.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, zapisałem to jako sugestię dalszego rozwoju API.

**Comment by wolodzkom** [comment]
Czy coś się ruszyło w temacie. Znane są jakieś terminy?

**Comment by PrzemyslawLukanowski** [comment]
Planujemy udostępnić ten zasób w okolicach Q1 2021. Jest to jednak wstępny termin, który może ulec zmianie. O szczegółach będziemy informować w naszych komunikatach.

**Comment by pliszka** [comment]
Taktyczny Janek do obserwacji ISSUE- nam też sporo by to ułatwiło :+1:

**Comment by WlascicielAllegro** [comment]
ping

**Comment by PrzemyslawLukanowski** [comment]
@WlascicielAllegro Na tę chwilę nie możemy podać przybliżonego terminu, kiedy udostępnimy zasób.

**Comment by tomasz-grzesik** [comment]
@PrzemyslawLukanowski , czy termin udostępnienia dostępu do Centrum Wiadomości przez API jest już znany?

**Comment by PrzemyslawLukanowski** [comment]
@tomasz-grzesik Planujemy udostępnić zasoby jeszcze w czerwcu lub w lipcu.

**Comment by tomasz-grzesik** [comment]
> 
> 
> @tomasz-grzesik Planujemy udostępnić zasoby jeszcze w czerwcu lub w lipcu.

a czy udostępniono już niektórym developerom dostęp do Cwentrum Wiadomości poprzez API do testów?
Niektórzy oferują już gotowe narzędzia, które niby bazują na Centrum Wiadomości - więc podejrzewam, że mają wcześniejszy dostęp do API Centrum Wiadomości.
Jeśli tak jest, prosze o informację jak dołączyć do testerów.

**Comment by PrzemyslawLukanowski** [comment]
Nie dawaliśmy wcześniejszego dostępu innym integratorom, zasoby nie są jeszcze w pełni gotowe. Prawdopodobnie korzystają z innych rozwiązań.

**Comment by tomasz-grzesik** [comment]
Dziękuję za szybką odpowiedź.
To dobrze, bo w przeciwnym wypadku nie wyglądało by to transparentnie.

**Comment by tomasz-grzesik** [comment]
Wyjaśnione. Wspomniany developer wymaga podania hasła do konta Allegro, więc z pewnością nie działa to po API i jest niezgodne z Regulaminem Allegro.
