### ISSUE TITLE
Brak możliwości generacji tokena przez localhost

### ISSUE THREAD

**Issue by sinfulsaint07** [allegro/allegro-api#3079]
Cześć,
Dopiero zaczynam z RestApi i już na pierwszym kroku napotykam problem. Przy próbie generacji tokena przy użyciu kodu PHP z waszej strony https://developer.allegro.pl/getting_started/
wpisaniu swojego ClientID oraz ClientSecret w odpowiednie miejsca dostaję komunikat: "access_token = Something went wrong". Problem ten występuje jedynie przy próbie odpalenia kodu PHP na localhost. Po wrzuceniu kodu na serwer Token generuje i wyświetla się prawidłowo. Co może być przyczyną?

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że dane dla clientID i clientSecret podałeś ze środowiska testowego i korzystasz z php7. Jeżeli problem dalej będzie występować, dodaj `curl_setopt($ch, CURLOPT_VERBOSE, true);` i prześlij nam komunikat.

**Comment by sinfulsaint07** [comment]
[Tue Apr 14 19:33:30 2020] PHP 7.4.4 Development Server (http://localhost:8000) started
[Tue Apr 14 19:33:32 2020] [::1]:56696 Accepted
[Tue Apr 14 19:33:32 2020] [::1]:56697 Accepted
*   Trying 5.134.211.92:443...
* TCP_NODELAY set
* Connected to allegro.pl.allegrosandbox.pl (5.134.211.92) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
[Tue Apr 14 19:33:32 2020] [::1]:56696 [200]: GET /
[Tue Apr 14 19:33:32 2020] [::1]:56696 Closing

**Comment by PrzemyslawLukanowski** [comment]
Nie jest to problem związany z naszym API, jego wytłumaczenie i propozycję dwóch rozwiązań znajdziesz [pod tym linkiem](https://thisinterestsme.com/php-curl-ssl-certificate-error/).

**Comment by wwwfactory** [comment]
Wszystko działa poprawnie na php od wersji 5.4 w górę - jak jest niżej to nie powiem bo nie mam jak tego sprawdzić. Działa na linuxie i na windowsie. Na lokalhostach i innych "hostach"...
Jak napisał Pan Przemek - nie problem w Allegro.

curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_URL, $endpoint);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

zazwyczaj w windowsie problem jest w pierwszej linii...... :)

www factory

**Comment by sinfulsaint07** [comment]
> Nie jest to problem związany z naszym API, jego wytłumaczenie i propozycję dwóch rozwiązań znajdziesz [pod tym linkiem](https://thisinterestsme.com/php-curl-ssl-certificate-error/).

Dziękuję, zadziałało
