### ISSUE TITLE
Uwagi odnośnie REST api

### ISSUE THREAD

**Issue by ircykk** [allegro/allegro-api#308]
Przyglądając się nico dokładniej nowemu api mam kilka uwag, mam nadzieje że okażą się pomocne.

1. Unifikacja nazewnictwa parametrów, jeśli parametr odnosi się do tego samego to lepiej aby w każdym endpoincie miał taką samą nazwę a nie np. raz `user.id`,` seller.id` etc.
2. J/w nazwy zmiennych, raz mamy `parent.id` a raz `categoryId`.
3. Błędy - `/sale/user-ratings` przy złym `user.id` zwraca puste body i kod `403` ale już `/sale/size-tables` zawraca błąd w body requesta. Warto by ujednolicić żeby łatwiej było obsługiwać błędy.

**Comment by MaciejPotepa** [comment]
Wielkie dzięki za konstruktywne uwagi, cenny feedback. Przekażę je do odpowiednich zespołów.
