### ISSUE TITLE
/order/checkout-forms brak linku do obrazka kupionego przedmiotu? 

### ISSUE THREAD

**Issue by jsadowski** [allegro/allegro-api#3080]
W jaki sposób pobrać miniaturkę z odpowiedzi zamówień /order/checkout-forms skoro checkoutForms.lineItems[0].offer posiada tylko id, name i externalId?

**Comment by PrzemyslawLukanowski** [comment]
Nie zwracamy takiej informacji. Wszystkie dostępne pola znajdziesz w [naszej dokumentacji](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET).

**Comment by jsadowski** [comment]
Czyli żeby pobrać obrazek dla przedmiotów z zamówienia muszę dodatkowo wysłać request /sale/offers/{offerId} i z niego pobrać obrazek? Czyli jeśli mam 5 zamówień, a w każdym po 5 róznych przedmiotów to wiąże się to z 25 dodatkowymi requestami dla 5 zamówień?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę to jedyne rozwiązanie.
