### ISSUE TITLE
https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=xxxxx

### ISSUE THREAD

**Issue by prusmarcin** [allegro/allegro-api#3081]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://api.allegro.pl.allegrosandbox.pl/sale/shipping-rates?seller.id=44292413
W nagłówkach podaje Token i Accept.

W odpowiedzi cały czas dostaje:
{
    "errors": [
        {
            "code": "UserRepresentativeException",
            "message": "Empty user_name claim",
            "details": null,
            "path": null,
            "userMessage": "Wystąpił błąd podczas uzyskiwania dostępu do zasobów konta powiązanego."
        }
    ]
}

Token który przesyłam jest prawidłowy. Również z poziomu konta allegro mam zapisana jedną testową dostawę. Nie rozumiem dlaczego wywala ten błąd. W dokumentacji nie ma dodatkowych parametrów o których bym zapomniał.

Z góry bardzo dziękuje za pomoc.

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie zasobu - bez przeszkód pobrałem cenniki należące do konta. Proszę sprawdź wykorzystywany token - czy jest on przypisany stricte do konta, dla którego chcesz pobrać informacje o cennikach dostawy.

**Comment by prusmarcin** [comment]
Kurcze nie wiem dlaczego tak się dzieje. Token generuje właśnie z właściwego konta.
Dla endpointa: https://api.allegro.pl.allegrosandbox.pl/sale/categories
ten sam token działa prawidłowo a dla sale/shipping-rates?seller.id=44292413 już nie działa.

Jest jakaś konfiguracja uprawnien dostepu dla API z poziomu konta allegro przez przeglądarkę?

**Comment by MaciejFrackowiak** [comment]
Podejrzewam, że korzystasz z autoryzacji client_credentials, która umożliwia tylko dostęp do publicznie dostępnych danych (ta autoryzacja nie działa w kontekście zalogowanego użytkownika). Aby pobrać konkretne informacje przeznaczone tylko dla danego użytkownika niezbędne jest skorzystanie z autoryzacji typu code_flow lub device_flow.

**Comment by prusmarcin** [comment]
Zgadza się - to bym mój błąd. Dziękuje za naprowadzenie na poprawne rozwiązane, teraz mi działa :)
