### ISSUE TITLE
Pobieranie aukcji

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3083]
Witam na środowisku produkcyjnym przy korzystaniu z metody 
https://api.allegro.pl/sale/offers?publication.status=ACTIVE,ENDED&limit=100&offset=31600  dostaje dziwne błędy

The server committed a protocol violation. Section=ResponseStatusLine
Value cannot be null.\r\nParameter name: value

Zdarza się on losowo, niezależnie od parametrów. Czasem parę dni bez błędu, a czasem każda seria zapytań kończy się takim błędem.

Niestety z jakiś powodów nie jestem wstanie odczytać trace-id
Wszystkie dodatkowe informacje które posiadam wysyłam na formularz kontaktowy.

Proszę o jak najwięcej szczegółów jeżeli to błąd po mojej stronie

**Comment by SebastianOzdoba** [comment]
Zerknij na ten wątek: #2719

**Comment by lukaszzborek** [comment]
Dzięki, umknął mi ten wątek
