### ISSUE TITLE
/categories vs /sale/categories

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#3084]
Czy do każdego z tych zasobów trzeba się inaczej odwołać?

/sale/categories -> pobiera mi prawidłowo tablicę z 14 głównymi kategoriami

jednak jak odwołuje się do /categories to wyskakuje mi błąd 406

Mój nagłówek wygląda za każdym razem tak:

_Accept: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJ.....qaU
Accept-Language: PL_

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem przed momentem działanie zasobów - błąd 406 otrzymałem tylko, gdy nie przekazałem wartości dla Accept: application/vnd.allegro.public.v1+json - dokładnie w takiej sytuacji pojawia się komunikat:

```
{
    "errors": [
        {
            "code": "NotAcceptableException",
            "message": "Not acceptable representation requested. Please check 'Accept' request header",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}
```

**Comment by slawomir-kudla** [comment]
Czy tak też działa na sandboxie?

Wersja z błędem:
_curl -X GET -H 'Accept: application/vnd.allegro.public.v1+json;charset=UTF-8' -H 'Content-Type: application/vnd.allegro.public.v1+json' -H 'Authorization: Bearer eyJ...FP0' -H 'Accept-Language: PL' "https://api.allegro.pl.allegrosandbox.pl/categories"_

Wersja poprawna:
_curl -X GET -H 'Accept: application/vnd.allegro.public.v1+json;charset=UTF-8' -H 'Content-Type: application/vnd.allegro.public.v1+json' -H 'Authorization: Bearer eyJ...k10' -H 'Accept-Language: PL' "https://api.allegro.pl.allegrosandbox.pl/sale/categories"_

**Comment by MaciejFrackowiak** [comment]
Po Twoim pierwszym poście byłem przekonamy, że wywołujesz GET /sale/categories/{categoryId} - natomiast jak widzę próbujesz pobierać dane z nieudokumentowanego zasobu - w tym momencie każdy napotkany błąd jest "prawidłowy".
Do obsługi parametrów i kategorii prosimy o korzystanie z zasobów dostępnych w [dokumentacji](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters).

**Comment by slawomir-kudla** [comment]
oki dziękuję a proszę mi powiedzieć jaką teraz metodą mógł bym pobrać całe drzewko kategorii? kiedyś pamiętam pobrałem je z tego zasobu

**Comment by MaciejFrackowiak** [comment]
Nie pobierzesz całego drzewa naraz - musisz odpytać kolejne categoryId aż dotrzesz do liścia danej kategorii.
Przykładowo, najpierw korzystasz z GET /sale/categories by poznać ID kategorii głównych, a następnie GET /sale/categories/{categoryId} by poznać kolejne gałęzie kategorii aż do wspomnianego liścia, czyli ostatniego elementu danej ścieżki kategorii.

**Comment by rtnet-pl** [comment]
@MaciejFrackowiak 
> próbujesz pobierać dane z nieudokumentowanego zasobu

Jak się na to zapatrujecie - czy możemy wykorzystywać takie zasoby na własne ryzyko?

**Comment by MaciejFrackowiak** [comment]
@rtnet-pl Na pewno nie wspieramy - w dowolnym momencie możemy dostęp zablokować - i jeżeli ktoś oparł logikę swojej aplikacji na niej to może nagle mieć spory problem.
