### ISSUE TITLE
[restAPI] Zasób sale/images

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3086]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Cześć, 
Prośba o weryfikację, przykładowy request / response 

REQUEST 2020-04-16 14:19:09.8651320 
curl -X POST \
  'https://upload.allegro.pl/sale/images' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: image/png' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

RESPONSE 2020-04-16 14:19:11.7713820 Duration: 1906,25ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (500) Internal Server Error.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at AllegroRest.Api.AllegroRestClient.GetResponseWrapper[TRestRequest,TObject](TRestRequest req, RestApplication app, Nullable`1 loginId, Boolean publicToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": "8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()",
    "HResult": -2146233079,
    "Source": "System",
    "WatsonBuckets": null
  },
  "TraceId": "3beccd06ce828825",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, wczoraj pomiędzy godz. 11:50 - 14:30 mieliśmy okresowe problemy z dodawaniem zdjęć. Obecnie mechanizm działa prawidłowo. Przepraszam za niedogodności.

**Comment by SebastianOzdoba** [comment]
Dziś podobnie
  "TraceId": "ec9d10972bf6e732",

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Tak, potwierdzam tymczasowy problem -  pierwsze błędy pojawiły się po godz. 11. Pracujemy już nad tym.
