### ISSUE TITLE
Błąd - INTERNAL_SERVER_ERROR REST API

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#3087]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zauważyłem w ostatnim czasie wzrost błędów wewnętrznych REST API na produkcji, dziś jakiś wysyp, błędy na zmiane:

`{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Timeout to the backend service.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}`

lub

`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}`

lub całkowicie zwrotka HTML-owa, obciąłem resztę treści:
`...
<h2>Rany Julek!</h2>
            <p>Wygląda na to, że mamy problemy.</p>
            <p>Dzielnie walczymy, by poprawić tę sytuację.</p>
            <p>(kod błędu: 504)</p>
...`

Zasób: https://api.allegro.pl/sale/offers

Te problemy losowo pojawiają się od ładnych kilku(nastu) dni, ostatnio się nasiliły.
Co sie dzieje?

**Comment by ppart** [comment]
Potwierdzam od 2 tygodni duża ilość timeoutów

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Wasze zgłoszenia - sprawę timeoutów weryfikujemy.
