### ISSUE TITLE
Odstąpienia - brak nr konta w e-mailu! 

### ISSUE THREAD

**Issue by MichalOmega** [allegro/allegro-api#3088]
Witam
Kiedy będzie można pobrać odstąpienia przez Restapi ?
Dzisiaj wprowadzili Państwo kolejne "ulepszenie" usuwając nr konta z e-maila o odstąpieniu. 
Teraz trzeba szukać nr konta przełączając się co chwile pomiędzy kontami allegro aby pobrać nr konta.
Zapomnieli Państwo że są Klienci którzy nie płacą przez płatności allegro i musimy mieć nr konta aby oddać im pieniądze. Teraz dostęp do niego został skutecznie utrudniony.
Mam wrażenie że ostatnie pomysły są coraz ciekawsze.

pozdrawiam Michał

**Comment by MaciejFrackowiak** [comment]
Zgodnie z tym co w poście GH #3016 wspomniał mój kolega, temat znajduje się na liście sugestii zasobów do wdrożenia w przyszłości.
Jednocześnie swoje uwagi dot. opisanej zmiany może Pan przekazać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=c89325cc-9505-4915-b221-8211302a412b&subjectId=9cddc7ec-fa3f-406b-8a84-99bbac21ce41) - zostaną one przekazane do zespołu odpowiedzialnego za zmianę.
