### ISSUE TITLE
ID użytkownika

### ISSUE THREAD

**Issue by ziemekpr0** [allegro/allegro-api#3089]
Dlaczego w dokumentacji, w sekcji Public user information nie ma niczego do pobrania publicznych danych o użytkowniku, takich jak choćby jego ID? Dlaczego zasób, który jest w tej sekcji:
https://api.{environment}/users/{userId}/ratings-summary 
przyjmuje tylko token użytkownika, a nie aplikacji?

Skąd, w razie gdybym chciał skorzystać z tej metody, mam niby wziąć id użytkownika?
W WEBAPI można było ŁATWO pobrać takie dane. 

Mam jeszcze takie pytanie, jak można wygaszać coś co działało na rzecz czegoś, co nie działa? Teraz żeby zrobić jedną aplikację trzeba mieszać pomiędzy dwoma API a za chwilę kolejne zmiany... Podejście conajmniej dziwne.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spostrzeżenia. Obecnie nie planujemy udostępniać osobnych zasobów, aby takie dane zwracać. W zasobie GET /offers/listing znajdziesz seller.id.

**Comment by ziemekpr0** [comment]
Przecież nie można wyszukać aukcji użytkownika nie znając jego ID? Nie mozna też znaleźc aukcji po jej ID więc?

**Comment by MaciejFrackowiak** [comment]
W tym wypadku możesz połączyć dwa światy - WWW oraz API, na froncie wyszukasz ofertę po jej numerze, a idąc dalej tak poznasz login sprzedającgo i id konta.

**Comment by ziemekpr0** [comment]
Aha... dziękuję za odpowiedź. 

Zastanawiam się, jak wysłumaczyć komuś, np. klientowi, że żeby skorzystać z jakiejś funkcji w aplikacji, najpierw musi sobie znaleźć swoje ID w allegro. :D
