### ISSUE TITLE
doGetItemsList zwraca 0 wyników

### ISSUE THREAD

**Issue by szymonpru** [allegro/allegro-api#309]
Chce czytać listę przedmiotów z allegro(jakąkolwiek). Próbuję na wszystkie sposoby i mi się to nie udaje. Używam Pythona.
Przykładowy wynik użycia doGetItemList:

('itemsCount', 0)
('categoriesList', (CategoriesListType){
   categoriesTree = 
      (ArrayOfCategorytreetype){
         item[] = 
            (CategoryTreeType){
               categoryId = 26013
               categoryName = "Antyki i Sztuka"
               categoryParentId = 0
               categoryItemsCount = 0
            },
            (CategoryTreeType){
               categoryId = 98553
               categoryName = "Bilety, kupony, vouchery"
               categoryParentId = 0
               categoryItemsCount = 0
            },
            (CategoryTreeType){
               categoryId = 64477
               categoryName = "Biuro i Reklama"
               categoryParentId = 0
               categoryItemsCount = 0
            },

**Comment by jakubmaguza** [comment]
Jak wywołujesz tą metodę? Prawdopodobnie nie podajesz żadnych parametrów i dostajesz same kategorie, tak jak jest napisane w opisie metody "Domyślnie (bez podania identyfikatora kategorii/działu) zwracana jest lista wszystkich kategorii głównych (bez informacji o ofertach) oraz lista stałych filtrów dla listingu ofert (w tym lista działów)."

**Comment by masterix** [comment]
Dodam też, że miałem podobnie, gdy używałem parametru 'similar', potrafi już nie działać, także musiałem go wycofać.

**Comment by szymonpru** [comment]
Macie może zaimplementowane to API gdzieś w pythonie ?
Podając np.argument  filterId mam bląd suds.TypeNotFound: Type not found: 'filterId'.

**Comment by MaciejPotepa** [comment]
Czy jesteś w stanie podesłać mi treść zapytania i odpowiedzi w XMLU? API wspieramy z warstwy protokołu komunikacji, nie z warstwy językowo/aplikacyjnej.

**Comment by masterix** [comment]
@szymonpru nie mamy

**Comment by chawel** [comment]
@szymonpru przecież jest przykład implementacji w dokumentacji webapi:
https://allegro.pl/webapi/documentation.php/show/id,1342#method-code-examples

```#kod do wszukiwnia itemów w Pythonie 2.7, wymaga instalacji modulu suds
from suds.client import Client
import time
 
#Definiuje plik wejsciowz
url = 'https://webapi.allegro.pl/service.php?wsdl'
client = Client(url)
 
#Wpisz swoje webapi
webAPI = 'XXXXXX'
countryId = 1
 
filtr_query=client.factory.create('ArrayOfFilteroptionstype')
 
#do tej tablicy mozna dopisać co się chce i dowolnie edytować
tablica = {'category':'10',
           'condition':'used',
           'search':'tomanek'
           }
rangeUp = len(tablica)-1
 
for i in range(0,rangeUp):
    filtr = client.factory.create('FilterOptionsType')
    filtr.filterId = tablica.keys()[i]
    filtrAOS = client.factory.create('ArrayOfString')
    filtrAOS.item = tablica.values()[i]
    filtr.filterValueId = filtrAOS
    filtr_query.item.append(filtr)
 
 
wynik = client.service.doGetItemsList(webAPI, countryId, filtr_query, resultScope = 3,resultSize = 5)
print "Otrzymano %d wynikow." % wynik.itemsCount , "Sukces! %s " % time.strftime("%A, %H:%M:%S")
 
#time.sleep(10)
 ```
