### ISSUE TITLE
🐞 Nie zwracamy zdarzenia READY_FOR_PROCESSING / Missing READY_FOR_PROCESSING event

### ISSUE THREAD

**Issue by Dingo64** [allegro/allegro-api#3090]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam skrypt, który działa już kilka miesięcy i pobiera zamówienia. Nic nie było zmieniane, ale dzisiaj przestał zwracać wszystkie. Niektórych po prostu nie widzi.

Coś się zepsuło na produkcji i nie wszystkie opłacone zamówienia są zwracane przez API

**Comment by grz33gorz** [comment]
U mnie występuje to samo, metoda /order/events nie zwraca wszystkich wpisów z typem **READY_FOR_PROCESSING**, pozostałe np. **FILLED_IN**, **BOUGHT** dla danego CHECKOUT_FORM_ID pojawiają się. 

Problem zaobserwowany wczoraj, jedyna zmiana która wystapiła to zamienienie poprzedniego headera "_application/vnd.allegro.beta.v1+json_" na aktualny "_application/vnd.allegro.public.v1+json_"

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenia - weryfikujemy Wasze spostrzeżenie.

**Comment by mojosoft** [comment]
Potwierdzam, u nas  w dniu 16.05.2020 to samo kilkanaście takich przypadków , które nie dostały statusu READY_FOR_PROCESSING, pomimo widocznego w allegro statusu wpłaty zakończona

**Comment by barthoos** [comment]
Potwierdzam, rowniez mam problem. Przyklad: d9ab3962-7fca-11ea-98d5-4d6ece3a368c

**Comment by mojosoft** [comment]
Kolejne zamówienie z którym jest ten sam problem cccd9182-8073-11ea-8b27-77cacb1e12c6

**Comment by MichalOmega** [comment]
To co sie dzieje od wczoraj to katastrofa, do 3 w nocy odkręcałem ręcznie transakcje.

**Comment by mojosoft** [comment]
Proszę tez o zweryfikowanie informacji od kupującego , że nie zapłacił a  jego status płatności jest na zakończona .....
https://spolecznosc.allegro.pl/t5/dyskusje-kupuj%C4%85cych/problem-brak-p%C5%82atno%C5%9Bci-a-status-zako%C5%84czona/m-p/21388#M7070

**Comment by MaciejFrackowiak** [comment]
@mojosoft Jak widzę ta kwestia została już podjęta przez koleżankę z Allegro Gadane.

**Comment by mojosoft** [comment]
Wiem, ale interesuje mnie kwestia techniczna , czy możliwa jest taka sytuacja że przez API dostaniemy informacje że zamówienie jest opłacone pomimo braku wpłaty od kupującego ?

**Comment by pliszka2** [comment]
potwierdzam u nas to samo od wczoraj (na początku mało teraz co drugie nie przychodzi)

**Comment by MaciejFrackowiak** [comment]
@mojosoft Co do zasady - nie. Jeżeli taka sytuacja miałaby miejsce to byłby to poważny błąd (a takiego nie mamy).

**Comment by mojosoft** [comment]
kolejne zamówienie a4abd931-800c-11ea-9414-5f013013c01f

**Comment by Vader5** [comment]
U nas to samo, nie przychodzą niektóre (dużo) powiadomień z metody:  /order/events nie zwraca niektórych wpisów z typem READY_FOR_PROCESSING, inne (poprzedzające) np. FILLED_IN, BOUGHT dla CHECKOUT_FORM_ID pojawiają się (np. dla zamówienia a3086204-7fc2-11ea-a509-4b789994e5b6 z 16 kwi 2020, 11:15 zapłacone wg panelu klienta, a w logach nic na ten temat)

**Comment by MichalOmega** [comment]
a5eaaf82-7fc4-11ea-afe7-7d5e6c93edc7 READY_FOR_PROCESSING - za pobraniem DPD, następnie Klient za to samo zamówienie płaci i wybiera Payu inpost, a paczka już wysłana, jak to możliwe ??? Co mam powiedzieć Klientowi

**Comment by mojosoft** [comment]
kolejne zamówienie 01d36fd2-807e-11ea-a178-89ce2dda148a
czy ktoś to weryfikuje ? proszę o nie pobieranie opłat i prowizji do czasu naprawienia systemu ;)

**Comment by MaciejFrackowiak** [comment]
@mojosoft Tak, działamy - znaleźliśmy przyczynę problemów, naprawiamy. Zamieszczę informację kolejną, gdy będę miał pewne dane.

**Comment by mojosoft** [comment]
Dziekuje, wiec już nie spamuje kolejnymi informacjami o zamówieniach i czekam na informacje.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak podpinamy się, mamy to samo

**Comment by radoslawkoziol** [comment]
@MaciejFrackowiak a od 15.04 od godziny 9 rano, nie mamy żadnych nowych eventów z /sale/offer-events, powiązany problem?

**Comment by MaciejFrackowiak** [comment]
@radoslawkoziol Nie, zgłoszony tu problem dotyczy tylko brakujących zdarzeń RFP, pozostałe eventy są dostępne. Proszę podaj nam swój login (UID), wówczas sprawdzę sytuację u Ciebie.

**Comment by MaciejFrackowiak** [comment]
@MichalOmega Sprawdziłem zamówienie a5eaaf82-7fc4-11ea-afe7-7d5e6c93edc7 - tu kupujący podczas swoich dwóch prób wypełnienia formularza pozakupowego nigdy nie wybrał opcji pobrania.

**Comment by radoslawkoziol** [comment]
@MaciejFrackowiak problem występuje na 3 niezależnych od siebie maszynach, u wszystkich naszych  klientów i przestało się pobierać równocześnie, 15.04, godzina 9 rano.  Po naszej stronie nie było żadnych aktualizacji w tym czasie, więc raczej niemożliwe, żeby było po naszej stronie

**Comment by MaciejFrackowiak** [comment]
@radoslawkoziol Proszę prześlij nam szczegóły przypadków poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - dodaj tylko info GH 3090.

**Comment by mojosoft** [comment]
problem  jest większy, właśnie okazuje się że nie dostaliśmy żadnego zdarzenia dla zamówienia z dnia wczorajszego af21c412-800c-11ea-85aa-272af83e1ba6

**Comment by radoslawkoziol** [comment]
@MaciejFrackowiak rozwiązałem problem z zasobem eventów ofert. Chodziło o nagłówek accept, cały czas używaliśmy przy tym requeście: application/vnd.allegro.beta.v1+json, a widocznie od 15.04 przestał działać.

**Comment by mojosoft** [comment]
Czy zdarzenia dla zamówienia z 16.04 af21c412-800c-11ea-85aa-272af83e1ba6 dostaniemy w późniejszym czasie bo w sumie to nie wiem czy je "ręcznie" zrealizować

**Comment by grz33gorz** [comment]
@radoslawkoziol miałem podobny problem, zmiana nagłówka co prawda rozwiązanie problem z pobieraniem dziennika zmian, natomiast w owym dzienniku bardzo często (nie zawsze) brakuje typu READY_FOR_PROCESSING, dlatego zwróć uwagę czy wszystkie zamówienia z pewnością go otrzymują.

**Comment by radoslawkoziol** [comment]
@grz33gorz tak, ale tutaj chodziło mi akurat o zasób eventów  z ofertami, a nie z orderami. Nie miałem tam nowych zdarzeń od 15.04, myślałem, że może problem jest powiązany.

**Comment by mojosoft** [comment]
Kolejne zamówienie które do nas nie dotarło przez API w dniu 16.04 6c12b012-8004-11ea-abf0-cb8e10f6e1ce nie było żadnego zdarzenia

Proszę o pilną  odpowiedź czy te pominięte zdarzenia otrzymamy w późniejszym czasie ?

**Comment by kormichu** [comment]
@MaciejFrackowiak czyli problem tak naprawdę jest z zasobem do pobierania samych zdarzeń z journala: https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET nie zaś z zasobem do pobierania zamówień: https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET . Prawda ? Czy może zajść taka sytuacja że w journalu nie pojawił się wpis READY_FOR_PROCESSING, a w zasobie do pobierania zamówień już on jest ? Martwi mnie ta sytuacja u naszych klientów bo adres dostawy oraz do faktury tak naprawdę poprawny przychodzi dopiero kiedy status zamówienia na Allegro zmieni się na READY_FOR_PROCESSING. Problem w tym że my pobieramy wszystkie zamówienia nawet jak takiego statusu nie mają. Może się to wiązać z tym że klient otrzyma w panelu opłacone (tutaj nie jestem pewien) zamówienie ze statusem FILLED_IN oraz nieprawidłowymi danymi klienta co może spowodować mnóstwo problemów pomiędzy kupującym a sprzedającym. Sprzedający przecież może wysłać towar do kupującego na błędny adres !

**Comment by MaciejFrackowiak** [comment]
@mojosoft Problem z kompletnym brakiem danych może być osobną usterką - proszę podeślij nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) szczegóły takich transakcji - w treści proszę dodaj tylko numer posta z GH - 3090.

**Comment by MaciejFrackowiak** [comment]
@kormichu Zamówienie jest opłacone, gdy ma status READY_FOR_PROCESSING - nie ma takiej informacji przy FILLED_IN. Problem dotyczy stricte braku eventu, w samym zamówieniu status jest OK.

**Comment by mojosoft** [comment]
Jakie szczegóły, klienci dzownią że nie dostali produktu
do zamówień obecnie do tych dwóch , my ich nie dostaliśmy przez api
6c12b012-8004-11ea-abf0-cb8e10f6e1ce
af21c412-800c-11ea-85aa-272af83e1ba6

Proszę o pilną odpowiedź  !!! **czy te pominięte zdarzenia otrzymamy w późniejszym czasie** ?

**Comment by MaciejFrackowiak** [comment]
@mojosoft Nie sposób mi zweryfikować tych zamówień po samych ID, stąd prośba o przynajmniej loginy kont kupującego i sprzedającego (a że są to dane wrażliwe, stąd kontakt via formularz).

Pracujemy by przywrócić wszelkie niezbędne dane - jak wspomniałem, gdy będę mógł przekazać potwierdzone informacje zamieszczę kolejny wpis.

**Comment by mojosoft** [comment]
@MaciejFrackowiak Proszę o konkretną odpowiedź czy pominięte zdarzenia będą dosłane w późniejszym czasie czy są już do zapomnienia ? i mamy ręcznie obrabiać te zamówienia ?

**Comment by whoIam-user** [comment]
Witam, w dalszym ciągu nie mogę pobrać zamówień z allegro. Proszę o informację czy dalej naprawiacie błąd czy może już został naprawiony

**Comment by Dingo64** [comment]
Teraz się pojawiły zaległe zamówienia, których nie było wcześniej. ALE! Niektóre, które były wcześniej teraz pojawiły się ponownie z innym ID transakcji. 
Dwa różne ID transakcji, ale jedna płatność:
1587049033420350
1587117315663876

**Comment by Dingo64** [comment]
Podobnie tutaj. 2 różne ID, jedna płatność:
1587101981354840
1587117603508862

**Comment by MaciejFrackowiak** [comment]
@mojosoft Napisałem cyt. "Pracujemy by przywrócić wszelkie niezbędne dane"

**Comment by MaciejFrackowiak** [comment]
@Dingo64 To jest ID eventu, a nie transakcji.

**Comment by mojosoft** [comment]
Dziekuje

**Comment by Dingo64** [comment]
@MaciejFrackowiak Faktycznie, ID eventu. Ale przy 1 wpłacie zawsze było 1 ID. A tu nagle 2.

**Comment by MaciejFrackowiak** [comment]
@Dingo64 Musimy dodać brakujące eventy, stąd taka sytuacja - jednak jest to zgodne z tym, że dla jednego zamówienia może wystąpić kilka takich samych zdarzeń, stąd kluczowe by zwracać uwagę na identyfikator w checkoutForm.

**Comment by MaciejFrackowiak** [comment]
@mojosoft Sprawdziłem podane przez Ciebie zamówienia (dostaliśmy zgłoszenie mailowe):

6c12b012-8004-11ea-abf0-cb8e10f6e1ce
af21c412-800c-11ea-85aa-272af83e1ba6

Oba zamówienia bez przeszkód można pobrać korzystając z GET /order/checkout-forms/{checkoutFormId}

**Comment by mojosoft** [comment]
@MaciejFrackowiak tak to ja wiem ale nie było ich w dzienniku zdarzeń i stąd moje pytanie było czy mam je pobrać ręcznie czy czekać na informacje z API.

**Comment by Zbigniew-L** [comment]
Potwierdzamy, że metoda Get pobierze brakujące zamówienia, ale to nie rozwiązuje nam problemu - gdy mamy setki zamówień skąd mamy wiedzieć które z nich się nie pobrały bo events ich nam nie zgłosił? 

Pamiętam, że ten problem już kiedyś się pojawił i zdarzenia dotyczące brakujących zamówień 'magicznie' się pojawiły po pewnym czasie, czy możemy prosić o potwierdzenie, że tak samo będzie tym razem? 

wystarczy, że poszukacie których orderid brakuje w events (każde powinno być przynajmniej raz?) i wygenerujcie nam po prostu 'zaginione' eventy...

**Comment by Zbigniew-L** [comment]
Pomyślałem, że id zamówień dodatkowo można tez znaleźć w zasobie payments/payment-operations - zakładam, że tam są wszystkie orderid - czyli aż tak się musimy gimnastykować, żeby mieć pewność, że nie pominiemy żadnych zamówień? 
wszystko dlatego, że events nie działa jak trzeba...

**Comment by Dingo64** [comment]
@Zbigniew-L Mój system wpisuje sobie do bazy ID tych płatności, które przetworzył. Więc jak się nagle pojawiły zaległe to je przetworzył jakby nigdy nic. Jedyny u mnie problem, że używałem ID eventu zamiast ID checkoutForm. Najlepiej więc przerób swój system w ten sposób.

**Comment by MaciejFrackowiak** [comment]
Przed momentem zakończyliśmy prace związane z przywróceniem eventów do dziennika zdarzeń, wszelkie dane dot. zamówień są już dostępne.
Najmocniej przepraszamy za powstały błąd, który utrudnił Wam pracę.

**Comment by mojosoft** [comment]
Dziękuje i potwierdzam wygląda na to że są wszystkie zamówienia i zdarzenia związane z nimi,
ale co się nasłuchaliśmy od klientów bezcenne ;)

**Comment by mskiba03** [comment]
Czy problem oby na pewno zostal rozwiazany? Bo mam ten sam problem.

Identyfikator zamówienia: a27f4c02-863d-11ea-8d24-d53eb95050ac
Identyfikator płatności: a2bcf142-863d-11ea-9dfd-7bac605463c4

Mam więcej takich przypadków.
