### ISSUE TITLE
Zasób sale/images

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#3091]
Otrzymałem od Państwa maila, w którym (słusznie zresztą) zauważono, że w aplikacji, w zasobie POST /sale/images korzystam z autoryzacji typu "bearer-token-for-application", zamiast "bearer-token-for-user", co jest niezgodne z obecną wersją dokumentacji (kiedyś, w momencie tworzenia, taki sposób autoryzacji był wystarczający).

W związku z wycofaniem przez Państwo możliwości autoryzacji "starym" sposobem, chciałbym spytać, czy ze zdjęć wysyłanych z użyciem tokena, którym autoryzowane jest konto A, można również korzystać na używającym tej samej aplikacji koncie B (zakładając oczywiście, że zdjęcie nie wygasło, jest dostępne).

Przykładowo:
1) Przed wystawieniem oferty, z użyciem tokena konta A, wrzucam zdjęcie z użyciem zasobu POST /sale/images,
2) Wystawiam ofertę na koncie A z użyciem zdjęcia na Państwa serwerze, zwróconego przez ww. zasób.
3) Wystawiam ofertę (z tym samym produktem) na koncie B, z wykorzystaniem tego samego zdjęcia.

**Comment by MaciejFrackowiak** [comment]
Obecnie jest taka możliwość - pamiętać jednak musisz, że właścicielem zdjęcia jest konto A - to istotne w sytuacji, gdyby konto A zgłosiło "kradzież" przez B zdjęcia ze swojej oferty.

**Comment by lkowol** [comment]
@MaciejFrackowiak Dziękuję za odpowiedź. 
Taka sytuacja się nie wydarzy, zdjęcia będą mogły być "współdzielone" tylko w przypadku posiadania przez użytkownika uprawnień do obsługi wszystkich zaangażowanych w proces kont.
