### ISSUE TITLE
Zdublowane READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by haloween** [allegro/allegro-api#3092]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Przykładowe line deal Transction ID
f0057ef2-7f98-11ea-abf0-cb8e10f6e1ce

Otrzymaliśmy READY_FOR_PROCESSING podwójnie, przypadków jest około 100.
Każdy ma inny event id... Premium, prawdziwe premium.

17.04.2020

Po objawach obstawiam desynchronizację klastra DB w standardzie master-master + split brain. Ale to taki szybki strzał ...

**Comment by MaciejFrackowiak** [comment]
To jest ściśle związane z problemem z GH #3090 - proszę zajrzyj do powyższego posta.
