### ISSUE TITLE
OPERATION_FAILED - Cannot resolve offer images. Please retry.

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3093]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam serdecznie, problem pojawia się podczas zmian ceny w ofertach

przykładowe guidy: 
71738655-62e5-4f5c-b127-b3b983eccdcd
0383475c-5a77-4cc3-9b6c-f304be1c42b7

**Comment by MaciejFrackowiak** [comment]
Tu mamy do czynienia z tym samym problemem, który został opisany w poście GH #3086 - w czasie wykonywania przez Ciebie operacji mieliśmy problemy z dodawaniem / wyświetlaniem zdjęć. Przepraszam za niedogodności.

**Comment by dlis2010** [comment]
Ok, dziękuję za informację. 

Pozdrawiam i zamykam ;)

**Comment by dlis2010** [comment]
Witam,

niestety problem powrócił.

guid z dzisiaj: ff7d83d6-5caa-4f16-9404-0b6c0b8c283e

**Comment by MaciejFrackowiak** [comment]
@dlis2010 Spojrzałem na Twój request i porównałem z danymi, które widzę w bazie - niestety, znów "nieszczęśliwie" trafiłeś na nasze problemy - pracujemy, aby możliwie szybko zapobiec ich powtórzeniu.
