### ISSUE TITLE
Przywrocenie poprzedniej wersji opisu aukcji. 

### ISSUE THREAD

**Issue by krzysztofM87** [allegro/allegro-api#3094]
Dzień dobry, popełniłem błąd i opisy aukcji zostały nadpisane ich generycznych wersjami. Czy jest jakaś możliwość pobrania poprzedniej wersji opisu? Klienci widzą wersje aukcji z chwili zakupu, więc kolejne wersje są na pewno gdzieś przechowywane.  Czy jest taka możliwość w API?

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy możliwości wersjonowania opisu poprzez API.
