### ISSUE TITLE
Informacja o statusie płatności poprzez API

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3095]
W panelu Allegro jest informacja przy zamówieniach: "PŁATNOŚĆ ANULOWANA", "OPŁACONE" itp.
Czy jest możliwość aby pobrać status płatności poprzez RestAPI ? Bo to że mam zamówienie w statusie FILLED_IN czy BOUGHT nic nie mówi czy ktoś anulował płatność czy nie itp.

**Comment by MaciejFrackowiak** [comment]
W zasobach GET /order/checkout-forms oraz GET /order/checkout-forms/{checkoutFormId} znajdziesz taką informację w obiekcie payment:

```
"payment": {
                "id": "2dae8d62-57b6-11ea-97c2-b71e91a5aa43",
                "type": "ONLINE",
                "provider": "PAYU",
                "finishedAt": "2020-02-25T10:06:39.065Z",
                "paidAmount": {
                    "amount": "1.00",
                    "currency": "PLN"
                }
            },
            "status": "READY_FOR_PROCESSING",
```

Wpis type oraz provider mówią w jaki sposób wpłaty dokonał kupujący, finishedAt natomiast zwraca datę i czas wpłaty, paidAmount - kwota wpłaty. Potwierdzeniem wpłaty jest status READY_FOR_PROCESSING. Jeżeli płatność będzie anulowana to w polu paidAmount znajdziesz "null", a status to będzie FILLED_IN. Zajrzyj też do [naszego poradnika](https://developer.allegro.pl/orders/) dot. obsługi zamówień.

**Comment by malbrandt** [comment]
Czy status READY_FOR_PROCESSING występuje tylko w momencie, gdy wpłata pełnej kwoty za zamówienie została potwierdzona przez operatora płatności? Możliwe jest, żeby ten status przytrafił się dla zamówienia nieopłaconego (nie licząc pobrania i płatności przy odbiorze)? Pytanie dotyczy wszystkich metod płatności ("CASH_ON_DELIVERY" "WIRE_TRANSFER" "ONLINE" "SPLIT_PAYMENT").

**Comment by MaciejFrackowiak** [comment]
@malbrandt READY_FOR_PROCESSING wystąpi, gdy otrzymasz wpłatę z góry (jakąkolwiek) - dlatego niezbędne jest sprawdzenie w jakiej wysokości wpłatę otrzymałeś.
Oczywiście, RFP pojawi się także przy zakupach za pobraniem (w momencie, gdy kupujący wypełni poprawnie formularz pozakupowy) oraz przy SPLIT_PAYMENT - gdy również formularz pozakupowy zostanie wypełniony. 
WIRE_TRANSFER (zwykły przelew poza Allegro Finanse) jest już niedostępny w Allegro.

**Comment by mskiba03** [comment]
> READY_FOR_PROCESSING wystąpi, gdy otrzymasz wpłatę z góry (jakąkolwiek)

A w jaki sposób kupujący może dokonać wpłaty jakiekolwiek? Czy kwota do zapłaty nie jest ustalana z automatu na wartość zamówienia?

**Comment by MaciejFrackowiak** [comment]
@mskiba03 Podaję przykład - wpłata poprzez przelew tradycyjny realizowana w ramach Allegro Finanse - kupujący może przelać kwotę dowolną - niekoniecznie zgodną z kwotą wynikającą z oferty i kosztów dostawy.

**Comment by mskiba03** [comment]
@MaciejFrackowiak  Wg mnie to mozna by traktowac jako blad po stronie obslugi rest api. Jezeli cos jest wystawione za 100zł to zamowienie powinno dostac RFP gdy kupujacy wplaci 100zł a nie 20 ;) Poza tym wyżej napisał Pan:

> WIRE_TRANSFER (zwykły przelew poza Allegro Finanse) jest już niedostępny w Allegro.

Wiec zakładam, że przykład, który Pan podał jest nieaktualny. Czy jest jakaś inna możliwość, że kupujący wpłacił mniejszą kwotę niż wartość zamówienia?

**Comment by MaciejFrackowiak** [comment]
@mskiba03 Jest w pełni aktualny - mylisz przelew zwykły realizowany bezpośrednio na konto sprzedającego (WIRE_TRANSFER - wycofany z Allegro) z przelewem tradycyjnym realizowanym przez Allegro Finanse.
