### ISSUE TITLE
[SANDBOX] Brak możliwości wystawienia oferty

### ISSUE THREAD

**Issue by xemix** [allegro/allegro-api#3096]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie mogę wystawić nowej aukcji na środowisku testowym (interfejs webowy), "Wystaw przedmiot" kieruje do: https://staging-lokalnie.allegrogroup.com/oferty/wystaw - gdzie otrzymuję błąd:

> Ta witryna jest nieosiągalna
> Nie udało się znaleźć adresu IP serwera ze stroną staging-lokalnie.allegrogroup.com.
> DNS_PROBE_FINISHED_NXDOMAIN

**Comment by MaciejFrackowiak** [comment]
Proszę skorzystaj z odnośnika: [https://allegro.pl.allegrosandbox.pl/offer/?lokalnie](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie)
