### ISSUE TITLE
Przy pobieraniu ofert Empty user_name claim

### ISSUE THREAD

**Issue by kamelTrop** [allegro/allegro-api#3097]
Mam dziwny błąd.
Najpierw pobieram token wywołując: 
https://allegro.pl/auth/oauth/token?grant_type=client_credentials

Dostaje token. Następnie próbuje wywołać: 
https://api.allegro.pl/sale/offers

tak jak w dokumentacji:
curl -X GET \
  https://api.allegro.pl/sale/offers \
 -H 'Authorization: Bearer {token}' \
 -H 'Accept: application/vnd.allegro.public.v1+json'

I dostaje taki błąd:
{"errors":[{"code":"UserRepresentativeException","message":"Empty user_name claim","details":null,"path":null,"userMessage":"There was an error while trying to get related account's resources."}]}

To jakie jeszcze parametry mam dodać żeby pobrać listę ofert? Bo robie to jak w dokumentacji i nie działa.

**Comment by MaciejFrackowiak** [comment]
Listę ofert sprzedawcy (GET /sale/offers) pobierzesz tylko, gdy będziesz zautoryzowany - autoryzacja client_credentials nie posiada kontekstu użytkownika. Chcąc pobrać listę skorzystaj z autoryzacji typu code_flow lub device_flow.

**Comment by kamelTrop** [comment]
Dobrze, to najpierw wywołuje to:
https://allegro.pl/auth/oauth/device   

dostaje device_code i verification_uri_complete
Weryfikuje aplikacje adresem z verification_uri_complete, klikam powiąż aplikacje i dostaje odpowiedz udało się.

Nastepnie próbuje pobrać token z 
https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=xxxxx

z użyciem tego device_code i jest ok
Ale po chwili już jest ten kod nieaktywny.
Za każdym wywołaniem api mam potwierdzać w przeglądarce połączenie konta z aplikacją?

**Comment by MaciejFrackowiak** [comment]
Opisany przez Ciebie sposób autoryzacji jest zgodny z [naszym poradnikiem](https://developer.allegro.pl/auth/#DeviceFlow). Napisałeś, że uzyskałeś token - czy następnie znów nie wykorzystujesz tego samego device_code co chwilę wcześniej.

**Comment by kamelTrop** [comment]
dokładnie tak, póżniej znów używam tego samego device_code i juz nie moge dostać tokena, a jak chce uzyskac nowy device_code, to musze w przegladarce na nowo go zatwierdzić

**Comment by MaciejFrackowiak** [comment]
Device_code zwraca tylko raz token, każda następna operacja wymaga nowego device_code. Podsumowując - zachowanie mechanizmu w Twoim przypadku jest prawidłowe.

**Comment by kamelTrop** [comment]
To nie rozumiem - skoro device_code wygasa mi po kilku sekundach - a zeby go miec to za kazdym razem musze zalogowac sie przez przegladarke do allegro i powiazac aplikacje uzywajac verification_uri_complete

Skoro chce zrobic automatyczne pobieranie aukcji i modyfikacji to nie moge za kazdym razem przy pobieraniu device_code aktywowac go linkiem verification_uri_complete. Gdzie tu sens robienia api skoro za kazdym razem muszę ręcznie logowac sie i powiazac aplikacje?

**Comment by MaciejFrackowiak** [comment]
Być może w Twoim przypadku lepszym rozwiązaniem będzie autoryzacja typu code_flow - bez konieczności potwierdzenia urządzenia.

**Comment by kamelTrop** [comment]
Czyli wywołuje pobranie tokena w ten sposób?
https://allegro.pl/auth/oauth/token?grant_type=client_credentials

ale majac ten token jak próbuje pobrac moje oferty to nie chce mnie zautoryzować pod adresem:

https://api.allegro.pl/sale/offers

dostaje odpowiedź: Empty user_name claim

**Comment by MaciejFrackowiak** [comment]
Nie, tu znów wybrałeś autoryzację client_credentials, czyli bez kontekstu zalogowanego użytkownika. Zerknij pod [link](https://developer.allegro.pl/auth/#user) - dokładnie w tym miejscu opisujemy autoryzację code_flow.
