### ISSUE TITLE
Lista ocen sprzedawcy

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#3098]
Czy planujecie dodać do REST API możliwość pobierania listy ocen sprzedawcy?

**Comment by MaciejFrackowiak** [comment]
Listę otrzymanych przez sprzedawcę ocen sprawdzisz zasobem [GET /sale/user-ratings](https://developer.allegro.pl/documentation/#operation/getUserRatingsUsingGET).

**Comment by dark774** [comment]
dziękuję za odpowiedz, bardziej miałem na myśli publiczne informacje o sprzedawcy, tak jak ratings summary

**Comment by MaciejFrackowiak** [comment]
Nie, takiego zasobu nie mamy, aby zwracał szczegółowe opisowe oceny wybranego sprzedawcy. Proszę wskaż nam do czego byłby przydatny Tobie taki zasób.

**Comment by patrick477** [comment]
Skoro ratings summary jest dostępny publicznie to też przydałaby się list ocen. Wtedy na przykład można by klientowi pogrupować oceny względem danej oferty.

**Comment by dark774** [comment]
Skoro ratings summary jest dostępny publicznie to też przydałaby się list ocen. Wtedy na przykład można by klientowi pogrupować oceny względem danej oferty.

**Comment by MaciejFrackowiak** [comment]
GET /sale/user-ratings zwraca ID oferty oraz otrzymane do niej oceny sprzedającego - tak otrzymasz to czego potrzebujesz.
