### ISSUE TITLE
Brak szczegółów błędu utworzenia wielowariantu

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#3099]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Niestety otrzymuję dość ogólny konunikat, który nie służy, ani programisom, ani użytkownikowi:
"Nie można utworzyć oferty wielowariantowej."

Prosiłbym o dodanie szczegółów odrzucenia wielowariantu.
Przykład:
https://api.allegro.pl/sale/offer-variants/b0c30eec-2d8b-429b-bc05-87049e09af10 422

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku problem generowała oferta ****281812, jest to duplikat oferty ****806735. Dodatkowo oferta musi być aktywna. Prośbę dot. doprecyzowania przekazuję do odpowiedniego zespołu.

**Comment by aktywnitu** [comment]
Czy mogę jeszcze dla pewności poprosić o podów niepowodzenia edycji wielowariantu:

```
{'id': '75c61612-015a-4158-a46c-5cd0e7ed0aba',
 'name': '*********************** Polska małe rozmiary',
 'offers': [{'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****975823'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****975953'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****315319'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****760116'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****976072'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****179987'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****975354'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****209496'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****975642'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****976356'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****975479'},
            {'colorPattern': '32b7b3b1-64c3-4db9-b85f-178b03bb8654',
             'id': '****760096'}],
 'parameters': [{'id': '7173'}, {'id': 'color/pattern'}]}
```

message: "Nie można utworzyć oferty wielowariantowej."

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku oferta *****44030 jest duplikatem *****79987

**Comment by aktywnitu** [comment]
Dziękuję za odpowiedź. 
Powyżej podesłałem również json wielowariantu, który był wysłany w celu edycji.
W jego strukturze jest oferta *****44030, ale nie ma oferty *****44030, dla której rzekomo jest duplikat.
Prosiłbym sprawdzić jeszcze raz. Być może powód jest inny.

**Comment by PrzemyslawLukanowski** [comment]
@aktywnitu Analizuję jeszcze ten przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@aktywnitu Oferta wielowariantowa został utworzona kilka miesięcy temu, kiedy zasób był w wersji beta. Błąd, który otrzymałeś związany jest z obsługą tych ofert po naszej stronie w momencie utworzenia oferty wielowariantowej. Aktualnie, aby dodać ofertę z rozmiarem 158, powinno pomóc zamknięcie i ponowna aktywacja ofert:

- 8317760116 - 92
- 8317760096 - 98
- 8708315319 - 104
- 6455344030 - 146
- 8686179987 - 146

**Comment by tomasz-grzesik** [comment]
Czy mógłbym prosić o szczegóły dla błędu  "Nie można utworzyć oferty wielowariantowej."?

https://api.allegro.pl/sale/offer-variants/2ffc8ecd-feb6-4b5b-b8b9-e48ab904487e 422

**Comment by PrzemyslawLukanowski** [comment]
@tomasz-grzesik W tym przypadku oferty po wystawieniu trafiły po naszej stronie do różnych zbiorów, przez co występuje problem z utworzeniem oferty wielowariantowej. Spróbuj proszę zamknąć i wznowić oferty 7452771980 i 7452771159, a problem powinien ustąpić.

**Comment by tomasz-grzesik** [comment]
Niestety takich wielowariantów jest więcej. Czy pracujecie nad rozwiązaniem tego problemu?
Czy jednak trzeba zalecić Użytkownikowi wszsytko zakończyć i wznowić?

**Comment by PrzemyslawLukanowski** [comment]
Udało nam już się wprowadzić odpowiednie rozwiązania, które nie powinny doprowadzać do takich sytuacji, jednak problem nadal może występować dla ofert, które zostały wystawione do 11-03-2020. Takie problematyczne oferty najlepiej będzie zakończyć i wznowić ponownie.

**Comment by tomasz-grzesik** [comment]
Użytkownik zakończył i wznowił oferty i dla podanego wyżej przykładu problem zniknął.
Niestety są jeszcze przypadki, w których nie wiadomo o co chodzi - komunikat "Nie można utworzyć oferty wielowariantowej.", np:
https://api.allegro.pl/sale/offer-variants/edb8de37-06ee-4ae8-b494-b5c1d3bd04c7 422
https://api.allegro.pl/sale/offer-variants/048b9b46-84d4-4213-9247-67c257d6ec73 422
https://api.allegro.pl/sale/offer-variants/7e078a78-2d9d-4203-be24-5a1d51d222a4 422

**Comment by MaciejFrackowiak** [comment]
W tym przypadku znów mamy do czynienia z osobnymi zbiorami - kolejno spróbuj zakończyć i wznowić:

1) 8196277459, 
2) 8282380092,
3) 7355429979.

**Comment by tomasz-grzesik** [comment]
Przekażę tą uwagę Użytkownikowi, jednak twierdzi, że zakończył i wznowił wszystkie 18119 oferty.

**Comment by tomasz-grzesik** [comment]
Niestety zakończenie i wznowienie wymienionych ofert nic nie zmieniło.
Nadmienię, że Użytkownik wcześniej wszystko zakończył i wznowił.
Być może to nie jest rozwiązanie problemu, albo przyczyna leży gdzie indziej.
Fajnie by było, gdyby treść komunikatu byłaby bardziej sprecyzowana.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku problem generują także duplikaty w ofertach sprzedającego:
- 8196277459  jest duplikatem 9306602064,
- 8282380092 jest duplikatem 8858650367,
- 7355429979 jest duplikatem 8857677211.

Zalecamy usunięcie duplikatów, problem wtedy powinien ustąpić.
Co do precyzyjności komunikatów - odpowiedni zespół już nad tym pracuje.
