### ISSUE TITLE
doGetMySellItems brak znaków końca linii w opisie aukcji

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#310]
Metoda doGetMySellItems dla niektórych aukcji nie zwraca znaków końca linii. Np. oferta nr 7405068954 pobieram opis tej aukcji i otrzymuję:
[description] => Obiektyw Canon EF 70-200 f/4L USMPrzedmiotem aukcji jest obiektyw Canon EF 70-200 f/4L USM. Jest to bardzo ceniony teleobiektyw ze stałym światłem f/4 w całym zakresie ogniskowych. Współpracuje zarówno z aparatami z matrycą pełnoklatkową jak i tymi ze matrycą DX.Ten obiektyw, jak każdy z profesjonalnej linii Canona oznaczonej "L" wyróżnia się świetną jakością wykonania i bardzo dobrą jakością optyczną. Obiektyw wyposażony jest w szybki silnik USM, dzięki czemu ustawianie ostrości odbywa się szybko i pewnie.Obiektyw jest w idealnym stanie wizualnym i idealnym technicznym, na obudowie praktycznie nie ma śladów użytkowania, szkła czyste bez rys, przednia soczewka zawsze chroniona filtrem UV, jedynie osłona przeciwsłoneczna posiada ślady użytkowania w postaci rysek. Obiektyw jest w pełni sprawny, autofocus działa szybko i pewnie.W komplecie:obiektyw,2 dekielki,osłona przeciwsłoneczna.

zamiast:
Obiektyw Canon EF 70-200 f/4L USM
Przedmiotem aukcji jest obiektyw Canon EF 70-200 f/4L USM. Jest to bardzo ceniony teleobiektyw ze stałym światłem f/4 w całym zakresie ogniskowych. Współpracuje zarówno z aparatami z matrycą pełnoklatkową jak i tymi ze matrycą DX.

Ten obiektyw, jak każdy z profesjonalnej linii Canona oznaczonej "L" wyróżnia się świetną jakością wykonania i bardzo dobrą jakością optyczną. Obiektyw wyposażony jest w szybki silnik USM, dzięki czemu ustawianie ostrości odbywa się szybko i pewnie.

Obiektyw jest w idealnym stanie wizualnym i idealnym technicznym, na obudowie praktycznie nie ma śladów użytkowania, szkła czyste bez rys, przednia soczewka zawsze chroniona filtrem UV, jedynie osłona przeciwsłoneczna posiada ślady użytkowania w postaci rysek. Obiektyw jest w pełni sprawny, autofocus działa szybko i pewnie.

W komplecie:

obiektyw,
2 dekielki,
osłona przeciwsłoneczna.

Inne oferty z tym problemem: 7373728814, 7373783821, 7375704758, 7375715348

**Comment by MaciejPotepa** [comment]
Dzięki za zgłoszenie. Badamy problem.

**Comment by juhacz** [comment]
Generalnie problem występuje chyba od jakiegoś czasu, a nie losowo. 2 aukcje wystawione przed momentem 7410100776 i 7410122929 i jest to samo.

**Comment by MaciejPotepa** [comment]
Okay, dzięki za przykłady.

**Comment by juhacz** [comment]
Są jakieś nadzieje na naprawę tego?

**Comment by MaciejPotepa** [comment]
@juhacz Pracujemy nad tym, przepraszam za problemy.

**Comment by juhacz** [comment]
Rozumiem, że błąd jest poważny i ciężko go namierzyć, ale czy po 4 miesiącach mogę zapytać czy potrwa to jeszcze długo?

**Comment by MaciejPotepa** [comment]
Najmocniej przepraszam za długi czas odpowiedzi, moje niedopatrzenie. 

Powiedz proszę, czy problem nadal u Ciebie występuje? Jeżeli tak to podeślij proszę treść request i response.

**Comment by juhacz** [comment]
Oto część odpowiedzi, nie wiem czy o to chodzi - https://pastebin.com/c0EwRenX
Po prostu z itDescription, dokładnie  <section class="text-item"></section> są usunięte znaki nowej linii.

**Comment by MaciejPotepa** [comment]
Dzięki za podesłane treści, jeżeli problem występuje w większej ilości ofert to też możesz śmiało podesłać. 

Im więcej danych tym łatwiej będzie namierzyć i rozwiązać problem. 

Jeszcze raz dzięki i przepraszam za zwłokę w tym temacie.
