### ISSUE TITLE
Rest API pole typu string, pole powtarzalne

### ISSUE THREAD

**Issue by GrzegorzLewinski** [allegro/allegro-api#3100]
Występuje problem: 
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam. Przy integracji Allegro z sklepem internetowym poprzez RestApi zauważyłem że pole typu string w sklepie internetowym przechowywane jest jako pole powtarzalne( ID kategorii: 258697, ID pola: 215941 ). 
Według dokumentacji wynika że do pola typu string może przypisać jedną bądź wiele wartości.
Natomiast moje pytanie brzmi czy każde pole z dokumentacji typu string może przyjść więcej niż jedną wartość ?

**Comment by PrzemyslawLukanowski** [comment]
Taką informację zwracamy w polu **restrictions.allowedNumberOfValues** w odpowiedzi dla [GET sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Dzięki niej dowiesz się, ile wartości możesz przypisać do danego pola. Odpowiedź dla wskazanego przez Ciebie przykładu:

```
{
            "id": "215941",
            "name": "Numery katalogowe zamienników",
            "type": "string",
            "required": false,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null
            },
            "restrictions": {
                "minLength": 1,
                "maxLength": 40,
                "allowedNumberOfValues": 20
            }
        },
```

**Comment by GrzegorzLewinski** [comment]
Dziękuję bardzo za wyjaśnienie. Musiało mi to umknąć.
