### ISSUE TITLE
Brak możliwości połączenia oferty zakończonej przez API - skąd takie ograniczenie?

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#3101]
Przez przeglądarkę można bez problemu zdefiniować wielowariant z ofertą zakończoną i go zapisać.
Przez API niestety nie da się tego zrobić:

Z poradnika:
"Czy mogę utworzyć ofertę wielowariantową przed aktywacją ofert?
Nie, otrzymasz wtedy odpowiedź z błędem i informacją, że nie znaleziono ofert, które przekazałeś w strukturze. Oferty muszą być w statusie ACTIVE."

Skąd takie ograniczenie. Niestety powoduje to dużo błędów typu:
"Można dodawać tylko oferty aktywne do oferty wielowariantowej. Oferty: ...  nie są aktywne."

**Comment by aktywnitu** [comment]
Zrobiłem test przez API utworzenia wielowariantu z ofertą zakończoną i się udało.
Pytanie zatem jest inne:
O czym mowa w poradniku?
Kiedy pojawia się błąd: "Można dodawać tylko oferty aktywne do oferty wielowariantowej. Oferty: ... nie są aktywne." ?

**Comment by PrzemyslawLukanowski** [comment]
Przez przeglądarkę również możesz połączyć tylko aktywne oferty. Czy możesz doprecyzować, w jaki sposób to zrobiłeś i podać przykładowe numery takich ofert? Podobnie w przypadku API - prosiłbym o przykładowe trace-id.

**Comment by aktywnitu** [comment]
Przykład wielowariantu utworzonego przez przeglądarkę:
607c9843-b77f-4544-be1c-98cc699168a2

Jak to zrobiłem?
1. Utworzyć wielowariant z kilkoma ofertami.
2. Zakończyć jedną z ofert wielowariantu.
3. Zedytować wielowariant - widać, że oferta zakończona jest na liście i można taki wielowariant zapisać.

**Comment by PrzemyslawLukanowski** [comment]
Taki scenariusz jest możliwy, ponieważ utworzyłeś ofertę wielowariantową w momencie, kiedy oferty były aktywne. Jeżeli teraz aktywujesz zakończoną ofertę, ponownie wejdzie ona w skład oferty wielowariantowej.

**Comment by aktywnitu** [comment]
Stąd pytanie - dlaczego takie ograniczenie?
Dla jednych zakończonych jest błąd, dla innych nie. 
Jakieś przeszkody, aby znieść to ograniczenie?

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem opisany przez Ciebie scenariusz w przeglądarce. Wszystko tutaj dzieje się prawidłowo - jeżeli zakończysz ofertę, nie możesz jej ponownie dodać do oferty wielowariantowej, jeśli jest w statusie "zakończona". Jak poniżej:

![Screenshot_34](https://user-images.githubusercontent.com/51473661/79876488-65ff3a00-83eb-11ea-8962-1adf29c98a49.png)

Oferty zakończonej nie da się wyszukać za pomocą wyszukiwarki po lewej stronie.

**Comment by aktywnitu** [comment]
Widocznie zostałem źle zrozumiany. 
Oczywiście, oferty zakończonej nie da się dodać i przez przeglądarkę i przez API.
Sądziłem wcześniej, że przy edycji ofert da się zapisać wielowariant z ofertą wcześniej dodaną i zakończoną tylko przez przeglądarkę, ale jednak przez API działa tak samo.
Otrzymywałem tylko błąd przez API związany z nowo dodawaną ofertą zakończoną do wielowariantu. 
Zastanawia mnie, czy nie można by znieść tego ograniczenia - a w przeglądarce można by zrobić filtr - oferty tylko aktywne lub wszystkie.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy znieść tego ograniczenia, wynika to z naszych wewnętrznych rozwiązań.

**Comment by aktywnitu** [comment]
Przez API niestetety nie da się zedytować wielowariantu, do którego wcześniej zostały dodane oferty aktywne, a później zostały zakończone:
"Można dodawać tylko oferty aktywne do oferty wielowariantowej. Oferty: ***5414375, ***0914529, ***0960699, ***2359793 nie są aktywne."

id wariantu: 2d19977d-cbde-48ab-89c2-0c52b98caddb

**Comment by PrzemyslawLukanowski** [comment]
Edycja przez przeglądarkę działa jeszcze w wersji beta, dlatego jest to możliwe. Na dniach się to zmieni, beta zostanie wyłączona.

**Comment by aktywnitu** [comment]
Czy jednak nie powinno to działać tak jak w becie?
Po wznowieniu oferty sprzedawcy będą musieli taką ofertę znowu dodać do wielowariantu.

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli chodzi o przypadek, w którym oferta, która wchodzi w skład oferty wielowariantowej, zostanie zakończona, to w momencie jej wznowienia automatycznie zostanie z powrotem dołączona do oferty wielowariantowej.

**Comment by aktywnitu** [comment]
No dobrze. Ale poprzez API (wersja public) nie można zedytować wielowariantu, w którym są takie oferty zakończone. W czasie edycji trzeba usunąć wszystkie zakończone oferty i pozostawić tylko aktywne zgodnie z tym co jest w komunikacie błęd: "Można dodawać tylko oferty aktywne do oferty wielowariantowej. ".
Zgadzam się, że można zakończyć ofertę i wznowić i wówczas oferta wznowiona wskoczy w wielowariant, w którym była o ile nie edytowaliśmy tego wielowariantu przez API.
Przez przeglądarkę to działa inaczej - można zapisać wielowariant z zakończonymi oferta - i tak też to powinno działać przez API.

**Comment by MaciejFrackowiak** [comment]
@aktywnitu Dziękuję za Twoje spostrzeżenie - sugestię przekażę do działu bezpośrednio odpowiedzialnego za rozwój tej funkcjonalności.
