### ISSUE TITLE
Getting "User is neither brandzone nor tags subscribed" error

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#3102]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

When I try `GET https://api.allegro.pl.allegrosandbox.pl/sale/offer-tags?user.id=44254129&offset=0&limit=1000` I get the error `User is neither brandzone nor tags subscribed`.

It was working last week and I'm sure the details are the same.

**Comment by PrzemyslawLukanowski** [comment]
Tags are available for Abonament sklepowy subscription users. Make sure you've activated it via [this link](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/abonamenty). You were also authorized as a seller ***77280, not 44254129.
