### ISSUE TITLE
Pytanie dot. wznawiania ofert.

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#3103]
Jeden z klientów zgłasza często występujący problem dot. niechcianego, niekontrolowanego automatycznego wznawiania ofert zamkniętych przez system korzystający z REST API.

Przykładowo: o 2020-04-20 11:14:02 została wydana dyspozycja zamknięcia oferty z ID: "7fca0e10-8383-46be-a3a0-7be15c835ad3". 

Zasób GET https://api.allegro.pl/sale/offer-publication-commands/7fca0e10-8383-46be-a3a0-7be15c835ad3 zwraca:
`{
    "id": "7fca0e10-8383-46be-a3a0-7be15c835ad3",
    "taskCount": {
        "total": 1,
        "success": 1,
        "failed": 0
    }
}`

Oferta pozostawała aktywna aż do godziny ok. 11:44, kiedy ponownie została wykonana komenda zamykająca ofertę, już z pozytywnym skutkiem.
Nie jestem w stanie jednoznacznie określić, czy oferta się w ogóle zamknęła, czy została wznowiona. Problem jest częsty.

Czy dysponują Państwo logami świadczącymi, czy:
- oferta została realnie zamknięta?
- czy coś (i ewentualnie co, w jakiej godzinie) wznowiło ofertę?

**Comment by PrzemyslawLukanowski** [comment]
Na podstawie naszych logów widzę, że komenda 7fca0e10-8383-46be-a3a0-7be15c835ad3 zakończyła ofertę o 11:14. Oferta została wzniowiona o 11:22 komendą 1ea56a7b-bd40-30c9-bca6-f99bef749474 - przy udziale innego clientID (końcówka ..2447). Następnie o 11:50 została ponownie zakończona komendą 7bc04c11-7b15-3545-9f0c-c93d38b5f454 (clientID ...2447).

**Comment by lkowol** [comment]
@PrzemyslawLukanowski Bardzo dziękuję, tak przypuszczałem.
