### ISSUE TITLE
[Cats-Prod]: Ponad 6 tys. kategorii w arkuszu - NOWE PARAMETRY!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#3104]
https://assets.allegrostatic.com/popart-attachments/att-ac04918b-a9fb-4a2e-b53b-89fc037bcd0f
Powyższy arkusz jest mocno sknocony, wiele ścieżek struktury kategorii się nie zgadza, są też braki w tym arkuszu, błędy nazewnictwa w gałęziach, po prostu wszystko... Poniżej pewien wybór tylko:

 1N> DOM I OGRÓD__WYPOSAŻENIE__AKCESORIA ŁAZIENKOWE__AKCESORIA DO PRANIA -> NotEXISTS!
 1N> DOM I OGRÓD__WYPOSAŻENIE__RĘCZNIKI__RĘCZNIKI PLAŻOWE I KĄPIELOWE -> NotEXISTS!
 1N> DZIECKO__KARMIENIE DZIECKA__ŻYWNOŚĆ DLA DZIECI__CIASTECZKA -> NotEXISTS!
 1N> DZIECKO__WÓZKI__AKCESORIA__PRZYCZEPKI -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__BATMAN -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__DISNEY PRINCESS -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__MINIFIGURES -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__PŁYTKI BUDOWLANE -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__POWER FUNCTIONS -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__KLOCKI__LEGO__SPIDER-MAN -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__LALKI I AKCESORIA__AKCESORIA DLA LALEK__DOMKI DLA LALEK -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__LALKI I AKCESORIA__AKCESORIA DLA LALEK__FOTELIKI I KRZESEŁKA -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__LALKI I AKCESORIA__AKCESORIA DLA LALEK__MEBLE DLA LALEK -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__BOB BUDOWNICZY -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__CLIFFORD -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__KŁAPOUCHY -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__KUBUŚ PUCHATEK -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__NODDY -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__PROSIACZEK -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__TYGRYSEK -> NotEXISTS!
 1N> DZIECKO__ZABAWKI__MASKOTKI__POSTACIE Z BAJEK__WŁATCY MÓCH -> NotEXISTS!
 1N> DZIECKO__ZDROWIE I HIGIENA__ARTYKUŁY HIGIENICZNE__ARTYKUŁY DO DEZYNFEKCJI -> NotEXISTS!
 1N> DZIECKO__ZDROWIE I HIGIENA__PIELUSZKI I CHUSTECZKI__CHUSTECZKI NAWILŻAJĄCE -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ELEKTRONIKA__KABLE, PRZEWODY__SVHS (S-VIDEO) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__BECKER -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__BLAUPUNKT -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__BLOW -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__CLARION -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__CRUSER -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__FABRYCZNE -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__LARK -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__MIO -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__MODECOM -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__NAVIGON -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__NAVITEL -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__NAVROAD -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__PEIYING -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__TOMTOM -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__UROUTE -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__GPS I AKCESORIA__URZĄDZENIA__VORDON -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT AUDIO DLA DOMU__DAC -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT AUDIO PRZENOŚNY__ODTWARZACZE CD, MD I KASETOWE__ODTWARZACZE CD -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT AUDIO PRZENOŚNY__ODTWARZACZE CD, MD I KASETOWE__ODTWARZACZE CD/MP3 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT AUDIO PRZENOŚNY__ODTWARZACZE CD, MD I KASETOWE__ODTWARZACZE KASETOWE -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT AUDIO PRZENOŚNY__ODTWARZACZE CD, MD I KASETOWE__ODTWARZACZE MD -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT CAR AUDIO__AKCESORIA__KOSTKI ISO, ZŁĄCZKI__ADAPTERY DO INSTALACJI SAMOCHODOWEJ - ISO -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT CAR AUDIO__AKCESORIA__KOSTKI ISO, ZŁĄCZKI__ZŁĄCZA DO RADIOODBIORNIKÓW FABRYCZNYCH - ISO -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT CAR AUDIO__AKCESORIA__KOSTKI ISO, ZŁĄCZKI__ZŁĄCZA ISO DO RADIA -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__SPRZĘT CAR AUDIO__AKCESORIA__STEROWANIE Z KIEROWNICY -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__18650 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__9V (6F22) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__AA (R6) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__AAA (R3) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__C (R14) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__AKUMULATORKI__D (R20) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE__9V (6F22) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE__AA (R6) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE__AAA (R3) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE__C (R14) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE__D (R20) -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__2CR5 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR1216 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR1220 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR123 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR1616 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR1620 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2016 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2025 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2032 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2430 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CR2450 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__CRP2 -> NotEXISTS!
 1N> ELEKTRONIKA__RTV I AGD__ZASILANIE__BATERIE SPECJALISTYCZNE__SREBROWE -> NotEXISTS!
 1N> ELEKTRONIKA__SPRZĘT ESTRADOWY, STUDYJNY I DJ-SKI__CD-PLAYERY DLA DJ-ÓW__CD/MP3 -> NotEXISTS!
 1N> ELEKTRONIKA__SPRZĘT ESTRADOWY, STUDYJNY I DJ-SKI__WALIZKI I TORBY__NA CD -> NotEXISTS!
 1N> FIRMA__PRZEMYSŁ__BUDOWNICTWO PRZEMYSŁOWE__PRACE NA WYSOKOŚCI__ZAWIESIA ŁAŃCUCHOWE -> NotEXISTS!
 1N> SPORT I TURYSTYKA__SPORTY ZIMOWE__SNOWPARK -> NotEXISTS!
 1N> SUPERMARKET__PRODUKTY SPOŻYWCZE__PRODUKTY SYPKIE__CUKIER I SUBSTANCJE SŁODZĄCE__MELASA -> NotEXISTS!
 1N> SUPERMARKET__PRODUKTY SPOŻYWCZE__WARZYWA I OWOCE__KWIATY JADALNE -> NotEXISTS!
 1N> SUPERMARKET__PRODUKTY SPOŻYWCZE__WARZYWA I OWOCE__ŚWIEŻE ZIOŁA -> NotEXISTS!
 1N> URODA__PIELĘGNACJA__CIAŁO__KĄPIEL I PRYSZNIC__AKCESORIA DO MASAŻU -> NotEXISTS!
 1N> ZDROWIE__LEKI BEZ RECEPTY__JAMA USTNA__PARADONTOZA -> NotEXISTS!
 1N> ZDROWIE__LEKI BEZ RECEPTY__POZOSTAŁE__DEZYNFEKCJA -> NotEXISTS!
 1N> ZDROWIE__LEKI BEZ RECEPTY__UKŁAD MOCZOWO-PŁCIOWY__KAMICA NERKOWA -> NotEXISTS!
 1N> ZDROWIE__LEKI BEZ RECEPTY__UKŁAD POKARMOWY__TRZUSTKA -> NotEXISTS!

**Comment by PrzemyslawLukanowski** [comment]
Pod [tym linkiem](https://github.com/allegro/allegro-api/files/4474138/lista.parametrow.globalnych.xlsx) znajdziesz zaktualizowany plik.

**Comment by FromAnyHole** [comment]
@PrzemyslawLukanowski - było to gdzieś wcześniej publikowane??

**Comment by PrzemyslawLukanowski** [comment]
Tak, w odpowiedzi w wątku [[NEWS] Nowe uniwersalne parametry obowiązkowe / New universal required parameters](https://github.com/allegro/allegro-api/issues/2975).

**Comment by FromAnyHole** [comment]
@PrzemyslawLukanowski - Ok, jest tam wszystko co trzeba, trzymajcie się już tego zasobu, bo pewnie będą jeszcze liczne zmiany...
