### ISSUE TITLE
validation error VALIDATION_ERROR

### ISSUE THREAD

**Issue by scharov** [allegro/allegro-api#3105]
I have the same problem as with #2964, but not in a sandbox account, but in a real account

"validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "ERR_IF_YOU_WANNA_SELL",
                "details": "",
                "path": "",
                "userMessage": ""
            }
        ]
}

This account is active (Greenfood) and a few items have already been sold. These articles were successfully created in Allegro backend. But when I try to create articles via REST-API I get this validation problem.

**Comment by PrzemyslawLukanowski** [comment]
Could you please send us sample request and response in cURL format via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=c89325cc-9505-4915-b221-8211302a412b&subjectId=9cddc7ec-fa3f-406b-8a84-99bbac21ce41) (add information about ticket number 3105 on GitHub). I checked our logs - there are no requests for this user. Also, this account doesn't have any [linked apps](https://developer.allegro.pl/en/auth/#checkApp).

**Comment by netfarma** [comment]
Cześć, to samo mam na Sandbox z nowym kontem.

**Comment by PrzemyslawLukanowski** [comment]
@netfarma Podaj proszę Twój login na sandboxie.
