### ISSUE TITLE
invalid_token przy metodzie "sale/shipping-rates?seller.id"

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#3106]
Witam
1. Loguję się do REST z aplikacji
2. Loguje poprawnie.
3. Wywołuje metodę "sale/shipping-rates?seller.id" i dostaję {"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

Logowanie przebiega poprawnie. 
Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że Twój token jest już nieaktualny lub używasz go w niewłaściwym środowisku, np. token z produkcji na sandboxie lub odwrotnie. Prześlij nam proszę przykładowy pełen request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=c89325cc-9505-4915-b221-8211302a412b&subjectId=9cddc7ec-fa3f-406b-8a84-99bbac21ce41), w zgłoszeniu dopisz Github #3106. Zweryfikuję to.

**Comment by qshop123** [comment]
Popróbowałem zrobić to samo na produkcji na swoim koncie i jest to samo. 
Wysłałem pack.zip z var_dump i var_log w XML, ale : 
- Formularz który służy do wysyłki uparcie chce numer oferty, podałem randomowy ale w treść wstawiłem Github #3106
Czekam na odpowiedź

**Comment by qshop123** [comment]
Otrzymałem dzisiaj wiadomość z waszego działu pomocy że Pani nie wie czego dotyczy moja wiadomość :( 
Proszę o sprawdzenie sytuacji bo moi klienci już ostrzą zęby na mnie.

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się dotrzeć do Twojego załącznika. Powodem problemu jest niepełny token, który wysyłasz dla `GET /sale/shipping-rates?seller.id`, brakuje końcówki "-gTD8flJtLNDtxgE7xZMhPUqS8m8f_mex8eEEQwpqV-TboYjt_Otcg0n779u7Ab5CQ_DTnoVwSAyXleSTK82-pYTN2J2BdWCDgFqKY6DasmpLdT5XxAraNibCyEDxwH0bR0DUHr77TJXw3T4hUqVG5W5jfE8MMcg". Token jest już także przeterminowany, musisz wygenerować nowy.

**Comment by qshop123** [comment]
Dzień dobry
Wygląda na to że dla nowo zakładanych aplikacji wasz system generuje tokeny o długości większej niż opisane to było w dokumentacji.
Temat rozwiązany.
