### ISSUE TITLE
Not Found przy PUT sale/offers/{id}

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3107]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Mam niespodziewany problem z aktualizacją ilości sztuk na jednej z aukcji. Problem zaczął występować dzisiaj dla różnych aukcji tego samego klienta.

Zasób
`PUT sale/offers/{id}`

Przykładowe trace-id:
```
trace-id:2410d9632583508f
trace-id:29a693aacf3bbdf6
trace-id:1ae69f6bf938b960
```

Status aukcji to active

Edit: właśnie dostałem pierwszy problem przy `GET sale/offers/{id}`

`GET sale/offers/{id} || trace-id:ba1277fccf8a6c0d`

**Comment by PrzemyslawLukanowski** [comment]
```
Przykładowe trace-id:

trace-id:2410d9632583508f
trace-id:29a693aacf3bbdf6
trace-id:1ae69f6bf938b960
```

Te żądania zakończyły się odpowiedzią 200. 

```
Edit: właśnie dostałem pierwszy problem przy GET sale/offers/{id}

GET sale/offers/{id} || trace-id:ba1277fccf8a6c0d
```

Oferta została zarchiwizowana po 60 dniach od zakończenia.

**Comment by Radeq** [comment]
Dziękuję za pomoc.
