### ISSUE TITLE
Błędny numer telefonu dla konta

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#3108]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam.

Dzisiaj jeden z naszych klientów zauważył brak zamówienia w naszym systemie, a został on spowodowany danymi, które obecnie nie mają prawa bytu (patrząc pod kątem ilości przerobionych zamówień, a pierwszym takim przypadkiem - być może jest to jakaś zaszłość). Mianowicie jest to zły numer telefonu w formacie "XXXXXXXXX   XXXXXXXXX" - są wpisane dwa numery z kilkoma spacjami pomiędzy. Dotyczy checkoutFormId 023604a2-825f-11ea-b45b-aba6bfbadce5, trace-id: 1c27fa6b6e49b0da.
Czy nie jest to jakiś błąd związany z walidacją z Waszej strony?

**Comment by PrzemyslawLukanowski** [comment]
Jest to sytuacja podobna do #3042.  W polu delivery.address.phoneNumber kupujący podał prawidłowy numer telefonu, realizacja zamówienia jest zatem możliwa. Numer ze spacją pochodzi z sekcji buyer, są to dane z ustawień konta kupującego. W przeszłości był w stanie uzupełnić dane w takiej formie, bez walidacji z naszej strony, aktualnie jest to niemożliwe. Jeżeli kupujący będzie chciał teraz edytować nr telefonu w ustawieniach, będziemy wymagać prawidłowego formatu.

**Comment by bacok** [comment]
Ok, dziękuję za informację.
