### ISSUE TITLE
Zmiana kategorii na poprawną w istniejącej ofercie

### ISSUE THREAD

**Issue by rafalandryanczyk** [allegro/allegro-api#3109]
Cześć,

nasz klient zgłosił, że po przez wasz interfejs, istnieje możliwość edycji kategorii w istniejącej już ofercie, w momencie jeśli system blokuje przypisanie produktu po EANie, właśnie z powodu błędnej kategorii. 

Czy planujecie dodać też taką możliwość w API ? Niestety nasze próby zmiany kategorii na poprawną (zwracaną przez wasze API), kończą się niepowodzeniem. 

Z góry dzięki za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Zarówno przez stronę, jak i w API, kategorię zmienisz tylko wtedy, gdy nie pojawiły się w niej jeszcze oferty kupna i od wystawienia upłynęło mniej niż 12 godzin. Czy możesz doprecyzować zgłoszenie od Waszego klienta? Jakie dokładnie czynności wykonuje?
