### ISSUE TITLE
Delete multiple offers

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#311]
Hi guys,

Is there any way to create/delete multiple offers at once ? I searched the REST API and couldn't find any route for batch insert/ batch delete. 

Thank you !

**Comment by AniaMalinowska** [comment]
Using publication method in REST you can also end many offer at once. [More about that](https://developer.allegro.pl/en/sale/#step-7-offer-publication-commands).

**Comment by crevu** [comment]
Thank you Ania !
