### ISSUE TITLE
Problem ze zmianą cen przez zasób /sale/offer-price-change-commands/{commandId}

### ISSUE THREAD

**Issue by cptgoldd** [allegro/allegro-api#3110]
Dzień dobry,
Przy zmianie cen przez zasób /sale/offer-price-change-commands/{commandId}
często zdarza się, że znaczna część ofert nie zmienia ceny:

Command summary z zasobu: /sale/offer-price-change-commands/{commandId}
{
   "id":"4eeebf1e-e66b-4014-89b4-30511004007c",
   "taskCount":{
      "total":1000,
      "success":754,
      "failed":246
   }
}

Po sprawdzeniu szczegółów w zasobie: /sale/offer-price-change-commands/{commandId}/tasks
"errors":[
      {
         "code":"OfferImagesNotAvailableException",
         "message":"Cannot resolve offer images. Please retry.",
         "details":null,
         "path":null,
         "userMessage":"Cannot resolve offer images. Please retry."
      }
   ]

Nie rozumiem jakie znaczenie dla zmiany cen mają zdjęcia w szczególności że w podanym commandId wszystkie oferty mają prawidłowe zdjęcia oraz uzupełnione wszystkie inne parametry obowiązkowe. Problem wydaje się występować głównie jeśli zmieniam ceny dużej ilości ofert w krótkim czasie. 

Prosiłbym o wyjaśnienie na czym polega błąd. Czy należy po prostu próbować zmieniać ceny ofert dla których komenda nie zadziałała do skutku?

**Comment by PrzemyslawLukanowski** [comment]
Jest to ten sam problem opisany w #3093, pracujemy nad rozwiązaniem. Na tę chwilę możesz spróbować powtórzyć operację zmiany ceny.
