### ISSUE TITLE
Specyfikacja techniczna produktu

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#3112]
https://allegro.pl/oferta/monroe-amortyzator-fiat-citroen-t-ducato-express-8882516724

Jak działa to przypisanie do tecdoca (specyfikacja techniczna produktu)?

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) musisz na początku wyszukać interesujący Cię produkt. Następnie przez GET /sale/products/{productId} pobierz wszystkie dane produktu, w tym m.in. sekcje compatibilityList (pasuje do) i tecdocSpecification, które przekażesz w ofercie za pomocą POST lub PUT /sale/offers. Więcej na ten temat przeczytasz w [naszym poradniku](https://developer.allegro.pl/productization/).
