### ISSUE TITLE
Niezidentyfikowany błąd podczas próby dodania nowej oferty

### ISSUE THREAD

**Issue by amazur31** [allegro/allegro-api#3113]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ X] na portalu [allegro.pl.allegrosandbox.pl/](allegro.pl.allegrosandbox.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę wystawić nowej oferty ani nie mogę zedytować oferty wstawionej już wcześniej - sprawdzałem kilka razy i wszystkie pola są poprawnie uzupełnione. Podsłuchałem ruch Fiddlerem - to zwrotka którą dostaję po tym jak klikam na przycisk "WYSTAW PRZEDMIOT" na allegrosandbox

`HTTP/1.1 500 Internal Server Error
date: Wed, 22 Apr 2020 08:11:43 GMT
content-type: application/json; charset=utf-8
content-length: 48
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-content-type-options: nosniff
x-envoy-upstream-service-time: 111
x-waf: waf-1a
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000

{"errors":[{"code":"ERROR","userMessage":null}]}`

Błąd który wyskakuje na stronie allegrosandbox to 
`Podczas wznowienia oferty wystąpiły błędy`

**Comment by Onixarts** [comment]
500 Internal Server Error

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, odpowiedni zespół pracuje nad rozwiązaniem problemu.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by amazur31** [comment]
Działa.
