### ISSUE TITLE
SANDBOX WEB - nie działa

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#3114]
Występuje problem: 
 - [X] ze środowiskiem testowym
 - [ ] inny
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)

Problem z Webowym Sandboxem ? 
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty

naciskamy na wystaw  i mamy coś takiego : 

staging-lokalnie.allegrogroup.com. (nie istnieje)
https://staging-lokalnie.allegrogroup.com/oferty/wystaw

ww factory

**Comment by Onixarts** [comment]
API do sandboxa też leży, błąd 500.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że na tę chwilę na sandboxie występują błędy przy tworzeniu i edycji oferty. Odpowiedni zespół pracuje nad rozwiązaniem problemu.

@wwwfactory w przypadku strony internetowej, po usunięciu problemu, skorzystaj z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
