### ISSUE TITLE
[restAPI] Zmiana ilości  - offer-quantity-change-commands

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3115]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś od rana mamy sporo błedów takiej postaci

REQUEST 2020-04-22 08:12:30.8987084 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/0844ab69-3b4a-4c91-98ad-d090d9503c75' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  
RESPONSE 2020-04-22 08:12:30.9299249 Database: Duration: 31,2165ms
{
  "Data": {
    "Id": "0844ab69-3b4a-4c91-98ad-d090d9503c75",
    "TaskCount": {
      "Failed": 1,
      "Success": 0,
      "Total": 1
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "521da6215f6e027a",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

REQUEST 2020-04-22 08:12:30.9299249 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/0844ab69-3b4a-4c91-98ad-d090d9503c75/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-04-22 08:12:30.9611741 Duration: 31,2492ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2020-04-22T06:03:19.398Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "8100957132"
        },
        "ScheduledAt": "2020-04-22T06:03:19.311Z",
        "Status": "FAIL",
        "Errors": [
          {
            "Code": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
            "Details": null,
            "Message": "Exception when update offer quantity.",
            "Path": null,
            "UserMessage": "Błąd podczas zmiany liczby sztuk."
          }
        ]
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "6376f1bbf7370707",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do zespołu, który zajmie się analizą tych błędów.
