### ISSUE TITLE
doGetBidItem2 nie zwraca histori dla niektórych ofert

### ISSUE THREAD

**Issue by AZJAJ** [allegro/allegro-api#3118]
Występuje problem:
 - [X ] z metodą WebAPI
 - [X ] ze środowiskiem produkcyjnym

Pojawia się coraz więcej ofert dla których **nie można pobrać historii transakcji** z pomocą **doGetBidItem2** - nie zwraca błędu, ale też i nie daje listy transakcji (jest pusta), jakby nic nie było sprzedane, ale sprzedaż była i na bieżąco jej przybywa. W większości oferty są aktywne i przychodzą kolejne eventy `now`. W ciągu kilku godzin było to 140 ofert dla których pojawiło się ponad 250 eventów 'now`. Przykładowe id ofert objęte problemem: 9172510069, 9175624593, 9195132328, 9191734142. Jest też wiele ofert jakie aktualnie mają status ADM_KILLED, dla których był to przejściowy stan np: 9196414247, 9196425135, 9196425698

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdzam problem. Przekazałem go do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@AZJAJ Problem już nie powinien występować, prośba o potwierdzenie. 

> Jest też wiele ofert jakie aktualnie mają status ADM_KILLED, dla których był to przejściowy stan np: 9196414247, 9196425135, 9196425698

Jest to prawidłowe zachowanie, nie wykonywaliśmy żadnych zmian w tej kwestii.

**Comment by AZJAJ** [comment]
Dziękuję i potwierdzam, gdyż już wczoraj nie przybyło kolejnych tego typu problemów, a te co były problematyczne już dawały pobrać dla siebie historię transkacji.
Co do ofert ze statusem ADM_KILLED to było do wiadomości, gdyż było podobne w zachowaniu jako etap przejściowy i mogło pomóc Wam szybciej zlokalizować problem. Patrząc jednak na numery id domyślam się, że to dotyczyło tylko nowo utworzonych ofert.
