### ISSUE TITLE
Brak starego numeru transakcji w payment-id-mappings

### ISSUE THREAD

**Issue by fabMoth4n** [allegro/allegro-api#3119]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dla zdarzenia:

**b6f86fd2-84ea-11ea-85db-557a1af1fcb7**

próbuję pobrać  stare ID transakcji:

**payments/payment-id-mappings?paymentId=78a4aae2-84eb-11ea-94c5-fdf67e5c89e6**

gdzie paymentId jest pobrane bezpośrednio ze zdarzenia.

W odpowiedzi dostaję:

"Accept: application\/vnd.allegro.public.v1+json","Content-Type: application\/vnd.allegro.public.v1+json","Connection: close"
"HTTP\/1.1 404 Not Found","expires: 0","cache-control: no-cache, no-store, max-age=0, must-revalidate","x-xss-protection: 1; mode=block","server: envoy","pragma: no-cache","x-frame-options: DENY","trace-id: 59ffe075cbe6625c","date: Thu, 23 Apr 2020 09:55:11 GMT","x-content-type-options: nosniff","content-type: application\/vnd.allegro.public.v1+json;charset=UTF-8","content-length: 86","x-envoy-upstream-service-time: 63","connection: close"
{"message":"Transaction not found for paymentId=78a4aae2-84eb-11ea-94c5-fdf67e5c89e6"}

To jednorazowy problem czy wycofaliście stare ID transakcji?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować, w jakim celu wykorzystujesz transactionId? Wyłączyliśmy już wszystkie metody WebAPI, które korzystają z tej wartości.

**Comment by fabMoth4n** [comment]
Wy wyłączyliście, ale ja nadal korzystam ;-)
Ogólnie mam tony danych w bazie i klas, które używają tego numerycznego ID do identyfikacji płatności. Do samej komunikacji "raczej" nie jest używane.
Stąd moje pytanie: czy w ogóle przestajecie je zwracać? Bo jak tak to musze na szybko przepisać "trochę" kodu.

**Comment by PrzemyslawLukanowski** [comment]
Twój przypadek załapał się na wyjątek dla wybranych zamówień pobraniowych. Na tę chwilę numery jeszcze zwracamy, o planowanym wyłączeniu zasobu będziemy informować w osobnym komunikacie.
