### ISSUE TITLE
Odpowiedniki funkcji WebApi -> RestAPI

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#312]
Czy możecie napisać które teraz metody w RestAPI odpowiadają tym z WebAPI?

Interesują mnie w szczególności te do pobierania informacji o zamówieniach:
1. doGetSiteJournalDeals
2. doGetPostBuyFormsDataForSellers
3. doAddPackageInfoToPostBuyForm

**Comment by KrzysztofLukanowski** [comment]
W tej chwili nie udostępniamy takich odpowiedników w RestAPI. Zasoby odpowiadające wskazanym funkcjom WebAPI udostępnimy wkrótce.

**Comment by SoftWareMG** [comment]
A możecie mi napisać którym teraz endPointami mogę pobrać listę zamówień lub zamówienie oraz którym endPointem mogę zmienić status zamówienia na "Wysłane"? Czy to też jeszcze nie działa?

**Comment by KrzysztofLukanowski** [comment]
Tak jak napisałem, nie ma jeszcze takiej możliwości w REST API. Statusu zamówienia aktualnie nie zmienisz, zarówno przez WebAPI, jak i REST API.
