### ISSUE TITLE
Problem z dodawaniem numeru przesyłki

### ISSUE THREAD

**Issue by TomekDuszynski** [allegro/allegro-api#3120]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próba nadania numeru przesyłki do zamówienia przez zasób https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST za każdym razem kończy się błędem 404.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - zasób działa prawidłowo. Upewnij się proszę, że dany checkoutForm należy do zautoryzowanego użytkownika. Podaj nam przykładowe trace-id, jeśli mimo poprawnych danych nadal będziesz otrzymywać błąd.

**Comment by TomekDuszynski** [comment]
Trace ID z ostatniej próby: 7633cb2b5e58f6e9
Użytkownik jest odpowiedni.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem. Przepraszam, ale wcześniej byłem przekonany, że chodzi o środowisko produkcyjne. Już przekazuję problem do odpowiedniego zespołu.

**Comment by TomekDuszynski** [comment]
Wygląda na to że już działa. Dziękuję za szybką reakcję :)
