### ISSUE TITLE
sale/offers  createDraft Brak parametrów pól sprzedaży dla : Producent części(127415).

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#3121]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wywołaniu metody sale/offers i tworzeniu draftu REST API zwraca
"Assigned valueId  for dictionary parameter 127415 is not found."

Przy pobieraniu danych o polach sprzedaży 127415 występuje

REQUEST

 array(2) {
      ["id"]=>
      string(6) "127415"
      ["valuesIds"]=>
      array(1) {
        [0]=>
        string(8) "127415_3"
      }
    }

RESPONSE
 object(stdClass)#28 (4) {
      ["id"]=>
      string(6) "127415"
      ["valuesIds"]=>
      array(0) {
      }
      ["values"]=>
      array(0) {
      }
      ["rangeValue"]=>
      NULL
    }

i błąd

object(stdClass)#55 (2) {
    ["errors"]=>
    array(2) {
      [0]=>
      object(stdClass)#56 (5) {
        ["code"]=>
        string(16) "VALIDATION_ERROR"
        ["message"]=>
        string(63) "Assigned valueId  for dictionary parameter 127415 is not found."
        ["details"]=>
        string(0) ""
        ["path"]=>
        string(0) ""
        ["userMessage"]=>
        string(63) "Assigned valueId  for dictionary parameter 127415 is not found."
      }
      [1]=>
      object(stdClass)#57 (5) {
        ["code"]=>
        string(16) "VALIDATION_ERROR"
        ["message"]=>
        string(57) "No values given for parameter Producent części(127415)."
        ["details"]=>
        string(0) ""
        ["path"]=>
        string(0) ""
        ["userMessage"]=>
        string(57) "No values given for parameter Producent części(127415)."
      }
    }
    ["validatedAt"]=>
    string(24) "2020-04-23T14:10:21.116Z"
  }

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Błąd oznacza, że dla parametru 127415 nie możesz przekazać wartości 127415_3. Sprawdziłem wybrane kategorie w motoryzacji i potwierdzam, że nie ma takiej wartości. Możesz to zweryfikować za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by qshop123** [comment]
W takim razie jaką mam przekazać wartość dla tego parametru 127415?
Bo zgodnie z dokumentacją we wskazanym punkcie 

dla parametrów słownikowych (wybór jednego lub wielu wartości z wielu)
"id": "209878",
"valuesIds": [
	"209878_2",
	"209878_1"
],
"values": [],
"rangeValue": null

Analogicznie skoro 127415 posiada opcje
325161
323089

To patrząc na dokumentację mam przekazać
array(2) {
      ["id"]=>
      string(6) "127415"
      ["valuesIds"]=>
      array(1) {
        [0]=>
        string(8) "127415_3"
      }
    }
Czy może jestem w błędzie? Bo tak to działa dla innych kategorii a dla tej nie działa.

**Comment by qshop123** [comment]
W kwestii uzupełnienia, pobieram dane metodą 
sale/categories/4136/parameters

Parametr kategorii 4136 i dostaje paczkę 127415 a w niej dla producenta DEPO wartość "3" jak byk

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowa wartość to "127410_3". Zwróć uwagę, że początek wartości nie zawsze rozpoczyna się od identyfikatora parametru, w tym przypadku "127415".

**Comment by qshop123** [comment]
Jak widać coś co w innych systemach jest oczywiste u was musi być kompletnie poprzekręcane. 
Dopiszcie zatem informacje do dokumentacji https://developer.allegro.pl/sale/ że 
"Nie zawsze początek wartości zaczyna się od identyfikatora parametru"

Masakra.
