### ISSUE TITLE
Brak informacji sprzedażowych w zakończonych ofertach

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#3122]
Witam,
Od kilku (2?) dni zauważyłem brak informacji sprzedażowych dla zakończonych aukcji (tj brak informacji czy przedmiot został sprzedany oraz ile osób kupiło go w aukcjach wieloprzedmiotowych). 
Wywołując zasób offers/listing z searchMode na CLOSED dla frazy "Płyta główna APPLE IPHONE 7 128GB +Touch ID +Tacka" otrzymamy jedna aukcję 8992102897 zakończoną sprzedażą (sprzedawca ma wystawiony komentarz), ale popularity jest ustawione na  0, a available na 1.
 
"sellingMode": {
                    "format": "BUY_NOW",
                    "price": {
                        "amount": "549.00",
                        "currency": "PLN"
                    },
                    "popularity": 0
                },
                "stock": {
                    "unit": "UNIT",
                    "available": 1
                },
                "category": {
                    "id": "46779"
                }

**Comment by PrzemyslawLukanowski** [comment]
W przypadku 8992102897 popularity akurat się zgadza, nie było sprzedaży w ciągu ostatnich 30 dni. Zweryfikowałem jednak inne oferty i potwierdzam rozbieżność w informacjach. Przekazałem problem do odpowiedniego zespołu.

**Comment by dol1234** [comment]
Ta oferta została sprzedana, a mimo to zgodnie z odpowiedzią nadal dostępna jest jedna sztuka

**Comment by juhacz** [comment]
Chciałem zgłosić ten sam błąd.  W wyprzedanych ofertach "available" nie jest równe 0, choć powinno.

Przy okazji jak rozumieć "popularity" wg. opisu "Popularity of the offer for BUY_NOW selling format" czyli ilość sprzedanych ofert poprzez kup teraz?

**Comment by PrzemyslawLukanowski** [comment]
Dla ofert typu Kup teraz jest to liczba zakupów od unikalnych użytkowników w ciągu ostatnich 30 dni. Dla aukcji jest to liczba użytkowników, którzy biorą udział w licytacji.

**Comment by juhacz** [comment]
Dziękuję.

**Comment by dol1234** [comment]
Czy jest już może jakaś informacja kiedy zostanie to naprawione?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedni zespół pracuje nad rozwiązaniem problemu. Jak tylko uda się go rozwiązać, poinformuję w tym wątku.

**Comment by dol1234** [comment]
Problem nadal występuje. Jakiś przewidywany termin, kiedy zostanie to poprawione?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mogę wskazać takiego terminu. Poinformuję w tym wątku po rozwiązaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@dol1234 Problem został rozwiązany.

**Comment by juhacz** [comment]
Dlaczego dla oferty 9154276269 w której był do sprzedania jeden przedmiot i się sprzedał stock-> available wynosi 1? Nie powinien wynosi 0, skoro przedmiot się sprzedał?
Albo dla oferty 9017859371, gdzie były do sprzedania 2 szt. i obie się sprzedały stock-> available wynosi również 1 a nie 0? Chyba, że źle rozumiem wartość tego pola, jego opis to jedno zdanie "The available stock value".

**Comment by PrzemyslawLukanowski** [comment]
Weryfkujemy jeszcze problem z inną wartością dla stock.available.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Problem z wartością dla stock.available został rozwiązany.

**Comment by juhacz** [comment]
@PrzemyslawLukanowski  moim zdaniem nie został, teraz stock.available, teraz dla odmiany wszędzie równa się 0 :) Np. aukcja 9146293013 nie został sprzedany, a stock.available = 0

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, w zamkniętych ofertach, w których towar się nie wyprzedał, zwracamy wartość 0. Przekazałem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Wracam z odpowiedzią po konsultacji - 0 dla stock.available w zamkniętych ofertach to prawidłowa wartość, nie należy tego traktować jako błąd.

**Comment by juhacz** [comment]
@PrzemyslawLukanowski  Komedia :) To w takim razie, proszę mi podpowiedzieć, skąd mam wiedzieć, czy przedmiot z aukcji 9105913949 został sprzedany czy nie, bo otrzymuję takie coś:

`
[sellingMode] => Array
--
  | (
  | [format] => BUY_NOW
  | [price] => Array
  | (
  | [amount] => 999.00
  | [currency] => PLN
  | )
  |  
  | [popularity] => 0
  | )
  |  
  | [stock] => Array
  | (
  | [unit] => UNIT
  | [available] => 0
  | )
  |  
  | [category] => Array
  | (
  | [id] => 110698
  | )
  |  
  | [publication] => Array
  | (
  | [endingAt] => 2020-04-15T09:09:57.000Z
  | )
`

czyli popularity = 0 i stock.available = 0, a lampa oczywiście została sprzedana.

**Comment by PrzemyslawLukanowski** [comment]
W kwestii sprzedaży powinieneś sugerować się polem popularity, w którym widnieje sprzedaż z ostatnich 30 dni. Wartość stock.available to liczba aktualnie dostępnych przedmiotów -  oferta jest zakończona, nie da się jej kupić, więc liczba dostępnych przedmiotów (do kupienia) to zero.

**Comment by juhacz** [comment]
@PrzemyslawLukanowski  to się kupy nie trzyma, albo nie działa. Proszę dowiedz się jak naprawdę jest i wróć z odpowiedzią.

`
**oferta niesprzedana**

            [id] => 9102682189
            [name] => Nikon D7100, stan bardzo dobry, przebieg 96000
            
            [sellingMode] => Array
                (
                    [format] => BUY_NOW
                    [price] => Array
                        (
                            [amount] => 1350.00
                            [currency] => PLN
                        )

                    [fixedPrice] => Array
                        (
                            [amount] => 1500.00
                            [currency] => PLN
                        )

                    [bidCount] => 0
                )

            [stock] => Array
                (
                    [unit] => UNIT
                    [available] => 0
                )

            [category] => Array
                (
                    [id] => 257933
                )

            [publication] => Array
                (
                    [endingAt] => 2020-04-05T12:12:01.000Z
                )
                
                
**oferta sprzedana**
                
                
                 [id] => 9198174022
            [name] => LUSTRZANKA NIKON D7100 BODY CZARNY
            
            [sellingMode] => Array
                (
                    [format] => BUY_NOW
                    [price] => Array
                        (
                            [amount] => 999.00
                            [currency] => PLN
                        )

                    [popularity] => 0
                )

            [stock] => Array
                (
                    [unit] => UNIT
                    [available] => 0
                )

            [category] => Array
                (
                    [id] => 257933
                )

            [publication] => Array
                (
                    [endingAt] => 2020-04-23T15:29:21.000Z
                )
                `

Proszę powiedz mi, skąd mam wiedzieć w swoim programie która oferta została sprzedana?


Czy jeśli popularity oznacza, sprzedaż w ciągu ostatnich 30 dni, a w drugiej ofercie minęło już ponad 30 dni, towar się sprzedał, to będzie tam 0, jeśli program uruchomił przed 23 majem byłoby tam 1? 

Jeśli tak to działa, to jestem w stanie sprawdzić tylko sprzedaż w ciągu 30 dni od zakończenia? Przez kilka miesięcy (lat) było ok, kiedy stock.avalible pokazywało wartość, czy coś zostało do sprzedaży, czy nie, raptownie po tym czasie stock.avalible zaczęło oznaczać coś innego. Ogarnijcie to, tak aby było wiadomo o co chodzi.

**Comment by PrzemyslawLukanowski** [comment]
Temat z wartością dla stock.available analizuję jeszcze z odpowiednim zespołem, wrócę z odpowiedzią. Co do

> Czy jeśli popularity oznacza, sprzedaż w ciągu ostatnich 30 dni, a w drugiej ofercie minęło już ponad 30 dni, towar się sprzedał, to będzie tam 0, jeśli program uruchomił przed 23 majem byłoby tam 1?

Tak, jeśli minęło 30 dni od ostatniego zakupu i niekt nie zakupił przedmiotu, zwrócimy tam 0. Jeśli wysłałbyś request przed 23 maja i w ciągu 30 dni wstecz od tej daty w ofercie byłby jakiś zakup, zwrócilibyśmy wartość dodatnią (w zależności od liczby ofert kupna).

**Comment by juhacz** [comment]
@PrzemyslawLukanowski czy nie uważasz, że jest to bezsensowne? Sprawdzając zakończone aukcje, sprawdzam po to, aby dowiedzieć się za ile jestem w stanie coś sprzedać i czy w ogóle jestem w stanie. Mogę sprzedawać rzecz kupioną 5 czy 20 lat temu i sprawdzając to nie interesuje mnie wyłącznie ostatnie 30 dni, ale cały okres dostępny w Allegro. Przywróćcie działanie tej metody, tak aby działała tak jak do momentu sprzed awarii, bo działa poprawnie. Niech stock =0 tylko i wyłącznie wtedy o ile się wyprzedało. Proszę potraktuj to jako sugestię i przekaż do ludzi którzy mają na to wpływ.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Będziemy to poprawiać, poinformuję o tym w tym wątku. Przepraszam za wcześniejszą informację, która wprowadziła w błąd.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Wprowadziliśmy odpowiednią poprawkę.

**Comment by juhacz** [comment]
@PrzemyslawLukanowski , możesz napisać co masz na myśli mówiąc o poprawce? Wg. mnie nic się nie zmieniło. Oferta 9304818530 się nie sprzedała, response wygląda tak:
```

 [stock] => Array
                (
                    [unit] => UNIT
                    [available] => 0
                )

            [category] => Array
                (
                    [id] => 257933
                )

            [publication] => Array
                (
                    [endingAt] => 2020-06-03T17:49:26.000Z
                )


```

czyli stock.avalible wynosi 0, a nie powinno.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem tę ofertę i zwracamy dla niej prawidłową wartość 

```
"stock": {
                    "unit": "UNIT",
                    "available": 1
                },
```

**Comment by juhacz** [comment]
Stan z godziny 9:25 10.06.2020

```
(
		[unit] => UNIT
		[available] => 0
	)

[category] => Array
	(
		[id] => 257933
	)

[publication] => Array
	(
		[endingAt] => 2020-06-03T17:49:26.000Z
	)
```

**Comment by PrzemyslawLukanowski** [comment]
Analizujemy jeszcze ten przypadek, wrócę z odpowiedzią. Dla zamkniętych ofert typu Kup teraz zwracamy już prawidłową wartość w tym polu.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Aktualnie wszystko powinno już funkcjonować prawidłowo. Prośba o potwierdzenie.

**Comment by juhacz** [comment]
Żeby to sprawdzić muszę wiedzieć, co konkretnie oznacza popularity dla zakończonych ofert. Bo jeżeli to co kiedyś, czyli ilość ofert w licytacji dla aukcji i ilość kupiony w ofertach kup teraz. To nie działa poprawnie, bo znalazłem 2 oferty w których jest błąd:

[id] => 9131624093
[sellingMode] => Array
		(
			[format] => BUY_NOW
			[price] => Array
				(
					[amount] => 2100.00
					[currency] => PLN
				)
			[popularity] => 0
		)
	[stock] => Array
		(
			[unit] => UNIT
			[available] => 1
			)


[id] => 8940460949
[sellingMode] => Array
			(
				[format] => BUY_NOW
				[price] => Array
					(
						[amount] => 1493.00
						[currency] => PLN
					)
				[popularity] => 0
			)
		[stock] => Array
			(
				[unit] => UNIT
				[available] => 1
			)

Dwie oferty są sprzedane, rest api zwraca to co powyżej, czyli nie sprzedane. 

Jeżeli wprowadziliście modyfikację, gdzie można uzyskać tylko informacje o sprzedaży z ostatnich 30 dni, to pewnie jest ok, bo te oferty zakończyły się ponad 30 dni temu. Ale w takim razie jest to idiotyczne posuniecie, ponieważ rest api nie odzwierciedla tego co można uzyskać na froncie.

Tak jak pisałem wcześniej, jeśli ktoś szuka informacji za jaką cenę może np. sprzedać jakąś rzadką monetę czy obraz, czy płytę vinylową nie obchodzi go tylko ostatni miesiąc, ale cały dostępny okres. Dlatego powinniście to poprawić, bo choćby na przykładzie 2 powyższych aukcji NIE MA MOŻLIWOŚCI sprawdzenia sprzedaży z poziomu api dla tego przedmiotu.

**Comment by PrzemyslawLukanowski** [comment]
Poprawka dotyczy wartości w polu stock.avaiable w zakończonych ofertach dla niesprzedanych przedmiotów. Dla tych ofert widnieje wartość 1 i jest ona prawidłowa - zakup przedmiotów odbył się w marcu i kwietniu, następnie stock został zaktualizowany +1 i od tego momentu nie było ofert kupna. W polu popularity zwracamy informację o sprzedaży z ostatnich 30 dni. Co masz na myśli przez "nie odzwierciedla tego co można uzyskać na froncie."? Zarówno w:
 - [wynikach wyszukiwania ](https://allegro.pl/zakonczone?string=NIKON%20D7200%202X32%20GB%20NIKKOR%20TAMRON&bmatch=baseline-al-product-cl-eyesa2-engag-dict45-uni-1-3-0605),
 - jak i na [stronie zakończonej oferty ](https://allegro.pl/oferta/nikon-d7200-2x32-gb-nikkor-tamron-9131624093)

nie zwracamy informacji o ofertach kupna z przeszłości.

**Comment by juhacz** [comment]
W skrócie, mam na myśli to, że nie mogę uzyskać informacji, że oferty 9131624093 i 8940460949 zostały sprzedane. API twierdzi, że nie, strona Allegro twierdzi, że tak. Wszystko kiedyś działało prawidłowo, ktoś "łapy  wsadził" i popsuł.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za odpowiedź, ale czy mógłyś doprecyzować, w którym miejscu na stronie widzisz informację, że oferty zostały sprzedane?

**Comment by juhacz** [comment]
Kiedy wchodzę na zakończona ofertę i widzę "Sprzedaż zakończona" domniemywam, że towar się wyprzedał, jeśli wchodzę na ofertę zakończoną, która się nie wyprzedała widzę: "Sprzedaż zakończona. Nie było ofert kupna"

Oferta  9131624093  sprzedała się 2020-04-27 13:08:59
Oferta 8940460949 sprzedała się  2020-03-14 17:27:19

**Comment by PrzemyslawLukanowski** [comment]
Dla tych ofert nie ma takiego dopisku, ponieważ sprzedały się w podanych przez Ciebie dniach. Następnie sprzedawca zaktualizował stock.available na 1, dlatego taką wartość zwracamy w tym polu i widnieje ona również na froncie. W polu popularity zawsze zwracaliśmy informację o sprzedaży z ostatnich 30 dni.

**Comment by juhacz** [comment]
Co oznacza, że "sprzedawca zaktualizował stock.available na 1"?  Jak on to zrobił, gdzie kliknął, co przez to rozumiesz? Oznacza, to, że wystawił jeszcze raz przedmiot na sprzedaż, czy co?

Sprawdzając zakończone oferty, widzę, że oferta była tylko raz wystawiona i się sprzedała, więc na zdrowy rozum stock avalible powinien wynosić 0.

https://allegro.pl/zakonczone?string=NIKON%20D7200%202X32%20GB%20NIKKOR%20TAMRON&bmatch=baseline-al-product-cl-eyesa2-engag-dict45-uni-1-3-0605

**Comment by PrzemyslawLukanowski** [comment]
Wykonał operację zmiany liczby przedmiotów przez API za pomocą jednego z dostępnych zasobów:
- PUT /sale/offers/{id}, 
- PUT /sale/offer-quantity-change-commands/{commandId}

I jest tak jak napisałeś - oferta 9131624093 mimo to nie została ponownie wystawiona.

**Comment by juhacz** [comment]
Rozumiem. Dziękuję za wyjaśnienie. 
Trochę to wszystko jest pomieszane, od której strony bym nie podszedł, nie jestem w stanie napisać programu, który jednoznacznie pokaże mi, za ile został sprzedany dany przedmiot na Allegro.  Bo albo mam dostęp do danych z ostatnich 30 dni (a aukcje zakończone są dostępne dłużej) , albo jeśli ktoś za pomocą API zwiększy stan towaru tak jak powyżej, do dane zwracane przez api, są niewiarygodne.
