### ISSUE TITLE
[sandbox] - odbiór w punkcie UPS

### ISSUE THREAD

**Issue by tommy-bear** [allegro/allegro-api#3123]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://allegro.pl.allegrosandbox.pl/](https://allegro.pl.allegrosandbox.pl/)
 - [ ] inny

📦 Na formularzu dostawy i płatności nie można wybrać dostawy w punkcie UPS.
Mapka do wyboru punktów się wyświetla. Jednak punky UPS nie pojawiają się przy wybranym filtrze "Punkt UPS". Są natomiast widoczne, gdy wybierze się filtr "Pokaż wszystkie".
Wybranie punktu nie powoduje pozytywnej akcji w formularzu dostawy.
Niemożliwe jest złożenie zamówienia z taką metodą dostawy.

- problem występuje przy próbie zakupu zalogowanego i niezalogowanego użytkownika.
- występuje dla dostawy "UPS Odbiór w Punkcie" i "Allegro UPS Odbiór w Punkcie"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za precyzyjny opis zgłoszenia. Zweryfikowałem to i potwierdzam problem. Przekazuję to do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@tommy-bear Problem już nie występuje.
