### ISSUE TITLE
Allegro Order Issue

### ISSUE THREAD

**Issue by Shubham-ebus** [allegro/allegro-api#3125]
Hello Team,

This is Shubham from eBusiness Guru.

I am raising an issue on behalf of my client who is using your channel.

We are trying to download the order via API integration but it is returning the below error.
Error: "Access denied. Contact the author of the application

Here is the Request|Response for that orders.

Can you please check this why it is happening?

Kind Regards,
Shubham

**Comment by PrzemyslawLukanowski** [comment]
Hi

You should use valid resource for managing orders - [GET /order/checkout-forms/{checkout-form-id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET).
