### ISSUE TITLE
Problem z płatnością w sandboxie

### ISSUE THREAD

**Issue by Przem4S** [allegro/allegro-api#3127]
Jest jakiś problem z płatnościami w sandboxie?
Złożyłem kilka, oczekiwałem płatności poprawnej, wisi natomiast na rozpoczętej.

![obraz](https://user-images.githubusercontent.com/37654401/80217858-ac99a200-8640-11ea-8cb6-1feb1e495d81.png)

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdzam problem. Przekazałem informację do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
Problem na tę chwilę nie powinien już występować.

**Comment by Przem4S** [comment]
Potwierdzam i zamykam.
