### ISSUE TITLE
{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessag

### ISSUE THREAD

**Issue by awuhuan** [allegro/allegro-api#3128]
Występuje problem: 
 - [1 ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hello, I want to create a draft. Only one name parameter is passed, but an error will be reported after the post request. The error message is 

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

Reference example:    https://developer.allegro.pl/sale/#7-draft-oferty

**Comment by PrzemyslawLukanowski** [comment]
Could you please send us your request (without token)? Did you erase the text- "-- wymagane, tytuł oferty" ("-- required, offer title")?
