### ISSUE TITLE
Pobieranie informacji o zwrotach (odstapienie od umowy)

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#3129]
Witam kiedy będzie dostępny powyższy zasób?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie możemy tego określić. Poinformujemy kiedy będziemy mogli podzielić się szczegółami.

**Comment by Przem4S** [comment]
Podpinam się, temat przewija się już długo i pozostaje bez echa.

**Comment by kylovile** [comment]
Dzień dobry,

nam również by bardzo zależało o informacji o odstąpieniach od umowy. Klienci chętnie korzystają z tej możliwości, nawet po kilku minutach od samego zakupu.
Czy jest możliwość wskazania terminu realizacji zasobu umożliwiającego pobranie odstąpień?

**Comment by MaciejFrackowiak** [comment]
@kylovile Na chwilę obecną nie mogę wskazać jednoznacznego terminu wdrożenia zasobów do obsługi zwrotów klienckich - mamy to na naszej liście dot. rozwoju REST API Allegro.
