### ISSUE TITLE
[RestAPI][OrderCheckout] Błąd 404

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3130]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy pobieraniu transakcji dla jednej w nocy dostaliśmy błąd

REQUEST 2020-04-25 02:53:37.3669443
curl -X GET \
  'https://api.allegro.pl/order/checkout-forms/35abbe62-868d-11ea-abda-9d8dd4503d0d' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-04-25 02:53:37.3982229  Duration: 31,2786ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "CheckoutFormNotFoundException",
        "Details": null,
        "Message": "checkout form of id 35abbe62-868d-11ea-abda-9d8dd4503d0d not found",
        "Path": "/order/checkout-forms/35abbe62-868d-11ea-abda-9d8dd4503d0d",
        "UserMessage": null
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (404) Not Found.",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at System.Net.HttpWebRequest.GetResponse()\r\n   at 
  "TraceId": "5ed4773c33e6cf43",
  "Error": true,
  "StatusCode": 404,
  "Message": "{\"errors\":[{\"code\":\"CheckoutFormNotFoundException\",\"message\":\"checkout form of id 35abbe62-868d-11ea-abda-9d8dd4503d0d not found\",\"details\":null,\"path\":\"/order/checkout-forms/35abbe62-868d-11ea-abda-9d8dd4503d0d\",\"userMessage\":null}]}"
}

Proszę o weryfikacje i odpowiednie poprawki

**I to samo z dziś dla innego checkoutform:** 
35abbe60-868d-11ea-abda-9d8dd4503d0d dla transakcji: 03e615f1-868e-11ea-9331-43ca3da62b5f (status: Ready_for w dzienniku)

TraceId: fc9c011bd0677868
{
    "errors": [
        {
            "code": "CheckoutFormNotFoundException",
            "message": "checkout form of id 35abbe60-868d-11ea-abda-9d8dd4503d0d not found",
            "details": null,
            "path": "/order/checkout-forms/35abbe60-868d-11ea-abda-9d8dd4503d0d",
            "userMessage": null
        }
    ]
}

**Comment by Maczuga** [comment]
Taki sam błąd u nas, występuje od 26 kwietnia od godziny 17:20.
Checkout ID 65887352-87d0-11ea-bbe8-d953a1f65951

**Comment by MaciejFrackowiak** [comment]
W tym przypadku było to prawidłowe zachowanie mechanizmu - ten sam kupujący o 2:46 dokonał płatności łącznej za 2 produkty - nowy id zamówienia: 03e615f1-868e-11ea-9331-43ca3da62b5f

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak  404 jest dla nowego id zamówienia, właśnie tego:  03e615f1-868e-11ea-9331-43ca3da62b5f

Checkout form id = 35abbe60-868d-11ea-abda-9d8dd4503d0d 
TraceId: fc9c011bd0677868
{
"errors": [
{
"code": "CheckoutFormNotFoundException",
"message": "checkout form of id 35abbe60-868d-11ea-abda-9d8dd4503d0d not found",
"details": null,
"path": "/order/checkout-forms/35abbe60-868d-11ea-abda-9d8dd4503d0d",
"userMessage": null
}
]

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba 35abbe62-868d-11ea-abda-9d8dd4503d0d to pierwotne id zamówienia, które zmieniło się na 03e615f1-868e-11ea-9331-43ca3da62b5f z uwagi na łączony zakup.
GET /order/checkout-forms/03e615f1-868e-11ea-9331-43ca3da62b5f zwraca poprawnie dane - status 200.

**Comment by MaciejFrackowiak** [comment]
@Maczuga Wymienione przez Ciebie zamówienie zostało zastąpione nowym - id "3f844891-87d1-11ea-90cf-b337e7e89177" na skutek kolejnego zakupu i łączonej płatności kupującego.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak coś jest jednak nie tak, w ramach testu pobrałem wszystkie READY FOR i FILLED IN
Nie ma w niej transakcji o której mówisz: 03e615f1-868e-11ea-9331-43ca3da62b5f, zrobiłem to przed chwilą

  "TraceId": "20f2a42608d799cb",

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Nie potwierdzam - dla GET /order/events?type=FILLED_IN&from=1587771200000000 otrzymuje event z wpisem:

```
"checkoutForm": {
                    "id": "03e615f1-868e-11ea-9331-43ca3da62b5f"
```

Oczywiście dla RFP w filtrze również.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak sprawdzę ponownie

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak zamykam, to u nas błąd w przypadku łączonej wpłaty
