### ISSUE TITLE
RestApi środowisko testowe allegrosandbox

### ISSUE THREAD

**Issue by GrzegorzLewinski** [allegro/allegro-api#3131]
Występuje problem: RestApi środowisko testowe allegrosandbox
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem testowym

Witam. Czy na środowisku testowym allegrosandbox dokonywane są jakieś prace ? 
Dodane oferty za pośrednictwem RestApi pozostają w szkicach, aktualizacja również nie zmienia statusu oferty. 
Dodatkowo próba ręcznego dodania oferty poprzez stronę allegro.pl.allegrosandbox.pl przenosi na adres "https://staging-lokalnie.allegrogroup.com/oferty/wystaw".
Natomiast zakończenie aukcji za pośrednictwem RestApi nie przynosi oczekiwanego efektu.

**Comment by MaciejFrackowiak** [comment]
Zacznę od drugiej kwestii - formularz dostępny jest pod adresem: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

Natomiast odnośnie zmiany statusu oferty - proszę podaj mi przykładowy nr oferty lub commandId, wówczas sprawdzę dane.

**Comment by GrzegorzLewinski** [comment]
Błąd z adresem formularza zauważyłem przez przypadek. Wspomniałem o nim gdyż przycisk "Dodaj nową" przenosi pod nie właściwy url.

ID produktu na Allegro 6207300851 -> produkt został już zaktualizowany ręcznie poprzez edycje oferty na Allegro i wystawienie przedmiotu z poziomu podstrony.

ID produktu na Allegro 6207301473 -> produkt został wystawiony przed chwilą, produkt utknął w szkicach.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykłady - to ten sam problem, który został zgłoszony w poście #3132 - analizujemy źródło problemu.
