### ISSUE TITLE
Metoda doGetItemsInfo - pytanie o EAN

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#3135]
Witam,
Metoda doGetItemsInfo zwraca dwa pola:
itEan w strukturze itemInfo 
oraz itEan | int Kod EAN zdefiniowany dla danej oferty - zwracany na końcu struktury.
Przy tym pierwszym jest informacja, że oferta zwraca tylko EAN dla własnych aukcji. Przy tym ostatnim nic nie jest napisane. Czy jest opcja pobrania EAN dla publicznych ofert z public access token?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie metody - kod EAN zwracany jest tylko w itemInfo.

**Comment by artzie92** [comment]
Czyli publicznie nie ma opcji dostępu do EAN? Planujecie to wdrożyć w pobieraniu publicznym oferty w REST? Kiedy taka ewentualnie metoda zostanie udostępniona?

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [harmonogramem](https://developer.allegro.pl/schedule/) informacje dot. zasobu REST API pojawią się w III kwartale 2020. Natomiast z WebAPI otrzymasz tylko EAN swoich ofert.
