### ISSUE TITLE
irrelevant search

### ISSUE THREAD

**Issue by wwwreptile** [allegro/allegro-api#3136]
Hello,   

Problem with irrelevant search

for "nowe"
https://allegro.pl/kategoria/czesci-i-akcesoria-motocyklowe-czesci-motocyklowe-158?string=Suzuki%20RF%20400&bmatch=baseline-al-product-cl-eyesa2-engag-dict43-aut-1-2-0318&stan=nowe

for "używane"

https://allegro.pl/kategoria/czesci-i-akcesoria-motocyklowe-czesci-motocyklowe-158?string=Suzuki%20RF%20400&bmatch=baseline-al-product-cl-eyesa2-engag-dict43-aut-1-2-0318&stan=u%C5%BCywane

especially many irrelevant offers for "nowe".   The same output in the API .

How to fix it?

**Comment by MaciejFrackowiak** [comment]
Please, look into screen -> 
![Suzuki RF 400 ](https://user-images.githubusercontent.com/53566763/80452133-e4953380-8925-11ea-9a79-0749a8a878da.png) - I checked the box which says that search results include information about matching vehicles entered by the seller - [Compatibility List](https://developer.allegro.pl/en/compatibility_list/) option is responsible for that.

**Comment by wwwreptile** [comment]
How to get this "Compatibility List"  when requesting offer information from API?

**Comment by MaciejFrackowiak** [comment]
It is available only for seller using [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
