### ISSUE TITLE
Problem z masową edycją ofert sandbox

### ISSUE THREAD

**Issue by bherczyk** [allegro/allegro-api#3137]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Metoda PUT sale/offer-modification-commands/951502e1-25b0-410d-9f45-24ff9d50335e
Zwraca:
    "id": "951502e1-25b0-410d-9f45-24ff9d50335e",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
traceId: e943bf32c13dbb33

Następnie metoda GET /sale/offer-modification-commands/951502e1-25b0-410d-9f45-24ff9d50335e/tasks
Zwraca:"tasks": []

traceId: 65f0acb23763865d

**Comment by MaciejFrackowiak** [comment]
Zgłoszony przez Ciebie problem był tożsamy z opisanym w poście GH #3132 - obecnie funkcjonalność już działa prawidłowo.
