### ISSUE TITLE
AccessDenied w /sale/offer-variants/

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#3138]
Problem, ze skryptem, który zawsze działał i nagle zwraca tablicę jak poniżej. Ktoś / coś :( ?

```
Array
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => AccessDenied
                    [message] => Access is denied
                    [details] => 
                    [path] => 
                    [userMessage] => Access denied. Contact the author of the application.
                )

        )

)
```

**Comment by shivson1337** [comment]
@partyumarty zweryfikuj czy masz prawidłowe tokeny dostępu. W naszym rozwiązaniu po kilku miesiącach działania i bezproblemowego odświeżania, nagle wygasły tokeny kilku kont. Możliwe, że u Ciebie wygląda to podobnie.

**Comment by MaciejFrackowiak** [comment]
Problem powiązany jest z wyłączeniem wersji beta, o czym informowaliśmy w poście GH #3082.
Przejdź proszę na wersję public.

**Comment by partyumarty** [comment]
> 
> 
> Problem powiązany jest z wyłączeniem wersji beta, o czym informowaliśmy w poście GH #3082.
> Przejdź proszę na wersję public.

Dziękuję, to faktycznie ten problem.
