### ISSUE TITLE
2 konta allegro / kopiowanie ofert

### ISSUE THREAD

**Issue by akwiecien3v** [allegro/allegro-api#3139]
hej, nie znam sie na programowaniu, ale potrzebuję jednej rzeczy którą w prosty i łatwy sposób będę mógł uzyskać tutaj....

Chciałbym w 100% skopiować ofertę z jednego konta allegro i wstawić ją do drugiego konta allegro.

Da się to prosto i sprawnie zrobić?

Dziękuję za pomoc.

Adrian 
512183293

**Comment by MaciejFrackowiak** [comment]
Jest to możliwe, pod warunkiem, że konto A i B należy do Ciebie.
Na koncie A pobierasz ofertę zasobem [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), a następnie pobrane dane przekazujesz na koncie B poprzez [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST). Oczywiście musisz w tym momencie podmienić na właściwe dla konta B identyfikatory cennika dostawy, warunków zwrotów, reklamacji.
Spójrz do naszych poradników, gdzie opisujemy proces [wystawiania oferty](https://developer.allegro.pl/sale/) oraz [zarządzania ofertami](https://developer.allegro.pl/my_offers/).

**Comment by akwiecien3v** [comment]
Super! To mi baaardzo ułatwi i usprawni pracę!
Może są jakieś filmiki instruktażowe?
Kompletnie nie wiem gdzie i jak wpisywać te kody.

**Comment by shivson1337** [comment]
@akwiecien3v jeżeli nie masz żadnej wiedzy programistycznej to wątpię, że będziesz w stanie wykonać taki zabieg samodzielnie.

Najlepiej będzie poszukać kogoś kto podejmie się tego zadania po godzinach.

**Comment by akwiecien3v** [comment]
Nie ma jakieś instrukcji? 
Może jest ktoś kto mógłby mi to zdalnie pokazać? 
Muszę ok 300 ofert skopiować na inne konto. Robienie aukcji od początku to masakra.

**Comment by MaciejFrackowiak** [comment]
@akwiecien3v Na rynku jest dużo gotowych rozwiązań pozwalających na wykonanie takiej operacji - z naszej strony tj. Allegro nie rekomendujemy żadnych konkretnych. Jak wspomniał @shivson1337 by samemu to wykonać trochę umiejętności potrzebnych jest. Możliwe, że cenne porady dla Ciebie przedstawią także inny użytkownicy forum.
