### ISSUE TITLE
Generowanie klucza WebAPI

### ISSUE THREAD

**Issue by Mesiek1000** [allegro/allegro-api#314]
Witam!
Zarejestrowałem nowe konto na sandboxie o takich samych danych jak mam moje główne konto allegro. Podczas tworzenia konta poproszono mnie o podanie numeru telefonu w celu weryfikacji użytkownika. Powinienem otrzymać kod zwrotny lecz nic nie otrzymałem. Prawdopodobnie dlatego nie mogę wygenerować kluba WebAPI. Co można w tym przypadku zrobić, czy trzeba czekać na ręczną aktywację?

**Comment by KrzysztofLukanowski** [comment]
Cześć, aby korzystać z WebAPI na środowisku testowym nie musisz podawać numeru telefonu. Ważna jest pełna aktywacja konta, najprawdopodobniej to jest problemem. Podaj proszę nazwę Twojego konta.

**Comment by Mesiek1000** [comment]
Konto było rejestrowane pod mailem: marek.michalczyk@ampmedia.pl

**Comment by KrzysztofLukanowski** [comment]
Uzupełnij [dane adresowe](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) i przejdź pełną aktywację konta, zgodnie ze [sugestią](https://allegro.pl/webapi/general.php):

> Pamiętaj, by podczas aktywacji podać rzeczywiste dane adresowe. Czyli taki kod pocztowy, ulicę i miasto, które do siebie pasują, np:

    ulica: Grunwaldzka 182,
    kod pocztowy: 60-166,
    miasto: Poznań.

**Comment by Mesiek1000** [comment]
Dane zostały uzupełnione. Czekam na aktywację.

**Comment by KrzysztofLukanowski** [comment]
Pod adresem, który podlinkowałem w poście wyżej, znajdziesz zakładkę "Aktywacja konta". Przeklikaj się proszę.

**Comment by SoftWareMG** [comment]
Witam, 
Również potrzebuje o aktywacje konta na sandboxie,
(Status konta Nieaktywne - trwa weryfikacja Twoich danych.)
mg-software

**Comment by KrzysztofLukanowski** [comment]
Konto jest już aktywne.

**Comment by Mesiek1000** [comment]
Gdy próbuję uzyskać dane (klucz WebAPI) na koncie sandbox otrzymuję informację: 

> Połączyliśmy generowanie kluczy dostępowych dla WebAPI i REST API
> Wszystkie niezbędne dane, dzięki którym skorzystasz z Allegro API, uzyskasz tutaj: https://apps.developer.allegro.pl.

Przechodzę pod podany link i nie mogę się zalogować pod marek.michalczyk@ampmedia.pl, gdyż taki użytkownik nie istnieje. Więc jak otrzymać wymagany klucz?

**Comment by KrzysztofLukanowski** [comment]
@Mesiek1000 problem jest z przekierowaniem, z sandboxa kierujemy na produkcję, a powinieneś zalogować się na stronie pod adresem https://apps.developer.allegro.pl.allegrosandbox.pl/ (wkrótce poprawimy przekierowanie)

Szczegółowe informacje na temat środowiska testowego znajdziesz również na [portalu developerskim](https://developer.allegro.pl/about/#Sandbox).
