### ISSUE TITLE
Problem z wygenerowaniem "device_code" (Python)

### ISSUE THREAD

**Issue by pstryczke** [allegro/allegro-api#3140]
Witam,
mam problem z wygenerowaniem "device_code", potrzebnym do uzyskania tokenu dostępowego. Przy wysyłaniu requestów otrzymuję błąd 400 z odpowiedzią:
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/device","userMessage":null}]}`

Requesty wywołuje poprzez funkcję Pythona:

    `def get_auth_token(self):
        string = f"{self.client_id}:{self.client_secret}"
        auth = b64encode(string.encode())
        payload = {'Authorization': f"Basic {auth.decode()}",
                   'Content-Type': 'application/x-www-form-urlencoded'}
        r = requests.post(self.allegro_auth, headers=payload)
        print(r.text)
        print(r.url)
        print(r)`

**Comment by MaciejFrackowiak** [comment]
Proszę zajrzyj na [stronę](https://requests.readthedocs.io/en/master/user/authentication/#digest-authentication) - istotne byś przekazał ClientID oraz Client Secret jak w podanym requeście, ponieważ wygląda to jakbyś dekodował go przed wrzuceniem w nagłówek.

**Comment by pstryczke** [comment]
ClientID oraz Client Secret koduję do base64 razem z ":" między nimi, dekodowanie w payload dotyczy zamiany postaci stringa z binarnej na ascii, bo myślałem że to może powodować problemy. W podanym linku dla funkcji HTTPBasicAuth nie mogę wprowadzić pojedynczej zmiennej, a przy wprowadzeniu ClientID jako username, a Client Secret jako password, nie mogę ich zakodować do base64. Jak rozumiem, przy odpowiednio skonstruowanym linku, po wywołaniu requesta powinnienem bez problemu otrzymać prawidłowy response? Możliwe, że problem leży w źle skonstruowanym przeze mnie zapytaniu.

**Comment by MaciejFrackowiak** [comment]
Do HTTPBasicAuth przekazujesz Client ID i Client Secret, a kodowaniem - dodaniem dwukropka zajmuje się już biblioteka.

Spróbuj z poniższym kodem:

```
response = requests.post("https://allegro.pl/auth/oauth/token?grant_type=client_credentials", auth=HTTPBasicAuth(self.client_id, self.client_secret))
```

Komenda wyżej powinna zadziałać bez ręcznego budowania nagłówka "authorization".

**Comment by pstryczke** [comment]
Dziękuję bardzo za pomoc, rzeczywiście ten request zadziałał.

śr., 29 kwi 2020 o 09:09 MaciejFrackowiak <notifications@github.com>
napisał(a):
