### ISSUE TITLE
Logowanie do konta

### ISSUE THREAD

**Issue by themikmas** [allegro/allegro-api#3141]
Klient twierdzi, że "nagle" przestało mu działać importowanie do programu do obsługi sprzedaży. Stosuje stary WebApi, ale nie dał się przekonać na przejście na nowe, więc póki muszę wycisnąć max co może być.
Wywoływany jest:
client.doMyAccount2(varSession, "sold", intOffset, varTMP, 25)  'sell
i faktycznie doMyAccount2 zostało wycofane, więc ciężko żeby działało. Jest dostępna alternatywna metoda, żeby tanim kosztem podmienić?

**Comment by MaciejFrackowiak** [comment]
Przez WebAPI nie obsłużysz już zakładek Moje Allegro. W REST API odpowiada za to zasób [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - zajrzyj także do [naszego poradnika](https://developer.allegro.pl/my_offers/#1), gdzie opisaliśmy właściwe filtry.
