### ISSUE TITLE
doGetSiteJournal - nie zwraca danych od godziny 2:00

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#3142]
Występuje problem: 
 - [ x] z metodą WebAPI
 - [x ] ze środowiskiem produkcyjnym

Metoda doGetSiteJournal nie zwraca eventów od godziny 2 w nocy. Ostatni row id: 47917140771. Poberam eventy publiczne

**Comment by artzie92** [comment]
Znaczy przychodzi 13 eventów, ale nie ma ani jeden statusu NOW. Wątpię, żeby od 2 w nocy nikt nic nie kupił.

**Comment by MaciejFrackowiak** [comment]
Proszę prześlij nam przykładowy request, który wysyłasz oraz wskaż, z którego klucza korzystasz - dane przekaż poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) z dopiskiem GH 3142.

**Comment by artzie92** [comment]
Wysłałem. Proszę o szybką reakcję, ponieważ te dane są dla mnie dosyć istotne.

**Comment by MaciejFrackowiak** [comment]
Proszę przełącz starting point na ostatni ze strony, którą otrzymałeś - wygląda to tak jakbyś sprawdzał czy dostałeś pełną stronę, a jeżeli nie to mechanizm zatrzymuje się.

**Comment by artzie92** [comment]
Zrobił się jakiś ogromny przeskok w Waszych id:
ChangeDate	RowId
2020-04-28 02:00:37.0000000	1588032047231688
2020-04-28 02:00:37.0000000	47917140771
2020-04-28 02:00:37.0000000	47917140770
2020-04-28 02:00:37.0000000	47917140741

Może to jest związane z Waszymi wczorajszymi zmianami w wygaszaniu API? Ruszyłem od row id 47917140784 i to zaczęło łapać id: 1588032047231688. Teraz ruszyło.

**Comment by artzie92** [comment]
> Proszę przełącz starting point na ostatni ze strony, którą otrzymałeś - wygląda to tak jakbyś sprawdzał czy dostałeś pełną stronę, a jeżeli nie to mechanizm zatrzymuje się.

Tylko dlaczego zostało zwrócone wyłącznie 18 elementów, skoro zawsze ilość jaka przychodziła to 100?

**Comment by MaciejFrackowiak** [comment]
W nocy przeprowadzaliśmy prace konserwacyjne w związku ze zmianą działania wartości infoType=0 dla doGetSiteJournal/JournalInfo. W toku tych prac zwiększony został także zakres wartości rowId, który przekazywany jest w parametrze startingPoint.

**Comment by artzie92** [comment]
Ok dzięki za info. Na ten moment działa - do zemknięcia
