### ISSUE TITLE
Zmiana konta na firmowe

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3143]
Czy mógłbym prosić o aktywacje konta firmowego na moim koncie testowym (sandbox)?

LOGIN: TESTOWY_ZXC

Muszę powystawiać kilka ofert na Allegro a bez konta firmowego nie mogę tego zrobić. Zgłosiłem już to przez Allegro Sandbox - ale nie mam niestety trzech dni na to. :(

**Comment by MaciejFrackowiak** [comment]
Proszę uzupełnij niezbędne dane i prześlij dwa dowolne pliki w zakładce [Dane konta Allegro](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) - to pozwoli zweryfikować Twoje konto jako firmowe.

**Comment by LukaszCierocki** [comment]
@MaciejFrackowiak dziękuję. Mam jeszcze tylko pytanie. Czy coś się zmieniło w API Allegro od strony walidacji przesyłanych danych?

Pobieram "całą" ofertę przy pomocy GET'a zmieniam niewielką cześć - np. nazwę oferty, a za pomocą PUT'a przesyłając całą ofertę zwraca mi błąd 400 (Nieprawidłowy request).

Już nie wiem co tam jest nieprawidłowego, skoro wszystkie walidatory prawidłowo walidują ten JSON, a Allegro jeszcze kilka sekund wcześniej samo mi przysłało ten JSON.

W załączeniu przesyłam body zapytania
[body.txt](https://github.com/allegro/allegro-api/files/4545112/body.txt)

ENDPOINT:https://api.allegro.pl.allegrosandbox.pl/sale/offers/6207426811

Dziękuję bardzo.

**Comment by MaciejFrackowiak** [comment]
@LukaszCierocki Na pierwszy rzut oka zamieniasz "true / false" na wartość typu "0". Ponadto w kilku miejscach mimo braku wartości przekazujesz "" zamiast null. Pobierz raz jeszcze swoją ofertę i zmieniaj kolejne wartości na PUT pojedynczo, wówczas od razu zobaczysz błąd.

**Comment by LukaszCierocki** [comment]
@MaciejFrackowiak OK. Dzięki, zaraz sprawdzę. :).
