### ISSUE TITLE
Sandbox - problem z autoryzacją użytkownika przez oAuth.

### ISSUE THREAD

**Issue by maciej-domski** [allegro/allegro-api#3144]
Podczas wykonywania autoryzacji typu "authorization code" na środowisku testowym, po potwierdzeniu konta po stronie Allegro otrzymuję błąd:
`<oauth>
<error_description>
Full authentication is required to access this resource
</error_description>
<error>unauthorized</error>
</oauth>`

Problem występuje na różnych kontach. Czy wszystko działa poprawnie?

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie autoryzacji na Sandbox i nie zauważyłem problemu. Sprawdź proszę, czy podajesz prawidłowy adres URL - https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={redirect_uri}.

**Comment by M4GiK** [comment]
Mam ten sam problem co powyżej, nie jestem w stanie uzyskać tokena. 
Jakie są obecne wytyczne co do headera?

**Comment by MaciejFrackowiak** [comment]
Nie dokonaliśmy żadnej zmiany w odniesieniu do Sandbox - wszelkie dane, adresy na [stronie](https://developer.allegro.pl/about/#Sandbox) są aktualne. Sprawdziłem również proces - bez najmniejszego problemu uzyskałem token.

**Comment by kajko-pl** [comment]
mam ten sam problem. w piątek jeszcze działało bez zarzutu. po potwierdzeniu konta dostaję zwrotkę `<oauth><error_description>Full authentication is required to access this resource</error_description><error>unauthorized</error></oauth>`, co ciekawe w urlu widzę coś takiego `https://allegro.pl.allegrosandbox.pl/auth/oauth/#error=invalid_scope&error_description=Invalid%20scope:%20allegro_api`

u nas zawsze jest przesyłany scope "allegro_api", bo tak kiedyś sugerowaliście robić w dokumentacji. sprawdziłem teraz żądanie bez przesyłania scope'a i zadziałało poprawnie.

@MaciejFrackowiak jak aktualnie wygląda sytuacja ze scope'ami? powinienem coś wskazywać konkretnie? czy w ogóle nie przesyłać?

**Comment by MaciejFrackowiak** [comment]
@kajko-pl Nie, nie przekazuj już takiego scope. Wczoraj opublikowaliśmy news - GH #3149 - tokeny zawierają obecnie większy zakres danych (w tym rozbudowane informacje dot. scope).

**Comment by M4GiK** [comment]
@MaciejFrackowiak przy okazji prosiłbym o aktywowanie konta allegro@kamstechnologies.pl, cały czas wisi do weryfikacji.

**Comment by kajko-pl** [comment]
@MaciejFrackowiak wszystko jasne, już poprawiam kod. dzięki za szybką odpowiedź!

**Comment by MaciejFrackowiak** [comment]
@M4GiK Konto aktywowane, wybrałeś konto Firma - proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) w celu jego weryfikacji.

**Comment by M4GiK** [comment]
@MaciejFrackowiak, dziękuję i przesłane. Jeśli chodzi o uzyskanie tokena, udało się wygenerować przez postmana. Widocznie problem leży gdzie indziej. Przesyłam trace-id=[a03fcd98f3cacf9f]. 
Czy coś więcej można się dowiedzieć?

**Comment by MaciejFrackowiak** [comment]
@M4GiK Znalazłem request, jednak bez payload niestety - widzę tylko problem z autoryzacją i błąd 401.
