### ISSUE TITLE
[REST-OAuth]: Nowe uprawnienia - nowe dane w zasięgu i NIC?

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#3145]
Gdzie informacje o zmianach, które weszły od dzisiaj?!?
'scope' => 
    array (
      0 => 'allegro:api:orders:read',
      1 => 'allegro:api:profile:write',
      2 => 'allegro:api:sale:offers:write',
      3 => 'allegro:api:billing:read',
      4 => 'allegro:api:campaigns',
      5 => 'allegro:api:disputes',
      6 => 'allegro:api:bids',
      7 => 'allegro:api:sale:offers:read',
      8 => 'allegro:api:orders:write',
      9 => 'allegro:api:ads',
      10 => 'allegro:api:payments:write',
      11 => 'allegro:api:sale:settings:write',
      12 => 'allegro:api:profile:read',
      13 => 'allegro:api:ratings',
      14 => 'allegro:api:sale:settings:read',
      15 => 'allegro:api:payments:read',
    ),

**Comment by MaciejFrackowiak** [comment]
Wprowadzone zmiany nie zaburzają działania API - zmieniła się przez to jedynie długość tokena, ale nie mamy udokumentowanej jego długości, zatem zalecamy nie ustawiać na to limitu albo ustawić spory zapas.
