### ISSUE TITLE
🐞 Problemy z autoryzacją/ Authorization issues

### ISSUE THREAD

**Issue by PrzemyslawLukanowski** [allegro/allegro-api#3146]
Obecnie mamy problemy techniczne, które mogą mieć wpływ na operacje związane z autoryzacją. O rozwiązaniu problemu poinformujemy w tym wątku.

-----

We have technical problems that may affect the authorization process. We will inform you in this topic when the problem is solved.

**Comment by FromAnyHole** [comment]
Wykrakałem więc nieco niżej...

**Comment by PrzemyslawLukanowski** [comment]
Problemy związane są ze zmianą długości tokena. Szczegóły w wątku #3149.

------

Issues are linked with change of token lenght. Details in #3149.

**Comment by jasiek07** [comment]
Czy znany jest czas usunięcia awarii , nie można pobrać żadnych zamówień w tym ich realizować

**Comment by PrzemyslawLukanowski** [comment]
@jasiek07 Szczegóły znajdziesz w wątku #3149. Jeżeli zmienisz limit na długość tokena w swoim oprogramowaniu, operacje powinny działać prawidłowo.
