### ISSUE TITLE
Allegro Sandbox - aktywacja konta oraz sprzedaży

### ISSUE THREAD

**Issue by aosmialowski** [allegro/allegro-api#3147]
Mam problem z szybką aktywacją konta w sandboxie:
- mail: jankowalski.testallegro@gmail.com
- mail: marcinnowak.testallegro@gmail.com
- mail: holmpl.testallegro@gmail.com.

Dodatkowo, dla tego ostatniego konta po przesłaniu plików w zakładce Moje Konto => Dane Konta mam informację o weryfikacji, nie mogą uruchomić sprzedaży testowej.

Prosiłbym o aktywację, w miarę możliwości.

**Comment by MaciejFrackowiak** [comment]
Podane przez Ciebie konta właśnie aktywowałem. Na koncie firmowym również bez przeszkód już możesz wystawiać oferty.

**Comment by aosmialowski** [comment]
@MaciejFrackowiak dziękuję bardzo!
