### ISSUE TITLE
Powiązanie płatności za zamówienia do przelewu otrzymywanego od allegro

### ISSUE THREAD

**Issue by pawel1151** [allegro/allegro-api#3148]
Mamy w planach integrację z allegro mającą na celu powiązanie przelewu z wyciągu bankowego z określonymi płatnościami za zamówienia,  które wchodzą w skład tego przelewu, otrzymanego od Allegro 

Dodatkowo, w pewnym zewnętrznym systemie zwanym "Baselinker" przetrzymywane są informacje o zamówieniach,  zawierające id zamówienia allegro ( https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET ) - które to informacje po tym id musimy wyciągnąć i dopasować do każdej płatności/zwrotu.

Co zatem potrzebujemy:
- kwotę przelewu jaką allegro wykonuje do nas
- listę płatności/ zwrotów które w ramach tego powyższego przelewu występują, oraz id zamówień których dotyczą  ( tych id: https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET ).

Z tego co znaleźliśmy w dokumentacji, do wyciągnięcia płatności/zwrotów występujących w danym przelewie prawdopodobnie będzie trzeba użyć endpointu https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory - poprzez pobieranie płatności /zwrotów/ruchów pomiędzy PAYOUT'ami i sprawdzenie czy suma się równa PAYOUT'owi 

Pytanie 1. Czy ta powyższa metoda jest odpowiednia aby wyciągnąć te informacje? Czy nie ma czegoś prostszego? ( jak sobie wyobrażam prostsze rozwiązanie - np. podaję id PAYOUTu i zwracana mi jest lista płatności/zwrotów z ich idkami które w jego skład wchodzą, tak żeby mieć solidne powiązanie, a nie "domniemanie" że wszystko pomiędzy payoutami ostatnim a obecnym należy do tego obecnego, jeszcze do tego jest PAYOUT CANCEL który mi anuluje payouty)

Pytanie 2. W jaki sposób znaleźć id zamówienia /checkoutforma  ( https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET  ) mając id płatności z https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory?

Pytanie 3. Co oznaczają poniższe typy ruchów w payment operations ( wyciągnąłem je z dokumentacji, nie mogę nigdzie znaleźć ich głębszego opisu)
INCOME 
- CONTRIBUTION: SURCHARGE, CORRECTION, DEDUCTION_INCREASE. 
- OUTCOME : PAYOUT, PAYOUT_CANCEL, DEDUCTION_CHARGE. 
- REFUND: - REFUND_CHARGE, REFUND_CANCEL, REFUND_INCREASE, CORRECTION.

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na Twoje pytania:

1. Tak, to jest odpowiedni zasób dla sprawdzania historii płatności. Dodatkowo, możesz użyć także [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments) do pobrania szczegółów dokonanych zwrotów.
2. Skorzystaj z [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) w query parameters użyj „payment.id” - wówczas dla danego payment.id w odpowiedzi otrzymasz konkretne id zamówienia.
3. SURCHARGE - dopłata, CORRECTION - korekta, DEDUCTION_INCREASE - uznanie z tytułu prowizji , PAYOUT - wypłata, PAYOUT_CANCEL - anulowanie wypłaty, DEDUCTION_CHARGE - wytrącenie prowizji z salda, REFUND_CHARGE - obciążenie z tytułu zwrotu, REFUND_CANCEL - anulowanie zwrotu, REFUND_INCREASE - zwiększenie zwrotu.
