### ISSUE TITLE
Sandbox Allegro

### ISSUE THREAD

**Issue by febestore** [allegro/allegro-api#315]
Dzień dobry,
mam problem z połączeniem modułu do synchronizacji Allegro z backofficem PrestaShop 1.7
Używam modułu ze strony addonspresta.com (https://addonspresta.com/pl/content/10-integracja-z-allegro#pt1)

Aktualnie moduł testujemy na wersji developerskiej naszego sklepu.

Mam problem z połączeniem się z sanboxem Allegro. Aktywowałem konto i wpisałem kody webApi i client secret. Po wybraniu karty "konta" i wybraniu opcji "dodaj konto (sandbox) nie działa przekierowanie. Przekierowuje mnie na adres: https://allegro.pl.webapisandbox.pl/auth/oauth/authorize?response_type=code&client_id=1838cad907364c828005195627899a39&redirect_uri=http%3A%2F%2Fwww.febe.pro-linuxpl.com%2Fpl%2Fgg84oirdi1cflmsy%2Findex.php%3Fcontroller%3DAdminAllegroAccount%26token%3D7ea406959084b75f308cf5bb703f9069%26addallegro_account%26sandbox

Link nie działa.

Jest jakaś inna możliwość aktywacji konta dla sandboxa w celu przeprowadzania testów?

PS. jak długo trzeba czekać na aktywacje konta w sandboxie? Chciałbym wystawić testowe zamówienie i zacząć budować nowy webservice.
Pozdrawiam,

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, mam pytanie założyłeś już i w pełni aktywowałeś konto na [Sandbox ](https://developer.allegro.pl/about/#Sandbox) i nastepnie w[ zarejestrowałeś aplikację](https://apps.developer.allegro.pl.allegrosandbox.pl/)? Czy nie masz pełnej aktywacji konta? Jeśli nie masz jeszcze w pełni aktywnego konta na sandboxie podeślij proszę login tego konta na Sandboxie i aktywujemy.

**Comment by kormichu** [comment]
Podpowiem ;) Chodzi o adres url: https://github.com/allegro/allegro-api/issues/91

> od 29 marca adres https://allegro.pl.webapisandbox.pl będzie automatycznie przekierowywał do nowego środowiska testowego, czyli do https://allegro.pl.allegrosandbox.pl,
> 29 kwietnia zupełnie wyłączymy stare środowisko - każda próba wejścia na nie zakończy się błędem.

Moduł ma stary adres

**Comment by febestore** [comment]
Tak, założyłem i aktyowowałem konto:
![obraz](https://user-images.githubusercontent.com/40421616/41647449-b6c3a70e-7476-11e8-99ee-24cc16e99e2c.png)
Konto nie jest aktywowane do sprzedaży:
![obraz](https://user-images.githubusercontent.com/40421616/41647525-ef64c278-7476-11e8-9b73-f527cdee40db.png)
Na wersji produkcyjnej wysyła się przelew o wysokości 1,01 zł. Na sandboxie wybrałem opcję przelewu i wyświetliła się aplikacja potwierdzająca wysłanie płatności. Kliknąłem 'tak' i otrzymałem informację o weryfikacji konta jak na screenie wyżej.
Login do konta to: b.sedenko@febe.store (nazwa użytkownika Febe_Store).

Co do pierwszego pytania. Chodzi o dodanie konta do modułu Allegro. Dodałem klucze API do modułu, lecz podczas próby dodania konta przekierowuje mnie na link w poście wyżej. Czy link jest prawidłowy? Może odwołuje się do starszej wersji sandboxa?
![obraz](https://user-images.githubusercontent.com/40421616/41647771-7899266a-7477-11e8-8b80-556923872078.png)

**Comment by PawelTaberski** [comment]
Konto aktywowane, a odnośnie przekierowania tak jak zauważył @kormichu masz stary adres sandboxa. Poprawny to https://allegro.pl.allegrosandbox.pl
