### ISSUE TITLE
[restAPI] Błąd aktualizacji stanów (offer-quantity-change-commands)

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3151]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry
Proszę o weryfikację, dlaczego tylko dla tej aukcji nie dało się zmienić ilości sztuk, takich prób było kilkanaście, wszystkie  z tym samym błędem. 

REQUEST 2020-04-28 08:01:39.9477978 
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/f4d72fed-74b3-4224-a6b2-a2471df646bb' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  -d '{"modification":{"changeType":"FIXED","value":1},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"8009807725"}]}]}' \

RESPONSE 2020-04-28 08:01:39.9633943  Duration: 15,5965ms
{
  "Data": {
    "Id": "f4d72fed-74b3-4224-a6b2-a2471df646bb",
    "TaskCount": {
      "Failed": 0,
      "Success": 0,
      "Total": 0
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "f558ec2d2dd0d615",
  "Error": false,
  "StatusCode": 201,
  "Message": null
}

REQUEST 2020-04-28 08:03:53.6587056 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/f4d72fed-74b3-4224-a6b2-a2471df646bb/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

RESPONSE 2020-04-28 08:03:53.6743328Duration: 15,6272ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2020-04-28T06:01:46.541Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "8009807725"
        },
        "ScheduledAt": "2020-04-28T06:01:45.706Z",
        "Status": "FAIL",
        "Errors": [
          {
            "Code": "ERR_INVALID_QUANTITY",
            "Details": null,
            "Message": "ERR_INVALID_QUANTITY",
            "Path": null,
            "UserMessage": "Nieprawidłowa liczba sztuk."
          }
        ]
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "d99a8b5cca5e2c30",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by MaciejFrackowiak** [comment]
Zgłoszony problem przekazałem do właściwego działu.
