### ISSUE TITLE
RestAPI - Access is denied (Brak dostępu do danego zasobu)

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3153]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzisiaj w ramach różnych metod rzuca błędem

  | [{"code":"AccessDenied","message":"Access is  denied","details":null,"path":null,"userMessage":"Brak dostu0119pu do  danego zasobu."}]
-- | --

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam przykład takiego requestu wraz z trace-id.

**Comment by pietrach** [comment]
Przykładowe: (jest dużo więcej)
18d08e6b694141a4
84c6ca1945074745
ea240dda73a7897

**Comment by pietrach** [comment]
I widzę że to się dzieje nie tylko u jednego klienta

**Comment by MaciejFrackowiak** [comment]
Wywołujesz zasób w becie, która została wyłączona 27.04.2020 - informowaliśmy o tym w komunikacie GH #3082

**Comment by pietrach** [comment]
Czyli już wszystkie zasoby działają w public ?

**Comment by FromAnyHole** [comment]
@pietrach - nie ufać wszystkiemu, cyklicznie czytać nagłówki odpowiedzi...

**Comment by MaciejFrackowiak** [comment]
@pietrach Zasób [GET /sale/offers/{offerId}/shipping-rates](https://developer.allegro.pl/documentation/#operation/getOfferShippingRatesGET) pozostaje w beta. Warto jednak śledzić nasze komunikaty, gdzie informujemy o przejściu na public.
