### ISSUE TITLE
Błędy w liczeniu czasu odpowiedzi na maile

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#3154]
Wydaje mi się że nieprawidłowo Państwo liczą terminowość odpowiedzi - coś tu jest nie tak. proszę zobaczyć statystyki dyskusji oraz maili na kontach sprzedawców np moim. 

Z jedej strony mam super, a maile - nieakcepotwalny mimo że odpowadamy na maile tak samo szybko jak na dyskusje. Inna sprawa, że nie mamy ostatnio zapytań mailowych - przez co pewnie ich brak liczy się jako ZERO i dramatycznie zaniża ocenę jakości - proszę się temu przyjrzeć i proszę o informację zwortną. 

oto zrzut ocen z mojego panelu: 

DYSKUSJE - SUPER

Terminowe odpowiedzi w dyskusjach:100% W dyskusjach zawsze odpowiadasz w ciągu 24 godzin. Dzięki temu nawet w przypadku problemów, klienci mogą liczyć na Twoją obsługę i zaangażowanie. 20 / 20 Super Super wynik! Jesteś w gronie najlepszych sprzedających na Allegro! 

Średni czas odpowiedzi w dyskusjach:19m Szybko udzielasz odpowiedzi w dyskusjach. Dla Twoich klientów to znak, że dbasz o ich obsługę. 30 / 30 Super Super wynik! Jesteś w gronie najlepszych sprzedających na Allegro! Nierozwiązane dyskusje:0,00% Świetnie! Na xxx transakcji z ostatnich 30 dni, nie masz żadnej nierozwiązanej dyskusji. 10 / 10 Super Super wynik! Jesteś w gronie najlepszych sprzedających na Allegro! 

I TERAZ UWAGA: - PROBLEM!

Terminowe odpowiedzi na wiadomości klientów:0,00% Część Twoich klientów nie dostaje odpowiedzi tak szybko, jak powinni. Dzięki efektywnej obsłudze możesz sprawić, że mimo problemów klienci nadal będą zadowoleni z zakupów u Ciebie. Postaraj się odpowiadać szybciej. -950 / 20 Nieakceptowalny 94% sprzedawców ma więcej punktów od Ciebie. Warto poprawić ten wynik. 

Średni czas odpowiedzi na wiadomości klientów:Brak danych W ostatnich 30 dniach klienci nie wysłali Ci żadnej wiadomości lub na żadną nie otrzymali od Ciebie odpowiedzi.

I TUTAJ LEŻY PROBLEM - BRAK DANYCH - bo nie ma zapytań mailowych, wszytsko robimy na bieżąco...) także uważam że ocena ta jest źle liczona i .. niesprawiedliwa... Podobną sytuację mam także na innym koncie z małą aktywnością mailową.  

Pisałem zapytania przez formularz kontatowy , ale zero odpowiedzi. Skoro ma to być wymagana to wypadało by to liczyć prawidłowo ;)

**Comment by MaciejFrackowiak** [comment]
Na pewno otrzymasz odpowiedź na zgłoszenie przekazane poprzez formularz - po prostu czasami czas oczekiwania na odpowiedź jest trochę dłuższy. Na forum natomiast wspieramy stricte wykorzystanie publicznego API.

**Comment by Adam1610** [comment]
NIestety s supportu nic nie otrzymałem. Wydaje mi się że błąd jest i pewnie pracujecie nad nim a mnie zamieciono pod dywan? Czy tak ?  :>

**Comment by MaciejFrackowiak** [comment]
Forum na GitHub`ie wykorzystujemy tylko do komunikacji tematów związanych bezpośrednio z API. Trudno mi się odnieść do Twoich zastrzeżeń, dlatego najlepiej będzie, gdy skontaktujesz się ponownie przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=b06c0cd1-bc28-4a16-8517-b2f493dc38d4&subjectId=581ea977-52d2-4469-ab70-0ef30744c0e0) i przedstawisz swój problem opisując go dokładnie.
