### ISSUE TITLE
Przy generowaniu parametru code dla Tokena Allegro pyta o powiązanie konta z aplikacją PyCharm

### ISSUE THREAD

**Issue by ChrupekV2** [allegro/allegro-api#3155]
Czy pytanie o powiązanie z PyCharm ma związek z ostatnimi niezapowiedzianymi zmianami w autoryzacji?

W powiązanych aplikacjach widzimy, że takie połączenie już istnieje z datą dzisiejszą. Pytanie dlaczego ono istnieje i dlaczego pyta o powiązanie skoro już takie jest?

**Comment by MaciejFrackowiak** [comment]
Tak, to efekt zmiany opisanej w poście GH #3049 - dlatego ponowne potwierdzenie powiązania aplikacji jest konieczne.
