### ISSUE TITLE
Problem z autoryzacją 

### ISSUE THREAD

**Issue by Przem4S** [allegro/allegro-api#3156]
Występuje problem:
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją

Czy jest jakiś problem z autoryzacją na środowisku testowym? Po próbie wejścia w link do logowania
otrzymuje informację jak poniżej, zmieniając dane na środowisko produkcyjne wszystko działa dobrze.
Adresy URL i dane zweryfikowane.

Nie możemy wyświetlić strony
Numer błędu: b669d329c70b9dde

**Comment by MaciejFrackowiak** [comment]
Otrzymany przez Ciebie komunikat świadczy o tym, że adres przekierowania, który masz w aplikacji nie jest zgodny z tym, który widnieje na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Tyle mogę stwierdzić na podstawie samego opisu zdarzenia.

**Comment by Przem4S** [comment]
Dziękuję bardzo za słuszną sugestię, sprawdziła się.
