### ISSUE TITLE
doGetUserID doGetUserLogin, co w zamian?

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#3157]
Dziś usunięto metody z tytułu, w jaki sposób mogę pobrać id dla danego użytkownika i nazwę użytkownika dla danego id?

**Comment by MaciejFrackowiak** [comment]
Obecnie nie mamy odpowiednich zasobów w REST API. Proszę, powiedz proszę do czego potrzebna jest Tobie taka funkcjonalność.

**Comment by juhacz** [comment]
Z prostej przyczyny, do człowieka bardziej przemawiają litery (zenek52) niż cyfry (11082817). Przez wiele lat napisałem wiele programów na swoje i innych potrzeby, które wyświetlają nazwę sprzedającego, a w tym momencie cyferki. Prosty przykład z brzegu , program który sprawdzania, co za ile się sprzedało  w archiwum Allegro.
Wyświetlana jest tabela i teraz kolumna sprzedający w tej tabeli to w każdym rekordzie rząd cyferek.  Do człowieka to nie przemawia, dlatego posługujemy się imieniem i nazwiskiem. Następny program, powiadomienia o nowych aukcjach, z dziennika, czy z listingu kategorii, tam nie mam już możliwości poinformowania, kto jest sprzedającym. Przez wiele lat korzystania z takich programów, znam pewne nicki na pamięć, wiem co kto sprzedaje, znam konkurencję i wiem czy mogę od nich kupować, ale to już są takie moje wewnętrzne rozmyślenia. Teraz to jest po prostu niemożliwe. Równie dobrze moglibyście zmienić nazwę wszystkich allegrowiczów na Client_547631654

**Comment by MaciejFrackowiak** [comment]
Dziękuję za obszerne wyjaśnienie. Twoje zdanie wpisuję na listę sugestii dot. rozwoju zasobów REST API.

**Comment by ziemekpr0** [comment]
@MaciejFrackowiak serio dopiero teraz na to wpadliście i serio trzeba było to tłumaczyć? Czemu nie poradziłęś, żeby kolega połączył WWW i API? xD

**Comment by TimothyKoval** [comment]
@ziemekpr0 Ale wiesz, że allegro przechowuje te sugestie w `/dev/null`? :)

**Comment by ziemekpr0** [comment]
@TimothyKoval Odwiedzam okazjonalnie to forum i zdaję sobie z tego sprawę. :) Sam w podobnym temacie dostałem odpowiedź typu "połącz WWW i API". Wytłumacz klientowi, że żeby uruchomić "coś" najpierw musi zalogować się do allegro przez www i znaleźć swój identyfikator konta (pomijam oAuth bo zmuszanie kogokolwiek żeby powiązał swoje konto allegro z apikacją tylko po to żeby pobrać publiczne dane z wyszukiwarki mija sie z celem).

**Comment by MaciejFrackowiak** [comment]
@ziemekpr0 Chcemy po prostu poznać Waszą potrzebę, stąd moja prośba.

**Comment by ziemekpr0** [comment]
@MaciejFrackowiak na pewno chcecie ją poznać? Ile razy można wałkować to samo? Domyślam się, że każda osoba, która odpala dokumentację REST, następnie próbuje uruchomić pierwszy lepszy zasób, nagle dowiaduje się, że brakuje czegoś takiego jak id usera. Zniechęcające, prawda? A ciężko go znaleźć nawet na stronie allegro bo przecież wprowadzacie wszędzie, o dziwo nawet w URL-ach, login (nie ID) użytkownika.

W znakomitej większości wątków tutaj na forum odpowiadacie że REST jest odzwierciedleniem funkcjonalności na froncie allegro, ale nie do końca jest to prawdą. Weźmy pierwszy lepszy zasób, czyli wyszukiwarkę, nie można wyszukiwać po id aukcji, nie można wyszukiwać po loginie sprzedawcy, id sprzedawcy nie wiadomo skąd pobrać, w wynikach wyszukiwania nie ma loginów sprzedawców i wielu innych danych i jest to o tyle drażniące, że te dane były łatwo dostępne w SOAPie. Sorry ale z tego co widzę to te wątki są tutaj cyklicznie wałkowane po kilka razy w tygodniu. Jaki jest tego skutek? Domyślam się, że więcej requestów omijających API, REST czy SOAP i scalpowanie kodu allegro.

**Comment by TimothyKoval** [comment]
O, proszę.
https://developer.allegro.pl/documentation/#operation/getRefundApplications - buyer.login
https://developer.allegro.pl/documentation/#operation/getListing - seller.id

**Comment by ziemekpr0** [comment]
> 
> 
> O, proszę.
> https://developer.allegro.pl/documentation/#operation/getRefundApplications - buyer.login
> https://developer.allegro.pl/documentation/#operation/getListing - seller.id

Możesz rozwinąć swoją myśl? Jeśli chodzi ci o to że pierwsza metoda zwraca login kupującego, to OK, tylko że na świeżym koncie, albo takim na którym akurat nie dokonywano zwrotów, może tych danych po prostu nie być? Ciężko oprzeć o coś takiego aplikację.

Druga z kolei, na co zwracałem uwagę ostatnio też nie zwróci identyfikatora tylko tego sprzedawcy, którego chcesz, bo żeby wyszukać jego oferty najpierw musiałbyś znać jego ID.

**Comment by TimothyKoval** [comment]
Mam na myśli to, że raz potrzebny jest login a raz id

**Comment by ziemekpr0** [comment]
A właśnie, w wyszukiwarce REST:
https://developer.allegro.pl/documentation/#operation/getListing
brakuje jeszcze trybu wyszukiwania (**searchMode**) po loginie sprzedawcy.

**Comment by MaciejFrackowiak** [comment]
@ziemekpr0 W mojej odpowiedzi do Ciebie wyjaśniałem dlaczego o to pytamy, a przy okazji dostałem i Twoje zdanie - bardzo dziękuję.

**Comment by ziemekpr0** [comment]
@MaciejFrackowiak wygląda na to, że pytacie aby pytać - bo ktoś kazał. 

> Chcemy po prostu poznać Waszą potrzebę, stąd moja prośba.

Osobiście odbieram to tak, że na tym się kończy.
