### ISSUE TITLE
Wartości masek

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#3158]
Gdzie można znaleźć opis poszczególnych masek? strona https://allegro.pl/webapi/faq.php#faq_4 nie pokazuje już tych informacji.

Czy takie informacje będą udostępniane w REST API dla publicznych ofert?

**Comment by MaciejFrackowiak** [comment]
W [FAQ](https://allegro.pl/webapi/faq.php#faq_3) wskazujemy listę wartości i odpowiadające im ustawienia. Aby odczytać poszczególne opcje, najprościej zamienić otrzymaną maskę na postać binarną i sprawdzić ustawienia kolejnych bitów.
Natomiast zgodnie z [harmonogramem](https://developer.allegro.pl/schedule/) informacje dot. zasobu REST API pojawią się w III kwartale 2020.
