### ISSUE TITLE
Błąd w rozliczeniu

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#3159]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Mam dość dziwny problem, dotyczy on zamówienia: 
e5f04a95-88c0-11ea-9e31-fb64ea5505c5
według: szczegółów zamówienia w panelu allegro jak i w rest api jest:
**55,38 zł**
27 kwi 2020, 21:57
płatność P24
e6401845-88c0-11ea-9dfd-7bac605463c4
OPŁACONE

Ale w rozliczeniu (Środki i historia operacji) 
27.04.2020, 21:57 
wpłata 
Przelewy24 
e6401845-88c0-11ea-9dfd-7bac605463c4
**52,42 zł**
w tym dostawa 10,31 zł 

Z czego wynika rozbieżność ?

**Comment by MaciejFrackowiak** [comment]
Potwierdzam zauważoną przez Ciebie rozbieżność, przekazałem sprawę do właściwego działu. Po otrzymaniu wyjaśnień wrócę z odpowiedzią.

**Comment by manoos** [comment]
warto też zauważyć że wypłata środków była na kwotę: 52,42.
I teraz mam rozjazd w bilansach :/

**Comment by MaciejFrackowiak** [comment]
Tak, zauważyłem to i zaznaczyłem w przekazanym zgłoszeniu.

**Comment by manoos** [comment]
Jakieś postępy ?

**Comment by MaciejFrackowiak** [comment]
Proszę o cierpliwość - sprawa jest analizowana.

**Comment by manoos** [comment]
I jak ustaliliście coś? Czy czekacie aż zapomnę o tym?

**Comment by manoos** [comment]
I kiedy planujecie dopłacić ?

**Comment by MaciejFrackowiak** [comment]
Nie zapomnieliśmy i pamiętamy o Twoim zgłoszeniu - po prostu niezbędny jest czas, abyśmy mogli sprawdzić szereg zmiennych, które tu mają kluczowe znaczenie. Wrócę z odpowiedzią.

**Comment by manoos** [comment]
Czy 12 dni analiz umożliwiło wam rozwiązanie problemu? 
Błąd jest ewidentny, prześlijcie kasę i już. Musimy to zbilansować w systemach, bo trzeba miesiąc zamykać.

**Comment by MaciejFrackowiak** [comment]
Niestety, jeszcze nie - clue sprawy to określenie właściwej kwoty, która powinna być przypisana do tego zamówienia. Szereg czynników ma wpływ na ostateczne rozwiązanie. Zgodnie z moją wcześniejszą wiadomością zamieszczę tu odpowiedź, gdy sprawa zostanie wyjaśniona.

**Comment by manoos** [comment]
i nadal nic ?

**Comment by MaciejFrackowiak** [comment]
Niestety - przesłałem dzisiaj monit w Twojej sprawie. Jeżeli otrzymam wiążącą odpowiedź w kwestii zgłoszonego problemu, dam znać w poście.

**Comment by manoos** [comment]
miesiąc minął a my dalej bez odpowiedzi...

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z tym, co napisał @MaciejFrackowiak - gdy otrzymamy wiążącą odpowiedź, udzielimy informacji w wątku.

**Comment by manoos** [comment]
I jak z tematem ?

**Comment by MaciejFrackowiak** [comment]
Pamiętam o Tobie - niestety, pomimo kilkukrotnych prób uzyskania wiążących wyjaśnień, jeszcze nie otrzymałem ich - nadal monitoruję sprawę.

**Comment by manoos** [comment]
Ciągle czekam!

**Comment by MaciejFrackowiak** [comment]
Wiem i pamiętam - niestety, finalnej odpowiedzi jeszcze nie posiadam.

**Comment by MaciejFrackowiak** [comment]
Wracam z wyjaśnieniem problemu tu zgłoszonego - w momencie, gdy kupujący dodał przedmioty do koszyka i wypełniał dane wysyłkowe koszt dostawy wynosił 10,31 zł. W międzyczasie - na przestrzeni kilku sekund sprzedający dokonał zmiany w cenniku dostawy - kliknięcie przez kupującego "kupuję i płacę" spowodowało zakup i płatność z kwotą z momentu wypełnienia formularza (co jest prawidłowe), jednak dane do zamówień wpadły już z zaktualizowaną kwotą dostawy wyliczoną wg nowego cennika tj. 13,27. Z naszej strony dokonamy niezbędnej poprawki, aby koszt dostawy dla procesowanego zamówienia nie zmienił się, gdy sprzedający w międzyczasie dokonuje zmian w cenniku dostawy.

Jednocześnie przepraszam Cię, że musiałeś tak długo czekać na wyjaśnienie zgłoszonego problemu.

**Comment by manoos** [comment]
taaa
