### ISSUE TITLE
Metoda doGetMyFutureItems zwraca błąd "SOAP-ERROR: Encoding: object has no 'itemThumbnailUrl' property"

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#316]
Jak w tytule, od metoda doGetMyFutureItems zwraca błąd "SOAP-ERROR: Encoding: object has no 'itemThumbnailUrl' property". 

Wywołanie bez żadnych parametrów 
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoGetMyFutureItemsRequest>
         <ser:sessionId>${#Project#sessionId}</ser:sessionId>
     </ser:DoGetMyFutureItemsRequest>
   </soapenv:Body>
</soapenv:Envelope>`

Odpowiedź:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring>SOAP-ERROR: Encoding: object has no 'itemThumbnailUrl' property</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by PawelTaberski** [comment]
Sprawdziłem i metoda działa poprawnie zarówno na Sandboxie jak i produkcji. Podeślij proszę na login usera na jakim występuje problem.

**Comment by k4pit4n** [comment]
Dzięki za szybką reakcję :)

Login to JustForTest, hasło Just4Test, błąd występuje na Sandboxie. 
Głowy za to nie dam, ale z tego co pamiętam jeszcze wczoraj działało 
poprawnie (a na pewno działało poprawnie w tym tygodniu).

Być może problem jest z którąś ofertą testową, którą wystawiałem 
wczoraj.

Pozdrawiam
Wiesław Czerwiński

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście na twoim koncie występuje jakiś problem, sprawę zgłosiłem do odpowiedniego zespołu.
Przy okazji zatwierdziłem Tobie konto na Sandboxie.

**Comment by k4pit4n** [comment]
Dzięki za zatwierdzenie konta :)

Problem prawdopodobnie spowodowany jest przez aukcję 6205372087, jeśli podaję tę aukcję na liście "itemIds"
` <ser:itemIds>
            <ser:item>6205372087</ser:item>
</ser:itemIds>`

to otrzymuję błąd. Natomiast dla aukcji 6205374822 błąd nie występuje.

**Comment by PawelTaberski** [comment]
Przekazałem Twoje spostrzeżenie do zespołu, który zajmie się tym problemem, proszę o cierpliwość.

**Comment by k4pit4n** [comment]
Dzisiaj oferta 6205372087 zmieniła status z "oczekującej" na "sprzedaję" i błąd już nie występuje. Być może został poprawiony, ale nie jestem w stanie tego stwierdzić.

Dodam, że na liście ofert "sprzedawanych" pole "itemThumbnailUrl" dla oferty 6205372087 jest prawidłowo wypełnione.

**Comment by PawelTaberski** [comment]
Dziękuje za informacje

**Comment by k4pit4n** [comment]
Jeszcze jedno, właśnie wystawiłem ofertę oczekującą ze zdjęciem **w przeglądarce** (**6205375786**), tutaj również dostaję błąd (SOAP-ERROR: Encoding: object has no 'itemThumbnailUrl' property) przy wywołaniu metody doGetMyFutureItems i zawężeniu do tej oferty. Można więc chyba wykluczyć problem z przesyłaniem zdjęcia przy wystawianiu oferty poprzez WebApi.

**Comment by PawelTaberski** [comment]
Rozumiem informacje przekazałem do odpowiedniego zespołu.

**Comment by k4pit4n** [comment]
Dzisiaj rano przy **wystawianiu** oferty oczekującej **ze zdjęciem** po dłuższym czasie oczekiwania pojawiał się komunikat 

> [-2146533087] Wewnętrzny błąd systemu. (System.Web.Services)

Wystawienie oferty oczekującej **bez zdjęcia** działało poprawnie.

Obecnie sytuacja wróciła do stanu poprzedniego, tzn. wystawienie oferty oczekującej ze zdjęciem powoduje błąd 

> SOAP-ERROR: Encoding: object has no 'itemThumbnailUrl' property

przy wywołaniu metody doGetMyFutureItems

**Comment by k4pit4n** [comment]
Tak dla porządku zaraportuję, że błąd nadal się pojawia.

**Comment by PawelTaberski** [comment]
Zespół odpowiedzialny za zajęcie się tym problemem pracuje nad rozwiązaniem, proszę o cierpliwość.

**Comment by k4pit4n** [comment]
Dziękuję za informację.

Skoro problem jest poważniejszy, to może dałoby się tymczasowo wysyłać pusty znacznik _<itemThumbnailUrl/>_ w przypadku ofert oczekujących z miniaturkami (a więc traktować oferty z miniaturką tak jak te bez miniaturki). Wówczas metoda _doGetMyFutureItems_ stałaby się przynajmniej używalna - zwracałaby listę ofert oczekujących z prawie wszystkimi informacjami o nich, brakowałoby jedynie miniaturki, a z tym można by jakoś żyć ;)

Przyznam, że obecny stan praktycznie uniemożliwia mi korzystanie z interfejsu WebAPI, a powyższe, połowiczne rozwiązanie byłoby akceptowalne.

**Comment by PawelTaberski** [comment]
Przekazałem Pana sugestię do zespołu zajmującego się tą sprawą.

**Comment by k4pit4n** [comment]
Dziękuję, ale niestety efekt jest na razie żaden :(

**Comment by k4pit4n** [comment]
_Na zachodzie bez zmian_, błąd nadal ten sam.

**Comment by PawelTaberski** [comment]
Jak tylko rozwiążemy ten problem poinformuje Pana.

**Comment by k4pit4n** [comment]
Dzisiaj sprawdziłem ponownie i błąd nie występuje, dziękuję za rozwiązanie problemu :)
