### ISSUE TITLE
Pytanie o autoresponder

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#3160]
Czy jest możliwość stworzenia autorespondera email poprzez API?
Chodzi mi o to jakim zasobem mogę pobierać pojawiające się pytania do sprzedającego dla danej oferty, a następnie odpowiednio zareagować odpowiedzią również używając jakiegoś zasobu poprzez API? Gdzie znajdę odpowiednie informacje by móc to obsłużyć?

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną nie obsługujemy jeszcze Centrum Wiadomości zasobami REST API. Funkcjonalność ta znajduje się na liście sugestii dot. rozwoju REST API - o wdrożeniu takiego rozwiązania poinformujemy w osobnym komunikacie oraz poście na GitHub.

**Comment by WGRINGO** [comment]
Ok dziękuję bardzo za odpowiedź.
