### ISSUE TITLE
Problem z odpytaniem zasobu mapującego identyfikatory

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3161]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Czy moglibyście odblokować metody służące do mapowania identyfikatorów transakcji i aktów zakupowych na Sandboxie ?

Po wywołaniu requestu:
```
GET /order/line-item-id-mappings?lineItemId=8de5dda0-8abf-11ea-91ac-0df475c30528 HTTP/1.1
```

Wyrzuca błąd:
```
{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}
```

Dokładnie to chodzi o metody:
https://developer.allegro.pl/documentation/#operation/findMapping
https://developer.allegro.pl/documentation/#operation/getPaymentIdMapping

**Comment by MaciejFrackowiak** [comment]
Proszę zmień nagłówek na wersję public i zasób będzie działać -> application/vnd.allegro.public.v1+json

**Comment by copyact** [comment]
Witam, czy ten zasób działa aktualnie? Od wczoraj mam błąd not found:(

**Comment by MaciejFrackowiak** [comment]
@copyact Tak, [GET /order/line-item-id-mappings](https://developer.allegro.pl/documentation/#operation/findMapping) działa prawidłowo. W poście #3248 wyjaśniliśmy natomiast usunięcie zasobu GET /payments/payment-id-mappings.
