### ISSUE TITLE
Problem z aktywacją ofert ze szkiców 

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#3162]
Metodą PUT na zasobie 
https://api.allegro.pl/sale/offer-publication-commands/9ad96efa-8b0f-11ea-b2d9-2fa759a59ad5
UUID : prawdziwy

Próbuję aktywować szkice 100 ofert. 

zasób 
https://api.allegro.pl/sale/offer-publication-commands/9ad96efa-8b0f-11ea-b2d9-2fa759a59ad5/tasks
w odpowiedzi dla każdej oferty pokazuje taki problem:

 "message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-04-30T18:23:25.507Z","finishedAt":"2020-04-30T18:23:26.96Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]

Ręcznie można te szkice wystawiać bez problemów. Formularz wystawiania nie pokazuje żadnego błędu. 

Bardzo proszę o pomoc !!!!

**Comment by MaciejFrackowiak** [comment]
Widzę, że obecnie oferty, z którymi miałeś problem są już pomyślnie wystawione na sprzedaż.

**Comment by crazyhtm** [comment]
Te oferty wystawiłem ręcznie. Mamy następne 2500 których ręcznie już nie wystawię.

Dziś jeszcze nie sprawdzałem czy zasób działa. 

Dlaczego ręcznie mogłem je wystawić a przez API nie?

**Comment by MaciejFrackowiak** [comment]
Nie znalazłem przyczyny dla wcześniejszych ofert - niestety, są one już aktywne, więc nijako możliwość ich zwalidowania jest już niemożliwa. Jeżeli natrafisz na podobny przypadek, proszę zgłoś to i wówczas mam nadzieję, że uda się to sprawdzić zanim będą aktywne.

**Comment by crazyhtm** [comment]
Ok, podjąłem kolejną próbę:
commandId - **c7ee732e-8e37-11ea-b1b6-ef6555876fc8** 
tym razem 8 aukcji, odpowiedź API:

 {"errors":[{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[3].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[5].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[1].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[4].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[0].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[7].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[2].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[6].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[3].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[1].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[5].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[0].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[2].type","userMessage":"may not be null"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[7].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be empty","details":"Invalid value: null","path":"offerCriteria[4].offers","userMessage":"may not be empty"},{"code":"VALIDATION_ERROR","message":"may not be null","details":"Invalid value: null","path":"offerCriteria[6].type","userMessage":"may not be null"}]}


co ciekawe, nie powiodła się próba wystawienia tych samych aukcji zbiorczo przez stronę komendą "wznów". Natomiast mogę wystawiać aukcje pojedyńczo za pomocą edycji.

Próba zbadania sytuacji komendą:
sale/offer-publication-commands/c7ee732e-8e37-11ea-b1b6-ef6555876fc8/tasks

zakończyła się odpowiedzią:
{"errors":[{"code":"COMMAND_NOT_FOUND","message":"Command not found.","details":null,"path":"","userMessage":"Command not found."}]}

Nie wiem czy ja coś źle robię? Ale do zeszłego tygodnia wszystko działało prawidłowo.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, komendy "c7ee732e-8e37-11ea-b1b6-ef6555876fc8" również i ja nie mogę odnaleźć w logach - stąd odpytanie GET /sale/offer-publication-commands/c7ee732e-8e37-11ea-b1b6-ef6555876fc8/tasks zwróciło poprawny błąd.

**Comment by crazyhtm** [comment]
Ok, podjąłem kolejną próbę to już chyba 5 może teraz będziesz w stanie coś odpowiedzieć:

wywołanie:

curl -X PUT "https://api.allegro.pl/sale/offer-publication-commands/8f9ee40e-8eaa-11ea-ad34-670ea027411a" -H "Authorization: Bearer XXXXX"  -H "Accept: application/vnd.allegro.public.v1+json" -H "Content-type: application/vnd.allegro.public.v1+json" -d '{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"9226295198"},{"id":"9226295220"},{"id":"9226295231"},{"id":"9226295253"},{"id":"9226295266"},{"id":"9226295277"},{"id":"9226295307"},{"id":"9226295328"}],"type":"CONTAINS_OFFERS"}]}'


Potem :

https://api.allegro.pl/sale/offer-publication-commands/8f9ee40e-8eaa-11ea-ad34-670ea027411a/tasks

{"tasks":[{"offer":{"id":"9226295266"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.935Z","finishedAt":"2020-05-05T08:31:02.347Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295277"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.935Z","finishedAt":"2020-05-05T08:31:02.192Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295328"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.935Z","finishedAt":"2020-05-05T08:31:02.348Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295307"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.936Z","finishedAt":"2020-05-05T08:31:02.28Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295198"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.936Z","finishedAt":"2020-05-05T08:31:02.345Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295220"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.936Z","finishedAt":"2020-05-05T08:31:02.346Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295231"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.936Z","finishedAt":"2020-05-05T08:31:02.304Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]},{"offer":{"id":"9226295253"},"message":"Could not change offer publication status. You cannot activate an invalid offer.","status":"FAIL","scheduledAt":"2020-05-05T08:31:01.937Z","finishedAt":"2020-05-05T08:31:02.493Z","field":"publication","errors":[{"code":"UnknownError","message":"You cannot activate an invalid offer.","details":null,"path":null,"userMessage":"You cannot activate an invalid offer."}]}]}

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład - problem generuje parametr Producent, którego przekazujesz poprawnie, jednak walidator zwraca inne jego id - przekazałem już sprawę do weryfikacji.

**Comment by crazyhtm** [comment]
Ok, dziękuję. Czekam na informację.

**Comment by crazyhtm** [comment]
Czy są jakieś informacje o naszym problemie?

**Comment by MaciejFrackowiak** [comment]
Nie, jeszcze nie otrzymałem zwrotnej informacji - zamieszczę tu odpowiedź, gdy uzyskam szczegóły.

**Comment by crazyhtm** [comment]
W dalszym ciągu nie wiadomo co się dzieję? 
Dlaczego nie mogę wystawić naszych aukcji?

Chciałem tylko powiedzieć że problem jest cały czas taki sam, nic się nie zmieniło.
Czekam na jakąś informację!

**Comment by MaciejFrackowiak** [comment]
Zgodnie z moim poprzednim postem zamieszczę tu odpowiedź, gdy tylko otrzymam wyjaśnienie. Testowo, przed chwilą podjąłem próbę wystawienia oferty na wzór jednej z Twoich - bez przeszkód dodałem nowy draft, który następnie aktywowałem. Być może warto, abyś spróbował dodać nowe drafty, a w kolejnym kroku je aktywować.

**Comment by crazyhtm** [comment]
Pojedyńcze drafty można aktywować bez problemu, ale my mamy 2500 akcji do wystawienia tylko w tym rzucie.
A API nie działa. 
Jeszcze 2 czy 3 tygodnie temu na innym koncie wystawiałem po kilkaset podobnych aukcji na raz i wszystko było ok.

**Comment by MaciejFrackowiak** [comment]
Przeprowadziliśmy proces aktualizacji ofert, w których pojawiał się komunikat z nieprawidłowym ID parametru. Widzę, że oferta ze zgłoszenia - 9226295253 jest także aktywna. Proszę sprawdź, czy obecnie problem już nie występuje.

**Comment by crazyhtm** [comment]
Niestety nic się nie zmieniło, próbowałem dosłownie przed chwilą :

wywołanie:
https://api.allegro.pl/sale/offer-publication-commands/1ae069ce-9514-11ea-b9a2-c30e5723751e
dla draftów: 
{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"9226284925"},{"id":"9226294950"},{"id":"9226294966"},{"id":"9226295016"},{"id":"9226295049"},{"id":"9226295098"},{"id":"9226295172"}],"type":"CONTAINS_OFFERS"}]}

zwraca
{"id":"1ae069ce-9514-11ea-b9a2-c30e5723751e","taskCount":{"total":0,"success":0,"failed":0}}

a sprawdzenie:
https://api.allegro.pl/sale/offer-publication-commands/1ae069ce-9514-11ea-b9a2-c30e5723751e/tasks
{"tasks":[]}

**Comment by TimothyKoval** [comment]
Nie używasz przypadkiem "zużytych" id-mów?

**Comment by crazyhtm** [comment]
Nie nie, to są id-ki moich draftów. 
Problem w tym że teraz nawet błędów nie zwraca tylko pustą tasks[]. Tak jakby wogóle nie było komendy.

**Comment by MaciejFrackowiak** [comment]
@crazyhtm Widzę, że z podanej grupy tylko jedna oferta pojawiła się w serwisie, dla pozostałej szóstki niestety błąd dalej widnieje (co prawda w innej odmianie dla części z nich). Przekazałem już spostrzeżenie do dalszej analizy, wrócę z odpowiedzią.
