### ISSUE TITLE
Pobranie ostatniej aukcji promowanej i niepromowanej

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#3163]
Witam, jak mogę pobrać ostatnią wystawioną aukcję niepromowaną?

Wykorzystuję metodę offers/listing:

$params=array('seller.id' => '0098','sort' => '-startTime', 'limit' => 100, 'offset' => 0);
$response=$api->offers->listing()->get($params);

w pętli wyciągam zasoby
$response['items']['promoted'][$i]['id'];

Promowaną ofertę zwraca bez problemu, jednak kiedy chcę pobrać ostatnio wystawioną ofertę bez promocji, to muszę najpierw ustawić offset na ilość ofert promowanych. 
Czyli skrypt musi najpierw obliczyć ilość ofert promowanych, i dopiero ustawić offset żeby zwrócić ofertę która nie jest promowana.

Czy jest możliwość zwrócenia pierwszej, ostatnio wystawionej oferty niepromowanej?

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości - wyszukiwarka na stronie WWW również nie pomija ofert promowanych, dlatego zasób API oddaje jej prawidłowość.
