### ISSUE TITLE
Pusty journal - brak eventów

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#3166]
Jest sobie konto, jest na nim około 20k ofert, a `/sale/offer-events` zwraca pustą listę...

- Czy to jest jakieś zamierzone zachowanie czy też błąd?
- Lista jest pusta, bo po prostu eventy się "przedawniły"?
- Jaki jest "timeout" dla eventu zanim zniknie z journala?

**Comment by PrzemyslawLukanowski** [comment]
Dziennik ofertowy /sale/offer-events zwraca informacje z ostatnich 24 godzin. Zweryfikowałem działanie - na tę chwilę otrzymuję prawidłowe wyniki. Czy w Twoim przypadku w dalszym ciągu otrzymujesz pustą listę? Jeśli tak, wyślij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz GitHub #3166.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
Dalej pusto, przesłałem request/response przez formularz

**Comment by PrzemyslawLukanowski** [comment]
W Twoim requescie dla parametru "from" przekazałeś nieprawidłową wartość "MA".  Widzę w logach, że pozostałe żądania dla tego sprzedawcy posiadały już poprawną wartość.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
Wasz system tak samo przyjmuje 'MA' jak i 'MA=='  więc to nie to
po tym co napisałeś, to po prostu brak akcji na koncie w ostatnich 24h

no a teraz jest coś w journalu, bo dzisiaj w nocy trochę ofert powznawiałem - więc zaczęło się coś dziać :)

**Comment by PrzemyslawLukanowski** [comment]
Wspomniałeś o 20k ofert, więc nie przypuszczałem, że powód może być tak prosty :)
