### ISSUE TITLE
Pobranie najnowszego eventu oferty

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3167]
Czy jest możliwość pobrania najnowszego eventu dla ofert tak jak dla zamówień ([https://developer.allegro.pl/documentation/#operation/getOrderEventsStatisticsUsingGET](https://developer.allegro.pl/documentation/#operation/getOrderEventsStatisticsUsingGET))?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiego endpointu dla dziennika ofertowego. Wskaż proszę potrzebę, a przekażę to jako sugestię do zespołu odpowiedzialnego za rozwój API.

**Comment by AnimalDEV** [comment]
Po prostu chciałbym pobierać eventy dla ofert rozpoczynając od najnowszego (przy pierwszym pobraniu), ale jak te eventy są tylko z 24h to pewnie nie ma ich ogromnej ilości i mogę pobierać wszystkie.
