### ISSUE TITLE
GET /sale/offer-variants/<setId> zwraca 404 dla 1 przypadku

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3169]
Mam sobie odwołanie `GET /sale/offer-variants/b92c3e40-88a2-4866-98cf-de16ffdac964` i zwraca 404 czyli tak jakby nie było takiego wariantu. Podczas gdy metoda GET /sale/offer-variants, która listuje wszystkie warianty zwraca właśnie ten wariant. Poniżej fragment kodu:

```
[7] => Array
        (
            [id] => b92c3e40-88a2-4866-98cf-de16ffdac964
            [name] => Mini BARTEK brązowy 22
        )
```

Trace-id => 93e4b9fe65133b4

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdzam problem. Przekazałem go do odpowiedniego zespołu.

**Comment by pietrach** [comment]
Coś wiadomo w tej sprawie ?

**Comment by PrzemyslawLukanowski** [comment]
Prośba o cierpliwość. Poinformuję w tym wątku po rozwiązaniu problemu.

**Comment by pietrach** [comment]
Teraz jeszcze inny przypadek. Podejrzewam, że chodzi o to samo co powyżej tylko, że u innego klienta.

Wariant o id = fb12ba3c-7ef4-46e3-809e-d056c701b4a2 niechce się usunąć poprzez API.
Zwrócony błąd to:

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => 
                )
        )
)
```

**Comment by PrzemyslawLukanowski** [comment]
Tak, to podobny problem. Dołączam ten przykład do zgłoszenia.

**Comment by pietrach** [comment]
@PrzemyslawLukanowski a czy w tym temacie coś już wiadomo ?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie. Pamiętam o tym zgłoszeniu i jak tylko otrzymam konkretne informację, dam znać w tym wątku.
