### ISSUE TITLE
User.id Jak zdobyć

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#317]
Jak mogę zdobyć user.id np: dla mojego loginu mg-software?

potrzebuje pobrać size-table.

**Comment by PawelTaberski** [comment]
Jak przejdziesz przykładowo do ocen swojego danego użytkownika to w pasku url będziesz miał widoczny user id. Rozumiem, że chodzi tobie o środowisko testowe, bo na produkcyjnym nie widze usera o takim loginie. Jeśli tak to ma on user.id 43999439

**Comment by SoftWareMG** [comment]
tak, tak miałem na myśli sandboxa.
Dzięki.
