### ISSUE TITLE
Brak możliwości wystawiania ofert

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3170]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-id: 
Nie udane: `c8201a8c93e292d`
Udane: `5c2dbbbe87baa8da`
Nieudane taski: `ab058554a076b5db` 

Kiedy tworzę ofertę na `/sale/offers` dostaje w opdpowiedzi w validation 

`"errors:[{"code":"VALIDATION_ERROR","message":"ERR_NOT_EXISTING_VALUE_IN_ATTRIBUTE","details":"","path":"","userMessage":""}]`,

po kilku próbach tworzenia się udaje, ale `/sale/offer-publication-commands/c763fae2-eff9-4a6d-9c95-6bc692168c2e/tasks`(możliwe, że to może nie być do tych ofert)  zwraca

`{"tasks":[{"offer":{"id":"6208096788"},"message":"Could not change offer publication status. Podana wartość parametru Color(127448) nie istnieje w słowniku.","status":"FAIL","scheduledAt":"2020-05-04T12:51:29.37Z","finishedAt":"2020-05-04T12:51:31.111Z","field":"publication","errors":[{"code":"ConstraintViolationException.ValidAttributes","message":"Podana wartość parametru Color(127448) nie istnieje w słowniku.","details":null,"path":"attributes","userMessage":"Podana wartość parametru Color(127448) nie istnieje w słowniku."}]}]}`

Ustawiam wartość dla parametru `127448` wartość `127448_1`, i jest ten id wartości zwracany dla parametrów w tej kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdzam problem. Przekazałem go do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@AnimalDEV Problem nie powinien już występować.

**Comment by AnimalDEV** [comment]
Potwierdzam problemu już nie ma.
