### ISSUE TITLE
Metoda POST /sale/offer-variants oraz PUT /sale/offer-variants zwraca niejednoznaczne błędy

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3171]
Obie te metody zwracają poniższy błąd przy czym metoda PUT tylko czasem. Jaka jest jego przyczyna ? Czy niechodzi o to, że oferty, które próbuje dodać do nowego wariantu lub zaktualizować  istniejący wariant należą do innych wariantów ? Jeśli tak czy nie mógł by to być inny komunikat. Np. tak który już zwracacie w przypadku metody PUT, że są wyspecyfikowane oferty i komunikat, że one "wchodzą w skład innej oferty wielowariantowej". Dużo by to ułatwiło.

  | [{"code":"VALIDATION_ERROR","message":"Nie mou017cna utworzyu0107  oferty wielowariantowej.","details":null,"path":null,"userMessage":"Nie  mou017cna utworzyu0107 oferty wielowariantowej."}]
-- | --

Odpowiednio trace-id:

(POST) 540a7dcdc90cd436
(PUT) c64f28ad0bdab2a9

To samo POST o trace-id 6c29a1d3831d944

  | [{"code":"VALIDATION_ERROR","message":"Podany atrybut kolor/wzu00f3r  nie mou017ce zostau0107 dopasowany do istnieju0105cych ofert  7833781228, 8088744180, 8276359667,  8315909970.","details":null,"path":null,"userMessage":"Podany atrybut  kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych  ofert 7833781228, 8088744180, 8276359667, 8315909970."}]
-- | --

Co to oznacza, że "Podany atrybut  kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych  ofert" ?

**Comment by pietrach** [comment]
To samo tutaj. Trace id => 9eee10607fa3f7b2. Nie jestem w stanie zrozumieć dlaczego niechce się stworzyć wariant. Każda z tych ofert nie jest w żadnym innym wariancie i rzuca błędem

> Podany atrybut kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych ofert

**Comment by pietrach** [comment]
I czy można coś zrobić aby Wasz automat nie łączył w warianty ?

**Comment by pietrach** [comment]
Czy ktoś wogóle się tym zajął :-) ?

**Comment by PrzemyslawLukanowski** [comment]
Prośba o cierpliwość. Jeżeli ktoś przypisał do siebie zgłoszenie, to masz pewność, że je analizujemy.

W przypadku komunikatu 

> "Podany atrybut kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych ofert" ?"

 Oznacza, że oferty z żądania powinny mieć ustawioną tą samą wartość w polu colorPattern, ponieważ mają ustawione to samo pierwsze zdjęcie.

Dla trace-id 540a7dcdc90cd436 - problem generuje to, że dla ofert z żądania wystawiłeś już wcześniej podobne oferty, które są duplikatami, np. dla *****94582 duplikatem jest *****46573 (rozmiar 21), dla *****93960 duplikatem jest  *****41557 (rozmiar 24), etc. dla trace id c64f28ad0bdab2a9 wysyłasz m.in. ofertę *****29714, która jest duplikatem *****36169 . Rozwiążaniem tego problemu będzie nie wystawianie duplikatów ofert. 

Odpowiedni zespół pracuje już nad doprecyzowaniem komunikatu błędów, taka by były one czytelniejsze.

> I czy można coś zrobić aby Wasz automat nie łączył w warianty ?

Nie ma takiej możliwości. Czy możesz wskazać, jaki problem chciałbyś dzięki temu rozwiązać? Podaj proszę przykład oferty, którą połączyliśmy wbrew Twoim oczekiwaniom.

**Comment by pietrach** [comment]
Jeszcze mam taki błąd podczas wystawiania ofert (trace Id = 1deb1c639d7ddce1)
`
{"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Nieprawidu0142owe u017cu0105danie."}],"offerId":"","offerTitle":""}`

Wszystkie oferty mi się wystawiły tylko ta jedna nie. Co jest przyczyną bo nie mogę znaleźć błędu.

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na problem z Twoją strukturą JSON. Czy możesz ją tutaj wkleić? Usuń przy tym wrażliwe dane.

**Comment by pietrach** [comment]
```
Array
(
    [name] => Yoskine JAPOŃSKI GRAVITY-LIFTING KREM 70+ 50ml
    [category] => Array
        (
            [id] => 258462
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 224017
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => okinawa4
                        )

                    [rangeValue] => 
                )

            [2] => Array
                (
                    [id] => 129369
                    [valuesIds] => Array
                        (
                            [0] => 129369_212
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [3] => Array
                (
                    [id] => 215870
                    [valuesIds] => Array
                        (
                            [0] => 215870_271998
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [4] => Array
                (
                    [id] => 129434
                    [valuesIds] => Array
                        (
                            [0] => 129434_8
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [5] => Array
                (
                    [id] => 129469
                    [valuesIds] => Array
                        (
                            [0] => 129469_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [6] => Array
                (
                    [id] => 215866
                    [valuesIds] => Array
                        (
                            [0] => 215866_271942
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [7] => Array
                (
                    [id] => 129569
                    [valuesIds] => Array
                        (
                            [0] => 129569_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [8] => Array
                (
                    [id] => 206338
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 50
                        )

                    [rangeValue] => 
                )

            [9] => Array
                (
                    [id] => 215766
                    [valuesIds] => Array
                        (
                            [0] => 215766_271226
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [10] => Array
                (
                    [id] => 215770
                    [valuesIds] => Array
                        (
                            [0] => 215770_271362
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

        )

    [ean] => 5900525065230
    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/11c39f/8c6c7dd94a6989b185794adfad39
                                        )

                                    [1] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 
Yoskine Okinawa Green Caviar
JAPOŃSKI GRAVITY-LIFTING KREM GŁĘBOKO ODBUDOWUJĄCY 70+

Cena: 60 zł

 

Wiek od: 70+

                                        )

                                )

                        )

                    [1] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 

Japoński Gravity-Lifting, luksusowy krem odbudowujący i wypełniający najgłębsze zmarszczki dla skóry 70+ z zielonym kawiorem z algi Umibudo. Zawiera kombinację skoncentrowanych składników ujędrniających oraz endoliftingujących, czyli napinających skórę od wewnątrz. Krem stosowany regularnie sprawia, że cera staje się aksamitnie gładka.

UMIBUDO SEA LIFT

Zaawansowany kompleks przeciwzmarszczkowy łączący ekstrakt z zielonego kawioru (Alga Umibudo) i nowoczesne, zagęszczające skórę Matix-Peptydy. Doskonale regeneruje, liftinguje oraz redukuje długość i głębokość zmarszczek.

7-PEPTIDE REPAIR TOTAL-LIFT

Silnie naprawczy kompleks pro-kolagenowy z Tetrapeptide-7, który wypełnia najgłębsze zmarszczki, bruzdy oraz utrwalone linie mimiczne. Intensywnie ujędrnia, a także znakomicie liftinguje skórę na policzkach.

TSUBAKI BEAUTY OIL

Bogaty w kwasy Omega-6 i Omega-9 olej z japońskiej kamelii z wyspy Jeju. Odbudowuje warstwę lipidową skóry, odżywia i nawilża.

Stosowanie: Codziennie rano i wieczorem stosować krem na oczyszczoną skórę twarzy i szyi. Doskonale sprawdza się jako baza pod makijaż. Dla wzmocnienia efektu stosować pod krem serum na twarz i pod oczy YOSKINE OKINAWA GREEN CAVIAR.

                                        )

                                )

                        )

                    [2] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/11aecb/b6b2e385434aa2c20fbfdd2ba9a8
                                        )

                                )

                        )

                )

        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/11c39f/8c6c7dd94a6989b185794adfad39
                )

            [1] => Array
                (
                    [url] => https://a.allegroimg.com/original/11aecb/b6b2e385434aa2c20fbfdd2ba9a8
                )

        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 60
                    [currency] => PLN
                )

        )

    [stock] => Array
        (
            [available] => 999995
            [unit] => UNIT
        )

    [publication] => Array
        (
            [duration] => 
            [status] => INACTIVE
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => 26d89645-fea7-4924-aed3-59b7aa353d7e
                )

            [handlingTime] => PT24H
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => fbf9c919-ed66-4d2e-9833-c956beb35dc0
                )

            [returnPolicy] => Array
                (
                    [id] => 1694d787-0cd1-412f-a1c6-1f5940f8d24a
                )

        )

    [promotion] => Array
        (
            [emphasized] => 
        )

    [external] => Array
        (
            [id] => 1844/0
        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => Wojewodztwo
            [city] => Miejscowosc
            [postCode] => kod pocztowy
        )

)
```

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz wkleić te dane w formacie cURL? Dzięki temu łatwiej będzie mi odszukać problematyczny fragment. Na tę chwilę widzę błędne wartości w sekcji location.

**Comment by pietrach** [comment]
Jesli chodzi o location to celowo to wpisalem. Zaraz wrzucę

**Comment by pietrach** [comment]
**Request:**

```
POST https://api.allegro.pl/sale/offers HTTP/1.1
Accept-Encoding: gzip,deflate
Accept-Language: pl-PL
Authorization: Bearer <token>
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
Content-Length: 3480
Host: api.allegro.pl
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

{"name":"Yoskine JAPOŃSKI GRAVITY-LIFTING KREM 70+ 50ml","category":{"id":"258462"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["okinawa4"],"rangeValue":null},{"id":"129369","valuesIds":["129369_212"],"values":[],"rangeValue":null},{"id":"215870","valuesIds":["215870_271998"],"values":[],"rangeValue":null},{"id":"129434","valuesIds":["129434_8"],"values":[],"rangeValue":null},{"id":"129469","valuesIds":["129469_2"],"values":[],"rangeValue":null},{"id":"215866","valuesIds":["215866_271942"],"values":[],"rangeValue":null},{"id":"129569","valuesIds":["129569_1"],"values":[],"rangeValue":null},{"id":"206338","valuesIds":[],"values":["50"],"rangeValue":null},{"id":"215766","valuesIds":["215766_271226"],"values":[],"rangeValue":null},{"id":"215770","valuesIds":["215770_271362"],"values":[],"rangeValue":null}],"ean":"5900525065230","description":{"sections":[{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f52e\/3f9136c04fc5a5c61202dfc61993"},{"type":"TEXT","content":"<h2>Yoskine Okinawa Green Caviar<\/h2><h1>JAPOŃSKI GRAVITY-LIFTING KREM GŁĘBOKO ODBUDOWUJĄCY 70+<\/h1><p>Cena: <b>60 zł<\/b><\/p><p>&nbsp;<\/p><p>Wiek od: <b>70+<\/b><\/p>"}]},{"items":[{"type":"TEXT","content":"<p><b>Japoński Gravity-Lifting, luksusowy krem odbudowujący i wypełniający najgłębsze zmarszczki dla skóry 70+ z zielonym kawiorem z algi Umibudo.<\/b> Zawiera kombinację skoncentrowanych składników ujędrniających oraz endoliftingujących, czyli napinających skórę od wewnątrz. Krem stosowany regularnie sprawia, że cera staje się aksamitnie gładka.<\/p><p><b>UMIBUDO SEA LIFT<\/b><\/p><p>Zaawansowany kompleks przeciwzmarszczkowy łączący ekstrakt z zielonego kawioru (Alga Umibudo) i nowoczesne, zagęszczające skórę Matix-Peptydy. Doskonale regeneruje, liftinguje oraz redukuje długość i głębokość zmarszczek.<\/p><p><b>7-PEPTIDE REPAIR TOTAL-LIFT<\/b><\/p><p>Silnie naprawczy kompleks pro-kolagenowy z Tetrapeptide-7, który wypełnia najgłębsze zmarszczki, bruzdy oraz utrwalone linie mimiczne. Intensywnie ujędrnia, a także znakomicie liftinguje skórę na policzkach.<\/p><p><b>TSUBAKI BEAUTY OIL<\/b><\/p><p>Bogaty w kwasy Omega-6 i Omega-9 olej z japońskiej kamelii z wyspy Jeju. Odbudowuje warstwę lipidową skóry, odżywia i nawilża.<\/p><p><b>Stosowanie:<\/b> Codziennie rano i wieczorem stosować krem na oczyszczoną skórę twarzy i szyi. Doskonale sprawdza się jako baza pod makijaż. Dla wzmocnienia efektu stosować pod krem serum na twarz i pod oczy YOSKINE OKINAWA GREEN CAVIAR.<\/p>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/115aa5\/4871fcbf4df4ad3a8d6b6f8888cc"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11f52e\/3f9136c04fc5a5c61202dfc61993"},{"url":"https:\/\/a.allegroimg.com\/original\/115aa5\/4871fcbf4df4ad3a8d6b6f8888cc"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":60,"currency":"PLN"}},"stock":{"available":"999995","unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE"},"delivery":{"shippingRates":{"id":"26d89645-fea7-4924-aed3-59b7aa353d7e"},"handlingTime":"PT24H"},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"fbf9c919-ed66-4d2e-9833-c956beb35dc0"},"returnPolicy":{"id":"1694d787-0cd1-412f-a1c6-1f5940f8d24a"}},"promotion":{"emphasized":false},"external":{"id":"1844\/0"},"location":{"countryCode":"PL","province":"MAZOWIECKIE","city":"Warszawa","postCode":"09-152"}}
```

**Response:**

```
HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 2b640ac293296bec
date: Tue, 05 May 2020 11:57:20 GMT
x-content-type-options: nosniff
content-type: application/json
x-envoy-upstream-service-time: 10
transfer-encoding: chunked

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}
```

**Comment by PrzemyslawLukanowski** [comment]
Request wygląda na prawidły, jednak w polu stock.available powineneś ustawić wartość mniejszą niż 100 000. Czy po tej zmianie otrzymujesz prawidłową odpowiedź?

**Comment by pietrach** [comment]
To nie do końca to proszę chwilę poczekać zaraz może mi się uda to wydobyć

**Comment by pietrach** [comment]
Wpiswałem 10000 i nic to nie zmieniło. Zaraz podeślę prawidłowy request

**Comment by pietrach** [comment]
Chyba musieliście zrobić coś po swojej stronie bo nagle poszło a ja nic nie zmieniałem :-)

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się rozwiązac problem :)

**Comment by pietrach** [comment]
A od kiedy weszło to ograniczenie że ilość nie może być większa od 100 000 ?

**Comment by PrzemyslawLukanowski** [comment]
Takie ograniczenie mamy już od 2018 roku.

**Comment by pietrach** [comment]
Odnośnie tego

> Oznacza, że oferty z żądania powinny mieć ustawioną tą samą wartość w polu colorPattern, ponieważ mają ustawione to samo pierwsze zdjęcie.
> 
> Dla trace-id 540a7dcdc90cd436 - problem generuje to, że dla ofert z żądania wystawiłeś już wcześniej podobne oferty, które są duplikatami, np. dla *****94582 duplikatem jest *****46573 (rozmiar 21), dla *****93960 duplikatem jest *****41557 (rozmiar 24), etc. dla trace id c64f28ad0bdab2a9 wysyłasz m.in. ofertę *****29714, która jest duplikatem *****36169 . Rozwiążaniem tego problemu będzie nie wystawianie duplikatów ofert.

To właśnie zamierzone działanie. Mamy obuwie w gat I i II i chcemy aby oba gatunki tworzyły oddzielne warianty. Zdjęcia mają zazwyczaj takie same.

**Comment by PrzemyslawLukanowski** [comment]
Wiemy o tym problemie, te sytuacje powinny już pojawiać się coraz rzadziej. Na tę chwilę możesz spróbować zakończyć i wznowić ofertę ****007894. Czy te duplikaty róźnią się którymś parametrem oprócz wartości "gatunek" w opisie oferty?

**Comment by pietrach** [comment]
Zakończyłem i wznowiłem w panelu Allegro

**Comment by pietrach** [comment]
Obecnie w naszym systemie wisi 30 ofert, których połączenie w warianty ma podobny problem

**Comment by imper86** [comment]
> Nie ma takiej możliwości. Czy możesz wskazać, jaki problem chciałbyś dzięki temu rozwiązać? Podaj proszę przykład oferty, którą połączyliśmy wbrew Twoim oczekiwaniom.

Wtrącę się do wątku - powód jest bardzo prosty - niektórzy klienci wolą swoje "customowe" rozwiązania zamiast Waszych automatów. Rozumiem, że duża część programów nie ma funkcji łączenia ofert w zestawy wielowariantowości, no ale są również takie które mają.

Ewentualnie drugim rozwiązaniem byłaby możliwość odfiltrowania automatycznych ofert korzystając z GET /sale/offer-variants. Taka możliwość jest na froncie, więc nie sądzę żeby dodanie filtra do api było jakimś problemem. W chwili obecnej w moich programach robię to w ten sposób, że pobieram wszystkie zestawy strona po stronie i weryfikuję po id czy dany zestaw został utworzony przez mój system czy nie. Strasznie niewydajne rozwiązanie, ale jedyne działające.

**Comment by pietrach** [comment]
@imper86, @PrzemyslawLukanowski chodzi o to, że to działało dobrze do maja. Czyli mój mechanizm był w stanie rozwalić taki customowy wariant i stworzyć na nowo po swojemu. Ale teraz przy próbie stworzenia rozpoznaje, że jest już gdzieś takie samo zdjęcie i nie można stworzyć. Nie wiem czemu to tak zaczęło działać. Wcześniej nie mieliśmy z tym problemów.

**Comment by PrzemyslawLukanowski** [comment]
@pietrach Tak jak wspomniałem przy okazji innego wątku, tego typu problemy dla nowych ofert powinny pojawiać się już coraz rzadziej. Na tę chwilę możesz spróbować zakończyć i wznowić problematyczne oferty.
@imper86 Dziękuję za sugestię, przekażę ją do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@imper86 Czy mógłbyś jeszcze podać przykład takiej oferty, która została utworzona wbrew Twoim oczekiwaniom? Np. w jaki sposób oferty zostały przez nas połączone, a jak chciałbyś, żeby zostały połączone.

**Comment by pietrach** [comment]
Czy coś w sprawie tych problemów związanych z grupowaniem w warianty jest robione ? Bo z 30 zrobiło się ju 50 problematycznych wariantów. Kasuje warianty próbuje utworzyć na nowo i cały czas to samo. Zakańczałem i wznawiałem aukcje. Wszystko zaczęło się od maja. Poniżej trace id:

de3673b766ae052d
5b2bfc917f939ce3
683f5091a042e3bd
87cd095404d72ccb
2348615de07e2294
78f840b3eee3ec55
e8117af67d584cce
6fd473548cef71fa
7125a7671e1bbd79
9030bcde0f840e59
8f062689921fd34d
5700c7dba6281984
9fa3da8ef5ed1843
bf9d0725730ff56d
b843e7a11b875766
af342fd502ff649a
c2ba792e3508de14
aafa844d0814ee43
f5bcf1df6aa2511d
afbf695da32094de
dfb0661ab8d189c8
cfeb20e7119e9a4
ec95c1516e69cbcf
44c69fc60c60e888
d14304909d875e94
7263223dbc1d40c
a6d3eba8b409dfc5
3ef618d27fc27dee
727393000903b866
eefc26b486328842
38de7ea815befce0
b295a966a0ce498f
342f38749e66422c
5138525a056473af
ae6a096078977472
5a1f77d639e8a18a
ab7a6124d9bfd4e4
fc0acabb092bf613
17859d73e5d01189
a4212819a707dab
efcdd88c933aea7c

**Comment by pietrach** [comment]
> Wiemy o tym problemie, te sytuacje powinny już pojawiać się coraz rzadziej. Na tę chwilę możesz spróbować zakończyć i wznowić ofertę ****007894. Czy te duplikaty róźnią się którymś parametrem oprócz wartości "gatunek" w opisie oferty?

Raczej tylko gatunkiem i ceną ale na 100% nie wiem

**Comment by PrzemyslawLukanowski** [comment]
@pietrach Analizujemy jeszcze te przypadki, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Wracam z informacją. Jeżeli oferty mają takie samo zdjęcie i rozmiar, to będą identyfikowane jako duplikaty. Nie będzie tutaj miało wpływu rozróżnienie na gatunek. Moja wcześniejsza wiadomość mogła wprowadzić w błąd. Przypadki, które powinny wystepować coraz rzadziej, opisane są w wątkach #3012 i #3099.

**Problemy związane z komunikatem "Podany atrybut kolor/wzór nie może zostać dopasowany do istniejących ofert...":**

TraceID: ea7b445f9a0a7058
występują duplikaty: 7831193669 i 7831157724 oraz 9241737232 i 7833086571,

TraceID: 7d91ddb659987300
występują duplikaty: 7767483608 i 7656489701,

Trace ID: 14a6671f616089e9
oferta 9238325300 ma inne pierwsze zdjęcie niż 9189824616, 9189814496 i 9238335520

Trace ID: 502937285e917d65
występują duplikaty: 7831186110 i 7831140087,

Dla każdej oferty z takim samym zdjęciem powinna być identyczna wartość colorPattern (nie może być pusta i musi być krótsza niż 50 znaków).

**Problem związany z komunikatem "Oferty wchodzą w skład innych ofert wielowariantowych..."**

Trace ID: 262d199645509b35
Widzimy w logach, że ta oferta wielowariantowa jest cyklicznie usuwana i dodawana co ~20 minut. Przykładowy request pomoże nam przeanalizować ten problem.

**Problemy związane z komunikatem "Nie można utworzyć oferty wielowariantowej"**

Trace ID: 4dcadb1c8d533b69

Dla oferty 8522782721, która ma wchodzić w skład oferty wielowariantowej, istnieje duplikat 8702619224. 

Trace ID: ec9ef64cc1e1feb
Występują duplikaty: 8434802694 i 7833092044, 8417852810 i 8276386128, 8434939966 i 7831177443, 7831177243 i 7831160706, 7831160881 i 7831177327.

Trace ID: d26006e1c1d4191e
Występują duplikaty 9081665740 i 7768458907.

Trace ID: a2f882f1ea9d9c13
Występują duplikaty 9197829714 i 9197836169.

**Comment by pietrach** [comment]
@PrzemyslawLukanowski a co jeśli byśmy do zdjęcia głównego dla gatunku np. II dodawali jakiś jeden pixel inny ? Pomoże to ? W jaki sposób rozpoznajecie czy zdjęcie jest takie samo ?

**Comment by PrzemyslawLukanowski** [comment]
@pietrach Zgadza się, odrobinę inne zdjęcie spowoduje, że oferty nie będą duplikatami.

**Comment by pietrach** [comment]
@PrzemyslawLukanowski nawet 1 pixel jak będzie miał inny kolor ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, takie zdjęcie powinno zostać zidentyfikowane jako inne, niż te przesłane wcześniej.

**Comment by imper86** [comment]
> @imper86 Czy mógłbyś jeszcze podać przykład takiej oferty, która została utworzona wbrew Twoim oczekiwaniom? Np. w jaki sposób oferty zostały przez nas połączone, a jak chciałbyś, żeby zostały połączone.

Szczerze mówiąc to wszystkie... :) Mój klient handluje głównie butami i odzieżą. Automat łączy oferty w 99% tylko po rozmiarze. Klient natomiast chce łączyć też grupy produktowe z wiadomych powodów.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za odpowiedź, przekazuję ją do właściwego zespołu.

**Comment by TomKks** [comment]
Dołączam do kwestii niejednoznacznych błędów.
`{ "offers": [
  { "id": "9335415212","colorPattern": "6c8070cc-32b7-491b-86f1-030b5d17c2d3"},
  { "id": "9335226465", "colorPattern": "8abbaf9d-7b51-4fb0-971f-ec37a109199c"},
  { "id": "9335226525", "colorPattern": "2a9c96cf-856e-4ae5-a9da-189bc286757e"}],
		"name" : "20200601_05",
		"parameters" : [{"id": "color/pattern"}]
}`
Wyrzuca błąd:
"Oferta wielowariantowa musi posiadać dokładnie dwa parametry."

Aukcje świeżutkie, wystawione dzisiaj.

**Comment by PrzemyslawLukanowski** [comment]
W tej sytuacji w sekcji parameters musisz dodać id parametru 'rozmiar'. Pracujemy nad zmianą, która umożliwi tworzenie takich ofert wielowariantowych, z podaniem jedynie parametru "kolor/wzór".

**Comment by TomKks** [comment]
OK, rozumiem i widzę, że działa.
Dziękuję.

wt., 2 cze 2020 o 11:01 PrzemyslawLukanowski <notifications@github.com>
napisał(a):

**Comment by pietrach** [comment]
Co jest przyczyną, że niechce mi połączyćtego w warianty. Trace id to **f28f751aca6a54f5**
Komunikat:
`[{"code":"VALIDATION_ERROR","message":"Podany atrybut kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych ofert 7831270203, 7833617974, 9337059682.","details":null,"path":null,"userMessage":"Podany atrybut kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do istnieju0105cych ofert 7831270203, 7833617974, 9337059682."}]`

**Comment by PrzemyslawLukanowski** [comment]
Wynika to z tego, że obrazek dla oferty 7833617974 (https://a.allegroimg.com/original/111ca0/d1f6c3624fe48628b353084*****) minimalnie róźni się od pozostałych - możesz porównać rozmiar plików, jak i skorzystać z dostępnych narzędzi do porównywania obrazków. Użyj dokładnie tego samego zdjęcia, co w pozostałych ofertach.

**Comment by TomKks** [comment]
Dziękuję, już rozwiązałem problem.

śr., 1 lip 2020 o 13:21 PrzemyslawLukanowski <notifications@github.com>
napisał(a):

**Comment by pietrach** [comment]
A czy Np. tworząc warianty w ramach dwóch różnych color/pattern gdzie dla obydwu kolor/pattern zdjęcia są takie same to wtedy też otrzymam błąd, że należy stworzyć tylko jeden color/pattern ?

**Comment by PrzemyslawLukanowski** [comment]
> A czy Np. tworząc warianty w ramach dwóch różnych color/pattern gdzie dla obydwu kolor/pattern zdjęcia są takie same to wtedy też otrzymam błąd, że należy stworzyć tylko jeden color/pattern ?

Jeżeli zdjęcia są takie same, będziesz musiał użyć takiego samego color/Pattern, w innym przypadlu otrzymasz błąd.

> Bo np. chciałbym się dowiedzieć co jest przyczyną w tym wypadku c76fe084e7f6e531 (trace-id), że niechce połączyć

Zdjęcie główne dla oferty 9336992292 minimalnie róźni się od pozostałych. Jeżeli użyjesz zdjęcia głównego z pozostałych trzef ofert, utworzysz ofertę wielowariantową.

**Comment by pietrach** [comment]
A co oznacza taki komunikat "Nie można połączyć ofert ..... z powodu występujących duplikatów. Spróbuj ponownie z ofertami ...." trace-id = 4a1d965e156e52f4

**Comment by pietrach** [comment]
Po tych zmianach z końca kwietnia / początku maja dotyczących wariantów dzieją się cyrki. Do dziś poprawnie nie łączy. Czy jest szansa aby powrócić do poprzedniego algorytmu ?

**Comment by PrzemyslawLukanowski** [comment]
Zmieniliśmy treść komunikatów na bardziej czytelne, w Twoim przypadku jest to "Nie można połączyć ofert 8523370***, 8609019*** z powodu występujących duplikatów. Spróbuj ponowić z ofertami 8523370***.'", co oznacza, że próbujesz połączyć dwie identyczne oferty (rozmiar 21 i to samo zdjęcie główne). 
Zmiany związane są z przejściem na wersję public, nie planujemy wrócić do algorytmów z wersji beta. Czy możesz podać przykłady błędnie utworzonych ofert wielowariantowych? Przekażę je do odpowiedniego zespołu w celu analizy.
