### ISSUE TITLE
offers/listing czyli wyszukiwarka i polskie znaki

### ISSUE THREAD

**Issue by ziemekpr0** [allegro/allegro-api#3172]
Witam,
mam pewien problem jeżeli chodzi o wyszukiwanie ofert, w których we frazie pojawiają się "ogonki".
Powiedzmy, że wyszukuję "buty damskie" - jest ok i mam wyniki, natomiast jeżeli wpiszę "buty męskie" to niestety otrzymuję 0 wyników.
Jak to naprawić? Co jest potrzebne aby frazy z ogonkami zaczęły działać? Powinienem je jakoś przekonwertować, zastąpić ogonki odpowiednikami bez ogonków, czy?

**Comment by PrzemyslawLukanowski** [comment]
Podobne zgłoszenie otrzymaliśmy w wątku #2843. Nasze API poprawnie zwraca wyniki dla fraz z polskimi znakami, wygląda to na problem z narzędziem, z którego korzystasz.

**Comment by ziemekpr0** [comment]
Po co linkować do tematu, który jest zamknięty i do tego nie rozwiązany? U mnie w narzędziu kodowanie znaków ustawione jest na UTF-8 w strict mode, więc pytam jak jest po stronie allegro bo nie wiem jak mam to ustawić. Najlepsza odpowiedź "u nas działa" ale nie powiedzieć nic jak ustawić żeby działało. Super pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Poniżej znajdziesz przykład curla, który zwraca prawidłowe wyniki:

```
curl --location --request GET 'https://api.allegro.pl/offers/listing?phrase=męskie' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer (token)
```

lub

```
curl --location --request GET 'https://api.allegro.pl/offers/listing?phrase=m%C4%99skie' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer (token)
```

Niestety nie znam narzędzia, z którego korzystasz, dlatego nie mogę wskazać, co należałoby w nim ustawić.
