### ISSUE TITLE
Pobranie seller.id z loginu

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#3173]
Czy da radę pobrać seller.id poprzez API podając tylko login?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości. Czy możesz przedstawić, do czego jest Ci potrzebna taka funkcjonalność?

**Comment by ziemekpr0** [comment]
@PrzemyslawLukanowski przecież wczoraj był podobny temat, ja także zakładałem jakiś czas temu pytanie o to samo. Ile wyjaśnień jeszcze musicie zebrać żeby dodać PODSTAWOWĄ funkcjonalność do tego API jaką jest pobranie id usera?

**Comment by JanuszK2** [comment]
Może ja podam (równie) dobry powód:
Zasób offers/listing, w przypadku wyszukiwania wg. sprzedawcy wymaga podania seller.id.
Skąd go brać?

**Comment by rtnet-pl** [comment]
https://github.com/allegro/allegro-api/issues/3157
https://github.com/allegro/allegro-api/issues/3089
https://github.com/allegro/allegro-api/issues/2910
https://github.com/allegro/allegro-api/issues/2287
https://github.com/allegro/allegro-api/issues/1191

Najwyraźniej zapotrzebowanie jest wciąż za małe

**Comment by PrzemyslawLukanowski** [comment]
Dołączyłem Wasze komentarze do sugestii wspomnianej w wątku #3157.

**Comment by Onixarts** [comment]
To ja dorzucę jeszcze od nas. Licencjonujemy użytkowników po numerze ich konta w Allegro. Dopóki id dało się wyciągnąć np na stronie z komentarzami to było nam prościej namierzyć użytkownika, gdy w kontakcie z nami posługiwał się nazwą swojego konta. Teraz musimy go dopytywać o numer tego konta, bo strona z komentarzami nie zawiera już numeru w adresie.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, dopisuję ten komentarz do naszej sugestii.

**Comment by aktywnitu** [comment]
Mnie również potrzebne wyciągnięcie id po loginie. Użytkownicy nie znają swoich ID, jak również ID innych sprzedawców, a przecież API udostępnia kilka metod co zwraca dane publiczne od sprzedawców bez potrzeby autoryzacji.

**Comment by PrzemyslawLukanowski** [comment]
@aktywnitu Twój komentarz również dopisuję do sugestii.

**Comment by aktywnitu** [comment]
@PrzemyslawLukanowski, czy jest jakiś sposób tymczasowy. Nawet wspomniane wyżej pobieranie id ze strony użytkownika łapie się na limity i niestety powstaje problem.

**Comment by MaciejFrackowiak** [comment]
@aktywnitu Tak, obecnie nie ma alternatywy.

**Comment by tomasz-grzesik** [comment]
@MaciejFrackowiak, to na co czekacie?
Brakuje fundamentalnej funkcjonalności w API - pobrania id Użytkownika po loginie.

**Comment by MaciejFrackowiak** [comment]
@tomasz-grzesik Również Twoje zdanie dopisuję do sugestii, które zostały zebrane dla propozycji nowego zasobu. Jeżeli wdrożymy go, poinformujemy o tym w osobnym komunikacie i poście.

**Comment by tomasz-grzesik** [comment]
Świetnie. Czekam na taki komunikat.

**Comment by dzoudzou3** [comment]
Wszelkie nowe informacje o tym, jak uzyskać login od seller.id?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie. Jeżeli zdecydujemy się wprowadzić taki zasób, opublikujemy odpowiedni komunikat.

**Comment by GosiaJK** [comment]
Witam serdecznie,
Czy funkcjonalność wyszukiwania loginu po user id jest już dostępna w RestApi?
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nic się nie zmieniło - jeśli zdecydujemy się wprowadzić taki zasób, opublikujemy odpowiedni komunikat.

**Comment by rfk91** [comment]
Też potrzebowałem i ewentualnie można zrobić GET do `/uzytkownik/login/oceny`, 404 jeśli user nie istnieje lub 200 OK i wtedy można wydobyć sellerId z odpowiedzi

Pozdro 👍
