### ISSUE TITLE
Wyczyszczenie całej historii aukcji z konta allegro

### ISSUE THREAD

**Issue by rafalandryanczyk** [allegro/allegro-api#3174]
Dzień dobry, 

czy istnieje możliwość wyczyszczenia całkowicie historii aukcji allegro z danego konta, bez konieczności wyłączania każdej z osobna ? Nasz klient posiada ponad 200 tys aukcji, z błędnymi cenami, które same się teraz wznawiają, dodam, że na forum githuba, odesłał nas jego opiekun. Ewentualnie czy istnieje możliwość wyłączenia wznawiania dla tych wszystkich aukcji ?

Z góry dziękuje za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą zasobu [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) możesz zamknąć max 1000 ofert w jednym requescie. Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#5). 
Nie ma możliwości wyczyszczenia całej historii ofert. Zamknięte oferty dopiero po 60 dniach trafią do archiwum.
