### ISSUE TITLE
Pobranie danych odnośnie sprzedaży w allegro

### ISSUE THREAD

**Issue by PaVeN0** [allegro/allegro-api#3175]
Dzień dobry,
zajmuje się obecnie wdrożeniem funkcji która pozwoli na pobranie przez mojego klienta, który sprzedaje towary na allegro, listy zamówień które zostały sprzedane z ostatniego okresu. 
Z dokumentacji wiem że jest endpoint który pozwala na wyjęcie takich danych jednak mam zwrotkę 403 próbując pobrać te dane po autoryzacji jako Client_credentials. Czy jest możliwość wyjęcia zamówień z konta które jest autoryzowane w API? 

Dodatkowo próbowałem też opcji z Authorization Code tylko z tego co czytam musze najpierw przygotować przycisk w mojej aplikacji który wyśle informacje do Allegro po czym otrzymam "code" który użyje przy autoryzacji po której otrzymam token i ten token będę mógł użyć do wyjęcia danych o zamówieniach. Dobrze to rozumiem? 

Trochę dużo zamieszania z tym. Nie da się tego zrobić inaczej? 
Prosiłbym o przykład w kodzie na połączenie bo dokumentacje przejrzałem już kilka razy i nie za bardzo wiem jak pójść dalej...

**Comment by PrzemyslawLukanowski** [comment]
Tak, jest to możliwe. Sposób, który opisałeś jest prawidłowy i pozwoli na operacje tego typu. Ten typ autoryzacji opisaliśmy w [naszym poradniku](https://developer.allegro.pl/auth/#app). Wątek generowania tokena np. w PHP, przewinął się w poniższych wątkach:

#2306
#708
#226
#2046

Być może wśród nich znajdziesz wskazówki, które rozwieją Twoje wątpliwości.

**Comment by PaVeN0** [comment]
Z tego co przeglądam nie do końca znajduje rozwiązanie którego szukam. Może doprecyzuje: 
1. Czy opcja Client_credentials da mi możliwość wyjęcia zrealizowanych sprzedaży na koncie allegro?
2. Jeśli 1 nie to czy mogę poprzez Code Flow lub Device Flow połączyć się bez autoryzacji w formie klikania, logowania się przeglądarką itp

**Comment by PaVeN0** [comment]
Dokumentacja ma dużo wątków które są niejasne lub napisane aby były..
Marnujemy czas na zrozumienie jak działa połączenie w momencie gdy osoby odpowiedzialne za API wrzucają linki do dokumentacji. 
Jakoś ogarnąłem przekierowanie robie testowo po linku wpisując go w przeglądarkę.

**Comment by LesiuNOL** [comment]
Czemu podczas próby pobrania ofert "/sale/offers" wyrzuca mi błąd "AccessDenied"? Czymuszę podać dodatkowe parametry?

`array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(5) {
      ["code"]=>
      string(12) "AccessDenied"
      ["message"]=>
      string(16) "Access is denied"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(36) "No access to the specified resource."
    }
  }
}`

**Comment by PrzemyslawLukanowski** [comment]
@LesiuNOL  Upewnij się, że posiadasz token wygenerowany w ramach [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow i aplikacja posiada zakres `allegro:api:sale:offers:read`. Jeśli wszystko wykonałeś poprawnie, ale mimo to zwracamy nadal błąd, podaj proszę przykładowe trace-id.

**Comment by LesiuNOL** [comment]
Już jest wszystko OK. Faktycznie błąd był z autoryzacją "code". Dziękuję.

Pozdrawiam,
Bartłomiej Leśniewski


tel. 733-501-781
e-mail: ***@***.***


śr., 24 kwi 2024 o 12:44 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Znając ID oferty, musisz pobrać jej pełne dane za pomocą [GET /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation#operation/getProductOffer). Informację o parametrach zwracamy w sekcji `parameters`, a ID ISBN to 245669.

**Comment by LesiuNOL** [comment]
Dziękuję za odpowiedź, udało mi się wczoraj do tego dotrzeć. :) Jednak
zastanawia mnie kolejna rzecz. Token jest jednorazowy. Gdy wywołam endpoint
"/sale/offers", aby pobrać do tablicy ID ofert to token traci ważność,
jednak w tym samym skrypcie chciałbym pobrać informację o ISBN za pomocą
endpoint "/sale/product-offers/{offer_id}". Czy jest jakaś opcja, aby
uzyskać nowy token w locie, bądź przedłużyć ważność/odświeżyć obecny?

Pozdrawiam,
Bartłomiej Leśniewski


tel. 733-501-781
e-mail: ***@***.***


czw., 25 kwi 2024 o 07:24 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Access token jest ważny przez 12 godzin, w tym okresie możesz wykonywać za jego pomocą wiele operacji do naszych zasobów. Przed upływem tego czasu możesz za pomocą refresh tokena (który otrzymałeś wraz z access tokenem) wygenerować nową parę access token (który jest ważny kolejne 12 godzin) oraz refresh token (którego użyjesz, aby ponownie wygenerować nową parę). Więcej na ten temat przeczytasz [w tym punkcie](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena) naszego poradnika.

**Comment by LesiuNOL** [comment]
> Access token jest ważny przez 12 godzin, w tym okresie możesz wykonywać za jego pomocą wiele operacji do naszych zasobów. Przed upływem tego czasu możesz za pomocą refresh tokena (który otrzymałeś wraz z access tokenem) wygenerować nową parę access token (który jest ważny kolejne 12 godzin) oraz refresh token (którego użyjesz, aby ponownie wygenerować nową parę). Więcej na ten temat przeczytasz [w tym punkcie](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena) naszego poradnika.

Wszystko się zgadza. Token jest ważny 12 godzin, działa elegancko, pobiera mi w pętli dane, które potrzebowałem, jednak mam następny problem. Gdy zrobiłem skrypt "na sucho" w pliku .php to wszystko działa, jednak gdy przeniosłem to do wordpress'a (na tym samym serwerze, tej samej domenie) wyskakuje mi błąd

`Something went wrong: 400 {"error":"invalid_grant","error_description":"Invalid authorization code: IH1DMcQHdT7MfMv99UWrp36tKoN3rh2B"}`

Czy mogę w jakiś sposób szerzej sprawdzić co jest powodem? Wszystko jest przeniesione jeden do jednego.

**Comment by PrzemyslawLukanowski** [comment]
Kod, który przekazujesz w parametrze "code", jest ważny 10 sekund oraz jest jednorazowego użytku - wygląda na to, że ten czas minął lub kod został już wykorzystany wcześniej.

**Comment by LesiuNOL** [comment]
Co prawda usunąłem już to pytanie (nie widziałem odpowiedzi), bo sobie poradziłem. Dziwnym trafem przeniosłem funkcję do klasy PHP i po wywołaniu wszystko działa. Może dochodziły jakieś błędne parametry po stronie WordPress. Nie wiem. :)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za odpowiedź, cieszę się, że udało się rozwiązać problem :)
