### ISSUE TITLE
Zmiana ceny dla przedmiotu, który się sprzedał.

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#3176]
Mam pytanie. Czy jest możliwe, żeby przy pomocy /sale/offer-price-change-commands zmienić cenę pojedynczej oferty, która zdążyła się już sprzedać? Bo wygląda na to, że właśnie miałem taką sytuację (9200858745).

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz wykonywać operacje tego typu.
