### ISSUE TITLE
GET /order/events - wersja beta/public

### ISSUE THREAD

**Issue by piotrek1555** [allegro/allegro-api#3177]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

https://api.allegro.pl.allegrosandbox.pl/order/events
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/{id}

W dokumentacji metody są oznaczone jako public. Implementowaliśmy ją kiedy były jeszcze w wersji beta. W kwietniu działały jeszcze jako beta, teraz już nie działają, a w changelogu brak jakichś informacji o zmianach. Kiedy metody przestały być w wersji beta?

**Comment by PrzemyslawLukanowski** [comment]
Informacje na temat przejścia na wersję public znajdziesz w naszym [newsie](https://github.com/allegro/allegro-api/issues/2220). Przedłużyliśmy okres wsparcia dla wersji beta. W tej chwili na Sandboxie działa tylko wersja public, wkrótce podobnie będzie na produkcji.
