### ISSUE TITLE
Brak ofert

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#3178]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam.

Czy nie ma obecnie problemu z publikowaniem ofert? Klient zgłasza nam, że wystawiając aukcje przez REST API, od strony Allegro cały czas pokazuje się "Oferta nie istnieje". Zazwyczaj oferta pojawiała się po 2-3 minutach, od czasu wystawienia minęło ponad 30.
Również wchodząc do panelu nie jest ona widoczna w żadnym miejscu (szkice/oferty), natomiast odpytując API na końcówce /sale/offers/ zwracane są informacje, że oferta jest aktywna wraz ze wszystkimi danymi.
Przykładowy numer aukcji - 9241382469

**Comment by K4R0LW** [comment]
Również zgłaszam taki problem, po zapisaniu draft'a nie jest on widoczny w żadnym listingu w panelu i nie jest zwracany w /sale/offers, jednak po odpytaniu /sale/offers/{id_drafta} zwraca mi wszystkie informacje o ofercie a jej status jest "INACTIVE" czyli draft. Przykład 9241474342

**Comment by SebastianOzdoba** [comment]
Dołączam się do tematu, mamy to samo, generalnie wystawianie działa, ale oferta pojawia się z dużym opóźnieniem

**Comment by PrzemyslawLukanowski** [comment]
Wystawienie oferty w serwisie może zająć do godziny. Oferta 9241382469 jest już aktywna.

**Comment by bacok** [comment]
Ok, dziękuję za informację, zamykam.
