### ISSUE TITLE
metody GET i PUT /sale/offer-variants/{setId}

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3179]
Witam, 
Chciałbym wymienić poprzez REST API id oferty w wielowariantowości.

1. Pobieram dane z zasobu GET sale/offer-variants/{setId}
2. Podmieniam tylko jedno id oferty (ponieważ została wystawiona na nowo)
3. Przesyłam PUT sale/offer-variants/{setId} zmodyfikowany obiekt

GET:
`{"id":"38b9830d-d911-4520-8bba-a9d8a8c33a31","offers":[{"id":"8136365706","colorPattern":"6096908735"},{"id":"6096908735","colorPattern":"6096908735"},{"id":"9206814649","colorPattern":"8046108602"},{"id":"8136385179","colorPattern":"9207614741"},{"id":"9206833017","colorPattern":"6097005026"},{"id":"9206800596","colorPattern":"7422838463"},{"id":"8046108602","colorPattern":"8046108602"},{"id":"8136363414","colorPattern":"8136361566"},{"id":"8136370624","colorPattern":"7422838463"},{"id":"9206809666","colorPattern":"8046108602"},{"id":"8348558091","colorPattern":"8136361566"},{"id":"8136365033","colorPattern":"9207615986"},{"id":"8136361566","colorPattern":"8136361566"},{"id":"7422836348","colorPattern":"7422836348"},{"id":"9206797031","colorPattern":"7422838463"},{"id":"9167012028","colorPattern":"7422841344"},{"id":"9206835263","colorPattern":"6097005026"},{"id":"9207609051","colorPattern":"6096908735"},{"id":"8136390457","colorPattern":"8046108602"},{"id":"8136385778","colorPattern":"9207614741"},{"id":"9108635352","colorPattern":"6097005026"},{"id":"9206788877","colorPattern":"7422836348"},{"id":"9167014754","colorPattern":"8136361566"},{"id":"8136371233","colorPattern":"7422838463"},{"id":"9206811072","colorPattern":"8046108602"},{"id":"8136374569","colorPattern":"9207614741"},{"id":"8137011195","colorPattern":"9207615986"},{"id":"7422835185","colorPattern":"6096908735"},{"id":"8136391032","colorPattern":"8046108602"},{"id":"9206831065","colorPattern":"7422841344"},{"id":"8137010697","colorPattern":"7422836348"},{"id":"9206776266","colorPattern":"8136361566"},{"id":"8137010011","colorPattern":"8136361566"},{"id":"9117746521","colorPattern":"6097005026"},{"id":"9206831555","colorPattern":"7422841344"},{"id":"9206779192","colorPattern":"9207615986"},{"id":"9039713700","colorPattern":"7422841344"},{"id":"9206805877","colorPattern":"9207614741"},{"id":"8046107458","colorPattern":"7422838463"},{"id":"9206795889","colorPattern":"7422838463"},{"id":"9206833912","colorPattern":"6097005026"},{"id":"9206791686","colorPattern":"7422836348"},{"id":"8348559073","colorPattern":"8136361566"},{"id":"9203769369","colorPattern":"9207615986"},{"id":"9206794134","colorPattern":"7422836348"},{"id":"8136369946","colorPattern":"7422836348"},{"id":"9206804525","colorPattern":"9207614741"},{"id":"8762345902","colorPattern":"9207615986"},{"id":"7422841344","colorPattern":"7422841344"},{"id":"9108628238","colorPattern":"8046108602"},{"id":"9206813902","colorPattern":"8046108602"},{"id":"8136393557","colorPattern":"7422841344"},{"id":"9206802129","colorPattern":"9207614741"},{"id":"9206785160","colorPattern":"6096908735"},{"id":"9207614741","colorPattern":"9207614741"},{"id":"9117745707","colorPattern":"7422836348"},{"id":"8836339962","colorPattern":"6097005026"},{"id":"9206782106","colorPattern":"9207615986"},{"id":"7422834978","colorPattern":"6096908735"},{"id":"7422842465","colorPattern":"7422841344"},{"id":"9206826247","colorPattern":"7422841344"},{"id":"9206807070","colorPattern":"9207614741"},{"id":"9207615986","colorPattern":"9207615986"},{"id":"6097005026","colorPattern":"6097005026"},{"id":"9108627951","colorPattern":"6096908735"},{"id":"9206838160","colorPattern":"6097005026"},{"id":"7422838463","colorPattern":"7422838463"},{"id":"8136372690","colorPattern":"7422838463"},{"id":"9206772650","colorPattern":"8136361566"},{"id":"9206783592","colorPattern":"6096908735"},{"id":"8136368822","colorPattern":"7422836348"},{"id":"9108626896","colorPattern":"9207615986"}],"name":"askr16","parameters":[{"id":"54"},{"id":"color/pattern"}]}`

Przepinam id:
`{"id":"7422838463","colorPattern":"7422838463"}`
na
`{"id":"9237989394","colorPattern":"7422838463"}`

PUT:
`{"id":"38b9830d-d911-4520-8bba-a9d8a8c33a31","offers":[{"id":"8136365706","colorPattern":"6096908735"},{"id":"6096908735","colorPattern":"6096908735"},{"id":"9206814649","colorPattern":"8046108602"},{"id":"8136385179","colorPattern":"9207614741"},{"id":"9206833017","colorPattern":"6097005026"},{"id":"9206800596","colorPattern":"7422838463"},{"id":"8046108602","colorPattern":"8046108602"},{"id":"8136363414","colorPattern":"8136361566"},{"id":"8136370624","colorPattern":"7422838463"},{"id":"9206809666","colorPattern":"8046108602"},{"id":"8348558091","colorPattern":"8136361566"},{"id":"8136365033","colorPattern":"9207615986"},{"id":"8136361566","colorPattern":"8136361566"},{"id":"7422836348","colorPattern":"7422836348"},{"id":"9206797031","colorPattern":"7422838463"},{"id":"9167012028","colorPattern":"7422841344"},{"id":"9206835263","colorPattern":"6097005026"},{"id":"9207609051","colorPattern":"6096908735"},{"id":"8136390457","colorPattern":"8046108602"},{"id":"8136385778","colorPattern":"9207614741"},{"id":"9108635352","colorPattern":"6097005026"},{"id":"9206788877","colorPattern":"7422836348"},{"id":"9167014754","colorPattern":"8136361566"},{"id":"8136371233","colorPattern":"7422838463"},{"id":"9206811072","colorPattern":"8046108602"},{"id":"8136374569","colorPattern":"9207614741"},{"id":"8137011195","colorPattern":"9207615986"},{"id":"7422835185","colorPattern":"6096908735"},{"id":"8136391032","colorPattern":"8046108602"},{"id":"9206831065","colorPattern":"7422841344"},{"id":"8137010697","colorPattern":"7422836348"},{"id":"9206776266","colorPattern":"8136361566"},{"id":"8137010011","colorPattern":"8136361566"},{"id":"9117746521","colorPattern":"6097005026"},{"id":"9206831555","colorPattern":"7422841344"},{"id":"9206779192","colorPattern":"9207615986"},{"id":"9039713700","colorPattern":"7422841344"},{"id":"9206805877","colorPattern":"9207614741"},{"id":"8046107458","colorPattern":"7422838463"},{"id":"9206795889","colorPattern":"7422838463"},{"id":"9206833912","colorPattern":"6097005026"},{"id":"9206791686","colorPattern":"7422836348"},{"id":"8348559073","colorPattern":"8136361566"},{"id":"9203769369","colorPattern":"9207615986"},{"id":"9206794134","colorPattern":"7422836348"},{"id":"8136369946","colorPattern":"7422836348"},{"id":"9206804525","colorPattern":"9207614741"},{"id":"8762345902","colorPattern":"9207615986"},{"id":"7422841344","colorPattern":"7422841344"},{"id":"9108628238","colorPattern":"8046108602"},{"id":"9206813902","colorPattern":"8046108602"},{"id":"8136393557","colorPattern":"7422841344"},{"id":"9206802129","colorPattern":"9207614741"},{"id":"9206785160","colorPattern":"6096908735"},{"id":"9207614741","colorPattern":"9207614741"},{"id":"9117745707","colorPattern":"7422836348"},{"id":"8836339962","colorPattern":"6097005026"},{"id":"9206782106","colorPattern":"9207615986"},{"id":"7422834978","colorPattern":"6096908735"},{"id":"7422842465","colorPattern":"7422841344"},{"id":"9206826247","colorPattern":"7422841344"},{"id":"9206807070","colorPattern":"9207614741"},{"id":"9207615986","colorPattern":"9207615986"},{"id":"6097005026","colorPattern":"6097005026"},{"id":"9108627951","colorPattern":"6096908735"},{"id":"9206838160","colorPattern":"6097005026"},{"id":"9237989394","colorPattern":"7422838463"},{"id":"8136372690","colorPattern":"7422838463"},{"id":"9206772650","colorPattern":"8136361566"},{"id":"9206783592","colorPattern":"6096908735"},{"id":"8136368822","colorPattern":"7422836348"},{"id":"9108626896","colorPattern":"9207615986"}],"name":"askr16","parameters":[{"id":"54"},{"id":"color\/pattern"}]}`

i w odpowiedzi dostaje:
`{"errors":[{"code":"VALIDATION_ERROR","message":"Given color pattern does not match existing offers: 6096908735, 6097005026, 7422834978, 7422835185, 7422836348, 7422841344, 7422842465, 8046107458, 8046108602, 8136361566, 8136363414, 8136365033, 8136365706, 8136368822, 8136369946, 8136370624, 8136371233, 8136372690, 8136374569, 8136385179, 8136385778, 8136390457, 8136391032, 8136393557, 8137010011, 8137010697, 8137011195, 8348558091, 8348559073, 8762345902, 8836339962, 9039713700, 9108626896, 9108627951, 9108628238, 9108635352, 9117745707, 9117746521, 9167012028, 9167014754, 9203769369, 9206772650, 9206776266, 9206779192, 9206782106, 9206783592, 9206785160, 9206788877, 9206791686, 9206794134, 9206795889, 9206797031, 9206800596, 9206802129, 9206804525, 9206805877, 9206807070, 9206809666, 9206811072, 9206813902, 9206814649, 9206826247, 9206831065, 9206831555, 9206833017, 9206833912, 9206835263, 9206838160, 9207609051, 9207614741, 9207615986, 9237989394.","details":null,"path":null,"userMessage":"Given color pattern does not match existing offers: 6096908735, 6097005026, 7422834978, 7422835185, 7422836348, 7422841344, 7422842465, 8046107458, 8046108602, 8136361566, 8136363414, 8136365033, 8136365706, 8136368822, 8136369946, 8136370624, 8136371233, 8136372690, 8136374569, 8136385179, 8136385778, 8136390457, 8136391032, 8136393557, 8137010011, 8137010697, 8137011195, 8348558091, 8348559073, 8762345902, 8836339962, 9039713700, 9108626896, 9108627951, 9108628238, 9108635352, 9117745707, 9117746521, 9167012028, 9167014754, 9203769369, 9206772650, 9206776266, 9206779192, 9206782106, 9206783592, 9206785160, 9206788877, 9206791686, 9206794134, 9206795889, 9206797031, 9206800596, 9206802129, 9206804525, 9206805877, 9206807070, 9206809666, 9206811072, 9206813902, 9206814649, 9206826247, 9206831065, 9206831555, 9206833017, 9206833912, 9206835263, 9206838160, 9207609051, 9207614741, 9207615986, 9237989394."}]}`

Z góry dziękuję za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Analizuję jeszcze Twój przykład, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Problem generuje to, że oferty z identycznymi kolorami (a różnymi rozmiarami) posiadają różne zdjęcia (mimo że wyglądają identycznie). Rozwiązaniem będzie ustawienie takich samych zdjęć dla tych ofert.  Bez tego nie uda się ich poprawnie połączyć przez REST API.
