### ISSUE TITLE
doChangeItemFields i ERR_INVALID_DURATION_TIME

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#318]
Wygląda na to że doChangeItemFields nie przyjmuje więcej fid 4. Oczywiście informacji wcześniejszej brak.

**Comment by zulus** [comment]
Albo nie, jest jeszcze śmieszniej. Ja tego pola nawet nie wysyłam, mimo to i tak mam błąd na aukcji która była wystawiana z fid 4 = 99.

**Comment by zulus** [comment]
Przykładowy numer aukcji: 7413376485

**Comment by PawelTaberski** [comment]
Sprawdziłem i podana przez Ciebie oferta jest wystawiona na 10 dni. Podeślij swój request co dokładnie próbujesz zmienić, sprawdzimy w czym jest problem.

**Comment by zulus** [comment]
niemożliwe, coś jest nie tak z waszej strony. Zawsze wystawiamy aukcję z fID4 = 99. Niema możliwości żebyśmy wystawili terminową aukcję, nic w kodzie w tej materii się nie zmieniło od początku integracji (99 jest ustawione na twardo). W panelu allegro gdy wchodzę w edycję aukcji mam zaznaczone "do wyczerpania zapasów". Skąd w takim razie 10dni?

**Comment by PawelTaberski** [comment]
Przepraszam mój błąd błędnie przekleiłem numer oferty ma Pan rację. Jak Pan [podeśle](https://allegro.pl/pomoc/kontakt#subjectId=1436f902-6fd9-420f-9e19-321b684cc8df) request i response sprawdzimy czemu przy zmianie pojawia się taki błąd. Proszę tutaj wlepić numer ticketa.

**Comment by zulus** [comment]
Form kontaktowy nie wyświetlił mi żadnego numeru ticketa. Także nie mam co przeklejać. W razie w pastebin:

Request: https://klienci.output42.com.pl/elitpolska/allegro_318_request.txt (za duży na pastebin)
Response: https://pastebin.com/E8QBGLbB (zwykły soap exception)

**Comment by PawelTaberski** [comment]
Problem jest z fidem 29 przesyłasz 1, a nie ma już ofert sklepowych wszystkie są ofertami zwykłymi.
Informowaliśmy o zmianie tutaj #299
Niemniej jest jakiś błąd bo z automatu powinno Tobie zmienić na 0 a tak się nie dzieje, sprawę zgłosiłem do odpowiedniego zespołu.
Chwilowo przesyłaj w fidzie 29 wartość 0 wtedy request przejdzie poprawnie.

**Comment by zulus** [comment]
Przeszło, ale błąd jest delikatnie mówiąc dziwny.

**Comment by zulus** [comment]
Po zmianie wartości na aukcji której mam sprzedaż leci "ERR_CANT_CHANGE_ITEM_TYPE_FOR_SHOP_ITEM". Na razie po prostu usunąłem to wysyłanie tego pola.

**Comment by PawelTaberski** [comment]
Rozumiem, sprawę przekazałem do odpowiedniego zespołu, proszę o cierpliwość.
