### ISSUE TITLE
Oferta w więcej niż 1 kategorii

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3180]
Rozumiem, że na chwilę obecną nie można przypisać oferty do więcej niż 1 kategorii ?
Jeśli tak czy w niedalekiej przyszłości będzie możliwe przypisanie do wielu kategorii 1 oferty ?
Rozumiem, że na chwilę obecną można wystawiać ten sam produkt kilka razy w wielu ofertach w różnych kategoriach ? Nie jest to w jakiś tam sposób banowane ? Czy jeśli utworzę kilka takich samych ofert w ramach różnych kategorii Allegro i połączę je w warianty to Wasz system nie będzie krzyczał, że już jest podobna oferta z wariantami itp. ?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie możesz przypisać jednej oferty (o tym samym id) do różnych kategorii. Jeżeli coś zmieni się w tej kwesti, opublikujemy odpowiedni komunikat na stronie dla sprzedających. Możesz za to wystawić ten sam przedmiot w różnych kategoriach. W przypadku ofert wielowariantowych powinieneś unikać duplikatów - może to generować błędy.

**Comment by pietrach** [comment]
> W przypadku ofert wielowariantowych powinieneś unikać duplikatów - może to generować błędy.

W jakim sensie unikać duplikatów ? Mam taki przykład.
Mam oferty A, B, C, D w kategorii Allegro X, one są połączone ze sobą jako warianty
Mam oferty E, F, G, H w kategorii Allegro Y, one są połączone ze sobą w wawianty. Są to z punktu widzenia naszego systemu te same produkty czyli A = E, B = F, C =G, D = H tylko, że wystawione w innej kategorii Allegro. Czy jeśli tak je połączę ze sobą w warianty to będzie to stanowiło problem jakiś ?

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuję - jeżeli oferty będą w innych kategoriach, nie powinno to generować błędów. Duplikatem będzie oferta w tej samej kategorii, w Twoim przypadku rzeczywiście nie powinno być problemów.
