### ISSUE TITLE
Obserwowane wyszukiwania dostępne z poziomu API

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#3181]
:bulb: **Sugestia**

Witam,
Czy jest szansa, że wystawicie do pobrania przez API obserwowane wyszukiwania?

**Comment by rafalkrupinski** [comment]
Nie jestem z zespołu Allegro, ale zdaje się, że API jest kierowane raczej do sprzedawców.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak jak wspomniał @rafalkrupinski - w REST API skupiamy się na funkcjonalnościach dla sprzedawców. Czy możesz wskazać potrzebę posiadania takiego zasobu? Przekażę to jako sugestię do odpowiedniego zespołu.

**Comment by dol1234** [comment]
Są też narzędzia dla kupujących. Nie jestem zadowolony z powiadomień, które otrzymuje tylko raz dziennie (w godzinach 7-10). Jeżeli wystawicie informację, będzie można odpytywać o wyszukiwania częściej.

**Comment by kfijalko** [comment]
@dol1234  czym się różni oczekiwane przez ciebie "obserwowane wyszukiwanie" od takiego, które sam możesz zdefiniować odpytując publiczny listing ?

**Comment by kfijalko** [comment]
mam na myśli:
https://developer.allegro.pl/documentation/#operation/getListing

**Comment by dol1234** [comment]
Żeby odpytać muszę wiedzieć o co. Chciałby pobrać przez API zawartość strony https://allegro.pl/moje-allegro/zakupy/obserwowane/wyszukiwania

**Comment by kfijalko** [comment]
Jeżeli to są Twoje wyszukiwania to bez problemu zdefiniujesz je za pomocą powyższej metody i możesz je wywoływać kiedy chcesz. Możesz w wyszukiwaniu określić kategorię, sprzedawcę, szukaną frazę, parametry .... chyba że czegoś nie rozumiem. Może chciałbyś taką usługę uruchomić dla innych kupujących?

**Comment by dol1234** [comment]
No tak, mogę też trzymać te dane w pliku, bazie lub zapamiętać i powtarzać przed snem:) Nie ma znaczenia jak miałbym je przetwarzać - są już zdefiniowane więc chciałbym uniknąć powielania bytów.

**Comment by rafalkrupinski** [comment]
getListing nie obsługuje zapisanych wyszukiwań.

**Comment by dol1234** [comment]
@PrzemyslawLukanowski : tak czy inaczej prosiłbym o wrzucenie tego na listę życzeń, może się kiedyś spełni;)

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście, zapisałem na to liście sugestii dot. rozwoju API.

**Comment by bartosz-lanik** [comment]
Witam. Czy jest szansa na dodanie takiej funkcjonalności?

**Comment by PrzemyslawLukanowski** [comment]
@bartosz-lanik Na tę chwili nie mamy tego w planach. Zachęcam Cię jednak do przekazania sugestii w dziale [Discussions](https://github.com/allegro/allegro-api/discussions?page=1), dzięki czemu również inni użytkownicy będą mogli zagłosować za tą funkcjonalnością.
