### ISSUE TITLE
API "gubi" zmienną wysłaną z formularza

### ISSUE THREAD

**Issue by mario033c** [allegro/allegro-api#3182]
Witam, problem jak w temacie, wysyłam do skryptu ID konta allegro za pomocą formularza metodą POST, jednak skrypt gubi zmienną po wykonaniu poniższego kodu:

$api = new Api($clientId, $clientSecret, $apiKey, $redirectUri, null, null);
$code = $_GET['code'];
if(strlen($code)<3)
{
  $authUri=$api->getAuthorizationUri();

	header("Location: $authUri");
  exit;
}
$response = $api->getNewAccessToken($code);

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Problem autoryzacji w PHP pojawił się jednak w wątkach:

#2306
#708
#226
#2046

Być może wśród nich znajdziesz wskazówki dotyczące Twojego problemu. Możesz także skorzystać z dostępnych wyszukiwarek. Jeżeli przekażesz w niej część swojego kodu, to wśród dostępnych wyników możesz znaleźć strony z przykładowym kodem.
