### ISSUE TITLE
Pobieranie: numery przesyłek dodane do zamówienia

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#3183]
Dzień dobry,
pobieram zdarzenia, ze statusem READY_FOR_PROCESSING a następnie checkoutForm.
Czy w tym momencie w zasobie /order/checkout-forms/{checkoutForm.id}/shipments będzie zawsze podany waybill dla Allegro Paczkomaty 24/7 InPost czy może sie zdarzyć, że nie będzie podany?
Kiedy waybill jest uzupełniany?

**Comment by PrzemyslawLukanowski** [comment]
Waybill dla tego zasobu podamy zawsze, jeżeli numer przesyłki zostany dodany do zamówienia - czy to przez narzędzie nadawcze przewoźnika, czy przez API. Oczywiście mogą zdarzyć się sytuacje, że pobierzesz zamówienia w statusie RFP i nie będzie w nich żadnego numeru przesyłki. 

Jeżeli chcesz dodatkowo filtrować zamówienia po tym, czy zostały do nich przypisane przesyłki, skorzystaj z filtru fulfillment.shipmentSummary.lineItemsSent, np.

`GET /order/checkout-forms?status=READY_FOR_PROCESSING&fulfillment.shipmentSummary.lineItemsSent=ALL`

Zwróci opłacone zamówienia, gdzie do wszystkich przedmiotów został przypisany numer przesyłki.
Więcej informacji na temat tego pola znajdziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/2813).

**Comment by BartekWroclaw** [comment]
A czy możliwe jest, że dla Allegro Paczkomaty 24/7 InPost zasób  /order/checkout-forms/{checkoutForm.id}/shipments zwróci więcej niż 1 element?

**Comment by PrzemyslawLukanowski** [comment]
Tak, jeżeli sprzedawca do zamówienia dodał parę numerów.
