### ISSUE TITLE
sale/offer-quantity-change-commands - 504

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3184]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś obserwujemy zwiększoną ilość błędów 504 dla podanej metody
Przykładowy request

REQUEST 2020-05-07 07:22:09.8441579 
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/7e816ae8-029c-4787-940a-630d6b685c56' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"modification":{"changeType":"FIXED","value":174},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"7283681184"}]}]}' \

RESPONSE 2020-05-07 07:22:12.8605598 Duration: 3016,4019ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
   },
  "TraceId": "59f79857d3db08eb",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem zgłoszenie do odpowiedniego zespołu, który przeanalizuje tę sytuację.
