### ISSUE TITLE
Prosba o dodanie obslugi opcji do API "Przy wystawianiu oferty stwórz jednocześnie produkt"

### ISSUE THREAD

**Issue by Dawidek990** [allegro/allegro-api#3185]
Witam, w czesci kategorii(nie w kazdej) jest taka opcja "Przy wystawianiu oferty stwórz jednocześnie produkt", to jest opcja wystawiania. Wszystkie moje aukcje to maja i potrzebuje to odznaczyc.

https://zapodaj.net/images/4c36967845243.png

Mozecie dodac to do restapi?

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad zasobem, który pozwoli wystawić ofertę i jednocześnie stworzyć nowy produkt. Wkrótce opublikujemy więcej szczegółów.
