### ISSUE TITLE
/order/checkout-forms/{checkouformId} FILLED_IN delivery cost null

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3186]
Występuje problem: 
 - [X] ze środowiskiem produkcyjnym
 - [X] z zasobem REST API
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry, dlaczego dla transakcji 56f4efe5-8ee1-11ea-b111-3f7b90f155e2 FILLED_IN delivery cost jest null?

trace-id 22bbb50305682c34
date Thu, 07 May 2020 11:05:34 GMT

```
"delivery": {
        "address": null,
        "method": {
            "id": "059c0d58-6cdb-4955-ab79-9031518f80f3",
            "name": "Kurier GLS"
        },
        "pickupPoint": null,
        "cost": null,
        "smart": false,
        "time": {
            "guaranteed": null
        },
        "calculatedNumberOfPackages": null
    },
```

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to i potwierdzam problem dla tego zamówienia. Przekazałem informację do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Problem został rozwiązany. Zamówienie powinno zwracać już prawidłowe wartości.
