### ISSUE TITLE
/sale/offer-variants/ An error has occurred

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#3188]
Wszystko działało. Nagle przestało... połowicznie. 
Jeśli wysyłam PUT dla wielowariantowości, która juz istnieje, jak tu:
```
{
  "offers": [{
      "id": "9186012681",
      "colorPattern": "60536"
    },{
      "id": "9201248085",
      "colorPattern": "60535"
    },{
      "id": "9201260970",
      "colorPattern": "60923"
    },{
      "id": "9201275509",
      "colorPattern": "60924"
    },{
      "id": "9201281671",
      "colorPattern": "60925"
    }
  ],
  "name": "balon gwiazda fx 9 cali",
  "parameters": [
    {
        "id": "color/pattern"
    }
  ]
}
```
dostaję zwrotnie OK, czyli [id] => 905897a4-c31e-e801-9f6f-5b7b5ad3a8c9

Jak zaś wysyłam poprawne oferty, ale ma się utworzyć nowa wielowariantowość:
```
	{
  "offers": [{
      "id": "9241265845",
      "colorPattern": "61223"
    },{
      "id": "9241282273",
      "colorPattern": "61224"
    },{
      "id": "9241292784",
      "colorPattern": "61225"
    },{
      "id": "9241323236",
      "colorPattern": "59717"
    },{
      "id": "9241600820",
      "colorPattern": "59714"
    },{
      "id": "9241608348",
      "colorPattern": "59716"
    }
  ],
  "name": "balony_test",
  "parameters": [
    {
        "id": "color/pattern"
    }
  ]
}
```
To w odpowiedzi dostajemy:
```
Array
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => 
                )

        )

)
```

Jeśli spieprzymy cokolwiek innego, np. podały zły numer oferty, zły parametr, nie podamy czegoś itd zgłasza się normalna obsługa błędów i komunikat co jest źle. A nagle od kilku dni za każdą próbą dodania nowej wielowariantowości jest taki babol... Czy może się okazać, ze osiągnęliśmy jakiś niewidoczny limit na ilość wielowariantowości ? Mamy ich ponad 1600... czy to może już kres możliwości API ?

**Comment by PrzemyslawLukanowski** [comment]
Czy nowy wariant dodajecie za pomocą POST? Nie widzę w naszych logach danych dla tej metody. O zmianach informowaliśmy w naszych newsach: #2976, #3082. Jeżeli mimo wszystko oferty wielowariantowe tworzone są za pomocą metody POST, to poproszę o przykładowe trace-id.

**Comment by partyumarty** [comment]
Fakt, przeoczyłem newsa, dziękuję za pomoc, wszystko śmiga.
