### ISSUE TITLE
Pobieranie informacji na temat produktów w środowisku testowym

### ISSUE THREAD

**Issue by rafalandryanczyk** [allegro/allegro-api#3189]
Dzień dobry,

w celach demonstracyjnych / testowych, chciałbym z API pobrać informacje na temat produktów (endpoint /sale/products/?ean=), niestety EANy, które w produkcyjnym środowisku zwracają dane produktów, nie działają na sandboxie, czy mogę prosić o jakąś pulę eanów, które zadziałają w wersji sanboxowej ? 

Z góry dziękuje  za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Informacyjnie dla pozostałych użytkowników - lista produktów dostępnych w środowisku testowym znajduje się [tutaj](https://developer.allegro.pl/productization/#sandbox).
