### ISSUE TITLE
Błąd podczas edycji opcji promowań.

### ISSUE THREAD

**Issue by bherczyk** [allegro/allegro-api#3190]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę zmienić opcji promowania w ofertach na środowisku testowym.
Opcja pakiet jest wyszarzona, a podczas próby zmiany innych opcji pojawia się błąd: "Podczas modyfikowania oferty wystąpiły błędy. Podany adres obrazka jest nieprawidłowy"
id przykładowej oferty: 6207126657

Podczas próby zmiany opcji promowań za pomocą metody PUT offer-modification-commands występuję ten sam bład. 
Kilka dni temu wszystko działało prawidłowo, nic w ofertach nie było zmieniane.

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj usunąć zdjęcie i dodać nowe. Obrazki na sandboxie usuwamy po 7 dniach (na samym końcu [poradnika](https://developer.allegro.pl/about/#Sandbox) znajdziesz taką informację). Problem z pozostającym starym obrazkiem w ofercie przekazałem do analizy do odpowiedniego zespołu.

**Comment by aktywnitu** [comment]
@PrzemyslawLukanowski, a czy może wystąpić taki problem na produkcji po dłuższym czasie?
Inaczej pytając, czy adres url obrazka może się zmienić bez ingerencji Użytkownika Allegro i API?

**Comment by PrzemyslawLukanowski** [comment]
Adres URL nie powinien się zmienić bez ingerencji Użytkownika Allegro i API.

Obrazki dostępne są minimum 60 dni - w zależności od tego, czy jeden obrazek podpięty jest do wielu ofert.
