### ISSUE TITLE
Unikalność checkoutForm.id

### ISSUE THREAD

**Issue by pawel1151** [allegro/allegro-api#3191]
Czy checkoutForm.id z zasobu https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET będzie zawsze unikalne i nigdy się nie powtórzy w 2 zamówieniach?

Taka sugestia apropos Waszego swaggera, fajnie by było dać w opisach informacje o polach, które zawsze będą unikalne- Czy może mogę założyć, że wszystkie pola posiadające nazwę id będą zawsze unikalne ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, każdy numer zamówienia to indywidualny numer UUID, który się nie powtórzy. Co do Twojego drugiego pytania - każda zwrócona wartość w formacie UUID zawsze będzie unikalna, np. checkoutForm.id, payment.id, claim.id, etc. W przypadku zamówień unikatowe zawsze będą:
- checkoutForm.id,
- payment.id,
- id eventu - chociaż mogą wystąpić dwa takie same zdarzenia, ale z innym id. Duplikaty można rozpoznać po typie zdarzenia i wartości w polu occuredAt,
- shipments.id

> Taka sugestia apropo...

Dziękuję za Twoją sugestię, przekażę ją do odpowiedniego zespołu.
