### ISSUE TITLE
Problem z wysyłaniem obrazków

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3193]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas wysyłania obrazka na sandbox dostaje odpowiedź Not Found ( kod błędu 404 ).
Adres jaki mam https://upload.allegro.pl.allegrosandbox.pl/sale/images. 
Trace-Id niestety nie jestem w stanie podać. Problem ten występuje na 2 niezależnych aplikacjach i od czasu do czasu uda się wystawić, zaktualizować aukcje.

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się powtórzyć ten problem, również otrzymuję w odpowiedzi 404. Przekazałem to do odpowiedniego zespołu.
