### ISSUE TITLE
Problem z wystawianiem ofert

### ISSUE THREAD

**Issue by pstryczke** [allegro/allegro-api#3194]
Stworzyłem aplikację do wystawiania ofert, która informację pobiera z pliku csv. Chciałem go przetestować, więc wrzuciłem plik z 112 rekordami, a następnie uruchomiłem program. Wszystkie rekordy zostały poprawnie dodane (na początku utworzenie draftu requestem POST /sale/offers, następnie uzupełnienie informacji requestem PUT/sale/offers/{offerId} wraz z dodaniem zdjęć i po poprawnym uzupełnieniu, wpisywanie ID draftu do listy). Po dodaniu wszystkich rekordów, publikuję je przy pomocy requesta PUT /sale/offer-publication-commands/{commandId}, co również zwraca mi poprawny response. Jednak na maila, przychodzą mi jedynie 74 wiadomości z potwierdzeniem utworzenia oferty, a po 12 godzinach od dodania, na sandboxie, widzę jedynie 50 ofert. Chciałbym się dowiedzieć czym to jest spowodowane, ta różnica w liczbach. Czy sandbox ma jakieś ograniczenia wobec wystawiania dużej ilości ofert jednocześnie? (czas tworzenia i uzupełniania pojedynczego draftu trwał średnio 4 sekundy)

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) możesz sprawdzić szczegółowy raport wykonania zadania. Możesz także przesłać nam numer commandId. Zweryfikujemy, co się wydarzyło i skąd pochodzi ta rozbieżność.

**Comment by pstryczke** [comment]
Czy można uzyskać listę użytych commandId? W dokumentacji nie znalazłem
żadnej informacji, a obecnie generuję UUID przy wystawianiu ofert, lecz
nigdzie go potem nie zapisuję.

pt., 8 maj 2020 o 13:07 PrzemyslawLukanowski <notifications@github.com>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiego zasobu. Możesz podać swój ID z sandboxa i orientacyjny timestamp dla tego commandID? Spróbuję odnaleźć tę komendę w naszych logach.

**Comment by pstryczke** [comment]
ClientID: dc19dd5636d447ecbe280f2358bdadb7,
Oferty zostały wystawione dokładnie o 12 w nocy dzisiaj, więc commandID zostało stworzone w tym przedziale

**Comment by PrzemyslawLukanowski** [comment]
Analizuję ten problem, wrócę z odpowiedzią. Informacja dla Ciebie - commandId dla tego żądania to f7d668b7-c040-4494-a5f4-289567f96309
