### ISSUE TITLE
"Kod producenta" jako pole w pozycjach zamówienia

### ISSUE THREAD

**Issue by Anidatte** [allegro/allegro-api#3195]
:bulb: **Sugestia**

Mam propozycję z którą wychodzą klienci, dla których integrujemy przesyłanie zamówień z Allegro: wielu z nich chciałoby przypisanie produktów do zewnętrznych systemów realizować po kodzie producenta który teraz jest już chyba wymagany na aukcjach.

Problem w tym, że tego kodu nie ma w API przy samych pozycjach w szczegółach zamówienia, czyli w zasobie:
/order/checkout-forms/{id}

I stąd sugestia, aby dodać to pole np. w tym samym miejscu, gdzie znajduje się sygnatura aukcji. Ułatwiłoby to łączenie produktów i nie wymagało dodatkowego odpytywania API o szczegóły aukcji.

**Comment by PrzemyslawLukanowski** [comment]
Dziekuję za sugestię. Przekazałem ją do zespołu odpowiedzialnego za rozwój API.

**Comment by asoio** [comment]
Dopisuję się do tej sugestii. Może udałoby się to zrobić przy okazji zapowiadanego udostępnienia parametru GTIN?

**Comment by PrzemyslawLukanowski** [comment]
@asoio Dopisuję Twoje zgłoszenie do naszej sugestii. Jeżeli zdecydujemy się wprowadzić takie rozwiążanie, poinformujemy o tym w odpowiednim komunikacie.
