### ISSUE TITLE
/offers/listing - skąd wziąć wartość seller.id?

### ISSUE THREAD

**Issue by kamilslaw** [allegro/allegro-api#3196]
Dawniej identyfikator użytkownika można było znaleźć na stronie _OCENY I KOMENTARZE_, ale teraz znajduje się tam jedynie jego nazwa. Czy mogę znaleźć tą informację w jakimś innym miejscu?

**Comment by DINK74** [comment]
https://allegro.pl/uzytkownik/<nazwa użytkownika>

zescrapuj tę stronę to znajdziesz parę wystąpień id, np.
<link rel="alternate" href="android-app://pl.allegro/http/allegro.pl/listing/user/listing.php?us_id=XXXXXXXX">

nawet jak user nic nie wystawia

**Comment by mario033c** [comment]
@kamilslaw niestety póki co nie ma możliwości pobrania ID użytkownika poprzez API.
Też miałem ten problem więc ułatwiłem sobie to tak: 

```
<?php

function searchID($login) {
preg_match("/us_id=[0-9]{1,10}/", file_get_contents("https://allegro.pl/uzytkownik/".$login), $results);
print_r(str_replace("us_id=" , "" , $results[0]));
}

searchID("login");

?>
```

**Comment by ziemekpr0** [comment]
@PawelTaberski , @PrzemyslawLukanowski idealne potwierdzenie teorii, że jeżeli czegoś nie ma w API to będzie scrapowane z WWW.  Zamiast zrobić normalny dostęp przez API i wykonywać jeden request, jest ich, no właśnie - ile trzeba zrobić requestów na froncie, żeby stronę wygenerować? Tak nie oszczędzicie zasobów.
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
@ziemekpr0 Dziękuję, przekażę informację do działu odpowiedzialnego za rozwoj API.
