### ISSUE TITLE
[Stany magazynowe] Podana wartość nie jest liczbą

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3198]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o weryfikację skąd taki komunikat, wydaje mi się że dotyczy to atrybutów a nie ilości sztuk

{"Zlecenie":{"Nr":"d29d78dc-7196-4ec4-b670-956eb42f4bc2","Operacja":{"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"9248236282"}]}],"Publication":{"Action":"ACTIVATE","ScheduledFor":null}},"Response":{"Data":{"Id":"d29d78dc-7196-4ec4-b670-956eb42f4bc2","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"931cea132ba76e10","Error":false,"StatusCode":201,"Message":null}}}

{"RaportZlecenia":{"Nr":"d29d78dc-7196-4ec4-b670-956eb42f4bc2","Response":{"Data":{"Tasks":[{"Field":"publication","FinishedAt":"2020-05-07T19:50:57.512Z","Message":"Could not change offer publication status. Podana wartość nie jest liczbą: Liczba sztuk w zestawie(130389).","Offer":{"Id":"9248236282"},"ScheduledAt":"2020-05-07T19:50:57.211Z","Status":"FAIL","Errors":[{"Code":"ConstraintViolationException.ValidAttributes","Details":null,"Message":"Podana wartość nie jest liczbą: Liczba sztuk w zestawie(130389).","Path":"attributes","UserMessage":"Podana wartość nie jest liczbą: Liczba sztuk w zestawie(130389)."}]}]},"Validation":null,"Exception":null,"TraceId":"17aec010dd5d498e","Error":false,"StatusCode":200,"Message":null}}}
(Błędy)

**Comment by MaciejFrackowiak** [comment]
Spojrzałem w nasze logi - w payloadzie oferty na moment jej aktywacji znajdował się nieobowiązkowy parametr 130389 bez podanej wartości - stąd komunikat "Podana wartość nie jest liczbą". Jak widzę obecnie oferta jest już aktywna i w swojej strukturze nie ma już parametru 130389.
