### ISSUE TITLE
POST sale/offers - dziwny identyfikator

### ISSUE THREAD

**Issue by mjag8** [allegro/allegro-api#3199]
Zwracam się z pytaniem dotyczącym wystawiania ofert. Używam zasobu **POST sale/offers**, w odpowiedzi serwer zwrócił mi strukturę z ustawioną nazwą, kategorią i poniższym identyfikatorem oferty: **5eb526bc7bdabe78b4ffd61c**, który powinien mieć raczej formę liczby całkowitej (np. 9253712177)
Czy jest to jakiś jednorazowy błąd serwera, czy coś innego poszło nie tak? 
Będę wdzięczny za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Tak, to był nasz błąd, którego efektem był niecodzienny identyfikator oferty. Obecnie już zwracamy "standardowe" numery ofert. Przepraszam za zamieszanie.
