### ISSUE TITLE
DoGetMySoldItems

### ISSUE THREAD

**Issue by blochos** [allegro/allegro-api#32]
chciałbym pobrać wszystkie aukcje z zakładki SPRZEDAZ.
Pobierać moge maks 1000 rekordów. 
jak zapewnić ze pobrałem wszystkie. mogę oczywiście wywołać metodę tak długo az ilość w zwrotce jest <1000. jesli jednak będę miał duzą ilość aukcji to za każdym wywołaniem muszę pobrać wszystkie reporty i porównac te które już pobrał np do lokalnej bazy.
czy jest na to jakiś lepszy sposób. pobieranie od zadanego ID? od zadanej daty?

**Comment by MaciejPotepa** [comment]
Jak napisałem w poprzednim poście - tu masz [poradnik](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421), który powinien Ci podsunąć rozwiązanie. 

Do pobierania danych o transakcjach zalecamy Dzienniki zdarzeń.

**Comment by blochos** [comment]
Czy w dzienniku transakcji któryś z tagów będzie reprezentował numer aukcji. wchodząc w zakłądkę sprzedaż widzę numery aukci i po ich numerze chciałbym ściągnąć dane programem.

GetSiteJournalDeals pokazuje dealtransactionid np dwa razy. sprawdzajac jednak ten konkretny transactionid metodą getpostbyform... dostaje info o jednym kliencie 


a teraz przykład. oferta 6984601632
pobrany GetSiteJournalDeals gdzie tej oferty (numeru który widzi klient) nie widzę

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
	<SOAP-ENV:Body>
		<ns1:doGetSiteJournalDealsResponse>
			<ns1:siteJournalDeals>
				<ns1:item>
					<ns1:dealEventId>3526626680</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1516801791</ns1:dealEventTime>
					<ns1:dealId>1739803082</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>19890687</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3526626962</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1516801801</ns1:dealEventTime>
					<ns1:dealId>1739803082</ns1:dealId>
					<ns1:dealTransactionId>808260137</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>19890687</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3526627620</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1516801822</ns1:dealEventTime>
					<ns1:dealId>1739803082</ns1:dealId>
					<ns1:dealTransactionId>808260137</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>19890687</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3539958373</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1517485056</ns1:dealEventTime>
					<ns1:dealId>1744089850</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6969504084</ns1:dealItemId>
					<ns1:dealBuyerId>17738426</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3539963824</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1517485230</ns1:dealEventTime>
					<ns1:dealId>1744089850</ns1:dealId>
					<ns1:dealTransactionId>811063053</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6969504084</ns1:dealItemId>
					<ns1:dealBuyerId>17738426</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3541742788</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1517574300</ns1:dealEventTime>
					<ns1:dealId>1744662435</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>20354547</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3541744355</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1517574358</ns1:dealEventTime>
					<ns1:dealId>1744662435</ns1:dealId>
					<ns1:dealTransactionId>811424758</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>20354547</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3541745901</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1517574419</ns1:dealEventTime>
					<ns1:dealId>1744662435</ns1:dealId>
					<ns1:dealTransactionId>811424758</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101595336</ns1:dealItemId>
					<ns1:dealBuyerId>20354547</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3551051661</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1518013932</ns1:dealEventTime>
					<ns1:dealId>1747638940</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968325861</ns1:dealItemId>
					<ns1:dealBuyerId>3012152</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3551051939</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1518013941</ns1:dealEventTime>
					<ns1:dealId>1747638940</ns1:dealId>
					<ns1:dealTransactionId>813379320</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968325861</ns1:dealItemId>
					<ns1:dealBuyerId>3012152</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3551055306</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1518014061</ns1:dealEventTime>
					<ns1:dealId>1747638940</ns1:dealId>
					<ns1:dealTransactionId>813379320</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968325861</ns1:dealItemId>
					<ns1:dealBuyerId>3012152</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3560316848</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1518460650</ns1:dealEventTime>
					<ns1:dealId>1750618291</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968192391</ns1:dealItemId>
					<ns1:dealBuyerId>1422398</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3560320417</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1518460738</ns1:dealEventTime>
					<ns1:dealId>1750618291</ns1:dealId>
					<ns1:dealTransactionId>815342687</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968192391</ns1:dealItemId>
					<ns1:dealBuyerId>1422398</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3560323147</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1518460799</ns1:dealEventTime>
					<ns1:dealId>1750618291</ns1:dealId>
					<ns1:dealTransactionId>815342687</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968192391</ns1:dealItemId>
					<ns1:dealBuyerId>1422398</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3567006459</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1518778285</ns1:dealEventTime>
					<ns1:dealId>1752712155</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7008008181</ns1:dealItemId>
					<ns1:dealBuyerId>21642640</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3567008253</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1518778352</ns1:dealEventTime>
					<ns1:dealId>1752712155</ns1:dealId>
					<ns1:dealTransactionId>816738670</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7008008181</ns1:dealItemId>
					<ns1:dealBuyerId>21642640</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3567010862</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1518778442</ns1:dealEventTime>
					<ns1:dealId>1752712155</ns1:dealId>
					<ns1:dealTransactionId>816738670</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7008008181</ns1:dealItemId>
					<ns1:dealBuyerId>21642640</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3569735504</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1518966264</ns1:dealEventTime>
					<ns1:dealId>1753637503</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>24492235</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3569739636</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1518966396</ns1:dealEventTime>
					<ns1:dealId>1753637503</ns1:dealId>
					<ns1:dealTransactionId>817344505</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>24492235</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3569740527</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1518966426</ns1:dealEventTime>
					<ns1:dealId>1753637503</ns1:dealId>
					<ns1:dealTransactionId>817344505</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>24492235</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3573556066</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1519119016</ns1:dealEventTime>
					<ns1:dealId>1754818431</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101582044</ns1:dealItemId>
					<ns1:dealBuyerId>2733711</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3573557791</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1519119053</ns1:dealEventTime>
					<ns1:dealId>1754818431</ns1:dealId>
					<ns1:dealTransactionId>818115461</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7101582044</ns1:dealItemId>
					<ns1:dealBuyerId>2733711</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3574892365</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1519157510</ns1:dealEventTime>
					<ns1:dealId>1755236725</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7120455977</ns1:dealItemId>
					<ns1:dealBuyerId>7195577</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3574894915</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1519157571</ns1:dealEventTime>
					<ns1:dealId>1755236725</ns1:dealId>
					<ns1:dealTransactionId>818397263</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7120455977</ns1:dealItemId>
					<ns1:dealBuyerId>7195577</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3576336928</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1519227360</ns1:dealEventTime>
					<ns1:dealId>1755673557</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7089518860</ns1:dealItemId>
					<ns1:dealBuyerId>41456309</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3576337516</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1519227379</ns1:dealEventTime>
					<ns1:dealId>1755673557</ns1:dealId>
					<ns1:dealTransactionId>818688681</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>7089518860</ns1:dealItemId>
					<ns1:dealBuyerId>41456309</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3582777867</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1519589689</ns1:dealEventTime>
					<ns1:dealId>1757826152</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968335869</ns1:dealItemId>
					<ns1:dealBuyerId>562946</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3582778372</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1519589697</ns1:dealEventTime>
					<ns1:dealId>1757826152</ns1:dealId>
					<ns1:dealTransactionId>820076468</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968335869</ns1:dealItemId>
					<ns1:dealBuyerId>562946</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3582780759</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1519589741</ns1:dealEventTime>
					<ns1:dealId>1757826152</ns1:dealId>
					<ns1:dealTransactionId>820076468</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968335869</ns1:dealItemId>
					<ns1:dealBuyerId>562946</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3584677851</ns1:dealEventId>
					<ns1:dealEventType>1</ns1:dealEventType>
					<ns1:dealEventTime>1519664550</ns1:dealEventTime>
					<ns1:dealId>1758364728</ns1:dealId>
					<ns1:dealTransactionId>0</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>46013170</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3584678212</ns1:dealEventId>
					<ns1:dealEventType>2</ns1:dealEventType>
					<ns1:dealEventTime>1519664560</ns1:dealEventTime>
					<ns1:dealId>1758364728</ns1:dealId>
					<ns1:dealTransactionId>820441772</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>46013170</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
				<ns1:item>
					<ns1:dealEventId>3584680968</ns1:dealEventId>
					<ns1:dealEventType>4</ns1:dealEventType>
					<ns1:dealEventTime>1519664641</ns1:dealEventTime>
					<ns1:dealId>1758364728</ns1:dealId>
					<ns1:dealTransactionId>820441772</ns1:dealTransactionId>
					<ns1:dealSellerId>44570083</ns1:dealSellerId>
					<ns1:dealItemId>6968313695</ns1:dealItemId>
					<ns1:dealBuyerId>46013170</ns1:dealBuyerId>
					<ns1:dealQuantity>1</ns1:dealQuantity>
				</ns1:item>
			</ns1:siteJournalDeals>
		</ns1:doGetSiteJournalDealsResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by blochos** [comment]
Kolejna sprawa. zakładka SPRZEDANE pokazuje mi 34 transakcje natomiast DoGetSiteJournalDealsInfo 32 tyle tez zwraca DoGetSiteJournalDeals. 
Jakbym sobie wyobrażał prace z API. 
Pobieram wszystkie numery zakończonych aukcji. posługując się tym numerem lub/i identyfikatorem pobieram info o kupujących.
Mam wrazenie ze to nie do ogarnięcia :) albo najprwdopodobniej ja nie ogarniam

**Comment by MaciejPotepa** [comment]
> pobrany GetSiteJournalDeals gdzie tej oferty (numeru który widzi klient) nie widzę

Jaki numer masz  konkretnie na myśli? Bardzo chętnie Ci pomogę, ale proszę zadaj pytanie trochę precyzyjniej bo nie wiem do czego się ustosunkować i jak. 

> Kolejna sprawa. zakładka SPRZEDANE pokazuje mi 34 transakcje natomiast DoGetSiteJournalDealsInfo 32 tyle tez zwraca DoGetSiteJournalDeals.

Zakładka Sprzedane wyświetla informacje z ostatnich 60 DNI. Przez DoGetSiteJournalDealsInfo i DoGetSiteJournalDeals udostępniamy dane z ostatnich 14 dni.

**Comment by blochos** [comment]
napisałem 
(....)a teraz przykład. oferta 6984601632
pobrany GetSiteJournalDeals gdzie tej oferty (numeru który widzi klient) nie widzę

moze zapytam inaczej. metoda getsitejournaldeals zwraca np taki rekord
            <ns1:item>
               <ns1:dealEventId>3526626680</ns1:dealEventId>
               <ns1:dealEventType>1</ns1:dealEventType>
               <ns1:dealEventTime>1516801791</ns1:dealEventTime>
               <ns1:dealId>1739803082</ns1:dealId>
               <ns1:dealTransactionId>0</ns1:dealTransactionId>
               <ns1:dealSellerId>44570083</ns1:dealSellerId>
               <ns1:dealItemId>7101595336</ns1:dealItemId>
               <ns1:dealBuyerId>19890687</ns1:dealBuyerId>
               <ns1:dealQuantity>1</ns1:dealQuantity>
            </ns1:item>

ktora wartosc z tych tagow to numer aukcji, ktora widzi klient? p ozadnym z numerow nie moge wyszukac aukcji w panelu "SPRZEDANE"

**Comment by blochos** [comment]
a przepraszam. rozumiem ze to tag 7101595336 dealItemId

**Comment by blochos** [comment]
chciałbym posłużyc sie przykładami i wskazac co gdzie widze ale nie moge tego publikowac na formu. czy moge to jakos opisac i wyslac gdzies do analizy mailem?

**Comment by MaciejPotepa** [comment]
Wyślij zgłoszenie przez [formularz kontaktowy](https://pomoc.allegro.pl/kontakt) z załączonymi plikami, a tutaj wklej numer zgłoszenia.
