### ISSUE TITLE
Filtrowanie po formacie sprzedaży w metodzie doGetMySellItems

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#320]
Metoda doGetMySellItems przyjmuje jako parametr opcjonalny "**format oferty**", który w dokumentacji opisany jest następująco:

> filterFormat | int | niewymagany
Parametr pozwalający na filtrowanie po formacie oferty (0 - pokaż wszystkie, 1 - tylko oferty z Allegro, 2 - tylko oferty sklepowe; domyślna wartość: 0).

Po ostatnich zmianach opis ten najwyraźniej nie odpowiada stanowi faktycznemu, po podaniu wartości "2" (tylko oferty sklepowe) metoda nie zwraca żadnych ofert, mimo że są one widoczne w zakładce "Kup Teraz" w przeglądarce. Z kolei podanie wartości "1" (tylko oferty z Allegro) jest równoważne podaniu wartości "0" (pokaż wszystkie).

Czy obecnie jest jakaś możliwość filtrowania po formacie oferty w metodach WebAPI (doGetMySellItems i pokrewne)?

**Comment by PawelTaberski** [comment]
Obecnie chcemy zrezygnować z ofert sklepowych, bo nie różnią się już niczym od zwykłych. Pisaliśmy o tym tutaj #299. Dokumentację zaktualizujemy, dziękujemy za zwrócenie uwagi.

**Comment by k4pit4n** [comment]
Dzięki za wskazówkę :)
