### ISSUE TITLE
Problem  z aktywacją szkiców

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#3200]
Ponieważ w tym wątku https://github.com/allegro/allegro-api/issues/3162 nie doczekałem się od kilku dni odpowiedzi piszę w nowym.

Od kilkunastu już dni nie jesteśmy w stanie aktywować szkiców ofert.

Polecenie : 
**curl -X PUT "https://api.allegro.pl/sale/offer-publication-commands/5c49de1c-936c-11ea-8370-1fb09ee01260" -H "Accept: application/vnd.allegro.public.v1+json" -H "Content-type: application/vnd.allegro.public.v1+json" -H "Authorization: Bearer TOKEN" -d '{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"offers":[{"id":"9226295220"},{"id":"9226295231"},{"id":"9226295253"},{"id":"9226295277"},{"id":"9226295307"}],"type":"CONTAINS_OFFERS"}]}'**

Odpowiedź:
 **{"id":"5c49de1c-936c-11ea-8370-1fb09ee01260","taskCount":{"total":0,"success":0,"failed":0}}**

Sprawdzenie: 
 **curl -X GET "https://api.allegro.pl/sale/offer-publication-commands/5c49de1c-936c-11ea-8370-1fb09ee01260/tasks" -H "Authorization: Bearer TOKEN" -H "Accept: application/vnd.allegro.public.v1+json"**

Odpowiedź:
**{"tasks":[]}**

Aukcji w dalszym ciągu nie można aktywować. 
**Bardzo proszę o odpowiedź !!!**

**Comment by MaciejFrackowiak** [comment]
W przytoczonym wątku #3162 wybrzmiało moje zdanie:

> Zgodnie z moim poprzednim postem zamieszczę tu odpowiedź, gdy tylko otrzymam wyjaśnienie. 

Nie otrzymałem jeszcze informacji zwrotnej, stąd brak aktualizacji w poście. O sprawie pamiętam, przypominam się, jednak cierpliwość jest konieczna.
