### ISSUE TITLE
Problem z autoruzacją Nie można wyświetlić strony

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3201]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam problem z uzyskanie autoryzacji, otrzymuję błąd
Nie możemy wyświetlić strony
Numer błędu: a4eb41a12f1458f0
redirect_uri się zgadza w czym może być problem?
Numer błędu wystarczy czy muszę podać coś więcej?

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę dokładnie adres przekierowania - musi być zgodny 1:1, aby przekierowanie zadziałało. Twój błąd sugeruje, że jednak jest jakaś rozbieżność.

**Comment by pawelosajda** [comment]
Dziękuje za szybką odpowiedź byłem na innym koncie w https://apps.developer.allegro.pl/
