### ISSUE TITLE
offer-quantity-change-commands - 504 timeout

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3203]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dziś  około 6:30 poleciało seryjnie trochę błędów timeout. Obecnie nie występują

REQUEST 2020-05-12 06:36:51.2394303 
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/53bc73fe-2078-41e2-8a7a-bb97be4b7d01' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"modification":{"changeType":"FIXED","value":58},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"9086361191"}]}]}' \

RESPONSE 2020-05-12 06:36:54.2550591 Duration: 3015,6288ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },

  },
  "TraceId": "6ea61059327ec325",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

REQUEST 2020-05-12 06:36:50.8593927 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/8e9567a8-0d44-41f5-b16b-14f28f75423e' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-05-12 06:36:53.8909903 Duration: 3031,5976ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ServiceTimeoutException",
        "Details": null,
        "Message": "An error occurred",
        "Path": null,
        "UserMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
      }
    ],
    "ValidatedAt": null
  },
  
  },
  "TraceId": "21491a9dba5d786b",
  "Error": true,
  "StatusCode": 504,
  "Message": "{\"errors\":[{\"code\":\"ServiceTimeoutException\",\"message\":\"An error occurred\",\"details\":null,\"path\":null,\"userMessage\":\"Przekroczono czas wykonania zapytania. Spróbuj ponownie.\"}]}"
}

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - dane przekazałem już do właściwego zespołu, który prowadzi weryfikację.
