### ISSUE TITLE
Brakujące taski, czas przetwarzania

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3204]
WItam, zdarza się, iż sprawdzając wykonanie danego zadania pojawiają się brakujące taski.

Przykładowy guid 8e987c96-da2a-4f64-b9a6-8dd0d77098ec
Total: 19
Success: 18
Failed: 0

Problem był już zgłaszany, natomiast sytuacja dość często pojawia się dalej. 
Chcielibyśmy to odpowiednio zakodować bo aktualnie cały czas odpytujemy zasoby, aż total=success+failed stąd pytanie:
po jakim maksymalnie czasie mogą nastąpić zmiany w rezultacie danego guida?

**Comment by MaciejFrackowiak** [comment]
Zadania wykonują się asynchronicznie, odpytanie zasobu zasobu zwraca stan operacji na chwilę po jej zleceniu. Aby poznać szczegóły wykonaia operacji skorzystaj z [GET /sale/offer-quantity-change-commands/8e987c96-da2a-4f64-b9a6-8dd0d77098ec/tasks](https://developer.allegro.pl/documentation/#operation/getQuantityModificationCommandTasksStatusesUsingGET) - tylko tak uzyskasz szczegółowe, w pełni dokładne informacje dot. konkretnych ofert.

**Comment by dlis2010** [comment]
Witam ponownie,

@MaciejFrackowiak może źle się wyraziłem, niemniej jednak nie za bardzo się zrozumieliśmy. 
Proszę prześledź moją wiadomość raz jeszcze ;)

To właśnie wspomniany przez Ciebie zasób zwrócił mi wynik, który podałem w poprzedniej wiadomości:
```
Total: 19
Success: 18
Failed: 0
```
Jest to task z 2020-05-11 21:18:12, a w dalszym ciągu total nie jest równe success+failed

Moje pytanie brzmi czy mogę założyć przykładowo, że jeżeli po godzinie zasób w dalszym ciągu zwraca niekompletne informacje to czy już to tak pozostanie czy też może się zmienić.

**Comment by MaciejFrackowiak** [comment]
Nie, Ty skorzystałeś z [GET /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getQuantityModificationCommandStatusUsingGET), natomiast ja do requestu dołożyłem /tasks.
Ta subtelna różnica powoduje, że dla Twojego requestu stan wykonania zadania nie zmieni się już - zawsze będzie już 19/18/0. Natomiast, gdy skorzystasz z wersji z /tasks to zobaczysz 19 razy SUCCESS przy każdej ofercie i to jest pełne potwierdzenie wykonania zadania.
