### ISSUE TITLE
Znaki specjalne html

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3205]
Dostaje błąd:

`{"code":"VALIDATION_ERROR","message":"Invalid HTML subset"}`

Trace id:

7de8a719b690514d
7879644893f6191e
f4f0daf535fb5686
4e99994e8edf9d7

Może to dlatego że w opisie jest znak TM
Jeśli tak to w jaki sposób to zamieniać. Czy wogóle jest taka możliwość aby takei znaki były ?

**Comment by MaciejFrackowiak** [comment]
Jest taka możliwość - wystarczy w opisie umieścić zakodowane odpowiedniki.
Dla TM to będzie `&#x2122;`
W sieci znajdziesz strony z rozpisanymi znakami np. [ta strona](https://www.degraeve.com/reference/specialcharacters.php).

**Comment by pietrach** [comment]
Mimo to proszę sprawdzić po trace id co jest przyczyną tych błędów bo usunąłem wczoraj te znaki i to samo było a nie mam pomysłu.

**Comment by MaciejFrackowiak** [comment]
Przejrzałem kolejne requesty na podstawie trace-id i takie wnioski pojawiły się:

1. 7de8a719b690514d - payload nie zawierał numerów ofert, które chciałeś zakończyć grupowo;
2. 7879644893f6191e - payload zawierał TM oraz nieprawidłowe zależności pomiędzy znacznikami, np. `<b></b>`może być tylko pomiędzy `<p></p>`, również pojawiło się `</p>` bez samego `<p>` na poczatku; 
3. f4f0daf535fb5686 - jw.
4. 4e99994e8edf9d7 - tu użyłeś `&trade;`, które nie jest dozwolone.
