### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#3206]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Od kilu godzin mamy problemy z WebAPI, co chwilę dostajemy `Could not connect to host` przy metodach doGetBidItem2, doGetItemsInfo.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie tych metod - nie napotkałem problemu opisanego przez Ciebie. Poproszę o więcej szczegółów dot. przesyłanych requestów.
