### ISSUE TITLE
Zmiany kategorii

### ISSUE THREAD

**Issue by GrzegorzLewinski** [allegro/allegro-api#3207]
Witam.
Gdzie znajdę jakiekolwiek informacje odnośnie zmian ID kategorii oraz zmian samych kategorii na dla Allegro Rest API. Przejrzałem wszystkie aktualności od początku roku na https://developer.allegro.pl/news/ i nie ma tam żadnej wzmianki odnośnik zmian dla kategorii.

Przykładem jest kategoria "Opony-> Do motocykli i skuterów". Aktualnie kategoria ta zmieniła swoje ID z 257702 na 301082 dodatkowo w tej kategorii pojawiły się 2 dodatkowe kategorie. 

Klient twierdzi że nie dostał żadnej informacje na maila na którego została zarejestrowana aplikacja.

**Comment by MaciejFrackowiak** [comment]
Nie informujemy o każdej zmianie w ID kategorii / parametrów. Natomiast o kluczowych zmianach informujemy na stronie [dla sprzedających](https://allegro.pl/dla-sprzedajacych/kategoria/zmiany-w-parametrach). Dlatego ważne jest by na bieżąco odpytywać [zasoby](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters) o aktualne wartości kategorii i parametrów.

**Comment by GrzegorzLewinski** [comment]
Zmiana ID kategorii oraz rozbijanie kategorii na 2 podkategorie to dla nas bardzo kluczowa zmiana. Przy 20.000 produktów zasypiemy państwa niepotrzebnymi zapytaniami aby przypisać produktom odpowiednie kategorie a co za tym idzie parametry.

**Comment by MaciejFrackowiak** [comment]
Jesteśmy na to przygotowani - de facto to jedyna właściwa droga, aby być na bieżąco z kategoriami i parametrami.
