### ISSUE TITLE
Prośba o sprawdzenie logów allegro

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3209]
Witam,
Poproszę o sprawdzenie moich wywołań.
Wywołuję:
https://api.allegro.pl/sale/compatible-products?type=CAR&group.id=92b457e4c4f13dbadc66ea88e2bfb3d9&offset=1000&limit=200
w pętli. Zmieniam offset. Pierwsze 4 wywołania idą ok.
Przy 5 dostaję pustą odpowiedź ze statusem 400.
trace-id:bef177b88bc0ded0 wywołania 4 (ostatniego poprawnego) .
Czy możecie sprawdzić czy przyszło z mojego IP kolejne i co z nim jest nie tak?
Dla ostatniego dostaję:
header:content-length:0  
header:x-envoy-upstream-service-time:0  
header:date:Wed, 13 May 2020 08:50:37 GMT  
header:server:envoy  
nie wiem czy to Wasze nagłówki, czy moje.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi - widzę kolejne wywołania, czyli bez offsetu, 200, 400, 600, 800 i tu koniec. Kolejnego requestu już nie mamy w logach - nie dotarł on do nas niestety.

**Comment by kfijalko** [comment]
Znalazłem, przy każdym wywołaniu dodawałem do nagłówków token.
Czyli nagłówki w piątym kroku przekraczały 8k i Wasz serwer "wejściowy" odrzucał lub mój nie puszczał wywołania - nie znam się na sieciach/protokołach i .....
Takie odkrycie przy okazji mojego błędu.
Dziękuję za pomoc.
