### ISSUE TITLE
nowy numer karty płatności

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#321]
Witam, karta płatności ma dwa numery, np: Karta płatności nr 865958539 (8dc63fb3-746c-11e8-9dea-8582c5af79af). I o ile ten pierwszy numer 9-cyfrowy zwraca nam doGetPostBuyFormsDataForSellers w post-buy-form-id o tyle pytanie - skąd wytrzasnąć ten drugi numer ?
Dlaczego mi to jest potrzebne do szczęścia ? Bo to jedyne sensowne co widzę po czym mogę jednoznacznie przypisać komentarz do transakcji z sale/user-ratings?user.id, któe zwraca właśnie ten nowy numer ;-/ 
Jakieś sugestie skąd go mogę odgrzebać ?

**Comment by MarcinLuczak** [comment]
@partyumarty będziesz mógł pobierać ten identyfikator za pomocą zasobu, który udostępnimy za jakiś czas. Na chwilę obecną nie pobierzesz go przez API.

**Comment by partyumarty** [comment]
Czyli nie da się w żaden sposób jednoznacznie i na 100% trafnie przypisać komentarza do transakcji ?

**Comment by MarcinLuczak** [comment]
@partyumarty w tej chwili tylko za pomocą tego identyfikatora, ale tak jak pisałem - REST API go jeszcze nie zwraca.
