### ISSUE TITLE
Dodatkowe parametry obowiązkowe?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#3210]
Witam,
proszę o informację w jaki sposób:
1. Pobrać listę marek przypisanych do danej kategorii?
2. Jak przy wystawianiu oferty wstawić parametr marka?
3. Co zrobić jeżeli nie macie danej marki na liście?
4. Jak dodać parametr kod producenta?

Czy to ma tak wyglądać?
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1".
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "224017",
            "valuesIds": [
                "KOD_PRODUCENTA"
            ],
            "values": [],
            "rangeValue": null
        },		
        {
            "id": "237190",
            "valuesIds": [
                "???? CO TU MA BYĆ????"
            ],
            "values": [],
            "rangeValue": null
        },	
    ],

Pozdrawiam
Aleksy

**Comment by MaciejFrackowiak** [comment]
Przede wszystkim musisz pobrać parametry przewidziane dla danej kategorii - zrobisz to przy wykorzystaniu zasobu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). W ten sposób poznasz listę obowiązkowych i nieobowiązkowych parametrów, możliwe ich wartości oraz dostępne do wyboru konkretne wartości. 
Przykładowo:
```
{
            "id": "237190",
            "name": "Marka",
            "type": "string",
            "required": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null
            },
            "restrictions": {
                "minLength": 1,
                "maxLength": 100,
                "allowedNumberOfValues": 1
            }
        },
```
Dla podanego parametru Marka podajesz własną nazwę, która ma od 1 do 100 znaków. Podobnie dla Kod producenta.

**Comment by AleksyZajac** [comment]
Oj chyba nie... Dla grupy 122802 masz zdefiniowane marki.
                             'dictionary' => [
                                                {
                                                  'dependsOnValueIds' => [],
                                                  'value' => 'A.Martinez',
                                                  'id' => '222181_298761'
                                                },
                                                {
                                                  'dependsOnValueIds' => [],
                                                  'value' => 'Admira',
                                                  'id' => '222181_298745'
                                                },
i chciałbym podać markę która jest już zdefiniowana bo wtedy padnie mi w odpowiednią markę a nie do "inne".

Co mam podać  'id' => '222181_298745' czy to: 'value' => 'Admira' i jak?

{
"id": "237190",
"valuesIds": [
"'222181_298745"
],
"values": [],
"rangeValue": null
}

?

**Comment by MaciejFrackowiak** [comment]
Ku wyjaśnieniu - podałem przykładowo i jak wspomniałem konieczne jest pobranie parametrów dla danej kategorii zawsze osobno. ID kategorii, której parametry podejesz też jest inne tzn. 260311.
Natomiast w kontekście oferty z "Admira" w parametrze Marka należy parametr przekazać tak:

```
{
            "id": "222181",
            "valuesIds": [
                "222181_298745"
            ],
            "values": [],
            "rangeValue": null
        },
```

**Comment by AleksyZajac** [comment]
Ok a jak ma to wyglądać dla kodu producenta, bo 
{
"id": "237190",
"valuesIds": [
"???? CO TU MA BYĆ????"
],
"values": [],
"rangeValue": null
},
nie idzie...
Dostaję:
$VAR1 = {
          'errors' => [
                        {
                          'userMessage' => "Parametr tekstowy nale\x{c5}\x{bc}y uzupe\x{c5}\x{82}ni\x{c4}\x{87} poprzez warto\x{c5}\x{9b}\x{c4}\x{87} dla 224017.",
                          'path' => '',
                          'details' => '',
                          'message' => 'You can only assign string parameter by value for 224017.',
                          'code' => 'VALIDATION_ERROR'
                        }
                      ]
        };

**Comment by MaciejFrackowiak** [comment]
Dla Kod producenta podajesz wartość stringową - od 2 do 50 znaków, przykład:

```

{
"id": "224017",
"valuesIds": [],
"values": [
"Mój kod"
],
"rangeValue": null
},
```
