### ISSUE TITLE
Problem z autoryzacja w SOAP API

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3211]
Występuje problem: 
 - [X] z metodą WebAPI
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Występuje problem z autoryzacją po przy pomocy identyfikatora sesji który otrzymujemy od Was z wykorzystaniem metody doLoginWithAccessToken:

```
2020-05-13T14:38:24+02:00 INFO (6): doLoginWithAccessToken
-------------------------------------

REQUEST: 

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:DoLoginWithAccessTokenRequest><ns1:accessToken>(...ciach...)</ns1:accessToken><ns1:countryCode>1</ns1:countryCode><ns1:webapiKey>675ae747-(...ciach...)</ns1:webapiKey></ns1:DoLoginWithAccessTokenRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>

-------------------------------------
RESPONSE: 

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doLoginWithAccessTokenResponse><ns1:sessionHandlePart>e3a0d3(...ciach...)</ns1:sessionHandlePart><ns1:userId>3248820</ns1:userId><ns1:serverTime>1589373504</ns1:serverTime></ns1:doLoginWithAccessTokenResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>


2020-05-13T14:38:24+02:00 INFO (6): doGetMyData
-------------------------------------

REQUEST: 

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:DoGetMyDataRequest><ns1:sessionHandle>e3a0d3(...ciach...)</ns1:sessionHandle></ns1:DoGetMyDataRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>

-------------------------------------
RESPONSE: 

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_NO_SESSION</faultcode><faultstring>Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!</faultstring><faultactor>doGetMyData - Wrong session</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

Problem jest o tyle poważny, że podczas odświeżania access tokena odpytujemy także o nowy identyfikator sesji i dane klienta. Klucz który jest przez Was zwrócony przez metodę doLoginWithAccessToken jest identyczny jak ten który wysyłamy w polu sessionHandle w metodzie doGetMyData. Problem pojawił się dzisiaj

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować, proszę o potwierdzenie.

**Comment by kormichu** [comment]
Potwierdzam. Dzięki za szybką reakcje

**Comment by kormichu** [comment]
Problem znowu występuje

**Comment by kormichu** [comment]
Numer zgłoszenia przez formularz kontaktowy: "09695881" ref:_00D24aE05._5003V3mi8T:ref

Pytanie, czy macie jakieś zabezpieczenie przypisujące identyfikator sesji do konkretnego adresu IP ?

**Comment by PrzemyslawLukanowski** [comment]
Analizujemy jeszcze przesłany request. Błędu nie udało mi się powtorzyć, nie otrzymujemy także innych podobnych zgłoszeń. Co do zabezpieczeń - informację na ten temat znajdziesz w naszym [FAQ](https://allegro.pl/webapi/faq.php#faq_4).

**Comment by kormichu** [comment]
Ok widzę informację, która mnie interesowała:

> Błąd ten może być wynikiem jednego z zabezpieczeń, które stosowane jest w WebAPI. Podczas wywoływania metody wykorzystującej identyfikator sesji, sprawdzane jest czy IP z którego wywoływana jest metoda jest tym samym IP z poziomu którego sesja była uprzednio utworzona. Należy upewnić się, że obie metody wywoływane są z poziomu tego samego IP.

Czy dla REST API jest podobnie ?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie ma takiej blokady, dla REST API możesz wygenerować token z jednego IP i wywołać odpowiedni zasób na innym IP.
