### ISSUE TITLE
Prośba o aktywacje konta sanbox

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3212]
Prośba o aktywacje konta klienta
login DDDtest

**Comment by MaciejFrackowiak** [comment]
Konto aktywowałem - wybrałeś konto Firma, dlatego w celu jego weryfikacji proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).
