### ISSUE TITLE
Brakuje metody w REST API do pobrania wysokości aktualnych kosztów po usunięciu metody doMyBilling

### ISSUE THREAD

**Issue by serten-d** [allegro/allegro-api#3213]
Witam,

W jaki sposób można odczytać informację o aktualnych kosztach wystawiania pojazdów w allegro ?
Zakładałem, że jeżeli metoda SOAP doMyBilling została usunięta to dodana została jakaś metodę w REST API, która zwraca te informacje.
Jednak nie mogę takiej metody znaleźć w aktualnej dokumentacji Rest API.

Jeżeli takiej metody nie ma to proszę o uzupełnienie tego, ponieważ jest to potrzebne, aby informować klientów jakie są ich aktualnie koszty wystawiania pojazdów.

**Comment by MaciejFrackowiak** [comment]
Udostępniamy zasób [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#tag/Billing), którym pobierzesz informacje o wszelkich rozliczeniach na swoim rachunku, w tym kosztach wystawienia ogłoszeń moto.
