### ISSUE TITLE
Błąd INVALID_JSON - nieprawidłowe żądanie

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3215]
Potrzebuje pomocy bo nie mam pojęcia co jest nie tak. Dostaje taki błąd w kilku produktach:

`[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Nieprawidu0142owe u017cu0105danie."}]`

Trace-id:
7c78177a05300d5d
cf2d4ca130a767c4
89b7c4cc96910139
e70411ba73910e13
596e023477e933dc
1c63ad430bbea3c1
fdd36fb4e48d99fc

**Comment by MaciejFrackowiak** [comment]
Niestety, nie widzę w logach payload Twoich requestów - tylko informację o błędzie 400. Proszę podeślij nam przykładowy request poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) (dopisz proszę nr posta).

**Comment by pietrach** [comment]
@MaciejFrackowiak wysłałem

**Comment by MaciejFrackowiak** [comment]
Tak, już otrzymałem dane - w parametrach znalazłem:

```
{
			"id": "237206",
			"valuesIds": [],
			"values": "CLH15-3",
			"rangeValue": null
		},
```

Wartość powinna być w [] - dla każdego innego parametru poprawnie podałeś wartości, tu tego brakuje.
