### ISSUE TITLE
Wykorzystanie alternatywnej treści wiadomości e-mail (text/plain) prezentowanej w powiadomieniach allegro

### ISSUE THREAD

**Issue by dbednarczykiai** [allegro/allegro-api#3219]
:bulb: **Sugestia**

Wysyłając wiadomość do kupującego z naszego oprogramowania wysyłana jest ona wraz z alternatywną treścią dla agentów pocztowych nieobsługujących html (alternatywna treść w kodzie wiadomości e-mail). Widzimy, że w powiadomieniach Allegro prezentowana jest wersja wiadomości e-mail HTML po prostu z wyciętymi tagami HTML, zamiast alternatywnej wersji tekstowej pozbawionej html.

Czy planują Państwo także obsługę treści alternatywnych (tekstowych) wiadomości e-mail prezentowanych w powiadomieniach? Na pewno zwiększyłoby to czytelność dla kupujących.

**Comment by MaciejFrackowiak** [comment]
To kwestia poza samym API - dotyczy wszelkich powiadomień z serwisu. Bardzo proszę w tej kwestii o kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by dbednarczykiai** [comment]
Dziękuję
