### ISSUE TITLE
Filtrowanie aukcji

### ISSUE THREAD

**Issue by mbx88** [allegro/allegro-api#322]
Witam,

czy da się jakoś pobrać aukcje, które zostały wystawione np miesiąc lub rok temu?

**Comment by MarcinLuczak** [comment]
@mbx88 masz na myśli oferty cały czas trwające? Doprecyzuj proszę co dokładnie chcesz uzyskać, co wyfiltrować.

**Comment by mbx88** [comment]
Witam,
tak chodzi o oferty cały czas trwające.

Chciałbym wyszukać wszystkie oferty które zostały wystawione ponad 3 miesiące temu, czyli np warunek na dziś to
data wystawienia < 21.03.2018

**Comment by MarcinLuczak** [comment]
To niestety na chwilę obecną nie udostępniamy takiego sposobu filtrowania w naszym API.
