### ISSUE TITLE
Dodawanie nr przesyłki poprzez API - 2 szt. produktów - duże gabaryty - zapytanie

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3221]
Co się stanie gdy ktoś kupi z jednej oferty 2 szt. produktu. Ten produkt jest na tyle duży, że każda sztuka będzie musiała zostać wysłana oddzielną przesyłką. Czy podczas pobierania zamówienia w strukturze JSON taka pozycja zostanie rozdzielona na dwie odrębne czyli dostaniemy w `lineItems` 2 pozycje po 1 szt.  (ta sama oferta) czy przyjdzie jako 1 pozycja z ilością 2 ?

Jeśli zostanie rozdzielona na 2 to ok ale jeśli nie to jak wtedy wysłać numer przesyłki dla każdego z tych 2 sztuk ? 2 razy to samo żądanie z tym samym `lineItem.id` tylko w każdym numer przesyłki inny ?

**Comment by MaciejFrackowiak** [comment]
W lineItem znajduje się pole quantity - w tym przypadku zwróci 2.
Tak, w takiej sytuacji przesyłasz do jednego lineItem dwa numery przesyłek.
