### ISSUE TITLE
Kategorie a parametry obowiązkowe?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#3222]
Witam,
proszę o informację czy będą Państwo w RestAPI zmieniać strukturę grup, chodzi mi o grupy które zawierają nazwę producenta jak:
122643 | Gitary i akcesoria / Akustyczne / Cort
122644 | Gitary i akcesoria / Akustyczne / Crafter
258032 | Gitary i akcesoria / Akustyczne / Echo
122645 | Gitary i akcesoria / Akustyczne / Epiphone
122646 | Gitary i akcesoria / Akustyczne / Fender
122647 | Gitary i akcesoria / Akustyczne / Ibanez

w interfejsie WWW jest grupa "Gitary i akcesoria / Akustyczne" i nie ma poszczególnych grup prezentujących markę towaru.

Prosiłbym o informację.

**Comment by MaciejFrackowiak** [comment]
W serwisie WWW podane przez Ciebie marki znajdziesz w polu wyboru Marka - jak na zrzucie:
![obraz](https://user-images.githubusercontent.com/53566763/82176994-8f22c580-98d8-11ea-8aa2-4fa9acc58a40.png)
Natomiast w REST API odpowiedzialny za parametr Marka dla kategorii 260274 jest parametr o identyfikatorze 221493, dla którego podane są kolejne wartości:

```
"dictionary": [
                {
                    "id": "221493_295913",
                    "value": "Baton Rouge",
                    "dependsOnValueIds": []
                },
                {
                    "id": "221493_295917",
                    "value": "Chateau",
                    "dependsOnValueIds": []
                },
                {
                    "id": "221493_295921",
                    "value": "Cort",
                    "dependsOnValueIds": []
                },
                {
                    "id": "221493_295925",
                    "value": "Crafter",
                    "dependsOnValueIds": []
                },
                {
                    "id": "221493_295929",
                    "value": "Dean",
                    "dependsOnValueIds": []
                },
....
```

**Comment by AleksyZajac** [comment]
W takim razie skoro mamy parametr "Marka" to w jakim celu to samo powtarzacie w strukturze kategorii?

W jakim celu w są kategorie: 
122643 | Gitary i akcesoria / Akustyczne / Cort
122644 | Gitary i akcesoria / Akustyczne / Crafter
258032 | Gitary i akcesoria / Akustyczne / Echo

(UWAGA!!! Podałem identyfikatory grup a nie parametrów).

Gdzie mam przypisać gitarę firmy Cort ? Do jakiej kategorii ?

**Comment by MaciejFrackowiak** [comment]
Nie mamy kategorii o podanych przez Ciebie identyfikatorach - w REST API zwracamy przykładowo komunikat:

```
            "message": "Category '258032' not found",
```
A na WWW, w formularzu wystawiania: Wybrano nieprawidłowy numer kategorii.

**Comment by AleksyZajac** [comment]
Macie tylko że w systemie testowym.

**Comment by MaciejFrackowiak** [comment]
Oj, to takie informacje musisz podawać w zgłoszeniu - domyślnie działamy i odpowiadamy w kontekście produkcji. I tak, drzewo kategorii i parametrów na Sandbox odbiega od tego produkcyjnego - w najbliższej przyszłości chcemy je ujednolicić.
