### ISSUE TITLE
Błędny typ zwracanego Payout.id

### ISSUE THREAD

**Issue by p0wertiger** [allegro/allegro-api#3223]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dokumentacja zasobu `/payments/payment-operations` deklaruje dla wyniku typu "PAYOUT" wartość atrybutu payout.id jako UUID, tymczasem faktyczna odpowiedź zwracana przez API to INT.

```
{
    "type": "PAYOUT",
    "group": "OUTCOME",
    "wallet": {
        "paymentOperator": "PAYU",
        "type": "AVAILABLE",
        "balance": {
            "amount": "0.00",
            "currency": "PLN"
        }
    },
    "occurredAt": "2020-03-02T01:33:12.491Z",
    "value": {
        "amount": "-9999.99",
        "currency": "PLN"
    },
    "payout": {
        "id": "155511734"
    }
}
```

Proszę poprawić zwracaną wartość albo specyfikację API.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, słuszne spostrzeżenie. W tym polu nie zwracamy UUID - poprawimy dokumentację w najbliższym czasie.

**Comment by p0wertiger** [comment]
Klienta API generuje się z pliku swaggera jeśli jest udostępniany, w wyniku w kodzie dostaniemy Guid, więc przy błędnych danych będzie exception. Nie było trudno na to trafić, aż się dziwię, że do tej pory tego nikt nie zgłosił.

**Comment by MaciejFrackowiak** [comment]
Czasem właśnie tak bywa - niby oczywiste, a dopiero po jakimś dłuższym czasie któryś z użytkowników znajdzie rozbieżność.

**Comment by p0wertiger** [comment]
Wracam do tematu ponieważ stała się ciekawa sprawa. Zgodnie z #3134 i potwierdzone przez #3245  został właśnie usunięty zasób `/payments/payment-id-mappings` . Pobierając listę operacji z /payments/payment-operations dostajemy liczbę całkowitą zgodnie z tym co napisane powyżej. Próbując wysłać zapytanie do /payments/payment-operations z tym payment.id dostajemy pusty wynik, a na GUID tego już nie możemy mapować. W związku z tym jedynym sposobem na wyszukanie PAYOUT jest teraz z zakresu dat. 

Przykład:
```
GET /payments/payment-operations?group=OUTCOME&limit=100&occurredAt.gte=2020-05-10T00:00:00.000Z&occurredAt.lte=2020-05-10T23:59:59.999Z

{
    "paymentOperations": [
        {
            "type": "PAYOUT",
            "group": "OUTCOME",
            "wallet": {
                "paymentOperator": "PAYU",
                "type": "AVAILABLE",
                "balance": {
                    "amount": "0.00",
                    "currency": "PLN"
                }
            },
            "occurredAt": "2020-05-10T00:33:04.354Z",
            "value": {
                "amount": "-1234.56",
                "currency": "PLN"
            },
            "payout": {
                "id": "159779221"
            }
        },
        {
            "type": "PAYOUT",
            "group": "OUTCOME",
            "wallet": {
                "paymentOperator": "P24",
                "type": "AVAILABLE",
                "balance": {
                    "amount": "0.00",
                    "currency": "PLN"
                }
            },
            "occurredAt": "2020-05-10T00:33:04.279Z",
            "value": {
                "amount": "-9876.54",
                "currency": "PLN"
            },
            "payout": {
                "id": "159779204"
            }
        }
    ],
    "count": 2,
    "totalCount": 2
}
```

```
GET /payments/payment-operations?group=OUTCOME&limit=100&payment.id=159779221

{
    "paymentOperations": [],
    "count": 0,
    "totalCount": 0
}
```

I co teraz?

**Comment by MaciejFrackowiak** [comment]
Usunęliśmy mapowanie płatności, natomiast Twoje zgłoszenie dot. id wypłaty - to są dwa niezależne od siebie identyfikatory. Query parameters dla zasobu [GET /payments/payment-operation](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) pozwalają filtrować po payment.id (które jest UUID), a nie payout.id.

**Comment by p0wertiger** [comment]
Czyli, jak rozumiem, filtrować po payout.id się nie da by design? Próbuję cały czas znaleźć pewniejszej metody na poskładanie transakcji, które wchodzą w zawartość payoutu.

**Comment by MaciejFrackowiak** [comment]
Tak, dokładnie, nie dodaliśmy możliwości filtrowania po id wypłaty.

**Comment by p0wertiger** [comment]
Sprawdziłem ponownie dokumentację, nadal jest UUID zamiast INT dla payout.id

**Comment by PrzemyslawLukanowski** [comment]
@p0wertiger Dzisiaj zaktualizowaliśmy dokumentację.
