### ISSUE TITLE
Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#3225]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od dzisiaj przestało działać pobieranie ofert na produkcji i sandboxie. Podaję parametry produkcyjne.

Parametry restClient:
object(RestClient)#24 (8) {
  ["options"]=>array(11) {
    ["headers"]=>array(4) {
      ["accept"]=>string(38) "application/vnd.allegro.public.v1+json"
      ["content-type"]=>string(38) "application/vnd.allegro.public.v1+json"
      ["accept-language"]=>string(2) "PL"
      ["authorization"]=>string(1143) "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiZXhwIjoxNTg5NjY0MTQ3LCJqdGkiOiI3NTlhZGVlMS1kYjFhLTRmNDgtYTBmZC04NzJlNjhhZmY4ODQiLCJjbGllbnRfaWQiOiJmMzlhNDQ0NDI0ZDA0ZGI4ODM4ZjRmOTJiYjE4NjBlOSJ9.V5hr2HZiwzA37Q6k4uYzXVEyDjoTkW_oZdpHov5ExjchXgTtgVwA1nKOmOQTV8yNphol03xvF-jU5tswwT3EOh1tvFkA9HQDLcJxJoUBTI_kIvdm8hCkzlHIuL_xFiTujvOPrmJ_Ak0Ki3aqxH8EeoL8Z0jhnnqnglThszZ0A0PmaVQpUhPY8RH76BCvRawkGtG9CRJxm3_Y3oQ5clFLs-F13gpuoJ8Iodtje49e6lGluGZt-5U0sSKFlqt2SOGtFQV8Yb2wJAzhmJxhPyzBFmtmJdDD8l_uU78wvyKGu1JW552MsINfksVCTIIxYrD7GH4AGrLEGC1DI__vu8mVDg"
    }
    ["parameters"]=>array(0) {
    }
    ["curl_options"]=>array(0) {
    }
    ["build_indexed_queries"]=>bool(false)
    ["user_agent"]=>string(20) "PHP RestClient/0.1.7"
    ["base_url"]=>NULL
    ["format"]=>NULL
    ["format_regex"]=>string(22) "/(\w+)\/(\w+)(;[.+])?/"
    ["decoders"]=>array(2) {
      ["json"]=>string(11) "json_decode"
      ["php"]=>string(11) "unserialize"
    }
    ["username"]=>NULL
    ["password"]=>NULL
  }
  ["handle"]=>NULL
  ["response"]=>NULL
  ["headers"]=>NULL
  ["info"]=>NULL
  ["error"]=>NULL
  ["response_status_lines"]=>NULL
  ["decoded_response"]=>NULL
}

url:
 "https://api.allegro.pl/sale/offers?publication.status=ACTIVE&seller.id=80830642"

method:
 "GET"

response:
object(stdClass)#71 (1) {
  ["errors"]=>array(1) {
    [0]=>object(stdClass)#24 (5) {
      ["code"]=>string(21) "INTERNAL_SERVER_ERROR"
      ["message"]=>string(22) "Internal server error."
      ["details"]=>NULL
      ["path"]=>NULL
      ["userMessage"]=>string(61) "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
    }
  }
}

**Comment by drzemik** [comment]
Problem już rozwiązany.

**Comment by mjag8** [comment]
Podpinam się, zauważyłem, że przez ostatnie tygodnie udany request sale/offers to rzadkość, w zasadzie niezależnie od ilości danych do zwrócenia łapał się tylko na timeout. Wczoraj i dziś dostaję błąd serwera

**Comment by MaciejFrackowiak** [comment]
@mjag8 Proszę podaj nam trace-id przykładowego wywołania.

**Comment by drzemik** [comment]
Problem rozwiązany. Dzięki

 

Pozdrawiam

Dariusz Drzemicki

**Comment by edatPL** [comment]
Witam
Dotknął mnie dzisiaj ten problem:

Wystąpił błąd podczas przesyłania załącznika:
Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.

Oprogramowanie Soneta enova365 z dodatkiem Allegro

**Comment by Lukasz-Zurek** [comment]
Podaj proszę tracę-id dla wspomnianego wywołania. Zweryfikuję problem.

**Comment by edatPL** [comment]
Chyba znalazłem problem w nieopłaconych rozliczeniach :)
Obecnie mam:

Twoja płatność jest przetwarzana
Przetwarzanie twojej płatności trwa dłużej niż zazwyczaj. Prosimy, sprawdź historię operacji za chwilę.

konto edat_pl_test

Mam nadzieję, że to tylko to :)

**Comment by Lukasz-Zurek** [comment]
Cieszę się, że udało się to wyjaśnić. Oczywiście jeśli problem się powtórzy i przyczyna nie będzie znana - daj proszę znać.

**Comment by edatPL** [comment]
Niestety problem występuje nadal
**To jest jedyna informacja jaką mam:**

Wersja programu: 2110.2.5 release 2021-12-08 12:40:19
===============================================
Komentarz:
Wystąpił błąd podczas przesyłania załącznika:

Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.

Źródło:
Soneta.e-Sklepy

Wywołanie:
   w Soneta.e_Sklepy.Allegro.Offers.OfferService.CreateAttachmentForOffer(String contentType, String contentInBase64, String jwtToken)
   w Soneta.e_Sklepy.Allegro.Workers.OfferServiceWorker.UploadImages(Offer offer, String jwtToken)
   w Soneta.e_Sklepy.Allegro.Workers.OfferServiceWorker.CreateOffer(Offer offer, String token)
   w Soneta.e_Sklepy.Allegro.Workers.OfferServiceWorker.HandleFilledParameters(FillParameters parameters, Offer offer, List`1 requiredParameters, String token)
   w Soneta.e_Sklepy.Allegro.Workers.OfferServiceWorker.<>c__DisplayClass11_0.<CreateOffer>b__1()
   w Soneta.Business.Forms.FormResultHandler.HandleWithProgress(String caption, Func`1 handler)
   w Soneta.Business.Forms.FormResultHandler.ShowQueryContext(Context cx, QueryContextInformation qci, String caption, Boolean newThread)
   w Soneta.Business.Forms.WorkerCommands.MyCommand.OpenForm(Context context, Object result)
   w Soneta.Business.Forms.WorkerCommands.MyCommand.rowInSession(IRow data)
   w Soneta.Business.Forms.WorkerCommands.MyCommand.go()

Jeżeli potrzebne są jakieś inne informacje to proszę o pomoc, w którym miejscu mógłbym je znaleźć.

**Comment by Lukasz-Zurek** [comment]
W tej sytuacji najlepiej będzie jak skontaktujesz się z twórcą oprogramowania. Jeżeli problem występuje po naszej stronie, będzie on mógł skontaktować się z nami i udostępnić szczegółowe logi potrzebne do zweryfikowania zgłoszenia.
