### ISSUE TITLE
parametr user.id - sugeruję go usunąć

### ISSUE THREAD

**Issue by PhotoSoft** [allegro/allegro-api#3226]
:bulb: **Sugestia**
Witam,
po co w poniższych zasobach trzeba podawać user.id?

> /sale/offer-tags?user.id=
> /sale/loyalty/promotions?user.id=
> /sale/offer-variants?user.id=
> /after-sales-service-conditions/warranties?sellerId=
> /after-sales-service-conditions/implied-warranties?sellerId=
> /after-sales-service-conditions/return-policies?sellerId=
> /sale/offer-additional-services/groups?user.id=
> /sale/shipping-rates?seller.id=
> /sale/size-tables?user.id=

I tak nie można pobrać danych innego sprzedawcy, więc nie ma to sensu i można by usunąć ten parametr. Po za tym widać, że trzymał się ktoś schematu z nazewnictwem :D

**Comment by MaciejFrackowiak** [comment]
W przypadku zasobów, w których podajemy w ścieżce seller.id/user.id kierowaliśmy się [rekomendacją](https://allegro-restapi-guideline.readthedocs.io/en/latest/Resource/#urls-for-users-collections). Twoją sugestię przekazuję natomiast do osób bezpośrednio odpowiedzialnych za rozwój REST API.

**Comment by PhotoSoft** [comment]
Jeśli dobrze rozumiem to zgodnie z tą rekomendacją zamiast zasobu **/sale/offers** powinien być **/users/{userId}/sale/offers**
Zamiast **/order/events** powinien być **/users/{userId}/order/events** itd.

A tak nie jest, bo do tego wystarczy token, więc sami widzicie :)

**Comment by MaciejFrackowiak** [comment]
Widzimy, wiemy - jak wspomniałem sugestię przekazałem.

**Comment by MaciejFrackowiak** [comment]
Dzisiaj wdrożyliśmy zmianę - https://github.com/allegro/allegro-api/issues/3625.
