### ISSUE TITLE
/order/refund-claims - zwroty prowizji za wiele przedmiotów

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#3227]
Dzień dobry, mam szybkie pytanie, czy zasób /order/refund-claims umożliwia złożenie wniosku dla kilku przedmiotów naraz (oczywiście w obrębie jednego zamówienia)? Jeżeli dobrze rozumiem dokumentację jest tam podany przykład zapytania dla jednego produktu.

**Comment by PrzemyslawLukanowski** [comment]
Zasób przyjmuje tylko jeden przedmiot z zamówienia. Nie można przekazać większej liczby.
