### ISSUE TITLE
Brak nowych wydarzeń

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#3229]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Rest APi ponownie nie zwraca informacji o nowych wydarzeniach , problem jest od godziny 12.30

Proszę o informacje czy ktoś pracuje nad przywróceniem działania serwisu.

Pozdrawiam
Pawłowicz

**Comment by mojosoft** [comment]
Problem jest większy, nie działa cała poczta przechodząca przez allegromail, nie działa konto na allegro, kompletny brak informacji o zamówieniach

**Comment by PrzemyslawLukanowski** [comment]
Wiemy o problemie, odpowiedni zespół pracuje nad rozwiązaniem.

**Comment by mojosoft** [comment]
to może poinformować kupujących, podczas dokonywania zakupu, że jest awaria i czas realizacji może się wydłużyć z winy allegro

**Comment by mojosoft** [comment]
W związku z licznymi awariami taką opcje powinniście sobie wprowadzić, wówczas klient na etapie dodawania produktu do koszyka miałby już wiedzę że jego zamówienie w związku z problemami technicznym będzie zrealizowane w późniejszym czasie. i mógłby sie z niej ewentualnie wycofać.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za tę sugestię, przekażę ją do odpowiedniego zespołu. Na tę chwilę wszystkie operacje powinny już działać prawidłowo.
