### ISSUE TITLE
Czy można przygotować nowy standard opisu dla WebAPI?

### ISSUE THREAD

**Issue by Mesiek1000** [allegro/allegro-api#323]
Witam!
Szukajac w dokumentacji jak przystosować opis według nowego standardu (FID 341) znalazłem tylko wskazówki do RestAPI. Czy to również można wykorzystać w WebAPI? Przy dostosowaniu opisu w formacie JSON pojawia się problem **ERR_REFERENCED_VALUE_NOT_EXISTS** (Podano identyfikator (uuid) warunku, który nie istnieje).

**Comment by MarcinLuczak** [comment]
@Mesiek1000 nie wiem czy dobrze zrozumiałem Twoje pytanie.

Opis oferty przygotowany w ramach nowych zasad można przekazać przez API tylko jako JSON. W przypadku WebAPI opis przygotowany w JSON przekazujesz właśnie w fidzie 341.

Komunikat błędu **ERR_REFERENCED_VALUE_NOT_EXISTS** oznacza, że jeden z warunków oferty jaki podałeś w swoim requeście jest nieprawidłowy.

**Comment by Mesiek1000** [comment]
Nadal nie mogę zlokalizować tego warunku, który jest błędny.

**$client->doNewAuctionExt($response['session-handle-part'], $form,  0, $local, null, $variants, null, $afterSalesServiceConditions);**

**Comment by MarcinLuczak** [comment]
@Mesiek1000 

> Nadal nie mogę zlokalizować tego warunku, który jest błędny.
> $client->doNewAuctionExt($response['session-handle-part'], $form, 0, $local, null, $variants, null, $afterSalesServiceConditions);

Wszystkie swoje warunki oferty możesz pobrać przez te zasoby:

- warunki reklamacji - https://developer.allegro.pl/documentation/#/after-sales-service-conditions/getPublicSellerListingUsingGET
- warunki zwrotów - https://developer.allegro.pl/documentation/#/after-sales-service-conditions/getPublicSellerListingUsingGET_1
- warunki - gwarancji - https://developer.allegro.pl/documentation/#/after-sales-service-conditions/getPublicSellerListingUsingGET_2

Pobierz i porównaj z tym, co podajesz w requeście przy wystawianiu oferty. 

Z kodem, który podałeś, niestety Ci nie pomogę. Support prowadzimy tylko na warstwie interfejsu naszych API, czyli na XML-ach i JSON-ach.
