### ISSUE TITLE
Niedziałające SOAP API na sandboxie

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3231]
Występuje problem: 
 - [X] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [X] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**
Adres z plikiem wsdl https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl przestał odpowiadać. Nie widzi domeny

**Comment by PrzemyslawLukanowski** [comment]
Czy problem nadal występuje? Nie udało mi się go powtórzyć.

**Comment by kormichu** [comment]
Hmm, już nie. Jak zapytałem o adres IP dla w/w domeny to dostałem SERVFAIL (dns google):
```
nslookup webapi.allegro.pl.allegrosandbox.pl
```

Zamykam
