### ISSUE TITLE
Zmiana szczegółów aktywnych ofert

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3232]
[Jak zmienić szczegóły oferty po jej wystawieniu?](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#)

Czy te zasady obowiązują na sandboxie, bo jak kupię przedmioty z mojej oferty i potem zmieniam tytuł to nie ma błędu i został poprawnie zmieniony.

W dokumentacji pisze 

> Możesz zmienić tytuł oferty jeśli nie doszło w niej jeszcze do sprzedaży (jeśli nie pojawiły się w niej żadne oferty kupna).

Id oferty : `6208146442`
Trace-Id: `778544461714e562`

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, również udało mi się zmienić tytuł. Zachowanie powinno być podobne na obu środowiskach, dlatego przekazuję ten temat do analizy do odpowiedniego zespołu.

**Comment by AnimalDEV** [comment]
Czy te zasady obowiązują również dla ofert dezaktywowanych, czy są jakieś inne?

**Comment by PrzemyslawLukanowski** [comment]
Tak, dla ofert w statusie ENDED również obowiązują te zasady. Jeżeli w takiej ofercie była oferta kupna, to nie zmienisz w niej tytułu lub kategorii.

**Comment by AnimalDEV** [comment]
Czyli jeśli muszę zwiększyć cenę o ponad 100% to logika `wyłącz ofertę -> zaktualizuj cenę -> włącz ofertę` nie zadziała? Teraz działa i pytanie czy powinno. Jeśli nie powinno to czy jest sposób oprócz robienia nowej oferty na zwiększenie ceny o ponad 100%?

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuję - w przypadku zmiany ceny limit 100% dotyczy tylko aktywnych ofert, tak więc możesz zmienić cenę o dowolną kwotę w ofercie nieaktywnej. 

> Czy te zasady obowiązują na sandboxie, bo jak kupię przedmioty z mojej oferty i potem zmieniam tytuł to nie ma błędu i został poprawnie zmieniony.

Zmieniliśmy już zachowanie dla zmiany tytułu dla sandboxie.

**Comment by AnimalDEV** [comment]
Dziękuje za pomoc.
