### ISSUE TITLE
Using API vs existing products

### ISSUE THREAD

**Issue by normelma** [allegro/allegro-api#3233]
Hello,

We currently use the marketplace of Allegro to sell some of our products.
For the moment, the products are manually filled through Allegro's backoffice.

We want to move to a more automatic way of feeding product & offer information. And rely on [Lengow](https://www.lengow.com/) to do this job. They are actually plugged to your API.

We would like to know what could be the impacts of such action on our current products in Allegro.pl?
Are there some best practices that we should know before doing this?

Thanks in advance for your help.

Regards

**Comment by PrzemyslawLukanowski** [comment]
Using API will not affect your current products. Their data will remain the same and you will still be able to update them, etc.

There are no best practices, it depends on your needs, so don't hesitate to ask further questions, if you have any doubts.

You can also check our [portal](https://developer.allegro.pl/en/about/), where you can find information about:
- [listing offers](https://developer.allegro.pl/en/sale/),
- [simple way to list an offer assigned to a product](https://developer.allegro.pl/en/product_offers/),
- [managing orders](https://developer.allegro.pl/en/orders/), 
- [processing list of offers](https://developer.allegro.pl/en/my_offers/).

**Comment by normelma** [comment]
Thank you for your quick reply.
To be sure to well understand what going on behind the scene. Below the two main use cases identified so far:

- _**Use case 1**_: My product **does not exist** in Allegro system
As per my understanding there should be no problem.

- **_Use case 2_**: My product **already** exist in Allegro system
The data sent through the API will override the data previously provided manually.

Am I right ?

_**Subsidiary question**_:
In that case, how do you state that a product already exist in Allegro?  Via its product ID or its EAN?

Thanks & Regards

**Comment by PrzemyslawLukanowski** [comment]
Yes, those are two main cases:

- if your product doesn't exist in our database, you can create one and assign it to your offer;
- if your product exist in our database, we don't overriding data. You can assign this product to your offer, all you need to know is its ID or EAN. For example - if you want to list an offer of a product, which is "Harry Potter and the Philosopher's Stone Slytherin Edition J.K. Rowling", you can check its ID via [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts)?phrase=Harry Potter... and in the next step assign this product to your offer. Or - by our new resource [POST /sale/product-offers](https://github.com/allegro/allegro-api/issues/3214) you don't even need to check its ID, all you need to know is its EAN.

By product I mean products, which you can assign to your offers, not your current offers - those will still remain the same, if don't make any changes.

We recognize that product is already in our database via EAN and parameters that identifies product.

**Comment by normelma** [comment]
Sorry to insist, but we want to be sure of what we are doing before moving forward.
So to sum up our situation.

* Regarding the first use case, it’s ok. 

We will start from scratch providing the product with its data(ID, EAN, Name, Description, …) and the associated offer(Price,Stock, Delivery).

* Regarding the second use case:

Let say we have provided for product with EAN `2222222` the bellow data manually:
>
>__Product__:
>  - ID: 123456, 
>  - EAN: 2222222, 
>  - Name: The **manual** name, 
>  - Description: The **manual** description
>
>__Offer__:
>  - Price: 150 zloty
>  - Stock: 9


Now let say we start the _**automatic process**_ by providing the bellow information for the above product:
>__Product__:
>  - ID: 123456
>  - EAN: 2222222
>  - Name: The **automatic** name 
>  - Description: The **automatic** description
>
>__Offer__:
>  - Price: 300 zloty
>  - Stock: 5

**Expected result:**
If I understand well, in Allegro we will have the following status regarding the product data and its associated offer:

>__Product__:
>  - ID: 123456
>  - EAN: 2222222
>  - Name: The **manual** name
>  - Description: The **manual** description
>  
>  __Offer__:
>  - Price: **300 zloty**
>  - Stock: **5**

Am I right?
Can you please confirm this or not? It's very important for us.

**Comment by PrzemyslawLukanowski** [comment]
Please remember that there are two approaches to assign product to an offer:
- our new simple way via POST /sale/product-offers,
- our 'classic' approach, you can find more information about it in [our guide](https://developer.allegro.pl/en/productization/).

How exactly it will work in your software depends on solutions from your integration.

But if it comes to your example and simpe way to listing new offer with a product:
1) If the product exist in our database, you won't be able to change it's data. You can only provide offer data such as:
- offer parameters,
- offer description,
- price,
- stock,
- images of your specific copy of a product,
2) So if you start automatic process of assigning, all product data you will need to provide to assign offer to a product, will be its ID/EAN. Name of the product will be taken from our database, same it will be with description (but you can add your own in your offer).
3) Regarding to your example - if this product with EAN 2222222 exist in our database, you will need to provide only its EAN or ID to list an offer assigned to this product, e.g.

```
Product:

ID: 123456,

Offer:

Price: 150 zloty
Stock: 9
```

Expected result:

```
Product:

ID: 123456,
Name: taken from our database
Description: taken from our database (but you can add your own)

Offer:

Price: 150 zloty
Stock: 9
```
