### ISSUE TITLE
Problem z łączeniem aukcji w wielowariantowe

### ISSUE THREAD

**Issue by adamus994** [allegro/allegro-api#3234]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Dzień dobry,
próbuję połączyć dwie aukcje w ofertę wielowariantową metodą:
https://developer.allegro.pl/documentation/#operation/createVariantSet

Na wejściu podaje takie dane:
stdClass Object
(
    [offers] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 8950672949
                    [colorPattern] => ML10-b
                )
            [1] => stdClass Object
                (
                    [id] => 8786378934
                    [colorPattern] => ML10-b
                )
        )
    [name] => |API| ML10-
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => color/pattern
                )
            [1] => stdClass Object
                (
                    [id] => 26388
                )
        )
)

W odpowiedzi dostaję:
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => VALIDATION_ERROR
                    [message] => Cannot create variant set.
                    [details] => 
                    [path] => 
                    [userMessage] => Cannot create variant set.
                )
        )
)

Mogę poprosić o podpowiedź, dlaczego tych aukcji nie da się połączyć w wielowariantową? 
Odpowiedź, którą otrzymuję od api nie za bardzo tłumaczy co jest nie tak.
Obydwie aukcje to buty w dwóch różnych rozmiarach. Wszystkie atrybuty oprócz rozmiaru i długości wkładki są identyczne.

Z góry dziękuję,
Adam

**Comment by PrzemyslawLukanowski** [comment]
Jest to znany nam problem, w przyszłości powinien występować coraz rzadziej. W rozwiązaniu pomoże zakończenie i wznowienie oferty 8950672949.

**Comment by adamus994** [comment]
Ok rozumiem. Problem w tym, że takich aukcji mamy już ponad tysiąc. Czy istnieje może jakiś zakres dat wystawienia aukcji, w którym będzie występował ten problem?
Wiedziałbym z góry, które aukcje należy zakończyć i wznowić.

**Comment by PrzemyslawLukanowski** [comment]
Problem może dotyczyć ofert, które zostały wystawione do 11-03-2020.
