### ISSUE TITLE
inPost etykiety

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#3235]
Dzień dobry,
czy istnieje możliwość żeby w REST Api dodać możliwość pobrania etykiety inpost?
Wg uzyskanych informacji nie ma możliwości drukowania etykiet przez API inpost dla przesyłek przygotowanych przez allegro.

**Comment by PrzemyslawLukanowski** [comment]
W naszym API nie planujemy udostępniać takiej możliwości. Co do API InPost udało mi się znaleźć [taką informację ](https://docs.inpost24.com/pages/viewpage.action?pageId=12091525), jednak wszelkie wątpliwości powinny być wyjaśnione ze wsparciem InPostu.

**Comment by BartekWroclaw** [comment]
Rozumiem. Niestety  nie ma możliwości obecnie drukowania etykiet przez api inpost przesyłek utworzonych przez allegro. Ani przez wskazany zasób ani inne zasoby.

**Comment by PrzemyslawLukanowski** [comment]
Zwróć uwagę jeszcze na tę [informację](https://docs.inpost24.com/display/PL/%5B1.6.0%5D+API+Pobieranie+wielu+etykiet) z dokumentacji InPostu. Informacje tam zawarte świadczą o tym, że da się pobierać etykiety przygotowane przez Allegro.

**Comment by BartekWroclaw** [comment]
A jednak się nie da dla paczek utworzonych przez allegro. Informacje potwierdzone z inpost.
Może się da w przypadku gdy samemu się utworzy przesyłkę allegro, ale to nie ten przypadek.
