### ISSUE TITLE
Problem z wystawieniem oferty

### ISSUE THREAD

**Issue by sinfulsaint07** [allegro/allegro-api#3236]
Witam,
Przy próbie wystawienia oferty poprzez REST API i pomocy tego kodu: 
`<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.allegro.pl.allegrosandbox.pl/sale/offers",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS =>"{\"name\": \"nazwa oferty\"}",
  CURLOPT_HTTPHEADER => array(
    "Accept: application/vnd.allegro.public.v1+json",
    "Content-Type: application/vnd.allegro.public.v1+json",
    "Authorization: Bearer *Token z sandboxa*",
    "Cookie: _cmuid=3xq61y7f-hszw-5r9j-ksja-u3m7x0ufyxj7; cartUserId=3xq61y7f-hszw-5r9j-ksja-u3m7x0ufyxj7; gdpr_permission_given=0"
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
`
dostaję jako odpowiedź:

`{
    "errors": [
        {
            "code": "UserRepresentativeException",
            "message": "Empty user_name claim",
            "details": null,
            "path": null,
            "userMessage": "There was an error while trying to get related account's resources."
        }
    ]
}`
Czy wymagana jest aktywacja konta do wystawiania ofert?
Moje konto na sandboxie to Client:44292276

**Comment by PrzemyslawLukanowski** [comment]
Właśnie aktywowałem Twoje konto. Dodatkowo upewnij się, że **nie korzystasz** z autoryzacji typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. W [naszej dokumentacji ](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).
