### ISSUE TITLE
offerts limits 0-100 for category 

### ISSUE THREAD

**Issue by Sergiutirziu** [allegro/allegro-api#3237]
Hello, 

I’ve created a website , dedicated to car parts and accessories using the API REST application on www.allegro.pl 

 I’ve encountered a problem while trying to synchronize the offers and have seen that there is a limit of item availability from 0 to 100 per each category.  How could this limit be exceeded?  

Looking forward to your support and thanking you in advance

I wish you a good day.

**Comment by PrzemyslawLukanowski** [comment]
Hello,

For [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) current limit is 60. You can use parameter 'offset' to retrieve next results.
