### ISSUE TITLE
Dokumentacja RESTAPI

### ISSUE THREAD

**Issue by SoftSolid** [allegro/allegro-api#3238]
Dlaczego wpisując w wyszukiwarce w dokumentacji https://developer.allegro.pl/documentation/
"sale/offers" (szukam GET sale/offers) nie dostaję sensownego wyniku ?
Po co jest ta wyszukiwarka skoro nie szuka po sensownych kryteriach ?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, będziemy go analizować.
