### ISSUE TITLE
Automatyczna zmiana statusu zamówienia na SENT

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3239]
Witam,

Czy status zamówienia zmienia się automatycznie po Waszej stronie na SENT lub READY_FOR_SHIPMENT w przypadku kiedy wyślemy do Was numer listu przewozowego przy pomocy metody: https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST ? Czy jakoś monitorujecie status po Waszej stronie i zmieniacie automatycznie z READY_FOR_SHIPMENT na SENT ?

**Comment by PrzemyslawLukanowski** [comment]
Status realizacji zamówienia automatycznie zmieniamy na SENT po dodaniu numeru przesyłki, jeśli sprzedawca ma włączony abonament i w zakładce Zamówienia, po kliknięciu 'Ustawienia', wybrał odpowiednią opcję:

![Screenshot_30](https://user-images.githubusercontent.com/51473661/82427530-86252600-9a89-11ea-9794-1bed196d236c.png)
