### ISSUE TITLE
Archiwum dokumentacji WebAPI

### ISSUE THREAD

**Issue by p0wertiger** [allegro/allegro-api#3241]
Czy jest gdzieś archiwum dokumentacji WebAPI? W szczególności metod już usuniętych, jak na przykład doGetMyPayoutsDetails (https://allegro.pl/webapi/documentation.php/show/id,87). Przepisałem podstawową funkcjonalność payoutów na PaymentHistory, ale chcę się upewnić, czy poprawnie to wszystko liczę. 

Konkretnie chodzi o zwracane z WebAPI parametry wyjściowe refundTo i refundFrom, co się składało na te tablice i jak to się ma do wartości z Rest API?

**Comment by PrzemyslawLukanowski** [comment]
Archiwum nie jest już publicznie dostępne, poniżej znajdziesz informacje, co składało się na te tablice. Obok wymieniłem odpowiednik z REST API:

- transactionId - Identyfikator formularza płatności - payment.id 
- refundId - Identyfikator zwrotu wpłaty - refunds.id w odpowiedzi dla [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments)
- refundReason  - Powód zwrotu płatności - refunds.reason w odpowiedzi dla [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments)
- itemId - Numer oferty, której dotyczy zwrot - lineItems.id (identyfikator aktu zakupowego) w odpowiedzi dla [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments)
- toUserId - Identyfikator Użytkownika, od /do którego został wysłany zwrot - participant.id
- amount - Kwota zwrotu - value.amount
- paidDate -Data dokonania zwrotu - occurredAt

**Comment by p0wertiger** [comment]
Dziękuję
