### ISSUE TITLE
Dodawanie zdjęć poprzez REST API

### ISSUE THREAD

**Issue by GrzegorzLewinski** [allegro/allegro-api#3242]
Występuje problem: 
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym

Witam.
Podczas dodawanie bądź aktualizacji produktu na Allegro poprzez REST API w momęcie wysyłania zdjęć do serwisu otrzymuję błąd : " {"errors":[{"code":"RequestNotReadable","message":"Unable to parse request body.","details":null,"path":null,"userMessage":"Invalid upload image request. Please contact the author of the application."}]} " . 
Co dziwniejsze dla produktu dla którego występuje ten błąd zdjęcia załączone są poprawnie.
ID aukcji dla których otrzymałem błąd a grafiki zostały załączone poprawnie: 9289990131, 9289989709.
Za którąś z kolei aktualizacją produktu błąd nie występuje.

**Comment by PrzemyslawLukanowski** [comment]
Błąd tego typu możesz otrzymać, kiedy obrazek wysyłasz w postaci binarnej, ale w nagłówkach dla Content-Type masz zdefiniowaną wartość inną niż:
- image/jpeg
- image/png

Upewnij się, że przesyłasz prawidłowe wartości. Jeśli były one określone poprawnie, a błąd mimo to wystąpił, prześlij nam proszę przykładowe trace-id.

**Comment by GrzegorzLewinski** [comment]
Zdjęcie dodawane są w postaci linku, wysyłane nagłówki są zgodne z dokumentacją.
Przykład : ID produktu 9292639606
Trace id dla wysyłanych zapytań w celu dodawania grafiki: 
9986e5139fec6227
8efd2d5297ea97c8
ecf7f47c989941e9
f0b4f9fd1b4cc9a1
c4dc78138cd4f7c1
c73178a545e95e69
5250138dc1e5ffb3
a1ea2d6ebd4028ab

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu, który zajmie się analizą błędu. Wrócę z odpowiedzią, gdy otrzymam informację, co było przyczyną.

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach widzimy, że w requestach wysyłasz {"url": null} lub parametr "url" w ogóle nie jest załączony w body. Wygląda to na problem po stronie integracji, prośba o weryfikację po swojej stronie.
