### ISSUE TITLE
aktywacja sprzedaży allegro.sandbox

### ISSUE THREAD

**Issue by michalleszcz** [allegro/allegro-api#3244]
Witam,
wczoraj utworzyłem konto na allegro sandbox oraz potwierdziłem wykonanie przelewu (uproszczona formatka) potrzebne do aktywacji sprzedaży. Jak długo trzeba czekać na aktywację?
login michalleszcz

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktywowałem Twoje konto. Ponieważ wybrałeś konto Firma, w celu zakończenia aktywacji wyślij dwa dowolne pliki przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by michalleszcz** [comment]
Dzięki za tak szybką reakcję, nie spodziewałem się :)

Dodałem pliki do sekcji Skan odpisu z KRS * - tylko tam znalazłem możliwość dodawania plików. 
Wysłałem do weryfikacji. 
W dalszym ciągu mam wpis w zakładce Aktywacja konta -> Status -> Nieaktywne - trwa weryfikacja Twoich danych.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku Sandboxa ten status może nie być jeszcze zaktualizowany, jednak po naszej stronie konto jest już w pełni aktywnie. Powinieneś móc wykonywać wszystkie dostępne operację.

**Comment by michalleszcz** [comment]
Sprawdziłem i rzeczywiście mogę już wystawiać produkty. 
Dzięki!
