### ISSUE TITLE
/payments/payment-id-mappings - zwraca response code 404 zamiast 200

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#3245]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Wywołanie /payments/payment-id-mappings?paymentId={ID PLATNOSCI} zwraca response code 404 zamiast 200

Id transakcji na podstawie id platności jest nam potrzebny do stworzenia paczki w Inpost, przez wysłanie do Inpost id transakcji w Allegro.

Cały mechanizm dotychczas dobrze działał, kod programu po naszej stronie nie był zmieniany, id płatności jest prawidłowy - zresztą dotyczy to wszystkich kilkudziesięciu płatności z dzisiaj, a nie tylko jednej lub wybranych.

Wygląda to na błąd po stronie allegro API

**Comment by tztztztz** [comment]
Przykładowy id płatności:

1b8c6d91-9b23-11ea-825b-433e31ea2a28

**Comment by PrzemyslawLukanowski** [comment]
Usunęliśmy ten zasób zgodnie z naszą [wcześniejszą zapowiedzią](https://github.com/allegro/allegro-api/issues/3134) - w wątku znajdziesz również rozwiązanie tego problemu,

**Comment by tztztztz** [comment]
Działa, dzieki za info.
