### ISSUE TITLE
Problem z mapowaniem payment-id-mappings na produkcji

### ISSUE THREAD

**Issue by celitoasmus** [allegro/allegro-api#3246]
Występuje problem: Pobraniem danych z zasobu payment-id-mappings?paymentId=
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
request: payment-id-mappings?paymentId=3561be92-9b3d-11ea-afa6-ef4999d6df18

response: 
{'errors': [{'code': 'NotFoundException', 'message': 'Not found', 'details': None, 'path': None, 'userMessage': 'Funkcja niedostępna. Skontaktuj się z autorem aplikacji.'}]}

Nie moge pobrac starego 'PayU' dla w/w 3561be92-9b3d-11ea-afa6-ef4999d6df18. Uzywam application/vnd.allegro.public.v1+json

**Comment by PrzemyslawLukanowski** [comment]
Usunęliśmy ten zasób zgodnie z [wcześniejszą zapowiedzią](https://github.com/allegro/allegro-api/issues/3134).  Podobne zgłoszenie otrzymaliśmy już w #3245.
