### ISSUE TITLE
Aktywacja sandbox

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#3247]
Prosił bym o aktywację konta S3kawek

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktywowałem Twoje konto. Ponieważ wybrałeś konto Firma, w celu zakończenia aktywacji wyślij dwa dowolne pliki przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by PatrykPorabik** [comment]
@PrzemyslawLukanowski jeśli można prosić o aktywację, to też jestem chętny :) - konto grandnode

**Comment by PrzemyslawLukanowski** [comment]
@PatrykPorabik Wstępnie aktywowałem Twoje konto. Podobnie jak w powyższym przypadku - ponieważ wybrałeś konto Firma, w celu zakończenia aktywacji wyślij dwa dowolne pliki przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by vlclu** [comment]
zobaczysz moje konto?     
viciu
dzięki

**Comment by PrzemyslawLukanowski** [comment]
@vi4m Aktywowałem Twoje konto.

**Comment by thehardway15** [comment]
@PrzemyslawLukanowski również proszę o aktywację kont
devunisosandall
devsandallthd

Dzięki

**Comment by PrzemyslawLukanowski** [comment]
@thehardway15 Aktywowałem Twoje konta. Dla konta devsandallthd prześlij jeszcze dwa dowolne pliki przez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php), aby dokończyć aktywację.
