### ISSUE TITLE
Nie działa /payments/payment-id-mappings

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#3248]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od wczoraj dla wszystkich zamówień ta metoda nie zwraca wyniku. Przykładowe id
7f3ba811-9b4b-11ea-a38f-c1678100a372
f9ff6be1-9b4b-11ea-879e-87c7bd0b838c
Co jest powodem?

**Comment by copyact** [comment]
Gdy otwieram w przeglądarce ten adres, to mam:
{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [zapowiedzą z 27 kwietnia](https://github.com/allegro/allegro-api/issues/3134) usunęliśmy ten zasób. W wątku znajdziesz więcej informacji.
