### ISSUE TITLE
Login sprzedawcy

### ISSUE THREAD

**Issue by wussup** [allegro/allegro-api#3249]
Witam,

czy jest możliwość dostać login sprzedawcy po jego seller.id? W wyniku wyszukiwania ofert (/offers/listing) w obiekcie seller są zwracane tylko id, superSeller i company? Czy jest możliwość dostać jeszcze przynajmniej jego login?

PS: Dobrze byłoby też mieć tutaj userListingUrl oraz positiveFeedbackPercent

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie ma takiej możliwości. Podobne zgłoszenia pojawiły już się w innych wątkach, dlatego również Twoje zapisuję do naszej listy sugestii dot. rozwoju API.

**Comment by wussup** [comment]
Ok, w takim razie będę czekał póki to się zrobi
