### ISSUE TITLE
"sygnatura" w WebAPI

### ISSUE THREAD

**Issue by kamil-em** [allegro/allegro-api#325]
Witam,
Od twórcy zewnętrznego oprogramowania do obsługi sprzedaży dowiedziałem się, że API nie obsługuje pola "sygnatura". Czy jest planowane wprowadzenie obsługi tego pola? Ułatwiłoby to zarządzanie sprzedażą.

**Comment by MarcinLuczak** [comment]
@kamil-em Doprecyzuj proszę pytanie, bo obecnie nie wiem co to za pole i do czego miało by służyć.

**Comment by kamil-em** [comment]
![przechwytywanie](https://user-images.githubusercontent.com/40472247/41764449-6ff09cc4-7601-11e8-8c44-e4a9114f2114.png)

Chodzi o zaznaczone pole. MS potrafi je ściągać z ofert, a z tego co się dowiedziałem zewnętrzne aplikacje już nie, ze względu na ograniczenia API.

**Comment by MarcinLuczak** [comment]
@kamil-em dziękuję za wyjaśnienie. Nie planujemy dodania tego pola do naszych API.
