### ISSUE TITLE
Błąd "Oferta nie istnieje"

### ISSUE THREAD

**Issue by malbrandt** [allegro/allegro-api#3250]
Mamy u siebie funkcję importu zamówień. Do każdego można było przejść za pomocą linku, np.:
`http://allegro.pl/oferta/{lineItemId}`.
Od jakiegoś czasu link ten przestał działać - wyświetla się błąd "Oferta nie istnieje". Zamiast tego działają linki ze slugiem, np.
```
https://allegro.pl/oferta/apple-iphone-11-64gb-black-nowy-pl-8505785187
```

1) To jakiś błąd, czy ta funkcja została wycofana? 
2) Jak możemy teraz budować linki do ofert (nie znalazłem żadnej informacji w dokumentacji na ten temat)?

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem - URL na kształt allegro.pl/oferta/numer_oferty funkcjonuje prawidłowo. Na podstawie przykładu: [allegro.pl/oferta/8505785187](allegro.pl/oferta/8505785187)

**Comment by malbrandt** [comment]
Ok, już widzę swój błąd, używałem line-items.id zamiast offer.id. 
Dziękuję za szybką odpowiedź i pozdrawiam.
