### ISSUE TITLE
Problem ze wznowieniem aukcji i brakiem komunikatu

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#3251]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie możemy wznowić niektórych aukcji na sandboxie bo wywala błąd:

```
2020-05-25T14:04:30+02:00 INFO (6): 
-------------------------------------
REQUEST:

GET /sale/offer-publication-commands/ea5c5440-f779-496c-9fd9-f7acdf38daa0/tasks HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.0.0
Authorization: Bearer (...ciach...)
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

-------------------------------------
RESPONSE:

HTTP/1.1 200 OK
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Server: envoy
Pragma: no-cache
X-frame-options: DENY
Trace-id: 48b5629084badd61
Date: Mon, 25 May 2020 12:04:30 GMT
X-content-type-options: nosniff
Content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-length: 19044
X-envoy-upstream-service-time: 97
Connection: close

{"tasks":[{"offer":{"id":"6207047538"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-25T12:03:48.068Z","finishedAt":"2020-05-25T12:04:16.198Z","field":"publication","errors":[{"code":"IncorrectParametersException","message":"","details":null,"path":null,"userMessage":""}]} ...
```

Domyślam się że dotyczy to aukcji które zostały wystawione przed okresem w którym włączyliście wymagalność dla niektórych parametrów np. Kod produktu, Kod producenta itd, jednak pole userMessage nie powinno być przez to puste. Dodam jeszcze tyle, że zawartość tego pola wyświetlamy klientowi i on sam nie jest świadom w czym popełnił błąd

**Comment by MaciejFrackowiak** [comment]
Spojrzałem w logi i dla podanego trace-id widzę operację END, a nie ponowną aktywację oferty. Oferta 6207047538 jest już aktywna na Sandbox.

**Comment by kormichu** [comment]
A przepraszam, racja, wrzucałem tam END. W każdym razie komunikat dla użytkownika powinien brzmieć inaczej albo jakikolwiek żeby był

**Comment by MaciejFrackowiak** [comment]
Oczywiście - tu pełna zgoda - przekazuję temat do właściwego zespołu.
