### ISSUE TITLE
[Sandbox] GET sale/offers wszystkie oferty stan 0 dla jednego konta

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3252]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Na serwerze testowym przy pobieraniu listy ofert aktywnych stock.available jest zawsze 0.

`
GET sale/offers?limit=500&offset=0&publication.status=ACTIVE&sellingMode.format=BUY_NOW
trace-id:c1bbc65d1a4aa628`
`
offers[].stock.available: 10
offers[].publication.status: ACTIVE
`

Sprawa dotyczy jednego konta testowego (id konta 43948417).

Na pierwszej aukcji jest sztuk 10, przy pobraniu szczegółów oferty otrzymuję prawidłowy wynik

`GET sale/offers/{id}?
trace-id:34de5d18cc286ec9`

`
stock.available: 10
`

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem dla tego konta i przekazuję zgłoszenie do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Problem nie powinien już występować.
