### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by michalzimniak** [allegro/allegro-api#3253]
Hej,

Prosze o aktywowanie konta na sandboxie. Nazwa konta: malanet

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktyowałem Twoje konto. Aby dokończyć rejestrację, wyślij dwa dowolne pliki przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by michalzimniak** [comment]
Hej, Status konta po wyslaniu plikow: Nieaktywne, trwa weryfikacja danych.

**Comment by PrzemyslawLukanowski** [comment]
Proszę się tym nie sugerować, na Sandboxie może jeszcze występować rozbieżność. Wszystkie operacje powinny już być dostępne.

**Comment by michalzimniak** [comment]
OK dzieki.
