### ISSUE TITLE
[Sandbox] Brak możliwości wystawienia nowej oferty

### ISSUE THREAD

**Issue by yami-five** [allegro/allegro-api#3254]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Na środowisku testowym nie można wystawić nowe aukcji. Guzik Dodaj Nową w Moje oferty zawiera link https://staging-lokalnie.allegrogroup.com/oferty/wystaw, a Wystaw Przedmiot na liście w prawym górnym rogu zawiera link https://allegrolokalnie.pl/oferty/wystaw/kup-teraz.

**Comment by PrzemyslawLukanowski** [comment]
Wiemy o tym problemie, na tę chwilę skorzystaj proszę z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.
