### ISSUE TITLE
[REST API] - Pytania od kupujących - /moje-allegro/moje-konto/centrum-wiadomosci/wiadomosci

### ISSUE THREAD

**Issue by pliszka2** [allegro/allegro-api#3255]
Dostęp do danych z podstrony: "/moje-allegro/moje-konto/centrum-wiadomosci/wiadomosci" poprzez REST API? 
Czy jest możliwy? Czy planujecie?

**Comment by MaciejFrackowiak** [comment]
Tak, obsługa Centrum wiadomości znajduje się na liście sugestii dot. rozwoju REST API. Oczywiście w przypadku wdrożenia zasobów zamieścimy osobny news.

**Comment by pliszka2** [comment]
Dzięki za informację :) Zamykam :)
