### ISSUE TITLE
Klient opłacił zamówienie, lecz nadal jest w trakcie płatnośc rozpoczęta.

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#3256]
https://allegro.pl/moje-allegro/sprzedaz/zamowienia/5064e343-8e48-11ea-9995-b337e7e89177

Klient opłacił zamówienie (dostaliśmy od państwa automatyczny @ z tą informacją).

Niestety w panelu dalej jest jako "PŁATNOŚĆ ROZPOCZĘTA".

Ale jak kliknę na płatność: https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji#!/?query=50b414b5-8e48-11ea-9b7d-8d3fd1711d23&dateFrom=2020-05-04&dateTo=2020-05-04 - jest opłacone. 

Z naszej strony zamówienie jest już anulowane. Potrzebuje tylko mieć możliwość wykonania zwrotu pieniędzy.

**Comment by MaciejFrackowiak** [comment]
Problem potwierdzam - przekazałem już zgłoszenie do właściwego zespołu.

**Comment by MaciejFrackowiak** [comment]
@pgasidlo Status płatności już jest prawidłowy - przepraszam za niedogodności.
