### ISSUE TITLE
SellerId - REST API

### ISSUE THREAD

**Issue by malytworca** [allegro/allegro-api#326]
Po co jest REST API i po co logowanie, skoro SellerId nie da się pobrać a przynajmniej nigdzie tego znaleźć nie mogę. Po to się ktoś loguje, żeby potem trzeba było ręcznie wklepać ten id? To ma ośmieszać aplikacje? Tylko proszę nie pisać o WebAPI, bo to przecież jest odradzane i REST API miało być "lepsze", a tu brakuje podstaw. 

Temat sellerid pojawia się już nie pierwszy raz i nikomu do głowy nadal nie przyszło żeby ten prymitywny element dodać do powrotnych informacji podczas logowania. To jest normalnie jakiś żart. Gorszym żartem byłoby chyba, gdyby ktoś zapomniał o logowaniu, ale z drugiej strony po co się logować, jak dane użytkownika nie wiadomo jak uzyskać, bo nikt nie napisał tego w dokumentacji, ani w REST API.

**Comment by MarcinLuczak** [comment]
@malytworca wystarczy, że zdekodujesz access token. Skorzystaj z https://jwt.io/ - gdy zdekodujesz token, w polu user_name będziesz miał swój userId. Jeżeli w danym kontekście jesteś sprzedawcą, to znaczy że to także Twój sellerId.

> Tylko proszę nie pisać o WebAPI, bo to przecież jest odradzane i REST API miało być "lepsze", a tu brakuje podstaw.

WebAPI działa od dawna, a REST API rozwijamy dopiero od pewnego czasu, więc jeszcze trochę potrwa aż udostępni wszystkie potrzebne zasoby w REST API.
