### ISSUE TITLE
Anulowana płatność, zamówienie pozostaje w statusie READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by bartolomeon** [allegro/allegro-api#3260]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Formularz zakupowy:
https://api.allegro.pl/order/checkout-forms/729e8c94-92e9-11ea-8641-11d593cf38d8

zwraca zamówienie, które ma status READY_FOR_PROCESSING oraz informacje o dokonanej płatności, natomiast w GUI  widzimy, że płatność ma status 'anulowana' a zamówienie status NOWE.

Zamówienie to zostało pobrane przez nasz system tego samego dnia (10.05.2020), a 'fulfilment' status zmieniony na PROCESSING i później na SENT.

Coś tu chyba nie gra? Nawet zakładając, że mieliśmy niefart i klient się wstrzelił z anulacją w kilka sekund między pobraniem a ustawieniem przez nas PROCESSING - dlaczego to zamówienie nie ma statusu 'CANCELLED'? Do dnia dzisiejszego?

**Comment by MaciejFrackowiak** [comment]
Kupujący dokonał dwóch oddzielnych zakupów w ofercie xxxxx51861:

1) zamówienie wskazane przez Ciebie - 729e8c94-92e9-11ea-8641-11d593cf38d8 jest opłacone i taki status widnieje na WWW;

2) zamówienie 0c808a42-92e8-11ea-9f3e-6d79ce448772 - to ono zostało anulowane i przy nim widnieje płatność anulowana.

**Comment by bartolomeon** [comment]
OK, istotnie, tak jest - tylko dlaczego to anulowane zamówienie wygląda w GUI tak:
![Zrzut ekranu z 2020-05-29 11-48-08](https://user-images.githubusercontent.com/154424/83246558-9a140a80-a1a2-11ea-8828-6d4fe4933547.png)

i faktycznie, jeżeli pobrać je przez API:
```
  "payment": {
    "id": "0cc00440-92e8-11ea-85e7-7f2373d99883",
    "type": "ONLINE",
    "provider": "PAYU",
    "finishedAt": "2020-05-10T18:05:15.430Z",
    "paidAmount": null
  },
  "status": "CANCELLED",
  "fulfillment": {
    "status": "NEW",
    "shipmentSummary": {
      "lineItemsSent": "NONE"
    }
  },
```

te statusy się nie zgadzają (CANCELLED w API vs 'NOWE' w GUI), co powoduje konfuzję u sprzedającego - to chyba jest błąd?

**Comment by bartolomeon** [comment]
> Kupujący dokonał dwóch oddzielnych zakupów w ofercie xxxxx51861:
> 
>     1. zamówienie wskazane przez Ciebie - 729e8c94-92e9-11ea-8641-11d593cf38d8 jest opłacone i taki status widnieje na WWW;

Faktycznie, to zamówienie zostało pobrane przez nas system.
Problem w tym, że ono nie jest w ogóle widoczne na WWW!
Szukając z użyciem id 'checkoutForm' czy nazwy klienta, czy  oferty - tego zamówienia nie widać:
![Zrzut ekranu z 2020-05-29 12-12-01](https://user-images.githubusercontent.com/154424/83248728-ce3cfa80-a1a5-11ea-8fd3-bc5e5676c75b.png)

 
>     2. zamówienie 0c808a42-92e8-11ea-9f3e-6d79ce448772 - to ono zostało anulowane i przy nim widnieje płatność anulowana.

Tak, to zamówienie jest widoczne na WWW, ale znowu - widać na nim status 'NOWE' a nie 'Anulowane' - dlaczego? (pobierając przez API na szczęście ma CANCELLED).

![Zrzut ekranu z 2020-05-29 11-48-08](https://user-images.githubusercontent.com/154424/83248821-f0367d00-a1a5-11ea-9db9-6f9f55b489c4.png)

**Comment by bartolomeon** [comment]
Podsumowując - 2 problemy:
1. nie da się wyszukać na WWW zamówienia 729e8c94-92e9-11ea-8641-11d593cf38d8
2. zamówienie 0c808a42-92e8-11ea-9f3e-6d79ce448772 (wewn. status CANCELLED) na WWW widnieje jako 'NOWE'

**Comment by MaciejFrackowiak** [comment]
1. Jest dostępne, tylko wybierz filtr Wysłane - w [Ustawieniach zamówień](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) masz wybrane "Ukryj zamówienia ze statusem WYSŁANE";

2. W tym przypadku mylisz status zamówienia ze statusem realizacji zamówienia - zamówienie jest CANCELLED, natomiast stan jego realizacji to NEW (zwracany w polu fulfillment.status) - proszę spójrz do [naszego poradnika](https://developer.allegro.pl/orders/#zmiana-statusu-realizacji-zam%c3%b3wienia).

**Comment by bartolomeon** [comment]
Faktycznie, zgadza się - chociaż moim zdaniem to 'Ukryj zamówienia ze statusem WYSŁANE' powinno być na werzchu, w filtrze zamówień...

Czyli - status widoczny na WWW to jest fulfilment.status, ustawiany tylko przez sprzedającego.
Zamykam.
