### ISSUE TITLE
ERR_YOU_CANT_CHANGE_ITEM podczas wznowienia aukcji

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3261]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Zakończyłem kilka aukcji korzystając z zasobu PUT /sale/offer-publication-commands/{commandId}, wszystko przeszło poprawnie, po chwili chciałem wszystkie aukcje wznowić i tutaj pojawia się problem. Wysyłając ten sam request dopiero po 5-6 razie oferty stają się aktywne.

Request kończący aukcje:
`{"offerCriteria":[{"offers":[{"id":"7374177090"},{"id":"7374172495"},{"id":"7374176896"},{"id":"7374172328"},{"id":"8205144328"},{"id":"7374175186"},{"id":"8196177789"},{"id":"8196177657"},{"id":"8205144229"},{"id":"7374177234"},{"id":"7374174959"},{"id":"7374177363"},{"id":"8196178103"},{"id":"7374174781"},{"id":"8282231134"},{"id":"7374176732"},{"id":"8196178019"},{"id":"8196178483"},{"id":"8196178431"},{"id":"7374175935"},{"id":"8196177956"},{"id":"8196178701"},{"id":"8196177877"},{"id":"7374175468"},{"id":"7374175777"},{"id":"8196178235"},{"id":"7374173599"},{"id":"7374173741"},{"id":"7374174586"},{"id":"7374173286"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END"}}`

Response: 
`{"id":"585bc684-5b69-4a7c-9a24-64b3e7430f95","taskCount":{"total":0,"success":0,"failed":0}}`

Poźniej gdy task został przetworzony 30/30 ok, chciałem wznowić oferty zasobem PUT /sale/offer-publication-commands/5aada2a4-4672-453f-9d60-16a2fc7ade29, 

Request:
`{"offerCriteria":[{"offers":[{"id":"7374177090"},{"id":"7374172495"},{"id":"7374176896"},{"id":"7374172328"},{"id":"8205144328"},{"id":"7374175186"},{"id":"8196177789"},{"id":"8196177657"},{"id":"8205144229"},{"id":"7374177234"},{"id":"7374174959"},{"id":"7374177363"},{"id":"8196178103"},{"id":"7374174781"},{"id":"8282231134"},{"id":"7374176732"},{"id":"8196178019"},{"id":"8196178483"},{"id":"8196178431"},{"id":"7374175935"},{"id":"8196177956"},{"id":"8196178701"},{"id":"8196177877"},{"id":"7374175468"},{"id":"7374175777"},{"id":"8196178235"},{"id":"7374173599"},{"id":"7374173741"},{"id":"7374174586"},{"id":"7374173286"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}`

Response: 
`{"id":"5aada2a4-4672-453f-9d60-16a2fc7ade29","taskCount":{"total":0,"success":0,"failed":0}}`

Jednak taski o wznowienie zwróciły same faile. Każdy task był wysyłany z tymi samymi danymi:
5aada2a4-4672-453f-9d60-16a2fc7ade29 - fail
cd17cdba-29f1-4eb7-8514-6c062d36ac60 - fail
0a55762d-ba2e-4868-b337-87c4259ca48e - fail
827aef5c-a458-4aff-bc42-531e5845bc09 - fail
c4873fb8-47fa-492e-89f7-bc23ba55fb27 - fail
11799d1b-1792-401b-9dfb-15b15822c1d9 - ok

Dopiero 6 raz wysłanie dokładnie tych samych danych zostało wykonane poprawnie.

Odpytując zasób GET /sale/offer-price-change-commands/5aada2a4-4672-453f-9d60-16a2fc7ade29/tasks dla każdego faila odpowiedź taka sama:
`{"tasks":[{"offer":{"id":"8196177956"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.754Z","finishedAt":"2020-05-28T13:42:17.947Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8196177657"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.764Z","finishedAt":"2020-05-28T13:42:17.923Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8196178701"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.773Z","finishedAt":"2020-05-28T13:42:17.911Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8196177877"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.781Z","finishedAt":"2020-05-28T13:42:17.939Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8282231134"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.789Z","finishedAt":"2020-05-28T13:42:17.945Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374173599"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.798Z","finishedAt":"2020-05-28T13:42:17.934Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8196178103"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.811Z","finishedAt":"2020-05-28T13:42:17.93Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374175777"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.819Z","finishedAt":"2020-05-28T13:42:17.903Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"8196178483"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.827Z","finishedAt":"2020-05-28T13:42:17.966Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374172328"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.836Z","finishedAt":"2020-05-28T13:42:17.938Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374175935"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.844Z","finishedAt":"2020-05-28T13:42:17.947Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374176896"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.852Z","finishedAt":"2020-05-28T13:42:18.189Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374173286"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.86Z","finishedAt":"2020-05-28T13:42:17.922Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374175186"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.868Z","finishedAt":"2020-05-28T13:42:17.898Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id":"7374175468"},"message":"Could not change offer publication status.","status":"FAIL","scheduledAt":"2020-05-28T13:42:16.877Z","finishedAt":"2020-05-28T13:42:17.97Z","field":"publication","errors":[{"code":"ERR_YOU_CANT_CHANGE_ITEM","message":"ERR_YOU_CANT_CHANGE_ITEM","details":null,"path":null,"userMessage":""}]},{"offer":{"id`

**Comment by MaciejFrackowiak** [comment]
Zasoby do operacji grupowych działają asynchronicznie - jeżeli jedna operacja nie zostanie zakończona, to kolejna z automatu skazana jest na niepowodzenie. W Twoim przypadku zadanie zakończenia ofert zostało przetworzone, jednak same oferty jeszcze nie odświeżyły swojego statusu. W międzyczasie wysłałeś kolejne requesty z ich aktywacją - pierwotne zadanie nie zostało jeszcze przetworzone i dlatego dostawałeś komunikaty błędów. Dopiero, gdy mechanizm ukończył zadanie numer 1 pozwolił na kolejną zmianę - co kluczowe całość operacji została wykonana w ciągu 6 minut.

**Comment by mkulig** [comment]
Dziękuję za wyjaśnienie. W jaki sposób można przez api sprawdzić czy dana oferta faktycznie została odświeżona skoro zasób GET /sale/offer-publication-commands/{commandId} zwraca 30/30 poprawnie wykonanych tasków zamknięcia ofert to trzeba jeszcze odczekać kilka minut, żeby je aktywować bo muszą zostać przetworzone na serwerach allegro, tak? można ten czas jakoś sprawdzić?

**Comment by MaciejFrackowiak** [comment]
Na WWW przy wystawianiu / edycji oferty widnieje komunikat, że operacja zostanie wykonana w ciągu 60 minut. Taki zakres czasu pozwala na poprawne przeprocesowanie zleceń. Nie mamy osobnego zasobu do sprawdzania tego czasu.
