### ISSUE TITLE
PUT /sale/offer-variants/

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3262]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, pobieram dane z serwerów allegro poprzez zasób GET /sale/offer-variants, poźniej zasobem GET /sale/offer-variants/{idVariant} dokładne dane o ofercie wielowariantowości i dokładnie te same dane odsyłam poprzez zasób PUT /sale/offer-variants/{varaintId} i dostaje w odpowiedzi ogóle nie pomocny opis błędu 'Cannot create variant set'. 

GET /sale/offer-variants?user.id=39858725&limit=50&offset=0&query=7355451337
`{"count":1,"offerVariants":[{"id":"048b9b46-84d4-4213-9247-67c257d6ec73","name":"KOSZULKA MĘSKA STRAŻ POŻARNA STRAŻAK WZORY"}]}`

GET /sale/offer-variants/048b9b46-84d4-4213-9247-67c257d6ec73
`{"id":"048b9b46-84d4-4213-9247-67c257d6ec73","offers":[{"id":"8282380297","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"9217857817","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282379386","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379427","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380056","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379770","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8882924714","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379564","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8200664032","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379634","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"7355451337","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380180","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380862","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282380092","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282380470","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282380262","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282379182","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282380373","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282380659","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282383379","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282380012","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379771","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282379240","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8713831775","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282379565","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8876951498","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282380532","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"7355451270","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379309","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"7355451282","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"}],"name":"KOSZULKA MĘSKA STRAŻ POŻARNA STRAŻAK WZORY","parameters":[{"id":"54"},{"id":"color/pattern"}]}`

PUT /sale/offer-variants/048b9b46-84d4-4213-9247-67c257d6ec73
`{"id":"048b9b46-84d4-4213-9247-67c257d6ec73","offers":[{"id":"8282380297","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"9217857817","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282379386","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379427","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380056","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379770","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8882924714","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282379564","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8200664032","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379634","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"7355451337","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380180","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282380862","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282380092","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8282380470","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282380262","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282379182","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282380373","colorPattern":"5c1ed804-bcc4-4434-8f67-f89cb506ba7a"},{"id":"8282380659","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282383379","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282380012","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379771","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"8282379240","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"8713831775","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8282379565","colorPattern":"aca48326-fe8b-4be9-974a-1da811ac423d"},{"id":"8876951498","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282380532","colorPattern":"3f245ac7-7a4d-4ad5-9f80-03cdcaf71578"},{"id":"7355451270","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"},{"id":"8282379309","colorPattern":"82557c30-04d1-4ed6-b2b8-88adb82f4a84"},{"id":"7355451282","colorPattern":"c5e2e79d-9e15-4100-afb7-b29c7a798274"}],"name":"KOSZULKA M\u0118SKA STRA\u017b PO\u017bARNA STRA\u017bAK WZORY","parameters":[{"id":"54"},{"id":"color\/pattern"}]}`

Response:
`{"errors":[{"code":"VALIDATION_ERROR","message":"Cannot create variant set.","details":null,"path":null,"userMessage":"Cannot create variant set."}]}`

Problem ten pojawia się w prawie w 2,5k zapytań. Znalazłem tutaj podobny problem: #3012 .

Próbowałem zakończyć i wznowić wszystkie aukcje, które są w danej wielowariantowości ale pomogło to tylko przy jednym zestawie ofert wielowariantowości, reszta nadal zwraca błąd 'Cannot create variant set.', poza tym przy aktywacji występuję problem #3261 .

Dlaczego dane, które są na serwerze i odsyłane przez api bez żadnej modyfikacji nie przechodzą poprawnej weryfikacji ?

**Comment by MaciejFrackowiak** [comment]
Opisany tutaj problem ma swoje źródło w wersji beta wielowariantowości, która była dostępna poprzednio - nie weryfikowaliśmy w niej duplikatów ofert. Mianowicie, przesyłane w requeście oferty podzielone są na zbiory - w tym konkretnym przypadku:

zbiór 1:
8282380092 M

zbiór 2:
**8858650367 M**
8882924714 L
8282379309 XL
8282380056 XXL
8282379386 S
8282379240 3XL

Zaznaczona oferta nie jest przesyłana w requeście, należy jednak do tego samego zbioru, co część z przesłanych ofert, dlatego następuje próba jej dołączenia do oferty wielowariantowej.
Taka próba zakończy się jednak niepowodzeniem, ponieważ jednocześnie w żądaniu jest przesyłana oferta z pierwszego zbioru, która jest duplikatem pogrubionej oferty (rozmiar M vs M).

Rozwiązaniem w tym konkretnym przypadku jest przesłanie oferty 8858650367 zamiast 8282380092 (lub nie przesłanie jej wcale, ponieważ i tak zostanie dołączona przez nas).

**Comment by mkulig** [comment]
Dziękuję za wyjaśnienie. W jaki sposób mogę sprawdzić takie duplikaty przez API i wyeliminować je, żeby poprawnie wysłać wielowariantowość na serwer allegro? Zależy mi, żeby móc samemu to rozwiązać, ponieważ tak jak pisałem wyżej, obecnie problem pojawia się w około 2,5k takich zapytań.

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną nie ma takiej możliwości, ponieważ nie wspieramy duplikatów ofert. Jedyne możliwe rozwiązanie poza niewystawianiem duplikatów to przesłanie po jednej ofercie z każdego koloru / wzoru - pozostałe będące razem z nimi w zbiorach zostaną dołączone do oferty wielowariantowej automatycznie. W takim przypadku trzeba jednak "dobrze ucelować" - wysłanie oferty 8858650367 lub 8882924714 spowoduje dociągnięcie pozostałych ofert z tego zbioru, natomiast przesłanie już 8282380092 już tak nie zadziała.
