### ISSUE TITLE
Środki i Historia operacji

### ISSUE THREAD

**Issue by gromusek** [allegro/allegro-api#3263]
Czy istnieje metoda analogiczna do zakładki allegro ,,Środki i historia operacji'' w której znajdują się wszystkie zdarzenia związane z płatnościami:

- wpłaty
- wypłaty
- zwroty
- nadpłaty

**Comment by MaciejFrackowiak** [comment]
Tak, mamy taki zasób - [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory).

**Comment by gromusek** [comment]
@MaciejFrackowiak w jaki sposób zwracani są klienci niezarejestrowani w polu _participant.login
_

**Comment by MaciejFrackowiak** [comment]
Login przyjmie postać "!g_xxxxxxx", gdzie xxxxxxx to user ID.
