### ISSUE TITLE
Problem z płatnościami w środowisku testowym

### ISSUE THREAD

**Issue by aosmialowski** [allegro/allegro-api#3265]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Żadna z płatności dla konta firmowego w sandboxie nie jest zakończona sukcesem. Czego może być to przyczyna?
Konto: SomeCompany2020

**Comment by asoio** [comment]
Mam ten sam problem.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem z płatnościami na Sandboxie. Przekazałem zgłoszenie do odpowiedniego zespołu.

**Comment by asoio** [comment]
U mnie już działa.

**Comment by PrzemyslawLukanowski** [comment]
@asoio Tak, problem na tę chwilę nie powinien występować.
