### ISSUE TITLE
Producent części w Klocki hamulcowe, tarcze i zestawy

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#3266]
Kiedy zmieniliście parametr z 127408 na 127415 w kategorii Klocki hamulcowe, Tarcze hamulcowe i Zestawy tarcz i klocków i czemu nigdzie nie ma o tym słowa?

Dodatkowo np BLUE PRINT w parametrze 127415 ma wartość 127417_251458, czy zamierzacie to porządkować czy tak zostawicie?

**Comment by PrzemyslawLukanowski** [comment]
Parametr zaktualizowaliśmy 18 lutego, informację o tym znajdziesz na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/czesci-samochodowe-18-lutego-ey5zZvldATr).

Wartości zostawimy w tym formacie - początek wartości parametru nie musi być zgodny identyfikatorem parametru.
