### ISSUE TITLE
Edycja oferty - zmiana tytułu

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3268]
Już kiedyś o to pytałem ale nie mogę coś znaleźć tego.
Czy można zmienić tytuł oferty jeśli ktoś na niej kupił ?

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [naszym artykułem ](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz) tytuł oferty możesz zmienić tylko, "jeśli nie doszło w niej jeszcze do sprzedaży (jeśli nie pojawiły się w niej żadne oferty kupna)."

**Comment by pietrach** [comment]
A później muszę zakończyć i wystawić nową ofertę ? Czy może wystarczy, że zakończę istniejącą, zmienię tytuł i ją wznowię ?

**Comment by PrzemyslawLukanowski** [comment]
Musisz w takim przypadku wystawić nową ofertę. Blokada zmiany tytuły dot. także zamkniętych ofert, w których wykonano zakup.
