### ISSUE TITLE
Testowe allegro - nie da się dodawać nowych ofert.

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#3269]
Występuje problem: 
 - [X ] ze środowiskiem testowym

Po wejściu na listę swoich ofert:

https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty 

nie da się dodać nowej oferty, kliknięcie w przycisk "Dodaj nową" otwiera nowe okno z URL:

https://staging-lokalnie.allegrogroup.com/oferty/wystaw 

strona nie otwiera się, zgłoszny jest błąd "Server Not Found".

Wiem, że to nie stricte REST API, ale nie wiedziałem gdzie indziej to zgosić, problem jest od kilku dni i nie da się dodawać nowych ofert do testów.

Proszę o naprawę.

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj wybrać w prawym górnym rogu:
![Screenshot_45](https://user-images.githubusercontent.com/51473661/83414492-ee76ee80-a41d-11ea-90e7-ceb3d7c1bd42.png)

Link przeniesie Cię do https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, skąd będziesz mógł wystawić nową ofertę.

**Comment by tztztztz** [comment]
Na stronie:

https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty

nie ma nigdzie takiego linku jak "Możesz też wystawić przez dotychczasowy formularz" jest tylko przycisk "Dodaj nową"

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuję, ten przycisk zobaczysz po przekierowaniu na stronie https://staging-lokalnie.allegrogroup.com/oferty/wystaw/kup-teraz.

**Comment by tztztztz** [comment]
Strona:

https://staging-lokalnie.allegrogroup.com/oferty/wystaw/kup-teraz

w ogóle się nie otwiera, jest błąd: "Nie mogę znaleźć serwera" tak jakby to był błąd DNS, może u Was lokalnie ją widzicie u siebie ale ja nie widze, jakby na publiuczne DNSy nie była zloszona ta subdomena.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, przekażę ten problem do odpowiedniego zespołu. Na tę chwilę rozwiązaniem będzie wystawienie oferty z poziomu - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by PrzemyslawLukanowski** [comment]
@tztztztz Czy w Twoim przypadku dalej występuje błąd związany z komunikatem "Nie mogę znaleźć serwera"?

**Comment by tztztztz** [comment]
Tak nadal nie mogę dla domeny domeny:

staging-lokalnie.allegrogroup.com

uzyskać adresu na IP, komenda ping nie udaje się zarówno na swoim domowym komputerze z poziomu windows, jak i z linuxa z poziomu jednego z serwerów którym zarządzam (w OVH)

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, będziemy dalej analizować ten problem.
