### ISSUE TITLE
Jak pobrać moje oferty rest api

### ISSUE THREAD

**Issue by Daniel820** [allegro/allegro-api#327]
Mam już dodawanie i edycję ofert ale jak pobrać listę moich ofert z sandbox?

**Comment by MarcinLuczak** [comment]
@Daniel820 W REST API dopiero udostępnimy zasoby, które to umożliwią. Właśnie nad nimi pracujemy. Obserwuj komunikaty na [stronie REST API](https://developer.allegro.pl/news/).
