### ISSUE TITLE
Allegro sandbox - heavy user

### ISSUE THREAD

**Issue by przemoo83** [allegro/allegro-api#3270]
Potrzebowałbym w ramach testów odpytać konto usera, które posiada co najmniej kilkanaście tysięcy ofert oraz minimum tyle samo transakcji. "Zrobienie" sobie takiego konta na Sandboxie wygląda na mocno pracochłonny proces. Tym bardziej że dane mają być stamtąd cyklicznie usuwane. Macie jakieś sugestie jak takie coś ogarnąć? A może są jakieś takie  konta na Sandboxie publicznie dostępne do testów?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma łatwego i szybkiego rozwiązania tej kwestii .Sandbox jest odzwierciedleniem środowiska produkcyjnego, dlatego jedynym sposobem jest wystawienie tych ofert za pomocą zasobów opisanych w [naszej dokumentacji](https://developer.allegro.pl/documentation/).

**Comment by rtnet-pl** [comment]
A potrzebujesz dostęp do tego konta, czy odpytujesz publicznie?

**Comment by przemoo83** [comment]
No ok tak tez  w sumie podejrzewałem, że nie będzie to łatwe. 
@rtnet-pl  Odpytuję `/sale/offers` i `/order/checkout-forms` wiec muszę być zautoryzowany jako user.
