### ISSUE TITLE
Pobieranie ofert, których external.id nie jest null

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#3271]
Witam.
Piszę z zapytaniem, czy jest opcja, aby pobrać oferty, których `external.id != null`? W dokumentacji jest opisane, że taki parametr przyjmuje wartość (id) i owszem mógłbym to zrobić w drugą stronę, ale w systemie ERP mam 1073 towary, a ofert 269 i jeszcze nie każda z nich ma ustawiony `external.id`.

**Comment by PrzemyslawLukanowski** [comment]
Nie wspieramy wyszukiwania po "!=", dlatego jedynym rozwiązaniem jest wyszukiwanie po id.
