### ISSUE TITLE
Sprawdzenie opłat utrzymaniowych

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3272]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: `12658cf0f9c3b77d`,

Kiedy pobieram opłaty z adresu `/pricing/offer-quotes?offer.id=6208257083&name=Utrzymaniowa` z parametrem name ustawionym na `Utrzymaniowa`, to w zwrotce dostaje:

```json
{
    "count": 1,
    "quotes": [
        {
            "type": "LISTING",
            "name": "Wystawienie",
            "nextDate": "2020-06-12T07:30:56.919Z",
            "fee": {
                "amount": "0.50",
                "currency": "PLN"
            },
            "offer": {
                "id": "6208257083"
            },
            "enabled": true
        }
    ]
}
```

Dlaczego zwróciło opłatę z name `Wystawienie`

**Comment by DarkStoorM** [comment]
Jeżeli jest tak jak na froncie, to opłaty utrzymaniowe będą pod filtrem **Pozostałe opłaty**, a najprawdopodobniej zwraca domyślny wynik (wszystkie), tylko nie mam jak sprawdzić 🤷

**Comment by AnimalDEV** [comment]
Z czego to widzę, nie ważne co wpiszę w `name` i tak nie bierze tego pod uwagę.

**Comment by DarkStoorM** [comment]
Aaaaaa ok, już widzę, jest to zasób https://developer.allegro.pl/documentation/#operation/getBillingEntries
A opłata utrzymaniowa to type.id = "ILF"

**Comment by AnimalDEV** [comment]
@DarkStoorM 
Bardziej ten zasób
https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET,
A tutaj pisze, jakie są możliwe nazwy https://developer.allegro.pl/charges/#4

- Wystawienie,
- Pogrubienie,
- Podświetlenie,
- Wyróżnienie,
- Pakiet promo,
- Strona działu,
- Cena minimalna,
- Okazja,
- Utrzymaniowa

**Comment by DarkStoorM** [comment]
@AnimalDEV  ah, ok, dokumentacja poprowadziła mnie do zmian z lutego 2018 i nie widniała tam nazwa **Utrzymaniowa** i dlatego szukałem innego zasobu. 
Z drugiej strony i tak ciągle zwraca wszystkie opłaty z podanej oferty, a **name** jakby ignorowało. Obojętnie co podam to i tak wszystkie opłaty pokazuje. Dobrze, że ten drugi zasób chociaż działa

**Comment by PrzemyslawLukanowski** [comment]
Parametr 'name' nie jest wspierany dla GET /pricing/offer-quotes. Dziękuję, że zwróciliście uwagę na ten problem, w najbliższym czasie zaktualizujemy naszą dokumentację.

**Comment by AnimalDEV** [comment]
@PrzemyslawLukanowski Co jeśli zakończę ofertę na 7 dni przed naliczeniem opłat utrzymaniowych i po 2 tygodniach ją wznowie (pod tym samym id), to czy opłaty zostaną naliczone od razu, czy czas kiedy była nieaktywna nie zostanie wliczony, a opłaty zostaną naliczone dopiero za 7 dni?

**Comment by PrzemyslawLukanowski** [comment]
@AnimalDEV W takim przypadku opłaty zostaną naliczone od razu.
