### ISSUE TITLE
Brak możliwości wystawiania aukcji

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#3273]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: ab1d44edb6e27020

Witam.

Klient zgłasza nam problem z wystawianiem aukcji. W sekcji Validation dostajemy komunikat **You don't have the required permissions to publish offer (sell blocked).**
Jest to dla mnie zrozumiałe i mógłbym to odbić, jednak wystawiając aukcje od strony panelu Allegro wszystko działa prawidłowo, tam nie ma żadnej informacji o blokadzie.  
Proszę o informację co jest przyczyną takiej blokady wystawiania od strony API.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku komunikat jest prawidłowy - użytkownik od 01.06.2020 00:20 ma nałożoną blokadę sprzedaży.

**Comment by bacok** [comment]
W porządku, dziękuję za informację.
