### ISSUE TITLE
UTF-32 w danych dla zamówienia

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#3275]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Chciałbym zgłosić problem z kodowaniem znaków jakie otrzymałem dla zamówienia o id *8a1cc162-a4ce-11ea-955c-b9ddc84478c0*. Dziwnie wyglądające znaki znajdują się w street oraz city zarówno w adresie dostawy jak i w danych kupującego.
![alt](https://share.merce.com/files/P5uUJK2v.png) 
_(rozmycie jest celowe, proszę zwrócić uwagę na czcionkę w polu street i city)_
Czy takie znaki będą zwracane w przyszłości czy jest to bug po Waszej stronie? Chce wprowadzić odpowiednie zabezpieczenia.
Zamówienie pobieram oczywiście za pomocą endpointu `[GET] /order/checkout-forms/8a1cc162-a4ce-11ea-955c-b9ddc84478c0`

**EDIT:** wrzucam wycinek odpowiedzi jaką dostaje
```
"address": {
            "street": "𝐖𝐢𝐥𝐜𝐳𝐤𝐨𝐰𝐢𝐜𝐞 (...)",
            "city": "𝐌𝐢𝐜𝐡𝐚ł𝐨𝐰𝐢𝐜𝐞",
            "postCode": "32-091",
            "countryCode": "PL"
        }

**Comment by PrzemyslawLukanowski** [comment]
Nie jest to problem związany stricte z formatowaniem znaków w zamówieniu - user przekazał dane w takiej postaci już w ustawieniach swojego konta. Przekazuję ten problem do odpowiedniego zespołu.
