### ISSUE TITLE
Sandbox - requests not working

### ISSUE THREAD

**Issue by IHaveIssuesWithAllegro** [allegro/allegro-api#3277]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hello,
im testing your api on sandbox and i have issue with some requests.
sale/categories requests seem to work ok, requests below do not. Results from your api included.
Results are always same, so i cant rly use the api.
Can you please tell me where the issue might be?
Thanks.

GET sale/offers
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

POST sale/offers
{"errors":[{"code":"UserRepresentativeException","message":"Empty user_name claim","details":null,"path":null,"userMessage":"There was an error while trying to get related account's resources."}]}

POST sale/product-proposals
{"errors":[{"code":"UserRepresentativeException","message":"Empty user_name claim","details":null,"path":null,"userMessage":"There was an error while trying to get related account's resources."}]}

POST sale/images (posting image as url)
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]}

**Comment by PrzemyslawLukanowski** [comment]
You are using [clients credentials](https://developer.allegro.pl/en/auth/#clientCredentialsFlow) type of authorization. To get access to this endpoints, you should use token from [code flow](https://developer.allegro.pl/en//auth/#app) or [device flow](https://developer.allegro.pl/en//auth/#DeviceFlow) authorization.
In documentation you can find [information](https://developer.allegro.pl/documentation/#section/Authentication), which type of authorization you should use for selected resource:
![67561795-c4d64600-f71d-11e9-83f7-f265c20bed55](https://user-images.githubusercontent.com/51473661/83610079-53962580-a57f-11ea-9fd4-fe31a7fb9162.png)

bearer-token-for-user - code or device flow,
bearer-token-for-application - client credentials flow - access only to public resources, without user context, e.g. GET /offers/listing or mentioned GET /sale/categories.

**Comment by IHaveIssuesWithAllegro** [comment]
Hello, thanks for reply.
Im not sure i understand the documentation properly, but if we have an e-shop which would use your api to create offers ect. and we got api credentials, we still have to make user login in his browser to allegro and only then we can receive token so we can post offers?
We need to post offers for the user through which we created/obtained api credentials. I believe those should be everything we need so i guess i missed something?
Thanks.

**Comment by IHaveIssuesWithAllegro** [comment]
Sorry if i wasnt clear enough, i will try to explain what we are after.
We have client (owner of e-shop) which created account on allegro, through which he created and gave us api credentials.
We need to perform operations through api on behalf of this users account (automated operiations on eshop when prices change, new products are added/removed ect.).
Required authorization to perform actions: bearer-token-for-user.
So, we need to use the api credentials to have permanent access to this users account through api until the account or api credentials are deleted.
We need to do so without user having to do anything else, if he doesnt want us to have access to his account anymore, he will remove api credentials in his allegro account.
	
Documentation contains 2 options for required auth (bearer-token-for-user):
	- authorization code flow
	- device code flow
		
Both speak about user having to login in his browser.
Option which seems to not require user to login is which we want, but it seems it can grant access only to read data from allegro?

So if i understand your documentation properly, we need the owner of eshop to put in his api credentials, then he has to login to his allegro account from eshop (using credentials from his api) so eshop can get token to perform required api operations on behalf of his account, and then he has to periodically renew the token in future with more logins to allegro from eshop?
Thanks.

**Comment by PrzemyslawLukanowski** [comment]
User should login to the browser only once - when clicking the 'Log in to Allegro' button/link in your application. After that, user will be redirected to the log in form on Allegro.pl, where he grants a consent for the application to perform operations/requests on his behalf.
User doesn't need to login in the future to extend token validity. You can use [refresh token mechanism](https://developer.allegro.pl/en/auth/#refresh-token) without user actions.
Please remember that correct approach is to generate API credentials (clientId and client secret) per application, not per single user.

**Comment by IHaveIssuesWithAllegro** [comment]
Thanks, issue solved with different login method.
