### ISSUE TITLE
BUG: Custom values are not enabled in the parameter

### ISSUE THREAD

**Issue by pavelion** [allegro/allegro-api#3278]
Requesting /sale/categories/256728/parameters returns 
...
{'id': '18112',
   'name': 'Marka',
   'type': 'dictionary',
   'required': True,
   'unit': None,
   'options': {'variantsAllowed': False,
    'variantsEqual': True,
    'ambiguousValueId': '18112_4096',
    'dependsOnParameterId': None},
   'dictionary': [{'id': '18112_1048576',
     'value': '4F',
     'dependsOnValueIds': []},
...

Trying to update offer in the category with following parameters payload (as described here https://developer.allegro.pl/sale/#w%c5%82asna-warto%c5%9b%c4%87-parametru):

...
 'parameters': [{'id': '18112', 'valuesIds': ['18112_4096'], 'values': ['Kama']}],
...

Returns:

2020-06-03 09:59:03 [32] WARNING Status: 400	Message: Unable to update offer 8306804279	Original response: {'errors': [{'code': 'BAD_REQUEST', 'message': 'Custom values are not enabled in the parameter: parameterId=18112', 'details': '', 'path': '', 'userMessage': "W parametrze 'Marka' nie można definiować własnych wartości słownikowych"}]} (/usr/local/lib/python3.7/site-packages/shop-2.76.1-py3.7.egg/shop/allegro/webapi.py:parse_error_message)

**Comment by PrzemyslawLukanowski** [comment]
Custom values are a new feature and for now available only in selected categories. You can find the full list [here.](https://allegro.pl/dla-sprzedajacych/na-api-mozesz-wprowadzic-wlasna-wartosc-parametru-marka-w-wybranych-kategoriach-z8EDxMZd0fa) ("parametry w ktorych sprzedajacy moze rozszerzyc slownik wartości,")

**Comment by pavelion** [comment]
Do you mean that ambiguous value can't be used as parameter 18112 value in given the category, even if the API responds with  'ambiguousValueId': '18112_4096' instead of 'ambiguousValueId': null ?

How should API client know if the ambiguous value can or cannot be used? Parsing linked XLS file and hoping it is up-to-date?

**Comment by PrzemyslawLukanowski** [comment]
Custom value for ambiguous value can't be used in this category, but ambiguous value can be used itself (without providing custom value). You can find more information about ambiguousValueId in [our news](https://developer.allegro.pl/en/news/#ambiguousValueId).

Right now list of available parameters can be found on our sellers page. There is no separate solution to API clients.
