### ISSUE TITLE
Problem z pobieraniem zasobow z kontekstem uzytkownika.

### ISSUE THREAD

**Issue by wojtasss** [allegro/allegro-api#3280]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

wysylam takie o to zapytanie z tokenem uzyskanym przez autoryzacje "device flow" z kontekstem uzytkownika:

`
curl --location --request GET 'https://api.allegro.pl/sale/offers/' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer <TOKEN>'
`

otrzymuje odpowiedz:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/","userMessage":null}]}`

z kodem 405 Method not allowed

prosze o pomoc

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj usunąć  '/' na końcu 'sale/offers/'.

**Comment by wojtasss** [comment]
Dziala :) Dziekuje za pomoc, mozna zamknac temat
