### ISSUE TITLE
Sandbox: Nieaktywne - trwa weryfikacja Twoich danych.

### ISSUE THREAD

**Issue by erte04** [allegro/allegro-api#3281]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,
proszę o aktywację konta sprzedawcy w sandboxie. Login: test_tez
Pojawia mi się komunikat: 

> Nieaktywne - trwa weryfikacja Twoich danych.
> Weryfikacja Twoich danych może potrwać do 3 dni. O jej wyniku poinformujemy Cię e-mailem.
>

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by erte04** [comment]
Dziękuję bardzo za szybki odzew. Już działa. Pozdrawiam
