### ISSUE TITLE
POST /sale/product-offers - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by grzesiektoton** [allegro/allegro-api#3282]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próbuje stworzyć na sandbox testową ofertę, używam przykładu z https://developer.allegro.pl/product_offers/
Niestety dostaje błąd jak poniżej. Czekanie nic nie pomaga. 

*trace-id:94500d8ea4a63d4*

**Request**
```
{
    "product": {
        "name": "Produkt testowy",
        "category": {
            "id": "89060"
        },
        "parameters": [
            {
                "name": "EAN",
                "values": [
                    "0744861045021"
                ]
            },
            {
                "id": "237218",
                "values": [
                    "Testowy tytuł"
                ]
            }
        ],
        "images": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/3-Tasten-Maus_Microsoft.jpg/220px-3-Tasten-Maus_Microsoft.jpg"
        ]
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    }
}
```

**Response**
```
https://api.allegro.pl.allegrosandbox.pl:443 "POST /sale/product-offers HTTP/1.1" 500 None
{   'errors': [   {   'code': 'INTERNAL_SERVER_ERROR',
                      'details': None,
                      'message': 'Internal server error.',
                      'path': None,
                      'userMessage': 'Internal server error. Please try again '
                                     'in a few minutes.'}]}
```

**Comment by PrzemyslawLukanowski** [comment]
Problem wynika z tego, że kategorie i parametry w środowisku testowym nie są do końca zsychnronizowane z produkcją. 8 czerwca je zaktualizujemy, info znajdziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/3267).  Aby Twój request zadziałał na środowisku testowym, usuń parametr 237218, jak poniżej:

```
{
    "product": {
        "name": "Produkt testowy",
        "category": {
            "id": "89060"
        },
        "parameters": [
            {
                "name": "EAN",
                "values": [
                    "0744861045021"
                ]
            }
        ],
        "images": [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/3-Tasten-Maus_Microsoft.jpg/220px-3-Tasten-Maus_Microsoft.jpg"
        ]
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 10
    }
}
```

W odpowiedzi dla [statusu produktu ](https://github.com/allegro/allegro-api/issues/3257) otrzymasz 'NOT_LISTED', ponieważ w tej kategorii na Sandboxie nie możesz dodawać propozycji nowych produktów. Samą ofertę utworzymy i aktywujemy.

**Comment by grzesiektoton** [comment]
Dziekuje za odpowiedź.

Niestety po usunięciu parametru nadal nie działa, ten sam błąd.

_trace-id: dcb37418d159c460_

**Comment by PrzemyslawLukanowski** [comment]
Powodem błędu jest także to, że nie masz uzupełnionej lokalizacji w Danych Konta. Dodaj proszę tę informację i spróbuj powtórzyć request.

**Comment by grzesiektoton** [comment]
Zadziałało, dziekuję!
