### ISSUE TITLE
czy i jak można otworzyć płatność przekazując ID zamówienia w URL ?

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#3283]
Cześć,
takie pytanie czy i jak można otworzyć płatność przekazując ID zamówienia w URL ?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chcesz otworzyć płatność w [historii operacji](https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji#!/), możesz przekazać tylko payment.id, np. https://allegro.pl/moje-allegro/sprzedaz/srodki-i-historia-operacji#!/?query={paymentId}. Po id zamówienia jest to niemożliwe.
