### ISSUE TITLE
Obsługa tylko i wyłącznie sfinalizowanych zamówień, rozpatrzenie przypadków.

### ISSUE THREAD

**Issue by wojtasss** [allegro/allegro-api#3284]
Na stronie developer.allegro.pl doszukałem się następujących informacji: 

1) READY_FOR_PROCESSING - klient wypełnił FOD i sfinalizował płatność (status: zakończona), albo wybrał płatność przy odbiorze lub odbiór osobisty. Dopiero w tym statusie zobaczysz adres dostawy jaki klient podał na FOD. Jeśli otrzymasz ten status, masz pewność, że w danych na FOD nic się już nie zmieni

2) Możesz np. otrzymać kilka zdarzeń READY_FOR_PROCESSING, dlatego zwróć uwagę na identyfikator zamówienia w obiekcie checkoutForm i to właśnie na nim oprzyj swoją logikę obsługi zamówień.

3) Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty otrzymasz nowe zdarzenie z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

Czyli jeżeli interesują mnie zamówienia tylko i wyłącznie sfinalizowane (opłacone, za pobraniem, odbiór osobisty) muszę sprawdzić w każdym event checkout-form i jeżeli w tym checkout-form jest READY_FOR_PROCESSING oznacza to jest to już finalna wersja zamówienia? 

W jakim przypadku możemy otrzymać w event READY_FOR_PROCESSING a w checkout-form inny status?

Czy jeżeli rozpatruję tylko sfinalizowane zamówienia z READY_FOR_PROCESSING muszę uważać na przypadek z 3) czy jako że interesują mnie tylko i wyłącznie sfinalizowane zamówienia, takich przypadków nie napotkam ponieważ będą one występowały przed sfinalizowaniem zamówienia?

**Comment by PrzemyslawLukanowski** [comment]
> Czyli jeżeli interesują mnie zamówienia tylko i wyłącznie sfinalizowane (opłacone, za pobraniem, odbiór osobisty) muszę sprawdzić w każdym event checkout-form i jeżeli w tym checkout-form jest READY_FOR_PROCESSING oznacza to jest to już finalna wersja zamówienia?


Tak, READY_FOR_PROCESSING oznacza, że zamówienie jest gotowe do wysyłki. Pamiętaj, że kupujący może [anulować zamówienie](https://github.com/allegro/allegro-api/issues/3085), otrzymasz wtedy dodatkowy event BUYER_CANCELLED, a status zamówienia zmieni się na CANCELLED. Aby prawidłowo procesować takie przypadki, możesz korzystać z pola [revision](https://github.com/allegro/allegro-api/issues/3187).

> W jakim przypadku możemy otrzymać w event READY_FOR_PROCESSING a w checkout-form inny status?

Takie sytuacje nie powinny występować. Jeżeli otrzymasz event RFP, to w tym samym momencie status zamówienia również zmieni się na RFP.

> Czy jeżeli rozpatruję tylko sfinalizowane zamówienia z READY_FOR_PROCESSING muszę uważać na przypadek z 3) czy jako że interesują mnie tylko i wyłącznie sfinalizowane zamówienia, takich przypadków nie napotkam ponieważ będą one występowały przed sfinalizowaniem zamówienia?

Zgadza się, w statusie RFP zobaczysz zamówienie już po tym, jak kupujący połączył płatność dla dwóch osobnych przedmiotów i sfinalizował zakup.
