### ISSUE TITLE
offers/listing różnice w kolejności zwracanych wyników

### ISSUE THREAD

**Issue by madkot** [allegro/allegro-api#3285]
Dzień dobry,
w opisie zasobu **offers/listing** jest wyraźnie zaznaczone:

> WAŻNE! Pamiętaj, że ta metoda jest odzwierciedleniem wyszukiwarki w wizualnej wersji serwisu, przykładowo w pierwszej kolejności otrzymasz promowane oferty.

Jakkolwiek nie ustawie parametrów/filtrów to wyniki z API nie pokrywają się z wynikami na stronie (chodzi o kolejność).

od razu zaznacze, że trafność itd ustawiam takie same zarówno w API jak i w 'wizualnej wersji serwisu".

sprawdzałem na wynikach z samej kategorii, jak i z konkretną frazą wyszukiwania.

Skąd są te różnice?

**Comment by PrzemyslawLukanowski** [comment]
Wyjaśnienie znajdziesz w wątku #2516.

**Comment by madkot** [comment]
Dzięuje. To mi wystarczy.
