### ISSUE TITLE
Metoda płatności w REST API i zamówieniach

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#3287]
Czy coś ruszyło w tym temacie?
https://github.com/allegro/allegro-api/issues/1246

Czy przez REST API mogę się dowiedzieć jaką metodę płatności wybrał klient? W szczególności czy to przelew tradycyjny czy szybka płatność.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy wprowadzać takiej informacji, ale czy możesz doprecyzować, jaka byłaby potrzeba dla takiego pola (jeśli jest inna niż w wątku #1246)?

**Comment by Lebioda** [comment]
Potrzeba jest dokładnie taka sama. Klienci nie zdają sobie sprawy, że płatność się nie udała albo nie wiedzą co z tym fantem zrobić. W tej chwili wysyłam im maile i mają one dużą skuteczność. Chciałbym to zautomatyzować (najlepiej jakby samo Allegro dodało taką funkcję). Na statusie płatności nie można polegać bo wisi w stanie "Rozpoczęta" bez końca.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację. Przekazałem ją do odpowiedniego zespołu i jeśli miałoby się zmienić coś w tej kwestii, poinformuję.
