### ISSUE TITLE
Import products from Allegro to woocommerce

### ISSUE THREAD

**Issue by achchu93** [allegro/allegro-api#3288]
Hello developers,

I am trying to achieve a task related to woocommerce. Seriously i didnt have good understand about how Allegro product and offers work. But later on i understood a bit. I dont understand the API doc as well. May be it should be more explained with correct examples. Let me list down what i am looking for. (we are okay to pay for this if there is a need.)

1. **List down products by filters.**
Currently i do this by `GET /offer/listing` endpoint. Now i want to get the product of this offer. But i dont see any product id in the listing response. I trust the ID which contains in the response is for offer ID. Is there way to get the Single product details by offer id? When i tried to get the single offer by `GET /sale/offer/{offerId}`  it says forbidden. I trust it is because i am using application level auth. Next question would be regarding auth.

2. **Auth Level**
As i tested with some endpoints, some endpoints need user-bearer-token and some need application-bearer-token. I wanna know which i should i use to do all actions. Like admin role where i can do any actions.

Those are the questions for now. But i would suggest if you can explain what is the offer and product in allegro and how do them work then it would be very helpful for future developers. Because i couldnt retrieve products by cateory.id. It requires phrase or seller.id to be in the request. But i dont want to filter with it. I wanna get all the products under a category. So please help me out for this issues. 

Thanks,
best regards!

**Comment by PrzemyslawLukanowski** [comment]
1. You can't retrieve offers details, if you're not the owner of them. You can only search listing offers via GET offers/listing.

2. bearer-token-for-application authentication is authorization without user context, so you will be able to retrieve only public data, such as GET /sale/categories, GET /offers/listing. If you want to list offers, manage offers, retrieve orders, etc. you should use bearer-token-for-users.

As you mentioned - on Allegro we have offers and those offers can be assigned to a specific product. For example - you can list offer item via POST /sale/offers and in the response, you will get its ID, after activating this offer will be visible on our site, and customers may buy it. You can also assign this offer to a specific product, which is in our database - product is described by a set of product parameters (which not include condition, price, or quantity, etc.). Thanks to this, customers will find a product that meets their needs easier. You can find more information about productization in our guides:

- [How to list an offer assigned to a product with one request,](https://developer.allegro.pl/en/product_offers/),
- [Assigning offers to a products
](https://developer.allegro.pl/en/productization/).
