### ISSUE TITLE
[REST-Prod] Miszczostfo świata - tak odpowiada ID na produkcji:

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#3289]
"parameters":[{"id":"130691","valuesIds":["130691_128","130691_2"],"values":["Produkt niesiarkowany","Produkt wegański","Produkt wegetariański"],"rangeValue":null},{"id":"128456","valuesIds":[],"values":["Pieprz czarny ziarno"],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["0.06"],"rangeValue":null}]

(nie podaję tu ID, bo już ręcznie naprawione...)

**Comment by PrzemyslawLukanowski** [comment]
Doprecyzuj proszę problem i napisz, czego konkretnie dotyczy.

**Comment by FromAnyHole** [comment]
@PrzemyslawLukanowski - ano dwa błędy były w strukturze "parameters":
- przedmiot odpowiadał wartościami "valuesIds" oraz "values" (dla "id":"130691")
- dodatkowo (dla kat. 77746) sypał nieaktualnym ID parametru ("id":"128456").

Przy okazji - czy te poniższe zasoby są (lub będą) aktualizowane??
https://github.com/allegro/allegro-api/files/4474138/lista.parametrow.globalnych.xlsx
https://assets.allegrostatic.com/popart-attachments/att-3460bc78-d497-4078-91ac-bb7428b3d06f

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć żadnego z tych błędów, więc jeśli problem nadal występuje - proszę o informację, jakie konkretnie operacje wykonujesz. Możesz przesłać także przykładowe trace-id.


> Przy okazji - czy te poniższe zasoby są (lub będą) aktualizowane??
> https://github.com/allegro/allegro-api/files/4474138/lista.parametrow.globalnych.xlsx
> https://assets.allegrostatic.com/popart-attachments/att-3460bc78-d497-4078-91ac-bb7428b3d06f

Te pliki nie są aktualizowane.

**Comment by FromAnyHole** [comment]
Ok, dajmy już spokój tym błędom - pewnie to wynik nanoszonych zmian...
Sprawa ważniejsza, to jak na dzisiaj wygląda sytuacja z komunikatu poniżej?
https://allegro.pl/dla-sprzedajacych/na-api-mozesz-wprowadzic-wlasna-wartosc-parametru-marka-w-wybranych-kategoriach-z8EDxMZd0fa

**Comment by PrzemyslawLukanowski** [comment]
Ta lista jest aktualna - możesz dodać własną wartość dla parametru "Marka" w tych kategoriach.

**Comment by FromAnyHole** [comment]
Fajnie, fajnie... Ale jak konkretnie wygląda dzisiaj ta cała "procedura"??
- czy nadal przechodzi to etap weryfikacji i zatwierdzenia w REST?
- czy jest jakiś konkretny komunikat po zatwierdzeniu lub odrzuceniu?
- czy to się zawsze pojawia globalnie dla wszystkich kont użytkowników?
- czy można na siebie "nakładać" więcej propozycji dla ID parametru w kategorii?
- zgodnie z zapowiedzią - kiedy będzie to obowiązkowe dla "ambiguousValueId"??

**Comment by PrzemyslawLukanowski** [comment]
> czy nadal przechodzi to etap weryfikacji i zatwierdzenia w REST?

Nie, własną wartość dla marki od razu dodajemy do oferty.

> czy jest jakiś konkretny komunikat po zatwierdzeniu lub odrzuceniu?

Nie, w modelu oferty zobaczysz poniższą strukturę:

```
   "parameters": [
        {
            "id": "129033",
            "valuesIds": [
                "129033_13"
            ],
            "values": [
                "Nazwa brakującej marki"
            ],
            "rangeValue": null
        }
    ],
```

> czy to się zawsze pojawia globalnie dla wszystkich kont użytkowników?

Tak, wartość jest widoczna w ofercie dla wszystkich.

> czy można na siebie "nakładać" więcej propozycji dla ID parametru w kategorii?

Możesz podać tylko jedną wartość dla parametru "Marka". Możesz tę wartość nadpisać, wtedy poprzednią usuniemy.

> zgodnie z zapowiedzią - kiedy będzie to obowiązkowe dla "ambiguousValueId"??

Jeszcze nie mamy dokładnej daty, opublikujemy odpowiednio wcześniej komunikat w tym temacie.

**Comment by FromAnyHole** [comment]
Ale zaraz - zasięg tej operacji jest globalny czy "per user account"?? Chyba to drugie raczej, bo przecież inaczej niezły bajzel by powstawał ;-)

**Comment by PrzemyslawLukanowski** [comment]
Jako zautoryzowany użytkownik możesz dodać swoją wartość dla Marki w kategoriach z pliku i będzie ona widoczna w serwisie.

**Comment by FromAnyHole** [comment]
Czyli co - mamy taką "karuzelę zgłoszeń"?? Każdy może da wszystkich innych zmieniać, no i raz ta wartość "niejednoznaczna" jest taka a innym razem siaka??? Coś to dziwnie wygląda...

**Comment by FromAnyHole** [comment]
Czyli co - mamy taką "karuzelę zgłoszeń"?? Każdy może dla wszystkich innych zmieniać, no i raz ta wartość "niejednoznaczna" jest taka a innym razem siaka??? Jakoś to dziwnie wygląda...

**Comment by PrzemyslawLukanowski** [comment]
Możesz zmienić wartość tylko w swoich ofertach. Zachowanie jest takie samo, jak w przypadku innych parametrów, np. możesz zmienić wartość "Inny" na "Testowa Marka".

**Comment by FromAnyHole** [comment]
Aha, więc jednak zasięg tego jest 'per user', no to jeszcze taki przypadek:
- przedmiot [A] z kategorii [xxx] ma nadaną wartość tego parametru jako "Dobra Marka"
- zmieniamy wartość tego parametru z kategorii [xxx] dla przedmiotu [B] na "Inna Marka"
- wystawiamy przedmiot [C], ale z innej kategorii [zzz] gdzie występuje ten sam parametr
- czy w tej innej kategorii [zzz] pojawi się do wyboru wartość parametru z kategorii [xxx]?
- czy przedmiot [A] nadal ma wartość tego parametru "Dobra Marka", czy "Inna Marka"?

**Comment by PrzemyslawLukanowski** [comment]
Nie, w kategorii [zzz] nie pojawi się do wyboru taka wartość. Na tę chwilę będziesz mógł ją jedynie dodać ręcznie jako własną wartość parametru niejednoznacznego. Zgodnie z informacją naszego newsa - "Dzięki temu zbierzemy propozycje brakujących wartości, zweryfikujemy je i uzupełnimy listę wartości danego parametru" - czyli własną wartość możesz dodać od razu, ale nie jest to jednoznaczne z tym, że automatycznie ją dodamy do listy dostępnych parametrów. Na tym etapie zbieramy propozycje wartości.

Przedmiot [A] nadal będzie mieć wartość "Dobra Marka", bo w kontekście tej oferty nie doszło do zmiany wartości parametru. Zmieniłeś wartość dla przedmiotu [B] - osobnej oferty, która nie jest powiązana z przedmiotem [A].
