### ISSUE TITLE
Problem z certyfikatem ssl

### ISSUE THREAD

**Issue by GosiaJK** [allegro/allegro-api#3290]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

<curl -X POST https://allegro.pl/auth/oauth/device -H 'Authorization: Basic base64(clientID:clientsecret)' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id={clientID}'>

Komendy żywcem przepisane z dokumentacji rest api. 
Po uruchomieniu pojawia się komunikat:

curl: (60) SSL certificate problem: unable to get local issuer certificate

i dalej kilka innych, jak się domyślam powiązanych z powyższym.
W jaki sposób mogę pozbyć się problemu?

**Comment by TimothyKoval** [comment]
> W jaki sposób mogę pozbyć się problemu?

W taki sam jak większości tego typu problemów; [google.pl](https://google.pl)

**Comment by PrzemyslawLukanowski** [comment]
@GosiaJK W wątku #3079 znajdziesz link, do jednego z rozwiązań problemu.

**Comment by GosiaJK** [comment]
I jeszcze jedno pytanie odnośnie kodu. W jakim programie mogę żywcem przepisywać komendy ze strony https://developer.allegro.pl/? Chodzi mi np. o przeklejenie tego zapytania <curl -X POST https://allegro.pl/auth/oauth/device -H 'Authorization: Basic base64(clientID:clientsecret)' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id={clientID}'>

**Comment by PrzemyslawLukanowski** [comment]
Możesz to zrobić m.in. za pomocą lini poleceń, jednak jako Allegro nie możemy wskazać zewnętrznych rozszerzeń i programów.

**Comment by MaciejFrackowiak** [comment]
Jeżeli wywołując request otrzymujemy response z danymi potwierdza to prawidłowość działania użytkownika. Nie wskazujemy konkretnych aplikacji - kontekstu "prywatnie" również nie wspieramy.

**Comment by GosiaJK** [comment]
W dalszym ciągu nie otrzymałam konkretnej odpowiedzi. W jaki sposób wywołać request? Wpisując z palca? Ale gdzie? W którym programie działa to konkretne zapytanie z początku mojego posta.

**Comment by MaciejFrackowiak** [comment]
Wszystko zależy od języka programowania, którego będziesz używać. Możesz request wywołać także z poziomu konsoli czy też terminala. Jako Allegro nie wskazujemy konkretnych rozwiązań, ani programów - ich wybór pozostaje w gestii użytkownika.
