### ISSUE TITLE
Problem z aktywacją konta na środowisku testowym

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#3291]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Występuje problem z aktywacją konta na Sandboxie. Pomimo podania poprawnych danych firmy, próby autoryzacji przez płatność, czy nawet zakup na innej aukcji - konto nie chce zmienić statusu, co uniemożliwia wystawianie ofert.

Proszę o informację, jak prawidłowo aktywować konto testowe (żeby wydarzyło się to automatycznie), a także ewentualną manualną aktywację konta horex-sandbox.

**Comment by MaciejFrackowiak** [comment]
Przed momentem aktywowałem konto - proszę sprawdź czy masz już możliwość wystawienia oferty.

**Comment by Gamatronic** [comment]
Proszę o aktywacje dwóch kont na Sanboxie:
Gam1
Gam

**Comment by MaciejFrackowiak** [comment]
@Gamatronic Oba konta aktywowałem. W przypadku Gam proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) - jest to wymóg do zweryfikowania konta Firma.

**Comment by MaciejFrackowiak** [comment]
@Gamatronic Zajrzyj proszę [tu](https://allegro.pl.allegrosandbox.pl/myaccount/Settings/mysettings.php) i dołącz wspomniane pliki.

**Comment by Gamatronic** [comment]
Dziękuję niestety pojawia się poniższy komunikat:
"Wpisałeś błędny kod. Wpisz poprawnie kod z obrazka"
a nie widzę tu żadnego pola z kodem do uzupełnienia

**Comment by MaciejFrackowiak** [comment]
@Gamatronic Prace trwają, staramy się możliwie szybko przywrócić funkcjonalność - zamieszczę info w poście.
