### ISSUE TITLE
Brak opcji anulowania w szczegółach zakupu

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3292]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry,
Czy w środowisku testowym występuje problem z anulowaniem zamówienia, nie mogę znaleźć tej opcji w szczegółach zakupu, wcześniej widziałem, że była. Na koncie sprzedającego opcja anulowania jest włączona.

**Comment by MaciejFrackowiak** [comment]
Opcja może pojawić się z drobnym opóźnieniem na Sandbox. Proszę o chwilę cierpliwości.

**Comment by pawelosajda** [comment]
Zamówienie 6b067bc2-a70a-11ea-8306-ed1189c14bbf z 5 cze 2020, 10:59 status 
`"status": "READY_FOR_PROCESSING",
    "fulfillment": {
        "status": "NEW",
        "shipmentSummary": {
            "lineItemsSent": "NONE"
        }
    },`
Też nie widać opcji anulowania

**Comment by MaciejFrackowiak** [comment]
Spojrzałem na konto, które wykorzystujesz jako konto sprzedającego - ono nie jest do końca zweryfikowane jako firmowe, nie przesłano dwóch dowolnych plików. Efektem tego jest brak opcji anulowania na koncie kupującego. Proszę prześlij dwa dowolne pliki w zakładce Dane konta by konto zostało zatwierdzone jako firmowe w pełni.

**Comment by pawelosajda** [comment]
Konto już chyba jest w pełni aktywowane?
> 2020-06-08 11:25:55 | Pozytywna weryfikacja Allegro
Ile wynosi maksymalny czas pojawienia się opcji anulowania? 5ea03062-a96c-11ea-8306-ed1189c14bbf

**Comment by MaciejFrackowiak** [comment]
Powód braku opcji anulowania leży w samym koncie kupującego - anulowanie jest dostępne tylko dla kont zwykłych, a na koncie kupującego wybrano konto Firma.

**Comment by pawelosajda** [comment]
Dziękuje, już widzę opcje
