### ISSUE TITLE
Sandbox Logowanie

### ISSUE THREAD

**Issue by hYOUstone** [allegro/allegro-api#3293]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, Chyba jest problem z logowaniem tradycyjną metodą na Sandbox. Logowanie przez Google działa. Gdy próbując tradycyjnie (login, hasło), krzyczy że nieprawidłowy login lub hasło. Zmieniam hasło (przez przypomnij hasło) i system twierdzi, że wraz hasło jest nieprawidłowe. Operacje tą próbowałem robić kilkanaście razy i nic z tego. Niestety Logowanie przez google dla rozpatrywanego przeze mnie przypadku jest bezużyteczne. Potrzebuję tradycyjnej metody do połączenia kont użytkowników ze swojego portalu. Swoją drogą łączenie kont przez OAuth URL https://allegro.pl.allegrosandbox.pl/auth/oauth/ powinno działać przez logowanie z googla, tymczasem dzieje się inaczej. OAuth URL (wywołane z mojego serwisu) pokazuję okno logowania allegro. Następuje próba logowania przez google. Loguje mnie, ale zamiast wrócić na podany adres powrotny przekierowań (podany w dev apps), przekierowuje mnie do strony Allegro Sandbox.
REASUMUJĄC:
Nie jestem w stanie absolutnie w żaden sposób połączyć kont użytkowników z kontem Sandbox (przez OAuth Url) przez dwa wykryte przeze mnie błędy:
1. Nie działa tradycyjne logowanie allegro sandbox (również przez OAuth Url)
2. Logowanie z OAuth URL poprzez Google zamiast kierować do adresu przekierowań kieruje na stronę Allegro Sandbox

**Comment by MaciejFrackowiak** [comment]
Ad. 1 - nie potwierdzam problemu, bez przeszkód zalogowałem się korzystając z loginu i hasła. Także skorzystałem z przypomnienia hasła, zmieniłem je i zalogowałem się na konto. 

Ad. 2 - proszę doprecyzuj kolejne kroki, które wykonujesz - tak byśmy mogli odtworzyć krok za krokiem.

**Comment by hYOUstone** [comment]
Przepraszam, ale jestem zmuszony ponowić wątek... O ile po moim zapytaniu (sprzed ponad miesiąca -jak wyżej), faktycznie zaczęło mi logowanie działać. W formie prób nic nie zmieniłem. Próbowałem wtedy na różnych przeglądarkach i to nie pomogło, ale faktycznie tak jak mówię zaczęło działać tak samo nagle jak nagle dzisiaj stwierdziłem, że znowu logowanie tradycyjne nie działa. Myślałem, że skasowane zostały na Sandboxie moje konta -ale najwyraźniej nie, ponieważ nie da się przypomnieć hasła jak i utworzyć nowego konta. Wywala błąd przy haśle, że jest nieprawidłowe we wszystkich przypadkach (logowanie, przypomnienie hasła oraz próba stworzenia nowego konta firmowego).

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście mieliśmy problem z logowaniem - obecnie problem został usunięty. Przepraszam za niedogodności.
