### ISSUE TITLE
Pobieranie aukcji Rest

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#3294]
Czy jest jakiśproblem z Restem?

Od jakiegoś czasu nie pobieramy wszystkich naszych wystawionych aukcji. Korzystamy z:

GET https://allegroapi.io/offers/listing?seller.id=2722090&searchMode=DESCRIPTIONS&phrase=AL%20AD%20PINCH%202SZT&limit=100&offset=0

**To np. jest:**

GET https://allegroapi.io/offers/listing?seller.id=2722090&searchMode=DESCRIPTIONS&phrase=AL%20AD%20PINCH%202SZT&limit=100&offset=0 HTTP/1.1

Accept: application/vnd.allegro.public.v1+json;charset=UTF-8

Content-Type: application/vnd.allegro.public.v1+json

Accept-Language: PL

Authorization: Bearer ...

Api-Key: ...

Host: allegroapi.io

 

 

HTTP/1.1 200 OK

server: envoy

trace-id: 2d3d9e803961de30

content-type: application/vnd.allegro.public.v1+json;charset=UTF-8

date: Mon, 08 Jun 2020 07:58:28 GMT

x-envoy-upstream-service-time: 64

Content-Length: 5010

 

{"items":{"promoted":[],"regular":[{"id":"7140934580","name":"ADAPTER PIÓRA WYCIERACZKI T4 PINCH TAB 2SZT","seller":{"id":"2722090","company":true,"superSeller":true},"promotion":{"emphasized":false,"bold":false,"highlight":false},"delivery":{"availableForFree":false,"lowestPrice":{"amount":"8.00","currency":"PLN"}},"images":[{"url":"https://a.allegroimg.com/original/039144/ac4f3fce406d964620c419f0d726/ADAPTER-PIORA-WYCIERACZKI-T4-PINCH-TAB-2SZT"},{"url":"https://a.allegroimg.com/original/03b0bd/45c696e340ec9fdc93dd27ab8972/ADAPTER-PIORA-WYCIERACZKI-T4-PINCH-TAB-2SZT-Producent-Alca"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"5.90","currency":"PLN"},"popularity":0},"stock":{"unit":"UNIT","available":994},"category":{"id":"257361"}}]},"searchMeta":{"availableCount":1,"totalCount":1,"fallback":false},"categories":{"subcategories":[{"id":"3","name":"Motoryzacja","count":1}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[{"id":"parameter.11323","type":"MULTI","name":"Stan","values":[{"value":"11323_1","name":"nowe","count":1,"selected":false}]},{"id":"sellingMode.format","type":"MULTI","name":"rodzaj oferty","values":[{"value":"BUY_NOW","name":"kup teraz","count":1,"selected":false},{"value":"AUCTION","name":"licytacje","count":0,"selected":false}]},{"id":"price","type":"NUMERIC","name":"cena","values":[{"idSuffix":".from","name":"od","selected":false},{"idSuffix":".to","name":"do","selected":false}],"minValue":0,"maxValue":1000000000,"unit":"zł"},{"id":"deliveryMethod","type":"MULTI","name":"sposoby dostawy","values":[{"value":"5b445fa0580ce26bb2f99602","name":"Kurier","selected":false},{"value":"5b445fd9580ce26bb2f99608","name":"Kurier wieczór","selected":false},{"value":"5b445fe6580ce26bb2f9960a","name":"Paczkomaty InPost","selected":false},{"value":"5b446004580ce26bb2f9960c","name":"Odbiór w punkcie","selected":false},{"value":"5b446013580ce26bb2f9960e","name":"List","selected":false},{"value":"5b446031580ce26bb2f99610","name":"Paczka","selected":false},{"value":"5b44606c580ce26bb2f99616","name":"Ekspresowa dostawa","selected":false},{"value":"5b446044580ce26bb2f99612","name":"Odbiór osobisty","selected":false},{"value":"5b44605c580ce26bb2f99614","name":"Przesyłka elektroniczna","selected":false}]},{"id":"location.city","type":"TEXT","name":"miejscowość","values":[{"name":"miejscowość","selected":false}]},{"id":"location.province","type":"SINGLE","name":"województwo","values":[{"value":"DOLNOSLASKIE","name":"z dolnośląskiego","selected":false},{"value":"KUJAWSKO_POMORSKIE","name":"z kujawsko-pomorskiego","selected":false},{"value":"LUBELSKIE","name":"z lubelskiego","selected":false},{"value":"LUBUSKIE","name":"z lubuskiego","selected":false},{"value":"LODZKIE","name":"z łódzkiego","selected":false},{"value":"MALOPOLSKIE","name":"z małopolskiego","selected":false},{"value":"MAZOWIECKIE","name":"z mazowieckiego","selected":false},{"value":"OPOLSKIE","name":"z opolskiego","selected":false},{"value":"PODKARPACKIE","name":"z podkarpackiego","selected":false},{"value":"PODLASKIE","name":"z podlaskiego","selected":false},{"value":"POMORSKIE","name":"z pomorskiego","selected":false},{"value":"SLASKIE","name":"ze śląskiego","selected":false},{"value":"SWIETOKRZYSKIE","name":"ze świętokrzyskiego","selected":false},{"value":"WARMINSKO_MAZURSKIE","name":"z warmińsko-mazurskiego","selected":false},{"value":"WIELKOPOLSKIE","name":"z wielkopolskiego","selected":false},{"value":"ZACHODNIOPOMORSKIE","name":"z zachodniopomorskiego","selected":false}]},{"id":"option","type":"MULTI","name":"oferta ma","values":[{"value":"FREE_SHIPPING","name":"darmowa dostawa","selected":false},{"value":"FREE_RETURN","name":"darmowy zwrot","selected":false},{"value":"VAT_INVOICE","name":"faktura VAT","selected":false},{"value":"COINS","name":"Monety Allegro","selected":false},{"value":"BRAND_ZONE","name":"Strefa Marek","selected":false},{"value":"SUPERSELLER","name":"Super Sprzedawca","selected":false},{"value":"CHARITY","name":"Allegro Charytatywni","selected":false},{"value":"SMART","name":"Allegro Smart!","selected":false}]},{"id":"campaign","type":"MULTI","name":"kampania","values":[{"value":"INSTALLMENTS_ZERO","name":"raty zero","selected":false},{"value":"BARGAIN","name":"Strefa okazji","selected":false}]}],"sort":[{"value":"-relevance","name":"trafność","order":"największa","selected":true},{"value":"+price","name":"cena","order":"od najniższej","selected":false},{"value":"-price","name":"cena","order":"od najwyższej","selected":false},{"value":"+withDeliveryPrice","name":"cena z dostawą","order":"od najniższej","selected":false},{"value":"-withDeliveryPrice","name":"cena z dostawą","order":"od najwyższej","selected":false},{"value":"-popularity","name":"popularność","order":"największa","selected":false},{"value":"+endTime","name":"czas do końca","order":"najmniej","selected":false},{"value":"-startTime","name":"czas dodania","order":"najnowsze","selected":false}]}

 

**A tu nie ma:**

 

GET https://allegroapi.io/offers/listing?seller.id=2722090&searchMode=DESCRIPTIONS&phrase=AL%20AD%20PINCH%202SZT&limit=100&offset=0 HTTP/1.1

Accept: application/vnd.allegro.public.v1+json;charset=UTF-8

Content-Type: application/vnd.allegro.public.v1+json

Accept-Language: PL

Authorization: Bearer ...

Api-Key: ...

Host: allegroapi.io

 

 

 

HTTP/1.1 200 OK

server: envoy

trace-id: 3e126bcd09aaa5d2

content-type: application/vnd.allegro.public.v1+json;charset=UTF-8

date: Mon, 08 Jun 2020 08:05:21 GMT

x-envoy-upstream-service-time: 44

Content-Length: 4125

 

{"items":{"promoted":[],"regular":[]},"searchMeta":{"availableCount":0,"totalCount":0,"fallback":false},"categories":{"subcategories":[],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[{"id":"sellingMode.format","type":"MULTI","name":"rodzaj oferty","values":[{"value":"BUY_NOW","name":"kup teraz","count":0,"selected":false},{"value":"AUCTION","name":"licytacje","count":0,"selected":false}]},{"id":"price","type":"NUMERIC","name":"cena","values":[{"idSuffix":".from","name":"od","selected":false},{"idSuffix":".to","name":"do","selected":false}],"minValue":0,"maxValue":1000000000,"unit":"zł"},{"id":"deliveryMethod","type":"MULTI","name":"sposoby dostawy","values":[{"value":"5b445fa0580ce26bb2f99602","name":"Kurier","selected":false},{"value":"5b445fd9580ce26bb2f99608","name":"Kurier wieczór","selected":false},{"value":"5b445fe6580ce26bb2f9960a","name":"Paczkomaty InPost","selected":false},{"value":"5b446004580ce26bb2f9960c","name":"Odbiór w punkcie","selected":false},{"value":"5b446013580ce26bb2f9960e","name":"List","selected":false},{"value":"5b446031580ce26bb2f99610","name":"Paczka","selected":false},{"value":"5b44606c580ce26bb2f99616","name":"Ekspresowa dostawa","selected":false},{"value":"5b446044580ce26bb2f99612","name":"Odbiór osobisty","selected":false},{"value":"5b44605c580ce26bb2f99614","name":"Przesyłka elektroniczna","selected":false}]},{"id":"location.city","type":"TEXT","name":"miejscowość","values":[{"name":"miejscowość","selected":false}]},{"id":"location.province","type":"SINGLE","name":"województwo","values":[{"value":"DOLNOSLASKIE","name":"z dolnośląskiego","selected":false},{"value":"KUJAWSKO_POMORSKIE","name":"z kujawsko-pomorskiego","selected":false},{"value":"LUBELSKIE","name":"z lubelskiego","selected":false},{"value":"LUBUSKIE","name":"z lubuskiego","selected":false},{"value":"LODZKIE","name":"z łódzkiego","selected":false},{"value":"MALOPOLSKIE","name":"z małopolskiego","selected":false},{"value":"MAZOWIECKIE","name":"z mazowieckiego","selected":false},{"value":"OPOLSKIE","name":"z opolskiego","selected":false},{"value":"PODKARPACKIE","name":"z podkarpackiego","selected":false},{"value":"PODLASKIE","name":"z podlaskiego","selected":false},{"value":"POMORSKIE","name":"z pomorskiego","selected":false},{"value":"SLASKIE","name":"ze śląskiego","selected":false},{"value":"SWIETOKRZYSKIE","name":"ze świętokrzyskiego","selected":false},{"value":"WARMINSKO_MAZURSKIE","name":"z warmińsko-mazurskiego","selected":false},{"value":"WIELKOPOLSKIE","name":"z wielkopolskiego","selected":false},{"value":"ZACHODNIOPOMORSKIE","name":"z zachodniopomorskiego","selected":false}]},{"id":"option","type":"MULTI","name":"oferta ma","values":[{"value":"FREE_SHIPPING","name":"darmowa dostawa","selected":false},{"value":"FREE_RETURN","name":"darmowy zwrot","selected":false},{"value":"VAT_INVOICE","name":"faktura VAT","selected":false},{"value":"COINS","name":"Monety Allegro","selected":false},{"value":"BRAND_ZONE","name":"Strefa Marek","selected":false},{"value":"SUPERSELLER","name":"Super Sprzedawca","selected":false},{"value":"CHARITY","name":"Allegro Charytatywni","selected":false},{"value":"SMART","name":"Allegro Smart!","selected":false}]},{"id":"campaign","type":"MULTI","name":"kampania","values":[{"value":"INSTALLMENTS_ZERO","name":"raty zero","selected":false},{"value":"BARGAIN","name":"Strefa okazji","selected":false}]}],"sort":[{"value":"-relevance","name":"trafność","order":"największa","selected":true},{"value":"+price","name":"cena","order":"od najniższej","selected":false},{"value":"-price","name":"cena","order":"od najwyższej","selected":false},{"value":"+withDeliveryPrice","name":"cena z dostawą","order":"od najniższej","selected":false},{"value":"-withDeliveryPrice","name":"cena z dostawą","order":"od najwyższej","selected":false},{"value":"-popularity","name":"popularność","order":"największa","selected":false},{"value":"+endTime","name":"czas do końca","order":"najmniej","selected":false},{"value":"-startTime","name":"czas dodania","order":"najnowsze","selected":false}]}

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam problemu - podczas wywoływania zasobu zawsze otrzymałem 1 ofertę.
Natomiast widzę, że nadal korzystasz z adresu, który już nie jest przez nas wspierany - proszę zmień adres wywołania na https://api.allegro.pl/
Także w postach proszę nie podawaj wartości klucza oraz wygenerowanych tokenów.

**Comment by areklal** [comment]
A dla takiego wywołania też otrzymujecie 1 ofertę? : https://allegroapi.io/offers/listing?seller.id=2722090&searchMode=DESCRIPTIONS&phrase=AL%20AD%20PINCH%202SZT&limit=100&offset=0

**Comment by MaciejFrackowiak** [comment]
Tak, GET /offers/listing?seller.id=2722090&searchMode=DESCRIPTIONS&offset=0&limit=100&phrase=AL AD PINCH 2SZT zwraca 1 dostępną ofertę - 7140934580.

**Comment by areklal** [comment]
Kurczę, coś jest nie tak. raz odnajduje, raz nie. TO dziwne bo problemy zaczęły się dopiero początkiem czerwca. Do tej pory 2 lata korzystamy i było ok. 

Zmieniliśmy adres wywołania, spację zastąpiliśmy %AD i dalej raz wyszukuje, raz nie. A problem jest taki, że taką metodą zmieniamy ceny i mamy aktualnie duży problem. Czy możesz zerknąć na ofertę:

https://allegro.pl/oferta/adapter-piora-wycieraczki-t5-bayonet-lock-2szt-7140934557

Szukamy tej oferty po  frazie : AL AD Bajonet 2szt i niestety dostajemy pusty wynik.
Wyszukanie jej bez filtra seller.id pokazuje ją. 

Czy może mieć na to wpływ fakt, że produkt po ręcznej edycji a poziomu allegro.pl distaje promozycję podpięcia pod produkt w ramach produktyzacji? Wydaje mi się że to nie wpoinno mieć żandego znaczenia.

Dla produktu który ma w opisie : AL AD Top 2szt są wystawione dwie oferty 👍 

https://allegro.pl/oferta/adapter-piora-wycieraczki-t3-top-lock-2-szt-ok-9361444197
https://allegro.pl/oferta/adapter-piora-wycieraczki-t3-top-lock-2-szt-7141084870

i jak już za którymś odpytaniem uda się znaleźć to znajduje tylko z końcówką 197


Z każdym produktem jest tak, że raz odnajdzie, a za 20 sekund już nie odnajdzie. Co może być rpzyczyną, metoda wywołania jest identyczna.

**Comment by areklal** [comment]
Panei Macieju, problem cały czas występuje. Czy możecie go zdiagnozować?? Jeśli problem leż po naszej stronie chociaż nie wydaje mi się to proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Odnośnie oferty 7140934557 - tu nie napotkałem problemu, każdy request kończy się prawidłowym wynikiem.

Natomiast w kwestii AL AD Top 2szt - tu rzeczywiście tej drugiej oferty nie zwraca wyszukiwarkę, problem już przekazałem do właściwego zespołu.

**Comment by areklal** [comment]
U mnie każdy (5 prób w odstępie co 30 sekund) dla frazy AL AD Bajonet 2szt kończy się brakiem wyniku. A powinno odnaleźć ofertę : https://allegro.pl/oferta/adapter-piora-wycieraczki-t5-bayonet-lock-2szt-7140934557

Czy może Pan podać zapytanie jakiego Pan używa do odnalezienia w opisie AL AD Bajonet 2szt ??

Co do tego co Pan nie znalazł to kiedy można zspodziewać się jakiegoś feedbacku z tego zespołu?

**Comment by MaciejFrackowiak** [comment]
Proszę o cierpliwość - zgłoszone przez Ciebie spostrzeżenia są weryfikowane. Zamieszczę odpowiedź, gdy otrzymam wiążące informacje.

**Comment by areklal** [comment]
Oczywiście domyślam się że to nie piekarnia :) Jednak pisze Pan że znajduje Panu ofertę na zapytanie  AL AD Bajonet 2szt  a nawet szukajka główna produkcyjna tego nie znajduje.

**Comment by MaciejFrackowiak** [comment]
Z "AL AD Bajonet 2szt" widzę, że obecnie jest również problem - tu też działamy.

**Comment by areklal** [comment]
ok, no to fajnie że problem potwierdzony. Co do terminu feedbacku to bardziej pytałem z Waszego doświadczenia. Czy to są godziny/dni/tygodnie? :)

**Comment by MaciejFrackowiak** [comment]
Konkretnego terminu nie potrafię wskazać - nastąpi to możliwie szybko.

**Comment by areklal** [comment]
No wybaczcie, chyba możecie w zespole określić kiedy się sprawą zajmiecie i ile to potrwa. Co miesiąc na fakturze z Allegro widnieje usługa "Zapewnienie dostępu do funkcjonalności platformy allegro.pl" więc jakie to jest zapewnienie? Troszkę to nieeleganckie zachowanie.

**Comment by MaciejFrackowiak** [comment]
Nie mogę wskazać jednoznacznego terminu co do daty i godziny - problem nie jest błahy i dokładając wszelkich starań możliwie szybko zostanie usunięty.

**Comment by areklal** [comment]
ok - rozumiem że jakiś zespół rpacuje nad rozwiązaniem tego problemu?

**Comment by MaciejFrackowiak** [comment]
Tak, zgodnie z moim wcześniejszym wpisem:

> zgłoszone przez Ciebie spostrzeżenia są weryfikowane. Zamieszczę odpowiedź, gdy otrzymam wiążące informacje.

**Comment by areklal** [comment]
Witam, czy już wiadomo kiedy naprawicie ten błąd?

**Comment by MaciejFrackowiak** [comment]
Trwają prace programistyczne, których celem jest wyeliminowanie błędu - problem nie dotyczy tylko Twoich ofert, stąd nie jest to działanie punktowe, a na szerszą skalę.

**Comment by MaciejFrackowiak** [comment]
Wymienione przez Ciebie oferty są już widoczne.

**Comment by areklal** [comment]
Potwierdzam, dzięki.
