### ISSUE TITLE
IP is bloked

### ISSUE THREAD

**Issue by artimovskiy** [allegro/allegro-api#3295]
Hi, we get a list of offers via the REST API. But in order to get a description of the offer and "Stan", we have to parse the page. And now our IP 84.201.131.64 is blocked.

Since the beginning of the year, we have made purchases on allegro.pl more than a million zlotys (I can send you the account from which we make all orders, so that you will be convinced of the truth of my words).

And now we can't continue working. What should we do?

**Comment by artimovskiy** [comment]
![изображение](https://user-images.githubusercontent.com/41344076/84037433-e2031080-a99e-11ea-8b3d-81bf4edd183f.png)

**Comment by MaciejFrackowiak** [comment]
Please, contact with us via [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - provide account ID which IP was blocked. Also please add GitHub thread number - 3295.

**Comment by artimovskiy** [comment]
Hi,

we sent contact with you via contact form, but you still no answer after 10 days...

**Comment by MaciejFrackowiak** [comment]
Unfortunately, we haven`t received your message. However, we checked your IP - you should limit your requests to our service. Otherwise, your IP will be blocked automatically again.

**Comment by artimovskiy** [comment]
1. What is the limit value of requests?
2. 84.201.131.64 still is blocked, please remove it from your black list.
3. 28 Nov 2019 We asked you to add a simple functionality to the API so that you can get the description not through parsing, but through the API functionality.

**Comment by MaciejFrackowiak** [comment]
1. This limit is not public available;
2. This IP is not on our blacklist - you send too many requests, so every request extends the time to remove limit;
3. According to [our schedule](https://developer.allegro.pl/en/schedule/) information about that resource will be published in Q3 2020.

**Comment by artimovskiy** [comment]
There are 4 option in Q3:
    ☑ Black list management
    ☑ Event log for user’s offers
    ☑ Delivery settings management
    ☑ User details
None of these items is not mentioned about adding text's ads in RestAPI. Please refine option.

**Comment by MaciejFrackowiak** [comment]
It was for Q3 2019, in Q3 2020 we have:

- Get public data about offers
- Event log for all offers
- Settings and request for withdrawal

**Comment by pszost** [comment]
Same problem here: 178.159.140.208

**Comment by AureliuszBrussy** [comment]
@pszost I checked your IP address. The solution is the same: you should limit your requests to our service. Every request ended with 429 error extend the time to remove the limit.

**Comment by artimovskiy** [comment]
> 
> 
> It was for Q3 2019, in Q3 2020 we have:
> 
>     * Get public data about offers
> 
>     * Event log for all offers
> 
>     * Settings and request for withdrawal

Hi,
what about "Get public data about offers"? Q3 2020 is end.

**Comment by AureliuszBrussy** [comment]
As we [announced](https://github.com/allegro/allegro-api/issues/3377) before, in REST API we will not provide methods for retrieving public data about offers.
