### ISSUE TITLE
Problem z requestem https://allegro.pl/auth/oauth/device dla Device flow

### ISSUE THREAD

**Issue by jan-tyburski** [allegro/allegro-api#3296]
Wybrałem ścieżkę:

Device flow i dla requestu oraz podstawionych danych client_id oraz client_secret ze strony https://apps.developer.allegro.pl/:

curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic base64(client_id:client_secret)' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'

Otrzymuję ciągle błąd:

{"error":"Unauthorized","error_description":"Unauthorized"}
Błąd jest dla client_id = 91602d05dbf648e29171c63e3966f5fa

**Comment by MaciejFrackowiak** [comment]
Proszę podeślij nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) pełen request, który przesyłasz. W zgłoszeniu dodaj proszę nr postu z GitHub - 3296.

**Comment by jan-tyburski** [comment]
Już się wyjaśnił problem, że zamiast:
_base64(client_id:client_secret)_
trzeba wprowadzić już konkretną encodowaną wartość i będzie działać. Dziękuję za szybką reakcję.
