### ISSUE TITLE
Kody kreskowe w zasobach publicznych

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3297]
Dzień dobry,
chciałbym dowiedzieć się w jaki sposób pobrać kod kreskowy (jeżeli oferta go posiada) z oferty której nie jestem właścicielem.

Z góry dziękuję za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości - EAN dostępny jest tylko w zasobie [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
