### ISSUE TITLE
GET /me - puste pola/null 

### ISSUE THREAD

**Issue by monoaminoxydase** [allegro/allegro-api#3299]
Dzień dobry,

Moje pytanie dotyczy endpointu GET /me (https://developer.allegro.pl/documentation/#operation/meGET) - czy któreś pole w zwracanej odpowiedzi może mieć wartość null lub zawierać pusty ciąg znaków? 

Dziękuję z góry za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Jeżeli używasz GET /me dla konta zwykłego to otrzymasz odpowiedź:

```
{
    "id": "123456",
    "login": "Allegro",
    "firstName": "Jan",
    "lastName": "Kowalski",
    "email": "allegro@allegro.pl",
    "company": {}
}
```
