### ISSUE TITLE
Metoda POST /sale/loyalty/promotions zwraca błąd mimo tego dodaje promocję

### ISSUE THREAD

**Issue by jakubkoziara** [allegro/allegro-api#33]
Witam,

Przy użyciu POST /sale/loyalty/promotions na ok 2 tyś aukcji kilka razy miałem przypadek, że metoda zwróciła:
` Error message: HTTP/1.1 504 Gateway Time-out, raw response: 
{"errors":[{
"code":"ServiceTimeoutException",
"message":"Gateway Time-out",
"details":null,
"path":null,"userMessage":"Przekroczono czas wykonania zapytania. Spróbuj ponownie."}]}`

Przy ponownym wywołaniu metody dla tej samej aukcji otrzymuje błąd:

` Error message: HTTP/1.1 422 Unprocessable Entity, raw response: {"errors":[{"code":"BundleAlreadyExistsException","message":"Bundle with offerIds [6804345299, 7195534380] already exists","details":null,
  "path":"\/sale\/loyalty\/promotions","userMessage":"Bundle with offerIds [6804345299, 7195534380] already exists"}]}
`

Wygląda na to, że mimo przekroczenia czasu połączenia zestaw promocyjny i tak jest dodawany.
Proszę o sprawdzenie.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Faktycznie, tak nie powinno być. Błędy powinny być bardziej 'konsekwentne'

Zgłosiłem problem.

**Comment by jakubkoziara** [comment]
Dziękuję.
 Jeszcze zauważyłem, że przy dużej ilości wywołań tej metody pojawia się błąd:
`Error message: Problem with the SSL CA cert (path? access rights?), raw response: false`
Kiedy tak sie stanie występuje on cały czas na wszystkich kolejnych aukcjach(nie da się już dodać żadnej kolejnej promocji). Aby ustąpił trzeba dać chwile przerwy dla API i wszystko wraca do normy (oczywiście wcześniejszy błąd 504 dalej występuje).

**Comment by MaciejPotepa** [comment]
Dzięki za informacje. Pracujemy nad tym, żeby to naprawić. Dam znać jak to wyjaśnimy.
