### ISSUE TITLE
Cenniki dostawy

### ISSUE THREAD

**Issue by malytworca** [allegro/allegro-api#330]
Jak mam wystawić aukcje jak nie mogę utworzyć cennika dostawy, bo w przykładzie nie ma na ten temat nic i nie widzę też nic w dokumentacji?

Mam wchodzić na allegro, żeby utworzyć cennik? Poważnie? To chore. Jak utworzę cennik przez allegro to koniec ze zniżkami na wysyłki. Ceny wrócą normalne. Ktoś musi zapłacić za braki w systemie, a ja nie mam czasu przepisywać ręcznie kilkunastu cenników, bo to miał robić system.

Jak bez tworzenia cennika wystawić aukcje? Jak "ręcznie" wypełnić pola poszczególnych metod wysyłki bez konkretnego cennika?

Stoję z tematem, bo to jakaś paranoja, zero podstaw API, a jednocześnie nacisk na migrację. Przez tę migrację rozwaliłem wszystko co stare, bazy zmodyfikowałem, a tu leżę na jakichś podstawach. W tej chwili kończą mi się ostatnie aukcje i nie planuję wystawiać następnych, bo nie mam na czym. Przywrócić starej wersji nie mogę, bo nie po to TRACĘ czas żeby wracać, a rest api to ciągle pod górkę.

Czy właściciele allegro zdają sobie sprawę, że przez te wszystkie cudowne braki z naciskiem na korzystanie z tych braków, właśnie podnoszą ceny wszystkich produktów? Kto wg was za to zapłaci?

**Comment by masterix** [comment]
Nie wiem czy Cię dobrze zrozumiałem, ale REST API nie udostępnia tworzenia cenników. Teraz jest taki punkt, że część rzeczy jest w WebAPI a część w REST. ID cennika można pobrać tylko, póki co nie ma pobieranie przez REST.

**Comment by malytworca** [comment]
No to ładnie. Brak możliwości edycji i tworzenia cennika w locie to strzał w dziesiątkę. Szkoda słów. Właściwie to miałbym jeszcze kilka pytań, ale przy takim rozwoju rest api i takim nakłanianiu na migrację przy jednocześnie tapk niskim poziomie funkcjonalności w stosunku do webapi i w stosunku do tego co wolno na stronie allegro to sądzę, że szkoda na to życia, żeby jeszcze o cokolwiek pytać. Robię po łebkach. Coraz bardziej jestem przekonany, że allegro powinno za to wszystko zapłacić, bo jak tak dalej będą zmieniać i w takim tempie, to twórcy oprogramowania mają zapewnioną pracę na lata. Szkoda słów. 

Mam wrażenie, że tam pracuje jeden programista, który w nadgodzinach cokolwiek tworzy i to bez wynagrodzenia. W godzinach pracy utrzymuje serwery i odpowiada na pytania. A po godzinach jak jeszcze ma siłę to coś tworzy. To by tłumaczyło tak powolny rozwój rest api, bo napisanie paru wywołań np. POST, które wystarczy tylko połączyć z i tak już istniejącymi elementami to nie wymaga miesięcy pracy, a parę godzin. To by również tłumaczyło tak nędzy poziom dokumentacji, w której aż roi się od niedomówień i to po prostu żenujących (np. przedstawiono parametry typu directory, ale nikt nie wpadł na pomysł przedstawienia typu float o range to już nie wspomnę) oraz błędów (w dokumentacji raz range oznacza, że podajemy zakres od ... do ..., a raz że dane należy podać w określonym zakresie). Po prostu jak to czytałem, to jest to poziom podstawówki. O tych id'kach do wszystkiego i o wszystkim i id'kach tych samych o różnych nazwach to już nie wspomnę. Czytając tę dokumentację mam wrażenie, że ona na id'kach stoi :). Przebili po prostu wszystko! Nawet dokonano cudu! Myślałem, że dokumentacja WebAPI krytykowana za jej poziom będzie nie do przebicia, ale widać tam nikt się niczego nie nauczył.

Gratulacje ekipo allegro! Tak dalej!
