### ISSUE TITLE
Błąd - tworzenie wariantów

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3300]
Podczas tworzenia wariantów dostaje taki komunikat:

**Podany atrybut kolor/wzór nie może zostać dopasowany do istniejących ofert**

**Przykładowe trace id:**
a788ef8540dba8ee
11453f18ce9dbab5
ca94832479034cb9
405be7dd05db28e1

**Comment by MaciejFrackowiak** [comment]
Komunikat ten pojawia się, gdy oferty z identycznym zdjęciem nie mają przekazanej tej samej wartości w polu **colorPattern**.

**Comment by pietrach** [comment]
A może tak być, że już jest wariant, który istnieje i ma takie samo zdjęcie ? Wtedy też taki komunikat się pojawi ?

**Comment by MaciejFrackowiak** [comment]
Nie, to jest komunikat uwzględniający tylko dane przesłane w konkretnym requeście.
