### ISSUE TITLE
problem z aktualizacją ceny poprzez offer-price-change 

### ISSUE THREAD

**Issue by techjaw** [allegro/allegro-api#3301]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Array
(
    [modification] => Array
        (
            [type] => FIXED_PRICE
            [price] => Array
                (
                    [amount] => 41.83
                    [currency] => PLN
                )

        )

    [offerCriteria] => Array
        (
            [0] => Array
                (
                    [offers] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 9239924951
                                )

                        )

                    [type] => CONTAINS_OFFERS
                )

        )

)

---------------------------------------------------------
---------------------------------------------------------
Array
(
    [id] => 4202f6f3-d298-41b5-9688-82d7185c9c12
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
---------------------------------------------------------

Dzień dobry, od 25 maja mam problem z aktualizacją ceny, aktualizacja stanów działa bezproblemowo. Cena pomimo braków błędów pozostaje niezmieniona. Powyżej zapytanie i odpowiedz. Pytanie gdzie szukać problemu? Wykorzystuję offer-price-change.

**Comment by MaciejFrackowiak** [comment]
Widzę, że dla operacji zwracany jest błąd: Uzupełnij parametry obowiązkowe: Kod produktu. - oferta 9239924951 nie posiada określonego tego parametru.

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z GET sale/offer-price-change-commands/4202f6f3-d298-41b5-9688-82d7185c9c12/tasks, a otrzymasz szczegóły:

```
{
    "tasks": [
        {
            "offer": {
                "id": "9239924951"
            },
            "message": "OPERATION_FAILED",
            "status": "FAIL",
            "scheduledAt": "2020-06-09T09:50:41.751Z",
            "finishedAt": "2020-06-09T10:05:20.278Z",
            "field": "price",
            "errors": [
                {
                    "code": "ConstraintViolationException.HasAllRequiredAttributes",
                    "message": "Uzupełnij parametry obowiązkowe: Kod produktu.",
                    "details": null,
                    "path": "attributes",
                    "userMessage": "Uzupełnij parametry obowiązkowe: Kod produktu."
                }
            ]
        }
    ]
}
```

Wskazana oferta jest wystawiona w kategorii 300729, gdzie parametrem obowiązkowym jest Kod produktu - Twoja oferta nie ma go uzupełnionego, stąd błąd podczas zmiany ceny.

**Comment by techjaw** [comment]
Wszystko jasne, dziękuję
Mam jeszcze jedno małe pytanie, czy ten parametr zaczął teraz być wymagany przy wystawianiu aukcji czy przy aktualizacji ceny? Czy problem jest przy aktualizacji bo przy wystawianiu nie był uzupełniony ?

**Comment by MaciejFrackowiak** [comment]
Parametr stał się wymagany dla oferty - Twoja oferta go nie ma, zatem przy próbie wystawienia oferty / jej edycji (w tym ceny) obligujemy użytkownika do określenia wartości parametru.

**Comment by techjaw** [comment]
Wszystko rozumiem, dziękuję i pozdrawiam

**Comment by techjaw** [comment]
Niestety kolejny problem z tym związany, zrobiłem jak mówisz
Wysyłam:
Array
(
    [modification] => Array
        (
            [type] => FIXED_PRICE
            [price] => Array
                (
                    [amount] => 30.37
                    [currency] => PLN
                )

        )

    [offerCriteria] => Array
        (
            [0] => Array
                (
                    [offers] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 9241702858
                                )

                        )

                    [type] => CONTAINS_OFFERS
                )

        )

)
Dostaję:
Array
(
    [id] => 9440bbe6-fab7-4da8-a14b-1e0a2bb5d8c7
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
Sprawdzam:
Array
(
    [tasks] => Array
        (
            [0] => Array
                (
                    [offer] => Array
                        (
                            [id] => 9241702858
                        )

                    [message] => 
                    [status] => NEW
                    [scheduledAt] => 2020-07-04T13:54:24.373Z
                    [finishedAt] => 
                    [field] => price
                    [errors] => Array
                        (
                        )

                )

        )

)
Co robię źle?

**Comment by MaciejFrackowiak** [comment]
Widzę, że zadanie wykonało się - mamy jego status:
```
{
    "tasks": [
        {
            "offer": {
                "id": "9241702858"
            },
            "message": "OPERATION_FAILED",
            "status": "FAIL",
            "scheduledAt": "2020-07-04T13:54:24.373Z",
            "finishedAt": "2020-07-04T13:54:25.051Z",
            "field": "price",
            "errors": [
                {
                    "code": "ConstraintViolationException.HasAllRequiredAttributes",
                    "message": "Uzupełnij parametry obowiązkowe: Marka, Kod produktu.",
                    "details": null,
                    "path": "attributes",
                    "userMessage": "Uzupełnij parametry obowiązkowe: Marka, Kod produktu."
                }
            ]
        }
    ]
}
```
Zmiana ceny nie powiodła się, ponieważ oferta nie posiada określonych parametrów obowiązkowych.

**Comment by techjaw** [comment]
Ok ale czemu ja nie dostałem błędu a Wy tak? Po zmianie ceny odczytałem zgodnie z Waszą sugestią i dostałem to co powyżej? Mam odczekać ?

**Comment by MaciejFrackowiak** [comment]
Tak, to jest zmiana asynchroniczna, której wykonanie wymaga czasu - odpytanie po chwili o status kończy się statusem NEW - jak w Twoim przypadku, czyli zadanie jeszcze się nie wykonało.

**Comment by techjaw** [comment]
Ok po jakim bezpiecznym czasie moge sprawdzać rezultaty?

**Comment by techjaw** [comment]
Przy okazji czy w parametrach różnią się te dwa pola:
                    [required] => 
                    [requiredForProduct] => 
Które pole mówi o tym że parametr jest niezbędny ?

**Comment by MaciejFrackowiak** [comment]
Mamy 60 minut na wykonanie operacji edycji oferty, w zdecydowanej większości przypadków zmiana odbywa się znacznie szybciej.

required - to parametr wymagany przy wystawianiu oferty;
requiredForProduct - wartość true oznacza, że musisz przekazać wartość dla tego parametru, gdy tworzysz propozycję nowego produktu przez [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers).

**Comment by techjaw** [comment]
Co oznacza "tworzysz propozycję nowego produktu", czy przy tworzeniu szkicu a nastepnie aktywacji produktu tem parametr muszę uzupełnić czy nie? Oczywiście za pomocą  POST sale->offers

**Comment by MaciejFrackowiak** [comment]
Zasób POST /sale/offers służy do wystawienia oferty - i dla niego korzystasz z parametrów typu required.

Natomiast zasób POST /sale/product-offers, który pozwala w prosty sposób wystawić ofertę powiązaną z produktem korzysta z oznaczenia "requiredForProduct" - zajrzyj do [naszego poradnika](https://developer.allegro.pl/product_offers/), gdzie opisujemy ten typ wystawiania ofert.

**Comment by techjaw** [comment]
Dzięki serdeczne, wszystko jasne
