### ISSUE TITLE
Cykl wydawniczy danych TecDoc

### ISSUE THREAD

**Issue by baza** [allegro/allegro-api#3303]
Cykl wydawniczy danych TecDoc to 3 miesiące.
Czy Allegro planuje aktualizację danych gdyż 9/19 to już bardzo odległa przeszłość

**Comment by PrzemyslawLukanowski** [comment]
Tak, jak najbardziej planujemy zrobić taki update. Nie mogę jednak na tę chwilę zagwarantować konkretnego terminu.

**Comment by martacronic** [comment]
Nie będę zakładała osobnego wątku, gdyż pytanie jest identyczne. Rozumiem, że na ten moment baza TecDoc Allegro jest nadal z 09/19, więc jest rok różnicy. 

Czy jest już znana data updatu i czy planują Państow systematycznie aktualizować bazę np. kwartalnie?
Czy pracujecie nad jednorazowym updatem i następny może być ponownie w nieznanym odległym horyzoncie czasowym?

**Comment by AureliuszBrussy** [comment]
Ustalam to z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Aktualnie baza TecDoc jest w najnowszej wersji. Od teraz planujemy cykliczne aktualizacje, co kwartał.

**Comment by martacronic** [comment]
Musiał mi umknąć wątek, w którym ta informacja została ogłoszona. Dla mnie jest to bardzo dobra wiadomość. Dziękuję.

**Comment by martacronic** [comment]
Sprawdziłam przed chwilą aukcję spięte z produktami i widnieje wersja 09/19
![image](https://user-images.githubusercontent.com/37405655/95823171-6be82f00-0d2d-11eb-934c-8b4381748c14.png)

Nie do końca rozumiem co powinnam teraz zrobić, żeby produkty były aktualne. Skoro dane w produktach są z TecDoc, to logicznym by było, żeby nowa wersja je nadpisywała. I pytanie symetryczne, czyli co z sekcją "Pasuje do"? Czy co kwartał trzeba będzie wszystko samodzielnie aktualizować?

**Comment by AureliuszBrussy** [comment]
Po aktualizacji TecDoca aktualizujemy dane w produktach, jednak nie nanosimy automatycznie tych zmian w ofertach (nie chcemy nanosić tych zmian bez wiedzy sprzedającego).  Możesz samodzielnie zaktualizować dane produktu - w [poradniku](https://developer.allegro.pl/productization/#offer_update) opisujemy, w jaki sposób to zrobić. Odpowiednia funkcja dostępna jest także w zakładce [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty) -  "Aktualizuj danymi z produktu".
