### ISSUE TITLE
Get the user's orders

### ISSUE THREAD

**Issue by zhu463175790** [allegro/allegro-api#3304]
url:https://api.allegro.pl/order/checkout-forms
params:{"offset":0,"limit":100,"updatedAt.lte":"2020-04-01T00:00:00.000Z","updatedAt.gte":"2020-06-10T00:00:00.000Z"}
return:{"checkoutForms":[],"count":0,"totalCount":0}

Confirm that there is an order, but can not find，
Is there a problem with the request？

**Comment by PrzemyslawLukanowski** [comment]
Could you send us your full request in cURL format with the user id via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)? We need to identify you as a user to verify your issue. Also please add GitHub thread number - 3304.

You can also add in this thread sample checkout-form id which should be included in your response.

**Comment by zhu463175790** [comment]
Already sent
