### ISSUE TITLE
Błąd NotAcceptableException na order/events

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#3305]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Właśnie zauważylem, że moje wywołanie zaczęło zwracać błąd:
GET https://api.allegro.pl/order/events?from=1591771815566882&type=READY_FOR_PROCESSING&limit=100` resulted in a `406 Not Acceptable` response: {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept'

Wcześniej działało cały czas i nic nie było zmieniane. Czy mogę prosić o wyjaśnienie.

**Comment by PrzemyslawLukanowski** [comment]
Wyłączyliśmy dzisiaj wersję beta. Szczegóły znajdziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/3259).

**Comment by copyact** [comment]
A ok,:)
