### ISSUE TITLE
Pytania odnośnie /order/checkout-forms/{id}/fulfillment

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3307]
Mam kilka pytań:
- Do czego jest wykorzystywane pole shipmentSummary.lineItemsSent?
- Czy wymagane jest dokładne ustawianie statusów zamówienia, czy trzeba używać wszystkich statusów? 
- Jak zmiana statusu wygląda od strony kupującego?

**Comment by PrzemyslawLukanowski** [comment]
- w tym polu znajdziesz informację, czy do przedmiotów z zamówienia dołączono numery przesyłek. Obszerniej to pole opisaliśmy w [naszym newsie](https://github.com/allegro/allegro-api/issues/2813).
- nie jest to wymagane, jest to informacja dla sprzedawcy, w jakim statusie aktualnie znajduje się zamówienie,
- jeżeli sprzedawca ma wykupiony [abonament](https://allegro.pl/moje-allegro/sprzedaz/abonamenty), to może ustawić automatyczną wysyłkę do kupującego po zmianie statusu. Zgodnie z poniższym zrzutem:
![Screenshot_29](https://user-images.githubusercontent.com/51473661/84253769-9e301880-ab10-11ea-8a83-dd996ee7b989.png)
