### ISSUE TITLE
Blocked account

### ISSUE THREAD

**Issue by jguthriedodax** [allegro/allegro-api#3308]
Hi,

My test account has been blocked for lack of paying the 'fees'. I've sent the imaginary payment, but the account is still blocked.

Is it possible to unblock it?

(userid: jguthrie100)

**Comment by PrzemyslawLukanowski** [comment]
You account should be unblocked now. Could you please verify it?

**Comment by jguthriedodax** [comment]
Hi, thanks, yes its unblocked
