### ISSUE TITLE
checkout-forms - 406 Not Acceptable

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#3309]
Witam,
dzisiaj dostajemy cały czas: 406 Not Acceptable przy próbie wykonania: https://api.allegro.pl/order/checkout-forms

czy macie jakąś awarię? Jeżeli nie to proszę o informację dlaczego tak się dzieje?
Do wczoraj wszystko działało bez problemu.

Pozdrawiam
Aleksy

**Comment by TinTours** [comment]
U nas dokładnie to samo

**Comment by AleksyZajac** [comment]
Ok, dziękuję za informację.
