### ISSUE TITLE
witam mam błąd z zapytaniem

### ISSUE THREAD

**Issue by artursin** [allegro/allegro-api#3310]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:Błąd w komunikacji z API - {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

**Comment by PrzemyslawLukanowski** [comment]
Czy chodzi o zasoby do obsługi zamówień? Zmień w nagłówkach wartość ‘application/vnd.allegro.beta.v1+json’ n ‘application/vnd.allegro.public.v1+json’. Szczegóły znajdziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/3259).

**Comment by artursin** [comment]
ok dzieki
