### ISSUE TITLE
/payments/refunds INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3311]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, dzisiaj od rana podczas próby złożenia wniosku o zwrot prowizji cały czas dostaje odp INTERNAL_SERVER_ERROR. Czy coś robie nie tak?

POST https://api.allegro.pl/payments/refunds
`{"payment":{"id":"8ae5f361-aae5-11ea-b12f-99a5d9f62b34"},"reason":"REFUND","lineItems":[{"id":"8a8d9a30-aae5-11ea-a3b0-b14b30f5c848","type":"QUANTITY","quantity":1,"value":null}]}`

res:
`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}`

**Comment by PawelTaberski** [comment]
W przypadku tego zamówienia płatność została anulowana i zamówienie jest w statusie "FILLED_IN", dlatego nie możesz zwrócić płatności.
