### ISSUE TITLE
developer.allegro.pl/orders/#anulowanie-zam%C3%B3wienia

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3312]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://developer.allegro.pl/orders/#anulowanie-zam%C3%B3wienia
Treść ważne w ramce, coś zostało z kopiowania.

`WAŻNE! Do końca lipca 2020 możesz wyłączyć opcję anulowania zamówienia dla wszystkich swoich zamówień - zrobisz to na stronie Ustawienia zamówień.my do 60 dni. Po tym okresie usuniemy taki draft. Jeśli zmienisz coś w nim, wydłużymy jego ważność o 60 dni.`

**Comment by PawelTaberski** [comment]
Dzięki za zwrócenie uwagi, poprawimy to przy najbliższym wdrożeniu na stronie.
