### ISSUE TITLE
Fulfillment 504 Gateway Timeout

### ISSUE THREAD

**Issue by MariuszBekus** [allegro/allegro-api#3314]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas próby zmiany statusu zamówienia, za każdym razem otrzymuje błąd 504,  próbuje od kilku dni, aczkolwiek bezskutecznie. Proszę o sprawdzenie.

PUT /order/checkout-forms/{ID ZAMÓWIENIA USUNIĘTE}/fulfillment HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer {TOKEN USUNIĘTY}
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json

fb29ed2cb5cfd4fa

Curl zwraca:

HTTP/1.1 504 Gateway Timeout
trace-id: fb29ed2cb5cfd4fa
content-type: application/json; charset=utf-8
content-length: 167
date: Wed, 10 Jun 2020 12:35:09 GMT

{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}

**Comment by MariuszBekus** [comment]
Czy zmieniło się coś w tym temacie?

**Comment by PawelTaberski** [comment]
Zespół jeszcze pracuje nad rozwiązaniem tego problemu.

**Comment by PawelTaberski** [comment]
@MariuszBekus  Czy mógłbym prosić o wywołanie tego błędu ponownie, najlepiej kilkukrotnie w różnych odstępach czasu?

**Comment by MariuszBekus** [comment]
> @MariuszBekus Czy mógłbym prosić o wywołanie tego błędu ponownie, najlepiej kilkukrotnie w różnych odstępach czasu?

Jasne, przesyłam trace id, za każdym razem to samo, niezależnie od tego jaki status ustawiam:

 504 Gateway Timeout, {"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]} 

Nie wiem, może problem jest po mojej stronie. Jeszcze raz przesyłam nagłówki curla:

**Nagłówek curla:**

PUT /order/checkout-forms/[CHECKOUT_FORM_ID]/fulfillment HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer [TOKEN]
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json

**Payload**

{
"status": "PROCESSING",
    "shipmentSummary": {
      "lineItemsSent": "ALL"
   }
}


**Trace id**

752f05bb6a8dcc09
b189070c4fcda516
8890d39177444d2c
b9223ab5c4630905
22623bbf9d84923e

**Comment by PawelTaberski** [comment]
Dziękuję bardzo, dane przekazałem.

**Comment by MariuszBekus** [comment]
Podbijam bo by się wątek zakończył :)

**Comment by AureliuszBrussy** [comment]
Jeszcze pracujemy nad rozwiązaniem tego problemu. Proszę o jeszcze trochę cierpliwości.

**Comment by webkret** [comment]
Czy coś w tym temacie się dzieje? Pytam, ponieważ jest to kluczowe dla wdrożenia obsługi zamówień.

**Comment by webkret** [comment]
Ja zmieniam tylko status, ale zauważyłem, że kiedy curla wysyłam z programu typu Insomnia jest wszystko ok, a kiedy wysyłam go z aplikacji php-owej postawionej na lokalnym Dockerze, dostaje 504.
Może gdzieś tu leży przyczyna?

**Comment by AureliuszBrussy** [comment]
Weryfikujemy jeszcze źródło problemu - wrócę z odpowiedzią, gdy będę mógł przekazać wiążące informacje.

**Comment by AureliuszBrussy** [comment]
@MariuszBekus prześlij proszę request i response wywołania w formacie curl z przełączoną flagą --verbose. Dane możesz wysłać w wątku (najpierw usuń wrażliwe dane, np. token) lub w całości poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W treści wiadomości podaj proszę numer zgłoszenia na GitHub - #3314. Cz problem występuje jeszcze przy każdym zapytaniu? Czy mogę prosić ponownie o wykonanie kilku takich zapytań pod rząd?

**Comment by MariuszBekus** [comment]
Dzieje się to za każdym razem. Niestety teraz nie otrzymuje żadnej odpowiedzi przy PUT. Nie ma nawet żadnego komunikatu o błędzie, czy kodu http, rezultat z curl_exec jest pusty. Żeby było śmieszniej, to jak zmienię na metodę na POST lub usunę payload, to komunikaty z błędami się pojawiają.

**Przykładowe zapytanie:**

PUT /order/checkout-forms/b97d4aea-f5c5-11ea-a4c3-fd261543e5cb/fulfillment HTTP/2
Host: api.allegro.pl
Authorization: Bearer [TOKEN]
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 64

**Payload:** {"status":"CANCELLED","shipmentSummary":{"lineItemsSent":"ALL"}}


**Jak zmienię PUT na post, to normalnie otrzymuję odpowiedź z trace id:**

HTTP/2 405 
trace-id: b5544c2205497304
content-type: application/json; charset=utf-8
content-length: 147
date: Wed, 23 Sep 2020 08:39:09 GMT
x-envoy-upstream-service-time: 0
server: envoy

{"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed","details":null,"path":null,"userMessage":"An error occurred"}]}

**Comment by AureliuszBrussy** [comment]
Dziękuję za informację, przekazałem je już do odpowiedniego zespołu. Bardzo proszę o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@MariuszBekus czy mógłbyś wykonać wywołanie innym klientem http? Jeśli używasz curla, spróbuj wykonać wywołanie np. w Postmanie lub odwrotnie.

**Comment by MariuszBekus** [comment]
@AureliuszBrussy - podejrzałem request w postmanie i dodatkowo był custom request z wartością PUT. Dodałem i działa :)

curl_setopt($curl, CURLOPT_PUT, true); 
**curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");**
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPHEADER, [
            "Authorization: Bearer " . $token],
            "Accept: application/vnd.allegro.public.v1+json",
            "Content-Type: application/vnd.allegro.public.v1+json"
  ]);
curl_setopt($curl, CURLOPT_POSTFIELDS, $payload);

**Comment by AureliuszBrussy** [comment]
@MariuszBekus dziękuję za informację.
