### ISSUE TITLE
How can I get a list of login based data?

### ISSUE THREAD

**Issue by T0iS** [allegro/allegro-api#3315]
Hello everyone

This question might be rather dumb, but I actually cannot figure it out. 
I managed to successfully get a token and get, let's say, a list of all categories from the API. 

Sadly, I cannot get my offers or new orders by customers at all. 
I guess you need a different kind of authorization, but sadly, I was not able to figure it out by the documentation. 

Could someone send me a code sample of how I could possibly get the list of new orders? 

Thanks for help in advance

**Comment by MaciejFrackowiak** [comment]
You should use code_flow or device_flow authorizations to get orders or offers.
We described whole process in [our tutorial](https://developer.allegro.pl/en/auth/).
