### ISSUE TITLE
Problem z checkoutForms

### ISSUE THREAD

**Issue by marpyc** [allegro/allegro-api#3316]
Mam od wczoraj problem z pobieraniem danych przez Restapi. Do wczoraj przez kilka miesięcy poniższy skrypt działał bez problemu.

	_public static function checkOrders() {
		try {
			$db = (new Database())->getConnection();
			$token = $db->query('SELECT access_token,last_update FROM data ORDER BY id asc LIMIT 1;');
			$token = $token->fetch();
			if($token) {
				$auth = new AllegroOAuth2Client();
				$offset = 0;
				$totalCount = 1;
				$lastEvent = new DateTime(self::getLastEvent());
				$lastupdate = new DateTime($token['last_update']);

				if($lastEvent>$lastupdate || 1==1) {
					$db->prepare('UPDATE data SET last_update = NOW();')->execute();
						$headers[] = 'Authorization: Bearer '.$token['access_token'];
						$headers[] = 'Accept: application/vnd.allegro.beta.v1+json';
					while($offset<$totalCount) {
						$date_lower_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('-7 days'));
						$date_upper_range = gmdate('Y-m-d\TH:i:s.000\Z', strtotime('now'));
						$curl = curl_init($auth->providerSettings['baseUri'].'order/checkout-forms?status=READY_FOR_PROCESSING&limit=100&offset='.$offset.'&lineItems.boughtAt.lte='.$date_upper_range.'&lineItems.boughtAt.gte='.$date_lower_range);
						curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
						curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
						curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'GET');
						$result = ($result = curl_exec($curl)) === false ? false : json_decode($result);
						if ($result === false) {
							throw new Exception('Unrecognized error');
						} else if (!empty($result->error)) {
							throw new Exception($result->error . ' - ' . $result->error_description);
						} else {
							$totalCount = $result->totalCount;
							foreach($result->checkoutForms as $form) {
								try {
..._ 

Aktualnie uruchomienie skryptu powoduje wyświetlenie błędu: Warning: Invalid argument supplied for foreach() in /restapi_pyc_pl/Main.php on line 135
Kontrolnie chciałem sprawdzić co zwraca $result->totalCount i okazuje się, że aktualnie nie zwraca nic. Czy coś od wczoraj zmieniło się z Restapi, czy też może problem jest w moim kodzie? Będę wdzięczny za pomoc.

**Comment by MaciejFrackowiak** [comment]
Musisz zmienić nagłówek z ‘application/vnd.allegro.beta.v1+json’ na ‘application/vnd.allegro.public.v1+json’ - o zmianie informowaliśmy w poście #3259

**Comment by marpyc** [comment]
Działa, dziękuję za pomoc!
