### ISSUE TITLE
Nie można połączyć ofert

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3317]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Kiedy próbuję połączyć oferty w wielowariantowe dostaje komunikat

> {"code":"VALIDATION_ERROR","message":"Oferta wielowariantowa zawierająca oferty z różnymi zdjęciami, musi być połączona po parametrze \"kolor/wzór\"..","details":null,"path":null,"userMessage":"Oferta wielowariantowa zawierająca oferty z różnymi zdjęciami, musi być połączona po parametrze \"kolor/wzór\".."}

Oferty: `9378683381`, `9378683379`, `9378683376`
Mają one te same zdjęcia, więc nie wiem co jest nie tak. Wcześniej nie miałem tego problemu.

**Comment by MaciejFrackowiak** [comment]
Sprawdzamy Twoje zgłoszenie, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Przyczyną problemu są duplikaty ofert - masz po dwie oferty z tym samym rozmiarem tego samego produktu:

rozmiar XS: 9367615326 oraz 9378683379
rozmiar M: 9367615303 oraz 9378683376
rozmiar XL: 9378683381 oraz 9367615370.

Jeżeli miałbyś po 1 ofercie w danym rozmiarze to połączenie rozmiarami nastąpiłoby automatycznie (oferty wystawione zostały w kategorii, dla której włączone jest automatyczne łączenie w oferty wielowariantowe).

**Comment by AnimalDEV** [comment]
Wiem, że mają te same rozmiary, ale nie da się wybrać parametru kolor jako identyfikujący wariant, a one mają inny kolor tylko to samo zdjęcie. Na sandboxie bez problemu mogłem tak połączyć. A chciałem porobić osobne wariantowe grupy dla każdego z unikalnych kolorów. Nie ma na to sposobu?

**Comment by AnimalDEV** [comment]
A dobra nie te oferty spojrzałem, a na sandboxie nie łączy automatycznie w warianty. Te automatyczne łączenie po stronie API więcej szkodzi niż pomaga :smile_cat: . Dziękuję za pomoc.
