### ISSUE TITLE
READY_FOR_PROCESSING 2 różne eventy jedna płatność

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3318]
Mam taką sytuację  2 różne eventy READY_FOR_PROCESSING jedna płatność:
evanty: 1591787497728191,1591787510335400
platnosc: 8f579b02-ab09-11ea-a3b0-b14b30f5c848
czy to normalne?

**Comment by MaciejFrackowiak** [comment]
Tak, możesz otrzymać kilka zdarzeń typu READY_FOR_PROCESSING, dlatego zawsze zwróć uwagę na identyfikator zamówienia w obiekcie checkoutForm - w opisanym przez Ciebie przypadku są identyczne.

**Comment by marcinja2** [comment]
ok dzięki,
