### ISSUE TITLE
Problem z nadaniem numeru przesyłki

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#3319]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

:beetle: **Opis**
Witam, mam problem z ustawieniem numeru przysyłki poprzez zasób https://api.allegro.pl/order/checkout-forms/54a275a1-a912-11ea-b279-51104c5e06d3/shipments

Metodą POST podaje dane:
```
Array
(
    [carrierId] => DHL
    [waybill] => 22248437338
    [lineItems] => Array
        (
            [0] => Array
                (
                    [id] => 54a24e90-a912-11ea-b279-51104c5e06d3
                )
        )
)
```

A w odpowiedzi dostaję:
```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /order/checkout-forms/54a275a1-a912-11ea-b279-51104c5e06d3/shipments
                    [userMessage] => 
                )
        )
)
```

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi - Twój request, który do nas przesyłasz zawiera nieprawidłowy payload, stąd komunikat błędu.
Prawidłowa forma:

```
{
	"lineItems": [{
		"id": "7f1b3861-5d3d-11ea-b28f-abdd22eab30d"
	}],
	"waybill": "1234567890",
	"carrierName": null,
	"carrierId": "DHL"
}
```

**Comment by Himon-SYNCRAFT** [comment]
Dziękuję za szybką informację, ale błąd znalazłem w innym miejscu. Rzeczywiście payload był niepoprawny, ale dlatego, że nie wysyłałem go jako json.

Dziękuję za pomoc
