### ISSUE TITLE
Acces forbidden - after-sales-service-conditions

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#332]
Hi guys,

I'm trying to create a draft to see if I can at least create 1 offer. The problem is I cannot access after-sales-service-conditions API. all 3 routes return access forbidden error message ! 

ex:  GET https://api.allegro.pl/after-sales-service-conditions/implied-warranties?SellerId=xxxxxxx` resulted in a `403 Forbidden` response: {"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":null,"userMessage":"You do not have permissio (truncated...)

If I try other routes, everything works fine (https://api.allegro.pl/sale/delivery-methods, https://api.allegro.pl/after-sales-service-conditions/implied-warranties?SellerId=xxxxx etc.).

What can I do ?

**Comment by LukaszKorek** [comment]
In such situations the most common problem is token. Please check if you are downloading the data to the correct account.

**Comment by crevu** [comment]
Hello,

I decoded the access token and the client ID and Seller ID are correct. Is there any other way for me to verify if the account is correct ?

**Comment by LukaszKorek** [comment]
You should check if you are dowloading access after-sales-service-conditions to the same account.

**Comment by crevu** [comment]
I don't understand what you mean. I use the same access token for all rest API routes, using the same client ID = 87023111ad1e432f9a1e3f8434dc27b

What do you mean by account ?

**Comment by crevu** [comment]
Any news on this ?

**Comment by LukaszKorek** [comment]
you cant download after-sales-service-conditions conditions for all accounts at once. You must be authorized on the account for which you download the conditions

**Comment by crevu** [comment]
I still don't understand why you say I have multiple accounts. What do you mean by account ?
I only have 1 account. And I am authorized because I can use other REST API routes using it. 
From what you are saying I can only speculate that 1 seller ID can have multiple accounts. Where can I see all these accounts ? 

Maybe I'm doing something wrong, can you see any problem in my curl request ? Tell me what must I change in order to make it work

**Comment by LukaszKorek** [comment]
Please send us curl with whole request and response via contact form https://allegro.pl/pomoc/kontakt
