### ISSUE TITLE
Sandbox - no permissions

### ISSUE THREAD

**Issue by IHaveIssuesWithAllegro** [allegro/allegro-api#3320]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hello,
we are trying to test implementation on sandbox but we see this message for about a week now:

Nie możesz jeszcze sprzedawać.
Poczekaj na weryfikację swoich danych. O jej wyniku poinformujemy Cię e-mailem w ciągu 3 dni roboczych.

Ofcourse related methods return error - no permissions.
What can we do to get this fixed so we can work with your sandbox?
Thanks.

**Comment by MaciejFrackowiak** [comment]
Please, give me your account ID or login, I`ll check it.

**Comment by IHaveIssuesWithAllegro** [comment]
Login is "web-media".
Thanks.

**Comment by PawelTaberski** [comment]
Your account is not fully active you should send any 2 files in tab [Moje Konto](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) to end this process.
