### ISSUE TITLE
Offer detailed

### ISSUE THREAD

**Issue by dev-vadym** [allegro/allegro-api#3321]
Hello!
How to get detailed information about the offer by offer id?

**Comment by PawelTaberski** [comment]
If you want to get information about your own offers you can use GET /sale/offers/{offerId}

**Comment by dev-vadym** [comment]
I get an error on GET /sale/offers/{offerId} request - FORBIDDEN

**Comment by dev-vadym** [comment]
> If you want to get information about your own offers you can use GET /sale/offers/{offerId}

No, I want to receive information about other offers.

**Comment by PawelTaberski** [comment]
Public information about offer you will receive by GET /offers/listing, more information about that you will find in our [tutorial](https://developer.allegro.pl/en/listing/).

**Comment by dev-vadym** [comment]
> Public information about offer you will receive by GET /offers/listing, more information about that you will find in our [tutorial](https://developer.allegro.pl/en/listing/).

/offers/listing here I get a list of offers, but I'm interested in the details of the offer itself, an analog of webapi doGetItemsInfo

**Comment by PrzemyslawLukanowski** [comment]
We will provide more details about the future of this functionality in the REST API at the turn of Q2/Q3.
