### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3322]
otrzymuję ten bład przy próbie wysłania jsona metodą PUT na "https://api.allegro.pl.allegrosandbox.pl/sale/offers/6278976754". Json otrzymany metodą GET, zmieniona ilość sztuk. proszę o pomoc

mój Json :

{"id":"6278976754","name":"xiaomi redmi note 5 64 GB","category":{"id":"258234"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["uebdciuybdcbuidcybuicyn"],"rangeValue":null},{"id":"202685","valuesIds":["202685_212929"],"values":[],"rangeValue":null},{"id":"127448","valuesIds":["127448_13"],"values":[],"rangeValue":null},{"id":"202749","valuesIds":[],"values":["20"],"rangeValue":null},{"id":"202869","valuesIds":["202869_214213"],"values":[],"rangeValue":null},{"id":"202865","valuesIds":["202865_214113"],"values":[],"rangeValue":null},{"id":"4388","valuesIds":["4388_1"],"values":[],"rangeValue":null},{"id":"202717","valuesIds":[],"values":["2000"],"rangeValue":null},{"id":"219","valuesIds":["219_128","219_4","219_2","219_64","219_1","219_256"],"values":[],"rangeValue":null},{"id":"202821","valuesIds":["202821_315514"],"values":[],"rangeValue":null}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Lorem Ipsum jest tekstem stosowanym jako przykładowy wypełniacz w przemyśle poligraficznym. Został po raz pierwszy użyty w XV w. przez nieznanego drukarza do wypełnienia tekstem próbnej książki. Pięć wieków później zaczął być używany przemyśle elektronicznym, pozostając praktycznie niezmienionym. Spopularyzował się w latach 60. XX w. wraz z publikacją arkuszy Letrasetu, zawierających fragmenty Lorem Ipsum, a ostatnio z zawierającym różne wersje Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych, jak Aldus PageMaker</p>"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/11145e/8348b8db4d609582e06a8888d27b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"2000","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":null,"stock":{"available":66,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"9840a555-cea7-4001-89a5-d4a00ac9526d"},"handlingTime":"PT24H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"bd337aff-37d1-4597-9891-07598efb3247"},"returnPolicy":{"id":"f06b8f23-a8df-479e-86b3-a35cc58a935c"},"warranty":{"id":"d50eaa74-c78a-4dc2-ae28-6764b6d82b26"}},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"LODZKIE","city":"Łódź","postCode":"91-128"},"external":{"id":"abc"},"attachments":[],"contact":null,"validation":{"errors":[],"validatedAt":"2020-06-08T18:32:43.641Z"},"createdAt":"2020-06-08T18:26:21.000Z","updatedAt":"2020-06-08T18:32:44.480Z"}

**Comment by MaciejFrackowiak** [comment]
Widzę, że udało Ci się już edytować wskazaną ofertę - wklejony json stracił znaczniki, które są niezbędne przy tworzeniu opisu oferty.

**Comment by speedygopl** [comment]
witam, właśnie nie udało mi się zmienić za pomocą aplikacji, tylko zmieniłem dla próby ręcznie.
Jsona przesyłam ze znacznikami, ich tylko nie widać na tej stronie.

**Comment by MaciejFrackowiak** [comment]
Przed momentem pobrałem dane Twojej oferty przy pomocy GET /sale/offers/{offerId}, a następnie wykorzystałem je do edycji mojej testowej oferty przy pomocy PUT /sale/offers/{offerId} - żadnego problemu nie napotkałem, bez przeszkód dokonałem edycji oferty danymi Twojej oferty.
