### ISSUE TITLE
Karta zamówienia

### ISSUE THREAD

**Issue by Lebioda** [allegro/allegro-api#3323]
Czy linki do kart zamówienia generowane są w ten sposób, że jest w nich numer zamówienia? Interesuje mnie link do karty klienta. W ponagleniu o płatność chcę mu wysłać link bezpośrednio do karty zamówienia. Czy taka forma linku będzie poprawna?

NUMER ZAMÓWIENIA
**98e463f4-adb2-11ea-820a-37da43f765be**

Szczegóły zamówienia dla klienta:
https://allegro.pl/moje-allegro/zakupy/kupione/**98e463f4-adb2-11ea-820a-37da43f765be**

Szczegóły zamówienia dla sprzedawcy:
https://allegro.pl/moje-allegro/sprzedaz/zamowienia/**98e463f4-adb2-11ea-820a-37da43f765be**

**Comment by MaciejFrackowiak** [comment]
Tak, to jest poprawna forma odnośników do danego zamówienia (numer zamówienia oczywiście bez **).
