### ISSUE TITLE
Wyróżnienia, darmowe pakiety i naliczanie opłat

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3326]
Witam,
Miałem taką sytuację:
otrzymałem dwa darmowe pakiety wyróżnień po 50 sztuk.
wyróżniłem ręcznie poprzez "moje allegro"
w panelu (centrum zniżek) widniało rozliczenie pakietów:
do jednego zaliczyło mi 51 ofert 
do drugiego 49 ofert
minęło 10 dni,
następnie skryptem przez rest api wyłączyłem wyróżnienia
po przejściu skryptu okazało się, że kilkanaście (nie pamiętam ile) wyróżnień pozostało. wyłączyłem je ręcznie i obsługa skasowała mi naliczone opłaty,
dziś wszedłem w panel i widzę jedną ofertę wciąż wyróżnioną,
czy możecie sprawdzić co się wydarzyło? oczywiście login mogę przesłać przez formularz kontaktowy

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę komplet danych za pomocą naszego [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz Github #3326, będziemy to weryfikować.
