### ISSUE TITLE
Status to inactive

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#3328]
Hi,

Is it possible to change the publication status of an offer to INACTIVE using PUT https://api.{environment}/sale/offer-publication-commands/{commandId} instead of PUT https://api.{environment}/sale/offers/{offerId} ?

Thank you

**Comment by PrzemyslawLukanowski** [comment]
You can't change status to INACTIVE after activating your offers. If your offer is in ACTIVE status, you can only change it to ENDED and it can be done via GET /sale/offer-publication-commands/{commandId}.

**Comment by frenci8** [comment]
How can I delete an offer once it is Active? Does DEL https://api.{environment}/sale/offers/{offerId} delete only draft offers or all offers?

**Comment by PrzemyslawLukanowski** [comment]
It deletes only draft offers. You can only end an active offer - after 60 days it will be removed to our archive.
