### ISSUE TITLE
Wydarzenie na zmianie statusu aukcji na ENDED

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3329]
Czy jest możliwe wysłanie powiadomienia z API do aplikacji w momencie zakończenia aukcji z informacją o zmianie statusu?

**Comment by Radeq** [comment]
Allegro w API nie wysyła powiadomień na Twój endpoint ale może to Ci pomoże

https://developer.allegro.pl/my_offers/#dziennik-zdarzeń-w-ofertach-sprzedawcy

`GET /sale/offer-events?TYPE=OFFER_ENDED`

**Comment by marmited** [comment]
Dzięki, widziałem to, ale myślałem że może istnieje bardziej eleganckie rozwiązanie po stronie API niż bombardowanie zapytaniami  i sprawdzanie czy coś się zmieniło.
