### ISSUE TITLE
Konsultacje na temat edycji atrybutów i tytułów

### ISSUE THREAD

**Issue by fjn-6666** [allegro/allegro-api#3330]
Witaj,
Czy obraz produktu i informacje atrybutowe wspierają edycję za pomocą API?
Czy wszystkie produkty statusu wspierają edycję obrazków i właściwości za pomocą API?
Obecnie edytuję atrybuty i zdjęcia za pośrednictwem interfejsu API, okazało się, że edycja nie działa.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz dokładnie opisać, na czym polega problem? Możesz edytować zdjęcia i parametry w ofercie. Jeśli otrzymujesz błąd przy próbie edycji, prześlij proszę przykładowy request i response za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w zgłoszeniu dopisz GitHub #3330. Logi możesz umieścić także w tym wątku, usuń jednak wrażliwe dane (np. access token).

**Comment by fjn-6666** [comment]
Zmodyfikowaliśmy obraz produktu stanowego aktywna i informacji Waga (Z opakowaniem) za pomocą API, a zwrócone informacje wskazują, że edycja zakończyła się sukcesem.Jednak odpowiednie informacje o produkcie nie uległy zmianie.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, rozumiem zatem problem, jednak bez odpowiednich logów nie mogę wskazać jego przyczyny. Prosiłym o przykładowy request i response, tak jak opisałem to wyżej.

**Comment by wcywangchunyi** [comment]
Halo, chcę zapytać, czy obraz w opisie musi być obrazem w polu "images"?

**Comment by PrzemyslawLukanowski** [comment]
Tak, jeśli chcesz użyć obrazka w opisie, musisz go także przekazać w sekcji "images".
