### ISSUE TITLE
Zmiana ceny w Strefie Okazji

### ISSUE THREAD

**Issue by esprzedaz** [allegro/allegro-api#3331]
Mój klient otrzymał od obsługi Strefy Okazji mailowe pozwolenie na zmianę cen w wybranych ofertach. Jak mam to rozwiązać po stronie API? Po prostu zmienić i niczym się nie martwić? 

Zgodę dostał w zgłoszeniu ref:_00D24aE05._5003V3oZef:ref

**Comment by PrzemyslawLukanowski** [comment]
Aby skorzystać ze Strefy Okazji, musisz zgłosić ofertę do odpowiedniej kampanii.  Zrobisz to za pomocą [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/badges_post). W [naszym poradniku](https://developer.allegro.pl/badge/) znajdziesz szczegółowe informacje na ten temat.  Poniżej przykładowy request, dzięki któremu zgłosisz ofertę do Strefy Okazji:

```
curl -X POST \
‘https://api.allegro.pl/sale/badges’ \
-H 'Authorization: Bearer {token}' \
-H 'Content-Type: application/vnd.allegro.beta.v1+json' \
-d '{
    "campaign": {
        "id": "BARGAIN"             -- wymagane, identyfikator kampanii, jaką 
                                    chcesz dodać do oferty - zgodnie z 
                                    badgeCampaigns.id otrzymanym przez GET /sale/badge-campaigns
    },
    "offer": {
        "id": "6206378062"          -- wymagane, identyfikator oferty, do jakiej 
                                    chcesz dodać kampanię
    },
    "prices": {                     -- wymagane dla kampanii typu DISCOUNT
                                    i SOURCING, informacje o cenie, jaka 
                                    ma być widoczna na ofercie i o cenie rynkowej   
        "market": {                 -- wymagane dla kampanii typu DISCOUNT, 
                                    cena rynkowa za oferowany przedmiot, 
                                    wyświetlimy ją jako przekreśloną na liście ofert    
            "amount": "200.00",
            "currency": "PLN"
        },
        "bargain": {                -- wymagane dla kampanii typu DISCOUNT 
                                    i SOURCING, cena promocyjna oferty
            "amount": "180.00",
            "currency": "PLN"
        }
    },
    "purchaseConstraints": {        -- opcjonalne - ograniczenia zakupowe 
                                    na czas udziału w kampanii
        "limit": {
            "perUser": {
                "maxItems": "1"     -- ograniczenie liczby sztuk dostępnych 
                                    dla pojedynczego użytkownika
          }
        }
    }       
}'
```

**Comment by esprzedaz** [comment]
Fajnie, a coś w sprawie mojego pytania?

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku zmianę ceny możesz wykonać za pomocą [PUT /sale/offers/{id}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT), wprowadzając nową w polu sellingMode.price. Możesz też użyć [PUT  /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) -zasobu, który służy stricte do zmiany ceny. Otrzymałem informację od odpowiedniego zespołu, że taka oferta po takiej zmianie nie zostanie usunięta ze Strefy Okazji.

**Comment by esprzedaz** [comment]
Dziękuję.
