### ISSUE TITLE
Informacje o brakującej wartości parametru podczas zapisu oferty przez API, brak takiej informacji przy edycji przez przeglądarkę

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#3333]
Czy w tym aspekcie również działanie API i strony www różni się od siebie?
Otrzymywany komunikat:

`Brakuje parameteru Kolor (9308) o wartości: "Czarny, Turkusowy" dla oferty z produktem. Kategoria oferty jest różna od kategorii produktu - 86395. Brakuje parameteru Min. długość wkładki (9312) o wartości: "20" dla oferty z produktem. Brakuje parameteru Maks.długość wkładki (9313) o wartości: "22.5" dla oferty z produktem.`

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam inne zachowanie na stronie www. Przekazałem ten przypadek do odpowiedniego zespołu, który go przeanalizuje.

**Comment by tomasz-grzesik** [comment]
Dziękuję za odpowiedź. Przekażę informację Użytkownikowi.

**Comment by PrzemyslawLukanowski** [comment]
Konsultuję ten temat z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by g-michalski** [comment]
A w tym stuleciu?

**Comment by PrzemyslawLukanowski** [comment]
Nadal weryfikujemy ten temat. Gdy będę mógł przekazać więcej informacji, podzielę się z nimi w wątku.

**Comment by PrzemyslawLukanowski** [comment]
@tomasz-grzesik Zmieniliśmy sposób walidacji - aktualnie, jeżeli wybierzesz błędną kategorię dla produktu, zwócimy błąd "ERR_CATEGORY_NOT_FOUND", a na froncie otrzymasz komunikat "Wybrano nieprawidłowy numer kategorii". Jeśli zauważyłeś inne rozbieżności, opisz proszę przykładowy scenariusz.
