### ISSUE TITLE
Lista moich ofert

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#3334]
Chcę napisać mały program ustawiający sygnatury moich ofert zgodnie ze wzorcem. Na razie próbuję pobrać listę moich ofert z Allegor Sandbox. Używam C# i biblioteki RestSharp. Zalogowałem się prawidłowo bo odczytuję listę kategorii. Natomiast jeśli wywołuje https://api.allegro.pl.allegrosandbox.pl/sale/offers?limit=100&offset=0 dostaje błąd Internal Server Error.

**Comment by PrzemyslawLukanowski** [comment]
Ten komunikat jest związany z użytym przez Ciebie typem autoryzacji - prawdopodobnie skorzystałeś z [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Jest to autoryzacja bez kontekstu użytkownika, która pozwala na dostęp tylko do publicznych danych. Jeżeli chcesz pobrać listę swoich ofert, musisz skorzystać z autoryzacji [code_flow](https://developer.allegro.pl/auth/#app) lub [device_flow](https://developer.allegro.pl/auth/#DeviceFlow).  W naszej dokumentacji, przy każdym zasobie, znajdziesz odpowiednie oznaczenie, jaki jest wymagany typ autoryzacji:
- bearer-token-for-user - code lub device flow,
- bearer-token-for-application - client_credentials flow.

**Comment by jmarek-pl** [comment]
Zgadza się. Ponieważ to aplikacja konsolowa użyłem device_flow i coś się udało. Wyświetliło oferty. Ale teraz przy każdym żądaniu muszę po wskazany adres przekazywać user_code. Czy da się podpiąć aplikację tak do konto użytkownika tak aby tego nie wymagała i autoryzowała się automatycznie.

**Comment by PrzemyslawLukanowski** [comment]
Tak, po tym, gdy w odpowiedzi na POST https://allegro.pl/auth/oauth/device otrzymasz m.in device_code, user_code i verification_uri, jako użytkownik powinieneś wejść na stronę, którą zwróciliśmy w verification_uri, i podać user_code. Dzięki temu zautoryzujesz aplikację i nie będziesz musiał wpisywać user_code następnym razem. W następnym kroku Twoja aplikacja powinna użyć POST https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}, na co w odpowiedzi otrzymasz token dostępowy, który da Ci dostęp do zasobów REST API. Token jest ważny przez 12 godzin, możesz jednak [wydłużyć ten czas za pomocą refresh tokena](https://developer.allegro.pl/auth/#refresh-token).

Jeżeli nadal na swojej drodze napotykasz problemy, prześlij proszę przykładowe logi za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433). W zgłoszeniu dopisz GitHub #3334.

**Comment by jmarek-pl** [comment]
Czy każde użycie tokena przedłuża jego ważność o kolejne 12 godz? Jak na razie logowanie działa, pracuję nad dynamicznymi obiektami JSON w C#, biblioteka Newtonsoft.Json.

**Comment by PrzemyslawLukanowski** [comment]
Każde użycie refresh tokena przedłuża ważność o kolejne 12h. Kiedy go użyjesz, w odpowiedzi otrzymasz nową parę access token (ważny kolejne 12h) oraz nowy refresh token. W tym momencie stara para traci już ważność.
