### ISSUE TITLE
Pobranie tokenu użytkownika C#

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3335]
Próbuję używać REST API niestety poległem już na początku. 
Staram się pobrać Token użytkownika, robię to w ten sposób:

Na stronie umieściłem link:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={ID_APLIKACJI}&redirect_uri=http://localhost:56446/Products/AuthorizeAllegroApp

Wszystko ładnie działa, po akceptacji odpalany jest link zwrotny z kodem wygenerowanym przez Allegro, ale pojawia się problem w momencie próby wysłania POSTA w celu pobrania tokena:

        public async Task<ActionResult> AuthorizeAllegroApp(string code)
        {
            string _clientId = "...";
            string _clientSecret = "...";
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = ToAuthHeaderValue(_clientId, _clientSecret);

            var result = await client.PostAsync($"https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri=http://localhost:56446/", null);

            //var result = await client.PostAsync($"https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri=http://localhost:56446/", null);

            return View();
        }

        public static AuthenticationHeaderValue ToAuthHeaderValue(string clientid, string secret)
        {
            return new AuthenticationHeaderValue("Basic", Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes($"{clientid}:{secret}")));
        }

Odpowiedz jaką otrzymuję:

> {StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  transfer-encoding: chunked
  pragma: no-cache
  vary: Accept-Encoding
  age: 0
  content-security-policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp;
  x-content-type-options: nosniff
  grace: none
  x-xss-protection: 1; report=https://allegro.pl/seclog/xss
  x-frame-options: SAMEORIGIN
  strict-transport-security: max-age=15552000
  Cache-Control: no-store
  Date: Wed, 17 Jun 2020 10:31:32 GMT
  Set-Cookie: _cmuid=3ku30qhy-g5ef-5pw7-tcpe-1y7zts0m1h13; Expires=Fri, 17 Jun 2022 10:31:32 GMT; Path=/; Domain=.allegro.pl; Secure
  Content-Type: application/json; charset=UTF-8
}}

Jeżeli zmienię link na sandboxa to dostaję:

> {StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  pragma: no-cache
  vary: Accept-Encoding
  age: 0
  content-security-policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp;
  x-content-type-options: nosniff
  grace: none
  x-xss-protection: 1; report=https://allegro.pl.allegrosandbox.pl/seclog/xss
  x-frame-options: SAMEORIGIN
  strict-transport-security: max-age=15552000
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Wed, 17 Jun 2020 10:30:46 GMT
  Set-Cookie: _cmuid=uj47u1a4-k42p-5xq0-rkjx-q6ez08y77d2g; Expires=Fri, 17 Jun 2022 10:30:46 GMT; Path=/; Domain=.allegro.pl.allegrosandbox.pl; Secure
  WWW-Authenticate: Basic realm="oauth2/client"
  Content-Length: 59
  Content-Type: application/json; charset=UTF-8
}}

W czym może być problem?

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Temat generowania tokena w C# przewinął się w innych wątkach, znajdziesz w nich przykładowy kod:

#935
#1949

**Comment by Aryak2099** [comment]
Napisz do mnie na priva to Ci wyjaśnię
