### ISSUE TITLE
Limit zamykania aukcji

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#3336]
https://api.{environment}/sale/offer-publication-commands/{commandId}

Ile maksymalnie ofert można zamknąć używając jednorazowo powyższego zasobu?

**Comment by PrzemyslawLukanowski** [comment]
W tym zasobie maksymalnie możesz przekazać 1000 ofert. Niezalżnie, czy operacja dotyczy aktywacji czy zakończenia.
