### ISSUE TITLE
[Events] Brak informacji o zmianie ceny

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3338]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o weryfikację poniższych requestów z dzisiaj (oferta nr: 7795450611)
Scenariusz:
- automat zmiena cenę 
- zmiana ceny się udaje
- brak w dzienniku takiego zdarzenia

Chronologia requestów poniżej

REQUEST 2020-06-18 08:27:30.3358266 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU5MjQ2MTEyNTE1OTQxNA&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-06-18 08:27:30.3675938 Duration: 31,7672ms
{
  "Data": {
    "OfferEvents": []
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "170de1b3baef1eaa",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

REQUEST 2020-06-18 08:27:30.6956617 
curl -X GET \
  'https://api.allegro.pl/sale/offer-price-change-commands/213c8172-9eb4-4c67-9e57-7bbe5d411e99' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-06-18 08:27:30.7269103 Duration: 31,2486ms
{
  "Data": {
    "Id": "213c8172-9eb4-4c67-9e57-7bbe5d411e99",
    "TaskCount": {
      "Failed": 0,
      "Success": 1,
      "Total": 1
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "59d1c49c6c5d51a4",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

REQUEST 2020-06-18 08:27:30.7269103 
curl -X GET \
  'https://api.allegro.pl/sale/offer-price-change-commands/213c8172-9eb4-4c67-9e57-7bbe5d411e99/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-06-18 08:27:30.7737885 Duration: 46,8782ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "price",
        "FinishedAt": "2020-06-18T06:24:55.181Z",
        "Message": "",
        "Offer": {
          "Id": "7795450611"
        },
        "ScheduledAt": "2020-06-18T06:24:54.744Z",
        "Status": "SUCCESS",
        "Errors": []
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "4c086e92cb06554f",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

REQUEST 2020-06-18 08:36:36.1038106 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU5MjQ2MTEyNTE1OTQxNA&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-06-18 08:36:36.1507347  Duration: 46,9241ms
{
  "Data": {
    "OfferEvents": []
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "bc6c78d9d08b6b5d",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

REQUEST 2020-06-18 08:38:19.0925770 
curl -X GET \
  'https://api.allegro.pl/sale/offer-events?from=MTU5MjQ2MTEyNTE1OTQxNA&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json,application/json' \
  -H 'Accept-Language: pl-PL' \

RESPONSE 2020-06-18 08:38:19.1394601  Duration: 46,8831ms
{
  "Data": {
    "OfferEvents": [
      {
        "Type": "OFFER_STOCK_CHANGED",
        "Offer": {
          "Id": "8406691473"
        },
        "Id": "MTU5MjQ2MjIxMzQwNzkxOA",
        "OccurredAt": "2020-06-18T06:36:43.198Z"
      },
      {
        "Type": "OFFER_STOCK_CHANGED",
        "Offer": {
          "Id": "7036631855"
        },
        "Id": "MTU5MjQ2MjIxMzUwMjk5Mw",
        "OccurredAt": "2020-06-18T06:36:42.76Z"
      },
      {
        "Type": "OFFER_STOCK_CHANGED",
        "Offer": {
          "Id": "7947956834"
        },
        "Id": "MTU5MjQ2MjIxMzY3ODM3NQ",
        "OccurredAt": "2020-06-18T06:36:42.979Z"
      },
      {
        "Type": "OFFER_STOCK_CHANGED",
        "Offer": {
          "Id": "9102514765"
        },
        "Id": "MTU5MjQ2MjIxNjAzMDA4MA",
        "OccurredAt": "2020-06-18T06:36:45.468Z"
      },
      {
        "Type": "OFFER_STOCK_CHANGED",
        "Offer": {
          "Id": "8963235414"
        },
        "Id": "MTU5MjQ2MjIxNjA3Nzg3NA",
        "OccurredAt": "2020-06-18T06:36:45.532Z"
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "437bb0138a66d279",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by PrzemyslawLukanowski** [comment]
Nie zwróciliśmy eventu, ponieważ cena w ofercie w rzeczywistości się nie zmieniła. Zarówno przed żądaniem dla commandId 213c8172-9eb4-4c67-9e57-7bbe5d411e99, jak i po, wynosiła 103,55zł. Jeżeli wykonasz zmianę cenę na tą samą, w odpowiedzi zwrócimy SUCCESS.

**Comment by SebastianOzdoba** [comment]
ok, dziękuję, zamykam
