### ISSUE TITLE
Problem z pobieraniem danych od 10-06-2020 - wpłat Allegro

### ISSUE THREAD

**Issue by siberjunior** [allegro/allegro-api#3339]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam.
Od 10-06-2020 występuje problem z pobraniem danych - wpłat Allegro .
Do 09-06-2020 działało wszytko dobrze.
Czym spowodowany jest problem ?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem działanie GET payments/payment-operations z użyciem filtra group=INCOME i otrzymałem prawidłowe dane. Prześlij proszę swój login lub id za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=14a4eea0-8c13-4c5f-84d2-aa1b52a06c15&subjectId=7eca6d55-c9cc-4e2a-a37f-4ad0de3c44d9), zweryfikuję, jakie dane zwraca API. W zgłoszeniu dopisz GitHub #3339.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem to - w API prawidłowo zwracamy dane na temat wypłat dla użytkownika ze zgłoszenia. Czy możesz doprecyzować, czym objawia się ten problem? Jakie wykonujesz operacje przez API i jaką otrzymujesz odpowiedź? W naszych logach nie widzę, aby ten użytkownik pobierał od poczatku czerwca jakiekolwiek informacje na temat historii operacji za pomocą GET /payments/payment-operations.

**Comment by siberjunior** [comment]
ostatnie pobieranie danych było 09-06-2020

**Comment by siberjunior** [comment]
> A czy istnieje możliwość że został zablokowany dostęp po przez Rest Api?

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach widzę, że żądania do REST API mają miejsce cały czas (ale dotyczą innych endpointów). Prześlij proszę jeszcze przykładowy request i response w formacie cURL przez nasz formularz kontaktowy. Podobnie jak poprzednim razem, dopisz GitHub #3339. Na tę chwilę możesz nam przekazać informację w wątku, jaki status HTTP otrzymujesz w odpowiedzi.

**Comment by PrzemyslawLukanowski** [comment]
Zwróc uwagę na [ten news](https://github.com/allegro/allegro-api/issues/3259). Czy zmiana nagłówków nie będzie rozwiązaniem Twojego problemu?
