### ISSUE TITLE
Permission error on creating new offer draft

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#334]
Hi guys.

I'm trying to create a new draft, but I get this validation error: 
"You don't have the required permissions to publish offer (sell blocked)"

How can I overcome this problem ?

**Comment by LukaszKorek** [comment]
Please write Your login.

**Comment by crevu** [comment]
My account is europe.operational@thewolfinternational.org
and 
The client ID is 87023111ad1e432f9a1e3f8434dc27bf

**Comment by crevu** [comment]
I tried to create an offer manually (from the browser), and I got an error saying that my account is blocked.

Here is a screenshot : https://ibb.co/euOcfT

**Comment by adityakokate** [comment]
Hello

I'm trying to create a new draft, but I get this validation error:

You don't have the required permissions to publish offer (sell blocked). Verify your account as a company.

How can I overcome this problem ?

**Comment by PrzemyslawLukanowski** [comment]
@adityakokate Are you receiving this error on a Sandbox or production environment?  Please send us your login or sample trace-id so we can verify this problem.

**Comment by adityakokate** [comment]
on got production 
my client id = 0b362d641e7c4ad786c3c1ed7eef0b04

**Comment by PrzemyslawLukanowski** [comment]
Thanks, you have a sell blocked on your account due to an unpaid bill. Please settle it via the [Settlements with Allegro](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) tab.

**Comment by macsanta** [comment]
@PrzemyslawLukanowski @LukaszKorek Hi! Seems like a have the same issue in sandbox.
Username: szybkie_towary
![image](https://user-images.githubusercontent.com/5413700/215134980-54714a2b-3305-4e69-8dce-af97ba31df4b.png)

**Comment by PrzemyslawLukanowski** [comment]
@macsanta Hi, your blockade has been lifted.
