### ISSUE TITLE
Usunięcie oferty przez administrację a wykrycie w REST API / panelu

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3341]
Dzień dobry,

Mam pytanie dotyczące sytuacji w której administrator Allegro usunął/zakończył aukcję np. z powodu niezgodności z regulaminem.

1. Czy w panelu Allegro lub REST API jest widoczna informacja powodzie i zakończeniu aukcji przez administrację?
2. Czy zakończenie aukcji przez administrację  będzie widoczne w dzienniku zdarzeń ofert [ GET /sale/offer-events zdarzenie OFFER_ENDED]?
3. Czy w przypadku blokady konta (np. brak płatności - nie można edytować aukcji) zakończenie aukcji (czas trwania: do wyczerpania przedmiotów) będzie widoczne w dzienniku zdarzeń ofert [ GET /sale/offer-events zdarzenie OFFER_ENDED]?

Numer przykładowej aukcji znajduje się w zgłoszeniu
`"09818342"    [ ref:_00D24aE05._5003V3oVZF:ref ]`

Aukcja została zakończona w godzinach popołudniowych/wieczornych 2020-06-12. Regularnie przetwarzam dziennik zdarzeń i mój skrypt nie wykrył zdarzenia zakończenia dla tej aukcji. Natomiast aukcja była widoczna na liście zakończonych ofert.

Dziękuję i pozdrawiam!

**Comment by PrzemyslawLukanowski** [comment]
>  Czy w panelu Allegro lub REST API jest widoczna informacja powodzie i zakończeniu aukcji przez administrację?

Informacji o powodzie nie udostępnimy, ale w polu endedBy w ofercie zwrócimy wartość "ADMIN".

> Czy zakończenie aukcji przez administrację będzie widoczne w dzienniku zdarzeń ofert [ GET /sale/offer-events zdarzenie OFFER_ENDED]?
> Czy w przypadku blokady konta (np. brak płatności - nie można edytować aukcji) zakończenie aukcji (czas trwania: do wyczerpania przedmiotów) będzie widoczne w dzienniku zdarzeń ofert [ GET /sale/offer-events zdarzenie OFFER_ENDED]?
> 

Tak, powinieneś otrzymać takie zdarzenie. Na podstawie Twojego zgłoszenia udało nam się zlokalizować źródło problemu, dlaczego go nie otrzymałeś. Obecnie zwrócimy już taki event, w polu endedBy również otrzymasz wartość "ADMIN".

**Comment by Radeq** [comment]
Dziękuję za informację
