### ISSUE TITLE
Komunikacja między REST API a Elektronicznym Nadawca (PP)

### ISSUE THREAD

**Issue by likrot** [allegro/allegro-api#3342]
Witam,

mam pytanie, które jest tylko (chyba) pośrednio związane z samym Allegro, ale nie umiem uzyskać nigdzie jednolitej odpowiedzi. Po kolei.

Allegro udostępniło sprzedawcom możliwość rozliczania przesyłek PP bezpośrednio z Allegro. Sklep, którego platformę obsługuję, ma swoją integrację z Allegro. Zgodnie z dokumentacją PP dane do ED są przekazywane w konkretny sposób, tak, aby Allegro było w stanie zidentyfikować wysyłkę/aukcję i ją rozliczyć po swojej stronie.

Jest jednak problem. Allegro nie chce rozliczać w taki sposób przesyłek, nie ważne jakie dane wysyłam.
Przykładowy payload:

```
POST /websrv/en.php HTTP/1.1
Host: en-testwebapi.poczta-polska.pl
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.3.9
Content-Type: text/xml; charset=utf-8
SOAPAction: "http://e-nadawca.poczta-polska.pl/addShipment"
Content-Length: 864
Authorization: Basic <dane>
Cookie: <ciach>;

Body:
addShipment Object
(
    [przesylki] => Array
        (
            [0] => przesylkaBiznesowaType Object
                (
                    [zasadySpecjalne] => 
                    [masa] => 1000
                    [gabaryt] => S
                    [wartosc] => 
                    [ostroznie] => 
                    [numerTransakcjiOdbioru] => 
                    [pobranie] => 
                    [urzadWydaniaEPrzesylki] => 
                    [subPrzesylka] => 
                    [ubezpieczenie] => ubezpieczenieType Object
                        (
                            [rodzaj] => STANDARD
                            [kwota] => 1000
                        )

                    [epo] => 
                    [numerNadania] => 
                    [sygnatura] => 
                    [terminSprawy] => 
                    [rodzaj] => 
                    [adres] => adresType Object
                        (
                            [nazwa] => Stacja PKN Orlen 4359
                            [nazwa2] => 
                            [ulica] => Trakt Lubelski 154
                            [numerDomu] => 154
                            [numerLokalu] => 
                            [miejscowosc] => Warszawa
                            [kodPocztowy] => 04790
                            [kraj] => Polska
                            [telefon] => <ciach>
                            [email] => <email_wygenerowany_przez_allegro>@user.allegrogroup.pl
                            [mobile] => 
                            [osobaKontaktowa] => 
                            [nip] => 
                        )

                    [nadawca] => 
                    [relatedToAllegro] => relatedToAllegroType Object
                        (
                            [id] => <id_allegro>
                            [sellerId] => <ciach>
                            [channel] => REST_API
                            [deliveryMethod] => <uuid_metody_z_tabeli_allegro>
                        )

                    [iloscPotwierdzenOdbioru] => 1
                    [kategoria] => PRIORYTETOWA
                    [guid] => <ciach>
                )

        )
)
```

Pracownicy i konsultanci PP kompletnie nie potrafili wyjaśnić co i dlaczego nie działa. Żeby było śmieszniej, nie jest zwracany żaden błąd, etykieta jest poprawnie generowana, a jedyne (wg konsultanta PP) po czym mogę poznać, że nie jest to ta o którą mi chodzi, to brak kolorowego logo Allegro. Pominę to milczeniem.

Zwróciłem się więc do Allegro, prosząc o sprawdzenie i udzielenie informacji, które wysyłane informacje, są nieprawidłowe lub czego brakuje (w mail podałem guid transakcji). Konkretnej odpowiedzi brak. Moje wiadomości też chyba nie do końca są czytane.

Ponieważ ED nie umożliwia testowania swojej funkcjonalności z Allegro Sandbox, to została utworzona specjalna aukcja, żebym mógł to testować. Został też utworzony nowy cennik, uwzględniający nowe formy dostawy.
Pytałem o tą konkretną aukcję, ale odpowiedzi też nie uzyskałem (a przynajmniej nie na zadane pytania). Nie wiem czy muszę podać coś jeszcze, ale ostatnie zgłoszenie było pod 10082462 i jest tam kilka powiązanych wątków.

Kończąc. W jednej z odpowiedzi jest też informacja, że po prostu powinienem wdrożyć nowy sposób przekazywania informacji do Allegro i czekać. Jeżeli Allegro stwierdzi, że wszystko jest ok, to po prostu aktywuje nowy model rozliczeń… Tylko proszę o infomację typu: proszę wdrożyć i czekać na aktywację - a nie lawirowanie z odpowiedziami.

Pytanie gdzie to można w takim razie testować. Czy mam po prostu coś wprowadzić i liczyć, że będzie działać poprawnie, a Allegro któregoś dnia to uzna. Jeżeli mam tak po prostu zrobić, to proszę o taką informację, bo tego bezpośrednio też nikt mi nie powiedział.
Jeżeli ja robię coś źle, nie umiem itd. to też fajnie byłoby wiedzieć.

W razie czego przekażę oczywiście wszelkie niezbędne informacje.

Wybaczcie rozgorczynie, ale tak się właśnie czuję.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać ID sprzedającego? Jeśli nie chcesz przekazywać tego publicznie, prześlij go proszę za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). Dopisz wtedy w zgłoszeniu #3342.

**Comment by likrot** [comment]
Dzięki za odpowiedź. Wysłałem.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem ten temat - okazuje się, że id sprzedawcy trafiło na naszą czarną listę  dot. nowego modelu rozliczania dla Poczty Polskiej. Powodem mogło być:
- błędne przekazywanie maskowanych adresów mailowych;
- specyfika sklepu, np. nadawanie zamówień tydzień po zakupie przez kupującego.

Jeśli chcesz, aby id sprzedającego zostało usunięte z czarnej listy, wyślij taką prośbę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=6b0fd6c3-e25e-4e61-a1da-ed23df85af7e&subjectId=84e1c27e-ba93-48c2-b237-c3ae940ae06a).

**Comment by likrot** [comment]
1. Czy jesteś w stanie wyłuskać mi takie informacje? Żebym dokładnie to potwierdził? (jak widać w payloadzie nadaję maile prawidłowe, więc chciałbym ewentualnie ustalić z PP co nie tak może być po ich stronie)
2. Transakcje były testowane maksymalnie 2 dni po zakupie. Czy później ponawiałem próby? Musiałbym sprawdzić, ale nie zmienia to faktu, że pierwszy  raz na pewno testowałem w krótkim okresie czasu.

Jeszcze jedno pytanie. Skoro tak łatwo wskoczyć na `blacklist` to w jaki sposób mogę testować poprawność funkcjonowania tej zmiany? (inaczej niż wpuszczając na produkcję i patrzyć co się wydarzy).

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że w payloadzie używasz końcówki @user.allegrogroup.pl - dane w takiej postaci zwracamy na Sandboxie. Na produkcji powinieneś przekazywać  @allegromail.pl.

Po naszej stronie widzę, że nie przekazałeś żadnego maila dla poniższych zamówień. Może to wynikać z powodów opisanych powyżej. Niestety z poziomu wsparcia API nie mam dostępu do logów, aby sprawdzić, czy później ponawiałeś próby:

- 7cd90cc2-95b5-11ea-afa6-ef4999d6df18
- ff0edeb3-96d0-11ea-89c2-25a06a039a4a
- 242102e2-9510-11ea-b8fd-a7c18543ae98
- 02e6bd22-98ff-11ea-9ba8-99c16b2820c6
- 534c6912-956a-11ea-9ba8-99c16b2820c6
- 2a6b6c52-975c-11ea-ae8d-99a27d90bec9
- 73a22612-976c-11ea-b015-b58e7ad614b6

> Jeszcze jedno pytanie. Skoro tak łatwo wskoczyć na blacklist to w jaki sposób mogę testować poprawność funkcjonowania tej zmiany? (inaczej niż wpuszczając na produkcję i patrzyć co się wydarzy).

Weryfikuję jeszcze ten temat.

**Comment by likrot** [comment]
Masz rację z tym mailem. Podesłałem złego loga (testowałem wcześniej z sandboxem), ale sprawdziłem w kodzie i jest ok i tak też idzie (tzn poprawnie, z produkcyjnym mailem allegro).

Co do wspomnianych transakcji, ja się absolutnie zgadzam. One są tak wykonywane ('błędnie'), bo sklep nie ma produkcyjnie podpiętych nowych metod. Cały czas to zaznaczam i staram się uzyskać informację czy jedynym wyjściem po mojej stronie jest wypchanie wszystkich zmian i czekanie na ruch Allegro.
Same metody mi działają, ale nie wiem czy poprawnie działa sam system rozliczeń, czy generowania 'allegrowych' etykiet, bo tego po prostu nie umiem/wiem jak przetestować.

pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Co do trafienia na black listę - sprzedawca powinien wcześniej otrzymać maila, który informuje go o tym, że nie jest jeszcze gotowy na przejście na nowe rozliczenia.
Jeśli przez "testowanie poprawności funkcjonowania tej zmiany" masz na myśli integrację z API PP to niestety z poziomu wsparcia publicznego API Allegro nie mogę więcej pomóc.

**Comment by likrot** [comment]
No dobra, zostawmy PP, bo to rzeczywiście jest ciężko temat.

Czy jeżeli sklep chciałby teraz móc rozliczać się po nowemu, to muszę wprowadzić przekazywanie informacji po `nowemu`, a następnie napisać do Was żebyście odblokowali konto sprzedawcy?

dzięki za odpowiedzi

**Comment by PrzemyslawLukanowski** [comment]
Dokładniej to, żeby usunąć id sprzedawcy z czarnej listy dot. nowego modelu rozliczania dla Poczty Polskiej.

**Comment by likrot** [comment]
Witam ponownie.

Mam prośbę o pomoc, ponieważ klient ciągle przerzuca się wiadomościami z działem obsługi.

Chodzi o tą konkretną transakcję: `20a2fcb2-ad9b-11ea-b18d-3dd87d3b2a8f` .

Została ona przesłana do ED wg ichnich wytycznych oraz zawierając maskowany adres email (osobiście podglądałem komunikację, plus sprawdziłem i w bazie sklepu nie ma innych adresów email dla transakcji pochodzących z Allegro).

W odpowiedzi od Was, klient otrzymał wiadomość, że ta transakcja została błędnie przekazana.
Co to oznacza?
 1. Allegro otrzymało błędne dane wynikowe z ED?
 2. Co w payloadzie się nie zgadza? Ogólne stwierdzenie, że jest źle jest mało pomocne...

Jeżeli prawdziwy jest pkt. 1, w jaki sposób mogę kontrolować dane przekazywane przez ED? I ewentualnie którym zasobem mogę to sobie podejrzeć?

dzięki!

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy ten przypadek - po naszej stronie widzimy, że mail w elektronicznym nadawcy powinien być prawidłowy. Brakuje nam jednak odpytań o niego, co może świadczyć o tym, że PP nie wykonała takiej próby. W tym przypadku sugerujemy dalszy kontakt z PP.

**Comment by likrot** [comment]
Dzięki i dzięki za szybką odpowiedź.
