### ISSUE TITLE
Parametry poszukiwania po Numer oferty (id, sku)  technologia API REST ?

### ISSUE THREAD

**Issue by xirurg303** [allegro/allegro-api#3343]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Witam. jak sformować zapytanie żeby znaleźć towar przez poszukiwanie po **Numer oferty**, zorientowałem się jak szukać metodą frazy i kategorie lecz wtedy frazę szuka tylko w nazwie towaru i opisie, chciało się by zrealizować poszukiwawcze zapytanie po Numer oferty (id, sku) , a także czy być może zadawać parametr poszukiwania po charakterystykom. Nie chciał wykorzystywać technologię WEB API bo ja tak rozumiem ona już nie podtrzymuje się.*

**Comment by xirurg303** [comment]
przeczytałem na nowo całą dokumentację po Rest Api lecz tak i nie znalazł rozwiązania tego problemu. nie mogę zrozumieć jak formować kod zapytania żeby otrzymać w wyniku towar pod (id albo Numer oferty ) znam że przy użyciu Web Api ta możliwość jest ... a w Rest ona jest nieobecna czy prosto nie wniesiona do dokumentacji?

**Comment by PrzemyslawLukanowski** [comment]
Przez REST API możesz wyszukać oferty tylko za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) i dostępnych filtrów:
- category.id,
- phrase,
- seller.id.

Nie możesz pobrać danych oferty na podstawie offer.id.

Możesz wykorzystać offer.id, aby pobrać swoje oferty za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by xirurg303** [comment]
zrozumiale, a wtedy pytanie jak formować zapytanie żeby przy użyciu ( phrase)  frazę szukało nie tylko w nazwie towaru i opisie ale i w charakterystykach ogłoszenia . na stronicy towaru obecny Numer oferty on nie stosuje do pola poszukiwania przy użyciu ( phrase) ?

**Comment by xirurg303** [comment]
> Через API REST ви можете шукати пропозиції лише за допомогою [GET / пропозицій / лістингу](https://developer.allegro.pl/documentation/#operation/getListing) та доступних фільтрів:
> 
> * category.id,
> * фраза,
> * seller.id.
> 
> Ви не можете завантажити дані пропозиції з Offer.id.
> 
> Ви можете використовувати Offer.id для завантаження пропозицій за допомогою [GET / sale / offers / {offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) .

tak rozumiem tej możliwości poszukiwania przy użyciu pola Numer oferty nie będzie u REST API?

**Comment by PrzemyslawLukanowski** [comment]
Więcej informacji na temat przyszłości tego zasobu w REST API opublikujemy na początku Q3. 
W zapytaniu możesz skorzystać także z filtrów, które są widoczne na końca odpowiedzi Twojego requestu. Odpowiadają one filtrom ze strony www. Przykładowe wywołania znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).
