### ISSUE TITLE
Get Offer details

### ISSUE THREAD

**Issue by houssame17** [allegro/allegro-api#3344]
Hello,

How can I get the offer details related to a specific offer which I dont own ?
I tried to use GET /sale/offers/{offerId}, but it return forbidden error.

Is there is any solution for that ? 
if not, are there any plans to add such us functionality? when ?

Thanks in advance.

Best regards
Houssame

**Comment by kvinkinamoto** [comment]
I join I also need this information. through web api there is no possibility, there I so understood already blocked given function.

**Comment by PrzemyslawLukanowski** [comment]
@kvinkinamoto In WebAPI you can use [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,52) and [doShowItemInfoExt](https://allegro.pl/webapi/documentation.php/show/id,342).
@houssame17 We will provide more details about the future of this functionality in the REST API at the beginning of the Q3. Right now you can use [GET /offers/listing
](https://developer.allegro.pl/documentation/#operation/getListing). You can find more information about this resource in [our guide](https://developer.allegro.pl/en/listing/).

**Comment by kvinkinamoto** [comment]
Yes, I tried but it gives an error key is locked

**Comment by PrzemyslawLukanowski** [comment]
@kvinkinamoto This error means there are some issues with your key. Make sure you're using correct data to log in and retrieve the session identifier (sessionHandle). You can send us your logs via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a).  Also please add GitHub thread number - #3344.
