### ISSUE TITLE
Więcej warunków dla filtra fulfillment.status

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3346]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie działąją dwa warunki dla filtra fulfillment.status. Zwraca wyniki tylko dla pierwszego warunku. 
{https://api.allegro.pl/order/checkout-forms?fulfillment.status=NEW&fulfillment.status=PROCESSING}

**Comment by MaciejFrackowiak** [comment]
Problem potwierdzam, przekazałem go już do właściwego działu.

**Comment by MaciejFrackowiak** [comment]
Obecnie zasób nie filtruje po liście statusów - w przypadku wybrania kilku wartości brana pod uwagę jest dowolna z nich. Twoje spostrzeżenie i sugestia sprawiły, że zespół odpowiedzialny za ten zasób niebawem doda możliwość filtrowania po kilku statusach jednocześnie.

**Comment by paafcioc22** [comment]
Super, dacie gdzieś znać jak będzie już działać?

**Comment by MaciejFrackowiak** [comment]
Na pewno wrzucę tu info do posta, a także możliwe, że dodane zostanie info w dokumentacji - temat świeży, więc jeszcze nie znam szczegółów do końca :)
