### ISSUE TITLE
Mapowanie lineItemId i odpowiedź NotFound 

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3347]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuję pobrać dealId poprzez 
{https://api.allegro.pl/order/line-item-id-mappings?lineItemId=101180a2-b44f-11ea-a94e-69ba2a59c040} parametr checkoutform.Id.
![Bez tytułu](https://user-images.githubusercontent.com/49162881/85262232-ca7f5980-b46d-11ea-9c6b-c6c7c88b217d.png)
Sprawdzane dla kilku zamówień - dla każdego zwrotka NotFound.
To błąd czy coś robię nie tak?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie zasobu i zwraca poprawne dane. Proszę podaj mi id zamówienia, do którego przynależy podany lineItemId, wówczas postaram się sprawdzić sytuację u Ciebie.

**Comment by paafcioc22** [comment]
Id zamówienia : 59899033 , lineItemId=101180a2-b44f-11ea-a94e-69ba2a59c040.

**Comment by MaciejFrackowiak** [comment]
Ten numer - 59899033 - to nie jest numer zamówienia z API, niestety po samym lineItemId nie mam jak odszukać tego zamówienia.

**Comment by paafcioc22** [comment]
Korzystam z  REST API, id (to nasze lineItemId?) pobieram z karty checkOut. To gdzie mam szukać nr zamówienia?
![image](https://user-images.githubusercontent.com/49162881/85275665-ee986600-b480-11ea-9d01-808c8d2ec413.png)

**Comment by MaciejFrackowiak** [comment]
W obiekcie lineItems znajdziesz właściwe id, które następnie możesz zmapować na dealId.

**Comment by paafcioc22** [comment]
Dzięki, działa :)
