### ISSUE TITLE
baselinker UPS  Allegro

### ISSUE THREAD

**Issue by iver1987** [allegro/allegro-api#3348]
Witam
Mam problem z kontem Allegro UPS

2. Wygenerowałem klucz api do baselinkera, po konfiguracji wyskakuje info

Próbujesz nadać przesyłkę z odbiorem w punkcie (sekcja 'Odbiór w punkcie' jest wypełniona), ale nie masz uprawnień do nadawania do UPS Access Point poprzez API. Skontaktuj się z opiekunem UPS w celu aktywacji tej usługi.
Komunikat od kuriera: UPS Account is not authorized for Hold for Pickup at UPS Access Point Shipment.

Obsługa UPS przekierował mnie do Was do Allegro , prosze o aktywacje ,
nazwa mojego konta  Numer klienta UPS R324R1
prosze o odpowiedz

**Comment by MaciejFrackowiak** [comment]
Kwestia samej umowy z UPS oraz aktywacji usługi w Allegro znajduje się poza naszym bezpośrednim zasięgiem jako wspacie API. Proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5).

**Comment by dlis2010** [comment]
@iver1987 udało Ci się rozwiązać ten problem?
