### ISSUE TITLE
Mapowanie parametrów i kategorii na wewnętrzny system

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3349]
Aby przyśpieszyć działanie aplikacji  (i nie odpytywać API za każdym razem) chciałbym dodać definicję parametrów po swojej stronie w bazie danych. Czy ID kategorii, parametrów lub opcji parametrów ulegają zmianie? jak w najłatwiejszy sposób monitorować takie zmiany by pobrać nowe dane z API?
Może aktualizacje pojawiają się wyłącznie o jakiejś porze?

**Comment by MaciejFrackowiak** [comment]
Tak, id kategorii, parametrów i dostępnych wartości może ulec zmianie. Dlatego ważne jest bieżące odpytywanie [zasobów](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters) - nie można przyjąć, że raz pobrane dane nie ulegną zmianie, nie ma także żadnych "sztywnych" godzin i terminów zmian.
