### ISSUE TITLE
PUT i https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/{$commandID}

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#3350]
Próbuję aktywować draft oferty i w odpowiedzi dostaje:

[code] => ERROR
[message] => An error has occurred
[details] => 
[path] => /sale/offer-publication-commands/{$commandID}
[userMessage] => 

JSON:
{
    "offerCriteria":[
        {
            "offers":[
                {
                    "id":"6392856754"
                    
                },
                {
                    "id":"6392846754"
                    
                }
            ],
            "type":"CONTAINS_OFFERS"
        }
    ],
        
    "publication":{
        "action":"ACTIVATE"
            
    }
                
}

**Comment by MaciejFrackowiak** [comment]
Wklejony tu JSON wygląda poprawnie. Widzę, że ofertę 6392846754 aktywowałeś już poprzez stronę WWW.

**Comment by ButcherFromHell** [comment]
Tak z panelu konta mogłem aktywować - przez API nie mogę.
Oferty: 6399046754 i 6399106754.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi commandId, którym chciałeś aktywować oferty (ponieważ nie widzę takiego requesta) lub trace-id wywołania.

**Comment by ButcherFromHell** [comment]
Proszę:
commandID: f69820bc-9937-4545-b5ab-2df69740f0b9
i kolejne np: c69bec50-34f2-449d-9ba7-f4ad6fed96d9

**Comment by MaciejFrackowiak** [comment]
Payload z Twoich requestów nie trafia do nas w postaci JSONa - oto przykładowy payload jaki wysyłasz do nas:

`
------------------------------2e06cf9ace0a Content-Disposition: form-data; name="offerCriteria"  Array ------------------------------2e06cf9ace0a Content-Disposition: form-data; name="publication"  Array ------------------------------2e06cf9ace0a-- 
`

**Comment by ButcherFromHell** [comment]
Super - dziękuje za wskazówkę.
json_encode i oferty aktywują się poprawnie.
