### ISSUE TITLE
GET /order/refund-claims z parametrem buyer.login

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3352]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, przy próbie pobrania wniosków o zwrot prowizji dla danego loginu allegro występuję problem - ServiceTimeoutException.

GET https://api.allegro.pl/order/refund-claims?limit=100&buyer.login=markul12

res
`{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}`

podając dwa parametry (id oferty i login kupujacego):
GET https://api.allegro.pl/order/refund-claims?limit=100&lineItem.offer.id=9371432354&buyer.login=markul12

res
`{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}`

Odpytując zasób przez 
GET https://api.allegro.pl/order/refund-claims?limit=100 
GET https://api.allegro.pl/order/refund-claims?limit=100&lineItem.offer.id=9371432354
działa poprawnie, ale podając buyer.login nie działa.

**Comment by MaciejFrackowiak** [comment]
Potwierdzam problem z filtrowaniem wniosków o zwrot prowizji po loginie - przekazałem sprawę już do właściwego działu.

**Comment by MaciejFrackowiak** [comment]
Filtrowanie po buyer.login już działa poprawnie.
