### ISSUE TITLE
[GET] Lista transakcji po Offer.ID

### ISSUE THREAD

**Issue by Krispekowy** [allegro/allegro-api#3353]
Cześć,

Czy w REST API jest możliwość wyszukania listy transakcji po numerze oferty?

Pozdrawiam,
K

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości - ten feature działa tylko na stronie WWW.

**Comment by Krispekowy** [comment]
Ok rozumiem. A czy jest możliwość wyszukania listy transakcji wg jakiegokolwiek filtru? Jeśli nie to czy jest planowana w przyszłości?

Z tego co wiem to na webAPI chyba taka możliwość istnieje - tzn wyszukiwania szczegółów oferty po id oferty i tam mamy dojście do listy transakcji

**Comment by MaciejFrackowiak** [comment]
Rozumiem, że masz na myśli pobieranie publicznych danych o ofercie - informacja o takim zasobie powinna pojawić się w trzecim kwartale 2020 - zgodnie z [naszym harmonogramem](https://developer.allegro.pl/schedule/).

**Comment by Krispekowy** [comment]
Rozumiem. I będzie tam też lista transakcji danej oferty?

**Comment by MaciejFrackowiak** [comment]
Wszelkie szczegóły dot. tego zasobu jak wspomniałem pojawią się w trzecim kwartale 2020.

**Comment by kislukacs** [comment]
Hi,

if I understand correctly, in Q3 2020 there will be new methods through which we will be able to read public offers data. Am I right? How can I read offers data through offers ID?
