### ISSUE TITLE
Powiazanie zwrotów z płatnościami

### ISSUE THREAD

**Issue by MatiKapka** [allegro/allegro-api#3354]
Do pobierania zwrotów korzystam z metody: 
/payments/refunds - otrzymuje listę zwrotów i pytanie jak mam połączyć te zwroty z płatnościami.
Płatności mogły być kilka miesięcy temu i wtedy był krótki IdPłatności, a teraz jest długi IdPłatności.
Jeszcze zapytam się czym różni się metoda /payments/refunds od metody payments/payment-operations z parametrem group ustawionym na "REFUND"?

**Comment by MaciejFrackowiak** [comment]
Zasób do mapowania płatności został przez nas już usunięty - komunikat zamieściliśmy [tu](https://github.com/allegro/allegro-api/issues/3134).

GET /payments/refunds zwraca tylko listę dokonanych zwrotów płatności. Natomiast GET /payments/payment-operations zwraca całą grupę REFUNDS (obciążenie z tytułu zwrotu,  anulowanie zwrotu, zwiększenie zwrotu.)
