### ISSUE TITLE
Problem z przesłaniem oferty, nic nie mówiący błąd

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3355]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry,
Mógłbym prosić o sprawdzenie poniższego trace-id zwracany jest następujący błąd {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]} oraz chyba zdjęcie nie jest prawidłowo przesyłane, Object not found 
trace-id: 12093289b8033edd

**Comment by MaciejFrackowiak** [comment]
W logach widzę 400, jednak payload do nas już nie dotarł, dlatego ciężko mi więcej napisać na podstawie samego loga.

**Comment by pawelosajda** [comment]
przed chwilą przesłałem to zdjęcie
https://a.allegroimg.com//original//11936e//54bb3d04464e9f29373cb3795b24
dlaczego przy próbie wyświetla wyświetla się Object not found.?
