### ISSUE TITLE
Checkout form status po zwrocie prowizji

### ISSUE THREAD

**Issue by mstrzyzewski** [allegro/allegro-api#3356]
Jeżeli kupujący nie zapłaci za zamówienie w ciągu 7 dni i sprzedający złoży wniosek o zwrot prowizji, który zostanie rozpatrzony pozytywnie, to czy status checkout_form zmieni się na CANCELLED i będzie nowy event?

Nie mogłem znaleźć odpowiedzi na moje pytanie w dokumentacji, ale jeżeli coś przeoczyłem, to proszę o podanie linka :)

**Comment by MaciejFrackowiak** [comment]
Nie, zwrot prowizji nie zmienia statusu checkoutForm, nie generuje się też nowy event.

**Comment by cieslix** [comment]
@MaciejFrackowiak kiedy zamówienie nieopłacone zostanie anulowane ? Czy sprzedający może w jakiś sposób zmienić status  zamówienia na anulowane tak żeby CheckoutForm otrzymało status `CANCELLED` ?

**Comment by MaciejFrackowiak** [comment]
CheckoutForm otrzyma status CANCELLED tylko w sytuacji, gdy kupujący [anuluje zakup](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/anulowanie-zakupu-informacje-dla-sprzedajacych-KMOZGKlO5fR). Samo przyznanie zwrotu prowizji nie zmienia statusu checkoutForma. Jako sprzedający możesz natomiast zmienić [status realizacji](https://developer.allegro.pl/orders/#zmiana-statusu-realizacji-zam%c3%b3wienia) takiego zamówienia - wówczas możesz je oznaczyć jako CANCELLED (anulowane).

**Comment by cieslix** [comment]
@MaciejFrackowiak jako sprzedawca status zamówienia mogę dowolnie zmieniać z nowego/w realizacji/wysłanego/do wysłania/anulowanego i z tego co kojarzę, to klient może opłacić zamówienie, które oznaczę jako anulowane. Z drugiej strony potrzebujemy otrzymać "wpis w dzienniku zdarzeń dla zamówień", które będzie jasno identyfikowało, że zamówienie zostało przez nas anulowane - jest to niezbędne aby zwolnić zarezerwowany produkt w sklepie.

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak - status oznaczony przez Ciebie może być niezgodny ze stanem faktycznym, czyli np. anulowane, a kupujący dokonał zapłaty. Takiego eventu - stricte oddającego Twoje wymagania - w [dzienniku zdarzeń](https://developer.allegro.pl/orders/#dziennik-zdarze%c5%84) nie mamy.

**Comment by cieslix** [comment]
@MaciejFrackowiak czy w takim razie jest możliwe po stronie Allegro dodanie nowego statusu w dzienniku zdarzeń, że zamówienie zostało anulowane przez sprzedającego ? Pewnie wiązałoby się to dodatkowo z zablokowaniem opcji opłacenia przez kupującego.

**Comment by MaciejFrackowiak** [comment]
Nie mamy takiej funkcjonalności w Allegro, w związku z tym REST API musi być w pełni zgodne z tym co jest dostępne na stronie WWW. Twoją sugestię w tej kwestii przekażę do osób odpowiedzialnych za rozwój REST API.

**Comment by cieslix** [comment]
@MaciejFrackowiak dziękuję :)
