### ISSUE TITLE
Brak zakończonej aukcji w sale/offers (aukcja ukryta w panelu)

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3358]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Aukcja x została zakończona w Allegro. Nie jest w archiwum - dalej widoczna na stronie Allegro. Nie jest widoczna na liście zakończonych aukcji (mam jedną stronę wyników) i prawdopodobnie nie była widoczna w dzienniku zdarzeń ofert.

Dotyczy aukcji
`GET sale/offers/{id}? || trace-id:cc4315b7ef6aa498`
Oraz listy 
`GET sale/offers?limit=500&offset=0&publication.status=ENDED&sellingMode.format=BUY_NOW || trace-id:e0c716a04f062f1`

```
    "publication" => {
      #container: array:6 [
        "duration" => null
        "ending_at" => null
        "starting_at" => null
        "status" => "ENDED"
        "ended_by" => "USER"
        "republish" => false
      ]
    }
    "updated_at" => DateTime {
      +"date": "2020-06-20 06:46:05.641000"
      +"timezone_type": 2
      +"timezone": "Z"
    }
```

Proszę o informację dlaczego aukcja nie jest widoczna?

Klient mówi, że mógł ukryć aukcje z poziomu strony Allegro - czy to wpływa na REST API?

**Comment by MaciejFrackowiak** [comment]
Tak, ta oferta 92xxxxx787 została ukryta z poziomu WWW, zatem GET /sale/offers również jej nie zwróci. Natomiast cały czas jest dostępna dla GET /sale/offers/{offerId}.

**Comment by Radeq** [comment]
@MaciejFrackowiak , mam pytania:

1. czy jest możliwość włączenia wyszukiwania po ofertach ukrytych w dzienniku zdarzeń ofert / liście zamówień?
2. czy jak użytkownik ukryje aukcję aktywną to może ją potem odkryć?
3. czy powyższa funkcjonalność jest opisana w dokumentacji (nie mogę znaleźć)?

**Comment by MaciejFrackowiak** [comment]
1. Nie ma takiej możliwości;
2. Nie, nie ma opcji jej przywrócenia;
3. To feature dostępny tylko z poziomu WWW - opisany w [Pomocy](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/moje-oferty-lista-sprzedawanych-ofert-5VZjLom02s9#jak-ukryc-zakonczone-oferty).

**Comment by Radeq** [comment]
Dziękuję za odpowiedź.

Dla zainteresowanych: zrobiłem testy na sandbox i wygląda to tak:

1. można ukryć tylko zakończoną aukcję:
 - nie będzie widoczna na liście zakończonych aukcji w panelu użytkownika 
- nie będzie widoczna REST API w sale/offers?publication.status=ENDED
- będzie widoczna w zdarzeniach GET /sale/offer-events
- jest widoczna na stronie allegro
- można ją wznowić z szczegółów aukcji lub znając link `https://allegro.pl/offer/{id}/start`
- można ją wznowić przez REST API
2. jej wznowienie spowoduje odkrycie - po zakończeniu trzeba ją na nowo ukryć
