### ISSUE TITLE
Problem z publikacją oferty url.

### ISSUE THREAD

**Issue by potockit** [allegro/allegro-api#3359]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mam problem z publikacją oferty, gdzie odwołanie do obrazu jest prawidłowe po naszej stronie. Mimo tego, nie może opublikować danej oferty. 
Zdjęcie z danego adresu wyświetla się prawidłowo w przeglądarkach i jest dostępne publicznie. 

Po uploadzie zwracany jest komunikat 

{\"errors\":[{\"code\":\"DownloadInvalidUrl\",\"message\":\"Invalid URL '<adres_obrazka>'.\",\"details\":null,\"path\":null,\"userMessage\":\"Niepoprawny adres URL: '<adres_obrazka>'.\"}]}\n

trace-id: 824cc05703f0911a

**Comment by MaciejFrackowiak** [comment]
Weryfikuję opisaną przez Ciebie kwestię, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, wczoraj podczas upload`u zdjęcia pojawiał się problem z DNSami domeny. Dzisiaj problem ustąpił - bez przeszkód udało mi się załadować zdjęcie z adresu, który podałeś w swoim requeście.
