### ISSUE TITLE
Offer location - detailed explanation

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#336]
Hello,

I want to create a new draft and I need to fill in the location section in order to pass validation.

Is this field referring to
A) where we will ship the products (Poland and all other available countries) 
     OR
B) where we - as a company- are located (Romania) ?

In the documentation, this section looks like this : 

"location": {
        "countryCode": "PL",
        "province": "WIELKOPOLSKIE",
        "city": "Poznań",
        "postCode": "60-166"
    },

Can you give me a complete example (In case location refers to A) ) ?
P.S. We can deliver to every country in the Delivery settings list.

Thank you !

**Comment by LukaszKorek** [comment]
Hello. I suggest issuing a trial offer by the www  editor, and then download the fields of the offered offer using  [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#!/offer/getOfferUsingGET) - in this way you will receive complete example.

**Comment by crevu** [comment]
Thank you, it seems it was B)
