### ISSUE TITLE
Blokada adresu IP przy odczytywaniu https://allegro.pl

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3362]
Doznałem blokady IP podczas odpytywania https://allegr.pl/xxxx.
Teraz otrzymuję http-code:429.
Czy blokada jest czasowa?
Jak ją zdjąć?
KF

**Comment by MaciejFrackowiak** [comment]
Tak, blokada jest czasowa - odczekaj przed wysłaniem kolejnych zapytań, wówczas sama zniknie.

**Comment by kfijalko** [comment]
juz zdjęta - pozdrawiam,kf
