### ISSUE TITLE
Czy limity powinny być per ClientID?

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#3363]
Hej!

Czy limity powinny być per ClientID?

Załóżmy że tworzę aplikację którą będzie używać 9001 osób.
Aplikacja po odpaleniu wysyła 1 zapytanie do rest api na sekundę.

Jeśli dobrze rozumiem, w takim przypadku zapytania będą blokowane, bo został przekroczony limit 9000 zapytań na minutę.

Czy jedynym rozwiązaniem jest wygenerowanie kilku (w większej skali kilkuset/kilku tysięcy) ClientID i przypisywanie ich losowo do aplikacji?

**Comment by MaciejFrackowiak** [comment]
Obecna wartość limitu (9000 req/min) nie jest przypadkowa - ustalona na podstawie posiadanych przez nas danych, przy zoptymalizowaniu funkcjonowania aplikacji bez przeszkód pozwala na prawidłowe (zgodne z limitem) działanie użytkowników. Z naszej strony sugerujemy rozwiązanie opierające się na jednym ClientID - aby to nim "przedstawiała się" aplikacja.

**Comment by jakubmaguza** [comment]
Zgadzam się, że użycie jednego ClientID byłoby najlepszym rozwiązaniem, ale co w przypadku który podałem wyżej?
Załóżmy użycie, gdzie mam 10 klientów i każdy z nich chce sobie zbierać statystyki, więc odpytuje co chwilę dziennik + dla nowych przedmiotów zwróconych przez dziennik odpytuje API o informację o tych przedmiotach.

W niedzielę wieczorem nowych przedmiotów pojawia się cała masa i myślę że liczba zapytań na minutę spokojnie może przekroczyć 1000.

Czy w takim przypadku jedynym rozwiązaniem jest wygenerowanie ClientID per użytkownik/grupa użytkowników?

**Comment by MaciejFrackowiak** [comment]
Naprawdę podajesz mocno skrajny przypadek - działania standardowego użytkownika nie wpisują się w takie działanie, stąd "ciężko" przekroczyć limit przy zgodnym ze sztuką korzystaniu z REST API. Kluczem jest zoptymalizowanie aplikacji, aby nie przekraczała dostępnego limitu wywołań.

**Comment by jakubmaguza** [comment]
Podałem skrajny przypadek, bo ze skrajnym przypadkiem się spotkałem.
W każdym razie otrzymałem już odpowiedź, dziękuję :)
