### ISSUE TITLE
Nie można połączyć oferty w wariant

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3364]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zadawałem kiedyś podobne pytanie (#3317), ale teraz nie mogę znaleźć powodu dlaczego nie mogę połączyć w wariant oferty.
Oferty mają te same zdjęcia i są identyczne poza parametrem rozmiar, który się różni. Kiedy próbuję stworzyć wariant przez API jak i przez front nie mogę połączyć ich w warianty. Z komunikatem:

> Oferta wielowariantowa zawierająca oferty z różnymi zdjęciami, musi być połączona po parametrze "kolor/wzór"..

Nie wydaje mi się, że nie powinno dać się tego połączyć, albo komunikat jest nie odpowiedni.

Oferty: `6452816754`, `6452816758`, `6452836754`

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem podane przez Ciebie oferty - widzę, że masz dla nich utworzone duplikaty:

1) 6452816754 - 6452816757
2) 6452816758 - 6452826754
3) 6452836754 - 6452836755

Dodatkowo, oferty znajdują się w osobnych zbiorach:

A) 6452816757, 6452836755, 6452816758
B) 6452826754, 6452816754, 6452836754

**Comment by AnimalDEV** [comment]
To nie są duplikaty ponieważ mają inną wartość parametru kolor, a nie mogę po zdjęciu połączyć bo wszystkie kolory mają takie same.

**Comment by MaciejFrackowiak** [comment]
Wskazane przez Ciebie oferty mają takie same zdjęcia, zatem wraz z określonymi je rozmiarami tworzą duplikaty. Dla każdego koloru dodaj osobne zdjęcie, wówczas unikniesz tego problemu (de facto uprościsz kupującemu wybór, gdy zobaczy foto z np. czarną koszulką odpowiadającą kolorowi czarnemu, a nie np. białemu).

**Comment by AnimalDEV** [comment]
Problemem jest to, że w danych produktów które otrzymuje nie ma podziału na "które zdjęcie dla którego wariantu", więc myślałem, że mogę sobie pogrupować bez wariantowych zdjęć.

**Comment by MaciejFrackowiak** [comment]
Takie podejście przy wariantowaniu jest utrudnieniem dla kupujących - na podstawie miniaturki nie mają możliwości stwierdzić, czy w danej ofercie jest dostępny np. czerwony czy zielony t-shirt.
