### ISSUE TITLE
wielowariantowość w odzież / stroje / kostiumy

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#3365]
Przy próbie utworzenia wielowariantowości przez RESTAPI w ten sposób:
```
{
  "offers": [{
      "id": "8222409162",
      "colorPattern": "S45527"
    },{
      "id": "8222442632",
      "colorPattern": "S45527"
    },{
      "id": "8311728485",
      "colorPattern": "S45527"
    }
  ],
  "name": "strój zakonnica 2020",
  "parameters": [
    {
        "id": "color/pattern"
    },{"id": "54"}
  ]
}
```
Dostaję taki błąd:
```
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => VALIDATION_ERROR
                    [message] => Given color pattern does not match existing offers: 8222409162, 8222442632, 8311728485.
                    [details] => 
                    [path] => 
                    [userMessage] => Given color pattern does not match existing offers: 8222409162, 8222442632, 8311728485.
                )
        )
```

Czy ktoś ma pomysł dlaczego ? Dodam, ze skrypt działa i gdy w identyczny sposób wysyłam żądanie wielowariantowości w kategorii ze strojami dla dzieci podając odpowiednio ID:7153 a nie ID:54 wszystko jest OK i wielowariantowość się tworzy. Dlaczego nie mogę utworzyć na trzech w/w ofertach ?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem Twoje oferty - powodem błędu są różne zdjęcia przy tych ofertach (one pozornie wyglądają tak samo).

**Comment by partyumarty** [comment]
Zwracam honor, działa... przydała by się informacja, o zmianach w algorytmie, bo wszystkie oferty, które dzisiaj sprawiają problem - kiedyś działały... no nie mniej jednak faktycznie po wgraniu identycznego zdjęcia - udało się spiąć :) Dziękuję za pomoc.
