### ISSUE TITLE
Get single offer info endpoint

### ISSUE THREAD

**Issue by joel-a11y** [allegro/allegro-api#3366]
Hello,

I've researched REST API documentation and hadn't found endpoint that would allow to get any offer info by ID (analog of WebAPI doShowItemInfoExt). Have I missed something or there is no such endpoint?

Thank you in advance for reply

**Comment by kfijalko** [comment]
there is no such endpoint

**Comment by MaciejFrackowiak** [comment]
@joel-a11y You can use [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) to retrieve public offer information (of course you cannot use offer ID, but using e.g. phrases you will receive search results).

**Comment by joel-a11y** [comment]
Thank you for response! Could you clarify please, is using WebAPI for such a request the only option as for now? Thank you!

**Comment by MaciejFrackowiak** [comment]
@joel-a11y Yes, it is the only option till September 30th, 2020 when this [WebAPI method will be removed](https://github.com/allegro/allegro-api/issues/3377).
