### ISSUE TITLE
Polskie znaki w response od tygodnia z błędami.

### ISSUE THREAD

**Issue by pam83** [allegro/allegro-api#3367]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/order/events?limit=500

Response:
{"events":[{"id":"1593120597834442","order":{"seller":{"id":"34107637"},"buyer":{"id":"43451854","email":"gf9mv10qho+7dcd5dfa0@allegromail.pl","guest":false,"login":"Tresor_1508"},"lineItems":[{"offer":{"id":"9346642022","name":"ZESTAW **GARNKA?W** EMALIOWANYCH BALBINA KREMOWE 8EL","external":null},"price":{"amount":"302.00","currency":"PLN"},"id":"cefb3320-b72a-11ea-b356-97609f52057c","quantity":1,"originalPrice":{"amount":"302.00","currency":"PLN"},"boughtAt":"2020-06-25T21:29:45.702Z"}],"checkoutForm":{"id":"cefb3322-b72a-11ea-b356-97609f52057c","revision":"2a40f1fb"}},"type":"BOUGHT","occurredAt":"2020-06-25T21:29:45.702Z"},{"id":"1593120599051984","order":{"seller":{"id":"34107637"},"buyer":{"id":"43451854","email":"++++++++0@allegromail.pl","guest":false,"login":"+++++_1508"},"lineItems":[{"offer":{"id":"9346642022","name":"ZESTAW GARNKA?W EMALIOWANYCH BALBINA KREMOWE 8EL","external":null},"

Od około tygodnia mam problem z odpowiedzią. Polskie znaki nie są zwracane poprawnie. 
np. SZPATUAKA  zamiast SZPATUAŁKA 

Nic nie zmieniałem w programie wysyłającym zapytania.

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam opisanego przez Ciebie problemu - bez przeszkód zwracamy w response polskie litery, nie dokonywaliśmy też żadnych zmian w tym zasobie, przykład:

```
"lineItems": [
                    {
                        "offer": {
                            "id": "xx63876754",
                            "name": "test nagłówka róża międź żópań",
                            "external": {
                                "id": "abc"
                            }
                        },
                        "price": {
                            "amount": "1.00",
                            "currency": "PLN"
                        },
                        "id": "b2597710-b791-11ea-bdae-41b5c103c423",
                        "quantity": 1,
                        "originalPrice": {
                            "amount": "1.00",
                            "currency": "PLN"
                        },
                        "boughtAt": "2020-06-26T09:45:10.011Z"
                    }
                ],
```

**Comment by NM97** [comment]
Również napotkaliśmy się na ten problem, dokładnie od tygodnia są problemy z polskimi znakami. Allegro nie poinformowało o jakiś zmianach, dlatego też szukaliśmy problemu po swojej stronie. Jednak widzę, że nie jesteśmy jednymi użytkownikami, którzy napotkali się na ten problem.

**Comment by MaciejFrackowiak** [comment]
@pam83 @NM97 Proszę podeślijcie pełny request, który do nas wysyłacie - najlepiej poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) podając w treści numer posta z GitHub`a.

**Comment by NM97** [comment]
Proszę o informacja jaki dokładnie system kodowania znaków został użyty w przypadku requestów.

**Comment by pam83** [comment]
> numer posta z GitHub`a.

wysłane

**Comment by MaciejFrackowiak** [comment]
@NM97 Request, który zwraca polskie znaki:

```
curl --location --request GET 'https://api.allegro.pl/order/events?limit=1000' \
--header 'Authorization: Bearer (token) \
--header 'Accept: application/vnd.allegro.public.v1+json' 
```

@pam83 Dziękuję, zapoznam się z nim, gdy zostanie do nas przekierowany.

**Comment by MaciejFrackowiak** [comment]
@pam83 Otrzymałem Twoje zgłoszenie - porównaliśmy request i response z danymi w naszej bazie - zwracamy dane z polskimi znakami. Musisz zatem zweryfikować działanie swojego oprogramowania.

**Comment by NM97** [comment]
Ponawiam więc pytanie. Jaki dokładnie system kodowania znaków został użyty w przypadku request oraz response?

**Comment by MaciejFrackowiak** [comment]
@NM97 Podczas naszych testowych operacji nie deklarowaliśmy żadnego kodowania i otrzymaliśmy poprawne odpowiedzi. W oprogramowaniu "dla porządku" możesz korzystać z UTF-8.

**Comment by pam83** [comment]
Witam, 
nie jest deklarowany żaden system kodowania.
Nagle response zacząłem otrzymywać z błędami. Nic się w kodzie oraz w konfiguracji systemu nie zmieniło.
Czy były w Allegro wprowadzane jakieś zmiany? Jeżeli przynajmniej u dwóch użytkowników w tym samym czasie występuje ten sam błąd to można wnioskować, że coś jest nie tak w API allegro.
Wcześniej na starym WebAPI też czasowo pojawiały się błędy ze zwracaniem polskich znaków. Po jakimś czasie znikały.
Proszę o sprawdzenie czy w aktualizacji nie ma jakiegoś buga.

**Comment by MaciejFrackowiak** [comment]
@pam83 Nie wprowadziliśmy żadnych zmian, jak wspomniałem z samej bazy zwracamy również polskie znaki.

**Comment by NM97** [comment]
W nagłówku nie przekazując już Państwo w parametrze charset informacji jaki wykorzystywany jest system kodowania znaków (od 19.06.2020). W wielu systemach korzysta się z bibliotek, które rozpoznają system kodowania znaków i usunięcie takiej informacji może spowodować pewne komplikacje u innych użytkowników. Poza tym informacja o tym, że nie wprowadzili Państwo żądnych zmian mija się z prawdą. Proszę dokładnie zweryfikować tę kwestię.

**Comment by pam83** [comment]
w takim razie jak powinno wyglądać zapytanie z nagłówkiem przekazującym system kodowania znaków?

**Comment by MaciejFrackowiak** [comment]
@NM97 @pam83 Sprawdźcie proszę teraz jak zachowa się Wasze oprogramowanie, czy uzyskacie już polskie znaki. Oprogramowanie, z którego korzystacie, oparte jest zapewne na Spring - niestety posiada ono błąd - my ze swojej strony przed chwilą zastosowaliśmy poprawkę dla niego, aby u Was pojawiały się polskie znaki.

**Comment by pam83** [comment]
U mnie nadal tak samo. korzystam z objektu WinHttpRequest.

**Comment by NM97** [comment]
@pam83 przekonwertuj wartość z parametru charset  na małe litery.

**Comment by pam83** [comment]
charset=utf-8 ?
caly czas błędy w polskich znakach ...

**Comment by MaciejFrackowiak** [comment]
@pam83 Tak, spróbuj dodać ;charset=utf-8 do nagłówka accept.

**Comment by pam83** [comment]
Właśnie tak go dodaje :) 
Sprawdziłem jeszcze raz w różnych kombinacjach. Dodalem ";charset=utf-8" też do "Content-Type" .... i bez.
Dziwne, że jeszcze niedawno wszystko działało i nie było żadnych problemów z polskimi znakami.

**Comment by MaciejFrackowiak** [comment]
@pam83 Niestety, w tym momencie wydaje się, że musisz popatrzeć na ustawienia swojej aplikacji / systemu - my jak wspominałem wczoraj dokonaliśmy zmian, aby obejść problem aplikacji opatych na Spring, nie mamy już kolejnego tropu.

**Comment by pam83** [comment]
dla winhttp musi być dokładnie ";charset=UTF-8"  (z dużych liter)  w nagłówku accept.
