### ISSUE TITLE
Błąd ERR_YOU_CANT_CHANGE_ITEM_NOT_A_SELLER przy wywołaniu metody doChangeQuantityItem

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#337]
Przy wywołaniu metody _doChangeQuantityItem_ dla **ofert oczekujących na wystawienie** otrzymuję błąd _ERR_YOU_CANT_CHANGE_ITEM_NOT_A_SELLER_.

Zapytanie:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoChangeQuantityItemRequest>
         <ser:sessionHandle>${#Project#sessionId}</ser:sessionHandle>
         <ser:itemId>6205380550</ser:itemId>
         <ser:newItemQuantity>9</ser:newItemQuantity>
      </ser:DoChangeQuantityItemRequest>
   </soapenv:Body>
</soapenv:Envelope>`

Odpowiedź:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_YOU_CANT_CHANGE_ITEM_NOT_A_SELLER</faultcode>
         <faultstring>Odwołanie ofert nie jest możliwe z uwagi na fakt, że aukcja nie została wystawiona przez zalogowanego użytkownika, jest zakończona lub nie zostały w niej złożone żadne oferty kupna. (24)</faultstring>
         <faultactor>doChangeQuantityItem - You cannot make any changes in this auction (you are not a seller)</faultactor>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

Zmiana ilości przez WWW dla tej samej aukcji działa bez problemu. Zmiana przez WebApi dla ofert aktywnych również działa bez problemu. Błąd występuje przy próbie zmiany ilości w aukcji oczekującej na wystawienie przez WebApi.

Dodam jeszcze, że zmiana **ceny** w ofercie oczekującej przez WebApi (metoda _DoChangePriceItem_) działa bez problemu.

**Comment by k4pit4n** [comment]
Przy wywołaniu metody _doChangeQuantityItem_ dla **ofert oczekujących na wystawienie** otrzymuję błąd _ERR_YOU_CANT_CHANGE_ITEM_NOT_A_SELLER_.

Zapytanie:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoChangeQuantityItemRequest>
         <ser:sessionHandle>${#Project#sessionId}</ser:sessionHandle>
         <ser:itemId>6205380550</ser:itemId>
         <ser:newItemQuantity>9</ser:newItemQuantity>
      </ser:DoChangeQuantityItemRequest>
   </soapenv:Body>
</soapenv:Envelope>`


Odpowiedź:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>ERR_YOU_CANT_CHANGE_ITEM_NOT_A_SELLER</faultcode>
         <faultstring>Odwołanie ofert nie jest możliwe z uwagi na fakt, że aukcja nie została wystawiona przez zalogowanego użytkownika, jest zakończona lub nie zostały w niej złożone żadne oferty kupna. (24)</faultstring>
         <faultactor>doChangeQuantityItem - You cannot make any changes in this auction (you are not a seller)</faultactor>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

Zmiana ilości przez WWW dla tej samej aukcji działa bez problemu. Zmiana przez WebApi dla ofert aktywnych również działa bez problemu. Błąd występuje przy próbie zmiany ilości w aukcji oczekującej na wystawienie przez WebApi.

**Comment by MartaNowaczyk** [comment]
Przetestowałam i dostaję taki sam błąd. Sprawę weryfikujemy. Dzięki za zgłoszenie.

**Comment by k4pit4n** [comment]
Niestety nadal otrzymuję ten sam błąd.

**Comment by PawelTaberski** [comment]
Pracujemy jeszcze nad rozwiązaniem tego problemu, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
Jak tylko rozwiążemy ten problem poinformuje Pana.

**Comment by k4pit4n** [comment]
Minął miesiąc od zgłoszenia a błąd nadal występuje...

**Comment by PawelTaberski** [comment]
Niedługo wprowadzimy zmiany w dokumentacji, jednakże metoda doChangeItemField nie obsługuje i nie obsługiwała ofert, które wystawią się w przyszłości, dlatego zachęcamy do korzystania z REST API, gdzie można wykonać tą operację.

**Comment by k4pit4n** [comment]
Ok, dziękuję za wyjaśnienia.
