### ISSUE TITLE
Getting overall sales volume/ value stats 

### ISSUE THREAD

**Issue by user432432** [allegro/allegro-api#3370]
I would like to get a list of the volume and value of sales for a certain phrase per seller.

I manage to get these statistics for "offers" (offers/listing), but not for "purchases". 

Where do I find these figures for purchases? What should I query?

I'm not a seller myself and I'm trying to get general sales volume/ value statistics per phrase per seller, not just my own sales results. That is probably the reason why the "orders" method didn't work.

**Comment by MaciejFrackowiak** [comment]
We don`t have such a resource to get this kind of data. Orders management resources are only available for the authorized user.

**Comment by user432432** [comment]
Ok. Understood. I'm just wondering: I know a few tools that, according to their developers are based 100% on Allegro API data, which do include sales data for all sellers.

Is Allegro selling additional data to them? Or do they use some kind of estimation calculated from the data available to everyone?

**Comment by MaciejFrackowiak** [comment]
No, they are using old version of our API - [WebAPI](https://allegro.pl/webapi/?lang=en) - there are some methods which allow you to get this kind of data. However, on September 30th, 2020 we will remove these methods too - see [our info](https://github.com/allegro/allegro-api/issues/3377).

**Comment by user432432** [comment]
Ok, thanks for the info.
