### ISSUE TITLE
autoryzacja / uwierzytelnienia uzyskiwanie tokena, czy możliwe zapytania w javascript

### ISSUE THREAD

**Issue by cristiano555** [allegro/allegro-api#3371]
Witam,
Próbuję napisać prostą aplikację, która ma za zadanie jedynie pobrać dane z allegro i wyświetlić na froncie.
Mój problem występuje na etapie uzyskiwania tokena. Jest wysylany request, ale zostaje zablokowany przez przegladarke - blad CORS - access-control-allow-origin, czyli serwer allegro daje przegladarce sygnal ze mojemu adresowi nie nalezy sie odpowiedz, tak to rozumiem w uproszczonym tłumaczeniu. Do kodu źródłowego restowego api allegro dostępu nie mam, więc zgody w nagłówku na swój adres nie ustawię. Da się to jakoś obejść? Szukałem więcej informacji, ale nie znalazłem. Wyczytałem jednak, że komunikacja nie powinna odbywać się przez Javascript (?)(obstawiam że to kwestie związane z bezpieczenstwem, a właśnie corsy blokuja taką możliwość?). W takim razie pozostaje mi php?

Będę wdzięczny za objaśnienie tematu i ewentualne sugestie. Dziękuję za poświęcony czas.

**Comment by MaciejFrackowiak** [comment]
Niestety, nie wspieramy pytań związanych bezpośrednio z programowaniem. Może ktoś z użytkowników forum podpowie Tobie jak to zrobić.
