### ISSUE TITLE
Sandbox - aktywacja konta

### ISSUE THREAD

**Issue by McAbra** [allegro/allegro-api#3372]
Dzień dobry, 
Proszę o aktywację konta w środowisku testowym.
Użytkownik/login piotro@arg.pl

Z góry dziękuję i pozdrawiam,
Piotr

**Comment by MaciejFrackowiak** [comment]
Aktywowałem Twoje konto.

**Comment by lfuszara** [comment]
Dzień dobry,
Czy mogę poprosić o aktywację?
Użytkownik: l.fuszara@grupaaf.pl

Z pozdrowieniami
Łukasz

**Comment by MaciejFrackowiak** [comment]
@lfuszara Konto jest już aktywne.
