### ISSUE TITLE
Odświeżenie tokena

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#3374]
Mam jakiś problem z odświeżeniem tokena dla ID: c9a8f942f2f24849b1aac1fb0d0bd9eb

Zwraca komunikat "Too Many Requests" i trwa to już od ponad godziny. Nikt na tym teraz nie pracuje (bo nie może). Czy można się dowiedzieć, z czym jest tam problem?

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi i widzę, że udało Ci się pobrać kolejne access_token`y wraz z przypisanymi do nich refresh_token`ami.

**Comment by Mihalis76** [comment]
Tak, po kilku godzinach sprawdziłem czy coś się zmieniło i wtedy już działało.

**Comment by Mihalis76** [comment]
Powtórzył się problem z odświeżeniem tokena, tym razem dla ID: 030ec022a3f847da82aeacbe08ba36d8. 
Jest komunikat "Too Many Requests". Nikt teraz nie pracuje na tym ID.

**Comment by MaciejFrackowiak** [comment]
Spojrzałem w logi i nie widzę nic niepokojącego. Gdzie otrzymujesz komunikat "Too Many Requests"?

**Comment by Mihalis76** [comment]
Sprawdzałem co, około 10 minut i za którymś razem: 8, 9 czy 10 te tokeny pobrał. Poprzednio było podobnie.
Korzystam z bibliotek, których nie mogę teraz znaleźć. W nagłówku jest Copyright (c) 2016 Piotr Jakubik.
I wywala się to podczas 
$api->getNewAccessToken($_GET['code']); $api->refreshAccessToken();

które są zdefiniowane:
    public function refreshAccessToken()
    {
        $data = array(
            'grant_type' => 'refresh_token',
            'api-key' => $this->apiKey,
            'refresh_token' => $this->refreshToken,
            'redirect_uri' => $this->redirectUri
        );
        return $this->requestAccessToken($data);
    }

    public function getNewAccessToken($code)
    {
        $data = array(
            'grant_type' => 'authorization_code',
            'code' => $code,
            'api-key' => $this->apiKey,
            'redirect_uri' => $this->redirectUri
        );
        return $this->requestAccessToken($data);
    }

    private function requestAccessToken($data)
    {
        $authorization = base64_encode($this->clientId . ':' . $this->clientSecret);
        $headers = array(
            "Authorization: Basic $authorization",
            "Content-Type: application/x-www-form-urlencoded"
        );
        $data = http_build_query($data);
        $response = $this->sendHttpRequest(static::TOKEN_URI, 'POST', $headers, $data);
        $data = json_decode($response);
        if (isset($data->access_token) && isset($data->refresh_token))
        {
            $this->accessToken = $data->access_token;
            $this->refreshToken = $data->refresh_token;
        }
        return $response;
    }

    protected function sendHttpRequest($url, $method, $headers = array(), $data = '')
    {
        $options = array(
            'http' => array(
                'method' => $method,
                'header' => implode("\r\n", $headers),
                'content' => $data,
                'ignore_errors' => true,
			    'timeout' => 15  
            )
        );
        $context = stream_context_create($options);
        return file_get_contents($url, false, $context);
    }

**Comment by MaciejFrackowiak** [comment]
W tym wypadku musiałbyś nawiązać kontakt z autorem skryptu. Ze względu na dużą liczbę języków programowania, nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.
