### ISSUE TITLE
Płatności na sandboxie

### ISSUE THREAD

**Issue by Sebug-rsa** [allegro/allegro-api#3375]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Na sandboxie nie działają płatności. Kiedy zostanie przywrócona ta funkcjonalność?

**Comment by MaciejFrackowiak** [comment]
Potwierdzam problem - działamy już nad jego usunięciem.

**Comment by TomekDuszynski** [comment]
Uda się to dziś poprawić?

**Comment by MaciejFrackowiak** [comment]
Niestety nie, przywrócenie funkcjonalności nie do końca od nas zależy, w optymistycznym scenariuszu jutro powinno być OK.

**Comment by MaciejFrackowiak** [comment]
Symulator płatności już funkcjonuje prawidłowo. Przepraszam za niedogodności.
