### ISSUE TITLE
Śledzenie zmian w api

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3376]
Jest jakiś sposób aby na otrzymywanie powiadomień o zmianach w api allegro? 
Chodzi mi o otrzymywanie np. maila z z issue z etykietą "news", albo ze strony dokumentacji api z aktualności.
Ma ktoś jakiś patent na to, niestety powiadomień z issue allegro jest od groma.

**Comment by MaciejFrackowiak** [comment]
Każdy nasz komunikat oprócz etykiety "news" posiada także tytuł w postaci [NEWS] .... - wystarczy, że założysz sobie filtr na tytuł i już szybko wyfiltrujesz kluczowe wiadomości.

**Comment by PabloMD** [comment]
> wystarczy, że założysz sobie filtr na tytuł i już szybko wyfiltrujesz kluczowe wiadomości.

Ja też jestem chyba noobem, ponieważ nie widzę opcji filtrowania notyfikacji na githubie?

**Comment by MaciejFrackowiak** [comment]
@PabloMD Miałem na myśli filtr w kliencie pocztowym, który po tytule wiadomości odpowiednio wyfiltruje wiadomości z tytułem [NEWS].
