### ISSUE TITLE
Autoryzacja użytkownika

### ISSUE THREAD

**Issue by Krispekowy** [allegro/allegro-api#3378]
Mam pytanie dotyczące autoryzacji użytkownika. Wywołuję na przycisku przekierowanie na url z odpowiednimi parametrami. Po zalogowaniu wraca do mnie informacja (w formie url) z kodem - https://localhost:8080/?code=xyzxyzxyz. Niestety w żaden sposób nie mogę pobrać tego kodu. Chcąc się odwołać do url i pobrać ten parametr otrzymuję mój routeTrack (korzystam z .net MVC c#)

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania, nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc
