### ISSUE TITLE
Kod EAN jest niepoprawny. Prośba o szczegóły walidacji.

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#3379]
Czy mógłbym uzyskać więcej informacji na temat uznania kodu EAN 590376960000 za niepoprawny?

**Comment by MaciejFrackowiak** [comment]
Zgadza się, podany EAN jest nieprawidłowy - ma niepoprawną sumę kontrolną, właściwy kod to 590376960003.

**Comment by tomasz-grzesik** [comment]
Rzeczywiście, po kontakcie Gs1 okazało się, że Użytkownik nie do końca zrozumiał przydzielone kody EAN i wpisywał niepoprawne.

**Comment by esprzedaz** [comment]
Mam taki sam błąd z numerem 5902052859788. Walidatory pokazują, że jest poprawny, a API zwraca błąd jak w temacie.
