### ISSUE TITLE
doGetBidItem2 - różnice w danych

### ISSUE THREAD

**Issue by mkosiek** [allegro/allegro-api#338]
Witam,
Na przykładzie aukcji nr 6926465062 (dane rzeczywiste) widać, że na tą chwilę 12 osób kupiło 15 sztuk. Natomiast po wywołaniu metody doGetBidItem2 ostatnie 12 wpisów wygląda jak poniżej. Mamy tutaj różnicę jednej sztuki. Skąd ta różnica?

Liczba zakupionych	Status zakupu	Data zakupu (Unix)	Data zakupu
1	1	1527765961	31.05.2018 13:26:01
1	1	1528045068	03.06.2018 18:57:48
1	1	1528269608	06.06.2018 09:20:08
1	1	1528355154	07.06.2018 09:05:54
1	1	1528380574	07.06.2018 16:09:34
1	1	1528566036	09.06.2018 19:40:36
2	1	1528743294	11.06.2018 20:54:54
1	1	1529004413	14.06.2018 21:26:53
2	1	1529050559	15.06.2018 10:15:59
1	1	1529644825	22.06.2018 07:20:25
3	1	1529648535	22.06.2018 08:22:15
1	1	1529924376	25.06.2018 12:59:36

**Comment by MartaNowaczyk** [comment]
Witam,
W tym wpisie 2 1 1529050559 mamy 2 sztuki bo klient zrobił zakupy dwa razy 15.06.2018 i 11.04.2018, stąd zapewne ta rozbieżnność.

Do monitorowania sprzedaży polecamy inny schemat działania, więcej [w tym artykule](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421).

**Comment by mkosiek** [comment]
Witam,
Niestety, metody podane w artykule odnoszą się do aukcji, w których użytkownik jest stroną. Mnie natomiast interesuje dokładniejszy przebieg aukcji, w której nie jestem stroną
Wnioskując po Pani odpowiedzi dla metody doGetBidItem2 dane grupowane są po kupującym? Jeżeli tak, to trochę to mylące, ponieważ zgodnie z opisem interfejsu mamy tam datę zakupu, a wychodzi na to, że jest to ostatnia data zakupu danego użytkownika. Ilość natomiast to suma wszystkich zakupionych przedmiotów użytkownika w aukcji. Czy dobrze to rozumiem?
Jeżeli tak, to czy jestem w stanie pobrać dla dowolnej aukcji ilość zakupionych przedmiotów na dzień?

**Comment by KrzysztofLukanowski** [comment]
Cześć, tak jak napisałeś, dane w tej metodzie grupowane są po kupującym i wyświetlamy datę ostatniego zakupu. Nie jesteś w stanie wyciągnąć konkretnej daty zakupu, jeżeli nie jesteś sprzedającym - chyba, że odpytujesz ofertę codziennie od początku "jej życia".
