### ISSUE TITLE
Jak pobrać wiadomości od kupującego, które są w skrzynce

### ISSUE THREAD

**Issue by WlascicielAllegro** [allegro/allegro-api#3381]
W związku z tym, że jak zwykle coś nie działa - te maile z maskowanych adresów przychodzą albo i nie - a ciśniecie mnie ujemnymi punktami, natychmiast macie mi podać jak po api sprawdzać/pobierać/odpowiadać na "pytanie o przedmiot".

**Comment by PrzemyslawLukanowski** [comment]
W naszym API nie ma jeszcze funkcjonalności, która odzwierciedla Centrum Wiadomości. Znajduje się to jednak na liście naszych sugestii. Opublikujemy odpowiedni komunikat, gdy zdecydujemy się wprowadzić taki zasób.
