### ISSUE TITLE
Błąd łączenia ofert w oferty wielowariantowe

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#3382]
Dziwny błąd przy próbie łączenia ofert wielowariantowych  po color/pattern w kategorii 253547
Otrzymuję komunikat :

(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => All active offers must have identical values for validating parameters: Manufacturer (127422).
                    [details] =>.
                    [path] =>.
                    [userMessage] => All active offers must have identical values for validating parameters: Manufacturer (127422).
                )

        )

)

Czy to oznacza że mogę łączyć w ofertę wielowariantową tylko oferty tego samego producenta ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, w tym przypadku musisz podać taką samą wartość dla parametru "Producent". Świadczy o tym wartość true, którą otrzymasz w polu `variantsEqual `w odpowiedzi dla `GET /sale/categories/253547/parameters`.
