### ISSUE TITLE
Wiązanie zamówień (notatki?)

### ISSUE THREAD

**Issue by premax** [allegro/allegro-api#3383]
Dzień dobry

czy planujecie dodać możliwość definiowania notatek do zamówień przez Rest API?
Próbuję dwustronnie powiązań zamówienia Allegro - system sprzedawcy, tak żeby w panelu Allegro sprzedawca widział również ID zamówienia ze swojego systemu i pomyślałem właśnie o polu notatka (z braku lepszego).

**Comment by PrzemyslawLukanowski** [comment]
Mamy taką sugestię na naszej liście. Jeśli będę mógł przekazać bardziej wiążące informację, poinformuję w tym wątku.

**Comment by Planche95** [comment]
@PrzemyslawLukanowski czy dzisiaj jest możliwość dodania notatki przez RestAPI?

**Comment by Lukasz-Zurek** [comment]
@Planche95 Odpowiem w imieniu mojego kolegi - nie ma możliwości dodania notatki przez RestAPI. W zeszłym roku dodaliśmy jednak [możliwość sprawdzenia notatki](https://github.com/allegro/allegro-api/issues/7409) (dodanej wcześniej za pośrednictwem "Zamówień" w "Moim Allegro").

**Comment by andjjs** [comment]
Witam. A czy półtora roku później temat jest brany pod uwagę? :) Super byłoby móc dodawać / aktualizować notatki po REST Api. Pozdrowienia.

**Comment by Lukasz-Zurek** [comment]
@andjjs Dzięki za wiadomość :) Jesteśmy otwarci, aczkolwiek jak w przypadku większość funkcjonalności, które są już dostępne w Allegro, ale nie ma ich jeszcze w API - nie jest to takie proste i w pełni zależne tylko od nas. W tym miejscu zachęcam Cię do oddania głosu na [utworzoną już sugestię](https://github.com/allegro/allegro-api/discussions/12504) na Github Discussions.
