### ISSUE TITLE
Anulowanie zamówienia a zwrot prowizji i płatności

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3384]
Jak wygląda sprawa zwrotu prowizji i płatności gdy klient anuluje zamówienie, należy ręcznie wystąpić o zwroty, czy dzieje się to automatycznie?

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji musisz ręcznie wystąpić o zwrot prowizji.

**Comment by ppart** [comment]
A jeśli chodzi o zwrot wpłaty? Jest to po stronie allegro czy klienta w przypadku anulowania zamówienia?

**Comment by PrzemyslawLukanowski** [comment]
Również należy to wykonać manualnie.
