### ISSUE TITLE
Listingi - internal server error

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3387]
od godziny dla zapytania:
https://api.allegro.pl/offers/listing?category.id=250405&sort=-popularity
dostaję http:500
czy jest jakas awaria, czy ja tak trafiam?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, zgłosiłem go już do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
Problem już nie powinien występować.
