### ISSUE TITLE
Motoryzacja: wyszukiwanie po marce/modelu

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3388]
Zauważyłem, że w motoryzacja->części do samochodów pojawiło się wybieranie marki/modelu.
Czy w api również udostępnicie takie filtry?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz wskazać, które konkretnie rozwiążanie na froncie masz na myśli?

**Comment by kfijalko** [comment]
![wybieranie](https://user-images.githubusercontent.com/7058985/86241002-7594bf00-bba2-11ea-8ce6-3f50072a729e.png)

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli masz na myśli filtry po pasuje do w wyszukiwarce, to na razie nie, nie mamy tego w planach. Jeżeli sytuacja się zmieni, opublikujemy odpowiedni komunikat.
