### ISSUE TITLE
Motoryzacja: opony: brak słownika dla średnicy opony ciężarowej

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#3389]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam następujące problemy:
1. **(REST API)** Podczas wystawiania aukcji z oponami ciężarowymi dla parametru **średnica opony** brakuje słownika.
2. Podczas ręcznego wystawiania aukcji allegro, brakuje parametru średnica na liście pól i nie można wystawić aukcji, zwraca informacje że średnica nie została wybrana.

**Comment by promsters** [comment]
Podpinam się do zgłoszenia. 
Od godziny około 16 zaczęły pojawiać się błędy:

PUT sale/offers

> VALIDATION_ERROR: Assigned valueId  for dictionary parameter 127088 is not found.

Price, Quantity change commands

> Podana wartość parametru Średnica(127088) nie istnieje w słowniku
> ERR_NOT_EXISTING_VALUE_IN_ATTRIBUTE

Sprawdziłem też wtedy za pomocą GET sale/categories/../parameters i parametr 127088 nie miał żadnych pozycji w dictionary.

W momencie gdy to piszę dictionary ma już z powrotem swoje wartości, ale błędy niestety pozostają bez zmian.

Jest to o tyle problematyczne, że nie można zaktualizować żadnej aukcji (stan, cena).

**Comment by PrzemyslawLukanowski** [comment]
Problem już nie powinien występować, prośba o potwierdzenie.

**Comment by promsters** [comment]
Potwierdzam, ostatni błąd jest pojawił się o 8:21 więc wygląda na to, że problem został rozwiązany.

Szkoda tylko, że zajęło wam to aż tyle czasu, bo teraz jesteśmy zmuszeni ponowić wszystkie zmiany jakie miały miejsce od wczoraj na naszych aukcjach.
