### ISSUE TITLE
Quantity validation error

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#339]
Hi guys,

I'm trying to upload a new draft offer, but I get this error : "Quantity must be provided".
I cannot find anything related to this field in the documentation (https://developer.allegro.pl/en/sale/)

Can you give me an example ? And please update the documentation, I presume others will have this problem as well.

Thank you !

**Comment by MartaNowaczyk** [comment]
Hi, can I get request and response with "Quantity must be provided" error?

**Comment by crevu** [comment]
**Request:**

curl -X POST \
  'https://api.allegro.pl/sale/offers'
  -H 'authorization: Bearer {my_access_token}' \
  -H 'accept: application/vnd.allegro.beta.v1+json' \
  -H 'content-type: application/vnd.allegro.beta.v1+json' \
  -d '{
	"name": "Etui Blue Fight LG Magna",
	"category": {
		"id": "19338"
	},
	"parameters": [{
		"id": 11323,
		"valuesIds": ["11323_1"]
	}, {
		"id": 207786,
		"valuesIds": ["207786_233834"]
	}, {
		"id": 206002,
		"valuesIds": ["206002_225634"]
	}, {
		"id": 207790,
		"valuesIds": ["207790_233882"]
	}],
	"description": {
		"sections": [{
			"items": [{
				"type": "TEXT",
				"content": "<p>Ciesz si\u0119 obudow\u0105 <b>Premium TPU<\/b> wyprodukowan\u0105 w Rumunii z najlepszymi dost\u0119pnymi materia\u0142ami.<\/p><ul><li> <b> \u015awie\u017ce <\/b> <\/li><li> <b> Premium <\/b> <\/li><li> <b> Funky <\/b> <\/li><\/ul>"
			}]
		}]
	},
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "33.99",
			"currency": "PLN"
		},
		"startingPrice": null,
		"minimalPrice": null
	},
	"delivery": {
		"shippingRates": {
			"id": "1ffed977-8a59-40a3-9525-8edc2fee5303"
		}
	},
	"payments": {
		"invoice": "VAT"
	},
	"location": {
		"countryCode": "RO",
		"city": "Rosiorii de Vede"
	}
}'


**Response:**

{
	"id": "7425088382",
	"name": "Etui Blue Fight LG Magna",
	"category": {
		"id": "19338"
	},
	"parameters": [{
		"id": "11323",
		"valuesIds": ["11323_1"],
		"values": [],
		"rangeValue": null
	}, {
		"id": "207786",
		"valuesIds": ["207786_233834"],
		"values": [],
		"rangeValue": null
	}, {
		"id": "206002",
		"valuesIds": ["206002_225634"],
		"values": [],
		"rangeValue": null
	}, {
		"id": "207790",
		"valuesIds": ["207790_233882"],
		"values": [],
		"rangeValue": null
	}],
	"ean": null,
	"description": {
		"sections": [{
			"items": [{
				"type": "TEXT",
				"content": "<p>Ciesz się obudową <b>Premium TPU</b> wyprodukowaną w Rumunii z najlepszymi dostępnymi materiałami.</p><ul><li> <b> Świeże </b> </li><li> <b> Premium </b> </li><li> <b> Funky </b> </li></ul>"
			}]
		}]
	},
	"images": [],
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "33.99",
			"currency": "PLN"
		},
		"startingPrice": null,
		"minimalPrice": null
	},
	"stock": null,
	"publication": {
		"duration": null,
		"status": "INACTIVE",
		"startingAt": null,
		"endingAt": null
	},
	"delivery": {
		"shippingRates": {
			"id": "1ffed977-8a59-40a3-9525-8edc2fee5303"
		},
		"handlingTime": null,
		"additionalInfo": null,
		"shipmentDate": null
	},
	"payments": {
		"invoice": "VAT"
	},
	"afterSalesServices": null,
	"additionalServices": null,
	"sizeTable": null,
	"promotion": null,
	"location": {
		"countryCode": "RO",
		"province": null,
		"city": "Rosiorii de Vede",
		"postCode": null
	},
	"external": null,
	"contact": null,
	"validation": {
		"errors": [{
			"code": "VALIDATION_ERROR",
			"message": "Quantity must be provided",
			"details": "",
			"path": "",
			"userMessage": "Quantity must be provided"
		}, {
			"code": "VALIDATION_ERROR",
			"message": "You don't have the required permissions to publish offer (sell blocked)",
			"details": "",
			"path": "",
			"userMessage": "You don't have the required permissions to publish offer (sell blocked)"
		}, {
			"code": "VALIDATION_ERROR",
			"message": "After sales service conditions (return policies, implied warranties) are required by company account",
			"details": "",
			"path": "",
			"userMessage": "After sales service conditions (return policies, implied warranties) are required by company account"
		}],
		"validatedAt": "2018-06-26T14:48:27.07Z"
	},
	"createdAt": "2018-06-26T14:48:27Z",
	"updatedAt": "2018-06-26T14:48:27.071Z"
}

**Comment by AniaMalinowska** [comment]
You give null - you must complete the quantity: https://developer.allegro.pl/en/sale/#new-offer - this is called 'stock'.

**Comment by crevu** [comment]
Indeed, 'stock' it is. Thank you !
