### ISSUE TITLE
GET offers/listing aukcje: regular i promoted

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#3390]
Jak pobrać aukcje tylko regular lub promoted?
Czyli wszystkich aukcji "nie promowanych" lub "promowanych"

**Comment by PrzemyslawLukanowski** [comment]
Zasób jest odzwierciedleniem wizualnej wyszukiwarki serwisu, dlatego nie możesz osobno pobrać ofert typu promoted i regular.

**Comment by Aryak2099** [comment]
Pobiez całość i potem wyodrębnij tylko regular.

**Comment by gsti** [comment]
Są kategorie które mają o wiele więcej wyników i nie da się pobrać wszystkich ofert. Liczę że jest to rozwojowa wersja API i jeszcze wiele tutaj się zmieni. Oby na lepsze.

**Comment by Aryak2099** [comment]
To trzeba filtrować według ceny naprzykład niech pobiera , ustaw limity i offsety, doprecyzuj zapytanie lub zastosuj wykluczenia . Da się pobrać wszystkie oferty.
