### ISSUE TITLE
Zwrot jest na Allegro, nie ma go w REST API (/payments/refunds)

### ISSUE THREAD

**Issue by Venzonite1** [allegro/allegro-api#3391]
Witam, posiadam transakcję, która ma payment.id: 6aa741d1-b50d-11ea-83e6-f33e923f2c7c

Dla tej płatności klient zażądał zwrotu pieniędzy i widać to na Allegro w zakładce "Zwroty".
Status zwrotu: WYBRANO SPOSÓB WYSYŁKI

Mam problem ponieważ gdy odpytuję zasób: /payments/refunds?payment.id=6aa741d1-b50d-11ea-83e6-f33e923f2c7c
to otrzymuję odpowiedź [200] z poniższym jsonem:

`{
  "refunds": [],
  "count": 0,
  "totalCount": 0
}`

Dlaczego nie otrzymuję w odpowiedzi informacji o zwrocie, który widzę na Allegro?

--

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Dla zasobu GET /payments/refunds w odpowiedzi otrzymasz wszystkie zwroty płatności, jakie wykonałeś do klienta. Nie jest to tożsame z samym wykonaniem zwrotu towaru - taki zasób mamy na tę chwilę na naszej liście sugestii dot. rozwoju API. Ostatecznie nie wykonałeś zwrotu płatności, dlatego nie otrzymujesz żadnych danych, które byłyby powiązane z tym payment.id.

**Comment by Venzonite1** [comment]
Czy jest w takim razie możliwość, aby napisali Państwo, czy jest jakikolwiek zasób, który pozwoli choćby częściowo umożliwić obsługę zwrotów dokonanych przez klienta. Nie rozumiem w jakim celu jest obsługa płatności bez obsługi wypełnionych formularzy, kiedy nie mam informacji co i kiedy komu zwracać. Np.

Klient wypełnia zwrot na Allegro i odsyła przedmiot -> system pobiera wypełniony formularz przez API -> wykonujemy zwrot pieniędzy -> składamy wniosek o zwrot prowizji

Jak spełnić ten podstawowy łańcuch obsługi?

**Comment by PrzemyslawLukanowski** [comment]
Tak, mamy taki zasób na liście naszych sugestii, jednak na tę chwilę nie mogę przekazać więcej szczegółów. Na pewno opublikujemy odpowiedni komunikat w momencie wdrożenia.

> Nie rozumiem w jakim celu jest obsługa płatności bez obsługi wypełnionych formularzy, kiedy nie mam informacji co i kiedy komu zwracać

Zwrot płatności może wystąpić także z innych powodów, np. po anulowaniu zamówienia, przez niedostępność produktu czy przez zbyt niską wpłatę kupującego.

Na tę chwilę w API nie zwracamy informacji, która pomogłaby zidentyfikować zwrot towaru.

**Comment by AleksanderLewandowski** [comment]
@PrzemyslawLukanowski  Czy w tym momencie w API są już przekazywane informacje dotyczące zwrotów?

**Comment by AleksanderLewandowski** [comment]
@PrzemyslawLukanowski  Czy przez API można pobrać formularz zwrotu z Allegro?

**Comment by PrzemyslawLukanowski** [comment]
@AleksanderLewandowski Jeśli masz na myśli obsługę zwrotów klienckich, to tak, udostępanimy takie API. W [naszym poradniku](https://developer.allegro.pl/orders/#zwroty-klienckie) znajdziesz więcej szczegółów.

**Comment by AleksanderLewandowski** [comment]
Łącznie z obsługą płatności do zwrotu?

**Comment by PrzemyslawLukanowski** [comment]
Taką funkcjonalność udostępniamy już od dłuższego czasu, szczegóły znajdziesz również w [wyżej wymienionym poradniku.](https://developer.allegro.pl/orders/#zwroty-p%c5%82atno%c5%9bci)
