### ISSUE TITLE
GET /offers/listing - offset / availableCount ?

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#3392]
Jeżeli przeszukuje aukcje wg category.id i nie podaje seller.id zwracane jest 6.000 wyników ale jak podaje seller.id zwracane jest 120.000 wyników.
Tylko wydaje mi się że mało który sprzedawca ma wystawione 120.000 aukcji szukając nawet od głównej kategorii. 
Czy to czasem nie powinno być na odwrót, chyba że źle interpretuje wyniki?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykład wywołania, dla którego otrzymałeś taką odpowiedź?

**Comment by gsti** [comment]
Jak w dokumentacji:
Search offers - /offers/listing
offset - Index of the first returned offer from all search results. Max offset is: - 120000 - <limit> if seller.id parameter is given in request, - 6000 - <limit> if no seller.id parameter is given in request.

**Comment by PrzemyslawLukanowski** [comment]
Tak to prawidłowa informacja. Zdecydowaliśmy się na taki ruch, ponieważ takie było zapotrzebowanie ze strony sprzedawców.
