### ISSUE TITLE
Problem z długością tytułu oferty

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#3394]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mimo że w artykule https://allegro.pl/pomoc/dla-sprzedajacych/opis-oferty/jak-utworzyc-dobry-tytul-oferty-WEDKYqakaUB jest informacja, że tytuł może zawierać 50 znaków, nie zawsze się to sprawdza.
Użycie np. znaku "&" powoduje naliczenie kilku znaków (prawdopodobnie dlatego, że konwertujecie to na "& a m p ;" i liczycie jako 5 znaków). Przy jedynym logicznym w moim odczuciu założeniu, że limit ten ma znaczenie estetyczne lub biznesowe, a nie techniczne - wydaje się to błędem. Prośba o naprawę, albo wyprowadzenie mnie z błędu, że to błąd :)

**Comment by PrzemyslawLukanowski** [comment]
To prawidłowe zachowanie, umieściliśmy taką informację w [naszym poradniku](https://developer.allegro.pl/sale/#4-tytu%c5%82-oferty):

> **Ważne!** Niektóre litery jak i znaki specjalne są zamieniane na encje, dlatego zajmują więcej niż jeden znak. Przykładowo znak & jest encjonowany jako & dlatego zajmuje 5 miejsc w tytule.
