### ISSUE TITLE
Problem z zakończeniem aukcji na produkcji

### ISSUE THREAD

**Issue by prusmarcin** [allegro/allegro-api#3395]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,

Do wystawienia aukcji wykorzystuje endpointa:
PUT sale/offer-publication-commands/3a4ddb2e-fc13-4dad-9564-f3c5eeccc6c2
I to działa bez problemów.

Do zakończenia aukcji wykorzystuje tą samą metodę tylko zamiast ACTIVATE używam END lecz aukcja cały czas jest aktywna
Parametry json jakie wysyłam:
{"publication":{"action":"END"},"offerCriteria":[{"offers":[{"id":"9452158689"}],"type":"CONTAINS_OFFERS"}]}

Odpowiedź jaką dostaję to:  [id] => 3a4ddb2e-fc13-4dad-9564-f3c5eeccc6c2 [taskCount] => stdClass Object ( [total] => 0 [success] => 0 [failed] => 0 ) [statusCode] => 201 )

Nie rozumiem dlaczego to nie działa.
Aukcja jest aktywna na produkcji, nie będe jej zamykał. Proszę przeanalizować ten problem.

Z góry bardzo dziękuje za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Jednego commandId możesz użyć tylko dla pojedyńczego żądania. Czyli jeśli dla komendy ACTIVATE użyłeś 3a4ddb2e-fc13-4dad-9564-f3c5eeccc6c2, to dla akcji END musisz już użyć innego numeru UUID.

**Comment by prusmarcin** [comment]
Przetestowałem - działa :)
Bardzo dziękuje za pomoc.
