### ISSUE TITLE
Invalid parameter Długość wkładki(203093) value

### ISSUE THREAD

**Issue by likrot** [allegro/allegro-api#3396]
Witam,

mam taki niesforny model `New Balance ML515RSB `, któremu klient próbuje ustawić takie rozmiary wkładki:
- 29.5
- 29.0
- 28.5
- 28.0
- 27.5
- 27.0
- 26.5

Jest to jedyny model, z którym mam taki problem. Mógłby ktoś wskazać co tutaj jest nie tak? (liczby są rzutowane na `float` i dla pewności jest sprawdzany znak czy jest `przecinkiem` czy `kropką`)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id? Przeanalizowałem nasze logi, ale widzę, że taki błąd otrzymywałeś, gdy jako wartość przekazywałeś >40. Odpowiedź w tym przypadku jest prawidłowa, ponieważ maksymalna wartość dla tego parametru to 40.
