### ISSUE TITLE
InPost Paczkomat 24/7 vs Allegro InPost Paczkomat 24/7

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3397]
Mam pytanie o pewną nieścisłość mianowicie: 
na aukcji np 8927917647 mam formę dostawy Inpost Paczkomat
natomiast w GET https://api.allegro.pl/sale/delivery-methods nie zwraca takiem metody dostawy. Jak to rozumieć?

**Comment by PrzemyslawLukanowski** [comment]
W /sale/delivery-methods ta metoda dostawy to Paczkomaty 24/7 o id 685d8b40-2571-4111-8937-9220b1710d4c.
