### ISSUE TITLE
Allegro API Magento 2 API

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#3398]
Integruje atrybuty magento 2 z atrybutami allegro.
Jakie są nazwy kolorów, rozmiarów, wzorów itd w atrybutach api allegro?
Ponieważ chce w moim magento 2 utworzyć takie nazwy tych atrybutów, aby poprawnie przesyłały sie do api allegro.

**Comment by Aryak2099** [comment]
Wszystkie parametry a API allegro dzielą się na różne typy, kolor jest wartością słownikową DICTIONARY i tam opisane są jakie są kolory.  To nie są nazwy tylko liczby za którymi chowają się nazwy i przekazuje się je do allegro w postaci tych liczb. Jaki masz ten plik z magento wynikowy CSV XML czy jakiś inny ? Napisz do mnie : na 
  admin@e-api.pl

**Comment by sportmma** [comment]
Plik XML

**Comment by Aryak2099** [comment]
Panu zalezy tylko naprzykłąd na samych parametrach ? Dla przykładu chce Pan uzsykać jakie są dostepne kolory do wyboru w dziale Moda tak? Trzeba pamiętać że inne są napryzkłąd romziary obuwia dla działu męskiego i inne dla dziecęcego. Pytam bo jak Pan chce to mogę udostępnić program który po wpisaniu numeru kategorii z allegro i naprzykłąd parametru kolor pokaże Panu wszystkie wartości jakie tam są dostępne.

**Comment by sportmma** [comment]
Własnie takiego programu bym potrzebował. Chcę zintegrować magento 2 z
allegro. Musiał bym wtedy stworzyć odpowiednie atrybuty produktów do
mapowania do allegro, aby recznie za kazdym razem ich nie wpisywć.
Chodzi o kolory, rozmiary, ilość kieszenie, krój itd. Wszystkie atrybuty
które są do wyboru z listy w allegro.

**Comment by sportmma** [comment]
Niektóre produkty do magento mam dodane przez csv/xml inne przez API
niektóre zaś przez webscraping. Ale produkty do integracji allegro chcę
przesyłać przez wbudowany moduł magento 2.

**Comment by sportmma** [comment]
Produkty bede dodawał w różnych kategoriach. Głównie moda oraz sporty
walki.

**Comment by Aryak2099** [comment]
To wie Pan ja to robiłem komuś inaczej z pliku xml który był do integracji z np RedCart i Prestashop wystawiałęm od razu oferty na allegro. Program sam odcztuje parametry z pliku xml z towarem przetwarza , dodoaje parametry i tak wystawia na allegro. Dajmy na przyłąd tak ma Pan buty w dziale buty te parametry są inne niż dla np spodenek , kolor , model , kod producenta , skłąd materialowy to będzie to samo ale już rozmary są zupelnie inne. Ma Pan jakiś skrócony  taki plik xml z 2-5 sztuk towaru      to Panu napisze czy dasię tak zrobić . Niech Pan mejla zostawi. Można też tak jakPan pisze ale to kupe roboty jest.

**Comment by sportmma** [comment]
Wysyłam plik xml który chciałbym dodać do allegro.

**Comment by sportmma** [comment]
??

**Comment by Aryak2099** [comment]
admin@e-api.pl  tu niech Pan wysle
