### ISSUE TITLE
co to jest uuid ?

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3399]
witam, chciałem zakończyć ofertę, myślałem, że trzeba podać id aukcji, natomiast widzę, że muszę podać uuid. Co to jest uuid i jak je wygenerować?

**Comment by yd6d7hhds** [comment]
Niewątpliwie id aukcji też musisz podać.
Za poradnikiem:
W polu commandId podaj wartość w formacie UUID (universally unique identifier). Jest to globalnie unikatowy identyfikator, który składa się z 32 liczb szesnastkowych (np.: 21ae4ed1-eab7-34ea-b605-cf2e22b5eed3). Identyfikator generujesz we własnym zakresie.

**Comment by Aryak2099** [comment]
Losowo go wygeneruj i  tyle. W czym piszesz? python , java c# php ?

**Comment by speedygopl** [comment]
witam, piszę w javie, już poradziłem, dzięki
