### ISSUE TITLE
Dlaczego metoda doGetItemsInfo zwraca puste tablice mimo podania wszystkich wymaganych parametrów?

### ISSUE THREAD

**Issue by samilmarekrygula** [allegro/allegro-api#34]
Wykonanie:
$data_params = array('sessionHandle' => $_SESSION[0]['sessionHandlePart'], 'itemsIdArray' => array($id1,$id2));
$data = $client->call("doGetItemsInfo",$data_params);
print_r zwraca mi:
Array
(
[arrayItemListInfo] =>
[arrayItemsNotFound] =>
[arrayItemsAdminKilled] =>
)

*****

Dokładny kod wygląda tak:
$myItemsInfo = $soapClient->call(
					'doGetItemsInfo',
					array(
					   array(
							'sessionHandle' => $session['sessionHandlePart'],
							'itemsIdArray' => $tablica,
							'getProductInfo' => 1,
							'getDesc' => 1,
							'getEan' => 1
					   )
					)
				);
za zmienną tablica wpadają takie wartości w tej tablicy array(24) { [0]=> int(7159184595) [1]=> int(6776291560) [2]=> int(6776312247) [3]=> int(6741275547) [4]=> int(6636486756) [5]=> int(6636490115) [6]=> int(6776466759) [7]=> int(6946494243) [8]=> int(7072491159) [9]=> int(6776545316) [10]=> int(6636716527) [11]=> int(6946610825) [12]=> int(6741649336) [13]=> int(6946626441) [14]=> int(6983305906) [15]=> int(6880243335) [16]=> int(6983310245) [17]=> int(6741739791) [18]=> int(7072738772) [19]=> int(6946649480) [20]=> int(7072742298) [21]=> int(7159931141) [22]=> int(7159944697) [23]=> int(6706345619) }

**Comment by LukaszKorek** [comment]
Dzień dobry. Wspieramy tutaj API na poziomie interface'u, a nie języka programowania. Dlatego poproszę o request i response w formacie xml. Pozwoli to na pełną weryfikację zgłoszenia.
