### ISSUE TITLE
Czy to prawda, że...

### ISSUE THREAD

**Issue by malytworca** [allegro/allegro-api#340]
Mówi się, że do wkręcenia jednej żarówki potrzeba czasami kilku osób. Jestem ciekaw jak wygląda to na allegro. Chodzi mi o stosunek ilości prezesów, do ilości pozostałych osób. Ponieważ jak widzę tempo rozwoju tego serwisu, a także poziom tego rozwoju, mam wrażenie, że pracuje tam jedna osoba. Czy to prawda?

**Comment by Onixarts** [comment]
Nie. Można się rozejść.
