### ISSUE TITLE
Request of the device code - Response: Unauthorized

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#3400]
Jestem nowy w pracy z API, więc błąd najprawdopodobniej wynika z nieświadomośći. Jednak już trzy dni nie rozumiem w czym polega problem.
Używam kodu z poradnika: https://developer.allegro.pl/auth/#DeviceFlow
```
curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'

```
dostaję:
`{"error":"Unauthorized","error_description":"Unauthorized"}`

- zakodowalem client_id:client_secret przy użyciu bash, próbowałem także użyć zasobu internetowego - to musi być w porządku
- client_id i client_secret mam dla zarejestrowanej aplikacji typu DEVICE

Proszę o pomoc

**Comment by asoio** [comment]
Czy przypadkiem nie jest tak, że client_id i client_secret masz wygenerowane dla sandboxa, a żądanie wysyłasz na bramkę produkcyjną?

**Comment by vartaller** [comment]
Dziękuję, problem rozwiązany. Czytalem na developer.allegro.pl o różnicy między tymi stronami, ale nadal nie rozumiem w czym to polega. Oddzielne konto jest używane dla sandboxa, więc muszę stale z nim pracować?

**Comment by asoio** [comment]
Dopóki chcesz testować api, to oczywiście powinieneś korzystać z sandboxa (i z parą client_id i client_secret wygenerowaną z konta sandboxowego), natomiast jak chcesz przejść na środowisko produkcyjne, to musisz wygenerować client_id i client_secret z normalnego konta Allegro.
