### ISSUE TITLE
GET sale/offer-events/ brak niektórych ofert 

### ISSUE THREAD

**Issue by wybitnygracz** [allegro/allegro-api#3401]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

 
dla GET sale/offer-events/

nie otrzymuje w wynikach niektórych aukcji dla przykładu aukcji nr 9199436350 mimo, że aukcja została zakończona dnia 05.07.2020, a wyniki ale/offer-events/  są od 2020-07-04 do chwili obecnej, to nie mogę odnaleźć w wynikach tej i wielu innych aukcji.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem dla tej oferty. Odpowiedni zespół już go analizuje.

**Comment by PrzemyslawLukanowski** [comment]
Czy problem w Twoim przypadku nadal występuje dla innych ofert? Niestety nie mamy już dostępu do logów powiązanych z tą ofertą.
