### ISSUE TITLE
Zakup zestawu - jak sprawdzić

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#3402]
Cześć

Czy istnieje jakiś prosty sposób na sprawdzenie, czy w danym checkout formie kupujący skorzystał z zakupu zestawu? Chodzi mi o te zestawy z zasobów /sale/loyalty/promotions.

Wiem, że można sprawdzić każdy line item i porównać cenę "originalPrice" z "price", ale - poprawcie mnie jeśli się mylę - czy tam ewentualnie nie mogą wpaść inne promocje, niezwiązane z zestawami?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Tam mogą pojawić się również rabaty ilościowe, gdzie cena pojedynczych przedmiotów zmienia się wraz z kupnem kolejnej sztuki.

**Comment by imper86** [comment]
@MaciejFrackowiak no właśnie, a więc czy jest możliwość sprawdzić czy w danej transakcji wykorzystano zestaw?

**Comment by MaciejFrackowiak** [comment]
@imper86 Nie, takiej bezpośredniej metody nie ma.

**Comment by imper86** [comment]
@MaciejFrackowiak mógłbyś to zapisać jako "sugestię dla odpowiedniego zespołu"? ;)

**Comment by MaciejFrackowiak** [comment]
@imper86 Robi się :)

**Comment by imper86** [comment]
Dzięki, zamykam w takim razie
