### ISSUE TITLE
Kod sms 

### ISSUE THREAD

**Issue by DKucia** [allegro/allegro-api#3403]
Witam , chce kupić produkt na sandbox żeby zasymulować proces kupna do testów , tylko mam problem bo ejst wymagany kod sms przy kupnie który nie przychodzi do mnie

**Comment by MaciejFrackowiak** [comment]
Proszę podaj szczegóły transakcji - czy próbowałeś zakupu jako niezarejstrowany użytkownik czy korzystałeś z konkretnego konta?

**Comment by DKucia** [comment]
Próbowałem jako gość i jako zarejestrowany użytkownik i za każdym razem wymagana jest "Weryfikacja numeru telefonu", tylko sms nie przychodzi

**Comment by MaciejFrackowiak** [comment]
Moje testowe zakupy za każdym razem prowadzą do weryfikacji poprzez email. Proszę podeślij poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=e2e1f990-74d6-4bea-9b5c-a408bde7983d&subjectId=da43023c-bc80-44ec-9a6d-d43df46b42a6) szczegóły Twoich prób zakupu wraz z nr telefonu, na który chciałeś otrzymać sms. W treści wiadomości przekaż proszę nr postu z GH - 3403.
