### ISSUE TITLE
Zdjecia / images

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#3404]
Próbuję dodać zdjęcie do draftu oferty i otrzymuje:

{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Function is not available. Contact the author of the application."}]}

Przy pomocy POST /sale/images prześlesz zdjęcie na https://upload.allegro.pl/allegrosandbox.pl/sale/images

Proszę o informacje

**Comment by MaciejFrackowiak** [comment]
Wywołaj POST na adresie: https://upload.allegro.pl.allegrosandbox.pl/sale/images, wówczas bez przeszkód dodasz zdjęcie.

**Comment by ButcherFromHell** [comment]
Dziękuje ! 
:)

**Comment by ButcherFromHell** [comment]
Obrazek się wgrywa - dostaje w odp jego url, natomiast przy dodawaniu draftu: 

[code] => VALIDATION_ERROR
                    [message] => Description images are not valid.
                    [details] => Invalid value: unknown
                    [path] => offerDto
                    [userMessage] => Description images are not valid.
?

**Comment by MaciejFrackowiak** [comment]
Czy do opisu oferty w drafcie użyłeś URL wygenerowany podczas uploadu? Przed momentem sprawdziłem działanie mechanizmu - bez przeszkód dodane wcześniej na serwer zdjęcie mogłem wykorzystać przy drafcie oferty.

**Comment by ButcherFromHell** [comment]
tak,
w tablicy 'images' oraz w 'section'

**Comment by MaciejFrackowiak** [comment]
Proszę prześlij poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) requesty, które wykonujesz wraz z ich trace-id. W treści zgłoszenia dodaj proszę numer postu z GitHub`a - 3404.
