### ISSUE TITLE
Adres E-mail kupującego

### ISSUE THREAD

**Issue by ebartlomiej89** [allegro/allegro-api#3407]
1. Czy adres E-mail zamawiającego ma zawsze postać: **[Stały kod (Wskaźnik użytkownika Allegro)]+[Losowe znaki]@allegromail.pl**?
2. Czy każdy adres e-mail zamawiającego na Allegro zawiera znak plusa jako łącznika danych?Czy każdy adres e-mail zamawiającego na Allegro zawiera znak plusa jako łącznika danych?
3. Czy znaki umieszczone przed plusem zawsze są takie same dla tego samego klienta? Czy ulegają czasowej zmianie?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na Twoje pytania:

1) "stałykodnadawcy+identyfikatortransakcji@allegromail.pl";

2) Tak, łącznikiem jest "+";

3) Tak, pierwszy człon jest stały dla danego użytkownika.

Zajrzyj proszę do [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL), gdzie szczegółowo opisaliśmy identyfikację e-mail.
