### ISSUE TITLE
Anulowanie zamówienia, a email wysłany przez Allegro

### ISSUE THREAD

**Issue by pokash** [allegro/allegro-api#3408]
Witam,
czy jest możliwość powiązania wiadomości o anulowaniu zamówienia wysłanej poprzez system Allegro, a informacjami o zamówieniu dostępnymi poprzez API?
Pytam, gdyż odnośniki w mailu nie powodują przeniesienia do konkretnego zamówienia.

Pozdrawiam,
Łukasz

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie mechanizmu - kliknięcie linku "Przejdź do zamówienia" z powiadomienia email przenosi do konkretnego, anulowanego zamówienia na stronie WWW:

![mail_order](https://user-images.githubusercontent.com/53566763/86781113-c5b9c880-c05d-11ea-8da5-67f2d9d7774d.png)

**Comment by pokash** [comment]
Odnośnik "PRZEJDŹ DO ZAMÓWIENIA" oczywiście przenosi do zamówienia,
jednakże, pozostałe dwa, nie przekierowują do:
a) konkretnej oferty na liście ofert
b) do zamówienia na liście zamówień

Chodź ten drugi przypadek jest niwelowany przez odnośnik "PRZEJDŹ DO ZAMÓWIENIA"

**Comment by MaciejFrackowiak** [comment]
Porady z "Co musisz teraz zrobić" mają charakter ogólny - nie mają kierować do konkretnej oferty / zamówienia.
Stąd zamieszczony odnośnik poniżej z bezpośrednim przekierowaniem do tego jednego, wybranego zamówienia.

**Comment by pokash** [comment]
Ok :) Dziękuję za info.
