### ISSUE TITLE
Lista tecdoc.kTypNr dla zapytania /sale/compatible-products

### ISSUE THREAD

**Issue by cybula95** [allegro/allegro-api#3409]
Czy istnieje możliwość, żeby do zapytania do endpointu "/sale/compatible-products" podać listę numerów kTypNr, czy trzeba wysyłać zapytania dla każdego kodu z osobna?
Jeżeli nie, to czy jest może coś takiego w planach?
W przypadku produktów, które mają kilkadziesiąt, a nawet kilkaset pasujących pojazdów jest to strasznie czasochłonne i niepotrzebnie obciążające sieć.

**Comment by MaciejFrackowiak** [comment]
Dla zasobu [GET /sale/compatible-products](https://developer.allegro.pl/documentation/#operation/getCompatibleProducts) możesz jako parametr wyszukiwania podać "tecdoc.kTypNr" - pole przyjmuje pojedynczą wartość. Szukasz pasujących części dla konkretnego pojazdu, stąd stricte tylko jeden typ - nie planujemy tu na chwilę obecną żadnej zmiany.
