### ISSUE TITLE
Photo Upload error

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#341]
Hello again,

I'm trying to upload an image to allegro for future use (in offer), but I get no error description.

My request: 

curl -X POST "https://upload.allegro.pl/sale/images" -H "authorization: Bearer {my access token}" -H "accept: application/vnd.allegro.beta.v1+json" -H 'content-type: "image/jpeg"' -H "accept-language: en-EN" --data-binary "@C:\Users\Horia\Desktop\husa.jpg"

Response:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 37 88181    0   119   37 32768    201  55351  0:00:01 --:--:--  0:00:01 70017{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/images","userMessage":null}]}

As you can see, the error message is null, how can I know what is wrong with my request?

Also, is it possible to send a picture directly from web (without downloading it first on my server).

For example, I have this picture : https://cdn.shopify.com/s/files/1/2135/3889/products/Husa_-_abstract_-_LG_G3_S_spo.jpg?v=1521304071 and I want to upload it directly. How can I achieve this ?

Thank you for your help and patience !

**Comment by MartaNowaczyk** [comment]
Hello, 
You can't upload images for future use. After 6 hours we will remove files unless you use it in your offer.

Can You check that error again and give me another response?

**Comment by AniaMalinowska** [comment]
In headers like content-type you should choose one type of data you send. For example, if you want to send photo in jpeg format, enter in the header content-type image/jpeg - not everything. 
We show in example all format which we supported.

**Comment by crevu** [comment]
You were right, thank you. It worked after leaving only one content-type. Also, I had to remove quotes - instead of 'content-type: "image/jpeg"', it should be 'content-type: image/jpeg'. So If anyone else stumbles upon this, here is the complete request that worked for me:

curl -X POST "https://upload.allegro.pl/sale/images" -H "authorization: Bearer {access_token}" -H "accept: application/vnd.allegro.beta.v1+json" -H 'content-type: image/jpeg' -H "accept-language: en-EN" --data-binary "@C:\Users\Horia\Desktop\husa.jpg"
