### ISSUE TITLE
Dokładniejsza informacja o walidacji opisów!

### ISSUE THREAD

**Issue by Onixarts** [allegro/allegro-api#3410]
Super! Podziękujcie temu/tym, kto przyczynił się do dodania tejże informacji. Wreszcie jak klienci do nas piszą, możemy od razu wskazać im rozwiązanie :) - na wypadek gdyby nie rozumieli o co chodzi. Masa roboty spadła nam z barków.

```
Tag "b" is a simple type, so it must have no children
```

```
Invalid tag "strong", expected one of {b}
```

Good job!

**Comment by MaciejFrackowiak** [comment]
Dziękujemy za miłe słowa - przekazaliśmy je bezpośrednio do zespołu odpowiedzialnego za zmianę.
