### ISSUE TITLE
Konto zablokowane - SANDBOX

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3411]
Od pewnego czasu dostaję informację, że moje konto na SANDBOX jest zablokowane. Nie mogę przez to wystawiać ofert. Czy mógłbym prosić o odblokowanie konta? 

LOGIN: TESTOWY_ZXC

**Comment by MaciejFrackowiak** [comment]
Na Twoim koncie widnieje blokada sprzedaży z powodu nieuregulowania należności wobec Allegro - skorzystaj proszę z symulatora płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i dokonaj wpłaty, wówczas blokada zostanie zniesiona.

**Comment by Radeq** [comment]
@MaciejFrackowiak , mam podobną sytuację na swoim koncie testowym, id użytkownika (/me)  43948417

Przy próbie wejścia na stronę rozliczenia otrzymuję błąd

Nie możemy wyświetlić strony
To nie Twoja wina

Czy można prosić o pomoc?

**Comment by MaciejFrackowiak** [comment]
@Radeq Potwierdzam problem z prawidłowym wyświetleniem strony Rozliczenia z Allegro - zgłosiłem to już do właściwego działu. Dam znać, gdy przywrócimy właściwe działanie zakładki.

**Comment by MaciejFrackowiak** [comment]
@Radeq Zakładka już funkcjonuje w pełni prawidłowo, możesz skorzystać z symulatora płatności.

**Comment by Radeq** [comment]
@MaciejFrackowiak , dziękuję - działa
