### ISSUE TITLE
Problem z utworzeniem produktu

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#3413]
Witam,

próbuje utworzyć produkt przy użyciu zasobu /sale/product-proposals ,a oto jego body:
{
	"parameters": [{
		"id": 224017,
		"rangeValue": null,
		"values": ["SCL-L01"],
		"valuesIds": []
	},
	{
		"id": 202685,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202685_212929"]
	},
	{
		"id": 225693,
		"rangeValue": null,
		"values": ["6901443087945"],
		"valuesIds": []
	},
	{
		"id": 127448,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["127448_1"]
	},
	{
		"id": 202693,
		"rangeValue": null,
		"values": ["72"],
		"valuesIds": []
	},
	{
		"id": 202697,
		"rangeValue": null,
		"values": ["144"],
		"valuesIds": []
	},
	{
		"id": 202701,
		"rangeValue": null,
		"values": ["9"],
		"valuesIds": []
	},
	{
		"id": 202705,
		"rangeValue": null,
		"values": ["155"],
		"valuesIds": []
	},
	{
		"id": 202749,
		"rangeValue": null,
		"values": ["5"],
		"valuesIds": []
	},
	{
		"id": 202745,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202745_213201"]
	},
	{
		"id": 202873,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202873_214265"]
	},
	{
		"id": 202753,
		"rangeValue": null,
		"values": ["294"],
		"valuesIds": []
	},
	{
		"id": 202757,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202757_213321"]
	},
	{
		"id": 202725,
		"rangeValue": null,
		"values": ["8"],
		"valuesIds": []
	},
	{
		"id": 202729,
		"rangeValue": null,
		"values": ["2"],
		"valuesIds": []
	},
	{
		"id": 202733,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202733_1"]
	},
	{
		"id": 202737,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202737_4"]
	},
	{
		"id": 219761,
		"rangeValue": null,
		"values": ["Qualcomm MSM8909 Snapdragon 210"],
		"valuesIds": []
	},
	{
		"id": 202849,
		"rangeValue": null,
		"values": ["1.1"],
		"valuesIds": []
	},
	{
		"id": 202877,
		"rangeValue": null,
		"values": ["4"],
		"valuesIds": []
	},
	{
		"id": 202869,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202869_214205"]
	},
	{
		"id": 202865,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202865_214137"]
	},
	{
		"id": 4388,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["4388_1"]
	},
	{
		"id": 202717,
		"rangeValue": null,
		"values": ["2200"],
		"valuesIds": []
	},
	{
		"id": 202713,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202713_213193"]
	},
	{
		"id": 202861,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202861_214101"]
	},
	{
		"id": 219765,
		"rangeValue": null,
		"values": ["Adreno 304"],
		"valuesIds": []
	},
	{
		"id": 219,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["219_4"]
	},
	{
		"id": 217,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["217_512"]
	},
	{
		"id": 202845,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202845_1"]
	},
	{
		"id": 202841,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202841_64"]
	},
	{
		"id": 202837,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202837_8"]
	},
	{
		"id": 202829,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202829_32"]
	},
	{
		"id": 202825,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202825_213921"]
	},
	{
		"id": 202821,
		"rangeValue": null,
		"values": [],
		"valuesIds": ["202821_213913"]
	}],
	"images": [{
		"url": "https://a.allegroimg.com/original/11bc99/5e00431a4428b1e2cbee5e437761"
	},
	{
		"url": "https://a.allegroimg.com/original/11b41f/0a5681bf469e8045d58eeebb21f9"
	},
	{
		"url": "https://a.allegroimg.com/original/116443/c2bac8a24a26b749055169d0973c"
	},
	{
		"url": "https://a.allegroimg.com/original/11ffd5/d78066c547e788aa44c3bbfbc0cd"
	},
	{
		"url": "https://a.allegroimg.com/original/115a72/90c15dc14a879bc437187b2ce97d"
	}],
	"category": {
		"id": "253389"
	},
	"eans": ["6901443087945"],
	"name": "HUAWEI Y6 SCL-L01 8GB KOLORY GRADE C+"
}

W odpowiedzi dostajemy:
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

Bardzo proszę o wskazanie czy to problem z requestem jest czy moze jakis bug po strnie api?

**Comment by MaciejFrackowiak** [comment]
Weryfikuję Twój request, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, mamy tu błąd - problem przekazałem już do właściwego zespołu.

**Comment by kylovile** [comment]
Ok, dziękuje za informacje. Czekamy na rozwiązanie problemu.

**Comment by tomasz-grzesik** [comment]
Otrzymuję podobny komunikat zarówno na sandboxie, jak i produkcji.
Czy problem nadal występuje?

**Comment by AureliuszBrussy** [comment]
Pracujemy jeszcze nad odpowiednim komunikatem błędu, natomiast rozwiązaniem jest to, abyś nie przekazywał w parametrze "valuesIds" pustej tablicy ("valuesIds": []). W takim przypadku powinieneś przekazać wartość null ("valuesIds": null) lub w ogóle pominąć to pole (wtedy także podstawiona zostanie wartość null).

**Comment by tomasz-grzesik** [comment]
Rzeczywiście, przed przekazaniem słownika parametrów, należało usunać klucze z pustymi listami.

**Comment by tomasz-grzesik** [comment]
@AureliuszBrussy, w tej chwili otrzymuję nieustannie komunikat:
"Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."
Nie dodałem produktu wcześniej. Nie sądzę, również, aby ktoś na sandboxie zaproponował podobny produkt.
Na produkcji to samo.

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik Prześlij proszę pełną strukturę requesta. Zweryfikuję problem.

**Comment by tomasz-grzesik** [comment]
Podaję najprosztszą wersję, która zwraca ten sam błąd (bez pola unit i options):
```
"curl` -X POST -H 'Accept: application/vnd.allegro.public.v1+json' -H "
 "'Accept-Encoding: gzip, deflate' -H 'Accept-Language: pl-PL' -H "
 "'Authorization: Bearer "
 "[wyciety access token]' "
 "-H 'Connection: keep-alive' -H 'Content-Length: 540' -H 'Content-Type: "
 "application/vnd.allegro.public.v1+json' -H 'User-Agent: "
 'python-requests/2.21.0\' -d \'{"parameters": [{"values": ["12345"], "id": '
 '"224017"}, {"valuesIds": ["127788_280137"], "id": "127788"}, {"valuesIds": '
 '["222521_299589"], "id": "222521"}, {"values": ["32"], "id": "222537"}, '
 '{"valuesIds": ["127768_72"], "id": "127768"}, {"valuesIds": ["4906_2"], '
 '"id": "4906"}, {"valuesIds": ["127789_1", "127789_2"], "id": "127789"}, '
 '{"values": ["5904017036777"], "id": "225693"}], "category": {"id": "50685"}, '
 '"name": "Zeszyt A5", "images": [{"url": '
 '"https://a.allegroimg.allegrosandbox.pl/original/1160c5/07e72d624422930bd355544cf3df"}]}\' '
 'https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals'
```

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik produkt ten już istnieje zarówno na sandboxie, jak i na produkcji. Id produktu to odpowiednio:
- na sandboxie: 8c8580e8-8c58-4649-aa33-882bb19b1352
- na produkcji: d373a976-9ec8-4be5-b847-95b36052d25f

**Comment by tomasz-grzesik** [comment]
Udało się. Nie zauważyłem, że Allegro samo wcześniej podpięło produkt podczas wystawiania.
