### ISSUE TITLE
Nie mogę utworzyć nowego konta do sandbox

### ISSUE THREAD

**Issue by C3C-Marek** [allegro/allegro-api#3414]
Witam, nie mogę utworzyć konta dla sklep@c3c.pl. Próbowałem kilkanaście razy przez kilka dni i nigdy nie dostaje żadnego maila z linkiem potwierdzającym. Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi i widzę, że wiadomości dostarczamy na Twoją skrzynkę - ostatnie udane doręczenie miało miejsce 2020/07/10 03:25:45.

Wiadomości z Sandbox przesyłane są w postaci załącznika w formacie *.eml - część serwerów pocztowych traktuje je jako spam, itp. Sprawdź proszę dokładnie ustawienia serwera pocztowego.

**Comment by C3C-Marek** [comment]
Niestety okazuje się, że AZ.PL nie przepuszcza załączników *.eml. Założyłem konto gdzie indziej i poszło. Dzięki
