### ISSUE TITLE
[API] stock and price update

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#3416]
Hello.

Does API has a way to fast update only product stock and price only? without update all product.

Thanks a lot

**Comment by MaciejFrackowiak** [comment]
Yes, we have that kind of resources:

1) [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) you can change offers price;
2) [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT) you can change quantity;

Please, look into [our tutorial](https://developer.allegro.pl/en/my_offers/#editing-many-offers).

**Comment by Folganoid** [comment]
ok thanx a lot
