### ISSUE TITLE
webAPI - brak szczegółowych opcji nt. kraju dostawy

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#342]
Request doGetSellFormFieldsForCategory zwracam nam następujące dane:

sellFormId | 9
-- | --
sellFormTitle | Kraj
sellFormCat | 0
sellFormType | 2
sellFormResType | 2
sellFormDefValue | 0
sellFormOpt | 1
sellFormPos | 9
sellFormLength | 50
sellMinValue | 0.00
sellMaxValue | 0.00
sellFormDesc |  
sellFormOptsValues |  
sellFormFieldDesc | Wybierz z listy kraj
sellFormParamId | 0
sellFormParamValues |  
sellFormParentId | 0
sellFormParentValue |  
sellFormUnit |  
sellFormOptions | 0

Proszę wskazać, gdzie tutaj mamy informację, o możliwych krajach do wyboru?

**Comment by AniaMalinowska** [comment]
Metoda [doGetSellFormFieldsForCategory](https://allegro.pl/webapi/documentation.php/show/id,782) zwraca informacje jakie pola należy uzupełnić przy danej kategorii. Aby sprawdzić jaki podać kraj, należy użyć metody [doGetCountries](https://allegro.pl/webapi/documentation.php/show/id,25). Dodam, że dla Polski jest to Identyfikator o wartości "1".
