### ISSUE TITLE
Zapytanie o system umożliwiający automatyczne pobieranie parametrów wystawianych produktów na Allegro

### ISSUE THREAD

**Issue by Doman111** [allegro/allegro-api#3420]
Witam, potrzebuję porady. 
Które oprogramowanie dostępne na rynku, służące do obsługi modelu dropshipping, umożliwia wymianę informacji między zasobami Allegro, a oprogramowaniem zewnętrznym?
Zależy mi na możliwości AUTOMATYCZNEGO POBIERANIA (z bazy Allegro) PARAMETRÓW DLA WYSTAWIANYCH PRODUKTÓW - np. na podstawie nr EAN
(na takiej zasadzie jak opcja na karcie poduktu w panelu Allegro: AKCJE > EDYTUJ > "Czy uzupełnić parametry dla..." > TAK, UZUPEŁNIJ).
Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Jako Allegro nie możemy wskazać konkretnych rozwiązań, ponieważ nie jesteśmy autorem takiego oprogramowania - natomiast z pewnością użytkownicy naszego forum podzielą się z Tobą swoimi doświadczeniami.

**Comment by Aryak2099** [comment]
Tak jest to możliwe napisz do mnie na priv lub tutaj podaj adres email.

**Comment by Doman111** [comment]
Dzień dobry, dziękuję za kontakt.

 

Poszukujemy systemu, który posiada narzędzia do zarządzania sprzedażą głównie na Allegro ( w przyszłości dodatkowo na eBay i Amazon)

oraz w sklepie internetowym - WSZYSTKIE KANAŁY SPRZEDAŻY W PANELU JEDNEGO SYSTEMU.

Obecnie głównie zależy nam na poniższych funkcjach (Oszczędność czasu + Pełna funkcjonalność),

które zapewniają możliwość SZYBKIEGO wystawiania DUŻEJ ILOŚCI, KOMPLETNYCH ofert na Allegro (głównie dropshipping),

 

MASOWE AKCJE:

- Automatyczne dopasowanie do szablonu: Tytułu, opisu, zdjęć

- Automatycznie pobierane PARAMETRY PRODUKTÓW z Allegro przez API dla wszystkich wystawianych ofert (oraz automatyczne przypisanie pobranych parametrów DO PRODUKTU)

- Wystawianie produktów W WIELU KATEGORIACH jednocześnie

- Masowa edycja szablonów cenników (PROGI KWOTOWE - narzuty cenowe na prod. z poszczególnych hurtowni) z możliwością podpięcia cenników do wielu kategorii o tej samej prowizji Allegro oraz osobno

- SUGESTIE CEN / PROGÓW KWOTOWYCH dla poszczególnych produktów / kategorii Allegro

- Osobne progi kwotowe dla Sklepów (z mozliwością SZYBKIEGO ZARZĄDZANIA CENAMI)

- Automatyczna WIELOWARIANTOWOŚĆ Allegro

- Automatyczna klasyfikacja do CENNIKÓW WYSYŁEK

 

+ Automatyczne wystawianie Faktur VAT (oraz wysyłka faktur PDF na e-mail) + możliwość wystawiania Faktur PROFORMA, Faktur korygujących

+ Możliwość generowania pliku JPK FAKTURA dla poszczególnych miesięcy

+ Możliwość pobrania już trwajacych aukcji Allegro do Systemu (oraz automatycznego uzupełnienia parametrów)

+ Automatyzacja procesów wystawiania ofert i sprzedaży (zmiana statusów zamówień, wiadomości do Kupujacych itp.)

+ Możliwość obsługi zwrotów i reklamacji

+ Możliwość (najlepiej automatycznego) składania zamówień w hurtowniach z poziomu Systemu

+ Obsługa wiadomości od Kupujacych i dyskusji (+ autoresponder)

 

Proszę o informację dot. systemu, który zapewni nam wymienione funkcjonalności,

głównie umożliwiającego automatyczne pobieranie parametrów wystawianych produktów na Allegro

 

Pozdrawiam

**Comment by Doman111** [comment]
Witam, biuro@rproject.pl
