### ISSUE TITLE
PUT sale/offers/{id} validation error

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#3423]
Witam,

Od niedawna mam problem z PUT sales/offers/{id}
Oferta, którą wysyłam wygląda następująco: 
{
  "id": "9021409124",
  "name": "Dekoria Chlebak na pieczywo Bamboo black 34x21x20",
  "category": {
    "id": "49871"
  },
  "product": null,
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "11484",
      "valuesIds": [
        "11484_4096"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "237190",
      "valuesIds": [],
      "values": [
        "metal"
      ],
      "rangeValue": null
    },
    {
      "id": "228921",
      "valuesIds": [
        "228921_336117"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "17448",
      "valuesIds": [],
      "values": [
        "3"
      ],
      "rangeValue": null
    },
    {
      "id": "225693",
      "valuesIds": [],
      "values": [
        "5400586354750"
      ],
      "rangeValue": null
    },
    {
      "id": "237190",
      "values": [
        "Dekoria"
      ]
    },
    {
      "id": "219809",
      "values": [
        "813-062"
      ]
    }
  ],
  "ean": "5400586354750",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>Chlebak na pieczywo Bamboo black, 35 x 21,5 x 20,5 cm<\/h1>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/117b67\/32c2aa7a4751b930f4e042b934af"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Kod produktu: <\/b>813-062<\/p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Du\u017cy chlebak na pieczywo wykonany z metalu.<\/b><\/p> <p><\/p> <p><b> <\/b>Pe\u0142ni tradycyjn\u0105 funkcj\u0119 chlebaka, a jego bambusowa pokrywa mo\u017ce by\u0107 tak\u017ce wykorzystana jako <b>deska do krojenia<\/b> czy te\u017c serwowania, np. ser\u00f3w.<\/p> <p>Nada kuchni nowoczesnego charakteru.<\/p> <p>Ciekawy spos\u00f3b otwierania i zamykania chlebaka poprzez przesuni\u0119cie poziomo deski bambusowej w prawo b\u0105d\u017a w lewo<\/p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Dane produktu<\/b><\/p><ul><li><b>Waga:<\/b> 1.58kg<\/li><li><b>Rozmiar:<\/b> 35 x 21,5 x 20,5 cm<\/li><li><b>Materia\u0142:<\/b> drewno, metal<\/li><li><b>Kolor:<\/b> czarny<\/li><\/ul>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/1156ac\/2acfa7ac488fb618445b27497501"
          },
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/116c24\/73967296464f8b0a16ad1ff0b8a9"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tecdocSpecification": null,
  "images": [
    {
      "url": "https:\/\/a.allegroimg.com\/original\/117b67\/32c2aa7a4751b930f4e042b934af"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/1156ac\/2acfa7ac488fb618445b27497501"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/116c24\/73967296464f8b0a16ad1ff0b8a9"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "141",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "tax": null,
  "stock": {
    "available": 2,
    "unit": "UNIT"
  },
  "publication": {
    "duration": null,
    "status": "ENDED",
    "startingAt": null,
    "endingAt": null,
    "endedBy": "USER",
    "republish": false
  },
  "delivery": {
    "shippingRates": {
      "id": "10083882-ee5f-445e-adb0-c604d49e71d2"
    },
    "handlingTime": "PT48H",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "bc886de2-a1bf-4f36-b748-43dccb36614c"
    },
    "returnPolicy": {
      "id": "a01edae3-fe52-49e2-b468-7fa00c622acd"
    },
    "warranty": {
      "id": "a981f7d1-f0f5-4d62-8b53-cf4b0e179717"
    }
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "DOLNOSLASKIE",
    "city": "\u017bar\u00f3w",
    "postCode": "58-130"
  },
  "external": {
    "id": "813-062"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [],
    "validatedAt": "2020-05-05T11:11:49.229Z"
  },
  "createdAt": "2020-03-04T12:34:37.000Z",
  "updatedAt": "2020-07-02T01:48:27.879Z"
}

Odpowiedzią API jest:

[
  {
    "code": "VALIDATION_ERROR",
    "message": "You can only enter the parameter once.",
    "details": "",
    "path": "",
    "userMessage": "You can only enter the parameter once."
  }
]

Czy mogę dostać odpowiedź na pytanie "dlaczego tak się dzieje". Jeśli odpowiedzią jest stwierdzenie 'w ofercie jest  "product": null,' od razu dodam, że takie dane (bez ustawionego 'product') dostaję GET-em z endpointu /sale/offers/{id}. Zatem być może to błąd Allegro?
Pozdrawiam,

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałeś ten błąd, ponieważ parametr 237190 przekazałeś dwukrotnie, usuń jeden z nich.

**Comment by adamTynski** [comment]
Faktycznie, dziękuję
