### ISSUE TITLE
Przedsprzedaż a wystawianie nowej oferty

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3425]
Nie znalazłem żadnych informacji nt. przedsprzedaży innej niż na stronie: https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/przedmioty-w-przedsprzedazy-D5AgVlPDdiE

czy przy przygotowywaniu drafta oferty należy zaznaczyć jakieś pole? czy wystarczy tylko informacja w cenniku dostaw+opisie oferty? Z góry dziękuję za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Wystarczy, że uzupełnisz odpowiednio pola:
- delivery.handlingTime,
- delivery.shipmentDate.

Oraz, zgodnie z podlinkowanym artykułem, zaznaczysz taką informację w opisie oferty.

**Comment by jakubriegel** [comment]
@PrzemyslawLukanowski czy jak ustawimy te pola dla aktywnej oferty to przełączy się ona w tryb przedsprzedaży?

**Comment by PrzemyslawLukanowski** [comment]
@jakubriegel Tak, operacja zakończy się powodzeniem i dane zostaną zaktualizowane na stronie oferty.

**Comment by jakubriegel** [comment]
Dzięki
