### ISSUE TITLE
Moje zakupy

### ISSUE THREAD

**Issue by pwujczyk** [allegro/allegro-api#3426]
Chciałbym napisać aplikację do sprawdzania czy zgłoszony zwrot został rzeczywiście wykonany przez sprzedającego. Potrzebuje do tego listy zakupów z adresu https://allegro.pl/moje-allegro/zakupy/kupione. Przeglądałem dokumentację (https://developer.allegro.pl/documentation/) i nie widzę odpowiedniego endpointu. Na forum jednak jest wątek w którym zagnagaspo  znałazł odpowiednią metodę (https://github.com/allegro/allegro-api/issues/1441). Teraz metoda z tego co widzę nie jest dostępna.

Czy posiadacie metodę która zwróci mi listę zakupów, moich (czyli stronę klienta a nie sprzedawcy)

**Comment by PrzemyslawLukanowski** [comment]
Nie mamy takiego zasobu. W REST API skupiamy się na funkcjonalnościach dla sprzedawcy.

**Comment by pwujczyk** [comment]
Dzięki
