### ISSUE TITLE
TAG w REST API

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#343]
W jaki sposób można stosować tagi dla ofert przez REST API?

Znaleźliśmy tylko tutaj informację:
https://allegro.pl/pomoc/faq/tagi-ofertowe-1ME1Gkv2lHb

**Comment by AniaMalinowska** [comment]
Aktualnie przez REST API nie obsłużysz tagów. Pracujemy nad tym.
Gdy już udostępnimy taką możliwość, poinformujemy o tym w stosownym komunikacie.
