### ISSUE TITLE
Zmiana statusu zamówienia

### ISSUE THREAD

**Issue by patrys666** [allegro/allegro-api#3434]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas próby zmiany statusu zamówienia za pomocą:
`$jayParsedAry = [
   "status" => "READY_FOR_SHIPMENT"
]; 

$response = $api->order->{"checkout-forms/6a356342-c5ce-11ea-af54-bdb0f3255c5/fulfillment"}->put($jayParsedAry);`

Otrzymuję komunikat:

`{"errors":[{"code":"SellerOrdersStoreUnprocessableEntityException","message":null,"details":null,"path":"/order/checkout-forms/6a356342-c5ce-11ea-af54-bdb0f3255c5/fulfillment","userMessage":null}]}`

Czy występuje jakiś problem z tym zasobem?

**Comment by PrzemyslawLukanowski** [comment]
Zamówienie o takim ID nie istnieje lub próbujesz zmienić status, będąc zautoryzowanym jako użytkownik, który nie jest jego właścicielem. Do tego użytkownika przypisane są tylko dwa zamówienia: 57741a22-c688-11ea-8657-9384e8b533d7 oraz 6a356342-c5ce-11ea-af54-bdb0f3255c52.

**Comment by patrys666** [comment]
Dla zamówienia 57741a22-c688-11ea-8657-9384e8b533d7 zmienia status natomiast dla drugiego już nie.

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach widzę, że o 14:52 próbowałeś zmienić status na READY_FOR_SHIPMENT i to się udało - taki status zobaczysz w polu fulfillment.status, jeśli pobierzesz zamówienie przez GET /order/checkout-forms/6a356342-c5ce-11ea-af54-bdb0f3255c52. Status 422 zwróciliśmy, gdy "ucięło" Tobie ostatni znak w ID zamówienia, zamiast: 6a356342-c5ce-11ea-af54-bdb0f3255c52 przekazywałeś: 6a356342-c5ce-11ea-af54-bdb0f3255c5.

**Comment by patrys666** [comment]
Faktycznie..mój błąd. Dziękuje za pomoc.
