### ISSUE TITLE
Aktywacja konta - SANDBOX

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3438]
Dzień dobry,

Proszę o aktywację konta Client:44112746 na środowisku SANDBOX. Podczas "manualnej" aktywacji (wysyłanie plików, przepisywanie kodu z obrazka ) rzuca błąd 403. 

Z góry dziękuję. :)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto, spróbuj ponownie przepisać kod z obrazka i wysłać pliki.

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski dzięki, tym razem poszło. Prosiłbym jeszcze o zaakceptowanie tych zmian.

**Comment by PrzemyslawLukanowski** [comment]
Powinieneś już mieć dostęp do wszystkich operacji.

**Comment by thefoe76** [comment]
nie mogę aktywowac konta pomimo posiadania linku aktywacyjnego 
https://t.allegro.pl.allegrosandbox.pl/rejestracja/?utm_source=notification&utm_medium=PLnonRegisteredUserRemindEmail&utm_campaign=non-registered-user-remind&tr_n=activation_link&tr_id=85a502ce-3cd0-4806-9911-7bc2843d416b&tr_d=allegro.pl.allegrosandbox.pl&tr_f=/confirm/c8299e6430cd47a09fe6413bd381fe6a&tr_s=rgyFZzkT

**Comment by MaciejFrackowiak** [comment]
@thefoe76 W wątku GitHub #1046 aktywowałem już Twoje konto.
