### ISSUE TITLE
How to upload images from web

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#344]
Hi guys,

How can I upload an image using an external url ? I want to avoid downloading all my product images locally before I send them to allegro. 
Is there any way I can transfer the images by providing a valid url instead of a local file path? 

This is what I tried:

**Request:**
curl -X POST "https://upload.allegro.pl/sale/images" -H "authorization: Bearer {access_token}" -H "accept: application/vnd.allegro.beta.v1+json" -H 'content-type: image/gif' -H "accept-language: en-EN" --data-binary "@https://cdn.shopify.com/s/files/1/2135/3889/products/Husa_-_abstract_-_APPLE_IPHONE_4S_spo.jpg?v=1521300309"

**Response:**
Warning: Couldn't read data from file
Warning: "https://cdn.shopify.com/s/files/1/2135/3889/products/Husa_-_abstract_
Warning: -_APPLE_IPHONE_4S_spo.jpg?v=1521300309", this makes an empty POST.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   125    0   125    0     0    216      0 --:--:-- --:--:-- --:--:--   276{"errors":[{"code":"400","message":"400 Bad Request","details":null,"path":null,"userMessage":"Request body not readable."}]}

Thank you !

**Comment by AniaMalinowska** [comment]
No. You can not add a picture by sending an URL. You must send a file.

**Comment by crevu** [comment]
Ok, thank you !
