### ISSUE TITLE
Brak przekierowania po autoryzacji użytkownika

### ISSUE THREAD

**Issue by sc4rface97** [allegro/allegro-api#3441]
Występuje problem:
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam. Mam problem z autoryzacją zarówno na środowisku sandboxowym, jak i na produkcyjnym. Nadmienię, że prowadzę testy na localhoście. Otóż - generuję link w postaci:

https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={callback}&prompt=confirm

Gdzie naturalnie {client_id} - podmieniam ID klienta zarejestrowanej aplikacji na sandboxie, a {callback} zamieniam na adres localhostowy, gdzie chcę odebrać dane zwrotne. Niestety - po poprawnym zalogowaniu do konta allegro, przekierowanie nie następuje, a ja otrzymuję informację:

Nie możemy wyświetlić strony
Numer błędu: 5fd89656aeb2d97c

Żeby rozwiać wątpliwości, oczywiście stosuję autoryzację sandboxową i korzystam z danych sandboxowych. W czym leży problem?

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd świadczy o tym, że adres, który przekazałeś dla redirect_uri róźni się od tego, który podałeś na stronie https://apps.developer.allegro.pl/ (lub https://apps.developer.allegro.pl.allegrosandbox.pl/). Upewnij się, że jest to taki sam adres.

**Comment by sc4rface97** [comment]
> Ten błąd świadczy o tym, że adres, który przekazałeś dla redirect_uri róźni się od tego, który podałeś na stronie https://apps.developer.allegro.pl/ (lub https://apps.developer.allegro.pl.allegrosandbox.pl/). Upewnij się, że jest to taki sam adres.

**Comment by sc4rface97** [comment]
> Ten błąd świadczy o tym, że adres, który przekazałeś dla redirect_uri róźni się od tego, który podałeś na stronie https://apps.developer.allegro.pl/ (lub https://apps.developer.allegro.pl.allegrosandbox.pl/). Upewnij się, że jest to taki sam adres.

Racja, teraz śmiga. Dzięki za pomoc ;)
