### ISSUE TITLE
Billing entries - sortowanie niemalejące?

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#3445]
Według dokumentacji:

> The billing entries are sorted in a descending order (newest first) by date on which they occurred.

Jest szansa, że doczekamy się możliwości sortowania w drugą stronę? Ułatwiłoby to zebranie wpisów od konkretnej daty do dziś.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy tego w planach, możesz jednak wykorzystać parametry occurredAt.gte (najwcześniejsza data wystąpienia operacji) i occurredAt.lte (najpóźniejsza data wystąpienia operacji).

**Comment by radoslawkoziol** [comment]
@PrzemyslawLukanowski tak wiem, tylko biorąc pod uwagę fakt, że limit jest ustawiony na 100, to musiałbym ten przedział ustawiać praktycznie na minutę lub dwie, przy niektórych klientach. Z drugiej strony używanie limitu + offset + daty też nie jest idealne, bo offset jest maks 1000, co czasem nie wystarcza przy zakresie dobowym. Żaden z tych sposobów nie będzie optymalny. 

Sortowanie w drugą stronę rozwiązałoby problem, myślę że wiele osób to potwierdzi.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie planujemy takiej funkcjonalności. Zapisałem ją jednak do naszych sugestii - jeżeli coś zmieni się w tym temacie, poinformuję.
