### ISSUE TITLE
Konta sandbox - brak możliwości zalogowania

### ISSUE THREAD

**Issue by harorri** [allegro/allegro-api#3446]
Witam,
Gdy próbuję zalogować się na moje konta allegro dostaję komunikat: **Login, e-mail lub hasło są nieprawidłowe.** (loginy oraz hasła są dobre, prosiłem również współpracowników o zalogowanie się na swoje i mają ten sam problem).

Dodatkowo przy próbie rejestracji nowego konta, po wpisaniu loginu oraz hasła mam ciągle komunikat **Wystąpił błąd serwera Spróbuj odświeżyć stronę za jakiś czas.**

**Comment by rumiak** [comment]
Witam,
Mam dokładnie ten sam problem podczas próby rejestracji nowego konta.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, operacje w moim przypadku przebiegły prawidłowo. Czy problem nadal występuje?

**Comment by harorri** [comment]
Sprawdziłem. Problem z zalogowaniem już nie występuje, błąd przy rejestracji również. Thx.
