### ISSUE TITLE
Unallowed image type.

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#3447]
Jestem nowy w pracy z API, więc błąd najprawdopodobniej wynika z nieświadomośći. Rozmiary zdjęć odpowiadają wymaganiom, ale mam błąd - "Unallowed image type."

```
$post = array('file_contents'=> "@/media/volodymyr/C9A0-4DAF/Soft/AllegroAPI/products/${id_prod}/${n_jpeg}.jpg");
        print_r($post);
// tutaj output: [file_contents] => @/media/volodymyr/C9A0-4DAF/Soft/AllegroAPI/products/6755796754/1.jpg
        $ch = curl_init();
    
        curl_setopt($ch, CURLOPT_URL, 'https://upload.allegro.pl.allegrosandbox.pl/sale/images');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        include 'token.php';
        $headers = array();
        $headers[] = "Authorization: Bearer $token_day";
        $headers[] = 'Accept: application/vnd.allegro.public.v1+json';
        $headers[] = 'Content-Type: image/jpeg';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
```

**Comment by Aryak2099** [comment]
-d '{
       "url":"https://link.jpg"       -- wymagane, link do obrazka
      }'     
zwróc uwagę na https też żeby było.

**Comment by vartaller** [comment]
Przesyłam plik z mojego komputera, musze wpisać  "url":"https:// przed ścieżką do lokalizacji obrazu ?

**Comment by PrzemyslawLukanowski** [comment]
"url" musisz wpisać, jeśli przesyłasz zdjęcie w postaci linku, nie - jeśli binarnie. Prześlij nam proszę przykładowy request i response  (wraz z problematycznym zdjęciem) w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #3447.
