### ISSUE TITLE
Offer detail

### ISSUE THREAD

**Issue by kvinkinamoto** [allegro/allegro-api#3449]
Jak mogę uzyskać szczegółowe informacje z ogłoszenia (oferty), takie jak parametry produktu i opis, jeśli nie jestem właścicielem tego ogłoszenia. Jak mogę uzyskać informacje o najwyższym koszcie wysyłki? Ponieważ teraz API zwraca tylko najniższą cenę.

**Comment by MaciejFrackowiak** [comment]
Takie informacje nie są dostępne w REST API, nie będą też upublicznione w przyszłości - komunikat w tej sprawie zamieściliśmy w poście #3377
