### ISSUE TITLE
Czas trwania jest zmieniany na "30 dni" dla formatu oferty "Sklep"

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#345]
Przy wystawianiu oferty o formacie sprzedaży **"Sklep (bez licytacji)**" (`fid = 29, fvalueInt = 1`), czas trwania oferty jest zmieniany na **"30 dni"**.

Błąd występuje dla ofert wystawianych przez WebApi, dla ofert sklepowych wystawianych przez WWW błąd nie występuje i można np. wystawić ofertę z czasem trwania **"7 dni"** (`fid = 4, fvalueInt = 2`)

Przykład requesta do wystawienia oferty sklepowej z czasem trwania "7 dni", który pojawia się w serwisie z czasem trwania "30 dni":

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoNewAuctionExtRequest>
         <ser:sessionHandle>${#Project#sessionId}</ser:sessionHandle>
         <ser:fields>
            <ser:item>
               <ser:fid>1</ser:fid>
               <ser:fvalueString>Oferta na 7 dni</ser:fvalueString>
           </ser:item>
            <ser:item>
               <ser:fid>2</ser:fid>
              <ser:fvalueInt>252214</ser:fvalueInt>
           </ser:item>
            <ser:item>
               <ser:fid>3</ser:fid>
              <ser:fvalueDatetime>1530136800</ser:fvalueDatetime>
           </ser:item>
             <ser:item>
               <ser:fid>4</ser:fid>
              <ser:fvalueInt>2</ser:fvalueInt>
           </ser:item>
              <ser:item>
               <ser:fid>5</ser:fid>
              <ser:fvalueInt>7</ser:fvalueInt>
           </ser:item>
               <ser:item>
               <ser:fid>8</ser:fid>
              <ser:fvalueFloat>77</ser:fvalueFloat>
           </ser:item>
              <ser:item>
               <ser:fid>9</ser:fid>
              <ser:fvalueInt>1</ser:fvalueInt>
           </ser:item>
               <ser:item>
               <ser:fid>10</ser:fid>
              <ser:fvalueInt>15</ser:fvalueInt>
           </ser:item>
               <ser:item>
               <ser:fid>11</ser:fid>
              <ser:fvalueString>Poznań</ser:fvalueString>
           </ser:item>
               <ser:item>
               <ser:fid>28</ser:fid>
              <ser:fvalueInt>0</ser:fvalueInt>
           </ser:item>
               <ser:item>
               <ser:fid>29</ser:fid>
              <ser:fvalueInt>1</ser:fvalueInt>
           </ser:item>
                <ser:item>
               <ser:fid>32</ser:fid>
              <ser:fvalueString>60-166</ser:fvalueString>
           </ser:item>
             <ser:item>
               <ser:fid>341</ser:fid>
                <ser:fvalueString>{  "sections":   [{        "items":         [{              "type"   : "TEXT",              "content": "&lt;p&gt;VAM18&lt;/p&gt;"         }]  }]}</ser:fvalueString>
           </ser:item>
                <ser:item>
               <ser:fid>23669</ser:fid>
               <ser:fvalueInt>1</ser:fvalueInt>
           </ser:item>
                <ser:item>
               <ser:fid>24340</ser:fid>
               <ser:fvalueInt>1</ser:fvalueInt>
           </ser:item>
               <ser:item>
               <ser:fid>61</ser:fid>
              <ser:fvalueFloat>11</ser:fvalueFloat>
           </ser:item>
         </ser:fields>
     </ser:DoNewAuctionExtRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

Po zamianie 

               <ser:fid>29</ser:fid>
              <ser:fvalueInt>1</ser:fvalueInt>
 
na 

               <ser:fid>29</ser:fid>
              <ser:fvalueInt>0</ser:fvalueInt>
 
oferta pojawia się z poprawnym czasem trwania **"7 dni"**.

**Comment by MaciejPotepa** [comment]
Jest to efekt ostatnich zmian, którego wprowadziliśmy. Nie da się już wystawić oferty w formacie sklepowym. Więcej informacji znajdziesz [tutaj](https://allegro.pl/webapi/news.php#news_100621).

**Comment by k4pit4n** [comment]
Dzięki za wyjaśnienia. Zauważyłem jednak, że przy wystawianiu ofert przez WWW opcje dostępne w comboboxie **Czas trwania** są zależne od wyboru formatu oferty, mianowicie po zaznaczeniu "Licytacji" nie są dostępne czasy trwania **"20 dni"** oraz **"30 dni"**. Jeśli wybrany format sprzedaży jest obecnie bez znaczenia, to nie powinien on mieć wpływu na dostępność opcji przy wyborze **Czasu trwania**.

**Comment by MaciejPotepa** [comment]
Format sprzedaży nie jest bez znaczenia. **Licytacja** i **Kup Teraz** to dwie odrębne opcje. 
W **Licytacji** jest cena minimalna i wywoławcza.  
Dodatkowo, z perspektywy biznesowej licytacja czasem większym niż 10 dni się absolutnie nie sprawdza.

**Comment by k4pit4n** [comment]
To zapytam inaczej, załóżmy, że mamy ofertę z opcją "**Kup teraz**" i czasem trwania "7 dni". Użytkownik chce zmienić czas trwania tej oferty. Skąd program ma wiedzieć, czy chodzi o ofertę "**Kup teraz**" czy o "**Licytację**"? Pośrednio można to wywnioskować np. na podstawie ceny wywoławczej (obowiązkowej przy "**Licytacji**"), ale czy jest możliwość bezpośredniego stwierdzenia tego faktu?

**Comment by MaciejPotepa** [comment]
> Skąd program ma wiedzieć, czy chodzi o ofertę "Kup teraz" czy o "Licytację"? 
Ceny dla **Kup Teraz** i **Licytacji** są podawane w różnych FIDach, na podstawie tego program może rozróżnić co jest czym i jakie wartości można do tego przypisać.

**Comment by k4pit4n** [comment]
Dziękuję za odpowiedź,
