### ISSUE TITLE
Shipping rates

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#3450]
Hi,

Is it possible to add multiple delivery methods/shipping rates for specific offers? For example, for some offers we have "Allegro Pocztex Kurier48" and GLS and for some we have only GLS.

Thank you

**Comment by MaciejFrackowiak** [comment]
You should create shipping rates for every combination of your delivery methods. You can add a maximum 250 shipping rates using [POST /sale/shipping-rates](https://developer.allegro.pl/documentation/#operation/createShippingRatesSetUsingPOST). Then you can assign it to offers, e.g. shipping rate A to offer B and C, shipping rate Z to offer X and Y, etc.
