### ISSUE TITLE
Wygasanie statusu zleceń

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#3451]
Po jakim czasie od dodania zlecenia zmiany ceny/ilości - status zlecenia pod adresem: _/sale/offer-price-change-commands/{commandId}/tasks_ wygasa, tzn. zacznie zwracać COMMAND_NOT_FOUND ?

**Comment by MaciejFrackowiak** [comment]
Obecnie jest to 7 dni.

**Comment by vitapak** [comment]
Czy można wiedzieć kiedy ostatnio była aktualizacja tego mechanizmu? 
Jeszcze niedawno chyba zlecenia wisiały dosyć długo

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, w ostatnim czasie ograniczyliśmy przedział czasu, w którym zwracamy status wykonania danego commandId.
