### ISSUE TITLE
Wysokość prowizji

### ISSUE THREAD

**Issue by brawatbrawat** [allegro/allegro-api#3452]
Czy możliwe jest wysyłanie przez API informacji o wysokości prowizji konkretnego zamówienia (produkt+koszty dostawy)?

**Comment by MaciejFrackowiak** [comment]
Korzystając z zasobu [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) pobierzesz historię opłat - możesz użyć filtrów offer.id oraz occurredAt.gte / occurredAt.lte by doprecyzować czas ich naliczenia w korelacji z datą zamówienia.
