### ISSUE TITLE
Stworzenie linku do zakupionego ebooka

### ISSUE THREAD

**Issue by dgtlmstr** [allegro/allegro-api#3453]
Dzień dobry,
Chcemy sprzedawać na Allegro ebooki i odpowiednie zintegrować się poprzez Państwa API. Proszę uprzejmie o informacje, gdzie mogę znaleźć szczegóły, w jaki sposób mamy dostarczać klientom linki do zakupionych ebooków oraz jaki są do tych linków wymagania?
Dziękuję!

**Comment by MaciejFrackowiak** [comment]
Sprzedaż w kategorii Ebooki prowadzić mogą wyłącznie oficjalni dystrybutorzy, po spełnieniu odpowiednich wymagań technicznych i podpisaniu osobnej umowy z Allegro. Gdy już taką umowę podpiszesz, wówczas otrzymasz wszelkie niezbędne informacje.
