### ISSUE TITLE
Blokada: 429

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3454]
Witam,
Czy, jeżeli mam blokadę too many requests 429, wykonywanie zapytań w trakcie blokady przedłuża blokadę czy nie?

**Comment by kfijalko** [comment]
Ile trwa blokada?

**Comment by MaciejFrackowiak** [comment]
Tak, takie działanie wydłuża czas trwania blokady (jej czas uzależniony jest od intensywności requestów użytkownika).

**Comment by kfijalko** [comment]
Czy jest jakiś bezpieczny (bez przedłużania blokady) sposób na sprawdzenie czy blokada jest już zdjęta?

**Comment by kfijalko** [comment]
Mam problem z integracją.
Dziś od 7 rano mam cały czas blokadę.
Teraz wyłączyłem całkowicie komunikację na 30 minut i blokada nie została zdjęta.
Czy może Pan @MaciejFrackowiak sprawdzić co się wydarzyło na moim clienId ?
Oraz odpowiedzieć na wcześniejsze pytanie?

**Comment by deneb-k** [comment]
Ciekawe, od wczoraj walczę z tym samym u siebie, ale do tej pory zakładałem, że to wina mojego kodu i kombinowałem nad optymalizacjami.

Sprawdzałeś przez proxy czy nie musisz captchy przeklikać?

**Comment by kfijalko** [comment]
@deneb-k  nie sprawdzałem. 
Możesz podać jakiś link do dokumentacji?

**Comment by kfijalko** [comment]
Poszukałem trochę i w webapi była captcha, i sam raz taką blokadę zdejmowałem. Tylko będę musiał zainstalować proxy na serwerze. Tylko czy muszę się w to bawić @MaciejFrackowiak ?

**Comment by kfijalko** [comment]
Teraz odczekałem 1,5 h i wygląda na to, że blokada została zdjęta tylko "straciłem" refresh-tokeny. Muszę powiązać konta i aplikacje jeszcze raz.

**Comment by MaciejFrackowiak** [comment]
@kfijalko Poprosiłem o weryfikację sytuacji, którą opisałeś, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@kfijalko Otrzymałeś Captchę, ponieważ Twoje działania mocno wykraczały poza standardowe działanie użytkownika m.in. ciągłe odpytywanie listingów oraz ofert. Aby zapobiec podobnym sytuacjom w przyszłości musisz ograniczyć wykonywanie podobnych requestów.

**Comment by kfijalko** [comment]
@MaciejFrackowiak w logach widzę: wystąpił błąd przy pobraniu tokena => nastąpiło spiętrzenie wywołań => nastąpiła blokada => kolejki zwariowały, bo mają wykonywać każde zadanie do 10 razy (chyba, że nastąpi sukces) =>ogólnie kocioł.
Chciałbym się przed takim czymś zabezpieczyć, ale potrzebuję odpowiedź na pytanie: w jaki sposób sprawdzić czy blokada została zdjęta (bez przedłużania blokady)?
Dodatkowo, czy macie jakiś "wzorzec" w jaki sposób zapewnić spójność systemu zewnętrznego z systemem allegro. Na chwile obecną allegro traktuję jako "źródło prawdy" i dość często odpytuję o listing i szczegóły ofert. Co przy ponad 100k ofert może być obciążające.

**Comment by MaciejFrackowiak** [comment]
@kfijalko Jak wspomniałem wcześniej - tylko zaprzestanie wywołań spowoduje "zatrzymanie" mechanizmu przedłużania blokady z 429. Jeżeli Twoje działania nie wykraczają poza limit 9000 req/min w API, a podczas odpytywania WWW nie jest to automatyczne wysyłanie requestu za requestem w sposób lawinowy to mechanizm nie uruchomi zabezpieczenia.

**Comment by gsti** [comment]
@MaciejFrackowiak Rozumiem limit wszędzie jest napisane 9000req/min wykonuję ok 100 zapytań na minutę. Takie działanie powtarza się przez kilka minut. Odpalony jest Cron więc cyklicznie. Nie przekraczamy w takim razie żadnych limitów a kilka razy już był problem z 401 i teraz 429.

**Comment by MaciejFrackowiak** [comment]
@gsti Zgadza się, standardowy limit wynosi 9000 req/min dla danego ClientID. Jest to jednak limit obowiązujący dla zgodnego z wytycznymi ruchu. Jeżeli działania użytkownika zaczynają odbiegać od norm (np. notoryczne, masowe odpytywanie listingu) to zostaje uruchomiony mechanizm zabezpieczający z wydłużeniem czasu odpowiedzi - 429.
Finalnie, aby zapobiec takim działaniom pojawia się Captcha, która wymaga ingerencji użytkownika.

**Comment by gsti** [comment]
@MaciejFrackowiak Dziękuję za odpowiedź proszę jeszcze o odpowiedź na zgłoszenie przez formularz kontaktowy.

**Comment by MaciejFrackowiak** [comment]
@gsti Odpowiedź już przekazałem, niebawem zapewne otrzymasz email.

**Comment by gsti** [comment]
@MaciejFrackowiak Dziękuję za czujność i wyczerpujące informacje. Liczę że w email też takie będą 👍

**Comment by tomasz-grzesik** [comment]
@MaciejFrackowiak, podczas autoryzacji Użytkownika i odświeżania tokenów otrzymuję komunikat "429 - Too Many Requests". Rozumiem, że w jakiś sposób załapałem się na limit. Co powinienem teraz zrobić, aby blokada została zdjęta? Czy sporadyczne żądania uzyskania tokena Użytkownika  przedłużają czas blokady, czy jednak musi to być zwiększona liczba requestów w czasie? Ile dokładnie do odświeżenia tokena na minutę / godzinę ?

**Comment by MaciejFrackowiak** [comment]
@tomasz-grzesik Proszę podaj mi IP, z którego wywołujesz autoryzację. Jeżeli nie chcesz publicznie go zamieszczać na forum, prześlij do nas zgłoszenie za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by tomasz-grzesik** [comment]
Odblokowałem poprzez captche na stronie dostępnej z ip serwera.
Czy po podaniu IP jest szansa na jakieś szczegóły? Czy samodzielnie muszę sprawdzić po logach w czym wystąpił problem?

**Comment by MaciejFrackowiak** [comment]
Konkretny IP pozwoli potwierdzić hipotezę - mianowicie, uderzasz na jakiś zasób, gdzie zostaje przekroczony limit. Uruchamia się mechanizm zabezpieczający w postaci Captchy, jest ona ignorowana, aplikacja dalej próbuje uzyskać autoryzację. To powoduje nawarstwienie kolejnych błędów, jeżeli oprogramowanie nie potrafi obsłużyć Captchy i pojawiających się błędów 400.

**Comment by tomasz-grzesik** [comment]
188.165.207.229

**Comment by tomasz-grzesik** [comment]
Błędy 400 mogą oznaczać również inny problem (nie koniecznie blokadę), przy  zasobie można rozróżnić po błędzie “error”:“slow_down”. A w przypadku innych metod? Nie odnotowałem kodów 400 w odniesieniu do autoryzacji / odświeżenia tokenów.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem dane dla podanego przez Ciebie IP - rzeczywiście, Twoje zapytania związane z odpytywaniem zasobu /sale/products wywołały pojawienie się blokady.

**Comment by tomasz-grzesik** [comment]
Dziękuję za informację. Opracuję monitor requestów, tak aby sytuacja się nie powtórzyła.

**Comment by tomylee0** [comment]
> Odblokowałem poprzez captche na stronie dostępnej z ip serwera.

W jaki sposób przez captche można odblokować 429 - too many requests? Rozumiem, że należy wysłać żądanie z zablokowanego IP. Ale pod jaki URL?

Pozdrawiam
