### ISSUE TITLE
Kategoria motoryzacja- produktyzacja

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#3455]
Moje pytanie dotyczy produktyzacji w kategoriach związanych z  motoryzacją. 
W TecDoc'u kody kreskowe lub kody towarów często się powielają. Proszę mi powiedzieć jaką mam pewność, że wystawiając towar X z kodem kreskowym A podepnie mi się rzeczywiście towar X a nie towar Y, który posiada ten sam EAN. 
Przy kodach towarów trzeba posługiwać się także kodem producenta by mieć pewność, że wskazujemy poprawny towar.

Czy do produktyzacji w motoryzacji będziemy musieli podawać więcej parametrów, które jasno wskażą konkretny towar np EAN, kod towaru producenta + kod producenta?

**Comment by MaciejFrackowiak** [comment]
Wystarczy, że skorzystasz z GET /sale/products?ean={ean} i otrzymasz listę wszystkich produktów, które mamy w bazie z danym EANem. W następnym kroku wybierasz ten wybrany produkt i przekazujesz jego product.id.

**Comment by mlonc** [comment]
product.id wygląda tak "634238b1-4385-4de7-9c00-dfa49fce16ab", podejrzewam, że jest to zakodowany **kod towaru producenta + kod producenta w tecdoc** i nie ma możliwości wysyłania tych danych w bardziej przystępny sposób?  Pytam, ponieważ posiadamy bazę TD i mamy bezpośredni dostęp do danych w niej zawartych i chciałbym  ograniczyć do minimum możliwość włąsnie ręcznego wyboru towaru do podpięcia.

**Comment by MaciejFrackowiak** [comment]
To jest identyfikator produktu w naszej bazie produktów - ten konkretny podany przez Ciebie (634238b1-4385-4de7-9c00-dfa49fce16ab) odpowiada "Harry Potter i Książę Półkrwi J.K. Rowling", co sam sprawdzisz wywołując GET /sale/products/634238b1-4385-4de7-9c00-dfa49fce16ab. Nie ma alternatywnej "drogi" na przypisanie produktu.

**Comment by mlonc** [comment]
Ten konkretny to wiem, że jest nie motoryzacyjny :) wziąłem go z przykładu z jednego z artykułów dotyczących produktyzacji.

**Comment by mlonc** [comment]
Kolejne pytanie dotyczące parametryzacji czy planujecie automatycznie uzupełniać te parametry, które są obowiązkowe i są w bazie TD np strona zabudowy w klockach hamulcowych?

**Comment by MaciejFrackowiak** [comment]
Nie, nie planujemy rozbudowy parametrów. Jeżeli dany produkt posiada już określone parametry, to my oferty wzbogacimy o nie.
