### ISSUE TITLE
Jak można w opisie dodać htmlowe <br />. Jest jakieś obejście ?

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3456]
Jak można w opisie dodać htmlowe <br /> ? Jest jakieś obejście ?

**Comment by MaciejFrackowiak** [comment]
My go nie wspieramy - listę dozwolonych znaczników znajdziesz w [poradniku](https://developer.allegro.pl/sale/#5-opis-oferty).

**Comment by pietrach** [comment]
A takie coś jest możliwe `<p></p>` lub `<p>&nbsp;</p>`

**Comment by MaciejFrackowiak** [comment]
Tak, takie zapisy przechodzą przez walidator.
