### ISSUE TITLE
Przykład nie działa

### ISSUE THREAD

**Issue by thefoe76** [allegro/allegro-api#3457]
Ktoś ma pomysł czemu ten generyczny kod mi nie działa? zwraca "Something went wrong". Choć kiedy wejdę na url z przeglądarki i wpisze clientID/clientSecret to pokazuje mi JSONa wszytko OK. Testowane lokalnie na 7.0 i na zdalnym 7.2, z włączonym wyświetlaniem błedów, ale nic nie wyświetla. 

`<?php

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";
    $clientId = "...";
    $clientSecret = "...";

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

function main()
{
    echo "access_token = ", getAccessToken();
}

main();`

**Comment by MaciejFrackowiak** [comment]
Ze względu na dużą liczbę języków programowania, nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.
Spójrz również na podobne tematy, które pojawiły się na [forum w przeszłości](https://github.com/allegro/allegro-api/issues?q=Something+went+wrong).

**Comment by thefoe76** [comment]
ale to jest Wasz przykład, z Waszej strony
https://developer.allegro.pl/getting_started/
chyba, ze jest nieaktualny i coś się zmieniło?

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę do postu #1539 na zaproponowane tam rozwiązanie.

**Comment by thefoe76** [comment]
tak, teraz działa, wystarczyło usunąć jedną linijkę. Dziękuję, ale nie prościej byłoby wyedytować błędnie podany przykład na Waszej stronie, wprowadza w błąd bo kązdy zakłada ze MUSI działać. A tak nie jest.

**Comment by MaciejFrackowiak** [comment]
Przyjrzymy się temu raz jeszcze i zweryfikujemy poprawność kodu z przykładu.

**Comment by thefoe76** [comment]
Chciałem pobrać dane oferty po id i wyskakuje mi coś takiego:
`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}`

Macie problemy, czy ja coś w kodzie mam, pytam bo nie chce znów tracić godzin na szukaniu problemu, którego u mnie nie ma?

**Comment by thefoe76** [comment]
Ok, problem znaleziony, błędnie token pobierałem, moglibyście popracować nad treścią błędów, bo raczej, w tym przypadku, na nic nie naprowadzają.

**Comment by MaciejFrackowiak** [comment]
Proszę opisz krok po kroku jakie czynności wykonałeś, gdy otrzymałeś wspomniany komunikat błędu.
