### ISSUE TITLE
AllegroPay - restAPI

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3459]
Dzień dobry
Jak w temacie, kiedy więcej informacji w temacie jak wyżej?  31 lipca ma testowo zostać wdrożone.

**Comment by MaciejFrackowiak** [comment]
O uruchomieniu usługi w trybie produkcyjnym poinformujemy w osobnym komunikacie. Jeżeli będzie miała ona wpływ na API również stosowna informacja pojawi się na portalu oraz na GitHubie.

**Comment by SebastianOzdoba** [comment]
Będzie miała wpływ bo pewnie bedzie nowy GUID typu płatności. Ta informacja przydałaby się nam wcześniej :)

**Comment by MaciejFrackowiak** [comment]
Jeżeli pojawi się jakakolwiek istotna zmiana to na pewno zamieścimy informację o niej.
