### ISSUE TITLE
wznawianie i kończenie ofert przy użyciu /sale/offer-publication-commands/ [NIE DZIAŁA]

### ISSUE THREAD

**Issue by pythonga** [allegro/allegro-api#346]
W newsie z 13 czerwca czytam:
> Zakończoną ofertę - w statusie ENDED - możesz wznowić za pomocą akcji ACTIVATE komendą PUT /sale/offer-publication-commands/{commandId}.

W [dokumentacji](https://developer.allegro.pl/sale/#step-7-offer-publication-commands) w tutorialu czytam:
>WAŻNE! Przy pomocy tej metody możesz również: 
>- zakończyć wybrane oferty - wystarczy, że w polu action podasz wartość END
>- zaplanować wystawienie oferty w przyszłości - wystarczy, że w polu scheduleFor ustawisz datę planowanej publikacji oferty
>- znowić[sic!] zakończone oferty - w statusie ENDED. Przekaż dla takich ofert wartość ‘ACTIVATE’ w polu action. Udostępnimy je ponownie w serwisie.

Próbuję więc wznowić kilka aukcji na raz **(wszystkie zostały zakończone mniej niż 30 dni temu - nie są w archwium!).**

Przykładowy request body, PUT do zasobu `/sale/offer-publication-commands/{moje_wygenerowane_uuid}` z przypisanym przeze mnie unikalnym uuid:
```
{
        "publication": {
            "action": "ACTIVATE"
        },
        "offerCriteria": [
            {
                "offers": [{'id': 11111111}, {'id': 22222222}, {'id': 33333333}],
                "type": "CONTAINS_OFFERS"
            }
        ]
}
```

Sprawdzam wynik requesta, GET na zasobie `/sale/offer-publication-commands/{moje_wygenerowane_uuid}` i otrzymuję (przykładowo):
```
{'id': {moje_wygenerowane_uuid}, 'taskCount': {'total': 69, 'success': 65, 'failed': 4}}
```

Jestem happy, sprawdzam co się konkretnie udało a co nie, GET na zasobie `/sale/offer-publication-commands/{moje_wygenerowane_uuid}/tasks` i otrzymuję:
```
{
  'tasks': [
    {
      'offer': {
        'id': '11111111'
      },
      'message': '',
      'status': 'SUCCESS',
      'scheduledAt': '2018-06-27T14:29:25.001+02:00',
      'finishedAt': '2018-06-27T14:29:26.033+02:00',
      'field': 'publication'
    },
    {
      'offer': {
        'id': '22222222'
      },
      'message': '',
      'status': 'SUCCESS',
      'scheduledAt': '2018-06-27T14:29:25.002+02:00',
      'finishedAt': '2018-06-27T14:29:26.457+02:00',
      'field': 'publication'
    },
    {
      'offer': {
        'id': '33333333'
      },
      'message': 'OfferRepository error',
      'status': 'FAIL',
      'scheduledAt': '2018-06-27T14:29:25.019+02:00',
      'finishedAt': '2018-06-27T14:29:30.254+02:00',
      'field': 'publication'
    }
  ]
}
```

Myślę, fajnie, mam z bani, aukcje wystawione. (Kilka godzin później) Sprawdzam w panelu jak tam moje aukcje, a tu nie ma aukcji. Wpisuję moje numery aukcji (1111111, 222222) w wyszukiwarkę na stronie głównej, a tam aukcja nadal zakończona. Po co więc `task` ich wznowienia został oznaczony i zwrócony w wyniku jako `'SUCCESS'` skoro nie wznowił?

Tak samo mam z zakończeniem aukcji (dostaję pozytywny response, a aukcja dalej wisi).

**Comment by MaciejPotepa** [comment]
Dzięki za świetnie opisane zgłoszenie. Sprawdzamy co jest nie tak. Przepraszamy za kłopoty.

**Comment by pythonga** [comment]
Ok, jakiś czas temu znowu sprawdziłem aukcje, które zostały oznaczone jako `'SUCCESS'` ale nie były dostępne (nawet po kilkunastu godzinach) - **dzisiaj o dziwo są aktywne**. Chyba, że któreś przeoczyłem, bo nie sprawdziłem wszystkich, ale te co sprawdziłem, zaczęły działać. Dzisiaj znowu kończyłem i aktywowałem aukcje i na razie nie widzę problemów z złym statusem `'SUCCESS'` - pobieżnie sprawdzając większość jest już dostępna. Wnioskuję, że może przy większym obciążeniu serwerów, response nadaje "na zaś" status `'SUCCESS'`, ale dopiero później procesuje request (z drugiej strony macie opisane że od takich sytuacji jest status `'NEW'` - z tego co zrozumiałem z dokumentacji).

**JEDNAKOWOŻ**, nadal otrzymuję w stosunku do niektórych ofert ten enigmatyczny error `OfferRepository error`, dzisiejsze przypadki które z tego tytułu _zfailowały_:

```
{'failed': ['7317525101', '7390961289', '7234158760']}
```

**Comment by MaciejPotepa** [comment]
Dzięki za IDki ofert. Sprawdzamy co jest nie tak.

**Comment by lukasnet** [comment]
Potwierdzam, wznawianie nie działa też jako do zaplanowania ani bez planowania.

**Comment by MaciejPotepa** [comment]
Dalej pracujemy nad rozwiązaniem problemu. Przepraszamy za kłopoty i prosimy za cierpliwość.

**Comment by pythonga** [comment]
Nie poganiam, ale robi się to niebezpieczne kiedy aukcje które powinny zostać zakończone, nadal wiszą. Dajcie priorytet na naprawienie "OfferRepository error" podczas próby zakończenia aukcji, bo nie ma szans tego kontrolować, a negatywa to _letko_można wyłapać i ostrzeżenie.

**Comment by MaciejPotepa** [comment]
@pythonga Jesteśmy wdzięczny tak za każdy post, pokazujecie, że to istotna kwestia. 

 Z tego co widzę - rozwiązanie tego problemu niedługo pojawi się w serwisie produkcyjnym. Dam znać. 
Jeszcze trochę, dziękuję wszystkim za cierpliwość.

**Comment by MaciejPotepa** [comment]
@tomaszgrzyb1 dzięki za zwrócenie uwagi na ten problem. Na Allegro.pl problem został rozwiązany już jakiś czas temu, pozostało trochę do posprzątania na Sandboxie. Dam znać odpowiedniemu zespołowi. 
Miłego dnia.
