### ISSUE TITLE
ClientId does not match authenticated client

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#3460]
Jestem nowy w pracy z API, więc błąd najprawdopodobniej wynika z nieświadomośći.
Wysyłam prośbę o prywatny token za pomocą prostego kodu:

```
curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic MTkw...Q==' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=19..2'
```
Wszystko działa dobrze z sandboxem, ale teraz dla allegro.pl mam błąd "ClientId does not match authenticated client".
Client ID oraz Client Secret są pobrane z https://apps.developer.allegro.pl/.
Czy muszę coś jeszcze zrobić z kontem, aby go autoryzować?

**Comment by vartaller** [comment]
I jeszcze tutaj zapytam (czy lepiej jest stworzyć nowe pytanie?): wysyłam EAN do sandboxu, aby otrzymać produkt, ale otrzymuję puste pole i żadnych błędów, nawet w przypadku produktów, które zdecydowanie znajdują się na allegro. Więc myślę, że ta prośba nie jest dostępna dla sandboxu, czy to jest tak?
I wymaga autoryzacji użytkownika.

**Comment by MaciejFrackowiak** [comment]
Taka sytuacja ma miejsce, gdy przekazujesz wybrany ClientID, a w aplikacji masz zapisane inne dane autoryzacyjne (np. username i password z innego środowiska). Sprawdź proszę dokładnie te dane.

Natomiast odnośnie EAN i Sandbox - środowisko testowe w zakresie produktów jest niezależne od produkcji tzn. na Sandbox znajdziesz tylko niewielką ilość produktów - ich listę znajdziesz [tu](https://developer.allegro.pl/productization/#sandbox).
