### ISSUE TITLE
Błąd przy autoryzacji API

### ISSUE THREAD

**Issue by rwojtyczka-neurosys** [allegro/allegro-api#3462]
Dzień dobry,

Integruję allegro dla jednego z klientów i trafiłem na następujący problem: przy próbie autoryzacji api ze środowiska staging, dostaję stronę błędu ("nie możemy wyświetlić strony", ostatni taki bład z 7:35 miał kod 302ce8340a9f000a), podczas gdy ze środowiska lokalnego wszystko działa poprawnie. Co może być przyczyną?

pozdrawiam
rw

**Comment by MaciejFrackowiak** [comment]
Adres przekierowania, który masz podany w aplikacji nie jest zgodny (1:1) z tym, który podałeś przy rejestracji aplikacji na stronie Zarządzanie aplikacjami Allegro.
