### ISSUE TITLE
Wystawiana liczba nie może być większa niż 100 000

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3463]
Dlaczego otrzymuje błąd `"Wystawiana liczba nie może być większa niż 100 000"`. W parametrach przesyłam `stock.available = 99999`.

Trace id to `c884b8d831a161b8`

**Comment by MaciejFrackowiak** [comment]
Zauważony przez Ciebie problem przekazałem do właściwego działu.

**Comment by pietrach** [comment]
A czy to nie jest tak, że jak ktoś już kupił 2 szt. z jakiejś oferty to przy próbie ustawienia `stock.available = 99999` na tej ofercie to Wasz system próbuje ustawić `100001` ?

**Comment by MaciejFrackowiak** [comment]
Wydaje się, że taki flow właśnie ma miejsce w tym wypadku - jak wspomniałem, temat przekazałem do weryfikacji.

**Comment by SebastianOzdoba** [comment]
@pietrach tak jest, dodaje się. Co wysyłasz w PUT /sale/offer-quantity-change-commands/ ?
FIXED  czy GAIN?

**Comment by pietrach** [comment]
@SebastianOzdoba to skoro tak jest to przyczyna znaleziona. Myślałem, że to zostało poprawione w porównaniu ze starym WebAPI Allegro

**Comment by pietrach** [comment]
@SebastianOzdoba wysyłam  `PUT /sale/offers/{offerId}`

**Comment by SebastianOzdoba** [comment]
@pietrach 
https://github.com/allegro/allegro-api/issues/2120

**Comment by czlowiekpolar** [comment]
@MaciejFrackowiak - do przesyłanego `stock.available` dodajecie w tym wypadku liczbę zakupionych sztuk dostępną pod /sale/offers (`stock.sold`) czyli dane z ostatnich 30 dni?

**Comment by MaciejFrackowiak** [comment]
@czlowiekpolar Ogólna, łączna liczba przedmiotów dla danej oferty nie może przekroczyć 100000 sztuk. Jeżeli sprzedałeś dotychczas np. 30 przedmiotów, to maksymalna dostępna ilość może wynieść 99970.

**Comment by czlowiekpolar** [comment]
@MaciejFrackowiak w takim razie jak uzyskać informację o łącznej liczbie sprzedanych przedmiotów przez API?

**Comment by MaciejFrackowiak** [comment]
@czlowiekpolar Bezpośrednio takiej informacji nie uzyskasz. Możesz pobierać informacje o sprzedanych ilościach w ciągu ostatnich 30 dni i tak dodawać co kolejne 30 dni poszczególne ilości.
