### ISSUE TITLE
plik xml 

### ISSUE THREAD

**Issue by jdmuniversal** [allegro/allegro-api#3466]
mam taki problem
jak zmienić ustawienia w eksporcie faktur do xml
program księgowy wywala mi błąd że nie może dodac zamówienia z powodu nazwa nabywcy nie może byc pusta
NA 99 proc system allegro podczas eksporty ma odznaczony ten rekord - jak to naprawić, gdzie znaleźć 

Damian Czyżewski 
 poważaniem/ Best Regards

BIURO J.D.M. UNIVERSAL

54-611 Wrocław
ul. Stanisławska 47

tel:        510 500 224

e-mail:  biuro@jdmuniversal.pl

www:    www.jdmuniversal.pl

**Comment by MaciejFrackowiak** [comment]
To sprawa wykraczająca poza API - myślę, że najlepszym rozwiązaniem byłby kontakt z autorem oprogramowania, z którego usług korzystasz.

**Comment by Aryak2099** [comment]
Ja bym zrobił to tak że trezba napisac jakiś programik który będzie dodawał wartości wymagane przez program księgowy.

**Comment by jdmuniversal** [comment]
hmmmm korzystam z programu fakturaxl, skontaktowałem się z nimi i przesłałem im też plik xml do weryfikacji, z tego co mówią to gdzies w ustawienia allegro nie mamy odznaczonej opcji do eksportu wlaśnie tego rekoru - nazwa nabywcy i stąd ten problem, nie wiem gdzie to znaleźć , na czat allegro odesłali mnie tu

**Comment by Aryak2099** [comment]
Oni mają błąd wartość <invoice><name> jest to nazwa nabywcy do faktury ,jest często pusta i ich program nie zrobił na tę okolicznośc wyjątku. Nazwa do faktury VAT nabywcy zawarta jest w <invoice><companyName> .Pozdrawiam

**Comment by Aryak2099** [comment]
miało by  invoicer-name <- nazwa nabywy często psuta i invoicer-vompanyname <- nazwa firmy

**Comment by jdmuniversal** [comment]
:) ok a dla laika ? :)) co moge zrobic ?? aby to poprawić ? naprawic ? u mnie

**Comment by Aryak2099** [comment]
Wie Pan producent tego oprogramowania to Panu poprawi napewno to westia kilku minut . Mogłby Pan sam uzupełnić te dane ale po co ? Z tego co wiem to w allegro nie ma takiej opcji żeby ustawić co konkretnei exportować bo nie jest to potrzebne wszystkie dane są w ich pliku. Wcześniej  było okej ? Czy po prostu taki program Pan znalazł i używa .

**Comment by jdmuniversal** [comment]
taki program mi polecono, jest przyjemny w użytkowaniu nie było problemu z niczym - teraz dopiero poszła sprzedaż na allegro i sie ujawniła ta luka - poczekam na odp sprzedawcy programu dziękuje za pomoc

**Comment by Aryak2099** [comment]
A to jak Pan uzywa to nie ma co zmieniać , jakby Pan miał plik wynikowy XML ze swojego sklepu pojedyńczy to można by porównać i ewentualnie programowo zmienić. admin@e-api.pl
