### ISSUE TITLE
 An error has occurred

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#3468]
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/offers
                    [userMessage] => 
                )

        )

)

w jaki sposób zdebugować co powoduje error?? błąd generowany przy tworzeniu draftu

**Comment by MaciejFrackowiak** [comment]
Jest to błąd składni całego payloadu, bez przykładu nie sposób określić co jest nieprawidłowego.

**Comment by ButcherFromHell** [comment]
w jaki sposób mogę przesłać cały payload? @ ?

**Comment by MaciejFrackowiak** [comment]
Proszę prześlij request poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - dodaj proszę nr postu z GitHub do zgłoszenia.

**Comment by ButcherFromHell** [comment]
wysłane, proszę o wskazówkę

**Comment by MaciejFrackowiak** [comment]
Jak tylko wiadomość zostanie do nas przekazana, spojrzę na request i dam znać tu w poście.

**Comment by ButcherFromHell** [comment]
ok, czekam - dziękuje

**Comment by MaciejFrackowiak** [comment]
Czy przekazałeś nam w zgłoszeniu nr posta - dopytuję, bo dostaliśmy podobne zgłoszenie - czy Twoja oferta dot. kategorii 258462?

**Comment by MaciejFrackowiak** [comment]
Spojrzałem w Twój request i:

1) na początku payload przekazujesz tablicę z parametrami, a następnie obiekt z numerem oferty - wystarczy, że przekażesz obiekt oferty;

2) parametry przekazujesz w nieprawidłowy sposób, nie numerujemy ich 1, 2, etc. - przykładową struktuę znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty).

**Comment by ButcherFromHell** [comment]
Dziękuje,
tak - dot. kategorii 258462

1. tak robię - do Was w @ przesłałem po prostu 2 JSONY - jeden z parametrami i drugi z całym obiektem oferty / draftu

2. parametry to array of objects - zmieniłem ją na tablicę bez numerów indexów

w odp dostaję informację:
[code] => INVALID_JSON
                    [message] => Invalid request.
                    [details] => 
                    [path] => 
                    [userMessage] => Invalid request.


sam JSON zarówno z parametrami jak i całym obiektem oferty waliduje się poprawnie (przesłałem @)

**Comment by MaciejFrackowiak** [comment]
Jeżeli JSON waliduje się poprawnie, to udało Ci się stworzyć draft?

Poniżej zamieszczam strukturę, dla której zwracamy 200 - do uzupełnienia pozostaje sekcja delivery, afterSalesServices:

```
{
    "name": "Clarena Spider Silk Cream Krem pajeczy jedwab ",
    "category ": {
        "id ": "258462 "
    },
    "parameters ": [{
        "id ": "215870 ",
        "valuesIds ": [
            ["215870 _271998 "]
        ],
        "values ": [""]
    }, {
        "id ": "129434 ",
        "valuesIds ": [
            ["129434 _317713 ", "129434 _317717 "]
        ],
        "values ": [""]
    }, {
        "id ": "129469 ",
        "valuesIds ": [
            ["129469 _1 ", "129469 _7 ", "129469 _2 "]
        ],
        "values ": [""]
    }, {
        "id ": "215866 ",
        "valuesIds ": [
            ["215866 _271942"]
        ],
        "values ": [""]
    }, {
        "id ": "206338 ",
        "valuesIds ": [""],
        "values ": [
            ["50"]
        ]
    }],
    "stock ": {
        "available ": "100000",
        "unit ": "UNIT"
    },
    "sellingMode ": {
        "format ": "BUY_NOW",
        "price ": {
            "amount ": "59.00",
            "currency ": "PLN"
        }
    },
    "location ": {
        "city ": "Wrocławw ",
        "postCode ": "51-356 ",
        "countryCode ": "PL",
        "province ": "DOLNOSLASKIE"
    },
    "external ": {
        "id ": "22449 "
    },
    "payments ": {
        "invoice ": "NO_INVOICE"
    },
    "description ": {
        "sections ": [{
            "items ": [{
                "type ": "TEXT ",
                "content ": "TESTowy opis "
            }, {
                "type ": "IMAGE ",
                "url ": "https://a.allegroimg.allegrosandbox.pl/original/11546d/1c1dde4741648f9ef50d7de1c9aa"
            }]
        }, {
            "items": [{
                "type": "TEXT",
                "content": "Tekstowyopis przedmiotu4 "
            }]
        }]
    },
    "publication ": {
        "status ": "INACTIVE"
    },
    "images ": [{
        "url ": "https://a.allegroimg.allegrosandbox.pl/original/11546d/1c1dde4741648f9ef50d7de1c9aa"
    }]
}
```

**Comment by ButcherFromHell** [comment]
Cały czas ten sam błąd.

Mój request (uzupełniony o kilka parametrów)
{
   "name":"Clarena Spider Silk Cream Krem pajeczy jedwab",
   "category":{
      "id":"258462"
   },
   "parameters":[
      {
         "id":"215870",
         "valuesIds":[
            [
               "215870_271998"
   ]
      
],
         "values":[
            ""
         
]
      
},
      {
         "id":"129434",
         "valuesIds":[
            [
               "129434_317713",
               "129434_317717"
            
]
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"129469",
         "valuesIds":[
            [
               "129469_1",
               "129469_7",
               "129469_2"
            
]
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"215866",
         "valuesIds":[
            [
               "215866_271942"
            
]
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"206338",
         "valuesIds":[
            ""
         
],
         "values":[
            [
               "50"
            
]
         
]
      
},
      {
         "id":"11323",
         "valuesIds":[
            "11323_1"
         
],
         "values":null
      
},
      {
         "id":"129369",
         "valuesIds":[
            "129369_130"
         
],
         "values":null
      
},
      {
         "id":"224017",
         "valuesIds":null,
         "values":[
            "22449"
         
]
      
},
      {
         "id":"129770",
         "valuesIds":[
            "129770_128"
         
],
         "values":null
      
},
      {
         "id":"225693",
         "valuesIds":[

         
],
         "values":[
            "5902194810258"
         
]
      
}
   
],
   "stock":{
      "available":"100000",
      "unit":"UNIT"
   
},
   "sellingMode":{
      "format":"BUY_NOW",
      "price":{
         "amount":"59.00",
         "currency":"PLN"
      
}
   
},
   "location":{
      "city":"Wroc\u0142aw",
      "postCode":"51-356",
      "countryCode":"PL",
      "province":"DOLNOSLASKIE"
   
},
   "delivery":{
      "additionalInfo":"Informacja dodatkowa o wysy\u0142ce",
      "handlingTime":"PT240H",
      "shipmentDate":"2019-05-04T13:11:10+00:00",
      "shippingRates":{
         "id":"xxxxxxxxxxxxxxxxxxxxxxxxxxx"
      
}
   
},
   "external":{
      "id":"22449"
   
},
   "payments":{
      "invoice":"NO_INVOICE"
   
},
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"TESTowy opis"
               
},
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118fb2\/3ed50d5c4b2a8c3238c794179c70"
               
}
            
]
         
},
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"Tekstowy opis przedmiotu 4"
               
}
            
]
         
}
      
]
   
},
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      
},
      "returnPolicy":{
         "id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      
}
   
},
   "publication":{
      "status":"INACTIVE"
   
},
   "images":[
      {
         "url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118fb2\/3ed50d5c4b2a8c3238c794179c70"
      
}
   
]
}

**Comment by MaciejFrackowiak** [comment]
Spojrzeliśmy i widzimy:

- dla parametru 206338 przekazujesz nieprawidłową strukturę - podwójna tablica dla values
- dla parametrów 129434, 129467 podajesz wiele wartości, a to są parametry jednokrotnego wyboru
- opis oferty nie zawiera wymaganych znaczników.

Przykład prawidłowego kodu:

```
{
    "name": "Clarena Spider Silk Cream Krem pajeczy jedwab",
    "category": {
        "id": "258462"
    },
    "product": null,
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "224017",
            "valuesIds": [],
            "values": [
                "22449"
            ],
            "rangeValue": null
        },
        {
            "id": "129369",
            "valuesIds": [
                "129369_130"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "215870",
            "valuesIds": [
                "215870_271998"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129434",
            "valuesIds": [
                "129434_317713"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129469",
            "valuesIds": [
                "129469_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "215866",
            "valuesIds": [
                "215866_271942"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129770",
            "valuesIds": [
                "129770_128"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "129569",
            "valuesIds": [
                "129569_2"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "206338",
            "valuesIds": [],
            "values": [
                "50"
            ],
            "rangeValue": null
        },
        {
            "id": "225693",
            "valuesIds": [],
            "values": [
                "5902194810258"
            ],
            "rangeValue": null
        }
    ],
    "ean": "5902194810258",
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>TESTowy opis</p>"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.allegrosandbox.pl/original/118fb2/3ed50d5c4b2a8c3238c794179c70"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Tekstowy opis przedmiotu 4</p>"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "images": [
        {
            "url": "https://a.allegroimg.allegrosandbox.pl/original/118fb2/3ed50d5c4b2a8c3238c794179c70"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "59",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null,
        "netPrice": null
    },
    "tax": null,
    "stock": {
        "available": 100000,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": false
    },
    "delivery": {
        "shippingRates": {
            "id": "xxxx"
        },
        "handlingTime": "PT240H",
        "additionalInfo": "Informacja dodatkowa o wysyłce",
        "shipmentDate": "2019-05-04T13:11:10.000Z"
    },
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "xxxx"
        },
        "returnPolicy": {
            "id": "xxxx"
        },
        "warranty": null
    },
    "additionalServices": null,
    "sizeTable": null,
    "fundraisingCampaign": null,
    "promotion": {
        "emphasized": false,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "DOLNOSLASKIE",
        "city": "Wrocław",
        "postCode": "51-356"
    },
    "external": {
        "id": "22449"
    },
    "attachments": [],
    "contact": null
}
```

**Comment by ButcherFromHell** [comment]
Dziękuje,
1 - faktycznie, nie zauważyłem.

2 - czyli gdy dla parametru: 
[restrictions] => Array (
                            [multipleChoices] => 
                        )
oznacza że nie może być multiple? 

W przypadku parametrów: 
1) 
[id] => 129469
[name] => Działanie
2) 
[id] => 129434
[name] => Typ skóry

i kosmetyków to mocne ograniczenie gdy mogą mieć tylko jedną wartość.

3 - o jakie parametry chodzi? 
w przesłanym requescie jest: 
"description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>TESTowy opis</p>"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.allegrosandbox.pl/original/118fb2/3ed50d5c4b2a8c3238c794179c70"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Tekstowy opis przedmiotu 4</p>"
                    }
                ]
            }
        ]
    },

ja mam natomiast: 

"description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "TESTowy opis"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.allegrosandbox.pl/original/11b97c/3bbb349944b4acc0a07a20aeb67b"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "Tekstowy opis przedmiotu 4"
                    }
                ]
            }
        ]
    },

**Comment by MaciejFrackowiak** [comment]
Pobierając parametry dla kategorii 258462 otrzymujesz m.in.
```
{
            "id": "215870",
            "name": "Rodzaj",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "describesProduct": true
            },
            "dictionary": [
                {
                    "id": "215870_271962",
                    "value": "na dzień",
                    "dependsOnValueIds": []
                },
                {
                    "id": "215870_271966",
                    "value": "na noc",
                    "dependsOnValueIds": []
                },
                {
                    "id": "215870_271998",
                    "value": "dzień i noc",
                    "dependsOnValueIds": []
                },
                {
                    "id": "215870_384369",
                    "value": "brak informacji",
                    "dependsOnValueIds": []
                }
            ],
            "restrictions": {
                "multipleChoices": false
            }
        },
```

"multipleChoices": false - oznacza, że możesz podać tylko jedną wartość. Taki sam wymóg jest na WWW.

Zgodnie z wymogami dot. [opisu](https://developer.allegro.pl/sale/#5-opis-oferty), musisz opis "ubrać" w znaczniki.

**Comment by ButcherFromHell** [comment]
OK - dziękuje.
a : 
 [errors] => Array
        (
            [0] => Array
                (
                    [code] => BAD_REQUEST
                    [message] => Invalid custom value: provided string cannot be empty
                    [details] => 
                    [path] => 
                    [userMessage] => To pole nie może być puste
                )


o jaką wartość chodzi?

**Comment by MaciejFrackowiak** [comment]
Po takiej odpowiedzi nie mamy możliwości wskazać jednoznacznie jaka to wartość - w jakimś polu "values" nie podałeś żadnej wartości.

**Comment by ButcherFromHell** [comment]
Jedyne co widze to w parametrach np:
{
            "id": "129569",
            "valuesIds": [
                "129569_2"
            ],
            "values": [],
            "rangeValue": null
        },

jeśli są valuesIds to values [ ]



{
   "name":"Clarena Spider Silk Cream Krem pajeczy jedwab",
   "category":{
      "id":"258462"
   
},
   "parameters":[
      {
         "id":"215870",
         "valuesIds":[
            "215870_271998"
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"129434",
         "valuesIds":[
            "129434_317713"
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"129469",
         "valuesIds":[
            "129469_1"
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"215866",
         "valuesIds":[
            "215866_271942"
         
],
         "values":[
            ""
         
]
      
},
      {
         "id":"206338",
         "valuesIds":[
            ""
         
],
         "values":[
            "50"
         
]
      
},
      {
         "id":"11323",
         "valuesIds":[
            "11323_1"
         
],
         "values":null
      
},
      {
         "id":"129369",
         "valuesIds":[
            "129369_130"
         
],
         "values":null
      
},
      {
         "id":"224017",
         "valuesIds":null,
         "values":[
            "22449"
         
]
      
},
      {
         "id":"129770",
         "valuesIds":[
            "129770_128"
         
],
         "values":null
      
},
      {
         "id":"225693",
         "valuesIds":[

         
],
         "values":[
            "5902194810258"
         
]
      
}
   
],
   "stock":{
      "available":"100000",
      "unit":"UNIT"
   
},
   "sellingMode":{
      "format":"BUY_NOW",
      "price":{
         "amount":"59.00",
         "currency":"PLN"
      
}
   
},
   "location":{
      "city":"Wroc\u0142aw",
      "postCode":"51-356",
      "countryCode":"PL",
      "province":"DOLNOSLASKIE"
   
},
   "delivery":{
      "additionalInfo":"Informacja dodatkowa o wysy\u0142ce",
      "handlingTime":"PT240H",
      "shipmentDate":"2019-05-04T13:11:10+00:00",
      "shippingRates":{
         "id":"exxxx9"
      
}
   
},
   "external":{
      "id":"22222"
   
},
   "payments":{
      "invoice":"NO_INVOICE"
   
},
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"text"
               
},
               {
                  "type":"IMAGE",
                  "url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/112348\/f9fa462a420e84f1c97363eb46f5"
               
}
            
]
         
},
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"text"
               
}
            
]
         
}
      
]
   
},
   "ean":"5902194810258",
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"0xxx5"
      
},
      "returnPolicy":{
         "id":"2xxxxxc1"
      
}
   
},
   "publication":{
      "status":"INACTIVE"
   
},
   "images":[
      {
         "url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/112348\/f9fa462a420e84f1c97363eb46f5"
      
}
   
]
}

**Comment by MaciejFrackowiak** [comment]
W parametrach, w values przekazujesz "" co jest błędne, zostaw tylko [] jak w moim requeście: 

```
{
            "id": "215866",
            "valuesIds": [
                "215866_271942"
            ],
            "values": [],
            "rangeValue": null
        },
```

**Comment by ButcherFromHell** [comment]
teraz:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => INTERNAL_SERVER_ERROR
                    [message] => Internal server error.
                    [details] => 
                    [path] => 
                    [userMessage] => Internal server error. Please try again in a few minutes.
                )

        )

)

dl aparametrów:
[
   {
      "id":"215870",
      "valuesIds":[
         "215870_271998"
      
],
      "values":[
         null
      
]
   
},
   {
      "id":"129434",
      "valuesIds":[
         "129434_317713"
      
],
      "values":[
         null
      
]
   
},
   {
      "id":"129469",
      "valuesIds":[
         "129469_1"
      
],
      "values":[
         null
      
]
   
},
   {
      "id":"215866",
      "valuesIds":[
         "215866_271942"
      
],
      "values":[
         null
      
]
   
},
   {
      "id":"206338",
      "valuesIds":[
         null
      
],
      "values":[
         "50"
      
]
   
},
   {
      "id":"11323",
      "valuesIds":[
         "11323_1"
      
],
      "values":null
   
},
   {
      "id":"129369",
      "valuesIds":[
         "129369_130"
      
],
      "values":null
   
},
   {
      "id":"224017",
      "valuesIds":null,
      "values":[
         "22449"
      
]
   
},
   {
      "id":"129770",
      "valuesIds":[
         "129770_128"
      
],
      "values":null
   
},
   {
      "id":"225693",
      "valuesIds":null,
      "values":[
         "5902194810258"
      
]
   
}
]

**Comment by MaciejFrackowiak** [comment]
Teraz przekazujesz null, gdzie powinny zostać same []

```
"values": [],
```

Raz jeszcze proszę spójrz na mój [request](https://github.com/allegro/allegro-api/issues/3468#issuecomment-662889370) - zmień wartości na wybrane przez Ciebie i bez przeszkód mechanizm przyjmie go.

**Comment by ButcherFromHell** [comment]
[
   {
      "id":"215870",
      "valuesIds":[
         "215870_271998"
      
],
      "values":[ ]
   
},
   {
      "id":"129434",
      "valuesIds":[
         "129434_317713"
      
],
      "values":[ ]
   
},
   {
      "id":"129469",
      "valuesIds":[
         "129469_1"
      
],
      "values":[
         ""
      
]
   
},
   {
      "id":"215866",
      "valuesIds":[
         "215866_271942"
      
],
      "values":[
         ""
      
]
   
},
   {
      "id":"206338",
      "valuesIds":[
         ""
      
],
      "values":[
         "50"
      
]
   
},
   {
      "id":"11323",
      "valuesIds":[
         "11323_1"
      
],
      "values":null
   
},
   {
      "id":"129369",
      "valuesIds":[
         "129369_130"
      
],
      "values":null
   
},
   {
      "id":"224017",
      "valuesIds":null,
      "values":[
         "22449"
      
]
   
},
   {
      "id":"129770",
      "valuesIds":[
         "129770_128"
      
],
      "values":null
   
},
   {
      "id":"225693",
      "valuesIds":null,
      "values":[
         "5902194810258"
      
]
   
}
]

**Comment by ButcherFromHell** [comment]
OK, faktycznie - chyba opanowane - dziękuje.
Czy zmieniły się ostatnio wymagane parametry dla kategorii 258462?

**Comment by MaciejFrackowiak** [comment]
Parametry i ich obowiązkowość podlegają ciągłym zmianom - najlepiej będzie, gdy zawsze pobierzesz aktualną strukturę parametrów dla danej kategorii korzystając z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by ButcherFromHell** [comment]
Tak też robię. Dziękuje za pomoc.
