### ISSUE TITLE
API zwraca numer aukcji lecz aukcje nie zostały wystawione

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#347]
Witam,
Mam problem z aukcjami. Dostałem odpowiedź z allegro API, że wszystko jest ok oraz numer aukcji, po czym wszystkie aukcje po 14:10 nie pojawiły się do tej pory na allegro. Poniżej podaję przykładowe numery aukcji:
Id	Status	CreatedOn
7427176081	0	2018-06-27 16:10:00.687
7427161018	0	2018-06-27 16:05:14.140
7427160677	0	2018-06-27 16:05:00.910
7427155632	0	2018-06-27 16:00:27.313
7427155327	0	2018-06-27 16:00:14.053
7427155082	0	2018-06-27 16:00:00.793
7427129302	0	2018-06-27 15:55:00.603
7427124010	0	2018-06-27 15:50:40.707
7427123764	0	2018-06-27 15:50:26.637
7427123461	0	2018-06-27 15:50:14.180
7427123191	0	2018-06-27 15:50:00.687
7427117015	0	2018-06-27 15:45:00.623
7427101633	0	2018-06-27 15:40:18.700
7427101477	0	2018-06-27 15:40:10.017
7427101302	0	2018-06-27 15:40:00.460
7427095698	0	2018-06-27 15:35:15.047
7427095390	0	2018-06-27 15:35:00.570
7427079944	0	2018-06-27 15:30:37.573
7427079768	0	2018-06-27 15:30:24.867
7427079544	0	2018-06-27 15:30:16.663
7427079386	0	2018-06-27 15:30:08.683
7427079230	0	2018-06-27 15:30:00.497
7427074333	0	2018-06-27 15:25:32.613
7427074041	0	2018-06-27 15:25:17.780
7427073741	0	2018-06-27 15:25:00.403
7427068058	0	2018-06-27 15:20:12.410
7427067775	0	2018-06-27 15:20:00.473
7427041746	0	2018-06-27 15:15:00.597
7427035904	0	2018-06-27 15:10:08.600
7427035783	0	2018-06-27 15:10:00.293
7427030474	0	2018-06-27 15:05:25.970
7427030294	0	2018-06-27 15:05:15.620
7427030150	0	2018-06-27 15:05:09.477
7427030036	0	2018-06-27 15:05:00.343

Pozdrawiam

**Comment by MaciejPotepa** [comment]
Dzień dobry

Dzięki za zgłoszenie i przepraszamy za kłopoty. 
Czy możesz podać treść requestu i response, którego użyłeś do wystawienia ofert?
