### ISSUE TITLE
Sandbox error

### ISSUE THREAD

**Issue by IHaveIssuesWithAllegro** [allegro/allegro-api#3470]
Hello,
i tried to create product in sandbox environment and got strange error which doesnt seem right, data below.

1. I followed response errors step by step and i believe the request should be finally ok as required parameters are present, at least it shouldnt be 0/5 present as stated in error.

2. The result seems like a bug on your side as it contains information that usually shouldnt be shown to anyone else other than devs on your side.

Can you provide info on what is wrong with the request and/or fix the response?
Thanks.

request:

array(4) {
  ["name"]=>
  string(14) "Xerox B1022V_B"
  ["category"]=>
  array(1) {
    ["id"]=>
    string(6) "260346"
  }
  ["parameters"]=>
  array(2) {
    [0]=>
    array(2) {
      ["id"]=>
      string(5) "11323"
      ["valuesIds"]=>
      array(1) {
        [0]=>
        string(7) "11323_1"
      }
    }
    [1]=>
    array(2) {
      ["id"]=>
      string(6) "225693"
      ["values"]=>
      array(1) {
        [0]=>
        string(13) "0000202001393"
      }
    }
  }
  ["images"]=>
  array(1) {
    [0]=>
    array(1) {
      ["url"]=>
      string(83) "https://a.allegroimg.allegrosandbox.pl/original/11f113/3b53c3af46f9b17bf012647cc192"
    }
  }
}

response:

Request failed! HTTP code: 422, result: {"errors":[{"code":"ProductCreateFailedException","message":"Nie można stworzyć produktu bez podania wszystkich parametrów wymaganych (0 / 5)","details":"pl.allegro.product.index.ohs.product.merchant.exception.ProductCreateFailedException: Nie można stworzyć produktu bez podania wszystkich parametrów wymaganych (0 / 5)\n\tat pl.allegro.product.index.ohs.productservice.ProductServiceClient.createProductByAllegroMerchant(ProductServiceClient.java:83)\n\tat pl.allegro.product.index.ohs.product.merchant.service.MerchantProductService.createProductByMerchant(MerchantProductService.java:46)\n\tat pl.allegro.product.index.ohs.product.merchant.CreateProductEndpoint.addProduct(CreateProductEndpoint.java:60)\n\tat jdk.internal.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:665)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:750)\n\tat io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)\n\tat pl.allegro.product.index.ohs.config.AcceptLanguageFilter.doFilter(AcceptLanguageFilter.java:36)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.filter.webmvc.ServerFilterWebMvcAdapter.doFilterInternal(ServerFilterWebMvcAdapter.java:67)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.filter.webmvc.ServerFilterWebMvcAdapter.doFilterInternal(ServerFilterWebMvcAdapter.java:67)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.filter.webmvc.ServerFilterWebMvcAdapter.doFilterInternal(ServerFilterWebMvcAdapter.java:60)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.trace.spring.TraceServletFilter.doFilterInternal(TraceServletFilter.java:28)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat pl.allegro.tech.common.andamio.spring.webmvc.filter.ExcludeUriPrefixFilterDecorator.doFilter(ExcludeUriPrefixFilterDecorator.java:32)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.spring.webmvc.filter.RequestContextCleanerFilter.doFilterInternal(RequestContextCleanerFilter.java:22)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat pl.allegro.tech.common.andamio.filter.webmvc.ServerFilterWebMvcAdapter.doFilterInternal(ServerFilterWebMvcAdapter.java:60)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)\n\tat io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)\n\tat io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)\n\tat io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)\n\tat io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)\n\tat io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)\n\tat io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)\n\tat io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)\n\tat io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)\n\tat io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)\n\tat io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)\n\tat io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)\n\tat io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)\n\tat io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)\n\tat io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)\n\tat io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)\n\tat io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)\n\tat io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)\n\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)\n\tat io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.springframework.web.client.HttpClientErrorException$UnprocessableEntity: 422 Unprocessable Entity: [{\"errors\":[{\"code\":\"UnableToCreateProductWithoutAllRequiredParametersException\",\"message\":\"Unable to create product without all required parameters (0 / 5)\",\"details\":\"pl.allegro.product.index.pmd.product.validation.parameter.required.UnableToCreateProductWithoutAllRequiredParametersException: Unable to create product without all required parameters (0 / 5)\\n\\tat pl.allegro.product.index.pmd.product.validation.parameter.required.RequiredParameterValidation.validate(RequiredParameterValidation.java:13)\\n\\tat pl.allegro.product.index.pmd.product.validation.CompositeProductValidation.lambda$validate$0(CompositeProductValidation.java:18)\\n\\tat java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)\\n\\tat pl.allegro.product.index.pmd.product.validation.CompositeProductValidation.validate(CompositeProductValidation.java:18)\\n\\tat pl.allegro.product.index.pmd.product.create.strategy.ProductByAllegroMerchantCreateStrategy.preValidate(ProductByAllegroMerchantCreateStrategy.java:55)\\n\\tat pl.allegro.product.index.pmd.product.create.strategy.CreateStrategy.prepareContext(CreateStrategy.java:20)\\n\\tat pl.allegro.product.index.pmd.product.create.ProductCreator.create(ProductCreator.java:105)\\n\\tat pl.allegro.product.index.pmd.product.create.ProductCreator$$FastClassBySpringCGLIB$$6a2751ae.invoke()\\n\\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\\n\\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)\\n\\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\\n\\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)\\n\\tat pl.allegro.tech.common.andamio.metrics.spring.micrometer.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:31)\\n\\tat pl.allegro.tech.common.andamio.metrics.spring.micrometer.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:15)\\n\\tat pl.al... (17813 bytes)]\n\tat org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:141)\n\tat pl.allegro.product.index.ohs.config.CustomRestResponseErrorHandler.handleError(CustomRestResponseErrorHandler.java:46)\n\tat pl.allegro.product.index.ohs.config.CustomRestResponseErrorHandler.handleError(CustomRestResponseErrorHandler.java:33)\n\tat org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)\n\tat org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)\n\tat org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)\n\tat org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583)\n\tat pl.allegro.product.index.ohs.productservice.ProductServiceClient.lambda$createProductByAllegroMerchant$0(ProductServiceClient.java:73)\n\tat org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)\n\tat org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)\n\tat pl.allegro.product.index.ohs.productservice.ProductServiceClient.createProductByAllegroMerchant(ProductServiceClient.java:73)\n\t... 93 more\n","path":"/products","userMessage":"Błąd przetwarzania żądania. Nie można stworzyć produktu bez podania wszystkich parametrów wymaganych (0 / 5)"}]}

**Comment by Aryak2099** [comment]
First, for your category, download the list of parameters for the product and check if those with "true" requirements are in the transferred json file, or, create a draft and see then on the Allegro in the editor what parameters there are or not .This category 260346 have much more required parameters.

**Comment by MaciejFrackowiak** [comment]
1. You tried to propose a product without required parameters - you have to check them for your category as @Aryak2099 said;

2. Yes, our response shouldn`t display that kind of data - we will fix it.
