### ISSUE TITLE
Zniknęły niektóre wartości słownikowe dla pola "Marka". Nie da się uaktualnić ilości sztuk dla ofert które używały tych wartości

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#3471]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

trace-id: e7068eee1bcccf8

Kategoria Dziecko,Zabawki,Gry,Planszowe (123958), pole Marka (127812). Zniknęły tam niektóre wartości słownikowe np.: 

Egmont (127812_505701)
Rebel (127812_505713)
Portal Games (127812_505885)

Przez co nie można uaktualnić ilości sztuk dla ofert które miały ustawione te wartości:

{
   "errors":[
      {
         "code":"VALIDATION_ERROR",
         "message":"You can only assign dictionary parameter by valueId for 127812.",
         "details":"",
         "path":"",
         "userMessage":"You can only assign dictionary parameter by valueId for 127812."
      },
      {
         "code":"VALIDATION_ERROR",
         "message":"No values given for parameter Marka(127812).",
         "details":"",
         "path":"",
         "userMessage":"No values given for parameter Marka(127812)."
      }
   ]
}

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, podane przez Ciebie marki nie były dostępne - przed momentem zostały przywrócone.

**Comment by tomylee0** [comment]
Chciałbym uprzejmie poprosić o zwrócenie uwagi również na inne podkategorie Dziecko,Zabawki,Gry (np. Karciane, Logiczne, itd.). Oraz na zniknięcie pozostałych wartości słownikowych w polu "Marka" (np. "Galakta", "Kangur", itd.).

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Sprawę weryfikuję z działem odpowiedzialnym za parametry - wrócę do Ciebie, gdy uzyskam odpowiedź.

**Comment by tomylee0** [comment]
Podsyłam w załączniku listę brakujących marek w wybranych kategoriach w formacie csv. Kiedyś te marki można było ustawić a teraz nie. Jest tego niemało dlatego w drugim pliku podsyłam 31 marek które dla mnie są ważne. Jeśli mógłbym poprosić aby przynajmniej te wróciły do swoich kategorii to byłoby super. Pozdrawiam

[lista_brakujacych_marek.csv.txt](https://github.com/allegro/allegro-api/files/5129554/lista_brakujacych_marek.csv.txt)
[dla_mnie_wazne.txt](https://github.com/allegro/allegro-api/files/5129556/dla_mnie_wazne.txt)

**Comment by MaciejFrackowiak** [comment]
To zmiany wynikające z działań zespołu odpowiedzialnego za kategorie i parametry - zarówno w API, jak i w serwisie WWW. Tym samym nie jest to sprawa stricte dot. API, dlatego bardzo proszę, abyś swoje uwagi i wątpliwości zgłosił poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
