### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by radekkuliberda** [allegro/allegro-api#3472]
Proszę o aktywacje kont w sandbox: a4b_1 i a4b_2

**Comment by MaciejFrackowiak** [comment]
Oba konta są już aktywne. W celu weryfikacji kont jako konta Firma proszę prześlij dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/Settings/mysettings.php).
