### ISSUE TITLE
/sale/product-offers Parametr 129218 nie umożliwia podawania wartości spoza słownika 

### ISSUE THREAD

**Issue by grzesiektoton** [allegro/allegro-api#3473]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam problem z parametrem **Materiał** w kategorii **110915**
Jeżeli wysyłam go jak poniżej:
```
{'id': '129218', 'valuesIds': ['129218_7'], 'values': ['inny materiał'], 'rangeValue': None}
```
Otrzymuje błąd: 
```
{'errors': [{'code': 'ParameterIsNotCustomValueEnabledException', 'message': '129218', 'details': '', 'path': 'product./products', 'userMessage': 'Parametr 129218 nie umożliwia podawania wartości spoza słownika'}]}
```

trace-id: ccee6ddd711c697a

Jeżeli wysyłam:
```
{'id': '129218', 'valuesIds': ['129218_7']}
```
Otrzymuje błąd:

```
{'errors': [{'code': 'ProductCreateFailedException', 'message': 'Nieprawidłowe wartości parametrów: [parameter = 129218 [ Wartość niejednoznaczna - inny materiał]]', 'details': '', 'path': 'product./products', 'userMessage': 'Błąd przetwarzania żądania. Nieprawidłowe wartości parametrów: [parameter = 129218 [ Wartość niejednoznaczna - inny materiał]]'}]}
```

trace-id: d6b79a173ea9a420

Jak poprawnie dodać parameter **Materiał** z wartością "inna wartość" ?

**Comment by Aryak2099** [comment]
Wygląda to na próbę zmiany parametru w produkcie.

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości - nie możesz zaproponować produktu, który ma wartość parametru "inna wartość".
Tylko w wybranych kategoriach natomiast można dodać własną wartość, gdy wartość parametru jest niejednoznaczna - listę znajdziesz na stronie [dla sprzedających](https://allegro.pl/dla-sprzedajacych/na-api-mozesz-wprowadzic-wlasna-wartosc-parametru-marka-w-wybranych-kategoriach-z8EDxMZd0fa).
