### ISSUE TITLE
Problem z autoryzacją konta.

### ISSUE THREAD

**Issue by potockit** [allegro/allegro-api#3474]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Po otrzymaniu kodu http://exemplary.redirect.uri/?code=pOPEy9Tq94aEss540azzC7xL6nCJDWto
i wysłaniu requesta
curl -X POST -H 'Authorization: Basic YTI...Hg=' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'

dostajemy odpowiedź 400 bez żadnej treści?  

Czy jest to możliwe jeśli przez całą noc leciały requesty ze złym access key i access secret to czy mogliście zablokować adres IP?

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam szczegóły Twojego wywołania - skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), wówczas będziemy mogli spojrzeć dokładnie. Dodaj proszę numer postu z GitHub - 3474.

**Comment by MaciejFrackowiak** [comment]
Niestety, otrzymaliśmy od Ciebie wyłącznie adres IP, który nie pozwala na jednoznaczne sprawdzenie opisanych przez Ciebie problemów. Jak wspomniałem w poprzedniej wiadomości, niezbędne są nam szczegóły wywołania byśmy mogli je zweryfikować.
