### ISSUE TITLE
Unauthorized przy próbie użycia refresh_tokena

### ISSUE THREAD

**Issue by sc4rface97** [allegro/allegro-api#3477]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, mam problem przy próbie uzyskania nowego access_tokena przy użyciu refresh_tokena na środowisku testowym. Zaznaczę, że ten sam kod z powodzeniem działa na środowisku produkcyjnym. 

Otóż, używam refresh_token by uzyskać access_token odpytując ten zasób:

https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=refresh_token&refresh_token={token-z-bazy}&redirect_uri={adres-url-przekierowania-z-aplikacji}

Poniżej podrzucam fragment kodu PHP:

```
$c = curl_init("https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=refresh_token&refresh_token={token-z-bazy}&redirect_uri={adres-url-przekierowania-z-aplikacji}");
curl_setopt($c, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($c, CURLOPT_USERNAME, "id-klienta");
curl_setopt($c, CURLOPT_PASSWORD, "secret-klienta");
curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
```
W zamian otrzymuję response "{"error":"Unauthorized","error_description":"Unauthorized"}", gdzie wszystkie dane są poprawne.

Warto nadmienić, że pierwsza autoryzacja do uzyskania access_tokena działa poprawnie, problem występuje tylko przy użyciu refresh_tokena.

**Comment by MaciejFrackowiak** [comment]
Niestety, bez konkretnych logów nie mamy możliwości wskazać co jest nie tak - wg wzorca wszystko powinno funkcjonować poprawnie. Proszę sprawdź raz jeszcze wykorzystane przy wywołaniu dane (ClientID, Client_secret, etc.)

Jeżeli nadal będziesz miał problem, proszę prześlij nam swoje wywołanie wraz z odpowiedzią poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W treści dodaj numer postu z GitHub - 3477.
