### ISSUE TITLE
Wyszukiwanie ofert w REST API

### ISSUE THREAD

**Issue by kmrozewski** [allegro/allegro-api#348]
Dzień dobry,
W jaki sposób (jeśli istnieje) można wyszukiwać oferty po tytule przy użyciu REST API?

**Comment by KrzysztofLukanowski** [comment]
Dzień dobry, na tę chwilę nie ma takiej możliwości. Udostępnimy odpowiednie zasoby niebawem. Poinformujemy o tym na forum  oraz na stronie [REST API](https://developer.allegro.pl/).

**Comment by kmrozewski-kainos** [comment]
@KrzysztofLukanowski a czy można do tego użyć WebAPI do komunikacji przez SOAP? Jesli tak to czy korzystając z serwisu do wyszukiwania ofert trzeba wcześniej przechodzić przez proces autentykacji/autoryzacji? Czy wystarczy Client ID w requescie?

**Comment by KrzysztofLukanowski** [comment]
Możesz wykorzystać [doGetItemsList](https://allegro.pl/webapi/documentation.php/show/id,1342). Nie musisz przechodzić procesu logowania.
