### ISSUE TITLE
Aktualizacja cen i ilości po API

### ISSUE THREAD

**Issue by Przemek848** [allegro/allegro-api#3480]
Proszę o sprawdzenie, czy mam zablokowaną na moim koncie allegro aktualizację cen i ilości po API. Odkąd włączyliśmy promocję bestseller, ilości  i ceny dla wszystkich produktów przestały się aktualizować. Moja aplikacja działa, ale ilości i ceny się nie aktualizują. Moje konto: AmplaSklep.

**Comment by MaciejFrackowiak** [comment]
Na Twoim koncie nie ma żadnej blokady. Proszę podaj przykładowy numer oferty, w której próbowałeś dokonać zmian.
