### ISSUE TITLE
Maximum execution i Error 401 REST API 

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#3481]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Jest jakaś przerwa w pracy serwera REST API??

Błąd 
Mój ClientID: 6767862c138a403da8243205db9554c6
od 2020-07-25 04:43:01 próbując pobrać token przez cron dostaję "Maximum execution time of 60 seconds exceeded"
Jeśli zapytanie jest w przeglądarce cały czas mieli brak odpowiedzi.

Pobieram token w następujący sposób:

        $ch = curl_init(config('allegro.authUrl'));
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
        curl_setopt($ch, CURLOPT_USERNAME, config('allegro.clientId'));
        curl_setopt($ch, CURLOPT_PASSWORD, config('allegro.clientSecret'));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

        $tokenResult = curl_exec($ch);
        $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($tokenResult === false || $resultCode !== 200) {
            $this->resultCode = $resultCode;
        }

Próbowałem na innym serwerze i na przeglądarce dostaję komunikat:
Status: 401
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

P.S. Na innego użytkownika jest to samo.

**Comment by gsti** [comment]
ok godz. 9 serwer się obudził a 9:21 znów to samo.

**Comment by MaciejFrackowiak** [comment]
Z logów, które widzę autoryzujesz się w praktycznie w sposób ciągły korzystając z autoryzacji typu client_credentials. Autoryzacja ta umożliwia dostęp do zasobów, które są wyłącznie dostępne publicznie m.in. wyszukiwarka, drzewo kategorii i parametrów. Jeżeli chcesz uzyskać dostęp do danych przeznaczonych stricte dla użytkownika musisz skorzystać z autoryzacji code_flow lub device_flow.

**Comment by gsti** [comment]
Tak loguję się do zasobów publicznych bo o nie mi chodzi. Tutaj wszystko jest ok i o to połączenie chodzi. Aktualnie coś zaczęło działać na konsoli ale na stronie jak odpytuję się przez przeglądarkę dalej jest błąd:
"{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}"
401

**Comment by MaciejFrackowiak** [comment]
Komunikat jednoznacznie mówi, że próbujesz pobrać dane zasobu, dla którego wymagana jest autoryzacja bearer-token-for-user - [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).

**Comment by gsti** [comment]
właśnie że tak robię dokładnie jak w instrukcji: 

function getAccessToken(): String
{
    $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";

    $clientId = '6767862c138a403da8243205db9554c6';
    $clientSecret = '..................................';

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    var_dump($resultCode);
    var_dump($tokenResult);

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

function main()
{
    echo "access_token = ", getAccessToken();
}

main();

i się zastanawiam co jest nie tak? Wcześniej dostawałem odpowiedź poprawną.

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę na wątek #1539 i zaproponowane tam rozwiązanie.
