### ISSUE TITLE
problemy z token'em

### ISSUE THREAD

**Issue by blonders** [allegro/allegro-api#3482]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam 

od dziś (tj. 2020.07.25 od 09:30) mam problem z uzyskaniem token;a dla aplikacji która wcześniej działa jak należy. 
Teraz nie jestem w stanie się uwierzytelnić stosują nawet podstawowy przykład z api_allegro.php (https://developer.allegro.pl/getting_started/#jak-zarejestrowa%C4%87-now%C4%85-aplikacj%C4%99) cały czas podając własny (poprawny) ClientID i Client Secret otrzymuje informacje zwrotną "access_token = Something went wrong" czyli nie jest w stanie uzyskać autoryzacji. 
Dodam że sprawdzałem w/w sposób autoryzacji z innego serwera i z nowo zarejestrowaną aplikacje w Allegro REST API i też jest tak samo.
W związku z tym mam pytanie  czy coś się zmieniło w sposobie autoryzacji a przykłady zostały bez zmian czy jest jakaś ew. blokada na projekt zarejestrowany w Allegro REST API  ?

Pozdrawiam i liczę na pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za opóźnienie w odpowiedzi. Nic nie zmienialiśmy w sposobie autoryzacji. Jeśli problem nadal występuje, prześlij proszę przykładowy request i response w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), w zgłoszeniu dopisz GitHub #3482.
