### ISSUE TITLE
REST API - Do pełnej funkcjonalności strony potrzebujesz włączonej obsługi skryptów...

### ISSUE THREAD

**Issue by ArkadiuszGroch** [allegro/allegro-api#3483]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Wszystkie zapytania kierowane na serwer testowy kończy się taką samą odpowiedzią:
![image](https://user-images.githubusercontent.com/20543776/88485346-7805f100-cf75-11ea-9553-963e91fe4567.png)
Sprawdzałem na postman oraz curl i za każdym razem ten sam efekt.

**Comment by TimothyKoval** [comment]
Ślesz request pod zły URL. Prawidłowe URL-e dla środowiska testowego:

`https://allegro.pl.allegrosandbox.pl/auth/oauth/`

Dla produkcji:

`https://allegro.pl/auth/oauth/`

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak jak @TimothyKoval wspomniał - użyłeś nieprawidłowego adresu wywołania. Spójrz proszę na [tabelę](https://developer.allegro.pl/about/#Sandbox), w której opisaliśmy adresy URL dla produkcji i Sandbox.

**Comment by ArkadiuszGroch** [comment]
Działa poprawnie. Dziękuję za pomoc.
