### ISSUE TITLE
Błąd podczas rejestracji nowej aplikacji

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#3484]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, po zarejestrowaniu nowej aplikacji i próbie autoryzacji użytkownika "przekierowania go na allegro celem zalogowania się" Zamiast powrócić na redirect_uri otrzymuje komunikat o błędzie.
Nr Błędu: 370dd2b66fe4ffa6
Client Id: 3c0da3e70660447db98e95c0722083e3

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę dokładnie jaki adres przekierowania masz podany w aplikacji - musi być on 1:1 z adresem podanym podczas rejestracji aplikacji. Twój komunikat błędu świadczy, że adresy nie są zgodne.

**Comment by Troian1337** [comment]
@MaciejFrackowiak przekierowanie mam na h t t p ://localhost/ i jest ono prawidłowe.
