### ISSUE TITLE
Problem z zasobem GET /sale/offer-events Błąd parametru TYPE

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#3486]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, mam problem z zasobem GET /sale/offer-events, kiedy próbuje przekazać mu parametry:
[
 'type' => 'OFFER_PRICE_CHANGED',
 'limit' => 500
]
otrzymuje kod błędu InvalidQueryParameterException. 
Jeżeli podam samo 'limit' otrzymuje listę 500 zdarzeń. 

Według dokumentacji (ja tak to rozumiem) parametr 'type' podajemy jako pojedynczą zmienną, tak wynika też z przykładowego requesta dostępnego na stronie.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, żądanie GET /sale/offer-events?type=OFFER_PRICE_CHANGED&limit=500 zwraca prawidłowe wyniki. Czy możesz podać przykładowe trace-id Twojego wywołania?

**Comment by Troian1337** [comment]
trace-id: 639c9f6efd4a79e5
GET /sale/offer-events?type=OFFER_ENDED&limit=100

**Comment by PrzemyslawLukanowski** [comment]
Według naszych logów posługujesz się myślnikami zamiast podreślnikami dla wartości type, np. type=OFFER-ENDED&limit=100. Odpowiedź 200 zwróciliśmy, gdy w parametrach przekazałeś np. type%5B0%5D=OFFER-ENDED&limit=500. Parametr type nie jest w tym przypadku prawidłowo zdefiniowany, więc - z racji tego, że jest opcjonalny - został zignorowany, pod uwagę wzięliśmy tylko limit i zwróciliśmy prawidłowe wyniki.

**Comment by Troian1337** [comment]
Faktycznie! Nawet nie zwróciłem na to uwagi, dziękuje za pomoc :)
