### ISSUE TITLE
Problem z autoryzacją użytkownika - 403 forbidden

### ISSUE THREAD

**Issue by elfiorr** [allegro/allegro-api#3487]
Od wczoraj próbuję dokonać autoryzacji użytkownika. Z autoryzacją dla aplikacji nie miałem problemów. Mianowicie, zgodnie z dokumentacją strzelam endpointem https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=TUTAJ_KLIENT&redirect_uri=https://exemplary2.redirect.uri.com (POST).

W zwrotce otrzymuje 403:

`{
    "error": "Forbidden",
    "error_description": "Forbidden"
}`

Coś robię pewnie źle, ale już mi się kończą pomysły. Ktoś pomoże?
Dziękuję

**Comment by elfiorr** [comment]
Dodam, że strzelając endpointem https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=TUTAJ_KLIENT&redirect_uri=https://exemplary2.redirect.uri.com dostaję zwrotkę 200


`<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" data-front-main="9ffb2e32b254472a">

<head>
	<base href="/login/" />
	<title>Allegro Logowanie - Zaloguj się na swoje konto w Moje Allegro</title>
	<meta name="description"
		content="Wejdź na stronę logowania. Zaloguj się lub zarejestruj nowe konto, by korzystać z udogodnień oferowanych przez Moje Allegro" />
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
	<meta name="robots" content="index, nofollow" />
	<link rel="canonical" href="https://allegro.pl/login/form" />
	<link rel="stylesheet" href="https://assets.allegrostatic.pl/opbox-skins/1.18.2/styles/fonts.css" />
	<link href="//cdn.allegrostatic.com/login/dist/css/main-0bb4b9b3.css" rel="stylesheet" />
	<script src="//cdn.allegrostatic.com/login/dist/js/jquery.min-1d35678c.js" type="text/javascript"></script>
	<script src="//cdn.allegrostatic.com/login/dist/js/angular.min-8c9ac3aa.js" type="text/javascript"></script>
	<script src="//cdn.allegrostatic.com/login/dist/js/angular-ui-router.min-78c94563.js" type="text/javascript">
	</script>
	<script src="//cdn.allegrostatic.com/login/dist/js/ui-bootstrap-tpls.min-e7cb7da4.js" type="text/javascript">
	</script>
	<script src="//cdn.allegrostatic.com/login/dist/js/angular-gettext.min-7b3f9ac5.js" type="text/javascript"></script>
...`

Ale kodu do autoryzacji brak.

**Comment by PrzemyslawLukanowski** [comment]
Przekaż ten adres w url w przeglądarce, w odpowiedzi powinieneś dostać code na adres powrotu, który określiłeś dla redirect_uri.

**Comment by elfiorr** [comment]
W momencie wrzucenia w url adresu mam:
![image](https://user-images.githubusercontent.com/28575269/88655672-5e78bc80-d0cf-11ea-9933-f2363b4f048e.png)

**Comment by elfiorr** [comment]
Strzelam postmanem i zwrotka bez zmian.

**Comment by PrzemyslawLukanowski** [comment]
Kod zostanie zwrócony na adres, który określiłeś w ramach redirect_uri. Sprawdziłem to i jeśli w przeglądarce wkleję:

https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={clientId}&redirect_uri=https://exemplary2.redirect.uri.com

W odpowiedzi, w adresie url, otrzymuję prawidłowy kod:
https://exemplary2.redirect.uri.com/?code={code}

Jeżeli nadal nie otrzymujesz kodu, prześlij nam proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) z dopiskiem GitHub #3487.

**Comment by elfiorr** [comment]
Ok mam kod. dzięki
