### ISSUE TITLE
Pasuje do

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3488]
Chcę skorzystać z funkcji "Pasuje do" w kategorii "części samochodowe".

Czy możliwe jest podanie tekstu z którego zaczytaną zostaną modele samochodów a następnie zindeksowane w Państwa systemie jako konkretne pozycje? 

Chodzi mi o funkcjonalność podobną do "wklej listę modeli" podczas ręcznego wystawiania aukcji.

**Comment by PrzemyslawLukanowski** [comment]
W tej kategorii możesz uzupełnić sekcję 'Pasuje do' tylko [identyfikatorami produktów](https://developer.allegro.pl/compatibility_list/#id).

**Comment by marmited** [comment]
Tak też podejrzewałem. Dziękuję za odpowiedź.
