### ISSUE TITLE
Brak netPrice w sale/offers

### ISSUE THREAD

**Issue by g-radzio** [allegro/allegro-api#3489]
Występuje problem: 
 - [ X ] z zasobem REST API

:beetle: **Opis**
Według dokumentacji (https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)
zasób powinien w strukturze zwracać w sellingMode cenę netto, jednak wywołując go z filtrami 'limit' oraz 'offset' uzyskuję niekompletną zawartość SellingMode, przykładowo:

###
###

GET https://api.allegro.pl/sale/offers?limit=5&offset=0
"Accept: application/vnd.allegro.public.v1+json"
"Accept-Language: pl-PL"
"Content-type: application/vnd.allegro.public.v1+json"

###
###
sting(15) "HTTP/1.1 200 OK"
["expires"]=>
string(1) "0"
["cache-control"]=>
string(46) "no-cache, no-store, max-age=0, must-revalidate"
["x-xss-protection"]=>
string(13) "1; mode=block"
["server"]=>
string(5) "envoy"
["pragma"]=>
string(8) "no-cache"
["x-frame-options"]=>
string(4) "DENY"
["trace-id"]=>
string(16) "e2fac5c04bf38b49"
["date"]=>
string(29) "Tue, 28 Jul 2020 13:23:26 GMT"
["x-content-type-options"]=>
string(7) "nosniff"
["content-type"]=>
string(52) "application/vnd.allegro.public.v1+json;charset=UTF-8"
["content-length"]=>
string(4) "4488"
["x-envoy-upstream-service-time"]=>
string(2) "48"
...  
Http info
["url"]=>
string(51) "https://api.allegro.pl/sale/offers?limit=5&offset=0"
["content_type"]=>
string(52) "application/vnd.allegro.public.v1+json;charset=UTF-8"
["http_code"]=>
int(200)
["header_size"]=>
int(406)
["request_size"]=>
int(1385)
...

###
###

stdClass Object
(
    [offers] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 9523442503
                    [name] => KlÄtwa gruziĹskiego tortu
                    [category] => stdClass Object
                        (
                            [id] => 79168
                        )

                    [primaryImage] => stdClass Object
                        (
                            [url] => https://a.allegroimg.com/original/1135fa/a07af4e94f6b8808f78e41d12c51
                        )

                    [sellingMode] => stdClass Object
                        (
                            [format] => BUY_NOW
                            [price] => stdClass Object
                                (
                                    [amount] => 11.97
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => stdClass Object
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => stdClass Object
                        (
                            [watchersCount] => 0
                            [visitsCount] => 3
                        )

                    [stock] => stdClass Object
                        (
                            [available] => 8
                            [sold] => 0
                        )

                    [publication] => stdClass Object
                        (
                            [status] => ACTIVE
                            [startingAt] => 
                            [startedAt] => 2020-07-22T09:16:00Z
                            [endingAt] => 
                            [endedAt] => 
                        )

                    [afterSalesServices] => stdClass Object
                        (
                            [warranty] => stdClass Object
                                (
                                    [id] => 4fbb7cae-8c15-4d6c-8cb3-b3de07f3a499
                                )

                            [returnPolicy] => stdClass Object
                                (
                                    [id] => f369f2a1-6642-4f0c-a714-a380f1b41995
                                )

                            [impliedWarranty] => stdClass Object
                                (
                                    [id] => 8bab42df-2dfc-4fbf-bf5d-104d6dfe4e67
                                )

                        )

                    [additionalServices] => 
                    [external] => stdClass Object
                        (
                            [id] => klatwa
                        )

                    [delivery] => stdClass Object
                        (
                            [shippingRates] => stdClass Object
                                (
                                    [id] => bde089a0-6c51-49bc-83cc-458b5368e707
                                )

                        )

                )

            [1] => stdClass Object
                (
                    [id] => 9523387718
                    [name] => KlÄtwa gruziĹskiego tortu
                    [category] => stdClass Object
                        (
                            [id] => 79168
                        )

                    [primaryImage] => stdClass Object
                        (
                            [url] => https://a.allegroimg.com/original/11400b/0a0440024375ab0300fab4a692e6
                        )

                    [sellingMode] => stdClass Object
                        (
                            [format] => BUY_NOW
                            [price] => stdClass Object
                                (
                                    [amount] => 11.97
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => stdClass Object
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => stdClass Object
                        (
                            [watchersCount] => 0
                            [visitsCount] => 0
                        )

                    [stock] => stdClass Object
                        (
                            [available] => 8
                            [sold] => 0
                        )

                    [publication] => stdClass Object
                        (
                            [status] => ENDED
                            [startingAt] => 2020-07-22T08:57:00Z
                            [startedAt] => 
                            [endingAt] => 
                            [endedAt] => 2020-07-22T07:11:49Z
                        )

                    [afterSalesServices] => stdClass Object
                        (
                            [warranty] => stdClass Object
                                (
                                    [id] => 4fbb7cae-8c15-4d6c-8cb3-b3de07f3a499
                                )

                            [returnPolicy] => stdClass Object
                                (
                                    [id] => f369f2a1-6642-4f0c-a714-a380f1b41995
                                )

                            [impliedWarranty] => stdClass Object
                                (
                                    [id] => 8bab42df-2dfc-4fbf-bf5d-104d6dfe4e67
                                )

                        )

                    [additionalServices] => 
                    [external] => stdClass Object
                        (
                            [id] => klatwa
                        )

                    [delivery] => stdClass Object
                        (
                            [shippingRates] => stdClass Object
                                (
                                    [id] => bde089a0-6c51-49bc-83cc-458b5368e707
                                )

                        )

                )

            [2] => stdClass Object
                (
                    [id] => 9523379384
                    [name] => KlÄtwa gruziĹskiego tortu
                    [category] => stdClass Object
                        (
                            [id] => 79168
                        )

                    [primaryImage] => stdClass Object
                        (
                            [url] => https://a.allegroimg.com/original/11efaf/516f558d4ef0896a69ab4844d1e6
                        )

                    [sellingMode] => stdClass Object
                        (
                            [format] => BUY_NOW
                            [price] => stdClass Object
                                (
                                    [amount] => 27.93
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => stdClass Object
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => stdClass Object
                        (
                            [watchersCount] => 0
                            [visitsCount] => 0
                        )

                    [stock] => stdClass Object
                        (
                            [available] => 8
                            [sold] => 0
                        )

                    [publication] => stdClass Object
                        (
                            [status] => ENDED
                            [startingAt] => 2020-07-22T08:51:00Z
                            [startedAt] => 
                            [endingAt] => 
                            [endedAt] => 2020-07-22T06:56:19Z
                        )

                    [afterSalesServices] => stdClass Object
                        (
                            [warranty] => stdClass Object
                                (
                                    [id] => 4fbb7cae-8c15-4d6c-8cb3-b3de07f3a499
                                )

                            [returnPolicy] => stdClass Object
                                (
                                    [id] => f369f2a1-6642-4f0c-a714-a380f1b41995
                                )

                            [impliedWarranty] => stdClass Object
                                (
                                    [id] => 8bab42df-2dfc-4fbf-bf5d-104d6dfe4e67
                                )

                        )

                    [additionalServices] => 
                    [external] => stdClass Object
                        (
                            [id] => klatwa
                        )

                    [delivery] => stdClass Object
                        (
                            [shippingRates] => stdClass Object
                                (
                                    [id] => 777e7552-87b5-4a9b-ad54-781a195c1903
                                )

                        )

                )

            [3] => stdClass Object
                (
                    [id] => 9523363916
                    [name] => KlÄtwa gruziĹskiego tortu
                    [category] => stdClass Object
                        (
                            [id] => 79168
                        )

                    [primaryImage] => stdClass Object
                        (
                            [url] => https://a.allegroimg.com/original/110a06/40a420db4a95984752c26ed6d882
                        )

                    [sellingMode] => stdClass Object
                        (
                            [format] => BUY_NOW
                            [price] => stdClass Object
                                (
                                    [amount] => 27.93
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => stdClass Object
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => stdClass Object
                        (
                            [watchersCount] => 0
                            [visitsCount] => 0
                        )

                    [stock] => stdClass Object
                        (
                            [available] => 8
                            [sold] => 0
                        )

                    [publication] => stdClass Object
                        (
                            [status] => ENDED
                            [startingAt] => 2020-07-22T08:46:00Z
                            [startedAt] => 
                            [endingAt] => 
                            [endedAt] => 2020-07-22T06:56:15Z
                        )

                    [afterSalesServices] => stdClass Object
                        (
                            [warranty] => stdClass Object
                                (
                                    [id] => 4fbb7cae-8c15-4d6c-8cb3-b3de07f3a499
                                )

                            [returnPolicy] => stdClass Object
                                (
                                    [id] => f369f2a1-6642-4f0c-a714-a380f1b41995
                                )

                            [impliedWarranty] => stdClass Object
                                (
                                    [id] => 8bab42df-2dfc-4fbf-bf5d-104d6dfe4e67
                                )

                        )

                    [additionalServices] => 
                    [external] => stdClass Object
                        (
                            [id] => klatwa
                        )

                    [delivery] => stdClass Object
                        (
                            [shippingRates] => stdClass Object
                                (
                                    [id] => 777e7552-87b5-4a9b-ad54-781a195c1903
                                )

                        )

                )

            [4] => stdClass Object
                (
                    [id] => 9523320384
                    [name] => KlÄtwa gruziĹskiego tortu
                    [category] => stdClass Object
                        (
                            [id] => 79168
                        )

                    [primaryImage] => stdClass Object
                        (
                            [url] => https://a.allegroimg.com/original/118aa5/2dc863534ccda6b6f89bfb4b882d
                        )

                    [sellingMode] => stdClass Object
                        (
                            [format] => BUY_NOW
                            [price] => stdClass Object
                                (
                                    [amount] => 27.93
                                    [currency] => PLN
                                )

                            [minimalPrice] => 
                            [startingPrice] => 
                        )

                    [saleInfo] => stdClass Object
                        (
                            [currentPrice] => 
                            [biddersCount] => 0
                        )

                    [stats] => stdClass Object
                        (
                            [watchersCount] => 0
                            [visitsCount] => 0
                        )

                    [stock] => stdClass Object
                        (
                            [available] => 8
                            [sold] => 0
                        )

                    [publication] => stdClass Object
                        (
                            [status] => ENDED
                            [startingAt] => 2020-07-22T08:21:00Z
                            [startedAt] => 
                            [endingAt] => 
                            [endedAt] => 2020-07-22T06:43:19Z
                        )

                    [afterSalesServices] => stdClass Object
                        (
                            [warranty] => stdClass Object
                                (
                                    [id] => 4fbb7cae-8c15-4d6c-8cb3-b3de07f3a499
                                )

                            [returnPolicy] => stdClass Object
                                (
                                    [id] => f369f2a1-6642-4f0c-a714-a380f1b41995
                                )

                            [impliedWarranty] => stdClass Object
                                (
                                    [id] => 8bab42df-2dfc-4fbf-bf5d-104d6dfe4e67
                                )

                        )

                    [additionalServices] => 
                    [external] => stdClass Object
                        (
                            [id] => klatwa
                        )

                    [delivery] => stdClass Object
                        (
                            [shippingRates] => stdClass Object
                                (
                                    [id] => 777e7552-87b5-4a9b-ad54-781a195c1903
                                )

                        )

                )

        )

    [count] => 5
    [totalCount] => 3993
)

Stawka VAT w ofercie jest ustawiona. Z czego może wynikać problem?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie, jest to błąd w dokumentacji. To pole zwracamy tylko dla GET /sale/offers/{id}, nie dla GET /sale/offers.

**Comment by g-radzio** [comment]
Dziękuję za wyjaśnienie. A czy jest szansa, że w przyszłości będziecie zwracać to pole także dla GET /sale/offers?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę tego nie planujemy. Jeżeli zdecydujemy się na taki krok, opublikujemy odpowiedni komunikat.
