### ISSUE TITLE
Metoda /pricing/fee-preview zwraca opłaty których zgodnie z regulaminem nie powinno być

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#349]
Endpoint `/pricing/fee-preview`, przesyłane dane:

```
{
	"offer": {
		"type": "SHOP",
		"category": {
			"id": "50855"
		},
		"duration": "PT720H",
		"unitPrice": "116.00",
		"quantity": "3",
		"soldQuantity": "1",
		"numberOfPhotos": "2",
		"bold": false,
		"highlight": false,
		"emphasized": false,
		"departmentPage": false,
		"emphasizedHighlightBoldPackage": false
	},
	"includeQuotingBundles": true
}
```

Dane zwracane:

```
{
	"quotes": [{
		"type": "listingFee",
		"name": "Opłata za wystawienie",
		"fee": {
			"amount": "0.30",
			"currency": "PLN"
		}
	}],
	"commissions": [{
		"type": "commissionFee",
		"name": "Prowizja od sprzedaży (sklep)",
		"fee": {
			"amount": "9.28",
			"currency": "PLN"
		}
	}]
}
```

Te 0,30 zł za wystawienie to jakaś nowość?

**Comment by KrzysztofLukanowski** [comment]
Otrzymałeś prawidłowe informacje. Pobieramy opłatę za wystawienie używanej miski olejowej. Piszemy o tym w [artykule](https://allegro.pl/pomoc/faq/cennik-ile-kosztuje-korzystanie-z-allegro-XEGmwoPy2UB), w części "Lista kategorii, w których opłata podstawowa jest uzależniona od ceny początkowej [1] towaru (dotyczy wszystkich ofert z wyjątkiem oznaczonych parametrem stan „Nowy”)".

**Comment by TimothyKoval** [comment]
A gdzie jest napisane że ta miska olejowa jest używana?

**Comment by TimothyKoval** [comment]
A od kiedy stan używany a nie nowy jest domyślny?

**Comment by KrzysztofLukanowski** [comment]
Nie jest domyślny. Po prostu jakikolwiek inny stan niż nowy, w tym brak stanu jest traktowany jako brak parametru "stan" - "nowy" w ofercie. Jeśli do parametru "stan" nie przypisałeś wartości "nowy" to naliczyliśmy opłatę.

**Comment by TimothyKoval** [comment]
Tak, to jest właśnie definicja domyślności.

Wczoraj ta metoda działa inaczej, dzisiaj - jak zwykle bez ostrzeżenia - nastąpiła zmiana.

**Comment by TimothyKoval** [comment]
Sorry, przedwczoraj

**Comment by KrzysztofLukanowski** [comment]
Zadbaliśmy o spójność pomiędzy formularzem, a API. Użytkownik wszędzie otrzymuje identyczną informację.
