### ISSUE TITLE
Alternatywa dla GET /sale/offer-events

### ISSUE THREAD

**Issue by Troian1337** [allegro/allegro-api#3490]
Witam, mam pytanie czy istnieje zasób który działa jak GET /sale/offer-events, ale pozwala zobaczyć zmiany które miały miejsce po 24h?

**Comment by PrzemyslawLukanowski** [comment]
GET /sale/offer-events to jedyny zasób, który jest dziennikiem zmian w ofertach.

**Comment by Troian1337** [comment]
Trochę głupie podejście że jedyna opcja sprawdzenia zmian jest do 24h co w przypadku kiedy uruchamiam program i potrzebuje znać starsze zmiany aby uwzględnić to w mies zestawieniu?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie ma innego rozwiązania. Jeżeli zdecydujemy się wydłużyć okres, dla jakiego zwracamy eventy w sale/offer-events, opublikujemy odpowiedni komunikat. Możesz wypracować po swojej stronie rozwiązanie, aby eventy zapisywać w swojej bazie raz na 24h.

**Comment by Onixarts** [comment]
Takie rozwiązanie nic nie da, bo nie każda aplikacja ma możliwość działania non stop. Po weekendzie aplikacje desktopowe nie są w stanie skorzystać z dziennika przez to ograniczenie, więc jego implementacja mija się z celem.
