### ISSUE TITLE
Problem z Generowaniem Tokenu użytkownika

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3491]
Generuje token użytkownika na sandboxie, niestety zwrotka jaką dostaje to:

{"error":"invalid_grant","error_description":"Redirect URI mismatch."} 

redirect URI który podaję w pierwszym linku do Allegro to: "http://localhost:51111/Allegro/GenerateToken"
redirect URI który podaję do zapytania autoryzacyjnego po otrzymaniu kodu to: "http://localhost:51111/Allegro/TokenSuccess"

Przy aplikacji dodałem też adresy URI do przekierowania:

"http://localhost:51111/Allegro/GenerateToken
http://localhost:51111/Allegro/TokenSuccess"

Czy możliwe jest żeby błąd był spowodowany inną sytuacją?

**Comment by AureliuszBrussy** [comment]
Podczas rejestracji aplikacji faktycznie możesz wskazać wiele adresów przekierowań, jednak w ramach uwierzytelniania oraz autoryzacji - adres przekierowania musi być jednakowy. Jeżeli generujesz kod, podając adres: http://localhost:51111/Allegro/GenerateToken, to podczas zgłoszenia się po token również musisz podać ten sam redirect_uri.

**Comment by fjjjq** [comment]
Dzięki! Do zamknięcia 👍
