### ISSUE TITLE
Brak możliwości publikacji oferty ze względu na wartość podatku

### ISSUE THREAD

**Issue by lkowol** [allegro/allegro-api#3493]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją

/sale/offer-publication-commands/7d3c9b85-e15a-44c9-bd2f-e39edcffb437/tasks zwraca
`{
    "tasks": [
        {
            "offer": {
                "id": "9544309076"
            },
            "message": "Could not change offer publication status. Tax may be filled only if you have company account.",
            "status": "FAIL",
            "scheduledAt": "2020-07-29T14:31:03.561Z",
            "finishedAt": "2020-07-29T14:31:04.167Z",
            "field": "publication",
            "errors": [
                {
                    "code": "ConstraintViolationException.TaxSpecifiedOnlyIfCompany",
                    "message": "Tax may be filled only if you have company account.",
                    "details": null,
                    "path": "tax",
                    "userMessage": "Tax may be filled only if you have company account."
                }
            ]
        }
    ]
}`

Konto jest kontem firmowym, wartość podatku jest podana w poprawnym formacie ["23.00" - wcześniej była niepoprawna (23.0), dostawałem ten sam błąd + jeden dodatkowy]

Proszę o weryfikację.

**Comment by lkowol** [comment]
Dodatkowo, w przypadku niepodania powyższego pola otrzymuję błąd:

```
{
    "tasks": [
        {
            "offer": {
                "id": "9544309076"
            },
            "message": "Could not change offer publication status. You cannot activate an invalid offer.",
            "status": "FAIL",
            "scheduledAt": "2020-07-29T14:39:05.717Z",
            "finishedAt": "2020-07-29T14:39:06.264Z",
            "field": "publication",
            "errors": [
                {
                    "code": "UnknownError",
                    "message": "You cannot activate an invalid offer.",
                    "details": null,
                    "path": null,
                    "userMessage": "You cannot activate an invalid offer."
                }
            ]
        }
    ]
}
```

Zapewne jest to związane z błędnymi danymi oferty, ale komunikat nie pozwala namierzyć błędu.

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto nie zostało zweryfikowane jako firmowe. [Dokończ pełną aktywację konta](https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/jak-zarejestrowac-konto-firmowe-WEDKYRDByHG), a problem powinien ustąpić.

**Comment by lkowol** [comment]
@PrzemyslawLukanowski Konto zostało zweryfikowane jako firmowe, wysłany i odesłany został przelew, a w panelu KONTO -> Ustawienia -> Dane konta jest informacja "Rodzaj konta: Konto firmowe"
Nie jest to firma zagraniczna, czy aktywowana za pomocą kodu papieru przesłanego pocztą, czy zarejestrowana na NIP 5242495143 lub 5213641211.

Co jest nie tak?

**Comment by PrzemyslawLukanowski** [comment]
Ponieważ zmieniasz konto zwykłe na firmowe (a nie rejestrujesz od razu konto firmowe), musisz jeszcze przesłać odpowiednie dokuemnty przez zakładkę [Dane konta](https://allegro.pl/myaccount/mysettings.php).

**Comment by lkowol** [comment]
Dziękuję. Myślę, że warto to dopisać tutaj: https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/jak-zarejestrowac-konto-firmowe-WEDKYRDByHG :)

**Comment by PrzemyslawLukanowski** [comment]
Cieszę się, że udało się rozwiązać problem. Ten przypadek opsialiśmy już tutaj https://allegro.pl/pomoc/dla-sprzedajacych/dane-i-ustawienia-konta/kiedy-i-jak-moge-zmienic-status-konta-rKxBgnr6ksx

**Comment by lkowol** [comment]
@PrzemyslawLukanowski prosiłbym jeszcze o weryfikację, co jest nie tak z wystawieniem oferty - commandId: 8564edf3-5f8a-4df9-95c4-658b26744a32

```
{
    "tasks": [
        {
            "offer": {
                "id": "9544359063"
            },
            "message": "Could not change offer publication status. You cannot activate an invalid offer.",
            "status": "FAIL",
            "scheduledAt": "2020-07-30T18:12:45.197Z",
            "finishedAt": "2020-07-30T18:12:45.483Z",
            "field": "publication",
            "errors": [
                {
                    "code": "UnknownError",
                    "message": "You cannot activate an invalid offer.",
                    "details": null,
                    "path": null,
                    "userMessage": "You cannot activate an invalid offer."
                }
            ]
        }
    ]
}
```

**Comment by PrzemyslawLukanowski** [comment]
Jeśli pobierzesz tę ofertę za pomocą GET /sale/offers/{id}, w sekcji validation znajdziesz error "ERR_WORD_IN_ITEM_NAME_TOO_LONG". Oznacza to, że któreś słowo w Twoim tytule przekroczyło 30 znaków - i rzeczywiście tak jest, wyraz "AMORTYZATORY,PILOT,LAKIER/SX-1728" zawiera 33 znaki.
