### ISSUE TITLE
Informacje na temat wspieranych parametrów w kategorii przez API

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3494]
Gdzie mogę znaleźć aktualną wersję tego co zwracane jest dla REST API po zapytaniu się o wspierane parametry?

Po odpytaniu _sale/categories/{allegroCategoryId}/parameters_ zwracane są takie dane dla obiektu restrictions:
     

>         bool multipleChoices
>         double? min
>         double? max
>         bool? range
>         int? precision
>         int? minLength
>         int? maxLength
>         int? allowedNumberOfValues

Pod następującym linkiem, widzę jedynie wzmiankę o polu **multipleChoices** w zakładce **Responses**: 
https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2

**Comment by AureliuszBrussy** [comment]
Pola dostępne w obiekcie "restrictions" zależne są od typu parametru ("type" w obiekcie "parameters"). W dokumentacji (https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) możesz przełączać się między przykładami różnych typów parametrów ("Example"), w ten sposób otrzymasz wszystkie aktualnie dostępne wartości.

**Comment by fjjjq** [comment]
Dzięki. Wydaje mi się jednak że powinniście stworzyć odpowiednią dokumentację z opisem pól do czego służą, bo to podejście nie jest intuicyjne :)

**Comment by AureliuszBrussy** [comment]
W [tym poradniku](https://developer.allegro.pl/sale/#parametry) (w sekcji "Parametry") w przykładowym response dodatkowo opisujemy pola.
