### ISSUE TITLE
Skąd Allegro zna numery przesyłek, jeżeli ich nie wysyłamy

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#3495]
Dzień dobry,

mamy kilka kont/użytkowników allegro, ale tylko na jednym użytkowniku działamy przez REST API. 

Dla zamówień ściągniętych przez komendę **/order/events** przy użyciu w/w konta, nadajemy później przez REST API numer przesyłki (**/order/checkout-forms/{checkout form id}/shipments**).

Jednakże ostatnio zauważyliśmy, że numery paczek nadają się samoczynnie także w przypadku zamówień z ofert wystawionych przez innych użytkowników, nieobsługiwanych przez REST API.

Pytanie: w jaki sposób się to dzieje, skory my tych numerów przesyłek do allegro nie wysyłamy - w przypadku dodatkowych kont zawsze były nadawane ręcznie w panelu allegro.

Wysyłanie dla dodatkowych kont numerów przesyłek, jest z naszej strony technicznie niemożliwe, ponieważ:

* wysyłka numeru przesyłki odbywa się przez to jedno konto
* warunkiem wysyłki jest ściągnięcie zamówienia (checkout form) z allegro przez **/order/events**, tymczasem żadne zamówienia z innych kont nie są ściągane (bo nie ma na nich włączonej obsługi REST), a jednak po stworzeniu przesyłki w systemie kuriera np. Fedex, numer pojawia się w Allegro

**Comment by tztztztz** [comment]
Dokonałem jeszcze przed momentem aktualizacji wpisu, proszę o przeczytanie końcówki.

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobnie chodzi o sytuację, kiedy przesyłka zostaje nadana przez narzędzie przewoźnika. Na podstawie przekazanego adresu email wiążemy ją z konkretnym zamówieniem. Możesz nam podać przykłądowe numery zamówień, zweryfikujemy to dokładnie.

**Comment by tztztztz** [comment]
Identyfikator transakcji, z pliku XML który jest pobierany z panelu allegro:

83928318

Mogę podać też adres email z domeny allegromail.pl który został wygenerowany dla zamówienia.

**Comment by tztztztz** [comment]
Jeżeli trzeba więcej przykładów proszę o info

**Comment by PrzemyslawLukanowski** [comment]
Będziemy potrzebować konkretny numer zamówienia w formacie uuid, np. - a1e3cd25-0daf-4d5b-ba27-d9225d44a207. Numer ten jest także widoczny na froncie - po wejściu w szczegóły danego zamówienia.

**Comment by tztztztz** [comment]
30aedd72-d1ba-11ea-8593-b338f687a440

**Comment by PrzemyslawLukanowski** [comment]
W przypadku tego zamówienia sprzedawca dodał numer przesyłki ręcznie przez naszą stronę internetową - Zamówienia -> Akcje -> Numery przesyłek.

**Comment by tztztztz** [comment]
Ok, dostałem więc zły przykład. 

Jednak mechanizm rozumiemy: Fedex rozpoznaje email w domenie allegromail.pl i wysyła do Państwa informację.

Proszę jeszcze nie zamykać, zgłoszenia być może jutro podam inny przykład, a jeżeli nie, to zamknę po prostu zgłoszenie, dziękuję za pomoc.
