### ISSUE TITLE
offers/listing - zwracanie 429 + dodatkowe pytania związane z wyszukiwaniem

### ISSUE THREAD

**Issue by gardenicus** [allegro/allegro-api#3496]
Od jakiegoś czasu podczas próby odnowienia klucza API zwraca błąd 429, co wymusza ingerencję człowieka do przeklikania Captchy (nawet kilkukrotnie!) na froncie Allegro (co się kompletnie mija z ideą oprogramowania), aby klucz mógł zostać odnowiony. Przypuszczam, że błąd ten jest zwracany po sporej liczbie zapytań (oprogramowanie wykonuje około 120 zapytań offers/listing na minutę). W związku z napotkanym problemem miałbym kilka pytań:

1. Wykonywane są dokładnie 4 zapytania na każdy produkt; fraza1 + parametr, fraza1, fraza2 + parametr, fraza2. Czy możliwe jest utworzenie zapytania, które połączy wszystkie w/w sposoby wyszukiwania, aby zwracany był pojedynczy json, a nie 4? Chodzi tu o wyszukiwanie ofert zawierających frazę1 lub frazę2 oraz zawierające informacje o określonym parametrze lub gdy parametr ten jest niewypełniony.

2. Domyślam się, że informacja o limicie zapytań offers/listing nie może zostać udostępniona, ale w takim razie do jakiego stopnia powinienem ograniczyć liczbę tych zapytań (wprowadzić sleepa między zapytaniami)? Czy tę konkretną liczbę powinienem sam 'odkryć' metodą prób i błędów?

**Comment by AureliuszBrussy** [comment]
1. W jednym zapytaniu możesz wyszukiwać tylko po jednej frazie. Gdy wskażesz w żądaniu konkretny parametr oznacza to, że w odpowiedzi otrzymasz oferty, które ten parametr posiadają. Gdy oferta nie spełni tego warunku - nie otrzymasz jej w odpowiedzi. Nie możesz połączyć zapytania w ten sposób, aby otrzymać tylko jeden response. 

2. Nie udzielamy informacji dot. tego limitu. Jest to zabezpieczenie przed działaniem, które nie przypomina standardowego działania użytkownika. Po pojawieniu się 429 sugerowałbym zaprzestania kolejnych requestów, ponieważ każdy kolejny wydłuża czas blokady.

**Comment by gardenicus** [comment]
Na jaki czas powinienem zaprzestać kolejnych requestów?

**Comment by AureliuszBrussy** [comment]
Przykro mi, jednak nie udzielamy informacji o czasie trwania blokady. Im więcej zapytań w trakcie blokady wysyłasz, tym czas jej trwania będzie dłuższy.
