### ISSUE TITLE
[REST API] Uzupełnienie draftu - metoda PUT

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#3497]
Cześć. integruję mój dedyowany sklep z REST API. Ogarnąłem kilka rzeczy i utknąłem na uzupełnieniu szablonu...

1. autoryzacja ogarnięta i połączenie z allegro
2. dodaję draft - dodaję tylko nazwę - zwraca mi ID 6962116756
3. pobieram dane z utworzonego ID 
4. uzupełniam dane o nazwę, kategorię

Otrzymuję błąd Response status code 400....

```
// $auction - obiekt pobrany przez GET sale/offers/6962116756

// uzupełniam nazwę i kategorię na próbę
$auction->name='Centralka AC STAG - 2G gaźnik';
$auction->category='18857';
$ret=$api->updateDraft($auction);

```
i funkcja która ma zmienić szablon wygląda tak:

```
public function updateDraft($data){
            $url =  $this->config['url']."sale/offers/".$data->id;

            $ch = curl_init($url);
            
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                         "Authorization: Bearer ".$this->token,
                         "Accept: application/vnd.allegro.public.v1+json",
                         "Content-Type: application/vnd.allegro.public.v1+json",
                        
            ]);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
            
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode ($data));
            curl_setopt($ch, CURLOPT_VERBOSE, true);
            $verbose = fopen('debug.txt', 'w+');
            curl_setopt($ch, CURLOPT_STDERR, $verbose);

            $uploadResult = curl_exec($ch);
            $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            
            if ($uploadResult === false || $resultCode !== 200) {
                echo "Response status code: $resultCode\n";
                
                exit;
            }

            $ret = json_decode($uploadResult);
            
            print_r($ret);
            
            return $ret;
        }
```

I to właśnie zwraca mi błąd 400... 

Czy ktoś spotkał się z takim problemem? To pewnie jakaś pierdoła znając życie....

Url to SANDBOX:
https://api.allegro.pl.allegrosandbox.pl/
A Mój login to: nagaz24

Dzięki!

**Comment by lasoczczyk** [comment]
Debug pokazuje to:
```

* Hostname was found in DNS cache
*   Trying 185.31.27.131...
* Connected to api.allegro.pl.allegrosandbox.pl (185.31.27.131) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=PL; ST=Wielkopolskie; L=Poznan; OU=IT; O=Allegro.pl sp. z o.o.; CN=allegrosandbox.pl
* 	 start date: 2020-01-22 09:16:44 GMT
* 	 expire date: 2021-04-22 14:18:30 GMT
* 	 subjectAltName: api.allegro.pl.allegrosandbox.pl matched
* 	 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
* 	 SSL certificate verify ok.
> PUT /sale/offers/6962116756 HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Transfer-Encoding: chunked
Authorization: Bearer eyJhbGciOiJSUzI1... **wyciąłem to :)** ...oBtKJ6Rd0kwi4f1eiwAwoRs8isex3MRmDYDfv1-iU
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Expect: 100-continue

< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< trace-id: 82303967e6172603
< date: Fri, 31 Jul 2020 04:55:03 GMT
< x-content-type-options: nosniff
< content-type: application/json
< transfer-encoding: chunked
< 
* Connection #0 to host api.allegro.pl.allegrosandbox.pl left intact

```

**Comment by lkowol** [comment]
Na pewno błąd w kategorii. Kontrakt przyjmuje ID ({"id": "jakieś ID kategorii"}), a nie bezpośrednio stringa.
Dodatkowo przydałby się response z lepszym contentem, zgadując Ci nikt rzeczowo nie pomoże.

**Comment by AureliuszBrussy** [comment]
Ze względu na dużą liczbę języków programowania, nie prowadzimy wsparcia dla każdego z nich. Prześlij proszę pełny request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) w formie cURL. W treści dodaj numer postu z GitHub - 3497.

Dodatkowo, Twoje konto w sandboxie nie było w pełni aktywne. Wstępnie je aktywowałem. Aby dokończyć aktywację, prześlij dwa dowolne pliki w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by lasoczczyk** [comment]
OK poprawiłem kategorię... troszkę ten system komunikatów mógły byc bardziej szczegółowy.

Aktywacja konto pomogła też i chyba nawet zaczęło działać... bałem się że coś z kodem....

Dziękuję!

**Comment by lasoczczyk** [comment]
Ok wszystko mi działa..... tylko jeszcze szybkie pytanko - dlaczego przy kolejnym zaktualizowaniu Draftu - parametry duplikują się i dodają jako kolejne?
Podobnie zdjęcia dodają się w nieskonczonosc?

Czy nie powinne byc zastępowane nowymi? Jak sobie z tym poradzic?

**Comment by lkowol** [comment]
Zapewne bo obiekt pobierasz przez GET i uzupełniasz (jak napisałeś) dodając nowe elementy, a nie aktualizując stare.
Zdumpuj sobie request i zobacz co wysyłasz.

**Comment by lasoczczyk** [comment]
@lkowol Dzieki.... taki szkolny błąd.... miałeś rację :)
No to jeszcze tylko zwroty i reklamacje i bede mogl publikować aukcje :)

**Comment by lkowol** [comment]
Optymista :D

**Comment by lasoczczyk** [comment]
Hahahahah.

No ale ogólnie masakra.... zdagywanie po omacku co nei gra... albo 400 albo 422 numer błędu...
i jak z babą... coś nie gra ale sie domyśl.....
