### ISSUE TITLE
Błąd autoryzacji użytkownika, Authorization Code

### ISSUE THREAD

**Issue by array3** [allegro/allegro-api#3498]
Ostatnio zauważyłem, że podczas autoryzacji otrzymuję błąd:
**Nie możemy wyświetlić strony
Numer błędu: 46a6b07280484e25**

Błąd tego typu ponoć wskazuje na różnice w adresie  przekierowań podanym w https://apps.developer.allegro.pl/, a tym wysłanym w requescie. Oba adresy są identyczne i nie mogę ustalić przyczyny, czym to jest spowodowane. Jeszcze nie tak dawno (kilka miesięcy temu) wszystko działało. Rzadko używamy autoryzacji, ponieważ większość tokenów odświeża się automatycznie i do teraz działają. Właściwie to przypadkowo wykryłem tą przypadłość.

Request wygląda mniej więcej tak:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=http://111.111.111.1:70/~f1/_fo2/fo3/fi.php

W czym może być problem?

**Comment by PrzemyslawLukanowski** [comment]
Najczęstszą przyczyną tego błędu jest to, o czym wspomniałeś - różnica między adresem przekierowania na stronie https://apps.developer.allegro.pl/, a tym w żądaniu. Aby zweryfikować dokładnie Twój przypadek, będziemy potrzebować client id, dlatego prześlij proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). W zgłoszeniu dopisz GitHub #3498.

**Comment by lasoczczyk** [comment]
Przemysław ma rację - u mnie też tak było - adres się musi zgadzać.

**Comment by array3** [comment]
Rozumiem, tylko adres naprawdę się zgadza ;-)
Ciekawe jest to, że dla testów wypróbowałem inny uri i on działa. Ciężko jest mi określić dlaczego tak jest, mam pewne przypuszczenia, ale poczekam na odpowiedź z wysłanego zgłoszenia.

**Comment by PrzemyslawLukanowski** [comment]
Dodatkowo możesz zapoznać się z [naszym newsem](https://github.com/allegro/allegro-api/issues/2737). Jeśli użyłeś adresu z powyższego przykładu, to należy on do adresów niedozwolonych.

**Comment by array3** [comment]
Adres jest podobny do tego, który podałem. Ścieżka dostępu zawierała folder użytkownika zaczynający się znakiem tyldy "~", który powodował wspomniany błąd. Na tą chwilę po przepisaniu adresu w .htaccess problem nie występuje.
Dziękuję za pomoc.
