### ISSUE TITLE
Autoryzacja WebAPI (Soap) nie działa

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3499]
Dzień dobry,
klucz autoryzacyjny (CLIENT_ID) do WebAPI (soap) nie działa.
Przy korzystaniu z endpointa: doLoginWithAccessTokenAsync , cały czas zwraca wartość:
Błędny identyfikator sesji. Proszę spróbować zalogować się jeszcze raz!
ERR_NO_SESSION

Sprawdzałem wszystko kilka razy, czy problem leży po waszej stronie? Proszę o wsparcie.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, dlatego jeśli problem nadal występuję, przeslij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). W zgłoszeniu dopisz, że problem dotyczy wątku GitHub #3499. Zweryfikujemy to.

**Comment by 4sp3ll** [comment]
Wysłałem 3 wiadomości, bo jak się okazuje, formularz obcina wiadomości które są zbyt długie (bez ostrzeżenia).
W trzeciej wiadomości jest załącznik, gdzie jest przykład requesta i response.

**Comment by PrzemyslawLukanowski** [comment]
Problem generuje to, że przekazujesz token otrzymany za pomocą autoryzacji typu client_credentials flow, który nie posiada kontekstu użytkownika. Użyj tokena, który otrzymasz przez typ autoryzacji [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).
