### ISSUE TITLE
after-sales-service-conditions - FORBIDDEN - You do not have permission to request this resource

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#35]
Moja aplikacja obsluguje ok 250 uzytkownikow. Bez problemu pobiera access tokeny, refresh tokeny i uslugi pozakupowe dla nich wszystkich. Niestety zdaza sie ze _czasami_ pomimo pobrania tokenow przy probie pobrania uslug zakupowych dostaje komunikat FORBIDDEN (patrz nizej). Zazwyczaj po kilku dniach problem sam znika i zaczyna wszystko banglac, ale przez te kilka dni musze uzerac sie z klientem tlumaczac, ze nie dziala nie z mojej winy. 

Nie do konca wiem, co mam Wam przekazac, zeby moc sprawe zdebuggowac, bo tokenow otwartym tekstem wrzucac nie bede :P Takze wrzucam co moge:

URL:
`https://allegroapi.io/after-sales-service-conditions/implied-warranties?sellerId=48557097`

STREAM_CONTEXT:
`array(1) {
  ["http"]=>
  array(4) {
    ["method"]=>
    string(3) "GET"
    ["header"]=>
    string(878) "Authorization: Bearer ##TUTAJ_TOKEN## 
Api-Key: ##TUTAJ_KLUCZ_API##
Accept-Language: PL
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json;charset=UTF-8"
    ["content"]=>
    string(2) "[]"
    ["ignore_errors"]=>
    bool(true)
  }
}`

RESPONSE:
`array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(5) {
      ["code"]=>
      string(9) "FORBIDDEN"
      ["message"]=>
      string(9) "Forbidden"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(51) "You do not have permission to request this resource"
    }
  }
}`

**Comment by LukaszKorek** [comment]
Dzień dobry. W takich sytuacjach najczęściej problemem jest token tzn. nie jest do tego loginu czyli użytkownicy próbują pobrać dane nie do tego konta. Proszę to sprawdzić.

**Comment by barthoos** [comment]
Ekhm. Moj blad - nie napisalem rzeczy oczywistej. Oczywiscie uzytkownik sie zgadza. Gdyby sie nie zgadzal to w ogole nie robilbym zgloszenia.

Token wygenerowany jest pod dany login (sellerId), na tym loginie sa tez uslugi pozakupowe. Jak mowilem - zdarza sie to raz na jakis czas i puszcza po pewnym czasie.

**Comment by LukaszKorek** [comment]
W tej sytuacji poproszę o klucz API.

**Comment by LukaszKorek** [comment]
Oczywiście klucza nie wklejaj tutaj. Możesz skorzystać z formularza https://pomoc.allegro.pl/kontakt

**Comment by barthoos** [comment]
Klucz API przeslany [Ticket#1245769602] .

Natomiast w miedzyczasie (jak zreszta sygnalizowalem) moim automatom udalo sie pobrac uslugi pozakupowe dla podanego sellerId. Mimo wszystko doprowadzmy sprawe do konca, bo to jest N-ty raz jak mi sie cos takiego zdarza. Tym razem po prostu mialem dosc pary, zeby sprawe pociagnac dalej (no i nie moglem sie powstrzymac, zeby wyprobowac GitHuba).

To co mi sie _wydaje_ to ze jest to jakas kwestia replikacji danych do subsystemow dla _albo_ nowo utworzonych konta allegro, _albo_ nowo zweryfikowanych loginow w danej aplikacji zewnetrznej. Wnioskuje na podstawie zgloszen od moich klientow - zawsze to byly nowe konta a nie juz istniejace w mojej aplikacji.

**Comment by LukaszKorek** [comment]
Sprawdziliśmy i wszytsko wskazuje na to, że to jednak  błędny token.  Prawdopodobnie dlatego zaczyna działać po kilku dniach - być może token wtedy traci ważność i następuje kolejne logowanie, już z poprawnym tokenem. Proszę upewnić się jeszcze raz czy błąd nie występuje po Państwa stronie.

**Comment by barthoos** [comment]
Dzieki za sprawdzenie, aczkolwiek troszke nie chce mi sie w to wierzyc. Reset przyznanego tokena to pierwsza rzecz, ktora zalecilem klientowi (usunalem w bazie zapisane tokeny dostepowe na kliencie, wymuszajac tym samym jego ponowna autoryzacje). Jezeli natomiast rzeczywiscie token jest bledny to znaczy, ze blad jest wczesniej - w samym mechanizmie nadawania tokena. 

Nic, zglosze sie ponownie, gdy bede mial taki przypadek "na goraco". Wtedy bedziecie mogli sprawdzic na zywym organizmie, ze token jest poprawny a zadanie zwraca FORBIDDEN. Teraz juz sie zautoryzowalo bez problemow, wiec nic nie potestujemy..
