### ISSUE TITLE
Wyszukiwanie kategorii REST API /sale/categories/{search}

### ISSUE THREAD

**Issue by a4gpl** [allegro/allegro-api#350]
Witam,
Tworzymy integrację Magento 2 z Allego Rest Api. Chcemy uniknąć replikacji danych, ale jednocześnie w założeniu mamy, że kategorie allegro będą miały wyszukiwarkę, stąd moje pytanie czy istnieje szansa, na to aby enpoint /sale/categories/{categoryId} dostał dodatkowy paramter np
/sale/categories/{categoryId}/{search} ew. /sale/categories/{search}?
W związku z częstymi zmianami w Allegro nie chcielibyśmy przechowywać kategorii w naszej bazie danych,  a jednocześnie nie chcemy za przy każdej kategorii odpytywac restapi o całe drzewo kategorii, tylko po to by wyszukiwarka działała na podkategoriach.
Z góry dziękuję za odpowiedź. M.S.

**Comment by KrzysztofLukanowski** [comment]
Cześć. Nie mieliśmy takich planów, ale dziękuję - sugestię przekazałem zespołowi pracującemu nad API.
