### ISSUE TITLE
Czy można pobrać wszystkie zamówienia

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#3500]
Czy można pobrać wszystkie zamówienia za pomocą `/order/checkout-forms`? przy offset 10000 mamy błąd.

**Comment by AureliuszBrussy** [comment]
Przekroczyliście maksymalną wartość offset. Suma offset i limit na zasobie /order/checkout-forms nie może przekroczyć 10 000. Możecie skorzystać z dodatkowych filtrów, np. daty zamówienia:

- lineItems.boughtAt.lte={data} - najpóźniejsza data złożenia zamówienia,
- lineItems.boughtAt.gte={data} - najwcześniejsza data złożenia zamówienia.

Więcej o dostępnych filtrach [tutaj](https://developer.allegro.pl/orders/#lista-zam%c3%b3wie%c5%84).
