### ISSUE TITLE
Uwagi kupującego do zamówienia

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3501]
Witam,
pobierając szczegóły konkretnego zamówienia za pomocą :
https://api.allegro.pl/order/checkout-forms/{checkoutForm_id}
nie znalazłem w response pola "Uwagi kupującego do zamówienia"
Czy to pole nie jest pobierane za pomocą powyższego requesta?
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Wiadomość dla Sprzedającego dostępna jest w polu ""messageToSeller" - przykładowy response:

```
{
    "id": "eb44a242-d55d-11ea-9a82-e9d1786a211f",
    "messageToSeller": "Test notki",
    "buyer": {
        "id": "xxxxxxx",
        "email": "ddmnmwwgos+71075b560@user.allegrogroup.pl"
...
```

**Comment by crazyhtm** [comment]
A czy istnieje możliwość pobrania **notatki** ?

**Comment by MaciejFrackowiak** [comment]
@crazyhtm Nie, pole "notatka" dostępne jest wyłącznie na WWW.
