### ISSUE TITLE
Filtering ADVERTISEMENTs via REST or getting their infos via SOAP

### ISSUE THREAD

**Issue by joel-a11y** [allegro/allegro-api#3502]
Hello,

Recently I've found out that there are types of offers other than common auction offers and buy now offers. Their sellingMode->format is equal to ADVERTISEMENT. Offers of this type are returned as a result of request to REST API endpoint "/offers/listing". Unfortunately, SOAP API with it's "doGetItemsInfo" can't get any offer of this type. Is there any custom filter for "/offers/listing" which could be applied to get only common "BUY NOW" offers ? "sellingMode.format" => "BUY_NOW" does not help. 

Thanks in advance for any help!

**Comment by AureliuszBrussy** [comment]
By using parameter sellingMode.format=BUY_NOW on /offers/listing endpoint, you should get only Buy Now offers. Also, in SOAP there is a field “itAdvertisementActive” which returns information does offer is advertisement or not. Send us your full request and response via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (add info about Github #3502 thread), we will verify this issue.
