### ISSUE TITLE
Brak daty zakończenia w danych szczegółowych oferty

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#3503]
Niestety część zakończonych ofert Użytkownika jest zwracana bez daty zakończenia.
Czy mogę prosić o informację, dlaczego tak się dzieje?
```
"publication": {
    "endedBy": "USER",
    "status": "ENDED",
    "endingAt": null,
    "republish": false,
    "duration": null,
    "startingAt": null
  },
  "updatedAt": "2020-06-22T10:10:05.818Z",
```

**Comment by AureliuszBrussy** [comment]
W polu "endingAt" znajduje się informacja, do kiedy oferta trwa, oczywiście jeżeli czas trwania został wcześniej określony. Jeżeli podczas uzupełniania draftu oferty w polu "duration" nie przekażesz konkretnego czasu trwania oferty (co oznacza, że będzie ona wystawiona do wyczerpania zapasów), w polu "endingAt" zawsze zobaczysz wartość null.

**Comment by tomasz-grzesik** [comment]
Aha. W takim razie problem wynika z mojego niezrozumienia zawartości pola.
Czy może Pan poradzić jakiś sposób na proste uzyskanie daty zakończenia oferty?
Czy pole "updatedAt" dotyczy również zakończenia oferty, czy może trzeba śledzić dziennik zdarzeń ofert?

**Comment by AureliuszBrussy** [comment]
Pole "updatedAt" to data ostatniej aktualizacji dowolnego pola w ofercie. Jeżeli ostatnią zmianą w ofercie było jej zakończenie - będzie to data zakończenia oferty. Aby zobaczyć datę zakończenia oferty (jeżeli do zakończenia doszło), skorzystaj z zasobu GET /sale/offers (nie przekazuj id oferty). Jeżeli status konkretnej oferty to ENDED - w obiekcie "publication" zobaczysz pole "endedAt" - jest to data zakończenia oferty.

**Comment by tomasz-grzesik** [comment]
Dziękuję za podanie efektywnej metody.
