### ISSUE TITLE
BOUGHT->FILLED_IN wymuszenie nastąpienia

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3504]
Mam takie proste pytanko: czy jeżeli pojawia się event 'BOUGHT' to czy możliwa jest sytuacja że nie będzie uzupełniony żaden formularz dostawy (tzn z jakiegoś powodu nie wystapią inne kolejne statusy np. 'FILLED_IN') Wydaje mi się że warunkiem zakupu jest wypełnienie jakiegokolwiek formularza co by znaczyło że FILLED_IN musi wystąpić, mam rację?

**Comment by AureliuszBrussy** [comment]
Zdarza się, że kupujący nie uzupełnia danych dotyczących zakupu, dlatego może nastąpić sytuacja, że po evencie BOUGHT nie nastąpią kolejne zdarzenia. Dodatkowo warto zwrócić uwagę, że z uwagi na uwarunkowania techniczne, zdarzenia mogą pojawić się w nieoczekiwanej kolejności. Jest możliwość by np. zdarzenie ze statusem FILLED_IN pojawiło się przed BOUGHT.

**Comment by marcinja2** [comment]
dzieki
