### ISSUE TITLE
Jak zmienić stawkę w kampanii allegro ads?

### ISSUE THREAD

**Issue by dark774** [allegro/allegro-api#3505]
Jak można zmienić stawkę dla kampanii allegro ads? jeżeli nie ma takiej możliwości kiedy planujecie dodać taki zasób?

**Comment by MaciejFrackowiak** [comment]
Zasoby do obsługi ADS nie są zasobami publicznie dostępnymi, dlatego bezpośrednio na forum nie prowadzimy wsparcia w zakresie ich wykorzystania.

**Comment by dark774** [comment]
Czy planujecie ten zasób zrobić publicznym?

**Comment by MaciejFrackowiak** [comment]
Jeżeli w przyszłości podjęta zostanie decyzja o upublicznieniu tych zasobów, to na pewno poinformujemy o tym w osobnym komunikacie na forum oraz w [aktualnościach](https://developer.allegro.pl/news/) na portalu.
