### ISSUE TITLE
Dodanie produktu podczas wystawienia oferty.

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#3506]
Witam serdecznie.

Czy jest możliwość aby automatycznie dodać produkt podczas wystawiania oferty? 
Aktualnie mogę bezproblemowo dodawać oferty i chciałbym ten moduł rozbudować tak żebym nie musiał ręcznie klikać utwórz produkt z poziomu panelu Allegro.

Dodatkowo w jaki sposób pobrać dane do produktów które nie posiadają własnych kodów EAN?
Przykładowe kategorie:  261207, 6089, 6090, 6091, 6092, 6093, 6094, 6095, 6096,6097, 6087
Gdzie ProductEANRequired=True

Dane które mnie interesują to:
- identyfikator produktu (product.id)
- zgodny z wybranym produktem identyfikator kategorii
- zgodne z wybranym produktem parametry i ich wartości parametrów
- zgodną z  wybranym produktem pojedynczą wartość parametru GTIN
- zgodną z wybranym produktem zawartość sekcji Pasuje do (compatibilityList)
- zgodną z wybranym produktem specyfikację techniczną TecDoc (tecdocSpecification).

Bardzo proszę o wskazówkę gdzie mogę tych danych szukać, a ja w między czasie idę grzecznie czytać dokumentacje :)

**Comment by MaciejFrackowiak** [comment]
Możliwość dodania produktu podczas wystawiania oferty (jeżeli takiego produktu nie mamy w bazie) istnieje, gdy skorzystasz z opcji uproszczonego wystawiania ofert połączonych z produktem z wykorzystaniem [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). Proces ten szczegółowo opisaliśmy w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-wystawi%c4%87-ofert%c4%99-z-produktem-kt%c3%b3rego-nie-ma-w-naszej-bazie).
Alternatywym rozwiązaniem jest przeszukanie naszej bazy produktów korzystając z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts), dzięki któremu uzyskasz product.id niezbędny do powiązania produktu z ofertą podczas wystawiania samej oferty z użyciem [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST). W przypadku tego rozwiązania warto, abyś spojrzał do [poradnika](https://developer.allegro.pl/productization/).

**Comment by Troom** [comment]
Super, ładnie mi to pan przedstawił, ale na daną chwilę widzę kolejną wątpliwość. 
Jak wspomniałem wcześniej towar który sprzedaje nie posiada kodów EAN, dlatego proponuje o zmianę ProductEANRequired=False.

Do wspomnianych kategori prosiłbym o dodanie parametru produktowego (najlepiej do wymaganych):

ExpansionCode: string limit 5 znaków. Na daną chwilę jest około 400 dodatków.
https://en.wikipedia.org/wiki/List_of_Magic:_The_Gathering_sets

Język: string (3 znaki).  Ewentualnie dictionary też może być, bo języków będzie około 10. Jeśli trzeba będzie mogę przygotować liste.

Są karty o tej samej nazwie, które zostały wydane w róznych edycjach. Jeśli nie dodamy tego parametru, klient nie będzie wiedział z ktorego dodatku kupuje kartę. Z językiem sytuacja wygląda analogicznie.

**Comment by MaciejFrackowiak** [comment]
Twoje wątpliwości przekazałem do działu odpowiedzialnego za zarządzanie kategoriami i parametrami.

**Comment by Troom** [comment]
Super, kiedy mogę się spodziewać odpowiedzi?
Głównie zależy mi na zajęciu jakiegoś stanowiska w sprawie kodów EAN, bo bez nich aktualnie nie moge wystawiać ofert powiązanych z produktem.

**Comment by MaciejFrackowiak** [comment]
Temat jest konsultowany - i tu prośba o cierpliwość, wrócę z odpowiedzią.

**Comment by Troom** [comment]
Chciałbym sie przypomnieć.

**Comment by MaciejFrackowiak** [comment]
Wracam z update`m - flaga ProductEANRequired została zdjęta dla kategorii z grami karcianymi.

**Comment by Troom** [comment]
A co w przypadku gdy karty są z innych dodatków, lub w innym języku?

**Comment by MaciejFrackowiak** [comment]
Twoje pytania i wątpliwości stricte dotyczą układu kategorii oraz parametrów Allegro, nie zaś samej funkcjonalności API, dla której działamy tu na forum. Dlatego prośba, abyś skorzystał z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i w nim przedstawił dalsze kwestie dot. układu kategorii oraz parametrów dla nich przewidzianych.

**Comment by Troom** [comment]
Rozumiem, nie mam więcej pytań.

**Comment by Troom** [comment]
Mogę prosić o aktualizacje Sandboxa. Po próbie wystawienia produktu otrzymuje błąd:

code=ConstraintViolationException.ProductParameterGTINRequired
userMessage=W tej kategorii wymagane jest podanie parametru EAN.

**Comment by MaciejFrackowiak** [comment]
Postaram się zadziałać w tej materii - może to jednak trochę potrwać. Wrócę z odpowiedzią, gdy będę miał już właściwe info.

**Comment by MaciejFrackowiak** [comment]
Flaga ProductEANRequired została usunięta z wymienionych kategorii na Sandbox.

**Comment by Troom** [comment]
Super, dziękuje , działa :).
Na daną chwilę temat zamykam, jeśli w temacie produktyzacji pojawią się problemy, to wrócę do tematu.

**Comment by MaciejFrackowiak** [comment]
Tak, flaga ProductEANRequired była zdjęta. Problem w Twoim wypadku powodowała flaga już przy samym parametrze EAN, gdzie "requiredForProduct" było nadal ustawione na true - od teraz jest już false.

**Comment by Troom** [comment]
Spoko, dzięki udało mi sie dodać produkty,.
Teraz jeszcze prosiłbym o poprawkę API Sandboxowego, bo na produkcje wskoczyły dwa nowe parametry - Język i Expansions.
![image](https://user-images.githubusercontent.com/10126507/92585981-f43e6480-f295-11ea-8d9d-74838873beab.png)

**Comment by MaciejFrackowiak** [comment]
Niestety, tu już nie mam możliwości pomóc "od ręki" - parametry i kategorie na Sandbox są uspójniane względem produkcji raz na jakiś czas, nie jest to proces punktowy. Jeżeli dojdzie do takiej aktualizacji, to zamieścimy osobny komunikat - na wzór https://github.com/allegro/allegro-api/issues/3267.

**Comment by Troom** [comment]
OK, no to trudno, potestuje na produkcji.

Kolejna sprawa - podczas próby dodania nieistniejacego produktu otrzymuje INTERNAL_SERVER_ERROR.
Proszę o potwierdzenie ze wszystko działa prawidłowo na Sandboxie, podczas próby wysłania GET'a na /sale/product-proposals

**Comment by MaciejFrackowiak** [comment]
Komunikat, który otrzymujesz sugeruje na problem z samym requestem - zasób POST /sale/product-proposals funkcjonuje na Sandbox prawidłowo.

**Comment by Troom** [comment]
OK, mam kolejny problem - sekcja filters jest pusta.
O ile dobrze rozumiem, jeśli chce wyszukiwać parametry, to muszę się odwołac do istniejącego filtru.
Potrzebuje filtry zgodnie z parametrami Expanison, i Język (przy okazji można też zmienić nazwe tego parametru na Language)

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś wysłać przykład żądania, gdzie zwróciliśmy pustą sekcję filters? Pozwoli mi to dokładniej zapoznać się z sytuacją.

**Comment by Troom** [comment]
https://api.allegro.pl/sale/products?phrase={name}&category.id={categoryId}
Konkretny przykład:
https://api.allegro.pl/sale/products?phrase=Tumble%20Magnet&category.id=6089

**Comment by AureliuszBrussy** [comment]
W GET /sale/products możesz filtrować tylko po słownikowych parametrach identyfikujących. W tej kategorii nie ma obecnie takiego parametru, stąd brak filtru.

**Comment by Troom** [comment]
No to moim skromnym zdaniem mamy tutaj błąd, który trzeba będzie jakoś rozwiązać.

Karty z róznych edycji mają rózne obrazki, przykładowo:
Lighting bolt z dodatku MPR
https://static.cardmarket.com/img/5d7a85496b818d6ed2017183875bca6f/items/1/MPR/21797.jpg
Lighting Bold z dodatku M11
https://static.cardmarket.com/img/9c572ba74077d00e235f129bed3a2bdf/items/1/M11/241866.jpg

Czyli dodany produkt jest niewele wart, bo przekazuje złe wartości. 
Jak w tym przypadku dodawać aukcje powiązaną z produktem?
Proszę wziąść pod uwagę ze występują kolosalne różnice w cenach pomiędzy róznymi dodatkami.

**Comment by AureliuszBrussy** [comment]
Aktualnie twoje zgłoszenie dotyczy parametrów Allegro, nie samej funkcjonalności API. Proszę, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), jeżeli masz wątpliwości związane rodzajem parametrów i możliwymi wartościami w tych parametrach.

**Comment by Troom** [comment]
Ech, rozumiem, zatem przekazuje problem do właściwego działu. Dziękuje za pomoc.

**Comment by Troom** [comment]
OK kolejny problem podczas proby dodania produktu:
![image](https://user-images.githubusercontent.com/10126507/95209546-c263e380-07ea-11eb-846d-278b74b7b3fc.png)

Czy mógłbym prosić o jakąś sugestie jak w tym przypadku wystawić oferte powiązana z produktem?

**Comment by Troom** [comment]
Czyli wnioskuje ze w takich sytacjach należy dodawać kolejny produkt, dostosowany do nazwenictwa każdej z firm wystawiającej oferty powiązane z produktem.

**Comment by Troom** [comment]
OK pytanie kolejne - jaki sposób jest weryfikowany dodawany produkt. Wysyłam produkt który nie istnieje w bazie danych (sprawdzam to poprzez ręczną próbe wystawienia artykułu).
Wysyłane dane:
![image](https://user-images.githubusercontent.com/10126507/95320852-68225b80-089a-11eb-871d-6bc631ac8b0f.png)

Zwracana odpowiedz:
![image](https://user-images.githubusercontent.com/10126507/95320884-76707780-089a-11eb-9b3b-12a127dbcc4c.png)

**Comment by AureliuszBrussy** [comment]
Sprawdzamy wprowadzone parametry - jeżeli jesteśmy w stanie zidentyfikować produkt po parametrach identyfikujących i produkt z takimi samymi parametrami istnieje już w naszej bazie - jest on rozpoznawany. 

Jeżeli produkt już istnieje - wystawiając ofertę powiązaną z produktem nie musisz w tytule oferty korzystać z istniejącej nazwy produktu. Możesz wporwadzić swój własny tytuł oferty. Modyfikacja nazwy samego produktu nie jest jednak możliwa.

**Comment by Troom** [comment]
OK, większość produktów wystawiam bezproblemowo ale natrafiłem na wyjątek.
Adres Url requesta: https://api.allegro.pl/sale/products?phrase=Relic%20Golem&category.id=6089
Znalezione produkty:
![image](https://user-images.githubusercontent.com/10126507/95465244-2ae1ca80-097b-11eb-9e52-f6e2ad5233f5.png)

Teoretycznie moge wybierać każdy z nich, ale interesuje mnie dodanie bardziej szczegółowego produktu z kompletem danych. Dlatego wysyłam propozycje produktu
[RequestAllegro.txt](https://github.com/allegro/allegro-api/files/5348158/RequestAllegro.txt)

> {
> 	"id": null,
> 	"name": "Relic Golem ZNR EX Foil",
> 	"category": {
> 		"id": "6089"
> 	},
> 	"images": [
> 		{
> 			"url": "https://a.allegroimg.com/original/1114e6/3ca392cf449ca0cd71da0e10245f"
> 		}
> 	],
> 	"parameters": [
> 		{
> 			"id": "237194",
> 			"values": [
> 				"Wizards of the Coast"
> 			],
> 			"valuesIds": null,
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "234937",
> 			"values": [
> 				"Relic Golem"
> 			],
> 			"valuesIds": null,
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "5175",
> 			"values": null,
> 			"valuesIds": [
> 				"5175_30"
> 			],
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "247229",
> 			"values": null,
> 			"valuesIds": [
> 				"11326_656365"
> 			],
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "247612",
> 			"values": [
> 				"ZNR"
> 			],
> 			"valuesIds": null,
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "247611",
> 			"values": [
> 				"English"
> 			],
> 			"valuesIds": null,
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		},
> 		{
> 			"id": "5174",
> 			"values": null,
> 			"valuesIds": [
> 				"5174_32"
> 			],
> 			"rangeValue": null,
> 			"valuesLabels": null,
> 			"unit": null,
> 			"options": null
> 		}
> 	],
> 	"eaNs": null,
> 	"offerRequirements": null,
> 	"compatibilityList": null,
> 	"tecDocSpecification": null,
> 	"description": null
> }

W odpowiedzi otrzmuje ProductDuplicate
![image](https://user-images.githubusercontent.com/10126507/95465743-cbd08580-097b-11eb-99f1-bf0204e790b6.png)

Podsumowując - czy da sie dodać kolejny produkt który różni sie parametrami, w tym między innymi parametrem nazwy? Jeśli tak, to gdzie może być błąd?

**Comment by Troom** [comment]
Natknałem się jeszcze na ciekawy przypadek
https://api.allegro.pl/sale/products?phrase=Gamble&category.id=6092
Nie zwraca żadnych produktów, podczas próby dodania otrzymuje ProductDuplicate. 
Struktura wysyłanego pliku jest podobna do wcześniej podesłanego json'a w pliku RequestAllegro.txt.

**Comment by AureliuszBrussy** [comment]
Konsultuję to z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@Troom jeżeli chodzi o utworzenie produktu Relic Golem - produkt o takiej nazwie (w tej kategorii jest to parametr identyfikujący) już istnieje, stąd taki komunikat. Podobnie w przypadku drugiego produktu - widzę, że aktualnie produkt o nazwie "Gamble" istnieje w kategorii, stąd informacja o duplikacie.

**Comment by Troom** [comment]
@AureliuszBrussy 
AD1. Relic Golem - problem pojawia się gdy produkt został wcześniej dodany z błędną kategoria. Przykładowo, chce wystawić name="Relic Golem" w kategorii categoryId=6089.

Sprawdzam allegro reqestem "products?phrase={name}&category.id={categoryId}"
Znajduje dwie karty które w nazwie mają nazwe karty i rozszerzenie innego sprzedawcy między innymi jego login.

Gdy próbuje dodać właściwy produkt, w właściwej kategorii to jest to niemożliwe ponieważ produkt o właściwej nazwie istnieje w innej kategorii 6087, co jest błędem.

Jeśli spróbuje powiążać oferte z produktem z kategorii 6087 to jestem blokowany ponieważ istnieje róznica pomiędzy produktem a ofertą.

No i teraz pytanie - jak to rozwiązać - dodawać nazwe własną dla każdego artykuły? 
Każdorazowo prosić w o aktualizację błędu produktu? W przypadku 60k kart może to być dość uciążliwe.

AD2 Gamble - nie wiem czy cos było zmieniane z Waszej strony, udało mi się bez żadnej zmiany w kodzie dodać produkt.

**Comment by AureliuszBrussy** [comment]
Produkt 23aaad59-fdb8-4b8f-aa26-b114b8fe91f0 jest już we właściwej kategorii. W przypadku, gdy jednym parametrem identyfikującym produkt jest nazwa - próba utworzenie produktu o takiej samej nazwie będzie kończyła się niepowodzeniem i informacją o duplikacie. Tutaj wracamy do tematu dostępnych w tej kategorii parametrów i ich funkcjonowania - dlatego prośba, abyś skorzystał z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i w nim przedstawił kwestie dot. parametrów w tych kategoriach.

**Comment by Troom** [comment]
OK, poki co wymogi produktyzacyjne mam spełnione wiec nie jest to jakos super ważne, spróbuje się dogadać przez formularz i jak coś to wróce do tematu.
Na daną chwile dziękuje.

**Comment by Troom** [comment]
Od jakiegos czasu mam problem z parametrem język.

Wysyłam
![image](https://user-images.githubusercontent.com/10126507/104579082-cca04400-565b-11eb-9a34-3a569d26dd1a.png)
[ProductProposalRequestTest.txt](https://github.com/allegro/allegro-api/files/5813814/ProductProposalRequestTest.txt)

Otrzymuje:
![image](https://user-images.githubusercontent.com/10126507/104579121-dc1f8d00-565b-11eb-815e-1e5882bf84fd.png)
[ProductProposalResponseTest.txt](https://github.com/allegro/allegro-api/files/5813820/ProductProposalResponseTest.txt)

Co skutkuje błędem:
![image](https://user-images.githubusercontent.com/10126507/104579241-02ddc380-565c-11eb-9cf9-4251d7033f5c.png)
message=Invalid parameter Język (247611) value for offer with product. Value should be "angielski".

Czy jest możliwość wyłączenia tego mapowania, albo zmiany na parametry słownikowe?
Mówimy tutaj o przynajmniej 11 językach.

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś jeszcze przesłać pełen request kończący się błędem "message=Invalid parameter Język (247611) value for offer with product. Value should be "angielski"."?

**Comment by Troom** [comment]
Proszę bardzo
Request:
[AllegroOfferRequest.txt](https://github.com/allegro/allegro-api/files/5814765/AllegroOfferRequest.txt)

Response:
[AllegroOfferResponse.txt](https://github.com/allegro/allegro-api/files/5814769/AllegroOfferResponse.txt)

**Comment by AureliuszBrussy** [comment]
Potwierdzam - aktualnie mapujemy wartość "English" przekazaną w tym parametrze. Aby wystawić ofertę powiązaną z produktem - skorzystaj z wartości, które przekazujemy w odpowiedzi na Twoje żądanie [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct). Jeżeli natomiast masz sugestię dotyczącą zmiany tego parametru (np. aby był to parametr słownikowy) - proszę przekaż sugestię poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
