### ISSUE TITLE
Błąd => You cannot modify the name for offer with bids

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3507]
Zróbcie coś z tym błędem bo po pobraniu oferty ilość sprzedanych = 0 a powinna być > 0 skoro ktoś coś kupił. 

  Trace-id =>32d6f1cc445c5991

**Comment by AureliuszBrussy** [comment]
Nie ma tutaj błędu. Pole “sold” to liczba sprzedanych przedmiotów w ciągu ostatnich 30 dni. W ofercie, której dotyczy podane trace-id zakup był dokonany ponad 30 dni temu, dlatego wartość w tym polu wynosi 0. Zakup jednak nastąpił, dlatego nie możesz zmienić tytułu.
