### ISSUE TITLE
Czy można z klientowi wysłać maila z prośbą o ocenę ?

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#3508]
Przykładowo: 
Szanowny Iksiński, zależy nam na Twojej opinii, kupiłeś “Nasz Produkt”. Wystaw komentarz [LINK DO TRANSAKCJI]

Jak wygenerować link do transakcji ?

**Comment by AureliuszBrussy** [comment]
Generowanie takiego linku bezpośrednio którąś metodą w Allegro API nie jest możliwe. Link natomiast możesz wygenerować na podstawie id w obiekcie checkoutForms, który uzyskasz np. na zasobie /order/checkout-forms. Wystarczy, że podasz stały adres do zakładki Kupione + checkoutForm.id, w postaci: https://allegro.pl/moje-allegro/zakupy/kupione/{checkoutForm.id}. Kupujący zostanie przekierowany do konkretnego zamówienia.

**Comment by KrzychuWalek** [comment]
Super. Bardzo dziękuję za odpowiedź.

**Comment by KrzychuWalek** [comment]
Byłem na urlopie i trochę późno testuję.
Coś nie tak z linkiem. zwraca mi Hello, response delay = 0 oraz zakodowany błąd.
Jestem odpowiednio zalogowany

 https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione/af1a9022-e20c-11ea-8d6d-1573c1accd10

**Comment by KrzychuWalek** [comment]
Już działa, dziękuje
