### ISSUE TITLE
how to set order status?always get 400 error 

### ISSUE THREAD

**Issue by whyun1** [allegro/allegro-api#3509]
Hi, 
I tried to set order status, but always get error.
 {"code":"ERROR","message":"An error has occurred","details":null,"path":"/order/checkout-forms/{checkoutformid}/fulfillment","userMessage":null}]}

**Comment by AureliuszBrussy** [comment]
Please send your full request in curl format via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Also please add GitHub thread number - 3509.

**Comment by webkret** [comment]
> @webkret Zapoznamy się z Twoim requestem i wrócimy z odpowiedzią.

Czy udało się coś ustalić?

**Comment by PrzemyslawLukanowski** [comment]
Niestety ze względu na dużą liczbę języków programowania, nie prowadzimy wsparcia dla każdego z nich. Prześlij ponownie swój request w formacie cURL, możesz to zrobić tutaj. Usuń przy tym wrażliwe dane, takie jak token.
