### ISSUE TITLE
Dokumentacja - zduplikowane pole w poradniku "Jak powiązać ofertę z produktem"

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#3510]
{
    "id": "224017",
    "name": "Kod producenta",
    "type": "string",
    "required": false,
    "**requiredForProduct**": false,
    "unit": null,
    "**requiredForProduct**": true
    "options": {
        "variantsAllowed": false,
        "variantsEqual": false,
        "ambiguousValueId": null,
        "dependsOnParameterId": null,
        "describesProduct": true
    },
    "restrictions": {
        "minLength": 2,
        "maxLength": 35,
        "allowedNumberOfValues": 1
    }
 },

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie błędu. Już poprawiliśmy poradnik.
