### ISSUE TITLE
Id przewoźnika

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#3512]
Proszę o podanie carrier.Id przewoźnika spoza listy dostępnych. (Other)

**Comment by AureliuszBrussy** [comment]
Wartość “OTHER” funkcjonuje jako nazwa własna operatora przesyłki. Nie jest to metoda dostawy, którą można zdefiniować w cenniku dostawy. Zbiór dostępnych metod dostawy jest zamknięty. Wszystkie dostępne możliwości uzyskasz korzystając z GET na zasobie /sale/delivery-methods.

**Comment by mojosoft** [comment]
Jaki w takim razie carrier.Id  podać dla operatora nie znajdującego się na liście ?

**Comment by mojosoft** [comment]
dokładnie chodzi o to jakie carrier.id przesłac z informacją o numerze przesyłki
https://developer.allegro.pl/orders/#jak-doda%c4%87-numer-przesy%c5%82ki-do-przedmiotu-w-zam%c3%b3wieniu

**Comment by AureliuszBrussy** [comment]
Dziękuję za doprecyzowanie - "carrierId" dla innego przewoźnika to po prostu "OTHER". Dodatkowo przekaż nazwę przewoźnika w polu "carrierName".

Przykładowe body takiego requesta:

{
    "carrierId": "OTHER",
    "waybill": "12345678910PL",
    "carrierName": ”PrzykładowaNazwa”
    "lineItems": [
        {
        "id": "31896450-2de1-11e9-bced-352ab82ad9cd"
        }
    ]
  }

**Comment by mojosoft** [comment]
Dziękuje
