### ISSUE TITLE
Parametr uzupełniany samodzielnie

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3513]
W częściach samochodowych istnieje taki parametr jak numery katalogowe zamienników. Jak rozumiem powinien być to parametr do którego wartości przekazuje się w ten sposób:

> {
>     	"id": "...",
>     	"valuesIds": [],
>     	"values": [
>         	"zielony",
>         	"żółty",
>         	"czerwony"
>     	],
>     	"rangeValue": null
> }

Chciałbym dowiedzieć się która właściwość wskazuje na ten rodzaj uzupełniania. Jest to tylko zależne od tego czy AllowednumberOfValues jest większe od 1?

**Comment by PrzemyslawLukanowski** [comment]
O tym, że to użytkownik musi uzupełnić wartość świadczy "type" tego parametru, czyli "string" - tę informację sprawdzisz za pomocą [GET /sale/categories/{id}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). AllowednumberOfValues wskazuje liczbę wartości, które możesz przekazać.
