### ISSUE TITLE
Regularne błędy "The stock level of items to be listed may not be lower than 1" pomimo dodatniej ilości sztuk

### ISSUE THREAD

**Issue by kieliszek85** [allegro/allegro-api#3514]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ X] inny

Podczas modyfikacji oferty (zasób sale/offers PUT), pomimo ustawiania prawidłowej wartości pola "available" otrzymujemy błędy: The stock level of items to be listed may not be lower than 1

Dzieje się tak regularnie dla niektórych ofert, tak naprawdę problem obserwowaliśmy już kilka miesięcy temu.
Przykładowe numery ofert: 9241154157, 9501140221, 9502213755

Co ważne - problem również jest obserwowany, gdy ręcznie próbujemy edytować ofertę.
Dla powyższych ofert próba ustawienia ilości 5, 10 a nawet 900 skutkuje błędem "The stock level of items to be listed may not be lower than 1".
W panelu Allegro podanie ilości 1000 wystarczy aby oferta się poprawnie zapisała, ale API dla tej ilości ciągle zwraca błąd.
Gdy podam wartości rzędu 10 000 wówczas oferty poprawnie aktualizują się również poprzez API.

**Comment by AureliuszBrussy** [comment]
Zweryfikowałem logi dla tych ofert, potwierdzam błąd. Przekazałem sprawę do zespołu, który zajmie się dalszą analizą problemu.

**Comment by AureliuszBrussy** [comment]
@kieliszek85 uspójniliśmy wskazane oferty. Możesz już poprawnie zmienić w nich liczbę sztuk.

**Comment by kieliszek85** [comment]
@AureliuszBrussy Dziękuję. Jaki jest najprostszy/najszybszy sposób zgłaszania tego typu ofert? Skoro jest to problem związany z jakąś niespójnością danych w tych konkretnych ofertach, to zakładam że jest duża szansa że będzie dalej od czasu do czasu występował.

**Comment by AureliuszBrussy** [comment]
@kieliszek85 jeżeli będziesz miał ten sam problem z innymi ofertami - przekaż je w tym wątku.

**Comment by kieliszek85** [comment]
@AureliuszBrussy Zdaje się że ten sam problem dotyczy oferty 9667517766

**Comment by AureliuszBrussy** [comment]
@kieliszek85 zgłosiłem już problem w tej ofercie do odpowiedniego zespołu. Wrócę z informacją.

**Comment by kieliszek85** [comment]
@AureliuszBrussy Problem w dokładnie tej samej ofercie dalej występuje. Kiedy możemy się spodziewać rozwiązania problemu?

**Comment by AureliuszBrussy** [comment]
@kieliszek85 zgadza się, problem w tej ofercie wciąż występuje. Poinformowałem odpowiedni zespołu. Bardzo proszę o jeszcze trochę cierpliwości.

**Comment by AureliuszBrussy** [comment]
@kieliszek85 problem nie powinien już występować.

**Comment by kieliszek85** [comment]
@AureliuszBrussy niestety problem dalej występuje, dzieje się to przy próbie ustawienia poprzez API ale również kiedy w panelu po zalogowaniu w tej ofercie próbuję ustawić ilość dostępnych sztuk np. na 5

**Comment by AureliuszBrussy** [comment]
@kieliszek85 proszę, sprawdź teraz, błąd nie powinien już wystąpić.

**Comment by kieliszek85** [comment]
@AureliuszBrussy podaję 2 kolejne numery ofert których problem dotyczy: 9676517860, 9676518284

**Comment by AureliuszBrussy** [comment]
@kieliszek85 dziękuję, zgłosiłem już problem dot. tych ofert do odpowiedniego zespołu. Wrócę z informacją.

**Comment by cyfranT** [comment]
Zgłaszam identyczny problem dla aukcji: 
10000071690,10000075361,10000078891,10000082374

**Comment by AureliuszBrussy** [comment]
@cyfranT zgłosiłem problem z tymi ofertami do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@cyfranT problem nie powinien już występować.

**Comment by fabianCyfran** [comment]
Zgłaszam problem z ofertą 10000121500

**Comment by PrzemyslawLukanowski** [comment]
@fabianCyfran Przekazałem problem do odpowiedniego zespołu, wrócę z odpowiedzią.

**Comment by fabianCyfran** [comment]
Zgłaszam kolejne oferty z tym problemem: 10000121367, 10000121591, 10000084090

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem również te numery ofert, wrócę z informacją po rozwiązaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@fabianCyfran Wyeliminowaliśmy problem dla ofert, które wskazałeś.

**Comment by fabianCyfran** [comment]
@PrzemyslawLukanowski dziękuję. Zgłaszam kolejny przypadek: 10000110684

**Comment by PrzemyslawLukanowski** [comment]
Ten przypadek również przekazałem do poprawy.

**Comment by PrzemyslawLukanowski** [comment]
@fabianCyfran Problem dla tej oferty również wyeliminowany.

**Comment by fabianCyfran** [comment]
Zgłaszam kolejny przypadek: 10000087850

**Comment by AureliuszBrussy** [comment]
@fabianCyfran dla oferty 10000087850 problem nie powinien już występować.

**Comment by fabianCyfran** [comment]
Zgłaszam przypadek: 10000068287

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem to już do odpowiedniego zespołu. Po poprawieniu wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy ofertę.

**Comment by fabianCyfran** [comment]
Zgłaszam kolejne oferty: 10000071624,10000073159.
Czy wiadomo co jest przyczyną występowania tego błędu?

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem wskazane oferty do odpowiedniego zespołu. 

Wiemy co jest przyczyną problemu - powinniśmy go rozwiązać do końca tego kwartału.

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 9725590121

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem to już do odpowiedniego zespołu. Po poprawieniu wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy wskazaną ofertę.

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 10000106688

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy wskazaną ofertę.

**Comment by kieliszek85** [comment]
Zgłaszam ofertę: 10454755479

**Comment by AureliuszBrussy** [comment]
@kieliszek85 uspójniliśmy wskazaną ofertę.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy tą ofertę.

**Comment by kieliszek85** [comment]
zgłaszam ofertę: 10454754660

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 10000067001

**Comment by AureliuszBrussy** [comment]
@kieliszek85 @fabianCyfran zgłosiłem to już do odpowiedniego zespołu. Po poprawieniu wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran @kieliszek85 uspójniliśmy obydwie oferty.

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 10000103195

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy tą ofertę.

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 10000073684

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy wskazaną ofertę.

**Comment by fabianCyfran** [comment]
Zgłaszam aukcję 10000076878

**Comment by Lukasz-Zurek** [comment]
@fabianCyfran Uspójniliśmy ofertę.

**Comment by fabianCyfran** [comment]
Zgłaszam ofertę: 10000081008

**Comment by AureliuszBrussy** [comment]
@fabianCyfran zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@fabianCyfran uspójniliśmy wskazaną ofertę.
