### ISSUE TITLE
Access token expired

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#3516]
Mam pytanie o Access token zgodnie z dokumentacją ważny jest 12 godzin (ustawiłem więc odświeżanie 3 razy na dobę dla pewności) natomiast bardzo często otrzymuję odpowiedź: invalid_token Access token expired
Jaka może być przyczyna wygaśnięcia tokena przed upływem 12 godzin?

**Comment by AureliuszBrussy** [comment]
Zweryfikowałem logi dla tych ofert, potwierdzam błąd. Przekazałem sprawę do zespołu, który zajmie się dalszą analizą problemu.

**Comment by AureliuszBrussy** [comment]
Powodem wygaśnięcia tokena przed upłynięciem 12 godzin może być to że:
- skorzystałeś już z refresh tokena, generując nową parę tokenów. Gdy otrzymałeś nową parę access oraz refresh token - wcześniejsza para traci ważność, nawet jeżeli nie minęło jeszcze 12 godzin;
- użytkownik zmienił hasło.

Możesz nam przesłać przykładowe żądania i odpowiedzi poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W treści dodaj numer postu z GitHub - #3516. Zweryfikujemy, co dokładnie wydarzyło się w Twoim przypadku.
