### ISSUE TITLE
Sandbox sale/product-offers Not Acceptable representation requested. Please check 'Accept' request header.

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#3517]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas próby wrzucenia POST'a na api.allegro.pl.allegrosandbox.pl/sale/product-offers otrzymuję błąd:
Not Acceptable representation requested. Please check 'Accept' request header.

Sam Accept prezentuje się następująco:  "application/vnd.allegro.public.v1+json"

Co ciekawe poza tym zasobem komunikacja działa prawidłowo.(wystawianie ofert, pobieranie zamówień) Proszę o potwierdzenie ze wszystko jest OK, i jeśli tak to zaczynam szukanie przyczyny błędu.

**Comment by PrzemyslawLukanowski** [comment]
Ten zasób jest jeszcze w wersji beta, dlatego w nagłówku przekaż 'application/vnd.allegro.beta.v1+json'.

**Comment by Troom** [comment]
Faktycznie, nawet w dokumentacji jest na przykładowym zapytaniu. Teraz wszystko działa prawidłowo, dziękuje ;)
