### ISSUE TITLE
FILLED_IN a brak danych do wysyłki

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3518]
np w zamowieniu:  ac6f085c-d7bd-11ea-b566-9739757ccba0 o statusie FILLED_ID nie podajecie danych do wysyłki tymczasem w Waszym Managerze Sprzedaży takie dane już widnieją. wpłata jest rozpoczęta (i raczej nie będzie zakończona), wybrany został rodzaj dostawy (kurier). Natomiast np w zamowieniu "0d2f6d24-d8df-11ea-ad69-89fd2375ba41" o tym samym statusie  rodzaj dostawy paczkomat jest zawarta informacja o konkretnym paczkomacie jednak brakuje telefonu podczas gdy jest on widoczny w Waszym Managerze Sprzedaży. Czy zatem ja czegoś nie rozumiem czy tak powinno być?

**Comment by AureliuszBrussy** [comment]
W Allegro REST API dane do wysyłki w zamówieniu zobaczysz dopiero w momencie, gdy zamówienie ma status READY_FOR_PROCESSING. W przypadku zdarzenia FILLED_IN - dane dostawy mogą się jeszcze zmienić, dlatego nie możesz ich pobrać. W przypadku dostawy do punktu odbioru i statusu FILLED_IN  - adres punktu odbioru w obiekcie "pickupPoint" będzie już widoczny, natomiast nie będzie danych w polu "address" w strukturze "delivery". 

Aby przejść do kolejnych kroków realizacji zamówienia - poczekaj na event READY_FOR_PROCESSING. Menedżer Przesyłek działa w oparciu o inne mechanizmy, stąd różnice w dostępie do poszczególnych danych.

**Comment by Radeq** [comment]
@AureliuszBrussy, kiedy planujecie zaktualizować Manager Sprzedaży aby pokazywał takie same dane jak zakładka zamówienia w panelu sprzedawcy ( /moje-allegro/sprzedaz/zamowienia )?

**Comment by AureliuszBrussy** [comment]
W Menadżerze Sprzedaży w zakładce Zamówienia dane są dokładnie takie same jak w https://allegro.pl/moje-allegro/sprzedaz/zamowienia. 

Różnice występują w zakładce Transakcje. Docelowo Zamówienia całkowicie zastąpią zakładkę Transakcje, którą planujemy wyłączyć.

**Comment by marcinja2** [comment]
No to delikatnie mówiąc nieładnie z Waszej strony, że zapewniacie przewagę Waszemu managerowi. Ale to nie forum prawne, nie będę tego roztrząsał. W takim razie składam sugestię by chodziarz numer telefonu z danych do wysyłki był podawany, bo często jest także jeżeli wpłata nie jest ukończona , również często bez świadomości klienta nieukończona to gdy dzwonimy aby o tym poinformować pod numer z danych konta okazuje sie że sam właściciel jest albo zaskoczony sytuacją że np żona z jego konta coś kupowała albo wie ze coś było kupowane ale kompletnie nie ma pojęcia o szczegółach a przecież np. syn podawał numer telefonu a my go nie widzimy. Tłumaczenie ze jeszcze moze sie zmienić nie ma sensu bo bo przecież paczkomat który podajecie też jeszcze może sie zmienic

**Comment by AureliuszBrussy** [comment]
Dziękuję, że szczegółowo opisałeś potrzebę. Sugestię przekażę do odpowiedniego zespołu. Jeżeli zdecydujemy się na tę zmianę, opublikujemy odpowiedni komunikat.

**Comment by Radeq** [comment]
> Różnice występują w zakładce Transakcje. Docelowo Zamówienia całkowicie zastąpią zakładkę Transakcje, którą planujemy wyłączyć.

@AureliuszBrussy , dokładnie chodzi mi o tą zakładkę. Czy wiadomo już kiedy to ma nastąpić?

**Comment by AureliuszBrussy** [comment]
Aktualnie ostateczna data wyłączenia zakładki Transakcje nie jest jeszcze znana - będziemy komunikować wszelkie zmiany.
