### ISSUE TITLE
Litsta paczkomatów

### ISSUE THREAD

**Issue by fortelll** [allegro/allegro-api#3519]
W jaki sposób można pobrać listę dostępnych paczkomatów dla Waszej metody dostawy "Allegro Paczkomaty 24/7 InPost"(2488f7b7-5d1c-4d65-b85c-4cbcf253fd93)?

**Comment by AureliuszBrussy** [comment]
W Allegro API nie udostępniamy zasobu, którym sprawdzisz listę dostępnych Paczkomatów. Listę Paczkomatów dostępnych w sieci InPost udostępnia [tutaj](https://inpost.pl/znajdz-paczkomat).

**Comment by Radeq** [comment]
@fortelll , Inpost ma również API - listę paczkomatów można pobrać bez weryfikacji
https://docs.inpost24.com/pages/viewpage.action?pageId=18513923

Ps: pamiętaj o określeniu typu punktu
