### ISSUE TITLE
Podanie zdefiniowanego cennika dostawy przy wystawianiu oferty

### ISSUE THREAD

**Issue by k4pit4n** [allegro/allegro-api#352]
Czy jest możliwość podania zdefiniowanego wcześniej cennika dostawy przy wystawianiu oferty za pomocą metody `doNewAuctionExt`? W dokumentacji tej metody nie znajduję odpowiedniego pola czy struktury. Metoda `doGetSellFormFieldsForCategory` zwraca natomiast całą gamę pól dla zdefiniowania poszczególnych typów przesyłek, ale również nie ma możliwości podania identyfikatora zdefiniowanego wcześniej cennika dostawy.

Możliwość wyboru zdefiniowanego wcześniej cennika dostawy istnieje przy wystawianiu oferty przez WWW, w sekcji **"Dostawa i płatność"** jest combobox z listą zdefiniowanych wcześniej cenników, pozwalający wybrać jeden z cenników. Analogicznej możliwości nie mogę doszukać się w interfejsie WebApi…

Sensownym rozwiązaniem byłoby również automatyczne wypełnianie pól dotyczących dostawy na bazie zdefiniowanego wcześniej cennika dostawy, jeśli istnieje możliwość pobrania zdefiniowanych wcześniej cenników przez WebApi. Jednak i takiej możliwości nie udało mi się znaleźć...

Czy wobec tego jedyną możliwością wystawienia ofert przez WebApi jest każdorazowe wypełnianie całej tabeli definiującej cennik dostaw?

**Comment by KrzysztofLukanowski** [comment]
Możesz wystawić ofertę ze zdefiniowanym cennikiem przez REST API, w WebAPI nie ma takiej możliwości. WebAPI będziemy stopniowo wygaszać. Rozwijamy REST, dlatego już dzisiaj zapoznaj się z [tutorialem ](https://developer.allegro.pl/sale/#rest-api)i wystaw ofertę przez REST API.

Wystawiając przez WebAPI każdorazowo musisz określić cenę dla przynajmniej jednej opcji dostawy.

**Comment by k4pit4n** [comment]
Szkoda... Przy okazji zapytam, czy przez REST API można jakoś zalogować się automatycznie, tak jak poprzez WebApi?

**Comment by KrzysztofLukanowski** [comment]
Pierwsze logowanie w aplikacji wymaga od użytkownika zgody, aby ta miała możliwość wykonywania operacji na Allegro w jego imieniu, potem aplikacja może wykorzystywać refresh token. Zapoznaj się z [artykułem](https://developer.allegro.pl/auth/).

**Comment by piotrkomisarski** [comment]
Piszę taką aplikację do integracji z allegro i przecież ta obsługa autoryzacji jest bez sensu.
Albo ja czegoś nie rozumiem. System ma automatycznie synchronizować aukcje o północy i mam teraz budzić użytkownika żeby coś kliknął ? Albo ja czegoś nie rozumiem.

Super, że jest operacja refresh token, ale jak będzie jakiś maintenance przez godzinę i aplikacja nie będzie wtedy działać to znaczy że koniec ? 

Integrowałem się z dziesiątkami różnych systemów ale czegos takiego to prawdę mówiać nie widziałem....  No chyba że czegoś nie rozumiem

**Comment by KrzysztofLukanowski** [comment]
@piotrkomisarski Napisałem, że pierwsze logowanie wymaga zgody usera. Wówczas wydawana jest para access_token i refresh_token. Jeżeli access_token wygasnie po tych 12h, to każde zapytanie skończy się odpowiedzia 401 Unauthorized. Skorzystaj wtedy z refresh_tokena i automatycznie pobierz nową parę access_token i refresh_token. Nie ma potrzeby odświeżania tego dokładnie co 12h. 

Zawsze jest wydawany nowy refresh_token, ale obecnie jego długość życia nie jest przedłużana i trwa rok. Po tym czasie tracimy możliwość pobierania nowych access_tokenow w tle i użytkownik musi się przelogować.

Możesz również podejść w inny sposób, aby uniknąć odpowiedzi 401. Przed każdym zapytaniem mozna zajrzeć do access_token (dekoder JWT) i sprawdzić kiedy wygasa. Nowy access_token możesz pobrac przy pomocy refresh_tokena w dowolnym momencie, przed wygaśnięciem albo po wygaśnięciu.
