### ISSUE TITLE
Problem z aktualizacją oferty

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#3520]
Witam, od pewnego czasu nie mogę zaktualizować oferty;
1) Pobieram ofertę przy użyciu GET sale/offers/id
2) aktualizuję wyłącznie handlingTime z wartości "PT144H" na "PT168H"
3) próbuję zaktualizować ofertę przy użyciu PUT sale/offers/id
4) dostaję błąd: "Invalid delivery or location part."

Proszę o pomoc. Poniżej request:

{
  "id": "8683860143",
  "name": "Pokrowiec na sof\u0119 Ektorp 2 os IKEA oliwkowy velvet",
  "category": {
    "id": "300777"
  },
  "product": null,
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "235717",
      "valuesIds": [
        "235717_391305"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "225693",
      "valuesIds": [],
      "values": [
        "5902117386686"
      ],
      "rangeValue": null
    }
  ],
  "customParameters": null,
  "ean": "5902117386686",
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>Pokrowiec na sof\u0119 Ektorp 2-osobow\u0105, rozk\u0142adan\u0105, model do 2012, 195 x 90 x 73 cm, oliwkowy zielony, kolekcja Velvet<\/h1>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/11f39c\/90d3b21346c8af9b28e2adedc35b"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Kod produktu: <\/b>634-704-27<\/p><p><b>Kolekcja: <\/b>Velvet<\/p><p><b>Tkanina: <\/b>oliwkowy zielony<\/p><p><b>Sk\u0142ad tkaniny: <\/b>100% poliester<\/p><p><b>Gramatura: <\/b>290 g\/m2<\/p><p><b>Zaciemnienie: <\/b>Du\u017ce<\/p><p><b>Cecha tkaniny: <\/b>jednostronna<\/p>"
          },
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/11b58f\/f8a2faed4649809959bf0fd466fb"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Pokrowiec idealnie pasuj\u0105cy na sof\u0119 IKEA Ektorp 2-osobow\u0105, model rozk\u0142adany, sprzedawany do 2012 roku. <\/p> <p><b>Pokrowiec sk\u0142ada si\u0119 z:<\/b> 1 x pokrowiec na ram\u0119 sofy, 2 x pokrowce na poduszki- siedziska, 2 x pokrowce na poduszki- oparcia. Pokrowce na poduszki na siedziska i oparcie wyposa\u017cone s\u0105 w zamki b\u0142yskawiczne.<\/p> <p>Pokrowiec wykonany z solidnej tkaniny, jest \u0142atwy do za\u0142o\u017cenia i \u015bci\u0105gni\u0119cia.<\/p> <p> Zach\u0119camy do zam\u00f3wienia bezp\u0142atnych pr\u00f3bek tkanin, aby najlepiej dopasowa\u0107 kolor pokrowca i struktur\u0119 tkaniny do Twojego wn\u0119trza.<\/p> <p>Ka\u017cdy pokrowiec jest szyty przez nas dla Ciebie w Polsce i wysy\u0142any w ci\u0105gu 4 dni.<\/p> <p><b>Wymiary:<\/b> szer. 195cm, g\u0142. 90cm, wys. 73cm.\u00a0 <\/p> <p>Informujemy, \u017ce zgodnie z Ustaw\u0105 PWP art.156 pkt.1 ust. 3, nazwy producent\u00f3w i znaki towarowe s\u0105 ich prawn\u0105 i zastrze\u017cona w\u0142asno\u015bci\u0105. W naszym internetowym sklepie u\u017cyte s\u0105 jedynie w celach informacyjnych - do jakiego producenta sofy i modelu pokrowiec jest przeznaczony. Nie sugerujemy, \u017ce jest to produkt oryginalny producenta sof.<\/p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/114fe8\/b3f0675c4fe1b65afd3a80d165cd"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/119e62\/e269baad42c19d4fb68a00fe9109"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/1177c0\/eeb55efa48a8a7365c6ea90c5acc"
          }
        ]
      },
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Kolekcja Velvet to luksusowe, pe\u0142ne elegancji tkaniny <\/b>przypominaj\u0105ce aksamit. <b>Mi\u0119kkie i przyjemne w dotyku<\/b> - nadaj\u0105 wn\u0119trzom niepowtarzalne, szykowne oblicze. Mi\u0119sisto\u015b\u0107 materia\u0142u oraz wyj\u0105tkowe kolory, to cechy charakterystyczne dla tej kolekcji. Nale\u017cy pami\u0119ta\u0107, \u017ce kolory mog\u0105 wydawa\u0107 si\u0119 ja\u015bniejsze lub ciemniejsze w zale\u017cno\u015bci od kierunku \u017ar\u00f3d\u0142a \u015bwiat\u0142a.Tkaniny Velvet sprawdz\u0105 si\u0119 zar\u00f3wno w klasycznej, jak i nowoczesnej stylistyce. Doskonale zaprezentuj\u0105 si\u0119 w sypialni lub salonie, gdzie pomog\u0105 Ci stworzy\u0107 ekskluzywn\u0105 stref\u0119 odpoczynku. <b>Pozw\u00f3l sobie zatopi\u0107 si\u0119 w wykwintnym \u015bwiecie Velvetu! To absolutny must have 2019 roku.<\/b><b><\/b><\/p>"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tecdocSpecification": null,
  "images": [
    {
      "url": "https:\/\/a.allegroimg.com\/original\/11f39c\/90d3b21346c8af9b28e2adedc35b"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/11b58f\/f8a2faed4649809959bf0fd466fb"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/114fe8\/b3f0675c4fe1b65afd3a80d165cd"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/119e62\/e269baad42c19d4fb68a00fe9109"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/1177c0\/eeb55efa48a8a7365c6ea90c5acc"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "939",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "tax": null,
  "stock": {
    "available": 50,
    "unit": "UNIT"
  },
  "publication": {
    "duration": null,
    "status": "ACTIVE",
    "startingAt": null,
    "endingAt": null,
    "endedBy": null,
    "republish": false
  },
  "delivery": {
    "shippingRates": {
      "id": "c8efe08b-5f6f-4750-a2c4-07216073cd18"
    },
    "handlingTime": "PT168H",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "VAT"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "bc886de2-a1bf-4f36-b748-43dccb36614c"
    },
    "returnPolicy": {
      "id": "a01edae3-fe52-49e2-b468-7fa00c622acd"
    },
    "warranty": {
      "id": "a981f7d1-f0f5-4d62-8b53-cf4b0e179717"
    }
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "DOLNOSLASKIE",
    "city": "\u017bar\u00f3w",
    "postCode": "58-130"
  },
  "external": {
    "id": "634-704-27"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [],
    "warnings": [],
    "validatedAt": "2020-08-10T06:57:53.251Z"
  },
  "createdAt": "2019-11-14T09:57:47.000Z",
  "updatedAt": "2020-08-10T06:57:53.591Z"
}

**Comment by AureliuszBrussy** [comment]
Widzę, że próbujesz zmienić “handlingTime” z "PT168H" na "PT144H" - odwrotnie, niż napisałeś w zgłoszeniu. Wartość "PT144H” (6 dni) nie jest dostępna.

**Comment by adamTynski** [comment]
Dziękuję, dostępne wartości znalazłem w edycji oferty. A czy jest możliwe, by uwzględnić tą informację w dokumentacji?

**Comment by AureliuszBrussy** [comment]
Wszystkie dostępne wartości wypisujemy w [tym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty) w przykładowym requescie. Przekazałem sugestię dotyczącą uzupełnienia informacji w dokumentacji do odpowiedniego zespołu.

**Comment by adamTynski** [comment]
Dziękuję, pozdrawiam

**Comment by AureliuszBrussy** [comment]
@adamTynski dokumentacja została uzupełniona o dostępne wartości.
