### ISSUE TITLE
Jeden kupujacy, 2 zamówienia vs numer wysyłki

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3521]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

witam mam problem, kupujący zakupił u mnie 2 różne zestawy książek i wypełnił 2 różne opcje dostawy dla dwóch różnych zamówień. Korzystam z autorskiego programu do obsługi przesyłek i w przypadku gdy nadałem pierwszą przesyłkę i uzupełniłem jej numer używając Allegro REST Api dla zamówienia: 584c92d3-d5bd-11ea-a917-c52f8b6d3d0f to nieoczekiwanie ten sam numer przesyłki w tym samym czasie został tez uzupełniony także w drugim zamówieniu: 32160d74-d5be-11ea-a917-c52f8b6d3d0f Sprawdziłem czy błąd nie leży po mojej stronie i wszystko na to wskazuje, że u mnie jest ok. Proszę o zweryfikowanie tej sytuacji.

**Comment by AureliuszBrussy** [comment]
Numer przesyłki został dodany do zamówienia 32160d74-d5be-11ea-a917-c52f8b6d3d0f, ponieważ nadałeś przesyłkę przez narzędzie nadawcze przewoźnika, korzystając z adresu e-mail przypisanego do tego właśnie zamówienia. Przewoźnik automatycznie przekazał nam numer przesyłki.

**Comment by marcinja2** [comment]
ciąg dalszy: klient wyskoczył mi z pretensjami i dyskusją że będę próbował go i Was oszukać wpisując ten sam numer przesyłki w obu zamówieniach, że kombinuję z nadzieją że nikt się nie kapnie. Takie samowolne dodawanie numerów nie jest dobre

**Comment by AureliuszBrussy** [comment]
Każde zamówienie posiada przypisany unikatowy adres e-mail. To on jest podstawą do automatycznego uzupełnienia numeru przesyłki - mechanizm ten powstał, aby zautomatyzować, a co za tym idzie, ułatwić sprzedającym cały proces dodawania tego numeru.

Wystarczy, że podczas wysyłania przesyłki przekażesz w narzędziu nadawczym adres e-mail przypisany do odpowiedniego zamówienia, do którego rzeczywiście wysyłasz przesyłkę - wtedy taka sytuacja nie wystąpi.
