### ISSUE TITLE
Publish command summary

### ISSUE THREAD

**Issue by pawelcudowski** [allegro/allegro-api#3522]
Zaraz po wystawianiu aukcji dostałem zwrotkę (oczywiście później było już ok):

array(2) {
  ["id"]=>
  string(36) "7ada9b5b-caef-45f2-a208-5af7012a6f7d"
  ["taskCount"]=>
  array(3) {
    ["total"]=>
    int(1)
    ["success"]=>
    int(0)
    ["failed"]=>
    int(0)
  }
}

Po jakim czasie mogę się spodziewać jednoznacznej odpowiedzi czy wystawienie aukcji się powiodło?

**Comment by Aryak2099** [comment]
Ustaw sobie pobieranie statusu co np 5 sekund po kodzie UUID a ż do momentu jak zwróci wartość sccess albo failed , można to synchronicznie to zrobić lub asynchronicznie.

**Comment by AureliuszBrussy** [comment]
Endpoint /sale/offer-publication-commands/{commandId} działa asynchronicznie, dlatego w odpowiedzi nie otrzymujesz od razu informacji o statusie publikacji. Aby sprawdzić status - użyj GET /sale/offer-publication-commands/{commandId}/tasks. Publikacja może potrwać do 60 minut, w zdecydowanej większości przypadków odbywa się to znacznie szybciej.
