### ISSUE TITLE
Strefa okazji - dane dowolnej oferty

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3523]
W jaki sposób można pobrać informację nt. tego czy oferta jest w strefie okazji (dla dowolnej oferty w serwisie)?

**Comment by AureliuszBrussy** [comment]
W przypadku wszystkich ofert na Allegro - możesz skorzystać z GET /offers/listing i filtrować oferty z oznaczeniem "Strefa okazji". Skorzystaj z filtra campaign=BARGAIN. 
Przykładowy request: 
GET offers/listing?seller.id={Seller_ID}&campaign=BARGAIN

**Comment by 4sp3ll** [comment]
Dziękuję za odpowiedź.
Jeszcze jedno pytanie: czy response z tego endpointa zwraca w jakikolwiek sposób informację nt. tego czy oferta jest w strefie okazji (w odniesieniu do pojedynczej oferty, bez filtrowania w requeście)?

**Comment by AureliuszBrussy** [comment]
Nie, endpoint ten nie zwraca takiej informacji dla pojedynczej oferty.
