### ISSUE TITLE
Invalid_Json in https://api.allegro.pl/sale/offers/

### ISSUE THREAD

**Issue by MartinColace** [allegro/allegro-api#3524]
I send this Json by 
https://api.allegro.pl/sale/offers/xxxxxxx

------------------------------
{"id":"9560966104","name":"Plecak szkolny od SKPAT,Poliester 130001","category":{"id":"5556"},"product":"130001","parameters":[{"id":"451","valuesIds":["451_32"],"values":null,"rangeValue":null},{"id":"715","valuesIds":["715_2"],"values":[],"rangeValue":null},{"id":"3766","valuesIds":["3766_2397"],"values":[],"rangeValue":null},{"id":"7994","valuesIds":[],"values":["42"],"rangeValue":null},{"id":"7995","valuesIds":[],"values":["33"],"rangeValue":null},{"id":"7996","valuesIds":[],"values":["15"],"rangeValue":null},{"id":"15851","valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["0.63"],"rangeValue":null},{"id":"129650","valuesIds":["129650_4"],"values":[],"rangeValue":null},{"id":"201029","valuesIds":[],"values":["3"],"rangeValue":null},{"id":"203885","valuesIds":["203885_218309"],"values":[],"rangeValue":null},{"id":"203917","valuesIds":[],"values":["2"],"rangeValue":null},{"id":"203921","valuesIds":["203921_218397"],"values":[],"rangeValue":null},{"id":"203953","valuesIds":["203953_218581"],"values":[],"rangeValue":null},{"id":"215918","valuesIds":[],"values":["130001"],"rangeValue":null},{"id":"215926","valuesIds":[],"values":["SHEYENNE"],"rangeValue":null},{"id":"11323","valuesIds":["11323_1"],"values":null,"rangeValue":null},{"id":"3786","valuesIds":["3786_85"],"values":null,"rangeValue":null},null,null],"customParameters":null,"ean":"8435337032530","description":{"sections":[{"items":[{"type":"TEXT","content":"<p><b>SKPAT plecak szkolny dla dzieci firmy SKPAT</b></p><p>Ekskluzywny design</p><p>SKPAT również myśleć o najmłodszych w domu, co zbiór plecaków szkolnych i akcesoriów dla nich i nich</p><p>SKPAT jest młodym i odważnym  referencyjnym</p><p>Ten szkolny plecak oferuje lekką, wygodną, solidną i wodoodporną opcję</p><p>SKPAT plecaki na wózki są zaprojektowane z myślą o maksymalnym komforcie</p><p> Wyściełane oparcie zaprojektowane tak, aby plecy twojego malucha nie ucierpiały, Są bardzo przestronne i mają wiele przegród</p><p>Jego pomiary pozwalają dopasować laptopa i duże notebooki</p><p>DymensionsWymiary: 42x33x15 cmObjętość: 15 LWaga: 0,63 kgUchonia WynikMateriał: Drukowany poliester</p><p>Zamek błyskawiczny: Podwójny kursor</p><p> Bardzo gładkie przesuwne, Uchwyty: Górny uchwyt i 2 regulowane i wyściełane tylne paski</p><p> Maksymalny komfort, Wyściełane oparcie</p><p> Pasek z tyłu plecaka, aby dostosować się do wózka, gwarantując maksymalne wsparcie</p><p>Zawiera pęk kluczy z podpisem prezentu InteriorWewnętrzna niezbędna kieszeń i wzmocniona podstawa</p><p>Wiele przedziałów</p><p> Bardzo kompletny</p><p></p>"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/11a8ea/7a27721840d9969b94a66e778427"},{"url":"https://a.allegroimg.com/original/111000/7d67c69943ceb501c5dbef8b0073"},{"url":"https://a.allegroimg.com/original/118b0a/b399268842ad900c1104ec25a4e1"},{"url":"https://a.allegroimg.com/original/11b40e/f4b0b7304c879b0f85301d59663b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"131.94","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":null,"stock":{"available":8,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":true},"delivery":{"shippingRates":{"id":"5edc8e6c-9070-463d-867f-9c9ec007aa65"},"handlingTime":"PT120H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"NO_INVOICE"},"afterSalesServices":{"impliedWarranty":{"id":"cc09cf3e-f8a2-45c0-96c0-1f30ce2c3bb2"},"returnPolicy":{"id":"cc2d6546-d97b-4bbb-ae1c-05dc460e9531"},"warranty":{"id":"bf89a34e-8d0f-4c23-b00a-0280625d5462"}},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"ES","province":null,"city":"ATZENETA D ALBAIDA","postCode":"46869"},"external":{"id":"SKPAT"},"attachments":[],"contact":null,"validation":{"errors":[{"code":"VALIDATION_ERROR","message":"Ean field is read-only. Set this value in parameter with id: 225693.","details":"","path":"","userMessage":"Ean field is read-only. Set this value in parameter with id: 225693."}],"warnings":[],"validatedAt":"2020-08-06T18:08:25.779Z"},"createdAt":"2020-08-03T10:09:16Z","updatedAt":"2020-08-06T18:08:25.779Z"}
----------------

and response this error.
{
    "errors": [
        {
            "code": "INVALID_JSON",
            "message": "Invalid request.",
            "details": null,
            "path": null,
            "userMessage": "Invalid request."
        }
    ]
}

that could be happening?.
The Json seems correct.
some help?

**Comment by AureliuszBrussy** [comment]
If you don’t want to assign product from our database to your offer - don’t pass the value in the “product” field. If you want to use your own signature of a product - use external.id instead.

You should also provide EAN in proper way - use parameter 225693. “Ean” is a read only field.

Also your description section is invalid. You need to put your content in HTML tags. We describe the available tags [here](https://developer.allegro.pl/en/sale/#5-offer-content). Do not use newlines in a single object.
