### ISSUE TITLE
Informacja o fakturach w /order/checkout-forms

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#3527]
Czy możemy być pewni że w zasobie **"/order/checkout-forms"**  jeżeli **"invoice->required"** jest **true**   to :

 - jeżeli **"company"** jest **null**   to będzie wypełnione  **"naturalPerson"**   i odwrotnie

- jeżeli **"company"**  nie jest **null**   to **"taxId"**   zawsze będzie wypełnione

**Comment by AureliuszBrussy** [comment]
Już wyjaśniam:

- zgadza się, w przypadku “invoice”:”required” jeżeli jeżeli w pole “company” ma wartość null - zobaczysz dane w “naturalPerson” i odwrotnie - formularz zakupu pozwala na wybranie tylko jeden z tych opcji,
- formularz zakupu w przypadku wybrania faktury na firmę wymusza wprowadzenie “taxId”, dlatego też będzie on w takim przypadku zawsze wypełniony.
