### ISSUE TITLE
Numery telefonów walidacja

### ISSUE THREAD

**Issue by crazyhtm** [allegro/allegro-api#3528]
Firmy kurierskie wymagają prawidłowego 9 cyfrowego numeru telefonu. 
Na przykład API InPostu odrzuca requesty z innym numerem niż 9 cyfrowy.

Czy Allegro mogłoby wymagać podawania prawidłowych (technicznie) numerów telefonów przez klientów?

I uniemożliwić wpisywania **" ( ) ", " / ", " + ", spacji** i innych znaków poza cyframi?

**Comment by AureliuszBrussy** [comment]
Dziękuję za sugestię. Aktualnie wprowadzenie części wymienionych przez Ciebie znaków w numerze telefonu wprowadzonego przy adresie dostawy nie jest możliwe (chodzi o takie znaki jak: "()", "/", ".", ","). Znak "+" występuje w numerach telefonu, dlatego jego użycie jest możliwe. Sprawdzamy także liczbę cyfr w podanym numerze telefonu, jednakże dane importowane są przez sprzedających do różnych narzędzi nadawczych, więc nie możemy przyjąć, że jeden model jest słuszny. Liczymy, że kupujący podaje prawidłowy numer - nie mamy sposobności walidowania, czy każdy podany numer jest prawidłowy.

**Comment by Aryak2099** [comment]
Zrób sobie usuwanie spacji w programie i znaków jakimi nie jesteś zainteresowany i po sprawie.
