### ISSUE TITLE
Kiedy w odpowiedzi na GET /order/checkout-forms/{id} pole buyer.address może być nullem?

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#3529]
Dzień dobry,

Kiedy w odpowiedzi na GET /order/checkout-forms/{id} pole buyer.address może być nullem? Przykładowe zamówienie 529b8a11-dbff-11ea-bd51-1b38c615b85a

**Comment by AureliuszBrussy** [comment]
Sprawdziłem sytuację - jest to błąd. Zgłosiłem to już do odpowiedniego zespołu. Wrócę z dalszymi informacjami.

**Comment by AureliuszBrussy** [comment]
@pawelosajda dziękuję za cierpliwość. Dane w zamówieniu zostały poprawione.
