### ISSUE TITLE
Logowanie oauth nie działa

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#353]
Witam,
zgodnie z dokumentacją na stronie https://developer.allegro.pl/auth/ kieruję użytkowników na taki link:

https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=<client_id>&redirect_uri=<redirect_uri>

gdzie <client_id> oraz <redirect_uri> pochodza z utworzonej na koncie aplikacji. Po przekierowaniu pojawia sie formularz logowania na konto Allegro, wpisuje tam swoje dane logowania i w kolejnym kroku wyskakuje błąd:

error
Nie możemy wyświetlić strony
Numer błędu: 24ffaf68b07ee571

Testowałem to przekierowanie na różnych kontach Allegro, efekt zawsze taki sam. Proszę o pomoc w rozwiązaniu problemu.

**Comment by DINK74** [comment]
coś robisz nie tak - autoryzacja działa poprawnie w aplikacji, którą administruję

**Comment by KrzysztofLukanowski** [comment]
@amarel123 Czy na pewno wprowadzasz client_id oraz redirect_uri dla tej konkretnej aplikacji? Zwróć uwagę, czy na pewno wprowadzasz prawidłowe dane. Przed chwilą sprawdziłem i wszystko jest ok.

**Comment by amarel123** [comment]
@KrzysztofLukanowski Tak, client id oraz redirect uri są prawidłowe. Wysłałem pełny link przez formularz kontaktowy, nr zgłoszenia Ticket#1249095938 - proszę o sprawdzenie.

**Comment by KrzysztofLukanowski** [comment]
Weryfikujemy Twoje zgłoszenie.

**Comment by KrzysztofLukanowski** [comment]
@amarel123  podajesz błędne redirect uri. Sprawdź, jakie podałeś redirect uri podczas rejestracji aplikacji. Dokładnie to samo powinieneś wykorzystać do budowy urla.

**Comment by amarel123** [comment]
Faktycznie, jeden z naszych programistów przez przypadek dodał dodatkowy człon w adresie. Przepraszam za marnowanie czasu :)

**Comment by rtnet-pl** [comment]
@KrzysztofLukanowski Czy mogę prosić o reopen?
Chyba wczoraj przestała działać nam autentykacja. Dodam, że w ostatnim czasie nic nie zmienialiśmy.
Otrzymujemy błąd  Nie możemy wyświetlić strony
Numer błędu: 69afee4eaebbdfc6
ID i secret zgadzają się i nie były zmieniane.

http://rtnet.pl/allegro-token/index.php

**Comment by rtnet-pl** [comment]
@KrzysztofLukanowski Z tej strony wynika, że zignorujecie ten nagłówek ;) W każdym razie wykonałem zmianę, błąd dalej występuje.

**Comment by KrzysztofLukanowski** [comment]
OK, sprawdzamy gdzie tkwi problem.

**Comment by KrzysztofLukanowski** [comment]
Podajesz błędną nazwę parametru, zmień proszę redirect_url na redirect_uri.

**Comment by rtnet-pl** [comment]
@KrzysztofLukanowski Dziękuję serdecznie, pomogło.

**Comment by ukaszjankowski** [comment]
@KrzysztofLukanowski poproszę o reopen. 

Mój link: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=628082&api-key=f54fbf7934e34583abfca79aa5a0a916&redirect_uri=http%3A%2F%2Finstytut-badan.pl%2Fallegro%2Fsrc%2Foauth.php 

Numer błędu 3a9ed18a5774bf96 

Sprawdziłem porady dostępne w tym i kilku innych wątkach na githubie. Możliwe, że o kilka razy za dużo logowałem się ze złymi danymi. (Api key ze starej aplikacji).

**Comment by KrzysztofLukanowski** [comment]
Załóż proszę nowy wątek, ale z tego co widzę to najprawdopodobniej podajesz
błędny client_id. Ta wartość powinna pochodzić z kolumny o tej samej nazwie
na stronie https://apps.developer.allegro.pl/ , podobnie jak i redirect_uri.

pozdrawiam,


// Krzysztof Łukanowski

Senior Communication and Technical Support Specialist
*Zespół Wsparcia i Komunikacji w Pionie Technologii*

*Allegro*

Grunwaldzka 182 | 60-166 Poznań

Allegro sp. z o.o.  ul. Grunwaldzka 182, 60-166 Poznań,
NIP: 525-26-74-798, Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu,
VIII Wydział
Gospodarczy KRS 0000635012, kapitał zakładowy 34 000 000 złotych.


pon., 22 paź 2018 o 19:20 Łukasz Jankowski <notifications@github.com>
napisał(a):

**Comment by martasobota** [comment]
> @rtnet-pl W maju ułatwiliśmy proces autoryzacji. Nie wymagamy już nagłówka API Key. Pod tym [adresem ](https://developer.allegro.pl/news/2018-05-24-Zmiana_w_obsludze_kluczy/)znajdziesz więcej informacji na temat zmian. Dostosuj proszę swoją aplikację do wprowadzonych zmian.

Pod tym adresem jest 404, gdzie mogę uzyskać informacje o zmianach?

**Comment by PrzemyslawLukanowski** [comment]
Interesujące Cię informacje znajdziesz [tutaj](https://developer.allegro.pl/news/2018-05-24-zmiana_w_obsludze_kluczy/).
