### ISSUE TITLE
Lissting offers by Numer katalogowy części

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#3530]
Dzień dobry. Pracuję z częściami samochodowymi i moje pytanie - czy za pomocą numera katalogowego części można uzyskać listę popularnych ofert innych kupujących?

Próbowałem to zrobić w ten sposób:
` curl -X GET "https://api.allegro.pl/offers/listing?phrase=${name_prod}&215858=$code&sort=-relevance&sort=-popularity"`

**Comment by AureliuszBrussy** [comment]
Nie wszystkie parametry dostępne w ofertach w danej kategorii możesz użyć do wyszukiwania ofert z wykorzystaniem endpointu /offers/listing.  Sprawdź najpierw, np. wyszukując tylko w danej kategorii (z parametrem category.id={categoryId}), z jakich parametrów rzeczywiście możesz skorzystać do filtrowania wyników. 

Parametr przekazuj w ten sposób: parameter.{parameterID}={value}.

Dodatkowo - w pojedynczym żądaniu możesz skorzystać tylko z jednego sposobu sortowania.

**Comment by vartaller** [comment]
Próbuję wyszukiwać według producenta części, ale odpowiedź nadal zawiera szczegóły od dowolnego producenta. Co ja robię źle?

_parameter.127415 - Producent części parameter ID 
producer_id - Producent części ID_

`https://api.allegro.pl/offers/listing?phrase=${code}&searchMode=DESCRIPTIONS&parameter.127415=${producer_id}&fallback=false&sort=-popularity`

**Comment by AureliuszBrussy** [comment]
Czy mogę prosić o przykład wywołania z uzupełnionymi wartościami ${code} i ${producer_id}? Sprawdzę to na konkretnym przykładzie.

**Comment by vartaller** [comment]
> Czy mogę prosić o przykład wywołania z uzupełnionymi wartościami ${code} i ${producer_id}? Sprawdzę to na konkretnym przykładzie.

```
curl -X GET \
   "https://api.allegro.pl/offers/listing?phrase=MAHLE%20LAO373&searchMode=DESCRIPTIONS&parameter.127415=127411_339101&fallback=false&sort=-popularity" \
   -H 'Accept: application/vnd.allegro.public.v1+json' \
   -H 'content-type: application/vnd.allegro.public.v1+json' \
   -H "Authorization: Bearer $token"
```
szukam Mahle - dostaję Valeo, BOSCH, Mahle, Blue Print...

**Comment by AureliuszBrussy** [comment]
Zwróć uwagę na to, jakie w odpowiedzi otrzymujesz możliwe do wykorzystania filtry (cała struktura “filters”). W przypadku tego konkretnego żądania - nie masz możliwości filtrowania po wskazanym parametrze, więc jest on ignorowany (wszystkie nieprawidłowe parametry są ignorowane). Doprecyzuj swoje żądanie, podając np. id kategorii (np. category.id=49237), w której chcesz wyszukać ofert. Wtedy w response zobaczysz więcej możliwości filtrowania, m.in. właśnie po parametrze 127415.
