### ISSUE TITLE
Brak możliwości wystawienia nowej oferty na sandbox

### ISSUE THREAD

**Issue by DanBSixin** [allegro/allegro-api#3531]
Aby przetestować pobieranie informacji o zamówieniach z API allegro na sandbox, chciałem dodać nową ofertę, więc wchodzę na stronę: https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty, klikam na przycisk: "DODAJ NOWĄ" i dostaje komunikat, że strona jest nieosiągalna - dlaczego tak się dzieje?

**Comment by AureliuszBrussy** [comment]
Prosiłbym o podanie loginu na sandboxie - sprawdzę to.

**Comment by DanBSixin** [comment]
Login: Sixin

**Comment by AureliuszBrussy** [comment]
Potwierdzam problem z działaniem formularza wystawiania. Zgłosiłem to do odpowiedniego zespołu. Na ten moment spróbuj skorzystać z [tego linku](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie). Zostaniesz prawidłowo przekierowany do formularza wystawiania.

**Comment by DanBSixin** [comment]
OK, dziękuję za pomoc :)
