### ISSUE TITLE
[OAuth] Custom URL scheme for redirect uri

### ISSUE THREAD

**Issue by przemyslaw-szurmak** [allegro/allegro-api#3532]
Hey,

is there any way to set a custom scheme for redirect uri when registering an app?

I'm trying to use iOS's `ASWebAuthenticationSession` but it requires custom URL scheme for redirect to work. When I try to set one in Allegro Apps editor I just get info that's invalid protocol :(

<img width="305" alt="Zrzut ekranu 2020-08-13 o 19 33 11" src="https://user-images.githubusercontent.com/16134919/90167615-301c0200-dd9c-11ea-978f-6ba7dc273857.png">

**Comment by AureliuszBrussy** [comment]
Correct return address:
- must be the URI address,
- must contain an HTTP(S) protocol,
- cannot contain URI fragments,
- cannot contain relative paths,
- cannot use IP addresses.

If this method of authorization does not meet your requirements and assumptions, you can use other authorization methods - [Device Flow](https://developer.allegro.pl/en/auth/#DeviceFlow) or [DCR](https://developer.allegro.pl/en/auth/#dynamicClientRegistration).

**Comment by przemyslaw-szurmak** [comment]
@AureliuszBrussy thanks for explanation!
