### ISSUE TITLE
Dane do Paczkomatu są niepuste, kiedy pobierane jest zamówienie z przesyłką kurierską InPost Kurier24

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3533]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,

pobierając zamówienia z zasobu `order/checkout-forms` zdarza się czasami, że dane adresowe dostawy dla przesyłek kurierskich InPost zawierają wypełniony obiekt `pickupPoint`. Problem pojawia się nie za często, mam ledwo 20 zarejestrowanych przypadków w bazie danych w ciągu kilku miesięcy. Widzę, że pobrane wcześniej dane są po stronie RESTa zaktualizowane i `pickupPoint` jest zmieniany na `null` w danych zamówieniach. Nie myślałem, że może być konieczna aktualizacja danych dostawy, skoro Allegro nie udostępnia możliwości ich zmiany klientom i sprzedawcom.

Niestety nie udało mi się uchwycić błędu na gorącym uczynku. Mam jednak świeży przykład transakcji, której `pickupPoint` jest w API wartością `null` ale wcześniej pobrano wartości z wypełnionym `pickupPoint` .
ID transakcji: `a78183e1-dcd1-11ea-b259-774ded902f6b`.

To jakiś bug po stronie Allegro? Czy jakiś event z zasobu `order/events` rejestruje konkretnie tą zmianę w danych dostawy? Jeśli tak, to pod jakim typem eventu zostanie odnotowana ta zmiana?

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Dane w zamówieniach mogą się zmieniać do momentu wystąpienia w zamówieniu eventu READY_FOR_PROCESSING. Dopiero po tym statusie zamówienie jest gotowe do realizacji - masz wtedy pewność, że w zamówieniu nie nastąpią żadne zmiany. 

Sprawdziłem wskazane przez Ciebie zamówienie. Faktycznie, gdy zamówienie posiadało inne statusy niż READY_FOR_PROCESSING, metoda dostawy wybrana przez Klienta była inna, niż ostatecznie po wystąpieniu eventu READY_FOR_PROCESSING, stąd pojawił się wcześniej adres w sekcji “pickupPoint”. Nie jest to błąd.

**Comment by hahyes** [comment]
> Dane w zamówieniach mogą się zmieniać do momentu wystąpienia w zamówieniu eventu READY_FOR_PROCESSING. Dopiero po tym statusie zamówienie jest gotowe do realizacji - masz wtedy pewność, że w zamówieniu nie nastąpią żadne zmiany.
> 
> Sprawdziłem wskazane przez Ciebie zamówienie. Faktycznie, gdy zamówienie posiadało inne statusy niż READY_FOR_PROCESSING, metoda dostawy wybrana przez Klienta była inna, niż ostatecznie po wystąpieniu eventu READY_FOR_PROCESSING, stąd pojawił się wcześniej adres w sekcji “pickupPoint”. Nie jest to błąd.

Dziękuję za odpowiedź, rozjaśniła moje wątpliwości. Pozdrawiam.
