### ISSUE TITLE
Problem z pobraniem produktu

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3534]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, mamy problem na środowisku produkcyjnym, nie możemy pobrać jednego z produktów o identyfikatorze a8df7385-fadc-4263-bdf9-ef8a5f8d0139, dostajemy błąd  InternalServerError

Korzystamy z adresu /sale/products/a8df7385-fadc-4263-bdf9-ef8a5f8d0139
TraceId 6023f2ec9e7b63e6

**Comment by AureliuszBrussy** [comment]
Potwierdzam występujący problem. Zgłosiłem to do odpowiedniego zespołu. Wrócę z dalszymi informacjami.

**Comment by AureliuszBrussy** [comment]
Potwierdzam występujący problem. Zgłosiłem to już do odpowiedniego zespołu. Wrócę z dalszymi informacjami.

**Comment by AureliuszBrussy** [comment]
@lukaszzborek problem został już rozwiązany, możesz już pobrać dane tego produktu.
