### ISSUE TITLE
Sandbox Allegro Zapłać Później PayPo

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3536]
Dzień dobry, czy istnieje możliwość przetestowania zamówień z płatnością allegro zapłać później w serwisie testowym allegro.pl.allegrosandbox.pl bez konieczności przekazywania prawdziwych danych z numerem PESEL (formularz "Zacznij korzystać z Allegro Zapłać Później") do serwisu PayPo?

Czy jest planowane udostępnienie testowej płatności allegro zapłać później (PayPo), jak w przypadku innych płatności?

**Comment by MaciejFrackowiak** [comment]
Warunkiem pomyślnego przejścia aktywacji Allegro Zapłać Później na Sandbox jest unikalność adresu email, nr telefonu oraz nr PESEL - nie ma możliwości "obejścia" któregokolwiek z tych wymogów. Ponadto opcja nie będzie dostępna, gdy są spełnione warunki opisane w [Pomocy Allegro](https://allegro.pl/pomoc/dla-kupujacych/allegro-zaplac-pozniej/kiedy-nie-skorzystam-z-allegro-zaplac-pozniej-KMLKy6AdYc6).

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak a co z drugim pytaniem? W przypadku innych płatności jest sandbox, w przypadku tej także powinien być. Zatem pytanie kiedy będzie sandbox dla PayPo

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Jeżeli jako kupujący spełnisz warunki udostępnienia płatności Allegro Zapłać Później to możesz skorzystać z tej opcji. Nie ma alternatywnej opcji.

**Comment by SebastianOzdoba** [comment]
@MaciejFrackowiak  jako kupujący spełniam warunki, pytałem o to czy będzie serwis testowy w którym zasymulujemy sobie odpowiedź pozytywną lub negatywną i będziemy mogli podać np pesel z generatora. Podawanie prawdziwych danych na serwisie testowym w szczególności peselu uważamy za dosyć poważną lukę, ja nie wiem co dalej z tym peselem się podzieje.

**Comment by MaciejFrackowiak** [comment]
@SebastianOzdoba Nie, takie rozwiązanie w przypadku AZP nie jest dostępne. Możesz podać losowo wygenerowany PESEL.

**Comment by SebastianOzdoba** [comment]
Dzięki

**Comment by alekskuc** [comment]
> @SebastianOzdoba Nie, takie rozwiązanie w przypadku AZP nie jest dostępne. Możesz podać losowo wygenerowany PESEL.

Dzień dobry, dla losowo wygenerowanego nr pesel opcja zapłać później jest niedostępna. Nie jest aktywna pomimo spełnienia wszystkich możliwych warunków poza prawdziwością danych przekazywanych do PayPo.

![s](https://user-images.githubusercontent.com/8465007/90777408-ac15cd00-e2fb-11ea-8979-50b6727eb22b.png)

Dla tej samej aukcji dla innego konta sandbox z prawdziwym nr pesel opcja jest dostępna.

![ss](https://user-images.githubusercontent.com/8465007/90777942-52fa6900-e2fc-11ea-88bf-5ef9a7ff9ca8.jpg)

Czy jest możliwość ręcznej aktywacji tej płatności przez państwa na koncie ComarchSandbox5?

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Funkcjonalność powinna już być dostępna dla konta ComarchSandbox5, limit wynosi 200zł.
