### ISSUE TITLE
Permanentny błąd 504 przy zapytanie PUT (madyfikacja stawki VAT)

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#3537]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Zgodnie  z zaleceniem zawartym w poście 
[NEWS] Grupowa edycja stawki podatku VAT w ofertach / Batch offer modification - change VAT rate #3429

 chciałem uzupełnić stawki VAT
 i niestety od piątku cały czas mam błąd 504 i nic się nie zapisuje 
np.
-PUT

https://api.allegro.pl/sale/offer-modification-commands/f2ef21ee-6a4d-4596-9ced-7011295e5255

aPostFields string(237) "{"modification":{“payments":{"invoice":"VAT","tax":{"percentage":"23"}},},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[ {'id':'9593798853'}, {'id':'9593786803'}, {'id':'9593786727'}, {'id':'9593786572'}, {'id':'9593786470'}]}]}"
 i po urlencode
str string(483) "%22%7B%5C%22modification%5C%22%3A%7B%5Cu201cpayments%5C%22%3A%7B%5C%22invoice%5C%22%3A%5C%22VAT%5C%22%2C%5C%22tax%5C%22%3A%7B%5C%22percentage%5C%22%3A%5C%2223%5C%22%7D%7D%2C%7D%2C%5C%22offerCriteria%5C%22%3A%5B%7B%5C%22type%5C%22%3A%5C%22CONTAINS_OFFERS%5C%22%2C%5C%22offers%5C%22%3A%5B+%7B%27id%27%3A%279593798853%27%7D%2C+%7B%27id%27%3A%279593786803%27%7D%2C+%7B%27id%27%3A%279593786727%27%7D%2C+%7B%27id%27%3A%279593786572%27%7D%2C+%7B%27id%27%3A%279593786470%27%7D%5D%7D%5D%7D%22"

gdy następnie robię
 -GET
https://api.allegro.pl/sale/offer-modification-commands/f2ef21ee-6a4d-4596-9ced-7011295e5255
otrzymuje błąd 404

**Comment by MaciejFrackowiak** [comment]
Otrzymujesz 404 przy GET, ponieważ nie mamy w logach Twojego PUTa z komendą zmiany stawki VAT. Twój request powinien wyglądać tak:

```
{
    "modification": {
    "payments": {
      "invoice": "VAT",                             
      "tax": {                                     
         "percentage": "23.00"               
      }                                             
    }
   },
    "offerCriteria":[
      {
        "type":"CONTAINS_OFFERS",
        "offers":[
         {
        "  id":"7531636067"
         },
         {
          "id":"7512439587"
         }
       ]
     }
    ]
 }
```

Spróbuj dokonać testowo zmiany dla jednej oferty.

**Comment by Zbigi** [comment]
https://api.allegro.pl/sale/offer-modification-commands/f4d86813-775f-4c04-b569-b5f322de5a42
curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "authorization: $token_type $token",
                 "accept: $accept",
                "content-type: $accept",
                "X-HTTP-Method-Override: PUT"
                ]);
i otrzymuje
 $wyn= object(stdClass)#325 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#324 (5) {
      ["code"]=>
      string(19) "NotAllowedException"
      ["message"]=>
      string(30) "The HTTP method is not allowed"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(17) "An error occurred"
    }
  }
}

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam swój request w formacie cURL. Możesz także skorzystać z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), aby przekazać pełny request i response.

**Comment by Zbigi** [comment]
Nie mam możliwości podejrzenia requestu, ponieważ robię to ze zdalnego serwera. mogę tylko header output podejrzeć

responseUUID= string(36) "4309a84b-90d9-4511-8200-ca7477e9f698"

url= string(92) "https://api.allegro.pl/sale/offer-modification-commands/4309a84b-90d9-4511-8200-ca7477e9f698"

$heder= string(1452) "PUT /sale/offer-modification-commands/4309a84b-90d9-4511-8200-ca7477e9f698 HTTP/1.1
Host: api.allegro.pl
authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTc2OTYzNTUsInVzZXJfbmFtZSI6IjYxNTI4MjY4IiwianRpIjoiMTVlMjZjMzgtZDhlMC00OGFjLThkZTMtYTM3ZjllNDllMWYwIiwiY2xpZW50X2lkIjoiNWZjMjAxODc1ZDAxNDUxYWJjYTM4YzIwYzZhYWIzODUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.YRTWNnlNd-rpVBLPmvu2OFf0KOjNBjxOO7imO3fKx2_Xbwb2HHsdgfb0RdhYtLuJR4zbzUI83m-AoeJ0TE_bsHCxp6nQ2C8Rb9OB2HarEtEjtLbrLkqmkL4duWlCJ2Ixmnuxrx5xPwItp1Jv6NvdFp4-wF5TO011qnSz0D28iF__g_08MewNTqivxTxnD6p3TwA_Ww8jt9A1__pA18MZR3H3rinBFuYe-0ZYJyr4wZ-xsJFA5Red0Is-Dz_OW-lT1-PJ6sCwZ3FjX5DnZPb1a8xZ19SC757MnnYhGrVhYqYXEuT1HF-HLG_98I7sazoMkDzsYMgV4bRT5-HeOLO6TA
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json
Content-Length: 153
X-HTTP-Method-Override: PUT

"

resultCode= int(400)

response= string(177) "{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-modification-commands/4309a84b-90d9-4511-8200-ca7477e9f698","userMessage":null}]}"


 $wyn= object(stdClass)#324 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#325 (5) {
      ["code"]=>
      string(5) "ERROR"
      ["message"]=>
      string(21) "An error has occurred"
      ["details"]=>
      NULL
      ["path"]=>
      string(70) "/sale/offer-modification-commands/4309a84b-90d9-4511-8200-ca7477e9f698"
      ["userMessage"]=>
      NULL
    }
  }
}

**Comment by MaciejFrackowiak** [comment]
Tu widzimy błąd 400, czyli Twój request nie był prawidłowy - oznacza to, że nie dociera on nawet do nas. Jeżeli wyślesz request zgodnie z moim przykładem, wówczas błąd 400 nie pojawi się.

**Comment by Zbigi** [comment]
podgląd requestu
https://requestinspector.com/inspect/01eh4w532wze8v527cae2zw4gm

a odpowiedz 

error= NULL

 $wyn= object(stdClass)#324 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#325 (5) {
      ["code"]=>
      string(5) "ERROR"
      ["message"]=>
      string(21) "An error has occurred"
      ["details"]=>
      NULL
      ["path"]=>
      string(70) "/sale/offer-modification-commands/961781f3-c19f-42e3-9858-3eb90d5af78b"
      ["userMessage"]=>
      NULL
    }
  }
}
 numery commands się nie zgadzają, ponieważ to są różne zapytania a numer uuid  jest generowany przy każdym zapytaniu

**Comment by MaciejFrackowiak** [comment]
Proszę zajrzyj do posta https://github.com/allegro/allegro-api/issues/3429 - odpowiedziałem tam już na Twoje wątpliwości.

**Comment by Zbigi** [comment]
Witam w tej chwili niby wszystka działa ale: po zapytaniu put
{"modification":{"payments":{"invoice":"VAT","tax":{"percentage":"23.00"}}},"offerCriteria":[{"offers":[ {"id":"9213779504"}, {"id":"9213779078"}, {"id":"9213778948"}, {"id":"9213778812"}, {"id":"9213778706"}, {"id":"9213778582"}, {"id":"9213778493"}, {"id":"9213778418"}, {"id":"9213778318"}, {"id":"9213778247"}, {"id":"9213778165"}, {"id":"9213777993"}, {"id":"9213777724"}, {"id":"9213777527"}, {"id":"9213777279"}, {"id":"9213777212"}, {"id":"9213777088"}, {"id":"9213776817"}, {"id":"9213776719"}, {"id":"9213776622"}, {"id":"9213776549"}, {"id":"9213776299"}, {"id":"9213776193"}, {"id":"9213775955"}, {"id":"9213775626"}, {"id":"9213775308"}, {"id":"9213775090"}, {"id":"9213774636"}, {"id":"9213774438"}, {"id":"9213774310"}],"type":"CONTAINS_OFFERS"}]}"

 zwracają mi takie odpowiedzi
int(201) string(92) "{"id":"986d93cb-66cc-4ad2-9b4b-af2d9fd2d75e","taskCount":{"total":0,"success":0,"failed":0}}" 
 a gdy zadaje pytanie
"https://api.allegro.pl/sale/offer-modification-commands/986d93cb-66cc-4ad2-9b4b-af2d9fd2d75e/tasks" 
otrzymuje

int(200) string(1361) "{"tasks":[{"offer":{"id":"9213775090"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.853Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213776817"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.861Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213776719"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.869Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213775308"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.878Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213776622"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.886Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213778948"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.894Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213778706"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.903Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213776549"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.911Z","finishedAt":null,"field":"payments","errors":[]},{"offer":{"id":"9213775955"},"message":null,"status":"NEW","scheduledAt":"2020-09-10T12:44:23.919Z","finishedAt":null,"field":"payments","errors":[]}]}" object(stdClass)#741 (1) { ["tasks"]=> array(9) { [0]=> object(stdClass)#757 (7) { ["offer"]=> object(stdClass)#759 (1) { ["id"]=> string(10) "9213775090" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.853Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [1]=> object(stdClass)#756 (7) { ["offer"]=> object(stdClass)#758 (1) { ["id"]=> string(10) "9213776817" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.861Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [2]=> object(stdClass)#754 (7) { ["offer"]=> object(stdClass)#755 (1) { ["id"]=> string(10) "9213776719" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.869Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [3]=> object(stdClass)#752 (7) { ["offer"]=> object(stdClass)#753 (1) { ["id"]=> string(10) "9213775308" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.878Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [4]=> object(stdClass)#751 (7) { ["offer"]=> object(stdClass)#749 (1) { ["id"]=> string(10) "9213776622" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.886Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [5]=> object(stdClass)#748 (7) { ["offer"]=> object(stdClass)#750 (1) { ["id"]=> string(10) "9213778948" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.894Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [6]=> object(stdClass)#670 (7) { ["offer"]=> object(stdClass)#747 (1) { ["id"]=> string(10) "9213778706" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.903Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [7]=> object(stdClass)#744 (7) { ["offer"]=> object(stdClass)#623 (1) { ["id"]=> string(10) "9213776549" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.911Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } [8]=> object(stdClass)#743 (7) { ["offer"]=> object(stdClass)#742 (1) { ["id"]=> string(10) "9213775955" } ["message"]=> NULL ["status"]=> string(3) "NEW" ["scheduledAt"]=> string(24) "2020-09-10T12:44:23.919Z" ["finishedAt"]=> NULL ["field"]=> string(8) "payments" ["errors"]=> array(0) { } } } } 

pytanie jest czy wartość jest zmieniona, czy nie. Wygląda na to że, bo gdy jeszcze raz próbuj zrobić i sprawdzam
czy tax==NULL dostaje odpowiedzi True czyli tak ma wartość NULL.
Wygląda na to, że błędów nie ma, ale też nic nie zmienił

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem status zmian dla ofert wymienionych w Twoim requeście korzystając z GET sale/offer-modification-commands/986d93cb-66cc-4ad2-9b4b-af2d9fd2d75e/tasks - praktycznie wszystkie (bez jednej - 9213777724) mają status SUCCESS, co oznacza, że zmiany zostały dokonane. Łatwo to sprawdzić korzystając z GET /sale/offers/{offerId} dla każdej z ofert - wyrywkowo sprawdziłem kilka i każda z nich miała ustawioną stawkę podatku VAT na 23%:
```
"tax": {
        "percentage": "23.00"
    },
```
Co do 9213777724 - mimo informacji o problemie, stawka VAT też jest ustawiona.

**Comment by Zbigi** [comment]
To dlaczego zwraca mi TaskCount":{"total":0,"success":0,"failed":0}}" ?

**Comment by MaciejFrackowiak** [comment]
Te polecenia wykonują się asynchronicznie - jeżeli zlecasz X zmian naraz, to mechanizm wykona je zgodnie z kolejnością, która obowiązuje dla wszystkich zmian w serwisie. Niemożliwe jest, aby po przykładowo 2 sekundach wszystkie zadania zostały wykonane i ich status od razu pojawił się w postaci odpowiednich wartości dla total, success, failed.
Dlatego, aby pobrać dane najlepiej odczekać chwilę (zdecydowanie więcej niż kilka sekund) lub skorzystać z GET /sale/offer-modification-commands/{commandId}/tasks by poznać szczegółowe statystyki względem każdej modyfikowanej oferty.

**Comment by Zbigi** [comment]
ok, dziękuję
Zrobię za pytanie po kilku minutach
