### ISSUE TITLE
masowa publikacja ofert z ENDED -> ACTIVE

### ISSUE THREAD

**Issue by AdrianPiwnicki** [allegro/allegro-api#3538]
Witam,
Mam problem z masową publikacją z powrotem z statusu ENDED -> ACTIVE.
Gdy wykonuje zapytanie PUT to czasem aktywuje połowe, czasem wszystkie a czasem wcale.
Czy można ten problem jakoś rozwiązać?

**Comment by MaciejFrackowiak** [comment]
Czy sprawdzałeś status wykonywanej przez siebie operacji przy użyciu [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET)? Otrzymasz w ten sposób szczegółowy raport dot. zleconej zmiany.

**Comment by AdrianPiwnicki** [comment]
tak, czasem jest fail a czasem success
![image](https://user-images.githubusercontent.com/56109682/90397120-a8820c00-e097-11ea-8dc8-951d83ea70c8.png)
Czy masowa publikacja ponowna jest możliwa? Bo masowe zakończenie działa bez zarzutów a w drugą stronę już nie koniecznie.

**Comment by MaciejFrackowiak** [comment]
Oferta, której id wskazałeś na screenie - 7087406754 została zakończona w 2017 roku, czy to właściwy numer?

**Comment by AdrianPiwnicki** [comment]
Pracuję aktualnie w allegro sandbox

**Comment by AdrianPiwnicki** [comment]
według tej dokumentacji: https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT
jest możliwość publikowania i zakończenia wielu ofert w jednym czasie.

**Comment by MaciejFrackowiak** [comment]
Wykonujesz zbyt dużo jednoczesnych prób zmian naraz - mechanizm nie zdąży przeprocesować jednej zmiany, a już ma zleconą kolejną dot. tej samej oferty. Przykładowo - oferta trwa, zlecasz zakończenie jej, i po chwili jej aktywację - pierwsza operacja jeszcze się nie wykonała, a już druga ma ją wznowić - tylko trwającej oferty nie można już wznowić, zatem jej status nie da się zmienić. Ogranicz liczbę jednoczesnych operacji, wówczas taki problem nie będzie występować.

**Comment by AdrianPiwnicki** [comment]
rozumiem, dziękuje za odpowiedź

**Comment by AdrianPiwnicki** [comment]
Nie do końca się z tym zgodzę, wystawiłem przed chwilą 3 oferty które nie były ruszane od około godziny i dalej jednej nie wystawił

**Comment by MaciejFrackowiak** [comment]
Mechanizm ma do 60 minut na wykonanie operacji - zdecydowana większość czynności odbywa się szybciej, jednak jest to przedział, który stanowi górną granicę.
