### ISSUE TITLE
Zbyt inwazyjna walidacja oferty

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3539]
Podczas edycji oferty (POST sale/offers/xxx) otrzymujemy:

[code] => VALIDATION_ERROR
   [message] => Usuń z opisu przedmiotu dane o warunkach gwarancji i umieść je w zakładce: Moja sprzedaż > Ustawienia Sprzedaży > Informacje o gwarancjach. Dla różnych grup produktów możesz utworzyć osobne gwarancje. Jeżeli w przyszłości zechcesz zmienić warunki wybranej gwarancji, zmiany zapiszą się automatycznie we wszystkich ofertach, w których ta gwarancja została użyta.
   [details] =>
   [path] =>
   [userMessage] => Usuń z opisu przedmiotu dane o warunkach gwarancji i umieść je w zakładce: Moja sprzedaż > Ustawienia Sprzedaży > Informacje o gwarancjach. Dla różnych grup produktów możesz utworzyć osobne gwarancje. Jeżeli w przyszłości zechcesz zmienić warunki wybranej gwarancji, zmiany zapiszą się automatycznie we wszystkich ofertach, w których ta gwarancja została użyta.

W treści oferty zostały użyte zwroty:
[...] **Gwarantuje** to najwyższą pewność użytkowania, bezpieczeństwo i niezawodność. Poprawny montaż częśći [...] nie narusza **gwarancji** producenta samochodu. [...] poddawany intensywnym testom **gwarantującym** spełnienie wymagań i standardów OE.

Czy powyższe nie powinno być jako warnings i nie blokować oferty?
Nie mówiąc już o nie prawidłowym działaniu filtrów, które w tym przypadku całkiem się nie spisały.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spostrzeżenie. Problem skonsultowaliśmy z działem odpowiedzialnym za jakość opisów ofert - od teraz informacja o gwarancji zostanie uwzględniona w polu "warnings".

**Comment by dlis2010** [comment]
Świetna informacja, dziękuję ;)
