### ISSUE TITLE
ACTIVATE czyli wznawianie ofert w sale/offer-publication-commands/

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#354]
Błagam, niech mi ktoś powie, czy ja odchodzę od zmysłów, czy to nie działa. Załączam poniżej w największym uproszczeniu pocięty plik PHP przerobiony  z edycji ceny, co świetnie w podobnej postaci działa. Dlaczego aktywacja oferty zwraca "An error has occurred" ? Niech się ktoś zlituje i podstawi w to miejsce swój klucz i powie co jest tu źle ? 

```
function commandRequest($uri, $generatedKey, $params)
    {
    $headers = array(
        'accept: application/vnd.allegro.beta.v1+json',
        'content-type: application/vnd.allegro.beta.v1+json',
        'Authorization: Bearer '.$generatedKey.'');
    $curl =    curl_init($uri);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'PUT');
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $data = json_encode($params);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);   
	return curl_exec($curl);
    }

    $generatedKey   = 'mój_token';
	$guId = 'b1441984-28f4-4cea-9a9d-4b44ebc9cbdf';
	$aukcja='7392649308';
    $data = array(
        'offerCriteria' => array(
        'offers' => array(
        'id' => ''.$aukcja.'')),
		'publication' => array(
        'action' => 'ACTIVATE')
		);
	$xx=commandRequest('https://api.allegro.pl/sale/offer-publication-commands/'.$guId,$generatedKey,$data);
    $myData = json_decode($xx);
	print_r($myData);
```

**Comment by Rnapzsih** [comment]
$data = array(
        'offerCriteria' => array(
        'offers' => array(
        'id' => ''.$aukcja.'')),
        'type' => "CONTAINS_OFFERS".
		'publication' => array(
        'action' => 'ACTIVATE',
       'scheduledFor' => "")
		);

A to nie powinno wyglądać tak?

**Comment by bozydarlelutko** [comment]
Mam identyczny problem - też zaraz osiwieję. Moje dane:
`$data = [
    "offerCriteria" => [
        [
            "offers" => [
                [
                    "id" => $result->id
                ]
            ],
            "type" => "CONTAINS_OFFERS",
        ]
    ],
    "publication" => [
        "action" => "ACTIVATE"
    ]
];`

Dostaję ten sam błąd: An error has occurred

**Comment by KrzysztofLukanowski** [comment]
Weryfikujemy ten problem. Jak tylko będę miał więcej informacji, dam znać.

**Comment by BABYBOOM-SERWIS** [comment]
No powiem że mi zadziałało po 5 godzinach testów. muszę jeszcze sprawdzić na większej ilości aukcji ale błąd wg mnie po stronie samego API / lub dokumentacji jak kto woli.

**Comment by BABYBOOM-SERWIS** [comment]
Zwracam honor, ogólnie jak się dostosuje do dokumentacji to działa poprawnie, a to że te dokumentacje są mało czytelne to inna sprawa

**Comment by bozydarlelutko** [comment]
@BABYBOOM-SERWIS czy możesz podzielić się fragmentem kodu?

**Comment by lukasnet** [comment]
"offerCriteria":[{"offers":[{"id":'.$itemId.'},{"id":'.$itemId.'}],"type":"CONTAINS_OFFERS"}]
lub
'offerCriteria' => array(array('offers' => array(array('id' => $itemId)), 'type' => 'CONTAINS_OFFERS'))

**Comment by bozydarlelutko** [comment]
Dzięki za podzielenie się kodem, ale u mnie nadal nie działa. @KrzysztofLukanowski czy udało się coś ustalić w tej spawie?

**Comment by BABYBOOM-SERWIS** [comment]
function GUID() {
        if (function_exists('com_create_guid') === true) {
            return trim(com_create_guid(), '{}');
        }

        return sprintf('%04X%04X-%04X-%04X-%04X-%04X%04X%04X', mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(16384, 20479), mt_rand(32768, 49151), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535));
    }

    $headers = [
        'accept: application/vnd.allegro.beta.v1+json',
        'content-type: application/vnd.allegro.beta.v1+json',
        'Authorization: Bearer ' . $_SESSION['access_token'] . ''
    ];

    $obj->offerCriteria[0]->offers[0]->id = $nr_aukcji;
    $obj->offerCriteria[0]->type = CONTAINS_OFFERS;
    $obj->publication->action = ACTIVATE;
 
    $guid = GUID();
    $uri = 'https://allegroapi.io/sale/offer-publication-commands/' . $guid;
	$ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $uri);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $obj1);
    $output = curl_exec($ch);


Tak wygląda mój kod, on działa przynajmniej u mnie

**Comment by bozydarlelutko** [comment]
@BABYBOOM-SERWIS dzięki za udostępnienie kodu - fajnie, że chociaż u Ciebie działa ;)
U mnie ten sam kod niestety zwraca błąd _An error has occurred_.

Mój kod:
```php
$headers = [
    'accept: application/vnd.allegro.beta.v1+json',
    'content-type: application/vnd.allegro.beta.v1+json',
    'Authorization: ' . $bearer
];

$obj->offerCriteria[0]->offers[0]->id = $offerId;
$obj->offerCriteria[0]->type = CONTAINS_OFFERS;
$obj->publication->action = ACTIVATE;
$guid = GUID();
$uri = 'https://allegroapi.io/sale/offer-publication-commands/' . $guid;
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $uri);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($obj));
$output = curl_exec($ch);
```

Przesyłane dane JSON:
```json
{
  "offerCriteria": [
    {
      "offers": [
        {
          "id": 7450294369
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ],
  "publication": {
    "action": "ACTIVATE"
  }
}
```

Output:
```json
{
  "errors": [
    {
      "code": "NotAcceptableException",
      "message": "An error has occurred",
      "details": null,
      "path": null,
      "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
    }
  ]
}
```

Najciekawsze jest to, że przesyłając identyczne nagłówki i identyczne dane za pomocą klienta REST (Advanced Rest Client) polecenie wywołuje się poprawnie i oferta się publikuje.

**Comment by lukasnet** [comment]
Dodaj jeszcze to co poniżej i zobacz co tam mówi plik debug.txt, może się przydać w diagnozowaniu błędów
curl_setopt($ch, CURLOPT_VERBOSE, true);
$verbose = fopen('debug.txt', 'w+');
curl_setopt($ch, CURLOPT_STDERR, $verbose);

**Comment by BABYBOOM-SERWIS** [comment]
```
 function GUID() {
        if (function_exists('com_create_guid') === true) {
            return trim(com_create_guid(), '{}');
        }

        return sprintf('%04X%04X-%04X-%04X-%04X-%04X%04X%04X', mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(16384, 20479), mt_rand(32768, 49151), mt_rand(0, 65535), mt_rand(0, 65535), mt_rand(0, 65535));
    }

    function HandleHeaderLine($curl, $header_line) {
        echo "" . $header_line; // or do whatever
        return strlen($header_line);
    }

    $headers = [
        'accept: application/vnd.allegro.beta.v1+json',
        'content-type: application/vnd.allegro.beta.v1+json',
        'Authorization: Bearer ' . $_SESSION['access_token'] . ''
    ];

    $obj->offerCriteria[0]->offers[0]->id = 7450294369;
    $obj->offerCriteria[0]->type = CONTAINS_OFFERS;
    $obj->publication->action = ACTIVATE;
    print_r($obj);
    $obj1 = json_encode($obj);
    $guid = GUID();
    $uri = 'https://allegroapi.io/sale/offer-publication-commands/' . $guid;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $uri);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_HEADER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $obj1);
    curl_setopt($ch, CURLOPT_HEADERFUNCTION, "HandleHeaderLine");
    $output = curl_exec($ch);
    $curl_info = curl_getinfo($ch);
    curl_close($ch);

    echo "<hr>CURL_INFO:<BR>";
    print_r($curl_info);
    echo "<hr>OUTPUT<br>";
    print_r(($output));
   
```

Cały kod po wycięciu z klasy, nawet na Twoim numerze zwraca:

`{"id":"9ad5f3d3-778a-42ef-acf9-d699d08b01f8","taskCount":{"total":0,"success":0,"failed":0}}
`

wpisz ten kod w skrypcie php, uruchom i wstaw to co Ci zwróci. Możesz też wstawić swój kod zeby dało się zobaczyć co jest nie tak, z tego co widzę to u Ciebie inaczej wyglądają dane json niż u mnie.

**Comment by pfunkowski** [comment]
Też otrzymuje komunikat
"taskCount":{"total":0,"success":0,"failed":0}
chociaż metoda działa prawidłowo :)

śr., 11 lip 2018, 20:09 użytkownik BABYBOOM-SERWIS <notifications@github.com>
napisał:

**Comment by BABYBOOM-SERWIS** [comment]
póżniej na podstawie guid można sprawdzić wynik, bo ta funkcja zawsze zwraca zera nie wiem w sumie czemu :) taki zamysł allegro , a tak przy okazji allegro milczy :)

**Comment by pfunkowski** [comment]
A jak obsługujecie zmianę stanu magazynu podczas wznawiania?

śr., 11 lip 2018, 20:21 użytkownik BABYBOOM-SERWIS <notifications@github.com>
napisał:

**Comment by partyumarty** [comment]
@pfunkowski nie obsługujemy, bo to nie działa... poczytaj tu: #363

**Comment by bozydarlelutko** [comment]
@BABYBOOM-SERWIS dzięki za Twój kod - wreszcie zaczęło działać! 🥇

**Comment by Rnapzsih** [comment]
Czy to już działa, mi po publikacji wyskakuje komunikat: {"id":"ae7a4b25-f561-481d-a7bf-c491d6299814","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by KrzysztofLukanowski** [comment]
@Rnapzsih Działa. Otrzymałeś taką odpowiedź, bo w momencie odświeżenia oferty nie jesteśmy w stanie stwierdzić, czy wszystko poszło okej. Aby przekonać się, czy request przeszedł prawidłowo, skorzystać z tego [zasobu](https://developer.allegro.pl/documentation/#/offer-management/getTasksUsingGET).

**Comment by kris86k** [comment]
> ```
>  print_r(($output));
>    
> ```
> 
> Cały kod po wycięciu z klasy, nawet na Twoim numerze zwraca:
> 
> 
> `{"id":"9ad5f3d3-778a-42ef-acf9-d699d08b01f8","taskCount":{"total":0,"success":0,"failed":0}} `
> 
> 
> wpisz ten kod w skrypcie php, uruchom i wstaw to co Ci zwróci. Możesz też wstawić swój kod zeby dało się zobaczyć co jest nie tak, z tego co widzę to u Ciebie inaczej wyglądają dane json niż u mnie.

Podpowiecie dlaczego u mnie ten kod wyrzuca:

'Warning: Creating default object from empty value in /webapi/wzn.php on line 22

Warning: Creating default object from empty value in /webapi/wzn.php on line 24'

**Comment by BABYBOOM-SERWIS** [comment]
ponieważ nie zdeklarowałeś zmiennej jako obiekt a definiujesz wartości :)

możesz to zrobic np:

`$obj = new \stdClass(); `

a dopiero potem:
```
obj->offerCriteria[0]->offers[0]->id = 7450294369;
$obj->offerCriteria[0]->type = CONTAINS_OFFERS;
$obj->publication->action = ACTIVATE;
```
