### ISSUE TITLE
After successfully obtaining the token, the access displays "Full authentication is required to access this resource"

### ISSUE THREAD

**Issue by shulao2010** [allegro/allegro-api#3540]

**Comment by shulao2010** [comment]
url='https://api.allegro.pl/sale/categories'    
'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTc3MjEzMjUsInVzZXJfbmFtZSI6Ijc5OTgzNDg4IiwianRpIjoiZmI2MDFkNWQtMjczYy00ODUxLTg4YWItMjQ2YzBmNDkwZjZhIiwiY2xpZW50X2lkIjoiMjFjYmY4Y2M4YzQ0NDRmNjhiN2FmODljNDEzYmYzY2MiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.sMOkDB3Ols5WDPgYLaoNUSJFtBqR3hmb4pr20TCW-eb7RRbiZYTguldC38TetmtdON48ptsXNj9fUn5U9uugFIMrxKnXZbFI09m5k4d3MhMauCLGZntvq40PF4hddo41W_sBy8WdjCd8enKvSjq4aeFnUGnvBB_ZrjZMVjp5IXKPVXFm4FFGqXcW7AtVtXwDr4vlVjDAF6x9XvR7YFQKo3P5i5RXLeP6jGWAI5EMjfYvcSACMhj1-4N9J3hl37J8B2VzF5lXl7EwESkuMzkFBqotOALrwRjjPDDKxQJ7qhV3IC_jU4EJEIIRhBQG_Xz_2htKnr1FFuEg3UjUawJQWA'
 
**And there are few permissions, only the following items. Ask what went wrong.**
allegro:api:orders:read 
allegro:api:profile:write 
allegro:api:sale:offers:write 
allegro:api:billing:read 
allegro:api:campaigns 
allegro:api:disputes 
allegro:api:bids 
allegro:api:sale:offers:read 
allegro:api:orders:write 
allegro:api:ads 
allegro:api:payments:write
 allegro:api:sale:settings:write 
allegro:api:profile:read 
allegro:api:ratings 
allegro:api:sale:settings:read 
allegro:api:payments:read","

**Comment by MaciejFrackowiak** [comment]
Please, write your questions always in one post - I will answer to your question in post https://github.com/allegro/allegro-api/issues/3542.

**Comment by hahyes** [comment]
You need to provide token as parameter in HTTP request.

**Comment by shulao2010** [comment]
thank you very much
