### ISSUE TITLE
 'Full authentication is required to access this resource'

### ISSUE THREAD

**Issue by shulao2010** [allegro/allegro-api#3542]
Występuje problem: 
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] z zasobem REST API
 - [ ] inny

:beetle: **Opis**

**Comment by shulao2010** [comment]
url='https://allegro.pl/auth/oauth/token?grant_type=client_credentials'
I used this request address. And successfully obtained the token.
But this is always prompted when using tokens to access data.

url='https://allegro.pl/auth/oauth/token?grant_type=client_credentials'
user_info_str = '----' + ":" + '-------'
user_info = base64.b64encode( user_info_str.encode())  
header_info = {'Authorization': "Basic " + user_info.decode()} 
import json
xiangqing = requests.post(url, headers=header_info)  
ss1 = xiangqing.text
print(ss1)
result = xiangqing.content
json_obj = json.loads(result)
tok=json_obj['access_token']
print(tok)
header_info = {"Authorization":'Basic '+tok, "Accept": "application/vnd.allegro.public.v1+json"} 
url='https://api.allegro.pl/sale/categories'
test = requests.get(url, headers=header_info) 
s1 = test.text
print(s1)
jsonobj = test.json()
print(jsonobj)

**Comment by hahyes** [comment]
Authorization is not "Basic", it's "Bearer" type.

**Comment by shulao2010** [comment]
Okay, after following this method, the problem was successfully solved. thank you very much.
