### ISSUE TITLE
Grupowa zmiana ilości

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#3545]
:bulb: **Sugestia**
Witam,
Aktualnie wygląda tak, że jak chce zaktualizować stan magazynowy dla 10 produktów w sklepie to muszę wywołać metodę grupowej zmiany ilości 10 razy, ponieważ metoda umożliwia ustawienie tylko jednego stanu magazynowego dla wszystkich ofert podanych w kryteriach. Optymalnie byłoby gdyby była dodatkowa metoda umożliwiająca masową zmianę ilości podając id oferty oraz jej nową ilość. Dzięki temu, żeby zaktualizować 10-20 ofert na allegro nie potrzebowałbym wykonywać od 10-20 zapytań tylko 1.

Pozdrawiam
Marcin Butlak

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twój głos - sugestię mamy już na liście propozycji dot. rozwoju REST API Allegro.
