### ISSUE TITLE
Hello, please help me to see where there is a mistake，'BAD_REQUEST', 'message': 'Message is not readable.'

### ISSUE THREAD

**Issue by shulao2010** [allegro/allegro-api#3546]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by shulao2010** [comment]
url='https://api.allegro.pl/sale/product-offers'

data={
    "product": {
        "name":"Produkt testowyqweqwe",
        "category":{"id":"124264"},
        "parameters": [
            {"id": "15851","values": ["15851_1"]},
            {"id": "3786","values": ["3786_319653"]},
            {"id": "3806","values": ["3806_407362"]},
            {"id": "201041","values": 5.0},
            {"id": "451","values": ["451_1"]},
            {"id": "3766","values": ["3766_11"]},
            {"id": "127662","values": ["127662_3"]},
            {"id": "127488","values": ["127488_5"]},
            {"id": "127468","values": ["127468_11"]},
            {"id": "59","values": ["59_3"]},
            {"id": "4126","values": ["4126_206685"]},
            {"id": "18160","values": ["18160_212393"]},
            {"id": "201025","values": ["201025_380485"]},
            {"id": "201017","values": ["201017_2381"]},
            {"id": "215930","values": "2"},
            {"id": "202477","values": ["202477_4194304"]},
            {"id": "216925","values": ["216925_275825"]},
            {"id": "201029","values": 5},
            {"id": "201033","values": 10.0},
            {"id": "201037","values": 10.0},
            {"id": "201045","values": 10.0},
            {"id": "201089","values": 10.0},
            {"id": "201249","values": 10.0},
            {"id": "201049","values": 10.0},
            {"id": "215918","values": "10"},
            {"id": "215926","values": "10"},
            {"id": "215922","values": "10"},
            {"id": "225693","values": "5402503366976"}
        ],
    "images": ["https://cbu01.alicdn.com/img/ibank/2019/212/677/12610776212_2147101084.jpg"]},
    "sellingMode": {"price": {"amount": "220.85","currency": "PLN"}},
    "stock": {"available": 1}
}


{'errors': [{'code': 'BAD_REQUEST', 'message': 'Message is not readable.', 'details': None, 'path': 'request.body', 'userMessage': 'Invalid request. Please contact the application author.'}]}

**Comment by MaciejFrackowiak** [comment]
If you want to list an offer assigned to a product with one request please check [our tutorial](https://developer.allegro.pl/en/product_offers/). We described every single point which will allow you to list an offer.

**Comment by shulao2010** [comment]
I want to upload a new product. I have strictly followed your tutorial to operate, but still reported an error.

**Comment by shulao2010** [comment]
send: b'POST /sale/product-proposals HTTP/1.1\r\nHost: api.allegro.pl\r\nUser-Agent: python-requests/2.23.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/vnd.allegro.public.v1+json\r\nConnection: keep-alive\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTc4Mzk5NjcsInVzZXJfbmFtZSI6Ijc5OTgzNDg4IiwianRpIjoiNWY3MmNhMjQtZjlmZS00NGUxLTgzYTktMTc5ZDIzN2QxOWM5IiwiY2xpZW50X2lkIjoiOTcwOGZmYjU0YzQ5NDA0YzhmMmIxODU4MjIwZDc4ZjciLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.nASlv1fu2Yt54zeVAc_nZbl0Nu3B4vs-TUBcucZf1ZE-oAhEtz3ZltwlXG6mFEnrZnDYaBxIWsZ9dgD8I0za-dH_UQmH-ux-Ei2GTeva-ZCt4H4ee8mN7BMN0oN-wgLxIx_vGrVqA2OS2-EPcznSd0Ngli1jWnslMmRpnQV_2QfEWpwMwD_pn0HAed4M3GK7HHIbl3cXDAKMqAUSyHi45ietJ3o41QkdGB0xbOOrTd6naMP3zdzYzq0sxjxLO0i5MZduCBJaiCi4t0xsfyb5o1EVIhRJGfvLSQoddiuFeTQuP342yYXljl4-sJjzSyvVZP8Mydr6HIuSW0U42ils4g\r\ncontent-type: application/vnd.allegro.public.v1+json\r\nContent-Length: 63\r\n\r\n'
send: b'product=name&product=category&product=parameters&product=images'
DEBUG:urllib3.connectionpool:https://api.allegro.pl:443 "POST /sale/product-proposals HTTP/1.1" 400 130
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: expires: 0
header: cache-control: no-cache, no-store, max-age=0, must-revalidate
header: x-xss-protection: 1; mode=block
header: server: envoy
header: pragma: no-cache
header: x-frame-options: DENY
header: trace-id: b2f3551ded4ad098
header: date: Wed, 19 Aug 2020 00:26:51 GMT
header: x-content-type-options: nosniff
header: content-type: application/json
header: content-length: 130
header: x-envoy-upstream-service-time: 37



url='https://api.allegro.pl/sale/product-proposals'

data={
    "product": {
        "name":"Produkt testowyqweqwe",
        "category":{"id":"124264"},
        "parameters": [
            {"id": "15851","values": ["15851_1"]},
            {"id": "3786","values": ["3786_319653"]},
            {"id": "3806","values": ["3806_407362"]},
            {"id": "201041","values": 5.0},
            {"id": "451","values": ["451_1"]},
            {"id": "3766","values": ["3766_11"]},
            {"id": "127662","values": ["127662_3"]},
            {"id": "127488","values": ["127488_5"]},
            {"id": "127468","values": ["127468_11"]},
            {"id": "59","values": ["59_3"]},
            {"id": "4126","values": ["4126_206685"]},
            {"id": "18160","values": ["18160_212393"]},
            {"id": "201025","values": ["201025_380485"]},
            {"id": "201017","values": ["201017_2381"]},
            {"id": "215930","values": "2"},
            {"id": "202477","values": ["202477_4194304"]},
            {"id": "216925","values": ["216925_275825"]},
            {"id": "201029","values": 5},
            {"id": "201033","values": 10.0},
            {"id": "201037","values": 10.0},
            {"id": "201045","values": 10.0},
            {"id": "201089","values": 10.0},
            {"id": "201249","values": 10.0},
            {"id": "201049","values": 10.0},
            {"id": "215918","values": "10"},
            {"id": "215926","values": "10"},
            {"id": "215922","values": "10"},
            {"id": "225693","values": "5402503366976"}
        ],
    "images": ["https://cbu01.alicdn.com/img/ibank/2019/212/677/12610776212_2147101084.jpg"]}

}




url='https://api.allegro.pl/sale/product-offers'
{'errors': [{'code': 'BAD_REQUEST', 'message': 'Message is not readable.', 'details': None, 'path': 'request.body', 'userMessage': 'Invalid request. Please contact the application author.'}]}

send: b'POST /sale/product-offers HTTP/1.1\r\nHost: api.allegro.pl\r\nUser-Agent: python-requests/2.23.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/vnd.allegro.beta.v1+json\r\nConnection: keep-alive\r\nAuthorization: Bearer （"tok"）\r\ncontent-type: application/vnd.allegro.beta.v1+json\r\nContent-Length: 63\r\n\r\n'
send: b'product=name&product=category&product=parameters&product=images'
DEBUG:urllib3.connectionpool:https://api.allegro.pl:443 "POST /sale/product-offers HTTP/1.1" 400 None
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: expires: 0
header: cache-control: no-cache, no-store, max-age=0, must-revalidate
header: x-xss-protection: 1; mode=block
header: server: envoy
header: pragma: no-cache
header: x-frame-options: DENY
header: trace-id: 3342fa247b192003
header: date: Wed, 19 Aug 2020 00:30:46 GMT
header: x-content-type-options: nosniff
header: content-type: application/json
header: x-envoy-upstream-service-time: 23
header: transfer-encoding: chunked

**Comment by MaciejFrackowiak** [comment]
Unfortunately, your request is incorrect. You missed required fields with price and stock. Moreover, you sent parameters in wrong way. Please, look into our sample request:

```
{
    "product": {
        "images": [ "https://image.adrress.com" ],
        "name":"Test product",
            "category":{
                    "id":"258020"
            },
        "parameters": [
            {
                "name": "Kod producenta",
                "values": [
                    "test 1587459230"
                ]
            },
            {
         "name": "EAN",
         "values": [
             "0744861045021"
         ]
     },
            {
                "id": "202749",
                "values": [
                    "5.9"
                ]
            },
            {
                "id": "202869",
                "values": [
                    "512 GB"
                ]
            },
            {
                "id": "202829",
                "valuesIds": [
                    "202829_8374"
                ]
            },
            {
                "id": "202685",
                "valuesIds": [
                    "202685_212929"
                ]
            },
            {
                "id": "127448",
                "valuesIds": [
                    "127448_2"
                ]
            },
            {
                "id": "202865",
                "valuesIds": [
                    "202865_214109"
                ]
            },
            {
                "id": "4388",
                "valuesIds": [
                    "4388_1"
                ]
            },
            {
                "name": "Pojemność akumulatora",
                "values": [
                    100
                ]
            },
            {
                "id": "219",
                "values": [
                    "Bluetooth"
                ]
            },
            {
                "name": "Opcje SIM",
                "valuesIds": [
                    "202821_213913"
                ]
            }
        ]
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}
```

This request returns 201 Created - so just change category id, price, stock, image and parameters values, and you should list an offer.

**Comment by shulao2010** [comment]
I tried various tokens to submit the examples you gave, but still failed. Thank you very much. I intend to abandon this situation. Use the simulated request method instead. At the same time, I hope your company's api return message can be more detailed. For example, an error is returned, where is it, for example, a certain parameter is missing, or the situation is wrong. This can also reduce the workload of users asking here.

**Comment by MaciejFrackowiak** [comment]
We are unable to show error message with missing parameters when whole request is invalid. If you received error 400, it means that request hasn`t reached our server.

**Comment by shulao2010** [comment]
Yes, as you said. The error code is always 400. "url='https://api.allegro.pl/sale/product-proposals'" Isn't this address a request address for adding a new product? I still cannot understand that the request you said did not reach your server. If it does not reach your server, I receive this error "{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path" :"/sale/product-proposals","userMessage":null}]}" Isn't it sent to me by your server.

**Comment by shulao2010** [comment]
I have tried other requests that also write "post". All of them are successful and return "201". However, how to modify the uploaded product, it returns "400"

**Comment by PrzemyslawLukanowski** [comment]
Yes - /sale/product-proposals is the address for adding a new product to our database and /sale/product-offers is the address for listing new offer assigned to a product, which already exists in our database which is not in our database (then you need to provide product data in your request).

In your request above there are some mistakes - e.g. 

`{"id": "201045","values": 10.0},`

the value should be in an array.

> I have tried other requests that also write "post". All of them are successful and return "201". However, how to modify the uploaded product, it returns "400".

Could you please send us your full request for this issue? Remember to remove your token data.

**Comment by shulao2010** [comment]
header_info1 = {"Authorization":'Bearer '+tok,'Accept':'application/vnd.allegro.public.v1+json','content-type':'application/vnd.allegro.public.v1+json'}
url='https://api.allegro.pl/sale/product-proposals'
data={
    "product":{
        "name":"Produkt testowyqweqwe",
        "category":{"id":"87843"},
        "parameters":
            [
                {"name":"Brand","values":["4F"]},
                {"name":"EAN","values":["4774243019827"]},
                {"id":"3786","valuesIds":["3786_319653"]},
                {"id":"54","valuesIds":["54_562129"]},
                {"id":"3806","valuesIds":["3806_407362"]},
                {"id":"451","valuesIds":["451_1"]},
                {"id":"3766","valuesIds":["3766_11"]},
                {"id":"127662","valuesIds":["127662_3"]},
                {"id":"1294","valuesIds":["1294_8"]},
                {"id":"202641","valuesIds":["202641_212457"]},
                {"id":"18293","valuesIds":["18293_3"]},
                {"id":"127488","valuesIds":["127488_5"]},
                {"id":"127468","valuesIds":["127468_11"]},
                {"id":"59","valuesIds":["59_2429"]},
                {"id":"4126","valuesIds":["4126_4"]},
                {"id":"18160","valuesIds":["18160_1"]},
                {"id":"201025","valuesIds":["201025_2513"]},
                {"id":"201017","valuesIds":["201017_2381"]},
                {"id":"202477","valuesIds":["202477_4194304"]}
            ],
        "images": ["https://cbu01.alicdn.com/img/ibank/2019/212/677/12610776212_2147101084.jpg"],
        "sellingMode":
            {
            "price":{"amount":"220.85","currency":"PLN"}
        },
        "stock":{"available":1}
    }
}
requests.post(url, headers=header_info1,json=data,verify=False)#发送请求

POST https://api.allegro.pl/sale/product-proposals HTTP/1.1
Host: api.allegro.pl
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: application/vnd.allegro.public.v1+json
Connection: keep-alive
Authorization: Bearer “this is tok”
content-type: application/vnd.allegro.public.v1+json
Content-Length: 1114

{"product": {"name": "Produkt testowyqweqwe", "category": {"id": "87843"}, "parameters": [{"name": "Brand", "values": ["4F"]}, {"name": "EAN", "values": ["4774243019827"]}, {"id": "3786", "valuesIds": ["3786_319653"]}, {"id": "54", "valuesIds": ["54_562129"]}, {"id": "3806", "valuesIds": ["3806_407362"]}, {"id": "451", "valuesIds": ["451_1"]}, {"id": "3766", "valuesIds": ["3766_11"]}, {"id": "127662", "valuesIds": ["127662_3"]}, {"id": "1294", "valuesIds": ["1294_8"]}, {"id": "202641", "valuesIds": ["202641_212457"]}, {"id": "18293", "valuesIds": ["18293_3"]}, {"id": "127488", "valuesIds": ["127488_5"]}, {"id": "127468", "valuesIds": ["127468_11"]}, {"id": "59", "valuesIds": ["59_2429"]}, {"id": "4126", "valuesIds": ["4126_4"]}, {"id": "18160", "valuesIds": ["18160_1"]}, {"id": "201025", "valuesIds": ["201025_2513"]}, {"id": "201017", "valuesIds": ["201017_2381"]}, {"id": "202477", "valuesIds": ["202477_4194304"]}], "images": ["https://cbu01.alicdn.com/img/ibank/2019/212/677/12610776212_2147101084.jpg"], "sellingMode": {"price": {"amount": "220.85", "currency": "PLN"}}, "stock": {"available": 1}}}

{'errors': [{'code': 'ERROR', 'message': 'An error has occurred', 'details': None, 'path': '/sale/product-proposals', 'userMessage': None}]}


Hello, the above is my request. I think there is something missing in my "body" parameter. I used the api to obtain the required attributes under the category according to the category, and I wrote the "body" according to them. It is also possible that my technique is not good enough and I have not figured out this problem.

**Comment by PrzemyslawLukanowski** [comment]
In your request, you are sending the structure that is valid for /sale/product-offers, but not for /sale/product-proposals. These are two separate endpoints. But there are also some other issues with your structure - parameters with id:

3786
3806
127662
127488
127468
59
4126
18160
202477

don't exist in category 87843. Also sellingMode and stock objects should be outside of the product object.

**Comment by shulao2010** [comment]
I succeeded. I have been using "sale/product-proposals" before and have been unsuccessful. I always think that this address is used to upload a brand new product, but it may not be the function I understand. Later, I successfully uploaded a new product using "product-offers". Maybe I did not understand it correctly when translating the document. But now I am very happy, I successfully uploaded the new product. Thank you very much for your support.

**Comment by shulao2010** [comment]
Hello. In the "Brand" field. Use "sale/categories/ID/product-parameters" to query the value "Other Brand", but once this value is used, an error will be reported.

{'errors': [{'code': 'ProductCreateFailedException', 'message': 'Nieprawidłowe wartości parametrów: [parameter = 3786 [ Wartość niejednoznaczna - inna]]', 'details': None, 'path': 'product./products', 'userMessage': 'Błąd przetwarzania żądania. Nieprawidłowe wartości parametrów: [parameter = 3786 [ Wartość niejednoznaczna - inna]]'}]}
D

**Comment by PrzemyslawLukanowski** [comment]
If you want to pass "other" value you should use the structure below:

```
{
        "id": "129033",                                    -- parameter id
        "valuesIds": [
         "129033_13"                                       -- ambiguous value id
        ],
        "values": [ "Name of the missing brand" ],         -- value, which you want to provide.
                                                           Complete this field.
        "rangeValue": null
 }
```

But please remember that right now not all of the categories support providing custom value for parameter with an ambiguous value. Full list can be found on our [seller's page](https://allegro.pl/dla-sprzedajacych/na-api-mozesz-wprowadzic-wlasna-wartosc-parametru-marka-w-wybranych-kategoriach-z8EDxMZd0fa).

**Comment by shulao2010** [comment]
https://developer.allegro.pl/multi_variant_offers/

https://testv-1259505167.cos.ap-hongkong.myqcloud.com/123.JPG
https://testv-1259505167.cos.ap-hongkong.myqcloud.com/456.jpg
The above picture connection is the effect I want to achieve



Hello, I want to merge my products into this. You can choose the color and size in a product. I follow the tutorial. I uploaded two products with the same size and different colors. I want to merge them, but I cannot succeed now.


{
            "name": 'skaunme',
             "offers": [{"id": "9629527898","colorPattern": "blue"},{"id": "9629527879","colorPattern": "red"}],
            "parameters":  [{"id": "color/pattern"},{"id": "54"}]
    }


{"errors":[{"code":"VARIANT_ATTRIBUTE_NOT_ALLOWED_IN_CATEGORY","message":"It is not allowed to connect offers by parameter 54 in category 76102.","details":null,"path":null,"userMessage":"It is not allowed to connect offers by parameter 54 in category 76102."}]}

{"id": "54"} Does this parameter refer to size variables? If I do not add {"id": "54"}, the error is reported as follows.

{"errors":[{"code":"VALIDATION_ERROR","message":"Offers: 9629527879, 9629527898 are already a part of other variant set.","details":null,"path":null,"userMessage":"Offers: 9629527879, 9629527898 are already a part of other variant set."}]}

I am not trying to understand where the problem is. I am confused.

**Comment by PrzemyslawLukanowski** [comment]
In a category 76102 there is no parameter 54. If you want to check what's the valid parameter ID for "size", you should use GET /sale/categories/76102/parameters, you can also add header "Accept-Language: en-US" to receive a response in English - the proper parameter ID is 3806. 

About the second issue - you cannot merge these two offers, because they already are in a variant set, with five other offers.

**Comment by shulao2010** [comment]
Ok, I see. In fact, it can be merged in this way, but the new product that has just been uploaded can be merged in this way after a period of time. If the merge is carried out immediately, an error will be reported. Thank you very much for your support during the API development phase of our company. Thank you very much. I wish you every success in your work. May a bright smile appear on your face every day.
