### ISSUE TITLE
Sprawdzanie które oferty nie zostały opublikowane

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3547]
Zasób `/sale/offer-publication-commands/{commandId} `umożliwia podejrzenie jak wykonał się proces publikacji i ile ofert opublikowało się poprawnie. Jaki jest najszybszy sposób żeby sprawdzić które z ofert nie zapisały się poprawnie gdy w odpowiedzi dostaniemy failed > 0?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj prosze z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET), wówczas otrzymasz szczegółowy raport z podziałem na oferty.
