### ISSUE TITLE
Aktualizacja ofert danymi z produktu

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3549]
Witam,

podczas edycji ofert borykamy się z przeszkodami biorących się z zmian w produkcie przypiętym do oferty.
Drobna zmiana w produkcie i już nie możemy zmienić ceny, stanów, nie działa wznawianie itd...

Aktualnie radzimy sobie poprzez pobranie informacji o ofercie, pobranie informacji o produkcie, scaleniu i aktualizacji oferty. Niestety jest to dość czasochłonne i zasobożerne rozwiązanie, ponadto końcówka produktowa ma jeszcze Leaky Bucket.

Na froncie zostało wprowadzone fajne rozwiązanie:
![akt](https://user-images.githubusercontent.com/36523118/90522540-20216b00-e16c-11ea-8bea-dbb1398722a0.png)

Planujecie jego odpowiednik po stronie API lub też macie jakąś alternatywę na powyższy problem?

**Comment by MaciejFrackowiak** [comment]
Mamy w planach wprowadzenie podobnego rozwiązania w API - na chwilę obecną jednak jest za wcześnie bym mógł podać jakiekolwiek konkrety co do ostatecznego rozwiązania.
