### ISSUE TITLE
metoda WebAPI doGetPostBuyFormsIds - problem z filtrem

### ISSUE THREAD

**Issue by YpsilonSH** [allegro/allegro-api#355]
Proszę o określenie w jakim formacie należy podać datę dla filtra metody WebAPI doGetPostBuyFormsIds - dokumentacja w tym temacie nic nie przedstawia
filterId = "createTime"
Wszelkie próby zawodzą, podawałem daty dla filterValueRange.rangeValueMin w formacie:
2018-06-27 12:30:00
2018-06-27T12:30:00
2018-06-27
2018/06/27 12:30:00
#5/25/2018 6:53:39 AM#
5/25/2018 6:53:39
1530102655 (- jako UnixTime)
zawsze otrzymuję odp.
Niepoprawna wartość dla filtra: Czas utworzenia FODiZa - [wartość wejściowa]
Również podawanie lub nie wartości wejściowej dla filterValueRange.rangeValueMax - nic nie zmienia

**Comment by PawelTaberski** [comment]
W formacie ISO 8601, przykładowo: 2018-06-26T14:55:49+02:00

**Comment by YpsilonSH** [comment]
Potwierdzam, działa w tym formacie, Dzięki za szybką reakcję.
