### ISSUE TITLE
Wyszukiwarka  wg "trafność - najlepsza cena"

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#3550]
Witam,

Na Allegro pojawiła się nowa funkcjonalność - sortowanie wyników wyszukiwania wg parametru "trafność - nalpesza cena"

Pytanie brzmi, jak wywołać to w REST API? Nie mogę się doszukać w dokumentacji...

Klasycznie trafność wywoływaliśmy np.
https://api.allegro.pl/offers/listing?seller.id={Seller_ID}&sort=-relevance

co teraz należy podać do zmiennej "sort"  ?

Dzięki!

**Comment by MaciejFrackowiak** [comment]
Obecnie jest to test, który dostępny jest dla wybranej grupy użytkowników - dlatego nie ma swojego odzwierciedlenia w API. Jeżeli w przyszłości zdecydujemy się wprowadzić taki typ sortowania na stałe, to na pewno poinformujemy o tym w osobnym komunikacie.

**Comment by Adam1610** [comment]
Ok, rozumiem. Z tego co widzę bardzo fajnie to działa  i potwierdzam, że to dobry pomysł :) Mam nadzieję że wdrożycie to na stałe.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za miłe słowa, od wyników testu zależy przyszłość tego rozwiązania.

**Comment by Adam1610** [comment]
Czy wiadomo może coś ta temat wdrożenia do API? Na Allegro widzę, że śmiga ;)

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem wcześniej - jest to test, który jest dostępny tylko dla wybranej grupy użytkowników. Jeżeli po przeprowadzonych testach okaże się, że ten sposób wyszukiwania pojawi się w Allegro, to dopiero wówczas ujrzy swoje odzwierciedlenie w API.

**Comment by Adam1610** [comment]
OK, czy wiadomo mniej więcej kiedy planowane jest wdrożenie? miesiąc, dwa, pó lroku?

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną nie ma konkretnego terminu.

**Comment by Adam1610** [comment]
w takim razie czekamy, prosze nie zamykac wątku 👍

**Comment by MaciejFrackowiak** [comment]
Wcześniejsze zamknięcie wątku to efekt chochlika, który się wkradł podczas wysyłania odpowiedzi :)

**Comment by Adam1610** [comment]
Zdarza się ;)
