### ISSUE TITLE
API do pobierania kupionych rzeczy

### ISSUE THREAD

**Issue by przemyslaw-szurmak** [allegro/allegro-api#3551]
Dzień dobry,

czy istnieje jakieś API do tego, żeby pobrać wszystkie rzeczy kupione przez zalogowanego użytkownika? Nie interesują mnie moje oferty czy też zamówienia jakie złożyli inni użytkownicy w moich ofertach, próbuję znaleźć informację o rzeczach które ja (tj. zalogowany użytkownik) kupiłem.

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy dostępnych takich zasobów. Jedyne zasoby dostępne od strony kupującego dostępne są [tu](https://developer.allegro.pl/documentation/#tag/Auctions-and-Bidding).

**Comment by przemyslaw-szurmak** [comment]
@MaciejFrackowiak dziękuję za informację.
