### ISSUE TITLE
Powiadomienia wysyłane do serwisów

### ISSUE THREAD

**Issue by dominikfomicz** [allegro/allegro-api#3552]
Chciałbym zasugerować wprowadzenie powiadomień (np. kiedy klient dokona płatności) któe by wysyłały dane do zdefiniowanego w aplikacji webhooku. Takie rozwiązania są zaimplementowane w API PayPal'a czy PayU.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoją sugestię, przekażę ją do osób odpowiedzialnych za rozwój API Allegro.
