### ISSUE TITLE
API Allegro nie odpowiada. Spróbuj później lub wystaw mniejszą liczbę produktów.

### ISSUE THREAD

**Issue by sullaroma** [allegro/allegro-api#3553]
Taki komunikat pojawia się gdy chcę przenieść produkt ze Sky Shopa do folderu w allegro

**Comment by MaciejFrackowiak** [comment]
Nie mieliśmy problemów z działaniem API. Trudno mi się odnieść co oznacza stricte ten komunikat, ponieważ pod nim kryją się jakieś logi, których my nie widzimy. Dlatego, aby wyjaśnić jaki dokładnie napotkałeś problem sugeruję kontakt z dostawcą oprogramowania - bezpośrednio od niego nie otrzymaliśmy żadnej wiadomości.

**Comment by MaciejFrackowiak** [comment]
Udało nam się zlokalizować źródło problemu - w dniu wczorajszym przekazaliśmy niezbędne informacje do firmy Sky-Shop.
