### ISSUE TITLE
Czas między aktualizacją oferty, a jej wznowieniem.

### ISSUE THREAD

**Issue by Rafal-dev-php** [allegro/allegro-api#3554]
Dzień dobry,

Chciałbym się dowiedzieć ile czasu musi upłynąć między requestem, który aktualizuje mi ofertę zakończoną (np. zwiększa stan z 0 na x), a requestem, który wznowi mi tą ofertę. Obecnie, jeśli oba requesty wystąpią zaraz po sobie, dostaję zwrotkę, że nie można wznowić oferty, gdyż niedawno dokonano jej zmian.

Jeżeli jest możliwość wznowienia oferty jednocześnie ją aktualizując, to proszę o podpowiedź.

Z góry bardzo dziękuję!

**Comment by MaciejFrackowiak** [comment]
Co do zasady mamy 60 minut na wykonanie operacji - w zdecydowanej większości operacji ten czas jest diametralnie krótszy. Dlatego najlepiej zlecić jedną operację, zostawić pewien czas na jej wykonanie, a następnie zlecić drugą operację. W tym układzie unikniesz opisanej przez Ciebie sytuacji z odmową wykonania kolejnej operacji, gdy pierwsza jest jeszcze procesowana.
