### ISSUE TITLE
Kiedy można się spodziewać zasobów związanych z "Wysyłam z Allegro"?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3555]
Dzień dobry,

kiedy można się spodziewać informacji nt. "Wysyłam z Allegro" w REST API? Planujecie uruchomić zasoby wraz z uruchomieniem usługi na froncie 1 września, czy jednak będzie trzeba poczekać? 

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Wraz z pojawieniem się usługi w Allegro, udostępnimy jej dokumentację w API.
