### ISSUE TITLE
Brak zamówienia przy wysyłce numeru paczki

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#3556]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry, podczas wysyłki numeru paczki na zasób https://api.allegro.pl/order/checkout-forms/28706b06-30a3-11ea-a885-b1d46f72fef3/shipments Otrzymuje odpowiedź 404 - Order not found. 
Zamówienie jest w statusie READY_FOR_PROCESSING, a mimo to nie można dodać mu numeru paczki. Prosiłbym o weryfikację. 

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
To zamówienie zostało złożone 6 stycznia 2020 - zgodnie z zasadami gwarantujemy dostępność zamówień do 180 dni wstecz, w tym wypadku czas ten jest przekroczony. Na stronie WWW już go nie znajdziesz, w API jeszcze jest dostępne, ponieważ proces "czyszczenia" danych odbywa się co jakiś czas. Powoduje to, że nie ma możliwości dodania trackingu do zamówienia sprzed 180 dni, stąd komunikat Order not found jest prawidłowy.

**Comment by manhunto** [comment]
Wszystko jasne. Bardzo dziękuję za odpowiedź :)
