### ISSUE TITLE
Access to fetch has been blocked by CORS policy.

### ISSUE THREAD

**Issue by SewerynPiorkowski** [allegro/allegro-api#3557]
Próbuję zdobyć access token do API. Używając Insomnii wszystko idzie zgodnie z planem:
![image](https://user-images.githubusercontent.com/50875213/90762465-5f26fc00-e2e5-11ea-95f7-f59dac1b30da.png)
ale mój kod już mi odrzuca i zostawia mnie z błędem:
```javascript
const getAccessToken = async () => {
  const clientId = '58f2e[...]c3057a1c6ea2'
  const clientSecret = '5JvGYHLpFySsS[...]nawuI2vK8v6oHQ8eepThkxSCp'
  const auth = btoa(`${clientId}:${clientSecret}`)
  const requestUrl = 'https://allegro.pl/auth/oauth/token?grant_type=client_credentials'

  const response = await fetch(requestUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Allow-Credentials': true,
      'Access-Control-Allow-Methods': 'GET, POST, PATCH, PUT, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Origin, Content-Type, X-Auth-Token'
    }
  })

  return response
}

console.log(getAccessToken())
```
![image](https://user-images.githubusercontent.com/50875213/90762627-a2816a80-e2e5-11ea-9c00-1690d1caca3e.png)

**Comment by MaciejFrackowiak** [comment]
Korzystasz z wewnętrznego adresu 127.0.0.1:5500, który jest przez nas blokowany zgodnie z informacją, którą zamieściliśmy w poście https://github.com/allegro/allegro-api/issues/2737.
