### ISSUE TITLE
Planowana data wysyłki i dostawy?

### ISSUE THREAD

**Issue by webkret** [allegro/allegro-api#3558]
Cześć.
Nie mogę zlokalizować w dokumentacji więc proszę o wskazówkę.
Pobieram przez Api dane zamówienia, ale nie mogę zlokalizować wyliczonej przez allegro daty wysyłki i daty dostawy?
Jedyna data jaką widzę to: boughtAt w lineItems
Teoretycznie mogę ją wyliczyć po swojej stronie, jednak wolałbym mieć dokładnie ta jaka w swoim zamówieniu na allegro widzi klient.
Z góry dzięki za pomoc.

**Comment by MaciejFrackowiak** [comment]
Te wartości widoczne są wyłącznie na stronie WWW Allegro, nie są dostępne w API.

**Comment by webkret** [comment]
Dzięki za szybką odpowiedź.
Rozumiem, że nie ma w planach udostępniania tego?

boughtAt jest w takim razie datą zakupu i od tego muszę sobie obliczyć resztę, czy tak?

Rozumiem, że w jednym zamówieniu te daty dla wszystkich elementów będę zawsze tożsame?

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną nie - jest to informacja skierowana głównie dla potencjalnego kupującego.
"boughAt" to data zakupu dla wybranego lineItem`a - jeżeli w jednym zamówieniu sprzedałeś kilka przedmiotów z wielu ofert, to "boughtAt" pojawi się tyle razy ile poszczególnych lineItem`ów wystąpi.

**Comment by webkret** [comment]
Dziękuję za odpowiedź.

**Comment by webkret** [comment]
Cześć, czy w tym temacie może coś się zmieniło? 
Wcześniejsza informacja była "Na chwilę obecną" :)
Informacja o dacie jaką otrzymał klient jest bardzo istotna.

**Comment by MaciejFrackowiak** [comment]
Nie, nie dodaliśmy jeszcze tego rozwiązania.

**Comment by webkret** [comment]
A czy jest to w planach?

-----------------------------------

Pozdrawiam
Łukasz Susarski


śr., 8 lut 2023 o 14:21 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Jest to na naszej roadmapie, ale konkretnego terminu wskazać obecnie nie mogę. Jak tylko wprowadzimy opcję, zamieścimy komunikat informujący o zmianie.
