### ISSUE TITLE
Zakończone aukcje widoczne na froncie

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3559]
Witam,

namierzyliśmy przynajmniej kilka aukcji dla których https://api.allegro.pl/sale/offers?offer.id=XXX zwraca
```
            "publication": {
                "status": "ENDED",
                "startingAt": null,
                "startedAt": "2020-06-11T12:59:53Z",
                "endingAt": null,
                "endedAt": "2020-06-22T19:13:28Z"
            }
```
natomiast aukcje są normalnie widoczne na froncie jako aktywne.

Przykładowy trace-id: 84105afb0e6f5420

**Comment by MaciejFrackowiak** [comment]
Potwierdzam zauważony problem - przekazałem sprawę do właściwego działu.
