### ISSUE TITLE
Pytanie o doGetPostBuyFormsDataForSellers w wersji REST API

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#356]
Witam,
Mam pytanie, bo na liście funkcji https://developer.allegro.pl/documentation/ nie mogę znaleźć nic, co by zastąpiło funkcję doGetPostBuyFormsDataForSellers  z webApi.

Generalnie w obsłudze sprzedaży pobieram transakcje doGetFilledPostBuyForms i potem szczegóły doGetPostBuyFormsDataForSellers  i zastanawiam się jak to zastąpić w nowym REST API.

Pozdrawiam

**Comment by PawelTaberski** [comment]
Obecnie nie ma jeszcze zasobu w REST API, który odpowiadałby tej funkcji. Pracujemy nad wdrożeniem zasobów w REST API do obsługi sprzedaży. Niedługo powinniśmy udostępnić takie zasoby w wersji beta. Informowaliśmy o tym [tutaj](https://developer.allegro.pl/news/2018-06-06-Wygaszamy_webapi/).

**Comment by copyact** [comment]
OK, tak właśnie myślałem, ale chciałem się upewnić. Czyli według rozpiski od lipca jest wersja beta a w październiku już gotowe?

**Comment by PawelTaberski** [comment]
Zasoby w wersji beta już będą w pełni działały, jednakże do października zostawiamy czas dla Państwa do zgłaszania uwag do działania tych zasobów. W tym czasie będziemy mogli wprowadzić jeszcze większe zmiany w sposobie ich działania. W październiku przejdziemy z bety na public.
