### ISSUE TITLE
Błąd GET /sale/offers metoda z listą nie zwraca aukcji, szczegóły GET sale/offers/{offerId} zwraca poprawnie

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3560]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Dzień dobry, lista nie zwraca zakończonej aukcji nr 9559748159 widocznej w serwisie https://allegro.pl/oferta/9559748159 oraz na szczegółach przez rest api GET sale/offers/9559748159. Proszę o poprawę listy.

```
7debbb2b0ee51a2d

curl --location --request GET 'https://api.allegro.pl/sale/offers?offer.id=9559748159' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL' \
--header 'Authorization: Bearer #'

{
    "offers": [],
    "count": 0,
    "totalCount": 0
}


3921b55ff3e89ff0

curl --location --request GET 'https://api.allegro.pl/sale/offers/9559748159' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept-Language: pl-PL' \
--header 'Authorization: Bearer #'

{
    "id": "9559748159",
    "name": " ... ",
    "category": {
        "id": "93072"
    },
    "product": {
        "id": "f4918a69-3b59-4ab6-93c9-80db7bc3fad6"
    },
...
```
https://github.com/allegro/allegro-api/issues/667

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku jest to prawidłowe działanie. Sprzedawca ukrył ofertę na froncie, dlatego nie zwracamy jej na liście ofert GET /sale/offers, ale można pobrać jej dane za pomocą GET /sale/offers/{id}.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski jeśli taka operacja następuje to dodatkowo w dzienniku zdarzeń powinno być to odzwierciedlone, skąd mamy wiedzieć że coś na froncie zostało ukryte? To jest błąd do poprawy ;)

**Comment by PrzemyslawLukanowski** [comment]
Zapisałem taką sugestię, by informować o tym, że dana oferta została ukryta, tak aby uniknąć tego typu problemów.

**Comment by jcudzich** [comment]
@PrzemyslawLukanowski Czy coś zmieniło się w tym temacie?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie wprowadzaliśmy zmian w tej kwestii.
