### ISSUE TITLE
Komunikat o błędzie

### ISSUE THREAD

**Issue by BiliBlum** [allegro/allegro-api#3562]
Dzień dobry, gdy próbuję dodać ofertę allegro przez sklep sky-shop wyskakuje komunikat" API Allegro nie odpowiada.
Spróbuj później lub wystaw mniejszą liczbę produktów.

Wszelkie pytania dotyczące działania API należy kierować bezpośrednio do Allegro."
Oczywiście próbuję później i wystawiam jeden produkt a mimo wszystko komunikat się pojawia.

**Comment by MaciejFrackowiak** [comment]
Udało nam się zlokalizować źródło problemu - w dniu wczorajszym przekazaliśmy niezbędne informacje do firmy Sky-Shop.
