### ISSUE TITLE
Zamiana sellerId na sellerLogin

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#3563]
Nie potrafię znaleźć metody zamiany sellerId (zwracane np. przez `GET /offers/listing`) na jego login w Allegro (sellerLogin). Czy istnieje jakiś zasób/url na stronie Allegro gdzie mógłbym rozszyfrować sellerId?

**Comment by MaciejFrackowiak** [comment]
Nie posiadamy obecnie bezpośredniego zasobu do zamiany sellerId na sellerLogin. Przytoczony wyżej przykład natomiast oddaje funkcjonalność.

**Comment by ziemekpr0** [comment]
@MaciejFrackowiak i nie wstyd Wam tak ciągle odpisywać? Przecież co chwile ktoś o to pyta. Przepraszam, ale to co produkujecie jest niefunkcjonalne!

**Comment by MaciejFrackowiak** [comment]
@ziemekpr0 Jak wspomniałem już w poście https://github.com/allegro/allegro-api/issues/3157 temat został zaadresowany jako sugestia dot. rozwoju REST API Allegro.

**Comment by ziemekpr0** [comment]
@MaciejFrackowiak No właśnie... Od kiedy tam jest i od kiedy Wasze REST API jest w wersji public? Wyłączyliście WEBAPI, które taką funkcjonalność miało i nie ma nic w zamian. Serio, nie widzicie tutaj pewnego zgrzytu? Jak można budować coś, co wymaga sellerID, jeżeli nie udostępniacie metody, która pozwala go pobrać?

**Comment by MaciejFrackowiak** [comment]
@ziemekpr0 Przejście z WebAPI na REST API nie gwarantuje, że dotychczas dostępne metody będą miały swoje odzwierciedlenie w nowych zasobach. Sugestie zmian wprowadzające nowe rozwiązania są natomiast sukcesywnie realizowane.
