### ISSUE TITLE
How to fetch products data from specific category via REST API ?

### ISSUE THREAD

**Issue by cyberz** [allegro/allegro-api#3564]
According Allegro REST API Documentation I'm doing next:

- Register new Application (aplikacja konsolowa)
- Using client_id add secret code obtain Oauth2 access token:
`https://allegro.pl/auth/oauth/token?grant_type=client_credentials`
- Got interesting me category items
`/offers/listing?category.id=620&limit=10`

**My question is how to get full info(product id, description, parameter values) for every item under category.id=620?**

**Comment by MaciejFrackowiak** [comment]
It is impossible to get these data if you are not a seller of that offers - in REST API we will not introduce this kind of resources - please, check [our post](https://github.com/allegro/allegro-api/issues/3377).
