### ISSUE TITLE
Link do oferty na podstawie id oferty i nazwy

### ISSUE THREAD

**Issue by pawelcudowski** [allegro/allegro-api#3565]
W jaki sposób można pobrać link do wystawionej oferty? 
Czy można go uzyskać na podstawie id oferty i nazwy?

**Comment by MaciejFrackowiak** [comment]
Odnośnik do konkretnej oferty przyjmuje postać https://allegro.pl/oferta/xxxxxxxxxx, gdzie xxxxxxxxxx to numer oferty.
