### ISSUE TITLE
Czy działa Sandbox ?

### ISSUE THREAD

**Issue by piotrkolodziejski** [allegro/allegro-api#3566]
Próbuje wejść na link  https://apps.developer.allegro.pl.allegrosandbox.pl/new ale pyta się mnie czy chodzi mi o allegro i przekierowuje na allegro. Prośba o pomoc jaki jest link do założenia aplikacji developerskiej ?

**Comment by MaciejFrackowiak** [comment]
To efekt działania przeglądarki Chrome, która umieściła Allegro na liście top domen i sprawdza adresy podobnie wyglądające. W przypadku Sandbox kliknij Ignoruj i zostaniesz właściwie przekierowany.
