### ISSUE TITLE
Problem z wystawianiem produktów przez platforme sky shop

### ISSUE THREAD

**Issue by agashops** [allegro/allegro-api#3569]
Mam taki komunikat API Allegro nie odpowiada. Spróbuj później lub wystaw mniejszą liczbę produktów. Wszelkie pytania dotyczące działania API należy kierować bezpośrednio do Allegro.

Prosze o pomoc.

POZDRAWIAM

**Comment by MaciejFrackowiak** [comment]
Wiemy o problemie, obecnie go wyjaśniamy - szczegóły zamieścimy w pierwotnym temacie https://github.com/allegro/allegro-api/issues/3562.

**Comment by agashops** [comment]
Dziękuję za informację dziś coś ruszyło. Może będzie już dobrze.

Pozdrawiam
Agnieszka Dryl

pon., 24 sie 2020 o 09:31 MaciejFrackowiak <notifications@github.com>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Udało nam się zlokalizować źródło problemu - w dniu wczorajszym przekazaliśmy niezbędne informacje do firmy Sky-Shop.

**Comment by agashops** [comment]
Dziękuję za informację.

pt., 28 sie 2020 o 07:39 MaciejFrackowiak <notifications@github.com>
napisał(a):

**Comment by agashops** [comment]
Dziękuje.

niedz., 27 wrz 2020 o 14:11 stale[bot] <notifications@github.com>
napisał(a):
