### ISSUE TITLE
integracja z sky-shop nie działa

### ISSUE THREAD

**Issue by Dieter13** [allegro/allegro-api#3570]
Występuje problem: 
Mam taki komunikat API Allegro nie odpowiada. Spróbuj później lub wystaw mniejszą liczbę produktów. Wszelkie pytania dotyczące działania API należy kierować bezpośrednio do Allegro.

Prosze o pomoc.

POZDRAWIAM
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by MaciejFrackowiak** [comment]
Wiemy o problemie, obecnie go wyjaśniamy - szczegóły zamieścimy w pierwotnym temacie https://github.com/allegro/allegro-api/issues/3562.

**Comment by tuszeria** [comment]
kiedy problem zostanie rozwiązany ?>

**Comment by MaciejFrackowiak** [comment]
Cały czas działamy w tej materii, zamieścimy update, gdy ostatecznie problem zostanie rozwiązany.

**Comment by MaciejFrackowiak** [comment]
Udało nam się zlokalizować źródło problemu - w dniu wczorajszym przekazaliśmy niezbędne informacje do firmy Sky-Shop.
