### ISSUE TITLE
EAN w aukcjach

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#3571]
Mam pytanie odnośnie eanów w aukcjach, w zasobie /sale/offers jest pole EAN i do tej pory je uzupełnialiśmy lecz zauważyliśmy że dla niektórych aukcji pojawił się również parametr w polu parameters. Przy edycji aukcji przez panel www, jest tylko jedno pole na EAN wiec po jest ten parametr i czy w związku z tym że EAN dla niekótrych kategori jest wymagany to chodzi o EAN w aukcji czy EAN jako parametr?

**Comment by PrzemyslawLukanowski** [comment]
Musisz uzupełnić EAN jako parametr w ofercie. Wszystkie szczegóły na ten temat znajdziesz w naszym newsie - [Parametr GTIN w ofertach oraz produktach.](https://developer.allegro.pl/news/#gtin)
