### ISSUE TITLE
Oznaczanie zamówień jako wysłane - list zwykły

### ISSUE THREAD

**Issue by vendoremo** [allegro/allegro-api#3572]
:bulb: **Sugestia**

O ile dobrze rozumiem dokumentację rest API nie jest obecnie możliwe oznaczenie zamówienia jako wysłane w panelu allegro **poprzez API**, jeżeli zamówienie jest wysyłane listem zwykłym lub kupujący wybrał odbiór osobisty. Brak takiej funkcji ma szereg negatywnych konsekwencji - po pierwsze klient może nie otrzymać informacji o tym, że zamówienie zostało wysłane, a po drugie może anulować zamówienie nawet po jego wysłaniu. Ciężko oczekiwać od sprzedawcy, który wysyła setki listów, żeby codziennie przez 1-2h wykonywał mrówczą pracę polegającą na oznaczaniu zamówień jako wysłane. Czy może jest jakiś sposób na to? Może da się dodać pusty numer przesyłki albo jakoś w ten sposób ugryźć ten temat?

**Comment by PrzemyslawLukanowski** [comment]
Przez API da się oznaczyć takie zamówienia jako wysłane, wystarczy skorzystać z PUT /order/checkout-forms/{orderID}/fulfillment i w strukturze przekazać:

```
{
    "status": "SENT"
}
```
