### ISSUE TITLE
Aktywacja Konta - SANDBOX

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3573]
Czołem, czy mógłbym prosić o aktywacje konta na Allegro Sandbox?

LOGIN: ISOF-START

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie aktywowałem Twoje konto. Ponieważ wybrałeś konto firma, prześlij dwa dowolne pliki przez zakładkę [Dane Konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski , pliki wrzucone. :+1:

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto jest już w pełni aktywne, masz dostęp do wszystkich operacji.

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski , Dzięki wielkie! :+1:
