### ISSUE TITLE
Inpost Allegro Smart

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#3574]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nr płatności: 345aee61-e717-11ea-9892-0d83f1fe08eb
Numer zamówienia: 34297e22-e717-11ea-9418-2ff472dd8e2b

zamówienie opłacone przez Allegro Finanse, status płatności: zakończona
FD wypełniony tylko raz

Manager Paczek oraz api Inpost odmawiają wygenerowania etykiety. 
Komunikat MP: Nie znaleziono takiego zamówienia Allegro
Komunikat API inpost: Zamówienie przesyłki jest innego rodzaju, niż wynika z metody dostawy w zamówieniu

**Comment by PrzemyslawLukanowski** [comment]
Allegro API zwraca prawidłowe dane - zamówienie znajduje się w statuse READY FOR PROCESSING, metoda dostawy to Allegro Paczkomaty 24/7 Inpost, jest również oznaczone jako Smart. Skontaktuj się proszę z pomocą techniczną Inpostu, nie mamy wpływu na działanie ich narzędzia i API.

**Comment by ciaglok2** [comment]
Dziękuje za sprawdzenie po stronie Allegro, ale:
1. to Allegro wprowadziło zmiany ostatnio
2. inpost nie ma pomocy technicznej. jest e-mail, na który ktoś czasem po dwóch tygodniach/m-cach odpowie coś bez związku ze sprawą.

**Comment by PrzemyslawLukanowski** [comment]
Nie wprowadzaliśmy w ostatnim czasie zmian dla GET /order/checkout-forms i sam zasób również działa prawidłowo, świadczy o tym brak innych problematycznych zgłoszeń. Tak jak wspomniałem wcześniej - Manager Paczek to osobne, zewnętrzne narzędzie, na którego działanie nie jest zależne od nas. Nasze API zwraca komplet prawidłowych informacji o tym zamówieniu, co powinno umożliwić bezproblemowe pobranie danych przez zewnętrzne aplikacje.

**Comment by ciaglok2** [comment]
Zmiany zostały wprowadzone wczoraj przez Allegro: https://allegro.pl/dla-sprzedajacych/od-27-sierpnia-nadasz-przesylke-tylko-dla-oplaconego-zamowienia-sprawdz-co-to-oznacza-Xxky8dEWkIA

**Comment by ciaglok2** [comment]
Udało mi się skontaktować z Inpostem. Ignorując informację o tym, że problem występuje nie tylko w MP, ale też w ich API, zaproponowali:
_proszę o wyczyszczenie plików cookies lub skorzystanie z innej przeglądarki i ponowne zalogowanie się na konto Managera Paczek. Import danych z aukcji Allegro może trwać do 8h. Jeśli po wykonaniu powyższych czynności oraz upływie 8h problem dalej będzie występował, proszę o podanie następujących danych:
- Nazwa użytkownika Allegro sprzedającego:
- Nazwa użytkownika Allegro kupującego:
- Adres e-mail sprzedającego (w naszym systemie):
- Numer Aukcji:
- ID płatności:
- Data zakupu i płatności:
- Nowa integracja Allegro (zakładka Allegro) czy stara (zakładka Wyślij paczki)_ 

API na to nie pozwoliło (do API loguję się kontem MP, do którego podpięte są wszystkie moje konta Allegro), ale etykietę udało się wygenerować w MP za pomocą innego konta MP, gdzie podpięte jest tylko jedno konto Allegro.

To nie rozwiązuje problemu, bo generowanie etykiet do tej pory trzeba było robić na 4 razy (w API oddzielnie dla: allegro paczkomaty, allegro paczkomaty smart, allegro miniKurier, allegro miniKurier smart). W MP 4 razy x liczba kont Allegro (smart/nie-smart razem, ale pobrania/bez pobrań oddzielnie). Teraz nawet w API trzeba 4 pomnożyć przez liczbę kont Allegro. Obłęd.
