### ISSUE TITLE
Brak możliwości odświeżenia AccessToken

### ISSUE THREAD

**Issue by koszar93** [allegro/allegro-api#3575]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od kilku dni nie mogę dla jednego z kont klienta odświeżyć AccessToken poprzez wywołanie
`https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhb....`
W odpowiedzi otrzymuję status StatusCode 400 - BadRequest bez jakiegokolwiek komunikatu. Sposób odświeżania tokenów dla innych kont allegro działa prawidłowo. W czym może być problem?

**Comment by PrzemyslawLukanowski** [comment]
Aby przeanalizować przyczynę błędu, będziemy potrzebowali konkretne logi, dlatego prześlij je proszę za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że problem dotyczy wątku #3575 na GitHubie.

**Comment by koszar93** [comment]
Witam, kiedy uzyskam jakąś informację na temat problemu. Zgodnie z zaleceniem, napisałem do Państwa przez formularz kontaktowy, gdzie otrzymałem informację, aby wątek kontynuować tutaj na GITHUB:

> Jeśli prowadzą Państwo zapytanie na forum GITUB, bardzo proszę o kontynuowanie tego wątku w tym miejscu. Udzielają się tam nasi eksperci z dziedziny API, oraz otrzymają tam Państwo najszybciej informację odnośnie rozwiązania zaistniałego problemu.

**Comment by AureliuszBrussy** [comment]
Przykro mi, jednak zgłoszenie to nie dotarło dotychczas do naszego zespołu. Proszę o podanie numeru zgłoszenia wysłanego przez formularz kontaktowy.

**Comment by koszar93** [comment]
Numer: 10875427

**Comment by AureliuszBrussy** [comment]
Dziękuję za numer zgłoszenia. Ze względu na działania użytkownika na koncie, którego autoryzacja dotyczyła - refresh token, z którego próbowałeś skorzystać był w momencie użycia unieważniony. Aktualnie powinieneś ponownie uwierzytelnić użytkownika - tym samym uzyskasz nową parę access token + refresh token.

**Comment by koszar93** [comment]
Dziękuję za pomoc. Synchronizacja przywrócona.
