### ISSUE TITLE
Błąd logowania na sandboxie

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#3576]
Witam,
nie działa logowanie na sandboxie, po kliknięciu na zaloguj następuje przekierowanie na https://allegro.pl.allegrosandbox.pl/?msgAfterRegistration=1 i wyświetla się strona główna 
![obraz](https://user-images.githubusercontent.com/36850550/91270621-37b6b000-e779-11ea-884e-441b464ad4f8.png)

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, jednak nie jest to pierwsze zgłoszenie, które zwraca uwagę na ten problem, dlatego przekazuję je do analizy do zespołu odpowiedzialnego za tę funkcjonalność. Sprawdź proszę po swojej stronie, czy mimo komunikatu o wylogowaniu, masz dostęp do opcji z menu.

**Comment by mzawodzinski** [comment]
Faktycznie jestem zalogowany ale mimo to mam opcję zaloguj, nie zwróciłem na to uwagi.
Jak zobaczyłem "zaloguj" to uznałem że muszę się zalogować.
![obraz](https://user-images.githubusercontent.com/36850550/91274306-c548ce80-e77e-11ea-9772-7ff5d55d1744.png)

zdaje się że wszystkie opcje poza wystaw aukcje(przenosi na produkcje) i zaloguj działają

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sprawdzenie, będziemy analizować tę sytuację. Aby wystawić ofertę z poziomu Sandboxa, skorzystaj z linka https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by PrzemyslawLukanowski** [comment]
@mzawodzinski Czy możesz jeszcze podać ID usera, dla którego zauważyłeś problem?

**Comment by mzawodzinski** [comment]
userId | "44048565"
userName | "aa"

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, wrócę z informacją po wyeliminowaniu problemu.

**Comment by PrzemyslawLukanowski** [comment]
@mzawodzinski Na tę chwilę, aby uniknąć problemu w przyszłości, edytuj jedną z informacji w zakładce Dane konta.

**Comment by mzawodzinski** [comment]
Zadziałało, dziękuję za pomoc 
![obraz](https://user-images.githubusercontent.com/36850550/91388720-37c9b500-e838-11ea-87aa-98a9ddfa24b4.png)
