### ISSUE TITLE
Problem z aktualizacją ilości

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#3577]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam problem z ustawianiem ilości dla aukcji
8517416907
8531667405
8662588428
9304311784

Nie aktualizują mi się ani przez metodę restAPI, ani także przez formularz - na aukcji są 2 sztuki, próbuję zmienić na 1 i dostaję informację, że jest nieprawidłowa liczba sztuk.
Już kiedyś musieli mi Państwo naprawić kilka aukcji ręcznie bo nie dało się tego obejść. Proszę o to samo dla podanych numerów. Proszę o możliwie szybką reakcję - sprzedaż większej ilości niż posiadana nie jest mile widziana przez Klientów.

Pozdrawiam
Maciej

**Comment by PrzemyslawLukanowski** [comment]
W przypadku ofert:

8517416907
8531667405

brakuje uzupełnionego obowiązkowego parametru "Stan". Potwierdzam problem dla pozostałych ofert i przekazuję go do odpowiedniego zespołu.

**Comment by mkaluszka** [comment]
Kolejny numer 9371702511
Ciężko tak pracować tym bardziej, że robi to automat co 10 minut i każda nieudana próba to mail z raportem błedów ...

**Comment by PrzemyslawLukanowski** [comment]
Dodałem numer do zgłoszenia.

**Comment by mkaluszka** [comment]
Kolejny - 8451926566
A tamte nadal - raportowane co 10 minut. Który jestem w kolejce?

**Comment by PrzemyslawLukanowski** [comment]
Stock dla wszystkich ofert, prócz 8451926566, został zaktualizowany. Poinformuję po rozwiązaniu problemu dla ostatniej oferty.

**Comment by PrzemyslawLukanowski** [comment]
@mkaluszka Poprawiliśmy stock dla tej oferty.

**Comment by mkaluszka** [comment]
Dziękuję. Mam kolejną 
9355663560

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem prośbę do odpowiedniego działu, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
@mkaluszka Poprawiliśmy stock dla tej oferty.
