### ISSUE TITLE
Błąd "User is not brandzone user and doesn't have tags subscription" podczas pobierania ofert

### ISSUE THREAD

**Issue by Aleksandra-Janczak** [allegro/allegro-api#3578]
Dwa dni temu pojawił się błąd "User is not brandzone user and doesn't have tags subscription" podczas pobierania ofert przez aplikację wykorzystującą REST API. Zaznaczam, że konto (login artwena) ma aktywny abonament i do tej pory problemu z pobieraniem nie było. Czy jakieś inne ustawienie oprócz abonamentu może mieć wpływ na wystąpienie takiego problemu?

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd nie powinien występować podczas pobierania ofert przez GET /sale/offers, dlatego prześlij proszę przykładowy request i response, abyśmy mogli to przeanalizować. Możesz to zrobić przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (wtedy dopisz w zgłoszeniu GitHub #3578) lub tutaj w wątku - pamiętaj, aby zamazać wtedy wrażliwe dane, takie jak token.

**Comment by Aleksandra-Janczak** [comment]
Problem wyjasniony, polegał na czymś innym (używano błędnych danych do logowania a błąd występował w rzeczywistości przy pobieraniu tagów, tylko zgłaszał się w innym miejscu). Dziękuję za reakcję i przepraszam za zamieszanie :)
