### ISSUE TITLE
how to install an application on allegro sandbox store to fetch the private code

### ISSUE THREAD

**Issue by ahmed624** [allegro/allegro-api#3579]
I am from a company called Volo Commerce. Volo Commerce is a UK market-leading ecommerce solution package that has many connections to online marketplaces.

We have registered an app in the sandbox and the client id and client secret is working fine to fetch the bearer-token-for-application for the public APIs but can't find information on how to add this application to my sandbox store so we can start testing with the private code to fetch the bearer-token-for-user as mentioned in your documents. Can anyone point me in the right direction or walk me through the process.

Thanks,

**Comment by PrzemyslawLukanowski** [comment]
You can receive bearer-token-for-user via code or device flow authorization. We describe both processes step by step in our [tutorial.](https://developer.allegro.pl/en/auth/#app)

**Comment by ahmed624** [comment]
yes I need a test store to install the application to. so that I can generate the private code to be sent to the redirect uri. is there a test store associated with the sandbox account? if yes then how to install the app there?

**Comment by PrzemyslawLukanowski** [comment]
We have only our test environment https://allegro.pl.allegrosandbox.pl/ if this is what you mean.

**Comment by ahmed624** [comment]
yes how do we install an application to this test environment? i dont see any install button over there. and it says associated apps are empty. I assume getting the app installed is the way to get the auth token on the redirect uri of the app.

**Comment by PrzemyslawLukanowski** [comment]
You should register your application on https://apps.developer.allegro.pl.allegrosandbox.pl/ to receive clientID and clientSecret, after that, you can go to the next steps described [here](https://developer.allegro.pl/en/auth/#user) - all of them you should do in your application.

**Comment by ahmed624** [comment]
so in the tutorial it says on point 1 that In the application there is a **button/link, e.g. Log in to Allegro** calling an HTTP request with relevant parameters to the resource allowing for user authentication:. Can you tell me where this button is ? as i dont see any such button on https://apps.developer.allegro.pl.allegrosandbox.pl/

**Comment by PrzemyslawLukanowski** [comment]
It means that in your application you should create this button, which will call an HTTP request. It is not related with button on our test environment.

**Comment by ahmed624** [comment]
just to confirm, in our application there will be a login button that will call the https://allegro.pl/auth/oauth/authorize?response_type=code and will pass our client id then the auth code will be provided by allegro to our redirect uri mentioned in the app.

**Comment by PrzemyslawLukanowski** [comment]
Yes, exactly, but remember that in https://allegro.pl/auth/oauth/authorize? besides response_type you should also provide clientId and redirect_uri parameters. After you receive a ten-second code your application should call for a token (step 5 in our tutorial).

**Comment by ahmed624** [comment]
yes thanks got it, PrzemyslawLukanowski  thank you so much. will surely give it a try.

**Comment by ahmed624** [comment]
![allegro_error](https://user-images.githubusercontent.com/59685078/91316674-880e2c00-e7d2-11ea-8a60-558ab65a8733.png)

this is what i get when i try to follow your steps. Can you tell me whats wrong here

**Comment by PrzemyslawLukanowski** [comment]
Try to use this authorization address in your browser, you should receive the ten-second code in the URL address.

**Comment by ahmed624** [comment]
thanks, yeah now its working.
