### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by Ontr** [allegro/allegro-api#358]
Czy Draft po jakimś czasie nieaktywności jest automatycznie usuwany? Czy jest widoczny w panelu "Moje Allegro"? Czy zdjęcie dodane do niewystawionego draftu nie będzie automatycznie usuwane (expiresAt)?

**Comment by PawelTaberski** [comment]
Obecnie nie ma czasu po jakim usuwamy drafty, i nie pojawiają się w panelu w Moim Allegro. Zdjęcia dodane do draftu nie wygasną.
