### ISSUE TITLE
My product has no brand. His category is "124264". How should I set the brand in the API.

### ISSUE THREAD

**Issue by shulao2010** [allegro/allegro-api#3580]

**Comment by shulao2010** [comment]
https://allegro.pl/dla-sprzedajacych/na-api-mozesz-wprowadzic-wlasna-wartosc-parametru-marka-w-wybranych-kategoriach-z8EDxMZd0fa

My category ID is not in this document. Does this mean that unbranded products are not allowed to be uploaded? But you can choose "Other Band" for manual upload on the page


{"id": '3786',"valuesIds": ["3786_85"],"values": [ "Nazwa brakującej marki" ],	  "rangeValue": None}

Can I upload unbranded products via API?

**Comment by PrzemyslawLukanowski** [comment]
You can choose "Other Brand", but when uploading a product you should point a specific Brand, that's why you should also provide your value in "values" field.
But, on the other hand, in this category, there is a flag "offersWithProductPublicationEnabled": false (you can check it via GET /sale/categories/12464), which means you are unable to list offer assigned to a product, you can only publish your offer via [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) without associated product. Check for more info in [our tutorial](https://developer.allegro.pl/en/sale/).

**Comment by shulao2010** [comment]
But why can you choose the brand "Other Brand" when uploading in the "allegro" seller background. However, API uploading products have to look different.

**Comment by shulao2010** [comment]
https://testv-1259505167.cos.ap-hongkong.myqcloud.com/360%E6%88%AA%E5%9B%BE20200830104952441.jpg   
In the picture above, I manually upload products in the background, no matter which category I choose. I can use the "other Brand" option. But why only some categories of api can use "other Brand". I think this design is not very reasonable. 124264 76084 76076 76083 None of the above categories can use "other Brand", when uploading using api. But they can use "other Brand" when uploading manually in the background.

**Comment by shulao2010** [comment]
If a category "offersWithProductPublicationEnabled": false, it can be understood that other brands cannot be used？

**Comment by PrzemyslawLukanowski** [comment]
You can choose "other Brand" for those categories if you are listing a new offer via [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) (this is equivalent of the functionality in your screenshot), but not when you are uploading new product via [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) or [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). 
"offersWithProductPublicationEnabled": false - means that you can't assign a product to your offer, you can only list a new offer via POST /sale/offers. Other brand values can be used. 

You can also send your sample request and response, so we can verify it.

**Comment by shulao2010** [comment]
Hello, I use "POST / sale / offers" to release new products. However, none of the following categories can use "other Brand" or "other". They will return the error 
"{'errors': [{'code':'ProductCreateFailedException','message':'Invalid parameter values: [parameter = 3786 [Value is ambiguous-Other Brand]]','details': None, 'path':'product./products','userMessage':'Request failed. Invalid parameter values: [parameter = 3786 [Value is ambiguous-Other Brand]]'}]}.

The following categories will report the above errors


76039-76102-76078-76025-76036 -76077 -76034 -112121-76105-78137-76042-76044-257020----76084--75994--87913----76003--76035--254778-124265 -124264 -75998-76012-76043-76076 -76083 -76104-76095-76103

**Comment by PrzemyslawLukanowski** [comment]
Could you please send us your full request (without token)? Via POST /sale/offers you can only list new offers, not upload new products to our database. This message looks like this is a response for other endpoint than POST /sale/offers.

**Comment by shulao2010** [comment]
“https://api.allegro.pl/sale/product-offers'”
{"name": "Brand", "values": ['Other Brand']}
Sorry, my description is wrong. I am using "https://api.allegro.pl/sale/product-offers'".

{'product': {'name': "2020 Leggings women's riding pants breeches tigh", 'category': {'id': '76003'}, 'parameters': [{'name': 'EAN', 'values': ['8382597684590']}, {'name': 'Additional Features', 'values': ['none']}, {'name': 'Finish', 'values': ['other']}, {'name': 'Thickness', 'values': ['200']}, {'name': 'Main Fabric', 'values': ['other']}, {'name': 'Type', 'values': ['Other']}, {'name': 'Kind', 'values': ['other']}, {'name': 'Color', 'values': ['white']}, {'name': 'Size', 'values': ['M']}, {'name': 'Brand', 'values': ['Other Brand']}], 'images': ['https://testv-1259505167.cos.ap-hongkong.myqcloud.com/imgdata/17140928648_1484890501.jpg']}, 'sellingMode': {'price': {'amount': '44.0', 'currency': 'PLN'}}, 'afterSalesServices': {'impliedWarranty': {'name': 'test'}, 'returnPolicy': {'name': 'test'}}, 'stock': {'available': 944}}


My product does not have a brand. So I want all my product brands to display "other Brand", but in the following categories, if I use "other Brand", an error will be reported.

76039-76102-76078-76025-76036 -76077 -76034 -112121-76105-78137-76042-76044-257020 ---- 76084--75994--87913 ---- 76003--76035--254778-124265- 124264 -75998-76012-76043-76076 -76083 -76104-76095-76103

{'errors': [{'code': 'ProductCreateFailedException', 'message': 'Invalid parameter values: [parameter = 3946 [ Value is ambiguous - Other Brand]]', 'details': None, 'path': 'product./products', 'userMessage': 'Request failed. Invalid parameter values: [parameter = 3946 [ Value is ambiguous - Other Brand]]'}]}
Code :422

What I don't understand is that some categories use "other Brand" to return results that are successful, and some are failed. But in the background of the seller center, manually upload products, and each category is allowed to use "other Brand". The link below is a screenshot.

https://testv-1259505167.cos.ap-hongkong.myqcloud.com/360%E6%88%AA%E5%9B%BE20200830104952441.jpg

**Comment by PrzemyslawLukanowski** [comment]
Remember that offers and products are two separate things on Allegro. You can list an offer of an item and you can also assign product from our database (or create your own) to this offer. You can read more about productization in [our guide](https://developer.allegro.pl/en/productization/).

Via POST /sale/product-offers you can list an offer assigned to a product, but not in each category. You can check it via GET /sale/categories/{categoryId} in offersWithProductPublicationEnabled field. In your case - we return false, so it means you can only list a new offer, but you can't associate it with a product. You should use POST /sale/offers and you will be able to choose the "Other Brand" value.

**Comment by shulao2010** [comment]
API document introduction is to add new quotations to existing products. Isn't it that understanding? I want to add a completely new product, a product that is not in the database.

**Comment by PrzemyslawLukanowski** [comment]
In all of the categories that you mentioned above, you can't assign a product to an offer (field offersWithProductPublicationEnabled is false), so in your case, you don't need to to create a new product via POST /sale/product-offers, you should use [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) to list an offer of your item. You will find more about listing offers in [our guide](https://developer.allegro.pl/en/sale/).

**Comment by shulao2010** [comment]
{'errors': [{'code': 'NotAllowedException', 'message': 'The HTTP method is not allowed', 'details': None, 'path': None, 'userMessage': 'An error occurred'}]} 

put  'https://api.allegro.pl/sale/offers/{offerId}

Hello, I want to guide what caused this error. I have successfully created a draft. I want to show him in the store now.

**Comment by shulao2010** [comment]
https://developer.allegro.pl/sale/#7-draft-oferty   
I have successfully completed the seventh step, but I kept reporting the error described above in the eighth step.

**Comment by PrzemyslawLukanowski** [comment]
Are you sure you are using the correct endpoint for making changes in the offer? A valid endpoint is PUT /sale/offers/{offerID} - as a {offerID} you should provide ID which you receive in the response when you created a draft.

**Comment by shulao2010** [comment]
code:405

**Comment by PrzemyslawLukanowski** [comment]
Could you send us your full request?

**Comment by shulao2010** [comment]
PUT / sale / offices / {offerId}
data = {"name": "66666666666666666666666666666",
                "category": {"id": "76039"},
                "parameters": [
                    {"id": "225693", "values": ["8382597684866"]},  # 品牌
                    {"id": "3786","valuesIds": ["3786_85"]},#品牌
                    {"id": "3806", "valuesIds": ["3806_407374"]},#尺寸
                    {"id": "451", "valuesIds": ["451_1"]},  # 颜色
                    {"id": "3766", "valuesIds": ["3766_14"]} , # 面料
                    {"id": "18293", "valuesIds": ["18293_4"]} , # Sleeve
                    {"id": "201077", "valuesIds": ["201077_380489"]} , # Leg Length
                    {"id": "11323", "valuesIds": ["11323_1"]},  # 是否是新的
                    {"id": "1294", "valuesIds": ["1294_8"]},  # kind
                    {"id": "201081", "valuesIds": ["201081_1"]},  # Pants Type
                    {"id": "201085", "valuesIds": ["201085_1"]},  # Additional Features
                    {"id": "201017", "valuesIds": ["201017_2357"]}  # Leg Length
                ],
                "description": {
                    "sections": [
                        {"items": [
                    {
                        "type": "TEXT",
                        "content": "<p>Tekstowy opis przedmiotu</p>"}]}]},
                "images": [{"url":"https://testv-1259505167.cos.ap-hongkong.myqcloud.com/imgdata/8969700586_3640521.jpg"}],
                "sellingMode": {"format": "BUY_NOW",
        "price": {"amount": "1499", "currency": "PLN"},},
        "payments": {"invoice": "NO_INVOICE"},
        "afterSalesServices": {"impliedWarranty": {"id":"c1692f7b-1b79-45fb-96d0-d5e61c24ea35"}, "returnPolicy": {"id":"582196b0-35f9-462c-80de-d0caf3ea5fd5"}},
        #"afterSalesServices": {"impliedWarranty": {"c1692f7b-1b79-45fb-96d0-d5e61c24ea35"}, "returnPolicy": {"582196b0-35f9-462c-80de-d0caf3ea5fd5"},"warranty": {""}},
        "delivery": {"shippingRates": {"id": "986b6159-2511-43df-aae4-2830fdba2a5c"},"handlingTime": "PT168H"},
        "location": { "countryCode": "CN",
        "province": "Shan Dong",
        "city": "Shou Guang",
        "postCode": "262700"        },
        "stock": { "available": 4,"unit": "UNIT"}
        }

Now I have seen the product I uploaded in the draft. Now I want to publish this draft to the website.

**Comment by PrzemyslawLukanowski** [comment]
Please find below issues with your request:

- you are using PUT /sale/offices/{offerID} instead of PUT /sale/offers/{offerID} <- as a {offerID} you need to provide specific offerID,
- in the parameters field, there are unnecessary data, such as # Pants Type, # Additional Features - you should remove it,
- in the images section, there is an image from external server. In this resource, you need to first upload images to our server via POST /sale/images ([guide](https://developer.allegro.pl/en/sale/#3-upload-photos)),
- content in description section should be inside HTML tags ([guide](https://developer.allegro.pl/en/sale/#5-offer-content)),
- leave the "province" field in the location section empty if countryCode is other than PL,
- field "afterSalesServices" id duplicated,
- after changes, you can activate your offer via PUT /sale/offer-publication-commands/{commandId} ([guide](https://developer.allegro.pl/en/sale/#9-publish-your-offer)).

**Comment by shulao2010** [comment]
We ware unable to download one of your images: https://imgur.com/1aOIvg3E.jpg.',   Upload the picture to your server, it will report an error

**Comment by PrzemyslawLukanowski** [comment]
That's because the image from this address is no longer available.

**Comment by shulao2010** [comment]
ok ,I succeeded. Thank you for your help.
