### ISSUE TITLE
Zakończenie oferty END

### ISSUE THREAD

**Issue by tomzara** [allegro/allegro-api#3583]
Mama taki problem z zakończeniem oferty. Mianowicie w momencie jej zakończenie zmienia się także sygnatura w aukcji.
Co może być powodem zmiany sygnatury? Co zrobić aby została ona bez zmian.

Wysyłane dane:
{
"publication":
    {
     "action":"END"
    },
    "offerCriteria":[{"offers":[{"id":"9636147445"],"type":"CONTAINS_OFFERS"}]
}

**Comment by PrzemyslawLukanowski** [comment]
Przenalizowałem nasze logi, wygląda na to, że to nie komenda zakończenia oferty ma wpływ na zmianę sygnatury, ponieważ wydarzyło się to wcześniej za pomocą PUT /sale/offers/{offerID}:

2020-08-27 10:08:39.881 - ustawienie sygnatury 314584
2020-08-27 10:11:42.583 - ustawienie sygnatury 7025
2020-08-27 10:42:00.583 - zakończenie oferty

**Comment by tomzara** [comment]
Poproszę o sprawdzenie ofert 9636352315, taka sama sytuacja.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku wartość dla external.id to 7025 od samego początku trwania oferty aż do teraz.

**Comment by tomzara** [comment]
Sytuacja wyjaśniona, dziękuję za pomoc.
