### ISSUE TITLE
Czy są jakieś dane testowe na Sandboxie ?

### ISSUE THREAD

**Issue by piotrkolodziejski** [allegro/allegro-api#3584]
Witam,
kiedyś słyszałem, że dajecie Państwo jakieś dane testowe na Sandboxie a teraz nie widzę, żebym miał jakieś eventy czy to nadal aktualne ?

**Comment by PrzemyslawLukanowski** [comment]
Nie dostarczamy takich danych, musisz utworzyć nowe konto - kupującego, wykonać np. zakup w ofercie. Dopiero wtedy jako sprzedający otrzymasz przykładowe eventy.

**Comment by piotrkolodziejski** [comment]
A można to zakładać w ramach sandboxa ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, Sandbox to odrebnę środowisko względem produkcji i możesz założyć na nim konto zarówno dla sprzedającego, jak i kupującego.

**Comment by piotrkolodziejski** [comment]
Ok, a proszę powiedzieć bo już zalogowałem się na sandboxie na moje konto i chce wystawić przedmiot po czym przekierowuje mnie na stronę allegro.pl czy tak ma być ? Jeśli tak w takim wypadku jak wystawić przedmiot na sandboxie ?

**Comment by piotrkolodziejski** [comment]
W sumie na mozilli przekierowuje mnie na allegro i prosi, żebym się logował a na chromie dostaje informację, że Aktywuj konto aby sprzedawać na Allegro Lokalnie. Można prosić o pomoc z tym ?

**Comment by piotrkolodziejski** [comment]
Jeszcze dodam, że mam zwykłe konto.

**Comment by piotrkolodziejski** [comment]
Próbowałem aktywować konto ale mogłem tylko podać dane, nie mogłem przelać pieniędzy na konto, prośba o szybką odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Aby wystawić ofertę na Sandboxie, skorzystaj z linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie. Jeśli chcesz zmienić konto zwykłe na firmowe, skorzystaj z tego [linku](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php/convertAccount).

**Comment by piotrkolodziejski** [comment]
OK ale pojawiło sie pytanie jak dodać produkt, można poprosić o url dodania produktu ?

**Comment by piotrkolodziejski** [comment]
Udało mi się dojść do procesu dodania przedmiotu ale wyświetla mi się info Jeśli chcesz wystawić przedmiot, aktywuj sprzedaż.

**Comment by PrzemyslawLukanowski** [comment]
Wkleiłem powyżej - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, kieruje do Sandboxa (nie lokalnie).

**Comment by PrzemyslawLukanowski** [comment]
Poproszę w takim razie o ID lub login.

**Comment by piotrkolodziejski** [comment]
mogę podać email na który się loguję 
piotr.kolodziejski@kivy.pl

**Comment by MaciejFrackowiak** [comment]
Na Twoim koncie sprzedaż jest już aktywna.

**Comment by piotrkolodziejski** [comment]
ok, już mogę wystawiać produkty ale jeszcze mam pytanie jak je kupować czy mam płacić tą minimalną złotówkę czy to jest jakoś inaczej rozwiązane ?

**Comment by MaciejFrackowiak** [comment]
Uruchomiony jest symulator płatności, czyli płacisz tylko wirtualnie.
