### ISSUE TITLE
Problem z Zasobem /sale/images

### ISSUE THREAD

**Issue by Teestus** [allegro/allegro-api#3585]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Request przesłałem za pomocą formularza kontaktowego

:beetle: **Opis**

Podczas próby wysłania zdjęcia poprzez zasób /sale/images otrzymuję błąd o nastepującej treści:

`downloading image from URL 'tutaj link' failed. Server returned the following HTTP status code : 500 INTERNAL_SERVER_ERROR and response body '500 Internal server error got itself in trouble'`

Błąd zdarza sie wybiórczo dla różnych zdjęć i np 3 razy z rządu otrzymam w odpoweidzi error, a za 4 razem, i każdym kolejnym jest już w porządku i dostaje pozytywny response

**Comment by AureliuszBrussy** [comment]
W Twoim przypadku adres URL żądania jest nieprawidłowy - zamiast “https://api.allegro.pl/sale/images”, adres powinien wyglądać następująco: “https://upload.allegro.pl/sale/images”.

**Comment by Teestus** [comment]
Zmodyfikujemy aplikacje w takim rpzypadku aby uzywała poprawnego URL, nie mniej jednak czy w przypadku czy w przypadku błędnego adresu nie powinniśmy odnotować błędu za każdym razem ?, po n-tej próbie wysłania zdjęcia, otrzymujemy pozytywny response.

**Comment by AureliuszBrussy** [comment]
Nie gwarantujemy poprawnego działania nieudokumentowanego endpointu. Poprawny adres to żądania to https://upload.allegro.pl/sale/images.
