### ISSUE TITLE
INFO API REST 

### ISSUE THREAD

**Issue by Sergiutirziu** [allegro/allegro-api#3587]
Dear all, hello
I intend to create a site in the auto parts sector using all products from the ALLEGRO.PL automotive category.
There is talk of about 40 million products.
My question is: can I use ALLEGRO's REST API for the extract of all products or the app and will it only valid for sellers on ALLEGRO.PL?
Waiting for a kind reply I wish you a good day!
Sergiu Tirziu

Szanowni Państwo, witam
Zamierzam stworzyć serwis w branży części samochodowych z wykorzystaniem wszystkich produktów z kategorii motoryzacyjnej ALLEGRO.PL.
Mówi się o około 40 milionach produktów.
Moje pytanie brzmi: czy mogę użyć API REST ALLEGRO do wyodrębnienia wszystkich produktów lub aplikacji i czy będzie to ważne tylko dla sprzedawców na ALLEGRO.PL?
Czekam na miłą odpowiedź, życzę miłego dnia!
Sergiu Tirziu

**Comment by AureliuszBrussy** [comment]
Extracting offers on your website/application should only take place in cases when you are the seller of the product. Any other use of the offers is not allowed.
