### ISSUE TITLE
Aplikacja przekroczyła limit zapytań - Przepisz kod z obrazka

### ISSUE THREAD

**Issue by Bienqq** [allegro/allegro-api#3588]
Podczas wysyłania zapytań GET pod adresy ogłoszeń w stylu:

https://allegro.pl/oferta/bateria-energizer-industrial-lr6-aa-1-5v-1-szt-8318267039

Otrzymuje błąd że aplikacja przekroczyła limit zapytań (odpowiedź z kodem 429). 
Jest zwracana strona z uzupełnieniem Capchy, na zdjęciu go nie widać bo bo to statyczny HTML.

Jaki jest limit requestów dotyczących zapytań wysyłanych w kierunku Waszej strony internetowej ? (Nie mam na myśli API)

![image](https://user-images.githubusercontent.com/35897213/91470894-94a78880-e895-11ea-9896-b480157d6a9d.png)

**Comment by AureliuszBrussy** [comment]
Nie udzielamy szczegółowych informacji dotyczących tego dodatkowego limitu. Jest to zabezpieczenie przed działaniem, które nie przypomina standardowego działania użytkownika. 

Po pojawieniu się błędu 429 sugerowałbym zaprzestania kolejnych requestów, ponieważ każdy kolejny wydłuża czas trwania blokady.

**Comment by mlv-** [comment]
Dostałem tą wiadomość przy standardowym korzystaniu z allegro jako zwykły użytkownik (żadnej automatyzacji, itd.), chyba za agresywnie coś działa to zabezpieczenie.

**Comment by AureliuszBrussy** [comment]
@mlv- jeżeli Ciebie to niepokoi lub jest uciążliwe - jeżeli to możliwe, prześlij proszę w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt?kategoria=78c31546-41e0-4305-8a41-4415ed3bd32c&subjectId=e6bcf131-deb8-4c2e-88cb-d929981a108c) adres IP, który został zablokowany wraz z informacjami kiedy to się wydarzyło. W zgłoszeniu wskaż numer tego zgłoszenia: #3588. Spróbujemy to sprawdzić.
