### ISSUE TITLE
How to find out if an offer is sold or not? 

### ISSUE THREAD

**Issue by kvinkinamoto** [allegro/allegro-api#3589]
How to find out if an offer is sold or not? 
Let's say I received a list of proposals for api and some product from it has already been sold. how it can be checked.

**Comment by AureliuszBrussy** [comment]
Using the [GET /sale /offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) resource you can check all events related to changes in offers in the last 24 hours, including change in stock. If the stock is sold out - the offer will be automatically ended. You can also check the available stock in an offer using the [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) resource in the stock.available field.
