### ISSUE TITLE
niewytłumaczalne ilości - wznawianie i edytowanie oferty

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#359]
Godzina jest późna i nie wiem, czy dobrze to wszystko ubiorę w słowa. Ogarniam REST bo chcemy zrobić wznawianie. Działa do momentu gdy aukcja była zakończona z dostępną ilością. Wtedy wystarczy ACTIVATE i aukcja wstaje. Co prawda na etapie jej wskrzeszania sale/offer-publication-commands/ zwraca [total] => 0, [success] => 0, [failed] => 0 tylko po to, żeby po minucie jednak wznowić tę aukcję i po kolejnym odpytaniu o GUID zwrócić  [total] => 1, [success] => 1, [failed] => 0 no ale to w końcu beta więc OK. Działa. 
Schody zaczynają się, gdy aukcja umarła z powodu braku sztuk (wystawione 12, sprzedane 12 i dead). Wtedy przy wskrzeszaniu przez ACTIVE oczywiście jest babol. Oczywiście webapi nie pozwala dotknąć trupa więc ilości nie można zmienić. Jedziemy zatem w REST. GET na /sale/offers/ szybka podmiana ilości, PUT i... no i tu nie można świętować. Tu jest taki hit, że chyba zanim to pozbieracie to już na emeryturę pójdę. Otóż ilość przekazywana PUT w STOCK AVAILABLE (a było to w moim przypadku 13) okazała się być potraktowana jak ilość dodatkowo sprzedanych sztuk w moim odczuciu. Dlaczego ? No bo 4 razy uruchomiłem skrypt podbijając za każdym razem o 13 szt (pierwotnie było wystawione i sprzedane 12). Za każdym razem nie dawało te efekt i wciąż nie można było wskrzesić jej przez ACTIVATE. Zdesperowany postanowiłem sprawdzić czy mogę ją wskrzesić przez stronę Allegro, bo może z aukcją było coś nie tak. Klikam WZNÓW na allegro.pl i w ilości mam wpisane 12. Myślę sobie - zwiększę o 1. Wpisuję 13, klikam WZNÓW i dostaję odpowiedź, że to za mało. Wpisuję 30 - za mało. Wpisuję 900 szt - BINGO. Aukcja wznowiona ręcznie. Z ciekawości odpalam webapi i robię korektę do 500 szt. Na aukcji widnieje 500-12 czyli 488 - wszystko poprawnie. Pobieram draft w REST i co widzę ? 436 szt dostępne... wpisuję mu jako available 13 szt i VALIDATION ERRO The quantity of items to be listed may not be lower than 1. Wchodzę więc nauczony przykładem na allegro.pl i próbuję ręcznie wskrzesić aukcję. Jako ilość mam... -692 szt, Kurtyna opada. Idę spać. 
Drogi supporcie REST - zweryfikujcie aukcję numer **7425659768**. Prześledźcie jej stock i powiedzcie skąd się wzięło 436. Skąd się wzięło MINUS 692 i dajcie jakiś mini tutorial jak wskrzesić aukcję na której dostępna ilość = 0, czyli w jaki sposób zwiększyć ilość w trupie i jaką tam ilość podać. Ilość o ile zwiększamy, czy ilość dostępną po staremu czyli suma sprzedanych + dostępne ? i dlaczego każdorazowe wywołanie PUT na /sale/offers/ powoduje zwiększenie ilości sprzedanych, które widać w allegro.pl podczas wskrzeszania trupa ? Dlaczego w ogóle każde wywołanie PUT na /sale/offers/ zwiększa ilość a nie ustawia ilości do zadanej ?

**Comment by partyumarty** [comment]
Drążę dalej. Ta sama aukcja. 7425659768 jest dead. Wznawianie przez allegro.pl wskazuje -692 szt. 
Edytuję ją REST i podaję jako available -1000 szt - validation error ilość nie może być mniejsza od 0. 
Edytuję ją REST i podaję jako available 1000 szt - validation error ilość nie może być mniejsza od 0. 
Edytuję ją REST i podaję jako available 10000 szt - validation OK. 
Wchodzimy na allegro.pl przy próbie wznowienia liczba sztuk to... 8000. WTF ?
OK, wskrzeszam ją ACTIVATE przez REST. SUKCES. Ilość dostępna to 7988. Rozumiem 12 sprzedanych minus 8000 to 7988, ale skąd tam się wzięło 8000 szt ?
Bawimy się dalej. PUT na /sale/offers/ z AVAILABLE 20 szt. Ilość dostępna na aukcji to... 7572 szt. Wciskam EDYTUJ na allegro.pl - ilość szt to 7584 szt. 
Zabawa trwa. Edit na 100 szt przez webapi - niestety ERR_INVALID_QUANTITY. Edit na 333 szt przez webapi - ERR_INVALID_QUANTITY. Edit na 999 szt przez webapi - ERR_INVALID_QUANTITY.
Robię PUT z ilością AVAILABLE 5000 szt na sale/ofers. W aukcji ilość dostępna to 12552. Dlaczego przed chwilą było 7572. Dodaliśmy 5000 i zamiast 12572 mamy 12552 ? Co tak naprawdę nalezy podać w AVAILABLE w przypadku trupa z ilością sztuk wystawionych równą ilości sztuk sprzedanych czyli zakończona aukcja z powodu wyprzedania stoku ?

**Comment by partyumarty** [comment]
Nowy przykład: 7423907767 jest dead. Ręczne wznawianie ilość 1 szt. Wywołuję REST available 1 szt. Próba wznowienia przez REST i Could not change offer publication status. Próba ręcznego wznowienia przez Allegro.pl i mamy 2 szt, czyli ta 1 szt z rest dodała się i mamy już 2 szt, ALE... kiedy klikamy WZNÓW na allegro.pl znowu Niepoprawna liczba sztuk. Kiedy ręcznie wpisuję 3 szt - aukcja się wznawia. Dlaczego ? Odnoszę ponownie wrażenie, że... początkowo była 1 sztuka. Dodane przez REST 1 sztuka tak naprawdę jest traktowana jako sprzedana 1 sztuka, czyli że niby się sprzedały 2, dlatego jak wpisałem z palca 3 na allegr.pl to pozwolił mi ją wskrzesić. No i wskrzesił, ale z ilości dostępnych 2 sztuk, czyli wbrew mojej poprzedniej teorii. Dlaczego przy 2 sztukach nie pozwalał wznowić a przy 3 pozwolił ? Zatem aukcja wskrzeszona z palca. Edytujemy RESTEm i podajemy AVAILABLE 1 szt. Na aukcji ilość dostępna to nadal 2 sztuki. Kilka wdechów i edytujemy RESTEm i podajemy AVAILABLE 5 szt. Na aukcji ilość dostępna to 6 szt. Kilka wdechów i edytujemy RESTEm i podajemy AVAILABLE 3 szt. Na aukcji ilość dostępna to 4 szt. WTF ? Czy to oznacza, że ilość dostępna w aukcji to będzie suma która była dostępna w chwili zakończenia aukcji + ilość podana w available ? Innych wniosków z tej aukcji nie potrafię wyciągnąć. Natomiast pytanie brzmi: dlaczego ACTIVATE w rest nie pozwoliło mi jej wznowić mimo zwiększenia ilości ?

**Comment by PawelTaberski** [comment]
Sprawdziłem i rzeczywiście jest jakiś błąd, sprawę zgłosiłem do odpowiedniego zespołu proszę o cierpliwość.

**Comment by partyumarty** [comment]
Dzisiaj, dla odminy, aukcja któa miała 4 sztuki wystawione i 4 sztuki sprzedane czyli zakończyła się z powodu zerowego stanu pozwoliła się wyedytować. Tyle, że po wpisaniu w polu stock available 5 sumarycznie wyszło 9. Postępując na czuja zgodnie ze starymi zasadami z webapi wpisaliśmy analogicznie czyli nie ilość dostępną w danym zapytaniu tylko sumę ilości wystawionej, sprzedanej oraz tej do sprzedaży. Efekt jest inny. Czy to działanie celowe czy nadal bug. Mówiąc krótko czy podczas edytowania trupa przez /sale/offers/ ilość należy podawać tak samo jak w webapi czyli suma sprzedanych i do sprzedaży czy należy podać ilość dostępną od wznowienia ?

**Comment by PawelTaberski** [comment]
@partyumarty Po konsultacjach z z klientami z którymi omawialiśmy kwestie działania REST zdecydowaliśmy się na to drugie podejście. Obecnie nie musi Pan pamiętać ile było sztuk i dodawać dodatkowe. Od teraz jeśli chce Pan przykładowo mieć dostępnych 5 sztuk wystarczy, że przy zmianie poda Pan w stock 5.
