### ISSUE TITLE
"message":"An error has occurred" podczas zmiany statusu zamówienia

### ISSUE THREAD

**Issue by piotrkolodziejski** [allegro/allegro-api#3591]
Podczas zmiany statusu zamówienia pojawia mi się taki błąd:
 b'{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/order/checkout-forms/5ff39a51-e905-11ea-ba18-7bbaa97723a8/fulfillment","userMessage":null}]}'

Mój request wygląda tak:
{'method': 'PUT',
 'url': 'https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/5ff39a51-e905-11ea-ba18-7bbaa97723a8/fulfillment',
 'headers': {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/vnd.allegro.public.v1+json', 'Connection': 'keep-alive', 'Authorization': 'Bearer token', 'Content-Type': 'application/vnd.allegro.public.v1+json', 'Content-Length': '17'},

**Comment by piotrkolodziejski** [comment]
To dzieje się na sandboxie

**Comment by piotrkolodziejski** [comment]
A jeszcze nie dodałem body 

'body': 'status=PROCESSING',

**Comment by AureliuszBrussy** [comment]
Upewnij się, czy payload żądania jest odpowiednio sformatowany. Powinien on wyglądać następująco: 

```
{
     "status": "PROCESSING"              
}
```
