### ISSUE TITLE
"too many operations match search filter: 15,757 the maximum number of operations is: 10,000, please narrow search filter

### ISSUE THREAD

**Issue by LucasCichon** [allegro/allegro-api#3592]
Występuje problem: <"too many operations match search filter: 15,757 the maximum number of operations is: 10,000, please narrow search filter>
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 
Mam taki problem, ze podczas odpytania zasobu, dostaję odpowiedź o statusie 422 z takim komunikatem:
"too many operations match search filter: 15,757 the maximum number of operations is: 10,000, please narrow search filter.

request:
https://api.allegro.pl/payments/payment-operations?occurredAtgte=2020-04-28T23:59:99.000Z&offset=0

Używam aplikacji do pobierania transakcji finansowych. W aplikacji jest kilka kont. Niektóre działają poprawnie, a inne z kolei wysypują taki błąd.

POMOCY! :D

**Comment by PrzemyslawLukanowski** [comment]
Liczba wyników, które pasują do żądania jest zbyt duża. Musisz je zawęzić za pomocą innych dostępnych filtrów.

**Comment by PrzemyslawLukanowski** [comment]
Liczba wyników, które pasują do żądania jest zbyt duża. Musisz je zawęzić za pomocą innych dostępnych filtrów.

**Comment by LucasCichon** [comment]
Bardzo dziękuję. Okazało się że wpisanie dat zawężających z ręki nie przechodziło, jednak użycie w C# System.DateTime.UtcNow.ToString("o") zadziałało i filtr został zaakceptowany.
bardzo dziękuję za pomoc
