### ISSUE TITLE
/pricing/fee-preview - 503 - Service unavailable

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#3593]
Witam,

Problem z:

- RESTAPI
- Środowiskiem produkcyjny

requesty na zasób `/pricing/fee-preview` zwraca mi kod 503 podczas gdy `/pricing/offer-fee-preview` działa poprawnie.

Czy to błąd po stronie Allegro ? Kiedy można spodziewać się przywrócenia działania serwisu ?

**Comment by Bodzix** [comment]
Ok, okazało się, że pole type też jest obowiązkowe. Dokumentacja powinna zawierać wyszczególnioną taką informację oraz API powinno zwracać w tym przypadku 422. A przynajmniej tak mi się wydaje :)

**Comment by AureliuszBrussy** [comment]
Pole **type** jest opisane przez nas w [dokumentacji](https://developer.allegro.pl/documentation/#operation/previewFeesPublicAPIUsingPOST), gdzie znajduje się informacja o konieczności uzupełnienia tego pola. Dodatkowo jeżeli w polu **shop** przekażesz wartość **true** lub **false** - wtedy wartość w **type** uzupełniana jest automatycznie. Konieczność uzupełnienia tego pola wskazujemy również w [naszym poradniku](https://developer.allegro.pl/charges/#kalkulator-op%c5%82at) w przykładowym requeście.
