### ISSUE TITLE
Powiadomienia email po zmianie statusu zamówienia/dodaniu numeru listu przewozowego

### ISSUE THREAD

**Issue by geestaq** [allegro/allegro-api#3595]
Dzień dobry,
Czy po zmianie statusu/dodaniu numeru listu przewozowego przez REST api jest wysyłane powiadomienie email do kupującego?
Testuję na sandboxie i nie dostaję powiadomienia.
W panelu sprzedaży w zamówieniach mam ustawione wysłanie powiadomieni po zmianie statusu na Do wysyłki oraz automatyczną zmianę statusu na Wysłane po dodaniu numeru przesyłki.
Po zmianie statusu metodą: /order/checkout-forms/{id}/fulfillment
zmienia się status, ale powiadomienia brak
Po dodaniu numeru listu metodą: /order/checkout-forms/{id}/shipments
numer listu zostaje dodany, brak zmiany statusu na Wysłane i brak powiadomienia.
Przy wykonywaniu tych czynności w panelu sprzedaży powiadomienia przychodzą.

Jak wysłać powiadomienia dla kupującego?

**Comment by AureliuszBrussy** [comment]
Po dodaniu numeru przesyłki, niezależnie od tego czy numer przesyłki dodałeś poprzez API czy na stronie - powiadomienie e-mailowe z numerem przesyłki zostaje przez nas automatycznie wysłane. Sprawdziłem tą funkcjonalność i nie odnotowałem problemu z wysyłką powiadomień. Proszę sprawdź, czy powiadomienia nie trafiły na przykład do folderu spam.

**Comment by geestaq** [comment]
W spamie nie ma, ale zrobiłem testy teraz ponownie i działa. Nie wiem, może jakaś chwilowa awaria ;].
Co dziwne jak sprawdzałem przez weekend to powiadomienia nawet nie dochodziły nawet po zmianie w panelu.
Na tą chwilę wygląda ok. Dzięki za pomoc.
