### ISSUE TITLE
Status oferty pomiedzy ACITVE i ENDED

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3596]
Hej, metoda do publikacji jak i zamykania aukcji jest asynchroniczna. Podczas aktywacji oferty pomiędzy statusem **INACTIVE** a **ACTIVE** mamy status **ACTIVATING**. Czy istnieje również taki status dla zamykania aukcji pomiędzy statusem **ACTIVE** a **ENDED**?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie ma statusu pośredniego pomiędzy ACTIVE a ENDED.

**Comment by fjjjq** [comment]
Ok, dzięki.
