### ISSUE TITLE
konto użytkownika zostało zablokowane a symulator płatności nie działa 

### ISSUE THREAD

**Issue by patrycze** [allegro/allegro-api#3597]
Witam, chciałbym odblokować konto przez nieopłacone rachunki, natomiast wszystkie próby opłaty zostały odrzucone przez symulator płatności. Mój login to: patryniu 

Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by AureliuszBrussy** [comment]
Potwierdzam problem z symulatorem płatności za billing. Zgłosiłem już sprawę do odpowiedniego zespołu.

**Comment by patrycze** [comment]
A czy ze względu na niedziałający symulator płatności mogę prosić o odblokowanie konta???

**Comment by AureliuszBrussy** [comment]
Udało się ustalić, że symulator tylko częściowo nie funkcjonuje prawidłowo. Spróbuj opłacić rachunek korzystając np. z opcji "Szybka wpłata" -> "Płacę z Millennium". Pracujemy nad usunięciem problemu.

**Comment by AureliuszBrussy** [comment]
Problem nie powinien już występować.
