### ISSUE TITLE
Tecdoc zapytanie odnośnie bazy na Allegro

### ISSUE THREAD

**Issue by lmajgier** [allegro/allegro-api#3598]
Witam, 

Proszę o informację. 
Posiadam aplikację zintegrowaną z bazą tecdoc. 
Jaki numer z tecdoc danego produktu używa Allegro, abym mógł bez problemu połączyć swój produkt z tym w bazie Allegro?
Jakiej obecnie wersji tecdoc używa Allegro? 

Czy Allegro posiada w bazie wszystkie części zamienne, które obecnie występują w bazie tecdoc, mam na myśli części do samochodów osobowych.

Czy w przypadku gdy brak jakiejś części na Allegro, dodając ją musimy dodawać jakiś kod dzięki któremu zapiszecie produkt w bazie i w przyszłości bedzie można go użyć?

Co w przypadku gdy lista samochodów kompatybilnych będzie się różnić? czy możemy dodać brakujące samochody na aukcje?

**Comment by AureliuszBrussy** [comment]
W kategorii części samochodowe do łączenia oferty z produktem używamy pary parametrów: numer katalogowy + producent. Dodatkowo numer EAN w ofercie musi być zgodny z EANem produktu lub pusty (nie może być niezgodny).

Korzystamy z TecDoca w wersji 2019. W katalogu Allegro są wszystkie części zamienne z TecDoca przeznaczone na polski rynek.

Jeżeli chodzi o stworzenie produktu - jeśli uzupełniona zostanie w ofercie para numer katalogowy + producent to istnieje szansa że w przyszłości stworzymy produkt na podstawie tej oferty.

Z kolei jeśli produkt w katalogu Allegro pochodzi z bazy TecDoc i ma listę pasujących modeli, to podpinając produkt trzeba użyć tej listy, nie można jej usunąć, ani zmodyfikować. Jeśli produkt nie ma podpiętej listy kompatybilnych produktów, można do oferty podpiąć własną listę korzystając z katalogu pojazdów z TecDoc.

**Comment by lmajgier** [comment]
Dziękuje za odpowiedź.

Proszę mi powiedzieć jeszcze jedną rzecz.
Mamy pobrane kategorie produktów z tecdoca, czy w jakiś prosty sposób można je mapować z tymi z Allegro?

**Comment by AureliuszBrussy** [comment]
Niestety, ale nie ma prostego sposobu mapowania kategorii. Rozwiązanie pozostaje tu w Twojej gestii.

**Comment by lmajgier** [comment]
Rozumiem, 
proszę mi powiedzieć jedną rzecz, mam produkt o numerze ID - 46adaa72-824f-4d25-816d-7df0b59826ca
Allegro żąda od nas parametru rodzaj zawieszenia, 
Produkt jest u Państwa w bazie, nie możecie parametrów obowiązkowych podpiąć pod te produkty? 
Jedynie co mam w bazie tecdoc jako atrybuty to 

{
"Rodzaj amortyzatorów":"Ciśnienie oleju"
},
{
"Strona zabudowy":"Oś tylna"
},
{
"Strona zabudowy":"z lewej"
},
{
"Strona zabudowy":"z prawej"
},
{
"Typ amortyzatora":"Amortyzator teleskopowy"
},
{
"Typ amortyzatora":"amortyzator podtrzymujący sprężynę"
},
{
"Sposób mocowania amortyzatora":"górne oko"
},
{
"Sposób mocowania amortyzatora":"dolne oko"
},
{
"System tłumienia drgań zawieszenia":"dwururka"

skąd zatem w Allegro parametr o którym mowa? 
Skoro macie Państwo dane z tecdoca i takie dane podaje producent, to de facto z uproszczonego wystawiania robi nam sie robota ręczna, albo wybór pola 'brak informacji' bo nie jest zbyt profesjonale z naszej strony.

Mamy w swoim magazynie ponad 150,000 SKU, wszystkie dane z tecdoc a u Was mimo ze podpieliście tecdoc to wszystko się różni..

**Comment by PrzemyslawLukanowski** [comment]
Przenalizuję ten temat z odpowiednim zespołem i wrócę z odpowiedzią.

**Comment by lmajgier** [comment]
ok dziękuję

**Comment by PrzemyslawLukanowski** [comment]
@lmajgier Dodaliśmy ten parametr do produktu:

```
        {
            "id": "216493",
            "name": "Rodzaj zawieszenia",
            "valuesLabels": [
                "sportowe"
            ],
            "valuesIds": [
                "216493_274585"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
```

**Comment by lmajgier** [comment]
A skąd pobraliście Państwo ten atrybut - z tecdoca?

**Comment by PrzemyslawLukanowski** [comment]
Nie, w tec docu nie ma tej informacji, uzupełniliśmy to na podstawie innego specjalistycznego źródła.

**Comment by lmajgier** [comment]
Rozumie, 
pozwolę sobie wrócić do Państwa w momencie gdy sytuacja się powtórzy.

**Comment by lmajgier** [comment]
Panie Przemyslawie, 
cała kategoria tarcz hamulcowych ma obowiązkowy parametr strona zabudowy, w Państwa produktach brak uzupełnionej informacji. 

Druga sprawa, 
Tarcze hamulcowe w większości przypadków są sprzedawane w komplecie 2sztuk. 
Jak to jest rozwiązane na Allegro?
Widze, że większość sprzedawców dodaje po 1 sztuce, lecz w opisie dodają informację, że należy zakupić dwie, co jest absurdem w mojej ocenie, bo wiem, że ludzie nie czytają opisów.

Czy wystarczy że dodam sobie do tytułu kpl. podwyższę cenę i po sprawie?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pierwszego problemu może Pan podać ID produktów, dla których chce Pan, abyśmy uzupełnili tę informację. 
W drugim przypadku prosiłbym o kontakt przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), ponieważ nie jest to pytanie powiązane z problemami technicznymi API.

**Comment by lmajgier** [comment]
Panie Przemku to jest problem po stronie API.
Ten sam kod kreskowy widnieje dla produktów które pakowane są x2, ten sam kod kreskowy dodawany jest dla 1 sztuki produktu, tutaj obsługa allegro nic nie pomoże..

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem wyrywkowo oferty z kategorii Tarcze hamulcowe, jednak widzę, że w większości przypadków jest to rozwiązane prawidłowo - przedmiotem sprzedaży jest zestaw tarcz, czyli x2. Zgodnie z podpiętym produktem.

**Comment by lmajgier** [comment]
Może mi Pan wysłać przykład?

**Comment by PrzemyslawLukanowski** [comment]
Proszę, poniżej:

[4905202392 ](https://allegro.pl/oferta/tarcze-klocki-lozyska-tyl-tylne-audi-a4-b5-hit-4905202392)
[9576187909](https://allegro.pl/oferta/rotinger-gt-20344-gl-t5-tarcze-przod-bmw-e60-e61-9576187909)
[6726701674 ](https://allegro.pl/oferta/tarcze-x2-klocki-tyl-do-audi-a4-b6-b7-seat-exeo-6726701674)
[6726650581](https://allegro.pl/oferta/tarcze-klocki-przod-ford-mondeo-iii-mk3-2000-6726650581) 
[8459678010](https://allegro.pl/oferta/mini-cooper-one-r50-r53-tarcze-zimmermann-sport-8459678010)

**Comment by lmajgier** [comment]
Panie Przemyslawie, ok rozumiem jak mam to zrobić, ale pojawia sie kolejny problem

TC747 - proszę zerknąć na dane Państwa które macie zapisane w systemie. 

Specyfikacja techniczna produktu
Wysokość [mm]:83,2
Wymiar gwintu:M14x1.25
Rozmiar gwintu 3:M14x1.25
Szerokość [mm]:82,9
Długość [mm]:107,7
Typy referencyjne:wymienialny
Wersja TecDoc:2019 

W sierpiniu dane zostaly zmienione 
Wymiar gwintu: M14x1.25
Rozmiar gwintu 3: M14x1.25
Długość [mm]: 108
Szerokość [mm]: 83
Wysokość [mm]: 83
te są poprawne, co w takim przypadku? 
W specyfikacji produktu bede miał inne dane niżli w szablonie, mam podpiety tecdoc świeży, co jaki czas Państwa robicie aktualizację danych?

**Comment by PrzemyslawLukanowski** [comment]
W tej sytuacji może Pan zgłosić błąd w produkcie w [formularzu wystawiania](https://allegro.pl/dla-sprzedajacych/jak-zaktualizowac-lub-zmienic-dane-produktu-ZGZG89WkOU0) lub podać ID tego produktu - przekażę wtedy zgłoszenie do odpowiedniego zespołu. Dane produktów staramy się aktualizować na bieżąco, uzupełniamy brakujące parametry, a także edytujemy istniejące.

**Comment by lmajgier** [comment]
Witam

Czy możecie Państwo ogarnąć produkty w kategorii tarcze hamulcowe?
Probuje wystawić 10 produkt pod rząd i ciągle pokazuję mi komunikat aby podać stornę zabudowa która jest niby wymagana a wszyscy inni sprzedawcy jej nie maja.

**Comment by MaciejFrackowiak** [comment]
Parametr "Strona zabudowy" [id=127636] jest parametrem obowiązkowym - zarówno w API, jak i na formularzu wystawiania dla kategorii 250406.

**Comment by lmajgier** [comment]
Oczywiście, że jest, tylko nie rozumie Pan jednej kwestii, dodajecie produkty na bazie tecdoca, tak aby mozna było się łączyć. 
W momencie podpięcia się pod produkty tarcz hamulcowych WASZE uzupełnienie produktów nie jest pełne I NIE MA W NICH STRONY ZABUDOWY. Tu jest problem.
Proszę zatem abyście Panstwo to uzupełnili, czy możecie?

**Comment by lmajgier** [comment]
Ps. Jak to jest możliwe, że dodajecie produkt który sami tworzycie z tecdoca, a następnie dodajecie parametr który jest obowiązkowy nie zmieniając danych w produktach już dodanych? :o

**Comment by MaciejFrackowiak** [comment]
Nie możemy dowolnie edytować produktów już istniejących - są one podpięte pod oferty Sprzedających, zatem każdy Sprzedający musi mieć możliwość zweryfikowania czy produkt, który sprzedaje jest zgodny z produktem z bazy. Sprzwdziłem losowe produkty dot. tarcz hamulcowych i miały one parametr strona zabudowy. Jeżeli masz konkretne typy produktów, które nie mają tej wartości możesz je zgłosić poprzez [formularz zgłaszania błędów](https://allegro.pl/dla-sprzedajacych/jak-zaktualizowac-lub-zmienic-dane-produktu-ZGZG89WkOU0).

**Comment by lmajgier** [comment]
Mogę Ci wysłać 10,000 SKU dodacie do nich wtedy parametr?

**Comment by AureliuszBrussy** [comment]
Tak, prześlij proszę listę poprzez [ten formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), w zgłoszeniu dopisz proszę numer wątku na GitHubie:  #3598. Zgłoszę tą listę do odpowiedniego zespołu, natomiast w tym przypadku zaznaczę, że wprowadzanie takich zmian może potrwać pewien czas.
