### ISSUE TITLE
Rozbieżność w statusie zamówienia

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#3599]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, mam problem z przetwarzaniem zamówienia o id **5091dc84-e193-11ea-8b1b-fbd59b0adbd6**.
Z eventów które odczytałem z event loga pojawił się tam tylko wpis o typie **BOUGHT**, natomiast pobierając stan tego zamówienia przez api jest ono w statusie **FILLED_IN**. Co ciekawe wchodząc do tego zamówienia przez
 panel allegro.pl jest tam informacja o płatności, są dane do dostawy i faktury, których nie ma dostępnych przez resta. Wychodzi na to, że jest ono w statusie **READY_FOR_PROCESSING**.

Proszę o szybką informację, czy te eventy pojawią się do pobrania i czy dla tego zamówienia będzie możliwość pobrania danych dostawy i faktury przez api. Pytam dlatego ponieważ chce uniknąć duplikatów kiedy zamówienie jednak trafi poprawnie do event loga.

**Comment by AureliuszBrussy** [comment]
Potwierdzam rozbieżność. Zgłosiłem już problem do odpowiedniego zespołu. Wrócę z informacją.

**Comment by manhunto** [comment]
@AureliuszBrussy Dziękuję, czekam w takim razie na odpowiedź.

**Comment by AureliuszBrussy** [comment]
@manhunto dane w zamówieniu zostały uspójnione. Przepraszamy za niedogodność.

**Comment by manhunto** [comment]
@AureliuszBrussy Potwierdzam, zamówienie już zostało u nas przetworzone. Dziękuję :+1:
