### ISSUE TITLE
Pięciominutowe opóźnienie dziennika.

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#36]
Od prawie roku jest ustawione sztywne 5 minutowe opóźnienie dziennika zdarzeń, kiedy je zlikwidujecie?

**Comment by LukaszKorek** [comment]
Dzień dobry. Przeanalizowaliśmy temat. Próbowaliśmy wielu podejść. Niestety, ilość danych, które musimy przetworzyć i zweryfikować, by zapewnić ich spójność - nie tylko w API, ale też na froncie- nie pozwala nam zmniejszyć czasu opóźnienia.

**Comment by dfranczuk** [comment]
Czy w RestAPI planowane jest jakieś wsparcie dziennika by działał lepiej np. przerobienie go na notyfikacja tak jak np. w Ebay?

**Comment by LukaszKorek** [comment]
Tutaj sytuacja jest analogiczna do tej powyżej przeze mnie opisanej czyli "Niestety, ilość danych, które musimy przetworzyć i zweryfikować, by zapewnić ich spójność - nie tylko w API, ale też na froncie- nie pozwala nam zmniejszyć czasu opóźnienia.".
