### ISSUE TITLE
doGetPostBuyFormsDataForSellers - Formularz bez informacji o zakupionych przedmiotach

### ISSUE THREAD

**Issue by Krasiu** [allegro/allegro-api#360]
![image](https://user-images.githubusercontent.com/12200435/42128025-dfdb19c2-7ca2-11e8-99a1-6126720fa6a9.png)

Nie wiem, które informacje mam podać żebyście byli w stanie zidentyfikować błąd, ale metoda `doGetPostBuyFormsDataForSellers` od paru dni zaczęła czasami zwracać płatności, gdzie tablica zakupionych przedmiotów jest pusta.

**Comment by PawelTaberski** [comment]
Prosiłbym o podesłanie przykładowego identyfikatora transakcji w którym występuje błąd w formacie XML. Przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=7e8e35b6-d773-4a0a-8d38-c056148165e8), a następnie wklejenie tutaj numeru ticketa.
