### ISSUE TITLE
Nie działają płatności na sandboxie

### ISSUE THREAD

**Issue by piotrkolodziejski** [allegro/allegro-api#3600]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,
dzisiaj przesytały działać płatności, tzn wystawiam produkt i przechodzę do płatności i po wyborze blika bardzo długo pojawia się ikonka płatności a payu przechodzi i pokazuje, że płatność jest rozpoczęta a nie ma opłacono, prośba o pomoc.

**Comment by piotrkolodziejski** [comment]
już działa

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - aktualnie symulator płatności działa prawidłowo.
