### ISSUE TITLE
Obiekty dictionary parametrów zwracają nieprzewidywalne id

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3602]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,

mam pewien problem z pobieranymi parametrami kategorii. Otóż pobieram i zapisuje parametry, oraz osobno ich wartości dictionary. Dotychczas korzystałem z tego tak, że wartość `id` z dictionary składała się z id parametru oraz wartości danej opcji np. `129269_374033`. Od niedawna obserwuję jednak, że do parametrów trafiają dictionary z nieprzewidywalnymi `id`.
Dla przykładu, fragment odpowiedzi z kategorii `306837`:

`
{
            "id": "129269",
            "name": "Rodzaj",
            "type": "dictionary",
            "required": false,
            "requiredForProduct": false,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": "229545_341817",
                "dependsOnParameterId": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "129269_374033",
                    "value": "bidony i butelki",
                    "dependsOnValueIds": []
                },
                {
                    "id": "229545_341793",
                    "value": "śniadaniowe (lunch box)",
                    "dependsOnValueIds": []
                },
                {
                    "id": "229545_341817",
                    "value": "inny",
                    "dependsOnValueIds": []
                }
`

Jak widać, `id` z obiektów dictionary raz zawierają id parametru, a w niektórych wypadkach jest jakiś inny tj. `229545`. Czy to jest właściwe zachowanie REST API, czy jednak występuje tu jakiś błąd i REST zwraca nieprawidłowe ID z jakiegoś powodu?

Według mnie REST powinien zwrócić wartości dictionary: 129269_374033, 129269_341793, 129269_341817...

**Comment by AureliuszBrussy** [comment]
Jest to prawidłowe zachowanie REST API Allegro. Dzieje się tak ze względu na scalenie parametrów i ich wartości, o czym informowaliśmy w [newsie](https://github.com/allegro/allegro-api/issues/2160), stąd też identyfikator parametru nie zawsze będzie częścią składową identyfikatora wartości tego parametru.

**Comment by hahyes** [comment]
> Jest to prawidłowe zachowanie REST API Allegro. Dzieje się tak ze względu na scalenie parametrów i ich wartości, o czym informowaliśmy w [newsie](https://github.com/allegro/allegro-api/issues/2160), stąd też identyfikator parametru nie zawsze będzie częścią składową identyfikatora wartości tego parametru.

Czyli przestało działać, bo minął rok od zmiany i przestaliście wspierać parametry według starych id. Zrozumiałe.

Dziękuję za odpowiedź.
