### ISSUE TITLE
Lista zamówień GET /order/checkout-forms

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#3603]
Witam nie znalazłem nigdzie informacji o tym ale czy planujecie w zasobie GET /order/checkout-forms udostęnić możliwość szukania zamówień po danych kupującego? Obecnie mamy możliwość szukania po id płatności, id dopłaty, loginie allegro, metodzie dostawy, nie zawsze to wystarczy by znaleźć konkretne zamówienie ponieważ klient nie poda id płatności, id dopłaty czy nawet swojego loginu/nicku na allegro (nowe konta gdy użytkownik nie nada swojego loginu mają go automatycznie uzupełniany według wzoru "Client:xxxxxxxx" a Ci klienci bez rejestracji mają jeszcze inaczej :) ).

Zazwyczaj gdy klient dzwoni i mówi, że za drugie zamówienie zrobił dopłatę w poprzednim i che by oba były wysłane jednocześnie to nie podaje w/w parametrów tylko imię i nazwisko.

**Comment by AureliuszBrussy** [comment]
W API Allegro nie ma możliwości wyszukiwania zamówienia po takich danych jak imię i/lub nazwisko. Na tę chwilę nie planujemy takiej funkcjonalności. Sugestię dopisałem do naszej listy.

**Comment by mlonc** [comment]
Czy jakaś decyzja zapadła? Kiedy można spodziewać się realizacji tematu?

**Comment by AureliuszBrussy** [comment]
Aktualnie nie planujemy wprowadzenia takiej funkcjonalności. Jeżeli coś się zmieni w tej kwestii - poinformujemy o tym.
