### ISSUE TITLE
jak usunąć numer nadania przesyłki z zamówienia?

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#3604]

**Comment by AureliuszBrussy** [comment]
Nie ma możliwości usunięcia dodanego do zamówienia numeru przesyłki w Allegro REST API. Możesz jednak to zrobić z poziomu zakładki [Zamówienia](https://allegro.pl/moje-allegro/sprzedaz/zamowienia). Skorzystaj z akcji “Numery przesyłek” przy konkretnym zamówieniu . Pojawi się tam opcja “Usuń”.
