### ISSUE TITLE
Co dokładnie zwraca pole "publication" w endpoincie /offers/listing?

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3605]
Dzień dobry,
2 pytania:
1. Co dokładnie zwraca pole "publication" w endpoincie /offers/listing?
2. W waszej dokumentacji jest przykład response:
![image](https://user-images.githubusercontent.com/26189632/91981672-79bb9500-ed29-11ea-8927-354f2b878254.png)
Czy jest to data zakończenia cyklu 10, 30 dni? Jak to wygląda?

Z góry dziękuję za odpowiedź!

**Comment by AureliuszBrussy** [comment]
W polu **publication.endingAt** pokazujemy datę zakończenia oferty, pod warunkiem, że oferta została wystawiona na czas określony. Aktualnie jest to jedyna informacja, którą zwraca ten obiekt.
