### ISSUE TITLE
Jak pobrać datę rozpoczęcia oferty

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3606]
Dzień dobry,
jak pobrać datę rozpoczęcia oferty, której nie jestem właścicielem, z REST API?

**Comment by AureliuszBrussy** [comment]
W REST API Allegro nie pobierzesz daty rozpoczęcia oferty nie będąc jej właścicielem. Możesz jedynie przefiltrować oferty według czasu dodania, korzystając z filtra **-startTime** na zasobie [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).
