### ISSUE TITLE
An error has occurred w order/event-stats

### ISSUE THREAD

**Issue by keriooof** [allegro/allegro-api#3608]
Witam,

przy prostym zapytaniu trzymuję taki błąd: {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}

kod:
<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}

$t=getAccessToken();
//https://developer.allegro.pl/orders/

  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  

	
?>

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
`<?php
	
	function getAccessToken(): String
{
     $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials";
   $clientId = "";
    $clientSecret = "";
    

    $ch = curl_init($authUrl);

    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERNAME, $clientId);
    curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $tokenObject = json_decode($tokenResult);

    return $tokenObject->access_token;
}


$t=getAccessToken();
//https://developer.allegro.pl/orders/






  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.allegro.pl/order/event-stats",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_POSTFIELDS => "",
    CURLOPT_HTTPHEADER => array(
      "Accept: application/vnd.allegro.public.v1+json",
      "Authorization: Bearer $t",
      "Content-Type: application/vnd.allegro.public.v1+json"
    ),
  ));
  
  $response = curl_exec($curl);
  $err = curl_error($curl);
  
  curl_close($curl);
  
  if ($err) {
    echo "cURL Error #:" . $err;
  } else {
    echo $response.'323';
  }  


	
?>
`

**Comment by keriooof** [comment]
proszę o pomoc

**Comment by TimothyKoval** [comment]
Usuń

```
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($ch, CURLOPT_USERNAME, $clientId);
curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
```

**Comment by keriooof** [comment]
nawet gdy cała pierwsza część kodu usunę i podam token "recznie" w "Authorization: Bearer $t", to dostaje {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":null,"userMessage":null}]}

**Comment by TimothyKoval** [comment]
Dodaj `curl_setopt($ch, CURLINFO_HEADER_OUT, true);` a po curl_exec `$info = curl_getinfo($ch); var_dump($info["request_header"]);` - będziesz mógł przeanalizować wysyłane nagłówki

**Comment by keriooof** [comment]
kurcze, nic nadzwyczajnego: string(1380) "GET /order/event-stats HTTP/1.1 Host: api.allegro.pl Accept-Encoding: deflate, gzip, br Accept: application/vnd.allegro.public.v1+json Authorization: Bearer {token} Content-Type: application/vnd.allegro.public.v1+json Content-Length: 0 "

**Comment by keriooof** [comment]
chyba ze aplikacja musi byc dodana do https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje
lecz czytalem, że jeżeli pobieramy token   $authUrl = "https://allegro.pl/auth/oauth/token?grant_type=client_credentials"; 
to nie trzeba autoryzować dodatkowo aplikacji?

**Comment by keriooof** [comment]
najlepsze jest to, że jeśli odpytuję https://api.allegro.pl/offers/listing?seller.id={id} to pokazuje oferty i w zasadzie nic innego nie działa

**Comment by TimothyKoval** [comment]
/order/event-stats to nie jest publiczny zasób, musisz skorzystać z autoryzacji użytkownika.

**Comment by keriooof** [comment]
dziękuje, wszystko okej, a wystarczyłby komunikat "brak dostępu" ;)
