### ISSUE TITLE
Problem z tokenem przy wystawianiu wielu ofert 

### ISSUE THREAD

**Issue by Aleksandra-Janczak** [allegro/allegro-api#3609]
Użytkownik wystawiając zbiorczo oferty otrzymuje w przypadkowych miejscach błąd 401. 
Dzieje się to bez uprzedzenia, dotyczy tokenu, który przy kilkudziesięciu poprzednio wystawionych aukcjach był poprawny, następne oferty z listy też przechodzą prawidłowo przez chwilę, po czym cykl się powtarza a po kilku takich cyklach występuje już odmowa dla każdej próby wystawienia aukcji. Przy ponownej próbie wystawienia uprzednio odrzuconych ofert, błąd nie występuje, co upewnia nas, że parametry są ustawione prawidłowo. Podczas próby wystawiania tego samego zestawu ofert z innego miejsca w sieci, problemu nie udało się powtórzyć, przy czym z innego komputera wystawianie idzie wolniej i trwa dłużej. Czy możliwe jest aby  faktycznym problemem była nadmierna prędkość komputera lub nadmierna przepustowość sieciowego i program wysyłający żądania do API powinien sztucznie spowalniać proces czyli wymuszać czekanie po każdej wystawionej aukcji?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę przykładowy request i response w formacie curl poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), abyśmy mogli to przeanalizować. W treści podaj numer zgłoszenia na GitHubie - #3609.
