### ISSUE TITLE
RestAPI PUT - limit wielkości payload

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#361]
Cześć,
próbowałem właśnie zmienić cennik dostawy na 70 tyś aukcji.
Pojedynczy request PUT (/sale/offer-modification-commands/DEFE3338-1B0D-4F9A-B9A0-805BBFDC7A4E).

Na 5 tyś aukcji poszło bez problemu, przy 70 tyś serwer allegro rozłącza połączenie.

Jaki jest limit wielkości payload i czy ewentualnie możecie go zwiększyć ?

**Comment by PawelTaberski** [comment]
Problemem tutaj nie jest wielkość requesta a ustawione timeout-y, możliwe że występuje jakiś problem z Twoim łączem. Rozważymy wydłużenie tych czasów.

**Comment by sis6326r** [comment]
Z łączem wszystko ok. Teraz zadziałało. Dzięki i pozdrawiam.
