### ISSUE TITLE
Nieprawidłowa liczba sztuk

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3610]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o sprawdzenie błędu. Poniżej request i response w wersji skróconej wraz z traceId (zmiana ilości)
Dzieje się tak tylko dla jednej oferty

Request:
{"Zlecenie":{"Nr":"b5727846-ed10-408d-b900-3fc5f1aafa44","Operacja":{"Modification":{"ChangeType":"FIXED","Value":3},"OfferCriteria":[{"Type":"CONTAINS_OFFERS","Offers":[{"Id":"7904539686"}]}]},"Response":{"Data":{"Id":"b5727846-ed10-408d-b900-3fc5f1aafa44","TaskCount":{"Failed":0,"Success":0,"Total":0}},"Validation":null,"Exception":null,"TraceId":"141488f577076972","Error":false,"StatusCode":201,"Message":null}}}

Response:
{"RaportZlecenia":{"Nr":"b5727846-ed10-408d-b900-3fc5f1aafa44","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-09-03T09:41:51.296Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"7904539686"},"ScheduledAt":"2020-09-03T09:41:50.578Z","Status":"FAIL","Errors":[{"Code":"ERR_INVALID_QUANTITY","Details":null,"Message":"ERR_INVALID_QUANTITY","Path":null,"UserMessage":"Nieprawidłowa liczba sztuk."}]}]},"Validation":null,"Exception":null,"TraceId":"2e53002acf1f5370","Error":false,"StatusCode":200,"Message":null}}}

**Comment by AureliuszBrussy** [comment]
Zgłosiłem już ten problem do odpowiedniego zespołu.

**Comment by AureliuszBrussy** [comment]
Dla wskazanej oferty problem nie powinien już występować.

**Comment by SebastianOzdoba** [comment]
Dziękuję, sprawdzamy
