### ISSUE TITLE
PUT /offers/{offerId}/change-price-commands/{commandId} - a status?

### ISSUE THREAD

**Issue by M4GiK** [allegro/allegro-api#3611]
Występuje problem:

* [X] z zasobem REST API
 * [X]  ze środowiskiem produkcyjnym
 * [ ]  ze środowiskiem testowym
* [ ]  z logowaniem lub autoryzacją
 * [ ]  na portalu https://developer.allegro.pl/
 * [ ]  inny

Podczas wywołania metodą PUT/offers/{offerId}/change-price-commands/{commandId} dostaję zwrot statusu VALIDATED_AND_RUNNING.
Pomijając że w dokumentacji nie ma takiego statusu, to pytanie brzmi jak sprawdzić czy cena się zmieniła?
Metodą GET /sale/offer-publication-commands/{commandId} niestety nie idzie tego sprawdzić.

**Comment by AureliuszBrussy** [comment]
Status komendy sprawdzisz korzystając z [GET /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandStatusUsingGET) lub [GET /sale/offer-price-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET).

**Comment by M4GiK** [comment]
Nic dziwnego, że nie mogłem znaleźć metody. Dokumentacja swagger.yaml jest przestarzała... 
Dziękuję za pomoc.

**Comment by M4GiK** [comment]
Jednak nie do końca, w opisie dotyczy że ta metoda służy do "Batch offer price modification".

**Comment by AureliuszBrussy** [comment]
Przepraszam za pomyłkę - faktycznie w przypadku PUT /offers/**{offerId}**/change-price-commands/{commandId}, czyli komendy zmiany ceny w pojedynczej ofercie - nie ma możliwości sprawdzenia statusu komendy. Był to pierwszy zasób jaki udostępniliśmy na REST API. Sugeruję, abyś korzystał z zasobu [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT), nawet dla zmiany ceny w pojedynczej ofercie.

**Comment by M4GiK** [comment]
Można o szczegółowe informacje kodu błędu jak już jesteśmy w temacie:
- {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-price-change-commands/5fd9010f-75e5-4ea8-ae43-9815d6ae0d67","userMessage":null}]}

**Comment by AureliuszBrussy** [comment]
W polu modification.type przekazałeś niepoprawną wartość - "PriceModificationFixedPrice". Dozwolona wartość w tym przypadku to FIXED_PRICE.

**Comment by M4GiK** [comment]
Prosiłbym o podanie listy dostępnych statusów dla metody GET/sale/offer-price-change-commands/{commandId}/tasks.
Nie jestem pewny czy dobrze patrzę ale nie jestem w stanie odszukać informacji na ten temat w dokumentacji.

**Comment by PrzemyslawLukanowski** [comment]
@M4GiK dostępne statusy to NEW, SUCCESS i FAIL.
