### ISSUE TITLE
Problem: NIE MOŻNA WYŚWIETLIĆ STRONY

### ISSUE THREAD

**Issue by galaktyka56** [allegro/allegro-api#3612]
Witam.
Współpracuję z sky shopem i gdy aktualizuję konto ARUUMS z poziomu programu przekierowywuje mnie do allegro i wyskakuje taki błąd:

Nie możemy wyświetlić strony
Numer błędu: 748cbbb83d37512d

O co chodzi?

**Comment by AureliuszBrussy** [comment]
Problem występuje prawdopodobnie podczas uwierzytelniania dlatego, że adres przekierowania podany [podczas rejestrowania aplikacji na naszej stronie](https://apps.developer.allegro.pl/) nie jest zgodny z adresem przekierowania, który podany jest w aplikacji (redirect_uri). Sprawdź poprawność tych adresów.
