### ISSUE TITLE
Zamówienia a email kupującego

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3613]
Pobierając dane na temat zamówienia nie otrzymuje prawdziwego emaila kupującego którego podawałem przy zakupie, a coś na zasadzie "n5z9ungq4v+5f147aa75@user.allegrogroup.pl" nie podajecie jawnie maila użytkownika? Czy email jest unikatowy i powiązany z kontem Allegro? Pisząc na ten mail mogę skontaktować się z użytkownikiem?

**Comment by mlonc** [comment]
to jest zaszyfrowany mail i składa się z 2 części -> nick kupującego i chyba id oferty i tak pisząc na tego maila kupujący dostanie go na własną skrzynkę pocztową i dodatkowo będzie go mógł odczytać w oknie czatu po stronie allegro

**Comment by fjjjq** [comment]
Właśnie to zweryfikowałem i faktycznie mogę skontaktować się przez ten email. Jeżeli jest tak jak mówisz email będzie różny w przypadku tego samego użytkownika i rożnych ofert co powoduje że jestem zmuszony zapisywać ID użytkowników w bazie w swoim systemie bo po emailu nie można ich identyfikować.

**Comment by mlonc** [comment]
Pierwsza część(ta przed plusem) powinna być taka sama poza tym mail to słaba opcja identyfikacji(użytkownik może go zmienić :))

**Comment by AureliuszBrussy** [comment]
Zgadza się, nie podajemy jawnie adresu e-mailowego użytkownika. W [tym artykule](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL) opisujemy jak wyglądają adresy w ramach korespondencji Allegro. Tego samego kupującego możesz łatwo zidentyfikować, ponieważ pierwszy człon w adresie zawsze jest taki sam i odnosi się bezpośrednio do adresu e-mail użytkownika. Drugi człon z kolei identyfikuje transakcje.

**Comment by fjjjq** [comment]
Dobrze, co się stanie jeżeli wiadomości do użytkownika będę wysyłał na tylko jeden email (np. wygenerowany przy pierwszym zamowieniu). Bo widzę że po stronie allegro nie ma osobnych korespondencji do zamówień. Czy ten email kiedyś wygaśnie? Czy będą z tego powodu jakieś negatywne skutki? Chciałbym zapisać użytkownikowi u siebie w systemie tylko jeden email.

**Comment by fjjjq** [comment]
Widzę że jest jeszcze inaczej, mogę obciąć część związaną z identyfikatorem zamówienia i wiadomość wciąż dochodzi do użytkownika.

**Comment by AureliuszBrussy** [comment]
Tak, możesz usunąć drugą część adresu, wiadomość wciąż dotrze do adresata. Maskowane adresy e-mail nie mają daty ważności - są bezterminowe. Pamiętaj jednak, że przy obsłudze zamówień powinieneś korzystać z adresów przypisanych do konkretnego zamówienia, a nie traktować jako stały wpis do swojej bazy - nie będzie to zgodne z założeniami w kontekście wykorzystania danych transakcyjnych. Dodatkowo jest to ważne ze względu na mechanizmy związane z naszą integracją z przewoźnikami, np. na [automatyczne uzupełnianie](https://allegro.pl/dla-sprzedajacych/dodawaj-numery-przesylek-do-zamowien-Lvo3k6DWnIx) przez przewoźników numerów przesyłek, czy też choćby ze względu na rozpoznawanie zamówienia Smart na podstawie tego unikatowego adresu e-mail.

**Comment by fjjjq** [comment]
Dziękuję za pomoc.
