### ISSUE TITLE
Korespondencja z klientem przez skrzynkę pocztową

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3614]
Czy jest w systemie jakaś opcja która umożliwia korespondencje za pośrednictwem wyłącznie maili? Przykładowo widzę, że w sytuacji gdy użytkownik odpisze sprzedawcy w systemie Allegro to sprzedawca dostaje tylko powiadomienie o wiadomości oczekującej w Allegro. Nie może na nią bezpośrednio odpisać z poziomu skrzynki. Czy można zmienić jakoś to ustawienie tak aby korespondencja zachodziła pomiędzy mailami użytkowników a nie powiadomienia@allegro.pl?

**Comment by AureliuszBrussy** [comment]
Wszystkie wiadomości w ramach Centrum Wiadomości przesyłane są także na skrzynkę e-mailową adresata. W przyszłości planujemy udostępnienie obsługi Centrum Wiadomości w REST API.

**Comment by dark774** [comment]
Czy jest możliwe że jeszcze w tym roku udostępnicie taki zasób w REST API?

**Comment by MaciejFrackowiak** [comment]
@dark774 Jest taka szansa, jednak na chwilę obecną nie mogę jednoznacznie potwierdzić ewentualnej daty wdrożenia tej funkcjonalności. Oczywiście pojawi się news informujący o nowym rozwiązaniu.

**Comment by shivson1337** [comment]
@MaciejFrackowiak a co w przypadku sklepów obsługujących zgłoszenia przez systemy ticketowe? Na ten moment, każda wiadomość od klienta wysyłana jest w taki sposób, że z automatu zakłada nowe zgłoszenia. Prowadzenie korespondencji w ten sposób mija się z celem.

Metody do obsługi tego przez REST API wydają się na ten moment kluczowe dla zapewnienia sprawnej obsługi klientów.

**Comment by MaciejFrackowiak** [comment]
@shivson1337 Jak wspomniał @AureliuszBrussy - w przyszłości planujemy udostępnienie obsługi Centrum Wiadomości w REST API. Niestety, na chwilę obecną to jest jedyna pewna informacja, którą możemy przekazać.

**Comment by dark774** [comment]
@MaciejFrackowiak @MartaNowaczyk Jak wygląda sytuacja z API do obsługi centrum wiadomości? Jesteście stanie podać jakiś przybliżony okres kiedy udostępnicie to API?

**Comment by MaciejFrackowiak** [comment]
@dark774 Niestety, precyzyjnego terminu nie mogę wskazać - mamy to jednak "na tapecie". Oczywiście wraz z wdrożeniem zasobów zamieścimy osobny komunikat.

**Comment by daniel8702** [comment]
@MaciejFrackowiak Podpinam się do pytania @dark774, a mogli byście powiedzieć coś więcej? 
Bardziej przyszły rok dopiero, czy jeszcze w tym planujecie? Pod koniec? w połowie roku? 

Była by to naprawdę świetna funkcjonalność :heart:

**Comment by MaciejFrackowiak** [comment]
@daniel8702 Nie chcę obiecywać, dlatego nie wskazuję konkretnego terminu obecnie. Jest to jednak na liście oczekiwanych funkcjonalności.
