### ISSUE TITLE
Masowa zmian cen 

### ISSUE THREAD

**Issue by lmajgier** [allegro/allegro-api#3615]
Dzień Dobry, 

Czy nie ma innej możliwości niżeli opisana tutaj dot. zmiany cen

https://developer.allegro.pl/my_offers/#cena

Codziennie zmieniamy cenę dla 20,000 - 40,000 produktów, czasami i dla większej liczby.
Z tego co tutaj czytam
https://developer.allegro.pl/my_offers/#cena

Musimy kolejkować zmianę dla każdego produktu z osobna, nie można tego wysłać w paczkach po 1000 produktów na raz?

**Comment by lmajgier** [comment]
Tak samo tyczy się to zmiany ilości na aukcjach.

**Comment by SebastianOzdoba** [comment]
@imajgier nie ma innej możliwości tylko zgodnie z tym opisem powyżej

**Comment by AureliuszBrussy** [comment]
@lmajgier nie, nie ma innej możliwości masowej zmiany cen i liczby sztuk w ofertach. W pojedynczej komendzie możesz podać tylko jedną regułę modyfikacji oraz możesz podać listę z id maksymalnie 1000 ofert w której zmiana ta ma zostać wykonana.
