### ISSUE TITLE
zwrot prowizji

### ISSUE THREAD

**Issue by fjn-6666** [allegro/allegro-api#3616]
Cześć.

Czy API wspiera zwrot prowizji？

**Comment by AureliuszBrussy** [comment]
Tak, Allegro REST API wspiera zwrot prowizji, dostępne zasoby opisaliśmy w [dokumentacji](https://developer.allegro.pl/documentation/#tag/Commission-refunds). Informacje, jak korzystać z tych zasobów znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/#rabaty-transakcyjne-zwroty-prowizji).
