### ISSUE TITLE
Generowanie paczki Wysyłam z Allegro Sandbox

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3617]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mam problem ze środowiskiem testowym Wysyłam z Allegro. Próbuję przetestować tworzenie paczek  UPS do 10kg (testowane też na żabka i fedex z umową własną).  Z poziomu API mam błąd :
{"id":"eb34f2df-0cab-4849-8082-815576fb7efb","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"}]}
Natomiast na stronie :
![image](https://user-images.githubusercontent.com/49162881/92229820-5bc96e00-eeaa-11ea-9f26-cec00c800d24.png)

**Comment by AureliuszBrussy** [comment]
Problem dotyczy pola “referenceNumber” - przekazujesz w nim niedozwolony znak “:”. Sukcesywnie będziemy dodawać odpowiednie komunikaty wskazujące tego typu błędy.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pierwszego problemu przekazaliśmy ten problem do dalszej weryfikacji. Co do Allegro Pocztex Kurier 48 - nasze umowy nie obsluguja podjazdu kuriera Pocztex (tylko nadanie w punkcie/na poczcie).

**Comment by paafcioc22** [comment]
Czy już coś wiadomo co usługą? Generowanie paczki opłaconej przebiega ok, teraz problem występuje w przypadku wysyłki pobraniowej (fedex).

**Comment by PrzemyslawLukanowski** [comment]
Proszę jeszcze o cierpliwość, wyjaśniamy ten temat.

**Comment by PrzemyslawLukanowski** [comment]
@paafcioc22 Zweryfikowaliśmy ten temat, przyczyną jest to, że na umowie z Fedexem nie posiadasz wymaganych uprawnień, aby utworzyć przesyłkę pobraniową. Prośba o kontakt z Fedexem w tym przypadku.

**Comment by patrys666** [comment]
@PrzemyslawLukanowski również mam ten sam błąd, który jest wspomniany w pierwszym poście. Możecie to sprawdzić? UUID: 18d9ad03-27e0-4d70-9cd9-95fdd745de1c

**Comment by PrzemyslawLukanowski** [comment]
@patrys666 Usuń ze swojego requestu informacje o county, np. w sender.address,pole dotyczy tylko USA, Irlandii i Kanady. W najbliższym czasie zaktualizujemy dokumentację oraz poradnik. Wdrożymy również komunikaty błędu, które będą informować, z którym polem konkretnie jest problem.

**Comment by paafcioc22** [comment]
> @paafcioc22 Zweryfikowaliśmy ten temat, przyczyną jest to, że na umowie z Fedexem nie posiadasz wymaganych uprawnień, aby utworzyć przesyłkę pobraniową. Prośba o kontakt z Fedexem w tym przypadku.

Zwrotka z serwisu wskazuje na to, że mogę (?)
id":8617642,
"service":"FEDEX",
"name":"fedex",
"owner":"CLIENT",
"additionalServices":{
**"cashOnDelivery":{
"available":true,**
"expressAvailable":true
},
"options":[
{
"name":"returnOfDocuments",
"description":"Zwróć dokumenty podpisane przez odbiorcę. Po dostawie odbiorca podpisuje dokumenty i zwraca je kurierowi."
},
{
"name":"additionalHandling",
"description":"Paczka niestandardowa."
},
{
"name":"fedexPriority",
"description":"Usługa priorytetowa FedEx. Czas realizacji do 3 dni roboczych."
}
]

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że przekazujesz prawidłowy numer serviceId, gdy tworzysz paczkę. Jeśli błąd nadal będzie występować, prześlij nam proszę przykładowe trace-id, będziemy to dalej weryfikować.

**Comment by paafcioc22** [comment]
@PrzemyslawLukanowski  jedyne co mogę przekazać to UUID ponieważ parcelID jest null,
{
"id":"c739cb3e-0890-4d68-8ada-d7485c89be36",
"parcelId":null,
"status":"ERROR",
"errors":[
{
"code":"ERROR",
"message":"Processing error",
"details":null,
"path":null,
"userMessage":"Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"
}
]
}

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, zgłosiłem ten problem do właściwego zespołu. Wrócę z odpowiedzią, gdy uda się coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
@paafcioc22 Problem już nie powinien występować na środowisku testowym. Czy możesz powtórzyć swoje wywołanie i potwierdzić?

**Comment by paafcioc22** [comment]
@PrzemyslawLukanowski potwierdzam, działa :) dzięki

**Comment by paafcioc22** [comment]
@PrzemyslawLukanowski dodałem swoją umowę z pocztą i przy generowaniu paczki mam błąd "Ubezpieczenie nie jest dozwolone dla tej usługi"

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 

>  dodałem swoją umowę z pocztą i przy generowaniu paczki mam błąd "Ubezpieczenie nie jest dozwolone dla tej usługi"

Czy mógłbyś podać nam więcej szczegółów - czy Twoja umowa z Pocztą przewiduje korzystanie z opcji ubezpieczenia?

**Comment by paafcioc22** [comment]
@PrzemyslawLukanowski  faktycznie opiekun stwierdził, że nie była zaznaczona opcja. Teraz paczka się generuje (status sukces) jednak drukowana etykieta jest pusta.
uuid : 18b738a2-ea8f-4b93-a059-89c68a4f89b8
parcelId :32125537

**Comment by AureliuszBrussy** [comment]
@paafcioc22 rozumiem, że próbujesz pobrać etykietę za pomocą [GET /parcel-management/parcels/label](https://developer.allegro.pl/documentation/#operation/getParcelLabel)? Prosiłbym o więcej szczegółów: czy pobrany plik jest pusty, czy w ogóle nie udało się Tobie pobrać pliku?

**Comment by paafcioc22** [comment]
Pobieranie etykiety działa (w przypadku innych przewoźników jest ok), natomiast plik zpl jest "niekompletny". W tym samym procesie pobieram również nr listu przewozowego i tu już mam błąd :
"Required property 'company' expects a non-null value. Path 'receiver', line 1, position 587."
Zwrotka:
{"parcelId":"32185156","serviceId":7883568,"label":{"sender":{"name":" ","company":"JOART X","address":{"street":"Stanisława X","postCode":"59-700","city":"X","county":null,"countryCode":"PL"},"email":"allegro@szachownica.com.pl","phone":"XX"},"fileFormat":"ZPL","referenceNumber":"Client51439276"},"receiver":{"name":"Stanislawa XXX","company":null,"address":{"street":"XXX48A","postCode":"37-500","city":"Jarosław","county":null,"countryCode":"PL"},"pointId":null,"email":"ai5cgoo826+aeb24b36@allegromail.pl","phone":"XXX"},"pickup":{"name":"JOART X","company":"X","address":{"street":"Stanisława X11A","postCode":"59-700","city":"X","county":null,"countryCode":"PL"},"pointId":null,"email":null,"phone":"X"},"items":[{"waybill":"00359007738375468676","dimensions":{"height":{"value":"20","unit":"CENTIMETER"},"width":{"value":"10","unit":"CENTIMETER"},"depth":{"value":"20","unit":"CENTIMETER"}},"weight":{"value":"1.0","unit":"KILOGRAM"},"description":"odzież","value":{"amount":"25.48","currency":"PLN"}}],"type":"PACKAGE","additionalServices":{"options":[]},"state":"CREATED"}


Uzupełnienie tego pola niestety nie pomogło.

**Comment by AureliuszBrussy** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by paafcioc22** [comment]
Udało się coś ustalić?

**Comment by AureliuszBrussy** [comment]
Przeanalizowaliśmy ten problem, potwierdzam błąd. Pracujemy nad naprawą. Aktualnie jedyne rozwiązanie dla tej konkretnej etykiety to wygenerowanie jej z poziomu E-nadawcy. Z kolei dla etykiet dla przesyłek jeszcze nie utworzonych - tymczasowe rozwiązanie to korzystanie z formatu PDF lub ustawienie odpowiedniego formatu i rozmiaru w ustawieniach E-nadawcy:
![image](https://user-images.githubusercontent.com/68948612/96599020-c403d000-12ef-11eb-91ec-656287b709b4.png)

**Comment by paafcioc22** [comment]
Próbowałem różnych ustawień - za pierwszym razem miałem status IN_PROGRESS. Później za każdym razem (pomimo usuwania paczki z "dodanych przesyłek" w serwisie) dostawałem błąd :
![image](https://user-images.githubusercontent.com/49162881/96831539-8dd46680-143d-11eb-90c9-3722bc5efc50.png)
przykładowe uuid : a13feccb-4989-44e9-97fe-86778072039c

**Comment by AureliuszBrussy** [comment]
Potwierdzam występowanie tego problemu - dotyczy on błędu komunikacji z API przewoźnika. Wyjaśniam to z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@paafcioc22 wracam z wyjaśnieniem - na tę chwilę dla jednego użytkownika pozwalamy na wygenerowanie tylko jednej przesyłki w danym czasie. Abyś mógł wygenerować następną - musi zakończyć się przetwarzanie poprzedniej. Pracujemy nad tym, aby znieść to ograniczenie.

**Comment by paafcioc22** [comment]
Zdaje się, że działa. Paczki się generują, etykiety drukują :)

**Comment by paafcioc22** [comment]
Jest jeszcze jeden błąd odnoście poczty. 
guuid: 8890c113-94f8-43ff-9326-fbb56b89b0ef
parcelid: 33275706
Status : success
Błąd przy pobieraniu/drukowaniu etykiety:
Required property 'company' expects a non-null value. Path 'receiver', line 1, position 572
Klient nie jest firmą.

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 Czy możesz doprecyzować - komunikat pojawił się Tobie podczas pobierania etykiety przez przeglądarkę?

**Comment by paafcioc22** [comment]
@MaciejFrackowiak Przepraszam, wydawało mi się, że błąd był zwracany przez zasób : parcel-management/parcels/{parcelId}.
Błąd występuje po mojej stronie podczas deserializacji danych.

**Comment by MaciejFrackowiak** [comment]
@paafcioc22 Dziękuję za odpowiedź - z naszych logów wynikało właśnie, że etykietę można bezproblemowo pobrać.
