### ISSUE TITLE
Faktury za AllegroSmart

### ISSUE THREAD

**Issue by yami-five** [allegro/allegro-api#3618]
Przed chwilą dostałem dwa maile pod rząd z fakturą za AllegroSmart na maila z konta testowego na sandboksie. Ktoś się pomylił, to jakieś testy czy może być wyciek?
Z tego co mi wiadomo kilka innych osób dostało taką samą wiadomość na maile, z których zakładali konta na sandboksie.

**Comment by lukaszzborek** [comment]
Również jestem ciekawe 🙄
co ciekawe mail z normalnej domeny allegro, a dane z sandbox

**Comment by AureliuszBrussy** [comment]
Konsultuję zgłoszenie z odpowiednim zespołem. Wrócę z wiążącą odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Wiadomości zostały wysłane z systemu testowego. Wysyłka została już wstrzymana, proszę o zignorowanie tej wiadomości. Przepraszam za niedogodność.
