### ISSUE TITLE
Przekazanie statusu przesyłki nie będąc zintegrowanym z allegro

### ISSUE THREAD

**Issue by geiscargo** [allegro/allegro-api#3619]
Witam, nasi klienci ktorzy prowadzą sprzedaż przez allegro zamawiają u nas usługę transportową. Nie jesteśmy jednak na Cargo zintegrowani z allegro a chcielibyśmy przekazać status przesyłki którą u nas zamówili. Jak można to zrobić?

**Comment by AureliuszBrussy** [comment]
Uzupełnianie numerów przesyłek możliwe jest tylko pod warunkiem [zautoryzowania aplikacji](https://developer.allegro.pl/auth/). Nie uda się pominąć integracji, jeżeli chcieliby Państwo uzupełniać numery przesyłek w imieniu klientów.

**Comment by geiscargo** [comment]
Jak możemy przystąpić do integracji?

Pozdrawiam

Grzegorz Chmielecki
Geis PL

________________________________

**Comment by geiscargo** [comment]
Dodam, ze Geis jest zintegrowany na produkcie Paczka. Aktualnie jednak nie świadczymy tej usługi a chcielibyśmy przejść na Cargo. Chciałbym się dowiedzieć, jakie kroki możemy podjąć, żeby zacząć wymieniać dane na drugim produkcie.

**Comment by MaciejFrackowiak** [comment]
Kwestia integracji i odpowiedniego rozwiązania pozostaje w Państwa gestii. Aplikacja musi być zautoryzowana by mogła przekazywać numery przesyłek dla zamówień z wykorzystaniem zasobu [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST).
