### ISSUE TITLE
PHP upload images problem

### ISSUE THREAD

**Issue by crevu** [allegro/allegro-api#362]
Hi guys,

I'm having trouble uploading images from php. The following request works perfectly if i simply use it from command line:

curl -X POST "https://upload.allegro.pl/sale/images" -H "authorization: {access_token}" -H "accept: application/vnd.allegro.beta.v1+json" -H 'content-type: image/jpeg' -H "accept-language: en-EN" --data-binary "@C:\Users\Horia\Desktop\husa.jpg"

However, I cannot make it work from php. This is my code:

 $imageFile = new CURLFile(
                realpath("C:\Users\Horia\Desktop\husa.jpg"),
                'image/jpeg',
                'test_name'
            );

            curl_setopt($ch, CURLOPT_URL,            "https://upload.allegro.pl/sale/images" );
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1 );
            curl_setopt($ch, CURLOPT_POST,           1 );
            curl_setopt($ch, CURLOPT_POSTFIELDS, [$imageFile]);
            curl_setopt($ch, CURLOPT_HTTPHEADER,
                [
                    "Authorization: Bearer $accessToken",
                    "Accept: application/vnd.allegro.beta.v1+json",
                    "Content-Type: image/jpeg",
                    "Accept-Language: en-EN"
                ]
            );

            $result=curl_exec ($ch);

The response from allegro looks like this:

 {"errors": [{"code": "415", "message": "415 Unsupported Media Type "," details ": null," path ": null," userMessage ":" File is not PNG, JPG or GIF image. "}]} 
Status code = 415

Can you give me some advice on how to approach this problem ?

**Comment by LukaszKorek** [comment]
I am very sorry but I will not be able to help. We do not support API in this language -PHP.

**Comment by LukaszKorek** [comment]
I will add that We do not provide technical support for any programming language. We only support the protocol layer, in case of REST API we need curl in .json format.

**Comment by ksmistry1991** [comment]
Upload image to your server first and pass uploaded image link as parameter to below function

public function curl_image($image_link)
    {        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://upload.allegro.pl/sale/images');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"url\":\"".$image_link."\"}");
        curl_setopt($ch, CURLOPT_POST, 1);
        $headers = array();
        $headers[] = 'Authorization: Bearer '.$this->access_token;
        $headers[] = 'Accept: application/vnd.allegro.public.v1+json';
        $headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);exit;
        }else{
            $temp = json_decode($result);            
            $image = $temp->location;
        }
        return $image;
    }
