### ISSUE TITLE
Stawka VAT na zamówieniu

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3620]
W jaki sposób można otrzymać stawkę VAT dla danej pozycji zamówienia jeżeli [zasób](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) nie zwraca takich informacji?

**Comment by AureliuszBrussy** [comment]
Obecnie stawka VAT w [GET /order/checkout-forms/{checkouFormId}](url) nie jest widoczna. Aby ją pobrać w kontekście oferty, w której klient wykonał zakup, skorzystaj z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by fjjjq** [comment]
Co w przypadku gdy stawka ulegnie zmianie, pomiędzy zakupem a odpytaniem o dane oferty?

**Comment by MaciejFrackowiak** [comment]
Stawką VAT zarządzasz Ty jako sprzedający, zatem wiesz kiedy dokonałeś ewentualnej zmiany w ofercie. Co do zasady stawka VAT dla danego towaru jest stała, zmienia się tylko wtedy, gdy ustawowodawca dokonuje zmian w przepisach.
