### ISSUE TITLE
Pobieranie ofert wraz z ID i kategoriami

### ISSUE THREAD

**Issue by Aleks79Q** [allegro/allegro-api#3621]
Witam,
Chciałabym pobrać wszystkie oferty z mojego konta oraz ich ID i kategorie. W jaki sposób mogę to zrobić?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET), wówczas otrzymasz listę ofert z Twojego konta - przykładowa struktura:

```
"offers": [
        {
            "id": "numer_oferty",
            "name": "Produkt testowy",
            "category": {
                "id": "numer_kategorii"
            },
...
```

**Comment by Aleks79Q** [comment]
Dzięki za odpowiedź. Czy możesz mnie krok po kroku pokierować jak to zrobić? A właściwie gdzie wpisać kod.
Czy oprócz ID otrzymam też kategorie?

**Comment by MaciejFrackowiak** [comment]
Z naszej strony nie sugerujemy konkretnych programów czy też rozwiązań - w sieci dostępna jest spora liczba rozwiązań, które pozwalają w prosty sposób korzystać z naszego REST API. Tu otrzymasz tylko ID kategorii, natomiast drzewo kategorii i parametrów pobierzesz [tymi zasobami](https://developer.allegro.pl/documentation/#tag/Categories-and-parameters).
