### ISSUE TITLE
https://allegro.pl/auth/oauth/token?grant_type=refresh_token 503 Backend fetch failed

### ISSUE THREAD

**Issue by shopelo** [allegro/allegro-api#3622]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Request:
https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_toke
n=***&redirect_uri=https%3A%2F%2Fpanel.shopelo.pl%2Fallegro-callback

Response: 503 Backend fetch failed

Nasz system regularnie co 12 godzin odświeża token,  próbował odświeżyć token o godzinie 2020-09-05 00:09:05 w odpowidzi otrzymaliśmy błąd 503
Została podjęta kolejna próba (2020-09-05 00:09:07) wywołania request podanego wyżej  i otrzymaliśmy odpowiedź "400 Bad Request" oraz json-a
{"error":"invalid_grant","error_description":"Invalid refresh token: eyJhb......

Dodam że problem występuje cyklicznie, poprzednio wystąpił 2020-08-11 14:00:07.

Nasz system ma połączone inne konta allegro w których problem z odświeżeniem nigdy nie wystąpił.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowaliśmy nasze logi - o godzinie 00:09:05.970 udało się usunąć stary token, jednak nie zwróciliśmy nowego. Następstwem tego były kolejne komunikaty 400 Bad Request, ponieważ używali Państwo tokena, który został już zdezaktywowany. Jest to wyjątek, który jest nam znany, pracujemy nad jego rozwiązaniem.

**Comment by shopelo** [comment]
Dziękuję za szybką odpowiedź.
Czy istniej jakieś rozwiązanie tymczasowe?
Czy odświeżenie tokenu przed wygaśnięciem jest wolne od błędów 503 a w następstwie 400.
Jaki przewdywany jest termin naprawienia tego wyjątku.

**Comment by PrzemyslawLukanowski** [comment]
Rozwiązaniem tymczasowym będzie jedynie ponowne przejście procesu autoryzacji, aby wygenerować nową parę access + refresh token. Odświeżenie tokenu przed wygaśnięciem jest wolne od błędów tego typu, trafili Państwo na wyjątek. Problem powinien zostać rozwiązany w ciągu najbliższych tygodni.
