### ISSUE TITLE
Zła data zakończenia aukcji

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#3623]
Występuje problem: 
 - [ x ] z zasobem REST API

Aukcja 9587394479 zakończona ręcznie 1 września. 
Pobierając dane aukcji mam:
publication' => 
    array (size=6)
      'duration' => string 'PT720H' (length=6)
      'status' => string 'ENDED' (length=5)
      'startingAt' => null
      'endingAt' => string '2020-09-11T11:59:23.000Z' (length=24)
      'endedBy' => string 'USER' (length=4)
      'republish' => boolean false

Czyli wychodzi że aukcja zakończona 'by User' w przyszłości .... Dzisiaj mamy 7.09.2020

**Comment by PrzemyslawLukanowski** [comment]
W polu endingAt zwracamy datę, kiedy oferta ma /miała się zakończyć, jeśli ustawiłeś określony czas trwania. Faktyczną datę zakończenia znajdziesz w odpowiedzi dla GET /sale/offers?offer.id={offer.id} w polu publication.endedAt.
