### ISSUE TITLE
Filtrowanie offert po etykiecie

### ISSUE THREAD

**Issue by LukaszKams** [allegro/allegro-api#3624]
Witam, istnieje możliwość filtrowania ofert po etykietach oraz ustawiania etykiet podczas tworzenia draftu?

**Comment by PrzemyslawLukanowski** [comment]
Etykiety są funkcjonalnością dostępną tylko na froncie, dlatego opcje, o których napisałeś, nie są dostępne przez API. Jeżeli coś się zmieni w tej kwestii, opublikujemy odpowiedni komunikat.

**Comment by M4GiK** [comment]
Kiedy planujecie wdrożenie takiej funkcji do API.  Przydała by się taka opcja.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy tego w planach. Jak wspomniałem - jeżeli coś się zmieni w tym temacie, opublikujemy odpowiedni komunikat.
