### ISSUE TITLE
Skąd brać datę sprzedaży złożenia zamówienia

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3626]
Skąd brać datę sprzedaży złożenia zamówienia jak na froncie allegro, bo branie daty z pola lineItems.boughtAt w jest dla danego przedmiotu a nie całego zamówienia?

**Comment by hahyes** [comment]
Data sprzedazy wyświetlona na froncie to data zakupu najnowszego przedmiotu z zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
@AnimalDEV Jest tak jak napisał @hahyes - data sprzedaży to element z najnowszą datą w lineItems.boughtAt.

**Comment by AnimalDEV** [comment]
Dziękuję za pomoc
