### ISSUE TITLE
NIP kupującego w zamówieniach

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3627]
Dlaczego zasób [getListOfOrdersUsingGET](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) nie zwraca NIPu kupującego. Wydaje się to błędne, jeżeli zwracana jest sama nazwa firmy jak i nawet numer PESEL dla użytkownika.

**Comment by fjjjq** [comment]
Nie jest to przecież NIP kupującego sklepu, a NIP który musi być wystawiony na fakturze.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz wskazać potrzebę lub inny scenariusz, dla którego potrzebujesz pola z tą wartością?
