### ISSUE TITLE
[SANDBOX] nie działa logowanie

### ISSUE THREAD

**Issue by grzesiekm86** [allegro/allegro-api#3628]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie można zalogować się na sandboxie, jest biała strona
https://allegro.pl.allegrosandbox.pl/login/auth

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, weryfikujemy go.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by grzesiekm86** [comment]
Potwierdzam, teraz działa.
