### ISSUE TITLE
Błąd user_name from JWT cannot be empty

### ISSUE THREAD

**Issue by Dunkej99** [allegro/allegro-api#3629]
Po autoryzacji Autoryzacja Client_credentials flow i otrzymaniu tokenu wywołuje metoda GET https://api.allegro.pl/order/checkout-forms z 
header:
"authorization: Bearer $token",
"Accept: application/vnd.allegro.public.v1+json",
"Content-Type: application/vnd.allegro.public.v1+json"

i otrzymuje blad EmptyUserIdException (user_name from JWT cannot be empty)

czym to jest spowodowane ?

**Comment by PrzemyslawLukanowski** [comment]
Autoryzacja client_credentials nie posiada kontekstu użytkownika i służy tylko do pobierania publicznych danych. np. GET /sale/categories. W [naszej dokumentacji](https://developer.allegro.pl/documentation/#section/Authentication) znajdziesz odpowiednie oznaczenia, jakiego typu autoryzacji powinieneś użyć. Aby pobrać zamówienia dla zautoryzowanego użytkownika, skorzystaj z autoryzacji typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow).
