### ISSUE TITLE
procedura wznawiania ofert

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#363]
Tak sobie myślę, że skoro moje piątkowe nocne wypociny były za długie do przeczytania to zadam pytanie prościej: Jaka jest procedura wznawiania ofert w których ilość dostępna jest równa 0. Zatem konkretny przykład: 
oferta: 7341427467, 
ilość wystawiona: 5
ilość sprzedana: 5
ilość dostępna: 0
korekta ilości przez /sale/offers/ w polu available podajemy 15, wynik walidacji poprawny
przy próbie edycji oferty przez Allegro pojawia się ilość 20 szt - nie wznawiamy jej, to było tylko sprawdzenie
Następnie wykonujemy ACTIVATE na /sale/offer-publication-commands/ i gdy sprawdzamy /TASKS widzimy: [message] => Could not change offer publication status [status] => FAIL
**Proszę o weryfikację i informacje DLACZEGO mimo dostępnej ilości sztuk nie można wskrzesić oferty 7341427467**

**Comment by PawelTaberski** [comment]
#359 --> Sprawdziłem i rzeczywiście jest jakiś błąd, sprawę zgłosiłem do odpowiedniego zespołu proszę o cierpliwość.

**Comment by partyumarty** [comment]
Panie Pawle - czy jakieś światełko w tunelu odnośnie wznawiania ?
Jak byście potrzebowali kolejny przykład to proszę:
oferta: 7331480858
wystawione: 10
sprzedane: 10
edycja: 15 szt
wznowienie i [message] => Could not change offer publication status [status] => FAIL
oczywiście w edycji manualnej dostępna ilość to 25, wznowić z palca jej się nie da ani dla 25, ani dla 11, ale już dla 26 tak. 

WNIOSEK: nadal ilość podana w REST jako dostępna updajtuje ilość sprzedaną ;-/

**Comment by PawelTaberski** [comment]
Zespół odpowiedzialny za tą funkcjonalność już nad tym pracuje proszę o cierpliwość.

**Comment by partyumarty** [comment]
Hallo hallloooo.... drogi zespole. Mijają kolejne dni i cisza... dlaczego robicie coś nowego, skoro nie działa stare ? Dlaczego przedłużacie testy dziwiąc się, że macie za mało wywołań skoro to co dajecie to bubel i nie naprawiacie tego ? Przecież tu nikt się nie czepia o kosmetyke ani o pierdoły tylko o to, ze funkcja nie działa wcale, czyli jej użyteczność wynosi ZERO! Jak ludzie mają testować Wasz nowy cudowny REST jeśli nie działa podstawowa operacja na podstawowej funkcji, czyli edycja ilości w edycji aukcji ? Proszę aby ktoś się tym pilnie zajął.

**Comment by PawelTaberski** [comment]
Tak jak pisałem zespół odpowiedzialny za tą funkcjonalność pracuje nad rozwiązaniem tego problemu, proszę o cierpliwość.

**Comment by partyumarty** [comment]
Panie Pawle, rozumiem, ale będę pytał do skutku. PO CO wprowadzacie nowe moduły, jeśli stare nie działają ? Jaki sens mają prace nad czymś nowym, skoro nie działa podstawowy request ? Jak mamy to testować i używać jeśli czekamy TYDZIEŃ i nikt nie ruszył problemu ? Problem nadal bez zmian. Dowodowo zweryfikowane przed chwilą na aukcji 7438043522, wystawione 2, sprzedane 2, dostępne 0 (zero). Podana ilość 20. Wznowienie FAIL. Wznowienie ręczne z poziomu aukcji wskazuje 22 sztuki, ale również nie pozwala sie wznowić. To, że coś nie działa, a Wy sie dziwicie, że macie za mało requestów na testach można uznać, że jest nawet zabawne w pewnych kategoriach, ale to, że ktoś za Was odwala robotę, testuje, wskazuje konkretne błędy, a Wy go macie w 4 literach i przez tydzień nic nie robicie już zabawne nie jest :(

**Comment by PawelTaberski** [comment]
Rozumiem, jednakże proszę o jeszcze trochę cierpliwości pracujemy nad rozwiązaniem tego problemu.

**Comment by partyumarty** [comment]
@PawelTaberski czy to "trochę" to już prawie, czy jeszcze daleko ?

**Comment by PawelTaberski** [comment]
Tak jak pisałem pracujemy nad rozwiązaniem problemu, jak tylko go rozwiążemy dam znać.

**Comment by PawelTaberski** [comment]
Jak tylko rozwiążemy ten problem poinformujemy.

**Comment by partyumarty** [comment]
Oczko... 21 dni. Czy to ma być kiepski żart, czy o co chodzi ? Jakie są plany na naprawienie tego ?

**Comment by PawelTaberski** [comment]
@partyumarty  Dostałem informacje, że poprawka została wdrożona, czy mimo to problem dalej występuje?

**Comment by PawelTaberski** [comment]
@partyumarty Po konsultacjach z z klientami z którymi omawialiśmy kwestie działania REST zdecydowaliśmy się na to drugie podejście. Obecnie nie musi Pan pamiętać ile było sztuk i dodawać dodatkowe. Od teraz jeśli chce Pan przykładowo mieć dostępnych 5 sztuk wystarczy, że przy zmianie poda Pan w stock 5.
