### ISSUE TITLE
Empty user_name claim

### ISSUE THREAD

**Issue by Kevin-qs** [allegro/allegro-api#3630]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz opisać swój problem? / Could you describe your issue?

**Comment by Kevin-qs** [comment]
Mam już token kodu i nadal pojawia się błąd, kiedy żądam utworzenia wersji roboczej. Puste żądanie nazwa_użytkownika

**Comment by PrzemyslawLukanowski** [comment]
Spójrz na rozwiązanie zgłoszenia #3629, to ten sam problem.

**Comment by Kevin-qs** [comment]
Został autoryzowany przez Autoryzację użytkownika, ale nadal wraca do powyższego pytania, które różni się od tego, co powiedział wcześniej użytkownik.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę trace-id Twojego żądania lub prześlij przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dopisz wtedy w zgłoszeniu, że problem dotyczy wątku #3630 na githubie.

**Comment by Kevin-qs** [comment]
Przepustka: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=
Uzyskaj token autoryzacyjny
header
'Accept: application/vnd.allegro.public.v1+json',
                'Authorization: Bearer ' . token,
                'Content-type: application/vnd.allegro.public.v1+json',
Następnie zapytaj https://api.allegro.pl/sale/offers
Zwróć powyższy błąd:  There was an error while trying to get related account's resources

**Comment by PrzemyslawLukanowski** [comment]
Ten request zawiera zbyt mało danych, abyśmy mogli zlokalizować źródło Twojego problemu. Ponawiam prośbę - podaj trace-id Twojego żądania lub prześlij przykładowy **pełny** request i response przez nasz formularz kontaktowy. Dopisz wtedy w zgłoszeniu, że problem dotyczy wątku #3630 na githubie.

**Comment by PrzemyslawLukanowski** [comment]
Możesz także spojrzeć na rozwiązanie problemu #3277, w którym pojawił się podobny komunikat błędu. Wszystko wskazuje na to, że korzystasz z autoryzacji typu client_credentials.

**Comment by Kevin-qs** [comment]
header:
 Accept: application/vnd.allegro.public.v1+json  Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiZXhwIjoxNTk5Njc5ODY2LCJqdGkiOiIxZmQxZTA0OS0zZDIwLTQxODgtYTRjNC0yZTc5NDE3OGJiMmMiLCJjbGllbnRfaWQiOiI1MTUwMjQ2MjlmOTg0OWY3YWNmZWE1NmJhY2MxOGIzMiJ9.dPC2vfZtgZsCQIuRZPKmnbe6UghcuRp30XpogqDaR0uWQ_l4cg4cnQmcl6m0YNOv4xkg8x3Hsw0DTGlUuX1XwFKUlRHjS0pKdLhNvLV7RCyhRuosQ9fWQiN8EZXsGL6F7OO0NoPGtpK7cJ-JW_NgZGR1WBt30KN_whxu9_bnvf0XwASQfwwWpz0eOQSfdIe0IZMNKaj7j9mkgKhYXxYiPD4GvB4X-hcyWZ98u7OXCmh5Aty_KvuP7azSQ64kLdt2X9FhZzH94TiP53PVbgyU0WJBAHF3PfXmiwFmePO9GeeX7YKuDLn22PGqPIQ9xrxbfAyoyWvq5bmJ6cY4a2VANg  Content-type: application/vnd.allegro.public.v1+json other param: {"name":"Dywan r\u0119cznie wypleciony z juty, 150 cm","ean":"8075215126007","category":{"id":"20257"}} To, o co chcę poprosić, to: https://api.allegro.pl/sale/offers 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午5:41
收件人:&nbsp;"allegro/allegro-api"<allegro-api@noreply.github.com&gt;;
抄送:&nbsp;"Kevin"<767922913@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Empty user_name claim (#3630)





 
Ten request zawiera zbyt mało danych, abyśmy mogli zlokalizować źródło Twojego problemu. Ponawiam prośbę - podaj trace-id Twojego żądania lub prześlij przykładowy pełny request i response przez nasz formularz kontaktowy. Dopisz wtedy w zgłoszeniu, że problem dotyczy wątku #3630 na githubie.

**Comment by Kevin-qs** [comment]
![image](https://user-images.githubusercontent.com/54785222/92583228-9e34e580-f2c4-11ea-9d1f-a1fefe952223.png)

Uzyskano autoryzację użytkownika zgodnie z działaniem procesu w tym miejscu i zgłaszany jest ten sam błąd, a nie ten sam problem napotkany przez poprzedniego użytkownika

**Comment by PrzemyslawLukanowski** [comment]
Możesz rozkodować swój token za pomocą jednego z darmowych narzędzi - brakuje w nim informacji o user_name, co świadczy o tym, że jest to token wygenerowany przez typ autoryzacji client_credentials. Błąd, który otrzymujesz również na to wskazuje. Jeżeli jesteś przekonany, że skorzystałeś z autoryzacji typu code, prześlij nam proszę żądania i odpowiedzi, które wykonujesz w procesie autoryzacji.  Link do [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
