### ISSUE TITLE
Nie działa rejestracja aplikacji na sandbox

### ISSUE THREAD

**Issue by konrad871030** [allegro/allegro-api#3631]
Nie można zarejestrować nowej ani edytować istniejącej aplikacji na sandbox. Pojawia się komunikat proszę spróbować później. Ile czasu to może potrwać?

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem, weryfikujemy to. Wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Problem już nie występuje.
