### ISSUE TITLE
Problemy z zmianą cen przez RedCart.

### ISSUE THREAD

**Issue by maarle** [allegro/allegro-api#3632]
Witam,
czy istnieje jakiś problem w integracji Allegro-RedCart? Nie można w wystawionych aukcjach zmieniać cen poprzez zmianę "zwiększ/zmniejsz narzut". Support RedCart tłumaczy, ze to jest wina zmian dokonywanych przez Allegro i potrwa to jeszcze chwile. Jak długo ta chwila potrwa?
pozdrawiam

**Comment by SebastianOzdoba** [comment]
@maarle  my osobiście nie mamy problemów ze zmianami cen, restaAPI odpowiada poprawnie i wszystko działa. Są oczywiście jakieś losowe sytuacje ale to się zgłasza punktowo na bieżąco. Tłumaczenie że "wina Allegro" to chyba taki wytrych ;)

**Comment by maarle** [comment]
Hej Sebastian, dzięki za odpowiedź. Powiedz mi jeszcze, Ty jesteś użytkownikiem RedCart'a, czy też piszesz ze strony Allegro?

**Comment by SebastianOzdoba** [comment]
@maarle  ani jednym ani drugim :), używamy API Allegro

**Comment by PrzemyslawLukanowski** [comment]
@maarle Nie odnotowaliśmy problemów ze zmianą cen w ofertach w podanym czasie.

**Comment by maarle** [comment]
Dzięki za informację. Muszę w takim razie pomęczyć support RC.
