### ISSUE TITLE
Nie można ustawić stawki VAT

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#3633]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Do oferty nie można przypisać stawki VAT pomimo, że konto jest kontem firma; `/me` zwraca `company.name` i `taxId`. Trace `f7354fbf7b079fae`

**Comment by PrzemyslawLukanowski** [comment]
Konto zostało ostatecznie zweryfikowane jako firmowe wczoraj o 21:44 - problem nie powienien już występować.

**Comment by TimothyKoval** [comment]
A dlaczego nie mogę ustawić stawki VAT jeżeli nie mam konta firma?

**Comment by PrzemyslawLukanowski** [comment]
Stawka VAT jest powiązana z możliwością wystawienia faktury - opcji niedostępnej dla kont zwykłych.

**Comment by TimothyKoval** [comment]
No, tak, tylko że nie.

[https://allegro.pl/oferta/rama-wozek-belka-sanki-tyl-vw-golf-4-iv-97-9658513786](https://allegro.pl/oferta/rama-wozek-belka-sanki-tyl-vw-golf-4-iv-97-9658513786)

Sprzedawca nie ma konta firma, a wystawia faktury VAT

**Comment by PrzemyslawLukanowski** [comment]
Podtrzymuję, że na koncie zwykłym nie ma możliwości wystawiania faktur - również zgodnie z informacjami na naszej [stronie dla sprzedających](https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/jakie-sa-roznice-miedzy-kontem-zwyklym-a-kontem-firmowym-Oqxkval7aS7). Jeżeli uważasz, że użytkownik prowadzi działalność na koncie zwykłym, zgłoś to przez nasz [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c)

**Comment by TimothyKoval** [comment]
Ktoś tu chyba ma wylew. Podałem przykład aukcji, na której sprzedawca nie mający konta zarejestrowanego na firmę ma zaznaczoną opcję wystawiania faktur VAT, więc niezależnie od tego co i jak Pan podtrzymuje, jest Pan w błędzie.

**Comment by PrzemyslawLukanowski** [comment]
Na forum proszę wypowiadać się kulturalnym językiem i zwracać się z szacunkiem do pozostałych użytkowników. Doprecyzuję - na koncie zwykłym nie ma możliwości ustawienia stawki VAT. Aby móc ją zdefiniować, należy prowadzić działalność gospodarczą w ramach konta firmowego. Samą opcję Wystawiam fakturę VAT w ofercie może zaznaczyć każde konto, zarówno firmowe, jak i zwykłe.
Na forum udzielamy wsparcia technicznego API - jeżeli masz dalsze wątpliwości związane z funkcjonowaniem kont, zgłoś je przez nasz formularz kontaktowy.

**Comment by TimothyKoval** [comment]
> na koncie zwykłym nie ma możliwości wystawiania faktur

> opcję Wystawiam fakturę VAT w ofercie może zaznaczyć każde konto, zarówno firmowe, jak i zwykłe

To się nie nazywa "doprecyzowanie", tylko zaprzeczenie samemu sobie
