### ISSUE TITLE
Więcej zamówień przez API w stosunku do zamówień widzianych w panelu po zalogowaniu.

### ISSUE THREAD

**Issue by techjaw** [allegro/allegro-api#3634]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Jakim cudem widzę więcej zamówień przes API aniżeli w panelu?
Co ciekawe [fulfillment] w tym przypadku mam puste. Proszę o wyjaśnienie.

**Comment by PrzemyslawLukanowski** [comment]
W obu przypadkach gwarantujemy zamówienia z ostatnich 180 dni, jednak w przypadku API mogą się zdarzyć sytuacje, że otrzymasz także jeszcze starsze zamówienia.
