### ISSUE TITLE
Statystyki ofert w API

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#3635]
:bulb: **Sugestia**

Czy na zasobie GET /sale/offers/{offerId} mogłaby się znaleźć informacja o statystykach ofert ? 
![obraz](https://user-images.githubusercontent.com/43290585/92687550-08d53800-f33c-11ea-9660-9873e2825ac9.png)
Byłoby to przydatne w kontekście obliczania wskaźnika konwersji.

**Comment by PrzemyslawLukanowski** [comment]
Te informacje znajdziesz w zasobie GET /sale/offers w obiektach stats oraz stock. Aby odwołać się do konkretnej oferty, użyj parametru offer.id - GET /sale/offers?offer.id={offer.id}.
