### ISSUE TITLE
Orders/Events: dziwne statusy zamówień w dniu wczorajszym

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3636]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Klient na poziomie MS Allegro, zmienił status zamówienia na ANULOWANE
W dzienniku API mamy odnotowany fakt zmiany stanu zamówienia ale jest on inny

Reqest:
https://api.allegro.pl/order/events?from=1599662201084588&type=READY_FOR_PROCESSING%2CFILLED_IN%2CFULFILLMENT_STATUS_CHANGED%2CBUYER_CANCELLED&limit=1000' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 

Response (obcięty, takich sytuacji jest więcej i tylko z wczoraj, dotyczy zamówień z lipca i sierpnia 2020)

        "Type": "FULFILLMENT_STATUS_CHANGED",
        "Id": "1599663446409661",
        "Order": {
          "Seller": {
            "Id": "46401842"
          },
          "Buyer": {
            "Id": "46742423",
            "Email": "1j9o39b8bo+134d99253@allegromail.pl",
            "Login": "Client:46742423",
            "Guest": false
          },
          "LineItems": [
            {
              "Id": "60fc6580-dcd5-11ea-a44e-594b643b2e6d",
              "Offer": {
                "Id": "9504992416",
                "Name": "Gillette Mach 3 Maszynka do golenia",
                "External": {
                  "Id": "06-1424"
                }
              },
              "Quantity": 1.0,
              "OriginalPrice": {
                "Amount": "17.36",
                "Currency": "PLN"
              },
              "Price": {
                "Amount": "17.36",
                "Currency": "PLN"
              },
              "BoughtAt": "2020-08-12T19:55:53.974Z"
            }
          ],
          "CheckoutForm": {
            "Id": "60fc6582-dcd5-11ea-a44e-594b643b2e6d",
            "Revision": "f1901a50"
          }
        },
        "OccurredAt": "2020-09-09T14:57:15.832Z"

"Validation": null,
  "Exception": null,
  "TraceId": "49054d87902255f0",
  "Error": false,
  "StatusCode": 200,
  "Message": null

Prośba o sprawdzenie

**Comment by PrzemyslawLukanowski** [comment]
Otrzymany event w tym przypadku jest prawidłowy, to sprzedawca zmienił status realizacji zamówienia - wpłynął na wartość w polu "fulfillment.status", dlatego zwróciliśmy event "FULFILLMENT_STATUS_CHANGED". Natomiast status zamówienia to "FILLED_IN", ponieważ kupujący go nie anulował - wtedy zwrócilibyśmy event "BUYER_CANCELLED", a wartość w polu status zmieniłaby się na "CANCELLED".

**Comment by SebastianOzdoba** [comment]
A skąd taki status jeśli sprzedający  w ogóle nie ustawiał statusu WYSŁANA?

**Comment by PrzemyslawLukanowski** [comment]
"FULFILLMENT_STATUS_CHANGED" pojawia się w przypadku każdej zmiany statusu realizacji zamówienia, np. z NEW na PROCESSING, z NEW na CANCELLED, etc.

**Comment by SebastianOzdoba** [comment]
dobra, dzięki, sprawdzamy po naszej stronie
