### ISSUE TITLE
Kod EAN

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#3638]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym

Nie rozumiem dlaczego Wy jako programiści zmuszacie nas programistów do dowania kodów EAN w dwóch miejscach, na polu aukcji i w polach dodatkowych, ja tego totalnie nie rozumiem to jest zwykłe mnożenie bytów które nie powinno mieć miejsca.

Samo rozwiązanie przechowywania kodów EAN w dwóch polach w zależności od kategorii jest naprawdę bardzo słabe i skoro już tak musi być nie powinno to być nam innym programistom wogole pokazywane !

Jeżeli programista wysyła Wam pole EAN na aukcji powinno być ono automatycznie przez Was przepisane do pola dodatkowego EAN i tyle, natomiast pokazywanie komuniaktu że pole jest tylko do odczytu jest mega słabe.

**Comment by PrzemyslawLukanowski** [comment]
Nie musisz przekazywać wartości dla EAN w dwóch miejscach. Wystarczy, że określisz tę wartość [w odpowiednim parametrze](https://developer.allegro.pl/news/#gtin), w odpowiedzi automatycznie przeniesiemy ją do pola "ean".

**Comment by PrzemyslawLukanowski** [comment]
[Zmianę zapowiedzieliśmy 29 maja](https://developer.allegro.pl/news/#gtin-intro), od 29 czerwca EAN został przeniesiony do parametru GTIN. Jeżeli przekażesz go w tym miejscu, nie otrzymasz komunikatu o read-only i dodatkowo nie musisz zamieszczać informacji w polu "ean" - automatycznie przeniesiemy tam wartość z parametru. W przyszłości - jak wspominaliśmy w komunikacie - planujemy usunąć pole "ean".
