### ISSUE TITLE
Zmiana systemu tokenów i refresh tokenów. 

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#3639]
:bulb: **Sugestia**
Czy jest szansa, aby to zmienić? Dlaczego inne serwisy są w stanie mieć ważny token nawet rok, a allegro nie? Jakieś chore wymysły "bezpieczeństwa", które nie mają najmniejszego sensu. Biorąc pod uwagę, że oczywiście u was zawsze jest wszystko ok, ja musze znowu po raz czwarty z rzędu generować ręcznie tokeny do 5 kont allegro... 

Jak za 50cioma poprzednimi przypadkami mogło być tak, że dysk był uszkodzony i miał problem z zapisaniem nowych tokenów, tak teraz już błagam, proszę, wymagam jakieś zmiany... Chociaż zargumentujcie wybór takiego "czegoś", bo jakoś pozytywów w tym żadnych nie widzę.

**Comment by PrzemyslawLukanowski** [comment]
Bezpieczeństwo jest bardzo ważnym aspektem i [zgodnie z dokumentacją OAuth 2.0 ](https://tools.ietf.org/html/rfc6819#page-54) należy używać krótkiego okresu wygaśnięcia:

>    A short expiration time for tokens is a means of protection against
>    the following threats:
> 
>    o  replay
> 
>    o  token leak (a short expiration time will reduce impact)
> 
>    o  online guessing (a short expiration time will reduce the
>       likelihood of success)

Możesz zautomatyzować proces po swojej stronie i po wygaśnięciu access tokena, korzystać z [refresh tokena](https://developer.allegro.pl/auth/#refresh-token), którego ważność to 3 miesiące.

**Comment by Onixarts** [comment]
Problem jest raczej nie w czasie odświeżania, a w tym, że jak nam nie uda się zapisać nowych tokenów to zachodzi konieczność ingerencji ręcznej użytkownika, bo stare tracą już ważność i do niczego się nie nadają. A tego chyba dokumentacja OAuth 2.0 nie narzuca, więc refresh tokeny mogły by być odświeżane tylko i wyłącznie podczas ręcznej autoryzacji przez użytkownika i mięć długi okres ważności. Użytkownik przeprowadzając ponową autoryzację mógłby wtedy (pół)świadomie blokować stary refreshtoken. 

Albo nie do końca rozumiem idei. W dokumentacji API jest napisane, że token autoryzujący ma ważność 12h. Do tego dostajemy token odświeżający, który jest jednorazowy. Następnie pojawia się informacja, że:

**Dzięki obsłudze tzw. odnawialnego czasu życia tokena, za każdym razem gdy używasz refresh token, czas jego ważności zostaje przedłużony o kolejne 3 miesiące.
**
Czas ważności refresha czy autoryzującego jest przedłużany? Rozumiem, że refresha. Tylko po co komu refresh token o długości trwania 3 miesiące, skoro po 12h i tak dostajemy nowy bo musimy odświeżyć nim token autoryzujący. W praktyce refresh token żyje nie więcej niż 12h zatem. Czego dotyczy więc okres 3 miesięcy? Ilu sprzedawców korzysta z API raz na kilka tygodni?

**Comment by PrzemyslawLukanowski** [comment]
Po użyciu refresh tokena otrzymujesz nowa parę tokenów - access i refresh, dla których obowiązują nowe daty użyteczności. Stare tokeny w tym momencie tracą ważność. 
Dziękuje za przekazane uwagi. Przekażę je do zespołu odpowiedzialnego za proces autoryzacji.

**Comment by Onixarts** [comment]
Wiem, że tak jest, dlatego nie rozumiem po co jest 3 miesięczna ważność tokena, skoro i tak jest on 1-2 razy na dobę wymieniany u przeciętnego sprzedawcy :).

**Comment by troncomputers** [comment]
Ja mam taki automat. Problem polega na tym, że z niewiadomych przyczyn refresh token jest nieważny jeśli usługa nie działa/pracuje przez dwa dni (jest wyłączona). Zgłaszałem to już nie raz i z waszej strony (jak zwykle) jest wszystko super extra pro elo. Usługa działa miesiąc, z nie wiadomych przyczyn nie działa 2 dni i pufff... `refresh token is invalid`. Najłatwiej jest zwalić bezpieczeństwo na "użytkownika". Idąc waszym tokiem rozumowania o auth 2.0: "Jeśli by ci kazali włożyć rękę do ognia to wkładasz?"

Argument jest kiepski, ponieważ to są tylko zalecenia, wady. Nie jesteście małą firmą i nie pracują tam głupi ludzie. Wyjdźcie na przeciw, zbuntujcie się, zróbcie coś swojego. Dajcie nam żyć...

**Comment by pkrzemo** [comment]
@troncomputers Skoro tylko u ciebie występuje problem, to jaki jest sens zmieniać system allegro oraz potencjalnie systemy innych sprzedawców tylko dlatego że nie potrafisz poprawnie napisać swojego kawałka oprogramowania bądź poprawnie skonfigurować swój system? U mnie, a także wydaje mi się że u innych też, ten problem nie występuje. Nie szukaj więc problemu u innych tylko u siebie. ;)

@Onixarts 3 miesięczna ważność refresh_tokena jest potrzebna po to aby sprzedawca mógł wyłączyć swój system na 2 miesiące i pojechać na covid-wakacje, a potem przejść kwarantannę i zdążyć uruchomić system zanim refresh_token straci ważność. ;)

**Comment by troncomputers** [comment]
@pkrzemo 
To ciekawe dlaczego po paru dniach nie działania mojego systemu, refresh_token jest nieważny. To też jest problem po mojej stronie?

**Comment by pkrzemo** [comment]
@troncomputers  Jest wiele scenariuszy w których sam sobie możesz unieważnić token.. Możesz  np. pobrać nowy i go nie zapisać...
Możesz też mieć kilka procesów odpalonych jednocześnie które wzajemnie sobie nadpisują tokeny... itp. itd.
Skoro u innych ten problem nie występuje, to trzeba najpierw zająć się swoją częścią systemu.. ;-)

**Comment by troncomputers** [comment]
@pkrzemo A możesz mnie jakoś nakierować jak u ciebie jest to rozwiązane. Mam 5 kont allegro do ogarnięcia. I zawsze jest tak, że wszystkie 5 mają niepoprawny refresh_token, co jest dziwne. Muszę wtedy znowu wszystko od nowa generować i powiązywać z kontami allegro. Muszę korzystać z device_flow, ponieważ to jest usługa, a nie www i nie mam gdzie przekierowania zrobić.
