### ISSUE TITLE
Empty user_name on client_credencials

### ISSUE THREAD

**Issue by AiMediaSK** [allegro/allegro-api#3640]
Hi,

i use client_credentials an i need to find offers from specific seller - i do it with api call "/offers/listing?seller.id='.$seller_id", and it returns offers correctly.
But then i need description of each offer, so i need to call - "/sale/offers/'.$offer->id", and i get message "Empty user_name claim".

I read docs and i think i need DCR authorization, so i send message to contact form, but they pointed me to github issues... 
My question is, where can i get Software statement ID? Is my approach to this data correct?

Thank you for your time

**Comment by PrzemyslawLukanowski** [comment]
To get access to this endpoint, you should use a token from [code](https://developer.allegro.pl/en/auth/#app) flow or [device](https://developer.allegro.pl/en/auth/#DeviceFlow) flow authorization. To retrieve offer data you need to be authorized as a seller who is the owner of this offer. You won't be able to download offers from all of the sellers on Allegro even if you are using DCR.
In our [documentation](https://developer.allegro.pl/en/documentation/) you can find information, which type of authorization you should use for selected resource:
[
![83610079-53962580-a57f-11ea-9fd4-fe31a7fb9162](https://user-images.githubusercontent.com/51473661/92729029-ffff5900-f371-11ea-98d4-26185f01632b.png)
](url)

- bearer-token-for-user - code or device flow,

- bearer-token-for-application - client credentials flow - access only to public resources, without user context, e.g. GET /offers/listing  GET /sale/categories.
