### ISSUE TITLE
Get an order's details Can you return the courier cabinet address information?

### ISSUE THREAD

**Issue by Lzw1300** [allegro/allegro-api#3642]
Hi,

If the buyer chooses the express cabinet to receive the goods, in addition to the buyer’s delivery address, the buyerShippingMethod is currently returned, but there is no address information related to the delivery method, so that it can only be delivered to the buyer’s delivery address instead of the express cabinet address.

Thanks

**Comment by PrzemyslawLukanowski** [comment]
If by the express cabinet you mean delivery method such as Allegro Paczkomaty 24/7 InPost (id 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93) we return the address in the **delivery.pickupPoint** field:

```
"pickupPoint": {
                    "id": "POZ12A",
                    "name": "Paczkomat POZ12A",
                    "description": "Przy Galerii Malta",
                    "address": {
                        "street": "Maltańska 1",
                        "zipCode": "61-131",
                        "city": "Poznań"
                    }
                }
```

**Comment by Lzw1300** [comment]
I received the email, thank you support team.
