### ISSUE TITLE
Wysyłka paczek

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3643]
Staram się zaimplementować wysyłkę paczek przez Wasz moduł "Wysyłam z Allegro". Chciałbym dowiedzieć się czy możliwe jest 

Udostępniacie tabelę możliwych kombinacji metod dostawy. 
![obraz](https://user-images.githubusercontent.com/68945711/92880279-28d52c00-f40e-11ea-981c-87875f3e7e37.png)

Rozumiem że nie ma jakiegoś zasobu zwracającego możliwe usługi dostawy dla konkretnego zamówienia.
Przykładowo jeżeli kupujący wybrał metodę Allegro Kurier DPD to żeby w zwrotce było tylko Allegro DPD.

Jak to w takim razie mapować? Powinien po swojej stronie utworzyć jakieś mapowanie które dla odpowiednich ID metod dostawy zwróci odpowiednie Id usług dostawy sprzedawcy?

Znalazłem również informację na temat metod wysyłek:
[metody dostawy](https://developer.allegro.pl/news/2019-01-30-metody_dostawy/)

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadamy takiego zasobu. Prawidłowym rozwiązaniem może być to, o którym wspominasz, czyli np. jeżeli w zamówieniu w polu delivery.method.id zwróciliśmy c3066682-97a3-42fe-9eb5-3beeccab840c (Allegro Kurier DPD) lub 259b5c7a-9056-4c74-80ec-8bdc50cb0413 (Allegro DPD Kurier Pobranie), to przypisz do danej przesyłki usługę dostawy {id_usługi_dostawy_przez_umowe_własną} lub {id_usługi_dostawy_Allegro_DPD}, w zależności od tego, na jakiej umowie wysyłasz paczkę. Pełną listę id i nazw metod dostawy znajdziesz w odpowiedzi dla [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET).
