### ISSUE TITLE
Powiadomienie dla Odbiór własny w punkcie

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3644]
Witam, nie moge znaleźć takiej informacji, dlatego zapytam
Czy po tym jak zmienię w api status zamówienia na SENT, to czy dla Odbioru własnego w punkcie sprzedawcy jest wysyłane powiadomienie ( na maila) że "przesyłka" jest gotowa do odbioru?
Ewentualnie czy jest jakiś mechanizm którego można użyć? niestety z jakiś przyczyn nie dostaje mail z allegro od wtorku ( nie wiem z jakiej przyczyny ) wiec ciężko mi cokolwiek zweryfikować

**Comment by PrzemyslawLukanowski** [comment]
Nie wysyłamy takiej wiadomości. Kupujący otrzyma maila jedynie po zakupie przedmiotu. Informacje na temat gotowości do odbioru powinny zostać uwzględnione w sekcji [Punkty odbioru](https://allegro.pl/moje-allegro/sprzedaz/punkty-odbioru), dzięki czemu kupujący będzie mógł je zobaczyć w ofercie, w zakładce Dostawa i płatność.
