### ISSUE TITLE
Dodanie auta z napędem elektrycznym wymaga podania pojemności silnika

### ISSUE THREAD

**Issue by serten-d** [allegro/allegro-api#3646]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas dodawania pojazdu osobowego, jeżeli ustawiony jest rodzaj paliwa jako napęd elektryczny, API nadal wymaga podania pojemności silnika. 
(zaobserwowane w kategorii 145065)

**Comment by PrzemyslawLukanowski** [comment]
Napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - API odzwierciedla w tym momencie zachowanie z frontu, gdzie ten parametr również jest obowiązkowy w takiej sytuacji.
