### ISSUE TITLE
my Sandbox account cannot create new products

### ISSUE THREAD

**Issue by dingzheyan** [allegro/allegro-api#3647]
my Sandbox account cannot create new products
![image](https://user-images.githubusercontent.com/28720657/92985188-edf0f800-f4e2-11ea-8cda-89cee960f0a8.png)

**Comment by jakub-adamski** [comment]
Potwierdzam, jakoś od miesiąca nic tam nie działa. Żałosne i nieprofesjonalne jest to, że muszę wszystko testować na produkcji u klienta.

**Comment by PrzemyslawLukanowski** [comment]
Try to use this [link](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie).

**Comment by dingzheyan** [comment]
> Try to use this [link](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie).

![image](https://user-images.githubusercontent.com/28720657/93148494-7d3a1d80-f726-11ea-8f0c-4ea9cd2bae4b.png)

**Comment by dingzheyan** [comment]
my accout has create new products ,thanks
