### ISSUE TITLE
Problem ze stroną dokumentacji

### ISSUE THREAD

**Issue by rafalkrupinski** [allegro/allegro-api#3649]
na stronie [dokumentacji](https://developer.allegro.pl/documentation/#) nie przewija się
 nagłówek, w efekcie czego połowa ekranu jest zajęta przez zielone tło, a tylko druga połowa na przeglądanie dokumentacji. Firefox.

Bardzo proszę o odzepsucie strony

**Comment by hahyes** [comment]
https://developer.allegro.pl/redoc/redoc-static.html

Proszę, dokumentacja bez ramki.

**Comment by PrzemyslawLukanowski** [comment]
@rafalkrupinski Wiemy już o problemie dot. przeglądarki Firefox, będziemy to weryfikować.

**Comment by rafalkrupinski** [comment]
provlem nadal występuje

**Comment by PrzemyslawLukanowski** [comment]
Pamiętamy o tym zadaniu. Poinformuję w tym wątku po tym, jak uda się wyeliminować problem.
