### ISSUE TITLE
Czy zgodnie z regulaminem mogę przenieść swoich znajomych do siebie na swoją stronę? Czy mogę mieć przycisk "przenieś na Allegro i 'kup teraz' na Allegro"? Czy Allegro pozwala na pobieranie ogłoszeń i współpracuje z innymi serwisami?

### ISSUE THREAD

**Issue by dertof** [allegro/allegro-api#3650]

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już podobne pytania w zgłoszeniu przez formularz kontaktowy. Prośba o cierpliwość, udzielimy na nie odpowiedzi.

**Comment by dertof** [comment]
Dziękuję bardzo.-- Krzysztof DeręgowskiOd: "PrzemyslawLukanowski" &lt;notifications@github.com&gt;Do: "allegro/allegro-api" &lt;allegro-api@noreply.github.com&gt;; Wysłane: 8:59 Poniedziałek 2020-09-14Temat: Re: [allegro/allegro-api] Czy zgodnie z regulaminem mogę przenieść swoich znajomych do siebie na swoją stronę? Czy mogę mieć przycisk "przenieś na Allegro i 'kup teraz' na Allegro"? Czy Allegro pozwala na pobieranie ogłoszeń i współpracuje z innymi serwisami? (#3650)

Otrzymaliśmy już podobne pytania w zgłoszeniu przez formularz kontaktowy. Prośba o cierpliwość, udzielimy na nie odpowiedzi.

**Comment by dertof** [comment]
Dzień dobry,
proszę o odpowiedź na jakim etapie znajduje się moje zapytanie, z wyrazami wdzięczności
Krzysztof Deręgowski

**Comment by PrzemyslawLukanowski** [comment]
Uzyskaliśmy już odpowiedzi od odpowiedniego działu. W najbliższym czasie powinien Pan otrzymać odpowiedź na zgłoszenie wysłane przez formularz kontaktowy.
