### ISSUE TITLE
where is the commandId

### ISSUE THREAD

**Issue by Kevin-qs** [allegro/allegro-api#3651]
I want to modify the price and inventory through the following interface, but where is the commandId, you generated it or we defined it yourself, and then uploaded it. Your document does not have relevant instructions, but it says that the commandId parameter is required.
PUT / sale / offer-price-change-commands / {commandId}
PUT / sale / offer-quantity-change-commands / {commandId}

**Comment by PrzemyslawLukanowski** [comment]
Command Id is a string of characters in UUID format, you can find some example [here](https://developer.allegro.pl/en/about/#ids).       UUID can be generated via free online tools - just type "UUID generator" in the search browser.

**Comment by Kevin-qs** [comment]
OK,Thank you
