### ISSUE TITLE
PUT order/checkout-forms/{id}/fulfillment SellerOrdersStoreUnprocessableEntityException

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3652]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas próby zmiany statusu zamówienia otrzymuję błąd

PUT order/checkout-forms/{id}/fulfillment

array:1 [
  "status" => "SENT"
]

```
{#1292
  +"errors": array:1 [
    0 => {#1234
      +"code": "SellerOrdersStoreUnprocessableEntityException"
      +"message": null
      +"details": null
      +"path": "/order/checkout-forms/1cce8a82-e461-11ea-ae92-713de2fd4c96/fulfillment"
      +"userMessage": null
    }
  ]
}
```

trace-id: 25130bae417930e9

Problem pojawia się jak próbuję drugi raz nadać ten sam status zamówienia (zamówienie ma już status SENT). Dla innych zamówień ( np. trace-id9209e2942465288f ) mogłem ustawić status taki sam więcej razy.

**Comment by PrzemyslawLukanowski** [comment]
Każde zamówienie posiada limit operacji, jakie można na nim wykonać. W przypadku tego zamówienia limit został przekroczony - głównie ze względu na bardzo dużą liczbę operacji, które dotyczyły zmiany statusu realizacji zamówienia.

**Comment by lukeroot** [comment]
Hi @PrzemyslawLukanowski - We've had the same issue with one of our sandbox orders `56ff6340-a1cd-11ef-b5a7-9b0ca307ce2b`, this was down to an American/English spelling issue (`CANCELLED`/`CANCELED`) during the testing we've currently undergoing. 

Would it be possible for you to unlock this order so I can resend the correct status? Thanks

**Comment by PrzemyslawLukanowski** [comment]
Sorry, but this is a global blockade that cannot be lifted. I recommend to create just a new order and test this feature on it.

**Comment by lukeroot** [comment]
@PrzemyslawLukanowski just tried again with a brand new order `9eb03390-a1cd-11ef-b5a7-9b0ca307ce2b` and the very first API PUT gave the exact same error output 
![image](https://github.com/user-attachments/assets/f8be9e73-36e7-4407-bfff-c92f099bec88)

Can you advice further please thanks

**Comment by lukeroot** [comment]
Cancel this request @PrzemyslawLukanowski I believe I've found the issue on my end. Apologies there thanks a lot for your help
