### ISSUE TITLE
API stock and price update fail

### ISSUE THREAD

**Issue by Kevin-qs** [allegro/allegro-api#3653]
PUT  
https://api.allegro.pl/sale/offer-price-change-commands/fab2c3f2-41ae-bfeb-d972-240c321aa41b
JSON
{"modification":{"type":"FIXED_PRICE","price":{"amount":"769.69","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"9670979098"}]}]}
response
[state] => 400
    [response] => Array
        (
            [errors] => Array
                (
                    [0] => Array
                        (
                            [code] => ERROR
                            [message] => An error has occurred
                            [details] => 
                            [path] => /sale/offer-price-change-commands/fab2c3f2-41ae-bfeb-d972-240c321aa41b
                            [userMessage] => 
                        )

                )

        )
Where is the problem with the data I submitted

**Comment by PrzemyslawLukanowski** [comment]
Your request is correct, You can try to use 769.69 instead of "769.69" and send a request again. Does the problem still occur?

**Comment by Kevin-qs** [comment]
Still the same error

**Comment by Kevin-qs** [comment]
Can this problem be solved?

**Comment by PrzemyslawLukanowski** [comment]
We verify your problem, I will come back with the answer.

**Comment by Kevin-qs** [comment]
What's the progress

**Comment by PrzemyslawLukanowski** [comment]
I have forwarded this issue to the appropriate team. I'll be back with an answer when I get a reply.

**Comment by Kevin-qs** [comment]
Thank you very much and look forward to your reply

**Comment by Kevin-qs** [comment]
I have found the reason, it is because json adds a backslash to escape
like this
{\"modification\":{\"type\":\"FIXED_PRICE\",\"price\":{\"amount\":769.69,\"currency\":\"PLN\"}},\"offerCriteria\":[{\"type\":\"CONTAINS_OFFERS\",\"offers\":[{\"id\":\"9670979098\"}]}]}
