### ISSUE TITLE
Problem z aktywacją sprzedaży na koncie i działaniem /sale/offers

### ISSUE THREAD

**Issue by tomaszk23** [allegro/allegro-api#3654]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję utworzyć ofertę poprzez POST na /sale/offers - oferta się tworzy, ale z błędem: ERR_IF_YOU_WANNA_SELL , przykładowy numer oferty: 7678552869 . Z tego co widzę, chodzi o uprawnienia do sprzedaży - próbowałem aktywować sprzedaż, ale od wczoraj mam info: "Nie możesz jeszcze sprzedawać.
Poczekaj na weryfikację swoich danych. O jej wyniku poinformujemy Cię e-mailem w ciągu 3 dni roboczych." , prosiłbym o pełne aktywowanie konta na Sandboxie.

**Comment by tomaszk23** [comment]
Login: tomaszk23

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by tomaszk23** [comment]
Dzięki
