### ISSUE TITLE
Błędy zwracane przez PUT i POST /points-of-service

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#3655]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

```
{
	"code": "ConstraintViolationException",
	"message": "Przesłany formularz zawiera błędy walidacji.",
	"details": "Invalid value: ",
	"path": "address.state",
	"userMessage": "must not be blank"
}
```

```
{
	"code": "ConstraintViolationException",
	"message": "Przesłany formularz zawiera błędy walidacji.",
	"details": "Invalid value: ",
	"path": "name",
	"userMessage": "must not be blank"
}
```

Rozumiem, że guideline poszedł do kosza?

**Comment by AureliuszBrussy** [comment]
Czy możesz doprecyzować, czego dokładnie dotyczy Twój problem?

**Comment by TimothyKoval** [comment]
[https://github.com/allegro/restapi-guideline#generate-structured-errors](https://github.com/allegro/restapi-guideline#generate-structured-errors)

**Comment by AureliuszBrussy** [comment]
Dziękuję za informację, zgłosiłem prośbę o doprecyzowanie komunikatu i dostosowanie go do guideline'u do odpowiedniego zespołu.
