### ISSUE TITLE
Offers - Internal server error

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3657]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy próbie wystawienia aukcji występuje błąd 500, występuje on cały czas przy próbie wystawienia oferty
Przesyłam request i response, proszę o analizę

REQUEST 2020-09-15 09:09:15.9097283 
curl -X POST \
  'https://api.allegro.pl/sale/offers' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer  \

  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"e2701b99-c08f-4a79-873a-8c588652ac06"},"returnPolicy":{"id":"93139d5d-102b-45df-b841-dda5682ed919"},"warranty":{"id":"108e0684-b0aa-4011-bee3-0bee47273427"}},"attachments":null,"category":{"id":"260081"},"compatibilityList":null,"contact":null,"createdAt":null,"customParameters":null,"delivery":{"additionalInfo":null,"handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"109f36d6-4da0-4f8e-8a55-d277d2412581"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/118c5a/15d1a10943f48748f51c66537c61"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/115582/10d77de245169d3d448cdb1bf293"},{"type":"TEXT","content":"<p><b>Zlewka PP 500 ml skala tłoczona&nbsp;</b></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Pojemność: 500 ml Średnica: 89 mm Wysokość: 120 mm Podziałka: 10 ml Materiał: PP</p>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1136fa/8ced10ee46e4ab507b2e45eab8ae"},{"type":"TEXT","content":"<p>Wszystkie nasze zamówienie realizujemy zgodnie ze standardem&nbsp;<b>BIOSPACE ZERO WASTE</b>.</p>\r\n\r\n<p>Opracowany przez nas system umożliwia&nbsp;bezpieczne dostarczanie do Państwa zamówień bez użycia tworzyw sztucznych.</p>\r\n\r\n<p>Jak to robimy?&nbsp;Do pakowania zamówień używamy wyłącznie kartonów, tektury, papieru i wytrzymałej papierowej taśmy klejącej.</p>\r\n"}]}]},"ean":"","external":{"id":"01/02-11104"},"fundraisingCampaign":null,"id":null,"images":[{"url":"https://a.allegroimg.com/original/115582/10d77de245169d3d448cdb1bf293"},{"url":"https://a.allegroimg.com/original/118c5a/15d1a10943f48748f51c66537c61"},{"url":"https://a.allegroimg.com/original/1136fa/8ced10ee46e4ab507b2e45eab8ae"}],"location":{"city":"Poznań","countryCode":"PL","postCode":"61-619","province":"WIELKOPOLSKIE"},"name":"Zlewka PP 500 ml skala tłoczona","parameters":[{"id":"11323","rangeValue":null,"values":null,"valuesIds":["11323_1"]},{"id":"224017","rangeValue":null,"values":["01"],"valuesIds":null},{"id":"17448","rangeValue":null,"values":[""],"valuesIds":null},{"id":"237194","rangeValue":null,"values":["BioSpace"],"valuesIds":null},{"id":"210786","rangeValue":null,"values":["500"],"valuesIds":null},{"id":"225157","rangeValue":null,"values":null,"valuesIds":["225157_310645"]},{"id":"224745","rangeValue":null,"values":null,"valuesIds":["224745_309477"]}],"payments":{"invoice":"VAT"},"product":{"id":"ce0b6808-a132-4cf1-a83e-f2508656f897"},"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"7.49","currency":"PLN"},"minimalPrice":null,"startingPrice":null,"netPrice":null},"tax":null,"sizeTable":null,"stock":{"available":50,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-09-15 09:09:17.7065908  Duration: 1796,8625ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (500) Internal Server Error.",
      },
  "TraceId": "948fd11b4b0bd047",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**Comment by AureliuszBrussy** [comment]
Problem występuje, ponieważ w parametrze “ean” przekazujesz pusty string. Usuń ten parametr z payloadu lub przekaż null. Rozumiem natomiast, że w tym przypadku nie powinniśmy zwrócić błędu 500. Zgłosiłem ten problem do odpowiedniego zespołu.

**Comment by SebastianOzdoba** [comment]
To jest bardzo dziwne, na innym koncie tego samego Klienta przechodzi bez błędów. Nie powinien faktycznie zwracać błędu 500 tylko poprawny komunikat

**Comment by SebastianOzdoba** [comment]
Problemem nie jest EAN, tylk opis, raz na jakiś czas zwraca poprawnie błąd

{
"code": "VALIDATION_ERROR",
"message": "Nieprawidłowy podzbiór HTML",
"details": "Invalid value: <p><b>Zlewka PP 500 ml skala tłoczona&nbsp;</b></p>rnrn<p>&nbsp;</p>rnrn<p>Pojemność: 500 ml Średnica: 89 mm Wysokość: 120 mm Podziałka: 10 ml Materiał: PP</p>rn",
"path": "description.sections[1].items[1].content",
"userMessage": "Nieprawidłowy podzbiór HTML"
}
