### ISSUE TITLE
Brak możliwości wylogowania się z sandbox-a

### ISSUE THREAD

**Issue by DanBSixin** [allegro/allegro-api#3658]
Występuje problem: 
- [ X ] ze środowiskiem testowym

Po zalogowaniu się do sanbox-a, chciałem się przelogować na inne konto, ale nie ma takiej możliwości (nie można się wylogować). Menu: "Moje Allegro", górny "pasek" wygląda tak jakbym był nie zalogowany, ale i tak mogę poruszać się po swoim koncie, podglądać zamówienie, itp., konto to: Sixin, w czym może być problem?

**Comment by AureliuszBrussy** [comment]
Wiemy o tym problemie (sprawa została już poruszona w #3576). Na tę chwilę, aby go uniknąć, edytuj jedną z informacji w zakładce Dane konta (np. zmiana województwa). Po zmianie - przycisk umożliwiający wylogowanie powinien się pojawić.

**Comment by SebastianOzdoba** [comment]
F12 w przeglądarce, Application \ Clear storage i Cię wyloguje ;)
