### ISSUE TITLE
Allegro Inpost paczkomaty / Kurier - generowanie etykiet w IAI

### ISSUE THREAD

**Issue by phenomena4** [allegro/allegro-api#3659]
Posiadam sklep na platformie IAI. Potrzebuję danych API umożliwiających generowanie etykiet kurierskich bezpośrednio z panelu IAI. Nie jestem biegły z "programowania" Będę wdzięczny za łopatologiczną pomoc :)

**Comment by AureliuszBrussy** [comment]
Nie wiemy, w jaki sposób aplikacja której używasz korzysta z naszego API. Skontaktuj się z twórcami tego narzędzia, aby dowiedzieć się w jaki sposób pobrać za jego pomocą interesujące Ciebie dane. Możesz pobrać dane zamówienia bezpośrednio za pośrednictwem naszego API, skorzystaj z [GET /order/checkout-forms/{checkoutForm_id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET). Cały proces opisaliśmy w [naszym poradniku](https://developer.allegro.pl/orders/#szczeg%c3%b3%c5%82y-zam%c3%b3wienia) dotyczącym obsługi zamówień.

Dodatkowo, do generowania etykiet możesz wykorzystać [Wysyłam z Allegro](https://wysylam.allegro.pl/).

**Comment by krzysda** [comment]
Nawiązując do problemu z tytułu (INPOST) zauważyłem coraz częstsze (wcześniej było to sporadycznie) problemy z adresem e-mail podczas generowania etykiet do paczkomatów. Zdarza się że otrzymujemy komunikat z INPOST błędny adres e-mail chociaż adres zgadza się z tym pobranym przez API a także tym po zalogowaniu się do Allegro (zakładka zamówienia). 

Rozumiem że INPOST sprawdza na podstawie adresu mailowego czy zamówienie posiada usługę SMART czy nie (związanie z naliczeniem opłat) ale problem pojawia się nawet w zamówieniach które nie mają usługi SMART i skutecznie blokuje możliwość wygenerowania etykiety (praktycznie nie ma możliwości wygenerowania etykiety do takiego zamówienia automatycznie)

**Comment by AureliuszBrussy** [comment]
@krzysda pamiętaj, że abyś mógł wygenerować etykietę w narzędziu InPostu, Klient musi zakończyć płatność (w przypadku przedpłaty). Jeżeli mimo zakończenia płatności problem występuje - proszę, zgłoś go bezpośrednio do InPostu, ponieważ nie ma mamy wpływu na działanie ich narzędzi.
