### ISSUE TITLE
Modyfikacja istniejących aukcji - REST API

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#366]
Cześć,
jak długo może zając modyfikacja aukcji przez REST API?  
W poleceniu wrzuconym przez RESTAPI wczoraj około południa (commandid = 7382B444-A992-40E2-9DC8-3E87AB02377D) było 10 tyś aukcji do zmiany.
Przed chwilą sprawdziłem status wykonania powyższego polecenia za pomocą /sale/offer-publication-commands/{commandId}/tasks - 695 ofert ma status = NEW, reszta SUCCESS. Czy mam ponawiać niewykonane polecenia?

**Comment by sis6326r** [comment]
Nic się nie zmieniło. Nadal 695 ofert ze statusem NEW.

**Comment by AniaMalinowska** [comment]
Prośba, abyś ponowił request. Jeśli problem będzie nadal, to podeślij nam Trace-ID.

**Comment by sis6326r** [comment]
Ponowiłem, przetworzyło prawidłowo całość. Niestety następny reqest: 3D5D8A7D-7B35-4351-A1DF-F36BBB6343A8 nie wykonał się do końca. 
{"id":"3d5d8a7d-7b35-4351-a1df-f36bbb6343a8","taskCount":{"total":80595,"success":80592,"failed":0}}.
Request wrzucony około 12:30.

**Comment by AniaMalinowska** [comment]
W takiej sytuacji podeślij nam Trace-ID.

**Comment by sis6326r** [comment]
Świeży przypadek: modyfikacja cennika dostaw na 75360 aukcjach. 
CommandId: 675E6852-1D8A-4AE4-922B-F67EEC960CFC 
TraceId: e26d9784acbfb71f 

11 pozycji wisi w statusie NEW.

**Comment by sis6326r** [comment]
i następne TraceId z którymi jest problem

666b0a084fb813ce
1a369cc5f66893a6
2a1ef48dd5195c01
5a2d10b49a991a5
53cbbb242ad44d65
bb6cdf7143e1dfd0
c1cf2cfb1b21d565
44d566f51b805672
559a82861f6747a3
95348754af1956f6
f77e5e549aba3b39
573b507737888f6b
f8546966682fbacd
3a42f10bff8fb6c6
c522bd4890abc927
daa1e7fd7d7061f4
7536cb7bd2f1b6e5
5a65215839f249cc
203efa9546154c0c


666b0a084fb813ce
--
1a369cc5f66893a6
2a1ef48dd5195c01
5a2d10b49a991a5
53cbbb242ad44d65
bb6cdf7143e1dfd0
c1cf2cfb1b21d565
44d566f51b805672
559a82861f6747a3
95348754af1956f6
f77e5e549aba3b39
573b507737888f6b
f8546966682fbacd
3a42f10bff8fb6c6
c522bd4890abc927
daa1e7fd7d7061f4
7536cb7bd2f1b6e5
5a65215839f249cc
203efa9546154c0c

**Comment by LukaszKorek** [comment]
Poprosimy też o przykładowy request, prześlij go za pomocą formularza https://allegro.pl/pomoc/kontakt

**Comment by sis6326r** [comment]
json wystarczy?

**Comment by LukaszKorek** [comment]
Poprosimy o pełnego curla z headerem.
