### ISSUE TITLE
Aktywacja konta: sandbox_omecon

### ISSUE THREAD

**Issue by aktywacjaOmecon** [allegro/allegro-api#3660]
Czy mona prosić o aktywację konta j.n. z góry dziękuję

**sandbox_omecon**

**Comment by AureliuszBrussy** [comment]
Wstępnie aktywowałem twoje konto. Aby dokończyć aktywację, wjedź w zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) i prześlij dwa dowolne pliki.

**Comment by rdzierwa** [comment]
Czy mogę prosić o aktywację konta nsystems ? mail filmsmp@gmail.com

**Comment by MaciejFrackowiak** [comment]
@rdzierwa Twoje konto jest już aktywne.

**Comment by rdzierwa** [comment]
Prośba o aktywację jeszcze firmowego

**Comment by MaciejFrackowiak** [comment]
@rdzierwa Jak widzę konto zostało już zweryfikowane jako firmowe.
