### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by dingzheyan** [allegro/allegro-api#3663]
I get access_token  from  https://allegro.pl/auth/oauth/token?grant_type=client_credentials
than  i   visit   https://api.allegro.pl/order/checkout-forms?fulfillment.status=NEW&fulfillment.status=处理中
Accept :application/vnd.allegro.public.v1+json
Authorization:Bearer $token
it tell me ：
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}

**Comment by AureliuszBrussy** [comment]
To get access to this endpoint, you should use a token from [code flow](https://developer.allegro.pl/auth/#app) or [device flow](https://developer.allegro.pl/auth/#DeviceFlow) authorization. With client_credentials flow you will get access only to resources marked as “bearer-token-for-application” in the “Authorizations” section in [documentation](https://developer.allegro.pl/en/documentation/).
