### ISSUE TITLE
Dodanie produktu do istniejącej oferty

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#3664]
Próbuję połączyć istniejącą ofertę z produktem. Oferta ma dodany EAN. Postępują w następujący sposób.
1. GET /sale/offers/{offer.id} - pobieram ofertę, żeby mieć draft i ean
2. GET /sale/products?ean=EAN - sprawdzam czy istnieją jakieś produkty
3. w drafcie z punktu 1. zmieniam pole product, które było null na produkt.id z punktu 2.
4. PUT /sale/offers/{offer.id} 

Otrzymuję błąd: Given product has TecDoc specification but it is not assigned to offer, use product TecDoc specification. Update offer with the most recent product data.

Moje oferty mają uzupełnione różne parametry w zależności od kategorii i myślałam, że tak jak przy łączeniu po stronie frondendu zostaną one nadpisane przez to co znajduje się w produkcie. W jaki sposób wykonać to poprawnie, przy założeniu, że są to produkty z TecDoc i istnieją w Państwa bazie.

**Comment by AureliuszBrussy** [comment]
Za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProducts) pobierz parametry produktu. Prócz nich uzyskasz także tecdocSpecification (specyfikację TecDoc) i compatibilityList (sekcję Pasuje do). Te dane także przekaż w strukturze oferty. Tylko wtedy powiązanie oferty z produktem zakończy się powodzeniem.  

Zachęcam także do korzystania z zasobu [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), dzięki któremu w jednym wywołaniu wystawisz ofertę powiązaną z produktem, co opisujemy w [naszym poradniku](https://developer.allegro.pl/product_offers/). Wystarczy, że przekażesz w żądaniu EAN produktu, a dane produktu zostaną w ofercie automatycznie uzupełnione.

**Comment by martacronic** [comment]
Po paru próbach scalenia parametrów z TecDoc z innymi parametrami, które ma oferta udało się zgodnie z powyższymi wskazówkami połączyć istniejącą ofertę z produktem. 

Rozumiem, że sytuacja idealna jest gdy wystawiam ofertę od razu łącząc z produktem, ale jak ktoś już ma tysiące aukcji i część ma sprzedaż lub jest obserwowana, to jesteśmy zmuszeni pracować na istniejących ofertach.

@AureliuszBrussy Nasuwa to teraz pytanie. Na ten moment kategoria nie ma compatibilityList. Czy jeśli oferta w tej kategorii została połączona z produktem z TecDoc, to jak w kategorii pojawi się opcja compatibilityList to w takiej ofercie pojawi się sekcja "Pasuje do" czy będzie trzeba ponownie pobrać produkt i uzupełnić to pole w ofercie?

**Comment by martacronic** [comment]
@AureliuszBrussy W trakcie dalszych prac pojawił się błąd Given category does not support TecDoc specification.
W jaki sposób posiadając id kategorii zweryfikować czy wspiera ona tecdocSpecification?

**Comment by AureliuszBrussy** [comment]
Jeżeli w danej kategorii pojawi się możliwość dodania **compatibilityList** - będziesz mogą uzupełnić te dane samodzielnie. Jeżeli **compatibilityList** równocześnie pojawi się w produkcie powiązanym z ofertą w takiej kategorii, będziesz musiała uzupełnić tą sekcję na podstawie tego produktu. Aktualnie pracujemy nad tym, aby taka operacja była prosta do zrealizowania. 

Nie udostępniamy zasobu, dzięki któremu mogłabyś sprawdzić, czy dana kategoria wspiera **tecdocSpecification**. Natomiast jeżeli dana kategoria nie wspiera **tecdocSpecification**, to produkt będący w tej kategorii także nie powinien zwrócić identyfikatora specyfikacji TecDoc. Jeżeli trafiłaś na taki przypadek - proszę prześlij id tego produktu.

**Comment by tomasz-grzesik** [comment]
Dzień dobry,

chciałem zapytać jak można z automatu uporać się z tego typu błędami?
"Wskazana sekcja "Pasuje do" jest nieaktualna, podepnij najnowszą wersję dla tego produktu. Zaktualizuj dane produktowe w ofercie. Wskazana specyfikacja techniczna TecDoc nie jest najnowszą wersją dla tego produktu. Zaktualizuj dane produktowe w ofercie."

Czy wystarczy uaktualnić listę Pasuje do zgodnie z wynikami zwróconymi przez metodę /sale/compatibility-list-suggestions?
Skoro wymagana jest taka sama lista jak w produkcie, to dlaczego nie jest to z automatu aktualizowane?

**Comment by AureliuszBrussy** [comment]
Uaktualnij w ofercie dane o produkcie wraz z listą Pasuje do - aby pobrać te dane (razem z **compatibilityList**), skorzystaj z GET /sale/products/{productId}.

Na ten moment nie chcemy aktualizować danych w produkcie bez zgody sprzedającego.

**Comment by tomasz-grzesik** [comment]
Ok. Rozumiem.
