### ISSUE TITLE
Data ostatniej sprzedaży oferty

### ISSUE THREAD

**Issue by Dawid-IziGSM** [allegro/allegro-api#3665]
Czy za pomocą API mogę pobrać informację na temat daty ostatniej sprzedaży danej oferty? Przykładowo wysyłam request z id oferty na jakiś zasób i w odpowiedzi otrzymuję informację z datą ostatniej sprzedaży w danej ofercie. Czy taka informacja jest zwracana wśród istniejących zasobów?

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy zasobu lub pola, gdzie mógłbyś sprawdzić datę ostatniej sprzedaży. Mamy taką funkcję na naszej liście sugestii. Jeżeli udostępnimy taką możliwość, opublikujemy odpowiedni komunikat.
