### ISSUE TITLE
Czy Publish command detailed report jak zwróci task ze statusem "SUCCESS" to gwarantuje aktywacje oferty

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3666]
Czy [Publish command detailed report](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) jak zwróci task ze statusem "SUCCESS" to oznacza, że oferta już jest aktywowana, czy że aktywacja jest w kolejce i gwarantuje jej aktywacje?

**Comment by AureliuszBrussy** [comment]
Status "SUCCESS"oznacza, że zadanie zostało poprawnie przetworzone i maksymalnie w ciągu godziny zmiana statusu oferty będzie widoczna na stronie.

**Comment by AnimalDEV** [comment]
Dziękuje
