### ISSUE TITLE
Cache'owanie parametrów produktyzowanego produktu

### ISSUE THREAD

**Issue by Rafal-dev-php** [allegro/allegro-api#3669]
Witam,

Wysyłamy dużo zapytań pod adres /sale/products/{productId}, w celu pobrania parametrów produktyzowanego produktu. Często się zdarza, że prosimy o ten sam produkt i przy większej ilości użytkowników dostajemy zwrotkę 429. W związku z tym chcielibyśmy wprowadzić cache parametrów, tak, aby nie odpytywać wielokrotnie zasobu o dany produkt. 

Proszę mi powiedzieć, czy taki cache ma sens? Potrzebujemy tych parametrów na etapie tworzenia oferty, żeby wyświetlić użytkownikowi odpowiedni formularz, oraz mechanizmów automatycznych. Mamy obawy, że przy dynamicznie zmieniających się parametrach produktu, oraz wymagań, czy dany parametr jest obowiązkowy/nie obowiązkowy do wystawienia oferty taki cache nie będzie powodował problemów. 
Może macie Państwo, lepsze rozwiązanie?

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Cache może być rozwiązaniem, natomiast jest to zależne od częstotliwości zapytań oraz długości cache. Przy krótkim, kilkuminutowym cache problem z nieaktualnym produktem nie występowałby często. 

Dodatkowo, skoro problem uwidacznia się przy większej ilości użytkowników - wygląda na to, że korzystasz z jednego tokena do pobierania danych o produkcie, zamiast z wielu tokenów należących do konkretnych użytkowników. Zasób GET /sale/products/{productId} ma [dodatkowy limit](https://developer.allegro.pl/about/#Leaky_Bucket) liczby zapytań dla użytkownika.
