### ISSUE TITLE
Sandbox - błąd pobierania listy kampanii

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#3671]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Chcę pobrać listę dostępnych kampanii zasobem GET /sale/badge-campaigns
Ale zwraca mi błąd "Konto nie jest Kontem Firma" natomiast w panelu mam informację "Rodzaj konta: Konto firmowe"

Trace-ID: 1770df68cb7d037e

**Comment by AureliuszBrussy** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu. Wrócę z informacją.

**Comment by avello** [comment]
Minął tydzień, kiedy mogę się spodziewać poprawy?

Dodam od razu jeszcze drugi problem, który prawdopodobnie uniemożliwi mi testowanie kampanii na sandboxie.
W "Moje oferty" -> "Akcje" nie mam możliwości zgłoszenia oferty do kampanii, a w "Jakość mojej sprzedaży" mam "Nie możemy Ci pokazać danych o Twojej jakości sprzedaży" pomimo że zrobiłem kilka testowych zakupów na tym koncie.

**Comment by AureliuszBrussy** [comment]
@avello pracujemy jeszcze nad rozwiązaniem problemu. Wyjaśniam też kwestię związaną z "Jakością mojej sprzedaży". Proszę o jeszcze trochę cierpliwości.

**Comment by avello** [comment]
Czekam nadal na rozwiązanie problemu

**Comment by AureliuszBrussy** [comment]
Tak, pamiętam o tym problemie. Bardzo proszę o jeszcze trochę cierpliwości.
