### ISSUE TITLE
rest api Problem z parametrami

### ISSUE THREAD

**Issue by redactive596** [allegro/allegro-api#3673]
Witam,

Używam res api i endpointu

chciałem po parametrze doprecyzować zapytanie i mam problem

`/offers/listing?category.id=312565&offset=0&limit=60&price.to=2&parameter.11323=11323_1`

powonieniem moim zdaniem dostać zwrotnie tylko nowe z ceną do 2 zł
a dostaję wszystkie z tej kategorii z ceną do 2 zł, co robię źle?
Sprawdziłem w filters i mam ten parametr.

**Comment by AureliuszBrussy** [comment]
Nie potwierdzam występowania tego problemu. Skorzystałem ze skonstruowanego przez Ciebie żądania i otrzymałem w wyniku 4 oferty, które rzeczywiście spełniają kryteria podane w parametrach. Oferty te pokrywają się z tymi, które otrzymałem podczas tego samego wyszukiwania na stronie. Czy możesz przesłać response jaki otrzymujesz? Możesz go skrócić do samych ofert, dodając parametry **&include=-all&include=items&include=searchMeta**.

**Comment by redactive596** [comment]
No to jeszcze jedno:

`/offers/listing?category.id=312565&sort=+price&offset=1&limit=60&price.to=1&parameter.247137=247137_645901`

zwracam mi:
promoted: 5 rekordy
regular: 46 rekordy

a powinno ok 18-tu
```
    [searchMeta] => stdClass Object
        (
            [availableCount] => 52
            [totalCount] => 52
            [fallback] => 
        )
```
sprawdziłem [filters]

`stdClass Object
                (
                    [id] => price
                    [type] => NUMERIC
                    [name] => cena
                    [values] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [idSuffix] => .from
                                    [name] => od
                                    [selected] => 
                                )

                            [1] => stdClass Object
                                (
                                    [idSuffix] => .to
                                    [value] => 1
                                    [name] => do
                                    [selected] => 1
                                )

                        )

                    [minValue] => 0
                    [maxValue] => 1000000000
                    [unit] => zł
                )`
jest dobrze

ale tutaj:
`(
                    [id] => parameter.247137
                    [type] => MULTI
                    [name] => Typ silnika (n)
                    [values] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [value] => 247137_645901
                                    [name] => benzynowy
                                    [count] => 18
                                    [selected] => 
                                )

                            [1] => stdClass Object
                                (
                                    [value] => 247137_645905
                                    [name] => Diesel
                                    [count] => 27
                                    [selected] => 
                                )

                            [2] => stdClass Object
                                (
                                    [value] => 247137_645909
                                    [name] => elektryczny
                                    [count] => 0
                                    [selected] => 
                                )

                            [3] => stdClass Object
                                (
                                    [value] => 247137_645913
                                    [name] => hybrydowy
                                    [count] => 0
                                    [selected] => 
                                )

                        )

                )`

tutaj przy silniku benzynowy też powinno być selected - a nie jest
trace-id: b62618fbb740a4c3

**Comment by AureliuszBrussy** [comment]
Nie udało mi się powtórzyć tego problemu - dla dokładnie takiego samego zapytania, otrzymuję w odpowiedzi prawidłową liczbę ofert (18). Konsultuję sprawę z odpowiednim zespołem.

**Comment by AureliuszBrussy** [comment]
Nie potwierdzamy tego problemu. Zweryfikowaliśmy to wielokrotnie, na wielu kontach - API zwraca prawidłowe wyniki.
