### ISSUE TITLE
How to stop advertising sales?

### ISSUE THREAD

**Issue by Kevin-qs** [allegro/allegro-api#3674]
As the title says, we now want to temporarily stop sales, but the API cannot directly modify the inventory to 0. Which interface should I call to stop advertising sales?

**Comment by Kevin-qs** [comment]
As the title says, we now want to temporarily stop sales, but the API cannot directly modify the inventory to 0. Which interface should I call to stop advertising sales?

**Comment by PrzemyslawLukanowski** [comment]
You should use [PUT /sale/offer-publication-commands/{commandId} ](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) to end or suspend your offers. In your structure provide:

```
{
    "publication": {
        "action": "END"           
    },
    "offerCriteria": [
        {
            "offers":[ 
                {
                    "id": "{offerID}"
                }
            ],
            "type": "CONTAINS_OFFERS"            
        }
    ]
 }
```

**Comment by Kevin-qs** [comment]
OK,I tried it and it was ok, thanks
