### ISSUE TITLE
Problem z autoryzacja (oauth)

### ISSUE THREAD

**Issue by rafalandryanczyk** [allegro/allegro-api#3676]
Cześć, mam problem z autoryzacją konta po przez metodę "authorization_code", próbowałem już przeróżnych kombinacji, niestety bezskutecznie. Testowałem requsta w PHP, shellu oraz postmanie, wszędzie z takim samym skutkiem, mianowicie jeżeli "code" jest aktywny otrzymuje błąd: 

`{
    "error": "invalid_request",
    "error_description": "Unauthorized"
}`

tutaj zrzut requesta z postmana:

```
POST /auth/oauth/token HTTP/1.1
Host: allegro.pl.allegrosandbox.pl
Authorization: Basic ZmE1YTc1OTgxMGU5NDA5ODk3ODc3NWU5NGQ4NGFkODI6eTBZNE1zZGZZRU12dGFTa3R3azR0U1pONFJoMGFyMmZHdzFqQ2JweEl3NW9VTjZIdlB4RTRpbXBMZ2E2OVBUYw==
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: a9a0a2d7-9292-037c-3b7b-fa149306af9f

grant_type=authorization_code&code=1MuXt5iEugTLDNymej9OJNqmpX9Q2D6s&redirect_uri=https%3A%2F%2Fdemoapi.easy-sync.pl%2Fapi%2Fallegro%2Fauth
```

widziałem w innych wątkach że macie jakieś logi, czy możecie sprawdzić je o co dokładnie chodzi? Jak dobrze rozumiem, wg. api wysyłam błędny "basic" token, natomiast jestem w 100% pewny że dane są poprawne. Będę bardzo wdzięczny za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
W swoich żądaniach, za pomocą których otrzymujesz authorization code przez /auth/oauth/authorize, przekazujesz także parametry dot. PKCE - code_challenge i code_challenge_method. Pomijasz je jednak, kiedy próbujesz wygenerować token, dlatego otrzymujesz Unauthorized. Jeżeli chcesz korzystać z PKCE, przekaż dodatkowo parametr code_verifier z odpowiednią wartością, gdy wysyłasz request na auth/oauth/token. Jeśli nie - usuń nadmiarowe parametry ze swojego pierwszego żądania.
