### ISSUE TITLE
<!-- błąd podczas pobierania zamówień z wysylam.allegro.pl -->

### ISSUE THREAD

**Issue by DariuszGryciuk** [allegro/allegro-api#3677]
Występuje problem: <! błąd podczas pobierania zamówień z https://wysylam.allegro.pl/konto/zamowienia>
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
<! Allegro LKJ_pl: Odpytywany zasób nie istnieje w API. Oryginalny błąd: "checkout form of id ef2b56b2-f538-11ea-9e87-bb07adadf940 not found">

**Comment by PrzemyslawLukanowski** [comment]
Podaj nam proszę więcej szczegółow. Kiedy otrzymujesz ten błąd? Podczas korzystania z jakiego zasobu?

**Comment by DariuszGryciuk** [comment]
Po kliknięci przycisku Pobierz zamówienia. Ostatnie zamówienia ana liście mam z 2020-09-12
12:04

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, przycisk funkcjonuje prawidłowo. Ponieważ problem występuje na stronie internetowej i nie jest bezpośrednio powiązany z problemami technicznymi API - skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by DariuszGryciuk** [comment]
Jak działa prawidłowo jak ja za każdym razem jak go naciskam to błąd się pojawia i nie pojawiają się nowe zamówienia od 12 września?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy ten problem na kilku kontach i za każdym razem udało się pobrać nowe zamówienia. Tak jak wspomniałem wcześniej, opisz swój problem i prześlij go za pomocą [formularza kontaktowego.](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)

**Comment by DariuszGryciuk** [comment]
Ok, zrobiłem zgłoszenie przez formularz i podałem i link do tego zgłoszenia.
