### ISSUE TITLE
Problem z pobraniem szczegółów zamówienia

### ISSUE THREAD

**Issue by kajko-pl** [allegro/allegro-api#3678]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas synchronizacji zamówień od czasu do czasu otrzymujemy błąd "checkout form of id 708e1661-d9a6-11ea-af24-092caaf64bde not found".

Nasz flow wygląda tak:
Pobranie eventów x 2 (READY_FOR_PROCESSING + FULFILLMENT_STATUS_CHANGED):
- GET order/events (https://api.allegro.pl/order/events?type=READY_FOR_PROCESSING&from=1597992171798207&limit=100)
- GET order/events (https://api.allegro.pl/order/events?type=FULFILLMENT_STATUS_CHANGED&from=1597992171798207&limit=100)

Następnie dla każdego unikalnego pobranego checkoutFormId leci GET order/checkout-forms/:checkoutFormId. I tu od czasu do czasu wpada właśnie błąd z kodem "CheckoutFormNotFoundException".

Przykładowy request:
`GET https://api.allegro.pl/order/checkout-forms/708e1661-d9a6-11ea-af24-092caaf64bde`

Przykładowy response:
`{"http_code":404,"data":{"errors":[{"code":"CheckoutFormNotFoundException","message":"checkout form of id 708e1661-d9a6-11ea-af24-092caaf64bde not found","details":null,"path":"/order/checkout-forms/708e1661-d9a6-11ea-af24-092caaf64bde","userMessage":null}]}}`

Czym jest spowodowane takie zachowanie API?

**Comment by PrzemyslawLukanowski** [comment]
Podany przykład opisaliśmy w naszym [FAQ](https://developer.allegro.pl/faq/#zam%c3%b3wienia):

> **W dzienniku zdarzeń otrzymałem event FILLED_IN z konkretnym numerem zamówienia. Kiedy przekazuję ten numer w GET /order/checkout-forms/{id} w odpowiedzi otrzymuję status 404 z informacją, że nie znaleziono takiego zamówienia. Co się z nim z stało?**
> 
> Kupujący najprawdopodobniej wykonał oddzielne zakupy, a następnie łącznie je opłacił. Otrzymasz nowy event z nowym numerem zamówienia, a stare usuniemy. Aby zidentyfikować taką sytuację możesz oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

W tym przypadku możemy oprzeć się na lineItem.id 708e1662-d9a6-11ea-af24-092caaf64bde. Najpierw wystąpiło w zamówieniu 708e1661-d9a6-11ea-af24-092caaf64bde (które pobrali Państwo przy okazji zmiany statusu realizacji tego zamówienia, przy evencie FULFILLMENT_STATUS_CHANGED). Następnie kupujący połączył zakupy w jedną płatność i powstało zamówienie 47d8a221-e63b-11ea-bdba-f1253b87b629, tym samym zamówienie 708e1661-d9a6-11ea-af24-092caaf64bde zostało usunięte.

**Comment by kajko-pl** [comment]
Dziękuję za wyczerpującą odpowiedź, teraz wszystko jest jasne.
