### ISSUE TITLE
Aktywacja kont na sansboxie.

### ISSUE THREAD

**Issue by pkoziolandrobit** [allegro/allegro-api#3679]
Już dobrze ponad 3 dni czekamy na aktywacje kont na sandboxie:
m.stochlik@androbit.com
p.koziol@androbit.com

Czy można prosić o aktywację?

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem konta. W przypadku firmowego konta androbit proszę jeszcze przesłać dwa dowolne pliki przez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta), aby zakończyć aktywację.

**Comment by pkoziolandrobit** [comment]
Bardzo dziękuję. Czy można poprosić jeszcze o konto `androbit_seller`?

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem konto.

**Comment by pkoziolandrobit** [comment]
Działa. Dziękuję.
