### ISSUE TITLE
ERR_INVALID_STATE: Niepoprawna wartość w polu określającym województwo.

### ISSUE THREAD

**Issue by FreelinePL** [allegro/allegro-api#368]
W wystawianych aukcjach zmieniony został kraj na USA (id 163). Dla tego kraju nie ma określonych województw, więc w fid=10 ustawiam wartość 0. API krzyczy mi błędem 

> ERR_INVALID_STATE: Niepoprawna wartość w polu określającym województwo.

Jak ustawić fid 10, gdy w fid 9 ustawiamy inny kraj niż Polska?

**Comment by MarcinLuczak** [comment]
@FreelinePL odpowiedź jest prosta - nie ustawiać :) Fid 10, czyli 'Województwo' jest nieobowiązkowy. Dla innego kraju niż Polska nie musisz go ustawiać.
