### ISSUE TITLE
Środowisko testowe dla Wysyłam inpost

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3680]
Chciałbym przetestować wysyłkę za pomocą Inpost w środowisku testowym przez co muszę podpiąć umowę własną. Czy w środowisku testowym należy dodać produkcyjne Client ID oraz Klucz autoryzacyjny otrzymane od Inpost?

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku zgłoś się proszę do InPost, czy posiadają takie testowe dane. Jeśli nie, możesz przetestować funkcjonalności np. dla DPD, UPS, PP.

**Comment by fjjjq** [comment]
Dziękuję, kontaktuje się z InPost w tej sprawie.
