### ISSUE TITLE
problem z aktywacją oferty

### ISSUE THREAD

**Issue by burnburnburn123** [allegro/allegro-api#3681]
Od jakiegoś czasu mam problemy z aktywowaniem ofert. ponad połowa szkiców nie chce się aktywować. Natomiast szkice mają wszystkie dane poprawne, ponieważ po ręcznym wejściu w szkic(na koncie allegro) i zatwierdzeniu aukcja się wystawia.

Czy coś się zmieniało w ostatnich miesiącach? Przez ostatnie miesiące aktywacja draftów działała bez problemu, a od ok 2 miesięcy mam ciągłe problemy z aktywacją draftów.

Poniżej przykładowy zrzut z logów z próby aktywacji oferty. Prosze o pomoc w analizie problemu.
Czy mozecie sprawdzić czemu ten draft się nie aktywował?

URL: https://allegroapi.io/sale/offer-publication-commands/09d87dee-5c43-46e7-9308-413c71cadd49
OPTIONS: Array
(
    [http] => Array
        (
            [method] => PUT
            [header] => Authorization: Bearer ***
Api-Key: foreginbooks_apiKey
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
            [content] => {"offerCriteria":[{"offers":[{"id":"9721727030"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}
            [ignore_errors] => 1
        )

)

**Comment by PrzemyslawLukanowski** [comment]
Możesz sprawdzić przyczynę błędu, odpytując GET /sale/offers/9721727030. W sekcji validation.errors zwracamy komunikat:

`
You cannot publish offer without a related product because you have too few offers related to a product in that category. Select or create a new product and associate it with your offer.`

Próbujesz wystawić ofertę w kategorii, w której wymagamy 1% sproduktyzowanych ofert. Więcej informacji znajdziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/3332).

**Comment by burnburnburn123** [comment]
Dziękuję za szybką odpowiedz.  Jednak coś się nie zgadza.  
Na koncie widzę "Połączono 843 z wymaganych 101 ofert.    8.3%"     , czyli ośmiokrotnie przewyższam limit, a nadal nie mogę aktywować draftów.

**Comment by burnburnburn123** [comment]
To chyba jednak błąd.  
Historia była taka.
- wystawiałem aukcje
- allegro nie zliczało na bieżąco liczby połączonych ofert z produktami, wiec zablokowało wystawianie = tworzyły się drafty
- zaktualizowała się liczba połączonych ofert "Połączono 843 z wymaganych 101 ofert. 8.3%"
- draftów nadal nie można aktywować = są zablokowane.

Ale nowe aukcje już mogę wystawiać (zapewne znowu do czasu aż proporcje spadną poniżej 1% połączenia".

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe numery ofert, z którymi nadal masz problem? Sprawdziłem niektóre szkice i udało się aktywować m.in. 9721727030, 9724340506, 9724350706 ale dla części draftów nie było jeszcze próby aktywacji, np. 9724338114. Dla innych zwracamy błąd, ale tym razem jest związany z czym innym, np. 9724258001 - zbyt długi tytuł oferty, 9724220126, 9724205825, 9724205740 - zbyt długie słowo w tytule (tytuły wyglądają na nieprawidłowe).

**Comment by burnburnburn123** [comment]
np. 9721725742       [id] => ff78cde2-8ee3-4fc4-a233-5eca8cf10723

Dla pewności sprawdziłem. Zalogowałem się na konto, wszedłem w szkice. Widniała tam pomimo wysłania komendy do aktywacji.
Następnie wszedłem ręcznie w szkic(z poziomu panelu) i kliknąłem "wystaw aukcję" - wystawiła się bez problemu, czyli  w ofercie nie było błędów.
Mam takich szkiców w kolejce ponad 10tys, wiec nie mogę tego ręcznie klikać.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam problem, zwrociliśmy błąd, mimo że wymóg 1% został spełnioniony. Przekazałem problem do odpowiedniego zespołu, wrócę z informacją.

**Comment by burnburnburn123** [comment]
Dziękuję.
Mi zależy na tym abym jak najszybciej mógł aktywować te drafty za pomocą API  lub abyście Wy mi je wszystkie aktywowali jeśli problem miałby występować dłużej niż 24 godziny. Oczywiście aktywacja ma dotyczyć tylko tych, które nie mają innych błędów jak zbyt długa nazwa.

**Comment by burnburnburn123** [comment]
Czy coś się ruszyło w sprawie zgłaszanego problemu?

**Comment by PrzemyslawLukanowski** [comment]
Prośba jeszcze o cierpliwość. Czy możesz powtórzyć operację aktywacji dla części starszych ofert? Ostatnia próba miała miejsce 21.09.2020, aktualnie spełniasz wymóg 1%, więc operacje powinny zakończyć się powodzeniem. Natomiast dla dużej części nowych ofert zwracamy już błędy innnego rodzaju, np. `Invalid parameter Number of Pages(223493) `, `Value is too short in parameter Series(223497)`, `The value of a parameter "Title" contains illegal characters: ¨. `

**Comment by burnburnburn123** [comment]
Problem nadal występuje.
Wykonałem próbę dla 500 najstarszych rekordów, a następnie dla 500 rekordów gdzieś ze środka listy czekających na akceptację.
np. 90f3463f-f4c3-41ce-b643-9a2ad3dd5b7d     - tu nie aktywowało oferty, ale gdy minute później z konta allegro kliknąłem edycję i wystawienie oferty to bez problemu wystawiło aukcję bez modyfikacji danych w ofercie.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
@burnburnburn123 Problem nie powinien już występować. Spróbuj proszę aktywować przykładowe oferty.

**Comment by burnburnburn123** [comment]
Potwierdzam. Działa. Dzięki.
