### ISSUE TITLE
Wysyłanie obrazków do Allegro

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#3683]
Witam,

Mam pytanie odnośnie przesyłania obrazków do Allegro. Dlaczego pewne zdjęcia są odrzucane przez allegro? Jako przykład mogę podać: 
![zdjecie](https://user-images.githubusercontent.com/23072296/93876904-df22f600-fcd7-11ea-9f59-6d1a9d75861a.png)

**Comment by PrzemyslawLukanowski** [comment]
Zdjęcie jest w formacie, którego nie wspieramy z naszej strony - RIFF, natomiast mime-type to: image/webp (wspieramy tylko image/jpeg i image/png). Format pliku możesz sprawdzić za pomocą jednego z dostępnych, bezpłatnych narzędzi.

**Comment by mrezlik** [comment]
Dziękuję za odpowiedź :)
