### ISSUE TITLE
Problemy z integracją Shoplo/wfirma

### ISSUE THREAD

**Issue by KarolinaCiesielska** [allegro/allegro-api#3684]
Dzień dobry!
Mamy problem z integracją pomiędzy systemami, w wyniku czego nie fakturują nam się wszystkie zamówienia. System zamówień w allegro mamy zintegrowany z panelem sklepu Shoplo, gdzie z kolei fakturowanie zamówień jest zintegrowane z wfirma. Od jakiegoś czasu obserwujemy braki w zamówieniach złożonych przez allegro w zestawieniach faktur z wfirma - zamówienia natomiast normalnie przechodzą z allegro do systemu Shoplo.

Skontaktowałam się w tej sprawie z Shoplo i początkowo otrzymałam informację, że jest to kwestia braku ITN od PayU.
Po kontakcie z PayU z kolei, dowiedziałam się, że dla podanych przypadków nie zostało przesłane żądanie do PayU. Po porównaniu zestawień w panelu PayU, rzeczywiście nie pojawiają się tam wspomniane zamówienia.

Czy mogą Państwo zweryfikować, gdzie pojawia się problem w przekazywaniu zamówień?

**Comment by SebastianOzdoba** [comment]
@KarolinaCiesielska to jest forum dla developerów. Powinnaś skontaktować się z supportem Shoplo lub wFirma. 
Jeśli masz pytanie dotyczące API Allegro to możesz śmiało pisać, forumowicze lub Allegro Ci pomoże :)

**Comment by KarolinaCiesielska** [comment]
@SebastianOzdoba skontaktowałam się z supportem Allegro, dostałam informację od p. Anity Kwircińskiej, cytuję: "W zgłoszonej przez Panią sprawie najlepszym rozwiązaniem będzie przesłanie zgłoszenia bezpośrednio poprzez ścieżkę przeznaczoną dla API. W tym celu proszę skorzystać z poniższego linku: https://github.com/allegro/allegro-api"

**Comment by PrzemyslawLukanowski** [comment]
@KarolinaCiesielska W Twoim przypadku powinnaś w pierwszej kolejności skontaktować się z supportem oprogramowania, z którego korzystasz. Nie wiemy, w jaki sposób te aplikacje funkcjonują i jak korzystają z naszego API. Jeśli deweloperzy stwierdzą problemy po naszej stronie - wtedy prośba o kontakt z nami wraz z logami, które będą nam niezbędne do wykrycia źródła problemu.
