### ISSUE TITLE
API problem z pobieraniem i aktualizacją 

### ISSUE THREAD

**Issue by AlekKlepacz** [allegro/allegro-api#3686]
Występuje problem: 
 - [ x] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Dziś od rana.

Przy pobieraniu i  aktualizacji danych.

Nieznany blad wystapil w serwisie Allegro - wystapil w serwisie Allegro - commandRequest 

Nieznany blad wystapil w serwisie Allegro - wystapil w serwisie Allegro - commandRequestAukcja o nr 78327.... - Offer id cannot be changed.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać więcej szczegółów? Przy wykorzystaniu jakich zasobów otrzymujesz taki komunikat? Czy posiadasz przykładowe trace-id?

**Comment by AlekKlepacz** [comment]
bezpośrednia komunikacja systemem sklepowym. Pierwszy:
Nieznany blad wystapil w serwisie Allegro - wystapil w serwisie Allegro - polecenieRequest
przy próbie pobrania zamówień.
Drugi:
Nieznany blad wystapil w serwisie Allegro - wystapil w serwisie Allegro - commandRequestAukcja o nr 78327 .... - Identyfikatora oferty nie można zmienić.
przy próbie zaktualizowania stanu magazynowego istniejących ofert.

nie posiadam trace-id.

**Comment by PrzemyslawLukanowski** [comment]
O te dane, o których wspomniałem, możesz poprosić autorów oprogramowania, z którego korzystasz. Nie odnotowaliśmy błędów z naszym API, a przytoczone komunikaty pochodzą z Twojego systemu - problem może być zatem powiązany z działaniem Twojej aplikacji. 
Podaj proszę w takim razie przykładowy numer oferty. Jeśli nie chcesz go wklejać tutaj, użyj naszego [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i powołaj się na zgłoszenie GitHub #3686. Spróbujemy na tej podstawie dojść do tego, czy w tym przypadku problemy wystąpiły po naszej stronie.

**Comment by AlekKlepacz** [comment]
Dane o które była prośba wysłałem przez formularz. Proszę o informacje zwrotną czy udało się coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi - problem z pobieraniem zamówień ustąpił, otrzymujesz prawiłowe odpowiedzi 200. Wczorajsze statusy 401, które wystąpiły sporadycznie od 13:00, związane były z tym, że ok. 11 usunąłeś powiązanie z aplikacją. Innych przypadków dla sytuacji z rana nie znalazłem, dlatego jeśli problem wystąpi w przyszłości prośba o przykładowe logi z żądań do naszego API.

Problemy z aktualizacją ofert związane są z tym, że wszystkie wartości, jakie przekazujesz to null. Poniżej przesyłam przykładową strukturę, którą otrzymujemy, np. dla oferty *******130:

```
{
	"id": null,
	"seller": {
		"id": "****"
	},
	"name": null,
	"product": null,
	"category": null,
	"parameters": [],
	"ean": null,
	"description": null,
	"compatibilityTable": null,
	"tecdocSpecification": null,
	"images": [],
	"sellingMode": null,
	"tax": null,
	"stock": {
		"available": 7,
		"unit": null
	},
	"publication": {
		"duration": null,
		"status": null,
		"startingAt": null,
		"endingAt": null,
		"endedBy": null,
		"countryCode": "PL",
		"republish": false
	},
	"delivery": null,
	"payments": null,
	"afterSalesServices": null,
	"additionalServices": null,
	"sizeTable": null,
	"fundraisingCampaign": null,
	"location": null,
	"external": null,
	"attachments": null,
	"contact": null,
	"promotion": null,
	"validation": null,
	"createdAt": null,
	"updatedAt": null
}
```
Najpierw powinieneś pobrać dane oferty za pomocą GET /sale/offers/{offerID} a następnie, wraz z naniesionymi nowymi danymi, przesłać strukturę za pomocą PUT /sale/offers/{offerID}.

**Comment by AlekKlepacz** [comment]
Dziękuje. ja tylko podałem jedną aukcje ale problem z komunikacją cały czas występuje. Nie mogę pobierać zamówień, nie mogę wystawiać nowych ofert. Zwracałam się do administracji serwera o sprawdzenie połączenia i otrzymałem odpowiedź.
Nie mogę wykonać połączenia z poziomu serwera www obsługującego Państwa stronę do strony allegro.pl:



www22:~$ telnet allegro.pl 80

Trying 5.134.213.82...

telnet: Unable to connect to remote host: Connection timed out



www22:~$ mtr allegro.pl

www22 (93.157.99.148) 2020-09-23T20:56:58+0200

Packets Pings

Host Loss% Snt Last Avg Best Wrst StDev

1. 2.96.157.93.ip.ogicom.net 0.0% 9 2.4 1.8 1.5 2.5 0.4

2. host-185-73-89-21.oxylion.net.pl 0.0% 9 0.2 0.3 0.2 0.8 0.2

3. host-185-73-91-46.oxylion.net.pl 0.0% 9 0.3 0.3 0.2 0.6 0.1

4. host-185-73-91-45.oxylion.net.pl 0.0% 9 0.3 0.3 0.2 0.4 0.1

5. 193.242.168.102 0.0% 9 1.2 7.9 1.0 49.6 15.9

6. host-185-73-89-102.oxylion.net.pl 0.0% 9 19.3 10.2 8.9 19.3 3.4

7. host-185-73-89-114.oxylion.net.pl 0.0% 9 10.2 11.3 9.6 15.0 1.8

8. host-185-73-89-109.oxylion.net.pl 0.0% 9 19.6 19.6 19.5 19.7 0.1

9. allegropl.ip4.epix.net.pl 0.0% 9 20.8 22.3 20.7 27.6 2.7

10. ???





Z poziomu mojego laptopa:

$ mtr allegro.pl

My traceroute [v0.93]

dell (192.168.0.132) 2020-09-23T20:58:15+0200

Packets Pings

Host Loss% Snt Last Avg Best Wrst StDev

1. _gateway 0.0% 9 1.0 1.1 1.0 1.4 0.2

2. host-37-247-56-1.wtvk.pl 0.0% 9 1.5 2.3 1.5 3.6 0.8

3. 10.128.25.1 0.0% 8 1.8 2.6 1.8 3.9 0.7

4. 10.192.15.1 0.0% 8 1.2 1.3 1.1 1.7 0.2

5. 10.192.16.1 0.0% 8 1.0 1.2 1.0 1.5 0.2

6. allegro-gw.pozix.pl 0.0% 8 1.5 1.6 1.5 1.8 0.1

7. 194.0.251.254 0.0% 8 1.5 1.8 1.5 2.2 0.2

8. 5.134.208.54 0.0% 8 10.5 10.3 9.9 11.1 0.4

9. 5.134.208.27 0.0% 8 14.0 13.7 10.4 16.8 1.8

10. 5.134.213.82



$ telnet 5.134.213.82 80

Trying 5.134.213.82...

Connected to 5.134.213.82.

Escape character is '^]'.



Wygląda to tak, jakby blokada miała miejsce po stronie allegro.

Jakie dane mam podać do głębszej weryfikacji problemu.

**Comment by PrzemyslawLukanowski** [comment]
Nie mogę potwierdzić blokady z naszej strony. Ostatnie prawidłowe zapytanie nastąpiło o 09:09 - pobranie zamówień. Nie widzę jednak śladu po innych nieudanych operacjach (prócz edycji ofert), dlatego prosiłbym o przykładowe requesty i response'y w formacie cURL. Ze względu na wrażliwość danych proszę to przesłać za pomocą formularza - jak w poprzednim przypadku.

**Comment by AlekKlepacz** [comment]
Na chwile obecną problem rozwiązany. Na moim serwerze była blokada która została zdjęta. Dziękuje za wsparcie! Pozdrawiam
