### ISSUE TITLE
Oddzielne przesyłki dla jednego zamówienia Allegro Wysyłam

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3687]
Czy możliwe jest stworzenie dwóch oddzielnych przesyłek dla jednego zamówienia?

Przykładowo: 
Klient zamawia 3 produkty i aktualnie mamy tylko dwa na stanie a trzeci będzie dostępny dopiero jutro.
Chcemy wysłać towar jak najwcześniej więc musimy stworzyć przesyłkę dla dwóch produktów i zamawiamy dla nich kuriera. Co zrobić z trzecim produktem?

Wiem że teoretycznie możemy rozdzielić przesyłkę na 2 paczki, ale co w przypadku gdy okaże się że trzeba zmienić sposób wysyłki i następnego dnia będziemy musieli wysłać jednak 2 paczki a nie jedną jak wcześniej zadeklarowaliśmy.

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz utworzyć więcej niż jedną przesyłkę dla jednego zamówienia. Przy tworzeniu paczki, przekaż ten sam adres mailowy kupującego.
