### ISSUE TITLE
Jak obsłużyć zamówienia opłacane przelewem tradycyjnym?

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#3688]
Jak obsłużyć zamówienia opłacane przelewem tradycyjnym? 
zamówienia takie są cały czas ze statusem FILLED_IN

**Comment by PrzemyslawLukanowski** [comment]
Aby zamówienie opłacone przelewem tradycyjnym otrzymało status READY FOR PROCESSING, kupujący musi wypełnić dane przelewu zgodnie ze wzorem, który otrzyma po kliknięciu "Kupuję i płacę". Dzięki temu płatność zostanie prawidłowo przeprocesowana przez Allegro Finanse i zamówienie otrzyma odpowiedni status.

**Comment by ArturBakAxl** [comment]
A co w przypadku kiedy kupujący niepoprawnie wypełni przelew (bo tak). Nie ma możliwości oznaczenia go z poziomu allegro jako opłaconego?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości. Aby zamówienie otrzymało poprawny status RFP, kupujący może jedynie anulować poprzednie zamówienie i wykonać kolejne, przechodząc prawidłowo proces zakupu.
