### ISSUE TITLE
Błąd w dokumentacji  dla GET /sale/badge-campaigns

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#3689]
Na stronie dokumentacji https://developer.allegro.pl/badge/#1 w Przykładowy response chyba są błędy.
Pole application->type ma w opisie "UNTIL (przedział czasowy), WITHIN (do danego dnia)" wydaje mi się że powinno być odwrotnie.
To samo tyczy się pól publication->type oraz visibility->type

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie, w najbliższych dniach poprawimy informację w poradniku.
