### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#3690]
Problemy z sandbox:
1. Mam status konta firmowego, mimo wszystko nie mogę wystawiać ofert - zostaję przekierowany na https://staging-lokalnie.allegrogroup.com/oferty/wystaw
![image](https://user-images.githubusercontent.com/36500569/94017161-62634b00-fdaf-11ea-9be6-adcabc1460b0.png)

2. Po raz kolejny jestem jednocześnie zalogowany i wylogowany. Nie ma przycisku wyloguj, nie mogę przełączyć konta. https://streamable.com/aog888

**Comment by PrzemyslawLukanowski** [comment]
1. Skorzystaj w takim przypadku [z tego linku do wystawiania](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie).
2. Spróbuj w Danych konta zmienić jedną z wartości, np. województwo. Jeżeli problem nie ustąpi, podaj proszę id usera.

**Comment by rtnet-pl** [comment]
Dziękuję, działa
