### ISSUE TITLE
Aktywacja konta - SANDBOX

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3691]
Czołem, 

czy mógłbym prosić o aktywację konta na sandbox? Status cały czas : oczekuję na weryfikację.

login: mse

Z góry dzięki.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by LukaszCierocki** [comment]
@PrzemyslawLukanowski , dzięki. Tam zostały teraz przesłane dane do weryfikacji, na konto firmowe. Mógłbym prosić, o aktywację jako konto firmowe? :+1:

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto firmowe jest już prawidłowo aktywowane, powinieneś mieć dostęp do wszystkich operacji na sandboxie.
