### ISSUE TITLE
Opóźnienia GET /sale/offer-events

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#3693]
Dobrze mi się wydaje, że mieliście dzisiaj (2020.09.23) 10 godzinne opóźnienie w aktualizacji danych? Sprzedaże realizowane od rana, zaczęły pojawiać się na liście eventów OFFER_ENDED dopiero po 19:00.
W razie potrzeby służę danymi.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mogę tego potwierdzić - sprawdziłem nasze logi i eventy wysyłaliśmy zgodnie ze stanem faktycznym. Prześlij proszę swoje dane, zweryfikujemy to. Możesz je przekazać tutaj lub za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (wtedy dopisz, że problem dotyczy zgłoszenia na GitHubie #3693).

**Comment by lukada4100** [comment]
Oferta to pojedyncze kup teraz. OFFER_STOCK_CHANGED o 06:27, OFFER_ENDED 12 godzin później. Ta sama sytuacja dla kilkuset innych ofert.

{"id":"MTYwMDg0MjY3OTY3MTQxMQ","type":"OFFER_STOCK_CHANGED","occurredAt":"2020-09-23T06:27:12.632Z","offer":{"id":"9726837549","publication":null}}

{"id":"MTYwMDg4ODQyNTUwOTA1NQ","type":"OFFER_ENDED","occurredAt":"2020-09-23T19:13:34.000Z","offer":{"id":"9726837549","publication":{"endedBy":"EXPIRATION"}}}

**Comment by PrzemyslawLukanowski** [comment]
Przeanalizowałem ten temat z odpowiednim zespołem. Potwierdzam, że przedwczoraj, jak i wczoraj, mogły wystąpić opóźnienia związane z przetwarzaniem statusu publikacji oferty, co miało także wpływ na czas wystąpienia eventu OFFER_ENDED.
