### ISSUE TITLE
offer-price-change-commands problem

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#3694]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
wysyłany request:
{"modification":{"type":"FIXED_PRICE","price":{"amount":"69.90","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"9398372068"}]}]}
na url: 
https://api.allegro.pl/sale/offer-price-change-commands/4E0851A6-DA1F-FDA0-44CD-65B14E75A4C6

Otrzymany response"HTTP/1.1 201 Created expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block server: envoy pragma: no-cache x-frame-options: DENY trace-id: 80b031fad64689f date: Wed, 23 Sep 2020 21:12:34 GMT x-content-type-options: nosniff content-type: application/vnd.allegro.public.v1+json;charset=UTF-8 content-length: 92 x-envoy-upstream-service-time: 42 {"id":"4e0851a6-da1f-fda0-44cd-65b14e75a4c6","taskCount":{"total":0,"success":0,"failed":0}}" 
co jest grane czemu cena się nie zmienia? do tej pory wszystko śmigało.

**Comment by akxx87** [comment]
Również u mnie występuje problem, cena się nie zmienia.

**Comment by PrzemyslawLukanowski** [comment]
@marcinja2 Zmiana w ofercie może nastąpić do godziny czasu. W przypadku Twojej oferty cenę zmieniliśmy o 23:34. Co do samych zer w response - możesz otrzymać taką odpowiedź ze względu na asynchroniczne działanie zasobu. W momencie wysłania requestu, nie został on przez nas jescze przetworzony. Szczegółowy status zadania sprawdzisz za pomocą [GET /sale/offer-price-change-commands/{commandId}/tasks.](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET)

@akxx87 Czy w Twoim przypadku problem nadal występuje? Jeśli tak, podaj proszę przykładowe commandId.
