### ISSUE TITLE
Brak możliwości odświeżania tokenów - SANDBOX

### ISSUE THREAD

**Issue by LukaszCierocki** [allegro/allegro-api#3695]
Czołem, 

od godziny dostaję sygnały, że niemożliwe jest odświeżenia tokenów, rzuca błąd 504 Gateway Time-out.

Czy można prosić o weryfikację, czy ten błąd rzeczywiście ma miejsce?

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam problemy na Sandboxie, ma to związek z [przerwą techniczną](https://developer.allegro.pl/news/#sandbox-technical-break-24092020). Przepraszam za dalsze utrudnienia.
