### ISSUE TITLE
zmiana ilości

### ISSUE THREAD

**Issue by tomzara** [allegro/allegro-api#3696]
jak najszybciej zmienić ilość w aukcjach.
czy użycie PUT /sale/offer-quantity-change-commands/{commandId} także powoduje zmianę do godziny czasu?

**Comment by PrzemyslawLukanowski** [comment]
Tak, operacja zmiany liczby przedmiotów może zająć do godziny czasu, jednak w większości przypadków dzieje się to dużo szybciej.

**Comment by tomzara** [comment]
Czy jest jakieś szybsze rozwiązanie?

**Comment by tomzara** [comment]
Czy np. przez edycje oferty będzie szybciej?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku edycji oferty również może to zająć do godziny, chociaż - jak wspomniałem - z reguły dzieje się to dużo szybciej.

**Comment by tomzara** [comment]
Dzięki za informacje
