### ISSUE TITLE
Logowanie dla https://allegro.pl.allegrosandbox.pl przestało działac 

### ISSUE THREAD

**Issue by tomasprice** [allegro/allegro-api#3697]
Nie ma możliwości zalogowania się na https://allegro.pl.allegrosandbox.pl

Pozostała funkcjonalność strony działa, podczas logowania na konto nie ma reakcji ze strony  https://allegro.pl.allegrosandbox.pl

![Screenshot 2020-09-24 at 10 39 08](https://user-images.githubusercontent.com/37268276/94122034-55e3fe80-fe52-11ea-9531-4cc5b2d06e51.png)

**Comment by PrzemyslawLukanowski** [comment]
Problemy są związane z naszą [przerwą techniczną](https://developer.allegro.pl/news/#sandbox-technical-break-24092020), przepraszam za utrudnienia.
