### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3698]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o weryfikację, występowanie błędu jest bardzo częste
Przykładowy request poniżej

**- PROD**
REQUEST 2020-09-25 08:36:22.1354025 
curl -X PUT \
  'https://api.allegro.pl/sale/offers/9736215125' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"222b2238-faf9-4389-88b1-c961db126e59"},"returnPolicy":{"id":"a1c787bc-6009-4476-9c45-9ccf8a3e6669"},"warranty":{"id":"74991eb9-0a93-4106-9b33-a6c89b7295b2"}},"attachments":null,"category":{"id":"261233"},"compatibilityList":null,"contact":null,"createdAt":null,"customParameters":null,"delivery":{"additionalInfo":"","handlingTime":"PT120H","shipmentDate":null,"shippingRates":{"id":"ea8ba3a7-129b-4c59-929d-ff3ec6d8018e"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>PYCHOTKA JAGODA BIO 200 g - RUNOLAND</h1>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11cbc1/e7e112174781bc01a406a385d280"}]},{"items":[{"type":"TEXT","content":"<p>SKŁADNIKI jagoda czarna* (Vaccinium myrtillus), cukier trzcinowy*, substancja zagęszczająca - pektyny, sok z cytryny* (*certyfikowany składnik ekologiczny)</p>\r\n\r\n<p>OPIS Ekologiczna Jagoda Pychotka 80% owoców, pasteryzowana. Owocowy produkt do smarowania sporządzony z 80 g owoców jagody czarnej na 100 g wyrobu gotowego.</p>\r\n\r\n<p>WARTOŚĆ ODŻYWCZA W 100 g Wartość energetyczna - 523 kJ/127 kcal (6%**) Tłuszcz - 0 g (0%**) w tym kwasy tłuszczowe nasycone - 0 g (0%**) Węglowodany - 31 g (12%**) w tym cukry - 21 g (24%**) Białko - 0,6 g (1%**) Sól - 0 g (0%**) (**Referencyjna wartość spożycia dla przeciętnej osoby dorosłej (8400 kJ/2000 kcal)</p>\r\n\r\n<p>ZALECANE WARUNKI PRZECHOWYWANIA Przechowywać w suchym i chłodnym miejscu. Po otwarciu przechowywać w temp. +4 st. C.</p>\r\n\r\n<p>Producent - nazwa i adres:&nbsp;RUNOLAND SP. Z ORGANICZONĄ ODPOWIEDZIALNOŚCIĄ - SP. J., PODWALE 11, 56-200 GÓRA</p>\r\n\r\n<p>Kraj Producenta:&nbsp;Polska</p>\r\n\r\n<p>Kod produktu: 5901641005919&nbsp;</p>\r\n\r\n<p>EAN: 5901641005919</p>\r\n"}]}]},"ean":null,"external":{"id":"5901641005919"},"fundraisingCampaign":null,"id":"9736215125","images":[{"url":"https://a.allegroimg.com/original/11cbc1/e7e112174781bc01a406a385d280"}],"location":{"city":"GDYNIA","countryCode":"PL","postCode":"81-586","province":"POMORSKIE"},"name":"PYCHOTKA JAGODA BIO 200 g - RUNOLAND","parameters":[{"id":"237190","rangeValue":null,"values":["RUNOLAND"],"valuesIds":[]},{"id":"246245","rangeValue":null,"values":[],"valuesIds":["246245_1"]},{"id":"246253","rangeValue":null,"values":[],"valuesIds":["246253_583997"]},{"id":"235585","rangeValue":null,"values":["JAGODA"],"valuesIds":[]},{"id":"230801","rangeValue":null,"values":["200"],"valuesIds":[]},{"id":"233345","rangeValue":null,"values":[],"valuesIds":["233345_1"]},{"id":"10643","rangeValue":null,"values":[],"valuesIds":["10643_4"]},{"id":"130691","rangeValue":null,"values":[],"valuesIds":["130691_128"]},{"id":"224017","rangeValue":null,"values":["5901641005919"],"valuesIds":[]},{"id":"244509","rangeValue":null,"values":["PYCHOTKA JAGODA BIO 200 g"],"valuesIds":[]},{"id":"225693","rangeValue":null,"values":["5901641005919"],"valuesIds":[]},{"id":"17448","rangeValue":null,"values":["0.38"],"valuesIds":[]}],"payments":{"invoice":"VAT"},"product":{"id":""},"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"10.89","currency":"PLN"},"minimalPrice":null,"startingPrice":null,"netPrice":null},"tax":{"percentage":"5.00"},"sizeTable":null,"stock":{"available":10000,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-09-25 08:36:23.9635216
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "Warnings": null,
    "ValidatedAt": null
  },
  "Exception": {

  },
  "TraceId": "42a64c4e8a9650a8",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**- SANDBOX**
REQUEST 2020-09-25 08:39:21.9024642 
curl -X PUT \
  'https://api.allegro.pl.allegrosandbox.pl/sale/offers/7678590473' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"17129023-5ad3-47d6-8b87-0bef7986ee5a"},"returnPolicy":{"id":"5f97afb6-adb3-4598-9954-3385f5e66a67"},"warranty":{"id":"bda58d66-a9e3-46a3-bac5-7f37b26aefbf"}},"attachments":null,"category":{"id":"121340"},"compatibilityList":null,"contact":null,"createdAt":null,"customParameters":null,"delivery":{"additionalInfo":"","handlingTime":"PT0S","shipmentDate":null,"shippingRates":{"id":"33ef10e3-ff90-4741-a568-2fa370ea88bc"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Opis grupy super super elegancko buty elegancie do kościoła do restauracji.</p>"}]}]},"ean":null,"external":{"id":"NTOWN"},"fundraisingCampaign":null,"id":"7678590473","images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/11c864/db76084f444e88a1f41dc49a5fd2"}],"location":{"city":"Mielec","countryCode":"PL","postCode":"54-900","province":"LODZKIE"},"name":"Buciki Eleganckie","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]},{"id":"237190","rangeValue":null,"values":["gerg"],"valuesIds":[]},{"id":"219809","rangeValue":null,"values":["234"],"valuesIds":[]}],"payments":{"invoice":"NO_INVOICE"},"product":{"id":""},"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"200.00","currency":"PLN"},"minimalPrice":null,"startingPrice":null,"netPrice":null},"tax":null,"sizeTable":null,"stock":{"available":1,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-09-25 08:39:25.1211545 
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "Warnings": null,
    "ValidatedAt": null
  },
  "Exception": {
  
  },
  "TraceId": "6bbab8b074a44f41",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**Comment by PrzemyslawLukanowski** [comment]
Problem generuje dokładnie ten fragment struktury:

```
	"product": {
		"id": ""
	},
```

Problem znika, jeżeli zamiast zagnieżdżonego pustego stringa przekaże się null.

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski wcześniej to działało, np. wczoraj :). Poprawiamy po swojej stronie
