### ISSUE TITLE
Błąd podczas wystawiania aukcji na 20 dni trwania i "do wyczerpania"

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3699]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

mam problem z wystawianiem aukcji. Ustawienie `publication.duration` na `P20D` oraz na `null` (co dotychczas uważałem za odpowiednik "do wyczerpania") powoduje pojawienie się błędu przy wystawianiu `Invalid offer duration limit`. Coś się zmieniło w kwestii możliwych do ustawienia czasów trwania akcji? Była jakaś informacja, którą pominąłem?

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć Twojego błędu - po ustawieniu "P20D" w odpowiedzi otrzymuję prawidłową odpowiedź "PT480H", dla null - null. Podaj proszę przykładowe trace-id lub wklej tutaj swój json (z zamazaniem wrażliwych danych). Możesz także przesłać wszystkie dane za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), wtedy dopisz, że problem dotyczy zgłoszenia na GitHubie #3699.

**Comment by hahyes** [comment]
> Nie udało mi się powtórzyć Twojego błędu - po ustawieniu "P20D" w odpowiedzi otrzymuję prawidłową odpowiedź "PT480H", dla null - null. Podaj proszę przykładowe trace-id lub wklej tutaj swój json (z zamazaniem wrażliwych danych). Możesz także przesłać wszystkie dane za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), wtedy dopisz, że problem dotyczy zgłoszenia na GitHubie #3699.

Przykłady JSONów:
https://pastebin.pl/view/ff909dfc (przykład P20D)
https://pastebin.pl/view/31ae2d87 (przykład "do wyczerpania")

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, ale myślałem, że miałeś na myśli oferty typu Kup Teraz, ponieważ null dla licytacji oznaczałby, że jej koniec nie nastąpi nigdy. W przypadku licytacji, zgodnie z informacją w [naszym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty):

> Dla oferty typu AUCTION (licytacja) nie możesz
> podać wartości null i dostępne są wartości:
> P1D (1 dzień); P3D (3 dni); P5D (5 dni); P7D (7 dni);

**Comment by hahyes** [comment]
> Przepraszam, ale myślałem, że miałeś na myśli oferty typu Kup Teraz, ponieważ null dla licytacji oznaczałby, że jej koniec nie nastąpi nigdy. W przypadku licytacji, zgodnie z informacją w [naszym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty):
> 
> > Dla oferty typu AUCTION (licytacja) nie możesz
> > podać wartości null i dostępne są wartości:
> > P1D (1 dzień); P3D (3 dni); P5D (5 dni); P7D (7 dni);  P10D (10 dni)

Rozumiem, dziękuję za informacje. 👍
