### ISSUE TITLE
Problem z metodą doChangePriceItemRequest

### ISSUE THREAD

**Issue by PawelSzGit** [allegro/allegro-api#37]
Witam, 
Zmieniając cenę aukcji za pomocą metody doChangePriceItem, cena aukcji się nie zmienia. W odpowiedzi nie dostaje żadnego błędu. Co może być przyczyną tego problemu ?

**Request:**
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:DoChangePriceItemRequest><ns1:sessionHandle>xxxxxxxxxx</ns1:sessionHandle><ns1:itemId>6876672773</ns1:itemId><ns1:newStartingPrice>0</ns1:newStartingPrice><ns1:newBuyNowPrice>9.99</ns1:newBuyNowPrice></ns1:DoChangePriceItemRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

**Response:**
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doChangePriceItemResponse><ns1:itemInfo>-</ns1:itemInfo><ns1:itemId>6876672773</ns1:itemId></ns1:doChangePriceItemResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

**Comment by imper86** [comment]
zmiany ceny w aukcjach z ofertami kupna musisz robić przez REST Api:
https://developer.allegro.pl/documentation/#!/default/put_offers_offerId_change_price_commands_commandId

**Comment by dfranczuk** [comment]
> zmiany ceny w aukcjach z ofertami kupna musisz robić przez REST Api:
https://developer.allegro.pl/documentation/#!/default/put_offers_offerId_change_price_commands_commandId

Z tego co widzę to ta aukcja to tylko kup teraz.

**Comment by PawelTaberski** [comment]
Zgadzam się z przedmówcami i polecam tą metodę do zmiany ceny. Jednakże w tym konkretnym przypadku w podanej ofercie nie ma żadnych ofert kupna, także jest to błąd. Sprawę przekazałem do odpowiedniego zespołu. Chwilowo proszę korzystać z metody do zmiany ceny w Allegro REST API https://developer.allegro.pl/documentation/#!/default/put_offers_offerId_change_price_commands_commandId

**Comment by PawelTaberski** [comment]
Jeśli napotkałbyś taki przypadek skontaktuj się z nami, sprawdzimy w czym jest problem. Jednakże do weryfikacji niezbędny jest request i respons.

**Comment by rtnet-pl** [comment]
Faktycznie wygląda na to, że ceny nie aktualizują się.
Request
```
PUT https://allegroapi.io/offers/7133959660/change-price-commands/506fbb89-a66c-4d51-9bf5-9b4de4d1ca17 HTTP/1.1
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJh(...)GA
Api-Key: ey(...)PM=
Host: allegroapi.io
Content-Length: 108
Expect: 100-continue

{"id": "506fbb89-a66c-4d51-9bf5-9b4de4d1ca17","input": {"buyNowPrice": {"amount": "110","currency": "PLN"}}}
```
Response
```
HTTP/1.1 200 OK
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: c2f0d7e62227751f
Date: Fri, 02 Mar 2018 13:15:05 GMT
X-RateLimit-Remaining: 9000
X-Content-Type-Options: nosniff
Content-Length: 269
Content-Type: application/vnd.allegro.public.v1+json
X-RateLimit-Limit: 9000

{"id":"506fbb89-a66c-4d51-9bf5-9b4de4d1ca17","input":{"buyNowPrice":{"amount":"110","currency":"PLN"}},"output":{"status":"ERROR","errors":[{"code":"ERR_OBLIGATORY_ATTRIB_NOT_SET","message":"ERR_OBLIGATORY_ATTRIB_NOT_SET","details":null,"path":null,"userMessage":""}]}}
```

**Comment by dfranczuk** [comment]
@rtnet-pl W tym przypadku w odpowiedzi widzę error związany z brakiem wymaganych atrybutów.

**Comment by PawelTaberski** [comment]
W tym wypadku nie doszło do zmiany ceny, gdyż wszystkie parametry obowiązkowe dla tej oferty nie są uzupełnione. Po ich uzupełnieniu będzie można normalnie zmienić cenę.

**Comment by rtnet-pl** [comment]
Faktycznie, zmylił mnie nagłówek 200

**Comment by dfranczuk** [comment]
Czy można się spodziewać, że metoda doChangePriceItem z webapi zacznie działać, czy jest konieczność korzystania z REST API jeżeli chodzi o zmianę cen?

**Comment by PawelTaberski** [comment]
Pracujemy nad rozwiązaniem tego problemu, proszę o cierpliwość. I mimo wszystko bardziej polecam korzystanie ze zmiany ceny w REST API.

**Comment by dfranczuk** [comment]
Z tego co rozumiem metoda w REST API działa tylko na ofertach KUP TERAZ. Co z ofertami Licytacja + kup teraz dla których chcę zmienić cenę?

**Comment by PawelTaberski** [comment]
W przypadku licytacji do momentu zalicytowania możesz zmienić cenę kup teraz przez REST. Później nie ma już możliwości edycji ceny Kup Teraz.
