### ISSUE TITLE
ERR without any description

### ISSUE THREAD

**Issue by ventoh** [allegro/allegro-api#370]
Hello, i'm trying to send an offer via REST API calling a POST to /sale/offers
I have solved several validation errors until i'm stucked on this error:

```
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/offers
                    [userMessage] => 
                )

        )

```

Please, can you help me?

**Comment by MarcinLuczak** [comment]
Hello @ventoh - it look like not our error message. Are you sure, that this our error, and not from your code?

Send to us your full request and response, in where problem occurs. We will verify this.

**Comment by ventoh** [comment]
Yes it is, the response was a dump of the api response.
Anyway I have figured out what was the problem :) The request I have sended was not well-formed. 
I think you should document that error in tha API. Thank you very much.

**Comment by MarcinLuczak** [comment]
@ventoh thanks for this information. Next time at first send to us request and response in cURL. And status of your api calling - maybe we can help you faster.

**Comment by ventoh** [comment]
ok, please  I'm still stucked on publish an offer. 

Until now i have validated the offer and getted the offer_id.  After that, please note the offer isn't present at all in the merchant admin panel at https://allegro.pl.allegrosandbox.pl/myaccount/sell.php.
Neither in draft status.

Anyway, i trying to publish using the api call below
https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/UUID

UUID is generate on my side like this 94825-e1ee-4df1-849a-9d8a116cbc4b

This are the headers of the request
Array
(
    [0] => Accept: application/vnd.allegro.beta.v1+json
    [1] => Content-type: application/vnd.allegro.beta.v1+json
    [2] => Authorization: Bearer eyJhbGciOiJSUzI1Ni ...CUT
)

This is the body of the request
{"offerCriteria":{"0":{"offers":{"id":"6205391890"}},"type":"CONTAINS_OFFERS"},"publication":{"action":"ACTIVATE"}}

This are the headers of the response

HTTP/1.1 404 Not Found 
Expires: 0 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate 
X-XSS-Protection: 1; mode=block 
Pragma: no-cache 
X-Frame-Options: DENY 
Trace-Id: 9e6e2ca8a2e76fdd 
Date: Thu, 05 Jul 2018 10:29:48 GMT 
X-RateLimit-Remaining: 8994 
X-Content-Type-Options: nosniff 
Transfer-Encoding: chunked 
Content-Type: application/json 
X-RateLimit-Limit: 9000 

In your documentation 404 is not found. I think offer not found. 

Please, which step do i miss?

**Comment by MarcinLuczak** [comment]
@ventoh we need full cURL of your request and response to verify your problem.

**Comment by ventoh** [comment]
ok thanks,  the problem was on incorrect values in the request.

Please, still a question: is there a way to create(simulate) orders?

**Comment by ventoh** [comment]
Please, i have the following validation error when i trying to send an offer:

"code":"VALIDATION_ERROR", "message":"No values given for attribute Stan(11323)."

This is the jSON i'm sending, the stan attribute seems enabled.
{"id":null,"name":"N5130 PLEASANT BROWN \/ MYTH YGGDRASIL","category":{"id":"121809"},"parameters":[{"id":"25929","valuesIds":["25929_51"]},{"id":"130411","valuesIds":["130411_4"]},{"id":"15468","valuesIds":["15468_10"]},{"id":"17448","values":["1.25"]},{**"id":"11323","valuesIds":["11323_246466"]**}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Descrizione breve della scarpa<\/p>"}]}]},"payments":{"invoice":"VAT"},"images":[{"url":"https:\/\/0.allegroimg.allegrosandbox.pl\/original\/11a9aa\/66e7d53b438d82b19c7690e444e0"},{"url":"https:\/\/7.allegroimg.allegrosandbox.pl\/original\/114985\/b0c0dd7148699662830b58e55827"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"99.90","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":2,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":null,"endingAt":null},"delivery":{"shippingRates":{"id":"b2740186-1dd5-4b46-8db1-6f010e540923"},"handlingTime":"P2D"},"afterSalesServices":{"impliedWarranty":{"id":"b0a061e2-541e-474c-bb6e-6d2712fc4637"},"returnPolicy":{"id":"4a5b3140-e239-4acb-8e6e-73b1f626a5f5"},"warranty":{"id":"08c85d07-a8db-4c77-8e4a-9d411a40373b"}},"additionalServices":null,"sizeTable":null,"promotion":null,"location":{"countryCode":"IT","province":"Roma","city":"Anagni","postCode":"00100"},"external":null,"contact":null,"createdAt":null,"updatedAt":null}

I'm in sandbox.
Please, can you help me?

**Comment by ventoh** [comment]
I figured out my categories list was incorrects. Thank you very much.
