### ISSUE TITLE
Wznawianie zakończonych ofert przez PUT /sale/offer-publication-commands/{commandId} - An error has occurred

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#3700]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję aktywować zakończoną ofertę za pomocą PUT /sale/offer-publication-commands/{commandId}
Wysyłam:
```
array(2) {
  ["publication"]=>
  array(1) {
    ["action"]=>
    string(8) "ACTIVATE"
  }
  ["offerCriteria"]=>
  array(1) {
    [0]=>
    array(2) {
      ["offers"]=>
      array(1) {
        [2]=>
        array(1) {
          [0]=>
          array(1) {
            ["id"]=>
            string(10) "8789314696"
          }
        }
      }
      ["type"]=>
      string(15) "CONTAINS_OFFERS"
    }
  }
}
```
commandId = 1b006d4c-3c09-4989-af0c-8dc70f3c8975

Otrzymuję błąd ```An error has occurred```
Na podstawie tego komunikatu nie jestem w stanie stwierdzić w czym leży problem.

**Comment by PrzemyslawLukanowski** [comment]
Problem powoduje błędna struktura. Po przerobieniu na json wygląda jak poniżej:

```
{
	"publication": {
		"action": "ACTIVATE"
	},
	"offerCriteria": [{
		"offers": {
			"2": [{
				"id": "***"
			}]
		},
		"type": "CONTAINS_OFFERS"
	}]
}
```

a powinna:

```
{
	"publication": {
		"action": "ACTIVATE"
	},
	"offerCriteria": [{
		"offers": 
			[
                           {
				"id": "***"
			   }
                        ],
		"type": "CONTAINS_OFFERS"
	}]
}
```

**Comment by martacronic** [comment]
Ok, nie zauważyłam tej różnicy. Szkoda, że nie zwraca, którą częścią struktury jest problem, np. An error in offerCriteria.offers. Zawsze jak trafia, na An error has occurred wpadam w konsternację, szczególnie tworząc drafty.
