### ISSUE TITLE
Z /sale/offers zniknęło pole "ean"

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#3701]
Zasób /sale/offers do wczoraj zwracał pole "ean" na podstawie którego mogliśmy zidentyfikować produkt do aktualizacji.
Bez zapowiedzi terminu pole to zostało wyłączone tym samym wywalając działające integracje.
Czy macie w zanadrzu jeszcze jakieś ciekawe pomysły aby utrudnić wszystkim życie??

**Comment by PrzemyslawLukanowski** [comment]
Czy jesteś pewny, że chodzi o ten zasób? W GET /sale/offers nie zwracaliśmy pola ean, znajdziesz je tylko w GET /sale/offers/{offerId}, tam zwracamy je cały czas.

**Comment by keczerad** [comment]
Pola EAN nigdy nie było /sale/offers, jednak z drugiej strony rtet ma racje to pole powinno tam być, brak tego pola skutkuje milionami reqestow o to pole do allegro, jeżeli alegro lubi być "stukane" requesrami to niech tak będzie, a jak chce coś zoptymalizoać to mogło by to pole dodać do endpointa /sale/offers.

**Comment by AureliuszBrussy** [comment]
@keczerad zapisałem Twoją sugestię na naszej liście sugestii.
