### ISSUE TITLE
Angielskie nazwy parametrów w komunikatach błędów POST, PUT na zasobie /sale/offers

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#3702]
Może mi ktoś wyjaśnić po jaki ch. zmieniono ostatnio  nazwy parametrów w komunikatach błędów zwracanych przez metody POST i PUT na zasobie /sale/offers  z polskich na angielskie,  skoro w pozostałych metodach używa się polskich nazw parametrów. Komu to ma pomóc lub zaszkodzić i w jaki sposób ? 

Przykłady aktualnie zwracanych komunikatów:
Missing required parameters: Air filter type.
Missing required parameters: Type of suspension.
Missing required parameters: Engine Type.

**Comment by PrzemyslawLukanowski** [comment]
Dodaj do nagłówków "Accept-Language: pl-PL" - otrzymasz wtedy zarówno userMessage, jak i nazwy parametrów, w języku polskim.

**Comment by fabianCyfran** [comment]
Dodanie do nagłówków "Accept-Language: pl-PL" dla zasobu https://api.allegro.pl/sale/offer-price-change-commands/4895a575-f00b-416a-9ec7-9f6634f06080/tasks?limit=1000 nie spowodowało, że userMessage oraz nazwy brakujących parametrów są w języku polskim. W czym jest problem? Poniżej załączam request i response.

```
GET https://api.allegro.pl/sale/offer-price-change-commands/4895a575-f00b-416a-9ec7-9f6634f06080/tasks?limit=1000 HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer 
Accept-Language: pl-PL
Connection: Keep-Alive
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 0
```


```
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 66dec5339f75aaee
date: Tue, 11 May 2021 08:22:17 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 456

{"tasks":[{"offer":{"id":"10493355373"},"message":"OPERATION_FAILED","status":"FAIL","scheduledAt":"2021-05-10T12:47:46.235Z","finishedAt":"2021-05-10T12:47:46.234Z","field":"price","errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: Number of Colors, Manufacturer Code.","details":null,"path":"parameters","userMessage":"Missing required parameters: Number of Colors, Manufacturer Code."}]}]}
```

**Comment by PrzemyslawLukanowski** [comment]
@fabianCyfran Weryfkuję ten problem z odpowiednim zespołem. Wrócę z odpowiedzią, gdy uda mi się coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
@fabianCyfran W tym przypadku zwróciliśmy odpowiedź w języku angielskim, ponieważ draft oferty także utworzyłeś w tym języku. Draft przeszedł walidację a błędy zapisaliśmy w naszej bazie. Po pewnym czasie wysłałeś żądanie zmiany oferty z ustawionym Accept-Language: pl-PL, jednak request miał identyczną strukturę jak ta istniejąca w naszej bazie. W takiej sytuacji zwróciliśmy wynik poprzedniej walidacji - w języku angielskim. Jest to celowe zachowanie.
