### ISSUE TITLE
czy aplikacja readonly czytająca publicznie dostępne dane aukcji też wymaga autoryzacji użytkownika?

### ISSUE THREAD

**Issue by kompazz** [allegro/allegro-api#3703]

**Comment by PrzemyslawLukanowski** [comment]
Zasoby, które nie wymagają zgody użytkownika na autoryzację aplikacji oznaczyliśmy w naszej [dokumentacji](https://developer.allegro.pl/documentation/#) jako bearer-token-for-application (autoryzacja [client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)). Za pomocą tokena wygenerowanego w ten sposób m.in.  możesz odczytać dane ofert za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).

**Comment by kompazz** [comment]
dzieki. ponizszy kod pythona daje wynik 401 - Unauthorized. Czemu? xxx/yyy zastępują tu rzeczywiste wartości uzyskane dzisiaj.

`clientID = 'xxx'
clientSecret = 'yyy'
clientSet = clientID+':'+clientSecret
coded_data = base64.b64encode(clientSet.encode('utf-8'))
form_data = coded_data.decode('utf-8')
autoryzacja = requests.post('https://allegro.pl/auth/oauth/token?grant_type=client_credentials', data={'Authorization': f'Basic {form_data}'})`

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich, wygląda to jednak na problem z zakodowaniem clientId i clientSecret. Prześlij proszę przykładowy request w formacie cURL przez nasz [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), zweryfikuję to. W zgłoszeniu dopisz, że dane dotyczą wątku GitHub #3703.

**Comment by kompazz** [comment]
To była kwestia przesłania wartości w data zamiast w headers. Rozwiązane
