### ISSUE TITLE
Public offers data by offerID

### ISSUE THREAD

**Issue by kislukacs** [allegro/allegro-api#3704]
Hi,

if I understand correctly, in Q3 2020 there will be new methods through which we will be able to read public offers data. 
[#3353](https://github.com/allegro/allegro-api/issues/3353#issuecomment-647932337)
Am I right? How can I read public offers data through offers ID?

**Comment by PrzemyslawLukanowski** [comment]
According to [our news](https://github.com/allegro/allegro-api/issues/3377), we will not provide these methods in REST API.
