### ISSUE TITLE
Pobranie ofert z filtrem promotions

### ISSUE THREAD

**Issue by mkaluszka** [allegro/allegro-api#3705]
:bulb: **Sugestia**

Byłoby miło, gdyby zasób 
/sale/offers
otrzymał dodatkowo możliwość filtrowania po (lub po prostu zawierał tą sekcję): 
"promotion": {
"bold": true,
"departmentPage": true,
"emphasized": true,
"emphasizedHighlightBoldPackage": true,
"highlight": true
},

Obecnie pobierajac listę ofert nie wiemy, czy dana oferta korzysta z tych oznaczeń. Aby się tego dowiedzieć musimy pobrać pełną ofertę. Dla osób nie korzystających z promowania po stronie swojej aplikacji (a włączając to po stronie allegro) stanowi to duży problem. 

Chyba, że jest inna opcja pozyskania tej wiedzy bez konieczności pobierania szczegółów dla każdej wystawionej oferty.

**Comment by PrzemyslawLukanowski** [comment]
Nie ma innego sposobu niż pobranie danych o ofercie przez GET /sale/offers/{id}. Zapisałem powyższe zgłoszenie na listę naszych sugestii. Jeżeli zdecydujemy się na wdrożyć taką funkcjonalność, poinformujemy o tym w odpowiednim komunikacie.
