### ISSUE TITLE
Brak loginów sprzedawców przy pobieraniu ofert za pomocą /offers/listing

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#3706]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas pobierania ofert przez /offers/listing u części sprzedawców brakuje ich loginów. Jest tylko informacja o id, company, superSeller. Jest to losowe, czasami działa ok, a następnie przez kilka wywołań u części sprzedawców nie ma informacje o loginie.
Np traceid 692c962eca221ddc allegro nie zwróciło nicka sprzedawców z aukcji  8338843032, 8337363975, 8332906403 i wielu innych.

**Comment by PrzemyslawLukanowski** [comment]
Przeslij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą wątku GitHub #3706. Na tę chwilę nie udało mi się powtórzyć tego błędu, za każdym razem otrzymuję prawidłowo uzupełnioną informację o seller.login.

**Comment by juhacz** [comment]
Poniżej link do pliku, z którego można się pewnie czegoś dowiedzieć. Nie wiem czy dobrze go zrobiłem ,ale zrobiłem jak umiałem :)
Przeszukując ten plik można wyszukać
urlJUHA - parametry podane dla  /offers/listing
headerJUHA - nagłówki
contentJUHA - json zwrócony przez serwer

Np brak loginu dla aukcji 7229338541.
https://www58.zippyshare.com/v/yGNiwm62/file.html

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu.

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Problem nie powinien już występować.

**Comment by juhacz** [comment]
Wracam jeszcze do tematu. Czy normalne i prawidłowe jest to, że ta sama metoda nie zwraca loginów dla ofert, które wystawione są na Allegro Lokalnie?. Konkretnie, wybieram daną kategorię, sprawdzam wszystkie oferty z danej kategorii i jeśli oferta jest z Allegro jest ok, jeśli dla ofery pojawia się pole:

```
[vendor] => Array
                (
                    [id] => ALLEGRO_LOKALNIE
                    [url] => https://allegrolokalnie.pl/oferta/xxxx
                )

```
to wtedy  zamiast:
```
[seller] => Array
                (
                    [id] => 40724153
                    [login] => Mini-MaxLombard
                    [company] => 1
                    [superSeller] => 
                )

```
jest:

```
[seller] => Array
                (
                    [id] => 40724153                    
                    [company] => 1
                    [superSeller] => 
                )

```

**Comment by PrzemyslawLukanowski** [comment]
@juhacz Jest to świadome działanie. Gdy wyświetlisz podgląd takiej oferty na froncie, również nie otrzymasz informacji o loginie.
