### ISSUE TITLE
Listing a SMART

### ISSUE THREAD

**Issue by nitool** [allegro/allegro-api#3707]
Cześć,
Chciałbym dowiedzieć się w jaki sposób rozpoznać, że oferta zwrócona z endpointu /offers/listing daje możliwość skorzystania z Allegro SMART. Niestety obecnie nie widzę takiej informacji w zwrotce bezpośrednio z endpointu, a dokumentacja nie wskazuje konkretnego miejsca, które mogłoby taką informację zwrócić.

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
W tym zasobie cie nie zwracamy informacji, czy oferta jest oznaczona jako Allegro Smart, natomiast możesz skorzystać z opcji filtrowania takich ofert. Użyj parametru **option=SMART**, np. GET /offers/listing?category.id=312565&option=SMART. Zwrócimy tylko oferty Smart.

**Comment by nitool** [comment]
W takim razie czy istnieje jakikolwiek inny zasób, który na podstawie powiedzmy ID oferty (mam na myśli ofertę, która nie należy do obecnego użytkownika) będzie w stanie zwrócić mi informację o opcjach danej oferty, między innymi o opcji Allegro Smart?

**Comment by AureliuszBrussy** [comment]
@nitool nie, aktualnie nie udostępniamy zasobu, gdzie zwrócilibyśmy taką informację w ofercie, która nie należy do zautoryzowanego użytkownika. Możesz korzystać z różnych opcji filtrowania w GET /offers/listing, np. wyszukując oferty Smart u konkrentego użytkownika (filtr **seller.id** lub **seller.login**).

**Comment by nitool** [comment]
@AureliuszBrussy Niestety obawiałem się takiej odpowiedzi, ponieważ kreuje ona bardzo okrężne rozwiązanie. Niemniej jednak dzięki za odpowiedź. Zamykam.
