### ISSUE TITLE
Czy potwierdzenie "SUCCESS" podczas aktywacji/dezaktywacji jest wystarczające

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3708]
Witam.
1. Czy jak zlecę aktywację/dezaktywację i pobiorę Publish command detailed report i otrzymam status "SUCCESS" to jest wystarczające i można np. po aktywacji natychmiast dezaktywować bez błędów.
2. Na razie bazuje na zwrotce z  "/sale/offer-events" - "OFFER_ACTIVATED". Czy nie jest to zbędne/nadmiarowe?

**Comment by AureliuszBrussy** [comment]
1. Nie, response o udanej operacji na ofercie nie oznacza, że kolejna komenda na pewno zakończy się powodzeniem. Jest możliwe, że zwrócimy failed np. gdy spróbujesz aktywować ofertę która jest w trakcie kończenia, nawet jeśli komenda zakończenia oferty zakończyła się już powodzeniem.

2. Nie, nie jest to nadmiarowe - event OFFER_ACTIVATED zwraca informację o tym, że oferta jest już aktywna w serwisie, natomiast w przypadku [GET sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET) uzyskujesz informację, czy komenda publikacji została pomyślnie przetworzona, co nie oznacza, że oferta jest już aktywna (może to potrwać do godziny).

**Comment by AnimalDEV** [comment]
A czy zwrócony już event OFFER_ACTIVATED oznacza, że nie powinno być problemu z zakończeniem jak w przypadku pytania nr 1?

**Comment by AureliuszBrussy** [comment]
Dokładnie tak, zgadza się.

**Comment by AnimalDEV** [comment]
Ok dziękuję za pomoc
