### ISSUE TITLE
Zamawianie kuriera

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3709]
Zasób [getParcelPickupStatus](https://developer.allegro.pl/documentation/#operation/getParcelPickupStatus) zwraca status powodzenia zamówienia odbioru przesyłek. Możliwy jest Status PARTIAL_SUCCESS który wskazuje że wystąpiły błędy przy niektórych przesyłkach. Jak dowiedzieć się które przesyłki zostały poprawnie przeprocesowane? Czy nie możecie w takim wypadku podawać ID błędnych przesyłek?

**Comment by AureliuszBrussy** [comment]
W przypadku PARTIAL_SUCCESS w strukturze errors zwracamy id przesyłek (**path**) oraz wiadomość, dlaczego w przypadku danej przesyłki zlecenie się nie powiodło (**message**).
