### ISSUE TITLE
Pytanie o dzienniki i REST'a

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#371]
Czy planujecie udostępnienie usług REST analogicznych do doGetSiteJournal ?

**Comment by MarcinLuczak** [comment]
@kfijalko - tak, zgodnie z naszym [niedawnym komunikatem](https://github.com/allegro/allegro-api/issues/277), już wkrótce udostępnimy zasoby do obsługi zamówień.

**Comment by kfijalko** [comment]
@MarcinLuczak ok w kwestii własnych zamówień, czy będzie dziennnik zawierający wszystkie zdarzenia w allegro?

**Comment by MarcinLuczak** [comment]
@kfijalko szczegóły podamy w komunikacie, który opublikujemy wraz z nowymi zasobami.
