### ISSUE TITLE
X osoby kupiły Y sztuk. Gdzie znajdę wartość Y? 

### ISSUE THREAD

**Issue by kompazz** [allegro/allegro-api#3710]
Dla aukcji 9263937304 w odpowiedzi na 
`r = requests.get('https://api.allegro.pl/offers/listing', headers={'Authorization': f'Bearer {token}', 'Accept': 'application/vnd.allegro.public.v1+json'}, params = {'phrase':"Czarny Smartfon SAMSUNG Galaxy M21 4/64GB", 'parameter.11323':'11323_1'})`
dostaję tylko element popularity=24 a więc ilości osób, które kupiły. Nie widzę zaś nigdzie wartości 30, czyli liczby kupionych sztuk.

**Comment by AureliuszBrussy** [comment]
Nie ma tutaj nieprawidłowości - zasób ten zwraca tylko informację o popularności, czyli liczbie kupujących w ofercie. Tak samo jest na stronie - podczas wyszukiwania na liście ofert zwracamy informację o popularności.

**Comment by kompazz** [comment]
@AureliuszBrussy właśnie na www jest też informacja o liczbie kupionych sztuk i właśnie ją chciałbym uzyskać. W tym przypadku wartość 30 zamiast 24.
![FireShot Capture 031 - Czarny Smartfon SAMSUNG Galaxy M21 4_64GB 9263937304 - Sklep internet_ - allegro pl](https://user-images.githubusercontent.com/63023990/94536580-03845280-0243-11eb-9ad3-1b9f81a475f4.png)

**Comment by AureliuszBrussy** [comment]
Liczba kupionych sztuk widoczna po przejściu do konkretnej oferty - na samej liście ofert zwracamy tylko informację o liczbie osób, które zakupiły przedmiot. Tak jak wspomniałem - korzystając z GET /offers/listing nie uzyskasz takiej informacji. 

Liczbę sprzedanych sztuk uzyskasz jako zautoryzowany użytkownik, który wystawił daną ofertę, korzystając z [GET /sale/offers](https://developer.allegro.pl/documentation/#tag/User's-offer-information).

**Comment by kompazz** [comment]
Dzięki za wyjaśnienie. 
Szkoda że ta informacja nie jest w api dostępna bez autoryzacji użytkownika, skoro jest tak dostępna na www
