### ISSUE TITLE
Pobranie dat odebrania przesyłki / pobranie realnego payment przesyłki pobraniowej

### ISSUE THREAD

**Issue by rafor4** [allegro/allegro-api#3711]
Czy jest możliwość pobrania daty odebrania przez klienta przesyłki za pomocą jakiegoś zasobu? Potrzebuję do fakturowania pobrać realną datę opłacenia przesyłki pobraniowej przez odbierającego. "Payment" w checkout-forms zwraca jedynie datę wybrania opcji dostawy, nigdy nie zwraca więcej danych takich jak np. kwota zapłacona w przypadku przesyłek za pobraniem. Jedyną opcją jaką znalazłem jest pobranie numeru przesyłki dla danej transakcji, a następnie własne szukanie statusów przesyłki po przewoźnikach.

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy zasobu, który umożliwiałby sprawdzenie statusu przesyłki. Możesz natomiast pobrać dodany do zamówienia numer przesyłki korzystając z zasobu [GET /order/checkout-forms/{checkoutForm.id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingGET) i sprawdzić status po stronie przewoźnika.
