### ISSUE TITLE
POST /sale/images => HTTP: 500 INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3712]
Podczas próby wysłania zdjęcia dostaje błąd 500. Url do zdjęcia jest ok. Trace id to np.  **d2255f8663b8a8dc**

**Comment by Teestus** [comment]
Witam, 
Również doskwierają nam problemy związane z tym zasobem Przykład Trace id z mojej strony to : **caaba3229e411fe1**

**Comment by AureliuszBrussy** [comment]
Przekazałem informację do odpowiedniego zespołu - anliazujemy problem.

**Comment by hahyes** [comment]
> Przekazałem informację do odpowiedniego zespołu - anliazujemy problem.

Możliwe, że ma powiązany problem. Przy podaniu poprawnego linku do zasobu `sale/images` serwer zwraca błąd 422 Unprocessable Entity i twierdzi, że podałem nieprawidłowy url. Trace-Id: **a452d52b875b5eb**

**Comment by Troom** [comment]
Potwierdzam błąd, u mnie też występuje.
message=Downloading image from URL 'https://static.cardmarket.com/img/items/1/C15/285979.jpg' failed. Server returned the following HTTP status code: 400 BAD_REQUEST and response body: 'Invalid url'.

**Comment by szymon-convertis** [comment]
Także potwierdzam. Jeszcze wczoraj było wszystko poprawnie a dzisiaj 
 Downloading image from URL 'http://***********allegro_W18SZ368T-3.jpg?lm=1601383928' failed. Server returned the following HTTP status code: 400 BAD_REQUEST and response body: 'Invalid url'.

**Comment by AureliuszBrussy** [comment]
Przepraszam za niedogodności. Pracujemy nad rozwiązaniem tego problemu.

**Comment by Troom** [comment]
No mi już zadziałało, także jest nadzieja na lepszą przyszłość :)

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by TimothyKoval** [comment]
Naprawcie sobie jeszcze user agent
