### ISSUE TITLE
Błędna ilość przesyłek

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#3713]
Występuje problem: 
 - [X] z zasobem REST API
 - [?] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym

:beetle: **Opis**
złożyłem zamówienie na testowym allegro(event id: 1601370201290257; checkout id: e5ea9061-0231-11eb-86f9-a7ffdff8b330)

Kupiłem 
2x https://allegro.pl.allegrosandbox.pl/oferta/pufa-dziergana-pleciona-dmuchana-morski-blekit-7678596773
2x https://allegro.pl.allegrosandbox.pl/oferta/pufa-dziergana-pleciona-dmuchana-kremowy-bezowy-7678596816

obie mają max w paczce 2 szt obie są wysyłane pocztexem 
koszt wysyłki pierwszego produktu to 12zł, drugiego to 10zł.

Koszt wysyłki  dla zamówienia to 24zł, czyli policzyło koszt droższego razy 2. Ok to jestem w stanie zaakceptować. 
ALE  public 'calculatedNumberOfPackages' => int 1 
jak ? 
Mam 4 produkty, każdy max 2 produkty na paczki. Jak mam to upchnąć w jedną paczkę ?

**Comment by AureliuszBrussy** [comment]
W przypadku różnic w cennikach dostawy w różnych ofertach - koszty dostawy obliczamy na podstawie wybranego w zakładce [Ustawienia dostawy](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy) algorytmu. W tym przypadku jest to “Klient zapłaci kwotę najdroższej dostawy”, czyli na podstawie cennika z oferty 7678596773 wyliczyło właśnie jedną przesyłkę, w kwocie 24 zł (pierwszy przedmiot w paczce 12 zł + 12 zł za kolejny przedmiot w paczce). 

Możesz wybrać inny sposób obliczania dostawy lub skorzystać z tego samego cennika dostawy w różnych ofertach. W tym drugim przypadku, liczba paczek będzie obliczana tylko na podstawie ilości sztuk w paczce.

**Comment by mzawodzinski** [comment]
Ok, faktycznie jest taka opcja, nie wiedziałem mea culpa.
Ale w takim razie to ustawienie przynajmniej nie powinno być domyślne lub wyraźniej wskazane że coś takiego istnieje.
Jak ktoś zamówi mi 50 rzeczy które będę musiał wysłać 10 paczkami "Allegro Pocztex Kurier 48" to nie dość że będę musiał do tego dopłacić  to pewnie jeszcze dostanę ostrzeżenie że wysyłam ilości paczek niezgodną z tą wyznaczoną przez allegro.
