### ISSUE TITLE
Nie można zaktualizować ceny

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3714]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas wysyłania requesta z aktualizacją ceny i stanu magazynowego `/sale/offers/8900552986` dla oferty `8900552986` dostaję błąd:
```json
{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/8900552986","userMessage":null}
```
System próbował już 25 razy w ciągu 4 dni i ciągle ta sama zwrotka.
Ciężko wyciągnąć mi trace-id, więc jak można bez to byłbym wdzięczny.
Jaka może być przyczyna tego błędu?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę przykładowy request i response w formacie curl poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), abym mógł to przeanalizować. W treści podaj numer zgłoszenia na GitHubie - #3714.

**Comment by AnimalDEV** [comment]
Doszedłem do tego, że te oferty nie mają po stronie allegro wymaganych parametrów "Marka" i "Kod produktu". Nasz system stara się je uzupełnić i możliwe, że coś źle wstawia. Również ciężko mi stworzyć curl-a. Nie dałoby się sprawdzić bez tego?

**Comment by AureliuszBrussy** [comment]
@AnimalDEV niestety, jednak bez konkretnego przykładu wywołania nie uda mi się ustalić jaki problem wystąpił.
