### ISSUE TITLE
Dowanie zjęć a błąd 422 Unprocessable EntityError

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#3716]
Witam,
dzisiaj od kilku godzin, przy próbie dodania zdjęć dostaję komunikat "422 Unprocessable EntityError".

przykład poniżej:
{
       "url":"https://muzyczny.pl/towary1/113701.jpg"
}

Czy coś się zmieniło w sposobie dodawania zdjęć ?

**Comment by AureliuszBrussy** [comment]
Otrzymaliśmy już informacje o podobnych błędach (zgłoszenie #3712) - pracujemy już nad rozwiązaniem problemu. Przepraszam za niedogodność.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
