### ISSUE TITLE
Allegro nie może pobrać zdjęcia

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3717]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas uploadu zdjęcia do allegro dostaje błąd w odpowiedzi: `Downloading image from URL 'https://static2.redcart.pl/templates/images/integrations/324/51612_0.jpg' failed. Server returned the following HTTP status code: 400 BAD_REQUEST and response body: 'Invalid url'.`. Na zdjęcie normalnie da się dostać z linku. W czym może być problem?

**Comment by imper86** [comment]
U mnie to samo, przykładowy URL - https://ks2.imper.info/jedi-img/public/adidas/skarpety/ge6133/2560x2560/adidas-skarpety-low-cut-3pp-ge6133-2342f3df.jpg

**Comment by AureliuszBrussy** [comment]
Otrzymaliśmy już informacje o podobnych błędach - pracujemy już nad rozwiązaniem problemu. Przepraszam za niedogodność.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
