### ISSUE TITLE
Brak możliwości zalogowania przez stronę do sandbox -a

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#3719]
Przy każdej próbie logowania przez stronę https://allegro.pl.allegrosandbox.pl/login/form pojawia się komunikat "Login, e-mail lub hasło są nieprawidłowe" wygląda to tak jakby konta zostały usunięte lub wyłączone. Próbowałem logować się z 3 różnych kont które wczoraj działały poprawnie.

**Comment by Onixarts** [comment]
Potwierdzamy.

**Comment by Onixarts** [comment]
Już działa.

**Comment by AureliuszBrussy** [comment]
Wystąpił chwilowy problem z logowanie na Sandboxie. Nie powinien już występować. Przepraszam za niedogodności.
