### ISSUE TITLE
Pobieranie zdjęcia 

### ISSUE THREAD

**Issue by jakubowski421** [allegro/allegro-api#372]
Witam czy jest możliwość pobrania zdjęcia oferty poprzez API, wykorzystałem metodę doShowItemInfoExt ale za każdym razem array item-img-list jes pusta. Czy tak jak w przypadku productImageList ta funkcja jest zdezaktywowana, jeżeli tak to czy da się to zrobić w inny sposób ?

**Comment by AniaMalinowska** [comment]
Sprawdziłam i funkcja działa poprawnie - zwraca zdjęcia. Czy próbujesz pobrać zdjęcia na produkcji, czy na sandbox? Upewnij się też, czy w ofertach, które pobierasz są zdjęcia.

**Comment by jakubowski421** [comment]
Pobieram na produkcji, sprawdzałem kilka różnych ofert wszystkie miały
zdjęcia, dostawałem pustą arrayke, co dziwne inne wartości takie jak
item-id, it-name były tak jak być powinny. Jutro zrobię więcej testów, bo
nie ma mnie już w pracy. Dziękuję za odpowiedź, miłego popołudnia.

Pozdrawiam,
Maciej.

Śr., 4.07.2018, 16:31 użytkownik AniaMalinowska <notifications@github.com>
napisał:

**Comment by rtnet-pl** [comment]
Nie widzę, abyś ustawiał getImageUrl =1

> getImageUrl | int | niewymagany
> Parametr wskazujący na to, czy mają zostać pobrane odnośniki do zdjęć (1 - tak, 0 - nie; domyślna wartość: 0).

**Comment by jakubowski421** [comment]
Zgadza się teraz działa, dziękuję za pomoc.
