### ISSUE TITLE
Brak możliwości wystawienia oferty powiązanej z produktem

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#3720]
https://developer.allegro.pl/productization/#sandbox niestety żaden z podanych tutaj kodów EAN nie działa. Próbuję wystawić lub edytować ofertę w taki sposób żeby była powiązana z produktem ale jest to niemożliwe.

**Comment by AureliuszBrussy** [comment]
Nie potwierdzam problemu - udało mi się wystawić ofertę powiązaną z jednym z produktów dostępnych na Sandboxie. Pamiętaj, że podczas wystawiania oferty ważne jest przekazanie prawidłowego identyfikatora produktu w polu **product.id** - kod EAN nie jest identyfikatorem produktu. Abym mógł to dokładniej zweryfikować - prześlij proszę przykładowy request i response w formacie curl poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W treści podaj numer zgłoszenia na GitHubie - #3720.

**Comment by michalpokora** [comment]
Problem występuję na froncie przy wystawianiu oferty przez stronę https://allegro.pl.allegrosandbox.pl/offer/?lokalnie lub przy edycji oferty również z poziomu panelu użytkownika na froncie.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - produkty z listy nie są wyszukiwane po EAN. Wyjaśniam to z odpowiednim zespołem.
