### ISSUE TITLE
Zmiany API

### ISSUE THREAD

**Issue by Miradon-HAP** [allegro/allegro-api#3721]
czy API zmieniłoby się na allegro za przez ostatnie dwa dni?  strona przestała działać, nie mogę otworzyć opisu produktu

[Allegro API](https://youtu.be/qskHZmfaCWQ)

**Comment by AureliuszBrussy** [comment]
Zgodnie z [zapowiedzią](https://github.com/allegro/allegro-api/issues/3377) - [wyłączyliśmy dzisiaj](https://github.com/allegro/allegro-api/issues/3718) metody WebAPI pozwalające na uzyskanie szczegółowych danych o sprzedaży innych sprzedających, dlatego też nie możesz ich pobrać.

**Comment by AureliuszBrussy** [comment]
Chcemy ograniczyć sytuacje, w których strony trzecie kopiują wprost oferty z Allegro i umieszczają je na własnej stronie jako własną ofertę - sporo grupa Sprzedających zgłaszała nam, że nie wyrażała zgody na prezentację swoich ofert na stronach, których de facto nawet nie znają. Ponadto działania, które polegają stricte na pobieraniu naszej bazy produktowej są również sprzeczne z właściwym wykorzystaniem API Allegro.  Jeżeli otrzymasz zgodę od sprzedawcy na pobieranie danych jego oferty (uwierzytelnienie przez aplikację), to za pomocą GET /sale/offers i GET /sale/offers/{id} możesz pobierać te informacje.

**Comment by ziemekpr0** [comment]
To, że zablokowaliście pobieranie opisu przez API nie oznacza, że problem został rozwiązany. Większe strony bazujące wcześniej na tym rozwiązaniu dalej działają i mają się dobrze. Płynnie przeszły na "ręczne" pobieranie opisu.

"umieszczają je na własnej stronie jako własną ofertę" 

A co zrobicie ze sprzedawcami, którzy nie mają towarów w magazynie, tylko po sprzedaży sprowadzają je z hurtowni albo z innych stron? W końcu udostępniają nieswoją ofertę tylko hurtowni. Albo jeszcze lepiej, co ze sprzedawcami, którzy udostępniają ofertę z aliexpress na allegro i wysyłają towary z Chin? To już allegro nie przeszkadza, prawda? Kupujący pewnie za mało Wam zgłaszali problem, że czekają miesiącami na paczkę. Jeszcze inny przykład: czy Wy, jako allegro uzyskaliście zgody od waszych sprzedających na promowanie i wyświetlanie ich ofert poza portalem allegro w tym np. poprzez Google AdWords? Tym medium ich oferty pojawiają się w dość losowych miejscach w internecie. 

Ciężko wyobrazić sobie sprzedawcę allegro, który protestowałby przeciw trafianiu do szerszego grona kupujących i zwiększeniu swojej szansy na sprzedaż.

**Comment by ziemekpr0** [comment]
Z punktu widzenia sprzedającego allegro, proszę mi powiedzieć jaki jest sens promowania własnych ofert z allegro na swojej stronie, wydawania przy tym na kampanie promujące tą stronę i jeszcze oddawania Wam prowizji? To chyba tak nie zadziała. xD

**Comment by Miradon-HAP** [comment]
Za pośrednictwem naszych stron pomagamy sprzedawcom Allegro w sprzedaży ich towarów. Trudno uwierzyć, że sprzedawcy są przeciwni bezpłatnej reklamie swoich produktów. Mamy nadzieję, że podejmiesz właściwą decyzję i odwrotnie, rozszerzysz możliwości API i nie wyłączysz
