### ISSUE TITLE
Przekreślona cena

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3722]
Cześć
Przeszukałem materiały o API ale nie znalazłem. Jak uzyskać "przekreśloną cenę" na ofercie?
Przykład tutaj: https://allegro.pl/oferta/komputer-przenosny-4-rdzeniowy-amd-8gb-ssd256-w10-9732829272

Cena jest 2549 przekreślona, chciałbym móc tak przesłać ofertę z cenę aktualną i ceną poprzednią
Dziękuję

**Comment by AureliuszBrussy** [comment]
W API Allegro udostępniamy zasób pozwalający na zgłoszenie ofert do kampanii, programów specjalnych i oznaczeń Allegro - jest to [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/postBadges). Możesz także zapoznać się z [poradnikiem](https://developer.allegro.pl/badge/), w którym opisaliśmy dostępne zasoby.

**Comment by SebastianOzdoba** [comment]
Dziękuję, zamykam
