### ISSUE TITLE
503 SERVICE_UNAVAILABLE - Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.

### ISSUE THREAD

**Issue by Bienqq** [allegro/allegro-api#3723]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Podczas wysyłania requestów na endpoint GET https://api.allegro.pl/offers/listing 
regularnie otrzymuje Http Status 503 - Service unavailable. Wysyłam dosyć sporo zapytań nie przekraczając w żadnym razie limitu 9000 req/s, znaczna część z nich kończy się ze statusem 503.

```json
{
    "code":"SERVICE_UNAVAILABLE",
    "message":"Service unavailable.",
    "details":null,
    "path":null,
    "userMessage":"Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut."
}
```
Trace-id : d451226cbe5af022

**Comment by AureliuszBrussy** [comment]
Dziękuję za zgłoszenie, zdajemy sobie sprawę ze zwiększonej liczby błędów 503 na tym zasobie, pracujemy nad rozwiązaniem problemu.
