### ISSUE TITLE
Offers - 500 - Internal Server Error

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3724]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o weryfikację dostajemy błąd 500

REQUEST 2020-09-30 13:02:35.8655972 
curl -X PUT \
  'https://api.allegro.pl/sale/offers/9756625020' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"cba2d16c-cb5d-4bc7-87a3-f23baa76f872"},"returnPolicy":{"id":"f2356061-6e74-4398-a189-5d9e2a867927"},"warranty":{"id":"be1cfb05-b196-451b-9619-87d21cb05662"}},"attachments":null,"category":{"id":"269"},"compatibilityList":null,"contact":null,"createdAt":null,"customParameters":null,"delivery":{"additionalInfo":"","handlingTime":"PT24H","shipmentDate":null,"shippingRates":{"id":"23ef20fd-e70b-4656-ba60-5fa57c12a6a3"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11dab9/8a57d3fb47ea881dc70bbfc85947"},{"type":"TEXT","content":"<p>Funkcjonalny nożyk uniwersalny z ostrzem łamanym szerokości 18 mm firmy Richmann-Corona. Prowadnica wykonana ze stali chromowanej zapewnia dłuższą żywotność nożyka oraz odporność na korozję Obudowa o ergonomicznym kształcie odlewana z aluminium pokryta antypoślizgową gumą Regulacja długości ostrza Zapadkowy mechanizm wysuwania ostrza Sprawdza się przy pracach ogólnobudowlanych, ogrodowych, w warsztatach mechanicznych, magazynach, jak również zwykłych przydomowych czynnościach Jakość premium</p>\r\n"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11bca3/864ecd6c4ba0937536006b1926e9"}]}]},"ean":null,"external":{"id":"C9108"},"fundraisingCampaign":null,"id":"9756625020","images":[{"url":"https://a.allegroimg.com/original/11dab9/8a57d3fb47ea881dc70bbfc85947"},{"url":"https://a.allegroimg.com/original/11bca3/864ecd6c4ba0937536006b1926e9"}],"location":{"city":"Rzeszotary","countryCode":"PL","postCode":"32-040","province":"MALOPOLSKIE"},"name":"NÓŻ DO TAPET METALOWY NOŻYK 18mm ŁAMANE OSTRZA","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]},{"id":"237190","rangeValue":null,"values":["Corona"],"valuesIds":[]},{"id":"17448","rangeValue":null,"values":["0.3"],"valuesIds":[]},{"id":"219809","rangeValue":null,"values":["C9108"],"valuesIds":[]},{"id":"225693","rangeValue":null,"values":["5906741691086"],"valuesIds":[]}],"payments":{"invoice":"VAT"},"product":{"id":""},"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"8.59","currency":"PLN"},"minimalPrice":null,"startingPrice":null,"netPrice":null},"tax":{"percentage":"23.00"},"sizeTable":null,"stock":{"available":144,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-09-30 13:02:37.4124643 
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "Warnings": null,
    "ValidatedAt": null
  },
  "Exception": {
  
  },
  "TraceId": "688c5b9646671e46",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**i jeszcze jeden**
REQUEST 2020-09-30 11:37:39.1712790
curl -X PUT \
  'https://api.allegro.pl/sale/offers/9756431333' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"additionalServices":null,"afterSalesServices":{"impliedWarranty":{"id":"15b1f362-a9e2-4457-a604-16c7e4ba474a"},"returnPolicy":{"id":"f552b6bd-02a6-4955-9883-b844a94a2683"},"warranty":{"id":"211318d5-4cd9-4a7f-8e88-5ba7accef653"}},"attachments":null,"category":{"id":"74172"},"compatibilityList":null,"contact":null,"createdAt":null,"customParameters":null,"delivery":{"additionalInfo":"","handlingTime":"PT48H","shipmentDate":null,"shippingRates":{"id":"b2d5d4a3-f23c-4bf0-835c-d80121b63b9b"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11e93b/1c1f8dab494194ef2f4966fa637f"},{"type":"TEXT","content":"<p></p>\r\n"}]}]},"ean":null,"external":{"id":"72194"},"fundraisingCampaign":null,"id":"9756431333","images":[{"url":"https://a.allegroimg.com/original/11e93b/1c1f8dab494194ef2f4966fa637f"},{"url":"https://a.allegroimg.com/original/1183b8/89d31a844e53a5c11b0f2fa09666"}],"location":{"city":"Ożarów Mazowiecki","countryCode":"PL","postCode":"05-850","province":"MAZOWIECKIE"},"name":"Skrzydła anioła z piórami, niebieskie","parameters":[{"id":"11323","rangeValue":null,"values":[],"valuesIds":["11323_1"]},{"id":"225693","rangeValue":null,"values":["8712026721945"],"valuesIds":[]}],"payments":{"invoice":"VAT"},"product":{"id":""},"promotion":null,"publication":{"status":null,"endedBy":null,"duration":"","endingAt":null,"startingAt":null,"republish":null},"sellingMode":{"format":"BUY_NOW","price":{"amount":"36.90","currency":"PLN"},"minimalPrice":null,"startingPrice":null,"netPrice":null},"tax":{"percentage":"23.00"},"sizeTable":null,"stock":{"available":13,"unit":"UNIT"},"tecdocSpecification":null,"updatedAt":null,"validation":null}' \

RESPONSE 2020-09-30 11:37:40.6400160 
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "INTERNAL_SERVER_ERROR",
        "Details": null,
        "Message": "Internal server error.",
        "Path": null,
        "UserMessage": "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."
      }
    ],
    "Warnings": null,
    "ValidatedAt": null
  },
  "Exception": {
    "ClassName": "System.Net.WebException",
    "Message": "The remote server returned an error: (500) Internal Server Error.",
   
  },
  "TraceId": "bd65797cbe1b40f6",
  "Error": true,
  "StatusCode": 500,
  "Message": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}"
}

**Comment by AureliuszBrussy** [comment]
Problem powoduje to, że w polu **product.id** przekazujesz pusty string. Przekaż w nim prawidłowy identyfikator produktu lub **null**.

**Comment by SebastianOzdoba** [comment]
Dziękuję, poprawiamy
