### ISSUE TITLE
Problem z integracja sklepu sote.pl z allegro

### ISSUE THREAD

**Issue by rinlook** [allegro/allegro-api#3725]
Witam,
Wszystko wypełniam jak trzeba, dodaje witrynę z https i po wpisaniu wszystkich kopiuje Client id i Client secret do modułu w sklepie i chce zapisac/polaczyc przekierowuje mnie do strony allegro gdzie pokazuje sie komunikat nie możemy wyświetlić strony błąd:3dhsk3hsh23e za każdym razem jest inny numer błędu. Jak to naprawić ?
Sklep z którym ma być połączone allegro to
Www.hurtownia.aleczyscioch.pl  na od serwisu sote.pl

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Przyczyną takiego problemu jest zwykle to, że podany w aplikacji adres przekierowań jest niezgodny z tym podanym [podczas jej rejestrowania](https://apps.developer.allegro.pl/). Aby to wyjaśnić - skontaktuj się z autorami aplikacji, z której chcesz skorzystać.

**Comment by rinlook** [comment]
Witam,

Czyli mam zgłosić się do allegro w tej sprawie?

czw., 1.10.2020, 08:38 użytkownik AureliuszBrussy <notifications@github.com>
napisał:

**Comment by AureliuszBrussy** [comment]
@rinlook chodzi o twórców oprogramowania z którego korzystasz, z Twojego zgłoszenia wynika, że jest to sote.pl.

**Comment by rinlook** [comment]
Dziękuję za pomóc w takim razie napisze do nich.
Pozdrawiam Cię

czw., 1.10.2020, 08:47 użytkownik AureliuszBrussy <notifications@github.com>
napisał:
