### ISSUE TITLE
Problem z logowaniem

### ISSUE THREAD

**Issue by trainsport** [allegro/allegro-api#3726]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam mam problem z powiązaniem aplikacji swojego sklepu internetowego z kontem allegro. Wyświetla się strona:
https://allegro.pl.allegrosandbox.pl/login/form?authorization_uri=https:%2F%2Fallegro.pl.allegrosandbox.pl%2Fauth%2Foauth%2Fauthorize%3Fresponse_type%3Dcode%26client_id%3Ddc3fb91e2dd146928db09f80dca3d19f%26redirect_uri%3Dhttps:%2F%2Ftrainsport.bestseller.sklep.pl%2Fadmin%2FallegroRest.php&oauth=true
Trzeba tam wpisać swoje dane logowania do konta allegro jednak po ich wpisaniu wyskakuje:
Login, e-mail lub hasło są nieprawidłowe
Proszę o rozwiązanie tej sytucji.
PS jeżeli wpisuje te dane normalnie przez stronę allegro.pl loguję sie bez problemu. 
Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Czy konto, którym próbujesz się zalogować, jest zarejestrowane na [Sandboxie](https://allegro.pl.allegrosandbox.pl/login/form)?

**Comment by trainsport** [comment]
Nie nie było zarejestrowane myślałem, że rejestrując się na allegro z automatu tworzone jest konto na sandboxie. Nieistotne zarejestrowałem konto i teraz wyskakuje mi taki błąd:

Nie możemy wyświetlić strony

Numer błędu: 8052defd46461f44

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Abyś mógł powiązać aplikację na Sandboxie - także ona musi być zarejestrowana w środowisku testowy. Aby ją zarejestrować, skorzystaj z [Zarządzanie aplikacjami Allegro Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/).
