### ISSUE TITLE
PUT /sale/offers/{offerId} - ERR_YOU_CANT_CHANGE_ITEM (sandbox)

### ISSUE THREAD

**Issue by Ganev78** [allegro/allegro-api#3727]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Hi,

I am experiencing a problem with the update of an offer. I am doing the following first the offer is on the listing of the sandbox environment, then I want to update the price of that product, to update it. Because the price is above the limit for updating products directly in the listing I first END my offer, to remove it from the listing. After that, I change the price in the offer and try to re-upload my new updated offer, and here is my problem. 
I'm making a curl PUT request to the following url: "https://api.allegro.pl.allegrosandbox.pl/sale/offers/['offerId']", and I send in the body of the request the offer with the updated price in it. Before I send the request I checked that the publication -> status is ENDED. And the response from the request is Status Code: 422, and Response: {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_YOU_CANT_CHANGE_ITEM","details":"","path":"","userMessage":""}]}

This problem occurs at random, sometimes 6 requests for updating the offer are successful with no VALIDATIO_ERRORs, and then this error stops my script. I try adding a 10 seconds delay before sending this request because sometimes I need to send a request before this one to END the offer, then wait the 10 seconds and do this request. I tried to increase the seconds but it does not help. 
When I searched about this issue I found an old issue with the same error, here it is https://github.com/allegro/allegro-api/issues/2101

Please help me solve this issue

Best Regards
// S. Ganev
Team Rebus Networks

**Comment by AureliuszBrussy** [comment]
Could you please send id of the example offer, in which this problem occurred?

**Comment by Ganev78** [comment]
I will send you an id tomorrow because I don't have one right now, but the problem does not occur on specific offers it's just on random, I tested it. After my script stops if I try again to upload this same offer, with the updated price the request passes with no problems. 
I think the issue could be that the offer status while successfully being changed from ACTIVE to ENDED, maybe it's still not removed from the listing on the allegro sandbox site. So when I try to update my offer the above error occurs.

I will send you an id of an example offer, first thing tomorrow :)

**Comment by Ganev78** [comment]
Sorry for the late response, but I wanted to test it more. 
So here are some ids of offers that gave the error - 7678624890, 767862868, 7678624891
I'm also sending you an attachment with three files, that show the output of the error in the terminal.
![error 1](https://user-images.githubusercontent.com/22392234/94913842-a5f63d00-04b2-11eb-8e6e-cdcbcae58e88.png)
![error 2](https://user-images.githubusercontent.com/22392234/94913872-b27a9580-04b2-11eb-8faf-02ceaf0c0b38.png)
![error 3](https://user-images.githubusercontent.com/22392234/94913884-b60e1c80-04b2-11eb-8e40-6b795c82e912.png)

After testing it again today I found out that the problem may be in the ENDING of an offer. I check that the status of the offer is ENDED before continuing to update the price, but it may be that the offer is still in the listing of the offers on the site, so that's why this error occurs. I tried with 10 seconds, after that 20 seconds delay between the two requests but it didn't help. Sometimes it would pass, other times it will give the error. 
Now I do all the ending of offers, for all products, before starting to update the price, and I add a 1-minute delay before starting the update of all prices. 

For the moment it works, but could you tell me what is the maximum estimated time for offers to be completely removed from the listing when there is some delay from the database? 
So I could set that time and be sure that the update of the prices will pass successfully. 

I would wait for your response :) 

Best Regards
// S. Ganev
Team Rebus Networks

**Comment by AureliuszBrussy** [comment]
Ending and activating of offer may take up to 1 hour (although it usually takes much less). You are trying to perform the price change too quickly.

**Comment by Ganev78** [comment]
Ok, thanks a lot :)
