### ISSUE TITLE
Opóźnienia otwierania i zamykania ofert

### ISSUE THREAD

**Issue by esprzedaz** [allegro/allegro-api#3728]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Po kilka godzin czeka się na zamknięcie i aktywację ofert. Przykładowy uuid: 351621df-6840-44d5-9fb9-ca93f0353050

**Comment by barthoos** [comment]
Potwierdzam. Uzytkownicy zglaszaja setki takich przypadkow. Sam wychwycilem tysiace ;> U mnie problem jest od 10:15 dzisiaj. Kilka najstarszych:

19c0ad22-ab73-4e0c-95ab-189e77b4e2ed
e97ffd01-823f-4bfe-b262-c2977e9c9bbc
5bcd22e0-db38-4c80-82a9-346a6c168a18
697675ff-ae75-473b-a514-dbd66ad6fe97

Problem jest powazny. Aukcje zamykam z powodu braku stocku. Bedzie to trzeba pozniej mocno odkrecac.

**Comment by barthoos** [comment]
A i w druga strone. Dziennik zdarzen dot ofert nie donosi o zakonczeniu ofert. Np. 9708432097

**Comment by AureliuszBrussy** [comment]
Występują opóźnienia związane z publikacją ofert. Pracujemy nad rozwiązaniem tego problemu.

**Comment by AnimalDEV** [comment]
Czy problem został rozwiązany?

**Comment by AureliuszBrussy** [comment]
@AnimalDEV opóźnienia wystąpiły 1 października. Nie mam aktualnie informacji o podobnych problemach.
