### ISSUE TITLE
Wysłanie zapytania do POST /sale/offers w rzadkich przypadkach powoduje wystąpienie błędu ERR_BRAND_ZONE_SERVICE_IS_UNAVAILABLE

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3729]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

losowo podczas wystawiania aukcji zdarza się problem. Otóż pojawia się znikąd błąd ERR_BRAND_ZONE_SERVICE_IS_UNAVAILABLE. Z tego, co przeczytałem, dotyczy on wystawiania aukcji w Strefie Marek, czego my nie robimy. Błąd dotyczy też losowych zapytań, stąd dziwi mnie to bardzo. Ponadto zrobiłem później drafta z tym samym JSONem przez Postmana i normalnie się dodał.

Dodam, że błąd występuje dość rzadko, maksymalnie parę razy dziennie.

Przykładowy JSON: https://pastebin.pl/view/0aacbae6

**Comment by AureliuszBrussy** [comment]
Żebym mógł to dokładniej zweryfikować - podaj proszę trace-id żądania w którym wystąpił taki błąd.

**Comment by hahyes** [comment]
> Żebym mógł to dokładniej zweryfikować - podaj proszę trace-id żądania w którym wystąpił taki błąd.

Niestety nie mam trace-id. Jednak wiem, że sytuacja wystąpiła w czasie zapisanym dokładnie pod timestampem 1601545167 (+- sekunda róznicy mogła wystąpić).

**Comment by AureliuszBrussy** [comment]
Dziękuję, wyjaśniam to z odpowiednim zespołem. Wrócę z informacją.

**Comment by dlis2010** [comment]
Witam, czy problem został wyeliminowany? Znaleźliśmy w logach też sporo "ERR_BRAND_ZONE_SERVICE_IS_UNAVAILABLE"

**Comment by AureliuszBrussy** [comment]
@dlis2010 @hahyes pracujemy jeszcze nad analizą tego problemu. Wrócę z informacją, gdy tylko uda nam się coś ustalić.

**Comment by AureliuszBrussy** [comment]
@dlis2010 @hahyes wdrożyliśmy poprawkę. Problem nie powinien już występować.

**Comment by hahyes** [comment]
> @dlis2010 @hahyes wdrożyliśmy poprawkę. Problem nie powinien już występować.

Niestety problem nadal występuje. Trace-Id: 9f91a54751ae37a3

**Comment by AureliuszBrussy** [comment]
@hahyes wyjaśniam to z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by hahyes** [comment]
> @hahyes wyjaśniam to z odpowiednim zespołem. Wrócę z odpowiedzią.

Wyskoczyły mi kolejne, więc dorzucam kilka Trace-Id:
79a5cecd84127f6e
6bf011fd50bc7eea
d43b47d8daf68fe1

**Comment by AureliuszBrussy** [comment]
@hahyes potwierdzam, że problem wciąż występuje. Ponownie to analizujemy. Wrócę z wiążącymi informacjami.
