### ISSUE TITLE
Pobieranie danych o sprzedanych produktach

### ISSUE THREAD

**Issue by piotrkomisarski** [allegro/allegro-api#373]
Witam

Czy jest taka możliwość, żeby pobrać dane o adresach na który trzeba wysłać sprzedane produkty ?

Usługa doGetMySoldItems nie zawiera takich danych.

**Comment by rtnet-pl** [comment]
Tutaj: https://allegro.pl/webapi/tutorials.php/tutorial/id,100421

**Comment by piotrkomisarski** [comment]
Dzięki. Można zamknąć.
