### ISSUE TITLE
REST API a dane udostępniane przez serwis TradeAnalytics

### ISSUE THREAD

**Issue by 4sp3ll** [allegro/allegro-api#3732]
Słowem wstępu:
 Na przestrzeni ostatnich kilku miesięcy Allegro sp. z o.o. (pomimo podania wcześniej sprzecznych z tymi informacji w planowanym harmonogramie wdrożenia) zapowiedziało, że wyłączy z WebAPI metody pozwalające na śledzenie sprzedaży wszystkich ofert w serwisie Allegro i nie przeniesie ich do nowego API, tj. REST API. Ten proces zakończył się w dniu 2020-09-30.
W konsekwencji w REST API (w przypadku ofert których się nie wystawiło) pozostała jedynie możliwość pobrania danych opisowych oferty, jego ceny, ilości transakcji (nie ilości sztuk) za ostatnie 30 dni oraz ilości aktualnie dostępnych sztuk.

Po dniu 2020-09-30, w serwisie TradeAnalytics (raporty dotyczące Allegro), stworzonym przez spółkę Trade Analytics Instytut Badań E-Commerce sp. z o.o. której wyłącznym właścicielem jest Allegro sp. z o.o. (100% udziałów), są dostępne jednak m.in. 2 funkcjonalności:
1. Możliwość sprawdzenia TOP100 najlepszych ofert, wraz z danymi o ilości sprzedanych sztuk, średnią ceną oraz wartością obrotu, dla okresu do 18 miesięcy wstecz dla wybranej kategorii.
2. Możliwość sprawdzenia liczby sprzedanych sztuk, wartości sprzedaży, kosztów wystawienia, kosztów promocji oraz prowizji od sprzedaży dowolnej oferty w serwisie Allegro z ostatnich 30 dni.
Możliwości sprawdzenia takich danych nie ma w nowym API, tj. REST API.

  Jednocześnie pragnę zaznaczyć, że Paweł Klimiuk będący dyrektorem komunikacji w Allegro sp. z o.o. w odpowiedzi na petycję sprzeciwiającą się wyłączeniu WebAPI, którą podpisało 1249 osób (https://www.petycjeonline.com/wyczenie_webapi_allegro), w dniu 12 sierpnia 2020r. napisał, cytuje: 
![image](https://user-images.githubusercontent.com/26189632/94865931-b8369380-043e-11eb-8fb6-15b3976b8401.png)

W dalszym ciągu (01-10-2020), dane te są publicznie dostępne za sprawą oprogramowania TradeAnalytics którego twórcą jest spółka córka Allegro.
Po 30-09-2020, nie same w/w dane, a dostęp do nich dla podmiotów współpracujących z serwisem Allegro został radykalnie ograniczony. Jednocześnie Allegro, za sprawą serwisu TradeAnalytics którego jest pośrednim twórcą zyskał monopol na rynku, który wcześniej zmonopolizowany nie był. Pozostawiając tym samym wszystkie współpracujące z nim podmioty ze szczątkowymi danymi i tworząc rynek niedoskonałej konkurencji, którego głównym beneficjentem będzie spółka Trade Analytics Instytut Badań E-Commerce sp. z o.o., której wyłącznym właścicielem jest Allegro sp. z o.o.

Pytanie:
 W związku z powyższym, kiedy planujecie Państwo zaprzestania upubliczniania w/w danych za pośrednictwem oprogramowania TradeAnalytics albo (jeżeli Państwa decyzja uległa zmianie) kiedy planujecie Państwo udostępnić w/w dane za pośrednictwem REST API?

**Comment by AureliuszBrussy** [comment]
Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

**Comment by artzie92** [comment]
> Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

To, że nie korzysta z WebAPI to moze i prawda, ale nie zostało dostosowane do polityki. Przykład - dostępne funkcje dla trendów:
- **Trend w liczbie sprzedanych sztuk** nie ma opcji żeby pobrać ile zostało sprzedanych sztuk dla danej oferty przez REST publicznie!
- **Trend w liczbie transakcji** również nie ma takiej opcji, jedyny parametr to popularity czyli ilosć unikalnych transakcji na przestrzeni 30 dni. Jest niemożliwe porównać to dziennie.

Więc takie rzeczy, że się dostosowaliście to można mówić konsumentom, a nie programistom, którzy tworzą te systemy. Od dłuższego czasu Allegro pokazuje gdzie nasze miejsce i to się nie zmieni. Jednak nie mówcie, że są równe szanse bo ich zupełnie nie ma. Monopolizujecie w tym momencie rynek wśród narzędzie analitycznych i tyle.

**Comment by rtnet-pl** [comment]
Rozdział 2: Zakaz nadużywania pozycji dominującej
Art. 8.
1. Zakazane jest nadużywanie pozycji dominującej na rynku właściwym przez jednego lub kilku przedsiębiorców.
2. Nadużywanie pozycji dominującej polega w szczególności na:
(...)
2) ograniczeniu produkcji, zbytu lub _postępu technicznego_ ze szkodą dla kontrahentów lub konsumentów,

**Comment by 4sp3ll** [comment]
> Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.
Proszę zatem o informację czy na potrzeby spółka Trade Analytics Instytut Badań E-Commerce sp. z o.o. zostało stworzone nowe API albo dodane nowe metody do istniejącego API, które nie są publicznie dostępne, a dostęp do nich ma TradeAnalytics?

**Comment by 4sp3ll** [comment]
> Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

Proszę zatem o informację czy na potrzeby spółka Trade Analytics Instytut Badań E-Commerce sp. z o.o. zostało stworzone nowe API albo dodane nowe metody do istniejącego API, które nie są publicznie dostępne, a dostęp do nich ma TradeAnalytics?

**Comment by 4sp3ll** [comment]
Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

Dane dotyczące ilości sprzedanych sztuk, średniej ceny oraz wartość obrotu dla TOP 100 ofert w danej kategorii oraz możliwość sprawdzenia liczby sprzedanych sztuk, wartości sprzedaży, kosztów wystawienia, kosztów promocji oraz prowizji od sprzedaży dowolnej oferty w serwisie Allegro z ostatnich 30 dni, nie są dostępne za pośrednictwem nowego REST API.
Nie istnieje żaden sposób aby pozyskać takich danych z nowego REST API, w szczególności nie istnieje sposób na pobranie danych o ilości sprzedanych sztuk oraz prowizji od sprzedaży.

Proszę zatem o informację, czy na potrzeby oprogramowania TradeAnalytics prowadzone przez spółkę Trade Analytics Instytut Badań E-Commerce sp. z o.o. zostało stworzone nowe API albo dodane nowe metody do istniejącego API, które nie są publicznie dostępne?

**Comment by 4sp3ll** [comment]
> Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

Dane dotyczące ilości sprzedanych sztuk, średniej ceny oraz wartość obrotu dla TOP 100 ofert w danej kategorii oraz możliwość sprawdzenia liczby sprzedanych sztuk, wartości sprzedaży, kosztów wystawienia, kosztów promocji oraz prowizji od sprzedaży dowolnej oferty w serwisie Allegro z ostatnich 30 dni, nie są dostępne za pośrednictwem nowego REST API.
Nie istnieje żaden sposób aby pozyskać takich danych z nowego REST API, w szczególności nie istnieje sposób na pobranie danych o ilości sprzedanych sztuk oraz prowizji od sprzedaży.

Proszę zatem o informację, czy na potrzeby oprogramowania TradeAnalytics prowadzone przez spółkę Trade Analytics Instytut Badań E-Commerce sp. z o.o. zostało stworzone nowe API albo dodane nowe metody do istniejącego API, które nie są publicznie dostępne?

**Comment by 4sp3ll** [comment]
> Trade Analytics nie korzysta z wyłączonych 30.09.2020 metod WebAPI. Narzędzie zostało dostosowane do zmian w polityce zarządzania danymi transakcyjnymi.

Dane dotyczące ilości sprzedanych sztuk, średniej ceny oraz wartość obrotu dla TOP 100 ofert w danej kategorii oraz możliwość sprawdzenia liczby sprzedanych sztuk, wartości sprzedaży, kosztów wystawienia, kosztów promocji oraz prowizji od sprzedaży dowolnej oferty w serwisie Allegro z ostatnich 30 dni, nie są dostępne za pośrednictwem nowego REST API.
Nie istnieje żaden sposób aby pozyskać takich danych z nowego REST API, w szczególności nie istnieje sposób na pobranie danych o ilości sprzedanych sztuk oraz prowizji od sprzedaży.

Proszę zatem o informację, czy na potrzeby oprogramowania TradeAnalytics prowadzone przez spółkę Trade Analytics Instytut Badań E-Commerce sp. z o.o. zostało stworzone nowe API albo dodane nowe metody do istniejącego API, które nie są publicznie dostępne, a które częściowo zastąpiły możliwości starego WebAPI, udostępniane wcześniej podmiotom współpracującym z Allegro?

**Comment by tztztztz** [comment]
No cóż, przygotujcie się w takim razie na wysyp botów które będa obserwować oferty, ruch na, i obciążenie Waszych serwerów znacznie wzrośnie, "powodzenia" z probami zabklokowania takiej działalności.

**Comment by AureliuszBrussy** [comment]
Ograniczenie publicznego dostępu przez WebAPI do danych o transakcjach dotyczy na równi wszystkich **zewnętrznych** narzędzi. Dostęp został ograniczony, żeby chronić informacje wrażliwe, zarówno naszych partnerów (sprzedających), jak i samej platformy. Dodatkowo w związku z debiutem giełdowym, Allegro nie może udostępniać publicznie w czasie rzeczywistym danych o całkowitej wartości sprzedaży na platformie, ani danych pozwalających ją wyliczyć. 
 
Jednocześnie, aby wesprzeć naszych sprzedających, oferujemy im dostęp do danych o własnej sprzedaży oraz wybrane informacje dotyczące Allegro (np. udziały i trendy kategorii, 100 najlepszych ofert i zanonimizowane informacje dot. 30 najlepszych sprzedających w danej kategorii) poprzez **własne** narzędzie Trade Analytics. Dostęp do wybranych, wymienionych wyżej informacji dot. Allegro (przedstawionych tak, aby uniemożliwić wyliczenia całkowitej wartości lub wielkości sprzedaży na platformie lub w poszczególnych kategoriach) Trade Analytics realizuje jako jedno z wielu narzędzi wewnętrznych, które w ramach Allegro oferujemy sprzedającym.
