### ISSUE TITLE
403 An error has occured when listing orders

### ISSUE THREAD

**Issue by T0iS** [allegro/allegro-api#3733]
Hello. 

I'm trying to list orders from customers but cannot get through. 
I got the Bearer token but then I get a 403 response.

`
function getNewOrders(String $token)  {

    $mainUrl = "https://api.allegro.pl/order/events";
    $call = curl_init($mainUrl);
    curl_setopt($call, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($call, CURLOPT_HTTPHEADER, [
        "authorization: Bearer $token",
        "accept: application/vnd.allegro.public.v1+json"
    ]);
    $orderList = curl_exec($call);
    $returnCode = curl_getinfo($call, CURLINFO_HTTP_CODE);
    curl_close($call);
    echo $returnCode;
    $orderList = json_decode($orderList);
    return $orderList;
}
`

Could I get an advice please? I cannot find out what I'm doing wrong. 

Thanks a lot

**Comment by AureliuszBrussy** [comment]
Due to the large number of programming languages, we do not support each one. Perhaps one of the forum users has encountered a similar problem in the past and will be able to help you.

**Comment by T0iS** [comment]
Hello. 

Thanks. 

It is just a simple PHP req, pretty much identical with the sample one on your website. 

Could you maybe explain the process of what I have to do in order to get a list of my orders? 
Maybe I missed something. 

Thanks a lot

**Comment by AureliuszBrussy** [comment]
It looks like you are using **client_credentials** flow to authorize. This is an authorization method without the user context. You should use another authorization method, for example [code flow](https://developer.allegro.pl/en/auth/#app). All authorization methods are described in our [guide](https://developer.allegro.pl/en/).

**Comment by T0iS** [comment]
Thanks for looking into it. 

Well, I went through the guide couple of times, but probably failed to understand it. 

I even attempted a different authorisation methods, but with no luck. 

Would you be so kind to provide a sample code or something? (in any language, I do not really mind) 

Thanks a ton

**Comment by AureliuszBrussy** [comment]
As I wrote earlier - we do not support programming languages. You can try using Postman and its [snippet generator](https://learning.postman.com/docs/sending-requests/generate-code-snippets/) to get some sample code.
