### ISSUE TITLE
INTERNAL_SERVER_ERROR przy próbie zwrotu środków klientowi

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#3736]
nasz obiekt
Object
(
    [payment] => Allegro\RefundPayment Object
       (
           [id] => 7ccf4d01-fb74-11ea-a5f2-2bc218a4b9b6
       )

   [reason] => REFUND
   [lineItems] => Array
       (
           [0] => Allegro\RefundLineItem Object
               (
                   [id] => 7c79b2f0-fb74-11ea-beb7-d7dd60b12405
                   [type] => QUANTITY
                   [quantity] => 1
                   [value] =>
               )

       )

   [delivery] =>
   [overpaid] =>
   [surcharges] =>
   [additionalServices] =>
)

odpowiedź
HTTP/1.1 500 Internal Server Error
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
server: envoy
pragma: no-cache
x-frame-options: DENY
trace-id: 1c7fed0fbf426438
date: Fri, 02 Oct 2020 11:01:26 GMT
x-content-type-options: nosniff
content-type: application/json; charset=utf-8
content-length: 181
x-envoy-upstream-service-time: 36

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

od wczoraj mamy taki błąd przy próbie zwrotu środków jednemu klientowi, proszę o pomoc.

**Comment by AureliuszBrussy** [comment]
W przypadku tego zamówienia Klient rozpoczął dwie płatności - pierwsza, ta do której próbują Państwo zwrócić środki, zakończyła się niepowodzeniem, stąd też zlecenie zwortu kończy się błędem.
