### ISSUE TITLE
Problem a zamykającą się aukcją

### ISSUE THREAD

**Issue by KamilCzyz** [allegro/allegro-api#3737]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [x] inny

:beetle: **Opis**

 Problem pojawia się cyklicznie

 Mam problem z ofertą 9328366316, która automatycznie zamyka się zaraz po wznowieniu. Oferta w pewnym momencie zamknęła się sama, bez powodu. Następnie wznawiałem ją kilkukrotnie i za każdym razem automatycznie się zamyka

**Comment by AureliuszBrussy** [comment]
Narzędzie z którego korzystasz wysyła żądanie zakończenia oferty. Nie jest to błąd po stronie Allegro. Aby to wyjaśnić - skontaktuj się z proszę z twórcami tego oprogramowania.
