### ISSUE TITLE
Problem z pieniędzmi 

### ISSUE THREAD

**Issue by AR3ON3R** [allegro/allegro-api#3738]
Kupujący kupił przedmiot u mnie, lecz nie dostałem pieniędzy za niego, co mogę zrobić jeżeli allegro pokazuje że go kupił a ja ich nie dostałem?

**Comment by AureliuszBrussy** [comment]
Aby wyjaśnić tą sprawę - proszę skontaktuj się z nami poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=14a4eea0-8c13-4c5f-84d2-aa1b52a06c15&subjectId=7eca6d55-c9cc-4e2a-a37f-4ad0de3c44d9). Wskaż w zgłoszeniu o jaką transakcję chodzi. Otrzymasz wyjaśnienie od odpowiedniego zespołu.
