### ISSUE TITLE
Data wysyłki w raporcie shipment_report

### ISSUE THREAD

**Issue by lukassoft** [allegro/allegro-api#3739]
Dzień dobry. 

Mam pytanie, na podstawie czego generowana jest data wysyłki i jak ewentualnie zrobić, żeby pojawiała się na zamówieniach już wysłanych, które oczywiście wcześniej miały przypisany numer listu przewozowego. 

Numer listu dodawany jest do zamówienia przez REST API, kurier GLS, sam list też dodawany jest przez zewnętrzną aplikację z wykorzystaniem API GLS.

**Comment by MaciejFrackowiak** [comment]
Raport ten nie jest generowany w ramach API Allegro, dlatego proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
