### ISSUE TITLE
Pobieranie informacji o sprzedawanych produktach

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#374]
Hej!
Czy jest możliwość pobrania informacji o wystawionych produktach przez REST API?
Jeśli nie, to kiedy planujecie to dodać?

Wiem, że można użyć nowego zasobu i podać ID sellera, ale chodzi mi o pobieranie bardziej
szczegołowych informacji, jak np. Etykieta niestandardowa (External).

**Comment by MaciejPotepa** [comment]
Cześć

W ciągu kilku tygodni udostępnimy nowe zasoby do zarządzania własnymi ofertami. Zasób będzie odpowiednikiem listy [Moje oferty](https://allegro.pl/seller-offers). Generalnie, prace są na ukończeniu. 

Nie wiemy co masz na myśli pisząc Etykieta niestandardowa (External). Wyjaśnisz?

**Comment by jakubmaguza** [comment]
"external": null,                           -- niewymagany, zewnętrzny ID,
                                                który nadaje sprzedający, np. aby powiązać ofertę 
                                                z produktem w swoim magazynie. Możesz wprowadzić 
                                                tutaj dowolny ciąg znaków - będzie on dostępny 
                                                również po wznowieniu oferty.

To z waszego tutoriala :)

**Comment by TomekKaczmarek** [comment]
@jakubmaguza Na razie jest [ogólna lista ofert](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/), wkrótce pojawi się odpowiednik zakładki [Moje oferty](https://allegro.pl/seller-offers). Na tym etapie, trudno mi jednak powiedzieć, czy będziemy zwracać wartość external.

**Comment by jakubmaguza** [comment]
To jeśli możecie, to bardzo proszę, żebyście zwracali, bo to jedyna możliwość zmapowania aukcji na własne dane

**Comment by TomekKaczmarek** [comment]
@jakubmaguza Pytanie jednak, po co taka informacja na liście ofert? Przecież i tak musisz ją najpierw nadać wystawiając albo edytując ofertę przez REST API. Pobrać możesz ją już teraz wysyłając GET o szczegóły oferty.

**Comment by jakubmaguza** [comment]
Powiedzmy, że mam w magazynie 50 000 przedmiotów. Wystawiłem już na allegro 45 000.
Żeby sprawdzić które są już wystawione, musiałbym wysłać 45 000 GETów o szczegóły oferty.
Jeśli dodacie External do listy ofert, wystarczy jedno zapytanie (bądź kilka z offsetem).

**Comment by TomekKaczmarek** [comment]
@jakubmaguza Jasne, tylko póki co nie możesz nigdzie podać wartości external, także zanim dotrzesz do pobrania listy ofert, musisz najpierw nadać im tę wartość i wtedy możesz zmapować ofertę na własne dane.

**Comment by jakubmaguza** [comment]
Czy External to jest to samo pole, które w Menadżerze Sprzedaży Allegro nazywa się "Sygnatura"?

Oczywiście, mogę mapować numery aukcji do własnych danych przy wystawianiu (tam podaję wartość External), ale jeśli już jest możliwość podawania mojego ID do allegro (co bardzo doceniam), to fajnie jakby można było też w łatwy sposób pobrać tą informację.

**Comment by TomekKaczmarek** [comment]
@jakubmaguza Nie, nie jest to to samo pole co Sygnatura w Menedżerze sprzedaży.

Dziękuję za sugestię, przekażę ją do zespołu, który zajmuje się tematem.

**Comment by jakubmaguza** [comment]
Dziękuję. Czy jest możliwość ustawienia pola Sygnatura przez API?

**Comment by TomekKaczmarek** [comment]
@jakubmaguza Nie. Odpowiednik tej opcji dla API dodaliśmy w formie pola external w modeli oferty w REST API.

**Comment by jakubmaguza** [comment]
Dziękuję za wyjaśnienie. Dobrego dnia!
