### ISSUE TITLE
get/order/checkout-forms - błędne odpowiedzi

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#3740]
Za pomocą  get/order/checkout-forms  próbuję pobrać wszystkie zamówienia z danego okresu. Filtruję za pomocą lineItems.boughtAt.lte i lineItems.boughtAt.gte.
W pierwszym requeście sprawdzam ile ich jest (totalCount), a następnie wysyłam serię tych samych zapytań zwiększając za każdym razem offset o 100.
Mimo, ze za każdym razem podaję te same filtry, przy niektórych wartościach offsetu nie są zwracane żadne dane (count=0) , a totalCount podaje całkiem inną wartość.
Szczegółowe zestawienie request/response przesyłam w formularzu.

**Comment by lukada4100** [comment]
Gdyby nie doszło, dajcie proszę znać.

**Comment by MaciejFrackowiak** [comment]
Jak tylko zgłoszenie zostanie do nas przekazane to sprawdzimy Twoje requesty - zamieszczę wówczas odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, udało mi się potwierdzić zauważone przez Ciebie rozbieżności - problem przekazałem już do właściwego działu.

**Comment by lukada4100** [comment]
Jakieś wieści czy i kiedy uda się problem rozwiązać?

**Comment by MaciejFrackowiak** [comment]
Wysłałem przypomnienie do zespołu - dam znać, gdy otrzymam odpowiedź.
