### ISSUE TITLE
/order/events filtrowanie po typach

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#3741]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym

Przy pobieraniu zdarzeń poprzez /orders/events i podaniu w parametrach typów do filtrowania zwracane są błędne dane.
Dla przykładu przy wywołaniu https://api.allegro.pl/order/events?from=1601653480353116&limit=1000
dostaję event o id 1601653480353118  który posiada "type": "BOUGHT",
przy zapytaniu 
https://api.allegro.pl/order/events?type=[BOUGHT]&from=1601653480353116&limit=1000
wynikiem jest pusta struktura events
a przy zapytaniu
https://api.allegro.pl/order/events?type=[BOUGHT,FILLED_IN,READY_FOR_PROCESSING,BUYER_CANCELLED]&from=1601653480353116&limit=1000
wynikiem jest lista evenetów ale brakuje eventu o id 1601653480353118. Zwrócona jest masa eventów ale żaden z nich nie jest typu "BOUGHT" mimo że w parametrze był podany.

**Comment by MaciejFrackowiak** [comment]
Przed momentem na testowych eventach sprawdziłem działanie kolejnych kroków opisanych przez Ciebie - nie zauważyłem problemu z filtrowaniem. Proszę podaj ID swojego konta byśmy mogli to zweryfikować lub też prześlij nam swoje wywołania poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (dodaj proszę nr postu z GitHub w opisie).

**Comment by d3stozaur** [comment]
40291280

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem - dla zapytania GET /order/events?limit=1000&from=1601653480353118 pierwszym dostępnym eventem jest 1601653529860267. Samo filtrowanie po type również zwraca właściwe wyniki.
Natomiast, gdy podasz event mniejszy o 1 tj. 1601653480353117 to pojawi się event z id 1601653480353118 w wynikach.

**Comment by d3stozaur** [comment]
W przykładach podaje id eventu z końcówka 116 a nie 118 wiec jest mniejsze niż 118 i ten event z końcówką 118 powinien się wyświetlić.
A samo filtrowanie dalej nie działa nawet jak nie podam parametru from to dostaje pusta liste eventów.
https://api.allegro.pl/order/events?type=[BOUGHT]&limit=1000  takie zapytanie zwraca
{
  "events": []
}
to samo
dla https://api.allegro.pl/order/events?type=[BOUGHT,FILLED_IN]&limit=1000
natomiast dla
https://api.allegro.pl/order/events?type=[BOUGHT,FILLED_IN,READY_FOR_PROCESSING]&limit=1000
zwracane są wyniki w tym FILLED_IN

**Comment by MaciejFrackowiak** [comment]
Aj, to widocznie z rozpędu nie dopatrzyłem - ale również dla 1601653480353116 dostaję 1601653480353118.
Zapytanie powinno przyjąć formę GET /order/events?limit=1000&type=BOUGHT&from=1601653480353116 - bez nawiasów kwadrtowych, które zamieszczasz.

**Comment by d3stozaur** [comment]
Ok przekazanie bez nawiasów, ale dlaczego przy podaniu w type BOUGHT,FILLED_IN nie dostaje nic, ale jak dodam READY_FOR_PROCESSING już dostaje odpowiedź wraz z wynikami FILLED_IN których rzekomo nie ma wg wcześniejszego wywołania?
Poniżej gif który przedstawia brak wyników dla BOUGHT,FILLED_IN oraz brak jakiekolwiek zdarzenia BOUGHT dla requestu na 
https://api.allegro.pl/order/events?type=[BOUGHT,FILLED_IN,READY_FOR_PROCESSING]&limit=1000
![screencast-nimbus-capture-2020 10 06-09_54_44](https://user-images.githubusercontent.com/32417963/95174479-6aad8400-07ba-11eb-892e-378637628de6.gif)

**Comment by MaciejFrackowiak** [comment]
W przypadku większej liczby filtrów należy je podać w postaci np. GET /order/events?limit=1000&type=BOUGHT&type=FILLED_IN&type=READY_FOR_PROCESSING&from=1601653480353116 - a nie jak podajesz je "po przecinku".

**Comment by d3stozaur** [comment]
ok to wszystko w takim razie jasne :D dzięki za pomoc
