### ISSUE TITLE
Zmiana startingPrice z oferty. 

### ISSUE THREAD

**Issue by kamiljaszczynski** [allegro/allegro-api#3742]
Witam serdecznie,
Szukam sposobu na modyfikację ceny startingPrice - która pojawia się w ofercie. 
Do tej pory w dokumentacji znaleźliśmy opcję zmiany ceny Kup Teraz. Udało się i zmiany sprawnie pojawiają się na aukcjach. Wcześniej próbowaliśmy używać updateOffer do zmian cen ale niestety bez rezultatu. 
Jest jakaś opcja podobna do sale/offer-price-change-commands, która zmieni cene startową/minimalną ? 
Z góry dziękuje za odpowiedzi.

**Comment by MaciejFrackowiak** [comment]
Cenę startową oraz minimalną dla licytacji możesz edytować tylko poprzez [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

**Comment by kamiljaszczynski** [comment]
Jeśli dodamy nową aukcję i np. do paru minut zrobimy update poparzez PUT /sale/offers/{offerId}.
to cena się zmienia.
Natomiast dla aukcji które są już parę dni a nie ma żądnych licytacji itp. Nie działa ta opcja. 
Co więcej nie dostajemy żadnego komunikatu błędu przy takim updacie. Wszystko przechodzi poprawnie mimo wysłania innej ceny. 
Wg tego: https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#licytacje

Można zmieniać ceny dopóki ktoś nie zalicytuje. Wiec już nie wiemy o co chodzi :)

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Dokładnie, dopóki nie ma złożonej pierwszej oferty kupna można zmienić ceny w licytacji - bez konkretnego przykładu niestety trudno mi się odnieść do Twoich spostrzeżeń.
Tak, musisz przesłać cały model oferty w PUT.
