### ISSUE TITLE
Token nie generuje się

### ISSUE THREAD

**Issue by krystian612** [allegro/allegro-api#3743]
Witam,

Dzisiaj postanowiłem rozpocząć przygodę z API,
Zacząłem od 1. tutoriala:
https://developer.allegro.pl/getting_started/#jak-uzyska%C4%87-token-dost%C4%99powy-do-api
Zrobiłem wszystko tak jak jest napisane, wypełniłem zmienne  $clientId i $clientSecret tymi wygenerowanymi w panelu
Odpaliłem skrypt u siebie na localhoście w xamppie, i wynik oczywiście taki:
 access_token = Something went wrong

Czy coś może należy zrobić inaczej niż w tutorialu lub może wykonuje to w zły sposób, może skrypt należy uruchomić jakoś inaczej. Mógłbym poprosić o pomoc? : )

**Comment by MaciejFrackowiak** [comment]
Trudno mi się odnieść do kodu, który przygotowałeś - dane z przykładu powinny funkcjonować. W przeszłości jednak okazywało się, że część serwerów natrafiała na problem - spójrz proszę do wątku https://github.com/allegro/allegro-api/issues/1539 - być może pomoże w rozwiązaniu Twojego problemu.
