### ISSUE TITLE
doGetSystemTime. Alternatywa w REST API?

### ISSUE THREAD

**Issue by robsonek** [allegro/allegro-api#3744]
Jak w temacie. Czy jest jakaś alternatywa metody doGetSystemTime?

**Comment by hahyes** [comment]
Możesz korzystać z serwerów NTP danego kraju do pobierania aktualnego czasu. Myślę, że nie ma lepszego rozwiązania do tego, a pewnie Allegro też synchronizuje się z NTP. ;)

**Comment by MaciejFrackowiak** [comment]
Dokładnie, nie mamy alternatywnego zasobu w REST API. Allegro korzysta z serwera czasu w Borówcu.
