### ISSUE TITLE
Aktywacja konta na Sandboxie

### ISSUE THREAD

**Issue by masztan** [allegro/allegro-api#3745]
Dziś chciałem dodać kolejne konto na sandboxie aby przetestować zakupy jako zwykły użytkownik. Na maila nie przyszły żadne informacje odnosnie weryfikacji. Czy rejestracja działa poprawnie?

**Comment by MaciejFrackowiak** [comment]
Tak, nie mam żadnych informacji, abyśmy mieli problem z rejestracją na Sandbox. Podaj proszę adres e-mail, na który rejestrowałeś konto.

**Comment by masztan** [comment]
Maile uzyte to:

m.twardowski@webreklama.net
jacykow@vp.pl

**Comment by MaciejFrackowiak** [comment]
Widzę w logach, że dostarczyliśmy maile na serwery - oto przykładowy log:

Subject:	 Message from WebAPI Sandbox environment
From:	no-reply@allegrosandbox.pl
To:	m.twardowski@webreklama.net

Start of delivery:	2020/10/06 08:35:32
Delivery status:
2020/10/06 08:35:32	m.twardowski@webreklama.net	Message queued for delivery
2020/10/06 08:36:13	m.twardowski@webreklama.net	OK id=1kPga5-0002Ja-B8
2020/10/06 08:36:13		End of message processing

**Comment by masztan** [comment]
System antywirusowy odrzucil mi:
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  m.twardowski@webreklama.net
    This message has been rejected because it has
    a potentially executable attachment "message.0b82a3069765254d8320cf047c026c29.eml"
    This form of attachment has been used by
    recent viruses or other malware.
    If you meant to send this file then please
    package it up as a zip file and resend it.

**Comment by MaciejFrackowiak** [comment]
Wiadomości z Sandbox przesyłane są wraz z załącznikiem w formacie *.eml, gdzie mieści się główna treść wiadomości. Twój serwer nie przyjmuje ich - niestety, niezbędna jest zmiana ustawień serwera bądź skorzystanie z alternatywnej skrzynki, która przyjmuje wiadomości z *.eml.

**Comment by masztan** [comment]
Okej, na to drugie doszło. Aktywowałem. Mozna zamknąć dyskusje.
