### ISSUE TITLE
Authorization Code flow dla Allegro OAuth: Unauthorized

### ISSUE THREAD

**Issue by Octanee** [allegro/allegro-api#3747]
Witam, 
w trakcie pracy nad wtyczką do Wordpress, napotkałem na problem z którym nie potrafię sobie poradzić. Podczas zgłaszania się po token wykonując żądanie HTTP metodą POST (https://developer.allegro.pl/auth/#user pkt ) otrzymuje:
```
Response status code: 401
Result: {"error":"Unauthorized","error_description":"Unauthorized"}.     
```  
Kod zapytania:

```
$base = 'https://allegro.pl.allegrosandbox.pl';
$end = '/auth/oauth/token?grant_type=authorization_code&code=' . $code . '&redirect_uri=' . get_option('wcara-redirect-uri');
$url = $base . $end;
$setopt = array(
  CURLOPT_RETURNTRANSFER    => 1,
  CURLOPT_POST              => 1,
  CURLOPT_HTTPHEADER        => [
    'Authorization: Basic ' . get_option('wcara-client-id') . ':' . get_option('wcara-client-secret'),
  ],
);
```
Aplikacja Allegro Sandbox: `Wcara Octane`
Użytkownik: `Client:44318331`

Z czego może wynikać brak autoryzacji i jak sobie z tym poradzić?

**Comment by MaciejFrackowiak** [comment]
Proszę upewnij się, że przekazujesz poprawne wartości dla Client ID oraz Client Secret. Z racji mnogości języków programowania nie prowadzimy wsparcia w zakresie wykorzystania konkretnego z nich. Być może któryś z użytkowników będzie mógł Ci pomoć. Spójrz także na podobny wcześniejszy wątek: https://github.com/allegro/allegro-api/issues/2620.

**Comment by Octanee** [comment]
W wątku #2620 znalazłem swój błąd. Wystąpił on w tej linijce:
`'Authorization: Basic ' . get_option('wcara-client-id') . ':' . get_option('wcara-client-secret'),`
Aby poprawnie działało należy encodować `client-id:client-secret`. Poprawny kod wygląda nastepująco:
`'Authorization: Basic ' . base64_encode(get_option('wcara-client-id') . ':' . get_option('wcara-client-secret')),`
Dziękuję za pomoc :)
