### ISSUE TITLE
Pobieranie danych do raportów - power bi

### ISSUE THREAD

**Issue by Pharamus** [allegro/allegro-api#3748]
Witam, chciałbym przygotować zestawienia różnych parametrów dotyczących sprzedaży i ocen mojego konta w formie graficznych aktywnych raportów.
Czy istniej możliwość podłączenia się bezpośrednio za pośrednictwem power bi i pobieranie za jego pomocą danych.

**Comment by MaciejFrackowiak** [comment]
Tu niezbędne jest, abyś sprawdził możliwości wspomnianego oprogramowania, czy pozwala na połączenie z zewnętrznym API. Jako Allegro nie prowadzimy bezpośredniego wsparcia w zakresie integracji z zewnętrznym oprogramowaniem.
