### ISSUE TITLE
Pobieranie nr przesyłki (jako kupujący) wprowadzonego do mojego zakupu.

### ISSUE THREAD

**Issue by maciej-domski** [allegro/allegro-api#3750]
Dzień dobry,

przeglądając dokumentację REST API nie widzę nigdzie metod pozwalających na pobieranie informacji o moich zakupach. Znalazłem podobne wątki, gdzie jest informacja, że nie ma takiej możliwości, gdyż API jest nakierunkowane na sprzedawcę. Potrzebuję jednak potwierdzenia, czy nie ma absolutnie możliwości, żebym jako klient mógł pobrać poprzez API nr przesyłek, jakie sprzedawca wprowadził do moich zakupów.

**Comment by MaciejFrackowiak** [comment]
Potwierdzam, nie mamy zasobów do obsługi zakupów kupującego.

**Comment by maciej-domski** [comment]
Ok, poproszę w takim razie o informacje, czy jest w ogóle coś takiego w planach, żeby dodawać metody do obsługi zakupów tj. pobierania informacji, nr przesyłek itp. oraz czy jest możliwość wykrycia zdarzenia (od strony sprzedawcy) kiedy został wprowadzony nr przesyłki? Chodzi o endpoint /order/events. Po wprowadzeniu nr przesyłki dla zamówienia, nie pojawia się nowe zdarzenie z typem FULFILLMENT_STATUS_CHANGED, czyli zakładam, że to dotyczy tylko zmiany statusu zamówienia?

**Comment by MaciejFrackowiak** [comment]
Nie, REST API rozwijamy stricte w zakresie zasobów przeznaczonych do obsługi sprzedaży. Event "FULFILLMENT_STATUS_CHANGED" pojawia się wyłącznie podczas zmiany statusu realizacji zamówienia.

**Comment by maciej-domski** [comment]
Ok, dzięki.
