### ISSUE TITLE
Problem with float parameter value for offer

### ISSUE THREAD

**Issue by scoox123** [allegro/allegro-api#3751]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
`
{
  "id": "9784169187",
  "name": "Kamień półszlachetny Plug Flesh Tunnel piercing",
  "category": {
    "id": "257527"
  },
  "product": null,
  "parameters": [
    {
      "id": "210702",
      "valuesIds": [
        "210702_244286"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "205826",
      "valuesIds": [
        "205826_382529"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "17948",
      "valuesIds": [
        "17948_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "210714",
      "valuesIds": [
        "210714_381521"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "210726",
      "valuesIds": [
        "210726_287657"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "210722",
      "valuesIds": [
        "210722_32"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "303",
      "valuesIds": [],
      "values": [
        "3"
      ],
      "rangeValue": null
    },
    **{
      "id": "303",
      "valuesIds": [],
      "values": [
        "4"
      ],
      "rangeValue": null
    },**
    {
      "id": "303",
      "valuesIds": [],
      "values": [
        "5"
      ],
      "rangeValue": null
    }
  ],
  "customParameters": null,
  "ean": null,
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/119a65/d66b8ce2467990a774711d4db52a"
          },
          {
            "type": "TEXT",
            "content": "<h1>Kamień półszlachetny Plug Flesh Tunnel piercing kolczyk do ucha</h1><ul><li><b>Średnica:</b> 5 mm</li></ul><ul><li><b>Rodzaj:</b> Plug</li><li><b>Ilość:</b> 1 Sztuka</li><li><b>Zastosowanie:</b> Ucho</li></ul>"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tecdocSpecification": null,
  "images": [
    {
      "url": "https://a.allegroimg.com/original/119a65/d66b8ce2467990a774711d4db52a"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "21.9",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "tax": null,
  "stock": {
    "available": 99,
    "unit": "UNIT"
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE",
    "startingAt": null,
    "endingAt": null,
    "endedBy": null,
    "republish": false
  },
  "delivery": {
    "shippingRates": {
      "id": "03be8c8c-bace-4646-b83d-b1155300385e"
    },
    "handlingTime": "PT168H",
    "additionalInfo": "",
    "shipmentDate": null
  },
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "a78f3c77-45ee-4e1e-bbd9-a2d538441b04"
    },
    "returnPolicy": {
      "id": "d467b04e-a504-47dd-b434-1fa937c1a483"
    },
    "warranty": null
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "LUBUSKIE",
    "city": "Sulechów",
    "postCode": "66-100"
  },
  "external": {
    "id": "HBPST09-4"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [
      {
        "code": "VALIDATION_ERROR",
        "message": "You can only enter the parameter once.",
        "details": "",
        "path": "parameters",
        "userMessage": "You can only enter the parameter once."
      }
    ],
    "warnings": [],
    "validatedAt": "2020-10-07T14:46:29.338Z"
  },
  "createdAt": "2020-10-07T14:46:29.000Z",
  "updatedAt": "2020-10-07T14:46:29.338Z"
}`

----

I have a problem with using a float parameter value. It works fine with the other values, but for the float value I get the error "You can only enter the parameter once." - the problematic parameter is:

(...)
    {
      "id": "303",
      "valuesIds": [],
      "values": [
        "4"
      ],
      "rangeValue": null
    },
(...)

The parameter is "srednica" of the allegro "piercing" category.

How can I specify a float parameter for an offer? I already tried "value":["string"] and "values":"string", but they resulted in errors within the API. I cannot find from your documentation how to set float values ...?

Kind Regards and Thank you
Stephan

**Comment by MaciejFrackowiak** [comment]
I checked your request and you sent parameter 303 three times, e.g.:

```
{
		"id": "303",
		"valuesIds": [],
		"values": ["3"],
		"rangeValue": null
	}, ** {
		"id": "303",
		"valuesIds": [],
		"values": ["4"],
		"rangeValue": null
	}, ** {
		"id": "303",
		"valuesIds": [],
		"values": ["5"],
		"rangeValue": null
	}],
```
You can add only one value of parameter 303, so you should send it in your request as:

```

            "id": "303",
            "valuesIds": [],
            "values": [
                "123.45"
            ],
            "rangeValue": null
        },
```

**Comment by scoox123** [comment]
Hello Maciej,
diekuje bardzo, that was the obvious error 👍. It worked out nicely!
