### ISSUE TITLE
Czas realizacji zamówienia

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#3752]
Cześć,
nie znalazłem w dokumentacji.
Czy jest możliwość odczytania (w API) ze złożonego zamówienia jaki czas realizacji wyliczyło Allegro a jaki zadeklarował sprzedawca?

**Comment by MaciejFrackowiak** [comment]
Nie, w szczegółach zamówienia nie zwracamy tych informacji. Wyłącznie korzystając z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) możesz sprawdzić zadeklarowany przez siebie czas wysyłki - pole "handlingTime".
