### ISSUE TITLE
Grubość as Parameter for variants in the Piercing Category

### ISSUE THREAD

**Issue by scoox123** [allegro/allegro-api#3753]
:bulb: **Sugestia**

Hello,
it would be really super if you could activate the grubość parameter for the variantization in the piercings category:

https://allegro.pl/kategoria/piercing-bizuteria-257527

or 

https://allegro.pl/kategoria/piercing-bizuteria-257527

Right now it is only possible to use colorpattern and Srednica, but many piercings vary in Srednica and Grubosc:

e.g. there is 1.2 x 8 mm and 1.6 x 8 mm and 1.2 x 10 mm and 1.6 x 10 mm

The only way to list these items now would be to split them up in many offers (for each grubosc), but that is not good for Allegro and the client looking for their piercings.

It would be super if you could activate it, diekuje bardzo in advance :)

**Comment by MaciejFrackowiak** [comment]
Multi-variant offer parameters are not dependent only on Allegro API - they are also available on WWW service. So this kind of change has to be introduced for whole Allegro - you can suggest it via [Allegro contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by scoox123** [comment]
Thank you i will do that
