### ISSUE TITLE
Grubosc in Piercing Category for Variantization

### ISSUE THREAD

**Issue by scoox123** [allegro/allegro-api#3754]
:bulb: **Sugestia**

Hello,
it would be really super if you could activate the grubość parameter for the variantization in the piercings category:

https://allegro.pl/kategoria/piercing-bizuteria-257527

or 

https://allegro.pl/kategoria/piercing-bizuteria-257527

Right now it is only possible to use colorpattern and Srednica, but many piercings vary in Srednica and Grubosc:

e.g. there is 1.2 x 8 mm and 1.6 x 8 mm and 1.2 x 10 mm and 1.6 x 10 mm

The only way to list these items now would be to split them up in many offers (for each grubosc), but that is not good for Allegro and the client looking for their piercings.

It would be super if you could activate it, diekuje bardzo in advance :)

**Comment by MaciejFrackowiak** [comment]
I replied in thread https://github.com/allegro/allegro-api/issues/3753.
