### ISSUE TITLE
Rozpoznawanie konta firmowego

### ISSUE THREAD

**Issue by Sebug-rsa** [allegro/allegro-api#3755]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Czy bazując na zasobie /me można rozpoznać rodzaj konta? Na środowisku testowym request zwraca nazwę firmy dla konta zwykłego, natomiast dla konta firmowego nie zawsze zwraca NIP. W jaki inny sposób można ustalić rodzaj konta?

**Comment by MaciejFrackowiak** [comment]
Zasób ten jednoznacznie nie zwraca typu konta - informacja o nazwie firmy czy też NIP mogą jedynie sugerować, że jest to konto firmowe (historycznie może być konto zwykłe, które ma uzupełnioną nazwę firmy oraz NIP, a co do zasady jest kontem zwykłym).
