### ISSUE TITLE
Nieprawidłowa liczba sztuk

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#3756]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry, 

Dostajemy błąd jak w temacie, poniżej R&R z wykonywanych operacji, prośba o weryfikację

REQUEST 2020-10-08 09:05:58.9334315
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/d4358921-f474-43ef-8bde-ed25f1abe513' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \
  -d '{"modification":{"changeType":"FIXED","value":1},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"8009807725"}]}]}' \

RESPONSE 2020-10-08 09:05:58.9646687 
{
  "Data": {
    "Id": "d4358921-f474-43ef-8bde-ed25f1abe513",
    "TaskCount": {
      "Failed": 0,
      "Success": 0,
      "Total": 0
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "21b712fa683cf50a",
  "Error": false,
  "StatusCode": 201,
  "Message": null
}

REQUEST 2020-10-08 09:24:05.6650861 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/d4358921-f474-43ef-8bde-ed25f1abe513/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2020-10-08 09:24:05.7111107 
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2020-10-08T07:06:00.035Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "8009807725"
        },
        "ScheduledAt": "2020-10-08T07:05:58.959Z",
        "Status": "FAIL",
        "Errors": [
          {
            "Code": "ERR_INVALID_QUANTITY",
            "Details": null,
            "Message": "ERR_INVALID_QUANTITY",
            "Path": null,
            "UserMessage": "Nieprawidłowa liczba sztuk."
          }
        ]
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "8fb0d0b4b654976c",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}

**Comment by MaciejFrackowiak** [comment]
Potwierdzam napotkany problem - zgłosiłem już to do weryfikacji.
