### ISSUE TITLE
Powiadomienie o nowych dyskusjach i wiadomościach od kupującego

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3758]
Chce skorzystać z modułu Dyskusji do zamówień.  Jak można dowiedzieć się o nowej dyskusji/nowej wiadomości w dyskusji?
Czy mamy udostępniony jest jakiś zasób z eventami tak jak jest to zrobione z ofertami zamówieniami?

Musze poinformować użytkownika o nowo wysłanych wiadomościach, a nie będę co chwila pobierał wszystkich dyskusji a potem ich wiadomości.

Czy Centrum wiadomości zostało już oprogramowane w REST API?

**Comment by MaciejFrackowiak** [comment]
Nie, w przypadku dyskusji nie emitujemy eventów. Wszelkie wiadomości w danej dyskusji pobierzesz zasobem [GET /sale/disputes/{disputeId}/messages](https://developer.allegro.pl/documentation/#operation/getMessagesFromDisputeUsingGET) -  we własnym zakresie musisz zaprogramować mechanizm, który będzie je aktualizował.
Natomiast obsługa Centrum wiadomości znajduje się na liście sugestii dot. rozwoju REST API Allegro.

**Comment by fjjjq** [comment]
Może powinniście się zastanowić nad takim podejściem? Bo rozumiem że jeżeli chce być na bieżąco i mam powiedzmy 100000 zamówień i chce powiedzieć użytkownikom czy  nie została utworzona kolejna wiadomość w jakiejś dyskusji lub czy żadna nowa dyskusja nie została utworzona to muszę:

- Odpytac się o wszystkie dyskusje
- Sprawdzić czy zasób nie zwrócił żadnej nowej dyskusji
     - Jeżeli zwrócił to zaczytać wiadomości i zapisać w systemie
- Sprawdzić liczbę wiadomości w pozostałych dyskusjach
    - Jeżeli jest inna od mojej w systemie to odpytać się o wiadomości w tej dyskusji i zapisać

Operacja musi być powtarzana cyklicznie co powiedzmy 10 minut. Co powoduje że za każdym razem muszę przebrnąć przez masę danych.

**Comment by MaciejFrackowiak** [comment]
Tak, takie rozwiązanie znajduje się na liście sugestii dot. dalszego rozwoju REST API Allegro. Twój głos dopisałem do listy.
