### ISSUE TITLE
Odświerzenie tokenów response 401 

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#3759]
Mam pytanie bo mam automat który odświeża tokeny dla sklepów z którymi współpracuje. 
Wszystko dzieje się w jednej pętli i na ok 10-sklepów dla 2-ch lub 3 sklepów zamiast nowego tokenu dostaję 401.

Tokeny odświeżam o pełnych godzinach 00, 08, 16.  O północy jest najmniej błędów, o 8-mej lub 16 tej błędów jest więcej. Jeżeli token nie odświeży się o 8-mej to o 16-tej już idzie ok. To są różne sklepy nie ma jakiejś prawidłowości.

Co może być powodem takiego zachowania lub co powinienem dostarczyć żebyście zrobili weryfikację tego problemu.

**Comment by MaciejFrackowiak** [comment]
Proszę przekaż nam id konta, na którym zaobserwowałeś opisany przez siebie problem. Podaj nam także przykładowe daty, kiedy wystąpiło 401. Postaramy się spojrzeć w logi - wstępnie trudno tu mówić o jakimś globalnym problemie, gdy część tokenów odświeża się w pełni prawidłowo. Dane prześlij nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - w treści proszę dodaj tylko id posta z GitHub'a.

**Comment by Raafal78** [comment]
Pisząc ID Konta masz na myśli moja Aplikacje która to robi czy konkretnego konta Allegro ?
Tego 2-go chyba nie mam .
Czy może chodzi o konkretną wartość tokenu ?

Pozdrawiam
Rafał Pazdej
Afida.pl

**Comment by MaciejFrackowiak** [comment]
Miałem na myśli id konkretnego użytkownika Allegro, który korzysta z Twojego rozwiązania - jeżeli korzystają z jednego ClientID to trudniej (więcej czasu potrzeba) to zweryfikować. Proszę przekaż nam dane, które posiadasz - z racji ich wrażliwości bezpieczniej będzie via formularz.

**Comment by Raafal78** [comment]
Ok szczegóły wysłane: 
Przyjęliśmy zgłoszenie numer  "11509598" ref:_00D24aE05._5003V7vwb9:ref

**Comment by AureliuszBrussy** [comment]
Dziękuję za informację. Odpowiedź udzielimy w zgłoszeniu przesyłanym przez Ciebie w formularzu.

**Comment by Raafal78** [comment]
Odświeżam problem od kilku dni średnio jeden na 50 klientów ma problem z odświeżeniem tokena dostępowego.
Szczegóły wyśle w zgłoszeniu.

**Comment by AureliuszBrussy** [comment]
@Raafal78 dziękuję za informację. Czekamy na zgłoszenie - udzielimy w nim odpowiedź.

**Comment by Raafal78** [comment]
Witam zgłoszenie zrobione wczoraj numer: 13757866

Pozdrawiam
Rafał Pazdej
Afida.pl

**Comment by AureliuszBrussy** [comment]
Otrzymałem dane, które przesłałeś w formularzu. Nie udało Ci się odświeżyć tokena w podanym przykładzie, ponieważ użytkownik wylogował się na wszystkich urządzeniach, co unieważniło ten refresh token.

**Comment by Raafal78** [comment]
Co to znaczy wylogował się z wszystkich urządzeń ?
Odebrał uprawnienia aplikacji czy jak ?

Inaczej jak ja mam swoje konto o się z niego wyloguję bo wyłączam komputer i mam taki nawyk wylogowywania tzn ze inne aplikacje nie mogą odświeżyć tokena dostępowego ?

Pozdrawiam
Rafał Pazdej
Afida.pl

**Comment by AureliuszBrussy** [comment]
@Raafal78 wylogowanie ze wszystkich urządzeń następuje, gdy użytkownik skorzysta z odpowiedniej opcji w jednej z [zakładek Moje Allegro](https://allegro.pl/moje-allegro/moje-konto/logowanie-i-haslo) lub w wyniku zmiany hasła na koncie.

**Comment by Raafal78** [comment]
Ok ale to chyba jest standardowe zachowanie że ludzie się wylogowują z urządzeń i zmieniają hasła do konta.

Czy to nie jest błąd że wtedy nie można odświeżyć tokena ? Przecież klient daje dostęp do swojego konta dla danej aplikacji na rok i niezależnie czy jest zalogowany czy nie.


Czy to nie jest jakiś bug po stronie allegro ?

**Comment by Raafal78** [comment]
Wysłałem jeszcze jedne szczegóły ( zgłoszenie 13868053 ) , jest to moje prywatne konto i też nie udało się odświeżyć tokena po jakiś 5-ciu miesiącach działania. Nie było też robione żadne wylogowanie. Proszę o inwestygację.

**Comment by AureliuszBrussy** [comment]
Utrata ważności tokena w takich przypadkach nie jest błędem. 

Klient powiązując aplikację nie daje dostępu do wykonywania operacji przez aplikacje na rok. Każdy refresh token ważny jest przez 3 miesiące i przez taki okres od wygenerowania ostatniego access tokena możesz go odświeżyć bez konieczności ponownego uwierzytelniania. Mogą się jednak zdarzyć sytuacje, że tokeny zostaną unieważnione (m.in. zmiana hasła na koncie). 

Gdy tylko przesłane przez Ciebie w formularzu dane dotrą do mnie - sprawdzę ten przypadek i wrócę z odpowiedzią.

**Comment by Raafal78** [comment]
A tak przy okazji - to jakie są możliwe sytuacje że token zostaje unieważniony? 
- Jestem zaskoczony że zmiana hasła jest jedną z takich sytuacji. Po to są tokeny dostępowe żeby nie było powiązania z hasłem do konta. 
Czekam też na inwestygację zgłoszenia 13868053 - bo tam nic 'podejrzanego się nie zdarzyło moim zdaniem bo to jest moje konto.

**Comment by AureliuszBrussy** [comment]
Zgłoszenie do nas dotarło - przekazałem ten problem do odpowiedniego zespołu, który aktualnie to wyjaśnia. Wrócę do Ciebie z odpowiedzią. 

Token może zostać unieważniony właśnie w przypadku wylogowania się ze wszystkich urządzeń, co użytkownik może zrobić ręcznie lub w wyniku zmiany hasła. Unieważnienie tokena może także nastąpić w wyniku przekroczenia liczby aktywnych sesji (max. 20 otwartych sesji dla jednego użytkownika).

**Comment by Raafal78** [comment]
Witam , czy jest jakiś postęp w inwestygacji zgłoszenia 13868053

**Comment by AureliuszBrussy** [comment]
@Raafal78 jeszcze nad tym pracujemy. Wrócę do Ciebie z wiadomością.

**Comment by Raafal78** [comment]
Witam , czy jest jakiś postęp w inwestygacji zgłoszenia 13868053

**Comment by AureliuszBrussy** [comment]
@Raafal78 niestety, jeszcze nie jestem w stanie przekazać wiążącej informacji. Pamiętam o tym i na pewno wrócę do Ciebie z informacją, gdy już to wyjaśnimy.

**Comment by Raafal78** [comment]
Witam , czy coś wiadomo ?  Dzisiaj piątek 12.03  po 16-tej  , 6-sć sklepów nie mogło odświeżyć tokena dostępowego

**Comment by AureliuszBrussy** [comment]
@Raafal78 niestety, jeszcze nie mam dla Ciebie informacji zwrotnej. Postaram się wrócić z odpowiedzią możliwe najszybciej.

**Comment by AureliuszBrussy** [comment]
@Raafal78 dziękuję za cierpliwość. Problem nie powinien już występować.

**Comment by Raafal78** [comment]
Witam, niestety pogorszyło się bo przed info o poprawie,  problem był tylko z moim kontem a od poprawki czyli do 2-ch dni codziennie inny sklep ma problem z odświeżeniem tokena .

Jakie informacje przekazać celem weryfikacji  . Czy robić to tutaj czy przez formularz ?

**Comment by AureliuszBrussy** [comment]
@Raafal78 poprosiłbym tak jak wcześniej - o przesłanie przykładowych tokenów przez formularz kontaktowy.

**Comment by Raafal78** [comment]
Szczegóły wysłane w tym zgłoszeniu:    Przyjęliśmy zgłoszenie numer "14352537" ref:_00D24aE05._5003VBv1kO:ref

**Comment by AureliuszBrussy** [comment]
@Raafal78 otrzymałem już Twoje zgłoszenie, przekazałem sprawę do analizy przez odpowiedni zespół.

**Comment by AureliuszBrussy** [comment]
@Raafal78 dziękuję za cierpliwość. 

W zgłoszeniu podałeś na przykłady. 

W pierwszym z nich refresh token został unieważnione ze względu na blokadę konta sprzedającego. 

W drugim przypadku, na koncie użytkownik zmienił hasło. W takich przypadkach także następuje unieważnienie wszystkich tokenów, które zostały wygenerowane przed zmianą hasła.

**Comment by Raafal78** [comment]
Dzięki za inwestygację.

Że blokada konta sprzedającego  unieważnia token to jest coś nowego( nie było to wyżej wymienione). Blokada rozumiem może być z wielu przyczyn i czy to nie jest czasem błąd że nie pozwalacie aplikacji klienta np wyłączyć wszystkich produktów itp ?

Przykładowo: klientowi spalił się magazyn i w tym samym czasie zablokowali mu konto. Stany magazynowe wyzerował w swoim programie magazynowym i przez moja aplikację chciałby zamknąć sporo aukcji a przez unieważnienie tokena nie może tego zrobić .

Czy takie działanie jest na pewno dobre dla klienta oraz Allegro ? 

Unieważnienie tokenów aplikacji w związku ze zmianą hasła klienta też moim zdaniem jest słabe bo przecież po to są tokeny aplikacyjne żeby rozdzielić konto użytkownika   od dostępów aplikacji do konta.

**Comment by AureliuszBrussy** [comment]
@Raafal78 żadne z powyższych powodów unieważnienia tokena nie jest przez nas rozpatrywane jako błąd, jest to zachowanie zgodne z naszymi założeniami.
