### ISSUE TITLE
Zmiana ilości  PHP

### ISSUE THREAD

**Issue by odidarek** [allegro/allegro-api#3760]
Proszę o pomoc w ułożeniu skryptu do zmiany ilości dostępnych w ofercie przy pomocy PHP.
Nie wiem jak przekazać opcje komendy  https://api.allegro.pl/sale/offer-quantity-change-commands/{commandId} 

załączam skrypt php który chcę użyć do tego zadania

po uzyskanu tokena 

$response = $api->getNewAccessToken($code);

$tokenObject = json_decode($response);

$access_token = $tokenObject->access_token;

$getOffersUrl = 'https://api.allegro.pl/sale/offer-quantity-change-commands';

$parametry='{"modification":{"changeType":"GAIN","value":10},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":
[{"id":"23488973"}]}]}';

$ch = curl_init($getOffersUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
curl_setopt($ch, CURLOPT_HTTPHEADER, [
"Authorization: Bearer $access_token",
"Accept: application/vnd.allegro.public.v1+json",
"Content-Type: application/vnd.allegro.public.v1+json"	 
    ]);

    $offersResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
 
    curl_close($ch);

    if ($offersResult === false || $resultCode !== 200) {
        echo "Response status code: $resultCode\n";
    }

return ;

**Comment by MaciejFrackowiak** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może ktoś z użytkowników forum będzie mógł wesprzeć Cię w tym temacie.

**Comment by m17ek** [comment]
Dodaj: 

`curl_setopt($ch, CURLOPT_POSTFIELDS, $parametry);`

I do adresu URL wygeneruj UUID ( https://developer.allegro.pl/about/)


```
function gen_uuid() {

    return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        // 32 bits for "time_low"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        // 16 bits for "time_mid"
        mt_rand( 0, 0xffff ),

        // 16 bits for "time_hi_and_version",
        // four most significant bits holds version number 4
        mt_rand( 0, 0x0fff ) | 0x4000,

        // 16 bits, 8 bits for "clk_seq_hi_res",
        // 8 bits for "clk_seq_low",
        // two most significant bits holds zero and one for variant DCE1.1
        mt_rand( 0, 0x3fff ) | 0x8000,

        // 48 bits for "node"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    );

}

$uuid = gen_uuid(); // https://www.php.net/manual/en/function.uniqid.php
$getOffersUrl = 'https://api.allegro.pl/sale/offer-quantity-change-commands/'.$uuid;
```

**Comment by odidarek** [comment]
skrypt przerobiłem ale otrzymuje  Response status code: 201

    $access_token = $tokenObject->access_token;
		
	$parametry='{"modification":{"changeType":"GAIN","value":10},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"88878777772"}]}]}';

	$uuid = gen_uuid(); 
	$getOffersUrl = 'https://api.allegro.pl/sale/offer-quantity-change-commands/'.$uuid;
		
	echo $getOffersUrl;
	
	$ch = curl_init($getOffersUrl);

    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $access_token",
                 "Accept: application/vnd.allegro.public.v1+json",
				 "Content-Type: application/vnd.allegro.public.v1+json"
    ]);
	
     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
	curl_setopt($ch, CURLOPT_POSTFIELDS, $parametry);
	
	

    $offersResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
 
    curl_close($ch);

    if ($offersResult === false || $resultCode !== 200) {
        echo "Response status code: $resultCode\n";
    }

return ;


function gen_uuid() {

    return sprintf( '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
        // 32 bits for "time_low"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),

        // 16 bits for "time_mid"
        mt_rand( 0, 0xffff ),

        // 16 bits for "time_hi_and_version",
        // four most significant bits holds version number 4
        mt_rand( 0, 0x0fff ) | 0x4000,

        // 16 bits, 8 bits for "clk_seq_hi_res",
        // 8 bits for "clk_seq_low",
        // two most significant bits holds zero and one for variant DCE1.1
        mt_rand( 0, 0x3fff ) | 0x8000,

        // 48 bits for "node"
        mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
    );

}

**Comment by odidarek** [comment]
Dziękuję działa.

Rozumiem, że kod 201 informuje o oczekiwaniu na zmianę?

**Comment by MaciejFrackowiak** [comment]
@odidarek Kod 201 oznacza, że komenda została zarejestrowana (zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT)). Dokładny status wykonania operacji możesz sprawdzić korzystając z [GET /sale/offer-quantity-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getQuantityModificationCommandTasksStatusesUsingGET).

**Comment by odidarek** [comment]
Wszystko działa dziękuję za pomoc.
Pozdrawiam
