### ISSUE TITLE
Zmiana danych dostawy przez kupującego

### ISSUE THREAD

**Issue by RaVq3K** [allegro/allegro-api#3761]
Witam, aktualnie pracujemy nad funkcjonalność informowania naszych użytkowników odnośnie zmiany adresu dostawy przez kupującego, chcieliśmy odtworzyć taką sytuację po stronie https://allegro.pl.allegrosandbox.pl/ wchodząc w odpowiednio w szczegóły zamówienia i klikając przycisk "ZMIEŃ", niestety wywołanie tego, nie powoduje nic po stronie Allegro w konsoli można zaś zobaczyć błędy przy każdej próbie wywołania tej akcji. 

![image](https://user-images.githubusercontent.com/53236315/95547397-37116a80-0a03-11eb-8957-5a93712adb93.png)

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie funkcjonalności - bez przeszkód na testowym zamówieniu edytowałem adres dostawy/nr telefonu. Proszę podaj id zamówienia oraz id konta, z którego dokonałeś testowego zakupu.

**Comment by RaVq3K** [comment]
nr zamówienia : 4df0a9b0-0930-11eb-bdbf-11335cc828c9, nie mogę znaleźć ID Sklepu: 44203348

**Comment by MaciejFrackowiak** [comment]
Nie udało mi się powtórzyć napotkanego błędu - bez przeszkód wywołałem okno Zmień z adresami do wyboru. Sprawdź proszę czy przypadkiem nie masz zablokowanych wyskakujących okienek lub nie używasz innych programów blokujących.

**Comment by RaVq3K** [comment]
Tak dla pewności czy aby na pewno mówimy o tym samym miejscu staram się wejść w 
https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione/4df0a9b0-0930-11eb-bdbf-11335cc828c9#edytuj-adres-dostawy

Próbowałem na zupełnie nowej przeglądarce zezwoliłem na wszystko koleżanka również i oboje nie możemy w to wejść:
na firefox pokazuje się coś takiego: 

![image](https://user-images.githubusercontent.com/53236315/95581964-30eab080-0a3a-11eb-8153-327e91a749dc.png)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za screen - dał kluczową wskazówkę. Rzeczywiście, problem istnieje - zgłosiłem już to do zespołu odpowiedzialnego za funkcjonalność. Wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@RaVq3K Update - udało nam się wyeliminować problem, edycja działa już w pełni prawidłowo. Przepraszam za niedogodności.
