### ISSUE TITLE
Atrybut klasyfikacji uzyskany za pośrednictwem interfejsu API jest niezgodny z tłem zarządzania

### ISSUE THREAD

**Issue by rovingsoul** [allegro/allegro-api#3762]
Istnieje partia katalogów, które mają atrybuty uzyskane przez API bez "Marka-podaj wartość", ale zaplecze zarządzania ma ten atrybut. Na przykład id katalogu 257489

**Comment by MaciejFrackowiak** [comment]
Zgadza się, tylko dla parametrów, przy których widnieje flaga "customValuesEnabled": true można dodać własną wartość dla parametru z wartością niejednoznaczną. Opisywaliśmy to w poście https://github.com/allegro/allegro-api/issues/3590.

**Comment by rovingsoul** [comment]
The translation is problematic!
I mean
The parameter "Marka-podaj wartość" was not found in the attributes obtained from the API
`{
    "parameters":[
        {
            "id":"11323",
            "name":"Stan",
            "type":"dictionary",
            "required":true,
            "requiredForProduct":false,
            "unit":null,
            "options":{
                "variantsAllowed":false,
                "variantsEqual":true,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":false,
                "customValuesEnabled":false
            },
            "dictionary":[
                {
                    "id":"11323_1",
                    "value":"Nowy",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"11323_2",
                    "value":"Używany",
                    "dependsOnValueIds":[

                    ]
                }
            ],
            "restrictions":{
                "multipleChoices":false
            }
        },
        {
            "id":"209278",
            "name":"Marka",
            "type":"dictionary",
            "required":true,
            "requiredForProduct":true,
            "unit":null,
            "options":{
                "variantsAllowed":false,
                "variantsEqual":true,
                "ambiguousValueId":"209278_238718",
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":true
            },
            "dictionary":[
                {
                    "id":"209278_238570",
                    "value":"Ada",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_280733",
                    "value":"Aleas",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238574",
                    "value":"Aqua Art",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238590",
                    "value":"Aquabotanique",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238594",
                    "value":"Aquael",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238598",
                    "value":"Aquaforest",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_571709",
                    "value":"AquaGlass",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238602",
                    "value":"Aquamax",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238578",
                    "value":"Aqua Nova",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238582",
                    "value":"Aqua Rebell",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_727058",
                    "value":"Aquastel",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238586",
                    "value":"Aqua Szut",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238606",
                    "value":"Aquawild",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_266274",
                    "value":"Atman",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238610",
                    "value":"Azoo",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_730834",
                    "value":"Blue-Line",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238614",
                    "value":"BorneoWild",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238618",
                    "value":"CAL Aqua Labs",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238622",
                    "value":"Chihiros",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238626",
                    "value":"Dennerle",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238630",
                    "value":"Diversa",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238634",
                    "value":"Drak",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_252198",
                    "value":"Easy Life",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238642",
                    "value":"Eheim",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238646",
                    "value":"Femanga",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_579657",
                    "value":"GHL",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_264378",
                    "value":"Glopex",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_729268",
                    "value":"Goldi",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_246978",
                    "value":"Hagen",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_264386",
                    "value":"Hailea",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_264374",
                    "value":"Happet",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238650",
                    "value":"Hikari",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_403114",
                    "value":"Hozelock",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_260430",
                    "value":"Hs Aqua",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238654",
                    "value":"Hydor",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238658",
                    "value":"Ikola",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238662",
                    "value":"Ista",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238666",
                    "value":"JBL",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_260354",
                    "value":"Jeneca",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238670",
                    "value":"Juwel",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238674",
                    "value":"Kordon",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238678",
                    "value":"Microbe-lift",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_260426",
                    "value":"Naturefood",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238682",
                    "value":"Planta Garden",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238686",
                    "value":"Prodibio",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_264390",
                    "value":"Salifert",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_567629",
                    "value":"Sanikoi",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238690",
                    "value":"Seachem",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238694",
                    "value":"Sera",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_264382",
                    "value":"Shrimp Nature",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238698",
                    "value":"Sunsun",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_260370",
                    "value":"Supreme",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238702",
                    "value":"Tetra",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238706",
                    "value":"Tropical",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_260374",
                    "value":"UST-M",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238710",
                    "value":"Vimi",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_280717",
                    "value":"Wiwal",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_280721",
                    "value":"Wromak",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238714",
                    "value":"Zoolek",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"209278_238718",
                    "value":"inna",
                    "dependsOnValueIds":[

                    ]
                }
            ],
            "restrictions":{
                "multipleChoices":false
            }
        },
        {
            "id":"210246",
            "name":"Materiał",
            "type":"dictionary",
            "required":true,
            "requiredForProduct":true,
            "unit":null,
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":"210246_242066",
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "dictionary":[
                {
                    "id":"210246_242050",
                    "value":"ceramika",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"210246_242054",
                    "value":"szkło",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"210246_242058",
                    "value":"tworzywo sztuczne",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"210246_242062",
                    "value":"żywica poliestrowa",
                    "dependsOnValueIds":[

                    ]
                },
                {
                    "id":"210246_242066",
                    "value":"inny materiał",
                    "dependsOnValueIds":[

                    ]
                }
            ],
            "restrictions":{
                "multipleChoices":false
            }
        },
        {
            "id":"207758",
            "name":"Wysokość",
            "type":"float",
            "required":false,
            "requiredForProduct":false,
            "unit":"cm",
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "restrictions":{
                "min":0,
                "max":1000,
                "range":false,
                "precision":2
            }
        },
        {
            "id":"207622",
            "name":"Szerokość",
            "type":"float",
            "required":false,
            "requiredForProduct":false,
            "unit":"cm",
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "restrictions":{
                "min":0,
                "max":1000000,
                "range":false,
                "precision":2
            }
        },
        {
            "id":"207766",
            "name":"Głębokość",
            "type":"integer",
            "required":false,
            "requiredForProduct":false,
            "unit":"cm",
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "restrictions":{
                "min":0,
                "max":1000,
                "range":false
            }
        },
        {
            "id":"17448",
            "name":"Waga (z opakowaniem)",
            "type":"float",
            "required":false,
            "requiredForProduct":false,
            "unit":"kg",
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":false,
                "customValuesEnabled":false
            },
            "restrictions":{
                "min":0,
                "max":1000000,
                "range":false,
                "precision":3
            }
        },
        {
            "id":"225693",
            "name":"EAN",
            "type":"string",
            "required":false,
            "requiredForProduct":false,
            "unit":null,
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "restrictions":{
                "minLength":8,
                "maxLength":18,
                "allowedNumberOfValues":1
            }
        },
        {
            "id":"224017",
            "name":"Kod producenta",
            "type":"string",
            "required":false,
            "requiredForProduct":true,
            "unit":null,
            "options":{
                "variantsAllowed":false,
                "variantsEqual":false,
                "ambiguousValueId":null,
                "dependsOnParameterId":null,
                "describesProduct":true,
                "customValuesEnabled":false
            },
            "restrictions":{
                "minLength":2,
                "maxLength":50,
                "allowedNumberOfValues":1
            }
        }
    ]
}`

![image](https://user-images.githubusercontent.com/9605995/95558332-a52c5080-0a48-11eb-93b6-e26908a7205f.png)

**Comment by rovingsoul** [comment]
Yes, it has been solved

**Comment by MaciejFrackowiak** [comment]
You can switch into English using our website:
![obraz](https://user-images.githubusercontent.com/53566763/95573186-5b813d00-0a2b-11eb-9893-6f77e23b83c1.png)

In API you should use accept-language header "en-US" to receive response in English.
