### ISSUE TITLE
Problem z autoryzacją aplikacji (Nie możemy wyświetlić strony)

### ISSUE THREAD

**Issue by robert0770** [allegro/allegro-api#3763]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Mam napisaną funkcje która tworzy przekierowanie do allegro z prośbą o uzyskanie dostępu do access tokena (po akceptacji użytkownik zostaje przekierowany na naszą strone z odbiorem code), ale kiedy się zaloguje na allegro dostaje:

Nie możemy wyświetlić strony
Numer błędu: 161b0edc34809966

dodam że adres powrotu w allegro devlopers jest ustawiony poprawnie, jest taki sam jak w AllegroAuth

to do tej pory działało, nie było zmian, a dzisiaj nagle nie działa (kiedyś dostawałem czasem tez takie błędy ale wystarczyło wykonać operacje jeszcze raz, ale dzisiaj robiłem to z 10x i nadal nic oraz testowałem na różnych przegladarkach)

**Comment by MaciejFrackowiak** [comment]
Otrzymany komunikat "Nie możemy wyświetlić strony" jednoznacznie potwierdza, że adres podany w aplikacji nie jest tożsamy (musi być 1:1) z tym, który został podany przy rejestracji aplikacji na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Sprawdź proszę raz jeszcze zgodność danych.

**Comment by robert0770** [comment]
jest taki sam, nawet nie było nic zmieniane w kodzie i przestało działać z dnia na dzień, nawet usunałem poprzednia aplikacje i zrobiłem nową dzisiaj  i podmieniłem client id i client secret i to samo było

macie logi jakies z tego nr błedu zeby je sprawdzić? moge podać Client id jezeli będzie łatwiej znaleźć log

**Comment by MaciejFrackowiak** [comment]
Proszę podaj ClientID.

**Comment by robert0770** [comment]
b4f2cb273dd4486c8a1f57455bc5e366

**Comment by MaciejFrackowiak** [comment]
Adresy nie są identyczne - wysyłasz https://domena/pl/rozszerzenie, a adres zarejestrowany to https://domena/rozszerzenie - za dużo o jedno "pl/".

**Comment by robert0770** [comment]
faktycznie, przepraszam za zamieszanie, zapomniałem ze dodałem locale do każdego urla
