### ISSUE TITLE
Pobieranie zdjęć

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#3765]
Czy rest api umożliwia pobranie zdjęć z ofert?
Oczywiście mowa jest o ofertach ze konta użytkownika a nie z każdej możliwej oferty

**Comment by AureliuszBrussy** [comment]
Gdy pobierzesz ofertę za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) w response otrzymasz m.in. bezpośrednią ściężkę do wszystkich zdjęć dodanych do oferty.  Możesz te zdjęcia pobrać korzystając z tych ścieżek.

**Comment by mlonc** [comment]
Dzięki! 👍
