### ISSUE TITLE
how to  find the  corresponding api of the picture?

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#3766]
I'm a little confused. I want to cancel the option in the picture through the interface ,could you show me a corresponding api?
![image](https://user-images.githubusercontent.com/72594584/95653422-3aa01100-0b2b-11eb-92aa-a7df639a3a37.png)

 I'm looking forward to your reply.

**Comment by bingnew** [comment]
Jak znaleźć odpowiadający im api obrazka?

Jestem trochę zdezorientowany.Chcę anulować opcję w obrazku przez interfejs, czy mógłbyś pokazać mi odpowiadający api?
![image](https://user-images.githubusercontent.com/72594584/95653488-ada98780-0b2b-11eb-8385-27b94f20e7cd.png)

**Comment by AureliuszBrussy** [comment]
You can modify your offer my using [PUT /sale/offer-modification-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT) or [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT). You will find all promotion option under the **promotion** field:

```
"promotion": {
"bold": true,
"departmentPage": true,
"emphasized": true,
"emphasizedHighlightBoldPackage": true,
"highlight": true
}
```

You need to set **promotion.emphasized** to **false** (or other fields, depending on the used promotion options).

**Comment by bingnew** [comment]
Thank you for your answer!
I also want to know through which  interface can I get the "data naliczenia opłaty"  ?
if you can not understand me, You can look at the arrow in the picture.
![image](https://user-images.githubusercontent.com/72594584/95759386-35ce8f00-0cdc-11eb-8436-87cede9690b8.png)

**Comment by AureliuszBrussy** [comment]
You can calculate fee and commission for an offer by using [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST).

**Comment by rovingsoul** [comment]
> You can calculate fee and commission for an offer by using [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST).

The API  response like this:
{
    "commissions": [
        {
            "name": "Prowizja od sprzedaży",
            "fee": {
                "amount": 6.46,
                "currency": "PLN"
            }
        }
    ],
    "quotes": [
        {
            "name": "Wystawienie przedmiotu",
            "fee": {
                "amount": 0.00,
                "currency": "PLN"
            },
            "cycleDuration": "PT240H",
            "classifiedsPackage": {
                "id": null
            }
        }
    ]
}

I have no idea to understand what is the start time or end time  "cycleDuration" base on

**Comment by AureliuszBrussy** [comment]
Fees are charged every 10 days. Use [GET /pricing/offer-quotes](https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET) to check when a given cycle ends and we charge another fee.

**Comment by bingnew** [comment]
And  how  can I get the  Interface  of  whole  lists  which contains  all promotions  we add  ?
the promotion means like the red sign  in  the  picture.
![image](https://user-images.githubusercontent.com/72594584/95941697-f0ad7880-0e13-11eb-860c-c932e59d1723.png)

**Comment by AureliuszBrussy** [comment]
To see all promotion option added to offer use [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). In response, you will see all promotion option in **promotion** field:
```
...
"promotion": {
"bold": true,
"departmentPage": true,
"emphasized": true,
"emphasizedHighlightBoldPackage": true,
"highlight": true
}
...
```

"true" means, that option is enabled. the **emphasized** option corresponds with "Wyróżnienie".

**Comment by bingnew** [comment]
you missed me. I want to get a list of all the products  added "wyr ó ż nienie",could you show me this interface?

**Comment by AureliuszBrussy** [comment]
It is not possible to filter promoted offers via Allegro API - it's only possible through our site, in [My offers](https://allegro.pl/my-allegro/sales/my-offers) tab. We already have such a suggestion on our suggestion list. If we introduce such functionality - we will inform you about it.

**Comment by bingnew** [comment]
OK, I'm expecting that,thank you very much for your professional support!

**Comment by bingnew** [comment]
Excuse me again，
**Department page、emphasized、Emphasized highlightboldpackage**，Which option do these three correspond to  in backstage？Can you  show me by a picture？
![image](https://user-images.githubusercontent.com/72594584/96087648-c54f8a00-0ef6-11eb-8124-76c75aa437a8.png)

**Comment by AureliuszBrussy** [comment]
**Emphasized** corresponds to "Wyróżnienie" (on the picture: "Featured offers"). **DepartmentPage** field means promotion on the category page. **EmphasizedHighlightBoldPackage** corresponds to "Promo Package" ("Pakiet Promo").
