### ISSUE TITLE
Błąd 406  ads/campains

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#3767]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

 curl -X GET \
  'https://api.allegro.pl/ads/campaigns’ \
  -H 'Authorization: Bearer {token}'  \
  -H 'Accept: application/vnd.allegro.public.v1+json' 

$token= string(1167) "[token ukryty]"

$token_type= string(6) "bearer"

$accept= string(38) "application/vnd.allegro.public.v1+json"

$parametr= string(13) "ads/campaigns"

$url= string(36) "https://api.allegro.pl/ads/campaigns"

$resultCode= int(406)

$response= string(255) "{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}"

**Comment by AureliuszBrussy** [comment]
Zasób do którego próbujesz zyskać dostęp nie jest zasobem publicznym, dlatego otrzymujesz komunikat błędu. Na forum wspieramy tylko zasoby opisane w [dokumentacji](https://developer.allegro.pl/documentation/).

**Comment by Zbigi** [comment]
A kiedy będzie dostępny lub jak uzyskać dostęp. Wiem, że nie którzy z tego korzystają

**Comment by AureliuszBrussy** [comment]
Aktualnie nie ma możliwości uzyskania dostępu do tych zasobów. Jeżeli w przyszłości podjęta zostanie decyzja o ich upublicznieniu, to na pewno poinformujemy o tym w osobnym komunikacie na forum oraz w [aktualnościach ](https://developer.allegro.pl/news/) na portalu.
