### ISSUE TITLE
Problem z uzyskaniem tokena do urządzenia

### ISSUE THREAD

**Issue by odidarek** [allegro/allegro-api#3768]
Witam .
mam  problem z otrzymaniem tokena do urządzenia autoryzowanego zdalnie "Device flow dla Allegro OAuth"

po otrzymaniu   "device_code":"3333333333333333333h"  
wykonuję następujący kod: 

$dev='3333333333333333333h';

$getUrl = ' https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code='.$dev ;
$authorization = base64_encode($clientId . ':' .$clientSecret);

$ch = curl_init($getUrl);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Basic $authorization"
    ]);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
$Result = curl_exec($ch);
$resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

// wynik do pliku loga 

$wyszlo= print_r($Result,true);
file_put_contents("log_glowny.txt",  date("Y-m-d H:i:s") . PHP_EOL .'kod: '.$resultCode. PHP_EOL, FILE_APPEND);
file_put_contents("log_glowny.txt",  date("Y-m-d H:i:s") . PHP_EOL .$wyszlo. PHP_EOL, FILE_APPEND);

w logu otrzymuję 
******************************************************
2020-10-11 03:57:39
 https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=kod urządzenia 
2020-10-11 03:57:39
kod: 0
2020-10-11 03:57:39
******************************************************
żadnego błędu .

**Comment by odidarek** [comment]
znalazłem  !!!!

'TU MIAŁEM SPACJEEEE!!!https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=kod urządzenia'

co ciekawe zwrotnie nie otrzymujesz błędu tylko dostajesz nic :)

**Comment by AureliuszBrussy** [comment]
@odidarek rozumiem, że problem został rozwiązany?

**Comment by odidarek** [comment]
Tak dziękuję za zainteresowanie
Zamykam sprawę .
