### ISSUE TITLE
Sandbox dodawanie oferty z produktem

### ISSUE THREAD

**Issue by krzysztofzajaczkowski** [allegro/allegro-api#3769]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
```
curl -X POST
    ‘https://api.allegro.pl.allegrosandbox.pl/sale/product-offers’
    -H 'Authorization: Bearer {token}'
    -H 'Accept: application/vnd.allegro.beta.v1+json'
    -H ‘Accept-Language: en-US’
    -H 'Content-Type: application/vnd.allegro.beta.v1+json'
    -d ‘{
    "product": {                        -- product data
            "name": "Test product",
            "category":{
                    "id":"89060"
            },
        "parameters":[
            {
                    "name": "EAN",
                    "values": [
                                "0744861045021"
                    ]
                },
                {
                    "id": "237218",
                    "values": [
                                "Test value"
                    ]
                }
        ],
        "images":[   
                "https://...first-image-address.jpeg"
        ]
  },
    "sellingMode": {
            "price": {
                "amount": "220.85",         
                "currency": "PLN"
            }
    },
     "stock": {
            "available": 10                 
    }
}
```

Trace-id
c1450dc25141252a

Podczas próby dodania oferty wraz z nowym produktem(w images przekazuje link z uploadowanego wcześniej przez REST API zasobu), na zwrocie dostaję internal server error z response body:
```
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}
```

**Comment by AureliuszBrussy** [comment]
Otrzymaleś błąd 500 ze względu na chwile problemy. Aktualnie przy takim requeście powinieneś otrzymać response z błędem 422 z odpowiednim userMessage, w którym prawidłowo informujemy o podaniu błędnego parametru w kategorii. Sprawdź najpierw, jakie parametry musisz uzupełnić. W tym celu skorzystaj z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by qusand** [comment]
**Komentarz post-mortem 2026-05-12** dla osób trafiających tu z wyszukiwarki:

Trafiliśmy na ten sam `OfferImagesNotFoundException` mimo że obrazki w `productSet[].product.images` i `payload.images` były świeżo zuploadowane na sandboxowy CDN (`a.allegroimg.allegrosandbox.pl/...`) i odpowiadały na HEAD 200 OK z poprawnym `Content-Length` i `etag`. Klasyczne hipotezy (propagation delay, format string vs object, cache staleness, scope tokena) wszystkie obalone.

**Faktyczny powód u nas:** w `description.sections[*].items` typu `IMAGE` były URL-e **produkcyjnego** CDN-u (`a.allegroimg.com/...`) — to obrazki z opisu oferty produkcyjnej kopiowanej do sandboxa. Allegro Sandbox waliduje **wszystkie** URL-e w payloadzie `POST /sale/product-offers`, nie tylko te w `productSet`/`offer.images`. Produkcyjny URL zwraca 422 z `OfferImagesNotFoundException` — komunikat jest dokładnie ten sam, co dla pustego/błędnego zdjęcia w productSet, więc bardzo łatwo szukać nie tam, gdzie trzeba.

**Co utrudnia diagnozę:** response 422 ma `path: null` i `metadata: {}`, więc nie widać która konkretnie URL-ka jest "invalid". Trzeba zdumpować cały payload tuż przed POST i zgrepować `a.allegroimg.com` (bez `sandbox`) w `description.sections`.

**Możliwe podejścia:** wystrippować inline `IMAGE` z `description.sections` (TEXT sekcje zostają), albo zrehostować każdy URL z description przez `POST /sale/images` tak samo jak galerię, albo — przy katalogowym `product.id` — w ogóle dropnąć `description` i pozwolić Allegro użyć opisu z katalogu serwerowo.

**Sugestia ulepszenia dla Allegro:** dodanie pola `path` w response z konkretną ścieżką do problematycznego URL-a (np. `"description.sections[3].items[0].url"`) skróciłoby diagnozę o godziny.

**Comment by Lukasz-Zurek** [comment]
@qusand Dziękuję za sugestię optymalizacji.
