### ISSUE TITLE
Gorąca prośba o pomoc

### ISSUE THREAD

**Issue by BusterLodz** [allegro/allegro-api#377]
Witajcie.
Wiem, wyjdę na totalną lamę. Ale trudno. Z metodami WebAPI radzę sobie doskonale pod PHP. Natomiast przeczytałem, że w niedalekiej przyszłości WebAPI będzie wygaszane. W związku z tym, podjąłem tą nieszczęsną decyzję o zapoznaniu się z REST API. I tu się pojawił problem. Wg mojej oceny, dokumentacja jest średnio przydatna i dla mnie kompletnie niezrozumiała. W dokumentacji WebAPI było fajnie to wszystko opisane, wraz z przykładami. A tutaj kompletnie nic, a przynajmniej ja nie znalazłem. I teraz pytanie. Czy ktoś mógłby mnie nakierować jak z tego ustrojstwa pt. REST API korzystać w PHP??

**Comment by tztztztz** [comment]
Skąd informacja, że WebAPI ma być wygaszone?

**Comment by BusterLodz** [comment]
W dniu 6.06 została umieszczona informacja, że w kwietniu 2019 zostaną
usunięte metody do obsługi ofert i sprzedaży. A podtytuł tej informacji
brzmi "Wygaszamy WebAPI".A skoro tak, tol ogika mi podpowiada, że wszystko
idzie w stronę wygaszenia Webapi i przejścia całkowicie na REST API.
Chyba,  że się mylę.


pt., 6 lip 2018, 02:45 użytkownik Tomasz Zadora <notifications@github.com>
napisał:

**Comment by TomekKaczmarek** [comment]
- Przede wszystkim zapoznaj się z artykułami, w których opisaliśmy [podstawowe informacje o REST API](https://developer.allegro.pl/about/) i [proces autoryzacji](https://developer.allegro.pl/auth/).
- Każdy zasób opisaliśmy dokładnie w [aktualnościach](https://developer.allegro.pl/news/), znajdziesz tam cURLe z przykładowymi requestami.
- Dodatkowo - dla wystawiania ofert przygotowaliśmy [szczegółowy poradnik](https://developer.allegro.pl/sale/).
