### ISSUE TITLE
Get offer details

### ISSUE THREAD

**Issue by ikononenko627** [allegro/allegro-api#3770]
Hello,

How can I get the offer details related to a specific offer which I dont own ?
I tried to use GET https://api.{environment}/sale/offers/{offerId}, but it return forbidden error.

`Array
(
[code] => 403
[error] =>
[result] => Array
(
[errors] => Array
(
[0] => Array
(
[code] => FORBIDDEN
[message] => Forbidden
[details] =>
[path] => /sale/offers/7785031058
[userMessage] =>
)

)

)

)`

Is there is any solution for that ?
if not, are there any plans to add such us functionality? when ?

Thanks in advance.

Best regards, 
Ivan

**Comment by ikononenko627** [comment]
Are there any plans to add such us functionality?

**Comment by AureliuszBrussy** [comment]
We do not plan to introduce such functionality. Only the sellers can retrieve this kind of information about their offers.
