### ISSUE TITLE
Wysyłam z Allegro

### ISSUE THREAD

**Issue by fjjjq** [allegro/allegro-api#3771]
Występuje u mnie problem z dodaniem umowy własnej DHL na środowisku testowym. Pomimo wpisywania prawidłowych danych wciąż dostaje odpowiedź: "Dane dostępowe do API przewoźnika są nieprawidłowe. Oryginalny błąd: Nieprawidlowe dane autoryzacyjne". Te dane działają gdy loguje się na stronie DHL.

Uzupełniam **Nazwa wyświetlana** i **Login**, **Hasło** oraz **Numer SAP** w **Dane Dostępowe do API**

**Comment by AureliuszBrussy** [comment]
Czy możesz podać login konta, ktorego problem dotyczy?

**Comment by fjjjq** [comment]
Jakim niepublicznym kanałem komunikacji mogę wysłać Wam te dane?

**Comment by AureliuszBrussy** [comment]
Skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=14a4eea0-8c13-4c5f-84d2-aa1b52a06c15&subjectId=7eca6d55-c9cc-4e2a-a37f-4ad0de3c44d9), a w treści podaj numer zgłoszenia na GitGubie: #3771.

**Comment by AureliuszBrussy** [comment]
Na potrzeby integracji systemu DHL, należy wprowadzić dane autoryzacyjne do WebAPI DHL, a nie te, które wykorzystujesz bezpośrednio w systemie DHL. Skontatkuj się z przewoźnikem, aby uzyskać te dane.
