### ISSUE TITLE
Metoda GET /payments/refunds => zmiana statusu

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3772]
W zwrotach mamy statusy "SUCCESS" "CANCELED" "PARTIAL" "IN_PROGRESS" "VALIDATE_FAILED" "NEW"

Które z tych statusów mogą ulec zmianie w zwrocie. Rozumiem, że IN PROGRESS może przejść w SUCCESS lub inny a inne. Chodzi o to które statusy są statusem ostatecznym danego zwrotu i już się nie zmienią.

**Comment by AureliuszBrussy** [comment]
Ostateczne statusy, które nie ulegną zmianie to: "SUCCESS", "CANCELED", "PARTIAL" oraz "VALIDATE_FAILED". Zmianie mogą ulec zwroty ze statusami "NEW" oraz "IN_PROGRESS".

**Comment by pietrach** [comment]
Rozumiem, że tylko zwroty SUCCESS i PARTIAL doszły do skutku reszta albo oczekuje albo wystąpił błąd i zwrot nie został przelany ?

**Comment by AureliuszBrussy** [comment]
Tak, zgadza się, zwrot SUCCESS i PARTIAL (częściowo) doszły do skutku, NEW i IN_PROGRESS oczekują na potwierdzenie, a CANCELED i VALIDATE_FAILED oznacza, że zwrot się nie powiódł.
