### ISSUE TITLE
Brak synchronizacji stanów

### ISSUE THREAD

**Issue by 12dawid** [allegro/allegro-api#3773]
W trakcie synchronizacji stanów pojawia się następujący problem.

Otóż ilość w pierwszej aukcji, w której należy zmienić ilość, jest zmieniana bez problemu. Niestety dla drugiej, trzeciej itd. ilość nie jest zmieniana. Po odczekaniu dłuższej chwili (kilkunastu minut) i ponownym uruchomieniu synchronizacji, ilość w kolejnej aukcji jest poprawnie aktualizowana.

W programie każda aukcja jest aktualizowana z osobna. Przykładowo:
Aukcja o numerze X - 5 sztuk, faktyczny stan posiadanych produktów 6 sztuk
Aukcja o numerze Y - 7 sztuk, faktyczny stan posiadanych produktów  8 sztuk

W pierwszej kolejności polecenie zmiany ilości aukcji X o jeden w górę, na 6 sztuk. Następnie kolejne zmiana ilości aukcji Y o jeden w górę na 8 sztuk.

Na czym może polegać problem? W jaki sposób można go rozwiązać?

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać id konkretnych ofert, w których dokonujesz zmiany liczby sztuk i - jeżeli to możliwe - trace-id tych wywołań? Potrzebuję więcej szczegółów aby to zweryfikować.

**Comment by 12dawid** [comment]
9127909550 - e1daaf80c86bcefc
8979316431 - d7c7deb602756f5b

Pierwsza synchronizacja istotnie zmniejszyła stan aukcji o jeden, do właściwego stanu. Następna aktualizacja niestety mimo wysłania polecenia o zmniejszenie stanu nie powiodła się.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to w logach - próbujesz wykonać dwie osobne komendy wykorzystując ten sam uuid . Powinieneś wygenerować nowy uuid dla każdej nowej komendy.
