### ISSUE TITLE
GET /sale/offers - najstarsze oferty nie są zwracane 

### ISSUE THREAD

**Issue by lekki** [allegro/allegro-api#3775]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/sale/offers?limit=100&offset=2490&publication.status=ACTIVE 

Mam oferty aktywne z 2017,2018 i 2019 roku. Ostatnie zmiany spowodowały, że oferty z 2017 i 2018 nie są zwracane. Url powyżej zwraca tylko do kwietnia 2019 roku.

**Comment by AureliuszBrussy** [comment]
Czy możesz przesłać trace-id twojego wywołania i id przykładowej oferty, która nie jest zwraca, a powinna? Pozwoli mi to dokładniej sprawdzić ten problem.

**Comment by lekki** [comment]
Hej @AureliuszBrussy 

Przepraszam za zamieszanie. Wygląda na to, że oferty zostały zamknięte przez ADMIN.  Czy możesz przy okazji wyjaśnić, co to dokładnie oznacza?

**Comment by lekki** [comment]
@AureliuszBrussy  Przykładowe id zamkniętych aukcji to: 7657271941, 7657325076, 7684613084

**Comment by AureliuszBrussy** [comment]
Oznacza to, że dana oferta została zakończona przez administarcję. W kwestiach ustalenia powodu zakończenia oferty - proszę, skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=a2f3ea49-2579-47d5-87f4-6d96a42e3e86&subjectId=ae7b20da-ee49-4df4-90ed-39e32533ed8c).
