### ISSUE TITLE
Pytanie dot. CSV, opis oferty

### ISSUE THREAD

**Issue by gabrysr1997** [allegro/allegro-api#3776]
Dzień dobry,

Zwracam się do Państwa z pytaniem dot. opisu oferty dodawanego poprzez CSV.

Mam problem z modyfikacją tekstu w opisach. W standardowym wystawianiu aukcji (przez stronę WWW Allegro) jestem w stanie powiększyć odstępy między wierszami tekstu poprzez: styl tekstu -> podstawowy tekst. Wiem, że są problemy z działaniem tej funkcji (po zamknięciu danego kontenera z tekstem odstępy znikają), ale da się obejść ten błąd poprzez skopiowanie kontenera zamiast "zamykanie" go przez kliknięcie myszką poza jego polem. W skopiowanym kontenerze test posiada odstępy między wierszami. Taki sam efekt chciałbym osiągnąć podczas wystawiania aukcji za pomocą pliku CSV. Jakich znaczników muszę użyć, aby uzyskać ten efekt?

Z góry bardzo dziękuję.

Pozdrawiam, 
Gabriel

**Comment by AureliuszBrussy** [comment]
Dzień dobry. Skorzystaj proszę z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) aby uzyskać wspracie związane z wystawianiem ofert z pliku CSV.

**Comment by gabrysr1997** [comment]
Bardzo dziękuję. Napisałem zapytanie poprzez formularz. 

Moje pytanie dotyczyło edycji opisu w formacie JSON. Może mógłby mi Pan w tym jednak pomóc?

**Comment by AureliuszBrussy** [comment]
Aby uzyskać efekt odstępu między wierszami/akapitami - umieszczaj je w znacznikach <p>.

**Comment by gabrysr1997** [comment]
Najmocniej dziękuję! Wszystko działa.

Nie wpadłem na najprostszy sposób...
