### ISSUE TITLE
[PUT] /parcel-management/parcel-create-commands/{commandId} - Błąd z walidacją stringów wg. wzorców regex 

### ISSUE THREAD

**Issue by Venzonite1** [allegro/allegro-api#3777]
Występuje problem: 
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

trace-id: 634cbac7b8835c01

Opis:

Mimo podania imienia i nazwiska prawidłowego wg. dokumentacji, to Allegro zwraca następujący komunikat:
W requeście podałem imię i nazwisko alfanumerycznie podobne do frazy "Jan Kowalski".

```json

{
   "errors":[
      {
         "code":"VALIDATION_ERROR",
         "message":"musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ-]*\"",
         "details":"Invalid value: Jan Kowalski",
         "path":"receiver.name",
         "userMessage":"musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ-]*\""
      },
      {
         "code":"VALIDATION_ERROR",
         "message":"musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ-]*\"",
         "details":"Invalid value: Jan Kowalski",
         "path":"pickup.name",
         "userMessage":"musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ-]*\""
      }
   ]
}

```

**Comment by AureliuszBrussy** [comment]
Potwierdzam wystąpienie problemu. Wdrożyliśmy poprawkę. Aktualnie błąd nie powinien się powtórzyć.
