### ISSUE TITLE
GET order/refund-claims/{id}

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#3778]
Dlaczego metoda order/refund-claims/ dla id "a28d1896-e239-4cf3-a288-50fbca053dac" zwraca status REJECTED?
Po kontakcie z obsługą Allegro, uzyskaliśmy informacje, że prowizja została zwrócona, ale metoda wciąż zwraca informacje o odrzuceniu.

**Comment by AureliuszBrussy** [comment]
Widzę, że wniosek ten został odrzucony, jednak później nastąpiła ręczna korekta ze strony administracji Allegro. W takiej sytuacji we wniosku wciąż będzie widniał status REJECTED.

**Comment by hahyes** [comment]
> Widzę, że wniosek ten został odrzucony, jednak później nastąpiła ręczna korekta ze strony administracji Allegro. W takiej sytuacji we wniosku wciąż będzie widniał status REJECTED.

Sugerowałbym wprowadzenie jednoznacznych dodatkowych statusów w tym wypadku, podobnie do ofert gdzie otrzymujemy informację, czy oferta się zakończyła i przez kogo została zakończona (jest informacja, że aukcja została zakończona przez administrację na przykład). Ponadto, REST w tym wypadku zwraca informację nieprawdziwą. Dlatego sugeruję, żeby odpowiedzi zwracane z REST API były jednoznaczne.

**Comment by AureliuszBrussy** [comment]
Informacja o odrzuceniu takiego wniosku jest widoczna także na stronie Allegro.pl - API Allegro zwraca te same informacje, co www. Jeżeli masz sugestię dotyczącą działania całego Allegro - skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=d1df83fc-8979-4595-90f6-008242ba2095&subjectId=ac728b31-985b-4dd2-81a8-724f0b65170f).

**Comment by hahyes** [comment]
> Informacja o odrzuceniu takiego wniosku jest widoczna także na stronie Allegro.pl - API Allegro zwraca te same informacje, co [www](http://www). Jeżeli masz sugestię dotyczącą działania całego Allegro - skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=d1df83fc-8979-4595-90f6-008242ba2095&subjectId=ac728b31-985b-4dd2-81a8-724f0b65170f).

Ale API nie zwraca informacji o ręcznych korektach administracji. Skąd mam wiedzieć, czy administracja dokonała korekty patrząc od strony API? Jakoś w ofertach można było dać `"endedBy": "ADMIN"`. Ponadto, jeżeli administracja dokonała korekty i prowizja została zwrócona, dlaczego API zwraca REJECTED? Skoro takie sytuacje występują, powinny one mieć odzwierciedlenie w API. 

Może inaczej. Mamy sytuację, gdzie prowizja została zwrócona, a wniosek o zwrot został odrzucony. Więc co, zwracany status nie jest odzwierciedleniem zwrócenia prowizji? Można mieć w waszym systemie odrzucone wnioski, które zakończyły się decyzją o zwrocie? Kuriozalne, jak dla mnie.

Dla dewelopera powinno być jasne, co się wydarzyło.

**Comment by AureliuszBrussy** [comment]
Zgadza się, REST API nie zwraca informacji o ręcznej korekcie administracji - tam samo jest w takich przypadkach w zakładce [Złożone wnioski](https://allegro.pl/moje-allegro/moje-konto/rachunki/rabat-transakcyjny). Kwestia ta dotyczy ogólnej funkcjonalności Allegro, w związku bardzo proszę o kierowanie tego typu sugestii poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=d1df83fc-8979-4595-90f6-008242ba2095&subjectId=ac728b31-985b-4dd2-81a8-724f0b65170f).
