### ISSUE TITLE
Hello dear support

### ISSUE THREAD

**Issue by Yulikm** [allegro/allegro-api#3779]
We are interested in selling goods from your marketplace in Ukraine. Do you have an API key, so that we can place your products on our website?

Thank You in advance

**Comment by AureliuszBrussy** [comment]
To get API key (Client ID) - you need to register your application via [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/) tab. Please, see [our guide](https://developer.allegro.pl/en/auth/) where we describe the entire process of authentication and authorization.
