### ISSUE TITLE
[GET] parcel-management/parcel-create-commands/{uuid} - błąd walidacji, gdy ulica odbiorcy jest zbyt długa.

### ISSUE THREAD

**Issue by Venzonite1** [allegro/allegro-api#3780]
Występuje problem: 
 - [ x ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Trace-Id do zasobu, w którym utworzyłem przesyłkę: 1bc5a86b8d3011ab
Trace-Id do zasobu, w którym sprawdzałem status utworzenia przesyłki: 66ba11fad64900e5

Dziennik zdarzeń pozakupowych zwrócił mi bardzo długą ulicę odbiorcy. 
Zasób [GET] parcel-management/parcel-create-commands/{uuid} nie może poprawnie zwalidować mojej utworzonej przez api allegro przesyłki. Poniżej response:

``` json

{
   "id":"511d89d4-2aac-44ab-8a17-6a13e6525543",
   "parcelId":null,
   "status":"ERROR",
   "errors":[
      {
         "code":"ERROR",
         "message":"Receiver street name is too long",
         "details":null,
         "path":"receiver.address.street",
         "userMessage":"Nazwa ulicy odbiorcy jest za długa"
      }
   ]
}

```

**Comment by AureliuszBrussy** [comment]
Ograniczenie liczby znaków w adresie wynika z ograniczeń narzuconych przez systemy informatyczne przewoźników. Liczba ta zależna jest od konkretnego przewoźnika i musieliśmy dostosować się do tych limitów. W tym przypadku musisz skrócić adres odbiorcy.
