### ISSUE TITLE
[POST] /sale/offers - spora ilość błędów ServiceTimeoutException

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3781]
Dzień dobry,

na zasobie [POST} /sale/offers mam sporo błędów `ServiceTimeoutException`. Czy to jakiś problem po waszej stronie? Czy to jednak wini połączenie pomiędzy mną a Allegro?

Przykładowe Trace-Id: 
cbdbc324751bb536
9a2f92e3d7863c00
2a5d4957e7266d0b

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Przepraszam za niedogodność. Problem nie powinien już występować.
