### ISSUE TITLE
Problem z API, kluczem, ID, błąd 429, brak mozliwości uruchomienia panelu

### ISSUE THREAD

**Issue by roman15112** [allegro/allegro-api#3782]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 
od wczoraj mam problem głównie z błędem 429 - zbyt duża ilośc zapytań, programista ograniczył do minimum zapytania do bazy i nadal błąd widnieje, dodatkowo przy każdorazowej próbie zalogowania w CMS na konto allegro wychodzi błąd: błędny klucz lub brak klucza ********* na serwerze co powoduje brak komunikacji.

ID: 84e79e1f709d4f7e95fe906d9f5be2ec

prośba o jakiś raport, co generuje tyle zapytań bo już wszystkie zapytania są ograniczone i brakuje pomysłów o co chodzi aby to naprawić.

dziękuję

**Comment by AureliuszBrussy** [comment]
Widzę, że oprogramowanie z którego korzystasz generuje dużą ilość żądań podczas autoryzacji, konkretniej chodzi o zasób POST /auth/oauth/token. Nie wysyłasz żadnej wartości w parametrze refresh_token. Dodatkowo, mechanizm ten działa w Twoim oprogramowaniu niepoprawnie — próbuje odświeżyć token kilka tysięcy razy na sekundę.
