### ISSUE TITLE
ERR_BLOCK_SELL_COMPANY_INFO  

### ISSUE THREAD

**Issue by Gouverneur001** [allegro/allegro-api#3783]
Hi,

I am trying to list products but get this error: ERR_BLOCK_SELL_COMPANY_INFO
What does it mean and how can I solve this?

Thanks

**Comment by AureliuszBrussy** [comment]
Does the problem occur in a production or test environment? Can you also give your account login?

**Comment by Gouverneur001** [comment]
Hi,  the problem is in the production environment. account login is ecom@theagouverneur.com

**Comment by AureliuszBrussy** [comment]
Your account is not fully active yet. Please use the [contact form](https://allegro.pl/help/contact?category=bb4e4c9f-4b4e-4f53-b283-68cbdd1b9ffb&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433) to explain this.
