### ISSUE TITLE
Brak możliwości generowania tokenu, "Rany Julek!"

### ISSUE THREAD

**Issue by fk4mil** [allegro/allegro-api#3784]
Występuje problem: Brak możliwości generowania tokenu, "Rany Julek!"
 - [X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [X ] z logowaniem lub autoryzacją
 - [ X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)

:beetle: **Opis**

 Przy próbie wygenerowania nowego tokenu dla aplikacji, występują następujący komunikat
"Rany Julek!
Coś poszło nie tak.

Kody błędu dla kilku naszych kont:
Kod błędu: 7f825af708030f05
Kod błędu: a1c6ccaaa39b9dff
Kod błędu: 6e42ed907bf887cb

**Comment by AureliuszBrussy** [comment]
Aktualnie autoryzacja funkcjonuje prawidłowo - nie potwierdzam występowania problemów. Jeżeli jednak Twój problem dalej występuje - proszę, wyślij poprzez [formularz kontakowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) id konta lub refresh_token, z którego próbujesz skorzystać. W treści podaj numer zgłoszenia na GitHubie: #3784.
