### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by keskinege** [allegro/allegro-api#3786]
Hi,

Is it possible to have some sample data in sandbox seller accounts?

**Comment by AureliuszBrussy** [comment]
I assume you mean data such as orders etc.? If so, you need to register another Sandbox account and buy products in offers you listed on your seller's account. 

If you mean listing offers,  adding offer terms, shipping price, etc. - you need to create everything by yourself. If you need more information about this - check [out guide](https://developer.allegro.pl/en/sale/).

**Comment by keskinege** [comment]
Do I need to add products from web interface? it asks captcha almost at every step which makes it impossible to use.

**Comment by keskinege** [comment]
for example. I try to add a new offer. It asks me captha every time.

**Comment by keskinege** [comment]
I am really confused on sandbox. I try to add a new offer, it stops me for validation.
You can't sell yet.
Wait for your data to be verified. We will inform you about the result by e-mail within 3 working days.

**Comment by keskinege** [comment]
how can I request the accounts to be activated?

**Comment by AureliuszBrussy** [comment]
No, you don't have to list offers from the web interface, you can do this via [REST API](https://developer.allegro.pl/en/sale/). Please, give me your login on Sandbox. I will check that the account is fully activated.

**Comment by keskinege** [comment]
keskinege@keskinege.com

**Comment by AureliuszBrussy** [comment]
Your account is fully activated now. To list an offer use this form: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie
