### ISSUE TITLE
Metoda GET /sale/badge-campaigns, pole eligibility

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3787]
Co to oznacza, że:

- czy kampania jest dostępna dla zautoryzowanego użytkownika,
- dlaczego użytkownik  nie kwalifikuje się do udziału w danej kampanii

**Comment by AureliuszBrussy** [comment]
Aby móc wziąć udział w niektórych kampaniach, użytkownik musi spełnić konkretne warunki, wskazane w regulaminie kampanii. W przypadku braku spełnienia tych warunków przez zautoryzowanego użytkownika, w polu **eligible** zwrócimy wartość false, a w **refusalReasons** wskażemy powód.
