### ISSUE TITLE
Sandbox - jak wystawić przedmiot?

### ISSUE THREAD

**Issue by marcinek1312** [allegro/allegro-api#3788]
Chciałbym przetestować na sandboxie swoją integrację z allegro ale ciągle jest problem z Sandboxem. Po zalogowaniu do sandboxa klikam w wystaw przedmiot i przenosi mnie do produkcyjnego allegro (zupełnie nie wiem po co). A chciałem za pomocą konta nr 1 w sandboxie wystawić przedmiot, następnie za pomocą konta nr2 dokonać zakupu tego przedmiotu, a na koniec chciałem podłączyć się przez restapi by pobrać tą sprzedaż. No ale jak to zrobić jeśli ciągle przerzuca mnie do produkcji. Czy w sandboxie w ogóle można wystawić coś na sprzedaż?

**Comment by marcinek1312** [comment]
> Chciałbym przetestować na sandboxie swoją integrację z allegro ale ciągle jest problem z Sandboxem. Po zalogowaniu do sandboxa klikam w wystaw przedmiot i przenosi mnie do produkcyjnego allegro (zupełnie nie wiem po co). A chciałem za pomocą konta nr 1 w sandboxie wystawić przedmiot, następnie za pomocą konta nr2 dokonać zakupu tego przedmiotu, a na koniec chciałem podłączyć się przez restapi by pobrać tą sprzedaż. No ale jak to zrobić jeśli ciągle przerzuca mnie do produkcji. Czy w sandboxie w ogóle można wystawić coś na sprzedaż?

**Comment by AureliuszBrussy** [comment]
Sandbox funkcjonuje prawidłowo - widzę, że formularz wystawiania jest dostępny i wystawienie przedmiotu powinno być możliwe. Spróbuj skorzystać z tego linku: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by marcinek1312** [comment]
Wobec tego czy możecie poprawić link prowadzący do wystawiania przedmiotu w sandboxie? bo teraz to jest link do: https://allegro.pl.allegrosandbox.pl/offer/ a jak się to kliknie to przekierowuje na nieistniejącą witrynę: https://staging-lokalnie.allegrogroup.com/oferty/wystaw

**Comment by marcinek1312** [comment]
W ogóle trzeba dużo poprawić w Sandboxie bo on jest dziurawy jak sito. Chociażby Moje allegro/ Zakładka Sprzedaż i linki "Wystawione" oraz "Moje zamówienia" prowadzą poza sandbox. Niechlujstwo czy może szczególny przypadek?. Natykam się na to wielokrotnie wielu punktach sandboxa od wielu lat! Aż wydaje mi się to niemożliwe że tylko ja mam taki problem

**Comment by AureliuszBrussy** [comment]
Faktycznie, podczas próby wystawiania oferty z konta zwykłego (nie posiadającego statusu Firma) następuje przekierowanie na nieistniejacą witrynę. Wiemy o tym problemie. Na ten moment proszę, abyś korzystał w takim przypadku z tego linku https://allegro.pl.allegrosandbox.pl/offer/.

Dla konta zwykłego na Sandboxie w Moje Allegro - tak samo jak w przypadku wersji produkcyjnej strony - pokazujemy linki prowadzące do Allegro Lokalnie. Allegro Lokalnie nie posiada środowska testowego, stąd też przekierowanie.

**Comment by corteum** [comment]
Mam podobny problem. Chcę wystawić ofertę w sandboksie i pojawia się informacja 'Jeśli chcesz wystawić przedmiot, aktywuj sprzedaż.'
Konto jest aktywne, sprzedaż też: 'Status konta Sprzedaż aktywna - wpłata online.'

PS. Przy próbie zmiany na konto firmowe również nie widzi aktywnej sprzedaży.

**Comment by MaciejFrackowiak** [comment]
@corteum Proszę podaj login konta na Sandbox.

**Comment by corteum** [comment]
@MaciejFrackowiak mój login to: mojeoferty

**Comment by MaciejFrackowiak** [comment]
@corteum Konto nie było aktywne - właśnie je aktywowałem.

**Comment by romigrabarz** [comment]
Potwierdzam opisane problemy z linkowaniem na sandboxie. Poprawcie to proszę bo muszę co chwile sięgać do Github'a.

**Comment by MaciejFrackowiak** [comment]
@romigrabarz Mamy świadomość niedogodności jakie to rodzi, jednak problem nie jest na tyle błahy by można go wyeliminować od ręki, stąd prośba o korzystanie z podanego odnośnika.

**Comment by marcinek1312** [comment]
Dzień dobry. Minął ponad rok, od tego czasu poprawki nie zostały wdrożone. Nadal jak próbuję wystawić przedmiot w sandboxie to muszę iść do tego wątku żeby zdobyć poprawny link prowadzący do wystawiania przedmiotu, ale pomijając ten "drobny" problem to w momencie gdy próbuję wystawić przedmiot pisze mi że mam konto zablokowane, natomiast jak wchodzę w dane konta to mam napisane "Sprzedaż aktywna - wpłata online.", nigdzie nie widzę informacji o blokadzie konta. Proszę o odblokowanie konta. Moje konto na sandboxie to: marcinek1312

**Comment by MaciejFrackowiak** [comment]
@marcinek1312 Masz nieuregulowane należności na Sandbox - proszę skorzystaj z [symulatora płatności](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i dokonaj wpłaty, gdy mechanizm rozliczy wpłatę, będziesz mógł ponownie wystawiać oferty.

**Comment by kamil-karkus** [comment]
@MaciejFrackowiak mam podobny problem, przekształcone konto zwykłe w firmowe dostaje przekierowanie a utworzone na nowo nie jestem w stanie aktywować w pełni, problem jak na screenie login averatec1993
![image](https://user-images.githubusercontent.com/2456974/151710642-8eb6a804-eab0-4bda-b827-28af8844b80d.png)

**Comment by MaciejFrackowiak** [comment]
@kamil-karkus Aktywowałem Twoje konto - jest już widoczne jako firmowe. Możesz zatem wystawiać oferty na Sandbox.

**Comment by 32nd-agency** [comment]
Prosze wystawic oferte ID: 7775753393, login - monkey

**Comment by Lukasz-Zurek** [comment]
@32nd-agency Z tego co widzę - udało się Tobie wystawić wspomnianą ofertę. Doprecyzuj proszę zgłoszenie.
