### ISSUE TITLE
GET /offers/listing i jego możliwości

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#379]
Skoro ten zasób ma zastąpić doGetItemList czy istnieje w nim możliwość pobrania najnowszych wystawionych aukcji w danej kategorii lub kończących się w danej kategorii tak jak to umożliwia doGetItemList?
Dziękuję za odpowiedź.

**Comment by TomekKaczmarek** [comment]
Przykłady wywołań opisaliśmy [tutaj](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/). Gorąco zachęcamy - czytajcie nasze aktualności :).

Najnowsze oferty z danej kategorii: https://api.allegro.pl/offers/listing?category.id=257929&sort=-startTime i takie które się zaraz zakończą: https://api.allegro.pl/offers/listing?category.id=257929&sort=+endTime

**Comment by juhacz** [comment]
Dziękuję za odpowiedź, widziałem to i czytałem, czyli jest to jedyna metoda, rozumiem, że filtry dostępne w starej metodzie nie są dostępne na nowej tj. 1h, 2h, 24h itd.

**Comment by TomekKaczmarek** [comment]
@juhacz Ten zasób w REST API odpowiada funkcjonalnie Liście ofert i Wyszukiwarce na froncie Allegro - tam takich filtrów nie ma, więc nie udostępnimy ich w tym zasobie.

**Comment by copyact** [comment]
Witam, a ja chciałem pobrać wszystkie moje aukcje filtrując po seller.id i metoda zwraca tylko 58, a mam ich 1515. W czym może być problem?

**Comment by PawelTaberski** [comment]
@copyact  zajmiemy się Twoim problemem tutaj:  #400

**Comment by mjag8** [comment]
Z innej beczki:

Czy zasób GET /offers/listing będzie w przyszłości zwracał kompletne pole `publication` jak w przypadku zasobu GET /sale/offers/{offerId} ?
```
 "publication": {
   "duration": "PDT12H30M5S",
   "endingAt": "2018-09-27T11:25:08.054Z",
   "startingAt": "2018-09-27T11:25:08.054Z",
   "status": "string"
 }
```
Obecnie pole tylko w poniższej postaci jest zwracane i tylko dla zakończonych aukcji
```
"publication": {
  "endingAt": "string"
 }
```

**Comment by TomekKaczmarek** [comment]
@mjag8 Takie szczegóły zwrócimy na liście ofert sprzedawcy, nad którą obecnie pracujemy. Więcej informacji na ten temat podamy niedługo.

**Comment by MariaPawlikowska** [comment]
Metoda zwraca błąd 404 po takim zapytaniu:
https://api.allegro.pl/offers/listing?seller.id=xxxxxx

**Comment by PawelTaberski** [comment]
@MariaPawlikowska Jaki seller.id podajesz w zapytaniu?

**Comment by MariaPawlikowska** [comment]
swój własny

**Comment by PawelTaberski** [comment]
Sprawdziłem na podstawie id użytkownika z allegro, który ma identyczny login jak Twój na GitHub-ie i otrzymałem poprawną odpowiedź.
Podeślij proszę pełnego cURL-a i responsa wraz z trace id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619). Sprawdzimy to, w zgłoszeniu zaznacz, że dane są potrzebne do zgłoszenia numer 379 na GitHub-ie.
