### ISSUE TITLE
Cena REST Api

### ISSUE THREAD

**Issue by agasior093** [allegro/allegro-api#3790]
Witam, 

1. Czy korzystanie z REST Api Allegro w wersji produkcyjnej jest całkowicie darmowe?
2. Czy napisanie na własne potrzeby aplikacji wyszukującej interesujące mnie oferty jest calkowicie zgodne z regulaminem? Taka aplikacja wykonywałaby około 7000 zapytań na minutę pod GET/offers/listing.

**Comment by AureliuszBrussy** [comment]
1. Tak, korzystanie z REST API w wersji produkcyjnej jest całkowicie darmowe.
2. Odpytywanie zasobu [GET/offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) nie jest niezgodnie z regulaminem, jednakże nakładamy na niego dodatkowy limit zapytań, tzw. [Leaky Bucket](https://developer.allegro.pl/about/#limits). Limit ten stanowi zabezpieczenie przed masowym odpytywaniem listingu o wyniki.

**Comment by agasior093** [comment]
Ok, dziękuje za odpowiedź. 
Mam jeszcze jedno pytanie co do /GET/offers/listing, może nie ma konieczności bym zakładał nowe issue? Mianowicie, wykonuje takie zapytanie
```
 https://api.allegro.pl/offers/listing
 ?seller.id={id}
 &phrase={phrase}
 &category.id={category}
 &include=-all&include=items
 &sort=-startTime
 &limit=20
```
Oczekuje dostać oferty danego sprzedawcy, zawierajace daną frazę w danej kategorii, oraz co ważne, chcę uzyskać tylko najnowsze przedmioty. By dodatkowo zmniejszyć rozmiar odpowiedzi, ograniczam response tylko do części z ofertami oraz ograniczam ich ilość do 20. O ile się nie mylę, powinienem więc dostawać 20 najnowszych ofert o danych kryteriach? Kilka razy się jednak zdarzyło, że  oferta którą otrzymałem w ten sposób była już zakończona, nie bardzo rozumiem jak to możliwe?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę pełen request i response w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), zweryfikuję to. W zgłoszeniu wskaż numer wątku GitHub: #3790.
