### ISSUE TITLE
Jak pobrać dane oferty (nazwa, data/czas zakończenia aukcji) na podstawie id /numeru oferty utworzonej przez innego usera?

### ISSUE THREAD

**Issue by immortalxxx** [allegro/allegro-api#3791]
Witam, mam id/numer oferty np "7678686161" i chciałbym pobrać jej dane (np nazwa). Z tego co widzę to nie mogę użyć "GET /offers/listing"... Czy jest jakaś inna metoda rest api którą mogę użyć (oferta została utworzona przez innego użytkownika)?

**Comment by immortalxxx** [comment]
Dodam tylko, że w WebAPI można było to zrobić za pomocą metody "doShowItemInfoExt" (atrybuty "itEndingTime" oraz "itName"). Z tego co widzę w changelogu "doShowItemInfoExt" zostało przeniesione do publicznych danych o ofertach (czyli "/offers/listing") ale nie jest to opisane w dokumentacji. Czy ktoś z Allegro moze wypowiedzieć się na ten temat?

**Comment by AureliuszBrussy** [comment]
W REST API nie udostępniamy bezpośredniego odpowiednika metody doShowItemInfoExt. Aby wyszukiwać dostępne w Allegro oferty wystawione przez innego użytkownika, korzystaj z [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - nie wyszukasz jednak oferty po jej numerze. Dostępne możliwości tego zasobu opisujemy w [naszym poradniku](https://developer.allegro.pl/listing/).

**Comment by immortalxxx** [comment]
Dzięki za odp, w takim razie gdzie jest informacja o dacie/czasie końca oferty (chcę wiedzieć kiedy oferta kończy się)? Nie jest to przypadkiem publiczna informacja? W odpowiedzi do GET /offers/listing nie widzę takiego atrybutu...

**Comment by AureliuszBrussy** [comment]
Jeżeli oferta wystawiona jest na określony czas - data zakończenia widoczna będzie w polu **publication.endingAt**. W przypadku ofert z czasem trwania "do wyczerpania przedmiotów" nie zwrócimy takiej informacji.

**Comment by immortalxxx** [comment]
Ok, chyba udało mi się to zrobić okrężną drogą, skoro nie można wyszukiwać po id aukcji to wyszukuję po nazwie aukcji i dostaję listę n aukcji, potem jadę po tej liście i porównuję id każdej z nich, jeśli zgadza się to mam ją, jeśli nie to prawdopodobnie skończyła się... 

Jest to moim zdaniem nie profesjonalne rozwiązanie ale cóż mi zostało. Proszę mi powiedzieć, dlaczego zdecydowaliście się pominąć opcje wyszukiwania po id aukcji, ze względów bezpieczeństwa? Nie rozumiem takiej decyzji, dziwny to standard...

**Comment by AureliuszBrussy** [comment]
Wyszukiwanie po ID oferty to funkcjonalność dodana wyłącznie do wyszukiwarki w serwisie WWW, aby kupującym uprościć możliwość wzajemnej wymiany informacji o interesujących i oglądanych produktach. Funkcjonalność ta nie miała i nie ma na celu zwracanie informacji, o których wspomniałeś w poście.

**Comment by immortalxxx** [comment]
Wszystko zostało wyjasnione
