### ISSUE TITLE
Zmiana statusu zamówienia

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#3792]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/order/checkout-forms/fe466ef2-107c-11eb-8ec3-c5ee60015f23/fulfillment
POST {'status'=>'PROCESSING'}

response:
{
  ["errors"]=array(1) {
    [0]=object(stdClass)#58 (5) {
      ["code"]=string(19) "NotAllowedException"
      ["message"]=string(30) "The HTTP method is not allowed"
      ["details"]=NULL
      ["path"]=NULL
      ["userMessage"]=string(17) "An error occurred"
    }
  }
}

Jaka jest przyczyna niepowodzenia zmiany statusu?

**Comment by AureliuszBrussy** [comment]
Widzę, że korzystasz z metody **POST**, natomiast prawidłowa metoda dla tego zasobu to [**PUT** /order/checkout-forms/{id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT)

**Comment by drzemik** [comment]
Dziękuję za pomoc.

Zadziałało.

 

Pozdrawiam

Dariusz Drzemicki
