### ISSUE TITLE
Sprawdzenie czy Smart po zakodowanym mailu

### ISSUE THREAD

**Issue by hYOUstone** [allegro/allegro-api#3793]
Endpoint (dla bearer-token-for-user) do sprawdzania zakodowanego maila użytkownika (kupującego), czy dane zlecenie to Smart jest następujące (dla sandbox):
https://api.allegro.pl.allegrosandbox.pl/logistics/brokers/api/orders?receiverEmail=
Czy istnieje jakiś endpoint do sprawdzania po mailu dla połączenia typu bearer-token-for-application? Nie mogę się doczytać w dokumentacji i zastanawiam się, czy jest takie sprawdzenie w ogóle możliwe (bez konieczności logowania się konkretnym sprzedającym -użytkownikiem). Nie chodzi mi tu o szczegóły zamówienia tylko o zero-jedynkową wartość zwracaną (jest/nie jest smartem) przy założeniu, że zakodowany mail posiada stałą dla danego użytkownika + token konkretnego zamówienia + @allegromail.com

**Comment by MaciejFrackowiak** [comment]
Każdy zasób, gdzie zwracane są jakiekolwiek dane, które nie są ogólnie dostępne ma autoryzację bearer-token-for-user.
