### ISSUE TITLE
Problem z POST /sale/offers

### ISSUE THREAD

**Issue by net-shops** [allegro/allegro-api#3794]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Jeśli zgłaszasz problem z zasobami REST API:
Request wygląda na poprawny a nie jest. Niestety ta odpowiedź nic totalnie nie mówi klientowi API.
cUrl:
`curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer xxx' \
--data-raw '{
    "name": "Buty piłkarskie adidas Predator 20.3 LL FG czarne EF1645",
    "category": {
        "id": "18014"
    },
    "parameters": [
        {
            "id": "11323",
            "values": [],
            "valuesIds": [
                "11323_1"
            ]
        },
        {
            "id": "215782",
            "values": [],
            "valuesIds": [
                "215782_271442"
            ]
        },
        {
            "id": "215798",
            "values": [],
            "valuesIds": [
                "215798_271470"
            ]
        },
        {
            "id": "15468",
            "values": [],
            "valuesIds": [
                "15468_8"
            ]
        },
        {
            "id": "203093",
            "values": [
                24.0
            ],
            "valuesIds": []
        },
        {
            "id": "215802",
            "values": [],
            "valuesIds": [
                "215802_271490"
            ]
        },
        {
            "id": "191",
            "values": [],
            "valuesIds": [
                "191_1"
            ]
        },
        {
            "id": "130411",
            "values": [],
            "valuesIds": [
                "130411_2"
            ]
        },
        {
            "id": "205826",
            "values": [],
            "valuesIds": [
                "205826_225046"
            ]
        },
        {
            "id": "207398",
            "values": [],
            "valuesIds": [
                "207398_231770"
            ]
        },
        {
            "id": "215790",
            "values": [],
            "valuesIds": [
                "215790_271458"
            ]
        },
        {
            "id": "227149",
            "values": [
                "Predator"
            ],
            "valuesIds": []
        },
        {
            "id": "224017",
            "values": [
                "EF1645"
            ],
            "valuesIds": []
        }
    ],
    "ean": "4062053770893",
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "To jest przykładowy tekst"
                    }
                ]
            }
        ]
    },
    "images": [
        {
            "url": "https://www.mywebsite.pl/upload/123589-1602294097.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123589-1602294097.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123590-1602294097.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123591-1602294097.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123592-1602294097.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123593-1602294098.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123594-1602294098.jpg"
        },
        {
            "url": "https://www.mywebsite.pl/upload/123595-1602294098.jpg"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "123.45",
            "currency": "PLN"
        }
    },
    "tax": 23,
    "stock": {
        "available": 0,
        "unit": "UNIT"
    },
    "publication": {
        "status": "INACTIVE",
        "republish": true
    },
    "delivery": {
        "shippingRates": {
            "id": "eabbbea0-0705-4ab7-8919-f68d69b98f8a"
        },
        "handlingTime": "PT48H",
        "additionalInfo": ""
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "dfc37a74-b962-4bf3-a9b4-fc5ba9e435c8"
        },
        "returnPolicy": {
            "id": "70b2b997-8eae-4dc3-b69b-50655bc35169"
        }
    },
    "promotion": {
        "bold": false,
        "departmentPage": false,
        "emphasized": false,
        "emphasizedHighlightBoldPackage": false,
        "highlight": false
    },
    "location": {
        "city": "Łódź",
        "countryCode": "PL",
        "postCode": "91-003",
        "province": "LODZKIE"
    },
    "external": {
        "id": "NET-SHOPS-155790-4062053770893"
    },
    "attachments": []
}'`

Response:
`{
    "errors": [
        {
            "code": "INVALID_JSON",
            "message": "Invalid request.",
            "details": null,
            "path": null,
            "userMessage": "Invalid request."
        }
    ]
}`

Trace-id: e6ca85e6386d72af

Problem ze stworzeniem oferty. Co jest nie tak w tym requeście?

**Comment by MaciejFrackowiak** [comment]
Twój request jest nieprawidłowy - nie można przekazywać "images" jeśli ich nie wykorzystujesz w opisie oferty. Do tego dla POST /sale/offers zdjęcia muszą zostać wcześniej przesłane na serwer Allegro przy pomocy [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST). Proszę zajrzyj do [naszego poradnika](https://developer.allegro.pl/sale/), gdzie opisaliśmy proces wystawienia oferty krok po kroku.

**Comment by net-shops** [comment]
Hej @MaciejFrackowiak,
Usunąłem elementy z images i poprawiłem długość tytułu oferty. Możesz sprawdzić trace id 5cadeae6e14bb48a ? Dlaczego nie zwracacie tych błędów walidacji w odpowiedzi?

**Comment by MaciejFrackowiak** [comment]
Niestety, trace-id oprócz błędu 400 nie zwróci mi szczegółów - cały JSON ma nieprawidłową strukturę, zatem nie dociera on już do naszego serwera. Spróbuj wystawić taką samą ofertę przez stronę WWW, a następnie skorzystaj z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - otrzymasz wówczas poprawny kod.

**Comment by net-shops** [comment]
Ok, dzięki za podpowiedź i szybką reakcję. Znalazłem przyczynę, $.tax był niepoprawny. Dzięki!
