### ISSUE TITLE
EAN update

### ISSUE THREAD

**Issue by tomzara** [allegro/allegro-api#3796]
Czy za pomocą PATCH jest możliwość modyfikacji kodu EAN w aukcji?

**Comment by MaciejFrackowiak** [comment]
EAN podlega pod parametry oferty, czyli musisz przekazać całą sekcję "parameters".

**Comment by makerlabs** [comment]
Problem jest taki, że jak już podasz parametr EAN jako GTIN nie możesz go w ogóle usunąć chociaż w ofercie wyświetlany jest jako opcjonalny w przypadku przekazania pustej wartości string dla parametru GTIN czyli 225693 allegro api zwraca komunikat "Nie podano wartości dla parametru (225693).". W przypadku nie przekazania tego parametru podczas aktualizacji kod GTIN nie jest usuwany. 

Czy jest to zamierzone czy raczej bug od strony API?

**Comment by MaciejFrackowiak** [comment]
@makerlabs Zależy nam, aby oferty posiadały EAN - po jego wartości dochodzi do połączenia oferty z produktem. Jeżeli przedmiot wystawiony w ofercie posiadał EAN to jest mało prawdopodobne, że nagle przestał go posiadać.
