### ISSUE TITLE
Podwójne lineItems ?

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#3797]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, podczas zapytania

GET https://api.allegro.pl/order/checkout-forms/9abc8611-121d-11eb-ba1e-b5916e412112 

pierwszy raz zdarzyło się otrzymać ten sam przedmiot, każdy w innej "lineItems", czy to błąd? Czy coś się zmieniło? Dawniej wszystkie zakupy były grupowane po id i w odpowiedzi otrzymywało się:
`5 x przedmiot X (lineItems - 1),
2 x przedmiot Y (lineItems - 2), `

natomiast tutaj w odp jest:
`1 x przedmiot X (lineItems - 1),
1 x przedmiot X (lineItems - 2)`

Oba przedmioty maja to samo id i zakup pomiędzy nimi wynosił około 30sek (pierwszy - 2020-10-19T15:00:56.903Z, drugi - 2020-10-19T15:00:29.315Z).

**Comment by MaciejFrackowiak** [comment]
W tym przypadku kupujący dokonał dwóch osobnych zakupów w tej samej ofercie - dwa pojedyncze lineItem połączył w jedno zamówienie, ale co do zasady były to dwa oddzielne akty zakupowe, dlatego prezentujemy każdy z osobna w lineItems.
