### ISSUE TITLE
Automat do łączenia ofert z produktami

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3799]
W jaki sposób działa Wasz automat do łączenia ofert z produktami ? Jeśli nie połączę oferty to automat sam to zrobi jeśli znajdzie odpowiedni produkt o takim samym EAN i kategorii ? A co jeśli nie mógł połączyć a np. oferta została wyedytowana i zmieniony został EAN gdzie istnieje taki produkt to automat połączy to czy on łączy tylko jednorazowo i jak mu się nie uda to już trzeba ręcznie to zrobić samemu w panelu Allegro lub poprzez API ?

**Comment by PrzemyslawLukanowski** [comment]
Oferty z produktami łączymy na podstawie parametrów jednoznacznie identyfikujących dany produkt (np. numer EAN). Jeżeli takie dane dodasz dopiero po edycji, automat zadziała, ponieważ proces automatycznego łączenia oferty z produktem przeprowadzamy zarówno po wystawieniu, jak i każdej edycji oferty.

**Comment by pietrach** [comment]
Ale edycji, która miała miejsce za pomocą API to także później automat zadziała ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, w takiej sytuacji automat również powinien zadziałać.

**Comment by pietrach** [comment]
Jak długo trzeba czekać aby automat zadziałał po edycji ?

**Comment by pietrach** [comment]
A co się stanie gdy oferta nie jest połączona i po pewnym czasie pojawi się dla niej produkt. Czy automat bez edycji oferty zadziała i połączy taką ofertę ?

**Comment by PrzemyslawLukanowski** [comment]
Automat nie zadziała, musisz wykonać jakąkolwiek edycję oferty.
