### ISSUE TITLE
Cenniki dostawy

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#38]
czy jest jakis fid przy wystawianu aukcji aby wybrać zdefiniowany cennik dostawy (jak np podpięcie warunków zwrotu) - taki który przy zmianie przez stronę Allegro będzie się aktualizował na aukcjach? Jeśli jest taki fid i jak pobrać jakiś identifikator istniejącego cennika. Jeśli nie to jest poważny problem bo przy fidach które udostepniacie w doNewAuctionExt opcje kolejna sztuka nie sumują się koszty wysyłki bo jak mi pewien Pan z Allegro wytłumaczył dla wpisywanych ręcznie cennikach to nie działa. By koszty wys sumowały się musi byc zdefiniowany cennik

**Comment by PawelTaberski** [comment]
Obecnie w Allegro WebAPI nie ma możliwości przypisania cennika, planujemy wprowadzić taką możliwość w Allegro REST API. Jak tylko będziemy znali termin poinformujemy o tym.
Odnośnie pytania jeśli dodajesz jakąś formę wysyłki musisz uzupełnić 3 fidy np.  w przypadku przesyłki kurierskiej będą to fidy 44; 144 i 244. Oznaczają one odpowiednio cenę za pierwszą sztukę; cenę za kolejną sztukę w paczce i  ilość w paczce. 
Jeśli w dwóch różnych ofertach będzie dodana taka sama forma wysyłki to klient można zamówić te przedmioty jedną paczką. Jeśli ustawisz koszt za kolejną sztukę w paczce również zostanie to wzięte pod uwagę. 
Przykładowo jeśli będziesz miał w obu ofertach przesyłkę kurierską w cenie 10 pln, z ilością sztuk w paczce 2 i cenę za kolejną sztukę 5,50 pln. To jeśli klient kupi przez koszyk w tych dwóch ofertach po 1 sztuce to może wybrać przesyłkę kurierską w cenie 15,5 pln.
Jeśli jednak chcesz korzystać z cenników to możesz wystawić oferty po API, a następnie masowo przypisać do tych ofert dany cennik przez Moje Allegro.

**Comment by marcinja2** [comment]
ok rozumiem, choć odnoszę wrażenie ze nie do końca to tak jest jak Pan przedstawił, jednak bedziemy rozmawiac z Allegro jak będą jasne dowody, niważne. A tak generalnie widze ze duzo wiecej funkcji jest dostepne w REST czy ta tendencja bedzie utrzymywana by z czasem wygasic webapi? bo może sie niepotrzebnie w webapi pacham czy z innych powodów to wynika?

**Comment by PawelTaberski** [comment]
Obecnie bardziej rozwijamy Allegro REST API, ale nie planujemy wygaszania WebAPI i wiele funkcjonalności jest tam dostępnych.
