### ISSUE TITLE
 doGetItemsInfo

### ISSUE THREAD

**Issue by apiallegro** [allegro/allegro-api#380]
Cześć,
czy w restowym api istnieje odpowiednik soapowej funkcji 'doGetItemsInfo'? 
Jeżeli nie, to czy jej zaimplementowanie jest w planach lub w trakcie?

**Comment by TomekKaczmarek** [comment]
Cześć @apiallegro 

Rozumiem, że pytasz o metodą, która pozwoli pobrać publiczne dane o ofertach? A nie tylko oferty danego sprzedawcy?

Na razie dokładnego odpowiednika nie planujemy. Wiele informacji na temat ofert sprawdzisz zasobem [GET /offers/listing](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/).

**Comment by apiallegro** [comment]
Tak, dokładnie o to pytam. 
GET /offers/listing w restowym api posiada mniej informacji.

W każdym razie, dzięki za odpowiedź.
