### ISSUE TITLE
Zwroty

### ISSUE THREAD

**Issue by kasiakry** [allegro/allegro-api#3801]
Cześć,
czy jest/będzie jakiś moduł do obsługi zwrotów? 
[https://allegro.pl/moje-allegro/sprzedaz/zwroty](https://allegro.pl/moje-allegro/sprzedaz/zwroty)
Chodzi o to, żeby dało się pobrać info o wszystkich zwrotach/konkretnym zwrocie po Numerze zwrotu.
K

**Comment by PrzemyslawLukanowski** [comment]
Zasoby poświęcone zwrotom mamy już na naszej liście sugestii dot. rozwoju API. Gdy zdecydujemy się na ich udostępnienie, opublikujemy odpowiedni komunikat.

**Comment by pgasidlo** [comment]
Jakieś postępy nad tą funkcjonalnością?

**Comment by PrzemyslawLukanowski** [comment]
@pgasidlo Wstępnie planujemy udostępnić zasoby do obsługi zwrotów jeszcze w tym kwartale.
