### ISSUE TITLE
Różnice w nazwach metod wysyłki dla zamówienia

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3802]
Witam,

zauważyłem, że transakcje na Allegro z metodą dostawy Allegro Paczkomat 24/7 InPost zaczęły przyjmować dwie różne nazwy dla różnych zamówień (konkretnie Allegro Paczkomat 24/7 InPost i Allegro Paczkomat InPost, raz jest taka nazwa a raz inna), jednak mają nadal ten sam UUID. Jeżeli metody dostawy mają dokładnie ten sam identyfikator, z czego wynikają zmiany w nazwie? A może jednak to inne metody dostawy?

**Comment by PrzemyslawLukanowski** [comment]
Wczoraj zmieniliśmy nazwy metod dostawy po uzgodnieniach z InPost:
- Allegro Paczkomaty 24/7 InPost -> Allegro Paczkomaty InPost,
- Paczkomaty 24/7 InPost - > Paczkomaty InPost,
- Allegro Paczkomaty 24/7 InPost pobranie -> Allegro Paczkomaty InPost pobranie ,
- Paczkomaty 24/7 InPost pobranie - > Paczkomaty InPost pobranie.

Nowe zamówienia powinny już zawierać nową nazwę metody dostawy. Identyfikatory pozostały takie jak wcześniej.

**Comment by hahyes** [comment]
Dziękuję za informację, jednakże taka informacja powinna zostać ogłoszona publicznie, ponieważ ta zmiana może konfudować.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za utrudnienia, weźmiemy Pana spostrzeżenie pod uwagę w przypadku kolejnych, podobnych zmian w nazewnictwie.

**Comment by SebastianOzdoba** [comment]
Podpinam się, nam to osobiście nie przeszkadza, ale Klienci mają popisane różne dodatki działające "po nazwach" i nagle przestało działać
