### ISSUE TITLE
422 ERROR /order/checkout-forms/{id}/fulfillment

### ISSUE THREAD

**Issue by brokieb** [allegro/allegro-api#3803]
Witam, przy próbie zmiany statusu zamówienia  na "PROCESSING" u klienta metodą PUT otrzymuję błąd 422.
```
$ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://api.allegro.pl/order/checkout-forms/07...331/fulfillment');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
    
    curl_setopt($ch, CURLOPT_POSTFIELDS, '{"status": "PROCESSING"}');
    
    $headers = array();
    $headers[] = 'Authorization: Bearer '.$token;
    $headers[] = 'Accept: application/vnd.allegro.public.v1+json';
    $headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($mainResult === false || $resultCode !== 200) {
        return "BŁĄD ".$resultCode;
    } else {
        $answer = json_decode($mainResult);
        return $answer;
```

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać trace-id lub numer zamówienia dla Twojego wywołania? Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich, jednak błąd 422 wskazuje na błędną strukturę żądania. Po otrzymaniu trace-id lub id zamówienia, będę mógł bardziej szczegółowo przeanalizować ten problem.

**Comment by brokieb** [comment]
numer zamówienia 07d05ce1-12d2-11eb-82f7-7b47db937331

**Comment by PrzemyslawLukanowski** [comment]
Zamiast ID zamówienia przekazujesz ID płatności powiązanej z tym zamówieniem. Prawidłowy numer to - 0789b6f2-12d2-11eb-8131-3f1c0b6999f6.
