### ISSUE TITLE
Nieprawidłowy podzbiór HTML

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#3804]
Występuje problem: 
 z zasobem REST API
 ze środowiskiem produkcyjnym

'errors' => 
    array (size=1)
      0 => 
        array (size=5)
          'code' => string 'VALIDATION_ERROR' (length=16)
          'message' => string 'Nieprawidłowy podzbiór HTML' (length=29)
          'details' => string 'Invalid value: Testowy opis' (length=27)
          'path' => string 'description.sections[0].items[0].content' (length=40)
          'userMessage' => string 'Nieprawidłowy podzbiór HTML' (length=29)

przesyłane dane:
'description' => 
    array (size=1)
      'sections' => 
        array (size=2)
          0 => 
            array (size=1)
              'items' => 
                array (size=2)
                  0 => 
                    array (size=2)
                      'type' => string 'TEXT' (length=4)
                      'content' => string 'Testowy opis' (length=12)
                  1 => 
                    array (size=2)
                      'type' => string 'IMAGE' (length=5)
                      'url' => string 'https://a.allegroimg.com/original/116a3d/2db873ef4f35a36325b8cbdc953f' (length=69)

**Comment by MaciejFrackowiak** [comment]
Opis musisz umieścić w znacznikach HTML - ich dostępną listę znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#5-opis-oferty).

**Comment by KJtTGHAK** [comment]
Dziękuję za informację. Temat zamykam
Rozwiązanie:
było:    'type' => string 'TEXT' (length=4)
powinno być:     'type' => string '<p>TEXT</p>' (length=11)
