### ISSUE TITLE
Jak pobrać zdjęcie zakończonej aukcji?

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3805]
Witam, pobieram szczegóły oferty za pomocą get sale/offers/id. Wyciągam z jsona url zdjęcia. Próbując pobrać zdjęcie na dysk komputera dostaję wyjątek NoSuchElementException. Sprawdzam w przeglądarce- zdjęcie ładuje się na stronę.
Czy te zdjęcia są jakoś zabezpieczone przed pobieraniem? Pozdrawiam

**Comment by hahyes** [comment]
> Czy te zdjęcia są jakoś zabezpieczone przed pobieraniem?

Nie są. Musisz coś robić źle.

**Comment by MaciejFrackowiak** [comment]
Dokładnie jak wspomniał @hahyes - zdjęcia bez przeszkód można pobrać i zapisać.

**Comment by speedygopl** [comment]
no ok, ale w pętli też można pobrać np. 100 zdjęć za jednym razem, ze 100 różnych zakończonych ofert, czy jest jakiś limit?

**Comment by speedygopl** [comment]
mam np. url https://d.allegroimg.com/original/06fdb5/ab98d69f4ac4a573ddea7f0c62ed , to z jakim rozszerzeniem jest ten plik? jpg?

**Comment by hahyes** [comment]
> mam np. url https://d.allegroimg.com/original/06fdb5/ab98d69f4ac4a573ddea7f0c62ed , to z jakim rozszerzeniem jest ten plik? jpg?

Plik jest z takim rozszerzeniem, jakie jest zapisane w nagłówku odpowiedzi `Content-Type`. Typ jest zapisany zgodnie ze standardem MIME.
https://pl.wikipedia.org/wiki/Typ_MIME

**Comment by speedygopl** [comment]
dzięki , udało się
