### ISSUE TITLE
Lista adresów IP

### ISSUE THREAD

**Issue by LagonPL** [allegro/allegro-api#3806]
Witam
Mój hostingodawca polecił mi przygotowanie listy adresów IP od API Allegro, gdyż potrzebuje ich do odblokowania komunikacji na firewallu. Gdzie można takowe adresy zdobyć?

**Comment by MaciejFrackowiak** [comment]
Nie udostępniamy publicznie listy adresów IP, którymi posługuje się Allegro.

**Comment by hahyes** [comment]
> Mój hostingodawca polecił mi przygotowanie listy adresów IP od API Allegro, gdyż potrzebuje ich do odblokowania komunikacji na firewallu. Gdzie można takowe adresy zdobyć?

Jeżeli nie jest możliwe zdobycie IP, ja proponuje wykorzystać adresy endpointów REST API Allegro (_api.allegro.pl_ etc.) do reguł komunikacji.

**Comment by LagonPL** [comment]
Próbowałem po prostu zpingować adres api.allegro.pl z cmd i ten adres ip dodać do firewalla, ale nie rozwiązało to mojego problemu.

**Comment by hahyes** [comment]
> Próbowałem po prostu zpingować adres api.allegro.pl z cmd i ten adres ip dodać do firewalla, ale nie rozwiązało to mojego problemu.

Firewall nie ma filtru URL? Słabo.
