### ISSUE TITLE
Złe sortowanie produktów po trafności

### ISSUE THREAD

**Issue by gorskimarcin96** [allegro/allegro-api#3807]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,

Źle są sortowane produkty na api allegro jeśli chodzi o filtr trafność. Gdy wpiszemy w wyszukiwarkę allegro "yerba mate" produkt "zestaw yerba mate green 500g tykwa bombilla 10x50g" jest 4 na liście promowanych.  A w api allegro znajduje się na 19 pozycji.

`function getData($token)
{
    $url = "https://api.allegro.pl/offers/listing?phrase=yerba+mate&sort=-relevance";

    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
		 "Authorization: Bearer $token",
		 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $result = curl_exec($ch);

    return ($result);
}`

![z](https://user-images.githubusercontent.com/32451056/96990899-0152a280-1528-11eb-96a6-9d8503061e43.png)
![z2](https://user-images.githubusercontent.com/32451056/96990906-0283cf80-1528-11eb-9bc3-abf8ac6f27c8.png)

**Comment by PrzemyslawLukanowski** [comment]
Takiej sytuacji nie należy traktować jako błąd. Wyniki mogą się różnić, wyjaśnienie znajdziesz w wątku #2516.

**Comment by gorskimarcin96** [comment]
Dziękuje za przekierowanie do wątku. Może warto opisać cookie monster w dokumentacji?

Pozdrawiam :)
