### ISSUE TITLE
POST /sale/product-proposals => błąd

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3809]
Wysyłam następujący request do zasobu POST /sale/product-proposals 

```
(
    [eans] => Array
        (
            [0] => 5902693219170
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 219809
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => Etno + HP-111 + koala/fix/ch1
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 237194
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => Spokey
                        )

                    [rangeValue] => 
                )

        )

    [name] => Fotel hamakowy Etno + HP-111 + koala/fix/ch1 120kg
    [category] => Array
        (
            [id] => 257757
        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/11b4ca/958f02b54b0eb7464c979717638c
                )

        )
)
```

Otrzymuje błąd:

```
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/product-proposals
                    [userMessage] => 
                )

        )
)
```

Co jest przyczyną tego błędu ?

**Comment by PrzemyslawLukanowski** [comment]
Usuń z requestu puste pola valuesIds oraz rangeValue. Dodatkowo numer EAN przekaż w parametrze 225693 zamiast w osobnym polu "eans".

**Comment by pietrach** [comment]
Dalej to samo:

```
(
    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 219809
                    [values] => Array
                        (
                            [0] => Etno + HP-111 + koala/fix/ch1
                        )

                )

            [1] => Array
                (
                    [id] => 237194
                    [values] => Array
                        (
                            [0] => Spokey
                        )

                )

            [2] => Array
                (
                    [id] => 225693
                    [values] => Array
                        (
                            [0] => 5902693219170
                        )

                )

        )

    [name] => Fotel hamakowy Etno + HP-111 + koala/fix/ch1 120kg
    [category] => Array
        (
            [id] => 257757
        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/112e2d/cd1e9fdf4c22b3d35ee18ef05d08
                )
        )
)
```

**Comment by pietrach** [comment]
Dobra już działa :-)

**Comment by pietrach** [comment]
A to pole eans to jest potrzebne jak przekaże parametr EAN w parametrach ?

**Comment by PrzemyslawLukanowski** [comment]
Nie jest, wystarczy, że przekażesz ean w parametrze.

**Comment by pietrach** [comment]
Aby przypisać produkt do oferty to ten produkt musi być w tej samej kategorii ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, oferta i produkt muszą być w tej samej kategorii.

**Comment by pietrach** [comment]
Jak wyszukuje produkt GET /sale/products i podam jako parametr ean i category.id to wraz pokazuje mi wszystkie produkty zamiast tylko ten z tej jednej kategorii

**Comment by pietrach** [comment]
A czy wystarczy, że produkt znajduje się w tej samej kategorii i ma taki sam EAN ale parametry nie wszystkie mogą się zgadzać z ofertą to i tak mogę go przypisać do oferty ?

**Comment by PrzemyslawLukanowski** [comment]
> Jak wyszukuje produkt GET /sale/products i podam jako parametr ean i category.id to wraz pokazuje mi wszystkie produkty zamiast tylko ten z tej jednej kategorii

Tak, wiemy o tym problemie, odpowiedni zespół został już wcześniej poinformowany. 

> A czy wystarczy, że produkt znajduje się w tej samej kategorii i ma taki sam EAN ale parametry nie wszystkie mogą się zgadzać z ofertą to i tak mogę go przypisać do oferty?

Parametry, które identyfikują produkt, muszą w ofercie być uzupełnione tak samo jak w danych produktu.

**Comment by pietrach** [comment]
A czy można podawać inny symbol niż EAN aby rozpoznawał produkt. Po prostu zwykły symbol produktu ? Jeśli tak to jak ?

**Comment by PrzemyslawLukanowski** [comment]
W zależności od kategorii możesz użyć EAN, ISBN lub ISSN, w [naszym newsie](https://developer.allegro.pl/news/#gtin) znajdziesz więcej szczegółow. Tylko te parametry jednoznacznie identyfikują dany produkt.

**Comment by pietrach** [comment]
OK ale jako EAN muszę podać poprawny kod EAN a nie jakiś tam symbol ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, musi to być poprawny numer EAN produktu.

**Comment by pietrach** [comment]
Mam następujące EANy ( to tylko przykładowe bo jest ich dużo więcej):

4025122919548
4025122919555
4025122919562
4025122919609

Przy próbie dodania produktu otrzymuje błąd:

```
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ProductDuplicate
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji.
                )

        )
)
```

Wszystko jest OK tylko zanim dodam wyszukuje produkty po tych właśnie EANach (GET /sale/products) i dla wszystkich otrzymuje brak czyli pusta tablica products. Według mnie to błąd. Powinny się pojawić i wtedy nie dokonywał bym próby ich dodania.

**Comment by pietrach** [comment]
Z tego co widzę to podczas dodawania produktu POST /sale/product-proposals to nie sprawdzacie duplikatu po EAN tylko po parametrach wymaganych dla produktu ? 

Czy kod producenta powinien być kodem konkretnego modelu czy ogólnym kodem produktu. Przykład:

Mamy produkt A w kolorze 1, 2, 3.
Symbol główny produktu to A, Symbole dla poszczególnych modeli (kolorów) to A-1, A-2, A-3
Czy jak dodam 3 oferty z każdym z tych kolorów to w kodzie producenta powinienem zawrzeć "A" (kod główny) czy dla każdej oferty kod modelu czyli A-1, A-2, A-3 ?

Bo teraz jest tak, że zawieram główny kod produktu i pewnie przez to jest ten problem. Że jak próbuje dodać nowy kolor to idzie główny symbol a on już jest w innym produkcie. Dodatkowo zgadza się producent itp. i mamy duplikat. A jakbym wstawiał kod poszczególnych modeli to pewnie problemu by nie było ?

Czy mogę dodać wiele razy ten sam produkt tylko, że w innych kategoriach ?

**Comment by PrzemyslawLukanowski** [comment]
> Wszystko jest OK tylko zanim dodam wyszukuje produkty po tych właśnie EANach (GET /sale/products) i dla wszystkich otrzymuje brak czyli pusta tablica products. Według mnie to błąd. Powinny się pojawić i wtedy nie dokonywał bym próby ich dodania.

Przekazałem ten problem dalej, do odpowiedniego zespołu.

> Czy kod producenta powinien być kodem konkretnego modelu czy ogólnym kodem produktu. Przykład:

Powinien być kodem konkretnego modelu, to powinno rozwiązać Twój problem.

> Czy mogę dodać wiele razy ten sam produkt tylko, że w innych kategoriach ?

Powinieneś dodać ten sam produkt tylko jeden raz, w odpowiedniej kategorii.

**Comment by pietrach** [comment]
> Powinieneś dodać ten sam produkt tylko jeden raz, w odpowiedniej kategorii.

Czyli podsumowując dążycie do tego aby nie wystawiać tego samego produktu / oferty w wielu kategoriach ?

**Comment by pietrach** [comment]
Są 2 metody **POST /sale/product-offers**  oraz  **PATCH /sale/product-offers/{offer-id}**. Piszecie, że można nimi od razu utworzyć produkt albo przypisać istniejący. A co jeśli produkt istnieje a przekażemy w nich strukturę produktu bez id. Czy te metody są na tyle "sprytne", że po odpowiednich parametrach znajdą sobie ten produkt i przypiszą do oferty bez tworzenia nowego ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, w takiej sytuacji odnajdziemy produkt w naszej bazie i w polu product.publication.status zwrócimy wartość LISTED ([tutaj](https://developer.allegro.pl/news/#product-status) znajdziesz więcej informacji na temat tego pola).

**Comment by pietrach** [comment]
A co się stanie jak będę próbował przypisać produkt z innej kategorii niż oferta ? Czy oferta się wystawi normalnie a produkt wtedy się nie przypisze czy będzie jakiś błąd podczas wywołania żądania ?

**Comment by PrzemyslawLukanowski** [comment]
Otrzymasz wtedy błąd "Offer category doesn't match product category".

**Comment by pietrach** [comment]
A mogę przez te dwie metody  **POST /sale/product-offers** oraz **PATCH /sale/product-offers/{offer-id}** wystawiać normalnie same oferty bez produktów ? Na zasadzie tych dotychczasowych metod  **POST /sale/offers** oraz **PUT/sale/offers/{offerId}**

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą POST /sale/product-offers musisz zawsze przekazać strukturę produktu, natomiast PATCH /sale/product-offers/{offer-id}  służy do edycji - i tak, możesz w ten sposób edytować także te oferty, które nie są powiązane z produktami.

**Comment by pietrach** [comment]
A co się stanie jak przekaże te same zdjęcia w **product.images** oraz w samym ofertowym **images**. Czy metody są na tyle sprytne że do oferty weźmie mi zdjęcia tylko z ofertowego **images** ?

**Comment by pietrach** [comment]
Piszesz, że:

> Za pomocą POST /sale/product-offers musisz zawsze przekazać strukturę produktu

A jeśli bym przekazał pustą strukturę product, w której nic nie ma to nie przejdzie takie coś ?

**Comment by PrzemyslawLukanowski** [comment]
> A co się stanie jak przekaże te same zdjęcia w product.images oraz w samym ofertowym images. Czy metody są na tyle sprytne że do oferty weźmie mi zdjęcia tylko z ofertowego images ?

W takiej sytuacji nasz mechanizm wykryje duplikaty i je pominie, używając adresu oryginalnego zdjęcia.

> A jeśli bym przekazał pustą strukturę product, w której nic nie ma to nie przejdzie takie coś ?

W tym przypadku otrzymasz błąd - status 422.

**Comment by pietrach** [comment]
Co tu jest źle => trace id = 139a34a6854b6abc. Błąd jest następujący

```
{"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"images[0]","userMessage":"u017bu0105danie zawiera bu0142u0119dne dane. Skontaktuj siu0119 z autorem aplikacji."}],"offerId":"9855021839","offerTitle":"Fotel hamakowy dla dzieci JOKI KOKON 70x150cm 80kg","offerParams":{"id":"9855021839","name":"Fotel hamakowy dla dzieci JOKI KOKON 70x150cm 80kg","category":{"id":"82257"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["2.7"],"rangeValue":null},{"id":"225693","values":["4025122935050"]}],"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/117372/5059daa0436da88d6c5cf1f4d5fd"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/110406/c3c1e0a64b9a8e119b47efea79f3"},{"type":"TEXT","content":"
Fotel hamakowy dla dzieci JOKI z zestawem montau017cowym, La Siesta, niebieski (33)

 

Wymiary materiau0142u [cm]: 70x150

Wysokou015bu0107 cau0142kowita [cm] /od dou0142u fotela do uchwytu mocuju0105cego/: 200

Dopuszczalne obciu0105u017cenie [kg]: 80

Waga [kg]: 2,7

Symbole: Czysta, nie pochodzu0105ca z recyklingu baweu0142na, Wypeu0142nione wnu0119trze, Prau0107 w pralce - 30u00b0C, tryb delikatny, Produkty zalecane przez BAG

Materiau0142y: Baweu0142na

Opakowanie [cm]: 60 x 40 x 25

wiek: 3-10
"}]},{"items":[{"type":"TEXT","content":"

Z MYu015aLu0104 O DZIECIACH.

Hamaki to nie tylko zabawa, to taku017ce wau017cny czynnik wpu0142ywaju0105cy na prawidu0142owy rozwu00f3j fizyczny i psychiczny dziecka. Od dawna hamaki wykorzystywane su0105 w wielu terapiach lekarskich z doskonau0142ym rezultatem. Nadzorowane przez dorosu0142ych przewracanie i obracanie siu0119 wewnu0105trz hamaka stymuluje zmysu0142 balansowania i przeciwdziau0142a problemom percepcyjnym.

Wysoka Jakou015bu0107 Baweu0142ny

Do produkcji hamaku00f3w La Siesta uu017cywamy wyu0142u0105cznie prawdziwej, nie przetwarzanej baweu0142ny, z du0142ugimi wu0142u00f3knami. Nasza baweu0142na nie posiada meszku, nie rwie siu0119 i jest bardzo wytrzymau0142a. Fotel 100% baweu0142ny, poduszka 100% poliester. u015arednica kou0142a to 70 cm. Informacje dotyczu0105ce uu017cytkowania

W celu zamocowania fotela wiszu0105cego JOKI wymagana jest wysokou015bu0107 200 cm. Jeu015bli punkt zaczepienia znajduje siu0119 jeszcze wyu017cej, to fotel JOKI mou017cna przedu0142uu017cyu0107 za pomocu0105 liny. W celu zawieszenia JOKI potrzebuju0105 Pau0144stwo tylko jednego punktu zaczepienia. Mou017ce on znajdowau0107 siu0119 na suficie albo belce. JOKI nie zabiera wiele miejsca i idealnie dopasowuje siu0119 taku017ce do mau0142ych pokoi dzieciu0119cych. Fotel wiszu0105cy JOKI mou017ce byu0107 w mgnieniu oka odwieszony i zabrany z pomieszczenia. Po wyju0119ciu poduszki, JOKI mou017cna prau0107 w pralce w temp. 30u00b0C, wybieraju0105c program do tkanin delikatnych. W celu ochrony produktu prosimy o suszenie na wolnym powietrzu i nieuu017cywanie suszarki kondensacyjnej.

Gwarancja Bezpieczeu0144stwa

Wszystkie produkty La Siesta zostau0142y przetestowane i zatwierdzone przez Tu00dcV Rheinland (uznanu0105 niemiecku0105 instytucju0119 kontroluju0105cu0105 bezpieczeu0144stwo i jakou015bu0107 produktu00f3w).
"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/116fe9/918a1683424d8fa2d20372f991af"},{"type":"IMAGE","url":"https://a.allegroimg.com/original/11f25c/4a2fc3f44da4ab800a670175eb20"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11c41d/337eea564c2b94c9edc207d4d968"}]}]},"images":[{"url":"https://a.allegroimg.com/original/110406/c3c1e0a64b9a8e119b47efea79f3"},{"url":"https://a.allegroimg.com/original/117372/5059daa0436da88d6c5cf1f4d5fd"},{"url":"https://a.allegroimg.com/original/116fe9/918a1683424d8fa2d20372f991af"},{"url":"https://a.allegroimg.com/original/11f25c/4a2fc3f44da4ab800a670175eb20"},{"url":"https://a.allegroimg.com/original/11c41d/337eea564c2b94c9edc207d4d968"}],"product":{"name":"Fotel hamakowy dla dzieci JOKI KOKON 70x150cm 80kg","category":{"id":"82257"},"parameters":[{"id":"237214","valuesIds":[],"values":["Joki"],"rangeValue":null},{"id":"237194","valuesIds":[],"values":["LaSiesta"],"rangeValue":null},{"id":"9400","valuesIds":["9400_1"],"values":[],"rangeValue":null},{"id":"9401","valuesIds":[],"values":["200"],"rangeValue":null},{"id":"9403","valuesIds":[],"values":["70"],"rangeValue":null},{"id":"9405","valuesIds":[],"values":["80"],"rangeValue":null},{"id":"219809","valuesIds":[],"values":["JCD70-33"],"rangeValue":null},{"id":"225693","values":["4025122935050"]}],"images":[{"url":"https://a.allegroimg.com/original/110406/c3c1e0a64b9a8e119b47efea79f3"}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":"611.10","currency":"PLN"}},"stock":{"available":"2","unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE"},"delivery":{"shippingRates":{"id":"f6bec455-1503-4c4b-a922-6b644b765e84"},"handlingTime":"PT24H"},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"48c819e0-43d2-4290-9b5a-dfb68a5c77de"},"returnPolicy":{"id":"fc745739-c269-44fa-8f36-a4423ffe0ae7"}},"promotion":{"emphasized":false},"external":{"id":"5676"},"tax":{"percentage":"23.00"},"location":{"countryCode":"PL","province":"MAZOWIECKIE","city":"Siedlce","postCode":"08-110"}}}
```

**Comment by pietrach** [comment]
Dobra chyba już wiem. Struktura images różni się od tej przekazywanej poprzez te podstawowe metody do wystawiania/edycji oferty. Szkoda że nie jest to ujednolicone

**Comment by PrzemyslawLukanowski** [comment]
Korzystasz też z metody PATCH, która służy do edytowania konkretnych pól w ofercie, a w Twoim przypadku wysyłasz tam całą struktrę oferty, dodatkowo z danymi produktu. [Tutaj](https://developer.allegro.pl/product_offers/#edytowanie-p%c3%b3l-oferty) znajdziesz więcej szczegółów na temat działania tego zasobu. 
Jeżeli chcesz przypisać produkt do istniejącej oferty, powinieneś odpowiednio przekazać product.id oraz parametry produktu z sekcji parameters.

**Comment by PrzemyslawLukanowski** [comment]
> Mam następujące EANy ( to tylko przykładowe bo jest ich dużo więcej):
> 
> 4025122919548
> 4025122919555
> 4025122919562
> 4025122919609
> 
> Przy próbie dodania produktu otrzymuje błąd:

Naprawiliśmy już ten błąd. GET /sale/products zwraca produkty powiązane z powyższymi numerami ean.

**Comment by pietrach** [comment]
**GET /sale/offers** => dlaczego tutaj nie ma struktury product. Czy jest jakaś metoda która pozwoli mi pobrać listę iluś tam ofert wraz z id produktu ? Bo odpytywanie o pojedyncze oferty to trochę słabo.

**Comment by PrzemyslawLukanowski** [comment]
Możesz jedynie użyć filtru product.id.empty=false, dzięki czemu w wynikach zobaczysz wszystkie oferty, które mają przypisany produkt. Następnie możesz pobrać szczegóły danej oferty za pomocą GET /sale/offers/{id}.

**Comment by pietrach** [comment]
Próbuje wyszukać produkt po EAN 0727670920840 oraz kategorii 147862. Nie zwraca mi żadnego produktu. Przy próbie stworzenia produktu wyrzuca błąd że już taki produkt istnieje:

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ProductDuplicate
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji.
                )

        )

    [params] => Array
        (
            [parameters] => Array
                (
                    [0] => Array
                        (
                            [id] => 224017
                            [values] => Array
                                (
                                    [0] => Lightest Hammock-01
                                )

                        )

                    [1] => Array
                        (
                            [id] => 237206
                            [values] => Array
                                (
                                    [0] => Jednoosobowy
                                )

                        )

                    [2] => Array
                        (
                            [id] => 237194
                            [values] => Array
                                (
                                    [0] => Ticket To The Moon
                                )

                        )

                    [3] => Array
                        (
                            [id] => 211738
                            [valuesIds] => Array
                                (
                                    [0] => 211738_251190
                                )

                        )

                    [4] => Array
                        (
                            [id] => 209802
                            [values] => Array
                                (
                                    [0] => 150
                                )

                        )

                    [5] => Array
                        (
                            [id] => 205826
                            [valuesIds] => Array
                                (
                                    [0] => 205826_225102
                                )

                        )

                    [6] => Array
                        (
                            [id] => 211754
                            [values] => Array
                                (
                                    [0] => 320
                                )

                        )

                    [7] => Array
                        (
                            [id] => 225693
                            [values] => Array
                                (
                                    [0] => 0727670920840
                                )

                        )

                )

            [name] => Hamak jednoosobowy Lightest Hammock 150kg
            [category] => Array
                (
                    [id] => 147862
                )

            [images] => Array
                (
                    [0] => Array
                        (
                            [url] => https://a.allegroimg.com/original/11c9a3/38f1982c4c59bd9a9160905dacec
                        )

                )

        )
    [location] => https://api.allegro.pl/sale/product-proposals/577f2e95-0c7c-4f78-bd8b-3e65eab65aaa
)
```

**Comment by PrzemyslawLukanowski** [comment]
Zwracamy ten produkt, jeśli jako EAN przekażesz 727670920840 (bez zera na początku). ID produktu to 577f2e95-0c7c-4f78-bd8b-3e65eab65aaa.

**Comment by pietrach** [comment]
Ale w EAN w produkcie jest 0 na początku więc powinno być z 0 OK. Według mnie źle działa ta wyszukiwarka.

**Comment by PrzemyslawLukanowski** [comment]
Ten produkt również jest oznaczony numerem EAN bez zera na początku - taki właśnie mamy zapisany w naszej bazie.

**Comment by pietrach** [comment]
Czy możecie zmienić EAN tego produktu aby było 0 na początku. EAN powinien być 13 cyfrowy.

**Comment by PrzemyslawLukanowski** [comment]
Tak, przekazałem już prośbę do odpowiedniego działu.

**Comment by PrzemyslawLukanowski** [comment]
Zmieniliśmy wspomiany numer EAN.

**Comment by pietrach** [comment]
A komu można przekazywać te zmiany ? Bo wysłałem mnóstwo zmian w produktach w przeciągu prawie 2 tyg i praktycznie zerowy odzew. Wysyłałem na mail allegro.kontakt@allegro.pl

**Comment by PrzemyslawLukanowski** [comment]
Możesz to zrobić przez opcję "zgłoś błąd w produkcie" na stronie internetowej. Poprawki zostaną wprowadzone, prosimy jednak o cierpliwość.

**Comment by pietrach** [comment]
Rozumiem skoro napisałem na ten mail to ktoś się tym zajmie ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, wiadomość powinna trafić do odpowieniego działu.

**Comment by pietrach** [comment]
Kolejny przypadek. Próbuje wyszukać po EAN produkt 4030454006637. Nie znajduje nic. Natomiast przy próbie zapisu dostaje błąd, że produkt już istnieje => ddc29d6e-4912-41dd-81a7-959aa0969751

**Comment by pietrach** [comment]
To samo ten produkt 3076d9a7-a4e6-47ef-8271-71cbf2e2187a. Po EAN 4030454000772 nie wyszukuje. Takich przypadków jest dużo więcej.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz przesłać pozostałe produkty, dla których zauważyłeś ten problem? Przekażę wtedy listę do odpowiedniego zespołu.

**Comment by pietrach** [comment]
Narazie to zostawmy. Bardziej pilniejszy jest zmiana danych w produktach, które wysyłałem w wielu mailach. Numer sprawy to:

11693965

**Comment by PrzemyslawLukanowski** [comment]
Prosimy o cierpliwość, odpowiedni zespół przyjrzy się zgłoszeniu.
