### ISSUE TITLE
tworzenie szkicu na podstawie zakończonej aukcji

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3810]
witam,
pobieram szczegóły oferty zakończonej za pomocą get sale/offers/id. Otrzymuję jsona. Czy mogę na podstawie tego jsona utworzyć szkic oferty do późniejszego wystawienia? Czy jest jakaś instrukcja jak to zrobić? Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz to zrobić. Wystarczy, że z json usuniesz poniższe pola i pozostałą strukturę prześlesz przez POST /sale/offers:

- id
- validatedAt
- createdAt
- updatedAt
- publication

**Comment by speedygopl** [comment]
dzięki, będę próbował

**Comment by speedygopl** [comment]
a jeszcze pytanko , czy przy tworzeniu szkicu ,zdjęcie musi być na serwerach allegro  ? czy da radę z dysku swojego komputera je załadować?

**Comment by PrzemyslawLukanowski** [comment]
Musisz wcześniej wgrać zdjęcia na nasz serwer za pomocą POST /sale/images. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#3-zdj%c4%99cia).
