### ISSUE TITLE
How to replace WebAPI methods after disabling doGetItemsInfo

### ISSUE THREAD

**Issue by koticik** [allegro/allegro-api#3811]
In the month of [March](https://github.com/allegro/allegro-api/issues/2994), I asked for advice on how to get complete information about a specific offer from a specific seller.
Then I was told that the Rest API method
https://api.allegro.pl/sale/offers/
works only for its suggestions and was advised to use the WebAPI method
 doGetItemsInfo or doShowItemInfoExt.
Now these methods have been disabled and my work has stopped.
Tell me if there is some mechanism that replaces the work of the doGetItemsInfo or doShowItemInfoExt methods when using the Rest API
I am interested in the opportunity to get detailed information about the offer, the one that any buyer sees who simply clicked on the product page in Allegro

**Comment by MaciejFrackowiak** [comment]
No, we do not have a similar mechanism in REST API and we will not add it in future according to [our previous announcement](https://github.com/allegro/allegro-api/issues/3718).

**Comment by koticik** [comment]
How to be?

You have written that you do not add such information due to restrictions on confidential data, but I do not want to get access to confidential data, I need information that can be seen on the site even without registration to any visitor.
Photos, product descriptions, delivery conditions, condition, nothing else is required, what is confidential if it's all on the page in the public domain?

**Comment by MaciejFrackowiak** [comment]
Sorry, but this kind of data also will not be available in REST API.

**Comment by koticik** [comment]
Very bad. In this version of the API, the functionality for buyers is greatly reduced.
We'll have to look for other options to get seemingly public information.

**Comment by MaciejFrackowiak** [comment]
Yes, REST API is developed mainly with resources for the sellers.
