### ISSUE TITLE
Logowanie - REST API

### ISSUE THREAD

**Issue by raftom9885** [allegro/allegro-api#3812]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

1bbc279376b15eb7

Witam

Ostatnimi czasy (od czwartku) mam bardzo duże problemy z zalogowaniem się do REST API.
Przy próbie wejścia na stronę:
https://allegro.pl/skojarz-aplikacje?code=xxxxxxx
dostaję zwrotkę (kod błędu 1bbc279376b15eb7)
![image_2020_10_23T06_13_09_948Z](https://user-images.githubusercontent.com/39498051/97113361-22fb8780-16ea-11eb-8ca1-546532a28474.png)
po odświeżeniu strony wszystko wraca do normy i działa poprawnie. Domyślnie w mojej aplikacji logowanie jednak odbywa się za pomocą skryptu, a przez ww błąd uniemożliwia normalne korzystanie z programu.

Nie mam 100% pewności z którego konta został wygenerowany ww. błąd jednak musi to być jedno z poniższych:
czesci-kunow
czesci-mystkow
CZESCI-MALINIE
opony-mystkow-pl

**Comment by PrzemyslawLukanowski** [comment]
Czy ten problem pojawia się od razu po wejściu na stronę czy po kliknięciu przycisku "Dalej"?

**Comment by raftom9885** [comment]
Witam

Od razu po wejściu na stronę https://allegro.pl/skojarz-aplikacje?code=xxxxxxx
W dniu dzisiejszym zamiast tego błędu dostaję pustą stronę - nic na niej nie ma

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję jeszcze ten temat, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Wygląda to na, że wystąpił problem z Twoją aplikacją. Po naszej stronie widzimy momentami znacznie wzmożony ruch na https://allegro.pl/skojarz-aplikacje?code=xxxxxxx (~5k razy na 3h), przez co nakładaliśmy chwilową blokadę. Wystarczy, że user tylko raz zautoryzuje aplikację, w następnych krokach otrzyma access oraz refresh token - jego można użyć, aby przedłużyć ważność tokena o kolejne 12h i otrzymać kolejny refresh token.
