### ISSUE TITLE
Pobieranie ofert z różnych "klientów" / "środowisk"

### ISSUE THREAD

**Issue by ZenonZ** [allegro/allegro-api#3813]
Witam,

zauważyłem dziwne zachowanie: 
wygenerowałem token dla nowo-tworzonej aplikacji (w java), przy użyciu tego tokena chciałem sprawdzić czy poprawnie działa więc "strzeliłem" Postmanem by zobaczyć np wszystkie zakończone oferty i np 1 wybraną - działa bez żadnych problemów (np trace-id: abda73b35a80250c), skopiowałem "wygenerowany curl" i uruchomiłem na serwerku docelowym (Linux) i tu ciekawostka bo odpowiedź to: 403 Forbidden.

Uruchomiłem kod javowy - ten sam IP co Postman (poprzez HttpURLConnection / HttpsURLConnection) i też nie działa pomimo użycia identycznego tokena / nagłówków jak w Postman'ie (np trace-id: 726a8c63787fde65).

Dlaczego tak dziwne zachowanie ? 

pozdr
ZZ

**Comment by MaciejFrackowiak** [comment]
Spojrzałem na podane przez Ciebie trace-id - oto wnioski:

1) abda73b35a80250c - w tym przypadku pobrałeś ofertę, ponieważ byłeś zautoryzowany jako sprzedawca danej oferty;
2) 726a8c63787fde65 - tu chciałeś pobrać ofertę 984xxxx013, która nie należała do użytkownika, dla którego  byłeś zautoryzowany w danej chwili - oferta należy do tego samego konta co w punkcie 1, natomiast operację wykonywałeś z konta 413xxx68.

Efektem końcowym było 403 - nie można pobrać ofert, które nie należą do danego, zautoryzowanego użytkownika.

**Comment by ZenonZ** [comment]
Dziękuję, za szybką odpowiedź, zweryfikuję to jeszcze.
