### ISSUE TITLE
Wznowienie ofert

### ISSUE THREAD

**Issue by marcin3883** [allegro/allegro-api#3815]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Od wczoraj występuje problem ze wznowieniem aukcji zarówno poprzez API jak i www.
Wyskakuje informacja o wznowieniu oferty, po czym oferta nie jest wznawiana.
Problem występuje również podczas dodawania ilości produktów do aukcji - nie jest ona brana pod uwagę i oferta jest zakańczana z powodu sprzedaży wszystkich sztuk (po czym nie można wznowić aukcji).

Przykładowe numery ofert w którym występuje problem:
9804156719
9798709781
9820983358
9835683533
9798695737

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, dla części ofert zaobserwowaliśmy opisany przez Ciebie problem. Sprawa jest już weryfikowana przez właściwy zespół.

**Comment by mkaluszka** [comment]
Mam to samo - problem jest globalny, czy też podpiąć swoje numery?

**Comment by MaciejFrackowiak** [comment]
@mkaluszka Podchodzimy do sprawy globalnie - nie musisz podawać nam swoich numerów ofert. Działamy.

**Comment by mojosoft** [comment]
Problem jest od 2 dni, zmieniają się tylko oferty których to dotyczy.

**Comment by MaciejFrackowiak** [comment]
Tak, jest określona grupa ofert, która została dotknięta problemem. W momencie potwierdzenia rozwiązania problemu zamieszczę tu info.

**Comment by MaciejFrackowiak** [comment]
Problem został rozwiązany, przepraszamy za utrudnienia.
