### ISSUE TITLE
ilość towarów, dostepnych dla zamowień

### ISSUE THREAD

**Issue by Olyamodul** [allegro/allegro-api#3817]
Cześć! Jesteśmy sprzedawcą. Cheliśmy mieć mozliwość przekazania do kupujących wiadomości o ilości towarów, dostepnych dla zamowień. Na dzień dzisiejszy taka informacja jest wkazana rączne w gabinecze Allegro przez użytkowników. Jak możemy taką ilość przenieść z systemu księgowego? Niestety nie znalezliśmy taką informacjj w dokumentacji API

**Comment by MaciejFrackowiak** [comment]
Niestety, nie dajemy takiej możliwości. Liczbę dostępnych sztuk określa dany sprzedający w każdej ze swoich ofert osobno, w polu "stock.available".

**Comment by Olyamodul** [comment]
Ręczne? Nie możemy przekazać te dane automatyczne, na przykład wg kodu kreskowego?

**Comment by MaciejFrackowiak** [comment]
W REST API udostępniamy zasoby [PUT /sale/offers](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) oraz [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT) do zmiany ilości sztuk w ofercie. Natomiast jak zaimplementujesz swoje własne rozwiązanie przekazujące ilości z programu księgowego to już pozostaje wyłącznie w Twojej gestii.
