### ISSUE TITLE
GET/offers/listing - niedeterministyczne wyniki

### ISSUE THREAD

**Issue by agasior093** [allegro/allegro-api#3818]
Wykorzystuje REST API Allegro by śledzić interesujące mnie aukcje, których jest dośc sporo, +/- 300. W tym celu co kilka sekund odpytuje `GET/offers/listing` z interesującymi mnie kryteriami. Docelowo będzie to 7000-8000 requestów co minutę. 
Podczas testów różnych rozwiązań i porównania ich wydajności wewnątrz mojej aplikacji, doszedłem do niepokojącego odkrycia, mianowicie - API zwraca niedeterminystyczne wyniki. 

Obecny setup wygląda tak - mam dwie identyczne aplikację, które co 3 sekudny wykonują 30 tych samych zapytań do wspomnianego API. W celach diagnostycznych, loguje obecnie każdą odpowiedź, i mogę na tej podstawie stwierdzić, że faktycznie co 3 sekundy wychodzi ode mnie zapytanie HTTP i dostaję poprawną odpowiedź. Z zapytań które wykonuje wraca średnio 30-40 ofert, więc po przeanalizowaniu logów widzę wyraźnie, że mimo iż obydwie aplikacje wykonują dokładnie to samo zapytanie, to jedna z nich otrzymała nową ofertę kilka minut wcześniej niż druga aplikacja. 

Przykład z dzisiaj:
https://api.allegro.pl/offers/listing?seller.id=38122453&phrase=ekspres&category.id=42540aec-367a-4e5e-b411-17c09b08e41f&include=-all&include=items&include=searchMeta

O 14:38:19 aplikacja pierwsza znalazła ofertę o ID 9855030350, a druga instancja ten aplikacji, znalazła tę samą ofertę dopiero o 14:45:34. Wykluczyłem wszelkie problemy związane ze swoją aplikacją, po logowaniu odpowiedzi z API Allegro, widzę że obydwie aplikacje co 3 sekundy wykonywały zapytania i otrzymwały poprawne odpowiedzi, z jakiegoś powodu jednak jedna aplikacja orzymała tę ofertę o ponad 5 minut wcześniej. 

Co może być przyczyną? Zbyt ogólna kategoria, czyli elektronika? Szczerze mówiąc, brakuje mi już pomysłów. W razie czego mogę wyciągnąć logi z jednej i drugiej aplikacji, aczkolwiek jedyna różnica w odpowiedziach z API to brak wspomnianej oferty w jednej z aplikacji przez kilka minut.

**Comment by SebastianOzdoba** [comment]
@agasior093 moim zdaniem to normalne, po prostu dane są propagowane z różną szybkością w API i jedna apka strzela powiedzmy do API1 a druga do API2, gdzie w API2 tego jeszce nie ma

**Comment by MaciejFrackowiak** [comment]
Jest dokładnie jak napisał @SebastianOzdoba - Allegro oparte jest wielu serwerach i dane muszą się na kolejne z nich rozpropagować. Część z nich zwróci informacje szybciej, część później. Oferta z Twojego przykładu została wystawiona chwilę przed wysłanym requestem - gwarantujemy widoczność oferty w serwisie w ciągu 60 minut od jej wystawienia.

**Comment by agasior093** [comment]
Ok, rozumiem. Pytanie więc, czy istnieje jakiś sposób by zwiększyć prawdopodobieństwo, ze znajdę ofertę szybciej? Jak np. bardziej dokładne kryteria wyszukiwania?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiego gwaranta, również kryteria wyszukiwania na to nie wpłyną.

**Comment by agasior093** [comment]
Ok, dziękuje za informacje.
