### ISSUE TITLE
Moja saldo i wypłata środków w REST Api`

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#3819]
W jaki sposób mogę uzyskać informację jakie mam saldo z wpłat? Druga sprawa w jaki sposób mogę wypłacić te środku za pomocą REST? Nie znalazłem w dokumentacji zasobów, które to umożliwiają. WebAPI miało odpowiednie zasoby.

**Comment by MaciejFrackowiak** [comment]
Saldo po każdej operacji sprawdzisz przy pomocy [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory). Zasobów do obsługi wypłat z Allegro Finanse nie udostępnimy w REST API - informowaliśmy o tym w poście https://github.com/allegro/allegro-api/issues/3492. Aktualne ustawienia danych do wypłat możesz sprawdzić w [Moim Allegro](https://allegro.pl/myaccount/newpayments_payout.php?source=system). Jeśli chcesz otrzymywać codziennie wypłaty, wystarczy, że ustawisz automatyczny sposób wypłat.

**Comment by juhacz** [comment]
Dziękuje za odpowiedź odnośnie salda. Jeśli chodzi o zlecenia wypłaty, uważam, że jest to przydatna rzecz. Kiedyś miałem faktycznie ustawioną automatycznie wypłatę, teraz nie mogę tego włączyć, robię to ręcznie, odkąd Allegro zaczęło wymagać zwrotu środków przez PayU aby otrzymać zwrot prowizji od sprzedaży.
Sprzedaję kilka rzeczy w tyg. dosyć drogich, minimum kilkaset złotych, do tej pory wypłacałem je codziennie za pomocą Api, po kliknięciu jednego przycisku na pewnym urządzeniu, kiedy dostaję informację o tym, że ktoś odstąpił od umowy, przestaję wypłacać pieniądze i zaczynam "zbierać" na koncie PayU, aby móc je zwrócić. Czekam na zwrot od kupującego, zwracam pieniądze przez PayU i jednym kliknięciem wypłacałem resztę na swoje konto. Teraz mi tego brakuje, trzeba się logować za każdym razem i robić to ręcznie. Dodajcie tę możliwość do sugestii, byłoby miło.

**Comment by MaciejFrackowiak** [comment]
Dobrze, zgodnie z prośbą przekazuję sprawę jako sugestię dot. dalszego rozwoju REST API.
