### ISSUE TITLE
Ilość sprzedanych sztuk w metodzie doGetBidItem2

### ISSUE THREAD

**Issue by dxsoftware** [allegro/allegro-api#382]
Przy pobieraniu informacji z metody doGetBidItem2 zauważyłem niezgodność.
Klient kupił produkt jednego dnia i nie dokończył wypełniać formularz opcji dostawy.
Po kilku dniach zamiast dokończyć poprzedni zakup kupił ponownie i wszystko wypełnił poprawnie.
Więc mam sprzedaż oferty od tego klienta wygląda następująco:
Data1: 1 sztuka
Data2: 1 sztuka

Metoda doGetBidItem2 zwraca mi że w Data2 zostały sprzedane 2 sztuki.

Proszę o informację czy jest to błąd czy celowe rozwiązanie, jeśli celowe to w mojej ocenie jest złe, ponieważ jest to wprowadzanie w błąd. Czy zostanie to rozwiązane?

**Comment by TomekKaczmarek** [comment]
@dxsoftware metoda działa poprawnie - klient dokonał dwóch aktów zakupowych. Mamy lepsze metody do monitorowania sprzedaży - zapoznaj się z [naszym poradnikiem](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421).

W ciągu najbliższych kilku tygodni opublikujemy też zasoby na REST API, które pozwolą Ci monitorować sprzedaż.
