### ISSUE TITLE
Jak poznać swój numer Id (nie login)

### ISSUE THREAD

**Issue by jaceklodz** [allegro/allegro-api#3820]
Cześć
nowe konto, loguję się ale za chiny nie wiem jakie mam id żeby na spokojnie podziałać w API.
Kiedyś w url był widoczny, teraz tylko nazwy konto.

Pomocy

**Comment by MaciejFrackowiak** [comment]
Swoje ID poznasz korzystając z zasobu [GET /me](https://developer.allegro.pl/documentation/#operation/meGET).
