### ISSUE TITLE
Śledzenie statusu przesyłki dodanej poprzez zasób /order/checkout-forms/{id}/shipments

### ISSUE THREAD

**Issue by AdrianPiechota** [allegro/allegro-api#3821]
Czy jest możliwe śledzenie statusu przesyłki dodanje przez zasób `order/checkout-forms/{id}/shipments`? W formie jak na screenie?

W Allegro:
![obraz](https://user-images.githubusercontent.com/6989873/97315361-f02bcd80-1868-11eb-8d1e-3ab6dba14b7a.png)

W InPost:
![obraz](https://user-images.githubusercontent.com/6989873/97315406-fa4dcc00-1868-11eb-82de-338791b174b4.png)

W tej chwili dodajemy listy przewozowe, ale dla nich dostępny jest tylko link do śledzenie.

**Comment by AureliuszBrussy** [comment]
W API Allegro nie udostępniamy możliwości śledzenia statusu przesyłek. 

Możliwość ta jest dostępna dla kupującego bezpośrednio w naszym serwisie, jednak nie w przypadku wszystkich przewoźników. Jeżeli w trakcie dodawania numeru przesyłki za pomocą [POST /order/checkout-forms/{checkoutForm.id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) w polu **carrierId** wskażesz jednego z przewoźników, dla którego wspieramy śledzenie przesyłek - status przesyłki będzie widoczny bezpośrednio w Allegro.pl.

**Comment by AdrianPiechota** [comment]
Chodziło mi raczej o możliwość ręcznego dodawania kolejnych statusów (w przewozie, doręczono itp) przesyłki do Allegro. Rozumiem, że API nie udostępnia takiej możliwości? Czy w takim razie jest ona może w planach?

> Jeżeli w trakcie dodawania numeru przesyłki za pomocą POST /order/checkout-forms/{checkoutForm.id}/shipments w polu carrierId wskażesz jednego z przewoźników, dla którego wspieramy śledzenie przesyłek - status przesyłki będzie widoczny bezpośrednio w Allegro.pl.

Czy znajdę gdzieś listę tych przewoźników? Próbowałem dla przewoźników z `/order/carriers`: 

Dla InPost i nie nie wyświetla:
![obraz](https://user-images.githubusercontent.com/6989873/97405608-3c721e80-18f8-11eb-9824-4f2480cbc6aa.png)

Dla Poczty (Pocztex Kurier 48) wyświetla, ale nieaktualny status:
![obraz](https://user-images.githubusercontent.com/6989873/97406124-02ede300-18f9-11eb-8c24-e599a8147ed4.png)
przesyłka jest doręczona https://emonitoring.poczta-polska.pl/?numer=00359007738374712329

DPD równiez nie wyświetla:
![obraz](https://user-images.githubusercontent.com/6989873/97406303-52341380-18f9-11eb-9c06-944b58296353.png)

Jakie mamy opcje aby prawidłowo wyświetlać statusy przesyłek kupującym?

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy możliwości samodzielnej zmiany statusu przesyłki. Chcemy uzyskiwać te dane bezpośrednio od przewoźników.

Na ten moment kupujący może śledzić przesyłkę bezpośrednio w Allegro w przypadku następujących przewoźników: DPD, Poczta Polska, InPost, X-press Couriers i RUCH.

Jeżeli chodzi o brak śledzenia czy nieprawidłowy status przesyłki - nie jest to problem bezpośrednio związany z publicznym API, dlatego proszę zgłoś to poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) oraz podaj numery powyższych przykładowych zamówień, gdzie pomimo dodania prawidłowego numeru przesyłki - śledzenie nie jest prawidłowe.
