### ISSUE TITLE
 Server returned HTTP response code: 415 for URL: https://api.allegro.pl/order/checkout-forms/7a0d5e96-1857-11eb-83f8-e53b0700a720/shipments

### ISSUE THREAD

**Issue by dingzheyan** [allegro/allegro-api#3822]
![image](https://user-images.githubusercontent.com/28720657/97376825-5b24e500-18f9-11eb-8b7c-33cf5896f9a0.png)

**Comment by MaciejFrackowiak** [comment]
We will return error 415 if you do not add content-type header - "application/vnd.allegro.public.v1+json" as we described in [documentation](https://developer.allegro.pl/documentation/#operation/getOrderShipmentsUsingGET). I also tried to find your request in our logs, however I was unable to find it.

**Comment by dingzheyan** [comment]
Unsupported content type. Please check 'Content-Type' request header
![Uploading image.png…]()

**Comment by dingzheyan** [comment]
Unsupported content type. Please check 'Content-Type' request header
![image](https://user-images.githubusercontent.com/28720657/97437265-2bf48f00-195e-11eb-9d13-b76b761e9e27.png)

**Comment by MaciejFrackowiak** [comment]
You have incorrect content-type "application/json" - you should use "application/vnd.allegro.public.v1+json" as I mentioned before.

**Comment by dingzheyan** [comment]
ok ,thanks
