### ISSUE TITLE
Skąd wziąć seller.id mając tylko nick/username użytkownika?

### ISSUE THREAD

**Issue by vifus** [allegro/allegro-api#3823]
Jak w tytule, mam nazwę użytkownika i chciałbym na tej podstawie dobrać się do seller.id 

Jest mi to potrzebne do pobrania aukcji usera
`https://api.allegro.pl/offers/listing?seller.id=".$info['user-id']."&limit=".$auctionsPage."&offset=".$auctionsPage*$page`

Wcześniej działała ta metoda:

`	$client = new SoapClient('https://webapi.allegro.pl/service.php?wsdl');
	$info = $client->doGetUserID($key, 1, 0, $_POST['user_name']);
`

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z filtra "seller.login" dla zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - podając nazwę użytkownika w odpowiedzi otrzymasz również jego id - "seller.id":

```
{
    "items": {
        "promoted": [],
        "regular": [
            {
                "id": "5555566666",
                "name": "Testowa oferta",
                "seller": {
                    "id": "1234567890",
                    "login": "nazwa_użytkownika",
...
```
