### ISSUE TITLE
GET /sale/offers - czy można wyfiltrować wyróżnione oferty?

### ISSUE THREAD

**Issue by r1pped** [allegro/allegro-api#3824]
Jak w tytule. Albo jakieś pole w response data wskazujące na to, że ta oferta jest wyróżniona?

**Comment by MaciejFrackowiak** [comment]
Nie, w tym zasobie nie znajdziesz takiej informacji. Skorzystaj z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) by szczegółowo otrzymać te dane w sekcji "promotion".

**Comment by r1pped** [comment]
Dziękuję za informacje. Niestety to rozwiązanie sprawiłoby, że przy wielu aukcjach na koncie musiałbym wysłać dodatkowych 1000+ requestów.
Byłoby fajnie gdyby w przyszłości została dodana też ta opcja dla GET /sale/offers.
Temat do zamknięcia.

**Comment by MaciejFrackowiak** [comment]
Taką sugestię mamy już na liście dot. rozwoju REST API - dodam Twój głos w sprawie.

**Comment by CombatCode** [comment]
@r1pped możesz pobrać promowane oferty używając endpointa `/offers/listing`

**Comment by r1pped** [comment]
Tak, niestety tam limit pobranych ofert ogranicza się do 60
