### ISSUE TITLE
Unable to activate account

### ISSUE THREAD

**Issue by wangzhen1990** [allegro/allegro-api#3825]
account  dianxiaomi

**Comment by MaciejFrackowiak** [comment]
Your account is now active. However, you chose company account, so you should send any two files via [Allegro Account Details tab](https://allegro.pl.allegrosandbox.pl/myaccount/Settings/mysettings.php) to verify it.

**Comment by wangzhen1990** [comment]
Has been uploaded, please help to verify

**Comment by MaciejFrackowiak** [comment]
As I see your account is verified as the company account now.

**Comment by wangzhen1990** [comment]
![image](https://user-images.githubusercontent.com/33195988/99509603-ed804c00-29c0-11eb-8b7d-9db5fc3cdb4c.png)
As shown in the figure, the verification still fails

**Comment by MaciejFrackowiak** [comment]
Unfortunately, in our admin tool, we see different data than on the Sandbox website. I will try to explain it and come back with the answer.

**Comment by MaciejFrackowiak** [comment]
We made some changes - could you try to list an offer now? (please, do not pay attention to the company verification message).
