### ISSUE TITLE
Wiele category id wskazujące na tą samą kategorię.

### ISSUE THREAD

**Issue by Czefrej** [allegro/allegro-api#3826]
Witam mam pytanie odnośnie REST API.

Czemu REST API posiada duplikaty kategorii?

Po pobraniu danych kategorii z Rest API, wiele id wskazuję na tą samą kategorię. 

np. 
260121 i 11842 wskazuje na Pozostałe zabawki dla dzieci,
100103, 100107 i 100125 wskazuje na Pozostałe filmy na DVD
dotyczy to głównie kategorii pozostałe., ale nie jestem pewien.

Korzystając z okazji, chciałbym się dowiedzieć czemu API zwraca czasem null w lowest_delivery_price, a czasem normalną cenę  dla tej samej oferty.

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam Twojej obserwacji:

1) 11842 to Dziecko - Zabawki - Pozostałe, kategoria 260121 nie istnieje;
2) 100125 to Kultura i rozrywka - Filmy - Płyty DVD - Pozostałe, 100103 i 100107 również nie są dostępne.

Jednocześnie proszę podaj konkretne przykłady odnośnie Twojej drugiej wątpliwości.

**Comment by Czefrej** [comment]
Sprawdź proszę te linki:
https://allegro.pl/kategoria/260121
https://allegro.pl/kategoria/100103
https://allegro.pl/kategoria/100107

Przy próbie wejścia w te linki następuje redirect na poprawną kategorię. Jeżeli id by faktycznie nie istniały, allegro zwróciło by 404. np. jak tutaj - https://allegro.pl/kategoria/7821

Przy przeszukiwaniu ofert na API, allegro wypluło mi duplikaty tego samego produktu (z tym samym numerem oferty) ale z za każdym razem innymi kategoriami.

**Comment by MaciejFrackowiak** [comment]
To są stare ID kategorii, które zostały zmigrowane do nowych - widać to nawet podczas przekierowania na stronie WWW. Zmiany zostały wprowadzone we wrześniu 2020 dla tych kategorii.

**Comment by Czefrej** [comment]
Faktycznie kategorię pobierałem jakoś we wrześniu. Skoro mam trzy rekordy dla jednej kategorii to znaczy, że w ciągu jednego miesiąca kategoria była zmieniana dwukrotnie. Niezły bałagan.

**Comment by hahyes** [comment]
> Faktycznie kategorię pobierałem jakoś we wrześniu. Skoro mam trzy rekordy dla jednej kategorii to znaczy, że w ciągu jednego miesiąca kategoria była zmieniana dwukrotnie. Niezły bałagan.

Allegro regularnie zmienia zarówno kategorie, jak i parametry. Jeżeli je buforujesz lokalnie bądź zapisujesz gdzieś, musisz te dane aktualizować.

**Comment by MaciejFrackowiak** [comment]
Ze swojej strony mogę w 100% potwierdzić słowa @hahyes - zachęcamy do bieżącego i regularnego pobierania drzewa kategorii i parametrów, ponieważ tylko tak zapewnisz sobie aktualność danych.
