### ISSUE TITLE
Grupowa edycja ofert - jaka jest maksymalna ilość ofert w CONTAINS_OFFERS

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#3827]
Jaka jest obecnie maksymalna ilość ofert którą można przekazać w kolekcji CONTAINS_OFFERS podczas grupowej edycji ofert?
Kiedyś pamiętam, że było ograniczenie do 1000 ofert, teraz nie mogę znaleźć tej informacji.
Gdy wysyłam zapytanie o zmianę cennika hurtowego z 1000 numerów ofert i sprawdzam po command id status zmiany w odpowiedzi mam tylko 100 tasków. W obu odpowiedziach nie ma zadnych errorów.
CommandId dla tego requestu: b836c630-806e-4c3c-b63d-371fcc87f82f

**Comment by MaciejFrackowiak** [comment]
Limit wynosi 1000 ofert. Domyślnie w odpowiedzi zwracamy 100 operacji - musisz podać limit=1000 byśmy wyświetlili status dla 1000 operacji - opisaliśmy to w [dokumentacji](https://developer.allegro.pl/documentation/#operation/getTasksUsingGET) zasobu.

**Comment by dol1234** [comment]
Faktycznie, przegapiłem tego defaulta - dziekuje.

**Comment by dol1234** [comment]
Zauwazyłem problem z zasobami "sale/offer-modification-commands/{commandId}" oraz  "sale/offer-modification-commands/{commandId}/tasks". Jeżeli odpytuje je o konkrenty CommandId dostaje puste odpowiedzi 
{"id":"4243d064-a93c-43ad-be87-71a56a8f9fde","taskCount":{"total":0,"success":0,"failed":0}} 

Finalnie po jakimś czasie otrzymuję kompletną odpowiedź, ale brak jest progresu nie mówiąc o nieprawidłowo ustawionym total: 0

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem dane dla podanego przez Ciebie commandId - dla ogólnego zasobu otrzymałem:
```
{
    "id": "4243d064-a93c-43ad-be87-71a56a8f9fde",
    "taskCount": {
        "total": 1000,
        "success": 1000,
        "failed": 0
    }
}
```
Natomiast dla GET /sale/offer-modification-commands/4243d064-a93c-43ad-be87-71a56a8f9fde/tasks pełną listę z wykonanymi operacjami z podziałem na konkretne oferty.

**Comment by dol1234** [comment]
Tak też napisałem, ale przez kilka minut otrzymywałem {"id":"4243d064-a93c-43ad-be87-71a56a8f9fde","taskCount":{"total":0,"success":0,"failed":0}} . Proszę zwrócić uwagę na "total":0

**Comment by MaciejFrackowiak** [comment]
To jest zasób asynchroniczny - oznacza to, że statusu wykonania nie otrzymasz od razu po wykonaniu requestu. Dopiero po ostatecznym wykonaniu wszystkich zmian - a było ich 1000 dochodzi do update`u wartości. Dlatego, aby poznać szczegóły operacje polecamy korzystanie z GET /sale/offer-modification-commands/{commandId}/tasks.

**Comment by dol1234** [comment]
Chyba pomyliłeś pojęcia. Oczywistym jest, że zmiana może potrwać jednak total powinno być ustawione poprawnie w statusie commanda bez względu na status zadania (zresztą kiedyś tak było)
Dla sale/offer-modification-commands/{commandId}/tasks zwracana jest pusta kolekcja.

**Comment by MaciejFrackowiak** [comment]
Kwestię wartości przy total wyjaśniam z właściwym zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
W momencie wysłania komendy nie wiemy ile łącznie ofert jest podanych w zleceniu, stąd wartość "total=0" jest prawidłowa. Dopiero po wykonaniu całego zlecenia i odpytaniu GET otrzymasz łączną liczbę zleconych ofert w wartości "total".

**Comment by dol1234** [comment]
Oczywiście, że "wiecie" jaka jest liczba w zapytaniu dla odpytywanego CommandId, bo nie można sprawdzić statusu requestu  którego się nie wysłało - kłania się logika.
Zgaduje, że po waszej stronie request o zmiane leci na kolejke i dopiero jak zostanie w całości przetworzony to "sale/offer-modification-commands/{commandId}" oraz "sale/offer-modification-commands/{commandId}/tasks" zwrócą coś z sensem. Pierwotnie logika była inna i liczba total była ustawiona prawidłowo (mam takie przykłady w testach)

**Comment by MaciejFrackowiak** [comment]
Nie sposób zwrócić prawidłowe wartości na bieżąco, gdy mechanizm otrzymuje dziesiątki komend naraz, a tak się zadziało na podstawie zleconych przez Ciebie komend.

**Comment by dol1234** [comment]
Rozumiem, że system może się nie wyrabiać , ale wtedy wystarczy napisać prawdę, a nie opowiadać historie o tym, że czegoś nie wiecie. Dziękuję za szybką odpowiedź.
