### ISSUE TITLE
Parametry obowiązkowe

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#3829]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas próby aktualizacji oferty np:  4756084063 otrzymujemy komunikat błędu:
"Uzupełnij parametry obowiązkowe: Nazwa."

W tej kategorii ten parametr nie jest obowiązkowy, po zalogowaniu na konto allegro i kliknięciu w opcje uzupełnij parametry
jest informacja "Nie masz ofert w kategoriach, w których są do uzupełnienia parametry obowiązkowe."

Proszę o sprawdzenie i pilną informację zwrotną.

**Comment by MaciejFrackowiak** [comment]
Dla kategorii 258224 parametr 244505 "Nazwa" jest obowiązkowy - jak widzę został już uzupełniony w wymienionej ofercie.

**Comment by mojosoft** [comment]
Zgadza sie faktycznie w dniu wczorajszym ten parametr stał się obowiązkowym.

**Comment by mojosoft** [comment]
Zgadza sie faktycznie w dniu wczorajszym ten parametr stał się obowiązkowym.
mamy jeszcze problem np z ofertami

Oferta: 8712535084 Błąd REST API: opis{"errors":[{"code":"VALIDATION_ERROR","message":"New offer description is required

Wcześniej nie było problemu z aktualizacją tych ofert, proszę o weryfikacje w czym może być problem.

**Comment by MaciejFrackowiak** [comment]
Oferta posiadała przypisany produkt, do którego dodany był jego opis. Jak widzę obecnie dla produktu "f0c6c875-4f06-4cb7-822d-fdba3096a9b5" nie ma dostępnego opisu, stąd próby edycji kończyły się błędem 422 z informacją o braku opisu.

**Comment by mojosoft** [comment]
Czyli że teraz żeby zaktualizować ofertę musimy też uzupełnić opis produktu który jest przypisany do tej oferty ? 
W jaki sposób edytować opis produktu z poziomu API i bezpośrednio z konta ?

**Comment by MaciejFrackowiak** [comment]
W requeście, który został wysłany o 14:20 dla PUT/sale/offers/{offerId} brakuje sekcji description odpowiedzialnej za opis przedmiotu. W rezultacie zwróciliśmy błąd 422 - mechanizm nie może przyjąć zmian, gdy oferta nie posiada opisu.

**Comment by mojosoft** [comment]
czyli jednak chodzi o opis oferty a nie produktu przypisanego do oferty uff, sprawdzę to

**Comment by mojosoft** [comment]
Dziękuje , faktycznie to był tylko błędny opis. 

Dziękuje za naprowadzenie.
