### ISSUE TITLE
Lista wszystkich możliwych statusów dla wpłat 

### ISSUE THREAD

**Issue by piotrkomisarski** [allegro/allegro-api#383]
Gdzie można zobaczyć pełną listę ?

Dokumentacja na stronie https://allegro.pl/webapi/documentation.php/show/id,703#method-output wskazuje adres https://www.allegro.pl/help_item.php?item=2090 ale jest on nieprawidłowy.

**Comment by TomekKaczmarek** [comment]
Tu: https://allegro.pl/pomoc/faq/allegro-finanse-statusy-platnosci-oGgaG2M4ATL

Dzięki za sygnał, link w dokumentacji zaraz będzie poprawny.
