### ISSUE TITLE
compatibility-list-suggestions?offer.id=9792907048 jakikolwiek wpisany offer.id twierdzi że nie ma żadnych wartości.

### ISSUE THREAD

**Issue by Aryak2099** [allegro/allegro-api#3830]
Występuje problem: 
 - [*] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

curl -X GET \
    'https://api.allegro.pl/sale/compatibility-list-suggestions?offer.id=9792907048' 
    -H 'Authorization: Bearer {token}' 
    -H 'Accept: application/vnd.allegro.public.v1+json'

Krótko wpisując jakikolwiek id oferty zwraca wartość że oferta o wskazanym identyfikatorze nie istnieje. Metodą product.id  też pisze że dany produkt nie ma sekcji pasuje do. Bzdura

**Comment by MaciejFrackowiak** [comment]
W filtrze "offer.id" możesz podać wyłącznie numer oferty, która należy do Ciebie jako sprzedającego, wówczas otrzymasz konkretną odpowiedź w response. Gdy przesyłasz numer oferty, która nie należy do Ciebie otrzymasz "Oferta o wskazanym identyfikatorze nie istnieje."

Natomiast w "product.id" należy podać id produktu z naszej bazy, który odczytasz z [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) - nie możesz tu podać dowolnego swojego id produktu, który sam sobie obrałeś.

**Comment by Aryak2099** [comment]
Stworzyłem ofertę , pobieram po wartości offer.id  i dale to samo.
Według mnie działa to tylko z własną ofertą ale jednoczesnie tylko z własną listą kompatybilności jak jest stworzona. Opcja w takim razie bezużyteczna.

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [dokumentacją zasobu](https://developer.allegro.pl/documentation/#operation/getCompatibilityListSuggestion) w odpowiedzi otrzymasz listę pasuje do, gdy do oferty przypisany jest produkt, dla którego zdefiniowana jest właściwa tabela lub do oferty została ona dodana ręcznie.
