### ISSUE TITLE
Pobieranie ofert po dacie zakupu

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3832]
Pobieram oferty Allegro po dacie zakupu i np. klient zakupił 2 przedmioty na różnych aukcjach. Mam 2 różne zamówienia o jakimś id po czym klient to opłaca i powstaje 3 nowe zamówienie o nowym id a tamte 2 stare znikają. Czy to 3 nowe zamówienie ma datę zakupu pierwszego przedmiotu a nie teraźniejszą ?

**Comment by MaciejFrackowiak** [comment]
Data sprzedaży będzie odziedziczona po dacie najnowszego zamówienia pojedynczego.

**Comment by pietrach** [comment]
A co zrobić, żeby nie pominąć takich zamówień ? Bo stosuje filtr **lineItems.boughtAt.lte** oraz **lineItems.boughtAt.gte** i powstaje mi tu nagle 3 zamówienie ale data zakupu jest już przeszła i nie pobieram go do systemu

**Comment by pietrach** [comment]
Czy zamiast tych 2 powyższych filtrów filtr **updatedAt.lte** oraz **updatedAt.gte** byłby dobrym rozwiązaniem ? Czy uwzględnia on datę zakupu jako update ?

**Comment by MaciejFrackowiak** [comment]
updatedAt to data ostatniej zmiany na zamówieniu - nie jest to data sprzedaży. Zgodnie z [naszym FAQ](https://developer.allegro.pl/orders/#faq) odnośnie zamówień - w przypadku połączenia dwóch pojedynczych zakupów otrzymasz nowy event z nowym numerem zamówienia, a stare usuniemy. Aby zidentyfikować taką sytuację możesz oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

**Comment by pietrach** [comment]
Chodzi o to, że ja nie używam eventów. A updatedAt wychwyci powstanie nowego zamówienia ? Według mnie nowe zamówienie powinno mieć wartość id jednego ze starych i byłoby wszystko ok

**Comment by MaciejFrackowiak** [comment]
updatedAt ujrzysz w każdym zamówieniu - zatem w zamówieniu nr 1 będziesz miał jedną wartość, w nr 2 - drugą wartość, a połączonym zamówieniu de facto trzecią wartość updatedAt, zatem opieranie się na nim nie jest zbyt dobre. Tylko logika oparta na eventach i osobnych lineItem.id zapewnia właściwą obsługę zamówień łączonych.

**Comment by pietrach** [comment]
Co przy eventach znaczy filtrowanie po typie "FULFILLMENT_STATUS_CHANGED". Czyli zdarzenie kiedy sprzedawca zmienił status zamówienia ?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak - każda zmiana statusu realizacji zamówienia przez sprzedającego generuje event "FULFILLMENT_STATUS_CHANGED".

**Comment by pietrach** [comment]
Rozumiem, że każde zamówienie ma zdarzenie BOUGHT ? Nigdy to zdarzenie nie jest pomijane ?

**Comment by MaciejFrackowiak** [comment]
Nie, dla każdego zamówienia musi pojawić się minimum jedno zdarzenie - może to być BOUGHT, FILLED IN, READY_FOR_PROCESSING. Zajrzyj proszę do [poradnika](https://developer.allegro.pl/orders/#dziennik-zdarze%c5%84), gdzie opisaliśmy najważniejsze zależności.
