### ISSUE TITLE
Centrum wiadomości nie dochodzą odpowiedzi.

### ISSUE THREAD

**Issue by akxx87** [allegro/allegro-api#3833]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**

Od wczoraj od godziny 14 w centrum wiadomości pojawia się co 2 odpowiedź do kupujących wysłana za pomocą maila
Czy ktoś ma taki problem ?

**Comment by Vertigo-Online** [comment]
tak, dokladnie to samo, na kilku kontach.
część wiadomości nie pojawia się w centrum Wiadomosci czyli de facto, nie dociera do klienta (do drugiej strony).
niezaleznie czy wysłane z maila, z platformy API, są w wysłanych i nie pojawiają sie w centrum. nie ma reguły, czasem ten sam mail pare razy wysłany oi wskoczy przy ktorejs próbie a czasem w ogole.
masakra. 
na oko , przynajmiej 30% wiadomosci.

**Comment by jakub-dev271719** [comment]
Potwierdzam, również odnotowujemy problem z dostarczalnością wiadomości e-mail do Kupujących. Problem dotyczy kilku kont, wiadomość wysłana drugi raz czasami dociera do Kupującego.

**Comment by Vertigo-Online** [comment]
> Potwierdzam, również odnotowujemy problem z dostarczalnością wiadomości e-mail do Kupujących. Problem dotyczy kilku kont, wiadomość wysłana drugi raz czasami dociera do Kupującego.

zazwyczaj powtórne dochodzi ale nie zawsze. rekord mialem  cztery razy i nie doszło, wiec wszedłem bezposrednio na centrum. nie dosc ze trzeba piolnowac czy przeszło, to sprawdzac czy ponowna wiadomosc tez przeszła i pilnowac do skutku. masakra.
a ile jest takich co do nas nie dotrą i się nie dowiemy ? 
weekend na allegro!

**Comment by jakub-dev271719** [comment]
> > Potwierdzam, również odnotowujemy problem z dostarczalnością wiadomości e-mail do Kupujących. Problem dotyczy kilku kont, wiadomość wysłana drugi raz czasami dociera do Kupującego.
> 
> zazwyczaj powtórne dochodzi ale nie zawsze. rekord mialem cztery razy i nie doszło, wiec wszedłem bezposrednio na centrum. nie dosc ze trzeba piolnowac czy przeszło, to sprawdzac czy ponowna wiadomosc tez przeszła i pilnowac do skutku. masakra.
> a ile jest takich co do nas nie dotrą i się nie dowiemy ?
> weekend na allegro!

U nas większość dociera za drugim razem. No nic, czekamy na info od Allegro Tech.

**Comment by damianszymanskiphp** [comment]
Potwierdzam, problem nadal istnieje. Nawet po resendach nie dociera.

**Comment by creative-pl** [comment]
Potwierdzam, problem nadal istnieje. Nawet po resendach nie dociera. Produkcja.

**Comment by MaciejFrackowiak** [comment]
Problem nie jest powiązany bezpośrednio z funkcjonowaniem API Allegro, jednakże zgłosilśmy go do właściwego działu. Gdy tylko otrzymamy wiążącą odpowiedź, pozwolę sobie przekazać update.

**Comment by akxx87** [comment]
Ładny syf robicie teraz zaczynaja dopiero przychodzic wszystkie wiadomości. Mam nadzieje, że wyślecie do wszystkich kupujących informacje o waszej awarii ??

**Comment by BejmosBiznes** [comment]
> Ładny syf robicie teraz zaczynaja dopiero przychodzic wszystkie wiadomości. Mam nadzieje, że wyślecie do wszystkich kupujących informacje o waszej awarii ?? Przez 3 dni zablokowaliście możliwość kontaktu z kupującymi.

Potwierdzam , najgorsze jest to że ucierpimy na tym my wszyscy sprzedawcy , pewnie znowu dostane blokade bo już mi kilka negatywów padło ...

**Comment by creative-pl** [comment]
No syf robią, sprzedaż cyfrowa też kuleje przez taki bałagan, ocenzurowali maile, nie ma jak się z klientem skontaktować, telefon jedynie ale i to bywa zawodne.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem potwierdzenie, że wczoraj około godz. 20 problem został wyeliminowany, wszelkie zaległe wiadomości zostały dostarczone. Przepraszam za niedogodności.
