### ISSUE TITLE
Swagger error

### ISSUE THREAD

**Issue by michalorlinskidev** [allegro/allegro-api#3834]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**

Próba załadowania swagger.yaml do Swagger Editor kończy się błędem:
`Hide
 
Semantic error at paths./sale/loyalty/promotions/{promotionId}
Declared path parameter "promotionId" needs to be defined within every operation in the path (missing in "put"), or moved to the path-level parameters object
Jump to line 1286`

Dodanie `      parameters:
        - name: promotionId
          in: path
          description: Promotion identifier.
          required: true
          schema:
            type: string`
w linii 1327 rozwiązuje problem a dodatkowo umożliwia wygenerowanie klienta java za pomocą openapi-generator-maven-plugin

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spostrzeżenie - poprawka już wdrożona.
