### ISSUE TITLE
Wysyłanie obrazka - początkujący

### ISSUE THREAD

**Issue by selcouth2** [allegro/allegro-api#3835]
Dzień dobry,

czy byłby w stanie ktoś mi pomóc z wysyłką obrazka do Allegro?
Chciałbym wysyłać obrazek z linku 
```
curl -X POST \
    https://upload.allegro.pl/sale/images \
    -H 'Authorization: Bearer {token}' \
    -H 'Accept: application/vnd.allegro.public.v1+json' \
    -H 'Content-Type: application/vnd.allegro.public.v1+json' \
    -d '{
         "url":"https://imgur.com/1aOIvg3E.jpg"       -- wymagane, link do obrazka
        }'
```

W jaki sposób uruchomić te skrypt? Czy należy coś wpisać przy {token}? Poproszę o pomoc, jestem zielony.

**Comment by MaciejFrackowiak** [comment]
Aby skorzystać z [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST) musisz się zautoryzować przy wykorzystaniu tokena - proces uzyskania go opisaliśmy szczegółowo w [poradniku](https://developer.allegro.pl/auth/).

**Comment by selcouth2** [comment]
Dzień dobry, zautoryzowałem aplikację, posiadam token. Czy należy go pisać w nawiazy {}? Wyczytałem, że token ważny jest 12 godzin, czy za każdym razem należy generować nowy token?

**Comment by MaciejFrackowiak** [comment]
Tak, wartość tokena przekazujesz w miejscu {token}. Access_token ważny jest 12 godzin, wraz z nim otrzymujesz w parze refresh_token ważny 3 miesiące - proces opisaliśmy szczegółowo w podlinkowanym wcześniej poradniku.
