### ISSUE TITLE
Problem z dodaniem podstawowego draftu

### ISSUE THREAD

**Issue by RL89pl** [allegro/allegro-api#3836]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: 
Zgodnie z dokumentacją na stronie, wystarczy podać tytuł, jednakże zwraca mi nic nieznaczący komunikat z błędem
Zapytanie:
```python
headers = {
    'authorization': f'Bearer {access_token}',
    'accept': 'application/vnd.allegro.public.v1+json',
    'content-type': 'application/vnd.allegro.public.v1+json',
}

data = {
	"name": "Produkt testowy",
    }


response = requests.post('https://api.allegro.pl.allegrosandbox.pl/sale/offers', headers=headers, data= data)
print(response)
print(response.json())
```
Odpowiedź:

> <Response [400]>
> {'errors': [{'code': 'ERROR', 'message': 'An error has occurred', 'details': None, 'path': '/sale/offers', 'userMessage': None}]}

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam problemu - bez przeszkód dodałem draft korzystając z kodu:
```
curl -X POST \
    'https://api.allegro.pl/sale/offers'
    -H 'Authorization: Bearer {token}' \
    -H 'Accept: application/vnd.allegro.public.v1+json' \
    -H 'Content-Type: application/vnd.allegro.public.v1+json' \
    -d '{
      "name": "Oferta testowa"                       
  }
```

**Comment by RL89pl** [comment]
Okazuje się, że na innym kliencie zadziałało.
Bardzo dziwne, skoro to sandbox.
Komunikat błędu jest nic nie wartym bełkotem, a odpowiedź typu "u mnie działa", nie dość, że nie pomaga, to wprowadza w błąd.
