### ISSUE TITLE
Zmiana ilości na aukcji a parametry obowiązkowe kategorii

### ISSUE THREAD

**Issue by warehouser** [allegro/allegro-api#3837]
Witam,

kiedyś jeżeli aukcja znalazła się w kategorii do której wprowadzono nowe "parametry obowiązkowe" to można było zmieniać na niej ilości bo była w WebAPI osobna metoda do tego. Błąd był zwracany dopiero w momencie próby zmiany nazwy lub opisu aukcji, wtedy trzeba podać parametr obowiązkowy którego brakuje.

Czy w RestAPI nadal możliwa jest zmiana ilości jeżeli do kategorii w której się znajduje dodano nowe "parametry obowiązkowe" bez ich podania?

**Comment by MaciejFrackowiak** [comment]
Nie, w REST API oferta musi mieć uzupełnione wszystkie obowiązkowe parametry, aby zmiana ilości / ceny była skuteczna.

**Comment by AnimalDEV** [comment]
@MaciejFrackowiak Nie było tak, że dało się zmieniać cenę/sztuki przez metody do masowej edycji bez uzupełnionych nowych parametrów? Bo ostatnimi dniami sypie błędami o niewypełnionych parametrach, a wcześniej to działało. Czy została dodana walidacja czy się mylę?

**Comment by MaciejFrackowiak** [comment]
Nie, nic tutaj nie zmienialiśmy. Konieczne jest, aby oferta posiadała wymagane parametry by móc zmienić ilość, cenę, etc.
