### ISSUE TITLE
Błąd podczas logowania do sandboxa

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#3838]
Występuje problem: 
 - [] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Dzisiaj rano zauważyłem, że mam problem z zalogowaniem się do sandboxa. Dostaję informację: 
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/authorize","userMessage":null}]}`

**Comment by MaciejFrackowiak** [comment]
Tak, wiemy o problemie - działamy już. Powrócę z info, gdy problem zostanie wyeliminowany.

**Comment by MaciejFrackowiak** [comment]
Logowanie już w pełni działa, przepraszam za niedogodności.
