### ISSUE TITLE
Automatycznie wypełniane numery listów przewozowych z przesyłek kurierskich InPost na Allegro

### ISSUE THREAD

**Issue by 4myglass4** [allegro/allegro-api#3839]
Dzień dobry Państwu,
mamy pytanie czy jest możliwe by po konfiguracji InPost z Allegro - wypełniały się nie tylko automatycznie numery przesyłek z paczkomatów, ale i numery przesyłek kurierskich InPost?

Obecnie wypełniają nam się tylko automatycznie numery przesyłek z paczkomatów.

Czy to prawda, że istnieje taka możliwość jeśli Menadżer Paczek Inpost jest zintegrowany z Allegro?

Korzystamy z Managera paczek – wysyłamy nim do Paczkomatów.

Jeśli chodzi o wysyłkę kurierem InPost – to nalepki dla kuriera tworzymy przez program na komputer InPostSubiekt GT w wersji 1.4.1.0.

Nie wystawiamy ich przez Manadżera paczek (jak to robimy w przypadku paczkomatów InPost).

W załączniku przesyłam print screen z Allegro – jednego z naszych kont na Allegro. Są tam pokazane powiązane aplikacje i jest powiązanie „Allegro InPost Integration”. 

Mimo istniejącego połączenia "Allegro InPost Integration" dalej nie uzupełniają się nr listów przewozowych kuriera InPost. Co może być tego przyczyną?

Od firmy InPost dowiedzieliśmy się, że „Najlepszym rozwiązaniem jest użycie API ShipX od InPost w panelu Allegro.” I, iż „Ważne jest jednak, że przy API konieczne jest posiadanie umowy na usługi kurierskie aby one tam zadziałały.” – z tego co wiem mamy podpisaną umowę kurierską z kurierem InPost – ten sam kurier w dni robocze o podobnej porze odbiera regularnie nasze przesyłki.

Czy mamy możliwość integracji z API InPost na koncie na Allegro o nazwie „robax_pl”?

Jak użyć to API ShipX od InPost w panelu Allegro?

Mamy już klucz autoryzacyjny od InPost – jednak nie wiem, co z nim zrobić i klucz mamy od 30.10.2020r. od godziny 10:16 – nie wiemy, ile czasu jest ważny ten klucz… Czy w ogóle jest jeszcze ważny.

Jaka musi być dodana forma przesyłek Inpost do aukcji - z napisem "Allegro" czy bez a może ani jedno, ani drugie nie robi żadnej różnicy... Na razie mamy dodaną z dopiskiem "Allegro". Mieliśmy też bez tego dopisku i też się nie wypełniały automatycznie numery listów przewozowych przesyłek kurierskich InPost.

Jak dodać tu print screen, o którym wspomnieliśmy w tym tekście?

**Comment by PrzemyslawLukanowski** [comment]
> mamy pytanie czy jest możliwe by po konfiguracji InPost z Allegro - wypełniały się nie tylko automatycznie numery przesyłek z paczkomatów, ale i numery przesyłek kurierskich InPost?
> 
> Czy to prawda, że istnieje taka możliwość jeśli Menadżer Paczek Inpost jest zintegrowany z Allegro?
> 
> Mimo istniejącego połączenia "Allegro InPost Integration" dalej nie uzupełniają się nr listów przewozowych kuriera InPost. Co może być tego przyczyną?
> 
> Jaka musi być dodana forma przesyłek Inpost do aukcji - z napisem "Allegro" czy bez a może ani jedno, ani drugie nie robi żadnej różnicy... Na razie mamy dodaną z dopiskiem "Allegro". Mieliśmy też bez tego dopisku i też się nie wypełniały automatycznie numery listów przewozowych przesyłek kurierskich InPost.
> 

Jeśli chodzi o te pytania, zwróć się proszę z nimi do InPostu lub twórców oprogramowania InPostSubiekt GT. Niestety nie wiemy, jak dokładnie zewnętrzne aplikacje korzystają z naszego API, a poruszone przez Ciebie problemy dotyczą konfiguracji po stronie tychże aplikacji.

> Czy mamy możliwość integracji z API InPost na koncie na Allegro o nazwie „robax_pl”?
> 
> Jak użyć to API ShipX od InPost w panelu Allegro?
> 

API ShipX to API dla Managera Przesyłek Inpost. Jeżeli w powiązanych aplikacjach mają Państwo aplikację Allegro InPost Integration, oznacza to, że udało się ją prawidłowo zautoryzować na Państwa koncie.

**Comment by bieni4** [comment]
Witam, czy używają Państwo API do automatycznego generowania faktur ? Jeśli tak to czy mógłbym prosić o polecenie jakiegoś rozwiązania ? Pozdrawiam @4myglass4
