### ISSUE TITLE
Jak zacząć używać WebApi w .Net core?

### ISSUE THREAD

**Issue by marcino24pl** [allegro/allegro-api#384]
Witam, tak jak powyżej, jak zacząć tego używać w aplikacji .net corowej. Niestety dokumentacja jest bardzo słaba. Dziękuje za wszelkie podpowiedzi.

**Comment by TomekKaczmarek** [comment]
Niestety nie wspieramy tematu API w ujęciu konkretnych języków programowanie. Możemy Cię wesprzeć na poziomie treści wywołań i odpowiedzi naszego SOAP i REST API.

**Comment by rtnet-pl** [comment]
Stare api (webapi) jest bardzo łatwe w użyciu z .netem.
References > Add Service reference > Advanced > Add Web Reference > https://webapi.allegro.pl/service.php?wsdl > Add Reference
Z REST jest trochę więcej roboty.

**Comment by marcino24pl** [comment]
No tak, to zrobiłem. Ale mam dalej problem, czy mam utworzyc nową klasę np AllegroService i zaimplementowac interface z WebApi SerialPort? Po implementacji takiego interfejsu funckje mają puste ciało.

**Comment by rtnet-pl** [comment]
Podejrzyj sobie w object browser co zawiera namespace pl.allegro.webapi (w Solution explorer > Project > Web references > pl.allegro.webapi > prawy klik).
```
using test1.pl.allegro.webapi;
...
            serviceService service = new serviceService();
            service.doQueryAllSysStatus(1, "webapi key");
            service.doLogin(...)
```
