### ISSUE TITLE
Kategorie: produktyzacja i pasuje do

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3840]
Witam,
Mam dwa pytania:
1) czy w restapi jest dostępna informacja, w których kategoriach na froncie jest możliwość połączenia ofert ->przycisk na listingu "połącz oferty" ?
2) czy w zasobie https://api.{environment}/sale/compatibility-list/supported-categories może jednocześnie wystąpić kategoria nadrzędna i któreś z jej dzieci ?
Pozdrawiam, kf

**Comment by PrzemyslawLukanowski** [comment]
1) Nie, nie zwracamy takiej informacji w API.
2) Taka sytuacja nie powinna się wydarzyć.

**Comment by kfijalko** [comment]
ok
