### ISSUE TITLE
Brak informacji o ilości sprzedanych produktów

### ISSUE THREAD

**Issue by RaVq3K** [allegro/allegro-api#3841]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam gdy odpytuję zasób sale/offers w zwrotce nie otrzymuję informacji ile szt. zostało sprzedanych
![image](https://user-images.githubusercontent.com/53236315/97855492-1afba300-1cfb-11eb-98e7-637ce069fdbd.png)

**Comment by PrzemyslawLukanowski** [comment]
Wygląda na to, że odpytujesz zasób GET /sale/offers/{offerID} i otrzymujesz prawidłową zwrotkę - pole stock.sold zwracamy tylko dla GET /sale/offers.

**Comment by RaVq3K** [comment]
Racja mój błąd :)
