### ISSUE TITLE
Pobranie prowizji od sprzedaży dla konkretnego zamówienia

### ISSUE THREAD

**Issue by MarekCiecharowski** [allegro/allegro-api#3843]
Witam

Od strony panelu Allegro w "historii operacji" mam "prowizje od sprzedaży" powiązaną z konkretnym zamówieniem:
![obraz](https://user-images.githubusercontent.com/57184341/97862868-5c458000-1d06-11eb-8553-6a27040c029e.png)

Chciałbym to samo uzyskać od strony REST API, dlatego pobieram historię operacji billingowych za pomocą zasobu GET /billing/billing-entries. 

Otrzymuje:
    {
      "id": "c902931f-cfb0-4d54-9ae6-f65b8424f017",
      "occurredAt": "2020-11-02T10:44:13.332Z",
      "type": {
        "id": "SUC",
        "name": "Prowizja od sprzedaży"
      },
      "offer": {
        "id": "858274....",
        "name": "ŻWIREK SILIKONOWY DLA KOTA 3,8L"
      },
      "value": {
        "amount": "-1.94",
        "currency": "PLN"
      },
      "tax": {
        "percentage": "23"
      },
      "balance": {
        "amount": "-9950.50",
        "currency": "PLN"
      }
    }

W otrzymanej operacji billingowej nie ma nigdzie numeru zamówienia. 
Jak pobrać kwotę prowizji dla konkretnego zamówienia?

Nie musi to być w ten sposób w który ja próbuje to zrobić - punkt  startowy może być inny, tzn.
1. Mam numer zamówienia - chce wiedzieć jaka prowizja była od niego zapłacona
2. Mam płatność od klienta - chce wiedzieć jaka prowizja jest od tej płatności

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie ma takiej możliwości, aby otrzymać informację o zamówieniu powiązanym z prowizją od sprzedaży. Sugestie, aby dodać numer zamówienia do zasobu /billing/billing-entries pojawiły się już wcześniej. Zapisuję Twoje zgłoszenie do listy - jeżeli zdecydujemy się wprowadzić takie pole, opublikujemy odpowiedni komunikat.

**Comment by MarekCiecharowski** [comment]
Ok, dziękuję za informację.

**Comment by neldh** [comment]
Nam również przydałaby się taka możliwość.

**Comment by MaciejFrackowiak** [comment]
@neldh Twój głos również dodaję do listy.

**Comment by Inarus** [comment]
I ja tego szukam. Próbuję powiązać czas płatności z prowizją w 5 sekundowym przedziale ale połowa rekordów się nie spina.

**Comment by PrzemyslawLukanowski** [comment]
@Inarus Cały czas pamiętamy o tej sugestii. Gdy będę mógł przekazać więcej informacji i zdecydujemy się udostępnić to rozwiązanie, opublikujemy odpowiedni komunikat.

**Comment by awema-pl** [comment]
Ja także poproszę o wdrożenie funkcji.

**Comment by PrzemyslawLukanowski** [comment]
@awema-pl Dodałem Twój głos do naszej listy.

**Comment by awema-pl** [comment]
Kiedy można spodziewać się funkcji pobierania prowizji po numerze zamówienia?

**Comment by PrzemyslawLukanowski** [comment]
@awema-pl Zgodnie z moją informacją powyżej - "Cały czas pamiętamy o tej sugestii. Gdy będę mógł przekazać więcej informacji i zdecydujemy się udostępnić to rozwiązanie, opublikujemy odpowiedni komunikat.".

**Comment by awema-pl** [comment]
Dziękuję za odpowiedź, czekam cierpliwie.

**Comment by Lebioda** [comment]
Ile jeszcze musimy czekać? Również tego potrzebuję.

**Comment by PrzemyslawLukanowski** [comment]
Udostępnimy tę informację prawdopodobnie po Q1 2021.
