### ISSUE TITLE
Błąd: dozwolone są: {h1, h2, p, ul, ol}

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#3845]
- [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Witam podczas wysyłania aktualizacji oferty dostajemy powyższy błąd na 1 aukcji "dozwolone są: {h1, h2, p, ul, ol}"
Czy mozna sprawdzić dlaczego. Na innych aukcjach bez problemu a tutaj, albo nie widze błedu albo go nie ma
TraceId: 52a6bd087a9760cb

**Comment by PrzemyslawLukanowski** [comment]
Błąd generuje dokładnie fragment "<b>CD2</b>" - tag b powinien być osadzony np. w <p></p>.
