### ISSUE TITLE
Jak odwzorować w REST API akcję : Edytuj przedmiot -> Parametry produktu -> Wybierz produkt

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#3846]
Witam serdecznie,

Pytanie 1:
jak w temacie, jak za pomocą REST API wybrać parametry do produktu z TecDoc za pomoca indeksu produktu? 

podczas edycji ręcznej robi się to następująco: 
- otwieram aukcję 
- edytuję
- w sekcji Parametry produktu klikam "Wybierz Produkt"
- wpisuję kod produktu a następnie wybieram jeden z podpowiadanych produktów 

Pytanie 2:
Jeśli dobrze rozumiem podpowiadane produkty to tylko i wyłącznie te których dane zostały pobrane z TecDoc ? Czy istnieje też możliwość pobrania złych danych np. z ofert stworzonych przez innych użytkowników? 

Dziękuję i pozdrawiam Paweł

**Comment by PrzemyslawLukanowski** [comment]
1) Jeżeli chcesz przypisać parametry produktu do isntiejącej oferty, musisz najpierw wyszukać interesujący Cię produkt za pomocą [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts), a następnie pobrać jego pełne dane przez [GET /sale/products/{productID}](https://developer.allegro.pl/documentation/#operation/getSaleProduct). W odpowiedzi otrzymasz m.in. ID produktu, sekcję parametrów oraz inne dane produktu, które musisz przekazać przez [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT), edytując ofertę. Proces ten opisaliśmy także w [naszym poradniku](https://developer.allegro.pl/productization/#offer).
Jeżeli wystawiasz nową ofertę, możesz skorzystać z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), gdzie wystarczy, że w strukturze przekażesz tylko ID produktu, cenę i licznę sztuk - pozostałe dane uzupełnimy automatycznie, włączając w to także parametry produktu. Więcej na temat tego zasobu przeczytasz w [naszym poradniku](https://developer.allegro.pl/product_offers/).
2. Podpowiadane produkty są z naszej bazy produktowej. Nie ma możliwości, że pobierzesz złe dane z ofert innych użytkowników.

**Comment by pliszka** [comment]
Dziękuję bardzo, temat do zamknięcia :+1:
