### ISSUE TITLE
Jak pobrać kolor i rozmiar oferty

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3847]
Jak pobierając listę zamówień, zaczytać do konkretnej oferty parametry typu kolor i rozmiar?
Korzystam z zasobów :order/checkout-forms następnie >> /sale/offers/{offerId}, tu widzę parametry.
Jaki zasób odpytać by pobrać kolor i rozmiar? 
Z góry dzięki za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
W liście zamówień nie znajdziesz takiej informacji. Parametry wraz z ich wartościami znajdziesz, tak jak napisałeś, w odpowiedzi dla GET /sale/offers/{offerID}. Skorzystaj z zasobu [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), aby sprawdzić, które identyfikatory w danej kategorii odpowiadają parametrom Kolor i Rozmiar. Więcej informacji o parametrach znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#2-kategorie-i-parametry).
