### ISSUE TITLE
Dozwolone znaki w opisie i tytule oferty

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#3848]
Czy posiadacie gdzieś dostępną listę znaków wraz z kodem html, które mogą być użyte podczas tworzenia i publikowania oferty?
W przypadku TM możemy zapisać w trojaki sposób: &trade; lub &#x2122; lub &#8482;, znaków tego typu może być więcej stąd moje pytanie.

W jednym z tematów została podana strona: https://www.degraeve.com/reference/specialcharacters.php jednak na niej również są znaki z 2 możliwościami. Jeżeli lista z powyższego linku jest właściwa, proszę o określenie których kodów możemy używać do poprawnego wystawienia oferty.

**Comment by PrzemyslawLukanowski** [comment]
Listę tagów HTML, które wspieramy, znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#5-opis-oferty). Jeżeli chodzi o znak TM, jak i inne encje, możesz użyć jednego z możliwych zapisów, które określone są na [tej stronie](https://dev.w3.org/html5/html-author/charref).
