### ISSUE TITLE
Błąd w GET /offers/listing

### ISSUE THREAD

**Issue by k0rba** [allegro/allegro-api#3849]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

16f00effd62ae891 i 483c3b34c91a926f

Nie ważnie, czy przez API (GET api.allegro.pl/offers/listing), czy przez stronę:

Wyszukuję frazy "rolson klucz nastawny" w ofertach użytkownika ecartpl. Otrzymuję w odpowiedzi aukcję "Rolson 18589 - Klucz nastawny 24 cale", wszystko gra:
https://allegro.pl/uzytkownik/ecartpl?string=rolson+klucz+nastawny

Zapytanie:
GET /offers/listing?phrase=rolson+klucz+nastawny+&seller.login=ecartpl&offset=0&limit=60&fallback=0&searchMode=REGULAR&include=-all&include=items&inlcude=searchMeta HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer {token}
Accept: application/vnd.allegro.public.v1+json

Odpowiedź:
HTTP/1.1 200 OK
trace-id: 16f00effd62ae891
content-type: application/vnd.allegro.public.v1+json
content-length: 1307
date: Thu, 05 Nov 2020 23:10:21 GMT

{"items":{"promoted":[],"regular":[{"id":"9879147082","name":"Rolson 18589 - Klucz nastawny 24 cale","seller":{"id":"80988673","login":"ecartpl","company":true,"superSeller":false},"promotion":{"emphasized":false,"bold":false,"highlight":false},"delivery":{"availableForFree":false,"lowestPrice":{"amount":"8.99","currency":"PLN"}},"images":[{"url":"https://a.allegroimg.com/original/118c85/8ffeca434e9298cc24f2f2b6922a/Rolson-18589-Klucz-nastawny-24-cale"},{"url":"https://a.allegroimg.com/original/1115e6/94465be24042939fe32cadbc4751/Rolson-18589-Klucz-nastawny-24-cale-Liczba-elementow-pojedyncze"},{"url":"https://a.allegroimg.com/original/11b9ae/1d89703142a6a6d7d11684f8442c/Rolson-18589-Klucz-nastawny-24-cale-Marka-inna"},{"url":"https://a.allegroimg.com/original/111f91/00775f584832bde7e66c3e550cc6/Rolson-18589-Klucz-nastawny-24-cale-EAN-5029594185899"},{"url":"https://a.allegroimg.com/original/11a44e/4c857afe4974bd1d58ea2d73bc59/Rolson-18589-Klucz-nastawny-24-cale-Numer-katalogowy-producenta-18589"},{"url":"https://a.allegroimg.com/original/110bd3/c463f0534f36b6dacad18b06f315"}],"sellingMode":{"format":"AUCTION","price":{"amount":"6.50","currency":"PLN"},"bidCount":6},"stock":{"unit":"UNIT","available":1},"category":{"id":"252659"},"publication":{"endingAt":"2020-11-09T20:18:01.000Z"}}]}}

-----------------------------------------------------------
Wyszukuję frazy "rolson klucz nastawny cale" w ofertach tego samego użytkownika. Otrzymuję informację o braku ofert:
https://allegro.pl/uzytkownik/ecartpl?string=rolson+klucz+nastawny+cale

Zapytanie:
GET /offers/listing?phrase=rolson+klucz+nastawny+cale&seller.login=ecartpl&offset=0&limit=60&fallback=0&searchMode=REGULAR&include=-all&include=items&inlcude=searchMeta HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer {token}
Accept: application/vnd.allegro.public.v1+json

Odpowiedź:
HTTP/1.1 200 OK
trace-id: 483c3b34c91a926f
content-type: application/vnd.allegro.public.v1+json
content-length: 38
date: Thu, 05 Nov 2020 23:12:54 GMT

{"items":{"promoted":[],"regular":[]}}

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku jest to zachowanie celowe - aby zwiększyć precyzję wyników, wiążemy  wartości z oznaczeniami jednostek, dlatego dla frazy "cale", ale bez wartości, nie zwróciliśmy żadnych wyników. Czy możesz wskazać, jaki efekt chciałeś tutaj uzyskać, przekazując dodatkowo frazę "cale"?

**Comment by k0rba** [comment]
Oczywiście. Na poziomie ogólnym odpowiedź jest taka, że chciałem zwiększyć precyzję wyszukiwania. W tym konkretnym przykładzie możemy założyć, że sprzedawca ma w ofercie przedmioty, których rozmiar jest podawany w calach i takie, których rozmiar jest podawany w centymetrach. Dodając frazę "cale" wskazuję, która grupa mnie interesuje.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za wyjaśnienie. Przekazałem je do odpowiedniego zespołu, który przenalizuje to pod kątem działania mechanizmów wyszukiwania.
