### ISSUE TITLE
Pytanie dot. doGetSellFormFieldsForCategory

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#385]
Witam,

parametry zwracane dla podkategorii Wyposażenie (123) różnią się w zależności od wybranej kategorii najniższego rzędu:

Dom i Ogród - Wyposażenie - Ozdoby świąteczne i okolicznościowe - Boże Narodzenie - Pozostałe (11989)
zwracane parametry dla podkategorii Wyposażenie (123):
- **Stan (20634)**
- **Waga z opakowaniem (22140)**

Dom i Ogród - Wyposażenie - Przybory kuchenne - Noże i nożyce kuchenne - Komplety noży (68693)
zwracane parametry dla podkategorii Wyposażenie (123):
- **Waga z opakowaniem (22140)**

Proszę o informacje czy jest to błąd z Waszej strony.

**Comment by TomekKaczmarek** [comment]
Dzień dobry @joe1d83 

Nie jest to błąd. Parametry mogą się różnić na poziomie kategorii najniższego rzędu.

**Comment by joe1d83** [comment]
Dziękuję za informacje
