### ISSUE TITLE
Pytanie o publiczny listing ofert https://api.{environment}/offers/listing

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3850]
W wyniku otrzymuję element "categories->subcategories" np.:

> 
            {
                "id": "19732",
                "name": "Biżuteria i Zegarki",
                "count": 9999
            },
            {
                "id": "20585",
                "name": "Filmy",
                "count": 8888
            },

Na liście znajdują się kategorie z różnego poziomu zagnieżdżenia: dział, grupująca, liść, 
Pytanie:
W jaki sposób jest tworzona lista? Dokładnie jak są wybierane kategorie, które są uwzględniane na liście?

Pozdrawiam,kf

**Comment by PrzemyslawLukanowski** [comment]
Te kategorie są zwracane w różny sposób - jeżeli podasz jakąś kategorię w zapytaniu, to dostaniesz jej podkategorie (tylko poziom niżej). Jeżeli przekażesz kategorię, ale jest ona liściem - dostaniesz tylko tę kategorię liść. Jeżeli nie podasz kategorii, to zwracamy kategorie, w których znaleźliśmy wyniki i sa to kategorie najwyższego rzędu (ale mogą wystąpić także kategorie "pośrednie").
