### ISSUE TITLE
REST API - OTWARTE SPORY 

### ISSUE THREAD

**Issue by donedb** [allegro/allegro-api#3852]
Dzień dobry
korzystam z programu zewnetrznego edesk to generowania odpowiedzi na wiadomości klientów allegro. Niestety  zapytania z otwartych sporów, które trafiają do edesk jako NEW TICKETS, nie mogą być odpowiedziane z edesk . Pytania z allegro przychodzą z emaila powiadomiena@allegro.pl ... odpowiadając na te wiadomości Państwa system je odrzuca ..... Niby Allegro posiada API do obsługi zewnętrznej ale najwyraźniej gdzieś jest błąd lub temat nie do końca przemyślany. Proszę o wiadomość od Państwa JAK TO ROZWIAZAC, którą będę mógł przesłać do informatyków z EDESK. Pozdrawiam Dawid

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę w zgłoszeniu brakuje szczegółow, dzięki którym moglibyśmy zlokalizować przyczynę błędu. Mamy API do obsługi dyskusji, wysyłkę wiadomości można obsłużyć przy pomocy [POST /sale/disputes/{dispute.id}/messages](https://developer.allegro.pl/dispute/#6). To, czego byśmy potrzebowali od autorów oprogramowania, z którego Pan korzysta, to konkretne logi (request i response w formacie cURL), gdzie odpowiedzieliśmy błędem. Dopiero na tej podstawie będziemy mogli zweryfikować, gdzie tkwi problem. Jeżeli uda się Panu uzyskać takie dane, prosiłbym o wysyłkę wiadomości wraz z załącznikami przez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W treści wiadomości proszę dodać, że zgłoszenie dotyczy wątku na forum GitHub #3852.
