### ISSUE TITLE
How to get seller information

### ISSUE THREAD

**Issue by DevPartner** [allegro/allegro-api#3853]
Hi,

Could you please let me know how I can get seller parameters(like on the following screenshot)?
![image](https://user-images.githubusercontent.com/12186237/98373575-7e196c80-2050-11eb-86df-56cd38144924.png)

I use GET /offers/listing to get offers and I'm able to see the following params.
![image](https://user-images.githubusercontent.com/12186237/98373491-5de9ad80-2050-11eb-9fef-20bf14937246.png)

Can I get additional seller params somehow by using RestApi?

Best regards, Konstantin.

**Comment by PrzemyslawLukanowski** [comment]
You can retrieve only the information that you pointed in your attachment (via GET /offers/listing). We do not share any additional information about sellers via API.

**Comment by chuggun** [comment]
> You can retrieve only the information that you pointed in your attachment (via GET /offers/listing). We do not share any additional information about sellers via API.
May be you could share some internal calls you guys use to generate "Dane Firmy" block? Our customer do want to attach this info to orders based on the Allegro offers. Please, let us know if this data is omitted deliberately and not supposed to be obtained by resellers automatically.

**Comment by PrzemyslawLukanowski** [comment]
Every seller can retrieve his data via [GET /me](https://developer.allegro.pl/documentation/#operation/meGET) and it can e attached to his orders. We don't want to provide other sellers data in API.
