### ISSUE TITLE
Zdarzenia z przyszłości

### ISSUE THREAD

**Issue by APICoderPL** [allegro/allegro-api#3854]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Jaki jest powód, że w dzienniku zdarzeń pojawiają się zdarzenia z przyszłości:

[id] => MTYwNDU5MDIzODc0MzMyOQ
                    [type] => OFFER_ENDED
                    [occurredAt] => 2020-11-24T05:50:10.000Z
                    [offer] => stdClass Object
                        (
                            [publication] => stdClass Object
                                (
                                    [endedBy] => EXPIRATION
                                )
                        )
                )

**Comment by PrzemyslawLukanowski** [comment]
Jaka jest skala tego problemu? Czy zauważyłeś kolejne eventy tego rodzaju? Na tę chwilę przekazałem przykładowe zdarzenie dalej do analizy.

**Comment by APICoderPL** [comment]
jest bardzo duża, są tego dziesiątki i codziennie.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem, wrócę z odpowiedzią.

**Comment by APICoderPL** [comment]
czy udało się zdiagnozować przyczynę problemu?

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze nie udało się tego ustalić, przepraszam za utrudnienia. Poinformuję w wątku po wyeliminowaniu problemu.

**Comment by darsoftpl** [comment]
proszę pamiętać, że jest to dość "upierdliwy" bug, który jeżeli ktoś się nie zorientuje będzie doprowadzał do nieprawidłowych operacji na ofertach, zamówienia etc. Mało tego to samo zdarzenie może być zwracane wielokrotnie.

**Comment by PrzemyslawLukanowski** [comment]
@APICoderPL Czy cały czas zauważasz problem po swojej stronie? Jeśli tak - czy dysponujesz ID najnowszych przypadków?
