### ISSUE TITLE
Błąd 403 przy dostępie do /sale/products

### ISSUE THREAD

**Issue by walec51** [allegro/allegro-api#3855]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

```
curl --location --request GET 'https://api.allegro.pl/sale/products?ean=888462600712' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer <token uzyskany z /auth/oauth/token?grant_type=client_credentials>' 
```

Dostaje 403 Forbidden

w headerze `www-authenticate` jest info

Bearer error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."

choć wg `/auth/oauth/token?grant_type=client_credentials` uzyskałem między innymi scope `allegro:api:sale:offers:read` który wg. dokumentacji powinien dać mi dostęp do bazy produktów

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz ten błąd, ponieważ skorzystałeś z autoryzacji typu [client-credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow) (bearer-token-for-application). Zgodnie z dokumentacją, musisz być zautoryzowany za pomocą flow typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) (bearer-token-for-user).
