### ISSUE TITLE
[REST]: Publikacja lub Edycja przedmiotu z nadmiarową treścią OPISU - WTF!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#3856]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

Czy ktoś poda tu autorytatywnie jakie ograniczenia na dziś obowiązują dla przestrzeni [Treści Opisów], może z podziałem na samą treść merytoryczną (bez znaczników), dodatkowo też łącznie z wagą znaczników w treści jak i może całej reszty...??
p.s.
NIE MA RÓWNIEŻ POPRAWNEJ OBSŁUGI oraz KOMUNIKACJI BŁĘDÓW (przy przekroczeniach).

**Comment by MaciejFrackowiak** [comment]
Maksymalna wielkość opisu to 40,000 bajtów - szczegółowe dane znajdziesz w [poradniku](https://developer.allegro.pl/sale/#5-opis-oferty). Natomiast wszelkie zasady co do treści opisu, obowiązujących zasad i wymogów znajdziesz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/abc-sprzedazy/jakie-sa-zasady-dotyczace-wystawiania-i-opisu-qzdAg29ZAIV) oraz na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/zasady-dla-tytulu-i-opisu-przedmiotu-9dXYnO3OYcz).

**Comment by FromAnyHole** [comment]
@MaciejFrackowiak - no powiedzmy, że tam są wiarygodne informacje...
A co z obsługą błędów w REST? Proszę ujawnić listę ERRORS dla wszelkich przekroczeń!

**Comment by MaciejFrackowiak** [comment]
Nie mamy takiej listy dostępnej, część komunikatów błędów generowana jest na podstawie użytych zmiennych, zatem taka lista byłaby nieskończenie długa.

**Comment by FaustT2** [comment]
Proszę o doprecyzowanie używania tagów w polach opisowych, przy kolejnych próbach edycji opisu otrzymałem informację:

      ["path"]=> string(40) "description.sections[0].items[0].content"
      ["userMessage"]=> string(37) "Błędny tag "h2", dozwolone są: {b}"
        
API nie dopuszcza również możliwości stosowania <br> 
      string(37) "Błędny tag "br" , dozwolone są: {b}" - XHTML
      string(35) "Brakuje taga zamykającego dla "br"" - HTML

Z komunikatów wynika, że jedynym tagiem nie skutkującym odrzuceniem treści jest.... tag <b>.
Pomijając drakońskie obostrzenie ma się to nijak do informacji zawartych w https://developer.allegro.pl/sale/#5-opis-oferty.

**Comment by MaciejFrackowiak** [comment]
@FaustT2 Zgadza się, nie akceptujemy ```<br>``` - możesz użyć ```<p></p>``` i osiągniesz ten sam efekt. Tag h2 oraz h1 możesz stosować wyłącznie bez dodatkowego formatowania, co opisaliśmy we wskazanym poradniku.

**Comment by FaustT2** [comment]
**Nie akceptujecie również p, h1, h2, ul, li... napisałem wyraźnie - jedynym tagiem, który akceptujecie jest b.** 

```
<h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit</h1>
    <p><b>Aliquam vitae nisi ac lectus gravida rhoncus</b>. Vivamus egestas, orci quis
    fermentum sollicitudin, leo urna pellentesque quam, ut mattis risus nisl sed dolor.</p>
    <ul>
        <li><b>Nulla eu justo ut velit pellentesque porta.</b></li>
        <li>Pellentesque eget arcu id ligula consequat fermentum at nec velit. Maecenas vitae nunc
        non ante aliquet facilisis nec id leo.</li>
        <li>Sed vitae metus vel lorem iaculis rhoncus.</li> <li>Nullam nec felis felis.</li>
    </ul>
    <ol>
        <li><p><b>In eget vulputate purus</b></p></li>
        <li><p>Integer a pharetra odio.</p></li>
        <li><p>Vestibulum ut vestibulum diam.</p></li>
        <li><p>Phasellus quis tempor ipsum, at tincidunt nibh.</p></li>
        <li><p>Nulla sollicitudin, libero sit amet fermentum iaculis.</p></li>
    </ol>
```
["path"]=>
      string(40) "description.sections[0].items[0].content"
      ["userMessage"]=>
      string(37) "Błędny tag "h1", dozwolone są: {b}"

Powyższy przykład kodu poprawnego pochodzi z waszej dokumentacji...

**Comment by MaciejFrackowiak** [comment]
@FaustT2 Proszę podaj mi trace-id Twojego wywołania.
Opis skopiowany z poradnika i przesłany w poniższej formie bez przeszkód jest akceptowany przez mechanizm:
```
"description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit</h1><p><b>Aliquam vitae nisi ac lectus gravida rhoncus</b>. Vivamus egestas, orci quis fermentum sollicitudin, leo urna pellentesque quam, ut mattis risus nisl sed dolor.</p><ul><li><b>Nulla eu justo ut velit pellentesque porta.</b></li><li>Pellentesque eget arcu id ligula consequat fermentum at nec velit. Maecenas vitae nuncnon ante aliquet facilisis nec id leo.</li><li>Sed vitae metus vel lorem iaculis rhoncus.</li> <li>Nullam nec felis felis.</li></ul><ol><li><p><b>In eget vulputate purus</b></p></li><li><p>Integer a pharetra odio.</p></li><li><p>Vestibulum ut vestibulum diam.</p></li><li><p>Phasellus quis tempor ipsum, at tincidunt nibh.</p></li><li><p>Nulla sollicitudin, libero sit amet fermentum iaculis.</p></li></ol>"
                    }
                ]
            }
        ]
    },
```
