### ISSUE TITLE
Nowy załącznik w dyskusji

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3857]
Wysyłając załączniki do dyskusji na przykładowe adresy:

https://upload.allegro.pl.allegrosandbox.pl/sale/dispute-attachments/abe08edb-b16d-4e5a-9009-fc75a0b31c78
https://upload.allegro.pl.allegrosandbox.pl/sale/dispute-attachments/399f8506-84d6-4fa4-9ad0-256f9da8db6a

Otrzymuje odpowiedź: OK, a Content jest pusty, która nie jest ujęta w dokumentacji. Co w takim razie źle robię?

**Comment by MaciejFrackowiak** [comment]
Czy masz trace-id swoich wywołań? W jakim formacie dołączasz załączniki - od formatu zależy content-type, który musisz przekazać dla tego [zasobu](https://developer.allegro.pl/documentation/#operation/uploadDisputeAttachmentUsingPUT).

**Comment by marmited** [comment]
Nie mam akurat dla tych ale tutaj kolejne wywołanie:

https://upload.allegro.pl.allegrosandbox.pl/sale/dispute-attachments/6de878d5-f13a-4c39-9727-53d0daadd1fb

"trace-id": "e5e3afb4ed554c10"

Ustawiam odpowiedni Content-Type w zależności od pliku. Pliki które testowałem to png i jpg.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem podany przez Ciebie trace-id - plik załadowany został na serwer, status wykonania operacji to 200. Po takiej operacji musisz wykorzystać przesłany przez siebie plik dodając go do trwającej dyskusji poprzez [POST /sale/disputes/{disputeId}/messages](https://developer.allegro.pl/documentation/#operation/addMessageToDisputeUsingPOST) - przykładowy request:
```
{
  "text": "Odpowiadam na dyskusję",
  "attachment": {
      "id": "b8a07492-b6fd-43c0-81c5-978f136c3e24"
  },
  "type": "REGULAR"
}
```
Proces zarządzania dyskusjami opisaliśmy w [naszym poradniku](https://developer.allegro.pl/dispute/#0).

**Comment by marmited** [comment]
Po takiej wysyłce otrzymuje błąd:

{trace-id=3ac4c3bce71c6840}
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

**Comment by MaciejFrackowiak** [comment]
Komunikat, który otrzymałeś pojawia się, gdy jako attachment.id podasz null - wówczas zwracamy błąd 500.

**Comment by marmited** [comment]
Diękuję za pomoc. Faktycznie, okazało się że wysyłam attachment.attachmentId zamiast attachment.id. Błąd który otrzymywałem wskazywał zdecydowanie inny problem.

Jednak muszę zauważyć że w Państwa dokumentacji są błędy, poprawny status jest opisany jako 201 a nie 200.

Tak samo nie wiem dlaczego nie podaliście nagłówka Accept dla [zasobu](https://developer.allegro.pl/dispute/#5) pobierającego załączniki z dyskusji. Dopiero w [#1215](https://github.com/allegro/allegro-api/issues/1215) z tamtego roku jest taka informacja.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zwrócenie uwagi odnośnie dokumentacji oraz poradnika - oba tematy już zaadresowałem.
