### ISSUE TITLE
Co może powodować zwrócenie kodu 500 podczas dodawania pakietu

### ISSUE THREAD

**Issue by arczas89** [allegro/allegro-api#3858]
Dodaję draft ogłoszenia (w samochodach), później robię: 

PUT https://api.allegro.pl/sale/offer-classifieds-packages/idOferty
{
        "basePackage": {"id": "' . $this->selectedPackageId . '"}
}

Wcześniej oczywiście pobieram pakiety pasujące do kategorii, pobieram sobie ID podstawowego pakietu do $this->selectedPackageId.

W odpowiedzi dostaję kod 500:

array(1) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(5) {
      ["code"]=>
      string(21) "INTERNAL_SERVER_ERROR"
      ["message"]=>
      string(22) "Internal server error."
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(57) "Internal server error. Please try again in a few minutes."
    }
  }
}

Najlepsze jest to, że jak próbuje popsuć i np.: ID pakietu wpiszę jakieś z dupy to normalnie dostaje w zwrotce, kod błędu że nie ma takiego pakietu itd. Dopiero jak wszystko się zgadza i powinno zwrócić OK 200 to zwraca INTERNAL_SERVER_ERROR.

Wcześniej mi to działało, po jakimś miesiącu usiadłem i taki problem.

**Comment by MaciejFrackowiak** [comment]
Przed momentem sprawdziłem działanie zasobów - przygotowałem draft ogłoszenia, a następnie korzystając z PUT /sale/offer-classifieds-packages/{offerId} dodałem pakiet promocyjny - przykładowo:
```
{
    "basePackage": 
{
    "id": "21144348-0415-4dce-a8fe-40f423f596ad"
}
}
``` 
Wysłany request zakończył się statusem 200 OK. Pakiet został dodany do draftu ogłoszenia. Sprawdź proszę swój kod, który przekazujesz.

**Comment by arczas89** [comment]
> Przed momentem sprawdziłem działanie zasobów - przygotowałem draft ogłoszenia, a następnie korzystając z PUT /sale/offer-classifieds-packages/{offerId} dodałem pakiet promocyjny - przykładowo:
> 
> ```
> {
>     "basePackage": 
> {
>     "id": "21144348-0415-4dce-a8fe-40f423f596ad"
> }
> }
> ```
> 
> Wysłany request zakończył się statusem 200 OK. Pakiet został dodany do draftu ogłoszenia. Sprawdź proszę swój kod, który przekazujesz.

`$ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.allegro.pl/sale/offer-classifieds-packages/' . $this->offerId);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
        curl_setopt($ch, CURLOPT_POSTFIELDS, '{"basePackage": {"id": "' . $this->selectedPackageId . '"}}');

        $headers = array();
        $headers[] = 'Authorization: Bearer ' . $this->accessToken;
        $headers[] = 'Accept: application/vnd.allegro.public.v1+json';
        $headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        echo '<pre>';
        var_dump(json_decode($result, true));
        echo '</pre>';
        $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        //var_dump($resultCode);
        if ($result === false || $resultCode !== 200) {
            exit ("Something went wrong " . $resultCode);
        }
        curl_close($ch);`

Niestety u mnie jest problem. Wszystko inne działa, dodawanie draftu działa, kontaktów, zdjęć ale tu jest tylko problem. Jak mówie jak z palce podam jakiś zmyślony offerID albo zmyślony ID pakietu lub barer to dostaje zwrotkę z konkretnym błędem, że to i to jest źle. Gdy wszystko jest podane tak jak ma być to mam wtedy ten błąd 500

**Comment by arczas89** [comment]
> Przed momentem sprawdziłem działanie zasobów - przygotowałem draft ogłoszenia, a następnie korzystając z PUT /sale/offer-classifieds-packages/{offerId} dodałem pakiet promocyjny - przykładowo:
> 
> ```
> {
>     "basePackage": 
> {
>     "id": "21144348-0415-4dce-a8fe-40f423f596ad"
> }
> }
> ```
> 
> Wysłany request zakończył się statusem 200 OK. Pakiet został dodany do draftu ogłoszenia. Sprawdź proszę swój kod, który przekazujesz.

Ok jak uprościłem draft do samego Tytułu oferty i kategorii to działa. Dziwne. Przejrzę krok po kroku co w drafcie może to psuć.

**Comment by MaciejFrackowiak** [comment]
Mam nadzieję, że uda Ci się zlokalizować źródło problemu.
