### ISSUE TITLE
HTTP 500 przy próbie stworzenia oferty na podstawie produktu

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#3859]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Track-id: 92911609bf95e7a3

Za każdym razem przy próbie utworzenia tej konkretnej oferty produktyzowanej (POST https://api.allegro.pl/sale/product-offers) otrzymujemy:
`{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}`

Request dosyłam przez formularz kontaktowy.

**Comment by MaciejFrackowiak** [comment]
Na swoim koncie nie masz uzupełnionych danych, a ponadto niezbędna będzie jego aktywacja do wystawiania ofert w serwisie, dlatego obecnie otrzymujesz błąd.
