### ISSUE TITLE
/sale/offer-publication-commands/{commandId}

### ISSUE THREAD

**Issue by dxsoftware** [allegro/allegro-api#386]
Czy ta funkcja w ogóle działa? Straciłem na nią już cały wieczór.
Cały czas otrzymuję komunikat "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
Obojętnie co zmienię w parametrach otrzymuję tylko ten komunikat, dlaczego nie możecie dodać normalnych komunikatów aby było jasne co jest nie tak.

Wysyłam parametry:
{"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"7002607592"}]}],"publication":{"action":"ACTIVATE","scheduledFor":"2018-07-10T02:00:22.000Z"}}

Co tu jest nie tak?

**Comment by MaciejPotepa** [comment]
Pracujemy nad naprawą tego zasobu, to część większego problemu, stąd to tyle trwa. Przepraszamy za kłopoty. Jak tylko naprawimy to dam znać. 

@partyumarty O którym manualu dokładnie piszesz? Poprawimy błąd. Będę wdzięczny za informacje.

**Comment by partyumarty** [comment]
@MaciejPotepa tutaj: https://developer.allegro.pl/sale/#step-7-offer-publication-commands w przykładowym request ktoś stawiał nawiasy jakby pies sikał na lodowisku... :) nie dość, że liczba kwadratowych nawiasów otwartych i zamkniętych jest inna to jeszcze są w niewłaściwych miejscach jeśli dobrze pamiętam... 2 posty wyżej jest poprawna, działająca wersja jak coś :)

**Comment by dxsoftware** [comment]
@partyumarty dalej mam ten problem.
A jaki komunikat dostajesz gdy chcesz aktywować ofertę, która zakończyła się poprzez wyprzedanie wszystkich sztuk?

**Comment by partyumarty** [comment]
@dxsoftware samo wywoałnie struktury z aukcją, której nie masz prawa wskrzesić zwaraca to co zwykle:
```
stdClass Object
(
    [id] => b1441984-28f4-4cea-9a9d-4b44ebc9aacd
    [taskCount] => stdClass Object
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
```
Natomiast kiedy już odpytasz o status dostaniesz:
```
stdClass Object
(
    [tasks] => Array
        (
            [0] => stdClass Object
                (
                    [offer] => stdClass Object
                        (
                            [id] => 7429384665
                        )

                    [message] => Could not change offer publication status
                    [status] => FAIL
                    [scheduledAt] => 2018-07-10T11:50:20.001+02:00
                    [finishedAt] => 2018-07-10T11:50:20.084+02:00
                    [field] => publication
                )

        )

)
```
Natomiast co ci po tym jak z założenia ta funkcja jest aużyteczna na ten moment. Nie można wskrzesić oferty, która się zakończyła z powodu wyprzedania. Trzeba ja najpierw wyedytować dodając dostępne sztuki, co możesz zrobić tylko w REST (bo webapi nie pozwoli Ci dotknąć trupa), a nie zrobisz tego w REST, bo od 8 dni ta funkcja nie działa i jest w trakcie naprawiania. Mówiąc krótko - gdzie się nie obrócisz zawsze dupa.

**Comment by MaciejPotepa** [comment]
@partyumarty Dzięki za wskazówkę, za kilka chwil poprawię poradnik.

**Comment by masterix** [comment]
U mnie niby zlecenie odnowienia oferty idzie poprawnie, przez GETa dostaję potwierdzenie, że success, ale oferta się nie odnawia.

**Comment by MaciejPotepa** [comment]
@masterix Wiemy o problemy. Pracujemy nad rozwiązaniem. Przepraszamy za kłopoty.

**Comment by 11mszot** [comment]
Jaka jest maksymalna ilość aukcji modyfikowanych jednocześnie metodą PUT dla tego endpointu ?

**Comment by MaciejPotepa** [comment]
@11mszot Limit to 5000 ofert i 1 sekunda na wysyłkę requesta.

**Comment by MaciejPotepa** [comment]
@11mszot aktualnie z tym endpointem mamy problemy. Pracujemy nad ich rozwiązaniem. Problemy występują przy kilku sposobach użycia endpointu. 

Aby mógł Ci pomóc w Twoim przypadku potrzebuję pełnej treści requestu i response w pliku .json razem z nagłówkiem, który przesyłasz. 
Udzielamy wsparcia technicznego jedynie z poziomu komunikacji protokołów - SOAP i REST. 

Nie zagłębiamy się w języki programowania, dlatego proszę o 'surowe' treści requestu i response.

**Comment by 11mszot** [comment]
PUT DATA 

{"modification":{"delivery":{"shipingRates":{"id":"8b491b60-3ec2-46a6-8c21-eaa4137c2bab"}}},"offerCriteria":{"offers":[{"id":"7462166484"},{"id":"7461038370"},{"id":"7460119943"},{"id":"7460119993"},{"id":"7462152731"},{"id":"7462152780"},{"id":"7460120064"},{"id":"7461469046"},{"id":"7460120134"},{"id":"7461469083"}],"type":"CONTAINS_OFFERS"}}

RESPONSE

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-modification-commands/b85490d4-2807-49ea-9c3b-8e905a7fc276/","userMessage":null}]}

HTTP 

*   Trying 5.134.213.9...
* Connected to allegroapi.io (5.134.213.9) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: C=PL; ST=Wielkopolskie; L=Poznan; O=Grupa Allegro sp. z o.o.; CN=*.allegroapi.io
* 	 start date: Mar  8 00:00:00 2017 GMT
* 	 expire date: May  6 23:59:59 2020 GMT
* 	 subjectAltName: allegroapi.io matched
* 	 issuer: C=US; O=thawte, Inc.; CN=thawte SHA256 SSL CA
* 	 SSL certificate verify ok.
> PUT /sale/offer-modification-commands/b85490d4-2807-49ea-9c3b-8e905a7fc276/ HTTP/1.1
Host: allegroapi.io
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzE5NTg0NjMsInVzZXJfbmFtZSI6IjQzMzY2NTEwIiwianRpIjoiZGNjMGE1MjUtMzkzYS00NmZlLTgzNGQtNGYwM2U5NDZkZjBiIiwiY2xpZW50X2lkIjoiOWEzMDk5MGYtODlmNC00ZmI2LWFhMGItZjYyYzJkYTc5M2NjIiwic2NvcGUiOlsiYWxsZWdyb19hcGkiXX0.YTZVW593JCAeHcUdDtwFaxv-en2NKqjEkggwNGNG80ckQofW5j_CmPMf7dE8QTq4kFYCMvUBwbluDcpvuh2IjIFLq6cKTFfaB5ZdJf5AnpcG8lSZ-p1v2ubO3Ya6nVDRcxfnX5n4oIppIS9NYVd3f3fjZ1Zx1evc7M9pfe29UwC_Giw2u-h_oOP89-X_0ObaP2DHkjfis_BU2mptqiZDhvcCRJlxrd_mDcXniiXydskj4BNO0cEE3ixdGk6NsFs8Ab2jTGUCCu1_OUdT6qWRFTY_NMUSAtP9rMT0jPiBQYt-55MgzRDnXEY3vuW_8YQA6PpDAcEuacSoSSkCY02s4A
Api-Key: eyJjbGllbnRJZCI6IjlhMzA5OTBmLTg5ZjQtNGZiNi1hYTBiLWY2MmMyZGE3OTNjYyJ9.5lnSUjLDmAyj8CAzqeW_0RdLqM01PmT3r-hOf67wtiU=
Content-Length: 346

* upload completely sent off: 346 out of 346 bytes
< HTTP/1.1 400 Bad Request
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: b4cac98c1303530e
< Date: Wed, 18 Jul 2018 14:32:44 GMT
< X-RateLimit-Remaining: 8909
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
< Content-Type: application/json
< X-RateLimit-Limit: 9000
< 
* Connection #0 to host allegroapi.io left intact

**Comment by masterix** [comment]
@MaciejPotepa  coś wiadomo na temat terminu usunięcia problemów?

**Comment by MaciejPotepa** [comment]
@masterix zasób powinien już działać poprawnie. Dzięki wszystkim za cierpliwość.
