### ISSUE TITLE
Ilość ofert danego użytkownika

### ISSUE THREAD

**Issue by pawelcudowski** [allegro/allegro-api#3860]
Czy można pobrać z API jedynie liczbę wszystkich ofert użytkownika? Czy jest dostępne filtrowania w takim zapytaniu?

**Comment by MaciejFrackowiak** [comment]
Liczbę ofert pobierzesz dwojako:
1) GET /sale/offers?publication.status=ACTIVE - zwróci liczbę ofert aktywnych na Twoim koncie jako sprzedającego - widać to w polu "totalCount";
2) GET /offers/listing?seller.id=xxxxxx - zwróci liczbę ofert wybranego użytkownika w polu "searchMeta.totalCount".
