### ISSUE TITLE
Dostawa i jej koszt ustalane ze sprzedającym

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#3861]
Czy przy takiej formie dostawy zwracanej przez Allegro id jest zawsze stałe dla danego konta?
"method": {
              "id": "1fa56f79-4b6a-4821-a6f2-ca9c16d5c925",
              "name": "Dostawa i jej koszt ustalane ze sprzedającym"
            },

**Comment by PrzemyslawLukanowski** [comment]
Tak, ID metod dostawy są stałe.
