### ISSUE TITLE
Nieprawidłowy podzbiór HTML

### ISSUE THREAD

**Issue by RL89pl** [allegro/allegro-api#3862]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Losowo dostaję komunikat o błędzie - czasem przejdzie, czasem nie

'<p><b>Teczka ekologiczna wykonana z lnu.</b></p>    <p>Zawiera 1 dużą '
 'kieszeń, 1 średnią, 6 małych kieszonek w tym 2 z okienkiem oraz notes (20 '
 'kartek w linie).</p>    <p>Notes nie jest umocowany na stałe, ale wsuwany w '
 'kieszonkę, dzięki czemu można go łatwo wymienić.&nbsp;</p>    <p></p>'

Nie wiem, gdzie w tym jest błąd?

**Comment by MaciejFrackowiak** [comment]
Przed momentem edytowałem ofertę z opisem skopiowanym od Ciebie tj.:
```
<p><b>Teczka ekologiczna wykonana z lnu.</b></p>    <p>Zawiera 1 dużą ''kieszeń, 1 średnią, 6 małych kieszonek w tym 2 z okienkiem oraz notes (20 ''kartek w linie).</p>    <p>Notes nie jest umocowany na stałe, ale wsuwany w ''kieszonkę, dzięki czemu można go łatwo wymienić.&nbsp;</p>    <p></p>
```
Bez przeszkód został zaakceptowany.

**Comment by RL89pl** [comment]
Kolejna odpowiedź na zgłoszenie typu "u mnie działa".
To jestem ciekaw skąd zwortka z błędem?

{'errors': [{'code': 'VALIDATION_ERROR',              'details': 'Invalid value: .',              'message': 'Nieprawidłowy podzbiór HTML',              'path': 'description.sections[1].items[1].content',              'userMessage': 'Nieprawidłowy podzbiór HTML'}]}

**Comment by MaciejFrackowiak** [comment]
Wklej kod swojego wywołania używając znaczników < > - w przeciwnym wypadku GitHub sam dopisuje znaczniki i wówczas Twój opis wkleja się jako tekst do postu. Komunikat jasno zwraca uwagę, że użyto w opisie nieprawidłowej składni HTML - można używać tylko takiej jak opisana w [poradniku](https://developer.allegro.pl/sale/#5-opis-oferty).

**Comment by RL89pl** [comment]
``` python
"description": {
            "sections": [{
                "items": [{
                    "type": "TEXT",
                    "content": opis
                }]
            }, {
                "items": [{
                    "type": "IMAGE",
                    "url": allegro_img
                }, {
                    "type": "TEXT",
                    "content": key_info
                }]
            }]
        },```

**Comment by MaciejFrackowiak** [comment]
'path': 'description.sections[1].items[1].content' sugeruje, że problem jest w drugiej sekcji, w drugim itemie, czyli patrząc na wklejony przez Ciebie kod - to co kryje się pod "key_info". I tu prośba, abyś podał w < > wklejaną wartość lub podał trace-id wywołania byśmy mogli sprawdzić w logach.

**Comment by RL89pl** [comment]
Teraz to ma sens, bo te, które przechodzą to mają uzupełnione key_info, a te, które nie przechodzą mają puste, bądź wpisaną kropkę. Tylko dlaczego nie pozwala na przesyłanie tego?
`
key_info = "."
`

**Comment by MaciejFrackowiak** [comment]
Musisz tekst ująć w znaczniki, czyli:
```
<p>.</p>
```

**Comment by RL89pl** [comment]
Ewidentnie mój błąd i niedopatrzenie. Szukałem błędu, gdzie go nie było, choć ewidentnie index 1 , a nie 0 był w kodzie błędu.
Dziękuję za pomoc
