### ISSUE TITLE
An error occurred during the api authorization process. 

### ISSUE THREAD

**Issue by Myamwso** [allegro/allegro-api#3863]
An error occurred during the api authorization process. I don’t know why this problem occurred. How to deal with this problem.
[Apply for api](http://r6d.cn/CBxj)
[Error](http://r6d.cn/CBxh)

**Comment by Myamwso** [comment]
https://allegro.pl/auth/oauth/token  
return   {"error":"Unauthorized","error_description":"Unauthorized"}
What to do？

**Comment by Myamwso** [comment]
@vi4m @nigras @adamdubiel @MaciejPotepa

**Comment by MaciejFrackowiak** [comment]
You received an error because redirect_URI address which you put in your application was not the same as registered on [website](https://apps.developer.allegro.pl/). Now I see that you changed it and authorization was successful.
