### ISSUE TITLE
TECDOC ISSUE

### ISSUE THREAD

**Issue by lmajgier** [allegro/allegro-api#3864]
Czy mogą Państwo mi powiedziec o co chodzi ?

Błąd przy zmianie publikacji w ofercie #9875400039
[{"code":"ConstraintViolationException.ValidTecdocSpecification","message":"Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data.","details":null,"path":"tecdocSpecification","userMessage":"Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data."}]

Co to oznacza?

**Comment by MaciejFrackowiak** [comment]
Otrzymany komunikat oznacza, że przypisana do oferty specyfikacja TecDoc nie jest aktualna względem tej, która jest obecnie dostępna dla produktu. Do Twojej oferty przypisałeś produkt o id: c3d23748-7a12-478e-9466-d015bd6dd2f5 - gdy pobierzesz jego szczegóły przy pomocy [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct) to zobaczysz, że obecnie dla niego wartość pola "tecdocSpecification.id" zmieniła się. Musisz edytować ofertę z nowym id specyfikacji TecDoc, wówczas bez przeszkód aktywujesz ofertę.

**Comment by lmajgier** [comment]
To nie ulega wątpliwości, ale na jakiej zasadzie aktualizujecie ofertę tecdoc? 

To jest aktualizacja ręczna czy pociągnięta z tecdoca?

**Comment by mlonc** [comment]
Allegro wgrało nową edycję tecdoca i gdy masz ofertę wpiętą do tecdoca allegro takie kwiatki będą wychodzić przy każdej aktualizacji oferty czyli średnio co 3 miesiące jak się nie mylę.

Dla mnie bezsens zwłaszcza gdy różnica polega na  np braku jednego pojazdu w ofercie.

**Comment by MaciejFrackowiak** [comment]
@lmajgier Gdy aktualizujemy bazę TecDoc pociąga to za sobą aktualizację identyfiaktorów TecDoc w produktach z naszej bazy. Nie możemy jednak sami nadpisywać nowych wartości w ofertach, dlatego niezbędna tu jest ręczna edycja oferty przez użytkownika.

**Comment by lmajgier** [comment]
Ok, wszystko jasne, trochę się zdziwiłem, bo we wrześniu zaciągałem bazę do naszego systemu z tecdoca, 

@MaciejFrackowiak co jaki czas aktualizujecie produkty?

**Comment by MaciejFrackowiak** [comment]
Nie ma tu jednej reguły - aktualizacja produktu może mieć miejsce np. na skutek zgłoszenia użytkownika, który zgłosił nieprawidłowości, bądź tak jak w tu opisywanym przypadku na skutek aktualizacji bazy TecDoc.

**Comment by lmajgier** [comment]
Drogi Panie Macieju, 

Dodaliście obowiązkowy parametr na aukcji tecdoc, = EAN.

Jak mam teraz dostosować swoje aukcje? Nie macie metody która pozwoli mi to zrobić, ponieważ jak chce ją edytować prosicice mnie tecdoc compatiblity, a jak go podaje to zwracacie mi błąd... 

Czy Wy możecie nas uprzednio informować, że zmieniacie wersję tecdoc produktów?
Przecież byśmy dodali sobie EAN i po sprawie... nie byłoby problemu... 

A teraz, stany mag nie przesyłają się, zmiany cen tak samo, bo sobie podmieniacie i dodajecie nagle obowiązkowy EAN.

CZy była gdzieś o tym informacja?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj konkretny przykład oferty, z którą pojawił się problem, wówczas będę mógł zweryfikować stan faktyczny.

**Comment by lmajgier** [comment]
Daj spokój proszę, wszystkie oferty, w których był produkt podpięty do oferty Allegro z wersją tecdoc 2019 muszą zostać zmienione.
nawet jeśli nie chcecie EAn do danej oferty do każecie zmienić compatiblity, jak ją wysyłamy to krzycicie że źle :) 

Ogarnijcie się tam proszę, to wy wprowadzacie zmiany o których nie imformujecie a później robi się syf

Jak skończę aktualizację, bo oczywiście nie macie metody na to aby zmieniać istniejące aukcje po API to Wam podeslę listę produktów w których występują dwa kody EAN.

Czy przed dodaniem aktualizacji sprawdzaliscie fakt, że EAN nie jest równy unikatowemu kodowi? 
Eany w tecdoc się powielają.. jeden produkt ma ich kilka, zobaczycie zaraz jaki będzie 'burdel'  z ofertami

**Comment by AureliuszBrussy** [comment]
@lmajgier aby szybciej i łatwiej wyjaśnić Twoje wątpliwości - wątek ten będziemy kontynuować w najnowszym zgłoszeniu: #3936.
