### ISSUE TITLE
Pobieranie trackingu paczek

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3866]
Czy jest możliwość pobrania numeru tracking przewoźnika za pomocą REST API?
Np. w momencie tworzenia paczki. 

Na etykiecie przewozowej stworzonej przez REST API jest tracking.

Co ciekawe w podglądzie zamówień pokazane są numery trackingowe natomiast w zamówieniach w "Wysyłam z Allegro" ich nie ma. Czym jest to spowodowane?

**Comment by MaciejFrackowiak** [comment]
Przy pomocy [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/getOrderShipmentsUsingGET) możesz pobrać numery trackingowe przypisane do danego zamówienia. Natomiast odnośnie drugiej kwestii proszę doprecyzuj swoje wątpliwości.

**Comment by marmited** [comment]
Dziękuję bardzo za rozwiązanie.

Co do drugiej kwestii  to przesyłki które zostały utworzone przez rest API maja swoje numery trackingowe widoczne w zakładce Zamówienia: 
![obraz](https://user-images.githubusercontent.com/37150863/98944550-7f83e280-24f1-11eb-9488-56ee3a357b95.png)

Natomiast w aplikacji Wysyłam z Allegro nie widzę połączeń pomiędzy zamówieniem a przesyłką:
![obraz](https://user-images.githubusercontent.com/37150863/98944693-b659f880-24f1-11eb-9f2d-cf0c1f047b46.png)

**Comment by MaciejFrackowiak** [comment]
Numer przesyłki zostanie przekazany do zakładki Zamówienia dopiero, gdy dany operator przeprocesuje jej status - samo przygotowanie przesyłki nie dodaje numeru do zakładki.

**Comment by marmited** [comment]
Co to znaczy? Przesyłki są doręczone.

**Comment by MaciejFrackowiak** [comment]
W tej sytuacji proszę podaj nam przykładowe numery przesyłek oraz odpowiadające im id zamówień - dane możesz podać tu w wątku lub przekazać nam poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - dodaj tylko proszę info z numerem postu z GitHub`a.

**Comment by marmited** [comment]
Przekazałem dane przez formularz kontaktowy.

**Comment by MaciejFrackowiak** [comment]
Dotarło do nas Twoje zgłoszenie - jak sprawdziłem w obu podanych zamówieniach numer trackingowy jest uzupełniony, został dodany przez narzędzie nadawcze.

**Comment by marmited** [comment]
Proszę w takim razie powiedzieć mi dlaczego w środowisku testowym przesyłka:  0000001095746Q nie jest połączona z zamówieniem: a7fa7521-25a6-11eb-8d9a-3340f79286e1. Został przekazany ten sam email przez REST API co powinno połączyć te dwa obiekty.

**Comment by MaciejFrackowiak** [comment]
Numer trackingowy jest przekazywany do Zamówień dopiero, gdy operator przesyłki nada jej status - w przypadku Sandbox jest to niemożliwe, ponieważ nie dochodzi do transportu realnej przesyłki.

**Comment by marmited** [comment]
OK! Po jakim czasie można być pewnym takiego połączenia? Chciałbym pobierać numery trackingowe wraz z momentem pobierania listu przewozowego.

**Comment by MaciejFrackowiak** [comment]
Nie ma jednej reguły - wszystko zależy od aktualnego czasu przetwarzania danych przez przewoźnika. Czasem jest to kilka minut (lub nawet mniej), a czasem kilka godzin.
