### ISSUE TITLE
Cennik dostaw

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#3867]
Witam. Na moim koncie Allegro mam chyba z 50 cenników dostaw. Spowodowane, to jest prawdopodobnie błędami przy integracji Allegro z Magento 2 moich poprzednich programistów, ktorzy tym się zajmowali. Czy jest możliwość skasowania cenników dostawy z poziomu Api? Bo w panelu administracyjnym nie ma takiej możliwości. A może można wyczyścić całe moje konto do stanu zaraz po rejestracji.Proszę o pomoc jak pozbyć sie 50 niepotrzebnych cenników dostaw.

**Comment by MaciejFrackowiak** [comment]
Nie, w API również nie ma możliwości usunięcia utworzonych dotychczas cenników dostawy. Cenniki możesz wyłącznie edytować. Nie mamy również możliwości odgórnego skasowania danych na Twoim koncie.
