### ISSUE TITLE
Jak zmienić użytkownika?

### ISSUE THREAD

**Issue by BusterLodz** [allegro/allegro-api#387]
Zacząłem działać w REST API. Zaczęło mi nawet wychodzić. Zrobiłem zgodnie z dokumentacją logowanie. Za pierwszym razem pokazało się okienko logowania allegro i fajnie. Ale za następnym razem już nie. Jak ponownie wywołać okienko logowania allegro po kliknięci w link z dokumentacji??

**Comment by rtnet-pl** [comment]
Najlepiej chyba przekierować użytkownika na adres wylogowania: https://allegro.pl/logout.php

**Comment by BusterLodz** [comment]
Ok. Fajnie. Działa. No ale jak teraz powrócić do naszej aplikacji??

**Comment by rtnet-pl** [comment]
Jeśli masz już wygenerowane tokeny, to musisz przechować je gdzieś w aplikacji i po prostu posługiwać się odpowiednimi tokenami dla odpowiedniego konta. Gdzieś w tle mieć serwis, który je odświeży zanim wygasną.
W ostateczności jeśli użytkownik musi wygenerować nowe tokeny, czyli przejść proces logowania przez http i musi to zrobić dla więcej niż jednego konta, to jeśli to jest aplikacja webowa, to otworzyłbym nowe okno (window.open) z adresem strony wylogowania, które użytkownik musi potem zamknąć. Zamknięcie okna chyba można wykryć i potem przekierować dalej.
Jeśli aplikacja desktopowa, to możesz np. zaszyć webBrowser w twojej aplikacji i każdorazowo wyczyścić cookies pomiędzy logowaniami.
