### ISSUE TITLE
Opcje dostawy wraz z cenami dla konkretnego produktu

### ISSUE THREAD

**Issue by wussup** [allegro/allegro-api#3870]
Witam,

czy jest możliwość pobrania z API wszystkich opcji dostawy wraz z cenami dla konkretnego produktu?

API w wyszukiwaniu zwraca tylko najniższy koszt dostawy, a wolałbym wiedzieć, jakie są wszystkie możliwości.

**Comment by MaciejFrackowiak** [comment]
Nie, takie informacje dostępne są wyłącznie dla sprzedającego po pobraniu szczegółów dla shippingRates.id z danej oferty.

**Comment by wussup** [comment]
> Nie, takie informacje dostępne są wyłącznie dla sprzedającego po pobraniu szczegółów dla shippingRates.id z danej oferty.

Smutno, bo często lowest jest jako 0, ponieważ sprzedający deklaruje możliwość odbioru osobistego. Pasowałoby w wyszukiwarce przynajmniej zwracać lowest jako najniższa wartość przesyłki bez odbioru osobistego.

**Comment by MaciejFrackowiak** [comment]
@wussup W API jest dokładnie taki sam mechanizm jak na WWW - w delivery.lowestPrice.amount znajdziesz wartość najniższego kosztu dostawy bez odbioru osobistego, który wyceniany jest automatycznie na 0.

**Comment by wussup** [comment]
> @wussup W API jest dokładnie taki sam mechanizm jak na WWW - w delivery.lowestPrice.amount znajdziesz wartość najniższego kosztu dostawy bez odbioru osobistego, który wyceniany jest automatycznie na 0.

Aha, to już wiem o co chodzi, jest tak jak Pan mówi, ale nie w przypadku Allegro Lokalnie:

```
{
  "id": "1005387647",
  "name": "Maseczka Minecraft Browl Stars FORTNITE Lol zings",
  "vendor": {
    "id": "ALLEGRO_LOKALNIE",
    "url": "https://allegrolokalnie.pl/oferta/maseczka-minecraft-browl-stars-lol-dziecieca"
  },
  "seller": {
    "id": "36349218",
    "company": false,
    "superSeller": false
  },
  "promotion": {
    "emphasized": true,
    "bold": false,
    "highlight": false
  },
  "delivery": {
    "availableForFree": false,
    "lowestPrice": {
      "amount": "0.00",
      "currency": "PLN"
    }
  },
  "images": [
    {
      "url": "https://a.allegroimg.com/original/1e00d0/785e62b442bfaa51200a77f7621f"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "9.99",
      "currency": "PLN"
    },
    "popularity": 133
  },
  "stock": {
    "unit": "UNIT",
    "available": 35
  },
  "category": {
    "id": "259464"
  },
  "publication": {
    "endingAt": "2020-12-12T14:00:44.000Z"
  }
}
```

Czy w przypadku Allegro Lokalnie lowestPrice jest zawsze 0? Czy można omijać w wyszukiwaniu oferty z Allegro Lokalnie? Filter na BUY_NOW mam już ustawiony.

**Comment by MaciejFrackowiak** [comment]
Na listingu Allegro oferty z Allegro Lokalnie zwracamy bez uwzględnienia kosztów dostawy - de facto na listingu prezentujemy tylko przekierowanie do Allegro Lokalnie, a nie stronę oferty. Tym samym koszt dostawy podany zawsze będzie 0. Ogłoszenia z Allegro Lokalnie ponadto oznaczamy jako ADVERTISEMENT w formacie sprzedaży "sellingMode.format".

**Comment by wussup** [comment]
> Na listingu Allegro oferty z Allegro Lokalnie zwracamy bez uwzględnienia kosztów dostawy - de facto na listingu prezentujemy tylko przekierowanie do Allegro Lokalnie, a nie stronę oferty. Tym samym koszt dostawy podany zawsze będzie 0. Ogłoszenia z Allegro Lokalnie ponadto oznaczamy jako ADVERTISEMENT w formacie sprzedaży "sellingMode.format".

Czy jest możliwość wykluczenia ofert Allegro Lokalnie z wyszukiwania? sellingMode.format=-ADVERTISEMENT ?

**Comment by MaciejFrackowiak** [comment]
Nie, ponieważ oferty z Allegro Lokalnie z dostępnym Kup Teraz oznaczamy jako BUY_NOW.
Ogłoszenia natomiast można rozróżnić po tym, że dla nich zwracamy wpis o vendorze:
```
"vendor": {
                    "id": "ALLEGRO_LOKALNIE",
                    "url": "https://allegrolokalnie.pl/oferta/abcdef"
                },
```
Nie ma jednak możliwości filtrowania po samym vendor.id.

**Comment by wussup** [comment]
> Nie, ponieważ oferty z Allegro Lokalnie z dostępnym Kup Teraz oznaczamy jako BUY_NOW.
> Ogłoszenia natomiast można rozróżnić po tym, że dla nich zwracamy wpis o vendorze:
> 
> ```
> "vendor": {
>                     "id": "ALLEGRO_LOKALNIE",
>                     "url": "https://allegrolokalnie.pl/oferta/abcdef"
>                 },
> ```
> 
> Nie ma jednak możliwości filtrowania po samym vendor.id.

Dziękuje za informacje, tak właśnie zrobiłem.
