### ISSUE TITLE
Łączenie w warianty => rozpoznawanie zdjęć

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3871]
To łączenie w warianty jest totalną porażką. Jakoś na wiosnę zmieniliście algorytm i to średnio działa. Mamy dużo produktów, które np. mają identyczne zdjęcia a jest to produkt model wyżej i chcemy go ująć jako oddzielny byt to przy próbie stworzenia wariantu z jego rozmiarów krzyczy błędem, że już taki wariant jest bo rozpoznał gdzieś takie samo zdjęcie. To tak nie może być. Ja powinienem ustalić colorPattern i nie powinno być żadnych walidacji po zdjęciach.

**Comment by MaciejFrackowiak** [comment]
Mechanizm uznaje za takie same produkty, które mają identyczne zdjęcie i wówczas oznacza je jako duplikaty zgodnie z informacją zawartą w [poradniku](https://developer.allegro.pl/multi_variant_offers/#3b). Jeżeli dla każdego produktu i jego modelu zastosujesz osobne zdjęcie, wówczas problem nie wystąpi - rozpoznamy, że zdjęcie nie jest tożsame. Działanie mechanizmu wielowariantowości szczegółowo opisane jest w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/wielowariantowosc-jak-polaczyc-oferty-i-edytowac-warianty-lDkngqrGYhL).

**Comment by pietrach** [comment]
@MaciejFrackowiak ja wszystko to rozumiem. Ale wcześniej (jeszcze na wiosnę) mechanizm ten działał bardzo dobrze. Teraz to trochę komplikuje sprawę

**Comment by MaciejFrackowiak** [comment]
Mechanizm działa w takiej samej formie od momentu wprowadzenia wersji public zasobów - zgodnie z naszym wcześniejszym [newsem](https://github.com/allegro/allegro-api/issues/2976).

**Comment by pietrach** [comment]
Mamy następujące przypadki. Sprzedajemy obuwie np. w II gatunkach. W każdym z gatunków mamy te same modele z takimi samymi zdjęciami. Chcemy aby gatunek I i II łączyły się w warianty ale tylko w ramach swoich gatunków. I tutaj mamy problem. Albo mamy model A i model B, który jest modelem wyżej od A tego samego buta. Oba mają te same zdjęcia, żeby nie dodawać ich po kilka razy. Chcemy stworzyć warianty dla każdego oddzielnie czyli model A i jego rozmiary oraz oddzielny wariant model B i jego rozmiary. Podczas dodawania krzyczy, że błąd bo już takie zdjęcie gdzieś istnieje w innym wariancie itp.

**Comment by MaciejFrackowiak** [comment]
Stworzony mechanizm wielowariantowości jest mechanizmem uniwersalnym tj. ma łączyć po zdjęciu oferty, których przedmiotem sprzedaży jest ten sam towar. Nie sposób nam rozróżnić, że w Twoim przypadku część towarów mających to samo zdjęcie to gatunek pierwszy, a część to gatunek drugi. Aby była możliwość rozdzielenia asortymentu musiałbyś zmienić zdjęcia dla przedmiotów np. z drugiego gatunku - co kluczowe, to mogą być wizualnie te same zdjęcia jednak zapisane / uploadowane raz jeszcze tak, aby miały inny adres URL lub sumę kontrolną.

**Comment by pietrach** [comment]
> Stworzony mechanizm wielowariantowości jest mechanizmem uniwersalnym tj. ma łączyć po zdjęciu oferty, których przedmiotem sprzedaży jest ten sam towar. Nie sposób nam rozróżnić, że w Twoim przypadku część towarów mających to samo zdjęcie to gatunek pierwszy, a część to gatunek drugi. Aby była możliwość rozdzielenia asortymentu musiałbyś zmienić zdjęcia dla przedmiotów np. z drugiego gatunku - co kluczowe, to mogą być wizualnie te same zdjęcia jednak zapisane / uploadowane raz jeszcze tak, aby miały inny adres URL lub sumę kontrolną.

Czyli wystarczy, że będzie inna ścieżka zdjęcia a zdjęcie będzie identyczne jak w przypadku produktu z I gatunku ?

**Comment by MaciejFrackowiak** [comment]
Dla mechanizmu zdjęcia muszą mieć inną sumę kontrolną byśmy traktowali je jako różne - najlepiej zatem jeśli zrobisz jakąś edycję takiego zdjęcią, a następnie jego upload.

**Comment by pietrach** [comment]
Czyli jednak trzeba coś zmienić w takim zdjęciu ? To niedobrze. Myślałem, że samo stworzenie zdjęcia na nowo z już istniejącego rozwiąże sprawę.

**Comment by MaciejFrackowiak** [comment]
Wystarczy je de facto raz jeszcze zapisać i już powinno posiadać inną sumę kontrolną.

**Comment by pietrach** [comment]
@MaciejFrackowiak właśnie nie. Ponowne zapisanie nic nie zmienia. Korzystam z poniższego skryptu:

```
$sourcePath = 'foto/produkty/oryg/stare-zdjecie.jpg';     
$destPath = 'foto/produkty/oryg/nowe-zdjecie.jpg'; 
$destPath2 = 'foto/produkty/oryg/nowe-zdjecie2.jpg'; 
imagejpeg(imagecreatefromjpeg($sourcePath), $destPath, 97);
imagejpeg(imagecreatefromjpeg($sourcePath), $destPath2, 97);
```

Zdjęcie **nowe-zdjecie.jpg** oraz **nowe-zdjecie2.jpg** posiadają tą samą sumę kontrolną.
Sumę kontrolną obliczam metodą:

```
sha1_file($destPath)
sha1_file($destPath2)
```

**Comment by pietrach** [comment]
Chodzi o to, aby nic nie zmieniać a żeby Wasz system rozpoznawał to jako inne zdjęcie :-)

**Comment by MaciejFrackowiak** [comment]
Nie ma takiej możliwości - jak wspomniałem już wcześniej, nie sposób, aby mechanizm rozpoznawał jedno zdjęcie jako różne względem oferowanych przedmiotów, jak to opisałeś w gatunku 1 czy 2.

**Comment by pietrach** [comment]
Nawet zmiana koloru pixela nic nie daje. Przykład:

**Stare zdjęcie 1, pixel 495x463, kolor 249,250,245, crc = 002c1e0600498ae13f6b5477ca50d02d90de25dc**
![1](https://user-images.githubusercontent.com/5420924/110943417-7853d080-833b-11eb-9eee-b0483ae08b23.jpg)
**Nowe zdjęcie 1, pixel 495x463, kolor 253,250,245, crc = df7e951c835a737313e1cdf399ce733b43a75533**
![1-nowe](https://user-images.githubusercontent.com/5420924/110943414-77bb3a00-833b-11eb-9e16-c51435cbf55d.jpg)
**Stare zdjęcie 2, pixel 161x227, kolor 255,255,255, crc = 002c1e0600498ae13f6b5477ca50d02d90de25dc**
![2](https://user-images.githubusercontent.com/5420924/110943415-77bb3a00-833b-11eb-8227-53b53a7775e3.jpg)
**Nowe zdjęcie 2, pixel 161x227, kolor 251,255,255, crc = df7e951c835a737313e1cdf399ce733b43a75533**
![2-nowe](https://user-images.githubusercontent.com/5420924/110943411-7722a380-833b-11eb-90b4-7121d7dab089.jpg)

Przy czym stare zdjęcie 1 i 2 to te same zdjęcia tylko w dwóch różnych kopiach. W każdym z tych zdjęć zmieniono jeden pixel na inny kolor i zarówno nowe zdjęcie 1 i 2 mają takie same sumy kontrolne.

**Comment by AureliuszBrussy** [comment]
Czy jesteś pewien, że faktycznie dokonałeś jakiejkolwiek zmian w tych zdjęciach lub czy zostały one zapisane prawidłowo? Wg. mojej analizy - zdjęcia "nowe" i "stare" są identyczne.

**Comment by pietrach** [comment]
Zmieniony w nich jest kolor jednego pixela. Widocznie zmiana koloru jednego pixela nie powoduje zmiany sumy kontrolnej całego pliku. Trochę dziwne.

**Comment by pietrach** [comment]
Już wiem gdzie jest przyczyna. JPG podczas zapisu kompresuje obraz więc zmiana koloru pixela w niewielkim stopniu np. stary kolor 255, 255, 255 na nowy 255,254,255 nic nie daje i powoduje, że obraz jest identyczny z pierwotnym.

**Comment by pietrach** [comment]
W takim razie co się stanie jak mam obraz i przez formularz uploaduje go 2 razy. Czy dwa nowo powstałe pliki pod różnymi nazwami będą miały tą samą sumę kontrolną ?

**Comment by AureliuszBrussy** [comment]
@pietrach konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@pietrach 2-kroty upload niezmienionego pliku nic nie da - suma kontrolna będzie taka sama dla obydwóch zdjęć. Obliczamy file hash jeszcze przed skalowaniem zdjęcia. Zmiany wprowadzone w zdjęciu powinny być na tyle duże, że nie będą one zgubione podczas ewentualnego kompresowania zdjęcia w trakcie zapisu.
