### ISSUE TITLE
Pobieranie - przeglądanie ofert 

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#3872]
Dzień dobry,  mam pytanie 
Dlaczego liczba ofert przeglądanych przez - GET /offers/listing  różni się od zwracanej liczby z pobieranych ofert - GET /sale/offers? Zbiór wspólny tych dwóch zapytań wynosi od 98 do 100% w zależności od pory odświeżenia.  Rzadko jednak 100%. 

Przykładowe wywołanie listing w pętli po 60: 
https://api.allegro.pl/offers/listing?seller.id='.$selerId.'&limit='.$limit.'&offset='.$offset  

Przykładowe wywołanie offers w pętli po 1000 : 
https://api.allegro.pl/sale/offers?limit='.$limit.'&offset='.$offset .'&publication.status=ACTIVE

pozdrawiam Paweł

**Comment by MaciejFrackowiak** [comment]
Zasób GET /offers/listing musi wyfiltrować dane z milionów ofert, które dostępne są w serwisie by zwrócić stricte oferty konkretnego sprzedającego. Z racji ilości ofert sam listing również może odświeżać się z pewnym opóźnieniem. Natomiast GET /sale/offers filtruje już dane zautoryzowanego użytkownika, czyli zwraca już "z urzędu" tylko oferty tego jedynego konkretnego sprzedającego - a ofert w tym wypadku jest zdecydowanie mniej względem wszystkich ofert Allegro. Staramy się by mechanizmy działały możliwie spójnie, jednak nie zawsze jest to w 100% możliwe.

**Comment by syw2020xd** [comment]
Dziekuję za odpowiedż.  Mam jeszcze jedno pytanie. W zasadzie o to mi chodzi, co teraz napiszę. 

Pobieram swoje oferty w formie listy: 
https://api.allegro.pl/sale/offers?limit='.$limit.'&offset='.$offset .'&publication.status=ACTIVE 

potrzebuję jednak wyliczyc koszty oferty, dostawy  i żeby przekazać informacje czy coś jest np. wyróżnione,  muszę sięgnąć po  zasoby dotyczące szczegółu aukcji.     Zatem w pętli odpytuję o detail dla każdego listowanego auctionId:
https://api.allegro.pl/sale/offers/'.$id_auction

w ten sposób pozyskuję brakujące informacje i dopiero wtedy przekazuję do kolejnego odpytania o koszty:
https://api.allegro.pl/pricing/offer-fee-preview

Problemem jest to, że czas pobierania znacznie się wydłuża przy odpytywaniu o detail. 
Przykładowo dla około 4000 aukcji  sama lista z podstawowymi danymi pobiera się 5-8 sekund. 
Natomiast gdy dochodzi zapytanie o detail dla każdego auctionId,  wówczas czas się rozciąga do 25 - 35 minut. 


Dlatego sięgnąłem po sposób drugi, o którym pisałem we wczesniejszym wątku, czyli poprzez GET /offers/listing. . Pomimo, że filtruje miliony ofert, to tę listę mam już po około 40 sekundach dla 4000 aukcji i tam są te dane, które potrzebuje (niestety oprócz external->id, ale to sobie uzupełniam) . Jednak okazuje się, że dane mogą być troche rozbieżne. 

W jaki zatem  sposób mogę w miare sprawnie ściągnąć potrzebne dane do obliczenia kosztów aukcji, kosztów dostawy? 

Czy jest szansa, żeby dane związane z kosztami aukcji i wysyłki były dostepne na podstawowej liście GET /sale/offers, która łąduje się 5-8 sekund? Tak, żeby nie odpytywać o szczegóły dla danego produktu. 
Pozdrawiam 
Paweł

**Comment by MaciejFrackowiak** [comment]
GET /sale/offers to zasób odwzorowujący działanie listy Moje oferty z serwisu WWW. Nie ma na niej danych o kosztach czy też o wszelkich dostępnych metodach dostawy - nie planujemy tego dodawać w przyszłości.

**Comment by syw2020xd** [comment]
Czyli odpytanie każdej aukcji o szczegóły :
https://api.allegro.pl/sale/offers/'.$id_auction 
jest jedynym sposobem pozyskania informacji dodatkowych?

**Comment by MaciejFrackowiak** [comment]
Tak, dokładnie.

**Comment by syw2020xd** [comment]
rozumiem, że, jesli zamienię to na GET /offers/listing , to będę miał nie zawsze kompletne dane

**Comment by MaciejFrackowiak** [comment]
GET /offers/listing zwraca najniższy koszt dostawy, a nie każdy dostępny w ofercie.

**Comment by syw2020xd** [comment]
ok dziekuję
