### ISSUE TITLE
offer-events , oferty INACTIVE

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3873]
Mam pytanie, czy za pomocą GET sale/offer-events można śledzić tworzenie nowych draftów ofert?(INACTIVE)
Potrzebuję tworzyć na bieżąco listę ID nowo powstałych ofert o statusie INACTIVE. dzięki za pomoc

**Comment by MaciejFrackowiak** [comment]
Nie, nie zwracamy eventu o utworzeniu draftu. Pełną listę eventów znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#dziennik-zdarze%c5%84-w-ofertach-sprzedawcy).
