### ISSUE TITLE
zamówienia typu READY FOR PROCESSING

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#3874]
Mam pytanie o zasób GET order/events. Chciałbym pobrać zamówienia typu ready for processing a potem wyeliminować powtarzające się. Jak je rozpoznać?  Wyczytałem, że lineItem.id może się powtórzyć, a czy checkoutForm.id też może się powtórzyć?
pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Tak, checkoutForm.id może się powtórzyć, dlatego aby wyeliminować duplikaty, możesz dodatkowo oprzeć się na czasie wystąpienia zdarzenia, czyli polu **occuredAt**.

**Comment by speedygopl** [comment]
czyli muszę brać pod uwagę te 3 pola? : checkoutFor.Id , occuredAt i lineItem.id . Czy któreś można pominąć?

**Comment by PrzemyslawLukanowski** [comment]
Nie pomijaj żadnego, dzięki tym trzem będziesz mieć pewność w zidentyfikowaniu duplikatu.

**Comment by speedygopl** [comment]
jeszcze pytanko, jaka jest zależność między tymi polami? jeżeli którekolwiek pole się różni od swojego drugiego odpowiednika to nie mam do czynienia z duplikatem? pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Ten sam lineItem.id może wystąpić w zdarzeniach w różnych zamówieniach (o innym checkoutForm.id) i podobnie może wystąpić sytuacja, gdzie najpierw otrzymasz tylko jedno lineItem.id w danym zamówieniu, a w następnym evencie będą już np. dwa. W takich sytuacjach masz do czynienia z łączoną płatnością. 
Tak - jeżeli którekolwiek pole się różni, zamówienie nie jest wtedy duplikatem.
