### ISSUE TITLE
Zasób pobierania eventów zamówień Allegro

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#3875]
Dzień dobry,

Pytanie odnośnie zasobu: https://developer.allegro.pl/redoc/redoc-static.html#operation/getOrderEventsUsingGET
Według dokumentacji parametr **type** przyjmuje tablicę stringów, jednakże jeżeli owa tablica jest wysyłana - API zwraca wyniki pomijając ten parametr. Dopiero jak wyślemy wartość stringiem, po przecinku, przykładowo _type=FULFILLMENT_STATUS_CHANGED,FILLED_IN_ to wtedy API filtruje prawidłowo wyniki.

Mają Państwo błąd w dokumentacji, czy jednak w całym API albo tylko przy metodzie GET w parametrach typu _Array of strings_ należy je wysyłać jako string skonkatenowane znakiem przecinka?

**Comment by PrzemyslawLukanowski** [comment]
Jest to poprawne oznaczenie, zgodne z [dokumentacją swaggera](https://swagger.io/docs/specification/describing-parameters/) tablice należy wysyłać w jeden z dwóch poniższych sposobów:
`/products?color=blue,green,red or /products?color=blue&color=green`
