### ISSUE TITLE
Pobieranie parametrów => pole customValuesEnabled

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3876]
**GET /sale/categories/{categoryId}/parameters**
zwraca dane na temat parametrów. Występuje tam pole **options.customValuesEnabled**. Co ono oznacza ? Czy mogę dodać podczas tworzenia oferty albo produktu swoją wartość dla danego parametru ? Czy to tylko dotyczy wystawiania/ aktualizacji nowej oferty ?

**Comment by PrzemyslawLukanowski** [comment]
Wartość true w tym polu oznacza, że dla danego parametru z wartością niejednoznaczną (np. inna, itp.) możesz przekazać własną wartość - dotyczy to wystawiania i edycji oferty oraz tworzenia produktu. W naszym [newsie](https://developer.allegro.pl/news/#customValuesEnabled) znajdziesz więcej szczegółów o tym polu.
