### ISSUE TITLE
Witam, proszę o informacje czy można połączyć konto allegro z zewnętrzną aplikacją do składnia reklamacji lub zwrotów

### ISSUE THREAD

**Issue by And68** [allegro/allegro-api#3877]

**Comment by And68** [comment]
Witam, proszę o informacje czy można połączyć konto allegro z zewnętrzną aplikacją do składnia reklamacji lub zwrotów, Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie udostępniamy zasobów API do obsługi zwrotów klienckich. Planujemy to zrobić w drugim kwartale 2021 roku - data może jednak ulec zmianie.

**Comment by And68** [comment]
Dziękuje za informacje, mam jeszcze pytanie dotyczące panelu reklamacji czy jest możliwość stworzenia aplikacji dzięki której klient miałby możliwość zakładania reklamacji i pobierania listów przewozowych, coś na wzór door to doo.

**Comment by PrzemyslawLukanowski** [comment]
Nasze API jest skierowane głównie do sprzedających, nie udostępniamy takich możliwości dla kupujących. Sprzedawca może przez API [zarządzać dyskusjami](https://developer.allegro.pl/dispute/) oraz [pobrać listy przewozowe przypisane do zamówienia](https://developer.allegro.pl/orders/#jak-pobra%c4%87-numery-przesy%c5%82ek-dodane-do-zam%c3%b3wienia).

**Comment by And68** [comment]
ja nie pytam jako osoba prywatna tylko jako forma i chodzi mi czy jest możliwość podpięcia zewnętrznej aplikacji do reklamacji na sprzedawcy

**Comment by PrzemyslawLukanowski** [comment]
Jak wspomniałem wcześniej - jeżeli ma Pan na myśli reklamacje związane ze zwrotami towarów, to takiej funkcjonalności aktualnie przez API nie udostępniamy.

**Comment by And68** [comment]
Witam, jeszcze jedno pytanie o hiperłacze, czy jest możliwość dodania do zwrotów lub reklamacji linku przez które mieliby możliwość składania reklamacji lub zwrotu

**Comment by PrzemyslawLukanowski** [comment]
Na forum udzielamy wsparcia technicznego dot. API. Prześlij proszę zatem swoją sugestię przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
