### ISSUE TITLE
Przypisywanie ofert do kampanii

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#3878]
Czy jeśli zgłosimy ofertę do kampanii, która wymaga podania nowych cen to możemy później w trakcie trwania tej kampanii zmienić jej cenę np. na niższą ?
Czy możemy dodać do różnych kampanii tą samą ofertę z różnymi cenami ?

**Comment by AureliuszBrussy** [comment]
Możesz zmienić cenę w ofercie zgłoszonej do kampanii na cenę niższą. Dokonywanie wszelkich innych zmian w ofercie zgłoszonej do Strefy Okazji bez zgodny Allegro zgodnie z [regulaminem Strefy Okazji](https://allegro.pl/regulaminy/regulamin-strefy-okazji-R8l59vW7GfL) nie jest dozowlone, ale technicznie możliwe. 

Nie możesz zgłosić jeden oferty do wielu kampanii.

**Comment by pietrach** [comment]
A czy jest jakiś mechanizm aby poprzez API usunąć ofertę z danej kampanii ?

**Comment by pietrach** [comment]
Kolejne pytanie czy jak zgłaszam ofertę do kampanii i nadam jej cenę rynkową i cenę promocyjną to ta cena sama się już ustawi w ofercie czy jeszcze muszę dodatkowo wyedytować ofertę i jej ustawić tą cenę co w kampanii ? (Mam nadzieje, że nie :-))

**Comment by AureliuszBrussy** [comment]
W API Allegro nie ma mechanizmu pozwalającego na usunięcie oferty z danej kampanii. 

Cena promocyjna zostanie wprowadzona w ofercie automatycznie po pozytywnej weryfikacji.

**Comment by pietrach** [comment]
A w jaki sposób możemy wyjść z wybranymi ofertami z danej kampanii poprzez API. Zależy nam na takim mechanizmie gdyż musimy liczyć koszty itp.

**Comment by pietrach** [comment]
Np. mamy Outlet i chcemy tam wejść na 10 dni a później wyjść ze wszystkimi ofertami

**Comment by AureliuszBrussy** [comment]
Pytanie to nie dotyczy bezpośrednio API Allegro, ale ogólnego funkcjonowania Strefy Okazji. W takiej sytuacji proszę, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022).

**Comment by pietrach** [comment]
1. Czy można dodać kilka zgłoszeń kampanii do jednej oferty poprzez API jedno po drugim ?
2. GET /sale/badges => czy od razu po wysłaniu zgłoszenia oferty do kampanii będzie to widoczne w tym zasobie ?

**Comment by AureliuszBrussy** [comment]
2 i 4. Na zasobie **GET /sale/badge-applications** są 3 możliwe statusy zgłoszenia: REQUESTED, PROCESSED i DECLINED - z czego tylko ten pierwszy może się zmienić. Po

**Comment by AureliuszBrussy** [comment]
1. Można, natomiast kolejne zgłoszenia tej samej oferty będą odrzucane. 
2. Zgłoszenie będzie widoczne w **GET /sale/badges** dopiero, gdy uzyska status **PROCESSED** na zasobie **GET /sale/badge-applications**.
3.  Nie ma takiego maksymalnego czasu ważności zgłoszenia. Obecnie informację o wyniku weryfikacji otrzymasz zwykle niemalże od razu. Jeśli jednak zdarzy się sytuacja, że zgłoszenie czeka już długo na wynik - aby to wyjaśnić, proszę o kontakt poprzez ten [formularz](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).
4. W przypadku zasobu: **GET /sale/badge-applications** statusy, które się nie zmienią to **PROCESSED** i **DECLINED**.

**Comment by pietrach** [comment]
Czy jeśli tutaj **GET /sale/badges** oferta ma status **DECLINED** albo **FINISHED** to oznacza, że można ją ponownie zgłaszać do tej kampanii ?

**Comment by pietrach** [comment]
I co się stanie kiedy oferta będzie w kampanii i zakończę ją a następnie wznowię czy dalej będzie w tej kampanii ?

**Comment by AureliuszBrussy** [comment]
Te pytania nie dotyczą bezpośrednio funkcjonalności API Allegro, a ogólnych zasad funkcjonowania Strefy Okazji. Aby uzyskać więcej informacji na ten temat, skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).

**Comment by pietrach** [comment]
A co się dzieje gdy np. oferta została zgłoszona do OUTLET poprzez API i otrzymujemy komunikat poprzez API, że „Oferta nie spełnia kryteriów danego oznaczenia” i status takiej oferty w danym oznaczeniu jest „DECLINED”. Czy możemy wtedy ponownie wysłać zgłoszenie takiej oferty do OUTLET poprzez API z danymi spełniającymi kryteria czy musimy to wyjaśniać błąd bezpośrednio z odpowiednim działem Allegro ?

**Comment by AureliuszBrussy** [comment]
Możesz w takiej sytuacji ponownie zgłosić ofertę poprzez API - zostanie ono rozpatrzone.

**Comment by pietrach** [comment]
A co się stanie gdy zgłoszona oferta jest np. w OUTLET i wyślę ponowne zgłoszenie jej do OUTLET ale np. z inną ceną rynkową niż jest obecnie. To czy to zgłoszenie zostanie rozpatrzone i poprzednia cena anulowana czy zgłoszenie zostanie odrzucone ?

**Comment by AureliuszBrussy** [comment]
To pytanie również dotyczy ogólnego funkcjonowania Strefy Okazji. Proszę, zadaj je poprzez ten [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372). Zgłoszenie trafi prosto do zespołu zajmującego się Strefą Okazji.

**Comment by pietrach** [comment]
Ale to chodzi o API

**Comment by AureliuszBrussy** [comment]
Pytanie dotyczy ogólnego procesowania takiego zgłoszenia do Strefy Okazji, a konkretniej decyzji, jaką w takim przypadku podejmiemy. Dlatego zespołu zajmujący się Strefą Okazji będzie w stanie precyzyjnie odpowiedzieć na zapytanie, co wydarzy się w opisanym przez Ceibie przypadku.
