### ISSUE TITLE
UTWORZENIE KLUCZA API

### ISSUE THREAD

**Issue by Kuzniareklamy** [allegro/allegro-api#3879]
Dzień dobry,
Czy ktoś może udzielić nam konkretnej odpowiedzi jak połączyć program fakturowy iBiznes z allegro? Opłaciliśmy licencje na wtyczkę TradeHub, jednakże potrzebuję z konta allegro klucz API. Niestety nie mam w firmie zaplecza informatyków, i musimy poradzić sobie sami. 
Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Klucz aplikacji wygenerujesz na stronie https://apps.developer.allegro.pl/. Niestety nie znamy oprogramowania iBiznes, dlatego nie możemy wskazać konkretnych kroków, jakie dalej musisz wykonać w tejże aplikacji. Sam proces autoryzacji opisaliśmy w [naszym poradniku](https://developer.allegro.pl/auth/).

**Comment by Kuzniareklamy** [comment]
Już próbowałam, jednak nie uzyskuję żadnego klucza.....
