### ISSUE TITLE
Logowanie REST API w aplikacji desktopowej

### ISSUE THREAD

**Issue by Anidatte** [allegro/allegro-api#388]
Chcę dodać do istniejącej aplikacji w Javie możliwość pobierania danych przez REST API Allegro. Moje pytanie jest następujące: co muszę podać jako adres redirect_uri aplikacji? W jaki sposób odebrać kod do pobrania tokena?

**Comment by kfijalko** [comment]
#12 - przeczytaj

**Comment by jakubmaguza** [comment]
Na ten moment, jeśli ma to mieć jakiś sens, to w Allegro ustaw sobie przekierowanie na localhosta, a w swojej aplikacji nasłuchuj na tym samym localhoście.

**Comment by Anidatte** [comment]
Dzięki, @jakubmaguza . Po przeczytaniu całego tematu podlinkowanego przez @kfijalko  myślałem, że sytuacja jest beznadziejna, ale w praktyce pod koniec poprzedniego tygodnia udało mi się dodać obsługę REST API. Posiłkowałem się tym materiałem: https://www.ibm.com/developerworks/library/se-oauthjavapt2/index.html i poszło bez problemów, wykorzystując wyłącznie wygenerowany client ID i client secret. Działa bez zabawy z redirect_uri i bez konieczności logowania przez stronę Allegro.

**Comment by jakubmaguza** [comment]
@Anidatte Poczytam to, ale jeśli jest tak jak piszesz, to cały ten system zabezpieczeń allegro jest bez sensu :)

**Comment by MaciejPotepa** [comment]
@Anidatte 

Token można uzyskać na trzy sposoby/:

1) Token na użytkownika - tutaj mamy normalny przebieg, gdzie użytkownik się loguje na tej [stronie](https://developer.allegroapi.io/), akceptuje zgodę i później aplikacją, np Postmanem za pomocą **clientId** i **seceret** może pobrać token. Wtedy w tym tokenie jest **userId** i aplikacja może swobodnie pobierać dane dla tego użytkownika. 

2) Token w aplikacji - aplikacja korzysta tylko ze swojego **clientId** i **secret** i dostaje token, w którym nie ma **userId**, z takim tokenem nie może pobrać danych w imieniu użytkownika, ma dostęp tylko do ‘otwartych danych’, np. lista metod dostaw lub lista ofert.

3) Przez **refreshToken** - czyli gdy token wygaśnie, to masz dostępny **refreshToken**,  którym po prostu odświeżysz token - jest wtedy ważny 365 dni. 

Z tego co zrozumiałem - skorzystałeś z metody **2)**, a jesteś w przekonaniu, że masz efekt z metody **1)**. Na szczęście tak nie jest. Doceniamy dociekliwość.

**Comment by pmielcza** [comment]
Reasumując - poprawcie mnie jeśli się mylę - nie ma możliwości zalogowania się przez REST API jako dany user bez przekierowania i konieczności wprowadzenia danych użytkownika ?

Chciałbym stworzyć automat (zadanie crona na serwerze hostingowym z bazą MySQL), który co kilka godzin ściąga mi oferty z moich kont Allegro do bazy (bez ingerencji użytkownika [podawanie loginu i hasła]) - jest to możliwe ?

Może to głupie pytanie - nie jestem tutaj zawodowcem ale jakoś nie potrafię tego ogarnąć.
Mam skrypt, który działa ale za każdym razem (gdy odpalę na nowo przeglądarkę) muszę przechodzić przez logowanie .... strasznie to upierdliwe.

**Comment by Anidatte** [comment]
Musisz logować się raz na rok. Twój skrypt/zadanie po prawidłowym pierwszym logowaniu powinno zapisać token i refresh token. Token działa przez 12h i pozwala korzystać z API dodatkowego bez logowania. Po 12h używając refresh tokena generujesz nową parę token+refresh token które znów ważne są przez 12h.

Ja tak to rozumiem i implementując to w taki sposób działa bez problemu.

W zasadzie nic też chyba nie stoi na przeszkodzie aby twój skrypt przy każdym uruchomieniu generował nową parę token+refresh token. Oczywiście nadal działa zasada, że raz w roku musisz się zalogować i ponowić zezwolenie na dostęp do API.

**Comment by TimothyKoval** [comment]
> Musisz logować się raz na rok

Lub kiedy allegro Cię wyloguje, z powodu że bo tak.

**Comment by pmielcza** [comment]
Anidatte - jak dobrze rozumie - token i refresh token jak sobie zapiszę np. do pliku/bazy i przy ponownym połączeniu z nich skorzystam to Allegro nie powinno już chcieć ode mnie danych logowania ?

Parzę na to ciągle z poziomu CRON'a i zadania - czyli gdyby w razie czego "wywaliło" mi skrypt - to dobrze by było pewnie zrobić jakieś powiadomienie że trzeba z ręki skrypt odpalić i przelogować.
Jak uważacie - logika działania jest OK ?

**Comment by kfijalko** [comment]
@MaciejPotepa  Zaobserwowałem coś takiego:
1) w "mojej aplikacji" wywołuje pierwszą autoryzację dla KontaA
2) wyświetla stronę w przeglądarce chrome, która pamięta, że jestem zalogowany na KoncieB
3) klikam "potwierdź"
4) otrzymuję potwierdzenie dla KontaA
Czy tak to powinno działać, czy mi się wydaje, że KontoB wyraża zgodę dla KontaA ?

**Comment by MaciejPotepa** [comment]
@kfijalko 
Popełniasz błąd w procesie. To nie jest możliwe żebyś z autoryzował konto B kontem A. 

W swojej aplikacji uruchamiasz proces autoryzacji, ale jeszcze nie wiesz dla kogo. 
Dopiero na naszej stronie logowania okazuje się jaki user jest zalogowany.
Zakładasz, że autoryzujesz konto A, a strona logowania jest pomijana bo już jesteś zalogowany jako user z konta B i token wraca do Cienie dla konta B.

Zdekoduj otrzymany token i zobacz jaki login masz w środku, to rozwieje wątpliwości.

**Comment by TimothyKoval** [comment]
I to jest największa bzdura w tym całym api

**Comment by jakubmaguza** [comment]
Hmm.. Czy do takiego procesu nie musiałby mieć identycznego clientid i secretu na obu kontach? To jest raczej niewykonalne. Pytanie czy możliwe jest zalogowanie się jednym userem na clientid i secret drugiego usera?

**Comment by Anidatte** [comment]
ClientID i Secret są powiązane z aplikacją, to token identyfikuje użytkownika.

Bardzo podobne rozwiązanie stosuje Google w dostępie do API ich usług.

**Comment by jakubmaguza** [comment]
Rozumiem. Ma to sens :)

**Comment by Anidatte** [comment]
Ja sam na początku myślałem, że jest inaczej, ale po odpowiedzi @MaciejPotepa  na temat tokenów zdałem sobie sprawę z tego, że autoryzacja OAuth 2 do Allegro działa w zasadzie identycznie jak do API usług Google. I nagle wszystko stało się jasne. :)

**Comment by pmielcza** [comment]
witajcie, po uporaniu się z tematem logowania znowu mam pewien problem.
Mianowicie - mam skrypt który za pomocą CRONE uruchamia się co godzinę.
Skrypt przy 1 logowaniu pobiera "access_token" i "refresh_token" i zapisuje je sobie do plików.

Podczas ponownego uruchomienia skrypt pobiera za każdym razem "**refresh_token**" i zapisuje
go sobie do pliku (nadpisuje plik). 

Problem polega na tym że po 12 godzinach działania - wywala mnie z konta i muszę od
nowa się logować. 

Czy podczas każdego wywołania refresh'a powinienem pobierać także
"access_token" i też zapisywać go do pliku (nadpisywać) ? Jest możliwe że on też się zmienia ?

**Comment by jakubmaguza** [comment]
Swoją drogą, pewnie szybciej byś to sprawdził sam niż pisał i czekał na odpowiedź :)

**Comment by pmielcza** [comment]
dokładnie, już sprawdziłem - pozostaje mi poczekać to 12 godz. czy teraz faktycznie będzie już ok.
ps. ubezpieczyłem się alertem na e-maila :-)
