### ISSUE TITLE
Wielokrotność tego samego produktu

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#3881]
Cześć.

W jednym zamówieniu zauważyłem dziwny przypadek, a mianowicie klient kupił 50 sztuk produktu z tej samej aukcji, jednak z API przyszła nam informacja po 5 produktów kupionych w ilości 10 sztuk (5 x 10). W logach widzę ten sam identyfikator eventu, jednak jest inny lineItemId.
Identyfikator zamówienia - **ef3e02b1-282d-11eb-b297-df0c0e2e7aa6**
Czy nie powinno to przyjść jako jeden produkt zakupiony w ilości 50 sztuk (1 x 50)?

**Comment by AureliuszBrussy** [comment]
lineItems to unikatowy identyfikator pozycji zamówienia. Jest on przypisany do danej pozycji zamówienia. W przytoczonym przypadku - Klient kupił kilka przedmiotów oddzielnie, a następnie sfinalizował zamówienie w jednej płatności. Nie ma tutaj nieprawidłowości.

**Comment by bacok** [comment]
@AureliuszBrussy ok, tylko te "kilka przedmiotów" dotyczy tej samej aukcji. Wszystkie 5 pozycji pochodzi z tego samego numeru aukcji. "Klient kupił kilka przedmiotów oddzielnie, a następnie sfinalizował zamówienie w jednej płatności." - czy tutaj nie powinno być innego identyfikatora zamówienia jeśli to byłyby osobne zakupy? :wink:

**Comment by AureliuszBrussy** [comment]
Może zdażyć się sytuacja, że Klient dokona kilku osobnych aktów zakupowych, a mimo to finalizuje i opłaci te akty zakupowe w pojedynczym zamówieniu.

**Comment by bacok** [comment]
Na logikę powinien przyjść jeden element w tablicy, ale skoro tak to działa to dziękuję za wyjaśnienie. Zamykam.
