### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by masterix** [allegro/allegro-api#3882]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Korzystając z artkykułu: https://developer.allegro.pl/getting_started/
Nie mogę się uzyskać tokenu, odpowiedź to zawsze: {"error":"Unauthorized","error_description":"Unauthorized"}
Próbowałem zarówno do sandbox jak i prod.
clientId: ca0ec046a6674c769848eb4f618e6338

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać więcej szczegółów na temat problemu?

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że Twój nagłówek Authorization, który wysyłasz przy żądaniu do `https://allegro.pl/auth/oauth/token...`,  jest odpowiednio zakodowany:
`-H ‘Authorization: Basic base64(clientId:secret)’`

Pamiętaj, że dla środowiska testowego należy wygenerować osobną aplikację na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/.

Jeśli problem nadal będzie występować, prześlij proszę przykładowy request w formacie cURL za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą zgłoszenie GitHub #3882, zweryfikujemy to.

**Comment by masterix** [comment]
Dzięki, miałem klucze tylko do prod.
