### ISSUE TITLE
Nowe parametry obowiązkowe wysokość (cm), szerokość (cm)

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#3883]
:bulb: **Sugestia**

Witam, uważam, że wprowadzenie nowych parametrów obowiązkowych typu wysokość (cm), szerokość (cm), gdzie ich wartości są wartościami słownikowymi, zaś przedziały liczbowe są zaszyte w stringu jest krokiem w bardzo złym kierunku; parametry te bardzo utrudniają automatyzację procesu wystawiania ofert, czy choćby późniejszej analizy tychże parametrów. Proponuję wycofać się z (przynajmniej) obowiązkowości tych parametrów jak najszybciej, gdyż z własnego doświadczenia wiem, że takie "stringowe" parametry powodują więcej problemów, niż korzyści. W naszych systemach też mieliśmy takie wartości i wycofaliśmy się z nich bardzo szybko.

**Comment by AureliuszBrussy** [comment]
Dziękuję za sugestię - przekazałem ją do odpowiedniego zespołu odpowiedzialnego za parametry.

**Comment by AureliuszBrussy** [comment]
Czy możesz jeszcze wskazać konkretną kategorię oraz id parametru, którego dotyczy twoja sugestia?

**Comment by adamTynski** [comment]
Tak, proszę:

Id kategorii: 110911
Id parametrów: 207446, 207450

**Comment by adamTynski** [comment]
Jeszcze dodam drobny komentarz. Use case. Mam ponad setkę (delikatnie licząc) istniejących ofert wymagających nowych parametrów (szerokość cm, wysokość cm). Chcąc z automatu zaktualizować takie aukcje muszę
- odczytać wysokość, szerokość produktu oryginalnego,
- przejrzeć wartości parametrów szerokość cm, wysokość cm
- dobrać odpowiednie wartości parametrów na podstawie wartości wyłuskanych ze stringa
Nie wiem, może się nie znam, ale wydaje mi się to niezgodne ze sztuką.

**Comment by AureliuszBrussy** [comment]
Dziękuję za dodatkowe informacje, przekazałem je do odpowiedniego zespołu.

**Comment by AureliuszBrussy** [comment]
@adamTynski po analizie potwierdziliśmy nieoptymalne ustawienie obowiązkowości we wskazanej kategorii (id: 110911). Zdjęliśmy obowiązkowość we wspomnianych wcześniej parametrach.

**Comment by adamTynski** [comment]
Dziękuję :+1:
