### ISSUE TITLE
Produktyzacja coś nie jest dobrze ....

### ISSUE THREAD

**Issue by keczerad** [allegro/allegro-api#3885]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

**trace-id: 1b7ae9c0723e263e**

Produktyzacja bez skopiowanymi parametrami ze znalezionej oferty po EAN do prouktyzacji, produkt znajduje się w innej kategorii. Przekazano tylko product. id = "6901f6e0-5ba9-4df7-b4fa-e2a7d9562d7f"
Efekt aukcja wgrywa się jako szkic.

Jeden z błędów: Brakuje parameteru Przekrój żyły (mm²) (129902) o wartości: \"Inna wartość\" dla oferty z produktem.

Tego parametru nie ma w przekazywanej kategorii 316091 ?!

**trace-id: 30380719cebd0989** 

Produktyzacja ze skopiowanymi parametrami ze znalezionej oferty po EAN do prouktyzacji, produkt znajduje się w innej kategorii. Przekazano product. id = "6901f6e0-5ba9-4df7-b4fa-e2a7d9562d7f" wraz z parametrami z tego produktu. Efekt aukcja wgrywa się jako szkic.

Jeden z błędów: Niepoprawna wartość parametru Przekrój żyły (mm²) (129902) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : \"Inna wartość\"

Tego parametru nie ma w przekazywanej kategorii 316091 ?! 

**trace-id: 6007e4541bb0a8b0** 

Bez produktyzacji, czyli product. id = null, efekt aukcja wgrywa się prawidłowo.

Przy włączonej produktyzacji auckje dodają się jako szkic natomiast przy wyłączonej produktyzacji aukcje dodają się prawidłowo.

**Comment by PrzemyslawLukanowski** [comment]
**trace-id: 1b7ae9c0723e263e
trace-id: 30380719cebd0989**

W tych dwóch przypadkach otrzymujesz prawidłowy komunikat błędu, ponieważ próbujesz powiązać ofertę z produktem, który znajduje się w kategorii 15962, tymczasem jako category.id przekazujesz 316091. Aby prawidłowo powiązać ofertę z produktem, musisz przekazać także prawidłowy numer category.id. Dodatkowo dla trace-id: 30380719cebd0989 przekazujesz parametr 129902, jednak bez uzupełnionej wartości.

**trace-id: 6007e4541bb0a8b0**
Nie do końca rozumiem ten problem, trace-id prowadzi do odpytania GET /sale/offers/{id}. 

> Przy włączonej produktyzacji auckje dodają się jako szkic natomiast przy wyłączonej produktyzacji aukcje dodają się prawidłowo.

Przez POST /sale/offers oferty zawsze tworzą się jako szic i jest to prawidłowe zachowanie.

**Comment by keczerad** [comment]
Kilka pytań :
1. W takim razie czemu nie można skorzystać z produktyzacji jak produkty są w innym kategoriach ?
2. Czemu sprawdzacie przy dodawaniu oferty  parametry z kategorii produktu do której nie należy ?
3. Po co jest produktyzacja jak wy korzystacie z niej z produktów wystawionych przez innych użytkoników a nie z produktów wzrocowych  zrobionych przez Was i przez Was zweryfikowanych ?!

**Comment by PrzemyslawLukanowski** [comment]
1. Produkt w swoich danych, w strukturze JSON, zawiera informacje o prawidłowej kategorii dla tego produktu. Ta kategoria musi zostać uwzględniona także w ofercie, aby nastąpiło poprawne powiązanie. W przeciwnym przypadku wystąpi konflikt, który będzie skutkować m.in. błędami, które otrzymałeś. Podobnie jest na stronie internetowej - przypisując produkt, przypisujesz jednocześnie kategorię dla niego.
2. Które parametry masz na myśli? Te wymienione w zgłoszeniu należą do kategorii produktu.
3. Wszelkie informacje o tym, dlaczego wprowadzamy produktyzację w serwisie, znajdziesz na naszej [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/kategoria/produktyzacja).

**Comment by keczerad** [comment]
1. Przecież ja chcę wystawić ofertę w kategorii nazwijmy ją "A" którą określiłem w zapytaniu, dodatkowo chciałem skorzystać z produktyzacji więc wyszukałem sobie produkt po EAN w Waszej bazie, dla mnie jest to jednoznacze wskazanie tego samego produktu innego bardziej pewnego nie sposobu nie znam . Problem w tym, że ktoś inny ten produkt z takim samym EAN wystawił w innej kategorii nazwijamy ją "B".

2. W jednym zapytaniu są parametry z wymaganymi parametrami w kategorii "A", ale wystawienie aukcji  zwraca błąd, że wymagacie też innych ponieważ produkt wpisany "do produktyzacji"  należy do nazwijmy ją kategorii "B". Co już samo w sobie wydaje się mało logiczne, bo jak nazwać błąd, że wstawiająć produkty do kategorii "A" potrzebujecie mimo wszystko parametrów z kategorii "B"  ? (LOL)

3. No nic myśle sobie w takim razie wstawie parametry, których chcecie z tej kategorii "B" i grzeczny jak nigdy zmieniłem kod przekopiowałem parametry z kategorii "B", po czym Wy zwracacie komunikat, że nie potrzebujecie parametrów z kategorii "B" bo kategoria "A" ich nie wymaga. Tutaj już jest lekka konsternacja, ale jak wspomniałem w Waszym postępowaniu logiki brak.

4. W zasadzie to u góry mógłbym nawet przyjąć do wiadomości, gdyby nie fakt wystawienia tego produktu: 

https://allegro.pl/oferta/forever-dezodorant-100ml-uzywany-towar-9888683467
https://1drv.ms/u/s!AgioGHW0t0gw2FqPqih0pBoBAKUX?e=013ban

który jest Samsungiem S20 a jednocześnie dezodarantem i to Wam pasuje LOL.

**Comment by keczerad** [comment]
Przy różnorakim testowaniu produktyzacji udało mi się "osiągnąć" coś takiego, co świadczy o ułomności Waszych algorytmów. Proszę spojrzeć na markę.

https://1drv.ms/u/s!AgioGHW0t0gw2F4IHtNEWckLW8Jx?e=lfp1lm

**Comment by keczerad** [comment]
Dodam też że produktyzacja taka działa w zasadzie dobrze tylko i wyłącznie jeżeli kategorie produktu znalezionego jest zbieżna z aukcją wystawianą.

**Comment by PrzemyslawLukanowski** [comment]
> Dodam też że produktyzacja taka działa w zasadzie dobrze tylko i wyłącznie jeżeli kategorie produktu znalezionego jest zbieżna z aukcją wystawianą.

I dokładnie takie podejście opisaliśmy [w naszym poradniku](https://developer.allegro.pl/productization/#offer_edit):

> Możesz dodać produkt do oferty w każdym stanie: Draft, Aktywna, Zakończona.
> 
> W requeście PUT /sale/offers/{offer.id} przekaż:
> 
> identyfikator produktu (product.id)
> zgodny z wybranym produktem identyfikator kategorii
> zgodne z wybranym produktem parametry i ich wartości parametrów
> ...

Wszelkie inne próby przypisania produktu będą skutkowały błędami, które przytoczyłeś w poprzednich punktach.

> W zasadzie to u góry mógłbym nawet przyjąć do wiadomości, gdyby nie fakt wystawienia tego produktu

Ofertę wystawiłeś bez przypisanego produktu, dołączyłeś go dopiero podczas edycji oferty. Poprawność parametrów sprawdzamy tylko na etapie wystawiania oferty, ale już nie podczas edycji, aby nie blokować edycji istniejących ofert, które są powiązane z produktem, ale nie mają poprawnych parametrów produktowych.

> Przy różnorakim testowaniu produktyzacji udało mi się "osiągnąć" coś takiego, co świadczy o ułomności Waszych algorytmów. Proszę spojrzeć na markę.

Przypisany produkt nie posiada w naszej bazie żadnej marki (czyli sprzedawca sam może wprowadzić tę wartość), a sam parametr marka to parametr typu słownikowego - czyli to sprzedawca wprowadza tę wartość. Oczywiście powinna to być wartość oddająca faktyczną markę oferowanego przedmiotu.

**Comment by keczerad** [comment]
Tyle tylko że to podejscie jest błędne, skąd wiadomo że pierwszy wystawiajacy aukcje z tym EAN ma rację ? Jeżeli wy bylibyście autorami takiej produktyzacji to można mieć w zasadzie pewno że zrobicie to dobrze, ale w przypadku użytkowników allegro już nie ma, a opisywany przypadkem sprowadzał się do tego że jeden użytkownik od produkcyzaji mial to w ustalonej przez siebie kategorii a inni który mieli ten sam produkt mieli to w innej, nie wiem z czego to wynika aleje jednak można popełnić błąd skutkujący tym ze trzeba tak naprawdę korzystają z produktyzacji opeirać się na pierwszym który doda aukcje.

**Comment by keczerad** [comment]
Nie wiem w czym Wam miała pomóc produktyzacja, ale z perspektywy użytkownika końcowego który kupuje wg mnie ona miała pomóc temu użytkownikowi w znalezieniu szybciej produktu, bo Wy mająć tą informację możecie mu ją dostarczyć w szybki i przystępny sposób ja to tak rozumiem. 

Po czym sprowadzacie produktyzację do jednej kategorii w której ten użytkownik i tak to znajdzie wszystkie produkty (bo to przecież jedna kategoria) , ale z drugiej strony zniechęcacie wystawiajacych aukcję do tejże produktyzacji takimi ograniczeniami co spowoduje zniechęcanie wystawiajacych do produktyzacji no chyba ze ich zmusicie, ale wtedy oni stracą wiecej czasu na szukanie kateogrii gdzie występują produkty wiec im produktyzacja wogole nie pomoga bo stracą na tym wiecej czasu który mogli by przeznaczyć na obsługę sprzedaży. ZONK ! Jednak użytkownik nie dostanie tej inforamacji bo wystawiajacemu nie zechce sie tej informacji dostarczyć.

Gdzie tu jest sens i logika, no chyba ze produktyzacja ma tylko Wam służyć ?

Wg mnie obecnie usprawienieniem obecnej produktyzacji zamiast podawania głupich komunikatów że nie ma jakiś parametrów z kategorii do których wystawiamy, należało by napisać. Taki o to komunikat:

Próbujesz wystawiać aukcje z produktyzacją do kategori "A" a produkt z produktyzacji należy ależy do kategorii "B". Proszę zmienić kategorię.

Tyle w temacie. Komunikaty muszą być proste nawet dla nas programistów. Wystawiania nie logicznych komunikatów z błędami tworzy niepotrzebnie taki wątki i spala zasoby wszystkich na nie potrzebne nasze nerwy wynikające z Waszej logiki i Wasze nerwy wynikające z tego ze nie przeczytaliśmy dokładnie pomocy przeznaczonej defakto dla użytkowników końcowych a nie dla programistów.

Ewentualnie pozwolenie na produktyzację w innych kategoriach bo przecież wy i tak macie tą iformacje i możecie ją wyświetlić użytkownikom allegro.

**Comment by PrzemyslawLukanowski** [comment]
> Wg mnie obecnie usprawienieniem obecnej produktyzacji zamiast podawania głupich komunikatów że nie ma jakiś parametrów z kategorii do których wystawiamy, należało by napisać. Taki o to komunikat:

Wśród komunikatów błędu zwracamy również i taki:

`Offer category doesn't match product category - {categoryId}.`

> Ewentualnie pozwolenie na produktyzację w innych kategoriach bo przecież wy i tak macie tą informacje i możecie ją wyświetlić użytkownikom allegro.

W takiej sytuacji możesz przypisać produkt z innej kategorii już po wystawieniu oferty. Jeżeli uważasz, że kategoria produktu jest błędna, możesz przesłać uwagi przez formularz zgłaszania błędów w produkcie.

**Comment by keczerad** [comment]
Powiem szczerze ze nie widziałem tego komunikatu logi widziałem u kolegi z pracy i wysyałał mi je wiec mogłem nie dojrzeć, ale powiem szczerze ze nie domyślił bym się że chodzi o kategoryzacje.

Ps. Ludzie mówią, że już na allegro nie wystawia się aukcji jak było 20 lat temu a produkty ;).
