### ISSUE TITLE
dodawanie numeru listu do zamówienia

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#3886]
Mam pytanie, 
jak sprawdzić czy numer listu przewozowego został dodany? 
Dodaje zgodnie z wytycznymi : POSTEM na https://api.allegro.pl/order/checkout-forms/ID/shipments
w odpowiedzi otrzymuje uzupełnione:

"id": "string",
"waybill": "string",
"carrierId": "string",
"carrierName": "string",
"lineItems": 
[

    {
        "id": "string"
    }

],
"createdAt": "string"

Ale poprzez panel allegro przy zamówieniu numeru listu nie widać...(Akcje->numery przesyłek)
Czy trzeba jeszcze zmienić status zamówienia? Przez: https://api.{environment}/order/checkout-forms/{id}/fulfillment na "SENT" ?
Obecny to [status] => READY_FOR_PROCESSING

Ogólnie czy trzeba te statusy zmieniać?

**Comment by AureliuszBrussy** [comment]
Poprawnie dodany numer przesyłki powinien być widoczny w Moim Allegro. Skorzystaj także z [GET /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingGET) żeby sprawdzić dodane do zamówienia numery przesyłek. 

Brak zmiany statusu zamówienia nie wpływa na możliwość dodania lub widoczność wprowadzonego numeru przesyłki.

Jeżeli numer przesyłki mimo dodania nie jest widoczny - proszę, podaj trace-id wywołania, w którym przekazałeś ten numer. Sprawdzę to. 

Zmiana statusu zamówień nie jest obligatoryjna, ale zachęcam do korzystania z tej możliwości. Dzięki temu kupujący ma większą wiedzę, co dzieje się z jego zamówieniem. Dodatkowo - jeżeli nie zmienisz statusu realizacji zamówienia (na status “PROCESSING”, “READY_FOR_SHIPMENT”, “SENT”) lub nie dodasz numeru przesyłki do zamówienia, to Kupujący może anulować zamówienie w ciągu 3 dni od zakupu.

**Comment by ButcherFromHell** [comment]
Ok - dziękuje za odpowiedź.
Czy zmiana statusu zamówienia lub dodanie numeru przesyłki skutkuje automatycznym wysłaniem wiadomości @ do kupujacego?

**Comment by AureliuszBrussy** [comment]
Dodanie numeru przesyłki zawsze wiąże się z wysłaniem przez nas powiadomienia do kupującego. W przypadku reszty powiadomień np. dotyczących zmiany statusu zamówienia - to sprzedający w ustawieniach w zakładce [Zamówienia](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) decyduje, jakie automatyczne powiadomienia mamy wysłać do klienta.

**Comment by ButcherFromHell** [comment]
Dziękuje .
