### ISSUE TITLE
Dziwny błąd BAD_REQUEST i pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#3887]
Zauważyłem dzisiaj przy tworzeniu niektórych nowych ofert, dziwny błąd typu BAD_REQUEST

> JSON parse error: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type; nested exception is com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type
at [Source: (PushbackInputStream); line: 1, column: 573] (through reference chain: pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto["updatedAt"])

trace-id dla tego requestu: 2d2c427093f023ed

mogę prosić o wskazówkę po której stronie leży błąd?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję to zgłoszenie z odpowiednim zespołem, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się znaleźć źródło problemu po naszej stronie. Wprowadzimy odpowiednią poprawkę.

**Comment by mindc** [comment]
Kiedy można się spodziewać wprowadzenia poprawki?
Przejrzałem logi, problem dotyczy także aktualizacji istniejących ofert i obejmuje ponad 60% aktywnych ofert...

**Comment by PrzemyslawLukanowski** [comment]
@mindc W ciągu najbliższych dni, do końca tygodnia, powinniśmy rozwiązać problem.

**Comment by anih** [comment]
Chyba coś kombinują, bo i u mnie zaczęły pojawiać się te problemy....

**Comment by PrzemyslawLukanowski** [comment]
@anih Podobnie jak wyżej, planujemy wprowadzić poprawkę w najbliższym czasie.

**Comment by anih** [comment]
Może chociaż jakaś porada, czy można to w jakikolwiek sposób obejść, bo kilka dni bez aktualizacji ofert to jakaś masakra

**Comment by PrzemyslawLukanowski** [comment]
@anih Na tę chwilę jedynym obejściem będzie edycja przez stronę internetową. Poprawkę postaramy się wprowadzić możliwe najszybciej.

**Comment by mindc** [comment]
@PrzemyslawLukanowski Aktualizacja 300k ofert przez stronę, powodzenia

**Comment by PrzemyslawLukanowski** [comment]
Pracujemy nad poprawką, przepraszam za utrudnienia.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
Kilka godzin temu uruchomiłem aktualizację ofert, nie obserwuję już występowania tego błędu.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację - tak, problem już nie powinien występować.
