### ISSUE TITLE
Nieprawidłowy podzbiór HTML - niezgodność z dokumentacją

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#3888]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry
Wołam sobie metodę "sale/offers" i dostaję takie coś w odpowiedzi

`class stdClass#21 (1) {
  public $errors =>
  array(1) {
    [0] =>
    class stdClass#20 (5) {
      public $code =>
      string(16) "VALIDATION_ERROR"
      public $message =>
      string(29) "Nieprawidłowy podzbiór HTML"
      public $details =>
      string(360) "Invalid value: Stół bezcieniowy do doskonałe rozwiązanie do fotografii produktów. Pleksi stołu może być podświetlane od dołu zapewniają idealnie białe tło. Niewielkie rozmiary stołu pozwalają na wygodną pracę i przechowywanie w warunkach domowych. Konstrukcja pozwala ustawiać podłoże stołu, a także rozmieścić odpowiednio oświetlenie."
      public $path =>
      string(40) "description.sections[0].items[0].content"
      public $userMessage =>
      string(29) "Nieprawidłowy podzbiór HTML"
    }
  }
}
`

Patrzę na dokumentację https://developer.allegro.pl/sale/#5-opis-oferty i widzę

Możesz tu użyć określonych znaczników HTML:
h1 - tytuł
h2 - podtytuł
p - akapit
ul - wypunktowanie
ol - wylistowanie
li - element listy
b - pogrubienie.

Więc, używam sobie znacznika aby opis zamiast tak
"Stół bezcieniowy do doskonałe rozwiązanie do fotografii produktów. Pleksi stołu może być podświetlane od dołu zapewniają idealnie białe tło. Niewielkie rozmiary stołu pozwalają na wygodną pracę i przechowywanie w warunkach domowych. Konstrukcja pozwala ustawiać podłoże stołu, a także rozmieścić odpowiednio oświetlenie."

Wyglądał tak

`<p>Stół bezcieniowy do doskonałe rozwiązanie do fotografii produktów. Pleksi stołu może być podświetlane od dołu zapewniają idealnie białe tło. Niewielkie rozmiary stołu pozwalają na wygodną pracę i przechowywanie w warunkach domowych. Konstrukcja pozwala ustawiać podłoże stołu, a także rozmieścić odpowiednio oświetlenie.</p>`

Puszczam request i działa :) Wszystko OK, draft się wystawia.
Teraz proszę o wytłumaczenie, jakim cudem w dokumentacji jest zapis
"Możesz tu użyć określonych znaczników HTML"

Skoro bez użycia znacznika "< p >" nie można wystawić draftu?
Zawsze byłem przekonany że zwrot MOŻESZ jest zwrotem typu "czy to zrobisz czy nie nic się nie stanie" 
Ktoś mi to wytłumaczy?

**Comment by pkrzemo** [comment]
Z dokumentacji...

Najważniejsze zasady:

1)**Treści musisz umieścić w znacznikach HTML**.

... i oczywiście **możesz** tu użyć dowolnego znacznika z listy dozwolonych ;-)

**Comment by PrzemyslawLukanowski** [comment]
@qshop123 Nie potwierdzam niezgodności z dokumentacją. Prócz tego, o czym napisał @pkrzemo, na początku przytoczonego przez Ciebie linku znajdziesz również poniższy zapis: **"możesz korzystać tylko z określonych znaczników HTML"**, a jeszcze niżej załączyliśmy poprawny i niepoprawny zapis struktury:


```
Niepoprawnie:
	{
      "type": "TEXT",
      "content": "opis tekstowy"
	}
```

**Comment by qshop123** [comment]
Heh
Wiedziałem.... po prostu wiedziałem. Z wami nie ma lekko. Jestem osobą zero jedynkową i mam ciężko z wami.
Zatem reasumując zapis w dokumentacji według zasad języka polskiego jest wprowadzający w błąd. 

"Możesz tu użyć określonych znaczników HTML"

Powinno być

"Musisz tu użyć jednego z określonych znaczników HTML"

Ja się na języku polskim tłukę tylko od strony pisania wierszy i wydawania tomików. Mam kolegę profesora filologii polskiej i skieruje do niego zapytanie czy to co jest w dokumentacji jest poprawne. Jak otrzymam od niego informacje powrócę z kontaktem. 
Dziękuję.
