### ISSUE TITLE
Wystawianie oferty i ERR_YOU_HAVE_TO_ACTIVE_CODE

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#3889]
Co oznacza taki błąd podczas wykonywania POST /sale/offers?

{"code":"VALIDATION_ERROR","message":"ERR_YOU_HAVE_TO_ACTIVE_CODE","details":"","path":null,"userMessage":""}

trace-id: aa079d2b48216fa5

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Błąd oznacza, że użytkownik nie ma aktywowanej sprzedaży na koncie.
