### ISSUE TITLE
Pytanie o listing

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3890]
Proszę o sprawdzenie wywołania:
"{\"trace-id\":\"2dd7b818aafba578\"
z mojego logu wynika, że zapytałem o kategorię 18698:
https://api.allegro.pl/offers/listing?fallback=false&searchMode=REGULAR&include=-filters&include=-sort&include=-categories&category.id=18698&sort=-popularity
w wyniku ma oferty z innymi kategoriami.

Z czego to wynika?
KF

**Comment by kfijalko** [comment]
Dziś na spokojnie pobrałem próbkę 6mln ofert i wśród nich 76k pojawiło sią na listingach gdzie kategoria listingu nie zgadza się z kategorią oferty.
Sprawdziłem kilka ofert ręcznie na froncie allegro.pl i kategoria oferty zapisana w ofercie zgadza się z tą wyświetlaną na froncie.
Czyli oferta pojawiła się na listingu nieprawidłowej kategorii.
Pytania:
Czy to jest błąd?
Czy oferta jest w trakcie przepięcia pomiędzy kategoriami (zmiany kategorii) [np. baza ofert się zaktualizowała a baza wyszukiwania jeszcze nie]?
Jeżeli jest to celowe/prawidłowe działanie, to czy mogę przyjąć, że prawidłowa jest kategoria zapisana w ofercie?

Taki poranne przemyślenia.
Poproszę o odpowiedzi.
KF

**Comment by kfijalko** [comment]
Jest jeszcze jeden trop: może źle konstruuje url?
Może niepotrzebnie dodaję:
fallback=false
searchMode=REGULAR

Chcę uzyskać listing dla konkretnej kategorii i sortowania.

**Comment by kfijalko** [comment]
Jeszcze jedna statystyka. Sprawdziłem dla których kategorii występują takie sytuacje:
{ "_id" : "259708", "count" : 1201 }
{ "_id" : "252374", "count" : 798 }
{ "_id" : "253799", "count" : 781 }
{ "_id" : "253285", "count" : 747 }
{ "_id" : "253775", "count" : 712 }
{ "_id" : "256656", "count" : 705 }
{ "_id" : "259747", "count" : 698 }
{ "_id" : "253270", "count" : 657 }
{ "_id" : "253264", "count" : 655 }
{ "_id" : "257360", "count" : 651 }
{ "_id" : "253238", "count" : 636 }
{ "_id" : "252664", "count" : 610 }
{ "_id" : "256660", "count" : 610 }
{ "_id" : "259628", "count" : 597 }
{ "_id" : "259712", "count" : 594 }
{ "_id" : "253813", "count" : 594 }
{ "_id" : "253265", "count" : 551 }
{ "_id" : "255919", "count" : 543 }
{ "_id" : "19034", "count" : 540 }
{ "_id" : "253243", "count" : 533 }
... 729 kategorii zawiera "nieprawidłowe" oferty na listingach / z 1707 listingów kategorii, które pobrałem.
Czyli na listingu dla kategorii 259708, 1201 ofert ma inną kategorię niż listing.
Wolałbym, żeby się okazało, że źle zadaję pytanie. Przy 6000 ofert jakie zwraca listing, udział ofert "nieprawidłowych" jest całkiem duży.

**Comment by kfijalko** [comment]
Więcej już nie będę drążył. Proszę o Wasze zdanie na ten temat.
KF

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to już z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Potwierdzam występowanie błędu. Problem jest związany z tym, że niektóre oferty przeniesione do innej kategorii wciąż mogą być wyszukiwane w poprzedniej. Pracujemy nad rozwiązaniem tego problemu.

**Comment by kfijalko** [comment]
@AureliuszBrussy proszę jeszcze o odpowiedź na takie pytanie.
Jak pytam o listing dla kategorii i sortowania, bez szukanej_frazy:
Czy parametry zapytania:
fallback=false
searchMode=REGULAR

pomagają ? przeszkadzają ? n=są ignorowane ?

**Comment by AureliuszBrussy** [comment]
W przypadku braku frazy - parametry fallback i searchMode są ignorowane.

**Comment by kfijalko** [comment]
ok, dziękuję za odp
