### ISSUE TITLE
How to get the price of postage from a given offer or total price (price already with postage) ? Rest API

### ISSUE THREAD

**Issue by lukasprelovsky** [allegro/allegro-api#3891]
Good day,

I have the following problem:

We need to pull the price of postage from the given offerty or total price (price + shipping)

![Screenshot_2020-11-19 Przedmioty użytkownika nikoaz00 - Allegro pl](https://user-images.githubusercontent.com/15073394/99655338-e4908880-2a5b-11eb-8b88-6d0a275bc3c7.png)

price of transport on the offer:
![Screenshot_2020-11-19 MODUŁ MOWY TRAFIC MASTER 8200624041-G 8200624041](https://user-images.githubusercontent.com/15073394/99655490-17d31780-2a5c-11eb-87f5-1e6459e36e3b.png)

It is not defined in offerte API:

![cekuj](https://user-images.githubusercontent.com/15073394/99655713-5668d200-2a5c-11eb-9569-70994f2db799.png)

we read the complete documentation at
https://developer.allegro.pl/en/news/2018-08-14-cenniki_dostawy/

but we did not find an answer to the solution.

It seems that if the offerer has not filled in the price of transport on the product, it is not possible to get it.

Is there another way?

Thanks for the reply

**Comment by PrzemyslawLukanowski** [comment]
Each offer should have a defined delivery price list. We return the ID of the assigned delivery price list in the place that you pointed - delivery.shippingRates. Via [GET /sale/shipping-rates/{id}](https://developer.allegro.pl/documentation/#operation/getShippingRatesSetUsingGET) you can retrieve details of the given shipping rates set and you can check there the amount for the given delivery methods.  You can add values from those fields to your offer price, which we return in sellingMode.price.amount field in response to [GET /sale/offers/{id}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by PrzemyslawLukanowski** [comment]
Could you please send us the offer.id with the missing shippingRate.id?

**Comment by lukasprelovsky** [comment]
Hi, thanks.

Offer id: 4906659800

**Comment by lukasprelovsky** [comment]
> 
> 
> Could you please send us the offer.id with the missing shippingRate.id?

Hi, thanks.

Offer id: 4906659800

**Comment by PrzemyslawLukanowski** [comment]
This offer was created in 2014 - at this time we don't require a shipping rate assigned to an offer. The offer has never been ended since then and also no changes have been provided - that's why we never return validation error. I assume that the rest of the problematic offers were also created a few years ago. Right now you can add shippingRates.id via PUT /sale/offers/{id} to fill this data.

**Comment by lukasprelovsky** [comment]
> 
> 
> This offer was created in 2014 - at this time we don't require a shipping rate assigned to an offer. The offer has never been ended since then and also no changes have been provided - that's why we never return validation error. I assume that the rest of the problematic offers were also created a few years ago. Right now you can add shippingRates.id via PUT /sale/offers/{id} to fill this data.

Thank you for your response

Unfortunately, we can't do anything with these old offers, we're just pulling data from the supplier.

well thank you.
