### ISSUE TITLE
Pytanie o regulamin

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3892]
W obecnym regulaminie interesuje mnie punkt:
https://developer.allegro.pl/rules/
4.1.b

Z kim mógłbym o tym porozmawiać?

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i powołaj się na zgłoszenie GitHub #432.

**Comment by kfijalko** [comment]
Dziękuję, napisałem.
KF
