### ISSUE TITLE
Listingi - blokada 429

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#3893]
Musze przyznać, że w całej integracji 429 stanowi dla mnie poważny problem.
Do wczoraj bez problemu pobierałem dane.
Dziś ciągle dostaję 429.
Z mojego logu wynika, że 429 dostałem po 6527 requestach.
{ "httpCode" : [ 429, "READ_CATEGORY_LISTING" ], "count" : 9 }
{ "httpCode" : [ 200, "READ_CATEGORY_LISTING" ], "count" : 6527 }

Czy coś się zmieniło po Waszej stronie?
Czy moglibyście zerknąć na moje wywołania i powiedzieć co jest nie tak?
Może trafiłem na czarną listę ;)
Przykładowy trace-id:562094c1106dd2e3

KF

**Comment by AureliuszBrussy** [comment]
Otrzymałeś 429 ponieważ Twoje działania mocno wykroczyły poza standardowe działanie użytkownika. Może tak się zdarzyć w przypadku np. ciągłego odpytywanie listingów. Aby zapobiec podobnym sytuacjom w przyszłości - musisz ograniczyć wykonywanie podobnych requestów.
