### ISSUE TITLE
Błąd zmiany ceny

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3894]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: 886f1c533f85606f
inny przykład: 25f07bae24f0559e
(jest tego dużo więcej)

U jednego z klientów dostajemy taki błąd po zmianie ceny zasobem do edycji masowej. Po odpytaniu zasobu 'Change price command detailed report' dostajemy status failed z takimi błędami:

```json
[ { "code" : "OFFER_PRICE_CHANGE_ERROR", "message" : "Error when update offer price.", "details" : null, "path" : null, "userMessage" : "Błąd podczas zmiany ceny." } ]
```

Co może być powodem braku powodzenia zmiany ceny, bo zwykle pisze uzupełnij parametry itp.?

**Comment by PrzemyslawLukanowski** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu, wrócę z odpowiedzią.

**Comment by AnimalDEV** [comment]
Coś już wiadomo? Problem nie występuje, ale klient chciał abyśmy mu przekazali odpowiedź od was dlaczego tak się działo.

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym jeszcze o cierpliwość, weryfikujemy, co spowodowało błąd. Wrócę z informację.

**Comment by PrzemyslawLukanowski** [comment]
@AnimalDEV Powodem błędu była utrata autoryzacji przez użytkownika w trakcie przetwarzania requestu. Planujemy wprowadzić rozwiązanie, które wyeliminuje podobne sytuacje.
