### ISSUE TITLE
niedziałająca własna wartość parametru "ambiguousValueId"

### ISSUE THREAD

**Issue by mariuszthecoder** [allegro/allegro-api#3897]
- [X] z zasobem REST API
 - [X] ze środowiskiem testowym
być może środowisko produkcyjne, ale do niego nie doszedłem.

:beetle: **Opis**
https://developer.allegro.pl/sale/#w%c5%82asna-warto%c5%9b%c4%87-parametru

zgodnie z w/w powinienem móc dodać własną wartość parametru 
      "name": "Marka",
      "options": {
        "ambiguousValueId": "1019_130",
        "customValuesEnabled": true,
      }
podając do wartości parametru klucze "id, valuesIds, values", natomiast odpowiedź mówi, że API nie może zrealizować zapytania.
Proszę o pomoc

request URL:
/sale/product-offers
request data:
{'product': {'category': {'id': '51148'},  'parameters': [{'id': '225693', 'values': ['4009803067445']}, {'id': '1019', 'valuesIds': ['1019_130'], 'values': ['Revell']}] ... }

RESPONSE:<Response [422]>
RESPONSE:{'errors': [{'code': 'InvalidDictionaryParameter', 'message': 'Unprocessable Entity', 'details': None, 'path': '', 'userMessage': 'Given dictionary parameter valuesIds `1019_130` in parameter `1019` indicates different value than `values` field.'}]}

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się powtórzyć błąd na środowisku testowym, na produkcji request przechodzi prawidłowo. Zweryfikuję to i wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Błąd powodowało to, że marka `Revell`, którą próbujesz dodać, jest już dostępna jako jedna z wartości parametru - konkretnie `1019_90`.

**Comment by mariuszthecoder** [comment]
Mam rozumieć, że na sandbox marka jest już oficjalnie dodana, a na produkcji jeszcze nie?
Zmodyfikuję swój kod tak, żeby obsługiwać obydwa przypadki.
Dzięki!

**Comment by PrzemyslawLukanowski** [comment]
Na produkcji marka również jest widoczna, różnica w odpowiedzi wynikała jednak z odmiennego zachowania naszego mechanizmu w środowisku testowym.
