### ISSUE TITLE
Parametry zależne - więcej przykładów

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#3899]
Dzień dobry,
czy prócz kategorii "Klipsy" są inne, w których można przetestować działanie parametrów zależnych? Np. warunkowego ukrywania/opcjonalności? Bardzo by się przydało więcej przypadków.

**Comment by PrzemyslawLukanowski** [comment]
Warunkową obowiązkowość sprawdzisz w kategoariach `121724`, `124887`, `13592` i `19630` na przykładzie parametrów "Stan" i " ISBN". Nie mamy jeszcze dostępnych pierwszych kategorii i parametrów dla opcjonalnego ukrywania.
