### ISSUE TITLE
Niemożliwość zmiany liczby sztuk

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#39]
Aukcja:

http://allegro.pl/show_item.php?item=6601318051

Zarówno przez frontend jak i przez API nie jestem w stanie zmienić liczby sztuk na 2.

Zawsze dostaje: 

`Podczas modyfikowania oferty wystąpiły błędy: Niepoprawna liczba sztuk`

Sprawdzałem to np. dla aukcji:

http://allegro.pl/show_item.php?item=7093303507.

Z 5 mogłem spokojnie zmienić na 4, 3, lecz już nie na 1 lub 2.

Dla:

http://allegro.pl/show_item.php?item=6951873099

Już 3 nie jest dopuszczalne.

O co chodzi?

Dodatkowo, co znaczy szybko pojawiający się i znikający box z tekstem:

`Od momentu wystawienia oferty minęło ponad 12 godzin, dlatego nie możesz zmienić niektórych danych.`

**Comment by PawelTaberski** [comment]
Jaką metodą starasz się zmienić ilość przedmiotów. Jeśli doChangeItemFields to czy na pewno edytujesz fid5. Próbowałeś może zmienić ilość metodą doChangeQuantityItem?

**Comment by pgasidlo** [comment]
Zawsze używałem doChangeItemFields i nie miałem nigdy z tym problemów. Nie testowałem ostatnio doChangeQuantityItem.

Druga sprawa - ten błąd wam wyskakuje w panelu WWW. Czyli zwykły śmiertelnik używający tylko waszej strony też tego nie może zmienić.

**Comment by pgasidlo** [comment]
Inne aukcje, z którymi mam problem ze zmianą:

7060509205
6872106490
6956199510
6987710314
7061663190
7061763378
7062502762
7062726026
7063412090
7060787504
7062412776
7063179660
6601318051
6951873099
7062619835
7093303507

**Comment by PawelTaberski** [comment]
Przetestowałem na swoich ofertach i zmiana ilości sztuk przebiega poprawnie. Jednakże u Ciebie musi występować jakiś problem, bo z tego co napisałeś pamiętasz o tym, aby brać pod uwagę liczbę przedmiotów dotychczas sprzedanych w danej ofercie. Zgłosiłem sprawę do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by pgasidlo** [comment]
Wszystkie te oferty trwają już bardzo długo. Nie mam problemów z nowymi aukcjami.

```
+------------+-----------+---------------------+--------------------+
| item_id    | seller_id | item_time_start     | item_quantity_sold |
+------------+-----------+---------------------+--------------------+
| 6601318051 |  44294360 | 2016-11-11 20:16:31 |                  0 |                                                                                                  
| 6872106490 |  44294360 | 2017-06-27 16:00:25 |                  0 |
| 6951873099 |  44294360 | 2017-09-07 11:07:26 |                  0 |
| 6956199510 |  44294360 | 2017-09-11 12:08:34 |                  0 |
| 6987710314 |  44294360 | 2017-10-05 01:53:12 |                  8 |
| 7060509205 |  44294360 | 2017-11-23 14:39:41 |                  0 |
| 7060787504 |  44294360 | 2017-11-23 17:37:33 |                  0 |
| 7061663190 |  44294360 | 2017-11-24 08:14:21 |                  0 |
| 7061763378 |  44294360 | 2017-11-24 09:47:29 |                  1 |
| 7062412776 |  44294360 | 2017-11-24 17:38:03 |                  0 |
| 7062502762 |  44294360 | 2017-11-24 18:48:47 |                  0 |
| 7062619835 |  44294360 | 2017-11-24 20:13:24 |                  0 |
| 7062726026 |  44294360 | 2017-11-24 21:11:05 |                  0 |
| 7063179660 |  44294360 | 2017-11-25 08:36:17 |                  0 |
| 7063412090 |  44294360 | 2017-11-25 12:26:20 |                  0 |
| 7093303507 |  44294360 | 2017-12-16 01:02:14 |                  0 |
+------------+-----------+---------------------+--------------------+
```

**Comment by PawelTaberski** [comment]
Rozumiem sprawę, tak jak mówiłem przekazałem do odpowiedniego zespołu, proszę o cierpliwość. Powyższe dane zaraz im podeślę.

**Comment by pgasidlo** [comment]
Czy coś wiadomo, po 51 dniach od mojego ustatniego kontaktu? Aktualnie nie mogłem czekać i zamknąłem aukcje, na których nie miałem sprzedaży w ciągu 30 dni, ale zostało kilka:

```
+------------+-----------+---------------------+--------------------+
| item_id    | seller_id | item_time_start     | item_quantity_sold |
+------------+-----------+---------------------+--------------------+
| 6872085043 |  44294360 | 2017-06-27 15:34:50 |                  5 |                                                                                                                                                                                                                
| 7028729085 |  44294360 | 2017-11-02 14:34:12 |                  2 |
| 7062968246 |  44294360 | 2017-11-25 00:31:21 |                  3 |
| 7208122258 |  44294360 | 2018-02-27 19:07:34 |                  1 |
+------------+-----------+---------------------+--------------------+
```

**Comment by PawelTaberski** [comment]
Otrzymałem informacje, że problem ze zmianą liczby sztuk nie powinien już występować. Czy w dalszym ciągu na pozostałych ofertach masz ciągle ten problem?

**Comment by pgasidlo** [comment]
Tak, to aktualne dane.

**Comment by PawelTaberski** [comment]
Czyli, przy edycji liczby sztuk przy tych ofertach ciągle występuje ten sam problem, tak?

**Comment by pgasidlo** [comment]
Tak. Świeża aukcja (wczoraj wystawiona 2018-04-25 07:22:28)

`7311531616`

Nikt nie kupił, a przy edycji i próbie zmiany 5 -> 1 dostaję w panelu allegro błąd:

`Podczas modyfikowania oferty wystąpiły błędy: Niepoprawna liczba sztuk`

**Comment by PawelTaberski** [comment]
Przekazałem Pana informacje do odpowiedniego zespołu, proszę o jeszcze trochę cierpliwości.

**Comment by PawelTaberski** [comment]
Otrzymałem informację, że problemem jest spowodowany przez zbyt szybką zmianę ceny po zmianie ilości, co powoduje nadpisanie oferty. Oferty poprawimy.
