### ISSUE TITLE
Brak zwracanego kodu EAN w SOAP API

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#390]
Zauważyliśmy, że w SOAP API nie jest zwracany kod EAN dla metody doGetItemsInfo: http://allegro.pl/webapi/documentation.php/show/id,52 . Pola (bo są 2 o dziwo) o nazwie itEan są puste. Możliwe że w innych metodach SOAP API dzieje się podobnie. W przypadku REST API oczywiście zwraca poprawnie wynik. Jako przykład podaje aukcje z sandboxa: https://allegro.pl.allegrosandbox.pl/kotlety-mielone-z-kurczaka-370g-i6205397217.html choć problem występuje także na produkcji

**Comment by KrzysztofLukanowski** [comment]
Cześć, czy w request określiłeś wartość 1 dla parametru getEan?

**Comment by kormichu** [comment]
Ehh... :)
