### ISSUE TITLE
Pobieranie listy wystawionych przedmiotów - Internal server error (500)

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#3900]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

```
curl --request GET \
  --url https://api.allegro.pl/sale/offers \
  --header 'accept: application/vnd.allegro.public.v1+json' \
  --header 'authorization: Bearer (tu wstawilem access_token zwrocony z https://allegro.pl/auth/oauth/token)'
```

`trace-id: e3b62c01a95e4658`

Czy macie obecnie jakiś problem, czy to wina mojego zapytania? Nie działa ani na sandboxie ani na produkcji

![image](https://user-images.githubusercontent.com/3116731/99837156-66b9a380-2b67-11eb-9572-2b903eba5f3f.png)

**Comment by PrzemyslawLukanowski** [comment]
Czy na pewno używasz tokena wygenerowanego w drodze [code](https://developer.allegro.pl/auth/#app)lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow? W [dokumentacji](https://developer.allegro.pl/documentation/#section/Authentication), przy każdym zasobie, znajdziesz odpowiednie oznaczenie, jakiego typu autoryzacji musisz użyć:

- bearer-token-for-user - autoryzacja code lub device,
- bearer-token-for-application - autoryzacja client_credentials, bez kontekstu użytkownika, dostęp tylko do wybranych zasóbów.

**Comment by bugproof** [comment]
@PrzemyslawLukanowski  tak, używam client id + client secret https://developer.allegro.pl/auth/#clientCredentialsFlow

**Comment by PrzemyslawLukanowski** [comment]
Możesz, musisz jednak użyć autoryzacji typu [device](https://developer.allegro.pl/auth/#DeviceFlow). W Twoim przypadku korzystasz z client_credentials.

**Comment by bugproof** [comment]
Wszystko działa. Szkoda tylko, że nie działa z client_credentials.
