### ISSUE TITLE
VPN używać czy nie

### ISSUE THREAD

**Issue by sieciii** [allegro/allegro-api#3901]
Czy można używać sieci VPN na platformie allegro ? Podobno zakazu nie ma ,ale czy moje konto nie będzie powiązane z innym użytkownikiem sieci VPN ? Przecież ta sieć ma jeden serwer i wszyscy użytkownicy mają to samo ip?

**Comment by AureliuszBrussy** [comment]
Korzystanie z VPN w ramach Allegro nie jest zabronione. W kontekście API może mieć to jednak takie konsekwencje, że wielu użytkowników z tym samym adresem IP mogą przekroczyć limit zwyczajnego ruchu, przez co możemy np. nałożyć tymczasowe ograniczenia ilości requestów.
