### ISSUE TITLE
Błąd zakańczania akcji

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3902]
Występuje problem: 
 - [ X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Próbuję zakończyć aukcje (na produkcji jak i sandbox) lecz za każdym razem błąd:
{"errors":[{"code":"VALIDATION_ERROR","message":"must not be empty","details":"Invalid value: null","path":"offerCriteria[0].offers[].id","userMessage":"must not be empty"}]}

przykładowe polecenie:

UUID: 4e0329ac-b1fd-4cda-87f9-62d4fc93bbf2
{"offerCriteria":[{"offers":[{"Id":"9898909341"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END"}}

**Comment by PrzemyslawLukanowski** [comment]
Pole "id" oferty musisz przekazać małymi literami, błąd powoduje właśnie "Id" zamiast "id".

**Comment by paafcioc22** [comment]
Dzięki! Taki szczegół mi umknął ;/. 
Teraz mam problem ze wzowieniem tej oferty : 
{"offerCriteria":[{"offers":[{"id":"9898909341"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}
Po wykonaniu  GET /sale/offers/promo-options-commands/{commandId}
, dostaję zwrotke:
{"errors":[{"code":"ERROR","message":"Command abfd64ea-b237-4552-8c46-6a6c795e5cd6 does not exist.","details":null,"path":null,"userMessage":"Batch modification command does not exist."}]}

Edit
zauważyłem, że po chwili aukcja wznowiona.

**Comment by PrzemyslawLukanowski** [comment]
> Po wykonaniu GET /sale/offers/promo-options-commands/{commandId}
> , dostaję zwrotke:
> {"errors":[{"code":"ERROR","message":"Command abfd64ea-b237-4552-8c46-6a6c795e5cd6 does not exist.","details":null,"path":null,"userMessage":"Batch modification command does not exist."}]}

Tutaj dodatkowo chcesz odpytać status publikacją za pomocą niewłaściwego zasobu - GET /sale/offers/promo-options-commands/{commandId} służy do odpytania statusu przypisania pakietu promowania do oferty.
