### ISSUE TITLE
/sale/offer-modification-command i usuwanie

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#3903]
W jaki sposób odpiąć coś za pomocą /sale/offer-modification-commands/{commandId}? Czy np. dla odpięcia cennika hurtowego zadziała podanie w "id" null?

`"discounts": {
   "wholesalePriceList": {
      "id": null
   }
}
`

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku taki request zadziała, opisaliśmy go w [naszym poradniku](https://developer.allegro.pl/offer_bundles/#32). Nie zawsze jednak się to sprawdzi - nie wspieramy takiego działania dla cennika dostawy (shipping rate), który jest wymagany dla każdej oferty.

**Comment by tomylee0** [comment]
Czy w razie potrzeby uda się w ten sposób usunąć stawkę VAT?

    "modification": {
        “payments": {
            "tax": {
               "percentage": null
            }      
        }
   }

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz w ten sposób usunąć stawkę VAT, ale pamiętaj, aby dodatkowo w polu **payments.invoice** określić rodzaj faktury przypisany do oferty.

**Comment by tomylee0** [comment]
Dzięki za pomoc. Pozdrawiam.
