### ISSUE TITLE
Jakie maksymalnie danne mozno otrzymac z REST API na Allegro.pl ?

### ISSUE THREAD

**Issue by srotas24** [allegro/allegro-api#3905]
Jakie maksymalnie danne mozno otrzymac z REST API na Allegro.pl ? Bo otrzymalem tyku null albo error.

![image](https://user-images.githubusercontent.com/64946896/99947982-6bf23a80-2d81-11eb-8641-ce768b93d05a.png)

**Comment by AureliuszBrussy** [comment]
Poprzez [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) pobierzesz tylko dane oferty jako użytkownik zautoryzowany (właściciel oferty). Błąd wskazuje na to, że próbujesz pobrać szczegóły oferty innego użytkownika.  Oferty innych użytkowników możesz wyszukiwać i przeglądać za pomocą [GET /offers/listing](https://developer.allegro.pl/redoc/redoc-static.html#operation/getListing).

**Comment by srotas24** [comment]
Jakim sposobem moglbym otrzymac dane drugiego sprzedawcy (nazwa, cena, dostawa, kategorija, parametry, o sprzedajoncym, opis, stan, filtry ?

**Comment by AureliuszBrussy** [comment]
Część z tych danych otrzymasz właśnie w odpowiedni na żądanie [GET /offers/listing](https://developer.allegro.pl/redoc/redoc-static.html#operation/getListing). Konkretnie chodzi o nazwę, kategorię, cenę, liczbę sztuk. Możesz także skorzystać z określonych w odpowiedzi filtrów (sekcja **filters**). Więcej informacji o tym zasobie znajdziesz w naszym [poradniku](https://developer.allegro.pl/listing/).

**Comment by srotas24** [comment]
Alie niemoga nigdzie nalesc informacyji o "opise" i "parametry".

**Comment by AureliuszBrussy** [comment]
Takie dane o ofercie możesz pobrać jedynie jako zautoryzowany użytkownik, będący właścicielem danej oferty. Tylko wtedy możesz skorzystać z GET /sale/offers/{offerId}.

**Comment by srotas24** [comment]
A jezeli niejestem włascicielem oferty? jakie maksymalnie mozno dany otrzymwac bedonc zautoryzowanym uzytkownikiem.
Dziekuje za otpowiedz.

**Comment by AureliuszBrussy** [comment]
W takiej sytuacji wszystkie możliwe do pobrania dane o ofertach innych sprzedających otrzymasz w odpowiedzi na [GET /offers/listing](https://developer.allegro.pl/redoc/redoc-static.html#operation/getListing). Przez API Allegro nie uda Ci się uzyskać danych ponad te pobrane właśnie poprzez ten zasób.
