### ISSUE TITLE
Integracja allegro z Sky - shop

### ISSUE THREAD

**Issue by Klockownia** [allegro/allegro-api#3906]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

ef:_00D24aE05._5003V7iEac:ref

 Dzień dobry, konfiguruje integrację z Sky-Shop na domenie https://klockownia.eu, dodałam ID Client, Client Secret i dostaje taki komunikat
Jedno z kont Allegro nie zostało zweryfikowane w konfiguracji na stronie Allegro.
Z tego powodu integracja dla tego konta jest NIEAKTYWNA!.
Potwierdź konto Allegro klikając w ikonkę w kolumnie:
"Potwierdzenie Allegro (aplikacji) - Dni do ponownego potwierdzenia"

Otrzymałam wcześniej maila z informacją, że dane firmy na allegro zostały zaakceptowane. Kiedy klikam na ikonkę potwierdzenia ważności aplikacji dostaję stronę allegro z komunikatem: Nie możemy wyświetlić strony i numer błędu aab4e68c8b1f3afa - przy czym jeśli próbuję zrobić to jeszcze raz to generuje się inny kod błędu.

**Comment by AureliuszBrussy** [comment]
Adres przekierowania podany [podczas rejestrowania aplikacji](https://apps.developer.allegro.pl/) na naszej stronie nie jest zgodny z adresem przekierowania, który podany jest w żądaniu (redirect_uri). Sprawdź poprawność tych adresów - muszą być identyczne.
