### ISSUE TITLE
Sprawdzenie EANu dla konkretnej aukcji własnej/obcej

### ISSUE THREAD

**Issue by kompazz** [allegro/allegro-api#3907]
W jaki sposób moge odczytać EAN aukcji? Czy mogę to zrobić dla aukcji wystawionej przez kogoś innego niż ja? 
Nie widzę takiej informacji w wyniku zapytania GET /offers/listing. Z kolei EAN jest w wyniku GET /sale/offers/{offerId} ale tu wymagana jest autoryzacja uzytkownika i zdaje sie ze wyniki są ograniczone do aukcji zautoryzowanego uzytkownika. O ile się nie mylę EAN nie jest też widoczny przez www, tak?

**Comment by AureliuszBrussy** [comment]
Zgadza się, EAN nie jest widoczny w www, nie zwrócimy też tej informacji w odpowiedzi na żądanie [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). EAN możesz pobrać tylko jako zautoryzowany użytkownik korzystając np. z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
