### ISSUE TITLE
zgłaszanie promocji przez API 

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#3908]
Parametry wysłanego requestu API pod adres: https://api.allegro.pl/sale/badges

Array
(
    [campaign] => Array
        (
            [id] => SALE_CATEGORY_BLACKWEEK2020
        )
    [offer] => Array
        (
            [id] => 8857442602
        )
    [prices] => Array
        (
            [bargain] => Array
                (
                    [amount] => 74.79
                    [currency] => PLN
                )
        )
)

a nie chce się zgłosić co robimy źle ? 

dostajemy taką odp:

stdClass Object
(
    [id] => 
    [createdAt] => 2020-11-23T11:30:50.225Z
    [updatedAt] => 2020-11-23T11:30:50.225Z
    [campaign] => stdClass Object
        (
            [id] => SALE_CATEGORY_BLACKWEEK2020
        )

    [offer] => stdClass Object
        (
            [id] => 8857442602
        )

    [prices] => stdClass Object
        (
            [bargain] => stdClass Object
                (
                    [amount] => 74.79
                    [currency] => PLN
                )

            [market] => 
        )

    [purchaseConstraints] => 
    [process] => stdClass Object
        (
            [status] => REQUESTED
            [rejectionReasons] => Array
                (
                )

        )

)

**Comment by AureliuszBrussy** [comment]
Status "**REQUESTED**" w odpowiedzi oznacza, że wniosek czeka na przetworzenie. Widzę, że aktualnie oferta jest już pozytywnie zakwalifikowana do oznaczenia.

**Comment by centrumelektroniki** [comment]
> Status "**REQUESTED**" w odpowiedzi oznacza, że wniosek czeka na przetworzenie. Widzę, że aktualnie oferta jest już pozytywnie zakwalifikowana do oznaczenia.

bo ręcznie ją zgłosiłem w momencie kiedy przez api nie przeszła.

**Comment by AureliuszBrussy** [comment]
Podaj proszę id zgłoszenia do kampanii, który otrzymałeś w odpowiedzi na swoje żądanie poprzez API. Ewentualnie podaj proszę trace-id tego żądania. Pozwoli mi to dokładnie zapoznać się z sytuacją.

**Comment by centrumelektroniki** [comment]
> Podaj proszę id zgłoszenia do kampanii, który otrzymałeś w odpowiedzi na swoje żądanie poprzez API. Ewentualnie podaj proszę trace-id tego żądania. Pozwoli mi to dokładnie zapoznać się z sytuacją.

9c9a84e7-a16b-426f-9ce0-a5be97a57666

**Comment by AureliuszBrussy** [comment]
Kampania "Black Week 23.11-30.11" to kampania typu "**DISCOUNT**" w związku z z tym w requeście powinieneś podać cenę rynkową (w polu **prices.market.amount**). Zgłoszenie zostało przez nas odrzucone ze względu na brak przekazania wartości w tym polu.

**Comment by centrumelektroniki** [comment]
> Kampania "Black Week 23.11-30.11" to kampania typu "**DISCOUNT**" w związku z z tym w requeście powinieneś podać cenę rynkową (w polu **prices.market.amount**). Zgłoszenie zostało przez nas odrzucone ze względu na brak przekazania wartości w tym polu.

stdClass Object
(
    [id] => a54529ba-57d3-4798-8e2f-28235379a728
    [createdAt] => 2020-11-24T08:32:08.557Z
    [updatedAt] => 2020-11-24T08:32:09.286Z
    [campaign] => stdClass Object
        (
            [id] => SALE_CATEGORY_BLACKWEEK2020
        )

    [offer] => stdClass Object
        (
            [id] => 8857442602
        )

    [prices] => stdClass Object
        (
            [bargain] => stdClass Object
                (
                    [amount] => 74.79
                    [currency] => PLN
                )

            [market] => stdClass Object
                (
                    [amount] => 89.00
                    [currency] => PLN
                )

        )

    [purchaseConstraints] => 
    [process] => stdClass Object
        (
            [status] => PROCESSED
            [rejectionReasons] => Array
                (
                )

        )

)

i tak od 30 minut

**Comment by AureliuszBrussy** [comment]
Zgłoszenie zostało przeprocesowane prawidłowo, ale zostało odrzucone (ze względu na brak spełnienia kryteriów kampanii id: SALE_CATEGORY_BLACKWEEK2020). Widzę, że oferta została już zgłoszona do innej kampanii.
