### ISSUE TITLE
Wysyłam z allegro : Poczta - Punkt odbiorcy jest niepoprawny

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#3909]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dla paczki b88e9be6-78fd-4765-a22f-50511227ba8e błąd ; Punkt odbiorcy jest niepoprawny
Edit : 
kolejna paczka ten sam błąd : 81dc8518-2183-4cfa-a350-b88038a27a2e

**Comment by AureliuszBrussy** [comment]
Wyjaśniam ten problem z zespołem odpowiedzialnym za tą funkcjonalność. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@paafcioc22 przepraszam za wydłużony czas odpowiedzi. Problem ten nie powinien już występować.
