### ISSUE TITLE
Dwa sklepy i ten sam numer postBuyFormId. 

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#391]
Korzystamy z SOAP API i zdarzył nam się przypadek dość dziwny. 
Posiadamy dwa konta allegro i na tych dwóch kontach ten sam klient złożył zamówienie, problem pojawia się w tym że Id transakcji jest dokładnie taki sam dla tych dwóch różnych sklepów. Czy to jest normalne? 
Zamówienia są z dwóch różnych dni.

klient: Client:44362465
postBuyFormId: 873972314

Takie informacje są trochę problematyczne, dla naszego systemu ponieważ przeprowadzamy weryfikację po numerze 'postBuyFormId'.
Jakich jeszcze potrzebujecie informacji aby zweryfikować problem?

**Comment by KrzysztofLukanowski** [comment]
Tak, to jest normalna sytuacja, gdy klient wypełnił jeden formularz dostawy dla kilku przedmiotów od różnych sprzedających. W metodzie [doGetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703#method-output), w tablicy struktur postBuyFormItDeals znajdziesz informację dealId, czyli identyfikator konkretnego aktu zakupowego.

**Comment by SoftWareMG** [comment]
OK, dzięki za info, wprowadzę sobie zmiany.
