### ISSUE TITLE
zerowa wartość quantity getPriceModificationCommandTasksStatusesUsingGET

### ISSUE THREAD

**Issue by mariuszthecoder** [allegro/allegro-api#3910]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym

:beetle: **Opis**
próbując zmienić quantity na 0 dostaję błąd, mimo, że przyjmowana wartość dopuszcza zerowe quantity
https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET
modification.value `integer >= 0`

```import uuid
command_id = str(uuid.uuid4())
data = {
    'modification': {
        "changeType": "FIXED",
        "value": 0,
    },
    "offerCriteria": [
        {
            "type": "CONTAINS_OFFERS",
            "offers": [
                {
                    "id": "9829917722"
                },
            ]
        },
    ],
}
response = requests.put(f'{API_ALLEGRO}/sale/offer-quantity-change-commands/{command_id}', headers=get_headers(post=True), json=data)
```
response:
```
{"errors":[{"code":"INCORRECT_QUANTITY_VALUE","message":"Incorrect value of quantity","details":null,"path":"modification.value","userMessage":"Incorrect quantity value."}]}
```
Ewentualnie poproszę o informacje jak wyzerować quantity dla oferty.

**Comment by AureliuszBrussy** [comment]
Wartość 0 jest dopuszczalna w przypadku **modification.changeType=GAIN**. W przypadku modyfikacji typu **"FIXED"** najmniejszą dozwoloną wartością jest 1. Nie ma możliwości wyzerowania liczby sztuk. W przypadku braku przedmiotów na stanie - możesz zakończyć ofertę.

**Comment by mariuszthecoder** [comment]
Ok, ale później takiej zakończonej oferty nie mogę wznowić ani przez API, ani z panelu sprzedawcy.
item id w sandbox: 7678938482

panel:

```
Podczas wznowienia oferty wystąpiły błędy
Nie można dokonać zmian. Możliwe przyczyny: błędny numer oferty, oferta została zakończona, przed chwilą wprowadzałeś zmiany w aukcji - spróbuj ponownie za kilka minut.
```

API: 
```
{'tasks': [{'offer': {'id': '7678938482'}, 'message': 'Could not change offer publication status.', 'status': 'FAIL', 'scheduledAt': '2020-11-23T14:48:26.48Z', 'finishedAt': '2020-11-23T14:48:26.461Z', 'field': 'publication', 'errors': [{'code': 'ERR_YOU_CANT_CHANGE_ITEM', 'message': 'ERR_YOU_CANT_CHANGE_ITEM', 'details': None, 'path': None, 'userMessage': ''}]}]}
```

Obydwu sposobów próbowałem wielokrotnie w odstępach czasu.

**Comment by mariuszthecoder** [comment]
```
requests.put(
        f'{API_ALLEGRO}/sale/offer-publication-commands/{command_id}',
        headers=get_headers(post=True),
        json=data,
    )
```
gdzie
command_id: `UUID('3c7f50b4-2d9d-11eb-9666-185680b01017')`
data:
```
{'publication': {'action': 'ACTIVATE', 'scheduledFor': '2020-11-23T16:05:51Z'}, 'offerCriteria': [{'offers': [{'id': '7678938482'}], 'type': 'CONTAINS_OFFERS'}]}
```
(schodeuledFor na minutę do przodu, żeby do API nie przyszła data wsteczna)

**Comment by AureliuszBrussy** [comment]
Zasoby do operacji grupowych działają asynchronicznie - jeżeli jedna operacja nie zostanie zakończona, to kolejna z automatu skazana jest na niepowodzenie. W Twoim przypadku wcześniej wykonałeś żądanie zakończenia oferty - zadanie to zostało przetworzone, jednak sama oferta jeszcze nie odświeżyły swojego statusu. W międzyczasie wysłałeś kolejne requesty z aktywacją tej oferty - pierwotne zadanie nie zostało jeszcze przetworzone i dlatego dostawałeś komunikaty błędu.
