### ISSUE TITLE
Jak wyświetlić promowane aukcje?

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#3911]
Witam serdecznie,

Ostatnio było trochu zmian w sposobie promowania aukcji i nie mogę teraz znaleźć rozwiązania na wyświetlenie promowanych aukcji. 

GET /sale/offers nie zwraca już informacji o promowaniach/wyróżnieniach.

W jaki sposób mogę pozyskać taką listę?

**Comment by PrzemyslawLukanowski** [comment]
Dla GET /sale/offers nie zwracaliśmy informacji o promowaniu, ale nadal je dostaniesz w odpowiedzi dla GET /sale/offers/{id} w sekcji promotion. Jeśli chodzi o nowe zasoby, pakiety przypisane do oferty sprawdzisz za pomocą [GET /sale/offers/{offerId}/promo-options](https://developer.allegro.pl/documentation/#operation/getOfferPromoOptionsUsingGET). W [naszym poradniku](https://developer.allegro.pl/my_offers/#jak-pobra%c4%87-opcje-promowania-przypisane-do-oferty) znajdziesz więcej informacji o tym zasobie.

**Comment by lukasczg** [comment]
@dlis2010  gdzie uzyskałeś dostęp do api  TecDoc webservice?

**Comment by dlis2010** [comment]
@lukasczg musisz kontaktować się z nimi bezpośrednio. Zdecydowanie **nie jest** to rozwiązanie freeware.
