### ISSUE TITLE
Jak pobrać dane aukcji

### ISSUE THREAD

**Issue by vifus** [allegro/allegro-api#3912]
Jak w tytule, jak się dobrac do szczegołów aukcji mając jej id?

wczesniej robiłem to w taki sposob...

`        $response = $this->getSoapClient()->doShowItemInfoExt(
            $session,
            $auction_id,
            1,
            1,
            1,
            1,
			1,
			1
        );`

**Comment by AureliuszBrussy** [comment]
Zasób o którym piszesz był częścią WebAPI oraz został wyłączony. W REST API Allegro nie udostępniamy odpowiednika tego zasobu. Szczegóły oferty możesz pobrać tylko jako zautoryzowany użytkownik korzystając z [GET
/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by vifus** [comment]
`function getOffer(String $token, Int $offerId): stdClass
{
    $getOfferUrl = "https://api.allegro.pl.allegrosandbox.pl/sale/offers/".$offerId;

    $ch = curl_init($getOfferUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);

    $result = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($result === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }

    $offer = json_decode($result);

    return $offer;
}


function main()
{
    $token = getAccessToken();
    echo getOffer($token, 1005847861);
}

main()`

Cały czas dostaję taki błąd

{"errors":[{"code":"NOT_FOUND","message":"Offer not found. It was deleted, archived or never existed.","details":"NOT_FOUND","path":"/sale/offers/9542866776","userMessage":"Offer not found. It was deleted, archived or never existed."}]}


a aukcje o tym id istnieją.

**Comment by AureliuszBrussy** [comment]
Oferta id 9542866776 istnieje na produkcji, a Ty próbujesz pobrać jej dane w środowisku testowym (ścieżka https://api.allegro.pl.allegrosandbox.pl). Dodatkowo pamiętaj, że aby pobrać dane oferty za pomocą GET /sale/offers/{offerId} musisz być zautoryzowany jako użytkownik, który tą ofertę wystawił.

**Comment by vifus** [comment]
W takim razie w jaki sposób mam pobrac dane oferty innego uzytkownika?

**Comment by AureliuszBrussy** [comment]
@vifus nie możesz pobrać szczegółowych danych oferty innego użytkownika (takich jak np. parametry w ofercie). Jedyny zasób, dzięki któremu pozyskasz podstawowe dane o ofertach jako niezautoryzowany użytkownik to [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). W [naszym poradniku](https://developer.allegro.pl/listing/) opisujemy jak korzystać z tego zasobu.

**Comment by vifus** [comment]
W takim razie jak mielismy importer aukcji z allegro, juz teraz nie ma opcji tego zrobic?

**Comment by AureliuszBrussy** [comment]
Tak, w Allegro REST API nie udostępniamy odpowiednika metody doShowItemInfoExt. Tylko autoryzowany użytkownik może uzyskać szczegóły ofety, które chciałbyś pobrać.
