### ISSUE TITLE
/sale/offers (searchOffersUsingGET) - filtrowanie po parametrach

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#3913]
Czy jest możliwość filtrowania po np. numeru katalogowym części używając https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET ?

![image](https://user-images.githubusercontent.com/3116731/100013549-4d1d9380-2dd5-11eb-8cc2-159eb61dfef3.png)

Czy trzeba dla każdej oferty pobierać osobno szczegóły używając https://developer.allegro.pl/documentation/#operation/getOfferUsingGET i sprawdzać i filtrować w pamięci? 

Gdyby było możliwe, zawsze mniej zapytań do serwera a tak jest x2 i zmniejsza się limit zapytań (9000 zapytań na minutę)

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy możliwości filtrowania ofert po parametrach takich jak numer katalogowy części w GET sale/offers. Alternatywnie możesz posłużyć się polem **external.id** i wprowadzać w nie interesującą Cię wartość - następnie możesz wykorzystywać **external.id** do filtrowania. Wszystkie możliwości filtrowania wymieniliśmy w [naszym poradniku](https://developer.allegro.pl/my_offers/#filtry).

**Comment by bugproof** [comment]
@AureliuszBrussy tak myślę, że lepiej chyba sobie cacheować to gdzieś u siebie używając np. redis, bo tak z external.id i tak trzeba wszystkie oferty pobrać i w pamięci szukać tego co nas interesuje albo po kolei wysyłać zapytania z danym external.id a gdy jest dużo ofert to szybko wyczerpie to limit zapytań (9000 zapytań na minutę) więc ta opcja odpada.

W moim przypadku mam listę ponad 100 000 numerów katalogowych i allegro musiałbym odpytać aż tyle razy aby znaleźć istniejące oferty z takimi numerami.

Najbardziej optymalne rozwiązanie to takie, że pobieram listę wszystkich ofert (maksymalny limit to 1000  w 1 zapytaniu) więc 100 000 w teorii powinno pobrać w 100 zapytaniach tak? I wtedy w pamięci mógłbym sobie to wyfiltrować na podstawie external.id

No albo redis lub cokolwiek innego wtedy łatwo mogę zamienić oe na id i operować już dalej na id.

**Comment by AureliuszBrussy** [comment]
Rozwiązanie o którym piszesz faktycznie może być w Twoim przypadku najbardziej optymalne. Być może inny użytkownik forum spotkał się z podobnym zapotrzebowaniem i będzie w stanie Ci coś podpowiedzieć. 

Maksymalna ilość ofert, którą zwrócimy w odpowiedzi na pojedyncze zapytanie  [GET sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) to 1000, więc jeżeli chcesz uzyskać listę wszystkich 100 000 ofert - minimalna liczba requestów w takim przypadku to właśnie 100.
