### ISSUE TITLE
Jak pobrać aukcje oznaczone etykietą "offerLabelId"

### ISSUE THREAD

**Issue by krzysiu818** [allegro/allegro-api#3914]
Dzień dobry, w jaki sposób odróżnię aukcje oznaczone etykietą po pobraniu ich treści przez REST?
Pozdrawiam

**Comment by AureliuszBrussy** [comment]
W REST API Allegro nie zwracamy pola offerLabelId. Czy możesz wyjaśnić o jakie dokładnie oznaczenia etykietami chodzi?

**Comment by krzysiu818** [comment]
![ETYKIETY](https://user-images.githubusercontent.com/36963378/100069262-d5815000-2e38-11eb-8b8a-542df4abce33.jpg)
Chodzi o przedstawioną na obrazku funkcję filtracji aukcji

**Comment by AureliuszBrussy** [comment]
Etykiety to funkcjonalność występująca tylko w www. Aktualnie nie planujemy wprowadzenia ich w API Allegro. Jeżeli jednak to się zmieni, opublikujemy stosowny komunikat.
