### ISSUE TITLE
Błędy TooManyRequests i Capcha na stronie Allegro mimo nieprzekraczania limitów

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3915]
Witam,

zauważyłem ostatnimi czasy spory problem. Zdarza się, że masowo pojawiają się błędy `TooManyRequests` i dostęp do strony Allegro też jest blokowany przez capcha. Dodałem do swojej aplikacji licznik zapytań na wasze serwery i nie mogę doszukać się w logach liczby zapytań, która mogła by to wywoływać.

Czy coś uległo zmianie, jeżeli chodzi o limity per Client ID? Czy może jednak są jakieś nowe limity nieopisane w poradniku? 

Pamiętam, że kiedyś była mowa o limitach per IP, chyba w kontekście samego uploadu, jednak może przekroczenie limitu uploadu powoduje zablokowanie całego API? Ten problem pojawił się nagle przy podobnej ilości zapytań wykonywanej każdego dnia, nie wykonywałem żadnych zmian ostatnio zwiększających ilość zapytań.

**Comment by AureliuszBrussy** [comment]
Czy możesz przesłać trace-id przykładowego żądania, którego wywołanie zakończyło się błędem TooManyRequests? Pozwoli mi to dokładniej zapoznać się z tą sytuacją.

**Comment by hahyes** [comment]
> Czy możesz przesłać trace-id przykładowego żądania, którego wywołanie zakończyło się błędem TooManyRequests? Pozwoli mi to dokładniej zapoznać się z tą sytuacją.

Sytuacja po paru dniach się ustabilizowała, problem też występował po części z łączem.
