### ISSUE TITLE
Edycja oferty - Niepoprawna liczba sztuk

### ISSUE THREAD

**Issue by darjusz** [allegro/allegro-api#3916]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Ten sam problem co tutaj:
https://github.com/allegro/allegro-api/issues/2349

Problem wciąż występuje, testowane na produkcji. Co ciekawe w panelu Allegro w kolumnie sprzedano jest mniejsza ilość, niż minimalna, która pozwala wprowadzić formularz edycji oferty (prawdopodobnie dlatego, że w tej kolumnie jest sprzedaż z ostatnich 30 dni).

Oferta: 8411548555

Błąd:
![image](https://user-images.githubusercontent.com/15068657/100075222-fa2cf600-2e3f-11eb-86dd-0a672ff43f1b.png)

Dodatkowo po wprowadzeniu odpowiedniej ilości jest ona wyświetlana jako dostępna do zakupu (nie jest pomniejszana o ilość sprzedanych).

Bardzo proszę o rozwiązanie problemu.

**Comment by AureliuszBrussy** [comment]
Rozumiem, że próbowałeś wykonać zmianę liczby sztuk także przez API? Jeżeli tak - czy mógłbyś podać trace-id wywołania, gdzie zmiana liczy sztuk zakończyła się niepowodzeniem? Niestety, ale nie udało mi się znaleźć błędów dotyczących tej oferty w naszych logach.

**Comment by darjusz** [comment]
Trace-Id: 4d76f44a8b09e381

**Comment by AureliuszBrussy** [comment]
Dziękuję za informację. Potwierdzam występowanie problemu - zgłosiłem to do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@darjusz dziękuję za cierpliwość. Problem ten nie powinien już występować.

**Comment by darjusz** [comment]
@AureliuszBrussy potwierdzam, wygląda, że problem ustał
