### ISSUE TITLE
edycja oferty, BAD_REQUEST

### ISSUE THREAD

**Issue by barthoos** [allegro/allegro-api#3918]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

:beetle: **Opis**

Witam,

Kolo godziny 10:15 zaczalem dostawac bledy 400 BAD_REQUEST do dokladnie 247 ofert (z roznych loginow allegro, zakladanych w roznym czasie) podczas edycji oferty. Zastanawiajaca jest "wybiorczosc bledu" - w tym samym czasie wystawilem tysiace ofert.

Przykladowy request:

**URL:** 
https://api.allegro.pl/sale/offers/9934766644

**HEADER:** 
["Authorization: Bearer xx.xx.xx_x_x_x_x","Accept-Language: PL","Content-Type: application/vnd.allegro.public.v1+json","Accept: application/vnd.allegro.public.v1+json;charset=UTF-8"]

PARAMS: 

`{"id":"9934766644","name":"PANASONIC ENELOOP AAA 750 mAh 2100 CYKLI 2SZT","category":{"id":"76371"},"parameters":[{"id":"224017","valuesIds":[],"values":["154013"],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["5410853052678"],"rangeValue":null},{"id":"237190","valuesIds":[],"values":["Panasonic"],"rangeValue":null},{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"237206","valuesIds":[],"values":["inny"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>PANASONIC ENELOOP AAA 750 mAh 2100 CYKLI 2SZT<\/h1>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1199db\/e3e8f41a4208aa7db8d5f935e245"}]},{"items":[{"type":"TEXT","content":"<ul><li><b>Typ:<\/b> Bateria<\/li><li><b>Rozmiar:<\/b> AAA<\/li><li><b>Ogniwo:<\/b> Ni-MH<\/li><li><b>Pojemno\u015b\u0107 akumulatora:<\/b> 750 mAh<\/li><li><b>Napi\u0119cie:<\/b> 1.2 V<\/li><li><b>Liczba w opakowaniu jednostkowym:<\/b> 2<\/li><li><b>\u0141adowarka w zestawie:<\/b> Nie<\/li><li><b>Pasuje do:<\/b> Idealne do telefon&#243;w bezprzewodowych<\/li><li><b>Pozosta\u0142e parametry:<\/b> - Raz na&#322;adowany eneloop zachowuje swoj&#261; energi&#281; przez rok na poziomie do 90 % oraz do 70% po 5 latach- Wysoka wydajno&#347;&#263; r&#243;wnie&#380; przy niskich temperaturach do &#8211;10 &#176;C- 2100 cykli &#322;adowania&#160;<\/li><\/ul>"}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":"26.67","currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"publication":{"republish":false,"duration":null},"delivery":{"shippingRates":{"id":"1e848d01-dcf3-4f8e-920c-1d08945fad56"},"handlingTime":"P2D"},"payments":{"invoice":"WITHOUT_VAT"},"afterSalesServices":{"impliedWarranty":{"id":"4a359bcf-2d11-489c-a406-89c749c6867b"},"returnPolicy":{"id":"adc1844f-9d7a-4bfe-81d8-bea180fcf8aa"},"warranty":{"id":"f7e541ec-1708-49a5-ad89-d095b494fb0a"}},"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"LODZKIE","city":"\u0141\u00f3d\u017c","postCode":"90-057"},"external":{"id":"4781673"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1199db\/e3e8f41a4208aa7db8d5f935e245"}]}`

**RESPONSE:** 

`{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type; nested exception is com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type\n at [Source: (PushbackInputStream); line: 1, column: 564] (through reference chain: pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto[\"updatedAt\"])","details":"","path":"","userMessage":null}]}`

**RESPONSE HEADER:**

`{"0":"HTTP/1.0 400 Bad Request","code":400,"expires":"0","cache-control":"no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":"1; mode=block","pragma":"no-cache","x-frame-options":"DENY","trace-id":"**93a4c36e89b929ec**","date":"Tue, 24 Nov 2020 10:41:19 GMT","x-content-type-options":"nosniff","content-type":"application/json"}`

**Comment by AureliuszBrussy** [comment]
Wiemy o tym problemie - w ciągu najbliższych dni, do końca tygodnia, powinniśmy go rozwiązać.

**Comment by barthoos** [comment]
Ło Panie.. Tydzien czekania na fix, a w systemie mi te oferty robia maly huraganik. Me not happy :(

**Comment by AureliuszBrussy** [comment]
Problem nie powinien już występować.
