### ISSUE TITLE
Bład podczas aktualizacji ofert

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#3919]
Podczas aktualizacji ofert dostaje takie cudo:

    JSON parse error: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type; nested exception is com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto] value failed for JSON property updatedAt due to missing (therefore NULL) value for creator parameter updatedAt which is a non-nullable type at [Source: (PushbackInputStream); line: 1, column: 569] (through reference chain: pl.allegro.finance.promo.promooptions.domain.OfferPromotionsModifyDto["updatedAt"])

O co chodzi w tym komunikacie ?
Dzieje się to np dla oferty: 8858683727

**Comment by AureliuszBrussy** [comment]
Wiemy o tym problemie - rozwiążemy go w ciągu najbliższych dni.

**Comment by AureliuszBrussy** [comment]
Poprawkę postaramy się wprowadzić możliwe najszybciej. Na tę chwilę jedynym obejściem będzie edycja ofert przez stronę internetową.

**Comment by manoos** [comment]
No chyba Pan nie rozumie, wyobraża sobie Pan edycję 2000 ofert przez waszą stronę? 
Potrzebuję dla kilkudziesięciu produktów zmienić czas wysyłki, bo zaraz będziecie wywalać oferty, kupujący zakładać dyskusje...

**Comment by AureliuszBrussy** [comment]
Poprzez stronę możesz grupowo edytować nawet 1000 ofert jednocześnie. W zakładce [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty) zaznacz oferty, w których chcesz wprowadzić zmiany - pojawi się zielona belka dzięki której edytujesz grupowo m.in. czas wysyłki.  Rozumiem, że chciałby Pan dokonać edycji przez API, jednak aktualnie mogę zaproponować tylko takie rozwiązanie.

**Comment by Onixarts** [comment]
Tak dodam od siebie, że nasi klienci również zgłaszają ten problem i nie mogą aktualizować ofert.

**Comment by manoos** [comment]
Zauważyłem, że problem ten pojawia się jak nasz request "nie wnosi zmian" w ofercie allegro. Np jak zmienię cenę to jest ok, jak zmienię opis lub parametr to jest ok.
Ale jak nie zmienię nic lub jak zmienię tylko czas wysyłki to dostaję ten komunikat.

**Comment by AureliuszBrussy** [comment]
@manoos dziękuję za spostrzeżenie. Tak jak wcześniej wspomniałem - postaramy się możliwie najszybciej wdrożyć poprawkę.

**Comment by manoos** [comment]
Na chwilę obecną problem nie występuje.

**Comment by AureliuszBrussy** [comment]
Zgadza się - problem już nie powinien występować.
