### ISSUE TITLE
/after-sales-service-conditions/return-policies

### ISSUE THREAD

**Issue by BusterLodz** [allegro/allegro-api#392]
Czy ktoś podpowie, jak to wywołać?

PS: Dlaczego nie ma odpowiedników w WebAPI????????????

**Comment by KrzysztofLukanowski** [comment]
Tak jak zapowiadaliśmy, wygaszamy [WebAPI](https://github.com/allegro/allegro-api/issues/277). Warunki zwrotów są dostępne od kwietnia ub.r. w REST API. To właśnie REST API rozwijamy, nowe zasoby będziemy publikować wyłącznie w ramach REST.

Id warunków zwrotów możesz pobrać przez [REST API](https://developer.allegro.pl/news/2017-04-05-News_warunki_oferty/). Nowe warunki dodasz jedynie w [zakładce](https://allegro.pl/afterSalesServiceConditions/returnPolicy/).

**Comment by BusterLodz** [comment]
A czy znajdę gdzieś konkretny przykład wywołania w jakimś języku programowania? Np. php??
