### ISSUE TITLE
Access Token Expired po pobraniu kilku aukcji

### ISSUE THREAD

**Issue by meron1122** [allegro/allegro-api#3921]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam aktualny token(wygasa jutro), Pobieram nim kilka checkout forms, po czym po chwili otrzymuje że  "invalid_token". Gdy spróbuję użyć jeszcze raz tego samego tokenu, mogę znowu pobrać kilka aukcji i otrzymać błąd jak wyżej. Czy coś aktualnie dzieje się z api produkcyjnym?

Edit, requesty poszły przez formularz.

**Comment by AureliuszBrussy** [comment]
Aby przeanalizować przyczynę problemu, będziemy potrzebowali konkretny access token -  dlatego prześlij go proszę za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dodatkowo podaj proszę także trace-id wywołania, które zakończyło się błędem invalid_token. W zgłoszeniu dopisz, że problem dotyczy wątku #3921 na GitHubie.

**Comment by meron1122** [comment]
@AureliuszBrussy  poszły requesty z linkiem do githuba na formularz, błąd występuje dla kilku access tokenów.

**Comment by AureliuszBrussy** [comment]
@meron1122 sprawdzimy to, gdy tylko zgłoszenie do nas dotrze.

**Comment by AureliuszBrussy** [comment]
@meron1122 powodem problemów z autoryzacją jest fakt usunięcia przez Państwa wczoraj o godzinie 10:01 klucza aplikacji (Client_id) z poziomu [Zarządzania aplikacjami Allegro](https://apps.developer.allegro.pl/). Badamy jeszcze powód, dlaczego mimo to część requestów po usunięciu klucza zakończyła się powodzeniem.
