### ISSUE TITLE
Sandbox - błąd składania zamówienia

### ISSUE THREAD

**Issue by k-trela** [allegro/allegro-api#3922]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Jest problem podczas składania zamówienia na środowisku testowym. Przy wyborze sposobu dostawy pojawia się komunikat 'Wystąpił błąd. Proszę spróbować później.' - i tak za każdym razem niezależnie od loginu.
W konsoli leci 
t {errorCode: "SERVICE_UNAVAILABLE", name: "UpdatePurchaseException", message: "[503] Failed to update purchase. UpdatePurchaseCom…llback disabled. (failure_type=COMMAND_EXCEPTION)", userMessage: "undefined (Wystąpił błąd.)", traceId: null, …} undefined

GET https://collector-server-nga-test.allegrogroup.com/c5t/ev2?epid=ZoS8Ve1QVqgx3XG5TSjLg9ZHFtII62FWojE0&eseq=18&ecat=Performance&elab=CumulativeLayoutShift&eval=1.4617&sid=CM.991213.tz_pl&suid=MTgzZABVVAwADQVSNGFlNA%253D%253D&xp=%7B%22st%22%3A760596%7D&cid=qu26m8kk-7793-5wxn-9eyd-dhkmuby5gkeh&ctv=63bb6dd&ccts=1606315682355&ws3=LFKrHAfcIIrCtULaGSY1j4mUzFldqGbgP&csts=1606315682390 net::ERR_NAME_NOT_RESOLVED

**Comment by AureliuszBrussy** [comment]
Wiemy o tym problemie - odpowiedni zespół już go analizuje. Wrócę z informacją, gdy już uda się go rozwiązać.

**Comment by k-trela** [comment]
Czy coś już wiadomo?

**Comment by AureliuszBrussy** [comment]
@k-trela błąd kończący się komunikatem: 'Wystąpił błąd. Proszę spróbować później.' oraz brak możliwości złożenia zamówienia wystąpił w tamtym czasie incydentalnie. Z kolei jeżeli chodzi o błąd ERR_NAME_NOT_RESOLVED - wiemy o jego występowaniu, jednak nie jest on bezpośrednio powiązany z brakiem możliwości złożenia zamówienia. 

 Aktualnie złożenie zamówienia w Sandboxie powinno być możliwe.
