### ISSUE TITLE
/sale/offer-modification-commands/{commandId}/tasks - filtrowanie po status=FAIL

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#3924]
Czy jest możliwość filtrowania **modification command detailed report** po status=FAIL? Jeśli nie ma takiej możliwości to chciałbym zgłosić sugestię. Zwykle bowiem wykonując operacje batch'owe pobieramy **summary** i jeśli znajdziemy tam **failed > 0** to chcemy znaleźć numery ofert które się nie udały. Pobierając więc potem **detail report** pomijamy informacje ze statusami **success**. 

Przy wykonywaniu operacji batchowych na koncie które ma kilkadziesiąt tysięcy ofert może to zmniejszyć ruch.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie ma możliwości takiego filtrowania po statusie modyfikacji. Twój pomysł dopisałem do listy sugestii dot. rozwoju API.
