### ISSUE TITLE
Link do aukcji

### ISSUE THREAD

**Issue by romigrabarz** [allegro/allegro-api#3925]
Potrzebuję pobrać link do aukcji.
Jedyny sposób jaki znalazłem w dokumentacji RestAPI to pobranie aukcji metodą **/offers/listing**, gdzie np. podaję tylko **seller.login**, a następnie szukam w wynikach pola vendor.url.
Niestety obiekt **vendor** mam zawsze NULL. Czy to błąd? w jaki sposób mogę pobrać linki do aukcji danego sprzedawcy?

**Comment by hahyes** [comment]
Możesz po prostu utworzyć link do aukcji w postaci `allegro.pl/oferta/{numer_oferty}`. Prościej się chyba nie da. :)

**Comment by AureliuszBrussy** [comment]
W GET /offers/listing nie zwracamy pola z url oferty. Możesz zasugerować się podpowiedzią użytkownika @hahyes.

**Comment by romigrabarz** [comment]
Dzięki, działa 👍 
Wcześniej sugerowałem się linkiem w formie: https://allegro.pl/oferta/tanie-duze-dywany-bcf-150x210cm-klasyczne-7438353523
