### ISSUE TITLE
offer-quantity-change-commands - problemy z losowymi ofertami

### ISSUE THREAD

**Issue by kofston** [allegro/allegro-api#3929]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam!
Mam problem z metodą offer-quantity-change-commands. Zaimplementowałem ją do mojego sklepu aby synchornizować stany magazynowe sklepu z allegro. Głównym problemem jest to że dla niektórych ofert synchronizacja odbywa się i zmiana na allegro przechodzi bez problemu, a dla niektórych ofert po prostu zwraca fail:

Problemem nie powinno być żądanie, bo tak jak napisałem dla niektórych ofert działa a dla niektórych nie (wszystkie oferty są ACTIVE ).
Czy żądanie wykonało się poprawnie sprawdzam : offer-quantity-change-commands/commandId/tasks

Przykładowo dla ofery o ID : 8920434836 zmiana ilości nie działa:
( obecna liczba na allegro wynosi 5, chcę ją zmienić na 3 )
ŻĄDANIE:
OBIEKTY:

```
stdClass Object
(
    [changeType] => FIXED
    [value] => 3
)

stdClass Object
(
    [offers] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 8920434836
                )

        )

    [type] => CONTAINS_OFFERS
)
```

RESPONSE:
```
{"id":"856aedab-cf04-4003-880d-a1fa5f599a77","taskCount":{"total":0,"success":0,"failed":0}}

stdClass Object
(
    [id] => 856aedab-cf04-4003-880d-a1fa5f599a77
    [taskCount] => stdClass Object
        (
            [total] => 1
            [success] => 0
            [failed] => 0
        )

)
```

Sprawdzenie po czasie:

```
stdClass Object
(
    [id] => 856aedab-cf04-4003-880d-a1fa5f599a77
    [taskCount] => stdClass Object
        (
            [total] => 1
            [success] => 0
            [failed] => 1
        )

)
```

**Comment by AureliuszBrussy** [comment]
Nie udało Ci się edytować oferty 8920434836 ze względu na brakującą wartość w parametrze obowiązkowy: EAN (id parametru: 225693). Za pomocą [GET /sale/offers/unfilled-parameters](https://developer.allegro.pl/documentation/#operation/getOffersUnfilledParametersUsingGET_1) możesz sprawdzić, jakie parametry obowiązkowe powinieneś w oferach uzupełnić. Więcej informacji o tym zasobie znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#kategorie-i-parametry).
