### ISSUE TITLE
aktualizacja ofert

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#3930]
Dzień dobry.
Oferty przestały być wznowione z zakonczonych i szkiców. Uważam, że problem dotyczy nowej wersji TecDoc. Na stronie internetowej aktualizacja jest oferowana automatycznie w edycji oferty. Czy można szybko aktualizowac  ofertę przez API?

**Comment by AureliuszBrussy** [comment]
Aktualnie nie udostępniamy mechanizmu pozwalajacego na takie szybkie aktualizowanie ofert danymi produktu, choć w przyszłości chcemy wdrożyć taką funkcjonalność w Allegro API. 

Żebym mógł dokładniej sprawdzić powód braku wznowienia oferty - podaj proszę trace-id przykładowego wywołania.

**Comment by vartaller** [comment]
uuid: ded9f2cb-627b-4e91-8463-f92efa3a1f16

> Aktualnie nie udostępniamy mechanizmu pozwalajacego na takie szybkie aktualizowanie ofert danymi produktu, choć w przyszłości chcemy wdrożyć taką funkcjonalność w Allegro API.
> 
> Żebym mógł dokładniej sprawdzić powód braku wznowienia oferty - podaj proszę trace-id przykładowego wywołania.

**Comment by AureliuszBrussy** [comment]
W tym przypadku nie udało Ci się aktywować oferty, ponieważ w polu **scheduledFor** podajesz datę wsteczną (w przeszłości).

**Comment by vartaller** [comment]
W ogóle tego nie piszę:

```
curl --keepalive-time 5 \
   --connect-timeout 10 \
   --retry 300 \
   --retry-delay 5 -s -X PUT \
   "https://api.allegro.pl/sale/offer-publication-commands/${uuid}" \
   -H "Authorization: Bearer ${token}" \
   -H 'Accept: application/vnd.allegro.public.v1+json' \
   -H 'Content-Type: application/vnd.allegro.public.v1+json' \
   -d "{
               \"publication\":{
                  \"action\":\"ACTIVATE\"
               },
               \"offerCriteria\":[
                  {
                  \"offers\":[
                    {\"id\":\"9959423680/\"}
                  ],
                  \"type\":\"CONTAINS_OFFERS\"
               }
               ]
            }"

```

**Comment by lmajgier** [comment]
> Aktualnie nie udostępniamy mechanizmu pozwalajacego na takie szybkie aktualizowanie ofert danymi produktu, choć w przyszłości chcemy wdrożyć taką funkcjonalność w Allegro API.
> 
> Żebym mógł dokładniej sprawdzić powód braku wznowienia oferty - podaj proszę trace-id przykładowego wywołania.

Wy sobie jaja robicie z użytkowników i sprzedawców na Allegro?
Jak możecie aktualizować wersję tecdoc, dodawać parametr obowiązkowy EAN, nie dając możliwości zmiany ofert przez API.

Mając 200,000 produktów mam zatrudnić kogoś do tego aby przeklikać wszystko? 
Jak to jest, że wprowadzacie zmiany w tecdoc nie informując o tym nikogo?
Nie dajecie w ogole czasy aby sie przygotować. Wystarczyło napisać ze EAN bedzie obowiązkowy z dniem takim i takim to bysmy go dodali...

**Comment by lmajgier** [comment]
A i jeszcze jedno, podczas zmiany produktów pokazuje się błąd
Więcej niż jeden produkt ma ten sam EAN.

Czy ktoś z Was w ogóle przetestował tecedoca przed wdrożeniem?
Czy wiecie że producenci części zmieniają w systemie kod ean? Czy wiecie ze tam jest też syf z tymi eanami? :) 
Wróże Wam taki syf w tych produktach , ze to jest dramat ;)

**Comment by AureliuszBrussy** [comment]
@vartaller z naszych logów wynika, że w payloadzie komendy ded9f2cb-627b-4e91-8463-f92efa3a1f16 podałeś datę w polu **publication.scheduledFor**. Przyślij proszę dokładny request komendy ded9f2cb-627b-4e91-8463-f92efa3a1f16, wraz z pełnym payloadem.  

@lmajgier Czy mógłbyś podać trace-id konkretnego wywołania, gdzie wystąpił taki przypadek?

**Comment by lmajgier** [comment]
Panowie wszystkie oferty, tak mają.
Wprowadzacie aktualizację tecdoc bez dodania metody w api do jej masowej zmiany tak jak macie na froncie. 
Zaraz będziecie mieć wysyp od ludzi którym nie działa nic, bo muszą przeklikać wszystko na nowo.

Nie będe wam wrzucał 200,000 numerów do sprawdzenia.

Chyba sami wiecie, co się wydarzyło w Waszym systemie, wprowadziliscie aktulizację nie przygotowując ani informująć nas o tym

**Comment by bart1337** [comment]
To jest po prostu jakiś cyrk. Mamy produkt(0786878c-60a0-4f72-a673-b22c9282be6a) który ma parametr EAN(225693) z DWIEMA wartościami ["4013872617531", "4013872859610"]. Uprzednio ten produkt nie miał tych EANów w ogóle (albo nie były wymagane do wystawienia). Teraz gdy próbujemy takową ofertę zaktualizować biorąc parametry, które są w produkcie musimy jeszcze dodatkowo walidować samemu czy te parametry aby na pewno dobrze uzupełniliście inaczej wyskoczy błąd "W parametrze EAN(225693) można zdefiniować maksymalnie jedną wartość."

Kolejna głupota, która pokazuje że robicie to na oślep
Produkt(c50871c6-bec5-4aa4-9c54-8d89fe786aa6) marki VDO i tak też było uzupełnione wcześniej a nagle coś wam się ubzdurało i zmieniacie to na "Inny" po czym oczywiście nie da się zmienić stanów czy ceny.

[{"code":"ConstraintViolationException.ValidProduct","message":"Invalid parameter Parts manufacturer (127415) value for offer with product. Value should be \"Inny\".","details":null,"path":"null","userMessage":"Invalid parameter Parts manufacturer (127415) value for offer with product. Value should be \"Inny\"."}] 

Co to w ogóle ma być, że nazwa parametru jest tutaj po angielsku ??? Testujecie nowe funkcjonalności na produkcji ?

**Comment by AureliuszBrussy** [comment]
@bart1337 aby szybciej i łatwiej wyjaśnić Wasze zgłoszenie - wątek ten będziemy kontynuować w najnowyszym zgłoszeniu: #3936.

**Comment by vartaller** [comment]
> @vartaller z naszych logów wynika, że w payloadzie komendy ded9f2cb-627b-4e91-8463-f92efa3a1f16 podałeś datę w polu **publication.scheduledFor**. Przyślij proszę dokładny request komendy ded9f2cb-627b-4e91-8463-f92efa3a1f16, wraz z pełnym payloadem.
> 
> @lmajgier Czy mógłbyś podać trace-id konkretnego wywołania, gdzie wystąpił taki przypadek?

Proszę sprawdzić ten request `65f64e6d-4ed8-4ede-9949-784cf0d84c4b`, dlaczego nie moge wznowic oferte

**Comment by AureliuszBrussy** [comment]
@vartaller w tym przypadku nie udało się wznowić oferty ze względu na niezgodność specyfikacji TecDoc w ofercie z powiązanym produktem.

**Comment by AureliuszBrussy** [comment]
@bart1337 czy mógłbyś jeszcze wskazać konkretną ofertę powiązaną z produktem 0786878c-60a0-4f72-a673-b22c9282be6a, gdzie problem przez Ciebie opisany wystąpił? Rozumiem, że wg Ciebie tylko jedna z wartości EAN jest prawidłowa? Jeżeli tak, to jaka?

**Comment by vartaller** [comment]
> @vartaller w tym przypadku nie udało się wznowić oferty ze względu na niezgodność specyfikacji TecDoc w ofercie z powiązanym produktem. 

Jak mogę zmienić ten parametr dla tej oferty przez Allegro API?

**Comment by AureliuszBrussy** [comment]
@vartaller pobierz aktualne dane produktu poprzez [GET /sale/products/{product.id}](https://developer.allegro.pl/documentation/#operation/getSaleProducts), a następnie nanieś zmiany na ofertę za pomocą [PUT /sale/offers/{offer.id}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT). W [naszym poradniku ](https://developer.allegro.pl/productization/#offer_update) opisujemy ten proces. Pracujemy nad tym, aby taka aktualizacja była łatwiejsza.

**Comment by AureliuszBrussy** [comment]
@vartaller właśnie wdrożyliśmy zmianę, dzięki której możesz skorzystać z [PATCH /sale/product-offers/{offer-id}](https://developer.allegro.pl/documentation/#operation/editProductOffers) żeby w łatwy sposób aktualizować **tecdocSpecification** i **compatibilityList**. Więcej informacji znajdziesz w wątku #3964.
