### ISSUE TITLE
GET /order/refund-claims -  REQUEST

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#3932]
Dziś od rana dostaję odpowiedzi INVALID REQUEST na próby pobrania refund-claimsów

GET https://api.allegro.pl/order/refund-claims/?limit=100 HTTP/1.1
Authorization: Bearer xxxxxxxxx.....xxxxxx
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
Host: api.allegro.pl

HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: d219e9a54fd259d7
date: Sat, 28 Nov 2020 10:05:32 GMT
x-content-type-options: nosniff
content-type: application/json
content-length: 148

{"errors":[{"code":"HttpMessageNotReadableException","message":"Invalid data format.","details":null,"path":null,"userMessage":"Invalid request."}]}

**Comment by AureliuszBrussy** [comment]
W Twoim requeście znajduje się zbędny znak "/" przed parametrem **limit**. Żadanie powinno wyglądać następująco:

`GET https://api.allegro.pl/order/refund-claims?limit=100`

**Comment by lukada4100** [comment]
Obawiam się, że musi być jakaś inna przyczyna:

GET https://api.allegro.pl/order/refund-claims?limit=100 HTTP/1.1
Authorization: Bearer XXXXX-XXXXX
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json
Host: api.allegro.pl


HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 9fdaa216933a9016
date: Mon, 30 Nov 2020 16:19:12 GMT
x-content-type-options: nosniff
content-type: application/json
content-length: 148

{"errors":[{"code":"HttpMessageNotReadableException","message":"Invalid data format.","details":null,"path":null,"userMessage":"Invalid request."}]}

**Comment by AureliuszBrussy** [comment]
@lukada4100 weryfikujemy jeszcze ten problem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@lukada4100 Dziękuję za cierpliwość. Problem nie powinien już występować. Jeżeli jednak wciąż błąd występuje w odpowiedzi na Twój request - proszę o informację.
