### ISSUE TITLE
Język dokumentacji

### ISSUE THREAD

**Issue by cinam** [allegro/allegro-api#3933]
Dzień dobry,

Dlaczego dokumentacja API (https://developer.allegro.pl/documentation/) nie jest dostępna w języku polskim, tylko w angielskim? Link "Switch to english version / Przejdź do polskiej wersji" na dole strony sugerowałby, że zmiana języka jest możliwa - a jednak tak nie jest.

Warto zadać sobie pytanie, dla kogo jest to API? I pytanie pomocnicze: jaki procent użytkowników Allegro API jest niepolskojęzycznych? :) (na pewno da się to sprawdzić w bazach danych sprytnym SELECT-em)

Mam tu na myśli oczywiście opisy poszczególnych endpointów, nie url-e same w sobie.

Nie chodzi mi tylko o znajomość angielskiego wśród naszych rodzimych programistów, bo tu raczej nie ma problemu, przynajmniej w stopniu pozwalającym na rozumienie dokumentacji. Chodzi mi bardziej o to, że są tam zwroty, których polski odpowiednik nie jest oczywisty.

Np. akcja "get offer rating" (operation/offerRatingGET). Opis endpointa: "Use this resource to get offer rating". Hmm...... Co to jest "offer rating"? Jaki jest polski odpowiednik na stronie Allegro? Dla Was to pewnie oczywiste, dla mnie mniej. Mam nadzieję, że inni użytkownicy są bardziej domyślni. Mam jednak wrażenie, że przynajmniej początkującym użytkownikom byłoby łatwiej, gdyby mieli chociaż możliwość wyboru polskiej wersji dokumentacji.

**Comment by AureliuszBrussy** [comment]
Dziękuję za spostrzeżenie dotyczące udostępniania dokumentacji także w języku polskim. Przy opisie naistotniejszych zasobów dodajemy linki prowadzące do poradników w języku polskim i angielskim, np [ten](https://developer.allegro.pl/documentation/#operation/getListing) zasób ("Read more: [PL ](https://developer.allegro.pl/listing/)/ [EN](https://developer.allegro.pl/en/listing/)"). Dokumentacja w języku angielskim jest powszechnym standardem, stąd taka decyzja z naszej strony.
