### ISSUE TITLE
Pasuje do - brak danych w TechDoc

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3934]
Otrzymuje od klienta identyfikatory TechDoc, jednak dla niektórych z nich nie zwracacie informacji na temat pojazdu, przykładowo:

8311
27668
28654
59659
20219
28588
133216
108813
116223
121807
56196
136949
25119
16310
16306
136933

W czym jest problem?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać nazwy tych pojazdów? Prawdopodobnie pochodzą z innej wersji TecDoca niż ta, której używamy (europejska).

**Comment by marmited** [comment]
Przykładowo:

59659  - SIERRA (GBG, GB4) 2.0 01.1990 - 02.1993
133216 - FIESTA sedan 1.6 Ti 03.2015 -
16306 - PASSAT (3B2) 1.8 01.1997 - 11.2000

Mógłbym prosić o dokładniejszą informację co do wersji TechDoc? Może uda mi się porównać z klientem.

**Comment by PrzemyslawLukanowski** [comment]
Aktualna wersja bazy TecDoc, z której korzystamy, to 2046.
