### ISSUE TITLE
Czy zmieniane ostatnio były parametry w kategorii 82271

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3935]
Czy zmieniane ostatnio były parametry w kategorii `82271`, bo ostatnio zwróciło `Nieprawidłowe parametry (237190) dla wybranej kategorii.`? Jak porównuje z wersją u siebie w lokalnym szkicu to teraz nie ma w kategorii parametru o id `237190`. Jeśli nic nie było zmieniane to znaczy, że błąd jest po mojej stronie.

**Comment by AureliuszBrussy** [comment]
@AnimalDEV aktualnie parametr ten nie występuje w kategorii 82271. Konsultuję z odpowiednim zespołem to, czy parametr ten występował w niej wcześniej. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@AnimalDEV mam informację, że w kategorii 82271 nie nastąpiły żadne zmiany - odkąd sięgają nasze logi, zwracamy w niej parametr 237194 (Producent). Nie występował w kategorii parametr o id 237190 (Marka).

**Comment by AnimalDEV** [comment]
OK dziękuje za informację.
