### ISSUE TITLE
TECDOC NOWA WERSJA

### ISSUE THREAD

**Issue by lmajgier** [allegro/allegro-api#3936]
Czy ktoś z Państwa weźmie na siebie odpowiedzialnośc za to co się dzieje ?!
Brak informacji o aktualizacji wersji tecdoc na allegro!

Milion błędów
Wiadomość: Błąd połączenia z allegro. Kod http - 422, treść: {"errors":[{"code":"VALIDATION_ERROR","message":"Provided EAN is assigned to different product than attached in offer.","details":"","path":"","userMessage":"Provided EAN is assigned to different product than attached in offer."}]} Nazwa kolejki: fix_allegro_offers
Co to jest? czy wy wiecie, że EAN są podpięte do różnych produktów? 

Nie podaliście metody do edycji aukcji masowo, 
Jak to możliwe, że tak duża firma ma taki bałagan?

**Comment by AureliuszBrussy** [comment]
Dane w produktach oraz wymagane parametry w kategoriach do których przypisane są produkty mogą ulec zmianie. 

Jeden produkt może mieć wiele kodów EAN. Możecie uzyskać takie informacje między innymi korzystając z zasobu [GET /sale/categories/{categoryId}/product-parameters](https://developer.allegro.pl/documentation/#operation/getFlatProductParametersUsingGET). W przypadku produktu przytoczonego w wątku #3930 o id 0786878c-60a0-4f72-a673-b22c9282be6a - produkt ten posiadał dwie wartości w parametrze EAN jeszcze przed aktualizacją TecDoca. 

Jeżeli chodzi o ten konkretny przypadek z powyższego postu (error o kodzie VALIDATION_ERROR) - czy możesz podać konkrenty przykład wywołania, które zakończył się tym błędem (najlepiej trace-id lub id edytowanej oferty)? Pozwoli mi to lepiej zrozumieć zgłaszany problem.

**Comment by lmajgier** [comment]
Ale nie rozumiesz ze wystarczyło nas poinformować ze będziecie zmieniać bazę danych tecdoc? 

Jescze dwa miesiące temu zadałem pytanie kiedy zammierzacie to zrobić bo w naszej bazie były świeższe produkty niż u Was. Dostałem odpowiedz ze nieprędko ale na pewno dacie znać. 

Zrozum, ze teraz zmiana w 150,000 produktów parametrów które nagle są wymaga e nie dzieje od tak. 

Produkty które maja nowe wersje tecdoc nie zmieniają się w nich stany mag oraz ceny. 

Czy możesz powiedzieć kiedy zaktualizujecie cała bazę? 

Czy wy nie widzicie problemu w tym momencie ze trzeba wam wysyłać id i inne rzeczy? 
Wszystko jest rzucana na odczep się..

**Comment by AureliuszBrussy** [comment]
Dotychczas zmienialiśmy wersję TecDoca bez publikowania o tym fakcie - nie spotkaliśmy się z negatywnym odzewem dot. takiego działania. Aktualizacje nie były regularne. Aktualnie planujemy przeprowadzać aktualizację TecDoca cyklicznie, co kwartał.

**Comment by lmajgier** [comment]
> Dotychczas zmienialiśmy wersję TecDoca bez publikowania o tym fakcie - nie spotkaliśmy się z negatywnym odzewem dot. takiego działania. Aktualizacje nie były regularne. Aktualnie planujemy przeprowadzać aktualizację TecDoca cyklicznie, co kwartał.

Kiedy zmienialiście wersję tecdoca? 
Mieliście 2019 która była bardzo nieaktualna.
Pisałe do Was, że macie inne dane w produktach niżeli my mamy w opisie co wynikało z Waszej starej wersji Tecdoc.

**Comment by AureliuszBrussy** [comment]
Wersja TecDoc dotychczas była zmieniana nieregularnie, głównie z uwagi na uwarunkowania techniczne dot. ofert - faktycznie wciąż korzystaliśmy z wersji 2019, mimo, że dostępne były nowsze wersje. Trzeba pamiętać, że w serwisie widnieje blisko 200 milionów ofert, które naraz nie sposób zaktualizować, gdy tylko pojawia się nowa wersja TecDoc. Aktualnie wypracowaliśmy zasoby, które pozwalają nam efektywniej aktualizować wersję bazy TecDoc, dlatego aktualizacje będą pojawiać się cyklicznie - co kwartał.

**Comment by lmajgier** [comment]
Super, 
Tylko wiesz o tym, że w momencie w którym teraz zrobiliście aktualizacje posypało się wszystko?
Nie dając metody, aby zmienić dostosować ofert dodanych do produktów. 
Na froncie dodaliście opcje edycji produktu. W api nie - o tutaj chodzi, jak dla mnie aktualizować możecie codziennie, ale zróbcie to tak abyśmy nie musieli w to ingerować, albo wymagajcie od ludzi / serwisu tej samej wersji. 

Gdybyście miesiąc wcześniej co jest i tak mało, dawało znać ze tego i tego dnia się spinacie w nowa wersje - fo my mając ja u siebie w systemie dopasujemy sobie aukcje i nie ma problemu.

**Comment by AureliuszBrussy** [comment]
@lmajgier abyśmy mogli lepiej zrozumieć i przeanalizować problem - czy mógłbyś wskazać przykładowe id produktu oraz wprowadzony w ofercie EAN, gdzie otrzymałeś w odpowiedzi poniższy błąd?

`{"errors":[{"code":"VALIDATION_ERROR","message":"Provided EAN is assigned to different product than attached in offer.","details":"","path":"","userMessage":"Provided EAN is assigned to different product than attached in offer."}]}  `

**Comment by bart1337** [comment]
@AureliuszBrussy odpowiedz mi na jedno pytanie to już sobie sam ogarnę to co namieszaliście. Rozumiem, że dążycie do tego by był tylko jeden produkt z danym EANem tak ? 

Bo z tego co widzę to teraz poznikały EANy z niektórych produktów i gdy próbujemy wystawić takowy produkt z EANem (który mamy od tecdoca) to rzucacie błędem że EAN jest już przypisany do innego produktu. Wtedy takową aukcje powinniśmy rozpiąć od danego produktu i wystawić z tym co znajdziemy po EANie. Bo mamy produkt od tecdoca FILTRON AP 146. Gdy wyszukamy po frazie "FILTRON AP 146" zwróci dwa produkty, które nie mają EANu i w tym momencie takiego produktu nie da się wystawić (nawet jeśli mamy poprawny EAN od tecdoca). Kiedy wyszukamy po EANie znajdzie całkiem inny produkt od tych dwóch wcześniej - Toyota OE 17801-74020-83 filtr powietrza(67d45bb0-a4ca-4310-b42e-2264d0694b82). I takowy zapewne będzie można wystawić.

**Comment by AureliuszBrussy** [comment]
@bart1337 dziękuję za wskazanie konkretnego przykładku. Analizujemy jeszcze ten problem. Wrócę do Ciebie z odpowiedzią.

**Comment by lmajgier** [comment]
> @bart1337 dziękuję za wskazanie konkretnego przykładku. Analizujemy jeszcze ten problem. Wrócę do Ciebie z odpowiedzią.

Musicie zrozumieć, że integracja z tecdoc jest skomplikowana, nie mozecie od tak zmieniać sobie wersji bez uprzednio wprowadzonych metod, które pomogą edytować zmiany.

Tak jak @bart1337 napisał, teraz jest syf, do produktu macie te same EAN. 
Z tym Filtronem, owszem jest montowany na pierwszy montaż, ale wymuszacie aby dodać ean jako OE Toyota a nie filtron, teraz wybobraź sobie, że kupujesz ten filtr do swojej Toyoty, a przychodzi zamiast naklejek OE - Filtron, nie znając się, pewnie poczujesz się oszukany, prawda?

A wiesz, co twoi koledz z działu BOK powiedzą na dyskusję, negatywa? że klient ma prawo wyrazić swoją opinię, pal licho w to, że wy tutaj mieszacie..

**Comment by AureliuszBrussy** [comment]
@lmajgier planujemy wdrożyć zmiany, które ułatwią aktualizację takich ofert. Wciąż analizujemy kwestię zgłoszoną przez @bart1337

**Comment by bart1337** [comment]
Komedii ciąg dalszy. Nie możemy zmienić liczby sztuk w ofercie bo dostajemy błąd - ConstraintViolationException.ValidProduct (Provided EAN is assigned to different product than attached in offer.). Chcemy zatem zamknąć takową ofertę nim kupi ją ktoś i pojawi się problem. Wysyłamy zatem PATCHa z publication status na INACTIVE. Jaki błąd dostaniemy ? A no ten sam z tym, że po polsku ;) Podany kod EAN występuje w innym produkcie niż wskazany w ofercie.

**Comment by AureliuszBrussy** [comment]
@bart1337 czy mógłbyś wskazać konkretną ofertę, której problem dotyczy? Pozwoli mi to dokładniej sprawdzić sytuację oraz zasugerować ewentualne rozwiązanie.

**Comment by bart1337** [comment]
@AureliuszBrussy problem dotyczy metody PATCH (sale/product-offers/{offerId}). Gdy chcemy zmienić tylko publikację oferty (czyli zmienić jej status na INACTIVE) to mimo wszystko walidacji podlega całość. Tak więc jeśli oferta posiada błędy (które defacto wynikają z waszych modyfikacji) to nie zmienimy w niej nic dopóki nie poprawimy tych błędów.

**Comment by AureliuszBrussy** [comment]
@bart1337 rozumiem, tak jak wspomniałem wcześniej - problemy te są zaadresowane. Docelowo chcemy w ofertach powiązanych z produktem automatycznie prezentować najbardziej aktualne dane, zgodnie z danymi produktu. Tym samym nie będzie konieczne z Państwa strony aktualizowanie danych produktu w takich ofertach.

**Comment by lmajgier** [comment]
> @bart1337 rozumiem, tak jak wspomniałem wcześniej - problemy te są zaadresowane. Docelowo chcemy w ofertach powiązanych z produktem automatycznie prezentować najbardziej aktualne dane, zgodnie z danymi produktu. Tym samym nie będzie konieczne z Państwa strony aktualizowanie danych produktu w takich ofertach.

Chcecie - ale kiedy? Na chwilę obecną tracimy czas oraz zasoby na poprawnie błędów Allegro - czyt. stoimy w miejscu. 
Zamiast rozwijać inne rzeczy w systemie babrzemy się za przeproszeniem w gów... aby wszystko posklejać.

**Comment by AureliuszBrussy** [comment]
@lmajgier jeszcze nie jestem w stanie podać konkretnej daty. Oczywiście będziemy komunikować wszelkie zmiany, gdy tylko będziemy gotowi.
