### ISSUE TITLE
Nie można połączyć w warianty ofert bez zdjęć

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3937]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Kiedy próbuje połączyć oferty w wariant dostaje błąd `Oferty składające się na ofertę wielowariantową łączoną bez parametru kolor/wzór muszą mięć identyczne zdjęcia. Upewnij się, że zdjęcia nie różnią się drobnym szczegółem (np. rozmiar zdjęcia, znak wodny) lub dodaj parametr kolor/wzór.`. Problem w tym jest taki, że żadna z tych ofert nie ma zdjęć. Jeśli zdjęcia są wymagane to fajnie by było to zwrócić w błędzie.

To samo się dzieje przez front.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe numery ofert? Umożliwiamy łączenie ofert bez zdjęc w ofertę wielowariantową. Nie możesz natomiast połączyć oferty bez zdjęcia z innymi ofertami, które zdjęcie posiadają.

**Comment by AnimalDEV** [comment]
7678961967
7678961969
7678961961
![Screenshot_20201130_151435](https://user-images.githubusercontent.com/20936097/100620643-efca9a80-331e-11eb-9e88-2da3cb958fbb.png)

**Comment by PrzemyslawLukanowski** [comment]
W Twoim przypadku problem generują duplikaty - komunikat jest nieco mylący dlatego weźmiemy pod uwagę jego zmianę. Podmień ofertę 7678961969 (XL) na 7678961975, rozwiąże to problem.

**Comment by AnimalDEV** [comment]
OK dzięki
