### ISSUE TITLE
Product details

### ISSUE THREAD

**Issue by dzoudzou3** [allegro/allegro-api#3938]
Hi all

Do you have any idea how can I get som additional info/data about product.
Half year ago I usually use doGetItemsInfo -> **WebAPI**.
But now when i search some products with [https://api.allegro.pl/offers/listing](url) and than I need many information about product (e.g.): 
- **price**: is this price with or witout VAT

- **delivery price:** in search i have only cheapest price, but there is also 0.00 price when vendor offer get this product from their company 

- **description:** I haven't got any info for customer about product

From https://api.allegro.pl/offers/listing i have product "id" but this is useless because I can't use this id in any query/path parameters in other REST API functions.

**Comment by AureliuszBrussy** [comment]
There is no equivalent of the doGetItemsInfo method in Allegro REST API. You can get specific offer data by [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) only as an authenticated user (owner of the offer). For searching and getting basic offer information of other users - use GET /offers/listing.

**Comment by dzoudzou3** [comment]
ok but describe me all this flow and which API method should to use:

> search products (for example by phrase)

> take product id from search and get all information about product

**Comment by AureliuszBrussy** [comment]
To search offers you can use [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). You cannot get all information about other seller's offers via API due to the sensitivity of this information. [Check our news](https://github.com/allegro/allegro-api/issues/3661) to get more information.

**Comment by dzoudzou3** [comment]
In old version Web API were sensitive information-> paymenth..., But I don't need this type of informations. 
Me and many others which use this REST API only need public informations which are also on allegro.pl for normal customer. All this information we need:

- product: id, name, price, description, some addiotional info where is info about "Faktura", Stan....
- all available delivery with prices
- about user only name and id

That is all.

I don't understand why you don't offer all public informations which are also on your web site available for normal customer?
If you want to get paid for this service, it is not problem. But I still don't understand why don't some basic informations, because people like me increase your selling

**Comment by AureliuszBrussy** [comment]
According to the decision taken by Allegro, about which you can read more on the [seller page](https://allegro.pl/dla-sprzedajacych/1-pazdziernika-2020-roku-ograniczymy-dostep-do-wrazliwych-danych-o-transakcjach-z82y8M11gC8), we limit access to sensitive data on transactions. The lack of equivalents of some WebAPI methods in the REST API is a consequence of this decision. You can get specific offer data by [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) only as an authenticated user (owner of the offer).
