### ISSUE TITLE
Monitorowanie sprzedaży poprzez REST API (odpowiednik doGetSiteJournalDeals)

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#394]
Dzień dobry,

czy udostępniają Państwo taki zasób w REST API, który pozwalałby monitorować złożone zamówienia?
Jeśli nie, to proszę napisać na kiedy planujecie rozszerzyć REST API o taką funkcjonalność?

**Comment by partyumarty** [comment]
#371

**Comment by aktywnitu** [comment]
Super. Dziękuję i pozdrawiam developerów Allegro.
