### ISSUE TITLE
Wyszukiwanie produktów GET /sale/products, dodatkowy dynamiczny filtr

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3940]
:bulb: **Sugestia**
Dzień dobry, zwracam się z prośbą o dodanie do zasobu GET /sale/products dodatkowego dynamicznego filtru umożliwiającego wyszukanie po ean więcej niż jednego produktu w jedynym requeście. Oczywiście z limitem. Przyśpieszyło by to znacząco grupowy proces dodawania nowych ofert w serwisie.

```
"eans": [
  12345545354.
  22321321231,
  12313131313
 ]
```

**Comment by AureliuszBrussy** [comment]
Dziękuję za sugestię - dopisałem ją do listy sugestii dot. dalszego rozwoju REST API.
