### ISSUE TITLE
Zmiana adresu url do przekierowania nie przynosi efektu - kieruje na stary adres

### ISSUE THREAD

**Issue by RL89pl** [allegro/allegro-api#3941]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Zmieniłem domenę aplikacji, edytowałem w ustawieniach na https://apps.developer.allegro.pl/ adres do przekierowania, ale użytkownika nadal próbuje przekierować do starego adresu.
O czymś zapomniałem?

**Comment by AureliuszBrussy** [comment]
Czy zmieniłeś w swojej aplikacji link z przekierowaniem do [uwierzytelniania użytkownika](https://developer.allegro.pl/auth/#user)? Chodzi o link postaci np.: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=a21…6be&redirect_uri=http://exemplary.redirect.uri?

**Comment by RL89pl** [comment]
Tak, mam zmienione. 
Niestety nadal próbuje przekierować na stary adres.

**Comment by AureliuszBrussy** [comment]
Proszę, podaj kod błędu, który pojawia się po przekierowaniu. Pozwoli mi to sprawdzić, w czym dokładnie jest problem.

**Comment by RL89pl** [comment]
kod błędu: 4e68e16835c87eae
By wszystko działało poprawnie, muszę ręcznie adres zmieniać redirect_url w pasku przeglądarki na właściwą stronę

**Comment by AureliuszBrussy** [comment]
Jeżeli z Twojej aplikacji następuje przekierowanie na url z nieodpowiednim redirect_url i musisz go zmieniać ręcznie - wygląda na to, że adres przekierowania w sparametryzowanym linku w Twojej aplikacji jest nieprawidłowy. Powinieneś zmienić ten adres (url przekierowujący do uwierzytelniania użytkownika) na poziomie swojej aplikacji. Sprawdziłem też logi i faktycznie - adres, który aktualnie podałeś w [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/) jest niezgodny z tym podany w aplikacji.

**Comment by RL89pl** [comment]
Tylko sprawdziłem dokładnie i przekazuję redirect_url prawidłowy, taki jak mam w zarządzaniu aplikacjami.

**Comment by RL89pl** [comment]
Jest jeszcze drugi link, który przetwarza żądanie.
Przepraszam, mój  błąd, wszystko działa poprawnie ;)
