### ISSUE TITLE
Generowanie kodu autoryzacyjnego

### ISSUE THREAD

**Issue by Cule5** [allegro/allegro-api#3942]
Chciałbym się dowiedzieć czy jest możliwość wykonania zapytania, po którym nastąpi odesłanie kodu autoryzacyjnego, z kodu C#? Obecnie próbuję to osiągnąć z wykorzystaniem biblioteki RestSharp.

**Comment by AureliuszBrussy** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może ktoś z użytkowników forum będzie mógł wesprzeć Cię w tym temacie. Zachęcam, abyś zapoznał się z udostępnionym przez nas [poradnikiem dotyczącym uwierzytelniania i autoryzacji.](https://developer.allegro.pl/auth/)
