### ISSUE TITLE
Kalkulator opłat a nowe opcje promowania

### ISSUE THREAD

**Issue by mkwalewski** [allegro/allegro-api#3943]
Witam,

Mam pytanie odnośnie do kalkulatora opłat, a nowych opcji promowania, ponieważ w dokumentacji dla "/pricing/fee-preview" są podane jeszcze stare opcje.

Jak policzyć dobrze opłatę posługując się nowymi opcjami promowania ?
Ewentualnie czy jest jakiś sposób, żeby przemapować stare na nowe i odwrotnie ?

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Sprawę nowych opcji promowania w kalkulatorze opłat konsultuję z właściwym zespołem - wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Kalkulator opłat - zarówno wersja dostępna w API, jak i w serwisie WWW zostanie zaktualizowana w najbliższym czasie by móc obsłużyć nowe opcje promowania.
