### ISSUE TITLE
Dziennik zdarzeń ofert przestał zwracać zdarzenie OFFER_STOCK_CHANGED

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#3945]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam.

Mam problem z dziennikiem zdarzeń ofert. Od jakiś 17 godzin nie otrzymuje żadnych zdarzeń typu `OFFER_STOCK_CHANGED` mimo tego, że odnotowałem sprzedanie przedmiotów na licytacjach. Co się stało? Jakaś awaria? Niezapowiedziana zmiana? Nie ukrywam, że to dość stresująca sytuacja, bo problem jest bardzo poważny.

Id ostatniego pobranego eventu typu `OFFER_STOCK_CHANGED`: `MTYwNjc3MjA5MjM1NTg2Mg` z Unix timestampem (milisekundowym) `1606772080008`. Po nim nie nastąpił już jakikolwiek event tego typu.

Jeżeli to jakkolwiek pomoże, mowa o licytacjach z możliwością natychmiastowego kupna (Kup Teraz!).

**Comment by AureliuszBrussy** [comment]
Sprawdziłem funkcjonowanie dziennika zdarzeń i eventu OFFER_STOCK_CHANGED - wygląda na to, że działa prawidłowo. Czy możesz podać ID oferty, gdzie po zmianie w ofercie nie zwróciliśmy eventu OFFER_STOCK_CHANGED? Zrób to w wątku, lub jeśli wolisz - przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Zweryfikujemy to. Jeśli zdecydujesz się na zgłoszenie przez formularz - wskaż w wiadomości numer wątku GitHub: #3945.

**Comment by hahyes** [comment]
Skontaktowałem się poprzez formularz kontaktowy.

**Comment by AureliuszBrussy** [comment]
@hahyes nie widzimy żadnego braku w zwracanych eventach OFFER_STOCK_CHANGED. W podanym przez Ciebie w formularzu przykładzie - pomiędzy wskazanymi eventami nie nastąpił żaden zakup, dlatego nie zwracaliśmy informacji o zmianie liczby przedmiotów. Czy jesteś w stanie wskazać jakiś inny przykład lub id konkretnego zamówienia, po którym nie nastąpił event OFFER_STOCK_CHANGED?
