### ISSUE TITLE
Problem z wystawieniem aukcji integracja shopGold

### ISSUE THREAD

**Issue by J4C0** [allegro/allegro-api#3946]
Witam, od kilku dni dodaję nowe aukcje na zintegrowanym sklepie internetowym. Sklep utworzony jest na nakładce shopGold. W pierwszy dzień po 4 aukcjach wyskoczył mi błąd: **"VALIDATION_ERROR Brakuje jednego z tagów otwierających"**. Bardzo proszę o informację co jest nie tak i wyjaśnienie pojęcia tagów otwierających. Dziękuję i pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
W opisach ofert, które wystawiasz możesz użyć ograniczonej liczby tagów HTML - ich pełną listę znajdziesz [tu](https://developer.allegro.pl/sale/#5-opis-oferty). Komunikat, który otrzymałeś natomiast mówi, że nie użyłeś, w którymś miejscu taga otwierającego <>, tylko od razu zamykający </> - sprawdź proszę swój opis oferty.
