### ISSUE TITLE
token_creation_rate_limit_exceeded 

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#3947]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Rozwijamy nasze oprogramowanie u klienta i byliśmy zmuszeni do pewnych modyfikacji, które wymagały generowania tokenów ręcznie, codziennie zamiast refresh_token. Dzisiaj, po wygenerowaniu nowej pary tokenów, API zwraca błąd `token_creation_rate_limit_exceeded`.

Rozumiem, że przekroczyliśmy jakiś limit?

**Comment by MaciejFrackowiak** [comment]
Tak, takie masowe generowanie tokenów doprowadza do przekroczenia limitu ich dostępności. Oczywiście, gdy zatrzymasz proces to po upływie czasu otrzymasz nową parę tokenów już bez komunikatu o limicie.

**Comment by troncomputers** [comment]
Co to znaczy "gdy zatrzymasz proces"?

**Comment by MaciejFrackowiak** [comment]
Jeśli w sposób ciągły będziesz występować o token, gdy otrzymałeś komunikat o przekroczeniu limitu to tylko wydłużysz czas trwania ograniczenia.

**Comment by troncomputers** [comment]
Ok, usługa jest zatrzymana już od godziny. Czy tokeny, które dzisiaj wygenerowałem, które zwracają błąd `token_creation_rate_limit_exceeded` będą działać, czy muszę wygenerować jeszcze raz?

**Comment by troncomputers** [comment]
Dalej ten błąd się pojawia. Chciałbym zaznaczyć, że ten błąd pokazuje się podczas odpytywania API, nie podczas autoryzacji. Dzisiaj rano byłem w stanie wygenerować parę tokenów, wgrać na serwer i klient mi zadzwonił (pół godziny później) z informacją o błędzie. Usługę włączyłem 10 minut temu i dalej nie można odpytać API.

**Comment by MaciejFrackowiak** [comment]
Komunikat "token_creation_rate_limit_exceeded" pojawia się podczas tworzenia tokena, zatem skoro się pojawił to żadne nowe tokeny nie powinny zostać wydane. Zautoryzuj się ponownie, i sprawdź proszę czy z nowym access + refresh tokenem uzyskasz dostęp do zasobów.

**Comment by troncomputers** [comment]
W tym przypadku podczas tworzenia tokena nie było żadnego błędu. Taki błąd pojawił się podczas odpytywania zasobów API. 

Wygenerowanie nowej pary tokenów przeszło bezbłędnie i wszystko działa. Dzięki za pomoc
