### ISSUE TITLE
change_price_commands - dokładny czas wprowadzenia zmiany?

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#395]
cześć,
czy jest jakaś metoda aby dowiedzieć się kiedy cena na aukcji uległa zmianie (dokładna data i czas) w przypadku użycia metody change_price_commands? 

pozdrawiam

**Comment by AniaMalinowska** [comment]
Nie ma takiej metody. Zmianę ceny należy śledzić samodzielnie. To, czy cena się zmieniła można sprawdzić pobierając daną ofertę [tym zasobem](https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET).

**Comment by sis6326r** [comment]
Tylko po co ciągnąć niepotrzebnie tyle danych? 
Sami zaproponowaliście wzorzec command - https://developer.allegro.pl/command/
Cytuję:
"_Co daje zastosowanie takiego wzorca?
standardowy mechanizm śledzenia statusu operacji asynchronicznych - obok zasobu wywoływanego metodą http PUT może istnieć zasób wywoływany poprzez metodę GET, który zwróci aktualny status przetwarzania polecenia_"

Może jednak warto dorobić śledzenie zmian cen? W tej chwili nie możliwe jest dokładne odwzorowanie cennika wraz z umiejscowieniem zmian w czasie. 

I druga prośba związana z tą metodą to hurtowa zmiana cen. Pewnie ma to też wpływ na system allegro - zamiast 70 tyś requestów można to załatwić np 7 requestami po 10 tyś. 
Wystarczy, że obsłużycie użycie array'a zamiast pojedynczego rekordu.


pozdr

**Comment by AniaMalinowska** [comment]
Dzięki @sis6326r za obie sugestie.
