### ISSUE TITLE
Dostępność faktoringu i możliwość pobrania stawek VAT

### ISSUE THREAD

**Issue by Sebug-rsa** [allegro/allegro-api#3950]
Czy w zasobach API jest uwzględniona usługa faktoringu, ewentualnie kiedy zostanie obsłużona? Analogiczne pytanie dotyczy pobierania stawek VAT.

**Comment by MaciejFrackowiak** [comment]
Nie, ponieważ odroczona płatność obecnie udostępniona jest wyłącznie dla sprzedających, aby mogli przygotować się na wprowadzenie funkcjonalności. Jeżeli wprowadzimy odpowiednie zasoby w API oczywiście opublikujemy osobny komunikat. Stawkę VAT dla danej oferty pobierzesz [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) w polu tax.percentage.
