### ISSUE TITLE
Błąd przy pobieraniu aukcji 

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#3951]
Dzień dobry, Czy coś się zmieniło w odpytaniach o oferty?
Chodzi o: 'https://api.allegro.pl/sale/offers/'.$id_auction
Gdy odpytuję np 200 ofert w pętli jest ok ale gdy zwiększę do 2000 serwis zaczyna mulić i nie kończy zadania . Problem jest od dzisiaj rano, wcześniej było normalnie.
Pozdrawiam
Paweł

**Comment by AureliuszBrussy** [comment]
Widzę, że wątek ten jest dublem #3949 - już odpisałem na to zgłoszenie.
