### ISSUE TITLE
Wystawianie aukcji - brak SMART, brak aukcji w listingach

### ISSUE THREAD

**Issue by szuwarek25** [allegro/allegro-api#3952]
Wystawiam aukcje opcją "wystaw ponownie" na kolejne 30 dni poprzez Easy Uploader
Dziś zauważyłem, że część z nich nie pokazuje się w listingach (poprzez tytuł itp) choć przyznany numer aukcji w wyszukiwarce wskazuje, że aukcja jest aktywna. Co ciekawe, każda z takich aukcji - widm nie posiada SMART, mimo że spełnia wszelkie wymogi, a zakończona aukcja na której podstawie została wystawiona nowa taki SMART posiadała. 

Ktoś ma jakies pomysły?

przykłady:
https://allegro.pl/oferta/czeslaw-niemen-od-poczatku-i-6cd-box-2002-9984199087
https://allegro.pl/oferta/sbb-follow-my-dream-1997-koch-ze-skorpionem-folia-9984261363
https://allegro.pl/oferta/niemen-czy-mnie-jeszcze-pamietasz-enigmatic-folia-9984201024
https://allegro.pl/oferta/czeslaw-niemen-sukces-1996-polskie-nagrania-folia-9984219986
https://allegro.pl/oferta/czeslaw-niemen-nasz-niemen-2009-digibook-2cd-9984237495

nie do nzalezienia przez wyszukiwarkę, nie pokazujące się jako nowo wystawione, bez smart. Mimo to sam link aktywny

**Comment by MaciejFrackowiak** [comment]
Jak widzę oferty są w pełni dostępne poprzez wyszukiwarkę. Również posiadają opcję Smart - mechanizm potrzebuje czasu, aby nową ofertę zweryfikować czy spełnia ona wymogi Smart.

**Comment by szuwarek25** [comment]
Tak, wskoczyły i do wyszukiwarki i na smarta, trwało to w ich przypadku jakieś 5-6 godzin. Pozostałe 90% wystawionych aukcji od razu miały prawidłowy status

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem proces oznaczania ofert może trwać - raz dzieje się to od razu, a czasem po jakimś czasie - jest to normalny flow, uzależniony od ilości operacji w serwisie.
