### ISSUE TITLE
Problem z Produktyzacją

### ISSUE THREAD

**Issue by MAREKWW** [allegro/allegro-api#3953]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Wystawiliśmy Aukcję przez REST API.
Numer aukcji 9260720398
Następnie do aukcji został podpięty produkt Allegro (Produktyzacja).
- Aukcja przestała się synchronizować. Zwracany jest błąd jak poniżej.
- Kategoria na aukcji i w naszym synchronizatorze nie zmieniła się.
- Nie ma innego towaru do wybrania po stronie Allegro.
- Co my albo klient mamy zrobić w takiej sytuacji?

Treść błędu: You cannot change category after 12 hours from publication. Informacje o błędzie: {"errors":[{"code":"VALIDATION_ERROR","message":"You cannot change category after 12 hours from publication.","details":"","path":"","userMessage":"Nie możesz zmienić kategorii po 12 godzinach od wystawienia."}]}StatusCode: 422x-xss-protection: 1; mode=blockpragma: no-cachex-frame-options: DENYtrace-id: ab4a23b078aa7735x-content-type-options: nosnifftransfer-encoding: chunkedCache-Control: no-cache, no-store, max-age=0, must-revalidateContent-Type: application/jsonDate: Mon, 23 Nov 2020 11:00:40 GMTExpires: 0**

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem dane oferty:

1) oferta ma przypisaną do siebie kategorię 122568;
2) do oferty przypięty jest produkt o id=44c3d809-906e-4b56-b140-bd64cab82bd9 - odpytując GET /sale/prodcuts/44c3d809-906e-4b56-b140-bd64cab82bd9 otrzymujemy produkt, który należy do kategorii 122571;
3) próba aktualizacji kończy się błędem, ponieważ nadrzędną kategorią jest kategoria z produktu, która jest różna względem tej z oferty.

Rozwiązaniem jest odpięcie produktu od oferty, ponieważ obecnie oferta ma wybraną kategorię niezgodną z produktem - a nie ma możliwości zmiany id kategorii po 12 godzinach od rozpoczęcia oferty, o czym wspomina komunikat.

**Comment by MAREKWW** [comment]
Zaproponowaliśmy klientowi odpięcie produktu od aukcji. Jednak nie da się tego zrobić. Gdy w edycji aukcji przy produkcie damy Zmień -> Usuń produkt z oferty. To po zapisaniu zmian w aukcji produkt podpina się od nowa. Prawdopodobnie poprzez EAN. Co w takiej sytuacji? Jak skutecznie odpiąć produkt od aukcji?

**Comment by MaciejFrackowiak** [comment]
Mechanizm na WWW wykrywa produkt dla podanego kodu EAN i stąd ponowne przypisanie. Jeżeli pobierzesz ofertę przez GET /sale/offers/{offerId}, a następnie wykonasz edycję przez PUT /sale/offers/{offerId}, gdzie w product.id przekażesz null to edycja oferty zostanie wykonana.
