### ISSUE TITLE
Problem z obsługą kampanii na sandboxie

### ISSUE THREAD

**Issue by p3le** [allegro/allegro-api#3954]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**

Moje konto nie zostało w pełni przekształcone w firmowe, a przynajmniej tak mi się wydaje. Próbuję dostać się tutaj:

https://api.allegro.pl.allegrosandbox.pl/sale/badge-campaigns

W odpowiedzi dostaję:
```
{
    "errors": [
        {
            "code": "BB2",
            "message": "Account is not a Company account type.",
            "details": null,
            "path": null,
            "userMessage": "Account is not a Company account type."
        }
    ]
}
```
userId: 43964642

**Comment by MaciejFrackowiak** [comment]
Konto masz w pełni aktywne, to niestety problem z zasobami do obsługi kampanii na Sandbox. Problem jest już przekazaliśmy do weryfikacji.

**Comment by p3le** [comment]
Rozumiem, że tyczy się to wszystkich kampanii?

![obraz](https://user-images.githubusercontent.com/2972454/101026600-66fa6b80-3577-11eb-8ef1-0a8a4a03909f.png)

**Comment by MaciejFrackowiak** [comment]
Tak, jest to ze sobą powiązane.

**Comment by p3le** [comment]
Czy wiadomo już coś w tym temacie?

**Comment by MaciejFrackowiak** [comment]
Niestety, problem nie został jeszcze rozwiązany. Zmuszony jestem prosić o cierpliwość.
