### ISSUE TITLE
Opóźnienia dot. zamykania ofert

### ISSUE THREAD

**Issue by lukada4100** [allegro/allegro-api#3955]
Mógłbym prosić o sprawdzenie skąd biorą się kilkugodzinne opóźnienia pomiędzy datą sprzedaży:  pole "boughtAt" z https://api.allegro.pl/order/checkout-forms/

a datą zamknięcia oferty: pole "endedAt" z https://api.allegro.pl/sale/offers.

Wygląda na to, jakby oferta (chodzi o pojedynczą ofertę kup teraz) zamykana była w niektórych sytuacjach dopiero kilka godzin po zakupie. 

W formularzu przesyłem zebrane dane.

**Comment by AureliuszBrussy** [comment]
Czekamy jeszcze na danie przesłane w formularzu - zweryfikujemy to i wrócimy z odpowiedzią.

**Comment by lukada4100** [comment]
Gdyby nie dotarło, dajcie znać, doślę jeszcze raz.

**Comment by lukada4100** [comment]
Czy udało się może coś wyjaśnić w powyższej sprawie?

**Comment by AureliuszBrussy** [comment]
@lukada4100 niestety, ale zgłoszenie do nas dotychczas nie dotarło. Czy mógłbyś podać numer tego zgłoszenia?

**Comment by lukada4100** [comment]
12537806

Dzień dobry,
Widzę że otrzymał Pan odpowiedz w tej sprawie w wątku #3955
,,Czekamy jeszcze na danie przesłane w formularzu - zweryfikujemy to i wrócimy z odpowiedzią."
Proszę o cierpliwość aktualnie czekamy na informacje w tej sprawie.
Pozdrawiam
// Jakub Olkusz
Zespół Allegro

**Comment by AureliuszBrussy** [comment]
@lukada4100 dziękuję za przesłanie numeru zgłoszenia - uzyskałem przesłane dane. Proszę jeszcze o informację, czy zauważyłeś, że problem się powtarzał, czy występował tylko w dniach z podanych przykładów (28/29.11)? Czy przy aktualnych zamówieniach także napotkałeś ten problem?

**Comment by lukada4100** [comment]
Opóźnienia, o których pisałem spowodowały u klienta pewne perturbacje dot. sprzedaży. Dlatego skoncentrowałem się właśnie na tych przykładach. W innych, nowych oferach problem nie występował.

**Comment by AureliuszBrussy** [comment]
Z przesłanych przez Ciebie danych faktycznie wynika, że nastąpiło opóźnienie. Jeżeli ponownie zauważysz takie opóźnienia - proszę,  poinformuj nas możliwie szybko, tak abyśmy mogli reagować na bieżąco.

**Comment by lukada4100** [comment]
Podobna sprawa. Mógłbym prosić o zweryfikowanie dlaczego licytacja która miała zakończyć się o 18:15 zakończyła się dopiero pół godziny później?
Dane w załączniku.

[12834_Full.txt](https://github.com/allegro/allegro-api/files/5681799/12834_Full.txt)

**Comment by AureliuszBrussy** [comment]
Oferta tak naprawdę nie zakończyła się z opóźnieniem. Licytacja trwała dokładnie 3 dni. Pół godziny opóźnienia w zakończeniu wynikało z opóźnienia aktywacji oferty - ta może potrwać do godziny czasu. Oferta rozpoczęła się 7 grudnia o godzinie 19:43:15, stąd też zakończenie 10 grudnia o 19:43:15.

**Comment by lukada4100** [comment]
Dzięki. Czy mi się wydaję, czy jeszcze do niedawna było tak, że zamknięcie tak jak piszesz trwało do godziny (praktycznie do 10 min), ale gdy oferta już się zamknęła to jako ended_at wstawiana była data z ending_at. Porównywałem te wartości, żeby sprawdzić czy oferta zamknęła się przez „EXPIRATION” czy przez „USER”.

**Comment by lukada4100** [comment]
A jeśli jest tak jak piszesz po czym wnosisz, że aukcja rozpoczęła się o 19:43? starting_at = started_at = 19:15

**Comment by AureliuszBrussy** [comment]
Konsultuję to z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Zweryfikowaliśmy to - oferta ta została wystawiona w czasie awarii, a więc jej faktyczne wystawienie odbyło się z opóźnieniem, mimo, że w polu started_at widzisz inną informację. Nieprawidłowe daty rozpoczęcia i zakończenia oferty spowodowane są właśnie tą awarią.

**Comment by lukada4100** [comment]
Dzięki za info. Pozdrawiam
