### ISSUE TITLE
Emaile nie docierają

### ISSUE THREAD

**Issue by Snajper315** [allegro/allegro-api#3956]
Występuje problem:
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Na chwilę obecną nie przechodzi u mnie żaden mail jaki próbuje wysłać w środowisku testowym. Nie działa dodatkowy adres email dodany u sprzedającego, ale również adres główny. Nic nie przechodzi.
Email kupującego na jaki próbuje wysłać wiadomość to: l8y5va3owv+50553d5f5@user.allegrogroup.pl

**Comment by AureliuszBrussy** [comment]
Mamy dzisiaj opóźnienia w dostarczaniu wiadomości na środowisku testowym - pracujemy nad rozwiązaniem tego problemu.

**Comment by Snajper315** [comment]
U mnie wiadomości właśnie zaczęły się pojawiać
