### ISSUE TITLE
Przekroczony czas zapytania - Kategorie

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3957]
Dlaczego prawie każde zapytanie na https://api.allegro.pl.allegrosandbox.pl/sale/categories?parent.id=4029
Kończy się odpowiedzią:

```
{
    "errors": [
        {
            "code": "ServiceTimeoutException",
            "message": "An error occurred",
            "details": null,
            "path": null,
            "userMessage": "Przekroczono czas wykonania zapytania. Spróbuj ponownie."
        }
    ]
}
```

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, mogły występować okresowo timeouty, podjęliśmy już działania mające na celu usprawnienie działania tego endpointu na Sandbox.

**Comment by marmited** [comment]
Dziękuję.
