### ISSUE TITLE
Wysyłanie przesyłek przez WZA Inpost

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3958]
Chcę zintegrować Inpost z WZA. Niestety Inpost dostarczył klucz produkcyjny do konta, a do jakiegoś konta testowego nie mogę się doprosić. Dlatego nie jestem w stanie wypróbować tworzenia ani zamawiania odbioru paczki, bo potrzebuję dodać umowę własną, która nie wyśle mi żądania odbioru prawdziwej paczki .

Dlatego pytam:

O ile dobrze rozumiem to w momencie zamawiania odbioru już utworzonej paczki nie powinienem odpytywać się zasobu
**GET /parcel-management/pickup-date-proposals** a jedynie zamówić kuriera **PUT /parcel-management/parcel-pickup-request-commands/{commandId}** bez uzupełniania dat i zakresów godzinowych odbioru paczek.

Tak wnioskuję po przeczytaniu: https://developer.allegro.pl/wza/

**Comment by AureliuszBrussy** [comment]
Zgadza się - w przypadku InPostu nie musisz korzystać z GET /parcel-management/pickup-date-proposals, ponieważ nie możesz wybrać daty podjazdu kuriera. Podczas zamawiania odbioru przesyłek (PUT /parcel-management/parcel-pickup-request-commands/{commandId}) nie przekazuj w żądaniu pola **pickupDate**.
