### ISSUE TITLE
Sandbox - błąd serwera przy opłacaniu salda konta

### ISSUE THREAD

**Issue by tommy-bear** [allegro/allegro-api#3959]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie uregulowania salda konta, w odpowiedzi zwracany jest kod 500. Przez co poblokowane są główne funkcjonalności konta.
Zaobserwowane dla konta `muvepl-test`
![obraz](https://user-images.githubusercontent.com/32964352/101323055-58a69b00-3868-11eb-8c5b-f56eeda06e0b.png)

Poniżej trace-id paru takich zapytań:
```
trace-id: 55ce527785db9c54
trace-id: 6835612466664821
trace-id: 7d83c94abbf4142
```

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by tommy-bear** [comment]
Wszystko w porządku.
Zamykam
