### ISSUE TITLE
'{https://webapi.allegro.pl/service.php}fvalueImage': '0' is not a valid value of the atomic type 'xs:base64Binary'.

### ISSUE THREAD

**Issue by goliatek86** [allegro/allegro-api#396]
Witam,

Co może być przyczyną tego błędu w WEBAPI ?

Wystąpił nieoczekiwany błąd podczas dodawania nowej aukcji.Element '{https://webapi.allegro.pl/service.php}fvalueImage': '0' is not a valid value of the atomic type 'xs:base64Binary'.

w opsie aukcji tez jest tylko 1 obrazek
Wysyłam tylko jeden obrazek w FID 16, obrazek jest wczytywany z pliku jpg robiony na nim base64_encode i wysylany SOAP-EM W PHP

Dodam ze dzieje sie to tylko u jednego z klientów.  na serwerach kei.  u pozostałych klientów  aukcje wystawiają się prawidłowo, tylko tutaj coś nie tak, i nie wiem za czym szukać.

**Comment by AniaMalinowska** [comment]
Błąd sugeruje, że podajesz niepoprawną wartość jako kod obrazka, czyli 0. Abyśmy mogli to zweryfikować podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) pliki *.XML z pełnym request i response i podaj tutaj numer zgłoszenia.
