### ISSUE TITLE
Sandbox błąd kupowania

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#3960]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od kilkunastu minut nie jest możliwe zakupienie produktu na Allegro na środowisku testowym.

![obraz](https://user-images.githubusercontent.com/37150863/101323556-34978980-3869-11eb-9848-2f5271d82836.png)

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.
