### ISSUE TITLE
fulfillment status - Zapłacone

### ISSUE THREAD

**Issue by lhascilo** [allegro/allegro-api#3961]
Witam

Mam pytanie, bo jednoznacznie nie ma tego opisanego w dokumentacji, który status określa zamówienie zapłacone ale nie wysłane ? Logika nakazywała by użyć statusu "READY_FOR_SHIPMENT", ale chciałbym się upewnić.

    NEW - nowe zamówienie,
    PROCESSING - zamówienie w realizacji,
    READY_FOR_SHIPMENT - zamówienie do wysłania,
    SENT - zamówienie wysłane,
    CANCELLED - zamówienie anulowane.

**Comment by PrzemyslawLukanowski** [comment]
O opłaconym zamówienie świadczy wartość READY_FOR_PROCESSING w polu order.status. Wartość order.fullfilment.status określa etap realizacji zamówienia po stronie sprzedającego, dlatego to w jego gestii pozostaje wybór odpowiedniej opcji, Może to być zarówno NEW, PROCESSING, jak i READY_FOR_SHIPMENT -  w zależności od tego, na jakim etapie znajduje się zamówienie,

**Comment by SebastianOzdoba** [comment]
READY_FOR_PROCESSING  nie oznacza że jest opłacone (jeśli kupujący wybrał płatność za pobraniem / odbiór osobisty też będzie RFP), musisz sprawdzać kwotę płatności

**Comment by PrzemyslawLukanowski** [comment]
Tak, zgadza się, w wyżej wymienionych przypadkach również widoczny będzie status RFP.
