### ISSUE TITLE
Service unavailable - permanentny błąd

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#3962]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Przykładowe trace-id:
8b156a5a95533690

Na wszystkie zmiany ilości lub cen oferty dostajemy błąd "Service unavailable. Please try again in a few minutes."

**Comment by mareklemur** [comment]
potwierdzam, nie da się nic zrobić przez api
albo INTERNAL_SERVER_ERROR albo SERVICE_UNAVAILABLE

**Comment by GosiaJK** [comment]
Allegro przekroczyło magiczną liczbę 10 miliardów aukcji(?). To może być przyczyną problemów.

**Comment by mareklemur** [comment]
może być
tylko moment nie najlepszy

**Comment by tomylee0** [comment]
Już chyba działa.

**Comment by mareklemur** [comment]
u mnie nie: Execution of the request timed-out. Try again.

**Comment by tomylee0** [comment]
Zgadza się. Zadziałało tylko na chwilę. Znów ciągle "Service unavailable. Please try again in a few minutes."

**Comment by mareklemur** [comment]
przy aktualizacji oferty mam: Internal server error. Please try again in a few minutes.

**Comment by mirkosmuz** [comment]
U nas też wisi....
SERVICE_UNAVAILABLE

**Comment by bzyku87** [comment]
U mnie to samo... SERVICE_UNAVAILABLE

**Comment by mareklemur** [comment]
Doczekamy się jakiejś oficjalnej informacji o problemie i czasie jego rozwiązania?

**Comment by tomylee0** [comment]
Znowu zaczęło działać. Ale czy na długo...

**Comment by bzyku87** [comment]
Potwierdzam u mnie też aktualnie działa

**Comment by Adam1610** [comment]
U mnie też nie działa,  SERVICE_UNAVAILABLE

**Comment by misiaszek** [comment]
Zaczeło działać zamykanie przez Moje Konto. Przez REST nie działa ...

**Comment by mareklemur** [comment]
Sprzedały się niedostępne produkty, bo nie można było aktualizować dostępnych stanów. Co w tej sytuacji? Czy allegro będzie reagować na negatywne oceny wystawione przez niezawinioną przez nas sytuację? Na pewno nie:(

**Comment by PrzemyslawLukanowski** [comment]
Wczoraj w godzinach popołudniowo-wieczornych wystąpiły po naszej stronie problemy z edycją i wystawianiem ofert. Aktualnie procesy działają już prawidłowo. Przepraszam za utrudnienia.

**Comment by numerogeek** [comment]
Hello @PrzemyslawLukanowski 
We are launching our store on Allegro, and we have a lot of timeout issue.
Are you aware about this ?
Thank you

**Comment by Adam1610** [comment]
Znowu są problemy z API.. to chwilowe przeciążenia czy coś innego? @PrzemyslawLukanowski Nie przepraszaj za błędy tylko napisz konkretnie co sie dzieje..

**Comment by PrzemyslawLukanowski** [comment]
@numerogeek We will need sample offer IDs to verify this issue. Please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) and send us your logs. Add in the message the GitHub thread number - #3962.
@Adam1610 Prosiłbym o przykładowe logi lub numery ofert, abyśmy mogli bliżej przyjrzeć się tym przypadkom. Wyślij je za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), w zgłoszeniu dopisz, że dotyczy wątku GitHub #3962.

**Comment by PrzemyslawLukanowski** [comment]
@numerogeek We found out what caused this problem on our side. The problem occurred yesterday around 5:00 PM to 5:30 PM. If you still receive timeouts please use our contact form and send us sample logs.
@Adam1610 Udało nam się zlokalizować przyczynę tych błędów, w okolicach 17:00-17:30 odpowiadaliśmy wzmożoną liczbą 500, problem został zlokalizowany i usunięty. Jeśli nadam otrzymujesz błędy, prześlij proszę przykładowe logi.
