### ISSUE TITLE
Zliczanie sprzedaży

### ISSUE THREAD

**Issue by gorskimarcin96** [allegro/allegro-api#3966]
Dzień dobry, chcę wyliczać sumę zysków z zamówień dla konta MateMundo_PL. Pobieram zamówienia z zasobu: `/order/events`. Porównywałem dane, które pobrałem z api z danymi z podstrony: [/moje-allegro/sprzedaz/zamowienia/ ](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/?lineItems.boughtAt.gte=2020-11-29T23%3A00%3A00.000Z&lineItems.boughtAt.lte=2020-11-30T22%3A59%3A59.999Z) dnia 30 listopada. I w `/allegro/events` są zamówienia, które nie istnieją. Dlaczego? Zamówienia, które nie istnieją podaje w liście poniżej, każde zamówienie sprawdzałem na zasobie `/order/checkout-forms/{checkoutFormId}`.

1. 6cd052b4-3359-11eb-93f2-ed19eef398c1
2. 53234834-3355-11eb-a226-21af8529433d
3. 6af08544-3350-11eb-ac72-3faaa69b27ef
4. 4d6c0595-334f-11eb-a226-21af8529433d
5. aba197f5-334b-11eb-bb93-3b0a0ca08e0d
6. f083e653-3348-11eb-84d5-c5cf87be7c79
7. 7b687532-3347-11eb-858a-0373b5bef0fa
8. 1351acf2-3342-11eb-933c-fd4e5af5012c
9. 2be5aa83-333f-11eb-b262-650d2ff2aa38
10. 37c67763-333c-11eb-921b-d3a8756ae6a3
11. 850b7623-333b-11eb-ac72-3faaa69b27ef
12. cefbf6e2-3333-11eb-8cba-f7b8157d732c
13. 3e9b2804-332e-11eb-86fd-772ad366da2e
14. dfeee003-3326-11eb-ac72-3faaa69b27ef
15. 5d7eb195-3326-11eb-a226-21af8529433d
16. a9c8c4a3-331c-11eb-a657-f343d357c760
17. abb98302-331a-11eb-93f2-ed19eef398c1
18. cfd52996-3317-11eb-9bb0-435daa5dbc74
19. 673f3ee3-3315-11eb-a7b1-9b8479fc94b3
20. e18929b2-3313-11eb-b1f8-e70d8bc00b1a
21. 489667a4-330d-11eb-9775-170b755b622b
22. 2f923cc4-3308-11eb-82c8-09c2ef4b29f1
23. 67221f22-3303-11eb-81d0-99303cbd3db0
24. fba9f182-32ff-11eb-86fd-772ad366da2e
25. 09b57bb2-32ff-11eb-adb1-e7cfbc819362
26. 179dcdd3-32fb-11eb-86fd-772ad366da2e
27. c2e6a3c2-32fa-11eb-9bb0-435daa5dbc74
28. e0e24185-32f6-11eb-892c-25256091b02f
29. 17fea4c2-32f6-11eb-a37c-d337359dd7aa
30. 3112e3f4-32f5-11eb-8cba-f7b8157d732c
31. 9dacd642-32ed-11eb-b839-71c0b6554d5f
32. 8e32d9e5-32ec-11eb-b839-71c0b6554d5f
33. 91e6d6a2-32eb-11eb-81d0-99303cbd3db0
34. 48f43ee3-32e8-11eb-84d5-c5cf87be7c79
35. 26e65162-32e5-11eb-b29a-73203df2483d
36. 925db982-32d9-11eb-9cdc-8b54ae6b4a88
37. 8bf6a027-32d9-11eb-b148-836a80167384
38. 2deeb1a4-32d6-11eb-84d5-c5cf87be7c79
39. 1f01ecd8-32a3-11eb-858a-0373b5bef0fa
40. e534372b-32a1-11eb-87de-55a82531bb07
41. 98f23836-329c-11eb-81d0-99303cbd3db0
42. 146c9eb0-3299-11eb-976f-5b5d7ae82435

Chciałbym pobierać zamówienia i sprawdzać jaką mam sprzedaż dla poszczególnych dni. Dla przykładu wybrałem sobie 30 listopad. Wyliczam koszt, zamówienia ze statusem BOUGHT odejmuje z zamówienia ze statusem BUYER_CANCELLED. U mnie łączna kwota wynosi 23731.02zł za 30 listopad. Porównywałem moją kwotę z innymi serwisami internetowymi. Na [tradewatchu](https://tradewatch.pl/) mam 23 756,01 zł, a na [tradeanalytics](https://tradeanalytics.pl/). W jaki sposób mogę prawidłowo wyliczać sprzedaż?

![tradeanalytics](https://user-images.githubusercontent.com/32451056/101477925-338d5780-3950-11eb-9af5-529b3a5dc236.png)
![tradewatch](https://user-images.githubusercontent.com/32451056/101478037-5cade800-3950-11eb-90cb-3faa81f1e98b.png)

**Comment by PrzemyslawLukanowski** [comment]
Przez GET /order/checkout-forms/{checkoutFormId} próbujesz pobrać dane, będąc zautoryzowany jako sprzedawca, który nie jest właścicielem danego zamówienia, np.

146c9eb0-3299-11eb-976f-5b5d7ae82435 - właścicielem jest user o id 86917164, próbujesz pobrać jako 40298441;

9dacd642-32ed-11eb-b839-71c0b6554d5f - właścicielem jest o user o id 89486954, próbujesz pobrać jako 40298441;

Aby sprawdzić sprzedaż dla konkretnego dnia, w żądaniu GET /order/checkout-forms użyj parametrów:
- status=READY_FOR_PROCESSING - w ten sposób pobierzesz tylko opłacone zamówienia (oraz te, których płatność z góry nie dotyczy, np. z płatnością przy odbiorze);
- lineItems.boughtAt.lte i lineItems.boughtAt.gte - aby wskazać konkretny przedział czasowy;

Kwotę sprzedaży otrzymasz, dodając wartości określone w polu payment.paidAmount.amount. Musisz jednak mieć na uwadze, że kwota zamówień pobraniowych nie będzie wzięta pod uwagę.

Możesz także skorzystać z [GET /payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory), dzieki czemu sprawdzisz historię operacji na saldzie zalogowanego użytkownika.  Dla tego zasobu przygotowaliśmy także dodatkowy [poradnik](https://developer.allegro.pl/charges/#historia-operacji-p%c5%82atniczych).
