### ISSUE TITLE
Błąd INVALID_JSON przy wystawianiu ofert

### ISSUE THREAD

**Issue by Marekmintishop** [allegro/allegro-api#3968]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
**
[Response](https://mintishop.pl/panel/ajax/webservices.php?attachment=response&id=31764918&name=response_allegro_20201208_125451)

Błąd pojawiający się przy niektórych aukcjach przez IdoSell

**Comment by PrzemyslawLukanowski** [comment]
Załączone dane nie są kompletne - w pliku request brakuje informacji o ofercie, plik response jest pusty.

**Comment by Marekmintishop** [comment]
[res.txt](https://github.com/allegro/allegro-api/files/5659368/res.txt)
[req.txt](https://github.com/allegro/allegro-api/files/5659373/req.txt)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję. Błąd powoduje poniższy fragment w sekcji "parameters":
```
{"id": 225693,
	"values": [{
		"uniw": ""
	}]
	}
```

W polu values przekaż od razu prawidłową wartość dla numeru EAN.

**Comment by Marekmintishop** [comment]
Rozumiem, dziękuję za odpowiedź!
