### ISSUE TITLE
Błąd w nazwie formy dostawy. Problem z bezpieczeństwem - platforma fastbox

### ISSUE THREAD

**Issue by ZieGDA** [allegro/allegro-api#397]
Witam,

Mam 2 sprawy.

1) WEBapi zwraca nazwę Odbiór w punkcie -Allegro paczkomaty 24/7 inpost bez spacji między myślnikiem a frazą "Allegro", co powoduje zamieszanie w aplikacji, z której korzystamy. Fajnie by było, gdybyście to naprawili. Poniżej screen pokazujący o co chodzi.
![przechwytywanie](https://user-images.githubusercontent.com/39126621/42626561-f231547a-85ca-11e8-9c33-a755bfb09cd3.JPG)

2) Czy jesteście świadomi o działalności portalu fastbox.su ? Portal ten podpiął się pod allegro twierdząc, że są pośrednikiem między Waszym portalem a rosyjskimi klientami.
Udzielamy się na pewnym forum sprzedażowym i wiemy, że żaden ze sprzedawców na allegro nie wyrażał zgody na umieszczanie swojej własności intelektualnej na tym portalu.
Jeśli nie byliście świadomi problemu, należy to sprawdzić, bo wychodzi na to, że macie luki w zabezpieczeniach.
Przechowujecie nasze autorskie miniatury i zdjęcia na Waszych serwerach, a nagle pojawiają się one na jakiejś rosyjskiej platformie. Jota w jotę przekopiowane z Allegro.

Proszę o odpowiedź w tej drugiej kwestii. Jak to możliwe, że nasze materiały i aukcje znalazły się na tej stronie? Tylko bez wymijających odpowiedzi, bo już nam takich udzielano w tej kwestii. Sprawa jest bardzo poważna, bo ktoś łamie prawo i ten ktoś musi ponieść konsekwencje.

Pozdrawiam.

**Comment by AniaMalinowska** [comment]
Witamy @ZieGDA

1. Dziękujemy za sygnał, poprawiliśmy.

2. Wrócimy do Ciebie z informacją zwrotną, proszę o chwilę cierpliwości.

**Comment by ZieGDA** [comment]
Dziękuję za poprawkę, jest dużo wygodniej.

Czekam. Mam nadzieję, że nie będę musiał czekać tak długo jak w przypadku opiekuna TOP, który już od tygodnia wyjaśnia tą sprawę i od tamtego czasu nie odpowiada na żadną wiadomość ;)

**Comment by AniaMalinowska** [comment]
Allegro nie łączą żadne stosunki prawne z podmiotem prowadzącym działalność w ramach serwisu internetowego w domenie fastbox.ru. W szczególności Allegro nie zawarło żadnego rodzaju umów oraz w żaden sposób nie współpracuje z wyżej wymienionym podmiotem. Działania podejmowane w ramach serwisu internetowego w domenie fastbox.ru są działaniami podejmowanymi w sposób samodzielny i całkowicie niezależny od Allegro oraz na własną odpowiedzialność.

W przypadku, gdy w Twojej ocenie działania podmiotu prowadzącego działalność w ramach serwisu internetowego w domenie fastbox.ru naruszają Twoje prawa, powinieneś zgłosić takie naruszenie oraz żądać podjęcia odpowiednich działań bezpośrednio przez ten podmiot. 
Nie jesteśmy uprawnieni do podejmowania tego rodzaju działań w imieniu użytkowników.
