### ISSUE TITLE
Powiązanie wypłaty środków z zamówieniami

### ISSUE THREAD

**Issue by romigrabarz** [allegro/allegro-api#3970]
Czy istnieje możliwość sprawdzenia jakie opłacone zamówienia składają się na kwotę otrzymanego przelewu?
Np. mamy ustawione otrzymywanie przelewów za każdy dzień. o 2 w nocy generowany jest przelew na kwotę typu 10000 zł, a wynika z wpłat od kupujących, którzy złożyli 400 zamówień.
Czy jesteśmy w stanie jakoś wskazać które z zamówień zostały włączone do tej kwoty?

**Comment by hahyes** [comment]
Możliwe, że UUID płatności jest takie samo? Tylko podejrzewam, ale skoro w ramach jednej płatności w Allegro opłacono 400 zamówień, to raczej powinny mieć wspólne UUID płatności i pewnie też ten sam Unix timestamp (paymentFinishedAt).

**Comment by PrzemyslawLukanowski** [comment]
Nie ma bezpośredniej metody, która by to umożliwiła - możesz jedynie ustawić konkretny przedział czasowy dla [GET payments/payment-operations](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) i porównać, jakie wpłaty zostały wykonane do momentu zlecenia wypłaty. I tak jak napisał @hahyes powyżej - payment.id przy rekordach dot. wpłat (group=INCOME), będzie odpowiadać płatności dla konkretnego zamówienia.

**Comment by ipking** [comment]
Via api [https://api.allegro.pl/order/checkout-forms/c5e84f42-34a0-11eb-8b7e-2d8c396f094a] Get order details
The returned results are as follows:
`{
    "id": "c5e84f42-34a0-11eb-8b7e-2d8c396f094a",
    "messageToSeller": null,
    "buyer": {
        "id": "43713257",
        "email": "qosbf706vn+1c43a9ea7@allegromail.pl",
        "login": "herkules",
        "firstName": "Mateusz",
        "lastName": "Michalski",
        "companyName": "Fhu Herkules",
        "guest": false,
        "personalIdentity": null,
        "phoneNumber": "+48 666 686 696",
        "address": {
            "street": "Cmentarna 57",
            "city": "Dębica",
            "postCode": "39-200",
            "countryCode": "PL"
        }
    },
    "payment": {
        "id": "c63b9f61-34a0-11eb-8a37-3977d3e18761",
        "type": "ONLINE",
        "provider": "PAYU",
        "finishedAt": "2020-12-02T13:19:15.827Z",
        "paidAmount": {
            "amount": "85.99",
            "currency": "PLN"
        }
    },
    "status": "READY_FOR_PROCESSING",
    "fulfillment": {
        "status": "SENT",
        "shipmentSummary": {
            "lineItemsSent": "ALL"
        }
    },
    "delivery": {
        "address": {
            "firstName": "Mateusz",
            "lastName": "Michalski",
            "street": "Cmentarna 57",
            "city": "Dębica",
            "zipCode": "39-200",
            "countryCode": "PL",
            "companyName": "Fhu Herkules",
            "phoneNumber": "600124129",
            "modifiedAt": null
        },
        "method": {
            "id": "059c0d58-6cdb-4955-ab79-9031518f80f3",
            "name": "Kurier GLS"
        },
        "pickupPoint": null,
        "cost": {
            "amount": "0.00",
            "currency": "PLN"
        },
        "smart": false,
        "time": {
            "guaranteed": null
        },
        "calculatedNumberOfPackages": 1
    },
    "invoice": {
        "required": false,
        "address": null
    },
    "lineItems": [
        {
            "id": "c5e84f40-34a0-11eb-8b7e-2d8c396f094a",
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny",
                "external": {
                    "id": "ALL#LHSG1801BW"
                }
            },
            "quantity": 1,
            "originalPrice": {
                "amount": "85.99",
                "currency": "PLN"
            },
            "price": {
                "amount": "85.99",
                "currency": "PLN"
            },
            "selectedAdditionalServices": [],
            "boughtAt": "2020-12-02T13:18:45.081Z"
        }
    ],
    "surcharges": [],
    "discounts": [],
    "summary": {
        "totalToPay": {
            "amount": "85.99",
            "currency": "PLN"
        }
    },
    "updatedAt": "2020-12-02T13:19:15.827Z",
    "revision": "b3a81206"
}`

Find where the lineItem id is [ 9886045529 ]

Via api [https://api.allegro.pl/billing/billing-entries?type.id=SUC&offer.id=9886045529]Get a list of bills
  The returned results are as follows: 
 `{
    "billingEntries": [
        {
            "id": "df9e5940-5041-460c-bb69-7faa062026da",
            "occurredAt": "2020-12-10T14:38:50.153Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-5.85",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-456.70",
                "currency": "PLN"
            }
        },
        {
            "id": "39fe7234-cb0a-4111-ad32-70857ba767a3",
            "occurredAt": "2020-12-02T13:18:46.183Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-6.88",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-76.75",
                "currency": "PLN"
            }
        },
        {
            "id": "57cfdce0-ec3c-47a8-ac63-1820c72f2658",
            "occurredAt": "2020-11-30T22:07:21.188Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-6.20",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-1451.92",
                "currency": "PLN"
            }
        },
        {
            "id": "7a261ee2-0c36-49d5-b771-1715933369a7",
            "occurredAt": "2020-11-29T11:10:26.172Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-6.20",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-1347.35",
                "currency": "PLN"
            }
        },
        {
            "id": "0f17e907-a8cb-458b-a07e-fffd0c1bcf65",
            "occurredAt": "2020-11-29T07:58:48.298Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-6.20",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-1348.01",
                "currency": "PLN"
            }
        },
        {
            "id": "9614d4f3-bf0a-492b-819f-9451aa86cebb",
            "occurredAt": "2020-11-24T04:11:08.155Z",
            "type": {
                "id": "SUC",
                "name": "Prowizja od sprzedaży"
            },
            "offer": {
                "id": "9886045529",
                "name": "DOZOWNIK DO PŁYNU MYDŁA DO ZLEW ZLEWOZMYWAK Czarny"
            },
            "value": {
                "amount": "-6.88",
                "currency": "PLN"
            },
            "tax": {
                "percentage": "23"
            },
            "balance": {
                "amount": "-869.84",
                "currency": "PLN"
            }
        }
    ]
}`

Cannot get the order commission of the order id [c5e84f42-34a0-11eb-8b7e-2d8c396f094a] through the information here

**Comment by PrzemyslawLukanowski** [comment]
@ipking We will respond to your question via email because we've received it also via this channel.
