### ISSUE TITLE
Nieautoryzowana zmiana cen

### ISSUE THREAD

**Issue by 83krynio** [allegro/allegro-api#3971]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [X ] inny

:beetle: **Opis**

E-mail Od Allegro w dniu 2020-11-26 10:34

Nieautoryzowana zmiana cen w ofercie:
Sprzedałeś przedmiot przez Kup Teraz - nr: 9911559608 - Zabawka Epee Królik Tusia szary.
Zabawka Epee Królik Tusia szary(9911559608)1 sztuka4,00 zł
Numer zamówienia: 78b37c22-2fca-11eb-b4b8-9bc2c5257873

Proszę o wyjaśnienie sytuacji do której doszło dnia 26.11.2020 - ceny zmieniały się same, a w tradeanalytics wyświetlane godziny były podawane z przyszłości.
![tusia](https://user-images.githubusercontent.com/49755684/101623451-c1347a00-3a18-11eb-979a-6c542a466986.JPG)

Poniżej korespondencja z allegro:
User-added image

Dziękuję za odpowiedź.

Już wyjaśniam. Niestety nie mam możliwości przekazania zgłaszanej przez Pana sprawy, tutaj musi to już Pan zrobić samodzielnie. Tego typu sprawami zajmuje się zespół ekspercki API, więc tak jak już wspomniałam w zgłoszonej przez Pana sprawie najlepszym rozwiązaniem będzie przesłanie zgłoszenia bezpośrednio poprzez ścieżkę przeznaczoną dla API. W tym celu proszę by skorzystał Pan z poniższego linku:

https://github.com/allegro/allegro-api

Dzięki temu sprawa trafi do ekspertów tej dziedziny i tym samym:

- skrócimy czas oczekiwania na odpowiedź,
- zachowamy ciągłość korespondencji na wypadek ewentualnych pytań z naszej strony.

Proszę przejść do zakładki Issues, założyć nowe zadanie i skorzystać z odpowiedniego szablonu. Proszę pamiętać, aby w zgłoszeniu podać jak najwięcej dokładnych informacji - dzięki temu szybciej będziemy mogli Panu pomóc.

Na wspomnianej stronie odpowiadamy na wszystkie pytania, sugestie i zgłoszenia, które dotyczą API. Co więcej:

- na bieżąco wyjaśniamy co i dlaczego zmieniamy;
- dbamy o dokładny opis zmian;
- opisujemy przykładowe wywołania i odpowiedzi;
- zmiany staramy się zapowiadać z wyprzedzeniem.

W razie pytań pozostaję do dyspozycji.

Pozdrawiam
// Paulina Nerwińska
Zespół Allegro

550x220

Allegro.pl sp. z o.o. z siedzibą w Poznaniu, przy ul. Grunwaldzkiej 182, 60-166 Poznań, wpisana do rejestru przedsiębiorców prowadzonego przez Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS: 0000635012, kapitał zakładowy: 33 016 950 złotych, posiadająca numer identyfikacji podatkowej NIP 525-26-74-798, REGON 365331553

 
 

--------------- Wiadomość oryginalna ---------------
Od: [z]
Wysłane: 26.11.2020 14:53
Do: allegro.kontakt@allegro.pl
Temat: Re: Odpowiedź na zgłoszenie nr "12260246" [ ref:_00D24aE05._5003V7jaZt:ref ]

Proszę przekazać to do odpowiedniego działu. Ja nie znam się na tym.
Numer oferty i wszystkie informacje jakie mogłem udzielić znajdują się w
naszej korespondencji.
Dziękuję i czekam na dalsze informacje.

W dniu 2020-11-26 14:36, Allegro Kontakt napisał(a):
> Dziękuję za odpowiedź.
>
> Widzę, że kwestia, o której Pan napisał, będzie wymagała
> odpowiedzi zespołu eksperckiego, który zajmuje się wsparciem w
> sprawach dotyczących API.
>
> Aby przyspieszyć proces weryfikacji sprawy, proszę, by utworzył Pan
> zgłoszenie na wyznaczonym dla tego typu zapytań forum GitHub:
>
> https://github.com/allegro/allegro-api/issues [1]
>
> Proszę przejść do zakładki Issues, założyć nowe zadanie i
> skorzystać z odpowiedniego szablonu. Proszę pamiętać, aby w
> zgłoszeniu podać jak najwięcej dokładnych informacji - dzięki
> temu szybciej będziemy mogli Panu pomóc.
>
> Na forum odpowiadamy na wszystkie pytania, sugestie i zgłoszenia,
> które dotyczą API. Wsparcie zapewniamy w języku polskim i
> angielskim.
>
> Pozdrawiam
> // Paulina Nerwińska
> Zespół Allegro
>
> [2]
>
> Allegro.pl sp. z o.o. z siedzibą w Poznaniu, przy ul. Grunwaldzkiej
> 182, 60-166 Poznań, wpisana do rejestru przedsiębiorców
> prowadzonego przez Sąd Rejonowy Poznań - Nowe Miasto i Wilda w
> Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego pod
> numerem KRS: 0000635012, kapitał zakładowy: 33 016 950 złotych,
> posiadająca numer identyfikacji podatkowej NIP 525-26-74-798, REGON
> 365331553
>
> --------------- Wiadomość oryginalna ---------------
> Od: [z]
> Wysłane: 26.11.2020 14:15
> Do: allegro.kontakt@allegro.pl
> Temat: Re: Odpowiedź na zgłoszenie nr "12260246" [
> ref:_00D24aE05._5003V7jaZt:ref ]
>
> Dzień dobry,
> Nie, nie korzystam.
>
> W dniu 2020-11-26 13:47, Allegro Kontakt napisał(a):
>> Dzień dobry,
>>
>> dziękuję za wiadomość.
>>
>> Bardzo chętnie Panu pomogę w wyjaśnieniu zaistniałej sytuacji,
>> proszę jednak o informację, czy korzysta Pan z jakiegoś
> narzędzia
>> do wystawiania i edycji ofert? Przekazane przez Pana informacje
>> pomogą mi w ustaleniu przyczyny zaistniałego problemu oraz
>> rozwiązanie go.
>>
>> Czekam na Pana odpowiedź.
>>
>> Pozdrawiam
>> // Paulina Nerwińska
>> Zespół Allegro
>>
>> [1]
>>
>> Allegro.pl [3] sp. z o.o. z siedzibą w Poznaniu, przy ul.
> Grunwaldzkiej
>> 182, 60-166 Poznań, wpisana do rejestru przedsiębiorców
>> prowadzonego przez Sąd Rejonowy Poznań - Nowe Miasto i Wilda w
>> Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego pod
>> numerem KRS: 0000635012, kapitał zakładowy: 33 016 950 złotych,
>> posiadająca numer identyfikacji podatkowej NIP 525-26-74-798, REGON
>> 365331553
>>
>> --------------- Wiadomość oryginalna ---------------
>> Od: [z]
>> Wysłane: 26.11.2020 11:00
>> Do: allegro.kontakt@allegro.pl
>> Temat: Mam pytanie o wystawianie lub edycję oferty
>>
>> Dzień dobry,
>> Proszę o wyjaśnienie sytuacji związanej z nieautoryzowaną
> zmianą
>> ceny w ofercie:9911559608
>>
>> W TradeAnalytics widzę:
>> Zmiana ceny
>> 26 lis 2020, 11:20:39
>>
>> A jest 10:47
>>
>> ref:_00D24aE05._5003V7jaZt:ref
>>
>> Links:
>> ------
>> [1]
>>
> http://allegro.pl/kampania/akademia-allegro/wez-udzial-w-akcji-black-week-cyber-monday-2020-na-allegro
>
>
>
> Links:
> ------
> [1] https://github.com/allegro/allegro-api/issues
> [2]
> http://allegro.pl/kampania/akademia-allegro/wez-udzial-w-akcji-black-week-cyber-monday-2020-na-allegro
> [3] https://Allegro.pl

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi - zmianę ceny na 4zł wykonał zautoryzowany użytkownik 22183495 w dniu 2020-11-26 o godz. 10:20 za pomocą aplikacji mobilnej Allegro na iOS.

**Comment by 83krynio** [comment]
A poprzednia zmiana ceny na 190, czy coś około 199?
Prosiłbym o przesłanie wszystkich zmian ceny produktu w tym dniu w takiej właśnie formie jak poprzednio.

**Comment by PrzemyslawLukanowski** [comment]
W dniu 26.11.10 to była jedyna zmiana ceny. Jej podwyższenie na 199.99zł miało miejsce 2020-11-23 o godz. 12:49 i nie nastąpiło  przez API, ale przez naszą stronę internetową.
