### ISSUE TITLE
[POST] /digital-content/files - Pliki cyfrowe

### ISSUE THREAD

**Issue by marlemiesz** [allegro/allegro-api#3972]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: 6a6992f88c73dba1

Podczas dodawania pliku do biblioteki otrzymujemy "An error has occurred", proszę o werfikację.

**Comment by PrzemyslawLukanowski** [comment]
Zasób nie jest dostępny publicznie, dlatego skontaktuj się proszę w pierwszej kolejności ze swoim opiekunem handlowym, aby sprawdzić czy zostały spełnione wszystkie warunki, aby móc korzystać z tych endpointów.

**Comment by marlemiesz** [comment]
Mamy informację, że możemy korzystać z podanych endpointów. Proszę o weryfikację. ( trace-id: d6975c16a1254ef3 )

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przez swojego opiekuna handlowego przykładowy request, dla którego otrzymujesz tę odpowiedź. W naszych logach nie widzimy pełnej struktury tego żądania.
