### ISSUE TITLE
GET sale/products?ean nie pokazuje produktu

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#3973]
Witam,

Mam problem z zasobem **sale/products** i wyszukiwaniem po **EAN**.

Środowisko Sandbox, EAN z poradnika https://developer.allegro.pl/productization/#sandbox

`GET sale/products?ean=9780000000057 || trace-id:2034ec7eaf3ffbd0`

Zwraca 
`"{"products":[],"categories":{"subcategories":[{"id":"5","name":"Dom i Ogród","count":0},{"id":"11763","name":"Dziecko","count":0},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","count":0},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma i usługi","count":0},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","count":0},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","count":0},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","count":0},{"id":"3","name":"Motoryzacja","count":0},{"id":"20782","name":"Nieruchomości","count":0},{"id":"3919","name":"Sport i turystyka","count":0},{"id":"258832","name":"Supermarket","count":0},{"id":"1429","name":"Uroda","count":0},{"id":"121882","name":"Zdrowie","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[],"nextPage":null}`

Natomiast produkt na pewno istnieje

`"GET sale/products/0cb89863-9bd0-4f92-b364-16ec3908201c? || trace-id:cb4596c67d98892c"`

`{"id":"0cb89863-9bd0-4f92-b364-16ec3908201c","name":"Tytus internautą. Księga XXVIII TYTUS, ROMEK I A'TOMEK Henryk Jerzy Chmielewski for Integration Testing","category":{"id":"66793"},"parameters":[{"id":"245669","name":"ISBN","valuesLabels":["9780000000057"],"values":["9780000000057"],"unit":null,"options":{"identifiesProduct":true,"isGTIN":true}},{"id":"7773","name":"Okładka","valuesLabels":["miękka"],"valuesIds":["7773_1"],"values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"74","name":"Rok wydania","valuesLabels":["2015"],"values":["2015"],"unit":null,"options":{"identifiesProduct":true}},{"id":"7453","name":"Przedział wiekowy","valuesLabels":["dla dzieci z klas I-III (6-9 lat)"],"valuesIds":["7453_4"],"values":null,"unit":null,"options":{"identifiesProduct":false}}],"images":[],"eans":["9780000000057"],"offerRequirements":{"parameters":[]},"compatibilityList":null,"tecdocSpecification":null}`

Co robię źle? Dziękuję za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam ten problem, przekazałem go do odpowiedniego zespołu. Wrócę z odpowiedzią po wyeliminowaniu błędu.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski problem występuje również na serwerze produkcyjnym

`GET sale/products?ean=9999316994 || trace-id:e6b52b09e8de08fa`

**Comment by PrzemyslawLukanowski** [comment]
Dopisałem ten przykład do zgłoszenia.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , przepraszam, skopiowałem nie to pole, na produkcji jest OK ( trace-id:7fba891b00c8a755 )
