### ISSUE TITLE
Zapytanie do API o nadchodzace oplaty użytkownika

### ISSUE THREAD

**Issue by bartOlech** [allegro/allegro-api#3974]
Czy jest możliwość wysłania requesta zwracającego **wszystkie nadchodzące opłaty uwierzytelnionego użytkownika / sprzedawcy**? 
Jeśli tak, pod jaki endpoint mogę wysłać takie zapytanie?

**Comment by PrzemyslawLukanowski** [comment]
Możesz sprawdzić nadchodzące opłaty tylko dla wybranych ofert za pomocą [GET /pricing/offer-quotes](https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET). Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/charges/#data-naliczenia-kolejnej-op%c5%82aty).
