### ISSUE TITLE
Przekroczono ilość znaków w tytule (50) mimo iż tytuł ma 50 znaków - które znaki allegro liczy podwójnie?

### ISSUE THREAD

**Issue by pawliszka** [allegro/allegro-api#3975]
Witam serdecznie,

z API dostaję następujący komunikat: 
The maximum allowed length of the offer title has been exceeded (50 characters, assuming that some letters and symbols are counted as more than 1 character).

Tytuł aukcji: "CHŁODNICA KLIMATYZACJI MITSUBISHI COLT VI 04-12" -> długość 47znaków (48znaków jeśli Ł liczone podwójnie)

- Czy wszystkie znaki diakrytyczne liczone są jako 2 znaki lub więcej? 
- Jaka jest poprawna metoda wyznaczania długości ciągu znaków dla allegro? 

Dziękuję i pozdrawiam Paweł Liszka.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, przekazałem powyższą nazwę prawidłowo. Czy posiadasz może trace-id dla wywołania?

**Comment by pawliszka** [comment]
@PrzemyslawLukanowski wywołania do tworzenia oferty (POST), aktywacji oferty PUT /sale/offer-publication-commands/{commandUUID} czy odpytania statusu GET /sale/offer-publication-commands/{commandUUID} ? 

Błąd otrzymuję dopiero w GET /sale/offer-publication-commands/{commandUUID} w polu errors

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę w takim razie powiązany commandUUID.

**Comment by pawliszka** [comment]
hmm, do zamknięcia, nie jestem w stanie tego już zreprodukować, teraz wygląda na to że wszsytko działa odbija faktycznie tylko te z długością powyżej 50 znaków, ewentualnie pozwolę sobie otworzyć gdyby problem w przyszłości się pojawił :)
