### ISSUE TITLE
Typ konta sprzedawcy allegro w zasobie GET /me

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#3976]
:bulb: **Sugestia**
Dzień dobry, buduję proces grupowego wystawiania aukcji i kompletuje pełne oferty. Na etapie zbierania danych nie są tworzone od razu drafty. Do sprawdzenia poprawności wszystkich danych jest potrzebny typ konta (type: "Person" oraz type: "Company"), który jest zwracany w serwisie www w momencie edycji oferty. Od tego typu przede wszystkim zależy wymagalność uzupełnienia warunków zwrotów i reklamacji.

Zwracam się zatem z prośbą o dodanie pola type: "Person" oraz type: "Company" do zasob rest api GET /me

Formularz dla konta firma z wymaganymi politykami:
![image](https://user-images.githubusercontent.com/8465007/101777264-83a41f80-3af2-11eb-9964-82f30dff0bd4.png)

Formularz dla konta dla osoby fizycznej z opcjonalnymi politykami:
![image](https://user-images.githubusercontent.com/8465007/101777122-4e97cd00-3af2-11eb-86e3-356c2d67600b.png)

**Comment by PrzemyslawLukanowski** [comment]
Zapisałem Twoje zgłoszenie do listy naszych sugestii. Jeśli zdecydujemy się wprowadzić to pole, opublikujemy odpowiedni komunikat.

**Comment by alekskuc** [comment]
Dodam jeszcze, że ilość zdjęć w ofercie także zależy od typu konta sprzedawcy, bo dla zwykłego jest 10, a dla firmy 16. 

Brak z góry określonego typu konta musi bazować na obsłudze błędów tworzenia draftów i ponawianych próbach dodawania ofert, co jest nieoptymalne.
