### ISSUE TITLE
Podatek VAT w ofertach

### ISSUE THREAD

**Issue by RaVq3K** [allegro/allegro-api#3979]
Witam, pobierając ofertę przez zasób 
https://developer.allegro.pl/documentation/#operation/getOfferUsingGET

 istnieje tam pole podatek (TAX), w jaki sposób można ręcznie dodać podatek do oferty aby go pobrać?.

**Comment by PrzemyslawLukanowski** [comment]
Możesz to zrobić za pomocą PUT /sale/offers/{Id} (gdy edytujesz ofertę) i POST /sale/offers (gdy wystawiasz ofertę), dodaj wtedy do struktury oferty poniższe pole, w ofercie musisz mieć wybraną opcję faktura VAT:
```
    "tax": {
        "percentage": "5.00"  - dostępne wartości to "0.00", "5.00", "8.00" lub "23.00"
    },
```

Możesz to zrobić także za pomocą grupowej edycji, przykład znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#informacje-o-fakturze).

**Comment by RaVq3K** [comment]
Chodziło mi o to czy można to gdzies wyklikać na https://allegro.pl.allegrosandbox.pl/

**Comment by PrzemyslawLukanowski** [comment]
Tak, [wystaw ofertę ](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie) i uzupełnij to pole w tym miejscu:
![Screenshot_21](https://user-images.githubusercontent.com/51473661/101880662-91f64800-3b93-11eb-84fb-2142b4a775dd.png)

**Comment by RaVq3K** [comment]
Dziękuje :+1:

**Comment by RaVq3K** [comment]
Dostałem jeszcze informację od Testera że u niego te pola sie nie pokazują czy cos jeszcze trzeba ustawić?

**Comment by PrzemyslawLukanowski** [comment]
Czy user posiada konto firmowe? Jeśli nie, niech wejdzie w [tę zakładkę](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta/) i przy "Rodzaj konta" wybierze "zmień na konto firmowe". Następnie należy wysłać dwa dowolne pliki przez zakładkę [Dane konta Allegro](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php). Jeśli nadal będą występować problemy, to poproszę o login lub ID usera.
