### ISSUE TITLE
niewypełniony formularz pozakupowy a cena produktu

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#398]
Czy istnieje możliwość uzyskania przez api ostatecznej ceny zamówionych przez klienta produktów w przypadku kiedy klient nie wypełnił formularza pozakupowego?

**Comment by AniaMalinowska** [comment]
Skorzystaj z metody [doGetDeals](https://allegro.pl/webapi/documentation.php/show/id,462#method-input). Zachęcam też, aby zapoznać się z tym [tutorialem](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421) - na dole tej strony opisaliśmy, jak pobierać informacje o cenach.
