### ISSUE TITLE
jesteśmy firmą przedającą na allegro. mam pyt dot integracji hurtowników

### ISSUE THREAD

**Issue by sportenga** [allegro/allegro-api#3980]
Witam, prosiłbym o wskazanie firm- hurtowni takich jak np. AB SA ktorzy sa naszym dostawcą lub podobnych ktore to maja obustronna integrację z allegro i działają podobnie jak AB SA. Branza nie ma znaczenia. Mozecie nam takie hurtownie wskazac?

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadamy bazy takich firm. Na forum prowadzimy wsparcie techniczne dot. publicznych zasobów API.
