### ISSUE TITLE
Brak spójności w danych

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#3981]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie wiem co się podziało w transakcji `cd27dbed-3ac2-11eb-b4c8-87104f45a254` (mam kilka innych z tym problemem - poniżej), ale jest jakaś niespójność, którą nie można wyłapać analizując samego journala.

Nie wiem czy to nie jest powiązane z https://allegro.pl/dla-sprzedajacych/juz-niebawem-kupujacy-zmieni-dane-dostawy-po-zakupie-5L5X01PMvHV - nie jestem w stanie w panelu znaleźć opcji wyłączania tego bajeru.

Najpierw w journal odnotowuje taki event:
```
{
  "id": "1607590365015341",
  "type": "READY_FOR_PROCESSING",
  "order": {
    "buyer": {
      "id": "4092350",
      "email": "vzyxl384ww+16c5acc04@allegromail.pl",
      "guest": false,
      "login": "vaults"
    },
    "seller": {
      "id": "44294360"
    },
    "lineItems": [
      {
        "id": "cd27dbe6-3ac2-11eb-b4c8-87104f45a254",
        "offer": {
          "id": "8965105892",
          "name": "Drzwi percepcji. Niebo i piekło. Aldous Huxley",
          "external": {
            "id": "I8965105892P788915"
          }
        },
        "price": {
          "amount": "16.01",
          "currency": "PLN"
        },
        "boughtAt": "2020-12-10T08:37:35.448Z",
        "quantity": 1,
        "originalPrice": {
          "amount": "16.01",
          "currency": "PLN"
        }
      },
      {
        "id": "cd27dbe7-3ac2-11eb-b4c8-87104f45a254",
        "offer": {
          "id": "8741217418",
          "name": "Nowy wspaniały świat 30 lat później. Aldous Huxley",
          "external": {
            "id": "I8741217418P779260"
          }
        },
        "price": {
          "amount": "20.94",
          "currency": "PLN"
        },
        "boughtAt": "2020-12-10T08:37:35.448Z",
        "quantity": 1,
        "originalPrice": {
          "amount": "20.94",
          "currency": "PLN"
        }
      },
      {
        "id": "cd27dbe8-3ac2-11eb-b4c8-87104f45a254",
        "offer": {
          "id": "8014149514",
          "name": "Nowy wspaniały świat. Huxley Aldous. Muza",
          "external": null
        },
        "price": {
          "amount": "15.79",
          "currency": "PLN"
        },
        "boughtAt": "2020-12-10T08:37:35.448Z",
        "quantity": 1,
        "originalPrice": {
          "amount": "15.79",
          "currency": "PLN"
        }
      }
    ],
    "checkoutForm": {
      "id": "cd27dbed-3ac2-11eb-b4c8-87104f45a254",
      "revision": "31632a8f"
    }
  },
  "occurredAt": "2020-12-10T08:52:30.619Z"
}
```
Natychmiast po jego stwierdzeniu pobieram dane przez `GET /order/checkout-forms/cd27dbed-3ac2-11eb-b4c8-87104f45a254` i dostaje taką transakcję (zostawiłem sedno):
```
{
  "id": "cd27dbed-3ac2-11eb-b4c8-87104f45a254",
  ...
  "delivery": {
    "cost": {
      "amount": "0.00",
      "currency": "PLN"
    },
    "time": {
      "guaranteed": null
    },
    "smart": true,
    "method": {
      "id": "849a8308-240d-4045-ab30-f8207815bce4",
      "name": "Allegro Punkty Poczta, Żabka, Orlen, Ruch"
    },
    ...
    "pickupPoint": {
      "id": "ZGI05N",
      "name": "Paczkomat ZGI05N",
      "address": {
        "city": "Zgierz",
        "street": "Boya Żeleńskiego 23B",
        "zipCode": "95-100"
      },
      "modifiedAt": null,
      "description": "Przy aptece Verbena"
    },
    "calculatedNumberOfPackages": 1
  },
  "updatedAt": "2020-12-10T08:52:30.619Z",
  "revision": "31632a8f",
  ...
}
```
updatedAt i revision identyczne jak w journal. Proszę spojrzeć na `method` i `pickupPoint` - nie ma to sensu - punkt i dane paczkomatu.

Po zgłoszeniu mi problemu (dane w panelu nie pokrywają się z Allegro) - ponownie wywołałem `GET /order/checkout-forms/cd27dbed-3ac2-11eb-b4c8-87104f45a254`:

```
{
  "id": "cd27dbed-3ac2-11eb-b4c8-87104f45a254",
  "delivery": {
    ...
    "method": {
      "id": "849a8308-240d-4045-ab30-f8207815bce4",
      "name": "Allegro Punkty Poczta, Żabka, Orlen, Ruch"
    },
    "pickupPoint": {
      "id": "939064",Pode
      "name": "Kiosk/Salonik RUCH",
      "description": null,
      "address": {
        "street": "Stanisława Witkacego 1/3",
        "zipCode": "95-100",
        "city": "Zgierz"
      },
      "modifiedAt": null
    },
    "cost": {
      "amount": "0.00",
      "currency": "PLN"
    },
    "smart": true,
    "time": {
      "guaranteed": null
    },
    "calculatedNumberOfPackages": 1
  },
  ...
 "updatedAt": "2020-12-10T08:52:30.619Z",
  "revision": "522c3eb6"
}
```

I tu moje zdziwienie, ze wszystko jest OK. `revision` się zmieniło. `updatedAt` - bez zmian - żadnych informacji w journalu, ze te dane się zmieniły.

O co chodzi?

Edit: Transakcje:
paczkomat->poczta
f43d96b3-3b0e-11eb-aa0c-b516fe59fd52
10fe4646-3ac5-11eb-9433-b1b316b1aac1
cabef265-3ae7-11eb-9433-b1b316b1aac1
cd27dbed-3ac2-11eb-b4c8-87104f45a254
c48058c2-3a5c-11eb-9433-b1b316b1aac1

ruch->paczkomat
1436c354-3a75-11eb-964a-1b83616119f4

paczkomat->ruch
1e39bac8-3aba-11eb-afa1-b50015936909
508b3bf2-3639-11eb-947b-156113aede3b

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Rzeczywiście wygląda to na problem z rozbieżnością danych, jednak nie dopatrywałbym się tutaj przyczyny we wskazanym linku - zgodnie z naszym [newsem](https://github.com/allegro/allegro-api/issues/3831) możliwość edycji adresu dostawy przez kupującego udostępnimy dopiero w styczniu 2021r. Przekażę ten problem do odpowiedniego zespołu, który zajmie się jego weryfikacją.

**Comment by pgasidlo** [comment]
Idealnie gdyby journal informował o każdorazowej zmianie `revision`. Po mojej stronie bym musiał dodatkowo weryfikować czy `revision` transakcji pokrywa się z `revision` z journala.

**Comment by PrzemyslawLukanowski** [comment]
@pgasidlo Zweryfikowałem ten temat - problem po naszej stronie został naprawiony i takie sytuacje nie powinny już się powtórzyć.
