### ISSUE TITLE
Przypisanie cennika hurtowego nie działa

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#3982]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przypisanie cennika hurtowego do oferty nie wykonuje się poprzez /sale/offer-modification-commands/{commandId}
Prosimy o weryfikację przykładowych request/response dla przypisania cennika (przypisanie w ten sposób nie działa również na żadnej innej ofercie na tym koncie)

**Request przypisania cennika:**
`PUT https://api.allegro.pl/sale/offer-modification-commands/14872a78-ce20-47a3-a09c-f519136703e8 HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer {TOKEN}
Accept: application/vnd.allegro.public.v1+json
Connection: Keep-Alive
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 175

{"modification":{"discounts":{"wholesalePriceList":{"Id":"4c43ba6a-a9a9-47c1-a653-562eee1b7d27"}}},"offerCriteria":[{"offers":[{"id":"9443374729"}],"type":"CONTAINS_OFFERS"}]}`

**Response przypisania cennika:**
`
HTTP/1.1 201 Created
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 512cc1fc4b2007fa
date: Fri, 11 Dec 2020 07:13:10 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 92

{"id":"14872a78-ce20-47a3-a09c-f519136703e8","taskCount":{"total":0,"success":0,"failed":0}}
`

**Sprawdzenie wyniku przypisania cennika - request:**
`GET https://api.allegro.pl/sale/offer-modification-commands/14872a78-ce20-47a3-a09c-f519136703e8/tasks?limit=1000 HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer {token}
Connection: Keep-Alive
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 0
`

**Sprawdzenie wyniku przypisania cennika - response:**
`HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 7c0b23b3e5292fea
date: Fri, 11 Dec 2020 07:14:21 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
content-length: 185

{"tasks":[{"offer":{"id":"9443374729"},"message":"","status":"SUCCESS","scheduledAt":"2020-12-11T07:13:12.472Z","finishedAt":"2020-12-11T07:13:12.47Z","field":"discounts","errors":[]}]}
`

Mimo feedbacku o poprawnym przypisaniu GET /sale/offers/9443374729 zwraca w polu discounts: null, jak i filtrowanie w panelu www po tej aukcji i przypisanych cennikach hurtowych zwraca pustą listę.

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach dla tego commandId widnieje informacja, że jako wholesalePriceList.id przekazałeś null, dlatego dalsze informacje są zgodne z prawdą. Czy to commandId nie zostało wykorzystane po raz drugi w zgłoszeniu powyżej? Spróbuj powtórzyć request z nowym numerem commandId, dodatkowo zamiast "Id" w polu **wholesalePriceList** przekaż proszę "id".

**Comment by cyfranT** [comment]
Dzięki, przyczyną było "Id" zmiast "id" :)
