### ISSUE TITLE
Słownik/dokumentacja parametrów w danych kategoriach

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#3983]
Czy istnieje jakaś dokumentacja wszystkich parametrów dostępnych dla danych kategorii? Czy należy samemu robić sobie zapytanie `GET /sale/categories/{categoryId}/parameters`? Gdy np. pobieram szczegóły oferty używając `GET /sale/offers/7678940112` to w parametrach są same id bez nazw. Jak mogę znaleźć nazwę po id parametru? 

Np. wiem, że numer OE ma id 215858, gdzie mogę znaleźć te informację? Gdy robię zapytanie wolałbym wiedzieć jaki dokładnie parametr pobieram bez komentarzy co oznacza te id. Tzn. zrobiłbym sobie jakiegoś enuma, stałą lub tablice wszystkich nazw i przyporządkowanych id i pobierałbym id po nazwie.

**Comment by PrzemyslawLukanowski** [comment]
Nie posiadamy takiej dokumentacji. Aby sprawdzić parametry dostępne w dane kategorii, musisz - tak jak napisałeś - odpytać GET /sale/categories/{categoryId}/parameters.
