### ISSUE TITLE
Słabe wyniki dla sugestii kategorii pojazdu

### ISSUE THREAD

**Issue by robert0770** [allegro/allegro-api#3984]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

![Screenshot_2020-12-11 Screenshot](https://user-images.githubusercontent.com/27285562/101941567-76695c80-3be8-11eb-8fcc-e36805b9dde1.png)

Dlaczego takie słabe wyniki wypluwa zasób:
/sale/matching-categories
dla każdego pojazdu?

sprawdzałem na stronie allegro podobne wyniki, to chwilowy błąd czy standardowo takie słabe sugestie dajecie dla pojazdów?

**Comment by PrzemyslawLukanowski** [comment]
Zasób aktualnie zwraca 10 propozycji - są to wyniki zgodne z frontem. Jeżeli uważasz, że powinno ich być więcej lub powinny być inne, zgłoś proszę sugestię przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
