### ISSUE TITLE
GET /order/checkout-forms nie zwraca nowych transakcji

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#3985]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Prosimy o zweryfikowanie wyników zwracanych przez poniższy request na koncie ksiazki-24h.

Request:
`GET /order/checkout-forms?status=ALL&offset=0 HTTP/1.1`

W odpowiedzi otrzymujemy jako pierwszy wynik "checkoutForm": z id "18051528-381f-11eb-84c0-1fd57dcb6577" , tj . zakup z 7.12 z godz. 1:10 i kolejne starsze transakcje. Brak wyników o nowych transakcjach.

**Comment by PrzemyslawLukanowski** [comment]
Zasób zwraca nowe zamówienia - jako pierwsze 3ba7b1b2-3ddb-11eb-bdc6-05fec90e9f2d z dzisiaj. Po naszej stronie nie odnotowaliśmy opóźnień w przetwarzaniu zamówień w dniu 12.12.2020

**Comment by cyfranT** [comment]
Tak, teraz już działa poprawnie. Opisany przeze mnie problem występował od 11.12 godz. ~17 do 13.12 do godz. ~18:30. W tym okresie zasób nie zwracał nowych zamówień.

**Comment by cyfranT** [comment]
Dodam, że pobieramy tym zasobem zamówienia z kilkunastu różnych kont i problem występował tylko na jednym koncie ksiazki-24h

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy nasze logi dla tego konta, jednak nie odnotowaliśmy żadnych problemów po naszej stronie. Nowe zamówienia były dostępne na bieżąco.
