### ISSUE TITLE
ZNÓW NIE POJAWIAJĄ SIĘ WIADOMOŚCI WYSŁANE W CENTRUM WIADOMOŚCI 

### ISSUE THREAD

**Issue by akxx87** [allegro/allegro-api#3986]
PO WYSŁANIU MAILA DO KUPUJĄCEGO NIE POJAWIA SIĘ ON W CENTRUM WIADOMOŚCI PRBOBLE ODNOTOWANY DLA KUPUJĄCYCH PO GODZINIE 10

**Comment by PrzemyslawLukanowski** [comment]
Wysyłka maili i obsługa Centrum Wiadomości nie jest powiązana z API, dla którego świadczymy wsparcie na tym forum. Zasoby do obsługi Centrum Wiadomości pojawią się w API dopiero w przyszłym roku, W związku z tym, prześlij prosze swoje zgłoszenie za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), dzięki temu trafi do odpowiedniego zespołu, który zajmie się analizą problemu.

**Comment by akxx87** [comment]
Znów to samo wysłane maile nie pojawiają się w centrum wiadomości, oraz nie przychodzą maile od wpłatach.

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z moją powyższą wiadomością wyślij proszę zgłoszenie przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w ten sposób trafi ono do zespołu, który zweryfikuje ten problem.
