### ISSUE TITLE
Czy external id musi być unikatowy?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#3987]
Czy dwie oferty mogą mieć to samo external id? Tak że w filtrowaniu podam np. "external.id=1337"  i zwróci mi kilka ofert.

**Comment by PrzemyslawLukanowski** [comment]
Tak, external.id nie musi być unikatowe - możesz dodać ten sam numer do wielu ofert i w opisanym przypadku otrzymasz je w odpowiedzi dla GET/sale/offers?external.id={external.id}.

**Comment by mack3d** [comment]
Czy jedno zapytanie może wyszukać oferty które zawierają ciąg znaków w tytule LUB external.id?

Jak skonstruować zapytanie aby wyszukiwanie po external.id działało tak jak po tytule:
- należy podać choć jedną literę, na którą zaczyna się jakikolwiek wyraz z tytułu

**Comment by PrzemyslawLukanowski** [comment]
@mack3d GET /sale/offers nie wspiera operatora **OR** , dlatego nie możesz stworzyć pojedynczego zapytania, które zwróci oferty  według jednego lub drugiego parametru.
Wyszukiwanie po external.id nie działa podobnie według parametru phrase - musisz podać całą wartość external.id, aby otrzymać powiązane wyniki.
