### ISSUE TITLE
Problem z metodami uwierzytelnienia 

### ISSUE THREAD

**Issue by LocalHeroPro** [allegro/allegro-api#3988]
Chcę w swojej aplikacji mieć możliwość podłączenia X kont z Allegro. Z tego co zauważyłem, pierwszy sposób autoryzacji nie jest pewnym rozwiązaniem - ze względu że nie można powiązać żądania pobrania tokenu z niezależną odpowiedzią z Allegro.
W tym miejscu lepiej wygląda opisana druga metoda, ale z dokumentacji - nie wiem dlaczego - wynika, że nie jest przeznaczona do aplikacji posiadających wersję przeglądarkowe ;] dziwne
I zastanawiam się z której wersji powinienem skorzystać. Pierwsza się nie nadaje z racji wieku kont, druga niby nie to przeglądarek, może ostatnia ? Ostatnia jest słabo opisana.

Chodzi mi o niniejsza dokumentację: https://developer.allegro.pl/auth/

**Comment by troncomputers** [comment]
Są tylko dwie metody do autoryzacji. Trzecia jest taką "do odczytu". Masz dostęp tylko do publicznych danych (kategorie itp). Ja obsługuje 5 kont. 

> W tym miejscu lepiej wygląda opisana druga metoda, ale z dokumentacji - nie wiem dlaczego - wynika, że nie jest przeznaczona do aplikacji posiadających wersję przeglądarkowe ;] dziwne

Skąd to niby wziąłeś? Do obu potrzebujesz przeglądarki, aby połączyć aplikację z wygenerowanymi `clientId` oraz `client_secret`. `access_token` nie generuje się za każdym razem. Robisz to raz i odświeżasz za pomocą `refresh_token`.

**Comment by AureliuszBrussy** [comment]
@LocalHeroPro Device flow przygotowany jest z myślą o urządzeniach lub aplikacjach, które nie posiadają np. interfejsu graficznego. Nie oznacza to, że nie możesz korzystać z tej metody uwierzytelniania, nawet jeżeli Twoja aplikacja posiada taki interfejs. 

Jeżeli skorzystasz z autoryzacji typu Authorization Code - możesz za pomocą jednej aplikacji swobodnie obsługiwać wiele kont na Allegro - nie ma żadnego ograniczenia co do ilości kont.

**Comment by LocalHeroPro** [comment]
Ograniczenia nie ma, ale skąd będę wiedziała czyje code wraca jak w jednym momencie może kilka osób przystąpić do aktywowania aplikacji?

**Comment by troncomputers** [comment]
Na podstawie `client_id` i `client_secret`, które musisz stworzyć dla każdego konta.

**Comment by LocalHeroPro** [comment]
Raczej ale ta informacja w pierwszej metodzie nie wraca w linku. Wraca jedynie code. Więc trochę jest to nieużyteczne.

**Comment by troncomputers** [comment]
Wiesz przecież do którego konta wysyłasz request o autoryzację ponieważ musisz zawrzeć basic na podstawie `client_id` i `client_secret`. Nie bardzo rozumiem co tutaj jest nieużyteczne? Sam się będziesz musiał do tego dostosować z oprogramowaniem i sobie te klucze jakoś identyfikować żebyś wiedział, który `code` tyczy się, którego konta.

Ja też miałem wzloty i upadki w tej kwestii ale problem został zażegnany i nie muszę nic robić. Samo się robi.

**Comment by AureliuszBrussy** [comment]
@LocalHeroPro podczas uwierzytelniania możesz skorzystać z opcjonalnego parametru **state** i tam przekazać np. identyfikator użytkownika z Twojego systemu. Zwrócimy ten parametr wraz z **code**. Istnieją też inne możliwości, np. rozkodowanie otrzymanego access tokena, gdzie umieszczamy user_name, czyli id użytkownika Allegro.

**Comment by LocalHeroPro** [comment]
Dziękuję Panowie za liczne, szybkie i rzeczowe odpowiedź!
