### ISSUE TITLE
TAGI - wczoraj przestało działać dodawanie tagów w metodzie doChangeItemFields

### ISSUE THREAD

**Issue by scalp00** [allegro/allegro-api#399]
Wczoraj jak testowałem z ręki - działało, rozochocony napisałem skrypt do ich obsługi, zacząłem testować i już nie działa. Przykładowy request:

Najgorsze jest to że nawet jak jeszcze działało to testy musiałem robić na chybił trafił, bo tagi nie zwracają żadnych błędów w odpowiedziach. Nie ważne czy prześle się poprawną strukturę czy jakieś głupoty, zawsze dostaję w odpowiedzi strukturę ChangedItemStruct

`<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns7938="http://tempuri.org"><SOAP-ENV:Body><DoChangeItemFieldsRequest xmlns="https://webapi.allegro.pl/service.php"><sessionId>XXX</sessionId><itemId>5602302707</itemId><tags><item><tagName>TEST8</tagName></item></tags></DoChangeItemFieldsRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>`

**Comment by masterix** [comment]
To już chyba od kilku miesięcy "działa bo działa". Raz faktycznie działa a raz nie.

**Comment by AniaMalinowska** [comment]
Dziękujemy za zgłoszenie, pracujemy nad tym.

**Comment by kfijalko** [comment]
W zakładce tagi (w koncie), nie można sortować tagów.

**Comment by AniaMalinowska** [comment]
Jeśli chodzi o przyciski z kierunkami na [liście tagów](https://allegro.pl/offerShopsTagsFrontend/myaccountTags/) w Moim Allegro, to nie służą one do sortowania. Za ich pomocą można zarządzać kolejnością tagów na liście ofert sprzedającego. 
Faktycznie teraz są nieaktywne - zweryfikujemy to. Możesz przesuwać tagi na liście 'chwytając' je kursorem, a następnie przesuwając w górę/dół.

**Comment by kfijalko** [comment]
Chwytanie nie działa. Sprawdziłem na windows 10, edge i chrome.

**Comment by AniaMalinowska** [comment]
Dziękuję za sygnał, 
weryfikujemy problem przesuwania tagów.

**Comment by AniaMalinowska** [comment]
@kfijalko prosimy, podaj nam swój ID użytkownika/login.

**Comment by kfijalko** [comment]
id uzytkownika: 48546368

**Comment by AniaMalinowska** [comment]
Dziękujemy, weryfikujemy to.

**Comment by AniaMalinowska** [comment]
@kfijalko nie udało nam się powtórzyć opisanego problemu. Prosimy zweryfikuj ustawienia swojej przeglądarki, uaktualnij ją do najnowszej wersji itp. Przykładowo na przeglądarce Google Chrome 67.0 zarządzanie kolejnością tagów działa prawidłowo - poprzez  'drag & drop'. Dodam, że jest to jedyny sposób na zarządzanie kolejnością tagów z poziomu mojego Allegro (przyciski z kierunkami nie służą do tego).

**Comment by kfijalko** [comment]
Przeglądarkę mam aktualną i niestety nie działa.
Na wszystkich mam ten sam efekt, jak klikam "drag" i przesuwam to pozostałe element zmieniają kolor tła, tak sobie "mrygają" - i kolejność się nie zmienia.

Windows 10 Pro 64bit - wszystkei updaty na bierząco.
1)
Google Chrome is up to date
Version 67.0.3396.99 (Official Build) (64-bit)
2)
61.0.1
Firefox Release
3)
Microsoft Edge 42.17134.1.0
4)
IE 11
11.112.*

Sprawdziłem dla 4 kont, z różną liczba tagów.

**Comment by MartaNowaczyk** [comment]
@kfijalko Potwierdzam wersję Ani. Mi również nie udało się powtórzyć błędu. Sprawdź jeszcze proszę na innym komputerze.

**Comment by kfijalko** [comment]
ok

**Comment by kfijalko** [comment]
Potwierdzam wersję Ani ;) sprawdziłem na innym i działa.
