### ISSUE TITLE
Bład przesyłania załacznika w dyskusji

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#3990]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

Witam, mam problem z przesłaniem załączników w dyskusji. Pliki przesyłają się, ale podczas dołączania do wiadomości Id załącznika dostaję informację: **Niepoprawne ID załącznika.**

Dodam, że rano działało normalnie, a od jakiś 20 minut jest z tym problem.

**Comment by AureliuszBrussy** [comment]
Czy możesz przesłać trace-id wywołania, które zakończyło się komunikatem: Niepoprawne ID załącznika? Na tej podstawie zweryfikuję sytuację.

**Comment by AureliuszBrussy** [comment]
Wystąpiły chwilowe problem z dodawaniem załączników do dyskusji - nie powinny już one występować.

**Comment by manoos** [comment]
ok sprawdzę
