### ISSUE TITLE
Problem z dodaniem załącznika w dyskusji

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#3992]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas dodawania załącznika w formacie .png do dyskusji, serwer zwraca błąd **409 Conflict**
Wcześniej nie notowaliśmy takich problemów.

**trace-id:** 5b479f661c917d40

**Comment by AureliuszBrussy** [comment]
Wystąpiły chwilowe problem z dodawaniem załączników do dyskusji - nie powinny już one występować.
