### ISSUE TITLE
Wysyłam z Allegro - ubezpieczenie/wartość przesyłki

### ISSUE THREAD

**Issue by Sebug-rsa** [allegro/allegro-api#3993]
W jaki sposób odróżnić przewoźników mających taką opcję i uzyskać jej limity? 
Po podaniu wartości poprzez API(sandbox) otrzymuję: "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem". Wiąże się to pewnie przekroczeniem dopuszczalnej wartości. Czy na środowisku produkcyjnym taki problem również występuje?

**Comment by AureliuszBrussy** [comment]
Podanie konkretnej wartości w strukturze value jest wymagane. W API Allegro aktualnie nie ma możliwości sprawdzenia maksymalnej wartości ubezpieczenia przesyłki. Abym mógł zweryfikować przyczynę tego błędu - proszę, podaj trace-id Twojego wywołania.

**Comment by Sebug-rsa** [comment]
209ee32fd6ffaf0d
d888f2c388eef6c7
8e25568e859cd77e
1b2f2865d4ee1184
6f8a264e8b7e3660

Dodatkowo jest problem z mapowaniem sposobów dostawy:
`        'Allegro Kurier DPD' => 'Allegro DPD',
        'Allegro Kurier DPD pobranie' => 'Allegro DPD',
        'Allegro Kurier UPS' => 'Allegro UPS',
        'Allegro Kurier UPS (do 10 kg)' => 'Allegro UPS do 10 kg',
`

Tabela z poradnika jest niekompletna: https://developer.allegro.pl/wza/

**Comment by AureliuszBrussy** [comment]
W przypadku podanych przykładów - powodem braku utworzenia przesyłki był fakt przekroczenia maksymalnej deklarowanej wartości paczki. Zgłosiłem brak takiego komunikatu do odpowiedniego zespołu. Uzupełnimy to.

W kwestii mapowania sposobów dostawy - rozumiem, że chodzi tutaj konkretnie o brak `Allegro Kurier UPS (do 10 kg)` w poradniku?

**Comment by Sebug-rsa** [comment]
Tak i Allegro Kurier DPD pobranie. Podejrzewam, że takich przypadków może być więcej.

**Comment by AureliuszBrussy** [comment]
@Sebug-rsa dziękuję za spostrzeżenie - zaktualizujemy poradnik.
