### ISSUE TITLE
Pole ean w szkicu jest a w parametrach nie ma.

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3994]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przykładowa oferta `10000068721`.

Mam problem u klienta, że jak aktywuję szkic to dostaję błąd: `Pole ean jest tylko do odczytu. Wartość z pola ean podaj w parametrze o id: 225693`. Kiedy pobieram szkic z Allegro to ma on uzupełniony ean, ale parametru nie ma. Raczej jestem pewny, że został wysłany podczas stworzenia szkicu. Czy możliwe, że jakoś parametr został usunięty, a ean w polu został?

```
"parameters": [{
        "id": "11323",
        "valuesIds": ["11323_1"],
        "values": [],
        "rangeValue": null
      }, {
        "id": "224017",
        "valuesIds": [],
        "values": ["LB1603 RED"],
        "rangeValue": null
      }, {
        "id": "9304",
        "valuesIds": ["9304_507125"],
        "values": [],
        "rangeValue": null
      }],
      "customParameters": null,
      "ean": "5903089063049",
```

**Comment by AureliuszBrussy** [comment]
Z naszych logów wynika, że podczas tworzenia szkicu nie przekazałeś wartości w parametrze 225693 (EAN). Nie widzę tutaj sytuacji, że wartość w tym parametrze została usunięta.

**Comment by AnimalDEV** [comment]
OK dzięki

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to jeszcze raz - podczas tworzenia oferty faktycznie przekazałeś wartość w parametrze 225693, który został przeniesiony do pola EAN (tego tylko do odczytu). 

Tego samego dnia (o godzinie 18:01:46) Twoje oprogramowanie wywołało na tym szkicu żądanie **PUT sale/offers/{offerId}**. W żądaniu tym nie było już sekcji **parameters**, w wyniku czego wcześniej uzupełnione w szkicu parametry zostały usunięte. EAN pozostał tylko w polu do odczytu.

**Comment by AnimalDEV** [comment]
Jak rozumiem to jest poprawne działanie tak? Jeśli w żądaniu `PUT sale/offers/{offerId}` nie przekazuje sekcji parameters to powinno usunąć tą sekcję ze szkicu. A w przykładowej ofercie parametry są tylko parametru ean nie ma.

**Comment by AureliuszBrussy** [comment]
Pozostałe parametry nie były uzupełnione - zwracaliśmy także błąd o treści: "Uzupełnij parametry obowiązkowe: Stan, Kod producenta, Marka.".
