### ISSUE TITLE
Problem z wystawieniem produktu z SkyShop

### ISSUE THREAD

**Issue by KarolKarol123** [allegro/allegro-api#3995]
Cześć
Mam problem taki jak w tytule. Konto z allegro i aplikacja SkyShop jest powiązane. Podczas próby wystawienia produktu przez SkyShop na allegro wyskakuje taki błąd:

**Allegro zwróciło następujące komunikaty:

Invalid post code. (ConstraintViolationException.ValidPostCode)
Invalid postcode 27225 (INVALID_POSTCODE)**

Bardzo proszę o pomoc

**Comment by AureliuszBrussy** [comment]
Błąd ten oznacza, że podany kod pocztowy podany w strukturze oferty jest niepoprawny. Dopuszczalny format kodu pocztowego zawiera znak "-" (format XX-XXX).
