### ISSUE TITLE
No change in update time

### ISSUE THREAD

**Issue by syzzmf** [allegro/allegro-api#3996]
Hello, I used Add a parcel tracking number and Set seller order status to change the order, and then got the data of the order through Get an order's details, but found that the update time (updatedAt) is consistent with the data before the order I updated. Is this normal or a bug?

**Comment by AureliuszBrussy** [comment]
It is normal. The date in this field will only change if there is a buyer interaction with the order, for example, canceling an order.

**Comment by syzzmf** [comment]
> 
> 
> It is normal. The date in this field will only change if there is a buyer interaction with the order, for example, canceling an order.

Okay thank you. This update time will only be updated if it is changed by the buyer, so what can I know immediately that this order has been changed by the seller or buyer?

**Comment by AureliuszBrussy** [comment]
If the date at updatedAt field changed - this means, that change has been made by the buyer. You can use [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) to retrieve events in the order, including changes of fulfillment status.

**Comment by syzzmf** [comment]
> 
> 
> If the date at updatedAt field changed - this means, that change has been made by the buyer. You can use [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) to retrieve events in the order, including changes of fulfillment status.

Ok, I see. Thank you very much

**Comment by syzzmf** [comment]
> 
> 
> It is normal. The date in this field will only change if there is a buyer interaction with the order, for example, canceling an order.

hi, there is an order on my side that was paid by the buyer, and the status changed from FILLED_IN to READY_FOR_PROCESSING. This is the buyer's change, but the update time has not changed. What's the matter?

**Comment by AureliuszBrussy** [comment]
Can you provide the order number (checkoutFormId)? I'll check this order.

**Comment by syzzmf** [comment]
> 
> 
> Can you provide the order number (checkoutFormId)? I'll check this order.

order number：7c06b754-4eee-11eb-a4fd-a94a35d37f1e

Hello, I found this order is very strange. The status of the order is FILLED_IN but there are payment details. The payment completion time(finishedAt) is: 2021-01-05T00:41:10.941Z. The update time(updatedAt) is also: 2021-01-05T00:41:10.941Z. Then the order status becomes READY_FOR_PROCESSING, but the payment time and update time are still 2021-01-05T00:41:10.941Z not updated. So I have the following questions:
1. The order status is FILLED_IN, but there are payment details including payment time and payment amount. Is this normal? Does FILLED_IN mean the status of the payment incomplete?
2. Will the update time change when the order status is updated to READY_FOR_PROCESSING

**Comment by PrzemyslawLukanowski** [comment]
I've checked events for this order, especially at which time order status was updated:
- FILLED_IN - "occurredAt": "2021-01-05T00:41:07.090Z",
- READY_FOR_PROCESSING - "occurredAt": "2021-01-05T00:41:10.941Z"

1. On our side, the order has RFP status with payment data. Payment data (finishedAt and paidAmount) shouldn't be visible if the order is in FILLED_IN status. Yes, FILLED_IN means that the payment status is incomplete. Do you have logs for this case? When the order has FILLED_IN status, but also the payment data? If so, you can send it to us via a [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (please add GitHub thread number - 3996), we will verify it. 
2. RFP status occurred after payment was finished - 2021-01-05T00:41:10.941Z. So the current date in "updateAt" is proper.

**Comment by syzzmf** [comment]
> 
> 
> I've checked events for this order, especially at which time order status was updated:
> 
>     * FILLED_IN - "occurredAt": "2021-01-05T00:41:07.090Z",
> 
>     * READY_FOR_PROCESSING - "occurredAt": "2021-01-05T00:41:10.941Z"
> 
> 
>     1. On our side, the order has RFP status with payment data. Payment data (finishedAt and paidAmount) shouldn't be visible if the order is in FILLED_IN status. Yes, FILLED_IN means that the payment status is incomplete. Do you have logs for this case? When the order has FILLED_IN status, but also the payment data? If so, you can send it to us via a [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (please add GitHub thread number - 3996), we will verify it.
> 
>     2. RFP status occurred after payment was finished - 2021-01-05T00:41:10.941Z. So the current date in "updateAt" is proper.

Okay, thank you. I have sent the information through the contact form and attached the logs of 2 orders, both of which are in FILLED_IN status but have Payment data (finishedAt and paidAmount)

**Comment by PrzemyslawLukanowski** [comment]
We've received your data,  we'll verify why in these orders the status did not change to RFP immediately after the payment was finished.

**Comment by PrzemyslawLukanowski** [comment]
I've verified this case with our team - it is possible that sometimes orders can be in FILLED_IN status along with the payment data, so sorry for my previous answer. You should use GET /order/events to retrieve a list of events and when the RFP event will occur - you can retrieve the order details, order will be also in the RFP status. 
If it comes to the order 7c06b754-4eee-11eb-a4fd-a94a35d37f1e - update time is valid. It changed after the payment was finished.
For both orders, the status has been changed to RFP a few seconds after payment was finished.

**Comment by syzzmf** [comment]
Okay, will it take the same time to update the status from FILLED_IN to READY_FOR_PROCESSING after the order is paid? How long will it take? We can try to delay to get the real status of the order**

**Comment by PrzemyslawLukanowski** [comment]
Order status should change to RFP immediately after the order is paid.

**Comment by syzzmf** [comment]
> 
> 
> Order status should change to RFP immediately after the order is paid.

If the received order is FILLED_IN and there is payment information, I will get the order information again in 3 or 5 minutes, can I get the RFP status?

**Comment by PrzemyslawLukanowski** [comment]
RFP status should occur immediately or a few seconds after the payment is completed, so you can repeat your request again after that time.

**Comment by syzzmf** [comment]
Okay, I see, thank you for your answer
