### ISSUE TITLE
Do you have Magento 1.9.4 Allegro plugin? 

### ISSUE THREAD

**Issue by asdnikita** [allegro/allegro-api#3997]
Hi,

Do you have Allegro plugin for Magento ecommerce platform 1.9.4?

Kind regards,

**Comment by AureliuszBrussy** [comment]
We don't maintain any official Magento plugin. We cannot recommend any specific (existing) solution. Maybe other forum users can help you.

**Comment by asdnikita** [comment]
Thank you for your reply!
