### ISSUE TITLE
Pusta tablica tasks w odpowiedzi

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#3999]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: `56620bbdbc2db18d`

Kiedy pytam na zasobie `/sale/offer-publication-commands/{commandId}/tasks` dostaję w odpowiedzi pustą tablicę tasks.
```
{
  code: 200,
  headers: {
    expires: '0',
    'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
    'x-xss-protection': '1; mode=block',
    pragma: 'no-cache',
    'x-frame-options': 'DENY',
    'trace-id': 'a4867b6044bb565',
    date: 'Tue, 15 Dec 2020 10:42:47 GMT',
    'x-content-type-options': 'nosniff',
    'content-type': 'application/vnd.allegro.public.v1+json;charset=UTF-8',
    'content-length': '12',
    connection: 'close'
  },
  body: { tasks: [] }
}
```
Dlaczego tak się dzieje?

**Comment by AnimalDEV** [comment]
Dopiero teraz po 10 min dostałem status `SUCCESS`. Chyba brakuje statusu `NEW`

**Comment by AureliuszBrussy** [comment]
To jest prawidłowe działanie - zwracamy tylko pełną tablicę tasks po ukończeniu wszystkich operacji. Przed ukończeniem tablica będzie pusta.

**Comment by AnimalDEV** [comment]
Ok dzięki
