### ISSUE TITLE
Unikatowy identyfikator (mój) aukcji

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#40]
Witam,

Witam, po przejściu nowy format straciłem funkcjonalność, której dotychczas używałem identyfikować osierocone aukcje. W opisie HTML wstawiałem specjalną klasę (np. `<div class="product-id-XXXX">`), po której jednoznacznie mogłem powiązać aukcję z produktem u siebie. Ponieważ wystawianie u mnie wygląda tak (w formie pseudokodu):

```
$response = doNewAuctionExt($request)
INSERT INTO auctions SET item_id = $response['itemId'], product_id = $product_id
```

Może się zdarzyć, że skrypt zakończy pracę przez wykonaniem INSERT - w efekcie tworząc osieroconą aukcję.

Aktualnie po pobraniu aukcji przez API, której nie miałem zapisanej u siebie dokonywałem parsowania opisu, aby wychwycić mój $product_id i wykonać brakujący INSERT to bazy danych.

Z nowym opisem jest to niemożliwe (przynajmniej w formie ukrytego elementu, musiałby być to jakiś widoczny dla użytkownika tekst).

Zauważyłem coś takiego jak `localId` w `doNewAuctionExt`. I teraz mam pytania związane z tym polem:

- czy pole to jest unikatowe u Państwa w ramach konta? Zależy mi aby każdy produkt był wystawiony maksymalnie raz, więc jeżeli dostanę wyjątek przy `doNewAuctionExt`, że `localId` podałem nieunikatowe - to super.

- która z metod zwraca localId? Szukam takiej, w której pytam o konkretne itemId i dostaje m.in. localId?

**Comment by pgasidlo** [comment]
Ok, chyba do zamknięcia pytanie, ale dla potomnych odpowiedzi:

- pole jest unikatowe w ramach konta
- do sprawdzania, czy istnieje aukcja z określonym localId służy metoda `doVerifyItem`. Jeżeli zwróci `itemId` o wartości -1, to aukcja nie została jeszcze wystawiona.

**Comment by pgasidlo** [comment]
Dobra, ale jednak jest pytanie. Mam `itemId`. Chce poznać `localId`. Jest do tego jakaś funkcja? Funkcja doVerifyItem na wejściu ma `localId` i zwraca `itemId` (czyli działa odwrotnie niż oczekuje).

**Comment by KrzysztofLukanowski** [comment]
Cześć,

Pole localId służy tylko i wyłącznie do weryfikacji poprawności opisu oferty wystawionej w ramach danego konta. Możesz to zrobić za pomocą wspomnianej metody doVerifyItem. Jeżeli wszystko poszło ok, w odpowiedzi tej metody otrzymasz itemId oraz wartość 1 w polu itemListed. Nie możesz natomiast wyciągnąć localId, wartość z tego pola nie służy identyfikacji poszczególnych ofert. W przyszłości planujemy udostępnić takie pole w ramach REST API.

**Comment by pgasidlo** [comment]
Ok, czyli na razie po swojej stronie przed wywołaniem ustawiam flagę, "wystawiam na allegro" (odnotowując dodatkowo `localId`), którą zeruję po otrzymaniu wyniku `doNewAuctionExt`. Następnie osobnym skryptem łapie przypadki, gdy flaga ta jest długo ustawiona i dla nich wywołuje `doVerifyItem`, aby sprawdzić czy wszystko poszło OK.
