### ISSUE TITLE
GET sale/offers

### ISSUE THREAD

**Issue by copyact** [allegro/allegro-api#400]
Witam,

Dlaczego przy próbie wywołania GET na https://allegroapi.io/sale/offers/7428986314

otrzymuję błąd

{"errors":[{"code":"NotAcceptableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

**Comment by PawelTaberski** [comment]
Zapewne błąd jest w przesyłanych nagłówkach, upewnij się że przesyłasz wszystkie wymagane nagłówki. W tym wypadku możliwe że brakuje nagłówka "accept" o wartości "application/vnd.allegro.beta.v1+json". Więcej na ten temat [tutaj](https://developer.allegro.pl/sale/#similar-offer).

**Comment by copyact** [comment]
Wysyłam taki:
Accept: application/vnd.allegro.public.v1+json
to mam dodać drugi z beta czy zastąpić?

**Comment by PawelTaberski** [comment]
To są zasoby w wersji beta, także tak jak w instrukcji, którą podesłałem nie dodawać nowego, a podmienić obecny i powinno wszystko być ok. Polecam zapoznać się z tą dokumentacją jest w niej opisane krok po kroku jak wystawić/pobrać/edytować ofertę przez REST API.

**Comment by copyact** [comment]
Dziękuję. Czy mógłbym prosić od razu o informację dlaczego zasób GET offers/listing dla mojego sellerId zwraca mi tylko 58 z 1515 ofert lub ewentualnie, jak mógłbym pobrać id wszystkich moich ofert?

**Comment by PawelTaberski** [comment]
Widzę, że zadałeś już to pytanie w innym wątku, na pewno otrzymasz na nie odpowiedź. Do weryfikacji Twojego zgłoszenia na pewno będzie potrzebny pełny cURL i respons jaki otrzymujesz. Podeślij takie dane przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=7e8e35b6-d773-4a0a-8d38-c056148165e8), a następnie wklej numer ticketa.
