### ISSUE TITLE
Opcje promowania ze statustem "oczekujący"

### ISSUE THREAD

**Issue by mkwalewski** [allegro/allegro-api#4000]
Witam,
Mam pytanie, gdy próbuje usunąć przez API opcję, która ma status "oczekujący", to nic się nie dzieje. Jeśli usunę bazową opcję to i "oczekująca" zniknie. Również, jeśli dodam tą samą bazową opcję to "oczekująca" zniknie, jeśli dodaje inne to dobrze się dodają jako oczekujące. W API jest opcja "BASE" lub "EXTRA" jako typ, ale nie ma "oczekującej".

Jest to zamierzone działanie, czy zostanie to w jakiś sposób poprawione ?

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś opisać swoje wątpliwości nieco bardziej oraz pokazać np. na przykładzie konkretnych wywołań, co według Ciebie funkcjonuje niepoprawnie? Rozumiem, że przez "oczekujące" masz na myśli informacje o nowych pakietach promowania, które włączymy po zakończeniu aktualnego okresu rozliczeniowego?

**Comment by mkwalewski** [comment]
Jasne, już mówię o co mi chodzi.
Gdy mam opcje promowania jak poniżej:
`{
    "offerId": "7679041175",
    "basePackage": {
        "id": "emphasized10d",
        "validFrom": "2020-12-16T08:00:09.307Z",
        "validTo": "2020-12-26T08:00:09.307Z",
        "nextCycleDate": null
    },
    "extraPackages": [],
    "pendingChanges": {
        "basePackage": {
            "id": "promoPackage",
            "validFrom": "2020-12-26T08:00:09.307Z",
            "validTo": null,
            "nextCycleDate": "2020-12-27T08:00:09.307Z"
        },
        "extraPackages": null
    }
}`

I wyślę taki request:
`{
  "modifications": [
    {
      "modificationType": "REMOVE_NOW",
      "packageType": "BASE",
      "packageId": "promoPackage"
    }
  ]
}`

To opcje promowania pozostają bez zmian.

Natomiast gdy wyślę taki
`{
  "modifications": [
    {
      "modificationType": "REMOVE_NOW",
      "packageType": "BASE",
      "packageId": "emphasized10d"
    }
  ]
}`

To usuwają się oba (zwykły i oczekujący) - dostając takiego responsa:
`{
    "offerId": "7679041175",
    "basePackage": null,
    "extraPackages": [],
    "pendingChanges": null
}`

**Comment by AureliuszBrussy** [comment]
Na ten moment jest to prawidłowe działanie. Przekazałem jednak Twoją uwagę do odpowiedniego zespołu, który rozważy ewentualną modyfikację tej funkcjonalności w API. Wrócę z informacją, jeżeli zdecydujemy się na zmianę.
