### ISSUE TITLE
Problem z aktualizacją aukcji - Parametr o tej nazwie już istnieje

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#4001]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,
od ok 2-ch dni w moich logach widzę sporo nowych błędów przy próbie aktualizacji ilości na aukcji.
Generalnie pobieram cały opis aktualnej aukcji zmieniam jej ilość i wysyłam do aktualizacji.

W wyniku dla niektórych produktów dostaję poniższy błąd:

wynik={"errors":[{"code":"BAD_REQUEST","message":"Parameter already exists: name='Model', id='237206'","details":"","path":"","userMessage":"Parametr o tej nazwie już istnieje"}]}

Co może być powodem ?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę pełen request w formacie cURL w tym wątku (wycinając wcześniej token) lub, jeśli chcesz - przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - zweryfikuję to. Jeśli zdecydujesz się na zgłoszenie - wskaż numer wątku GitHub: #4001.
