### ISSUE TITLE
Chcę mieć interfejs do odpowiadania na wiadomości przed sprzedażą

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#4002]

**Comment by bingnew** [comment]
Dear，
could you show me a way to reply discussion  messages and Pre salemessages by api？
I cannot find it.
Looking forward to your reply. Have a nice day

![image](https://user-images.githubusercontent.com/72594584/102303494-38788980-3f96-11eb-844d-caa8dff1dc1e.png)

**Comment by AureliuszBrussy** [comment]
You can manage disputes via API by using endpoints related to disputes. Those endpoints are listed in [our documentation](https://developer.allegro.pl/en/documentation/#tag/Disputes). You can also check [our tutorial](https://developer.allegro.pl/en/dispute/). 

Currently, the Message Center is not supported by the API. Next year we will present new endpoints to support it.
