### ISSUE TITLE
Niewidocze oferty ze statusem ENDED

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4004]
Występuje problem: 
 - [ X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Pobieram zakończone oferty zasobem sale/offers następnie pobieram szczegóły : sale/offers/{ofertaID}.
Niektórych nie pobiera i nie są widoczne od strony frontu np. 9433075914. 
Z czego to wynika?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę pełen request w formacie cURL w tym wątku (wycinając wcześniej token) lub, jeśli chcesz - przez [nasz formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - zweryfikuję to. Jeśli zdecydujesz się na zgłoszenie - wskaż numer wątku GitHub: #4004.

**Comment by AureliuszBrussy** [comment]
@paafcioc22 nie musisz już wysyłać zgłoszenia poprzez formularz. Udało mi się ustalić, że oferta była zakończona od 60 dni i została zarchiwizowana, dlatego też aktualnie nie powinna być już zwracana poprzez API.

**Comment by paafcioc22** [comment]
Faktycznie nie znajduję jej już na pierwszym zasobie .  Dzięki za wyjaśnienie.
