### ISSUE TITLE
Zgłaszanie ofert do kampanii

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#4005]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas próby zgłoszenia aukcji do kampanii, otrzymujemy poniższy błąd:

> {
    "errors": [
        {
            "code": "BB13",
            "message": "Too many requests from this account.",
            "details": null,
            "path": null,
            "userMessage": "Too many requests from this account."
        }
    ]
}

Konto z którego wysyłamy zapytanie nie ma żadnych oczekujących zgłoszeń.

**trace-id:** a0f1551713704d73

**Comment by AureliuszBrussy** [comment]
Dla konta, z którego wysyłasz żądanie zablokowaliśmy możliwość zgłaszania ofert do Kampanii. W przypadku pytań i wątpliwości - proszę o kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).
