### ISSUE TITLE
wyszukiwanie informacji o ofercie (nie swojej) po id

### ISSUE THREAD

**Issue by barpas** [allegro/allegro-api#4006]
czy jest jakakolwiek możliwość dowiedzenia się czegoś o aukcji mając jej id ? swego czasu obiecywaliście że w 3 kwartale 2019 powstanie w rest api odpowiednik dogetiteminfo - czy to zostało zrealizowane?
i szerzej - czy https://api.allegro.pl/offers//listing pozostaje w dalszym ciągu jedynym sposobem pozyskiwania informacji o nie swoich aukcjach dostępnym w rest api i dalej nie ma sposobu na dotarcie do szczegółowych informacji (opis/ilość kupionych sztuk/etc) na jej temat?

**Comment by AureliuszBrussy** [comment]
W związku z ograniczeniem dostępu do wrażliwych danych o transakcjach nie udostępnimy odpowiednika metody doGetItemInfo w REST API. Więcej szczegółów znajdziesz w naszym [newsie](https://developer.allegro.pl/news/#public-sales-data) oraz na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/1-pazdziernika-2020-roku-ograniczymy-dostep-do-wrazliwych-danych-o-transakcjach-z82y8M11gC8).
