### ISSUE TITLE
Software Statement ID

### ISSUE THREAD

**Issue by OKschroeter** [allegro/allegro-api#4007]
Guten Tag,

wir möchten den Datenaustausch zwischen Ihnen und unserem System automatisieren und benötigen dafür unbedingt eine Software Statement ID.

Mit freundlichen Grüßen

Robert Schröter

**Comment by AureliuszBrussy** [comment]
Please, contact us by [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) and write exactly why do you need to use DCR, and why other authorization methods will not work for you. We described every available authorization methods in [our guide](https://developer.allegro.pl/en/auth/).
