### ISSUE TITLE
Internal server error - permanentny błąd

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4009]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Przykładowy trace-id:
9630d92641725629

Nie działa między innymi GET https://api.allegro.pl/sale/offers/<numer oferty>. Nie da się zmieniać ofert. Nie da się publikować nowych. Za każdym razem dostajemy "Internal server error".

**Comment by bzyku87** [comment]
U mnie to samo: "Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut. (INTERNAL_SERVER_ERROR )"

**Comment by AureliuszBrussy** [comment]
Potwierdzam występowanie takich problemów. Pracujemy już nad przywracaniem normalnego funkcjonowania zasobów.

**Comment by mkawczynski** [comment]
Potwierdzam, u mnie problemy od 30 minut.

**Comment by javaguru-pl** [comment]
Potwierdzam występowanie problemu mniej więcej od godz. 15:00.
Czy wiadomo kiedy można się spodziewać naprawy usterki?

**Comment by AureliuszBrussy** [comment]
Problem nie powinien już występować. Przepraszam za utrudnienia.
