### ISSUE TITLE
Jak uzyskać NAZWĘ użytkownika mając ID użytkownika w REST API?

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#401]
Czy da się to zrobić nie korzystając z webapi?

**Comment by DINK74** [comment]
https://github.com/allegro/allegro-api/issues/60

**Comment by PawelTaberski** [comment]
Obecnie nie ma takiej możliwości przez REST API możesz otrzymać tylko id i login usera, który wystawił komentarz metodą [GET/sale/user-ratings](https://developer.allegro.pl/documentation/#/user-ratings/getUserRatingsUsingGET)

**Comment by aktywnitu** [comment]
Dobrze. Prosiłbym zatem o wdrożenie takiej metody.

**Comment by PawelTaberski** [comment]
Niedługo udostępnimy zasoby do zarządzania sprzedażą przez REST API, także będzie miał Pan wgląd w dane osoby, która zakupiła u Pana dany przedmiot.

**Comment by PawelTaberski** [comment]
Wiemy o takiej potrzebie, jeśli wdrożymy taki zasób w REST API, to na pewno o tym poinformujemy. Obecnie pracujemy nad wypuszczeniem nowych zasobów do zarządzania sprzedażą przez REST API.

**Comment by barthoos** [comment]
Chcialbym ponownie otworzyc watek. Potrzebuje znac login alllegro, pod ktory podpiety jest token. W przeciwnym razie uzytkownik mojej aplikacji nie bedzie wiedzial, jakie dokladnie konta allegro ma u mnie podpiete. ID uzytkownika niewiele mu mowi (swoja droga - jest gdzies jakies miejsce na www, gdzie mozna sprawdzic jakie ID uzytkownika ma moj login Allegro?)

**Comment by MartaNowaczyk** [comment]
@barthoos jeśli masz ID to możesz skorzystać z linka https://allegro.pl/uzytkownik/ID/oceny, gdzie w miejsce ID wpiszesz nr ID użytkownika

**Comment by barthoos** [comment]
@MartaNowaczyk ale nie wyglupiajmy sie. jestesmy na forum RestAPI. chce miec programowalna metode pobrania nazwy uzytkownika na podstawie ID. Mam sobie cURLem sciagac strone i parsowac XML? gdzie ta "dobra zmiana" zwiazana z RestAPI? na prawde nie rozumiem, dlaczego login nie jest w ogole zakodowany w access tokenie..

**Comment by MartaNowaczyk** [comment]
Wszystko rozumiem, ale w tej chwili nie ma dedykowanego zasobu dla pobrania nazwy po ID. Mamy to w planach. Jeśli udostępnimy taką możliwość na pewno poinformujemy o tym w oddzielnym komunikacie.

**Comment by pporadzisz** [comment]
Odświeżam temat, czy coś wiadomo w temacie pobrania nazwy po ID? 
Jak widzę, wiele osób zgłasza potrzebę zaistnienia takiego serwisu,
zwłaszcza, że nie jest to skomplikowana metoda.
Prośba o info kiedy wdrożenie

**Comment by PawelTaberski** [comment]
@pporadzisz Pracujemy nad zasobem do pobrania informacji o danym userze, jak tylko wdrożymy takie rozwiązanie to poinformujemy o tym w dedykowanym komunikacie.
Informacje o planowanych zasobach znajdziesz w naszym [harmonogramie](https://developer.allegro.pl/schedule/).

**Comment by barthoos** [comment]
@PawelTaberski rozumiem, ale czy obok ID# nie daloby sie zaszyc w tokenie rowniez nazwy uzytkownika? duzo bardziej wolalbym tak, niz caly wielki zasob do danych uzytkownika..

**Comment by PawelTaberski** [comment]
Nie planujemy rozbudowy danych zawartych w tokenie. Zasób, który niedługo wdrożymy powinien rozwiązać ten problem.

**Comment by bugproof** [comment]
Czy taki zasób został już udostępniony? Szukam w dokumentacji i nic. Podobnie jak @barthoos potrzebowałbym wyświetlić e-mail/login powiązanych kont na podstawie user_name w tokenie JWT

**Comment by barthoos** [comment]
Na podstawie samego ID tego nie pobierzesz, ale jak sie juz zautoryzujesz na dany ID, to calosc pobierzesz stad: https://developer.allegro.pl/documentation/#operation/meGET . W moim przypadku to wystarczy.

**Comment by bugproof** [comment]
@barthoos Wielkie dzięki, o to właśnie mi chodziło
