### ISSUE TITLE
Dziwna wartość nagłówka LOCATION

### ISSUE THREAD

**Issue by bart1337** [allegro/allegro-api#4010]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

36494897759b111f

Strzelamy POSTem pod /sale/product-offers żeby utworzyć ofertę. Zwrotka status 202 a w headerach:
"location":[
"https://**seller-product-offer-api**/sale/product-offers/**************/operations/32f7c9f2-6a8b-4788-a99b-98b8e46e1d17"
]
Zdaję sobie sprawe iż jest to zasób beta ale z tak banalnymi błędami to nie bardzo idzie pracować. Chyba, że jest to normalny url wg was i powinienem sobie sam go poprawić ?

**Comment by AureliuszBrussy** [comment]
Potwierdzamy występowanie tego błędu. Zgłosiłem to już do odpowiedniego zespołu. Wrócę z informacją.

**Comment by lmajgier** [comment]
> Potwierdzamy występowanie tego błędu. Zgłosiłem to już do odpowiedniego zespołu. Wrócę z informacją.

Czy ogarniecie ten temat dzisiaj? 
Przez ten bład nie możemy nic dalej robić... przecież to jest śmieszne.. a zarazem smutne..

**Comment by AureliuszBrussy** [comment]
@bart1337 @lmajgier właśnie wdrożyliśmy poprawkę. Nagłówek location powinien być już prawidłowy.
