### ISSUE TITLE
Błędy obsługi błędów metody  POST na zasobie /sale/offfers/ 

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#4011]
Występuje problem: 
 - [X ] z zasobem REST API
 
Próbuję wystawić przedmiot w kategorii : 260346
Dostaję następującą strukturę z opisem błędów:

Array
(
    [0] => Array
        (
            [code] => VALIDATION_ERROR
            [message] => Nieprawidłowe parametry (17589, 222905) dla wybranej kategorii.
            [details] =>.
            [path] => parameters
            [userMessage] => Nieprawidłowe parametry (17589, 222905) dla wybranej kategorii.
        )

    [1] => Array
        (
            [code] => VALIDATION_ERROR
            [message] => Uzupełnij parametry obowiązkowe: Kolor, Pasuje do.
            [details] =>.
            [path] => parameters
            [userMessage] => Uzupełnij parametry obowiązkowe: Kolor, Pasuje do.
        )

Kłopot w tym  że parametry z identyfikatorami 17289 i 222905 nie są parametrami właściwymi dla kategorii  260346 , właściwe odpowiedniki tych parametrów w tej kategorii to  Kolor : 17588 , Pasuje do: 222909 - i takie właśnie parametry wysyłam w strukturze . Mimo więc tego że przesyłam prawidłową strukturę z parametrami Api zgłasza błąd  z kkosmosu

przesyłam następującą strukturę z parametrami

Array
(
    [0] => Array
        (
            [id] => 11323
            [valuesIds] => Array
                (
                    [0] => 11323_1
                )

        )

    [1] => Array
        (
            [id] => 224017
            [values] => Array
                (
                    [0] => HP-304XBOX-2
                )

        )

    [2] => Array
        (
            [id] => 203433
            [valuesIds] => Array
                (
                    [0] => 203433_361577
                )

        )

    [3] => Array
        (
            [id] => 222909
            [valuesIds] => Array
                (
                    [0] => 222909_301533
                )

        )

    [4] => Array
        (
            [id] => 11328
            [valuesIds] => Array
                (
                    [0] => 11328_2
                )

        )

    [5] => Array
        (
            [id] => 203437
            [values] => Array
                (
                    [0] => 38 ml
                )

        )

    [6] => Array
        (
            [id] => 203441
            [valuesIds] => Array
                (
                    [0] => 203441_216913
                )

        )

    [7] => Array
        (
            [id] => 17588
            [valuesIds] => Array
                (
                    [0] => 17588_1
                    [1] => 17588_16
                    [2] => 17588_32
                )

        )

)

**Comment by 11mszot** [comment]
Przyczyna znaleziona i usunięta

**Comment by TomaszSzydlowski-sudo** [comment]
@11mszot możesz napisać jaka była przyczyna?

**Comment by 11mszot** [comment]
Szczerze mówiąc nie do końca wiem . Zwykle wystawiam aukcje w ten sposób że pobieram z konta strukturę jakiejś aukcji użytkownika i podmieniam te sekcje które mają być zmienione w nowej aukcji zostawiając te które nie ulagają zmianie jak np Location , shippingRates, afterSales .. etc. Tak robię od początku istnienia REST Api , wcześniej w ten sam sposób operowałem na Soap Api. Zirytowany zaistniałą sytuacją doszedłem do minął że być może wzorzec który wziąłem jest zbyt stary i podmieniłem go na świeższy. Problem minął . Być może poprzez jakieś zmiany w strukturze i Api po prostu zgłupiało dostając do przetworzenia strukturę opartą na wzorcu sprzed roku. W ciągu ostatniego roku zmieniła się np lokalizacja Ean , doszła sekcja vat i ceny netto oraz cenniki hurtowe. Fakt faktem błędy które zgłaszał system obsługi błędów  były co najmniej dziwne , dla mnie jest najistotniejsze to że udało się to ominąć
