### ISSUE TITLE
Channel Advisor integration with Allegro

### ISSUE THREAD

**Issue by VittSmg** [allegro/allegro-api#4012]
Hi Team, we are trying to integrate our Allegro account with Channel Advisor (3rd party tool to manage the listing). The info requested in order to connect the two parties are Seller ID and Access Token (as per screenshot attached). Where do we find this information? Allegro seller support was not able to address the issue and redirected us to this GitHub's repository. Thank you in advance for your support 

![Screenshot_5](https://user-images.githubusercontent.com/76152240/102461928-1fe69d00-4084-11eb-91f8-9442b570c665.png)

**Comment by AureliuszBrussy** [comment]
To get seller ID and access token to integrate with Channel Advisor, please use [this tab](https://allegro.pl/help/FcFXXscP4FSDrXIXDFQvFvPvYR48G). Before that - set returns policy and complaints policy on your account, and name them: channel-advisor. If you have more questions - please contact us through the [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b).
