### ISSUE TITLE
Podkategorie "Pozostałe" i zmiana kategorii

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4013]
Czy w związku ze znaczną podwyżką prowizji w podkategoriach o nazwie Pozostałe planujecie umożliwić zmianę kategorii poprzez REST API dla istniejących ofert?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie planujemy takiej dodatkowej funkcji/możliwości. Zasady zmiany kategorii w API Allegro są takie same jak przez stronę, czyli do 12 godzin od wystawienia oferty, pod warunkiem, że nie ma w niej żadnej sprzedaży.
