### ISSUE TITLE
Rate limit na PUT /sale/offers/{offerId}

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4015]
Jaki jest limit concurrent calls na ten zasób? 
Limit na całe api wynosi 9000req/min/client_id. Mam rate limiter po swojej stronie na 8000req/min/client_id, a zapytania na ten zasób i tak idą z szybkością 60req/min niezależnie od ilości instacji workerów.
W jaki sposób mogę edytować szybko produktyzację na dużej ilości aukcji?

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś podać Client_ID swojej aplikacji przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)? Zweryfikuję to. W zgłoszeniu wskaż proszę numer wątku GitHub: #4015.

**Comment by TomaszSzydlowski-sudo** [comment]
> Czy mógłbyś podać Client_ID swojej aplikacji przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)? Zweryfikuję to. W zgłoszeniu wskaż proszę numer wątku GitHub: #4015.

Podesłałem

**Comment by AureliuszBrussy** [comment]
Dziękuję, informacja do nas dotarła. PUT /sale/offers/{offerId} nie jest dodatkowo limitowany. W logach nie widzimy problemów po naszej stronie - wykonanie więcej niż 60 requestów na minutę powinno być możliwe. Same zmiany w ofertach mogą potrwać do godziny, choć zwykle trwa to dużo krócej.

**Comment by TomaszSzydlowski-sudo** [comment]
Okej, dziękuję za informację. Sprawdzę jeszcze wszystko po swojej stronie :)
