### ISSUE TITLE
aktywacja konta na sandbox

### ISSUE THREAD

**Issue by halsky1** [allegro/allegro-api#4017]
Witam,

Proszę o aktywację konta na allegrosandbox 

konto: hal_sky1

Dziękuję

**Comment by AureliuszBrussy** [comment]
Wstępnie aktywowałem Twoje konto.  Prześlij jeszcze dwa dowolne pliki przez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php), aby dokończyć aktywację.

**Comment by halsky1** [comment]
poszło dzięki

**Comment by halsky1** [comment]
jeszcze jedno  - przy próbie importu pliku csv (masowe wystawienie ofert) mam komunikat zły format 
Można prosić o pomoć?
ps robiłem tak jak w instrukcji

**Comment by halsky1** [comment]
nie ma tematu - wszystko działa
