### ISSUE TITLE
Różnica między PATCH /sale/product-offers/{offerId}, a PUT /sale/offers/{offerId}

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4018]
Jaka jest różnica między tymi metodami? 
Czy mogę jej użyć do dowolnego parametru?

**Comment by AureliuszBrussy** [comment]
Za pomocą [PATCH /sale/product-offers/{offer-id}](https://developer.allegro.pl/documentation/#operation/editProductOffers) edytujesz dowolne pole oferty, a jednocześnie nie musisz przekazywać całego jej modelu, w przeciwieństwie do PUT /sale/offers/{offerId}. Dodatkowo, korzystając z [PATCH /sale/product-offers/{offer-id}](https://developer.allegro.pl/documentation/#operation/editProductOffers) możesz zmienić status oferty bez konieczności wywołania osobnej komendy publikacji. Jest jeszcze kilka udogodnień i uproszczeń - o wszystkich przeczytasz w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99).

**Comment by TomaszSzydlowski-sudo** [comment]
@AureliuszBrussy Super, dzięki za odpowiedz. Pytam, bo w dokumentacji tej metody nie ma wszystkich pól np. "tecdocSpecification", "compatibilityList".
