### ISSUE TITLE
Obsługa po-zakupowa

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#402]
Hej,
Od dłuższego czasu widzę wpisy typu "Już niedługo(...)".
Czy możecie podać jakieś konkretne terminy wprowadzenia obsługi po-zakupowej?
Rozumiem, że temat jest złożony i nie jest to jeden zasób. Pytam o rozłożenie w czasie np,
Pobierania zamówień, wysyłania informacji o numerze przesyłki itp.

Jak sami w którymś komentarzu zauważyliście "zależy co rozumiesz pod pojęciem w najbliższym czasie".
Tak więc pytam, co wy rozumiecie pod tym pojęciem w przypadku powyższego tematu.

**Comment by MaciejPotepa** [comment]
Hej

Nie mogę podać konkretnego dnia. Mogę jedynie powiedzieć, że planujemy publikację takich zasobów jeszcze w tym tygodniu. Staramy się z całych, żeby nasz plan nie uległ zmianie.

**Comment by jakubmaguza** [comment]
Dziękuję, taka odpowiedź mnie satysfakcjonuje. Proszę tylko bardzo mocno, żeby w danych zwracanych z tych zasobów pojawiało się pole External z zasobu Offer.

**Comment by jakubmaguza** [comment]
Dziękuję :)
Powiedz mi jeszcze jedną rzecz, czy to prawda, że numer aukcji zmienia się co jakiś czas, jeśli aukcja jest wystawiona jako "Do wyczerpania zapasów"? Gdzieś to usłyszałem, ale nie chce mi się wierzyć.

**Comment by MaciejPotepa** [comment]
Zgadza się, to jest tak zwana 'oferta ze stałym id'. Jeżeli nie zostanie zakończona - to ID się zmieni.

**Comment by jakubmaguza** [comment]
W sensie nie zmieni?

**Comment by MaciejPotepa** [comment]
Tak, wybacz niejasne określenie. 
W przypadku oferty wystawionej z **Do wyczerpania zapasów** ID zmieni się tylko jeżeli ją zakończysz i wystawisz na nowo.  Czy _de facto_ to już będzie nowa oferta. 

Jeżeli będziesz konsekwentnie utrzymywać taką ofertę 'przy życiu' i nie pozwolisz żeby stock się wyczerpał to będzie prawie 'nieśmiertelna'. :)

W ramach ciekawostki - są oferty, które od prawie dekady mają taki sam ID.

**Comment by jakubmaguza** [comment]
Dziękuję za wyjaśnienie. Teraz wszystko jasne.
