### ISSUE TITLE
Inpost Wysyłam z Allegro 

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4021]
Podczas tworzenia przesyłki za pośrednictwem API do moduły Wysyłam Z Allegro otrzymaliśmy błąd: 

Service unavailable for carrier
Rodzaj przesyłki: Allegro Inpost 
CommandId: 790959f5-69ef-4598-afd6-869cefc82386

Czym powodowany jest błąd?

**Comment by marmited** [comment]
Dobra, już się zorientowałem że błąd leci w momencie uzupełnienia PointId o numer paczkomatu. Dlaczego tak się dzieje?

**Comment by PrzemyslawLukanowski** [comment]
Ponieważ ta paczka została nadaną usługą dostawy 8715239 (Inpost Kurier), a receiver point to ZNY01M czyli paczkomat. Kurier nie dostarcza paczki do paczkomatu tylko pod wskazany adres, dlatego otrzymałeś powyższy błąd.

**Comment by marmited** [comment]
Ok, faktycznie to był błąd. Co oznacza status paczki "Brak powiązanego miejsca nadania (bez podjazdu)"? 

Nie mogę zamówić odbioru paczki - odpowiedź to: PARTIAL_SUCCESS a błąd to "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"

**Comment by PrzemyslawLukanowski** [comment]
> Nie mogę zamówić odbioru paczki - odpowiedź to: PARTIAL_SUCCESS a błąd to "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"

Czy możesz spróbować ponowić request?  Komunikat świadczy o problemie z API przewoźnika.

> Co oznacza status paczki "Brak powiązanego miejsca nadania (bez podjazdu)"?

W jakiej konkretnie sytuacji otrzymałeś tę odpowiedź. Czy na pewno dotyczy API?

**Comment by marmited** [comment]
Status widnieje w "Wysyłam z Allegro"

![obraz](https://user-images.githubusercontent.com/37150863/102866342-626af980-4437-11eb-90f3-bd9903042abe.png)

Błąd wciąż występuje. Zamówienie podjazdu jest możliwe z Państwa strony, a przez API kończy się błędem.

**Comment by marmited** [comment]
Przykładowy traceId: {trace-id=b73a02928e1aedc1}.

Podjazd muszę teraz zamówić z poziomu strony internetowej bo nie mogę czekać.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem, wrócę z odpowiedzią.

**Comment by marmited** [comment]
@PrzemyslawLukanowski  Czy jest jakaś diagnoza?

**Comment by PrzemyslawLukanowski** [comment]
@marmited Jeszcze weryfikujemy ten temat, prośba o cierpliwość.

**Comment by marmited** [comment]
Minęły prawie dwa tygodnie od mojego pytania? Kiedy dostanę odpowiedź?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mogę tego określić. Wrócę z odpowiedzią, gdy otrzymam informację od odpowiedniego zespołu.

**Comment by marmited** [comment]
Czy to są żarty? Czekam na odpowiedź ponad 3 tygodnie. Kiedy się tym zajmiecie? 

Nie możemy zamawiać odbioru dla każdej paczki ręcznie.

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedni zespół zajmuje się już tym problemem, jest on w trakcie weryfikacji. Po wdrożeniu poprawki pozostawię wiadomość w wątku.

**Comment by marmited** [comment]
W takim razie czekam na odpowiedź.

**Comment by marmited** [comment]
@PrzemyslawLukanowski  Jak postępy w załataniu dość kluczowego błędu? Czekamy już ponad 1,5 miesiąca od naszego ostatniego kontaktu.

**Comment by PrzemyslawLukanowski** [comment]
@marmited Planujemy jutro wprowadzić odpowiednią poprawkę. Potwierdzę to w tym wątku.

**Comment by PrzemyslawLukanowski** [comment]
@marmited Właśnie wprowadziliśmy poprawkę. Przepraszam za długi czas oczekiwania na rozwiązanie problemu.
