### ISSUE TITLE
Problem z aktualizacją zapasu Put Sale/Offers VALIDATION_ERROR

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#4023]
Występuje problem: z zasobem REST API - PUT /sale/offers

Wysyłamy request PUT dla oferty 9210339187 zawierający quantity = 38
W odpowiedzi otrzymujemy:
[0] => stdClass Object
        (
            [code] => VALIDATION_ERROR
            [message] => The stock level of items to be listed may not be lower than 1.
            [details] => 
            [path] => 
            [userMessage] => The stock level of items to be listed may not be lower than 1.
        )

Ten sam problem występuje w przypadku próby aktualizacji oferty z Baselinker.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten problem do odpowiedniego zespołu. Wrócę z odpowiedzią po wyeliminowaniu błędu.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się rozwiązać ten problem, nie powinien już występować.
