### ISSUE TITLE
Problem z kodowaniem CSV - PHP

### ISSUE THREAD

**Issue by gabrysr1997** [allegro/allegro-api#4024]
Dzień dobry,

Zwracam się do Państwa z prośbą o pomoc. Nie potrafię znaleźć rozwiązania w Google pomimo wielu godzin szukania...

Stworzyłem kod w PHP, które generuje na podstawie formularza HTML plik CSV, który zawiera wszystkie parametry, linki do zdjęć oraz opisy aukcji w formacie JSON. 

Gdy wklejam komórki z wygenerowanego przeze mnie pliku CSV do pliku CSV ściągniętego z Allegro to niestety wyskakuje błąd o nazwie "Nieprawidłowy podzbiór HTML". Dzieje się tak jedynie przy próbie skopiowania komórki z tekstem w formacie JSON, gdy kopiuję inne komórki wszystko jest w porządku. 
Istotne jest, że gdy wejdę w "moją" komórkę z kodem JSON i skopiuję jej zawartość (nie kopiuję komórki, tylko jej wnętrze - tekst) to wtedy wszystko działa. Problem rodzi się tylko podczas kopiowania całej komórki. Prawdopodobnie coś psuje się z kodowaniem.

Tworzony przeze mnie CSV jest w kodowaniu UTF-8, a CSV ściągnięty z Allegro prawdopodobnie Windows-1250, ale nie mam pewności. Może mógłby mi ktoś pomóc zapisać "mój" CSV od razu w kodowaniu CSV'a z Allegro? Jestem bardzo początkującym programistą i nie mogę sobie z tym poradzić. Dodaję również screen z fragmentem kodu, który tworzy "mój" plik CSV.

Z góry bardzo dziękuję za pomoc!

![image](https://user-images.githubusercontent.com/72794775/102787216-048bd280-43a1-11eb-9b6d-0ec81d91c90e.png)
![image](https://user-images.githubusercontent.com/72794775/102787951-289be380-43a2-11eb-84cf-27195596e664.png)

**Comment by MaciejFrackowiak** [comment]
Komunikat "Nieprawidłowy podzbiór HTML" sygnalizuje, że w opisie oferty użyto znaczników HTML spoza listy dozwolonych - pełną listę znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#5-opis-oferty).
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Problem nie jest związany bezpośrednio z funkcjonowaniem API Allegro. Być może ktoś z użytkowników forum będzie mógł wesprzeć Cię w tym temacie.

**Comment by gabrysr1997** [comment]
> Komunikat "Nieprawidłowy podzbiór HTML" sygnalizuje, że w opisie oferty użyto znaczników HTML spoza listy dozwolonych - pełną listę znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#5-opis-oferty).
> Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Problem nie jest związany bezpośrednio z funkcjonowaniem API Allegro. Być może ktoś z użytkowników forum będzie mógł wesprzeć Cię w tym temacie.

W takim razie dlaczego błąd występuje tylko przy kopiowaniu całej komórki, a nie występuje przy kopiowaniu jej zawartości? To by wykluczało niepoprawność kodu skoro wystarczy zmienić sposób kopiowania żeby zadziałał.

Przeanalizowałem oczami kod skopiowany jako komórka i jako tekst. Są drobne różnice w enterach i tabulatorach, innych różnic nie dostrzegłem. Tabulatory i entery raczej nie grają roli w JSON, prawda?

**Comment by MaciejFrackowiak** [comment]
Wyjaśniłem Tobie co oznacza wspomniany komunikat, natomiast trudno mi się odnieść do tego co widzisz w swoim rozwiązaniu. Jak wspomniałem - to nie jest tematyka bezpośrednio związana z API, dlatego nie sposób nam tu udzielać rad i wskazówek. Możliwe, że któryś z forumowiczów będzie mógł przekazać Ci pomocne podpowiedzi.

**Comment by Aryak2099** [comment]
A ma Pan ten plik CSV?  Sprawdzę u siebie jak to wygląda , niech będzie krutki taki z 5-15 ofertami ale żeby był ten błąd. Niech Pan napisze admin@e-api.pl to potestuję w moim programie i napisze Panu gdzie jest błąd bo może są ukryte znaczniki często tak bywa.
