### ISSUE TITLE
Jak zmienić czas wysyłki w danej ofercie ? 

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#4025]
Innymi słowy czy mogę prosić o przykładową treść skryptu . Jak dotąd dobrnąłem do tego , ale nie działa , jak powinien wyglądać ten skrypt , chodzi mi o modyfikacje w trwającej ofercie deklarowanego czasu wysyłki przez sprzedającego:

$authUrl="https://api.allegro.pl/sale/offers/{offerId}"; // co ma być wpisane w offerID - numer ofery czy jakiś inny numer?
		$headers = array();
		$headers[] = 'Accept: application/vnd.allegro.public.v1+json';
		$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
		$headers[] = 'Authorization: Bearer '.$access_token; 
$data=array('{
  "additionalServices": {
    "id": "string"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "returnPolicy": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "warranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    }
  },
  "attachments": [
    {
      "id": "1928302_MANUAL_45d7a0f543e1b0d05e12a1aef5642efe63389a1d419fe9286d0f158044391fdce"
    }
  ],
  "category": {
    "id": "string"
  },
  "compatibilityList": {
    "type": "MANUAL"
  },
  "contact": {
    "id": "string"
  },
  "createdAt": "2020-12-22T10:31:52Z",
  "customParameters": [
    {
      "name": "string",
      "values": [
        "string"
      ]
    }
  ],
  "delivery": {
    "additionalInfo": "string",
    "handlingTime": "PDT12H30M5S",
    "shipmentDate": "2018-04-01T08:00:00Z",
    "shippingRates": {
      "id": "string"
    }
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  },
  "discounts": {
    "wholesalePriceList": {
      "id": "string"
    }
  },
  "ean": "string",
  "external": {
    "id": "AH-129834"
  },
  "fundraisingCampaign": {
    "id": "string"
  },
  "id": "string",
  "images": [
    {
      "url": "string"
    }
  ],
  "location": {
    "city": "string",
    "countryCode": "string",
    "postCode": "string",
    "province": "string"
  },
  "name": "string",
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "string",
        "to": "string"
      },
      "values": [
        "string"
      ],
      "valuesIds": [
        "string"
      ]
    }
  ],
  "payments": {
    "invoice": "string"
  },
  "product": {
    "id": "string"
  },
  "promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
  },
  "publication": {
    "duration": "PDT12H30M5S",
    "endingAt": "2020-12-22T10:31:52Z",
    "startingAt": "2020-12-22T10:31:52Z",
    "status": "INACTIVE",
    "endedBy": "USER",
    "republish": false
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "minimalPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "netPrice": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "tax": {
    "percentage": "23.00"
  },
  "sizeTable": {
    "id": "string"
  },
  "stock": {
    "available": 0,
    "unit": "string"
  },
  "tecdocSpecification": {
    "id": "470b8513-b786-b7b9-9e7e-2f848729cfd6",
    "items": [
      {
        "name": "Wersja TecDoc",
        "values": [
          "0319"
        ]
      }
    ]
  },
  "updatedAt": "2020-12-22T10:31:52Z",
  "validation": {
    "errors": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "warnings": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "validatedAt": "2020-12-22T10:31:52Z"
  }
}');
$requestjson = json_encode($data, JSON_UNESCAPED_UNICODE);
$ch  = curl_init($authUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_POSTFIELDS, $requestjson);
$response = curl_exec($ch);
curl_close($ch);

powyższe oczywiście nie działa , jak powinien wyglądać ten skrypt , chodzi mi o modyfikacje w trwającej ofercie deklarowanego czasu wysyłki przez sprzedającego

**Comment by MaciejFrackowiak** [comment]
Tak, jako offerId musisz przekazać id oferty. Najprostszym rozwiązaniem jest pobranie oferty przez [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET), a następnie skorzystanie z [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) i edycja czasu wysyłki w polu delivery.handlingTime. Jako czas wysyłki możesz podać jedną z dostępnych wartości: PT0S (natychmiast), PT24H (24 godziny), P2D (2 dni), P3D (3 dni), P4D (4 dni), P5D (5 dni), P7D (7 dni), P10D (10 dni), P14D (14 dni), P21D (21 dni), P30D (30 dni), P60D (60 dni). Możesz również podać te wartości w godzinach, np. PT72H (3 dni). W [naszym poradniku](https://developer.allegro.pl/sale/#8-dane-w-ofercie) znajdziesz też przykładowy request.

**Comment by jasiek07** [comment]
Poniżej skrypt , response daje błąd : 
"{"errors":[{"code":"NotAllowedException","message":"The HTTP method is not allowed","details":null,"path":null,"userMessage":"An error occurred"}]} "

   Co robię źle ?

	$authUrl="https://api.allegro.pl/sale/offers/100xxxx073";
	$headers = array();
	$headers[] = 'Accept: application/vnd.allegro.public.v1+json';
	$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
	$headers[] = 'Authorization: Bearer '.$access_token;
		
	$ch  = curl_init($authUrl);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$response = curl_exec($ch);
	curl_close($ch);
	
	print_r($response);

**Comment by jasiek07** [comment]
Ok więc rozumiem to tak by zmienić czas wysyłki w ofercie muszę najpierw pobrać wszystkie inne dane w ofercie metodą GET by je ponownie przesłać metodą PUT , zmieniając jedynie w ciągu pobranych informacji ofert czas wysyłki . Mój skrypt wygląda zatem tak : $curl = curl_init();
	curl_setopt_array($curl, array(
	CURLOPT_URL => "https://api.allegro.pl/sale/offers/100xxxxxx73",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_CUSTOMREQUEST => "GET",
	CURLOPT_HTTPHEADER => array(
	"Accept: application/vnd.allegro.public.v1+json",
	"Authorization: Bearer ".$access_token,
	)));
	$response = curl_exec($curl);
	print_r($response);
	curl_close($curl);

	echo '<hr>';
	$curl = curl_init();
	curl_setopt_array($curl, array(
	CURLOPT_URL => "https://api.allegro.pl/sale/offers/100xxxxx073",
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_CUSTOMREQUEST => "PUT",
	CURLOPT_POSTFIELDS => $response,	
	CURLOPT_HTTPHEADER => array(
	"Accept: application/vnd.allegro.public.v1+json",
	"Authorization: Bearer ".$access_token,
	)));
	$response2 = curl_exec($curl);
	print_r($response2);
W powyższym poprostu usiłuję nadpisać oferte , ale źle napisałem sktypt dla metody PUT ponieważ request daje mi to 
{"errors":[{"code":"NotSupportedException","message":"Unsupported content type. Please check 'Content-Type' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

Co robię nie tak ?

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [dokumentacją zasobu](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) musisz ustawić dla metody PUT nagłówek Content-Type: application/vnd.allegro.public.v1+json
