### ISSUE TITLE
PRODUKTARYZACJA - MOTORYZACJA - TECDOC

### ISSUE THREAD

**Issue by falconVS** [allegro/allegro-api#4026]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X ] inny

Drogie Allegro a właściwie osoby które są odpowiedzialne za wprowadzenie kompletnego bałaganu w tej kategorii

Prosiłbym o odpowiedz na następujące pytania:
1. Wymagacie xx% towarów z wpisanym EAN - ale jak mam to zrobić jak wasz system nie pozwala numeru wpisać.
    Za przykład niech posłuży towar o symbolu EG10003-12B1 
         >---------- w waszych danych brak EAN
         >---------- w danych TECDOC EAN: ­5012759173992
    Próbując wystawić produkt poprzez formularz wystawiania czy też API - wyszukując po EAN dostajemy response 
    z poprawnym towarem czyli  EG10003-12B1 ale już próbując wystawić ten towar otrzymujemy komunikat 
    "Podany kod EAN występuje w innym produkcie niż wskazany w ofercie."
    Od razu zaznaczę iż nie chodzi tu o aktualizację danych TECDOC.
2. Po co (jaki tego jest cel) pozwalacie tworzyć produkty w kategoriach MOTORYZACJA - które już istnieją w TECDOC.
3. W jaki sposób zaktualizować cokolwiek w produktach w których przy aktualizacji otrzymujemy komunikat
    "Podany kod EAN występuje w innym produkcie niż wskazany w ofercie. " , nie da się zaktualizować TECDOC, stanu, ceny itp.

**Comment by MaciejFrackowiak** [comment]
Problem związany z otrzymanym przez Ciebie komunikatem podczas wystawiania i edycji oferty przekazałem do weryfikacji. Natomiast wszelkie uwagi i sugestie względem produktyzacji możesz przekazać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by mlonc** [comment]
Pole ean musisz wtedy wyczyścić i przejdzie.

Miałem podobny problem ale z numerem katalogowym części, Allegro krzyczało że zły numer, po aktualizacji danych tecdocowych(poprzez ręczą edycję oferty) wskoczył o dziwo ten sam co wcześniej numer i już zdziałało :)

**Comment by falconVS** [comment]
Usunięcie EAN jak najbardziej pomaga ale to chyba nie o to chodzi aby kombinować w ten sposób., zwłaszcza gdy ma się dużo aukcji i wymagany jest próg nasycenia numerami EAN

**Comment by TomaszSzydlowski-sudo** [comment]
@MaciejFrackowiak jak szybko dacie rade to naprawić? Uciążliwe to jest przy aktualizacji produktyzacji.

**Comment by MaciejFrackowiak** [comment]
@TomaszSzydlowski-sudo Zespół pracuje nad tym, jednak na chwilę obecną nie potrafię wskazać jednoznacznego terminu, kiedy uda się wyeliminować problem.

**Comment by falconVS** [comment]
Źródłem problemu jest - "pozwolenie" na produkcję towarów które są w TECDOC użytkownikom

**Comment by FromAnyHole** [comment]
@falconVS - to jest kompletny bajzel i robienie z ludzi idiotów, blokowanie EAN w całym serwisie przez Produkty to poroniony pomysł, ludzie szału dostają zamiast sprzedawać...

**Comment by falconVS** [comment]
czy coś wiadomo ?

**Comment by MaciejFrackowiak** [comment]
@falconVS Obecnie trwają prace, których celem jest poprawna obsługa tego typu przypadków.

**Comment by falconVS** [comment]
@MaciejFrackowiak  to poproszę o info w jaki sposób aktualizować stany i ceny do momentu kiedy tego nie rozwiążecie.
Na dzień dzisiejszy jak ktoś dziś stworzy sobie jakiś produkt i dopisze EAN ja nie jestem w stanie bez kombinowania zaktualizować niczego na aukcji.

**Comment by MaciejFrackowiak** [comment]
@falconVS Obejściem jest obecnie sposób wymieniony przez @mlonc - zdaję sobie sprawę, że jest to mocno uciążliwe, jednak na tę chwilę jedyne wyjście dopóki nie zostanie wdrożone globalne rozwiązanie.

**Comment by falconVS** [comment]
Żeby nie powstał jeszcze większy problem w całej MOTORYZACJI powinniście zabronić tworzenie nowych produktów.

**Comment by falconVS** [comment]
@autoswiss - krążymy wokół zależności TECDOC - nowe produkty. 
Druga sprawa trwa w najlepsze nowa zabawa na allegro - wyścig w tworzenie nowych produktów w motoryzacji z reklamą swojej firmy - jako zdjęcie produktu. Podepnij taki produkt i masz piękną reklamę konkurencji

**Comment by MaciejFrackowiak** [comment]
@falconVS W nawiązaniu do mojej wcześniejszej wypowiedzi wszelkie spostrzeżenia dot. łączenia ofert z produktami proszę przekaż poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by MaciejFrackowiak** [comment]
@falconVS Wdrożyliśmy poprawkę, która powinna zapobiec podobnym sytuacjom z EAN w przyszłości.
