### ISSUE TITLE
Ograniczenie ilości checkout-form na zasobie order/checkout-forms: Offset and limit parameters exceed maximal result size of 10000 items

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#4027]
Witam,

Podczas pobierania zamówień z zasobu order/checkout-forms otrzymałem poniższą odpowiedź
{"errors":[{"code":"VALIDATION_ERROR","message":"Offset and limit parameters exceed maximal result size of 10000 items","details":null,"path":"/order/checkout-forms","userMessage":null}]} StatusCode: 422 

Limit ustawiony na 100, offfset na 10100. Całkowita ilość elementów: 10658

Zgodnie z dokumentacją:
422 Unprocessable Entity - Returned when limit or offset value is outside an acceptable range 
ale wydawało mi się, że dotyczy to raczej liczb spoza dostępnego zakresu.
Skąd to ograniczenie? Powinienem być  w stanie pobrać wszystkie zamówienia.

**Comment by MaciejFrackowiak** [comment]
Łączna suma limit i offset dla praktycznie każdego zasobu wynosi 10000 wyników. Jeżeli chcesz uzyskać dalsze dane to należy zawęzić wyszukiwanie np. podając przedział dat zamówienia. Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/orders/#lista-zam%c3%b3wie%c5%84).

**Comment by dol1234** [comment]
Dziękuję, nie znalazłem wcześniej tej informacji. Może warto byłoby dodać bezpośrednio w dokumentacji zasobu do opisu błędu 422.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoją sugestię dot. dokumentacji.
