### ISSUE TITLE
/order/checkout-forms/ a płatnośc bonami

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#4029]
Witam
W ktorej sekcji znajde informacje o platnosci bonem za zamowienie?
Klient twierdzi, ze zapłacił cześć bonem, a część przelewem - kontaktował sie z Allegro, które podobno potwierdziło,  że sprzedawca powinien widzieć zapłatę bonem.
Niestety przy wywołaniu zasobu /order/checkout-forms/171acfc2-42e1-11eb-9416-77859a6cda69, 
mamy   platność rozpoczętą i status FILLED_IN,

**Comment by MaciejFrackowiak** [comment]
Nie znajdziesz takiej informacji - jeśli płatność zostanie przeprocesowana i status zamówienia zmeni się na READY_FOR_PROCESSING to wówczas zobaczysz informację o otrzymanej pełnej płatności.  Z punktu widzenia Sprzedającego nie ma znaczenia w jakiej formie zapłacił Kupujący - jako Sprzedający otrzymujesz pełną wartość zamówienia. Natomiast w przypadku ewentualnego zwrotu płatności przez Allegro Finanse to już nasz mechanizm właściwie podzieli przekazane środki do Kupującego.

**Comment by anaxagore78** [comment]
Rozumiem, czyli jesli klient uważa, że zapłacił 200pln bonem, a reszte dopłacił poza Payu Allegro (zwykłym przelewem), to z punktu widzenia Allegro nie jest opłacone.

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak - został na chwilę obecną wyłącznie wypełniony formularz pozakupowy, jednak płatność nie została zakończona.
