### ISSUE TITLE
Aktywacja konta firma.

### ISSUE THREAD

**Issue by Grucholek** [allegro/allegro-api#403]
Dzień dobry,
Jak wygląda aktywacja konta firma w sandboxie? Faktycznie trzeba czekać te 3 dni? Jest mi ono potrzebne do wystawienia aukcji z większą ilością zdjęć niż 10.
Login do konta które oczekuje aktywacji: winkiel
Pozdrawiam.

**Comment by MaciejPotepa** [comment]
Dzień dobry 

Aktywowałem Twoje konto na sandboxie i nadałem mu status firma. 

Pozdrawiam,

**Comment by ma-mdz** [comment]
Proszę o aktywację konta  "mediaamba-bsl" w sandbox.

**Comment by myszaq99** [comment]
proszę o aktywację konta 'alucenter' w sandbox

**Comment by PawelTaberski** [comment]
@myszaq99  Wstępnie aktywowałem Twoje konto, aby zakończyć proces podeślij przez zakładkę moje konto jakieś dowolne dwa pliki.
