### ISSUE TITLE
Ciągły problem z 406 Client Error: Not Acceptable

### ISSUE THREAD

**Issue by Shanduur** [allegro/allegro-api#4031]
Próbuje zapoznać się z API Allegro. W tym celu napisałem prostą aplikację, która w portalu *apps.developer.allegro.pl.allegrosandbox.pl* została zarejestrowana jako *Aplikacja będzie działać w środowisku bez dostępu do przeglądarki albo klawiatury (np. aplikacja konsolowa albo na urządzeniu typu telewizor)*:

<details>
    <summary>Kod aplikacji</summary>

```python
import requests as req

def getToken():
    AUTH_URL = r'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials'
    CLIENT_ID = 'put id here'
    CLIENT_SECRET = 'put secret here'

    res = req.get(AUTH_URL, auth=(CLIENT_ID, CLIENT_SECRET))
    if not res.ok:
       res.raise_for_status()

    body = res.json()

    return body['access_token']

def getInfo(token: str):
    PARAMS = {
        'Authorization': r'Bearer '+token,
        'Accept': r'application/vnd.allegro.public.v1+json'
    }
    BASE_URL = r'https://api.allegro.pl.allegrosandbox.pl/sale/categories'

    res = req.get(BASE_URL, params=PARAMS)
    if not res.ok:
        res.raise_for_status()

    resp_body = res.json()

    return resp_body

if __name__ == "__main__":
   try:
      token = getToken()
      info = getInfo(token)
      print(info)
   except Exception as e:
      print(e)
```

</details>

Niestety przy każdej próbie uzyskania dostępu otrzymuje poniższy Error:
<details>
    <summary>Kod błędu</summary>

```log
406 Client Error: Not Acceptable for url: https://api.allegro.pl.allegrosandbox.pl/sale/categories?Authorization=Bearer+TOKEN&Accept=application%2Fvnd.allegro.public.v1%2Bjson
```

</details>

Skoro otrzymany token jest prawidłowy, natomiast wartość parametru `Accept` jest zgodna z tym co podane jest w przykładach na *developer.allegro.pl/getting_started*, czy jest w stanie mi ktoś wskazać błąd w kodzie lub poprawną wartość parametru `Accept`? Z góry dziękuje za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Ze względu na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich, jednak odpowiedź, którą otrzymujesz świadczy o tym, że nagłówki Authorization i Accept przekazujesz w żądaniu jako query parametry zamiast jako nagłówki. Być może któryś z użytkowników forum napotkał podobny problem i będzie w stanie pomóc w kwestii zmiany kodu.

**Comment by Shanduur** [comment]
Dzięki, nagłówki faktycznie pyły błędnie przekazywane. Gdyby ktoś jeszcze miał taki problem w Pythonie (moduł `requests`), należy zmienić:

```python
    res = req.get(BASE_URL, params=PARAMS)
``` 

na 

```python
    res = req.get(BASE_URL, headers=PARAMS)
```
