### ISSUE TITLE
jak zdobyć token za pomocą javascript

### ISSUE THREAD

**Issue by SerhiiShymchuk** [allegro/allegro-api#4032]
Czy możesz podać przykład kodu, aby uzyskać token w języku programowania JavaScript , node.js?

**Comment by MaciejFrackowiak** [comment]
Due to a large number of programming languages, we do not support all of them. We described how to authenticate application and users in [our tutorial](https://developer.allegro.pl/en/auth/). Perhaps someone from the forum users will be able to support you in this topic.

**Comment by SerhiiShymchuk** [comment]
poradziłem sobie z tym pytaniem. Oto przykładowy kod (Node.js)
```
const fetch = require('node-fetch')
fetch(url, {
        method: 'GET',
        headers: {
            Authorization: 'Basic ' + Buffer.from(clientID + ':' + clientSecret).toString('base64')
        }
    })
    .then(response => response.json())```

**Comment by TomaszSzydlowski-sudo** [comment]
@SerhiiShymchuk Czemu  reopened?

**Comment by kozakiewicz1221** [comment]
Ten kod nie chce działać. API zwraca błąd:
{ error: 'Unauthorized', error_description: 'Unauthorized' }

Ktoś wie gdzie jest błąd?


fetch('https://allegro.pl/auth/oauth/token', {
    method: 'GET',
    headers: {
      Authorization:
        'Basic ' +
        Buffer.from(
         clientID +
            ':' +
          clientSecret
        ).toString('base64'),
    },
  })
    .then((response) => response.json())
    .then((data) => console.log(data))
