### ISSUE TITLE
GET /sale/offers - HTTP 500

### ISSUE THREAD

**Issue by pawel-web** [allegro/allegro-api#4033]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przy próbie GET `https://api.allegro.pl.allegrosandbox.pl/sale/offers` dostaję błąd 500.

Pełny respone: 
```
"errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
```
Błąd występuje niezależnie od miejsca wywołania zapytania (php console/postman) oraz od ustawionego typu klucza (DEVICE/WEB).

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - na ten moment nie potwierdzam występowania problemu. Pobieranie ofert na środowisku testowym powinno być możliwe. Podaj proszę trace-id przykładowego wywołania, które zakończyło się błędem 500.

**Comment by pawel-web** [comment]
Problemem okazała się próba pobrania danych przy pomocy bearer-token-for-application a nie bearer-token-for-user. 
Przydało by się by serwer zwracał odpowiedni komunikat o błędnym tokenie w takim przypadku zamiast 500.

**Comment by AureliuszBrussy** [comment]
Dziękuję za wyjaśnienie. Potwierdzam - w takim przypadku zwracamy w tym momencie błąd 500. Kwestię dotyczącą innego kodu błędu w takich przypadkach zgłosiłem do odpowiedniego zespołu.
