### ISSUE TITLE
Czy to normalne, że e-maile nie dochodzą w sandbox?

### ISSUE THREAD

**Issue by pakkpl** [allegro/allegro-api#4034]
Wysyłam sobie emaila na adres typu utyyp4rqcp+423ee7564@user.allegrogroup.pl
i nie dochodzi, jesli wyślę z błędnego adresu (nie przypisanego do mojego konta) to dostanę zwrotkę, ale jeśli wysyłam poprawnie to cisza.  Kupujący ani sprzedający nie dostaje żadnego email'a.
Tak to powinno działać? Czy też występuje jakiś problem?

**Comment by pakkpl** [comment]
W centrum wiadomości jest:
"Sprawdzamy tę wiadomość pod kątem zgodności z naszymi zasadami"
Jak długo to trwa? Czy tez zawisa to i raczej nie ma się co spodziewać, że email dojdzie?

**Comment by AureliuszBrussy** [comment]
Konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@pakkpl wystąpiły chwilowe opóźnienia w dostarczaniu wiadomości i ich weryfikowaniu na Sandboxie. Aktualnie problemy te nie powinny występować.

**Comment by pakkpl** [comment]
Dziękuję, sprawdziłem i już działa :)
