### ISSUE TITLE
[Ridiculous REST] - Dziennik zdarzeń z ostatniej doby?!? A czemu nie z godziny...

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#4036]
Albo zrobicie zasięg czasowy do 30 dni (zbieżnie z tymi wynalazkami na historię ofert kupna - też paranoja), albo miesiące testowania Bety są NIEPOROZUMIENIEM (znowu) !!!
EOM!

**Comment by AureliuszBrussy** [comment]
Dziękuję za Twoją uwagę. Dopisałem ją do listy sugestii dotyczącej rozwoju API.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - tak od początku powinien być przewidziany dla tego zasobu zasięg czasowy, offset na kolejną porcję danych, limit już jest, resztę każdy by sobie filtrował (?limit=1000&scope=30&offset=0). Czekamy na rozsądek...

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - klient potrzebuje właśnie konkretne zdarzenia z ostatniego weekend'u, no i co - ma do Poznania podanie pisać w tej sprawie...?? Dla kogo to jest zrobione, to ma być dziennik?

**Comment by AureliuszBrussy** [comment]
Dziennik zdarzeń służy do bieżącego śledzenia aktualnych zdarzeń. W razie jakiś wątpliwości co do zmian w ofercie - sprzedający może skontaktować się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by Onixarts** [comment]
Również jestem za tym aby danych w tym dzienniku było więcej. Inaczej jest on tylko połowicznie użyteczny. Kilkudniowe nieobecności użytkowników działających np na desktopach to cotygodniowy wręcz standard, więc w przykładowy poniedziałek nie da się ściągnąć tym sposobem danych z weekendu, gdy aplikacja nie pracowała. Trzeba i tak pobierać wszystkie dostępne oferty aby mieć świeży komplet danych lokalnie. W wielu przypadkach są to dziesiątki minut nieustannej jazdy po ofertach.

**Comment by AureliuszBrussy** [comment]
@Onixarts dziękuję za opinię. Dopisałem Twój głos do tej sugestii.
