### ISSUE TITLE
pobranie ofert, które nie mają sygnatury

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#4037]
witam, 
staram się pobrać aktywne oferty, które nie mają sygnatury za pomocą get "/sale/offers?publication.status=ACTIVE&external.id="
niestety bez rezultatów. Czy jest jakiś inny sposób?
pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy możliwości filtrowania ofert nie mających wprowadzonej wartości w polu external.id.
