### ISSUE TITLE
Korzystanie z API w celach komercyjnych

### ISSUE THREAD

**Issue by patrykpalej** [allegro/allegro-api#4038]
W regulaminie korzystania z API nie znalazłem żadnych przeciwwskazań, ale dla pewności chciałbym zapytać o to wprost. Czy dozwolone jest wykorzystanie API do celów komercyjnych związanych z pozyskiwaniem danych dotyczących rynkowych cen produktów na przykładzie aukcji w serwisie Allegro?

**Comment by AureliuszBrussy** [comment]
Takie działanie nie jest niezgodne z regulaminem Allegro API. Zwróć jednak uwagę, że mechanizm taki nie powinien być wykorzystywany np. do prezentowania w serwisach konkurencyjnych Ofert (w tym Ofert archiwalnych) publikowanych w ramach Allegro.
