### ISSUE TITLE
Storna do dodania nowej oferty nie działa

### ISSUE THREAD

**Issue by LocalHeroPro** [allegro/allegro-api#4039]
Przechodzę na stronę dodania nowej oferty: 
https://staging-lokalnie.allegrogroup.com/oferty/wystaw
i mam następujący widok:
![image](https://user-images.githubusercontent.com/42643563/103486822-fd34e200-4e00-11eb-9e1e-8f1c62eaf0bd.png)
Sytuacja występuje zawsze na każdej przeglądarce.

**Comment by AureliuszBrussy** [comment]
Faktycznie, podczas próby wystawiania oferty z konta zwykłego (nie posiadającego statusu Firma) następuje przekierowanie na nieistniejącą witrynę. Wiemy o tym problemie. Na ten moment proszę, abyś korzystał w takim przypadku z tego linku https://allegro.pl.allegrosandbox.pl/offer/.

Dla konta zwykłego na Sandboxie w Moje Allegro, tak samo jak w przypadku wersji produkcyjnej strony - pokazujemy linki prowadzące do Allegro Lokalnie. Allegro Lokalnie nie posiada środowiska testowego, stąd też brak możliwości wyświetlenia strony.

Aby ominąć ten problem, możesz także zmienić typ konta na konto firma w zakładce [Dane Konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta/). W zakładce tej też wyślij dwa dowolne pliki do weryfikacji.

**Comment by LocalHeroPro** [comment]
Link: https://allegro.pl.allegrosandbox.pl/offer/ przekierowuje mnie na https://staging-lokalnie.allegrogroup.com/oferty/wystaw, więc jest petla.

**Comment by LocalHeroPro** [comment]
Posiadam konto firmowe z oznaczeniem `Status konta: Sprzedaż aktywna`, ale w dalszym ciągu występuje przekierowanie, które opisałem powyżej.

**Comment by corteum** [comment]
Prawidłowy link to: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

**Comment by AureliuszBrussy** [comment]
Przepraszam za podanie błędnego linku, faktycznie, ten podany przez @corteum jest poprawny.
Czy mógłbyś podać login konta na Sandboxie? Sprawdzę to.
