### ISSUE TITLE
Pobieranie informacji o cenniku dostaw przaypisanym do konkretnej oferty

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#404]
Jak w temacie , czy istnieje jakaś opcja pobrania informacji o identyfikatorze  cennika / cennikach dostaw przypisanych do konkretnej oferty ? Czy w najbliższym czasie planowana jest taka funkcjonalność

**Comment by MaciejPotepa** [comment]
Dzień dobry

W ciągu kilku tygodni udostępnimy taką możliwość. O wszystkich zmianach będziemy informować z odpowiednim wyprzedzeniem.

**Comment by sis6326r** [comment]
a czy  przypadkiem tej informacji nie zwraca metoda GET /sale/offers/{offerId} w sekcji 
 delivery/shippingRates?

**Comment by MaciejPotepa** [comment]
@sis6326r tak, masz rację. Źle zrozumiałem pytanie i miałem przez to na myśli zasoby do zarządzania cennikami dostaw w REST API- tworzenie, edycja. 

@11mszot Informacje, których potrzebujesz pobierzesz przy pomocy GETa /sale/offers/{offerId} pola
delivery i shippingRates.
