### ISSUE TITLE
How do I get the order`s return list and the corresponding order information

### ISSUE THREAD

**Issue by hyzgtihub** [allegro/allegro-api#4040]
Hello，

I want to get a list of returns through the rest API，so, which API can be reached? 

The data presentation in the allegro`s background looks like this:
![image](https://user-images.githubusercontent.com/15359396/103516224-1b571c80-4eab-11eb-823d-0db12776cb53.png)

thanks.

**Comment by PrzemyslawLukanowski** [comment]
At the moment we don't have resources for managing Returns in API, we plan to introduce them by the end of Q1.

**Comment by hyzgtihub** [comment]
Thank you.  :)
