### ISSUE TITLE
Problem z shippingFromPoland: 1

### ISSUE THREAD

**Issue by meridPL** [allegro/allegro-api#4043]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

wykonuje w pythonie przy pomocy biblioteki requests

requests.get("https://api.allegro.pl/offers/listing", headers={
    "Authorization": "Bearer " + access_token,
    "Accept": "application/vnd.allegro.public.v1+json",
}, params={
                "category.id": 305601,
                "phrase": "Lego 42082",
                "shippingFromPoland": 1,
                "parameter.11323": "11323_1",
                "sellingMode.format": "BUY_NOW",
                "sort": "+price",
                "offset": offset,
                "fallback": "false"
            })

Chce się pozbyć tego chińskiego sprzedawcy, który zaniża statystyki 720,71 zł i jest z chin. Użyłem "shippingFromPoland": 1, ale on cały czas się wyświetla.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten temat z odpowiednim zespołem. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej informacji.

**Comment by PrzemyslawLukanowski** [comment]
Prepraszam za długi czas odpowiedzi. Filtr "dostawa z Polski" działa - podobnie jak na froncie - tylko w wybranych kategoriach. Możesz z niech skorzystać, jeśli w odpowiedzi na żądanie w sekcji filters otrzymasz:

```
   {
            "id": "shippingFromPoland",
            "type": "MULTI",
            "name": "Dostawa z Polski",
            "values": [
                {
                    "value": "1",
                    "name": "tak",
                    "selected": false
                },
                {
                    "value": "0",
                    "name": "nie",
                    "selected": false
                }
            ]
        }
```

**Comment by meridPL** [comment]
To w takim razie jak nie występuje to w mojej kategorii to jak wyeliminować chińskie podróbki ?

**Comment by PrzemyslawLukanowski** [comment]
Aby ograniczyć wyniki tylko dla Polski, możesz wykorzystać parametr location={province} - tego parametru nie da się przekazać więcej niż jeden raz, dlatego musisz wykonać więcej requestów.

**Comment by meridPL** [comment]
Próbowałem już z tym parametrem tylko problem jest taki, że tam mogę wpisać tylko województwo lub miasto. Można tam wpisać ewentualnie Polska ? Czy muszę dla każdego województwa wpisać request. No i co w przypadku jeżeli jakiś przedmiot nie ma województwa ?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie da się wpisać tam "Polska".  Dla każdego województwa musiałbyś wysłać osobny request, a jeżeli przedmiot nie ma województwa - zostanie pominięty w wynikach.

**Comment by meridPL** [comment]
A czy gdzieś jest lista co należy wpisać w tą listę. Czy litery muszą być duże, z polskimi znakami. No i dlaczego jeżeli się nie zgadza województwo to zwraca wszystko ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, taką listę znajdziesz na końcu odpowiedzi. To, co musisz wpisać, umieszczone jest w polu value. Jeżeli wartość się nie zgadza, jest ona pomijana, dlatego otrzymujesz wszystkie wyniki.

```
   {
            "id": "location.province",
            "type": "SINGLE",
            "name": "Województwo",
            "values": [
                {
                    "value": "DOLNOSLASKIE",
                    "name": "z dolnośląskiego",
                    "selected": true
                },
                {
                    "value": "KUJAWSKO_POMORSKIE",
                    "name": "z kujawsko-pomorskiego",
                    "selected": false
                },
                {
                    "value": "LUBELSKIE",
                    "name": "z lubelskiego",
                    "selected": false
                },
                {
                    "value": "LUBUSKIE",
                    "name": "z lubuskiego",
                    "selected": false
                },
                {
                    "value": "LODZKIE",
                    "name": "z łódzkiego",
                    "selected": false
                },
                {
                    "value": "MALOPOLSKIE",
                    "name": "z małopolskiego",
                    "selected": false
                },
                {
                    "value": "MAZOWIECKIE",
                    "name": "z mazowieckiego",
                    "selected": false
                },
                {
                    "value": "OPOLSKIE",
                    "name": "z opolskiego",
                    "selected": false
                },
                {
                    "value": "PODKARPACKIE",
                    "name": "z podkarpackiego",
                    "selected": false
                },
                {
                    "value": "PODLASKIE",
                    "name": "z podlaskiego",
                    "selected": false
                },
                {
                    "value": "POMORSKIE",
                    "name": "z pomorskiego",
                    "selected": false
                },
                {
                    "value": "SLASKIE",
                    "name": "ze śląskiego",
                    "selected": false
                },
                {
                    "value": "SWIETOKRZYSKIE",
                    "name": "ze świętokrzyskiego",
                    "selected": false
                },
                {
                    "value": "WARMINSKO_MAZURSKIE",
                    "name": "z warmińsko-mazurskiego",
                    "selected": false
                },
                {
                    "value": "WIELKOPOLSKIE",
                    "name": "z wielkopolskiego",
                    "selected": false
                },
                {
                    "value": "ZACHODNIOPOMORSKIE",
                    "name": "z zachodniopomorskiego",
                    "selected": false
                }
            ]
        },
```
