### ISSUE TITLE
You cannot change category after 12 hours from publication

### ISSUE THREAD

**Issue by danmckp** [allegro/allegro-api#4044]
Allegro samo łączy produkty z innego działu po kodzie EAN. Efekt jest taki ze pozniej nie mozna zaktualizowac takiej oferty poniewaz jest w innym dziale i wychodzi blad jak na dole

Co w takim przypadku ? Nie ma mowy o zamykaniu aukcji i wystawianiu w innym dziale ze wzgledu na popularnosc. Nie da sie rozlaczyc tez produktu poniewaz zaraz wraca do polaczenia. Efekt taki ze nie mamy jak aktualizowac ofert ...

"Treść błędu You cannot change category after 12 hours from publication. Informacje o błędzie: {"errors":[{"code":"VALIDATION_ERROR","message":"You cannot change category after 12 hours from publication.","details":"","path":"","userMessage":"Nie możesz zmienić kategorii po 12 godzinach od wystawienia."}]}StatusCode: 422x-xss-protection: 1; mode=blockpragma: no-cachex-frame-options: DENYtrace-id: a82dd79b36950b67x-content-type-options: nosnifftransfer-encoding: chunkedCache-Control: no-cache, no-store, max-age=0, must-revalidateContent-Type: application/jsonDate: Tue, 05 Jan 2021 08:55:20 GMTExpires: 0"

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten problem do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku możesz posługiwać się kategorią, w której obecnie jest wystawiona oferta. Nie będziemy blokować edycji ze względu na niezgodność kategorii.

**Comment by danmckp** [comment]
> W takim przypadku możesz posługiwać się kategorią, w której obecnie jest wystawiona oferta. Nie będziemy blokować edycji ze względu na niezgodność kategorii.

Dziękuję za informację
W jakim terminie można spodziewać się poprawki ?
Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Nię będziemy tutaj wprowadzać poprawki - tak jak wspomniałem, w takich sytuacjach wystarczy w modelu oferty przesłać pierwotny numer kategorii, a request zakończy się prawidłową odpowiedzią.

**Comment by mindc** [comment]
@PrzemyslawLukanowski 
> W takim przypadku możesz posługiwać się kategorią, w której obecnie jest wystawiona oferta. Nie będziemy blokować edycji ze względu na niezgodność kategorii.

Hmmm.... jeśli oferta połączona jest z produktem, to nie da się zrobić czegoś takiego jak piszesz. Trzeba wtedy zrezygnować z podpinania produktu. Trzeba także zrezygnować z podawania EAN, bo wtedy następuje automatyczne podpięcie produktu.
Więc aby było możliwe pozostawienie wybranej/pierwotnej kategorii, należy zrezygnować z obu tych rzeczy.

Dodatkowo, coraz więcej kategorii wymaga produktyzacji i wtedy "papa" historia sprzedaży bo nie można aktualizować istniejących ofert...

**Comment by danmckp** [comment]
Już się udało. Jak jest zwracany inny numer kategorii to wtedy najlepiej wyłączyć z aktualizacji parametry (które i tak są już uzupełnione na karcie produktyzacji) i aktualizacja jest udrożniona
Pozdrawiam
