### ISSUE TITLE
Opłata za utrzymanie oferty wznowionej

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4045]
Jak liczony jest czas 365 dni związany z **dodatkową opłatą za utrzymanie oferty bez sprzedaży** jeśli oferta zostanie zakończona i po miesiącu wznowiona?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji w momencie zakończenia oferty licznik dni zostanie zastopowany, a po wznowieniu ponownie naliczany.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, sprostuję wcześniejszą informację - licznik w takiej sytuacji nie zostaje zastopowany.

**Comment by tomylee0** [comment]
Zatem dla jasności proszę o potwierdzenie czy taki scenariusz jest prawidłowy:
1. Oferta jest aktywna 340 dni i nie było sprzedaży.
2. Potem oferta jest nieaktywna 30 dni.
3. Opłata utrzymaniowa **nie była do tej pory pobrana** bo wprawdzie licznik ma już 370 dni ale oferta nie jest aktywna.
4. Potem wznawiam ofertę. 340 aktywności + 30 nieaktywności daje 370 dni z czego wynika, że **w dniu wznowienia zostanie pobrana opłata utrzymaniowa a licznik będzie ustawiony na 5 dni** (bo 370 - 365).

?

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze raz skonsultowałem ten temat z odpowiednim zespołem - moja pierwsza odpowiedź jest prawidłowa, przepraszam za zamieszanie. W opisanym przypadku w momencie wznowienia licznik będzie wynosić 340 dni.

**Comment by tomylee0** [comment]
W jaki sposób przez REST API mógłbym odczytać wartość licznika?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości.

**Comment by Aryak2099** [comment]
Musisz sam sprawdzić kiedy oferta była wystawiona i policzyć czas, potem zapisać sobie w bazie datę ostatniej sprzedaży.

**Comment by tomylee0** [comment]
Chciałbym zgłosić sugestię aby była możliwość odczytania wartości tego licznika. Bowiem w przypadku kiedy aplikacja REST API będzie miała dostęp tylko do **zarządzania ofertami** bez możliwości **zarządzania zamówieniami** to bez danych dotyczących sprzedaży nie będę miał możliwości samodzielnego wyliczenia wartości licznika.

**Comment by PrzemyslawLukanowski** [comment]
Zapisałem tę sugestię. Poinformuję, jeżeli zdecydujemy się wprowadzić takie rozwiązanie.
