### ISSUE TITLE
Get suggested compatibility list.

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4046]
Witam, 
Chciałbym zrealizować taki scenariusz:
1) mam ofertę z częścią samochodową - zamiennikiem, który nie występuje w tecdoc
2) znalazłem produkt, który jest zamiennikiem do mojej oferty
3) pobieram z 
https://api.allegro.pl/sale/compatibility-list-suggestions?product.id=4437b40a-6f6d-48b3-b15d-7f1d76dd1774
listę "pasuje do"
4) w ofercie wstawiam identyfikatory pojazdów z pkt 3

Pytania:
czy takie podejście jest ok, czy może jest jakieś bardziej optymalne?
dlaczego w pkt 3 dostaję: "Dla podanego produktu nie znaleziono sugerowanej tabeli kompatybilności."?

**Comment by PrzemyslawLukanowski** [comment]
Tak, podejście jest ok. Co do drugiego pytania - w naszej bazie nie posiadamy żadnych sugestii Pasuje Do dot. tego produktu. Sugestie tworzymy na podstawie list komptybilności ofert innych sprzedających, wygląda na to, że nikt nie wystawił oferty z tym produktem, podając jednoczesnie Pasuje Do.

**Comment by kfijalko** [comment]
Moglibyście to trochę jaśniej opisać w dokumentacji.
Czyli jeżeli 
1) sprzedawca wystawi ofertę z tym produktem, 
2) w ofercie pojawi się "pasuje do" na podstawie produktu (nie jest uzupełniana przez sprzedawcę)
3) odpytanie zasobu https://api.allegro.pl/sale/compatibility-list-suggestions zwróci mi "pasuje do" z pkt 2 ?

**Comment by PrzemyslawLukanowski** [comment]
Zasób /sale/compatibility-list-suggestions zwróci listę sugestii w przypadku, gdy produkt nie zawiera swojej własnej listy 'Pasuje Do', lecz została ona manualnie dodana (do oferty powiązanej z produktem) przez sprzedających.

**Comment by kfijalko** [comment]
To trochę inaczej to zrozumiałem.

**Comment by kfijalko** [comment]
W takim wypadku
1) mam zamienniki, których nie ma w tecdoc
2) wyszukuje w bazie allegro produkt, który jest zamiennikiem do mojego
3) pobieram dane produktu, w tym sekcję "pasuje do" - ta sekcja nie zawiera identyfikatorów pojazdów, tylko nazwy
4) pobieram bazę pojazdów z allegro
5) na podstawie nazw ustalam identyfikatory pojazdów (zaraz sprawdzę, ale wydaje mi się, że są unikatowe)
6) w swojej ofercie przekazuję listę id z pkt 5

a) czy takie podejście jest ok?
b) czy da się jakoś inaczej powiązać ofertę z "pasuje do" z produktu, tak żebym nie musiał jej aktualizować jak zrobicie aktualizację tecdoc ?

**Comment by PrzemyslawLukanowski** [comment]
a) nie możemy jednoznacznie potwierdzić, że takie podejście jest ok. Dane mamy z TecDoc, który nie zapewnia, że różne zamienniki pasują do tych samych pojazdów - TecDoc zabrania takiego wykorzystania jego danych, dlatego właśnie nie podajemy identyfikatorów pojazdów w produktowej sekcji compatibilityList.
b) na tę chwilę mogę polecić funkcjonalność z frontu - ["Aktualizuj danymi z produktu"](https://allegro.pl/dla-sprzedajacych/jak-zaktualizowac-dane-w-swoich-ofertach-na-podstawie-powiazanych-produktow-7wqydBLedhY) z zakładki Moje oferty. W przyszłości planujemy udostępnić rozwiązanie, w którym będziemy automatycznie aktualizować wszystkie dane produktu w ofercie. Jako pierwszy krok [wprowadziliśmy automatyczną aktualizację danych w tecdocSpecification i compatibilityList](https://developer.allegro.pl/news/#simple-api-update) przy edycji oferty za pomocą [PATCH /sale/product-offers/{offer-id}](https://developer.allegro.pl/documentation/#operation/editProductOffers).

**Comment by kfijalko** [comment]
a) do tego wniosku doszedłem.

czy mogę do oferty nie związanej z produktem podać CompatibilityList->PRODUCT_BASED i podać id produktu?
wtedy w ofercie "dociągniecie" pasuje do ze wskazanego produktu?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie, takie rozwiązanie nie zadziała.

**Comment by kfijalko** [comment]
Szkoda, dziękuję za pomoc.
Z poważaniem KF
