### ISSUE TITLE
Produkt ma wpisaną kategorię która nie istnieje

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4049]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Kiedy pobieram produkt po kodzie EAN `6970075601034` to dostaję w odpowiedzi produkt który ma wpisaną kategorię `63805` która po pobraniu zwraca błąd.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem to - kat. 63805 jest dostępna i można ją pobrać przez GET /sale/categories/{categoryID}. Jeżeli problem w Twoim przypadku nadal występuje, podaj proszę przykładowe trace-id.

**Comment by AnimalDEV** [comment]
Dziękuję za pomoc. Już znalazłem źródło problemu.
