### ISSUE TITLE
Sandbox - kupione aukcje 

### ISSUE THREAD

**Issue by raav88** [allegro/allegro-api#405]
Mam problem z kupionymi aukcjami. Czasami nigdzie ich nie ma ani w Sprzedanych ani w Zamówieniach. Czasami są tylko w Zamówieniach. Od czego to zależy ?

**Comment by MaciejPotepa** [comment]
@raav88 możliwe, że trafiłeś na problem z zaciąganiem ofert do tych zakładek.

Czy problem się powtarza cały czas? 

Żeby go zidentyfikować potrzebujemy więcej informacji:
- czas w jakim problem występuje
- konto
- przykładowe oferty, które się nie pojawią 

Bez tych informacji rozwiązanie tego problemu jest bardzo trudne.  Będę wdzięczny jeżeli takowe posiadasz.

**Comment by raav88** [comment]
Do wczoraj problem cały czas się pojawiał i dzieje się to co najmniej od piątku, wliczając to sobotę niedzielę i wczorajszy dzień.
Konto: kurierbps
Oferty: raczej każda ale oferty, które były kupowane to m.in.: 
https://allegro.pl.allegrosandbox.pl/sony-sluchawki-kurier-wieczor-2-12-24-0-i6205375756.html
https://allegro.pl.allegrosandbox.pl/sony-sluchawki-kurier-dhl-3-12-5-i6205375752.html
https://allegro.pl.allegrosandbox.pl/sony-sluchawki-austria-3-40-10-i6205375737.html

**Comment by MaciejPotepa** [comment]
@raav88 

Dzięki za zgłoszenie. Badamy problem.

**Comment by raav88** [comment]
Czy już coś wiadomo ?

**Comment by MaciejPotepa** [comment]
@raav88 niestety, jeszcze nie. Dam znać jak problem zostanie rozwiązany.
