### ISSUE TITLE
api.allegro.pl:443 connect timed out

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4050]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Czy są jakieś problemy z serwerami Allegro? Dziś wysyłając requesty z różnych serwerów (różnych adresów IP) otrzymujemy informację o nieudanym połączeniu:

Connect to api.allegro.pl:443 [api.allegro.pl/5.134.213.11] failed: connect timed out
Connect to api.allegro.pl:443 [api.allegro.pl/185.31.27.150] failed: connect timed out

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, nie otrzymaliśmy również innych zgłoszeń powiązanych z tym problemem. Prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) (w zgłoszeniu dopisz, że logi dotyczą wątku #4050 na Githubie), sprawdzimy to.

**Comment by p-pawel** [comment]
No to chyba nie był to odosobniony przypadek, bo u nas również było to samo. "Connection timed out" jest w logach od około 11:55 do około 13:47.

**Comment by tomylee0** [comment]
Dzięki @p-pawel za potwierdzenie. U mnie problem też był w tym samym mniej więcej przedziale czasowym.

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem temat z naszymi zespołami - potwierdzam, że wczoraj miał miejsce problem dot. zwiększonej liczby time-outów. Przepraszam za utrudnienia.
