### ISSUE TITLE
Dodanie nowego scope dla połączonych już kont z aplikacją

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#4051]
Mam pytanie o scope'y które mają wejść 11.01: https://github.com/allegro/allegro-api/issues/4022

Z informacji, które udostępniliście wynika, że dla dotychczasowo połączonych kont dostajemy pełną listę, jak poniżej:
```
"scope":"allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read"
```

Pytanie, co jeśli nadal będziemy korzystać z kont dla których wcześniej nie przekazywaliśmy parametru scope, a załóżmy że dodalibyście po jakimś czasie nowy scope. Czy zostanie on automatycznie dodany do listy, czy użytkownik będzie musiał na nowo zatwierdzać uprawnienia ?

**Comment by PrzemyslawLukanowski** [comment]
Jeżeli pojawią się nowe scope'y, użytkownik będzie musiał wysłać request, w którym o nie poprosi.
