### ISSUE TITLE
Błędy parametr offset

### ISSUE THREAD

**Issue by LocalHeroPro** [allegro/allegro-api#4052]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Pobranie zamówień z przekazaniem parametru offset powyżej 10000 powoduje błąd
```
{"errors": [{"code": "VALIDATION_ERROR", "path": "/order/checkout-forms", "details": null, "message": "Offset and limit parameters exceed maximal result size of 10000 items", "userMessage": null}]}
```
zaś dokumentacja zaprzecza możliwości takiego zachowania:
![image](https://user-images.githubusercontent.com/42643563/104096642-46bb7c00-529c-11eb-8192-1acff55ac69e.png)
podając parametr `offset` jako >= 0.

Naprawicie walidację? Czy poprawicie dokumentację?
Tak czy inaczej, jak mogę pobrać listing zamówień z parametrem offset powyżej 10k?

**Comment by PrzemyslawLukanowski** [comment]
Podobnie jak w wątku #4027 - aby uzyskać dalsze dane, możesz zawęzić wyniki wyszukiwania za pomocą dat w lineItems.boughtAt.lte i lineItems.boughtAt.gte. Informację o maksymalnym offsecie znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#lista-zam%c3%b3wie%c5%84), przedyskutujemy też, aby dodać ją w dokumentacji.

**Comment by LocalHeroPro** [comment]
No nic, zwyczajnie pod górkę.
Dzięki za odpowiedź.
