### ISSUE TITLE
Access all necessary parts of the API

### ISSUE THREAD

**Issue by OKschroeter** [allegro/allegro-api#4053]
I am working on automate communication between Oskar Kinderland and Allegro. After authentication via API we are not able to access essential API parts like create products (Endpoint: https://api.allegro.pl/sale/product-proposals) where i get an 403 - Forbidden.

**Comment by MaciejFrackowiak** [comment]
What kind of authorization did you use? It looks that it was client_credentials authorization which does not have user context. To get access to resources like [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) you have to use bearer-token-for-user, so you should choose [code](https://developer.allegro.pl/en/auth/#user) or [device](https://developer.allegro.pl/en/auth/#userDeviceFlow) flow.

**Comment by OKschroeter** [comment]
Yes i used client_credentials. Other tested authorization forces me to confirm the authorization via any website. To automize our processes we need an authorization without seperate confirmation.

**Comment by MaciejFrackowiak** [comment]
As I wrote before - you cannot use client_credentials to propose a product. You have to use authorization which supports bearer-token-for-user.

**Comment by OKschroeter** [comment]
Yes i understand.
In that case I think we need an "Software Statement ID". That id seems to be the only way to authenticate at the api without confirm authentication manually.
Or could you help me to use an authentication without that manual confirmation after authenticate at the api?

**Comment by MaciejFrackowiak** [comment]
No, every single authorization method which based on user context require user confirmation - it must be done by the user, not automatically. So you should make some changes in your solution which will allow using code or device flow.

**Comment by OKschroeter** [comment]
I checked the code and the device flow. I explain short what i understood and my problem with these. Please correct me if i am wrong:
code flow: 
- I grant my application once the access to the app. The next authorizations i get an url including the code i need to get the access token.
- My problem: if i get the url via browser (tested in RESTer) it works fine. If i try to get redirect-url in code the code-parameter is something like "error"
Device flow:
- I authorize at the API to get a link i send to any email to accept the authorization. At the same time i register in my app and get the token.
- My problem: Some processes will run overnight. There is no one to get and click the link in the email.

I really need help, what do i misunderstand or what am i using wrong? Please tell me, what to do to acces the API without extra url or link.

**Comment by MaciejFrackowiak** [comment]
Please, give us an example of request and response which you received, we will check it - send it via [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (please, add GitHub post number - 4053).

**Comment by MaciejFrackowiak** [comment]
We received your email with example but it shows only step 1 and 2 from [our tutorial](https://developer.allegro.pl/en/auth/#userDeviceFlow) - it is needed to go further with next steps which we described.

**Comment by OKschroeter** [comment]
I checked the code and the device flow. I explain short what i understood and my problem with these. Please correct me if i am wrong:
code flow: 
- I grant my application once the access to the app. The next authorizations i get an url including the code i need to get the access token.
- My problem: if i get the url via browser (tested in RESTer) it works fine. If i try to get redirect-url in code the code-parameter is something like "error"
Device flow:
- I authorize at the API to get a link i send to any email to accept the authorization. At the same time i register in my app and get the token.
- My problem: Some processes will run overnight. There is no one to get and click the link in the email.

I really need help, what do i misunderstand or what am i using wrong? Please tell me, what to do to acces the API without extra url or link.

**Comment by OKschroeter** [comment]
Thats what i told in my Mail.
The next steps require a person, who clicks the link or enters the code into an website. When we automatically transfer data there is no person to do that. Only a machine.

**Comment by MaciejFrackowiak** [comment]
That step requires user action - we cannot give access to resources without user confirmation. If user uses a WWW service, he has to log in with password to get access to most functionalities of Allegro too.

**Comment by OKschroeter** [comment]
I do understand to access data by login via ww service, and i understand 2-way authentication, if i login and accept that login via 2nd url or url-redirection.
But if our application logs on, to read/update orders or to update/upload offers, it does automatically without an employee sitting in front of the desktop. So nobody can grant access to the app. 
Isn't there any possibility to automize communication between allegro and our system without human ressource?

**Comment by MaciejFrackowiak** [comment]
No, it is impossible because the user has to grant consent for the application to perform operations/requests on his behalf.

**Comment by OKschroeter** [comment]
Ok next try.
What do i have to do if i use authentication via code_challenge and get back {[url]?error=login_required}.

**Comment by MaciejFrackowiak** [comment]
This error can happen when the auth cookies are not be sent correctly or are being blocked by ITP, or some sort of extension. Have you tried an incognito window? Or any other browsers? We are unable to give you more directions when we do not see your request and response, just error message. So if you do not resolve problem, send logs via [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (please, add GitHub post number - 4053).

**Comment by OKschroeter** [comment]
I used the GET with the following call:
https://allegro.pl/auth/oauth/authorize?response_type=code&code_challenge_method=plain&redirect_uri=[uri]&client_id=[client_id]&code_challenge=[code]


This works fine in Browser, but not in code.

Another problem of mine is, that i tried to authenticate too often, and has been blocked by the API. Could you unblock me please.

**Comment by MaciejFrackowiak** [comment]
We do not know your application and how it works - we are unable to say what is wrong, but if it works fine in a browser, you have to check application code to find a source of error.
There is an automatic mechanism which will allow you to get authorization - you have to just stop requests and take some time off.

**Comment by OKschroeter** [comment]
Well another try:
I logged on at the API and get the following Response:

{
	"access_token": "[token]",
	"token_type": "bearer",
	"expires_in": 43199,
	"scope": "allegro:api:orders:read allegro:api:profile:write **allegro:api:sale:offers:write** allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read",
	"allegro_api": true,
	"jti": "[jti]"
}

No i try to add a product, using the acces point: https://api.allegro.pl/sale/product-proposals
The documentation says, the endpoint requires:
bearer-token-for-user (allegro:api:sale:offers:write) 

The response says we have that permission. Why do i get the following response:

403 - Forbidden:

www-authenticate: Bearer error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token.", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"

Am i right, that this error means, that the data i send is not correct?
And if i am, where do i find out, what exactly was wrong?

**Comment by bugproof** [comment]
@OKschroeter I had similar requirements for my application. To be able to process multiple allegro accounts in the background. 

Initially, I wanted to use client credentials code flow but advanced operations are not possible with it, only with device code flow and authorization code flow. 

Authorization code flow requires you to host a web server that can accept requests with a token from allegro when a user authorizes your registered application. The one disadvantage I have with it is that when you authorize your app once you have to logout manually or use incognito mode to log in to another account so if you want your users to easily connect multiple allegro accounts without any workarounds probably device code is your best bet.

Device code flow gives you a link valid for maybe 1 hour that user must click to authorize your app, you can send it over email/sms or return it in your application for the user to click or do a 301 redirect to that link and wait in the background for authorization (spawn a thread or something that waits 1 hour, optionally save device code in your database to resume waiting when your app unexpectedly closes) or use some cloud service like amazon lambda/azure functions to handle these tasks :)

**Comment by MaciejFrackowiak** [comment]
@OKschroeter Error message which you received suggests that your account is not fully activated - please, give me its ID.

**Comment by OKschroeter** [comment]
20a7ab241e824a3898ed35813f8d7a12

**Comment by OKschroeter** [comment]
> 
> 
> @OKschroeter I had similar requirements for my application. To be able to process multiple allegro accounts in the background.
> 
> Initially, I wanted to use client credentials code flow but advanced operations are not possible with it, only with device code flow and authorization code flow. See my issue it's in polish though you have to use a translator: #3900
> 
> Authorization code flow requires you to host a web server that can accept requests with a token from allegro when a user authorizes your registered application. The one disadvantage I have with it is that when you authorize your app once you have to logout manually or use incognito mode to log in to another account so if you want your users to easily connect multiple allegro accounts without any workarounds probably device code is your best bet.
> 
> Device code flow gives you a link valid for maybe 1 hour that user must click to authorize your app, you can send it over email/sms or return it in your application for the user to click or do a 301 redirect to that link and wait in the background for authorization (spawn a thread or something that waits 1 hour, optionally save device code in your database to resume waiting when your app unexpectedly closes - because if it closes and the user confirms you need a way to handle that) or use some cloud service like amazon lambda/azure functions to handle these tasks :) Unlike auth code flow, device flow always shows you the login screen or at least it gives you the ability to switch to another account. This is ideal if you want your app to support multiple user accounts.

Thanks for your help, but unfortunately it won't help me, i think.
Data exchanges with allegro will partly run overnight, when there is no user to get this link.

**Comment by MaciejFrackowiak** [comment]
It is a ClientID, not userID - so please, confirm your userID which you used.

**Comment by OKschroeter** [comment]
Sorry i need to ask, but where do i get the userID? Is that the email, we use to login to allegro?

**Comment by MaciejFrackowiak** [comment]
You can find your userID using a resource [GET /me](https://developer.allegro.pl/documentation/#operation/meGET). Please, give me a trace-id of your request - I will try to find it in our database.

**Comment by OKschroeter** [comment]
{
    "id": "34948588",
    [...]
}

**Comment by MaciejFrackowiak** [comment]
Thanks for details. I found you requests in database - you used client_credentials authorization to get access to [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) - that resource requires "bearer-token-for-user", so you should use [code](https://developer.allegro.pl/en/auth/#user) or [device](https://developer.allegro.pl/en/auth/#userDeviceFlow) authorization instead.
