### ISSUE TITLE
Problem z odświeżeniem  Access Tokena za pomocą Refresh Tokena   

### ISSUE THREAD

**Issue by krawiec1011** [allegro/allegro-api#4054]
Występuje problem: 
 - [x] ze środowiskiem produkcyjnym
 - [x]  ze środowiskiem testowym

:beetle: **Opis**

Podczas odświerzenia access tokena za pomocą Refresh Tokena   
Otrzymuje błąd: 
"Wrong client for this refresh token"
Przykładowe żądania: 
- 2021-01-09 16:00:07.214
- 2021-01-09 16:00:07.172

**Comment by MaciejFrackowiak** [comment]
Proszę podai id konta, na którym wystąpił problem, pozwoli nam to zweryfikować sytuację.

**Comment by krawiec1011** [comment]
10:00:15
- 3228014
- 35921838
- 36268295

**Comment by MaciejFrackowiak** [comment]
Na podstawie wyłącznie id kont nie widzę żadnych nieprawidłowości. Proszę prześlij szczegóły swoich wywołań poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - w treści zgłoszenia dodaj proszę numer wątku z GitHub - 4054.

**Comment by MaciejFrackowiak** [comment]
Otrzymaliśmy przesłane przez Ciebie dane - dekodując tokeny zauważyłem, że zawierają one zupełnie inne username aniżeli te, które podajesz, stąd komunikat o nieprawidłowym kliencie. Sprawdź proszę dane, które wykorzystujesz do odświeżania tokenów.

**Comment by krawiec1011** [comment]
Zweryfikowałem po Swojej stronie, zamieniłem username. Dzięki, temat  rozwiązany.
