### ISSUE TITLE
Can I get order commissions from the  allegro platform

### ISSUE THREAD

**Issue by jixuming** [allegro/allegro-api#4055]
Can I get order commissions from the  allegro platform? Provide API for order commission and commission field information corresponding to API, thank you

**Comment by MaciejFrackowiak** [comment]
You can retrieve this data using [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries). You can use filters to limit received data. We described this resource in [our tutorial](https://developer.allegro.pl/en/charges/#billing-operations).

**Comment by jixuming** [comment]
I have searched in the  allegro platform, but I did not find the API corresponding to the commission

**Comment by jixuming** [comment]
Can you provide an API to get commission information? Thank you

**Comment by MaciejFrackowiak** [comment]
You can filter GET /billing/billing-entries results with filter "type.id"=SUC (Sales commission) and then compare date from "occurredAt" and "offer.id" fields with "lineItems" section in a resource [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET).

**Comment by jixuming** [comment]
Is the offer.id obtained from the API (Get an order's details) unique for each order? Then enter the unique offer.id into the billing API (Get a list of billing entries) to get the commission for the order？

**Comment by jixuming** [comment]
Question 4059 is the same as question 4055. Question 4055, please help me answer it, thank you

**Comment by MaciejFrackowiak** [comment]
No, offer.id is not unique, it is an offer number. As I wrote before - you should compare date from "occurredAt" field and "offer.id" field in "lineItems" section in a resource GET /order/checkout-forms/{id} with data which you will receive using GET /billing/billing-entries - use filters "offer.id" and "occurredAt.gte" / "occurredAt.lte" to limit result.

**Comment by jixuming** [comment]
OK ,thank you.Will your platform plan to enter the order number to return the order commission?

**Comment by MaciejFrackowiak** [comment]
Yes, we have it on the Allegro API development suggestion list.
