### ISSUE TITLE
Rate limit na GET /sale/products/{id}

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4056]
Jaki jest rate limit na ten zasób? 
Wykonywałem ok. 5 zapytań / sekunde na ten endpoint i dostaje 429 ale tylko na tym endpoincie.
Staram zaaktalizować się eany ale nie mogę, bo 429 przy pobieraniu informacji o produkcie.

**Comment by MaciejFrackowiak** [comment]
Na tym zasobie istnieje tzw. [Leaky bucket](https://developer.allegro.pl/about/#Leaky_Bucket), czyli dodatkowy mechanizm, który ogranicza liczbę zapytań dla danego użytkownika.

**Comment by TomaszSzydlowski-sudo** [comment]
@MaciejFrackowiak To, w jaki sposób szybko mogę uzupełnić parametry produktu w ofercie? Aktualnie, żeby zaktualizować ofertę pobieram sobie aktualne informacje o produkcie i na podstawie danych z produktu aktualizuje parametry. Jest jakiś endpoint, który szybko mi to zrobi? Myślałem nad PATCH /sale/product-offers/{offerId} ale w dokumentacji jest napisane, że  aktualizuje tecdocSpecification i compatibilityList, a nie parametry. Jak wyślę PATCH /sale/product-offers/{offerId} z product.id: null to czy parametry w ofercie zostaną zaktualizowane?

**Comment by MaciejFrackowiak** [comment]
Możesz nadal korzystać z [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct), tylko ogranicz częstotliwość wysyłanych requestów, wówczas nie natrafisz lub znacznie rzadziej na 429. Opisany przez Ciebie sposób wykorzystania metody PATCH nie spowoduje aktualizacji parametrów oferty.

**Comment by TomaszSzydlowski-sudo** [comment]
> Jaki jest limit na ten endpoint?

??

**Comment by MaciejFrackowiak** [comment]
Nie ujawniamy wartości tego limitu, działa on niezależnie od standardowego limitu per ClientID.
