### ISSUE TITLE
Import JSON opisu aukcji

### ISSUE THREAD

**Issue by mgxmajewski** [allegro/allegro-api#4057]
Dzień dobry,  

moim celem jest import opisu z własnej aukcji już istniejącej w allegro w formacie JSON w 
celu edycji i późniejszego wstawienia do szablonu pliku "bulk-import_v3.0_pl.xlsm"*

Aktualnie na ten temat w dokumentacji REST API jest poniższa sugestia:
"Sugerujemy, by pierwszy opis przygotować przez formularz wystawiania. Skorzystaj z wszystkich rodzajów sekcji i opcji formatowania i pobierz ofertę za pomocą GET /sale/offers/{offerId}. W ten sposób najłatwiej dowiesz się jak poprawnie przygotować opis."

1.  pytanie czy nie ma innego sposobu żeby ściągnąć taki szablon? Bo na ten moment musiałbym napisać i autoryzować swoją własną aplikację tylko po to żeby ściągnąć jednego JSON'a. (chyba że jest jakieś narzędzie/sposób na import?)

2. Ewentualnie czy wystawienie z pliku "bulk-import_v3.0_pl.xlsm"* można dokonać na testowym sanboxie? Jeśli tak to może łatwiej będzie napisać JSON'a z opisem i zobaczyć jak się wyrenderuje. (chyba że jest jakieś narzędzie?)

* szablon pliku pobrany z https://allegro.pl/moje-allegro/sprzedaz/wystaw-z-pliku 

Pozdrawiam serdecznie

**Comment by MaciejFrackowiak** [comment]
W [naszym poradniku](https://developer.allegro.pl/sale/) znajdziesz przykładowe requesty, tylko musisz mieć na uwadze, że dla każdej kategorii występują inne obowiązkowe paremetry, dlatego zacytowane przez Ciebie rozwiązanie jest najbardziej optymalne - wystaw ofertę przez WWW, a następnie pobierz jej szczegóły korzystając z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Zasady dotyczące opisu oferty szczegółowo opisaliśmy [tu](https://developer.allegro.pl/sale/#5-opis-oferty). Wystawianie ofert z pliku nie jest bezpośrednio powiązane z wykorzystaniem zasobów API, dlatego w przypadku wątpliwości proszę skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by mgxmajewski** [comment]
Dziękuję za szybką odpowiedź. Żeby skorzystać z  GET /sale/offers/{offerId} muszę mieć zarejestrowaną aplikację (bo nie da się skorzystać z api bez autoryzacji). Nie mam takiej aplikacji - rozumiem że jakbym ją napisał z użyciem OAuth i miał w niej tylko jedną metodę GET /sale/offers/{offerId}  to mógłbym sobie je ściągać? Bo nie wiem jakie są wymagania żeby się zarejestrować.
(np. czy musi być domena w ssl) 

Pozdrawiam serdecznie

**Comment by TomaszSzydlowski-sudo** [comment]
@mgxmajewski Na https://apps.developer.allegro.pl/ rejestrujesz aplikacje typu DEVICE. Dostajesz client_id + client_secret.
Robisz POST https://allegro.pl/auth/oauth/device
Authorization: Basic <base64encode(<client_id>:<client_secret>)>
Content-Type: application/x-www-form-urlencoded
W danych formularza:
client_id=<client_id>
Przykład curla:
```
curl 
--request POST \
--url https://allegro.pl/auth/oauth/device \
--header 'Authorization: Basic <base64encode(<client_id>:<client_secret>)>' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data client_id=<client_id>
```
Dostajesz w odpowiedzi device_code i link do powiązania apki. 
Jak wejdziesz w link i klikniesz żeby powiązać aplikację robisz request
POST https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=<Twój device_code>
Authorization: Basic <base64encode(<client_id>:<client_secret>)>

Dostajesz w odpowiedzi access_token + refresh_token

Później robisz 
GET https://api.allegro.pl/sale/offers/{id}
Authorization: Bearer <access_token>
Accept: application/vnd.allegro.public.v1+json
Dostajesz w odpowiedzi JSON'a z całą Twoją ofertą.

Mam nadzieję że jakoś pomogłem

**Comment by mgxmajewski** [comment]
Tak, dziękuję bardzo, jeśli można to załatwić z konsoli i rejestracja jest tylko nadaniem danych dostępowych

**Comment by mgxmajewski** [comment]
Z mojej strony ticket do zamknięcia. ]

Dziękuję i pozrdrawiam
