### ISSUE TITLE
Pytanie o metody dostaw i filtrowanie publicznego listingu

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#4058]
Witam,
W dokumentacji jest metoda pozwalająca pobrać wszystkie metody dostaw: /sale/delivery-methods dla publicznego tokenu.
Podczas przeglądania listingu ofert /offers/listing chciałbym te metody wykorzystać do filtrowania. Czy mogę to zrobić? Opcje filtrów, które zwracane są w response z offers listingu są bardzo ubogie.

**Comment by MaciejFrackowiak** [comment]
Nie, metod dostawy z /sale/delivery-methods nie można wykorzystać podczas przeglądania zasobów listingu. Na listingu występują zagregowane metody dostawy w postaci multifiltra "deliveryMethod" - zwraca on tylko grupy typów dostaw np. kurier, paczkomaty Inpost, itd.

**Comment by artzie92** [comment]
To w jakim celu tamta metoda ma opcje pobierania po publicznym tokenie? Gdzie ja te zasoby mogę wykorzystać nie będąc autoryzowany jako użytkownik. Filtry z listingu są bardzo ubogie :)

**Comment by MaciejFrackowiak** [comment]
Metody dostawy są jednakowe dla każdego sprzedającego w serwisie, dopiero cennik dostawy jest przypisany per użytkownik, stąd nie było konieczności zawężania dostępu do nich tylko dla bearer-token-for-user.
Odnośnie filtrów - filtry dostępne w API w tym zakresie są odzwierciedleniem tego co jest dostępne w serwisie WWW.

**Comment by artzie92** [comment]
OK, dzięki.
