### ISSUE TITLE
czas wysyłki przez restapi

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#406]
Witam, czy jest możliwość zmiany czasu wysyłki przez rest api jednorazowo dla kilku ofert?

**Comment by LukaszKorek** [comment]
Możesz skorzystać z naszych zasobów do wystawiania ofert - pole "handling time". Szczegóły odnajdziesz w naszym poradniku https://developer.allegro.pl/sale/ . Możesz też wykonać taką operację za pomocą zakładki Moje oferty ](https://allegro.pl/seller-offers)

**Comment by dlis2010** [comment]
witam ponownie, zmiana czasy wysyłki dla znacznej ilości ofert nawet grupując po 1000 ofert i wykorzystując zakładkę moje oferty jest czasochłonna. Edycja przez restapi każdej oferty osobno również odpada.

Liczyłem na wykorzystanie /sale/offer-modification-commands/ do zmiany czasu wysyłki, gdzieś kiedyś widziałem jakiś przykład z handlingTime... ale w takim razie coś źle widziałem ;)

Podsumowując: /sale/offer-modification-commands/ pozwala na zmianę shippingRates natomiast o zmianie handlingTime mogę zapomnieć?

**Comment by LukaszKorek** [comment]
Jeśli wystawiasz ponownie ofertę, to tworzysz nową ofertę (nowy numer oferty), dlatego traktujemy ją jako nową także dla opłat. Więcej na ten temat znajdziesz w artykule https://allegro.pl/pomoc/faq/oplata-za-utrzymanie-oferty-lDka5qo0nUV

**Comment by LukaszKorek** [comment]
HandlingTime to odpowiednik czasu wysyłki z formularza wystawiania, przepraszamy za błąd w opisie metody. Może go Pan zmienić za pomocą  /sale/offer-modification-commands/

**Comment by sikorskim** [comment]
Witam, czy ta odpowiedź jest aktualna?
Próbuję zmienić czas wysyłki dla kilku ofert jednocześnie za pomocą /sale/offer-modification-commands/{mojeCommandId} i w odpowiedzi otrzymuję: 
`{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": "/sale/offer-modification-commands/{mojeCommandId}",
            "userMessage": null
        }
    ]
}`

Moje request body:
`{
    "modification":{
    "delivery": {
    "handlingTime": "PDT12H30M5S"
}        
        },
"offerCriteria":[
    {
    "type":"CONTAINS_OFFERS","offers":[{"id":"idOferty0"},{"id":"idOferty1"}
    ]}
    ]}`

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy masowej edycji pola `delivery.handlingTime`. Jego wartość możesz zmienić w pojedynczych ofertach za pomocą:

- [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT), przesylając cały model oferty z wyedytowaną wartością pola;
- [PATCH /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation/#operation/editProductOffers), przesyłając tylko interesującą Cię sekcję, czyli w tym przypadku obiekt `delivery`:
