### ISSUE TITLE
nagły brak możliwości połączenia z API

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#4060]
Dzień dobry,
nie mogę połączyć się z api. W sobote było wszystko ok, a teraz mam błąd uwierzytelniania/złego przekierowania. 
wywołując link:

> https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=moj_kod&redirect_uri=moj_link

Otrzymuje kod do API. wywołując połączenie z 

> https://allegro.pl/auth/oauth/token?grant_type=authorization_code

posługując się kodem otrzymanym w poprzednim kroku otrzymuje błąd o złym przekierowaniu z czego może być to spowodowane? jeżeli potrzeba jakiś informacji to mówcie to dodam.

> Redirect URI mismatch.

**Comment by Radeq** [comment]
@lukaszkrakowiak , czy przekazujesz SCOPE? Od poniedziałku jest obowiązkowy, szczegóły https://github.com/allegro/allegro-api/issues/4022

**Comment by MaciejFrackowiak** [comment]
@lukaszkrakowiak Sprawdź proszę dokładnie adres przekierowania - komunikat "Redirect URI mismatch." mówi, że adres nie jest 1:1 z tym adresem, który widnieje na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/).

**Comment by lukaszkrakowiak** [comment]
@MaciejFrackowiak  jest taki sam, nawet go zmieniałem wiele razy. Problemy zaczęły się jak dodałem kolejną strone do aplikacji o tresci "moj_adres/adres" i wtedy przestało działać. Nie korzystam ze SCOPE bo nie wiedziałem o tym(dopiero zaczynam z integracjami waszymi). Jak podepne scope to powinno pójść

**Comment by hahyes** [comment]
> @lukaszkrakowiak , czy przekazujesz SCOPE? Od poniedziałku jest obowiązkowy, szczegóły #4022

>Jeżeli nie podejmiesz żadnych kroków, to twoja aplikacja będzie za każdym razem autoryzować się z pełną listą scope’ów.

Innymi słowy, scope nie jest obowiązkowy, jeżeli nie masz potrzeby ograniczania możliwości zautoryzowanej aplikacji.

**Comment by lukaszkrakowiak** [comment]
@MaciejFrackowiak @hahyes @vi4m 
Problem rozzwiązany. po prostu routing na /link nie działał, ale na /link.php już działa, także tak niech zostanie. Dzięki wam, zamykam.
