### ISSUE TITLE
Forma prawna firmy - dane do faktury

### ISSUE THREAD

**Issue by prdevox** [allegro/allegro-api#4061]
Dzień dobry,

Pytanie dotyczy zasobu **"/order/checkout-forms/{id}"** lub pokrewnych, z których można otrzymać informację o danych do wystawienia faktury za zamówienie.

Klient zaznaczył, że chce otrzymać fakturę i jest "firmą". W odpowiedzi otrzymujemy informację, że "invoice.required: **true**" oraz "invoice.company.taxId **!= null**"

Czy w strukturze odpowiedzi z REST API **"invoice.company"** możliwe byłoby dodanie informacji o formie prawnej firmy np. czy jest to jednoosobowa działalność gospodarcza itd.

**Comment by MaciejFrackowiak** [comment]
W API zwracamy dane, które stricte dostępne są na WWW - tam również nie są przekazywane dane o formie prawnej firmy. Generalnie, podając dane do faktury podmiot nie jest zobowiązany do przedstawienia swojej formy prawnej, dlatego jako Allegro nie wymuszamy tego.
