### ISSUE TITLE
pobranie oceny z zamówienia po ID zamówienia

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#4063]
Dzień dobry,
Czy jest jakaś funkcja odpowiedzialna za pobranie oceny poprzez podanie ID zamówienia? nie chcę co chwile literować wszystkich ocen, a potrzebuje aktualizować widok o to czy została wystawiona ocena czy nie.

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy dostępnego takiego zasobu.

**Comment by lukaszkrakowiak** [comment]
planujecie dodać? bo to jednak fajny dodatek :) no cóż. trzeba będzie inaczej sobie radzić

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy tego na liście zmian.
