### ISSUE TITLE
Notoryczny INTERNAL_SERVER_ERROR przy aktualizacji wybranych ofert

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#4064]
Proszę o pomoc w zdiagnozowaniu problemu z kilkoma ofertami. Nie mam pomysłu jak to ruszyć z powodu braku informacji o specyfice błędu.
Podaję trace-id dla requestów na zasób `PUT /sale/offers/...`, każdy trace-id dla osobnej oferty:
```
53f643e245d85d99
d1861c0ed64b92d
8afb88e32748bbde
85d57f377278c536
6bc05effecef891a
1910af2d5402393f
6744ea2fcaf1bbd6
90680a6dd35f27f0
7c84d00fce76df85
34feec2fe96e120
```

Dzięki

**Comment by MaciejFrackowiak** [comment]
Opisany przez Ciebie problem konsultuję z odpowiednim zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Problem, który napotkałeś związany był z chwilowym błędnym działaniem usługi. Przepraszam za niedogodności.

**Comment by mindc** [comment]
@MaciejFrackowiak 
Niestety, cały czas jest problem z tymi ofertami... podesłać bieżące trace-id?

**Comment by MaciejFrackowiak** [comment]
Tak, poproszę.

**Comment by mindc** [comment]
Załączam:
80f4db95cccaa4fb
4c22c25c78b4a880
32ace6a767384370
7603b1da3a8508e8
2b32e262feb46bad
ae9417115114d5d8
5d2bd9000ac0c9e
adca3efede80ae3
24a6b48fc38555db
add071fba212ac3f
dbdf4d85cd5e6331
83b09a95ff87f76d
978a5c3c99036e72
b7b56fad9953332a

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykłady, weryfikujemy je ponownie.

**Comment by MaciejFrackowiak** [comment]
Dzisiaj wdrożona została poprawka, problem nie powinien już występować.

**Comment by mindc** [comment]
Dzięki, potwierdzam działanie, widzę że wdrożyliście nowy komunikat błędu i wszystko jest teraz jasne.
