### ISSUE TITLE
Batch modyfikacja oferty, szczegóły błędu

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4067]
Skąd wiadomo co dokładnie wywołało błąd podczas batch modyfikacji? https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT

np taskCount zwróci failed: 2, skąd wiadomo przy jakich ofertach wystąpił błąd? np:

```JSON
{
  "id": "123213",
  "taskCount": {
    "failed": 2,
    "success": 2,
    "total": 4
  }
}
```

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z [GET /sale/offer-price-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET), wówczas otrzymasz szczegółową listę operacji uwzględniającą każdą ofertę.
