### ISSUE TITLE
sale/product-proposals return false

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#4068]
Występuje problem: z zasobem REST API ze środowiskiem produkcyjnym

Wysyłam i zwraca mi tylko false.

array
  'name' => string '385/65R22,5 Michelin X-MULTI T Naczepowa'
  'category' => 
    array
      'id' => string '257701'
  'parameters' => 
    array
      'id' => string '11323' 
      'valuesIds' => 
        array 
          0 => string '11323_2' 
  0 => 
    array
      'id' => string '128844' 
      'valuesIds' => 
        array 
          0 => string '128844_1'
  1 => 
    array 
      'id' => string '9300'
      'valuesIds' => 
        array 
          0 => string '9300_14'
  2 => 
    array 
      'id' => string '345' 
      'valuesIds' => 
        array
          0 => string '345_73'
  3 => 
    array
      'id' => string '344' 
      'valuesIds' => 
        array
          0 => string '344_256' 
  4 => 
    array
      'id' => string '127088' 
      'valuesIds' => 
        array 
          0 => string '127094_14'
  5 => 
    array
      'id' => string '225693'
      'name' => string 'EAN'
      'valuesLabels' => 
        array 
          0 => string '5900000970912'
  'images' => 
    array
      0 => 
        array
          'url' => string 'https://a.allegroimg.com/original/11cf69/706eafb14c5eb45c2f5b71b38fbd'

**Comment by MaciejFrackowiak** [comment]
Widze, że ostatecznie udało się Tobie zgłosić pomyślnie propozycję produktu.

**Comment by KJtTGHAK** [comment]
cały czas dostaję w odpowiedzi tylko FALSE

**Comment by MaciejFrackowiak** [comment]
Proszę sprawdź działanie swojej aplikacji, ponieważ widzę, że z podanymi danymi został dodany produkt o id=728785e3-7df6-44eb-a18c-fe48da5881a7.

**Comment by KJtTGHAK** [comment]
Możliwe że dodałem to poprzez stronę Allegro.
Próbowałem zrobić kolejne  i dostaję errors:
array (size=1)
  'errors' => 
    array (size=1)
      0 => 
        array (size=5)
          'code' => string 'ERROR' (length=5)
          'message' => string 'An error has occurred' (length=21)
          'details' => null
          'path' => string '/sale/product-proposals' (length=23)
          'userMessage' => null


array (size=10)
  'name' => string '315/80R22,5 Bridgestone R-DRIVE 002 Napędowa' (length=45)
  'category' => 
    array (size=1)
      'id' => string '257701' (length=6)
  'parameters' => 
    array (size=2)
      'id' => string '11323' (length=5)
      'valuesIds' => 
        array (size=1)
          0 => string '11323_2' (length=7)
  0 => 
    array (size=2)
      'id' => string '128844' (length=6)
      'valuesIds' => 
        array (size=1)
          0 => string '128844_1' (length=8)
  1 => 
    array (size=2)
      'id' => string '9300' (length=4)
      'valuesIds' => 
        array (size=1)
          0 => string '9300_2' (length=6)
  2 => 
    array (size=2)
      'id' => string '345' (length=3)
      'valuesIds' => 
        array (size=1)
          0 => string '345_22' (length=6)
  3 => 
    array (size=2)
      'id' => string '344' (length=3)
      'valuesIds' => 
        array (size=1)
          0 => string '344_2048' (length=8)
  4 => 
    array (size=2)
      'id' => string '127088' (length=6)
      'valuesIds' => 
        array (size=1)
          0 => string '127094_14' (length=9)
  5 => 
    array (size=3)
      'id' => string '225693' (length=6)
      'name' => string 'EAN' (length=3)
      'valuesLabels' => 
        array (size=1)
          0 => string '5900000968445' (length=13)
  'images' => 
    array (size=1)
      0 => 
        array (size=1)
          'url' => string 'https://a.allegroimg.com/original/11386d/4a524b734f0e84e05d52edb1dd1a' (length=69)

**Comment by MaciejFrackowiak** [comment]
W swoim payloadzie numerujesz kolejne parametry 0, 1, 2, 3, etc. co jest błędem i dlatego zwracamy błąd 400. Musisz przekazać id parametru i jego wartość - proces opisaliśmy w [poradniku](https://developer.allegro.pl/productization/#6-jak-doda%c4%87-produkt).

**Comment by KJtTGHAK** [comment]
Wyżej wkleiłem dane z decodowane. Poniżej dane jakie wysyłam. Próba wysłania danych zgodnie z opisem, kończy się errorem
  'errors' => 
    array (size=1)
      0 => 
        array (size=5)
          'code' => string 'ParameterException.InvalidParameterDtoException' (length=47)
          'message' => string 'An error has occurred' (length=21)
          'details' => null
          'path' => null
          'userMessage' => string 'Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.' (length=69)

{
    "name": "315\/80R22,5 Bridgestone R-DRIVE 002 Nap\u0119dowa",
    "category": {
        "id": "257701"
    },
    "parameters": [{
            "id": "11323",
            "valuesIds": ["11323_2"]
        }, {
            "id": "128844",
            "valuesIds": ["128844_1"]
        }, {
            "id": "9300",
            "valuesIds": ["9300_2"]
        }, {
            "id": "345",
            "valuesIds": ["345_22"]
        }, {
            "id": "344",
            "valuesIds": ["344_2048"]
        }, {
            "id": "127088",
            "valuesIds": ["127094_14"]
        }, {
            "id": "225693",
            "name": "EAN",
            "valuesLabels": ["5900000968445"]
        }],
    "images": [{
            "url": "https:\/\/a.allegroimg.com\/original\/11386d\/4a524b734f0e84e05d52edb1dd1a"
        }]
}

**Comment by KJtTGHAK** [comment]
temat rozwiązany EAN przekazać trzeba jako values a nie valuesLabels
