### ISSUE TITLE
Rest-API request throttling

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#407]
Cześć,
czy wasze REST-API ogranicza ilość zapytań w czasie?
Wywołuje wielowątkowo zmiany cen przez zasób /offers/{offerId}/change-price-commands/{commandId}.
Dla pojedynczego wątku czas odpowiedzi jest < 1 s. 
Dla 50 wątków wydłuża się do 18 s co daje wzrost wydajności tylko około 2.7 raza.
Aktualnie w kolejce mam około 500 tyś zmian cen. 
Z taką wydajnością jak teraz zajmie to około 2 dni :/

pozdrawiam

**Comment by kfijalko** [comment]
U mnie w jednym watku zajmuje 1,1s na ofertę.
Podzieliłem na grupy:
- najpierw wzrosty ceny > 20%
- wzrosty > 10%
- wzrosty > 5%
- wzrost > 0
- spadki ceny od najniższego

Mam 60k do aktualizacji.
Bedzie szło cały dzień, ale najważniejsze zmiany zrobi na początku.

**Comment by rtnet-pl** [comment]
Dokładnie tyle to trwa (ok. 1-1.5s).
Natomiast przy uruchamianiu w wielu wątkach raczej nie ma takiego problemu jak u Ciebie, podejrzewam wąskie gardło w innym miejscu. Uruchamiasz to na windowsie?

**Comment by sis6326r** [comment]
Raczej nie ma czy na pewno nie ma?:) Inne metody rest api allegro śmigają szybko bez problemu w wielu wątkach więc nie sądzę, żeby to była kwestia systemu czy implementacji.

**Comment by rtnet-pl** [comment]
Pytałem o platformę, bo na windows zauważyłem wzrost w wydajności gdy w ramach Twojej aplikacji wyłączysz wykrywanie proxy

**Comment by sis6326r** [comment]
Pytanie nieaktualne, winna była biblioteka RestSharp

pozdr
