### ISSUE TITLE
Błąd podczas wyszukiwania produktu BPZ-BM-003 (5902048045805)

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#4070]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wyszukiwaniu przez zasób `GET /sale/products` w/w produktu za pomocą: 
 - frazy `BPZ-BM-003` (trace-id: 6f6c8d2d951cf957) 
 - EAN `5902048045805` (trace-id: 39bff2f0a14ef153)

Otrzymuję błąd:
> HTTP 404
TecdocSpecificationNotFound
Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.

Jednakże produkt ten istnieje pod kodem `a2194797-f025-4608-9b72-ad9b77f990c4`
Numer katalogowy części oraz EAN tego produktu pokrywają się danymi podawanymi przy wyszukiwaniu.

Problemem na pewno nie jest błędny request.
Mogę wyszukać produkt `53f508f7-135c-4c35-9fb2-917195aeeb58` za pomocą: 
- frazy `HZP-FT-005` (trace-id: 4a1aa52ebbc271ca) 
- EAN `5902048085115` (trace-id: 27912b3a13ead1ed) - tego parametru nie ma nawet w danych produktu

**Comment by MaciejFrackowiak** [comment]
Potwierdzam Twoje spostrzeżenie, problem przekazałem do zespołu odpowiedzialnego za funkcjonowanie zasobu.

**Comment by MaciejFrackowiak** [comment]
Poprawiliśmy działanie wyszukiwarki, obecnie zarówno po EAN, jak i frazie znajdziesz wskazany przedmiot. Przepraszam za utrudnienia.

**Comment by mindc** [comment]
Super, potwierdzam poprawienie wyszukiwarki. 
Dzięki.
