### ISSUE TITLE
Problem z aktywacją oferty

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4076]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, 

Mam problem z aktywacją oferty. Rano wysyłałem request do allegro ze szkicem z oferta o id = 10121760880, chwilę później chciałem go aktywować, ale dla commandId = 3ebb1dbb-da11-48b3-a718-c8edccb9b535 otrzymałem, że dana oferta nie istnieje, została zarchiwizowana lub usunięta, jakie było moje zdziwienie, gdy sekundę potem  https://api.allegro.pl/sale/offers/10121760880 zwraca normalnie informacje jakby aukcja była szkicem. Gdy teraz wchodzę na allegro to rzeczywiście nie ma takiej oferty, a że sytuację obserwuję w logach to niestety nie mam pewności czy aukcja istniała przez sekundę czy co innego się wydarzyło. Dzisiaj zauważyłem więcej takich przypadków - do tej pory wszystko wydawało się działać poprawnie. Teraz dla testu spróbowałem uruchomić to zapytanie jeszcze raz i normalnie szkic się stworzył, a aukcja została aktywowana. Jestem w jakiś sposób sprawdzić co się rano stało, że ta aukcja się nie pojawiła?

**Comment by MaciejFrackowiak** [comment]
Odtworzyłem przebieg wydarzeń:

1) 2021-01-15 09:01:13.409 zleciłeś aktywację oferty
2) 2021-01-15 09:01:31.984 wysłałeś DELETE /sale/offers/{offerId}
3) 2021-01-15 09:01:37.821 nastąpiła próba wykonania komendy z punktu 1 - niestety, draft został chwilę wcześniej usunięty.

Na wykonanie komendy aktywacji mamy do 60 minut (zwyczajowo znacznie szybciej się to dzieje) i w tym przypadku zbyt wcześnie skorzystałeś z DELETE.

**Comment by mrezlik** [comment]
Ok. Dziękuję za odpowiedź. Muszę prześledzić jeszcze u siebie przebieg zdarzeń, bo wydawało mi się, że wszystkie zapytania do allegro loguje i powinienem mieć informacje o tym, że coś zostało usunięte.
