### ISSUE TITLE
PUT https://api.{environment}/sale/offer-variants/{setId}

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4079]
Zgodnie z dokumentacją:
Use this resource to create variant set.
oraz możliwe odpowiedzi: 200, 401, 403, 422

W odpowiedzi dostaję 404. Czyli nie tworzy wariantu?

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spostrzeżenie - [PUT /sale/offer-variants/{setId}](https://developer.allegro.pl/documentation/#operation/updateVariantSet) to zasób do edycji wariantów - oczywiście poprawimy opis. Jednocześnie zgłosiłem już do odpowiedniego zespołu dodanie informacji o błędzie 404.

**Comment by kfijalko** [comment]
Aktualizacja dokumentacji to jedno. Do tej pory używałem tej metody do tworzenia wariantów z własnym id i "nagle" przestało działać. Proszę zwrócić uwagę programistom, żeby nie robili takich niespodzianek. Teraz już przesiadłem się na POST.
