### ISSUE TITLE
REST API pobranie już trwających aukcji

### ISSUE THREAD

**Issue by piegus** [allegro/allegro-api#408]
Czy jest mozliość pobrania już trwających aukcji przy pomocy rest API w nowej strukturze?
Załóżmy że mamy aukcje stworzone przez WebApi.
 Czy jest mozliwość pobrania tych aukcji przy pomocy REST API?
Pozoliło by mi to na mniej drastyczną migracje aplikacji  z WebAPI do REST-API

**Comment by KrzysztofLukanowski** [comment]
Tak, możesz pobrać oferty, które wystawiłeś na danym koncie. Skorzystaj w tym celu z [nowych zasobów do list ofert](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/).
