### ISSUE TITLE
Aktualizowanie ilości na podstawie stanów magazynowych Comarch Optima

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#4081]
Witam.

Napisałem usługę, która w niestandardowy sposób zlicza ilość dostępną towarów i aktualizuje tą ilość na Allegro. Problem polega na tym, że tych aukcji jest bardzo dużo oraz klient ma kilka kont (sklepów). Usługa nie wyrabia. Kolejność wykonywania:

1. Pobieram ofertę `GET /sale/offers/{offerId}` 
2. Przeliczam ilość, wstawiam do obiektu i wywołuje `PUT /sale/offers/{offerId}` 
3. Jeśli stan jest 0 to dopisuje do listy i deaktywuje `PUT /sale/offer-publication-commands/{commandId}`
4. Na końcu sprawdzam czy są aukcje z ilością większą od 0 i statusem ENDED i je aktywuje `PUT /sale/offer-publication-commands/{commandId}`

Zauważyłem, że `PUT /sale/offers/{offerId}` zwraca odpowiedź po sekundzie. Wstępnie jest to bardzo dobry wynik ale przy tak dużej ilości aukcji czas wykonania pełnego przebiegu jest bardzo duży. 

**PYTANIA**
1. Czy jest możliwość aktualizacji stanów ofert "w paczkach"? 
2. Czy jest w ogóle jakaś możliwość zoptymalizowania takiej usługi?

**Comment by kfijalko** [comment]
metoda batch'owa do modyfikacji stanów
https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT
jeżeli wykonujesz w jednym wątku i synchronicznie to przy większej liczbie ofert to się nie sprawdzi
musisz zastosować wielowątkowość (np.: kolejki)

**Comment by troncomputers** [comment]
Tak, ale to się tyczy ustawiania tej samej ilość dla wszystkich, a u mnie się tak nie dzieje. Każdy może mieć różne ilości.

**Comment by kfijalko** [comment]
zgadza się, jedyna metoda na zmniejszenie liczby requestów to pogrupowanie po ilości

**Comment by troncomputers** [comment]
Też o tym pomyślałem ale wydaje mi się, że wariacja ilościowa jest tak szeroka, że prawdopodobieństwo tej samej ilości jest bardzo małe mimo iż aukcji jest bardzo dużo co spowoduje, że będę aktualizował pojedyncze sztuki.

**Comment by kfijalko** [comment]
ja mam kilkadziesiąt tysięcy requestów i działam na kolejkach (php: laravel + redis)
bez problemu daje rade

**Comment by kfijalko** [comment]
jak najbardziej daje rade,
ja mam aktualizację stanów co 2 godziny, wysyłam i "zapominam" (sprawdzenie wykonania wykonuje inne zadanie)
nie wysyłam tylko towarów, które mają 1 szt (tak samo kończę oferty, które mają 1 szt) - tu miałem braki magazynowe, jak się sprzedało w innym kanale

**Comment by kfijalko** [comment]
w kolejkach mam 15 workerów

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniał @kfijalko - do zmiany liczby sztuk w wielu ofertach jednocześnie możesz skorzystać z [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT). Nie udostępniamy innego zasobu pozwalającego na taką modyfikację.

**Comment by troncomputers** [comment]
Dzięki za sugestie. Spróbuję tą opcje. Zawsze to parę minut mniej.
