### ISSUE TITLE
Łączenie produktów i ilość znaków w polu tytul z parametrów

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#4082]
Witam,
Zauważyliśmy pewną nieścisłość w powiązywaniu ofert z produktami Allegro.

Tworzymy produkt przez API, mamy łącznie 3 pola tytułu:
1. Tytuł oferty
2. Tytuł w parametrach
3. Tytuł alternatywny w parametrach

Po wystawieniu oferty i edycji jej na portalu Allegro widać następujące ograniczenie znaków:
1. 50 znaków
2. 150 znaków
3. 150 znaków

Przy łączeniu produktów poprzez panel Allegro, za pośrednictwem szybkiego łączenie "Łączysz z produktem 1 z 60 ofert":
https://allegro.pl/moje-allegro/sprzedaz/moje-oferty?hasProduct=false&productizationRequired=true&categoryId=XXXXXXXXXXXXXX
zostawiając tytuły jak są tj. zapisując tytuł z parametrów z ilością znaków "ponad 50" wyskakuje na samym końcu procesu 60 z 60 błąd że niektóre oferty przekraczają dozwoloną ilość znaków.

Sugeruje to, że jest błąd i tytuł w parametrach powinien mieć 50 znaków zamiast 150 znaków, albo w procesie łączenia produktu niepotrzebnie wymuszacie krótszą ilość znaków tj. do 50 (to pole jest pobierane bezposrednio z tytuł w parametrach).

Prosimy również o wyjaśnienie jakie dokładnie jest zadanie pola:
-Tytuł w parametrach
-Tytuł alternatywny w parametrach

Z tego co zrozumieliśmy tytuł alternatywny będzie wykorzystywany w wyszukiwarce Allegro, jako dodatkowe frazy do szukania.
Natomiast tytuł w parametrach jest używany przez was do tworzenia produktu w bazie Allegro.

**Comment by unkn0wn0** [comment]
Jakikolwiek produkt np. w kategorii 
Kultura i rozrywka / Gry / Gry na konsole / Microsoft Xbox One /
Kultura i rozrywka / Gry /  Komputerowe PC /

Problem raczej będzie z każdym produktem jaki macie na Allegro, po prostu pozwalacie na dodanie w tytule parametru nazwy do 150 znaków, a następnie w samej aplikacji do "parowania produktów z wami" wymagacie 50 znaków.

**Comment by AureliuszBrussy** [comment]
Pierwsza wartość o którym piszesz to nazwa oferty (**name**) - służy ona do tytułowania oferty i z taką nazwą oferta po wystawieniu pojawi się na liście ofert. Maksymalna długość tego pola to 50 znaków. 

Z kolei "**tytuł**" oraz "**tytuł alternatywny**" w parametrach odnosi się do tytułu wystawianego produktu. Wartość pola "tytuł" w parametrach może różnić się od nazwy oferty. W parametrze "tytuł" należy podać dokładny tytuł sprzedawanego produktu. Wartość ta nie ma wpływu na nazwę oferty. 

Nazwa utworzonego produktu może mieć większą liczbę znaków, niż dozwolona długość nazwy oferty.

**Comment by unkn0wn0** [comment]
Nie rozumiemy różnicy pomiędzy tytuł a tytuł alternatywny, po co tworzyć dwa odrębne pola skoro jest to to samo.
Domyślamy się, że chodzi o przedłuzoną nazwę.
Chodziło nam o rzetelną informację gdzie konkretnie te pola wykorzystujecie bo to co Pan napisał już wiedzieliśmy sami.
np. które z pół jest wykorzystywane jako dodatkowe frazy w wyszukiwarce Allegro (jak wiadomo tytuł oferty jest ograniczony), lub podobne miejsca jak to z którego pobieracie informacje do swojej własnej bazy produktów.

Proszę w takim razie o informację dlaczego do łączenia produktów wymagacie 50 znaków, które są pobierane automatycznie z pola tytuł, skoro wcześniej pozwalacie na tworzenie do 150 znaków.

Czy produkty w bazie Allegro mają mieć 50 czy może 150 znaków.

**Comment by AureliuszBrussy** [comment]
Niektóre produkty mogą posiadać tytuł alternatywny, dlatego umożliwiamy wprowadzenie takiej wartości w parametrze oferty. Parametr ten nie wypływa na wyszukiwanie - jest dodatkową informacją, którą można zawrzeć w ofercie.

Dopuszczalna długość pola "name" (nazwa) w ofercie to 50 znaków, nazwa produktu w naszej bazie produktów nie ma takiego ograniczenia, więc w praktyce - w bazie mogą znajdować się produktu o nazwie dłuższej niż 50 znaków. W związku z tym mogą zdarzyć się sytuacje, gdzie po wybraniu produktu należy zmienić jego nazwę przed wystawieniem oferty, tak aby nie przekroczyła ona dopuszczalnych 50 znaków.

**Comment by unkn0wn0** [comment]
Dane jakie pobieracie przy łączeniu produktów to nie są dane z pola "name". Gdybyście pobierali te dane właśnie z tego miejsca nie byłoby w tej sprawie problemu. "Name" czyli tytuł oferty allegro.

@nazwa produktu w naszej bazie produktów nie ma takiego ograniczenia, więc w praktyce - w bazie mogą znajdować się produktu o nazwie dłuższej niż 50 znaków

Produkty w waszej bazie mają ograniczenie bo przy łączeniu występuje błąd (bezpośrednio na stronie Allegro na końcu procesu "Łączysz z produktem 60 z 60 ofert", że została przekroczona ilość znaków dla ofert powyżej 50 znaków). 

Dane przy łączeniu produktów pobieracie bezpośrednio z pola "tytuł" znajdującego się w parametrach (pole tytuł według tego co państwo piszą ma ograniczenie 150 znaków, niestety nie jest to 50 znaków i przez to jest wykonywana niepotrzebna dodatkowa praca).

Czyli podsumowując. W jednym miejscu pozwalacie na wprowadzanie 150 znaków, a w innym pobierające dane z tego samego formularza wymagacie 50 znaków.

Rozumiemy, że to nie zostanie zmienione.

**Comment by AureliuszBrussy** [comment]
> Produkty w waszej bazie mają ograniczenie bo przy łączeniu występuje błąd (bezpośrednio na stronie Allegro na końcu procesu "Łączysz z produktem 60 z 60 ofert", że została przekroczona ilość znaków dla ofert powyżej 50 znaków).

Ograniczone do ilości znaków dotyczy pola nazwa w ofercie (name). Produkty nie mają takiego ograniczenia - w naszej bazie mogą istnieć produkty z nazwą dłuższą, niż 50 znaków. Stąd też może zdarzyć się sytuacja, że nazwa produktu jest zbyt długa dla pola nazwa (name) podczas wystawiania oferty. Nie ma to jednak żadnego związku z parametrem tytuł. 

Aktualnie nie planujemy tego zmieniać.
