### ISSUE TITLE
Kategorie i subkategorie API przykład

### ISSUE THREAD

**Issue by olshas** [allegro/allegro-api#4083]
Czy macie przykładową schemę Allegro API kategorii i subkategorii ?

Np. Motoryzacja -> Częsci samochodowe -> Oświetlenie samochodowe, lampy, reflektory -> itd.

**Comment by AureliuszBrussy** [comment]
Nie mamy takich schematów. Skorzystaj z [GET /sale/categories?parent.id={categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) aby pobrać listę kategorii, które należą do podanej kategorii nadrzędnej. Główne kategorie pobierzesz za pomocą żądania **GET /sale/categories**. W ten sposób uzyskasz dostęp do całego drzewka kategorii.
