### ISSUE TITLE
[Sandbox] Potwierdzenie telefonu - SMS nie dociera

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#4084]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy logowaniu mam potwierdzić nr telefonu, potwierdzam i oczekuję na SMS. SMS nie dociera (czekałem 15 minut)
Prośba o poprawę. Moge oczywiście pominąć :)

**Comment by AureliuszBrussy** [comment]
W przypadku Sandboxa - nie wyślemy kodu SMS. Wprowadź kod: 1234.
