### ISSUE TITLE
Parametry zależne

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#4087]
Witam,
Czy macie jakąs listę kategorii gdzie można przetestować parametry zależne na sandbox między innymi Markę i Model?

Pozdrawiam
Marcin Butlak

**Comment by AureliuszBrussy** [comment]
Warunkową obowiązkowość możesz przetestować np. w kategoriach 121724, 124887, 13592 i 19630, na przykładzie parametrów "Stan" i " ISBN". Aktualna listy kategorii, w których wprowadzone są zależności obowiązkowe znajdziesz [tutaj](https://assets.allegrostatic.com/popart-attachments/att-c7b9564d-df1a-47a0-bf7c-ad305a158710) i [tutaj](https://assets.allegrostatic.com/popart-attachments/att-6455fcd6-2a08-4252-be72-947c27f3079a).

**Comment by makerlabs** [comment]
Niestety lista kategorii nie uwzględnia parametrów, które posiadają dodatkową zależność opisana w parametrze dependsOnValueIds oraz displayDependsOnValueIds. Czy możecie wskazać kategorie, które uwzględnia również te parametry.

**Comment by AureliuszBrussy** [comment]
@makerlabs ustalam, czy są na środowisku testowym takie kategorie. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@makerlabs  na Sandboxie możesz przetestować działanie tych parametrów w kategorii id 123428, parametr id 206646.

**Comment by makerlabs** [comment]
@AureliuszBrussy Dziękuje za pomoc :)
