### ISSUE TITLE
Czego nie można edytować w istniejącej ofercie oprócz kategorii?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4088]
Wiemy, że podczas wykonywania edycji na pojedynczej ofercie przez PUT /sale/offers/{offerId} nie można po 12 godzinach od wystawienia zmienić kategorii. Czego jeszcze nie można zmienić w istniejącej (aktywnej lub nieaktywnej) ofercie?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
W [tym artykule](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#) znajdziesz szczegółową listę, gdzie wyjaśniamy, jakie zmiany można dokonać po jej wystawieniu.
