### ISSUE TITLE
400 Bad request on production

### ISSUE THREAD

**Issue by kchakarov** [allegro/allegro-api#4089]
Hi,

When working from my development server I have no problem, but when I switched to production I am getting "400 Bad request" "Your browser sent an invalid request." when calling "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Ao....".
What might be the reason?

**Comment by AureliuszBrussy** [comment]
Did you register your app in [Developer apps](https://apps.developer.allegro.pl/) tab? If so - could you send us your full request via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1)? Please add GitHub thread number - #4089.

**Comment by AureliuszBrussy** [comment]
I received your data via the contact form. 

When calling "https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Ao...." you are passing the wrong value in the Content-Length header ('Content-Length: -1'). Please, try 'Content-Length: 0'.

**Comment by kchakarov** [comment]
Thank you, it was a CURL issue. 
Fixed now.
