### ISSUE TITLE
Jak odróżnić usuniętą ofertę z powodu blokady sprzedaży?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4090]
Czy jest możliwość sprawdzenia przez REST API konkretnej przyczyny zakończenia oferty przez Allegro czyli takich z publication.endedBy = ADMIN?

Do czego mi to potrzebne? W tym momencie znam takie możliwości zamknięcia oferty przez Allegro:
1. Zła miniaturka (niezgodna ze standardem Allegro).
2. Produkt nie może być sprzedawany na platformie Allegro np. z powodów prawnych.
3. Oferta niewznowiona automatycznie przez Allegro ponieważ konto ma blokadę sprzedaży.

I o ten trzeci punkt mi się rozchodzi. Jak mogę odróżnić **ofertę niewznowioną automatycznie przez Allegro z powodu blokady sprzedaży** po to abym po odblokowaniu sprzedaży mógł ją z powrotem wznowić? Ale tak, żeby przez przypadek nie wznowić tych, które zostały usunięte (i również mają publication.endedBy = ADMIN) z powodu np. złej miniaturki.

**Comment by AureliuszBrussy** [comment]
W Allegro API nie zwracamy dokładnego powodu zakończenia oferty w przypadku wartości ADMIN w polu **publication.endedBy**, więc nie rozróżnisz ofert nie wznowionych z powodu blokady sprzedaży. Rozumiem jednak Twoje uzasadnienie - sugestię dopisałem do naszej listy sugestii dot. rozwoju Allegro API.
