### ISSUE TITLE
how can I get the data of“My sales quality”by api?

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#4091]
Dear Allegro partner,

I want to get "my sales quality" data through the interface, which includs ratings from buyers, order fulfillment, customer service, etc. if you don't understand it, please refer to the figure below. In the API material, I didn't find the relevant interface. I hope I can get your help.

I look forward to your reply and wish you a wonderful day.
![image](https://user-images.githubusercontent.com/72594584/105034193-20fc5700-5a94-11eb-998f-bc17579de7b7.png)

**Comment by AureliuszBrussy** [comment]
Currently, we do not provide an endpoint that allows you to get the Sales Quality data via the Allegro API. These data can only be obtained through our website.

**Comment by bingnew** [comment]
I get it. Thank you for your timely reply.
I like your professionalism！
