### ISSUE TITLE
Niedziałająca masowa aktualizacja aukcji

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#4092]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nie działa masowa modyfikacja ofert przez API: https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT . W momencie kiedy wykonuje dany request: 
```
2021-01-19T17:57:18+01:00 INFO (6): 
-------------------------------------
REQUEST:

PUT /sale/offer-modification-commands/1e6adb6e-fdca-4c86-bc3c-c775f0dea23c HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
Authorization: Bearer (...ciach...)
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Content-Length: 172

{"modification":{"payments":{"tax":{"percentage":"23.00"},"invoice":"VAT"}},"offerCriteria":[{"offers":[{"id":"7679239998"},{"id":"7679190240"}],"type":"CONTAINS_OFFERS"}]}
```
Dostaję  w zwrocie:
```
RESPONSE:

HTTP/1.1 201 Created
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: 3f8de53577c376f8
Date: Tue, 19 Jan 2021 16:57:18 GMT
X-content-type-options: nosniff
Content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-length: 92
Connection: close

{"id":"1e6adb6e-fdca-4c86-bc3c-c775f0dea23c","taskCount":{"total":0,"success":0,"failed":0}}
```

Jak widać wartości w taskCount ustawione są na 0 co nie powinno mieć miejsca.

Także późniejsze odpytanie się o rezultat taska zwraca informację że nie ma żadnych danych do przetworzenia:

```
2021-01-19T17:57:18+01:00 INFO (6): 
-------------------------------------
REQUEST:

GET /sale/offer-price-change-commands/1e6adb6e-fdca-4c86-bc3c-c775f0dea23c/tasks HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
Authorization: Bearer (...ciach...)
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

-------------------------------------
RESPONSE:

HTTP/1.1 200 OK
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: de178bef811b1260
Date: Tue, 19 Jan 2021 16:57:18 GMT
X-content-type-options: nosniff
Content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
Content-length: 12
Connection: close

{"tasks":[]}
```

Dodam jeszcze informacje, że request wykonywałem spod użytkownika `kormichu2` oraz że aukcje należą do niego

**Comment by AureliuszBrussy** [comment]
To jest zasób asynchroniczny - oznacza to, że statusu wykonania nie otrzymasz od razu po wykonaniu requestu. To normalne, że w odpowiedzi na żądanie PUT /sale/offer-modification-commands/{commandId} otrzymałeś taką wartość (0). 

Zwrócimy pełną listę zadań po wykonaniu komendy. Aktualnie, jeżeli wykonasz zapytanie GET /sale/offer-price-change-commands/{commandId}/tasks powinieneś otrzymać listę wszystkich tasków.

**Comment by kormichu** [comment]
Wiem że jest to zasób asynchroniczny i dostaje odpowiedź po pewnym czasie na zasobie GET, ale jak już wcześniej napisałem w polu total przy odpowiedzi dostaje 0, a tak nie powinno być. Tak samo sam GET zwraca pustą tablicę z taskami co też nie jest poprawne. Wykonuje ten zasób tak samo jak zasoby odpowiedzialne za:
 - masową aktualizację ceny: https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT
 - masową aktualizację ilości: https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT
 - masową publikację i zakańczanie oferty: https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT

i wszędzie tam dostaję w odpowiedzi dla metody PUT w polu total jakąś wartość większą niż 0 oraz dla metody GET listę zadań

Problem prawdopodobnie pojawia się także na produkcji, ale nie weryfikowałem tego

**Comment by AureliuszBrussy** [comment]
To jest prawidłowe działanie - zwracamy pełną tablicę tasks po ukończeniu wszystkich operacji. Przed ukończeniem tablica będzie pusta. Wartość w polu taskCount.total (0) także jest spodziewana - zwrócimy konkretną sumę (success + failed) po wykonaniu zadania. Wszystko zależy od szybkości wykonania danej komendy.

**Comment by kormichu** [comment]
Hmm, racja. Zamykam
