### ISSUE TITLE
Jak uzyskać parametry danego produtku 

### ISSUE THREAD

**Issue by Itsuke** [allegro/allegro-api#4093]
Przykładowo chciałbym uzyskać parametry dla poniższego laptopa znalozionego przy wykorzystaniu 'https://api.allegro.pl/offers/listing?category.id=77917&phrase=laptop&fallback=false&searchMode=DESCRIPTIONS&price.from=1000&limit=5&sellingMode.format=BUY_NOW'

{'promoted': [{'category': {'id': '77917'},
               'delivery': {'availableForFree': False,
                            'lowestPrice': {'amount': '8.99',
                                            'currency': 'PLN'}},
               'id': '10136773839',
               'images': [{'url': 'https://a.allegroimg.com/original/115a24/58c316bb4507931bafd59fe560cf/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD'},
                          {'url': 'https://a.allegroimg.com/original/11fc5f/8faf83aa45b8825e2ffe1163b959/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Stan-opakowania-oryginalne'},
                          {'url': 'https://a.allegroimg.com/original/11c2c8/fd295c7b46088519ce06678f4a8c/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Model-Vostro-5402'},
                          {'url': 'https://a.allegroimg.com/original/11643b/2f81cbb74452a7cc1d3b6a48cf2e/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Typ-ultrabook'},
                          {'url': 'https://a.allegroimg.com/original/115e63/412a208f49239413d341dac6d8b3/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Kod-producenta-DELL'},
                          {'url': 'https://a.allegroimg.com/original/11961c/861ce2904a2cbab94c09e0bbd2d5/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Przekatna-ekranu-14'},
                          {'url': 'https://a.allegroimg.com/original/11e259/19b0b7504be7a05d91d850f09b52/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Rozdzielczosc-px-1920-x-1080'},
                          {'url': 'https://a.allegroimg.com/original/11fa5c/db834a1c4fd4a434e6e18baee1d5/DELL-Vostro-5402-i5-1135G7-16GB-256GB-FHD-NBD-Powloka-matrycy-matowa'}],
               'name': 'DELL Vostro 5402 i5 1135G7 16GB 256GB FHD NBD',
               'promotion': {'bold': False,
                             'emphasized': True,
                             'highlight': False},
               'seller': {'company': True,
                          'id': '88471523',
                          'login': 'Maxim_Group',
                          'superSeller': True},
               'sellingMode': {'format': 'BUY_NOW',
                               'popularity': 0,
                               'price': {'amount': '4359.00',
                                         'currency': 'PLN'}},
               'stock': {'available': 4, 'unit': 'UNIT'}},
              {'category': {'id': '77917'},
               'delivery': {'availableForFree': False,
                            'lowestPrice': {'amount': '8.99',
                                            'currency': 'PLN'}},

Jak widać powyżej znajdują się tylko parametry ceny, kosztu dostawy itp. Jak mogę uzyskać dla produktu o id 10136773839 jego parametry techniczne ?

**Comment by AureliuszBrussy** [comment]
Takie dane o ofercie możesz pobrać jedynie jako zautoryzowany użytkownik, będący właścicielem danej oferty (endpoint [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)).
