### ISSUE TITLE
Przy próbie autoryzacji API wyświetla się strona "Nie możemy wyświetlić strony"

### ISSUE THREAD

**Issue by DudaMarcin** [allegro/allegro-api#4095]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Staram się autoryzować aplikację WP DESK do WooCommerce jednak gdy wpisuję/klikam link, który powinien dać autoryzację aplikacji, niestety wita mnie taka strona:
![Screenshot](https://user-images.githubusercontent.com/16838723/105197627-18ac2680-5b3d-11eb-9664-be80b462eadc.png)

Już rozmawiałem z WP DESK, mówią, że problem jest po waszej stronie. Też mi się tak wydaje, ponieważ próbowałem zgodnie z dokumentacją autoryzować aplikację i problem był dokładnie ten sam. Nie wiem, czy moje konto nie jest oznaczone jako trędowate, czy coś :P.

Gadałem z supportem allegro i odesłali mnie tutaj, bo też nie wiedzieli, co się dzieje.

Pozdrawiam i czekam na kontakt.👋

**Comment by AureliuszBrussy** [comment]
Adres redirect_uri nie może zawierać znaku "~". Rozumiemy jednak, że w związku z tym nie powinieneś móc podczas rejestracji aplikacji wskazać adresu przekierowania zawierającego ten znak. Wypracujemy rozwiązanie, aby odpowiednio obsłużyć takie przypadki.

**Comment by DudaMarcin** [comment]
No cóż, zawsze coś do przodu. To kombinuje dalej :). Dziękuję za pomoc ;).
