### ISSUE TITLE
Jak sprawdzić status PUT /offers/{offerId}/change-price-commands/{commandId}

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4096]
https://developer.allegro.pl/documentation/#operation/createChangePriceCommandUsingPUT

Jak ponownie sprawdzić status np. QUEUEING?

```json
"output": {
"status": "QUEUEING",
"errors": []
}
```

Czy wystarczy użyć tego samego zasobu co w przypadku batch? https://developer.allegro.pl/documentation/#operation/getGeneralReportUsingGET
https://developer.allegro.pl/documentation/#operation/getTasksUsingGET

**Comment by AureliuszBrussy** [comment]
Endpoint o którym piszesz był pierwszym udostępnionym przez nas zasobem służącym do edycji oferty. Nie udostępniliśmy przy nim opcji sprawdzenia statusu komendy. Zalecamy korzystanie z  [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT), nawet jeżeli zmiana dotyczy pojedynczej oferty.
