### ISSUE TITLE
Jest mozliwosc przetestowania bota, który ma za zadanie dodawać oferty, bez dodawania oferty kupna na allegro?

### ISSUE THREAD

**Issue by miksonek1** [allegro/allegro-api#4097]

**Comment by AureliuszBrussy** [comment]
Testy swojego oprogramowania możesz przeprowadzać na naszym środowisku testowym: [https://allegro.pl.allegrosandbox.pl/](https://allegro.pl.allegrosandbox.pl/).  Więcej o Sandboxie przeczytasz w [naszym poradniku](https://developer.allegro.pl/about/#Sandbox).
