### ISSUE TITLE
Sekcja Pasuje do - jak uzupełnić przez API

### ISSUE THREAD

**Issue by karolADMT** [allegro/allegro-api#4098]
Witam. Chciałbym zapytać o:
 
1.	Czy można importować dopasowania w sekcji „dopasuje do samochodu” poprzez API? Jeśli tak, to czy posługujemy się K-TYPE?
2.	Czy macie Państwo udostępnioną bazę K-TYPE, którą można używać poprzez import API? Na platformie Ebay wygląda to tak, że Ebay udostępnia swoją bazę K-Type (Fahrzeugliste) w pliku excel, a potem podczas importu można te numery K-Type wprowadzić bezpośrednio do pliku CSV w odpowiedniej kolumnie. Szybko, sprawnie i bez pomyłek. I działa to bardzo dobrze.
3. Z jakiej dokładnie bazy danych K-Type Państwo korzystacie - chodzi mi o dokładny rodzaj/wersję. 

Z góry dziękuję za odpowiedź.

**Comment by AureliuszBrussy** [comment]
1. W API Allegro sekcję "Pasuje do" możesz uzupełnić tylko na dwa sposoby - albo podając identyfikatory produktów albo jako zwykły tekst. Skorzystaj z [GET /sale/compatibility-list/supported-categories](https://developer.allegro.pl/documentation/#operation/getCategoriesThatSupportCompatibilityList) aby dowiedzieć się jaki typ "Pasuje do" i na jakich zasadach możesz dodać w konkretnych kategoriach.
2. Aby uzyskać identyfikatory produktów skorzystaj z [GET /sale/compatible-products/groups?type={type}](https://developer.allegro.pl/documentation/#operation/getCompatibleProductsGroups). W [naszym poradniku](https://developer.allegro.pl/compatibility_list/#jak-zarz%c4%85dza%c4%87-sekcj%c4%85-pasuje-do-zintegrowan%c4%85-z-baz%c4%85-pojazd%c3%b3w) opisujemy dokładnie, jak korzystać z tego zasobu. 
3. Korzystamy z TecDoc wersji 2046.
