### ISSUE TITLE
drzewo kategorii

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#4099]
czy jest możliwość pobrania drzewa kategorii (id kategorii) w których ma oferty określony sprzedawca?

**Comment by AureliuszBrussy** [comment]
Możesz uzyskać id kategorii, w których oferty posiada podany sprzedawca używając [GET /offers/listing?seller.login={login}](https://developer.allegro.pl/documentation/#operation/getListing). Znajdziesz te informacje w odpowiedzi, w obiekcie **categories**.

**Comment by speedygopl** [comment]
widzę, że dostaję tylko główne kategorie, a chciałem otrzymać wszystkie podkategorie

**Comment by speedygopl** [comment]
chodzi o to, że chcę uzyskać numery id kategorii typu "pozostałe"

**Comment by AureliuszBrussy** [comment]
Dodając do swojego żądania parametr **category.id** (czyli GET /offers/listing?seller.login={login}&category.id={categoryId}) otrzymasz informacje o kolejnych subkategoriach.
