### ISSUE TITLE
ERR_STANDARDIZED_DESCRIPTION_INCORRECT

### ISSUE THREAD

**Issue by krawczyk12** [allegro/allegro-api#41]
Próbuję wystawić ofertę z nowym opisem.

Wysyłam request:
 
$client->doNewAuctionExt($session['session-handle-part'], $fields, 0, $nr,
    array('item-template-option'=>0, 'item-template-name'=>''), '', '', $rules);  
 
Wszystkie zmienne ($client, $session, $rules, ...) są w porządku, bo ze starym opisem wszystko jest OK.
 
$fields jest tablicą, zawierającą poszczególne FIDy.
 
Nowy opis jest zadany w ten sposób:
 
$fields[] = array('fid'=>341,'fvalue-string'=>$ndes,  'fvalue-int'=>0,
  'fvalue-float' => 0, 'fvalue-image' => '', 'fvalue-datetime' => 0, 'fvalue-date' => '',
  'fvalue-range-int' => array('fvalue-range-int-min' => 0,'fvalue-range-int-max' => 0),
  'fvalue-range-float' => array('fvalue-range-float-min' => 0,'fvalue-range-float-max' => 0),
  'fvalue-range-date' => array('fvalue-range-date-min' => 0,'fvalue-range-date-max' => 0));  

gdzie $ndes jest zdefiniowane tak:
 
$ndes = '  
{  "sections": [
    { "items": [{ "type":"TEXT", "content": "\<p>'.$opis.'\</p>" }] }  
]}';                          
 
Odpowiedź jest następująca:
 
Fatal error: Uncaught SoapFault exception: [ERR_STANDARDIZED_DESCRIPTION_INCORRECT] description musi byÄ podane in /allegro/allen.php:386 Stack trace: #0 /allegro/allen.php(386): SoapClient->__call('doNewAuctionExt', Array) #1 /allegro/allen.php(386): SoapClient->doNewAuctionExt('d91d9a21a0d464c...', Array, 0, '57548', Array, '', '', Array) #2 {main} thrown in /allegro/allen.php on line 386

Co robię źle?
 
Z góry dziękuję - Jan Krawczyk

**Comment by KrzysztofLukanowski** [comment]
Cześć,

z tego co widzę, nie korzystasz z ![CDATA. W takim przypadku pamiętaj proszę o encjach, dotyczy to również znaczników paragrafu.

**Comment by krawczyk12** [comment]
Jak użyć CDATA?
Próbuję

$fields[] = array('fid'=>341,'fvalue-string'=> \<![CDATA[$ndes]]\>,                           // linia 249
         'fvalue-int'=>0, 
         'fvalue-float' => 0, 'fvalue-image' => '', 'fvalue-datetime' => 0, 'fvalue-date' => '',
         'fvalue-range-int' => array('fvalue-range-int-min' => 0,'fvalue-range-int-max' => 0),
         'fvalue-range-float' => array('fvalue-range-float-min' => 0,'fvalue-range-float-max' => 0),
         'fvalue-range-date' => array('fvalue-range-date-min' => 0,'fvalue-range-date-max' => 0));  

i dostaję
Parse error: syntax error, unexpected '<' in /allegro/parau.php on line 249

Przy próbie
$fields[] = array('fid'=>341,'fvalue-string'=> '\<![CDATA[$ndes]]\>',        
  ....             
znowu ERR_STANDARDIZED_DESCRIPTION_INCORRECT.

**Comment by KrzysztofLukanowski** [comment]
W celu weryfikacji podeślij proszę ostateczny kształt request w formacie xml, jaki zostaje przesłany do Allegro.

**Comment by krawczyk12** [comment]
Nie bardzo wiem, jak w formacie xml.
Używam php i odpowiedni element tablicy $fields, wydrukowany przez print_r($fields[19]), bezpośrednio przed wysłaniem wygląda tak:
Array
(
    [fid] => 341
    [fvalue-string] =>   
    {  "sections": [
                { "items": [{ "type":"TEXT", "content": "&amp;lt;h1&amp;gt;Opis&amp;lt;/h1&amp;gt;" }] }   
        ]}
    [fvalue-int] => 0
    [fvalue-float] => 0
    [fvalue-image] => 
    [fvalue-datetime] => 0
    [fvalue-date] => 
    [fvalue-range-int] => Array
        (
            [fvalue-range-int-min] => 0
            [fvalue-range-int-max] => 0
        )
    [fvalue-range-float] => Array
        (
            [fvalue-range-float-min] => 0
            [fvalue-range-float-max] => 0
        )
    [fvalue-range-date] => Array
        (
            [fvalue-range-date-min] => 0
            [fvalue-range-date-max] => 0
        )
)

**Comment by KrzysztofLukanowski** [comment]
Chciałbym poznać dokładną zawartość FID 341, co się kryje pod tymi zmiennymi. XMLe w php możesz wyciągnąć funkcjami:

http://php.net/manual/en/soapclient.getlastrequest.php
http://php.net/manual/en/soapclient.getlastresponse.php

**Comment by abcompl** [comment]
Podepnę się bo też dzisiaj walczę z tym cały dzień.

taka zawartość zmiennej FID 341 działa:

[fvalue-string] => {"sections":[
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_19"}]},
				{"items":[{"type":"TEXT","content":"<h1>Błotnik przedni prawy VW Golf Sportsvan</h1>"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_16"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_17"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_18"}]}
				]}

Taka z kolei zwraca błąd:
Uncaught SoapFault exception: [ERR_STANDARDIZED_DESCRIPTION_INCORRECT] description musi byÄ podane in... (nazwa pliku).

[fvalue-string] => {"sections":[
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_19"}]},
				{"items":[{"type":"TEXT","content":"<h1>Błotnik przedni prawy VW Golf Sportsvan</h1>
<p>Błotnik przedni prawy w bardzo dobrym stanie, do założenia bez malowania.</p>"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_16"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_17"}]},
				{"items":[{"type":"IMAGE","url":"PHOTO_FID_18"}]}
				]}

Czy to oznacza, że każda linia tekstu formatowanego musi być w osobnej  sekcji items ???

**Comment by emesio** [comment]
abcompl nie musi być każda w nowej sekcji items (sekcje mają odstępy) - ale jak masz w opisie jednej sekcji wiele linii, musisz wysłać znaczniki nowej linii, tj. \n

**Comment by abcompl** [comment]
Już sam nie wiem w czym problem - ten przykład ma nową linię. A właśnie o dziwo jak umieściłem w jednej linii to poszło. Chyba, że jak w treści jest znak \r to się sypie?

**Comment by pfunkowski** [comment]
Nową linię daj jako br

**Comment by abcompl** [comment]
br według specyfikacji nie jest poprawnym tagiem przy nowych ofertach.

**Comment by pfunkowski** [comment]
Masz racje, sprawdziłem u siebie zrobiłem nowe linie poprzez p

5 mar 2018 23:57 "abcompl" <notifications@github.com> napisał(a):

br według specyfikacji nie jest poprawnym tagiem przy nowych ofertach.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/allegro/allegro-api/issues/41#issuecomment-370597824>,
or mute the thread

**Comment by abcompl** [comment]
Po usunięciu z kodu wszystkich znaków nowej linii \n i \r aukcje się wystawiają :)

**Comment by krawczyk12** [comment]
**Abcompl**, możesz pokazać fragment kodu definiujący FID 341?
Wydaje mi się, że robię wszystko tak jak opisujesz, a stale dostaję [ERR_STANDARDIZED_DESCRIPTION_INCORRECT] ...

**Comment by abcompl** [comment]
@krawczyk12 nie wiem czy zrobiłeś te encje żeby się wyświetliły tutaj, czy przekazujesz je w takiej postaci: 
`{ "items": [{ "type":"TEXT", "content": "&lt;h1&gt;Opis&lt;/h1&gt;" }] }`

Jeżeli tak idą sformatowane to wydaje mi się, że to powoduje błąd - webapi jak się przekonałem jest bardzo restrykcyjne.

A mój kod jest prosty:
```
$field->{'fid'} = 341; 
$field->{'fvalue-string'} = '{"sections": [
{"items":[{"type": "IMAGE","url": "PHOTO_FID_18"}]},
{"items": [{"type":"TEXT","content":"'.$opis_allegro.'"}]},
{"items": [{"type":"IMAGE","url":"PHOTO_FID_16"}]},
{"items": [{"type":"IMAGE","url":"PHOTO_FID_17"}]}
]}';
```
Wcześniej opis jest okrojony ze wszystkiego co nie jest przyjmowane.

**Comment by krawczyk12** [comment]
> XMLe w php możesz > wyciągnąć funkcjami:
>
>http://php.net/manual/en/soapclient.getlastrequest.php
>http://php.net/manual/en/soapclient.getlastresponse.php

Wynik:

 REQUEST: 
4c3f138bad505ddbb5536e73ce35f0679c7a9c430bcc68//00_11DotkniÄta przez Niebo. Prawdziwa... - 5756500000000028912400000000400000000052000000008028.6000000091000000001060000000011KrakĂłw00000000012100000000134800000000145100000000152000000001600/9j/4AAQSkZJRgABAQEBLAEsAAD
/2wBDAAQCAwMDAgQDAwMEBAQEBQkGBQUFBQsICAYJDQsNDQ0LDAwOEBQRDg8TDwwMEhgSExUWFxcXDhEZGxkWGhQWFxb
....
[bardzo dużo podobnych linijek  (zdjęcie?)]
.....
/4OR/xNpvUH9hchgUAFnB8fEqf6kNUf1hxXJ4Q+ueJU7jEZgxZfcGq/FNX9Ubvn8I/f0ktv5kw6yObBc2J8xs7w4n/9k=000000029100000000300000000003231-5040000000003510000000024{&quot;sections&quot;:[{&quot;items&quot;:[{&quot;type&quot;:&quot;TEXT&quot;,&quot;content&quot;:&quot;&lt;h1&gt;Dotknieta przez Niebo&lt;/h1&gt;&quot;}]},{&quot;items&quot;:[{&quot;type&quot;:&quot;IMAGE&quot;,&quot;url&quot;:&quot;PHOTO_FID_16&quot;}]}]}0000000003402400000000341{&quot;sections&quot;:[{&quot;items&quot;:[{&quot;type&quot;:&quot;TEXT&quot;,&quot;content&quot;:&quot;&lt;h1&gt;Dotknieta przez Niebo&lt;/h1&gt;&quot;}]},{&quot;items&quot;:[{&quot;type&quot;:&quot;IMAGE&quot;,&quot;url&quot;:&quot;PHOTO_FID_16&quot;}]}]}000000000205941000000005308.49030000000153000000000253500000000054010.49055000000015400000000025450000000005908.60000000159000000000259500000000060012.1000000016000000000026050000000005106.99000000015100000000025150000000005208.99000000015200000000025250000000004603.9900000001460000000002463000000004805.99000000014800000000024830000000044011.490150000000144000000000244500000000045013.4904000000014500000000024550000000004105.49000000014100.5000000024110000000063019.2000000016300000000026310000000064019.2000000016400000000026410000000065019.2000000016500000000026510000000066019.2000000016600000000026610000000067019.2000000016700000000026710000000068019.2000000016800000000026810000000069019.2000000016900000000026910000000070019.2000000017000000000027010000000071019.2000000017100000000027110000000072019.2000000017200000000027210000000073019.2000000017300000000027310000000074019.2000000017400000000027410000000075019.2000000017500000000027510000000076019.2000000017600000000027610000000077019.2000000017700000000027710000000078019.2000000017800000000027810000000079019.2000000017900000000027910000000080019.2000000018000000000028010000000027- OdbiĂłr osobisty w KsiÄgarni Rhema, KrakĂłw ul. Lubicz 10 (3 minuty od Galerii Krakowskiej, przy wiadukcie nad ulicÄ Lubicz), tel. 12-429-46-72, czynne od 9 do 17, soboty od 9 do 14, rhema@rhema.pl. - E-PRZESYĹKA / Paczka48 OdbiĂłr w Punkcie - przesyĹka do odebrania na wybranej poczcie. - PrzykĹadowe koszty wysyĹki za granicÄ przesyĹki o wadze do 0.5 kg: Ameryka PĹn., Afryka - 25,85 zĹ Ameryka PĹd., Azja - 30,75 zĹ Australia - 41,80 zĹ. 00000000005756502a0f59f2-d271-4fa3-9627-d05a80738c6637cab642-07e7-4c53-afc2-df1f9a3c36418ef47797-539b-43a2-b857-bbbb71c62793 

Response: 
ERR_STANDARDIZED_DESCRIPTION_INCORRECTdescription musi byÄ podanedoNewAuctionExt - Given standardized description is incorrect.387:1520335184:49

**Comment by krawczyk12** [comment]
@abcompl, dzięki!

> @krawczyk12 nie wiem czy zrobiłeś te encje żeby się wyświetliły tutaj, czy przekazujesz je w takiej postaci:
> { "items": [{ "type":"TEXT", "content": "&lt;h1&gt;Opis&lt;/h1&gt;" }] }

Próbowałem i tak i tak - bez różnicy.

> 
> Jeżeli tak idą sformatowane to wydaje mi się, że to powoduje błąd - webapi jak się przekonałem jest bardzo restrykcyjne.
> 
> A mój kod jest prosty:
> 
> $field->{'fid'} = 341; 
> $field->{'fvalue-string'} = '{"sections": [
> {"items":[{"type": "IMAGE","url": "PHOTO_FID_18"}]},
> {"items": [{"type":"TEXT","content":"'.$opis_allegro.'"}]},
> {"items": [{"type":"IMAGE","url":"PHOTO_FID_16"}]},
> {"items": [{"type":"IMAGE","url":"PHOTO_FID_17"}]}
> ]}';
> 
Mam na oko identycznie - i lipa :-(

**Comment by krawczyk12** [comment]
To już nikt nie ma żadnego pomysłu, jak mi pomóc?
@pfunkowski - Request nie pomógł?

**Comment by KrzysztofLukanowski** [comment]
@krawczyk12 trochę nieczytelny ten request. Czy próbowałeś wystawić przez GUI, a następnie pobrać pola oferty metodą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842)? W odpowiedzi zobaczysz jak powinien wyglądać prawidłowy zapis.

**Comment by krawczyk12** [comment]
Tak.
Nawet skopiowałem cały FID tak jak przyszedł prez  doGetItemFields i dostałem ten sam błąd.
Czy ten nowy opis ma być przesyłany przez element tablicy 'fvalue-string'?
Czy może kodowanie ma znaczenie - ja mam UTF-8?
Co to może być - wszystkim działa, a mnie nie...

**Comment by krawczyk12** [comment]
Tak wygląda fid, który posyłam:
Array
(
    [fid] => 341
    [fvalue-string] => {"sections": [
            {"items": [{"type":"TEXT","content":"<h1>Obraz sr 6542/1 IKŚw. Kielich w sercu     7x8</h1>"}]}
        ]}
    [fvalue-int] => 0
    [fvalue-float] => 0
    [fvalue-image] => 
    [fvalue-datetime] => 0
    [fvalue-date] => 
    [fvalue-range-int] => Array
        (
            [fvalue-range-int-min] => 0
            [fvalue-range-int-max] => 0
        )

    [fvalue-range-float] => Array
        (
            [fvalue-range-float-min] => 0
            [fvalue-range-float-max] => 0
        )

    [fvalue-range-date] => Array
        (
            [fvalue-range-date-min] => 0
            [fvalue-range-date-max] => 0
        )

)

**Comment by KrzysztofLukanowski** [comment]
Jeżeli przesyłasz opis bez encji, wrzuć go proszę w CDATA, a więc FID 341 powinien wyglądać tak:

<![CDATA[ opis ]]>

**Comment by krawczyk12** [comment]
```
 {"sections": [
             {"items": [{"type":"TEXT","content":"<![CDATA[<h1>Opis testowy</h1>]]>"}]}
         ]}
```


Fatal error: Uncaught SoapFault exception: [ERR_STANDARDIZED_DESCRIPTION_INCORRECT] description musi być podane in /allegro/alled.php:312 Stack trace: #0 /allegro/alled.php(312): SoapClient->__call('doNewAuctionExt', Array) #1 /allegro/alled.php(312): SoapClient->doNewAuctionExt('615750ba0e19355...', Array, 0, '57365', Array, '', '', Array) #2 {main} thrown in /allegro/alled.php on line 312

**Comment by KrzysztofLukanowski** [comment]
@krawczyk12 nie zrozumieliśmy się - opis to cała zawartość FID 341, a więc w znaczniku <![CDATA[]]> wprowadź wszystko, począwszy od `{"sections"`

**Comment by imper86** [comment]
Jeżeli faktycznie wysyłasz request jako tablica i jako key podajesz np 'fvalue-string' to nic dziwnego, że nie działa. Może błąd nie wynika ze złej struktury samego nowego opisu, tylko w ogóle ze złej struktury całego requesta?

Tak czy inaczej, gdybyś wysłał paczki xml, faktycznie byłoby łatwiej.

Zrób po prostu file_put_contents('sciezka_do_pliku.xml', $soapClient->__getLastRequest()) i wrzuć gdzieś zawartość pliku, np na pastebin.

**Comment by krawczyk12** [comment]
> @KrzysztofLukanowski  nie zrozumieliśmy się - opis to cała zawartość FID 341, a więc w znaczniku wprowadź wszystko, począwszy od {"sections"

Niestety:

```
Array
(
    [fid] => 341
    [fvalue-string] => <![CDATA[
                    {"sections": [
                            {"items": [{"type":"TEXT","content":"<h1>Opis testowy</h1>"}]}
                ]}
            ]]>
    [fvalue-int] => 0
    [fvalue-float] => 0
    [fvalue-image] => 
    [fvalue-datetime] => 0
    [fvalue-date] => 
    [fvalue-range-int] => Array
        (
            [fvalue-range-int-min] => 0
            [fvalue-range-int-max] => 0
        )

    [fvalue-range-float] => Array
        (
            [fvalue-range-float-min] => 0
            [fvalue-range-float-max] => 0
        )

    [fvalue-range-date] => Array
        (
            [fvalue-range-date-min] => 0
            [fvalue-range-date-max] => 0
        )

)

```

Fatal error: Uncaught SoapFault exception: [ERR_STANDARDIZED_DESCRIPTION_INCORRECT] description musi być podane in ...

**Comment by krawczyk12** [comment]
@imper86

> Jeżeli faktycznie wysyłasz request jako tablica i jako key podajesz np 'fvalue-string' to nic dziwnego, że nie działa. Może błąd nie wynika ze złej struktury samego nowego opisu, tylko w ogóle ze złej struktury całego requesta?

Ze starym opisem jest OK, więc chyba wszystko inne jest dobrze...

> 
> Tak czy inaczej, gdybyś wysłał paczki xml, faktycznie byłoby łatwiej.

W dokumentacji Allegro jest tak jak robię, nie wiem jak można robic inaczej...
> 
> Zrób po prostu file_put_contents('sciezka_do_pliku.xml', $soapClient->__getLastRequest()) i wrzuć gdzieś zawartość pliku, np na pastebin.

Poniżej fragment tego pliku, wycięte inne `<items>` poza FID = 341.
Próbował przedtem bez `<![CDATA[...]]>` i był ten sam błąd.
Mogę gdzieś wrzucić oczywiście caly plik.
```
<?xml version="1.0" encoding="UTF-8"?>
-<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="urn:AllegroWebApi" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
-<SOAP-ENV:Body>
-<ns1:doNewAuctionExt>
<session-handle xsi:type="xsd:string">e827506016cb54abe6cab481d9be0380b0eeb627846f2f//03_1</session-handle>
-<fields xsi:type="ns1:ArrayOfFieldsValue" SOAP-ENC:arrayType="ns1:FieldsValue[114]">
-------
-<item xsi:type="ns1:FieldsValue">
  <fid xsi:type="xsd:int">341</fid>
  <fvalue-string xsi:type="xsd:string">&lt;![CDATA[ {&quot;sections&quot;: [ {&quot;items&quot;: [{&quot;type&quot;:&quot;TEXT&quot;,&quot;content&quot;:&quot;&lt;h1&gt;Opis testowy&lt;/h1&gt;&quot;}]} ]} ]]&gt;</fvalue-string>
  <fvalue-int xsi:type="xsd:int">0</fvalue-int>
  <fvalue-float xsi:type="xsd:float">0</fvalue-float>
  <fvalue-image xsi:type="xsd:base64Binary"/>
  <fvalue-datetime xsi:type="xsd:float">0</fvalue-datetime>
  <fvalue-date xsi:type="xsd:string"/>
  -<fvalue-range-int xsi:type="ns1:RangeIntValueStruct">
    <fvalue-range-int-min xsi:type="xsd:int">0</fvalue-range-int-min>
    <fvalue-range-int-max xsi:type="xsd:int">0</fvalue-range-int-max>
  </fvalue-range-int>
  -<fvalue-range-float xsi:type="ns1:RangeFloatValueStruct">
    <fvalue-range-float-min xsi:type="xsd:float">0</fvalue-range-float-min>
    <fvalue-range-float-max xsi:type="xsd:float">0</fvalue-range-float-max>
  </fvalue-range-float>
  -<fvalue-range-date xsi:type="ns1:RangeDateValueStruct">
    <fvalue-range-date-min xsi:type="xsd:string">0</fvalue-range-date-min>
    <fvalue-range-date-max xsi:type="xsd:string">0</fvalue-range-date-max>
  </fvalue-range-date>
</item>
------------
</fields>
<item-template-id xsi:type="xsd:int">0</item-template-id>
<local-id xsi:type="xsd:int">57204</local-id>
-<item-template-create xsi:type="ns1:ItemTemplateCreateStruct">
<item-template-option xsi:type="xsd:int">0</item-template-option>
<item-template-name xsi:type="xsd:string"/>
</item-template-create>
<variants xsi:type="ns1:ArrayOfVariantStruct"/>
<tags xsi:type="ns1:ArrayOfTagNameStruct"/>
-<after-sales-service-conditions xsi:type="ns1:AfterSalesServiceConditionsStruct">
<implied-warranty xsi:type="xsd:string">2a0f59f2-d271-4fa3-9627-d05a80738c66</implied-warranty>
<return-policy xsi:type="xsd:string">37cab642-07e7-4c53-afc2-df1f9a3c3641</return-policy>
<warranty xsi:type="xsd:string">8ef47797-539b-43a2-b857-bbbb71c62793</warranty>
</after-sales-service-conditions>
<additional-services-group xsi:nil="true"/>
</ns1:doNewAuctionExt>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by KrzysztofLukanowski** [comment]
@krawczyk12 wystawiłem ofertę dokładnie z taką zawartością FID 341, jaką podałeś wyżej. Podeślij proszę pełen request w xml.

**Comment by krawczyk12** [comment]
@KrzysztofLukanowski - poniżej link do pełnego requestu (zwróconego przez __getLastRequest()):

https://drive.google.com/open?id=1e7tLUiK1-BSKePNHSQymMbQeZuUUETQu

**Comment by TomekKaczmarek** [comment]
@krawczyk12 Sprawdziłem Twój request - niepotrzebnie wprowadzasz encje w elementach JSONowych. Encje wystarczy wprowadzić w HTMLu, którym budujesz opis. W FID 341 prześlij poniższą wartość:

`			{
	"sections": [{
				"items": [{
					"type": "TEXT",
					"content": "&lt;h1&gt;Tytul&lt;/h1&gt;&lt;p&gt;Opis testowy&lt;/p&gt;"
				}]
			}
			]}`

**Comment by krawczyk12** [comment]
@TomekKaczmarek - Niestety, skopiowałem i wstawiłem Twoją wartość i jest to samo:

```
Array
(
    [fid] => 341
    [fvalue-string] => { "sections": [{ "items": [{ "type": "TEXT", "content": "&lt;h1&gt;Tytul&lt;/h1&gt;&lt;p&gt;Opis testowy&lt;/p&gt;" }] } ]}
    [fvalue-int] => 0
    [fvalue-float] => 0
    [fvalue-image] => 
    [fvalue-datetime] => 0
    [fvalue-date] => 
    [fvalue-range-int] => Array
        (
            [fvalue-range-int-min] => 0
            [fvalue-range-int-max] => 0
        )
    [fvalue-range-float] => Array
        (
            [fvalue-range-float-min] => 0
            [fvalue-range-float-max] => 0
        )
    [fvalue-range-date] => Array
        (
            [fvalue-range-date-min] => 0
            [fvalue-range-date-max] => 0
        )
)

[ERR_STANDARDIZED_DESCRIPTION_INCORRECT] description musi być podane
```

**Comment by TomekKaczmarek** [comment]
Wysłałem Twój opis bezpośredni w requeście XML - nie mogę powtórzyc błędu. Sprawdź czy błąd nie pojawia się przy procesie tworzenia XMLa. Czy jakieś znaki nie są zamieniane lub czy nie zmienia się kodowanie.

W każdym razie to XML z requestem powinien wyglądać tak, wtedy request kończy się sukcesem
`		  <ser:item>
               <ser:fid>341</ser:fid>
			<ser:fvalueString>	
			{ "sections": [{ "items": [{ "type": "TEXT", "content": 
                            "&lt;h1&gt;Tytul&lt;/h1&gt;&lt;p&gt;Opis testowy&lt;/p&gt;" }] } ]}
			</ser:fvalueString>
		  </ser:item>`

**Comment by krawczyk12** [comment]
@TomekKaczmarek - U mnie niestety wygląda tak:

`<item xsi:type="ns1:FieldsValue"><fid xsi:type="xsd:int">341</fid><fvalue-string xsi:type="xsd:string">{&amp;quot;sections&amp;quot;:{&amp;quot;items&amp;quot;:{&amp;quot;type&amp;quot;:&amp;quot;TEXT&amp;quot;,&amp;quot;content&amp;quot;:&amp;quot;&amp;amp;lt;p&amp;amp;gt;Test&amp;amp;lt;/p&amp;amp;gt;&amp;quot;}}}</fvalue-string></item>`

Czyli `"` i `&` są zamienione na encje.
Jak można temu zapobiec, albo jak wysłać request jako xml?

Ja wysyłam tak: 
`$res = $client->doNewAuctionExt($session['session-handle-part'], $fields, 0, $nr,
                                    array('item-template-option'=>0, 'item-template-name'=>''), 
                                    '', '', $rules);`
gdzie $fields zawiera wszystkie fidy.

**Comment by TomekKaczmarek** [comment]
@krawczyk12 warunek zmiany znaków na encje wprowadzasz na zbyt wysokim poziomie. Całą wartość FID 341 zamieniasz na encję. Na encję powinieneś zamienić tylko to co wysyłasz w stringu "content" w jsonie z opisem przedmiotu.

Alternatywnym rozwiązaniem jest użycie znacznika CDATA - na całą wartość FID 341. Wtedy nie musisz zmieniać znaków na encje.

`<![CDATA[{"sections":[{"items":[{"type":"TEXT","content":"<h1>Oferta testowa - nie realizujemy zakupów</h1>"}]}...]}]]>`

**Comment by krawczyk12** [comment]
@TomekKaczmarek - Ale ja NIE zamieniam znaków na encje - program sam to robi!
Co z tym zrobić?
Może jakoś inaczej wysyłać request?
Ja wysyłam tak: 
`$res = $client->doNewAuctionExt($session['session-handle-part'], $fields, 0, $nr,
                                    array('item-template-option'=>0, 'item-template-name'=>''), 
                                    '', '', $rules);`
gdzie $fields zawiera wszystkie fidy. 
FID 341 jest jak w poprzednich postach (taki jak u Ciebie) - próbowalem zarówno z CDATA jak i bez...
