### ISSUE TITLE
change-price-commands - brak skutku

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#410]
Cześć, klienci zgłaszają mi problemy które występowały na pewno wczoraj. Change-price-commands nie zmieniał ceny w ofercie nie zwracając jednocześnie żadnego komunikatu o błędzie.
Spływają jeszcze pojedyncze zgłoszenia z dziś, natomiast trudno mi ocenić czy są to opóźnienia (dzięki hułałej) czy problem nadal występuje.
Przykładowe numery ofert:
7336467640
6941765202
6103200623
5639095081
7451888497
Czy mogę prosić o sprawdzenie?

**Comment by KrzysztofLukanowski** [comment]
Cześć, nie odnotowaliśmy problemów. Kiedy konkretnie klienci zmieniali ceny w swoich aplikacjach? Widzę, że w części ofert zmiany były dziś w nocy i nad ranem.

**Comment by rtnet-pl** [comment]
@KrzysztofLukanowski 
Pozwolę sobie zacytować:
`Ostatnie dwa przypadki co do których jestem pewien to aukcja nr: 6941765202 - wczoraj około 16:00 (2x) oraz aukcja nr: 7451888497 - dzisiaj około 9:30. Opcja zadziałała dopiero po kilku powtórzeniach.`

**Comment by KrzysztofLukanowski** [comment]
Nie odnotowaliśmy takich zmian. Podaj proszę trace-id dla tych requestów, zbadamy sprawę.

**Comment by rtnet-pl** [comment]
Cześć, dzięki za odpowiedź, niestety identyfikatorów nie mam - dysponuję wyłącznie numerami itemów i ramami czasowymi

**Comment by KrzysztofLukanowski** [comment]
Niestety nie mamy żadnych informacji o takich zmianach w tym czasie, trace-id pozwoliłoby dokładniej zbadać temat.
