### ISSUE TITLE
Zła kategoria w produktyzacji

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4101]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**
Nie wiem czy tak powinno być ale do produktu jest przypisana kategoria która nie istnieje.

Id produktu: 1eecd7db-f2a4-4492-805d-b7156d7a7fe6
id kategorii: 260950 

GET https://api.allegro.pl/sale/categories/260950 zwraca 404 not found

**Comment by AureliuszBrussy** [comment]
Zgłosiłem już błąd w produkcie do odpowiedniego zespołu. Gdy to poprawimy - wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
Poprawiliśmy dane w produkcie - aktualnie kategoria jest prawidłowa.

**Comment by TomaszSzydlowski-sudo** [comment]
@AureliuszBrussy Dziekuje bardzo
