### ISSUE TITLE
ERROR 503 SERVICE_UNAVAILABLE /offers/listing

### ISSUE THREAD

**Issue by meridPL** [allegro/allegro-api#4102]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Widzę, że opisane jest, że problem ma się nie pokazywać niestety w niektórych sytuacja i nie zwsze wyświetla mi się taki błąd

```

headers = {
"Authorization": "Bearer " + access_token,
"Accept": "application/vnd.allegro.public.v1+json",
}

list_province = [
"DOLNOSLASKIE",
"KUJAWSKO_POMORSKIE",
"LUBELSKIE",
"LUBUSKIE",
"LODZKIE",
"MALOPOLSKIE",
"MAZOWIECKIE",
"OPOLSKIE",
"PODKARPACKIE",
"PODLASKIE",
"POMORSKIE",
"SLASKIE",
"SWIETOKRZYSKIE",
"WARMINSKO_MAZURSKIE",
"WIELKOPOLSKIE",
"ZACHODNIOPOMORSKIE"
]

Pętla id i province

req3 = requests.get("https://api.allegro.pl/offers/listing, headers=headers, params={
"category.id": 305601,
"phrase": "Lego " + str(self.id_lego),
"parameter.11323": "11323_1",
"sellingMode.format": "BUY_NOW",
"location.province": province,
"offset": offset,
"fallback": "false"
})


```

Jest to w pętli i nie zawsze występuje w tym samym id lego. Dodam tylko, że problem zaczął występować po dodaniu province.

Błąd

`{'errors': [{'code': 'SERVICE_UNAVAILABLE', 'message': 'Service unavailable.', 'details': None, 'path': None, 'userMessage': 'Service unavailable. Please try again in a few minutes.'}]}`

W tym momencie rozwiązuje to tak, że po prostu jeszcze raz po nie udanej próbie wykonuje request i działa, ale nie wiem na ile to może być problematyczne w przyszłości

**Comment by AureliuszBrussy** [comment]
Widzę, że wcześniej zgłosiłeś ten problem w innym wątku: #3051. Kolega odpisał już na Twoje zgłoszenie.
