### ISSUE TITLE
Czy trzeba sprawdzać wpłaconą kwotę, czy też można oprzeć się tylko o READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by pakkpl** [allegro/allegro-api#4104]
Czy jeśli otrzymamy READY_FOR_PROCESSING event, to czy przy pobieraniu szczegółów przez /sale/offers/ musimy dodatkowo sprawdzać wpłaconą kwotę?
Czy też wystarczy oprzeć się o ten status oraz o pole revision?

**Comment by pakkpl** [comment]
A jaki sposob mozna przetestowac nadplaty/niedoplaty w sandbox?
Po wybraniu metody platnosci nie moge zmienic kwoty, mogę jedynie wybrac czy czy transakcja zakonczona sukcesem czy nie...

**Comment by AureliuszBrussy** [comment]
Niestety, nie uda się tego odtworzyć na Sandboxie - nadpłata i niedopłata może nastąpić tylko w przypadku, gdy Kupujący wybierze podczas finalizowania zamówienia przelew tradycyjny i wykonanie go na niepoprawną kwotę. Symulator płatności nie przewiduje takiej możliwości.

**Comment by pakkpl** [comment]
To jeszcze kilka pytań:
- jeśli klient nie zapłaci całości to dostaniemy event READY_FOR_PROCESSING ?
- jeśli klient zrobi nadpłatę to otrzymamy event READY_FOR_PROCESSING?
- jeśli klient zrobi nadpłatę i później zrobi kolejną nadpłatę to czy otrzymamy również kolejny event READY_FOR_PROCESSING?

**Comment by AureliuszBrussy** [comment]
1. Zamówienie niedopłacone może otrzymać status READY_FOR_PROCESSING.

2. Zamówienie nadpłacone może otrzymać status READY_FOR_PROCESSING.

3. Klient może opłacić zamówienie jednokrotnie, ewentualne pozostałe przelewy po zaksięgowaniu pierwszej wpłaty zostaną automatycznie zwrócone. Później może wykonać ewentualną dopłatę. 
Zwróć uwagę, że może występować wiele zdarzeń dla jednego zamówienia (minimum jedno) np. zakup, wpłata, dopłata. W związku z tym możesz np. otrzymać kilka zdarzeń READY_FOR_PROCESSING, dlatego zwróć uwagę na identyfikator zamówienia w obiekcie checkoutForm i to właśnie na nim oprzyj swoją logikę obsługi zamówień.
