### ISSUE TITLE
Podwójna integracja Allegro

### ISSUE THREAD

**Issue by Przemeko4s** [allegro/allegro-api#4106]
Czy jest możliwe użycie dwóch integracji kontaktujących się z jednym kontem Allegro? Słyszałem o sytuacji, gdzie po podpięciu dodatkowej integracji (menedżer sprzedaży allegro) konto to utraciło połączenie ze wcześniej skonfigurowaną integracją sklepową. W mojej sytuacji niezbędne jest nawiązanie bezpośredniego kontaktu z hurtownią zachowując integrację z baselinkerem i sklepem internetowym.
Bardzo proszę o odpowiedź i wyjaśnienie.

**Comment by AureliuszBrussy** [comment]
Jedno konto Allegro może być powiązane z wieloma aplikacjami - ze strony Allegro API nie ma takich ograniczeń. 

Zwróć jednak uwagę na to, że jeżeli różne aplikacje korzystają z tych samych zasobów - ich działanie może wpływać na siebie wzajemnie i tworzyć konflikty, zależnie od architektury danej integracji. Dlatego zachęcam także do ewentualnego kontaktu z twórcami aplikacji, z których chcesz skorzystać równocześnie, aby dowiedzieć się, czy mogą wystąpić jakieś konflikty

**Comment by Przemeko4s** [comment]
Dokładniej chodzi o zewnętrzną integrację z hurtownią na zasadzie dropshippingu, oprócz aktualizacji stanów dla baselinkera konto allegro musi przekazywać informację do hurtowni w celu automatycznego druku etykiet i wysyłki. Wydaje mi się, że nie powinno stanowić to żadnego konfliktu, jednak postaram się też skontaktować z hurtownią.
