### ISSUE TITLE
Automatic offer description via POST /sale/product-offers

### ISSUE THREAD

**Issue by MetaMimic** [allegro/allegro-api#4107]
**Przepraszam za pisanie po angielsku. Mój polski jest bardzo zły.**

On this page:
https://developer.allegro.pl/en/product_offers/#how-to-add-offer-description

I read:
"You can add your own description to the offer. If you will not, we will automatically assign a description from the product you indicated in the request."

I have tried listing draft orders and active orders without passing the description in the request, but the description section in the ad is blank. 

Does it take some time for the description to be pulled from the product page? Or am I doing something wrong?

Thanks in advance.
(Polish replies are not a problem, I can use Google Translate)

**Comment by AureliuszBrussy** [comment]
Some products in our database do not have a "description" object filled - it is not required. In such cases, you should fill the description by yourself.

**Comment by MetaMimic** [comment]
Thank you for your reply.
Is there a way in which I can test it a product as the description object filled?

I ask, because the products that I tested are very mainstream and the ads that are online seem to have homogeneous descriptions.

**Comment by AureliuszBrussy** [comment]
You can add your own product with a description field filled by using  [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) on Sandbox, then test it. You can read how to create a product [in our guide](https://developer.allegro.pl/en/productization/#6-how-to-create-a-product). You can also search for existing products (by using [GET /sale/products](https://developer.allegro.pl/en/productization/#2-how-to-search-for-products)) and check if the description field is filled in.
