### ISSUE TITLE
ShopGold do Allegro i do WP

### ISSUE THREAD

**Issue by EdSkamor** [allegro/allegro-api#4109]
Witam, zamierzam zacząć pracować z allegro-api, chciałbym przenieść swoje produkty z shopgold: 
https://www.shopgold.pl/integracja-sklepu-shopgold-z-allegro-n-7.html
Planuję zassać przez allegro-api wszystkie produkty jakie mam w sklepie, jak to zrobić? 
Planuję następnie wystawić część ofert na allegro z użyciem api, to wiem jak zrobić, teoretycznie.
Ostatnim krokiem będzie wysłanie wszystkich produktów na nową witrynę na wordpress woocommerce.

Czy to wszystko jest wykonalne z poziomu API? 
Zależy mi żeby potem nie musieć siedzień nad api bo robię to dla rodziny - jako ten najbardziej ogarnięty z informatyki.
Proszę o wskazówki.

[REST API](https://developer.allegro.pl/)
[Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/auth/)
[Jak wystawić ofertę](https://developer.allegro.pl/sale/)
[Jak zarządzać ofertami](https://developer.allegro.pl/my_offers/)
[Jak obsługiwać zamówienia](https://developer.allegro.pl/orders/)
[Jak zarządzać zestawami i rabatami](https://developer.allegro.pl/offer_bundles/)
[Jak utworzyć ofertę wielowariantową](https://developer.allegro.pl/multi_variant_offers/)
[WebAPI](https://allegro.pl/webapi)
-->

**Comment by AureliuszBrussy** [comment]
Jeżeli chodzi o wystawienie produktów, które posiadasz w swoim zewnętrznym sklepie - proszę, skieruj pytanie do twórców danego narzędzia, aby dowiedzieć się, czy jest to możliwe. Narzędzie takie musiałoby mieć wdrożoną możliwość wystawiania nowych ofert Allegro z produktów.

Możesz następnie zintegrować swój nowy sklep z API Allegro, aby ten mógł pobierać dane o Twoich ofertach przez API Allegro ([GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) oraz [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)). 

Wykonanie wszystkich czynności, o których piszesz jest możliwe z wykorzystaniem API Allegro.
