### ISSUE TITLE
login a powiadomienia e-mail

### ISSUE THREAD

**Issue by lukasnet** [allegro/allegro-api#411]
Czy możecie ujednolicić loginy kupujących? bo jak ktoś jest niezarejestrowany to albo oznaczacie go jako "niezarejestrowany" albo "Client:111111" albo jakieś "!g_111111" a co gorsza to w każdym mailu inaczej. 
Przykładowo, nie ma jak potem wyszukać loginu w temacie "Kupujący niezarejestrowany wybrał sposób zapłaty i dostawy w ofercie" bo tego robi się pełno.
Czy nie lepiej zastosować wszędzie jedną wersję?! np Client:11111 albo wtedy zamiast loginu adres e-mail

**Comment by KrzysztofLukanowski** [comment]
Podany przez Ciebie przykładowy login "Client:1111" to pierwsza nazwa użytkownika, który dopiero co zarejestrował się. Z kolei "!g_ciagcyfr" to nazwa klienta, który kupił bez rejestracji. Oczywiście dziękujemy za uwagę - pracujemy nad uspójnieniem przekazywanych informacji.
