### ISSUE TITLE
Różnie wyświetlane podpięcie produktu w ofercie

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4110]
Od czego zależy sposób wyświetlania podpiętego produktu w ofercie? 

Zauważyłem, że niektóre oferty podpięte pod produkt mają tylko gwiazdki z oceną a inne mają tytuł, gwiazdki i "inne oferty tego produktu":

![rozne_podpiecie_produktu](https://user-images.githubusercontent.com/48419261/105533548-919db080-5cec-11eb-9beb-8e8aa86a0fa9.jpg)

**Comment by AureliuszBrussy** [comment]
Sposób wyświetlania zależny jest od kategorii, w której oferta jest wystawiona. W wybranych kategoriach informacje o produkcie przedstawiamy w taki sposób jak w drugiej ofercie na przesłanym obrazku.
