### ISSUE TITLE
Czy można pobrać informację, czy oferta jest smart

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#4111]
Hej,

Czy za pomocą `offers/listing?phrase=` można pobrać informację, czy dana oferta zawiera pakiet SMART?
Wiem, można przefiltrować po ofertach zawierających smart, ale chciałbym pobrać wszystkie oferty i wiedzieć, które z nich są smart.

**Comment by AureliuszBrussy** [comment]
Nie ma takiej możliwości -  możesz skorzystać jedynie z filtrowania ofert Allegro Smart.

**Comment by jakubmaguza** [comment]
W takim razie wnoszę taką sugestię, chociaż bez większych nadziei. Taka zmiana przybliżała by ten endpoint do wyszukiwarki na froncie.

**Comment by AureliuszBrussy** [comment]
Dopisuję sugestię do listy sugestii dot. rozwoju API Allegro.
