### ISSUE TITLE
Ceny w API dla ofert objętych programem Allegro Ceny

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#4112]
W poniższym artykule:
https://allegro.pl/dla-sprzedajacych/poznaj-allegro-ceny-na-czym-polega-program-wsparcia-dla-sprzedajacych-2YAZ1gAqRiK

napisaliście: "O rozpoczęciu i zakończeniu obniżki ceny w każdej ofercie damy Ci znać mailowo. Wyświetlimy też komunikat w zakładce Moje oferty oraz w API."

Chciałbym doprecyzować co oznacza "Wyświetlimy też komunikat w API"? Gdzie dokładnie będzie ta informacja?
Dodatkowo, jaką wartość dla ofert z obniżoną ceną będzie zwracać zasób GET /sale/offers w informacji o ofercie w polu sellingMode.price.amount? Jeśli to będzie cena obniżona, to czy gdzieś będzie zwracana cena sprzed obniżki?

**Comment by PrzemyslawLukanowski** [comment]
Komunikat w API oznacza informację, jaką otrzymasz dla GET /sale/badges (w [newsie ](https://developer.allegro.pl/news/#subsidy-badges)znajdziesz przykładowy response). W GET /sale/offers zwrócimy oryginalną cenę (nieobniżoną).

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , czy jeśli oferta zostanie zakupiona poprzez Allegro Ceny to czy w zasobie szczegółów zamówienia` /order/checkout-forms/{id}` w kwocie płatności `payment.paidAmount.amount` otrzymam kwotę pełną czy po obniżce?

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Otrzymasz w tym polu pełną kwotę.

**Comment by PrzemyslawLukanowski** [comment]
@cyfranT Przepraszam za wprowadzenie w błąd - w /sale/offers otrzymasz cenę już po obniżce.
