### ISSUE TITLE
Błąd przy tworzeniu przesyłki - numer telefonu

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4114]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas tworzenia przesyłki przez REST API:
CommandId: b5f17384-04a9-4ba4-a090-5e427d1b0bd6

Otrzymuję błąd: 
Phone number is required | Numer telefonu odbiorcy jest wymagany

To samo przy CommandId: 2368d647-e797-40ac-8a48-5fd92e6166b3

Telefon jest oczywiście podawany.
Z innymi przesyłkami nie mam problemu, a jedynie z tym numerem.

**Comment by marmited** [comment]
@PrzemyslawLukanowski Dobra, sami rozwiązaliśmy zagadkę. Jest to numer stacjonarny i prawdopodobnie walidacja InPosta nie pozwala na użycie tego numeru. Jeżeli tak jest to pytanie jest następujące: dlaczego wysyłacie błędne komunikaty?

**Comment by PrzemyslawLukanowski** [comment]
Zmienimy treść wyświetlanego komunikatu, tak aby był bardziej precyzyjny.
