### ISSUE TITLE
Chwilę po odświeżeniu tokena nie jestem w stanie go użyć

### ISSUE THREAD

**Issue by pkoziolandrobit** [allegro/allegro-api#4115]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Chwilę po odświeżeniu tokena nie jestem w stanie go użyć. A wygląda to jak w logach poniżej.**

Niestety nie mam zalogowanego trace-id, ale myślę, że poniższe wpisy z logów wystarczą do zidentyfikowania zapytań.

Sytuacja taka.
1. Odświeżam token. Zwracane są nowe dane.

`01/25 20:02:00.395 [get allegro user token] GET https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI1MDc2NjQxNCIsInNjb3BlIjpb
ImFsbGVncm86YXBpOm9yZGVyczpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YmlsbGluZzpyZWFkIiwiYWxsZWdybzphcGk6Y2FtcGFpZ25zIiwiYWxsZWdybzphcGk6ZGlz
cHV0ZXMiLCJhbGxlZ3JvOmFwaTpiaWRzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSIsImFsbGVncm86YXBpOmFkcyIsImFsbGVncm86YXBpOnBheW1lbnRzOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0
aW5nczp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnJhdGluZ3MiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwYXltZW50czpyZWFkIl0sImFsbGVncm9fYXBpIjp0cnVlLCJhdGkiOiI5Mzg3
NGUzYi1jYjRjLTQ1YjAtODg0NC05MjlkYmEwNGVmOWQiLCJleHAiOjE2MTkzNzU1NzMsImp0aSI6IjljZGNhNDFlLWZmNjQtNGM5My1iNDY3LWEwNzY0ZTU0NjRlMiIsImNsaWVudF9pZCI6ImUwZmI0Nzk4NDQ4OTQ1YTZiMzcxODg1ZjY5MDUxOTBlIn0.RFJu7MW90f85
xJGGcRzWQlh2Sf40Jqi5fpFdQBTBiKEjWsmhMC3ZOsNIsqa4_ezKBETbghrHgInxoc9PTxHRhaa5G2tR_e809fGHdYChmhTVS0zdnXqED3lyBWsQC0x1jXJSd8x4ASVT3KukDtQnxj8sAOx_m0-sY75DZXTX9-dIEdzcjzF-Rj0SVDujraxHAln5laGi22YtfwELNfdaGgFh
sFuWu7tghjvDDXqtzB0uVwNsZfbopUiO4WnTiyaP9wbmbE3y7Byoj3D18z90dR2WgpIx8d_lm1oxYiyJ0lyA6QyRUYo5_FModkNwn8yKrZGrcTHgeARiOrDIk2uuRw&redirect_uri=https://www.stocksell.io/allegro/api-response responseBody={"acc
ess_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE2NDQ1MjAsInVzZXJfbmFtZSI6IjUwNzY2NDE0IiwianRpIjoiNjM1ODFlMzgtZWJmOS00YjkyLWJhNzUtMWVhYWY0M2Y4MDE3IiwiY2xpZW50X2lkIjoiZTBmYjQ3OTg0NDg5NDVhNmI
zNzE4ODVmNjkwNTE5MGUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmN
hbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml
0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGx
lZ3JvX2FwaSI6dHJ1ZX0.sryZb5fDIkzDMFE_pWwPzXKlK5LDNQK19hT9cu0MkCe_EHDdJ5lwEq-7T1-qlfBogtOK_bCeRMUFanwS5MYiqVvO4jUj9dwKbaUXDhRa3esrpaU1KtPLchXd96q2dThULtVjQ22_QWjojzl2TS_ujAI0QUFElUEZQp-35KTT18exjS-XB2KVHY1
h7OOAC9VXPxZPCrogaU6Pnefqb7lHhd01XZpFx2K6EOh-iSUux1hVyv233HCQP2vbUSNSbM0guigpFhV8hRjjVJNWJw6giyCDaIrfEk5lVk5XUE52ZoWhe2sI7nJb_XH0d086UakunRuxW2iAkLTHFDi8Q8N65A","token_type":"bearer","refresh_token":"eyJh
bGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiI1MDc2NjQxNCIsInNjb3BlIjpbImFsbGVncm86YXBpOm9yZGVyczpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOndyaXRlIiwiYWxsZWdybzp
hcGk6YmlsbGluZzpyZWFkIiwiYWxsZWdybzphcGk6Y2FtcGFpZ25zIiwiYWxsZWdybzphcGk6ZGlzcHV0ZXMiLCJhbGxlZ3JvOmFwaTpiaWRzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSIsImFsbGVncm86YXB
pOmFkcyIsImFsbGVncm86YXBpOnBheW1lbnRzOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU6cmVhZCIsImFsbGVncm86YXBpOnJhdGluZ3MiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOnJlYWQiLCJ
hbGxlZ3JvOmFwaTpwYXltZW50czpyZWFkIl0sImFsbGVncm9fYXBpIjp0cnVlLCJhdGkiOiI2MzU4MWUzOC1lYmY5LTRiOTItYmE3NS0xZWFhZjQzZjgwMTciLCJleHAiOjE2MTkzNzczMjAsImp0aSI6Ijg4NzhkNDI1LThmODMtNGQwOS1hNDg4LTRiNDVmNjNhMGRiZCI
sImNsaWVudF9pZCI6ImUwZmI0Nzk4NDQ4OTQ1YTZiMzcxODg1ZjY5MDUxOTBlIn0.RM1P6XgbFNSY19cjqJ3g-npkI7qL8cVFvb5tOUJN9mSQ-4bZngfTMFu-aSHBtV-7_nKUppaJhMuqk2ChU6HhbQYcA_YYnINYZ31U_rMVpeypCEc_H32iAwiYBX_Lkloj35nwkzLaLdz
CoFy1JwpOrfIFKDVsxCcEqKeHYJ6okfjByzPJ-jRn5YKFUGWxGFDjpNXFf7rjgIK_lAnz3mGJv5rd_-qT46qy2R9kTk4rGiIDKqCID1f8T2yIdH1bCwOjjEmciGqV0C4kFIqT5fl6l-J-B8u6sEchbm8io29u8XuiUjv0f9_REq4ShiAqwBiOiM7XeKx9m61DSjsEafYeBQ"
,"expires_in":43199,"scope":"allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:bids allegro:ap
i:sale:offers:read allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:a
pi:payments:read","allegro_api":true,"jti":"63581e38-ebf9-4b92-ba75-1eaaf43f8017"}.`

2. Minutę później próba użycia nowego tokena skutkuje błędem.

`01/25 21:03:00.750 [WARN ] [1382628] Can't get offer events for allegro user account 'citylook.allegro@gmail.com'. [c.a.s.d.a.event.AllegroEventService]
com.androbit.stocksell.integration.allegro.AllegroApiException: Niepoprawna odpowiedź z Allegro. Kod: 401. Błąd: {"error":"invalid_token","error_description":"Access token expired: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE2NDQ1MjAsInVzZXJfbmFtZSI6IjUwNzY2NDE0IiwianRpIjoiNjM1ODFlMzgtZWJmOS00YjkyLWJhNzUtMWVhYWY0M2Y4MDE3IiwiY2xpZW50X2lkIjoiZTBmYjQ3OTg0NDg5NDVhNmIzNzE4ODVmNjkwNTE5MGUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.sryZb5fDIkzDMFE_pWwPzXKlK5LDNQK19hT9cu0MkCe_EHDdJ5lwEq-7T1-qlfBogtOK_bCeRMUFanwS5MYiqVvO4jUj9dwKbaUXDhRa3esrpaU1KtPLchXd96q2dThULtVjQ22_QWjojzl2TS_ujAI0QUFElUEZQp-35KTT18exjS-XB2KVHY1h7OOAC9VXPxZPCrogaU6Pnefqb7lHhd01XZpFx2K6EOh-iSUux1hVyv233HCQP2vbUSNSbM0guigpFhV8hRjjVJNWJw6giyCDaIrfEk5lVk5XUE52ZoWhe2sI7nJb_XH0d086UakunRuxW2iAkLTHFDi8Q8N65A"}.`

**Comment by PrzemyslawLukanowski** [comment]
Według Twoich danych błąd otrzymałeś po godzinie od wygenerowania tokena (nie po minucie). W naszych logach wygląda to podobnie - przez godzinę token był aktywny i za jego pomocą prawidłowo wykonywałeś żądania, jednak dokładnie o 21:02:00 za pomocą refresh tokena, który jest widoczny w response w zgłoszeniu, Twoja aplikacja wygenerowała nową parę tokenów. Tym sposobem poprzednia para straciła ważność i dlatego o 21:03 otrzymałeś błąd 401.

**Comment by pkoziolandrobit** [comment]
Dziękuję za odpowiedź. 

Czy wygenerowanie nowego tokena unieważnia stary? W tym momencie na koncie 'looklike.allegro@gmail.com' jestem w stanie użyć dwóch tokenów stukając w GET https://api.allegro.pl/me i oba zwracają ten sam wynik.

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE3ODQwODgsInVzZXJfbmFtZSI6Ijg1NjgxMjI2IiwianRpIjoiZjE0MjAxZDMtY2YyYS00NzE2LWJlNjMtMWEwNmIwNGFlZWIwIiwiY2xpZW50X2lkIjoiZTBmYjQ3OTg0NDg5NDVhNmIzNzE4ODVmNjkwNTE5MGUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.569TSSnoDeKOsvNlp4Ndu3OgpThYLGHIab6NBPsBqo9ItQcS42SKGur0kfjl0jwWHh8IwUmQAbMt3yig9m0E8Hi8mhY0peaFv_gHAh1NPMv_nyrVgS4dIoi4jh7e3OJo8JZ8d3lUKcLSyNidH4bbeq8By9qYHhgRxpFuiMxrioRuoFzmPOh1tpXsVj1MeCXVwUb8Nn2gWGNQpf-R34_OqiHDTx408_WuJjdw3-PCkRdy5eDgPVDeHh8513AoCMnwxuinsUa_p1ycagIzP91Fga-3hkohj1_lGcpygeYKjzvGCw1atnvP_YsyxHegBZt0RKtUO2nXF0nA8RGggDiF9A`
oraz
`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTE3ODA1NDEsInVzZXJfbmFtZSI6Ijg1NjgxMjI2IiwianRpIjoiNGRkOWY5NTctMDIwOC00ZTNhLWJkYmUtYThjY2I2ODkxODViIiwiY2xpZW50X2lkIjoiZTBmYjQ3OTg0NDg5NDVhNmIzNzE4ODVmNjkwNTE5MGUiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.jsTm6BoDqdN-mhAOBlWNAxA1XgUqTG0qum628hNOPesakfgFizN3VbVDQ6rERg8RABo0NkliDbvYros34G464mLq8dd3spde0oqzkGLFtkcbT80GkWSdE-sY9NmrhUF1ar3_GJN48_7GzCunNfqES7HfytTfq09Vr19E3MbMcHd_Qj37p62vUfzjfbbLMRNOMjyiYUvMlt8GlyUyeS1H6y9gI0XLCS5MjeCig2Si7hzf12b9q2RhlxXhufU_S8jhdFSouSdAAaBSB9djjnV6h67nH1cyS587JSh23rA1g_fJBauofDLpHOEHQI604ddFR3dRvYQkdF3dtVBoKQGM3A`

**Comment by PrzemyslawLukanowski** [comment]
Stara para straci ważność, jeśli użyjesz otrzymanego wcześniej refresh tokena w celu wygenerowania nowej pary. Możesz mieć kilka działąjących tokenów, jeśli wygenerowałeś je osobno.

**Comment by pkoziolandrobit** [comment]
Rozumiem. Dziękuję za pomoc.
