### ISSUE TITLE
[Sandbox] Odroczona płatność dla Firm - włączenie usługi

### ISSUE THREAD

**Issue by ham3r** [allegro/allegro-api#4116]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

Po złożeniu wniosku na [odroczoną płatność dla firm](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/odroczona-platnosc-dla-firm) następuje weryfikacja danych, która ma trwać do 10 minut. W środowisku _Sandbox_ potwierdzenie weryfikacji danych i włączenie usługi nie następuje.

W związku z tym mam dwa pytania:

1. Co jest potrzebne aby taka usługa została włączona na środowisku _Sandbox_?
2. Czy jest (lub kiedy będzie dostępna) możliwość składania zamówień z odroczoną płatnością na środowisku _Sandbox_?

**Comment by PrzemyslawLukanowski** [comment]
Funkcjonalność na Sandboxie planujemy udostępnić w okolicy drugiej połowy lutego. Wtedy też będziesz mógł ją aktywować przez wspomnianą zakładkę.

**Comment by maczking** [comment]
Czy funkcjonalność jest już dostępna na sandboxie? Klienci dopytują nas o wdrożenie rozwiązań dla tej funkcjonalności, a nie chcemy się brać za wdrażanie tego bez testów :)

**Comment by AureliuszBrussy** [comment]
@maczking wyjaśniam to z odpowiednim zespołem. Wrócę co Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@maczking możesz aktywować odroczoną płatność na Sandbox. Obecnie na koncie musi widnieć NIP, który faktycznie istnieje, a nie jest wygenerowany przez automat. 
Jeżeli ten warunek jest spełniony, to wówczas należy wystąpić z wnioskiem o aktywację [przez stronę WWW](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/odroczona-platnosc-dla-firm).

Proszę następnie wskazać nam login konta, na którym takie działania zostały podjęte.  Wydamy dyspozycję aktywacji płatności odroczonej na tym koncie.

**Comment by kpodemski** [comment]
@AureliuszBrussy 

złożyłem wniosek na sandbox o udostępnienie płatności odroczonej, NIP prawdziwy, wniosek wisi w walidacji, zakładam, że musicie to włączyć ręcznie ale... gdzie wysłać login konta? :-)

**Comment by AureliuszBrussy** [comment]
@kpodemski możesz nam wysłać login konta w tym wątku lub - jeżeli wolisz - w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pamiętaj jednak, żeby w tym drugim przypadku dopisać w zgłoszeniu numer wątku na GitHubie: #4116.

**Comment by kpodemski** [comment]
@AureliuszBrussy to żadna tajemnica, `SuperHiperFirma`, dzięki 👍

**Comment by kpodemski** [comment]
@AureliuszBrussy dostałem potwierdzenie, ale tam jest też jeszcze akceptacja warunków poprzez SMS, który - co pewnie zamierzone - nie wychodzi, jest jakiś kod uniwersalny?

**Comment by AureliuszBrussy** [comment]
@kpodemski odroczona płatność jest już na Twoim koncie w pełni aktywna.

**Comment by maczking** [comment]
@AureliuszBrussy ja też bym prosiła o aktywacje dla konta Mizuhi13 (nip prawdziwy, wniosek złożony). Z góry dziękuje :)

**Comment by AureliuszBrussy** [comment]
@maczking zgłosiłem to do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy usługa będzie już aktywna.

**Comment by AureliuszBrussy** [comment]
@maczking usługa jest już aktywna na wskazanym koncie.

**Comment by kpodemski** [comment]
@AureliuszBrussy czy usługa została wstrzymana dla nowych kont? jeżeli nie to prośba o aktywację dla `SuperHiperKupuje`

**Comment by AureliuszBrussy** [comment]
@kpodemski nie, nie została wstrzymana. Zgłosiłem to do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy usługa będzie już aktywna.

**Comment by AureliuszBrussy** [comment]
@kpodemski Płatność Odroczona jest już na wskazanym koncie aktywna.

**Comment by mroocoo** [comment]
To jeśli można to ja też poproszę o włączenie na kontach:
mrooczek
mroocoo-sprz3

**Comment by AureliuszBrussy** [comment]
@mroocoo zgłosiłem Twoją prośbę do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy usługa będzie już aktywna.

**Comment by alekskuc** [comment]
Dzień dobry, @AureliuszBrussy to idźmy za ciosem i poproszę o aktywację płatności odroczonych na kontach: comarchsandbox oraz ComarchSandbox1

Wnioski złożone, NIPy są ok.

**Comment by AureliuszBrussy** [comment]
@alekskuc  Płatność Odroczona na koncie ComarchSandbox1 jest w trakcie uruchamiania, proszę o jeszcze trochę cierpliwości, natomiast konto o loginie comarchsandbox nie istnieje.

**Comment by alekskuc** [comment]
> @alekskuc Płatność Odroczona na koncie ComarchSandbox1 jest w trakcie uruchamiania, proszę o jeszcze trochę cierpliwości, natomiast konto o loginie comarchsandbox nie istnieje.

Przepraszam @AureliuszBrussy, chodziło o konto comarchesklep

**Comment by AureliuszBrussy** [comment]
@alekskuc dziękuję - i to konto już zgłosiłem. Wrócę z informacją, gdy aktywujemy usługę.

**Comment by alekskuc** [comment]
> @alekskuc dziękuję - i to konto już zgłosiłem. Wrócę z informacją, gdy aktywujemy usługę.

Dzień dobry, @AureliuszBrussy czy uda się aktywować płatności odroczone na kontach comarchesklep i ComarchSandbox1 w najbliższym czasie?

**Comment by AureliuszBrussy** [comment]
@alekskuc @mroocoo przepraszam, natomiast występują chwilowe problem z aktywacją usługi na Sandboxie. Bardzo proszę o jeszcze trochę cierpliwości.

**Comment by maczking** [comment]
@AureliuszBrussy ja bym prosiła jeszcze aktywacje odroczonej płatności dla konta Pawulon1 :)

**Comment by AureliuszBrussy** [comment]
@mroocoo usługa jest aktywna na koncie mrooczek. Na koncie mroocoo-sprz3 jest ten sam NIP, jeżeli chcesz mieć możliwość zakupu, to powinieneś na koncie prowadzić inny NIP, lub podać inne konto (z innym NIPem).

@alekskuc aktywowaliśmy usługę na koncie comarchesklep, pracujemy jeszcze nad aktywacją ComarchSandbox1 - wrócę z informacją, gdy będzie aktywna. 

@maczking zgłosiłem Twoją prośbę do odpowiedniego zespołu. Tutaj także wrócę z odpowiedzią, gdy usługa będzie aktywna.

**Comment by alekskuc** [comment]
Dzień dobry, @AureliuszBrussy czy jest szansa, że dzisiaj będzie aktywacja płatności odroczonych na ComarchSandbox1?

**Comment by AureliuszBrussy** [comment]
@alekskuc pamiętam o tym, wciąż jednak nad tym pracujemy, ze względu na problem techniczny aktywacja wciąż się wydłuża. Wrócę z informacją, jak tylko usługa zostanie aktywowana.

**Comment by AureliuszBrussy** [comment]
@alekskuc usługa jest aktywna na koncie ComarchSandbox1. @maczking aktywna jest również na koncie Pawulon1.

**Comment by alekskuc** [comment]
Dzień dobry, dziękuję za aktywację.

@AureliuszBrussy proszę o informację jak potwierdzić wysyłkę kuriera na sanboxie żeby przeszła płatność i utworzyło się drugie zdarzenie w dzienniku, wtedy przetestuje cały proces.

![image](https://user-images.githubusercontent.com/8465007/114991638-19352e80-9e9a-11eb-899f-7323e1367822.png)

DATA SPRZEDAŻY
15 kwi 2021, 19:31
NUMER ZAMÓWIENIA
db563491-9e0f-11eb-9b38-094e78232463

Płatność
62368e61-9e10-11eb-8890-89264b8b7135

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Na tę chwilę wysyłkę musimy potwierdzić po naszej stronie. Procesujemy jeszcze Twój przypadek, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc Preprocesowaliśmy płatność, powinieneś już otrzymać drugi event RFP.

**Comment by alekskuc** [comment]
> @alekskuc Przeprocesowaliśmy płatność, powinieneś już otrzymać drugi event RFP.

Dziękuję, system zaczytał prawidłowo.
