### ISSUE TITLE
Import towarów z platformy Binagron

### ISSUE THREAD

**Issue by KETRINAPL** [allegro/allegro-api#4117]
Występuje problem: 
 - [ Błąd z dodaniem towaru] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dlaczego nie można importować towaru z platformy Binargon, poprzez API do kategorii Tkaniny na Allegro ?

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się proszę w tym temacie z autorem oprogramowania. Niestety nie znamy platformy Binagron i nie wiemy, jak korzysta z naszego API.

**Comment by KETRINAPL** [comment]
A kto jest autorem, jak można do niego napisać ?

**Comment by PrzemyslawLukanowski** [comment]
Chodzi o twórców aplikacji Binargon. Sprawdź, czy na swojej stronie internetowej nie mają odpowiedniej zakładki z danymi do kontaktu.

**Comment by KETRINAPL** [comment]
Dziękuję bardzo za informacje.

**Comment by KETRINAPL** [comment]
Dzień dobry. Binargon wysłał taki kod błędu. Co to znaczy ?
----------------------------------------------------------------------

In category 258939 ("Tkaniny") we get this response (productCreationEnabled is false):

{

"id": "258939",

"name": "Tkaniny",

"parent": {

"id": "76713"

},

"leaf": true,

"options": {

"variantsByColorPatternAllowed": true,

"advertisement": false,

"advertisementPriceOptional": false,

"offersWithProductPublicationEnabled": false,

"productCreationEnabled": false,

"productEANRequired": false,

"customParametersEnabled": true

}

}



When we try to import products into this category (258939), we get this error:

{

'code' => 'ConstraintViolationException.RequireEnabledCategory',

'message' => 'An error has occurred',

'details' => NULL,

'path' => 'category.id',

'userMessage' => 'Dodawanie produktów do kategorii nie jest możliwe.',

}

**Comment by PrzemyslawLukanowski** [comment]
Komunikat oznacza, że w danej kategorii nie możesz tworzyć produktu. Możesz wystawić ofertę, ale bez przypisywania do niej produktu.
