### ISSUE TITLE
Problem z dodaniem propozycji produktu

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4118]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

[sale-products.txt](https://github.com/allegro/allegro-api/files/5878529/sale-products.txt)
[product-proposals.txt](https://github.com/allegro/allegro-api/files/5878530/product-proposals.txt)

Witam, mamy problem z dodaniem propozycji produktu za pomocą zasobu sale/product-proposals. Na wysłany request otrzymujemy informację zwrotną, że taki produkt już istnieje. Jednak gdy za pomocą zasobu sale/products próbujemy wyszukać ean proponowanego produktu to nie zwraca nam żadnych produktów.
Dołączam request i response tych dwóch zasobów.

**Comment by PrzemyslawLukanowski** [comment]
Produkt o tym numerze EAN istnieje w naszej bazie jako product.id 331e35a3-72f0-49ac-8d49-8262793f991a. Opisany przez Ciebie problem w zgłoszeniu przekazałem do odpowiedniego zespołu.

**Comment by mindc** [comment]
Problem wygląda bardzo podobnie do #4070
Został on już rozwiązany, ale być może problem jest szerszy i wykracza poza wskazane produkty.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nie zwróciliśmy produktu przez wyszukiwarkę, ponieważ produkt nie ma uzupełnionych żadnych parametrów prócz numeru EAN. @fabianCyfran Jeśli otrzymasz odpowiedź 409 przy tworzeniu produktu, skorzystaj z adresu, który otrzymasz w nagłówku Location - znajdziesz tam ID produktu z naszej bazy o podobnych danych.
