### ISSUE TITLE
Błąd przy odpytywaniu o utworzenie przesyłki WZA

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4119]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id=babd34b22e7c59b5

Dziś podczas odpytywania środowiska testowego o status utworzenia przesyłki otrzymuję błąd, którego wcześniej nie widziałem:

Adres: "https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/b839b142-923f-453e-8689-377be4846a8b"

Content: {"id":"b839b142-923f-453e-8689-377be4846a8b","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Waiting for status update","details":null,"path":"/parcel-management/parcel-create-commands/{commandId}","userMessage":"Trwa oczekiwanie na aktualizację statusu"}]}

Jak mam interpretować ten błąd?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Treść komunikatu jest myląca, wynik tego polecenia się nie zmieni - musisz jeszcze raz utworzyć paczkę. Zmienimy odpowiednio komunikat, aby był precyzyjny.
