### ISSUE TITLE
GET /sale/offers/{id} nie znajduje aukcji

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#412]
Dzień Dobry,
wykonuję zapytanie GET do https://api.allegro.pl/sale/offers/{id} stosujac access token konta będącego wystawcą aukcji i otrzymuję następującą odpowiedz:

(    [errors] => Array
        (
            [0] => Array
                (
                    [code] => NOT_FOUND
                    [message] => Not Found
                    [details] =>
                    [path] => /sale/offers/<tutaj_id_aukcji>
                    [userMessage] =>
                )
        )
)

Aukcja istnieje w Allegro, jest typu Kup teraz i można na niej normalnie kupować.

Do zapytania używam następujących nagłówków:
'Authorization: Bearer <tutaj_jest_moj_access_token>',
'Accept: application/vnd.allegro.beta.v1+json'

Proszę o pomoc. Sprawa zgłoszona również przez email Ticket#1249592309 gdzie podałem ID przedmiotu i nazwę konta.

**Comment by KrzysztofLukanowski** [comment]
Dzień dobry - w tickecie nie podałeś wartości tokena. Możliwe, że podajesz nieprawidłowy token.

**Comment by amarel123** [comment]
@KrzysztofLukanowski dosłałem przed chwilą access token na maila odpowiadając na potwierdzenie przyjęcia zgłoszenia.

**Comment by amarel123** [comment]
Powinien być dobry bo przy jego pomocy działa mi odpytywanie /offers/listing.

**Comment by amarel123** [comment]
Dosłałem nowy access token na maila, testowałem czy po generacji nowego tokena coś się zmieni, ale nadal otrzymuję not found.

**Comment by KrzysztofLukanowski** [comment]
Podeślij proszę pełen request w tickecie, np. cURL. Sprawdziłem działanie i wszystko jest ok, więc błąd leży najprawdopodobniej w zapisie zapytania.

**Comment by amarel123** [comment]
@KrzysztofLukanowski okazuje się, że problem nie jest u mnie, tylko po Państwa stronie. Czy sprawdził Pan działanie używając mojego access tokena na tej konkretnej aukcji, którą podałem w mailu czy wykonał tylko pobieżnie testy (teraz proszę nie sprawdzać na tamtej bo ją poprawiłem, nowe ID podałem w nowym mailu)? Wykonałem testy na nowych aukcjach allegro (zapytanie identyczne tylko ID w linku inne) i wszystko działa jak należy co dowodzi, że sposób implementacji jest prawidłowy. Natomiast dla starszych aukcji to nie działa. Teraz wysłałem odpowiedź do ticketa (z nowym access tokenem) gdzie podałem dwa różne ID aukcji, dla jednego działa, dla drugiego nie. Stare aukcje są to tak zwane oferty "ze starym opisem", Allegro listuje mi je w panelu jako wymagające poprawy. Wielu klientów je posiada, jak więc je obsłużyć stosując ten endpoint? Co więcej, inny endpoint /offers/listings pokazuje część takich aukcji (nie wszystkie, ale znaczną część tak, np. teraz w mailu taką podałem) w wynikach, więc mamy tu rozbieżność w endpointach REST API - jedne widzą te aukcje, inne nie, co sprawia, że REST api jest beużyteczne kiedy część endpointów je pokazuje, a część nie i prowadzi to do konfliktów w moim systemie.

**Comment by amarel123** [comment]
@KrzysztofLukanowski jak mam teraz pracować na danych z API kiedy /offers/listingw losowo widzi część takich aukcji?

**Comment by KrzysztofLukanowski** [comment]
Tak jak zauważyłeś,  wkrótce wszystkie oferty będą miały nowy opis.
