### ISSUE TITLE
zmiana cen w aukcjach zamkniętych

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4120]
Dziń dobry, czy istnieje moŻliwość zmiany cen w aukcjach zamknietych - ze statusem publication->status->ENDED ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz to zrobić zarówno przez [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT), zmieniając cenę w polu **sellingMode.price.amount**, jak i za pomocą [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT).

**Comment by syw2020xd** [comment]
ok dziekuję, sprawdzę, bo coś nie poszło za pierwszym razem

**Comment by syw2020xd** [comment]
działa, dziekuję
