### ISSUE TITLE
Błąd przy tworzeniu paczki

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4121]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

CommandId: 5036a68a-3e62-4ed0-8779-2f62313aa7a4

Tworząc przesyłkę otrzymujemy błąd na środowisku produkcyjnym:  "Processing error | Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"

Co jest błędem?

**Comment by PrzemyslawLukanowski** [comment]
Nie utworzyliśmy przesyłki, ponieważ konto zostało zablokowane przez przewoźnika. Skontaktuj się w tej sprawie ze swoim opiekunem handlowym w InPost. W najbliższym czasie poprawimy treść komunikatu.
