### ISSUE TITLE
Błędna wartość publication.endingAt zasobu GET /offers/listing

### ISSUE THREAD

**Issue by k0rba** [allegro/allegro-api#4122]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Zdarza się, że przy wywołaniu GET /offers/listing otrzymuję błędną wartość pola publication.endingAt. Przykłady:
Oferta 10154863599: 2021-02-14T12:15:02.000Z (powinno być: 2021-01-31T12:15:02.000Z, różnica 1209600 sekund)
10163592589: 2021-02-21T09:07:22.000Z (2021-01-29T19:54:00.000Z, 1948402)
10158540375: 2021-01-28T19:18:00.000Z (2021-02-04T19:18:00.000Z, -604800)
10143925495: 2021-01-26T21:20:00.000Z (2021-01-26T19:31:00.000Z, 6540)
10136079224: 2021-01-31T22:59:56.000Z (2021-01-26T19:50:00.000Z, 443396)
10151000491: 2021-01-27T03:42:49.000Z (2021-01-28T17:47:00.000Z, -137051)

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu. Wyszukałem podane oferty bezpośrednio na podstawie frazy i dla każdego z przypadków otrzymałem poprawną datę w polu publication.endingAt. Prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz, że dane dotyczą wątku #4122 na GitHubie. Zweryfikujemy Twój przypadek.

**Comment by k0rba** [comment]
Nic dziwnego. Pewnie próbował Pan odpytać każdą z ofert raz, a w moim opisie wyrażeniem kluczowym jest "zdarza się". Uściślę więc: około 2-3 razy na każde 10 000 zapytań. Przykładowe zapisy wysłałem przez podany formularz.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady. Przekazałem je do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy uda nam się ustalić więcej informacji.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy odpowiednią poprawkę, problem nie powinien już występować.
