### ISSUE TITLE
Błąd przy tworzeniu przesyłki - WZA

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4123]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

CommandId: 375119a5-e1a8-4aad-8b1c-e818fb55e9d5

Ponownie występuje problem z tworzeniem przesyłki. Wasze API zwróciło ogólne informacje: Processing error	| Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem

Co jest przyczyną błędu?

**Comment by PrzemyslawLukanowski** [comment]
Wybrany paczkomat nie miał możliwości "tworzenia przesyłki", która miała by być w nim umieszczona. Prawdopodobnie informacja ta była wynikiem dezaktywacji paczkomatu. W tym momencie problem już nie występuje, paczkomat jest dostępny i można do niego tworzyć przesyłki.
