### ISSUE TITLE
"Invalid offer duration limit" dla czasu trwania aukcji "PT24H" oraz "P1D"

### ISSUE THREAD

**Issue by robertjankiewiczcontelizer** [allegro/allegro-api#4124]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Trace-id: 434678626bcb697f, f938c47ea4bbdb63 

Gdy próbuję utworzyć szkice oferty, w których czas trwania aukcji (duration) ustawiony jest na "P1D" lub "PT24H" w odpowiedzi otrzymuję błąd walidacji: "Invalid offer duration limit".

**Comment by PrzemyslawLukanowski** [comment]
Taki czas trwania możesz ustawić tylko dla formatu `sellingMode.format: AUCTION`. W Twoim przypadku wybierasz wartość "BUY_NOW". Poniżej znajdziesz wszystkie dostępne wartości, które wymieniliśmy w [naszym poradniku](https://developer.allegro.pl/sale/#uzupe%c5%82nij-draft-oferty):

```
"duration": null,                                -- wymagane, czas trwania oferty, dostępne
                                                    wartości: null (do wyczerpania zapasów),
                                                    P3D (3 dni); P5D (5 dni); P7D (7 dni);
                                                    P10D (10 dni); P20D (20 dni); P30D (30 dni), czas
                                                    możesz podać też w godzinach - np.: P72H (3 dni).
                                                    Dla oferty typu AUCTION (licytacja) nie możesz
                                                    podać wartości null i dostępne są wartości:
                                                    P1D (1 dzień); P3D (3 dni); P5D (5 dni); P7D (7 dni);
                                                    P10D (10 dni); Natomiast dla ofert typu
                                                    ADVERTISMENT (ogłoszenia) dostępne są wartości:
                                                    null (na czas nieokreślony - opłaty naliczane co 10 dni);
                                                    P10D (10 dni); P20D (20 dni); P30D (30 dni)

```

**Comment by robertjankiewiczcontelizer** [comment]
Dzięki za szybką odpowiedź, oczywiście nie jest to w takim razie błąd API, choć może przydałby się nieco bardziej szczegółowy komunikat błędu. Pozdrawiam.
