### ISSUE TITLE
Niepoprawna wymagana wartość parametru

### ISSUE THREAD

**Issue by dwalczyk** [allegro/allegro-api#4125]
Występuje problem:
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Występuje problem z produktem - Spray do szyby prysznica na kamień Kalkloser 750 (ean: 4260145996491).
Produkt ma u was bazie podaną markę jako "Inna" chociaż powinna być "PowerWash", która jest dostępna do wyboru w tej kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację. Przekazałem ją do odpowiedniego zespołu. Wrócę z informacją, gdy wyedytujemy dane w produkcie.

**Comment by PrzemyslawLukanowski** [comment]
Zmieniliśmy wartość w parametrze na poprawną.
