### ISSUE TITLE
/pricing/fee-preview POST 503 ERROR

### ISSUE THREAD

**Issue by brokieb** [allegro/allegro-api#4126]
Witam, mam problem z połączeniem POST z API. Przy próbie wysłania zapytania na /pricing/fee-preview otrzymuję opisany błąd: 

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => SERVICE_UNAVAILABLE
                    [message] => Service unavailable.
                    [details] => 
                    [path] => 
                    [userMessage] => Service unavailable. Please try again in a few minutes.
               )

       )

)

Mój kod wygląda tak:

`function restPost($event,$token){
    $ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://api.allegro.pl".$event);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$headers = array();
$headers[] = 'Authorization: Bearer '.$token;
$headers[] = 'Accept: application/vnd.allegro.public.v1+json';
$headers[] = 'Content-Type: application/vnd.allegro.public.v1+json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_POSTFIELDS, '
{
    "offer":{
        "id": "257931"
    },
    "duration":"PT720H",
    "type":"SHOP",
    "unitPrice":131
}

');
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
        $answer = json_decode($mainResult);
        return $answer;
}
restPost("/pricing/fee-preview",$allegro_token);
`

Jakieś pomysły co mogę robić nie tak?

**Comment by PrzemyslawLukanowski** [comment]
Pierwszy problem to brak pola **category.id** w **offer**, id kategorii przekazujesz bezpośrednio dla oferty. Brakuje także jednego z obowiązkowych pól **quantity** lub **soldQuanity**, jeśli offer.type nie jest równe wartości "advertisement"
Poniżej wklejam przykładową prawidłową strukturę:

```
 {
 	"offer": {
 		"category": {
 			"id": "257931"
 		},
 		"duration": "PT720H",
 		"type": "SHOP",
 		"unitPrice": 131
 	}
 }
```

Jeśli po poprawkach nadal będziesz otrzymywać 503, upewnij się, że korzystasz z tokena wygenerowanego w drodze autoryzacji [code](https://developer.allegro.pl/auth/#app)lub [device ](https://developer.allegro.pl/auth/#DeviceFlow) (dla client_credentials zwrócimy błąd).
