### ISSUE TITLE
Niedziałający Import w WooCommerce

### ISSUE THREAD

**Issue by DudaMarcin** [allegro/allegro-api#4127]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x ] inny

:beetle: **Opis**

Z przyjemnością, jeśli powiecie jak je znaleźć, jeśli w ogóle jestem w stanie, korzystając ze wtyczki WP Desk.

Import aukcji do woocommerce nie działa.  Serwer zwraca tylko błąd 500 co daje mi tyle info co nic... Ostatnim razem też miałem ten problem, potem zaczęło znów działać i teraz znów jest ten problem. Trochę to wygląda jak ruletka, kiedy mogę pobrać dane z allegro, a kiedy nie 🤷‍♂️

Tutaj wysyłam to, co widzę w konsoli DevTools , z zamazanym "security" tak na wszelki wypadek.
![Zrzut ekranu](https://user-images.githubusercontent.com/16838723/106354712-1c396d80-62f4-11eb-92c0-918d05264152.png)

**Comment by PrzemyslawLukanowski** [comment]
Nie wiemy, w jaki dokładnie sposób działa zewnętrzne oprogramowanie, z którego korzystasz, dlatego ilość przesłanych przez Ciebie informacji jest zbyt mała, abyśmy mogli stwierdzić, czy powodem problemu są błędy naszego API. Prześlij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) przykładowy request do naszego API (wraz z response) w formacie cURL. Pozwoli nam to zweryfikować opisaną sytuację. W zgłoszeniu dopisz, że dane dotyczą wątku GitHub #4127.
