### ISSUE TITLE
AUTHORIZATIONS dla getCompatibilityListSuggestion

### ISSUE THREAD

**Issue by zybirt** [allegro/allegro-api#4128]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

W poradniku: "Jak zarządzać sekcją Pasuje do (compatibilityList) w ofercie" 
Link: https://developer.allegro.pl/compatibility_list/
W sekcji: "Jak wyszukać sugerowaną sekcję compatibilityList"
Napisane jest: "Sugestie tworzymy na podstawie list komptybilności **ofert innych sprzedających**"
Za pomocą zasobu: https://developer.allegro.pl/documentation/#operation/getCompatibilityListSuggestion
Typ autoryzacji: AUTHORIZATIONS: bearer-token-for-user

Zasób posiada atrybut AUTHORIZATIONS: bearer-token-for-user czyli nie jest publiczny. Uniemożliwia to pobranie list kompatybilności za pomocą identyfikatora offer.id ofert innych sprzedających. Co jest sprzeczne z informacjami podanymi w poradniku. 
Proszę o dodanie AUTHORIZATIONS: bearer-token-for-application 

Request:
https://api.allegro.pl/sale/compatibility-list-suggestions?offer.id=9436958667

Response:
{
    "errors": [
        {
            "code": "NOT_FOUND",
            "message": "Oferta o wskazanym identyfikatorze nie istnieje.",
            "details": null,
            "path": "/sale/compatibility-list-suggestions",
            "userMessage": "Oferta o wskazanym identyfikatorze nie istnieje."
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
Powyższy zapis jest poprawny - możesz pobrać sugerowaną sekcję 'Pasuje do' dla Twoich ofert. Wyniki, które zwrócimy w odpowiedzi, **tworzymy na podstawie list kompatybilności ofert innych sprzedających**. Nie wskazujemy tutaj, że możesz pobrać bezpośrednio sekcję 'Pasuje do' z ofertt innych sprzedających
