### ISSUE TITLE
Zasób /sale/products/{productId} nie zwraca opisu

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4129]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

mamy problem z zasobem /sale/products/{productId}. Zgodnie z dokumentacją, w odpowiedzi powinniśmy otrzymać opis. Produkt na stronie https://allegro.pl/produkt/a8e89f22-5842-4907-8554-781cbaa4b3bc posiada opis, jednak obiekt pobrany przez api go nie zawiera. 

Dołączam request i response tego zasobu: [product.txt](https://github.com/allegro/allegro-api/files/5902545/product.txt)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie, problem z opisem przekazałem do właściwego zespołu.

**Comment by fabianCyfran** [comment]
Czy wiadomo już, kiedy to zgłoszenie będzie zweryfikowane?

**Comment by MaciejFrackowiak** [comment]
Pracujemy nad globalnym rozwiązaniem, aby zwracać opisy produktów - i tu nasza prośba o chwilę cierpliwości.

**Comment by MaciejFrackowiak** [comment]
Zmiana wdrożona - w odpowiedzi dla zasobu zwracamy już opisy.
