### ISSUE TITLE
Przelew tradycyjny

### ISSUE THREAD

**Issue by mariusz-charkot** [allegro/allegro-api#413]
Czy taka metoda płantości jak przelew tradycyjny (płatnosć bezpośrednio na rachunek bankowy sprzedawcy) jest jeszcze wspierana przez Allegro? Czy da się tworzyć aukcje z tego typu płatnoscią?

**Comment by KrzysztofLukanowski** [comment]
Nie. Nie obsługujemy już przelewów zwykłych poza Allegro Finanse. W ramach Allegro Finanse klienci mogą wybrać płatność przelewem tradycyjnym, wówczas wpłata jest procesowana przez PayU lub Przelewy24.

**Comment by mariusz-charkot** [comment]
Zatem jak sprzedawcy osiągają taki efekt? https://image.prntscr.com/image/x6QdW2-ESk601I0BqhOMKg.png

**Comment by TimothyKoval** [comment]
fid 14, pierwszy bit

`Zwykły przelew|-|-|-|Inne rodzaje płatności|Wystawiam faktury VAT|Wystawiam faktury VAT-marża|Wystawiam faktury bez VAT`

**Comment by mariusz-charkot** [comment]
@KrzysztofLukanowski zatem jakie jest oficjalne stanowisko? Czy ta opcja będzie dostępna? Zmieniamy mechanizm wystawiania ofert w naszej aplikacji i nie wiem czy mamy zostawić tą opcję.

**Comment by KrzysztofLukanowski** [comment]
@mariusz-charkot ta opcja jest dostępna w ramach ofert, które trwają od miesięcy w formacie "do wyczerpania zapasów". W maju [informowaliśmy](https://allegro.pl/webapi/news.php/page,2#news_100610) o zmianach w WebAPI.

**Comment by kormichu** [comment]
@KrzysztofLukanowski informowaliście o usunięciu numerów bankowych z FID'ów, a nie o usunięciu opcji wystawienia aukcji z możliwością zwykłego przelewu który definiuje się w FID 14 na pierwszym bicie tak jak napisał @TimothyKoval .  Z tego co widzę zarówno na produkcji jak i na sandboxie opcja ta jest dostępna. Z kolei na REST API nie doszukałem się takiej opcji

**Comment by KrzysztofLukanowski** [comment]
Przelew zwykły jest niedostępny w formularzu wystawiania, API dostosujemy wkrótce, damy znać.
