### ISSUE TITLE
403 error when trying GET /sale/offers/{id}

### ISSUE THREAD

**Issue by hikopol** [allegro/allegro-api#4133]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Good day.
Im reciving 403 error while trying to collect information of a particular offer from https://api.allegro.pl.allegrosandbox.pl
by trying GET /sale/offers/{id}.
I use user-bearer-token type of authorization so such rights of accesing to resourse have to be granted, following by your api documentation https://developer.allegro.pl/documentation/#operation/getOfferUsingGET
My user id: 93966938, My app client id: fe28f164d22942ef88372b3b80ef4cb0.

error looks like:
403 Forbidden {
  errors: [
    {
      code: 'FORBIDDEN',
      message: 'Forbidden',
      details: null,
      path: '/sale/offers/7679201042',
      userMessage: null
    }
  ]

**Comment by MaciejFrackowiak** [comment]
Offer 7679201042 does not belong to user 93966938 - you can retrieve via [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) only offers which belong to you.

**Comment by hikopol** [comment]
So as i undarstand, if offer isnt belong to your account you can not acces to detail info via  GET /sale/offers/{offerId}.
Is api support any other ways to get detail info of represented offers in category?
Thanks for your answer.

**Comment by MaciejFrackowiak** [comment]
No, detailed information about offer is available only for its seller.

**Comment by hikopol** [comment]
Maybe you have some partnership's of other type of relations?
So we want to create api that supports customers to buy goods from allegro.pl using our site. But cannot without such info like descripion of product, delivery details etc.
Is it posible for us to create partnership site like  https://motopoland.com.ua/detail/10186521704/ that support serhing products, and delivery from poland?

**Comment by MaciejFrackowiak** [comment]
No, according to [our previous news](https://github.com/allegro/allegro-api/issues/3661) we will not provide that kind of resources in REST API.

**Comment by hikopol** [comment]
So we want to create api that supports customers to buy goods from allegro.pl using our site. But cannot without such info like descripion of product, delivery details etc.
Is it posible for us to create partnership site like  https://motopoland.com.ua/detail/10186521704/ that support searhing products and view product details?

**Comment by MaciejFrackowiak** [comment]
No, because we do not allow to offer Allegro goods on third party sites.

**Comment by AgentosUA** [comment]
So, how https://motopoland.com.ua/detail/10186521704/ works then? As i can see, they are using your API for showing allegro products, but via motopoland.com.ua website.

**Comment by MaciejFrackowiak** [comment]
As I wrote before - there is no public API to show offers details, so they have to use /offers/listing resource.

**Comment by AgentosUA** [comment]
There no use for /offers/listing when you need details info about product. And somehow https://motopoland.com.ua/detail/10186521704/ got this info and if there no public API to show offers details - it looks strange.

**Comment by MaciejFrackowiak** [comment]
We do not provide any tools and support websites which copy Allegro content.
