### ISSUE TITLE
Tworzenie drafta, nowy opis "Description images are not valid."

### ISSUE THREAD

**Issue by kazmij** [allegro/allegro-api#4134]
Odnośnie opisu: https://developer.allegro.pl/new_desc/#03
Jak mam dodać w opisie te obazki w końcu, dodaję wszystkie url do pola "images", w opisie według powyższej dokumentacji nie można dodać linku.
Skąd mam wiedzieć, jakie to zdjęcie PHOTO_FID_16?

Gdy dodaję to zmiast linka (zakładam, ze to pierwsze dodane zdjęcie), to dostaję taki sam błąd:
**Description images are not valid**
Jak zatem powinienm dodać opis z orbazekim poprzez REST API?

Gdy pobieram drafta, to w type "IMAGE" i tak mam link zamiast nazwy pola, natomiast co muszę wyslać w końcu i jak to się ma do samego zdjęcia: PHOTO_FID_XX -> image url

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z aktualnej wersji [poradnika](https://developer.allegro.pl/sale/), gdzie krok po kroku opisaliśmy sposób przygotowania drafta oferty. Zdjęcia należy najpierw wysłać na nasz serwer, a w opisie oferty wykorzystywać adresy URL otrzymane po uploadzie plików.
