### ISSUE TITLE
Czy jest awaria w  /sale/offers?

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4135]
Dzień dobry, czy coś dzisiaj się zmieniło? Nie możemy ściągnąć listy produktów  we własciwym czasie wg: 
/sale/offers?limit='.$limit.'&offset='.$offset .'&publication.status=ACTIVE'

zwykle trwało to około 10 - 15 sekund dla 5000 aukcji , a teraz mieli i się przewraca ...

**Comment by MaciejFrackowiak** [comment]
Nie otrzymaliśmy podobnych zgłoszeń, nie widzę też żadnych nieprawidłowości. Proszę podaj przykładowe trace-id takiego wywołania.

**Comment by syw2020xd** [comment]
wyjasniło się - po stronie aplikacji
