### ISSUE TITLE
Brak kodu błędu ConstraintViolationException.ValidSeller PUT /sale/offers/

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#4138]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym

:beetle: **Opis**

Dzień dobry, dlaczego w przypadku próby edycji oferty przez PUT /sale/offers/ nie ma kodu błędu ConstraintViolationException.ValidSeller skoro z komunikatów wynika, że jest zablokowane konto?

`
  "TraceId": "d07efa2e8cf9f9b9",
  "StatusCode": 422,
  "Message": "{\"errors\":[{\"code\":\"VALIDATION_ERROR\",\"message\":\"Uzupełnij parametry obowiązkowe: Kod producenta, Model.\",\"details\":\"\",\"path\":\"\",\"userMessage\":\"Uzupełnij parametry obowiązkowe: Kod producenta, Model.\"},{\"code\":\"VALIDATION_ERROR\",\"message\":\"You don't have the required permissions to publish offer (sell blocked).\",\"details\":\"\",\"path\":\"\",\"userMessage\":\"Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).\"}]}"
`

W raportach jest zwracany zwracany kod ConstraintViolationException.ValidSeller dzięki czemu można jednoznacznie zidentyfikować blokadę konta.

`{"RaportZlecenia":{"Nr":"9c80ca52-3afe-4f9a-90b9-b5f69c5ed164","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2020-06-10T13:16:06.052Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"8129146515"},"ScheduledAt":"2020-06-10T13:16:05.739Z","Status":"FAIL","Errors":[{"Code":"ConstraintViolationException.HasAllRequiredAttributes","Details":null,"Message":"Uzupełnij parametry obowiązkowe: Marka, Kod produktu.","Path":"attributes","UserMessage":"Uzupełnij parametry obowiązkowe: Marka, Kod produktu."},{"Code":"ConstraintViolationException.ValidSeller","Details":null,"Message":"Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane).","Path":"seller","UserMessage":"Nie masz wymaganych uprawnień, aby wystawić ofertę (konto użytkownika zablokowane)."}]}]},"Validation":null,"Exception":null,"TraceId":"3c2ec0a3e30f78e7","Error":false,"StatusCode":200,"Message":null}}}`

Proszę o zwracanie kodu błędu ConstraintViolationException.ValidSeller dla metody PUT /sale/offers/

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie. Przyjrzymy się temu wraz z zespołami odpowiedzialnymi za te zasoby, które podejście powinno być dalej rozpowszechniane dla endpointów.
