### ISSUE TITLE
Błąd przy pobieraniu /sale/product-offers/'.$auctionId

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4140]
Dzień dobry, proszę o wskazówkę, w jaki sposób mozna poradzic sobie przy edycji oferty. 
Wywołuję przez :  application/vnd.allegro.beta.v2+json 
Próbowałem też: application/vnd.allegro.public.v1+json
 
"{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}"

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id, dla którego otrzymałeś powyższy błąd.
Zgodnie z [komunikatem](https://github.com/allegro/allegro-api/issues/3927) obecnie dla zasobu PATCH /sale/product-offers/{offerId} należy przekazywać nagłówek “application/vnd.allegro.beta.v2+json”.

**Comment by syw2020xd** [comment]
Dziekuje, faktycznie brakowało mi ustawien v2 w jednym nagłówku.
