### ISSUE TITLE
query to api-call question

### ISSUE THREAD

**Issue by sfxter** [allegro/allegro-api#4141]
Is there an easy way to transform browser http search query to api-call query? 
For example, I would like to get the same list (12 filtered offers) using api, as I would get following this link 

https://allegro.pl/kategoria/laptopy-apple-77915?string=macbook%20pro%2015&offerTypeBuyNow=1&price_from=3000&price_to=4000&wielkosc-pamieci-ram=8%20GB&bmatch=cl-cx210105ap-enomswp-diwebp-ele-1-3-0129

/offers/listing does not provide same filters as used in the http querry...
Thank you in advance.

**Comment by MaciejFrackowiak** [comment]
It is possible - [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) has dynamic filters, so you can filter and customize your search results to find exactly what you need by applying filters ids and their dictionary values to query according to the flowing pattern: id=value. 

For example, your query in API: GET /offers/listing?phrase=macbook pro 15&category.id=77915&sellingMode.format=BUY_NOW&price.from=3000&price.to=4000&parameter.200941=200941_2185

Please, look into [our tutorial](https://developer.allegro.pl/en/listing/) where we described how to search and browse offers.

**Comment by sfxter** [comment]
Thank you for your reply. 
Please correct me if I am wrong, but as I understand, there is no direct way to convert http query to api call query. To do that, I would have to manually translate between http query params and api params, for example filters in category. I would need to find which parameter.ID is "wielkost-pamieci-ram" and then which value ID is "8gb" ?

**Comment by MaciejFrackowiak** [comment]
Yes, indeed. There is no 1:1 reference HTTP to API.
