### ISSUE TITLE
"Allegro Ceny" i obniżona cena podana w /sale/offer

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4142]
W odpowiedzi na zgłoszenie #4112 dostaliśmy informację, że mimo uczestnictwa oferty w "Allegro Ceny" otrzymamy w GET /sale/offers **oryginalną cenę (nieobniżoną)**. Jednak wygląda na to, że jest inaczej. Sprawdziłem jedną ofertę, która ma obniżoną cenę z 49,01 na 48,01 i /sale/offer **zwraca cenę obniżoną**. 

Trace-id: eab1b331a416e15a

Czy to błąd tymczasowy czy tak zostanie na zawsze?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
W przytoczonym przez Ciebie poście już zamieściliśmy korektę informacji - w GET /sale/offers ujrzysz obniżoną cenę, taka jak jest dostępna dla klientów serwisu.
