### ISSUE TITLE
Błąd produktu Gates KP15682XS-2/5414465098512

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#4146]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Produkt firmy Gates `KP15682XS-2` (EAN:`5414465098512`) jest to Pompa wodna + zestaw paska rozrządu

Przy wyszukiwaniu produktu po frazie `KP15682XS-2` otrzymuję prawidłową nazwę, EAN oraz kategorię `50844`, czyli _Motoryzacja>Części samochodowe>Silniki i osprzęt>Rozrząd>Kompletne rozrządy_

Jednak przy wyszukiwaniu po EAN:`5414465098512` otrzymuję jako nazwę jedynie "Gates KP15682XS-2", oraz niepoprawną kategorię `50884`, czyli _Motoryzacja>Części samochodowe>Układ napędowy>Sprzęgła>Komplety sprzęgieł_

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem Twoją obserwację i:

1) dla frazy "KP15682XS-2" otrzymujemy produkt o id="e5af628d-1252-4bf7-934e-2664bbd5a5a8" - ten produkt nie ma przypisanego EAN w naszej bazie;

2) dla EAN=5414465098512 zwracamy produkt o id="aeb3b850-8636-43c4-b18b-ab83df5867cd" - ten produkt ma EAN w naszej bazie i stąd występuje w wynikach wyszukiwania po EAN.

Jeżeli uważasz, że dane produktów są niewłaściwe, proszę skorzystaj z formularza https://allegro.pl/offer/product/report/{productId} i zgłoś swoje uwagi.
