### ISSUE TITLE
Zakończone oferty w sale/offers/unfilled-parameters

### ISSUE THREAD

**Issue by potejtooo** [allegro/allegro-api#4147]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry. Mam problem z zasobem sale/offers/unfilled-parameters, który zwraca aukcje zakończone. Większa część zwracanych aukcji już dawno nie istnieje, a dokładnie 6 na 10.

trace-id 5bce229d72d635c8

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie, problem przekazałem już do właściwego zespołu.

**Comment by MaciejFrackowiak** [comment]
Dane zostały odświeżone, obecnie zasób zwraca już tylko aktualne oferty.

**Comment by potejtooo** [comment]
Problem nadal występuje 
trace-id 1c334a83c46729cc
numery aukcji: 10577762692, 10577981776

**Comment by MaciejFrackowiak** [comment]
Wymienionych przez Ciebie ofert nie ma już na zwracanej liście. Dane są procesowane raz dziennie, zatem może się zdarzyć sytuacja, że zakończona w danym dniu oferta będzie widoczna, jednak po nocnym odświeżeniu danych nie będzie już widoczna na liście wyników.
