### ISSUE TITLE
[WebAPI] Pobieranie informacji o atrybutach zamówionego produktu.

### ISSUE THREAD

**Issue by krawiec1011** [allegro/allegro-api#4148]
Czy można pobrać przez API informacje o atrybutach(rozmiar, kolor) zamówionego produktu ?

**Comment by MaciejFrackowiak** [comment]
Jako sprzedający pobierasz dane o zamówieniu zasobem [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), gdzie w lineItems otrzymujesz składowe zamówienia, w tym m.in. numer oferty - wystarczy, że skorzystasz z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) i poznasz dokładne parametry tej konkretnej oferty.

Dodam, że WebAPI zostało już [wyłączone w październiku 2020](https://github.com/allegro/allegro-api/issues/3814).

**Comment by krawiec1011** [comment]
Mój błąd, chodzi o Allegro REST API
Numer oferty odnosi się do konkretnego zamówionego przedmiotu ? Jeżeli klient zamówił dwie koszulki w dwóch różnych rozmiarach to każda będzie miała swój numer oferty?  Czy jest to jeden numer i  GET /sale/offers/{offerId} zwróci mi  wszystkie możliwe warianty nie ten konkretny który zamówił klient?

**Comment by MaciejFrackowiak** [comment]
Jeżeli wystawiasz - jedna koszulka, jeden rozmiar = jedna oferta, to nie będzie tu żadnego problemu, ponieważ w lineItems otrzymasz osobne numery ofert dla koszulek z odrębnymi rozmiarami.

**Comment by krawiec1011** [comment]
Dzięki, to rozwiązuje mój problem.

**Comment by krawiec1011** [comment]
Niestety wracam z problemem. 
Sytuacja wygląda tak że mam sprzedawane koszulki. 
Kilka ofert połączonych jest przez parametr kolor i rozmiar w wielowariantowość.

Chciałbym pobrać do Swojej aplikacji tylko te dwa parametry, czyli  w jakim rozmiarze i kolorze klient kupił koszulkę. 

Pobieram dane o zamówieniu wykorzystując GET /order/checkout-forms/{id}   
Następnie pobieram informacje o ofercie GET /sale/offers/{offerId}
W kolejnym kroku pobieram parametry przypisane do kategorii GET sale/categories/{categoriesId}/parameters

Filtruje dostępne parametry po kluczu variantsAllowed - tak by uzyskać tylko te po których mogę łączyć warianty.
Następnie mapuje id parametrów z oferty (klucz "parameters") z  nazwami i słownikiem z kategorii by otrzymać  konstrukcje "kolor:czerowny".

Czy to optymalna droga do uzyskania potrzebnych danych ? 
Niestety dla każdego zamówionego produktu musze pobrać duża ilość danych, a chciałbym to ograniczyć. 
Cz rozważaliście dodanie takich danych  w samum zamówieniu (/order/checkout-forms/)?

**Comment by AureliuszBrussy** [comment]
Jeżeli chcesz uzyskać dane tylko o oferowanym kolorze w danej ofercie (w której doszło do sprzedaży) i interesują Cię tylko parametry, po których można wariantować ofertę - to jest optymalna droga. 

Nie planujemy dodania takich danych w samym zamówieniu.
