### ISSUE TITLE
get products Response 403 Forbidden

### ISSUE THREAD

**Issue by VictorZZZZ** [allegro/allegro-api#4149]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam!
Przy **GET** _/sale/products_
Otrzymuje response 403 Forbidden a body jest puste
![изображение](https://user-images.githubusercontent.com/23142632/107031765-c832fb00-67c3-11eb-8889-9cff805be74b.png)

Przy tym powiem ze na request **GET** _/sale/categories_ otrzymuje normalny JSON

![изображение](https://user-images.githubusercontent.com/23142632/107031944-0d572d00-67c4-11eb-83bf-093bb94c2d82.png)

**Comment by MaciejFrackowiak** [comment]
Dostęp do zasobu [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) wymaga autoryzacji bearer-token-for-user, natomiast [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET) zwraca już informacje, gdy korzystasz tylko z bearer-token-for-application. Podsumowując - aby wyszukiwać produkty musisz skorzystać z autoryzacji typu [code](https://developer.allegro.pl/auth/#user) lub [device](https://developer.allegro.pl/auth/#userDeviceFlow), samo client_credentials jest niewystarczające.

**Comment by VictorZZZZ** [comment]
Dziekuje!
Wszysko sie udalo!
