### ISSUE TITLE
brak CAPTHA na stronie odblokowywania zablokowanego IP

### ISSUE THREAD

**Issue by dostawcaopon** [allegro/allegro-api#415]
mam zablokowane IP zapewne po zbyt dużej ilości zapytań na minutę.
na stronie służącej do odblokowywania https://allegro.pl/blocked/index.php
brak jest obrazka z kodem CAPTHA (odświeżanie nie pomaga), przez co nie mogę odblokować IP

**Comment by TomekKaczmarek** [comment]
Nie mogę powtórzyć błędu. Strona u nas działa. Spróbuj ją jeszcze raz odświeżyć. Jeśli problem nadal występuje, skorzystaj proszę z [formularza ](https://allegro.pl/pomoc/faq/problem-w-api-allegro-D5VjMgEdGha
)i podaj IP, którego nie możesz odblokować.
