### ISSUE TITLE
Jak dostac UUID oferty majac link z allegro?

### ISSUE THREAD

**Issue by VictorZZZZ** [allegro/allegro-api#4150]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam! Jak majac linka do oferty otrzymac informacje przez REST API ??
naprzyklad ja mam takiego linka:
https://allegro.pl/oferta/gasnica-proszkowa-gasnice-6kg-gp-6x-abc-z-podstawa-7652763312

Na moje rozumienie **ID** tego produktu jest **7652763312**
Ale przez GET _/sale/products/7652763312_ 
mam response

> {
>     "errors": [
>         {
>             "code": "NotFoundException",
>             "message": "Not Found",
>             "details": null,
>             "path": null,
>             "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
>         }
>     ]
> }

Ale np taki request GET _/sale/products/66387357-b763-44fd-be0c-0c0f68b0c5b6_
Wydaje mi normalny **JSON**

Jak mozna dostac UUID oferty majac tylko link allegro?

**Comment by MaciejFrackowiak** [comment]
Tak, 7652763312 to identyfikator oferty.

Natomiast GET /sale/products służy do wyszukiwania produktów - co do zasady są to dwa osobne twory.

Jeżeli oferta ma podpięty produkt, to znajdziesz go w polu product.id odpytując GET /sale/offers/{offerId} - musisz być jednak sprzedającym w tej ofercie.

**Comment by VictorZZZZ** [comment]
To znaczy ze nie moge dostac opis JSON przez REST API, jezeli mam linka(identyfilator) do oferty?

**Comment by MaciejFrackowiak** [comment]
Otrzymasz go tylko jeśli jesteś sprzedawcą w danej ofercie. W innym przypadku nie.

**Comment by VictorZZZZ** [comment]
Jak rozumiem z [tego](https://github.com/allegro/allegro-api/issues/3661) zaraz nie moge dostac informacje w sprawie oferty przez identyfikator.

Ale znalazlem jescze taki zasob GET

`GET offers/listing?phrase=TEST_PHRASE`

Jezeli _TEST_PHRASE_ na 100% taka sama jak nazwa oferty, wtedy pierwszym wynikiem w odpowiedzi JSON ja dostaje ta oferte ktora potrzebuje.
Z tej oferty mam wszyska informacje ktora potrzebuje (nazwe oferty i kilka linkow do zdjec). Mozna ten title wyciac z curl requestu, ale to nie jest zruczne.

Czy mozna zrobic taki request metod, na pzryklad `GET /sales/offers?id=123456789` ktory bedzie oddawac w responsie te same dane co i `GET offers/listing?phrase=TEST_PHRASE` tylko dla oddzielnej oferty?

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) służy do przeglądania ofert w serwisie - może być dowolna liczba ofert z takim samym tytułem, więc Twoje założenie jest nieprawidłowe.
Nie, nie planujemy żadnych zmian i dodawania osobnych endpointów dla połączenia zasobu /offers/listing i /sale/offers/{offerId}.
