### ISSUE TITLE
Problem z zakończeniem istniejącej oferty

### ISSUE THREAD

**Issue by walgula** [allegro/allegro-api#4151]
Występuje problem: 
 - [x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam
Mam problem z endpointem https://api.allegro.pl/sale/offer-publication-commands/commandId 
Chciałbym za jego pomocą zakończyć istniejące oferty.
Przykładowo wysyłam request PUT pod następujący url:
https://api.allegro.pl/sale/offer-publication-commands/a40aef6f-cc12-4f86-ad2b-26f4f947bca4
Nagłówki:
{'Authorization': 'Bearer Mój Token który działa bo mogę pobrać np. listę ofert', 'Accept': 'application/vnd.allegro.public.v1+json', 'Content-Type': 'application/vnd.allegro.public.v1+json'}
Dane:
{'offerCriteria': [{'offers': [{'id': '10180490239'}], 'type': 'CONTAINS_OFFERS'}], 'publication': {'action': 'END'}}
Response:
{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/a40aef6f-cc12-4f86-ad2b-26f4f947bca4","userMessage":null}]}

Nie rozumiem co robię źle;( Generuję uuid w wersji 4. Czy istnieje jakiś inny sposób zakończenia oferty?
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
To jest właściwy zasób, komenda powinna wyglądać tak:
```
{
	"publication": {
		"action": "END"
	},
	"offerCriteria": [{
		"offers": [{
			"id": "10180490239"
		}],
		"type": "CONTAINS_OFFERS"
	}]
}
```

Payload dla podanego przez Ciebie UUID z przykładu wyglądał tak:
```
offerCriteria=offers&offerCriteria=type&publication=action
```

**Comment by walgula** [comment]
Witam
Właśnie przed chwilą wysłałem requesta
https://api.allegro.pl/sale/offer-publication-commands/26338eee-d54e-4aa5-b318-fa77a6788175
{'publication': {'action': 'END'}, 'offerCriteria': [{'offers': [{'id': '10180490239'}], 'type': 'CONTAINS_OFFERS'}]}
Niestety dalej bez sukcesu:
 {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/26338eee-d54e-4aa5-b318-fa77a6788175","userMessage":null}]}

**Comment by MaciejFrackowiak** [comment]
Zgadza się, wysłałeś request o 2021-02-08 12:27:19.294 - jednak ponownie miał on niewłaściwy payload, dokładnie:
```
publication=action&offerCriteria=offers&offerCriteria=type
```
W payloadzie musisz wysłać zawartość na wzór tej, którą zamieściłem we wcześniejszym poście.

**Comment by walgula** [comment]
Już wiem gdzie miałem błąd;) Pobadam to jeszcze;) Dzięki
