### ISSUE TITLE
Unauthorized błąd w wersji testowej mimo poprawnych danych z aplikacji testowej

### ISSUE THREAD

**Issue by SebastianJavaGame** [allegro/allegro-api#4152]
[REST API](https://developer.allegro.pl/)
[Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/auth/)

![image](https://user-images.githubusercontent.com/26389094/107149557-7cb25580-6959-11eb-9da2-ed696dae9693.png)
![image](https://user-images.githubusercontent.com/26389094/107153392-9eb5d300-696d-11eb-9a5f-d0dd5ef29d48.png)

1.Mam stworzone konto typu DEVICE na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/  (testowa)
2.Wywołuje polecenie jak na załączonym zdjęciu lecz wciąż dostaje Unauthorize.

client i secret id napewno sie zgadza i pobrane jest z testowej wersji typu DEVICE.

Proszę o pomoc.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Przyjrzałem się Twoim zrzutom i widzę dwie rozbieżności:

1) Authorization - tu musisz podać już zakodowaną wartość (ClientID:Client_secret) - w Twoim przykładzie przekazujesz te wartości jawnie, a oprogramowanie ich nie zakoduje "w locie";

2) ClientID powinien się "dokleić" do adresu wywołania tj. POST ....device/ClientID - na screenie widzę, że ma zaznaczoną opcję, jednak w samym pasku adresowym nie dodała się wartość.

**Comment by SebastianJavaGame** [comment]
Super! 
Punkt 1 rozwiązuje mój problem nie zakodowałem nazw koderem base64.

Bardzo pięknie dziękuje.
Pozdrawiam

Temat do zamknięcia.
