### ISSUE TITLE
Wartość null w polu count

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#4153]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nie wiem czy to `by design` czy przypadek, ale zapytanie na `/sale/products?phrase=LWL-LC-LC-4.0M-50/125 Fiber` zwróciło mi w `filters => values` w polu `count` wartość `null`. Nie wygląda to dobrze, więc zgłaszam. Tutaj wynik:

`{
         "id":"3346",
         "name":"Długość kabla",
         "type":"NUMERIC",
         "values":[
            {
               "name":"od",
               "value":null,
               "idSuffix":".from",
               "count":null,
               "selected":false
            },
            {
               "name":"do",
               "value":null,
               "idSuffix":".to",
               "count":null,
               "selected":false
            }
         ],`

**Comment by MaciejFrackowiak** [comment]
Próbowałem odtworzyć Twój request, jednak dla GET /sale/products?phrase=LWL-LC-LC-4.0M-50/125 Fiber otrzymuje:
```
{
    "products": [],
    "categories": {
        "subcategories": [
            {
                "id": "5",
                "name": "Dom i Ogród",
                "count": 0
            },
            {
                "id": "11763",
                "name": "Dziecko",
                "count": 0
            },
            {
                "id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "name": "Elektronika",
                "count": 0
            },
            {
                "id": "4bd97d96-f0ff-46cb-a52c-2992bd972bb1",
                "name": "Firma i usługi",
                "count": 0
            },
            {
                "id": "a408e75a-cede-4587-8526-54e9be600d9f",
                "name": "Kolekcje i sztuka",
                "count": 0
            },
            {
                "id": "38d588fd-7e9c-4c42-a4ae-6831775eca45",
                "name": "Kultura i rozrywka",
                "count": 0
            },
            {
                "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0",
                "name": "Moda",
                "count": 0
            },
            {
                "id": "3",
                "name": "Motoryzacja",
                "count": 0
            },
            {
                "id": "20782",
                "name": "Nieruchomości",
                "count": 0
            },
            {
                "id": "3919",
                "name": "Sport i turystyka",
                "count": 0
            },
            {
                "id": "258832",
                "name": "Supermarket",
                "count": 0
            },
            {
                "id": "1429",
                "name": "Uroda",
                "count": 0
            },
            {
                "id": "121882",
                "name": "Zdrowie",
                "count": 0
            }
        ],
        "path": [
            {
                "id": "954b95b6-43cf-4104-8354-dea4d9b10ddf",
                "name": "Allegro"
            }
        ]
    },
    "filters": [],
    "nextPage": null
}
```

**Comment by jakubmaguza** [comment]
Pardon me,
`/sale/products?phrase=LWL-LC-LC-4.0M-50/125&category.id=67307`
Spróbuj z kategorią.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za doprecyzowanie, kwestię null`a przekazałem już do właściwego zespołu.

**Comment by MaciejFrackowiak** [comment]
Otrzymałem odpowiedź - w tym przypadku nie wystąpiła żadna wartość, stąd null - jest to działanie zgodne z opisem filtrów w [naszym poradniku](https://developer.allegro.pl/productization/#jak-znale%c5%ba%c4%87-produkt).

**Comment by jakubmaguza** [comment]
Nie wiem w którym miejscu na tej stronie jest informacja, że w polu `count` może wystąpić `null`.
W każdym razie, sugerowałbym zmianę z `null` na `0`.

**Comment by MaciejFrackowiak** [comment]
> Dla wartości filtrów słownikowych podajemy “count” - czyli liczbę produktów z daną wartością parametru:

Parametr zwrócony w żądaniu jest parametrem numerycznym dlatego zwracamy count:null == brak wartości.

**Comment by jakubmaguza** [comment]
W waszym `swagger.yaml` jest taka informacja:

    ListingResponseFiltersValues:
    (...)
    count:
          type: integer
          description: Number of search results matching this filter value.
          example: 123
          minimum: 0

Większość narzędzi przetłumaczy to na typ numeryczny, który nie może być `null`.
Nie rozumiem też, jak liczba czegoś może być pusta. Jeśli tego czegoś nie ma, to `count` powinno wynosić `0`. Jeśli to coś nie istnieje, to cały obiekt powinien być `null`.

Jeśli dalej uważacie, że `count` może być `null`, to przynajmniej oznaczcie to w `swagger.yaml`: https://swagger.io/docs/specification/data-models/data-types/#null

**Comment by MaciejFrackowiak** [comment]
"count"  przeznaczony jest tylko dla parametrów słownikowych. Jeżeli będziemy ustawiali "0" w przypadku parametrów numerycznych, to tak jakbyśmy stwierdzili, że w tym konkretnym wyszukiwaniu nie ma żadnego produktu posiadającego ten parametr - tego my nie wiemy, dlatego zwracamy null. Jednocześnie poprawimy swaggera - powinien być tam null.
