### ISSUE TITLE
pobieranie eventów typu OFFER_ENDED

### ISSUE THREAD

**Issue by speedygopl** [allegro/allegro-api#4154]
witam, mam pytanie . Czy ten request  GET /sale/offer-events?from=offerID&limit=500&type=OFFER_ENDED zwróci w odpowiedzi
wszystkie zdarzenia tego typu bez względu na datę wystąpienia, czy tylko eventy z ostatnich 24 godzin?

**Comment by AureliuszBrussy** [comment]
Zwrócimy wszystkie zdarzenia tego typu z ostatnich 24 godzin.

**Comment by speedygopl** [comment]
a czy jest możliwość pobrania wcześniejszych?

**Comment by AureliuszBrussy** [comment]
Zwracamy w ofertach eventy tylko sprzed 24 godzin. Nie ma możliwości pobrania tych wcześniejszych.
