### ISSUE TITLE
Oferty nie startują

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4157]
Dlaczego poniższe aukcje nie chcą się rozpocząć ? Pierwsza kolumna to nr aukcji a druga identyfikatora, który został zwrócony po wykonaniu komendy

`PUT /sale/offer-publication-commands/<uuid>`

9895558843	             9c84d3df-791b-4f77-92af-886f2e5ab99d
9895576820	   7808720b-c8cd-4caa-b4e1-8c17de9abd85
9907488914	   60045e36-3b52-4940-b637-c4ceb246a20a
9922256229	   39a9b9f7-674d-4842-933b-0e467ab92330
9922256681	   9e5a3293-cf1d-46cc-a551-1dc9f69d636f
9922437831	   651f0648-9343-4a80-a5a5-b71461b5cfd3
9922862832	   4191647c-dcf0-415d-931a-20807c107ac7
9938548942	   b156afef-4951-4e4f-9ec1-5f1334568508
9944544070	   b7f1a4cb-a5e4-4478-bca2-011e93cee61f
9944544162	   5a87d406-f86c-422f-a425-298614bc4d7b
9944576118	   a77152fd-43f1-4baa-8240-1813167c04f0
9944592273	   f932a769-c285-429f-b406-e0f7beb3bcc5
9976828745	   e59bdd78-8787-474c-bc41-9281d69d895a
9976829153	   2694651f-0eea-4f45-a8d2-2f80a49c2e9e
9999554834	   c51945a4-1a26-4265-8951-5c71f7cda4d3
10028475192	   360d7a30-422f-49c0-a56d-d598d35ac2fe
10045259263	   8e5614f3-a307-4832-9f2a-94481a441afb
10104763097	   bb7833a3-a1bd-4cec-8211-25fd459a763c
10106365381	   57a30773-4863-4439-a4cd-ee38abfb5764
10117298459	   df4aaaa4-6d07-4974-9566-aacbe23b4ad2
10175220854	   63c7fe45-0047-4f45-86af-2e936456bb50
10197065650	   c10326bc-fe6a-4559-8ab7-0059ef4022c2
10197065839	   fa992e14-f147-4f09-88c2-ec4a9c051256
10197117356	   4f4e2bed-4229-4063-9615-353602a52e99
10216254113	   de64ba31-1b5a-4ce6-9732-ab2d75414b3d

**Comment by AureliuszBrussy** [comment]
Oferty nie zostały aktywowane ze względu na błędną wartość w parametrze kod producenta (224017). Wprowadzona w ofertach wartość nie jest zgodna z produktami, z którymi ma zostać powiązana. Skorzystaj z wartości, które znajdziesz w produktach.

**Comment by pietrach** [comment]
Prośba o zmianę kodu producenta w tych produktach na taki jaki idzie w ofertach. Nie chce mi się już tego wysyłać przez odrębny formularz

**Comment by pietrach** [comment]
Albo ewentualnie aby tylko EAN jednoznacznie identyfikował produkt a nie kod producenta

**Comment by AureliuszBrussy** [comment]
Jeżeli są to błędy w produktach - zgłoś je za pomocą tego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Odpowiedni zespół to przeanalizuje. Jednoznaczne identyfikowanie produktu określane jest na poziomie całej kategorii. Nie wyłączymy tej funkcji tylko dla tych konkretnych produktów.
