### ISSUE TITLE
Aktywacja sprzedaży na sandbox

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#4158]
Proszę o aktywację sprzedaży na koncie mp_shoper_sa

**Comment by AureliuszBrussy** [comment]
Aktywowałem wskazane konto. Wybrałeś konto firmowe, dlatego w celu jego weryfikacji niezbędne jest przesłanie dwóch dowolnych plików w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by michalpokora** [comment]
Pliki przesłane.

**Comment by AureliuszBrussy** [comment]
Twoje konto jest już aktywne.

**Comment by michalpokora** [comment]
Dziękuję
