### ISSUE TITLE
Obsługa zamówień z odroczoną płatnością

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#4159]
Witam,
w artykule [Zmiany na Allegro od 8 lutego](https://allegro.pl/dla-sprzedajacych/zmiany-na-allegro-od-8-lutego-k1xWm7dX1ue#allegro-biznes-najlepsze-miejsce-na-firmowe-zakupy-i-sprzedaz) czytam "Twoja oferta trafi do tysięcy klientów biznesowych oraz do indywidualnych" i będzie widoczna dla wszystkich. 
1. Jak się mają do tego wyniki wyszukiwania z REST API /offers/listing - Mam tutaj jedną cenę a w dokumencie mowa o cenach netto. 
2. Czy tworząc aplikację z konta firmowego albo prywatnego dostaniemy inne wyniki biorąc pod uwagę w.w. zmiany? 

Z góry dziękuję za szybką dopowiedź :).

**Comment by AureliuszBrussy** [comment]
Konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by gsti** [comment]
> 
> 
> Konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę z odpowiedzią.

Dziękuję zaczekam :)

**Comment by AureliuszBrussy** [comment]
Wyniki zwrócone w [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) aktualnie pozostają bez zmian. O wszelkich ewentualnych zmianach będziemy komunikować.

**Comment by gsti** [comment]
> 
> Wyniki zwrócone w [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) aktualnie pozostają bez zmian (zwrócimy tylko cenę brutto). O wszelkich ewentualnych zmianach będziemy komunikować.

Ok. Dziękuję za odpowiedź będę obserwował zmiany. 

Jest to rozpatrywane?
Jest przybliżony czas kiedy te zmiany mogą być wdrażane?

**Comment by AureliuszBrussy** [comment]
@gsti mamy to na uwadze. Na ten moment nie jestem w stanie wskazać konkretnej czy przybliżone daty.

**Comment by gsti** [comment]
> 
> 
> @gsti mamy to na uwadze. Na ten moment nie jestem w stanie wskazać konkretnej czy przybliżone daty.

Ok dziękuję za info.
