### ISSUE TITLE
Brak wartości "publication" /offers/listing

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#4160]
Witam, 

Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W dokumentacji https://api.allegro.pl/offers/listing
dostajemy informację o "publication" a w REST API już nie. Czym to jest spowodowane albo jakie są warunki otrzymania "publication" w wynikach wyszukiwania.

P.S. Chodzi o REST API allegro.pl nie sandbox :)

Z góry dziękuję za szybką odpowiedź.

**Comment by AureliuszBrussy** [comment]
Zwracamy obiekt **publication**, a w nim pole **endingAt**, natomiast jest tak tylko w przypadku ofert, które zostały wystawione na czas określony. W przypadku ofert "do wyczerpania zapasów" - nie zwrócimy tego obiektu.

**Comment by gsti** [comment]
> 
> Zwracamy obiekt **publication**, a w nim pole **endingAt**, natomiast jest tak tylko w przypadku ofert, które zostały wystawione na czas określony. W przypadku ofert "do wyczerpania zapasów" - nie zwrócimy tego obiektu.

Dziękuję za expresową odpowiedź.
