### ISSUE TITLE
Podany EAN nie jest zgodny z jakimkolwiek EANem produktu.

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#4161]
Dzień dobry,

Klient korzystający z narzędzia działającego przez API otrzymuje poniższy komunikat:
    8472392316 - Podany EAN nie jest zgodny z jakimkolwiek EANem produktu.

Według niego EAN dla produktu jest prawidłowy: 5901925337279

Czy mogę prosić o wyjaśnienie nieprawidłowości, przez którą nie można wystawić oferty?

**Comment by AureliuszBrussy** [comment]
Oferta powiązana jest z produktem, w którym w parametrze 225693 (EAN) nie znajduje się wartość 5901925337279. Jeżeli jest to błąd w produkcie lub obydwie wartości są prawidłowe - Sprzedający może zgłosić to poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by dkceso** [comment]
W karcie produktu EAN jest uzupełniony

![Zrzut ekranu 2021-02-11 o 12 56 13](https://user-images.githubusercontent.com/78864364/107633645-aaa0de00-6c68-11eb-88aa-bbecb4105dbf.png)

**Comment by AureliuszBrussy** [comment]
Oferta jest powiązana z produktem o id d4cbfa58-9f18-4965-93bb-c9e5d5b04be1. Produkt ten w parametrze EAN (225693) posiada tylko wartość 5901925719938. W przypadku powiązania oferty z produktem - w ofercie powinni Państwo przekazać ten sam EAN, który jest zdefiniowany w produkcie, czyli 5901925719938. Jeżeli w tym produkcie EAN nie jest prawidłowy - mogą Państwo zgłosić błąd w produkcie z poziomu formularza wystawiania lub poprzez [formularz konktatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by dkceso** [comment]
Przepraszam, ale czy można jaśniej ? Nie rozumiem. W produkcie jest podany EAN, który jest prawidłowy. Przy automatycznym zakończeniu oferty i ponownym wznowieniu przekazujemy te same wartości, które były wcześniej, nic się nie zmienia, więc EAN jest prawidłowy. Sprawa za każdym razem dotyczy kilkuset aukcji, nie ma możliwości, żeby zakaźnym razem zgłaszać przez formularz kontaktowy.

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik czy mogę prosić jeszcze o pełen request oraz response w formacie curl lub trace-id konkretnego wywołania, które zakończyło się błędem?
