### ISSUE TITLE
Czy allegro api zwraca prowizję od sprzedaży oferty wyróżnionej?

### ISSUE THREAD

**Issue by gorskimarcin96** [allegro/allegro-api#4162]
Mam pytanie, czy allegro api zwraca prowizję od sprzedaży oferty wyróżnionej? Korzystalem z tych metod i wszystkie płatności mi zwróciło oprócz tej o której jest mowa w pytaniu.

Użyte metody:
/pricing/fee-preview
/pricing/offer-quotes

**Comment by AureliuszBrussy** [comment]
Tak, zwracamy po użyciu powyższych metod informację o prowizji od sprzedaży oferty wyróżnionej. Na liście **commissions** zwrócimy obiekt typu (**commissions[].type**) "commissionFeatureFee", gdzie znajdziesz kwotę tej prowizji.

**Comment by gorskimarcin96** [comment]
Dziękuje bardzo za informację tam wszystko jest :)
