### ISSUE TITLE
Pobranie informacji o ofercie na podstawie offer.id

### ISSUE THREAD

**Issue by patrykpalej** [allegro/allegro-api#4163]
Próbuję pobrać dane o dowolnej ofercie korzystając ze ścieżki `/sale/offers/<offer.id>`. Kod odpowiedzi to 403. Znalazłem informację, że może wynikać to z użycia bearer-token-for-application zamiast bearer-token-for-user. Problem polega na tym, że kod którym wygenerowałem token (używam Pythona) znalazłem w internecie i nie bardzo wiem jak pobrać bearer-token-for-user zamiast ...-for-application. W związku z tym mam dwa pytania:

1. Jakie modyfikacje należy wprowadzić żeby pobierany token pozwalał na wyszukiwanie ofert w taki sposób jaki opisałem. Domyślam się, że należy postępować podobnie ale z jakimiś modyfikacjami.
2. Czy na podstawie takiego zapytania można pobrać wszystkie parametry oferty jakie widnieją w aukcjach allegro (w tym treść oferty) czy tylko wybrane informacje takie jak cena czy czas wystawienia produktu?

**Comment by TimothyKoval** [comment]
Uprzedzę wątpliwości; możesz pobrać szczegóły tylko własnej oferty (zautoryzowanego użytkownika), oferty innych użytkowników weźmiesz tylko z listingów

**Comment by patrykpalej** [comment]
> Uprzedzę wątpliwości; możesz pobrać szczegóły tylko własnej oferty (zautoryzowanego użytkownika), oferty innych użytkowników weźmiesz tylko z listingów

Ale w ten sposób mogę pobrać pojedynczą ofertę? Z dokumentacji wynika że nie. Chyba że inną ścieżką niż `/offers/listing`

**Comment by AureliuszBrussy** [comment]
Nie możesz pobrać szczegółowych danych oferty innego użytkownika (takich jak np. parametry w ofercie). Jedyny zasób, dzięki któremu pozyskasz podstawowe dane o ofertach jako niezautoryzowany użytkownik to [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). 

Natomiast jako zautoryzowany użytkownik (np. autoryzacja typu [Authorization Code](https://developer.allegro.pl/auth/#app), w wyniku której uzyskasz bearer-token-for-user) możesz pobierać listę ofert za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i dane poszczególnych ofert za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by patrykpalej** [comment]
Tak właśnie podejrzewam, że muszę wygenerować bearer-token-for-user. Nie mogę jednak znaleźć instrukcji, która wyjaśniłaby w jaki sposób ten token wygenerować. Przeszukiwałem stronę dokumentacji którą podlinkowałeś żeby znaleźć frazę 'bearer-token-for-user' i taka fraza w ogóle tam nie występuje.

Zarejestrowałem swoją aplikacje, posiadam client ID oraz client secret ale nie wiem w jaki sposób wygenerować bearer-token-for-user

**Comment by AureliuszBrussy** [comment]
Masz dwie podstawowe możliwości - [Authorization Code flow](https://developer.allegro.pl/auth/#user) dla użytkownika lub [Device flow](https://developer.allegro.pl/auth/#DeviceFlow). Wybierz rozwiązanie najbardziej odpowiadające Twoim potrzebom. Pod obydwoma linkami znajdziesz instrukcję krok po kroku jak wygenerować bearer-token-for-user.

**Comment by patrykpalej** [comment]
Kod którego używam wygląda na to że realizuje instrukcje z  [Authorization Code flow](https://developer.allegro.pl/auth/#user). Token który otrzymałem nie pozwala jednak dostać się do zasobów których potrzebuję. Następnie wysłałem zapytanie POST z instrukcji [Device flow](https://developer.allegro.pl/auth/#DeviceFlow) i w odpowiedzi dostałem `{'error': 'Unauthorized', 'error_description': 'Unauthorized'}` 

Zdekodowałem też swój token i wynikowy json wskazuje, że w scopie tego tokenu jest między innymi `"allegro:api:sale:offers:read",` co sugeruje że powina być możliwość odczytu ofert. Czy istnieje jakiś sposób, żeby określić czy token który mam jest dla usera czy aplikacji?

Czy jest możliwość publikacji kodu, który bezpośrednio realizuje pobieranie tokena? Byłoby to o wiele bardziej klarowne niż instrukcja, która pozostawia miejsce na nieścisłości przy próbie jej implementacji.

Znalazłem fragmenty takiego kodu w PHP w [dokumentacji](https://developer.allegro.pl/getting_started/) ale jest napisane tylko że można nim wygenerować access token a nie który z tych dwóch tokenów (user, application).

**Comment by AureliuszBrussy** [comment]
@patrykpalej nie mamy przykładu kodu, który realizuje autoryzację dla użytkownika, natomiast po dekodowaniu takiego access tokena, w przeciwieństwie do bearer-token-for-application, znajdziesz w nim zakodowany id konta użytkownika ("user_name": "xxxxxxx"). Może któryś z użytkowników naszego forum pomoże Ci z konkretnym przykładem kodu. 

W dokumentacji przykład dotyczy generowania bearer-token-for-application.

**Comment by patrykpalej** [comment]
Token którego używam po zdekodowaniu posiada parametr "user_name" i jest to ten sam numer który pojawia się w przeglądarce pod tym endpointem `https://allegro.pl/login/user`. Wygląda więc na to, że mój token jest tokenem usera.

Być może więc adres url którego używam by pobrać dane o konkretnej ofercie jest błędny. Zgodnie z dokumentacją adres ten to `https://api.allegro.pl/sale/offers?offer.id=<xxxxxxxxx>` (offer.id jako query parameter). Odpowiedź jaką wówczas uzyskuję to `{'offers': [], 'count': 0, 'totalCount': 0}` pomimo tego, że offer.id wziąłem oczywiście z istniejącej oferty (`Numer oferty: <xxxxxxx>` który widać na dole aukcji na allegro). Moim zdaniem podanie parametru w ten sposób jest poprawne, ale może jestem w błędzie?

Nagłówki jakich używam są następujące. Być może problem tkwi w nagłówku 'Api-Key', znalazłem informację że ten nagłówek nie jest obecnie potrzebny, ale usunięcie go nic nie daje.

`'charset' = 'utf-8',
'Accept-Language' = 'pl-PL',
'Content-Type' = 'application/json',
'Api-Key' = <client_id>,
Accept' = 'application/vnd.allegro.public.v1+json' ,
Authorization' = "Bearer <xxxxxxxxx>"`

Czy w moich nagłówkach czegoś brakuje? Dokumentacja podaje query parameters, ale nie nagłówki.

**Comment by AureliuszBrussy** [comment]
@patrykpalej prześlij proszę pełen request (wraz z tokenem) i response w formacie curl przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dopisz w zgłoszeniu, że problem dotyczy wątku #4163 na GitHubie.

**Comment by AureliuszBrussy** [comment]
@patrykpalej otrzymałem Twoje zgłoszenie wraz z danymi. 

Access token, z którego korzystasz nie należy do użytkownika, z którego konta została wystawiona ta oferta.

Nie wystarczy, że wygenerujesz bearer-token-for-user dowolnego użytkownika - możesz pobrać szczegółowe dane oferty tylko jako użytkownik, z którego konta dana oferta została wystawiona.

**Comment by patrykpalej** [comment]
Czyli w takim razie nie istnieje żaden sposób, żeby pobrać szczegóły oferty innego użytkownika? Swoje oferty znam, więc nie potrzebuję pobierać o nich żadnych informacji przez API.

**Comment by AureliuszBrussy** [comment]
@patrykpalej podstawowe dane o ofertach innych użytkowników możesz pobrać tylko za pomocą  [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).

**Comment by patrykpalej** [comment]
> @patrykpalej podstawowe dane o ofertach innych użytkowników możesz pobrać tylko za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).

1. Czy po ostatnich zmianach w regulaminie getListing nadal będzie działał tak samo jeśli moja plikacja jest już zarejestrowana? 2. Czy jeśli włączę opcję dwustopniowego logowania do allegro to czy coś się zmieni z punktu widzenia korzystania z API?
3. Od czerwca mają być wprowadzone nowe zmiany. Czy można spodziewać się dodatkowych funkcjonalności czy raczej będzie to dalsze ich wygaszanie?

**Comment by AureliuszBrussy** [comment]
@patrykpalej 
1. Od 01.06.2021 zasób będzie dostępny tylko dla zweryfikowanych aplikacji, a zakres zwracanych danych ulegnie zmianie:
- popularność - zamiast liczby sprzedanych przedmiotów będą dostępne tylko zakresy,
- sortowanie po popularności nie będzie możliwe,
- wyszukiwanie zostanie ograniczone do 10 stron (maksymalna wartość parametru offset to 600).

2. Od 15.03. konieczne będzie włączenie dwustopniowego logowania, aby [zarejestrować](https://apps.developer.allegro.pl/) nową aplikację. Natomiast zmiana ta nie wpłynie na sposób działania API Allegro.  

3. Na ten moment nie planujemy nowych funkcjonalności dla zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).
