### ISSUE TITLE
Rozmiar pola offer.id w bazie danych

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#4164]
Potrzebuję przechować oferty użytkownika (nie całe) we własnej bazie danych. Mam problem z zaplanowaniem rozmiaru pól. Brak jest np. informacji ile taki offer.id ma maksymalnie znaków.

**Comment by AureliuszBrussy** [comment]
Aktualnie najdłuższe numery ofert mają 11 cyfr. Każda utworzona oferta posiada nowy numer oferty. Jeżeli dostępne 11 cyfrowe liczby się skończą - numer oferty będzie miał 12 cyfr, itd. Weź ten fakt pod uwagę podczas planowania rozmiarów pól.

Dodam również, że długość tytułu oferty nie może przekroczyć 50 znaków, a maksymalna wielkość opisu oferty to 40000 bajtów.

**Comment by jmarek-pl** [comment]
Myślę, że w SQL Server taki powinien być typ pola na numer oferty: varchar(50). Czyli ponad dwu krotnie więcej niż najdłuższy numer oferty. Dodam, że liczba 64 bitowa ze znakiem to max 19 cyfr.

Ile znaków maksymalnie przewidzieliście dla sygnatury?

**Comment by AureliuszBrussy** [comment]
Maksymalna długość external.id to 100 znaków.

**Comment by jmarek-pl** [comment]
Czy na pole stock.available wystarczy int (32-bitowa liczba całkowita ze znakiem) w bazie danych. Chyba nie dajecie możliwości wystawiania ułamkowych ilości, a int to maksymalnie dosyć duża liczba.

**Comment by AureliuszBrussy** [comment]
Wartość w tym polu nie może być większa niż 100000 i zawsze będzie liczbą całkowitą.
