### ISSUE TITLE
"Pasuje do", brak dopasowanie po kTypNr

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#4165]
Jak w temacie, zarówno poprzez API jak i przy wystawianiu ofert ręcznie z poziomu allegro.pl nie mogę wybrać pojazdów po kTypNr.

Przykładowe id:
- 26582
- 15657 -> przykład z    https://developer.allegro.pl/compatibility_list/

**Comment by AureliuszBrussy** [comment]
Konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by pliszka** [comment]
być może powiązane, zasób /sale/compatible-products nie zwraca w parametrach pola K_TYP_NR dla żadnego z 50 500 pojazdów

**Comment by pliszka** [comment]
zasób : /sale/compatible-products?type=CAR&tecdoc.kTypNr=15665 nie zwraca danych pojazdu Audi A6 C5 to samo dla 11831 - A8 D4 4H (zakładam że odpytanie dowolnego innego TecDoc.kTypNr da taki sam efekt)

**Comment by mlonc** [comment]
Czy zostało już coś ustalone(oprócz tego, że nie działa :))?

**Comment by AureliuszBrussy** [comment]
@pliszka @mlonc wciąż wyjaśniamy ten problem. Proszę o jeszcze trochę cierpliwości. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@pliszka @mlonc problem już nie występuje - prawidłowo zwracamy dane. Przepraszam za niedogodność.

**Comment by mlonc** [comment]
Sprawdzone, działa. 
Dziękuję za pomoc.
