### ISSUE TITLE
InternalServerError przy pobieraniu zamówień

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4166]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W piątek jeszcze wszystko działało dziś błąd (InternalServerError 500) wywołując zasób : 
https://api.allegro.pl/order/checkout-forms?status=READY_FOR_PROCESSING&limit=100&fulfillment.status=PROCESSING

Pobieranie ofert działa. Coś u Was?

**Comment by cyfranT** [comment]
U nas też ten sam błąd dla wywołania order/checkout-forms?status=ALL&offset=0

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Wiemy o problemie, pracujemy nad rozwiązaniem. Poinformuję w wątku po wyeliminowaniu błędów.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się wyeliminować problem, nie powinien już występować.

**Comment by paafcioc22** [comment]
@PrzemyslawLukanowski  działa, dzięki.
