### ISSUE TITLE
Pobieranie szczegółów wybranych zamówień - INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#4167]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

/order/checkout-forms/cf9313e9-6e25-11eb-bda2-193cb2a1456d
Zwraca:
{'status': 'error', 'code': 500, 'description': u'{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}'}

Przy próbie pobrania szczegółów zamówienia dostaje 500. Nie jestem w stanie określić zależności dlaczego problem występuje tylko czasami. Tu cała lista id zamówień gdzie problem dostałem:
abaebce1-6e1b-11eb-b584-1dfc12b35469
13f62451-6e1c-11eb-b5ff-31c75506ce34
08d488c1-6e1f-11eb-807b-37071f73bf9f
48721651-6e1f-11eb-b5ff-31c75506ce34
f521a0d1-6e21-11eb-bda2-193cb2a1456d
106cab41-6e23-11eb-8a60-e19bfc5297be
3a1e62c1-6e24-11eb-807b-37071f73bf9f

Mam ich ponad 100 ale raczej nie mam sensu wymieniać wszystkich tu.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, informacje o błędach otrzymaliśmy już w poprzednim wątku #4166. Pracujemy nad rozwiązaniem problemu.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się wyeliminować problem, nie powinien już występować.

**Comment by Bodzix** [comment]
Dziękuję. Widzę, że pobieranie szczegółów zamówień ponownie działa.
