### ISSUE TITLE
Pobieranie wszystkich aukcji z danego konta

### ISSUE THREAD

**Issue by SebastianKot** [allegro/allegro-api#4168]
Dzień dobry wszystkim,

Mam pewien problem z którym męczę się od jakiegoś czasu i nie mogę go przejść.

W jaki sposób mogę pobrać wszystkie aktywne aukcje danego konta? 
Używam argumentu **offset** dopisując do linku &offset=120000 (bo dla wywoływania danego linku przez login sprzedawcy wywołań jest 120 000). Ale jak wpisuje wszystko to nie wyskakuje nic, nie mam żadnej zwrotki. 

Czy mógłby mi ktoś z tym pomóc? 

Sugeruję się po tym:
https://developer.allegro.pl/listing/

Serdecznie wszystkich pozdrawiam i życzę miłego dnia,
Sebastian

**Comment by PrzemyslawLukanowski** [comment]
Wartość offset wskazuje, od którego momentu chcesz pobrać kolejne wyniki. Czyli jeśli przekazujesz 120000, a dany sprzedawca ma właśnie tyle ofert, w odpowiedzi nie otrzymasz żadnych wyników, bo od tego miejsca już ich nie ma. Oferty możesz pobierać zatem w pętli, po 60 wyników - dla pierwszej porcji wyników użyj GET /offers/listing?seller.id={seller.id}, następnie GET /offers/listing?seller.id={seller.id}&offset=60 i z każdą kolejną pętlą zwiększaj wartość dla offset o 60, aż pobierzesz wszystkie oferty, których łączną liczbę zwróciliśmy w polu **searchMeta.availableCount**.

**Comment by SebastianKot** [comment]
Dziękuję za szybką odpowiedź.
Przetestuję to dziś wieczorem i ew. pytania zamieszczę tutaj.

Miłego dnia :)

**Comment by SebastianKot** [comment]
Mam jeszcze pytania:

1. Mam konto https://allegro.pl.allegrosandbox.pl/uzytkownik/cmpVer_1_pl
I tutaj mam 486 aukcji, a "liczenie" pobiera mi tylko 426, dlaczego ? 

2. Czym róźni się **searchMeta**
availableCount a totalCount? Przy pobieraniu offset 60 czy 300 nawet nie ma żadnej różnicy

**Comment by SebastianKot** [comment]
Dałem sobie radę, dziękuję za wyjaśnienie Panie Przemysławie

Mam jeszcze pytanie:

Czym róźni się searchMeta
availableCount a totalCount? Przy pobieraniu offset 60 czy 300 nawet nie ma żadnej różnicy

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z info z naszego poradnika:
```

"availableCount": 1,                            -- liczba ofert, które spełniają warunki
                                                określone w zapytaniu i które
                                                wyświetlamy w serwisie. Przykładowo:
                                                dla danego zapytania liczba ofert jakie je
                                                spełniają to 2 000 000, ale na listach
                                                ofert w serwisie wyświetlamy
                                                maksymalnie 6000. Liczba 6000 to
                                                availableCount.
 "totalCount": 1,                               -- całkowita liczba ofert, które spełniają
                                                warunki określone w zapytaniu.
                                                Przykładowo: dla danego zapytania
                                                liczba ofert, jakie je spełniają wynosi
                                                2 000 000, ale na listach ofert w serwisie
                                                wyświetlamy maksymalnie 6000.
                                                Liczba 2 000 000 to totalCount.
```

**Comment by SebastianKot** [comment]
Przepraszam, za moje nie dopatrzenie. 

Dziękuje bardzo za pomoc, temat do zamknięcia :)
