### ISSUE TITLE
Czy anulowanie zamówienia przez kupującego zmienia status zamówienia.

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4169]
Czy jak kupujący anuluje zamówienie to czy zmieni się `fulfillment.status` na CANCELLED?

**Comment by PrzemyslawLukanowski** [comment]
Nie, ponieważ tym polem manipuluje tylko sprzedawca. Wartość zmieni się w polu `status` (na CANCELLED).

**Comment by AnimalDEV** [comment]
Ok dziękuję.
