### ISSUE TITLE
Rest API zakończenie aukcji

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#417]
Cześć,
czy istnieje metoda na hurtowe zakończenie aukcji?

Próbowałem użyć metody:
PUT /sale/offer-modification-commands/86807A7A-3198-4AD4-8614-BD1179DDAF51

w payload podając:
{   "modification": { "action": "END",   "offerCriteria": [{    "offers":[{"id": id1}, {"id": id2}, {"id": id3}],    "type": "CONTAINS_OFFERS"   }]  }

niestety zwrotnie dostaje błąd:

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-modification-commands/86807A7A-3198-4AD4-8614-BD1179DDAF51","userMessage":null}]}

**Comment by PawelTaberski** [comment]
Tak, jak napisałeś zasobem do masowego zakończenia oferty jest PUT /sale/offer-publication-commands/{commandId}, dokładny opis tej metody znajdziesz [tutaj](https://developer.allegro.pl/sale/#step-7-offer-publication-commands).
