### ISSUE TITLE
Problem ze zmianą ceny

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#4171]
trance id 4aff25c837a44487 status 201 a cena wciąż od dłuższego czasu nie ulega zmianie
https://api.allegro.pl/sale/offer-price-change-commands/

**Comment by PrzemyslawLukanowski** [comment]
Status 201 oznacza, że przyjęliśmy zadanie do wykonania, jednak nie zostało ono jeszcze ukończone. Za pomocą GET /sale/offer-price-change-commands/{commandId}/tasks sprawdzisz aktualny status zadania. W Twoim przypadku zakończyło się to niepowiedzeniem i zwróciliśmy komunikat - `"Uzupełnij parametry obowiązkowe: ISBN."`
