### ISSUE TITLE
Błąd 422 - Payment Operations

### ISSUE THREAD

**Issue by seosud** [allegro/allegro-api#4172]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam, Do dnia dzisiejszego tj. 15-02-2021 bez problemu używaliśmy w firmie Państwa API do pobierania historii płatności za pomocą metody: payment-operations o wywołaniu: 'https://api.allegro.pl/payments/payment-operations'
Problem jaki się dziś pojawił to błąd o numerze 422 z poniższą informacją. Proszę o informację jak rozwiązać problem.

{"errors": [{"code": "TooManyOperationsException", "message": "rezultat wyszukiwania zawiera zbyt du\u017c\u0105 liczb\u0119 operacji: 10\u00a0127, maksymalny limit operacji wynosi: 10\u00a0000, prosz\u0119 ograniczy\u0107 filtr wyszukiwania", "details": null, "path": "/payments/payment-operations", "userMessage": "rezultat wyszukiwania zawiera zbyt du\u017c\u0105 liczb\u0119 operacji: 10\u00a0127, maksymalny limit operacji wynosi: 10\u00a0000, prosz\u0119 ograniczy\u0107 filtr wyszukiwania"}]}

Zapytanie jakie stosujemy w kodzie Python:
`with requests.Session() as sesja:
    sesja.headers.update(headers)
    response = sesja.get('https://api.allegro.pl/payments/payment-operations')
    print(response)
`
Wynikiem tego kodu jest : <Response [422]>.

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z komunikatem, który zwróciliśmy w API - liczba wyników jest aktualnie zbyt duża, aby zwrócić ją w odpowiedzi. Aby rozwiązać problem, skorzystajcie z dodatkowych filtrów, które zmniejszą liczbę rekordów, np.  GET /payments/payment-operations?occurredAt.gte={date} - aby pobrać wyniki tylko od daty określonej w tym parametrze.

**Comment by seosud** [comment]
Dziękuje
