### ISSUE TITLE
Kampanie - zarządzanie oraz tworzenie

### ISSUE THREAD

**Issue by patryk20120** [allegro/allegro-api#4173]
Czy jest możliwość zarządzania (wstrzymywanie i wznawianie) oraz tworzenia nowych kampanii poprzez API? Jest opisane jak dodawać oferty do kampanii, ale o tym jak tworzyć czy nimi zarządzać nic nie znalazłem. Widzę, że niektóre aplikacje z tego korzystają - mogą mieć dostęp do bardziej rozbudowanego API?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli masz na myśli przypisywanie ofert do kampanii w ramach Badgy, to w publicznym API udostępniamy tylko te zasoby, które opisaliśmy w [naszym poradniku](https://developer.allegro.pl/badge/). Nie udostępniamy publicznie innych zasobów do tworzenia i zarządzania Kampaniami przez API.

**Comment by patryk20120** [comment]
Czyli dobrze rozumiem, że nie jest możliwe tworzenie kampanii przez API, które można tworzyć przez interfejs pod linkiem https://www.ads.allegro.pl/panel/campaigns ? To samo tyczy się wstrzymywania kampanii oraz ich wznawiania. BaseLinker bez problemu tworzy takie kampanie, nie jest to robione przez API? Dodatkowo tworzy kampanie, których nie można edytować (na tym mi zależy).

Czy jest inny sposób na tworzenie kampanii oprócz podanej wcześniej strony allegro?

**Comment by PrzemyslawLukanowski** [comment]
> Czyli dobrze rozumiem, że nie jest możliwe tworzenie kampanii przez API, które można tworzyć przez interfejs pod linkiem https://www.ads.allegro.pl/panel/campaigns ?

Nie, nie da się tworzyć takich kampanii przez API.

> BaseLinker bez problemu tworzy takie kampanie, nie jest to robione przez API? Dodatkowo tworzy kampanie, których nie można edytować (widoczna jest w Allegro jako kampania partnerska).

Baselinker ma dostęp do dedykowanego API dla Partnerów Allegro, które nie jest jednak szeroko udostępniane i nie pozwala na wszystkie funkcje dostępne w panelu Ads.

> Czy jest inny sposób na tworzenie kampanii oprócz podanej wcześniej strony allegro?
To jedyny dostępny sposób.
