### ISSUE TITLE
[SANDBOX] Brak możliwości wystawienia oferty

### ISSUE THREAD

**Issue by ziebapawel** [allegro/allegro-api#4174]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Nie mogę wystawić nowej aukcji na środowisku testowym (interfejs webowy), "Wystaw przez formualarz" kieruje mnie do: https://staging-lokalnie.allegrogroup.com/oferty/wystaw - gdzie otrzymuję błąd. Doczytałem już, że należy skorzystać z: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie lecz gdy chcę utworzyć ofertę za każdym razem otrzymuję komunikat: "Nie udało się utworzyć oferty dla wybranego produktu." Coś muszę jeszcze zrobić abym mógł wystawić ofertę w środowisku testowym (np. dodatkowo aktywować konto)?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać ID draftu, który tworzysz (znajdziesz w adresie url) oraz ID konta?

**Comment by ziebapawel** [comment]
Client ID: 93974418 - zaznaczam, że jest to konto na środowisku testowym
![image](https://user-images.githubusercontent.com/1412766/108037129-71d28180-7039-11eb-8b0f-f073d28063d1.png)

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto, [uzupełnij także wszystkie niezbędne dane konta](https://allegro.pl/moje-allegro/moje-konto/dane-konta/) (imię i nazwisko, adres, etc.) i spróbuj ponownie wystawić ofertę.

**Comment by ziebapawel** [comment]
Wszystko już działa. Dziękuje bardzo za pomoc.
