### ISSUE TITLE
Podczas access tokena za pomocą Refresh Tokena

### ISSUE THREAD

**Issue by krawiec1011** [allegro/allegro-api#4175]
Podczas odświerzenia access tokena za pomocą Refresh Tokena
Otrzymuje błąd: "Wrong client for this refresh token"
Sprawdziłem poprawność client_id i user_name, dla konkretnego Refresh Tokena. 
Problem występuje dla clientID: 6eede624805847429cc9808f69b473b2

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że w Authorization przesyłasz  odpowiednio zakodowowane clientID i clientSecret, powiązane z danym refresh tokenem. Ten komunikat oznacza, że dane są rozbieżne (może np. występować literówka w kodzie). Jeśli problem nadal będzie występować, prześlij nam przykładowe logi za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), z dopiskiem GitHub #4175

**Comment by AureliuszBrussy** [comment]
Dziękuję za dane przesłane w formularzu. Zakodowany Client_ID w Twoim wywołaniu nie jest prawidłowy - nie jest to 6eede624805847429cc9808f69b473b2. Sprawdź poprawność danych przekazany w nagłówku Authorization.
