### ISSUE TITLE
Jak pobrac podkategorie oraz ich cechy

### ISSUE THREAD

**Issue by sygmak** [allegro/allegro-api#4176]
Witam

pobralem wszystkie 13 kategorii porzez get ( https://api.allegro.pl/sale/categories) wszystkie te kategorie maja parent null
I leaf false.

Poniewaz nie znalazlem nic w dokumentacji o podkategoriach stad moje pytanie jak pobrac podkategorie i ich wszystkie cechy ?
1 czyli Mam np. kategorie Elektronika a ja chce miec to co jest pod nia, telefony i akcesoria (smartwatche, smartfony...), i tak wszystkie podkategorie i ich dzieci z wszystkich kategorii.
2 jak pobrac cechy wszystkich podkategorii ?

ps. autoryzuje sie za pomoca tokena a grant type to client_credentials
moj client id "bcd26b653a5344139f2c089faf4aa..."

prosze o podanie metod url jak pobierac sub kategorie i ich cechy i czy jest to mozliwe w waszym API

**Comment by AureliuszBrussy** [comment]
Skorzystaj z [GET /sale/categories?parent.id={categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) - dzięki temu pobierzesz listę kategorii, które należą do podanej kategorii nadrzędnej (czyli dla wskazanego query parametru **categoryId**). W ten sposób możesz pobierać kolejne kategorie, aż trafisz na kategorie najniższego rzędu, z wartością “leaf”: true. 

Parametry dostępne w konkretnej kategorii pobierzesz za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

Dla pobrania powyższych danych wystarczy autoryzacja typu client_credentials.

**Comment by sygmak** [comment]
Dzieki! 
co do parameters to znalazlem w dokumentacji juz wczesniej ale nie bylem pewnien czy to daje cechy, ale jesli tak to OK.
co do kategorii to super sprawa z tym parent.id
Pobralem rekurencyjnie 24 780 podkategorii i ich potomnych nie liczac tych 13 glownych kategorii czy to (24 780) sie zgadza ?

**Comment by AureliuszBrussy** [comment]
Tak, taka liczba kategorii aktualnie jest prawidłowa, jednak miej na uwadze, że może się ona zmieniać - może się zdarzyć, że usuniemy, dodamy czy przesuniemy kategorie. 

Żeby śledzić zmiany, możesz korzystać z dziennika zmian w kategoriach. Więcej o tym zasobie przeczytasz w [naszym poradniku](https://developer.allegro.pl/my_offers/#dziennik-zmian-w-kategoriach). 

Korzystamy z UTF-8.
