### ISSUE TITLE
Zablokowany użytkownik na Sandbox

### ISSUE THREAD

**Issue by marta7142** [allegro/allegro-api#4177]
Dzień dobry,
Próba pozyskania tokenu autoryzacyjnego dla użytkownika allegro-standard-test@euro.com.pl kończy się błędem 429 Too Many Requests. 
Wg dokumentacji konto jest blokowane przy 20k requestów/minutę na 1 minutę, od 2 dni mam problem aby pobrać token, mam wrażenie, że konto zostało trwale zablokowane.

**Comment by AureliuszBrussy** [comment]
Wskazanie konto nie jest zablokowane. Nie widzę także w logach żadnych requestów powiązany ze wskazanym kontem. 

Prześlij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) swój pełen request w formacie curl, a także pełen response, który otrzymujesz. W zgłoszeniu przekaż numer wątku na GitHubie: #4177.

**Comment by AureliuszBrussy** [comment]
Dziękuję za przesłanie danych w formularzu. Widzę, że próbujesz wykorzystać na Sandboxie refresh_token ze środowiska produkcyjnego. W pierwszej kolejności - sprawdź proszę poprawność używanego tokena.
