### ISSUE TITLE
Trener sprzedaży - kampanie

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4178]
Dzień dobry 
Czy jest możliwość otrzymania po API listy pasujących moich aukcji do kampanii, typu: "Znaleźliśmy 200 ofert spełniających kryteria programu ..." Chodzi o dane z tych 200 ofert spełniających kryteria. Podsyłam widok rekordu 
![2021-02-17_13h53_18](https://user-images.githubusercontent.com/74404770/108208194-010a9280-7129-11eb-83cb-757427f052e1.png)

**Comment by AureliuszBrussy** [comment]
Aktualnie nie udostępniamy w API Allegro takiej funkcjonalności.
