### ISSUE TITLE
Pytanie o produktyzację [Motoryzacja]

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4179]
W kategorii wkłady lusterek mamy opcję offerWithProductPublicationEnabled:true.
Jak użytkownik wystawia ofertę przez formularz to na dole ma checkbox'a "Przy wystawianiu oferty stwórz jednocześnie produkt".
Czy z poziomu API jest pole w drafcie, które odpowiada za tworzenie produktu z oferty lub nie?

**Comment by AureliuszBrussy** [comment]
W drafcie oferty w API Allegro (zasób **/sale/offers/{offerId}**) nie udostępniamy takiej flagi - nie utworzysz produktów w ten sposób.

Propozycję produktu możesz dodać za pomocą [POST /sale/product-proposals](https://developer.allegro.pl/productization/#6-jak-doda%c4%87-produkt). Opisujemy w [naszym poradniku](https://developer.allegro.pl/productization/#6-jak-doda%c4%87-produkt), jak to zrobić. 

Produkt utworzymy także, gdy skorzystasz z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). Ten proces opisujemy z kolei w [tym poradniku](https://developer.allegro.pl/product_offers/).

**Comment by kfijalko** [comment]
Coś mi się nie zgadza.
Dziś w bazie produktów znalazłem produkty utworzone na podstawie moich ofert.
Zawierają: tytuł, parametry, zdjęcia z moich ofert.
Nie tworzyłem tych produktów.
Nie chcę też żeby były tworzone na podstawie moich ofert.

Jak doszło do utworzenia produktów?

**Comment by autoswiss** [comment]
To nie nowość, że wykorzystują utworzone produkty i nawet zdjęcia.

**Comment by AureliuszBrussy** [comment]
@kfijalko wzbogacamy dane naszego Katalogu Produktów oparciu o dane z wystawionych ofert, więc i w ten sposób mogą powstać produkty - nie w trakcie, a po wystawieniu oferty.

**Comment by kfijalko** [comment]
@AureliuszBrussy ok, tylko, że do produktu dodaliście moje zdjęcia.
Nie mam problemu ze zdjęciami, które prezentują sam produkt na białym tle.
Jak przeczytałem w jednym uzasadnieniu wyroku sądowego "nie ma w nich iskry Bożej" (czy jakoś tak). Ok.

Natomiast w ofertach mam jedno zdjęcie prezentujące produkt w określonej aranżacji. Z modelem samochodu i modelem ludzkim. Zgodnie z regulaminem jest to dozwolone na zdjęć w galerii.
Mam zastrzeżenia do użycia przez innych tego właśnie zdjęcia.
Zgodnie z Waszym poradnikiem
https://allegro.pl/dla-sprzedajacych/prawa-autorskie-do-zdjec-WEYAYdlgacB
"Chcesz wykorzystać do swojej oferty cudze zdjęcie? Musisz mieć na to zgodę autora."
Ja takiej zgody nie udzielam.

**Proszę żebyście usunęli to właśnie zdjęcie z produktów utworzonych na podstawie moich ofert.**

Poza tym moglibyście działać bardziej transparentnie.
Nie przypominam sobie żadnego komunikatu mówiącego o automatycznym tworzeniu produktów na podstawie ofert.
W Waszym regulaminie jest mowa tylko o świadomym dodawaniu produktu przez użytkownika:
https://allegro.pl/regulamin/zalacznik/10
nie ma mowy o automatach.
W załączniku o "bazach Allegro" też nie ma mowy o automatycznym tworzeniu produktów z ofert:
https://allegro.pl/regulamin/zalacznik/11

Przejrzałem regulamin allegro i nie znalazłem też zapisów, które pozwalają na takie działanie jak: tworzenie produktów na podstawie ofert i udostępnianie tych danych innym użytkownikom (w tym zdjęć).

Oczywiście mogę się mylić. Proszę mnie wyprowadzić z błędu.

**Comment by AureliuszBrussy** [comment]
@kfijalko działanie takiej z naszej strony jest możliwe na podstawie punktu 5.5 [Regulaminu Allegro](https://allegro.pl/regulamin). Wszelkie uwagi tego dotyczące możesz zgłosić przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a2f3ea49-2579-47d5-87f4-6d96a42e3e86&subjectId=ae7b20da-ee49-4df4-90ed-39e32533ed8c). 

Same uwagi dotyczące konkretnych produktów możesz także zgłosić przez [formularz wystawiania](https://allegro.pl/offer/) - po wybraniu konkretnego produktu pojawi się opcja "Zgłoś błąd w produkcie".
