### ISSUE TITLE
Rest API informacje o ofertach - EAN

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#418]
Dlaczego metoda offers-listing  nie zwraca numeru EAN dla aukcji z innych kont niż aktualny kontekst access tokena?

**Comment by TomekKaczmarek** [comment]
@sis6326r Z tego co wiem, ten zasób nie zwraca EANu. Podaj proszę cURL, który wysyłasz w requeście - sprawdzimy temat.

**Comment by sis6326r** [comment]
Zgadza się, dlaczego pytam dlaczego nie zwraca skoro mógłby:)?

**Comment by TomekKaczmarek** [comment]
@sis6326r Zasób mógłby zwracać wiele danych. Jest jednak odpowiednikiem naszej listy ofert i wyszukiwarki na froncie. Takich danych nie zwracamy na froncie, nie planujemy ich też na razie zwraca. Do czego ich potrzebujesz w danych zwracanych w tym zasobie?

**Comment by sis6326r** [comment]
@TomekKaczmarek EAN jest przydatny do jednoznacznej identyfikacji produktu. Zapewne wiecie jak bardzo jest ważny skoro zrobiliście go parametrem obowiązkowym:)

**Comment by TomekKaczmarek** [comment]
@sis6326r Dzięki. Sugestię przekazałem do odpowiedniego zespołu.
