### ISSUE TITLE
Propozycja produktu - UnableToCreateProductWithoutAllIdentifyingParametersException

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4180]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

gdy wysyłamy propozycję produktu (zasób sale/product-proposals) w odpowiedzi otrzymujemy błąd sugerujący, że nie podaliśmy wszystkich parametrów podstawowych. Jakie to są parametry podstawowe i w jaki sposób możemy je oznaczać? Dołączam request i response:

- [request.txt](https://github.com/allegro/allegro-api/files/6001095/request.txt)
- [response.txt](https://github.com/allegro/allegro-api/files/6001094/response.txt)

**Comment by AureliuszBrussy** [comment]
W twoim requeście brakuje jednego parametru identyfikującego produkt: Typ publikacji (id parametru: **5026**).  

Żeby sprawdzić, jakie parametry niezbędne są do utworzenia produktu, skorzystaj z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Wszystkie takie parametry mają wartość **"true"** w polu **"requiredForProduct"**.

**Comment by fabianCyfran** [comment]
Rozumiem, dziękuję
