### ISSUE TITLE
Śledzenie przesyłek z WZA

### ISSUE THREAD

**Issue by tburton12** [allegro/allegro-api#4181]
Dzień dobry.
Chciałbym zapytać o możliwość śledzenia przesyłek w Api.
Wiem tyle, że numer śledzenia można pobrać endpointem Get a list of parcel tracking numbers. Żadnego endpointu do śledzenia natomiast nie znalazłem.

Pozdrawiam
Paweł

**Comment by AureliuszBrussy** [comment]
W ramach API Wysyłam z Allegro nie udostępniamy endpointu pozwalającego na śledzenie przesyłki. Możesz go sprawdzić jedynie u przewoźnika na podstawie numeru listu przewozowego.

**Comment by tburton12** [comment]
W porządku. Dziękuję za odpowiedź
