### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by gorskimarcin96** [allegro/allegro-api#4182]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,
wcześniej korzystaliśmy z hostingów zenbox i nasza aplikacja działała bezproblemowo. Przenieśliśmy aplikację do azure i mamy problem z żadaniami API, mnóstwo mam błędów z timeout'em. 

Tutaj państwo pisali, że występował problem ze względu lokalizacji serwerów. Zgaduję, że mam ten sam problem. https://github.com/allegro/allegro-api/issues/1393#issuecomment-477075625

**Comment by AureliuszBrussy** [comment]
Podaj proszę swój Client_ID oraz przykładowy request oraz response, gdzie trafiłeś na timeout. Zweryfikujemy to.

**Comment by gorskimarcin96** [comment]
Request: GET - https://api.allegro.pl/offers/listing?phrase=yerba

Response: Failed to connect to api.allegro.pl port 443: Connection timed out

Client_ID: f5d74f3a8f52400eae28c449c9b64749

Przy requestach przy użyciu tokenów użytkowników jest to samo, nasze wykorzystywane konta:
naturaleza_pl
matemundo_pl
TeaGuayusaCOM

**Comment by AureliuszBrussy** [comment]
Zgłosiłem ten problem do odpowiedniego zespołu. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Aktualnie nie stwierdzamy podobnego problemu jak w wątku #1393. Spróbuj wydłuż connect-timeout w swojej aplikacji.

**Comment by gorskimarcin96** [comment]
Ustawiłem CURLOPT_TIMEOUT_MS na 5 minut, pomimo to nadal występuję ten problem.

**Comment by AureliuszBrussy** [comment]
Rozumiem, dziękuję za informację. Konsultuję jeszcze Twoje zgłoszenie z innym zespołem. Wrócę do Ciebie z odpowiedzią.
