### ISSUE TITLE
i can' t take device code in production api(https://allegro.pl/auth/oauth/device)

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4184]
i use sandbox and it works;
curl --location --request POST 'https://allegro.pl.allegrosandbox.pl/auth/oauth/device?client_id=e8ada22***e4761b' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: datadome=Ya1gUOEhY6iev-H4W6OeiYVkBA5UmrVQ-b4lbiy-d2dUq4PKbc60EG.o2Ao-i5In_At9p8xp~SOD8Cx94l1uS73wCzWHmo9VeRdsFMMEpw; TEST_QXLSESSID=793e3bef47644669b8d439c16904985f5c0adc3a0bcc68//00; _cmuid=gdk7xszt-7a0a-5kzh-y78e-dnajkb8x4thn; ws3=LF3uHK2CBFmG6RQBJyGXDiHTwmJrDDytz'

but when i use, production api, it returns error;
curl --location --request POST 'https://allegro.pl/auth/oauth/device?client_id=2aba7fc***088f82' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: QXLSESSID=8a081c3e6b69414209a65ec74839c2668592cc54030b7b//02; _cmuid=q1qyue91-4hcf-5d08-zpnm-ptatzkp6mfpp; datadome=9Kx98lbbKb-ozhXhr8Z9YFCGs~oWjeUSJ~8D7lX_DnxHxxkbKR~8wJ6vpxbznQEg5-S0cdauZK9U~VWxl-bdTSQS7Rf73WAb8eNYLXe8M6; ws3=LFNrvXYfzfUzxAJ9siJWph2dmFFBiN9Hz'

it returns;
{
    "error": "Unauthorized",
    "error_description": "Unauthorized"
}
Is there something I am missing, can you help me?

**Comment by AureliuszBrussy** [comment]
First of all, you should pass the basic authorization header:

`Authorization: Basic {base64(client_id:client_secret)}
`

Also, pass client_id in your request body, not in the query parameter.

Curl should look like this:

```
curl --location --request POST 'https://allegro.pl/auth/oauth/device' \
--header 'Authorization: Basic base64{client_id:client_secret}' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: xxx' \
--data-urlencode 'client_id={client_id}'
```

**Comment by ymyuceturk** [comment]
Thank you for your quick and accurate answer
