### ISSUE TITLE
Integracja Wysyłam z Allegro

### ISSUE THREAD

**Issue by tubiflex** [allegro/allegro-api#4186]
Dzień dobry,

Posiadamy skonfigurowane konto w BaseLinker, gdzie dodana jest integracja Wysyłam z Allegro. Wygląda, że integracja skonfigurowana jest prawidłowo, gdyż generuje etykiety i nie zwraca żadnego błędu. Parę dni temu wygenerowaliśmy etykietę o numerze (00) 55900773 0 72241534 4 i przy dostarczeniu przesyłki do punktu pocztowego uzyskaliśmy informację, że nie można nadać przesyłki, gdyż "Nie znaleziono pozycji umowy...". W związku z tym wygenerowaliśmy nową etykietę bezpośrednio przez konto Allegro o numerze (00) 55900773 0 72355502 5, która bez problemu została nadana w tym samym punkcie pocztowym. Na początku szukałem rozwiązania tego problemu w pomocy technicznej BaseLinker, ale tam uzyskałem informację, że jeżeli nie występuje błąd przy generowaniu etykiety to nie mogą mi pomóc i muszę skontaktować się z Wami.
Proszę o pomoc w znalezieniu i usunięciu błędu, dlaczego w/w etykieta nie jest respektowana przez Pocztę Polską.

Pozdrawiam
Bartosz Sosiński

**Comment by AureliuszBrussy** [comment]
Problem ten występował po stronie Poczty Polskiej - mamy informację, że został już zdiagnozowany oraz wyeliminowany. Aktualnie nadanie takich paczek w placówkach Poczty Polskiej jest możliwe - błąd nie powinien występować.
