### ISSUE TITLE
Aktywacja konta do wypłat na Sandbox

### ISSUE THREAD

**Issue by gkurelewicz** [allegro/allegro-api#4187]
Od bardzo dawna czekam na aktywację konta do wypłat środków na sanbox.
Próbowałem PayU i P24 bez skutku.

Proszę o aktywację na koncie vadegi99999

**Comment by AureliuszBrussy** [comment]
Konto do wypłaty środków na Sandboxie zostało aktywowane. Powinieneś mieć już możliwość przetestowania tej funkcjonalności.
