### ISSUE TITLE
Dalekie IP

### ISSUE THREAD

**Issue by DudaMarcin** [allegro/allegro-api#4188]
Mam pewne pytanie, mianowicie korzystam z wtyczki WP Desk, jednak na serwerze który znajduje się w stanach (serwery bluehost) i zastanawiam się, czy allegro nie ma jakiegoś filtrowania zapytań z dalekich IP, ponieważ serwer łączy się z API allegro bez problemów, ale niestety często zwraca błąd. Wygląda to na istną ruletkę, raz działa import, raz nie działa nie ma żadnego schematu poza tym, że jak raz nie zadziała to potem trzeba odczekać, aby znowu zadziałał.

Przesyłam 3 filmiki tłumaczące problem, bo walczymy z tym już dobry miesiąc. 
https://www.loom.com/share/3ed38883894641e69e2ebb6a38c73f56?sharedAppSource=personal_library
https://www.loom.com/share/bbeeab2f4097433ab91aae2c2fde5919?sharedAppSource=personal_library
https://www.loom.com/share/c5360db31bfb4161bfb6bb5f58aa213b?sharedAppSource=personal_library

Przesyłam również screeny jak wygląda błąd:
![Allegro - Błąd - Rękawice Narciarskie Dawid](https://user-images.githubusercontent.com/16838723/108492478-81560280-72a5-11eb-9a80-c6cbbc82f0e6.png) <- tutaj ni działa
![Allegro - Błąd - Rękawice narciarskie dawid - Allegro się odbraziło](https://user-images.githubusercontent.com/16838723/108492501-8a46d400-72a5-11eb-89f1-1a01fff581f3.png) <- a tutaj jednak działa

Jeśli chodzi o zapytania cURL to wszystko wygląda ok:
yybgovmy@yyb.gov.mybluehost.me [~]# curl -v api.allegro.pl:443
* About to connect() to api.allegro.pl port 443 (#0)
*   Trying 5.134.213.11... connected
* Connected to api.allegro.pl (5.134.213.11) port 443

Jak widać na filmikach, jest to ruletka, sprawdziłem wtyczkę na serwerze w Polsce i działa ok, także jedyną różnicą jest odległość. 

Stawialiśmy wcześniej na filtrowanie serwera czy coś no ale nie może to być problem, jak raz działa, raz nie działa.

Proszę o jak najszybszą odpowiedź co mógłbym zrobić (poza przeniesieniem się na serwer w polsce).

Serdecznie pozdrawiam :)

**Comment by DudaMarcin** [comment]
A no i jest to serwer na shared hostingu :)

**Comment by AureliuszBrussy** [comment]
Konsultuję Twoje zgłoszenie z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią.

**Comment by rtnet-pl** [comment]
500tka jest po stronie Twojego serwera. Przejrzyj logi, patrząc na filmiki to możesz mieć za niski max_execution_time  lub memory_limit.

**Comment by DudaMarcin** [comment]
Memory limit 1024M także chyba wystarczający, max_execution_time 300, do ilu by go zwiększyć?

**Comment by DudaMarcin** [comment]
Cóż zwiększyłem max_execution_time do 10 000 i też nie pomogło :< 

Czy moglibyście spojrzeć na poje phpinfo, aby pokierować mnie w dobrą stronę :) 

https://mojadomenanawszystko.com.pl/phpinfo.php

**Comment by AureliuszBrussy** [comment]
@DudaMarcin czy możesz jeszcze pokazać jaką odpowiedź otrzymałeś z serwera w konsoli (tak, aby było widać co aplikacja rzeczywiście zwraca)?
