### ISSUE TITLE
Autoryzacja i pozyskiwanie access tokena dla dwóch kont Allegro

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#4189]
Dzień dobry,

Mam pytanie dot. pozyskiwania access tokena poprzez OAuth, gdy integracja z REST API dotyczy dwóch różnych kont Allegro. Sytuacja wygląda tak:

1. Użytkownik uruchamia link https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=ID_KLIENTA_1&redirect_uri=POWROTNY_URI_DLA_KONTA_1.
2. Loguje się w allegro.pl na pierwsze swoje konto.
3. Allegro przekierowuje na POWROTNY_URI_DLA_KONTA_1, w adresie dostarczany jest parametr code.
4. Używając otrzymany code, a także zapisany w konfiguracji systemu clientId, clientSecret pobierany jest accessToken do konta #1.
5. Użytkownik uruchamia link dla konta drugiego: https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=ID_KLIENTA_2&redirect_uri=POWROTNY_URI_DLA_KONTA_2.
6. **Po krokach 1-4 jest już zalogowany do Allegro, ale na konto pierwsze (nie wylogował się z serwisu)!** Allegro przekierowuje na POWROTNY_URI_DLA_KONTA_2, w adresie dostarczany jest parametr code.
7. Używając otrzymany code, a także zapisany w konfiguracji systemu clientId, clientSecret pobierany jest accessToken do konta ... ponownie pierwszego, a nie drugiego.

Pytanie jest takie, czy takie zachowanie jest poprawne? Rozumiem, że klient był zalogowany ciągle na  konto pierwsze, ale uruchomiony link żądał o code do konta drugiego. Następnie ten code został użyty w żądaniu curl do pobraniu access tokena dla konta drugiego, a otrzymywany jest ten dla konta pierwszego.

Czy dostarczyć Państwu client IDs, na których zaistniała taka sytuacja?

**Comment by MaciejFrackowiak** [comment]
Tak, to jest zachowanie poprawne, ponieważ operacja została wykonana w tej samej przeglądarce, gdzie potwierdził zalogowanie do konta nr 1 i tam trwa sesja - nie wylogował się, więc działa w kontekście konta nr 1.
Jeżeli chce autoryzować kolejne konto, to powinien wylogować się z konta nr 1 lub przeprowadzić operację w oknie prywatnym.

**Comment by AlpanetPL** [comment]
Dziękuję za odpowiedź. Jeszcze dwa pytania: Czy w takiej sytuacji wysyłanie cliend_id ma jakikolwiek sens? Nie powinno działać to w ten sposób, że jeżeli konto, na które zalogowany jest użytkownik, nie zgadza się z żądanym client_id to nie jest przydzielany code, tylko zwrócony powinien być jakiś błąd?

**Comment by MaciejFrackowiak** [comment]
Dany clientID może obsługiwać różne konta użytkowników, zatem nie jest wyznacznikiem unikalności per konto.

**Comment by AlpanetPL** [comment]
Rozumiem. Dziękuję za odpowiedzi.

**Comment by kfijalko** [comment]
@AlpanetPL możesz wyświetlić użytkownikowi ekran z informacja na jakie konto jest zalogowany
prompt=confirm
dodatkowo możesz rozkodować token i sprawdzić, dla jakiego id kont został wystawiony i dodatkowo w aplikacji poinformować go o konieczności przelogowania na allegro.

Poczytaj tez o OAuth2, dla obydwu kont możesz mieć jedną aplikację w allegro i jeden redirect uri.
Wysyłając żądanie "łączące" konto z aplikacją masz parametr status, w którym możesz sobie "coś" przesłać. Allegro w odpowiedzi zwróci to pole.

**Comment by kfijalko** [comment]
@AlpanetPL jeżeli masz użytkowników zewnętrznych (nie informatycznych) to nie będą znali swojego id konta allegro.
Możesz po połączeniu konta z Twoją aplikacją odpytać zasób /me, który zwróci dane konta. Na ich podstawie zweryfikować czy użytkownik łączy poprawne konto.

**Comment by AlpanetPL** [comment]
@kfijalko Dziękuję. Podsunąłeś mi pewien pomysł na dodatkowe sprawdzenie ;-).
