### ISSUE TITLE
Bug w doGetRefundsList

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#419]
Chciałbym zapytać w jaki sposób są sortowane wyniki w doGetRefundsList. W opisie, w podtablicy jest napisane:

"Lista zwracana jest od najnowszego wniosku."

Jak należy to rozumieć? Wysłałem właśnie zgłoszenie na email gdzie udowadniam iż jest to kolejność losowa, a nie chronologiczna. Załączyłem wynik bez nałożonych filtrów, wykonałem metodę z parametrami sessionId oraz resultSize=1000, nic więcej.

[Ticket#1249628736]

**Comment by TomekKaczmarek** [comment]
@amarel123 Załącz proszę request i response w formacie XML, które potwierdzają występowanie błędu.

**Comment by amarel123** [comment]
@TomekKaczmarek wysłałem plik xml.txt w załączniku w odpowiedzi na maila. Proszę o sprawdzenie.

**Comment by TomekKaczmarek** [comment]
@amarel123 niestety maila z GitHuba z załącznikiem nie otrzymałem. Możesz skorzystać z naszego [formularza kontaktowego](https://allegro.pl/pomoc/faq/problem-w-api-allegro-D5VjMgEdGha), gdy wyślesz zgłoszenie, wklej tu proszę jego nr. Sprawdzimy temat.

**Comment by amarel123** [comment]
@TomekKaczmarek Ticket#1249704647

**Comment by TomekKaczmarek** [comment]
@amarel123 Dzięki, faktycznie jest błąd. Przekazałem do odpowiedniego zespołu.

**Comment by amarel123** [comment]
@TomekKaczmarek czy mogę zapytać jaki jest przewidywany czas naprawy, np. czy będą to dni/tygodnie/miesiące/lata? Trochę ticketów z grudnia i stycznia za kilka miesięcy dobije mi do "lat" :) Na niektóre dopiero po kilku miesiącach czekania otrzymałem odpowiedź, że nikt nad tym nie pracuje i żeby sobie poczekać rok aż to będzie w nowym API działać prawidłowo. Raz nawet zdarzyło się, że zamiast poprawić błąd, poprawiono dokumentację techniczną żeby była z nim zgodna :D Nie wiem czy mam się nastawiać na rezygnację z tej funkcjonalności czy czekać cierpliwie.

**Comment by TomekKaczmarek** [comment]
@amarel123 Przyznam szczerze, że trudno mi odpowiedzieć na to pytania. Póki co mamy tylko jedno zgłoszenie tego problemu, a dane, które zwracamy w odpowiedzi możesz też posortować we własnym zakresie. Stąd inne zadania mają aktualnie większy priorytet.

**Comment by TomekKaczmarek** [comment]
Wysłałem monit do zespołu, który jest odpowiedzialny za naprawę tego błędu. Jak tylko coś ruszy się w tym temacie, damy znać.
