### ISSUE TITLE
/sale/products how to filter by parameters

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4190]
we used this method and the directions from the document but we couldn't filter
we also want to use multiple parameter filters and phrase filter together

our sample, we tried to filter by  54 - Rozmiar, 15851 - Płeć,
https://api.allegro.pl/sale/products?parameters.54=54_5&parameters.15851=15851_4&phrase=sweter

**Comment by MaciejFrackowiak** [comment]
You can use dynamic filters only if you search in the category, so you should narrow your search query.
Please, look into [our tutorial](https://developer.allegro.pl/en/productization/#how-to-find-a-product) where we described how to find a product.
