### ISSUE TITLE
numer oferty - typ danych

### ISSUE THREAD

**Issue by gorskimarcin96** [allegro/allegro-api#4191]
Dzień dobry, zastanawiam się nad sposobem przechowywania danych, jeśli chodzi o numer oferty. Czy numer oferty zawsze jest i będzie liczbą całkowitą? Czy mogą się znaleźć tam jakieś znaki? I czy mogą się pojawić zera z przodu? Z tego co mi wiadomo kiedyś na allegro miało takie oferty.

**Comment by MaciejFrackowiak** [comment]
Tak, zawsze był i będzie liczbą całkowitą, rosnącą. Nie ma dodatkowych znaków, nie pojawia się na początku 0.

**Comment by gorskimarcin96** [comment]
Dziękuję, za odpowiedź.
