### ISSUE TITLE
Kategoria nie istnieje - produktyzacja

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4194]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W produktach **88678767-4a11-4bde-97ac-b86d5086a1ec** i **3b655544-e4e6-4e2e-854b-1848c25bd8e7** jest przypisana kategoria: **260950**. Dostaję 404 jak próbuję pobrać jej szczegóły.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Zmieniliśmy błędną kategorię w produkcie. 

Następnym razem jeśli problem będzie dotyczył produktu, a nie bezpośrednio API proszę o zgłoszenie przez formularz https://allegro.pl/offer/product/report/{id}, gdzie id to id produktu.

**Comment by TomaszSzydlowski-sudo** [comment]
Ok, tak będę robił. Dzięki
