### ISSUE TITLE
Internal Server Error dla /sale/offers

### ISSUE THREAD

**Issue by WildSparrow** [allegro/allegro-api#4195]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
https://api.allegro.pl/sale/offers?publication.status=INACTIVE&publication.status=ACTIVE
od dnia wczorajszego, godzin wieczornych zwraca INTERNAL_SERVER_ERROR.

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem logi i wynika z nich, że korzystasz z autoryzacji typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. Stąd błąd 500 (Internal Server Error). 

Dla wskazanego zasobu wymagany jest: bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device flow](https://developer.allegro.pl/auth/#DeviceFlow))

**Comment by WildSparrow** [comment]
Dziękuję za odpowiedź. Gdyby nie internal (który mnie zmylił) pewnie nie zgłaszałbym błędu, uważałem że może to być coś poważniejszego.
