### ISSUE TITLE
Dostęp do zasobu API

### ISSUE THREAD

**Issue by jensej** [allegro/allegro-api#4196]
Dzień dobry,
Kontaktowałem się w tej sprawie z supportem allegro i zostałem skierowany do Państwa.
W korespondencji prowadzonej z supportem, prosiłem o informację na temat wymagań odnośnie otrzymania dostępu do zasobów API ADS, Pan Łukasz skierował mnie do Państwa.
Proszę o wiecej informacji jak uzyskać taki dostęp.
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Nie jest to publiczny zasób, w związku z czym nie możesz uzyskać obecnie do niego dostępu. Jeśli zdecydujemy się na jego wdrożenie w przyszłości, zamieścimy wówczas osobny post na GitHub oraz komunikat w [aktualnościach](https://developer.allegro.pl/news/).

**Comment by jensej** [comment]
Czy istnieje możliwość otrzymania dostępu do niego poprzez jakieś zgłoszenie, opłatę?
Domyślam się że istnieją jakieś warunki współpracy ponieważ Baselinker oferuję taką usługę.
Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
Nie ma obecnie możliwości, aby otrzymać dostęp do tych zasobów “na życzenie”.

**Comment by jensej** [comment]
Panie Łukaszu rozumiem że nie można dostać dostępu do tych zasobów "na życzenie".
Proszę mnie nakierować z kim powinienem się skontaktować aby ustalić opowiednie warunki dla obydwu stron.
Obsługuję 70 klientów którzy na pewno przyczynią się do zwiększenia Państwa zysków.

**Comment by Lukasz-Zurek** [comment]
Nie są to zaosby publicznego API, dlatego nie jesteśmy właściwym kanałem w tego typu kwestii. Proszę skorzystaj z f[ormularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=76428715-3f41-46f3-ab54-23a87576aae0&subjectId=3ea6fb58-bd64-4c5c-8839-cdfec1edd423) i tam opisz swój profil działania.
