### ISSUE TITLE
parametry `ambigious`

### ISSUE THREAD

**Issue by mariuszthecoder** [allegro/allegro-api#4197]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
**request:**
'parameters': [{'id': '215858', 'values': ['509T-Wx10']}, {'id': '225693', 'values': ['5060590381106']}, {'id': '23910', 'valuesIds': ['23910_26']}, {'id': '202269', 'valuesIds': ['202269_210969']}, {'id': '127634', 'valuesIds': ['127634_384881']}, {'id': '208602', 'valuesIds': ['208602_236402'], 'values': ['Does not apply']}]
**response:**
{'errors': [{'code': 'InvalidProductValueException', 'message': "Product has invalid values [ValidatedParameter{parameter=SimpleParameter{id='23910', values=[ParameterValue{id='23910_26', value='Inny'}]}, name='Bulb type', validationErrors=[ValidationError{value='Other', errorType='VALUE_AMBIGUOUS'}]}, ValidatedParameter{parameter=SimpleParameter{id='208602', values=[ParameterValue{id='null', value='Does not apply'}]}, name='Manufacturer', validationErrors=[ValidationError{value='Does not apply', errorType='CUSTOM_VALUE_EXTENDABLE'}]}]", 'details': None, 'path': '/products', 'userMessage': 'Invalid parameter values: [parameter = Bulb type [ Value is ambiguous - Other] , parameter = Manufacturer [ Value not in dictionary - Does not apply]]'}]}

**trace-id** 595afa842ac4f31d

**parametr 23910 Typ żarówki**
wpisuję wartość Inny - teoretycznie poprawna, bo nie ma możliwości wpisania wartości customowych ("ambiguousValueId": "23910_26", "customValuesEnabled": false), natomiast w zwrotce dostaję informację, że wartość jest niejednoznaczna
**parametr 208602 Producent**
tutaj z kolei wybieram wartość customową ("ambiguousValueId": "208602_236402", "customValuesEnabled": true), a w odpowiedzi dostaję informację, że powinienem wybrać ją ze słownika

nie doszedłem z tym problemem do środowiska produkcyjnego, więc nie wiem, czy tam również występuje

**Comment by Lukasz-Zurek** [comment]
Zweryfikuję zgłoszenie i wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
W przypadku parametru: 23910 Typ żarówki - komunikat jest prawidłowy. Jeżeli "customValuesEnabled": false, nie można wprowadzić własnej wartości spoza słownika.

Natomiast jeżeli chodzi o parametr 208602 Producent - problem ten zgłosiłem już do odpowiedniego działu w celu dalszej weryfikacji.

**Comment by mariuszthecoder** [comment]
Z tym, że w przypadku parametru: **23910 Typ żarówki** nie wprowadzam wartości spoza słownika, a informację o niejednoznacznej wartości - "Inny", która się de facto w słowniku znajduje i jest wskazana przez 23910_26 jako ambiguous.

**Comment by Lukasz-Zurek** [comment]
Przy tworzeniu produktu, wymagamy podania danej wartości, która nie jest inna. W zaistniałej sytuacji proszę podać wartość, jaką chciałbyś wprowadzić w polu **"Values"**. Kwestię dotyczącą dodania frazy do słownika przekażę do odpowiedniego działu Serwisu.

**Comment by Lukasz-Zurek** [comment]
@mariuszthecoder Czy problem nadal występuje ? Zweryfikowaliśmy po naszej stronie i błąd dotyczący parametru **208602 Producent** nie jest zwracany.
