### ISSUE TITLE
API-dane

### ISSUE THREAD

**Issue by pyscrapby** [allegro/allegro-api#4198]
Witam! 
Do kogo można napisać w sprawie wykorzystanie ofert z Allegro na innej platformie?

**Comment by MartaNowaczyk** [comment]
Sprecyzuj co dokładnie chcesz zrobić z tymi danymi i czy dotyczy to Twoich ofert.

**Comment by pyscrapby** [comment]
> Sprecyzuj co dokładnie chcesz zrobić z tymi danymi i czy dotyczy to Twoich ofert.

 Tworzę serwis porównujący oferty samochodowe z rożnych platform dla polskiego rynku.  Oczywiście, po kliknięciu na ofertę pochodzącej z Allegro, użytkownik zostanie automatycznie przekierowany na Allegro. Mój portal nie jest platformą ogłoszeniową, prawa do wszystkich ofert w całości należeć będą do Państwa.

**Comment by MartaNowaczyk** [comment]
Zgodnie z pkt. 4.1 c [regulaminu](https://developer.allegro.pl/rules/) REST API niedozwolone jest:
“wykorzystywanie do prezentowania w serwisach konkurencyjnych Ofert (w tym Ofert archiwalnych) publikowanych w ramach Allegro”

W związku z powyższym nie zezwalamy na dzialanie, które opisałeś.

**Comment by autoswiss** [comment]
zapoznaj się z art. 7 dyrektywy 96/9/WE PE zanim zaczniesz cokolwiek działać w kwestii baz danych
