### ISSUE TITLE
wielkość musi być pomiędzy 0 a 650

### ISSUE THREAD

**Issue by stasiubednarek** [allegro/allegro-api#4199]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry,

Przy próbie wystawienie aukcji do kategorii
67537 Elektronika > RTV i AGD > AGD do zabudowy > Płyty grzewcze > Płyty gazowe

otrzymuję z API informację o brakującym parametrze wielkość, którego jednak nie mogę znaleźć w cechach aukcji w tej kategorii.
Z czego może to wynikać?

pozdrawiam,
S.

**Comment by Lukasz-Zurek** [comment]
Podaj proszę trace-id dla wspomnianej próby wystawienia oferty.

**Comment by stasiubednarek** [comment]
Gdzie mogę znaleźć ten trace-id?

**Comment by Lukasz-Zurek** [comment]
Trace-ID otrzymujesz w nagłówku odpowiedzi na wywołanego wcześniej requesta.
