### ISSUE TITLE
Nowy opis jest za długi

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#42]
W starym opisie był jawny limit rozmiaru 65k. Po transformacji do nowego opisu, mimo zmniejszeniu ilości znaków (mniej tagów HTML), mam komunikat "Opis jest za długi".  Jak mam szacować rozmiar nowego opisu żeby móc zdecydować czy go nie przyciąć?

Problem jest istotny ponieważ w jednym z bloków listujemy listę pasujących typów samochodów (marka, model, kod, silnik, moc, rok produkcji), redukcja do poziomu modeli (np Reno Clio) często jest nieprecyzyjna i klienci popełniają błędy. Oczywiście najprościej było by gdybyście mieli gotową integrację z tecdoc ;)

**Comment by KrzysztofLukanowski** [comment]
Nowy opis nie może ważyć więcej niż 40kb. Ilość znaków bywa zmienna, m.in. z uwagi na to, że treść opisu możesz podzielić pomiędzy różnymi sekcjami. Wspomniana waga dot. zarówno treści opisu, jak i znaczników wykorzystywanych w ramach opisu.

**Comment by zulus** [comment]
Brany rozumiem jest pod uwagę cały blob? Czyli escape'owany html wewnątrz json'a, czy dopiero po zdekodowaniu.

**Comment by KrzysztofLukanowski** [comment]
Pod uwagę bierzemy całą zawartość pola z opisem.

**Comment by zulus** [comment]
Dobrze by było umieścić gdzieś tą informacje w dokumentacji albo treści błędu pola. Dzięki
