### ISSUE TITLE
Niespójność w wywołaniach doGetTransactionsIDs

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#420]
Zauważyłem, że wynik działania funkcji (czyli identyfikatory transakcji) zależy czy wywołamy funkcję osobno dla każdej z interesującej nas aukcji, czy zrobimy to raz, dla wszystkich aukcji.

Przykładowo, mam aukcje:
* 4947887198
* 6287769392
* 6691542724
* 6752101962
* 7281609850

Jeżeli wywołam pięć razy doGetTransactionsIDs dla każdej z aukcji osobna - otrzymam w sumie 1321 unikatowych identyfikatorów transakcji (tak wiem, że dwie aukcje mogą zawierać ten sam identyfikator jeżeli zostały razem zawarte w formularzu zakupowym) - nazwijmy ten zbiór t1.

Dane wyglądają OK, tj. są same ostatnie (przynajmniej wg. mnie) - wśród identyfikatorów brakuje 877409259 - ktory jest wg. journala anulowany, a jest 877410604 - który jest opłacony.

Jak wywołam metodę raz, ale podając wszystkie pięć aukcji w wywołaniu - dostaje 1492 unikatowe identyfikatory transakcji - nazwijmy ten zbiór t2.

Z czego, 4 identyfikatory występują w t1, lecz nie w t2 oraz 175 identyfikatorów występuje w t2 ale nie w t1. M.in pojawia się zarówno oczekiwany 877410604 jak i niepożądany 877409259. Skąd ta rozbieżność?

To pseudokod:

```
$item_ids = array(
      4947887198,
      6287769392,
      6691542724,
      6752101962,
      7281609850,
    );

    $t0 = array();
    foreach ($item_ids as $item_id) {

      $request = array(
        'userRole' => 'SELLER',
        'itemsIdArray' => array($item_id),
      );

      $response = $allegro->doGetTransactionsIDs($request);

      $c = 0;
      foreach ($response->transactionsIdsArray->item as $transaction_id) {
        $c++;
        $t0[$transaction_id][] = $item_id;
      }
      var_dump("DODANO dla {$item_id}: {$c}");
    }

    $t1 = array_keys($t0);
    $t2 = array();

    $request = array(
      'userRole' => 'SELLER',
      'itemsIdArray' => $item_ids,
    );

    $response = $allegro->doGetTransactionsIDs($request);

    foreach ($response->transactionsIdsArray->item as $transaction_id) {
      $t2[] = $transaction_id;
    }

    $t2 = array_unique($t2);

    var_dump('COUNT(t1)');
    var_dump(count($t1));
    var_dump('COUNT(t2)');
    var_dump(count($t2));

    var_dump('array_diff(t1,t2)');
    var_dump(array_diff($t1, $t2));
    var_dump('array_diff(t2,t1)');
    var_dump(array_diff($t2, $t1));
```

Wynik (skróciłem):
```
string(26) "DODANO dla 4947887198: 291"
string(26) "DODANO dla 6287769392: 419"
string(26) "DODANO dla 6691542724: 461"
string(25) "DODANO dla 6752101962: 46"
string(26) "DODANO dla 7281609850: 157"
string(9) "COUNT(t1)"
int(1321)
string(9) "COUNT(t2)"
int(1492)
string(17) "array_diff(t1,t2)"
array(4) {
  [140]=>
  int(860947612)
  [447]=>
  int(863556442)
  [704]=>
  int(877636150)
  [1192]=>
  int(874614893)
}
string(17) "array_diff(t2,t1)"
array(175) {
  [16]=>
  int(877409259)
  [36]=>
  int(877086443)
  [44]=>
  int(877030606)
  ...
}
```

**Comment by PawelTaberski** [comment]
Prosiłbym, o podesłanie pełnych requestów i responsów w formacie XML przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=7e8e35b6-d773-4a0a-8d38-c056148165e8). Następnie wklej tutaj numer ticketa, sprawdzimy w czym jest problem.
