### ISSUE TITLE
Błąd w dokumentacji w sale/offer-price-change-commands

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#4200]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Bład w dokumentacji:
Jeżeli używam `INCREASE_PRICE` lub `DECREASE_PRICE` powinienem wypełnić klucz `value` a nie `price` jak to sugeruje dokumentacja. Wypełnienie `price` generuje błąd.

https://developer.allegro.pl/my_offers/#cena
https://developer.allegro.pl/en/my_offers/#editing-many-offers

W znalezionym przezemnie issue na github jest to wyjaśnione i faktycznie, wtedy działa:

https://github.com/allegro/allegro-api/issues/1988#issuecomment-512813610

**Comment by Lukasz-Zurek** [comment]
`"Price"` przekazujesz, jeśli zmieniasz cenę na konkretną wartość `FIXED_PRICE`, czyli informacje zawarte w przykładowym requeście, w poradniku - są prawidłowe. Brakuje jednak doprecyzowania, że w przypadku użycia innych wartości (`INCREASE_PRICE` lub `DECREASE_PRICE`) należy zamienić `"price"` na `"value"`. Doprecyzujemy to w poradniku. Sama [dokumentacja zasobu](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) prawidłowo przedstawia działanie.
