### ISSUE TITLE
422 na  sale/product-offers

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4202]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
sale/product-offers

Dostaje 422 
```
{
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "Invalid HTML subset",
      "details": "Invalid value: <p>TEST</p>",
      "path": "description.sections[0].items[1].content",
      "userMessage": "Invalid HTML subset"
    }
  ]
}
```

**Comment by TomaszSzydlowski-sudo** [comment]
Podobnie jest w sekcji zdjęcia

**Comment by TomaszSzydlowski-sudo** [comment]
```
{
  "errors": [
    {
      "code": "JsonMappingException",
      "message": "Message is not readable.",
      "details": null,
      "path": "images[0]",
      "userMessage": "Invalid request. Please contact the application author."
    }
  ]
}
```
```
    ...,
   "images":[
      {
         "url":"https://a.allegroimg.com/original/11914f/1983edd845158875f953a9191a33"
      }
   ],
    ...
```

**Comment by Lukasz-Zurek** [comment]
Z podanych przykładów wynika, że popełniasz błędy. Zamiast `<p>TEST</p>"` powinieneś wysłać `"<p>TEST</p>"`. Natomiast w przypadku zdjęć nie musisz wysyłać `"url:"`. Skorzystaj proszę z naszego [poradnika](https://developer.allegro.pl/product_offers/).
