### ISSUE TITLE
Pobieranie etykiet przypisanych do zamówień

### ISSUE THREAD

**Issue by Gabbek** [allegro/allegro-api#4203]
Witam serdecznie, chciałbym zapytać czy jest możliwość pobierania etykiet przypisanych do zamówień z poziomu api?

Poniżej dodaję link gdyby były wątpliwości jaką funkcjonalność mam na myśli:
https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/etykiety-w-zakladkach-moje-oferty-i-zamowienia-ZG24qB1RaHO#zamowienia

Próbowałem znaleźć informację na ten temat w dokumentacji, ale najbliższa metoda to ta dotycząca ofert, a ja potrzebowałbym informacji na temat zamówień:
https://developer.allegro.pl/documentation/#operation/listAssignedOfferTagsGET

**Comment by Lukasz-Zurek** [comment]
Nie ma takiej możliwości. W naszym REST API nie ma tego typu zasobu.

**Comment by Gabbek** [comment]
Bardzo dziękuje za odpowiedź.
