### ISSUE TITLE
ID Punktu nadawczego

### ISSUE THREAD

**Issue by OKTAGONPL** [allegro/allegro-api#4205]
Witam 

Zostałem odesłany tutaj przez konsultanta Allegro 
Potrzebuję ustalić "ID punktu nadawczego" dla API Wysyłam z Allegro - konkretnie dla placówki pocztowej UP Nadarzyn ul. Mszczonowska 24

Ten ID potrzebny do powiązania EasyUploader ze wspomnianym Wysyłam Allegro 

Niestety jestem zielony w sprawach API a na oficjalnych poradnikach allegro nie odnalazłem takowej listy 

Dziękuję za wskazówki 

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Podaję ID punktu dla wskazanej placówki: 255290.
