### ISSUE TITLE
TecdocSpecificationNotFound

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#4207]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Odpytanie sale/product z frazą DELPHI CS20517 kończy się błędem:

```
[code] => TecdocSpecificationNotFound
[message] => An error has occurred
[details] =>
[path] =>
userMessage] => Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
```

Powyższy problem występuje również na froncie. Korzystając z https://allegro.pl/offer/ i wpisując DELPHI CS20517 dostajemy błąd "Nie udało się wyświetlić produktów."

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, przekazałem problem do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy uzyskam więcej infromacji.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by Radeq** [comment]
Witam,

@PrzemyslawLukanowski , od wczoraj zauważyłem powrót problemu, czy mógłbyś spojrzeć?

`
responseCode: 404
  +"errors": array:1 [▼
    0 => {#843 ▼
      +"code": "TecdocSpecificationNotFound"
      +"message": "An error has occurred"
      +"details": null
      +"path": null
      +"userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
    }
  ]
`

traceIds
`
GET sale/products?ean=4xxx0 || trace-id:3bcf1883ff2d16a2
GET sale/products?ean=4xxx1 || trace-id:712913eae5a83e1d
GET sale/products?ean=4xxx7 || trace-id:77f56fe819c27422
`

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Tak, przekazałem już problem do odpowiedniego działu. Po wdrożeniu poprawki poinformuję w wątku.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Wprowadzilismy odpowiednią poprawkę, produkty zwracamy już prawidłowo.

**Comment by dlis2010** [comment]
Witam ponownie, problem powrócił :(

Występuje dla fraz:
```
SACHS 315 641
LEMFORDER 34062 01
MAGNETI MARELLI 000723180181
MAGNETI MARELLI 352317100860
MAGNETI MARELLI 357095070100
MAGNETI MARELLI 357265070000
TRW GDB1936
TRW GDB3491
TRW GDB3524
TRW GDB4176
TRW GDB4605
TRW JBJ351
TRW PFK656
TRW PFK717
TRW PFK769
```

**Comment by PrzemyslawLukanowski** [comment]
@dlis2010 Przekazałem problem do odpowiedniego zespołu. Wrócę z informacją po wyeliminowaniu błędu.
