### ISSUE TITLE
Internal server error podczas Autoryzacji

### ISSUE THREAD

**Issue by maximanek** [allegro/allegro-api#4208]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas próby autozycjaci typu Code serwer zwraca error 500 myślałem, że może być jakiś problem ze składnią, że źle konstruuje request ale po wpisaniu danych do Postmana ( razem z nowym jescze aktywnym code zwracanym po połączeniu aplikacji tez dostaje Internal Server Error

`
function getCodeToken(Request $request)
    {

        $response = Http::withBasicAuth('login','hasło')

            ->post('https://allegro.pl.allegrosandbox.pl/auth/oauth/token/', [

                'grant_type' => 'authorization_code',

                'code' => $request->code,

                'redirect_uri' => 'http://localhost:8000/api/orders'

            ]);

        $this->code_token = $response;

        return view('api.allegroapi', ['response' => $response]);
    }
`

`{"error":"server_error","error_description":"Internal Server Error"}`

**Comment by PrzemyslawLukanowski** [comment]
Usuń proszę `/` z  końcówki adresu `https://allegro.pl.allegrosandbox.pl/auth/oauth/token/` w Twoim żądaniu. Powinno to rozwiązać problem.

**Comment by maximanek** [comment]
Dziękuje, w post manie otrzymuje porapwnie token, w swoim kodzie nie ale to ewidentnie blad z mojej strony, dziekuje problem mozna zamknąć :)
