### ISSUE TITLE
Jak uzyskać informacje o kategorii w jakiej znajduje się aukcja

### ISSUE THREAD

**Issue by darekwaw** [allegro/allegro-api#421]
Witam

Kożystając z [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,52) mogłem sprawdzić w jakiej kategorii znajduje się intersująca mnie oferta. 

W jaki sposób mogę wykonać to w RestApi ?

**Comment by sis6326r** [comment]
RTFM;)
https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET

GET na zasobie /sale/offers/{offerId}

zwróci informacje o aukcji m.in.:
"category": {
    "id": "string"
  },

**Comment by sis6326r** [comment]
fakt, w takim razie dołączam się do pytania

**Comment by TomekKaczmarek** [comment]
@darekwaw @sis6326r przecież zasób /offers/listing zwraca informacje o ID kategorii (ostatnia informacja w modelu danych).  Szczegóły znajdziesz w tym artykule https://developer.allegro.pl/news/2018-07-03-Listing_ofert/

**Comment by sis6326r** [comment]
@TomekKaczmarek faktycznie, czyli jednak RTFM ;)

**Comment by darekwaw** [comment]
Ok należy czytac dokumentację. :)

To może inaczej przedstawię mój problem.

Mam kolekcje identyfikatorów aukcji jakie powstały na Allegro w ciągu ostatnich 10 minut.
Przesyłając je do metody doGetItemsInfo sprawdzałem które z nich należą do kategorii które mam monitorować. 

Interesujące oferty pobierałem i analizowałem zgodnie z logiką wyznaczoną prze mojego klienta.

Czy tą samą funkcjonalność będę mógł wykorzystać korzystając z REST API ?

**Comment by TomekKaczmarek** [comment]
@darekwaw czy dobrze rozumiem, że potrzebowałbyś zasobu, który zwróci publiczne dane o ofercie? Mógłbyś w kilku zdaniach opisać w jakim celu? Przekażę sugestię do odpowiedniego zespołu.

**Comment by darekwaw** [comment]
Witam i dziękuję za zaintersowanie.
Opiszę pokrótce co robi aktualnie projekt.
1) Pobieram dziennik zdarzeń za pomocą doGetSiteJournal
2) W pobranej paczce filtruje aukcje które postwały lub się skończyły
3) Skończone aukcje na allegro kasuję z mojej bazy
4) Nowe aukcje pobieram za pomocą doGetItemsInfo
5) Z pobranych aukcji filtruję te które intersują klienta (kategoria, cena itp)
6) Interesujące aukcje zapisuję do bazy

reszta to już wewnetrzna logika ...

Serwis działa i jak na razi enie widzę funkcjonalności która umożliwiła by mu działanie po przejściu na REST API.

**Comment by TomekKaczmarek** [comment]
Dziennika dla ofert na razie nie planujemy. Docelowo zależy nam, by sprzedawcy korzystali z ofert w formacie do wyczerpania przedmiotów. Oferty po statusie będziesz mógł filtrować na liście ofert sprzedawcy, którą wkrótce udostępnimy w REST API.

**Comment by kfijalko** [comment]
Proszę jeszcze o potwierdzenie:
Czy planujecie udostęnienie zasobu podobnego w działaniu do "doGetSiteJournal", który udostęnia 
1) zdarzenia dla wszystkich ofert w serwisie, bez względu na zalogowanego użytkownika
2) zdarzenia dla zalogowanego użytkownika
?

**Comment by TomekKaczmarek** [comment]
@kfijalko Niestety nie.

**Comment by kfijalko** [comment]
No to pewien "popularny serwis z raportami" sprzedażowymi będzie miał problem.
Osobiście korzystam, mam nadzieję, że jakoś to rozwiąże lub Allegro zdąży z własnymi statystykami.
@TomekKaczmarek proszę to uwzględnic w planach.

**Comment by TomekKaczmarek** [comment]
@kfijalko dzięki za sugestię i celną uwagę - przekażę ją do odpowiednich zespołów.

**Comment by dxsoftware** [comment]
Dołączam się do tematu.
dziennik getSiteJournal jest dla mnie bardzo istotny, na jego podstawie wyszukuję daty sprzedaży mojej konkurencji, które dalej wykorzytuję do wniosków jak zwiększyć sprzedaż. Bez tej funkcji będzie lipa.

**Comment by juhacz** [comment]
Używam WebAPI w 90% w podobnym zastosowaniu co @darekwaw , mam wrażenie, jakby opisał mój program. Niestety zamiana WebAPI na REST API zmierza do tego, aby po prostu zniszczyć mój biznes, bo REST API póki co nie daje tyle możliwości co stare API. 
Najpierw wprowadziliście 5 minutowe opóźnienie dziennika, niedługo usuniecie metodę doGetItemsList, ale GET/offers/listing nie zastępuje jej w 100%, brak możliwości wyłuskania aukcji rozpoczętych w ciągu 1h lub kończących się w ciągu 1h, nawet nie zwraca adresu miniaturki..... Czekam na całkowite wyłączenie dziennika i nic, tylko żyły sobie podciąć.

**Comment by darekwaw** [comment]
Rozmawiałem z kilkoma osobami które używają WebApi podobnie jak ja i @juhacz 
Jeśli nie będzie metod umożliwiających pobieranie dziennika zdarzeń oraz pobierania danych publicznych to nasze biznesy będziemy musieli zamknąć.
