### ISSUE TITLE
Problem z transakcją 

### ISSUE THREAD

**Issue by TriRad** [allegro/allegro-api#4210]
Witam
Mam problem z transakcją ecf0cab0-7837-11eb-9b3a-bfa126c215a8 do systemu sprzedażowego przechodzą zupełnie inne dane.
Powinny: Rzepka 
qs8opklg3v+2236b2665@allegromail.pl

a przechodzą: Z.P.H. DAN-MET Henryk Błażejak
orflg76rkn+cff2d018@allegromail.pl

NIe wiadomo skąd. Sprzedaży dla takiego klienta nigdy nie było. Zgadza się produkt ale nie dane wysyłki i jest popowiedziany inny mail. Dlaczego???  

Mój login Allegro lapsi.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij nam proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=c486d322-b6ca-4cb4-9995-fc1ffd340902&subjectId=9aed45c1-1c74-43a6-8989-e01da7a8597d) (dopisz, że dane dotyczą zgłoszenia Github #4210).  Sprawdziłem to zamówienie i po naszej stronie zwracamy prawidłowe dane, tj. `"lastName":"Rzepka","email":"qs8opklg3v+2236b2665@allegromail.pl"`.

**Comment by TriRad** [comment]
Nie wiem za bardzo gdzie tego szukać?? Korzystamy z baselinkera i comarcha optimy do baselinker zamówienie przechodzi prawidłowe ale do comarch już nie. Czy problem może dotyczyć integracji baselinker comarch ???

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji skontaktuj się bezpośrednio ze wsparciem danej aplikacji. Zweryfikują oni problem po swojej stronie.

**Comment by TriRad** [comment]
Ok działam po tamtej stronie. Pozdrawiam
