### ISSUE TITLE
Problem z polem "ean" na ofercie

### ISSUE THREAD

**Issue by wojtasss** [allegro/allegro-api#4212]
Dzień dobry, mamy następujący problem, otóż oferta na Allegro ma uzupełnione pole EAN na ofercie o id 7395903738, jednak przy pobieraniu informacji na temat tej oferty przez API pole "ean" jest puste.

**Comment by Lukasz-Zurek** [comment]
Zgodnie z wcześniejszą [zapowiedzią](https://developer.allegro.pl/news/#ean-eans-remove), od 1 marca 2021 wartość w:

- polu “ean” na GET /sale/offers/{offerId},
- obiekcie “eans” na GET /sale/product/{productId},

ustawiliśmy trwale jako `null.`

W związku z powyższym opisana sytuacja nie ma charakteru błędu.

Od 29.06.2020 [udostępniliśmy parametr globalny numer jednostki handlowej](https://developer.allegro.pl/news/#gtin) tzw. GTIN, którego wartość (czyli EAN, ISBN, ISSN) zmienisz tylko korzystając z parametru. W Twoim przypadku będzie to: EAN (id parametru=225693).

**Comment by wojtasss** [comment]
Czy dobrze rozumiem, że teraz żeby pobrać EAN który jest uzupełniony na ofercie, muszę pobrać parametr o ID 225693 z danej oferty?

**Comment by Lukasz-Zurek** [comment]
Tak, wprowadzony wcześniej EAN zwracany jest w parametrze GTIN, o wartości id: 225693.

**Comment by wojtasss** [comment]
Dziękuję za pomoc, można zamknąć temat
