### ISSUE TITLE
"ConstraintViolationException.ProductizationMinLimitReached"

### ISSUE THREAD

**Issue by OKschroeter** [allegro/allegro-api#4214]
What tells me the following Error-Message? 

Could not activate product with id xxx: { "errors": [ { "code": "ConstraintViolationException.ProductizationMinLimitReached", "message": "You cannot publish offer without a related product because you have too few offers related to a product in that category. Select or create a new product and associate it with your offer.", "details": "ConstraintViolationException.ProductizationMinLimitReached", "path": "null", "userMessage": "Nie mozesz wystawic oferty bez powiazanego produktu, poniewaz masz za malo ofert powiazanych z produktem w tej kategorii. Wybierz lub utwórz nowy produkt i powiaz go ze swoja oferta." } ] }

Do i have to create another category to create an offer? We just tried to update price, quantity and deliverytime iif necessary frequently.

**Comment by Lukasz-Zurek** [comment]
An Error-Message which you've just mentioned, means that you will have to assign a product to your offer. You should have at least 1% or 10% of offers assigned to a product and it depends on the category in which you try to list your offers.

You will find more information about it on our [news page](https://developer.allegro.pl/en/news/#productization-10%-next-categories).

You can use [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) with `product.id.empty=true` parameter to check which offers are not associated with a product.

You can find more information in our guides:

- [Assigning offers to a products](https://developer.allegro.pl/en/productization/),

- [How to list an offer assigned to a product with one request](https://developer.allegro.pl/en/product_offers/)

**Comment by OKschroeter** [comment]
Thanks for your help. We have another Problem while updating an offer:

Throw InternalServerError: { "errors": [ { "code": "INTERNAL_SERVER_ERROR", "message": "Internal server error.", "details": null, "path": null, "userMessage": "Internal server error. Please try again in a few minutes." } ] } Throw InternalServerError: { "errors": [ { "code": "INTERNAL_SERVER_ERROR", "message": "Internal server error.", "details": null, "path": null, "userMessage": "Internal server error. Please try again in a few minutes." } ] } Throw InternalServerError: { "errors": [ { "code": "INTERNAL_SERVER_ERROR", "message": "Internal server error.", "details": null, "path": null, "userMessage": "Internal server error. Please try again in a few minutes." 

is that a problem at your site?

**Comment by Lukasz-Zurek** [comment]
I’ve verified it and as I see you didn’t fill `handlingTime` parameter in your drafts. Provide this value in your offers and you should receive valid response.
