### ISSUE TITLE
Błąd przy połączeniu 

### ISSUE THREAD

**Issue by AlekKlepacz** [allegro/allegro-api#4217]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry, problem z autoryzacją.
Przy próbie połączenia wyświetla komunikat:
Nie możemy wyświetlić strony  
Numer błędu: 8966dc38fdab1771

**Comment by AlekKlepacz** [comment]
id: 50434659

**Comment by Lukasz-Zurek** [comment]
Podałeś nieprawidłową wartość w Redirect URI. Adres podajesz bez “www”, przez co nie jest on spójny z tym, jaki został podany przy rejestracji aplikacji.

**Comment by AlekKlepacz** [comment]
Dziękuje. Powiązałem na nowo i działa.
