### ISSUE TITLE
Pobranie wszystkich kategorii

### ISSUE THREAD

**Issue by aplikacjededykowane** [allegro/allegro-api#4219]
Cześć,

Czy API Allegro daje możliwość wylistowania wszystkich kategorii i powiązanych z nimi wymaganych parametrów niezbędnych do automatycznego wystawiania aukcji wraz z podaniem wartości słowników dla tych parametrów?

Dziękuję.

**Comment by MartaNowaczyk** [comment]
Możesz pobrać kategorie i parametry przez nasze API, tylko nie jednym requestem. Na [stronie REST API](https://developer.allegro.pl/sale/#2-kategorie-i-parametry) Allegro wszystko dokładnie opisaliśmy. Zapoznaj się, a jeśli będziesz miał pytania pisz śmiało.
