### ISSUE TITLE
PUT /sale/offer-modification-commands

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#422]
Zakładam nowy temat , bo poprzedni post pozostał bez odpowiedzi , co jest nie tak z tym żądaniem i po czyjej stronie ?

PUT DATA

{"modification":{"delivery":{"shipingRates":{"id":"8b491b60-3ec2-46a6-8c21-eaa4137c2bab"}}},"offerCriteria":{"offers":[{"id":"7462166484"},{"id":"7461038370"},{"id":"7460119943"},{"id":"7460119993"},{"id":"7462152731"},{"id":"7462152780"},{"id":"7460120064"},{"id":"7461469046"},{"id":"7460120134"},{"id":"7461469083"}],"type":"CONTAINS_OFFERS"}}

RESPONSE

{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-modification-commands/b85490d4-2807-49ea-9c3b-8e905a7fc276/","userMessage":null}]}

HTTP

    Trying 5.134.213.9...
    Connected to allegroapi.io (5.134.213.9) port 443 (#0)
    ALPN, offering http/1.1
    Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@strength
    successfully set certificate verify locations:
    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs
    SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
    ALPN, server accepted to use http/1.1
    Server certificate:
    subject: C=PL; ST=Wielkopolskie; L=Poznan; O=Grupa Allegro sp. z o.o.; CN=*.allegroapi.io
    start date: Mar 8 00:00:00 2017 GMT
    expire date: May 6 23:59:59 2020 GMT
    subjectAltName: allegroapi.io matched
    issuer: C=US; O=thawte, Inc.; CN=thawte SHA256 SSL CA
    SSL certificate verify ok.

    PUT /sale/offer-modification-commands/b85490d4-2807-49ea-9c3b-8e905a7fc276/ HTTP/1.1
    Host: allegroapi.io
    Accept: application/vnd.allegro.public.v1+json
    Content-Type: application/vnd.allegro.public.v1+json
    Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzE5NTg0NjMsInVzZXJfbmFtZSI6IjQzMzY2NTEwIiwianRpIjoiZGNjMGE1MjUtMzkzYS00NmZlLTgzNGQtNGYwM2U5NDZkZjBiIiwiY2xpZW50X2lkIjoiOWEzMDk5MGYtODlmNC00ZmI2LWFhMGItZjYyYzJkYTc5M2NjIiwic2NvcGUiOlsiYWxsZWdyb19hcGkiXX0.YTZVW593JCAeHcUdDtwFaxv-en2NKqjEkggwNGNG80ckQofW5j_CmPMf7dE8QTq4kFYCMvUBwbluDcpvuh2IjIFLq6cKTFfaB5ZdJf5AnpcG8lSZ-p1v2ubO3Ya6nVDRcxfnX5n4oIppIS9NYVd3f3fjZ1Zx1evc7M9pfe29UwC_Giw2u-h_oOP89-X_0ObaP2DHkjfis_BU2mptqiZDhvcCRJlxrd_mDcXniiXydskj4BNO0cEE3ixdGk6NsFs8Ab2jTGUCCu1_OUdT6qWRFTY_NMUSAtP9rMT0jPiBQYt-55MgzRDnXEY3vuW_8YQA6PpDAcEuacSoSSkCY02s4A
    Api-Key: eyJjbGllbnRJZCI6IjlhMzA5OTBmLTg5ZjQtNGZiNi1hYTBiLWY2MmMyZGE3OTNjYyJ9.5lnSUjLDmAyj8CAzqeW_0RdLqM01PmT3r-hOf67wtiU=
    Content-Length: 346

    upload completely sent off: 346 out of 346 bytes
    < HTTP/1.1 400 Bad Request
    < Expires: 0
    < Cache-Control: no-cache, no-store, max-age=0, must-revalidate
    < X-XSS-Protection: 1; mode=block
    < Pragma: no-cache
    < X-Frame-Options: DENY
    < Trace-Id: b4cac98c1303530e
    < Date: Wed, 18 Jul 2018 14:32:44 GMT
    < X-RateLimit-Remaining: 8909
    < X-Content-Type-Options: nosniff
    < Transfer-Encoding: chunked
    < Content-Type: application/json
    < X-RateLimit-Limit: 9000
    <
    Connection #0 to host allegroapi.io left intact

**Comment by sis6326r** [comment]
spróbuj tak:

{
	"modification": {
		"delivery": {
			"shipingRates": {
				"id": "8b491b60-3ec2-46a6-8c21-eaa4137c2bab"
			}
		}
	},
	"offerCriteria": [{
		"offers": [{
			"id": "7462166484"
		}, {
			"id": "7461038370"
		}, {
			"id": "7460119943"
		}, {
			"id": "7460119993"
		}, {
			"id": "7462152731"
		}, {
			"id": "7462152780"
		}, {
			"id": "7460120064"
		}, {
			"id": "7461469046"
		}, {
			"id": "7460120134"
		}, {
			"id": "7461469083"
		}],
		"type": "CONTAINS_OFFERS"
	}]
}

**Comment by sis6326r** [comment]
offerCriteria to array

**Comment by MaciejPotepa** [comment]
Przez kilka dostatnich dni mieliśmy problemy z tym zasobem. Wczoraj go naprawiliśmy. 
Powinien już działać prawidłowo.

**Comment by 11mszot** [comment]
@sis6326r  , po zastosowaniu twojej wskazówki mam coś takiego 

{"errors":[{"code":"VALIDATION_ERROR","message":"modification should contain exactly 1 element","details":"Invalid value: ModificationDto{additionalServicesGroup=null, delivery=DeliveryDto{shippingRates=null, handlingTime=null}, promotion=null, sizeTable=null, payments=null}","path":"modification","userMessage":"modification should contain exactly 1 element"}]}

**Comment by 11mszot** [comment]
zaczęło działać , a przynajmniej już błędu nie zgłasza

{"id":"3d83f10c-a1a6-432f-a0ca-5b71d59576bd","taskCount":{"total":0,"success":0,"failed":0}}
