### ISSUE TITLE
Pobieranie faktur dot. opłat za konto

### ISSUE THREAD

**Issue by therionq** [allegro/allegro-api#4220]
Czy istnieje zasób umożliwiający pobranie faktur wspominanych w tytule?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie udostępniamy takiego zasobu w naszym API.

**Comment by therionq** [comment]
A czy istnieje szansa, że taki zasób zostanie udostępniony w przyszłości?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy tego w planach, dopiszę Twoje zgłoszenie do naszych sugestii dot. rozwoju API Allegro.
