### ISSUE TITLE
Jak zweryfikować aplikację? 

### ISSUE THREAD

**Issue by Adam1610** [allegro/allegro-api#4221]
Dzień dobry 

Jak zweryfikować moje konto i aplikację REST API?

 piszę w związku z komunikatem odnośnie "GET /offers/listing - tylko dla zweryfikowanych aplikacji" https://allegro.pl/dla-sprzedajacych/1-czerwca-2021-w-api-allegro-ograniczymy-dostep-do-publicznych-danych-o-sprzedazy-innych-uzytkownikow-i-zmienimy-forme-ich-udostepniania-O3BlgZVdwCa 

"aplikacje zarejestrowane do dnia 15.03.2021 mają czas na weryfikację do 1.06.2021 - aby przejść proces weryfikacji skontaktuj się z nami przez formularz "

Z formularza odbili mnie tutaj ... (?)

odpowiedź była dość enigmatyczna ...  ¯\_(ツ)_/¯ 

CYTUJĘ: 

"Dzień dobry,

dziękuję za wiadomość.

Widzę, że kwestia, o której Pan napisał, będzie wymagała odpowiedzi zespołu eksperckiego, który zajmuje się wsparciem w sprawach dotyczących API.

Aby przyspieszyć proces weryfikacji sprawy, proszę, by utworzył Pan zgłoszenie na wyznaczonym dla tego typu zapytań forum GitHub:

https://github.com/allegro/allegro-api/issues

Proszę przejść do zakładki Issues, założyć nowe zadanie i skorzystać z odpowiedniego szablonu. Proszę pamiętać, aby w zgłoszeniu podać jak najwięcej dokładnych informacji - dzięki temu szybciej będziemy mogli Panu pomóc."

Co dalej ?

**Comment by DINK74** [comment]
Ale rozumiem, że proces weryfikacji dotyczy tylko aplikacji korzystających z metody GET/offers/listing i pozostałych nie trzeba "weryfikować"?

**Comment by MartaNowaczyk** [comment]
@Adam1610 przepraszam, że Cię tutaj z tym odesłano, takie sprawy powinny być kierowane właśnie przez [formularz](https://allegro.pl/pomoc/kontakt?subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b&kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e). Widocznie ktoś Cię źle zrozumiał. Sprawdzamy co u nas nie zagrało, żeby w przyszłości uniknąć takich sytuacji.

**Comment by MartaNowaczyk** [comment]
@DINK74 weryfikacja dotyczy w tym przypadku tylko GET /offers/listing.

**Comment by PabloMD** [comment]
> @DINK74 weryfikacja dotyczy w tym przypadku tylko GET /offers/listing.

czy można "zweryfikować" teraz integrację i mieć spokój na przyszłość, czy ta weryfikacja jest stricte pod kątem /offers/listing ?

**Comment by MartaNowaczyk** [comment]
@PabloMD stricte pod kątem /offers/listing

**Comment by meridPL** [comment]
Też do was napisałem i na chwilę obecną żadnej odpowiedzi

**Comment by Adam1610** [comment]
W porządku, w takim razie proszę powiedzieć jakie mam podjąć dalsze kroki - używam tej moetody wyłącznie pod potrzeby obsługi transakcji *nie udostępniam* ich na zwenątrz innym użytkownikom (jak np. tradewatch itp.).

**Comment by MartaNowaczyk** [comment]
@meridPL poczekaj jeszcze na odpowiedź, na pewno ktoś odpisze.

**Comment by MartaNowaczyk** [comment]
@Adam1610 postaram się, żeby ktoś się z Tobą skontaktował.

**Comment by Adam1610** [comment]
ok, dzięki, czekam zatem na informację, napisałem wyjasnienie do czego używam metody i mam nadzieję na pozytywne zakończenie :)

**Comment by meridPL** [comment]
@MartaNowaczyk doczekałem się odpowiedzi. Niestety jest ona taka jaka @Adam1610 i nie za bardzo chcę zdradzać szczegóły wszystkiego na publicznym forum :) Z kim w takim razie mam się skontaktować lub czy ktoś może się skontaktować ze mną ?

**Comment by MartaNowaczyk** [comment]
@meridPL po tym co napisałeś pewnie nie uda mi się namierzyć tej korespondencji ;) dlatego najlepiej jak w odpowiedzi na tego maila co dostałeś podasz:
- nazwę aplikacji
- Client ID aplikacji
- uzasadnienie - dlaczego dostęp do GET /offers/listing jest Ci potrzebny
i poprosisz o przekazanie do weryfikacji. 

Niestety tu nie mamy takiej możliwości, by to przeprocesować.

**Comment by meridPL** [comment]
@MartaNowaczyk odpisałem na maila. Jeżeli możesz zobacz ten temat.
Odpowiedź na zgłoszenie nr "14049916" [ ref:_00D24aE05._5003VCSx8o:ref ]

**Comment by MartaNowaczyk** [comment]
@merdiPL sprawa jest już zaopiekowana :)

**Comment by meridPL** [comment]
@MartaNowaczyk super, dzięki. Mam nadzieję, że teraz będę miał w dalszym ciągu dostęp :D

**Comment by Adam1610** [comment]
@MartaNowaczyk  a moja sprawa też jest może zaopkiekowana? :)

Odpowiedź na zgłoszenie nr "14062281" [ ref:_00D24aE05._5003VCT8sv:ref ]

**Comment by MartaNowaczyk** [comment]
@Adam1610 jeśli chodzi o dalsze kroki weryfikacji, nie są mi znane. Czekaj proszę na kontakt z naszej strony lub odpowiedz na miala jakiego dostałeś od naszej obsługi w tej sprawie.

**Comment by Adam1610** [comment]
ok, ... niestety dość opornie to idzie i trochę mnie to niepokoi

**Comment by skazi0** [comment]
@MartaNowaczyk mnie tez odbito z "formularza" tutaj...
```
Odpowiedź na zgłoszenie nr "14067754" [ ref:_00D24aE05._5003VCTF30:ref ]
```

**Comment by MartaNowaczyk** [comment]
@skazi0 dzięki, przekazałam - ktoś powinien się z Tobą skontaktować.

**Comment by Adam1610** [comment]
Proszę jeszcze o opiekę nad tym wątkiem, bo też mnie tu odbijają :(

Odpowiedź na zgłoszenie nr "14062305" [ ref:_00D24aE05._5003VCT9AN:ref ]

**Comment by MartaNowaczyk** [comment]
@Adam1610 przekazane

**Comment by meridPL** [comment]
No i niestety moja aplikacja nie przeszła przez waszą weryfikację przez brak użytkowników i rodzaj konta czego nie rozumiem. Jestem ciekaw jak u innych ? :)
No niestety allegro nie chce działać jak robin hood, a odwrotnie zniszczyć biednych, a bogatym dać wszystko.
Może kiedyś uda mi się przejść waszą weryfikacje albo amazon razem z ebayem was zniszczą czego wam nie życzę :)

**Comment by Adam1610** [comment]
Ja jeszcze nie uzyskałem odpowiedzi i czekam.  

@MartaNowaczyk czy coś może wiadomo? Siedzę , jak na szpilkach :) dzięki :)

**Comment by MartaNowaczyk** [comment]
@Adam1610 podpytaj w korespondencji mailowej jaką prowadziłeś. Ja nie mam takich informacji.

**Comment by Adam1610** [comment]
Dwa z trzech kont nie dostały uprawnień :(  czy można uzyskać informację, jakie są wymagania ? Bardzo tajemniczo i nie transparentnie przebiega proces werfyfikacji. Efekt jest taki, że konta które nie uzyskają dostępu przestaną sprzedawać i zostaną wygaszone, czy o to chodzi Allegro ? Te wymagania to taka tajemnica że nie możecie powiedzieć dokładnie co należy zrobić żeby je spełnić ? O co tu chodzi?!?

**Comment by PrzemyslawLukanowski** [comment]
Kwestia weryfikacji aplikacji jest poza naszym zespołem wsparcia API, dlatego aby poznać powody negatywnej weryfikacji, napisz proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by Adam1610** [comment]
Widzę, że równie skutecznie odbijasz piłkę, co tamci prez formularz. Już pisałem w ten sposób i cisza. Odmowa, ale nie wiadomo dlaczego i jakie są wymagania. Dlatego jest to dla mnie nietransparentne i podejrzane. Powinny być jasno określone wymagania i wtedy mamy czystą sytuację. Teraz jest to mętne.

**Comment by meridPL** [comment]
Już to pisałem kiedyś, że ten zabieg jest po to aby giganci mogli sobie sprawdzać oferty wszystkich mniejszych aby móc dać mniejsze ceny niż oni, a co za tym idzie zwinąć interes z allegro, bo nigdy nie uda się dać niższej ceny niż oni. Baza allegro jest tak tajna, że wystarczyłoby zablokować dostęp chińczykom, którzy kopiują oferty, bo to oni są problemem :) Każdy szanujący się sklep daje taki dostęp tutaj jest odwrotnie, co widać po giełdzie. Poczekamy jeszcze chwilę i sami to odblokują, bo allegro jest tylko polskim wytworem ;) Kilka podwyżek prowizji i ludzie już tam nie będą kupować, bo będą tańsze alternatywy.

**Comment by Adam1610** [comment]
Masz rację, tzn ja wiem jedno - jak już wyjdę z Allegro, to będę na tyle gotowy i rentowny - że już nigdy tam nie wrócę, tego jestem pewny. A póki co świetnie idzie Allegro zniechęcanie Sprzedawców do siebie.

**Comment by Adam1610** [comment]
Chciałem przekazać Wam informację, że aktywacja aplikacji jest tylko dla uczestników programu VIP, czyli bardzo dużych sprzedawców. Nie miejcie złudzeń i nie traćcie nawet czasu, jeśli nie jesteście w tym programie. Trwa eliminacja małych sprzedawców w najlepsze.

**Comment by dave7280** [comment]
> Widzę, że równie skutecznie odbijasz piłkę, co tamci prez formularz. Już pisałem w ten sposób i cisza. Odmowa, ale nie wiadomo dlaczego i jakie są wymagania. Dlatego jest to dla mnie nietransparentne i podejrzane. Powinny być jasno określone wymagania i wtedy mamy czystą sytuację. Teraz jest to mętne.

No coz, mozna sobie radzic i wrocic do parsowania HTML'a. 
U mnie podobnie, odmowa i zero powodu. A aplikacja czysto hobbystyczna.

**Comment by Adam1610** [comment]
Nie jest to takie proste, bo chyba banują od razu IP zgłoszonej aplikacji. Próbowałem i mam błąd 403. Chyba, że macie jakiś sposób , to poproszę na PW :)

**Comment by meridPL** [comment]
Przecież do czerwca jest czas więc jeżeli zbanowali by twój ip to przez API również nie mógł byś się dostać.

Jak coś to spróbuj tego 
https://www.selenium.dev/

Zmieniaj przez proxy ip co request i allegro do końca swej kariery tego nie wychwyci :)

**Comment by Adam1610** [comment]
Racja! Dziękuję :)

**Comment by meridPL** [comment]
Tym bardziej się dziwie, po co allegro takich ruch jak teraz będzie miało większy ruch, ale nie dlatego, że ludzie będą chcieli coś kupić od super sprzedawców, tylko mnóstwo ludzi będzie im scrapowało stronę. Po co nie wiem.

**Comment by Adam1610** [comment]
Ja też nie. Jest to na pewno odsiew sprzedawców, może taki jest cel?  Zostawią kilku największych w każdej branży

**Comment by Adam1610** [comment]
@meridPL

zapraszam do kontaktu na maila w sprawie scrapingu na pewno się dogadamy :) tutaj to może nie jest dobre miejsce do swobodnej rozmowy
 
janekkowalski15002900@gmail.com

**Comment by elvisef** [comment]
Podpinam się do tematu. 

`zgłoszenie numer "16766342" ref:_00D24aE05._5003VHIoMr:ref

zgłoszenie numer "16783571" ref:_00D24aE05._5003V`

Zgłoszenia dotyczą weryfikacji aplikacji. Czekam na odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikacją zajmuje się osobny zespół, prosimy o cierpliwość.
