### ISSUE TITLE
Łączenie w warianty - rozpoznawanie zdjęć

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4222]
> Stworzony mechanizm wielowariantowości jest mechanizmem uniwersalnym tj. ma łączyć po zdjęciu oferty, których przedmiotem sprzedaży jest ten sam towar. Nie sposób nam rozróżnić, że w Twoim przypadku część towarów mających to samo zdjęcie to gatunek pierwszy, a część to gatunek drugi. Aby była możliwość rozdzielenia asortymentu musiałbyś zmienić zdjęcia dla przedmiotów np. z drugiego gatunku - co kluczowe, to mogą być wizualnie te same zdjęcia jednak zapisane / uploadowane raz jeszcze tak, aby miały inny adres URL lub sumę kontrolną.

Czyli wystarczy, że będzie inna ścieżka zdjęcia a zdjęcie będzie identyczne jak w przypadku produktu z I gatunku ?

Pytam dlatego gdyż skopiowanie zdjęcia pod inną nazwą daje identyczną sumę kontrolną.

**Comment by MaciejFrackowiak** [comment]
Na Twoje wątpliwości odpowiedziałem w pierwotnym wątku - https://github.com/allegro/allegro-api/issues/3871.
