### ISSUE TITLE
Nieudana modyfikacja oferty: Usuń z opisu oferty adresy stron zewnętrznych?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4223]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Podczas próby zmiany ilości sztuk otrzymuję VALIDATION_ERROR z komunikatem:

_Usuń z opisu oferty adresy stron zewnętrznych, za pośrednictwem których prowadzona jest sprzedaż poza Allegro. Możesz podać adresy stron, na których umieszczone są jedynie informacje poszerzające wiedzę o oferowanym produkcie._

Nie ma w opisie adresu strony zewnętrznej. 

Przykładowe trace-id: 66e7ccbe4b4c7ee8

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Problem stanowiła fraza “JUNIOR.PL”. Błąd nie powinien już występować.
