### ISSUE TITLE
Błąd przy tworzenie przesyłki 

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4224]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

CommandId: fdf8174f-94a3-49b8-9133-6c07654018cb

Podczas tworzenia przesyłki otrzymujemy błąd: Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem.

Co jest przyczyną błędu?

**Comment by paafcioc22** [comment]
Ten sam błąd przy tworzeniu Allegro Pocztex Kurier 48
--

**Comment by Lukasz-Zurek** [comment]
Weryfikujemy wskazany problem. Wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@marmited Status błędu wynika z nałożonej blokady na Twojej umowie u przewoźnika InPost. W celu wyjaśnień skontaktuj się ze swoim opiekunem handlowym w InPost.

**Comment by Lukasz-Zurek** [comment]
@paafcioc22 Podeślij proszę traceid lub CommandId dla wywołanego wcześniej requesta.

**Comment by marmited** [comment]
@Lukasz-Zurek dziękuję za odpowiedź
