### ISSUE TITLE
Request do GET /sale/products

### ISSUE THREAD

**Issue by DamianDuszny** [allegro/allegro-api#4225]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, jest to moje pierwsze zgłoszenie, jeżeli coś pominąłem, źle napisałem to poproszę o wskazówki jak w przyszłości lepsze posty pisać :). 
Podczas wysyłania requestu pod adres `https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=phrase` często natrafiam na błąd:
`{"errors":[{"code":"TecdocSpecificationNotFound","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}`
Przykładowy request:
    `"Header": [
        "Authorization: Bearer *...*",
        "Content-Type: application/vnd.allegro.public.v1+json",
        "Accept: application/vnd.allegro.public.v1+json",
        "Accept-Language: pl-PL"
    ],
    "url": "https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=lakier"
}`
Dla wielu innych wartości np `phrase=test` zwraca poprawny wynik. W czym może być problem?

**Comment by PrzemyslawLukanowski** [comment]
Taka sytuacja może wystąpić w środowisku testowym, ponieważ nie mamy tam udostępnionej bazy TecDoc. Jeżeli któryś z użytkowników stworzył "sztuczny" produkt, który nie ma specyfikacji technicznej, a jest związany z podaną frazą, to otrzymasz wspomniany przez Ciebie komunikat.
