### ISSUE TITLE
nr zamówienia w billlingu

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#4227]
Jak uzystkać listę prowizji powiązaną z zamówieniami?
Historia operacji billingowych w zasobie GET /billing/billing-entries
niestety nie zawiera tej informacji, a jedynie numer oferty.

**Comment by Lukasz-Zurek** [comment]
Nie uzyskasz listy prowizji posiadając numer zamówienia. Nie udostępniamy tego pola we wskazanym zasobie.
