### ISSUE TITLE
offer-publication-commands - nie zwraca liczby zmodyfikowanych aukcji

### ISSUE THREAD

**Issue by Mbif-dev** [allegro/allegro-api#4228]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Wysyłam request z żądaniem zakończenia aukcji:
`$json=json_encode([
            
            "publication" => [
                "action" => $status,
            ],
            "offerCriteria" => [
                [
                    "offers" =>
                    $offers,
                    "type" => "CONTAINS_OFFERS",
                ]
            ]
        ]);    
        $res = $this->client->request(
            'PUT',
            self::METHOD_URL . 'sale/offer-publication-commands/' . $uuid,
            [
                
                'headers' =>
                [
                    'Authorization' => 'Bearer ' . $this->account->access_token,
                    'Content-Type' => 'application/vnd.allegro.public.v1+json',
                    'Accept'=>'application/vnd.allegro.public.v1+json'
                ],
                'body' => $json
            ]
        );`
tablica json wygląda w następujący sposób:
`{"publication":{"action":"END"},"offerCriteria":[{"offers":[{"id":"7938202514"}],"type":"CONTAINS_OFFERS"}]}`

Aukcja poprawnie zmienia status jednak w odpowiedzi nie otrzymuje liczby zmodyfikowanych aukcji

`{"id":"bc347a7e-c491-4a10-affd-cc6571a8b918","taskCount":{"total":0,"success":0,"failed":0}}`

**Comment by Lukasz-Zurek** [comment]
Wskazany zasób, podobnie jak wszystkie zasoby do edycji wielu ofert jednocześnie - działa asynchronicznie, dlatego w odpowiedzi otrzymasz same zera. Dopiero po jakimś czasie pojawią się właściwe liczby ofert.

Jeśli chcesz sprawdzić szczególowy status wykonanej na ofercie akcji, korzystaj z GET na zasobie [/sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getTasksUsingGET)
