### ISSUE TITLE
GEIS data wysyłki

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#4229]
Mamy problem z datą wysyłki przesyłek GEIS, przekazujemy numery listów poprawnie na endpoint /order/checkout-forms/, w raporcie przesyłek wygenerowanym z allegro pola list przewozowy, przewoźnik są poprawnie uzupełnione, list przewozowy dodany w terminie, przewoźnik ustawiony poprawnie natomiast data wysyłki jest zawsze na brak. Sprawdzaliśmy w panelu GEIS i tam przesyłka jest prawidłowo dodana z poprawnym adresem email, wg trackingu paczka została nadana poprawnie tego samego dnia, na allegro w zamówieniu również nr listu jest poprawnie dodany. Co może być przyczyną że data wysyłki jest zawsze na Brak?

**Comment by PrzemyslawLukanowski** [comment]
Przez nasze publiczne API nie udostępniamy takiej informacji jak data wysyłki, dlatego przykro mi, ale nie mogę Ci pomóc. Zgłoś proszę swój problem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5), dzięki temu zgłoszenie zostanie skierowane do odpowiedniego zespołu, który zajmie się jego weryfikacją.
