### ISSUE TITLE
Rest API modyfikacja ilości

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#423]
Czy istnieje metoda w Rest API przy użyciu, której można zmienić dostępną ilość (stock/available) na trwającej ofercie?

**Comment by PawelTaberski** [comment]
Ilość przedmiotów w trwającej ofercie możesz zmienić przy pomocy metody PUT na zasobie /sale/offers/{offerId} , dokładny opis tej metody znajdziesz [tutaj](https://developer.allegro.pl/sale/#step-6-complete).

**Comment by sis6326r** [comment]
Dzięki za szybką odpowiedź. Czy cenę również mogę modyfikować tym zasobem?

**Comment by masterix** [comment]
Samą cenę możesz zmienić za pomocą tego: https://developer.allegro.pl/documentation/#/offer-management/put_offers__offerId__change_price_commands__commandId_

**Comment by sis6326r** [comment]
To znam i stosuje ale ciekaw jestem czy można to zrobić przez /sale/offers

**Comment by PawelTaberski** [comment]
@sis6326r Również możesz zmienić cenę ilość sztuk w ofercie i wszystkie inne pola.
