### ISSUE TITLE
Produktyzacja: produkty widmo niemożliwe do połączenia

### ISSUE THREAD

**Issue by DarkStoorM** [allegro/allegro-api#4230]
Witam, 

od jakiegoś czasu podczas wystawiania znajduję coraz więcej produktów, które są całkowicie puste. Wiem, że mogę zgłosić błąd w produkcie, ale chciałbym poznać przyczynę tego błędu.

Mamy dwa takie przykładowe produkty (w chwili pisania tego postu produkty były puste):
https://allegro.pl/offer/product/report/0002d0c5-b8ff-4392-baad-302fa441fa98
https://allegro.pl/offer/product/report/6dbc26a5-65b6-415d-946d-835ce8ee4c08

Pytanie: czy jest to błąd w produktyzacji podczas tworzenia produktu, czy są to produkty z jej wczesnego stadium? Z tego co widzę, nazwa produktu tworzona jest teraz automatycznie według parametrów i kategorii, więc może pochodzą one z czasów, kiedy Produkt tworzony był z nazwy oferty podanej przez sprzedającego + kategorii

![image](https://user-images.githubusercontent.com/7021295/109951966-9b003c80-7cde-11eb-862d-6f09a5fe3ef7.png)
Tytuł przekracza 50 znaków (54), mogło to byc również nawiązaniem do błędu przy łączeniu, gdzie dostawaliśmy ciągle komunikat o tytule przekraczającym 50 znaków.

Wiem, że nie dotyczy to ściśle API, ale warto by było rzucić okiem dlaczego powstaje w bazie produkt, który posiada jedynie nazwę i EAN. Zauważyłem, że dotyczy to głównie produktów, **które mają nazwę powyżej 50 znaków**. Nie mają one kompletnie żadnych danych. Kategoria jest "pusta" - nie wyświetla się ścieżka podczas zgłaszania błędu w produkcie (wskazuje na główną z jakiegoś powodu, info poniżej).

Poniżej inny produkt + jego kategoria.

I podobnie, Tytuł przekracza 50 znaków, jest to (pradopodobnie) kategoria "Mini Piekarnik", a nazwa przedmiotu pochodzi z pliku producenta, więc możliwe, że któryś sklep stworzył taki produkt przez API

```
^ array:2 [▼
  "product" => {#1257 ▼
    +"id": "0002d0c5-b8ff-4392-baad-302fa441fa98"
    +"name": "Mini piekarnik G3Ferrari Piekarnik elektr.28L G3Ferrari G10132"
    +"category": {#1267 ▶}
    +"parameters": array:1 [▶]
    +"images": []
    +"eans": null
    +"offerRequirements": {#1274 ▶}
    +"compatibilityList": null
    +"tecdocSpecification": null
    +"description": null
  }
  "category" => {#1273 ▼
    +"id": "42540aec-367a-4e5e-b411-17c09b08e41f"
    +"name": "Elektronika"
    +"parent": null
    +"leaf": false
    +"options": {#1272 ▶}
  }
]
```

Czy w tej chwili najlepszym rozwiązaniem jest zgłaszanie błędów w produkcie? Takie produkty stwarzają spory problem, gdyż wymagane są połączenia ofert z produktami, a takie właśnie produkty uniemożliwiają ich połączenie. Przypominam, że:

* wyszukanie tego produktu jest **niemożliwe**
* automatyczne połączenie oferty z tym produktem (lub stworzenie produktu) jest niemożliwe, bo Allegro pokazuje jedynie, że "EAN w ofercie jest przypisany do innego produktu w Katalogu."

uuid tego produktu do zgłoszenia można znaleźć jedynie wtedy, kiedy jest jeszcze widoczna oferta u sprzedającego, który stworzył taki produkt, więc. Przykładowo taki stworzony produkt o ID 0002d0c5-b8ff-4392-baad-302fa441fa98 pochodzi z oferty producenta 8381813132.

Jeżeli trzeba, przeniosę temat na Allegro Gadane i zamkniemy issue, chociaż uważam, że GH to lepsze miejsce.

**Comment by Lukasz-Zurek** [comment]
Poruszony przez Ciebie temat nie dotyczy stricte funkcjonowania API, a katalogu produktów, w związku z czym proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=51c159e7-e9c6-4991-a769-7a7fd5c458e1&subjectId=d6fe6f81-8e04-4612-b6f9-d845a97e5a8f).
