### ISSUE TITLE
Czy oferty "do wyczerpania zapasów" mogą się same zakończyć?

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#4231]
Cześć, dziś w nocy zakończyło nam się kilkaset ofert pomimo, że miały ustawioną opcję "do wyczerpania zapasów". Oferty zostały utworzone 5 lipca 2019 r, zaś zapasy nie wyczerpały się. Z informacji otrzymanej na maila wynika, że pomimo ustawienia opcji "do wyczerpania zapasów" zakończone oferty miały ustawione czasy trwania od 5 lip 2019 do 4 mar 2021.

W związku z tym moje pytanie: czy oferty z ustawioną opcją "do wyczerpania zapasów" mimo wszystko mają ustawiony czas trwania, czy wystąpił jakiś błąd?

**Comment by Lukasz-Zurek** [comment]
Oferty "do wyczerpania zapasów" mogą zakończyć się w sytuacji, gdy dostępna ilość zostanie wyprzedana, na Pańskie konto zostanie nałożona blokada sprzedaży, lub w przypadku nieuzupełnienia obowiązkowych parametrów, które w międzyczasie zostały zaktualizowane.

Najlepiej skontaktuj się proszę z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), w wiadomości podając przykładowe oferty.
