### ISSUE TITLE
błąd 404 w zapytaniu sale/offer-classifieds-packages

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#4232]
Dzień dobry, 
nie mogę poradzić sobie z błędem 404 w zapytaniu /sale/offer-classifieds-packages/{offer-id}
Próbuje pobrać dane z zamówienia, ale ciągle wyskakuje ten sam błąd.
Wiem że ID zamówienia jest poprawne, bo /sale/offers/{offerID} działa poprawnie. 

Wywołania obu zapytań wyglądają tak samo, różnią się tylko adresem. Jesteście w stanie mi pomóc?

**Comment by PrzemyslawLukanowski** [comment]
Czy jesteś pewny, że korzystasz z odpowiednich endpointów? Zamówienie pobierzesz za pomocą [GET /order/checkout-forms/{checkout-form-ID}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET). Przez [GET /sale/offer-classifieds-packages/{offer-id}](https://developer.allegro.pl/documentation/#operation/getClassifiedPackagesUsingGET) pobierzesz pakiety przypisane do ogłoszenia. Jeśli w odpowiedzi otrzymujesz 404, oznacza to, że do danej oferty nie przypisałeś żadnych pakietów.

**Comment by lukaszkrakowiak** [comment]
no dobrze, w takim razie dlaczego jak przesyłam https://api.allegro.pl/pricing/fee-preview odpowiedź otrzymaną od /sale/offers/{offerID} to występuje problem z zapytaniem. Dokładniej 422 - UNPROCESSABLE_ENTITY

**Comment by lukaszkrakowiak** [comment]
Udało się "odeprzeć" ten błąd 422. Tylko że teraz jest 503 - ale to chyba u was jakaś przerwa techniczna?

**Comment by lukaszkrakowiak** [comment]
Tym razem zamiast 422, jest błąd 503. Błąd 422 był spowodowany jednak błędnym przekazywaniem danych. No ale 503 SERVICE_UNAVAILABLE to już nie mam pojęcia

**Comment by lukaszkrakowiak** [comment]
No nic. Zły adres podawałem, bo fee-preview odnosi się ogólnie, np do kategorii, a ja potrzebowałem offer-fee-preview :) teraz wszystko gra. Dzięki za pomoc
