### ISSUE TITLE
Problem z połączeniem do API, lista zamówień i zmiana statusu zamówienia

### ISSUE THREAD

**Issue by webtsx** [allegro/allegro-api#4233]
Witam,

chcę stworzyć skrypt (uruchamiany z crona), który będzie łączyć się z API Allego i pobierać listę zamówień oraz zmieniać status zamówienia.
Mam zarejestrowaną aplikację, typ DEVICE, OAuth grant-type: device_code.
Niestety mam problem z uruchomieniem i działaniem itp.  
Udało mi się skojarzyć aplikację, pobierając device_code, oraz verification_url_complete. 
Zapisałem tą odpowiedź i w międzyczasie za pomocą linku z verification_url_complete skojarzyłem już przez przeglądarkę aplikację z kontem allegro. Potem wysłałem żądanie z device_code, aby pobrać token. 
Mam problem z tym, że zapisany token przestał działać po jednym dniu. 
Kojarzenie aplikacji codziennie przez stronę jest uciążliwe. W jaki sposób zautomatyzować ten proces ? 
Z tego co zauważyłem jak jeszcze działał mi token to nie mogłem zmienić statusu zamówienia. Mogłem tylko pobrać zdarzenia za pomocą /order/events. Wysyłałem nagłówki Authorization: Basic(clientId:clientSectet) lub Authorization: Bearer token.
Co powinienem zrobić, żeby móc pobrać listę zamówień i zmieniać status zamówienia oraz mieć nieprzerwany dostęp z poziomu skryptu uruchamianego co określony czas?

Z góry dzięki za jakąś wskazówkę.

**Comment by kfijalko** [comment]
Token działa(jest ważny) 12 godzin. 
Razem z tokenem dostajesz refresh_token, który jest ważny 3 miesiące.
Przy pomocy refresh_tokena możesz uzyskać nowy token (+ refresh_token), który będzie ważny 12h. Poprzedni refresh_token traci ważność.
...

**Comment by Lukasz-Zurek** [comment]
Zgodnie z tym, co napisał @kfijalko , token jest ważny 12 godzin. Aby ułatwić proces autoryzacji i jednocześnie nie przerywać regularnego korzystania z naszych zasobów, udostępniliśmy możliwość odświeżania tokenów. W takiej sytuacji otrzymujesz parę tokenów - access token (ważny kolejne 12h) oraz refresh token (ważny kolejne 3 miesiące).

Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#refresh-token).

**Comment by webtsx** [comment]
Dzięki, działa odświeżenie. 
Mam problem jeszcze ze zmianą statusu zamówienia. Wysyłam Authorization: Bearer {token}
na https://api.allegro.pl/order/checkout-forms/**$checkoutFormId**/fulfillmentGet
Ale otrzymuję błąd, z którym nie wiem za bardzo co zrobić, bo nic nie wnosi. 
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/order/checkout-forms/6e0387f1-7b99-11eb-a50f-7f8aa0b3ad16/fulfillment","userMessage":null}]}`

**Comment by webtsx** [comment]
Już wiem. Jakby ktoś potrzebował, chodziło o to, żeby wysłać dane w postaci json.

Dzięki za pomoc.
