### ISSUE TITLE
Czy jest możliwość zbioru informacji ofert wybranego sklepu?

### ISSUE THREAD

**Issue by vladeol** [allegro/allegro-api#4234]
Cześć,
czasami jest zapotrzebowanie dla analizy ściągać takie dane:
wszystkie oferty sklepu ze słowem kluczowym:
np: https://allegro.pl/uzytkownik/*sklep*?string=*słowo*
dla każdej oferty: id, tytuł, cena, ean

czy pozwala REST API Allegro wyciągać takie dane?
Z góry dziękuję

**Comment by kfijalko** [comment]
Tak. najpierw przeczytaj ten "NEWS"
#4213

**Comment by kfijalko** [comment]
Sprostowanie, EANu nie dostaniesz w żadnej metodzie dla ofert publicznych.

**Comment by Lukasz-Zurek** [comment]
Co do samego działania zasobu - jest taka możliwość, uzyskasz m.in. id oferty, tytuł, cenę, a także inne dane. Nie zostanie natomiast zwrócony kod EAN. 

Dane uzyskasz korzystając z zasobu: [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) oraz odpowiednich filtrów, np. `phrase` i `seller.login`. 

Jednocześnie zapoznaj się z [naszym poradnikiem](https://developer.allegro.pl/listing/#2-jak-filtrowa%c4%87-wyniki-wyszukiwania) oraz - jak już wspomniał @kfijalko  - [newsem](https://github.com/allegro/allegro-api/issues/4213)
