### ISSUE TITLE
przetłumaczyć wyszukiwanie na język api

### ISSUE THREAD

**Issue by zlotowinfo** [allegro/allegro-api#4236]
zablokowali file_get_contents i muszę użyć api, nie wiem co im odbiło

chciałbym takie coś przetłumaczyć na język api w php
https://allegro.pl/listing?string=wiertark*%20sto%C5%82ow*&price_to=250&price_from=100&bmatch=cl-e2101-d3681-c3682-uni-1-1-0304&allegro-smart-standard=1&stan=u%C5%BCywane&offerTypeBuyNow=1

interesują mnie: cena, koszt wysyłki, nazwa, numer aukcji, login sprzedawcy (do blacklisty), czy ma smart, numer kategorii
dla kupteraz: sortowanie wg. najnowszych
dla licytacji: sortowanie: czas zakończenia

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o zasoby związane z wyszukiwaniem ofert, służy do tego [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Wszelkie informacje na ten temat - opis parametrów, przykłady - znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/). -

**Comment by zlotowinfo** [comment]
nie wiem o co chodzi
nie ma tam żadnych przykładów w php

**Comment by PrzemyslawLukanowski** [comment]
W poradniku znajdziesz opis, jak korzystać z zasobu /offers/listing w API. Na tę chwilę nie udostępniamy w naszych poradnikach przykładów kodu dla konkretnych języków programowania.

**Comment by zlotowinfo** [comment]
ale ta dokumentacja jest bez sensu
w tym get listing są same klamry, nie wiadomo do czego to przypiąć

**Comment by PrzemyslawLukanowski** [comment]
Są to przykładowe, działające wywołania API w formacie cURL. Sposób implementacji w Twojej aplikacji jest już po Twojej stronie - nie świadczymy wsparcia w tym temacie.

**Comment by zlotowinfo** [comment]
czy jest na tym forum kto dałby przykład jednego takiego wywołania w php?
