### ISSUE TITLE
Błąd aktualizacji aukcji - link w opisie

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4237]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,

podczas ustawiania stanu na aukcji 9572563378, api zwraca błąd: "Please remove links to external sales websites outside Allegro from the offer description. You can only provide links to websites that include additional information about the product.". 

Opis oraz inne elementy nie zawierają linków, więc co jest przyczyną tego błędu?

**Comment by PrzemyslawLukanowski** [comment]
Problem powodowała fraza `junior pl`. Ostatni raz ten komunikat dla wspomnianej oferty zwróciliśmy w dniu 02.03.21 - po tym czasie wdrożyliśmy poprawkę i błąd nie powinien już występować. Spróbuj proszę ponownie zmienić stan w ofercie.
