### ISSUE TITLE
Użycie więcej niż 1 klucza API na stronie własnego sklepu internetowego.

### ISSUE THREAD

**Issue by Kacpieee** [allegro/allegro-api#4239]
Dzień dobry.

W planach mam stworzenie marketplace który działałby za granicą. W założeniu chcę się dogadać ze sprzedawcami z Allegro którzy sprzedają części używane żeby rejestrowali się na mojej stronie i integrowali swoje nowe konto na moim sklepie ze sklepem Allegro. 

Moje pytanie brzmi: Czy jest to możliwe że 5 sprzedawców ma 5 oddzielnych ze sobą kont na moim sklepie i każde z tych 5 kont jest zintegrowane w czasie rzeczywistym za pomocą ich kluczy API? 

Korzystając np. z platformy Shoper jeśli chce się zaimportować ogłoszenia z np. 3 kont Allegro należących to 3 różnych osób to trzeba je podpinać, importować i odłączać po kolei- nie ma możliwości połączenia ich 3 wszystkich w jednym momencie.

Dlatego wracając do pytania- Czy tworząc własną stronę internetową jest to możliwe zarówno z technicznego, jak i prawnego punktu widzenia że wiele kont Allegro(należących do innych osób więc nie można ich połączyć na samym Allegro-to ważne) jest zintegrowane i zsynchronizowane w czasie rzeczywistym z moją stroną?

Z góry dziękuję za odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Powinieneś korzystać z jednego klucza aplikacji, do którego podpiętych może być wielu użytowników. Aplikacja, po poprawnej autoryzacji użytkownika, zwróci tokena dostępowego, dzięki któremu może operować w kontekście danego usera. Nie ma możliwości, np. pobrania naraz ofert wszystkich sprzedawców, aplikacja wykonuje żądania tylko w odniesieniu do użytkownika, dla którego posiada token dostępowy. Więcej informacji na temat procesu autoryzacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/).
