### ISSUE TITLE
Sugestie kategorii poprzez API ?

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#424]
Witam,

czy istnieję metoda na uzyskanie sugestii kategorii poprzez API ?

Pozdrawiam

**Comment by darekwaw** [comment]
Dopisuję się do pytania.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Sugestii samych w sobie nie da się pobrać przez REST API. Kategorie i parametry możecie pobrać przy pomocy [tych ](https://developer.allegro.pl/sale/#step-2 )zasobów.

**Comment by kamilhark** [comment]
Czy jest szansa żeby takie Api dodać? Byłoby to wystawienie istniejącej funkcjonalności, która jest dostępna przy ręcznym wystawianiu oferty.

**Comment by PawelTaberski** [comment]
Nie planujemy zwracania parametrów uzupełnionych jakimiś defaultowymi danymi. Wszelkie informacje o parametrach znajdziesz w dedykowanym zasobie GET /sale/categories/{catId}/parameters.
