### ISSUE TITLE
Dobry procent podpiętych pod produkt ale nie mogę wystawić oferty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4240]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Podczas próby wystawienia oferty otrzymuję błąd z informacją _You cannot publish offer without a related product..._ (przykładowy trace-id: def10ad00633798c). Jednak używając zasobu sale/offers obliczyłem, że mam w tej kategorii 85% podpiętych ofert pod produkt. Dlaczego nie mogę wystawić oferty?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Ofertę próbujesz wystawić w kategorii: _123958 (planszowe)_, która należy do kategorii _11763 (Dziecko)_ i tu faktycznie nie masz jeszcze 1% ofert podpiętych do produktów.

**Comment by tomylee0** [comment]
Proszę o powtórne sprawdzenie. W tym momencie wyciągając produkty przez REST API mam w kategorii DZIECKO podpiętych 277 ofert na wszystkich 324 w tej kategorii.

I np. oferta 10462141902. Gdy się wejdzie na nią od strony kupującego przez www to nie widać że jest podpięta pod produkt. Natomiast wyciągając ją przez REST API mam produkt e078b1c1-83ba-4e3b-a9c7-d0a62ed9afad.

Podejrzewam, że problem jest gdzieś w wyliczaniu procentu w tej kategorii. 

Pozdrawiam

**Comment by tomylee0** [comment]
Dodam, że gdybym nie miał 1% wypełnionego to przy 300 ofertach musiałbym mieć maksymalnie 3 podpięte pod produkt. A ręcznie przeklikałem na www od strony kupującego i widać, że mam ich podpiętych więcej po produkt.

**Comment by Lukasz-Zurek** [comment]
Potwierdzam. Problem ten zgłosiłem już do odpowiedniego działu w celu dalszej weryfikacji.

**Comment by tomylee0** [comment]
Zaobserwowałem po swojej stronie, że zostało to poprawione ale jeszcze nie wszędzie. Tutaj na innym koncie jest wciąż ten sam problem: trace-id cf3d024f5080344b.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Dziękuję. Przykład ten również przekazałem do dalszej weryfikacji. Wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
Prawdopodobna przyczyna problemu zgłoszonego wcześniej, to duża ilość modyfikacji ofert w krótkim czasie oraz opóźnienie w aktualizacji statystyk. Przepraszamy za zaistniałe utrudnienia.

Jeśli natomiast chodzi o _trace-id cf3d024f5080344b_ - próbowałeś wystawić ofertę w kategorii: _256942_, która objęta jest wymogiem 1% ofert połączonych z Katalogiem produktów Allegro. Wymóg ten obejmuje tylko część podkategorii z działu "Dziecko". Obecnie w wymaganych podkategoriach nie masz wystawionej żadnej oferty.

Zapoznaj się proszę z plikiem zawierającym listę wszystkich podkategorii m.in. z działu "Dziecko". Jest on dostępny [tutaj](https://allegro.pl/dla-sprzedajacych/18-stycznia-wprowadzilismy-nowe-wymogi-dotyczace-ofert-powiazanych-z-katalogiem-produktow-allegro-O3BZgPon2Hz).

**Comment by tomylee0** [comment]
Problem ze statystykami istniał już przed _dużą ilością modyfikacji ofert w krótkim czasie_. Nie powinien to być więc ten powód.

Wymóg 1% dotyczy całego działu "Dziecko" a nie osobno 1% dla poszczególnych podkategorii. W przeciwnym razie:
1. Jak wytłumaczyć, że na koncie z trace-id: def10ad00633798c (to na samej górze tego zgłoszenia) pomimo analogicznej sytuacji udało mi się załadować oferty i np. w kategorii 312685 (która znajduje się na liście wymaganych podkategorii z 1%) są tylko 2 oferty i żadna nie jest podpięta pod produkt?
2. Jak wytłumaczyć sens podawania w zakładce "Moje oferty" informacji o procencie podłączonych ofert do produktów dla całego działu? Informacja ta stałaby się bezużyteczna gdyby i tak wymóg dotyczył osobno każdej podkategorii.

Podsumowując: jako, że na pierwszym ze wskazanych przeze mnie kont zgłaszany problem zniknął wieczorem 5 marca a na drugim wciąż istnieje proszę o powtórną weryfikację tematu związanego z niepoprawnym wyliczaniem statystyk dla konta z trace-id cf3d024f5080344b.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Wymóg 1% ofert połączonych z Katalogiem produktów Allegro dotyczy wybranych w kategoriach działów. Zapoznaj się proszę z tabelą dostępną na [tej stronie](https://allegro.pl/dla-sprzedajacych/18-stycznia-wprowadzilismy-nowe-wymogi-dotyczace-ofert-powiazanych-z-katalogiem-produktow-allegro-O3BZgPon2Hz). 

W związku z powyższym statystyki dla kategorii "Dziecko" uwzględniają dane ofert z kategorii objętych wymogami.

1. Komunikat błędy był tutaj prawidłowy. Błędne natomiast były statystyki, o czym wspomniałem w poprzedniej odpowiedzi. Wynikało to m.in. z tymczasowych opóźnień.

2. W kategoriach, w których wystawiasz oferty, tj. _19535, 261496 i 19416_, statystyki są wyłączone. Dlatego zarówno ilość wystawionych tam ofert (w kategorii "Dziecko"), jak i procent oferty połączonych z produktem wynosi "0".

W przypadku wywołania _trace id: cf3d024f5080344b_, próbujesz wystawić ofertę w kategorii: _256942_, która znajduje się na liście kategorii objętych wymogiem 1% ofert połączonych z Katalogiem produktów Allegro. W tej kategorii nie masz wystawionych ofert.
