### ISSUE TITLE
[Zmiana ilości sztuk] Błąd

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#4241]
:bulb: **Sugestia**

Cześc, 
API zwraca nam taki błąd, prośba o rozszerzenie komunikatu dlaczego nie udało się zmienić. Dzięki

{"RaportZlecenia":{"Nr":"bb96b55f-d0fa-41df-9514-b8305d3b521f","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2021-03-04T17:17:13.358Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"10248538942"},"ScheduledAt":"2021-03-04T17:17:13.374Z","Status":"FAIL","Errors":[{"Code":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Details":null,"Message":"Exception when update offer quantity.","Path":null,"UserMessage":"**Błąd podczas zmiany liczby sztuk**."}]}]},"Validation":null,"Exception":null,"TraceId":"**65b34ae290846bb4**","Error":false,"StatusCode":200,"Message":null}}}

**Comment by PrzemyslawLukanowski** [comment]
Zarówno problem, jak i sugestię co do zmiany treści w message, przekazałem do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@SebastianOzdoba Czy w ostatnim czasie wystąpiły podobne błędy? Jeśli tak, czy mogę prosić o przykładowe commandID?

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski sprawdzimy, dam znać

**Comment by SebastianOzdoba** [comment]
@PrzemyslawLukanowski w ostatnich dniach nie mieliśmy takich błędów (od 19.03.2021, godz: 0:00 do teraz 22.03.2021 godz 13:30). Zamykam, jeśli się pojawi wrócę ponownie ;)
