### ISSUE TITLE
Wykorzystanie danych

### ISSUE THREAD

**Issue by adam-54** [allegro/allegro-api#4243]
W nowym regulaminie REST API Allegro została naniesiona zmiana w punkcie dotyczącym wykorzystania: "wykorzystywanie do pobierania lub wykorzystywania w jakimkolwiek zakresie dostępnych w ramach Allegro materiałów (w tym danych oraz innych informacji) bez zgody Allegro.pl". W jakiej formule będzie można uzyskać taką zgodę? Czy przewidziane są ograniczenia w uzyskaniu takiej zgody w sytuacji, gdy celem byłoby wykorzystanie danych na potrzeby pracy naukowej lub dydaktyki?

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się w tej sprawie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a2f3ea49-2579-47d5-87f4-6d96a42e3e86&subjectId=ae7b20da-ee49-4df4-90ed-39e32533ed8c).
