### ISSUE TITLE
Jakie zapytanie słyży do wylistowania numerów ofert wg konkretnej nazwy ?

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#4244]
Jakie zapytanie słyży do wylistowania numerów ofert wg konkretnej nazwy (czyli rezultat danego wyszukania)?

**Comment by Lukasz-Zurek** [comment]
Jeśli chcesz wyfiltrować wyniki po konkretnej frazie, skorzystaj z filtrowania po parametrze `phrase`, w zasobie: [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).

Więcej informacji na temat dokładnego filtrowania wyników znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

Zapoznaj się również z naszym ostatnim [newsem](https://github.com/allegro/allegro-api/issues/4213).
