### ISSUE TITLE
Czy blokujecie ruch z mojego IP?

### ISSUE THREAD

**Issue by ospiotr** [allegro/allegro-api#4245]
Występuje problem: 
 - [x] z logowaniem lub autoryzacją

Cześć,

Mam problemy z połączeniem z REST API. Moja aplikacja albo nie może uzyskać autoryzacji, albo po jej uzyskaniu traci połączenie po jakimś czasie.

Prośba o sprawdzenie w logach czy IP mojego serwera **95.216.74.162** jest blokowany/filtrowany przez Waszego firewalla.
Będę wdzięczny za odpowiedź

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem nasze logi, jednak nie widzę w nich nic, co mogłoby wskazywać, że blokujemy Twoje IP. Prześlij proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c) przykładowy request i response dla sytuacji, gdy nie możesz uzyskać autoryzacji. Przeanalizujmy ten przypadek. W zgłoszeniu dopisz, że dane dotyczą wątku  GitHub #4245.

**Comment by ospiotr** [comment]
@PrzemyslawLukanowski 

Sama próba połączenia się z endpointem https://allegro.pl/auth/oauth/token poprzez curl (niezależnie od parametrów requesta)
w losowych sytuacjach kończy się błędem z informacją: `could not resolve host: allegro.pl`

Ten endpoint nie jest wyjątkiem - mój problem dotyczy wszystkich endpointów dostępnych w REST API.

**Comment by PrzemyslawLukanowski** [comment]
Ten komunikat może mieć związek z problemami sieciowymi po Twojej stronie, np. z DNS. Sprawdziliśmy nasze logi, jednak nie udało nam się znaleźć nic, co wskazywałoby na problemy po naszej stronie.

**Comment by Cresh22** [comment]
Po uzyskaniu tokenu i wywołaniu przykładowego zapytania GET (https://allegro.pl/sale/offers) otrzymuje podobny problem:

`string(459) "<html><head><title>allegro.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMAlWeHnD32tOsABfzmxw==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'fe','s':29560,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>`
