### ISSUE TITLE
Jak pobrać dane o ofercie?

### ISSUE THREAD

**Issue by depesz** [allegro/allegro-api#4247]
Potrzebuję pobrać dane o danej ofercie. Np. id 8785571039

Wygenerowałem sobie token, ale kiedy próbuję go użyć:

````
=$ curl -s -X GET "https://api.allegro.pl/sale/offers/${offerid}" -H "Authorization: Bearer ${token}"  -H 'Accept: application/vnd.allegro.public.v1+json' | jq -C .                                                                                                                                                          
{
  "errors": [
    {
      "code": "FORBIDDEN",
      "message": "Forbidden",
      "details": null,
      "path": "/sale/offers/8785571039",
      "userMessage": null
    }
  ]
}
```

W szczególności potrzebuję pobrać pełną treść oferty (należy do mnie). Jak to można zrobić?

**Comment by PrzemyslawLukanowski** [comment]
Używasz tokena wygenerowanego w ramach autoryzacji typu client_credentails. Taki token nie posiada kontekstu użytkownika, dlatego w odpowiedzi otrzymujesz kod 403. Aby prawidłowo pobrać ofertę, skorzystaj z autoryzacji typu [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow). W naszej [dokumentacji](https://developer.allegro.pl/documentation/#) znajdziesz odpowiednie oznaczenia, jakiego rodzaju autoryzacji musisz użyć, aby otrzymać prawidłową odpowiedź z danego endpointu:
- bearer-token-for-user - code lub device flow;
- bearer-token-for-application - client credentials;

**Comment by mr-yromanov** [comment]
> Używasz tokena wygenerowanego w ramach autoryzacji typu client_credentails.
`    "scope": "allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read",`

Kiedy dostajesz token, dostajesz listę tego, do czego masz dostęp, a potem okazuje się, że nie masz dostępu?

**Comment by depesz** [comment]
@PrzemyslawLukanowski Dzięki, to było to. Teraz działa :)
