### ISSUE TITLE
EAN wymagany do aktywacji draftu w API

### ISSUE THREAD

**Issue by sc4rface97** [allegro/allegro-api#4248]
Witam,

z dniem dzisiejszym program integrujący wewnętrzny magazyn z Allegro przestał aktywować oferty. Zaniepokojony sytuacją sprawdziłem logi aktywacji na endpoincie /sale/offer-publication-commands/{commandId}/tasks. W logach widnieje informacja o tym, że aktywacja nie powiodła się, ponieważ kod EAN jest wymagany.

Coś się zmieniło? W oficjalnej dokumentacji ten parametr wciąż nie jest oznaczony jako wymagany, a mimo to oferty wiszą w szkicach.

**Comment by PrzemyslawLukanowski** [comment]
26.06.20 udostępniliśmy parametr **[globalny numer jednostki handlowej tzw. GTIN](https://developer.allegro.pl/news/#gtin)**, który jest nadrzędny wobec pola ean. Samo pole ean, [zgodnie z naszą zapowiedzią](https://developer.allegro.pl/news/#ean-eans-remove), usuniemy 29.03.21 Aby zatem sprawdzić, czy w danej kategorii EAN jest obowiązkowy, użyj sale/categories/{categoryID}/parameters - informację znajdziesz w parametrze 225693, w polu **required**.

Możesz takie spojrzeć na [news na stronie dla sprzedających ](https://allegro.pl/pomoc/aktualnosci/od-1-marca-parametr-ean-bedzie-obowiazkowy-dla-produktow-ze-stanem-nowy-w-wybranych-kategoriach-lLRLDxozDcv) - w wybranych kategoriach od 1 marca parametr EAN stał się obowiązkowy dla produktów ze stanem - "nowy".

**Comment by sc4rface97** [comment]
Wszystko jasne, z tymże wciąż jest problem z EAN.

Według dokumentacji ma to być pole string bez żadnej dodatkowej struktury, po prostu:

ean = string

W taki też sposób zmieniłem obiekt Draft dodając do niego owy kod. W tym momencie wspomniany wcześniej endpoint statusowy (/sale/offer-publications-commans/...) nie zwraca błędu, ale również nie aktywuje oferty. Mało tego, wchodząc manualnie w edycję dodanego szkicu EAN nie wyświetla się.

Co w takiej sytuacji?

**Comment by PrzemyslawLukanowski** [comment]
[Od 1 marca](https://developer.allegro.pl/news/#ean-eans-null) przestaliśmy zwracać wartość w polu ean. Aby rozwiązać ten problem, musisz zacząć przekazywać wartość w parametrze GTIN-owym, czyli w zależności od kategorii jest to:

- EAN (ID 225693),
- ISBN (ID 245669),
- ISSN (ID 245673).

**Comment by sc4rface97** [comment]
Wszystko się zgadza, dzięki za pomoc.
