### ISSUE TITLE
getting error - HTTP/2 400 "code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null

### ISSUE THREAD

**Issue by rajgwalior** [allegro/allegro-api#4249]
Hi API Support Team,

i retrieve access token by Authorization Code. and same error i am getting, check below "HTTP/2 400 expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block pragma: no-cache x-frame-options: DENY trace-id: 37c5cad3879c453a date: Tue, 02 Mar 2021 19:24:27 GMT x-content-type-options: nosniff content-type: application/json {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}"

one more thing.  I am using my linux server for listing our items. I used PHP code for listing. so how can I get token "as a device or code autorisation type ". 

access token  response of code autorisation type :-

HTTP/2 200 date: Tue, 02 Mar 2021 19:20:17 GMT content-type: application/json;charset=UTF-8 cache-control: no-store pragma: no-cache vary: Accept-Encoding age: 0 content-security-policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp; x-content-type-options: nosniff grace: none x-xss-protection: 1; report=https://allegro.pl.allegrosandbox.pl/seclog/xss accept-ranges: bytes x-frame-options: SAMEORIGIN strict-transport-security: max-age=15552000 set-cookie: _cmuid=1r44c7w9-z663-54r7-jud2-b35bfn49wmrb; Expires=Thu, 02 Mar 2023 19:20:17 GMT; Path=/; Domain=.allegro.pl.allegrosandbox.pl; Secure set-cookie: datadome=FCoq9wLqoB_BU4XztTwt7qS_ca1Jfr484I4NKLeLQe7kR3bVw~24-c-ddt4cxqN1t5FvphAA3rh~tK_Yk3z.V11Qt~it83o2FxMCZvjyNN; Max-Age=31536000; Domain=.allegrosandbox.pl; Path=/; Secure; SameSite=Lax {"access_token":{token},"token_type":"bearer","refresh_token":"{token}","expires_in":43199,"scope":"allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:bids allegro:api:sale:offers:read allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read","allegro_api":true,"jti":"ce7e019a-7d35-4086-9913-2aad593b0d71"}

**Comment by PrzemyslawLukanowski** [comment]
Error 400 means that there is something wrong with your JSON structure. Can you attach it, so we can verify what caused the error (please remember to remove any sensitive data)?

**Comment by rajgwalior** [comment]
hi, 
below is json data.
{"category": { "id": "257931" }, "customParameters": [ { "name": "Author", "values": [H.D. Amos|A.G.P. Lang] } ], "ean": "9780715627310", "id": "ria9780715627310_rkm", "images": [ { "url": "http://imagesmain.riachristiecollections.com/9780715627310.jpg" } ], "name": "These Were the Greeks by H.D. Amos|A.G.P. Lang", "sellingMode": { "format": "BUY_NOW", "price": { "amount": "7743", "currency": "PLN" }, "minimalPrice": { "amount": "7743", "currency": "PLN" }, "startingPrice": { "amount": "7743", "currency": "PLN" }, "netPrice": { "amount": "7743", "currency": "PLN" } }, "stock": { "available": 14, "unit": "UNIT" }, }

and below is header data-

Array ( [0] => Authorization: Bearer token [1] => Accept: application/vnd.allegro.public.v1+json [2] => Content-Type: application/vnd.allegro.public.v1+json )

**Comment by rajgwalior** [comment]
and i am getting below response-

HTTP/2 400 expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block pragma: no-cache x-frame-options: DENY trace-id: f394f177aa640169 date: Fri, 05 Mar 2021 16:28:09 GMT x-content-type-options: nosniff content-type: application/json {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by PrzemyslawLukanowski** [comment]
There are few errors in your structure:
- value in "customParameters.values" should be a string inside an array;
- id is generated automatically on our side. If you want to add your own signature, use "external.id" value;
- ean should be set in a GTIN parameter, you can find more information about this field [here](https://developer.allegro.pl/en/news/#gtin);  
- if you use POST /sale/offers you should upload images to our server first - you can find more information [here](https://developer.allegro.pl/en/sale/#3-upload-images); 
- you don't need to provide minimalPrice and startingPrice if format of your offer is "BUY_NOW". You also shouldn't provide netPrice value;
- there is an unnecessary comma at the end of your structure (UNIT" }, })

Please look into our [guide ](https://developer.allegro.pl/en/sale/)to read about creating an offer in detail.

**Comment by rajgwalior** [comment]
hi,

i changed json as per your suggestions but now API showing INVALID_JSON. please provide me correct json. so i can make it correct. and i will create a offer.
HTTP/2 400 expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block pragma: no-cache x-frame-options: DENY trace-id: ff0566eb0f89bc11 date: Sat, 13 Mar 2021 10:11:16 GMT x-content-type-options: nosniff content-type: application/json {"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Invalid request."}]}

request json:-
{ "category":{ "id":"257931" }, "parameters":[ { "name":"EAN", "valuesLabels":"9780715627310", "values":"9780715627310", "unit":null, "options":{ "identifiesProduct":true, "isGTIN":true } } ], "customParameters":[ { "name":"Author", "values":"H.D. Amos, A.G.P. Lang" } ], "ean":"9780715627310", "external":{ "id":"ria9780715627310_rkm" }, "id":"ria9780715627310_rkm", "name":"These Were the Greeks by H.D. Amos, A.G.P. Lang", "sellingMode":{ "format":"BUY_NOW", "price":{ "amount":"7776", "currency":"PLN" } }, "stock":{ "available":14, "unit":"UNIT" } }

**Comment by PrzemyslawLukanowski** [comment]
Hi, there are still some issues n your structure:
- you should provide IDs of parameters, not names;
- values in parameters.values and customParameters.values should be inside an array;
- id is generated automatically on our side, you cannot provide your own value in this field;
- you should send EAN only in the parameters section, in the "ean" field it is necessary (you can find more info [here](https://developer.allegro.pl/en/news/#ean-eans-null));

Below you can find a sample of proper JSON:

```
{
	"category": {
		"id": "257931"
	},
	"parameters": [{
		"id": "225693",
		"values": ["9780715627310"],
		"unit": null
	}],
	"customParameters": [{
		"name": "Author",
		"values": ["H.D. Amos, A.G.P. Lang"]
	}],
	"external": {
		"id": "ria9780715627310_rkm"
	},
	"name": "These Were the Greeks by H.D. Amos, A.G.P. Lang",
	"sellingMode": {
		"format": "BUY_NOW",
		"price": {
			"amount": "7776",
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 14,
		"unit": "UNIT"
	}
}
```

**Comment by rajgwalior** [comment]
Hi thanks for your help. 

i used your json format but now i am getting 403 "FORBIDDEN" issue. please help me.
request is 👎

{ "category": { "id": "257931" }, "parameters": [{ "id": "225693", "values": ["9780715627310"], "unit": null }], "customParameters": [{ "name": "Author", "values": ["H.D. Amos, A.G.P. Lang"] }], "external": { "id": "ria9780715627310_rkm" }, "name": "These Were the Greeks by H.D. Amos|A.G.P. Lang", "sellingMode": { "format": "BUY_NOW", "price": { "amount": "7776", "currency": "PLN" } }, "stock": { "available": 14, "unit": "UNIT" } }

Array ( [0] => Authorization: Bearer (token here) [1] => Accept: application/vnd.allegro.public.v1+json [2] => Content-Type: application/vnd.allegro.public.v1+json ) 
------------------------------------------------------------------------------------------------
HTTP/2 403 expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block pragma: no-cache x-frame-options: DENY trace-id: 204fe09ac75e266e date: Mon, 15 Mar 2021 19:36:54 GMT x-content-type-options: nosniff content-type: application/json {"errors":[{"code":"FORBIDDEN","message":"Forbidden","details":null,"path":"/sale/offers","userMessage":null}]}

**Comment by PrzemyslawLukanowski** [comment]
To get access to this endpoint, you should use a token from [code](https://developer.allegro.pl/en/auth/#app) or [device](https://developer.allegro.pl/en/auth/#DeviceFlow) flow authorization. Right now you are using [client credentials](https://developer.allegro.pl/en/auth/#clientCredentialsFlow) authorization, which allows you to get access only to public resources, without user context, e.g. GET /sale/categories.
In our [documentation ](https://developer.allegro.pl/en/documentation/)you can find information, which type of authorization you should use for selected resource:

- bearer-token-for-user - code or device flow,
- bearer-token-for-application - client credentials flow -

**Comment by rajgwalior** [comment]
Hi, thanks for letting me know.

i want use these API process in my Linux server and it will be run automatically. and i have only SSH access fro my server. so please tell me which authorization  will be good.  and if you have any php code sample for it please provide me..

**Comment by PrzemyslawLukanowski** [comment]
Please look into our [tutorial ](https://developer.allegro.pl/en/auth/) and decide which authorization will be the best for your needs. Remember that both of them - code or device - require user authorization. After the valid authorization, you will receive pair of tokens - access and refresh. An access token is valid only for 12 hours, but you can use a refresh token (which is valid for 3 months) to extend its validity and automize the process.
Due to large number of programming languages, we don't support all of them. You can check our historical threads, in which there are some PHP code samples:

#226
#2306
#708

**Comment by rajgwalior** [comment]
Hi support,
now i am trying to authorization by device. and i am getting below error. please tell me what is wrong.?
"{"error":"invalid_request","error_description":"ClientId does not match authenticated client."}"

check below code:-

$headers=array(
			'Authorization: Basic '.base64_encode("$qd[client_id]:$qd[client_secret]"),
			'Content-Type: application/x-www-form-urlencoded'
		);
$params= array('client_id' => $qd[client_id]);
$connection = curl_init();
curl_setopt($connection, CURLOPT_URL, 'https://allegro.pl.allegrosandbox.pl/auth/oauth/device');
curl_setopt($connection, CURLOPT_HTTPHEADER, $headers );
curl_setopt($connection, CURLOPT_POST, 1);
curl_setopt($connection, CURLOPT_POSTFIELDS, $params);
curl_setopt($connection, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($connection, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($connection, CURLOPT_SSL_VERIFYHOST, 2);
curl_setopt($connection, CURLOPT_SSLVERSION, 6);

$response = curl_exec($connection);
var_dump($response);
curl_close($connection);

**Comment by PrzemyslawLukanowski** [comment]
Make sure that the client_ID parameter is provided properly and its value is the same as for client_ID from the Authorization header.

**Comment by rajgwalior** [comment]
hi,

as per php code i am using same PHP Variable for client_id. see below.
Array ( [client_id] => 658d77bc65c34124a97d83e94001d092 )

**Comment by PrzemyslawLukanowski** [comment]
I noticed in our logs that your client_ID query parameter is not properly attached to your request (so it's interpreted as null), but as I mentioned before - due to a large number of programming languages, we don't support all of them, so I can't indicate a specific error in your code.
Also, make sure that you register your application as a device type:
![Screenshot_6](https://user-images.githubusercontent.com/51473661/111972864-30346b00-8afe-11eb-93ed-6d972342b5f0.png)
