### ISSUE TITLE
Zakres dostępnych dat dla szczegółów zamówienia

### ISSUE THREAD

**Issue by p0wertiger** [allegro/allegro-api#4250]
Otrzymałem zadanie posprzątania problemów po dziurawym systemie obsługi zleceń. W ramach tego zadania pobieram listy wpłat (/payments/payment-operations) i szczegóły zamówień do nich (/order/checkout-forms) na podstawie payoutId. Listy wpłat działają bez zarzutu dla dowolnych zakresów dat, ale próba pobrania szczegółów zamówień starszych niż 12 miesięcy zwraca pusty wynik. Jak pobrać te dane "historyczne" przez REST API ?

**Comment by Lukasz-Zurek** [comment]
Zamówienia dostępne są przez minimum 180 dni. Nie pobierzesz jednak przez nasze API zamówień starszych niż z ostatnich 12 miesięcy.

**Comment by p0wertiger** [comment]
Nie ma przypadkiem jakiegoś API na archiwum.allegro.pl? ;) Jakie mam w tym wypadku opcje? Na razie mam tylko zestawienia sprzedaży z panelu klienta ale to tylko wycinek danych.

**Comment by Lukasz-Zurek** [comment]
Nie udostępniamy tego typu zasobu w naszym API.

**Comment by p0wertiger** [comment]
Czy mam przez to rozumieć, że muszę się skontaktować z opiekunem Allegro żeby pociągnąć ten temat dalej?

**Comment by Lukasz-Zurek** [comment]
Tak, skontaktuj się proszę z opiekunem.
