### ISSUE TITLE
Kolejność wykonywania tasków

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4251]
Jak zachowa się api gdy spróbuję zmienić cene kiedy  status poprzedniego taska zmiany ceny wciąż ma status "NEW"? Czy taski zakoleją się i będą czekać na siebie czy jednak nie ma określonej kolejności i musimy zaimplementować kolejkowanie/czekanie po naszej stronie? Spróbowałem tak zrobić i jednak chyba API nie kolejkuje tasków.

**Comment by AureliuszBrussy** [comment]
Taski nie są kolejkowane - aby kolejna komenda powiodła się, sprawdź najpierw, czy poprzednia się zakończyła.

**Comment by bugproof** [comment]
Właśnie to zweryfikowałem i faktycznie jednak queueing trzeba zaimplementować po stronie klienta. Taski nie zawsze zakończą się w tej samej kolejności. Dzięki za potwierdzenie.
