### ISSUE TITLE
calling sale/product-offers

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#4252]
i filled all required parameters of the category for product creation, but the api returned error;

 "message": "Unable to create product without all required parameters (5 / 6)",
 "path": "product./products/by-allegro-merchant",
 "userMessage": "Nie można stworzyć produktu bez podania wszystkich parametrów wymaganych (5 / 6)"

my product model;
{
  "product": {
    "name": "Tshirt",
    "category": {
      "id": "87913"
    },
    "parameters": [
      {
        "id": "451",
        "valuesIds": [
          "451_2"
        ]
      },
      {
        "id": "54",
        "valuesIds": [
          "54_317321"
        ]
      },
      {
        "id": "10563",
        "values": [
          "brak"
        ],
        "valuesIds": [
          "10563_40"
        ]
      },
      {
        "id": "201017",
        "valuesIds": [
          "201017_2317"
        ]
      },
      {
        "id": "3766",
        "valuesIds": [
          "3766_1"
        ]
      }
    ],
    "images": [
      "https://n11scdn.akamaized.net/a1/org/giyim-ayakkabi/tisort-atlet/tshirthane-fortnite-eat-sleep-play-tisort-erkek-tshirt__1268661352759580.jpg"
    ]
  },
  "sellingMode": {
    "price": {
      "amount": "148.43",
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 1
  }
}

**Comment by yavuzresif** [comment]
thank you very much. there were a bug in my code, at the final state when i create json string.
now i have got that error;
"userMessage": "The user does not have a return policy named: default."

i tried to create a return policy under Sales/Sale Settings/ Return Terms but it did not work
![image](https://user-images.githubusercontent.com/80310493/110465125-1568fc00-80e5-11eb-88cd-ca6bd789e3bf.png)

**Comment by yavuzresif** [comment]
as it says above, when calling ../allegro.pl/sale/product-offers;
Error:
"userMessage": "The user does not have a return policy named: default."

i tried to create a return policy under Sales/Sale Settings/ Return Terms but it did not work

**Comment by yavuzresif** [comment]
b3abf51533f21f16

**Comment by Lukasz-Zurek** [comment]
The error message is wrong and can be misleading in this specific situation. We will precise this "userMessage".

You still haven't provided a field:

`"sellingMode { returnyPolicy: { id: ""} } }"`

Please let me know if there will be any other problem.
