### ISSUE TITLE
external iD przez WWW

### ISSUE THREAD

**Issue by Jdev11** [allegro/allegro-api#4253]
Witam,
Podczas wystawienia oferty z poziomu przegladarki nie widze mozliwosci uzupelnienia pola externalID.
Czy jest jakis sposob zeby podczas wprowadzania nowego produktu/oferty uzupelnic to pole externalID?

Mysle ze zoptymalizowaloby to szukanie ofert przez rest api.
Mozna to wykorzystac przez GET sale/offers

Pozdrawiam Jerry

**Comment by AureliuszBrussy** [comment]
W [formularzu wystawiania](https://allegro.pl/offer/) masz możliwość uzupełniania pola external.id - jest to pole opisane jako "Sygnatura".
