### ISSUE TITLE
PATCH https://api.allegro.pl/sale/product-offers/ błąd 500

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#4255]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Klient natrafia na błędy 500 przy próbie aktualizacji ofert.
Przykładowe trace:
trace-id: 5979b46fac0bbea7
trace-id: 4ae79f1a903ba1ec
trace-id: 7017c33185d849fc
trace-id: c08882879b782758

W czym może być problem?

**Comment by AureliuszBrussy** [comment]
Potwierdzam występowanie błędu - leży po stronie naszej usługi. Nasz zespół pracuje już nad rozwiązaniem tego problemu. Wrócę z informacją po wdrożeniu poprawki.

**Comment by rtnet-pl** [comment]
Kolejny błąd, tym razem 422:

```
PATCH https://api.allegro.pl/sale/product-offers/9318917071 HTTP/1.1
Accept: application/vnd.allegro.beta.v2+json
Content-Type: application/vnd.allegro.beta.v2+json
Authorization: Bearer ...........
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Host: api.allegro.pl
Content-Length: 25
Expect: 100-continue
Connection: Close

{"stock":{"available":5}}

---------------------------

HTTP/1.1 422 Unprocessable Entity
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 4b183684ebeab85b
date: Fri, 19 Mar 2021 13:08:06 GMT
x-content-type-options: nosniff
content-type: application/json
content-length: 308
connection: close

{"errors":[{"code":"IllegalOfferUpdateException.IllegalChangeCategoryId","message":"You cannot change category after 12 hours from publication.","details":"IllegalOfferUpdateException.IllegalChangeCategoryId","path":"category","userMessage":"Nie możesz zmienić kategorii po 12 godzinach od wystawienia."}]}
```

**Comment by AureliuszBrussy** [comment]
@rtnet-pl i ten problem zgłosiłem do odpowiedniego zespołu. Wrócę z odpowiedzią. W kwestii pierwszego błędu zgłoszonego w tym wątku - nie został on jeszcze naprawiony, natomiast będziemy pracować nad poprawką.

**Comment by AureliuszBrussy** [comment]
@rtnet-pl wdrożyliśmy poprawkę rozwiązującą drugi problem - błąd 422 nie powinien już wystąpić. 

Pierwszy zgłoszony błąd wymaga jednak większych nakładów pracy - wrócę z informacją jaki i tutaj rozwiążemy problem.
