### ISSUE TITLE
WebApi Allegro 

### ISSUE THREAD

**Issue by koszyk82** [allegro/allegro-api#4256]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ x] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=koszyk82%40gmail.com&redirect_uri=http%3A%2F%2Fallthethings.mysky-shop.pl%2Fallegro

za kazdym razem kiedy chce integracji z skyshop,

**Comment by AureliuszBrussy** [comment]
Client_ID w odnośniku który podałeś jest niepoprawny. Zarejestruj aplikację w zakładce [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). W ten sposób uzyskasz prawidłowy Client_ID aplikacji. W [naszym poradniku ](https://developer.allegro.pl/auth/#user)opisujemy cały proces uwierzytelniania i autoryzacji. Jeżeli masz problem ze wskazaniem prawidłowych danych w aplikacji z której chcesz skorzystać - skontaktuj się z jej twórcami.
