### ISSUE TITLE
REST API - cURL request żąda włączonego JS

### ISSUE THREAD

**Issue by therionq** [allegro/allegro-api#4257]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od paru dni przy odświeżaniu access tokenów dostaję taki response:
<html><head><title>allegro.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'asd','hsh':'zxc','t':'fe','r':'b','s':16045,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>

Próba odświeżenia wszystkich access tokenów na koncie użytkownika kończy się w tym przypadku powodzeniem jedynie dla jednego połączonego konta allegro lub żadnego z nich, co uniemożliwia korzystanie z usług. W czym może być problem?

**Comment by Lukasz-Zurek** [comment]
Opisany przez Ciebie sposób odświeżania access tokenów, jak i odpowiedź, którą otrzymałeś, nie są bezpośrednio powiązane z działaniem naszego publicznego API. 

Być może na naszym forum znajdzie się użytkownik, który miał już taki problem i będzie mógł Tobie pomóc.

**Comment by therionq** [comment]
Z czym może być to związane w takim razie?
Mój request wygląda tak:

`$curl = curl_init();
  curl_setopt_array($curl, array(
    CURLOPT_URL => "https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=" . $refreshToken . "&redirect_uri=uri",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "POST",
    CURLOPT_HTTPHEADER => array(
      "Authorization: Basic ",
      "Cache-Control: no-cache",
      "Connection: keep-alive",
      "Host: api.allegro.pl"
    ),
  ));

  $response = curl_exec($curl);`

W response dostaję to co podałem wyżej.

**Comment by Lukasz-Zurek** [comment]
Ze względu na dużą liczbę jezyków programowania, nie świadczymy wsparcia dla każdego z nich. 

Możesz nam jednak przesłać request i response w formacie curl przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4257.
