### ISSUE TITLE
Działanie serwisu wysyłam z allegro

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4258]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Czy macie jakiś problem z działem, wydajnością serwisu?
Strona chodzi bardzo wolno, paczki przez API się nie generują (time outy).

**Comment by AureliuszBrussy** [comment]
Narzędzie Wysyłam z Allegro działa, ale mogą występować sporadyczne problemy dotyczące części zamówień obsługiwanych przez interfejs użytkownika. Pracujemy nad powrotem do pełnej stabilności. 

API Wysyłam z Allegro aktualnie powinno działać stabilnie.
