### ISSUE TITLE
Rest API /offers/listing InvalidOffsetException 

### ISSUE THREAD

**Issue by sis6326r** [allegro/allegro-api#426]
Cześć,
próbuję odczytać pełną listę aukcji danego sprzedawcy przy użyciu zasobu /offers/listing?seller.id={sellerId}&limit=100&offset={offset}

searchMeta.totalCount zwraca wartość 99942
parametr offset jest wielokrotnością 100 czyli parametru limit
dla offset od 0 do 59900 dane są zwracane poprawnie
dla offset od 6000 i wyższych api zwraca błąd:

{"errors":[{"code":"InvalidOffsetException","message":"Invalid offset parameter value. Offset should be multiplier of limit and less than searchMeta.availableCount.","details":null,"path":null,"userMessage":"Invalid request. Fix the request and try again."}]}

Wygląda na to, że ta metoda działa tylko dla pierwszych 60 tyś wyników.

**Comment by TimothyKoval** [comment]
```
"searchMeta": {             -- number of offers that meet the
                            requirements provided
    "availableCount": 1,    -- number of offers that meet the requirements
                            provided in the request and are displayed.
                            For example – the number of offers matching
                            a particular request is 2,000,000, but
                            we will display up to 60,000. Therefore
                            “60,000” is the value of availableCount.
    "totalCount": 1,        -- total number of offers that meet the
                            requirements provided in the request.
                            For example – the number of offers
                            matching a particular request is 2,000,000,
                            but we will display up to 60,000 offers.
                            Therefore “2,000,000” is the value of
                            totalCount.

```

**Comment by sis6326r** [comment]
OK to w takim razie jak można sprawdzić całkowitą ofertę danego sprzedawcy?

**Comment by TimothyKoval** [comment]
[Nie można.](https://github.com/allegro/allegro-api/issues/369#issuecomment-405530236)

**Comment by kfijalko** [comment]
Trzeba pobrać sortując po cenie rosnąco (60k), nastepnie malejąco (60k), wybrać unikaty i będzie pałna lista dla jednego konta.
Jeszcze nie sprawdziłem ale powinno zadziałać.

**Comment by sis6326r** [comment]
Jest to jakiś pomysł:) Ale czy allegro nie mogłoby zwiększyć limitu do 100 tyś? Sprzedawca i tak nie może mieć więcej aktualnie i byłby temat z głowy.

**Comment by kfijalko** [comment]
Jak się nie ma co się chce ... ;)

**Comment by AniaMalinowska** [comment]
Informacyjnie:
aktualnie jeśli w [zapytaniu](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/) poda się ID sprzedawcy, to można pobrać nawet 120 000 ofert.
