### ISSUE TITLE
co wpisać w miejsce tokena, client secret czy client id?

### ISSUE THREAD

**Issue by zlotowinfo** [allegro/allegro-api#4261]
curl -X GET \
  'https://api.allegro.pl/offers/listing?category.id=77917&phrase=laptop&fallback=false&limit=1&searchMode=DESCRIPTIONS' \
  -H 'Authorization: Bearer {token}' \
  -H 'Accept: application/vnd.allegro.public.v1+json'

ale na stronie allegro nie dali "token", podali secret i id, to które jest prawidłowe?
  -H 'Authorization: Bearer {Client Secret}' \
  -H 'Authorization: Bearer {Client ID}' \

**Comment by zlotowinfo** [comment]
dostaję tylko error w powyższym

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=###&redirect_uri=http://exemplary.redirect.uri&code_challenge_method=S256&code_challenge=###");

//curl_setopt($ch, CURLOPT_URL, "https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=###&redirect_uri=http://exemplary.redirect.uri&code_challenge_method=plain&code_challenge=###");

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $output = curl_exec($ch);
        curl_close($ch);     

echo $output;

próbowałem dwóch powyższych, ale nic się nie wyświetla

**Comment by Lukasz-Zurek** [comment]
Zarejestruj aplikację w zakładce [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). W ten sposób uzyskasz Client_ID i Client Secret, które są niezbędne do wygenerowania wspomnianego tokena. W [naszym poradniku](https://developer.allegro.pl/auth/#user) opisujemy cały proces uwierzytelniania i autoryzacji.
Jednocześnie zapoznaj się proszę z [ostatnimi zmianami](https://github.com/allegro/allegro-api/issues/4213) dotyczącymi zasobu _GET /offers/listing_, z którego planujesz korzystać.

**Comment by zlotowinfo** [comment]
mam zarejestronwane i podaje swoje id i secret
więc chyba dobrze robię, powinno coś być w $output 
a nic nie jest wyświetlane przez echo

**Comment by Lukasz-Zurek** [comment]
Na adres podany w parametrze redirect_uri zwrócimy kod autoryzujący, jednorazowego użytku, ważny przez 10 sekund.
Zwrócony przez nas kod przekaż w parametrze code, wykonując żądanie metodą POST, poniżej przykład:

`curl -X POST -H 'Authorization: Basic YTI...Hg=' 'https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri'`

W odpowiedzi zwrócimy m.in. access token, który możesz wykorzystać w swoim żądaniu _GET /offers/listing_.

**Comment by zlotowinfo** [comment]
dobra, zadziałało, jakiś fake adres tam podali
podałem z innej strony allegro.pl/auth/oauth/token i wyszedł token
