### ISSUE TITLE
API offers/listing często pojawia się komunikat o too many request

### ISSUE THREAD

**Issue by epartshop** [allegro/allegro-api#4262]

**Comment by Lukasz-Zurek** [comment]
Zgodnie z pkt. 4.1 c [regulaminu](https://developer.allegro.pl/rules/) REST API niedozwolone jest: “wykorzystywanie do prezentowania w serwisach konkurencyjnych Ofert (w tym Ofert archiwalnych) publikowanych w ramach Allegro”.

W związku z powyższym nie zezwalamy na wspomniane działanie.
