### ISSUE TITLE
Problem z utworzeniem przesyłki

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#4263]
Dzień dobry, 
mam problem z zasobem `https://api.allegro.pl/parcel-management/parcel-create-commands/`
Nie jestem w stanie utworzyć przesyłki, ciągle wyskakuje błąd 400
`[code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /parcel-management/parcel-create-commands/9a0136bb-d533-4e37-b5c2-7795dfc17304
                    [userMessage] => `

Brakuje mi już pomysłów co może iść nie tak.

**Comment by AureliuszBrussy** [comment]
Pole **items** jest tablicą obiektów, a nie pojedynczym obiektem.

W swoim requeście zamiast:
```
...
"items": {
    "dimensions": {...}
}
...
```

przekaż:
```
...
"items": [{
    "dimensions": {...}
}]
...
```

**Comment by lukaszkrakowiak** [comment]
Dzieki, nie zauważyłem tego :)

**Comment by lukaszkrakowiak** [comment]
teraz, za każdym razem, mam problem tego typu:
`[id] => 9a0136bb-d533-4e37-b5c2-7795dfc17306
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => Processing error
                    [details] => 
                    [path] => 
                    [userMessage] => Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem
                )

        )`

**Comment by AureliuszBrussy** [comment]
Problemem okazał się brak wartości w polu **label.sender.address.countryCode** oraz w **pickup.adress.countryCode** podczas tworzenia przesyłki. Utwórz nową przesyłkę oraz uzpełnij wartości w tych polach.

**Comment by lukaszkrakowiak** [comment]
Rozumiem, w takim razie w dokumentacji jest błąd, ponieważ te pola nie są oznaczone jako obowiązkowe.

**Comment by AureliuszBrussy** [comment]
Nie jest to stricte błąd w dokumentacji. Ustawiliśmy wymagalność dla pól, które są absolutnie niezbędne do utworzenia paczki dla zbioru wszystkich przewoźników, jednak część pól niewymaganych może się okazać konieczna dla konkretnego przewoźnika.

Oznacza to, że przesłany zestaw danych wystarczy do utworzenia paczki dla jednego przewoźnika, ale niekonieczne dla innego.
