### ISSUE TITLE
Korzystanie z API bez autoryzacji w przeglądarce

### ISSUE THREAD

**Issue by patrykpalej** [allegro/allegro-api#4264]
Podczas korzystania z API moja aplikacja autoryzuje się w przeglądarce, ponieważ korzystam z aplikacji typu WEB. Wiem że jest też aplikacja typu DEVICE, która do autoryzacji nie potrzebuje przeglądarki. W jaki sposób nalezy wowczas zmienić procedurę autoryzacji żeby przeglądarka nie była konieczna?

**Comment by Lukasz-Zurek** [comment]
Cały proces autoryzacji typu DEVICE szczegółowo opisaliśmy w [naszym poradniku](https://developer.allegro.pl/auth/#userDeviceFlow). Jeśli masz wątpliwości, chętnie odpowiem na wszelkie pytania.

**Comment by jakubmaguza** [comment]
Przeglądarka i tak będzie potrzebna, z tą różnicą, że klient będzie musiał sam wejść na podaną stronę i zaakceptować połączenie z API. Może to zrobić z dowolnego komputera/telefonu.

**Comment by patrykpalej** [comment]
> 
> 
> Przeglądarka i tak będzie potrzebna, z tą różnicą, że klient będzie musiał sam wejść na podaną stronę i zaakceptować połączenie z API. Może to zrobić z dowolnego komputera/telefonu.

W takim razie korzystanie z API na maszynie wirtualnej bez dostępu do przeglądarki nie będzie w ogóle możliwe?

**Comment by jakubmaguza** [comment]
Będzie. Możesz wyświetlić w konsoli link i użyć go na innym komputerze/telefonie. Możesz wysłać ten link mailem.

To raczej jednorazowa sytuacja, bo potem możesz użyć refreshToken, wtedy już przeglądarka nie jest potrzebna.

https://developer.allegro.pl/auth/#userDeviceFlow

Przeczytaj dokładnie jak to działa. W dużym skrócie:
1. Generujesz link
2. Pytasz endpoint co X sekund czy ktoś wszedł pod ten link
3. Wchodzisz pod ten link na innej maszynie.
4. Twoja aplikacja dostaje Tokeny
