### ISSUE TITLE
Problem z uzyskaniem API ALLEGRO DPD 

### ISSUE THREAD

**Issue by erajuniora** [allegro/allegro-api#4265]
Witam

bardzo proszę kolejny raz o pomoc... i przekazanie nam numeru API ALLEGRO DPD, bez tego nie jesteśmy w stanie generować paczek w naszej aplikacji zewnętrznej. A przy "wysyłam z allegro" musimy generować list przewozowy dla każdej paczki po kolei i zajmuje to mnóstwo czasu.

Czy mogą Państwo nam przekazać sam numer API? Tak jak robią to wszystkie firmy kurierskie? Nie mamy obecnie umowy z DPD i nie chcemy jej podpisywać.

Potrzebujemy numer **API DPD ALLEGRO.** Sprawa jest bardzo pilna...

Pozdrawiam i liczę na szybką i rzetelną odpowiedź.

**Comment by Lukasz-Zurek** [comment]
Nie dysponujemy danymi, do których dostęp posiadają firmy kurierskie. Umożliwiamy jedynie korzystanie z naszego API usługi "Wysyłam z Allegro", gdzie wymagana jest umowa własna z DPD. W tej sytuacji skontaktuj się proszę z firmą DPD.

**Comment by erajuniora** [comment]
Ale mamy możliwość wysyłania paczek za pomocą ALLEGRO DPD bez konieczności podpisana umowy z Allegro. 
DPD nie udzieli nam takiej informacji, gdyż nie jesteśmy bezpośrednio już ich Klientem. 
Z kilku źródeł mam informację, że to Państwo, czyli Allegro, muszą podać mi numer API allegro, za pomocą którego będziemy mogli nadawać paczki, tak jak do tej pory, czyli bez umowy z DPD, ale bezpośrednio ze swojej aplikacji, bez tego numeru jesteśmy zblokowani.

**Comment by erajuniora** [comment]
Przepraszam, miało być oczywiście "bez konieczności podpisania umowy z DPD".

**Comment by Lukasz-Zurek** [comment]
Temat nie dotyczy stricte naszego API. Nie jesteśmy w stanie udostępnić Tobie wspomnianych danych. 

Jeśli natomiast chodzi o możliwość nadawania przesyłek bez umowy DPD, taka funkcjonalność jest faktycznie dostępna w usłudze “Wysyłam z Allegro”. Więcej informacji na ten temat znajdziesz pod [tym adresem.](https://allegro.pl/dla-sprzedajacych/allegro-kurier-dpd-nowy-model-rozliczeniowy-ZGjlBn2rdU4#wysylam-z-allegro-korzystaj-bez-umowy-z-dpd)

**Comment by erajuniora** [comment]
Całe sedno sprawy polega na tym, że nie chcemy korzystać z aplikacji "Wysyłam z Allegro" tylko z aplikacji, z której korzystamy do obsługi konta Allegro (obu naszych sklepów) - Sellasist. 
Od usługodawców programu wiemy, że potrzebny jest nam jedynie kod API Allegro, aby podłączyć wysyłki DPD Allegro.
Gdy mieliśmy umowę bezpośrednio z DPD, taki numer udostępniło nam DPD, teraz Allegro pośredniczy między nami jako sklepem a DPD, więc to do Was jest kierowana prośba o podanie numeru API.

Procedura uzyskania narzędzia nadawczego opisana jest tutaj:

https://sellasist.pl/pomoc/jak-uruchomic-integracje-allegro-dpd-w-sellasist

Z tym, że pod mailem dpd_allegro@dpd.com.pl, uzyskałam informację, że mam się zgłosić bezposrednio do Allegro z prośbą o numer, a od nich dostałam przekierowanie TUTAJ.

**Comment by erajuniora** [comment]
![Login i hasło DPD](https://user-images.githubusercontent.com/80516926/111023582-30d05180-83da-11eb-8bb5-1d3cf1737318.png)

Jak wyżej: wymagane są login i hasło do API, do narzędzia nadawczego dla podanej metody wysyłki, czyli kurier DPD allegro.

**Comment by hahyes** [comment]
> Jak wyżej: wymagane są login i hasło do API, do narzędzia nadawczego dla podanej metody wysyłki, czyli kurier DPD allegro.

W REST API Allegro nie ma czegoś takiego jak login i hasło do API. Tutaj definitywnie ta metoda dostawy przewiduje korzystanie z API DPD. Żeby korzystać z Wysyłam z Allegro musisz korzystać z integracji z Allegro, a nie z integracji DPD. Nie wiem, jak to jest skonstruowane na konkretnej platformie, więc więcej nie pomogę. Jednak to, co pokazałeś na screenie nie ma nic do Allegro.

**Comment by erajuniora** [comment]
Witam

okazało się, że w naszej aplikacji jest integracja "wysyłam z allegro" .. Niestety usługodawcy aplikacji nas o tym nie poinformowali, tylko wciąż radzili kontakt z Allegro. 

Zintegrowałam przed momentem "wysyłam z allegro" na naszej platformie i wszystko działa.
Bardzo dziękuję za pomoc.

**Comment by Lukasz-Zurek** [comment]
@erajuniora Bardzo dziękuję za informację.
