### ISSUE TITLE
/order/events w wersji testowej zwraca pustą tablicę zamiast listy zdarzeń

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#4268]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem testowym

**Zostały stworzone dwa zamówienia w systemie testowym allegro:**
71588941-8342-11eb-b746-2b702e2d5ab3
265dc241-833b-11eb-b746-2b702e2d5ab3

Jedno jest opłacone, drugie płatne przy odbiorze.

**Po wywołaniu /order/events z parametrami:**
- limit=1
- type=READY_FOR_PROCESSING

Zwracana jest pusta tablica w formacie JSON:
{"events":[]}

**Oczekiwane zachowanie:**

Powinno zwrócić jedno najstarsze zdarzenie z listy zdarzeń gdzie type=READY_FOR_PROCESSING

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem przed momentem i wygląda na to, że jest już ok - zwracane jest zdarzenie z 12.03.

**Comment by tztztztz** [comment]
Niestety to nadal nie działa: wykonując /order/events dostaję pustą tablicę w json.

Komenda /order/events jest oczywiście wykonywana na tym samym koncie testowym, które stworzyło obydwie oferty.

Być może Wy testujecie w inny sposób, proszę spróbować pobrać te zakupy/checkout forms z naszego konta - nic nie zwraca.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę przykładowy request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4268.

**Comment by tztztztz** [comment]
Dane wysłane przez formularz kontaktowy, macie pełne info na temat nagłówków HTTP wysłanych, odebranych (wraz z trace id) oraz treść odpowiedzi - czyli JSON z pustą tablicą.

**Comment by tztztztz** [comment]
Trace id = c90d593889c2a4a3

**Comment by tztztztz** [comment]
Przepraszam bardzo, ale loguje się na to konto z którego robię zapytania API i widzę dwa zamówienia w testowym allegro. Następnie z tego konta robię zapytanie API i zwraca mi pustą listę zamówień.

Chociaż w tej chwili zostało tylko jedno, a drugie które było zrobione wczoraj jakoś magicznie zniknęło.

Jeszcze raz:

1) mam login X - loguje się na niego na https://allegro.pl.allegrosandbox.pl, wchodzę na https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty: widzę teraz jedno zamówienie opłacone

2) z tego samego lioginu X robię zapytanie API /order/events - nic nie zwraca.

**Comment by tztztztz** [comment]
Ok, jednak problem był po naszej stronie - ktoś odświeżył tokena nie do tego konta co trzeba, przepraszam za zamieszanie, aczkolwiek nadal zostaje kwestia tego, że zniknęło sobie jedno zamówienie z wczoraj.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę szczegóły w odpowiedzi na ostatnią naszą wiadomość. Zweryfikujemy to.

**Comment by tztztztz** [comment]
- zamówienie 265dc241-833b-11eb-b746-2b702e2d5ab3 istnieje 
- zamówienie 71588941-8342-11eb-b746-2b702e2d5ab3 zniknęło z listy zamówień na stronie https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty

**Comment by tztztztz** [comment]
Przepraszam, kolejna pomyłka - wszystko już jest w porządku, zamówienie istnieje i zostało pobrane, zamykam.
