### ISSUE TITLE
429/too many requests po wykoakniu 7 requestow

### ISSUE THREAD

**Issue by TonyAntoni** [allegro/allegro-api#4269]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny
 

Nie mam jak podać cCURL, używam pythona. Z rzeczy które mogą się przydać to limit występuje na endpointcie /offers/listing na produkcji. 10s przerwy między requestami niweluje błąd, lecz jednak w dokumentacji napisane jest o 9000/min. headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.allegro.public.v1+json"} | query_params = {"phrase": search_query, "searchMode": "REGULAR", "sort": "relevance"}

**Comment by AureliuszBrussy** [comment]
Poproszę o trace-id przykładowego wywołania, które zakończyło się błędem 429. Zapoznam się z sytuacją.

**Comment by TonyAntoni** [comment]
200 {'trace-id': 'a4feb1cc444ee1a6', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '54606', 'date': 'Mon, 15 Mar 2021 11:41:01 GMT'}
200 {'trace-id': '9c9349178e6c601c', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '54287', 'date': 'Mon, 15 Mar 2021 11:41:01 GMT'}
200 {'trace-id': '9350bfc90c271986', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '58692', 'date': 'Mon, 15 Mar 2021 11:41:01 GMT'}
200 {'trace-id': '69e431a91137f052', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '55410', 'date': 'Mon, 15 Mar 2021 11:41:01 GMT'}
200 {'trace-id': '7b785683fd4b9155', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '53237', 'date': 'Mon, 15 Mar 2021 11:41:02 GMT'}
200 {'trace-id': '9eb9a37cae5de46b', 'content-type': 'application/vnd.allegro.public.v1+json', 'content-length': '51514', 'date': 'Mon, 15 Mar 2021 11:41:02 GMT'}
429 {'trace-id': '2148deedf5b922b', 'content-type': 'application/json; charset=utf-8', 'content-length': '204', 'date': 'Mon, 15 Mar 2021 11:41:02 GMT'}
429 - TooManyRequestsException
429 {'trace-id': '1dbf7928a2277af8', 'content-type': 'application/json; charset=utf-8', 'content-length': '204', 'date': 'Mon, 15 Mar 2021 11:41:13 GMT'}
429 - TooManyRequestsException

**Comment by AureliuszBrussy** [comment]
Limit na tym zasobie jest inny niż 9000 req/min i związany jest on z [zapowiedzianą przez nas zmianą](https://github.com/allegro/allegro-api/issues/4213). Aby móc wykonać większą liczbę zapytań, zweryfikuj swoją aplikację, zgodnie z [komunikatem](https://github.com/allegro/allegro-api/issues/4213).
