### ISSUE TITLE
Zwroty

### ISSUE THREAD

**Issue by lukasnet** [allegro/allegro-api#427]
[Pytanie] Czy przez webapi/restapi jest lub będzie (kiedy) obsługa Zwrotu zakupów przez kupującego? czyli zakładki https://allegro.pl/myaccount/ReturnsListing.php

**Comment by AniaMalinowska** [comment]
Obsługa zwrotu zakupów przez kupującego, czyli tej [zakładki](https://allegro.pl/myaccount/ReturnsListing.php) nie jest dostępna przez API. Jeśli ją udostępnimy, poinformujemy o tym

**Comment by lukasnet** [comment]
Przypominam się i czekam na obsługę tego, bo już pół roku minęło i dalej nic.
