### ISSUE TITLE
Który zasób służy do pozyskania informacji o danej ofercie ?

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#4272]
Bedę wdzięczny za podanie , który zasób służy dla pozyskania informacji o danej ofercie , chodzi mi o opis produktu. Chodzi mi o informacje o publicznej ofercie .

**Comment by jasiek07** [comment]
mam na mysli wyszukaną ofertę publiczną (nie konkretnego sprzedawcy) . Czy jest to możliwe ?

**Comment by Lukasz-Zurek** [comment]
Nie pozyskasz informacji o konkretnej, publicznej ofercie. Możesz jednak skorzystać z zasobu: [GET offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), aby móc wyszukać oferty, korzystając z filtrów takich jak np. `phrase`.

Więcej informacji na temat dokładnego filtrowania wyników znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/).

Zapoznaj się również z [naszym ostatnim newsem](https://github.com/allegro/allegro-api/issues/4213).

**Comment by jasiek07** [comment]
To czy jest jakiś inny sposób pozyskania opisu danej oferty ? komende php file_get_contents allegro zblokowało

**Comment by Lukasz-Zurek** [comment]
Nie, jeśli chodzi o ofertę publiczną - nie ma możliwości pozyskania jej opisu.
