### ISSUE TITLE
Powstaje draft z nadanym numerem oferty pomimo odpowiedzi 422

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4273]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Zaobserwowałem, że w przypadku kiedy tworzę ofertę podając zły wholesalePriceList.id to otrzymuję odpowiedź z kodem 422 i treścią informującą tylko o rodzaju błędu {"errors":[{"code":"VALIDATION_ERROR","message":"Wholesale price list with given id does not exists."....} co jest jak najbardziej w porządku z jedną różnicą. Otóż draft pojawia się na koncie. 

Czyli dostaję 422 i nie dostaję id/numeru draftu a mimo to draft zostaje utworzony z nowym numerem oferty.
Np. trace-id: bc65f7b840a1a95c

Wydaje mi się, że jeśli draft zostanie utworzony to powinienem dostać w odpowiedzi jego numer a informacja o błędzie powinna pojawić się w polu validation. Gdy jednak draft jest utworzony a nie dostaję jego numeru podczas wystawiania to muszę wyszukiwać regularnie takie przypadki wywołując sale/offers?publication.status=INACTIVE.

Czy pojawienie się 422 z równoczesnym utworzeniem draftu nie jest błędem?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Wskazane zachowanie nie jest błędem. W takim przypadku draft oferty nawet nie powstaje.

**Comment by tomylee0** [comment]
Tu mam nowy przykład:
trace-id: db0a1587139d587

Dostałem 422 z błędem "Wholesale price list with given id does not exists." I równocześnie pojawił się draft 10504025459.

**Comment by Lukasz-Zurek** [comment]
Dziękuję. Błąd został już zgłoszony. 

Przepraszamy za utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Wdrożyliśmy poprawkę i problem nie powinien już występować.
