### ISSUE TITLE
Którym zapytaniem możemy uzyskać pełną ścieżke kategorii wraz z jej kategoriami matkami znając id kategorii końcowej ?

### ISSUE THREAD

**Issue by jasiek07** [allegro/allegro-api#4274]
Którym zapytaniem możemy uzyskać pełną ścieżke kategorii wraz z jej kategoriami matkami znając id kategorii końcowej ?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma bezpośredniego zapytania, dzięki któremu uzyskasz całą ścieżkę kategorii.  Możesz skorzystać z [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1), w odpowiedzi otrzymasz m.in. pola **id** oraz **parent.id**. Jeśli w kolejnym zapytaniu przekażesz dane **parent.id**, w wynikach otrzymasz wszystkie "kategorie dzieci" związane z tym działem.
