### ISSUE TITLE
Zwrot pieniędzy

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#4275]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 
Mam pytanie co do zwrotów pieniędzy. Według informacji na stronie:  https://allegro.pl/pomoc/dla-sprzedajacych/platnosc-od-kupujacego/jak-zwrocic-wplate-kupujacemu-xG71g2rkRIx

> Jeśli po 24 godzinach w Allegro Finanse nadal nie będzie wystarczających środków do wykonania zwrotu, zostanie on anulowany. Aby ponownie wykonać zwrot wpłaty, postępuj zgodnie z powyższą instrukcją. Zwrot wpłaty możesz wykonać przez rok, licząc od daty otrzymania płatności od kupującego na Allegro Finanse.

Mam zwrot o numerze c11549f1-7447-11eb-bf0e-73fd86591eab, który widnieje w waszym systemie jako w realizacji od dnia 21 lutego 2021, 14:21, czyli grubo ponad 24 godziny. 

Dodatkowo według rozliczeń okazuje się że ten przelew został pobrany przez was z naszych środków:

21.02.2021, 14:27 | zwrot  PayU       184a6d41-f12b-11ea-b809-e3b45dabb55b | | szczegóły zwrotu | -53,52 zł |  

A klient twierdzi, że środków nie otrzymał.

**Comment by PrzemyslawLukanowski** [comment]
W związku z tym, że nie jest to problem techniczny związany z działaniem API, ale stricte z wykonaniem płatności, skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=d1df83fc-8979-4595-90f6-008242ba2095&subjectId=ac728b31-985b-4dd2-81a8-724f0b65170f). Dzięki temu zgłoszenie trafi do odpowiedniego zespołu, który zajmie się analizą problemu.
