### ISSUE TITLE
Wybranie ilosci przez URL produktu

### ISSUE THREAD

**Issue by morgutrin** [allegro/allegro-api#4277]
Witam, 
mam pytanie. Czy przez URL produktu możliwe jest wybranie od razu jego ilości?
https://allegro.pl/oferta/moskitiera-okienna-ramka-siatka-na-wymiar-9517776397?fromVariant=9052368386
probowałem już dodać np. parametr ?quantity=3 , ale nie działało. 

Dziękuję i pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Doprecyzuj proszę który zasób w naszym API masz konkretnie na myśli i co chciałbyś uzyskać ?
