### ISSUE TITLE
Usunięcia błędnie nadanego numeru przesyłki z zamówienia

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#4278]
Czy można usunąć błędnie nadany numer przesyłki do zamówienia złożonego przez użytkownika?

Moje pytanie dotyczy zasobu:
https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST

Problem polega na tym, że do dużej części zamówień zostały dodane błędne numery. Z poziomu interfejsu sprzedawcy można ten numeru usunąć, czy można to również usunąć z poziomu REST API?

Z góry dziękuję za pomoc!

**Comment by Lukasz-Zurek** [comment]
Nie udostępniamy takiego zasobu w naszym API.
