### ISSUE TITLE
Podaj czas wysyłki - jak to dodać do WEBAPI - nie widzę nic w specyfikacji

### ISSUE THREAD

**Issue by umnierazniej** [allegro/allegro-api#428]
Witam,
Dziś po raz pierwszy otrzymałem błąd przy wystawianiu przez WebApi:
ERR_CONSTRAINT_VIOLATION_EXCEPTION_REQUIRE_ESTIMATED_SHIPPING_TIME Podaj czas wysyłki. Czas wysyłki nie może być pusty.
Co należy dodać aby to dodatkowe pole zostało uzupełnione?

**Comment by AniaMalinowska** [comment]
Zgodnie z [zapowiedzią](https://allegro.pl/webapi/news.php#news_100619) - wymagamy, aby także przez WebAPI określać czas wysyłki w ofertach. Służy do tego pole 'czas wysyłki', czyli FID 340:

` <ns1:item>
                  <ns1:sellFormId>340</ns1:sellFormId>
                  <ns1:sellFormTitle>Czas wysyłki</ns1:sellFormTitle>
                  <ns1:sellFormCat>0</ns1:sellFormCat>
                  <ns1:sellFormType>4</ns1:sellFormType>
                  <ns1:sellFormResType>2</ns1:sellFormResType>
                  <ns1:sellFormDefValue>0</ns1:sellFormDefValue>
                  <ns1:sellFormOpt>8</ns1:sellFormOpt>
                  <ns1:sellFormPos>0</ns1:sellFormPos>
                  <ns1:sellFormLength>4</ns1:sellFormLength>
                  <ns1:sellMinValue>0.00</ns1:sellMinValue>
                  <ns1:sellMaxValue>1440.00</ns1:sellMaxValue>
                  <ns1:sellFormDesc>-- Wybierz --|0|24|48|72|96|120|168|240|336|504|720|1440</ns1:sellFormDesc>
                  <ns1:sellFormOptsValues>0|1|24|48|72|96|120|168|240|336|504|720|1440</ns1:sellFormOptsValues>
                  <ns1:sellFormFieldDesc>Określ, ile czasu zajmie Ci wysłanie przedmiotu Kupującemu.</ns1:sellFormFieldDesc>
                  <ns1:sellFormParamId>0</ns1:sellFormParamId>
                  <ns1:sellFormParamValues/>
                  <ns1:sellFormParentId>0</ns1:sellFormParentId>
                  <ns1:sellFormParentValue/>
                  <ns1:sellFormUnit/>
                  <ns1:sellFormOptions>0</ns1:sellFormOptions>
               </ns1:item>`

Informacje na ten temat zamieściliśmy także [tutaj](https://github.com/allegro/allegro-api/issues/302#issue-331989234).

**Comment by barthoos** [comment]
No to dlaczemuz, for god sake, metoda doGetSellFormFieldsForCategory zwraca w polu sellFormOpt wartosc "8" (czyli obligatoryjny) zamiast "1" (wymagany) dla FID = 340 ???

**Comment by barthoos** [comment]
Zreszta (co nawet jest zabawne) w Twojej Ani odpowiedzi traktujacej o tym, ze to pole jest wymagane, przeklejasz jego definicje, z ktorej wynika ze jest opcjonalne :)

**Comment by AniaMalinowska** [comment]
@barthoos dziękujemy, zaktualizujemy to. Pozdrawiam :)

**Comment by AniaMalinowska** [comment]
Już powinno być ok.

**Comment by FreelinePL** [comment]
O dziwo zgadza się ;)

**Comment by FreelinePL** [comment]
Dzisiaj znowu fid 340 jest opcjonalny (sellFormOpt=8). To jak to w końcu jest z tym fid-em??

**Comment by AniaMalinowska** [comment]
Musieliśmy to przywrócić, ponieważ był problem z wystawianiem ogłoszeń przez API. Dostosowaliśmy przed chwilą opis tego fida do stanu rzeczywistego. Przepraszamy za zamieszanie.

**Comment by FreelinePL** [comment]
Nieobowiązkowe obowiązkowe...

**Comment by barthoos** [comment]
No to ekhm, rozumiem ze mamy sobie sami "recznie" nadpisywac obowiazkowosc tego pola u siebie? 

Uzytkownik mojej aplikacji nie wie, ktore pola sa obowiazkowe dla danej kategorii, a ktore nie. Opiera sie na moich wskazaniach, a te z kolei opieraja sie na definicji pobranej bezposrednio u zrodla. Tylko zrodlo mowi nie prawde.. 

Skoro macie rozroznienie pomiedzy aukcjami a ogloszeniami to dodajcie pole sellFormAdOpt, ktore bedzie dotyczylo ogloszen i ustawcie rozne wartosci w obu.

Troche kabaret.
