### ISSUE TITLE
Pobieranie opisu oferty

### ISSUE THREAD

**Issue by marcingi** [allegro/allegro-api#4280]
Witam serdecznie,

wytlumaczy mi ktos lopatologicznie, jak pobrac opis oferty, ktory potrzebuje na potrzeby Excela, aby wystawiac oferty przez plik csv.

Krok po kroku, zorbilem jak pisalo na stronie i zwraca mi brak autoryzacji.

Prosze o pomoc.

System Windows 10/Ubuntu ze sklepu App.

DZIEKUJE z gory za instrukcje step by step

**Comment by PrzemyslawLukanowski** [comment]
Jeśli masz na myśli, jak pobrać swoje oferty przez API, służy do tego [GET /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Opis znajduje się w sekcji description. Jeśli w odpowiedzi otrzymujesz kod błędu, prześlij nam trace-id, sprawdzimy co jest nie tak w żądaniu.

**Comment by marcingi** [comment]
wlasnie, ale zwraca mi brak autoryzacji, autoryzowalem sie przez php i curla tak jak pisze w dokumentacji, wygenerowalem na stronie developer.allegro.pl dane i wpisalem do pliku php..

z tym potrzebuje pomocy

**Comment by PrzemyslawLukanowski** [comment]
Ale czy dobrze rozumiem - udało Ci się wygenerować token, ale błąd dostajesz już na etapie żądania do GET /sale/offers/{id}? Jeśli tak, podaj proszę trace-id lub prześlij nam logi za pomocą formularza kontaktowego, gdzie dopisz, że dane dotyczą wątku #4280 na GitHubie. Jeśli masz natomiast problem z  wygenerowaniem tokena w PHP, zerknij na nasze wątki z przeszłosci, gdzie pojawiły się przykłady prawidłowego kodu od innych użytkowników forum:

#226
#2306
#708
