### ISSUE TITLE
Pobranie pojedynczej oferty poprzez REST API 

### ISSUE THREAD

**Issue by exu** [allegro/allegro-api#4281]
Witam, 

Czy jest możliwe pobranie danych publicznej oferty (klient nie jest właścicielem oferty) poprzez REST API ? 
Chciałbym sprawdzić czy dana oferta już wygasła na potrzeby linków afiliacyjnych.

Znalazłem https://developer.allegro.pl/documentation/#operation/getListing ale niestety nie ma tam nigdzie ID oferty.

**Comment by PrzemyslawLukanowski** [comment]
GET /offers/listing to jedyny sposób, w jaki możesz pobrać dane na temat ofert innych sprzedawców. Zapoznaj się jednak z [zmianami dla tego zasobu](https://developer.allegro.pl/news/#terms-and-conditions-changed), o których informowaliśmy wczoraj. Wyszukać ofertę możesz np. za pomocą frazy i kategorii, a ID znajduje się w obiekcie związanym z daną ofertą.
