### ISSUE TITLE
REST API i "hasła do aplikacji"?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4282]
W którym miejscu podczas tworzenia requestów REST API można użyć "hasła do aplikacji"? 

Na stronie:
https://allegro.pl/pomoc/dla-kupujacych/logowanie-i-haslo/czym-jest-dwustopniowe-logowanie-i-dlaczego-warto-z-niego-korzystac-dykqg9nMKSZ
mamy taki fragment:

_Jeśli włączysz dwustopniowe logowanie, do REST API zalogujesz się tylko hasłem aplikacyjnym. Ustawisz je w zakładce Hasła do aplikacji. Dowiedz się więcej._

W REST API mamy client_id, client_secret, tokeny... Nie widzę tu miejsca dla "hasła do aplikacji".

Czy to błąd w dokumentacji i autorowi chodziło tu o WebAPI?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za spostrzeżenie, masz rację, usuniemy ten fragment z artykułu.
