### ISSUE TITLE
dodawanie zdjęć przez POST /sale/product-offers 

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#4283]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam serdecznie,

podczas wystawiana aukcji za pomocą POST /sale/product-offers  automatycznie do aukcji dodają się zdjęcia z produktu.
Czy jest to prawidłowe działanie? Są to z reguły zdjęcia innego sprzedawcy do których nie mamy praw.

W jaki sposób wystawić nową aukcję powiązaną z produktem, lecz przypisując tylko własne zdjęcia?

**Comment by PrzemyslawLukanowski** [comment]
Tak, jest to prawidłowe zachowanie. Zgodnie z informacją z naszego poradnika:

```
Jeśli na podstawie przekazanych danych rozpoznamy, że produkt istnieje w naszej bazie, to weźmiemy jego dane i uwzględnimy je w wystawionej ofercie. Będą to:

- kategoria i parametry,
- zdjęcia,
- opis produktu (jeśli nie przekażesz własnego),
- numery EAN,
- sekcja pasuje do,
- specyfikacja techniczna TecDoc.
```

Nie ma możliwości przypisania tylko własnych zdjęć na poziomie requestu POST /sale/products-offers, możesz to zrobić jedynie przez edycję oferty w następnym kroku.

**Comment by hahyes** [comment]
> Tak, jest to prawidłowe zachowanie. Zgodnie z informacją z naszego poradnika:
> 
> ```
> Jeśli na podstawie przekazanych danych rozpoznamy, że produkt istnieje w naszej bazie, to weźmiemy jego dane i uwzględnimy je w wystawionej ofercie. Będą to:
> 
> - kategoria i parametry,
> - zdjęcia,
> - opis produktu (jeśli nie przekażesz własnego),
> - numery EAN,
> - sekcja pasuje do,
> - specyfikacja techniczna TecDoc.
> ```
> 
> Nie ma możliwości przypisania tylko własnych zdjęć na poziomie requestu POST /sale/products-offers, możesz to zrobić jedynie przez edycję oferty w następnym kroku.

@PrzemyslawLukanowski 
Mam pytanie w związku z tym, a nie chcę specjalnie tworzyć wątku. Czy dodając ofertę powiązaną z produktem poprzez zasób _POST /sale/offers_, można przypisać wyłącznie własne zdjęcia do takiej oferty? Czy jednak wtedy obowiązują też zasady, jak z zasobu POST /sale/product-offers?

**Comment by PrzemyslawLukanowski** [comment]
@hahyes W tym przypadku możesz przypisać tylko własne zdjęcia. Dla /sale/offers ważne jest, abyś strukturze oferty przekazał kategorię i parametry zgodne z wybranym produktem. Jeśli nie przekażesz zdjęć z produktu, walidacja nie zwróci żadnego błędu. Inaczej sytuacją wygląda dla POST /sale/product-offers, ponieważ w tym zasobie zdjęcia są pobierane bezpośrednio z danych produktu i dołączane do oferty.

**Comment by PrzemyslawLukanowski** [comment]
@hahyes @dlis2010 Wczoraj [wprowadziliśmy rozwiązanie](https://github.com/allegro/allegro-api/issues/4691), dzięki któremu możecie przypisywać do ofert tylko swoje zdjęcia.
