### ISSUE TITLE
dziwne zachowanie przy edycji zdjęć PATCH /sale/product-offers/{offerId}

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#4284]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym

:beetle: **Opis**
Dziwne zachowanie podczas edycji zdjęć w ofercie za pomocą PATCH /sale/product-offers/{offerId}
W ofercie są **cztery** zdjęcia, leci PATCH z tablica images zawierającą **dwa** zdjęcia, oferta się aktualizuje i są w niej nagle **trzy** zdjecia

trace-id: 662d562a6e8abfb5

**Comment by PrzemyslawLukanowski** [comment]
W ofercie uwzględniliśmy dwa Twoje zdjęcia plus automatycznie przypisaliśmy jedno z naszej bazy produktowej. W naszych danych produktu zawarte są dwa zdjęcia, jednak jedno z nich zostało rozpoznane jako duplikat Twojego obrazka, dlatego nie dodaliśmy go do oferty.

**Comment by dlis2010** [comment]
@PrzemyslawLukanowski 
Zgodnie z dokumentacja przy metodzie PATCH stosujecie zasadę wszystko albo nic. Przesyłam nowa tablice zdjęć, a dodają się automatycznie inne.

Podsumowując, nie ma możliwości wystawienia aukcji tylko ze swoimi zdjęciami za pomocą tej końcówki, gdy w produkcie są już jakieś przypisane. 

Nie ma też możliwości edycji takiej aukcji, aby przypisać tylko swoje zdjęcia. 

@PrzemyslawLukanowski Bardzo proszę o wskazanie rozwiazania, jak wystawić aukcję powiązana z produktem z własnymi zdjęciami?

Pozostaje tylko  możliwość wystawienia "starym" sposobem?

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem Twoje uwagi do zespołu odpowiedzialnego za ten endpoint. Na tę chwilę przez zasoby /sale/products-offers nie ma możliwości wystawienia/edycji oferty tylko ze swoimi zdjęciami. Jeśli jednak zdecydujemy się w tej kwestii wprowadzić zmiany, wrócę do Ciebie z informacją w tym wątku.

**Comment by dlis2010** [comment]
@PrzemyslawLukanowski 
Dziękuje za informację, postanowiliśmy potestować dalej bo coś nam nie dawało spokoju, tak jak myśleliśmy, jednak to bug.

wystawiamy aukcje trace-id (4704be5e7fccff48), przesyłamy dwa zdjęcia (AAA i BBB), automatycznie doklejają się dwa zdjęcia z produktu
![ss1](https://user-images.githubusercontent.com/36523118/111321632-6a1df100-8668-11eb-9a45-92065591c7b8.png)

następnie za pomocą PATCH przesyłam tablicę z dwoma zdjęciami (CCC i DDD) a w odpowiedzi dostaje:
![ss2](https://user-images.githubusercontent.com/36523118/111321775-8ae64680-8668-11eb-8d07-5b3bf4ea9274.png)

Nic z wcześniejszej wypowiedzi nie miało miejsca:
`W ofercie uwzględniliśmy dwa Twoje zdjęcia plus automatycznie przypisaliśmy jedno z naszej bazy produktowej. W naszych danych produktu zawarte są dwa zdjęcia, jednak jedno z nich zostało rozpoznane jako duplikat Twojego obrazka, dlatego nie dodaliśmy go do oferty.`
W ofercie nie dokleiło się zdjęcie z produktu, ale jedno poprzednie, bardzo proszę o ponowną weryfikację.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za ten przykład. Zweryfikuję go z zespołem i wrócę z odpowiedzia.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku dołączyliśmy zdjęcie "BBBB" do oferty, ponieważ znajdowało się w jej opisie w sekcji description. Jeżeli nie wysyłasz nam takiego zdjęcia, ale znajduje się ono w opisie oferty, to z automatu przyłączymy je do oferty. 
Jednocześnie chciałbym sprostować moją wcześniejszą informację:

> przez zasoby /sale/products-offers nie ma możliwości wystawienia/edycji oferty tylko ze swoimi zdjęciami

Przez PATCH możesz uwzględnić w ofercie tylko swoje zdjęcia. Warunkiem jest to, aby w sekcji description nie znajdywały się żadne inne.

**Comment by dlis2010** [comment]
świetnie, dziękuję za informację
