### ISSUE TITLE
Problem z łączeniem się z webapi

### ISSUE THREAD

**Issue by oosebossoo** [allegro/allegro-api#4286]
Występuje problem:

- [ ]  z metodą WebAPI
- [ ]  z logowaniem lub autoryzacją

Błąd:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl' : failed to load external entity "https://webapi.allegro.pl.allegrosandbox.pl/service.php?wsdl"

Opis:
Gdy próbuje połączyć się z danym kontem allegro wyświetla się wyżej wymieniony błąd. Zaznacze że w środowisky testowym jaki i produkcyjnym. Aplikacja jest zarejestrowana. ClientId jest poprawny.
Dziękuje za pomoc!

**Comment by PrzemyslawLukanowski** [comment]
Ostatnie metody WebAPI [wyłączyliśmy 26 października 2020](https://github.com/allegro/allegro-api/issues/3814). Aktualnie skorzystasz tylko z REST API.  Wszelkie niezbęne informacje znajdziesz na [naszej stronie](https://developer.allegro.pl/about/).
