### ISSUE TITLE
Procent ofert powiązanych z produktem od 1 kwietnia

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#4287]
Dzień dobry,

Od 1 kwietnia zwiększacie procent ofert powiązanych z produktem, głównie chodzi mi o kategorie Moda czy zmiany już są uwzględnione na sandboxie?
W odpowiedzi na https://api.allegro.pl.allegrosandbox.pl/sale/categories/76084 otrzymuje
`{
    "id": "76084",
    "name": "Spódnice i spódniczki",
    "parent": {
        "id": "76033"
    },
    "leaf": true,
    "options": {
        "variantsByColorPatternAllowed": true,
        "advertisement": false,
        "advertisementPriceOptional": false,
        "offersWithProductPublicationEnabled": false,
        "productCreationEnabled": false,
        "customParametersEnabled": true
    }
}`
Co się stanie w przypadku wznawianych automatycznie licytacji gdy nie będzie spełniony wymóg 10%? Czy takie oferty wznowią się automatycznie?

**Comment by PrzemyslawLukanowski** [comment]
Skierowałem prośbę do odpowiedniego działu, aby umożliwić tworzenie produktów i łączenie ofert z produktami w tym dziale na środowisku testowym. Wrócę z informacją, gdy udostępnimy tę funkcjonalność.
Gdy nie spełnisz wymogu 10%, ofertę wznowisz tylko, jeżeli wskażesz w niej produkt dostępny w Katalogu lub dodasz nowy produkt jej podstawie. Jeśli oferta nie będzie sproduktyzowana - zwrócimy błąd.

**Comment by pawelosajda** [comment]
Oferta wznawiana automatycznie przez allegro też się nie wznowi? Oferta z ustawionym polem republish

**Comment by PrzemyslawLukanowski** [comment]
Nie wznowi się, [tutaj ](https://allegro.pl/dla-sprzedajacych/od-1-kwietnia-zwiekszymy-procent-ofert-powiazanych-z-katalogiem-produktow-allegro-i-rozszerzymy-go-o-nowe-kategorie-lLRVK6eabHg)znajdziesz więcej szczegółów.

> Jeśli po 1 kwietnia procent Twoich ofert powiązanych z Katalogiem będzie mniejszy, niż wymagany w danym dziale:
> 
> - nowe i podobne oferty wystawisz dopiero, gdy wybierzesz produkt z Katalogu lub gdy dodasz go na podstawie swojej oferty. Tak samo będzie w przypadku, gdy zechcesz wznowić jakąś ofertę.
> - aktywne oferty edytujesz, nawet jeśli nie zostały powiązane z Katalogiem.

**Comment by PrzemyslawLukanowski** [comment]
@pawelosajda Uwzględniliśmy już zmiany na sandboxie w kat. Moda.

**Comment by pawelosajda** [comment]
Zauważyłem różnice pomiędzy live a sandbox w zasobie /sale/categories/78137/product-parameters. Czy parametr EAN będzie obowiązkowy w kategorii Moda?

**Comment by PrzemyslawLukanowski** [comment]
EAN nie jest wymagany, gdy tworzysz nowy produkt w tej kategorii (zgodnie z produkcją). Mogą występować róznice w parametrach pomiędzy tymi środowiskami - staramy się synchronizować ok. raz na kwartał.

**Comment by pawelosajda** [comment]
Na produkcji też będzie wymagany w kategorii Moda? Docelowo we wszystkich kategoriach?

**Comment by PrzemyslawLukanowski** [comment]
Miałem na myśli to, że środowisko testowe może być nieaktualne względem produkcji - czyli w drugą stronę.  Jeżeli chcesz sprawdzić, jakie parametry oznaczymy jako wymagane w najbliższym czasie, skorzystaj z [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/my_offers/#jak-sprawdzi%c4%87-przysz%c5%82e-zmiany-w-parametrach)
Tak, procent ofert powiązanych z produktem może się zwiększać przez automatyczne wiązanie ofert po naszej stronie.

**Comment by pawelosajda** [comment]
@PrzemyslawLukanowski Jaki jest warunek by allegro automatycznie połączyło ofertę z produktem? Czy wszystkie atrybuty describesProduct: true muszą mieć wartość?

**Comment by PrzemyslawLukanowski** [comment]
Automatyczne łączenie oferty z produktem nie jest bezpośrednio powiązane z polami, które są dostępne w API. Taka możliwość musi być przez nas udostępniona  w danej kategorii, oferta musi mieć uzupełniony numer GTIN, a kategoria produktu i oferty musi być zgodna.
