### ISSUE TITLE
Custom values are not enabled in the parameter: parameterId=129970

### ISSUE THREAD

**Issue by adamTynski** [allegro/allegro-api#4289]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Jakiś czas temu wystawiłem aukcję w kategorii 54090. Aukcja zakończyła się ze względu na zerowy stan magazynowy. Teraz przy próbie wznowienia aukcji dostaję komunikat "Custom values are not enabled in the parameter: parameterId=129970". Po krótkim dochodzeniu zauważyłem, że w ofercie, którą próbuję wznowić jeden z parametrów ma wartość:
{"id":"129970","valuesIds":["129970_18"],"values":["Yellow Tipi"],"rangeValue":null}
zaś endpoint
https://api.allegro.pl/sale/categories/54090/parameters
dla parametru o identyfikatorze 129970 zwraca listę słownikową, która nie zawiera marki Yellow Tipi.

W związku z tym proszę o:
1) albo przywrócenie możliwości ustawienia customowej marki w kategorii 54090 bądź
2) dodanie parametru Yellow Tipi do listy słownikowej parametru 129970

Dziękuję

**Comment by Lukasz-Zurek** [comment]
Zweryfikuję zgłoszenie i wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
Wartość _Yellow Tipi_ została dodana do słownika.

**Comment by adamTynski** [comment]
Dziękuję
