### ISSUE TITLE
Informacje o sprzedawcy 

### ISSUE THREAD

**Issue by apiallegro** [allegro/allegro-api#429]
Cześć,
czy istnieje metoda pozwalająca na pobranie informacji dotyczących sprzedawcy, tzw. zakładka "o sprzedającym" tj. numery telefonów / adresy email / adresy firmy?

Metoda może być zarówno soapowa lub restowa.

**Comment by MartaNowaczyk** [comment]
Cześć, 
tak, ale tylko gdy jesteś stroną transakcji. Dane sprzedającego możesz pobrać za pomocą metody WebAPI [doGetPostBuyData](https://allegro.pl/webapi/documentation.php/show/id,89#method-input).

**Comment by Qhoros** [comment]
Nie o to mi chodzi, ale dzięki za odpowiedź. Zamykam.

**Comment by apiallegro** [comment]
Szkoda, że nie można uzyskać informacji o dowolnym sprzedawcy. Niemniej dzięki za informacje. Zamykam.
