### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by gderon** [allegro/allegro-api#4290]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz opisać, czego dotyczy problem?
