### ISSUE TITLE
Zwroty

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#4292]
Kiedy w API pojawi się możliwość pobierania zwrotów wraz z listami przewozowymi przesyłek zwrotnych?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie mamy konkretnego terminu, dlatego nie mogę podać takiej informacji. W momencie opublikowania zasobów udostępnimy odpowiedni komunikat na naszej stronie.

**Comment by arolznov** [comment]
Wobec tego czy jest inna droga aby zautomatyzować proces pobierania zwrotów z Allegro?

**Comment by hahyes** [comment]
> Wobec tego czy jest inna droga aby zautomatyzować proces pobierania zwrotów z Allegro?

Możesz zautomatyzować proces tworzenia wniosków o zwrot prowizji za sprzedaż. W sumie nic więcej API na ten moment nie daje w tym zakresie.

**Comment by PrzemyslawLukanowski** [comment]
> Wobec tego czy jest inna droga aby zautomatyzować proces pobierania zwrotów z Allegro?

Na ten moment wszelkie funkcjonalności związane ze zwrotami towarów dostępne są jedynie przez Moje Allegro

**Comment by arolznov** [comment]
> > Wobec tego czy jest inna droga aby zautomatyzować proces pobierania zwrotów z Allegro?
> 
> Możesz zautomatyzować proces tworzenia wniosków o zwrot prowizji za sprzedaż. W sumie nic więcej API na ten moment nie daje w tym zakresie.

Chodzi o zwroty towarów przez kupujących.

**Comment by cieplik206** [comment]
Czy coś się zmieniło w tej kwestii ?
