### ISSUE TITLE
Problem z wysyłką zdjęć

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4293]
Otrzymujemy poniższy error. Podczas gdy wejdziemy na link ze zdjęciem to wszystko jest ok.

`[{"code":"DownloadError","message":"Downloading image from URL  'http://www.bartek-buty.pl/foto/produkty/oryg/gal_191339_img_06412.jpg'  failed. Server returned the following HTTP status code: 500  INTERNAL_SERVER_ERROR and response body: 'DNS resolve  timeout'.","details":null,"path":null,"userMessage":"Nie mou017cna  pobrau0107 zdju0119cia z adresu  'http://www.bartek-buty.pl/foto/produkty/oryg/gal_191339_img_06412.jpg'.  Serwer ze zdju0119ciem zwru00f3ciu0142 kod HTTP: 500  INTERNAL_SERVER_ERROR z bu0142u0119dem: 'DNS resolve timeout'."}]`

**Comment by Lukasz-Zurek** [comment]
Obecnie zdjęcie jest już zwracane w sposób prawidłowy.
