### ISSUE TITLE
Różne odpowiedzi w zależności od użytego tokenu

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4294]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Miałem dzisiaj problem z zasobem `/sale/categories/76043/parameters` na środowisku testowym. Otóż dla różnych tokenów otrzymywałem 2 różne odpowiedzi. Raz zostawała zwracana wartość z parametrem "3786_85" w słowniku, a raz bez. W zależności od tego, którego tokena używałem. Teraz żaden token nie zwraca mi tej wartości. Ta wartość w tym przypadku to "ambiguousValueId" dla parametru "Marka".

**Comment by Onixarts** [comment]
Ja taki problem spotkałem na sandboxie nawet na jednym tokenie. Raz była zwracana marka - Inna, raz nie :).

**Comment by Lukasz-Zurek** [comment]
Przekazałem ten problem do weryfikacji. Wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
Poprawiliśmy już błąd. Przepraszamy za utrudnienia.
