### ISSUE TITLE
Pobieranie danych 

### ISSUE THREAD

**Issue by ZAXERPL** [allegro/allegro-api#4295]
Witam,

Czy przez AllegroAPI można pobierać z listy ofert tej po zalogowaniu takie dane jak: wizyty, sprzedaż, wyróżnienie, obserwacje? 

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Tak. Takie dane jak wizyty, liczbę osób obserwujących oraz sprzedaż, uzyskasz, korzystając z zasobu: [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Odpowiednio są to następujące pola: `"visitsCount"`, `"watchersCount"`, które zwracane są w `"stats"`, natomiast wartość pola `"sold"` zwracana jest w `"stock"`.

Informacje dotyczące wyróżnienia, jak i pozostałych opcji promowania pobierzesz korzystając z zasobu: [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Pole odpowiedzialne za opcje promowania to `"promotion"`, natomiast “wyróżnienie” to `"emphasized"`.

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).
