### ISSUE TITLE
[INVALID JSON] - dla konkretnej oferty

### ISSUE THREAD

**Issue by goliatek86** [allegro/allegro-api#4296]
Witam
Nie mogę wystawić oferty dostaję błąd INVALID JSON do tej pory nie mieliśmy problemów u klientów aukcje wystawiają się prawidłowo. Sprawdzałem JSON w vaildatora i nie ma błedów, wiec nie wiem czego sie doszukiwać tutaj
 <pre>
<code>{
  "name": "TCL Telewizor LED 50 cali 50P615",
  "category": {
    "id": "257732"
  },
  "delivery": {
    "shippingRates": {
      "id": "55396ecf-2725-4230-b8ce-4eaf1d33f3c4"
    },
    "handlingTime": "P3D"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "1792.5",
      "currency": "PLN"
    }
  },
  "external": {
    "id": "26385"
  },
  "stock": {
    "available": "23.00",
    "unit": "UNIT"
  },
  "location": {
    "city": "Gdynia",
    "countryCode": "PL",
    "postCode": "81-509",
    "province": "POMORSKIE"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p><b>Gwarancja<\/b>: 24 msc.<\/p><p><b>Model<\/b>: 50P615<\/p><p><b>Opis:<\/b><\/p><ul> <li><b>4K HDR<\/b> doskona\u0142y kontrast, \u017cywe i naturalne kolory oraz najdrobniejsze szczeg\u00f3\u0142y<\/li> <li><b>Micro Dimming PRO<\/b> dla lepszego kontrastu<\/li> <li><b>Dolby Audio<\/b> zapewnia g\u0142\u0119boki, czysty i pot\u0119\u017cny d\u017awi\u0119k g\u0142o\u015bnik\u00f3w telewizora<\/li> <li><b>Android TV<\/b> Rozrywka dopasowana do Twoich potrzeb<\/li> <li><b>Asystent Google<\/b> Poznaj swojego Asystenta Google. Zadawaj mu pytania. Wydawaj mu polecenia.<\/li> <li><b>NETFLIX<\/b> teraz dost\u0119pny w jako\u015bci 4K UHD HDR<\/li> <li><b>YouTube<\/b> teraz dost\u0119pny w jako\u015bci 4K UHD HDR<\/li> <li><b>Alexa <\/b>Niech Tw\u00f3j g\u0142os kontroluje Tw\u00f3j \u015bwiat<\/li><\/ul><p><b>System d\u017awi\u0119ku: <\/b>Dolby Audio<\/p>"
          },
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/11e04b\/e8dc525943c1a14689c18f4f7d8e"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/111841\/2d7f6a4e48819f1020a3646c4a4b"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/11e4ab\/4e9dd0894b30922adcf1e07089c3"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https:\/\/a.allegroimg.com\/original\/11d457\/ad8658f042ec9c8790ce2f253a09"
          }
        ]
      }
    ]
  },
  "images": [
    {
      "url": "https:\/\/a.allegroimg.com\/original\/11e04b\/e8dc525943c1a14689c18f4f7d8e"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/111841\/2d7f6a4e48819f1020a3646c4a4b"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/11e4ab\/4e9dd0894b30922adcf1e07089c3"
    },
    {
      "url": "https:\/\/a.allegroimg.com\/original\/11d457\/ad8658f042ec9c8790ce2f253a09"
    }
  ],
  "parameters": [
    {
      "id": 11323,
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": 211398,
      "valuesIds": [
        "211398_249518"
      ]
    },
    {
      "id": 217585,
      "values": [
        "50P615"
      ]
    },
    {
      "id": 224017,
      "values": [
        "50P615"
      ]
    },
    {
      "id": 211486,
      "valuesIds": [
        "211486_250138"
      ]
    },
    {
      "id": 206002,
      "valuesIds": [
        "206002_225578"
      ]
    },
    {
      "id": 194,
      "values": [
        "50"
      ]
    },
    {
      "id": 206586,
      "values": [
        "50"
      ]
    },
    {
      "id": 129294,
      "valuesIds": [
        "129294_1"
      ]
    },
    {
      "id": 211606,
      "valuesIds": [
        "211606_250514"
      ]
    },
    {
      "id": 211678,
      "valuesIds": [
        "211678_250634"
      ]
    },
    {
      "id": 127632,
      "valuesIds": [
        "127632_2"
      ]
    },
    {
      "id": 129880,
      "valuesIds": [
        "129880_1"
      ]
    },
    {
      "id": 201605,
      "valuesIds": [
        "201605_1",
        "201605_64"
      ]
    },
    {
      "id": 1440,
      "valuesIds": [
        "1440_524288",
        "1440_16",
        "1440_16384",
        "1440_128",
        "1440_4096"
      ]
    },
    {
      "id": 201609,
      "values": [
        "3"
      ]
    },
    {
      "id": 201613,
      "values": [
        "2"
      ]
    },
    {
      "id": 129914,
      "valuesIds": [
        "129914_8",
        "129914_128",
        "129914_512",
        "129914_1024"
      ]
    },
    {
      "id": 211594,
      "values": [
        "16"
      ]
    },
    {
      "id": 211586,
      "valuesIds": [
        "211586_250510"
      ]
    },
    {
      "id": 247945,
      "valuesIds": [
        "247945_838297"
      ]
    },
    {
      "id": 247951,
      "valuesIds": [
        "247951_838331"
      ]
    },
    {
      "id": 129295,
      "valuesIds": [
        "129295_2"
      ]
    },
    {
      "id": 201661,
      "valuesIds": [
        "201661_256"
      ]
    },
    {
      "id": 201665,
      "values": [
        "1122"
      ]
    },
    {
      "id": 201669,
      "values": [
        "710"
      ]
    },
    {
      "id": 201673,
      "values": [
        "265"
      ]
    },
    {
      "id": 201677,
      "values": [
        "10"
      ]
    },
    {
      "id": 201681,
      "values": [
        "1122"
      ]
    },
    {
      "id": 201685,
      "values": [
        "656"
      ]
    },
    {
      "id": 204817,
      "values": [
        "10"
      ]
    },
    {
      "id": 225693,
      "values": [
        "5901292514426"
      ]
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "29cd9952-69e1-4223-b634-31e1c1347656"
    },
    "returnPolicy": {
      "id": "2a56b928-553f-400b-afa7-05ac2df580e7"
    },
    "warranty": {
      "id": "80442572-7b53-46d9-bf95-a1fee37d2293"
    }
  },
  "publication": {
    "duration": "P3D"
  }
}</code>
</pre>

**Comment by Lukasz-Zurek** [comment]
Wartość w polu: ` "stock": {"available": "23.00",`powinieneś wprowadzić bez `""`. Ilość sztuk uzupełniaj natomiast bez zer.

Powinno to wyglądać w następujący sposób: `"stock": {"available": 23,`
