### ISSUE TITLE
Problem z filtrowaniem po "productizationRequired"

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4297]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

cześć, mamy problem z pobraniem ofert, które wymagają produktyzacji:
https://api.allegro.pl.allegrosandbox.pl/sale/offers?publication.status=ACTIVE,ACTIVATING,ENDED&sellingMode.format=BUY_NOW&limit=50&offset=0&productizationRequired=1

dostajemy:

```
code] => BadRequestException
[message] => Invalid "productizationRequired" field value.
```

trace-id: `2a2750874b35a3bc`

czy to coś po naszej stronie? 🤔

**Comment by kpodemski** [comment]
Odpowiedź: po naszej, musimy przekazać `true` nie `1` 🤕

**Comment by Lukasz-Zurek** [comment]
Jeśli chcesz wyszukać oferty, które nie posiadają przypisanego produktu, a muszą spełnić wymaganie powiązania z produktem, skorzystaj dodatkowo z filtru: `product.id.empty=true`

Za pomocą parametru `productizationRequired` wyfiltrujesz oferty należące do kategorii, w których produktyzacja jest obowiązkowa. Jeśli zatem chcesz wyszukać oferty, które nie posiadają przypisanego produktu, a muszą spełnić wymaganie powiązania z produktem - skorzystaj z obu powyższych filtrów.
