### ISSUE TITLE
Problem z pobieraniem zasobów

### ISSUE THREAD

**Issue by szpiotr32** [allegro/allegro-api#4298]
Witam mam problem z pobraniem zasobów z konta np oferty. Stworzyłem aplikacje api, poprzez autoryzacje dodalem aplikacje do powiązanych jednak mogę pobierac tylko te rzeczy, które mogłem bez autoryzacji.
obiekt tokena jaki dostaje:
  public 'access_token' => string '{tu token}'... (length=1136)
  public 'token_type' => string 'bearer' (length=6)
  public 'expires_in' => int 43199
  public 'scope' => string 'allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read' (length=395)
  public 'allegro_api' => boolean true
  public 'jti' => string 'f06bb7e8-3cac-4b9a-8889-424f6878786d' (length=36)

Podczas próby pobrania /sale/offers 
zwraca 403.

**Comment by Lukasz-Zurek** [comment]
Upewnij się, że nie korzystasz z autoryzacji typu **client_credentials**, która nie posiada kontekstu użytkownika. W naszej dokumentacji znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device flow](https://developer.allegro.pl/auth/#DeviceFlow)),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

Zdekoduj swój token i sprawdź czy jest tam "user_name".

**Comment by szpiotr32** [comment]
Korzystałem podczas autoryzacji z grant_type=client_credentials. Dziekuje za pomoc.
