### ISSUE TITLE
Identyfikator kategorii danej oferty

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#4299]
Buduję aplikację, która pomoże mi obliczyć koszty prowizji związane ze sprzedażą na Allegro. Parametrami aplikacji będzie numer oferty oraz cena sprzedaży. Chcę wykorzystać zasób "/pricing/fee-preview". Ten zasób potrzebuje identyfikatora kategorii. W jaki sposób wyciągnąc ten identyfikator kategorii znając jedynie numer oferty?

Edit: Międzyczasie udało mi się znaleźć zasób, który wyciąga informacje na temat danej oferty. Jest to "/sale/offers/{offerId}". Niestety działa tylko dla ofert, które są użytkownika zalogowanego. Czy da sprawdzić oferty innego użytkownika?

**Comment by MartaNowaczyk** [comment]
Tak jak piszesz, po numerze oferty możesz uzyskać id kategorii tylko jeśli jesteś zautoryzowany jako sprzedawca.

**Comment by hahyes** [comment]
> Czy da sprawdzić oferty innego użytkownika?

Rozszerzę wypowiedź Pani Marty dla jasności. Otóż Allegro zależy na całkowitej ochronie danych sprzedaży innych sprzedawców. Powód realny czy nie, jednak Allegro w swoich zasobach tych danych teraz bardzo ostro chroni. REST API niestety nie zapewni ci potrzebnych danych. Można by scrappować portal, ale Regulamin Allegro nie tylko uwzględnia to i tego zakazuje, to zabezpieczenia anty-botowe są na tyle uparte, że potrafią zablokować każdego pod danym IP, jeżeli mają podejrzenia.

**Comment by maniootek** [comment]
Czy w ramach tokena konta X mogę sprawdzać informacje na temat oferty z konta Y gdzie konto X i Y to ten sam NIP?

**Comment by MartaNowaczyk** [comment]
Nie możesz, wspólny NIP nie ma tu nic do rzeczy.

**Comment by maniootek** [comment]
Tylko że właśnie odpytałem zasób "/sale/offers/{offerId}" tokenem konta X gdzie w pole {offerId} wpisałem numer oferty z konta Y i normalnie dostałem odpowiedź.

**Comment by MartaNowaczyk** [comment]
Widocznie masz [powiązane](https://allegro.pl/moje-allegro/moje-konto/powiazane-konta) konta, dzięki czemu możesz pobrać dane takiej oferty.

**Comment by maniootek** [comment]
Tak zgadza się. Czyli wszystko się wyjaśniło.

**Comment by maniootek** [comment]
W ramach powiązanych kont jak sprawdzić po numerze oferty do jakiego użytkownika (nick) jest przypisana? W zasobie "/sale/offers/{offerId}" nie znalazłem takiej informacji

**Comment by MartaNowaczyk** [comment]
Nie sprawdzisz tego. Takie informacje musisz mieć zebrane po swojej stronie.
