### ISSUE TITLE
Czy coś się zmieniło 3 marca (sobota) ok 15:00?

### ISSUE THREAD

**Issue by jedi-pl** [allegro/allegro-api#43]
Wygląda na to, że API Allegro działa dużo wolniej od tego czasu

**Comment by KrzysztofLukanowski** [comment]
Nie wprowadziliśmy żadnych zmian w ten weekend. Podaj proszę więcej szczegółów, w jakich konkretnie metodach zauważyłeś dłuższy czas odpowiedzi? Na jakim koncie?

**Comment by jedi-pl** [comment]
Namierzyłem. Dokładnie o 15:00 zawisły połaczenia i polecenia czytania z socketa. Cieżko określić dlaczego - może problem sieciowy u nas / u was / po drodze. Zamykamy.
