### ISSUE TITLE
Api allegro problem

### ISSUE THREAD

**Issue by abs335345** [allegro/allegro-api#4300]
Witam mam pytanie jak mam polaczyc API do allegro wyskakuje mi bład w momencie pobrania tokenu, dodałem zalacznik, prosze o pomoc jak mam to przypisac. pozdrawiam
<img width="1113" alt="Api allegro" src="https://user-images.githubusercontent.com/81101559/111915630-24e62e80-8a6f-11eb-88d1-f0be433a7de8.PNG">

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że przekazujesz błędny adres przekierowania redirect_uri. Powinieneś użyć dokładnie takiego, jaki był podany podczas rejestracji aplikacji. Możesz to sprawdzić w [zarządzaniu aplikacjami](https://apps.developer.allegro.pl/).

**Comment by abs335345** [comment]
Dziękuje za pomoc, już wszystko działa :-)

**Comment by Onixarts** [comment]
A tak przy okazji, przydało by się aby urle autoryzacji nie brały pod uwagę portów efemerycznych na localhoście. Pisałem już kiedyś o tym, że z góry założone porty mogą być na komputerze użytkownika aktualnie w użyciu i autoryzacji nie uda się przeprowadzić.

**Comment by PrzemyslawLukanowski** [comment]
@Onixarts Mamy to na naszej liście sugestii. Poinformujemy, jeśli zdecydujemy się wdrożyć zmiany.

**Comment by PrzemyslawLukanowski** [comment]
@Onixarts Wdrożyliśmy odpowiednie zmiany po naszej stronie.
