### ISSUE TITLE
Błąd "Produkt z takimi danymi już istnieje" powinien zwracać identyfikator produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4301]
:bulb: **Sugestia**

Witam,

mam pewną sugestię dotyczącą zasobu **POST /sale/product-proposals**. W przypadku tworzenia produktu i wystąpienia konfliktu o treści "Produkt z takimi danymi już istnieje", w odpowiedzi nie otrzymuje się żadnych danych pozwalających szybko znaleźć i wykorzystać ten produkt, choćby samego GUID. Uważam to za spore utrudnienie. 

Próbując zautomatyzować przeniesienie sporej ilości posiadanych przedmiotów do katalogu produktów Allegro, nie mogę skutecznie móc przejść na oferty produktowe. Jak pisałem też szybciej w innej sugestii, wyszukiwarka nie pozwoli mi bez odpowiedniej frazy znaleźć z tymi danymi żadnego produktu. Gdybym miał GUID produktu, nie byłoby praktycznie dla mnie żadnego problemu. 

Uważam też, że ułatwiłoby to życie innym twórcom aplikacji, w tym webowych. GUID produktu pozwoliłby szybko wyświetlić istniejący produkt, a osoba dodająca produkt mogłaby dane zweryfikować i stwierdzić, czy produkt ten pasuje do posiadanego.

Jeżeli jest jednak jakaś możliwość szybkiego znalezienia duplikatu produktu, byłbym wdzięczny za jakąś radę. W przeciwnym razie pozostawiam to jako silną sugestię, ponieważ mam wrażenie, że te zasoby lekko kuleją pod względem użyteczności.

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli otrzymasz komunikat "Produkt z takimi danymi istnieje", adres istniejącego produktu znadziesz w odpowiedzi w nagłówku **Location**.

**Comment by hahyes** [comment]
> Jeśli otrzymasz komunikat "Produkt z takimi danymi istnieje", adres istniejącego produktu znadziesz w odpowiedzi w nagłówku **Location**.

Dziękuję.
