### ISSUE TITLE
Błąd strony

### ISSUE THREAD

**Issue by alektest** [allegro/allegro-api#4302]
Dzień dobry, niestety nie działa mi strona https://allegro.pl.allegrosandbox.pl/. Proszę o podesłanie linka, który umożliwi mi rejestrację.

**Comment by PrzemyslawLukanowski** [comment]
Strona powinna działać już prawidłowo, [link do rejestracji konta](https://allegro.pl.allegrosandbox.pl/rejestracja?origin_url=%2F%3Flogout%3D1).

**Comment by alektest** [comment]
Dziękuję, po jakim czasie powinnam otrzymać maila z linkiem aktywacyjnym?

**Comment by PrzemyslawLukanowski** [comment]
Maksymalnie kilka minut po rejestracji. Sprawdź także, czy nie trafiła do folderu "Spam".

**Comment by alektest** [comment]
Niestety wiadomość nie dociera, co mogę zrobić w tej sytuacji?

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę maila, na którego zarejestrowałeś konto.

**Comment by alektest** [comment]
***@***.***

_____________________
Pozdrawiam / Kind regards
Aleksandra Kmieciak
Specjalista ds. e-commerce
+48 790 400 852

***@***.***

Office address:
ul. Obornicka 7, 62-002 Jelonek,
Telephone: +48 61 306 77 72
[cid:semilac_51622102-9f42-4b8f-bfec-abc4e632add7.jpg]<https://semilac.pl/>[cid:hi_hybrid_66312077-ea9d-4de4-9706-0d3e69e01cdc.jpg]<https://hihybrid.pl/>
Nesperta – właściciel marki Semilac. Nesperta sp. z o.o., ul. Jugosłowiańska 43, 60-149 Poznań, Polska. KRS: 0000463701 | NIP: 7792413878 | REGON: 302436962 | BDO: 000111680. Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego, kapitał zakładowy: 100 000.00 zł

**Comment by PrzemyslawLukanowski** [comment]
jeśli nie możesz umieścić adresu na forum, skorzystaj z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą wątku #4302 na GitHubie.

**Comment by PrzemyslawLukanowski** [comment]
W naszych logach znalazłem informację, że dwukrotnie wysyłaliśmy link aktywacyjny na adres ale...@....com, nie wysyłaliśmy wiadomości na adres, który podałaś w formularzu kontaktowym. Wysyłka maili nastąpiła o 11:55 i 12:09, nadawcą jest no-reply@allegrosandbox.pl, a tytuł maila to "Message from WebAPI Sandbox environment" . Upewnij się, że Twój program do obsługi poczty nie blokuje wiadomości, które zawierają załącznik w formacie .eml.

**Comment by alektest** [comment]
Sprawdza została skonsultowana z działem IT, program nie blokuje plików. Ponownie próbowałam dokonać rejestracji, jednak link nadal nie dociera.


_____________________
Pozdrawiam / Kind regards
Aleksandra Kmieciak
Specjalista ds. e-commerce
+48 790 400 852

***@***.***

Office address:
ul. Obornicka 7, 62-002 Jelonek,
Telephone: +48 61 306 77 72
[cid:semilac_51622102-9f42-4b8f-bfec-abc4e632add7.jpg]<https://semilac.pl/>[cid:hi_hybrid_66312077-ea9d-4de4-9706-0d3e69e01cdc.jpg]<https://hihybrid.pl/>
Nesperta – właściciel marki Semilac. Nesperta sp. z o.o., ul. Jugosłowiańska 43, 60-149 Poznań, Polska. KRS: 0000463701 | NIP: 7792413878 | REGON: 302436962 | BDO: 000111680. Sąd Rejonowy Poznań - Nowe Miasto i Wilda w Poznaniu, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego, kapitał zakładowy: 100 000.00 zł

**Comment by PrzemyslawLukanowski** [comment]
Tak, widzę w naszych logach, że prawidłowo wysłaliśmy wiadomość z linkiem o 15:35. Niestety nie znamy powodu, przez który mail jest blokowany po Twojej stronie. Sugeruję, abyś spróbowała zarejestrować konto na adres mailowy z innej domeny (następnie, po udanej aktywacji, będziesz mogła w opcjach zmienić go na właściwy).
