### ISSUE TITLE
Kalkulator opłat online vs api

### ISSUE THREAD

**Issue by maniootek** [allegro/allegro-api#4304]
Wg kalkulatora dostępnego pod adresem:
https://allegro.pl/pomoc/dla-sprzedajacych/kalkulator-oplat#
dla kategorii:
Motoryzacja - Części samochodowe - Układ elektryczny, zapłon - Materiały instalacyjne - Kostki, złączki
ustawiona Cena sprzedaży: 5,90
Wynik:
Prowizja od sprzedaży 0,54 zł
Prowizja od sprzedaży oferty wyróżnionej 0,32 zł

Wynik po API:
Prowizja od sprzedaży 0,54 zł
Prowizja od sprzedaży oferty wyróżnionej 0,4 zł

> {"quotes":[{"type":"listingFee","name":"Opłata za wystawienie","fee":{"amount":"0.1","currency":"PLN"},"cycleDuration":"PT240H"},{"type":"distinctionFee","name":"Opłata za wyróżnienie","fee":{"amount":"19","currency":"PLN"},"cycleDuration":"PT240H"}],"commissions":[{"type":"commissionFee","name":"Prowizja od sprzedaży","fee":{"amount":"0.54","currency":"PLN"}},{"type":"commissionFeatureFee","name":"Prowizja od sprzedaży oferty wyróżnionej","fee":{"amount":"0.4","currency":"PLN"}}]}

Skąd te różnice?

Edit:
Tak samo dla kategorii 18936 (Motoryzacja - Chemia - Płyny eksploatacyjne - Płyny do spryskiwaczy)
Cena sprzedaży 19,99zł
Kalkulator online = prowizja 1,60zł + 0,96zł
API = 1,80zł + 1,35zł

Request (POST):

>  {"offer":{"category": "id":"18936"},"duration":"PT72H","type":"shop","quantity":1,"soldQuantity":1,"unitPrice":19.99,"emphasized":true}}

Result:

> {"quotes":[{"type":"listingFee","name":"Opłata za wystawienie","fee":{"amount":"0","currency":"PLN"},"cycleDuration":"PT240H"},{"type":"distinctionFee","name":"Opłata za wyróżnienie","fee":{"amount":"19","currency":"PLN"},"cycleDuration":"PT240H"}],"commissions":[{"type":"commissionFee","name":"Prowizja od sprzedaży","fee":{"amount":"1.8","currency":"PLN"}},{"type":"commissionFeatureFee","name":"Prowizja od sprzedaży oferty wyróżnionej","fee":{"amount":"1.35","currency":"PLN"}}]}

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć Twojego błędu. Na stronie internetowej otrzymuję takie same wyniki jak w API. Jeśli cały czas masz problem z działaniem kalkulatora online, zgłoś go proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
![Screenshot_25](https://user-images.githubusercontent.com/51473661/111987074-06377480-8b0f-11eb-86e6-7d793f7765b2.png)

**Comment by maniootek** [comment]
![screencapture-allegro-pl-pomoc-dla-sprzedajacych-kalkulator-oplat-2021-03-22-13_07_34](https://user-images.githubusercontent.com/45625552/111987575-adb4a700-8b0f-11eb-8b3b-f047b4087f29.png)

**Comment by PrzemyslawLukanowski** [comment]
Różnica wynika z rodzaju konta - Twoje wyniki dotyczą konta prywatnego, moje firmowego.

**Comment by maniootek** [comment]
Dziękuję za wyjaśnienie. Fajnie gdyby była taka informacja w kalkulatorze
