### ISSUE TITLE
Jakie zdjęcia są przyjmowane dla produktu? Czy istnieją jakieś szczególne kryteria poza wymogami przy uploadzie?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4305]
Witam,

pytanie jest poniekąd powiązane z problemem generowania produktów na podstawie ofert na portalu. W dużym skrócie, powstałe na portalu produkty mają tylko połowę zdjęć, a na dodatek na miniaturkę wyznaczane było zdjęcie z tabelą rozmiarów, co produkty czyni bezużytecznymi do wystawiania. Do parametrów już zaglądać nie chciałem...

W związku z tym pytam, czy mogę oczekiwać podobnych jak nie takich samych zachowań w REST API? Czy jeżeli podam w danej kolejności zdjęcia, to w takiej kolejności zostaną one dodane do produktu? Czy ilość zdjęć będzie taka sama po dodaniu, czy pójdzie selekcja na nieznanych warunkach, która spowoduje jaki bajzel? Jeśli tak, dlaczego tak jest? Z jakiego powodu tworzenie produktów zachowuje się w taki nieprzewidywalny sposób?

Liczę na odpowiedź i pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Zasady dla zdjęć w galerii znajdziesz [w tym artykule](https://allegro.pl/dla-sprzedajacych/zasady-dla-zdjec-w-galerii-i-w-opisie-YLlAAa2oXf7). Maksymalnie możesz dodać ich 16. Zdjęcia w produkcie dodajemy w takiej samej kolejności, w jakiej wprowadziłeś w sekcji "images".

**Comment by PrzemyslawLukanowski** [comment]
Jeśli zauważysz niepożądane zachowanie w API, napisz proszę informację w tym wątku.
