### ISSUE TITLE
Wysyłanie maili do userów allegro (@allegromail.pl)

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4306]
Czy można wysyłać maile do klientów (@allegromail.pl), którzy złożyli zamówienie na Allegro ?
Chodzi o to aby im wysłać info, że np. zwrot dokonany przez nich doszedł do sklepu itp.
Jeśli jest to możliwe i ni jest to blokowane to jakie są restrykcje co do treści takich maili ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz wysyłać maile na te adresy. Co do restrykcji w treści - ponieważ nie jest to temat związany z API, skontaktuj się proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
