### ISSUE TITLE
Informacje o zwrotach - Rest API

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4307]
W jaki sposób można pobrać poprzez API informacje o zwrotach znajdujących się tutaj https://allegro.pl/moje-allegro/sprzedaz/zwroty ?

**Comment by PrzemyslawLukanowski** [comment]
Spójrz proszę na wątek #4292 - pojawiło się tam takie samo pytanie. 

> Na tę chwilę nie mamy konkretnego terminu, dlatego nie mogę podać takiej informacji. W momencie udostępnienia zasobów opublikujemy odpowiedni komunikat na naszej stronie.
