### ISSUE TITLE
Pole 215858 pozwala na dodanie jednej wartości, a powinno na wiele

### ISSUE THREAD

**Issue by ospiotr** [allegro/allegro-api#4308]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym

:beetle: **Opis**

Hej, problem stwierdziłem przy kategorii o ID `255103`. Nazwa kategorii to` Motoryzacja - Części samochodowe - Oświetlenie - Lampy przednie i elementy - Przetwornice`.

Pole o ID `215858` jest prezentowane w REST API jako pole zawierające jedną wartość o maksymalnej długości 25 znaków:

```
        {

            "id": "215858",
            "name": "Numer katalogowy części",
            "type": "string",
            "required": true,
            "requiredForProduct": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": "11323",
                "requiredDependsOnValueIds": [
                    "11323_1"
                ],
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "restrictions": {
                "minLength": 1,
                "maxLength": 25,
                "allowedNumberOfValues": 1
            }
        },
```

Tymczasem w panelu Allegro można do tego pola dodać wiele wartości:
https://i.imgur.com/qaBRVQw.png

Dlaczego w API to pole występuje jako pole z jedną wartością? Potrzebowałbym pobierać i wysyłać do tego pola różne numery katalogowe przy pomocy REST API. Tak jak mogę to robić w panelu Allegro.

**Comment by MartaNowaczyk** [comment]
Hej, pole o którym wspominasz ID 215858 "Numer katalogowy części", w formularzu ma taką samą długość jak w REST API - 25 znaków i w obu miejscach wartość dla tego pola może być tylko jedna.  
Może masz na myśli inne pola:
- ID 215941 "Numery katalogowe zamienników" 45 znaków,
- ID 227345 "Numer katalogowy oryginału" 40 znaków. 
Dla obu wymienionych parametrów masz możliwość wprowadzenia 20 wartości.

**Comment by ospiotr** [comment]
@MartaNowaczyk 

Dziękuję za odpowiedź.
