### ISSUE TITLE
Pobranie listy aukcji ze starymi opisami.

### ISSUE THREAD

**Issue by mwiercioch** [allegro/allegro-api#431]
Czy istnieje opcja pobrania takiej listy z web api albo rest api. Jeśli tak, to proszę o jakieś wskazówki jak to zrobić

**Comment by mwiercioch** [comment]
Metoda doShowItemInfoExt odnosi się do pojedynczej aukcji. Ja natomiast aukcji mam tysiące i chciałbym wyciągnąć listę tych ze starym opisem. W panelu allegro na liście produktów można przeglądać takie aukcje dzięki parametrowi hasStandardizedDescription=false
Ten parametr zdaje się nie działać prawidłowo doGetItemsList

**Comment by kfijalko** [comment]
W którymś wpisie była informacja, że trzeba pobierac pojedyńczo. WebApi juz nie będzie modyfikowane a w nowym rest jest założenie, że wszystkie oferty maja nowy opis.

**Comment by MartaNowaczyk** [comment]
W Rest API nie ma takiej możliwości, ale możesz spróbować metodą [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,52#method-input), gdzie możesz wrzucić tablicę 25-elementową.
