### ISSUE TITLE
Kampania Allegro Ceny - api nie zwraca oryginalnej wartości ceny

### ISSUE THREAD

**Issue by array3** [allegro/allegro-api#4310]
Jakiś czas temu czytałem tutaj na githubie, że ponoć zmiana ceny oferty w ramach kampanii Allegro Ceny nie jest widoczna dla zewnętrznych aplikacji przy pobieraniu danych za pomocą zasobu: 
`GET /sale/offers/{offerId}`

dotyczy części:
`"sellingMode": {
        "format": "BUY_NOW",
        "minimalPrice": null,
        "netPrice": {
            "amount": "121.14",
            "currency": "PLN"
        },
        "price": {
            "amount": "149",
            "currency": "PLN"
        },
        "startingPrice": null
    },`

wartość price->amount jest już po obniżeniu oryginalnej wartości przez Allegro. Czy to jest poprawne zachowanie? Nawet nie widać oryginalnej wartości w żadnym miejscu. Natomiast po zakończeniu promocji, Allegro przywraca oryginalną cenę.
Problem jest tego typu, że po pobraniu danych oferty aplikacja zewnętrzna widzi cenę obniżoną (a nie oryginalną) i porównuje ją z ceną w systemie i jeżeli są one różne, to aktualizuje cenę w Allegro, bo mógł to być błąd osoby zarządzającej tą ofertą, a nie zmiana ceny w ramach kampanii.

**Comment by MartaNowaczyk** [comment]
Tak jak napisałeś w GET /sale/offers, gdy masz uruchomioną kampanię ujrzysz obniżoną cenę, taka jak jest dostępna dla klientów serwisu i taka jest prawidłowa. Przed zmianą ceny musisz upewnić się czy dana oferta ma oznaczenie w GET /sale/badges.

**Comment by array3** [comment]
Rozumiem, dziękuję za szybką odpowiedź.
