### ISSUE TITLE
Brak zlecenie u kuriera

### ISSUE THREAD

**Issue by PerfectAllegro** [allegro/allegro-api#4311]
Witam.
Mam problem ze sposobem wysyłki w programie zewnętrznym Sello.
Chodzi o Allegro kurier DPD.
Transakcja jest wykrywana, mogę utworzyć paragony oraz etykiety przewozowe. Niestety u kuriera nie pojawia się zlecenie odbioru paczek.
Jak to rozwiązać?

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się proszę w tej sprawie z Sello. Jeśli stwierdzą błąd po naszej stronie, będą mogli nam dostarczyć logi niezbędne do weryfikacji problemu.

**Comment by PerfectAllegro** [comment]
Już się kontaktowałem. Dostałem odpowiedź: "Zlecenie odbioru trzeba zlecić ręcznie przez serwis WzA lub ustawić automatyczne zlecenie stałe w konfiguracji WzA. W Sello nie ma obecnie funkcji umożliwiającej zlecenie odbioru."
Niestety nie mogę namierzyć przez Allegro jak utworzyć zlecenie odbioru.
Działa jeżeli tworzę paczki przez Allegro to potem mam zamów kuriera. Natomiast jak mam utworzone etykiety przez Sello to nie potrafię znależć samego zamówienia podjazdu kuriera.

**Comment by PrzemyslawLukanowski** [comment]
Na naszym forum świadczymy wsparcie w tematach związanych z API Allegro, Twoje pytanie dotyczy teraz strony Wysyłam z Allegro, dlatego skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dzięki temu zgłoszenie trafi do odpowiedniego zespołu.

**Comment by Onixarts** [comment]
Serwis WzA -> dodane przesyłki -> zaznaczyć wszystkie bądź wybrane i na dole funkcja PODSUMOWANIE. Po jej kilknięciu można wybrać termin i zamówić podjazd kuriera.
