### ISSUE TITLE
[PATCH] sale/product-offers/offerId/ (404) not found

### ISSUE THREAD

**Issue by Jdev11** [allegro/allegro-api#4312]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,
Chodzi o aktualizacje sygnatury external.id
Pobieram oferty w/g offers/listing?seller.id
Sprawdzam sygnature i chce zrobic update sygnatury metoda:
[PATCH] https://api.allegro.pl/sale/product-offers/offerId/10527102488
Authorization=Bearer .....
Accept = "application/vnd.allegro.beta.v2+json";
ContentType = "application/vnd.allegro.beta.v2+json";
body: { "external": {"id": "3.8875.24"}}

------------------------------
response:
{trace-id: 55ecadb6d32c286b
Content-Length: 172
Content-Type: application/json; charset=utf-8
Date: Tue, 23 Mar 2021 15:10:17 GMT
}
------------------------------

trace-id: 55ecadb6d32c286b

Dostaje blad 404 nie znaleziono.

**Comment by PrzemyslawLukanowski** [comment]
Podajesz błędny adres - /sale/product-offers/offerId/10527102488 zamiast **/sale/product-offers/10527102488.**

**Comment by Jdev11** [comment]
ale numer, dzieki.
Dzialaaaaa ;-)
