### ISSUE TITLE
Pobieranie zamówień

### ISSUE THREAD

**Issue by MaxtorGames** [allegro/allegro-api#4313]
Występuje problem:  23.03.2021 godz. 13 - nadal
 - [Pobieranie zamówień ] z zasobem REST API
 - [Comarch e-sklep ] ze środowiskiem produkcyjnym

Pracujemy na oprogramowaniu Comarch ERP od wczoraj zauważyliśmy, że od godziny 14-15 przestały nam się pobierać zamówienia z allegro do Comarch e-sklep, wczoraj cały dzień wszystko było ok do mniej więcej godziny 14-15. Czy jest jakaś awaria? Nie możemy aktualnie namierzyć po której stronie leży problem allegro czy comarch.

**Comment by MartaNowaczyk** [comment]
Nie powinno być problemu z pobieraniem zamówień. Nie mamy też podobnych zgłoszeń. W takim wypadku skontaktuj się z obsługą Comarch.
