### ISSUE TITLE
Pobranie nazwy parametru na podstawie ID parametru

### ISSUE THREAD

**Issue by wojtasss** [allegro/allegro-api#4314]
Pobierając dane konkretnej oferty z zasobu ```/sale/offers/{offerId}``` w sekcji ```parameteres``` zamiast nazw parametrów są podane ID parametrów, czy jest możliwość odpytać konkretnie jakiś zasób o nazwę parametru po tym właśnie ID?

**Comment by MartaNowaczyk** [comment]
Możesz skorzystać z zasobu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Dzięki temu otrzymasz listę parametrów, dla danej kategorii, wraz z ich nazwami. Więcej informacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/sale/#parametry).
