### ISSUE TITLE
Brak przedmiotów na sprzedaż, brak historii sprzedaży, brak możliwości wystawienia nowego przedmiotu - Sandbox

### ISSUE THREAD

**Issue by rkolakowski3e** [allegro/allegro-api#4315]
Dzień dobry,
mam problem z danymi na zarejestrowanych kontach na środowisku Sandbox (https://allegro.pl.allegrosandbox.pl/). Na 3 posiadanych kontach nie nie ma żadnego wystawionego przedmiotu, ani historii sprzedaży. Wystawionych przedmiotów było przynajmniej kilkadziesiąt, które automatycznie się odnawiały. Dodatkowo nie możemy dodać nowego przedmiotu/oferty na sprzedaż, gdyż po kliknięciu w przycisk "Dodaj nową" zostaję przekierowany na stronę https://staging-lokalnie.allegrogroup.com/oferty/wystaw , która według przeglądarki nie istnieje (Ta witryna jest nieosiągalna). Powyższe problemy powodują, że nie możemy zweryfikować poprawności pobierania transakcji poprzez API. Konta, na których występują problemy to:

Login: 3e_allegro_s3@3e.pl
Login: 3e_allegro_s4@3e.pl
Login: 3e_allegro_s5@3e.pl

Bardzo proszę o pomoc.

Pozdrawiam
Rafał Kołakowski

**Comment by PrzemyslawLukanowski** [comment]
W celu wystawienia oferty skorzystaj z linku https://allegro.pl.allegrosandbox.pl/offer/?lokalnie. Z jakiego okresu pochodzą oferty, które wystawiałeś, a które już nie są widoczne? [5 stycznia przeprowadziliśmy aktualizację kategorii i parametrów na sandboxie](https://developer.allegro.pl/news/#sandbox-january-update), co wiązało się z usunięciem wszystkich ofert.

**Comment by rkolakowski3e** [comment]
Oferty na pewno pochodzę z zeszłego roku, a więc rzeczywiście mogły zostać usunięte a więc dziękuję za wyjaśnienie. Dziękuję również za podesłanie linku https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, ten działa poprawnie i można dodać oferty. W związku z powyższym myślę, że można uznać temat za rozwiązany. Dziękuję za pomoc.
