### ISSUE TITLE
Produktyzacja API - wiązanie produktów

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4316]
Kiedy API nie pozwoli na przypisanie produktu do oferty ? Na pewno kategorie muszą być takie same a np. 

1. Atrybuty, które mają `options.identifiesProduct = true` będą się różniły to wtedy także nie puści ?
2. A co jeśli atrybuty z `options.identifiesProduct = true` będą miały identyczne wartości a inne atrybuty będą się różnić ?
3. Czy dalej jest tak, że produkt może być tylko w 1 kategorii czy już się to zmieniło ?
4. Czy połączenie oferty z produktem zawsze wymusi nadpisanie parametrów z oferty ? Dodam, że mam oferty i chce przypisać im tylko produkt w taki sposób aby produkt nie nadpisał parametrów, które są obecnie w ofercie w przypadku kiedy się różnią.

**Comment by PrzemyslawLukanowski** [comment]
1. Jeśli parametry z tym oznaczeniem będą się różniły, zwrócimy odpowiedni błąd w sekcji validation.
2. Jeśli parametry z tym oznaczeniem będą takie same, to uwzględnimy zmiany w ofercie. Pozostałe parametry z `options.identifiesProduct = false` również zamienimy zgodnie z Twoim requestem.
3. Nie, produkt może występować także w kategoriach podobnych, które w danych produktu zwracamy w sekcji **category.similar**. Więcej o tym przeczytasz w naszym [newsie](https://github.com/allegro/allegro-api/issues/4113).
4. W zależności od sposoby, w jaki łączysz ofertę z produktem:
  - przez zasoby /sale/product-offers - do oferty przypiszemy wszystkie parametry z produktu, czyli nadpiszemy te, które już są w ofercie;
  - przez /sale/offers/{offerID} - jeśli w żądaniu wskażesz id produktu i parametry zgodne z produktem (`options.identifiesProduct = true`) i również różniące się (`options.identifiesProduct = false`) - to zmiany wykonamy zgodnie z danymi z requestu. Nie zmienimy wartości dla parametrów różniących się.

**Comment by pietrach** [comment]
Czyli ten zasób  `GET ​/sale​/products​/{productId}?category.id=<id>` przeszukuje zarówno po kategorii głównej produktu oraz po podobnych czyli `category.id` i `category.similar` ?

**Comment by PrzemyslawLukanowski** [comment]
`GET ​/sale​/products​/{productId}?category.id=<id>` za pomocą tego endpointu pobierzesz dane produktu, ale w sekcji **parameters** otrzymasz tylko parametry zgodne ze wskazaną kategorią podobną (czyli nie otrzymasz parametrów z kategorii "głównej", które nie występują w kategorii podobnej i nie są potrzebne do opublikowania oferty).

**Comment by pietrach** [comment]
Może inaczej. Mamy przykład. Produkt ma `category.id = 1` i `category.similar = [2,3,4]`.
Czy jak w poniższym zasobie zamiast `<id>` wpiszę 1 to mi go znajdzie ? I jeśli wpiszę 2 lub 4 lub 4 to też go znajdzie ?
`GET ​/sale​/products​/{productId}?category.id=<id>`

Chodzi o to aby filtrował zarówno po głównej jak i podobnych

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą tego zasobu już nie wyszukujesz produktu, ponieważ jest on już wskazany w `{productId}`. Dzięki dodatkowemu parametrowi `?category.id` wskazujesz po prostu dla jakiej kategorii (z kategorii zawartych w danych produktu) mamy zwrócić parametry dla produktu.

**Comment by pietrach** [comment]
Pomyłka. Nie chodziło mi o ten zasób tylko o ten `GET /sale/products`.

Dodatkowa rzecz czy jeśli do filtru oprócz kategorii dodam aby filtrował np. EAN lub po atrybucie kod producenta to będzie to traktował w taki sposób że produkt ma spełniać

**Comment by PrzemyslawLukanowski** [comment]
Nie, dla `GET /sale/products` nie wyszukasz produktu na podstawie kategorii podobnej. Jeśli przekażesz dodatkowe query parametry w żądaniu, to również weźmiemy je pod uwagę i zawęzimy wyniki wyszukiwania.

**Comment by pietrach** [comment]
To po czym najlepiej wyszukiwać produkt aby sprawdzić czy istnieje już w bazie Allegro aby go ponownie nie tworzyć ?

**Comment by PrzemyslawLukanowski** [comment]
Na podstawie numeru EAN lub frazy.

**Comment by pietrach** [comment]
A czy każdy stworzony produkt w Allegro posiada EAN ?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie każdy, dlatego w tym przypadku możesz wyszukać produkt na podstawie frazy. Aby zawęzić wyniki możesz także skorzystać z dodatkowych filtrów dla danej kategorii.

**Comment by pietrach** [comment]
Kiedy próbuje wyszukiwać po samych parametrach np.

```
Array
(
    [224017] => T-227893-2/01Z
    [5389] => 34
)
```

To jest kod producenta i rozmiar to wyrzuca mi błąd:

```
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ConstraintViolationException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Brak wymaganych parametrów.
                )

        )

    [trace_id] => 1e1064b298adbe7e
    [http_code] => 422
)
```

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z dokumentacją musisz przekazać przynajmniej EAN lub frazę.

> At least ean or phrase parameter is required.

**Comment by PrzemyslawLukanowski** [comment]
Po nazwach produktów, czyli po polu `name`.

**Comment by pietrach** [comment]
Ale on szuka w taki sposób, że phrase = name czy phrase zawiera się w name ?

**Comment by PrzemyslawLukanowski** [comment]
Phrase zawiera się w name.

**Comment by pietrach** [comment]
Coś słabo działa. Dlaczego po wyszukaniu po następujących parametrach:

```
Array
(
    [phrase] => Buty BARTEK trzewiki chłopięce niebiesko-biały
    [224017] => T-61828/1C3
    [5389] => 19
)
```

Wyszukał mi zupełnie inne rzeczy. W żadnym z wyszukanych produktów nie ma kodu producenta identycznego jak przeze mnie wyszukany + dodatkowo ma się zawierać fraza w tytule oraz rozmiar = 19. 

Nie mogłem tutaj wrzucić wyniku bo zbyt dużo znaków.






```

**Comment by PrzemyslawLukanowski** [comment]
W [naszym poradniku](https://developer.allegro.pl/productization/#jak-znale%c5%ba%c4%87-produkt) znajdziesz informację, jak dokładnie korzystać z filtrów dla danej kategorii. Aby z nich korzystać, musisz w parametrze przekazać parametr category.id - dzięki temu na końcu odpowiedzi otrzymasz listę filtrów, z jakich możesz korzystać w ramach danej kategorii. Przykładowy, jeśli wywołam:

`GET /sale/products?phrase=Buty BARTEK trzewiki chłopięce niebiesko-biały&category.id=25960`

to na końcu response otrzymam sekcję **filters**, w której znajdują się takie parametry jak Marka i Rozmiar. Teraz mogę skorzystać z tych parametrów, aby zawęzić wyniki wyszukiwania, np. chcę znaleźć tylko buty dla podanej frazy, których rozmiar zaczyna się od 20, a marka to Bartek:

`GET /sale/products?phrase=Buty BARTEK trzewiki chłopięce niebiesko-biały&category.id=25960&5389.from=20&5390=40`

**Comment by pietrach** [comment]
To słabo to wygląda bo chciałbym wyszukać po parametrze typu kod producenta bo to jest unikalne a nie mogę. Nie wiem po co ta wyszukiwarka po co mi szukać po innych parametrach jak takich produktów może być tysiące

**Comment by hahyes** [comment]
> Coś słabo działa.

Tak, dlatego w innym wątku zasugerowałem możliwość wyszukiwania po konkretnej kategorii oraz filtrach dynamicznych (wartościach parametrów). Frazy są w wielu wypadkach generowane automatycznie, jeżeli nie spełniają założeń. Dlatego ciężko frazą coś znaleźć.

**Comment by FromAnyHole** [comment]
Nie ma lekko, wontek żyje...
