### ISSUE TITLE
sale/product-offers method returns error, about required fields

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#4317]
I set all required properties but it returns error.
traceid: e1e7fe7afe81ce83, 
error message: Unable to create product without all required parameters (7 / 8)

**Comment by MartaNowaczyk** [comment]
The error occurs becouse you are set wrong parameters - for parameter.id:128610 you have set valuesIds:128610_827694 - this value does not exist. All parameters for category you can check with [GET /sale/categories/{category}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatProductParametersUsingGET). 

We know the error message does not indicate a problem, we are working to fix it.

**Comment by hahyes** [comment]
> We know the error message does not indicate a problem, we are working to fix it.

Yeah, error descriptions should be fixed ASAP. Some description of errors as news would be nice to see too, for easier implementation.
