### ISSUE TITLE
Czy GeneralReport zawsze zróci na początku success i failed 0?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4318]
Napisałem sobie funkcje krokowej zmiany ceny pojedyńczej oferty. Czy może wystąpić sytuacja że `taskCount.success` lub `taskCount.failed` zwróci od razu 1, czy zawsze zwraca 0? (status: NEW)

**Comment by PrzemyslawLukanowski** [comment]
Ten zasób działa asynchroncznie, więc w odpowiedzi otrzymasz 0. Aby sprawdzić status wykonania zadania skorzystaj z [GET /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET) lub - aby otrzymać dokładny raport - [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).
