### ISSUE TITLE
Ean na ofercie od 29.03

### ISSUE THREAD

**Issue by lukaszzborek** [allegro/allegro-api#4319]
W poniedziałek wchodzi ostatni etap usuwania ean z oferty i produktu jako pole. Pytanie czy jezeli w poniedziałek wyśle requesta z tworzeniem oferty które będzie zawierało pole ean (nawet puste lub null) to czy dostanę zwrotke z utworzonym szkicem czy dostanę bład że nieprawidłowe pole "ean"?
Ewentualnie czy to będzie działać tak jak teraz na sanbox, tzn moge wysłać puste pole ean, ale w zwrotce go nie otrzymuje. Na prod teraz dostaje ean bez wartości (null)

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji nie otrzymasz błędu - utworzymy draft oferty, a pole "ean" zignorujemy i nie zwrócimy w odpowiedzi.
