### ISSUE TITLE
Regulamin allegro pkt 10.6.b

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#432]
Mam pytanie do pracowników allegro.
Chcę udostepnić użytkownikom aplikację zewnętrzną, zgodnie z zapisem regulaminu pkt 10.6.b muszę uzyskać zgodę allegro.
Czy muszę? jak? gdzie? 
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Podsyłam aktualny [regulamin](https://allegro.pl/webapi/rules.php).
Podeślij proszę link gdzie znalazłeś ten zapis.
Pozdrawiam

**Comment by kfijalko** [comment]
https://allegro.pl/regulamin/pl#artykul-10-inne-obowiazki-uzytkownikow

10.6.b

**Comment by MartaNowaczyk** [comment]
Skierowałam pytanie do odpowiedniego działu, aby rozwiać wszelkie wątpliwości w tym temacie. Jak dostanę informację dam nać.

**Comment by kfijalko** [comment]
Chciałbym wrócić do tematu.
W obecnym regulaminie interesuje mnie punkt:
https://developer.allegro.pl/rules/
4.1.b

Z kim mógłbym o tym porozmawiać?

**Comment by PrzemyslawLukanowski** [comment]
Odpowiedź w wątku #3892.
