### ISSUE TITLE
Pobranie url aukcji

### ISSUE THREAD

**Issue by dboryc** [allegro/allegro-api#4320]
Czy jest możliwość pobrania url'a do aukcji mając jej numer?? Nie mogę znaleźć tej opcji w dokumentacji API.

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie zwracamy adresu URL oferty w żadnym z naszych zasobów API.

**Comment by Bober95** [comment]
Witam
http://allegro.pl/show_item.php?item={OfferID}

**Comment by kfijalko** [comment]
Tak jak napisał @Bober95 . Możesz też z odpowiedzi odebrać w nagłówku redirect_url, który będzie zawierał url właściwy.

**Comment by hahyes** [comment]
Ewentualnie
https://allegro.pl/oferta/{tutaj_numer_oferty}
