### ISSUE TITLE
"connect timed out" - czy ktoś ma podobny problem?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4321]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] inny

:beetle: **Opis**

Czy ktoś z Was też ma problemy z połączeniem z Allegro?  Dostaje co chwilę "connect timed out":
Connect to api.allegro.pl:443 [api.allegro.pl/5.134.213.11]

**Comment by PrzemyslawLukanowski** [comment]
Nie stwierdziliśmy problemów po naszej stronie, nie otrzymaliśmy także zgłoszeń od innych użytkowników.

**Comment by hahyes** [comment]
> Występuje problem:
> 
> * [x]  z zasobem REST API
> * [x]  ze środowiskiem produkcyjnym
> * [x]  inny
> 
> 🐞 **Opis**
> 
> Czy ktoś z Was też ma problemy z połączeniem z Allegro? Dostaje co chwilę "connect timed out":
> Connect to api.allegro.pl:443 [api.allegro.pl/5.134.213.11]

Prawdopodobnie problem z połączeniem internetowym po stronie operatora.

**Comment by tomylee0** [comment]
Trudno powiedzieć. W każdym razie takie rzeczy tu już były: #4050.

Na szczęście problem zniknął.
