### ISSUE TITLE
Problem z ponownym połaczeniem API z serwisem

### ISSUE THREAD

**Issue by luxisallegro** [allegro/allegro-api#4322]
Witam,

mam serwis połączony z allegro przez API, ostatnio musieliśmy zmienić serwer i trzeba było wszystko konfigurować od nowa, i w tym momencie zaczyna się problem, nie wiemy dlaczego rest api allegro zwraca nam błąd ""bad request", wszystko jest ustawione jak poprzednio, nie bylo zadnych zmian.

pomoc allegro wskazuje to forum jako miejsce gdzie mozna uzyskac pomoc techniczna allegro w sprawie api.
Mam tu podac client id aplikacji, zeby ktos na to spojrzal?

Pozdrawiam

**Comment by kfijalko** [comment]
Napisz, które żądanie zwraca "bad request".
Czy przeniosłeś tokeny? Czy łączyłeś konta z aplikacja od nowa?

**Comment by luxisallegro** [comment]
Ja sam nie jestem programista, administruje ale w ograniczonym zakresie, takie "trudniejsze" rzeczy to robi mi programista.

Myślę, że zrobił oba powyższe, ale będę pewien w poniedziałek, problem został określony jako:
"Sprawdziłem nawet najprostszy skrypt testowy z ich poradnika i on też nie działa, także to nie jest problem kodu. Nie mamy żadnej informacji zwrotnej o co konkretnie chodzi - jedynie "bad request". Być może to kwestia tego, że mamy za starą wersję OpenSSL, ale nie mogę nigdzie znaleźć jaka jest minimalna obsługiwana. Ewentualnie o to możesz zapytać supportu Allegro."

**Comment by PrzemyslawLukanowski** [comment]
@luxisallegro Prześlij proszę przykładowy request i response w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą wątku #4322 na GitHub. Zweryfikujemy, co jest przyczyną błędu.

**Comment by PrzemyslawLukanowski** [comment]
@luxisallegro Weryfikacja aplikacji związana jest tylko z GET /offers/listing, pozostałe zasoby powinny Wam działać prawidłowo. Tak jak wspomniałem - najlepiej będzie, jeśli prześlesz przykładowy request i response w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pozwoli nam to wskazać bezpośrednią przyczynę błędu. Pamiętaj proszę, aby w zgłoszeniu dopisać, że dane dotyczą wątku GitHub #4322.

**Comment by PrzemyslawLukanowski** [comment]
@luxisallegro Otrzymaliśmy dane przez formularz. Otrzymujecie błędy 401 i 403, ponieważ korzystacie z tokena, którego wygenerowaliście w ramach autoryzacji [client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow). Taki token nie ma kontekstu użytkownika i za jego pomocą możecie odpytywać tylko zasoby oznaczone w naszej [dokumentacji ](https://developer.allegro.pl/documentation/) jako bearer-token-for-application. Żeby natomiast pobrać zamówienia lub oferty dla zautoryzowanego użytkownika, musicie posiadać token wygenerowany w drodze [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow.

**Comment by luxisallegro** [comment]
ok, ale to nie ma zwiazku z "weryfikacja" aplikacji? tę od 15 marca (tej nasza apka nie przeszla i nie przejdzie, bo ta weryfikacje przechodza tylko podmioty z duza sprzedaza)

**Comment by AureliuszBrussy** [comment]
@luxisallegro nie, nie ma to związku z weryfikacją aplikacji. Chodzi tylko o wygenerowanie przez aplikację prawidłowego tokena, z kontekstem użytkownika.  Niezbędne jest użycie innej metody autoryzacji -  [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow.

**Comment by luxisallegro** [comment]
Poprawilismy token, juz prawie jest ok, niby jest połaczenie,

![obraz](https://user-images.githubusercontent.com/81446266/113453404-2f58de80-9406-11eb-9e8c-f709a2c629c8.png)

 ale przy probie wyslania kodów wyskakuje:

Błąd w komunikacji z API - {"errors":[{"code":"EmptyUserIdException","message":"user_name from JWT cannot be empty","details":null,"path":"/order/checkout-forms","userMessage":null}]}

**Comment by luxisallegro** [comment]
choc teraz wyrzucilo tez inny blad
"Błąd w komunikacji z API - {"error":"invalid_token","error_description":"Error decoding token. Token: "}"

**Comment by AureliuszBrussy** [comment]
@luxisallegro aplikacja, z której korzystasz próbuje odświeżyć token (skorzystać z refresh token), ale nie przekazuje żadnej wartości w parametrze refresh_token. 

Jeżeli chodzi o ten błąd:
```
{"errors":[{"code":"EmptyUserIdException","message":"user_name from JWT cannot be empty","details":null,"path":"/order/checkout-forms","userMessage":null}]}
```
to komunikat świadczy o tym, że korzystacie z tokena typu bearer-token-for-application, a zasób wymaga użycia tokena bearer-token-for-user. Tak jak wspominaliśmy wcześniej - niezbędne jest użycie innej metody autoryzacji - [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow.
