### ISSUE TITLE
Refresh token error

### ISSUE THREAD

**Issue by frenci8** [allegro/allegro-api#4323]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hi,

I am using this endpoint https://developer.allegro.pl/en/auth/#refresh-token in order to extend my access token for another 12 hours. 

But the problem is, when I send the post request, I get the error type `invalid_grant` with description `Invalid refresh token: {refresh token here}`

Any idea why? Do I have to wait for my current access token to expire first before trying to extend/refresh it? 

Thank you

**Comment by AureliuszBrussy** [comment]
No, you do not have to wait until the current access token expires. 

Please send your example refresh token via the [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) so that I can check it. Include your GitHub issue number in the message - #4323.

**Comment by frenci8** [comment]
> No, you do not have to wait until the current access token expires.
> 
> Please send your example refresh token via the [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) so that I can check it. Include your GitHub issue number in the message - #4323.

I sent it.

**Comment by AureliuszBrussy** [comment]
@frenci8 could you also send your full request in curl form?

**Comment by frenci8** [comment]
It is fixed now. I ran the code again and it worked now. Did you change anything from your side?

The full request looks like this curl -X POST -H 'Authorization: Basic YTI...Hg=' 'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJ...SDA' except I replace basic auth and refresh token with my values

**Comment by AureliuszBrussy** [comment]
@frenci8 I'm glad it works :). I did not change anything. The previous request did not reach the correct service. Now I see that you used the refresh token correctly - everything is alright.
