### ISSUE TITLE
WZA - identyfikator usługi dostawy

### ISSUE THREAD

**Issue by shopelo** [allegro/allegro-api#4325]
Witam,
próbuję zintegrować WZA z naszym systemem. Pobieram listę usług dostawy na której jest dostępny id usługi.
{
    "id": 8490564,
    "service": "DPD",
    "name": "Allegro DPD"
    "carrierId": "DPD",
    ....
}
            
Następnie pobieram szczegóły zamówienia w którym w danych adresowych klienta wskazana jest metoda:{
{
    "id":"c3066682-97a3-42fe-9eb5-3beeccab840c",
    "name":"Allegro Kurier DPD"
}.

Jak mam powiązać id z zamówienia z usługą dostawy z WZA.

**Comment by AureliuszBrussy** [comment]
Nie ma możliwości zmapowania usługi dostawy z przewoźnikiem po id tej usługi. Na ten moment kieruj się proszę tabelką udostępnioną w [naszym poradniku](https://developer.allegro.pl/wza/#jak-utworzy%c4%87-now%c4%85-paczk%c4%99).
