### ISSUE TITLE
Problem z /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by AptusShop** [allegro/allegro-api#4326]
Do tej pory zwracał invoice jako tablicę (nawet jak nie była required), a dziś od 14:00 pojawia mi się tam null. To jakaś planowana zmiana? 
Środowisko produkcyjne

**Comment by AureliuszBrussy** [comment]
Wystąpił z naszej strony chwilowy błąd - aktualnie zwracamy obiekt invoice w prawidłowej formie.

**Comment by AptusShop** [comment]
Potwierdzam, dziękuję
