### ISSUE TITLE
Niespójne wartości parametrów po dodaniu produktu do katalogu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4338]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

utworzyłem sobie produkt: 026e637b-41d5-492b-916d-0124ac9b6d93
Problem jest taki, że tworzyłem go z parametrem 3806 ustawionym na wartość 407382 (M). Jednakże w produkcie została umieszczona wartość 3 (36). Nie do końca rozumiem, dlaczego został zmieniony rozmiar. Próbuję potem wystawić ofertę z tymi samymi danymi, jakie podawałem przy produkcie i mam błąd, że podaję nieprawidłową wartość przy parametrze 3806.

O co tutaj chodzi? Nie jestem pewien, czy te rozmiary są równoważne, jednak sytuacja taka nie powinna moim zdaniem występować, nawet jeżeli są to teoretycznie zgodne ze sobą rozmiary. Zwłaszcza, że skoro byłyby to równoważne rozmiary, to czemu zasób POST /sale/offers ma z tym problem?

Dodatkowo, przez POST /sale/offers muszę podać TE SAME wartości dla parametrów identyfikujących produkt. Myślałem, żeby pominąć te parametry, ale nie - nie da się. Eh...

Edit: Znalazłem też przykład, kiedy po dodaniu produktu zmieniła się kategoria.
Produkt: 26c2534a-3e5f-4320-9fcb-157c50d47bec
Dodawałem produkt z kategorią 75995, produkt jest z kategorią 76013.
Jak z czymś takim pracować?

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Konsultuję Twoje zgłoszenie z odpowiednim zepsołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@hahyes z naszych danych wynika, że podczas tworzenia tych produktów takie parametry otrzymaliśmy, dlatego takie znalazły się we wskazanych produktach. Niestety, jednak nie jesteśmy już w stanie sprawdzić szczegółów w logach ze względu na zbyt odległy czas. Czy jesteś w stanie podać jakiś nowszy przykład, najlepiej (jeśli to możliwe) z trace-id?

**Comment by hahyes** [comment]
> z naszych danych wynika, że podczas tworzenia tych produktów takie parametry otrzymaliśmy, dlatego takie znalazły się we wskazanych produktach. Niestety, jednak nie jesteśmy już w stanie sprawdzić szczegółów w logach ze względu na zbyt odległy czas. Czy jesteś w stanie podać jakiś nowszy przykład, najlepiej (jeśli to możliwe) z trace-id?

Gdybym takie parametry w ogóle miał w swojej bazie danych, w ogóle bym tutaj nie pisał. Pobierałem dane z bazy, pakowałem do zapytania. Nie ma opcji, że wartość magicznie uległa zmianie gdzieś po mojej stronie, bo nie napisałem takiego kodu ani baza nie była w żaden sposób edytowana. Nikt mi nie wmówi, że takie parametry dostaliście, bo to nieprawda.

Niestety produkty dodawałem tego samego dnia, więc to są wszystko przykłady z podobnego czasu. Jednak jest ich stosunkowo wiele. Widzę wyraźnie produkty po swojej stronie, które nawet są tytułowane danym rozmiarem, a produkt posiada zupełnie inny rozmiar i zasób pruje się o podanie "prawidłowego" przy wystawianiu. 

Zauważyłem też, że przy problemie z kategoriami, za każdym razem zmiana kategorii jest na liść Pozostałe z konkretnego liścia. 

Postaram się wygenerować jakiś trace-id jeszcze dzisiaj i wrócę z nim, jak tylko znajdę tego typu przypadek. Jeszcze nie złapałem go na gorącym uczynku niestety.

**Comment by AureliuszBrussy** [comment]
@hahyes rozumiem, sprawdzimy co dokładnie się dzieje i jaka jest przyczyna takiego zachowania, jak tylko otrzymamy od Ciebie swieży przykład.
