### ISSUE TITLE
Problem z nazwą nowo powstałych ofert

### ISSUE THREAD

**Issue by kampep9** [allegro/allegro-api#4339]
Witam posiadam zewnętrzny sklep internetowy na platformie sellingo podczas wystawiania nowych aukcji poprzez tą platformę do do nazw nowych aukcji na allegro dopisywana jest końcówka "Najtaniej!" nie wiem gdzie jest problem ponieważ na sklepie zewnętrznym nazwy są poprawne. Dzwoniłem do administratora mojego sklepu www ale on powiedział że tą końcówkę nadaje allegro... jak to usunąć???

**Comment by MaciejFrackowiak** [comment]
Jako Allegro nie dodajemy automatycznie do tytułów ofert żadnych "dodatków" - sugeruję kontakt z dostawcą oprogramowania, ponieważ tylko on posiada requesty generowane przez oprogramowanie.

**Comment by kampep9** [comment]
Dziękuje za szybką odpowiedz udało się rozwiązać problem
