### ISSUE TITLE
Aktywacja oferty

### ISSUE THREAD

**Issue by masterix** [allegro/allegro-api#434]
Witam,

chcę aktywować zakończoną aukcję w ciągu 30 dni za pomocą endpointu offer-publication-commands.

https://allegroapi.io/sale/offer-publication-commands/3dc1ff67-d77b-41fe-a3e6-892717431c30
Body:
`{"offerCriteria":[{"offers":[{"id":7450375869}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2018-07-24T16:30:44.000Z"}}`

Po kilku sekundach dostaję z https://allegroapi.io/sale/offer-publication-commands/3dc1ff67-d77b-41fe-a3e6-892717431c30 odpowiedź:
`{"id":"3dc1ff67-d77b-41fe-a3e6-892717431c30","taskCount":{"total":1,"success":1,"failed":0}}`
Czyli jest sukces. Niestety aukcja się nie odnowiła.

Co tu jest źle?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam,
Jeśli możesz podaj proszę trace-id dla tego zapytania.

**Comment by masterix** [comment]
Skąd mam wziąć trace-id?

**Comment by MartaNowaczyk** [comment]
Przesysyłamy taką informację w Response -> Headers
Do weryfikacji proszę przesłać jeszcze pełne curle.

**Comment by masterix** [comment]
@MartaNowaczyk - sprzed chwili, nowa próba:
`{"offerCriteria":[{"offers":[{"id":7450375869}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE","scheduledFor":"2018-07-25T15:11:00:000Z"}}`

Odp:
`HTTP/1.1 400 Bad Request
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 8d35c18c09aebdbe
Date: Wed, 25 Jul 2018 13:09:16 GMT
X-RateLimit-Remaining: 8988
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/json
X-RateLimit-Limit: 9000`

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offer-publication-commands/c6f459d3-bc7c-4e60-800f-ad13c76184c9","userMessage":null}]}"`

Komunikat błędu nic nie mi nie mówi niestety.

**Comment by masterix** [comment]
HTTP/1.1 400 Bad Request
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
X-Frame-Options: DENY
Trace-Id: 8d35c18c09aebdbe
Date: Wed, 25 Jul 2018 13:09:16 GMT
X-RateLimit-Remaining: 8988
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/json
X-RateLimit-Limit: 9000

Tak nagłówki są czytelniejsze.

**Comment by MartaNowaczyk** [comment]
@masterix sprawdż czy wpisujesz poprawny UUID i pamiętaj, że to globalnie unikatowy identyfikator.

**Comment by masterix** [comment]
@MartaNowaczyk  to jest UUID wygenerowany wewnątrz naszego systemu i błąd powstał przy próbie aktywacji oferty a nie sprawdzaniu statusu: https://allegroapi.io/sale/offer-publication-commands/c6f459d3-bc7c-4e60-800f-ad13c76184c9

Czy po w/w trace-id możecie sprawdzić co tu się nie udało?

**Comment by MartaNowaczyk** [comment]
Tak, trace-id jest nam potrzebny do sprawdzenia co poszło nie tak.

**Comment by masterix** [comment]
To sprawdź proszę, tak jak wyżej: Trace-Id: 8d35c18c09aebdbe

**Comment by MartaNowaczyk** [comment]
Oczywiście. Dam znać jak uda nam się coś ustalić.

**Comment by masterix** [comment]
@MartaNowaczyk  czy coś już wiesz?

**Comment by MarcinLuczak** [comment]
@masterix jeszcze nie mamy nowych informacji na ten temat.

**Comment by MarcinLuczak** [comment]
@masterix udostępnij proszę pełne cURL-e requesta i response'a w których jest widoczny problem. Czy ten problem nadal występuje?

**Comment by masterix** [comment]
Problem przestał występować obecnie.
