### ISSUE TITLE
Dodanie faktury do zamówienia

### ISSUE THREAD

**Issue by RaVq3K** [allegro/allegro-api#4340]
- [X] z zasobem REST API
 - [X] ze środowiskiem testowym
 
Witam aktualnie próbuję dodać fakturę do zamówienia korzystając z zasobu /order/checkout-forms/{id}/invoices lecz za każdym razem otrzymuję 404 Funkcja niedostępna. Skontaktuj się z autorem aplikacji.

trace-id = 99d0a146f1ebd895 dla zamówienia 2dc1ff91-914d-11eb-9480-d7ade4e4db67

**Comment by MaciejFrackowiak** [comment]
Znalazłem log, jednak nie widzę jego szczegółów - mam tylko info o błędzie 404. Sprawdziłem działanie samej funkcjonalności na Sandbox - bez przeszkód wygerowałem obiekt faktury, a następnie dokonałem uploadu pliku.

**Comment by RaVq3K** [comment]
Witam przychodzę jeszcze z problemem uploadu, bo w poprzednim problemie miałem 404 bo zjadłem literkę :).
aktualnie przy próbie uploadu dostaję 415 Unsupported Media Type.

traceId = faeb9a9dac23085d dla endpointu /order/checkout-forms/7261eb71-92c3-11eb-ab8f-fdfb8a607443/invoices/7f363768-4786-4d95-9e67-d77d5786532a/file

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę nagłówek Content-Type - powinien przyjąć wartość "application/pdf".

**Comment by RaVq3K** [comment]
Ustawiłem na appliaction/pdf oraz na */* oraz application/vnd.allegro.beta.v1+json
w każdym z tych przypadków otrzymuję kod 406 Not Acceptable
 traceId = 8bcf5ac016ddfbe3

**Comment by MaciejFrackowiak** [comment]
Dla podanego trace-id=8bcf5ac016ddfbe3 widzę takie nagłówki:

accept: * / *
content-type: * / *

Prawidłowe wartości:

accept: application/vnd.allegro.public.v1+json
content-type: application/pdf

**Comment by RaVq3K** [comment]
Dla takich wartości również próbowałem np. 
/order/checkout-forms/16db6091-92d4-11eb-b68b-59dfcd1e885f/invoices/a2467117-ec79-447a-808e-0813ce1d9c52/file

trackId 4123a51979a43566

**Comment by MaciejFrackowiak** [comment]
W przypadku tego wywołania użyłeś accept:  application/vnd.allegro.beta.v1+json

**Comment by RaVq3K** [comment]
A czy to wywołanie nie jest właśnie na środowisko testowe

**Comment by MaciejFrackowiak** [comment]
Tak, jest to wywołanie na Sandbox, gdzie nagłówek powinien przyjąć wartość "public" również - dotyczy to zasobu, a nie środowiska. Tylko zasoby, który nie przyjęły jeszcze ostatecznego kształtu mają nagłówek "beta".

**Comment by RaVq3K** [comment]
Tak racja, wszystko już gra można zamknąć :)

**Comment by RaVq3K** [comment]
Jeszcze taka mała sugestia na sandboxie link do pobrania faktury prowadzi do stabilnej ;)

**Comment by MaciejFrackowiak** [comment]
Proszę wskaż miejsce, w którym widzisz taką niespójność.

**Comment by RaVq3K** [comment]
będąc pod linkiem https://allegro.pl.allegrosandbox.pl/moje-allegro/zakupy/kupione/(tutaj jakiś ciąg znaków gdzie jest FV)

Pod guzikiem pobierz url prowadzi do edge.allegro.pl a powinno chyba do edge.allegro.pl.allegrosandbox.pl
![image](https://user-images.githubusercontent.com/53236315/113391304-a2753d00-9393-11eb-93c3-980fc6445467.png)

**Comment by MaciejFrackowiak** [comment]
Dziękuję za screen i doprecyzowanie - sprawę przekazałem już do właściwego zespołu.
