### ISSUE TITLE
Zniknęła aplikacja API

### ISSUE THREAD

**Issue by p0wertiger** [allegro/allegro-api#4341]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W panelu zarządzania aplikacjami Allegro zniknęła nam jedna z aplikacji, która na pewno nie korzystała z /offers/listing . W ogóle nie ma śladu po niej. Spróbowałem skorzystać z danych innej aplikacji, która pozostała w panelu, ale tam z kolei dostaję 400 Bad Request. Problem zaczął występować od 15.03.2021.

Dodam tylko, że wymóg dwuskładnikowego uwierzytelniania przez SMSy w środowisku firmowym jest dosyć uciążliwy dla pracowników i developerów, nasze konto nie ma go włączonego.

**Comment by AureliuszBrussy** [comment]
Abym mógł zobaczyć co się stało - podaj proszę Client ID tej aplikacji.

**Comment by p0wertiger** [comment]
Udało mi się to wyjaśnić z Allegro przez formularz kontaktowy
