### ISSUE TITLE
Obejście limitu zapytań na Client ID

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4342]
![image](https://user-images.githubusercontent.com/3116731/113131919-155ca780-921e-11eb-8ad0-503d7b0b6a85.png)

A ile można maksymalnie stworzyć aplikacji? Przykładowo czy jeśli stworzę np 100 aplikacji na 100 osobnych użytkowników wtedy teoretycznie mam 9000 zapytań na minutę na 1 użytkownika zamiast 9000 zapytań na minutę dla 100 użytkowników co znacznie skróciło by czas przetworzenia wszystkich użytkowników. Pytanie tylko czy takie obejście jest dozwolone w Waszym regulaminie?

Mój pomysł polega na tym aby w swojej bazie mieć listę aplikacji (ClientID+Client secret) i każdy użytkownik może być przypisany do różnych aplikacji. Wtedy gdy każde konto ma np. 30 000 ofert skróci to znacznie czas przetworzenia tych ofert bo każdy użytkownik będzie używał innego client id ze swoim osobnym limitem.

**Comment by MaciejFrackowiak** [comment]
Maksymalnie możesz zarejestrować 5 aplikacji na jednym koncie. Każde działanie, które będzie odbiegać od działania standardowego użytkownika może zostać uznane za naruszające regulamin usługi. Ponadto zawsze sugerujemy, aby dana aplikacja przedstawiała się jednym ClientID, ponieważ zapewnia to spójność i przejrzystość działania.

**Comment by bugproof** [comment]
@MaciejFrackowiak 

> Każde działanie, które będzie odbiegać od działania standardowego użytkownika może zostać uznane za naruszające regulamin usługi

A jakie dokładnie działanie odbiega od standardowego użytkowania? Czy jeśli zrobię np 5 aplikacji i będe ich używał w tym samym celu będzie to odbiegało od standardowego użytkowania?

**Comment by MaciejFrackowiak** [comment]
Zbiór działań naruszających [regulamin REST API Allegro](https://developer.allegro.pl/rules/) znajdziesz w punkcie 3.8.
