### ISSUE TITLE
Jak wstawić oferte w allegro sandbox

### ISSUE THREAD

**Issue by oosebossoo** [allegro/allegro-api#4343]
Witam,

Mam pytanie dot. serwisu sandbox, czy można wstawić oferty w tym środowisku, jeśli tak to byłbym wdzięczny o podpowiedzienie co do metody wstawiania?

Pytanie nie dotyczy api lecz samego allegro sandbox. Jest przycisk "wystaw przedmiot", lecz prznosi on mnie do allegro lokalnie(https://staging-lokalnie.allegrogroup.com/oferty/wystaw), na dodatek wywalając błąd "This site can’t be reached".

Dodam, że potrzebuje zbierać info o aktualnych moich ofertach, jeżeli nie ma opcji wstawiania tam ofert to czy instenie inny sposób na testowanie wymienionej funkcji?

Z góry dziękuje za pomoc :)

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z [odnośnika](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie), wówczas będziesz mógł wystawić ofertę na Sandbox.

**Comment by Negaron** [comment]
Po skorzystaniu z odnośnika można rozpocząć wystawianie oferty, ale po wybraniu kategorii (lub produktu "podobnego") dostaję komunikat "Nie udało się utworzyć oferty dla wybranego produktu."

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi ID Twojego konta oraz ID draftu, który tworzysz.

**Comment by Negaron** [comment]
Oferty nie tworzę za pomocą API tylko z interfejsu.

Dodaję obsługę zamówień z Allegro do mojej aplikacji sprzedażowej. W tym celu założyłem 3 konta w sandboxie:
- "twórca aplikacji" - w nim zarejestrowałem aplikację
- "sprzedawca" - w nim powiązałem aplikację "twórcy" za pomocą oauth2
- "randomowy klient" - ten klient będzie coś kupował u "sprzedawcy" żeby ten mógł sobie w aplikacji pobrać zamówienia za pomocą API

Jestem na etapie takim, że powiązałem konto "sprzedawcy" z aplikacją "twórcy", umiem się "sprzedawcą" zalogować, otrzymuję access_token i refresh_token. I chciałem przejść do etapu pobierania zdarzeń za pomocą GET /order/events

Ale nie mam zamówień, bo "sprzedawca" nie ma jeszcze oferty w której kupić mógłby coś "randomowy klient". Więc zalogowałem się z poziomu przeglądarki na konto "sprzedawcy" i próbuję normalnie, z interfejsu graficznego stworzyć jakąś aukcję żeby "randomowy klient" mógł coś kupić, a "sprzedawca" wczytać za pomocą API zamówienie. I tutaj, na etapie wystawiania aukcji mam błąd "Nie udało się utworzyć oferty dla wybranego produktu."

Konto "sprzedawcy" ma nick regis, jeśli potrzebujesz jeszcze jakichś informacji to doprecyzuję.

**Comment by MaciejFrackowiak** [comment]
Twoje konto nie było aktywne - już je aktywowałem. Ponadto wybrałeś konto firmowe, które musisz zweryfikować - w tym celu proszę prześlij dwa dowolne piki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) - po weryfikacji już bez problemów wystawisz ofertę.

**Comment by Negaron** [comment]
Dziękuję za pomoc.
