### ISSUE TITLE
POST sale/offers przestał przyjmować zdjęcia z serwera zewnętrznego Zwraca: Provided image address is incorrect.

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4346]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Od dzisiaj nie jest możliwe wysłanie oferty z images które są na serwerze zewnętrznym
Wysyłam:

![image](https://user-images.githubusercontent.com/81759361/113301507-60022080-92ff-11eb-9408-4108b3822d13.png)

a otrzymuje:
![image](https://user-images.githubusercontent.com/81759361/113301562-6e503c80-92ff-11eb-91bd-ff3df6b14f34.png)

**Comment by AureliuszBrussy** [comment]
W przypadku zasobu **/sale/offers** - nigdy nie pozwalaliśmy na umieszczanie zdjęć bezpośrednio z serwera zewnętrzego. Na tym zasobie wymagane jest najpierw przesłanie zdjęcia [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST). 

Tylko w przypadku zasobu **/sale/product-offers** zdjęcia mogą pochodzić z zewnętrznych serwerów, nie musisz ich wcześniej wysyłać na serwer Allegro. Więcej o tym piszemy w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-doda%c4%87-w%c5%82asne-zdj%c4%99cie-do-oferty).

**Comment by Waclaw-W** [comment]
Dziękuję za szybką odpowiedź.
