### ISSUE TITLE
POST sale/offers nie przyjmuje "parameters"

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4347]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Wysyłam to :
![image](https://user-images.githubusercontent.com/81759361/113326872-884b4880-931a-11eb-9240-7c79e4b88e2c.png)

otrzymuję to :
![image](https://user-images.githubusercontent.com/81759361/113326931-9d27dc00-931a-11eb-928d-2f01c4bfed68.png)

to zupełnie prawidłowe bo nie podałem żadnych parametrów, ale jak dodam :
![image](https://user-images.githubusercontent.com/81759361/113327396-2e974e00-931b-11eb-8238-3f28e800c1f5.png)

to otrzymuję:
![image](https://user-images.githubusercontent.com/81759361/113327646-7ddd7e80-931b-11eb-9669-13d4ca488989.png)

Trochę mnie to dziwi bo przedwczoraj i wczoraj to wszystko działało :) Wystawiłem tą metoda 17 ofert

Prosze o jakąś podpowiedź

**Comment by AureliuszBrussy** [comment]
Obiekt **parameters[].rangeValue** nie jest tablicą. Jeżeli nie przekazujesz tam żadnych wartości, powinieneś wprowadzić **null**.

**Comment by Waclaw-W** [comment]
Dzień dobry, 
Dziękuję za informacje. Już wczoraj po 21:00 zaczęło to znów chodzić i dziś widzę nadal działa.
Pozdrawiam
