### ISSUE TITLE
Problem z refresh tokenem

### ISSUE THREAD

**Issue by webtsx** [allegro/allegro-api#4348]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Witam,

mam problem z refresh tokenem. Tj. po wygaśnięciu access tokena wysyłam żądanie odświeżenia tokena i otrzymuję błąd invalid_grant, invalid refresh_token. 
W jaki sposób można sprawdzić o co chodzi, bo ja już nie mam pomysłu. Zaraz po przypisaniu aplikacji do konta, działa refresh i można wygenerować, ale potem już nie. W jaki sposób sprawdzić o co chodzi w tym przypadku ?

**Comment by AureliuszBrussy** [comment]
Prześlij proszę przykładowy request (zachowaj w nim cały refresh token) i response  w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pozwoli nam to wskazać bezpośrednią przyczynę błędu. Pamiętaj proszę, aby w zgłoszeniu dopisać, że dane dotyczą wątku GitHub #4348.

**Comment by webtsx** [comment]
Poszło zgłoszenie. Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
@webtsx dziękuję, otrzymałem zgłoszenie. Na przykładzie, który przesłałeś w zgłoszeniu - z naszych logów wynika, że użyłeś po raz pierwszy refresh token tuż po otrzymaniu pary access i refresh token. Sekwencja jest taka:

1. Otrzymujesz parę access i refresh token: 2021-04-01 09:15:49,
2. Korzystasz z uzyskanego w pkt 1 refresh tokena i otrzymujesz nową parę: 2021-04-01 09:16:44,
3.  Próbujesz bezskutecznie ponownie skorzystać z refresh tokena uzyskanego w pkt 1: 2021-04-01 21:00:01.

**Comment by webtsx** [comment]
Wydaje mi się, że już wtedy to poprawiłem. Teraz ustawiłem aktualizację co 6 godzin i działa. Dzięki za informację.
