### ISSUE TITLE
Zły status wniosku o zwrot prowizji - rozbiezność z stanem w "Moje allegro"

### ISSUE THREAD

**Issue by najmrosek** [allegro/allegro-api#4349]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dlaczego wniosek o zwrot prowizji dla ktorego przyznano prowizje (podobniez "recznie" .. wg info z  zgłoszenia allegro nr "14558504" )  ma status "IN_PROGRESS" ?
Wniosek ma w  "Moje Allegro" status "Zaakceptowany" czyli "GRANTED" ..

Dla przykladu wniosek ID : 5448de01-3aba-4205-bedd-8f9dcd95430f 
Szczegoly wniosku ponizej :

 | aukcja | ilosc | cena | data sprzedazy | wniosek data | wniosek ID
 | 7494798810 | 1 | 19.95 | 2021-01-27T09:25:05.329Z | 2021-03-09T06:29:20.125Z | 5448de01-3aba-4205-bedd-8f9dcd95430f

**Comment by MaciejFrackowiak** [comment]
Sprawę konsultuję z zespołem odpowiedzialnym za zwroty prowizji, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Status został ujednolicony, w API widnieje też już "GRANTED".

**Comment by najmrosek** [comment]
Dziekuje za poprawe, tylko .. szkoda, ze nie rozwiazaliscie sprawy globalnie ..

Poszedl tylko pojedynczy update na rekordzie ??
Ja mam jeszcze kilka takich problematycznych wnioskow ..i co zawsze bede musial prosic o zmiane statusu ... ???

Prosze sprawdzic i porownac statusy dla : 
377ba465-52ad-4023-85b7-cf122a3f845e
4e52ad98-7f47-4c73-a3a7-c23dc24ab869
666ad396-59bb-4cc2-842a-f9a49a9f2427

**Comment by MaciejFrackowiak** [comment]
Pozostałe statusy również ujednoliciliśmy. Jednocześnie zespół odpowiedzialny za funkcjonalność przyjrzy się dokładnie kwestii różnic w statusach pomiędzy API a WWW.
