### ISSUE TITLE
Nie mozna pobrać ID produktu, a próba utworzenia produktu kończy się błędem ProductDuplicate

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#4351]
Witam,
Dla dużej ilości ofert nie jestem w stanie pobrać id produktu (po GTIN, nazwie z kategorią i nazwie bez kategorii), ale próba dodania kończy się błędem ProductDuplicate "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji"

Przykład GTIN: 070999005959 (próbowałem wyszukiwać również dla 0070999005959 oraz 70999005959 )

Przy okazji może rozważylibyście zwracanie product id w przypadku błędu ProductDuplicate?

**Comment by AureliuszBrussy** [comment]
W przypadku produktu GTIN: 070999005959, gdy skorzystasz z GET /sale/products?ean=070999005959 - zwrócimy odpowiedni produkt, z którego możesz skorzystać podczas wystawiania oferty. 

Jeżeli chodzi o duplikaty - w response w nagłówku **location** wskazujemy odnośnik do istniejącego produktu (w odnośniku jest product id tego duplikatu).

**Comment by dol1234** [comment]
Faktycznie, dzisiaj zwróciło produkt pod tym EANem, a dla innych przypadków alternatywę znalazłem w nagłówku, dziękuję za szybką odpowiedź:)
