### ISSUE TITLE
Centrum wiadomości - link z nazwą w html

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#4353]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Sprawa dotyczy centrum wiadomości i podglądu wiadomości wysłanej przez sprzedającego do kupującego. Wiadomość e-mail zawiera treść w formacie text/plain oraz text/html . W centrum wiadomości link z tekstem wyświetlany jest jako zwykły tekst bez hiperłącza - jakby została odczytana wiadomość HTML z strip_tags jak leci.

![image](https://user-images.githubusercontent.com/2742214/113708244-471fb380-96e1-11eb-899d-fa951b7cb004.png)

Test na sandbox (wiadomość 6.04.2021 13:57:43):
`https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/centrum-wiadomosci/wiadomosci/thread/9uTkk3ijLWiXi2IVVrIULBr2BFn4TOg9ZuLhl1gbohN
`

Alternative part (text/plain)
```
Dzień dobry
Link bez nazwy: https://assets.allegrostatic.com/metrum/brand/allegro-347440b030.svg
Link z nazwą: https://assets.allegrostatic.com/metrum/brand/allegro-347440b030.svg
Pozdrawiam
```

Alternative part (text/html) [wycinek]
```
<p>Dzień dobry</p>
<p>Link bez nazwy: https://assets.allegrostatic.com/metrum/brand/allegro-347440b030.svg</p>
<p>Link z nazwą: <a href="https://assets.allegrostatic.com/metrum/brand/allegro-347440b030.svg">Logo Allegro</a></p>
<p>Pozdrawiam</p>
```

Czy w centrum wiadomości:
- Powinna się wyświetlić wiadomość w formacie text/plain o ile została przesłana?
- Powinna się wyświetlić wiadomość html z strip_tags ale uwzględniająca podmianę tekstu w linku
 (`'~<a href="(https?://[^"]+)".*?>.*?</a>~', '$1' `)?

Dziękuję i pozdrawiam

**Comment by AureliuszBrussy** [comment]
Na naszym forum świadczymy wsparcie w tematach związanych z API Allegro, Twoje pytanie dotyczy niedostępnego w API Centrum Wiadomości. dlatego skontaktuj się z nami przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dzięki temu zgłoszenie trafi do odpowiedniego zespołu.

**Comment by Radeq** [comment]
Skontaktowałem się z Allegro, w skrócie, **nie uważają tego za błąd**. Odczytują tylko wiadomość HTML (tekstowy odpowiednik ignorują) i robią na nim strip_tags przez co z linka zostaje tylko tytuł.
