### ISSUE TITLE
Wyszukanie po identyfikatorze oferty

### ISSUE THREAD

**Issue by mearelin** [allegro/allegro-api#4354]
Czy istnieje możliwość wyszukania aukcji po identyfikatorze np.: **7680126102**?
> https://allegro.pl.allegrosandbox.pl/oferta/buty-na-obcasach-rozm-40-zloty-7680126102

Przeczytałem [poradnik ](https://developer.allegro.pl/listing/) na Państwa stronie, jednak nie znalazłem interesującej mnie informacji.
Próbowałem wyszukać aukcji po frazie
> /offers/listing?phrase=7680126102

Jednak nie przyniosło to pożądanego rekordu tzn. response nie zwraca żadnego rekordu.

**Comment by Lukasz-Zurek** [comment]
Nie ma możliwości wyszukiwania oferty po identyfikatorze.

Zapoznaj się również z [naszym ostatnim newsem](https://github.com/allegro/allegro-api/issues/4213).

**Comment by mearelin** [comment]
Czyli trzeba wyszukać oferty po loginie sprzedającego + ew. kategorii i z pobranej listy wyszukać danej oferty. Dzięki za informacje.

**Comment by Lukasz-Zurek** [comment]
Tak, potwierdzam.
