### ISSUE TITLE
updatedAt field in order API

### ISSUE THREAD

**Issue by sandguardian** [allegro/allegro-api#4355]
When does `updatedAt` value get updated in `/order/checkout-forms/{id}` endpoint?

I pull order fulfillment status via API and sometimes staff updates fulfillment status on the web page.
My script pulls orders from last checkpoint of updatedAt to get latest status of order.

But updating fulfillment status doesn't update value of `updatedAt` field.
What's the recommended approach to achieve this?

**Comment by Lukasz-Zurek** [comment]
The `updatedAt` is influenced only by the actions of the buyer, for example: making a surcharge, completing the payment or order cancelation.

Generally the `updatedAt` value will not be changed if you try to update fullfillment status, add a tracking number, etc.

**Comment by sandguardian** [comment]
@Lukasz-Zurek  What's the recommended way to pull the last fulfillment status of orders updated recently?

If `updatedAt` is for payment, isn't it same with `payment.finishedAt`?
Other ecommerce APIs such as Amazon update `updatedAt` for any change in order.

**Comment by Lukasz-Zurek** [comment]
You can use: [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) and pay attention to `FULFILLMENT_STATUS_CHANGED`. Event will occurs, if the status of the order fulfillment has been changed. You can pass it in your request as a value of type parameter, which will limit the results in the response.

The `updatedAt` is not the same as the `payment.finishedAt`. As I did mention earlier, the `updatedAt` is influenced only by the actions of the buyer - not only payments but also for example: order cancelation.

**Comment by Lukasz-Zurek** [comment]
If you change order fulfillment status visible in the `fulfillment.status` field via: [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment ](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT), then you will get `FULFILLMENT_STATUS_CHANGED` status in your events response. 

You wll find more information in [our guide.](https://developer.allegro.pl/en/orders/#order-fulfillment-status-change)
