### ISSUE TITLE
GET /sale/offer-price-change-commands/{commandId}/tasks działa też dla zmian ilości

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4356]
Zauważyłem że `GET /sale/offer-price-change-commands/{commandId}/tasks` można używać także do sprawdzania `offer-quantity-change-commands` czy jest jakaś różnica między `GET /sale/offer-quantity-change-commands/{commandId}/tasks` czy oba te zasoby w backendzie wskazują na tą samą metode?

**Comment by Lukasz-Zurek** [comment]
Wskazane zasoby, podobnie jak ich struktura - są niemal identyczne. Jednakże `GET /sale/offer-price-change-commands/{commandId}/tasks` dedykowany jest do sprawdzenia szczegółowego raportu dla zmiany ceny w ofercie/ofertach, a `GET /sale/offer-quantity-change-commands/{commandId}/tasks` przeznaczony jest do sprawdzenia szczegółowego raportu dla zmiany liczby sztuk. Chcieliśmy to rozdzielić.

**Comment by bugproof** [comment]
> Jednakże GET /sale/offer-price-change-commands/{commandId}/tasks dedykowany jest do sprawdzenia szczegółowego raportu dla zmiany ceny w ofercie/ofertach, a GET /sale/offer-quantity-change-commands/{commandId}/tasks przeznaczony jest do sprawdzenia szczegółowego raportu dla zmiany liczby sztuk.

Czy zwracają one identyczne raporty dla danego commandId?

**Comment by Lukasz-Zurek** [comment]
Tak, zwracają one identyczne raporty dla danego commandId.
