### ISSUE TITLE
Komunikat: "Zapytanie sformułowane nieprawidłowo. Popraw zapytanie i spróbuj ponownie." podczas pobierania aukcji.

### ISSUE THREAD

**Issue by SebaaK** [allegro/allegro-api#4357]
Dzień dobry Wszystkim,

Mam kod który pobiera wszystkie aukcje bazując na operatorze $offset dodając co 60 z każdym przejściem, aż do osiągnięcia wszystkich zebranych aukcji. Zapytanie wygląda tak: 

**`"https://api.allegro.pl/offers/listing?seller.login=" . $login . "&offset=" . $total;`**

Przy mniejszych kontach, które mają np. 30-40 tyś. aukcji program działa bez żadnego problemu, ale w momencie kiedy pojawi się konto, które ma blisko 200tyś. aukcji pojawia mi się błąd:

**`{"errors":[{"code":"InvalidOffsetException","message":"Invalid offset parameter value.","details":null,"path":null,"userMessage":"Zapytanie sformułowane nieprawidłowo. Popraw zapytanie i spróbuj ponownie."}]}`**

Jest w stanie mi ktoś pomóc?

Pozdrawiam serdecznie Was wszystkich ;)

**Comment by Lukasz-Zurek** [comment]
Komunikat świadczy o tym, że wartość parametru `"offset"` jest nieprawidłowa / przekracza dopuszczalny limit. 

Podaj proszę trace-id dla wywołanego zapytania. Trace-ID otrzymujesz w nagłówku odpowiedzi na wywołanego wcześniej requesta.

**Comment by SebastianKot** [comment]
Chodzi tutaj o to co zwraca AccessToken? Bo w wywołaniu tego: 

`"https://api.allegro.pl/offers/listing?seller.login=" . $login . "&offset=" . $total;`  requesta nie pokazuje mi się trace-ID.

A można przez PRIV idKonta podać?

**Comment by Lukasz-Zurek** [comment]
Możesz nam przesłać dodatkowe dane, w tym również request i response w formacie curl przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4357.

**Comment by hahyes** [comment]
> Chodzi tutaj o to co zwraca AccessToken? Bo w wywołaniu tego:
> 
> `"https://api.allegro.pl/offers/listing?seller.login=" . $login . "&offset=" . $total;` requesta nie pokazuje mi się trace-ID.
> 
> A można przez PRIV idKonta podać?

Musisz podać przy wykonywaniu requesta header "Trace-Id", którego wartością będzie wygenerowany kod GUID. Wtedy otrzymasz trace-id od Allegro (który jest inny od tamtego kodu GUID). Polecam, może się przydać w przyszłości.

**Comment by SebastianKot** [comment]
> > Chodzi tutaj o to co zwraca AccessToken? Bo w wywołaniu tego:
> > `"https://api.allegro.pl/offers/listing?seller.login=" . $login . "&offset=" . $total;` requesta nie pokazuje mi się trace-ID.
> > A można przez PRIV idKonta podać?
> 
> Musisz podać przy wykonywaniu requesta header "Trace-Id", którego wartością będzie wygenerowany kod GUID. Wtedy otrzymasz trace-id od Allegro (który jest inny od tamtego kodu GUID). Polecam, może się przydać w przyszłości.

Nie wiem czy dobrze rozumiem, dopisać do końca "linku"?
Czy mógłbym Cię prosić żebyś dał mi jakiś przykład z tym wywołaniem ?

**Comment by hahyes** [comment]
> Nie wiem czy dobrze rozumiem, dopisać do końca "linku"?
> Czy mógłbym Cię prosić żebyś dał mi jakiś przykład z tym wywołaniem ?

https://kobietydokodu.pl/niezbednik-juniora-protokol-http/
Wybacz, że taka strona, ale była pierwsza w Google a widzę też, że jest brak podstawowej wiedzy. Nagłówki to osobna część zapytania, którymi przekazywane są dodatkowe dane. Tego nie ma w samym adresie. Jak rozumiem, korzystasz z jakiegoś języka programowania. Wbudowana biblioteka powinna być w stanie takie nagłówki dodawać (dziwne, gdyby klient HTTP tego nie miał). 

A samo "Trace-Id" jest potrzebne do szybszego rozwiązywania problemów tutaj. Podajesz Trace-Id od Allegro i otrzymujesz szybko odpowiedź. Nie jest to rozwiązanie problemu niestety.

**Comment by SebastianKot** [comment]
> > Nie wiem czy dobrze rozumiem, dopisać do końca "linku"?
> > Czy mógłbym Cię prosić żebyś dał mi jakiś przykład z tym wywołaniem ?
> 
> https://kobietydokodu.pl/niezbednik-juniora-protokol-http/
> Wybacz, że taka strona, ale była pierwsza w Google a widzę też, że jest brak podstawowej wiedzy. Nagłówki to osobna część zapytania, którymi przekazywane są dodatkowe dane. Tego nie ma w samym adresie. Jak rozumiem, korzystasz z jakiegoś języka programowania. Wbudowana biblioteka powinna być w stanie takie nagłówki dodawać (dziwne, gdyby klient HTTP tego nie miał).
> 
> A samo "Trace-Id" jest potrzebne do szybszego rozwiązywania problemów tutaj. Podajesz Trace-Id od Allegro i otrzymujesz szybko odpowiedź. Nie jest to rozwiązanie problemu niestety.

I tak dziękuję!
Tzn. przyznaje się, że jestem samoukiem i wiem, że to ułatwia sprawę ze zgłoszeniami na Allegro także postaram się jak najszybciej to ogarnąć. 

Pisze w PHP

**Comment by SebastianKot** [comment]
> Możesz nam przesłać dodatkowe dane, w tym również request i response w formacie curl przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4357.

Wysłałem zgłoszenie Panie Łukaszu, a ja w między czasie ogarnę ten Trace-Id

**Comment by Lukasz-Zurek** [comment]
@SebastianKot Dziękuję. Wrócę wkrótce z odpowiedzią.

**Comment by SebastianKot** [comment]
@Lukasz-Zurek 
Ogólnie sprawdziłem ten parametr $offset i dochodzi do tych 120000. W jaki sposób inny można pobrać wszystkie aukcje?

Czekam z niecierpliwością. Miłego dnia.

**Comment by Lukasz-Zurek** [comment]
@SebastianKot Zapoznałem się z Twoim zgłoszeniem. W żądaniu podajesz następującą wartość parametru: `"offset=120000"`

Jeśli w swoim żądaniu wykorzystujesz parametr - `seller.id/seller.login, `maksymalna wartość wynosi `120000` i nie pobierzesz większej ilości ofert.

Informacje na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/#1-jak-wyszukiwa%c4%87-i-przegl%c4%85da%c4%87-oferty).

**Comment by SebastianKot** [comment]
@Lukasz-Zurek 

No tak :/ 
We wcześniejszych kontach, które nie mają tak dużo aukcji nie ma najmniejszego problemu z pobraniem wszystkich aukcji. Jaki sposób można by było zastosować by pobrać dużą ilość aukcji np. 200 tyś.?

**Comment by Lukasz-Zurek** [comment]
@SebastianKot Niestety nie udostępniamy takiej możliwości.
