### ISSUE TITLE
Masowe usuwanie draftów

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4358]
Witam,

Chciałbym się zapytać czy jest jakaś możliwość do masowego usuwania ofert w statusie INACTIVE? Poprzez GUI nie mogę tego uzyskać (brakuje przycisku USUŃ - jest tylko UKRYJ i ZAKOŃCZ). Więc musiałbym ręcznie to przeklikać. A przez API to musiałbym pobierać wszystkie INACTIVE, zapisać ich offer id i później dla każdej takiej oferty wysyłać DELETE na sale/offers?

**Comment by mirkosmuz** [comment]
Na GUI można tylko pojedynczo usuwać DRAFTY. Brakuje masowego usuwania.

**Comment by Lukasz-Zurek** [comment]
@mrezlik Potwierdzam - podobnie jak w przypadku GUI, przez API również nie usuniesz masowo ofert w statusie INACTIVE. Możesz jedynie korzystać z [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE), zgodnie z tym co napisałeś powyżej.

**Comment by mrezlik** [comment]
Dziękuję za odpowiedź. W przyszłości myślę, że można pomyśleć o wprowadzeniu tego rozwiązania :)

**Comment by Lukasz-Zurek** [comment]
Również dziękuję. Sugestię przekazałem do działu odpowiedzialnego za rozwój naszego API.
