### ISSUE TITLE
Problem z z zapytaniem które tworzy Produkt + ofertę - REPUBLISH dla licytacji + kup teraz nie wznawia oferty

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#4359]
Występuje problem: Problem z z zapytaniem które tworzy Produkt + ofertę - REPUBLISH dla licytacji + kup teraz nie wznawia oferty. 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mamy problem z z zapytaniem które tworzy Produkt + ofertę - REPUBLISH dla "licytacji" + "kup teraz" nie wznawia oferty. 
Wysyłamy w request:
`
"publication": {
		"duration": "P3D",
		"startingAt": null,
		"endingAt": null,
		"status": "INACTIVE",
		"endedBy": null,
		"republish": true
	},
	"sellingMode": {
		"format": "AUCTION",
		"price": {
			"amount": 129.9,
			"currency": "PLN"
		},
		"startingPrice": {
			"amount": 77.9,
			"currency": "PLN"
		}
`

A w odpowiedzi dostajemy:
`
"publication": {
		"duration": "PT72H",
		"status": "INACTIVE",
		"endedBy": null,
		"endingAt": null,
		"startingAt": null,
		"republish": false
	},
`

**Comment by mirkosmuz** [comment]
Pełną treść zapytania i odpowiedzi wysłałem przez https://allegro.pl/pomoc/kontakt

**Comment by Lukasz-Zurek** [comment]
W sekcji `“publication”`, w polu: `“status”` przekazujesz wartość `“INACTIVE”`, w związku z czym oferta nie była aktywna po wysłanym żądaniu. Utworzyłeś draft oferty.

Ponadto w zasobie [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) pole `"republish"` nie jest obsługiwane. Jest tylko zwracane w odpowiedzi.

**Comment by otwarcie** [comment]
Czy któraś z istniejących metod/zasobów umożliwia edycję tego pola?

**Comment by Lukasz-Zurek** [comment]
@otwarcie Pole `"republish"` możesz przekazać korzystając z: [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT). Wysyłając wartość: `true` w polu `"republish"`, włączysz opcję wznawiania oferty.

**Comment by otwarcie** [comment]
Dziękuję za odpowiedź. 
PUT /sale/offers/{offerId} powinienem wysłać z nagłówkami dla starego API (public.v1) czy dla nowego (beta.v2)? 
Ofertę stworzyłem łącznie z produktem, jest z nim połączona. Czy PUTem mam przesłać komplet danych użytych przy tworzeniu oferty, czy mam odfiltrować parametry opisujące produkt? Czy może PUT zadziała jak PATCH i wystarczy mu identyfikator aukcji i parametr 'republish'?

**Comment by mirkosmuz** [comment]
Dzięki za odpowiedź. Wiem że to jest draft, tak publikujemy oferty. (ponowie pytanie kolegi) Czy planujecie ustawianie tego pola metodą PATCH /sale/product-offers/{offerId}?
Bez sensu jest to teraz obsługiwać dwoma zapytaniami.

**Comment by Lukasz-Zurek** [comment]
@otwarcie @mirkosmuz Nie mamy tego w planach. Zachęcam jednak do utworzenia sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Pozostali użytkownicy będą mogli oddawać swoje głosy.
