### ISSUE TITLE
Problem z nowym opisem

### ISSUE THREAD

**Issue by smok55453** [allegro/allegro-api#436]
Witam. Mam problem z wystawienie oferty poprzez WebApi. Za każdym razem dostaję komunikat, że opis jest niepoprawny. Zawartość pola przesłałem poprzez formularz kontaktowy. Numer zgłoszenia to: 1249765718
Cała struktura pola fid_341 jest poprawna według mnie

**Comment by lokneey** [comment]
Witam. 
Mam podobny problem. W załączniku przesyłam request i response z Fiddlera. Do tej pory nie było problemu z przesyłaniem danych w takim formacie fid_341. REST API też nie miało potem problemu z taką strukturą opisu. Proszę o pomoc, gdzie może być błąd? Problemy zostały zgłoszone dzisiaj.
Pozdrawiam.
[opis.zip](https://github.com/allegro/allegro-api/files/2227775/opis.zip)

**Comment by MarcinLuczak** [comment]
@smok55453 masz nieprawidłowe znaki w treści opisu np. taki znacznik - `<\/p>`. Wystaw ofertę z opisem jaki chcesz mieć w ofercie, a następnie pobierz tą ofertę za pomocą [tego zasobu](https://developer.allegro.pl/documentation/#!/offer/getOfferUsingGET). Tam będziesz miał swój opis w prawidłowej formie.

Dodam w REST API są już dostępne zasoby do wystawiania ofert. W [tym miejscu](https://developer.allegro.pl/sale/#rest-api), w formie poradnika, dokładnie opisaliśmy wszystkie te zasoby. Natomiast w [październiku 2018](https://developer.allegro.pl/news/2018-06-06-Wygaszamy_webapi/) metody WebAPI do obsługi oferty oznaczymy jako deprecated i nie będziemy ich już rozwijać. 

@lokneey tak jak napisałem wyżej - wystaw ofertę z opisem jaki chcesz mieć w ofercie, a następnie pobierz tą ofertę za pomocą [tego zasobu](https://developer.allegro.pl/documentation/#!/offer/getOfferUsingGET). Tam będziesz miał swój opis w prawidłowej formie. Jeżeli nadal będziesz miał problem - podeślij XML-e z pełnym requestem i responsem w którym go widać. Plik, który udostępniłeś, nie zawiera XML-i.

**Comment by smok55453** [comment]
Poprawiłem generowanie opisu. Teraz otrzymuję inny komunikat: doCheckNewAuctionExt - Description not found.
Przesyłam pełny request oraz response 
[data.zip](https://github.com/allegro/allegro-api/files/2231508/data.zip)

**Comment by MarcinLuczak** [comment]
@smok55453 metoda doCheckNewAuctionExt nie służy już do sprawdzania poprawności oferty. Nie przystosowujemy jej do zmian w procesie wystawiania i obsługi ofert. Obecnie za jej pomocą sprawdzisz tylko ogólne oraz szczegółowe kosztów związane z wystawieniem oferty przed jej faktycznym wystawieniem. Dlatego zwraca taki komunikat błędu gdy podasz nowy opis - po prostu widzi, że nie podałeś starego opisu (którego i tak nie możesz dodać) i rzuca błędem.

Od razu dodam, że w październiku 2018 oznaczmy metody WebAPI do obsługi oferty jako deprecated. Dlatego warto zacząć korzystać z zasobów w REST API, które służą do obsługi oferty. Opisaliśmy je w [tym poradniku](https://developer.allegro.pl/sale/).

**Comment by smok55453** [comment]
Ok, koszty aukcji mogę sobie odpuścić, ale nie mogę wystawić aukcji przez metodę doNewAuctionExt. Sytuacja wygląda identycznie jak w przypadku doCheckNewAuctionExt. Takie same dane przesyłam, ten sam komunikat dostaję. 
Czyli mam rozumieć, że nie mogę wystawić już oferty poprzez WebApi, ponieważ podając nowy opis wymagane jest też podanie starego opisu, ale jednocześnie nie mogę podać starego opisu?
Jedynym wyjście jest przejście na REST API?

**Comment by MarcinLuczak** [comment]
> Czyli mam rozumieć, że nie mogę wystawić już oferty poprzez WebApi, ponieważ podając nowy opis wymagane jest też podanie starego opisu, ale jednocześnie nie mogę podać starego opisu? Jedynym wyjście jest przejście na REST API?

Wystawiając przez WebAPI możesz (a w zasadzie to nawet musisz) podać nowy opis. Służy do tego fid 341. Nawet jeśli podasz stary opis w fidzie 24, to i tak go zignorujemy.

Jeżeli w doNewAuctionExt masz podobny/taki sam problem, jak przy doCheckNewAuctionExt, udostępnij proszę XML-e (request i response) w których widać problem w metodzie doNewAuctionExt.

**Comment by MarcinLuczak** [comment]
@smok55453 w requeście dodałeś tylko dwa zdjęcia - w fidach 16 i 17 - a w treści nowego opisu w fidzie 341 odnosisz się do zdjęć z fidów 16, 17 i 18. Popraw opis, tak by był zgodny.

Nie wysyłaj również opisu w fidzie 24.

**Comment by smok55453** [comment]
Racja to był problem z tym jednym zdjęciem. Teraz opis już przechodzi poprawie w obu metodach. Ale natrafiłem na problem z czasem wysyłki. W metodzie doCheNewAuctionExt dostaję komunikat, że pole czas wysyłki nie jest dostępny w podanej kategorii. Ok, więc wyrzuciłem pole 340 z tego requesta. I przeszło normalnie do metody doNewAuctionExt. Tutaj dostałem taki sam komunikat. Więc usunąłem to pole tak samo jak w poprzedniej metodzie. Ale tym razem dostaję komunikat, że pole czas wysyłki nie może być puste. Podsyłam requesty i responsy z oraz bez pola 340
[bezPola340.zip](https://github.com/allegro/allegro-api/files/2244021/bezPola340.zip)
[zPolem340.zip](https://github.com/allegro/allegro-api/files/2244022/zPolem340.zip)

**Comment by MarcinLuczak** [comment]
@smok55453 dziwna sprawa - sprawdzimy to.

**Comment by smok55453** [comment]
@MarcinLuczak Czy przez te dwa tygodnie udało się coś ustalić w tej sprawie?

**Comment by MarcinLuczak** [comment]
@smok55453 Tak, otrzymałem dzisiaj informację, że problem nie powinien występować ani w serwisie produkcyjnym ani na Sandboxie.
