### ISSUE TITLE
Problem z responsem /order/events/

### ISSUE THREAD

**Issue by oosebossoo** [allegro/allegro-api#4360]
Witam! Mam problem z odczytaniem responsa z zasobu /order/events/. Otrzymuje następującą treść:

`{"events":[{"id":"1617790334872130","order":{"seller":{"id":"93979076"},"buyer":{"id":"93995208","email":"vyjpq3e2u1+1ee2043b8@user.allegrogroup.pl","guest":false,"login":"Client:93995208"},"lineItems":[{"offer":{"id":"7680166142","name":"UUN2 8GB SREBRNY USB2.0","external":null},"price":{"amount":"1.00","currency":"PLN"},"id":"66b19580-9789-11eb-b52c-8b7eefbb1428","quantity":1,"originalPrice":{"amount":"1.00","currency":"PLN"},"boughtAt":"2021-04-07T10:11:45.553Z"}],"checkoutForm":{"id":"66b231c0-9789-11eb-80ab-8b7eefbb1428","revision":"f1445f93"}},"type":"READY_FOR_PROCESSING","occurredAt":"2021-04-07T10:11:57.958Z"}]}true`

Dlaczego na końcu widnieje wartość "true", dlaczego gdy próbuje przetworzyć te informacje w zmienniej(np. dostać się do id) dostaje komunikat że zmienna jest zmienną typu bool? 

Pokreślę że w dokumentacji w przykładowym responsie nie ma tej ostatniej wartości. Jest tak z każdym zapytaniem również z zasobem /me, czy z /account/additional-emails.

Czy ma ktoś pomysł jak sobie z tym poradzić?

**Comment by Lukasz-Zurek** [comment]
Zgłoszenie zweryfikuję i wrócę wkrótce z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
W naszym API wszystko zwracamy poprawnie i nie otrzymaliśmy podobnych zgłoszeń od innych użytkowników. 

Przyczyna może leżeć po stronie oprogramowania, lub formatowania danych w odpowiedzi.

Być może któryś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie pomóc.
