### ISSUE TITLE
W jaki sposób działa automatyczne łączenie ofert z produktem?

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#4361]
Dzień dobry
Czy oferty w których wystarczy kliknąć zapisz z poziomu listy ofert by połączyć jest z produktem zostaną automatycznie połączone z produktem? Czy muszę wykonać dodatkową akcje?
![Screenshot from 2021-04-07 14-30-43](https://user-images.githubusercontent.com/4314822/113867014-4dc82c80-97ae-11eb-8a0d-6f79a54aa189.png)

**Comment by Lukasz-Zurek** [comment]
Jeżeli wszystkie warunki, o których wspomniał Przemek w [innym wątku](https://github.com/allegro/allegro-api/issues/4287#issuecomment-814684446) - zostały spełnione - kliknięcie w opcję "Zapisz" powinno zakończyć się prawidłowym przypisaniem oferty do produktu. Nie jest to jednak opcja bezpośrednio związana z naszym API, dlatego w przypadku pojawienia się jakichkolwiek pytań dotyczących produktyzacji, napisz proszę do nas przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
