### ISSUE TITLE
POST /sale/badges => zgłoszenie do kampanii

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4362]
Co się stanie gdy np. oferta ma cenę 149 zł i zgłaszam ją do kampanii np. SALE i podaje cenę promocyjną 129 zł a cenę rynkową 189 zł. Czy zostanie wyrzucony błąd ? Czy może zgłoszenie zostanie zaakceptowane a cena w ofercie automatycznie się zmieni na przekreśloną równą 189 zł i promocyjną równą 129 zł ?

**Comment by Lukasz-Zurek** [comment]
Jeśli skorzystasz z zasobu [POST /sale/badges](https://developer.allegro.pl/documentation/#operation/postBadges), w wysłanym żądaniu zostanie przekazane zgłoszenie oferty do określonej kampanii. W przypadku, gdy zgłoszenie zostanie zaakceptowane, cena promocyjna wyniesie: 129 zł.

Pamiętaj jednak, że zgłoszenia, które nie spełnią wymagań danej kampanii zostaną odrzucone.

**Comment by pietrach** [comment]
Chodzi o to czy przekreślona cena będzie 149 zł czy 189 zł. Czy to zgłoszenie automatycznie zmieni dotychczasową cenę 149 zł na 189 zł i ją przekreśli czy może zostanie wyrzucony błąd, że cena rynkowa nie jest równa cenie ustawionej w ofercie ?

**Comment by Lukasz-Zurek** [comment]
Pytanie nie dotyczy stricte API, dlatego napisz proszę w tej sprawie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).
