### ISSUE TITLE
Problem z wysłaniem zdjęć przez upload.allegro.pl.allegrosandbox.pl

### ISSUE THREAD

**Issue by rwojtyczka-neurosys** [allegro/allegro-api#4363]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Mamy analogiczny problem jak w https://github.com/allegro/allegro-api/issues/4346 . Idąc tropem z tamtego zgłoszenia, próbuję wysłać zdjęcia na podany w dokumentacji endpoint https://upload.allegro.pl.allegrosandbox.pl

Żądanie:
```
POST https://upload.allegro.pl.allegrosandbox.pl
Authorization: Bearer [tutaj token]
Content-Type: application/vnd.allegro.public.v1+json;charset=UTF-8
Accept: application/vnd.allegro.public.v1+json

{"url": "https://picsum.photos/801/601"}
```

Odpowiedź:
```
HTTP/1.1 404 Not Found
trace-id: fb27aeaebdcb7701
content-type: application/json; charset=utf-8
content-length: 172
date: Thu, 08 Apr 2021 08:17:20 GMT

{
  "errors": [
    {
      "code": "NotFoundException",
      "message": "Not found",
      "details": null,
      "path": null,
      "userMessage": "Function is not available. Contact the author of the application."
    }
  ]
}
```

W jaki sposób mogę poprawnie wysłać zdjęcia na sandboxa?

**Comment by Lukasz-Zurek** [comment]
Potwierdzam. Prawidłowy link dla tego żądania powinien wyglądać następująco: https://upload.allegro.pl.allegrosandbox.pl/sale/images

Dodawanie zdjęć na sandboxie działa prawidłowo.
