### ISSUE TITLE
/sale/offers/unfilled-parameters zwraca nieistniejące parametry

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#4364]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

`/sale/offers/unfilled-parameters` zwraca

```
"id": "9175376418",
"parameters": [{
	"id": "237190"
}],
"category": {
	"id": "49144"
}
```

Nie ma takiego parametru w tej kategorii

**Comment by AureliuszBrussy** [comment]
Potwierdzam wystąpienie tego błędu. Zgłosiłem to do odpowiedniego zespołu. Wkrótce wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Problem nie powinien już występować - kwestia związana była z opóźnieniem aktualizacji danych o parametrze.
