### ISSUE TITLE
Does exist fast way for creating new offers by REST-API?

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#4365]
Hello.

We create new offers by route /sale/offers and new images by route /sale/images. And It takes too long time. 
Does exist fast way for creating new offers by REST-API? Especially images uploading.

Thanks a lot

**Comment by AureliuszBrussy** [comment]
You can also create and manage offers by using [/sale/product-offers](https://developer.allegro.pl/en/product_offers/) resource. We simplify the whole process there, for example, you don't need to use /sale/images to upload images. Please check [out our tutorial](https://developer.allegro.pl/en/product_offers/) on how to use:
- [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers),
- [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/en/documentation/#operation/editProductOffers).
