### ISSUE TITLE
Weryfikacja aplikacji /offers/listing

### ISSUE THREAD

**Issue by mariobros6** [allegro/allegro-api#4368]
Cześć. Jak długo może trwać weryfikacja aplikacji?
Ja czekam 3. tydzień. 
Czy może na forum jest osoba, z która można się w tej sprawie kontaktować?

**Comment by AureliuszBrussy** [comment]
Temat weryfikacji i realizacji określonych warunków jest realizowany poza bezpośrednim wsparciem wykorzystania API, dlatego o wszelkie szczegóły dopytaj proszę w korespondencji, którą dotychczas prowadziłaś poprzez formularz kontaktowy.

Ze swojej strony mogę Cię prosić wyłącznie o cierpliwość - zespół odpowiedzialny za weryfikację ma obecnie sporo zadań, stąd wydłużony czas całego procesu.
