### ISSUE TITLE
PUT /sale/offers/ItemID

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#437]
Witam, odświeżę temat,
Co w przypadku gdy nie korzystam z e zdefiniowanego cennika dostaw tylko ustalam dla konkretnej oferty koszta ręcznie. Wówczas api zwraca mi dane w metodzie /sale/offers/ItemID:

[delivery] => stdClass Object
    (
        [shippingRates] => 
        [handlingTime] => PT0S
        [additionalInfo] => 
        [shipmentDate] => 
    )

Gdy próbuję to wysłać to otrzymuję błąd że mam podać ID cennika. Jak zaktualizować ofertę nie ruszając ręcznie ustalonych cen wysyłek?

**Comment by expondo** [comment]
To jest trochę bez sensu skoro przez stronę i stare API jest możliwość ustalania cen indywidualnych do oferty. Przy niektórych produktach trzeba podać konkretne ceny wysyłek i nie widzę sensu robienia cenników per produkt.

**Comment by masterix** [comment]
Allegro widzi to obecnie trochę inaczej, mają wprowadzać obowiązkowość cenników. W kwestii edycji oferty to wiem, że ma się coś zmienić odnośnie do cenników, ale kiedy/co/jak to już nie wiem.

**Comment by MarcinLuczak** [comment]
@expondo @masterix jeżeli wystawiasz ofertę na podstawie wcześniej pobranej oferty, nie możesz podać osobno kosztów dostawy dla poszczególnych sposobów dostawy. Musisz w takim przypadku wskazać cennik jaki ma być przypisany do tej oferty.

Wstępnie planujemy udostępnić możliwość edycji ofert, w których nie ma cennika dostawy.
