### ISSUE TITLE
wyłączyć wznawianie oferty przez API

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4371]
W formularzu Allegro jest pole "Wznawianie oferty (opcjonalnie) po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów".

Czy to oznacza, że ​​tworzona jest kopia oferty z nowym identyfikatorem lub ta sama oferta jest przywracana?

Wygląda na to, że kiedy publikuję ofertę przez API, ta opcja jest włączona. Jak mogę wyłączyć tę opcję przez API?

**Comment by AureliuszBrussy** [comment]
Tak, zaznaczenie opcji "_Wznawianie oferty (opcjonalnie) po zakończeniu wystaw ponownie ofertę z pełnym zestawem przedmiotów_" oznacza, że aktywujemy kopię oferty z nowym identyfikatorem. 

W API także jest taka opcja - udostępniamy pole **publication.republish**. Oferta wznowi się automatycznie pod nowym numerem tylko i wyłącznie w przypadku, gdy przekażesz w nim wartość **true**.

**Comment by vartaller** [comment]
Czy istnieje możliwość zmiany wartości tej opcji za pomocą API bez wysyłania pełnego szablonu oferty?

**Comment by vartaller** [comment]
Czy istnieje możliwość zmiany wartości tej opcji za pomocą API bez wysyłania pełnego szablonu oferty?

**Comment by AureliuszBrussy** [comment]
@vartaller nie, obecnie nie ma takiej możliwości, zmianę wprowadzisz tylko za pomocą [PUT sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) (wymaga przesłania pełnego szablonu oferty).
