### ISSUE TITLE
Powiązanie oferty z produktem jak sprawdzić oferty seryjnie ?

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4372]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Jaka jest możliwość sprawdzenia seryjnie które oferty sa powiązane z produktem a które nie ?

Gdy podpytuję np. GET sale/offers?publication.status=ENDED&limit=100&offset=0, lista nie zwraca informacji o produkcie.
![Screenshot_24](https://user-images.githubusercontent.com/81759361/114035707-a61b2f00-987f-11eb-91ce-b959e9977441.jpg)

Jednak gdy odpytam pojedynczą ofertę np. 
![Screenshot_23](https://user-images.githubusercontent.com/81759361/114035500-70764600-987f-11eb-9dcc-d07225e55e10.jpg)

 ... to ten produkt jest widoczny.

Jest jakiś sposób na szybkie porównanie które oferty mają a które nie mają produktu ? bez odpytywania 30 tys ofert pojedyńczo ?

**Comment by AureliuszBrussy** [comment]
Aby znaleźć oferty, które nie są powiązane z żadnym produktem - wywołaj **GET /sale/offers?product.id.empty=true**. W [naszym poradniku](https://developer.allegro.pl/my_offers/#filtry) znajdziesz informacje o innych dostępnych filtrach.

**Comment by Waclaw-W** [comment]
Dziękuje za szybką odpowiedź. 
Tak, to będzie dobre rozwiązanie :)
