### ISSUE TITLE
Brak zdjęć w aukcjach wystawianych przez API

### ISSUE THREAD

**Issue by michalmkr** [allegro/allegro-api#4373]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, na aukcjach wystawionych kiedyś przez API brak zdjęć np aukcja nr. 9753037539

**Comment by AureliuszBrussy** [comment]
Z naszych danych wynika, że oferta ta nie posiadała zdjęć już w momencie jej wystawienia (w roku 2020). Niestety, ale nie posiadamy już logów, które pozwoliłyby na sprawdzenie, co się dokładnie stało. Wygląda na to, że zdjęcia nie zostały w ogóle do oferty dołączone.
