### ISSUE TITLE
Dostęp do sandbox

### ISSUE THREAD

**Issue by EBeige** [allegro/allegro-api#4374]
Witam,

poproszę o dostęp do sandbox, user: e-beige
Jakie organisationID podajemy wtedy w sandbox, te z prod?, także ten sam token?

Dzieki,

KP

**Comment by SebaaK** [comment]
Przeczytaj tutaj: https://developer.allegro.pl/getting_started/

**Comment by EBeige** [comment]
Dzieki SebaaK, 
czyli to oznacza ze:
z PROD mogę korzytstać z tokena i id z paczkomaty.pl - bez rejestracji.
z TEST (sandbox)  muszę rejestrować app i generować id + token?

**Comment by Lukasz-Zurek** [comment]
@EBeige Zarejestruj proszę konto na [tej stronie](https://allegro.pl.allegrosandbox.pl/rejestracja?origin_url=%2F). Jest to środowisko testowe, w związku z czym możesz ustalić wybrane przez Ciebie dane.

Jeśli wybierzesz konto firmowe, w celu jego weryfikacji prześlij proszę dwa dowolne pliki poprzez zakładkę [Dane konta.](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php). Daj nam również znać w tym wątku - aktywujemy konto.

Jak już wspomniałeś powyżej - musisz zarejestrować aplikację na [stronie](https://apps.developer.allegro.pl.allegrosandbox.pl/) i korzystając z dostępnych tam danych, wygenerować token dostępowy.

**Comment by EBeige** [comment]
@Lukasz-Zurek, super, dzięki. już zarejestrowałem się. Strony są rozsypane pod Chrome a więc nie wiem i gdzie z tym przesyłaniem plików (mam konto firmowe)
Aplikacja też zarejestrowana, ale nie mam php, żeby wygenrować token. Macię jakąś storne, z generowaniem, czy muszę sobie kod napisać do generowania tokena? Jeśli tak, please link do funkcji REST odpowiedzilnej za generacje.

**Comment by Lukasz-Zurek** [comment]
@EBeige Konto już aktywowałem. Zakładka [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) powinna bez problemu się otwierać,. Masz możliwość załączenia dwóch plików (w tym przypadku dowolnych).

W [naszym poradniku](https://developer.allegro.pl/getting_started/#jak-uzyska%c4%87-token-dost%c4%99powy-do-api) udostępniliśmy kod, dzięki któremu wygenerujesz token. Zapoznaj się proszę również z naszym artykułem [Uwierzytelnianie i autoryzacja](https://developer.allegro.pl/auth/).

**Comment by EBeige** [comment]
Dzieki @Lukasz-Zurek,

Dane konta - sorry nie wiem co zrobic i co kliknąć. Potrzebuje dokładnej pomocy. Storna w chromie wygląda tak jak w załączniku (rozsypana) może to przez lang przeglądarki (en)

![image](https://user-images.githubusercontent.com/82169827/114139357-3ce2fc80-990f-11eb-9fa2-e196f011c574.png)

W poradniku jest tylko php, w uwierzytelnianiu znalazłem coś takiego:

![image](https://user-images.githubusercontent.com/82169827/114139447-5dab5200-990f-11eb-9278-725ba872436e.png)

W sumie muszę chyba to napisać, bo token jest ważny 12 godzin. tak? Ten token z paczkomatów - nie trzeba odświeżać tak często, prawda?

**Comment by Lukasz-Zurek** [comment]
@EBeige Spróbuj proszę otworzyć stronę w trybie incognito, lub w innej przeglądarce.

Jeżeli natomiast chodzi o access token, to potwierdzam, że ważny jest 12 godzin. Natomiast refresh token przedłuża ważność autoryzacji do 3 miesięcy.

Generalnie najlepiej będzie jak zapoznasz się dokładnie z różnymi typami autoryzacji, które opisaliśmy krok po kroku w [naszym poradniku](https://developer.allegro.pl/auth/).

**Comment by EBeige** [comment]
@Lukasz-Zurek nie pomaga - to chyba moje locale browsera. Powiedz proszę gdzie znajde tą opcję przesyłania plików, proszę?

Ten sandbocx trochę uciążliwy. Czyli zrobic create token i odświeżyć, wtedy spokój na 3 miesiące?

**Comment by michalpokora** [comment]
@Lukasz-Zurek mam dokładnie ten sam problem z wyglądem strony. Przeglądarka Chrome tryb normalny i incognito. To samo na Firefox i Opera.

**Comment by Lukasz-Zurek** [comment]
@EBeige Access token zawsze będzie ważny 12 godzin, ale masz 3 miesiące na to, aby go odświeżyć.

@EBeige @michalpokora Jeśli chodzi o wygląd strony na sandbox, faktycznie coś jest nie tak. Zweryfikujemy to po naszej stronie i wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@EBeige Problem dotyczący utrudnień na stronie: https://allegro.pl.allegrosandbox.pl/ zgłosiłem do odpowiedniego zespołu. Nie ma innej możliwości przesłania plików, w związku z czym proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
Strona powinna wyświetlać się prawidłowo, wdrożyliśmy poprawkę.

@EBeige Możesz już załączyć dokumenty.

Przepraszamy za zaistniałe utrudnienia.

**Comment by michalpokora** [comment]
@Lukasz-Zurek niestety dalej występuje błąd związany z wyświetlaniem strony. 
![image](https://user-images.githubusercontent.com/20809762/114166688-5b0c2500-992e-11eb-869e-49d52617e573.png)

**Comment by Lukasz-Zurek** [comment]
@michalpokora Dziękuję.  Zgłosiłem problem.

**Comment by Lukasz-Zurek** [comment]
@michalpokora Powinno być już ok.

**Comment by EBeige** [comment]
@Lukasz-Zurek Strona działa, dzięki ale nadal nie wiem o co come'on z tymi plikami, gdzie i co mam suploadowac? Proszę o pomoc.

**Comment by Lukasz-Zurek** [comment]
@EBeige Aby konto firmowe zostało zweryfikowane, konieczne jest przejście przez formularz na [stronie](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php). Na produkcji konieczne jest załączenie dokumentów firmowych, natomiast w wersji testowej sandbox wystarczy dodać dwa losowe pliki i kliknąć "Wyślij do weryfikacji".

**Comment by EBeige** [comment]
@Poszło, dzięki za info !
