### ISSUE TITLE
422 unprocessable entity "Provided image address is incorrect." with S3 hosted image

### ISSUE THREAD

**Issue by numerogeek** [allegro/allegro-api#4375]
Hello,

I have an error which came up suddenly.
I try to send you products through the REST API, and the API return 422 unprocessable entity with message : "Provided image address is incorrect."

what I send (part with image) : 
```
    "images": [
        {
            "url": "https:\/\/numiscorner.s3.eu-central-1.amazonaws.com\/83\/14\/62\/831462A.jpg"
        },
        {
            "url": "https:\/\/numiscorner.s3.eu-central-1.amazonaws.com\/83\/14\/62\/831462R.jpg"
        }
    ],
```

What I get : 

```

<<<<<<<<
HTTP/1.1 422 Unprocessable Entity
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: d900b60b64e1239d
date: Thu, 08 Apr 2021 21:27:52 GMT
x-content-type-options: nosniff
content-type: application/json
transfer-encoding: chunked

{"errors":[{"code":"VALIDATION_ERROR","message":"Provided image address is incorrect.","details":"","path":"","userMessage":"Provided image address is incorrect."}]}

```

thank you for your help

**Comment by Lukasz-Zurek** [comment]
You are providing incorrect image url. You should use: [POST /sale/images](https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST) first to upload images to our servers and receive suitable links which you will be able to use later.

**Comment by numerogeek** [comment]
@Lukasz-Zurek Hello, 

Thank you for your quick answer :)
Is that change is documented somewhere because my workflow haven't changed and the complete process stopped working few days ago.
I was using S3 images url  without problem until now.

**Comment by Lukasz-Zurek** [comment]
We did not change anything in our documentation. I've checked some logs and as I see - couple of days ago, you've received 422 errors with the same images problem. At the same time in requests with 200 status, you have provided correct images url.

**Comment by numerogeek** [comment]
@Lukasz-Zurek I don't understand : we did not implemented yet the images endpoint, we have sent S3 images on the offer body since the beggining and it was working. 
it just stopped working few days ago...
We are implementing it right now.

**Comment by Lukasz-Zurek** [comment]
@numerogeek Using: [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST), you have to provide images which you upload via: [POST /sale/images](https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST). You can add your own images only via: [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) but I cannot find any logs so I guess that you did not use it. Please check your application closely. I saw some 422 errors and images url were incorrect.

**Comment by numerogeek** [comment]
@Lukasz-Zurek I am pretty sur that I send something like 100.000 products on your API using S3 images in the offer in the past few months.
Could you please check the logs for this offer maybe ? https://allegro.pl/oferta/moneta-francja-louis-xiii-1-12-ecu-1643-paris-10009956589

**Comment by Lukasz-Zurek** [comment]
@numerogeek I understand that. Unfortunately we do not have logs for this offer, because it has been created quite long time ago. We do have logs from last two weeks so we will verify any new examples.

Did you use [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) previously ? It's essential because you can add your own images only with this resource.

**Comment by numerogeek** [comment]
@Lukasz-Zurek I am pretty sur yes, I fixed my code this morning and I double checked :)

**Comment by Lukasz-Zurek** [comment]
@numerogeek I have checked logs from 9.04 already and I see that you have used only: [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST) and you have provided incorrect images url, which can be added only with: [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers).

[POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST) - You have to upload images with:  [POST /sale/images](https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST)

[POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) - You can add direct images, for example: `url=https://numiscorner.s3.eu-central-1.amazonaws.com/83/14/58/831458A.jpg` ; I do not see that kind of requests from you in our logs. If you have some examples where do you use: [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) and you receive 422 errors, please let us know.

**Comment by numerogeek** [comment]
@Lukasz-Zurek I have fixed my connector last week.
I suggest you to have a look on the products that have been created in march 2021 if you have logs.
I was sending S3 urls in the /sale/offers endpoint, and it was working :) I'm pretty sure about that.

**Comment by Lukasz-Zurek** [comment]
@numerogeek We do have some logs but only from 28-29.03, unfortunately I cannot find anything which could be useful for verification.

However, it could be working correctly with your own image url for some time, but it should not and it could be our bug which we cannot verify right now. We have never had this functionality in: [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST), so 422 error status has been correct.

Of course I would like to apologize for any inaccuracies from our side which could be misleading.

**Comment by numerogeek** [comment]
Thank you :)
