### ISSUE TITLE
Allegro Kurier UPS (do 10 kg) - wartości w polach readyDate pickupDate, potwierdzenie odbioru POD

### ISSUE THREAD

**Issue by KrystianSart** [allegro/allegro-api#4378]
współpracujemy z UPS i mamy ustawione z nimi codzienne odbiory przesyłek

czy możemy oba pola nie przekazywać w żądaniu, jak w przypadkach opisanych dla Pocztexu/Poczty Polskiej
jeżeli musimy przekazywać pola w żądaniu to jakie mamy ustawiać wartości pola
**readyDate**
**pickupDate**

czy istnieje możliwość pobrania POD (potwierdzenie odbioru przez klienta) dla paczek - nie widzę żeby było opisane to w dokumentacji API

**Comment by Lukasz-Zurek** [comment]
Pole **readyDate** data określająca kiedy przesyłka będzie gotowa do odbioru.  Nie jest wymagane. Przekazujesz w nim datę w formacie YYYY-MM-DD.

Jeśli natomiast chodzi o **pickupDate** - musisz przekazać dokładnie te wartości, jakie uzyskałeś korzystając z: [GET /parcel-management/pickup-date-proposals](https://developer.allegro.pl/documentation/#operation/getParcelsPickupDateProposals)

Nie ma możliwości pobrania POD przez nasze API.

Więcej informacji na temat zarządzania przesyłkami przez "Wysyłam z Allegro" znajdziesz w [naszym poradniku](https://developer.allegro.pl/wza/).

**Comment by Lukasz-Zurek** [comment]
@KrystianSart Tak, dane te są wymagane.

**Comment by KrystianSart** [comment]
@Lukasz-Zurek dziękuję za informacje

**Comment by KrystianSart** [comment]
w trakcie integracji, nasz programista natrafił prawdopodobnie na błąd po stronie API-allegro
w zał podsumowanie "błędu" oraz kod
[allegro.zip](https://github.com/allegro/allegro-api/files/6441488/allegro.zip)
[podsumowanie.txt](https://github.com/allegro/allegro-api/files/6441489/podsumowanie.txt)

**Comment by AureliuszBrussy** [comment]
Dziękuję za przekazane dane. Zgłosiłem ten problem do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@KrystianSart wartość w polu **sender.name** oraz **pickup.name** nie jest wymagana, ale oczekujemy w nich ciągu znaków co najmniej dwuczłonowego (imię/imiona oraz nazwisko osoby). Rozumiem natomiast, że komunikaty błędów w tych przypadkach są nieprawidłowe - wdrożymy odpowiednią poprawkę.
