### ISSUE TITLE
[ sandbox ] Produkty dostępne do połączenia z ofertą

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#4379]
Jaki czas temu na stronie https://developer.allegro.pl/productization/#sandbox była dostępna lista produktów z nazwami i nr EAN które można było wykorzystać podczas wystawiania oferty do połączenia jej z produktem. Czy aktualnie dostępna jest taka lista? Potrzebuję nr EAN , ISBN i nazwy produktów do testów.

**Comment by Lukasz-Zurek** [comment]
Tak, usunęliśmy tę listę z powyższej strony. 

Poniżej podaję **product.id** do testów:

354f011f-c9c5-4cf2-9b35-5ce45d669d02
09cbf1ce-c836-4761-ba34-25e334c07300
0cb89863-9bd0-4f92-b364-16ec3908201c
