### ISSUE TITLE
Sandbox niespójność między metodami doCheckNewAuctionExt a doNewAuctionExt

### ISSUE THREAD

**Issue by j4r3kb** [allegro/allegro-api#438]
Dla kategorii Bilety/Pozostałe
w formularzu kosztów dostawy mam wypełnione pole 340 (czas wysyłki).
Metoda **doCheckNewAuctionExt** zwraca mi błąd:

"Wysyłka w ciągu - pole formularza sprzedaży nie jest dostępne w wybranej kategorii."

po usunięciu pola 340 przechodzę dalej do metody **doNewAuctionExt**
i otrzymuję błąd:

"ERR_CONSTRAINT_VIOLATION_EXCEPTION_REQUIRE_ESTIMATED_SHIPPING_TIME / Podaj czas wysyłki. Czas wysyłki nie może być pusty."

po ponownym dodaniu tego pola mam z kolei:

"ERR_FULFILLMENT_TIME_NOT_AVAILABLE_FOR_CATEGORY / Wysyłka w ciągu - pole formularza sprzedaży nie jest dostępne w wybranej kategorii. / doNewAuctionExt - Fulfillment time is not available for the selected category."

**Comment by MarcinLuczak** [comment]
@j4r3kb metoda doCheckNewAuctionExt nie służy już do sprawdzania poprawności oferty. Obecnie za jej pomocą sprawdzisz tylko ogólne oraz szczegółowe kosztów związane z wystawieniem oferty przed jej faktycznym wystawieniem. Dlatego może wystąpić niespójność pomiędzy tą metodą, a doNewAuctionExt.

Od razu dodam, że w październiku 2018 oznaczmy metody WebAPI do obsługi oferty jako deprecated. Dlatego warto zacząć korzystać z zasobów w REST API, które służą do obsługi oferty. Opisaliśmy je w [tym poradniku](https://developer.allegro.pl/sale/).
