### ISSUE TITLE
invalid_grant - Invalid refresh token:

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#4380]
Czy wprowadzono jakies zmiany w metodach ? od 7ego w aplikacji mam błędy typu:
AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Exception: invalid_grant - Invalid refresh token:

**Comment by AureliuszBrussy** [comment]
Nie wprowadziliśmy żadnych zmian w metodach autoryzacji. Prześlij proszę przykładowy request (zachowaj w nim cały refresh token) w formacie cURL przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pozwoli nam to wskazać bezpośrednią przyczynę błędu. Pamiętaj proszę, aby w zgłoszeniu dopisać, że dane dotyczą wątku GitHub #4380.

**Comment by hahyes** [comment]
> Czy wprowadzono jakies zmiany w metodach ? od 7ego w aplikacji mam błędy typu:
> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Exception: invalid_grant - Invalid refresh token:

Wyłapujesz błędy >=500 od nich? Zwykle widziałem takie sytuacje, gdzie serwer autoryzacji wyrzucił błąd 500 i widocznie unieważnił token gdzieś przed wyrzuceniem błędu. Wtedy miałem też komunikat o nieprawidłowym tokenie odświeżenia.
