### ISSUE TITLE
Trudność ze znalezieniem w dokumentacji wartości dla pola "Reference number (optional)"

### ISSUE THREAD

**Issue by awiaderny** [allegro/allegro-api#4381]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbóję dodać w kodzie używającym `API Allegro` możliwość automatycznego wystawiania aukcji za pomocą skryptu i interesuje mnie pole / input `Reference number (optional)` (w tłumaczeniu na języka polski: ``) poniżej wysyłam `screen`.

`screen` dla wersji po angielsku:
![image](https://user-images.githubusercontent.com/35666447/114207522-bf45dd80-995c-11eb-88db-bcec7cebbcb4.png)

`screen` dla wersji po polsku:
![image](https://user-images.githubusercontent.com/35666447/114208834-3760d300-995e-11eb-8597-aec3a5c1ec70.png)

Problem jest, bo nie mogę znaleźć w dokumentacji `API Allegro` informacji jak się nazywa to pole.
Jedyne co udało mi się znaleźć to np. pod linkiem:
[https://developer.allegro.pl/documentation/#operation/createNewParcel
](https://developer.allegro.pl/documentation/#operation/createNewParcel
) Jest `label.referenceNumber` - ale mnie interesuje wartość dla `Create offer based on product` z sekcji:
[https://developer.allegro.pl/documentation/#operation/createProductOffers
](https://developer.allegro.pl/documentation/#operation/createProductOffers
)
Ponieważ chce wystawić aukcje.

Czy byłaby możliwość dodania / wskazania tego pola w dokumentacji `API Allegro`?
A jeśli już istnieje to proszę o wskazanie która to jest wartość.

Korzystam z wersji `sandbox Allegro`

**Comment by Lukasz-Zurek** [comment]
Pole odpowiadające za sygnaturę w naszym API to **external.id**. Możesz go użyć korzystając właśnie m.in. z: [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers).

Więcej informacji znajdziesz w [poradniku](https://developer.allegro.pl/product_offers/#jak-doda%c4%87-sygnatur%c4%99).
