### ISSUE TITLE
API Allegro - status aukcji

### ISSUE THREAD

**Issue by xVinniVx** [allegro/allegro-api#4382]
Witam,
mam pewien problem i nie wiem jak go ugryźć.

Poprzez **/sale/offers/{offerId}** mogę sprawdzić szczegóły wystawionej oferty. W dziale **['publication']['status']** mam wypisany stan aukcji: "INACTIVE" "ACTIVATING" "ACTIVE" "ENDED" a w polu **['publication']['endedBy']** dlaczego została oferta zakończonaa: "USER" "ADMIN" "EXPIRATION" "ERROR"..

I teraz moje pytanie: **_Jak sprawdzić, czy dana aukcja - wystawiona jedynie z parametrem KUP TERAZ (bez licytacji, etc) została KUPIONA przez kogoś?_**

Czyli czy da się pobrać przez ID aukcji informację o tym, czy została zakończona sprzedażą, a nie wygaśnięciem / zamknięciem przez użytkownika / administratora Allegro?

Czy taka opcja w API istnieje? 
Jeżeli tak - mogę otrzymać wskazówki, jak to zrobić?
Przeglądam dokumentację i nie widzę tego....

**Comment by Lukasz-Zurek** [comment]
Generalnie jeżeli sprzedałeś w ofercie ostatnią sztukę, czyli zakup Klienta zakończył ofertę - status w polu **['publication']['endedBy']** powinien mieć wartość: **"EXPIRATION"**. Możesz skorzystać również z: [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET). Dla wybranej oferty znajdziesz zdarzenie, dzięki któremu potwierdzisz, czy oferta została zakończona i z jakiego powodu, np. **"endedBy": "EXPIRATION**";  **"type": "OFFER_ENDED"**.

Więcej informacji o dzienniku zdarzeń w ofertach znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/).
