### ISSUE TITLE
Provided ISBN is not equal with any ISBN assigned to the product.

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4383]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas tworzenia szkicu oferty otrzymujemy błąd: "Provided ISBN is not equal with any ISBN assigned to the product". W parametrach szkicu przekazujemy parametr ISBN z wartością 9780521146135.  Szkic dotyczy eanu 9780521146135 na podstawie którego, za pomocą zasobu **sale/products?ean=9780521146135**, został odnaleziony produkt a następnie jego id zostało dołączone do draftu. Gdy za pomocą zasobu **sale/products/ba7e5c55-a474-4b78-8c4e-d2d259a12eec** pobieramy szczegóły tego produktu to w jego parametrach jest parametr ISBN ale z wartością 9781107694286. 

W jaki sposób jest wyszukiwany produkt skoro wartość szukana, a wartość parametru produktu się różni?
Dołączam request i response w/w zasobów. 
[zasób 1.txt](https://github.com/allegro/allegro-api/files/6291540/zasob.1.txt)
[zasób 2.txt](https://github.com/allegro/allegro-api/files/6291541/zasob.2.txt)

**Comment by Lukasz-Zurek** [comment]
Jest to błąd, który zgłosiliśmy już wcześniej do zespołu odpowiedzialnego za tę funkcjonalność.

Przepraszamy za utrudnienia.
