### ISSUE TITLE
Problem z przesłaniem zdjęć przy /sales/offers

### ISSUE THREAD

**Issue by tomaszk23** [allegro/allegro-api#4384]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Mam problem z wystawieniem oferty ze zdjęciem. Zaraz po wysłaniu POSTa na /sales/offers dostaję taką odpowiedź: 

{"errors":[{"code":"VALIDATION_ERROR","message":"Provided image address is incorrect.","details":"","path":"","userMessage":"Provided image address is incorrect."}]}

Sprawdzałem na kilku obrazkach, zarówno w środowisku testowym, jak i produkcyjnym - żaden request nie przechodzi. Jeszcze w styczniu tego roku ten sam kod działał bez problemu. Zdjęcia idą z mojego serwera (nie przez serwer zdjęć Allegro) - sprawdzałem na takich wrzucanych na serwer przed chwilą i takich, które jakiś czas tam leżą - w obu przypadkach efekt jest ten sam. Obrazki są bez problemu dostępne z poziomu przeglądarki po wpisaniu rzekomo "błędnego" URL-a.
 
Przy okazji - wysłałbym request i odpowiedź, zgodnie z sugestią, przez formularz kontaktowy, ale po wybraniu odpowiedniej kategorii na stronie https://allegro.pl/pomoc/kontakt jestem kierowany z powrotem tutaj. W jaki sposób mogę je wysłać inaczej niż publikując na otwartym forum?

I jeszcze jedno pytanie, z innej beczki - jakiś czas temu na Sandboxie zmieniałem dane kontaktowe, m.in. podane imię i nazwisko, ale do tej pory zmiana nie została zatwierdzona. Czy jest możliwość, żeby to przeprocesować?

**Comment by AureliuszBrussy** [comment]
Gdy korzystasz z POST na zasobie /sales/offers, użyte podczas podczas tej operacji zdjęcia musisz najpierw upladować na serwer Allegro za pomocą [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST). W [naszym poradniku](https://developer.allegro.pl/sale/#5-zdj%c4%99cia) opisujemy cały proces.

Zdjęcia z zewnętrznego serwera możesz użyć tylko, gdy skorzystasz z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/getPromoModificationCommandDetailedResultUsingGET) i [PATCH
/sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers). Więcej o tym dowiesz się w [poradniku](https://developer.allegro.pl/product_offers/#jak-doda%c4%87-w%c5%82asne-zdj%c4%99cie-do-oferty).

Czy możesz podać numer zgłoszenia z formularza?

W kwestii konta na Sandboxie - podaj proszę login tego konta. Sprawdzę sytuację.

**Comment by hahyes** [comment]
> Gdy korzystasz z POST na zasobie /sales/offers, użyte podczas podczas tej operacji zdjęcia musisz najpierw upladować na serwer Allegro za pomocą [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST). W [naszym poradniku](https://developer.allegro.pl/sale/#5-zdj%c4%99cia) opisujemy cały proces.
> 
> Zdjęcia z zewnętrznego serwera możesz użyć tylko, gdy skorzystasz z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/getPromoModificationCommandDetailedResultUsingGET) i [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers). Więcej o tym dowiesz się w [poradniku](https://developer.allegro.pl/product_offers/#jak-doda%c4%87-w%c5%82asne-zdj%c4%99cie-do-oferty).
> 
> Czy możesz podać numer zgłoszenia z formularza?
> 
> W kwestii konta na Sandboxie - podaj proszę login tego konta. Sprawdzę sytuację.

Według wypowiedzi innego pracownika: https://github.com/allegro/allegro-api/issues/4375
nie można wykorzystać zewnętrznych linków w POST /sale/product-offers. Dziwne.

**Comment by AureliuszBrussy** [comment]
@hahyes z tego co widzę, Łukasz w wątku #4375 dawał znać, że w POST /sale/product-offers można korzystać z linków z serwerów zewnętrznych. Nie można tego jednak robić na zasobie /sales/offers.

**Comment by tomaszk23** [comment]
@AureliuszBrussy ok, rozumiem, jednak jeszcze w styczniu ten sam kod wysyłał zdjęcia z URL-ami z zewnętrznego serwera  przez /sale/offers bez konieczności odpalania /sale/images wcześniej. Nie widzę informacji o takiej zmianie w changelogu - czy to jest coś co weszło w życie przy okazji innych modyfikacji? 

Login mojego sandboxowego konta Allegro jest taki sam jak tutaj: tomaszk23. Jeżeli chodzi o namiar na formularz kontaktowy, to nie wysyłałem nic, gdyż po wyborze "API" z kategorii w wizardzie jestem kierowany bezpośrednio tutaj :) Niemniej nie powinno być takiej potrzeby jeżeli chodzi o dodanie wywołania /sale/images. 

Dzięki!

**Comment by AureliuszBrussy** [comment]
@tomaszk23 taka sytuacja nie powinna mieć nigdy miejsca - na zasobie /sales/offers zawsze dopuszczaliśmy możliwość wykorzystania w ofercie url do zdjęć tylko z naszego serwera. 

Co do konta na Sandboxie - z tego co widzę, ostatnie zmiany zostały wprowadzone, aktualnie nie widzę żadnych niepotwierdzonych zmian.

**Comment by tomaszk23** [comment]
@AureliuszBrussy najwyraźniej przez ostatni rok tak nie było - sprawdziłem kod i nie mam wywołań "/sale/images" - zdjęcia do tej pory były przekazywane jako URL-e w ofercie i zapewne taka możliwość była opisana w dokumentacji. Przeszło przez ten proces ok. 500 ofert na obu środowiskach na przestrzeni roku, więc to raczej nie przypadek. Przypuszczam, że było to po prostu ułatwienie, które ktoś usunął przy okazji ostatnich modyfikacji. 
Jeżeli chodzi o konto na Sandboxie, to nadal widzę komunikat przy nazwisku: "Dane niepotwierdzone. Sprawdzamy czy wszystko się zgadza.", więc prawdopodobnie jeszcze to trzeba gdzieś potwierdzić.

**Comment by AureliuszBrussy** [comment]
@tomaszk23 możliwość przekazywania zdjęć z zewnętrznych źródeł nigdy nie była planowaną funkcjonalnością na zasobie /sale/offers. Założenie od początku jest takie samo i - tak jak piszemy w dokumentacji - przed wykorzystaniem zdjęcia w ofercie, niezbędne jest wysłanie go na nasz serwsem poprzez POST /sale/images.

Dane na koncie tomaszk23 są już zmienione.
