### ISSUE TITLE
Wygenerowany json nie dziala przy wystawieniu aukcji z pliku

### ISSUE THREAD

**Issue by kraczo** [allegro/allegro-api#4385]
Hej, wygenerowalem sobie poprzez api JSONa, teraz chce to pliku excela skopiowac description tak abym mogl generowac aukcje z pliku, przy probie importu dostaje komunikat 
- Błędny tag "h1", dozwolone są: {b}

jednak w opisie https://developer.allegro.pl/sale/ punkt 6 
jest opisane ze mozna h1 uzywać, rowniez skoro jest to json wygenerowany z dzialajacej aukcji dlaczego dotaje bledy ? 
po usunieci h1 dostalem taki sam komunikat tylko z p ? 

Pozdrawiam
Dawid

**Comment by AureliuszBrussy** [comment]
W API Allegro w opisie możesz skorzystać ze znaczników `<h1>, <h2>, <p>, <ul>, <ol>, <li>, <b>`. Rozumiem, że chodzi tutaj o [wystawienie oferty z pliku](https://allegro.pl/moje-allegro/sprzedaz/wystaw-z-pliku)? Jeżeli tak - problemy takie zgłaszaj proszę poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
