### ISSUE TITLE
API - pobieranie ofert, na których nic się nie sprzedało w danym okresie czasu

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4386]
W jaki sposób poprzez API mogę pobrać oferty, na których nie było ofert kupna przez ostatnie 10 miesięcy bądź np. przez ostatnie 12 miesięcy ? Chodzi o to, że za takie oferty są naliczane dodatkowe opłaty i chcemy móc je wychwytywać. Z tego co wiem to takie narzędzia jak Baselinker chyba jakoś to robią to znaczy, że chyba jest to możliwe poprzez API ?

**Comment by pietrach** [comment]
Ewentualnie jeśli nie da się pobrać listy takich ofert to może pobierając wybraną ofertę jesteśmy w stanie to sprawdzić za pomocą jakiejś metody API, że za np. 2 miesiące będzie naliczona opłata jeśli nic się nie sprzeda itp.

**Comment by kfijalko** [comment]
https://developer.allegro.pl/charges/#data-naliczenia-kolejnej-op%C5%82aty

**Comment by PrzemyslawLukanowski** [comment]
Przez API zwracamy tylko informację na temat sprzedaży z ostatnich 30 dni. Znajdziesz ją w polu stock.sold w odpowiedzi dla GET /sale/offers?offer.id={offerID}. Datę naliczenia kolejnej opłaty dla danej oferty sprawdzisz za pomocą [GET /pricing/offer-quotes](https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET), o czym wyżej wspomniał kfijalko.

**Comment by pietrach** [comment]
Ok, dzięki to w takim razie co trzeba zrobić aby uniknąć opłaty za to, że przez ostatnie 12 miesięcy nic się nie sprzedało w danej ofercie ? Czy wystarczy zakończyć taką ofertę i ją wznowić ponownie czy może trzeba ją całkowicie zakończyć i wystawić zupełnie nową ofertę pod nowym numerem ?

**Comment by kfijalko** [comment]
Musisz ponownie wystawić [nowy numer oferty]. Jak zakończysz to wstrzymasz licznik, po wznowieniu licznik dalej liczy.

**Comment by pietrach** [comment]
A co oznacza pole "enabled" w strukturze "quotes" ?

**Comment by PrzemyslawLukanowski** [comment]
@pietrach Pole "enabled" oznacza status opłaty, wartość true - że jest ona aktywna.
