### ISSUE TITLE
Oryginał zdjęcia aukcji

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#439]
W jaki sposób mam pobrać oryginał zdjęć wystawionych przez siebie aukcji? I nie mówię tu o zmodyfikowanych przez steganografię zdjęciach takich jak [to](https://d.allegroimg.com/original/017bb8/b96ea2004fe18a8fb94cffceb72d); chcę pobrać to zdjęcie, które przesłałem do allegro.

**Comment by MarcinLuczak** [comment]
@TimothyKoval nie ma możliwości, aby pobrać . Oryginał zdjęć masz tylko zanim je dodasz na nasz serwer.
