### ISSUE TITLE
Metoda POST /payments/refunds możliwa tylko przy parametrze listItems->type = 'GUANTITY'

### ISSUE THREAD

**Issue by olgazawislakgc** [allegro/allegro-api#4391]
Dla api.allegro.pl.allegrosandbox.pl metoda POST /payments/refunds umożliwa zwrot płatności tylko dla parametru type = 'QUANTITY' w parametrze listItems. Dla type = 'AMOUNT' response zwraca odpowiedź:
{
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Niewłaściwy format parametru",
            "details": "Invalid value: null",
            "path": "lineItems.value",
            "userMessage": "Niewłaściwy format parametru"
        }
    ]
} 
dla takiej samej struktury requestu z podaniem 'value' zamiast ' quantity' (zgodnie z dokumentacją)

**Comment by Lukasz-Zurek** [comment]
Błąd jest uzasadniony, ponieważ w polu **“quantity”** wprowadzasz wartość **"null"**, a powinieneś przekazać liczbę przedmiotów, za które chcesz wykonać zwrot płatności.

Więcej informacji na temat: [POST /payments/refunds](https://developer.allegro.pl/documentation/#operation/initiateRefund) znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#jak-wykona%c4%87-zwrot-p%c5%82atno%c5%9bci).

**Comment by Lukasz-Zurek** [comment]
Chciałbym od razu sprostować moją wcześniejszą odpowiedź. 

Dla "type": **"AMOUNT"** otrzymujesz błąd, ponieważ przekazujesz pole: **"value"**, a powinieneś przekazać: **"amount"**. Przykład znajdujący się w [naszej dokumentacji](https://developer.allegro.pl/documentation/#operation/initiateRefund) dotyczy tylko przypadku, w którym jako wartość pola **"lineItems.type"**, podajesz **"QUANTITY"**. Natomiast przykład dotyczący **"AMOUNT"** opisaliśmy w [poradniku](https://developer.allegro.pl/orders/#jak-wykona%c4%87-zwrot-p%c5%82atno%c5%9bci).
