### ISSUE TITLE
Wartości parametru "range"

### ISSUE THREAD

**Issue by Slpw20** [allegro/allegro-api#4394]
Czy parametr typu "range" przyjmuje jedynie wartości typu integer, czy również inne, na przykład string?

**Comment by Lukasz-Zurek** [comment]
Zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1), parametr typu **"range"** przyjmuje wartość dla typu **"integer"** oraz **"float"**. Nie przyjmuje natomiast dla typu **"string"** i **"dictionary"**.
