### ISSUE TITLE
PUT /sale/offers/{offerId} Kod odpowiedzi

### ISSUE THREAD

**Issue by TomaszSzydlowski-sudo** [allegro/allegro-api#4396]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Endpoint PUT /sale/offers/{offerId} zwraca kod 200, a zwracana encja nie zawiera zmiany.
Próbowałem zmienić publication.status na ACTIVE, dostałem odpowiedz 200, a publication.status się nie zmienił.

**Comment by PrzemyslawLukanowski** [comment]
Ofertę aktywujesz/zakończysz za pomocą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT), w [naszym poradniku](https://developer.allegro.pl/sale/#12-publikacja-oferty) znajdziesz więcej informacji na ten temat.

**Comment by TomaszSzydlowski-sudo** [comment]
@PrzemyslawLukanowski W takim razie nie powinienem dostać kodu 200 w odpowiedzi.

**Comment by PrzemyslawLukanowski** [comment]
Z powodów technicznych przyjęliśmy takie założenie, aby w tym przypadku ignorować zmianę statusu publikacji, jeśli jest ona wykonana przez PUT /sale/offers/{offerID}. Tak jak wspomniałem, dedykowanym zasobem do tej operacji jest /sale/offer-publication-commands/{commandId}.
