### ISSUE TITLE
/offers/{offerId}/change-price-commands/{commandId} - ceny poniżej 1 zł

### ISSUE THREAD

**Issue by AptusShop** [allegro/allegro-api#44]
Nasz klient ma bardzo specyficzny asortyment, gdzie wiele produktów ma ceny poniżej 1 zł.
Niestety, próba zmiany cen na < 1 kończy się błędem

Wysyłamy
array(1) {
  ["input"]=>
  array(1) {
    ["buyNowPrice"]=>
    array(2) {
      ["amount"]=>
      string(4) "0.69"
      ["currency"]=>
      string(3) "PLN"
    }
  }
}

Odpowiedź:
 Enter a correct price. Make sure that the specified price does not contain letters. Recommended price format: 0.00 

Dla cen > 1 - funkcja działa bez problemu

**Comment by KrzysztofLukanowski** [comment]
W Allegro nie możesz określić ceny dla pojedynczego przedmiotu poniżej 1 zł. Jeżeli klientowi zależy na prezentacji niskiej ceny towaru, warto rozważyć sprzedaż takich przedmiotów w zestawach.

**Comment by AptusShop** [comment]
Ale wystawić się da :)

**Comment by KrzysztofLukanowski** [comment]
Nie, nie da się określić ceny < 1zł. Zarówno podczas wystawiania, jak i edycji ceny oferty.

**Comment by AptusShop** [comment]
Ok, rozumiem, za bardzo się wymianą informacji z klientem zasugerowałem.
