### ISSUE TITLE
Bug w /sale/offers/{id}

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#440]
Dzień Dobry,
zapytanie GET https://api.allegro.pl/sale/offers/5736193548 zawsze zwraca:

{"errors":[{"code":"NOT_FOUND","message":"Not Found","details":null,"path":"/sale/offers/5736193548","userMessage":null}]}

Oferta istnieje na Allegro, do tego oferty ze starym opisem już podobno nie istnieją na Allegro, więc nie widzę powodu, aby ten endpoint nie pokazał tej aukcji. Proszę spróbować z dowolnym access tokenem.

**Comment by PawelTaberski** [comment]
Tym zasobem nie pobierzesz oferty ze starym opisem, a widzę że podana przez Ciebie oferta ma jeszcze stary opis.

**Comment by amarel123** [comment]
@PawelTaberski Przecież tutaj https://github.com/allegro/allegro-api/issues/412 rozmawialiśmy, że te aukcje znikną po 23 lipca. Więc nie rozumiem.
