### ISSUE TITLE
Problem z brakującymi zamówieniami API Allegro order/events

### ISSUE THREAD

**Issue by webtsx** [allegro/allegro-api#4400]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ x] inny

Witam, mam problem z brakującymi zamówieniami. Mam uruchomionego crona, który sprawdza czy są nowe zamówienia wg. kryteriów, ale niestety jest problem, że zamowienia, które są dostępne przez strone nie są dostępne przez API. Po pobraniu listy zamówień powinny być wszystkie, ale niestety brakuje nowych(opłaconych). Wcześniej to działało. 
Parę dni temu podobną sytuację miałem, ale myślałem, że to błąd w kodzie. Dzisiaj miałem podobną sytuację i jak wyświetliłem zamówienia to nie było tego, które wpadło 40 minut przed sprawdzeniem. 

Dane o zamówieniach pobieram z https://api.allegro.pl/order/events , generalnie pobierając te ze statusem READY_FOR_PROCESSING i w szczegółach zamówienia fulfillment->status = NEW. 
Chociaż na potrzeby sprawdzenia czy wogóle doszło nowe zamówienie sprawdziłem zamówienia z różnymi statusami, ale niestety zamówienia tam nie było. 
Wysłać na formularz kontaktowy listę zamówień, którą dostałem w responsie ?

**Comment by Lukasz-Zurek** [comment]
Tak, najlepiej będzie jak prześlesz request i response wraz z trace-id przez nasz formularz kontaktowy. W zgłoszeniu dopisz GitHub #4400.

**Comment by Lukasz-Zurek** [comment]
@webtsx Nasze API prawidłowo zwraca najnowsze, wskazane przez Ciebie zamówienie.

Za pomocą [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) domyślnie pobierzesz listę 100 najstarszych zdarzeń, w związku z czym jeśli tych zdarzeń było więcej - nie znajdziesz wśród nich najnowszego zamówienia, etc. Chyba, że skorzystasz np. z parametru **limit**, określając liczbę zdarzeń (w tym przypadku zwiększając ją).

Filtrując po: **type=READY_FOR_PROCESSING** również powinieneś otrzymać wskazane zamówienie, podobnie jak w przypadku skorzystania z: [GET order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET), filtrując po: **fulfillment.status=NEW**

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#zam%c3%b3wienia-w-allegro-rest-api).

**Comment by webtsx** [comment]
Dzięki za odpowiedź. 
Spróbuję poprawić kod zgodnie z Twoją sugestią.
