### ISSUE TITLE
Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 203093

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#4401]
W parametrach produktu z zapytania /sale/categories/5547/product-parameters, parametr 203093 opisany jest następująco:
{
      "id": "203093",
      "name": "Długość wkładki",
      "type": "float",
      "required": true,
      "unit": "cm",
      "restrictions":       {
         "min": 0,
         "max": 40,
         "range": false,
         "precision": 2
      }

W metodzie /sale/product-proposals  wysyłam parametr 203093 opisany tak:

                (
                    [id] => 203093
                    [values] => Array
                        (
                            [0] => 28
                        )
                    [valuesIds] => Array
                        (
                        )
                    [rangeValue] => 
                )
i w odpowiedzi dostaję błąd:
Object
                (
                    [code] => ParameterException.InvalidParameterDtoException
                    [message] => An error has occurred
                    [details] => 
                    [path] => parameters
                    [userMessage] => Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 203093.
                )

Ktoś może mi powiedzieć gdzie jest błąd, tak samo zdefiniowany parametr wysyłam przy tworzeniu oferty i błąd nie występuje.

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć Twojego błędu, czy możesz w takim razie podać trace-id wywołania, tak abyśmy mogli przeanalizować Twój request?

**Comment by SlawomirMizerski** [comment]
trace-id: db9ea711df9344e3

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie mamy w naszych logach pełnych danych Twojego requestu. Prześlij go proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz, że dane dotyczą wątku #4401 na GitHubie. Przepraszam za utrudnienia.
