### ISSUE TITLE
W jaki sposób utrzymać wartość parametrów aukcji przy PATCH product.id?

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4402]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Cześć 👋 

Jestem w trakcie pisania rozwiązania do mapowania aukcji klienta, do produktów z katalogu Allegro, wszystko jest ok do czasu gdy chcemy utrzymać parametry produktu. Parametry produktu zwraca nam `sale/offers/{offerId}`, potem przekazujemy je do:

`$offer->product->parameters = $offerDetails->parameters;`

niestety zwrotka to:

> Błędnie przesłano definicje parametru `11323:Stan` jako parametr w sekcji `product`.

Zakładam, że część z parametrów powinna iść do... 

`$offer->parameters`

a część do

`$offer->parameters->product`?

Jeśli tak... to jak to przefiltrować odpowiednio?

trace-id: `86c5e5f502a9ea00`

**Comment by Lukasz-Zurek** [comment]
Tak, zgodnie z dokumentacją, jeśli korzystasz z: [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), powinieneś pamiętać o rozróżnieniu parametrów produktowych od ofertowych. 

W podanych przez Ciebie przykładzie widać, że parametr ofertowy: **"id": "11323"** przekazujesz w obiekcie **"product"**, a powinieneś przekazać w obiekcie **"parameters"**.

Wykorzystaj [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), by pobrać parametry dla wybranego produktu. Wartość **true** w polu: **"options.describesProduct"** oznacza, że dany parametr jest produktowy.

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/).

**Comment by kpodemski** [comment]
Dzięki 👍
