### ISSUE TITLE
Pomoc w dodawaniu przesyłek na wysylam.allegro.pl.allegrosandbox.pl

### ISSUE THREAD

**Issue by 0xceba** [allegro/allegro-api#4403]
Cześć,

To jest pytanie o Allegro Sandbox. Jeśli jest bardziej odpowiednie miejsce, aby zadać to pytanie, daj mi znać.

Chcę dodać przesyłki do moich zamówień z https://wysylam.allegro.pl.allegrosandbox.pl/konto/zamowienia. Kiedy dodam przesyłkę, otrzymuję informację:

> Kupujący wybrał Paczkomaty InPost. Aby wysłać przesyłkę tą metodą [dodaj umowę własną](https://wysylam.allegro.pl.allegrosandbox.pl/konto/przewoznicy/dodaj). Jeśli nie chcesz dodawać umowy, skorzystaj z [Managera Paczek Inpost](https://manager.paczkomaty.pl/).

Nie mogę przejść dalej niż ten krok. Próbowałem następujących rzeczy:

- **Dodanie umowy:** umowy wymagają płatnej subskrypcji w firmie kurierskiej, takiej jak DHL, GLS itp. Czy istnieją poświadczenia testowe, których mógłbym użyć w piaskownicy dla jednej z tych firm kurierskich?

- **Dodanie umowy Inpost ShipX:** Wygenerowałem klucz API Inpost ShipX pod adresem https://manager.paczkomaty.pl/account/api: 
![shipx_api_key](https://user-images.githubusercontent.com/44234156/115002764-65d23700-9ea5-11eb-9ec5-64f759aeaa74.png)
Otrzymuję komunikat o błędzie lub odpowiedź HTTP 500, gdy próbuję dodać klucz do Allegro pod adresem [https://wysylam.allegro.pl.allegrosandbox.pl/konto/przewoznicy/dodaj/inpost](https://wysylam.allegro.pl.allegrosandbox.pl/konto/przewoznicy/dodaj/inpost):
![shipx_submit](https://user-images.githubusercontent.com/44234156/115002990-a2059780-9ea5-11eb-9266-86cd2be6e77e.png)

- **Korzystanie z Managera Paczka Inpost:** Uważam, że aby skorzystać z tej funkcji, muszę zaimportować zamówienia z Allegro do Inpost. Poniższa strona w Inpost generuje kod autoryzacyjny:
![inpost_import](https://user-images.githubusercontent.com/44234156/115004088-bc8c4080-9ea6-11eb-9cf1-43829983dd19.png)
Kod autoryzacyjny jest mi przekazywany w linku takim jak [https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=111aaabbb](https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=111aaabbb). Kiedy próbuję użyć tego kodu w piaskownicy, pojawia się następujący błąd:
![inpost_import_error](https://user-images.githubusercontent.com/44234156/115004298-f4938380-9ea6-11eb-99e4-f814cb5f23e9.png)

Jak mogę skorzystać z jednej z tych funkcji, aby móc dodawać przesyłki przez wysylam.allegro.pl.allegrosandbox.pl?

**Comment by Lukasz-Zurek** [comment]
Sprawę skonsultuję i wrócę wkrótce z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@0xceba W sprawie uzyskania klucza do testowania umowy własnej, musisz zwrocić się do swojego opiekuna w firmie Inpost.

**Comment by 0xceba** [comment]
Dziękuję Ci.
