### ISSUE TITLE
POST /sale/badges - średnia cena rynkowa

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4406]
Podczas zgłaszania ofert do SALE trzeba podać cenę promocyjną i średnią cenę rynkową. Pytanie jak poprzez API pobrać średnią cenę rynkową ? Bo podczas ręcznego zgłaszania do wyprzedaży w panelu Allegro jest ta cena podpowiadana bodajże.

**Comment by Lukasz-Zurek** [comment]
Nie pobierzesz średniej ceny rynkowej poprzez nasze API. Pamiętaj jednak, że podana cena nie może być wyższa niż średnia cena sprzedaży oferty za ostatnie 30 dni. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/badge/).

**Comment by pietrach** [comment]
Trochę dziwne bo Allegro w panelu podpowiada czyli gdzieś musi mieć taką informację

**Comment by pietrach** [comment]
Brak średniej ceny do pobrania powoduje, że my nie wiemy co wpisać w cenę rynkową przy zgłaszaniu i mamy przez to wiele błędów.
Trochę słabo to rozwiązane bo trzeba zgadywać cenę.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za przesłane uwagi. Jednakże jak już wspomniałem wcześniej, nie udostępniamy niestety takiej możliwości w naszym API.
