### ISSUE TITLE
GET /sale/offers brak wartości watchersCount i visitsCount

### ISSUE THREAD

**Issue by netilmedia** [allegro/allegro-api#4407]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Podczas pobierania danych GET /sale/offers pola stats.watchersCount i stats.visitsCount dla wszystkich ofert zwracają wartość 0.

**Comment by arcziii** [comment]
U mnie również występuje wspomniany powyżej problem, środowisko produkcyjne.

**Comment by Lukasz-Zurek** [comment]
@netilmedia @arcziii Dziękuję za przesłane zgłoszenia. Problem przekazałem dalej do weryfikacji.

**Comment by netilmedia** [comment]
@Lukasz-Zurek Witam, czy coś wiadomo w tej sprawie? Rozumiem, że podobnych zgłoszeń jest wiele. Chciałbym jedynie wiedzieć czy możemy liczyć na przywrócenie tych danych. Z punktu widzenia naszej aplikacji są one ważne. Dziękuję za poświęcony czas.

**Comment by Lebioda** [comment]
Już 10 dni minęło a problem nadal występuje... @Lukasz-Zurek zajmiecie się nim?

**Comment by Lukasz-Zurek** [comment]
@netilmedia Tak, dane z całą pewnością zostaną przywrócone.

Przepraszamy za utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@Lebioda Tak, cały czas pracujemy nad poprawką. Prosimy Cię o cierpliwość.

Jednocześnie przepraszamy za utrudnienia.

**Comment by netilmedia** [comment]
Dzień dobry,
proszę o informację o planowanym terminie zakończenia prac.

**Comment by Lukasz-Zurek** [comment]
@netilmedia Problem został wyeliminowany i nie powinien już występować.
