### ISSUE TITLE
Brak możliwości synchronizacji aukcji allegro i  sklepu ShopGold ,,, brak aukcji o podanym numerze

### ISSUE THREAD

**Issue by katazipen** [allegro/allegro-api#4408]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by Lukasz-Zurek** [comment]
Komunikat może wskazywać na próbę uzyskania informacji dotyczących oferty archiwalnej. Prześlij proszę więcej szczegółów np. request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4408.

**Comment by katazipen** [comment]
Sprawdzałem to kilkukrotnie aukcji są nowe jest ich ponad 100 sprawdziłem
10 aukcji żadna z nich nie wchodzi ale zauważyłem wczoraj że udało się i
zawsze się tak dzieje w pierwszej kolejności nie mogę się zalogować potem
się loguje i potem zaczyna to wszystko działać nie wiem gdzie leży problem
podejrzewam że w API Allegro

pon., 19 kwi 2021, 07:43 użytkownik Lukasz-Zurek ***@***.***>
napisał:

**Comment by Lukasz-Zurek** [comment]
W tej sytuacji najlepiej będzie jak wyjaśnisz to w pierwszej kolejności z obsługą ShopGold. Jeśli twórcy aplikacji potwierdzą błąd, mogą to zgłosić bezpośrednio do nas.
