### ISSUE TITLE
Wyszukiwanie ofert pod kątem ochrony własności przemysłowej

### ISSUE THREAD

**Issue by cieplik206** [allegro/allegro-api#4409]
Dzień Dobry

Korzystam obecnie z API - zasobu GET /offers/listing w celu wyszukiwania ofert które wykorzustyją słowny znak towarowy a te podmioty które nie posiadają autoryzacji są zgłaszane do programu WOP.

Po 1.06.2021 jednakże stworzycie limit 600 ofert. Obecnie pobieram zbiór kilku tysięcy ofert i dopiero z niego wyfiltrowywuje oferty autoryzowanych sprzedawców a to co zostanie mogę przeanalizować i ewentualnie zgłosić do WOP.

Jak zatem zaproponujecie możliwosć wyszukiwania ofert dla tego przypadku?  

czy można skorzystać z wyjądku na podstawie pkt 3.5 Regulaminu API ?

**Comment by Lukasz-Zurek** [comment]
W tej sprawie skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
