### ISSUE TITLE
Problem z API REST - opinie

### ISSUE THREAD

**Issue by pmielcza** [allegro/allegro-api#441]
Dziś (26.07.2018) od około 8.00 przestały mi działać skrypty, które pobierały moje opinie przez API REST z moich kont Allegro.

Mianowicie w odpowiedzi serwera podczas wykonywanie zapytania curl dostaje błąd 403.
Skrypty wcześniej działały prawidłowo.

Czy jest to związane z problemami technicznymi Allegro ?

dodam że problem mam na 3 kontach a czwarte idzie prawidłowo

**Comment by rtnet-pl** [comment]
Hej. Prawdopodobnie używasz złego access tokena do złego zasobu (czyli nie z tego konta). Możesz sobie rozkodować token [tym narzędziem](https://jwt.io/) i upewnić się, że jest prawidłowy

**Comment by PawelTaberski** [comment]
Tak jak napisał @rtnet-pl  problem wynika, że próbujesz pobrać dane tokenem od innego konta.

**Comment by pmielcza** [comment]
kurcze, przecież piszę że skrypt działa prawidłowo - nie możliwe jest podmienianie tokenów (mam zupełnie oddzielne pliki do kont), natomiast dziś zauważyłem kolejną kwestię - która wiąże się z wczorajszą - mianowicie:

Mam skrypt który za pomocą CRONE uruchamia się co godzinę.
Skrypt przy 1 logowaniu pobiera "access_token" i "refresh_token" i zapisuje je sobie do plików.

Podczas ponownego uruchomienia skrypt pobiera za każdym razem "refresh_token" i zapisuje
go sobie do pliku (nadpisuje plik).

Problem polega na tym że po 12 godzinach działania - wywala mnie z konta i muszę od
nowa się logować. I to było powodem błędu.

Czy podczas każdego wywołania refresh'a powinienem pobierać także
"access_token" i też zapisywać go do pliku (nadpisywać) ? Jest możliwe że on też się zmienia ?

**Comment by PawelTaberski** [comment]
Nie wiem czy dobrze Ciebie zrozumiałem, ale access token jest ważny 12h, ale jeśli masz również refresh token nie musisz zmuszać użytkownika do ponownej autoryzacji co 12h. Możesz uzyskać dzięki refresh tokenowi nowy token dostępowy i korzystać z niego przez kolejne 12h. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/auth/#refresh-token).

**Comment by Xawier** [comment]
Witam, jaka jest metoda do pobierania opini z konta klienta? Gdyż w dokumentacji ani widu ani słychu.

**Comment by PawelTaberski** [comment]
Możesz pobrać jedynie informacje o ocenach użytkownika, więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/2017-10-09-news_informacje_o_ocenach/).
