### ISSUE TITLE
ProductNotFoundException

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#4410]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym

:beetle: **Opis**
Siostrzany problem: #4207

Podczas zmian (np za pomocą PATCH sale/product-offers/)  na aukcjach dostajemy:
[{"code":"ProductNotFoundException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Product not found for the given id. The data necessary to create the offer and to propose the product was not provided."}]

Problem związany jest bezpośrednio z produktem 9b148efd-4cb9-4828-ae38-5550c6f77426

Próba odszukania produktu na froncie również kończy się błędem:
po numerze 000723180181
![Bez tytułu](https://user-images.githubusercontent.com/36523118/115270260-6c2e1080-a13c-11eb-870b-29fa99660e1d.png)

po eanie 8001063916187
![Bez tytułu](https://user-images.githubusercontent.com/36523118/115270419-94b60a80-a13c-11eb-90f0-99820b60a671.png)

Nie jesteśmy w stanie nawet odłączyć produktu od oferty, na froncie pomimo braku powiązania oferty z produktem dostajemy:
![Bez tytułu](https://user-images.githubusercontent.com/36523118/115271950-2a05ce80-a13e-11eb-8ba2-e02e385db284.png)

Takich produktów mamy znacznie więcej - jeżeli będzie trzeba możemy podesłać id.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, jest to tożsamy problem jak opisany we wskazanym przez Ciebie wcześniejszym wątku. Sprawa jest weryfikowana. W momencie wyeliminowania problemu zamieszczę aktualizację.
