### ISSUE TITLE
Verification failed (1.01zt was successfully charged, but the request to activate my Allegro account has been rejected)

### ISSUE THREAD

**Issue by yuragalin** [allegro/allegro-api#4411]
I received the email with the following message:
_The technical problems we had with accepting your transfer prevented us from verifying your data. Try again._
Could you tell me please, how can I know what is the reason of the rejection and what should I do to fix it? Thanks in advance.

**Comment by MaciejFrackowiak** [comment]
Please, give us more details - account login or ID, so we will be able to check it.

**Comment by yuragalin** [comment]
Thanks for your response. My login on allegro: yuragalin

**Comment by MaciejFrackowiak** [comment]
This case is not connected directly with API, so please contact with Allegro support via [contact form](https://allegro.pl/help/contact?category=bf78f387-8bda-46e1-9ecd-5ffa5016101b&subjectId=0bc27e4d-4963-4626-aba5-3a4f32d5ec4d).

**Comment by yuragalin** [comment]
Thank you very much!
