### ISSUE TITLE
Blokada cennika dostaw

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#4414]
Czy istnieje możliwość zablokowania cennika dostaw tak by nie był on zwracany przez rest api?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma takiej możliwości.

**Comment by mlonc** [comment]
W takim razie jest problem, na zautoryzowanym koncie jest dużo więcej cenników niż zwraca mi rest api

**Comment by MaciejFrackowiak** [comment]
Proszę podaj ID konta lub jego login, byśmy mogli to zweryfikować.

**Comment by mlonc** [comment]
> Proszę podaj ID konta lub jego login, byśmy mogli to zweryfikować.

login: strefaczescipl

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam Twojego spostrzeżenia - w serwisie WWW masz 2 cenniki, w API na koncie również są dostępne tylko te 2 cenniki.

**Comment by mlonc** [comment]
Sprawdziłem z klientem ponownie, miał 2 konta połączone menadżerem sprzedaży i nie zmienił konta podczas przeglądania cenników.

Sprawa wyjaśniona, dziękuję za pomoc
