### ISSUE TITLE
GET /order/checkout-forms/{orderId}/invoices Błąd 404 przy próbie pobrania listy faktur

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#4415]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym

:beetle: **Opis**
Dzień dobry, proszę o poprawienie zasobu /invoices żeby zwracał pustą kolekcję jak nie ma faktur na zamówieniu zamiast błędu 404. Zamówienia istnieją wbrew temu co sugeruje komunikat. Potrzebuje najpierw odpytać czy już jest dodana faktura do zamówienia przed wysyłką.

  "TraceId": "c30324310829bb3f", ad673861-a10a-11eb-8094-b942f0de8ff6
  "TraceId": "abd19f0c2d495f8b", e146d111-a112-11eb-b61d-5b0e24b798c3
  "TraceId": "4c26e8a9a75485ae", 819e97b1-a11d-11eb-a61b-5522feca3dc6

REQUEST 2021-04-20 12:53:06.8061517  
curl -X GET \
  'https://api.allegro.pl/order/checkout-forms/26c9d371-a0e8-11eb-b61d-5b0e24b798c3/invoices' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer ' \

RESPONSE 2021-04-20 12:53:06.8842698   Duration: 78,1181ms
{
  "Data": null,
  "Validation": {
    "Errors": [
      {
        "Code": "ORDER-NOT-FOUND",
        "Details": null,
        "Message": "Order with id [26c9d371-a0e8-11eb-b61d-5b0e24b798c3] not found",
        "Path": "/order/checkout-forms/26c9d371-a0e8-11eb-b61d-5b0e24b798c3/invoices",
        "UserMessage": null
      }
    ],
    "Warnings": null,
    "ValidatedAt": null
  },
  "TraceId": "a10c85b85686ae41",
  "Error": true,
  "StatusCode": 404,
  "Message": "{\"errors\":[{\"code\":\"ORDER-NOT-FOUND\",\"message\":\"Order with id [26c9d371-a0e8-11eb-b61d-5b0e24b798c3] not found\",\"details\":null,\"path\":\"/order/checkout-forms/26c9d371-a0e8-11eb-b61d-5b0e24b798c3/invoices\",\"userMessage\":null}]}"
}

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem ten temat do odpowiedniego zespołu. Wrócę z informacją, gdy uda mi się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
@alekskuc W ciągu najbliższych tygodni wdrożymy odpowiednią poprawkę. Poinformuję w wątku, kiedy to już nastąpi.

**Comment by hoszke** [comment]
Is there any update?

I have an order in sandbox:
80c75750-736a-11ef-8814-01f4267834b6
Order exists, I can download it via /order/checkout-forms

But when I try to POST or GET to invoices endpoint, I have got ORDER-NOT-FOUND error message.


https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/80c75750-736a-11ef-8814-01f4267834b6/invoices

{"errors":[{"code":"ORDER-NOT-FOUND","message":"Order with id [80c75750-736a-11ef-8814-01f4267834b6] not found","details":null,"path":"/order/checkout-forms/80c75750-736a-11ef-8814-01f4267834b6/invoices","userMessage":"Order with id [80c75750-736a-11ef-8814-01f4267834b6] not found"}]}

**Comment by PrzemyslawLukanowski** [comment]
@hoszke This order belongs to user 107xxxx24 and being authorized as this one you received 200 status. When you try to add or retrieve an invoice you are authorized as a user 107xxxx61 and that is why we return 404 Not Found status.
