### ISSUE TITLE
Komunikat błędu dla braku niektórych parametrów przy tworzeniu oferty z nowym produktem

### ISSUE THREAD

**Issue by gufio** [allegro/allegro-api#4416]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem testowym
 
:beetle: **Opis**

POST sale/product-offers

Podczas tworzenia oferty wraz z nowym produktem (środowisko sandbox), komunikaty błędów dla większości parametrów są poprawne np.
![image](https://user-images.githubusercontent.com/59032279/115394272-e913c580-a1e2-11eb-9e60-5b6d221efded.png)
Gdy nie podam parametru "Model" dostaję komunikat, który nie wskazuje nazwy parametru. Byłoby super, gdyby api zwracało nazwy wszystkich brakujących parametrów.
![image](https://user-images.githubusercontent.com/59032279/115394454-13658300-a1e3-11eb-9418-47de64c8931a.png)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię. Czy możesz podać kategorię, dla której zwróciliśmy błąd bez wskazania konkretnego parametru? Przenalizujemy ten przypadek.

**Comment by gufio** [comment]
ID kategorii: 87981

**Comment by PrzemyslawLukanowski** [comment]
Zweryfikowałem ten przypadek - komunikat nie będzie występować po kolejnej [aktualizacji kategorii i parametrów na Sandboxie](https://github.com/allegro/allegro-api/issues/4019). W tej chwili parametr "Model" nie jest wymagany do stworzenia produktu na produkcji, jednak w środowisku testowym nadal widnieje jako "requiredForProduct".
