### ISSUE TITLE
Czy oferty z uzupełnionymi parametrami w sekcji "Podstawowe parametry" połączą się automatycznie z produktem?

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#4417]
Dzień dobry

Mam pytanie odnośnie oferty 10617429639 zostały uzupełnione dla niej wszystkie parametry z sekcji "Podstawowe parametry" czy dla tej oferty zostanie utworzony produkt automatycznie po jakimś czasie? Czy dla ofert wystawianych przez api należy ręcznie utworzyć produkt? Klikając na "Połącz z produktem" produkt się utworzy. Wcześniej zaobserwowałem, że oferty same się łączą z produktem gdy mają uzupełnione wszystkie wymagane parametry.

**Comment by MaciejFrackowiak** [comment]
Przytoczę tu odpowiedź z postu [#4287](https://github.com/allegro/allegro-api/issues/4287#issuecomment-814684446) - automatyczne łączenie oferty z produktem nie jest bezpośrednio powiązane z polami, które są dostępne w API. Proces ten musi zostać odgórnie włączony w danej kategorii, po uwzględnieniu GTIN i zgodności kategorii.

**Comment by pawelosajda** [comment]
Dla powyższej oferty utworzyłem produkt, jednak produkt nie posiada zdjęć czy pojawią się później? Przy tworzeniu produktu zdjęcia zostały przekazane
![Screenshot from 2021-04-21 16-43-31](https://user-images.githubusercontent.com/4314822/115573635-36fefb00-a2c1-11eb-83ee-b70f61be35e2.png)

**Comment by MaciejFrackowiak** [comment]
Jak widzę zdjęcia dla danego produktu zostały usunięte na skutek przeprowadzonej weryfikacji.

**Comment by ppart** [comment]
> Jak widzę zdjęcia dla danego produktu zostały usunięte na skutek przeprowadzonej weryfikacji.

Co dokładnie to oznacza? Nie spełniają jakiś kryteriów? 
I czy produkt ostatecznie jest prawidłowo utworzony mimo, że te zdjęcia zostały usunięte?

Z góry dziękuję za wyjaśnienie

**Comment by MaciejFrackowiak** [comment]
@ppart Produkt został wstępnie dodany do bazy produktów, jednak podlega on szczegółowej weryfikacji - sama weryfikacja odbywa się już poza nami, czyli stricte API. Więcej informacji o procesie możesz uzyskać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
