### ISSUE TITLE
Allegro API i bug bounty na H1 

### ISSUE THREAD

**Issue by Polo0110** [allegro/allegro-api#4418]
Witajcie,
Allegro Kontakt przekierował mnie tu bo nie byli w stanie odpowiedzieć na moje pytanie odnośnie Allegro Bug Bounty prowadzonego  na hackerone. Mianowicie:
Czy dane wrażliwe (nazwiska, adresy, telefony, zakupione przedmioty, shippment trackery, wartości zakupów itd ) ewidentnie związane ze sprzedażą prowadzoną za pośrednictwem Allegro (pewnie jakaś integracja z api) ale jednocześnie hostowane na adresie nie należącym do Allegro są "in scope" bug bounty? Czy też raczej powinienem zgłosić incydent do firmy-sprzedawcy?
Czy dev team Allegro prowadzi jakąś kontrolę nad integracjami api? To znaczy, czy "zatwierdzacie" to co tworzą ludzie jako "koszerne" i bezpieczne do użytku komercyjnego? I czy takie rozwiązania są "in scope" bug bounty?
Z góry dzięki za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Takie przypadki powinieneś zgłosić bezpośrednio do twórcy danego oprogramowania - jako Allegro obecnie nie weryfikujemy działania konkretnych rozwiązań firm trzecich. Twórca danej aplikacji powinien zachować należytą staranność pisząc dane oprogramowanie, uwzględniając wymagania [regulaminu usługi](https://developer.allegro.pl/rules/).
