### ISSUE TITLE
problem z change-price-commands

### ISSUE THREAD

**Issue by pfunkowski** [allegro/allegro-api#442]
Uruchomienie, metody zwraca błąd 
{"errors":[{"code":"NotAcceptableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

URI: https://allegroapi.io/offers/7339385825/change-price-commands/e0774306-273f-4b61-a9b4-b7d59ec328f4
DATA: {"id":"e0774306-273f-4b61-a9b4-b7d59ec328f4","input":{"buyNowPrice":{"amount":"47.90","currency":"PLN"}}}

**Comment by MaciejPotepa** [comment]
Dzień dobry 

Do weryfikacji problemu potrzebuję treści requestu. Numer oferty też nie zaszkodzi.

**Comment by pfunkowski** [comment]
Numer oferty podany w url body request też, proszę o wskazanie brakujących informacji

**Comment by rtnet-pl** [comment]
Nie ma nagłówków, a wygląda na to, że w nich jest błąd.

**Comment by pfunkowski** [comment]
Authorization: Bearer ***
Api-Key: ***
Content-Type: application/vnd.allegro.beta.v1+json
Accept: application/vnd.allegro.beta.v1+json

**Comment by rtnet-pl** [comment]
Powinieneś zmienić beta na public

**Comment by pfunkowski** [comment]
Dzięki, zmiana na public rozwiązała problem. Chociaż zmiana nagłówków dla każdej metody jest uciążliwa .... Zaskakujące jest też to że inne metody public/beta działały  bez problemów.

**Comment by rtnet-pl** [comment]
Musisz założyć, że każdy zasób beta będzie kiedyś przenoszony na production, trzeba śledzić terminy kiedy następują te zmiany. Ewentualnie obsłużyć kod błędu 406 ponawiając cały request z nowym nagłówkiem.
