### ISSUE TITLE
Weryfikacja aplikacja korzystających z GET /offers/listing

### ISSUE THREAD

**Issue by juhacz** [allegro/allegro-api#4420]
Proszę o usunięcie postu.

**Comment by MaciejFrackowiak** [comment]
Zgodnie z informacjami, które już przekazywaliśmy na GitHub`ie nie bierzemy czynnego udziału w procesie weryfikacji danej aplikacji, a co za tym idzie nie mamy żadnego wpływu na jej przebieg. W związku z tym tylko i wyłącznie podczas wymiany komunikacji via formularz kontaktowy możesz uzyskać informacje co do jej rezultatu. Mogę wyłącznie Cię zachęcić do ponownego kontaktu z przedstawieniem Twojej wizji, którą tu opisałeś.
