### ISSUE TITLE
Błąd podczas uzupełniania parametru GTIN

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4421]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas uzupełniania parametru GTIN na aukcji 9500932335 występuje błąd: **Niepoprawna wartość EANu.**
Kategoria tej aukcji ma parametr GTIN o id 225693 i jako values przekazujemy wartość **5909782601364**
Prosimy o informacje co jest nie tak z tym eanem.
Dołączam request i response aktualizacji draftu.

[ean_res (2).txt](https://github.com/allegro/allegro-api/files/6356223/ean_res.2.txt)

**Comment by MaciejFrackowiak** [comment]
To nie jest prawidłowy EAN - a dokładnie cyfra kontrolna jest niewłaściwa. Właściwy numer powinien przyjąć wartość - 5909782601366. Każdy kod możesz zweryfikować na stronie [GS1](https://www.gs1.org/services/check-digit-calculator).
