### ISSUE TITLE
Problem z włączaniem aukcji

### ISSUE THREAD

**Issue by jacekskowron** [allegro/allegro-api#4422]
Dzień dobry,

W aplikaji, która wykorzystuje allegro REST api do włączania i wyłączania aukcji występuje problem.
Problem polega na tym, że w odstępie 20 minut rezultat wykonywania zapytania nie jest do końca logiczny.

1) Próba włączenia aukcji (wyszukujemy aukcje po externalid) - podajemy listę 22 identyfikatorów kończy się bez włączenia żadnej aukcji, ponieważ nie znaleziono odpowiednich aukcji.

2) 10 minut później gdy do tych 22 identyfikatorów dołożyliśmy 8 innych sygnatur (czyli razem 30 sygnatur), dostajemy w rezultacie 21 identyfikatorów aukcji i wykorzystujemy je do wyłączenia aukcji.
Niestety wśród tych identyfikatorów pojawiły się aukcje, których nie wyszukiwaliśmy poprzez ezternal id, w rezultacie czego włączają się aukcje, które nie powinny.

Z kim mógłbym się skontakować, żeby przesłać dokładniejsze informację i poprosić o pomoc.

Pozdrawiam
Jacek Skowron

**Comment by MaciejFrackowiak** [comment]
Jeżeli korzystasz z aplikacji zewnętrznej to w opisanej kwestii powinieneś skontaktować się z jej twórcą, aby wyjaśnić wszelkie wątpliwości.

**Comment by jacekskowron** [comment]
Ja jestem twórcą tej aplikacji zewnętrznej i starałem się bardzo uważnie wyjaśnić przyczynę problemu.
Doszedłem do momentu, w którym chciałem poprosić o pomoc kogoś z Państwa strony.

2021-04-16 15:19:15.270 - wyszukujemy aukcji podająć 22 identyfikatory - 0 rezultatów
2021-04-16 15:19:15.270 - wyszukujemy aukcji podając 30 identyfikatory - 21 rezultatów
2021-04-16 15:19:15.473 - więc włączamy 21 aukcji używając komendy o identyfikatorze: 0784537c-d564-46b8-9009-f870c3d4b3f9
wśród aukcji, które próbujemy włączyć jest aukcja o externalid R10 SLIM-R - 16 NIEB, która nie powinna zostać włączona, ponieważ jej nie wyszukiwaliśmy.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem podany commandID i obejmował on 20 ofert, z czego 19 zakończyło się z powodzeniem, a tylko 1 oferta *628 nie została aktywowana. Zatem już liczba, którą wskazałeś jest nieprawidłowa.

**Comment by jacekskowron** [comment]
Komenda obejmowała 21 aukcji:
"id": 10541870506
"id": 10619092628
"id": 10562698639
"id": 10562695945
"id": 10562652918
"id": 10562504904
"id": 10559762597
"id": 10559753944
"id": 10559748646
"id": 10559731717
"id": 10559698704
"id": 10558454697
"id": 10541870506
"id": 10541834848
"id": 10537886671
"id": 10537852701
"id": 10517750233
"id": 10517747815
"id": 10517744740
"id": 10515198691
"id": 10515087972

Ale pytanie, na które próbuję znaleźć odpowiedź jest inne. Dlaczego szukając istniejących aukcji podając 22 identyfikatory, dostajemy 0 aukcji do włączenia, a gdy podajemy 30 identyfikatorów podczaasz szukania aukcji (czyli dołożyliśmy tylko 8:

R10 LIB MĘS - 19   GRA MAT
--
R10 LIB MĘS - 19 OŁÓW MAT
R20 SEN V2 MĘS - 21 GRAFIT
R21 29 GUARDIAN - 17 GRA-SEL
R21 29 THE ONE V1 - 21 GRA-SEL
R21 AERO V2 MĘ - 21 CZA-SEL
R21 DISC DAM - 19 CZA
R21 DISC DAM - 19 SEL
R21 DISC MĘS - 19 CZAR-CZE
R21 DISC MĘS - 21 CZAR-CZE
R21 ELITE PRO V2 DAM - 17 BIAŁA
R21 ELITE PRO V2 DAM - 17 GRANAT
R21 ELITE PRO V2 DAM - 19 BIAŁA
R21 ELITE PRO V2 DAM - 19 GRAFIT
R21 ELITE PRO V2 DAM - 19 GRANAT
R21 INT V1 AM MĘS - 21 BIA
R21 LIB MĘS - 19 CZA BŁĘ
R21 QUAN V4 DAM - 17 CZA-NIEB
R21 QUAN V4 MĘS - 17 CZA-NIEB
R21 QUAN V4 MĘS - 17 CZA-SEL
R21 QUAN V4 MĘS - 19 CZA-NIEB
R21 QUAN V4 MĘS - 19 CZA-SEL
R21 QUAN V4 MĘS - 21 CZA-NIEB
R21 QUAN V4 MĘS - 21 CZA-SEL
R21 SMART ST - GRA

) to w rezultacie otrzymaliśmy 21 aukcji a decydujące pytanie, to dlaczego dostajemy tam aukcje z external id, którego nie wysyłaliśmy? Jestem na 90% pewny, że nie podawaliśmy tam external ID R10 SLIM-R - 16 NIEB szukając aukcji (90% bo nie mam tego do końca zalogowanego po swojej stronie, ale pytałem uztykowinków i nikt nie zmieniał tych identyfikatorów w ciągu tamtych 10 minut).

Czy jest Pan w stanie zobaczyć body zapytania wyszukującego zamówienia po sygnaturach bezpośrednio przed wykomaniem wspomnianej komendy (0784537c-d564-46b8-9009-f870c3d4b3f9)? To powinno rozwiać wątpliwość czy wysłałem tam R10 SLIM-R - 16 NIEB

**Comment by MaciejFrackowiak** [comment]
Twoja lista zawiera 2 razy ofertę 10541870506, stąd różnica w ilości. 

Odnośnie wyszukiwań - widzę wyłącznie requesty, bez odpowiedzi dla nich, więc tu trudno mi się odnieść do wyników, które podajesz. Same requesty z okolic czasu zlecenia aktywacji ofert nie widzę, aby posiadały wskazany external.id=R10 SLIM-R - 16 NIEB.

Tylko na podstawie konkretnych requestów i response, a także Twoich późniejszych kroków moglibyśmy spróbować odtworzyć pełen przepływ danych - jeżeli podobna sytuacja będzie miała miejsce w przyszłości proszę zachowaj pełne wywołania i odpowiedzi wraz z trace-id, co pozwoli na szczegółową weryfikację.

**Comment by jacekskowron** [comment]
Ok, ja dodam zapis swoich requestów, w tej chwili mam identyfikatory produktów, requesty będą miały już konkretne sygnatury.

Sytuacja powtórzyła się już kilkukrotnie.

Jeśli widać requesty, to prosiłbym o podanie requesta do:
/sale/offers?external.id= ....
Z okresu pomiędzy: 2021-04-16 15:19:15.270 - 2021-04-16 15:19:15.473, gdzie data końcowa to data komendy wspomnianej wcześniej. Myślę, że jeśli Pan może zobaczyć requesta to nam jednoznacznie rozwieje wątpliwosci co tam wysłałem, a jeśli nie wysłałęm tam external.id=R10 SLIM-R - 16 NIEB to prosiłbym o sprawdzenie, dlaczego w rezultacie tego requesta dostałem identyfikator aukcji: 10558454697

Byłbym bardzo wdzięczny za pomoc.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem nie widzę odpowiedzi do wysłanych przez Ciebie requestów do GET /sale/offers... , dlatego trudno mi się odnieść stricte do tej kwestii. Także kolejny etap flow, czyli przeniesienie otrzymanych ofert do requestu z aktywacją wybranych z nich jest już obsługiwany stricte w Twojej aplikacji, tu również nie mamy możliwości weryfikacji tego kroku.

**Comment by jacekskowron** [comment]
Hmm, napisał Pan wcześniej, że "Odnośnie wyszukiwań - widzę wyłącznie requesty," oraz "z. Same requesty z okolic czasu zlecenia aktywacji ofert nie widzę, aby posiadały wskazany external.id=R10 SLIM-R - 16 NIEB."

Ja nie potrzebuję odpowiedzi tego requesta, ja potrzebuję URL dokładnie tego reqeusta, który był wykonany w przedziale 200 milisekund przed komendą. 

Czy mógłbym prosić o niego?

Rozumiem, kolejny etap flow jest po mojej stronie, nie potrzebuję jego weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Nie posiadam pełnych adresów URL wywołań, wyłącznie składowe wchodzące w dane wywołanie:

1) 2021-04-16 15:19:15.247: externalIds=[R21 AERO V2 MĘ - 21 CZA-POM, R21 INT V2 DAM - 17 BIA, R21 INT V2 DAM - 17 BŁĘ, R21 SEN V3 MĘS - 21 GRA, R21 AERO V1 MĘ - 21 CZA-POM, R21 INT V1 AM MĘS - 19 CZA, R8 SEN V3 MĘS - 21 CZA SREB KOMP, R21 29 THE ONE V1 - 19 CZA-NIE, R21 INT V1 AM MĘS - 17 CZA, R21 ALFA CITY MĘS- 19 GRA-ZŁO, R21 SEN V1 DAM - 19 GRA, R21 ALFA CITY DAM- 17 CZA-RÓŻ, R21 SEN V3 MĘS - 19 CZA, R21 SEN V1 DAM  - 17 GRA]

1) 2021-04-16 15:19:15.333: externalIds=[R21 LIB MĘS - 19 CZA BŁĘ, R21 QUAN V4 MĘS - 19 CZA-SEL, R21 DISC MĘS - 21 CZAR-CZE, R21 ELITE PRO V2 DAM - 17 BIAŁA, R21 QUAN V4 MĘS - 19 CZA-NIEB, ZAM-TY301, R10 LIB MĘS - 19 GRA MAT, R21 QUAN V4 MĘS - 17 CZA-SEL, R21 SMART ST - GRA, POM CRH-011P, R21 QUAN V4 MĘS - 21 CZA-NIEB, R21 QUAN V4 MĘS - 21 CZA-SEL, R21 DISC MĘS - 19 CZAR-CZE, R21 AERO V2 MĘ - 21 CZA-SEL, R10 LIB MĘS - 19 OŁÓW MAT, R21 DISC DAM - 19 CZA, R21 29 THE ONE V1 - 21 GRA-SEL, R21 ELITE PRO V2 DAM - 19 GRAFIT, ZAM-TY715, BŁO SDE, R21 QUAN V4 DAM - 17 CZA-NIEB, R21 DISC DAM - 19 SEL, R21 29 GUARDIAN - 17 GRA-SEL, R21 INT V1 AM MĘS - 21 BIA, R21 ELITE PRO V2 DAM - 17 GRANAT, R21 ELITE PRO V2 DAM - 19 GRANAT, BAG YJ-D14, R20 SEN V2 MĘS - 21 GRAFIT, R21 QUAN V4 MĘS - 17 CZA-NIEB, R21 ELITE PRO V2 DAM - 19 BIAŁA]

3) 2021-04-16 15:19:15.436: GET /sale/offers bez dodatkowych parametrów

**Comment by jacekskowron** [comment]
Dziękuję serdecznie.

Chodziło mi o request numer 2. 

Pozostaje już teraz tylko dowiedzieć się, dlaczego ten request w rezultacie zwrócił nam identyfikator aukcji numer: 10558454697

Niestety ta aukcja została usunięta przez użytkownika i ja nie mogę tego sprawdzić czy ta aukcja miała ustawioną kiedykolwiek sygnaturę inną niż
R10 SLIM-R - 16 NIEB
nie wiem nawet, czy jest taka możlowość w panelu sprzedawcy. Czy Pan mógłby to sprawdzić?

Jeśli ta sygnatura nie była zmieniana nigdy na tej aukcji, to należałoby odpowiedzieć na pytanie dlaczego request nr 2. z Pana poprzedniej odpowiedzi zwrócił tą aukcję.

**Comment by jacekskowron** [comment]
Czyli podsumowując, widzimy, że ja nie wysłałem sygnatury: R10 SLIM-R - 16 NIEB w celu otrzymania numerów aukcji do wyłączenia, jednak w odpowiedzi dostałem numer aukcji 10558454697, która została włączona, a która dotyczy produktu o sygnaturze R10 SLIM-R - 16 NIEB

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem - nie posiadamy odpowiedzi dla wysłanego przez Ciebie requestu do GET /sale/offers..., aby zweryfikować to co otrzymałeś w odpowiedzi - sam również tego nie posiadasz jak pisałeś, zatem trudno nam się jednoznacznie odnieść do Twoich słów.

Idąc dalej, request aktywacji ofert dostaliśmy  2021-04-16 15:19:15.558, czyli po 225 tysięcznych sekundy - czy w tym czasie Twój mechanizm jest zdolny przetworzyć wynik z pobrania ofert i wysłać nową komendę z wybranymi wartościami (numerami ofert)?

Wskazana oferta miała tylko tę jedną sygnaturę jak udało mi się ustalić.

**Comment by jacekskowron** [comment]
Nie posiadam body odpowiedzi GET /sale/offers ale posiadam zbudowaną komendę na postawie tych wyników która jednoznacznie wskazuje, że w odpowiedzi dostaliśmy aukcję o numerze 10558454697

Tak, mój system jest zdolny przetworzyć wynik z pobrania ofert i wysłać nową komendę, 
![image](https://user-images.githubusercontent.com/6025271/115710888-2a3adf80-a373-11eb-8f9e-80198331f72a.png)


Usprawnię logowanie po swojej stronie, ale myślę, że udało nam się już ustalić wszystkie szczegóły, które z takiego logowania moglibyśmy dostać.

Jeśli oferta miała tylko 1 sygnaturę, to ta oferta nie powinna zostać zwrócona jako wynik requesta z GET /sale/offers z godziny
2021-04-16 15:19:15.333, ponieważ nie szukaliśmy oferty z tą sygnaturą.

Byłoby super gdyby udało się ustalić, dlaczego ona została zwrócona i chciałbym Pana o to prosić, ponieważ to jest źródło problemu, który próbujemy wspólnie rozwiazać.

**Comment by MaciejFrackowiak** [comment]
Niestety, nie mamy zapisanej odpowiedzi, która została wysłana na Twój request jak pisałem, dlatego jest to po naszej stronie niemożliwe. Dlatego w przyszłości sugeruję, abyś logował requesty i response dla wywołań, bo tylko tak możemy odtworzyć przebieg wydarzeń.

**Comment by jacekskowron** [comment]
Zgoda.

Zrobię poprawkę logującą request i response.

Wrócę do Pana, gdy problem pojawi się ponownie, ale nie jestem w stanie powiedzieć kiedy się to stanie, gdyż występuje on nieregularnie.

Pozdrawiam i dziękuję za pomoc.

**Comment by jacekskowron** [comment]
Witam ponownie.

Znalazłem przyczynę problemu. Z mojej strony zapytanie GET /sale/offers po external ID było wywoływane w pętli po 30 produktów.
Jednak niepoprawnie było wykonywane z pustymi external ID gdy liczba protuktów była równa 30. Mieliśmy wtedy jednen reqyest z 30 externa.id oraz drugi request z pustymi parametrami. Z tego drugiego requesta dostawaliśmy aukcje, których nie chcieliśmy wyłączać. 
Tak więc ja poprawiam swój kod i nie będę już wysyłał tego nadmiarowego requesta. 

Podejrzewam, że /sale/offers bez parametrów zwracało być może najnowszy zestaw aukcji. W sumie dziwne, że było to np 21 aukcji. 

Dzięukuję za pomoc i pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Cieszę się, że udało się znaleźć przyczynę problemów.
