### ISSUE TITLE
Usunięcie oferty

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4423]
Dzień dobry.
Być może jest to banalne pytanie, ale jak ostatecznie usunąć oferty przez API?
Widzę tylko opcję usunięcia draftu.

**Comment by PrzemyslawLukanowski** [comment]
Nie da się usunąć oferty, możesz ją jedynie zakończyć za pomocą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT). Po 60 dniach od zakończenia oferty, zaarchiwizujemy ją i nie będziesz mógł jej już przywrócić.
