### ISSUE TITLE
[Przepisy] MOSS / IOSS w Allegro

### ISSUE THREAD

**Issue by SebastianOzdoba** [allegro/allegro-api#4426]
Cześć
Czy znacie już jakie zmiany są planowane w obsłudze zamówień przy nowych przepisach MOSS / IOSS?
Jeśli sprzedawca jest z Chin jako platforma macie wymóg rozliczania podatków "za niego"
Jakieś zmiany będą wprowadzane w obsłudze zamówień w API?

**Comment by MaciejFrackowiak** [comment]
Niebawem zamieścimy na portalu oraz GitHub komunikat dot. planowanych zmian związanych z VAT2021.
