### ISSUE TITLE
/sale/offers/unfilled-parameters zwraca tylko listę z ofertami które są aktywne?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4427]
https://github.com/allegro/allegro-api/issues/4147

**Comment by MaciejFrackowiak** [comment]
Tak, zasób co do zasady zwraca tylko aktywne oferty. Ich odświeżenie odbywa się raz dziennie, zatem mogą się też pojawić tam oferty zakończone w ciągu ostatnich 24 godzin.

**Comment by bugproof** [comment]
Dobrze jakby był jakiś filtr który pozwalałby na zwracanie też nieaktywnych ofert, bo są np. takie oferty których nie można wystawić bo brakuje jakiegoś parametru a można go automatycznie wypełnić np. na podstawie opisu lub tytułu oferty.

Chyba będę musiał zdać się na ręczne sprawdzanie czy dany parametr jest wypełniony, czy nie.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię. Zgodnie z [naszym newsem](https://github.com/allegro/allegro-api/issues/4337) przeniosłem wątek do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).
