### ISSUE TITLE
Usuwanie administracyjne ofert ze względu na kategorię i baza produktowa

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4428]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**

Wystawiając ofertę podpięliśmy ją pod kategorię taką, jaka jest w bazie produktowej Allegro. Niedawno oferta została usunięta administracyjnie z informacją:

_Nie możesz umieszczać ofert w innej kategorii niż ta, której dotyczy sprzedawany towar. Utrudnia to kupującym wyszukiwanie interesujących ich przedmiotów._

Chodzi o produkt:
{
  "id": "810b4ff1-29ec-4714-9ff4-2dc8539f04e3",
  "category": {
    "id": "89061"
...
}

I o ofertę z tego trace-id: 55604bba4422932e.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Kwestię usunięcia oferty wyjaśnij proszę bezpośrednio poprzez formularz kontaktowy - odpowiadając na wiadomość informującą o usunięciu lub wypełniając zgłoszenie [tu](https://allegro.pl/pomoc/kontakt?kategoria=a2f3ea49-2579-47d5-87f4-6d96a42e3e86&subjectId=ae7b20da-ee49-4df4-90ed-39e32533ed8c).
