### ISSUE TITLE
Różnica między PATCH /sale/product-offers/{offerId} a PUT /sale/offers/{offerId}

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4429]
Jak rozumiem w `PUT /sale/offers/{offerId}` muszę wysłać cały obiekt jaki dostałem z GET. Czy jeśli użyje `PATCH /sale/product-offers/{offerId}` mogę wysłać tylko pojedyńcze pole które chcę zmodyfikować? Co jeśli chcę zmienić tylko 1 parametr? Czy w tym wypadku wystarczy że wyślę listę z 1 parametrem? Nie wyczyści to pozostałych parametrów?

**Comment by MaciejFrackowiak** [comment]
Tak, w PUT /sale/offers/{offerId} przekazujesz cały model oferty, natomiast PATCH /sale/product-offers/{offerId} pozwala na edycję wybranego pola. W przypadku parametrów musisz przekazać całą strukturę sekcji "parameters". Proces edycji ofert przy pomocy PATCH opisaliśmy w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99).

**Comment by bugproof** [comment]
Czyli jak chcę zmodyfikować tylko 1 parametr w PATCH muszę wysłać tylko listę z 1 parametrem czy muszę wysłać tam całą listę wszystkich aktualnych parametrów + parametr który chcę zmodyfikować?

**Comment by MaciejFrackowiak** [comment]
Wszystkie parametry wraz z tym, który ma być zmodyfikowany.

**Comment by bugproof** [comment]
Widzę, że jednak nie do końca wystarczy przekazać tylko wybrane pole.

![image](https://user-images.githubusercontent.com/3116731/116073137-4d75cf80-a690-11eb-9ba9-30f2d65b303e.png)

**Comment by MaciejFrackowiak** [comment]
Jeżeli nie chcesz, abyśmy aktualizowali Tobie ofertę na podstawie danych z produktu to te wymienione w ramce pola musisz przekazać. Natomiast jeśli chcesz dokonać stricte aktualizacji jakiegoś pola to przekazujesz tylko to jedno pole - taka idea przyświeca operacji typu PATCH.

**Comment by bugproof** [comment]
Czyli jak chcę zmodyfikować tylko 1 parametr to wystarczy że przekażę listę wszystkich aktualnych parametrów + ten zmodyfikowany parametr ? Czy nie stracę wtedy aktualnego opisu i zdjęcia?

**Comment by MaciejFrackowiak** [comment]
Są dwa rodzaje parametrów:

1) parametry produktowe - dotyczą stricte produktu, opisuje je flaga options.describesProduct dla [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2);
2) parametry ofertowe - powiązane wyłącznie z daną ofertą, np. parametr Stan, nie są związane bezpośrednio z parametrami danego produktu.

Parametry z grupy 1 podlegają aktualizacji podczas zmian danych produktu w naszej bazie, natomiast parametry z grupy 2 nie.

Jeśli chcesz, aby oferta posiadała stałe wartości parametrów dot. produktu musisz przekazać je w swoim requeście - o tym właśnie mówi zapis z "ramki". Natomiast jeśli chcesz wyedytować jakiś parametr ofertowy np. Stan to wystarczy, że przekażesz tylko jego zmienioną wartość - opisaliśmy to w sekcji "[Jak przekazać własne wartości w żądaniu](https://developer.allegro.pl/product_offers/#jak-przekaza%c4%87-w%c5%82asne-warto%c5%9bci-w-%c5%bc%c4%85daniu)".

**Comment by bugproof** [comment]
@MaciejFrackowiak właśnie wczoraj zauważyłem, że nie mogę zmienić parametru produktowego bezpośrednio z `PATCH /sale/product-offers/{offerId}`.

**Comment by bugproof** [comment]
@MaciejFrackowiak w jaki sposób mogę przefiltrować parametry z oferty tak aby pokazywało tylko parametry produktowe? Muszę najpierw pobrać listę parametrów produktowych, czy może każdy parametr jest jakoś oznaczony dzięki czemu nie musiałbym robić osobnego zapytania.

**Comment by MaciejFrackowiak** [comment]
Pobierając szczegóły oferty poprzez [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) otrzymasz listę wszystkich jej parametrów - aby sprawdzić, który z nich jest produktowy, konieczne jest odpytanie [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) i sprawdzenie, który z parametrów ma flagę options.describesProduct - wspomniałem o tym w poście wyżej.
