### ISSUE TITLE
Obsługa posprzedażowa 

### ISSUE THREAD

**Issue by milena-stachowiak** [allegro/allegro-api#443]
#402 

Dzień Dobry,
Chciałabym się dowiedzieć kiedy zostanie wprowadzona obsługa posprzedażowa.  Interesuje mnie przybliżona data.

Pozdrawiam

**Comment by MaciejPotepa** [comment]
Dzień dobry

W ciągu kilku tygodni opublikujemy zasoby do obsługi zamówień. 

Nie jesteśmy w stanie określić konkretnej daty.

**Comment by aktywnitu** [comment]
Pisaliście, że to kwestia lipca. Nie przesadźcie z przesunięciem.

**Comment by MaciejPotepa** [comment]
@aktywnitu Nie przesadzamy, chcieliśmy oddać przetestowane i działające zasoby spełniające wymagania użytkowników. Znajdziesz je [tutaj](https://developer.allegro.pl/orders/).
