### ISSUE TITLE
Modyfikacja opcji promowania na wielu ofertach - problem z usuwaniem opcji typu "extra"

### ISSUE THREAD

**Issue by ziebapawel** [allegro/allegro-api#4430]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Moje oferty posiadają ustawione promowanie typu: **_base_** oraz **_extra_**. Chciałbym jedną operacją usunać wszystkie opcje promowania.
Używam w tym celu zasobu: [PUT /sale/offers/promo-options-commands/{commandId} ](https://developer.allegro.pl/documentation/#operation/promoModificationCommandUsingPUT) z poniższą zawartością:

```
{
   "offerCriteria":[
      {
         "offers":[
            {
               "id":"7680170485"
            }
         ],
         "type":"CONTAINS_OFFERS"
      }
   ],
   "modification":{
      "basePackage":{
         
      },
      "extraPackages":[
         
      ],
      "modificationTime":"NOW"
   }
}
```
Opcje promowania typu **_base_**  usuwane są natychmiastowo (tak jak tego oczekuje), natowmiast dla opcji typu **_extra_** zakończenie ustawiane jest z końcem cyklu. Jest to jakiś bug w REST API, czy może jest inny sposób aby natrychmiastowo usunąć opcje typu **_extra_**?

**Comment by MartaNowaczyk** [comment]
Jest tak jak piszesz, mimo opcji "NOW" wyłączamy dopiero z końcem cyklu. To błąd, pracujemy nad poprawką.

**Comment by ziebapawel** [comment]
OK, w takim razie czekam na poprawkę.

**Comment by MartaNowaczyk** [comment]
Wprowadzilismy poprawkę. Problem nie powinien już występować.
