### ISSUE TITLE
Błąd 400 podczas wystawiania oferty

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4432]
Dzisiaj wyskoczyły nam błędy:

Kod błędu to 400.
[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers","userMessage":null}]

Przykładowe trace-id 7d3063bdb0acb9ca, 9c42771a9f7398ad
Podejrzewam, że przyczyną jest jakaś dana ale nie mogę tego namierzyć

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że masz problem ze strukturą JSON. Podeślij pełen request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pozwoli nam to wskazać bezpośrednią przyczynę błędu. Dopisz proszę, że dane dotyczą wątku GitHub #4432.

**Comment by pietrach** [comment]
@MartaNowaczyk na razie temat nieaktualny. Chyba już wiem co było nie tak. Jeżeli problem się powtórzy to wrócę z tematem.
