### ISSUE TITLE
Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 237210

### ISSUE THREAD

**Issue by grzesiekm86** [allegro/allegro-api#4433]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie dodania produktu do bazy wyskakuje taki błąd jak w tytule.

Pole przy wywołaniu sale/categories/112735/parameters
dostaje opis pola jako:
`[id] => 237210
                    [name] => Kolekcja
                    [type] => string
                    [required] => 1
                    [requiredForProduct] => 1
                    [unit] => 
                    [options] => stdClass Object
                        (
                            [variantsAllowed] => 
                            [variantsEqual] => 
                            [ambiguousValueId] => 
                            [dependsOnParameterId] => 
                            [requiredDependsOnValueIds] => 
                            [displayDependsOnValueIds] => 
                            [describesProduct] => 1
                            [customValuesEnabled] => 
                        )

                    [restrictions] => stdClass Object
                        (
                            [minLength] => 1
                            [maxLength] => 40
                            [allowedNumberOfValues] => 1
                        )`
uzupełniam to tak:
`(
                    [id] => 237210
                    [values] => Array
                        (
                            [0] => Julietta
                        )

                    [valuesIds] => Array
                        (
                        )

                    [rangeValue] => 
                )`
i dostaje błąd jak w tytule. Próbowałem na różnych kategoriach i za każdym razem dostaję taki oto komunikat.

**Comment by MartaNowaczyk** [comment]
Potrzebuję pełnych danych Twojego requestu w formacie cURL. Prześlij go proszę za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz, że dane dotyczą wątku #4433 na GitHubie.

**Comment by SlawomirMizerski** [comment]
W [valuesIds]  przekaż null zamiast pustej tablicy
