### ISSUE TITLE
Modyfikacja lub dodanie parametrów produktowych bez przypisania product.id?

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4434]
Chciałem opisać ten problem w https://github.com/allegro/allegro-api/issues/4429 ale pomyślałem, że rozsądniej jest zrobić nowy issue.

Mam teraz taki problem, że chciałbym dodać lub zaktualizować numery katalogowe części (id parametru 215858) w ofertach i niestety modyfikacja bezpośrednio używając `PATCH /sale/product-offers/{offerId}` nie działa bo wyrzuca błąd, że parametr jest parametrem produktowym.

Większość ofert albo nie ma w ogóle przypisanego `product.id` albo numer katalogowy w przypisanym produkcie nie jest taki jak powinien być i chciałbym go poprawić.

Czy jest to możliwe bez przypisania product.id czy przypisanie produktu jest zawsze wymagane?

Jeśli tak, wyglądałoby to tak, że szukam produktu w katalogu produktów, jeśli znajdę czego szukam, przypisuje product.id, jeśli nie dodaję nową propozycję poprzez `POST /sale/product-proposals`? https://developer.allegro.pl/en/productization/

Czy jest możliwa modyfikacja parametru w istniejącym produkcie, czy zawsze trzeba używać `POST /sale/product-proposals` i tworzyć nowy produkt?

**Comment by MartaNowaczyk** [comment]
Nie da się zaktualizować danych w produkcie, dlatego tak jak napisałeś wyszukujesz w katalogu produktów, jeśli takiego nie ma, dodajesz swoją propozycję.

Jeśli stwierdzisz, że w jakimś produkcie jest błąd możesz nam go zgłosić przez odpowiedni formularz - 
 https://allegro.pl/offer/product/report/id_produktu (id_produktu podmień na faktyczny ID z katalogu produktu, którego błąd dotyczy).

**Comment by bugproof** [comment]
A czy da się wyszukiwać produkty w katalogu po parametrach produktów? Np. chciałbym znaleźć wszystkie produkty z danym numerem OE (215858). Czy muszę wyszukać najpierw po frazie a potem przefiltrować to w pamięci?

**Comment by MartaNowaczyk** [comment]
Fraza szuka po tytułach. Do tego powinieneś wybrać kategorię, dzięki czemu skorzystasz ze wspomnianych filtrów. Wszystko masz opisane w naszym [poradniku](https://developer.allegro.pl/productization/#2-jak-wyszuka%c4%87-produkt). Jak coś będzie nadal niejasne pytaj śmiało.

**Comment by bugproof** [comment]
Jednak widzę, że jednak da się zmienić parametry produktu ale nie z `PATCH` tylko z `PUT` gdy oferta nie jest powiązana z katalogiem produktów... Skoro da się przez `PUT` to dlaczego nie da się z `PATCH`? 

``userMessage=Given parameter id `127415:Parts manufacturer` should no have been passed as `offer` parameter.``

**Comment by MartaNowaczyk** [comment]
W tym momencie piszesz o dwóch różnych zasobach:

- /sale/product-offers/{offerId}
- /sale/offers/{offerId}

`PUT /sale/offers/{offerId} `- służy do uzupełniania draftu lub edycji istniejącej oferty. Tutaj w przypadku braku przypisania produktu do oferty możesz zmieniać wszystkie parametry oferty. Więcej znajdziesz [tutaj](https://developer.allegro.pl/sale/).

`PATCH /sale/product-offers/{offerId}` - tutaj dodasz produkt do oferty, zmienisz go lub edytujesz ofertę z produktem, ale nie edytujesz parametrów w przypisanym produkcie. Więcej na ten zasobów /sale/product-offers znajdziesz w naszym [poradniku](https://developer.allegro.pl/product_offers/)

Nie wiem co dokładnie próbujesz zrobić i po jakich działaniach dostajesz ten komunikat, dlatego najlepiej będzie jak podasz mi trace-id swoich wywołań lub podeślesz przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) logi z dopiskiem, że dotyczy to wątku #4434 na GitHubie.

**Comment by bugproof** [comment]
Chodziło mi tylko o zmianę parametrów produktowych w przypadku gdy oferta nie ma przypisanego produktu i udało mi się z `PUT /sale/offers/{offerId}`
