### ISSUE TITLE
We are trying to upload products with the EAN code. 

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4435]
We are trying to upload products with the EAN code. 
We want to load with the least possible information, for example ean, sellingMode, stock. 
When we proceeded according to the document, we were unable to achieve this. 
I would like your directions.

**Comment by ymyuceturk** [comment]
The json I am trying to post is as follows. It returns, 
Category is missing error, 
name error when the category is added,
picture etc. when the name is added.
{
    "product": {     
        "parameters": [{
                "name": "EAN",
                "values": [
                    "194501048231"
                ]
            }
        ]
    },
    "sellingMode": {
        "price": {
            "amount": "554.43",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    },
    "external": {
        "id": "80EBD274-49C6-425C-8446-987B1DFB3719"
    }
}

**Comment by MartaNowaczyk** [comment]
You should enter EAN as product.id:
```
{
   "product": {
     "id": "194501048231"
   }
```
  
You can find more information [here](https://developer.allegro.pl/en/product_offers/) - look at the first sample request.

**Comment by ymyuceturk** [comment]
Thanks very much
