### ISSUE TITLE
Wielowariantowość - błędy

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4436]
Co oznacza ten komunikat ? O co dokładnie chodzi. Trace-id dla niego to **9e0a90deac96e993**

`[{"code":"VALIDATION_ERROR","message":"Podany parametr kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do ofert 10464366769, 10565901261. Uu017cyj tej samej wartou015bci parametru kolor/wzu00f3r w obru0119bie grupy ofert (10464366769), (10565901261).","details":null,"path":null,"userMessage":"Podany parametr kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do ofert 10464366769, 10565901261. Uu017cyj tej samej wartou015bci parametru kolor/wzu00f3r w obru0119bie grupy ofert (10464366769), (10565901261)."}]`

**Comment by MartaNowaczyk** [comment]
W podanych ofertach są różne linki do zdjęcia. We wszystkich ofertach, które mają tworzyc ofertę wielowariantową powinno być dodane dokładnie to samo zdjęcie - ten sam link.

**Comment by pietrach** [comment]
No nie może być to samo zdjęcie bo to są 2 różne produkty. Mają różne symbole. Mimo że na zdjęciu wyglądają podobnie.

**Comment by pietrach** [comment]
Albo ten sam błąd tutaj. Trace-id: 7ee0c488d603c08
To są 2 różne modele. Parametry mają takie same. Dlaczego nie chce ich połączyć ?

`[{"code":"VALIDATION_ERROR","message":"Podany parametr kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do ofert 9198027621, 9238915334, 9238952712, 9238956809. Uu017cyj tej samej wartou015bci parametru kolor/wzu00f3r w obru0119bie grupy ofert (9198027621, 9238915334, 9238952712, 9238956809), (9259501615).","details":null,"path":null,"userMessage":"Podany parametr kolor/wzu00f3r nie mou017ce zostau0107 dopasowany do ofert 9198027621, 9238915334, 9238952712, 9238956809. Uu017cyj tej samej wartou015bci parametru kolor/wzu00f3r w obru0119bie grupy ofert (9198027621, 9238915334, 9238952712, 9238956809), (9259501615)."}]`

**Comment by pietrach** [comment]
To jeszcze inne pytanie. W ramach tego samego wzoro/koloru (parametr colorPattern w API) muszą być takie same zdjęcia ?

**Comment by MartaNowaczyk** [comment]
W ramach colorPattern jest możliwość grupowania produktów po zdjęciach, dlatego mogą być różne. 
Sprawdzamy jeszcze ten drugi przykład.

**Comment by MartaNowaczyk** [comment]
w tym drugim przykładzie masz duplikat oferty 9198027621 i 9238952712 mają ten sam rozmiar

**Comment by MartaNowaczyk** [comment]
Możesz mi podesłać pełen request, który przesyłasz dla połączenia ofert 10464366769, 10565901261 z pierwszego przykładu?

**Comment by pietrach** [comment]
Ale to są różne kolor/patterny. Jakby to było w ramach tego samego to tak.
One mają następujące kolor/patterny podczas dodania do API

9198027621 => T-11695-1/1JC
9238952712 => W-11695-3/1JC

Poniżej request:

`{"offers":[{"id":"9198027621","colorPattern":"T-11695-1/1JC"},{"id":"9238915334","colorPattern":"W-11695-3/1JC"},{"id":"9238952712","colorPattern":"W-11695-3/1JC"},{"id":"9238956809","colorPattern":"W-11695-3/1JC"},{"id":"9259501615","colorPattern":"1695/1FB"}],"parameters":[{"id":"color/pattern"},{"id":"5389"}],"name":"Mini first steps dla dziewczynki 1695"}`

**Comment by MartaNowaczyk** [comment]
tak mi się wydaję, że trochę się nie zrozumieliśmy. W ramach jednego colorPattern  - tutaj np. T-11695-1/1JC powinny być te same zdjęcia, dla kolejnego też te same, żeby mogły się grupować.  W naszym [poradniku](https://developer.allegro.pl/multi_variant_offers/#utw%c3%b3rz-ofert%c4%99-wielowariantow%c4%85) masz to świetnie rozpisane.  

Poza tym dla obuwia to najlepiej grupować po rozmiarze i wzorze. 
[Przykład 1](https://allegro.pl/oferta/wojtylko-polbuty-6032-chlopiece-khaki-r-21-kropka-10417219103?fromVariant=10417227610) 
[Przykład 2](https://allegro.pl/oferta/navy-line-mokasyny-zgrabne-wizytowe-36-41-r-40-10643322379)

**Comment by pietrach** [comment]
"W ramach jednego colorPattern - tutaj np. T-11695-1/1JC powinny być te same zdjęcia, dla kolejnego też te same, żeby mogły się grupować"

Te same zdjęcia w ramach jednego kolor patternu a w ramach drugiego inna grupa takich samych zdjęć ?

**Comment by MartaNowaczyk** [comment]
Dokładnie tak.  Chodzi o zdjęcie główne (miniaturkę).
