### ISSUE TITLE
Czemu usuwane są produkty z katalogu?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4437]
Witam,

utworzyłem w katalogu sporą ilość produktów i wystawiam oferty z nimi za pomocą zasobu POST /sale/offers.
Zauważyłem ostatnio jednak, że pewna mała ich liczba zaczyna znikać z katalogu. Dlaczego te produkty są usuwane? Czy mogę otrzymać jakieś informacje o powodzie usunięcia? Chciałbym na przyszłość unikać takich sytuacji. Zdaje sobie sprawę, że katalog produktów jest "podwórkiem" Allegro, jednak uświadomienie co do powodu usunięcia pozwoli mi korzystać z katalogu poprawnie.

Przykładowy produkt: 704b5255-235b-4e00-99f0-2f30aef0ecb0

**Comment by MartaNowaczyk** [comment]
Rzeczywiście, produkt został usunięty, ale tylko tyle mogę stwierdzić. Weryfikacja i katalog produktów nie jest kwestią API. Informacje o powodzie usunięcia możesz uzyskać kontaktując się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
