### ISSUE TITLE
Opis oferty podczas łączenia oferty z produktem

### ISSUE THREAD

**Issue by gufio** [allegro/allegro-api#4438]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

:beetle: **Opis**
Gdy dodaję draft oferty wraz z opisem i chwilę później stworzę nowy produkt bez sekcji opisu i połączę ofertę z tym produktem, to finalnie oferta zostaje bez opisu. Czy jest to błąd, że opis się zeruje, czy tak ma być i powinienem przenieść opis do produktu?

FLOW:
1. POST sale/offers
2. POST sale/product-proposals
3. PATCH sale/product-offers/

Z kolei korzystając z endpointu POST 'sale/product-offers', tworząc nową ofertę z nowym produktem, gdy przekazuję opis, ale nie w sekcji 'product' to finalnie w ofercie jest opis.

**Comment by MaciejFrackowiak** [comment]
Korzystając z PATCH /sale/product-offers/{offerId} i chcąc zachować opis, zdjęcia i parametry produktowe musisz przekazać pola description, images oraz product.parameters - wspominamy o tym w [poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99).
