### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by corozya** [allegro/allegro-api#4439]
Dzień dobry
Próbuje aktywować konto na sandbox jednak nie ma mozliwości dokonania płatności - brak listy banków. Wyświetla się jedynie 

Wybierz bank i przelej nam 1,01 zł, aby potwierdzić swoje dane. Kwotę w całości zwrócimy na Twój rachunek.
Przelew zrób ze swojego prywatnego rachunku lub z rachunku firmowego, jeżeli założyłeś konto Firma.

login: zlote

Prośba o pomoc

**Comment by AureliuszBrussy** [comment]
@corozya aktywowałem Twoje konto na Sandboxie. Aby wystawić ofertę z konta zwykłego, skorzystaj z tego [linka](https://allegro.pl.allegrosandbox.pl/offer/?lokalnie).
