### ISSUE TITLE
i can't set offer name

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4442]
i set product name "T-shirt koszulka z nadrukiem Biały. L. Okrągły."
but it seems  "Koszulka T-shirt brak r. L" on the allegro console

trace-id :748f6effb6013df6

I'm asking for help

**Comment by ymyuceturk** [comment]
The same is true when I send an update, also the cover image does not change even though I send the images in a different order.

**Comment by hahyes** [comment]
Allegro autogenerates name if your name doesn't meet their conditions. What are these conditions? I don't know, but it probably comes from lack of brand name in product name in your case. In my case it was like this.

**Comment by AureliuszBrussy** [comment]
In this category, we automatically generate product names based on the parameters (brand, model, and size). This autogenerated product name is used in the offer title. You can modify the title of the offer (if no purchase offers have appeared) by using [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/en/documentation/#operation/editProductOffers):

```
{ 
    "name": "Nowa nazwa T-shirt r. L"
}
```

**Comment by ymyuceturk** [comment]
> The same is true when I send an update, also the cover image does not change even though I send the images in a different order.

when I send an update, the cover image does not change even though I send the images in a different order.

**Comment by AureliuszBrussy** [comment]
Could you please send me a sample request and response (with trace-id)? I'll check it.

**Comment by ymyuceturk** [comment]
While sending fashion products, an error occurred in the section where I set the brand value and the brands were registered as empty. When I update the same product by setting the brand value, the brand information I set is not reflected in the product name that the system automatically creates. I'm asking for help.
trace-id : eca0bcd7781f97ab

**Comment by ymyuceturk** [comment]
While sending fashion products, an error occurred in the section where I set the brand value and the brands were registered as empty. When I update the same product by setting the brand value, the brand information I set is not reflected in the product name that the system automatically creates. I'm asking for help.
trace-id : eca0bcd7781f97ab

**Comment by Lukasz-Zurek** [comment]
You are trying to use: [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) in offer which has already got a product assigned. The "Brand parameter" value in this product is different, so the value which you are trying to provide - will be ignored by our system. 

If you create a new product, you will have to fill your own value for "10563_40" (other) parameter.

Please confirm if you want to fix your product and add "Other" brand with a value: ""Zepplin Giyim" - then I will report it to another department.

You will find more information about editing an offer with [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) in [our guide](https://developer.allegro.pl/en/product_offers/#how-to-edit-an-offer).

**Comment by Lukasz-Zurek** [comment]
@ymyuceturk Due to the fact that my message could mislead you, please contact your account manager. We have some different situation right here.
