### ISSUE TITLE
Praca licencjacka

### ISSUE THREAD

**Issue by tiagon97** [allegro/allegro-api#4444]
Cześć, niedługo będę pisał prace licencjacką i chciałem aby była ona oparta na testach automatycznych API or UI, które będa odpalane na Jenkinsie, czy w tym celu mogę wykorzystać wasze środowisko testowe allegro sandbox?

**Comment by AureliuszBrussy** [comment]
Tak, możesz korzystać z naszego środowiska testowego (Sandboxa).
