### ISSUE TITLE
REST api not approved for me account

### ISSUE THREAD

**Issue by Steam365** [allegro/allegro-api#4445]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

98310749

 Rest API is not approved for my account even though I AM BUYER NOT SELLER. Why in this case my application cant be varified?? I am willing to import other sellers offers from allegro to by woocommerce , REST api should be easily approved for this usage. 

LET ME KNOW ! 

Thanks in advance

**Comment by AureliuszBrussy** [comment]
I assume that you are writing about [GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) which is only available for verified applications? If you want to access this resource - contact us via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). If you have already contacted us before via form - ask any questions in the e-mail correspondence.

**Comment by Steam365** [comment]
Hi

Thanks for your reply,
Yes I am talking about this function. But i need it as a buyer, not seller.
Can it be varified in that case ?

**Comment by Steam365** [comment]
I already contacted you via form and got respond that my SELLING stat turover is not high enough to get varified for REST api. But as I said , this cant be achieved since I am only buying from allegro , not planning to sell anything. Is this situation clear ? Let me know how can BUYER get varified for REST api or simply get information about offer from allegro. 

Thanks in advance !

**Comment by AureliuszBrussy** [comment]
Your case is beyond the direct support of the API use so we cannot help you. Please, continue your discussion in the correspondence you have conducted so far via the contact form.

**Comment by jakub-kaminiarz** [comment]
> ready contacted you via form and got respond that my SELLING stat turover is not high enough to get varified for REST api. But as I said , this cant be achieved since I am only buying from allegro , not planning to sell anything. Is this situation clear ? Let me know how can BUYER get varified for REST api or simply get information about offer fro

I am in similar case. Could you please tell if You menage to get any positive respond from allegro service ? It looks weird tho, feel free to write me dm. I am looking for another way to go around the problem of automatic searching allegro offers.

**Comment by Steam365** [comment]
Hi, havent received any possitive answer, or even specific requirements.
Its a deadend how to get this verification. Whats your situation ?

**Comment by jakub-kaminiarz** [comment]
I get the message from the service that to be verified user needs to deal with unclear requirements, or be a VIP partner (at least 50k PLN of sales and 2 years of partnership).

I would like to get info about the sale for my data analysis project, but allegro.pl.sandbox.pl seems not enough for me. 
It may sound illegal but what about web scraping 👍 👎 💯

**Comment by Steam365** [comment]
How long are you selling on allegro and what turnover you made so far?

**Comment by jakub-kaminiarz** [comment]
About a year, the turnover is smaller as well. 
BTW, do you have experience with the "request " library in python ? I've just tried to use it with allegro site, but got the 403 respond. Looking for an answer.

**Comment by Steam365** [comment]
Havent tried to use anything. Write me straight to email steam365 eta gmail

**Comment by DarkStoorM** [comment]
Hi @Steam365  - to me, it just looks like they are trying to limit their API for some **really weird** reasons and they don't want *regular users* to use their services - **no one** will explain to you **why**.  That's some secret information they just won't tell you :) and no, "hiding sensitive information" (as they say) is not an explanation, because _it's available to public anyway_.

The TL;DR is:

- as a seller: 50k PLN turover
- as a developer: you need **at least 100** active users of your application

That's a really bad design to completely block this resource, REST API was supposed to be an exact copy of the Front page functionality, but as we see, it's not :)

There is a new topic under /Discussions about changing this resource to just not return the sales info, but we will never get to see this change :)
