### ISSUE TITLE
Problem z uprawnieniami w akcji /sale/products

### ISSUE THREAD

**Issue by lukaskolista** [allegro/allegro-api#4447]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Pomimo posiadania uprawnień `allegro:api:sale:offers:read` (taka wartość jest w polu scope w odpowiedzi z tokenem) akcja `/sale/products?ean=...` zwraca kod 403 Forbidden, korzystam ze sposobu autoryzacji `bearer-token-for-user`. Token jest na 100% prawidłowy, ponieważ inne akcje wymagające tokena dla użytkownika działają.

Log z odpowiedzi który posiadam:
```
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied.  (truncated...)
```

**Comment by AureliuszBrussy** [comment]
Prześlij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) przykładowe wywołanie w formacie curl (wraz z pełnym access tokenem) i trace_id przez nas zwrócone. W wiadomości podaj numer zgłoszenia na GitHubie: #4447.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - kolega @lukaskolista złapał pewnie BANA na zasobie /sale/products, bo tak żeście chcieli "zabezpieczyć" bazę Produktów (kompletnie nie wiadomo po kiego grzyba), że takie cuda będą się co chwila pojawiać... Już teraz po badzie lecicie - żadnych konkretnych zasad, ani słowa o tym co po przekroczeniu limitu, czy to działa czasowo a może dozgonnie, co raz lepiej...

**Comment by lukaskolista** [comment]
> Prześlij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) przykładowe wywołanie w formacie curl (wraz z pełnym access tokenem) i trace_id przez nas zwrócone. W wiadomości podaj numer zgłoszenia na GitHubie: #4447.

**Comment by lukaskolista** [comment]
Nie wiem czy i jak bany działają, ale skoro dostaję w tokenie info o uprawnieniach to zakładam, że jak sekundę później tego tokenu użyję, to te uprawnienia będę jednak miał. Chciałem się zintegrować z allegro, żeby ułatwić sobie pracę, a tu się okazuje, że połowa zasobów wymaga specjalnych uprawnień, których nie mam bo moja argumentacja jest niewystarczająca dla osoby, która te uprawnienia przyznaje... prosty przykład z wyszukiwarką produktów - trzeba składać specjalne wnioski o dostęp do tego zasobu i spowiadać się czemu chcę mieć możliwość wyszukiwania ofert na Allegro.

**Comment by AureliuszBrussy** [comment]
Aktualnie jedynym publicznie dostępnym zasobem, który wymaga dodatkowej weryfikacji jest [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). 

W przypadku [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) korzystamy z dodatkowego limitu, konkretnie z [Leaky Bucket](https://developer.allegro.pl/about/#ograniczenie-liczby-zapyta%c5%84-limity). @lukaskolista prześlij proszę wspomniane przeze mnie dane przez formularz kontaktowy. Sprawdzę, jaki jest powód Twojego problemu.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - a to ciekawe, jednak potraficie się przyznać do tego i owego, bo w sprawie zasobu dot. bazy Produktów było kilka Waszych wypowiedzi, które mówiły tylko, że CELOWO są tam LIMITY i nie podacie żadnych szczegółów. Było też wyraźnie pisane, że niby ten magiczny LIMIT dotyczy tylko i wyłącznie zapytania o ID Produktów, a teraz wygląda na to, że dotyczy każdego zapytania na tym zasobie...

**Comment by AureliuszBrussy** [comment]
@FromAnyHole limit ten dotyczy także [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Nie ujawniamy wartości tego limitu, działa on niezależnie od standardowego limitu per ClientID.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - ale to już konkretnie: LIMIT typu L.B. jest realizowany na całym zasobie i niezależnie od formy zapytania, czy tak?? Kiedy ta "banalna" informacja zostanie dodana do oficjalnej dokumentacji? Tak dla wszystkich, bo fura rzeczy jest gdzieś porozrzucana po dziesiątkach poradników i news'ów, tego się nie da ogarniać w całości...

**Comment by lukaskolista** [comment]
Problem wynikał z braku nagłówka Accept. Tylko czemu jedne zasoby wymagają tego nagłówka i rzucają statusy, których nie ma w dokumentacji, a inne zasoby już tego nagłówka nie wymagają?

**Comment by FromAnyHole** [comment]
@lukaskolista - widać musisz wysłać dla tego zasobu [Accept] i tym samym akceptujesz ewentualnego BANA ;-)

**Comment by lukaskolista** [comment]
Gdyby te informacje były w dokumentacji, to nie miałbym z tym problemu i nie tworzył tego wątku. Chyba że to ja czegoś nie widzę, ale starałem się uważnie przeczytać dokumentację przed stworzeniem tego tematu.

**Comment by AureliuszBrussy** [comment]
@lukaskolista dodawaj nagłówek **Accept** do każdego żądania. W [dokumentacji ](https://developer.allegro.pl/documentation/) znajdziesz zwracamy przez nas **Content-Type**, który powinieneś umieścić w nagłówku **Accept** swojego żądania. Taką informację znajdziesz np. w RESPONSE SCHEMA lub w przykładowych responsach. 

@FromAnyHole dziękuję za sugestię dotyczącą umieszczenia informacji o limicie w dokumentacji. W tym momencie informujemy o limicie w [dedykowanym poradniku](https://developer.allegro.pl/productization/#2-jak-wyszuka%c4%87-produkt).

**Comment by woolkan** [comment]
cześć,
mam podobny problem. Pierwszy raz mam styczność z API Allegro i testuje połączenie z Allegro bazując na skryptach przykładowych z tutoriali.
Aktualnie napisałem sobie prosty skrypt w oparciu o tutorial https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#:
`<?php
define('CLIENT_ID', ''); // wprowadź Client_ID aplikacji
define('CLIENT_SECRET', ''); // wprowadź Client_Secret aplikacji

function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;
}

function getAccessToken() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    $token = json_decode($tokenResult);
//print_r($token);
    return $token->access_token;
}
function productInformation($token)
{
    $headers = array("Authorization: Bearer {$token}", "Accept: application/vnd.allegro.public.v1+json");
    $url = 'https://api.allegro.pl/sale/products';
    $query = ['phrase'=>5904659090090,'language'=>'pl-PL','mode'=>'GTIN'];
    $prodInfo = $url."?".http_build_query($query);
    $ch = getCurl($headers,$prodInfo);
    $result = curl_exec($ch);
    $resultCode = curl_getinfo($ch,CURLINFO_HTTP_CODE);
    curl_close($ch);
    if($resultCode!=200){
        $result = json_decode($result);
        foreach ($result->errors as $error) {
            print_r($error);
            echo $error->message.PHP_EOL;
        }
    }
    else
        return json_decode($result);
}

function main()
{
    $token = getAccessToken();
    $prodInfo = productInformation($token);
    print_r($prodInfo);
}

main();`

zarówno uruchomienie skryptu czy wykonanie bezpośrednio zapytania: curl -X GET \
  'https://api.allegro.pl/sale/products?phrase=888462600712&language=pl-PL&mode=GTIN' \
  -H 'Authorization: Bearer {token}' \
  -H 'Accept: application/vnd.allegro.public.v1+json'
  
za każdym razem powoduje błąd: '{"errors":[{"code":"AccessDeniedException","message":"Access denied.","details":null,"path":null,"userMessage":"No access."}]}'
zarówno na środowisku produkcyjnym i sandbox.
Oczywiście CLIENT_ID i CLIENT_SECRET w skrypcie wstawiam właściwe dla środowiska a przy wywołaniu bezpośrednio zapytania z konsoli wstawiam też i token właściwy dla środowiska.

Jakiś pomysł co jest powodem tego lub co mogę zrobić aby w końcu zaczęło działać?

**Comment by AureliuszBrussy** [comment]
@woolkan  w tutorialu "[Jak zacząć](https://developer.allegro.pl/tutorials/getting-started-with-the-rest-api-0A2x4WaX8iB)" opisaliśmy jak uzyskać token dostępowy w ramach [Client_credentials flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow). W ten sposób wygenerujesz token aplikacji (bearer-token-for-application) - przy jego pomocy masz dostęp tylko do niektórych endpointów (w dokumentacji przy każdym endpointcie rozpoznasz to w polu AUTHORIZATIONS).

Jeżeli chcesz wygenerować bearer-token-for-user, powinieneś skorzystać z [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [Device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by woolkan** [comment]
@AureliuszBrussy teraz działa :) dziękuję za nakierowanie 👍 na właściwe tory
