### ISSUE TITLE
Produktyzacja - element "offerRequirements"

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4449]
Metoda "https://api.{environment}/sale/products/{productId}" zwraca "offerRequirements".
Jak/kiedy/na jakiej podstawie powstaje element "offerRequirements" ?
pozdrawiam,kf

**Comment by AureliuszBrussy** [comment]
W polu tym wymieniamy warunki, jakie musi spełnić oferta, aby mogła została przypisana do produktu. Np. warunkiem może być to, że w ofercie parametr "Stan" musi być wypełniony jako "Nowy" - aktualnie głównie w takim przypadku to pole jest wykorzystywane. 

Obostrzenia na parametr stan dotyczą na ta chwile produktów utworzonych na podstawie bazy TecDoc.

**Comment by kfijalko** [comment]
To rozumiem,
Tylko kto dodaję tą sekcję i czym się kieruje?
Dlaczego niektóre produktu mają warunek Stan=Nowy i inne nie?
kf

**Comment by AureliuszBrussy** [comment]
My dodajemy taką sekcję - jest to wewnętrzna decyzja. Może np. wynikać z warunków licencyjnych. Użytkownik API tworząc produkt nie ma możliwości  zdefiniowania pola **offerRequirements**.

**Comment by kfijalko** [comment]
ok

**Comment by FromAnyHole** [comment]
@kfijalko - proponuję uważać z tym zasobem, bo w sytuacji kompletnie niejasnego LIMITU na nim, można dostać bana, a zgodnie z treścią "nowego regulaminu API-REST" mogą zablokować dostęp dla całej aplikacji i koniec zabawy. Tak to rozwijano i zachęcano przez kilkanaście lat do korzystania ze "wspaniałych" rozwiązań, każdego można wyrzucić za cokolwiek i bez podania przyczyn.

**Comment by FromAnyHole** [comment]
@kfijalko - poniżej już jednego chyba nastraszyli, wątek zniknął:
https://github.com/allegro/allegro-api/issues/4447

**Comment by FromAnyHole** [comment]
https://github.com/allegro/allegro-api/issues/4316
