### ISSUE TITLE
Produktyzacja: pole isGTIN

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4450]
W dokumentacji:
https://developer.allegro.pl/productization/#3-jak-pobra%c4%87-pe%c5%82ne-dane-o-produkcie
występuje element:
 "options": {
               "identifiesProduct": false,
               "isGTIN": true
           }
Czy pole "isGTIN" jest zwracane w szczegółach produktu lub wyszukiwarce?
pozdrawiam,kf

**Comment by FromAnyHole** [comment]
Tak masz z odpytania konkretnego Produktu:

{"id":"245669","name":"ISBN","valuesLabels":["1234567890123"],"values":["1234567890123"],"unit":null,"options":{"identifiesProduct":true,"isGTIN":true}}

**Comment by MaciejFrackowiak** [comment]
Dokładnie jak wskazał @FromAnyHole, "isGTIN" pojawia się przy parametrze produktu, który reprezentuje [globalny numer jednostki handlowej tzw. GTIN](https://developer.allegro.pl/news/#gtin) tj. EAN, ISSN lub ISBN.

**Comment by kfijalko** [comment]
ok, dzięki, jakoś mi się do tej pory nie trafił.
w dokumentacji go nie ma, jest wymieniony tylko w poradniku.
https://developer.allegro.pl/documentation/#operation/getSaleProduct

**Comment by MaciejFrackowiak** [comment]
Flaga "isGTIN" pojawia się tylko przy parametrze, który jest GTINem (EAN, ISBN lub ISSN) - informowaliśmy o tym w [naszym newsie](https://github.com/allegro/allegro-api/issues/3264).
