### ISSUE TITLE
Czy w RestApi istnieje pole w wyszukiwarkach,które sami możemy zapisywać?

### ISSUE THREAD

**Issue by totutotam** [allegro/allegro-api#4451]
Czy w RestApi istnieje pole w wyszukiwarkach,które sami możemy zapisywać?
Tak aby podczas wyszukiwania już na poziomie listingu można było je sprawdzić? Nie wchodząc osobno w aukcje?

**Comment by MaciejFrackowiak** [comment]
W API Allegro korzystając z [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) otrzymujesz dostęp do wyszukiwarki ofert, która jest odzwierciedleniem wyszukiwarki działającej na stronie WWW. Każde kolejne wyszukiwanie to wysłanie osobnego żądania / requestu z daną frazą, kategorią, id sprzedawcy, etc. Działanie funkcjonalności w API opisaliśmy w [naszym poradniku](https://developer.allegro.pl/listing/).
