### ISSUE TITLE
Integracja wysylam.allegro.pl.allegrosandbox.pl z Inpost ShipX API

### ISSUE THREAD

**Issue by 0xceba** [allegro/allegro-api#4452]
Cześć,

To pytanie dotyczy usługi wysyłkowej https://wysylam.allegro.pl.allegrosandbox.pl/.

Próbuję dodać kontrakt Inpost ShipX API na https://wysylam.allegro.pl.allegrosandbox.pl/konto/przewoznicy/dodaj/inpost. Po dodaniu mojego identyfikatora klienta i Klucz autoryzacyjny pojawia się następujący komunikat o błędzie:
![shipx_add_contract](https://user-images.githubusercontent.com/44234156/116721345-7c1bdf00-a9dd-11eb-97ae-58c8989d0a57.png)

Tekst komunikatu o błędzie jest następujący:
```
Dane dostępowe do API przewoźnika są nieprawidłowe. Oryginalny błąd: No route matches [POST] /v1/organizations/34158
```

Komunikat o błędzie wskazuje, że wysylam.allegro.pl.allegrosandbox.pl wysłał żądanie POST do punktu końcowego https://api-shipx-pl.easypack24.net/v1/organizations/34158, gdzie 34158 to mój identyfikator organizacji. Jednak dokumentacja API ShipX pod adresem https://docs.inpost24.com/display/PL/%5B1.6.0%5D+Organizacje nie mówi, że ten punkt końcowy akceptuje żądania POST.

Punkt końcowy działa poprawnie z żądaniami GET, jak widać w następującej petycji:
```
curl -X GET https://api-shipx-pl.easypack24.net/v1/organizations/34158 -H "Authorization: Bearer $token"

{"href":"https://api-shipx-pl.easypack24.net/v1/organizations/34158","id":34158,"owner_id":POMINIĘTO,"name":POMINIĘTO,"tax_id":"POMINIĘTO","bank_account_number":POMINIĘTO,"carriers":["inpost_locker","inpost_letter"],"services":["inpost_locker_standard","inpost_locker_allegro","inpost_locker_pass_thru","inpost_locker_standard_smart","inpost_locker_allegro_smart","inpost_letter_allegro","inpost_courier_allegro","inpost_courier_c2c"],"address":POMINIĘTO,"street":"POMINIĘTO","building_number":POMINIĘTO,"line1":null,"line2":null,"city":"POMINIĘTO","post_code":"POMINIĘTO","country_code":"PL"},"invoice_address":{"id":POMINIĘTO,"street":"POMINIĘTO","building_number":"POMINIĘTO","line1":null,"line2":null,"city":"POMINIĘTO","post_code":"POMINIĘTO","country_code":"PL"},"contact_person":null,"created_at":"POMINIĘTO","updated_at":"POMINIĘTO"}
```

Mam dwie prośby:
- Czy możesz potwierdzić, że proces na wysylam.allegro.pl.allegrosandbox.pl w celu dodania umowy ShipX API działa? Uważam, że API ShipX mogło się zmienić, więc proces już nie działa.
- Jeśli podam Ci mój klucz ShipX API, czy możesz ręcznie dodać go do mojego konta wysylam.allegro.pl.allegrosandbox.pl, aby ominąć ten problem?

Dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Konsultuję sprawę z odpowiednim zespołem.
