### ISSUE TITLE
Problem z konfiguracją Sky Shop i Allegro

### ISSUE THREAD

**Issue by allegroskyshop** [allegro/allegro-api#4453]
Cześć, 
piszę z prośbą o pomoc, bo przeszukała forum i nie znalazłam odpowiedzi. 
Konfigurowałam Sky Shop z Allegro. Na koniec całego procesu jak miałam kliknąć w link z potwierdzeniem wyskoczył błąd i w Sky Shopie pokazuje się powiadomienie:
"Jedno z kont Allegro nie zostało zweryfikowane  w konfiguracji na stronie Allegro.
Z tego powodu integracja dla tego konta jest  NIEAKTYWNA!.
Potwierdź konto Allegro klikając w ikonkę w kolumnie:
" Potwierdzenie Allegro (aplikacji) - Dni do ponownego potwierdzenia"

Sprawdziłam i wszędzie mam ten sam adres URL, ale dalej nie wiem gdzie to aktywować stąd moja prośba o pomoc :)

**Comment by MartaNowaczyk** [comment]
Cześć,
nie wiem dokładnie jakie dane wpisujesz, dlatego najlepiej jakbyś skontaktowała się ze Sky-Shop. My nie mamy wglądu w to co robisz i co poszło nie tak. Zerknij na ich [ FAQ](https://sky-shop.pl/Pomoc-FAQ/Integracje-i-moduly/Integracja-z-Allegro/Jak-potwierdzic-aplikacje-Allegro), czy czegoś nei pominęłaś.
