### ISSUE TITLE
Invalidated Image URL is still active for some Accept header

### ISSUE THREAD

**Issue by casab** [allegro/allegro-api#4454]
I don't know Polish, so I had to skip the template. Sorry about that.

We use the following service to upload our images before creating an offer.
https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST

And the response is very clear. It gives an URL, and expiration date for the URL(typically 3 hours). It's all okay to this point. The problem is, the given URL still works after the expiration date BUT only for specific Accept header. 

Before creating an offer we check the URL to see if it is still valid. And if it is, we create an offer using the following service.
https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST

But even though we get a 200 response for the image URL, your sale/offers service responds with an error indicating that the URL is wrong. For some reason, it seems that the response is cached for either image/jpeg or image/webp and is not invalidated after the expiration date. Currently, it's possible to make a request to the image URL with `Accept: image/webp` header and obtain the image even though it should return 404. Since we can obtain the image, we are trying to create an offer without first reuploading the images, and we get the following error;

`Provided image address is incorrect.`

**Comment by MartaNowaczyk** [comment]
Please give me an example of this situation.

We don't support "image/webp". You will find this information in our [documentation].(https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST) We only support "image/ peg", "image/png".

**Comment by casab** [comment]
We use jpeg when uploading. That's not the problem. All of the following images were uploaded on 12th April and all of these URLs passed their expiration date. They should return 404, but somehow in some situations, they return 200. 

Just try few of the links on chrome, and then try to make a request with Postman with the header `Accept: */*` (default one). When opening the link in Chrome, chrome makes a request with the header `accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9` as default and we can see the image. But when we make a request with Postman, we get a 404 response. 

If this is the case, it's not really a problem, since we can always make a request with `Accept: */*` to check to see if the link is valid. But just two weeks ago, it was the other way around. Chrome responded with 404, while it was possible to get the image with Postman. So it's nondeterministic and vague. I am really not sure how we can check the validity of the URL if the behavior is changing over time.

P.S. We use `Cache-Control: no-cache` and `Pragma: no-cache` to prevent caching.


https://a.allegroimg.com/original/11c895/38f397bc47798af429df369d5abe
https://a.allegroimg.com/original/114056/4ce46bb641f497fdce1d2ad53ae6
https://a.allegroimg.com/original/1119eb/9616a39347728f247b8adb27c627
https://a.allegroimg.com/original/11b122/4236f9f44f1ca483b90891ba5c08
https://a.allegroimg.com/original/11b1ac/4f6fe3b0480782733a8142e56fb4
https://a.allegroimg.com/original/11012f/f4f2a3ce40f0b4e02669805fc31f
https://a.allegroimg.com/original/110700/907d49ea429a9c5ad74341a897f3
https://a.allegroimg.com/original/117baa/26c30eda43e8935f3a6bd98c9832
https://a.allegroimg.com/original/11d9fb/5fb581d046dd8e62dfb43b962e45
https://a.allegroimg.com/original/114c59/19cd0a72494bbad26fd312f56221
https://a.allegroimg.com/original/11a4ac/aa6ba6ab40a9b43db87a8ef15df7
https://a.allegroimg.com/original/113dd0/74653fec4f10bb39409332aa2549
https://a.allegroimg.com/original/111931/f6fcb0c54e4298dfe45cfbb625f5
https://a.allegroimg.com/original/11c747/5113a9d745a2b3170c9e45a805f8
https://a.allegroimg.com/original/11b84d/d6d37480489580c9e959d159cf39
https://a.allegroimg.com/original/11a1c7/ecaf32ef4e829cf1a1271e610755
https://a.allegroimg.com/original/116e91/0b1c350f4197b6bab562a331fb88
https://a.allegroimg.com/original/11e3eb/e7b462db4d7282c3d112c09d01d9
https://a.allegroimg.com/original/11a93a/cbac9ee84db78856ad71f545da37
https://a.allegroimg.com/original/11ff77/64b864f945768eb9561c160804ec
https://a.allegroimg.com/original/114740/6e6b300f435cac1a3893eac9dc08
https://a.allegroimg.com/original/11aee7/66f0dd5f464fbfcf79c288a3ed53
https://a.allegroimg.com/original/11b19e/cdfa4c10498a9fc0207e54bd8dc8

**Comment by MartaNowaczyk** [comment]
We'll check it out and let you know.

**Comment by MartaNowaczyk** [comment]
We analyzed the described problem and it is not a bug.
Trying to download an image to verify that it exists is not a good idea. We do not guarantee that if an image has expired in the system, it cannot be downloaded in 100%. You should know when those 3 hours were up.

**Comment by casab** [comment]
Alright, we can just compare with the expiration date, it's safer and easier anyway :smile: . Thanks for your time.
