### ISSUE TITLE
błąd wyglądu strony oferty

### ISSUE THREAD

**Issue by oponika** [allegro/allegro-api#4455]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [x] inny

:beetle: **Opis**
błąd wyglądu strony oferty
w podkategoriach 99193 (opony) parametr "Hałas zewnętrzny" ma zdublowany wyraz "dB" 
wygląda to tak: "Hałas zewnętrzny: 69 dB dB"
błąd jest we wszystkich ofertach przykładowy nr oferty: 10674355367

**Comment by MartaNowaczyk** [comment]
Problem nie dotyczy API Allegro, dlatego sprawę zgłoś przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
