### ISSUE TITLE
sale/offers Forbidden

### ISSUE THREAD

**Issue by 19konop93** [allegro/allegro-api#4456]
Witam

Od kilku dni próbuje stworzyć ofertę w serwisie allegrosandbox ale bez efektów.

Nazwa usera: 19konop93

Co robię pokolei:

Autoryzuje się za pomocą:
```
curl --location --request POST 'https://allegro.pl.allegrosandbox.pl/auth/oauth/device?client_id=XXX' \
--header 'Authorization: Basic  XXX' \
--header 'Content-Type: application/x-www-form-urlencoded' \
```

Później w kolejnym etapie 
```
curl --location --request POST 'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials&device_code=XXX' \
--header 'Authorization: Basic XXX' \
```

. Otrzymuje token oraz device code.
Problem występuje gdy chcę stworzyć draft oferty
```
curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/offers' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer XXX' \
--data-raw '{
      "name": "Oferta testowa"
}'
```

Otrzymuje komunikat 403 Forbidden:
```
{
    "errors": [
        {
            "code": "FORBIDDEN",
            "message": "Forbidden",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
} 
```
Drugim sposobem z jakiego korzystałem to próbowałem stworzyć testową ofertę przez endpoint sale/product-offers lecz otrzymuje 403 forbidden 
```
curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/product-offers' \
--header 'Accept: application/vnd.allegro.beta.v2+json' \
--header 'Content-Type: application/vnd.allegro.beta.v2+json' \
--header 'Authorization: Bearer XXX' \
--data-raw '{
"product": {                            
        "name": "Produkt testowy",
        "category":{
                "id":"89060"
        },
    "parameters":[
        {
                "name": "EAN",
                "values": [
                            "0744861045021"
                ]
            },
            {
                "id": "237218",
                "values": [
                        "Testowy tytuł"
                ]
            }
    ],
},
"sellingMode": {
        "price": {
            "amount": "220.85",        
            "currency": "PLN"
        }
},
 "stock": {
        "available": 10                 
}
}'
```

Czy jest problem jakiś z moim kontem? Lub robię coś w złej kolejności?
Proszę o informację.

Mam również pytanie odnośnie autoryzacji:
Mam aplikacje konsolową -bez dostępu do przeglądarki, bez dostępu do jakiegoś pola edycyjnego do potwierdzenia  autoryzacji użytkownika. Ta aplikacja będzie działać na serwerze co X minut i będzie tworzyć oferty oraz aktualizować stany. Czy jest możliwość aby zautoryzować użytkownika bez potrzeby klikania w link weryfikacyjny i bez potwierdzenia dostępu do zasobów użytkownika? 

Dziękuję i pozdrawiam

**Comment by 19konop93** [comment]
dodam, że curl'e są z postmana

**Comment by PrzemyslawLukanowski** [comment]
Błąd wskazuje na to, że korzystasz z tokena wygenerowanego w ramach autoryzacji [client-credentials](https://developer.allegro.pl/auth/#client-credentials-flow). Ten sposób autoryzacji nie ma kontekstu użytkownika i pozwala na dostęp tylko do publicznych danych (np. lista kategorii). W naszej [dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jakiego sposobu autoryzacji powinieneś użyć dla danego endpointu:
- bearer-token-for-user - [device ](https://developer.allegro.pl/auth/#device-flow)lub [code ](https://developer.allegro.pl/auth/#authorization-code-flow)flow;
- bearer-token-for-application - [client credentials](https://developer.allegro.pl/auth/#client-credentials-flow).

W przypadku bearer-token-for-user użytkownik musi jednorazowo zgodzić się, aby aplikacja mogła wykonywać żądania w jego imieniu. Następnie możesz już korzystać z [refresh tokenów](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena) w celu odświeżania daty ważności tokenów.
