### ISSUE TITLE
Enigmatyczne "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji." trace-id: 7b18db24f10f153f

### ISSUE THREAD

**Issue by pawliszka** [allegro/allegro-api#4457]
Proszę o pomoc w rozeznaniu problemu błędu 400 przy próbie wystawienia oferty z produktem.

**Dokumentacja techniczna z której korzystano**

https://developer.allegro.pl/product_offers/#jak-wystawi%c4%87-ofert%c4%99-z-produktem-kt%c3%b3rego-nie-ma-w-naszej-bazie

**Środowisko**

Sandbox

**Endpoint**

/sale/product-offers

**TraceID**

7b18db24f10f153f

**Payload**

```json
{"name":"PR\u00d3G REPERATURKA FIAT TEMPRA 90-96 LEWA","product":{"category":{"id":"254521"},"parameters":[{"id":"129591","valuesIds":["129591_1"]},{"id":"215858","values":["-"]},{"id":"127415","valuesIds":["127411_338645"]}]},"external":{"id":"[BLIC:6505-06-2025011P]"},"sellingMode":{"price":{"amount":"99000.00","currency":"PLN"}},"tax":{"percentage":"23.00"},"payments":{"invoice":"VAT"},"location":{"city":"Rybnik","postCode":"44-210","province":"SLASKIE","countryCode":"PL"},"parameters":[{"id":"11323","valuesIds":["11323_1"]},{"id":"129591","valuesIds":["129591_1"]},{"id":"214434","valuesIds":["214434_266986"]},{"id":"215858","values":["-"]},{"id":"127415","valuesIds":["127411_338645"]},{"id":"227349","valuesIds":["227349_342473"]}],"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"d9f7b30e-3518-49b6-8462-7d56e568c023"}},"stock":{"available":"99"}}
```

**Aktualny rezultat**

HttpMessageNotReadableException
Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.

**Oczekiwany rezultat**

kod HTTP: 201, 202 lub 422
błędy walidacji bądź stworzenie oferty i produktu

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku problem powoduje pole "name" - przesyłasz je poza obiektem "product", a zgodnie z załączonym linkiem, musi znajdować się bezpośrednio w nim. Pamiętaj także, aby dodać przynajmniej jedno zdjęcie produktu  sekcji product.images.

**Comment by pawliszka** [comment]
Dzięki wielkie!
