### ISSUE TITLE
Problem z zasobem POST /sale/offers/{offerId}/promo-options-modification

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#4458]
Po ustawieniu wyróżnienia, wszystko działa prawidłowo. Kolejne cykle działają prawidłowo...

Następnie w/w zasobem ustawiam zakończenie promowania z końcem cyklu, czyli payload requestu jest następujący:

```
{
  "modifications": [
    {
      "modificationType": "REMOVE_WITH_END_OF_CYCLE",
      "packageType": "BASE",
      "packageId": "emphasized10d"
    }
  ]
}
```
`packageId` zgodny z ustawionym dla oferty.

Otrzymuję prawidłową zwrotkę, bez błędów, pola `validFrom` (bez zmian), `validTo` (wpada prawidłowa data), `nextCycleDate` (brak daty) wyglądają prawidłowo....
ale jednak na końcu cyklu, promowanie się wznawia...

Jest jakiś błąd z tym zasobem, czy ja coś robię nie tak?

**Comment by MartaNowaczyk** [comment]
Najlepiej będzie jak podeślesz konkretny przykład przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), żebyśmy mogli to sprawdzić. Dopisz tylko, że wiadomość dotyczy wątku #4458 na GitHubie.

**Comment by MartaNowaczyk** [comment]
Dzięki za przykłady. Jak tylko sprawdzimy dam znać.

**Comment by mindc** [comment]
Znalazłem pewną rzecz, o której zapomniałem...
Podczas aktualizacji oferty podajemy parametry dla promowania, chodzi o klucz `promotion` z przykładowymi wartościami:
```
"promotion": {
  "emphasized": false,
  "bold": false,
  "highlight": false,
  "departmentPage": false,
  "emphasizedHighlightBoldPackage": false,
}
```

I teraz, nie ważne jaki stan ustawimy w zasobie `POST /sale/offers/{offerId}/promo-options-modification`, to ustawienie tutaj parametru `"emphasized": true` aktywuje promowanie, a ustawienie `"emphasized": false` wyłącza promowanie - po prostu ma wyższy priorytet...

Według mnie, albo trzeba ten parametr zrobić tylko do odczytu, albo rozszerzyć jego konfigurowalność (ale wtedy byłby zbędny tytułowy zasób) albo zrezygnować z interpretowania parametru `emphasized` w tym miejscu, bo to prowadzi właśnie do tytułowej sytuacji.

**Comment by MartaNowaczyk** [comment]
Mamy dwie możliwości promowania:

1. Opcje promowania w modelu oferty (promotions).
2. Opcje promowania oparte na pakietach.

Powinieneś używać 1 albo 2 i wtedy wszystko działa poprawnie.

**Comment by mindc** [comment]
@MartaNowaczyk 
nie do końca...
gdy ustawie promowanie przez `PUT /sale/offers/promo-options-commands`
to muszę uważać, aby przypadkiem podczas aktualizacji oferty nie ustawić `"emphasized": false` bo wyłączy mi promowanie
gdybym nie musiał aktualizować ofert, to by nie było problemu

**Comment by MartaNowaczyk** [comment]
Rozumiem, ale w najbliższym czasie nie planujemy wprowadzać zmian w promowaniu w modelu oferty .  

Na ten moment pozostaje mieć to na uwadze w chwili aktualizacji oferty.
