### ISSUE TITLE
Existing Product related to submitted data was found. The provided category `Thresholds` (254521) does not match the existing product category `Mudguards` (254683).

### ISSUE THREAD

**Issue by pawliszka** [allegro/allegro-api#4459]
Podczas wystawiania oferty z produktem na środowisku sandbox dostaję komunikat jak w tytule kod błędu 422.

Jak sobie radzić z podanym problemem (zakładam że sytuacja wystąpi również na produkcji)?

**Comment by MartaNowaczyk** [comment]
Taki błąd pojawia się w momencie, gdy w wystawianej ofercie masz inną kategorię, niż jest w produkcie + nie jest to też [kategoria podobna](https://developer.allegro.pl/product_offers/#jak-wystawi%c4%87-ofert%c4%99-w-kategorii-podobnej) dla tego produktu.

**Comment by pawliszka** [comment]
@MartaNowaczyk w tym konkretnym przypadku nie podaję kategorii (tylko kategorię produktu $.product.category.id) 

TraceID: 7d8f7982c2872e4c

Payload zawiera tylko dane produktu (próg / reperaturka progu) za to allegro tak jakby wymusza na mnie wystawienie tego produktu w kategorii błotniki

**Comment by MartaNowaczyk** [comment]
Nie widzę logów dla podanego trace-id. Podeślij proszę pełen request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) z dopiskiem, że dotyczy wątku #4459 na GitHubie.

**Comment by MartaNowaczyk** [comment]
@pawliszka ok, jednak udało mi się namierzyć. Przekazujesz dane produktu, ale na podstawie przesłanych informacji my znaleźliśmy produkt z takimi danymi, stąd błąd. Nie możesz stworzyć nowego produktu, bo mamy taki u nas (mimo, że ten produkt ma inną kategorię).

Jeśli według Ciebie kategoria nie będzie się zgadzała lub dane produktów są niewłaściwe, proszę skorzystaj z formularza https://allegro.pl/offer/product/report/{productId} i zgłoś swoje uwagi (dotyczy produkcji).

**Comment by pawliszka** [comment]
@MartaNowaczyk czy jest jakiś endpoint API do zgłaszania hurtowego produktów czy każdy produkt trzeba zgłosić ręcznie przez formularz ? 
Gdzie później mogę odebrać informację o stanie zgłoszonych produktów ? (akceptacji zmian / powodzie ich odrzucenia)

**Comment by MartaNowaczyk** [comment]
Nie ma takiego endpointu. Tylko podany wcześniej formularz daje taką możliwość. Informację o statusie znajdziesz na [naszej stronie ze zgłoszeniami](https://allegro.pl/moje-allegro/sprzedaz/zmiany-w-katalogu/zgloszenia).

**Comment by pawliszka** [comment]
@MartaNowaczyk ok dzięki wielkie zamykam :)
