### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by methadd** [allegro/allegro-api#446]
Witam,

Założyłem konto na sandbox allegro - adres email methadd@gmail.com - jak długo trzeba czekać na weryfikację i uruchomienie sprzedaży w środowisku testowym?

**Comment by MaciejPotepa** [comment]
Dzień dobry

Aktywowałem konto ręcznie żebyś nie musiał czekać.

**Comment by methadd** [comment]
Dziękuję bardzo
