### ISSUE TITLE
Błąd tworzenia paczki - błędny nr tel

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4460]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

 Błąd zarówno od frontu jak i API mimo, że numer jest podawany tylko jako 9 cyfr.
Nr paczki z api {119de127-511d-405b-b0bb-2325fee014e3}
lub zamówienie 2afc2362-acd9-11eb-931b-63af64f6372f
 
![image](https://user-images.githubusercontent.com/49162881/117114857-a2020480-ad8c-11eb-8abc-20abfc5c9a7b.png)

**Comment by MartaNowaczyk** [comment]
Sprawdzamy opisaną sytuację.

**Comment by MartaNowaczyk** [comment]
Wprowadzany numer to numer stacjonarny, stąd błąd.
