### ISSUE TITLE
Odrzucenie aplikacji Allegro API

### ISSUE THREAD

**Issue by 4mpro** [allegro/allegro-api#4461]
Odrzucili nam podanie o uwierzetelnienie aplikacji webAPI, napisanego przez naszego programistę, podając uzasadnienie że nie mamy konta VIP i 100 aktywnych użytkowników aplikacji (?). Nie wiem, jak mozna mieć 100 użtkowników aplikacji, skoro aplikacja jeszcze nie funkconuje. Proszę o pomoc w rozwiązaniu tego problemu, jakies dane kontaktowe do Allegro API. Bardzo zalezy nam na rozwiązaniu tego problemu.

**Comment by MartaNowaczyk** [comment]
"Allegro API" nie prowadzi weryfikacji i nie ustala kryteriów. Najlepszą drogą kontaktu w tej sprawie jest kontynuacja korespondencji jaką prowadziłeś w tej sprawie.
