### ISSUE TITLE
Could not resolve host: api.allegro.pl; Name or service not known

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4462]
Co jest przyczyną takiego błędu:

`{"errors":{"message":"Could not resolve host: api.allegro.pl; Name or service not known"}}`

**Comment by MartaNowaczyk** [comment]
Sprawdzaliśmy juz kiedyś podobny przypadek #4245 i nie znaleźliśmy problemu po naszej stronie. Jeśli nadal będziesz miał problem podeślij więcej danych za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c) do analizy. W zgłoszeniu dopisz, że dane dotyczą wątku  GitHub #4462.

**Comment by TimothyKoval** [comment]
[https://www.google.com/search?q=could+not+resolve+host](https://www.google.com/search?q=could+not+resolve+host)

**Comment by MartaNowaczyk** [comment]
@pietrach dane które podesłałeś nic nie wnoszą. Jak już to potrzebne są konkretne logi. Poza tym napisałeś, że raz działa, a raz nie + nie widzimy problemów z naszym API i nikt inny w tym momencie tego nie zgłasza, dlatego sugeruję, żebyś zbadał sprawę u siebie.
