### ISSUE TITLE
Tworzenie produktu z producent = inny

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4464]
Mam pytania o parametr producent.
Mojej nazwy producenta nie ma w słowniku allegro.
W trakcie tworzenia produktu przekazuję producent = inny + values['NOWY-PRODUCENT'].
Produkt zostaje utworzony.
Parametr odczytaliście prawidłowo i na jego podstawie utworzyliście automatyczną nazwę "NOWY-PRODUCENT + NR_KATALOGOWY".
Jak pobieram dane produktu to nie występuje w nim moja nazwa producenta.
Jak tworzę ofertę na podstawie tego produktu to nie zawiera mojej nazwy producenta.
Pytania:
Czy po utworzeniu nazwy nowego produktu zapominacie moją nazwę?
Czy jest szansa, że moja nazwa producenta gdzieś się pojawi?
Czy może muszę to zrobić inaczej?

Pozdrawiam,
KF

**Comment by MartaNowaczyk** [comment]
Wartość własna w takim przypadku powinna być widoczna w produkcie i w powiązanej z nim ofercie. Sprawdzamy opisaną sytuację. Jak tylko coś ustalimy dam znać.

**Comment by kfijalko** [comment]
@MartaNowaczyk czy możesz potwierdzić, że parametr zapisuje się właściwie w waszej bazie, a problemem jest wyświetlanie?
Ten watek mnie blokuje i nie pozwala na przekazywanie danych produktów (i wystawiania do nich ofert).

**Comment by MartaNowaczyk** [comment]
Po dodaniu produktu w bazie widać wartość własną, także wygląda to na brak wyświetlania/pobierania tej wartości. Sprawdzamy dlaczego tak się dzieje.

**Comment by kfijalko** [comment]
ok, dziękuję

**Comment by kfijalko** [comment]
@MartaNowaczyk czy coś się wyjaśniło?

**Comment by kfijalko** [comment]
@MartaNowaczyk  czy coś się wyjaśniło?

**Comment by MartaNowaczyk** [comment]
Wiemy w czym problem, jednak jest to dość złożone i na ten moment nie wiemy kiedy uda nam się przywrócić poprawne działanie.

**Comment by kfijalko** [comment]
@MartaNowaczyk poproszę o aktualny status.

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym jeszcze o cierpliwość, nasz zespół pracuje nad wypracowaniem rozwiązania.
