### ISSUE TITLE
Brak parametru warunkującego dla parametru zależnego

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#4467]
Pobieram listę parametrów dla kategorii Zdrowie -> Zdrowie intymne -> Lubrykanty i żele intymne. Otrzymuję listę 11 parametrów, w tym: 
```
            [10] => stdClass Object
                (
                    [id] => 225693
                    [name] => EAN
                    [type] => string
                    [required] => 1
                    [requiredForProduct] => 1
                    [unit] => 
                    [options] => stdClass Object
                        (
                            [variantsAllowed] => 
                            [variantsEqual] => 
                            [ambiguousValueId] => 
                            [dependsOnParameterId] => 11323
                            [requiredDependsOnValueIds] => Array
                                (
                                    [0] => 11323_1
                                )

                            [displayDependsOnValueIds] => 
                            [describesProduct] => 1
                            [customValuesEnabled] => 
                        )

                    [restrictions] => stdClass Object
                        (
                            [minLength] => 8
                            [maxLength] => 14
                            [allowedNumberOfValues] => 1
                        )

                )
```

Wymagalność parametru jest zależna od parametru 11323. Problem w tym, że parametru o takim ID nie ma na zwracanej liście. Co w takiej sytuacji?

**Comment by AureliuszBrussy** [comment]
Potwierdzam brak tego parametru w tej kategorii. Parametr 11323 to parametr "Stan", natomiast wszystkie produkty, które są sprzedawane w tej kategorii (id 259301) muszą być nowe, stąd brak tego możliwości skorzystania z tego parametru. Kwestię tego, że oznaczyliśmy ten paramert jako warunkujący konsultuję z odpowiednim zespołem. Wkrótce wrócę z odpowiedzią.

**Comment by czlowiekpolar** [comment]
@AureliuszBrussy potrzebuję informacji czy jest to błąd po Waszej stronie i poprawicie parametry w tej kategorii czy mamy robić obejścia u nas na takie niestandardowe przypadki?

**Comment by AureliuszBrussy** [comment]
@czlowiekpolar jeszcze analizujemy ten problem. Wrócę jeszcze z informacją.

**Comment by czlowiekpolar** [comment]
@AureliuszBrussy i jak postęp analizy? Błąd występuje również w innych kategoriach, przykładowo:
Zdrowie -> Suplementy diety -> Oczyszczanie
Supermarket -> Artykuły dla zwierząt -> Dla kotów -> Preparaty
Supermarket -> Artykuły dla zwierząt ->   Dla psów ->   Preparaty
Supermarket -> Artykuły dla zwierząt ->  Dla psów ->  Witaminy
Supermarket -> Artykuły dla zwierząt -> Dla fretek ->  Karmy i przysmaki

**Comment by AureliuszBrussy** [comment]
Jeszcze nie wypracowaliśmy podejścia. Proszę o jeszcze trochę cierpliwości - wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@czlowiekpolar przygotujemy odpowiednią poprawkę - nie będziemy pokazywać zależności parametru, jeżeli ten nie jest zwracany w danej kategorii. Wrócę z informacją po wdrożeniu takiej poprawki.

**Comment by AureliuszBrussy** [comment]
@czlowiekpolar wdrożyliśmy poprawkę. Problem nie powinien już występować.
