### ISSUE TITLE
Device Flow

### ISSUE THREAD

**Issue by daniel682** [allegro/allegro-api#4468]
Witam

Chciałbym napisać aplikację w C# i użyć autoryzacji Device Flow, ale napotkałem pewien problem. Wysyłam zapytanie na adres **https://allegro.pl/auth/oauth/device** z wszystkimi potrzebnymi danymi i otrzymuję zwrotnie dane poprawnie i teraz przed wysłaniem requesta na adres **https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}** należy dokonać autoryzacji przy pomocy **verification_uri** i **user_code**. Czy jest możliwość dokonania tej autoryzacji z poziomu aplikacji bez konieczności wchodzenia na stronę tak by potem można było otrzymać token? Oczywiście z podaniem loginu i hasła do konta allegro.

**Comment by MartaNowaczyk** [comment]
Trzeba przejść na stronę verification_uri - patrz [kroki 3, 4a, 5](https://developer.allegro.pl/auth/#device-flow-autoryzacja-u%c5%bcytkownika ).
