### ISSUE TITLE
Problem z dodaniem aukcji

### ISSUE THREAD

**Issue by tomek66m** [allegro/allegro-api#4469]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, mam problem ponieważ nie mogę dodać nowej aukcji przez stronę https://staging-lokalnie.allegrogroup.com/oferty/wystaw - chcę skorzystać z sandboxa i dodać przykładową aukcję, aby przetestować jak działa moja aplikacja. Kliknięcie w zakładce "Moje Oferty" przycisku "Dodaj Nową" przekierowuje mnie na wyżej podaną, niedziałającą stronę

**Comment by MartaNowaczyk** [comment]
Dziękuję za zgłoszenie - przekazałam do odpowiedniego zespołu. Na tę chwilę skorzystaj proszę z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by cyfranT** [comment]
Wiadomo kiedy to będzie naprawione? To raczej podstawowa funkcjonalność, a trzeba szukać po forum poprawnego linku :/

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak na ten moment nie mamy konkretnego terminu.
