### ISSUE TITLE
Allegro REST API tak po prostu przestało sobie działać...

### ISSUE THREAD

**Issue by thsPL** [allegro/allegro-api#447]
Witam,
Mam dość. Kod działał przez około 2 miesiące i od paru dni nic (wyświetla tylko "koniec"). print_r($wynik) nie wyświetla nawet error'a o jakimś błędzie, tak jakby nie było w ogóle połączenia. Co może być tego przyczyną? Jakiś ban na Allegro, czy może cichaczem weszła jakaś zmiana konfiguracji na moim serwerze (jeśli tak, to jak to sprawdzić?). Wcześniej było ok, działało i nie było problemów. Dodam jeszcze, że aplikacje w webapi allegro działają na szczęście bez problemów, chociaż pewnie nie będzie to miało z tym żadnego związku. Znowu trzeba będzie się nieźle narobić, żeby wszystko zostało po staremu. Te Wasze ciągłe zmiany są o kant d... warte.

`
error_reporting(E_ALL);
ini_set('display_errors', 1);
$hand = curl_init("https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=$kod&redirect_uri=$redirect_uri");
curl_setopt($hand, CURLOPT_POST, 1);
curl_setopt($hand, CURLOPT_HTTPHEADER,array(
"Authorization: Basic ".base64_encode("$client_id:$client_secret")
));
curl_setopt($hand, CURLOPT_RETURNTRANSFER, true);
$wynik=curl_exec($hand);
curl_close($hand);

print_r($wynik);

echo "koniec";
`

Z góry dzięki za pomoc.

**Comment by kormichu** [comment]
Skorzystaj z http://php.net/manual/en/function.curl-error.php

**Comment by thsPL** [comment]
> Skorzystaj z http://php.net/manual/en/function.curl-error.php

Dzięki, przynajmniej jest jakiś error "Curl error: SSL connect error". Mój ssl działa od dłuższego czasu raczej bezproblemowo. Nie wiem czy to ma związek, ale otwierając stronę https://ssl.allegro.pl/ dostaję taki komunikat w oknie przeglądarki:

Pętla przekierowań
Podczas łączenia z serwerem ssl.allegro.pl wystąpił błąd.
    Problem ten może się pojawić w wyniku zablokowania lub odrzucenia ciasteczek.

Dziwne jest tylko to, że nikt wcześniej nie zgłaszał takiego problemu. Wszyscy na plaży siedzą? :p

Grzebać dalej, czy wina jednak leży po stronie monopolisty od aukcji internetowych?

Wkurzające jest to, że wczoraj straciłem pół dnia żeby sprawdzić co się stało, a finalnie okaże się jak to już nie raz bywało, że problem leży po drugiej stronie...

**Comment by kormichu** [comment]
https://github.com/allegro/allegro-api/issues/65

**Comment by thsPL** [comment]
> #65

Faktycznie, nie mniej jednak to i tak nie rozwiązuje mojego problemu. W żadnym ze skryptów nie odwoływałem się do https://ssl.allegro.pl/

**Comment by thsPL** [comment]
>Zaktualizowałeś TLS na >= 1.1?

Nie wiem, czy dobrze to sprawdzam, ale otwierając np. stronę na której znajduje się ten skrypt we właściwościach przeglądarki mam takie informacje o stronie (Szczegóły techniczne):

Połączenie szyfrowane (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 128-bitowe klucze, TLS 1.2)

Więc domyślam się, że to raczej nie ten problem...

**Comment by MaciejPotepa** [comment]
Dzień dobry

Chciałbym pomóc, ale do tego potrzebuję treści requestu i response zapisanego bezpośrednio w jsonie.

**Comment by thsPL** [comment]
Sam nie wiem, ale jakoś udało mi się rozwiązać ten problem. Rzeczywiście problemem chyba był TLS. Niczego nie instalowałem, php_info() pokazywało mi, że tls 1.0, tls 1.1 i tls 1.2 są włączone. Rozwiązaniem było dopisanie do kodu jednej linijki:

`curl_setopt($hand, CURLOPT_SSLVERSION, 6);`

Może to dla większości jest oczywiste, ale napiszę - może się komuś przyda: 6 to TLS 1.2 właśnie. Bez tego ustawienia próbował się łączyć przez wersję 1.0 (tak mniemam). Jak wygenerować request w jsonie na podstawie tego kodu, który wrzuciłem na samej górze... nie mam pojęcia. Response tak jak pisałem wyżej nie było żadnego, bo nie doszło nawet do połączenia (wynikiem był pusty string). Dzięki za sugestię curl-error, bo to pomogło mi w ogóle zacząć cokolwiek szukać. Wersję TLS w sumie podejrzewałem od początku, ale nie za bardzo wiedziałem jak się do tego zabrać (w sumie nadal nie wiem jak zainstalować aktualizację TLS na serwerze, gdyby zaszła taka konieczność). Dzięki za pomoc. Problem rozwiązany. Pozdrawiam.
