### ISSUE TITLE
Potwierdzenie powiązania z Allegro - your connection is not private

### ISSUE THREAD

**Issue by RudaBaska** [allegro/allegro-api#4470]
Nie możemy potwierdzić zwrotnie powiązania SkyShop z Allegro. Po kliknięciu na link następuje blokada przekierowania, jako że połączenie nie jest bezpieczne. Nie możemy tego obejść, proszę o pomoc! https://www.hvh6rl.webwave.dev/allegro?codeXYZ -> Your connection is not private. Próbowałyśmy z: Linux (Peppermint) -> Mozilla, Windows -> Mozilla, Brave Browser oraz Avast Secure Browser, po usunięciu ciastek, a także wejściu przez prywatne okno, problem taki sam wszędzie. Co możemy jeszcze zrobić? 
![konf-allegro_LI](https://user-images.githubusercontent.com/83842336/117507629-9890bc00-af87-11eb-9713-c30c83f661ef.jpg)

**Comment by AureliuszBrussy** [comment]
Z przesłanego linku wynika, że nie są Państwo przekierowywani do Allegro.pl w celu powiązania konta. Tutaj niestety nie pomożemy. Proszę, aby zgłosili Państwo ten problem do supportu SkyShopa.
