### ISSUE TITLE
Jak sprawdzić czy własne konto Allegro ma status Super Sprzedawcy?

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#4471]
Przejrzałem wiele metod (w tym **/me, /sale/offers, /sale/user-ratings**) - ale nigdzie nie znalazłem informacji o statusie Super Sprzedawcy. Mówię tu oczywiście o własnych kontach zalogowanego użytkownika.
Paradoksalnie jedyna metoda, która zwraca taką informację to publicznie dostępna **/offers/listing** (bearer-token-for-app)
Jednakże ona pobiera listę aukcji, a przy każdej z nich zwraca pole **superSeller**: **true/false**.

Czy naprawdę żadna metoda z **Bearer-token-for-user** nie zwraca statusu super sprzedawcy???

**Comment by AureliuszBrussy** [comment]
Nie ma sposobu, aby sprawdzić, czy użytkownik jest Super Sprzedawcą - zwracamy taką informację tylko we wspomnianym przez Ciebie **GET /offers/listing**. Twoje zgłoszenie w takim przypadku potraktuję jako sugestię - zgodnie z [naszym newsem](https://github.com/allegro/allegro-api/issues/4337) przeniosłem wątek do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).
