### ISSUE TITLE
Jak dodać tabelę rozmiarów do oferty?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4473]
Witam,

chciałbym dodać tabelę rozmiarów do moich ofert. Problem jest taki, że nie mogę znaleźć w dokumentacji informacji, jak to zrobić. Nie ma żadnego wyszczególnionego pola w zapytaniu tworzącym szkic, w którym mógłbym podać identyfikator tabeli (wzorując się na sposobie dodawania warunków reklamacji czy gwarancji).

Czy jest możliwość dodania tabeli rozmiarów z poziomu API i jak to zrobić?

**Comment by PrzemyslawLukanowski** [comment]
Nie ma takiej możliwości, możesz jednak zagłosować [na taką sugestię ](https://github.com/allegro/allegro-api/discussions/4413)w zakładce Discussions. Więcej informacji na temat sugestii i zakładki Discussions znajdziesz[ w naszym newsie](https://github.com/allegro/allegro-api/issues/4337).

**Comment by hahyes** [comment]
> Nie ma takiej możliwości, możesz jednak zagłosować [na taką sugestię ](https://github.com/allegro/allegro-api/discussions/4413)w zakładce Discussions. Więcej informacji na temat sugestii i zakładki Discussions znajdziesz[ w naszym newsie](https://github.com/allegro/allegro-api/issues/4337).

Dziękuję za odpowiedź. Poszedł głos. ;)

Jednakże dziwi mnie to biorąc pod uwagę, że zauważam takie tabele u innych sprzedawców. Zakładam, że są dodawane ręcznie przez front, gdzie jest to możliwe.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, tabelę możesz stworzyć przez [front](https://allegro.pl/moje-allegro/sprzedaz/tabele-rozmiarow), jednak w API udostępniamy tylko [metody GET](https://developer.allegro.pl/documentation/#tag/Size-tables), które służą do pobierania informacji o nich. Dla jasności - tabelę, którą utworzyłeś przez front, możesz oczywiście dodać do oferty także przez API - gdy tworzysz lub edytujesz ofertę, przekaż jej ID w polu **sizeTable.id.**

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za wprowadzenie błąd. Opis tego pola znajdziesz [w pkt 8. poradnika ](https://developer.allegro.pl/sale/#11-uzupe%c5%82nij-dane-w-ofercie) (przykładowy request) oraz w dokumentacji dla [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) i [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

**Comment by hahyes** [comment]
> Opis tego pola znajdziesz [w pkt 11. poradnika ](https://developer.allegro.pl/sale/#11-uzupe%c5%82nij-dane-w-ofercie) (przykładowy request) oraz w dokumentacji dla [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) i [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

Zwracam honor, wyszukiwarka w dokumentacji mnie oszukała jak i wyszukiwarka przeglądarki w poradniku (teraz widzę, że wyszukuje, nie wiem jak to zrobiłem).

Jednak sugeruję dodać jakiś podpunkt w poradniku pod Opcje dodatkowe o pobieraniu i dodawaniu do oferty tabeli rozmiarów. Jak na tak przydatną funkcjonalność, jest praktycznie niewidoczna.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię. W najbliższej przyszłości dodamy taki punkt, aby informacja była bardziej widoczna.
