### ISSUE TITLE
Nie dostaję wszystkich ofert po wyszukaniu po external.id

### ISSUE THREAD

**Issue by myszaq99** [allegro/allegro-api#4474]
Gdy zaciągam oferty wywołując poniższy URL to nie dostaję danych o ofercie numer: 9733337932. Dlaczego?
https://api.allegro.pl/sale/offers?external.id=114132&offset=0&limit=999

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i podane zapytanie zwraca w wynikach ofertę 9733337932

**Comment by myszaq99** [comment]
To zapytanie zwraca mi 90 ofert, ale 9733337932 brak. Co może być tego powodem?
