### ISSUE TITLE
"Unprocessable Entity" - /order/checkout-forms/{checkOutFormId}/fulfillment

### ISSUE THREAD

**Issue by oosebossoo** [allegro/allegro-api#4475]
Mam następujący problem... Nie mogę zmienić statusu zamówienia.

> **$status** = "PROCESSING";
> public static function changeStatus(**$checkOutFormId**, **$token**, **$status**){
>  **$response** = Http::withHeaders([
>   "Accept" => "application/vnd.allegro.public.v1+json",
>   "Content-Type" => "application/vnd.allegro.public.v1+json",
>   "Authorization" => 'Bearer '.**$token**
>   ])->put("https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/**$checkOutFormId**/fulfillment", [
>     "body" => ["status" => **$status**]
>   ]);
>  dd(**$response**);
> }

![image](https://user-images.githubusercontent.com/24655673/117654197-b895ca80-b195-11eb-9a08-8f59a2070176.png)

Tak wygląda response, 
proszę o pomoc!

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Błąd 422 wskazuje na błędną strukturę żądania. Podaj proszę trace-id lub id zamówienia, to sprawdzę co mamy w logach.

**Comment by oosebossoo** [comment]
ID zamówienia: 1617790334872130
Dodam że pracuje n aśrodowisku testowym

**Comment by barthoos** [comment]
Zaczalem dostawac masowe blady 422. Ponizej kilka trace-id:

55e442d86be4313a
5ad8e02d1ccec0c2
aacd8afd109aa1a6
b560d3f15eb138c2

**Comment by MartaNowaczyk** [comment]
@barthoos Oferty, które znalazłam na podstawie podanych trace-id są już zarchiwizowane. Oferty przenosimy do archiwum po 60 dniach od zakończenia, stąd mógł wystąpić problem z ich aktualizacją. Sprawdzamy jeszcze przesłany request. Tam też udzielimy odpowiedzi.
