### ISSUE TITLE
W parametrze EAN (225693) można zdefiniować maksymalnie jedną wartość.

### ISSUE THREAD

**Issue by zulus** [allegro/allegro-api#4476]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Próbuję wystawić aukcję powiązaną z produktem. Grzecznie kopiuje dane z produktu `77a372cb-d77b-4b18-bf2f-46bf0d943ae1`. W zamian dostaje komunikat: `W parametrze EAN (225693) można zdefiniować maksymalnie jedną wartość.`. 

Gdzieś macie dziure  i można zapisać produkt z nieprawidłowymi parametrami, lub co gorsza jak wprowadzacie nowe kagańce to nie sprawdzacie bazy pod ich kątem.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego działu. Wrócę z informacją po wyeliminowaniu błędu.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku - podobnie jak działa to na froncie - powinieneś wybrać jeden z dostępnych EAN-ów. Produkt może mieć wiele EAN-ów, gdy np. pochodzi z różnych dystrybucji, jednak w samej ofercie musisz już wskazać jedną konkretną wartość.

**Comment by zulus** [comment]
Tyle że w dokumentacji jak mantra napisane jest `zgodne z wybranym produktem parametry i ich wartości parametrów`. Niema info że trzeba jeszcze te parametry obrabiać. 

Pytanie czy to tylko EAN czy możemy jakoś sprawdzić które parametry przyjmą tylko jedną wartość?

**Comment by PrzemyslawLukanowski** [comment]
Dodamy odpowiednią wzmiankę w naszym poradniku, aby zwrócić uwagę na tę kwestię.

W odpowiedzi dla [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) znajdziesz pola:
- **restrictions.allowedNumberOfValues** (dla parametrów typu string), którym zwracamy informację, ile maksymalnie wartości możesz przekazać w danym parametrze, gdy tworzysz ofertę,
- **restrictions.multipleChoices** (dla parametrów typu dictionary), w którym zwracamy informację, czy możesz przekazać więcej niż jedną wartość w danym parametrze, gdy tworzysz ofertę.

**Comment by zulus** [comment]
Tego się obawiałem. Czyli wystawianie aukcji po produkcie, z punktu widzenia API wydłuża i komplikuje zamiast upraszczać proces:

1. Znajdź produkt po EAN
2. Wciągnij parametry dla kategorii produktu
3. Sprawdź zgodność danych produktu z mapą parametrów kategorii (usuń zbędne, uzupełnij dodatkowe)
4. Wystaw aukcję

W sytaucji gdy niema jak śledzić zmian na produktach w aukcjach, cacheowanie nie wchodzi w grę. Przy kilkudzisięciu tysiącach aukcji jest to problematyczne (a pobranie po EAN ciut trwa), tym bardziej że np często wymagna "strona zabudowy" i tak trzeba na sztywno określać że brak danych (TEC ma tabeli 410 parametry dla wybranego pojazdu/silnika/etc..). Po mojemu jak już oznaczam aukcje jako produktowe, endpoint powinien wypełnić co się da samemu bez copy/paste/fix. Przygotuję odpowiednią sugestię.

**Comment by Lukasz-Zurek** [comment]
@zulus Dziękuję za przesłane uwagi. Możesz dokładnie opisać sugestię/propozycję w tym wątku - przeniosę ją wtedy do naszej zakładki [Discussions](https://github.com/allegro/allegro-api/discussions). Ewentualnie możesz utworzyć odrębny wątek na tej stronie.
