### ISSUE TITLE
Requirements to get approved fro rest api

### ISSUE THREAD

**Issue by Steam365** [allegro/allegro-api#4477]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

 How lonig selling history should be ? is it based on period of time while seller is selling, or incomes , or other points ?

**Comment by PrzemyslawLukanowski** [comment]
Do you mean requirements for using GET /offers/listing ([news](https://github.com/allegro/allegro-api/issues/4213))? This topic is beyond API technical issues, so please use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) to ask additional questions. Other endpoints can be used without any requirements.

**Comment by Steam365** [comment]
well guys after contacted them via form redirected to ask for more details,
requirements for approvment for api here, so can somemone finally tell me
what are exact requirements to get approved?

2021-05-11, an, 09:20 PrzemyslawLukanowski ***@***.***> rašė:

**Comment by Lukasz-Zurek** [comment]
@Steam365 This topic is beyond API technical issues so I guess they fowarded you to our github site incorrectly. I would like to apologize for this situation. Still you should receive a specific answer directly from Customer Service, which you have already contacted via contact form. It is the only way.
