### ISSUE TITLE
HTTP response code: 415 podczas uploadu grafik

### ISSUE THREAD

**Issue by Kasjan95** [allegro/allegro-api#448]
Od kilku tygodniu tworze apke w Javie i stanąłem na wrzucaniu grafiki na serwer. Niestety bez powodzenia. Mój kod:

		    URL obj = new URL("https://upload.allegro.pl/sale/images");
		    HttpURLConnection conn = (HttpURLConnection) obj.openConnection();

		    conn.setRequestMethod("POST");
		    conn.setRequestProperty("Authorization", "Bearer "+getToken());
		    conn.setRequestProperty("accept", "application/vnd.allegro.beta.v1+json");
		    conn.setRequestProperty("content-type","image/png");
		    conn.setRequestProperty("accept-language", "pl-PL");
		    conn.setDoOutput(true);

		    String data = "";
		    BufferedReader in = new BufferedReader(new FileReader(img));
		    String inputLine;
		    while ((inputLine = in.readLine()) != null) {
		    	data += inputLine;
		    }   
		    in.close();
		    OutputStreamWriter out = new OutputStreamWriter(conn.getOutputStream());
		    out.write(data);
		    out.close();

		    new InputStreamReader(conn.getInputStream()); `
Odpowiedz
`java.io.IOException: Server returned HTTP response code: 415 for URL: https://upload.allegro.pl/sale/images`

Bardzo podobny kod napisałem w PHP i działa bez problemu. Czy ktoś jest w stanie podpowiedzieć w czym problem?

**Comment by rtnet-pl** [comment]
Nie znam javy, ale chyba nie kodujesz obrazka do base64?

**Comment by Kasjan95** [comment]
Znalazłem błąd, dziekuje **rtnet-pl** za natchnienie 👍 Błędem była próba wysłania pliku jako String, (w PHP niema takiego problemu) i zadziałał kod:
`byte[] data = Files.readAllBytes(img.toPath());
DataOutputStream  out = new DataOutputStream (conn.getOutputStream());`
Dziekuje za pomoc
