### ISSUE TITLE
Limity allegro

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#4481]
Cześć,
Jak działa ten limit 9tysięcy zapytań na minute? robię około 20/30 zapytań i dostaje odpowiedź o przekroczonym limicie. Jakie są prawdziwe limity? Chciałbym ustawic zabezpieczenia w aplikacji aby nie wywyalało błędów.

**Comment by MartaNowaczyk** [comment]
Może to zależeć od tego jaki zasób odpytujesz. W naszym [FAQ](https://developer.allegro.pl/faq/#limity-i-ograniczenia) znajdziesz informacje o limitach.

**Comment by MartaNowaczyk** [comment]
Limit na tym zasobie jest inny niż 9000 rpm. Związany jest on z [zapowiedzianą zmianą](https://github.com/allegro/allegro-api/issues/4213). Aby móc wykonać większą liczbę zapytań, zweryfikuj swoją aplikację, zgodnie z [komunikatem](https://github.com/allegro/allegro-api/issues/4213).

**Comment by lukaszkrakowiak** [comment]
Czyli aktualnie powinien być 9000, ale po 1 czerwca powinien się zmienić.

**Comment by MartaNowaczyk** [comment]
Jeśli aplikacja będzie zweryfikowana (a po 1 czerwca każda musi być) to limit powinien być 9000 rpm.
