### ISSUE TITLE
Problem z  payment-operations

### ISSUE THREAD

**Issue by SebastianGalazka** [allegro/allegro-api#4482]
Podczas pobierania payment-operations z REST API, zawsze są zwracane dane z 5 dniowym opóźnieniem pomimo podania prawidłowych parametrów occurredAt.gte, occurredAt.lte jaka może być tego przyczyna?

**Comment by MartaNowaczyk** [comment]
Nie wiem co tam masz dokładnie w swoim zapytaniu. Podaj go proszę pomijając wrażliwe dane. Możesz też podesłać pełen request przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), to sprawdzę - w wiadomości podaj numer wątku na GitHubie: #4482

**Comment by SebastianGalazka** [comment]
Takie parametry wysyłam:
```
{ "occurredAt.gte", after.ToString("2021-04-11T08:00:00Z") },
{ "occurredAt.lte", before.ToString("2021-05-11T08:00:00Z") },
{ "limit", "100" },
{ "offset", (pageNumber * 100).ToString() }
```

a całe zapytanie wygląda tak:
`  using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + ConfigurationManager.AppSetting["AccessToken"].ToString());
                    PaymentOperationRoot paymentOperations = new PaymentOperationRoot();
                    List<PaymentOperation> paymentOperationList = new List<PaymentOperation>();
                    int pageNumber = 1;
                    bool endWhile = false;

                    while (!endWhile)
                    {
                        var queryString = new Dictionary<string, string>()
                        {
                            { "occurredAt.gte", after.ToString("yyyy-MM-ddTHH:mm:ssZ") },
                            { "occurredAt.lte", before.ToString("yyyy-MM-ddTHH:mm:ssZ") },
                            { "limit", "100" },
                            { "offset", (pageNumber * 100).ToString() }
                        };
                        var requestUri = QueryHelpers.AddQueryString("https://api.allegro.pl/payments/payment-operations", queryString);
                        var webRequest = new HttpRequestMessage(HttpMethod.Get, requestUri);
                        webRequest.Headers.TryAddWithoutValidation("Accept", "application/vnd.allegro.public.v1+json");
                        var response = client.Send(webRequest);
                        if (response.StatusCode == HttpStatusCode.Unauthorized)
                        {
                            RefreshToken();
                            return GetPaymentsOperationToDate(after, before);
                        }
                        else
                        {
                            var reader = new StreamReader(response.Content.ReadAsStream());
                            var operationsTemp = JsonConvert.DeserializeObject<PaymentOperationRoot>(reader.ReadToEnd());
                            if (operationsTemp != null && operationsTemp.paymentOperations.Count > 0)
                            {
                                paymentOperationList.AddRange(operationsTemp.paymentOperations);
                                pageNumber++;
                            }
                            else
                            {
                                endWhile = true;
                            }
                        }
                    }
                    paymentOperations.paymentOperations = paymentOperationList;

                    return paymentOperations;
                }`
