### ISSUE TITLE
Problem z wystawianiem ofert ze sklepu

### ISSUE THREAD

**Issue by aquatech-fun** [allegro/allegro-api#4484]
Występuje problem: <VALIDATION_ERROR You cannot publish offer without a related product because you have too few offers related to a product in that category. Select or create a new product and associate it with your offer>

 
:beetle: **Podczas wystawiania produktów ze sklepu pojawia się kominikat. Co jest powodem i co zmienić?

**Comment by MartaNowaczyk** [comment]
Tak jak mówi błąd. Masz za mało ofert powiązanych z produktem. W niektórych kategoriach wymagamy, by pewien % ofert powiązany był z produktem. Informujemy o tym np. [tutaj](https://github.com/allegro/allegro-api/issues/4367).

**Comment by aquatech-fun** [comment]
Proszę o rozwiązanie problemu. Jeden produkt mi się dodał a jak próbuję dodać następne to otrzymuje taki komunikat. Co mam zrobić.... Podczas dodawanie nie mam żadnej zakładki pt np dodaj do katalogu lub coś takiego. Tak jak wspomniałem jeden produkt się dodał a następne już nie.....

**Comment by MartaNowaczyk** [comment]
Rozumiem, że dodajesz produkt w zewnętrznej aplikacji. Jeśli tak zgłoś się do jej twórcy/obsługi, bo nie wiem jak ona działa.

**Comment by aquatech-fun** [comment]
To nie problem aplikacji tylko powiązań z katalogiem wprowadzonym przez Allegro. Nie wiem kto i po co wprowadził taki system. Zupełnie błędne rozwiązanie i utrudniające działanie. Po wrzuceniu produktu do allegro trzeba wejść do panelu i kliknąć powiaz z produktem.... I wtedy działa. Bzdura kompletna.Pozdrawiam TomekWysłano z telefonu Huawei-------- Oryginalna wiadomość --------Od: MartaNowaczyk ***@***.***>Data: śr., 12 maj 2021, 07:16Do: allegro/allegro-api ***@***.***>DW: aquatech-fun ***@***.***>, Author ***@***.***>Temat: Re: [allegro/allegro-api] Problem z wystawianiem ofert ze sklepu (#4484)

Rozumiem, że dodajesz produkt w zewnętrznej aplikacji. Jeśli tak zgłoś się do jej twórcy/obsługi, bo nie wiem jak ona działa.

**Comment by MartaNowaczyk** [comment]
Problem nie dotyczy API Allegro. Jeśli masz uwagi dotyczące katalogu produktów zgłoś je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
