### ISSUE TITLE
Problem ze zmianą ceny aukcji na Sandbox

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4485]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: `f966acd15df9aa24`

Próbujemy aktualizować cenę aukcji, testowaliśmy na 2 kontach ale niestety dostajemy zwrotkę:
`OFFER_PRICE_CHANGE_ERROR`

błąd pojawił się nagle na sandboxie, na produkcji działa prawidłowo, testowaliśmy to kilka dni i nagle padło

czy zepsuliśmy coś na 2 naszych kontach czy jednak to sandbox ma problemy? :)

**Comment by MartaNowaczyk** [comment]
Konsultuję ten błąd z odpowiednim zespołem. Wrócę do Ciebie z odpowiedzią jak tylko uda nam się coś ustalić.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i zgadza się - na sandboxie od wczoraj był taki problem, także nic nie zepsuliście - to nasz błąd. Dzisiaj nie powinien już występować.

**Comment by kpodemski** [comment]
Dziękuje za informacje. To dobrze :)
