### ISSUE TITLE
Weryfikacja danych konta sandbox

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#449]
Witam,
bardzo się czeszę że w końcu powstało środowisko testowe w którym przynajmniej da się zarejestrować.
Niestety aby wystawić aukcję muszę zweryfikować moje konto. 
Tu również bardzo się cieszę że zostało to połączane z sandboxowym kontem payu dzięki czemu nie muszę płacić tej złotówki.
ALE żeby nie było tak kolorowo:
Poważnie muszę 3 dni na weryfikację konta sanboxowego ?
Jeśli zakładam konto testowe to znaczy że chcę testować już, teraz, zaraz, a nie za trzy dni.
Naprawdę nie da się zrobić żeby weryfikacja konta na sandboxie była instant ?

**Comment by PawelTaberski** [comment]
Nie musisz tyle czekać podeślij swój login zweryfikujemy Twoje konto testowe.

**Comment by mzawodzinski** [comment]
Mój login to: aa
Nie dałby by się przynajmniej zrobić jakiego przycisku "weryfikuj konto sanbox"

**Comment by PawelTaberski** [comment]
Konto powinno już być aktywne.

**Comment by mzawodzinski** [comment]
Tak działa, dziękuję.
A nie dało by się tego zrobić automatycznie ? 
Nie żeby się czepiał ale jak by mi ktoś miał co chwilę zawracać D.. to wolałbym zrobić do tego jakiś automat.

**Comment by PawelTaberski** [comment]
Środowisko testowe w kwestii rejestracji działa na tej samej zasadzie co produkcyjne, dlatego tak to wygląda, ale przekażę Pana sugestię do odpowiedniego zespołu.

**Comment by DawidZylski** [comment]
Mój login: Demax666
Proszę o weryfikację.

**Comment by DawidZylski** [comment]
Hmm, dwa razy już rejestrowałem konto ale żadnego emaila nie otrzymałem.

**Comment by mzawodzinski** [comment]
Musisz się zarejestrować tu https://allegro.pl.allegrosandbox.pl/
oczywiście trzeba podać istniejący adres mailowy na który dostaniesz kod do aktywacji konta.
Po kliknięciu w link aktywacyjny będziesz musiał jeszcze podać kod sms którego nie dostaniesz.
Z tego co pamiętam to można tam podać cokolwiek, a ja zawsze podawałem 1234 i działało.

Następnie wybierasz opcję "wystaw aukcję" i dopiero tam opcja weryfikacji.

**Comment by DawidZylski** [comment]
Właśnie na tego emaila nie mogę się doczekać.

**Comment by PawelTaberski** [comment]
Podeślij przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#subjectId=7e8e35b6-d773-4a0a-8d38-c056148165e8) maila na jaki zakładałeś konto na sandboxie, a następnie wklej tutaj numer ticketa. Sprawdzimy w czym jest problem.

**Comment by DawidZylski** [comment]
Ok email doszedł. Proszę teraz o weryfikację konta: Demax666

**Comment by PawelTaberski** [comment]
@DawidZylski Konto atywowałem.

**Comment by DawidZylski** [comment]
Dziękuję bardzo.

Pozdrawiam
Dawid Żylski

**Comment by Pyrykymyny** [comment]
Dzień dobry,
Można prosić o aktywację konta?
Login: sprzedazfirmowa

**Comment by AureliuszBrussy** [comment]
@Pyrykymyny przejdź proszę cały proces weryfikacji w zakładce [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto). Chodzi o wykonanie symulacji przelewu weryfikacyjnego oraz o załączenie dowolnych (fikcyjnych) plików w następnych krokach aktywacji konta. Gdy to zrobisz, daj znać - aktywuję konto.

**Comment by Pyrykymyny** [comment]
Zrobione :) dziękuję za szybką reakcję  
  Dnia 16 maja 2023 09:35 AureliuszBrussy   napisał(a):  
 github.com @Pyrykymyny  przejdź proszę cały proces weryfikacji w zakładce  allegro.pl.allegrosandbox.pl Moje konto . Chodzi o wykonanie symulacji przelewu weryfikacyjnego oraz o załączenie dowolnych (fikcyjnych) plików w następnych krokach aktywacji konta. Gdy to zrobisz, daj znać - aktywuję konto.

**Comment by AureliuszBrussy** [comment]
@Pyrykymyny aktywowałem Twoje konto.

**Comment by Pyrykymyny** [comment]
Dziękuję! 
  Dnia 16 maja 2023 13:39 AureliuszBrussy   napisał(a):  
 github.com @Pyrykymyny  aktywowałem Twoje konto.

**Comment by p-wel** [comment]
@AureliuszBrussy mam ten sam problem, kod SMS 1234 nie działa.
Poproszę o aktywację mojego konta w Allegro Sandbox.

Login:
Client:105998825

**Comment by AureliuszBrussy** [comment]
@p-wel wybrałeś konto zwykłe - uzupełnij proszę dane (imię, nazwisko, adres - oczywiście dane fikcyjne), a następnie dokonaj testowego zakupu - konto zostanie aktywowane.

**Comment by AureliuszBrussy** [comment]
@p-wel aktywowałem Twoje konto.

**Comment by krwicher** [comment]
@AureliuszBrussy jeśli mogę prosić o aktywację mojego konta:
login: wichre

Zmieniłem na konto biznesowe, dokonałem zakupu, ale wciąż jest problem z wystawieniem oferty.

**Comment by AureliuszBrussy** [comment]
@krwicher aktywowałem Twoje konto.

**Comment by kubinho1032** [comment]
@AureliuszBrussy również prosiłbym o aktywację konta, login: tortytest. Wykonałem przelew testowy oraz dokonałem zakupu.

**Comment by NekoBroadway** [comment]
@AureliuszBrussy cześć. Mogę prosić o aktywację konta? Login: sanbox_ammag

**Comment by AureliuszBrussy** [comment]
@NekoBroadway aktywowałem Twoje konto.

**Comment by Pyrykymyny** [comment]
Witam.
Proszę o aktywacje konta.
Login: BastekDaria

**Comment by AureliuszBrussy** [comment]
@Pyrykymyny aktywowałem Twoje konto.

**Comment by Cupik83** [comment]
Witam.

Prosiłbym o weryfikację konta: TiO

**Comment by MaciejFrackowiak** [comment]
@Cupik83 Proszę dokończ proces aktywacji - wykonaj przelew oraz prześlij dokumenty (oczywiście fikcyjne pliki) - zrobisz to uzupełniając tzw. [krokowiec](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by adakon87** [comment]
Dzień dobry,

bardzo proszę o weryfikację konta: firmowepaliwo321

Dziękuję

**Comment by MaciejFrackowiak** [comment]
@adakon87 Proszę dokończ proces aktywacji - wykonaj przelew oraz prześlij dokumenty (oczywiście fikcyjne pliki) - zrobisz to uzupełniając tzw. [krokowiec](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by adakon87** [comment]
> @adakon87 Proszę dokończ proces aktywacji - wykonaj przelew oraz prześlij dokumenty (oczywiście fikcyjne pliki) - zrobisz to uzupełniając tzw. [krokowiec](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

Wydaje mi się, że udało mi się to zrobić. Czy możesz sprawdzić?

**Comment by MaciejFrackowiak** [comment]
@adakon87 Udało się - konto jest już aktywne.

**Comment by adakon87** [comment]
> @adakon87 Udało się - konto jest już aktywne.

Dziękuję. Mam problem na koncie klienckim: Client:106048847 
Nie mogę dokonać testowego zakupu gdyż weryfikacja numeru nie przyjmuje fejkowego numeru telefonu. Przekroczyłem limit wysyłki kodów weryfikacyjnych. Bardzo proszę o wsparcie.

**Comment by MaciejFrackowiak** [comment]
@adakon87 Uzupełnij proszę dane wymienionego konta, wówczas będę mógł je aktywować również.

**Comment by adakon87** [comment]
@MaciejFrackowiak czy możesz zerknąć teraz?

**Comment by Cupik83** [comment]
@MaciejFrackowiak 

Zrobione więc prosiłbym o weryfikację konta: TiO

**Comment by MaciejFrackowiak** [comment]
@adakon87 Powinno być OK.

**Comment by adakon87** [comment]
> @adakon87 Powinno być OK.

@MaciejFrackowiak Dziękuję za szybką i sprawną pomoc. Pozdrawiam :)

**Comment by michasiatko** [comment]
Cześć, 
Proszę w miarę możliwości o przyspieszenie- simplymation_pl, przelew zrobiony, dokument załączony, warunki uzupełnione.

Miłego dnia!

**Comment by MaciejFrackowiak** [comment]
@Cupik83 Konto zweryfikowane.

**Comment by MaciejFrackowiak** [comment]
@michasiatko Twoje konto również jest już zweryfikowane.

**Comment by Pyrykymyny** [comment]
Dzień dobry.
Bardzo proszę o aktywacje konta.
Login: Bastik

**Comment by PrzemyslawLukanowski** [comment]
@Pyrykymyny Aktywowałem Twoje konto.

**Comment by Darayavus** [comment]
Cześć,
Proszę o pomoc w aktywacji konta: Darayavus
Wydaje mi się, że uzupełniłem i przeklikałem wszystko, a od tygodnia chyba "wisi" ta weryfikacja. 

Dziękuje i pozdrawiam

**Comment by MaciejFrackowiak** [comment]
@Darayavus Konto już jest zweryfikowane.

**Comment by MichalKujawski** [comment]
Cześć,
Również proszę o pomoc w aktywacji i weryfikacji konta allegro sandbox.
Login do konta: SprzedawcaPog
@MaciejFrackowiak @PrzemyslawLukanowski  @AureliuszBrussy 

Dziękuje

**Comment by MartaNowaczyk** [comment]
@MichalKujawski na koncie SprzedawcaPog masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki.

**Comment by MichalKujawski** [comment]
@MartaNowaczyk 
Dziękuję za szybką odpowiedź
Dane zostały uzupełnione.
login: SprzedawcaPog

**Comment by MartaNowaczyk** [comment]
@MichalKujawski aktywowałam Twoje konto.

**Comment by MichalKujawski** [comment]
> @MartaNowaczyk 
Działa, pierwsza oferta wystawiona.
Dziękuję za pomoc.
Pozdrawiam

**Comment by bercik97** [comment]
@MartaNowaczyk 

Prośba o pomoc w aktywacji i weryfikacji konta allegro sandbox.
Login do konta: papugas2

Dziękuje :)

**Comment by MartaNowaczyk** [comment]
@bercik97 aktywowałam Twoje konto papugas2.

**Comment by wallykrk** [comment]
Dzień dobry,
bardzo proszę o weryfikację konta: Piotrek-PTR
Dziękuję

**Comment by PrzemyslawLukanowski** [comment]
@wallykrk Aktywowałem Twoje konto.

**Comment by potejtooo** [comment]
Proszę o weryfikację konta: potejto

**Comment by AureliuszBrussy** [comment]
@potejtooo przez ograniczenia techniczne nie mogę wykonać weryfikacji przy zmianie statusu konta na firmowe dla konta założonego kilka lat temu. Zarejestruj proszę [nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto).

**Comment by potejtooo** [comment]
@AureliuszBrussy nowe konto: potejto1

**Comment by AureliuszBrussy** [comment]
@potejtooo aktywowałem Twoje konto.

**Comment by anopak** [comment]
@AureliuszBrussy mogę prosić o aktywacje konta: testephp oraz ephp (jeżeli możliwe, bo stare konto)

**Comment by Lukasz-Zurek** [comment]
@anopak W imieniu kolegi - aktywowałem wskazane konta. Jeżeli chodzi o drugie: ephp - widnieje tam blokada sprzedaży, więc będziesz musiał skorzystać z symulatora płatności, by uregulować "należności" ;) Zrobisz to [tutaj](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro). Oczywiście w razie problemów ze zdjęciem blokady sprzedaży - daj proszę znać w wątku.

**Comment by anopak** [comment]
@Lukasz-Zurek dziękuję bardzo za szybką reakcję :) na ephp zostało opłacone, jednak komunikat o blokadzie nadal widnieje - czy to poprawnie? :)

**Comment by Lukasz-Zurek** [comment]
@anopak Nie do końca poprawnie, dlatego zdjąłem już blokadę ręcznie :)

**Comment by anopak** [comment]
@Lukasz-Zurek wygląda ok - dziękuję

**Comment by Szymson9x** [comment]
Zmieniłem konto zwykłe na konto firmowe. Podczas aktywacji rachunku bankowego po kilku dniach otrzymuję informację, że rachunek nie jest powiązany z użytkownikiem. W zakładce "Zweryfikuj dane firmy" proces zatrzymał się na "Weryfikujemy dane Twojej firmy". Login: szymson9x

**Comment by AureliuszBrussy** [comment]
@Szymson9x aktywowałem Twoje konto.

**Comment by michjoh** [comment]
Proszę o weryfikację konta yulihobby
Dziękuję

**Comment by AureliuszBrussy** [comment]
@michjoh aktywowałem Twoje konto.

**Comment by DudekPrzemek** [comment]
Proszę o aktywację konta: imet2test

**Comment by AureliuszBrussy** [comment]
@DudekPrzemek przejdź proszę cały tzw. "krokowiec" z poziomu zakładki [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto) - wykonaj symulację przelewu weryfikacyjnego oraz uzupełnij dane. Daj znać, gdy to zrobisz. Wtedy aktywuję konto.

**Comment by lukas3891** [comment]
Dzień dobry czy można prosić o weryfikację konta sandbox o loginie: lukpart
Od 2 tygodni mam info że trwa weryfikacja rachunku bankowego i danych firmy

**Comment by Hachiiko** [comment]
Potrzebuję wsparcia i pomocy z kontem allegro sandbox. :) Dodałam testowe dane oraz "zweryfikowałam" rachunek bankowy przelewami na sandboxie, ale nadal niestety konto nie jest w pełni aktywne i nie mogę wystawić pierwszej oferty, ani też po prostu w pełni aktywować konta żeby pracować z rest api. Czy mogę poprosić o ręczną aktywację?
Login: patrycjakepka

**Comment by AureliuszBrussy** [comment]
@Hachiiko aktywowałem Twoje konto.

**Comment by Kuracha** [comment]
Mógłbym prosić o aktywację konta na sandbox, płatność wykonana, login to: Jan_Niezbedny

**Comment by MartaNowaczyk** [comment]
@Kuracha na tym kocie masz wybraną niepełną opcję sprzedażową. Wejdź proszę do [ustawień konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/warunki-sprzedazy), skorzystaj z linku, który masz na dole "[WRÓĆ DO WYBORU WERYFIKACJI](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty)" i wybierz "Weryfikacja pełna". Uzupełnij dane i prześlij dowolne pliki, abym mogła aktywować to konto.

**Comment by sGrzechnik** [comment]
Dzień dobry,
Chciałbym prosić o weryfikacje konta firmowego na sandbox.
Login: DNatura

**Comment by PrzemyslawLukanowski** [comment]
@sGrzechnik Aktywowałem Twoje konto.

**Comment by MartaNowaczyk** [comment]
@Kuracha teraz jest już wybrana pełna opcja sprzedażowa, status się zgadza, więc aktywowałam konto Jan_Niezbedny.

**Comment by michalscislowski** [comment]
Proszę o weryfikację konta firmowego 
Login: Soundoshi

**Comment by Lukasz-Zurek** [comment]
@michalscislowski Konto jest już w pełni aktywne.

**Comment by Janek2444** [comment]
Witam, proszę o aktywację konta firmowego: SanCapit

**Comment by PrzemyslawLukanowski** [comment]
@Janek2444 Aktywowałem Twoje konto.

**Comment by Janek2444** [comment]
Proszę o weryfikację konta firmowego:
sin244

**Comment by Lukasz-Zurek** [comment]
@Janek2444 Aktywowałem konto.

**Comment by ItTookaQuarry** [comment]
Proszę o weryfikację konta firmowego:
PrzemoDeadlift12

**Comment by Lukasz-Zurek** [comment]
@ItTookaQuarry Wskazane przez Ciebie konto ma status zwykłego. Aby przekonwertować je na firmowe, skorzystaj proszę z [tej strony](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta). Następnie [skonfiguruj wypłaty](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i skorzystaj z naszego symulatora płatności w celu potwierdzenia.

**Comment by ItTookaQuarry** [comment]
Ok. Mam teraz na koncie informację że weryfikujecie dane mojej firmy.

**Comment by Lukasz-Zurek** [comment]
@ItTookaQuarry Ok, udało mi się teraz aktywować Twoje konto.

**Comment by mzawodzinski** [comment]
Nie żeby mi to jakoś przeszkadzało ale ten problem występuje od ponad 5lat. Naprawdę to aż taki problem zrobić to automatycznie?

**Comment by Lukasz-Zurek** [comment]
@mzawodzinski Owszem, masz rację. Obecnie musimy wszystkie takie konta aktywować manualnie, co również nie jest dla nas komfortowym procesem. Próbowaliśmy ten proces zautomatyzować. Niestety nie jest to temat w pełni zależny od nas i na ten moment nie będzie to możliwe.

**Comment by Herc84** [comment]
@Lukasz-Zurek to teraz poproszę o aktywacje konta z loginem Herc84

**Comment by Lukasz-Zurek** [comment]
@Herc84 Konto już w pełni aktywne :)

**Comment by ag-sell** [comment]
@Lukasz-Zurek czy ja też mogę prosić  o aktywację konta? Login TestoweSI

**Comment by ag-sell** [comment]
> @ag-sell Proszę prześlij jeszcze dowolne pliki jako dokumenty firmowe oraz wykonaj przelew weryfikacyjny poprzez symulator płatności - zrobisz to w tzw. krokowcu na stronie [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

Zrobione :)

**Comment by MaciejFrackowiak** [comment]
@ag-sell I ode mnie gotowe.

**Comment by ag-sell** [comment]
@MaciejFrackowiak działa! Dziękuję :)

**Comment by danielburchardt** [comment]
@ag-sell prośba o akceptacje - danieltajny

**Comment by Juraso2** [comment]
@MaciejFrackowiak ja również proszę o akceptację - DanielGorillas

**Comment by MaciejFrackowiak** [comment]
@danielburchardt Konto aktywowane.

**Comment by MaciejFrackowiak** [comment]
@Juraso2 Konto aktywowane.

**Comment by SmiejczakL** [comment]
Zmieniłam dane na aktywnym koncie i trwa ponowna weryfikacja danych firmy, proszę o ponowną aktywację konta Coc_sandbox

**Comment by AureliuszBrussy** [comment]
@SmiejczakL aktywowałem Twoje konto.

**Comment by wbiegala-insert** [comment]
Poproszę o aktywację, nazwa: geralt

**Comment by AureliuszBrussy** [comment]
@wbiegala-insert aktywowałem Twoje konto.

**Comment by matecz11** [comment]
Dzień dobry, proszę o aktywowanie konta firmowego; **login: 106890777**.
Dzięki, pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
@matecz11 Aktywowałem Twoje konto.

**Comment by Planche95** [comment]
Poproszę o aktywowanie konta firmowego; login: tkaniewski95

**Comment by Lukasz-Zurek** [comment]
@Planche95 Konto w pełni aktywne.

**Comment by wolpaw2005** [comment]
Proszę o aktywację konta test_2024

**Comment by AureliuszBrussy** [comment]
@wolpaw2005 aktywowałem Twoje konto.

**Comment by look4meX** [comment]
Proszę o weryfikację konta SPORT_SHOP_PL

**Comment by Lukasz-Zurek** [comment]
@look4meX Konto już w pełni aktywne.

**Comment by Aleksandrze** [comment]
Proszę o aktywację konta: mrooczek

**Comment by Lukasz-Zurek** [comment]
@mwinciorek Widzę, że zarejestrowałeś konto zwykłe. Aby móc testować np. proces wystawiania ofert - przekonwertuj konto na firmowe. Zrobisz to w [tej](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) zakładce. Następnie przejdź do [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i skorzystaj ze wspomnianego symulatora płatności.

**Comment by Najndrok333** [comment]
Proszę o aktywację konta: Najndrok

**Comment by AureliuszBrussy** [comment]
@Najndrok333 aktywowałem Twoje konto.

**Comment by mwinciorek** [comment]
> @mwinciorek Widzę, że zarejestrowałeś konto zwykłe. Aby móc testować np. proces wystawiania ofert - przekonwertuj konto na firmowe. Zrobisz to w [tej](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) zakładce. Następnie przejdź do [ustawień wypłat](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) i skorzystaj ze wspomnianego symulatora płatności.

Ponawiam prośbę o aktywację konta: Client:106913080 . Aktualnie proces wisi na weryfikacji rachunku bankowego i weryfikacji danych firmy (obie czynności były już robione).

**Comment by MaciejFrackowiak** [comment]
@mwinciorek Wskazane konto jest już aktywne.

**Comment by PrzemyslawWachowski** [comment]
Proszę o aktywację konta: Test2024

**Comment by AureliuszBrussy** [comment]
@PrzemyslawWachowski to konto jest kontem zwykłym - aktywujesz je podczas pierwszej transakcji.

**Comment by PrzemyslawWachowski** [comment]
#
Zrobione - zmieniłem na konto firmowe oraz wysłałem testowy przelew

> @PrzemyslawWachowski to konto jest kontem zwykłym - aktywujesz je podczas pierwszej transakcji.

**Comment by AureliuszBrussy** [comment]
@PrzemyslawWachowski przejdź proszę tzw. krokowca (uzupełnijąc fikcyjne dane i wykonując symulację przelewu weryfikacyjnego) z poziomu [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto). Wtedy będę mógł aktywować Twoje konto.

**Comment by PrzemyslawWachowski** [comment]
Teraz powinno przejść, wcześniej wysłałem na Allegro Pay Business.

> @PrzemyslawWachowski przejdź proszę tzw. krokowca (uzupełnijąc fikcyjne dane i wykonując symulację przelewu weryfikacyjnego) z poziomu [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto). Wtedy będę mógł aktywować Twoje konto.

**Comment by Sucharmen** [comment]
Proszę o aktywacje konta: DNatura2

**Comment by MaciejFrackowiak** [comment]
@Sucharmen Konto aktywne.

**Comment by KarolRzepka** [comment]
@MaciejFrackowiak Proszę o aktywacje konta: karoldevcoody

**Comment by MaciejFrackowiak** [comment]
@KarolRzepka Gotowe.

**Comment by lukoc** [comment]
Proszę o aktywację konta sandboksowego: lanaccount2

**Comment by MartaNowaczyk** [comment]
@lukoc aktywowałam twoje konto.

**Comment by wolodzkom** [comment]
Również proszę o aktywację na sandbox. oksspl

**Comment by MaciejFrackowiak** [comment]
@wolodzkom Konto aktywne.

**Comment by piatekpatryk** [comment]
Prosba o aktywacje konta sandbox, login: patpia

**Comment by AureliuszBrussy** [comment]
@piatekpatryk aktywowałem Twoje konto.

**Comment by swpw** [comment]
Proszę o aktywacje konta sandbox, login: sandbox111

**Comment by MaciejFrackowiak** [comment]
@swpw Konto aktywne.
