### ISSUE TITLE
Zakończenie aukcji - metody

### ISSUE THREAD

**Issue by tryton-slawekk** [allegro/allegro-api#4490]
Wg dokumentacji, aby zakończyć aukcję, należy użyć PUT /sale/offer-publication-commands/{commandId}
Czy dla pojedynczej aukcji mogę także użyć PATCH /sale/product-offers/{offerId} i ustawić array("publication" => array("status" => "ENDED"))?
Czy te metody będą wtedy tożsame?
No i pytanie w drugą stronę: czy tak samo mogę dwojako wykonać reaktywację zakończonej aukcji?

SK

**Comment by MartaNowaczyk** [comment]
Tak, możesz użyć PATCH /sale/product-offers/{offerId} aby aktywować/zakończyć ofertę. Więcej znajdziesz w naszym [poradniku](https://developer.allegro.pl/product_offers/#zmiana-statusu-oferty).
