### ISSUE TITLE
Offer Description HTML Issues

### ISSUE THREAD

**Issue by Peymanpn** [allegro/allegro-api#4491]
Hello Allegro Team,

We have created an API to automate creating/updating Offers, but we are having a issues with HTML contents.
It seems Allegro won't accept descriptions if there is a small issue with it quite strictly. 
Is there any way we could avoid it?
for example if there is an `&` entity in the text, the API will send it back with validation errors and asking our clients to do all these manual work to fix these text issues will defeat the purpose of automation, since it's a lot easier with posting contents through Allegro's online html box.
I will be grateful if you could help me with the topic, or any suggestion.

Kind Regards

**Comment by MartaNowaczyk** [comment]
Hello Peymanpn, 
In this case, you have to replace & with &nbsp; etc. - via Rest API we have no other way to help in this situation. 
Kind Regards
