### ISSUE TITLE
Problem z null w paidAmount przy płatności ONLINE i P24

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4492]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witajcie. Od jakiegoś czasu (kilku godzin) mamy niepokojące raporty o wartości `null` w `paidAmount`, wygląda to u nas tak:

```
[payment] => stdClass Object
        (
            [id] => 94111482-b2ee-11eb-adda-REMOVED
            [type] => ONLINE
            [provider] => P24
            [finishedAt] => 2021-05-12T06:54:38.766Z
            [paidAmount] => 
            [reconciliation] => 
        )
```

Nie mieliśmy wcześniej takiej sytuacji, nie jest to też `EPT`, klient dał nam screen z Allegro.pl gdzie zamówienie jest uznane jako `Opłacone`, a płatność to `0`, to jakiś nowy scenariusz czy jednak jakiś problem z produkcją?

**Comment by MartaNowaczyk** [comment]
Podaj proszę numer zamówienia.

**Comment by kpodemski** [comment]
Chodzi o zamówienie `58f7af81-b2ee-11eb-9bd9-2bf2cac956b8`

Na pytanie innym kanałem wsparcia (ponieważ to dla nas krytyczna sytuacja) dostaliśmy informacje, że to błąd Allegro.pl 🤔

**Comment by MartaNowaczyk** [comment]
Zgadza się, to nasz błąd. Pracujemy nad poprawką.

**Comment by BartekWroclaw** [comment]
u nas ten sam problem.

**Comment by Lukasz-Zurek** [comment]
Wdrożyliśmy poprawkę. Zwracamy już prawidłowe wartości w `paidAmount`.
