### ISSUE TITLE
Could not change offer publication status. Size table is not allowed in selected category

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#4493]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dlaczego podczas wznowienia oferty w kategorii obuwia zwraca błąd "Could not change offer publication status. Size table is not allowed in selected category.". Dzieje się tak tylko przy pierwszej próbie, po ponowieniu żądania błędu nie ma i aferta jest wznawiana?

**Comment by dwalczyk** [comment]
U mnie ten sam błąd

``
{"errors":[{"code":"VALIDATION_ERROR","message":"Size table is not allowed in selected category.","details":"","path":"","userMessage":"Nie mo\u017cesz wystawi\u0107 oferty z tabel\u0105 rozmiar\u00f3w w podanej kategorii."}]}
``

id kategorii = 89528

**Comment by MartaNowaczyk** [comment]
Podajcie prosze jakieś trace-id dla tego błędu.

**Comment by SlawomirMizerski** [comment]
trace-id: 215481ef552a889b

**Comment by MartaNowaczyk** [comment]
Dzięki, sprawdzam.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie, wygląda to na problem naszego serwisu. Poprawimy to, jak tylko uda nam się znaleźć przyczynę.

**Comment by Lukasz-Zurek** [comment]
@SlawomirMizerski @dwalczyk Wdrożyliśmy już poprawkę. Powinno być ok.

Przepraszamy za utrudnienia.
