### ISSUE TITLE
Pobranie EANu

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4497]
Witam,
chciałabym się dowiedzieć czy jest możliwość pobrania samego EANu z konkretnej oferty by móc go zapisać do bazy danych ? Aktualnie mam pobraną ofertę z wszystkimi danymi (w tym z EANem). Podobnie będę chciała pobrać numer oferty.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Niestety nie pobierzesz samego EANu, lub numeru oferty. Nie mamy takich zasobów.

Możesz jedynie pobrać pełne dane konkretnej oferty za pomocą: [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Musisz być autoryzowana jako sprzedawca.

**Comment by Kasia13130** [comment]
Rozumie, dziękuję za odpowiedź.
