### ISSUE TITLE
Połączenie konta allegro z platformą sky shop

### ISSUE THREAD

**Issue by EmkaStudio** [allegro/allegro-api#4499]
Dzień dobry, próbuję zintegrować Allegro z platformą sky-shop. 
Wydawało się, że proces przebiega dobrze, ale na końcu pojawił się taki komunikat (na platformie sky-shop);
"Jedno z kont Allegro nie zostało zweryfikowane w konfiguracji na stronie Allegro.
Z tego powodu integracja dla tego konta jest NIEAKTYWNA!.
Potwierdź konto Allegro klikając w ikonkę w kolumnie:
"Potwierdzenie Allegro (aplikacji) - Dni do ponownego potwierdzenia" 

Chodzi o konto EmkaStudio_Insp  Proszę o podpowiedz, co mam dalej zrobić. 
Bardzo dziękuję. 
Marta Kłuciejasz

**Comment by MartaNowaczyk** [comment]
Nie wiem dokładnie jakie dane wpisujesz w Sky-Shop. Na pewno nie dodałaś (na naszej [stronie do zarządzania](https://apps.developer.allegro.pl/)) aplikacji z adresem przekierowań:  http://sklepnaskyshop.pl/allegro. Zerknij w [FAQ Sky-Shop.](https://sky-shop.pl/Pomoc-FAQ/Integracje-i-moduly/Integracja-z-Allegro/Jak-potwierdzic-aplikacje-Allegro)
