### ISSUE TITLE
ERROR Niepoprawnie wypełniono koszt dostawy

### ISSUE THREAD

**Issue by lokneey** [allegro/allegro-api#45]
Witam.
Korzystam z WebAPI pisząc w C#. Próbuję wystawić aukcję używając doNewAuctionExt() i ciągle otrzymuję error "Niepoprawnie wypełniono koszt dostawy (należy podać wartość we wszystkich trzech polach: pierwsza sztuka, kolejna sztuka, ilość w paczce - lub jedynie dla pierwszej sztuki)."

Nie jestem w stanie zidentyfikować w czym problem, ponieważ mam wszystkie dane wypełnione zgodnie z informacjami uzyskanymi z doGetSellFormFieldsForCategory(). 

Podaję ceny we floatach, ilość w integrantach, pilotażowo próbuję wystawić aukcję tylko z możliwością wysyłki kurierskiej (fid: 44, 144, 244). Czy jest jakieś dodatkowe kryterium, które muszę tutaj wypełnić?

**Comment by MaciejPotepa** [comment]
Żeby Ci pomóc i zobaczyć w czym leży problem potrzebujemy treści request i response zapisanych w XMLu. 

Wyślij zgłoszenie przez [formularz kontaktowy](https://pomoc.allegro.pl/kontakt) z załączonymi plikami, a tutaj wklej numer zgłoszenia.

**Comment by MaciejPotepa** [comment]
Jeżeli chcesz, może również wrzucić treść request i response tutaj - w odpowiedzi do tego wątku. 
Chętnie pomogę rozwiązać problem.

**Comment by lokneey** [comment]
W załącznikach pliki, które mi wyrzucił Fiddler, dla request po którym jest błąd.
[5_Request.txt](https://github.com/allegro/allegro-api/files/1794440/5_Request.txt)
[5_Response.txt](https://github.com/allegro/allegro-api/files/1794441/5_Response.txt)

**Comment by MaciejPotepa** [comment]
```
<fid xsi:type="xsd:int">44</fid>
            <fvalue-int xsi:type="xsd:int">0</fvalue-int>
            <fvalue-float xsi:type="xsd:float">21</fvalue-float>
            <fvalue-datetime xsi:type="xsd:float">0</fvalue-datetime>

```
Spróbuj wysłać request podając tylko uzupełnione wartości. XML jest waliduje każde pole, jeżeli w int podajesz 0, a we float 21 to dochodzi konfliktu.

**Comment by lokneey** [comment]
Problem w tym, że wypełniam wartość tylko dla float. Te zera muszą być w jakiś sposób dopisywane domyślnie. Może przyczyną odrzucenia requesta jest coś innego?
![obraz](https://user-images.githubusercontent.com/25988408/37242443-e1dd4362-2469-11e8-8832-43b96f6caceb.png)

**Comment by lokneey** [comment]
Czy macie pojęcie w czym może leżeć problem i jak go naprawić? 
Z tego co się zorientowałem problemy może sprawiać niezgodność typów xsi:type=xsd:string. Występuje to przy każdym response po próbie wystawienia aukcji.
![1](https://user-images.githubusercontent.com/25988408/37292383-1fabb13a-2611-11e8-8cb0-d3319021e6bc.png)
![2](https://user-images.githubusercontent.com/25988408/37292384-2062d55e-2611-11e8-9085-ec95e1c1fc18.png)
![3](https://user-images.githubusercontent.com/25988408/37292385-208fb9f2-2611-11e8-9cc4-f8a661c50144.png)

**Comment by MaciejPotepa** [comment]
Wydaje mi się, że problem leży w tym o czym pisałem w poprzednim poście. Twój program dodaje do requesta przed wysłanie pola o różnych wartościach. 

Spróbuj zmodyfikować kod tak, aby nie dodawał niczego poza tym co wpisujesz. 

Mogę również podpowiedzieć żebyś wystawił ofertę przez [Formularz wystawiania](https://allegro.pl/offer/) i pobrał ją za pomocą [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842). Dzięki temu zobaczysz jak powinieneś wypełnić wszystkie pola, których potrzebujesz w ofercie.

**Comment by lokneey** [comment]
Okey, znalazłem problem. Miałem zaimplementowaną inicjalizację nowych obiektów każdej komórki FieldsValue[]. Przez inicjalizację komórek dla fid, których nie używałem pojawiały się problemy z akceptacją niewypełnionych pól dostawy. 
Dla każdego komu zdarzy się mieć taki problem polecam tworzyć obiekt tylko dla komórek, których mamy zamiar używać. 
Pozdrawiam.
