### ISSUE TITLE
Problem ze zmianą ilości przy użyciu metody doChangeQuantityItem

### ISSUE THREAD

**Issue by pablokol** [allegro/allegro-api#450]
Przy próbie zmiany ilości dla oferty https://allegro.pl/lamela-lilia-doniczka-donica-wklad-25x25-cm-i6767555569.html pojawia się błąd Podano nieprawidłową liczbę przedmiotów.
Próbujemy ustawić ilość 3 korzystając z metody doChangeQuantityItem

**Comment by PawelTaberski** [comment]
Pamiętaj, że aby zmienić liczbę sztuk dostępnych w danej trwającej ofercie przez WebAPI podana przez Ciebie wartość musi uwzględniać liczbę przedmiotów dotychczas sprzedanych w tej ofercie. 
Obliczysz ją w następujący sposób: liczba sprzedanych sztuk + liczba sztuk, która ma być dostępna w ofercie. 
Na przykład: oferujesz 100 sztuk. Sprzedało się już 95 i chcesz, by w ofercie było dostępnych teraz 10 sztuk. 95 +10 = 105 - tyle sztuk podaj podczas edycji

**Comment by PawelTaberski** [comment]
W podanej ofercie co prawda już jakiś czas temu bo w marcu i w maju sprzedałeś w sumie 3 sztuki.

**Comment by pablokol** [comment]
To tutaj dotykamy drugiej kwestii, od strony frontu prezentowana jest obecnie dostępna ilość 6 i 0 sprzedanych. Jeśli zmienię ilości zgodnie z opisem: 3 (ilość która chce aby była dostępna) + ilość której kiedyś była sprzedana to jaka ilość będzie widoczna od frontu dla klientów?
Jeśli dobrze pamiętam to Ilości sprzedane można pobrać na korzystając z dwóch metod: doGetMySellItems i doGetMySoldItems. Czy ilości dla ofert należy pobierać korzystając z tych dwóch metod: najpierw doGetMySoldItems a później doGetMySellItems ?

**Comment by PawelTaberski** [comment]
Jeśli sprzedałeś 3 a chcesz, aby były teraz dostępne 3 sztuki musisz podać w tej metodzie 6. Czyli tak pisałem wcześniej: "liczba sprzedanych sztuk + liczba sztuk, która ma być dostępna w ofercie".
A odnośnie sprawdzenia to tak jak napisałeś, choć wystarczy, że sprawdzisz ile sztuk sprzedałeś dotychczas i dodasz do tego ile sztuk chcesz, aby było od teraz dostępne.

**Comment by pablokol** [comment]
Dzięki.
