### ISSUE TITLE
Problem z synchronizacją aukcji Allegro poprzez program Subsync2

### ISSUE THREAD

**Issue by nauczsiegracpl** [allegro/allegro-api#4500]
W momencie próby synchronizacji produktów w serwisie Allegro przez program subsync2 pojawia się komunikat, wcześniejsze produkty które wprowadzałem działają bez zarzutu, natomiast nowe które powstały poprzez opcję "powiel" więc są identyczne - zmienione tylko opisy tytuł i zdjęcia już się nie synchronizują. 

Z komunikatu wynika że mamy niepodpięte warunki zwrotów, tylko że mamy podpięte warunki zwrotów i aukcje bez błędu synchronizacji wyglądają identycznie jak aukcje z błędem. 
![144444](https://user-images.githubusercontent.com/84269046/118392964-ac4db980-b63c-11eb-9175-2a9ec378b18b.png)

Proszę o sugestię, pomoc? nie wiem co robić.

14.05.2021 12:21:47 [244]    Information    100562: Błąd: Serwer zdalny zwrócił błąd: (422) Unprocessable Entity.: {"errors":[{"code":"ReturnPolicyNotFoundException","message":"Unprocessable Entity","details":null,"path":"afterSalesServices.returnPolicy","userMessage":"Użytkownik nie posiada warunków zwrotu o nazwie: default."}]}

**Comment by kfijalko** [comment]
Przeczytaj:
https://developer.allegro.pl/product_offers/
Jeżeli nie podasz warunków ass (after sale services) to system bierze:
1) jeżeli masz tylko jedne warunki zwrotu na koncie, to je bierze
2) jeżeli masz wiele to bierze te, które się nazywają "default"
Jeżeli to nie pomoże to musi się allegro wypowiedzieć.

**Comment by MartaNowaczyk** [comment]
Zgadzam się z tym co pisze kfijalko. 
Nie wiem jednak jak działa i co przekazujesz przez subsync2. Najpierw trzeba by się skontaktować z obsługą tego oprogramowania.  Po naszej stronie do weryfikacji potrzebuję konkretnego przykładu, a nie zrzutu. Jeśli podajesz warunki zwrotów, a my odpowiadamy podanym błędem, możesz podesłać pełen request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Dopisz proszę, że dane dotyczą wątku GitHub #4500.

**Comment by nauczsiegracpl** [comment]
Znalazłem błąd - program próbował zasysać i integrować dane ze szkicami które miałem w allegro z tą samą sygnaturą. Szkice usunąłem, błędy się skończyły. Wątek do zamknięcia dziękuję za wszelką pomoc i sugestie!
