### ISSUE TITLE
Zakładanie nowej aplikacji

### ISSUE THREAD

**Issue by jzloty** [allegro/allegro-api#4501]
Cześć, 
mam problem z utworzeniem nowej aplikacji na stronie: https://apps.developer.allegro.pl/

Utworzyłem nowe konto na Allegro.pl (GraszkiPl) dokonałem pełnej aktywacji (otrzymałem maila z taką informacją), wystawiłem pierwszy przedmiot na sprzedaż, według serwisu dokonałem wszystkiego co można było dokonać, jednak w dalszym ciągu nie mogę utworzyć nowej aplikacji

![Devportal apps](https://user-images.githubusercontent.com/38064224/118459961-87b91680-b6fc-11eb-9768-ef52a97efd35.png)

Czyściłem cache, próbowałem na różnych przeglądarkach, jednak rezultat w każdym przypadku jest identyczny.

**Comment by MartaNowaczyk** [comment]
Podane konto, to konto firmowe, które nie zostało jeszcze zweryfikowane. Po pozytywnej weryfikacji powinieneś dodać nową aplikację.
