### ISSUE TITLE
Integracja Presta Shop z Allegro modułem 

### ISSUE THREAD

**Issue by Poofi-shop** [allegro/allegro-api#4502]
dzień dobry
pomoc allegro skierowała mnie tutaj

zamierzam zintegrować sklep internetowy działający na Presta Shop z Allegro.
Do tego potrzebne są takie dane jak:

WebApi Key
REST API CLient ID
REST API Client Secret
REST API Kay

chodzi o takie dane:
https://x13.pl/1237/integracja-allegro-z-prestashop.jpg

Gdzie to znajdę?

**Comment by AureliuszBrussy** [comment]
Danę dostępowe do REST API Allegro wygenerujesz z poziomu zakładki [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Po zarejestrowaniu aplikacji  otrzymasz Client ID oraz Client Secret. WebAPI Allegro zostało wygaszone, więc nie wygenerujesz do niego klucza dostępowego.

**Comment by kpodemski** [comment]
@Poofi-shop integracje allegro z x13 autoryzujesz bezpośrednio z modułu, nie musisz mieć tych kluczy
