### ISSUE TITLE
Tworzenie przesyłki - Receiver company name is too short

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#4503]
Próbuję utworzyć paczkę, wysyłając request:
PUT, https://api.allegro.pl/parcel-management/parcel-create-commands/{tu wygenerowany guid}

Payload: {"serviceId":9396908,"receiver":{"address":{"street":"Al.Grunwaldzka 1\/2","postCode":"01-234","city":"Nazwa Miasta","countryCode":"PL"},"email":"qwerty+asdfgh@allegromail.pl","name":"Jan Kowalski","company":"Dostawa do osoby prywatnej","phone":"1234567890"},"pickup":{"address":{"street":"Wiejska 3\/4","postCode":"67-890","city":"Nazwa miasta 2","countryCode":"PL"},"email":"sklep@mojadomena.pl","name":"Brajan Nowak","company":"Arasaka","phone":"123-456-789"},"items":[{"weight":{"value":0.3,"unit":"KILOGRAM"},"dimensions":{"height":{"value":10,"unit":"CENTIMETER"},"width":{"value":10,"unit":"CENTIMETER"},"depth":{"value":75,"unit":"CENTIMETER"}},"type":"PACKAGE","description":"123456-nH"}],"type":"PACKAGE"}

Headers: ["Authorization: Bearer {token}, "Accept: application\/vnd.allegro.public.v1+json","content-type: application\/vnd.allegro.public.v1+json","User-Agent: Mozilla\/5.0 (Windows NT 5.1; rv:38.0) Gecko\/20100101 Firefox\/38.0","Connection: keep-alive","Accept-Language: pl","Accept-Encoding: deflate"]

Sprawdzam status paczki za pomocą:
GET, https://api.allegro.pl/parcel-management/parcel-create-commands/{tu ten sam guid, co w poprzednim requescie},
headers: ["Authorization: Bearer {token}","Accept: application\/vnd.allegro.public.v1+json","content-type: application\/vnd.allegro.public.v1+json","User-Agent: Mozilla\/5.0 (Windows NT 5.1; rv:38.0) Gecko\/20100101 Firefox\/38.0","Connection: keep-alive","Accept-Language: pl","Accept-Encoding: deflate"]

W odpowiedzi dostaję:
{"id":"{tu ten sam guid, co w poprzednim requescie}","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Receiver company name is too short","details":null,"path":"receiver.company","userMessage":"Nazwa firmy odbiorcy jest za krĂłtka"}]}

Przesyłka adresowana jest do osoby prywatnej. W polu company próbowałem dać pustego stringa, "Dostawa do osoby prywatnej", lub całkiem wyrzucić to pole z requestu - za każdym razem ten sam błąd. Żeby było weselej, przed weekendem wszystko działało, w systemie nie robiliśmy żadnych zmian, na innym koncie Allegro wszystko śmiga bez problemu.

**Comment by AureliuszBrussy** [comment]
Czy możesz podać commandId tej komendy lub trace-id, które wysyłamy w odpowiedzi na któreś z tych żądań? Pozwoli mi to zweryfikować zgłaszany problem.

**Comment by rasskabak** [comment]
Na przykład 3cac8c7d-e62e-5898-6c8a-5d9a77596374

**Comment by AureliuszBrussy** [comment]
Dziękuję. Czy mógłbyś jeszcze wskazać trace-id odpowiedzi, gdzie zwróciliśmy błąd o który piszesz (o zbyt krótkiej nazwie receiver.company)?

**Comment by rasskabak** [comment]
trace-id ? Nie ma takiego pola w odpowiedzi ;)

**Comment by AureliuszBrussy** [comment]
Trace-id znajduje się w nagłówku naszej odpowiedzi. Udało mi się sprawdzić status przesyłki utworzonej w komendzie 3cac8c7d-e62e-5898-6c8a-5d9a77596374 - zakończyła się ona sukcesem. Czy jesteś w stanie wskazać przykład komendy, gdzie faktycznie zwróciliśmy błąd o treści, którą przytoczyłeś?

**Comment by rasskabak** [comment]
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: c284d5061a7a9d66
date: Mon, 17 May 2021 14:04:24 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 247

{"id":"0091ae16-90d0-bcde-3cdf-f4483329e6fa","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Receiver company name is too short","details":null,"path":"receiver.company","userMessage":"Nazwa firmy odbiorcy jest za krótka"}]}

**Comment by AureliuszBrussy** [comment]
W requeście w polu **receiver.company** przekazałeś wartość "-" - jest ona zbyt krótka, dlatego nie udało się utworzyć paczki. Wypełnienie tego pola nie jest obowiązkowe - możesz je pominąć w swoim requeście lub przekaż wartość null.

**Comment by rasskabak** [comment]
O, faktycznie :) To by tłumaczyło dlaczego problem występował tylko w jednym sklepie. Dziękuję za pomoc :)
