### ISSUE TITLE
Błędna wartość max w restrictions w parametrze kategorii

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4504]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Pobieram parametry kategorii 315879 oraz 308617 i widzę taki kwiatek:

```
{
         "id":"231625",
         "name":"Pojemność",
         "type":"float",
         "required":false,
         "requiredForProduct":false,
         "unit":"ml",
         "options":{
            "variantsAllowed":false,
            "variantsEqual":false,
            "ambiguousValueId":null,
            "dependsOnParameterId":null,
            "requiredDependsOnValueIds":null,
            "displayDependsOnValueIds":null,
            "describesProduct":true,
            "customValuesEnabled":false
         },
         "restrictions":{
            "min":0.0,
            "max":9.9999999E14,
            "range":false,
            "precision":2
         }
      }
```

Jak widać wartość max jest ustawiona na jakąś surrealną. Ponadto raz pola **min** oraz **max** w restrykcjach parametrów tych kategorii raz przyjmują typ float, a innym razem integer. Nie rozumiem, co się tutaj wyrabia ale nie idzie z deserializacją dojść do ładu przy takim czymś.

**Comment by AureliuszBrussy** [comment]
Zgłoszę to do odpowiedniego zespołu, możesz jednak jeszcze doprecyzować, w jakim przykładowym parametrze powinien znaleźć inny typ i dlaczego ma to większy sens?

**Comment by hahyes** [comment]
> w jakim przykładowym parametrze powinien znaleźć inny typ i dlaczego ma to większy sens?

Nie rozumiem niestety pytania. Typ danych w polu powinien być jednolity. `0.0` i `0` to jest to samo, ale zapisane za pomocą różnych typów danych. Ja napisałem sobie dawno temu model do deserializacji obiektu parametrów kategorii z JSONa i mam tam zgodnie z dokumentacją typ `int` (bo przykład pokazuje liczbę całkowitą). Jednak teraz widzę nie tylko `float` ale różne wykorzystanie. 

Dla ścisłości - mówię o typie pola w JSONie. Nie typie parametru w kategorii Allegro.

**Comment by AureliuszBrussy** [comment]
Typ przy restrykcjach min i max zależny jest od typu w samego parametru. Jeżeli w parametrze oczekujemy wartość zmiennoprzecinkową, to wartość w min i max również będzie zmiennoprzecinkowa i odwrotnie - jeżeli oczekujemy w parametrze liczby całkowitej, wartość min i max będzie liczbą całkowitą. 

Kwestię wartości max w parametrze 231625 zgłosiłem do odpowiedniego zespołu.

**Comment by AureliuszBrussy** [comment]
@hahyes poprawiliśmy już wartość maksymalną tego parametru.

**Comment by hahyes** [comment]
> Typ przy restrykcjach min i max zależny jest od typu samego parametru. Jeżeli w parametrze oczekujemy wartość zmiennoprzecinkową, to wartość w min i max również będzie zmiennoprzecinkowa i odwrotnie - jeżeli oczekujemy w parametrze liczby całkowitej, wartość min i max będzie liczbą całkowitą.
> 
> Kwestię wartości max w parametrze 231625 zgłosiłem do odpowiedniego zespołu.

Rozumiem, jednak zgaduję, że w takim wypadku nadal miałbym problem z wartością maksymalną. Dziękuję za informację.

**Comment by hahyes** [comment]
> @hahyes poprawiliśmy już wartość maksymalną tego parametru.

Dziękuję i zamykam wątek. :)
