### ISSUE TITLE
Stock sold/available

### ISSUE THREAD

**Issue by gufio** [allegro/allegro-api#4505]
Dzień dobry, mam parę pytań odnośnie zasobu GET sale/offers i stwierdzenia: "Przez API zwracamy tylko informację na temat sprzedaży z ostatnich 30 dni. Znajdziesz ją w polu stock.sold".

1. Stock.available bez zmiany po zakończeniu niesprzedanej oferty. Czy ta wartość zmienia się tylko przy sprzedaży i czy wartość po 30 dniach się nie zresetuje?
2. Stock.sold na przestrzeni ostatnich 60 dni. Czy oferta zakończona i sprzedana 50 dni temu zwróci stock.sold > 0?
3. Czy stock.sold zredukuje się w przypadku wycofania się licytującego lub w przypadku zwrotu produktu? Jak ewentualnie uzyskać informację o rzeczywistej sprzedaży (najlepiej jakaś bulk operacja dla wielu ofert)? Potrzebuję sprawdzić np. kilka tysięcy ofert z 60 dni (w tym ponowne publikacje), czy ktoś nie kupił lub aktualnie nie licytuje, aby móc wycofać oferty.

**Comment by AureliuszBrussy** [comment]
1. Wartość w **stock.available** pozostanie bez zmian i nie zresetuje się po 30 dniach.
2. W takim przypadku zwrócimy wartość 0 w polu **stock.sold**. 
3. Nie, wartość w **stock.sold** nie zmniejszy się po odstąpieniu przez Kupującego od umowy. Nie udostępniamy zasobu, który pozwoliłby na sprawdzenie liczby sprzedanych sztuk z okresu 60 dni. W [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)  możesz ewentualnie skorzystać z sortowania  po liczbie sprzedanych przedmiotów w ciągu ostatnich 30 dni - więcej o tym w [naszym poradniku](https://developer.allegro.pl/my_offers/#sortowanie).

**Comment by gufio** [comment]
@AureliuszBrussy Chciałbym jeszcze doprecyzować odnośnie stock.availability. Czy wartość ta zmieni się po odstąpieniu przez Kupującego od umowy, jeśli tak to w jakim czasie następuje zmiana?

**Comment by AureliuszBrussy** [comment]
Wartość w polu  **stock.availability** również nie zmieni się w wyniku odstąpienia kupującego od umowy.

**Comment by maniootek** [comment]
Czy da się przez API sprawdzić ile sprzedano sztuk w ofercie od samego początku? Chciałbym dostosować maksymalną liczbę dostępnych sztuk w ofercie ale nie wiem jak to wyliczyć.

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy możliwości sprawdzenia liczby sprzedanych sztuk od początku oferty. Zwracamy taką informację dla ostatnich 30 dni w polu **stock.sold**.
