### ISSUE TITLE
VALIDATION_ERROR i puste pliki XML z błędem

### ISSUE THREAD

**Issue by ChybykByk** [allegro/allegro-api#4507]
Występuje problem w integracji IdoSell (platforma IAI) z :
"Kod odpowiedzi zwrócony przez API Allegro: 
VALIDATION_ERROR
"

Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
Nieprawidłowy podzbiór HTML

Postępowanie:
Jeżeli to możliwe popraw błędne dane, w przeciwnym wypadku kliknij tutaj by skontaktować się z obsługą Allegro w celu wyjaśnienia przyczyny występowania błędu. Poniżej znajdują się załączniki, o które możesz zostać poproszony.
Możesz w ciągu kilku dni przejrzeć ponownie ten błąd otwierając Dziennik zdarzeń

Załączniki:
Żądanie: request_allegro_20210518_130726
Odpowiedź: response_allegro_20210518_130726
Załączniki będą przechowywane do: 2021-05-25

Niestety pliki XML response są puste - nie zawierają żadnej treści.

Sprawdziłem opis aukcji - zawiera wyłącznie znaczniki `<p></p>.`

```
<p>Banana! Jeśli jesteś fanem słynnych Minionków, ten kubek jest stworzony dla Ciebie!</p>
<p>- Kubek z wysokiej jakości ceramiki. Rozmiar standardowy (320 ml).</p>
<p>- Opakowanie: czarne pudełko z okienkiem.</p>
<p>- Można myć w zmywarce i używać mikrofal.</p>

```
Próbowałem też zmienić opis na inne znaczniki `(<li>)`

i to też nie pomogło. 
```
<p>Tą charakterystyczną postać znamy z takich bajek jak "Jak ukraść księżyc?" czy "Minionki". Uwielbiana przez dzieci i dorosłych, słodka, mała kulka to nikt inny jak żółty Minionek. W bajce tej nie tylko płatają figle, ale równie często ukazują co jest dobre, a co złe. Skarbonka Bob nauczy Twoje dziecko oszczędzania i ozdobi jego pokój w iście bajkowym stylu!</p>

<p><b>Szczegóły:</b></p>
<ul>
<li> Materiał: vinyl PVC </li>
<li>Wysokość 15cm </li>
<li>Otwór z góry do wrzucana pieniędzy, posiada otwarcie na dole</li>
</ul>
```

Co w tej sytuacji zrobić? Nie rozumiem gdzie może leżeć problem, a support Allegro pokierował mnie tutaj, aby problem rozwiązać. Będę wdzięczny za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że po naszej stronie zwracamy błąd w opisie, który uniemożliwia wystawienie oferty. Błąd występuje w drugiej sekcji tekstowej, jednak nie widzimy, jakie treści konkretnie wysyłasz, przez co nie możemy wskazać żródła tego problemu. Skontaktuj się proszę ze wsparciem IdoSell, aby udostępnili dane z załącznika "Żądanie: request_allegro_20210518_130726" oraz sprawdzili, czy do tej sekcji nie są dołączane nadmiarowe znaki (opis w naszych logach wskazuje na to, że są).
