### ISSUE TITLE
Dane dotyczące liczby wymaganych produktów w danej kategorii

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#4508]
Czy jest dostępny jakiś zasób w API, który zwróciłby ile ofert musi mieć powiązany produkt w kategorii?

**Comment by Lukasz-Zurek** [comment]
Nie mamy takiego zasobu. Możesz jednak sprawdzić które oferty nie są powiązane z produktem. W tym celu skorzystaj z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i parametru **product.id.empty=true**. Dodatkowo możesz skorzystać również z innych filtrów. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#filtry).
