### ISSUE TITLE
Aktualizacja ofert zakończonych i szkiców

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4509]
Czy aby szkic został nie usunięty po 60 dniach ani zakończona oferta archiwizowana wystarczy je aktualizować?

Czy aktualizacja przez REST API która zakończy się błędem, np. brak czasu wysyłki również jest uznawana za edycje oferty i przedłuży czas usunięcia/archiwizowania?

**Comment by FromAnyHole** [comment]
@marmited - już nie 60 dni, skrócili po cichu...

**Comment by Lukasz-Zurek** [comment]
@marmited 

> Czy aby szkic został nie usunięty po 60 dniach ani zakończona oferta archiwizowana wystarczy je aktualizować? 

Jeśli chodzi o szkic - każda aktualizacja przedłuży czas wyświetlania w "Moich ofertach". Inaczej jest w przypadku zakończonych ofert. Są one przenoszone do archiwum po upływie minimum 60 dni od momentu ich zakończenia. Jakakolwiek edycja nic tutaj nie zmieni.

> Czy aktualizacja przez REST API która zakończy się błędem, np. brak czasu wysyłki również jest uznawana za edycje oferty i przedłuży czas usunięcia/archiwizowania?

Tak.

**Comment by marmited** [comment]
@Lukasz-Zurek  Dzięki za odpowiedź.

@FromAnyHole co masz przez to na myśli?

**Comment by FromAnyHole** [comment]
@marmited - skrócony jest czas dla Szkiców, proponuję to sprawdzić, bo nic oficjalnie nie podano.

**Comment by Lukasz-Zurek** [comment]
@FromAnyHole Nie wprowadzaliśmy zmian w tym zakresie. Jeśli dysponujesz świeżymi przykładami, prześlij nam proszę numery szkiców w obecnym wątku. Zweryfikujemy to.

**Comment by FromAnyHole** [comment]
@Lukasz-Zurek - to proszę podać oficjalnie przez jaki czas (oraz do jakiego limitu ilościowego) są obecnie przechowywane Szkice w ramach jednego (standardowego - bo są też uprzywilejowani) konta "firmowego"? Wtedy się wypowiem co ja czasem widzę...

**Comment by Lukasz-Zurek** [comment]
@FromAnyHole Tak.

**Comment by FromAnyHole** [comment]
@Lukasz-Zurek - Nie, nie zawsze ;-)
