### ISSUE TITLE
Błędy podczas kupowania na sandboxie

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#451]
Podczas próby kupienia oraz zapłacenia za produkt na sandboxie cały czas wyskakują błędy 401.
Przykładowo po kliknięciu na "kupuję i płacę" pojawia się błąd 401, po czym strona się odświeża i ponownie pojawia się błąd 401. Po kilku takich przekierowaniach pojawia się już prawidłowa kolejna strona lub wracam na stronę "kupuję i płacę".
Przejść do okna płatności udał mi się chyba za dziesiątym razem.
Kilka razy błędy pojawiły się również po kliknięciu "kup teraz" na karcie produktu.

![zrzut ekranu z 2018-07-30 12-35-53](https://user-images.githubusercontent.com/36850550/43392905-6e688ee0-93f5-11e8-87d2-c28277ea2ebb.png)
![zrzut ekranu z 2018-07-30 12-36-50](https://user-images.githubusercontent.com/36850550/43392906-6e8d0414-93f5-11e8-80ea-b7c071877db7.png)

**Comment by PawelTaberski** [comment]
Podaj proszę id oferty jaką próbujesz kupić i Twój login. Sprawdzimy w czym jest problem.

**Comment by mzawodzinski** [comment]
Aukcja: 6205429491
Login kupującego: aaa

**Comment by PawelTaberski** [comment]
Problem zgłosiłem do odpowiedniego zespołu, proszę o cierpliwość.

**Comment by PawelTaberski** [comment]
Problem nie powinien już występować. Jakbyś miał jeszcze takie przypadki daj znać.

**Comment by hmalewska** [comment]
Błąd konfiguracyjny został już naprawiony.. Zamykam issue.
