### ISSUE TITLE
Rejestracja aplikacji

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#4510]
Jaki jest sens wymagania podwójnego logowania przy rejestracji aplikacji?
Informatyk nie może się zalogować, bo numer telefonu przypisany do konta jest użytkownika konta, który nie zjamuje się api.

**Comment by Lukasz-Zurek** [comment]
Dwustopniowe logowanie wprowadziliśmy ze względów bezpieczeństwa.

W tej sytuacji skorzystaj proszę z opcji "Dodaj do zaufanych" w ["Moim Allegro"](https://allegro.pl/moje-allegro/moje-konto/dwustopniowe-logowanie).
