### ISSUE TITLE
/sale/product-offers i set the property and custom value but i had that error. 

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4511]
/sale/product-offers
i set the property and custom value but i had that error. 
"Unable to create product without proper values in all required parameters: [Materiał dominujący]"
{trace-id=e6e6ed4910fff4b3}

**Comment by Lukasz-Zurek** [comment]
We will verify it as soon as possible. I will come back with an answer.

**Comment by Lukasz-Zurek** [comment]
@ymyuceturk You have provided incorrect value: "Brak" right here:

`         {
            "id": "201017",
            "values": [
               "Brak"
            ],
            "valuesIds": [
               "201017_257870"
            ]
         },`

Our system will not accept this phrase. You should change value for a proper one.

**Comment by ymyuceturk** [comment]
Thank you for your help
