### ISSUE TITLE
Problem z rozłączeniem oferty z powodu nie podania id w obiekcie product /sale/offers

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#4512]
Witam.
Dostałem od klienta info, który kontaktował się z Allegro, że rozłączanie produktu w ofercie jest spowodowane nie podaniem `id` w obiekcie `product` and endpoincie `https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT`

> Aplikacja ta, np. dzisiaj o 2021-05-18 07:30:12.741 wykonała request (metodą PUT na /sale/offers/{ID}) i przekazała wartość null w polu product, w wyniku czego produkt został rozłączony. Nie mam możliwości przekazania dokładnych logów. 

Nasza aplikacja już długo pracuje i nigdy z tym obiektem nie było problemu. Powiązania jakie dla nas są ważne widnieją w obiekcie `external.id`. 

Czym jest obiekt `product` i czego to jest `id`?

**Comment by Lukasz-Zurek** [comment]
Generalnie `product.id` to identyfikator produktu z bazy naszego Serwisu. Jeśli w requeście: [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) przekażesz wartość **“null”** w polu `product.id` - usuniemy produkt z oferty. Podobnie jest w sytuacji, gdy dla obiektu `product` nie przekażesz pola `id`. Jest to zgodne z założeniem. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/productization/#jak-zaktualizowa%c4%87-informacje-o-produkcie-w-ofercie).

**Comment by Lukasz-Zurek** [comment]
Nie jest to nowość. Pole `product.id` wdrożyliśmy wraz z produktyzacją w Allegro, w marcu 2019 r.

**Comment by troncomputers** [comment]
Ok, czyli problem po naszej stronie. Dzięki za info ✌
