### ISSUE TITLE
Powracający OFFER_ACTIVATED mimo zamykania aukcji wcześniej

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4513]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Na jednym sklepie klienta mamy problem z samo aktywującą się aukcją, co kilkanaście minut dostajemy:

```
[:SYNC][2021-05-19 11:14:45]            OFFER-EVENT-DISPATCH             7900224668     MTYyMTQxNTU4MDc1NDE1MQ; OFFER_ACTIVATED; occurredAt: 2021-05-19T09:12:49.000Z
```

z naszej strony idzie request aby ją zamknać:

```
[:SYNC][2021-05-19 11:18:25]            SYNC-PUBLICATION-COMMAND         7900224668     [AccountID: 1] {"type":"PUBLICATION","method":"SYNC","value":"END","message":"","scheduledAt":"2021-05-19T09:16:17.901Z","code":"DEFAULT"}
```

przez kilkanaście minut jest w porządku i potem bez żadnej z naszych reakcji znów dostajemy informacje o tym, że aukcja została aktywowana

jakie informacje moglibyśmy Wam dostarczyć abyście pomogli nam w zdiagnozowaniu takiego zachowania? :) Czy jest taka możliwość wg numeru aukcji? `7900224668`?

**Comment by PrzemyslawLukanowski** [comment]
Czy na pewno chodzi o środowisko testowe? Udało mi się znaleźć tę ofertę na produkcji - żądania ponownej aktywacji oferty pochodzą z innej aplikacji (clientID - ...eba1f) niż ta, która kończy ofertę. Przykładowe commandID to: `b782cad1-f5ac-4689-bef4-7d677b326675` i `557087be-d218-4469-a107-6c9eda6c5024`. Najlepiej będzie, jeśli użytkownik sprawdzi przez zakładkę [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje), co to dokładnie za oprogramowanie i skontaktuję się z jej twórcami.

**Comment by kpodemski** [comment]
Oh, oczywiście chodzi o produkcję! Dzięki za namierzenie, tak podejrzewaliśmy, że "coś" musi nam przeszkadzać. Na razie nie zamykam, ale jak potwierdzę z klientem, że ma zamieszanie z powiązanymi aplikacjami to zamknę 👍

**Comment by kpodemski** [comment]
Dzięki @PrzemyslawLukanowski - to było to 💪
