### ISSUE TITLE
Produkturyzacja - wyszukiwanie istniejących produktów, a dodawanie nowych

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#4515]
Wykonuje request do API, dokładnie taki, wklejam:

**https://api.allegro.pl/sale/products?phrase=+SUKIENKA+MINI+G%C5%81ADKA+ROZM+32&category.id=124264&3786=413461&3806=272386**

Parametry:
phrase =  SUKIENKA MINI GŁADKA ROZM 32
category.id = 124264 (Moda / Odzież, Obuwie, Dodatki / Odzież damska / Sukienki)
3786 = 413461 (Marka: Invicta)
3806 = 272386 (Rozmiar: 32)

Api zwraca response:
(...)

(
--
&nbsp;[products] =&gt; Array
&nbsp;(
&nbsp;)
&nbsp;&nbsp;
&nbsp;[categories] =&gt; stdClass Object
&nbsp;(
&nbsp;[subcategories] =&gt; Array
&nbsp;(
&nbsp;[0] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 124264
&nbsp;[name] =&gt; Sukienki
&nbsp;[count] =&gt; 0
&nbsp;)
&nbsp;&nbsp;
&nbsp;)
&nbsp;&nbsp;
&nbsp;[path] =&gt; Array
&nbsp;(
&nbsp;[0] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 954b95b6-43cf-4104-8354-dea4d9b10ddf
&nbsp;[name] =&gt; Allegro
&nbsp;)
&nbsp;&nbsp;
&nbsp;[1] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; ea5b98dd-4b6f-4bd0-8c80-22c2629132d0
&nbsp;[name] =&gt; Moda
&nbsp;)
&nbsp;&nbsp;
&nbsp;[2] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 1454
&nbsp;[name] =&gt; Odzież, Obuwie, Dodatki
&nbsp;)
&nbsp;&nbsp;
&nbsp;[3] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 76033
&nbsp;[name] =&gt; Odzież damska
&nbsp;)
&nbsp;&nbsp;
&nbsp;[4] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 124264
&nbsp;[name] =&gt; Sukienki
&nbsp;)
&nbsp;&nbsp;
&nbsp;)
&nbsp;&nbsp;
&nbsp;)
&nbsp;&nbsp;
&nbsp;[filters] =&gt; Array
&nbsp;(
&nbsp;[0] =&gt; stdClass Object
&nbsp;(
&nbsp;[id] =&gt; 3786
&nbsp;[name] =&gt; Marka
&nbsp;[type] =&gt; SINGLE
&nbsp;[values] =&gt; Array
&nbsp;(
&nbsp;[0] =&gt; stdClass Object
&nbsp;(
&nbsp;[name] =&gt; &amp; Other Stories
&nbsp;[value] =&gt; 319653
&nbsp;[idSuffix] =&gt;
&nbsp;[count] =&gt; 0
&nbsp;[selected] =&gt;
&nbsp;)
&nbsp;&nbsp;
&nbsp;[1] =&gt; stdClass Object
&nbsp;(
&nbsp;[name] =&gt; 10DAYS
&nbsp;[value] =&gt; 518397
&nbsp;[idSuffix] =&gt;
&nbsp;[count] =&gt; 0
&nbsp;[selected] =&gt;
&nbsp;)
&nbsp;&nbsp;
&nbsp;[2] =&gt; stdClass Object
&nbsp;(
&nbsp;[name] =&gt; 20inLove
&nbsp;[value] =&gt; 587729
&nbsp;[idSuffix] =&gt;
&nbsp;[count] =&gt; 0
&nbsp;[selected] =&gt;
&nbsp;)
&nbsp;&nbsp;
&nbsp;[3] =&gt; stdClass Object
&nbsp;(
&nbsp;[name] =&gt; 2skin
&nbsp;[value] =&gt; 846193
&nbsp;[idSuffix] =&gt;
&nbsp;[count] =&gt; 0
&nbsp;[selected] =&gt;
&nbsp;)

(...)

**We właściwości "products" response mamy: 0 - żadnych produktów.**
Zatem wniosek taki, że produkt powinien zostać dodany jako nowy.

I tak też się dzieje, lecz podczas próby dodania nowego produktu, API zwraca informację, że produkt już jest:

(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ProductDuplicate
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji.
                )

        )
)

I bądź tu mądry, niby produkt jest, lecz podczas wyszukiwania, nie jest w ogóle zwracany. Dlaczego?
Czy zapytanie wyszukujące istniejące już produkty jest OK ? Parametry w nim przekazywane są jako:

**&3786=413461&3806=272386**

Jest tutaj coś nie tak?
Z góry dziękuję za pomoc!

**Comment by PrzemyslawLukanowski** [comment]
Parametry przekazujesz prawidłowo, produktu nie zwrócimy przez GET /sale/products, jeśli nie jest kompletny, tzn. nie posiada uzupełnionych wszystkich parametrów. 
W przypadku komunikatu, który otrzymałeś - 409- pamiętaj, że możesz skorzystać z nagłówka odpowiedzi `Location`. Znajdziesz tam identyfikator oryginalnego produktu.

**Comment by Lukasz-Zurek** [comment]
W imieniu Przemka odpowiem na zadane pytania.

> Mam kilka pytań. Napisał Pan o uzupełnieniu wszystkich parametrów, dla podanej przykładowej kategorii przy poszukiwaniu produktu. Są one następujące: Marka, Rozmiar, Kolor, Wzór dominujący, Okazja, Fason, Styl, Dekolt, Rękaw, Długość, Zapięcie, Materiał dominujący, Cechy dodatkowe.

Dla przykładowej kategorii wskazane wymagane parametry się zgadzają.

> Gdybym chciał wyszukać produktu tylko, podanej marki, wybranym kolorze i rozmiarze z podanej kategorii (bez zwracania uwagi na pozostałe filtry) - to nie da się tego zrobić?
Albo np. zobaczyć tylko produktu o kolorze białym danego producenta, z podanej kategorii? hmm...

Jest to możliwe, musisz jednak pamiętać o tym, że w odpowiedzi zwrócimy produkty, które zawierają wszystkie wartości wskazane dla podanych filtrów. Więcej informacji na temat wyszukiwania produktów znajdziesz w [naszym poradniku](https://developer.allegro.pl/productization/#jak-znale%c5%ba%c4%87-produkt).

> Rozumiem, że przy zwrocie komunikatu o podanej treści: "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji." - należy sprawdzić nagłówek "Location:" - czy w podanym nagłówku znajdę identyfikator produktu?

Tak.

**Comment by Kuba-Id** [comment]
Już ostatnia kwestia. Mam jeszcze mały drobny problem.

Wykonanie zapytanie GET z nagłówka: "Location", który pobrałem z Response:





[expires] =&gt; 0
--
| [cache-control] =&gt; no-cache, no-store, max-age=0, must-revalidate
| [x-xss-protection] =&gt; 1; mode=block
| [pragma] =&gt; no-cache
| [location] =&gt; https://api.allegro.pl/sale/products/29cecefd-3de8-4c32-8cfa-32584ece8879
| [x-frame-options] =&gt; DENY
| [trace-id] =&gt; 61a7ba339d4e90b3
| [referrer-policy] =&gt; no-referrer
| [date] =&gt; Tue, 25 May 2021 07:50:25 GMT
| [x-content-type-options] =&gt; nosniff
| [content-type] =&gt; application/vnd.allegro.public.v1+json;charset=UTF-8
| [content-length] =&gt; 193





To zapytanie:



&lt;hr&gt;CURL_INFO:&lt;BR&gt;Array
--
| (
| [url] =&gt; https://api.allegro.pl/sale/products/29cecefd-3de8-4c32-8cfa-32584ece8879
| [content_type] =&gt;
| [http_code] =&gt; 0
| [header_size] =&gt; 0
| [request_size] =&gt; 0
| [filetime] =&gt; -1
| [ssl_verify_result] =&gt; 0
| [redirect_count] =&gt; 0
| [total_time] =&gt; 0
| [namelookup_time] =&gt; 0
| [connect_time] =&gt; 0
| [pretransfer_time] =&gt; 0
| [size_upload] =&gt; 0
| [size_download] =&gt; 0
| [speed_download] =&gt; 0
| [speed_upload] =&gt; 0
| [download_content_length] =&gt; -1
| [upload_content_length] =&gt; -1
| [starttransfer_time] =&gt; 0
| [redirect_time] =&gt; 0
| [redirect_url] =&gt;
| [primary_ip] =&gt;
| [certinfo] =&gt; Array
| (
| )
| &nbsp;
| [primary_port] =&gt; 0
| [local_ip] =&gt;
| [local_port] =&gt; 0
| )




Otrzymuje pusty RESPONSE, to możliwe, hmm... czy coś robię nie tak?

Będę wdzięczny za pomoc!

**Comment by PrzemyslawLukanowski** [comment]
Niestety, ale nie udało mi się powtózyć Twojego błędu, request zwraca prawidłowe dane produktu:

```
{
    "id": "29cecefd-3de8-4c32-8cfa-32584ece8879",
    "name": "Bluzka Missguided r. 40",
    "category": {
        "id": "76034",
        "similar": [
            {
                "id": "260336"
            },
            {
                "id": "258922"
            },
            {
                "id": "89508"
            },
            {
                "id": "89529"
            },
            {
                "id": "76103"
            },
            {
                "id": "76010"
            }
        ]
    },
    "parameters": [
        {
            "id": "3786",
            "name": "Marka",
            "valuesLabels": [
                "Missguided"
            ],
            "valuesIds": [
                "3786_270490"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "3806",
            "name": "Rozmiar",
            "valuesLabels": [
                "40"
            ],
            "valuesIds": [
                "3806_5"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "451",
            "name": "Kolor",
            "valuesLabels": [
                "biały"
            ],
            "valuesIds": [
                "451_1"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "3766",
            "name": "Wzór dominujący",
            "valuesLabels": [
                "bez wzoru"
            ],
            "valuesIds": [
                "3766_1"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "201021",
            "name": "Fason",
            "valuesLabels": [
                "inny"
            ],
            "valuesIds": [
                "201021_256894"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "59",
            "name": "Dekolt",
            "valuesLabels": [
                "lejący"
            ],
            "valuesIds": [
                "59_11"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "18293",
            "name": "Rękaw",
            "valuesLabels": [
                "długi rękaw"
            ],
            "valuesIds": [
                "18293_1"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "201017",
            "name": "Materiał dominujący",
            "valuesLabels": [
                "poliester"
            ],
            "valuesIds": [
                "201017_2377"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "127708",
            "name": "Cechy dodatkowe",
            "valuesLabels": [
                "falbana"
            ],
            "valuesIds": [
                "127708_9"
            ],
            "values": null,
            "unit": null,
            "options": {
                "identifiesProduct": false
            }
        }
    ],
    "images": [
        {
            "url": "https://a.allegroimg.com/original/1111d5/1b07e7844a8b82dad0b59d29e89a"
        },
        {
            "url": "https://a.allegroimg.com/original/110c61/1c3b5d8b4ae5ac5172b007b54dc4"
        },
        {
            "url": "https://a.allegroimg.com/original/11990d/8399eb7d4875b78856fc04606df2"
        },
        {
            "url": "https://a.allegroimg.com/original/119b28/c276d0e7419c9720a8b5eeb7768c"
        },
        {
            "url": "https://a.allegroimg.com/original/1157af/a710df23416f8a0f8e0b12510010"
        }
    ],
    "offerRequirements": {
        "parameters": []
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "description": null
}
```

Upewnij się, że Twój request jest zgodny z [dokumentacją](https://developer.allegro.pl/documentation/#operation/getSaleProduct).
