### ISSUE TITLE
/order/carriers/ALLEGRO/points usunięte punkty

### ISSUE THREAD

**Issue by krzysztofzylka** [allegro/allegro-api#4516]
Czy są dane które informują gdy punkt zostanie usunięty?
W /order/carriers/ALLEGRO/points takich informacji nie znalazłem

**Comment by PrzemyslawLukanowski** [comment]
Nie zwracamy takiej informacji wprost, możesz skorzystać z nagłówka `If-Modified-Since` - jeśli zwrócimy kod 304 Not modified, oznacza to, że nie wprowadziliśmy żadnych zmian od daty wskazanej w nagłówki; jeśli 200 - zaktualizowaliśmy listę od tego czasu, mogliśmy dodać lub usunąć wybrane punkty.
