### ISSUE TITLE
sale/offers zwraca oferty z innego konta

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#4517]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Klient ma 2 o seller.id 80830642 i 97713667
Dlaczego przy zapytaniu o oferty od 97713667 response zwraca oferty z konta 80830642.
Wynik jest ten sam, gdy konta są połączone, jak i rozłączone.

**Comment by Lukasz-Zurek** [comment]
Widzę, że obecnie konta są rozłączone i dla 97713667 response nie zwraca ofert z konta 80830642. 

Jeśli sytuacja się powtórzy, prześlij proszę przykładowy request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4517.

**Comment by drzemik** [comment]
Obecnie konta są połączone. Zapytanie o oferty z obu kont dają te same wyniki, co powoduje, że nie wadomo, jaka oferta jest z jakiego konta.
Większy problem jest z zamówieniami.
Zapytanie o zamówienia z obu kont zwraca te same wyniki, ale tylko z konta 80830642.
Przykład:
urle z obu kont dla zamówienia na koncie 97713667
https://api.allegro.pl/order/checkout-forms/fb808021-bf9f-11eb-aa8e-4393a6da1c19?seller.id=80830642
https://api.allegro.pl/order/checkout-forms/fb808021-bf9f-11eb-aa8e-4393a6da1c19?seller.id=97713667
zwracają:
object(stdClass)#71 (1) {
  ["errors"]=>array(1) {
    [0]=>object(stdClass)#24 (5) {
      ["code"]=>string(29) "CheckoutFormNotFoundException"
      ["message"]=>string(66) "checkout form of id fb808021-bf9f-11eb-aa8e-4393a6da1c19 not found"
      ["details"]=>NULL
      ["path"]=>string(58) "/order/checkout-forms/fb808021-bf9f-11eb-aa8e-4393a6da1c19"
      ["userMessage"]=>NULL
    }
  }
}
urle z obu kont dla zamówienia na koncie 80830642
https://api.allegro.pl/order/checkout-forms/6d717471-c192-11eb-bee1-7d7ffc2980d1?seller.id=80830642
https://api.allegro.pl/order/checkout-forms/6d717471-c192-11eb-bee1-7d7ffc2980d1?seller.id=97713667
zwracają:
object(stdClass)#74 (14) {
  ["id"]=>string(36) "6d717471-c192-11eb-bee1-7d7ffc2980d1"
  ["messageToSeller"]=>NULL
  ["buyer"]=>object(stdClass)#72 (10) {
    ["id"]=>string(7) "2058986"
    ["email"]=>string(35) "iavva8m4w4+4b2d2f8e2@allegromail.pl"
    ["login"]=>string(10) "czeremszak"
    ["firstName"]=>string(7) "Andrzej"
    ["lastName"]=>string(8) "Jakimiuk"
    ["companyName"]=>NULL
    ["guest"]=>bool(false)
    ["personalIdentity"]=>NULL
    ["phoneNumber"]=>string(15) "+48 608 416 288"
    ["address"]=>object(stdClass)#73 (4) {
      ["street"]=>string(22) "Antoniukowska 56A m.21"
      ["city"]=>string(10) "Białystok"
      ["postCode"]=>string(6) "15-845"
      ["countryCode"]=>string(2) "PL"
    }
  }
  ["payment"]=>object(stdClass)#65 (6) {
    ["id"]=>string(36) "6dedd061-c192-11eb-b0e3-a5426d88473a"
    ["type"]=>string(6) "ONLINE"
    ["provider"]=>string(4) "PAYU"
    ["finishedAt"]=>string(24) "2021-05-30T22:00:51.321Z"
    ["paidAmount"]=>object(stdClass)#68 (2) {
      ["amount"]=>string(6) "220.00"
      ["currency"]=>string(3) "PLN"
    }
    ["reconciliation"]=>NULL
  }
  ["status"]=>string(20) "READY_FOR_PROCESSING"
  ["fulfillment"]=>object(stdClass)#69 (2) {
    ["status"]=>string(10) "PROCESSING"
    ["shipmentSummary"]=>object(stdClass)#67 (1) {
      ["lineItemsSent"]=>string(4) "NONE"
    }
  }
  ["delivery"]=>object(stdClass)#63 (7) {
    ["address"]=>object(stdClass)#66 (9) {
      ["firstName"]=>string(7) "Andrzej"
      ["lastName"]=>string(8) "Jakimiuk"
      ["street"]=>string(13) "diamentowa 14"
      ["city"]=>string(10) "Białystok"
      ["zipCode"]=>string(6) "15-161"
      ["countryCode"]=>string(2) "PL"
      ["companyName"]=>NULL
      ["phoneNumber"]=>string(15) "+48 608 416 288"
      ["modifiedAt"]=>NULL
    }
    ["method"]=>object(stdClass)#58 (2) {
      ["id"]=>string(36) "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93"
      ["name"]=>string(25) "Allegro Paczkomaty InPost"
    }
    ["pickupPoint"]=>object(stdClass)#61 (5) {
      ["id"]=>string(6) "BIA05M"
      ["name"]=>string(16) "Paczkomat BIA05M"
      ["description"]=>string(24) "Parking sklepu Stokrotka"
      ["address"]=>object(stdClass)#62 (3) {
        ["street"]=>string(11) "Raginisa 74"
        ["zipCode"]=>string(6) "15-161"
        ["city"]=>string(10) "Białystok"
      }
      ["modifiedAt"]=>NULL
    }
    ["cost"]=>object(stdClass)#59 (2) {
      ["amount"]=>string(4) "0.00"
      ["currency"]=>string(3) "PLN"
    }
    ["smart"]=>bool(true)
    ["time"]=>object(stdClass)#60 (1) {
      ["guaranteed"]=>NULL
    }
    ["calculatedNumberOfPackages"]=>int(1)
  }
  ["invoice"]=>object(stdClass)#64 (3) {
    ["required"]=>bool(false)
    ["address"]=>NULL
    ["dueDate"]=>NULL
  }
  ["lineItems"]=>array(1) {
    [0]=>object(stdClass)#55 (8) {
      ["id"]=>string(36) "6d714d60-c192-11eb-a1d5-7d7ffc2980d1"
      ["offer"]=>object(stdClass)#54 (3) {
        ["id"]=>string(11) "10243243335"
        ["name"]=>string(52) "SMART365 SZLIFIERKA STOŁOWA KAMIENIOWA TAŚMOWA 2w1"
        ["external"]=>object(stdClass)#56 (1) {
          ["id"]=>string(14) "SM-04-04150/50"
        }
      }
      ["quantity"]=>int(1)
      ["originalPrice"]=>object(stdClass)#57 (2) {
        ["amount"]=>string(6) "220.00"
        ["currency"]=>string(3) "PLN"
      }
      ["price"]=>object(stdClass)#53 (2) {
        ["amount"]=>string(6) "220.00"
        ["currency"]=>string(3) "PLN"
      }
      ["reconciliation"]=>NULL
      ["selectedAdditionalServices"]=>array(0) {
      }
      ["boughtAt"]=>string(24) "2021-05-30T22:00:46.026Z"
    }
  }
  ["surcharges"]=>array(0) {
  }
  ["discounts"]=>array(0) {
  }
  ["summary"]=>object(stdClass)#52 (1) {
    ["totalToPay"]=>object(stdClass)#51 (2) {
      ["amount"]=>string(6) "220.00"
      ["currency"]=>string(3) "PLN"
    }
  }
  ["updatedAt"]=>string(24) "2021-05-30T22:00:51.321Z"
  ["revision"]=>string(8) "1ab823c2"
}

**Comment by Lukasz-Zurek** [comment]
@drzemik Przepraszam za długi czas oczekiwania na odpowiedź.

Filtrowanie po parametrze **"seller.id"** dostępne jest tylko dla: [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/listing/#1-jak-wyszukiwa%c4%87-i-przegl%c4%85da%c4%87-oferty).

Próbowałeś uzyskać informacje na temat zamówienia "fb808021-bf9f-11eb-aa8e-4393a6da1c19" (które należy do konta: 97713667) będąc autoryzowanym jako sprzedawca na koncie: 80830642, stąd zaistniała sytuacja.

Jednocześnie chciałbym w tym miejscu poinformować, że nasze API nie zwraca zamówień dla kont powiązanych.

**Comment by drzemik** [comment]
Zamówienie fb808021-bf9f-11eb-aa8e-4393a6da1c19 pobierałem z obu kont poprzez obydwa access_tokeny.
To dobrze, że API nie zwraca zamówień z kont powiązanych,
więc pobierając oba zamówienia z dwóch kont powiniem mieć jedno zamówienie na jednym koncie, a na drugim not found,
podczas, gdy w rzeczywistości jedno zamówienie mam widoczne z obu kont, a drugie z żadnego.
To tak, jakby access_token z 97713667 był przypisany do 80830642

**Comment by Lukasz-Zurek** [comment]
Nie odnotowałem tutaj problemu. Sprawdziłem dokładnie nasze logi i zamówienie "fb808021-bf9f-11eb-aa8e-4393a6da1c19" zwracaliśmy prawidłowo tylko dla konta: 97713667 (dla drugiego konta: 80830642 nie zwracaliśmy tego zamówienia - status błędu: 404).

Natomiast zamówienie "6d717471-c192-11eb-bee1-7d7ffc2980d1" prawidłowo zwracaliśmy tylko dla konta: 80830642 (dla drugiego konta: 97713667 nie zwracaliśmy tego zamówienia - status błędu: 404).

**Comment by kfijalko** [comment]
@drzemik skasuj dane osobowe klienta.

**Comment by drzemik** [comment]
Dziękuję, problem z zamówieniami rozwiązany.
