### ISSUE TITLE
Fulfillment od Allegro - dostęp do API usług logistycznych

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#4518]
Witam.
1. Czy jest, albo będzie, dostęp do obsługi autorskim oprogramowaniem nowej usługi logistycznej, którą oferuje Allegro? 
2. Czy aktualnym REST API jesteśmy w stanie to jakoś obsłużyć?

**Comment by alekskuc** [comment]
Cześć, jest i można jakoś. https://developer.allegro.pl/wza/
Pozdrawiam

**Comment by hahyes** [comment]
> Cześć, jest i można jakoś. https://developer.allegro.pl/wza/
> Pozdrawiam

Przecież on nie pyta o wysyłanie paczek, tylko o usługę logistyczną tzw. Fulfillment od Allegro.

**Comment by troncomputers** [comment]
Czyli jeśli to jest kwestia tylko przekazania info do Allegro "spakuj mi i wyślij tym" to jak klient ma taką usługę włączoną to na jego panelu, po zalogowaniu, pewnie jest guzik, który wystarczy nacisnąć. Zastanawiam się czy to nie będzie strata czasu na oprogramowanie tego z systemem ERP, a wystarczy tylko zaznaczyć kilka zamówień, nacisnąć guzik i gotowe, ponieważ Allegro wszystkie niezbędne informacje ma.

**Comment by hahyes** [comment]
> Czyli jeśli to jest kwestia tylko przekazania info do Allegro "spakuj mi i wyślij tym" to jak klient ma taką usługę włączoną to na jego panelu, po zalogowaniu, pewnie jest guzik, który wystarczy nacisnąć. Zastanawiam się czy to nie będzie strata czasu na oprogramowanie tego z systemem ERP, a wystarczy tylko zaznaczyć kilka zamówień, nacisnąć guzik i gotowe, ponieważ Allegro wszystkie niezbędne informacje ma.

To nie jest to. WZA to jest usługa integracji z dostawcami przez Allegro, to nie jest Fulfillment.

**Comment by Lukasz-Zurek** [comment]
@troncomputers 

> 1. Czy jest, albo będzie, dostęp do obsługi autorskim oprogramowaniem nowej usługi logistycznej, którą oferuje Allegro?

Mamy w planach wdrożenie zasobów w API odpowiadających za usługę "Fulfillment od Allegro". Nie jestem jednak w stanie wskazać konkretnego terminu. 

> 2. Czy aktualnym REST API jesteśmy w stanie to jakoś obsłużyć?

Nie.

**Comment by troncomputers** [comment]
Czy rozumiem, że klient na tę chwilę ma możliwość obsługi tej usługi po stronie Allegro. Jest do tego jakiś panel obsługi? Nasz klient od stycznia się przymierza do uruchomienia na początku wakacji. Wychodzę z założenia, że usługa jest gotowa tylko nie ma publicznego API?

**Comment by hahyes** [comment]
> Wychodzę z założenia, że usługa jest gotowa

https://allegro.pl/kampania/fulfillment?affiliation_category=marketing&affiliation_source=fulfillment

Jest wszystko napisane wyraźnie.

**Comment by Lukasz-Zurek** [comment]
> Czy rozumiem, że klient na tę chwilę ma możliwość obsługi tej usługi po stronie Allegro. Jest do tego jakiś panel obsługi? Nasz klient od stycznia się przymierza do uruchomienia na początku wakacji. Wychodzę z założenia, że usługa jest gotowa tylko nie ma publicznego API?

@troncomputers Najlepiej będzie jak w sprawie samej usługi, jak i warunków, skontaktujesz się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Natomiast jak już wystartujemy z usługą w naszym API, poinformujemy o tym w [naszych aktualnościach](https://developer.allegro.pl/news/).

**Comment by troncomputers** [comment]
Ok. Dzięki za info ✌
