### ISSUE TITLE
Produktyzacja - kategoria i kategorie podobne [similar]

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4519]
Sugestia:
Do metody product-proposals proszę dodać możliwość podania category->similar[].
Jestem na etapie wprowadzania produktów do bazy allegro i okazało się że mam produkty, które mogą być przypisane do wielu kategorii.
"sprężyny gazowe (siłowniki)" mapują się na "siłowniki klapy bagażnika" i "siłowniki maski".
Spinki i elementy montażowe mają wiele zastosowań, które na allegro mają osobne kategorie.
Zgłaszanie zmian do produktu przez formularz nie wchodzi w grę.

**Comment by kfijalko** [comment]
Przeczytałem newsa o wprowadzeniu kategorii podobnych i jak to ma działać.
W takim wypadku będę pisał do Was jak będę potrzebował kategorię podobną.

**Comment by Lukasz-Zurek** [comment]
@kfijalko Cieszę się, że udało się Tobie zapoznać z naszym newsem. Gdyby pojawiły się dodatkowe pytania dotyczące `category.similar`, napisz proszę w tym wątku.
