### ISSUE TITLE
Excel pobierający dane z ofert dostępnych na allegro

### ISSUE THREAD

**Issue by dkowalewska** [allegro/allegro-api#452]
Muszę stworzyć plik w excelu łączący się z bazą allegro w celu wygenerowania
prostego zestawienia cen wybranych produktów. Z informacji na stronie
https://developer.allegro.pl wynika, ze konieczne jest zarejestrowanie aplikacji. W
formularzu rejestracyjnym jest obowiązkowe pole adres url, a moją aplikacją byłby
plik w excelu, który nie posiada adresu url. Gdy podaję adres serwera kod
wygenerował się, ale po wpisaniu do zakładki "interfejs api sieci web" nie został
zaakceptowany (komunikat: potrzebna jest nazwa klucza interjesu API sieci web).
Przeszukuję dostępną dokumentację, ale nie widzę nigdzie opisanego przypadku
połaczenia przez plik excel. Support allegro odpisał mi, ze nie ma możliwości połączenia przez excela metodami API. Na forum jest jeden ticket związany z VBA https://github.com/allegro/allegro-api/issues/55 dotyczący innego problemu niż samo połaczenie, z którego wynika jednak, że jest mozliwość zrealizowania takiego połączenia przez vba. Zależałoby mi na uzysakniu informacji:
1) czy rzeczywiście nie da się pobierać danych bezpośrednio do pliku Excel 
2) jeśli jest to możliwe, to jak zainicjować samo połaczenie (na dalszym etapie konieczne będzie wywołanie metody doGetItemsInfo https://allegro.pl/webapi/documentation.php/show/id,52#method-input - z tego co widzę, ta metoda chyba najlepiej pasuje do generowania zestawień cenowych produktów już wprowadzonych na allegro)

**Comment by PawelTaberski** [comment]
W kwestii rejestracji aplikacji, powinieneś mieć lokalnie postawiony serwer i przy rejestracji aplikacji w polu adresu url podaj localhost:{port}.
