### ISSUE TITLE
Błąd tworzenia paczki Inpost

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4521]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Podczas tworzenia paczki otrzymujemy błąd:

Receiver point is incorrect | Punkt odbiorcy jest niepoprawny

Wygląda na to jednak, że punkt jest poprawny.

CommandId: ca7566ff-81bf-4df7-b218-3379b7d545f3

**Comment by Lukasz-Zurek** [comment]
@marmited Problem zgłosiłem do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@marmited Wszystko wskazuje na to, że problem spowodowany był brakiem aktualizacji punktu w systemie firmy Inpost. Dostępność punktów zmienia się dynamicznie, natomiast same aktualizacje odbywają się najczęściej w godzinach 6:00, 12:00 i 18:00.

**Comment by marmited** [comment]
@Lukasz-Zurek błąd wciąż występuje. Musieliśmy zmienić paczkomat docelowy.

**Comment by Lukasz-Zurek** [comment]
@marmited Wspomniany [punkt](https://inpost.pl/paczkomat-ornontowice-orn01n-krotka-paczkomaty-slaskie) nie jest już zwracany przez Inpost. Jest niedostępny.

**Comment by marmited** [comment]
Dziękuję!
