### ISSUE TITLE
Adresy stron z informacjami o produkcie a mimo to brak możliwości edycji

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4523]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] inny

:beetle: **Opis**

Pojawiają się w sprzedaży produkty które w opisie mają adres strony internetowej z dodatkowymi informacjami. Przykładowy fragment opisu:

_Zgodność urządzenia możesz sprawdzić na stronie www.LEGO.pl/devicecheck_

Podczas próby zmiany ilości lub ceny produktu z takim opisem otrzymujemy błąd:

_Usuń z opisu oferty adresy stron zewnętrznych, za pośrednictwem których prowadzona jest sprzedaż poza Allegro. Możesz podać adresy stron, na których umieszczone są jedynie informacje poszerzające wiedzę o oferowanym produkcie._

Przykładowy trace-id: dc2caa6158b89bfc

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Zweryfkowałem trace-id: dc2caa6158b89bfc. Komunikat jest prawidłowy. Będziesz musiał usunąć z opisów ofert wszystkie linki prowadzące do stron zewnętrznych (zgodnie z komunikatem), w tym: www.LEGO.pl/devicecheck.

W powyższym przypadku nie odnotowałem próby podpięcia produktu. Jeśli jednak opis pobierasz z naszej bazy produktowej, podaj proszę id produktu - błąd w opisie zgłoszę do zespołu odpowiedzialnego za produktyzację w naszym serwisie.
