### ISSUE TITLE
Full Template Reload

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4524]
Dzień dobry. Aktualizuję informacje o ofercie poprzez wysłanie całego szablonu. Ze względu na fakt, że parametry produktu i parametry oferty muszą być określone osobno (co jest bardzo niewygodne), ponownie szukam produktu, do którego należy powiązać ofertę. Sądząc po tytule, znalazłem dokładnie ten produkt, do którego aktualnie powiązana jest oferta. Biorąc to pod uwagę, w pliku json w informacjach o produkcie brakuje EAN, chociaż na stronie w interfejsie widzę, że jest obecny. Wysyłam fragment z parametrami produktu do szablonu, który wysyłam za pomocą PATCH na Allegro. W odpowiedzi pojawia się błąd:

`{"errors":[{"code":"ConstraintViolationException.ValidProduct","message":"Brakuje parameteru EAN (225693) o wartości: \"5904608804303\" dla oferty z produktem.","details":"ConstraintViolationException.ValidProduct","path":"null","userMessage":"Brakuje parameteru EAN (225693) o wartości: \"5904608804303\" dla oferty z produktem."}]}`

- Skąd Allegro zna ten EAN, jeśli nie znajdę go w żadnym produkcie?
- Po co mam określać EAN przy powiązaniu z produktem? Ten parametr jest opcjonalny, co widać w interfejsie Allegro przy tworzeniu produktu.
- Czy podczas aktualizacji w ten sposób konieczne jest określenie parametrów oferty? Jeśli tak, to czy istnieje metoda aby określić, które parametry oferty, a które produktu?

**Comment by Lukasz-Zurek** [comment]
Problem zweryfikuję i wrócę wkrótce z odpowiedzią. Proszę o cierpliwość.

**Comment by vartaller** [comment]
Dziękuję, czekam

**Comment by Lukasz-Zurek** [comment]
@vartaller Podaj proszę trace-id dla wywołanego wcześniej requesta.

**Comment by vartaller** [comment]
> @vartaller Podaj proszę trace-id dla wywołanego wcześniej requesta.

Skąd wziąć ten trace-id? Mam taką odpowiedź
`{"errors":[{"code":"ConstraintViolationException.ValidProduct","message":"Brakuje parameteru EAN (225693) o wartości: \"5904608804303\" dla oferty z produktem.","details":"ConstraintViolationException.ValidProduct","path":"null","userMessage":"Brakuje parameteru EAN (225693) o wartości: \"5904608804303\" dla oferty z produktem."}]}`

**Comment by Lukasz-Zurek** [comment]
@vartaller Trace-ID otrzymujesz w nagłówku odpowiedzi na wywołanego requesta.

**Comment by vartaller** [comment]
Wysłałem Panu pełną odpowiedź i nie widzę żadnego trace id w odpowiedzi.

**Comment by vartaller** [comment]
> @vartaller Trace-ID otrzymujesz w nagłówku odpowiedzi na wywołanego requesta.

af9041d457b00753

**Comment by Lukasz-Zurek** [comment]
@vartaller Dziękuję. Sprawę cały czas konsultujemy. Wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@vartaller 

Przepraszam za długi czas oczekiwania na odpowiedź. 

Kategoria, w której próbujesz wystawić ofertę, posiada dodatkową walidację, w przypadku której parametr EAN (225693) jest wymagany, mimo, iż parametr ten nie jest identyfikujący i jest nieobowiązkowy. Jest to wyjątkowa sytuacja. 

Co jest również istotne - w żądaniu, w sekcji "product" niepotrzebnie przekazujesz parametry. Jeśli chcesz zmienić w ofercie produkt na inny - wystarczy, że przekażesz "product.id". Zaktualizujemy parametry produktowe zgodnie z danymi w powiązanym produkcie. Dzięki temu unikniesz tego typu błędów.

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-przypisa%c4%87-produkt-do-oferty).

**Comment by vartaller** [comment]
> @vartaller
> 
> Przepraszam za długi czas oczekiwania na odpowiedź.
> 
> Kategoria, w której próbujesz wystawić ofertę, posiada dodatkową walidację, w przypadku której parametr EAN (225693) jest wymagany, mimo, iż parametr ten nie jest identyfikujący i jest nieobowiązkowy. Jest to wyjątkowa sytuacja.
> 
> Co jest również istotne - w żądaniu, w sekcji "product" niepotrzebnie przekazujesz parametry. Jeśli chcesz zmienić w ofercie produkt na inny, korzystając z zasobu: [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) - wystarczy, że przekażesz `"product.id"`. Zaktualizujemy parametry produktowe zgodnie z danymi w powiązanym produkcie. Dzięki temu unikniesz tego typu błędów.
> 
> Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-przypisa%c4%87-produkt-do-oferty).

Dzień dobry. Zastosowałem PATCH /sale/product-offers/{offerId}, jednak produkt oferty nie uległ zmianie. Odpowiedź serwera również nie generuje żadnego błędu, ale po prostu wysyła szablon niezmodyfikowanej oferty.

```
            curl -i -s -X PATCH \
              "https://api.allegro.pl/sale/product-offers/${offer_id}" \
              -H "Authorization: Bearer ${token}" \
              -H 'Accept: application/vnd.allegro.beta.v2+json' \
              -H 'Content-Type: application/vnd.allegro.beta.v2+json' \
              -d "{
                    \"product.id\": \"${prod_id}\"
                  }"
```
trace-id: c727a06d9011416

**Comment by Lukasz-Zurek** [comment]
@vartaller Błędnie przekazujesz "product.id". Prawidłowy request powinien zawierać:

```
{
   "product": {
      "id": "78e9a52e-fd6e-4ce3-99f5-3f5b14a9aa84"
            }
         }
```
Daj proszę znać czy udało Ci się przypisać produkt w ten sposób.

**Comment by vartaller** [comment]
Tak, udało się. Dziękuję
