### ISSUE TITLE
Pytanie odnośnie pewnej strony

### ISSUE THREAD

**Issue by Kacpieee** [allegro/allegro-api#4527]
Dzień dobry

Mam pytanie do supportu Allegro.
Natknąłem się na stronę https://spolshy.com.ua/ która działa w ukrainie i korzysta z bazy produktów strony Allegro. Raczej jestem zielony w temacie żeby stwierdzić jak jakaś strona pobiera dane ale wydaje mi się że strona nie korzysta z REST API tylko jest tzw. scraperem. Nawet zdjęcia produktów (przykład: https://spolshy.com.ua/product/10744098609) są pobierane z serwera Allegro. Na stronie znajdziemy ok 25 milionów części używanych i nowych zarówno z Allegro jak i Allegro lokalnie. Strona Spolshy zarzeka się że są tylko pośrednikami między Allegro a klientem na Ukrainie i jeśli klient kupi na stronie Spolshy to pracownicy tej strony kupują rzecz u sprzedawcy na Allegro, wtedy rzecz przychodzi do nich do magazynu w Polsce i jest wysyłana do UA.

Moje pytania brzmią:
Czy ta strona działa legalnie czy łamie regulamin Allegro?
I czy moje przypuszczenie o działaniu tej strony jest prawidłowe?

Z góry dziękuję za odpowiedź i jeśli zamieściłem post w złym dziale to najmocniej przepraszam.

**Comment by AureliuszBrussy** [comment]
Działanie takie nie jest zgodne z regulaminem Allegro i staramy się mu przeciwdziałać.
