### ISSUE TITLE
Zapytanie zmieniające cenę i ilość oferty

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4529]
Witam, 
próbuję zmienić cenę oraz ilość wystawionej oferty. Po przez postaman udało mi się to wykonać, natomiast mam problem z kodem i nie wiem gdzie mam błąd. Dlatego chciałam prosić o pomoc.
Pozdrawiam
![Bez tytułu](https://user-images.githubusercontent.com/59577401/119396196-d9513a80-bcd4-11eb-8144-8030b07afe61.png)
![Bez tytułu2](https://user-images.githubusercontent.com/59577401/119396201-d9e9d100-bcd4-11eb-90ac-48dfb754875b.png)
![Bez tytułu3](https://user-images.githubusercontent.com/59577401/119396203-da826780-bcd4-11eb-9ba9-0071087a1efb.png)

**Comment by AureliuszBrussy** [comment]
Prześlij proszę swój pełen request oraz response. Jaki kod błędu zwracamy?

**Comment by kfijalko** [comment]
@Kasia13130 
Jeżeli zmieniasz stan i cenę to zerknij na metody:
https://developer.allegro.pl/documentation/#operation/modificationCommandUsingPUT
W powyższym kodzie widać, że wysyłasz więcej danych, które mogą powodować problemy.

**Comment by Kasia13130** [comment]
Request wykonałam z dokumentacją allegro, według niej należało podać całą zawartość oferty (jak robiłam wersję tylko zmieniającą cenę i ilość to nie działała). Tak czy inaczej spróbuję według powyższego linku.
Poniżej znajduje się cały request, natomiast co do response to po prostu nie przesyła zmienionej zawartości oferty. Po wykonaniu print_r($curl) wyświetla coś takiego:
![image](https://user-images.githubusercontent.com/59577401/119451180-3da3e680-bd35-11eb-985d-0e389d23d08f.png)


$newPriceAndQuantity = '{
"id": "........",
 "name": "Pure Color farba do włosów w żelu",
 "category": {
"id": "47631"
},
 "product": null,
 "parameters": [
{
"id": "......",
 "valuesIds": [
"......"
],
 "values": [],
 "rangeValue": null
},
 {
"id": "......",
 "valuesIds": [
"......"
],
 "values": [],
 "rangeValue": null
},
 {
"id": ".......",
 "valuesIds": [
"......."
],
 "values": [],
 "rangeValue": null
},
 {
"id": ".......",
 "valuesIds": [],
 "values": [
"......."
],
 "rangeValue": null
}
],
 "customParameters": null,
 "description": 
 {
    "sections": [
    {
        "items": 
        [
            {
            "type": "TEXT",
             "content": "<p>Pure Color to pierwsza trwała żelowa koloryzacja od Schwarzkopf</p><p>A tak w ogóle to:</p><p>- Trwały kolor</p><p>- Doskonałe pokrycie siwych włosów</p><p>- Włosy cudownie miękkie w dotyku</p><p>Wypróbuj!</p>"
            }
        ]
    }
    ]
},
 "compatibilityList": null,
 "tecdocSpecification": null,
 "images": [],
 "sellingMode": 
 {
     "format": "BUY_NOW",
     "price": 
     {
         "amount": "25.5",
         "currency": "PLN"
     },
     "startingPrice": null,
     "minimalPrice": null,
     "netPrice": null
 },
 "tax": null,
 "stock": 
 {
    "available": 10,
     "unit": "UNIT"
 },
 "publication": 
 {
     "duration": null,
     "status": "ACTIVE",
     "startingAt": null,
     "endingAt": null,
     "endedBy": null,
     "republish": false
},
 "delivery": 
 {
    "shippingRates": 
     {
        "id": "....."
     },
     "handlingTime": "PT72H",
     "additionalInfo": "",
     "shipmentDate": null
 },
 "payments": 
 {
    "invoice": "NO_INVOICE"
 },
 "discounts": null,
 "afterSalesServices": 
 {
    "impliedWarranty": {
    "id": "......."
    },
     "returnPolicy": {
    "id": "....."
    },
     "warranty": null
 },
 "additionalServices": null,
 "sizeTable": null,
 "fundraisingCampaign": null,
 "promotion": 
    {
   "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
    },
 "location": {
 "countryCode": "PL",
 "province": "",
 "city": "",
 "postCode": ""
    },
     "external": null,
     "attachments": [],
     "contact": null,
     "validation": {
    "errors": [],
     "warnings": [],
     "validatedAt": "2021-04-12T10:01:34.591Z"
    },
 "createdAt": "2021-04-12T09:47:03.000Z",
 "updatedAt": "2021-04-12T10:01:42.045Z"
}';

**Comment by AureliuszBrussy** [comment]
Do modyfikacji ceny oraz liczby sztuk możesz korzystać zarówno z [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) jak i zasobu wskazanego przez @kfijalko. 

Jeżeli request do nas dotrał - powinnaś otrzymać response z kodem odpowiedzi (curl_exec(), curl_getinfo()).

**Comment by Kasia13130** [comment]
Dobrze, spróbuję. Dziękuję
