### ISSUE TITLE
Cennik dostawy pole location ... format sprzedaży

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4530]
Dzień dobry, 
Przy edycji cennika dostawy, nie rozumiem pola "location", tzn, gdzie go szukać, jakimi danymi uzupełnić? Ponadto, gdzie mogę znaleźć format sprzedaży ? Podsyłam screena.

![cennik_dostawy](https://user-images.githubusercontent.com/74404770/119450089-bf931000-bd33-11eb-8983-ee312389f812.png)

**Comment by AureliuszBrussy** [comment]
Obiekt **location** określa miejsce, z którego wysyłany jest przedmiot. Więcej informacji o tym polu znajdziesz w [naszej dokumentacji](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Rozwijając odpowiedzi, znajdziesz tam poszczególne pola tego obiektu, ich opis oraz przykładowe wartości. 

Informację, jaki dana oferta ma format sprzedaży znajdziesz w polu **sellingMode.format** (zasób [/sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)).

**Comment by AureliuszBrussy** [comment]
Zmiana w ofercie powinna być widoczna maksymalnie w ciągu godziny, zwykle jest to kwestia kilku minut.
