### ISSUE TITLE
Dostawa i jej koszt ustalane ze sprzedającym

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4532]
Klient zamówił u nas w sklepie dwa przedmioty, które miały podpięty ten sam cennik, w którym jedyną metodą dostarczenia jest odbiór osobisty.

Dlaczego metoda dostarczenia została ustalona na "Dostawa i jej koszt ustalane ze sprzedającym"?

Czy da się zablokować tę metodę w każdym przypadku?

Identyfikator zamówienia:
8498f7a1-ba66-11eb-a304-e582d38674db

**Comment by Lukasz-Zurek** [comment]
Pytanie nie dotyczy konkretnie API. Jednakże "Dostawa i jej koszt ustalane ze sprzedającym" może pojawić się kupującemu w formularzu dostawy i zapłaty również w sytuacji, gdy jedyną opcją dostawy jest odbiór osobisty (odbiór w punkcie sprzedającego), lub w sytuacji, gdy Klient dokona zakupu w kilku ofertach, w których nie pokrywają się opcje dostawy. Nie można niestety zablokować tej metody. Więcej informacji znajdziesz w [Allegro Pomoc](https://allegro.pl/pomoc/dla-sprzedajacych/cennik-dostawy/jak-ustawic-odpowiedni-sposob-laczenia-kosztow-dostawy-dla-ofert-z-roznymi-cennikami-4GDdXnx0LuW).
