### ISSUE TITLE
Czy jakakolwiek metoda API zwraca informację o usłudze SMART?

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#4535]
Witam, pytanie podobne do #4471 - ale tym razem chodzi o **SMART**. Czy jakakolwiek metoda API zwraca informacje o aktywnej (lub nieaktywnej) usłudze SMART dla naszego własnego konta lub dla naszych własnych aukcji?

Ponownie przejrzałem metody API, ale nic takiego nie znalazłem.

Z góry dziękuję za szybką odpowiedź.

**Comment by Lukasz-Zurek** [comment]
Niestety nie mamy tego typu zasobów.

**Comment by javaguru-pl** [comment]
A czy jest możliwość dodania takich informacji (zarówno SMART jaki i SuperSprzedawca).
Myślę że najlepiej do metody /me.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za sugestię. Zgodnie z [naszym newsem](https://github.com/allegro/allegro-api/issues/4337) przenoszę wątek do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions).
