### ISSUE TITLE
Ucinanie redirect_uri, zgłoszenie nr "15688546"    [ ref:_00D24aE05._5003VFGYzq:ref ]

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#4537]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próbuję uzyskać token dla konta 365pro_dw urlem: 
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=00e494be98704f28b15443f71270c4db&redirect_uri=https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&konto=365pro_dw 
Jednak otrzymuję przekierowanie: 
https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&code=C0N1nbXag6sHFrkT3nV2lW6RSbRB4ZwX 
znika konto=365pro_dw 
Jak obejść problem, aby przekierowanie zawierało element geta konto?

**Comment by kfijalko** [comment]
Ostatecznie odpowie allegro, ale napisze co mi się wydaje:
link do dokumentacji:
https://developer.allegro.pl/auth/#authorization-code-flow




redirect_uri | Adres do przekierowania, na który wysłany zostanie kod (musi być zgodny z tym podanym przy rejestracji aplikacji) | wymagany
-- | -- | --





Zakładam, że chcesz przekazać w adresie parametr i otrzymać go w odpowiedzi, do tego masz parametr "state"




state | Dodatkowe dane, które zostaną przekazane z powrotem do aplikacji po autoryzacji | opcjonalny
-- | -- | --

**Comment by drzemik** [comment]
Zamieniłem konto na state i parametr przeszedł, jednak dalej wykonałem post z urlem
https://allegro.pl/auth/oauth/token
i parametrami:
array(3) {
  ["redirect_uri"]=>string(77) "https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&state=365pro_dw"
  ["code"]=>string(32) "Kl3ShPe2i5St3Kyxu21h2DRKR9vdtwWR"
  ["grant_type"]=>string(18) "authorization_code"
}
Zamiast tokena otrzymałem:
{"error":"invalid_grant","error_description":"Redirect URI mismatch."}
redirect_uri jest taki sam, jak w zarejestrowanej aplikacji.

**Comment by Lukasz-Zurek** [comment]
@drzemik 

Parametr `"state"` przekazujesz obecnie w nieprawidłowy sposób, jako część parametru `"redirect_uri"`:
https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&state=365pro_dw
 
Dlatego otrzymujesz błąd:
 
`{"error":"invalid_grant","error_description":"Redirect URI mismatch."}`
 
W związku z powyższym musisz zmienić adres przekierowania na stronie [Developer Apps](https://apps.developer.allegro.pl/), jak i w żądaniu, na: 

https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH

aby nie przekazywać parametru `“state”` jako część parametru `“redirect_uri”`. 
Parametr `“state”` musisz przekazać w pierwszym żądaniu o kod autoryzujący, w `“QueryParams”`.
 
Prawidłowy adres żądania powinien wyglądać zatem tak:
 
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=00e494be98704f28b15443f71270c4db&redirect_uri=https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&state=365pro_dw
 
Następnie otrzymujesz odpowiedź:
 
https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH&code={code}&state=365pro_dw
 
Reasumując - parametr `“state”` jest prawidłowo przekazywany, natomiast `“redirect_uri”` jest zgodny z tym, który podałeś na [stronie rejestracji aplikacji](https://apps.developer.allegro.pl/).
 
Następnie możesz już wysłać żądanie o token za pomocą:
 
https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri=https://ads.as3w.eu/index.php/allegro/redirect?instn=ERPATECH
