### ISSUE TITLE
Tax may be filled only if you have company account

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4538]
Podczas próby wystawienia oferty dla zwykłego konta Allegro dostajemy błąd:
_Tax may be filled only if you have company account._

Czy w związku z działaniami związanymi z #4514 jak np. _"...aby określić stawkę VAT, dotychczas niezbędne było przekazanie odpowiedniej wartości w polu payments.invoice. Dzisiaj usunęliśmy tę zależność..."_ mamy spodziewać się tutaj jakichś zmian? Np. czy na kontach zwykłych będzie możliwe lub może nawet obowiązkowe w przyszłości określanie stawki VAT dla wystawianych ofert?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Pytanie nie dotyczy stricte API, nie mamy jednak planów związanych z wdrożeniem możliwości określania stawek VAT przez konta zwykłe.
