### ISSUE TITLE
Wartości parametrów kategorii

### ISSUE THREAD

**Issue by gscoders** [allegro/allegro-api#4539]
Przeglądam sobie dokumentację dla parametrów kategorii i nie mogę doszukać sie co oznaczają te wartości które jak dla mnie mają schemat {id parametru}_{id jakiejś wartości}

dokładnie chodzi mi o te wartości:

```
"requiredDependsOnValueIds": 
[
    "202870_1" // ????
],
"displayDependsOnValueIds": 
[
    "202870_1", // ????
    "202870_2" // ????
]
```

co się kryje za tymi wartościami?

Pozdrawiam, Wojciech Rzepecki

**Comment by Lukasz-Zurek** [comment]
Jeśli **"requiredDependsOnValueIds": ["202870_1"]** to oznacza to, że będzie wymagany wtedy i tylko wtedy, gdy parametr **"202870"** przyjmie wartość **"202870_1"**. Jeśli parametr **"202870"** nie zostanie uzupełniony, to w tym przypadku będzie on nadal opcjonalny.

Jeżeli natomiast określony parametr, z którego chcesz skorzystać, w polu **"displayDependsOnValueIds"** ma wartości: **"202870_1"**, **"202870_2"**, dodatkowo w polu **"dependsOnParameterId"** ma wartość parametru: **"202870"** - oznacza to, że skorzystanie z niego w ofercie jest zależne od dodania parametru: **"202870"** o wymienionych wartościach w polu **"displayDependsOnValueIds"**.

**Comment by gscoders** [comment]
Dziękuję za odpowiedź, jednak dalej nie wiem co kryje się pod np. "202870_1" bo rozumiem że to jest ID i gdzieś można wydobyć na podstawie tego ID wartość słownikowom, przecież w aplikacji nie mogę stworzyć selecta dla klienta z labelami typu "202870_1", "202870_2" 

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
@gscoders Zapoznaj się proszę z [naszym wcześniejszym newsem](https://developer.allegro.pl/news/#options-required-display), gdzie dokładnie opisaliśmy wspomniane parametry.

**Comment by gscoders** [comment]
@Lukasz-Zurek przeczytałem podany artykuł jednak dalej nie mam pojęcia jak wyciągnąć wartość słownikowm dla podanych identyfikatorów, w artykule jest napisane _**w którym zwrócimy identyfikatory wartości parametru warunkującego, dla których ten parametr będzie wymagany, np. może się tutaj znaleźć identyfikator wartości “Nowy” dla parametru “Stan” **_ więc rozumiem że wywołując zasób w API otrzymam zamiast wartości "Nowy" identyfikator tej wartości w postaci właśnie {id_parametru}_{id_wartości} i dalej niestety nie wiem jak na podstawie tego identyfikatora mam wyciągnąć podaną w przykładzie wartość "Nowy" 

Pozdrawiam

**Comment by gscoders** [comment]
@Lukasz-Zurek OK wywołałem sobie zasób parametrów dla losowej kategorii i faktycznie jest pole "dictionary" z listą słownikową i identyfikatorami do nich, dobrze by było gdyby dodać tę informację do artykułu czy dokumentacji Allegro :)

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@gscoders Dziękuję za informację. Cieszę się, że udało się to wyjaśnić. 

Jednocześnie dziękuję za sugestię. Dodamy tę informację do naszego poradnika.
