### ISSUE TITLE
Kody błedów dla REST API

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#454]
Problem mamy następujący, token wygasl poniewaz minelo 365 dni, 
i tak
koncowka ../after-sales-service-conditions/implied-warranties 
zwraca:

         "code" => "FORBIDDEN"
         "message" => "Forbidden"
         "details" => null
         "path" => null
         "userMessage" => "You do not have permission to request this resource"

koncowka /offers/{offerId}/change-price-commands/{commandId}
zwraca:

         "code":"AccessDeniedException",
         "message":"Provided client doesn't have access to this resource",
         "details":"AccessDeniedException",
         "path":null,
         "userMessage":null

Gdzie można znaleźć kody błędów dla poszczególnych metod ?

**Comment by MarcinLuczak** [comment]
@yncki nie udostępniliśmy listy wszystkich błędów, jakie zwracamy. Możesz u nas przeczytać o [statusach HTTP](https://developer.allegro.pl/about/#http-statuses) oraz ogólnie o [obsłudze błędów](https://developer.allegro.pl/about/#errors).

Kwestii różnych komunikatów błędu dla jednego powodu się przyjrzymy.

**Comment by KluseG** [comment]
Czy zespół Allegro planuje uporządkować obsługę błędów w API? Brakuje w niej jakiejkolwiek spójności. Zwracane są kody nieopisane w dokumentacji, a struktura wyjątków jest inna dla praktycznie każdego zasobu.

**Comment by MarcinLuczak** [comment]
@KluseG podaj proszę jakieś przykłady?
