### ISSUE TITLE
Zasób /sale/offers?publication.status=ACTIVE&external.id=

### ISSUE THREAD

**Issue by BartekWroclaw** [allegro/allegro-api#4541]
Jeśli w external.id występuje znak "+" to dostaję pustą kolekcję pomimo tego, że oferta jest aktywna.
W jaki sposób podać takie znak by api zwróciło poprawny wynik?

**Comment by BartekWroclaw** [comment]
Przykładowe external_id: 1234+4321

**Comment by Lukasz-Zurek** [comment]
@BartekWroclaw W external.id znak "+" zamieniany jest na spację, dlatego korzystając z tego zasobu musisz zamienić "+" na "%2B":

https://api.allegro.pl/sale/offers?publication.status=ACTIVE&external.id=1234%2B4321

**Comment by BartekWroclaw** [comment]
> @BartekWroclaw W external.id znak "+" zamieniany jest na spację, dlatego korzystając z tego zasobu musisz zamienić "+" na "%2B":
> 
> https://api.allegro.pl/sale/offers?publication.status=ACTIVE&external.id=1234%2B4321

Zadziałało. Dziękuję.
Jakie jeszcze znaki zamieniacie na jakie?

**Comment by Lukasz-Zurek** [comment]
Sprawę konsultuję. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@BartekWroclaw Korzystamy z encodeURIComponent.
