### ISSUE TITLE
Błąd związany z pobieraniem załącznika w dyskusji

### ISSUE THREAD

**Issue by damianszymanskiphp** [allegro/allegro-api#4543]
Występuje problem:
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, próbuję pobrać załączniki z dyskusji i napotkałem problem. Po pierwsze, dokumentacja mówi że: 
`Skorzystaj z GET /sale/dispute-attachments/{attachmentId} żeby pobrać załącznik z dyskusji. {attachmentId} znajdziesz w danych o dyskusji - w polu attachment.`

Zaś jedyne co mi GET/sale/disputes/{disputeId}/messages zwraca to:
```
(
                    [id] => 6a565741-343a-468a-939e-c6e18061c8d0
                    [attachment] => stdClass Object
                        (
                            [fileName] => 20210525_204321.jpg
                            [url] => https://upload.allegro.pl/sale/dispute-attachments/70d9d645-044f-4719-8194-4cf276a2ab33
                        )

                    [author] => stdClass Object
                        (
                            [login] => (UKRYTE)
                            [role] => BUYER
                        )

                    [createdAt] => 2021-05-25T18:43:48.601Z
                )
```

Nie zwraca więc ID załącznika, a ID wiadomości - nieakceptowany przez zasób /sale/dispute-attachments/{attachmentId}
Z kolei url jest bezużyteczny, bowiem bez autoryzacji na stronie nie można wejść w ten link. Na waszej stronie. Będąc zalogowany na Allegro, owszem link działa, ale po co go udostępniać w API? Nie wiadomo.

**Comment by damianszymanskiphp** [comment]
Z kolei gdy sobie przeparsuje ten url i wezme to ID (zakładam że w linku to ID załacznika jest) to mi wyrzuca:



https://api.allegro.pl/sale/dispute-attachments/70d9d645-044f-4719-8194-4cf276a2ab33&lt;/br&gt;&lt;/br&gt;Array

 {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

**Comment by Lukasz-Zurek** [comment]
Faktycznie nie jest to do końca jasne. Pozwól, że sprawę skonsultuję i wrócę do Ciebie wkrótce z odpowiedzią.

**Comment by damianszymanskiphp** [comment]
Widzę podobny ticket: https://github.com/allegro/allegro-api/issues/1215
Sprawdzę to.

**Comment by damianszymanskiphp** [comment]
Sprawdziłem. Faktycznie po zrobieniu requesta GET na URL który podajecie w polu attachment - działa. Natomiast nie można podawać nagłówka Accept oraz Content-Type, tylko sam token.

Czyli dokumentacja wprowadza w błąd, bo każe podawać nagłówek Accept:
https://developer.allegro.pl/dispute/#pobranie-za%c5%82%c4%85cznika
Dodatkowo nigdzie nie zwraca attachmentId a jedynie w URL w przypadku tego:
https://developer.allegro.pl/documentation/#operation/getAttachmentUsingGET

**Comment by Lukasz-Zurek** [comment]
@damianszymanskiphp Bardzo dziękuję za wskazane błędy w poradniku. Oczywiście poprawimy treść, tak, aby nie wprowadzała w błąd. Sama dokumentacja jest jednak prawidłowa. 

Jeśli chodzi o `"attachmentId"`, zwracamy tę wartość na końcu adresu, w polu: `"attachment.url"`. Tu również doprecyzujemy treść poradnika. Nie jest to błąd, aczkolwiek w pełni rozumiem sytuację, która niejako wymusza konieczność podjęcia dodatkowych działania w celu uzyskania samego `"attachmentId"`.
