### ISSUE TITLE
mam problem z aktywacją konta Testy_Belini

### ISSUE THREAD

**Issue by TomaszBelini** [allegro/allegro-api#4544]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

witam mam problem z aktywacją konta Testy_Belini nie przychodzi link aktywacyjny na podany przy rejestracji e-mail , przez co nie da się aktywować konta

**Comment by Lukasz-Zurek** [comment]
@TomaszBelini Odpowiedzi udzieliłem w [tym](https://github.com/allegro/allegro-api/issues/1046#issuecomment-850162633) wątku.
