### ISSUE TITLE
Przykład z dokumentacji, a błąd "Not acceptable representation requested. Please check 'Accept' request header"

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4545]
Wywołanie jest takie jak w dokumentacji [https://developer.allegro.pl/en/about/](https://developer.allegro.pl/en/about/) podpunkt "Communication protocol": 

```
#!/bin/bash 

curl -X POST \
        'https://api.allegro.pl.allegrosandbox.pl/sale/offers'
        -H 'authorization: Bearer eyJhbGciO....tOZUO2rryhE15iV-QOI' \
        -H 'accept: application/vnd.allegro.public.v1+json' \
        -H 'content-type: application/vnd.allegro.public.v1+json' \
        -d '{
        }'
```

a otrzymuję błąd `Not acceptable representation requested. Please check 'Accept' request header"`: 

```
{"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}
```

Gdzie robię błąd? 
Dziękuję za pomoc.

**Comment by damianszymanskiphp** [comment]
https://developer.allegro.pl/my_offers/#jak-pobra%c4%87-moje-oferty-w-rest-api
Z tego co widzę to nie podaje się content-type choć może dokumentacja wprowadza w błąd, ale polecam sprawdzić.

**Comment by Lukasz-Zurek** [comment]
@leszekdubiel Sprawdziłem to przed chwilą i udało mi się otrzymać prawidłową odpowiedź. Jeżeli w dalszym ciągu otrzymujesz błąd, prześlij proszę przykładowy request i response wraz z trace-id przez nasz formularz kontaktowy. W zgłoszeniu dopisz GitHub #4545.
