### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sergiipopil** [allegro/allegro-api#4547]
Dobry dzień! W dziale motoryzacja, kategorie części samochodowych Używamy Twojego REST API, aby uzyskać listę propozycji ofert Mi poprzez REST API, otrzymujemy zdjęcie produktu, cenę, nazwę, sprzedawcę, mamy możliwość przefiltrowania listy produktów. Proszę mi powiedzieć, jak technicznie możemy uzyskać parametry i opis towaru? Z szacunkiem!

**Comment by kfijalko** [comment]
@sergiipopil
Zakładam, że korzystasz z metody /offers/listing.
Przeczytaj #4213 
Szczegółów oferty innego użytkownika nie da się pobrać.

**Comment by Lukasz-Zurek** [comment]
@sergiipopil Usunąłem wcześniejszy wątek: #4546 z powodu braku treści. Natomiast jeśli chodzi o Twoje pytanie, jak słusznie już zauważył @kfijalko  - nie uzyskasz wspomnianych danych przez: [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Możesz pobrać dane oferty za pomocą zasobu [GET sale/offers/offerID](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) (musisz być autoryzowany jako sprzedawca, do którego należy oferta). Wspomnieliśmy już o tym [w tym wątku](https://github.com/allegro/allegro-api/issues/4266#issuecomment-805574478).
