### ISSUE TITLE
Powiązanie metody dostawy z przewoźnikami

### ISSUE THREAD

**Issue by Avantle** [allegro/allegro-api#4548]
Czy jest jakiś sposób żeby powiązać metodę dostawy z przewoźnikiem? Przy pobieraniu zamówień przez API dostajemy deliveryMethod.id, ale przy dodawaniu listu przewozowego musimy podać carrierId. Pytanie jest następujące - skąd mam wiedzieć, którego carrierId użyć?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Niestety w naszym API pola: `deliveryMethod.id` i `carrierId` nie są ze sobą powiązane. Analogicznie jest na stronie Allegro.pl - otrzymujesz zamówienie od Klienta, z wybraną przez Niego opcją dostawy. Musisz dodatkowo wybrać przewoźnika z listy. Logika jest zatem podobna.

Zapoznaj się jednak proszę z narzędziem "Wysyłam z Allegro", gdzie wybrana przez kupującego metoda dostawy ma wpływ na to, jaką usługę dostawy będziesz mógł wybrać dla otrzymanego zamówienia. To może ułatwić zarządzanie przesyłkami. Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/wza/).
