### ISSUE TITLE
Generowanie klucza do webAPI

### ISSUE THREAD

**Issue by KrzysztofStachyra** [allegro/allegro-api#455]
Cześć,

Czy możecie mnie uświadomić w jakim celu połączone zostało generowanie klucza do WebAPI z danymi do aplikacji pod Rest?

Obecnie klient, korzystający z aplikacji desktop, którą kupuje na rynku aby z niej korzystać musi mieć klucz do webAPI - do tej pory było to niezależne. Teraz formularz wymaga podania danych pod REST API - po co?
Przecież w jego imieniu aplikacja ma to dostarczone przez producenta/developera i klienta to grzeje jakie aplication id i jaki jest redirect url bo on tego na oczy nie widzi a już na pewno nie chce mieć takiej strony u siebie żeby robić redirect...

no chyba, że mnie ktoś olśni co za tym stało

**Comment by rtnet-pl** [comment]
@KrzysztofStachyra  Regulamin usługi WebApi wprowadza w błąd, bo sugeruje że klient powinien sam wygenerować sobie swój klucz. Tymczasem Twoja aplikacja powinna działać na jednym kluczu - Twoim. Użytkownik podaje tylko login i hasło (jeśli jest potrzebne)
https://github.com/allegro/allegro-api/issues/289

**Comment by KrzysztofStachyra** [comment]
Jeszcze nie do końca o to mi chodzi. 
Jasne jest że obecnie musimy korzystać hybrydowo ze starego API i z nowego. Do starego musisz mieć klucz WebAPI, który jest zbędny do Rest API i odwrotnie klucz z Rest API jest zbędny do WebAPI.
Teraz jeśli czy ja czy Ty w swojej aplikacji podpinamy się naszymi kluczami developerskimi pod Rest API to w portalu nadal powinienem mieć rozbite generowanie klucza WebAPI na oddzielną operację a rejestrowanie aplikacji Rest na oddzielną bo do WebAPI każdy musi klucz uzyskać a do rest API już dostarczyć ją klientowi mogę ja czy Ty ze swoich rejestracji.

Teraz biedny nowy użytkownik, który bierze od Ciebie aplikację czy ode mnie nie wie kompletnie co ma wpisać bo połączony jest klucz z webAPI i z restAPI a do zapisania formularza wymagany jest redirectURL czyli teraz musisz się zgłosić do producenta po te dane...

**Comment by lukada4100** [comment]
A od kiedy te zmiany? Moja desktopowa aplikacja pod webApi działa wciąż bez problemów.

**Comment by MarcinLuczak** [comment]
@lukada4100 zmiany w obsłudze kluczy wykonaliśmy [pod koniec maja](https://github.com/allegro/allegro-api/issues/249). A Twoja aplikacja działa, dlaczego miała by nie działać?

Nie blokowaliśmy wcześniej wygenerowanych kluczy WebAPI. One cały czas działają, po prostu nie generujemy nowych kluczy WebAPI - zamiast tego generujemy Client ID.

**Comment by KrzysztofStachyra** [comment]
@lukada4100  - aplikacja działa tylko zmienił się proces rejestracji.

@MarcinLuczak  - słowo klucz to wygaszamy a nie wygasiliśmy czyli zanim wygasicie to jeszcze wiele wody w Wiśle upłynie i dalej webApi będzie używane - zanim my się przeniesiemy też chwilę się zejdzie. 

Jedną z podstawowych do tej pory zasad generowania klucza przez klienta były limity nakładane, więc każdy generował swój klucz.

Jak w takim razie teraz na jednym kluczu developerskim/aplikacyjnym liczone są limity wywołań?

**Comment by lukada4100** [comment]
W panice nie doczytałem do końca. Myślałem że przestajecie generować stringi sessionHandle. Przy okazji pytanie. One są ważne przez godzinę. A czy z dowolnego IP?

**Comment by MarcinLuczak** [comment]
@KrzysztofStachyra zgadza się, to trochę potrwa. Takiej zmiany nie możemy wprowadzać nagle.

Co do limitów, to wszystko opisaliśmy tutaj https://developer.allegro.pl/about/#limits

@lukada4100 sesja trwa godzinę, chyba że wywołasz w międzyczasie jakąś metodę, która wymaga sesji. Wtedy zerujesz licznik i godzina się liczy na nowo. Działają tylko na IP, na którym zostały ustanowione.
