### ISSUE TITLE
Verified app

### ISSUE THREAD

**Issue by esap22** [allegro/allegro-api#4550]
Dzień dobry.  Moje konto zostało niedawno zweryfikowane. Ale nadal nie mogę uzyskać danych przez API. . Bardzo proszę o pomóż. 
![12345](https://user-images.githubusercontent.com/84971970/119985715-373f9400-bfed-11eb-8661-b49311718b3b.jpeg)

**Comment by Lukasz-Zurek** [comment]
Skontaktuj się z nami w tej sprawie poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Jednakże wszystko wskazuje na to, że konto nie zostało zweryfikowane pozytywnie.

**Comment by esap22** [comment]
![61](https://user-images.githubusercontent.com/84971970/119993064-60642280-bff5-11eb-8a61-15255005176b.jpg)
Dziękuję. Napiszę. Weryfikacja była pozytywna
