### ISSUE TITLE
Allegro "Parameter Category Exception" error 

### ISSUE THREAD

**Issue by orulcan** [allegro/allegro-api#4551]
Hi guys. I have problem with Allegro Api.
When I post offer with category ID 55202 I'm getting error 
`{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Given parameter id `219629:Original Manufacturer's Packaging` should no have been passed as `product` parameter."}]}
`
![issueAllegro](https://user-images.githubusercontent.com/34381361/119998037-00f81980-bfd9-11eb-9247-dd0c7f2bb5ed.png)

**Comment by kfijalko** [comment]
Probably you are using:
https://developer.allegro.pl/documentation/#operation/createProductOffers
Read article:
https://developer.allegro.pl/en/product_offers/#how-to-set-offer-parameters

Id the request data you have two fileds/array of parameters:
offer->parameters[]
offer->product->parameters[]
you need to split your parameters between this fileds.
its depends on category->parameter options
example:
           "id": "219629",
            "name": "Oryginalne opakowanie producenta",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": false,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": "219629_380781",
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                **"describesProduct": false**,
                "customValuesEnabled": false
            },

describesProduct": **false** => offer
describesProduct": **true** => product

sorry for my english ;)

**Comment by Lukasz-Zurek** [comment]
@orulcan I fully agree with @kfijalko. You should provide a parameter id: 219629 in **"parameters"** object, not **"product.parameters"**, because this parameter has: `"describesProduct": false.`

**Comment by orulcan** [comment]
Guys I found a solution. If you sending Manufacturer Packaging parameter in product this will must give error. You need to send outside of product body.
Thanks for your help :)
