### ISSUE TITLE
Allegro Retrieve Products

### ISSUE THREAD

**Issue by orulcan** [allegro/allegro-api#4552]
Hi guys, I need retrieve all products without product ID, Is it possible?
-Thanks

**Comment by Lukasz-Zurek** [comment]
No, it is not possible to retrieve products data without product ID.

**Comment by orulcan** [comment]
@Lukasz-Zurek Okay but I need retrieve all product with spesific Category ID Is it possible?

**Comment by Lukasz-Zurek** [comment]
@orulcan It is also not possible. You have to always provide one of the two search parameters: `"EAN"` (EAN of the product) or `"phrase"` (product name). Then you can narrow your search results by using `"category.id"` parameter or different ones. 

You will find more information about searching for a products in [our guide](https://developer.allegro.pl/en/productization/#how-to-find-a-product).

**Comment by orulcan** [comment]
@Lukasz-Zurek I found a solution. You can retrieve all product with https://api.allegro.pl/sale/offers without ProductID
-Thanks for help.
