### ISSUE TITLE
Brak stawki VAT 5% dla niektórych książkowych podkategorii

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4553]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] inny

:beetle: **Opis**

Dla wskazanych poniżej podkategorii z "Książki i komiksy" nie możemy zrobić zmiany ilości sztuk. Dostajemy błąd "Stawka VAT 5.00 nie jest dostępna w kategorii 79419.".

Tu brakuje stawki 5%:
79419,Kultura i rozrywka,Książki i Komiksy,Komiksy,Pozostałe
90879,Kultura i rozrywka,Książki i Komiksy,"Kuchnia, potrawy",Pozostałe
91084,Kultura i rozrywka,Książki i Komiksy,"Sport, forma fizyczna",Sporty indywidualne - pozostałe

Co ciekawe dla podobnych podkategorii VAT 5% jest dostępny. Np. tu jest:
90885,Kultura i rozrywka,Książki i Komiksy,"Kuchnia, potrawy",Dania główne

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę dodatkowo trace-id dla wywołanej próby aktualizacji oferty.

**Comment by tomylee0** [comment]
Przykładowy trace-id próby zmiany oferty: ae37f27709e6402e. 

Operacja była wykonywana w sobotę. Wtedy jeszcze wykonanie poniższych requestów nie zwróciło w odpowiedzi vatu 5%:
/sale/tax-settings?category.id=79419
/sale/tax-settings?category.id=90879
/sale/tax-settings?category.id=91084

Dziś już widzę, że vat 5% został dodany do wszystkich trzech kategorii.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Potwierdzam występowanie błędu w przypadku wskazanego trace-id.

Obecnie "settings.id": 3878d329-5ce3-498d-a058-917d37e82fd8 dla kategorii 79419 jest zwracane prawidłowo. Natomiast VAT 5% dostępny jest dla każdej z podanych kategorii.

Przepraszamy za tymczasowe utrudnienia.
