### ISSUE TITLE
Problem z aktualizacją ceny poniżej 1 zł

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#4554]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
 
Nie mogę wysłać parametrów żeby zaktualizować cenę jeżeli cena  dla aukcji  jest poniżej 1 zł. Prośba o weryfikację dlaczego.

Przykładowy UUID:   3c4b7371-7be9-4e81-8405-40ff9e11ec4c

**Comment by Lukasz-Zurek** [comment]
@Raafal78 Niestety nie znalazłem żadnych logów dla wskazanego UUID. Niemniej jednak minimalna cena w ofercie powinna wynosić minimum 1,00 zł.

**Comment by Raafal78** [comment]
Czy to znaczy że Api nie pozwala na aktualizację ceny dla produktów poniżej 1 zł ? Przecież na Allegro jest sporo produktów z ceną poniżej 1 zł.

**Comment by Lukasz-Zurek** [comment]
Nasz Serwis (w tym również API) - nie pozwala na aktualizację/wystawienie oferty z ceną poniżej 1,00 zł.
