### ISSUE TITLE
KOD API

### ISSUE THREAD

**Issue by cuba1903** [allegro/allegro-api#4555]
Witam poproszę o kod do API dla Allegro Pocztex Kurier 48 Smart aby pasował do EasyUploader. Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Dane konfiguracyjne dla obsługi umowy własnej otrzymasz od Poczty Polskiej. Skontaktuj się proszę z ich przedstawicielem.

**Comment by cuba1903** [comment]
Witam, ale przecież nie potrzeba umowy z Pocztą Polską aby wysyłać Allegro
Smart

Pozdrawiam serdecznie.










Zespół VERA-LUCCI.


pon., 31 maj 2021 o 07:56 MaciejFrackowiak ***@***.***>
napisał(a):

**Comment by MaciejFrackowiak** [comment]
Dlatego doprecyzuj proszę czego potrzebujesz - nie ma żadnego kodu API dla Allegro Pocztex Kurier 48 Smart. ClientID, który możesz wygenerować osobiście, możesz wykorzystać do każdej aplikacji - zrobisz to na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/).
