### ISSUE TITLE
Produkty zostają automatycznie odłączone od przedmiotów

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#4556]
Witam,
Zauważyłem, że po podpięciu już istniejących produktów do aukcji duża ich część zostaje odłączona następnego dnia (nie są to jednostkowe przypadki, idą w dziesiątki tysięcy a sytuacja powtarza się codziennie). 
Dwa przypadki:
10030691521  => productId 9f28da2b-35a3-4e37-a2c2-fb00bd1451ec
10087260365 => productId 1c27836d-95aa-4d99-be2b-ee73f0bf2052

Prosiłbym o sprawdzenie dlaczego tak się dzieje.

**Comment by MaciejFrackowiak** [comment]
Kwestia weryfikacji powiązań produktów z ofertami jest stricte poza API - dlatego, aby poznać szczegóły procesu, proszę skontaktuj się z obsługą serwisu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by hahyes** [comment]
> Witam,
> Zauważyłem, że po podpięciu już istniejących produktów do aukcji duża ich część zostaje odłączona następnego dnia (nie są to jednostkowe przypadki, idą w dziesiątki tysięcy a sytuacja powtarza się codziennie).
> Dwa przypadki:
> 10030691521 => productId 9f28da2b-35a3-4e37-a2c2-fb00bd1451ec
> 10087260365 => productId 1c27836d-95aa-4d99-be2b-ee73f0bf2052
> 
> Prosiłbym o sprawdzenie dlaczego tak się dzieje.

Przez formularz kontaktowy wiele ci nie powiedzą. Mi na przykład nie odpowiedzieli wcale na prośbę o przekazanie informacji o usuniętym produkcie.

**Comment by dol1234** [comment]
> > Witam,
> > Zauważyłem, że po podpięciu już istniejących produktów do aukcji duża ich część zostaje odłączona następnego dnia (nie są to jednostkowe przypadki, idą w dziesiątki tysięcy a sytuacja powtarza się codziennie).
> > Dwa przypadki:
> > 10030691521 => productId 9f28da2b-35a3-4e37-a2c2-fb00bd1451ec
> > 10087260365 => productId 1c27836d-95aa-4d99-be2b-ee73f0bf2052
> > Prosiłbym o sprawdzenie dlaczego tak się dzieje.
> 
> Przez formularz kontaktowy wiele ci nie powiedzą. Mi na przykład nie odpowiedzieli wcale na prośbę o przekazanie informacji o usuniętym produkcie.

Tak faktycznie to wygląda i nikt nie jest w stanie powiedzieć dlaczego aukcje zostają odłączone od produktów. 
Z moich obserwacji wynika, że produkty są odłączane w przypadku gdy kategoria w produkcie i ofercie nie jest zgodna. 
O ile  z poziomu API można podłączyć taki produkt (oczywiście zostanie usunięty prędzej czy później), to już w przypadku edycji przez stronę już nie. I tu zaczynają się schody - na stronie nie można wyszukać/podłączyć żadnego produktu, więc nie można zgłosić błędu w produkcie - żeby to zrobić trzeba wysłać wiadomość w formularzu.
Oczywiście nie można zmienić kategorii oferty po upływie 12 godzin od jej wystawienia.
@MaciejFrackowiak: czy jesteście świadomi tego problemu? Planujecie udostępnić opcje zgłaszania błędów w produkcie przez API?

**Comment by MaciejFrackowiak** [comment]
@dol1234 Tak, udostępnienie zasobu/zasobów umożliwiających zgłaszanie błędów w produktach jest na liście sugestii dalszego rozwoju Allegro API - na chwilę obecną nie mogę jednak wskazać konkretnej daty.
Natomiast błąd w produkcie możesz zgłaszać obecnie poprzez formularz Zgłoś błąd w produkcie - https://allegro.pl/offer/product/report/{productId}.

**Comment by dol1234** [comment]
Dziękuję, ale byłoby ciężko dla kilkudziesięciu tysięcy aukcji, poczekam.
