### ISSUE TITLE
Automatyczne wznowienie oferty - rozbieżność GUI/API

### ISSUE THREAD

**Issue by wotekPL** [allegro/allegro-api#456]
Podczas wystawiania aukcji zakres danych, które mogę podać dla wznawiania aukcji w API (FID-30) jest równy                                  
```
[sellFormDesc] => Nie wznawiaj|Wznów z pełnym zestawem przedmiotów|Wznów tylko z przedmiotami niesprzedanymi
[sellFormOptsValues] => 0|1|2
```
Natomiast na froncie opcję jaką możemy podać to opcja tylko z pełnym zestawem ilościowym. 

Prosiłbym o potwierdzenie czy w API została jakaś zaszłość czy da się ustawić opcję wznowić aukcję z przedmiotami niesprzedanymi.

**Comment by MarcinLuczak** [comment]
@wotekPL opcja wznawiania z niesprzedanymi przedmiotami dotyczy licytacji.

**Comment by wotekPL** [comment]
Dzięki za info.
