### ISSUE TITLE
Can I get different offers for the same product through API?

### ISSUE THREAD

**Issue by lanrenbulan** [allegro/allegro-api#4563]
For example, if multiple sellers sell the same product and have multiple offers, can I get these offers through API, so that I can optimize the price of my offer.

**Comment by MaciejFrackowiak** [comment]
No, an authorized seller has access only to its offers. Only using [GET /offers/listings](https://developer.allegro.pl/documentation/#tag/Public-offer-information) you can search all offers - but this resource requires verification to use it. You can read more about verification [here](https://developer.allegro.pl/en/news/#public-offers-restrictions).

**Comment by MaciejFrackowiak** [comment]
The verification process is out of our scope - please, write again via a contact form and explain why do you want to use GET /offers/listing resource. Your request should be forwarded to the verification department.
