### ISSUE TITLE
Can an attribute be required or unrequired under different categories? 

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4564]
Can an attribute be required or unrequired under different categories? Or can its features change on a category basis? For example:
{
             "id": "451",
             "name": "Colour",
             "type": "dictionary",
             "required": true,
             "requiredForProduct": true,
             "unit": null,
             "options": {
                 "variantsAllowed": false,
                 "variantsEqual": false,
                 "ambiguousValueId": "451_2048",
                 "dependsOnParameterId": null,
                 "requiredDependsOnValueIds": null,
                 "displayDependsOnValueIds": null,
                 "describesProduct": true,
                 "customValuesEnabled": false
             }
}

**Comment by hahyes** [comment]
Every category has it's own atrributes set and own values of attributes set. It means that you can't group attributes by id number. If you buffering categories to the database, you will need to save every attribute set for every category.

**Comment by MaciejFrackowiak** [comment]
As @hahyes wrote - every single category has its own parameters, so you should retrieve them category by category using [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).
