### ISSUE TITLE
Zwroty https://allegro.pl/moje-allegro/sprzedaz/zwroty

### ISSUE THREAD

**Issue by AGCAR-pl** [allegro/allegro-api#4567]
Dobry dzień,

Chciałbym zapytać, czy można go pobrać przez zwrot API.
Konkretnie dane które znajdują się na tym url https://allegro.pl/moje-allegro/sprzedaz/zwroty.
Jest to sytuacja, w której kupujący zwraca towar po pewnym czasie np. 5 dni.
Informacje te nie są dostępne w GET /order/checkout-forms/{checkoutFormId}.

Dziękuję Ci

**Comment by MartaNowaczyk** [comment]
Dzień dobry, na ten moment nie mamy takiego zasobu w API. Pozdrawiam.
