### ISSUE TITLE
Błąd "Could not change offer publication status." przy publikowaniu oferty

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#457]
Co oznacza poniższy błąd:
"Could not change offer publication status. Estimated shipping time may not be empty."

Nie ma go w dokumentacji.

**Comment by rtnet-pl** [comment]
Uzupełnij FID 340 (pole "Wysyłka w ciągu")

**Comment by MarcinLuczak** [comment]
Zgadza się. Musisz uzupełnić w ofercie wysyłkę w ciągu.

Rozumiem, że błąd pojawia się podczas edycji oferty. Edytujesz ją za pomocą doChangeItemFields? Jeśli tak, to jaki dokładnie kod błędu się wtedy pokazuje?
