### ISSUE TITLE
odpowiedź 404 w momencie próby zakupu produktu 

### ISSUE THREAD

**Issue by MazurKamil** [allegro/allegro-api#4570]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

Po wystawieniu oferty , przelogowaniu jak na inne konto i próbie zakupu danego produktu  (użycie przycisku dostawa i płatnosć) nastepuje zwrotka 404. 

![image](https://user-images.githubusercontent.com/49535947/120344988-60686900-c2fa-11eb-80db-f313735179e3.png)

**Comment by MaciejFrackowiak** [comment]
Potwierdzam, występował problem z przejściem do zakładki Dostawa i płatność na Sandbox. Udało nam się już go wyeliminować, mechanizm działa prawidłowo. Przepraszamy za niedogodności.

**Comment by MazurKamil** [comment]
Potwierdzam , błąd naprawiony. Dzięki za szybką reakcję i  naprawienie problemu!
