### ISSUE TITLE
Jak pobrać w RestApi parametry ręcznie wystawianej oferty na allegro - odpowiednika doShowItemInfoExt

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4571]
Witam,
Miałbym pytanie takie jak w temacie.
Szukam już długo i póki co wiem, że mogę pobrać z allegro informacje jakie parametry są wymagane podczas wystawiania aukcji w danej kategorii. Mogę je modyfikować PATCH'em ale ja chciałbym pobrać je GET'em np.: /sale/product-offers/{id.mojej.oferty}.
Stąd moje pytanie: jak mogę pobrać parametry wystawionych ręcznie aukcji ( na stronie allegro.pl )?

Drugie pytanie brzmi co z opisem oferty? W sale/offers/id.oferty również nie mogę go pobrać, podobnie jak pozostałe zdjęcia.

Dziękuję.

**Comment by MaciejFrackowiak** [comment]
Jeśli chcesz pobrać wszystkie parametry danej oferty skorzystaj proszę z [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - otrzymasz je w tablicy "parameters". Opis oferty natomiast otrzymasz w obiekcie "description".
