### ISSUE TITLE
Błędne wartości producenta w kategorii klocki hamulcowe

### ISSUE THREAD

**Issue by Brenndy** [allegro/allegro-api#4574]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

api->sale->categories(250405)->parameters()->get()

Przy próbie wystawienia aukcji w kategorii klocki hamulcowe (250405) występuje błąd
![image (3) (1)](https://user-images.githubusercontent.com/40610163/120451298-94429d80-c391-11eb-86e4-6a18373dd05e.png).
Mimo, że wartość w producencie(127415) była wybrana na GSP (value: 127417_74) i z tego co widzę, problem wynika z faktu, że przy części produktów, wartość pierwszego członu value nie jest zgodna z wartością główną parametru (127415). Po ręcznej zmianie wartości producenta GSP na 127415_74 aukcja wystawiła się poprawnie. Problem występuję przy różnych producentach np. Graf, Greddy.

**Comment by MartaNowaczyk** [comment]
Bez problemu wystawiłam ofertę z parametrem `"id":"127417_74"` dla podanej kategorii. 
Dla `"id": "127415_74"` mamy zupełnie innego producenta `"value": "MAN OE"`

Potrzebuję wiecej informacji: trace-id, nr oferty lub request (może być przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) z dopiskiem GH #4574)
                  
                },

**Comment by Brenndy** [comment]
Przesłałem request przy pomocy formularza kontakowego.
