### ISSUE TITLE
Wysyłam z Allegro - integracja z narzędziem zewnętrznym.

### ISSUE THREAD

**Issue by alektest** [allegro/allegro-api#4575]
Dzień dobry,

Przy próbie odpytania allegro o usługi jakie są dostępne (zasób /parcel-management/delivery-services) dostaję komunikat:
{"error":"access_denied","error_description":"Dostęp zabroniony"}
Nie ma przy tym znaczenia czy robię to na platformie testowej czy na produkcji

Nie wiem czy jest to problem ustawień czy coś innego. Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, do pobrania danych z tego zasobu potrzebna jest autoryzacja użytkownika. Z podanego komunikatu wnioskuję, że korzystasz z [Client_credentials](https://developer.allegro.pl/auth/#client-credentials-flow). Ten sposób autoryzacji nie ma kontekstu użytkownika i pozwala na dostęp tylko do publicznych danych (np. lista kategorii). Skorzystaj np. z Device flow lub Authorization Code flow. Więcej nzjadziesz na [naszej stronie](https://developer.allegro.pl/auth/).

**Comment by alektest** [comment]
Niestety nadal nie otrzymaliśmy dostępu do danych jakie nas interesują. Czy są jeszcze jakieś działania, które możemy podjąć?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będę mógł sprawdzić co się wydarzyło.

**Comment by alektest** [comment]
Dzień dobry, 

Problem polega na logowaniu i uzyskaniu tokenu dostępowego.
Allegro udostępnia cztery sposoby logowania: 
1.	Authorization Code flow
2.	Device flow
3.	Client_credentials flow
4.	Dynamic Client Registration (DCR)

Sposób 3 jest prosty ale nie pozwala nam zarejestrować paczki.
Sposoby 1 i 2 teoretycznie pozwalają, ale trzeba potwierdzać za każdym razem logowanie do Allegro co je również eliminuje.
Zostaje sposób 4 teoretycznie z tego można by było skorzystać - tutaj pytanie, czy musimy zarejestrować w Allegro aplikację przez specjalny formularz aby uzyskać „Software statement ID”?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, 
dla `Dynamic Client Registration (DCR)`, tak czy inaczej musisz skorzystać z autoryzacji typu `Authorization Code flow` lub `Device flow` ([patrz pkt. 4](https://developer.allegro.pl/auth/#dcr-autoryzacja-u%c5%bcytkownika))

W przypadku `device` lub `code flow` użytkownik musi jednorazowo zgodzić się, aby aplikacja mogła wykonywać żądania w jego imieniu. Następnie możesz już korzystać z [refresh tokenów](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena) w celu odświeżania daty ważności tokenów.

**Comment by alektest** [comment]
A czy skorzystanie z Software statement ID rozwiąże problem?

**Comment by MartaNowaczyk** [comment]
DCR służy jako szablon aplikacji - dzięki niemu użytkownik podczas instalacji aplikacji nie musi rejestrować swojej instancji w zakładce Zarządzanie aplikacjami. DCR nie służy pominięciu interakcji użytkownika (czyli konieczności jego zalogowania). 

Tak jak pisałam DCR również wymaga skorzystania z autoryzowania użytkownika przy pomocy code lub device flow.

**Comment by alektest** [comment]
Proszę o informację, gdzie znajdziemy wspomniane wcześniej trace-id wywołania.

**Comment by MartaNowaczyk** [comment]
Trace-id był potrzebny do sprawdzenia z jakiego typu autoryzacji korzystaliście, gdy dostaliście ten pierwotny błąd. Wydaje mi się, że to już wyjaśniliśmy.

Trace-id znajduje się w nagłówku naszej odpowiedzi.

**Comment by alektest** [comment]
> DCR służy jako szablon aplikacji - dzięki niemu użytkownik podczas instalacji aplikacji nie musi rejestrować swojej instancji w zakładce Zarządzanie aplikacjami. DCR nie służy pominięciu interakcji użytkownika (czyli konieczności jego zalogowania).
> 
> Tak jak pisałam DCR również wymaga skorzystania z autoryzowania użytkownika przy pomocy code lub device flow.

W takim razie w przypadku integracji z narzędziem zewnętrznym nie ma możliwości pominięcia konieczności logowania do wysyłam z Allegro?

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości pominięcia logowania.

**Comment by alektest** [comment]
Jak w takim razie przejść proces logowania skoro aplikacja, która ma zostać zintegrowana z wysyłam z Allegro nie jest aplikacją na przeglądarkę?

**Comment by MartaNowaczyk** [comment]
Należy skożystać z autoryzacji typu [Device flow](https://developer.allegro.pl/auth/#device-flow).
