### ISSUE TITLE
Czy jest możliwość dostatnia linka oferty? /sale/offers

### ISSUE THREAD

**Issue by oosebossoo** [allegro/allegro-api#4576]
Witam,

Zgłębiłem wasze poradniki, pod tym linkiem: https://developer.allegro.pl/my_offers/. Nie znalazłem inforamcji o pozyskiwaniu linku do oferty(jest tylko link do obrazka 'primaryImage'), czy jest taka możliwość, jeśli nie to czy przewidujecie rozszerzenie o tę funkcjonalność?

**Comment by hahyes** [comment]
Link do oferty możesz stworzyć samemu dopisując numer oferty do adresu "https://www.allegro.pl/oferta/tutaj_numer_oferty"

**Comment by MartaNowaczyk** [comment]
@oosebossoo nigdzie nie pobierzesz takiego linku przez API Allegro. Nie planujemy wprowadzenia takiej możliwości.

**Comment by oosebossoo** [comment]
Dziękuje za info
