### ISSUE TITLE
Notorycznie występujący HTTP 429 Too many requests...

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#4577]
Wczoraj zauważyliśmy że w logach pojawił się masowo występujący błąd HTTP 429 Too many requests - przy wywoływaniu różnych metod na środowisku produkcyjnym (/sale/offers, /sale/offer-events, /me, ...). Ponieważ nasza aplikacja obsługuje sporą ilość kont Allegro - to od dobrych kilku m-cy używaliśmy w naszej aplikacji limitu 300 RPS (po wcześniejszym uzgodnieniu z p. Michałem Jackiem z Allegro).
Niestety od wczoraj taki limit zaczął powodować liczne błędy. Być może ma to jakiś związek z wprowadzeniem ograniczeń od 1. czerwca na metodę /offers/listing???
Czy możemy prosić Państwa o pomoc w tej sprawie?
Z góry dziękuję.
Mateusz Maksymiuk
TradeWatch.pl

**Comment by MartaNowaczyk** [comment]
Przykro mi, ale nic nie wiem o takich ustaleniach, dlatego nie widzę błędu po naszej stronie. W takim wypadku proszę skontaktować się z tym - z kim miał Pan kontakt.

**Comment by javaguru-pl** [comment]
Witam Pani Marto, wysłałem kilka maili do p. Michała, niestety on ma w zwyczaju odpowiadać z kilkudniowym opóźnieniem, natomiast ta sprawa jest dla nas dość pilna. Jeżeli ma Pani możliwość bezpośredniego kontaktu z p. Michałem Jackiem to bardzo proszę skontaktować się z nim i zweryfikować iż wcześniej był uzgodniony większy limit RPS. Bardzo potrzebujemy przywrócić dotychczasowy limit RPS aby na bieżąco przetwarzać dane transakcyjne użytkowników naszej aplikacji. Może Pani to dla nas zrobić?

**Comment by MaciejFrackowiak** [comment]
W zastępstwie Marty i Michała - sprawdziliśmy ustawienia, dokonaliśmy niezbędnego odświeżenia mechanizmów i obecnie problem nie powinien się już powtórzyć.

**Comment by javaguru-pl** [comment]
Witam Panie Macieju, BARDZO Panu dziękuję za szybką i sprawną reakcję. Wydaje się że błąd przestał już występować. Gdyby pojawił się ponownie - niezwłocznie o tym poinformuję. Pozdrawiam i życzę miłego weekendu;)

**Comment by javaguru-pl** [comment]
Witam Panie Macieju,

Wygląda na to że błąd znowu powrócił - dzisiaj ok. godz. 23:00 (czwartek).
Teraz nawet pojedyncze wywołanie jakiejkolwiek metody zwraca HTTP 429, aczkolwiek komunikat jest trochę inny: "The server is not able to complete the request. Please try again in a few minut...". Co ciekawe na naszym drugim kluczu (developerskim) - API działa prawidłowo (przynajmniej metody używające bearer-token-for-application). Czy możemy liczyć na naprawę błędu?

**Comment by MaciejFrackowiak** [comment]
Tym razem nie był to błąd, a przekroczenie limitu wywołań - szczegóły przekażę w bezpośredniej wiadomości mailowej.
