### ISSUE TITLE
Questions about the “Get categories suggestions”

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#4579]
How are you dear allegro team
In the near future, we want to use the interface provided by the platform to get the directory through the title.
 because the title character of the allegro platform is 50, there will be cases where the incoming title interface returns the category  id to be empty. 
Is it possible to add a description field to the interface parameter so that the corresponding category  id can be returned more accurately.
This is one of my thoughts. Does your company have a better suggestion to deal with the situation that the interface return directory is empty?
![image](https://user-images.githubusercontent.com/72594584/120617678-eddbc280-c48c-11eb-864d-541f24f6d193.png)

**Comment by MaciejFrackowiak** [comment]
I sent a similar request and I received a suggested category:

```
{
    "matching_categories": [
        {
            "id": "123448",
            "name": "Pendants",
            "parent": {
                "id": "123422",
                "name": "Women's Jewelry",
                "parent": {
                    "id": "19732",
                    "name": "Jewelry and Watches",
                    "parent": {
                        "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0",
                        "name": "Fashion",
                        "parent": null
                    }
                }
            }
        }
    ]
}
```

**Comment by bingnew** [comment]
Do you mean that if the interface returns an empty result, just call the interface again?

**Comment by bingnew** [comment]
Do you mean that if the interface returns an empty result, just call the interface again?

**Comment by bingnew** [comment]
Do you mean that if the interface returns an empty result, just call the interface again?

**Comment by bingnew** [comment]
Do you mean that if the interface returns an empty result, just call the interface again?

**Comment by bingnew** [comment]
And If we upload advertisements in large quantities, is there any time and frequency limit for calling this interface?

**Comment by MaciejFrackowiak** [comment]
Yes, it will be OK, but I can check your previous request - please, give me its trace-id.
We have one main limit - 9000 requests per minute - you can read all the necessary information in [our tutorial](https://developer.allegro.pl/en/about/#limiting-the-number-of-queries-limits).

**Comment by bingnew** [comment]
Thanks for your kind help！
For example, the following two headings:
 Knaga kabłąkowa do łodzi Czarny + czerwony       trace id:169a3cd3689bb8bb。
![image](https://user-images.githubusercontent.com/72594584/120963492-4a442800-c794-11eb-84e9-6e80e39da707.png)

 Końcówki błotników Osłony obiektywu . Palić         trace id： 3ca74e1а3761a545
![image](https://user-images.githubusercontent.com/72594584/120963540-5b8d3480-c794-11eb-9821-36fec75c9f2b.png)

 we can't get the result, please check it?
What should I do if I can't get the results by passing in the title when uploading the ad?

**Comment by MaciejFrackowiak** [comment]
Thanks for the examples. I checked our logs and I see that:

1. for "Knaga kabłąkowa do łodzi Czarny + czerwony" you used too specific description of knaga - if you just use "Knaga do łodzi Czarny + czerwony", you will get a suggested category:

```
{
            "id": "148237",
            "name": "Cleats",
            "parent": {
                "id": "13590",
                "name": "Yacht Equipment",
                "parent": {
                    "id": "13542",
                    "name": "Sailing",
                    "parent": {
                        "id": "13535",
                        "name": "Water Sports",
                        "parent": {
                            "id": "3919",
                            "name": "Sports and Travel",
                            "parent": null
                        }
                    }
                }
            }
        },
 ```

2. for "Końcówki błotników Osłony obiektywu . Palić" word "palić" does not suit the whole title - if you just skip it, you will get a response with suggested categories.

**Comment by bingnew** [comment]
Thank you very much, we will optimize our title
