### ISSUE TITLE
Liczba ofert na listingu

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#458]
Witam,
Ograniczenie listingu do 6k ofert: 
    "searchMeta": {
        "availableCount": 6000,
        "totalCount": 43420,
        "fallback": false
    },
W dokumentacji jest 60k, w przeglądarce allegro.pl jest - uwaga: było 60k a dzis jest 6k.
Czy mi się wydaje czy to się zmeniło dziś w nocy ;) ?

**Comment by kfijalko** [comment]
Nie no było 60k bo pobierałem listę ofert 95k.
Co się stało ?

**Comment by LukaszKorek** [comment]
Tak, wczoraj po południu wprowadziliśmy zmianę. Wktótce uaktualnimy dokumentację.

**Comment by LukaszKorek** [comment]
Jeśli podasz w zapytaniu ID sprzedawcy, to możesz pobrać nawet 120 000 ofert.
