### ISSUE TITLE
error product-offer

### ISSUE THREAD

**Issue by Tradetechnique** [allegro/allegro-api#4580]
Hi,
I'm trying to send with api "sale/product-offer"when I want to send many product but its work when I send 1 product.
Here is the json for 2 products:
[{
"product": {
		"id": "d9779729-3ce7-4a22-ab78-9089342f01ae"          
},
"sellingMode": {
		"price": {
	"amount": "79.01",    
	"currency": "PLN"
		}
},
"stock": {
		"available": 2               
},
	"publication": {
		"status": "ACTIVE"
},
"delivery": {
	"shippingRates": {
		"name": "default"
	}	
},
	"impliedWarranty": {
	"name": "default"
		}
	}]

 I have this error:
 Response status code product getProduct: 422 {"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"","userMessage":"Invalid request. Please contact the application author."}]}
 
 Can you help me?
 And can you tell me what is the limit can I send with 1 call?
 
 Thanks

**Comment by MaciejFrackowiak** [comment]
You can send only 1 product in a single request.

**Comment by Tradetechnique** [comment]
Thanls for your answer.
I want to make an batch update of the price and qte?
Witch api I need to use?

Le ven. 4 juin 2021 à 07:43, MaciejFrackowiak ***@***.***> a
écrit :

**Comment by MaciejFrackowiak** [comment]
For batch modifications:

1) price - [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT)

2) quantity - [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/quantityModificationCommandUsingPUT)

**Comment by Tradetechnique** [comment]
Great,
We are new seller on Allegro I want to list more than 10000 existing
product allegro on my shop.
That I have to list them One by one with "product-offer"?

Le ven. 4 juin 2021 à 11:34, MaciejFrackowiak ***@***.***> a
écrit :

**Comment by MaciejFrackowiak** [comment]
Yes, you should send as many single requests as many products you have.

**Comment by Tradetechnique** [comment]
Hi,
I want to make an batch update of the price with for every product an
different fixed price.
Its possible?

Thanks

Le ven. 4 juin 2021 à 13:51, MaciejFrackowiak ***@***.***> a
écrit :

**Comment by MaciejFrackowiak** [comment]
No, it is not possible. You can set only the same price for all the offers which you put in a request.

**Comment by Tradetechnique** [comment]
Thank you for the clarification.
So if we have big catalog we have to update price one by one if they are
different?

Le mar. 8 juin 2021 à 08:35, MaciejFrackowiak ***@***.***> a
écrit :

**Comment by MaciejFrackowiak** [comment]
Yes, indeed.
