### ISSUE TITLE
Zła ilość przesyłek, nieistniejąca matoda dostawy

### ISSUE THREAD

**Issue by Tomo2903** [allegro/allegro-api#4582]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Opis**

Nie moge pobrać szczegółów metody wysyłki z API allegro. id metody wysłki pobieram z https://api.allegro.pl/order/checkout-forms/78507851-c52a-11eb-9ec3-899c9c51b00d pola delivery -> method -> id. Próbuje pobrać https://api.allegro.pl/sale/shipping-rates/1a228763-c17a-4b2d-88b0-63b082b04da6 i dostaje 404

Dodatkowo źle jest obliczana ilość przesyłek

**Comment by Tomo2903** [comment]
Przepraszam, pobierałem złą metodą. Już poprałem https://api.allegro.pl/sale/delivery-methods. Klient zamówił 20 przedmiotów gdzie wchodzą 4 przedmioty na paczke i 6 przedmiotów po 1 przedmiocie na paczce. Obliczenie w allegro to 6 paczek. Dlaczego? Nie ma smarta ani nic.

**Comment by MaciejFrackowiak** [comment]
Sposoby obliczania kosztów dostawy i łączenia cenników to de facto temat całkowicie poza API - proszę [skontaktuj się z obsługą serwisu](https://allegro.pl/pomoc/kontakt?kategoria=a22643f3-4fb6-4aaa-ba32-1bd7a6619db6&subjectId=c8ed8df2-243b-4d06-ae79-240c312ea735) w celu uzyskania szczegółowych wyjaśnień.
