### ISSUE TITLE
Szukam ujednoliconej informacji jakie są dostępne czasy trwania i ceny ofert bez opcji do wyczerpania przedmiotów

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4583]
Szukam rzetelnej i klarownej informacji na temat tego jak naliczane są opłaty za wystawianie ofert i jakie są interwały ich trwania?
Z moich dociekań wynika że są naliczane opłaty co 10dni ale nie wiem w jakiej wysokości.
Mam też pytanie w kwestii ofert trwających do wyczerpania przedmiotów. Czy gdyby my ich ubyło szybciej w sklepie stacjonarnym a na allegro wciąż by były dostępne to czy mogę taką ofertę podmienić, dajmy na to po miesiącu, za inną czy co w takim przypadku mam robić?
Pytam bo porad jest wiele. Ale w gąszczu trudno wyszukać dokładnie to czego się szuka. A wręcz staje się to niemożliwe.

**Comment by MaciejFrackowiak** [comment]
Opłata za wystawienie jest naliczana na 10 dni na podstawie wartości początkowej przedmiotu. Opłata również zależy od kategorii, w której wystawiony jest przedmiot - wysokość opłaty możesz sprawdzić w [kalkulatorze opłat](https://allegro.pl/pomoc/dla-sprzedajacych/kalkulator-oplat). Natomiast informacje o ofercie do wyczerpania przedmiotów znajdziesz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-i-edycja-oferty/czym-jest-i-jak-dziala-oferta-do-wyczerpania-przedmiotow-7wOLX0D6dFo). Tematyka jest stricte poza funkcjonowaniem samego API, dlatego w przypadku dalszych pytań proszę [skontaktuj się z obsługą serwisu](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
