### ISSUE TITLE
Jak zweryfikować moje konto i aplikację REST API

### ISSUE THREAD

**Issue by managerdreamext** [allegro/allegro-api#4587]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x ] inny

:beetle: **Opis**

Hello
I am a representative of a sporta delivery service
Our service uses API allegro to provide services
From 1.06.2021 the service stopped working due to the problem of an unverified account.
Our customer number is 87487561
We are seeing an error when working with api https://prnt.sc/14hxogj
mail sporta.com.ua@gmail.com

**Comment by PrzemyslawLukanowski** [comment]
According to our [announcement,](https://developer.allegro.pl/en/news/#public-offers-restrictions) please use [contact form ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)to verify the application.
