### ISSUE TITLE
create offer with ean code,

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4588]
i want to create offer with ean code, so my json like this;
{
 "id":"4059809414071",       
"sellingMode": {          "price": {            "amount": "174.93",            "currency": "PLN"          }        },        
"stock": {          "available": 39        },        
"afterSalesServices": {          "returnPolicy": {            "id": "93d07afa-0ae4-423e-9065-3ad72f57a0d1"          }        },  
"external": {          "id": "3BF3CE48-6F81-4B08-969A-B820EDB51687"        }    
}    
the api returns;
"userMessage": "Product category is required. Please provide category id."

When i set category property, it wants other required fields. i think this product was already defined on the allegro system and only EAN must be enough. I ask for your help

traceid : 2dc5b416703929b3

**Comment by PrzemyslawLukanowski** [comment]
Parameter "Original Manufacturer's Packaging" in the meantime became required, so you should pass it in the "parameters" section. The valid JSON structure might look like this:

```
{
	"product": {
		"id": "277965c7-badb-4db7-bff9-09914fb37024"
	},
	"parameters": [{
		"id": "219629",
		"valuesIds": [
			"219629_286873"
		]
	}],
	"sellingMode": {
		"price": {
			"amount": "374.93",
			"currency": "PLN"
		}
	},
	"stock": {
		"available": 39
	}
}
```

Please remember that EAN/product ID should be provided in the product.id section. In the example above I've used a specific product.id instead of EAN, because more than one product matches EAN from your request.

**Comment by ymyuceturk** [comment]
_**" In the example above I've used a specific product.id instead of EAN, because more than one product matches EAN from your request"**_ 
Is there a way to send products in this condition?

**Comment by PrzemyslawLukanowski** [comment]
Can you elaborate on that? You can check the products IDs using GET /sale/products?ean={EAN}.
