### ISSUE TITLE
Allegro API: Could not resolve host: api.allegro.pl REST_API: 4096

### ISSUE THREAD

**Issue by stronydesire** [allegro/allegro-api#4589]
Witam serdecznie, mam sklep na postawiony na PRESTASHOP oraz zainstalowany moduł do Allegro REST API zakupiony na licencji. W Panelu Administracyjnym Sklepu, podczas: wystawiania aukcji lub powiązania produktów z Allegro lub nawet zmiany statusów listowania aukcji w Panelu Sklepu (aktywne/zakończone/) otrzymujemy taki komunikat:

Allegro API: Could not resolve host: api.allegro.pl REST_API: 4096

Wystarczy że 3,4,5, razy np zmienie status aukcji z POKAŻ AKTYWNE na POKAŻ ZAKOŃCZONE i wyrzuca ten błąd. Tak jakby ilość  możliwych połączeń była przekraczana. Tak się dzieje od 2 tygodni. 

Wcześniej wszystko działało pięknie - wystawiono i powiązano w ten sposób ponad 2100 produktów na linii SKLEP PRESTASHOP - ALLEGRO.  

Dziękuje za wszelkie wskazówki.

**Comment by PrzemyslawLukanowski** [comment]
Poruszaliśmy wcześniej ten temat w wątku #4245 - nie jest on związany z działaniem naszego API, ale prawdopodobnie z problemami sieciowymi po Twojej stronie, np. z DNS. Możesz spróbować zgłosić ten problem także autorom aplikacji, z której korzystasz.
