### ISSUE TITLE
Uzupełnienie danych w ofercie

### ISSUE THREAD

**Issue by pauldudyk** [allegro/allegro-api#459]
Zasobem PUT na https://api.allegro.pl.allegrosandbox.pl/sale/offers/{offerId} wysyłam tego jsona:
{
	"id": "$offerId",
	"name": "new offer",
	"category": {
		"id": "251842"
	},
	"parameters": "[{\"id\":4887,\"valuesIds\":[],\"values\":null,\"rangeValue\":null},{\"id\":4906,\"valuesIds\":[\"4906_8\",\"4906_128\"],\"values\":null,\"rangeValue\":null},{\"id\":11323,\"valuesIds\":[],\"values\":[\"11323_1\"],\"rangeValue\":null},{\"id\":17448,\"valuesIds\":[],\"values\":[\"555\"],\"rangeValue\":null},{\"id\":127768,\"valuesIds\":[],\"values\":[\"127768_2\"],\"rangeValue\":null},{\"id\":127788,\"valuesIds\":[],\"values\":[\"127788_2\"],\"rangeValue\":null},{\"id\":127789,\"valuesIds\":[\"127789_1\"],\"values\":null,\"rangeValue\":null},{\"id\":128394,\"valuesIds\":[],\"values\":[\"128394_1\"],\"rangeValue\":null},{\"id\":129389,\"valuesIds\":[],\"values\":[\"129389_2\"],\"rangeValue\":null},{\"id\":129390,\"valuesIds\":[\"129390_2\"],\"values\":null,\"rangeValue\":null},{\"id\":129391,\"valuesIds\":[\"129391_1\"],\"values\":null,\"rangeValue\":null},{\"id\":210918,\"valuesIds\":[],\"values\":[\"210918_245618\"],\"rangeValue\":null}]",
	"ean": null,
	"description": {
		"sections": "[{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>{auction_title} 234234234<\\\/p>\"}]},{\"items\":[{\"type\":\"IMAGE\",\"url\":\"https:\\\/\\\/b.allegroimg.allegrosandbox.pl\\\/original\\\/11b5f8\\\/f4df43074253bc58e7d7e6a5b94b\"},{\"type\":\"TEXT\",\"content\":\"<p>{product_weight}<\\\/p>\"}]},{\"items\":[{\"type\":\"TEXT\",\"content\":\"<p>{product_features}<\\\/p>\"},{\"type\":\"IMAGE\",\"url\":\"https:\\\/\\\/8.allegroimg.allegrosandbox.pl\\\/original\\\/11f3b8\\\/6ed44cb340398736c0568ffb3ce8\"}]}]"
	},
	"images": "[{\"url\":\"https:\\\/\\\/b.allegroimg.allegrosandbox.pl\\\/original\\\/11b5f8\\\/f4df43074253bc58e7d7e6a5b94b\"},{\"url\":\"https:\\\/\\\/8.allegroimg.allegrosandbox.pl\\\/original\\\/11f3b8\\\/6ed44cb340398736c0568ffb3ce8\"}]",
	"sellingMode": "{\"format\":\"BUY_NOW\",\"price\":{\"amount\":\"5190.60\",\"currency\":\"PLN\"},\"startingPrice\":null,\"minimalPrice\":null}",
	"stock": "{\"available\":\"55\",\"unit\":\"SET\"}",
	"publication": "{\"duration\":\"P10D\"}",
	"delivery": {
		"shippingRates": {
			"id": "[\"773167b1-feec-4ae9-b20f-1ed8ccb7b1ed\"]"
		}
	},
	"payments": "{\"invoice\":\"VAT\"}",
	"afterSalesServices": "{\"impliedWarranty\":{\"id\":\"426588c4-7e60-4443-ab5c-cdeebcc39860\"},\"returnPolicy\":{\"id\":\"98f5644e-f9aa-43c8-95a8-f209e31ecefb\"},\"warranty\":{\"id\":\"f7467c98-affb-4ab1-bf34-8328dd9b4d4c\"}}",
	"additionalServices": null,
	"sizeTable": null,
	"promotion": null,
	"location": "{\"countryCode\":\"PL\",\"province\":\"PODKARPACKIE\",\"city\":\"Rzesz\u00f3w\",\"postCode\":\"35-555\"}",
	"external": null,
	"contact": null,
	"validation": {
		"errors": [],
		"validatedAt": "2018-07-31T10:47:00.792Z"
	},
	"createdAt": "2018-07-31T10:53:33Z",
	"updatedAt": "2018-07-31T10:53:33.666Z"
}

w headers:
Accept: application/vnd.allegro.public.v1+json (beta też)
Content-Type: application/vnd.allegro.public.v1+json (beta też)
Token jest ważny
ale zawsze otrzymuję błąd - NotAcceptableException
dla czego?

**Comment by LukaszKorek** [comment]
Proszę wystawić ofertę przez graficzną wersję Serwisu i następnię proponuję ją pobrać metodą https://developer.allegro.pl/documentation/#!/offer/getOfferUsingGET  i na jej podstawie proponuję wystawić nową ofertę. Więcej informacji znajduje się w naszym poradniku https://developer.allegro.pl/sale/#similar-offer

**Comment by pauldudyk** [comment]
dla wystawienia oferty muszę mieć zweryfikowane konto (używam sandboxa)
teraz pisze "Weryfikacja Twoich danych może potrwać do 3 dni"
ale mam tą wiadomość od kiedy zacząłem testować (na pewno więcej jak tydzień)
czy w ogóle odbywa się weryfikacja konta dla sandboxa?

**Comment by LukaszKorek** [comment]
@pauldudyk podaj proszę login konta.

**Comment by pauldudyk** [comment]
@LukaszKorek p.dudyk@moonbite.pl

**Comment by LukaszKorek** [comment]
Konto aktywowaliśmy, spróbuj ponownie.
