### ISSUE TITLE
Wystawianie / edycja ofert - VAT

### ISSUE THREAD

**Issue by pietrach** [allegro/allegro-api#4590]
1. Czy ja muszę wszystkie te atrybuty dla obiektu "tax" (id, rate, subject, exemption) wypełniać podczas wystawienia oferty ?

"tax": {
    "id": "ae727432-8b72-4bfe-b732-6f163a2bf32a",
    "rate": "23.00",
    "subject": "GOODS",
    "exemption": "MONEY_EQUIVALENT",
},

2. A jak mam komunikat "Stawka VAT ZW nie jest dostępna w kategorii 25958" to znaczy, że w ogóle nie uzupełniam obiektu "tax" dla takiej oferty ? A czemu tak się dzieje ? Każdy produkt ma jakiś VAT.

3. I jakie są typy tych Vatów i co oznaczają ?. Jednym z nich widzę jest OUT_OF_SCOPE_OF_VAT

4. I jakie wartości może przyjmować pole exemption i co one oznaczają. Jednym z nich widzę jest MONEY_EQUIVALENT

**Comment by MaciejFrackowiak** [comment]
Możesz przekazać dwojako - albo tax.id albo uzupełnić łącznie tax.rate, tax.subject, tax.exemption, na podstawie których dopasujemy odpowiednie ustawienie tax.id - opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/sale/#ustawienia-vat).
Odpytując GET /sale/tax-settings dla danej kategorii otrzymasz listę dostępnych wszystkich przypadków exemption w danej kategorii.
To Ty jako sprzedawca deklarujesz jaką stawkę VAT przypisać do oferty - my natomiast zwracamy dostępne stawki dla danej oferty na podstawie stworzonej listy - szczegółowo opisane jest to w [komunikacie dla sprzedających.](https://allegro.pl/dla-sprzedajacych/od-19-maja-zobaczysz-nowe-pola-w-formularzu-wystawiania-sprawdz-stawki-vat-w-swoich-ofertach-Bv7MxMqwafj).
W [zapowiedzi zmiany](https://github.com/allegro/allegro-api/issues/4448), a dokładnie opisanym przykładzie znajdziesz obecnie dostępne wartości VAT: 23.00, 8.00, 5.00, EXEMPT, OUT_OF_SCOPE_OF_VAT.

**Comment by pietrach** [comment]
Proszę o info co jest przyczyną tego błędu => trace ID 14cb8a3a43955c7:

`[{"code":"VALIDATION_ERROR","message":"Stawka VAT ZW nie jest  dostępna w kategorii  25960.","details":"","path":"","userMessage":"Stawka VAT ZW nie jest  dostępna w kategorii 25960."}]`

Dodam, że wysyłam rate = 8.00, subject = GOODS, exemption = MONEY_EQUIVALENT

**Comment by MaciejFrackowiak** [comment]
W logach znalazłem wpis, w którym widnieje: 

"tax":{"percentage":"0.00","id":"de586ec7-2a4b-4f24-ba70-4cd4c18b6b59"} 

W danej kategorii nie widzę takiej stawki VAT, ani takiej polityki VAT.

**Comment by pietrach** [comment]
@MaciejFrackowiak dzięki. Chyba już wiem gdzie był problem.
