### ISSUE TITLE
VerificationRequired

### ISSUE THREAD

**Issue by wussup** [allegro/allegro-api#4591]
Witam,

od kilku dni zacząłem otrzymywać taką odpowiedź na żądanie do Państwa API:

> 403 Forbidden: [{"errors":[{"code":"VerificationRequired","message":"Access is denied. Verification is required.","details":null,"path":null,"userMessage":"Access denied. Access available only for verified applications."}]}]

Wcześniej wszystko sprawnie działało, konto na Allegro mam zweryfikowane. O co tu może chodzić?

**Comment by wussup** [comment]
Już wiem ocb:

> Od 1 czerwca 2021 tylko zweryfikowane aplikacje będą miały dostęp do tych danych. Podstawowe kryteria to udział w Programie VIP lub co najmniej 100 Użytkowników Allegro dla aplikacji. Aby przejść proces weryfikacji skontaktuj się z nami przez formularz lub ze swoim opiekunem, jeśli jesteś w Programie Partnerskim dla Sprzedających.

**Comment by elvisef** [comment]
Jeśli jest się sprzedającym, osobą prywatną, nie można korzystaćz API ?
Jak zweryfikować aplikację ?
Jak sprawdzić datę dodania danej aplikacji ?

**Comment by PrzemyslawLukanowski** [comment]
@elvisef Możesz w takim przypadku korzystać z API. Proces weryfikacji aplikacji przejdziesz, kontaktując się przez [formularz ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)- sprawa trafi do odpowiedniego zespołu, który zajmie się zgłoszeniem. Nie zwracamy informacji o tym, kiedy dana aplikacja została dodana.

**Comment by elvisef** [comment]
> @elvisef Możesz w takim przypadku korzystać z API. Proces weryfikacji aplikacji przejdziesz, kontaktując się przez [formularz ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)- sprawa trafi do odpowiedniego zespołu, który zajmie się zgłoszeniem. Nie zwracamy informacji o tym, kiedy dana aplikacja została dodana.

Ile trwa oczekiwanie na aktywację ? Chciałbym rozpocząć pracę nad aplikacją.
Pytam o daty, ponieważ nie wiem jak się odnieść do informacji na zrzucie:

![2021-08-04_11-30](https://user-images.githubusercontent.com/25976749/128157991-ed3ef342-732c-48f7-993e-917c2201caa8.png)

**Comment by PrzemyslawLukanowski** [comment]
Tak jak wspominamy w innych wątkach - weryfikacja aplikacji odbywa się poza naszym zespołem, dlatego nie możemy wskazać konkretnego terminu, kiedy otrzymasz odpowiedź. 
Co do daty dodania aplikacji, możesz skontaktować się z nami również przez [formularz ](https://allegro.pl/help/contact?category=3c9b1cc3-538f-4a6c-87ec-78c9b32e9b44&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c)- w treści dodaj informację o clientID oraz numer wątku, którego dotyczy zgłoszenie - #4591. Data dodania aplikacji jednak nie będzie istotna - jeśli dla GET /offers/listing otrzymujesz kod 403, to oznacza, że aplikacja nie jest na tę chwilę zweryfikowana i musi przejść przez ten proces. Aplikacje zarejestrowane do wskazanej przez Ciebie daty miały czas na weryfikację do 1.06.21, ponieważ od tego momentu endpoint udostępniliśmy tylko zweryfikowanym aplikacjom.
