### ISSUE TITLE
Częstotliwość odświeżania danych

### ISSUE THREAD

**Issue by OceanFireSoftware** [allegro/allegro-api#4592]
Dzień dobry,

Jak często odświeżane są dane dotyczące liczby obserwujących oraz statystyk wizyt naszych ofert?
Czy w przypadku liczby wizyt brane jest pod uwagę unikalne IP / wszystkie odsłony / odsłony z zalogowanych kont? Jak to jest liczone?

**Comment by PrzemyslawLukanowski** [comment]
Liczbę obserwujących aktulizujemy na bieżąco, natomiast liczbę odwiedzających odświeżamy co ok. 2 godziny. W przypadku liczby wizyt bierzemy pod uwagę unikalne IP.
