### ISSUE TITLE
Błąd "Invalid delivery or location part" przy wystawianiu aukcji poprzez POST /sale/offers

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4593]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

nie mogę wystawić części aukcji z powodu błędu "Invalid delivery or location part". Błąd mi nic nie mówi, ponieważ na tych samych danych inne aukcje się wystawiają. Prosiłbym o sprawdzenie.

Przykładowe trace-id:
Trace-Id: 4e063e0c96492a81
Trace-Id: df4c466082060020
Trace-Id: 7f0f82b1228d306e

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem podane przez Ciebie wywołania - w żadnym z nich nie przekazałeś wypełnionego obiektu "delivery", w którym niezbędne jest m.in. podanie konkretnego "shipping.rates". Przeglądając szkic na stronie WWW również ujrzysz informacje o braku przypisanego cennika dostawy.

**Comment by hahyes** [comment]
> Sprawdziłem podane przez Ciebie wywołania - w żadnym z nich nie przekazałeś wypełnionego obiektu "delivery", w którym niezbędne jest m.in. podanie konkretnego "shipping.rates". Przeglądając szkic na stronie WWW również ujrzysz informacje o braku przypisanego cennika dostawy.

Zapisałem treść zapytań tworzących szkic przez ich wysłaniem, w każdym z nich jest wypełniony obiekt `delivery` w sposób pokazany poniżej. Taki obiekt jest w szkicu wysyłany.

```
	"delivery": {
		"shippingRates": {
			"id": "f84cc058-7aef-4ddd-90d1-0bb2faf1c6c7"
		},
		"handlingTime": "PT0S"
	}
```

**Comment by MaciejFrackowiak** [comment]
Dziękuję za dodatkowe informacje - rzeczywiście, losowo pojawiał się problem z działaniem usługi odpowiedzialnej za prawidłowe rozpoznawanie cenników dostawy. Obecnie funkcjonalność wróciła do prawidłowego działania. Przepraszam za niedogodności.
