### ISSUE TITLE
Różnice w odpowiedzi dla /sale/offers oraz /offers/listing

### ISSUE THREAD

**Issue by MichalGrzybowski** [allegro/allegro-api#4598]
Dzień dobry,

podczas testu zasobów napotkałem na problem. Wykonując requesty jak poniżej, zasób GET /sale/offers zwraca mi informację, że mam 26 aktywnych ofert natomiast zasób GET /offers/listing informuje mnie, że jest to 0 ofert. 

1. Z czego wynika taka różnica ?
2. Jak skonstruować zapytanie do GET /sale/offers aby otrzymane wyniki były jak najbardziej zbliżone do tych otrzymywanych w GET /offers/listing

`
REQUEST:

GET /offers/listing?offset=0&limit=1&seller.id=43953514&sort=%2BendTime&searchMode=REGULAR HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.8.15
Authorization: Bearer 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

RESPONSE:

HTTP/1.1 200 OK
Trace-id: 7083bfc228f29568
Content-type: application/vnd.allegro.public.v1+json
Content-length: 4236
Date: Wed, 09 Jun 2021 12:00:53 GMT
Connection: close

{"items":{"promoted":[],"regular":[]},"searchMeta":{"availableCount":0,"totalCount":0,"fallback":false},"categories":{"subcategories":[],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[{"id":"sellingMode.format","type":"MULTI","name":"Rodzaj oferty","values":[{"value":"BUY_NOW","name":"kup teraz","count":0,"selected":false},{"value":"AUCTION","name":"licytacje","count":0,"selected":false},{"value":"ADVERTISEMENT","name":"ogłoszenia","count":0,"selected":false}]},{"id":"price","type":"NUMERIC","name":"Cena","values":[{"idSuffix":".from","name":"od","selected":false},{"idSuffix":".to","name":"do","selected":false}],"minValue":0,"maxValue":1000000000,"unit":"zł"},{"id":"deliveryMethod","type":"MULTI","name":"Sposoby dostawy","values":[{"value":"5b445fa0580ce26bb2f99602","name":"Kurier","count":0,"selected":false},{"value":"5b445fe6580ce26bb2f9960a","name":"Paczkomaty InPost","count":0,"selected":false},{"value":"5b44606c580ce26bb2f99617","name":"Dostawa za granicę","count":0,"selected":false},{"value":"5b446004580ce26bb2f9960c","name":"Odbiór w punkcie","count":0,"selected":false},{"value":"5b446013580ce26bb2f9960e","name":"List","count":0,"selected":false},{"value":"5b446031580ce26bb2f99610","name":"Paczka","count":0,"selected":false},{"value":"5b446044580ce26bb2f99612","name":"Odbiór osobisty","count":0,"selected":false},{"value":"5b44605c580ce26bb2f99614","name":"Przesyłka elektroniczna","count":0,"selected":false}]},{"id":"location.city","type":"TEXT","name":"Miejscowość","values":[{"name":"Miejscowość","selected":false}]},{"id":"location.province","type":"SINGLE","name":"Województwo","values":[{"value":"DOLNOSLASKIE","name":"z dolnośląskiego","selected":false},{"value":"KUJAWSKO_POMORSKIE","name":"z kujawsko-pomorskiego","selected":false},{"value":"LUBELSKIE","name":"z lubelskiego","selected":false},{"value":"LUBUSKIE","name":"z lubuskiego","selected":false},{"value":"LODZKIE","name":"z łódzkiego","selected":false},{"value":"MALOPOLSKIE","name":"z małopolskiego","selected":false},{"value":"MAZOWIECKIE","name":"z mazowieckiego","selected":false},{"value":"OPOLSKIE","name":"z opolskiego","selected":false},{"value":"PODKARPACKIE","name":"z podkarpackiego","selected":false},{"value":"PODLASKIE","name":"z podlaskiego","selected":false},{"value":"POMORSKIE","name":"z pomorskiego","selected":false},{"value":"SLASKIE","name":"ze śląskiego","selected":false},{"value":"SWIETOKRZYSKIE","name":"ze świętokrzyskiego","selected":false},{"value":"WARMINSKO_MAZURSKIE","name":"z warmińsko-mazurskiego","selected":false},{"value":"WIELKOPOLSKIE","name":"z wielkopolskiego","selected":false},{"value":"ZACHODNIOPOMORSKIE","name":"z zachodniopomorskiego","selected":false}]},{"id":"option","type":"MULTI","name":"oferta ma","values":[{"value":"FREE_SHIPPING","name":"darmowa dostawa","selected":false},{"value":"FREE_RETURN","name":"darmowy zwrot","selected":false},{"value":"VAT_INVOICE","name":"faktura VAT","selected":false},{"value":"COINS","name":"Monety Allegro","selected":false},{"value":"BRAND_ZONE","name":"Strefa Marek","selected":false},{"value":"SUPERSELLER","name":"Super Sprzedawca","selected":false},{"value":"CHARITY","name":"Allegro Charytatywni","selected":false},{"value":"COUPONS","name":"Kupony Allegro","selected":false},{"value":"SMART","name":"Allegro Smart!","selected":false}]},{"id":"campaign","type":"MULTI","name":"kampania","values":[{"value":"INSTALLMENTS_ZERO","name":"raty zero","selected":false},{"value":"BARGAIN","name":"Strefa Okazji","selected":false},{"value":"BARGAIN_REBATE","name":"rabaty","selected":false}]}],"sort":[{"value":"-relevance","name":"trafność","order":"największa","selected":false},{"value":"+price","name":"cena","order":"od najniższej","selected":false},{"value":"-price","name":"cena","order":"od najwyższej","selected":false},{"value":"+withDeliveryPrice","name":"cena z dostawą","order":"od najniższej","selected":false},{"value":"-withDeliveryPrice","name":"cena z dostawą","order":"od najwyższej","selected":false},{"value":"+endTime","name":"czas do końca","order":"najmniej","selected":true},{"value":"-startTime","name":"czas dodania","order":"najnowsze","selected":false}]}

-------------------------------------

REQUEST:

GET /sale/offers?offset=0&limit=1&publication.status=ACTIVE HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.8.15
Authorization: Bearer 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL

RESPONSE:

HTTP/1.1 200 OK
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: b138d293e0111e89
Date: Wed, 09 Jun 2021 12:00:53 GMT
X-content-type-options: nosniff
Content-type: application/vnd.allegro.public.v1+json
Content-length: 813
Connection: close

{"offers":[{"id":"7680179222","name":"hgjhg","category":{"id":"257936"},"primaryImage":{"url":""},"sellingMode":{"format":"BUY_NOW","price":{"amount":"149.5","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"saleInfo":{"currentPrice":null,"biddersCount":0},"stats":{"watchersCount":0,"visitsCount":0},"stock":{"available":4,"sold":0},"publication":{"status":"ACTIVE","startingAt":null,"startedAt":"2021-04-12T07:11:00Z","endingAt":null,"endedAt":null},"afterSalesServices":{"warranty":null,"returnPolicy":{"id":"cd289ff7-d858-4ac3-b363-f7ad2921b0e4"},"impliedWarranty":{"id":"fa942068-9b96-4c0b-bd35-9fc55844db2c"}},"additionalServices":null,"external":{"id":"602ec86c-9fa1-45be-8e5b-3c213740cced"},"delivery":{"shippingRates":{"id":"c988ddad-7e7f-4047-8070-28d1df83b102"}}}],"count":1,"totalCount":26}
`

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Potwierdzam zauważone przez Ciebie nieprawidłowości w wynikach - zgłosiłem je do właściwego działu.

**Comment by MaciejFrackowiak** [comment]
Źródłem opisanego w wątku problemu jest retencja danych - w przypadku Sandbox i wyszukiwarki wynosi ona 14 dni. Oznacza to, że tylko w okresie 14 dni od aktywacji oferty dajemy gwarancję dostępności oferty na testowym listingu.
