### ISSUE TITLE
Wystawianie aukcji na Allegro

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4599]
Witam,
chciałam się dowiedzieć czy jest możliwość podłączenia pod api Allegro lokalnej bazy danych by móc wystawiać aukcje. By nie  wykonywać ich wystawiania za pośrednictwem Baselinker ?

Pozdrawiam

**Comment by kfijalko** [comment]
https://developer.allegro.pl/documentation/#operation/createProductOffers

**Comment by PrzemyslawLukanowski** [comment]
Jest to możliwe, jeśli odpowiednio zaprogramujesz swoją aplikację. Więcej o możliwościach naszego API przeczytasz na [naszym portalu](https://developer.allegro.pl/about/).

**Comment by Kasia13130** [comment]
Dziękuję za informacje.
