### ISSUE TITLE
Błędnie wyzerowane pole payTransPrice w doGetMyIncomingPayments

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#46]
W specyfikacji
https://allegro.pl/webapi/documentation.php/show/id,85#method-output
jest wyraźnie napisane:

> payTransPrice | float
> Wartość przedmiotów zakupionych przez użytkownika w ramach danej oferty (lub ofert - dla wpłat łącznych) i opłaconych w ramach danej transakcji Allegro Finanse (lub 0 w przypadku dopłaty).

Po odpytaniu tego endpointa, kiedy mam dwie wpłaty, z których jedna jest wpłatą główna (niedopłatą), a druga dopłatą do niej (można zauważyć po wypełninym polu payTransMainId), okazuje się, że wpłata główna ma wyzerowane pole payTransPrice. Zgodnie ze specyfikacją na Państwa stronie tylko dopłaty mają mieć wyzerowane to pole.

Jak duży jest ten problem? Nie jestem w stanie rozpoznać czy klient wpłacił pełną kwotę na podstawie wpłaty głównej i dopłat, a więc nie mogę wysłać mu towaru, ponieważ wpłata główna może być wpłatą łączną więc tylko po samej kwocie z danej aukcji nie mogę stwierdzić czy zapłacono całość.

Jestem prawie pewien, że jeszcze półtora roku temu dla wpłaty głównej będącej niedopłatą API zwracało kwotę, ponieważ mam mój stary kod źródłowy który na to wskazuje. Obecne działanie jest niezgodne ze specyfikacją.

ID zgłoszenia: Ticket#1245546344 (26.02.2018)

[soap.txt](https://github.com/allegro/allegro-api/files/1783969/soap.txt)

**Comment by MaciejPotepa** [comment]
Korespondowałeś z nami na temat tego zgłoszenia w zgłoszeniu 1245546344  oraz na FB.

Pracujemy nad jego rozwiązaniem. Damy Ci znać - tutaj, jak wyjaśnimy sprawę.

**Comment by amarel123** [comment]
Mam nadzieję, że w sensownym terminie ponieważ na początku kwietnia mamy deadline oddania projektu dla klienta, a bardzo ważny moduł nie może zostać uruchomiony właśnie z powodu tego buga. Pozdrawiam.

**Comment by amarel123** [comment]
@MaciejPotepa Podbijam temat, minęło kilka miesięcy od zgłoszenia buga.

**Comment by MaciejPotepa** [comment]
@amarel123 Niezmiernie przepraszam, że to tak długo trwa i nic się nie dzieje w temacie. 
Obecne zasoby WebAPI będą w przyszłości wygaszane i już ich nie rozwijamy. 

Wkrótce udostępnimy zasoby do obsługi zamówień w REST API na których będziesz mógł oprzeć swoją aplikację. 

Wiem, że to nie jest do końca to o co prosiłeś, ale to jedyne co mogę zaoferować w tej sytuacji. 

Jeżeli masz pytania bardzo chętnie na nie odpowiem.
