### ISSUE TITLE
Nie podano parametru wymaganego dla wybranej kategorii. ()

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#460]
Wygląda na to, że jakaś "mała" awaria, wszystkie fidy obowiązkowe przesłane, a mimo to taki error, a i normalnie w nawiasach przychodzi fid, którego brakuje. Przykładowe kategorie dla jakich poleciał ten error: 257903, 19919.

**Comment by LukaszKorek** [comment]
Podeślij proszę pełny request i response w formacie .xml za pomocą formularza https://allegro.pl/pomoc/kontakt Pozwoli to na pełną weryfikację zgłoszenia.

**Comment by anih** [comment]
Ticket#1249954648, łatwiej było złapać request/response z wystawiania aukcji poprzez doNewAuctionExt

**Comment by LukaszKorek** [comment]
Paremetr "materiał wkładki" jest obowiązkowy w tej kategorii. Pobierz najnowszego WSDLa i skorzystaj z metody doGetSellFormFieldsForCategory, którą pobierzesz najnowsze wymagane fidy.

**Comment by anih** [comment]
Tak jak napisałem, wczoraj parametr ten nie był wymagany pobierając dane z doGetSellFormFieldsForCategory i powodował błąd bez informacji jaki to był fid, dziś parametr ten stał się już wymagalny w danych z doGetSellFormFieldsForCategory oraz poprawnie doNewAuctionExt wali błędem z informacja jaki fid jest winny.

**Comment by anih** [comment]
I znowu API nie zwraca informacji jakiego parametru brakuje

**Comment by anih** [comment]
@LukaszKorek mógłbyś się odnieść do tego problemu, jest on dość uciążliwy. Kategorie w których to występuje: 55207, 10783, 87981

**Comment by LukaszKorek** [comment]
Podeślij proszę przykładowy request i response - format .xml za pomocą formularza https://allegro.pl/pomoc/kontakt
