### ISSUE TITLE
Problem z przetworzeniem request'u /sale/product-offers

### ISSUE THREAD

**Issue by grojanteam** [allegro/allegro-api#4600]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Problem z przetworzeniem request'u /sale/product-offers**

Request:
``{"id":null,"name":"Fugen Acryl fajnen dla wallen","category":{"id":"258264"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"288.00","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"delivery":{"shippingRates":{"id":"f5b9f517-0bee-45ff-b3d6-57ce08bc35b6"},"handlingTime":"PT0S","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"NO_INVOICE"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null}],"publication":{"republish":false,"duration":null,"status":"INACTIVE"},"stock":{"available":999,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Fugen Acryl Fajnen Dla Wallen Srocen<\/h1>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118814\/e0d282914109872f3daa31819fda"}]},{"items":[{"type":"TEXT","content":"<p>Fajnen fugen do wallen<\/p><p>Fajnen fugen do wallen<\/p>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118903\/033f77314c148fb9b026c8ba48a0"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/113ca6\/65aff1aa4926b89f699741480196"},{"type":"TEXT","content":"<p>Srocen wielken<\/p><p><\/p>\n<p><\/p>\n"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e8c0\/fd0242b04545ad33f900ddc50291"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e15a\/1c57d33e404fab73dd5f6e6c601d"}]}]},"external":{"id":225},"location":{"city":"******","countryCode":"PL","postCode":"**-***","province":"******"},"images":["https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118814\/e0d282914109872f3daa31819fda","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118903\/033f77314c148fb9b026c8ba48a0","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/113ca6\/65aff1aa4926b89f699741480196","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e8c0\/fd0242b04545ad33f900ddc50291","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e15a\/1c57d33e404fab73dd5f6e6c601d"],"afterSalesServices":{"impliedWarranty":{"id":"016e594e-56fa-4fce-b1c5-9b90d95fd7de"},"returnPolicy":{"id":"4d9fb601-8f48-4d01-9df3-376d08a8861b"},"warranty":{"id":"82df85db-0bb8-482e-90f5-51eb7d84a6bf"}},"additionalServices":null,"product":{"name":"Fugen Acryl fajnen dla wallen","category":{"id":"258264"},"images":["https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118814\/e0d282914109872f3daa31819fda","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/118903\/033f77314c148fb9b026c8ba48a0","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/113ca6\/65aff1aa4926b89f699741480196","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e8c0\/fd0242b04545ad33f900ddc50291","https:\/\/a.allegroimg.allegrosandbox.pl\/original\/11e15a\/1c57d33e404fab73dd5f6e6c601d"],"parameters":[{"id":"213802","valuesIds":["213802_840279"],"values":[],"rangeValue":null},{"id":"213866","valuesIds":["213866_264362"],"values":[],"rangeValue":null},{"id":"213962","valuesIds":["213962_367413"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["8908908908904"],"rangeValue":null}]},"updatedAt":"2021-06-09T17:39:43Z"} ``

Response:
HTTP/2 422 
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 1505f224e4762a83
date: Wed, 09 Jun 2021 17:39:46 GMT
x-content-type-options: nosniff
content-type: application/json
content-length: 350

``{"errors":[{"code":"UnableToCreateProductWithoutAllRequiredParametersException","message":"Unable to create product without proper values in all required parameters: [Producent]","details":null,"path":"product.parameters","userMessage":"Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Producent]"}]}``

**Comment by PrzemyslawLukanowski** [comment]
Na środowisku testowym nie ma takiej wartości dla parametru `"Producent"` jak `213802_840279`. Sandbox może się różnić względem produkcji w tej kwestii - staramy się aktualizować kategorie i parametry ok. raz na kwartał.

**Comment by grojanteam** [comment]
@PrzemyslawLukanowski 
Problem jest dokładnie ten sam na produkcji.

Jeśli trzeba prześlę request

**Comment by PrzemyslawLukanowski** [comment]
Tak, prześlij proszę, ponieważ przed chwilą spróbowałem powtórzyć ten błąd na produkcji, ale udało mi się prawidłowo utworzyć produkt w tej kategorii.

**Comment by grojanteam** [comment]
Ok, wyślę wieczorem 👌
