### ISSUE TITLE
219629:Original Manufacturer's Packaging

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4601]
Hi,
when i set 219629:Original Manufacturer's Packaging, the api returns error;
{trace-id=e073a7f9d258f59c}  "Given parameter id `219629:Original Manufacturer's Packaging` should no have been passed as `product` parameter.

when don't set, it returns error too, 
ConstraintViolationException.MissingRequiredParameters\",\"message\":\"Uzupełnij parametry obowiązkowe: Oryginalne opakowanie producenta.
{trace-id=e03aebbd3e5a5899}

we need your help

**Comment by PrzemyslawLukanowski** [comment]
Hi, `Original Manufacturer's Packaging` is not a product parameter, so you should pass it in the `parameters` section, but beyond the `product` object. You can check the type of parameters, whether it is an offer or product parameter, using GET /sale/categories/{categoryID}/parameters - we will return the information in the `options.describesProduct `field:

- true - product parameter, 
- false - offer parameter.

**Comment by ymyuceturk** [comment]
where do i set or how to i set the product parameters

{
            "product": {
                "name": "Buty sportowe Kinetix... ",
                "category": {
                    "id": "257903"
                },
                "parameters": [
  **are these offer parameters? **
                ],
             
        }

**Comment by PrzemyslawLukanowski** [comment]
for example:

```
{
	"product": {
		"id": "46c10332-5134-48ee-b15b-bb7996087264",
		"parameters": [{                      -- product parameters
			"id": 225693,
			"values": ["7322540823998"]
		}]
	},
	...
        "parameters": [{                              -- offer parameters
			"id": 225693,
			"values": ["7322540823998"]
		}]
}
```
