### ISSUE TITLE
Pobranie załącznika z dyskusji 

### ISSUE THREAD

**Issue by brokieb** [allegro/allegro-api#4602]
Witam, mam problem z pobraniem załącznika w PHP, jak to zrobić poprawnie żeby po kliknięciu w link pobrał się dany załącznik? 

`$ch = curl_init($event);`
 `   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);`
 `   curl_setopt($ch, CURLOPT_HTTPHEADER, [`
 `       "Authorization:bearer $token"`
 `   ]);`
 `   $mainResult = curl_exec($ch);`
 `   $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);`
 `   curl_close($ch);`
 `   header('Content-type: ' . 'application/octet-stream');`
 `   header('Content-Disposition: ' . 'attachment; filename=report');`
 `   return $mainResult;`

**Comment by hahyes** [comment]
Dziwaczne nagłówki tam masz. W dokumentacji żadnych się nie podaje poza tokenem.
https://developer.allegro.pl/redoc/redoc-static.html#operation/getAttachmentUsingGET

**Comment by MaciejFrackowiak** [comment]
W opisanej kwestii PHP możliwe, że któryś z użytkowników natrafił na podobny problem - ze swojej nie prowadzimy wsparcia w zakresie języków programowania. Dodam, iż zasób [GET /sale/dispute-attachments/{attachmentId}](https://developer.allegro.pl/documentation/#operation/uploadDisputeAttachmentUsingPUT) nie wymaga przekazywania żadnego nagłówka.

**Comment by damianszymanskiphp** [comment]
Wyjaśnione tutaj https://github.com/allegro/allegro-api/issues/4543#issuecomment-869153079

**Comment by MaciejFrackowiak** [comment]
@damianszymanskiphp Obecnie, zarówno w poradniku, jak i dokumentacji widnieje już ujednolicona wersja.
