### ISSUE TITLE
Błąd z wystawianiem produktu z Idosell do allegro

### ISSUE THREAD

**Issue by maaaacko** [allegro/allegro-api#4603]
W załączeniu zrzut błędu. Towary które się nie wystawiły niczym nie odbiegały od wystawionych.. Proszę o pomoc. Niestety nie mogę załączyć plików .hml

<img width="597" alt="Zrzut ekranu 2021-06-10 o 20 22 46" src="https://user-images.githubusercontent.com/85703628/121578843-67deef00-ca2b-11eb-8aca-265f2908cf63.png">

**Comment by PrzemyslawLukanowski** [comment]
Ten komunikat oznacza, że masz za mało ofert powiązanych z produktem, aby dalej wystawiać w danej kategorii. W zakładce [Moje oferty](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty?offerType=BUY_NOW&statuses=ACTIVE&page=1&pageSize=20) możesz sprawdzić, jaki procent Twoich ofert jest aktualniepowiązanych z produktem oraz, jaki jest bieżący wymóg.
