### ISSUE TITLE
Tagi oraz etykiety aukcji w danych zwracanych przez /sale/offers/{offer-id}

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#4604]
:bulb: **Sugestia**
Czy jest możliwość aby w/w metoda zwracała także listę **tagów** oraz **etykiet** danej oferty?
Teoretycznie wg dokumentacji ta metoda zwraca **WSZYSTKIE** pola danej oferty. Wg mnie tagi i etykiety oferty też są polami/atrybutami danej oferty.

**Comment by PrzemyslawLukanowski** [comment]
Zapoznaj się proszę z [naszym newsem](https://github.com/allegro/allegro-api/issues/4337). Zgodnie z nim przenoszę ten wątek do zakładki [Discussions](https://github.com/allegro/allegro-api/discussions), gdzie również inni użytkownicy będą mogli głosować na tę funkcjonalność, co pozwoli określić jej priorytet. Jeśli zdecydujemy się na wdrożenie propozycji - poinformujemy o statusie prac w wątku. Jednocześnie prosiłbym o informację, jakie dokładnie etykiety w API masz na myśli oraz uzasadnienie - jaka jest potrzeba dla tej zmiany.
