### ISSUE TITLE
Opłaty za utrzymanie

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4606]
Dzień dobry.
Chcę ustalić z góry, za które oferty będą pobierane opłaty za utrzymanie. Czy istnieje jakiś sposób, aby dowiedzieć się, kiedy była ostatnia sprzedaż lub po ilu dniach zacznie się naliczać opłata dla konkretnej oferty?

Wiem o metodzie GET / pricing/offer-quotes, ale chciałbym znaleźć takie oferty przed dokonaniem płatności.

**Comment by MaciejFrackowiak** [comment]
Nie zwracamy informacji, czy oferta miała sprzedaż w ciągu ostatniego roku. Korzystając natomiast z [GET /pricing/offer-quotes](https://developer.allegro.pl/documentation/#operation/offerQuotesPublicUsingGET) możesz sprawdzić przewidywane naliczenie opłat dla wskazanej oferty w ciągu najbliższego cyklu.
