### ISSUE TITLE
Niezgodność w offer-price-change-commands

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#4607]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id:
e1dcc3d1d89c2602 i b1874b6cbf35215f

Hej!
Zdarzyła mi się dzisiaj niezgodność między ogólną i szczegółową informacją o zmianach cen:
`sale/offer-price-change-commands/cd01fc2c-0a6d-462f-8496-fd08aa07f6be`
oraz
`sale/offer-price-change-commands/cd01fc2c-0a6d-462f-8496-fd08aa07f6be/tasks`

Endpoint ogólny zwaraca:
`{
    "id": "cd01fc2c-0a6d-462f-8496-fd08aa07f6be",
    "taskCount": {
        "total": 4,
        "success": 3,
        "failed": 0
    }
}`
(3 zakończone sukcesem)
Endpoint szczegółowy (`/tasks`) zwraca natomiast informacje, że wszystkie 4 zakończyły się sukcesem.

Podany wyżej przykład to jeden z wielu. Sprawdzone po prawie dwóch godzinach od wysłania zmiany cen.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie - zauważoną rozbieżność skierowałem do weryfikacji, wrócę z odpowiedzią.

**Comment by jakubmaguza** [comment]
@MaciejFrackowiak 
27 dni to chyba dużo na sprawdzenie problemu. Coś wiadomo?

**Comment by MaciejFrackowiak** [comment]
Pamiętam o Tobie - niestety, nie uzyskałem jeszcze odpowiedzi. Przypomnę się.

**Comment by jakubmaguza** [comment]
Przypominam się ponownie. Sytuacja pojawia się od czasu do czasu.

**Comment by Lukasz-Zurek** [comment]
@jakubmaguza Przepraszam za długi czas oczekiwania na rozwiązanie tego problemu. Mogę jednak zapewnić, że w najbliższym czasie planujemy wdrożenie poprawki.
