### ISSUE TITLE
sale/offers zwraca offers 0

### ISSUE THREAD

**Issue by KostuTM** [allegro/allegro-api#4609]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Cześć
Autoryzuję się nastęująco:
```
            RestClient client = new RestClient(@"https://api.allegro.pl");
            RestRequest request = new RestRequest("sale/offers", Method.GET);
            request.AddHeader("Authorization", "Bearer " +token);
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
           var response = client.Execute(request);
            var oferty = response.Content;
```
Niestety w zwrotce dostaję: {"offers":[],"count":0,"totalCount":0}
Konto naktórym działam na wystawione kilkanacie ofert. Jest ktoś w stanie mi cos zaradzić....

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przykładowy request i response (+ login sprzedawcy) w formacie curl przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz, że dane dotyczą wątku #4609 na GitHubie.

**Comment by KostuTM** [comment]
Wysłane...
