### ISSUE TITLE
Offer external identifier may not be blank

### ISSUE THREAD

**Issue by maciek257** [allegro/allegro-api#4610]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W ofertach Allegro istnieje możliwość dodania **opcjonalnej** sygnatury. 
W API odpowiada za to pole external->id.
W przypadku projektu, który tworzę zdarza się, że konieczne jest usunięcie/wyczyszczenie tego parametru.

Niestety mimo, że tak ja podkreśliłem powyżej to pole jest opcjonalne to API w momencie przesyłania pustego string'a bądź NULL zwraca błąd "Offer external identifier may not be blank".

W mojej ocenie jest to błąd skoro w zwykłym edytorze na Allegro można edytować ofertę i zapisać ją z pustym polem sygnatury. 

Będę wdzięczny za pomoc w tej kwestii.

**Comment by Lukasz-Zurek** [comment]
Możesz usunąć **external.id** z oferty, wszystko jednak wskazuje na to, że robisz to źle, wysyłając **null** w niewłaściwym miejscu:

```
...
    "external": {
        "id": null
   },
...
```
Wskazany błąd zwracamy zatem w sposób prawidłowy, ponieważ w polu "id" nie przyjmujemy **null.**

Powinieneś przekazać **null** w poniższy sposób:

`"external": null`

W tej sytuacji usuniesz ten parametr z oferty.

**Comment by maciek257** [comment]
Bardzo dziękuję za podpowiedź. Faktycznie źle przekazywałem null, mój błąd.
