### ISSUE TITLE
Błąd parcel-management/parcel-create-commands

### ISSUE THREAD

**Issue by BappressWW** [allegro/allegro-api#4611]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać więcej szczegółów - przykładowe commandID oraz treść komunikatu błędu? Według naszych logów zasób działa prawidłowo.

**Comment by BappressWW** [comment]
Co mogę podać więcej aby to uściślić.
Wysyłam takiego jsona:
{
  "serviceId": 9842970,
  "receiver": {
    "address": {
      "street": "Katowicka, 33/112 ",
      "postCode": "61-131",
      "city": "Poznań",
      "countryCode": "PL",
      "county": null
    },
    "email": "tdiar1d8nn+b4f6a477@allegromail.pl",
    "name": "Skinlab33 Skinlab Skinlab",
    "company": null,
    "phone": "727723333",
    "pointId": null
  },
  "pickup": {
    "address": {
      "street": "Katowicka, 33/112 ",
      "postCode": "61-131",
      "city": "Poznań",
      "countryCode": null,
      "county": null
    },
    "email": "tdiar1d8nn+b4f6a477@allegromail.pl",
    "name": "Skinlab33 Skinlab Skinlab",
    "company": null,
    "phone": "727723333",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 10,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 20,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 10,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "1",
        "unit": "KILOGRAM"
      },
      "description": "ZS-1260/ALL/6/21; 293793250; 008452/2106/SPL",
      "value": {
        "amount": "99.9800",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": {
      "address": {
        "street": "ul. Poznańska 165",
        "postCode": "62-052",
        "city": "Komorniki",
        "countryCode": "PL",
        "county": null
      },
      "email": "zamowienia@nesperta.com",
      "name": "Nesperta Sp. z o.o.",
      "company": "Nesperta Sp. z o.o.",
      "phone": "587622020"
    },
    "fileFormat": "ZPL",
    "referenceNumber": "ZS-1260/ALL/6/21"
  },
  "additionalServices": {
    "cashOnDelivery": {
      "value": null,
      "accountNumber": "12345678901234567890123456",
      "name": "Nesperta Sp. z o.o.",
      "express": false
    },
    "options": [
      "returnOfDocuments",
      "additionalHandling",
      "privateShipping",
      "sendingAtPoint",
      "upsSaver"
    ]
  }
}
na adres: https://api.allegro.pl/parcel-management/parcel-create-commands/994ef4a8-5663-4be9-baf8-13e85e20d8cd
i przy prubie zarejestrowania paczki dostaję komunikat:
{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error","details":null,"path":"/parcel-management/parcel-create-commands/994ef4a8-5663-4be9-baf8-13e85e20d8cd","userMessage":"Nieprawidłowa treść żądania JSON"}]}

Robię to aplikacji pisane w C#

**Comment by PrzemyslawLukanowski** [comment]
Poniżej przesyłam listę błędów, jaką zwracamy dla tego żądania:
```
 "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "liczba spoza przedziału (oczekiwano <10 cyfr>.<2 cyfr>)",
            "details": "Invalid value: 99.9800",
            "path": "items[0].value.amount",
            "userMessage": "liczba spoza przedziału (oczekiwano <10 cyfr>.<2 cyfr>)"
        },
        {
            "code": "VALIDATION_ERROR",
            "message": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\"",
            "details": "Invalid value: Nesperta Sp. z o.o.",
            "path": "label.sender.name",
            "userMessage": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\""
        },
        {
            "code": "VALIDATION_ERROR",
            "message": "musi pasować do wzorca \"[A-Za-z0-9-_]+\"",
            "details": "Invalid value: ZS-1260/ALL/6/21",
            "path": "label.referenceNumber",
            "userMessage": "musi pasować do wzorca \"[A-Za-z0-9-_]+\""
        },
        {
            "code": "VALIDATION_ERROR",
            "message": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\"",
            "details": "Invalid value: Skinlab33 Skinlab Skinlab",
            "path": "pickup.name",
            "userMessage": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\""
        },
        {
            "code": "VALIDATION_ERROR",
            "message": "musi być podane",
            "details": "Invalid value: null",
            "path": "additionalServices.cashOnDelivery.value",
            "userMessage": "musi być podane"
        },
        {
            "code": "VALIDATION_ERROR",
            "message": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\"",
            "details": "Invalid value: Skinlab33 Skinlab Skinlab",
            "path": "receiver.name",
            "userMessage": "musi pasować do wzorca \"[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ -]*\""
        }
    ]
```

**Comment by BappressWW** [comment]
Szkoda, że w odpowiedzi tego nie dostaję.
Ale sprawdzę jak to wygląda. po mojej stronie

**Comment by BappressWW** [comment]
Poprawiłem
{
  "serviceId": 9842970,
  "receiver": {
    "address": {
      "street": "Katowicka, 33/112 ",
      "postCode": "61-131",
      "city": "Poznań",
      "countryCode": "PL",
      "county": null
    },
    "email": "tdiar1d8nn+b4f6a477@allegromail.pl",
    "name": "Skinlab Skinlab Skinlab",
    "company": null,
    "phone": "727723333",
    "pointId": null
  },
  "pickup": {
    "address": {
      "street": "Katowicka, 33/112 ",
      "postCode": "61-131",
      "city": "Poznań",
      "countryCode": null,
      "county": null
    },
    "email": "tdiar1d8nn+b4f6a477@allegromail.pl",
    "name": "Skinlab Skinlab Skinlab",
    "company": null,
    "phone": "727723333",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 10,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 20,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 10,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "1",
        "unit": "KILOGRAM"
      },
      "description": "ZS-1260/ALL/6/21; 293793250; 008452/2106/SPL",
      "value": {
        "amount": "99.98",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": {
      "address": {
        "street": "ul. Poznańska 165",
        "postCode": "62-052",
        "city": "Komorniki",
        "countryCode": "PL",
        "county": null
      },
      "email": "zamowienia@nesperta.com",
      "name": "NESPERTA",
      "company": "NESPERTA",
      "phone": "587622020"
    },
    "fileFormat": "ZPL",
    "referenceNumber": "ZS-1260_ALL_6_21"
  },
  "additionalServices": {
    "cashOnDelivery": {
      "value": {
        "amount": "0",
        "currency": "PLN"
      },
      "accountNumber": "42175010190000000036587393",
      "name": "NESPERTA",
      "express": false
    },
    "options": [
      "returnOfDocuments",
      "additionalHandling",
      "privateShipping",
      "sendingAtPoint",
      "upsSaver"
    ]
  }
}
 i nadal to samo
Dostaje komunikat :
{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error","details":null,"path":"/parcel-management/parcel-create-commands/3fbe1de9-f4ad-452c-8fc0-6f60830a8b2d","userMessage":"Nieprawidłowa treść żądania JSON"}]}

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy tę strukturę i jest ona prawidłowa - udało nam się na jej podstawie utworzyć paczkę, nie zwracmy żadnych błędów. Być może problemem jest kwestia formatowania po Twojej stronie, jednak nie możemy tego zweryfikować. Poprawność struktury możesz potwierdzić, przesyłając ją wraz z całym poleceniem cURL z poziomu konsoli.

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie świadczymy wsparcia dla innych języków programowania. Być może któryś z użytkowników forum miał podobny problem w przeszłości i będzie w stanie pomóc w rozwiązaniu.

**Comment by BappressWW** [comment]
Dobrze dziś spróbuję na innym zamówieniu, bo tamto musiało być już wysłane.

**Comment by BappressWW** [comment]
Wracam z tematem wysyłam:
{
  "serviceId": 9842970,
  "receiver": {
    "address": {
      "street": "Obornicka 7 ",
      "postCode": "62-002",
      "city": "Jelonek",
      "countryCode": "PL",
      "county": null
    },
    "email": "qu8ivfcg9q+2337c9e83@allegromail.pl",
    "name": "Aleksandra Kmieciak",
    "company": null,
    "phone": "790400852",
    "pointId": null
  },
  "pickup": {
    "address": {
      "street": "Obornicka 7 ",
      "postCode": "62-002",
      "city": "Jelonek",
      "countryCode": null,
      "county": null
    },
    "email": "qu8ivfcg9q+2337c9e83@allegromail.pl",
    "name": "Aleksandra Kmieciak",
    "company": null,
    "phone": "790400852",
    "pointId": null
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 10,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 20,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 10,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "1",
        "unit": "KILOGRAM"
      },
      "description": "ZS-1575/ALL/6/21; 294828717; 011215/2106/SPL",
      "value": {
        "amount": "104.97",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": {
      "address": {
        "street": "ul. Poznańska 165",
        "postCode": "62-052",
        "city": "Komorniki",
        "countryCode": "PL",
        "county": null
      },
      "email": "zamowienia@nesperta.com",
      "name": "NESPERTA",
      "company": "NESPERTA",
      "phone": "587622020"
    },
    "fileFormat": "ZPL",
    "referenceNumber": "ZS-1575_ALL_6_21"
  },
  "additionalServices": {
    "cashOnDelivery": {
      "value": {
        "amount": "0",
        "currency": "PLN"
      },
      "accountNumber": "42175010190000000036587393",
      "name": "NESPERTA",
      "express": false
    },
    "options": [
      "returnOfDocuments",
      "additionalHandling",
      "privateShipping",
      "sendingAtPoint",
      "upsSaver"
    ]
  }
}
dostaję:

{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error","details":null,"path":"/parcel-management/parcel-create-commands/8602c531-5f76-4d83-83c3-ab05899c8cbf","userMessage":"Nieprawidłowa treść żądania JSON"}]}

Dlaczego dostaję błąd "JSON parse error" zrobiłem wszystkie pola wg waszego wzorca, który dostałem ostatnio na tym poście.

**Comment by PrzemyslawLukanowski** [comment]
Pamiętaj proszę, aby zamazywać dane osobowe z przykładowych plików JSON. Struktura jest prawidłową, bez problemu udaje mi się na jej podstawie utworzyć paczkę. Spróbuj stworzyć tę paczkę np. w Postmanie. Prócz tego możesz także wymusić kodowanie utf-8. W tej sytuacji trudno nam wskazać przyczynę błędu po Twojej stronie - sama struktura JSON jest na pewno poprawna.

**Comment by BappressWW** [comment]
To czemu komunikat dostaję, że nie?

**Comment by PrzemyslawLukanowski** [comment]
Nie wiemy, jakie dokładnie operacje są wykonywane po Twojej stronie, dlatego trudno nam wskazać żródło problemu. Tak jak wspomniałem - poprawność JSON możesz sprawdzić np. w Postmanie.

**Comment by BappressWW** [comment]
Witam
Sprawdziłem Postamana i znalazłem błąd.
Idedalej sprawdzam czy paczka się utowrzyła i dostaje komunikat:
{
	"id": "875a6f45-4ef4-458c-a4a1-3b89ec69c21e",
	"parcelId": null,
	"status": "ERROR",
	"errors": [
		{
			"code": "ERROR",
			"message": "Service unavailable for carrier",
			"details": null,
			"path": "additionalServices",
			"userMessage": "Usługa niedostępna u tego przewoźnika"
		},
		{
			"code": "ERROR",
			"message": "Processing error",
			"details": null,
			"path": null,
			"userMessage": "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"
		}
	]
}
Czy tu coś jest źle skonfigurowane na koncie allegro, czy ja robię bląd?

**Comment by PrzemyslawLukanowski** [comment]
Usuń ze swojej struktury `additionalServices.cashOnDelivery` oraz `additionalServices.options["sendingAtPoint"]`, a request przejdzie prawidłowo.

**Comment by PrzemyslawLukanowski** [comment]
A jeśli chcesz przekazać `additionalServices.options["sendingAtPoint"]`, uzupełnij wtedy wartość w polu `pickup.pointId`.

**Comment by BappressWW** [comment]
W przypadku mojego klienta jest to tylko UPS a UPS nie ma punktów odbioru. Po zmianach udało mi się zarejestrować paczkę i wszystko jest ok, dziękuje za pomoc.

**Comment by BappressWW** [comment]
Witam ponownie wczoraj i dziś przy próbie rejestracji paczki np:
https://api.allegro.pl/parcel-management/parcel-create-commands/3e98e942-58f1-486b-8ca0-ba4a0a78fcf3 i sprawdzenia jej status dostaję komunikat: "Receiver address should be different than sender address", gdzie sender zawsze jest taki sam u mnie na stałe ale odbiorca jest z zamówienia i są rózne.

**Comment by Lukasz-Zurek** [comment]
@BappressWW Weryfikujemy to. Wkrótce wrócę z odpowiedzią.

**Comment by BappressWW** [comment]
Dziękuję

**Comment by Lukasz-Zurek** [comment]
Błąd jest prawidłowy. Dane w obiekcie "receiver" (odbiorca) są identyczne jak w obiekcie "pickup" (miejsce odbioru). Gdy odbiór towaru jest od nadawcy, poprawne dane w "pickup" muszą być spójne z danymi w "sender".

**Comment by BappressWW** [comment]
A to ciekawe bo kilka zamówień było tak złożonych od samego początku i błędu nie było, a wczoraj tylko na dwóch zamówieniach pokazał się błąd.

**Comment by Lukasz-Zurek** [comment]
> 
> 
> A to ciekawe bo kilka zamówień było tak złożonych od samego początku i błędu nie było, a wczoraj tylko na dwóch zamówieniach pokazał się błąd.

Jeśli są to świeże zamówienia i posiadasz commandId, dla których udało się bez problemu utworzyć paczki w ten sposób - zweryfikujemy to oczywiście i wyjaśnimy.

**Comment by BappressWW** [comment]
Wczoraj zostało to zarejestrowane o godzinie 17:00 comadnid: e004ef0b-4822-4cfb-9df8-d989b75ded8d

**Comment by Lukasz-Zurek** [comment]
Dziękuję. Sprawę przekazałem do dodatkowej weryfikacji. Proszę o cierpliwość.

**Comment by BappressWW** [comment]
Witam chciałem zapytać jak wygląda weryfikacja i czemu to tak długo trwa.

**Comment by Lukasz-Zurek** [comment]
Usługę "Wysyłam z Allegro" udostępniamy we współpracy z Furgonetka.pl. W związku z czym sprawę przekazaliśmy do wspomnianego serwisu w celu dalszej weryfikacji.

Przepraszam za długi czas oczekiwania na odpowiedź. Zależy mi jednak na dokładnej analizie, która wymaga czasu.

**Comment by Lukasz-Zurek** [comment]
@BappressWW Komunikat "Adres odbiorcy powinien być inny niż adres nadawcy" występuje zawsze kiedy podajesz ten sam adres nadawcy, jak i odbiorcy. System waliduje wtedy na podstawie adresu odbiorcy, czy przypadkiem adres nadawcy nie jest identyczny. W przypadku pierwszego zlecenia system zadziałał prawidłowo, gdyż wykrył te same dane w ulicy.

W przypadku walidacji ulicy odbiorcy serwis Furgonetka.pl sprawdza również, czy są zawarte tam nietypowe znaki, emotki, ukryte spacje itp. - jeśli tak - są one usuwane lub zamieniane na prawidłowe. W przypadku pola ulicy nadawcy nie jest to walidowane. 

Zamówienie, w którym nie było komunikatu o błędzie, walidacja na podstawie danych odbiorcy wyrzuciła ukrytą spację na końcu ulicy, porównała ją z adresem nadawcy, której walidacja nie usuwa ukrytej spacji i uznała to za dwa różne adresy. 

Unikaj podawania tych samych nazw ulic w polach nadawcy i odbiorcy. Realizacja takiego zlecenia mija się z celem, gdyż w takiej sytuacji kurier odbiera przesyłkę z adresu, do której ma ją dostarczyć.
