### ISSUE TITLE
INVALID_JSON 

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#4612]
Tak się zastanawiam dlaczego API nie odpowiada konkretnym błędem tylko trzeba pisać pytania.
 
 Proszę o pomoc w rozwiązaniu problemu

[data.json.txt](https://github.com/allegro/allegro-api/files/6655622/data.json.txt)

**Comment by PrzemyslawLukanowski** [comment]
INVALID_JSON wskazuje na błąd w strukturze żądania. Czy możesz podać trace-id tego wywołania? JSON wygląda na prawidłowy, udało mi się na jego podstawie utworzyć prawidłowy draft oferty.

**Comment by PiotrFerenc** [comment]
OK. Już znalazłem. Okazało się że błąd jest po stronie biblioteki z której korzystam. RestSharp.
