### ISSUE TITLE
shippingRates->id

### ISSUE THREAD

**Issue by syw2020xd** [allegro/allegro-api#4613]
Czy do zamówienia mogę dołączyć shippingRates->id   wg listy : /sale/shipping-rates?seller.id=...

W zamówieniu jest delivery->method->id   - jak to się ma do poszczególnego shippingRates->id ?

**Comment by PrzemyslawLukanowski** [comment]
Co masz dokładnie na myśli przez "Czy do zamówienia mogę dołączyć shippingRates"? Nie możesz modyfikować danych w zamówieniu.

> W zamówieniu jest delivery->method->id - jak to się ma do poszczególnego shippingRates->id ?

shippingRates.id to cennik dostawy, w skład którego może wchodzić wiele metod wysyłki. Wartość w delivery.method.id to natomiast konkretna metoda dostawy, którą wybrał kupujący i która wchodzi w skład cennika dostaw (shippingRate) przypisanego dla danej oferty. Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#cennik-dostaw).
