### ISSUE TITLE
Zwiększona ilość: Podana wartość parametru Marka (7108) nie istnieje w słowniku.

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#4615]
Wygląda na to, że coś jest nie tak z danymi w parametrach kategorii, bo mimo, że
https://api.allegro.pl/sale/categories/10783/parameters
zwraca 7108_597209 dla 7108 to później PUT https://api.allegro.pl/sale/offers/{auction_id} wali błędem

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz teraz spróbować powtórzyć operację? Jeśli prolbem nadal występuje, podaj proszę przykładowe trace-id. Nie udało mi się powtórzyć błędu, mogę zaktualizować parametr w ofercie na tę wartość.

**Comment by anih** [comment]
Wygląda na to, że już przeszło.

**Comment by anih** [comment]
Jednak jeszcze nie do końca, bo dla kategorii 147417 wysyłam:
{'id': 7108, 'valuesIds': ['7108_52'], 'values': ['PS1'], 'rangeValue': None}
i dostaję
Custom value cannot be defined when the dictionary value is not an ambiguous one: parameterId=7108 a w parametrach jest

  {'id': '7108',
   'name': 'Marka',
   'type': 'dictionary',
   'unit': None,
   'options': {'variantsEqual': True,
    'variantsAllowed': False,
    'ambiguousValueId': '7108_52',
    'describesProduct': True,
    'customValuesEnabled': True,
    'dependsOnParameterId': None,
    'displayDependsOnValueIds': None,
    'requiredDependsOnValueIds': None},

**Comment by hahyes** [comment]
Widać, że jest tego więcej. Dla kategorii 76103 w parametrze Marka (3786) wysyłam wartość 85 dla wartości "inna marka", jednak nie występuje ona w słowniku marki. Ta wartość jest też w ambigiousValueId, więc raczej zniknęła przez przypadek. Mam więcej takich problemów z marką z różnych kategorii np. kategoria 87913 i też parametr Marka (10563), brakuje wartości "inna marka".
Przykładowy Trace-Id: 6ebf692b61da56ae

**Comment by PrzemyslawLukanowski** [comment]
@anih @hahyes Weryfikuję zgłoszone przez Was nieprawidłowości, wrócę z odpowiedzią.

**Comment by anih** [comment]
Podobne problemy występują jeszcze w kategoriach: 19915, 5540, 19917, 5547, 5543, 55204, 55202

**Comment by shambo666** [comment]
w kategorii 250427 to samo
wartości słownikowe wymienione w parametrach kategorii pobranych przez API nie pokrywają się z tymi dostępnymi podczas wystawiania przez stronę

**Comment by anih** [comment]
Kolejna kategoria: 13380

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady, wiemy o problemie - poinformuję w wątku po rozwiązaniu.

**Comment by dol1234** [comment]
To samo dla kategorii 91282 (parametr: 223541, wartość: 223541_305725)

**Comment by PrzemyslawLukanowski** [comment]
Problem z wpisaniem własnej wartości (custom value) nie powinien już występować. Pracujemy jeszcze nad rozwiązaniem problemu dot. komunikatu o nieistniejącej wartości w parametrze.

**Comment by PrzemyslawLukanowski** [comment]
Drugi problem również nie powinien już występować.

**Comment by anih** [comment]
U mnie powrócił spokój ;)

**Comment by anih** [comment]
I dziś znowu problemy z parametrami słownikowymi, np:
```
Custom value cannot be defined when the dictionary value is not an ambiguous one: parameterId=7108
```
przy podaniu 
```
{'id': 7108, 'valuesIds': ['7108_52'], 'values': ['Lewski Shoes'], 'rangeValue': None}
```
dla kategorii: 147417

**Comment by PrzemyslawLukanowski** [comment]
@anih Czy możesz powtórzyć request, a jeśli problem nadal występuje, to pdoać przykładowe trace-id? Sprawdziłem ten przypadek  i udało mi się prawidłowo wystawić ofertę z wartością niejednocznaną parametru 7108 w tej kategorii.

**Comment by anih** [comment]
W tej chwili problem już nie występuje, ale od około 8 do 9:10(20) występował.

**Comment by anih** [comment]
@PrzemyslawLukanowski  nowy tydzień nowa fala: 
```
'category': {'id': 257929}
{'id': 7108, 'valuesIds': ['7108_88']}
Assigned valueId  for dictionary parameter 7108 is not found
```

**Comment by PrzemyslawLukanowski** [comment]
@anih  Dziękuję za przykład, potwierdzam występowanie problemu. Zweryfikujemy przyczynę błędu.

**Comment by PrzemyslawLukanowski** [comment]
@anih Problem nie powinien już występować.

**Comment by anih** [comment]
@PrzemyslawLukanowski wygląda na to, że co jakiś czas ktoś powoduje ten problem, bo znowu dla:
`{'id': 7108, 'valuesIds': ['7108_52'], 'values': ['Test'] }`
i `'category': {'id': 257903}`
dostajemy `'Assigned valueId  for dictionary parameter 7108 is not found.', 'No value was given for parameter Brand (7108).'`

**Comment by anih** [comment]
I nie jest to jedyna kategoria w jakiej są problemy

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, przekazałem problem do odpowiedniegu zespołu w celu weryfikacji.

**Comment by PrzemyslawLukanowski** [comment]
@anih Udało nam się znaleźć przyczynę, dlaczego problem powracał co jakiś czas. Wprowadziliśmy już poprawkę, problem nie powinien występować.
