### ISSUE TITLE
Zakonczenie pojedyńczej oferty w trybie synchronicznym

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#4618]
Prosiłbym o umożliwienie zakończenia pojedynczej oferty w sposób synchroniczny przez wywołanie zasobu sale/offers/{offerId} 
(np przez przekazanie statusu ENDED w obiekcie publication)

**Comment by Lukasz-Zurek** [comment]
W naszym serwisie aktywacja oferty, jak i jej zakończenie - działają asynchronicznie. W związku z tym umożliwienie zakończenia pojedynczej oferty w sposób synchroniczny nie będzie technicznie możliwe. 

Jeśli wspomniana funkcjonalność miałaby dotyczyć asynchronicznego zakończenia pojedynczej oferty - bardzo proszę o doprecyzowanie sugestii oraz jej uzasadnienie.
