### ISSUE TITLE
Brak Marki - produkt

### ISSUE THREAD

**Issue by ghost** [allegro/allegro-api#4619]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,

Oferta: 8633820121
Produkt: C0F1C3A1-53B5-4078-A297-0A8B969CA89C

Dla oferty, która jest spięta z produktem jak powyżej dostajemy komunikat błędu, skąd taki błąd jeśli oferta spięta jest z produktem? Wczoraj nagle błąd zaczął występować, wcześniej nie mamy nic w logach

{"RaportZlecenia":{"Nr":"2b04fa64-d2f1-43d9-b262-a0cea8f89658","Response":{"Data":{"Tasks":[{"Field":"quantity","FinishedAt":"2021-06-17T04:37:12.165Z","Message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","Offer":{"Id":"8633820121"},"ScheduledAt":"2021-06-17T04:37:12.166Z","Status":"FAIL","Errors":[{"Code":"ConstraintViolationException.NonExistingValueInDictionaryParameter","Details":null,"Message":"Podana wartość parametru Marka (129369) nie istnieje w słowniku.","Path":"parameters","UserMessage":"Podana wartość parametru Marka (129369) nie istnieje w słowniku."}]}]},"Validation":null,"Exception":null,"TraceId":"38b3f78565324475","Error":false,"StatusCode":200,"Message":null}}}

**Comment by hahyes** [comment]
Nie ty pierwszy i nie ty ostatni: #4615

**Comment by Lukasz-Zurek** [comment]
@SebastianOzdoba Potwierdzam, że jest to błąd i pracujemy obecnie nad jego wyeliminowaniem. 

Przepraszamy za utrudnienia.
