### ISSUE TITLE
Czy wznawianie ofert działa poprawnie?

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#462]
Witam,
wysyłam dzisiaj requesty aby wznowić oferty i cały czas moje requesty czekają w kolejce a aukcje są zakończone.
Gdy wznawiam oferty ręcznie to są aktywne do 5 minut a przez API czekam już 30 minut i nic.
Czy ta funkcja działa czy przestała działać?

**Comment by KrzysztofLukanowski** [comment]
Cześć, wszystko powinno być okej. Wystawienie oferty może zająć do 60 minut - jeżeli po tym czasie oferta nie pojawi się na Allegro, podeślij proszę request i response w json.

**Comment by expondo** [comment]
Już 2 godziny czekam i wysyłam po dziesiątki razy requesty aby aktywować oferty.
Przykładowy request:

{"publication":{"action":"ACTIVATE"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":7210931044}]}]}

Otrzymuję
{"id":"50ae4138-8618-5c14-da3e-2e7db9529cd5","taskCount":{"total":0,"success":0,"failed":0}}

I następnie gdy sprawdzam status zadania co cały czas otrzymuję todal, success i failed 0. Nic się nie zmienia

**Comment by expondo** [comment]
Inne zadania, które cały czas wiszą w kolejce

90c9b307-1276-6eef-e1ac-6eb43c90473f
6af4b031-7eb0-4d98-9fbd-cc3178978715
26570ae7-06a6-d248-863a-732585bd448a
3cbddd35-0b7f-b841-7417-ffdf7d9f9640

Proszę sprawdzić co z nimi się dzieje bo to nienormalnie wygląda
