### ISSUE TITLE
Wyszukiwanie produktu za pomocą filtrów

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4620]
Dzień dobry. Nie mogę zrozumieć, dlaczego ten request ignoruje filry. Proszę mi powiedzieć.

GET https://api.allegro.pl/sale/products?phrase=filtron&category.id=49237&215858=K%201256A&127415=127411_338861

**Comment by PrzemyslawLukanowski** [comment]
Listę dostępnych filtrów i ich wartości dla danej kategorii znajdziesz na końcu response, w sekcji "filters". Nie jest ona tożsama z wartościami, które otrzymasz dla GET /sale/categories/49237/parameters. Filtr tworzysz, podając identyfikator filtra i identyfikator szukanej wartości, na zasadzie {filter.id}={filter.value}. W podanej przez Ciebie kategorii możesz użyć tylko filtra "Producent części" - zamiast wartości "127411_338861" powinieneś przekazać "338861"

**Comment by vartaller** [comment]
Ok. Dziękuję.
