### ISSUE TITLE
Missing required parameters: Installation side.

### ISSUE THREAD

**Issue by bugproof** [allegro/allegro-api#4623]
Od jakiegoś czasu zaczęły pojawiać się te błędy przy zmiany ilości sztuk. Wcześniej ich nie było. Ofert jest zbyt dużo by ręcznie wypełnić ten parametr. Jak wypełnić go przez api?

**Comment by PrzemyslawLukanowski** [comment]
Zmiany możesz wykonać w kontekście pojedynczej ofert, najpierw pobierając ofertę za pomocą GET /sale/offers/{offerID}, a następnie - po uzupełnieniu danych - wysyłając update za pomocą PUT /sale/offers/{offerID}.

**Comment by bugproof** [comment]
A skąd można pobrać listę wszystkich prawidłowych wartości dla danego parametru?

**Comment by PrzemyslawLukanowski** [comment]
Zrobisz to za pomocą [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2), a w [naszym poradniku](https://developer.allegro.pl/sale/#parametry) znajdziesz więcej informacji na temat tego endpointu.
