### ISSUE TITLE
sandbox aktywacja płatności odroczonych

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#4624]
Jak w temacie jak mogę to zrobić?
Przy wyborze płatności odroczonej jestem kierowany do autoryzacji(zrobienie przelewu) i otwiera się strona: https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php#contentDiv3 na której tak naprawdę nie mogę nic zrobić.

**Comment by PrzemyslawLukanowski** [comment]
Zapoznaj się proszę z informacją z [tego wątku](https://github.com/allegro/allegro-api/issues/4116#issuecomment-783148435):

> możesz aktywować odroczoną płatność na Sandbox. Obecnie na koncie musi widnieć NIP, który faktycznie istnieje, a nie jest wygenerowany przez automat.
> Jeżeli ten warunek jest spełniony, to wówczas należy wystąpić z wnioskiem o aktywację przez [stronę WWW](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/odroczona-platnosc-dla-firm).
> 
> Proszę następnie wskazać nam login konta, na którym takie działania zostały podjęte. Wydamy dyspozycję aktywacji płatności odroczonej na tym koncie.

**Comment by mlonc** [comment]
ok, konta:
- sandboxasco_si
- sandboxasco_si_2

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, przekazałem prośbę do odpowiedniego zespołu, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Zaakceptowaliśmy wnioski, dalej postępuj proszę zgodnie z [instrukcją](https://allegro.pl/pomoc/dla-sprzedajacych/platnosc-od-kupujacego/odroczona-platnosc-dla-firm-informacje-dla-sprzedajacych-k1WOEaoXZHL):

> 1. Przejdź do zakładki [Odroczona płatność dla Firm](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/odroczona-platnosc-dla-firm).
> 2. Wybierz [sprzedaję i kupuję].
> 3. Wskaż konta, na których chcesz korzystać z usługi.
> 4. Zapoznaj się z umową faktoringową i regulaminem usługi, i potwierdź, że je akceptujesz.
> 5. Potwierdź chęć zawarcia umowy kodem SMS. Otrzymasz go na numer z ustawień konta, którego użyjesz do aktywacji usługi.

**Comment by mlonc** [comment]
Witam w dalszym ciągu nie mogę skorzystać z płatności odroczonej -> ciągle chce pełnej aktywacji konta

![image](https://user-images.githubusercontent.com/30781954/122742555-5a750080-d286-11eb-91e7-a44d5008048a.png)

![image](https://user-images.githubusercontent.com/30781954/122742623-6eb8fd80-d286-11eb-879a-dc2131080af1.png)

Czego mi jeszcze brakuje abym na środowisku testowym mógł przetestować te płatności odroczone?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz ponownie spróbować skorzystać z odrocznej płatności? Wykonaliście jeszcze dodatkowe zmiany po naszej stronie dla Twoich kont.

**Comment by mlonc** [comment]
Okna koncie sandboxASCO_SI_2 działa, póki co czekam na sms aktywacyjny
na koncie sandboxASCO_SI sprawdzę za chwilę

**Comment by mlonc** [comment]
Na obu kontach nie przychodzi sms 
![image](https://user-images.githubusercontent.com/30781954/122745844-b7be8100-d289-11eb-94a7-8fec494903e7.png)

Próbowałem opcji "Wyślij ponownie"

**Comment by mlonc** [comment]
Plus czy dla sandboxa również jest wymagane potwierdzenie tych płatności poprzez sms?

**Comment by PrzemyslawLukanowski** [comment]
W środowisku testowym nie wysyłamy SMS dla tej usługi, dlatego ostateczną aktywację wykonaliśmy wewnętrznie po naszej stronie. Odroczona płatnośc powinna być już w pełni aktywna.

> Plus czy dla sandboxa również jest wymagane potwierdzenie tych płatności poprzez sms?

Nie, nie ma takiego wymogu.

**Comment by mlonc** [comment]
Ok na chwilę obecną teoretycznie działa. Teoretycznie ponieważ przy próbie zakupu mam komunikat, że płatność jest nie udana
Tak ma być czy jest jakiś problem z tym?

![image](https://user-images.githubusercontent.com/30781954/122763120-43daa380-d29e-11eb-9c45-f0c63356bc3a.png)

**Comment by mlonc** [comment]
Ok jak rozumiem mam pobrać zamówienie do programu, wystawić fakturę i umieścić ją w zamówieniu potem dodać list przewozowy i wtedy status płatności się zmieni?

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj proszę teraz ponowić zamówienie.

**Comment by mlonc** [comment]
w dalszym ciągu na koncie sandboxASCO_SI_2 mam jak na powyższym screenie

**Comment by mlonc** [comment]
Albo inaczej, kiedy status zamówienia zmieni się na "READY_FOR_PROCESSING":
1. w momencie gdy klient wybierze płatność odroczoną
2. w momencie gdy sprzedający do zamówienia doda fakturę w pdf i numer listu przewozowego?

**Comment by mlonc** [comment]
zadziałało dziękuję za pomoc

**Comment by mlonc** [comment]
Po dodaniu faktury, została ona odrzucona:
![image](https://user-images.githubusercontent.com/30781954/122776420-62936700-d2ab-11eb-9e06-35311d53323e.png)
fragment faktury z danymi(numer konta bankowego jest dodany):
![image](https://user-images.githubusercontent.com/30781954/122776563-80f96280-d2ab-11eb-9d59-07acd4ef95b7.png)

**Comment by PrzemyslawLukanowski** [comment]
Powód odrzucenia faktury po naszej stronie brzmi: "Kupujący nie może być sprzedającym" - konto kupującego nie może mieć takiego samego NIPu jak sprzedającego. Możesz edytować NIP na koncie kupującego, musi to być prawdziwy, istniejący numer. Po edycji konieczna będzie ponowna weryfikacja dla odroczonej płatności.

**Comment by VanthuZ** [comment]
Jak można to się podepnę,
proszę o zmianę nipu konta IDEAerp na 7010682602  oraz aktywację odroczonych płatności.

**Comment by MaciejFrackowiak** [comment]
@VanthuZ Zmianę NIP możesz wykonać tylko osobiście poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) - niezbędne będzie przesłanie dwóch dowolnych plików, aby zweryfikować konto firmowe. Jak już z powodzeniem dokonasz zmiany, daj proszę znać, wówczas przejdziemy do aktywacji odroczonej płatności.

**Comment by VanthuZ** [comment]
@MaciejFrackowiak Wniosek złożony.

**Comment by MaciejFrackowiak** [comment]
@VanthuZ Dziękuję za info, działam w temacie aktywacji odroczonych płatności.

**Comment by VanthuZ** [comment]
@MaciejFrackowiak 
Nie mogliśmy automatycznie przyznać Ci środków w usłudze Odroczonej płatności dla Firm.
Taki komunikat mam na stronie:
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/odroczona-platnosc-dla-firm

**Comment by MaciejFrackowiak** [comment]
@VanthuZ Będę to wyjaśniać - niestety, proces aktywacji odroczonych płatności oparty jest na współpracy z zewnętrznym partnerem, stąd nie mamy możliwości wykonywania operacji "od ręki" oraz wyjaśnianie takich sytuacji trochę trwa.

**Comment by MaciejFrackowiak** [comment]
@VanthuZ Płatności odroczone są już aktywne na Twoim koncie.
