### ISSUE TITLE
Allegro Ceny - czy aktualizacja oferty może usunąć tą ofertę z tego programu?

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#4625]
Czy endpoint `PUT /sale/offers/{offerId}` jest w stanie zmienić coś w tych cenach? Klient zgłasza, że to nasze oprogramowanie usunęło ofertę.

> Wczoraj zostały włączone dla tej aukcji specjalne cenniki hurtowe, które umożliwiają reklamowanie tej oferty na głównej stronie Allegro – w dniu dzisiejszym cennik ten nie był już dostępny, Allegro informuje, że zmiana dokonała się z poziomu API. 

Szczerze mówiąc tylko my grzebiemy przy API Allegro. Jak możemy to naprawić?

**Comment by PrzemyslawLukanowski** [comment]
Tak, zmiana ceny może wykluczyć ofertę z programu. Poniżej załączam informację ze [strony dla sprzedających](https://allegro.pl/dla-sprzedajacych/poznaj-allegro-ceny-na-czym-polega-program-wsparcia-dla-sprzedajacych-2YAZ1gAqRiK#co-sie-stanie-z-oferta-objeta-programem-allegro-ceny-jesli-podniose-w-niej-cene-).

> **Co stanie się z ofertą objętą programem Allegro Ceny, jeśli podniosę w niej cenę?**
> 
> Każda zmiana ceny towaru w ofercie spowoduje wyłączenie programu Allegro Ceny dla tej oferty. Ponowne zakwalifikowanie oferty do programu będzie możliwe dopiero w następnej rundzie kwalifikacyjnej. Nie poniesiesz żadnych kosztów wyłączenia oferty z programu.
>

**Comment by troncomputers** [comment]
Zmieniamy tylko stany magazynowe i stawkę VAT. Nie zmieniamy cen, ponieważ klient ma inne ceny w systemie ERP i inne na Allegro i to robią ręcznie.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę numer oferty, której dotyczy ten problem. Możesz to zrobić tutaj lub za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - wtedy dopisz, że informacja dotyczy wątku #4625 na Githubie.

**Comment by troncomputers** [comment]
Poszło

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy nasze logi, według nich wskazana przez Ciebie oferta nigdy nie była objęta programem "Allegro Ceny".

**Comment by troncomputers** [comment]
Okazało się, że chodzi o jakiś program "Ceny Hurtowe". Jak klient kupi określoną ilość sztuk to zmienia się cena zamówienia. I nasze zmiany ilości i stawki VAT powoduje, że ta cena "hurtowa" nie wskakuje podczas kupowania. Przez piątek i sobotę ten towar był w programie, a przez niedziele, aż do dzisiaj już w tym programie nie widnieje.

**Comment by PrzemyslawLukanowski** [comment]
Powodem odpięcia cennika hurtowego od wskazanej oferty jest to, że Wasza aplikacja przy operacjach PUT /sale/offers/{offerID} w strukturze JSON nie uwzględnia pola `discounts.wholesalePriceList.id` (id cennika hurtowego) przez co w odpowiedzi w tym polu zmieniamy istniejącą wartość na `null`. Wygląda to tak:
- 2021-06-22 08:12 - użytkownik przez naszą stronę internetową przypisał do oferty cennik hurtowy o id 53197457-d9e9-4384-9adc-2a4dd558a1de. W tym momencie w odpowiedzi na GET /sale/offers/{id} w polu `discounts.wholesalePriceList.id` właśnie taką wartość;
- 2021-06-20 11:15 - ma miejsce pierwsza operacja PUT /sale/offers/{offerID}, gdzie w strukturze nie ma tego pola, w związku z czym wartość w `discounts.wholesalePriceList.id `zmieniliśmy na null;
- 2021-06-22 08:12 - użytkownik ponownie przypisuje przez stronę internetowącennik hurtowy do oferty.

**Comment by troncomputers** [comment]
Teraz już wszystko jasne. Poprawka wdrożona. Dzięki za pomoc ✌

**Comment by troncomputers** [comment]
Wracam z tematem. 
Bardzo proszę o weryfikacje czy to my klientowi zmieniamy znowu te cenniki hurtowe. Dostaje ofertę z API, w której jest `discounts.wholesalePriceList.id` i zmieniamy na tej ofercie tylko `stock.available`, a mimo to oferta "odpina" się od cennika. Wygląda to tak, że mimo, iż przekazuje w obiekcie komplet danych do API Allegro nie zapisuje tego id cennika. Dlaczego `discounts` się zeruje?

**OFERTY**
https://allegro.pl/oferta/dettol-bezdotykowe-mydlo-w-plynie-aloe-dozownik-9260104054 
https://allegro.pl/oferta/dettol-antybakteryjne-mydlo-plynie-aloes-500ml-9654913541 
https://allegro.pl/oferta/dettol-antybakteryjny-spray-powierzchni-lime-500ml-9297047090

**Comment by PrzemyslawLukanowski** [comment]
Z posiadanych przez nas logów wynika, że to edycje oferty za pomocą PUT /sale/offers/{offerID} nie zawierają informacji o `discounts.wholesalePriceList.id`, dlatego cenniki hurtowe są usuwane z oferty, np. dla 9654913541 wczorajsze edycje o 14:17 i 11:47.

**Comment by troncomputers** [comment]
Ok. Mogę jeszcze ewentualnie podejrzewać, że to Newtonsoft.Json. Zaktualizowałem tą bibliotekę i zobaczymy, czy teraz "zaskoczy". 
Ostatnie pytanie - są jakieś konsekwencje dla mojego klienta z powodu takiego włączania/wyłączania cenników na Allegro? Nie ukrywam, że sprawa już dawno powinna być zamknięta, a klient po każdym naszym "spartoleniu" sprawy włącza cennik na nowo.

**Comment by PrzemyslawLukanowski** [comment]
Nie, takie edycje nie niosą ze sobą żadnych konsekwencji.

**Comment by troncomputers** [comment]
Wątpię żeby ktoś w przyszłości miał taki sam problem ale na wszelki wypadek napiszę. Tyczy się to oprogramowania w .NET. Musiałem zaktualizować do najnowszych wersji `Newtonsoft.Json` oraz `RestSharp`. Dodatkowo musiałem pobrać `RestSharp.Serializers.NewtonsoftJson` i ustawić
```csharp
RestClient client = new RestClient(apiUrl);
client.UseNewtonsoftJson();
```
