### ISSUE TITLE
W jaki okolicznościach pojawia się błąd "Błąd pobierania produktu"

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#4626]
Dzień dobry

Mam przypadek oferty która ma przypisany produkt o id 0ba373d7-ff41-4ff4-9e6f-51cbf7d4e403, na formularzu wystawiania oferty w allegro pojawia się błąd 
![Screenshot from 2021-06-18 12-41-47](https://user-images.githubusercontent.com/4314822/122549700-14742e80-d033-11eb-8953-5178b4631fd1.png)

w odpowiedzi na https://api.allegro.pl/sale/products/0ba373d7-ff41-4ff4-9e6f-51cbf7d4e403 otrzymuję 

`{
    "errors": [
        {
            "code": "NotFoundException",
            "message": "Not Found",
            "details": null,
            "path": null,
            "userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
        }
    ]
}`

Czy produkty mogą zostać usunięte z bazy allegro? Z tego co mi wiadomo to mogą być zmienione ale nie usunięte.

**Comment by PrzemyslawLukanowski** [comment]
Tak, produkty mogą zostać usunięte i w takim przypadku otrzymasz komunikat wskazany przez Ciebie powyżej.
