### ISSUE TITLE
GET /sale/offers - filtrowanie po opcjach promowania (badges)

### ISSUE THREAD

**Issue by dawidkozlowski** [allegro/allegro-api#4627]
Czy jest możliwość filtrowania ofert przez API po opcjach promowania(badges)? Widzę że jest taka opcja w managerze allegro i bardzo przydatne byłoby to również przez API. Na ta chwilę widzę jedynie możliwość sprawdzania jakie 'badges' ma dana oferta.
![01](https://user-images.githubusercontent.com/25519114/122563232-3f1ab300-d044-11eb-969a-0517c2f58eb0.jpg)

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy takiej możliwości w API.

**Comment by dawidkozlowski** [comment]
Czy macie w planach udostępnianie takiej możliwości?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie, możesz skorzystać z naszej zakładki [Discussions ](https://github.com/allegro/allegro-api/discussions)i dodać taką sugestię. Dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba. Więcej o zakładce Discussions znajsziesz w [naszym newsie](https://github.com/allegro/allegro-api/issues/4337).
