### ISSUE TITLE
[sandbox api] Too Many Requests, pomimo nieprzekroczenia limitu

### ISSUE THREAD

**Issue by michalfurtak** [allegro/allegro-api#4630]
Cześć,
testuję wydajnościowo swoją aplikację i mam problem z API. Próbuję wyszukać produktu po EAN (url=https://api.allegro.pl.allegrosandbox.pl/sale/products?ean=xxx). Operację powtarzam 40 razy (dla rożnych EANów), w 10 wątkach. Według dokumentacji taki ruch nie powinien powodować blokady (limit to 150req/s). Błędy występują niedeterministycznie. Błędy pojawiają się także przy innych metodach.
Przykładowy response:
````
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: e225ed72221dc6c
date: Sat, 19 Jun 2021 14:38:04 GMT
x-content-type-options: nosniff
content-type: application/json
content-length: 154
OkHttp-Sent-Millis: 1624113496676
OkHttp-Received-Millis: 1624113496719


{"errors":[{"code":"RateLimitExceedException","message":"An error has occurred","details":null,"path":null,"userMessage":"Przekroczony limit zapytań."}]}
````

Co może być przyczyną błędy? Dlaczego API zachowuje się niedeterministycznie?

MF

**Comment by MartaNowaczyk** [comment]
Zgodnie z informacją w naszym [poradniku](https://developer.allegro.pl/productization/#2-jak-wyszuka%c4%87-produkt) - dla tego zasobu obowiązuje [Dodatkowy limit liczby zapytań dla użytkownika].(https://developer.allegro.pl/about/#ograniczenie-liczby-zapyta%C5%84-limity).
