### ISSUE TITLE
Problem z zasobem /after-sales-service-conditions/implied-warranties/${Id}

### ISSUE THREAD

**Issue by ahaw** [allegro/allegro-api#4631]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Od kilku godzin pojawia się problem przy korzystnaiu z zasobu `/after-sales-service-conditions/implied-warranties/${Id}`
: Error: AllegroRestApiClient::request: Internal Server Error 500 {"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please 
try again in a few minutes."}]}

Problem pojawia się tylko dla niektórych obiektów:
Działą źle: 250c9ce4-dfe3-445c-b5e2-80504942b70f
Działą dobrze: dc20dfcd-12d4-47d7-a7e7-c563f255dae4

clientId: b9f3f77426034dadb91362a7b27ee7ba

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się zlokalizować przyczynę problemu, nie powinien już występować.

**Comment by ahaw** [comment]
Działa dobrze, dziękuję :)
