### ISSUE TITLE
Sandbox problem przy sprawdzeniu statusu utworzonej paczki

### ISSUE THREAD

**Issue by M-Kaczmarek** [allegro/allegro-api#4632]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Cześć
Przy wywołaniu metody do sprawdzenia statusu utworzonej przesyłki `GET /parcel-management/parcel-create-commands/{commandId}`  występuje błąd 
`{
    "id": "e8b36ae6-f04e-4986-848a-ae79e42e2f8b",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Receiver point is required",
            "details": null,
            "path": "receiver.pointId",
            "userMessage": "Punkt odbiorcy jest wymagany"
        }
    ]
}`
Adresem odbiorczym zamówienia nie jest punkt odbiorcy( w szczegółach zamówienia pole delivery.pickupPoint jest nullem)
Problem ten występuje od piątku(w czwartek dla identycznego zamówienia i requesta przesyłka tworzyła się bez problemu)

**Comment by MartaNowaczyk** [comment]
Wiemy o tym problemie. Pracujemy nad jego rozwiązaniem. Dziękujemy za zgłoszenie.
