### ISSUE TITLE
PATCH \ Invalid parameter \ Tech doc

### ISSUE THREAD

**Issue by vartaller** [allegro/allegro-api#4633]
Dzień dobry.
Zmieniam opis oferty metodą PATCH (przekazuję tylko fragment 'description') i otrzymuję w odpowiedzi taki błąd:
`Invalid parameter Producent części (127415) value for offer with product. Value should be \"Inny\"`.
trace-id: 5210ad871877f55a

Wydaje mi się, że problem polega na tym, że w starym Tec doc producent części nazywał się inaczej. Jednak metoda PATCH musi zmienić Tech doc.
Proszę o podpowiedź, dlaczego wystąpił ten błąd?

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisany przypadek. Wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Odświeżyliśmy produkt, bo mieliśmy problem z tym parametrem. Sprawdź proszę czy teraz jest ok.

**Comment by vartaller** [comment]
Mam wiele takich błędów. Oto kolejny przypadek, ten samy problem
trace-id: a7a7c86b6683d215

**Comment by MartaNowaczyk** [comment]
Dzięki za info. Sprawdzimy szerzej w takim razie.

**Comment by MartaNowaczyk** [comment]
Zrobiliśmy odświeżanie dla Ashika. Zerknij czy ok. Jak coś jeszcze Ci wpadnie, podsyłaj.

**Comment by vartaller** [comment]
Ten samy problem mam z producentem Blue Print (wiele błędów), trace_id: 68f3bf3c77509aba.
Również z producentem NIPPARTS - wiele błędów.

**Comment by MartaNowaczyk** [comment]
Sprawdzę podane pyrzypadki i wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Odświeżyliśmy Blue Print i NIPPARTS. Daj znać czy dostajesz jeszcze jakieś błędy.
