### ISSUE TITLE
Problem z ofertą

### ISSUE THREAD

**Issue by TOBOMEBLE** [allegro/allegro-api#4636]
Dzień dobry,

Dzień dobry, Czemu oferta którą zamykam sama się wznawia?
numer oferty 9486692164**

**Comment by MartaNowaczyk** [comment]
Dzień dobry, widzę, że już sobie poradziłeś ze wznawianiem. Jak pewnie już wiesz oferta wznawiana była przez Waszą aplikację.

**Comment by TOBOMEBLE** [comment]
Dzień dobry,

 

Niestety oferta cały czas się wznawia bez naszej ingerencji (w ustawieniach oferty również nie jest ustawione automatyczne wznawianie)

Z poważaniem,

Obsługa Allegro

 

kom. 661 467 190
 ***@***.***> ***@***.***

                                      

TOBO Datczuk Spółka Jawna, Kuriany 104, 15-588 Białystok

Kom: 662 055 425, Tel: 85 674 94 31, Fax: 85 674 94 01                           

NIP: 542 24 98 686, REGON: 050615211, KRS: 0000268148               

 ***@***.***> ***@***.***,  <https://tobo.pl/> tobo.pl;  <http://sklep.tobo.pl/> sklep.tobo.pl

Pomyśl o środowisku zanim wydrukujesz tego e-maila.

**Comment by MartaNowaczyk** [comment]
Gdy sprawdzałam oferta była zakończona. Teraz też jest - zakończona ręcznie z poziomu allegro. Sprawdź proszę aplikację - ClientID z końcówką ...16368 i "commandId": "049205e5-fc73-4cbb-bb8e-b5cfb664b9a0" - tutaj widzę ostatnie wznawianie przez API. Po naszej stronie nie widzę problemu.
