### ISSUE TITLE
Jakość / terminowość wysyłki - wykrywanie duplikatów

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4640]
:bulb: **Sugestia**
Nie dotyczy bezpośrednio API, ale zagadnienie mocno programistyczne. Poproszę o przekierowanie do odpowiedniego zespołu do rozważenia.
Zagadnienie: liczenie terminowości wysyłki i wykrywanie duplikatów numerów listów przewozowych.
Mam taki przypadek:
Klient dokonał zakupu w dwóch ofertach w tej samej kategorii, obydwie mają ten sam cennik i do paczki wchodzi 4 sztuki.
Numery zamówień allegro:
b0551700-d011-11eb-b3a5-677c973318da
7aea29c0-d011-11eb-b965-c1b836d73492
Przyszło jako dwa zamówienia, nie zostało połączone w jedno.
U mnie w systemie zostało połączone i nadane w jednej paczce.
Obydwa zamówienia otrzymały ten sam numer nadania.

Przy liczeniu terminowości wysyłki, drugie zamówienie ma w numerze przesyłki "brak".
(To jest raport pobrany z "jakość mojej sprzedaży -> wysyłka w terminie -> zobacz zestawienie")
Prawdopodobnie Wasz algorytm usunął numer ponieważ uznał, że to duplikat.
Czy moglibyście zmodyfikować wykrywanie duplikatów w ten sposób, żeby nie uznawał za duplikat identycznych numerów dla tego samego klienta. To jest przypadek, kiedy dla jednego klienta, różne zamówienia zostały wysłane w jednej paczce.

Pozdrawiam,
kf

**Comment by MartaNowaczyk** [comment]
Jak sam napisałeś sprawa nie dotyczy problemu z API Allegro. Zgłoś proszę te uwagi przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
