### ISSUE TITLE
Pobieranie notatki do zamówienia

### ISSUE THREAD

**Issue by kpodemski** [allegro/allegro-api#4641]
Cześć.

Czy mamy możliwość pobrania przez API notatki do zamówienia, którą może dodać sprzedający?

![image](https://user-images.githubusercontent.com/2137763/123157318-ac767b80-d46a-11eb-9fae-843f5083833f.png)

**Comment by MartaNowaczyk** [comment]
Nie zwracamy tego przez API i nie mamy w planach tego udostępniać. Chcieliśmy ułatwić pracę tym, co obsługują zamówienia tylko przez panel allegro.

**Comment by kpodemski** [comment]
Dzięki za odpowiedź 👍🏻
