### ISSUE TITLE
Usuwanie szkiców

### ISSUE THREAD

**Issue by indigos79** [allegro/allegro-api#4642]
Czy jest możliwość usunięcia szkiców w większej ilości. Po dobiciu do 20000 przestają wysyłać się aukcje. Natomiast kasowanie każdego z osobna jest dość uciążliwe.

**Comment by hahyes** [comment]
Jedyny znany mi sposób w REST API to znalezienie wszystkich aukcji o statusie INACTIVE (przez zasób **/sale/offers**), po czym usuwać każdy po kolei takim zapytaniem: https://developer.allegro.pl/news/2018-10-09_draft_delete/

**Comment by kfijalko** [comment]
@hahyes dokładnie tak to robię.
Job uruchamiany raz dziennie w odstępie 3 godzin od wystawiania i aktywacji draftów.

**Comment by Lukasz-Zurek** [comment]
@indigos79 Niestety nie ma takiej możliwości. Warto tutaj skorzystać ze sposobu opisanego przez @hahyes.
