### ISSUE TITLE
Niepoprawne punkt nadania oraz punkt odbioru w wysyłam z allegro

### ISSUE THREAD

**Issue by krzysztofzylka** [allegro/allegro-api#4643]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Podczas próby wystawienia paczki dla aukcji za pomocą inpost paczkmaty api zwraca błąd o niepoprawnym punkcie nadania oraz punkcie odbioru chociaż identyfikatory paczkomatów wydają się poprawne

Wysyłane zapytanie:
> {"serviceId":"8544252","receiver":{"address":{"street":"ul. Grunwaldzka, 182","postCode":"60-166","city":"Poznań","countryCode":"PL"},"email":"xxxxxx@user.allegrogroup.pl","name":"Marcin xxxxxx","company":null,"phone":"+48 600 700 800","pointId":"KRA007"},"pickup":{"address":{"street":"Wiejska 12/1","postCode":"58-560","city":"Jelenia Góra","countryCode":"PL"},"email":"xxxxxx","name":"xxxxxx","company":"Główna","phone":"xxxxxx","pointId":"POZ17A"},"items":[{"dimensions":{"height":{"value":"1","unit":"CENTIMETER"},"width":{"value":"1","unit":"CENTIMETER"},"depth":{"value":"1","unit":"CENTIMETER"}},"weight":{"value":"1","unit":"KILOGRAM"},"description":"asdgasdg","value":{"amount":44,"currency":"PLN"}}],"type":"PACKAGE"}

Odebrane zapytanie:
> {"id":"9e447dd5-d4e8-11eb-a775-40b076dd15f1","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Pickup point is incorrect","details":null,"path":"pickup.pointId","userMessage":"Punkt punktu nadania przesyłki jest niepoprawny"},{"code":"ERROR","message":"Receiver point is incorrect","details":null,"path":"receiver.pointId","userMessage":"Punkt odbiorcy jest niepoprawny"}]}

**Comment by Lukasz-Zurek** [comment]
Na środowisku testowym przewoźnicy ograniczają się do znacznie zmniejszonej puli dostępnych punktów, stąd zaistniała sytuacja.
