### ISSUE TITLE
payments/refunds powiązanie z zamówieniem

### ISSUE THREAD

**Issue by GoHelekCreate** [allegro/allegro-api#4644]
Mam pobrane zamówienia za pomocą GET order/checkout-forms i chciałbym powiązać zamówienie ze zwrotem, jednak pobrane zwroty za pomocą payments/refunds nie posiadają checkoutForm id.

Czy jest jakiś sposób, żeby to powiązać? Może w jakiś inny sposób da się to zrobić? Przede wszystkim potrzebuję informacji, które zamówienie zostało zwrócone.

**Comment by Lukasz-Zurek** [comment]
Tak, to prawda. Dla zasobu [GET /payments/refunds](https://developer.allegro.pl/documentation/#operation/getRefundedPayments) nie zwracamy **checkoutForm.id**. Zwracamy natomiast **payment.id**. Możesz go użyć, gdy skorzystasz z [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET). Możesz wyfiltrować zamówienia po identyfikatorze płatności, np. https://api.allegro.pl/order/checkout-forms?payment.id=682c64b2-3108-11e9-b62a-6d16ee003b16.

Więcej informacji na temat listy filtrów znajdziesz w [naszym poradniku.](https://developer.allegro.pl/orders/#lista-zam%c3%b3wie%c5%84)
