### ISSUE TITLE
Wykorzystanie metody GET /offers/listing - pytanie

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#4645]
Dzień dobry,

Czy ta metoda jest potrzebna, aby aktualizować własne oferty na Allegro przez API w zakresie cen, parametrów czy pasuje do?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Nie. Wspomniana metoda służy do wyszukiwania i przeglądania - w ramach naszego API - ofert dostępnych na Allegro.

**Comment by palmemd** [comment]
Dziękuje za informację
