### ISSUE TITLE
Permissions for GET /offers/listing

### ISSUE THREAD

**Issue by seemsneat** [allegro/allegro-api#4647]
Hello, we've been developing ecommerce platform for automotive parts this year and launched last month, but suddenly one day last week, we couldn't get any products from Allegro API. We found out that this endpoint is only available for verified partners and this worries us a lot, as we couldn't get verified few weeks already. My question is how could we get verified so we could continue using mentioned endpoint for getting Allegro products? 

Our ecommerce website doesn't work (https://www.adgdalys.lt/) without products, so we are stuck if we don't get an access. We have legal company, address, employees, opened bank account so we can provide entire information about us so we could get verified. 

Please let us know how can we proceed further. Thanks a lot!

Alex

**Comment by Lukasz-Zurek** [comment]
Hello. Yes, we have announced [changes in this resource](https://developer.allegro.pl/en/news/#get-offers-listing-restrictions-done) recently. An authorized seller has access only to its offers. You can search all offers using only [GET /offers/listings](https://developer.allegro.pl/documentation/#tag/Public-offer-information) - but this resource requires verification to use it. You can read more about verification [here](https://developer.allegro.pl/en/news/#public-offers-restrictions).

The verification process is out of our scope - please, contact us via a [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b) and explain why do you want to use GET /offers/listing resource. Your request should be forwarded to the verification department.

**Comment by dzoudzou3** [comment]
> Hello, we've been developing ecommerce platform for automotive parts this year and launched last month, but suddenly one day last week, we couldn't get any products from Allegro API. We found out that this endpoint is only available for verified partners and this worries us a lot, as we couldn't get verified few weeks already. My question is how could we get verified so we could continue using mentioned endpoint for getting Allegro products?
> 
> Our ecommerce website doesn't work (https://www.adgdalys.lt/) without products, so we are stuck if we don't get an access. We have legal company, address, employees, opened bank account so we can provide entire information about us so we could get verified.
> 
> Please let us know how can we proceed further. Thanks a lot!
> 
> Alex

Hi **seemsneat**, 

Som na tom rovnako ako ty. Vyriešili ste problém s prístupom k API alebo vás Allegro schválilo ako overenú aplikáciu?

**Comment by seemsneat** [comment]
@dzoudzou3 hello. Today we got a message from support that our account should be verified now. We tried to get listings, but it throws the same error status 403. Could you please check our case? Thank you.

**Comment by Lukasz-Zurek** [comment]
@adgparts55 As I can see right now - the verification of your application has been negative. Please contact us in the ongoing correspondence. The verification process is out of our scope - so unfortunately we cannot help you in this case. Altough I hope that your case will be explained properly.

**Comment by webmaestro-ua** [comment]
@seemsneat @dzoudzou3 

Hi all,
we are web studio WebMaestro.
 In our portfolio
https://webmaestro.com.ua/ua/portfolio-development/
there are a lot of successful Allegro data extracting solutions + few projects in progress related above topic:

https://restauto.com.ua/
https://motopoland.com.ua/
https://spolshy.com.ua/
https://dvizok.com.ua/
https://motoallegro.net/
https://zp-auto.com.ua/
https://autodil.com.ua/
https://autoblok.com.ua/
https://automotive.org.ua/
https://avto-plus.com.ua/
https://mrzauto.com/
https://zakroot.com/

 We are open for new challenges and cooperations.
Best Regards
