### ISSUE TITLE
[sandbox api] Brak możliwości przedłużenia access_token (unauthorized)

### ISSUE THREAD

**Issue by kkkondzi** [allegro/allegro-api#4648]
Cześć,
Kiedy próbuję przedłużyć access_token, który otrzymałem po autoryzacji sposobem Device flow, dostaję status 401 - Unauthorized. Dzieję się tak pomimo tego, że autoryzuję się dokładnie tymi samymi Client ID i Client Secret co wcześniej, które działają. Dodam, że dzieję się to na sandboxie. Ma ktoś pomysł dlaczego?

```
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=${refresh_token}' \
  -H 'Authorization: Basic YTI...Hg=' \
```

**Comment by kkkondzi** [comment]
Okej, problem rozwiązany. Wysyłałem request nie na endpoint w piaskownicy.

**Comment by Lukasz-Zurek** [comment]
Cieszę się, że udało się Tobie wyjaśnić ten problem.
