### ISSUE TITLE
Obsługa zamówień - FILLED_IN and PROCESSING

### ISSUE THREAD

**Issue by artzie92** [allegro/allegro-api#4649]
Witam,
U jednego klienta obserwując eventy i checkoutformy mam taką sytuację:
Checkout Form ma status FILLED_IN i jednocześnie CheckoutFormFulfillmentStatus PROCESSING.
Z tego co widzę status PROCESSING powinien występować na statusach READY_FOR_PROCESSING. Czy to jest jakiś błąd logiczny, czy można obsługiwać zamówienia, które jeszcze nie są na etapie READY_FOR_PROCESSING.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Status zamówienia (np. READY_FOR_PROCESSING) nie jest zależny od statusu realizacji (np. PROCESSING), chyba, że Partner korzysta z abonamentu i ma ustawioną automatyczną zmianę realizacji zamówienia np. w sytuacji, gdy dodany zostanie numer przesyłki.

Za pomocą [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT) zmienisz status realizacji zamówienia widoczny w polu **fulfillment.status**. Niezależnie od statusu zamówienia w polu **status**, w obiekcie **"checkoutForms"**.

W związku z powyższym, jeśli **checkoutform.status** jest FILLED_IN - możesz zmienić status realizacji na PROCESSING.

Więcej informacji znajdziesz w [naszym poradniku.](https://developer.allegro.pl/orders/#zmiana-statusu-realizacji-zam%c3%b3wienia)

**Comment by artzie92** [comment]
Czy to samo mogę zrobić dla statusu BOUGHT? W każdym momencie mogę taki status ustawić?

**Comment by Lukasz-Zurek** [comment]
@artzie92 Tak.
