### ISSUE TITLE
Need new method to get all SESSION data

### ISSUE THREAD

**Issue by athullive** [allegro/allegro-api#465]
If I want to get 'user-id' from SESSION currently there is no method. 

 **So I need a new method in API class.**

```
/**
	 * Method allows you to return all values saved in $_SESSION
	 * @return array()
	 */
	public function getSessionAll() {
		$this->checkConnection();
		return $this->_session;
	}
```

In this way I can use this method in application like this;

```
public static function logToAllegro($login, $password) {
		try {
			$allegro = new AllegroWebAPI('', self::getAllegroKey(), $login, $password);
			$allegro->Login();
			$allegroSessionData = $allegro->getSessionAll();
			$allegroUserLogin 	= $allegro->GetUserLogin($allegroSessionData['user-id']);
			$allegroUserId 		= $allegro->GetUserID($allegroUserLogin);
			
			$_SESSION['allegroLogin'] = $login;
			$_SESSION['allegroPassword'] = $password;
			$_SESSION['allegroId'] = $allegroUserId;
			
			echo "1";
		}
		catch(SoapFault $fault) {
			print($fault->faultstring);
		}
	}
```

**Comment by athullive** [comment]
To use  _`GetUserID()`_ 

I need  _`Login`_ 

To get  _`Login`_ 

I should use  _`GetUserLogin()`_ 

To use  _`GetUserLogin()`_ 

I need  _`user-id`_ 

To get  _`user-id`_    => I should get it from SESSION, for this there is no method currently.

**Comment by MaciejPotepa** [comment]
Sadly, you can't obtain user-id trough API. It's not available.

**Comment by athullive** [comment]
But if I add this method to the class,

public function getSessionAll() {
		$this->checkConnection();
		return $this->_session;
	}

User-id is stored in session.

It’s possible right?  Am I doing something wrong?

**Comment by MaciejPotepa** [comment]
I'm sorry but we support WebAPI and REST API only on protocol level - XML/json files. 

We do not provide technical support within programming languages.

**Comment by athullive** [comment]
Ok thank you.
