### ISSUE TITLE
Problem z utworzonym produktem.

### ISSUE THREAD

**Issue by mb88x** [allegro/allegro-api#4650]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Comment by Lukasz-Zurek** [comment]
Odpowiedzi udzieliłem w [Twoim nowym wątku](https://github.com/allegro/allegro-api/issues/4651#issue-930706315).
