### ISSUE TITLE
Problem z produktem

### ISSUE THREAD

**Issue by mb88x** [allegro/allegro-api#4651]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,

w procesie produktyzacji tworzę produkt i podpinam go pod aukcję, sam proces kończy się z powodzeniem. Jednak nazwa produktu który jest stworzony jest zbyt ogólna i nie pasuje do wymagań, mimo, że nazwa którą podaje w modelu jest taka jak w aukcji np.:

Etui z klapką REDMI 9A wielokolorowy

a sama aukcja ma tytuł:

ETUI DO XIAOMI REDMI 9A KABURA BE UNIQUE +SZKŁO 9H
Czy jest możliwość aby nazwa produktu była bardziej szczegółowa? Czy mogę jakoś sam wymusić poprawną nazwę ? Ewentualnie czy możliwa jest edycja produktu?

 TraceId: 9f2f0e54a59362d2

**Comment by Lukasz-Zurek** [comment]
Nazwę produktu tworzymy automatycznie na podstawie pobranych parametrów, lub na podstawie wartości podanej w polu **name**. W propozycji produktu podałeś kolor: granatowy, dlatego na tej podstawie utworzyliśmy produkt o nazwie "Etui z klapką Galaxy A41 granatowy".

Nie możesz edytować produktu. Możesz jednak zgłosić do nas błąd w produkcie. Skorzystaj w tym celu z linka: https://allegro.pl/offer/product/report/id_produktu - id_produktu podmień na otrzymany wcześniej **product.id**.

**Comment by mariuszborys** [comment]
Witam,
dziękuję za odpowiedź.
Od czego zależy to czy nazwa jest tworzona z parametrów czy z pola name? Jak nie podam parametrów to będzie brana pod uwagę wartość z pola name?

**Comment by mb88x** [comment]
Witam,
dziękuję za odpowiedź.
Od czego zależy to czy nazwa jest tworzona z parametrów czy z pola name? Jak nie podam parametrów to będzie brana pod uwagę wartość z pola name?

**Comment by Lukasz-Zurek** [comment]
> Jak nie podam parametrów to będzie brana pod uwagę wartość z pola name?

Tak, w tej sytuacji powinna być brana pod uwagę wartość z pola **name**. Proces ten zależny jest jednak zarówno od podanych wartości parametrów, jak i od kategorii.

**Comment by mb88x** [comment]
Witam,
przy braku parametrów dostaję taki komunikat:
"{\"errors\":[{\"code\":\"UnableToCreateProductWithoutAllRequiredParametersException\",\"message\":\"Unable to create product without proper values in all required parameters: [Kod producenta, Producent, Przeznaczenie, Kolor, Typ]\",\"details\":null,\"path\":\"parameters\",\"userMessage\":\"Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Kod producenta, Producent, Przeznaczenie, Kolor, Typ]\"}]}"

Jak w takim razie wymusić stworzenie produktu z własną nazwą?

**Comment by Lukasz-Zurek** [comment]
Komunikat jest prawidłowy, ponieważ musisz podać wszystkie obowiązkowe parametry. Wspomniałem wcześniej o zależnościach w postaci wartości parametrów i kategorii. Nazwa będzie jednak zawsze generowana automatycznie przez nasz system. Tym bardziej nie jestem w stanie wskazać skutecznego działania. Analizując powyższy przypadek, można śmiało stwierdzić, że w tej kategorii, dla tego produktu, system do nazwy bierze pod uwagę parametr "kolor".

**Comment by mb88x** [comment]
Czyli mam rozumieć, że w przypadku tej kategorii nie ma możliwości utworzenia własnej nazwy produktu? Nie ma też możliwości edycji utworzonego produktu? Nazwa zawsze będzie generowana przez system?

**Comment by Lukasz-Zurek** [comment]
Nasz system zawsze generuje nazwę produktu w sposób automatyczny. Możesz wpłynąć na kształt nazwy poprzez podawane przez Ciebie wartości parametrów - jednakże jak już wspomniałem wcześniej - nie jestem w stanie wskazać skutecznego działania. 

Dodam, że edycja utworzonego produktu nie jest możliwa.
