### ISSUE TITLE
Stronicowanie i pobieranie całej oferty w pętli.

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#4652]
Chce pobrać wszystkie oferty: https://api.allegro.pl/sale/offers?limit={0}&offset={1} Potrzebuję określić warunek wyjścia z pętli, który wybrać? Aktualnie wykorzystuję totalCount i obliczam ile jeszcze ofert zostało do pobrania ale szukam czegoś prostszego. Może pobierać oferty do puki nie zostanie zwrócona zerowa zawartość strony, czyli sprawdzam Count tablicy ofert.

**Comment by kfijalko** [comment]
W API nie da się iść na skróty. Musisz sprawdzać totalCount, musisz sprawdzać zwracane kody http, jeżeli masz dużo ofert (przy małej liczbie pewnie też) to musisz założyć "jakąś" tolerancję na zgodność liczby pobranych z totalCount.
Dane ofert są propagowane na wiele serwerów i ich stan jest na bieżąco synchronizowany. Co jednak oznacza, że możesz trafić na jakieś rozbieżności.

**Comment by MartaNowaczyk** [comment]
Limit nie może być równy 0. 
To od ciebie zależy jak wykorzystasz parametry:
- limit, który określa liczbę ofert na liście, przyjmuje wartości od 1 do 1000,
- offset by wskazać miejsce, od którego chcesz pobrać kolejną porcję danych (min. 0) 
Tak czy inaczej musisz uzależnić pobieranie ofert od "totalCount".

**Comment by pkrzemo** [comment]
Ustawiasz sobie zmienną np. **limit**=100
Ustawiasz sobie zmienną np. **offset**=0
Ustawiasz sobie zmienną np. **pobranych**=**limit**

i teraz pętelka:
 while( **pobranych**==**limit**)
{
  pobranie danych: https://api.allegro.pl/sale/offers?limit={0}&offset={1} ; **limit,offset**
  ustawiasz: **pobranych**=ilość faktycznie pobranych ofert w powyższym żądaniu
  ustawiasz: **offset**=**offset**+**pobranych**
}
i samo się przerwie gdy pobierzesz wszystko.
Czyli warunkiem wyjścia jest pobranie w danym żądaniu mniejszej ilości ofert niż ustawiony w nim limit.
