### ISSUE TITLE
Przedłużenie ważności tokena

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#4654]
Witam,
Czy jeśli dodam konto do aplikacji A (które ma dostęp do danych publicznych) mogę odświeżyć token aplikacją B (które ma dostęp do danych publicznych)?

**Comment by MartaNowaczyk** [comment]
Nie możesz, bo zgodę otrzymuje konkretny Client ID.

**Comment by gsti** [comment]
Dziękuję za szybką odpowiedź.
