### ISSUE TITLE
Implementacja  api.allegro.pl w Delphi

### ISSUE THREAD

**Issue by FlySoftpl** [allegro/allegro-api#4656]
Witam,
czy mogę prosić o pomoc w sprawie wykonania pierwszych kroków połączenia
się z api.allegro.pl z poziomu Delphi? Czy może ktoś z Państwa udostępnić jakieś przykłady kodu?

z góry dziękuję za każdą wskazówkę
Sławek

**Comment by hahyes** [comment]
Nie jestem programistą Delphi, jednakże znalazłem coś takiego:
np. https://awesomeopensource.com/project/fabriciocolombo/delphi-rest-client-api

Wątpię, abyś znalazł gotową bibliotekę do tego API. Musisz pisać wszystko ręcznie z pomocą takiej biblioteki jak powyżej. Kwestia odpowiedniego wypełnienia zapytania i powinno śmigać.

**Comment by FlySoftpl** [comment]
Dziękuję za odpowiedź. Właśnie o to wypełnianie zapytań mi chodzi. Korzystam z Delphi 10.3 i mam komponenty do obsługi RestAPI. Był kiedyś na tym form podobny wątek https://github.com/allegro/allegro-api/issues/1850 ale niestety nie było tam publicznie podanego rozwiązania. Próbuję konstruować zapytanie tak jak tam było podane:

const client_secret = 'xxx';
client_id = 'xxx';
var Base64: TBase64Encoding;
begin

Base64 := TBase64Encoding.Create(5000,'');
RestClient1.BaseURL := 'https://allegro.pl';
RestRequest1.Resource := 'auth/oauth/device';
RestRequest1.AddParameter('Authorization','Basic '+ Base64.Encode( client_id+':'+client_secret ), pkHTTPHEADER);
RestRequest1.AddParameter('Content-Type','application/x-www-form-urlencoded', pkHTTPHEADER);
RestRequest1.AddParameter('client_id',client_id, pkREQUESTBODY);
RestRequest1.Execute;

i mam dokładnie taki sam objaw ja użytkownik autornet czyli bład 401.
Mam oczywiście zarejestrowaną aplikację typu device_code i odpowiednie parametry Client ID oraz Client Secret podawałem w tym zapytaniu. Próby wykonywałem zarówno na środowisku testowym jak również na produkcyjnym zmieniając oczywiście parametry aplikacji zarejestrowanej dla danej platformy. Zawsze efekt ten sam czyli błąd 401.

Bardzo proszę o jakieś wskazówki gdzie popełniam błąd.

**Comment by AureliuszBrussy** [comment]
@FlySoftpl czy możesz podać przykładowy kod błędu, który otrzymałeś w odpowiedzi?

**Comment by FlySoftpl** [comment]
Te kody są różne. Przy każdym wykonaniu zapytania jest inny kod np
Numer błędu: cc8e388f524f5b0f
Numer błędu: 97e52f0b0f3d602f
Numer błędu: f4a4b8afbf91d4fb

**Comment by AureliuszBrussy** [comment]
@FlySoftpl wygląda to na problem z prawidłowym zakodowaniem wartości w parametrze Authorization. Sprawdź poprawność kodowania: spróbuj np. w miejsce `Base64.Encode( client_id+':'+client_secret )` wstawić ciąg wygenerowany np. w tym [narzędziu](https://www.base64encode.org/) (nie zapomnij o znaku ":" między wartościami).

**Comment by FlySoftpl** [comment]
Zakodowałem zgodnie z przekazaną informację wskazanym narzędziem client_id oraz client_secret wraz ze znakiem dwukropka i wstawiłem go w kodzie w miejsce Base64.Encode( client_id+':'+client_secret )

Ale nadal to nic nie zmienia. Po tej modyfikacji wykonałem 3 próby połączenia i otrzymałem przed chwilą takie kody błędów: 
40c79526234d7121
1cab542a27ed132
f91c348d603c2bfe

**Comment by AureliuszBrussy** [comment]
@FlySoftpl podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełne zapytanie (z uzupełnionymi danymi) jakie wysyłasz. W zgłoszeniu zaznacz, że dane są potrzebne do zgłoszenia numer #4656 na GitHubie.

**Comment by FlySoftpl** [comment]
Zgłoszenie przez formularz zostało wysłane przed chwilą.

**Comment by AureliuszBrussy** [comment]
@FlySoftpl dziękuję za dane przesłane w formularzy, kodowanie jest prawidłowe. Sprawdź, czy podczas wykonywania requestu znak spacji po 'Basic' nie jest zamieniany na encje, np '%20' lub nie jest całkowicie pomijany.

**Comment by FlySoftpl** [comment]
Zmodyfikowałem kod i teraz autoryzacja działa. Poniżej kod po zmianach - może komuś się przyda. Bardzo dziękuję za pomoc.

   with TBase64Encoding.Create(0) do
  begin
    sEndodedAuth:= Encode(client_id + ':' + client_secret);
    Free;
  end;

  FMain.Restrequest1.Client:= RestClient1;
  FMain.RestClient1.BaseURL := 'https://allegro.pl';
  FMain.RestRequest1.Method := TRESTRequestMethod.rmPOST;
  FMain.RestRequest1.Resource := 'auth/oauth/device';
  FMain.RestRequest1.AddParameter('Authorization', 'Basic ' +  sEndodedAuth,
    TRESTRequestParameterKind.pkHTTPHEADER, [TRESTRequestParameterOption.poDoNotEncode]);
  RestRequest1.AddParameter('Content-Type','application/x-www-form-urlencoded',
    TRESTRequestParameterKind.pkHTTPHEADER, [TRESTRequestParameterOption.poDoNotEncode]);
  RestRequest1.AddParameter('client_id', client_id, TRESTRequestParameterKind.pkGETorPOST);
  RestClient1.ContentType:='application/x-www-form-urlencoded';
  FMain.RestRequest1.Execute;
