### ISSUE TITLE
lista ofert - api vs www

### ISSUE THREAD

**Issue by yd6d7hhds** [allegro/allegro-api#4658]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W jaki sposób pobrać poprzez api listę ofert (https://api.allegro.pl/offers/listing?phrase=elementarz) po szukanym ciągu tak aby była zgodna z wynikami prezentowanymi na stronie (https://allegro.pl/listing?string=elementarz).
Mimo sortowania w obu przypadkach po trafności otrzymuję różne wyniki.

**Comment by MartaNowaczyk** [comment]
Nie można zagwarantować tych samych wyników, co nie oznacza, że będą one niepoprawne. Po prostu wyszukiwanie po trafności (wartość domyślna) jest inna dla każdego użytkownika. Poza tym, w danym momencie, może ktoś dodać jakąś ofertę, jakaś się wyprzeda i np. na stronie tę ofertę już zobaczysz, a przez API jeszcze nie lub odwrotnie. Poza tym po API nie zobaczysz ofert sponsorowanych.
