### ISSUE TITLE
"Nie podano wartości dla parametru..." przy próbie zmiany ilości sztuk

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4659]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Poniżej trace-id z próbą zmiany tylko ilości sztuk w istniejącej ofercie:
107a12bee7cfd0d9
Dostajemy "Nie podano wartości dla parametru Wydawnictwo (223541)."

Wygląda na to, że problem z #4615 powrócił. Tak jak poprzednio takich przykładów mamy mnóstwo.

Pozdrawiam

**Comment by hahyes** [comment]
#4660 
Podpinam się, u mnie tworzenie szkiców oferty nie funkcjonuje.

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisany problem.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i próbowaliście podać parametr słownikowy jako wartość, a nie jako id. Widzimy, że zaktualizowaliście już ofertę.

**Comment by hahyes** [comment]
> Sprawdziliśmy i próbowaliście podać parametr słownikowy jako wartość, a nie jako id. Widzimy, że zaktualizowaliście już ofertę.

Skoro użyto liczby mnogiej, muszę poprawić.
Nie, ja nie podawałem parametru słownikowego jako wartość. Nie mam nawet takiej możliwości w swojej aplikacji, żeby coś takiego zrobić. Zresztą niczego nie aktualizowałem, po prostu błąd przestał występować. 

W każdym razie problem zażegnany jak dla mnie, ale nieładnie tak generalizować.
