### ISSUE TITLE
Powrót błędu z wartościami typu "inna"

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4660]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,
dosłownie chwilę temu zostałem przy wystawianiu zalany logami o błędzie:
```
Podana wartość parametru Marka (3786) nie istnieje w słowniku. 
Trace-Id: 2f6f342e9e39be83

Podana wartość parametru Marka (10563) nie istnieje w słowniku. 
Trace-Id: 2f6f342e9e39be83

Podana wartość parametru Rozmiar (129302) nie istnieje w słowniku.
Trace-Id: 135048aa973c19ed

Podana wartość parametru Marka (7108) nie istnieje w słowniku.
Trace-Id: 2dd3d8394853a94c

... mam takich pareset
```

W każdym razie, z przeanalizowanych przykładów wygląda to ponownie na błąd z wartością `ambigiousValueId` czyli wartością słownikową typu `inny`. Sprawdzając parametry kategorii tym razem znajduje w słowniku tą samą wartość podaną w zapytaniu tworzenia szkicu oferty.

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisany problem.

**Comment by MartaNowaczyk** [comment]
Tutaj namierzyliśmy problem po naszej stronie. Analizujemy jeszcze przyczynę, żeby uniknąć problemu w przyszłości.

**Comment by hahyes** [comment]
Zamykam wątek, bo problem już nie występuje od kilku dni. :)

**Comment by hahyes** [comment]
Problem znowu daje o sobie znać, Na razie znalazłem dwa przypadki.

```
Nie podano wartości dla parametru Materiał wykonania (18122).
Trace-Id: 2611330ab6b2f39d

Nie podano wartości dla parametru Materiał wykonania (18122).
Trace-Id: d4247d4c91715e39
```

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem parametry dostępne w kategorii 306837 i widzę, że dla Materiał wykonania 18122 nie ma dostępnej wartości "18122_341785" - jest za to "229541_341785".

**Comment by hahyes** [comment]
> Sprawdziłem parametry dostępne w kategorii 306837 i widzę, że dla Materiał wykonania 18122 nie ma dostępnej wartości "18122_341785" - jest za to "229541_341785".

Rzeczywiście, końcówka mi się zgadzała więc myślałem, że wszystko się zgadzało. Zamykam temat, dziękuję za sprawdzenie.
