### ISSUE TITLE
sandbox - wystawianie oferty sprzedaży

### ISSUE THREAD

**Issue by mtumtu** [allegro/allegro-api#4662]
Przy próbie wystawienia oferty (Moje oferty -> Dodaj nową) otrzymuję:

Unable to connect

Firefox can’t establish a connection to the server at staging-lokalnie.allegrogroup.com.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by AureliuszBrussy** [comment]
Skorzystaj proszę z alternatywnego linku - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie. Powinieneś zostać przekierowany na prawidłowy formularzy wystawiania.

**Comment by mtumtu** [comment]
Niestety, z tego linku, po wybraniu kategorii mam taki efekt:

![image](https://user-images.githubusercontent.com/47525595/124257862-165ae900-db2d-11eb-9eaf-d1a5db1a60f8.png)

**Comment by AureliuszBrussy** [comment]
Nie udało mi się powtórzyć tego błędu. Czy gdy korzystasz np. z innej przeglądarki - problem się powtarza?

**Comment by nowyyy31** [comment]
Mam to samo
![Zrzut ekranu 2021-07-02 132800](https://user-images.githubusercontent.com/86833897/124268304-a010b380-db39-11eb-9422-4a63d91f29f8.jpg)

**Comment by mtumtu** [comment]
Tak w Chrome mam to samo

**Comment by AureliuszBrussy** [comment]
@nowyyy31 Twoje konto nie jest w pełni aktywne. Aby w pełni je aktywować - prześlij jeszcze dwa dowolne pliki w zakładce [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php). 

@mtumtu podaj proszę login albo adres e-mail swojego konta.

**Comment by mtumtu** [comment]
login: TestLosia

**Comment by AureliuszBrussy** [comment]
@mtumtu nie ma takiej potrzeby - aktywowałem Twoje konto. Sprawdź proszę, czy aktualnie możesz wystawić ofertę.

**Comment by mtumtu** [comment]
OK, chyba się udało. Dziękuję za pomoc
