### ISSUE TITLE
Problem z wystawieniem aukcji allegro porzez IdoSell - New offer description is required.

### ISSUE THREAD

**Issue by Dleszczyn** [allegro/allegro-api#4663]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [Z ] inny

:beetle: **Opis**

Witam,

Od wczoraj próbuje wystawić aukcję na allegro poprzez panel sklepu IdoSell, ale niestety za każdym razem pojawia mi się błąd:
![prbolem](https://user-images.githubusercontent.com/86827418/124250374-2078e980-db25-11eb-8d55-cbe3927e05fd.JPG)

załączniki request i response są puste.
W jaki sposób mogę rozwiązać ten problem?

**Comment by AureliuszBrussy** [comment]
Komunikat błędu wskazuje na brak opisu w ofercie. Abym mógł dokładniej to sprawdzić - potrzebowałbym pełen request i response. Ewentualne problem z pobraniem plików zgłoś do supportu narzędzia, z którego korzystasz.

**Comment by Dleszczyn** [comment]
Sprawa wyjaśniona: Edytowałem opis aukcji przy pomocy narzędzia WYSIWYG, który wrzucał niedozwolone znaczniki HTML.
Dla potomnych: zawsze używajcie edytora HTML.
