### ISSUE TITLE
Brak możliwości edycji danych przesyłki po jej anulowaniu gdy była dodana przez API

### ISSUE THREAD

**Issue by maniek5m90** [allegro/allegro-api#4664]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

Przesyłka poprzez API definiowana jest w następujący sposób:
1. Wysyłany jest request:
[https://api.{environment}/parcel-management/parcel-create-commands/{commandId}](url)
gdzie commandId jest automatycznie tworzone.
2. Sprawdzany jest status utworzenia:
[https://api.{environment}/parcel-management/parcel-create-commands/{commandId}](url)
Status jest "**SUCCESS**"
3. Odczytywany jest waybill (items.waybill)
[https://api.{environment}/parcel-management/parcels/{parcelId}](url)
gdzie parcelId zostało pobrane podczas odczytu statusu. 
4. Dodawany jest numer śledzenia przesyłki
[https://api.{environment}/order/checkout-forms/{id}/shipments](url)
gdzie {id} jest identyfikatorem zamówienia (wykorzystując waybill poprzednio odczytany)
5. Weryfikowane jest dodanie:
https://api.{environment}/order/checkout-forms/{id}/shipments

Wszystkie powyższe kroki wykonują się pomyślnie. Jednak na [https://wysylam.allegro.pl/konto/zamowienia](url) zamówienie nie ma linku do przesyłki, to znaczy w Zamówienia/Przesyłka widnieje napis "Allegro Kurier DPD " a nie link do przesyłki.

Dodatkowo anulowanie przesłki w "Zamówione przesyłki" powoduje poprawne przeniesienie do "Dodane przesyłki". Jednak nie ma możliwości edycji, mianowicie podczas próby zapisania, walidacja zwraca "Proszę poprawić pola zaznaczone na czerwono" gdzie jedynym polem na czerwono jest wybór przewoźnika i nie można wybrać żadnego:
![image](https://user-images.githubusercontent.com/86827704/124251982-cda03180-db26-11eb-82d1-0e578684bd24.png)

**Comment by AureliuszBrussy** [comment]
Ze zgłoszenia wynika że wszystkie kroki w API przebiegły pomyślnie. Problemy dotyczące https://wysylam.allegro.pl/ zgłoś proszę poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by maniek5m90** [comment]
Ok
