### ISSUE TITLE
Aktualizacja stanów magazynowych

### ISSUE THREAD

**Issue by 1973darek** [allegro/allegro-api#4665]
Występuje problem: 
 - [X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Pracujemy na Comarch Opitma ERP, mamy zintegrowany e-Sklep Comarch z Allegro, od wczoraj mamy problem z synchronizacją  stanów magazynowych między esklepem a allegro. W ogóle sklep pomimo poprawnych ilości nie przekazuje ich do Allegro. Asysta Comarch nie widzi problemu z ich strony.

**Comment by AureliuszBrussy** [comment]
Problem powinien zostać wyjaśniony przez support aplikacji, z której Państwo korzystają. Jeżeli obserwują oni problem z naszym API - mogą zgłosić to bezpośrednio do nas. Potrzebujemy konkrentych danych, aby zweryfikować problem m.in. czy API Allegro zwraca jakieś błędy, w przypadku jakich konkretnie requestów itp.
