### ISSUE TITLE
Konto-Web API

### ISSUE THREAD

**Issue by xLipa** [allegro/allegro-api#4666]
Występuje problem: 
 - [ ] z metodą WebAPI
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X ] z logowaniem lub autoryzacją
 - [ ] [błędy na stronie WebAPI](https://allegro.pl/webapi)
 - [ ] inny

:beetle: **Opis**

2.07.2021, 15:00

Moje konto zarejestrowane pod adresem lipinskijulian1@gmail.com ma wszystkie niezbędne rzeczy do uzyskania Web API, co zostało potwierdzone przez pomoc Allegro jednak pomimo tego kiedy wchodzę na stronę wciąż nie mogę go wygenerować.

**Comment by Aryak2099** [comment]
Web Api nie jest już dawno wspierane

**Comment by MartaNowaczyk** [comment]
Z tego co widzę udało się dodać aplikację dla REST API Allegro na podanym koncie.
