### ISSUE TITLE
Błąd: 403 Forbidden przy pobieraniu: offers/listing

### ISSUE THREAD

**Issue by KubinkiewiczDawid** [allegro/allegro-api#4667]
Występuje problem:
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

**Request sent:**

D/OkHttp: --> GET https://api.allegro.pl/offers/listing?category.id=5
    Accept: application/vnd.allegro.public.v1+json
    Authorization: Bearer XXXXXXXXXXXXXXXX
    --> END GET

**Msg received:**

D/OkHttp: <-- 403 Forbidden https://api.allegro.pl/offers/listing?category.id=5&searchMode=REGULAR&offset=0&limit=60&sort=relevance&fallback=true (115ms)
D/OkHttp: date: Mon, 05 Jul 2021 05:28:44 GMT
    {"errors":[{"code":"VerificationRequired","message":"Access is denied. Verification is required.","details":null,"path":null,"userMessage":"Access denied. Access available only for verified applications."}]}

jeżeli chodzi o pobieranie kategorii to pobierają się one prawidłowo

autoryzacje uzyskuje za pomocą:
https://allegro.pl/auth/oauth/token?grant_type=client_credentials

Z tego co się orientuję to offers/listing jest publiczne więc żeby pobrać z niego dane wystarczy autoryzacja typu Client_credentials flow

**Comment by MartaNowaczyk** [comment]
Dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) mają tylko zweryfikowane aplikacje. Informowaliśmy o tym w [komunikatach](https://github.com/allegro/allegro-api/issues/4566). Informację znajdziesz też na [naszej stronie](https://developer.allegro.pl/listing/) i w [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListing).

**Comment by KubinkiewiczDawid** [comment]
Rozumiem że aby zweryfikować aplikację należy napisać do was poprzez formularz?

**Comment by KubinkiewiczDawid** [comment]
> Dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) mają tylko zweryfikowane aplikacje. Informowaliśmy o tym w [komunikatach](https://github.com/allegro/allegro-api/issues/4566). Informację znajdziesz też na [naszej stronie](https://developer.allegro.pl/listing/) i w [dokumentacji](https://developer.allegro.pl/documentation/#operation/getListing).

Rozumiem że aby zweryfikować aplikację należy napisać do was poprzez formularz?

**Comment by MartaNowaczyk** [comment]
Dokładnie tak.

**Comment by KubinkiewiczDawid** [comment]
dziękuję bardzo

**Comment by dzoudzou3** [comment]
Cześć.
czy udało ci się uzyskać dostęp?

**Comment by dzoudzou3** [comment]
> dziękuję bardzo

Cześć.
czy udało ci się uzyskać dostęp?
