### ISSUE TITLE
Getting all information about offers

### ISSUE THREAD

**Issue by morozov312** [allegro/allegro-api#4669]
After I get a list of offers using GET/offers/listing, can I get more detailed information about the offer (eg description) based on its ID?

**Comment by MaciejFrackowiak** [comment]
No, you will not receive an offer description using GET /offers/listing. Only if you are a seller of an offer, you can retrieve its offer description using [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).

**Comment by webmaestro-ua** [comment]
> After I get a list of offers using GET/offers/listing, can I get more detailed information about the offer (eg description) based on its ID?

Hi all,
we are web studio WebMaestro.
 In our portfolio
https://webmaestro.com.ua/ua/portfolio-development/
there are a lot of successful Allegro data extracting solutions + few projects in progress related above topic:

https://restauto.com.ua/
https://motopoland.com.ua/
https://spolshy.com.ua/
https://dvizok.com.ua/
https://motoallegro.net/
https://zp-auto.com.ua/
https://autodil.com.ua/
https://autoblok.com.ua/
https://automotive.org.ua/
https://avto-plus.com.ua/
https://mrzauto.com/
https://zakroot.com/

 We are open for new challenges and cooperations.
Best Regards
