### ISSUE TITLE
Wysyłka w ciągu - pole formularza sprzedaży nie jest dostępne w wybranej kategorii.

### ISSUE THREAD

**Issue by piotrkomisarski** [allegro/allegro-api#467]
Na testowym API pobieram sobie listę pól dla kategorii 258939.

Jedna z nich to FID 340 - wysyłka w ciągu.

Gdy nie dodaję tego pola podczas wystawiania aukcji to jest błąd: 
Podaj czas wysyłki. Czas wysyłki nie może być pusty.

<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_CONSTRAINT_VIOLATION_EXCEPTION_REQUIRE_ESTIMATED_SHIPPING_TIME</faultcode><faultstring>Podaj czas wysyłki. Czas wysyłki nie może być pusty.</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

Ale gdy dodaję to pole to jest też błąd:
Wysyłka w ciągu - pole formularza sprzedaży nie jest dostępne w wybranej kategorii.
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>ERR_FULFILLMENT_TIME_NOT_AVAILABLE_FOR_CATEGORY</faultcode><faultstring>Wysyłka w ciągu - pole formularza sprzedaży nie jest dostępne w wybranej kategorii.</faultstring><faultactor>doNewAuctionExt - Fulfillment time is not available for the selected category.</faultactor></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by MaciejPotepa** [comment]
Cześć

Dziękuję za zgłoszenia. Badamy sprawę

**Comment by Onixarts** [comment]
To samo w innych kategoriach, np. 1144.

**Comment by MasterSlynx** [comment]
To :point_up_2:
Dodatkowo nie działa prawidłowo metoda 'doGetItemFields'. 
Nie zwraca wartości dla pól specyficznych dla danej kategorii. Kilka dni temu działało prawidłowo (kategoria 110902, pole 48378, oferta 6205423166).

Kiedy będzie coś wiadomo? 
Nie można prawidłowo testować ofert pod kategorie z których korzysta klient. Środowisko testowe jest mocno potrzebne (zwłaszcza przed oddaniem projektu klientowi) :fearful:

**Comment by MaciejPotepa** [comment]
@MasterSlynx przepraszam za problemy jakie napotykasz. 

Podziel się proszę requestem i responsem w XML'u. Zgłoszę problem do odpowiedniego zespołu i postaramy się to jak najszybciej rozwiązać.

**Comment by MasterSlynx** [comment]
Wrzucam na zewnętrzny hosting, bo oferty z obrazkami więc w formie tekstu trochę duże:
Request [https://files.fm/f/yfhx2nv5](https://files.fm/f/yfhx2nv5)
Response [https://files.fm/f/4ay4gqz6](https://files.fm/f/4ay4gqz6)

(brak pola 47020)
Ten problem w ramach testu można łatwo wyeliminować ręcznie poprawiając dane pole (mechanizm który pisze klonuje daną ofertę, dlatego musi zawierać wszystkie oryginalne dane), ale problem wspomniany wcześniej, czyli "pole formularza sprzedaży nie jest dostępne w wybranej kategorii" całkowicie blokuje możliwość testowania i wystawiania oferty w danej kategorii, więc to jest priorytetem.
Tutaj request/response dla wspomnianego wcześniej błędu
[https://files.fm/f/c2hzrchs](https://files.fm/f/c2hzrchs)

I jeszcze jedno pytanie. Ostatnio bardzo często przy logowaniu rzuca błędem "Niepoprawna wersja kategorii lub pól sprzedaży. Proszę sprawdzić lokalne wersje i uaktualnić oprogramowanie!'". U mnie w programie jednorazowo pobiera się kategorie, klucz wersji, typy płatności, etc (wszystkie dane konfiguracyjne), ale to ciągła zmiana klucza wersji sprawia, że w co drugim logowaniu jest błąd i doszło do tego, że non stop aktualizuje sam klucz wersji.
Czy to normalne? Tak samo działa środowisko produkcyjne? Spodziewałem się, że aktualizacje klucza wersji + kategorii będzie trzeba robić raz/dwa w miesiącu 😕

**Comment by MasterSlynx** [comment]
Sprawdzałem też dla innych kategorii (termometry, etc.), ale nic z tego, dalej "pole formularza sprzedaży nie jest dostępne w wybranej kategorii". Nie sądzę by to był problem po mojej stronie. Wcześniej działało prawidłowo, choć wprowadzałem u siebie zmiany i poprawki to raczej nie spowodowałbym tak dziwnego rezultatu. Póki co jestem dosłownie zablokowany, jako, że w ogóle nie mogę wystawiać ofert.

Czekam na jakieś informacje lub poprawkę. Temat miał być zakończony do końca tygodnia, ale widać jeszcze sobie poczeka... 😩

**Comment by MaciejPotepa** [comment]
@piotrkomisarski @MasterSlynx @Onixarts 
Problem z FIDem 340 nie powinien już występować. 

@MasterSlynx Sprawę z doGetItemFields badamy i naprawimy problem. 

Żebyś nie marnował czasu, testuj na produkcji, w razie czego zwrócimy naliczone opłaty. Dam znać jak rozwiążemy problem na Sandboxie.

**Comment by MasterSlynx** [comment]
Problem na sandbox rozwiązany już od ok. 20 minut. Wystawiłem już kilka ofert bez problemu.

**Comment by MaciejPotepa** [comment]
@MasterSlynx Dzięki za informację!
