### ISSUE TITLE
Ostatnio dodane Oferty

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#4670]
Witam,
czy jest możliwość pobrania 10 ostatnio dodanych ofert z mojego konta (np. wg daty dodania)?

PS: mam 50 000 ofert na koncie także pobieranie wszystkich odpada.

**Comment by MaciejFrackowiak** [comment]
Listę swoich ofert ([GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)) możesz sortować wg ceny, liczby sprzedanych przedmiotów lub liczby dostępnych przedmiotów. Sposby sortowania wraz z przykładami opisujemy w [poradniku](https://developer.allegro.pl/my_offers/#sortowanie).

**Comment by Radeq** [comment]
@PiotrFerenc - jest jeszcze dziennik zdarzeń (OFFER_ACTIVATED) ale tam też są oferty wznowione i tylko z ostatnich 24h

https://developer.allegro.pl/my_offers/#dziennik-zdarzeń-w-ofertach-sprzedawcy

**Comment by PiotrFerenc** [comment]
@Radeq sprytnie! dzięki
