### ISSUE TITLE
API potwierdzenie

### ISSUE THREAD

**Issue by adgparts55** [allegro/allegro-api#4671]
Dzien dobry kolejny raz. Pisalem wam na zeszlym tygodniu na temat API. Rozumiem, ze regulamin nie pozwala nam uzyskac aktywacji api. Ale moze jeszcze raz opisze wam caly temat. Problem jest w tym, ze pol roku temu chcialem otwozyc strone internetowa, gdzie beda brac produktu z allegro.pl z kategorii czesci samochowe. Wlasnie moja strona internetowa robila firma : https://seemsneat.com , oni wlasnie zrobili strona internetowa adgdalys.lt , teraz problem polega na tym, ze allegro nam nie daje pozwolenia api, bez tego pozwolenia nasz biznes stoji na miejscu. Zrozumcie nas prosze, ze nasza firma tylko dziala jak 3 miesiace, to jest nie realna na terazniejszym kroku naszej pracy uzyskac 99% pozytywnych opinii i jeszcze miec 100 partnerow. Inne firmy przez 5 lat takiego nie moga uzyskac. Nastepny moment to jest strona internetowa srotas24.lt dla nich wy daliscie api podlaczenia, ja w tej firmie pracowalem , i mam duzo doswiadczenia z tym wszystkim. Teraz pytanie u mnie polega na tym, czy wy macie jakies obawy na temat naszej firmy czy w czym jest problem aby uzyskac api podlaczenia, ja wam wszystko reprezentowalem, ze chcemy pracowac, bardzo duzo inwestowalismy w nasz biznes, ktory po prosto stoji na miejscu, u nas jest magazyn w suwalkach, gdzie bedzie nasz pracownik przyjmowac paczki zamowionych czesci samochodowych, nastepnie my to sprowadzamy na Litwe, i sprzedajemy innym kupujacym, bussines to bussines. A panstwo nam teraz nie moze udzielic API podlaczen, ze wzgledu, ze po prosto jestemy nowa firma, tak ale my chcemy z wami wspolpracowac najmniej przez 10 lat, i beda u nas dobre opinie itd. Moze mozemy podpisac jakas umowe, ze nie naszkodzimy, ze po prosto na kozysc naszej firmy i naszego biznesu wy nam dacie pozwolenia na kozystania z API , i wszyscy bedziemy zadowoleni. Przeszlismy pelna weryfikacje firmy, wszystkie dokumenty wam wyslalismy, wszystko jest ok z nami, naprawda potrzebujemy tych podlaczen, zrozumcie nas prawidlowo zainwestowalismy co najmniej 20 tysiecy euru, a teraz stojimy na miejscu, moze jest jakies rozwiazanie? Mozemy przyjechac do waszej siedziby i zalatwic umowe. Dziekuje serdeczne wam jeszcze raz. Prosze to przejzec jeszcze raz...

**Comment by adgparts55** [comment]
nie dopisalem, ze jestem uzytkownikiem na allegro adgparts55, nasz IT specjalitsa zrobil i client code, i secret code, wszystko mamy to zrobione, jedynie, ze po prosto potrzebujemy z waszej strony potwierdzenia dzialalnosci... on wam juz przed tym kiedys pisal: https://github.com/allegro/allegro-api/issues/4647#issuecomment-868398221

**Comment by MaciejFrackowiak** [comment]
Jak wspominaliśmy w poście #4647 weryfikacja dostępu do zasobu GET /offers/listing jest całkowicie poza nami. Odbywa się w dziale weryfikacji, który jest jedyną komórką weryfikacyjną. Dlatego wszelkie wątpliwości proszę wyjaśniaj bezpośrednio z nimi.

**Comment by dzoudzou3** [comment]
> Dzien dobry kolejny raz. Pisalem wam na zeszlym tygodniu na temat API. Rozumiem, ze regulamin nie pozwala nam uzyskac aktywacji api. Ale moze jeszcze raz opisze wam caly temat. Problem jest w tym, ze pol roku temu chcialem otwozyc strone internetowa, gdzie beda brac produktu z allegro.pl z kategorii czesci samochowe. Wlasnie moja strona internetowa robila firma : https://seemsneat.com , oni wlasnie zrobili strona internetowa adgdalys.lt , teraz problem polega na tym, ze allegro nam nie daje pozwolenia api, bez tego pozwolenia nasz biznes stoji na miejscu. Zrozumcie nas prosze, ze nasza firma tylko dziala jak 3 miesiace, to jest nie realna na terazniejszym kroku naszej pracy uzyskac 99% pozytywnych opinii i jeszcze miec 100 partnerow. Inne firmy przez 5 lat takiego nie moga uzyskac. Nastepny moment to jest strona internetowa srotas24.lt dla nich wy daliscie api podlaczenia, ja w tej firmie pracowalem , i mam duzo doswiadczenia z tym wszystkim. Teraz pytanie u mnie polega na tym, czy wy macie jakies obawy na temat naszej firmy czy w czym jest problem aby uzyskac api podlaczenia, ja wam wszystko reprezentowalem, ze chcemy pracowac, bardzo duzo inwestowalismy w nasz biznes, ktory po prosto stoji na miejscu, u nas jest magazyn w suwalkach, gdzie bedzie nasz pracownik przyjmowac paczki zamowionych czesci samochodowych, nastepnie my to sprowadzamy na Litwe, i sprzedajemy innym kupujacym, bussines to bussines. A panstwo nam teraz nie moze udzielic API podlaczen, ze wzgledu, ze po prosto jestemy nowa firma, tak ale my chcemy z wami wspolpracowac najmniej przez 10 lat, i beda u nas dobre opinie itd. Moze mozemy podpisac jakas umowe, ze nie naszkodzimy, ze po prosto na kozysc naszej firmy i naszego biznesu wy nam dacie pozwolenia na kozystania z API , i wszyscy bedziemy zadowoleni. Przeszlismy pelna weryfikacje firmy, wszystkie dokumenty wam wyslalismy, wszystko jest ok z nami, naprawda potrzebujemy tych podlaczen, zrozumcie nas prawidlowo zainwestowalismy co najmniej 20 tysiecy euru, a teraz stojimy na miejscu, moze jest jakies rozwiazanie? Mozemy przyjechac do waszej siedziby i zalatwic umowe. Dziekuje serdeczne wam jeszcze raz. Prosze to przejzec jeszcze raz...

Hi adgparts55 ,

I am in the same position like you.
Did you solve your problem with access to API or allegro approve you as verified application?

**Comment by adgparts55** [comment]
Hi, we didnt solve, I dont now what to do... Maybe you know any solution?

сб, 17 июл. 2021 г., 10:39 dzoudzou3 ***@***.***>:

**Comment by adgparts55** [comment]
Hi

> > Dzien dobry kolejny raz. Pisalem wam na zeszlym tygodniu na temat API. Rozumiem, ze regulamin nie pozwala nam uzyskac aktywacji api. Ale moze jeszcze raz opisze wam caly temat. Problem jest w tym, ze pol roku temu chcialem otwozyc strone internetowa, gdzie beda brac produktu z allegro.pl z kategorii czesci samochowe. Wlasnie moja strona internetowa robila firma : https://seemsneat.com , oni wlasnie zrobili strona internetowa adgdalys.lt , teraz problem polega na tym, ze allegro nam nie daje pozwolenia api, bez tego pozwolenia nasz biznes stoji na miejscu. Zrozumcie nas prosze, ze nasza firma tylko dziala jak 3 miesiace, to jest nie realna na terazniejszym kroku naszej pracy uzyskac 99% pozytywnych opinii i jeszcze miec 100 partnerow. Inne firmy przez 5 lat takiego nie moga uzyskac. Nastepny moment to jest strona internetowa srotas24.lt dla nich wy daliscie api podlaczenia, ja w tej firmie pracowalem , i mam duzo doswiadczenia z tym wszystkim. Teraz pytanie u mnie polega na tym, czy wy macie jakies obawy na temat naszej firmy czy w czym jest problem aby uzyskac api podlaczenia, ja wam wszystko reprezentowalem, ze chcemy pracowac, bardzo duzo inwestowalismy w nasz biznes, ktory po prosto stoji na miejscu, u nas jest magazyn w suwalkach, gdzie bedzie nasz pracownik przyjmowac paczki zamowionych czesci samochodowych, nastepnie my to sprowadzamy na Litwe, i sprzedajemy innym kupujacym, bussines to bussines. A panstwo nam teraz nie moze udzielic API podlaczen, ze wzgledu, ze po prosto jestemy nowa firma, tak ale my chcemy z wami wspolpracowac najmniej przez 10 lat, i beda u nas dobre opinie itd. Moze mozemy podpisac jakas umowe, ze nie naszkodzimy, ze po prosto na kozysc naszej firmy i naszego biznesu wy nam dacie pozwolenia na kozystania z API , i wszyscy bedziemy zadowoleni. Przeszlismy pelna weryfikacje firmy, wszystkie dokumenty wam wyslalismy, wszystko jest ok z nami, naprawda potrzebujemy tych podlaczen, zrozumcie nas prawidlowo zainwestowalismy co najmniej 20 tysiecy euru, a teraz stojimy na miejscu, moze jest jakies rozwiazanie? Mozemy przyjechac do waszej siedziby i zalatwic umowe. Dziekuje serdeczne wam jeszcze raz. Prosze to przejzec jeszcze raz...
> 
> Hi adgparts55 ,
> 
> I am in the same position like you.
> Did you solve your problem with access to API or allegro approve you as verified application?

Hi, we didnt solve... maybe you know any solutions? Because our company need this...

**Comment by dzoudzou3** [comment]
Hi,

my solution now is "parse HTML". But after many requests to the server from
the app, the server blocked my app because I provided many requests.
This is my problem now. Because on my web site when I want to search
something, there are many requests to the allegro server.
Do you know how I can resolve this?

Thanks
Jozef

ut 20. 7. 2021 o 8:22 adgparts55 ***@***.***> napísal(a):

**Comment by adgparts55** [comment]
We have same problem, allegro is blocking us. and thats all, I think only way is to get access... but its impossible to get, when we are not old sellers... we just new company

**Comment by dzoudzou3** [comment]
I am still in the same state. I don't know how to resolve this problem.
