### ISSUE TITLE
Problem z pobraniem tokena -

### ISSUE THREAD

**Issue by nowyyy31** [allegro/allegro-api#4672]
dzień dobry, 

Próbuje pobrać w środowisku testowym access_token, ale podczas wywołania kodu który jest tutaj
https://developer.allegro.pl/getting_started/#jak-uzyska%c4%87-token-dost%c4%99powy-do-api
mam białą stronę, oczywiście zmienne:
Client ID
Client Secret 
uzupełniłem 

uzupełniłem. E-mail w środowisku testowym to karol.elus@gmail.com

**Comment by nowyyy31** [comment]
Udało się pobrać

**Comment by MaciejFrackowiak** [comment]
Cieszę się, iż udało się Tobie uzyskać autoryzację.
