### ISSUE TITLE
Integracja DPD Pobranie z BL

### ISSUE THREAD

**Issue by kasiajn** [allegro/allegro-api#4673]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X ] inny

:beetle: Dzień dobry. Baselinker skierował mnie do Allegro, gdyż uważają że błąd leży po Państwa stronie. Nadając paczki poprzez Wysyłam z Allegro z poziomu Allegro, **mając umowę z DPD** podpiętą pod system, mogę wygenerować etykiety bez problemów. Nie mogę jednak wygenerować przesyłek pobraniowych DPD w połączeniu Baselinker --> Wysyłam z Allegro gdyż wyskakuje "błąd przetwarzania." Baselinker wysłał mi logi, które powinny pomóc Państwu zidentyfikować problem, jednak zawierają one dane wrażliwe (adres klienta) i wyślę plik do Państwa poprzez formularz kontaktowy podając nr. wątku.

**Comment by MaciejFrackowiak** [comment]
Oczywiście, gdy otrzymamy zgłoszenie zweryfikujemy opisaną kwestię.

**Comment by MaciejFrackowiak** [comment]
Otrzymaliśmy Twoje zgłoszenie i dokonaliśmy już jego weryfikacji. 
W dodatkowych danych COD w polu name wprowadzono niedozwolony znak "/" - tak wygląda to od strony kodu:

```
{
    ...,
    "additional_services": {
        "cod": {
            ...,
            "name": "xxxxxx ulica 21/6 xx-xxx xxxxxxx Polska"
        }
    },
    ...
}
```
