### ISSUE TITLE
Brak Accept-Language w nagłówku, a mieszany język komunikatów błędów 

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#4674]
Witam,
Do tej pory nie wysyłałem Accept-Language w nagłówku i otrzymywałem treść w języku polskim, ale komunikaty błędów w języku angielskim (pasuje mi takie rozwiązanie). W ostatnim czasie zacząłem dla niektórych aukcji otrzymywać komunikaty walidacyjne w języku polskim 
I tak np przeplatają się komunikaty raz po polsku, a raz po angielsku:
"Uzupełnij parametry obowiązkowe" (zamiast "Missing required parameters")
"Nieprawidłowe parametry (123456) dla wybranej kategorii"
"Missing parameter Tytuł (223545) with value: "Pan Tadeusz" for offer with product.

Przy zmianie Accept-Language na en-US otrzymuje treść serwisu w języku angielskim (np nazwy kategorii).
Czy jest możliwość wymuszenia treści w języku polskim, a komunikatów w języku angielskim?

**Comment by MaciejFrackowiak** [comment]
Taka sytuacja ma miejsce, gdy pierwotny draft oferty został stworzony w języku A, a następnie wysłano Accept-Language w  języku B. Podczas pierwszej walidacji draftu zwróciliśmy komunikat w języku A, a następnie przesłałeś dokładnie ten sam payload, tylko z językiem B - jako że oferta/draft co do zasady nie zmieniła się, to zwracamy komunikat w pierwotnym języku A. Jest to celowe i prawidłowe zachowanie mechanizmu.

**Comment by dol1234** [comment]
Wszystkie drafty zostały utworzone bez podanego Accept-Language

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowy trace-id, dla którego otrzymałeś odmienne wersje odpowiedzi komunikatów.

**Comment by dol1234** [comment]
TraceId: 3abbfa5965403d97
OfferId: 10889627614
Poniżej json z dwujęzycznymi kodami błędów:

`[{"Code":"VALIDATION_ERROR","Details":"","Message":"Missing parameter ISBN (245669) with value: \"9788373272286\" for offer with product.","Path":"null","UserMessage":"Missing parameter ISBN (245669) with value: \"9788373272286\" for offer with product."},{"Code":"VALIDATION_ERROR","Details":"","Message":"Missing parameter Okładka (75) with value: \"twarda\" for offer with product.","Path":"null","UserMessage":"Missing parameter Okładka (75) with value: \"twarda\" for offer with product."},{"Code":"VALIDATION_ERROR","Details":"","Message":"Nieprawidłowe parametry (237218, 121, 11324, 7037, 7036, 246845, 225693) dla wybranej kategorii.","Path":"parameters","UserMessage":"Nieprawidłowe parametry (237218, 121, 11324, 7037, 7036, 246845, 225693) dla wybranej kategorii."},{"Code":"VALIDATION_ERROR","Details":"","Message":"Missing parameter Autor (223489) with value: \"Adam Mickiewicz\" for offer with product.","Path":"null","UserMessage":"Missing parameter Autor (223489) with value: \"Adam Mickiewicz\" for offer with product."},{"Code":"VALIDATION_ERROR","Details":"","Message":"Uzupełnij parametry obowiązkowe: Tytuł, Autor, Okładka, Rok wydania, Wydawnictwo.","Path":"parameters","UserMessage":"Uzupełnij parametry obowiązkowe: Tytuł, Autor, Okładka, Rok wydania, Wydawnictwo."},{"Code":"VALIDATION_ERROR","Details":"","Message":"Missing parameter Tytuł (223545) with value: \"Pan Tadeusz\" for offer with product.","Path":"null","UserMessage":"Missing parameter Tytuł (223545) with value: \"Pan Tadeusz\" for offer with product."}]`

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład - spostrzeżenie przekazałem do weryfikacji, wrócę z odpowiedzią.

**Comment by dol1234** [comment]
Dziękuję, komunikaty walidacyjne znów są po angielsku, ale teraz mix jest w treści.
Missing required parameters: Tytuł, Artist, Storage Medium (wcześniej komunikaty były po angielsku a zawartość po polsku)

**Comment by MaciejFrackowiak** [comment]
Sprawa jest weryfikowana, co do zasady nie otrzymałem jeszcze żadnej wiążącej odpowiedzi - prośba o cierpliwość.

**Comment by dol1234** [comment]
Zwróccie jeszcze proszę uwagę na literówkę (parameteru zamiast parametru) w błędzie walidacji:

"Brakuje parameteru Tytuł (223545) o wartości: "Pan Tadeusz" dla oferty z produktem."

**Comment by MaciejFrackowiak** [comment]
Dziękuję za spostrzeżenie - przekażę do zespołu.

**Comment by Lukasz-Zurek** [comment]
@dol1234 Błędne komunikaty zostały już przez nas poprawione. Pozostaje jeszcze literówka w "parameteru", którą zgłosiliśmy do poprawki i jak tylko ją poprawimy - damy znać w wątku.

Przepraszamy za te utrudnienia.
