### ISSUE TITLE
Problem z pobraniem informacji o aukcji

### ISSUE THREAD

**Issue by nowyyy31** [allegro/allegro-api#4675]
Próbuje pobrać informacji na temat aukcji za pomocą  GET /sale/offers/ ale otrzymuje komunikat: 

{"errors":[{"code":"AccessDeniedException","message":"Client is not allowed for execute this command","details":"AccessDeniedException","path":"/sale/offers/7680552280","userMessage":"Client is not allowed for execute this command"}]}"

> function getAccessToken()
> {
> 
>     $authUrl = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials";
>     $clientId = "xxx";
>     $clientSecret = "xxx";
> 
>     $ch = curl_init($authUrl);
> 
>     curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
>     curl_setopt($ch, CURLOPT_USERNAME, $clientId);
>     curl_setopt($ch, CURLOPT_PASSWORD, $clientSecret);
>     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
> 
>     $tokenResult = curl_exec($ch);
>     $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
>     curl_close($ch);
> 
>     if ($tokenResult === false || $resultCode !== 200) {
>         exit ("Something went wrong");
>     }
> 
>     $tokenObject = json_decode($tokenResult);
> //var_dump($tokenObject);
>     return $tokenObject->access_token;
> }
> 
> 
> function get($token)
> {
>     $getUrl = "https://api.allegro.pl.allegrosandbox.pl/sale/offers/7680552280";
> 
>     $ch = curl_init($getUrl);
> 
>     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
>     curl_setopt($ch, CURLOPT_HTTPHEADER, [
>                  "Authorization: Bearer $token",
>                  "Accept: application/vnd.allegro.public.v1+json"
>     ]);
>     $mainResult = curl_exec($ch);
>     $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
>     curl_close($ch);
> var_dump($mainResult);
>     if ($mainResult === false || $resultCode !== 200) {
>         exit ("Something went wrong");
>     }
> 
>     $Result = json_decode($mainResult);
> 
>     return $Result;
> }
> 
> 
> function main()
> {
>     $token = getAccessToken();
>     var_dump(get($token));
> }
> main();

**Comment by MaciejFrackowiak** [comment]
Zasób [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) wymaga autoryzacji "bearer-token-for-user", natomiast Ty korzystasz z autoryzacji "bearer-token-for-application" w postaci client_credentials. Aby pobrać szczegóły oferty musisz zautoryzować się code lub device flow - opisujemy to szczegółowo w [poradniku](https://developer.allegro.pl/auth/).

**Comment by nowyyy31** [comment]
Próbuje jeszcze pobrać informacje o kosztach za transakcje aukcji i znalazłem wątek: https://github.com/allegro/allegro-api/issues/2768

I teraz udało mi się pobrać informacje o aukcji i dodałem { "offer": \\dane \\ } 

I mam taki ciąg znaków

`
{ "offer": {"id":"7680552280","name":"TELEFON KOMÓRKOWY BRIO TOUCH","category":{"id":"170"},"product":{"id":"1c403f1b-a3c2-4f1b-9ef1-875899b08acd"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["TEOLIKBRIOTOUCH"],"rangeValue":null},{"id":"202685","valuesIds":["202685_212933"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["5903978376243"],"rangeValue":null},{"id":"127448","valuesIds":["127448_14"],"values":[],"rangeValue":null},{"id":"202749","valuesIds":[],"values":["12"],"rangeValue":null},{"id":"202869","valuesIds":["202869_233054"],"values":[],"rangeValue":null},{"id":"202865","valuesIds":["202865_214157"],"values":[],"rangeValue":null},{"id":"4388","valuesIds":["4388_4"],"values":[],"rangeValue":null},{"id":"202717","valuesIds":[],"values":["1234"],"rangeValue":null},{"id":"219","valuesIds":["219_2"],"values":[],"rangeValue":null},{"id":"202821","valuesIds":["202821_213909"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"

etest
"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1159a8/0d0987f34863a6bbf639ef9c557b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"100","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":{"percentage":null,"rate":null,"subject":"GOODS","exemption":null,"id":"ca6761f0-d7eb-4831-b809-6debbd957686"},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"4ea10621-2edc-4ece-b2f8-136b61306bf3"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"cfd66b12-86ca-4161-8093-861461e80c2e"},"returnPolicy":{"id":"ea60b889-dedc-44e9-9701-62da7b733958"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":true,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"POMORSKIE","city":"Sianowo","postCode":"83-328"},"external":null,"attachments":[],"contact":null,"validation":{"errors":[],"warnings":[],"validatedAt":"2021-07-02T12:15:02.696Z"},"createdAt":"2021-07-02T12:11:53.000Z","updatedAt":"2021-07-02T12:15:02.698Z"}}
`

I jak wysyłam go przez curl to otrzymuję komunikat: 
`{"errors":[{"code":"NotSupportedException","message":"Unsupported content type. Please check 'Content-Type' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}`

Gdzie popełniam błąd w kodzie:

`    $getUrl = "https://api.allegro.pl.allegrosandbox.pl/sale/offers/7680552280";

    $ch = curl_init($getUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
 //   var_dump($mainResult);
  /*  if ($mainResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }*/
	print_r($mainResult);
	$data='{
	"offer": '.$mainResult.'}';
    //$data = json_decode($mainResult);
echo '<hr>';
print_r($data);
    $getUrl = "https://api.allegro.pl.allegrosandbox.pl/pricing/fee-preview";

    $ch = curl_init($getUrl);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
                 "Authorization: Bearer $token",
                 "Accept: application/vnd.allegro.public.v1+json"
    ]);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	echo '<hr>';
		print_r($mainResult);`

**Comment by MaciejFrackowiak** [comment]
Zasób [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) wymaga również przekazania nagłówka Content type:
"application/vnd.allegro.public.v1+json" - nie widzę jego w Twoim reequeście.

**Comment by nowyyy31** [comment]
krok bliżej, ale jeszcze otrzymałem błąd że składnia JSON jest błędna 
"400 Bad request Your browser sent an invalid request. " 

mam taki kod: 

{"offer": {"id":"7680552280","name":"TELEFON KOMÓRKOWY BRIO TOUCH","category":{"id":"170"},"product":{"id":"1c403f1b-a3c2-4f1b-9ef1-875899b08acd"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["TEOLIKBRIOTOUCH"],"rangeValue":null},{"id":"202685","valuesIds":["202685_212933"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["5903978376243"],"rangeValue":null},{"id":"127448","valuesIds":["127448_14"],"values":[],"rangeValue":null},{"id":"202749","valuesIds":[],"values":["12"],"rangeValue":null},{"id":"202869","valuesIds":["202869_233054"],"values":[],"rangeValue":null},{"id":"202865","valuesIds":["202865_214157"],"values":[],"rangeValue":null},{"id":"4388","valuesIds":["4388_4"],"values":[],"rangeValue":null},{"id":"202717","valuesIds":[],"values":["1234"],"rangeValue":null},{"id":"219","valuesIds":["219_2"],"values":[],"rangeValue":null},{"id":"202821","valuesIds":["202821_213909"],"values":[],"rangeValue":null}],"customParameters":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"

etest
"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1159a8/0d0987f34863a6bbf639ef9c557b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"100","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":null},"tax":{"percentage":null,"rate":null,"subject":"GOODS","exemption":null,"id":"ca6761f0-d7eb-4831-b809-6debbd957686"},"stock":{"available":1,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"4ea10621-2edc-4ece-b2f8-136b61306bf3"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"cfd66b12-86ca-4161-8093-861461e80c2e"},"returnPolicy":{"id":"ea60b889-dedc-44e9-9701-62da7b733958"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":true,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"POMORSKIE","city":"Sianowo","postCode":"83-328"},"external":null,"attachments":[],"contact":null,"validation":{"errors":[],"warnings":[],"validatedAt":"2021-07-02T12:15:02.696Z"},"createdAt":"2021-07-02T12:11:53.000Z","updatedAt":"2021-07-02T12:15:02.698Z"}}

a jak sobie skopiowałem kod JSON z https://github.com/allegro/allegro-api/issues/349 i zmieniłem w CURL z https://api.allegro.pl.allegrosandbox.pl/pricing/offer-fee-preview  na https://api.allegro.pl.allegrosandbox.pl/pricing/fee-preview 

Czyli tak wygląda kod:
	$data='{
	"offer": {
		"type": "SHOP",
		"category": {
			"id": "50855"
		},
		"duration": "PT720H",
		"unitPrice": "116.00",
		"quantity": "3",
		"soldQuantity": "1",
		"numberOfPhotos": "2",
		"bold": false,
		"highlight": false,
		"emphasized": false,
		"departmentPage": false,
		"emphasizedHighlightBoldPackage": false
	},
	"includeQuotingBundles": true
}';

$getUrl = "https://api.allegro.pl.allegrosandbox.pl/pricing/fee-preview";
    $ch = curl_init($getUrl);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	    curl_setopt($ch, CURLOPT_HTTPHEADER, [				
                "Authorization: Bearer $token",
                "Accept: application/vnd.allegro.public.v1+json",
				"Content type: application/vnd.allegro.public.v1+json",
				'Accept-Language: pl-PL'				 
    ]);
	echo '<hr>';
	echo $data;
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    $mainResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
	echo '<hr>';
		print_r($mainResult);



To i tak mam błąd HTTP 400

**Comment by MaciejFrackowiak** [comment]
Podaj zamiast "Content type" prawidłową wersję tj. "Content-Type" i request powinien się zakończyć pozytywnie.
