### ISSUE TITLE
Problem z Authorization Code flow

### ISSUE THREAD

**Issue by itland1** [allegro/allegro-api#4676]
Dzień dobry,
Mam napisaną aplikację w C#. Używam Chromedriver do automatycznego logowania się użytkownika przez https://allegro.pl/auth/oauth/authorize?response_type=code&client_id={ApplicationDefinition.ClientId}&redirect_uri={ApplicationDefinition.RedirectURI} celem uzyskania kodu autoryzującego.
Do dnia dzisiejszego (6 lipca) aplikacja działała poprawnie. Od dzisiaj logowanie przez Chromedriver powoduje pojawienie się przed stroną logowania strony z napisem "Chcemy upewnić się, że nie jesteś robotem" i trzeba ręcznie przejść etap weryfikacji. 
Powyższa sytuacja nie ma miejsca gdy wprowadzę adres strony do autoryzacji ręcznie w przeglądarce Chrome.

Proszę o informację co mam zrobić aby Allegro nie prosiło o weryfikację podczas autoryzacji z Chromedriver.

**Comment by AureliuszBrussy** [comment]
Podaj proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) adres IP (powinieneś go znaleźć na stronie z komunikatem). W zgłoszeniu wskaż numer wątku na GitHubie: #4676.

**Comment by AureliuszBrussy** [comment]
@itland1 czy korzystasz z Chromedriver aby zautomatyzować proces wprowadzania loginu i hasła? Nie wspieramy takiego procesu i  faktycznie w takim przypadku możesz natknąć się na naszą blokadę.

**Comment by itland1** [comment]
Dzień dobry,

Tak, właśnie w tym celu.
Do przedwczoraj proces był niezakłócony ale od wczoraj pojawia się ta 
dodatkowa procedura z "puzlowym uwierzytelnianiem"

Jeśli tak nie będzie to działać to jak można to zrobić inaczej? Może 
jakiś przykład dla C#?
Dodam, że po pobraniu kodu autoryzacyjnego uzyskanie tokena już działa 
prawidłowo. Problem jest tylko z uzyskaniem kodu autoryzacji.


Pozdrawiam

*Andrzej Sidz*
Właściciel IT-LAND
kom. 509 498 138
***@***.*** ***@***.***>


W dniu 2021-07-07 o 14:50, AureliuszBrussy pisze:

**Comment by AureliuszBrussy** [comment]
Użytkownik powinien samodzielnie wprowadzić login i hasło. Aby nie zmuszać użytkownika do ponownego uwierzytelniania - korzystaj z opcji [przedłużania ważności tokena](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena) za pomocą refresh tokena.
