### ISSUE TITLE
Zmiana ceny przez kampanie

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4677]
1. Zgodnie z poradnikiem dotyczącym kampanii kampanie typu `DISCOUNT` oraz `SOURCING` zmieniają cenę. Jak dobrze rozumiem zmieniają cenę w `sellingMode.price.amount` tak?
2. Czy zmiana ceny przez wasz system następuje jednorazowo, czy wielokrotnie, ponieważ nasz system działa tak, że przy każdej zmianie w ofercie zgodnie z mechanizmem synchronizacji zostanie zaktualizowana cena na naszą z bazy i się "gryzą".
3. Czy AllegroCeny również wpływa na `sellingMode.price.amount`?

**Comment by AureliuszBrussy** [comment]
1. Tak, aktualnie wszystkie kampanie - prócz Allegro Ceny - zmieniają cenę w ofercie (pole **sellingMode.price.amount**). Planujemy jednak, aby w przyszłości również pozostałe kampanie nie wpływały na cenę w polu **sellingMode.price.amount**. 
2. Zmieniamy cenę jednorazowo. Każda zmiana ceny w ofercie zakwalifikowanej do danej kampanii spowoduje **wyłączenie jej** z danej kampanii.
3. Tak jak w punkcie 1: Allegro Ceny nie wpływa na **sellingMode.price.amount**.
