### ISSUE TITLE
Mimo błędu aukcja jest tworzona

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4678]
Witam,

Mam taki problem z API, ale nie wiem czy to jest domyślne zachowanie czy to jest błąd:

1. Tworzę ofertę z parametrem marka: Inna
2. Wpisuję tam wartość np. "Marka&Marka" (jako ambiguous value)
3. Podczas tworzenia oferty dostaje błąd `{"errors":[{"code":"BAD_REQUEST","message":"Invalid custom value: provided string contains illegal HTML markup","details":"","path":"","userMessage":"This field cannot contain HTML markups"}]}` - okej rozumiem.

Ale patrzę, że na allegro aukcja powstała jako szkic. Jednak nie mam ani offer id ani żadnej informacji o tej aukcji (przez co szybko potrafię osiągnąć limit szkiców). Spodziewanym zachowaniem byłoby albo nie tworzenie szkicu aukcji, albo zwracanie offer id - żeby można w jakiś sposób zidentyfikować aukcję, a nie tworzyć nowy szkic za każdym razem.

Chyba że jest jakieś inne rozwiązanie, którego nie widzę w tej chwili?

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@mrezlik aktualnie problem nie powinien występować.

**Comment by mrezlik** [comment]
Niestety sprawdzałem to właśnie teraz i dalej problem występuje. Chyba, że na sandboxie nie zostało to poprawione, a jedynie na "normalnym" allegro. Wtedy sprawdzę jeszcze tam, ale pierwsze chciałem sprawdzić na środowisku testowym.

**Comment by AureliuszBrussy** [comment]
@mrezlik czy jesteś w stanie podać trace-id przykładowego requesta zakończonego błędem 422, w wyniku którego utworzony został draft?

**Comment by mrezlik** [comment]
Przykładowy trace-id z sandboxa: 92de5cbb79501728 
Tylko zaznaczę, że jest to zakończone błędem 400 a nie 422

**Comment by AureliuszBrussy** [comment]
@mrezlik dziękuję, sprawdzamy to.

**Comment by AureliuszBrussy** [comment]
@mrezlik czy możesz jeszcze przesłać pełen request?

**Comment by mrezlik** [comment]
Tutaj jest przykładowy request

 requestBody={"afterSalesServices":{"impliedWarranty":{"id":"3fac965c-8e46-4a65-8d2d-4dde27fc84ce"},"returnPolicy":{"id":"4d1d3e4a-d972-4dd7-9b88-06d914336368"},"warranty":{"id":"b618afde-c0e2-4cf9-b3be-f6f172540011"}},"category":{"id":"78137"},"delivery":{"shippingRates":{"id":"53065932-d5ca-4948-bfa3-c3a755e8fc08"},"handlingTime":"PT24H"},"external":{"id":"stocksell_485575795"},"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/110094/cf8cddb445adac862fbb81c5a14f"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/119161/924888cf4362b9ba5c4a3594f4ea"},{"url":"https://a.allegroimg.allegrosandbox.pl/original/11ac5a/d93cd19b481088eae5de26739338"}],"location":{"city":"Skawina","countryCode":"PL","postCode":"32-050","province":"MALOPOLSKIE"},"parameters":[{"id":"59","valuesIds":["59_8"]},{"id":"3786","values":["mint\u0026amp;berry"],"valuesIds":["3786_85"]},{"id":"4126","valuesIds":["4126_1"]},{"id":"201089","values":["11"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"201025","valuesIds":["201025_2513"]},{"id":"201017","valuesIds":["201017_2377"]},{"id":"201193","valuesIds":["201193_16384"]},{"id":"201305","valuesIds":["201305_207925"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"4428","valuesIds":["4428_2"]},{"id":"201077","valuesIds":["201077_2577"]},{"id":"451","valuesIds":["451_4"]},{"id":"3806","valuesIds":["3806_579945"]},{"id":"3766","valuesIds":["3766_1"]}],"name":"Wystawianie Test q AAA","payments":{"invoice":"VAT"},"publication":{"startingAt":"2021-07-09T13:57:32.000Z","duration":"PT120H","republish":true},"sellingMode":{"format":"AUCTION","price":{"amount":94.99,"currency":"PLN"},"startingPrice":{"amount":75.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eWystawianie Test\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/110094/cf8cddb445adac862fbb81c5a14f"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e mint\u0026amp;amp;berry\u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e Brązowy\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 92% poliester 8% elastan\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Wycięte ze względu na restrykcję outletową\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e q\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 189,00 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/119161/924888cf4362b9ba5c4a3594f4ea"},{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/11ac5a/d93cd19b481088eae5de26739338"}]}]}} exception=Niepoprawna odpowiedź z Allegro. Kod: 400. Błąd: BAD_REQUESTThis field cannot contain HTML markupsInvalid custom value: provided string contains illegal HTML markup  .

**Comment by AureliuszBrussy** [comment]
Dziękuję, potwierdzam występowanie tego problemu. Wrócę z odpowiedzią, gdy tylko wdrożymy poprawkę.

**Comment by mrezlik** [comment]
Chciałem się dowiedzieć jak sytuacja? :) Bo mam dalej podobny problem, ale z parametrem marka. 
` Kod: 400. Błąd: BAD_REQUESTValue 'inna' should be used in order to set custom value for parameter 'Marka'Custom value cannot be defined when the dictionary value is not an ambiguous one: parameterId=25929  . Trace-id=[178d2f7d31805564]. 
`
Rozumiem skąd się pojawia błąd, ale nie dostaję informacji o tym, że aukcja została stworzona, a na allegro powstaje :)

**Comment by AureliuszBrussy** [comment]
Nie wdrożyliśmy jeszcze poprawki. Proszę o jeszcze trochę cierpliwości - mamy to na uwadze.
