### ISSUE TITLE
Oferta nieaktywna? [restapi]

### ISSUE THREAD

**Issue by bugas23** [allegro/allegro-api#468]
Witam,
bawię się w sandboxie, przygotowałem ofertę przez interface graficzny, próbuje ją skopiować poprzez GET -> POST -> PUT, nie ma żadnych błędów, status oferty jest INACTIVE i nie jest nigdzie widoczna w graficznym interfejsie.

Ostatnio wystawiona oferta w ten sposób to nr 6205584893

**Comment by bugas23** [comment]
Ok, już wiem że powinienem ją sam aktywować ale mam teraz problem z uuid - czy to jest dowolnie generowany uuid?

**Comment by bugas23** [comment]
`Array
(
    [publication] => Array
        (
            [action] => ACTIVATE
        )

    [offerCriteria] => Array
        (
            [offers] => Array
                (
                    [id] => 6205584903
                )

            [type] => CONTAINS_OFFERS
        )

)
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/offer-publication-commands/e02d6eaa-6c4e-4808-afee-2b0621ce132c
                    [userMessage] => 
                )

        )

)`

**Comment by bugas23** [comment]
Błąd w manualu - tu znalazłem rozwiązanie:
https://github.com/allegro/allegro-api/issues/386

**Comment by LukaszKorek** [comment]
Poprawimy błąd, dziękujemy za zgłoszenie.

**Comment by bugas23** [comment]
Witam ponownie,
czy jest jakiś problem z aktywacją oferty?
Dotychczas skrypt działał idealnie, odpowiedź przy próbie aktywacji wygląda jak zawsze, natomiast próba sprawdzenia statusu wraca pustą tablicę.

```
Array
(
    [id] => 2642fbe9-b02f-481d-be16-4a80ac71faf2
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
Array
(
    [tasks] => Array
        (
        )

)
```

**Comment by bugas23** [comment]
Najstarsze aukcje właśnie ruszyły - aktywacja zajęła 3h.

**Comment by bugas23** [comment]
Ponownie, 3h minęło i brak aktywacji ofert...
```


Array
(
    [id] => d0f53914-43e4-4e91-95f6-05117822bc2b
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
```

**Comment by LukaszKorek** [comment]
Poproszę o pełne curle łącznie z nagłówkami. Pozwoli to na pełną weryfikację zgłoszenia.

**Comment by bugas23** [comment]
Aktywacja nastapila po 10h... Jezeli problem sie powtorzy przygotuje pelna "dokumentacje".
Pozdrawiam

**Comment by LukaszKorek** [comment]
Jeżeli posiadasz takie informację odnośnie tego przypadku i nie będzie to problem to podeślij je proszę, a zbadamy temat.

**Comment by bugas23** [comment]
Problem pojawił się ponownie... tylko nie do końca wiem co mam przesłać. Generalnie skrypt generujący aukcje używany jest cały czas - codziennie i z reguły działa bez problemu. Aż raz w tygodniu ma problem i aktywuje aukcje dopiero po kilkunastu godzinach. Wystawianie aukcji z poziomu allegro działa ok.

Z kodu usunąłem nazwę aukcji oraz description

```

Array
(
    [id] => 7535741259
    [name] => [...]
    [category] => Array
        (
            [id] => 251842
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [1] => Array
                (
                    [id] => 128394
                    [valuesIds] => Array
                        (
                            [0] => 128394_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

        )

    [ean] =>

[...]

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 2099
                    [currency] => PLN
                )

            [startingPrice] =>
            [minimalPrice] =>
        )

    [stock] => Array
        (
            [available] => 100
            [unit] => UNIT
        )

    [publication] => Array
        (
            [duration] =>
            [status] => INACTIVE
            [startingAt] =>
            [endingAt] =>
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => a5ee9ac4-73d4-4e8f-9608-8233b00dd37a
                )

            [handlingTime] => PT48H
            [additionalInfo] =>
            [shipmentDate] =>
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => ee50a490-69a1-4e39-bda9-9c9ba60205c6
                )

            [returnPolicy] => Array
                (
                    [id] => 05f1946a-afde-4a91-8a4e-1c3a25ed3056
                )

            [warranty] => Array
                (
                    [id] => 71b329ae-d344-40a7-b801-a57a912e58bc
                )

        )

    [additionalServices] =>
    [sizeTable] =>
    [promotion] =>
    [location] => Array
        (
            [countryCode] => PL
            [province] => DOLNOSLASKIE
            [city] => Świdnica, Wrocław, Katowice
            [postCode] => 51-129
        )

    [external] =>
    [contact] =>
    [validation] => Array
        (
            [errors] => Array
                (
                )

            [validatedAt] => 2018-08-29T11:19:56.727Z
        )

    [createdAt] => 2018-08-29T11:19:56Z
    [updatedAt] => 2018-08-29T11:19:56.728Z
)


Array
(
    [id] => 1f9631f3-3b0e-4cf2-b722-2364697e68da
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)

```

**Comment by bugas23** [comment]
Skrypt generalnie pobiera dane z jednej aukcji (generowaną z poziomu interfejsu allegro) i na jej podstawie wystawia podobną.
Problem dotyczy wszystkich aukcji, tzn. skrypt nie działa nawet z aukcjami, które wcześniej były kopiowane bez problemu.
Także problem jest gdzieś na etapie aktywacji oferty.

**Comment by LukaszKorek** [comment]
Poproszę jeszcze Traceid. Dziękuję za dotychczasowe informacje.
