### ISSUE TITLE
Importowanie listów przewozowych 

### ISSUE THREAD

**Issue by Karas44a** [allegro/allegro-api#4680]
Witam, korzystamy z programu magazynowego FALCON5. Zastanawiamy się nad drukowaniem etykiet kurierskich bezpośrednio z tego programu, ale wiemy, że nie ma on powiązania z allegro ( chodzi doklładnie o listy przewozowe). Czy istnieje możliwość zaimportowania pliku i dodania listów przewozowych do allegro? 
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie, nie udostępniamy takiej możliwości. Numer trackingowy przesyłki możesz dodać tylko poprzez [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST).
