### ISSUE TITLE
zablokowany dostęp - /sale/categories

### ISSUE THREAD

**Issue by czech-rep** [allegro/allegro-api#4681]
zacząłem robić proste operacje na API allegro sandbox: autoryzacja, pobranie listy kategorii. Na początku działało, ale mój dostęp został zablokowany: 403 You have been blocked.

- you are browsing and clicking at a speed much faster than expected of a human being
- something is preventing Javascript from working on your computer
- there is a robot on the same network as you

rzeczywiście tak jest, bo korzystam z python requests. 
Chciałbym prosić o odblokowanie dostępu.

**Comment by AureliuszBrussy** [comment]
Podaj proszę adres adres IP który wskazaliśmy wraz z komunikatem o zablokowaniu dostępu. Jeżeli nie chcesz podawać tych danych tutaj, możesz to także zrobić przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu wskaż numer wątku na GitHubie: #4681.

**Comment by czech-rep** [comment]
napisałem przez formularz

**Comment by AureliuszBrussy** [comment]
@czech-rep czy automatyzujesz w jakiś sposób proces logowania się do konta użytkownika podczas uwierzytelniania?

**Comment by czech-rep** [comment]
tak - mam metodę get_token która podaje user id i secret przez basic authentication i zapisuje w pamięc token używany przy wysyłaniu kolejnych requestów.
Tak jak w poradniku na developer.allegro "Jak uzyskać token dostępowy do API"

**Comment by AureliuszBrussy** [comment]
@czech-rep blokada "403 You have been blocked" wynika z nieprawidłowego url: "https://allegro.pl.allegrosandbox.pl//auth/oauth/token" - używasz 2 znaków "/" przed "auth".

**Comment by czech-rep** [comment]
Ok, udało się naprawić. Mój problem był w tym że odpytywałem https://api.allegrosandbox.pl/sale/categories 
zamiast poprawnego: https://api.allegro.pl.allegrosandbox.pl/sale/categories
a wyjątki mówiły o przekroczenie liczby requestów.
