### ISSUE TITLE
Tworzenie paczki

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4682]
Podczas tworzenia paczki commandId: d26e24c5-97fc-4e24-99f4-3bdcfe8051fc.

Otrzymujemy błąd: Service unavailable for carrier

Czy można prosić o dokładną informację jaka to usługa, na czym polega nasz błąd?

**Comment by AureliuszBrussy** [comment]
Konsultuję to z odpowiednim zespołem. Wrócę z odpowiedzią.

**Comment by marmited** [comment]
@AureliuszBrussy  kiedy otrzymam informację?

**Comment by AureliuszBrussy** [comment]
@marmited czekam jeszcze na wyjaśnienie, wrócę w tym wątku od razu, gdy je otrzymam.

**Comment by marmited** [comment]
CommandI dla nowej paczki z tym samym błędem: 4cdbf4a3-28c5-4658-90f4-3a564d0b6178.

Zaobserwowaliśmy, że błąd występuje w jednym sklepie dla inpostu.

**Comment by AureliuszBrussy** [comment]
@marmited dziękuję za kolejny przykład, jeszcze to wyjaśniamy.

**Comment by AureliuszBrussy** [comment]
@marmited wskazany w zleceniu **serviceId** to InPost Kurier, natomiast adresem doręczenia przesyłki jest Paczkomat. Kurier InPost nie realizuje dostawy do Paczkomatów, stąd błąd. Podczas tworzenia paczki powinien zostać wskazany prawidłowy serviceId.

**Comment by marmited** [comment]
@AureliuszBrussy masz rację. Natomiast Wasza strona wprowadza w błąd. 
W widoku umów własnych: https://wysylam.allegro.pl/konto/przewoznicy pokazuje się jedno API service_id, które okazuje się, że odnosi się do kuriera inpost. Dopiero po odpytaniu odpowiedniego zasobu przez API okazuje się, że istnieją dwa różne serviceId.

**Comment by AureliuszBrussy** [comment]
@marmited zgłoś proszę ten błąd w [formularzu kontatkowym](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Najlepiej jeżeli załączysz np. zrzut ekranu obrazujący w jaki sposób to wygląda.
