### ISSUE TITLE
External id w offer event

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4683]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [] inny

:beetle: **Opis**

Dlaczego eventy dla oferty zwracają `external.id`. Nie ma o tym informacji w https://developer.allegro.pl/documentation/#operation/getOfferEvents
```json
{
      "id": "MTYyNTY0OTczMDYwOTg5Ng",
      "type": "OFFER_STOCK_CHANGED",
      "occurredAt": "2021-07-07T09:22:00.440Z",
      "offer": {
          "id": "10845901037",
          "publication": null,
          "external": {
              "id": "3032163607014"
          }
      }
},
```
I czy ta zmiana było niedawno, czy nie?

**Comment by AureliuszBrussy** [comment]
Wdrożyliśmy zmianę dzisiaj. Przepraszam za wcześniejszy brak komunikatu. Nanieśliśmy zmiany do swagger.yaml.
