### ISSUE TITLE
Create Offer shows blank page

### ISSUE THREAD

**Issue by aswiniimpro** [allegro/allegro-api#4686]
Create Offer in allegro dashboard not working in both sandbox and live, shows blank page
Sales->Handling Offers->Issue via the form->List the item - https://prnt.sc/199ybfo

**Comment by MaciejFrackowiak** [comment]
Please, use a direct link: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie - to list an offer on Sandbox.

**Comment by aswiniimpro** [comment]
Yes, I tried id. But, when clicking the "List the item" button in https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, blank page displays

**Comment by MaciejFrackowiak** [comment]
I cannot confirm any problem with the direct link - please, also check it in private mode.

**Comment by aswiniimpro** [comment]
Yeah. Checked in private too, it is not working, shows blank page.

**Comment by MaciejFrackowiak** [comment]
Maybe you can try with a different internet connection or browser? As I wrote before, using the direct link there is no problem with opening a list form. I also reported an issue with a link from the main menu.

**Comment by aswiniimpro** [comment]
Thanks. 

I'm not able to delete the 'ended or active' offers in dashboard. If mistakenly send any wrong data, how could I remove that offer. Is there any other way to remove ended offers ?

And, I'm not able to edit and save the ended offer, again shows blank page when submit and data not updated.

**Comment by MaciejFrackowiak** [comment]
There is no option to remove ended or active offers from the dashboard. You can delete only drafts.
Please, check your internet settings, browser or antivirus, because we cannot confirm problem with editing or saving offers via WWW - we do not receive any complaint from other users.
