### ISSUE TITLE
Account is not a Company account type.

### ISSUE THREAD

**Issue by dkolanus** [allegro/allegro-api#4687]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ X] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
REQUEST na https://api.allegro.pl.allegrosandbox.pl/sale/badge-campaigns 

RESPONSE:
{
    "errors": [
        {
            "code": "BB2",
            "message": "Account is not a Company account type.",
            "details": null,
            "path": null,
            "userMessage": "Account is not a Company account type."
        }
    ]
}

Wcześniej było to konto prywatne, zmieniłem na firmowe. W panelu https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta/ mam informację: Rodzaj konta - Konto firmowe 

Login: zlote

**Comment by MaciejFrackowiak** [comment]
Zmieniłeś typ konta, ale nie zweryfikowałeś go - do tego niezbędne jest przesłanie dwóch dowolnych plików poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by dkolanus** [comment]
Bardzo dziękuję za podpowiedź.

Mam pytanie odnośnie już przypadku na produkcyjnym api. Zostały zgłoszone do strefy okazji produkty w sposób ręczny z poziomu panelu użytkownika. Następnie poszła synchronizacja ofert na ten podstawowy endpoint https://api.allegro.pl/sale/offers/108919938.. z parametrami "sellingMode":{"format":"BUY_NOW","price":{"amount":499,"currency":"PLN"}}
Czy to mogło być powodem zmiany ceny promocyjnej zgłoszonej do strefy okazji? Aktualnie w panelu po kliknięciu przy produkcie w **akcje > strefa okazji** widzę:
status: w trakcie weryfikacji
cena rynkowa: 499,00 zł
cena w kampanii: 499,00 zł 

Czy jeśli wykonam request na https://api.allegro.pl/sale/badges z cenami prices":{"market":{"amount":"499.00","currency":"PLN"},"bargain":{"amount":"298.00","currency":"PLN"}
to czy to wróci do strefy okazji i czy nie spowoduje np. jakiejś blokady naszych aukcji?

**Comment by MaciejFrackowiak** [comment]
Tak, modyfikacje ceny mogą prowadzić do wykluczenia oferty z kampanii. Natomiast wszelkie informacje o zasadach kwalifikacji ofert do kampanii, w tym także co do zakresu cen uzyskasz poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).
