### ISSUE TITLE
Unikatowy ID - GET /sale/badges 

### ISSUE THREAD

**Issue by BambamJazz** [allegro/allegro-api#4688]
Jest jakiś unikatowy ID kampanii "Allegro ceny" ?
Po pobraniu danych tym zasobem znalazłem dwa ID które są związane z programem:
- SUBSIDY
- SUBSIDY_MULTI
Czy z czasem pojawią się kolejne?

**Comment by MaciejFrackowiak** [comment]
Nie, nie ma unikatowego ID. Aby sprawdzić konkretne ID kampanii powiązanych z Allegro Ceny musisz skorzystać z [GET /sale/badge-campaigns](https://developer.allegro.pl/documentation/#operation/badgeCampaigns_get_all) - wówczas w odpowiedzi otrzymasz listę wszyskich dostępnych kampanii.
