### ISSUE TITLE
Dlaczego tu jesteśmy? Dokąd zmierzamy?

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#4689]
Na podstawie waszego newsa https://github.com/allegro/allegro-api/issues/4566 postanowiłem zadać sobie pytanie, dokąd zmierzacie?

Patrząc z perspektywy ostatnich zmian, modyfikacji przez lata, problemów, na obecną chwilę oferowanie integracji z wami z podstawowym pakietem supportu technicznego dla moich klientów mija się z celem. Wprowadzacie zmiany absurdalne powodujące rozwalenie niejednego oprogramowania i niejednego biznesu. 

Pytanie jest jedno zatem. Dokąd zmierzacie?

**Comment by d48u** [comment]
Brak dostepu do publicznej bramki dla developerów którzy nie robią 50k obrotów? Co potem np brak dostępu dla rudych?

**Comment by qshop123** [comment]
Dyskryminowanie przedsiębiorcy który aby osiągnąć większe przychody musi się zintegrować z API ale nie może ponieważ ma mniejsze przychody. Zaklęty krąg wersja 2.0. Czy osoby niebinarne które nie mają takich przychodów także mogą się zintegrować?

**Comment by MaciejFrackowiak** [comment]
Zgodnie z wcześniejszymi naszymi odpowiedziami w podobnych tematach, decyzja o ograniczeniu dostępu do GET /offers/listing została podjęta z uwagi na ochronę danych dot. sprzedaży dostępnej w ramach platformy - szerszy kontekst został przedstawiony w [artykule na stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/1-czerwca-2021-w-api-allegro-ograniczymy-dostep-do-publicznych-danych-o-sprzedazy-innych-uzytkownikow-i-zmienimy-forme-ich-udostepniania-O3BlgZVdwCa).

**Comment by qshop123** [comment]
Panie MaciejFrackowiak - nie odpisał Pan na zdane pytanie. Pytanie brzmi "Dlaczego tu jesteśmy? Dokąd zmierzamy". Chce Pan zabrać stanowisko w tej sprawie, proszę odpisać na pytanie w topicu.

**Comment by hahyes** [comment]
> Wprowadzacie zmiany absurdalne powodujące rozwalenie niejednego oprogramowania i niejednego biznesu.

Chyba odkąd REST API istnieje, cechuje go niestabilność i ciągłe zmiany. Był tutaj nawet kiedyś kalendarz z planowanymi funkcjonalnościami, jedną z nich miał być właśnie lepszy zasób do publicznych danych z ofert. Terminy się przeciągały, wielu rzeczy nadal z tego nie wprowadzono. Ostatecznie kalendarz porzucono, kilka miesięcy później porzucono plan rozbudowania listingu. Po prostu zmienił się model biznesowy.

Opierając swój model biznesowy na czyimś modelu biznesowym trzeba brać pod uwagę, że jest to zawsze ryzyko. Zwłaszcza, kiedy Allegro zapowiadało tutaj zmiany i ograniczenia od wielu miesięcy. Piszecie posty pełne oburzenia za późno. Allegro zabrało, opakowało całość w swój model biznesowy i wątpię, że narzekanie tutaj cokolwiek już zmieni. To już w zasadzie któryś wątek w tym temacie tutaj a odzew mizerny, nie lepiej o tym porozmawiać na Allegro Gadane? Myślę, że tam zagląda dużo więcej ludzi, jak tu.

**Comment by adamz464** [comment]
> Zgodnie z wcześniejszymi naszymi odpowiedziami w podobnych tematach, decyzja o ograniczeniu dostępu do GET /offers/listing została podjęta z uwagi na ochronę danych dot. sprzedaży dostępnej w ramach platformy.

tylko, że my nie jesteśmy dyplomatami i tego nie łykamy.
Więc kiedy możemy się spodziewać alternatywy, chociażby w postaci RSS?

**Comment by qshop123** [comment]
hahyes - Dzięki za odpowiedź. Niestety poruszanie tego na "allegro gadane" mija się z celem. Bo to rozmowa devu z biznesem. Nikt tak nie zrozumie deva jak drugi dev. Ich decyzje nie są dyktowane logiką biznesową ale logiką spekulacyjną - zróbmy tak i zobaczymy co będzie bo testy na grupie pokazały że będzie dobrze.

Zauważ że Allegro REST Api jest i tak o wiele lepsze niż poprzednie API. Ja widzę deva z allegro który ma pomysły, robi prezentację i diagramy, zanosi do biznesu a biznes mówi
- Meh, jak im damy więcej danych to wzrośnie atrakcyjność innego serwisu a my stracimy

Dla porównania gdy dev idzie do biznesu w Ebayu to biznes mówi
- Dajmy im tyle danych ile chcą, zrobią lepszy system niż nasz? To super, dajmy wypasiony program partnerski aby nie chcieli reklamować swojego sereisu tylko kierowali traffic do nas :)

I taka niestety jest smutna różnica pomiędzy Allegro a Ebay....

**Comment by hahyes** [comment]
> Niestety poruszanie tego na "allegro gadane" mija się z celem. Bo to rozmowa devu z biznesem. Nikt tak nie zrozumie deva jak drugi dev.

Tylko dział deweloperski Allegro ma bardzo mało do powiedzenia, o ile cokolwiek. Według mnie, nie mają absolutnie nic do powiedzenia. W temacie funkcjonalności dla zamkniętego API sprzedawców robią co mogą, jednak listing został ukrócony odgórnie. Nie z powodu jakiejś logiki spekulacyjnej (bo dalej istnieją scrappery, które sobie radzą), tylko z powodu rozwijanych przez Allegro usług analitycznych. Dlatego mówią o zastrzeżeniu danych sprzedaży innych sprzedawców, bo ludzie nie mają ściągać tych danych botami czy aplikacjami, tylko porównywać się poprzez ich inne (oczywiście płatne) usługi. Czysty biznes.

**Comment by d48u** [comment]
> Więc kiedy możemy się spodziewać alternatywy, chociażby w postaci RSS?

póki nie będzie alternatywy to tylko
Goggle: "create rss from url website"

**Comment by MaciejFrackowiak** [comment]
Wielokrotnie podkreślaliśmy, że decyzja w kontekście weryfikacji i dostępu do zasobu jest poza nami i jest to stricte decyzja biznesowa. Swoje sugestie, pomysły co do działania zasobu możecie zgłaszać w [wątku Discussions](https://github.com/allegro/allegro-api/discussions/4584), co wielu z Was już uczyniło wcześniej jak widzę na podstawie dotychczasowych wpisów.

**Comment by qshop123** [comment]
Wierzę, że jesteście dobrymi fachowcami którzy nie testują nic na produkcji :)
Rozumiemy, że to biznes ma ostatnie słowa i trochę szkoda. Miało być tak fajnie. 

Jesteśmy tu aby zrozumieć dokąd zmierzacie
