### ISSUE TITLE
Aukcja typ BUY_NOW i AUCTION jednocześnie

### ISSUE THREAD

**Issue by krrojewski** [allegro/allegro-api#469]
Witam. Czy można wystawić aukcję przez REST API, która będzie miała format BUY_NOW i AUCTION jednocześnie?

**Comment by TomekKaczmarek** [comment]
@krrojewski Pamiętaj, że najłatwiej sprawdzisz jak cos wystawić - najpierw wystawiając dany przypadek przez formularz, a potem pobierając dane takiej oferty zasobem GET.

Dla licytacji i ceny Kup Teraz:
- w format podaj AUCTION
- wypełnij ceny price i startingPrice, ewentualnie minimalPrice
- w stock musisz podać wartość 1
- w duration możesz przekazać: PT72H, PT120H, PT168H, PT240H
Przykład:

```
"sellingMode": {
        "format": "AUCTION",
        "price": {
            "amount": "300",
            "currency": "PLN"
        },
        "startingPrice": {
            "amount": "100",
            "currency": "PLN"
        },
        "minimalPrice": {
            "amount": "200",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },

        "duration": "PT240H",
```

**Comment by krrojewski** [comment]
dziękuję za odpowiedź, problem rozwiązany
