### ISSUE TITLE
Kod odpowiedzi 429 na PUT /sale/offer-price-change-commands

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4690]
Witam serdecznie,

niedawno dostaliśmy email o następującej treści: "Kontaktuję się, ponieważ zauważyliśmy, że Państwa integracja oparta o API Allegro, co 2 godziny wykonuje ok 230 operacji zmiany statusu publikacji oferty (PUT /sale/offer-publication-commands/{commandId}) - operacje te są nieefektywne. Zmiana statusu danej oferty powinna być wykonywana tylko w momencie faktycznej zmiany statusu. Bardzo proszę o zweryfikowanie działania Państwa oprogramowania, ponieważ obecne działanie prowadzi do nadmiarowego wykorzystywania zasobów."

@MartaNowaczyk 

Limit zapytań na minutę ustawiony powinien być według dokumentacji na 9000 requestów (niektóre zasoby dodatkowy limit) niestety dokumentacja nie podaje, które zasoby oraz jaki dodatkowy limit.

Zgadzam się w 100% że nasza aplikacja na ten moment generuje dodatkowe niepotrzebne zapytania, problem polega na tym że ostatnio dostosowujemy tyle zmian na allegro związanych z zmianami w API że nie byliśmy w stanie poświęcić czasu na to by obrobić dodatkowe requesty związane z faktycznym określaniem czy operacja się powiodła i allegro zmieniło cenę i dostępność dlatego za każdym razem wysyłamy całość licząc na to że jeśli ostatnio nie przeszło z jakichkolwiek przyczyn to teraz się może uda. 

Prosił bym o informację czy dostaliśmy jakiś dodatkowy limit blokadę na operacje PUT na zasobach: 

*  /sale/offer-price-change-commands/{commandId}
* /sale/offer-publication-commands/{commandId}

Dziękuję i pozdrawiam,
Paweł

**Comment by MartaNowaczyk** [comment]
Witam serdecznie, wszystkie te kwestie wyjaśniłam w naszej korespondencji mailowej. Pozdrawiam.
