### ISSUE TITLE
Co oznacza "You can not sell in this category"?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4692]
Próbuję wystawić drafta. I dostaję błąd "You can not sell in this category". Kategorię 261392 wziąłem z bazy produktowej. Skąd ten błąd?
Trace-id: a479236edce207b2

Jakie są generalnie przyczyny, że nie można wystawić oferty w konkretnych kategoriach?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Kategoria o id=261392 to Kultura i rozrywka - Książki i Komiksy - Ebooki - Reportaż, literatura faktu - wystawianie ofert w tej kategorii przeznaczone jest tylko dla oficjalnych dystrybutorów. O warunkach wystawiania i liście towarów zakazanych przeczytasz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/abc-sprzedazy/jakich-przedmiotow-nie-mozna-wystawiac-na-allegro-a-jakie-mozna-wystawiac-warunkowo-GDeq5WEVqig#publikacje-elektroniczne-e-booki-audiobooki-videobooki-itp-).

**Comment by tomylee0** [comment]
Dzięki.
