### ISSUE TITLE
Potrzebna baza modeli motocykli z sekcji "pasuje do"

### ISSUE THREAD

**Issue by motoselect** [allegro/allegro-api#4694]
Szukam osoby która pomoże mi zdobyć zescrapowaną bazę modeli motocykli - tabela kompatybilności - compatibility table, która jest na API Allegro
https://developer.allegro.pl/documentation/#operation/getCompatibleProductsGroups
kategori części motocyklowe nr: 158
https://allegro.pl/kategoria/czesci-i-wyposazenie-motocyklowe-czesci-motocyklowe-158

**Comment by autoswiss** [comment]
Realizowałem oprogramowanie dodające do produktów tabelę kompatybilności typów motocykli do istniejących ofert na Allegro.

**Comment by motoselect** [comment]
Na jakiej podstawie były przydzielane kompatybilne motocykle do danej części? Działo się to automatycznie hurtowo?
Ja ogólnie potrzebuje widzieć liste modeli która jest dostępna w bazie allegro

**Comment by motoselect** [comment]
Nie rozumiem

śr., 18 sie 2021, 07:29 użytkownik stale[bot] ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Zgłoszenie zostało automatycznie zamknięte przez bota - stąd powiadomienie.

**Comment by motoselect** [comment]
Dlaczego?

śr., 18 sie 2021, 11:22 użytkownik AureliuszBrussy ***@***.***>
napisał:

**Comment by AureliuszBrussy** [comment]
Ze względu na brak aktywności w wątku.

**Comment by autoswiss** [comment]
> Na jakiej podstawie były przydzielane kompatybilne motocykle do danej części? Działo się to automatycznie hurtowo?
> Ja ogólnie potrzebuje widzieć liste modeli która jest dostępna w bazie allegro

Na podstawie numeru OEM danego produktu. Może być również własna marka produktów byle był tylko 1 numer zamienny poprzez który dana część zostanie rozpoznana. Po tym baza motocykli (nieco bardziej rozbudowana niż ta na Allegro z TecDoc) była mapowana z bazą typów motocykli z Allegro.
