### ISSUE TITLE
Weryfikacja aplikacji - realny czas oczekiwania

### ISSUE THREAD

**Issue by KKowalewski24** [allegro/allegro-api#4695]
Dzień dobry,
po zapoznaniu się z tą o to instrukcją https://github.com/allegro/allegro-api/issues/4213 pozwoliłem sobie wypełnić ten o to formularz celem otrzymania weryfikacji do mojej aplikacji, miało to miejsce 26.05.2021 21:59. Po około dwóch tygodniach totalnej ciszy w mojej sprawie pozwoliłem się subtelnie przypomnieć Pani, która wysłała mi emaila zwrotne, że zgłoszenie zostało przyjęte. Wedle jej odpowiedzi sprawa miała zostać potraktowana priorytetowo i jak widać podmiot gospodarczy Allegro.pl chyba ma totalnie inną definicje swoja priorytet. Po około miesiącu(05.07.2021r) od tamtego maila przypominającego pozwoliłem napisać maila to tej samej osoby korzystając z opcji odpowiedz aby dowiedzieć się czy cokolwiek wiadomo w mojej sprawie, przez cały tydzień roboty nie dostałem żadnej odpowiedzi co szczerze mówiąc przestaje mnie dziwić. Może tutaj znajdą się bardziej kompetentne osoby dzięki, którym uda mi się zweryfikować moją aplikacje. Totalnie nie oczekiwał bym priorytetu w mojej sprawie ale czekanie 1,5 miesiąca na dostęp do bazowego endpointu, który zwraca publiczne informacje dostępne dla każdego kto pojawi się na witrynie Allegro.pl jest mówiąc kolokwialnie lekkim przegięciem. Rozumiem, że portal może mieć dużo takich zgłoszeń ale bez przesady to są publiczne informacje, który każdy bez żadnej weryfikacji może posiąść. 

Co do zgłoszenia to jest zgłoszenie nr "15707581" [ ref:_00D24aE05._5003VFGqu1:ref ] aby nie było, że staram się publicznie przedstawiać nieprawdę. Jest to moja ostatnia prośba w tej sprawię, później dam sobie z tym spokój bo nie ma sensu tracić czasu i nerwów na podmiot gospodarczy, który tak traktuje swoich klientów. Kolejnym krokiem będzie przerzucenie się na jakiś inny portal np. eBay lub Amazon, który swoim poziomem znacznie przerasta ten prezentowany przez Allegro.pl i z godnością i szacunkiem traktuje swoich klientów.

Szczerze powiedziawszy zawsze uważałem Allegro.pl za portal, który ma dominującą pozycje na polskim rynku przez poziom świadczonych usług jednak czas przeszły w tym zdaniu został użyty nie bez powodu, gdyż po takich problemach straciłem jakąkolwiek ochotę na korzystanie z tego portalu i z pewnością zaprzestane dokonywać tam zakupów. 

Rozpoczynając moją pracę magisterską, która w planach miała wykorzystywać Allegro REST API dziwiłem się i nie mogłem uwierzyć w negatywne wpisy użytkowników na temat podejścia do nich i niszczenia ich biznesów oraz stworzonych aplikacji. Szkoda tylko, że Allegro nie jest mi w stanie odpisać, że nie dostane tego dostępu tylko żyje w oczekiwaniu, że to nastąpi kiedyś - kiedy nie wiadomo może za 10 lat ale wtedy to będzie mi totalnie zbędne. Całe szczęście, że to tylko praca magisterska a nie realnie zainwestowane pieniądze.

Zapewne po przeczytaniu tego dostane standardową korporacyjną odpowiedź, że możliwie szybko zostanie to załatwione albo zostanie przekazane do kolejnego działu, w którym utknie na kolejne miesiące. Ciekawi mnie tylko to czy administrator usunie to Issue ze względu na niewygodną wizerunkowo treść. Jeśli nie chcecie Państwo mi przyznać tego dostępu to po prostu dajcie informacje a ja zmienię sobie dostarczyciela usług i problem się rozwiąże, trudno wyrzucę do śmieci czas, który poświeciłem na stworzenie oprogramowania, które wykorzystuje wasze API, o którego jakości oraz czytelności dokumentacji nie będę wspominał bo to kolejna bardzo gorzka niespodzianka ze strony Allegro.

**Comment by MaciejFrackowiak** [comment]
Przykro mi, że oczekujesz na odpowiedź tak długo - niestety, proces weryfikacji jest całkowicie poza nami i nie mamy żadnego wpływu na jego przebieg, w tym czas trwania tej weryfikacji. Ze swojej strony mogę wyłącznie zachęcić Cię do ponownego kontaktu poprzez formularz kontaktowy z przypomnieniem się, choć zapewne otrzymasz również odpowiedź na wiadomość z 5 lipca br.
