### ISSUE TITLE
Edycja wielu ofert jednocześnie: VAT

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4696]
Czy ten sposób zmiany VAT dla wielu ofert jest aktualny?
https://developer.allegro.pl/my_offers/#informacje-o-fakturze

Jest tam używane pole "percentage" którego wg instrukcji przy edycji/wystawianiu pojedynczej oferty nie powinniśmy już używać:
https://developer.allegro.pl/sale/#ustawienia-vat

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Możesz w ten sposób modyfikować informacje o fakturze, jednak w przyszłości przestaniemy wspierać to pole. Po wskazaniu stawki VAT w polu **tax.percentage** przypiszemy do oferty odpowiednie dla kategorii ustawienia VAT. Do tego czasu jednak udostępnimy możliwość grupowego zarządzania informacjami o fakturze w oparciu o nowe pola (**rate**, **subject** i **exemption**).

**Comment by Radeq** [comment]
Ps: jeśli chcemy edytować VAT "po staremu" (tax.percentage) to w przypadku błędu

```
PUT sale/offers/{id}
BAD_REQUEST
Ustawienie VAT o stawce x% nie jest zgodne z wskazaną wartością procentową y%.
```

Można ustawić tax.rate i tax.id na null i zadziała
