### ISSUE TITLE
Baza motocykli "pasuje do" (compatibilityList) stare / nowe ID.  Rozbieżność w zasobach?

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#4698]
Dzień dobry.

Walczymy z błędami o nieprawidłowych sekcjach "compatibilityList", które od dłuższego czasu wstrzymują nam skuteczne zarządzanie aukcjami.

Od opiekuna dostaliśmy informacje, że stare UUID pojazdów zostały zastąpione nowymi, dodatkowo otrzymaliśmy plik CSV, gdzie multi wiersz z jednym UUID jest przypisany do wielu różnych ID numerycznych - przykładowo:

```
3c8addde-551d-459c-b0ee-947c64abd705,19993
3c8addde-551d-459c-b0ee-947c64abd705,19994
3c8addde-551d-459c-b0ee-947c64abd705,19995
3c8addde-551d-459c-b0ee-947c64abd705,19996
```
Id numeryczne są akceptowane w requestach, "stare" UUID już nie - zwracają błąd, że nie ma takiego ID.

Jednak odpytując przykładowo zasób:
`/sale/compatible-products?type=MOTORCYCLE&phrase=HONDA%20VFR%20750%20F`

Otrzymuję listę składającą się ze "starych" nieakceptowanych już w requestach UUID.

Nasz główny problem polega na tym, że nie jesteśmy w stanie nałożyć nowej listy na naszą aktualną bazę bazę wystawiającą, gdzie przykładowy rekord:
`
f3b6fe76-3d1d-416f-8ff8-65e7626abe09 = Honda VFR 750 F (RC24) 101KM/74kW lata prod. 1986-1989`

W nowej notacji każdy rocznik zdaje się mieć swoje własne ID w formie INT, ale nigdzie nie jesteśmy w stanie pobrać danych, że przykładowo nowe ID:

`19997 = Honda VFR (F) 750ccm 98KM 1994`

Czy istnieje jakiś zasób, który pozwala pobierać nowe ID motocykli np. po parametrze "phrase" czy może o pełniejszy plik CSV mamy prosić naszego opiekuna biznesowego? Skąd wynika taka niekonsekwencja w dokumentacji i wprowadzanych zmianach, ktora paraliżuje nasze (i zapewne innych) aukcje oparte o compatibilityList generowany z własnego systemu.

**Comment by MaciejFrackowiak** [comment]
Obecnie, po migracji części motocyklowe otrzymały nowe itemsType=MOTORCYCLE_EXPLODED - możesz to sprawdzić korzystając z [GET /sale/compatibility-list/supported-categories](https://developer.allegro.pl/documentation/#operation/getCategoriesThatSupportCompatibilityList). Zatem, aby otrzymać nowe id zmień swoje zapytanie na /sale/compatible-products?type=MOTORCYCLE_EXPLODED&phrase=HONDA%20VFR%20750%20F.
