### ISSUE TITLE
Czy zapytania GET /sale/products/{id} są limitowane?

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#4699]
Hej,
Próbuję zaktualizować aukcje zgodnie z danymi w produktyzacji.
Żeby to zrobić, jeśli dobrze rozumiem, muszę pobrać dane z oferty, pobrać dane z produktyzacji i przypisać dane z produktyzacji do oferty.
Wszystko wyglądałoby dobrze, tylko.. Zapytania do produktyzacji wracają bardzo powoli. Przy jednym wątku jest to ok 800ms. Przy większej ilości wątków odpytujących jednocześnie, czas rośnie bardzo mocno.

Jeśli limitujecie dostęp do tego zasobu, to czy jest jakiś inny sposób na zaktualizowanie wszystkich aukcji o parametry z produktyzacji? Coś takiego jak jest dostępne na froncie:
![image](https://user-images.githubusercontent.com/24191650/125334853-21dbba80-e34c-11eb-9c58-47fb4b1e013c.png)

**Comment by MaciejFrackowiak** [comment]
Tak, dostęp do GET /sale/products/{productId} podlega również pod [dodatkowy limit](https://developer.allegro.pl/productization/#2-jak-pobra%c4%87-pe%c5%82ne-dane-o-produkcie).
Obecnie nie ma w API dostępnego zasobu umożliwiającego aktualizację oferty danymi z produktu, jak to ma miejsce na stronie WWW. Konieczne jest działanie takie jak opisałeś to w poście.
