### ISSUE TITLE
Błędne sortowanie w doGetMyIncomingPayments

### ISSUE THREAD

**Issue by amarel123** [allegro/allegro-api#47]
Znalazłem bug w endpoincie doGetMyIncomingPayments. W specyfikacji technicznej jest wyraźnie napisane:

> Domyślnie (w przypadku niezdefiniowania zakresu czasu), pobierana jest lista wpłat z przeciągu ostatniego tygodnia (domyślnie 25 ostatnio dokonanych wpłat), posortowana malejąco po czasie ich realizacji.

Kiedy pobieram pierwszą porcję danych dla wybranej aukcji i kupującego, bez definiowania zakresu czasu, lista jest posortowana na odwrót. W tablicy na pierwszych indeksach pojawiają się najstarsze transakcje, a na końcu najnowsze. Zwracam się z prośbą o jak najszybszą poprawę ponieważ dokopanie się do najnowszych transakcji kiedy jest ich dużo zmusi mnie do pobierania wielu stron bez sensu, a to chyba Państwu najbardziej powinno zależeć, aby serwery były jak najmniej obciążone.

ID zgłoszenia: Ticket#1245453721 (23.02.2018) - załączyłem tam XML.

**Comment by MaciejPotepa** [comment]
Korespondowałeś z nami na temat tego zgłoszenia w zgłoszeniu 1245453721 oraz na FB.

Pracujemy nad jego rozwiązaniem. Damy Ci znać - tutaj, jak wyjaśnimy sprawę.

**Comment by amarel123** [comment]
Dziękuję za pamięć. Proszę wybaczyć moje zniecierpliwienie, ale jestem już lekko uprzedzony, zwłaszcza, że pierwszy błąd związany z sandboxem jest nienaprawiony od 2,5 miesiąca i ponieśliśmy przez to straty. Tamtego problemu już tutaj nie opisywałem ponownie ponieważ ostatecznie testy przeprowadzamy na prawdziwym Allegro, jedyny skutek uboczny jest taki, że na Allegro pojawiają się fake aukcje, ale nie pozostawili nam Państwo innego wyjścia, gdyż musielibyśmy zapłacić kary umowne. Natomiast ten błąd jak widać jest nierozwiązany od prawie 2 tygodni, a przecież jest to kwestia zmiany kolejności sortowania danych... Pozdrawiam i liczę na sprawne rozwiązanie problemu.

**Comment by MaciejPotepa** [comment]
Dzień dobry. 

Poprawiliśmy naszą dokumentację tak, aby nie wprowadzała w błąd w tym przypadku. Przepraszamy za wcześniejsze niedogodności.

**Comment by amarel123** [comment]
Dzień Dobry,
myślałem, że w projektach to specyfikacja jest pierwsza i stawiana ponad implementację, ale jak widać w Allegro dostosowuje się wymagania do projektu, a nie na odwrót. Czy istnieje jakiś sposób, aby przy podaniu aukcji i kupującego sortować listę w innej kolejności?

**Comment by TomekKaczmarek** [comment]
Dzień dobry. Listę zwracamy zawsze w tej samej kolejności wpłat - od najstarszej do najnowszej. Niestety nie ma możliwości, by zmienić jej sortowanie.
