### ISSUE TITLE
Błąd podczas próby autoryzacji aplikacji

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#470]
Podczas próby autoryzacji aplikacji (wywołanie urla https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=4b9423ea874048....) występuje następujący błąd: 
"Nie możemy wyświetlić strony
Numer błędu: a8c88ef2fcf92363"

Co może być przyczyną?

**Comment by LukaszKorek** [comment]
Najprawdopodobniej podajesz w zapytaniu w kodzie redirect_url a powinno być redirect_uri.
Proszę o sprawdzenie, cała instrukcja znajduje się tutaj - https://developer.allegro.pl/auth/.

**Comment by 3000auto** [comment]
Mam podobny problem "Nie możemy wyświetlić strony Numer błędu: a6a41b79dd22ef1d"
Link https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=21960179&redirect_uri=https%3A%2F%2Fmicar.usermd.net%2Ffromrest.php - zawiera poprawne parametry w tym redirect_uri zgodnie z https://developer.allegro.pl/auth/

**Comment by dragu** [comment]
@LukaszKorek mam ten sam problem

```

Nie możemy wyświetlić strony
Numer błędu: 7ba024aaa28c5f84

```

Na sandboxie, a na produkcji działa. Adresy są takie same, nazwa parametru ok.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgoszeniu dopisz GitHub #470. Przeanalizuję to i wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
@dragu Sandbox jest odrębnym środowiskiem, dlatego musisz wygenerować nowe clientId na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/.
