### ISSUE TITLE
Sandbox sale/dispute-attachments

### ISSUE THREAD

**Issue by gsti** [allegro/allegro-api#4700]
Witam dostaję cały czas błąd jak poniżej. Jest jakiś problem z sandbox dla rest api?
wysyłka trwa ok 5 sekund po niej dostaję standardowo 504. Dodam jeszcze że plik zajmuje ok 200KB 
{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}

**Comment by MaciejFrackowiak** [comment]
Przed momentem przetestowałem działanie dyskusji na Sandbox - bezproblemowo stworzyłem obiekt załącznika, załadowałem plik o wielkości 222 kB i dodałem go do dyskusji - wszystko przeszło płynnie. 
Proszę podaj mi trace-id Twojego zapytania, postaram się spojrzeć co poszło nie tak w Twoim przypadku.

**Comment by gsti** [comment]
Przed chwilą taki wygenerowałem.
sale/dispute-attachments/8a5a1c5e-cf5b-4562-b160-e610aae10923

**Comment by gsti** [comment]
tak podobny problem jest dla innych załączników. Mam jeszcze jedno pytanie w tym kontekście jaka jest ścieżka dodawania załączników.
deklaracja, wysyłanie załącznika, wysłanie wiadomości z załącznikiem 
czy
deklaracja, wysłanie wiadomości z deklaracja załącznika, wysłanie załącznika

**Comment by MaciejFrackowiak** [comment]
Wzorcowa ścieżka wygląda tak:
1. Deklaracja załącznika,
2. Upload załącznika,
3. Wysłanie wiadomości z załącznikiem.

**Comment by gsti** [comment]
Tak właśnie robię. 

>  a z logów wynika, że sam załącznik do nas w ogóle nie dociera, stąd błąd.

Może to być problem z nieprawidłowym źródłem pliku?

**Comment by MaciejFrackowiak** [comment]
Ciężko to jednoznacznie stwierdzić bez dostępu do samego pliku. Podobnego problemu z uploadem pliku nie zgłosili dotychczas inni użytkownicy, a jak wspmniałem moje testowe uploady różnych plików - co do wielkości, czy typu przeszły bez najmniejszego problemu.
