### ISSUE TITLE
Problem z parametrem Rozmiar

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4703]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Mam problem ze stworzeniem aukcji poprzez API. Uzupełniam wszystkie parametry i otrzymuję takie błędy:
`validation":{"errors":[{"code":"VALIDATION_ERROR","message":"Parameters (129302) are not expected.","details":"","path":"parameters","userMessage":"Parameters (129302) are not expected."},{"code":"VALIDATION_ERROR","message":"Missing required parameters: Size.","details":"","path":"parameters","userMessage":"Missing required parameters: Size."}],"warnings":[],"validatedAt":"2021-07-14T06:21:36.373Z"},"createdAt":"2021-07-14T06:21:36.000Z","updatedAt":"2021-07-14T06:21:36.373Z"}`

Kategoria to 
Allegro - Moda - Odzież, Obuwie, Dodatki - Odzież damska - Jeansy
Nr kategorii 254259

A parametr "129302" to właśnie parametr rozmiar.

 Po zrobieniu updatu z tymi samymi parametrami już wszystko jest w porządku i aukcja normalnie się wystawia. Wygląda jakby był jakiś problem z zasobem POST, a PUT działał dobrze.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem parametry dla kategorii 254259 i widzę, że Rozmiar ma inne id:

```
{
            "id": "54",
            "name": "Rozmiar",
            "type": "dictionary",
            "required": true,
...
```
Tylko same wartości przyjmują postać 129302_xxx.

**Comment by mrezlik** [comment]
Dziękuje za odpowiedź. Prawdopodobnie miałem zapisane nieaktualne parametry i dlatego wydawało mi się, że wszystko jest okej. Nie ma możliwości sprawdzenia, które parametry w jakich kategoriach się ostatnio zmieniły?

**Comment by MaciejFrackowiak** [comment]
Mamy tylko zasób [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation/#operation/getCategoryParametersScheduledChangesUsingGET_1), który informuje o planowych zmianach w obowiązkowości danych parametrów.

**Comment by hahyes** [comment]
Dlaczego nikt nie informuje do przodu o tak poważnych zmianach?! W dużej liczbie kategorii połączyliście dotychczasowo używane parametry "Rozmiar" w jeden parametr o innym identyfikatorze. Ja rozumiem, kiedy jest drobna zmiana w paru kategoriach ale to jest ogromna różnica. Jeszcze na dodatek ja bazując na starym systemie jeszcze z WebAPI stosowałem się dotychczas do zasady, że wartość po identyfikatorze (vel. "54_3" to 3 jest identyfikatorem wartości w słowniku) jest unikatowa. A teraz dostałem klapsa w dziąsło, dosłownie. Bo istnieją takie cuda w jednym parametrze jak "54_2" oraz "129302_2". Niby wartość 2 ale jednak ma kilka różnych identyfikatorów. To jest dramat. Jak mam teraz tysiące aukcji zaktualizować jednocześnie? To jest jakiś żart z waszej strony?!

Szkoda strzępić ryja, naprawdę.

**Comment by MaciejFrackowiak** [comment]
Zgadza się, została przeprowadzona akcja merdżowania parametru Rozmiar w kategoriach modowych. Zawsze powtarzamy, że należy pobierać aktualne drzewo kategorii i parametrów, ponieważ nie są to wartości ustalone raz na zawsze i mogą się zmieniać. Podobnie jak w przypadku samych parametrów i ich identyfikatorów.

**Comment by hahyes** [comment]
> Zgadza się, została przeprowadzona akcja merdżowania parametru Rozmiar w kategoriach modowych. Zawsze powtarzamy, że należy pobierać aktualne drzewo kategorii i parametrów, ponieważ nie są to wartości ustalone raz na zawsze i mogą się zmieniać. Podobnie jak w przypadku samych parametrów i ich identyfikatorów.

Nic mi po drzewie kategorii, jeżeli miałem zapisane wartości słownikowe dla danego produktu w bazie. Wystarczyło dać informację, że będziecie to łączyć. Nie wiem, użyć wymienionego wcześniej zasobu do informowania, że coś takiego ma mieć miejsce (ale widzę, że z zapowiedzi informowania o zmianach w drzewie kategorii wyszły powidła w temacie samych parametrów). Podać dane nowego parametru i pozwolić ludziom się przygotować na to. 

Zamiast tego mamy teraz parametr pełen dziwacznych wartości słownikowych wymieszanych ze starymi. Raz 54, raz 3806, raz 129302, absolutnie bez powodu. Skoro już łączycie wszystko do jednego parametru, zróbcie z wartościami słownikowymi jakiś porządek. Rozumiem potrzebę ujednolicenia parametrów, tylko z drugiej strony nie na pałę.

**Comment by MaciejFrackowiak** [comment]
Nie możemy w jednym podejściu dokonać połączenia parametrów i zmienić ich wszystkie ID jednocześnie. Obecnie parametr Rozmiar przyjął globalne ID=54. Również w przypadku wartości parametrów ich zapisywanie na stałe nie jest dobrym rozwiązaniem - one również mogą się zmieniać, co pokazała przeprowadzona operacja połączenia parametru Rozmiar.
