### ISSUE TITLE
Przesyłanie zdjęć do towaru

### ISSUE THREAD

**Issue by dichady** [allegro/allegro-api#4704]
Po wysłaniu zapytania '/sale/offers' , jest pole Images, przekazuję do niego images:[{url:"https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXQ9QVcJY8gulRPQV6CF7b9mMPaQhMgfAVT4uvxcwYy1qPJIzsV6oTlloPbzq6mZr3UlTIJ7sFy2LqQ9t2nxkS6rD8A51Cb"}]. i zwraca EROR (niepoprawnie wypełniony obiekt), a następnie próbował przesłać zdjęcie na serwer, i tak błąd, i zmienił na inne zdjęcie: https://st.depositphotos.com/3265665/4462/i/600/depositphotos_44627471-stock-photo-transparent.jpg
Również błąd.
Proszę o pomoc

**Comment by dichady** [comment]
Interfejs API pokazuje przesyłanie zdjęć z linku, w interfejsie API musimy podać https lub http (pełny link przed plikiem). Wskazujemy go i pojawia się błąd ładowania.

**Comment by hahyes** [comment]
Do ofert dodaje się jedynie linki przesłanych zdjęć na serwerach Allegro. Musisz najpierw przesłać zdjęcia według poradnika: https://developer.allegro.pl/sale/#5-zdj%C4%99cia
