### ISSUE TITLE
Dwa błędy

### ISSUE THREAD

**Issue by noname994** [allegro/allegro-api#4705]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Widzimy następujące błędy, proszę o weryfikację: 

REQUEST: 
POST /sale/offers HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer XXX
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json
Content-Length: 3280
Expect: 100-continue

`
{"name":"Buty DC Shoe Studio 2 3BK czarne tenis\u00f3wki 41","afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"a2f5e179-fa72-4b54-9d4f-72f76ddb4889"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"category":{"id":"257929"},"payments":{"invoice":"VAT"},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"delivery":{"shippingRates":{"id":"82bd8369-ebb9-480a-bd43-ec55941e95d1"},"handlingTime":"PT24H"},"images":[{"url":null},{"url":null},{"url":null},{"url":null},{"url":null},{"url":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Buty DC Shoe Studio 2 3BK czarne tenis\u00f3wki 41<\/h1><ul><li>Kolor czarny,<\/li><li>Realizacja zam\u00f3wienia w ci\u0105gu 24 h<\/li><li>Sk\u0142ad wierzch: materia\u0142 tekstylny, sk\u00f3ra,<\/li><li>Produkt Oryginalny<\/li><\/ul><p>   Sportowe buty DC idealne do szko\u0142y lub na skatepark.           Super solidne buty DC.             Budowa: Low Top.      Otwory wentylacyjne po boku.       Sk\u0142ad: Wierzch : Skora naturalna.            Podeszwa : Zewn\u0119trzna - Guma, kauczuk Pill Pattern.              Ekstremalnie wytrzyma\u0142e obuwie dc.    <\/p><p>rozmiar: <b>41<\/b><\/p><p>Stara cena: 299.00 z\u0142<\/p><h1>Cena: 199 z\u0142<\/h1>"},{"type":"IMAGE","url":null}]},{"items":[{"type":"IMAGE","url":null}]},{"items":[{"type":"IMAGE","url":null}]},{"items":[{"type":"IMAGE","url":null}]},{"items":[{"type":"IMAGE","url":null}]},{"items":[{"type":"IMAGE","url":null}]}]},"sellingMode":{"format":"BUY_NOW","price":{"amount":199,"currency":"PLN"}},"stock":{"available":"1","unit":"UNIT"},"publication":{"durationUnlimited":true},"parameters":[{"id":3766,"valuesIds":["3766_1"],"values":[],"rangeValue":null},{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":15851,"valuesIds":["15851_2"],"values":[],"rangeValue":null},{"id":127848,"valuesIds":["127848_1"],"values":[],"rangeValue":null},{"id":203085,"valuesIds":["203085_4"],"values":[],"rangeValue":null},{"id":219629,"valuesIds":["219629_286869"],"values":[],"rangeValue":null},{"id":219857,"valuesIds":["219857_287861"],"values":[],"rangeValue":null},{"id":64,"valuesIds":["64_215185"],"values":[],"rangeValue":null},{"id":451,"valuesIds":["451_2"],"values":[],"rangeValue":null},{"id":7108,"valuesIds":["7108_132"],"values":[],"rangeValue":null},{"id":22728,"valuesIds":["22728_3"],"values":[],"rangeValue":null},{"id":203105,"valuesIds":["203105_215381"],"values":[],"rangeValue":null},{"id":215918,"valuesIds":[],"values":["Studio 2"],"rangeValue":null},{"id":215926,"valuesIds":[],"values":["wiosna-lato 2020"],"rangeValue":null},{"id":217481,"valuesIds":[],"values":["guma"],"rangeValue":null},{"id":224017,"valuesIds":[],"values":["ADYS300406-3BK"],"rangeValue":null},{"id":232289,"valuesIds":["232289_366645"],"values":[],"rangeValue":null},{"id":127048,"valuesIds":["127048_1024"],"values":[],"rangeValue":null},{"id":203093,"valuesIds":[],"values":["26.5"],"rangeValue":null},{"id":203097,"valuesIds":["203097_215233"],"values":[],"rangeValue":null},{"id":203101,"valuesIds":["203101_215317"],"values":[],"rangeValue":null},{"id":225693,"valuesIds":[],"values":["3613375474863"],"rangeValue":null}]}
`
RESPONSE:
HTTP/1.1 100 Continue

HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: ca2fe97290d638fe
date: Wed, 14 Jul 2021 11:08:27 GMT
x-content-type-options: nosniff
content-type: application/json
transfer-encoding: chunked
`
{"errors":[{"code":"INVALID_JSON","message":"Invalid request.","details":null,"path":null,"userMessage":"Invalid request."}]}

`
__________________________________________________________________________________________________

REQUEST: 
POST /sale/images HTTP/1.1
Host: upload.allegro.pl
Authorization: Bearer XXX
accept: application/vnd.allegro.public.v1+json
content-type: application/vnd.allegro.public.v1+json
Content-Length: 73

{"url":"http:\/\/api.hiphopshop.pl\/images\/dc_size_charts_tabela_7.jpg"}

RESPONSE:
HTTP/1.1 422 Unprocessable Entity
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1 ; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: b116f52fe60846cf
referrer-policy: no-referrer
date: Wed, 14 Jul 2021 11:08:26 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 1200

{"errors":[{"code":"DownloadError","message":"Downloading image from URL 'http://api.hiphopshop.pl/images/dc_size_charts_tabela_7.jpg' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: '{\"message\":\"upstream connect error or disconnect/reset before headers. reset reason: local reset\",\"destination\":{\"path\":\"/get?url=http%3A%2F%2Fapi.hiphopshop.pl%2Fimages%2Fdc_size_charts_tabela_7.jpg&max_size=26214400\",\"serviceTag\":null,\"host\":\"public-downloader\",\"originalDst\":null},\"code\":\"LR,UO\",\"details\":{\"connectionId\":5012100}}\n'.","details":null,"path":null,"userMessage":"Downloading image from URL 'http://api.hiphopshop.pl/images/dc_size_charts_tabela_7.jpg' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: '{\"message\":\"upstream connect error or disconnect/reset before headers. reset reason: local reset\",\"destination\":{\"path\":\"/get?url=http%3A%2F%2Fapi.hiphopshop.pl%2Fimages%2Fdc_size_charts_tabela_7.jpg&max_size=26214400\",\"serviceTag\":null,\"host\":\"public-downloader\",\"originalDst\":null},\"code\":\"LR,UO\",\"details\":{\"connectionId\":5012100}}\n'."}]}

**Comment by hahyes** [comment]
W pierwszym zapytaniu masz nulle zamiast linków do zdjęć.

**Comment by MaciejFrackowiak** [comment]
Kwestię uploadu zdjęć wyjaśniam w wątku https://github.com/allegro/allegro-api/issues/4706.
