### ISSUE TITLE
Czy występuje jakiś problem z przesyłaniem zdjęć?

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4706]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy próbie uploadu zdjęć dostaję błąd w zwrotce. Czy może być to coś od was?
```json
{
  "message": "no healthy upstream",
  "code": "UH",
  "details": {
    "connectionId": 7103893
  },
  "destination": {
    "originalDst": null,
    "host": "public-downloader",
    "serviceTag": null,
    "path": "/get?url=https%3A%2F%2Fstatic2.redcart.pl%2Ftemplates%2Fimages%2Fproducts%2F16973%2F67c7ed3d066873500f0b4a6a20f52209.jpg&max_size=26214400"
  }
}
```

**Comment by shambo666** [comment]
u mnie to samo, na tą chwilę jest trochę lepiej ale problemy dalej występują

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykłady, sprawę przekazałem do weryfikacji, wrócę z odpowiedzią.

**Comment by premax** [comment]
Ja próbuję wywoływać zasób https://api.allegro.pl/sale/product-offers i co chwila dostaję losowe zwrotki:

`Downloading image from URL 'https://www.abe.pl/cv/blarge/7/2/0/9780198308720.jpeg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'DNS resolve failed'.","details":null,"path":"images","userMessage":"Downloading image from URL 'https://www.abe.pl/cv/blarge/7/2/0/9780198308720.jpeg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'DNS resolve failed'."`

Albo (z tym samym URL):

`"Downloading image from URL 'https://www.abe.pl/cv/blarge/7/2/0/9780198308720.jpeg' failed. Server returned the following HTTP status code: 502 BAD_GATEWAY and response body: 'Failed to connect to remote server'.`

Albo się udaje - raz na 10 razy.

Nie jest to kwestia serwera ani URL, bo zmieniałem na inny hostowany zupełnie gdzie indziej i też działa jak zepsuty kierunkowskaz, tzn. bardziej nie działa niż działa.

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, mieliśmy dzisiaj dwukrotnie problem z uploadem zdjęć - na chwilę obecną usługa działa już poprawnie, zdjęcia są prawidłowo zapisywane. Przepraszam za niedogodności.

**Comment by bartozi** [comment]
Problem występuje nadal, przed chwilą znowu pojawił się błąd. Na "dobrą" sprawę występuje on od 2,3 miesięcy z różną intensywnością.

**Comment by MaciejFrackowiak** [comment]
@bartozi Czy problem jest nadal aktualny? Jeśli zauważysz nieprawidłowości, proszę daj nam znać, wówczas przekażę sprawę do weryfikacji.

**Comment by bartozi** [comment]
Wystawiłem dzisiaj 8 aukcji i jak dotąd jest bezbłędnie. Natomiast nieprawidłowości w tym zakresie występuję od kilku dobrych tygodni. Czasem przez kilka dni jest wszystko w porządku, a czasem bywa tak że przez te błędy nie jesteśmy w stanie zrealizować połowy dziennej normy, można się wówczas owściekać. Zgłaszałem problemy dostawcy oprogramowania, myśląc że to coś po jego stronie. Dopiero wczoraj zostałem przekierowany tutaj.

**Comment by mateuszbieniascontelizer** [comment]
bład nadal wyspuje

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Proszę podaj więcej szczegółów byśmy mogli zweryfikować działanie usługi.

@bartozi Jak wspomniałem - gdy natrafisz na problem, proszę daj nam znać na forum, wówczas możemy zweryfikować sytuację.

**Comment by mateuszbieniascontelizer** [comment]
DownloadError - Downloading image from URL 'https://storage.waw.cloud.ovh.net/v1/AUTH_57db3a7ead234cb5afc4eec99f55117c/clients_images/2e69cd6316158e877777825387eb1040.jpg' failed. Server returned the following HTTP status code: 502 BAD_GATEWAY and response body: 'Failed to connect to remote server'.

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Dziękuję za przykład, analizujemy źródło powracającego problemu.

**Comment by bartozi** [comment]
U mnie również pojawiły się błędy:

"Informacje o błędach zmiany statusu oferty:
Poniższe błędy mogą mięć wpływ na brak synchronizacji oferty z aplikacji Allegro Droplo z ofertą Allegro.
Przesłanie zdjęcia się nie powiodło. Powód: The server is not able to complete the request. Please try again in a few minutes."

Dotyczy to kilku ofert. Od kilkunastu minut nie możemy wystawić nic.

**Comment by MaciejFrackowiak** [comment]
@bartozi Analizujemy globalnie pojawiające się problemy z uploadem zdjęć.

**Comment by mateuszbieniascontelizer** [comment]
czy udało się rozwiązać problem?

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Przeprowadziliśmy już część prac, które znacząco powinny poprawić efektywność działania. Staramy się jednak, aby to nie było działanie doraźne, dlatego w dalszym ciągu będziemy prowadzić prace, których celem jest zwiększenie niezawodności uploadu.

**Comment by bartozi** [comment]
Niestety problem występuje nadal. Dzisiaj kompletnie nic nie da się wystawić.

**Comment by premax** [comment]
> Niestety problem występuje nadal. Dzisiaj kompletnie nic nie da się wystawić.

A u mnie działa.

**Comment by MaciejFrackowiak** [comment]
@bartozi Mógłbyś podać więcej szczegółów? Na pierwszy rzut oka nie widzimy problemów.

**Comment by bartozi** [comment]
Za każdym razem gdy próbuję coś wystawić na końcu pojawia się komunikat "Przesłanie zdjęcia się nie powiodło. Powód: The server is not able to complete the request. Please try again in a few minutes."

**Comment by MaciejFrackowiak** [comment]
@bartozi Sam komunikat niewiele nam powie - potrzebujemy trace-id wywołania. Jeżeli go nie posiadasz, to autor oprogramowania powinien się z nami skontaktować i przekazać niezbędne dane do weryfikacji.

**Comment by bartozi** [comment]
Obecnie problem zniknął i można już swobodnie pracować. Gdyby pojawił się w przyszłości, postąpię zgodnie z Pana zaleceniami.
