### ISSUE TITLE
Problem z offer-events

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4707]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Zauważyłem, że dzisiaj od rana mam problem z zasobem offer-events. Otóż od godziny 6:50 otrzymuję pełno id offer, które zostały zmienione. Problem jest taki, że większość z tych ofert zakończyła się ponad 2 miesiące temu (więc nie ma żadnej możliwości, żeby się zmieniły). Do tej pory z kilku kont allegro uzbierało mi się prawie 2mln takich rekordów. Oczywiście wśród nich będą, które naprawdę się zmieniły, ale większość to jednak jakieś dziwne przypadki. Wklejam przykładową odpowiedź:
`https://api.allegro.pl/sale/offer-events?from=MTYyNjIzODg0OTY0NjU0Mw&limit=100 requestBody= responseBody={"offerEvents":[{"id":"MTYyNjIzODg1MDMyNDY0OA","type":"OFFER_CHANGED","occurredAt":"2021-07-14T05:00:39.547Z","offer":{"id":"10704459083","publication":{"endedBy":"EXPIRATION"},"external":{"id":"stocksell_948933322"}}},{"id":"MTYyNjIzODg1MzM5ODMzNw","type":"OFFER_CHANGED","occurredAt":"2021-07-14T05:00:43.291Z","offer":{"id":"10704942030","publication":{"endedBy":"EXPIRATION"},"external":{"id":"stocksell_865749345"}}}]} `

Oferta zakończona 17 maja, a pojawia się, że została zmieniona dzisiaj o 5 rano.

**Comment by dlis2010** [comment]
`endedBy":"EXPIRATION`
Tutaj masz powód. Oferta przeniesiona do archiwum.

Swoją drogą w którym momencie oferty przechodzą do archiwum? Różne 60 dni co do sekundy czy w końcowy dzień o różnych godzinach moga pojawić się przeniesienia?

**Comment by MaciejFrackowiak** [comment]
@mrezlik Eventy, które zauważyłeś zostały wyemitowane nadmiarowo - nie wysyłamy ich dla zakończonych ofert, a w tym przypadku niestety miało to miejsce. Pracujemy już, aby zapobiec podobnym sytuacjom w przyszłości, przepraszam za niedogodności.

**Comment by MaciejFrackowiak** [comment]
@dlis2010 Co do zasady liczy się stricte 60 dni co do sekundy, jednak mechanizm odświeża takie oferty cyklicznie, raz na dobę.
