### ISSUE TITLE
Server error in sandbox environment

### ISSUE THREAD

**Issue by morozov312** [allegro/allegro-api#4708]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] z logowaniem lub autoryzacją
 - [ ] inny

:beetle: **Opis**

For the second day, I get http error 503 with some frequency when requesting GET/offers/listing
Could this be a problem on my side?

**Comment by MaciejFrackowiak** [comment]
Yes, I can confirm that we have a problem with that resource on Sandbox. We are already working to restore proper operation.

**Comment by MaciejFrackowiak** [comment]
We have fixed it and now a resource works fine.
