### ISSUE TITLE
Nie można utworzyć szkicu

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4709]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam,

Dzisiaj zauważyłem, że mam problem z wystawianiem szkicu na koncie allegro. Dostaję informację, że jest ponad 20k draftów, ale logując się na allegro i sprawdzając jest ich tam niecałe 15k. Czy ten limit się zmienił w ostatnim czasie czy powinienem inaczej sprawdzać ich liczbę niż przez Licytacje -> "Szkic"?

**Comment by MaciejFrackowiak** [comment]
Nie, limit nie zmienił się i wynosi 20 tysięcy szkiców. W kwestii działania Allegro via strona WWW proszę skontaktuj się z nami poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - tak uzyskasz najszybciej wsparcie.

**Comment by hahyes** [comment]
> Czy ten limit się zmienił w ostatnim czasie czy powinienem inaczej sprawdzać ich liczbę niż przez Licytacje -> "Szkic"?

Tak, w REST API możesz sprawdzić liczbę szkiców odpytując zasób https://developer.allegro.pl/redoc/redoc-static.html#operation/searchOffersUsingGET z parametrem `publication.status=INACTIVE`. Status `INACTIVE` to są po prostu szkice. 

Natomiast szkice możesz usuwać tym zasobem: https://developer.allegro.pl/redoc/redoc-static.html#operation/deleteOfferUsingDELETE

**Comment by pawelosajda** [comment]
@mrezlik Czy problem dalej u Ciebie dalej występuje? Obserwuję coś podobnego, allegro zwraca błąd o przekroczeniu limitu a liczba draftów jest dużo poniżej 20k.
