### ISSUE TITLE
Nie wystawia się aukcja

### ISSUE THREAD

**Issue by hjgtutgb** [allegro/allegro-api#471]
2 miesiące temu został wykonany system do wystawiania.
Kilka dni temu chciałem zacząć korzystać ale aukcje nie wystawiają się, nie ma żadnego komunikatu o błędzie. Nie jest zwracany żaden komunikat.
Gdy zmienię cokolwiek, zabiorę jakiś parametr, jest komunikat o jego braku.

Co może być przyczyną?

**Comment by MarcinLuczak** [comment]
@hjgtutgb obsługujemy zgłoszenia dotyczące API, jeżeli dotyczą one poziomu interfejsu. Oznacza to, że operujemy na requestach i responsach w XML i JSON-ach.

Twoje pytanie jest zbyt ogólne, nie podałeś żadnych szczegółów. Jeżeli chcesz zgłosić problem, napisz na czym on polega, której metody (WebAPI) lub zasobu dotyczy (REST API). Podaj komunikat błędu jaki otrzymujesz. Do zgłoszenia najlepiej załącz request i response, w którym widać problem (cURL-e requesta i response w przypadku REST API).

**Comment by hjgtutgb** [comment]
Nie wiem jak to zrobić. Ogólnie nie zwraca żadnego błędu i jednocześnie nie wystawia. ten sam skrypt dwa miesiące temu wystawiał.

Jak wyświetlić  request i respons?

**Comment by hjgtutgb** [comment]
wysyłane jest taka tablica:
Array
(
    [name] => Oferta testowa 2
    [category] => Array
        (
            [id] => 76104
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => Array
                (
                    [id] => 3806
                    [valuesIds] => Array
                        (
                            [0] => 3806_5
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [2] => Array
                (
                    [id] => 451
                    [valuesIds] => Array
                        (
                            [0] => 451_65536
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [3] => Array
                (
                    [id] => 3786
                    [valuesIds] => Array
                        (
                            [0] => 3786_85
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [4] => Array
                (
                    [id] => 3766
                    [valuesIds] => Array
                        (
                            [0] => 3766_8
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [5] => Array
                (
                    [id] => 201017
                    [valuesIds] => Array
                        (
                            [0] => 201017_2317
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [6] => Array
                (
                    [id] => 202641
                    [valuesIds] => Array
                        (
                            [0] => 202641_212457
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [7] => Array
                (
                    [id] => 202657
                    [valuesIds] => Array
                        (
                            [0] => 202657_512
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [8] => Array
                (
                    [id] => 128188
                    [valuesIds] => Array
                        (
                            [0] => 128188_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

        )

    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 

Tekstowy opis przedmiotu

                                        )

                                )

                        )

                    [1] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 

Tekstowy oooopis przedmiotu

                                        )

                                )

                        )

                )

        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 99
                    [currency] => PLN
                )

            [startingPrice] => 
            [minimalPrice] => 
        )

    [stock] => Array
        (
            [available] => 10
            [unit] => UNIT
        )

    [publication] => Array
        (
            [duration] => 
            [status] => INACTIVE
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => abb4b883-4a86-43d7-8853-ec3f5109112d
                    [handlingTime] => P2D
                )

        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => 49df5d0c-998b-40f6-a33b-598f2c36e80f
                )

            [returnPolicy] => Array
                (
                    [id] => df648e58-b2dc-4adc-8835-6f819d06307a
                )

            [warranty] => Array
                (
                    [id] => 3735928c-e16b-40df-8fb3-63332dab7e37
                )

        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => WIELKOPOLSKIE
            [city] => Poznań
            [postCode] => 60-166
        )

)
Array
(
    [id] => 85d73cd1-2290-40ed-b2e5-92c9233a3238
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)
Array
(
    [id] => 85d73cd1-2290-40ed-b2e5-92c9233a3238
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)


A odpowiedź jest taka:
Array
(
    [id] => 85d73cd1-2290-40ed-b2e5-92c9233a3238
    [taskCount] => Array
        (
            [total] => 0
            [success] => 0
            [failed] => 0
        )

)

**Comment by MarcinLuczak** [comment]
@hjgtutgb z jakiego zasobu korzystasz? Udostępnij proszę pełne (czyli także z nagłówkami) cURL-e z requestem i responsem.

**Comment by hjgtutgb** [comment]
Zasób REST API.
Draft aukcji jest tworzony i przechodzi walidację nie zwracając żadnego błędu. Następnie aktywuję aukcję poprzez zasób "offer-publication-commands" wysyłając PUT prze curl. Przykład: {"offerCriteria":[{"offers":[{"id":"7502514811"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}

A response jakie dostaje to: {"id":"6e8e72e9-5e6f-40f9-af15-5cb3b205e6df","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by AniaMalinowska** [comment]
Aby to sprawdzić należy użyć metody GET/sale/offer-publication-commands/{commandId}  - tam otrzymasz prawidłowe zestawienie.
Wyjaśniam, że w odpowiedzi do metody PUT do publikacji zawsze otrzymasz same zera - bo system w momencie wysłania przed walidacją nie jest w stanie podać, ile zadań zakończy się powodzeniem, a ile nie.
Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/sale/#step-7-offer-publication-commands).

**Comment by hjgtutgb** [comment]
To da odpowiedź, czy akcja się wystawiła. Nie nie wystawiła się. Pytanie dlaczego.
Miesiąc temu wystawiała się a dziś bez jakichkolwiek zmian w kodzie nie wystawia się.
Draft aukcji jest tworzony i przechodzi walidację! a aukcja nie wystawia się. Dlaczego?

**Comment by hjgtutgb** [comment]
przy wystawianiu oferty i sprawdzeniu potem tego przez "sale/offer-publication-commands/uuid/tasks" wywala coś takiego: {"tasks":[{"offer":{"id":"7503727613"},"message":"Could not change offer publication status. Estimated shipping time may not be empty.","status":"FAIL","scheduledAt":"2018-08-10T21:23:20.002+02:00","finishedAt":"2018-08-10T21:23:21.811+02:00","field":"publication"}]}

**Comment by hjgtutgb** [comment]
cennik w allegro tak zwraca puste pole shippingTime
Nie mam na to wpływu.

Array
--
  | (
  | [id] => abb4b883-4a86-43d7-8853-ec3f5109112d
  | [name] => Bareo
  | [rates] => Array
  | (
  | [0] => Array
  | (
  | [deliveryMethod] => Array
  | (
  | [id] => 7203cb90-864c-4cda-bf08-dc883f0c78ad
  | )
  |  
  | [maxQuantityPerPackage] => 100
  | [firstItemRate] => Array
  | (
  | [amount] => 14.00
  | [currency] => PLN
  | )
  |  
  | [nextItemRate] => Array
  | (
  | [amount] => 0.00
  | [currency] => PLN
  | )
  |  
  | [shippingTime] =>
  | )
  |  
  | )
  |  
  | [lastModified] => 2018-08-10T19:58:13.043Z
  | )

**Comment by pfunkowski** [comment]
Handling time to odrębny parametr oferty, nie łącz go z cennikiem. Od nie
dawna jest polem wymaganym.

pt., 10 sie 2018, 22:10 użytkownik hjgtutgb <notifications@github.com>
napisał:

**Comment by hjgtutgb** [comment]
handlingTime jest przekazywany

'delivery' => array(
			'shippingRates' => array(
				'id' => $id_cenika_dostawy,
				'handlingTime' => 'P2D'))

**Comment by MarcinLuczak** [comment]
@hjgtutgb dla których opcji dostawy w cennikach dla shippingTime dostajesz puste pole/null?

Przy okazji prośba - gdy chcesz pokazać coś w swoim requeście lub responsie, zawsze udostępniaj pełne cURL-e requesta i response'a. Nie wklejaj wycinków z samymi danymi lub wyciętych struktur.
