### ISSUE TITLE
Błędy przy tworzeniu wniosków o zwrot prowizji

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4710]
Witam,
próbuję dla niektórych transakcji stworzyć wnioski o zwrot prowizji (ponieważ nikt ich nie opłacił). Dostaje niestety w kilku przypadkach dziwne błędy:

Przypadek 1:
```
POST /order/refund-claims
200 OK
<?xml version="1.0" encoding="UTF-8"?>
<error>
<code>100003</code>
<message/>
</error>
```

Przypadek 2:
```
422 
{"errors":[{"code":"VALIDATION_ERROR","message":"Oferta: f4570452-b0fd-11eb-8f88-bf71f2abfeec ilość przekroczona, dostępna: 0, żądana: 1","userMessage":"Oferta: f4570452-b0fd-11eb-8f88-bf71f2abfeec ilość przekroczona, dostępna: 0, żądana: 1"}]}
```

Co oznaczają te błędy? Żaden z tych błędów nie informuje mnie dokładnie, co robię nie tak.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi trace-id swoich wywołań, to pozwoli zlokalizować requesty. Tak na pierwszy rzut oka, w drugim przypadku chcesz dokonać zwrot za 1 sztukę, ale ten zwrot został już wykonany.
