### ISSUE TITLE
billings/billing-entries

### ISSUE THREAD

**Issue by grab95** [allegro/allegro-api#4712]
Występuje problem: 
Zwrot prowizji nie jest przpisany do zamówienia

https://api.{environment}/billing/billing-entries

Podczas pobierania bilingów nie nie mozna polaczyc ze soba oplaty ze zwrotem aby ta sie wyzerowala

**Comment by MaciejFrackowiak** [comment]
Numer zamówienia zwracamy tylko dla naliczenia prowizji, zgodnie z [newsem](https://github.com/allegro/allegro-api/issues/4528).

**Comment by grab95** [comment]
przez to nie da sie powiazac naliczonej prowizji z jej zwrotem, np z powodu anulacji zamowienia przez klienta. przez co nie mam mozliwosci zredukowac poniesionych kosztów w systemie. Uważam że to wada API którą można by poprawić

**Comment by MaciejFrackowiak** [comment]
Takiego powiązania zwrotu z zamówieniem nie ma również w serwisie WWW:

![Screenshot 2021-07-16 at 07-04-07 Allegro pl - Więcej niż aukcje Najlepsze oferty na największej platformie handlowej ](https://user-images.githubusercontent.com/53566763/125894718-e29a3949-5202-4c4e-b5f9-d362bc5f5961.png)

Swoją sugestię zmiany zamieść proszę w dziale [Discussions](https://github.com/allegro/allegro-api/discussions) - dzięki temu inni użytkownicy również będą mogli oddać na nią swoje głosy.
