### ISSUE TITLE
Zdublowane parametry po ostatnich zmianach

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4713]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Znalazłem po ostatnich zmianach parę baboli, wiec zgłaszam.
Dla kategorii 148002 zwracany jest podwójny parametr Rozmiar (54 i 248345) oraz dla kategorii 316073 jest zwracany podwójny parametr Długość (2977 i 248496).

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie, wyjaśniam zauważone rozbieżności, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Parametry w obu kategoriach zostały uporządkowane.

**Comment by hahyes** [comment]
Dziękuję za reakcję, zamykam wątek.
