### ISSUE TITLE
sandbox - nie można wystawić aukcji

### ISSUE THREAD

**Issue by cohubodev** [allegro/allegro-api#4714]
Dzień dobry, założyłem konto na sandboxie allegro, po kliknięciu w wystaw przedmiot : 

Ta witryna jest nieosiągalna Nie udało się znaleźć adresu IP serwera ze stroną staging-lokalnie.allegrogroup.com.
Wypróbuj te rozwiązania:

Sprawdź połączenie
Sprawdź serwer proxy, zaporę sieciową i konfigurację DNS
Uruchom Diagnostykę sieci systemu Windows
ERR_NAME_NOT_RESOLVED

czy obecnie jest jakiś problem w tej kwestii? jeśli tak to kiedy zostanie rozwiązany?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z bezpośredniego odnośnika: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie
