### ISSUE TITLE
sale/offer-events i filtrowanie po numerze oferty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4715]
Czy jest jakiś zasób lub jakiś sposób na użycie sale/offer-events, żeby można było wylistować zdarzenia dotyczące konkretnej oferty?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie, [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents) umożliwia filtrowanie tylko po typie eventu, limicie oraz evencie, od którego zasób ma zwrócić kolejne eventy.
