### ISSUE TITLE
Brak możliwości wejścia na strone sandboxa przy uzyciu Cypressa

### ISSUE THREAD

**Issue by tiagon97** [allegro/allegro-api#4717]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Cześć, chciałem popisać testy automatyczne frontu/API na waszym sandboxie, aczkolwiek dostaje bląd gdy chce wejść na strone przy użyciu Cypressa

Sorry, we could not load:
https://allegro.pl.allegrosandbox.pl/
403 - Forbidden (text/html)

**Comment by tiagon97** [comment]
![image](https://user-images.githubusercontent.com/48652792/125994220-3cf8c9d0-6059-4886-9080-1fb6697509ff.png)
Czy mogę się ubiegać o jakiś specjalny dostęp, żebym nie był traktowany jako bot? Testy automatyczne na przykładzie sandboxa podałem jako temat pracy licencjackiej...

**Comment by hahyes** [comment]
Twoje testy triggerują zabezpieczenia przeciwko botom. Czy obsługujesz JavaScript? Jeśli tak, pomyślałbym też nad zmianą UserAgent na jakiś przeglądarkowy.

**Comment by tiagon97** [comment]
> Czy obsługujesz JavaScript?
Tak

>  pomyślałbym też nad zmianą UserAgent na jakiś przeglądarkowy
zmieniłem w rezultacie otrzymuje 
![image](https://user-images.githubusercontent.com/48652792/126117454-1d5eccaa-8e59-480e-bc3e-b9cca1369722.png)

Jakieś rady?

**Comment by MaciejFrackowiak** [comment]
Twoje działanie odbiega od standardowego działania użytkownika, przez co uruchamiane są mechanizmy zabezpieczające. W ten sposób chronimy dostęp do Sandboxa dla innych użytkowników. Nie udzielamy żadnych specjalnych dostępów czy też uprawnień.

**Comment by tiagon97** [comment]
Pytałem już w jednym wątku, przed zatwierdzeniem tematu pracy licencjackiej czy mogę używać sandboxa do testów automatycznych, dostałem odpowiedź, że tak.
https://github.com/allegro/allegro-api/issues/4444

W takim razie nic się nie da zrobić?

**Comment by hahyes** [comment]
> > Czy obsługujesz JavaScript?
> 
> Tak
> 
> > pomyślałbym też nad zmianą UserAgent na jakiś przeglądarkowy
> 
> zmieniłem w rezultacie otrzymuje
> ![image](https://user-images.githubusercontent.com/48652792/126117454-1d5eccaa-8e59-480e-bc3e-b9cca1369722.png)
> 
> Jakieś rady?

Dostałeś bana (raczej tymczasowego) na dany adres IP. Do testów pomyślałbym o VPNie. :)

Musisz zachowywać się jak zwykły użytkownik, po prostu. Działanie Cypressa nie może odbiegać od zachowania zwykłego użytkownika. Inaczej, zawsze będziesz łapany. Pewnie sprawdzają też, jak często odpytujesz. Myślę, że trzeba zachować ileś sekund odstępu pomiędzy zapytaniami.

Generalnie trochę lipa, nie wiem czy da się takie coś przeprowadzić na Cypressie. Osobiście zrezygnowałbym z Allegro jako "obiektu testowego". Ostatnio dodane zabezpieczenia są dosyć ostre i niektórzy normalni użytkownicy się nawet na nie łapią.

**Comment by MaciejFrackowiak** [comment]
@tiagon97 Twoje testy nie mogą naruszać integralności Sandbox. Jeżeli zachowanie oprogramowania wykracza poza normy działania standardowego użytkownika, to nie są to już testy, które moglibyśmy uznać tylko "za testy".

**Comment by tiagon97** [comment]
Dlatego we wcześniejszym wątku #4444 , jasno zapytałem o TESTY AUTOMATYCZNE a nie manualne, co znaczy ingerencje jakiegoś narzędzia na Wasze środowisko testowe, więc czuje się lekko wprowadzony w błąd przez jedną osobę z waszego teamu.

**Comment by MaciejFrackowiak** [comment]
Rozumiem, miej jednak na uwadze, że jest to środowisko przeznaczone dla każdego użytkownika i musi ono działać niezawodnie, a testować można mając na uwadze odpowiednie natężenie ruchu.
