### ISSUE TITLE
Czy jest jakis regulamin opisujący jakie treści można wysyłać do klient w ramach własnej komunikacji e-mail

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#4718]
Witam,
Integrując się z platformą Allegro nasze oprogramowanie wysyła również swoje dodatkowe wiadomości informujące kupującego o przebiegu transakcji czy jest jakiś regulamin opisujący jakie treści są dozwolone w ramach tego typu wiadomości?

Pozdrawiam
Marcin Butlak

**Comment by MaciejFrackowiak** [comment]
W tej sprawie skontaktuj się proszę z obsługą serwisu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - tak uzyskasz szczegółowe informacje jakie treści można, a jakich nie można przesyłać.

**Comment by makerlabs** [comment]
Dziękuje za informacje.
