### ISSUE TITLE
REST API - podstawowe pytania / rozpoczęcie pracy

### ISSUE THREAD

**Issue by FlySoftpl** [allegro/allegro-api#4719]
Dzień dobry, 
mam prośbę o pomoc w rozwianiu wątpliwości w sprawach związanych z wykorzystaniem REST API. Tworzymy aplikacje fakturująco - magazynowe i chcielibyśmy stworzyć program pobierający dane o zamówieniach złożonych przez klientów danego użytkownika programu w celu ułatwienia obsługi tego zamówienia (m.in. pobranie danych kontrahenta, danych do wystawienia faktury, danych o zamówionych towarach itp). Mając na uwadze informacje zawarte w regulaminie https://developer.allegro.pl/rules/ chciałbym się upewnić czy dobrze rozumiem pewne kwestie: 

1) czy Client ID oraz Client Secret generuję i zaszywam w aplikacji, którą udostępniam klientom? czy też każdy klient chcący korzystać z aplikacji generuje je na swoim koncie i prowadza do programu samodzielnie? Czy zaszycie tych kodów w aplikacji z której będzie korzystał nasz klient nie jest złamaniem regulaminu? cyt: 3.9. "Użytkownicy, którzy wygenerowali Klucz REST API, nie mogą udostępniać tego Klucza osobom trzecim" 

2) nie rozumiem, również zapisu który nie pozwala na : pkt4.2. "...., bądź uzależnione jest od wykorzystania loginu i hasła Użytkowników, niebędących Twórcami Oprogramowania REST API" skoro mój klient kupujący program nie jest twórcą oprogramowania a używanie przez niego aplikacji będzie wymagało zalogowania do serwisu Allegro.pl jego danymi w celu otrzymania tokenu to czy nie jest to łamaniem tego punktu? 

3) pkt 4.3. mówi: "Twórcy Oprogramowania REST API zobowiązani są w każdym przypadku do podania Użytkownikom Oprogramowania REST API rzetelnej i pełnej informacji dotyczącej zasad korzystania z Oprogramowania REST API (w tym obejmującej wymogi i zasady określone Regulaminem) i polityki bezpieczeństwa dotyczącej danych jego użytkowników" w jakiej formie i zakresie mam podawać użytkownikom taką informację? Czy to ma być link do tego regulaminu? https://developer.allegro.pl/rules/ Bardzo proszę o pomoc w prawidłowej interpretacji tych zapisów. 

Nie chciałbym czegoś opacznie zrozumieć i spowodować w związku z tym problemów z dostępem do REST API. 

pozdrawiam
Sławomir Mucha

**Comment by jakubmaguza** [comment]
1. Z tego co piszesz, wychodzi na to, że to aplikacja desktopowa. W takim przypadku najbezpieczniej byłoby zrobić własny backend, który będzie logował użytkownika i generował bearer token. Możesz w teorii wrzucić client id + secret bezpośrednio do swojej aplikacji, ale jeśli trafi ona w niepowołane ręce, to ktoś może się podszyć pod Twoją firmę, tworząc inną aplikację, która np. wykrada dane. Mało prawdopodobne, ale skoro napisałeś o tym na forum publicznym, to prawdopodobieństwo się zwiększa.

2. Nie wiem na jakim etapie jesteś w logowaniu przy użyciu OAUTH. Tutaj klient nie podaje hasła ani loginu tobie, ani Twojej aplikacji. Wpisuje je bezpośrednio w allegro, a ty od allegro otrzymujesz token umożliwiający wysyłane zapytań. 

3. To raczej link do własnego regulaminu

PS. Nie jestem z Allegro.

**Comment by MaciejFrackowiak** [comment]
@FlySoftpl Odpowiadając na wątpliwości:

1.  Sugerowanym przez nas rozwiązaniem jest, aby aplikacja przedstawiała się jednym ClientID, co w efekcie nie wymusza na jej użytkownikach osobnej rejestracji swoich własnych ClientID;
2. Tu przede wszystkim mamy na myśli sytuację, w której tworzyłbyś własną bazę danych z loginami oraz hasłami użytkowników. Jak wspomniał @jakubmaguza oparcie się na OAuth rozwiązuje ten problem - otrzymujesz tylko token;
3. To wewnętrzny regulamin aplikacji, który powinien być w zgodzie z regulaminem API Allegro. Co więcej, warto użytkowników uświadomić na jakie operacje dają zgodę Twojej aplikacji - sugerujemy wdrożenie obsugi [scope`ów](https://developer.allegro.pl/auth/#scope-w-api-allegro), dzięki czemu aplikacja wykorzystuje tylko niezbędne dane.

**Comment by FlySoftpl** [comment]
Bardzo dziękuję za te cenne wskazówki.

**Comment by adgparts55** [comment]
Witam @FlySoftpl  czy moglby pan dla mnie napisac na maila adgparts55@gmail.com? Mam kilka pytan, oraz chcialby panu zaproponowac jedne rozwiazania dotyczace mojej strony internetowej, poniewaz nie mam dostepu do api aplikacji, a mam dosyc wielka strone internetowa. Dziekuje
