### ISSUE TITLE
offers-listing

### ISSUE THREAD

**Issue by expondo** [allegro/allegro-api#472]
Bardzo byłoby pomocne aby w metodzie offers-listing były dostępne sumy sprzedanych sztuk na każdej ofercie jak w starym API. Obecnie są tylko sprzedane sztuki z ostatnich 30 dni.
Czy dodacie tą informację do tej metody?

**Comment by expondo** [comment]
to czy w ogóle dacie jakieś narzędzia do monitorowania skoro tego nie udostępnicie i nie będzie dziennika zdarzeń?

**Comment by MaciejPotepa** [comment]
Niestety na ten moment nie udostępniamy takich informacji w nowych narzędziach.  

W nieokreślonej przyszłości będziemy chcieli to zaadresować, ale nie jestem w stanie podać żadnej, nawet przybliżonej daty. 

Przepraszam za niedogodności, wiem, że to nie jest idealne rozwiązanie, ale to jedyne co teraz udostępniamy.
