### ISSUE TITLE
Nie dziala skrypt, prosze o pomoc.

### ISSUE THREAD

**Issue by Dawidek990** [allegro/allegro-api#4721]
Witam, Posiadam skrypt ktory sciaga od danego uzytkownika(ktorego mu wskaze bez zalogowania do niego) Tytuly, kategorie, ceny i linki do zdjec aukcji na allegro.

Jednak nie wiem czemu nie dziala, czy kto moze mi pomoc co trzeba zrobic?
Kilka miesiecy temu dzialal, ale aktualnie wywala mi blad "Something went wrong 111"

Link do skryptu:
https://www.transfernow.com/dl/202107186fZQ0ZAL

tst to plik wyjsciowy z danymi.

**Comment by MaciejFrackowiak** [comment]
Ten skrypt nie jest naszego autorstwa, dlatego trudno nam się odnieść co do właściwego jego działania. Być może któryś z użytkowników forum będzie mógł Tobie pomóc.

**Comment by Dawidek990** [comment]
Nie jest waszego autorstwa? czyli kogo?
 i co w zwiazku z tym? przeciez pytam wszystkich osob o to nie was, nawet nie wiem kim jestes.

**Comment by MaciejFrackowiak** [comment]
Kogo - Allegro.

Jak wspomniałem - być może któryś z użytkowników forum będzie mógł Tobie pomóc.

**Comment by damianszymanskiphp** [comment]
Pomogłbym ale jesteś pajacem i nie będę wspierał takich ludzi. Naucz się kultury i wróć.
