### ISSUE TITLE
Tworzenie produktu wraz z oferta

### ISSUE THREAD

**Issue by dichady** [allegro/allegro-api#4722]
Dzień dobry,
Określamy pole "Podstawowe parametry" (Nazwa przedmiotu) , a po załadowaniu ofert nie są one powiązane z produktami (produkty nie są tworzone). Ale ręcznie, za pośrednictwem strony moje-allegro/sprzedaz/moje-oferty mogę powiązać oferty, tworząc produkty (bez zmiany zawartości pól "Podstawowe parametry" (Nazwa przedmiotu)). Jak być? Czy możliwe jest automatyczne tworzenie produktu wraz z ofertą?

**Comment by MaciejFrackowiak** [comment]
Aby wystawić ofertę wraz z przypisanym produktem, którego nie ma jeszcze w naszej bazie skorzystaj z zasobu [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) - szczegółowe informacje opisujące krok po kroku każdy etap znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/).
