### ISSUE TITLE
Pobranie informacji o aukcji - prośba o wyjaśnienie dla laika

### ISSUE THREAD

**Issue by casadecorata** [allegro/allegro-api#4723]
Dzień dobry,

Na wstępie chcę zaznaczyć, że nie jestem programistą, znam jedynie podstawy HTML ze szkoły. Chcąc skorzystać z opcji Wystaw przez formularz natknąłem się na brak wystrczających informacji dotyczących formatowania opisu aukcji w Excelu. W ściągnietym formularzu zostało opisane jedynie formatowanie tekstu jednak pominięto informacje dotyczące formatowania grafik tj. wstawienia zdjęcia lub zdjęcia z tekstem obok. 

Okazuje się, że aby poprawnie wypełnić ściągniętego Excela nie wystarczą podstawy HTML i należy przechodzić przez skomplikowane (dla mnie) procedury:
1. Rejestracji aplikacji na https://apps.developer.allegro.pl/ - udało się
2. Intalacji XAMPP lub innej aplikacji do obsługi PHP - udało się
3. Uzyskanie tokenu dostępowego zgodnie z instrukcją zamieszczoną na https://developer.allegro.pl/getting_started/ - udało się
4. Wykonanie prostego zapytania które pobiera dane  zgodnie z instrukcją zamieszczoną na https://developer.allegro.pl/getting_started/ - udało się - mój kod i odpowiedź poniżej
5. Skorzystanie z GET /sale/offers/{offerId}, aby pobrać opis konkretniej aukcji - NIE UDAŁO SIĘ

```
<?php

define('CLIENT_ID', 'tutaj wpisałem Client_ID'); // wprowadź Client_ID aplikacji
define('CLIENT_SECRET', 'tutaj wpisałem Client_Secret'); // wprowadź Client_Secret aplikacji

function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;
}

function getAccessToken() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    return json_decode($tokenResult)->access_token;
}

function getMainCategories($token) {
    $headers = array("Authorization: Bearer {$token}", "Accept: application/vnd.allegro.public.v1+json");
    $url = "https://api.allegro.pl/sale/categories";
    $ch = getCurl($headers, $url);
    $mainCategoriesResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($mainCategoriesResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    $categoriesList = json_decode($mainCategoriesResult);
    return $categoriesList;
}

function main()
{
    $token = getAccessToken();
    $main_categories = getMainCategories($token);
    var_dump($main_categories);
}

main();
```

i otrzymałem odpowiedź

`object(stdClass)#27 (1) { ["categories"]=> array(13) { [0]=> object(stdClass)#1 (5) { ["id"]=> string(1) "5" ["name"]=> string(12) "Dom i Ogród" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#2 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [1]=> object(stdClass)#3 (5) { ["id"]=> string(5) "11763" ["name"]=> string(7) "Dziecko" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#4 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [2]=> object(stdClass)#5 (5) { ["id"]=> string(36) "42540aec-367a-4e5e-b411-17c09b08e41f" ["name"]=> string(11) "Elektronika" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#6 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(true) ["productCreationEnabled"]=> bool(true) ["customParametersEnabled"]=> bool(true) } } [3]=> object(stdClass)#7 (5) { ["id"]=> string(36) "4bd97d96-f0ff-46cb-a52c-2992bd972bb1" ["name"]=> string(15) "Firma i usługi" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#8 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [4]=> object(stdClass)#9 (5) { ["id"]=> string(36) "a408e75a-cede-4587-8526-54e9be600d9f" ["name"]=> string(17) "Kolekcje i sztuka" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#10 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(false) } } [5]=> object(stdClass)#11 (5) { ["id"]=> string(36) "38d588fd-7e9c-4c42-a4ae-6831775eca45" ["name"]=> string(18) "Kultura i rozrywka" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#12 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [6]=> object(stdClass)#13 (5) { ["id"]=> string(36) "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0" ["name"]=> string(4) "Moda" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#14 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [7]=> object(stdClass)#15 (5) { ["id"]=> string(1) "3" ["name"]=> string(11) "Motoryzacja" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#16 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [8]=> object(stdClass)#17 (5) { ["id"]=> string(5) "20782" ["name"]=> string(14) "Nieruchomości" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#18 (6) { ["variantsByColorPatternAllowed"]=> bool(false) ["advertisement"]=> bool(true) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(false) } } [9]=> object(stdClass)#19 (5) { ["id"]=> string(4) "3919" ["name"]=> string(17) "Sport i turystyka" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#20 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [10]=> object(stdClass)#21 (5) { ["id"]=> string(6) "258832" ["name"]=> string(11) "Supermarket" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#22 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [11]=> object(stdClass)#23 (5) { ["id"]=> string(4) "1429" ["name"]=> string(5) "Uroda" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#24 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } [12]=> object(stdClass)#25 (5) { ["id"]=> string(6) "121882" ["name"]=> string(7) "Zdrowie" ["parent"]=> NULL ["leaf"]=> bool(false) ["options"]=> object(stdClass)#26 (6) { ["variantsByColorPatternAllowed"]=> bool(true) ["advertisement"]=> bool(false) ["advertisementPriceOptional"]=> bool(false) ["offersWithProductPublicationEnabled"]=> bool(false) ["productCreationEnabled"]=> bool(false) ["customParametersEnabled"]=> bool(true) } } } }`

Niestety nie wiem jak skorzystać z GET /sale/offers/{offerId} . Po kliknięciu w tę frazę przenosi mnie do https://developer.allegro.pl/documentation/#tag/User's-offer-information i niestety nie wiem jak powinien wyglądać kod w całości żeby wysłać prawidłowe zapytanie o opis jednej z moich aukcji.

Pozdrawiam,
Casa Decorata

**Comment by MaciejFrackowiak** [comment]
Wystawianie ofert poprzez API nie opiera się na pliku Excela - czy Ty chcesz skorzystać z opcji [Wystaw z pliku](https://allegro.pl/moje-allegro/sprzedaz/wystaw-z-pliku)? Jeżeli tak, to w przypadku pytań proszę skontaktuj się poprzez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)

**Comment by casadecorata** [comment]
Kontaktowałem się z tą sprawą przez formularz kontaktowy (zgłoszenie nr 16513801) i zostałem odesłany tutaj. Chcę skorzystać z opcji **Wystaw z pliku** i jest dla mnie bardzo dziwnym, że w tym samym pliku w zakładce **Przykład z opisem danych** odsyłacie Państwo klientów do https://developer.allegro.pl/sale/#5-opis-oferty jeżeli chcą poznać więcej informacji tylko odnośnie formatowania opisu.

![Opis Oferty](https://user-images.githubusercontent.com/87612510/126110803-05d0bbc5-18c3-4557-bcce-402abc9163ae.JPG)


Czy uważają Państwo za zasadne przechodzenie przez cały proces łączenia się z API, tylko po to aby uzyskać informację o zakodowaniu 5 podstawowych funkcjonalności dodania zdjęć w opisie aukcji? Te funkcjonalności, o których mówie są zaznaczone poniżej na print screenie tj.:
1. Dodaj kolejny wiersz
2. Tylko zdjęcie
3. Zdjęcie i tekst
4. Tekst i zdjęcie
5. Dwa zdjęcia

![Funkcjonalności](https://user-images.githubusercontent.com/87612510/126110773-7d5542dd-98bb-4fa3-b134-328c6643404c.JPG)

**Comment by MaciejFrackowiak** [comment]
Niestety, otrzymałeś błędną informację - na GitHub nie wspieramy opcji wystawiania ofert przez pliki płaskie. Trudno mi się zatem odnieść do Twoich uwag dot. procesu wystawiania oraz jego przebiegu. Korzystając z API do wystawiania ofert można opierać się na [poradniku](https://developer.allegro.pl/sale/) przez nas przygotowanym, gdzie w punktach 5 i 6 opisaliśmy proces uplodu zdjęć oraz wymogów dot. opisu ofert. Proszę skontaktuj się z supportem raz jeszcze odpowiadając na wcześniejsze zgłoszenie.
