### ISSUE TITLE
No rate limit at /authentication/phone-number/web/code/verification

### ISSUE THREAD

**Issue by tusharrecon** [allegro/allegro-api#4724]
##Description:

The correct OTP for every phone number is `123456`. Navigate to account settings in allegro.pl.allegrosandbox.pl and try to add a phone number, an OTP will be sent to your provided number. Enter 123456 as the OTP, it will be successfully changed.

There is no protection from brute force attempts at all in the sandbox env., you are only allowing to test the sandbox environment on Hackerone, so how can we even test this functionality if this is totally different from the production env.

Thank You

**Comment by PrzemyslawLukanowski** [comment]
We don't send messages to phone numbers on Sandbox Environment, so it's not possible to test this functionality.

**Comment by tusharrecon** [comment]
Ahh!! I see.

No problem ,I am already invited to the private program.


Thank you for the quick response.
