### ISSUE TITLE
POST /sale/product-offers zdjęcia domyślne - błąd OfferGallerySizeException

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#4725]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

Korzystam z uproszczonego wystawiania oferty powiązanej z produktem (który już istnieje w Allegro) - https://developer.allegro.pl/product_offers/

W zapytaniu nie przekazuję opisu ani zdjęć (description, images). Otrzymuję błąd:

`POST sale/product-offers || trace-id:15992d8de1a3d091`
```
    0 => {#1496
      +"code": "OfferGallerySizeException"
      +"message": "Unprocessable Entity"
      +"details": null
      +"path": "images"
      +"userMessage": "Przekroczono limit 10 zdjęć w ofercie."
    }
```

Produkt pod który się podpinam ma 15 zdjęć ( `GET sale/products/{id} || trace-id:de05e6f352095d08` ) . Zapewne klient ma konto zwykłe a osoba tworząca produkt konto firmowe. Ucinanie zdjęć może być problematyczne, ponieważ mogą się one również znajdować w opisie. Proszę o uwzględnienie przypadku.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Tak, w tym przypadku użytkownik posiada konto zwykłe. Konsultuję ten temat z naszym zespołem, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Dodaliśmy odpowiednie rozwiązanie, dzięki któremu nie otrzymasz już wspomnianego błędu w opisanej przez Ciebie sytuacji. Dla konta zwykłego przypiszemy maksymalnie 10 zdjęć z naszej bazy produktowej.
