### ISSUE TITLE
Missing required parameters: Size.

### ISSUE THREAD

**Issue by mateuszbieniascontelizer** [allegro/allegro-api#4726]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

https://api.allegro.pl/sale/offers

stare parametry 

605035	-	client_product_id
76034	-	allegro_category_id
{
	"11323": "11323_246514",
	"3786": "3786_109",
	"3806": "3806_6",
	"451": "451_2",
	"3766": "3766_1",
	"201021": "201021_208241",
	"59": "59_8",
	"18293": "18293_1",
	"201017": "201017_2377",
	"127708": "127708_10",
	"201037": "62",
	"201033": "69",
	"201025": "201025_2521",
	"201041": "56",
	"15851": "15851_1",
	"215922": "",
	"215926": "",
	"215918": "",
	"201049": "",
	"201045": "",
	"215930": "",
	"201029": "",
	"216925": "",
	"17448": "",
	"225693": ""
}

nowe id parametru rozmiar mimo tego błąd opisywany poniżej

605035	-	client_product_id
76034	-	allegro_category_id

{
	"11323": "11323_246514",
	"3786": "3786_109",
	"451": "451_2",
	"3766": "3766_1",
	"201021": "201021_208241",
	"59": "59_8",
	"18293": "18293_1",
	"201017": "201017_2377",
	"127708": "127708_10",
	"201037": "62",
	"201033": "69",
	"201025": "201025_2521",
	"201041": "56",
	"15851": "15851_1",
	"215922": "",
	"215926": "",
	"215918": "",
	"201049": "",
	"201045": "",
	"215930": "",
	"201029": "",
	"216925": "",
	"17448": "",
	"225693": "",
	"54": "3806_6"
}

Podczas walidacji draftów dostajemy taki błąd "Missing required parameters: Size".
Kategorie świeże, parametry rozmiar z nowymi id, mimo tego dla części produktów taki błąd występuje, większość przechodzi gładko 
id categorii gdzie występuje problem na ten moment, jednakże nie zawsze
124264
254259
254260
254778
254779
258922
76034
76035
76036
76043
76044
76076
76083
76084
76095
76103
76104
78137
87842
91193

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać trace-id dla przypadków, gdzie odpowiedzieliśmy komunikatem "Missing required parameters: Size"?
