### ISSUE TITLE
billing-entries nie raaguje na parametr offset

### ISSUE THREAD

**Issue by hryniak** [allegro/allegro-api#4729]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

GET "https://api.allegro.pl/billing/billing-entries?limit=1&offset=0" -H "Accept: application/vnd.allegro.public.v1+json" -H "Authorization: ...."

zwraca dokładnie takiego samego response jak

GET "https://api.allegro.pl/billing/billing-entries?limit=1&offset=1" -H "Accept: application/vnd.allegro.public.v1+json" -H "Authorization: ...."

podobnie jeśli podaje limit 100 i odpowiednio offset 0 lub 100

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu - parametr offset w moim przypadku działa prawidłowo. Prześlij nam proszę przykładowy request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu dopisz, że dane dotyczą wątku #4729 na Githubie.

**Comment by hryniak** [comment]
Dziękuję za odpowiedź i sorry, błąd był po naszej stronie :-(
