### ISSUE TITLE
How does doSendPostBuyForm method works?

### ISSUE THREAD

**Issue by A2lEX** [allegro/allegro-api#473]
Hello, i have the problem with doSendPostBuyForm method. When I request method I receive something like that:

```
[postBuyForm] => stdClass Object
  | (
  | [transactionId] => 884000000
  | [transactionPackageIds] => stdClass Object
  | (
  | )
  |  
  | [transactionPayByLink] => stdClass Object
  | (
  | [actionHttpMethod] => POST
  | [actionUrl] => NP_PAYGW_URL_PAYMENT_NEW
  | [actionData] => stdClass Object
  | (
  | [item] => Array
  | (
  | [0] => stdClass Object
  | (
  | [actionKey] => pos_id
  | [actionValue] => NP_PAYGW_POS_ID
  | )
  |  
  | [1] => stdClass Object
  | (
  | [actionKey] => pos_auth_key
  | [actionValue] => NP_PAYGW_POS_AUTH_KEY
  | )
```

but where can i get these values? 
NP_PAYGW_URL_PAYMENT_NEW, NP_PAYGW_POS_ID etc??? 

And one more question: Are there some payment methods when it's possible to pay by card?

**Comment by MarcinLuczak** [comment]
@A2lEX we are supporting our API at interface level, so you should share some XML files with request and response, where problem is visible.

If you need payment methods, which you can use in [doSendPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,1140?lang=en), you should call [doGetPaymentMethods](https://allegro.pl/webapi/documentation.php/show/id,1144?lang=en). If in offer, where you want to fill post buy form, is pay by card method - doGetPaymentMethods will get you this information.

Everything is described in documentation of [doSendPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,1140?lang=en) method.

**Comment by MarcinLuczak** [comment]
@A2lEX you already created post buy form. In last response from your comment, you received transactionId = 887234853. It's your post buy form.

And as if comes to broken link to PDF - we will fix this.

**Comment by A2lEX** [comment]
Thank you for answer, but I still don't understand how does it work) 

In documentation for method doSendPostBuyForm 'Output parameters' tab in example i see something like that

<pre>$dosendpostbuyform_response = array(
   'postBuyForm' => array(
      'transactionId' => 45367221,
      'transactionPackageIds' => array(46353511),
      'transactionPayByLink' => array(
         'actionHttpMethod' => 'POST',
         'actionUrl' => 'https://www.platnosci.pl/np/UTF/newpayment.action',
         'actionData' => array(
            array(
               'actionKey' => 'pos_id',
               'actionValue' => '33230'),
            array(...),
            array(
               'actionKey'  => 'email',
               'actionValue'  => 'adres@email.pl'),
            array(...),
            array(
               'actionKey'  => 'sig',
               'actionValue'  => 'f05216ce23e5e987224de602051740f0'))))
);</pre>

And I can understand how i can build payment form, but I received like that 

<pre>
stdClass Object
  (
  | [postBuyForm] => stdClass Object
  | (
  | [transactionId] => 888771793
  | [transactionPackageIds] => stdClass Object
  | (
  | )
  |  
  | [transactionPayByLink] => stdClass Object
  | (
  | [actionHttpMethod] => POST
  | [actionUrl] => NP_PAYGW_URL_PAYMENT_NEW
  | [actionData] => stdClass Object
  | (
  | [item] => Array
  | (
  | [0] => stdClass Object
  | (
  | [actionKey] => pos_id
  | [actionValue] => NP_PAYGW_POS_ID
  | )
  |  
  | [1] => stdClass Object
  | (
  | [actionKey] => pos_auth_key
  | [actionValue] => NP_PAYGW_POS_AUTH_KEY
  | )
  |  
  | [2] => stdClass Object
  | (
  | [actionKey] => ts
  | [actionValue] => 1534495620
  | )
</pre>

Or in other words - how can I build payment form if I know only transactionId? 
Sorry for bothering

PS: http://serwis.platnosci.pl/view/admin/ckeditor/uploaded_images/110518135351_dokumentacja_platnosci.pl_2011-05-16.pdf Link also broken

**Comment by A2lEX** [comment]
@MarcinLuczak, Hello, do you have news?)

**Comment by MarcinLuczak** [comment]
@A2lEX hello Alex. I'm sorry that you wait so long. Give me a day or two more, and I will be back with some informations. Thanks.

**Comment by MarcinLuczak** [comment]
@A2lEX Hello Alex

Thank you for your patience. I asked you about it, because I needed some time, to check the future of this method. And, unfortunately, the news are that this method will be removed soon. So I suggest, that there is no need to use your time to use method, which will be removed soon. Sorry for this.

**Comment by A2lEX** [comment]
@MarcinLuczak Hello)

I'm very upset for this situation, may be there is another method?

I need a way to build a payment form items i bought, cannot find anything like that in webapi. Thank you for a help)

**Comment by MaciejPotepa** [comment]
@A2lEX WebAPi won't be further developed. 

We will release all new resources in REST API. 

You can find our latest resource considering Orders [here](https://developer.allegro.pl/en/orders/).
