### ISSUE TITLE
nazwy parametrów, możliwe wartości, skąd brać? hakować? 

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4730]
Przy wystawianiu oferty numer 10926727464 w kategorii 105337 otrzymuję błąd: 

`
"Missing required parameters: State, Brand, Width, Height, Product Code."`

Mogę wejść przez www, zmieniać parametry i zgadywać, że na przykład "State" oznacza czy produkt jest nowy czy używany, że parametr jest definiowany jako 

`
  		{
  			"id" : "11323",
  			"rangeValue" : null,
  			"values" : [],
  			"valuesIds" : [
   				"11323_2"
  			]
  		},
`

oraz że może mieć wartość "11323_2" (znaczy uzywany) lub "11323_1" (znaczy że nowy). 

Ale czy jest gdzieś dokumentacja nazw parametrów, dozwolonych wartości, aby nie trzeba było tak kombinować?

**Comment by hahyes** [comment]
A trzeba było poradnik przeczytać najpierw: https://developer.allegro.pl/sale/#3-kategorie-i-parametry ;)

**Comment by PrzemyslawLukanowski** [comment]
Dodam jeszcze, że w kontekście parametrów, za pomocą:
-  [GET /sale/offers/unfilled-parameters](https://developer.allegro.pl/my_offers/#jak-sprawdzi%c4%87-nieuzupe%c5%82nione-parametry-w-ofertach) - sprawdzisz nieuzupełnione parametry obowiązkowe w ofertach;
- [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/my_offers/#jak-sprawdzi%c4%87-przysz%c5%82e-zmiany-w-parametrach) - sprawdzisz przyszłe zmiany w wymagalności parametrów.

**Comment by leszekdubiel** [comment]
Faktycznie po kliknięciu w dokumentacji, aby pokazać response wszystko staje się jasne. 
Dziękuję.
