### ISSUE TITLE
billing Zwrot kosztów powiązać z zamówieniem

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#4731]
:bulb: **Sugestia**
Proszę dla zasobu billing/billing-entries 
dla operacji billingowej REF zwrot kosztów przypisać numer zamówienia.

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z naszym [newsem](https://github.com/allegro/allegro-api/issues/4337), przenoszę Twoją sugestię do zakładki Discussions.
