### ISSUE TITLE
Błąd przy aktualizacji ofert - "Dany parametr możesz podać tylko raz"

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#4732]
Zauważyliśmy dzisiaj, że przy aktualizacji parametrów ofert serwer zwraca w/w błąd, mimo, że parametry nie są zdublowane.

Przykładowe zapytanie:
PUT, https://api.allegro.pl/sale/offers/10218893068
`{"afterSalesServices":{"impliedWarranty":{"id":"e5bc4fab-32d3-4e1d-b36b-2f523e7c01d8"},"returnPolicy":{"id":"c4d79249-a4d5-48ec-8123-a60f19401be9"},"warranty":{"id":"ffc6680f-a27f-46fa-849a-3c66a3a87ade"}},"category":{"id":"76085"},"delivery":{"handlingTime":"PT120H","shippingRates":{"id":"f16eb099-825d-426c-b2e4-b4544ddfcf86"}},"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Czapka zimowa</h1><ul><li><b>Kolor: 7 \\u015bredni Br\\u0105z</b></li><li>Sk\\u0142ad-kompozycja: 80% we\\u0142na, 20% poliamid</li><li>Wysoko\\u015b\\u0107: 21 cm</li><li>Obw\\u00f3d: 38 - 60 cm</li><li>Cechy dodatkowe: Unisex</li></ul>"}]},{"items":[{"type":"TEXT","content":"<p>Podana cena dotyczy 1 szt produktu</p>"}]},{"items":[{"type":"TEXT","content":"<p>Kod produktu: 16827-820431</p>"}]}]},"external":{"id":"id-16827/var-150966/set-1"},"id":"10218893068","images":[{"url":"https://a.allegroimg.com/original/110487/fe13b27644b5a980c09ae1e219f9"}],"location":{"countryCode":"PL","province":"POMORSKIE","postCode":"80-180","city":"Gda\\u0144sk"},"name":"Czapka zimowa","payments":{"invoice":"VAT"},"parameters":[{"id":11323,"valuesIds":["11323_1"]},{"id":3786,"valuesIds":["3786_85"]},{"id":3806,"valuesIds":["3806_381541"]},{"id":451,"valuesIds":["451_2048"]},{"id":3766,"valuesIds":["3766_8"]},{"id":201017,"valuesIds":["201017_257870"]},{"id":54,"valuesIds":["54_381565"]}],"sellingMode":{"format":"BUY_NOW","price":{"amount":146.01,"currency":"PLN"}},"stock":{"available":4,"unit":"UNIT"},"tax":{"percentage":"23.00"}}`

Nagłówki zapytania:
["Authorization: Bearer <token>","Accept: application\/vnd.allegro.public.v1+json","content-type: application\/vnd.allegro.public.v1+json","User-Agent: Mozilla\/5.0 (Windows NT 5.1; rv:38.0) Gecko\/20100101 Firefox\/38.0","Connection: keep-alive","Accept-Language: pl","Accept-Encoding: deflate"]

Odpowiedź:
{"errors":[{"code":"VALIDATION_ERROR","message":"You can only enter the parameter once.","details":"ConstraintViolationException.NoDuplicateIds","path":"parameters","userMessage":"Dany parametr możesz podać tylko raz."}]}

Nagłówki odpowiedzi:
    [url] => https://api.allegro.pl/sale/offers/10218893068
    [content_type] => application/json
    [http_code] => 422
    [header_size] => 369
    [request_size] => 1550
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.321384
    [namelookup_time] => 1.8E-5
    [connect_time] => 0.010591
    [pretransfer_time] => 0.106385
    [size_upload] => 1536
    [size_download] => 223
    [speed_download] => 693
    [speed_upload] => 4779
    [download_content_length] => -1
    [upload_content_length] => 1536
    [starttransfer_time] => 0.11714
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 5.134.213.11
    [certinfo] => Array
        (
        )
    [primary_port] => 443
    [local_ip] => 10.65.36.87
    [local_port] => 53482

**Comment by PrzemyslawLukanowski** [comment]
Przekazujesz podwójnie parametr "Rozmiar" - raz jako 3806 (stare ID, które już nie występuje w tej kategorii), raz jako 54 (nowe ID).

**Comment by rasskabak** [comment]
Dziękuję, chyba pomogło :). Nie mniej było by bardzo użyteczne, gdyby błąd był jednoznaczny i nie wprowadzał w błąd (NoDuplicateIds, kiedy w rzeczywistosci duplikat był w nazwie atrybutu, a nie w Id).
