### ISSUE TITLE
Allegro Sandbox problem z wystawieniem aukcji

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4737]
Witam,
Próbuję poprzez Postman wystawić aukcję, po wysłaniu request otrzymuję status OK, ale pojawiają się pewne problemy dotyczące niektórych parametrów oraz z brakiem wymaganych uprawnień "sprzedaż zablokowana". Na allegro sandbox pojawia się wystawiony produkt ale tylko jako szkic. Sprawdziłam poprawność tokenu, czy konto jest ustawione jako firmowe oraz poprawność powiązania aplikacji, ale wszystko jest wydaje się poprawne. Niecałe dwa miesiące temu wysyłałam już aukcje przez Postaman i było wszystko poprawnie, a teraz nie działa.  
Nie wiem gdzie szukać błędu lub co robię źle. Poniżej podaję url, request oraz response. 
url: https://api.allegro.pl.allegrosandbox.pl/sale/offers
request:
{
    "name": "Rzęsy i akcesoria Natural 107 1 para sztucznych rzęs Black",
    "product": {

        
        "parameters": [
            {
                "name": "EAN",
                "values": [
                    "074764607102"
                ]
            },
            {
                "id": "11323",
                "valuesIds": [
                    "11323_1"
                ]
            }
        ],
        "sellingMode": {
            "price": {
                "amount": "15.05",
                "currency": "PLN"
            }
        },
        "stock": {
            "available":1
        },
        "publication": {
            "duration": null,
            "status": "ACTIVE",
            "startingAt": null,
            "endingAt": null,
            "endedBy": null,
            "republish": false
        },
        "delivery": {
            "shippingRates": {
                "id": "005febe7-bfa5-4759-9e18-bc562881f05c"
            },
            "handlingTime": "PT72H",
            "additionalInfo": "",
            "shipmentDate": null
        },
        "payments": {
            "invoice": "NO_INVOICE"
        },
        "sizeTable": null,
        "location": {
            "countryCode": "PL",
            "province": "MAZOWIECKIE",
            "city": "Warszawa",
            "postCode": "03-924"
        },
        "description": {
            "sections": [
                {
                    "items": [
                        {
                            "type": "TEXT",
                            "content": "<p>$Profesjonalne sztuczne rzęsy Natural zostały wykonane z naturalnego, ludzkiego włosia, które zostało poddane sterylizacji. Zostały umieszczone na bezbarwnym, elastycznym pasku, który po nałożeniu na powiekę staje się niewidoczny. Sztuczne rzęsy są długie i gęste - doskonale podkreślą spojrzenie.</p>"
                        }
                    ]
                }
            ]
        }
    }
}

response:
{
    "id": "7680613721",
    "name": "Rzęsy i akcesoria Natural 107 1 para sztucznych rzęs Black",
    "category": null,
    "product": null,
    "parameters": [],
    "customParameters": null,
    "description": null,
    "compatibilityList": null,
    "tecdocSpecification": null,
    "images": [],
    "sellingMode": null,
    "tax": null,
    "stock": null,
    "publication": {
        "duration": null,
        "status": "INACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null,
        "republish": false
    },
    "delivery": null,
    "payments": {
        "invoice": "NO_INVOICE"
    },
    "discounts": null,
    "afterSalesServices": null,
    "additionalServices": null,
    "sizeTable": null,
    "fundraisingCampaign": null,
    "promotion": {
        "emphasized": false,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": null,
    "external": null,
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [
            {
                "code": "VALIDATION_ERROR",
                "message": "Location may not be empty.",
                "details": "",
                "path": "location",
                "userMessage": "Location may not be empty."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Payments may not be empty.",
                "details": "",
                "path": "payments",
                "userMessage": "Payments may not be empty."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "You must select at least one selling mode and provide the required prices.",
                "details": "",
                "path": "sellingMode",
                "userMessage": "You must select at least one selling mode and provide the required prices."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "You don't have the required permissions to publish offer (sell blocked). Verify your account as a company.",
                "details": "",
                "path": "seller",
                "userMessage": "You don't have the required permissions to publish offer (sell blocked). Verify your account as a company."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "The maximum allowed length of the offer title has been exceeded (50 characters, assuming that some letters and symbols are counted as more than 1 character).",
                "details": "",
                "path": "product.embedded.name.name",
                "userMessage": "The maximum allowed length of the offer title has been exceeded (50 characters, assuming that some letters and symbols are counted as more than 1 character)."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "New offer description is required.",
                "details": "",
                "path": "description",
                "userMessage": "New offer description is required."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "Category may not be empty.",
                "details": "",
                "path": "category",
                "userMessage": "Category may not be empty."
            },
            {
                "code": "VALIDATION_ERROR",
                "message": "After sales service conditions (return policies, implied warranties) are required by company account.",
                "details": "",
                "path": "null",
                "userMessage": "After sales service conditions (return policies, implied warranties) are required by company account."
            }
        ],
        "warnings": [],
        "validatedAt": "2021-07-20T13:54:37.009Z"
    },
    "createdAt": "2021-07-20T13:54:37.000Z",
    "updatedAt": "2021-07-20T13:54:37.009Z"
}

Bardzo proszę o pomoc.

Pozdrawiam,
Kasia Kuc

**Comment by PrzemyslawLukanowski** [comment]
Najprawdopodobniej Twoje konto zostało zablokowane ze względu na nieopłacone rachunki- skorzystaj z symulatora płatności w zakładce [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro). Sprzedaż po krótkim czasie zostanie odblokowana. Jeśli to nie rozwiąże problemu i pozostałe komunikaty także nadal będą występować, podaj proszę przykładowe trace-id wywołania. Wstępnie widzę także błąd w strukturze - wszystko prócz pola "name" zawarłaś w "product". [Tutaj ](https://developer.allegro.pl/sale/#12-uzupe%c5%82nij-dane-w-ofercie)znajdziesz prawidłowo uzupełniony przykład.

**Comment by Kasia13130** [comment]
Dobrze, dziękuję.

**Comment by Kasia13130** [comment]
Sprzedaż już mam odblokowaną. Poprawiłam strukturę według przykładu, ale po wysłaniu requestu otrzymuję odpowiedź o problemie z serwerem. Jak można to naprawić ?
metoda: PUT
url: https://api.allegro.pl.allegrosandbox.pl/sale/offers/7680613395
request:
{
    "id": "7680613395",
    "name": "Rzęsy i akcesoria Natural 107 1 para sztucznych rzęs Black",
    "product": null,
    "category": {
        "id": "93074"
    },
    "parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>$Profesjonalne sztuczne rzęsy Natural zostały wykonane z naturalnego, ludzkiego włosia, które zostało poddane sterylizacji. Zostały umieszczone na bezbarwnym, elastycznym pasku, który po nałożeniu na powiekę staje się niewidoczny. Sztuczne rzęsy są długie i gęste - doskonale podkreślą spojrzenie.</p>"
                    }
                ]
            }
        ]
    },
    "images": null,
    "compatibilityList": null,
    "tecdocSpecification": null,
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "15.05",
            "currency": "PLN"
        },
        "netPrice": null,
        "startingPrice": null,
        "minimalPrice": null
    },
    "tax": {
        "id": "f40ae51c-70a2-4882-98a7-6272404f0ec5"
    },
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },
    "publication": {
        "republish": true,
        "duration": null,
        "status": "ACTIVE",
        "startingAt": null,
        "endingAt": null,
        "endedBy": null
    },
    "delivery": {
        "shippingRates": {
            "id": "005febe7-bfa5-4759-9e18-bc562881f05c"
        },
        "handlingTime": "",
        "additionalInfo": "",
        "shipmentDate":""
    },
    "payments": {
        "invoice": "VAT"
    },
    "discounts": {
       "wholesalePriceList": {
           "id": ""
       }
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "74e4f01c-e9a7-4979-89a5-68b5bd313a04"
        },
        "returnPolicy": {
            "id": "6f08c861-63af-489c-951b-29fd0bd9e602"
        },
        "warranty": {
            "id": ""
        }
    },
    "additionalServices": null,
    "sizeTable": null,
    "fundraisingCampaign": null,
    "promotion": {
        "emphasized": true,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "MAZOWIECKIE",
        "city": "Warszawa",
        "postCode": "03-924"
    },
    "external": null,
    "attachments": null,
    "contact": null,
    "validation": {
        "errors": [],
        "validatedAt": ""
    },
    "createdAt": "2020-11-04T13:07:04Z",
    "updatedAt": "2021-05-17T09:36:35Z"
}
response:
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
- w `discounts.wholesalePriceList.id` przekazujesz "" - możesz to zamienić na `discounts: null` lub usunąć to pole;
- w `afterSalesServices.warranty.id` podobnie - możesz tam przekazać `null` lub usunąć pole `afterSalesServices.warranty`
- w opisie oferty `description->content` nie używasz znaków HTML, listę dozwolonych znaków znajdziesz [tutaj](https://developer.allegro.pl/sale/#6-opis-oferty).
`

**Comment by Kasia13130** [comment]
Dobrze, dziękuję.
Z tego co czytałam w dokumentacji by móc opublikować ofertę należy podać commandId w formacie UUID. Próbowałam sobie go wygenerować po przez program znaleziony na github, ale po wklejeniu go do url niestety nie działał. Czy jest jakiś sposób by wygenerować taki commandId ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz go wygenerować np. [na tej stronie](https://www.uuidgenerator.net/).

**Comment by Kasia13130** [comment]
Wygenerowany commandId zadziałał. Publikowanie oferty jeszcze się nie powiodło (muszę dodać jeszcze niektóre parametry), ale sądzę że dalej sobie poradzę. 
Bardzo dziękuję za pomoc.
