### ISSUE TITLE
Jak zdefiniować produkty -- nie przez wystawianie oferty

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4738]
Jesteśmy producentem luster: 

www.lustra.pl

i będizemy na Allegro wystawiać wszystkie nasze produkty (kilkaset pozycji). 

W jaki sposób mogę **zdefiniować te wszystkie produkty w bazie danych Allegro przez API**? Nie znajduję odpowiednich metod. 

Widzę jedynie możliwość wystawiania oferty, a potem powiązania oferty z produktem.

**Comment by PrzemyslawLukanowski** [comment]
W API prezentujemy dwa podejścia w tworzeniu produktów:
- za pomocą [POST /sale/product-offers ](https://developer.allegro.pl/documentation/#operation/createProductOffers)mogą Państwo utworzyć nowy produkt i za pomocą jednego requestu powiązać go z aktywną ofertą. Więcej szczegółów na temat tego procesu znajdą Państwo [tutaj](https://developer.allegro.pl/product_offers/#jak-wystawi%c4%87-ofert%c4%99-z-produktem-kt%c3%b3rego-nie-ma-w-naszej-bazie);
- za pomocą [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) mogą Państwo dodać nowy produkt, a w kolejnym kroku konieczne będzie powiązanie go z tworzoną/aktywną ofertą. Więcej informacji o tym podejściu znajdą Państwo w [naszym poradniku](https://developer.allegro.pl/productization/#5-jak-doda%c4%87-produkt).
