### ISSUE TITLE
PUT sale/offer-publication-commands - problem z przedłużeniem oferty

### ISSUE THREAD

**Issue by mankovsky** [allegro/allegro-api#4743]
Występuje problem:
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 
trace_id: 75fd897d99efe2de

dzień dobry, po próbie przedłużenia trwania oferty poprzez metodę
PUT https://api.allegro.pl/sale/offer-publication-commands
i po sprawdzeniu statusu publikacji (uzyskujemy status SUCCESS dla wysłanej publikacji) oferta nadal jest ważna tylko do jutra, tak jakby jej przedłużenie nie nastąpiło, czy mogę prosić o pomoc albo wskazówkę co może być nie tak?
chodzi dokładnie o ofertę https://allegro.pl/ogloszenie/fiat-tipo-1-4benz-95km-easy-krajowy-10872161781

status publikacji sprawdzamy poniższą metodą
https://api.allegro.pl/sale/offer-publication-commands/e051c807-86df-002b-482c-6347dd522f29/tasks

**Comment by PrzemyslawLukanowski** [comment]
Ta oferta jest cały czas aktywna, jeszcze się nie zakończyła - w polu publication.status wartość dla niej to cały czas "ACTIVE", a nie "ENDED". Endpoint PUT /sale/offer-publication-commands/{uuid} służy do zmiany tych statusów - czyli do aktywowania lub zakończenia oferty. Reasumując - nie możecie aktywować już aktywnej oferty, w takim przypadku w odpowiedzi zawsze otrzymacie SUCCESS. Musicie zatem poczekać aż oferta się zakończy i wtedy aktywujecie ją ponownie za pomocą PUT /sale/offer-publication-commands/{uuid}.

**Comment by mankovsky** [comment]
Bardzo dziękuję za odpowiedź, czy jest możliwość przedłużania wciąż aktywnych ofert? Tzn. chodzi mi o sytuację jak wyżej, np. oferta kończy się jutro, a klient chciałby ją przedłużyć o kolejne 10 dni już dzisiaj, czy jest to możliwe jakąś inną metodą w API? czy jedynym rozwiązaniem jest poczekanie aż oferta się zakończy i potem ponowna jej aktywacja?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku ofert jest to możliwe - nalezy za pomocą [PUT /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) ustawić wartość pola `publication.republish` na `true` (jest to pole odpowiedzialne za automatyczne wznawianie oferty). W przypadku ogłoszeń - niestety nie.

**Comment by mankovsky** [comment]
dziękuję za informację, zamykam zgłoszenie :)
