### ISSUE TITLE
Rozbieżność przy aktywacji między api a panelem

### ISSUE THREAD

**Issue by fabianCyfran** [allegro/allegro-api#4744]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam, mamy problem ze szkicem 10942011116. Próba aktywacji przez api za pomocą zasobu sale/offer-publication-commands kończy się błędem w tasku: **"Could not change offer publication status. Offer category doesn't match product category - 66793."** ale aktywacja z poziomu panelu przechodzi bez problemu. Z czego wynika ta rozbieżność? Istnieje już aukcja (10072035876) z tym samym produktem w innej kategorii więc pytanie czy zwracany błąd jest poprawny?

**Comment by PrzemyslawLukanowski** [comment]
Komunikat jest prawidłowy, ponieważ kategoria, którą zwracamy dla tego produktu przez GET /sale/products/52a9e2c3-1fc1-48d8-ac40-7fc2d2737f57, to właśnie 66793 i w niej zawarta jest większość ofert - https://allegro.pl/produkt/traktor-katarzyna-campbell-52a9e2c3-1fc1-48d8-ac40-7fc2d2737f57. Jeśli uważasz, że kategoria jest niepoprawna, możesz zgłosić [błąd w produkcie](https://allegro.pl/offer/product/report/52a9e2c3-1fc1-48d8-ac40-7fc2d2737f57). W przypadku pytań o panel na stronie internetowej, kontaktuj się proszę przez nasz [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by fabianCyfran** [comment]
A jak to możliwe, że są oferty powiązane z tym produktem ale w innych kategoriach? Skoro wymagacie produktyzacji a jednocześnie nie pozwalacie wystawić oferty zproduktyzowanej w innej kategorii niż "pozostałe" na którą podnieśliście ostatnio prowizję od sprzedaży to jest to niefajne zagranie. Oczekiwalibyśmy, żeby można było automatycznie wystawiać towary w innych kategoirach niż "Pozostałe", a zgłaszanie ofert przez formularz przy tysiącach produktów nie wchodzi w gre.

**Comment by PrzemyslawLukanowski** [comment]
Jak wspomniałem wcześniej - oferta w innej kategorii została wystawiona przez stronę internetową, dlatego kontaktuj się proszę w tej sprawie przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), a odpowiedni dział zweryfikuję tę kwestię. W przypadku API nie stwierdziliśmy tutaj żadnego błędu, zwracamy komunikat zgodny z rzeczywistym stanem rzeczy.
