### ISSUE TITLE
Blokowanie IP ?

### ISSUE THREAD

**Issue by timi-1** [allegro/allegro-api#4745]
Powrót z urlopu i ..  Blokujecie jakoś IP ? Wg nie wchodzi mi domena allegro.

**Comment by PrzemyslawLukanowski** [comment]
Zgłoś się do nas proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a), podaj numer IP i załącz zrzut ekranu, który widzisz po wejściu na stronę.

**Comment by timi-1** [comment]
Jak bym mógł to bym zgłosił przez formularz, cała domena nie działa. Co ciekawe że tylko domena: allegro.pl nie działa ok. Błąd to limit oczekiwania, dostawca multimedia, tracerout kończy się na plix.pl: 
...
 6    25 ms    11 ms    13 ms  host-89-228-6-5.dynamic.mm.pl [89.228.6.5]
  7    12 ms    12 ms    13 ms  host-89-228-6-6.dynamic.mm.pl [89.228.6.6]
  8    15 ms    14 ms    13 ms  host-89-228-6-1.dynamic.mm.pl [89.228.6.1]
  9     *        *        *     Request timed out.
 10    18 ms    12 ms    13 ms  095160069000.business.static.vectranet.pl [95.160.69.0]
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.
 13    19 ms    14 ms    13 ms  atm2.plix.pl [195.182.219.235]
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.

**Comment by PrzemyslawLukanowski** [comment]
Aby móc zweryfikować, czy zostałeś zablokowany, będziemy potrzebować Twojego adresu IP. Spróbuj wejść na stronę z formularzem, korzystając np. z innego urządzenia lub przy użyciu VPN. Jeśli to nie pomoże, możesz to zgłosić także przez messengera naszym [profilu Facebook'owym](https://www.facebook.com/allegro/)
