### ISSUE TITLE
Błąd wydruku etykiety kuriera Allegro

### ISSUE THREAD

**Issue by wasyl1547** [allegro/allegro-api#4747]
Cześć,
mam problem z wygenerowaniem nr przesyłki oraz pobraniem etykiety dla danych. Czy jesteście w stanie mi napisać, czemu nie mogę pobrać nr i etykiety lub czy coś jest nie tak z tymi danymi?

`<pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.request.AllegroNewParcelRequest>
  <serviceId>9188665</serviceId>
  <receiver>
    <address>
      <street>Wojska Polskiego 11</street>
      <postCode>65-077</postCode>
      <city>zielona góra</city>
      <countryCode>PL</countryCode>
    </address>
    <email>gqnadrknnz+3b8c312b8@user.allegrogroup.pl</email>
    <name>Streamsoft</name>
    <phone>728330177</phone>
  </receiver>
  <pickup>
    <address>
      <street>Nowa 9</street>
      <postCode>65-001</postCode>
      <city>Nowy Kisielin</city>
      <countryCode>PL</countryCode>
    </address>
    <email>ccc.allegro.sandbox@gmail.com</email>
    <company>CCC.EU Sp. z o.o.</company>
    <phone>422144222</phone>
  </pickup>
  <items>
    <pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.pojo.AllegroItems>
      <dimensions>
        <height>
          <value>10</value>
          <unit>CENTIMETER</unit>
        </height>
        <width>
          <value>10</value>
          <unit>CENTIMETER</unit>
        </width>
        <depth>
          <value>10</value>
          <unit>CENTIMETER</unit>
        </depth>
      </dimensions>
      <weight>
        <value>1.000</value>
        <unit>KILOGRAM</unit>
      </weight>
      <description>obuwie</description>
      <type>PACKAGE</type>
    </pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.pojo.AllegroItems>
  </items>
  <type>PACKAGE</type>
  <label>
    <sender>
      <address>
        <street>Nowa 9</street>
        <postCode>65-001</postCode>
        <city>Nowy Kisielin</city>
        <countryCode>PL</countryCode>
      </address>
      <email>ccc.allegro.sandbox@gmail.com</email>
      <company>CCC.EU Sp. z o.o.</company>
      <phone>422144222</phone>
    </sender>
    <fileFormat>PDF</fileFormat>
  </label>
  <additionalServices>
    <options/>
  </additionalServices>
</pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.request.AllegroNewParcelRequest>`

Response:
`<pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.response.AllegroNewParcelResponse>
  <id>f5f49103-51d6-4a5e-8d31-a681b48b5d92</id>
  <input>
    <serviceId>9188665</serviceId>
    <receiver>
      <address>
        <street>Wojska Polskiego 11</street>
        <postCode>65-077</postCode>
        <city>zielona góra</city>
        <countryCode>PL</countryCode>
      </address>
      <email>gqnadrknnz+3b8c312b8@user.allegrogroup.pl</email>
      <name>Streamsoft</name>
      <phone>728330177</phone>
    </receiver>
    <pickup>
      <address>
        <street>Nowa 9</street>
        <postCode>65-001</postCode>
        <city>Nowy Kisielin</city>
        <countryCode>PL</countryCode>
      </address>
      <email>ccc.allegro.sandbox@gmail.com</email>
      <company>CCC.EU Sp. z o.o.</company>
      <phone>422144222</phone>
    </pickup>
    <items>
      <pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.pojo.AllegroItems>
        <dimensions>
          <height>
            <value>10</value>
            <unit>CENTIMETER</unit>
          </height>
          <width>
            <value>10</value>
            <unit>CENTIMETER</unit>
          </width>
          <depth>
            <value>10</value>
            <unit>CENTIMETER</unit>
          </depth>
        </dimensions>
        <weight>
          <value>1.000</value>
          <unit>KILOGRAM</unit>
        </weight>
        <description>obuwie</description>
        <type>PACKAGE</type>
      </pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.pojo.AllegroItems>
    </items>
    <label>
      <sender>
        <address>
          <street>Nowa 9</street>
          <postCode>65-001</postCode>
          <city>Nowy Kisielin</city>
          <countryCode>PL</countryCode>
        </address>
        <email>ccc.allegro.sandbox@gmail.com</email>
        <company>CCC.EU Sp. z o.o.</company>
        <phone>422144222</phone>
      </sender>
      <fileFormat>PDF</fileFormat>
    </label>
    <additionalServices>
      <options/>
    </additionalServices>
  </input>
</pl.com.stream.integration.cr.courier.server.impl.configuration.data.allegro.response.AllegroNewParcelResponse>`

**Comment by MartaNowaczyk** [comment]
Cześć, wstępnie wygląda na to, że serviceId nie zgadza się z wybraną metodą dostawy w zamówieniu. Przekazałam jeszcze do sprawdzenia. Jeśli będę wiedziała coś więcej dam znać.
Polecam sprawdzać status utworzenia paczki przez GET /parcel-management/parcel-create-commands/{commandId}.

**Comment by wasyl1547** [comment]
Wywołałem metodę wskazaną metodę:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/f5f49103-51d6-4a5e-8d31-a681b48b5d92
W odpowiedzi otrzymałem:	
```
errors	
0	
code	"NotAcceptableException"
message	"Not acceptable representation requested. Please check 'Accept' request header"
details	null
path	null
userMessage	"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
```

Dodatkowo od strony Allegro wybieram sposób dostawy Allegro DPD z ID: 9188665.

**Comment by MaciejFrackowiak** [comment]
Zgodnie z otrzymaną odpowiedzią nie przekazujesz żadnej wartości dla nagłówka Accept oraz Content-Type (powinno to być application/vnd.allegro.public.v1+json), a ponadto wywołałeś metodę HEAD zamiast PUT.

**Comment by wasyl1547** [comment]
Ok, dodałem brakujące dane:
W odpowiedzi otrzymuje (dla każdej paczki):
{
    "id": "d2b51770-395c-40c3-85d5-5424a552baf5",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "VALIDATION_ERROR",
            "message": "Order cannot be send using selected delivery service",
            "details": null,
            "path": null,
            "userMessage": "Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"
        }
    ]
}

**Comment by MaciejFrackowiak** [comment]
Otrzymany komunikat mówi, że przesyłka nie została nadana metodą dostawy zgodną z wyborem kupującego. Wszelkie dostępne metody dostawy na danym koncie sprzedającego znajdziesz przy użyciu [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices).

**Comment by wasyl1547** [comment]
Ok, sprawdziłem i rzeczywiście używaliśmy nie ten service ID.
Pytanie dodatkowe jeżeli mogę, to czy każdy z klientów posiada różne service ID czy są to stałe wartości?

**Comment by MaciejFrackowiak** [comment]
Tak, id usług mogą być różne, dlatego zawsze warto sprawdzić jakie są ich wartości na danym koncie.

**Comment by wasyl1547** [comment]
Ok, dziękuję za informację.
Zgłoszenie zostało wyjaśnione.
