### ISSUE TITLE
problem z rejestracją zleceń 

### ISSUE THREAD

**Issue by MagdaMusial** [allegro/allegro-api#4748]
Witam,
Jestem projektantem aplikacji w firmie Comarch. Aktualnie pracujemy nad integracją naszej nowej aplikacjiComarch Shipping z Kurierem Allegro inPost Kurier. W dokumentacji kuriera InPostu jest zapis ze przy rejestracji zlecenie nie używaja już ID transakcji i ID usera tylko wystarczy maskowany adres e-mail. Próbowaliśmy na sandboxie testowym wystawić taką licytacje i ją zakupić i u nas odpowiednio w aplikacji wpisać mail wg schematu: stałykodnadawcy+identyfikatortransakcji@allegromail.com, na przykład 8awgqyk6a5+cub31c122@allegromail.com. ale niestety dostajemy komunikat: {[receiver, [ { "email": "allegro_order_not_found" }]]}. Próbowalismy również na serwerze produkcyjnym zakupić jakieś towary i niestety dostajemy ten sam komunikat. czy my robimy coś zle? zle budujemy te adresy mailowe? czy aby zarejestrować takie zlecenie zarówno adres nadawcy jak i odbiorcy musi być w domenie allegro? czy maja Państwo przykładową listę mailowa na której możemy testować zamawiania produktów?

**Comment by MartaNowaczyk** [comment]
Witaj,
prawidłowy email znajdziesz pobierając zamówienie przez GET /order/checkout-forms/{id} w polu buyer.email. 
Nie mamy przykładowej listy mailowej. Pozsotałe kwestie skonsultuj proszę z InPostem.

**Comment by MagdaMusial** [comment]
o jakie ID dokładnie chodzi? to ma być wykonane po prostu do API Allegro?

**Comment by PrzemyslawLukanowski** [comment]
Tak, chodzi o ID konkretnego zamówienia, które możesz pobrać za pomocą [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) w polu `checkoutForms.id`.

**Comment by MagdaMusial** [comment]
https://api.allegro.pl/order/checkout-forms - próbuję robić get na ten endpoint ale nie dostaję odpowiedzi tylko error 406

**Comment by MartaNowaczyk** [comment]
Błąd 406 oznacza, że w nagłówku Accept przekazany został nieobsługiwany przez zasób typ danych.
Umieść w nim: application/vnd.allegro.public.v1+json
