### ISSUE TITLE
Oferty promowane

### ISSUE THREAD

**Issue by mb88x** [allegro/allegro-api#4749]
Występuje problem: 
 - [x ] z zasobem REST API

Witam,

Rest api zwraca 60 aukcji promowanych, podczas gdy na allegro jest ich 80, jaki jest tego powód?
Wczesniej działało dobrze.

trace-id=a4c5efc219b5cc84

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z [naszym newsem](https://developer.allegro.pl/news/#offers-listing) - od 06.05.2020 dla GET /offers/listing zwracamy maksymalnie 60 ofert. Kolejne oferty możesz pobrać za pomocą parametru `offset`.
