### ISSUE TITLE
Tagi w ofercie [rest api]

### ISSUE THREAD

**Issue by bugas23** [allegro/allegro-api#475]
Witam,
czy jest/będzie możliwa obsługa tagów z aukcji? Tzn. na chwilą obecną "kopiując" aukcje tagi są pomijane.

Pozdrawiam.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Tagi w REST API udostępnimy w najbliższych tygodniach. Do końca sierpnia powinny być gotowe.
