### ISSUE TITLE
Missing / deleted offerts - why it's happened

### ISSUE THREAD

**Issue by invital** [allegro/allegro-api#4750]
Hi,
we have about 700 offerts on Allegro. We find out yesterday that 200 offers are missing (we do not delete them manually), so we were contact Allegro helpdesk and they tell us offers were deleted. We ask them for more informations, but they refuse answer us how or who delete offerts (it's important for find out how it happend). Because we do not delete them manually then they must be deletet by Allegro automatically (for long status of inactive) or it must do our connector to our warehouse system which is commincating with Allegro via Allegro API.

Because of that a I would like to ask you, if our way communication between our CRM and Allegro API is correct.
We are creating offerts on Allegro manually, our connector only editing prices and availability of offerts. So we are using only theses 3 API commands, which I am describing bellow 👇👇

---------------------------------

### 1️⃣ End / start of offert
If product of offer is not available then we deactivate offert on Allegro = it no have any reason offer offert which is not available +  it's not even allowed by Allegro. So we are hidding unavaible offerts. If offer (= product of offer) is available again, then we will reactive it.
**Documentation:** https://developer.allegro.pl/en/sale/#13-offer-publication

**Example of API calling:**
- **API URL:** https://api.allegro.pl/sale/offer-publication-commands/%UID%
- **API calling - Start of offert:** {"publication": {"action": "ACTIVATE"}, "offerCriteria": [{"offers": [%ID_offert%],"type": "CONTAINS_OFFERS"}]}
- **API calling - End of offert:** {"publication": {"action": "END"}, "offerCriteria": [{"offers": [%ID_offert%],"type": "CONTAINS_OFFERS"}]}

---------------------------------

### 2️⃣ Updating amount of available pcs of offert
If offert is available, then we must ensure offering correct amount of pcs. For this we are using this API calling:
**Documentation:** https://developer.allegro.pl/en/my_offers/#editing-many-offers

**Example of API calling:**
- API URL: https://api.allegro.pl/sale/offer-quantity-change-commands/
- API calling: {"modification":{"changeType":"FIXED","value":%QUANTITY%},"offerCriteria":[{"type":"CONTAINS_OFFERS", "offers":[%ID_offert%]}]}

---------------------------------

### 3️⃣ Updating price of offert
This action is ensuring correct price of offer according price list in our CRM system.
**Documentation:** https://developer.allegro.pl/en/my_offers/#price

**Example of API calling:**
- API URL: https://api.allegro.pl/sale/offer-price-change-commands/
- API calling: {"modification":{"type":"FIXED_PRICE","price": {"amount":"%PRICE (2 decimal format)%", "currency":"PLN"} }, "offerCriteria":[{"type":"CONTAINS_OFFERS", "offers":[ {"id":"%ID_offerty%"} ]}]}

### Is it correct way of editing offerts❓ Thank you. 👍👎❓

**Comment by PrzemyslawLukanowski** [comment]
Yes, you are using the correct endpoints, alternatively to update stock or price you can use [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) or [PUT /sale/offers/{offerID](https://developer.allegro.pl/en/documentation/#operation/updateOfferUsingPUT)}. And when it comes to the missing offers issue - we will need your seller login (or ID) and sample IDs of the deleted offers to verify this case. You can use our [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) to send this data, please also add information that the data concern thread #4750 on GitHub. Please remember that offers are automatically moved to our archive after 60 days if they are in ENDED status and are not listed again - that may be one of the reasons why offers are missing.

**Comment by invital** [comment]
Thanks for fast reply. Our seller login is **invital-pl** and bellow you can find some of missing offerts:

- 10011789167
- 10024735721
- 10042063732
- 10113729907
- 10135765363
- 10631684883
- 9954209565
- 9957327315
- 9378624672
- 10042512421

**Comment by PrzemyslawLukanowski** [comment]
Thanks for the examples. As I mentioned in my previous post - all of those offers were ended more than 60 days ago and were not listed again. That is the reason why they are missing - they were moved to our archive and are not available anymore.

**Comment by invital** [comment]
Is there any way to hot to set up to not move offers into archive automatically? Is it not unusual that some goods are not available more than 60 days, especially in COVID time and create new offer take some time.

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately not - within 60 days of expiring an offer, information is archived and it cannot be restored.
