### ISSUE TITLE
Systematycznie usuwanie ofert z przyczyną: [{"code": "ConstraintViolationException.ValidTecdocSpecification", "path": "tecdocSpecification", "details": null, "message": "Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data.", "userMessage": "Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data."}]

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4752]
Jak w temacie kod odpowiedzi API:

[{"code": "ConstraintViolationException.ValidTecdocSpecification", "path": "tecdocSpecification", "details": null, "message": "Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data.", "userMessage": "Given TecDoc specification is not most recent for selected product. Update offer with the most recent product data."}]

Nasza maszyna nie nadąża kasować ofert i wystawiać ich na nowo średnio kasujecie nam od 30 - 260 tys ofert tygodniowo...

dajcie proszę info jak to aktualizować poprzez API (my łączymy się z produktami a po aktualizacji bazy TecDoc oferty zostają usunięte.... nie jesteśmy w stanie wystawiać w takich ilościach ofert na nowo co kilka tygodni)  

Pytanie 1. Inaczej (zakładam że to poprawne rozwiązanie) jak wykorzystać https://developer.allegro.pl/product_offers/#jak-edytowa%C4%87-ofert%C4%99 by nie zmieniać nic w ofercie a jednocześnie ją aktualizować do najnowszej wersji TecDoc ? 

Pytanie 2. Jak pobrać oferty które będą za chwilę usunięte z powodu niekompatybilnej wersji TecDoc ?

**Comment by PrzemyslawLukanowski** [comment]
1. W takim przypadku możesz przesłac pusty `{}` przez PATCH /sale/product-offers/{offerID}, a w wyniku takiej operacji automatycznie zaktualizujemy w ofercie pola `tecdocSpecification `i `compatibilityList`, zgodnie z danymi występującymi w powiązanym produkcie.
2. W tej chwili nie ma takiej możliwości. My jako Allegro nie usuwamy ofert z powodu niekompatybilnej wersji TecDoc.

**Comment by pliszka** [comment]
ok thx za informacje zamykam :)
