### ISSUE TITLE
Czy można ustawić więcej niż jedną usługę dodatkową dla oferty?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4754]
Wygląda na to, że można tylko jedną:

"additionalServices": {
    "id": "string"
}

Ale chciałbym się upewnić czy czegoś nie przegapiłem.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Do oferty można przypisać tylko jedną grupę usług dodatkowych, natomiast pojedyncza grupa może składać się z wielu takich usług. Działa to podobnie jak np. cenniki dostawy - możesz do oferty przypisać jeden cennik, ale sam cennik składać się może z wielu pozycji. 

Więcej informacji o usługach dodatkowych [znajdziesz w newsie](https://developer.allegro.pl/news/2017-10-25-news_uslugi_dodatkowe/#1).

**Comment by tomylee0** [comment]
Dzięki wielkie.
