### ISSUE TITLE
refund api problem

### ISSUE THREAD

**Issue by whyun1** [allegro/allegro-api#4755]
Hello, I want to use payments/refunds api, but I got an error as below:
{
    "errors":[
        {
            "code":"VALIDATION_ERROR",
            "message":"Invalid parameter format",
            "details":"Invalid value: null",
            "path":"lineItems.value",
            "userMessage":"Invalid parameter format"
        }
    ]
}

The following is my request:
{
    'payment': {
        'id': 'e2cc0241-eb94-11eb-9cfe-aaaaaaa'
    }, 
    'reason': 'PAID_VALUE_TOO_LOW', 
    'delivery': {
        'value': {
            'amount': '20', 
            'currency': 'PLN'
        }
    }, 
    'lineItems': [
        {
            'id': 'e2761a10-eb94-11eb-a92a-aaaaaaa', 
            'type': 'AMOUNT', 
            'value': {
                'amount': '31.29', 
                'currenty': 'PLN'
            }
        }
    ]
}

Thanks in advance.

**Comment by AureliuszBrussy** [comment]
I see a typo in your request body - in lineItems[].value change **currenty** to **currency**.

**Comment by whyun1** [comment]
> I see a typo in your request body - in lineItems[].value change **currenty** to **currency**.

Didn't notice that.
Thanks very much.
:)
