### ISSUE TITLE
Nagle wygasające tokeny

### ISSUE THREAD

**Issue by Bodzix** [allegro/allegro-api#4756]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Klient zgłasza nam, że zrywane jest połączenie pomiędzy allegro a zewnętrznymi aplikacjami. 
Każda aplikacja ma swoje powiązanie. Nie jest tak, że więcej niż jedna aplikacja korzysta z jednego tokenu, więc konflikt wykluczam. Średnio raz dziennie trzeba wykonać ponowne powiązanie aplikacji. Powiąże jedno, reszta połączeń wygasa.

Poniżej podaje ID aplikacji.
9d1a2b0e-617e-4bc5-857f-1a314191850
316b3df496774a9f92361c5e4e4189dc
fbcaec56322848088492d2396c14dbbc

Proszę o pomoc.

**Comment by AureliuszBrussy** [comment]
Potrzebuję więcej danych aby to sprawdzić. Wyślij w [formularzu kontaktowym](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) access tokeny, które wygasły i bardziej szczegółowe informacje, jak to wg. Ciebie przebiegło. W zgłoszeniu dopisz proszę numer wątku na GitHubie: #4756.

**Comment by kfijalko** [comment]
@Bodzix nowy wydany token unieważnia poprzedni i jak nie zapiszesz nowego refresh-tokena to potrzebne jest ponowne powiązanie konto-aplikacja. Jeżeli to nie jest błąd allegro [pewnie była by lawina zgłoszeń], to sprawdź czy nie masz luki polegającej na pobraniu nowego tokena bez zapisania go. Allegro pewnie to zaraz sprawdzi.

**Comment by mrezlik** [comment]
U nas występuje podobny problem dla kilku kont allegro. Wszystko działa dobrze (odświeżają się tokeny itd.), ale w pewnym momencie tokeny wygasają, nie działają przez chwilę i później znowu wszystko potrafi wrócić do normy (przeważnie zaczyna się to około godziny 22), bez ingerencji żadnego użytkownika. A czasami trzeba ręcznie odświeżyć i na nowo powiązać konto allegro z aplikacją mimo, że nic nie było zmieniane.

**Comment by AureliuszBrussy** [comment]
@mrezlik jeżeli chcesz, żebyśmy to wyjaśnili - również wyślij szczegóły przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz proszę także numer wątku na GitHubie: #4756 oraz wskaż login: mrezlik.
