### ISSUE TITLE
Prawdopodobnie czasem na GET sale/offers otrzymujemy niepoprawne parametry w odpowiedzi

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4757]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Przy próbie zmiany tylko ilości sztuk otrzymałem błąd:

{
   "errors":[
      {
         "code":"VALIDATION_ERROR",
         "message":"Assigned valueId  for dictionary parameter 223541 is not found.",
         "details":"ConstraintViolationException.InvalidDictionaryParameterValueId",
         "path":"parameters[6].valuesIds[0]",
         "userMessage":"Assigned valueId  for dictionary parameter 223541 is not found."
      },
      {
         "code":"VALIDATION_ERROR",
         "message":"No value was given for parameter Publishing House (223541).",
         "details":"ConstraintViolationException.NoValueInDictionaryParameter",
         "path":"parameters",
         "userMessage":"No value was given for parameter Publishing House (223541)."
      }
   ]
}

Pobierając GET'em ofertę **modyfikuję jedynie ilość sztuk** i robię potem PUT. Jeśli faktycznie wysłałem w PUT niepoprawnie parametry to otrzymałem je robiąc GET'a. Mam podejrzenie, że GET zwrócił niepoprawne parametry. Chciałbym poprosić o sprawdzenie sytuacji. Mam dziś takich przypadków więcej. Zauważyłem ponadto, że pojawiają się co jakiś czas. Np. tu #4659.

trace-id:
GET: 3043a16443531730
PUT: 281ee8d621150c9d

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Jest to ten sam problem, o którym mowa w wątku #4615. Udało nam się zlokalizować przyczynę, dlaczego problem powraca raz na jakiś czas - jeszcze prawdopodobnie dziś wprowadzimy odpowiednią poprawkę, poinformuję w wątku.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy poprawkę, problem nie powinien już występować.
