### ISSUE TITLE
sale/offer-events - brak external id przy OFFER_BID_PLACED

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4759]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

86bf516bf4ebfa71 - trace id w którym występują takie przypadki.

Witam,

Mam problem z zasobem `sale/offer-events `. Zdarza się sytuacja, że external przychodzi jako null mimo, że jest uzupełniony. Najczęściej zdarza się to przy evencie OFFER_BID_PLACED.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Analizujemy ten problem. Wrócę do Ciebie z odpowiedzią gdy coś ustalimy.

**Comment by AureliuszBrussy** [comment]
Aktualnie dla eventów: OFFER_BID_PLACED i OFFER_BID_CANCELED nie zwrócimy external.id. W przypadku innych typów eventów - zwrócimy external.id. Poprawiliśmy już dokumentację.
