### ISSUE TITLE
Refresh Token - doprecyzowanie

### ISSUE THREAD

**Issue by lgtk** [allegro/allegro-api#476]
Witam, chciałbym się dowiedzieć jak długo jest ważny refresh_token, tzn czy po minięciu np 13h mogę go wykorzystać aby odświeżyć access token, czy musi zostać wykorzystany przed wygaśnięciem access token. Moja aplikacja działa w interwałach ustalanych przez klientów np co 1h czy mogę odświeżać access token co interwał? Nie będzie miało to jakiś efektów ubocznych?

**Comment by MaciejPotepa** [comment]
Dzień dobry

Refresh token musi być wykorzystany zanim wygaśnie access token. 

Po odświeżeniu access tokenu refresh tokenem, access token będzie ważny przez 365 dni, weź to pod uwagę przy projektowaniu aplikacji. 

Więcej informacji [tutaj](https://developer.allegro.pl/auth/).

**Comment by lgtk** [comment]
Jeśli dobrze rozumiem kolejny access token jest ważny rok?

**Comment by Onixarts** [comment]
> Refresh token musi być wykorzystany zanim wygaśnie access token.
> Po odświeżeniu access tokenu refresh tokenem, access token będzie ważny przez 365 dni

Na pewno tak? Czy access token nie jest przypadkiem ważny 12h a refresh token służy do odświeżenia go i działa po jego wygaśnięciu. Autoryzacja zaś jest ważna 365 dni.

**Comment by MaciejPotepa** [comment]
@lgtk @Onixarts najmocniej przepraszam, pomieszałem tokeny. 

**Refresh token** musi być wykorzystany zanim sam wygaśnie i to **refresh token** ważny jest rok, a **access token** 12 godzin.
