### ISSUE TITLE
Znikające parametry obowiązkowe w ofercie?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4760]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Wystawiłem ofertę w dniu 11 lipca 2021. Parametr "Okładka" był wtedy obowiązkowy. Ustawiłem go. Udało się wysłać draft bez błędów. Udało się publikować.
Trace-id draftu oferty: 9e14b1fc40d31495
Trace-id publikacji oferty: 85195bac5aef510b

Niedawno próbuję zmienić ilość sztuk.
Trace-id GET: 8d45057deb0ca07
Trace-id PUT: 79f9a044930280a9
Dostaję błąd: Missing required parameters: Cover.

To nie chwilowe. Przy kolejnych próbach zmiany ilości sztuk mam to samo. Zaglądam do oferty przez www. Faktycznie nie ma ustawionej okładki. Wygląda na to, że parametr zniknął.

Proszę uprzejmie o sprawdzenie tej sytuacji.

**Comment by AureliuszBrussy** [comment]
16 lipca przenieśliśmy ofertę do innej kategorii (79477). W kategorii w której była oferta (79419) parametr o nazwie "Okładka" posiada inne id, niż w kategorii do której oferta została przeniesiona (7773). Parametr o nazwie "Okładka" w tej kategorii to id: 75. W trakcie przenoszenia oferty usunęliśmy parametr nieistniejący w kategorii. 

W takim przypadku uzupełnij brakujący w nowej kategorii parametr.

**Comment by tomylee0** [comment]
Kategoria i parametry tej oferty w momencie wystawienia zostały pobrane z bazy produktowej. Sprawdziłem przed chwilą i w bazie produktowej produkt wciąż jest w starej kategorii czyli 79419. A tam jak wspomniałeś identyfikator okładki jest inny. Wydaje się więc, że nie jest możliwe przypisanie tego parametru dbając równocześnie aby oferta była podłączona do bazy produktowej. Czy mam rację?

W tej sytuacji nie mogę zmienić ilości sztuk oferty. Muszę ofertę usunąć i wystawić od nowa. Wystawiając pobieram kategorię i parametry z bazy produktowej. Oferta wystawi się w 79419 zgodnie z bazą produktową. Wkrótce oferta zostanie przeniesiona do innej kategorii. Wtedy zniknie okładka...

Jeśli dobrze to zrozumiałem to brak synchronizacji pomiędzy dostępną dla nas bazą produktową a bazą lub algorytmem na podstawie którego Allegro podejmuje decyzje o przeniesieniu oferty do innej kategorii uniemożliwia nam utrzymanie oferty.

**Comment by Lukasz-Zurek** [comment]
> 
> 
> Kategoria i parametry tej oferty w momencie wystawienia zostały pobrane z bazy produktowej. Sprawdziłem przed chwilą i w bazie produktowej produkt wciąż jest w starej kategorii czyli 79419. A tam jak wspomniałeś identyfikator okładki jest inny. Wydaje się więc, że nie jest możliwe przypisanie tego parametru dbając równocześnie aby oferta była podłączona do bazy produktowej. Czy mam rację?

Nie, w tym przypadku oferta nadal będzie połączona z produktem.
> 
> W tej sytuacji nie mogę zmienić ilości sztuk oferty. Muszę ofertę usunąć i wystawić od nowa. Wystawiając pobieram kategorię i parametry z bazy produktowej. Oferta wystawi się w 79419 zgodnie z bazą produktową. Wkrótce oferta zostanie przeniesiona do innej kategorii. Wtedy zniknie okładka...

Nie musisz usuwać oferty. Wystarczy, że uzupełnisz brakujący parametr.
> 
> Jeśli dobrze to zrozumiałem to brak synchronizacji pomiędzy dostępną dla nas bazą produktową a bazą lub algorytmem na podstawie którego Allegro podejmuje decyzje o przeniesieniu oferty do innej kategorii uniemożliwia nam utrzymanie oferty.

Nie, Poprawność parametrów sprawdzamy tylko na etapie wystawiania oferty. Nie robimy tego jednak podczas edycji, aby nie blokować edycji istniejących ofert, które są powiązane z produktem, ale nie mają poprawnych parametrów produktowych.

Dodam również, że zgłosiłem już zmianę kategorii produktu (z 79419 na 79477) do odpowiedniego działu, w celu naniesienia poprawki.

**Comment by kfijalko** [comment]
@Lukasz-Zurek zgłoś również do odpowiedniego zespołu, żeby dbał o spójność danych (oferty, produkty) w procesie przenoszenia ofert pomiędzy kategoriami.

**Comment by Lukasz-Zurek** [comment]
@kfijalko Poruszę również i ten temat. Dziękuję.

**Comment by tomylee0** [comment]
OK. Jeśli jednak **jedynym źródłem parametrów podczas wystawiania oferty jest dla mnie baza produktowa** to w tej konkretnej sytuacji w ofercie brakuje mi parametru 75 a w bazie produktowej nie ma tego parametru więc nie mam czym go wypełnić. Wtedy nie mogę edytować ani ilości ani ceny oferty. Dbając o aktualność mojej oferty muszę ją usunąć. Owszem, mógłbym sprawdzać parametry po nazwie ale nikt nie zagwarantuje mi, że parametr w przeniesionej kategorii ma taką samą nazwę.

A potem nasze systemy informatyczne wystawią tą ofertę od nowa. Bo dlaczego nie. Przecież produkt w bazie produktowej jest. Nie mamy informacji, że produkt wprawdzie istnieje ale nie jest aktualny. Czyli scenariusz że **dopóki nie zostanie uaktualniony produkt w bazie produktowej to w nowo wystawionej ofercie parametr po pewnym czasie znowu zniknie** wydaje się być prawidłowy.

**Comment by Lukasz-Zurek** [comment]
> 
> 
> OK. Jeśli jednak **jedynym źródłem parametrów podczas wystawiania oferty jest dla mnie baza produktowa** to w tej konkretnej sytuacji w ofercie brakuje mi parametru 75 a w bazie produktowej nie ma tego parametru więc nie mam czym go wypełnić. Wtedy nie mogę edytować ani ilości ani ceny oferty. Dbając o aktualność mojej oferty muszę ją usunąć. Owszem, mógłbym sprawdzać parametry po nazwie ale nikt nie zagwarantuje mi, że parametr w przeniesionej kategorii ma taką samą nazwę.

Jak już wspomniałem wcześniej - nie chcemy blokować edycji istniejących ofert (z przypisanym produktem, ale z nieprawidłowym parametrem), dlatego nie sprawdzamy poprawności parametrów. W tym konkretnym przykładzie edycja oferty jest możliwa. Nowy parametr możesz sprawdzić za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).
> 
> A potem nasze systemy informatyczne wystawią tą ofertę od nowa. Bo dlaczego nie. Przecież produkt w bazie produktowej jest. Nie mamy informacji, że produkt wprawdzie istnieje ale nie jest aktualny. Czyli scenariusz że **dopóki nie zostanie uaktualniony produkt w bazie produktowej to w nowo wystawionej ofercie parametr po pewnym czasie znowu zniknie** wydaje się być prawidłowy.

Jest to jedna z opcji. Cały czas monitorujemy sytuację, zależy nam na tym, aby takich przypadków było jak najmniej i jednocześnie zależy nam również na tym, aby cały proces uspójnić, coś na co zwrócił uwagę @kfijalko
