### ISSUE TITLE
Pobranie szczegółów klienta dla /payments/payment-operations

### ISSUE THREAD

**Issue by brokieb** [allegro/allegro-api#4765]
Witam, w jaki sposób mogę pobrać ID zamówienia lub najlepiej adres Email klienta powiązanego z daną płatnością?

**Comment by hahyes** [comment]
Jeżeli masz ID płatności, możesz wyszukać konkretne zamówienie podając w zapytaniu do zasobu: https://developer.allegro.pl/redoc/redoc-static.html#operation/getListOfOrdersUsingGET parametr `payment.id` z identyfikatorem płatności.

**Comment by Lukasz-Zurek** [comment]
@brokieb Potwierdzam, to co napisał pomocny @hahyes
