### ISSUE TITLE
Jak sprawdzić cenę za wyróżnienie elastyczne?

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#4766]
Korzystam z endpointu **/pricing/offer-fee-preview** do wyliczenia kosztów promowania oferty.
W jaki sposób przekazać tam opcję "wyróżnienia elastycznego" skoro brakuje takiego parametru lub jak inaczej efektywnie to można zrealizować?
```
"promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
},
```

**Comment by Lukasz-Zurek** [comment]
Niestety nie ma takiej możliwości, jak również nie ma alternatywnego sposobu przekazania wspomnianej opcji.
