### ISSUE TITLE
Kategoria, która EAN ma opcjonalnie wymusza ustawienie EAN

### ISSUE THREAD

**Issue by bigretromike** [allegro/allegro-api#4767]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Nr kategorii 100128
Nie zmieniałem niczego po swojej stronie, nagla dostaje odpowiedź z informację zwrotną z API, "W tej kategorii wymagane jest podanie parametru EAN(product.parameters)" mimo, że przez WWW nie ma takiego wymagania i dotychczas wszystko przechodziło poprawnie. Pomoc Allegro skierowała mnie tutaj. Czy to możliwe że dostałem jakieś ograniczenie ? Czy coś z API ?

**Comment by PrzemyslawLukanowski** [comment]
W tej kategorii EAN nie jest potrzebny do utworzenia oferty, tylko produktu:

```
  {
            "id": "225693",
            "name": "EAN",
            ...
            "required": false,
            "requiredForProduct": true,
             ...
   }
```

Komunikat, który otrzymałeś świadczy o tym, że prawdopodobnie korzystasz z endpointu POST /sale/product-offers i próbujesz utworzyć nowy produkt, dlatego powinieneś przekazać EAN w sekcji **product.parameters**.

**Comment by bigretromike** [comment]
> Komunikat, który otrzymałeś świadczy o tym, że prawdopodobnie korzystasz z endpointu POST /sale/product-offers i próbujesz utworzyć nowy produkt, dlatego powinieneś przekazać EAN w sekcji **product.parameters**.

Tak potwierdzam, program wysyła ofertę właśnie na na ``` POST /sale/product-offers ```

Czy coś się zmieniło, że teraz prosi o EAN ?
