### ISSUE TITLE
Rozpoznawanie wykorzystania kuponów w zamówieniach - czy jest potrzebne

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4768]
W związku z chęcią wypróbowania kampanii kuponowych mam wątpliwości:

Czy w cenie zapłaconej przez klienta jest już uwzględniony kupon? Jeżeli nie, jak będzie wyglądać zamówienie w wypadku użycia kuponu? Chodzi mi głównie o wystawianie faktur. Czy każda pozycja w zamówieniu będzie indywidualnie zmodyfikowana do kuponu? 

Liczę na odpowiedź
Pozdrawiam. :)

**Comment by PrzemyslawLukanowski** [comment]
W polu `payment.paidAmount` znajdziesz kwotą od kupującego już z uwzględnieniem kuponu. Informacja o tym, że skorzystał z kuponu widoczna będzie w sekcji `discounts` (`"type": "COUPON" `). W polu `lineItems[].originalPrice.amount` znajdziesz oryginalną kwotę przedmiotu, a w `lineItems[].price.amount`  kwotę po użyciu kuponu.

**Comment by cieplik206** [comment]
> W polu `payment.paidAmount` znajdziesz kwotą od kupującego już z uwzględnieniem kuponu. Informacja o tym, że skorzystał z kuponu widoczna będzie w sekcji `discounts` (`"type": "COUPON" `). W polu `lineItems[].originalPrice.amount` znajdziesz oryginalną kwotę przedmiotu, a w `lineItems[].price.amount` kwotę po użyciu kuponu.

Nie jest to prawdą, w przypadku typu ALLEGRO_PRiCES czy CROSS_MUlTIPACK owszem, ale w przypadku kuponów sekcja discount jest pusta. BUG ?

**Comment by PrzemyslawLukanowski** [comment]
@cieplik206 Zwróć uwagę, czy w Twoim przypadku nie miał miejsce scenariusz opisany w wątku #6719, tj.:

> Jeśli price i originalPrice jest takie samo, oznacza to, że to nie był kupon, który obniża cenę samej oferty, np. kupon wymieniany za monety. Kwota z kuponu jest wtedy dodawana do kwoty wpłaty kupującego (właśnie od strony kupującego strony pochodzi Twój zrzut ekranu), dla sprzedającego jest to wtedy transparentne, dostajesz wtedy taką kwotę, jakiej oczekujesz i nie musisz wnikać w to, czy cała wpłata pochodzi od klienta, czy została opłacona kuponem.
