### ISSUE TITLE
Search offer info by ID

### ISSUE THREAD

**Issue by morozov312** [allegro/allegro-api#4770]
Is it possible to find basic information about offer using offer ID? I tried use GET/offers/listing but it doesn't work.
Request example - https://api.allegro.pl.allegrosandbox.pl/offers/listing?phrase=44320357

**Comment by kfijalko** [comment]
Access to /offers/listing is restricted.
Read this news: #4566

**Comment by PrzemyslawLukanowski** [comment]
In addition to info from kfijalko - if you want to undergo the verification process, [contact us via the form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by morozov312** [comment]
> Помимо информации от kfijalko - если вы хотите пройти процесс верификации, [свяжитесь с нами через форму](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) .

Thanks we have already contacted, at the moment the application owner is collecting the necessary documents. I'm still working with a sandbox environment, and I'm interested in searching offer info by ID

**Comment by PrzemyslawLukanowski** [comment]
You can use only the following parameters: phrase, category.id, seller.id or seller.login. It is not possible to find a specific offer using offer ID as the phrase parameter value.
