### ISSUE TITLE
sale/product-proposals zwraca błąd ProductDuplicate, wskazując na produkt różny od zdefiniowanego

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#4771]
Próbuję połączyć ofertę z produktem, kojarząc ją za pomocą numeru EAN. Gdy próbuję pobrać istniejący produkt z użyciem EANu, dostaję pusty wynik. Aktualnie są jednak aktywne oferty z tym EANem, które są połączone z produktem.
Mimo wszystko, z powodu rzekomego braku istniejącego produktu, próbuję takowy utworzyć, jednak w odpowiedzi otrzymuję błąd, że produkt z takimi parametrami jednak istnieje. 

Zapytanie (wyszukiwanie produktu po nr ean):
2021-07-30 02:38:48, GET, https://api.allegro.pl/sale/products?ean=8591149069178, headers:["Authorization: Bearer <token>","Accept: application/vnd.allegro.public.v1+json","User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0","Connection: keep-alive","Accept-Language: pl","Accept-Encoding: deflate"]

Odpowiedź:
{"products":[],"categories":{"subcategories":[{"id":"5","name":"Dom i OgrĂłd","count":0},{"id":"11763","name":"Dziecko","count":0},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","count":0},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma i usĹ‚ugi","count":0},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","count":0},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","count":0},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","count":0},{"id":"3","name":"Motoryzacja","count":0},{"id":"20782","name":"NieruchomoĹ›ci","count":0},{"id":"3919","name":"Sport i turystyka","count":0},{"id":"258832","name":"Supermarket","count":0},{"id":"1429","name":"Uroda","count":0},{"id":"121882","name":"Zdrowie","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[],"nextPage":null}

Wyniki wyszukiwania na stronie:
![image](https://user-images.githubusercontent.com/5887720/127587021-62670f28-b054-4e8d-842d-7e42441bd7d6.png)

Zapytanie (tworzenie nowego produktu):
2021-07-30 02:39:48, POST, https://api.allegro.pl/sale/product-proposals,

Body:"`{"name":"Oczka metalowe wew.fi10 mm / zew.fi16 mm 100par","category":{"id":"1497"},"images":[{"url":"https://a.allegroimg.com/original/1161d5/2f7e3da04c5284464968e84f105a"}],"parameters":[{"id":11323,"valuesIds":["11323_1"]},{"id":15851,"valuesIds":["15851_1"]},{"id":451,"valuesIds":["451_2048"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Oczka metalowe wew.\\u00d810 mm / zew.\\u00d816 mm (100par)</h1><ul><li><b>Kolor: 1 stary mosi\\u0105dz</b></li><li>Sk\\u0142ad-kompozycja: metal magnetyczny</li><li>Wewn\\u0119trzna \\u015brednica oczka: 10 mm</li><li>Zewn\\u0119trzna \\u015brednica oczka: 16 mm</li><li>Wysoko\\u015b\\u0107: 6 mm</li><li>Techniki: wyr\\u00f3b torebek, toreb i portfeli</li><li>Cechy dodatkowe: Do wyrob\\u00f3w sk\\u00f3rzanych</li></ul>"}]},{"items":[{"type":"TEXT","content":"<p>Oczka metalowe skr\\u00f3cone. U\\u017cywane jako przelotka do sznurk\\u00f3w i gum. Sk\\u0142adaj\\u0105 si\\u0119 z dw\\u00f3ch cz\\u0119\\u015bci.</p><p>&nbsp;</p><p> Do mocowania przelotek s\\u0142u\\u017cy zagniatacz, kt\\u00f3ry znajduje si\\u0119 pod kodem i . Do tkaniny zalecamy u\\u017cy\\u0107 zestawu dziurkaczy, kt\\u00f3re znajduj\\u0105 si\\u0119 pod kodem . Wykorzystywane s\\u0105 g\\u0142\\u00f3wnie w przemy\\u015ble odzie\\u017cowym (przy wyrobie kurtek, bluz). Znajduj\\u0105 zastosowanie w kaletnictwie np: przy produkcji toreb. W kontakcie z wod\\u0105 oczka mog\\u0105 rdzewie\\u0107.</p><p>Do wstawienia oczek wykorzystywane jest narz\\u0119dzie do nitowania, kt\\u00f3re znajduje si\\u0119 pod kodem .</p><p>&nbsp;</p><p> Wewn\\u0119trzna \\u015brednica podk\\u0142adki: 11 mm</p><p>Zewn\\u0119trzna \\u015brednica podk\\u0142adki: 16 mm</p>"}]},{"items":[{"type":"TEXT","content":"<p>Podana cena dotyczy 100 par produktu</p>"}]},{"items":[{"type":"TEXT","content":"<p>Kod produktu: 3267-060917</p>"}]}]},"eans":["8591149069178"]}",`

headers:["Authorization: Bearer <token>","Accept: application/vnd.allegro.public.v1+json","content-type: application/vnd.allegro.public.v1+json","User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:38.0) Gecko/20100101 Firefox/38.0","Connection: keep-alive","Accept-Language: pl","Accept-Encoding: deflate"]

Odpowiedź:
{"errors":[{"code":"ProductDuplicate","message":"An error has occurred","details":null,"path":null,"userMessage":"Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."}]}

**Comment by hahyes** [comment]
Możliwe, że ten EAN jest podany jako parametr a nie jako identyfikator produktu. Tamte oferty mogą być nieprzypisane do żadnego produktu i po prostu mieć wypełniony EAN.

**Comment by PrzemyslawLukanowski** [comment]
Co do wyszukiwarki - jest dokładnie tak, jak napisał @hahyes. Działanie GET /sale/products nie jest tożsame z działaniem wyszukiwarki ofert na stronie, a oferty faktycznie zwróciliśmy dlatego, ponieważ mają uzupełniony EAN w parametrach. 
Jeśli otrzymasz komunikat o duplikacie, zwróć uwagę na adres w nagłówku Location, tam zwracamy identyfikator odnalezionego przez nas produktu. W Twoim przypadku jest to https://api.allegro.pl/sale/products/9405b0b5-a8e5-479b-a617-ec8b0226ed57. Zwróciłem także uwagę, że EAN przekazujesz w stary, niewspierany już przez nas sposób. Możesz przenieść numer EAN z tablicy "eans", przenieść go do sekcji parametrów (jak poniżej) i spróbować utworzyć nowy produkt:

```
...
	"parameters": [{
		"id": 11323,
		"valuesIds": ["11323_1"]
       }, 
       {
                "id": 225693,
                "values": [
                    "8591149069178"
                 ]
       },
       {
		"id": 15851,
		"valuesIds": ["15851_1"]
       }, {
		"id": 451,
		"valuesIds": ["451_2048"]
       }],
...
```

**Comment by rasskabak** [comment]
OK, więc EAN mojego produktu, to 8591149069178.

Wysyłam zapytanie GET, https://api.allegro.pl/sale/products?ean=8591149069178 - dostaję wynik jak wyżej (brak produktów z tym EANem).

Chcę stworzyć nowy produkt, wysyłam:
POST, https://api.allegro.pl/sale/product-proposals, z parametrami:
```
[parameters] => Array
(
	[0] => stdClass Object
	(
		[id] => 11323
		[valuesIds] => Array
		(
			[0] => 11323_1
		)
	)

	[1] => stdClass Object
	(
		[id] => 15851
		[valuesIds] => Array
		(
			[0] => 15851_1
		)
	)

	[2] => stdClass Object
	(
		[id] => 451
		[valuesIds] => Array
		(
			[0] => 451_2048
		)
	)

	[3] => stdClass Object
	(
		[id] => 225693
		[values] => Array
		(
			[0] => 8591149069178
		)
	)
)
```

W nagłówku odpowiedzi faktycznie dostaję link do produktu - https://api.allegro.pl/sale/products/3e19bec4-08e7-411d-bedb-ca68f3f40908. Pobieram szczegóły tego produktu i w odpowiedzi otrzymuję:



```
[parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 15851
                    [name] => Płeć
                    [valuesLabels] => Array
                        (
                            [0] => Produkt uniseks
                        )

                    [valuesIds] => Array
                        (
                            [0] => 15851_4
                        )

                    [values] => 
                    [unit] => 
                    [options] => stdClass Object
                        (
                            [identifiesProduct] => 
                        )

                )

            [1] => stdClass Object
                (
                    [id] => 237190
                    [name] => Marka
                    [valuesLabels] => Array
                        (
                            [0] => Inna
                        )

                    [values] => Array
                        (
                            [0] => Inna
                        )

                    [unit] => 
                    [options] => stdClass Object
                        (
                            [identifiesProduct] => 
                        )

                )

            [2] => stdClass Object
                (
                    [id] => 451
                    [name] => Kolor
                    [valuesLabels] => Array
                        (
                            [0] => czarny
                            [1] => szary
                            [2] => żółty
                        )

                    [valuesIds] => Array
                        (
                            [0] => 451_2
                            [1] => 451_128
                            [2] => 451_512
                        )

                    [values] => 
                    [unit] => 
                    [options] => stdClass Object
                        (
                            [identifiesProduct] => 
                        )

                )

            [3] => stdClass Object
                (
                    [id] => 224017
                    [name] => Kod producenta
                    [valuesLabels] => Array
                        (
                            [0] => 11
                        )

                    [values] => Array
                        (
                            [0] => 11
                        )

                    [unit] => 
                    [options] => stdClass Object
                        (
                            [identifiesProduct] => 
                        )

                )

            [4] => stdClass Object
                (
                    [id] => 225693
                    [name] => EAN
                    [valuesLabels] => Array
                        (
                            [0] => 5904067836655
                        )

                    [values] => Array
                        (
                            [0] => 5904067836655
                        )

                    [unit] => 
                    [options] => stdClass Object
                        (
                            [identifiesProduct] => 
                            [isGTIN] => 1
                        )

                )

        )
```
Od razu widać, że produkt ma inny nr EAN. Wchodzę więc na Allegro i szukam ofert po tym EANie. Znajduję te same kółka, u innego sprzedającego, który usnął oryginalny EAN producenta i zastąpił go własnym. Nie jest to mój EAN, więc nie mogę go używać. Do tego w przypadku tego produktu może nie jest to aż tak wielki problem, ale nie mam gwarancji, że gdzie indziej nie okaże się, że produkt z innym EANem różni się jakimś detalem, przez co jest to w rzeczywistości inny produkt.

**Comment by rasskabak** [comment]
Poszedłem o krok dalej i uzupełniłem wszystkie możliwe parametry, wszystkie z innymi wartościami niż w już istniejącym produkcie. Wszystkie z nich, poza parametrem Stan, są oznaczone jako "definiujące produkt". Mimo tego cały czas ta sama zwrotka - ProductDuplicate. Tak jakby serwer brał pod uwagę tylko np nazwę, ignorując pozostałe parametry.

```
[parameters] => Array
(
	[0] => stdClass Object
	(
		[id] => 11323
		[valuesIds] => Array
			(
				[0] => 11323_1
			)

	)

	[1] => stdClass Object
	(
		[id] => 17448
		[values] => Array
			(
				[0] => 0.001
			)

	)

	[2] => stdClass Object
	(
		[id] => 15851
		[valuesIds] => Array
			(
				[0] => 15851_1
			)

	)

	[3] => stdClass Object
	(
		[id] => 237190
		[values] => Array
			(
				[0] => Pasmanterie.eu
			)

	)

	[4] => stdClass Object
	(
		[id] => 451
		[valuesIds] => Array
			(
				[0] => 451_2048
			)

	)

	[5] => stdClass Object
	(
		[id] => 3766
		[valuesIds] => Array
			(
				[0] => 3766_8
			)

	)

	[6] => stdClass Object
	(
		[id] => 215918
		[values] => Array
			(
				[0] => 1
			)

	)

	[7] => stdClass Object
	(
		[id] => 215926
		[values] => Array
			(
				[0] => Brak
			)

	)

	[8] => stdClass Object
	(
		[id] => 215930
		[values] => Array
			(
				[0] => 
			)

	)

	[9] => stdClass Object
	(
		[id] => 215922
		[values] => Array
			(
				[0] => brak
			)

	)

	[10] => stdClass Object
	(
		[id] => 224017
		[values] => Array
			(
				[0] => Pasmanterie.eu_3267_29160
			)

	)

	[11] => stdClass Object
	(
		[id] => 225693
		[values] => Array
			(
				[0] => 8591149069178
			)

	)
)
```

**Comment by PrzemyslawLukanowski** [comment]
@rasskabak Wygląda to na podobny problem co w wątku #4769. Przekazałem zgłoszenie do weryfikacji, wrócę z informacją, gdy uda nam się znaleźć przyczynę problemów.

**Comment by PrzemyslawLukanowski** [comment]
@rasskabak Problem nie powinien już występować.

**Comment by rasskabak** [comment]
Póki co wygląda na to, że działa :).
