### ISSUE TITLE
422 Unprocessible Entity - /sales/product-offers/{offerId} - przy próbie aktualizacji TecDoc Version

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4772]
Próba aktualizacji TecDoc Version strzałem PATCH na /sales/product-offers

URL: https://api.allegro.pl/sale/product-offers/{offerId}
TraceID: c903f7b2d2d4fa08
JSON: []

URL: https://api.allegro.pl/sale/product-offers/{offerId}
TraceID: bb66899eb840e86e
JSON: {}

Oba kończą się 422 Unprocessable Entity 

Pomożecie dowiedzieć się co jest nie tak ?

**Comment by PrzemyslawLukanowski** [comment]
W pierwszym przypadku powodem błędu było to, że przekazałeś pustą tablicę` [] `zamiast obiektu `{}`. W drugim przypadku wygląda na to, że obiekt jest dodatkowo opakowany w cudzysłów ` "{}"`- usuń go, a request powinien przejść poprawnie.

**Comment by pliszka** [comment]
działa dzięki zamykam

**Comment by pliszka** [comment]
Zobaczył byś jeszcze te TraceID co jest powodem że dostaję 422 ? (każdy do innej oferty) teraz część ofert przechodzi część nie.

TraceID: 
- 6816300bb376ced7
- ee7a3910e72a90fd
- 92fafe3d8a2e03e7
- b730d96e9ce41cf1
- 6685a760751e2e0a
- 3458eca917baba4
- 452d93eab4475dcd
- ac8545135b74f775
- cf8e58ecf39f40d3
- 75987a399a6642f6
- 85be205e80ffeb88

Dla 1891dfed28dcc21a dostaję z API:

{"errors":[{"code":"ConstraintViolationException.ValidProduct","message":"Niepoprawna wartość parametru Producent części (127415) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : \"NPS\".","details":"ConstraintViolationException.ValidProduct","path":"null","userMessage":"Niepoprawna wartość parametru Producent części (127415) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : \"NPS\"."}]}

Ale edycja tej samej oferty na panelu allegro  (/offer/{id})  poprzez edytuj ofertę działa już poprawnie i o nic się nie kłóci.... czy można ten sam mechanizm mieć w API czy muszę te oferty jakoś poprawiać ręcznie ?

**Comment by PrzemyslawLukanowski** [comment]
Podobny komunikat otrzymasz, gdy spróbujesz edytować ofertę za pomocą PUT /sale/offers/{Id}. Niestety nie ma na to obejścia, musisz zaktualizować w ofertach wartośc parametru "Producent części" na aktualny, czyli "NPS" ("127411_339197").

**Comment by pliszka** [comment]
a co w przypadku jeśli producentem jest DENSO a nie NPS ? wtedy jedyną opcją jest odpięcie produktu z oferty by zachować poprawnego producenta ?

**Comment by PrzemyslawLukanowski** [comment]
Możesz także zgłosić sugestię zmiany danych w produkcie, wtedy odpięcie nie będzie wymagane -> https://allegro.pl/offer/product/report/a42bc9e0-2ba9-40c6-bc96-3cc2141ce97a.

**Comment by pliszka** [comment]
czy zgłaszanie sugestii można realizować jakoś przez API ?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie, jednak mamy to w planach - na razie bez sprecyzowanego terminu.
