### ISSUE TITLE
/order/events z parametrem from - brak pojedynczych zamówień

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#4773]
Problem, z którym się borykam, polega na tym, że korzystając z REST API, od czasu do czasu, w tabeli zamówień mojej bazy, brakuje pojedynczego zamówienia. Przykładem takiego zamówienia jest np. ID: 62606422-f07b-11eb-8420-b3f45db6e162, złożone w dniu wczorajszym tj. 29.07.2021. 

Skrypt pobierający zamówienia z REST API i zapisujący do naszej bazy danych odpalam co kilka minut, a mimo to zamówienie nie zostało zapisane. Gdy odpaliłem skrypt dziś ręcznie, co ważne z przestawionym ID ostatniego eventu o kilkadziesiąt pozycji do tyłu, zamówienie zapisało się prawidłowo. Więc wychodzi na to, że zapis do bazy działa prawidłowo (choć oczywiście, biorę pod uwagę, że może być jeszcze jakiś błąd, który przeoczyłem). Skrypt działa tak:

1. Pobieram ID ostatniego eventu zapisanego w moje bazie danych.
2. Wykorzystuję to ID w requeście /order/events?type=READY_FOR_PROCESSING&limit=1000&from=TUTAJ_ID_Z_PKT_1
3. Przetwarzam pobrane w punkcie drugim eventy, a następnie zamówienia - zapisuję je do bazy danych.
4. Pobieram id ostatniego eventu przez /order/event-stats i zapisuję do bazy, aby przy kolejnym uruchomieniu skryptu wykorzystać go w punkcie 1.

Czy jest taka możliwość, że event wraz powiązanym z nim zamówieniem trafia do REST API z opóźnieniem (licząc od czasu faktycznego jest złożenia)? Czy jest możliwość, że po tym jak ja zapiszę ID ostatniego zamówienia w swojej bazie, złożone zamówienie trafia, po Waszej stronie do REST API z wcześniejszym/mniejszym ID i dlatego pobierając zamówienia z ID, które sobie zapisałem już go nie widzę? Podejrzewam, że nie ma takiej możliwości, ale pytam na wszelki wypadek. Rozumiem, że wystarczy posługiwanie się samym ID ostatniego eventu, aby pobrać kolejne, nie muszę w tym celu porównywać dat?

**Comment by PrzemyslawLukanowski** [comment]
Co do Twoich pytań - nie, takie sytuacje nie powinny występować. Jeśli chodzi o algorytm, który opisałeś, sugeruję zrezygnować z punktu 4. i jako ostatni event, którego używasz w pkt 2, wskazywać id ostatniego eventu, który pobrałeś w pkt 3 i to on powinien zaczynać kolejną iterację. W przeciwnym przypadku, między zakończeniem pkt 3. a rozpoczęciem pkt 4. możemy wygenerować event, który zostanie zagubiony.

**Comment by AlpanetPL** [comment]
Rozumiem. Serdeczne dzięki za pomoc.
