### ISSUE TITLE
Pobieranie ofert

### ISSUE THREAD

**Issue by janczajkowski** [allegro/allegro-api#4774]
Czy istnieje możliwość pobierania przez API wszystkich ofert motoryzacyjnych ?

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) i parametru `category.id`możesz pobierać informacje o ofertach w danej kategorii. ID kategorii sprawdzisz natomiast za pomocą [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) ([link do poradnika](https://developer.allegro.pl/sale/#identyfikator-kategorii)). Pamiętaj jednak, że z GET /offers/listing mogą korzystać wyłącznie zweryfikowane aplikacje, więcej na ten temat przeczytasz w [naszym newsie](https://developer.allegro.pl/news/#public-offers-restrictions).
