### ISSUE TITLE
You have been blocked

### ISSUE THREAD

**Issue by YayKay** [allegro/allegro-api#4776]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [x] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próba uzyskania tokena do rest api (https://allegro.pl/auth/oauth/device) kończy się niepowodzeniem i odpowiedzią jak w tytule.
Zmiana adresu ip nie pomogła.

**Comment by MaciejFrackowiak** [comment]
Dla środowiska testowego adres wywołania to https://allegro.pl.allegrosandbox.pl/auth/oauth/device.

**Comment by YayKay** [comment]
> Dla środowiska testowego adres wywołania to https://allegro.pl.allegrosandbox.pl/auth/oauth/device.

Ten sam rezultat dla https://allegro.pl.allegrosandbox.pl/auth/oauth/device
![image](https://user-images.githubusercontent.com/71512768/127858649-70e324ec-2a62-445a-afe8-9d86d664f520.png)

**Comment by MaciejFrackowiak** [comment]
Prześlij proszę przykładowy request i response (+trace id) wraz z numerem IP przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4776.

**Comment by YayKay** [comment]
@MaciejFrackowiak  Czy mogę prosić i zajęcie się sprawą? Zostało ponownie zgłoszone przez formularz kontaktowy z konta , którego dotyczy problem (produkcyjnego). Od 5 sierpnia (odpowiedź email od allegro) nie zostało nic w tej sprawie zrobione.

**Comment by AureliuszBrussy** [comment]
@YayKay prześlij proszę wszystkie niezbędne dane: także przykładowy request i response (+trace id). Dotychczas otrzymaliśmy tylko adres IP.

**Comment by YayKay** [comment]
@AureliuszBrussy  Czy jest jakaś normalniejsza forma kontaktu z Państwem? Gdy dosyłam przez formularz informacje, o które Państwo proszą, odpowiada mi co chwilę inna osoba. 
Proszę o przekazanie ostatniego złogszenia (zawierającego pełny html otrzymany jako response) Odpowiedź na zgłoszenie nr "16921754"    [ ref:_00D24aE05._5003VHLBBG:ref] osobie odpowiedzialnej za problemy API.

**Comment by AureliuszBrussy** [comment]
@YayKay prześlij proszę jeszcze w zgłoszeniu nr 16921754 pełną strukturę HTML odpowiedzi, którą otrzymałeś.

**Comment by YayKay** [comment]
@AureliuszBrussy A jak mam przesłać jeszcze coś w konkretnym zgłoszeniu? Formularz, do którego zostałem skierowany nie umożliwia takiej opcji.

**Comment by AureliuszBrussy** [comment]
@YayKay zgłoszenie do mnie dotarło. W swoim requeście w Postmanie wyłączasz defaultowe nagłówki (headers). Skorzystaj z defaultowych nagłówków Content-Length i Host - wtedy request powinien zakończyć się powodzeniem.

**Comment by YayKay** [comment]
@AureliuszBrussy  Teraz działa, dziękuję. Niby oczywista rzecz,a jednak warto to dodać do dokumentacji :).
