### ISSUE TITLE
Update opisu za pomocą sale/product-offers

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#4777]
Dzień dobry - próbuję zmienić sam opis za pomocą sale/product-offers oraz trybu PATCH - niestety nie otrzymuję prawidłowego statusu.
Wszystkie inne funkcje pozostałe mi działają więc chyba z autoryzacją ok, a to jakiś inny problem....

trace-id: 433722e96bc5cde1

**Comment by MaciejFrackowiak** [comment]
Nagłówek Accept oraz Content-Type przekazujesz w postaci "application/vnd.allegro.public.v1+json" - a ten zasób dostępny jest obecnie tylko w wersji v2 lub v3 - musisz zatem zmienić zawartość nagłówków.

**Comment by lasoczczyk** [comment]
Dziękuję - działa :)
