### ISSUE TITLE
Adres e-mail nadawcy

### ISSUE THREAD

**Issue by wasyl1547** [allegro/allegro-api#4778]
Tworząc przesyłkę wskazujemy też tam adres e-mail sprzedającego.
Czy to powinien być mail przypisany do konta np. test@gmail.com czy mail wygenerowany przez Allegro otrzymany w wiadomości e-mail np. test123@user.allegrogroup.pl?

**Comment by MaciejFrackowiak** [comment]
Jest to standardowy adres email sprzedającego. Tylko email kupującego musi być maskowany, abyśmy rozpoznali właściwe zamówienie.

**Comment by wasyl1547** [comment]
Ok, dziękuję za odpowiedź.
