### ISSUE TITLE
Pytanie o Centrum Wiadomości - statystyki terminowości

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4779]
Czy statystyki terminowych odpowiedzi na wiadomości są liczone dla wątków (GET /messaging/threads) ?
Czy wątki są tworzone dla poszczególnych klientów, czy jeszcze bardziej zagnieżdżone, np: klient-zamówienie, klient-pytanie o ofertę ...?

**Comment by AureliuszBrussy** [comment]
Wątki tworzymy pomiędzy poszczególnymi użytkownikami - nie są bardziej zagnieżdzone. 

Czas odpowiedzi w tym momencie liczymy tylko dla wiadomości zadanych poprzez "Pytanie do sprzedającego" (typ: **ASK_QUESTION** w **messages[].type**).

**Comment by kfijalko** [comment]
Poproszę o szczegóły:
czy statystyka w danym wątku będzie liczona tylko raz jeżeli wystąpi ASK_QUESTION?
czy ma znaczenie do ilu ofert zadał pytania, czy ma znaczenie w jakim odstępie czasu zadał pytania?

**Comment by AureliuszBrussy** [comment]
Jeżeli pojawi się w wątku więcej wiadomości typu ASK_QUESTION od tego samego użytkownika, a w międzyczasie nie pojawiła się żadna odpowiedź od sprzedającego - liczymy czas odpowiedzi względem tej starszej (pierwszej chronologicznie) wiadomości. 

Najlepiej trzymać się jednak ogólnej zasady - na każdą wiadomość najlepiej odpowiedzieć możliwie szybko.

**Comment by kfijalko** [comment]
Tylko ja pytam pod kątem zaprogramowania autorespondera. Nie chcę odpowiadać na każdą wiadomość od klienta bo to bardzo zaśmieci komunikację i zamiast satysfakcji klienta otrzymamy niezadowolenie. Dlatego wolałbym precyzyjnie ustalić jakie zdarzenia (pytania) ze strony klienta startują licznik statystyki terminowości odpowiedzi. @AureliuszBrussy czy jest Pan w stanie wskazać w jakich dokładnie warunkach staruje licznik terminowości?

W moim obecnym rozwiązaniu opartym na mailach mam takie warunki:
id wątku to: zakodowany mail klienta (zakładam iż jest on jednoznacznym wskazaniem na parę kupujący-sprzedający) + slug(tytuł maila)
Dla każdego wątku wysyłam tylko jedną autoodpowiedź.
W tym podejściu mam 100% skuteczności i 3minuty średni czas odpowiedzi (czytanie maili co 5 minut).
zauważyłem, że w centrum wiadomości wątki są zakładane dla zakodowanego maila klienta, jeżeli zapyta on o różne oferty lub zada pytanie o złożone zamówienie to wiadomości trafiają do jednego wątku.
Myśle, że przy przejściu z maili na api muszę w ramach wątku rozpoznawać pod-wątki, czyli pytania o poszczególne oferty, pytania do zamówienia...

Może ktoś z obecnych ma jakieś doświadczenia / przemyślenia na temat autorespondera opartego na api?

**Comment by kfijalko** [comment]
ok, rozumiem
