### ISSUE TITLE
Problem przy logowaniu do Sandboxa za pomocą Tokena

### ISSUE THREAD

**Issue by dida886** [allegro/allegro-api#478]
Po otrzymianiu tokena i próby zalogowania się do serwisu wyświetla mi się taki błąd:

{"error":"Unauthorized","error_description":"Full authentication is required to access this resource"}

Wydaje mi się, że konto w serwisie nie jest w pełni aktywowane.

Email: xtest.develop@gmail.com

**Comment by MaciejPotepa** [comment]
@dida886 

Aktywowałem Twoje konto na Sandboxie.
