### ISSUE TITLE
Pobieranie dyskusji

### ISSUE THREAD

**Issue by miecha3l** [allegro/allegro-api#4781]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

### Zapytanie
```
curl --location --request GET 'https://api.allegro.pl/sale/disputes?limit=100&offset=0' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer <access_token>'
```

### Odpowiedź
```
{
   "disputes": []
}
```

Problem pojawia się podczas pobierania dyskusji dla kilku kont allegro z którymi pracuję. Konta posiadają otwarte dyskusje, natomiast zasób API /sale/disputes zwraca:

a) Pustą listę - nazwa konta allegro **Ettiene**
b) Zwraca listę na której brakuje co najmniej jednej dyskusji - nazwa konta allegro **stiatkisieci**

W obu przypadkach w allegro pokazują się dyskusje, które powinny zostać zwrócone przez API, a z jakiegoś powodu odpowiedzi nie pokrywają się z rzeczywistością

**Comment by kfijalko** [comment]
Allegro zaraz poprosi cię o trace-id, wtedy sprawdzą szczegóły wysłanych zapytań.
Sam możesz się upewnić czy przekazujesz właściwe tokeny. Token musi być przypisany do konta, dla którego chcesz pobrać dyskusje.

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniał @kfijalko - proszę o przykładowe trace-id które otrzymałeś w odpowiedzi w nagłówku.

**Comment by miecha3l** [comment]
9048313f2e38f54d - request który zwraca pustą listę
a39e98ef50e315ac - request który zwraca listę z brakującą co najmniej jedną dyskusją

**Comment by AureliuszBrussy** [comment]
W 9048313f2e38f54d prawidłowo zwracamy pustą tablicę - użytkownik powiązany z tym tokenem nie ma żadnej dyskusji od kupującego.

W przypadku a39e98ef50e315ac - czy jesteś w stanie podać id brakującej dyskusji?

**Comment by miecha3l** [comment]
Dziękuję za weryfikację problemu. Okazało się, że w  obu przypadkach wina leżała po stronie klienta, który podał nieprawidłowe dane dostępowe do konta. Zamykam
