### ISSUE TITLE
Problem z pobieraniem listy wątków na koncie

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4782]
Przy próbie pobrania listy wątków na koncie dostaję "403 ForbiddenError".
Odpowiedz serwera:
{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]}

To co leci do serwera:
$VAR1 = bless( {
                 '_method' => 'GET',
                 '_uri' => bless( do{\(my $o = 'https://api.allegro.pl/messaging/threads?limit=4&offset=1')}, 'URI::https' ),
                 '_content' => '',
                 '_uri_canonical' => $VAR1->{'_uri'},
                 '_headers' => bless( {
                                        'accept' => 'application/vnd.allegro.public.v1+json',
                                        'user-agent' => 'libwww-perl/6.36',
                                        'authorization' => 'Bearer  TOKEN ',
                                        '::std_case' => {
                                                          'if-ssl-cert-subject' => 'If-SSL-Cert-Subject'
                                                        }
                                      }, 'HTTP::Headers' )
               }, 'HTTP::Request' );

Czy możecie podpowiedzieć co może być przyczyną?

To samo też dzieję się jak wykonam zapytanie komendą curl.

**Comment by AureliuszBrussy** [comment]
Sprawdź, czy nie korzystasz z tokenu **bearer-token-for-application** zamiast z **bearer-token-for-user**. Jeżeli korzystasz z tokenu bearer-token-for-user upewnij się również, czy token ma odpowiednie uprawnienie (scope): allegro:api:messaging.

**Comment by AleksyZajac** [comment]
Ten sam token działa bez problemu  z "GET /sale/disputes" a nie działa z: "GET /messaging/threads".
Czy do zasobu GET /messaging/threads jest potrzebny inny token?

**Comment by AureliuszBrussy** [comment]
Nie, nie jest potrzebny inny token, ale musi być to token użytkownika (bearer-token-for-user). Czy token posiada odpowiedni [scope](https://developer.allegro.pl/auth/#lista-dost%c4%99pnych-scope-%c3%b3w) (**allegro:api:messaging**)? Podaj proszę jeszcze trace-id, które dostajesz w nagłówku odpowiedzi z błędem AccessDenied.

**Comment by AleksyZajac** [comment]
np.: 
    Trace-Id                                          : f21c6cc6b1a297fc
lub 
    Trace-Id                                          : 22ae21ba85930402

**Comment by thefoe76** [comment]
mam to samo, disputes działają a mają DOKŁADNIE takie same ustawienia (bearer-token-for-user). Nie stosuje żadnych scopów, czyli wszystko działa by default. Cały czas Access Denied, czyli Allego jak zwykle coś zepsuło.

**Comment by AureliuszBrussy** [comment]
@thefoe76 @AleksyZajac access tokeny użytkowników z których korzystacie nie mają odpowiedniego scope'a (allegro:api:messaging). Wygląda na to, że oryginalny access token został wygenerowany jeszcze przed dodaniem przez nas nowego scope'a, stąd przy jego odświeżaniu macie cały czas te same uprawnienia - bez allegro:api:messaging. Nie jest to błąd. 

Wasza aplikacja w takim przypadku powinna zgłosić się po całkiem nowy token - wyświetlimy użytkownikowi consent screen i po wyrażeniu przez niego zgody - aplikacja będzie miała dostęp do Centrum Wiadomości.

**Comment by AleksyZajac** [comment]
Dziękuję, po pobraniu nowego tokena wszystko działa.
