### ISSUE TITLE
Czy jest możliwość w REST API sprawdzić które oferty zostały odpięte od produktu przez Allegro?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4783]
Czy jest jakiś zasób REST API dzięki któremu po otrzymaniu informacji od Allegro, że "Część Twoich ofert była połączona z niewłaściwym produktem, dlatego odpięliśmy je od produktów" będę mógł zebrać automatycznie identyfikatory takich ofert? Chodzi mi o to, żeby to sobie automatycznie i regularnie monitorować.

**Comment by MaciejFrackowiak** [comment]
Nie, obecnie nie mamy takiego zasobu w API Allegro.
