### ISSUE TITLE
Lista wiadomości z wiadomościami bez odpowiedzi

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4784]
Czy da się pobrać listę wiadomości na które nie została udzielona odpowiedź lub nowych wiadomości ?

**Comment by MaciejFrackowiak** [comment]
Możesz skorzystać z filtra "after" dla [GET /messaging/threads/{threadId}/messages](https://developer.allegro.pl/documentation/#operation/listMessagesGET), wówczas otrzymasz listę wiadomości, które zostały utworzone od wybranego momentu czasu.

**Comment by AleksyZajac** [comment]
Ok, ale po czym mogę stwierdzić czy na daną wiadomość została udzielona odpowiedź?
Dla przykładu mam wiadomość od klienta:
                          {
                            'subject' => undef,
                            'createdAt' => '2021-07-24T14:07:03.029Z',
                            'hasAdditionalAttachments' => $VAR1->{'messages'}[0]{'author'}{'isInterlocutor'},
                            'author' => {
                                          'login' => 'xxxxxxxxxxxxxxxxxxxxxxx',
                                          'isInterlocutor' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' )
                                        },
                            'thread' => {
                                          'id' => 'ccjzbuOqyYGt6tlATxEg7AruKymQMgmiAM0pblbMpGB'
                                        },
                            'id' => 'a30b05fd-5341-407b-ace4-ee53092b5ced',
                            'type' => 'ASK_QUESTION',
                            'text' => "Prosze o numer przesyłki",
                            'status' => 'DELIVERED',
                            'attachments' => [],
                            'relatesTo' => {
                                             'offer' => undef,
                                             'order' => {
                                                          'id' => '4d57d481-e3cb-11eb-b84a-35c9817b607f'
                                                        }
                                           }
                          },

**Comment by MaciejFrackowiak** [comment]
Możesz skorzystać z [PUT /messaging/threads/{threadId}/read](https://developer.allegro.pl/documentation/#operation/changeReadFlagOnThreadPUT) i oznaczyć wątek jako przeczytany dopiero, gdy odpowiesz na wiadomość.

**Comment by AleksyZajac** [comment]
Kiedy wiadomość jako typ otrzymuje "MESSAGE_CENTER" ?

**Comment by MaciejFrackowiak** [comment]
Taki typ wiadomości pojawi się, gdy wiadomość zostanie wysłana bezpośrednio poprzez [Centrum wiadomości](https://allegro.pl/moje-allegro/moje-konto/centrum-wiadomosci/wiadomosci) na stronie WWW lub API.

**Comment by AleksyZajac** [comment]
Dziękuję za wyjaśnienia.
