### ISSUE TITLE
Zmiany w trwającej aukcji: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#4785]
Występuje problem: 
 - [ ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

PUT /sale/offers/10639465821

Response: 
{"errors":[{"code":"ValidationError.MethodArgumentNotValidException","message":"Not valid parameters","details":null,"path":null,"userMessage":"Not valid parameters"}]}

**trace-id: e575828908d6b71e**

Przy zapisywaniu szablonu w trwającej aukcji wyrzuca 422 - niestety nie mam pomysłu co podaję nie tak. Przy nowo wystawianych aukcjach ten problem nie występuje.

**Comment by AureliuszBrussy** [comment]
Prześlij proszę cały request (wraz z pełnym body) który wykonujesz - postaram się to wyjaśnić.

**Comment by lasoczczyk** [comment]
`stdClass Object
(
    [id] => 10639465821
    [name] => Złączka do wody 19/19 mm
    [category] => stdClass Object
        (
            [id] => 255912
        )

    [product] => stdClass Object
        (
            [id] => f6cb012e-9036-4394-aeef-b6da88248441
        )

    [customParameters] => 
    [description] => stdClass Object
        (
            [sections] => Array
                (
                    [0] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <h1>Złączka do wody 19/19 mm</h1><h2>Opis produktu:</h2><p>Złączka do wody 19/19 mm - metalowa złączka do przewodów wodnych.</p><h2>Opis zastosowania:</h2><p>Złączka do wody 19/19 mm - umożliwia włącznie reduktora, parownika w układ chłodzenia silnika. Ciecz z układu chłodzenia silnika ogrzewając parownik intensyfikuje przemianę LPG z fazy ciekłej w fazę lotną.</p>
<p>Złączka do wody 19/19 mm - umożliwia także połączenie dwóch przewodów wodnych.</p><h2>Dane techniczne:</h2><p>Złączka do wody 19/19 mm:</p>
<ul>
<li>średnica zewnętrzna z obu stron - 19 mm.</li>
</ul><h2>Cechy produktu</h2><ul>
<li>Średnice złączki: 19/19 mm </li>
</ul><h2>Informacje dodatkowe</h2><ul>
<li>Kod produktu Nagaz: 15.NAG.786</li>
<li>Producent: GOMET</li>
<li>Kod producenta: GZ-253AS</li>
</ul>
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/11b146/b73fe46341d590761af73572735d
                                        )

                                )

                        )

                    [1] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/115616/0a092b244dc990f18460a54715ce
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => TEXT
                                            [content] => <h2>Opis zastosowania:</h2><p>Złączka do wody 19/19 mm - umożliwia włącznie reduktora, parownika w układ chłodzenia silnika. Ciecz z układu chłodzenia silnika ogrzewając parownik intensyfikuje przemianę LPG z fazy ciekłej w fazę lotną.</p><p>Złączka do wody 19/19 mm - umożliwia także połączenie dwóch przewodów wodnych.</p><h2>Dane techniczne:</h2><p>Złączka do wody 19/19 mm:</p><ul><li>średnica zewnętrzna z obu stron - 19 mm.</li></ul>
                                        )

                                )

                        )

                    [2] => stdClass Object
                        (
                            [items] => Array
                                (
                                    [0] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [content] => <h2>Cechy produktu</h2><ul><li>Średnice złączki: 19/19 mm</li></ul><h2>Informacje dodatkowe</h2><ul><li>Kod produktu Nagaz: 15.NAG.786</li><li>Producent: GOMET</li><li>Kod producenta: GZ-253AS</li></ul>
                                            [url] => https://a.allegroimg.com/original/118f39/d8a867e444c589b62b9f1554e262
                                        )

                                    [1] => stdClass Object
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/11c5ef/981c4b2e4ab5b0be394ce3b60584
                                        )

                                )

                        )

                )

        )

    [compatibilityList] => 
    [tecdocSpecification] => 
    [sellingMode] => stdClass Object
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 4.00
                    [currency] => PLN
                )

            [startingPrice] => 
            [minimalPrice] => 
            [netPrice] => Array
                (
                    [amount] => 3.25
                    [currency] => PLN
                )

        )

    [tax] => stdClass Object
        (
            [percentage] => 23.00
            [rate] => 23.00
            [subject] => 
            [exemption] => 
            [id] => b763d782-572a-47db-8752-8b2cb32b3d0a
        )

    [stock] => stdClass Object
        (
            [available] => 55
            [unit] => UNIT
        )

    [publication] => stdClass Object
        (
            [duration] => 
            [status] => ACTIVE
            [startingAt] => 
            [endingAt] => 
            [endedBy] => 
            [republish] => 
        )

    [delivery] => stdClass Object
        (
            [shippingRates] => stdClass Object
                (
                    [id] => e7c945f1-bd9f-4630-bf67-3e014a5982f9
                )

            [handlingTime] => PT24H
            [additionalInfo] => Wysyłka w dni robocze od poniedziałku do piątku. Jeżeli zamówisz do 14 - wysyłka będzie wysłana jeszcze  tego samego dnia
            [shipmentDate] => 
        )

    [payments] => stdClass Object
        (
            [invoice] => VAT
        )

    [discounts] => 
    [afterSalesServices] => stdClass Object
        (
            [impliedWarranty] => stdClass Object
                (
                    [id] => f6823ee2-4ad0-496c-8032-445bfb815661
                )

            [returnPolicy] => stdClass Object
                (
                    [id] => b22f4108-f5e0-4367-aa76-eea63a5473a6
                )

            [warranty] => stdClass Object
                (
                    [id] => e26fd748-7dc1-4a54-80b0-c06e4368af7d
                )

        )

    [additionalServices] => 
    [sizeTable] => 
    [fundraisingCampaign] => 
    [promotion] => stdClass Object
        (
            [emphasized] => 
            [bold] => 
            [highlight] => 
            [departmentPage] => 
            [emphasizedHighlightBoldPackage] => 
        )

    [location] => stdClass Object
        (
            [countryCode] => PL
            [province] => LODZKIE
            [city] => Łódź
            [postCode] => 90-740
        )

    [external] => stdClass Object
        (
            [id] => 260
        )

    [attachments] => Array
        (
        )

    [contact] => 
    [validation] => stdClass Object
        (
            [errors] => Array
                (
                )

            [warnings] => Array
                (
                )

            [validatedAt] => 2021-08-02T11:25:55.448Z
        )

    [createdAt] => 2021-04-22T08:51:29.000Z
    [updatedAt] => 2021-08-02T11:25:55.449Z
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [url] => https://a.allegroimg.com/original/11b146/b73fe46341d590761af73572735d
                )

            [1] => stdClass Object
                (
                    [url] => https://a.allegroimg.com/original/115616/0a092b244dc990f18460a54715ce
                )

            [2] => stdClass Object
                (
                    [url] => https://a.allegroimg.com/original/118f39/d8a867e444c589b62b9f1554e262
                )

        )

    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                )

            [1] => stdClass Object
                (
                    [id] => 214434
                    [valuesIds] => Array
                        (
                            [0] => 214434_266982
                        )

                )

            [2] => stdClass Object
                (
                    [id] => 127415
                    [valuesIds] => Array
                        (
                            [0] => 127415_859548
                        )

                )

            [3] => stdClass Object
                (
                    [id] => 129591
                    [valuesIds] => Array
                        (
                            [0] => 129591_64
                            [1] => 129591_1
                            [2] => 129591_2
                            [3] => 129591_4
                            [4] => 129591_32
                            [5] => 129591_8
                            [6] => 129591_16
                        )

                )

            [4] => stdClass Object
                (
                    [id] => 130309
                    [valuesIds] => Array
                        (
                            [0] => 130309_1
                            [1] => 130309_2
                            [2] => 130309_4
                        )

                )

            [5] => stdClass Object
                (
                    [id] => 17448
                    [values] => Array
                        (
                            [0] => 0.036
                        )

                )

            [6] => stdClass Object
                (
                    [id] => 215858
                    [values] => Array
                        (
                            [0] => GZ-253AS
                        )

                )

        )

)`

**Comment by lasoczczyk** [comment]
[request.txt](https://github.com/allegro/allegro-api/files/6923148/request.txt)

**Comment by lasoczczyk** [comment]
A to mi zapisuje DEBUG:

`* Hostname was found in DNS cache
*   Trying 5.134.213.11...
* Connected to api.allegro.pl (5.134.213.11) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=PL; ST=wielkopolskie; L=Pozna\U0144; OU=IT; O=ALLEGRO.PL Sp. z o.o.; CN=edge.allegro.pl
* 	 start date: 2021-06-02 13:51:03 GMT
* 	 expire date: 2022-07-04 13:51:03 GMT
* 	 subjectAltName: api.allegro.pl matched
* 	 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
* 	 SSL certificate verify ok.
> PUT /sale/offers/10639465821 HTTP/1.1
Host: api.allegro.pl
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgwMjUzMDEsInVzZXJfbmFtZSI6Ijk5Njg0MzEyIiwianRpIjoiNzkyOWI3YjYtZTM3NS00MjUyLWI1ZWItYzA1NWU2N2UwNzI0IiwiY2xpZW50X2lkIjoiZWNhZmI1MjY5Mjc4NGE5YTlhMDBhNWVjMDA5YTY1YjMiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.9UCAhqz_Yyajq47bsFcpPFs4LUDq2NLlfLylJs8f9n2ZkGpFdS_JbYWukiuN3FO8OFYQ3uzGTaYi0fEW9592xrqrwW-pvst3H33WaQigdLyMsvvKUm6HrZlUV8cxsv2uIMc_hfO_0bmZ0ovWJZ_AouI5lq6oW75PmhROXDjw9aV0GxD3ChaTb34TBCI-t1Z4wFHNPbEKygx83jH4vH8ZCrvaNH9RnvKT0es-n1btGytRV9oEDtcQLKLeDC1XDQNiXEvRPWCIFdBmPv87GvGr1Bkz8g2hvPPpyUUb-puG2sFAa8MeDwC5VZpVtSoAY9FmXEE-BomrE2pTfQv2wEUTYA
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 4729
Expect: 100-continue

< HTTP/1.1 100 Continue
< HTTP/1.1 422 Unprocessable Entity
< expires: 0
< cache-control: no-cache, no-store, max-age=0, must-revalidate
< x-xss-protection: 1; mode=block
< pragma: no-cache
< x-frame-options: DENY
< trace-id: da89d662f628dff1
< date: Tue, 03 Aug 2021 09:48:09 GMT
< x-content-type-options: nosniff
< content-type: application/json
< transfer-encoding: chunked
* HTTP error before end of send, stop sending
< 
* Closing connection 0
`

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś jeszcze enkodować ten obiekt na json?

**Comment by lasoczczyk** [comment]
[request_json.txt](https://github.com/allegro/allegro-api/files/6923433/request_json.txt)
Załączam - na przyszłość już będę wiedział :)
Dzięki. Wydaje się validować - może chodzi o jakieś znaczki z opisu....

**Comment by AureliuszBrussy** [comment]
W opisie (**description**) korzystasz z url zdjęcia, który nie znajduje się w sekcji **images**. Url tego zdjęcia to: `https://a.allegroimg.com/original/11c5ef/981c4b2e4ab5b0be394ce3b60584`.
