### ISSUE TITLE
Co jakiś czas trzeba ponownie połączyć aplikację

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#4786]
Witam,

Mamy stworzoną aplikację allegro i wszystko działa w porządku. Jednak co jakiś czas nasze konta są jakby "rozłączane" i podczas odświeżenia tokena (który wygasa i nie chce się czasami odświeżyć, może to przez to?) pojawia się okno ponownego łączenia z aplikacją. Mimo, że jeszcze wczoraj wieczorem było okej i nikt przez noc nic nie zmieniał. 

To jest normalne zachowanie systemu?

**Comment by kfijalko** [comment]
Nie, mam konta połączone z aplikacją. W ramach kont codziennie wykonuje żądania (w tym odświeżenie tokenów).
Przez ostatnie dwa lata nie musiałem ponownie łączyć. Dopiero ostatnio wprowadzone uprawnienie do centrum wiadomości wymusiło ponowne połączenie konto-aplikacja, żeby pobrać nowy token z nowym zakresem uprawnień.
Zarządzanie tokenami (pobieranie, odświeżanie) mam wyłączone do osobnej klasy "singleton". To ona wydaje tokeny żądaniom i to ona wie kiedy token odświeżyć i zapisać.
Powinieneś dokładnie sprawdzić proces odświeżenia tokena. Szczególnie jeżeli masz przetwarzanie równoległe.
Prawdopodobnie gdzieś gubisz nowy token w trakcie odświeżania. Jak nie zapiszesz nowego tokena to musisz ponownie łączyć konto-aplikacja.

**Comment by MaciejFrackowiak** [comment]
@mrezlik Jest dokładnie tak jak przedstawił to @kfijalko - raz autoryzując aplikację nie wymuszamy ponownej jej weryfikacji. Wyjątek stanowią sytuacje z wprowadzeniem nowego scope`a jak to miało miejsce w przypadku [scope dla Centrum wiadomości](https://github.com/allegro/allegro-api/issues/4702).

**Comment by kfijalko** [comment]
Prośba do Allegro @MaciejFrackowiak 
Może opracowalibyście i udostępnili jakiś wzorzec w jaki sposób zarządzać tokenami w aplikacji, która wykorzystuje przetwarzanie równoległe, mikroserwisy, wiele serwerów/dokerów ...
Temat tokenów pojawia się co jakiś czas i na pewno by to pomogło. Wydaje mi się, że większość zgłoszeń wynika z "gubienia tokena", niewłaściwego redirect_uri lub niewłaściwego typu tokena.
Ja niestety nie posiadam odpowiedniej wiedzy i wykształcenia z zakresu IT, żeby podjąć się takiego zadania.

**Comment by MaciejFrackowiak** [comment]
@mrezlik Dokładnie tak. 

@kfijalko Dziękuję za sugestię - przedyskutujemy temat w zespołach i postaramy się wyjść naprzeciw oczekiwaniom.
