### ISSUE TITLE
GET /messaging/threads kolejność w wynikach?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4787]
Czy lista wątków którą zwraca  /messaging/threads jest posortowana od tego w którym ostatnio pojawiło się jakieś zapytanie/wiadomość? 

Czy może w kolejności utworzenia wątku w systemie?

Wątek jest przypisany do użytkownika, jak system zachowuje się jak użytkownik np. XXXX zadał pytanie w 2019-05-01 a kolejne w 2021-08-03?

Gdzie na liście będzie wątek?

**Comment by MaciejFrackowiak** [comment]
Tak, sortowane są wg daty ostatniej wiadomości. W związku z tym wiadomość z 2021-08-03 sprawi, że wątek będzie wyświetlany jako pierwszy.
