### ISSUE TITLE
Nowa wiadomość w centrum wiadomości a znak nowej linii?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4788]
Przy próbie wysłania poniższego zapytania 
https://api.allegro.pl/messaging/threads/T5SrQZGkqXjyHKgKG7XeVetUwCC1bssnDxhgmJKcbUm/messages

{
 "recipient": {
    "login": "xxxxxxx"
},
 "text": "Witamy! 

Bardzo dziękujemy za informacje.",
 "attachments": []
}

dostaje:

400 Bad RequestError 1
$VAR1 = {
          'errors' => [
                        {
                          'userMessage' => 'Bad Request',
                          'path' => undef,
                          'details' => undef,
                          'code' => 'ERROR',
                          'message' => 'Bad Request'
                        }
                      ]
        };

Jak mam zakodować znak nowej linii oraz polskie znaki?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj z "\n" dla nowej linii. Najprostszym sposobem testowania API jest równoległe korzystanie z serwisu WWW - pobierając wiadomości napisane przez Centrum wiadomości na WWW zobaczysz efekt końcowy w wersji API.
