### ISSUE TITLE
The HTTP method is not allowed

### ISSUE THREAD

**Issue by elvisef** [allegro/allegro-api#4789]
Cześć.

Mam coś takiego w PHP:
```
    define('clientID','xxx');
    define('secretID','xxx');

    /* Pobieranie tokenu */
    /* ================= */

        $uchwytToken    = curl_init();
        $urlToken       = "https://allegro.pl/auth/oauth/token";
        $auth           = base64_encode(clientID.":".secretID);
        $naglowkiToken  = array('Authorization: Basic '.$auth.'','Content-Type: application/x-www-form-urlencoded');

        curl_setopt($uchwytToken, CURLOPT_URL, $urlToken);
        curl_setopt($uchwytToken, CURLOPT_HTTPHEADER, $naglowkiToken);
        curl_setopt($uchwytToken, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($uchwytToken, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($uchwytToken, CURLOPT_POST, true);
        curl_setopt($uchwytToken, CURLOPT_POSTFIELDS, 'grant_type=client_credentials');

        $odpowiedzToken = curl_exec($uchwytToken);
        $odpowiedzKod   = curl_getinfo($uchwytToken, CURLINFO_HTTP_CODE);

        curl_close($uchwytToken);

        if ($odpowiedzToken === false || $odpowiedzKod !== 200) {
            exit ("Coś poszło nie tak $odpowiedzKod $odpowiedzToken");
        }

        $odpowiedzTokenJSON = json_decode($odpowiedzToken);


    /* Pobieranie danych */
    /* ================= */

        $uchwytDane     = curl_init();
        $urlDane        = "https://api.allegro.pl/offers/listing";
        $naglowkiDane   = array(
                                'Authorization: Bearer '.$odpowiedzTokenJSON->access_token.'',
                                'Accept: application/vnd.allegro.public.v1+json'
                            );

        curl_setopt($uchwytDane, CURLOPT_URL, $urlDane);
        curl_setopt($uchwytDane, CURLOPT_HTTPHEADER, $naglowkiToken);
        // curl_setopt($uchwytDane, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($uchwytDane, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($uchwytDane, CURLOPT_POSTFIELDS, 'phrase=telewizor');
        // curl_setopt($uchwytDane, CURLOPT_POSTFIELDS, 'searchMode=DESCRIPTIONS');

        $odpowiedzDane = curl_exec($uchwytDane);
        curl_close($uchwytDane);
        
        var_dump($naglowkiDane);
        var_dump($odpowiedzDane);
        die;

        $odpowiedzDaneJSON = json_decode($odpowiedzDane);
        $odpowiedzDaneTab = json_decode(json_encode($odpowiedzDaneJSON),true);

        foreach($odpowiedzDaneTab as $test)
        {
            var_dump($test);
            die;
        }

    
    die('koniec');

```
Zrobiłem sobie wcześniej var_dump'a, żeby zobacyzć zwrotkę z curl'a pobierającego oferty, i mam:
![2021-08-04_10-19](https://user-images.githubusercontent.com/25976749/128147404-443b909d-60d4-4bd0-beba-522eb6b92e10.png)

Co to właściwie oznacza ? Ten komunikat mówi o czym konkretnie ?
Mam gdzieś błąd w kodzie ?
Może coś przeoczyłem, no nie widzę...

Autoryzacja oczywiście przechodzi pomyślnie, bo zwraca mi token, a aplikacja Allegro jest zweryfikowana, bo nie mam nic zablokowanego na liście aplikacji a korzystam z jednej. Druga utworzyłem i też testowałem żeby sprawdzić czy coś z weryfikacją nie jest poblokowane. Ale wg API wszystko powinno działać tak jak tu mam... teoretycznie.

![2021-08-04_10-21](https://user-images.githubusercontent.com/25976749/128147766-ebcf30d4-c9a6-4d11-83ff-53e1c99081df.png)

**Comment by kfijalko** [comment]
Endpoint/adres: /offers/lisiting obsługuje metodę GET.
Komunikat mówi, że wysłałeś inne żądanie, które nie jest obsługiwane.
Nie do końca rozumiem Twoj kod, ale wygląda jak byś wysłał żądanie POST.

**Comment by elvisef** [comment]
> Endpoint/adres: /offers/lisiting obsługuje metodę GET.
> Komunikat mówi, że wysłałeś inne żądanie, które nie jest obsługiwane.
> Nie do końca rozumiem Twoj kod, ale wygląda jak byś wysłał żądanie POST.

A no tak, racja. POSTFIELDS jest do POST'a, a tutaj musi być GET dla pobrania danych.
No chcę listę ofert pobrać sobie.

Zmieniłem teraz curl'a pobierającego oferty na:
`	/* Pobieranie danych */
	/* ================= */

		$uchwytDane 	= curl_init();
		$urlDane	= "https://api.allegro.pl/offers/listing/?phrase=telewizor&limit=1";
		$naglowkiDane	= array(
					'Authorization: Bearer '.$odpowiedzTokenJSON->access_token.'',
					'Accept: application/vnd.allegro.public.v1+json'
				);

		curl_setopt($uchwytDane, CURLOPT_URL, $urlDane);
		curl_setopt($uchwytDane, CURLOPT_HTTPHEADER, $naglowkiDane);
		curl_setopt($uchwytDane, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($uchwytDane, CURLOPT_RETURNTRANSFER, true);
`

Czyli dodałem parametry dla GET'a i usunąłem POSTFIELDS który (z tego co piszą) inicjuje automatycznie POST'a (bez opcji CURL_POST niby..).

Teraz mam:
`string(207) "{"errors":[{"code":"VerificationRequired","message":"Access is denied. Verification is required.","details":null,"path":null,"userMessage":"Access denied. Access available only for verified applications."}]}"
`

**Comment by kfijalko** [comment]
Przeczytaj post #4566

**Comment by elvisef** [comment]
> Przeczytaj post #4566

Tak, czytałem już wcześniej, dzięki.

> @elvisef Dostęp do GET /offers/listing jest limitowany i wymaga weryfikacji - proces ten odbywa się poza naszym zespołem, dlatego tu proszę o cierpliwość.

Ta "weryfikacja" to jakiś złożony proces ? Tutaj chodziło tylko o włączenie dwuetapowego logowania na koncie i aktywację samego konta, tak ? Przydałby się przycisk "aktywuj". Ta aplikacja nie jest nigdzie wykorzystywana. Chyba że sprawdzane jest czy nie pochodzę np z Chin, i wtedy jestem blokowany.

W takim razie z cierpliwością czekam.

**Comment by MaciejFrackowiak** [comment]
@elvisef Czysto porządkowo - proces opisał mój kolega w poście https://github.com/allegro/allegro-api/issues/4591#issuecomment-892518237.
