### ISSUE TITLE
Błędne działanie metody doGetSiteJournalInfo na sandboxie

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#479]
W polu siteJournalInfo->itemsNumber zawsze dostaję wartość 255 niezależnie od tego co wyślę w parameterze startingPoint, a przekazywałem do niego wszystko zgodnie ze sztuką czyli kolejno:
0
2505017329
2505019066
2505026333
2505028933
2505029477
2505029734

Edit: Jakby co to mam logi
Edit 2: konto kormichu

**Comment by kormichu** [comment]
Eh, czeski błąd doGetSiteJournalInfo -> doGetSiteJournalDealsInfo, ale to nie zmienia faktu że istnieje górny limit

**Comment by MaciejPotepa** [comment]
Dzięki za zwrócenie uwagi na tą niespójność. Zgłaszam do odpowiedniego zespołu.
