### ISSUE TITLE
Witam, chciałbym prostymi requestami edytować kody EAN i GTIN wszystkich moich ofert

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4790]
Witam, jestem nowy, dopiero uczę się RestApi.
kiedyś czytałem, że macie narzędzie do łatwego nanoszenia zmian w ofertach.
Już nie pamiętam jakie, coś oprócz PUT i POST.
Chciałbym nadać wszystkim moim ofertom hurtem, przy wykorzystaniu RestApi, odpowiednie kody EAN i GTIN z mojego sklepu.
Nie chcę przekopywać całej dokumentacji.
Czy moglibyście mi doradzić jak mogę to zrobić?
Inna sprawa, którą wolę wyjaśnić to jak przekazać strukturę danych JSON: Zgaduję, że przesyłam w stringu ale jaka ma być nazwa zmiennej POST?
Dziękuję, 
i Pozdrawiam :-)

**Comment by AureliuszBrussy** [comment]
Udostępniamy [batchowe zasoby](https://developer.allegro.pl/documentation/#tag/Batch-offer-modification), dzięki którym możesz zmodyfikować wiele ofert na raz, jednakże nie będą miały zastosowania przy wprowadzaniu parametrów takich jak EAN. Oprócz PUT i POST na endpointcie /sale/offers/{offerId} udostępniamy także [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), dzięki któremu możesz modyfikować ofertę bez konieczności przekazywania całej jej struktury. Więcej o tym przeczytasz w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99). 
Czy możesz rozszerzyć drugie pytanie dotyczące zmiennej POST?

**Comment by Witold1983** [comment]
Dobrze, mam jeszcze tylko pytanie, chcę zmienić hurtem numery EAN i GTIN produktów:
Wspomnianym PATCHEM próbuję przesłać żądanie na adres: 
sale/product-offers/10744524133

Ale mam problem z konfiguracją PHP'owego curl'a:
Nie wiem jakie dane mam przesłać aby żądanie przeszło:



$curl = curl_init('https://allegroapi.io/sale/product-offers/10744524133');
$data='{"parameters":{"224017":{"values":["5900009000005"]},"225693":{"values":["5900009017144"]}},"category":{"id":"18005"}})';
$headers = array(
            "Authorization: Bearer $token",
            "Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PATCH");
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

Dostaję odpowiedź: 
result: {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

Nie wiem co jest nie tak.
Będę wdzięczny za pomoc.

**Comment by Witold1983** [comment]
Dobrze, mam jeszcze tylko pytanie, chcę zmienić hurtem numery EAN i GTIN produktów:
Wspomnianym PATCHEM próbuję przesłać żądanie na adres: 
sale/product-offers/10744524133

Ale mam problem z konfiguracją PHP'owego curl'a:
Nie wiem jakie dane mam przesłać aby żądanie przeszło:



$curl = curl_init('https://allegroapi.io/sale/product-offers/10744524133');
$data='{"parameters":{"224017":{"values":["5900009000005"]},"225693":{"values":["5900009017144"]}},"category":{"id":"18005"}})';
$headers = array(
            "Authorization: Bearer $token",
            "Api-Key: $key",
            "Content-Type: application/vnd.allegro.public.v1+json",
            "Accept: application/vnd.allegro.public.v1+json"
        );
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PATCH");
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

Dostaję odpowiedź: 
result: {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

Nie wiem co jest nie tak.

Będę wdzięczny za pomoc.

**Comment by Witold1983** [comment]
Sprawa nadal aktualna. Uczę się obsługi interfejsu github'a

**Comment by Witold1983** [comment]
Ok, domyśliłem się, że w obu, "Content-Type" i "Accept" ma być nagłówek application/vnd.allegro.beta.v2+json
Teraz, przy powyższym kodzie mam taki błąd:
Nie mam pojęcia o co chodzi:

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => JsonMappingException
                    [message] => Message is not readable.
                    [details] => 
                    [path] => parameters
                    [userMessage] => Invalid request. Please contact the application author.
                )

        )

)

**Comment by Witold1983** [comment]
Ok, miałem błąd w strukturze zapytania.
Za to ten błąd jest bardzo ciekawy:
Jak mam przesłać wartości kodu EAN i GTIN?

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ParameterCategoryException
                    [message] => Unprocessable Entity
                    [details] => 
                    [path] => 
                    [userMessage] => Given parameter id `224017:Manufacturer Code` should no have been passed as `offer` parameter.
                )

        )

)

**Comment by AureliuszBrussy** [comment]
Na zasobie **/sale/product-offers** wyróżniamy dwa rodzaje parametrów - ofertowe i produktowe. Parametr którego dotyczy błąd powinien być przekazany przez Ciebie w polu **product.parameters[]**. Więcej o tym w jaki sposób może rozpoznać parametry ofertowe i produktowe opisujemy w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-ustawi%c4%87-parametry-ofertowe).

**Comment by Witold1983** [comment]
Witam,
Dziękuję za pomoc. Naprawdę widać że się przykładacie do pracy.

Numery GTIN i EAN potrafię podmienić.
Teraz mam problem z kolorem i rozmiarem:
                                           
Jak próbuję je zmienić przez offer to dostaję:
{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Given parameter id `451:Color` should no have been passed as `offer` parameter."}]}


Kiedy przesyłam je w "product"=>parameters
{"offerId":"10744524133","product":{"id":"190050b6-4de1-48cc-9731-9ab2114556f9","parameters":[{"id":"224017","values":["5900009000005"]},{"id":"225693","values":["5900009017144"]},{"id":"25929","valuesIds":["25929_41"],"values":["mazoretka.pl"]},{"id":"130411","valuesIds":["130411_1","130411_4"]},{"id":"451","valuesIds":["451_32"]},{"id":"54","valuesIds":["54_22"]}]},"category":{"id":"18008"}})

dostaję:
{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter `Size`(54) value ((54_22)) does not match the existing parameter value (uniwersalny(3806_16))","details":null,"path":"product.parameters","userMessage":"The provided parameter `Size` value `(54_22)` does not match the existing parameter value `uniwersalny(3806_16)`."}]}

Przejrzałem dokumentację, i wszędzie pisze o wielowariantowości, ale ja na początek, chciałbym ofertom, wystawionym ręcznie, nadać właściwe parametry

**Comment by AureliuszBrussy** [comment]
Produkt (190050b6-4de1-48cc-9731-9ab2114556f9), który jest powiązany z tą ofertą w parametrze "Rozmiar" (54) w naszym Katalogu Produktów posiada wartość o id 3806_16 (uniwersalny). Parametry w ofercie powinny być zgodnie z parametrami produktu - Ty próbujesz wprowadzić inną wartość. 
Jeżeli w produkcie jest błąd - możesz zgłosić to [tutaj](https://allegro.pl/offer/product/report/190050b6-4de1-48cc-9731-9ab2114556f9). W przyszłości umożliwimy zgłaszanie błędów w produktach również przez API.

**Comment by Witold1983** [comment]
Dobrze, rozumiem. 
Dziękuję, za szybką odpowiedź.
