### ISSUE TITLE
Listing offers?

### ISSUE THREAD

**Issue by lobbin** [allegro/allegro-api#4791]
I'm helping a customer with a small application that will list the current prices/offers on some of the customer's products. But as I understand, this is no longer possible unless you are a verified application?

**Comment by AureliuszBrussy** [comment]
[GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) can be used only by verified applications: you can read more in [our news](https://github.com/allegro/allegro-api/issues/4213). If you want to get only offers listed by the user - use [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).

**Comment by lobbin** [comment]
Thank you! What does it mean being a verified application, and how would I get about becoming one?

**Comment by AureliuszBrussy** [comment]
@lobbin please, read [our news](https://github.com/allegro/allegro-api/issues/4213) about verification. If you want to verify to get access to [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - contact us via [the form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), or if you are in the [Partnership Program for Sellers](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) via your account manager to undergo the verification process.
