### ISSUE TITLE
Pobieranie informacji o ofercie

### ISSUE THREAD

**Issue by BigZ25** [allegro/allegro-api#4792]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Opis**
Witam
Mam problem z pobraniem danych dotyczących oferty.
Wykonuję takie zapytanie:

$url = 'https://api.allegro.pl/sale/offers?offer.id=10687104292'

I otrzymuję taką odpowiedź:

https://ibb.co/5RLjD8F

Generalnie chodzi mi o pobranie listy wszystkich moich ogłoszeń i na podstawie tej listy sprawdzanie sygnatury (external.id) każdego ogłoszenia.

**Comment by thefoe76** [comment]
spróbuj 
https://api.allegro.pl/sale/offers/10687104292

**Comment by BigZ25** [comment]
Teraz mam inny komunikat

https://ibb.co/SPMFHX2

**Comment by kfijalko** [comment]
dokumentacja:
https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET
tutaj możesz sprawdzić swój token:
https://jwt.io/
token musi być typu:
bearer-token-for-user
token musi być wydany do konta, do którego należy oferta o którą pytasz
token musi posiadać uprawnienie:
allegro:api:sale:offers:read

**Comment by MaciejFrackowiak** [comment]
@BigZ25 Jak wspomniał @kfijalko - aby pobrać szczegóły oferty musisz być jej sprzedawcą, posiadać token "bearer-token-for-user", czyli wygenerowany w ramach code lub device flow, a także zapewnić dostęp do scope "allegro:api:sale:offers:read". Sprawdź proszę ustawienia swojego wywołania.

**Comment by BigZ25** [comment]
Ok
Dodałem nową aplikację typu Device.
Użyłem kodu z dokumentacji: https://developer.allegro.pl/auth/#device-flow
Niestety pętla kręci się w kółko.
var_dump($resultAccessToken) daje wynik ["error"]=> string(21) "authorization_pending" ["error_description"]=> string(44) "User has not authorized the device code yet." }

**Comment by MaciejFrackowiak** [comment]
Otrzymany przez Ciebie komunikat błędu sugeruje, że nie wprowadzasz otrzymanego kodu, który jest niezbędny do zweryfikowania użytkownika.

**Comment by BigZ25** [comment]
Dobra działa

Dodałem tylko te dwie linijki na początek pętli do():
flush();
ob_flush();

**Comment by MaciejFrackowiak** [comment]
Super, że udało Ci się rozwiązać problem.
