### ISSUE TITLE
lineItems.boughtAt.gte źle interpretuje przesłane dane

### ISSUE THREAD

**Issue by LocalHeroPro** [allegro/allegro-api#4793]
Występuje problem: 
 - [ x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przesłanie `"2021-08-04T00:00:00.000000Z"` powoduje pobranie zamówień od dnia 04 od północy, a powinno od 03 od 22 godziny.

**Comment by MaciejFrackowiak** [comment]
Czy możesz doprecyzować swoje zgłoszenie - dlaczego mielibyśmy zwrócić dane tylko z przedziału 03-22?

**Comment by LocalHeroPro** [comment]
Bo na to wskazuje UTC a jesteśmy w strefie +2.
Inaczej: macie gdziej jak to powinno poprawnie działać? Nie mówię o dokumentacji, bo tam tego nie znalazłem.
Jak mam pobrać zamówienia starsze od początek np. Dzisiejszego dnia.
Jakaa być wersja wymaganego ISO, bo tutaj są braki w dokumentacji.

**Comment by MaciejFrackowiak** [comment]
Korzystając z [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) udostępniamy filtry:

- lineItems.boughtAt.lte - górna granica czasu,
- lineItems.boughtAt.gte - dolna granica czasu.

Czas zwracamy w formacie ISO w postaci "2018-01-01T10:23:43.123Z".

Zatem wykorzystując filtry możesz określić zakres, z którego zwrócimy Tobie zamówienia.

**Comment by LocalHeroPro** [comment]
Super.
Pomijam fakt, że lte kojarzy się z lower than equal, zaś gte z greater that equal. Pomijam, że to całkowicie odwrotnie.
Mogę prosić o opis znakami tego formatu ISO, jego wersję, bo jest wiele, dlaczego nie działa jak dam +2 po czasie? Przecież to w dalszym ciągu odpowiednie ISO, albo samą datę w formacie odpowiedniego ISO?

**Comment by MaciejFrackowiak** [comment]
Górna granica to maksymalna data określona przez użytkownika, czyli "lte" to wszystko przed tą datą, adekwatnie "gte" - wszystko po dacie. Przedział musi być zamknięty, zatem jest to właściwa ścieżka.

Jak podałem w przykładzie: "2018-01-01T10:23:43.123Z", czyli YYYY-MM-DDThh:mm:ss.SSSZ.
Czas podajemy wg strefy ZULU (UTC+0).

**Comment by LocalHeroPro** [comment]
Oznaczenia YYYY i tak dalej z jakiego języka są?

**Comment by LocalHeroPro** [comment]
Czy czas składania zamówień również pokazujecie w tej strefie czasowej?

**Comment by LocalHeroPro** [comment]
Czy filtrowaniu uwzględniacie PL zmiany czasu letniego, itp?

**Comment by LocalHeroPro** [comment]
Przykład gte: https://laravel.com/docs/8.x/validation#rule-gte
Przykład lte: https://laravel.com/docs/8.x/validation#rule-lte

**Comment by LocalHeroPro** [comment]
Przykład gte: https://symfony.com/doc/current/reference/constraints/GreaterThan.html

**Comment by MaciejFrackowiak** [comment]
Oznaczenia YYYY to skróty z języka angielskiego, YYYY - year, MM - month, etc. Każdy czas zwracamy jako czas strefy UTC+0. Po Twojej stronie zostaje obsługa właściwego czasu dla PL - w response zawsze otrzymasz czasu UTC+0.
