### ISSUE TITLE
sale/product-proposals, Parametr nie jest parametrem stringowym

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#4794]
Próbuję utworzyć nowy produkt. W parametrze 224801 (Zakres pobierania płynów), który jest floatem, podaję wartość 1.1 (która jest floatem;) ). W odpowiedzi otrzymuję błąd - "Parametr 224801 nie jest parametrem stringowym"

TraceId: bbeea3f226584019
```
[parameters] => Array
(
...
	[11] => stdClass Object
	(
		[id] => 224801
		[values] => Array
		(
			[0] => 1.1
		)
	)
...	
)
```

**Comment by MaciejFrackowiak** [comment]
Zgadza się, ten parametr przyjmuje wartości typu float, jednak jest również parametrem zakresowym ("range": true,), zatem jako wartość podaj proszę zakres pobierania płynów.

**Comment by rasskabak** [comment]
Spędziłem wczoraj pół dnia, próbując rzutować floata na wszystkie możliwe typy zmiennych, a tu się okazuje, że wzmianka o stringu była tak tylko dla zmyłki :D Teraz działa, dzięki :).
