### ISSUE TITLE
Unprocessed offer when creating new variant set.

### ISSUE THREAD

**Issue by theazgra** [allegro/allegro-api#4795]
Hi,
When I am trying to create/update the variant set I get HTTP result 422, because some offer is not processed yet.
The issue occurs in Sandbox environment!

One error message for example, with trace-id: `f06930d6f4d46306`
```
{
  "errors": [
    {
      "code": "VALIDATION_ERROR",
      "message": "Offers 7680654426, 7680654460 have not been processed yet. Try again later.",
      "details": null,
      "path": null,
      "userMessage": "Offers 7680654426, 7680654460 have not been processed yet. Try again later."
    }
  ]
}

```

This happened when trying to update variant set with ID: `72a8a103-5c92-4c12-adc6-c424ac1ca82c`

I know that the error says that I should try again later, but this has happened to me with 4 different products already.
### My main question
Is this just processing  delay on Allegro side, and I will be able to create/update the variant set, when the processing is done? Or is this result of some wrong configuration on my side?

Thank you

**Comment by MaciejFrackowiak** [comment]
Offers are usually visible up to 60 minutes after listing - as I see you created them just 40 minutes ago. Our mechanism needs some time to process and later combine into multi-variant offers. So please try again later.
