### ISSUE TITLE
Problem z wiązaniem produktów

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4797]
Witam,
Mam taki problem:
Sprzedajemy min. Zestaw Pałeczka mażoretkowa, pokrowiec i owijka.
https://allegro.pl/oferta/zestaw-paleczka-mistral-80cm-owijka-i-pokrowiec-10744443888

Dany produkt ma różne rozmiary: 40cm, 45cm, 50cm, 55cm, 60cm, 65cm, 70cm, 75cm, 80cm.
I trzy kolory końcówek pałeczki: Białe, Żółte i Różowe.
W sumie 3*9 wariantów.

Produkt wiązany w allegro pozwala na podanie wyłącznie jednego z 27wariantów. A co z pozostałymi? Wolałbym nie podawać w nim szczegółów typu rozmiar czy kolor ale podać je w konkretnych wariantach. Ale system mi na to nie pozwala.

Wszystkie warianty produktu mają wspólny Numer EAN i GTIN.

Abstrahując mając tak dodany produkt na stronie oferty zdarza się, że sprzedawany aktualnie w ofercie wariant to 40 cm, a produkt powiązany w nazwie ma 80cm i klient nie wie czego dotyczy aukcja.

Osoba która go dodawała zrobiła 'jak umiała' i muszę kasować powiązania.
Chciałbym wprowadzić produkt prawidłowo.
Moje pytanie brzmi czy każdy wariant ma mieć osobny GTIN ?
Mamy 700produktów.
Koszty nadawania własnych numerów GTIN puszczą nas z torbami.

Bardzo proszę o odpowiedź,
Jestem odpowiedzialny za integrację sklepu z allegro.
Integracja jest dla mnie kwestią być albo nie być ;-)

**Comment by Witold1983** [comment]
Wspomniana wyżej aukcja, w której klient nie wie co kupuje:
https://allegro.pl/oferta/paleczka-mazoretkowa-juniorka-biala-50cm-10749646600

**Comment by MaciejFrackowiak** [comment]
Tak, co do zasady, każdy produkt różniący się od siebie rozmiarem, kolorem, etc. powinien posiadać osobny GTIN - szczegółowe informacje w tej kwestii uzyskasz kontaktując się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), ponieważ nie jest to temat stricte związany z funkcjonowaniem API.

**Comment by Witold1983** [comment]
Ok, mam jeszcze jedno pytanie:
Czy wystawiany produkt na allegro może być dodawany do kilku (podobnych) kategorii czy ma być wyłącznie w jednej?
W im więcej kategoriach zostanie wystawiony, tym bardziej będzie widoczny i tym większa będzie szansa na sprzedaż.

Będę wdzięczny za odpowiedź,
Wiem, że to pytanie nie dotyczy stricte RestApi.

**Comment by MaciejFrackowiak** [comment]
To stricte zależy od produktu - przykładowo, karty SD dostępne są zarówno jako dodatek do telefonów, ale także w fotografii. Co do zasady, produkt powinien być umieszczony w kategorii, która jest dla niego w 100% adekwatna i tym samym nie wprowadza kupującego w błąd.
