### ISSUE TITLE
Problem z utworzeniem oferty - przekroczona liczba szkiców

### ISSUE THREAD

**Issue by pawelosajda** [allegro/allegro-api#4799]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,
Mam problem z utworzeniem draftu oferty na środowisku produkcyjnym, zwracany błąd to 

`{"errors":[{"code":"VALIDATION_ERROR","message":"You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."}]}`

Przykładowe trace id dla POST https://api.allegro.pl/sale/offers
`trace-id: e4e69d41aabd2b9b`
`trace-id: 27cba5add28f6cb5`
`trace-id: 7f5fecc28ce8c0a9`

Wcześniej zgłaszany był taki sam problem https://github.com/allegro/allegro-api/issues/4709

Na koncie liczba draftów jest znacząco poniżej 20000

**Comment by MaciejFrackowiak** [comment]
Problem przekazałem już do właściwego działu, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Liczba draftów została uspójniona, przepraszam za niedogodności.

**Comment by mirkosmuz** [comment]
Tak, mi na kontach klientów którzy mieli 14000 draftów już krzyczało że jest ich za dużo, mimo że oficjalny limit to 20 000.

**Comment by Lukasz-Zurek** [comment]
@mirkosmuz Jeśli taka sytuacja będzie powtarzała się w przyszłości, proszę o kontakt poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i wskazanie id Partnerów, których dotyczy problem. Przyznam, że może pojawić się taka sytuacja. Uspójniamy to na bieżąco.

Przepraszamy za wszelkie utrudnienia z tym związane.

**Comment by ppart** [comment]
Dzień dobry 

Znów ten sam problem, szkiców około 7k (sprawdzane na allegro), a dostaję zwrotkę z allegro "Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców"

**Comment by MaciejFrackowiak** [comment]
@ppart Proszę podaj login lub identyfikator konta oraz przykładowy trace-id wywołania, przy którym otrzymałeś komunikat błędu.

**Comment by ppart** [comment]
> @ppart Proszę podaj login lub identyfikator konta oraz przykładowy trace-id wywołania, przy którym otrzymałeś komunikat błędu.

trace-id: 15022b781878d0c7
trace-id: 32e5339880e3c8c7
trace-id: 75e4cbe6ac3d7dbb
trace-id: 4dd1c3aa5be4671d

You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców.

**Comment by MaciejFrackowiak** [comment]
@ppart Dziękuję za przykłady. Problem przekazałem do właściwego zespołu, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@ppart Odświeżyliśmy dane, dzięki temu dodasz już kolejne szkice.

**Comment by ppart** [comment]
Potwierdzam, tworzą się nowe szkice, dziękuję. Czy można naprawić błąd na stałe ponieważ cyklicznie jest to problemem?

**Comment by MaciejFrackowiak** [comment]
@ppart Rozumiem niedogodności, jednak nie mogę zagwarantować obecnie, że problem nie powtórzy się za jakiś czas. Staramy się minimalizować możliwość wystąpienia błędu, jednak czasem same chęci to niestety i za mało.

**Comment by ppart** [comment]
Dzień dobry

Dziś znów to samo, 15k szkiców, a otrzymujemy zwrotkę:

You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts.","details":"ConstraintViolationException.MaxInactiveOffers","path":"null","userMessage":"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców. 

Proszę o odświeżenie, tak jak poprzednio. Dotyczy "userId":"24251961"

**Comment by MaciejFrackowiak** [comment]
@ppart Problem przekazałem już do weryfikacji, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@ppart Zsynchronizowaliśmy liczbę draftów na wskazanym koncie.

**Comment by ppart** [comment]
Dzień dobry

Ponownie proszę o synchronizację liczby szkiców, na koncie widzę ponad 15k natomiast otrzymuję zwrotkę "Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."

"userId":"24251961"

**Comment by MartaNowaczyk** [comment]
Dzień dobry. Problem przekazałam do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by ppart** [comment]
Dzień dobry

Proszę o rozwiązanie problemu ponieważ nie możemy wysyłać draftów, a co za tym idzie wystawiać produktów.

**Comment by MartaNowaczyk** [comment]
Dzień dobry @ppart
Dane dotyczące draftów są już zsynchronizowane na podanym koncie.

**Comment by ppart** [comment]
Ponownie ciągle pojawia się ten sam problem, czy nie da się go rozwiązać?
"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."
Szkiców na allegro 6k.

userId":"24251961"

Prosiłbym o rozwiązanie (cykliczna automatyczna synchronizacja lub inne wyeliminowanie problemu) ponieważ jest to mocno uciążliwe.

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Dzień dobry @ppart zgłosiłam problem z draftami do zespołu odpowiedzialnego za tą funkcjonalność. Przekazałam też Twoją prośbę o cykliczne/trwałe rozwiazanie. Dam znać jak tylko dostanę odpowiedź. Pozdrawiam.

**Comment by ppart** [comment]
Dobry wieczór

Znów to samo 7 raz i kolejny w przeciągu 2 tygodni. Czy to wykracza poza Państwa możliwości techniczne? Prosiłbym o poprawę błędu.

"Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."
Szkiców na allegro 4k.

userId":"24251961"

**Comment by Lukasz-Zurek** [comment]
@ppart Zgłosiłem to ponownie do odpowiedniego zespołu, do poprawki.

Dodam, że tego typu przypadki mogą się powtarzać. Staramy się maksymalnie zminimalizować i poprawić globalnie.

Przepraszamy za te utrudnienia.

**Comment by ppart** [comment]
Niestety nadal otrzymuje zwrotkę "Nie możesz utworzyć nowych szkiców - Twoje konto przekroczyło maksymalną liczbę 20000 szkiców."

**Comment by Lukasz-Zurek** [comment]
@ppart Jak tylko Twój przypadek zostanie poprawiony, poinformuję o tym takcie w obecnym wątku.

**Comment by MartaNowaczyk** [comment]
@ppart podczas zgłoszenia z 2 stycznia, tak jak pisałam zaadresowałam odpowiednio ten problem i będziemy się temu przyglądać. Problemem jest samo działanie na ofertach na tym koncie. Ponad 1 mln ofert wystawionych na 72h, gdy się skończą wystawiane jest kolejne tyle ofert pod nowym numerem. Jaki jest powód takich działań? Oferta powinna trwać jeśli stan magazynowy na to pozwala. Warto spojrzeć na optymalizację i poprawność działań aplikacji pod tym kontem. Na ten moment możemy poprawiać liczbę draftów po Twoim zgłoszeniu, bo nie ma jeszcze gotowego rozwiązania z naszej strony.

**Comment by ppart** [comment]
Wystawiamy oferty na licytacji 3 dni, po zakończeniu wznawiają się
automatycznie gdy nikt nie dokona zakupu. Na listingu mamy ponad 100k
aukcji ale nie milion.

W dniu pt., 20.01.2023 o 11:00 MartaNowaczyk ***@***.***>
napisał(a):

**Comment by MartaNowaczyk** [comment]
Fakt, nie doprecyzowałam, że ta ilość zmian jest z około tygodnia, także dotyczy rotacji ofert, a nie samej liczby ofert, które są wystawione.

**Comment by ppart** [comment]
Reasumując są to licytacje dlatego są takie ruchy na ofertach

W dniu pt., 20.01.2023 o 12:07 MartaNowaczyk ***@***.***>
napisał(a):

**Comment by MartaNowaczyk** [comment]
@ppart Rozumiem. Tak jak pisałam, ten przypadek jest już w zespole, który ma w planach rozwiązanie tego problemu. Przepraszam za niedogodności, ale do czasu rozwiązania tej kwestii daj po prostu znać, gdy będziesz miał problem ze szkicami.

**Comment by ppart** [comment]
A dziś udało Wam się doraźnie zsynchronizować?

W dniu pt., 20.01.2023 o 13:41 MartaNowaczyk ***@***.***>
napisał(a):

**Comment by Lukasz-Zurek** [comment]
@ppart Tak, udało nam się to doraźnie poprawić.

**Comment by ppart** [comment]
Ok, dziękuję

**Comment by ppart** [comment]
Chciałbym zgłosić, ż co tydzień pojawia nam się ten błąd, teraz również:
"Could not change offer publication status. Nie możesz wystawiać nowych ofert - Twoje konto przekroczyło maksymalną liczbę 200000 aktywnych ofert."

Było to zgłaszane do opiekuna VIP ale problem ciągle występuje, nie możemy wystawiać nowych ofert, raz na tydzień otrzymuję tą odpowiedź. Prosiłbym o weryfikację. User ID ten sam userId":"24251961"

**Comment by Lukasz-Zurek** [comment]
@ppart Jeżeli sprawę zgłaszałeś już raz do opiekuna to myślę, że najlepiej będzie jak skontaktujesz się z nim ponownie. Być może sprawa jest w toku. A jeśli nie - Twój opiekun opisze nam sytuację.

**Comment by ppart** [comment]
Zgłaszałem sprawę poprzednio, aktualnie problem się pojawił i nadal występuje. Czy mogliby Państwo również zsynchronizować liczbę ofert?

**Comment by Lukasz-Zurek** [comment]
@ppart Ok, zgłosiłem dalej do poprawki.

**Comment by Lukasz-Zurek** [comment]
@ppart No i poprawione :)

**Comment by ppart** [comment]
@Lukasz-Zurek dzięki serdeczne za szybką reakcję. Ogólnie przekazywali coś developerzy czy problem da się na stałe naprawić?

**Comment by Lukasz-Zurek** [comment]
@ppart Taki jest plan i tu faktycznie chcemy na stałe zabezpieczyć się przed tego typu sytuacjami. Póki co sytuacja jest monitorowana i analizowana. Naszym celem jest całkowite usunięcie problemu, ale trudno mi tutaj dać jednoznaczną deklarację. Proszę o zrozumienie.
