### ISSUE TITLE
GetPaymentMethods

### ISSUE THREAD

**Issue by blochos** [allegro/allegro-api#48]
Powyższa metoda pobiera wszystkie metody płatnosci ale dla konkretnej aukcji. 
Pierwsze pytanie. czy istnieje metoda pozwalająca pobrac słownik wszystkich metod?
Drugie pytanie. Dla konkretnej aukcji pobrałem dane o metodach płatnosci i widzę tam sporoą liste. nie ma tam jednak Paymentmethodid = tt którą to z kolei widzę w GetPostBuyFormsDataForSellers. nie widzę metody, która widoczna jest w karcie płatnosci na stronie i opisana jest jako Karta płatnicza (PayU)

ogolnie nie widzę 3 metod, które wystepują w GetPostBuyFormsDataForSellers
ai
mtex
tt

jak sobie z tym poradzić?
Z góry dziękuje

**Comment by MaciejPotepa** [comment]
Dziękuję zgłoszenie błędu. Przekazałem do odpowiedniego zespołu. 
Dam znać w tym wątku jak rozwiążemy tą kwestie.

**Comment by MaciejPotepa** [comment]
@blochos Wiem, że minęło trochę czasu, ale te metody nie będą już rozwijane, więc kwestia, którą zgłosiłeś nie będzie adresowna. [Zapraszam do korzystania z REST API. ](https://developer.allegro.pl/orders/)
