### ISSUE TITLE
Statusy zamówień w zakładce Zamówienia

### ISSUE THREAD

**Issue by areklal** [allegro/allegro-api#480]
Witam,

Czy jest możłiwość zmiany statusu zamówienia na Wysłane w zakładce zamówienia?? Jeśli tak to czy można to zrobić poprzez id transakcji?

Arek

**Comment by MaciejPotepa** [comment]
Dzień dobry 

W zakładce [Zamówienia](https://allegro.pl/seller-orders/#!/) w wybranym zamówieniu kliknij w **Opcje** > **Oznacz jako wysłane.** 

Pytając o to czy można to zrobić przez ID transakcji masz na myśli API czy dalej samą zakładkę Zamówienia?

**Comment by areklal** [comment]
Witam,

Jak się to robi ręcznie to wiemy :) Chodzi o to że mamy już wszystko zasadniczo zintegrowane z api allegro i potrzebujemy odejść całkowicie od MS i sprawdzać ew. błędy w realizacji (wysłane/niewysłane) z poziomu allegro. Czyli po wysyłce towaru chcemy automatem poprzez API oznaczyć zamówienie jako wysłane.

**Comment by KrzysztofLukanowski** [comment]
@areklal aktualnie przez API nie ma możliwości oznaczenia zamówienia wysłane/niewysłane. Jednak nie wykluczamy, że w niedalekiej przyszłości udostępnimy taką możliwość.

**Comment by areklal** [comment]
To byłoby fajne bo wprowadziłoby czystość w tej zakładce. Nieraz prócz Api poprostu trzeba zajrzeć do tej zakładki :)

Widziałem że jest coś napisane o wyłączeniu jakichś funkcji dzięki którym możemy ściągać transakcje. Mamy zrobione oprogramowanie od ok 4lat opierając się o to. Widziałem że teraz można pobierać bezpośrednio zamówienia.

To prawda?

**Comment by MaciejPotepa** [comment]
@areklal To prawda, wkrótce będziemy wygaszać część metod w WebAPI. Więcej informacji znajdziesz [tutaj](https://allegro.pl/webapi/news.php#news_100617).

Co do pobierania zamówień w REST API. [Tu](https://developer.allegro.pl/orders/) znajdziesz wszystkie informacje.
