### ISSUE TITLE
Kategoria oferty jest różna od kategorii produktu

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#4805]
Wystawiam produkt, "Czujnik klocka hamulcowego BMW". W naszym systemie jest on przypisany do kategorii 260578, "Okładziny szczęk hamulcowych". Przy próbie połączenia oferty z produktem dostaję błąd "Kategoria oferty jest różna od kategorii produktu - 50860". Kategoria 50860 to "Poduszki silnika", która ma się nijak do układu hamulcowego. Prawdopodobnie ktoś, kto definiował ten produkt, podał złą kategorię.
GUID produktu to 'f32f3072-8c65-4ee1-99cd-20d16d23035a'. W polu category/similar mamy pustą tablicę.
Trace-id: 9bb86586e0c3f4fd
W jaki sposób możemy wystawić ten produkt w poprawnej kategorii, bez kombinowania z usuwaniem kodu producenta / EAN?

**Comment by MaciejFrackowiak** [comment]
Problem z właściwą kategorią dla wskazanego produktu zgłosiłem do weryfikacji. Jeżeli znajdziesz błąd w produkcie możesz to zgłosić poprzez formularz - https://allegro.pl/offer/product/report/{productId}.
Nie ma możliwości obejścia wystawienia danego produktu w innej kategorii, jeżeli nie ma on przypisanych do siebie kategorii podobnych.
