### ISSUE TITLE
incomplete order information returned by the interface（/order/checkout-forms）

### ISSUE THREAD

**Issue by xiaohua1005** [allegro/allegro-api#4806]
Hello, 
         The order information returned by calling the (/order/checkout-forms) interface is incomplete, and the SKU attribute is missing.
         The SKU of the product fed back by the customer is "B60S4177". The following screenshot is provided by the customer. The file in the attachment is the order details returned by the platform.
orderId:7bd152d0-f78c-11eb-8650-ad786052714e.
message:
{
	"summary": {
		"totalToPay": {
			"amount": "1149.00",
			"currency": "PLN"
		}
	},
	"delivery": {
		"address": {
			"firstName": "xx",
			"lastName": "xx",
			"zipCode": "32-400",
			"phoneNumber": "+xxx",
			"city": "xx",
			"street": "xxx",
			"countryCode": "PL"
		},
		"cost": {
			"amount": "0.00",
			"currency": "PLN"
		},
		"method": {
			"name": "Przesyłka kurierska",
			"id": "7203cb90-864c-4cda-bf08-dc883f0c78ad"
		},
		"calculatedNumberOfPackages": 1,
		"time": {},
		"smart": false
	},
	"buyer": {
		"firstName": "xx",
		"lastName": "xx",
		"phoneNumber": "+48 608 152 603",
		"address": {
			"city": "xx",
			"street": "xx",
			"countryCode": "xx",
			"postCode": "xx"
		},
		"guest": false,
		"id": "25126156",
		"login": "xx",
		"email": "xx"
	},
	"revision": "f1445f93",
	"lineItems": [{
		"offer": {
			"name": "xxx",
			"id": "11004563208"
		},
		"quantity": 1,
		"originalPrice": {
			"amount": "1149.00",
			"currency": "PLN"
		},
		"boughtAt": "2021-08-07T14:35:01.400Z",
		"price": {
			"amount": "1149.00",
			"currency": "PLN"
		},
		"id": "7bd152d0-f78c-11eb-8650-ad786052714e",
		"selectedAdditionalServices": []
	}],
	"discounts": [],
	"surcharges": [],
	"payment": {
		"provider": "PAYU",
		"id": "7c15aed1-f78c-11eb-ab41-e9a99bae0c5f",
		"type": "ONLINE",
		"paidAmount": {
			"amount": "1149.00",
			"currency": "PLN"
		},
		"finishedAt": "2021-08-07T14:35:15.441Z"
	},
	"id": "7bd179e1-f78c-11eb-8650-ad786052714e",
	"fulfillment": {
		"shipmentSummary": {
			"lineItemsSent": "NONE"
		},
		"status": "NEW"
	},
	"invoice": {
		"required": false
	},
	"status": "READY_FOR_PROCESSING",
	"updatedAt": "2021-08-07T14:35:15.441Z"
}

**Comment by MaciejFrackowiak** [comment]
We do not return external in order response, because the offer does not have an assigned external (reference number).

**Comment by xiaohua1005** [comment]
The seller reported that the value of Manufacturer Code was filled in during offer, and the seller asked the platform that this is SKU

**Comment by Lukasz-Zurek** [comment]
@xiaohua1005 I understand, but you have sent an order response where we do not return "Manufacturer Code". We return it, among others, in [GET /sale/offers/{offerId}](https://developer.allegro.pl/en/documentation/#operation/getOfferUsingGET), in the parameter: "224017".
