### ISSUE TITLE
Dyskusje - zasób zwraca pustą listę

### ISSUE THREAD

**Issue by mwojtko1** [allegro/allegro-api#4807]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
curl --location --request GET 'https://api.allegro.pl/sale/disputes' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer ....' \
--header 'Cookie: _cmuid=d1565602-a27d-4049-8422-07f03d9c0967; datadome=PWtfjgdwJJEYEEznI1O7V0zt1bLwvmfdw3PxUHcoeqAy1DasRGvavu1VbpO70BnKTP._jSuP.Ldi10X9_70UGE3MvPFOKuQps_P_GLTgXH; wdctx=v3.xU_u1np9Ltdq1lQ3qgH8sDMxkDuuGHjAY5163A4Cklku7FP92RiTZr9DHwDXslk7JI4o0fWKTLOGX6duxHdQlS3ykipntmLUCZVnhTvz908zUqLRcnr90BrxasnNLcWpjdKLcxua-uUcl246oXwv6n6ZYP_OvW7NQUL4InsNoWaaj6jLjihNakBG'

traceId: 79432fc646ea76f7

Konto amiicus ma wiele wylistowanych dyskusji, natomiast przy próbie pobrania wszystkich jak powyżej lub konkretnej po uuid, zasób zwraca pustą listę: 

`{"disputes":[]}
`

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę na rodzaj autoryzacji, który wykorzystujesz - zasób GET /sale/disputes wymaga "bearer-token-for-user", czyli działania w kontekście zalogowanego użytkownika. Natomiast Twój trace-id nie posiada identyfikatora użytkownika, czyli wykorzystałeś autoryzację client_credentials.
