### ISSUE TITLE
Aktualizacja draftu/oferty (Inactive)

### ISSUE THREAD

**Issue by grzegorzwalus** [allegro/allegro-api#4808]
Pobieram dane o ofercie, która jest Inactive. (GET /sale/offers/{offerId})
Rozszerzam o pola, które chciałbym zaktualizować tą samą metodą tylko, że przez PUT.

Dlaczego w odpowiedzi przy aktualizacji oferty otrzymuje Not Found (404) skoro metoda get zwraca dane o id po jakim szukam?

**Comment by grzegorzwalus** [comment]
[10986950902_json.txt](https://github.com/allegro/allegro-api/files/6954894/10986950902_json.txt)

**Comment by Lukasz-Zurek** [comment]
@grzegorzwalus Otrzymujesz błąd "'Nie znaleziono ustawienia podatku VAT dla podanej stawki". W polu **tax.percentage** podałeś wartość 22.00, która najwyraźniej nie jest dostępna dla danej kategorii (122569). Skorzystaj najlepiej z [GET /sale/tax-settings?category.id={categoryId}](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory). W ten sposób pobierzesz wszystkie ustawienia VAT dostępne we wskazanej kategorii i skorzystasz z nich podczas aktualizacji oferty.

**Comment by grzegorzwalus** [comment]
Teraz działa, dziękuję za pomoc ;)
