### ISSUE TITLE
Błąd "Parameter value does not exist"

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4809]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Nie jestem pewien czy nie powrócił problem z #4615. Robię zmianę ilości sztuk i otrzymuję błąd:
Parameter value does not exist (223541)

GET: c6aed822c0d9d055
PUT: a9484b0cfb20b1b2

Zrobiłem przed chwilą ręcznie GET'a na ofercie i parametr 223541 wydaje się mieć prawidłową wartość 223541_303069.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Dziękuję za zgłoszenie i szczegółowe informacje na temat problemu. Sprawę przekazałem do weryfikacji. Wkrótce wrócę z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Po naszej stronie mógł występować tymczasowy problem, który jednak nie powinien się już powtarzać. 

Jeśli błąd nadal się pojawia - daj proszę znać w wątku. Sprawę ponownie przekażę dalej.

**Comment by tomylee0** [comment]
Chyba znów to samo:

GET: 14b65445968ef0f4
PUT: a72351b4d92ce37d
Parameter value does not exist Publishing House (223541).

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Dziękuję. Problem zgłosiłem do odpowiedniego zespołu.
