### ISSUE TITLE
REST to get all watched offers by user id?

### ISSUE THREAD

**Issue by mapet241** [allegro/allegro-api#481]
As in title. I'm looking for REST method to get information on all auctions watched by my user.  So basically I need a rest service that will accept as parameter user id or something else that identifies user and will return list of watched items with details (name price etc.)

Can you point me to the right method? Is it already available? 

To add more: The problem I'm trying to solve is to get immediate notification as soon as price changes on one of the items that I have on my watch list. I have notifications setup for 'obserwowane' but the email is not cumming immediately - it takes quite some time. Maybe there is some other way to setup notifications so that I'm notified immediately (SMS or Email or anything else)?

**Comment by MaciejPotepa** [comment]
Hello 

I'm sorry to being you bad news, but watched offers aren't avalibe via API in any way. 
There is also no other way of sending notifications about it than the e-mail we sent about change of price.

**Comment by mapet241** [comment]
Poprzednią wiadomość z rozpędu napisałem po angielsku :).
Dziękuje za odpowiedź dotyczącą aukcji obserwowanych.
W takim razie czy przy użyciu Państwa API mogę wykonać następujące operacje:
- Wyszukać aukcje (po słowach kluczowych np. 'ekspesr saeco' ) u konkretnego sprzedawcy
- Wyszukać aukcje (po słowach kluczowych np. 'ekspesr saeco' ) wszędzie (u wszystkich sprzedawców)
- Mając już u siebie w aplikacji, listę numerów/id aukcji które mnie interesują, pobierać aktualne ceny każdej z nich, np. co minutę / 5 minut? 

Powyższe kroki pozwoliłyby mi w zasadzie zastąpić funcjonalność pobierania informacji o obserwowanych  aukcjach? Pytanie czy są dostępne endpointy REST które realizowałyby ten scenariusz i czy mają Państwo jakieś limity zapytań które mogłyby przeszkodzić w odpytywaniu serwisu w ten sposób?

**Comment by MaciejPotepa** [comment]
@mapet241 Bardzo dobrze kombinujesz. :)

Do wyszukiwania ofert u sprzedawcy/w serwisie możesz wykorzystać zasób [offers-listing](https://developer.allegro.pl/documentation/#/offers-listing/getListing). 

Mając dane, o których piszesz możesz je pobierać z limitami, które opisaliśmy [tutaj](https://developer.allegro.pl/about/#limits). 

Powyższe kroki w teorii powinny Ci pomóc w stworzeniu mechanizmu, który będzie symulował obserwowane. Jeżeli natrafisz na jakiekolwiek problemy to bardzo chętnie pomożemy.
