### ISSUE TITLE
Wystawianie aukcji przez IAI

### ISSUE THREAD

**Issue by SCDSSO** [allegro/allegro-api#4811]
![JSON](https://user-images.githubusercontent.com/56715818/128845322-ea1138fa-4147-485d-8700-33dbb023e9bc.jpg)
Przy próbie wystawienia aukcji przez panel IAI pojawił się komunikat "Kod odpowiedzi zwrócony przez API Allegro: INVALID_JSON Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro: Invalid request.". O jaki konkretnie błąd może chodzić?

**Comment by Lukasz-Zurek** [comment]
@SCDSSO Sugeruję zgłoszenie tego problemu bezpośrednio do supportu IdoSell. Do weryfikacji potrzebne będą dostępne do pobrania pliki request i response, które widoczne są na zrzucie. Komunikat wskazuje jednak na problem po stronie konfiguracji w IdoSell. W przypadku problemów po stronie naszego serwisu, support IdoSell będzie mógł zgłosić to już bezpośrednio do nas.

**Comment by SCDSSO** [comment]
Dziękuję za odpowiedź,
pozdrawiam
