### ISSUE TITLE
Automatyczna produktyzacja nie działa?

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#4812]
Czy w tej chwili automatyczne tworzenie i łączenie produktów ( w produktyzacji) jest wyłączone?
Przybywa nam produktów w kategorii "moda" które trzeba przeklikać przez kreator "połącz z produktem" mimo że wszystkie parametry są uzupełnione prawidłowo.

**Comment by Lukasz-Zurek** [comment]
Nie. Nie odnotowaliśmy również problemów w tym zakresie. Prześlij proszę przykładowy request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4812.
