### ISSUE TITLE
wysylam.allegro.pl - ubezpieczenie przesyłki

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4815]
W przykładnie podanym w dokumentacji nie zlokalizowałem części dotyczącej ubezpieczenia przesyłki - a dokładnie wartości ubezpieczenia.

{
 "id": "14d3b9c4-ca3b-4e37-89c0-6f6cac24a02e",
 "input": {
  "serviceId": 8490564,     				
  "receiver": {								
    "address": {
      "street": "Testowa 172",		        
      "postCode": "61-132",					
      "city": "Poznań",						
      "countryCode": "PL"			
    },
    "email": "hamu7udk3p+17454c1b6@allegromail.pl",  
    "name": "Jan Kowalski",					
    "company": "Allegro.pl sp. z o.o.",		
    "phone": "500600700",					
    "pointId": "1234567"					
  },
  "pickup": {								
    "address": {							
      "street": "Testowa 8",				
      "postCode": "10-200",					
      "city": "Warszawa",					
      "countryCode": "PL"					
    },
    "email": "email@mail.com",		
    "name": "Jan Kowalski",			
    "company": "Allegro.pl sp. z o.o.",		
    "phone": "500600700",			
    "pointId": "1234567"	
  },
  "items": [								
    {
      "weight": {							
          "value": 12,
          "unit": "KILOGRAM"
      },		            
      "dimensions": {						
        "height": {							
          "value": 20,
          "unit": "CENTIMETER"
        },				
        "width": {							
          "value": 20,
          "unit": "CENTIMETER"
        },		
        "depth": {							
          "value": 20,
          "unit": "CENTIMETER"
        },					
      },
      "description": "Car wheels.",   
      "value": {
        "amount": "2.50",
        "currency": "PLN"
      }
      "type": "PACKAGE"		
    }
  ],
  "type": "PACKAGE",						
  "label": {								
    "sender": {								
      "address": {
        "street": "Testowa 8",
        "postCode": "10-200",
        "city": "Warszawa",
        "countryCode": "PL",
        "county": null                      
      },
      "email": "email@mail.com",
      "name": "Jan Kowalski",
      "company": "Allegro.pl sp. z o.o.",
      "phone": "500600700"
    },
    "fileFormat": "PDF",				
    "referenceNumber": "abcd1234"   		
  },
   "additionalServices": {										
     "cashOnDelivery": {
       "value": {
         "amount": "2.50",
         "currency": "PLN"
       },
       "accountNumber": "12345678901234567890123456",
       "name": "Jan Kowalski",
        "express": false
      },
    "options": [
      "guarantee0930"
    ]
  }
 }
}

**Comment by Lukasz-Zurek** [comment]
Potwierdzam, że we wskazanym zasobie nie ma pola odpowiedzialnego za wartość ubezpieczenia przesyłki.

**Comment by Lukasz-Zurek** [comment]
W tym miejscu chciałbym dodać, że w [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel) mamy obiekt **items** odpowiedzialny za wartość przesyłki. Wartość przesyłki musisz przekazać w następujący sposób:

```
"items": [

{

    "dimensions": 

{},
"weight": 
{},
"description": "Car wheels.",
"value": 

    {
        "amount": "2.50", - wartość przesyłki
        "currency": "PLN"
    },
    "type": "PACKAGE"

}
```
