### ISSUE TITLE
wysylam.allegro.pl - pickup?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4817]
Czy "pickup" w waszym przykładzie oznacza punkt odbioru przesyłki przez kuriera nie zależnie od danych które zostały podane w "dender" ?

  "pickup": {								
    "address": {							
      "street": "Testowa 8",				
      "postCode": "10-200",					
      "city": "Warszawa",					
      "countryCode": "PL"					
    },
    "email": "email@mail.com",		
    "name": "Jan Kowalski",			
    "company": "Allegro.pl sp. z o.o.",		
    "phone": "500600700",			
    "pointId": "1234567"	
  },

Czy jeżeli te dane są takie same jak dane nadawcy to czy ta część jest wymagana?

**Comment by Lukasz-Zurek** [comment]
Dane w obiekcie "pickup" to dane nadawcy wraz z adresem do odbioru przesyłki przez kuriera - są one wymagane.

Natomiast dane w obiekcie "label" to informacje o nadawcy na etykiecie - są one opcjonalne.

Reasumując, jeśli - tak jak Pan wspomniał - dane te są takie same, uzupełnienie danych w obiekcie "label" nie będzie potrzebne.
