### ISSUE TITLE
wysylam.allegro.pl - przykład JSON dla paczkomatu?

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4818]
Czy mogę dostać przykład wysyłki paczki do paczkomatu ?

Jak dobrze rozumiem to ten poniżej jest dla kuriera.
{
 "id": "14d3b9c4-ca3b-4e37-89c0-6f6cac24a02e",
 "input": {
  "serviceId": 8490564,     				
  "receiver": {								
    "address": {
      "street": "Testowa 172",		        
      "postCode": "61-132",					
      "city": "Poznań",						
      "countryCode": "PL"			
    },
    "email": "hamu7udk3p+17454c1b6@allegromail.pl",  
    "name": "Jan Kowalski",					
    "company": "Allegro.pl sp. z o.o.",		
    "phone": "500600700",					
    "pointId": "1234567"					
  },
  "pickup": {								
    "address": {							
      "street": "Testowa 8",				
      "postCode": "10-200",					
      "city": "Warszawa",					
      "countryCode": "PL"					
    },
    "email": "email@mail.com",		
    "name": "Jan Kowalski",			
    "company": "Allegro.pl sp. z o.o.",		
    "phone": "500600700",			
    "pointId": "1234567"	
  },
  "items": [								
    {
      "weight": {							
          "value": 12,
          "unit": "KILOGRAM"
      },		            
      "dimensions": {						
        "height": {							
          "value": 20,
          "unit": "CENTIMETER"
        },				
        "width": {							
          "value": 20,
          "unit": "CENTIMETER"
        },		
        "depth": {							
          "value": 20,
          "unit": "CENTIMETER"
        },					
      },
      "description": "Car wheels.",   
      "value": {
        "amount": "2.50",
        "currency": "PLN"
      }
      "type": "PACKAGE"		
    }
  ],
  "type": "PACKAGE",						
  "label": {								
    "sender": {								
      "address": {
        "street": "Testowa 8",
        "postCode": "10-200",
        "city": "Warszawa",
        "countryCode": "PL",
        "county": null                      
      },
      "email": "email@mail.com",
      "name": "Jan Kowalski",
      "company": "Allegro.pl sp. z o.o.",
      "phone": "500600700"
    },
    "fileFormat": "PDF",				
    "referenceNumber": "abcd1234"   		
  },
   "additionalServices": {										
     "cashOnDelivery": {
       "value": {
         "amount": "2.50",
         "currency": "PLN"
       },
       "accountNumber": "12345678901234567890123456",
       "name": "Jan Kowalski",
        "express": false
      },
    "options": [
      "guarantee0930"
    ]
  }
 }
}

**Comment by Lukasz-Zurek** [comment]
Poniżej przykładowy request z wysyłką do paczkomatu Inpost:

```
{
      "serviceId": "7390312",
      "label": {
         "sender": {
            "name": "Test company",
            "company": "Test company",
            "address": {
               "street": "Testowa 172",
               "postCode": "61-132",
               "city": "Poznań",
               "county": null,
               "countryCode": "PL"
            },
            "email": "email_company@email.com",
            "phone": "755444333"
         },
         "fileFormat": "ZPL",
         "referenceNumber": "Test"
      },
      "receiver": {
         "name": "Joanna Kowalska",
         "address": {
            "street": "Opolska 11",
            "postCode": "31-277",
            "city": "Kraków",
            "county": null,
            "countryCode": "PL"
         },
         "pointId": "KRA18AP",
         "email": "test@allegromail.pl",
         "phone": "000000000"
      },
      "pickup": {
         "name": "Test company",
         "company": "Test company",
         "address": {
            "street": "Testowa 24",
            "postCode": "87-100",
            "city": "Toruń",
            "county": null,
            "countryCode": "PL"
         },
         "pointId": null,
         "email": "email_company@email.com",
         "phone": "755444333"
      },
      "items": [
         {
            "dimensions": {
               "height": {
                  "value": "38",
                  "unit": "CENTIMETER"
               },
               "width": {
                  "value": "8",
                  "unit": "CENTIMETER"
               },
               "depth": {
                  "value": "60",
                  "unit": "CENTIMETER"
               }
            },
            "weight": {
               "value": "1",
               "unit": "KILOGRAM"
            },
            "description": "odzież",
            "value": {
               "amount": "18.98",
               "currency": "PLN"
            },
            "type": "PACKAGE"
         }
      ],
      "type": "PACKAGE",
      "additionalServices": null
   }
```
