### ISSUE TITLE
Dyskusje - informacja że wiadomość typu END_REQUEST została już wysłana

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#4819]
Wysyłając wiadomość w dyskusji mogę określić typ wiadomości REGULAR i END_REQUEST gdzie END_REQUEST można użyć tylko raz.
Jak mogę sprawdzić że w danej dyskusji była już wysłana taka wiadomość? 
Przy zwracanych wiadomościach nie ma podanego typu.

**Comment by Lukasz-Zurek** [comment]
Sprawdzisz to za pomocą [GET/sale/disputes/{disputeId}/messages](https://developer.allegro.pl/documentation/#operation/getMessagesFromDisputeUsingGET). W ten sposób pobierzesz wszystkie wiadomości z wybranej dyskusji, również tę systemową - generowaną automatycznie w trakcie wysłania prośby o zakończenie dyskusji (END_REQUEST) przez [POST /sale/disputes/{disputeId}/messages](https://developer.allegro.pl/documentation/#operation/addMessageToDisputeUsingPOST). Poniżej udostępniam przykładową część response dla tego typu wiadomości:

```
{
    "messages": [
        {
            "id": "25cae969-121a-48b0-be8b-5fed9d93b745",
            "text": "Sprzedający poprosił kupującego o potwierdzenie, że problem został rozwiązany.",
            "author": {
                "role": "SYSTEM"
            },
            "createdAt": "2021-08-11T09:25:13.149Z"
        },
        {
            "id": "f1f41c71-2615-455f-89e2-328de8f7d7a8",
            "text": "Dzień dobry, problem rozwiązany, proszę o zakończenie dyskusji.",
            "author": {
                "login": "Tutaj_login",
                "role": "SELLER"
            },
            "createdAt": "2021-08-11T09:25:13.018Z"
        },
...
```
Pierwsza z góry wiadomość jest systemowa - generujemy ją automatycznie, natomiast kolejna to prośba o zakończenie dyskusji czyli wiadomość wysyłaną przez przez [POST /sale/disputes/{disputeId}/messages](https://developer.allegro.pl/documentation/#operation/addMessageToDisputeUsingPOST), w której przekazujesz m.in. pole: **"type": "END_REQUEST"**.

**Comment by avello** [comment]
Jak odczytywać wiadomości to wiem.
Chodzi o to że wiadomości nie mają określonego typu, a wiadomości systemowe mogą być różne.
Rozpoznawanie typu wiadomości po treści nie jest dobrym sposobem bo treść może ulec zmianie w przyszłości, ale widzę że nie ma innego sposobu.

**Comment by Lukasz-Zurek** [comment]
Rozumiem. Potwierdzam, że nie ma niestety innego sposobu na rozpoznawanie tego typu wiadomości.
