### ISSUE TITLE
Moduł allegro

### ISSUE THREAD

**Issue by ReporterYoung** [allegro/allegro-api#482]
Dzień dobry,

Jesteśmy w trakcie przygotowania się do integracji naszej strony z allegro.

Firma, która nas obsługuje z zakresu IT poleca moduły:

http://prestahelp.com/pl/administracja/32-integracja-z-allegro-pro-prestashop.html
https://x13.pl/integracje-prestashop/integracja-allegro-z-prestashop.html
https://baselinker.com/cennik/

Który moduł wybrać? 

Sklep jest postawiony na PrestaShop wersja 1.6.1.9

strona to reporteryoung.pl

**Comment by KrzysztofLukanowski** [comment]
Dzień dobry,

aktualnie nie współpracujemy z żadnym z tych dostawców, dlatego jako pracownik Allegro nie mogę jednoznacznie sugerować wybór konkretnego modułu. Możliwe, że ktoś na forum poleci dobre rozwiązanie.

**Comment by ReporterYoung** [comment]
Dzień dobry,

 

W takim razie jaki sposób integracji Pan poleca? 

 

Pozdrawiam

 

Angelika Kuśnierz

  _____  

E- commerce Manager

mob. +48 513 768 127
tel. +48 12 295 04 16
email:  <mailto:akusnierz@reporteryoung.pl> akusnierz@reporteryoung.pl

**Comment by AniaMalinowska** [comment]
Aktualnie nie możemy polecić żadnego rozwiązania. Jak już wspomniał @KrzysztofLukanowski, być może  jakieś dobre rozwiązanie zasugeruje ktoś tutaj na forum.
