### ISSUE TITLE
Issue with access

### ISSUE THREAD

**Issue by Liketodev3** [allegro/allegro-api#4820]
Hi. 
I want to import some products into allegro categories, but have got an issue. 
I have client keys of Allegro. 
However, It says client doesn't have access to do so. 

Just doing "POST, GET" to this URL https://api.allegro.pl/sale/offers, it says access denied  ("userMessage":"Access denied. Contact the author of the application.")
Let me know how to proceed.

**Comment by Lukasz-Zurek** [comment]
The error indicates that you are using a token generated under [client-credentials authorization](https://developer.allegro.pl/en/auth/#client-credentials-flow) - without a user context. In our [documentation](https://developer.allegro.pl/en/documentation/), you will find an appropriate indication of what authorization method you should use for a given endpoint:

-   bearer-token-for-user - [device](https://developer.allegro.pl/en/auth/#device-flow) or [code flow](https://developer.allegro.pl/en/auth/#authorization-code-flow);
-   bearer-token-for-application - [client credentials](https://developer.allegro.pl/en/auth/#client-credentials-flow). 

It is also possible that you are trying to download / list an offer that belongs to another account.

Please make sure of the cause of the problem.
