### ISSUE TITLE
Problem z aktywacja oferty

### ISSUE THREAD

**Issue by studio17a** [allegro/allegro-api#4822]
Dzień dobry, 
nie mogę aktywować ofert przy pomocy API.

Dla zapytania: 

`
curl -X PUT \
    'https://api.allegro.pl/sale/offer-publication-commands/'13d7cb55-f186-4e94-a3be-f034e86d572e
    -H 'Authorization: Bearer {token}' \
    -H 'Accept: application/vnd.allegro.public.v1+json' \
    -H 'Content-Type: application/vnd.allegro.public.v1+json' \
    -d '{
      "publication": {
        "action": "ACTIVATE"
    },
      "offerCriteria": [
        {
            "offers":[   
                {
                    "id": "11026817286"
                }
            ],
            "type": "CONTAINS_OFFERS"
        }
    ]
  }'
`

otrzymuję odpowiedź: 

`
{
    "id": "13d7cb55-f186-4e94-a3be-f034e86d572e",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}
`

ale oferta pozostaje szkicem. 
Przy ręcznej próbie aktywacji wszystko jest ok i oferta zostaje wystawiona. 

pozdrawiam, 
Marek Walczak

**Comment by Lukasz-Zurek** [comment]
@studio17a Zweryfikowałem to i okazuje się, że tworząc wcześniej draft za pomocą [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST), dla parametru "11323" przekazałeś dwukrotnie wartość słownikową "11323_1", a powinieneś przekazać ją tylko raz:

```
   "parameters": [
      {
         "id": "11323",
         "valuesIds": [
            "11323_1",
            "11323_1"
         ],
         "values": [],
         "rangeValue": null
      },
...
```

Już wtedy otrzymałeś błąd w obiekcie "validation":

```
            {
                "code": "VALIDATION_ERROR",
                "message": "Too many values in parameter (11323)",
                "details": "",
                "path": "parameters",
                "userMessage": "Too many values in parameter State (11323)."
            },
```
Dlatego również próba aktywacji tej oferty za każdym razem kończy się niepowodzeniem właśnie z tego powodu.

**Comment by studio17a** [comment]
Faktycznie, dziękuję za pomoc.

**Comment by studio17a** [comment]
No niestety, mam znów podobny problem (oferta id 11026817238) ale tym razem nie widzę błędów w walidacji 
    `
"validation": {
        "errors": [],
        "warnings": [],
        "validatedAt": "2021-08-15T10:54:56.483Z"
    }
`

próba aktywacji zwraca
`{
    "id": "13d7cb55-f186-4e94-a3be-f034e86d572e",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}`
a oferta pozostaje szkicem :/

pozdrawiam, 
Marek Walczak

**Comment by Lukasz-Zurek** [comment]
Wskazane uuid: 13d7cb55-f186-4e94-a3be-f034e86d572e odnosi się do innej oferty (11026817286). Natomiast dla oferty nr 11026817238 nadal zwracamy ten sam błąd, co wcześniej.

**Comment by studio17a** [comment]
Uuid był wcześniej użyty. Dziękuję i pozdrawiam
