### ISSUE TITLE
Problem z łączeniem ofert w ofertę wielowariantową: Różne zdjęcia

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4824]
Witam,

Mam trzy oferty powiązane automatycznie w jedną, wielowariantową:

{"id":"d2d874a3-4bcc-4259-ac63-09a8a1c318bd",
"offers":[{"id":"9379529147"},{"id":"10907434291"},{"id":"9379797813"}],
"name":"Dziewcz\u0119ca koszulka z tancerk\u0105, bia\u0142a",
"parameters":[{"id":"54"}]}

Chciałbym dodać czwartą:
10908295002

Kiedy wysyłam requesta PUT'em dostaję komunikat, że różnią się zdjęciami.
Zadałem sobie trud i sprawdziłem, że wszystkie mają identyczne zdjęcia i identyczne url'e zdjęć.
Mam więc pytanie: Co robię nie tak?

Będę wdzięczny za pomoc.

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VALIDATION_ERROR
                    [message] => Offers in variant set connected without color/pattern parameter must have identical photos. Make sure the photos do not differ in small details (e.g. photo size, watermark) or add the color/pattern parameter.
                    [details] => 
                    [path] => 
                    [userMessage] => Offers in variant set connected without color/pattern parameter must have identical photos. Make sure the photos do not differ in small details (e.g. photo size, watermark) or add the color/pattern parameter.
                )

        )

)

**Comment by Lukasz-Zurek** [comment]
Zdjęcia mogą mieć identyczne adresy, jednak nasz system porównuje konkretnie zdjęcia i tu najwyraźniej miniaturka z oferty 10908295002 jest inna. Stąd ten błąd.

Natomiast w ramach **colorPattern** masz możliwość grupowania produktów po zdjęciach, dlatego w takiej sytuacji mogą być one różne.

Proces tworzenia oferty wielowariantowej poprzez nasze API, opisaliśmy dokładnie w [naszym poradniku](https://developer.allegro.pl/multi_variant_offers/#utw%c3%b3rz-ofert%c4%99-wielowariantow%c4%85).

**Comment by Witold1983** [comment]
https://allegro.pl/uzytkownik/mazoretka_pl/taniec-stroje-18008
To są jakieś jaja. W końcu płacę wam za to, to chyba mam prawo wymagać aby to działało. Prawda?
Zadajcie sobie trud, wejdźcie na ten [link](https://allegro.pl/uzytkownik/mazoretka_pl/taniec-stroje-18008) i zobaczcie: Zdjęcią są identyczne.
Nie mam ochoty wiązać ich po color/pattern bo wtedy znikną mi oznaczenia rozmiaru. O czym Łukaszu nie raczyłeś wspomnieć ani słowem.
Możecie przenosić oferty z kategorii, możecie łączyć je z produktami, rozłączać. A ja, szary użytkownik, mam się borykać z waszym botem, który najwidoczniej wymaga szlifów. Szkoda słów.

**Comment by Witold1983** [comment]
Tutaj są te oferty, jakby się wam nie chciało przewinąć strony:
https://allegro.pl/uzytkownik/mazoretka_pl/taniec-stroje-18008

https://allegro.pl/oferta/dziewczeca-koszulka-z-tancerka-biala-6lat-122-10908295002

https://allegro.pl/oferta/dziewczeca-koszulka-z-tancerka-biala-8lat-134-9379529147

**Comment by Witold1983** [comment]
Ok, zadałem sobie trud i podmieniłem opis we wszystkich czterech ofertach. Z zewnętrznymi zdjęciami
Kiedy podmieniam w każdej aukcji opis z identycznym zewnętrznym url'em z mojego sklepu to nie ma bata, zdjęcia muszą być identyczne.
Mam cały czas ten sam błąd.
Ewidentnie macie coś nie tak z botem, który decyduje czy zdjęcia są identyczne, czy się różnią.
Sprawdźcie to do licha ciężkiego. W końcu za to wam płacimy.

**Comment by Witold1983** [comment]
Poradnik też czytałem, robię wszystko wg. niego ale z pominięciem parametru colorPattern ponieważ zależy mi aby klient widział do wyboru cztery różne rozmiary a nie cztery identyczne miniatury

**Comment by Lukasz-Zurek** [comment]
Jak już wspomniałem wcześniej - zdjęcia mogą mieć identyczne adresy, jednak nasz system porównuje zdjęcia pod każdym kątem. Najmniejsza różnica w samym zdjęciu będzie powodowała tego typu niespójności.

Prześlij proszę przykładowy request i response (odnoszący się do błędu) wraz z trace-id (w związku z otrzymywanym błędem) przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4824. Zweryfikujemy dokładnie ten przypadek.

**Comment by Lukasz-Zurek** [comment]
> 
> 
> Poradnik też czytałem, robię wszystko wg. niego ale z pominięciem parametru colorPattern ponieważ zależy mi aby klient widział do wyboru cztery różne rozmiary a nie cztery identyczne miniatury

Ok, rozumiem.

**Comment by Witold1983** [comment]
Dzięki, poszło,
Będę wdzięczny za pomoc.
Pozdrawiam :-)
