### ISSUE TITLE
Błąd w poradniku zarządzania przesyłkami

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#4827]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry, w poradniku [Jak zarządzać przesyłkami przez Wysyłam z Allegro](https://developer.allegro.pl/wza/#jak-anulowa%c4%87-paczk%c4%99) znajduje się błąd w ścieżce anulowania paczki.
Dokładniej chodzi o "wymieszane" adresy dla metody PUT:

- PUT /parcel-management/parcel-cancel-commands/{commandId} <- prawidłowy
- PUT /parcel-management/cancel-commands/{commandId} <- nieprawidłowy

Błąd znajduje się w akapicie "Jak anulować paczkę" (w opisie) oraz jako link w liście zasobów (na końcu poradnika).

**Comment by Lukasz-Zurek** [comment]
Bardzo dziękujemy za wskazane w poradniku błędy. Poprawimy to.

**Comment by magik092** [comment]
Ponadto w sekcji [Jak pobrać protokół nadania przesyłek](https://developer.allegro.pl/wza/#jak-pobra%c4%87-protok%c3%b3%c5%82-nadania-przesy%c5%82ek) w przykładowym Request brakuje w ścieżce `/parcels/`

**Comment by Lukasz-Zurek** [comment]
@magik092 Dziękujemy. Bardzo doceniamy Twoją pomoc. Ten błąd również wkrótce poprawimy.

**Comment by Lebioda** [comment]
Nie bede zakladal osobnego wątku, w tym poradniku tez jest blad:
https://developer.allegro.pl/charges/

> Za pomocą **GET /billing/billing-types** pobierzesz również numer zamówienia, który zwrócimy w polu “order.id”. Dzięki temu w historii operacji billingowych będziesz mógł zidentyfikować zamówienie, dla którego pobrana została opłata.

to nie ten zasób

**Comment by Lukasz-Zurek** [comment]
@Lebioda Potwierdzam. Dziękuję! Poprawimy.
