### ISSUE TITLE
ConstraintViolationException.ValidCompatibilityTable - jak poprawnie ustawić wartość dla oferty która do tej pory była poprawna?

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4829]
Pytanie jak w temacie, coraz więcej ofert nie da się aktualizować (cena / dostępność) z powodu błędu: "ConstraintViolationException.ValidCompatibilityTable" 
pełny komunikat: ConstraintViolationException.ValidCompatibilityTable with message Given compatibility table is outdated, use the current one. Update offer with the most recent product data. / Given compatibility table is outdated, use the current one. Update offer with the most recent product data.

Pytanie skąd wziąć te dane oraz jak powinien wyglądać przykładowy request do API 

Dzięki !

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę listę ofert objętych błędem oraz przykładowy request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #4829.
