### ISSUE TITLE
GET /sale/offers/{offerId} for any offer

### ISSUE THREAD

**Issue by EdLSa** [allegro/allegro-api#483]
Hi,

based on [documentation](https://developer.allegro.pl/en/sale/#similar-offer), _\[I\] must be authorized as a seller that listed the offer in question._ for any `GET /sale/offers/{offerId}`.

Would it be possible to remove this restriction, so I can get details of any offer previously found by `GET
/offers/listing`, or create an endpoint which would allow to get additional details (such as offer description)?

Thanks,
Ed

**Comment by TomekKaczmarek** [comment]
Hi, 

At the moment, we do not plan to remove such restriction in the nearest future. Although thank you for your suggestion, we will consider it in our development plans for public API.

**Comment by EdLSa** [comment]
Would you kindly keep this open until the change is implemented?

Thanks,
Ed

**Comment by MaciejPotepa** [comment]
@EdLSa No problem, we can keep the issue open. But keep in mind that implementing this isn't certain.
