### ISSUE TITLE
PATCH /sale/product-offers/{offerId} - ograniczenia

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4830]
Czy PATCH /sale/product-offers/{offerId} ma takie same ograniczenia jak edycja oferty? Chodzi mi o fakt poprawy tylko jednego z kilku występujących błędów np.

oferta XYZ posiada dwa błędy: 
- ConstraintViolationException.MissingRequiredParameters with message Missing required parameters: 215858 / Missing required parameters: Catalog number for part.
- ConstraintViolationException.ValidOfferName with message Please remove the part in the description that redirects to the “About Seller” tab. / Please remove the part in the description that redirects to the “About Seller” tab.

Czy za pomocą PATCH mogę zlikwidować ConstraintViolationException.MissingRequiredParameters? Nie ruszając jednocześnie ConstraintViolationException.ValidOfferName? Taka operacja nie była możliwa podczas edycji oferty w polu z błędami dostawaliśmy wtedy komunikat że drugi błąd dalej jest do poprawy, jak to wygląda w przypadku metody PATCH logika sprawdzające jest zapinana tylko na pola które są aktualizowane?

**Comment by Lukasz-Zurek** [comment]
@pliszka Nie. W przypadku korzystania z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) możesz faktycznie wysłać tylko to pole, które chcesz zmienić. Następnie ta zmiana jest jednak weryfikowana również pod kątem wszystkich pozostałych, tzn. jeśli w innych parametrach/opcjach są jakiekolwiek braki, nasza późniejsza walidacja je wychwyci i zwróci błąd.

**Comment by pliszka** [comment]
Dla potomnych - tak są ograniczenia właśnie dostałem 422 "Unprocessible entity" przesyłając pustą tablicę celem podbicia wersji TecDoc
