### ISSUE TITLE
Kategoria mająca dwóch rodziców w drzewie kategorii. Czy to zamierzone czy błąd?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4831]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Kategoria 93719 "Labirynty, przeplatanki" ma dwóch rodziców. Czy to błąd? 

Robiąc GET'a sale/categories?parent.id=320128 (trace-id: ea24207e0a2b76ba) dostaję:

{
  "categories": [
    {
      "id": "93719",
      "name": "Labirynty, przeplatanki",
      "parent": {
        "id": "320128"
      },
...

A robiąc GET'a sale/categories?parent.id=19423 (trace-id: ed63c103d82592a8) dostaję:

{
  "categories": [
    {
      "id": "93719",
      "name": "Labirynty, przeplatanki",
      "parent": {
        "id": "19423"
      },

Pozdrawiam

**Comment by mbednarski** [comment]
Również proszę o odpowiedź gdyż moja aplikacja wysypuje się w trakcie pobierania kategorii z tego powodu - gdyż do kategorii 93719 można dojść więcej niż jedną ścieżką

**Comment by Lukasz-Zurek** [comment]
@tomylee0 @mbednarski Problem ten zgłosiłem dalej do weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 @mbednarski Poprawiliśmy już. Przepraszamy za te utrudnienia.
