### ISSUE TITLE
listing variant product issue

### ISSUE THREAD

**Issue by abhishekkumar20cedommerce** [allegro/allegro-api#4833]
I am creating a variant product by using " POST /sale/offer-variants ", and trying to list variant offers in   categories id 1494
by using color paramter of categories but I get error (Given parameter id `451:Color` should no have been passed as `offer` parameter.) , please provide solution.
[request_and_response_data.txt](https://github.com/allegro/allegro-api/files/6990685/request_and_response_data.txt)

**Comment by AureliuszBrussy** [comment]
Please send the **trace-id** we returned in the header of the response. This will allow me to verify the problem.

**Comment by abhishekkumar20cedommerce** [comment]
Hi, @AureliuszBrussy  issue has been sorted now. product has combined. 
one more question,
I want to know that if the product has 4 different color variants, after created a variant set, then color name would not be display at allegro site. 
As you can see in the attached Screenshot color name is not displayed.
![Screenshot_2021-08-16_14-31-42](https://user-images.githubusercontent.com/79986688/129539902-9d662283-d22e-4e36-bc61-947d34859fd7.png)

**Comment by AureliuszBrussy** [comment]
"ColorPatern" variants have been designed to be used for products with a different color scheme, so different colors should be visible on the thumbnail (first offer picture).

**Comment by abhishekkumar20cedommerce** [comment]
ok thanks
