### ISSUE TITLE
brak external id przy ofercie dodanej poprzez formularz w panelu

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#4838]
Czy coś się zmieniło ostatnio?

Oferta dodana poprzez formularz w panelu allegro. 
Jest podany "kod producenta" (który powinien zapisać się jako external->id) ale gdy pobieram dane o ofertach:

`$url = "https://api.allegro.pl/sale/offers?publication.status=ACTIVE&limit=200";
$make_call = callAllegroAPI("GET", $url, $data, $token);
$response = json_decode($make_call, true);

$oferty = json_decode($make_call);`

to przy tej ofercie jest: 
   [external] => 

przy pozostałych ofertach - dodanych wcześniej - external.id jest widoczny normalnie 👍 
 [external] => Array
                        (
                            [id] => 0000
                        )

**Comment by AureliuszBrussy** [comment]
Parametr "Kod producenta" w formularzu wystawiania to nie **external.id**. Powinieneś uzupełnić pole "Sygnatura":

<img width="970" alt="sygnatura" src="https://user-images.githubusercontent.com/68948612/129694606-5298d45f-ad65-48fc-9354-257707f72dc5.PNG">

**Comment by ButcherFromHell** [comment]
Słusznie - dziękuje! 
Problem rozwiązany.
