### ISSUE TITLE
Rozszerzenie PWR o Orlen i automaty - określenie typu wysyłki

### ISSUE THREAD

**Issue by Elterian** [allegro/allegro-api#4839]
Witam,

Czy przy pobieraniu zamówienia z wysyłką na Orlen, czy też do automatu, będzie wiadomo jaki to jest konkretnie typ punktu (kiosk, automat czy stacja paliw)? Jest to istotne przy wyborze rozmiaru paczki, także taka informacją była by przydatna - w formie skrótowej oczywiście, a nie opisowej "Rodzaj Punktu/Automatu (automat - APM, stacja Orlen – PKN"

W poniższym linku znalazłem tylko informację o ilości o obsłudze punktów, ale nic na temat szczegółów wysyłki. Proszę o informacje jak to będzie wyglądać.

[](https://allegro.pl/pomoc/aktualnosci/zmiany-dla-sprzedajacych-1-i-6-wrzesnia-oraz-25-pazdziernika-2YG27bLGLtB?utm_source=coma_email&utm_medium=07355e8e-2ae0-4f63-839c-11fb5e8c9ad0#zmienimy-nazwy-metod-paczka-w-ruchu)

**fragment getOrder** w którym powinna znaleźć się taka informacja
"method": 
{
    "id": "1fa56f79-4b6a-4821-a6f2-ca9c16d5c925",
    "name": "Allegro Paczkomaty InPost"
},
"pickupPoint": 
{
    "id": "POZ08A",
    "name": "Paczkomat POZ08A",
    "description": "Stacja paliw BP",
    .
   .
   .
}

**Comment by AureliuszBrussy** [comment]
Gdy sprzedający udostępni metodę dostawy Punkty Poczta, Żabka, Orlen, Ruch (bo zakładam, że o nią chodzi), podczas finalizacji zakupu rozbijamy poszczególne punkty dostawy:
<img width="230" alt="punkt" src="https://user-images.githubusercontent.com/68948612/129724455-dba1f9a2-b24f-46e2-94b8-ec3db67ce0a8.PNG">

Informację, jaki konkretnie to punkt dla [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) zwracamy opisowo w polu **pickupPoint.name**, np:
```
...
"pickupPoint": {
                    "id": "757653",
                    "name": "Smartbox - automat w Biedronce",
                    "description": null,
                    "address": {
                        "street": "Dolna Wilda 104/106",
                        "zipCode": "61-492",
                        "city": "Poznań"
                    }
...
```
```
...
"pickupPoint": {
                    "id": "780722",
                    "name": "Sklep Żabka",
                    "description": null,
                    "address": {
                        "street": "Kolejowa 85",
                        "zipCode": "62-064",
                        "city": "Plewiska"
                    }
...
```

Sugestie dotyczące np. dodania kolejnego pola zgłaszać możesz w [zakładce Discussions](https://github.com/allegro/allegro-api/discussions). Inni użytkownicy naszego API będą mogli głosować na taką sugestię, a przy popularnej potrzebie istnieje prawdopodobnieństwo, że dana sugestia zostanie wdrożona.

**Comment by Elterian** [comment]
Pan wybaczy niedoprecyzowanie - chodziło mi o "zwykłą" Paczkę w Ruchu. A pojawiło się w związku z poniższą informacją:

[](https://allegro.pl/pomoc/aktualnosci/zmiany-dla-sprzedajacych-1-i-6-wrzesnia-oraz-25-pazdziernika-2YG27bLGLtB?utm_source=coma_email&utm_medium=07355e8e-2ae0-4f63-839c-11fb5e8c9ad0#zmienimy-nazwy-metod-paczka-w-ruchu)

Czy to tylko zmiana kosmetyczna w nazwie i forma PWR nie będzie obejmować nowych punktów?

**Comment by AureliuszBrussy** [comment]
Już rozumiem, chodzi o nadciągające zmiany w Paczce w RUCHu - zmianę na ORLEN Paczka. Ustalam, czy będziemy zwracać w nazwie typ punktu, tak jak to robimy w przypadku Punktów Poczty. Wrócę do Ciebie gdy tylko uda mi się uzyskać odpowiedź.
