### ISSUE TITLE
Get offer URL from offer Id

### ISSUE THREAD

**Issue by EdLSa** [allegro/allegro-api#484]
Hi,

is there a way how to convert offer Id (e.g. 7480695328) to URL to web frontend (e.g. https://allegro.pl/mercedes-c-klasa-w202-mata-bagaznika-oryginal-i7480695328.html)?

Thanks,
Ed

**Comment by TomekKaczmarek** [comment]
Hi,

We do not have such endpoint in public API. However, you may try to convert offer title by yourself:
https://allegro.pl/{offert-title}-i{offer-ID}.html

**Comment by EdLSa** [comment]
Thank you. I'm closing this issue (unless you want to keep it in the backlog for implementing such endpoint)

Ed
