### ISSUE TITLE
Jakim zasobem mogę uzyskać informację o etykiecie "SUPER CENA" dla wybranej oferty?

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#4840]
Myślałem, że zasobem `GET /sale/bages`, ale dane są tam niespójne (albo źle je interpretuję)

dzięki za pomoc

**Comment by AureliuszBrussy** [comment]
Oferty z etykietą "SUPER CENA" można wyfiltrować tylko korzystając z [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Jest możliwość filtrowania wyników po [odpowiednim filtrze](https://developer.allegro.pl/listing/#kampanie). Nie zwracamy tego oznaczenia w GET /sale/bages - do "SUPER CENA" nie można zgłosić oferty. Oznaczenie to otrzymują oferty z najniższą ceną produktu na Allegro.
