### ISSUE TITLE
Kraj PF2

### ISSUE THREAD

**Issue by artikpl** [allegro/allegro-api#4841]
Zapytanie GET https://api.allegro.pl/order/checkout-forms/b93e79c1-234f-11eb-b5e1-d530d5e7d27c 
zwraca w węźle delivery->address->countryCode wartość PF2 i dostawa do Bydgoszczy.
Co oznacza ten kod i skąd się wziął?

**Comment by AureliuszBrussy** [comment]
Wartość "PF2" to kod Polinezji Francuskiej. Taki kraj dostawy został wybrany przez kupującego (prawdopodobnie omyłkowo) w momencie finalizowania zakupu w formularzu dostawy. Dlatego zwróciliśmy go w zamówieniu.
