### ISSUE TITLE
Wysyłka obrazka do API

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#4845]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam.

Podczas załączania obrazków u jednego z klientów, zauważyliśmy liczne problemy z błędem **curl error 55 ssl_write() returned syscall errno = 32**. Wklejam poniższe wywołanie jakie wysyłamy (z wyciętym Bearerem i Base64): 
POST /sale/images HTTP/1.1 Content-Type: image/jpeg Accept: application/vnd.allegro.public.v1+json Host: upload.allegro.pl Authorization: Bearer XXX Content-Length: 199479 (tutaj treść Base64).
Niestety nie da się z tego zapytania wydobyć trace-id oraz nie ma response, jedynie opisany błąd.
Wyjątek występuje raz na kilka wywołań, w większości requesty przechodzą. Mogę załączyć całość przez formularz kontaktowy, proszę o informację.
Operacje wykonują się na koncie, które posiada ID 101412875.

**Comment by hahyes** [comment]
Opis błędu wskazuje na to, że połączenie zostało zamknięte. Nie jest to bug związany z Allegro, tylko z połączeniem gdzieś po stronie klienta czy serwera.

**Comment by AureliuszBrussy** [comment]
Nie jest to błąd zwrócony przez API Allegro. Tak jak wspomniał @hahyes - problem leży po stronie klienta lub serwera.

**Comment by bacok** [comment]
W porządku, dziękuję za szybką i sprawną odpowiedź. Pozdrawiam.
