### ISSUE TITLE
Adresy IP

### ISSUE THREAD

**Issue by matihepi** [allegro/allegro-api#4847]
Czy są jakieś ograniczenia IP dla API allegro? czy API blokuje jakieś adresy?

**Comment by AureliuszBrussy** [comment]
Tak, może pojawić się chwilowa blokada konkretnego IP przy przekraczaniu limitów, spójrz np. na [ten wątek](https://github.com/allegro/allegro-api/issues/3454).

**Comment by matihepi** [comment]
Dziękuję za informację.

Ale nie ma jako takiej blokady IP przy korzystaniu z API Allegro w innych
Państwach niż Polska? Mam tutaj na myśli rosyjski adres IP.

czw., 19 sie 2021 o 07:19 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
Nie, nie ma takiej blokady IP z innych Państw.

**Comment by matihepi** [comment]
Dziękuję za pomoc.

czw., 19 sie 2021 o 07:53 AureliuszBrussy ***@***.***>
napisał(a):
