### ISSUE TITLE
Pytanie dotyczące token_creation_rate_limit_exceeded

### ISSUE THREAD

**Issue by mrsuchy** [allegro/allegro-api#4849]
Dzień dobry,

Napisałem w PHP moduł do importowania aukcji. Podczas importu kilku aukcji nie ma problemu ale jak zaznaczę więcej to mam komunikat token_creation_rate_limit_exceeded. Proszę o wyjaśnienie tego komunikatu. Znalazłem inny wątek ale w nim rozwiązaniem było odświeżenie tokena. W moim przypadku próby odświeżenie także mam ten sam komunikat.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
W Allegro REST API obowiązuje limit dla liczby access tokenów, które możesz wygenerować w określonym czasie dla jednego użytkownika. Jeżeli go przekroczysz, w odpowiedzi zwrócimy błąd HTTP: 429 Too Many Requests. Oznacza to, że działanie twojej aplikacji odbiega od normy - upewnij się, że nie tworzysz więcej tokenów niż wymagają tego operacje, które wykonujesz. Raz wygenerowany token dla jednego użytkownika powinien być używany aż do momentu wygaśnięcia (przez 12 godzin), po tym czasie odśwież token za pomocą refresh tokena. Przekroczony limit będzie się zmniejszał wraz z liczbą wygaśniętych access tokenów.

**Comment by mrsuchy** [comment]
Proszę o informację z czego może wynikać taki błąd

`Failed to create token for client [XXXXXX] and user [XXXXXXX]`

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Proszę o przesłanie trace-id, który wysłaliśmy w nagłówku response'a. Na tej podstawie postaram się to wyjaśnić.

**Comment by mrsuchy** [comment]
Wkleić tutaj w wiadomości?
Jeszcze się wstrzymam. Z tego co widzę to mój moduł działa na kilku serwerach bez problemu a tylko na jednym mam ten problem tj. Failed to create token for client bądź token_creation_rate_limit_exceeded. Wszystkie łączą się z tym samym kontem Allegro. Zweryfikuje jeszcze dwie rzeczy i wrócę z odpowiedzią.
