### ISSUE TITLE
Jaki powiązać aukcję Allegro z towarem w systemie sprzedazowym Sprzedającego ?

### ISSUE THREAD

**Issue by WCzaj** [allegro/allegro-api#485]
Allegro WebApi udostępnia metodę doMyAccount2 (https://allegro.pl/webapi/documentation.php/show/id,107)
Parametrem wyjściowym tej metody jest tablica MyAccountArray w której zwracane są wszystkie publicznie dostępne informacje nt. ofert. Tablica ta zawiera kolumnę (nr 31 od początku) opisaną w dokumentacji jako "treść notatki dodanej przez sprzedającego do oferty (widoczna tylko dla sprzedającego, dla pozostałych oraz w przypadku braku notatki zwracane jest 0),"

Jak za pomocą Managera Sprzedaży, lub innego narzędzia umożliwiającego definiowanie oferty, wpisać wartość do tego pola ?
Chciałbym tam umieścić SYMBOL TOWARU  w programie sprzedażowym SPRZEDAWCY, aby automatycznie powiązać opis w ofercie Allegro z kartoteką towaru w ERP klienta.

Jestem programistą, ale nie znam kuchni Allegro, więc proszę o pomoc lub ukierunkowanie...
Z góry dziękuję

**Comment by TomekKaczmarek** [comment]
Dzień dobry

Przez WebAPI nie da się dodać tego pola. Ogólnie wygaszamy opcję, by sprzedawca mógł dodać taką notatkę do oferty. Przypominam też, że [zapowiedzieliśmy wygaszenie metod do wystawiania i zarządzania oferty w WebAPI](https://github.com/allegro/allegro-api/issues/277).

Zalecam, by skorzystać z [REST API](https://developer.allegro.pl/sale/) - tam w modelu oferty można wykorzystać pole external by dodać Symbol towaru.

**Comment by kfijalko** [comment]
@TomekKaczmarek tylko prosze uczulić "wielkiego elektronika" (mam na myśli architekta, projektanta, który jest odpowiedzialny za spójność interfejsu) żeby we wszystkich serwisach zwracających dane dla zalogowanego użytkownika i zawierających dane ofert był zawarty external.id.
W wątku #474 jest pytanie o external i o ean, tam piszecie, że rozważacie tylko ean.

**Comment by TomekKaczmarek** [comment]
@kfijalko Wielki elektronik uczulony. Rozmawiałem już wcześniej na ten temat i zobaczymy co da się zrobić, by np w zasobach o zamówieniach dodać pole EAN i external przy sekcji o ofertach. Damy znać, jeśli wprowadzimy taką zmianę.

**Comment by jakubmaguza** [comment]
@TomekKaczmarek 
Minął kolejny miesiąc, a pola external dalej nie widać. Nie wiem jak jest zbudowany wasz system, ale dodanie jednego pola nie powinno być problemem. Prosicie nas o sugestie, a następnie te sugestie całkowicie olewacie. Nie chcę robić wam wyrzutów, tylko czuję, że piszecie jedno, a robicie drugie. Proste pytanie: Czy dodanie tego pola jest aż tak skomplikowane, czy musi dostać akceptację prezydenta allegro, wielkiego elektronika, czy jak kto tam nazywa ten byt.
