### ISSUE TITLE
Wprowadzenie do draftu oferty wartości ze zmiennych

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4850]
Witam, 
chciałam się dowiedzieć czy jest możliwe wprowadzenie do szkicu wartości zmiennych pochodzących z bazy danych ? Gdyż podczas wysyłania otrzymuję taki błąd:

{"errors":[{"code":"ValidationError.HttpMessageNotReadableException","message":"Message not readable","details":null,"path":null,"userMessage":"Message not readable"}]}

Wiem. że szkic jest poprawny, ponieważ sprawdzałam go poprzez Postman z tym że po wprowadzeniu do PHP i dodaniu zmiennych pojawia się powyższy problem. 
W samym szkicu zmieniłam apostrofy na cudzysłowy by móc wprowadzić zmienne.

public function draftProduct()
    {
        // $allegroProductTitle = OfferGenerator::productTitle();
        $allegroProductParameters = MysqlProducts::getParametersProducts();

        // print_r($allegroProductParameters);

        foreach($allegroProductParameters as $productParameters)
        {
            $productTitle = $productParameters['title'];
            $productSku = $productParameters['sku'];
            $productPrice = $productParameters['price'];
            $productDescr = $productParameters['descr'];
            
            // print_r($productParameters['title']);
            // foreach($productParameters as $product)
            // {
            //     print_r($product);
            // }
        

            $draftOffer =  "{
                'name': $productTitle,
                'product': {        
                'parameters': [
                    {
                        'name': 'EAN',
                        'values': [
                            $productSku
                        ]
                    },
                    {
                        'id': '11323',
                        'valuesIds': [
                            '11323_1'
                        ]
                    }
                ],
                'sellingMode': {
                    'price': {
                        'amount': $productPrice,
                        'currency': 'PLN'
                    }
                },
                'stock': {
                    'available':1
                },
                'publication': {
                    'duration': null,
                    'status': 'ACTIVE',
                    'startingAt': null,
                    'endingAt': null,
                    'endedBy': null,
                    'republish': false
                },
                'delivery': {
                    'shippingRates': {
                        'id': '005febe7-bfa5-4759-9e18-bc562881f05c'
                    },
                    'handlingTime': 'PT72H',
                    'additionalInfo': '',
                    'shipmentDate': null
                },
                'payments': {
                    'invoice': 'NO_INVOICE'
                },
                'sizeTable': null,
                'location': {
                    'countryCode': 'PL',
                    'province': 'MAZOWIECKIE',
                    'city': 'Warszawa',
                    'postCode': '12-345'
                },
                'description': {
                    'sections': [
                        {
                            'items': [
                                {
                                    'type': 'TEXT',
                                    'content': $productDescr
                                }
                            ]
                        }
                ]}
                }
            }";

            // echo "</br>";
            // print_r($draftOffer);
            // echo "</br>";
        }

        $this->api->postNewDraftOffer($draftOffer);
    }

Dziękuję za wszelką pomoc, pozdrawiam.
Kasia

**Comment by AureliuszBrussy** [comment]
Oczywiście, jest to możliwe, natomiast powinnaś się upewnić, czy struktura jsona oraz przesłane typy w parametrach są zgodne z tymi, które oczekujemy. Upewnij się, czy na pewno zamieniasz znaki **'** na **"**. Upewnij się również, że przekazane zmienne np. $productTitle to stringi, czy wartość $productPrice jest w odpowiednim formacie itd. Przekaż proszę jeszcze trace-id, które wysłaliśmy w nagłówku odpowiedzi - spróbuję ustalić, co przesłałaś niepoprawnie.

**Comment by Kasia13130** [comment]
Dobrze, gdzie znajdę trace-id ? Gdyż po próbie przesłania szkicu otrzymałam tylko ten komunikat o błędzie.

**Comment by AureliuszBrussy** [comment]
Trace-id znajdziesz w nagłówku "trace-id" naszego response'a z błędem.

**Comment by Kasia13130** [comment]
Nie widzę tutaj trace-id, a przekopiowałam z Postman. Jak wcześniej przesyłałam szkic oferty ale z konkretnymi wartościami, nie używając zmiennych to szkic pojawiał się na allegro sandbox. Chyba że muszą być dodatkowe nagłówki tak jak tutaj w poradniku https://developer.allegro.pl/about/ ?
$curl = curl_init();

        curl_setopt_array($curl, array(
        CURLOPT_URL => 'https://api.allegro.pl.allegrosandbox.pl/sale/offers',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => $draft,
        CURLOPT_HTTPHEADER => array(
            'Accept: application/vnd.allegro.public.v1+json',
            'Content-Type: application/vnd.allegro.public.v1+json',
            'Authorization: Bearer'
        ),
        ));

        $response = curl_exec($curl);

        curl_close($curl);

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniałem, trace-id na pewno znajduje się w headerze odpowiedzi z errorem "ValidationError.HttpMessageNotReadableException". Powinnaś wydobyć ten nagłówek z naszego response'a. 

W swoim requeście powinnaś oczywiście skorzystać z nagłówków:
```
        'Accept: application/vnd.allegro.public.v1+json',
        'Content-Type: application/vnd.allegro.public.v1+json'
```
tak jak przy większości udostępnianych przez nas endpointów. 

Tak jak wspomniałem, w Twoim requeście problemem mogą być znaki ' (apostrofy). W jsonie korzystaj z " (cudzysłów). Wklej tu proszę wynik funkcji print_r($draftOffer). Być może lepszym pomysłem także będzie skorzystanie z tablicy, a później jej enkodowanie na json (json_encode).

**Comment by hahyes** [comment]
@Kasia13130 Żeby otrzymać Trace-Id, sama musisz wysłać w zapytaniu nagłówek "Trace-Id" a w jego wartości wygenerowany UUID (Postman ma gotowe funkcje do generowania UUID w nagłówkach, chyba się pisze {uuid} lub coś podobnego). Wtedy w odpowiedzi uzyskasz inny kod w nagłówku "Trace-Id", który to masz podać tutaj w wątku.

**Comment by Kasia13130** [comment]
Poniżej wynik funkcji printf_r
<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">{ 'name': Rzęsy i akcesoria Natural 107 1 para sztucznych rzęs Black, 'product': { 'parameters': [ { 'name': 'EAN', 'values': [ xxxxxx ] }, { 'id': '11323', 'valuesIds': [ '11323_1' ] } ], 'sellingMode': { 'price': { 'amount': 15.05, 'currency': 'PLN' } }, 'stock': { 'available':1 }, 'publication': { 'duration': null, 'status': 'ACTIVE', 'startingAt': null, 'endingAt': null, 'endedBy': null, 'republish': false }, 'delivery': { 'shippingRates': { 'id': '005febe7-bfa5-4759-9e18-bc562881f05c' }, 'handlingTime': 'PT72H', 'additionalInfo': '', 'shipmentDate': null }, 'payments': { 'invoice': 'NO_INVOICE' }, 'sizeTable': null, 'location': { 'countryCode': 'PL', 'province': 'MAZOWIECKIE', 'city': 'Warszawa', 'postCode': '12-345' }, 'description': { 'sections': [ { 'items': [ { 'type': 'TEXT', 'content':</span><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Profesjonalne sztuczne rzęsy Natural zostały wykonane z naturalnego, ludzkiego włosia, które zostało poddane sterylizacji. Zostały umieszczone na bezbarwnym, elastycznym pasku, który po nałożeniu na powiekę staje się niewidoczny. Sztuczne rzęsy są długie i gęste - doskonale podkreślą spojrzenie.</p>

Gramatura | sztuka
-- | --
Kolor | black
Pojemność | 1
Słońce | nie

<span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">} ] } ]} } }</span>
</body>
</html>

Jak tylko uda mi się otrzymać Trace-Id to tutaj podam, gdyż aktualnie próbuję rozwiązać problem z tokenem.

**Comment by hahyes** [comment]
> Poniżej wynik funkcji printf_r
> 
> { 'name': Rzęsy i akcesoria Natural 107 1 para sztucznych rzęs Black, 'product': { 'parameters': [ { 'name': 'EAN', 'values': [ xxxxxx ] }, { 'id': '11323', 'valuesIds': [ '11323_1' ] } ], 'sellingMode': { 'price': { 'amount': 15.05, 'currency': 'PLN' } }, 'stock': { 'available':1 }, 'publication': { 'duration': null, 'status': 'ACTIVE', 'startingAt': null, 'endingAt': null, 'endedBy': null, 'republish': false }, 'delivery': { 'shippingRates': { 'id': '005febe7-bfa5-4759-9e18-bc562881f05c' }, 'handlingTime': 'PT72H', 'additionalInfo': '', 'shipmentDate': null }, 'payments': { 'invoice': 'NO_INVOICE' }, 'sizeTable': null, 'location': { 'countryCode': 'PL', 'province': 'MAZOWIECKIE', 'city': 'Warszawa', 'postCode': '12-345' }, 'description': { 'sections': [ { 'items': [ { 'type': 'TEXT', 'content':
> Profesjonalne sztuczne rzęsy Natural zostały wykonane z naturalnego, ludzkiego włosia, które zostało poddane sterylizacji. Zostały umieszczone na bezbarwnym, elastycznym pasku, który po nałożeniu na powiekę staje się niewidoczny. Sztuczne rzęsy są długie i gęste - doskonale podkreślą spojrzenie.
> 
> Gramatura	sztuka
> Kolor	black
> Pojemność	1
> Słońce	nie
> } ] } ]} } }
> 
> Jak tylko uda mi się otrzymać Trace-Id to tutaj podam, gdyż aktualnie próbuję rozwiązać problem z tokenem.

1. Cudzysłów zamiast apostrofów.
2. Nie widać tego w poście, ale czy treść opisu jest w HTMLu? Ponadto nie widzę ani apostrofów, ani cudzysłowów tam. Treść opisu musi być w HTMLu.

**Comment by Kasia13130** [comment]
Ad. 1 -> cudzysłowem mam objęty cały $draftOffer natomiast poszczególne dane mam w apostrofie (jak próbowałam zmienić wszystkie apostrofy na cudzysłów to miałam błędy w kodzie), spróbuję jeszcze raz zmienić na cudzysłów wszystko.
Ad. 2 -> Tak, treść jest w HTMLu. Po utworzeniu komentarza prawdopodobnie znaczniki zostały ukryte.

**Comment by AureliuszBrussy** [comment]
@Kasia13130 tak jak wspomniał @hahyes - w strukturze jsona musisz korzystać z cudzysłowów, a nie apostrofów, stąd moja rada dot. skorzystania w php z tablicy i późniejszego kodowania jej na json.

**Comment by hahyes** [comment]
@Kasia13130 Tak powinien wyglądać poprawny JSON. Polecam sprawdzić swój JSON przed wysłaniem za pomocą takiego narzędzia jak https://jsonformatter.curiousconcept.com/ . Dopóki w nim walidacja nie przejdzie, nie przejdzie też na Allegro.

```
{
  "additionalServices": {
    "id": "string"
  },
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "returnPolicy": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    },
    "warranty": {
      "id": "09f0b4cc-7880-11e9-8f9e-2a86e4085a59"
    }
  },
  "attachments": [
    {
      "id": "1928302_MANUAL_45d7a0f543e1b0d05e12a1aef5642efe63389a1d419fe9286d0f158044391fdce"
    }
  ],
  "category": {
    "id": "257931"
  },
  "compatibilityList": {
    "type": "MANUAL"
  },
  "contact": {
    "id": "string"
  },
  "createdAt": "2021-08-23T09:13:52Z",
  "customParameters": [
    {
      "name": "string",
      "values": [
        "string"
      ]
    }
  ],
  "delivery": {
    "additionalInfo": "string",
    "handlingTime": "PT24H",
    "shippingRates": {
      "id": "string"
    },
    "shipmentDate": "2018-04-01T08:00:00Z"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "string"
          }
        ]
      }
    ]
  },
  "discounts": {
    "wholesalePriceList": {
      "id": "string"
    }
  },
  "external": {
    "id": "AH-129834"
  },
  "fundraisingCampaign": {
    "id": "string"
  },
  "id": "string",
  "images": [
    {
      "url": "string"
    }
  ],
  "location": {
    "city": "string",
    "countryCode": "string",
    "postCode": "string",
    "province": "string"
  },
  "name": "string",
  "parameters": [
    {
      "id": "string",
      "rangeValue": {
        "from": "string",
        "to": "string"
      },
      "values": [
        "string"
      ],
      "valuesIds": [
        "string"
      ]
    }
  ],
  "payments": {
    "invoice": "string"
  },
  "product": {
    "id": "string"
  },
  "promotion": {
    "bold": true,
    "departmentPage": true,
    "emphasized": true,
    "emphasizedHighlightBoldPackage": true,
    "highlight": true
  },
  "publication": {
    "duration": "PT24H",
    "endingAt": "2031-01-04T11:01:59Z",
    "startingAt": "2031-01-04T11:01:59Z",
    "status": "INACTIVE",
    "endedBy": "USER",
    "republish": false
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "minimalPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "startingPrice": {
      "amount": "123.45",
      "currency": "PLN"
    },
    "netPrice": {
      "amount": "123.45",
      "currency": "PLN"
    }
  },
  "tax": {
    "id": "ae727432-8b72-4bfe-b732-6f163a2bf32a",
    "rate": "23.00",
    "subject": "GOODS",
    "exemption": "MONEY_EQUIVALENT",
    "percentage": "23.00"
  },
  "sizeTable": {
    "id": "string"
  },
  "stock": {
    "available": 0,
    "unit": "string"
  },
  "tecdocSpecification": {
    "id": "470b8513-b786-b7b9-9e7e-2f848729cfd6",
    "items": [
      {
        "name": "Wersja TecDoc",
        "values": [
          "0319"
        ]
      }
    ]
  },
  "updatedAt": "2021-08-23T09:13:52Z",
  "validation": {
    "errors": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "warnings": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "validatedAt": "2021-08-23T09:13:52Z"
  }
}
```

**Comment by Kasia13130** [comment]
Dobrze, dziękuję. Wprowadzę zmiany

**Comment by Kasia13130** [comment]
Wprowadziłam zmiany, sprawdziłam na jesonformatter i jest dobrze. Muszę jeszcze parę drobniejszych zmian wprowadzić w wartościach draftu oferty. Ale chyba sobie z tym poradzę.
Trace-Id: f490705c45b402e1
Dziękuję za pomoc

**Comment by AureliuszBrussy** [comment]
@Kasia13130 trace-id które podałaś dotyczy requesta metodą GET na zasobie /sale/offers, nie POST. Tak czy inaczej rozumiem jednak, że zgłoszenie możemy uznać za wyjaśnione?

**Comment by Kasia13130** [comment]
Tak, dziękuję.
