### ISSUE TITLE
REST API: Parametr product w metodzie  POST /sale/offers

### ISSUE THREAD

**Issue by burnburnburn123** [allegro/allegro-api#4851]
kiedyś zbudowałem narzędzie to wystawiania ofert metodą /sale/offers  (tzn wystawiam draft i aktywuję)

Obecnie to nie wystarcza bo pojawił się wymóg aby 50% ofert(ksiązki) było powiązanych z produktami z katalogu allegro.

W związku z tym mam 2 pytania.
1. Do czego w metodzie /sale/offers służy parametr "product"   oraz co podstawić pod jego ID?
Pytam ponieważ:
a. dotychczas nie używałem tego parametru i wystawianie działało dobrze (pomijając blokadę gdy zbyt mało ofert jest powiązanych z katalogiem)
b. gdy dodałem ten parametr - np. tak to wygląda w jsonie
"product": {
		"id": "9788380088535"
	}
to otrzymuję **komunikat błedu (dlaczego?):**   Obsługa allegro zapewniało mnie ze tu wolno podawać EAN.
[code] => VALIDATION_ERROR
                    [message] => The field contains invalid value.
                    [details] => ConstraintViolationException.Uuid
                    [path] => product.pmd
                    [userMessage] => The field contains invalid value.

c. Czy uzupełniając ten parametr można sprawić ze automatycznie oferta będzie powiązania z produktem w allegro?
2. najważniejsze pytanie.  Mam działający mechanizm wystawiania draftu i aktywacji oferty. Czy jest jakiś prosty sposób aby dla takiego draftu powiązać go poprzez API z katalogiem produktów?  Wszystkie oferty mają EAN(isbn). Jak to najprościej rozwiązać aby oferty się wiązały z katalogiem produktów?

**Comment by AureliuszBrussy** [comment]
Pole **product.id** służy właśnie do wiązania oferty z produktem. Produkty, wraz z ich id wyszukasz za pomocą [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Szczegóły danego produktu pobierz za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct). Zachęcam Ciebie do zapoznania się z całym [poradnikiem](https://developer.allegro.pl/productization/) dotyczącym wiązania ofert z produktem. Pamiętaj, że parametry w ofercie muszą być zgodne z tymi, które znajdują się w produkcie - tylko tak uda się powiązać ofertę z produktem.  

Możesz użyć także [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) aby w łatwy sposób powiązać ofertę z produktem. Wystarczy, że w polu product.id wskażesz identyfikator danego produktu lub parametr GTIN (EAN, ISBN, ISSN). Więcej o tym przeczytasz w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-przypisa%c4%87-produkt-do-oferty).

**Comment by burnburnburn123** [comment]
Dzięki.
Jeszcze 2 pytania:
- Czy jesteś pewien że podanie EAN  w polu product.id    będzie poprawne?   niepokoi mnie komunikat o błędzie :
[message] => The field contains invalid value.
[details] => ConstraintViolationException.Uuid
Może bład wynika właśnie z faktu że jakiś mój parametr różni sie od tego w katalogu allegro?

- co się dzieje gdy jakiś z moich parametrów będzie inny niż w katalogu produktów z allegro?   Da się ustawić aby w takim przypadku allegro nadpisało moje wartości danymi , co by skutkowało aktualizacją oferty i powiązaniem z produktem?

Wracam do czytania wskazanej dokumentacji, ale bedę wdzięczny za odpowiedz na te 2 pytania.

**Comment by burnburnburn123** [comment]
Jednak jeszcze trzecie pytanie, wszędzie gdzie widzę informację "The product identifier."   chodzi o dowolny identyfikator, czyli może być EAN?  czy chodzi o identyfikator nadany przez allegro, czyli w przypadku tego screena np.   c9e39cae-9cb6-11e9-a2a3-2a2ae2dbcce4   ?

![image](https://user-images.githubusercontent.com/31242001/130073132-26c2b19f-31fc-4beb-af77-a14a81ab9ab1.png)

**Comment by AureliuszBrussy** [comment]
W przypadku zasóbu **/sale/offers** - nie możesz podać EAN produktu w product.id. Musi to być id produktu z naszego Katalogu Produktów. Id produktów znajdziesz dzięki [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). 

W przypadku **/sale/offers** nie nadpiszemy parametrów - samodzielnie musisz zaimplementować funkcje, która "przekopiuje" dane produkt do oferty.

Z kolei w przypadku zasobu **/sale/product-offers** i metody PATCH - w polu product.id możesz także korzystać z EAN. Na tym zasobie automatycznie nadpiszemy parametry.

**Comment by burnburnburn123** [comment]
Dziękuję - bardzo mi pomogły Twoje informacje.
Za pomocą PATCH   dodaję produkt do oferty na podstawie EANU.

Napisz proszę co w przypadkach gdy w allegro nie ma produktu odpowiadającego EANowi jaki wystawiałem(mam szkic) w kategorii książki.   Jak sobie z tym poradzić w przypadku limitów na oferty niepowiązane?

**Comment by AureliuszBrussy** [comment]
Jeżeli nie znalazłeś produktu, który odpowiada danej ofercie - możesz go utworzyć samodzielnie. Masz dwie możliwości:
- za pomocą [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) dodaj propozycję produktu - w odpowiedzi zwrócimy identyfikator tego produktu, który potem możesz wykorzystać do podpięcia produktu. Więcej o tym w [tej części poradnika](https://developer.allegro.pl/productization/#5-jak-doda%c4%87-produkt).
- za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) wystawisz nową ofertę, na podstawie której utworzymy produkt. Więcej o tym w [tej części poradnika](https://developer.allegro.pl/product_offers/#jak-wystawi%C4%87-ofert%C4%99-z-produktem-kt%C3%B3rego-nie-ma-w-naszej-bazie).

**Comment by burnburnburn123** [comment]
Dzięki.

Natrafiłem na następujące komplikacje w związku ze stosowaniem  PATCH
/sale/product-offers/{offerId}   [do wcześniej utworzonej aktywnej oferty
lub draftu]
- Czasami po zastosowaniu PATCH allegro zmienia mi kategorię z tej na którą
ja ustawiłem na "Pozostałe", co mi nie odpowiada, bo w "pozostałe" prowizja
wynosi aż 15%. Jak uniemożliwić taką zmianę? Nie przeszkadza mi zmiana
kategorii na lepiej dopasowaną. Przeszkadza mi jedynie zmianą na tą
kategorię.
- także zauważyłem że w niektórych moich ofertach Patch wykasowuje mi
jakieś dane z oferty (np. rok wydania), a następnie z tego powodu oferty
nie da się aktywować bo rok wydania był wymagany do aktywacji. Chyba nie
powinno się tak dziać? Jesli już produktyzacja nie posiada roku wydania to
nie powinna kasować moich wprowadzonych danych
- najmniejszy problem: czasem  w produktyzacji allegro jest więcej niż
jeden produkt dla danego EANu i wtedy otrzymuję response: "More then one
product matches given ean.". Sądziłem że w przypadku ksiązek jeden
Ean=jedna unikalna ksiązka(bez wyjątku). Domyślam się że może chodzić o
drobne różnice jak przypisana kategoria w tych ofertach czy coś podobnego.
Czy jest jakiś prosty sposób aby to ogarnąć bez wywoływania metody
pobierającej wszystkie produktyzacje dla danego EANU, analizowania danych i
następnie wybrania jednej z nich? Np. wskazanie aby w takim przypadku
przypisywała pierwszy z produktów pasujący do EANu(bo nie wierzę ze dla
pasującego EANu mogą być większe różnice w parametrach ksiązki)

pt., 20 sie 2021 o 07:25 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
1. Sprawdź, czy dany produkt ma inną, interesującą Cię kategorię w tablicy category.similar ([GET ​/sale​/products​/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)). Jeżeli tak, to możesz również wskazać jedną z tych kategorii podobnych w swoim requeście PATCH /sale/product-offers/{offerId} w polu category.id. 
Sprawdź też, czy na pewno produkt, który chciałbyś wykorzystać nie istnieje w innej kategorii ([GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts)).

2. Po wskazaniu produktu w w PATCH /sale/product-offers/{offerId} podmieniamy całą tablicę parametrów. Jeżeli chcesz zachować aktualny opis, zdjęcia i parametry produktowe, oprócz product.id powinieneś przekazać również takie pola jak: description, images i product.parameters. Możesz je pobrać z edytowanej przez Ciebie oferty, korzystając z zasobu: [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). 

3. Nie, nie ma takiej możliwości. Możesz samodzielnie w przypadku takiego erroru pobierać produkty dla tego EAN ([GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts)) i wrzucić do swojego requesta id pierwszego ze zwróconej listy.

**Comment by hahyes** [comment]
@burnburnburn123 /sale/product-offers działa inaczej niż /sale/offers i dziwi mnie, że Allegro nie wyjaśnia tego w takim wątku od razu.

Dla /sale/product-offers, wystawiasz ofertę bazując na katalogu produktów. W takim oto wypadku nie możesz zmodyfikować istniejących tam już zdjęć (jedynie dodać dodatkowe), kategoria jest dodana na bazie katalogu, parametry również. Po prostu przy PATCH /sale/product-offers/{offerId} Allegro usunęło twoje dane, a załadowało dane z katalogu produktów. Teoretycznie produkt powinien zawierać wszystkie obowiązkowe parametry, jednak te się zmieniają z czasem, więc widocznie jakiegoś brakuje.

Co do samych kategorii, niektóre produkty posiadają kategorie podobne, w których też można wystawiać dany produkt. Sprawdź, czy produkt ten posiada takie kategorie (w GET /sale/products). Jeżeli nie, nic z tym nie zrobisz, bo ktoś dodał sobie produkt w taki a nie inny sposób. Jedyny sposób na zmianę kategorii to pisanie zgłoszeń do Allegro o poprawienie produktów. Nie dodasz podobnego produktu, ponieważ /sale/product-proporsals z automatu wyrzuci ci, że taki produkt istnieje.

Jeżeli chcesz zachować częściową zgodność z produktyzacją, mógłbyś część aukcji przypisywać do produktów z poziomu /sale/offers przez podawanie product.id. Jednak oczywiście taka oferta będzie krzyczeć o niewłaściwych parametrach, kategorii itd. Niestety sytuacja z produktyzacją jest okropna, katalog został zaśmiecony, a Allegro wymaga.

Osobiście każdemu współczuję z tym, bo to okropne doświadczenie.
