### ISSUE TITLE
Product activation

### ISSUE THREAD

**Issue by Liketodev3** [allegro/allegro-api#4852]
Hi. This is product activation json. What goes wrong that it doesn't activate?
Sample request

{
"publication": {
        "action": "ACTIVATE"
    },
    "offerCriteria": [
        {
            "offers":[  
                {
                    "id": "11059647110"
                }
            ],
            "type": "CONTAINS_OFFERS"     
        }
    ]
}

Sample response

{
    "id": "88b2f21a-ca2f-48b9-9c49-fb4f58de178d",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}

**Comment by AureliuszBrussy** [comment]
In you command (88b2f21a-ca2f-48b9-9c49-fb4f58de178d) you also used "**scheduledFor**" field, and you have provided past data ("2018-03-28T12:00:00.000Z"). You cannot schedule offer activation in the past, so the command failed.
