### ISSUE TITLE
Wysyłanie maili - Greylisted.

### ISSUE THREAD

**Issue by MILsoldier** [allegro/allegro-api#4853]
Witam

Wysyłam maile przy pomocy API Emaillabsa do allegro, lecz wszystkie wysłane wiadomości trafiają na "Recipient address rejected: Greylisted", gdzie trzeba czekać po 10-15 min, aby wiadomość doszła. Czy jest jakieś szybsze rozwiązanie w wysyłaniu wiadomości do klienta lub dodanie serwera do zaufanych przez allegro, aby allegro nie traktowało tych wiadomości jako spam? Czy spotkał się ktoś z podobnym problemem z Emaillabsem ?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Dodatkowe adresu e-mail na koncie można ustawić za pomocą [POST /account/additional-emails](https://developer.allegro.pl/documentation/#operation/addAdditionalEmailUsingPOST), albo w zakładce [Moje adresy e-mail](https://allegro.pl/moje-allegro/moje-konto/moje-adresy-email). Tylko z tych zdefiniowanych adresów powinieneś wysyłać wiadomości do Klientów. Aktualna biała lista domen znajduje się [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/kontakt-z-klientem/jak-wyswietlamy-adresy-e-mail-w-korespondencji-w-ramach-allegro-5VZxXd8vzSL#lista-domen-adresow-e-mail). Jeżeli chciałbyś zasugerować jakiś dodatkowy adres, skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
