### ISSUE TITLE
Weryfikacja najniższej ceny produktu na Allegro

### ISSUE THREAD

**Issue by strangeletstudio** [allegro/allegro-api#4854]
Cześć wszystkim!

Czy istnieje możliwość uzyskania informacji o najniższej cenie (lub wszystkich cen) dla danego produktu po kodzie EAN? Ręczna weryfikacja w serwisie odpada, bo mamy bardzo dużo produktów. 🙂

**Comment by AureliuszBrussy** [comment]
Nie, w API Allegro nie udostępniamy funkcjonalności, która pozwoliłaby śledzić najniższe ceny produktu po kodzie EAN.
