### ISSUE TITLE
Jak ustawić w RestApi miniaturę/główne zdjęcie oferty?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4855]
Witam, miałbym pytanie, ponieważ nie znalazłem tego w dokumentacji,
chciałbym w ofercie ustawić miniaturę/główne zdjęcie oferty, **nie będące na pierwszym miejscu** w liście przesyłanych zdjęć.
Czyli, dajmy na to, drugi obrazek z kolei ( na liście [images] i w opisie [description] )
Czy jest jakiś inny zasób niż /sale/offers/{offerId} który by to umożliwiał?

**Comment by AureliuszBrussy** [comment]
Powinienieś zmienić kolejność zdjęć w swoim requeście - zdjęciem głównym zawsze będzie pierwsze zdjęcie przesłane w tablicy **images**.
