### ISSUE TITLE
Błąd podczas tworzenia przesyłek w WZA

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4858]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Otrzymujemy błąd podczas tworzenia przesyłek

CommandId: e958c423-6d8a-4bc4-823f-0cad56392d3c
oraz 8765b17d-ce34-4b93-8cc0-afd8fb1921fc

Błąd:
Processing error | Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem

Jaka jest przyczyna błędu?

**Comment by AureliuszBrussy** [comment]
Zgłosiłem to do odpowiedniego zespołu - wrócę do Ciebie z odpowiedzią, gdy tylko uda się ustalić powód.

**Comment by AureliuszBrussy** [comment]
UPS dla danych autoryzacyjnych zwraca nam błąd:

`The Shipper's shipper number cannot be used for the shipment.`

Sugerujemy kontakt z UPS - być może np. konto z jakiegoś powodu zostało zawieszone.

**Comment by marmited** [comment]
Dzięki, skontaktowaliśmy się z klientem, który to zweryfikuje.
