### ISSUE TITLE
Nieprawidłowo zdefiniowana wartość z nieznanego powodu przy tworzeniu produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4859]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Witam, mam problem z dodaniem produktu do katalogu. 
Dodaje produkt do kategorii o ID: 261265. Jednym z zapisanych parametrów jest "Długość maksymalna", jako float. Z jakiegoś powodu wyrzucany jest błąd:

```
{"errors":[{"code":"ParameterException.InvalidParameterDtoException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 231977."}]}
```

Sprawdzam zapis JSONa, którego wysłałem i widzę:
```
{"id":"231977","valuesIds":[],"values":[44.5]}
```

O co chodzi? Wartość jest zapisana prawidłowo dla struktury JSONa. Nie jest to też parametr zakresowy, więc brak `rangeValue` nie powinien być problemem, jeżeli i tak byłby to null.

Trace-Id: 77822ccd96078eff

Edit: Kolejny przypadek znalazłem, kategoria 76004 i parametr 2970: e497ba9f9e114052

**Comment by PrzemyslawLukanowski** [comment]
Usuń proszę pole `"valuesIds": []` z parametrów 231977 i 2970, a produkt utworzy się prawidłowo.

**Comment by hahyes** [comment]
> Usuń proszę pole `"valuesIds": []` z parametrów 231977 i 2970, a produkty utworzą się prawidłowo.

Dziękuję, to jest to. Pozdrawiam.
