### ISSUE TITLE
REST API, lista wystawionych aukcji, status danej aukcji

### ISSUE THREAD

**Issue by jestemradek** [allegro/allegro-api#486]
Witam.

Przeprowadzam integrację z Allegro za pomocą nowego interfejsu REST API i napotkałem różne problemy.
Załóżmy, że wystawiam 100 aukcji, po pewnym czasie część z nich nadal trwa, część zakończyła się np. z powodu braków magazynowych, część przeszła do archiwum.
W między czasie magazyn uzupełnił się i potrzebuję np. sprawdzić czy draft danego produktu jeszcze istnieje.

Jak sprawdzić jakie drafty istnieją na moim koncie za pomocą REST API?
Jak sprawdzić mając numer aukcji jaki ona ma status? Np. INACTIVE, NEW, ACTIVE, END oraz "ARCHIWUM".
Brak takich metod powoduje duże kłopoty w zarządzaniu aukcjami, draftami.
Tworzę nowego robota do obsługi Allegro i mam używać po części dwóch różnych interfejsów?

Pozdrawiam
RK

**Comment by AniaMalinowska** [comment]
Jeśli znasz numer oferty, możesz sprawdzić jej stan metodą GET: https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET
Planujemy udostępnić metodę, którą będzie można pobrać swoje drafty. Gdy ją udostępnimy, oczywiście poinformujemy o tym w stosownym komunikacie.
