### ISSUE TITLE
Artykuł w dokumentacji "Jak zacząć pracę z REST API" - przeredagowanie.

### ISSUE THREAD

**Issue by kuba4400** [allegro/allegro-api#4860]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Informacje na stronie https://developer.allegro.pl/getting_started/ nie są zbyt intuicyjne a nawet mogą wprowadzić w błąd zwykłego użytkownika zaczynającego swoją drogę z API Allegro.

Idąc krok po kroku przez ten dokument:
Po sekcji "Jak zarejestrować nową aplikację" w której rejestrujemy aplikację w Sandbox'ie następuje sekcja "Jak uzyskać token dostępowy do API".
W sekcji tej napisane jest: "Masz już zarejestrowaną aplikację, czas wygenerować access_token", oraz później: "Skopiuj poniższy kod do pliku, np. api_allegro.php:". Niestety, jeśli użytkownik zarejestrował swoją aplikację w Sandbox'ie zgodnie ze wcześniejszą sekcją to kod ten nie zadziała. Powodem jest adres "curl" w funkcji "getAccessToken()".

![image](https://user-images.githubusercontent.com/76817721/130433730-04b98744-5f6a-4f41-a0df-25eef893c6b7.png)

W przykładzie do skopiowania jako curl url podają Państwo adres "https://allegro.pl/auth/oauth/token".
Lepszym rozwiązaniem byłoby podanie tam adresu "https://allegro.pl.allegrosandbox.pl/auth/oauth/token" odpowiadającego za autentyfikację aplikacji Sandbox'owych, oraz zwrócenie uwagi jeszcze w tym paragrafie na różnice w adresach między produkcyjnym a testowym REST API o których piszą Państwo w "Informacjach podstawowych".

W tym momencie użytkownik po uzupełnieniu zdefiniowanych stałych w skopiowanym kodzie ("CLIENT_ID" oraz "CLIENT_SECRET") i wykonaniu go otrzymuje tylko informację o błędzie: "access_token = Something went wrong". Wówczas może głowić się gdzie popełnił błąd pomimo tego, że postępował zgodnie z instrukcjami zamieszczonymi w poprzedniej sekcji tego dokumentu ("Jak zarejestrować nową aplikację").

Ponadto niżej w tej sekcji ("Jak uzyskać token dostępowy do API") napisane jest "W powyższym kodzie możesz dodać w linii 26 polecenie var_dump($tokenObject);". Niestety w kodzie nie ma nawet obiektu o nazwie "$tokenObject" (możliwe, że kod na tej stronie ulegał zmianie?). Jak mniemam chodziło Państwu o obiekt powstały na wskutek wykonania funkcji "json_decode($tokenResult)".

EDIT1:
Zauważyłem, że przez cały ten artykuł w przykładach używane są adresy produkcyjne a nie sandbox'owe. W takim wypadku rzeczywiście zamiast edytować cały artykuł najlepiej w pierwszej sekcji "Jak zarejestrować nową aplikację" dodać adnotację o tym, że w dalszych przykładach wykorzystywane będą takie adresy zamiast adresy sandbox'owe aby użytkownik nie dziwił się, dlaczego kod który skopiował z dalszych sekcji nie działa i nie błądził w poszukiwaniu rozwiązania.

**Comment by PrzemyslawLukanowski** [comment]
Bardzo dziękuję za uwagi. W najbliższym czasie poprawimy treść poradnika.
