### ISSUE TITLE
Błąd przy wyborze rodzaju przesyłki przez API (WZA, Allegro przesyłka polecona)

### ISSUE THREAD

**Issue by MonitumSklep** [allegro/allegro-api#4861]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Testujemy rozwiązania API i system zwraca nam błąd podczas próby zmiany formatu przesyłki.
W narzędziu web-owym dla przesyłki "Allegro przesyłka polecona", do wyboru są 3 formaty:

1. Przesyłka
2. Koperta
3. Paleta 

Następnie uzupełniane są dane gabarytowe i wagowe.

Problem pojawia się podczas korzystania z API, dla tej samej formy dostawy "Allegro przesyłka polecona", opcja zmiany formy przesyłki z "Koperta", na "Przesyłka, jest niedostępna:
![list_jako_paczka](https://user-images.githubusercontent.com/89398422/130457822-cde4ff66-abc1-4290-96ed-bf8f46804486.jpg)

Z czego wynika ten problem i jak go rozwiązać?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id dla wywołania, gdzie zwróciliśmy wspominany komunikat błędu?

**Comment by MonitumSklep** [comment]
Dzień dobry,
Oczywiście, dziękuję za tak szybką reakcję, przekazałem wiadomość do firmy
zajmującej się integracją, jak tylko otrzymam odpowiedź, wrócę z informacją.

Pozdrawiam
Aleksander Cuber

pon., 23 sie 2021 o 15:58 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by MonitumSklep** [comment]
Dzień dobry,
Firma zajmująca się integracją nie była w stanie przesłać potrzebnych
danych, skontaktowałem się więc bezpośrednio z Baselinkerem.
Pracownik przesłał mi plik z logami, który zamieszczam w załączniku.
Jeśli będą potrzebne inne informację, postaram się je uzyskać.

Pozdrawiam
Aleksander Cuber

pon., 23 sie 2021 o 15:58 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Niestety załącznik na GitHubie jest niewidoczny, dlatego prześlij proszę te dane za pomocą naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). W zgłoszeniu dopisz, że dane dotyczą wątku #4861 na GitHubie.

**Comment by MonitumSklep** [comment]
Dziękuję za instrukcję, przesłałem załącznik w formularzu, gdyby to jednak
pomogło, przesyłam je również w załączniku do tej wiadomości.
Pozdrawiam
Aleksander Cuber

wt., 24 sie 2021 o 14:46 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za wysłane logi. Przeanalizowaliśmy je - powodem, dla którego zwróciliśmy komunikat błędu, jest to, że "Allegro przesyłka polecona" może być wyłącznie kopertą. W przypadku zmiany typu przesyłki na "PACKAGE" zwracamy adekwatny komentarz "Usługa niedostępna dla wybranego typu przesyłki", ponieważ usługa "registeredCompanyLetter" zarezerwowana jest wyłącznie dla typu przesyłki "DOX" (koperta).

**Comment by MonitumSklep** [comment]
Dzień dobry,
Bardzo dziękuję za odpowiedź, proszę jeszcze o informację, czy w takim
wypadku błędem jest, że w narzędziu WEB-owym możemy nadawać przesyłki
Allegro przesyłka polecona jako "Paczka"?

Pozdrawiam
Aleksander Cuber

śr., 25 sie 2021 o 08:58 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Pozwolę sobie wkleić fragment [artykułu](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1) ze strony dla sprzedających:

> Jeśli kupujący wybrał metodę dostawy Allegro Przesyłka Polecona, w trakcie zamawiania przesyłki w Wysyłam z Allegro wszystkie niezbędne opcje zaznaczymy za Ciebie. Są to:
> - rodzaj przesyłki: Koperta
>  - usługa dodatkowa: Przesyłka polecona firmowa
>  - przewoźnik: Poczta Polska (w sekcji "Wybierz przewoźnika" - Allegro Poczta)

(...)

> Kupujący wybrał metodę dostawy Allegro Przesyłka Polecona. Dlaczego Wysyłam z Allegro traktuje przesyłkę jako Allegro Pocztex Kurier48?
> Może się tak wydarzyć w poniższych przypadkach:
>  - rodzaj przesyłki jest inny, niż koperta (paczka albo paleta)
>  - w sekcji “Usługi dodatkowe” nie masz zaznaczonej opcji “Przesyłka polecona firmowa”
> Zanim zamówisz przesyłkę, upewnij się, że te pola są zaznaczone poprawnie. W przeciwnym wypadku przesyłkę nadasz metodą Allegro Pocztex Kurier 48 i rozliczysz się za nią zgodnie z cennikiem.

Jeśli zatem zmienisz na stronie rodzaj przesyłki na "Paczka", potraktujemy ją jako przesyłkę "Allegro Pocztex Kurier48".

**Comment by MonitumSklep** [comment]
Teraz rozumiem, zatem przesyłki, które wysyłaliśmy w ten sposób były
traktowane jako pocztex Kurier48.
Dziękuję za wyjaśnienie.
Pozdrawiam
Aleksander Cuber

śr., 25 sie 2021 o 09:26 PrzemyslawLukanowski ***@***.***>
napisał(a):
