### ISSUE TITLE
W jaki sposób przez REST API mógłbym sprawdzić czy konto klienta ma prawidłowo przygotowane warunki zwrotu?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4862]
Chciałbym automatycznie kontrolować przez REST API i w razie potrzeby ponaglać klienta żeby dostosował warunki zwrotu do nowych wymagań. Tak aby nie było niespodzianek po 30 września.

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie ma w tym momencie (przed wdrożeniem w październiku) takiego sposobu. Aktualnie musiałbyś kierować się wytycznymi, które opisaliśmy w [naszym newsie](https://developer.allegro.pl/news/#return-policy-changed). Pisaliśmy, że walidacja adresu zostanie włączona już w lipcu, jednak tak się nie stało - przepraszam za błędną informację, sprostujemy to. 

W skrócie wytyczne to:
- adres w odpowiednim formacie, który opisujemy w [newsie](https://developer.allegro.pl/news/#return-policy-changed) (będziemy walidować w przypadku countryCode: PL),
- obowiązkowe uzupełnienie flag w nowym polu "**options**",
- opcjonalne uzupełnienie pola "**contact**",
- upewnienie się, że w "**availability.restrictionCause**" nie jest ustawiona jedna z wartości:
     - “ALCOHOL”,
     - “BOOKED_SERVICE”,
     - “FULLY_IMPLEMENTED_SERVICE”.

**Comment by tomylee0** [comment]
Czy walidacja adresu przy ręcznym aktualizowaniu (przez panel administracyjny www konta) też jeszcze nie działa? Jeśli nie działa to klient który uaktualnił sobie już warunki zwrotu nie może być pewien, że od 1 października nie będzie miał kłopotów z obsługą konta.

Czy znany jest termin wprowadzenia walidacji adresu przy ręcznym aktualizowaniu?

**Comment by AureliuszBrussy** [comment]
Zakładka [Warunki zwrotów](https://allegro.pl/moje-allegro/sprzedaz/warunki-zwrotow) jest już dostosowana do nowych wymagań i adres jest walidowany.

**Comment by tomylee0** [comment]
W takim razie wydaje się, że jeśli pobiorę przez REST API warunki zwrotu i znajdę tam nowe pole **options** to mogę założyć, że warunki zwrotu są przystosowane do nowych wymagań. Bo udało się ręcznie klientowi zapisać. Popraw mnie proszę jeśli się mylę.

**Comment by AureliuszBrussy** [comment]
@tomylee0 przy założeniu, że sprzedający edytował je w zakładce, to tak, zgadza się, to oznaczałoby, że warunki zwrotów zostały już edytowane i zapisane (czyli przeszły walidację) - w związku z tym są przystosowane do nowych wymagań.

**Comment by tomylee0** [comment]
Dzięki.
