### ISSUE TITLE
Pobieranie informacji o wielu ofertach

### ISSUE THREAD

**Issue by therionq** [allegro/allegro-api#4864]
Czy istnieje możliwość pobierania informacji o wielu ofertach zalogowanego użytkownika w jednym zapytaniu? Bądź jest planowane wprowadzenie takiej funkcjonalności?

**Comment by PrzemyslawLukanowski** [comment]
Możesz wykorzystać [GET /sale/offers](https://developer.allegro.pl/documentation/#tag/User's-offer-information), aby pobrać listę ofert zalogowanego użytkownika. Response, który otrzymasz w odpowiedzi, nie zawiera jednak wszystkich informacji, które możesz pobrać za pomocą [GET /sale/offers/{id}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET). Na tę chwilę nie mamy w planach innego rozwiązania.
