### ISSUE TITLE
taski nie wykonują się (aktywacja zakończonych ofert), utknęły na statusie "new"

### ISSUE THREAD

**Issue by oponika** [allegro/allegro-api#4867]
Występuje problem: 
 -  X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
taski nie wykonują się (aktywacja zakończonych ofert), utknęły na statusie "new" i tak w nieskończoność

sale/offer-publication-commands/ea708772-e123-4d77-bc77-50f9d7747805/tasks

ręcznie oferty aktywują się bezproblemowo

**Comment by tomasz244** [comment]
mam ten sam problem.
Gdy pobieram responce na końcu mam takie coś
 [contact] => [validation] => stdClass Object ( [errors] => Array ( ) [warnings] => Array ( ) [validatedAt] => 2021-08-24T21:32:31.200Z ) [b2b] => [createdAt] => 2021-08-24T21:32:31.000Z [updatedAt] => 2021-08-24T21:32:31.349Z ) 
i już nie wiem gdzie jest błąd.

**Comment by oponika** [comment]
Widzę, że się jednak wykonały po...6 godzinach, niezłe tempo

**Comment by oponika** [comment]
W takim razie pytanie, dlaczego jeśli zmieniam status publikacji ręcznie to trwa to sekundę a przez API 6 godzin

**Comment by hahyes** [comment]
> W takim razie pytanie, dlaczego jeśli zmieniam status publikacji ręcznie to trwa to sekundę a przez API 6 godzin

Bo API na froncie jest inne. Popsuli coś w API dla sprzedawców, w API frontowym wszystko działa.

**Comment by barthoos** [comment]
Tez podbijam. Mam 8k prob aktywowania oferty i wszystkie stoja. Najstarsze od wczoraj od 20. 
Przykladowo:

9a63e49d-6c21-4ff2-a7fc-68eb0b6839b6
d5677696-10b5-4223-90d3-a42990da8a09
376190b6-36cc-4466-aeeb-68412544ba0a
8f260367-38cd-40a4-82d0-c90cc895e2c4
c27b0453-f53f-424f-af18-f22cb3fc7278

**Comment by AureliuszBrussy** [comment]
Mamy opóźnienia w operacjach na ofertach - aktualnie je niwelujemy, jednak może to potrwać jeszcze kilka godzin. Przepraszamy za niedogodności.
