### ISSUE TITLE
[Urgent]Regarding the problem of abnormal advertising pictures 

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#4868]
Dear allegro team, there are a lot of abnormal pictures in our shop, but the links we uploaded have specific pictures, and the picture size is about 100kb. How can I solve this problem?
For example, the shop Prettyia, spuid: 11074127842, the address of the image we uploaded: https://i.bosity.com/neimage/66031436/image.jpg
![image](https://user-images.githubusercontent.com/72594584/130746219-1ffa9c69-4af8-4d65-b9be-460a36cd734e.png)
Platform display picture  as shown in the figure：https://allegro.pl/oferta/5-2-1-high-speed-metalowa-szpula-z-11074127842
![lALPD3zUOu1Y_6DNA_LNBgo_1546_1010](https://user-images.githubusercontent.com/72594584/130746279-18ddb2a0-5981-44b4-8282-4e7d604dbc17.png)

There are a large number of advertisements in the uploaded advertisements which are such problems. I look forward to getting your reply as soon as possible. Thank you!

**Comment by AureliuszBrussy** [comment]
When you uploaded the photo - your server returned just such an image as you see in the offer. Please check if there was any problem with your image server at the time of uploading the picture and why a different picture (no-image replacement) was available at that time.
