### ISSUE TITLE
Brak informacji o nowych zamówieniach

### ISSUE THREAD

**Issue by mojosoft** [allegro/allegro-api#4869]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Od godz około 3.00 nie pobierają się informacje o nowych zamówieniach
np numer zamówienia: 
a681a191-0562-11ec-9bb1-418da61df1af

**Comment by AureliuszBrussy** [comment]
Opóźnienia mogły wystąpić w nocy, natomiast aktualnie wszystkie zamówienia powinieneś otrzymywać na bieżąco. Sprawdziłem wskazane zamówienie - aktualnie jest ono zwracane w API.

**Comment by mojosoft** [comment]
Niestety nadal nie mamy informacji o nowych zamówieniach ostatni numer zamówienia z APi to 0ef7f821-052a-11ec-86ac-cd4ee39f1d4c

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to - tak jak wspomniałem, aktualnie możesz przez API pobrać wszystkie najnowsze zamówienia - zwracamy je. Upewnij się, czy narzędzie z którego korzystasz działa prawidłowo.

**Comment by mojosoft** [comment]
Czy coś było zmienianie dzisiaj w nocy w restapi jezeli chodzi o pobieranie zamówień ?

**Comment by mojosoft** [comment]
Teraz ruszyło , a nic nie zmieniałem ;)

**Comment by arolznov** [comment]
Wydaje mi się, że coś zostało namieszane w /order/events. Do tej pory numery id były mniej więcej powiązane z polem occuredAt. Kolejne numery id zdarzeń mają dzisiejsze daty jak i wczorajsze

**Comment by AureliuszBrussy** [comment]
@arolznov możesz doprecyzować co masz na myśli i podać jakiś przykład? Powiniśmy zwrócić eventy chronologicznie od najstarszych do najmłodszych.

**Comment by arolznov** [comment]
```
id eventu        | data wystąpienia UTC
1629843635636816 | 2021-08-24 22:20:24
1629843635295672 | 2021-08-24 22:20:24
1629842451935304 | 2021-08-24 22:00:39
1629862815121530 | 2021-08-24 22:00:39
1629842229518317 | 2021-08-24 21:56:53
1629860418421064 | 2021-08-24 21:56:53
```

eventy 1629860418421064 oraz 1629862815121530 mają znacznie wyższe idki. Odpytanie /order/events?from=1629860418421064 nie zwróci np. eventu 1629842451935304 który ma późniejszą datę wystąpienia

**Comment by hahyes** [comment]
To ja z kolei mam inny przypadek, gdzie event nagle pojawia się w dzienniku po kilku godzinach.
```
eventID                    | type                                                 | occuredAt
1629891813376990 | FILLED_IN                                        | 1629891802110
1629891669522193 | BOUGHT                                         | 1629877680000
1629891640827425 | FULFILLMENT_STATUS_CHANGED | 1629891630395
```

Odpytując o następne eventy po `1629891630395`, który to stał się o `25 August 2021 11:40:30.395`, otrzymuje event `1629891669522193`, który to stał się o `25 August 2021 07:48:00`. Fajnie, że w ogóle event zaistniał w dzienniku, ale prawie 4 godziny to jest ogromne opóźnienie!

**Comment by AureliuszBrussy** [comment]
Dziękuję za przykłady - przeanalizujemy to i wrócę z odpowiedzią.
