### ISSUE TITLE
odświeżenie aukcji

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#487]
Witam,
Mam kilkaset aukcji które od roku się nie sprzedały i chciałbym je zakończyć i wystawić dokładnie takie same jeszcze raz. Moglibyście mi napisać z jakich metod korzystać? Może to być w WebApi lub w REST bez różnicy.

**Comment by AniaMalinowska** [comment]
Informacje na ten temat znajdziesz na naszym [portalu developerskim](https://developer.allegro.pl/). 

- Zakończenie:

 [metoda PUT](https://developer.allegro.pl/sale/#step-7-offer-publication-commands) - wystarczy, że w polu action podasz wartość END.

- Jak [wystawić ofertę](https://developer.allegro.pl/sale/) w Allegro REST API.

**Comment by martacronic** [comment]
Ja mogę powiedzieć jak to wygląda ze strony WebApi, bo ostatnio to robiłam.

1. Metodą [doGetMySellItems ](https://allegro.pl/webapi/documentation.php/show/id,1202) pobieram wszystkie aukcje za pomocą pół 'itemStartTime' sprawdzam aukcję, które są starsze niż rok.

2. Metodą [doSellSomeAgainInShop](https://allegro.pl/webapi/documentation.php/show/id,322) wystawiam aukcję na podstawie id tych wyszukanych

3. Wszystkie aukcję, dla których zostało przeprowadzone prawidłowe wystawianie podobnej zamykam metodą [doFinishItem](https://allegro.pl/webapi/documentation.php/show/id,221).

Problemem jest to, że nie mam możliwości sprawdzenia kiedy była ostatnia sprzedaż, więc zamukam wszystko, co trwa rok i w moim przypadku nie jest to problem.

Nie sugeruj się również tym, że w metodzie [doSellSomeAgainInShop](https://allegro.pl/webapi/documentation.php/show/id,322) jest parametr, który pozwala aukcję, na której podstawie wystawiasz zamknąć, czyli sellShopOptions = 1(źródłowe oferty zostaną usunięte z odpowiedniej zakładki w Moim Allegro). To nie działa, zgłaszałam Ticket#1249989734], ale konkretnej informacji o tym kiedy będzie to naprawione nie dostałam.

Mam nadzieję, że pomogłam.

**Comment by SoftWareMG** [comment]
Dzieki za info, takiej informacji oczekiwalem :) Wysłane ze smartfona w T-Mobile, sieci największych możliwości.-------- Wiadomość oryginalna --------Temat: Re: [allegro/allegro-api] odświeżenie aukcji (#487)Od: martacronic Do: allegro/allegro-api DW: SoftWareMG ,Author Ja mogę powiedzieć jak to wygląda ze strony WebApi, bo ostatnio to robiłam.


Metodą doGetMySellItems  pobieram wszystkie aukcje za pomocą pół 'itemStartTime' sprawdzam aukcję, które są starsze niż rok.


Metodą doSellSomeAgainInShop wystawiam aukcję na podstawie id tych wyszukanych


Wszystkie aukcję, dla których zostało przeprowadzone prawidłowe wystawianie podobnej zamykam metodą doFinishItem.


Problemem jest to, że nie mam możliwości sprawdzenia kiedy była ostatnia sprzedaż, więc zamukam wszystko, co trwa rok i w moim przypadku nie jest to problem.
Nie sugeruj się również tym, że w metodzie doSellSomeAgainInShop jest parametr, który pozwala aukcję, na której podstawie wystawiasz zamknąć, czyli sellShopOptions = 1(źródłowe oferty zostaną usunięte z odpowiedniej zakładki w Moim Allegro). To nie działa, zgłaszałam Ticket#1249989734], ale konkretnej informacji o tym kiedy będzie to naprawione nie dostałam.
Mam nadzieję, że pomogłam.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/allegro/allegro-api","title":"allegro/allegro-api","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/allegro/allegro-api"}},"updates":{"snippets":[{"icon":"PERSON","message":"@martacronic in #487: Ja mogę powiedzieć jak to wygląda ze strony WebApi, bo ostatnio to robiłam.\r\n\r\n1. Metodą [doGetMySellItems ](https://allegro.pl/webapi/documentation.php/show/id,1202) pobieram wszystkie aukcje za pomocą pół 'itemStartTime' sprawdzam aukcję, które są starsze niż rok.\r\n\r\n2. Metodą [doSellSomeAgainInShop](https://allegro.pl/webapi/documentation.php/show/id,322) wystawiam aukcję na podstawie id tych wyszukanych\r\n\r\n3. Wszystkie aukcję, dla których zostało przeprowadzone prawidłowe wystawianie podobnej zamykam metodą [doFinishItem](https://allegro.pl/webapi/documentation.php/show/id,221).\r\n\r\nProblemem jest to, że nie mam możliwości sprawdzenia kiedy była ostatnia sprzedaż, więc zamukam wszystko, co trwa rok i w moim przypadku nie jest to problem.\r\n\r\nNie sugeruj się również tym, że w metodzie [doSellSomeAgainInShop](https://allegro.pl/webapi/documentation.php/show/id,322) jest parametr, który pozwala aukcję, na której podstawie wystawiasz zamknąć, czyli sellShopOptions = 1(źródłowe oferty zostaną usunięte z odpowiedniej zakładki w Moim Allegro). To nie działa, zgłaszałam Ticket#1249989734], ale konkretnej informacji o tym kiedy będzie to naprawione nie dostałam.\r\n\r\nMam nadzieję, że pomogłam."}],"action":{"name":"View Issue","url":"https://github.com/allegro/allegro-api/issues/487#issuecomment-412091690"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/allegro/allegro-api/issues/487#issuecomment-412091690",
"url": "https://github.com/allegro/allegro-api/issues/487#issuecomment-412091690",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [allegro/allegro-api] odświeżenie aukcji (#487)",
"sections": [
{
"text": "",
"activityTitle": "**martacronic**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@martacronic",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"allegro/allegro-api\",\n\"issueId\": 487,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"allegro/allegro-api\",\n\"issueId\": 487\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/allegro/allegro-api/issues/487#issuecomment-412091690"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367019858\n}"
}
],
"themeColor": "26292E"
}
]
