### ISSUE TITLE
Problem z podwójnym/potrójnym wysyłaniem eventów  READY_FOR_PROCESSING

### ISSUE THREAD

**Issue by lasoczczyk** [allegro/allegro-api#4870]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dublują się eventy ze statusem READY_FOR_PROCESSING od 19 sierpnia to występuje. Pododawało mi po kilka razy te same zamówienia do mojego sklepu.
Przykładowe zamówienia: **ae144ab1-01d5-11ec-a31d-a5774b94b506** oraz **f157b841-0516-11ec-9deb-b93ab6f30e1f**

Tutaj przykład eventów - w tym przypadku potrójnie! W kolejnosci ID, data, zamowienie i status

1629835800094592 | 2021-08-24 20:09:44 | f157b841-0516-11ec-9deb-b93ab6f30e1f | READY_FOR_PROCESSING 
1629860266454414 | 2021-08-24 20:09:44 | f157b841-0516-11ec-9deb-b93ab6f30e1f | READY_FOR_PROCESSING
1629863554222453 | 2021-08-24 20:09:44 | f157b841-0516-11ec-9deb-b93ab6f30e1f | READY_FOR_PROCESSING

**Comment by AureliuszBrussy** [comment]
Może zdarzyć się tak, że otrzymasz kilka zdarzeń READY_FOR_PROCESSING dla tego samego zamówienia. Piszemy o tym także w [naszym poradniku](https://developer.allegro.pl/orders/#dziennik-zdarze%c5%84).

**Comment by lasoczczyk** [comment]
OK rozumiem, musiałem to przegapić.
Tylko ciekawe dlaczego przed 19 sierpnia taka sytuacja się nigdy nie zdarzyła.... sprawdziłem całą bazę zamówień....

**Comment by hahyes** [comment]
> OK rozumiem, musiałem to przegapić.
> Tylko ciekawe dlaczego przed 19 sierpnia taka sytuacja się nigdy nie zdarzyła.... sprawdziłem całą bazę zamówień....

Musiałeś mieć szczęście. Sytuacja z wieloma eventami jest znana już od jakiegoś czasu i opisana w poradniku też już od dawna. ;)
