### ISSUE TITLE
[sandbox] Odbiór osobisty wpunkcie sprzedawcy

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#4871]
Hej, mam problem z odbiorem osobistym w punkcie sprzedawcy.
Mam stworzony punkt odbioru + mam w cenniku dostawy wybrany odbiór w punkcie sprzedawcy + pobranie.
Po wystawieniu oferty na sandboxie w zakładce dostawy widzę odbiór w punkcie ale gdy chce sfinalizować zakup widzę wszystkie pozostałe formy transportu poza odbiorem w punkcie sprzedawcy.
Co robię źle? Czy coś trzeba dodatkowo aktywować?

**Comment by PrzemyslawLukanowski** [comment]
Nie musisz wykonywać dodatkowych kroków. Niestety nie udało mi się powtórzyć tego błędu - "odbiór w punkcie" w moim przypadku jest widoczny na dostępnych metodach dostawy przy finalizacji zakupu. Czy możesz podać numer oferty, w której występuje ten problem? Jeśli nie chcesz go podawać na forum, skorzystaj z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=e2e1f990-74d6-4bea-9b5c-a408bde7983d&subjectId=da43023c-bc80-44ec-9a6d-d43df46b42a6), dopisz wtedy, że dane dotyczą zgłoszenia #4871 na GitHub.

**Comment by mlonc** [comment]
Jasne nie ma problemu: 7680720585

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem na dwóch różnych urządzeniach i kontach kupującego - odbiór w punkcie jest widoczny:
![Untitled](https://user-images.githubusercontent.com/51473661/130798479-e771bbb7-8006-4aee-b663-47078e2c55d7.png)
![untitled2](https://user-images.githubusercontent.com/51473661/130798488-a8656d51-186c-4741-bd87-f3a492d52204.png)

**Comment by mlonc** [comment]
ok w tym momencie też to mam. Jednak zaraz po wystawieniu oferty odbiór osobisty nie wyświetlał się.
