### ISSUE TITLE
Pobieram listę ofert INACTIVE ale nie mogę pobrać szczegółów oferty

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4878]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Pobieram pierwsze 3 oferty INACTIVE:

/sale/offers?limit=3&publication.status=INACTIVE
trace-id: b686fed175bd2482

Pobieram szczegóły jednej z nich przez /sale/offers/{offerId}
trace-id: f7d8bbd24664775e

Otrzymuję błąd:
Offer not found. It was deleted, archived or never existed.

Do tej pory sądziłem, że /sale/offers nie zwróci zarchiwizowanych ofert. Na tym opierała się moja funkcjonalność wyszukująca drafty (czyli INACTIVE) które należy usunąć żeby nie przekroczyć ich maksymalnej wartości i nie doprowadzić do blokady wystawiania nowych ofert. 

Czy to chwilowy błąd czy coś się zmieniło?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Faktycznie, w ten sposób możesz wyszukać drafty, nie powinniśmy zwrócić ofert zarchiwizowanych. Analizujemy jeszcze ten problem, wrócę z odpowiedzią.

**Comment by tomylee0** [comment]
Czy udało się coś już zdiagnozować?

**Comment by AureliuszBrussy** [comment]
@tomylee0 pracujemy jeszcze nad tym błędem. Napiszę, gdy tylko pozbędziemy się problemu.
