### ISSUE TITLE
Access Denied dla szukana produktu po Ean

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4880]
API działa, zwraca dane, komunikuję się bez błędów. 

Ale gdy wyślę zapytanie: 

```
GET 
https://api.allegro.pl/sale/products?ean=5905241004587
```

to otrzymuję błąd: 

```
403
https://api.allegro.pl/sale/products?ean=5905241004587
{
	"errors": [
		{
			"code": "AccessDenied",
			"details": null,
			"message": "Access is denied",
			"path": null,
			"userMessage": "Access denied. Contact the author of the application."
		}
	]
}
```

Co poprawić, abym mógł pobrać informacje o produkcie?

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że korzystasz z autoryzacji typu [client-credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow) (bearer-token-for-application). Zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/getSaleProducts), musisz być zautoryzowany za pomocą [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow (bearer-token-for-user).

**Comment by leszekdubiel** [comment]
Token pobieram takim zapytaniem, czyli jest to "authorization_code": 

```
        my $dat = rest(
                "GET", 
                "https://allegro.pl/auth/oauth/token" . 
                        REST::Client->new()->buildQuery({ 
                                grant_type => "authorization_code", 
                                code => $$inp{code}, 
                                "redirect_uri" => "https://www.lustra.pl/allegro.pl",
                        }),
                "",
                {
                        "Authorization" => "Basic " . encode_base64("$$konf{clientId}:$$konf{clientSecret}", "")
                }
        ); 
````

Jeśli zamiast 

```
GET 
https://api.allegro.pl/sale/products?ean=5905241004587
```

wywołam (słowo "products" zamienione na "offers"), to wszystko działa dobrze: 

```
GET 
https://api.allegro.pl/sale/offers?ean=5905241004587
```

Co więcej -- w dokumentacji obie metody używają takiego samego rodzaju tokena "bearer-token-for-user": 

[https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET)
[https://developer.allegro.pl/documentation/#operation/getSaleProducts](https://developer.allegro.pl/documentation/#operation/getSaleProducts)

**Comment by MartaNowaczyk** [comment]
Rozumiem. Sprawdź jeszcze proszę czy w nagłówku Accept masz na pewno `application/vnd.allegro.public.v1+json` jeśli tak, a nadal dostajesz błąd podeślij trace-id dla tego wywołania.

**Comment by leszekdubiel** [comment]
Oto trace-id:   448e6e862ba01ccc

```
błąd komunikacji
403
https://api.allegro.pl/sale/products?ean=5905241004600
trace-id 448e6e862ba01ccc
date Tue, 31 Aug 2021 08:40:37 GMT
client-peer 185.31.27.150:443
content-type application/json; charset=utf-8
{
	"errors": [
		{
			"code": "AccessDenied",
			"details": null,
			"message": "Access is denied",
			"path": null,
			"userMessage": "Access denied. Contact the author of the application."
		}
	]
}
```

**Comment by MartaNowaczyk** [comment]
Z tego co widzę przesyłasz dla accept application/vnd.allegro.beta.v1+json zmień na application/vnd.allegro.public.v1+json i powinno być ok.

**Comment by MartaNowaczyk** [comment]
Poprawka, wcale nie wysyłasz tego Accepta, stąd błąd.

**Comment by leszekdubiel** [comment]
Faktycznie źle napisałem nazwę nagłówka -- zamiast Content-Type powinno być Accept. 
Dziękuję za pomoc. 

Oto błędny kod: 

```
        rest(
                $_[0], # metoda "GET" czy "POST", i inne
                $_[1], # Url 
                encode_utf8(do_json($_[2])), # treść do wysłania; muszę numerować argumenty, bo może być puste 
                {
                        "Authorization" => "Bearer $$konf{token}{access_token}",
                        "Content-Type" => "application/vnd.allegro.public.v1+json", 
                }
        );
```
