### ISSUE TITLE
Nie działa DELETE /sale/offers/{offerId} - 400 You can delete only inactive offer. - oferta jest już nieaktywna od kilku dni

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4887]
Próbuję usunąć ofertę przez API 

`DELETE /sale/offers/{offerId}`

W odpowiedzi dostaję:

`[{"code":"BAD_REQUEST","message":"You can delete only inactive offer.","details":"CannotDeleteOfferException","path":"","userMessage":"You can delete only inactive offer."}]}`

TraceId: 2503917e321b6d2f

Oferta jest zakończona: 

Według allegro po wejściu na ofertę na stronie allegro: 

> Sprzedaż zakończona
> Nie było ofert kupna.
> 
> szukana oferta jest nieaktualna - może podobny przedmiot?

Poradzicie co robię źle jak usunąć ofertę z allegro przez API?

**Comment by AureliuszBrussy** [comment]
Za pomocą [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE) usuwać możesz tylko drafty (szkice) ofert, czyli takie oferty, które nigdy nie były aktywowane. Nie ma sposobu usunięcia aktywowanej oferty - zostanie ona przeniesiona do archiwum po 60 dniach od zakończenia i wtedy przestanie być zwracana w [GET /sale/offers](https://developer.allegro.pl/documentation/#tag/User's-offer-information).

**Comment by pliszka** [comment]
ok thx zamykam :)
