### ISSUE TITLE
wznawianie przestało zwracać statusy ?

### ISSUE THREAD

**Issue by partyumarty** [allegro/allegro-api#489]
Hej, co jest grane ? Aukcja się wznawia, dostaję maila, aukcja wisi w serwisie, a tymczasem jest lipa w statusie. Cały czas wisi jako NEW czyli system mi o to w kółko odpytuje. Problem dotyczy wszystkich aukcji od wczoraj wznawianych od godziny 15:00...

```
stdClass Object
(
    [tasks] => Array
        (
            [0] => stdClass Object
                (
                    [offer] => stdClass Object
                        (
                            [id] => 7344599490
                        )

                    [message] => 
                    [status] => NEW
                    [scheduledAt] => 2018-08-10T15:49:25.011+02:00
                    [finishedAt] => 
                    [field] => publication
                )

        )

)
```

**Comment by MaciejPotepa** [comment]
Cześć

Podeślij proszę request i response. Jeżeli masz możliwość to jeszcze trace ID. Sprawdzimy co poszło nie tak. 

Swoją drogą, bardzo fajna oferta. :)
