### ISSUE TITLE
Błąd zmiany ilości na 100 000

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#4892]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - 
:beetle: **Opis**
Dzień dobry, przy próbie zmiany ilości na dokładnie 100 000 dostaję błąd zmiany, że wartość nie może być większa od 100 000, a przecież ustawiam dokładnie 100 000. Proszę o wyjaśnienie skąd jest taki błąd.

Przykładowy request, response zmiany ilości i raportu:

```
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/32ab6b48-b662-41bd-81cc-fe5e134834c8' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \
  -d '{"modification":{"changeType":"FIXED","value":100000},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"9392959593"}]}]}' \

RESPONSE 
{
  "Data": {
    "Id": "32ab6b48-b662-41bd-81cc-fe5e134834c8",
    "TaskCount": {
      "Failed": 0,
      "Success": 0,
      "Total": 0
    }
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "fd4f659fc8680a7e",
  "Error": false,
  "StatusCode": 201,
  "Message": null
}


REQUEST 2021-09-03 09:15:17.8330235 
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/32ab6b48-b662-41bd-81cc-fe5e134834c8/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer 
  
RESPONSE 2021-09-03 09:15:17.8647945 Duration: 31,771ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2021-09-03T07:04:52.031Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "9392959593"
        },
        "ScheduledAt": "2021-09-03T07:04:52.032Z",
        "Status": "FAIL",
        "Errors": [
          {
            "Code": "ConstraintViolationException.Max",
            "Details": null,
            "Message": "The stock level of items to be listed may not be greater than 100 000.",
            "Path": "stock.initialQuantity",
            "UserMessage": "Wystawiana liczba nie może być większa niż 100 000."
          }
        ]
      }
    ]
  },
  "Validation": null,
  "Exception": null,
  "TraceId": "9effbc324ace166c",
  "Error": false,
  "StatusCode": 200,
  "Message": null
}
```

**Comment by AureliuszBrussy** [comment]
Wyjaśnienie znajdziesz w [tym wątku](https://github.com/allegro/allegro-api/issues/3463). Do ustawionej przez Ciebie liczby sztuk dodajemy też te dotychczas sprzedane, stąd występuje przekroczenie limitu 100 000 sztuk.

**Comment by alekskuc** [comment]
@AureliuszBrussy aha, no tak. 

Proponuję zlikwidować to dodawanie tych dotychczas sprzedanych.

Scenariusz mam taki gdzie sprzedający ma nieograniczoną liczbę sztuk do sprzedania powiedzmy gwoździe na sztuki. W przypadku zmniejszania limitu o sprzedane jak sprzeda odpowiednio dużo sztuk to polecą błędy i trzeba będzie od nowa ofertę wystawiać z tym samym towarem.

Miałem sztuczne obejście tego problemu, maksymalnie pozwalając wystawiać 10 000 i wtedy można sprzedawać 90 000 do momentu błędów z limitem. Wolałbym żeby sprzedawcy mieli możliwość uzupełniania ilości sztuk do 100 000 żeby mieć duży zapas na większe zamówienia.

**Comment by AureliuszBrussy** [comment]
@alekskuc dziękuję za propozycję i argumenty - faktycznie po sprzedaniu 100 000 sztuk towaru niezbędne byłoby ponowne wystawienie nowej oferty przy tym ograniczeniu.
Jeżeli coś zmienimy w kwestii dodawania sztuk sprzedanych - zakomunikujemy to.
