### ISSUE TITLE
Pusty response raz na kilkaset wywołań

### ISSUE THREAD

**Issue by kuba4400** [allegro/allegro-api#4896]
Raz na kilkaset wywołań otrzymuję pusty response.
Widać to po wiadomości w logach - po dwukropku wypisuję odpowiedź serwera:
![error](https://user-images.githubusercontent.com/76817721/132304007-e8fb24b8-17dc-4104-86d3-a3fda1fb7bcb.png)
Kod:

	//FUNKCJA POBIERA OSTATNIE 20 WIADOMOSCI Z DANEGO WATKU
	function getThreadMessagesList($token, $threadId)
	{
		$headers = array("Authorization: Bearer {$token}", "Accept: application/vnd.allegro.public.v1+json");
		$url = "https://api.allegro.pl/messaging/threads/".$threadId."/messages";
		$ch = getCurlUrl($headers, $url);
		$messagesListResult = curl_exec($ch);
		$resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		curl_close($ch);
		if ($messagesListResult === false || $resultCode !== 200) {
			Logger::addErr("Błąd podczas pobierania informacji o wiadomościach w danym wątku Centrum Wiadomości: $messagesListResult", LOGS_FILE, LOGS_PATH);
			exit;
		}
		$messagesList = json_decode($messagesListResult);
		return $messagesList;
	}

Ponieważ problem występuje sporadycznie, nie stanowi on zagrożenia w funkcjonowaniu programu.
Dlatego też chciałem zapytać czy istnieje szansa na pusty response z API Allegro?
Oczywiście nie licząc sytuacji w których dla przykładu połączenie z api zostało przerwane i z tego powodu nie otrzymaliśmy odpowiedzi od serwera.

EDIT 1:
Mój kod działa prawidłowo, jako dowód zamieszczam przykładowy log gdy response został zwrócony:
| 2021-09-07 09:35:29 |  ERROR  |Błąd podczas pobierania informacji o wątkach w Centrum Wiadomości: {"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}

**Comment by MartaNowaczyk** [comment]
Generalnie jest taka możliwość, że raz na kilkaset razy dostaniesz błąd. Sprawdzamy jednak opisany przypadek. Jak tylko coś ustalimy wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Nie znaleźliśmy problemu po naszej stronie. Taka sytuacja pojawić się może w przypadku zerwania połączenia.
