### ISSUE TITLE
Typy wiadomości w Centrum Wiadomości

### ISSUE THREAD

**Issue by miecha3l** [allegro/allegro-api#4897]
API Centrum Wiadomość przy pobieraniu wiadomości zwraca jej typ. W dokumentacji wypisane są takie typy jak:  
- MESSAGE_CENTER,
- ASK_QUESTION,
- MAIL

Mam następujące pytania:
 Jakie warunki muszą być spełnione żeby wiadomość została przypisana do konkretnego typu?
 Kiedy dokładnie w wiadomości pojawia się tytuł? Z mojej obserwacji wynika, że tylko w przypadku typu MAIL - czy jest to prawidłowa obserwacja?

**Comment by hahyes** [comment]
> API Centrum Wiadomość przy pobieraniu wiadomości zwraca jej typ. W dokumentacji wypisane są takie typy jak:
> 
> * MESSAGE_CENTER,
> * ASK_QUESTION,
> * MAIL
> 
> Mam następujące pytania:
> Jakie warunki muszą być spełnione żeby wiadomość została przypisana do konkretnego typu?
> Kiedy dokładnie w wiadomości pojawia się tytuł? Z mojej obserwacji wynika, że tylko w przypadku typu MAIL - czy jest to prawidłowa obserwacja?

Tak, typ `MAIL` jest po prostu konwersją otrzymanego maila do obiektu wiadomości, stąd jest tytuł. Tworząc normalnie wątek/wiadomość, nie można dodać tytułu, co widać w dokumentacji API.

**Comment by miecha3l** [comment]
Rozumiem. Natomiast brakuje mi tu odpowiedzi na drugie pytanie:
Jakie warunki muszą być spełnione żeby wiadomość została przypisana do konkretnego typu?

MAIL - tutaj sprawa raczej oczywista - typ jest przypisany jeśli wiadomość pochodzi ze skrzynki pocztowej
Natomiast jaka jest różnica między `MESSAGE_CENTER` oraz `ASK_QUESTION`? W jakich przypadkach te typy występują i co je od siebie różni?

**Comment by MartaNowaczyk** [comment]
MESSAGE_CENTER - wiadomość pisana w samym Centrum Wiadomości lub przez API
ASK_QUESTION - to jest "Pytanie do sprzedającego"
