### ISSUE TITLE
API documentation bug for /payments/refunds. Invalid HTTP code for success

### ISSUE THREAD

**Issue by theazgra** [allegro/allegro-api#4898]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [x] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
 The documentation on the  https://developer.allegro.pl/en/documentation/#operation/initiateRefund says, that the only correct HTTP response code, for payment refund initiation, is `201 CREATED`.

But I have *successfully* refunded payment `0db17d41-0fd1-11ec-861e-537127749702` and got HTTP code `200 OK`

This is the whole response: 
```json
{
  "id": "7bce93be-0fd1-11ec-8229-5ba74ff0a9d4",
  "payment": {
    "id": "0db17d41-0fd1-11ec-861e-537127749702"
  },
  "reason": "REFUND",
  "status": "NEW",
  "createdAt": "2021-09-07T11:48:14.329Z",
  "totalValue": {
    "amount": "69.99",
    "currency": "PLN"
  },
  "lineItems": [
    {
      "id": "09474550-0fd1-11ec-b90e-71edd7432b94",
      "type": "QUANTITY",
      "quantity": 1
    }
  ],
  "surcharges": []
}
```

TraceId:
`2d282006d8eaae93`

Is this documentation or API bug? Should I expect the result code `200` or `201`? 
Thank you

**Comment by MartaNowaczyk** [comment]
Thank you for the information. It should be 201. We'll check and let you know.

**Comment by MartaNowaczyk** [comment]
Due to backward compatibility, we decided to improve the documentation and still return the code 200.

**Comment by theazgra** [comment]
Ok, thanks for your reply. I will update my application to recognize 200 as successful status code.
