### ISSUE TITLE
Dane do faktury zamówienia są w email, a w API zwraca bez danych

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#4899]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Klient zgłasza, że nie ma w zamówieniu w naszym systemie danych do faktury. Kiedy sprawdziłem w bazie to mamy, że `invoice.required` na false. Przed chwilą pobierałem z API to zamówienie i również jest, że nie ma faktury. Klient jako dowód wysłał zrzut emaila gdzie są podane dane do faktury dla tego zamówienia.

Id zamówienia: `2dfa3a12-0bc1-11ec-b5c1-a39c1f4b0cd8`

Trace-id:  `ca17f303dadab1b0`

**Comment by MartaNowaczyk** [comment]
Nie widzę w tym zamówieniu faktury. Podeślij ten zrzut przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) do weryfikacji. Sprawdzimy i damy znać.

**Comment by AnimalDEV** [comment]
Przesłałem zrzut w zgłoszeniu numer 17342886 wraz z linkiem do tego issue, ale  dostałem w odpowiedzi "Dziękuję za przesłany zrzut, jak mogę pomóc?" :disappointed:

**Comment by MartaNowaczyk** [comment]
Mój błąd, powinnam Ci napisać o dodatkowej informacji, żeby do nas dotarło. Dopisz proszę, że dotyczy API i wątku na GitHubie #4899 i na pewno dojdzie.
