### ISSUE TITLE
Przestajemy wspierać domenę https://ssl.allegro.pl

### ISSUE THREAD

**Issue by LukaszKorek** [allegro/allegro-api#49]
W listopadzie 2017 roku zmieniliśmy adres domeny w procesie autoryzacji [OAuth](https://developer.allegro.pl/auth/) z https://ssl.allegro.pl na https://allegro.pl.

Zgodnie z [zapowiedzią](https://developer.allegro.pl/news/) domenę https://ssl.allegro.pl przestaniemy wspierać **13 marca**. Od tego momentu powiniście logować się tylko na https://allegro.pl. **Zaktualizujcie do 13 marca adres domeny w swoim oprogramowaniu.**

**Comment by amarel123** [comment]
Czy subdomena ssl przestanie działać na sandboxie? Jeśli tak to aktualizacje proponuję zacząć od siebie. Strona główna sandboxa prowadzi od dawna na adres allegro.pl.webapisandbox.pl, który nie loguje bez żadnego komunikatu. Tylko logowanie przez ssl.allegro.pl.webapisandbox.pl daje właściwe rezultaty. Jeśli ktoś nie znał tego tricku do tej pory to nie mógł w ogóle korzystać z sandboxa :D

**Comment by LukaszKorek** [comment]
Wkrótce udostępnimy nowe środowisko testowe na którym nie powinny występować tego typu problemu. Prosimy jeszczę o odrobinę cierpliwości :)
