### ISSUE TITLE
kupiony przedmiot niewidoczny w zakladce kupione

### ISSUE THREAD

**Issue by hufoAA** [allegro/allegro-api#490]
po zakupieniu przedmiotu (DoBidItemRequest) wysłaniu formularza pozakupowego (DoSendPostBuyFormRequest) zakupiony przedmiot niewidoczny w zakładce kupionych przedmiotów
sprzedajacy otrzymal wypelniony formularz pozakupowy
srodowisko: sandbox

**Comment by MaciejPotepa** [comment]
Podeślij proszę request i response w .XML. Pamiętaj o zamieszczeniu numeru przedmiotu/transakcji, którego to dotyczy. 

Bez tego nie jesteśmy w stanie namierzyć źródła problemu.

**Comment by hufoAA** [comment]
po wyslaniu podobnego requesta nie na sandboxie zakupiony item od razu jest widoczny w moje zakupy -> kupione

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
				  xmlns:gs="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <gs:DoBidItemRequest>
         <gs:sessionHandle>###</gs:sessionHandle>
         <gs:bidItId>6205399405</gs:bidItId>
		 <gs:bidUserPrice>555</gs:bidUserPrice>
		 <gs:bidQuantity>1</gs:bidQuantity>	
		  <gs:bidBuyNow>1</gs:bidBuyNow>	
      </gs:DoBidItemRequest>
   </soapenv:Body>
</soapenv:Envelope>`

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl.allegrosandbox.pl/service.php">
    <SOAP-ENV:Body>
        <ns1:doBidItemResponse>
            <ns1:bidPrice>555,00 zł - Gratulacje! Kupiłeś przedmiot poprzez Kup Teraz</ns1:bidPrice>
        </ns1:doBidItemResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by MaciejPotepa** [comment]
Dzięki za zgłoszenie, przekazałem problem do odpowiedniego zespołu.

**Comment by MaciejPotepa** [comment]
@hufoAA Otrzymałem informację, ze informacje wszystko powinno już działać prawidłowo. Dzięki za oczekiwanie.
