### ISSUE TITLE
Usuwanie niepotrzebnych już aukcji

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4900]
W jaki sposób mogę w API wyknać usunięcie aukcji z listy? 
W panelu mam taki przycisk "USUŃ" na zielonym tle: 

![jakukryc](https://user-images.githubusercontent.com/17785717/132357139-d3c1e51b-330e-4bf5-a5ea-8d093a267e64.png)

PS. poniższe nie działają

```"DELETE", "https://api.allegro.pl/sale/offers/$ofer"```

```"PUT", ...."https://api.allegro.pl/sale/offer-publication-commands/"    ```

**Comment by MartaNowaczyk** [comment]
Nie ma takiej opcji w API Allegro. Możesz skorzystać z naszej zakładki [Discussions](https://github.com/allegro/allegro-api/discussions) i dodać taką sugestię. Dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.

**Comment by leszekdubiel** [comment]
Czy jest jakiś sposób oznaczenia ofert, aby nie pojawiały się w wynikach zapytania: 

                   ``` "GET",      "https://api.allegro.pl/sale/offers" ```

Usunąć mogę tylko szkice (Status=INACTIVE). 

Czyli jak posprzątać listę ofert... Wysłać je "do kosza", albo "w kosmos", abym ich więcej nie widział.

**Comment by MartaNowaczyk** [comment]
Oferty są usuwane automatycznie po 60 dniach od zakończenia oferty. Innej opcji w API nie ma, dlatego tak jak pisałam wcześniej - zgłoś sugestię, zobaczymy jakie jest zapotrzebowanie na taką opcję.
