### ISSUE TITLE
Obowiązkowe parametry dla kategorii

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#4903]
Witam, 

potrzebuję uzyskać obowiązkowe parametry dla kategorii według produktów. Do tej pory pobierałam parametry dla kategorii po przez metodę get dla https://api.allegro.pl.allegrosandbox.pl/sale/categories/{categoryId}/parameters, w odpowiedzi otrzymywałam wszystkie parametry. 
Czy jest możliwość uzyskania tylko obowiązkowych parametrów dla kategorii ?

Pozdrawiam,
Kasia

**Comment by MartaNowaczyk** [comment]
Nie dostaniesz takiej gotowej listy, możesz tylko je rozpoznać przez "required":true

**Comment by Kasia13130** [comment]
Czy chodzi o coś takiego jak w poniższym przykładzie dla marki ?
stdClass Object ( [id] => 129369 [name] => Marka [type] => dictionary [required] => 1 [requiredForProduct] => 1

**Comment by MartaNowaczyk** [comment]
tak, tylko jeśli chcesz tylko parametry obowiązkowe dla danej kategorii to zwracasz uwagę na `required`, a jeśli chcesz mieć parametry obowiązkowe dla produktu to potrzebujesz też `requiredForProduct`.

**Comment by Kasia13130** [comment]
Bardzo dziękuję za pomoc.
