### ISSUE TITLE
Kiedy pojawi się dokumentacja API do maszyn pocztowych Allegro?

### ISSUE THREAD

**Issue by LukaszMalekBH** [allegro/allegro-api#4904]
Kiedy pojawi się dokumentacja API do maszyn pocztowych Allegro?

**Comment by MartaNowaczyk** [comment]
Mamy już API dla sieci Punktów Allegro. Informowaliśmy o tym np. w [Aktualnościach](https://developer.allegro.pl/news/#allegro-points). 
Tu masz [dokumentację](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET).
