### ISSUE TITLE
Za mały offset na "Get a list of billing entries"

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4905]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy pobieraniu listy opłat nie przyjmuje offsetu więcej niz 1000
![Screenshot_49](https://user-images.githubusercontent.com/81759361/132550490-983cafba-9c92-4a70-a103-f88a918d8f2d.jpg)

I rzeczywiście instrukcja podaje max offset 1000
![Screenshot_51](https://user-images.githubusercontent.com/81759361/132550606-2cbf049a-3976-48a7-b499-c94a1273acb6.jpg)

Jednak inne listy można pobierać w ilości nieskończonej np. GET seller offers ma offset 99999999
![Screenshot_50](https://user-images.githubusercontent.com/81759361/132551076-1ae091dc-9bec-416f-8d42-f48e723cd33b.jpg)

**PYTANIA:**
1. Czym jest podyktowane takie ograniczenie ?
2. Jest może jakiś inny sposób aby ściągnąć listę wszystkich opłat w miesiącu ?

Przy dużej ilości opłat aby zrobić listę miesięczną muszę teraz sumować/odptywać po dniach, a to raczej średnie rozwiązanie.
Jest może szansa na zwiększenie tego ograniczenia ?

**Comment by MartaNowaczyk** [comment]
1. Jest to ustalane wewnętrznie podczas tworzenia funkcjonalności.
2. Nie ma

Możesz skorzystać z naszej zakładki [Discussions](https://github.com/allegro/allegro-api/discussions) i dodać taką sugestię. Dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.

**Comment by Waclaw-W** [comment]
Bardzo dziękuje za szybką odpowiedź,
choć nie do końca takiej oczekiwałem :)

Dodam sugestie na Discussions.

Pozdrawiam
