### ISSUE TITLE
Problem z: /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#4908]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

odpytujemy ten endpoint i dostajemy 
/order/checkout-forms/{id}

{
    "errors": [
        {
            "code": "CheckoutFormNotFoundException",
            "message": "Checkout form 10f97ea2-fad0-11eb-af75-91fcb89c8687 not found",
            "details": null,
            "path": "/order/checkout-forms/10f97ea2-fad0-11eb-af75-91fcb89c8687",
            "userMessage": "Checkout form 10f97ea2-fad0-11eb-af75-91fcb89c8687 not found"
        }
    ]
}

Zamówienie istnieje w systemie.

**Comment by MartaNowaczyk** [comment]
Zamówienie istnieje, ale token, który wysyłasz dotyczy innego konta, stąd opisany problem.
