### ISSUE TITLE
Pobieranie oferta zwraca pustą tablicę

### ISSUE THREAD

**Issue by gscoders** [allegro/allegro-api#4909]
Ta sama metoda na innym koncie nie sprawia tego problemu, poniżej raw request
```
<- "GET /sale/offers?limit=1000&offset=0 HTTP/1.1\r\nAuthorization: Bearer token\r\nAccept: application/vnd.allegro.public.v1+json\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: api.allegro.pl\r\n\r\n"
-> "HTTP/1.1 301 Moved Permanently\r\n"
-> "content-length: 0\r\n"
-> "location: https://api.allegro.pl/sale/offers?limit=1000&offset=0\r\n"
-> "connection: close\r\n"
-> "\r\n"
reading 0 bytes...
-> ""
read 0 bytes
Conn close
opening connection to api.allegro.pl:443...
opened
starting SSL for api.allegro.pl:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384
<- "GET /sale/offers?limit=1000&offset=0 HTTP/1.1\r\nAuthorization: Bearer TOKEN\r\nAccept: application/vnd.allegro.public.v1+json\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: api.allegro.pl\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "expires: 0\r\n"
-> "cache-control: no-cache, no-store, max-age=0, must-revalidate\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "pragma: no-cache\r\n"
-> "x-frame-options: DENY\r\n"
-> "trace-id: 4d43597ade9ced55\r\n"
-> "date: Thu, 09 Sep 2021 09:24:42 GMT\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "content-type: application/vnd.allegro.public.v1+json\r\n"
-> "content-length: 38\r\n"
-> "connection: close\r\n"
-> "\r\n"
reading 38 bytes...
-> "{\"offers\":[],\"count\":0,\"totalCount\":0}"
read 38 bytes
Conn close
```

**Comment by MartaNowaczyk** [comment]
Wygląda na to, że na tym koncie nie ma ofert, stąd pusta tablica.

**Comment by gscoders** [comment]
Na 100% oferty są ponieważ jest to nasz główny sklep, który funkcjonuje od kilku lat i też na pewno została autoryzowana aplikacja z tego konta Allegro.

**Comment by MartaNowaczyk** [comment]
Rozkoduj token i sprawdź. W każdym razie jak chcesz, możesz podesłać poprawne konto tutaj, albo przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) z dopiskiem GitHub #4909. Sprawdzę czy to to samo, co widzę w naszych logach.

**Comment by wojciech-rzepecki** [comment]
Czy ```user_name``` w JWT to jest to samo co otrzymuję pod linkiem https://allegro.pl/login/user jako ```userId```?

**Comment by MartaNowaczyk** [comment]
Tak, to jest to samo.

**Comment by wojciech-rzepecki** [comment]
Wysłałem przez formularz kontaktowy wiadomość ze wskazanym dopiskiem, proszę o weryfikację.

**Comment by MartaNowaczyk** [comment]
Ok, dzięki za informację. Jak przekażą mi dane na pewno zweryfikuję.

**Comment by wojciech-rzepecki** [comment]
Już 3 razy dostajemy taką odpowiedź na wysłane wcześniej zgłoszeni
![allegro](https://user-images.githubusercontent.com/90463267/134819298-7fba1e39-7a6e-4801-bb7a-94f4106a83c1.png)
Czy da się coś z tym zrobić?

**Comment by MartaNowaczyk** [comment]
To na pewno jakieś nieporozumienie. Rozumiem, że podałeś tam login konta, którego to dotyczy?

**Comment by wojciech-rzepecki** [comment]
@MartaNowaczyk napisałem zgłoszenie będąc zalogowanym na koncie którego to dotyczy

**Comment by MartaNowaczyk** [comment]
ok, pewnie nie wiedzieli co mi przekazać. Postaram się to wyjaśnić.
