### ISSUE TITLE
Can't create new offer draft with POST https://api.allegro.pl.allegrosandbox.pl/sale/offers

### ISSUE THREAD

**Issue by Pirotechnic** [allegro/allegro-api#4912]
First I tried to create an offer draft on a real platform (api.allegro.pl): web UI led me to an activation through payment page and attempts of passing this activation led to a page, that stated, that selling account is active. That behaviour appears every time I try to create a new offer through web UI. Then I added an application to my account and created a program, that can get the bearer token and do GET requests to Allegro API, but all the attempts of doing command POST https://api.allegro.pl/sale/offers ended up with this response:
{""errors"":[{""code"":""AccessDeniedException"",""message"":""Client is not allowed for execute this command"",""details"":""AccessDeniedException"",""path"":""/sale/offers"",""userMessage"":""Client is not allowed for execute this command""}]}

After that, I created a sandbox account, found the seller account activation option, passed the activation through payment simulation and tried to create an offer draft there, with both: web UI and program, that works with API.
Web UI returns a page with error:
"This site can’t be reached
The webpage at https://staging-lokalnie.allegrogroup.com/oferty/wystaw might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED".
Program returns the same response to request as in case of the real platform.

In my program I use WinHTTPRequest.5.1 with "POST" command, URL https://api.allegro.pl/sale/offers (or https://api.allegro.pl.allegrosandbox.pl/sale/offers in case of sandbox), three headers:
1) "Authorization": "Bearer <BearerToken>"
2) "Accept": "application/vnd.allegro.public.v1+json"
3) "Content-Type": "application/vnd.allegro.public.v1+json",
and body: {"name": "Oferta testowa"}

Can anyone tell me, what am I missing?

**Comment by MartaNowaczyk** [comment]
We have the following options:
1. You are using "bearer-token-for-application" authorization like client_credentials but POST /sale/offers requires "bearer-token-for-user" authorization. To create an offer draft, you need to authorize a code or device flow - we describe it in [our guide](https://developer.allegro.pl/en/auth/).
2. You are using the wrong token and trying to download offers that do not belong to you.

Check it and if you still have problems send the trace-id for verification.

> Web UI returns a page with error:
"This site can’t be reached
The webpage at https://staging-lokalnie.allegrogroup.com/oferty/wystaw might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED".

 Please use the direct link: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

**Comment by Pirotechnic** [comment]
Thank you for the previous response! I really have been using "bearer-token-for-application" authorization and now I changed the flow to "Device flow - user authorization" and it worked for POST request.
Can you help me with another one? I am trying to PATCH changes to an active offer (still in sandbox), but the response to request says:
401, {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
My program does next things one after another:
1. authorization via Device flow (obtaining access token) - successful
2. getting main categories - successful
3. getting data from existing offer - successful
4. setting available stock by PATCH request - fails with the error, mentioned above.

For PATCH request I use {"Accept": "application/vnd.allegro.beta.v2+json"} header, because {"Accept": "application/vnd.allegro.public.v1+json"} returns an error:
406, {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"The request contains incorrect data. Contact the author of the application."}]}

Any ideas, what am I doing wrong?

**Comment by Pirotechnic** [comment]
Nevermind, that was my mistake in an authorization header.
