### ISSUE TITLE
Oferty połączone z produktem w API 

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4913]
Powiedzmy, że mam 2 tysiące ofert. 
Allegro oczekuje ode mnie 70% ofert połączonych z produktem. 

**Program**, który kontroluje oferty po mojej stronie, **musi wiedzieć, które oferty są połączone z produktem**, a które nie... 
W jaki sposób ten program **przez API** może uzyskać taką informację? 

Odpowiedź z zasobu `https://api.allegro.pl/sale/offers` nie zawiera informacji o produkcie. 
Czy program **musi wysłać 2 tysiące zapytań o każdą ofertę** przez `https://api.allegro.pl/sale/offers/nr-oferty` aby ustalić, które z tych moich 2 tysięcy ofert nie są jeszcze połączone, albo zostały rozłączone po weryfikacji?

**Comment by MartaNowaczyk** [comment]
Dla GET /sale/offers nie zwracamy ID produktu, ale mamy filtr, który pozwoli otrzymać listę ofert, które nie są połączone z produktem. Możesz użyć GET /sale/offers?product.id.empty=true. Do tego możesz skorzystać jeszcze z innych filtrów, aby ograniczyć listę ofert np. do danej kategorii czy statusu oferty. Wszystkie filtry opisaliśmy [w poradniku](https://developer.allegro.pl/my_offers/#jak-pobra%c4%87-moje-oferty-w-rest-api).

**Comment by leszekdubiel** [comment]
Celem jest zrobienie raportu, gdzie są oferty Allegro z parametrami. Jednym z tych parametrów jest czy oferta jest połączona z produktem. 

Algorytm będzie taki: 

-- wiele razy pytam o listę ofert, strona za stroną (bo jest stronicowanie) 
-- następnie znowu wiele razy pytam, aby odfiltrować tyle te, które mają  "product.id.empty=true"

Czy jest szansa, że ktoś doda informację do /sale/offers (bez dodatkowego filtrowania)?

**Comment by MartaNowaczyk** [comment]
Dzięki za dodanie [sugestii](https://github.com/allegro/allegro-api/discussions/4920), dzięki temu sprawdzimy jak jest potrzeba wprowadzenia takiej zmiany.
