### ISSUE TITLE
Allegro One Fullfilment

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#4914]
Witam.
Klient zwrócił się do nas o integrację. Z tego co widzę to w news'ach nie było jeszcze wpisu o udostępnieniu API. Czy wiadome są jakieś terminy udostępnienia API do Allegro Fullfilment? Czy w ogóle będzie można taką integrację stworzyć dla naszego klienta?

**Comment by MartaNowaczyk** [comment]
Planujemy udostępnić API dla Allegro Fullfilment, ale na tę chwilę nie możemy wskazać konkretnej daty. Jak będziemy mieć takie informacje, na pewno poinformujemy o tym w oddzielnym komunikacie.

**Comment by troncomputers** [comment]
Z tego co się orientuje, to system jeszcze nie pracuje prawda? Czy ci, którzy zapisali się do tego projektu mają już jakiś dostęp do paneli zarządzających tą usługą?

**Comment by MartaNowaczyk** [comment]
Nie, jeszcze nie. Jak będzie taka możliwość na pewno damy znać.

**Comment by troncomputers** [comment]
Dzięki za info ✌
