### ISSUE TITLE
Jak pobrać listę wystawionych ofert z filtrem delivery.handlingTime

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4917]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [X ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry, 

Czy jest jakaś możliwość pobrania listy wystawionych ofert z ustalonym czasem dostawy np.  = **PT168H** ?
Próbowałem GET/sale/offers?delivery.handlingTime=**PT168H** ale zwraca pełną listę , tak jakby ten filtr ignorował.

Z drugiej strony pobierając listę ofert wystawionych nie otrzymujemy tego parametru na liście wiec tez nie można tego przefiltrować po własnej stronie w efektywny sposób.

Jest na to jakieś rozwiązanie bez odpytywania wszystkich 30 tyś ofert ? :)

**Comment by PrzemyslawLukanowski** [comment]
Nie umożliwiamy filtrowania wg tego parametru, wszelkie pozostałe query parametry dla tego endpointu znajdziesz w [naszej dokumentacji](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Nie ma niestety sposobu, aby za pomocą jednego requestu pobrać oferty tylko z określonym delivery.handlingTime.

**Comment by Waclaw-W** [comment]
Bardzo dziękuję za szybką odpowiedź.

Pozdrawiam
