### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by EwaF** [allegro/allegro-api#492]
Witam,
czy mogłabym prosić o kontakt do działu zajmującego się aktywacją kont w allegro sandbox?

**Comment by MaciejPotepa** [comment]
Dzień dobry
Trafiła Pani do takiego działu. W czym pomóc?

**Comment by EwaF** [comment]
W piątek wysłałam prośbę o aktywację konta testowego, jednak nadal nie dostałam wiadomości. Mogłabym prosić o aktywację? Niestety jest to temat dość pilny.

**Comment by MaciejPotepa** [comment]
Możemy aktywować konto, nie ma problemu - tylko potrzebny jest login.

**Comment by MaciejPotepa** [comment]
Aktywowałem konto.

**Comment by EwaF** [comment]
Dziękuję, jednak dalej wszystko bez zmian...

**Comment by MaciejPotepa** [comment]
Teraz powinno być okay. Przepraszam za problem.

**Comment by EwaF** [comment]
Dziękuję bardzo za pomoc!
