### ISSUE TITLE
Uszkodzone załączniki w wiadomościach nadanych do Centrum Wiadomości przez REST API

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4921]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry,

wykryłem problem z załącznikami nadanymi z wiadomościami przez REST API. Kiedy ktoś chce pobrać dołączony do wiadomości załącznik, otrzymuje plik zawierający na początku nieznany nam nagłówek:

```
-------------------------------28947758029299
Content-Disposition: form-data; name="file"; filename="13.9.2021-12x7x59x100-17.jpg"
Content-Type: application/x-gzip

```

Nagłówek ten powoduje, że klienci nie mogą otworzyć pliku. Poniżej tego nagłówka jest właściwa treść pliku. Usunięcie nagłówka powoduje, że plik jest ponownie możliwy do odczytu. Jestem pewien, że wysyłam zdjęcia z poprawnym `Content-Type` dla pliku JPEG: `image/jpeg`. Nawet nie zakodowałem możliwości wykorzystania archiwum gzip, plik oryginalny znaleziony na serwerze też nie posiada tego nagłówka. 

Wszystko wskazuje na to, że to proces przetwarzania załączników w REST API miesza w treści plików i wywołuje problemy. Zdjęcia dodane jako załączniki na portalu są poprawne.

Proszę o pomoc.

**Comment by hahyes** [comment]
Postanowiłem sprawdzić, czy pobierając załączniki z REST API otrzymam taki sam efekt i rzeczywiście, linki z domeny `upload.allegro.pl` prowadzą do plików nadpisanych w ten sam sposób. Przykład uszkodzonych załączników z wiadomości poniżej:

```
      "attachments": [
        {
          "fileName": "13.9.2021-12x7x59x100-17.jpg",
          "mimeType": "image/jpeg",
          "url": "https://upload.allegro.pl/message-center/message-attachments/1cd36ddd-9223-4e54-9bae-67744937dbc1",
          "status": "SAFE"
        },
        {
          "fileName": "13.9.2021-12x7x18x710-17.jpg",
          "mimeType": "image/jpeg",
          "url": "https://upload.allegro.pl/message-center/message-attachments/6f91b29a-cc65-4523-81ed-af1cef5ace33",
          "status": "SAFE"
        },
        {
          "fileName": "13.9.2021-12x7x40x878-17.jpg",
          "mimeType": "image/jpeg",
          "url": "https://upload.allegro.pl/message-center/message-attachments/70d31f6b-9014-4579-a678-7282c27d9158",
          "status": "SAFE"
        },
        {
          "fileName": "13.9.2021-12x8x13x926-17.jpg",
          "mimeType": "image/jpeg",
          "url": "https://upload.allegro.pl/message-center/message-attachments/7474819a-f6c1-4bdd-993f-8cca53bdd554",
          "status": "SAFE"
        },
        {
          "fileName": "13.9.2021-12x8x43x479-17.jpg",
          "mimeType": "image/jpeg",
          "url": "https://upload.allegro.pl/message-center/message-attachments/ee06701a-46ae-427e-acf6-4beb4167dff1",
          "status": "SAFE"
        }
      ]
```

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego błędu, załączniki za każdym razem są prawidłowe. Czy możesz przesłać nam przykładowy oryginalny załącznik za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)? Opisz proszę także całe flow dla obsługi załączników - z jakiej technologii korzystasz, dodaj także requesty (uwzględniające nagłówki) oraz response'y. Dopisz, że dane dotyczą wątku #4921 na GitHubie.

**Comment by hahyes** [comment]
> Opisz proszę także całe flow dla obsługi załączników - z jakiej technologii korzystasz, dodaj także requesty (uwzględniające nagłówki) oraz response'y. Dopisz, że dane dotyczą wątku #4921 na GitHubie.

Wysłałem zgłoszenie przez formularz, wyklikałem ręcznie zamiast użyć url podanego tutaj ale to chyba nie powinien być problem, jeżeli podałem numer wątku na Githubie.

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie, jeśli podałeś numer wątku, zgłoszenie do nas trafi.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Udało mi się znaleźć problem po mojej stronie. Okazuje się, że metoda biblioteki, z której korzystałem, dodawała sama z siebie nagłówek, o czym nie miałem pojęcia. Tym samym zamykam wątek i pozdrawiam. ;)

**Comment by PrzemyslawLukanowski** [comment]
Super, cieszę się, że udało się rozwiązać problem :)

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Chociaż z drugiej strony nie jestem do końca pewien, czy to na pewno biblioteka. Jednak z pewnością mogę stwierdzić, że dodanie bajtów jako parametr do zapytania typu request body, dało poprawnie wysłany plik w REST API. Teoretycznie nie powinno być problemu dla API z obsługą tego zapytania i nie widzę, żeby bilioteka w obiekcie z automatu modyfikowała bajty zdjęcia. Chyba, że API odbiera bezpośrednie pliki w zapytaniu inaczej, niż te z parametrów. Wtedy byłby problem.
