### ISSUE TITLE
Problem z zasobem sale/product-proposals

### ISSUE THREAD

**Issue by Atospl** [allegro/allegro-api#4923]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Dzień dobry, mam problem z zasobem "sale/product-proposals". Po wykonaniu zapytania POST o trace-id: d32c259480629805
z danymi w formie:

`
{
	"name": "Tajemnica generała Samsonowa",
	"category": {
		"id": "89274"
	},
	"images": [
		{
			"url": "https://a.allegroimg.com/original/115d7a/a67317ea431d8485cf80f605f621"
		}
	],
	"parameters": [
		{
			"id": "11323",
			"valuesIds": [
				"11323_1"
			]
		},
		{
			"id": "245669",
			"valuesLabels": [
				"9788396082503"
			],
			"values": [
				"9788396082503"
			],
			"options": {
				"identifiesProduct": true,
				"isGTIN": true
			}
		},
		{
			"id": "223545",
			"values": [
				"Tajemnica generała Samsonowa"
			]
		},
		{
			"id": "223489",
			"values": [
				"Sławomir Ambroziak"
			]
		},
		{
			"id": "75",
			"valuesIds": [
				"75_1"
			]
		},
		{
			"id": "74",
			"values": "2021"
		},
		{
			"id": "223541",
			"valuesIds": [
				"223541_312925"
			]
		}
	],
	"description": {
		"sections": [
			{
				"items": [
					{
						"type": "TEXT",
						"content": "<h1>Tajemnica generała Samsonowa</h1>"
					}
				]
			},
			{
				"items": [
					{
						"type": "IMAGE",
						"url": "https://a.allegroimg.com/original/115d7a/a67317ea431d8485cf80f605f621"
					}
				]
			},
			{
				"items": [
					{
						"type": "TEXT",
						"content": "<p>Co tak naprawdę wydarzyło się w sierpniową noc 1914 r. w podwielbarskim lesie, kiedy to po przegranej bitwie pod Tannenbergiem carski generał Aleksander Samsonow wraz z towarzyszami próbował przedostać się przez granicę? Dlaczego w Rosji tragiczne losy dowódcy armii „Narew” stały się niewygodnym tematem? Jak wyglądały ostatnie chwile generała i czy rzeczywiście popełnił on samobójstwo? Odpowiedzi na te i inne pytania można znaleźć w najnowszej książce Sławomira Ambroziaka „Tajemnica generała Samsonowa” wydanej przez Mazurskie Stowarzyszenie Regionalne. Licząca 380 stron publikacja nie jest typowym historycznym opracowaniem. Autor z niemal detektywistycznym zacięciem i pasją szuka odpowiedzi na nurtujące go pytania. Pracując nad książką, dotarł do wielu nieznanych dotąd dokumentów, relacji i opisów. Odwiedził też miejsca związane z jej bohaterami. Na szczególną uwagę zasługują fragmenty będące reporterskim zapisem dwóch podróży na Ukrainę, w rodzinne strony Samsonowa.</p>"
					}
				]
			},
			{
				"items": [
					{
						"type": "TEXT",
						"content": "<ul>  <li>Autor: Sławomir Ambroziak,</li>  <li>Wydawnictwo: Mazurskie Stowarzyszenie Regionalne,</li>  <li>Kod kreskowy: 9788396082503</li></ul>"
					}
				]
			}
		]
	}
}
`
API odpowiada mi kodem HTTP 400 z komunikatem:
`
{
	"errors": [
		{
			"code": "HttpMessageNotReadableException",
			"message": "An error has occurred",
			"details": null,
			"path": null,
			"userMessage": "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."
		}
	]
}
`
Od kilku godzin zachodzę w głowę czym różnią się wyżej podane dane od zamieszczonego w tutorialu (https://developer.allegro.pl/productization/#5-jak-doda%c4%87-produkt)  przykładu i byłbym wdzięczny za pomoc, gdyż wszystkie obowiązkowe pola są tu wypełnione.

**Comment by PrzemyslawLukanowski** [comment]
Wartość w parametrze 74 przekazujesz poza tablicą, powinno być:

```
           {
		"id": "74",
		"values": ["2021"]
           }
```

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, poprawimy oczywiście przykład na naszej stronie.

**Comment by Atospl** [comment]
Serdecznie dziękuję :)
