### ISSUE TITLE
Kampanie - jak pobrać listę aktywnych aukcji w Strefie Okazji

### ISSUE THREAD

**Issue by C05m0s** [allegro/allegro-api#4925]
Po nowych zmianach dotyczących Kampanii (badges) uległ sposób zmiany cen. Aby można było zmienić cenę aukcji w Strefie Okazji potrzebna jest wiedza o offer.id.

**W jaki sposób można pobrać listę aukcji w Strefie Okazji, które nie zostały dodane przez api,  aby można było im zmieniać ceny?**

Mówimy o aukcja które są w Strefie Okazji przed wprowadzeniem kampanii (badges) w api. Te aukcje były wskazane ręcznie z poziomu panelu allegro.

/sale/badges nie zwraca na listingu aukcji jeśli nie zostały one wcześniej przez API dodane do kampanii. Znając jednak offer.id nie ma problemu ze zmianą cen.  
/offers/listing nie jest otwarty dla wszystkich

Na chwilę obecną najszybszą (jedyną?) metodą jest scrubbing listingu strony Allegro z odfiltrowanymi wynikami. 

Jednocześnie, jak dobrze rozumiem, nie można anulować aukcji w kampanii Strefa Okazji i ponownie jej włączyć przez API , gdyż każde wyłączenie wiąże się z "karami" (?)

**Comment by PrzemyslawLukanowski** [comment]
> W jaki sposób można pobrać listę aukcji w Strefie Okazji, które nie zostały dodane przez api, aby można było im zmieniać ceny?
> /sale/badges nie zwraca na listingu aukcji jeśli nie zostały one wcześniej przez API dodane do kampanii. 
> 

Sprawdziłem to i przez GET /sale/badges możesz pobrać wszystkie oferty, także te, które nie zostały dodane przez API. O tym, że prawidłowo przypisaliśmy ofertę do kampanii, świadczy wartość "ACTIVE" w polu process.status.

> Jednocześnie, jak dobrze rozumiem, nie można anulować aukcji w kampanii Strefa Okazji i ponownie jej włączyć przez API , gdyż każde wyłączenie wiąże się z "karami" (?)

Z technicznego punktu widzenia jest to możliwe, jednak zgodnie z punktem [V.3 regulaminu Strefy Okazji](https://allegro.pl/regulaminy/regulamin-strefy-okazji-9dGVAPB69In) - jak wspomniałeś - mogą zostać naliczone kary. Jeśli masz jakieś wątpliwości co do tego punktu, zadaj proszę pytanie poprzez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?kategoria=0b6a5987-d763-4373-9f9e-145bafafc022&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372) - jest to temat już wykraczający poza API.

**Comment by C05m0s** [comment]
Dzięki za szybką odpowiedź. 
Siadam zatem ponownie to weryfikacji wyników z /sale/badges

**Comment by C05m0s** [comment]
Musiałem zatem robić błąd przy wywołaniu. 
Potwierdzam, że dane są zwracane.
