### ISSUE TITLE
Jak rozpoznać zdarzenie typu "sprzedawca anulował zamówienie" w dzienniku pozakupowym?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4926]
Dzień dobry,

zajrzałem do poradnika oraz dokumentacji, ale nie znalazłem odpowiedzi na nurtujące mnie pytanie.

Chciałbym wiedzieć, jak mogę rozpoznać w dzienniku zdarzeń sytuację, kiedy to sprzedawca anuluje zamówienie własnoręcznie? Nie widzę odpowiedniego rodzaju zdarzenia dla takiej sytuacji. Czy powinienem w jakiś sposób kierować się zdarzeniem `FULFILLMENT_STATUS_CHANGED` i w jego wypadku sprawdzać zamówienie, czy zostało ono akurat anulowane?

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Sprzedawca sam nie może anulować zamówienia, tzn. może zmienić status realizacji na "ANULOWANE" i w tym przypadku - tak jak napisałeś - możesz sugerować się statusem `"FULFILLMENT_STATUS_CHANGED"`. To kupujący może anulować zamówienie i wtedy zwrócimy zdarzenie `"BUYER_CANCELLED"`. Inny przypadek to, gdy automatycznie anulujemy zamówienie, kiedy kupujący wybierze płatność z góry i nie opłaci swojego zamówienia w wyznaczonym czasie, czyli:
- po 7 dniach – w przypadku zakupu w opcji kup teraz
- po 30 dniach – w przypadku zakupu w licytacji.

Wtedy otrzymasz zdarzenie `"AUTO_CANCELLED"`.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Dziękuję za odpowiedź i pozdrawiam. :)
