### ISSUE TITLE
Wysyłam z Allegro: API nie zwraca niektórych usług

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#4927]
Dzień dobry

Mam dwa pytania związane z API (Wysyłam z Allegro).

1. Od 6 września powinna być dostępna usługa **Allegro DPD Pobranie**, również dla kont bez umowy z DPD.

Jednak okazuje się, że API nadal nie zwraca tej usługi, sprawdzone na kilku różnych kontach:

https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices

Co należy zrobić, aby mieć dostęp do tej usługi w API?

2. Druga sprawa, to usługa Poczty Polskiej, nasz klient chce nadać przesyłkę poleconą, ale API nie zwraca usługi dodatkowej "Przesyłka polecona firmowa".

pozdrawiam

**Comment by mmodrzejewski** [comment]
Odnośnie punktu numer 2.
Czy dla listu poleconego nazwa usługi dodatkowej to nie jest czasem :
**Nadawanie przesyłek poleconych za potwierdzeniem odbioru**
 (`registeredCompanyLetter`)
?

**Comment by PrzemyslawLukanowski** [comment]
Konsultuję to jeszcze z zespołem odpowiedzialnym za funkcjonalność. Wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Co do drugiego pytania - tak, to będzie `registeredCompanyLetter`. Konsultuję jeszcze pierwszy problem.

**Comment by mmodrzejewski** [comment]
Dzień dobry. Czy coś w tej sprawie już wiadomo?

**Comment by mmodrzejewski** [comment]
Dzień dobry.

Podbijam temat, problem dalej nie został rozwiązany - API wciąż nie zwraca: "Allegro DPD Pobranie" 
dla klientów bez umowy.

Czy poprawka jest nadal w drodze?

**Comment by PrzemyslawLukanowski** [comment]
Tak, jeszcze nad tym pracujemy. Poinformuję w wątku po wdrożeniu poprawki.

**Comment by CF-WR617AC** [comment]
Nie można się doczekać na poprawki od ALlegro, sami już mamy swoje poprawki, działa z DPD pobranie oraz UPS pobranie:

https://forum.insert.com.pl/index.php?/topic/70806-nie-mo%C5%BCesz-ustawi%C4%87-dpd-pobranie-w-wza-rozwi%C4%85zanie/&tab=comments#comment-358206

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy poprawkę, w usłudze dostawy Allegro DPD zwracamy:

```
 "additionalServices": {
                "cashOnDelivery": {
                    "available": true,
...
```

**Comment by CF-WR617AC** [comment]
Tak, jest wreszcie faktynie widać teraz w DPD i UPS. Kiedy zrobicie status MINIPACZKI dla ORLEN nadawanego w punktach LEWIATAN ?

**Comment by PrzemyslawLukanowski** [comment]
Jak tylko uda nam się to ustalić, odpowiedzi udzielimy w wątku #5048.
