### ISSUE TITLE
błąd /parcel-management/parcel-create-commands

### ISSUE THREAD

**Issue by apriaszpatryk** [allegro/allegro-api#4928]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Witam,
mam problem z utworzeniem paczki za pomocą rest api. Zwracany jest błąd:
{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error","details":null,"path":"/parcel-management/parcel-create-commands/e3f4871e-0c81-4b0b-bc4c-caae1568fb23","userMessage":"Nieprawidłowa treść żądania JSON"}]}

Niestety api nie zwróciło konkretnego błędu. Czy mógłbym prosić o wskazówkę gdzie go szukać?

**Comment by PrzemyslawLukanowski** [comment]
W `dimensions `przekazujesz pustą tablicę, a powinieneś obiekt z konkretnymi wymiarami paczki. Czyli zamiast:

`"dimensions": [],`

Przekaż np.

```
	"dimensions": {
            "height": {
                "value": 20,
                "unit": "CENTIMETER"
            },
            "width": {
                "value": 20,
                "unit": "CENTIMETER"
            },
            "depth": {
                "value": 20,
                "unit": "CENTIMETER"
            }
        },
```

**Comment by apriaszpatryk** [comment]
Ok, dzięki za informację.
