### ISSUE TITLE
Wysyłam z Allegro - pobranie protokołu

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#4929]
Witam,
w jakim przypadku przy pobieraniu protokołu dla wysyłam z allegro zwracany jest status:
204 No Protocol For Given Parcels 

Inaczej jakie warunki muszą być spełnione, żeby pobrać protokół dla przesyłki?

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za długi czas oczekiwania na odpowiedź, ale konsultuję jeszcze tę kwestię z zespołem odpowiedzialnym za usługę Wysyłam z Allegro. Wrócę z informacją, gdy otrzymam odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Taki status otrzymasz, jeśli dany przewoźnik nie udostępnia protokołów dla przesyłek. Nie zwracamy protokołów np. dla metody dostawy "Allegro Punkty".
