### ISSUE TITLE
Produkt Ean 5905241042022 -- dziwny wynik

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4932]
Jeśli do wyszukiwarki Allegro wpiszę "5905241042022", to znajduje produkt. 
Zapytanie 

```
https://api.allegro.pl/sale/products?ean=5905241042022
```

niestety nie zwraca tego produktu. 
Dlaczego? 

Trace-id zapytania:    

```
trace-id 6a29b73425092359
```

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że masz na myśli wyszukiwarkę ofert na stronie. Jej działanie nie jest tożsame z wyszukiwarką produktów GET /sale/products. Zwrócona oferta nie jest powiązana z żadnym produktem, a w wynikach widnieje dlatego, ponieważ sprzedawca uzupełnił wartość 5905241042022 w parametrze EAN.
