### ISSUE TITLE
Delivery update nie zwraca błędów, ale nie zmienia również wartości

### ISSUE THREAD

**Issue by SylwesterEjkszto** [allegro/allegro-api#4934]
Updatuje kilka parametrów jednocześnie, request przechodzi nie zwraca żadnego błędu  i zmienia wszystkie parametry poza delivery, probowałem również zmienić samo delivery - bezskutecznie, ciągle dostaje zwrot delivery : none

https://pastebin.com/q9MHdnAS  - przykładowy json

**Comment by PrzemyslawLukanowski** [comment]
Uzupełnij proszę także pole `"location"`, walidacja tych pól jest ze sobą powiązana, dlatego w Twoim przypadku nie następuje update  wartości w `"delivery"`.

**Comment by SylwesterEjkszto** [comment]
{"city":"Olsztyn","countryCode":"PL","postCode":"10-166","province":"Warmińsko-Mazurskie"}

Mógłbym prosić o listę wartości które są przyjmowane np. w province?  Probowałem wysłać dane jak wyżej - z takim wynikiem:
 {'code': 'VALIDATION_ERROR', 'message': 'Invalid state null for country PL', 'details': '', 'path': 'location.state', 'userMessage': 'Wskazane województwo jest nieprawidłowe.'}]

**Comment by asoio** [comment]
Z dokumentacji (https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST):
province | string  <= 50 characters
This  field is mandatory if countryCode is set to "PL", for other values,  currently, it is ignored. For countryCode equalling "PL", this field  must be set to one of the following: DOLNOSLASKIE, KUJAWSKO_POMORSKIE,  LUBELSKIE, LUBUSKIE, LODZKIE, MALOPOLSKIE, MAZOWIECKIE, OPOLSKIE,  PODKARPACKIE, PODLASKIE, POMORSKIE, SLASKIE, SWIETOKRZYSKIE,  WARMINSKO_MAZURSKIE, WIELKOPOLSKIE, ZACHODNIOPOMORSKIE.
