### ISSUE TITLE
Generowanie Tokenu, błąd serwera.

### ISSUE THREAD

**Issue by M4GiK** [allegro/allegro-api#4937]
Bardzo bym prosił o podesłanie loga dotyczącego numeru błędu: 881038392532e704 na środowisku produkcyjnym. 
Błąd występuje tylko podczas korzystania ze środowiska na systemie operacyjnym mac os.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować, w którym momencie autoryzacji otrzymujesz ten błąd? Co dokładnie otrzymujesz w odpowiedzi? Czy jest to etap generowania 10-sekudowego kodu, a komunikat błędu wygląda podobnie jak niżej?

![auth](https://user-images.githubusercontent.com/51473661/133735782-c2ba6144-202c-44cb-9fe6-c4ac0a89c6d5.png)

Jeśli tak - upewnij się, że adres, który przekazujesz w parametrze redirect_uri, jest zgodny z adresem przekierowania, który podałeś na stronie https://apps.developer.allegro.pl/.

**Comment by M4GiK** [comment]
Wygląda dokładnie tak, na przekierowaniu wyrzuca błąd (redirect-uri się zgadza)  więc za bardzo nie jestem w stanie stwierdzić na jakim etapie jest problem. Nie wiem czy to jest istotne aplikacja na systemie w Windowsem śmiga bez błędów. Zanim zacznę grzebać w politykach bezpieczeństwa, chciałem wiedzieć co jest w logach błędu.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy nasze logi, według nich nie podajesz wartości w parametrze client-id.

**Comment by M4GiK** [comment]
Dziękuję. Mea culpa.
