### ISSUE TITLE
API Allegro Ads

### ISSUE THREAD

**Issue by reqv** [allegro/allegro-api#4941]
Cześć, w dokumentacji widnieje informacja, że to API ma status zamkniętej bety. Czy są jakieś konkretne plany odnośnie wydania tego API? Ewentualnie, czy można się jakoś do tej bety zapisać?

Zależy mi głównie na pobieraniu statystyk kampanii.

**Comment by AureliuszBrussy** [comment]
Aktualnie nie ma możliwości uzyskania dostępu do tych zasobów. Jeżeli w przyszłości podjęta zostanie decyzja o ich upublicznieniu, to na pewno poinformujemy o tym w osobnym komunikacie na forum oraz w [aktualnościach](https://developer.allegro.pl/news/) na portalu.

**Comment by reqv** [comment]
Dzięki za odpowiedź
