### ISSUE TITLE
Wysyłam z Allegro // Allegro DPD pobranie // przelew zbiorczy - zestawienie CSV

### ISSUE THREAD

**Issue by AleksyZajac** [allegro/allegro-api#4944]
Dzień dobry,
czy jest możliwość wygenerowania zestawienia do przelewu zbiorczego z pobrań (Allegro DPD pobranie)?

Chciałbym wiedzieć które zamówienia zostały opłacone danym przelewem zbiorczym.

Pozdrawiam,
Aleksy

**Comment by AureliuszBrussy** [comment]
W API nie udostępniamy takiej możliwości. Jeżeli chodzi o możliwości narzędzia https://wysylam.allegro.pl/ - skieruj proszę pytanie poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5).

**Comment by CF-WR617AC** [comment]
Dołączę się do zapytania. Rozliczanie przelewów z WzA jest coraz trudniejsze.

**Comment by CF-WR617AC** [comment]
![image](https://user-images.githubusercontent.com/84842730/137702372-16e7a0e3-f8fe-403c-8885-281bd4783b4c.png)
