### ISSUE TITLE
Pobieranie zamówień na podstawie zasobu /order/checkout-forms

### ISSUE THREAD

**Issue by ham3r** [allegro/allegro-api#4946]
Dzień dobry,

piszą Państwo, że zalecaną metodą pobierania najnowszych zamówień jest użycie dziennika zdarzeń.
https://developer.allegro.pl/orders/#lista-zam%c3%b3wie%c5%84

1. Czy uwaga o polu `boughtAt` jest aktualna, jeżeli dla zasobu `/order/checkout-forms` jest możliwe sortowanie po polu `updatedAt`?

2. Czy pobranie zamówień przez...
* dziennik zdarzeń (z parametrem `from`), a potem pojedynczo przez `/order/checkout-forms/:id`
oraz
* /order/checkout-forms/ (z parametrem filtrowania ` updatedAt.gte` i sortowania `updatedAt`)

...jest odwzorowane 1:1?

A może jednak są pewne niuanse, może czegoś brakuje, może coś jest pomijane, przez co korzystanie z `/order/checkout-forms` jest niewłaściwe?

Pozdrawiam!

**Comment by AureliuszBrussy** [comment]
Oparcie logiki o sortowanie po `updatedAt` może sprawić, że np. zgubisz zamówienia. Nie gwarantujemy, że zamówienia będą pojawiać się idealnie wg kolejności pola `updatedAt`.

Potencjalna sytuacja obrazująca problem:
- pojawia się zamówienie nr 1 z updatedAt = 10,
- pobierasz zamówienia od daty = 0 (robisz to po raz pierwszy),
 - zwrócimy jedno zamówienie z datą 10,
- w tym momencie pojawia się także drugie zamówienie, jednak z updatedAt = 9,
- pobierasz zamówienia od ostatniej daty updatedAt ze swojej perspektywy, czyli od 10,
- zwracamy pustą pustą listę, mimo, że w międzyczasie pojawiło się inne zamówienie z datą updatedAt = 9.

Dlatego też zalecamy korzystanie z dziennika zdarzeń - wtedy masz pewność, że nie pominiesz żadnego zamówienia.

**Comment by ham3r** [comment]
Rozumiem. A co jeżeli pobieramy większą liczbę zamówień (np. milion), co może mieć bezpośrednio wpływ na liczbę requestów?

Jeżeli rzeczywiście istnieje taki problem, to czy widzicie Państwo jakieś przeciwwskazania, aby podejść do sprawy hybrydowo, tj. zaciągać dziennik zdarzeń i zamówienia z `/order/checkout-forms`, a następnie różnicę uzupełnić pojedynczo przez `/order/checkout-forms/:id`?

Takie podejście, moim zdaniem ,wygląda sensownie i pozwala wyłapać braki w zamówieniach.

**Comment by AureliuszBrussy** [comment]
@ham3r być może będzie to dobre rozwiązanie, tutaj rozbija się to już o szczegóły implementacji.
