### ISSUE TITLE
Metody płatności

### ISSUE THREAD

**Issue by Marika-CCC** [allegro/allegro-api#4947]
Chciałabym uzyskać informację czy możemy po API otrzymywać dane o tym jaką klient wybrał metodę płatności (Allegro Pay, przelew, BLIK, etc.)?

**Comment by AureliuszBrussy** [comment]
Nie, zwracamy tylko informacje kto był operatorem danej płatności w polu payment.provider. Możliwe wartości to: P24", "PAYU", "OFFLINE", "EPT".
