### ISSUE TITLE
Jak automatycznie poprawić błąd - ConstraintViolationException.ValidProduct

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4949]
Jak w tytule:

```
ConstraintViolationException.ValidProduct with message Wybrany produkt nie istnieje. / Wybrany produkt nie istnieje.
```

Problem dotyczy w tej chwili około 60 tys ofert i licznik wygląda że ciągle idzie do góry

Jak automatycznie poprawić ten błąd? W tej chwili nie możemy zmienić ceny / aktywować ofert.

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać kilka przykładowych trace-id, gdzie taki błąd wystąpił? Sprawdzę to dokładniej.

**Comment by pliszka** [comment]
o które trace-id chodzi?

1. te które otrzymuję przy próbie wykonania "PUT /sale/offer-publication-commands/{commandId}" lub "PUT /sale/offer-price-change-commands/{commandId}" 
2. te które otrzymuję przy GET /sale/offer-publication-commands/{commandId} ( o ile tam w ogóle trace-id występuję ) 
3. te które otrzymuję przy GET /sale/offer-publication-commands/{commandId}/tasks ( o ile tam w ogóle trace-id występuję )

**Comment by MartaNowaczyk** [comment]
W odpowiedzi wszystkich tych zasobów dostajesz w nagłówku trace-id. Podaj to trace-id dla którego dostajesz w zwrotce opisany błąd: 

> ConstraintViolationException.ValidProduct with message Wybrany produkt nie istnieje. / Wybrany produkt nie istnieje.
