### ISSUE TITLE
Czy istnieje możliwość skorzystania z /offers/listing w REST api bez konieczności wiązania konta użytkownika z aplikacją?

### ISSUE THREAD

**Issue by retrowaver** [allegro/allegro-api#495]

**Comment by MarcinLuczak** [comment]
@retrowaver nie ma możliwości, by wywołać ten zasób bez autoryzacji.

Przy okazji prośba - w kolejnych przypadkach umieść proszę pytanie bezpośrednio w poście, a nie w jego tytule. Będzie nam łatwiej.

**Comment by retrowaver** [comment]
Okej, dziękuję. Postaram się pamiętać.
