### ISSUE TITLE
BAD_REQUEST przy /sale/offers

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#4954]
Zauważyłem dziwny problem przy próbie wstawienia oferty. Najdziwniejsze że część prób przy użyciu tej samej funkcji kończy się powodzeniem co wskazywało by raczej na problem z danymi niestety z komunikatu nic nie wynika.

stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => BAD_REQUEST
                    [message] => Message not readable
                    [details] => ValidationError.HttpMessageNotReadableException
                    [path] => 
                    [userMessage] => Message not readable
                )

        )

)

**Comment by AureliuszBrussy** [comment]
Żeby to sprawdzić potrzebuję pełnego requestu który zakończył się tym błędem, najlepiej w formie curl (usuń z niego token).

**Comment by krzysda** [comment]
Jest ok, problem dotyczył ceny nie zawsze miała dwa miejsca po przecinku
