### ISSUE TITLE
Wykrycie adresów www dopiero podczas publikacji a nie podczas tworzenia drafta

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#4955]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Kiedy tworzę drafta i w opisie znajdzie się niedozwolony adres www to spodziewam się otrzymać błąd już podczas tworzenia drafta. Tak się jednak nie dzieje. O tym, że w opisie jest adres www dowiaduję się dopiero jak sprawdzam przyczynę nieudanej publikacji. W samym natomiast drafcie tablica "validation.errors" jest pusta co sugeruje, że wszystko jest w porządku. Natomiast dopiero przy sprawdzeniu przyczyny nieudanej publikacji dostaję:

      "errors": [
        {
          "code": "ConstraintViolationException.ValidOfferName",
          "message": "Usuń z opisu oferty adresy stron zewnętrznych, za pośrednictwem których prowadzona jest sprzedaż poza Allegro. Możesz podać adresy stron, na których umieszczone są jedynie informacje poszerzające wiedzę o oferowanym produkcie.",
          "path": "description.id",
          "userMessage": "Usuń z opisu oferty adresy stron zewnętrznych, za pośrednictwem których prowadzona jest sprzedaż poza Allegro. Możesz podać adresy stron, na których umieszczone są jedynie informacje poszerzające wiedzę o oferowanym produkcie."
        }

Poniżej lista trace-id.

Tworzenie drafta: 
d9ece7f8ad7ab07a

Publikacja: 
11b7ed33b2f72e6f

Sprawdzenie przyczyny nieudanej publikacji: 
bc3382e8b788974f

Pobranie drafta w którym tablica "validation.errors" jest pusta: 
a8facf0d3306bc1d

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Weryfikuję to - wkrótce wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Opis oferty i jego zgodność z regulaminem jest przez nas walidowana zarówno w momencie tworzenia draftu, jaki i w momencie publikacji oferty. W tym pierwszym przypadku (brak asynchroniczności) mogą jednak zdarzyć się sytuacje, że nasza wewnętrzna usługa sprawdzająca zgodność opisu nie zwróci błędu (nie odpowie błędem w wyznaczonym czasie) i przepuści walidację. W związku z tym czasem może zdarzyć się tak, że taki błąd otrzymasz dopiero przy próbie aktywacji oferty.
