### ISSUE TITLE
Dlaczego zadania zamknięcia aukcji znikają, jeżeli jest ich więcej niż jeden?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#4956]
Witam,

chciałbym zapytać o naturę komend tworzonych poprzez zasób https://developer.allegro.pl/redoc/redoc-static.html#operation/changePublicationStatusUsingPUT. Doświadczam sytuacji, gdzie mój system zleca więcej niż jedną komendę zamknięcia aukcji. Sprawdziłem właśnie kilka przykładów i wygląda na to, że po wniesieniu do REST API Allegro kolejnego takiego samego zlecenia, UUID poprzedniego zlecenia nie jest już dłużej osiągalne. 

Widząc taką sytuację zastanawia mnie parę rzeczy. Czy nowe zlecenie odnosi się do tego samego zamknięcia aukcji, które zleciłem w starym? Czy może proces restartuje się, gdy wysyłam kolejne zlecenie zamknięcia aukcji, wydłużając jednocześnie czas realizacji tego zamknięcia?

Jestem bardzo ciekawy tych odpowiedzi,
Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Potwierdź proszę, czy do dobrze rozumiem:
1. Zlecasz zakończenie oferty nr 123 komendą uuid 1 (dla uproszczenia).
2. Przed zakończeniem działania i potwierdzeniem wykonania komendy uuid 1 - jeszcze raz zlecasz zakończenie oferty 123 komendą uuid 2. 
3. Nie możesz po tym sprawdzić wyniku komendy uuid 1.

Czy chodzi o taką sytuację? Masz jakieś konkretne przykłady?

**Comment by hahyes** [comment]
> Potwierdź proszę, czy do dobrze rozumiem:
> 
> 1. Zlecasz zakończenie oferty nr 123 komendą uuid 1 (dla uproszczenia).
> 2. Przed zakończeniem działania i potwierdzeniem wykonania komendy uuid 1 - jeszcze raz zlecasz zakończenie oferty 123 komendą uuid 2.
> 3. Nie możesz po tym sprawdzić wyniku komendy uuid 1.
> 
> Czy chodzi o taką sytuację? Masz jakieś konkretne przykłady?

@AureliuszBrussy Tak, chodzi o dokładnie taką sytuację. Znalazłem nawet dosyć świeży przykład, oferta 11202557366 i zadania zamknięcia.

1. 7c497878-fdf0-4639-bd5e-15fbb3339baf - starsza komenda, wyrzuca błąd:
```
{
  "errors": [
    {
      "code": "COMMAND_ACCESS_FORBIDDEN",
      "message": "Nie masz uprawnień do tego zlecenia - podaj poprawny commandId.",
      "details": null,
      "path": "",
      "userMessage": "Nie masz uprawnień do tego zlecenia - podaj poprawny commandId."
    }
  ]
}
```
2. 76551c77-7d8d-43cf-a1f0-13e11be91bbd - nowsza komenda, zwraca poprawny status komendy w JSONie, wszystko się zgadza.

**Comment by MartaNowaczyk** [comment]
W przypadku:
1. 7c497878-fdf0-4639-bd5e-15fbb3339baf byłeś zalogowany na konto, do którego nie należała oferta 11202557366, stąd mógł powstać problem przy odwołaniu się do tego uuid z konta do którego należy oferta.
2. Tutaj wszystko prawidłowo - w tokenie i ofercie to samo konto, stąd otrzymujesz prawidłową zwrotkę.

**Comment by hahyes** [comment]
@MartaNowaczyk Trochę późna odpowiedź, ale dziękuję. Udało mi się znaleźć błąd po mojej stronie dzięki tej informacji. Pozdrawiam. :)
