### ISSUE TITLE
Często "Internal server error." -- zacina programy i nie można rozmawiać z Allegro API

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4957]
Występuje problem: 
 - [x] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Opis**

Ciągle programy się zacinają... raz można zmieniać opis w aukcji, za chwilę nie można... 
Dlaczego? 

Trace id jest ```ad6ae57f6fd00601```, a odpowiedź jak niżej. 

```
błąd komunikacji
500
https://api.allegro.pl/sale/offers/11166448974
trace-id ad6ae57f6fd00601
date Thu, 23 Sep 2021 10:39:10 GMT
client-peer 185.31.27.150:443
content-type application/json; charset=utf-8
{
	"errors": [
		{
			"code": "INTERNAL_SERVER_ERROR",
			"details": null,
			"message": "Internal server error.",
			"path": null,
			"userMessage": "Internal server error. Please try again in a few minutes."
		}
	]
}
```

**Comment by leszekdubiel** [comment]
Kolejny przykład Trace id jest ```bfc53d900a7c378a```. 

```
błąd komunikacji
500
https://api.allegro.pl/sale/offers/11166448974
trace-id bfc53d900a7c378a
date Thu, 23 Sep 2021 10:45:19 GMT
client-peer 185.31.27.150:443
content-type application/json; charset=utf-8
{
	"errors": [
		{
			"code": "INTERNAL_SERVER_ERROR",
			"details": null,
			"message": "Internal server error.",
			"path": null,
			"userMessage": "Internal server error. Please try again in a few minutes."
		}
	]
}
```

**Comment by AureliuszBrussy** [comment]
Chwilowo mogły wystąpić błędy podczas edycji ofert. Problem nie powinien już występować.

**Comment by leszekdubiel** [comment]
Czyli to nie jest moja wina, że na przykład za dużo pytałem przez API, czy za dużo chciałem zapisywać?

**Comment by AureliuszBrussy** [comment]
@leszekdubiel nie, jeżeli wykonałbyś np. zbyt dużo requestów - zwrócony error powinien być inny. Twój problem powiązaliśmy z chwilowymi problemami w naszej usłudze. Jeżeli jednak błędy wciąż występują - poinformuj mnie.
