### ISSUE TITLE
Problem z wygenerowaniem user_code oraz device_code

### ISSUE THREAD

**Issue by AT1000** [allegro/allegro-api#4958]
Udało mi się zarejestrować aplikację typu DEVICE jednakże przy próbie uzyskanie user_code oraz device_code otrzymuję błąd {"error":"Unauthorized","error_description":"Unauthorized"}
Korzystam z windowsowego curl-a w trybie wsadowym:
curl -X POST "https://allegro.pl/auth/oauth/device" ^
-H "Authorization: Basic {base64(15768e210d174ae2a73XXXXXXXXXX:YYYYYYYYS48g7lNbd5AcSogyTe8qHvyAHR1Jvl6douvvWLzv0Czl0p)}" ^
-H "Content-Type: application/x-www-form-urlencoded" ^
-d "client_id={15768e210d174ae2a73XXXXXXXXXX}"

Kompletnie nie znajduje punktu zaczepienia w temacie błędu, będę wdzięczny za wszelkie sugestie.

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że kodowanie base64, które wykonujesz nie funkcjonuje prawidłowo. Upewnij się, czy faktycznie przekazujesz prawidłową wartość, ew. zamień funkcje kodującą base64 na enkodowany już string.

**Comment by AT1000** [comment]
Próbowałem tego rozwiązania również, niestety bez efektów.

**Comment by AureliuszBrussy** [comment]
Upewnij się też, czy na pewno wykonuje się cały skrypt, razem z przekazanym przez Ciebie headerem i payloadem. Rozumiem także, że zarejestrowałeś aplikację na środowisku produkcyjnym, nie na sandboxie?

**Comment by AT1000** [comment]
Udało mi się dojść do etapu generowania tokena. Wcześniejsze problemy były czysto składniowe. Polecenie zadziałało gdy wyeliminowałem funkcję base64 i wszystkie nawiasy klamrowe.
Niestety teraz otrzymuje komunikat: {"error":"unsupported_grant_type","error_description":"Unsupported grant type"}
Device_Code w poleceniu jest prawidłowy, autoryzacja poprawna tylko polecenie nie działa :(
Próbowałem na środ. prod. oraz sandboxie i jest dokładnie to samo.

**Comment by AureliuszBrussy** [comment]
Czy query parametr `grant_type` przekazujesz na pewno w odpowiedniej formie?:

`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code`

Zwrócony błąd wskazuje właśnie na niewłaściwą wartość w `grant_type`.

**Comment by AT1000** [comment]
Przekazuje dokładnie to samo co do znaku. Próbowałem nawet wydzielić ten parametr do odrębnego wiersza z przełącznikiem
-d "grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=XXXXXXXXXXXXXXX"
Żadnej poprawy, nadal otrzymuję błąd.

**Comment by MartaNowaczyk** [comment]
Podeślij mi pełen request i response do weryfikacji. Skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz, że sprawa dotyczy wątku #4958 na GitHubie.

**Comment by AT1000** [comment]
Póki co sobie poradziłem :).  Problem polegał na tym, że wartość grant_type była przekazywana w sposób zakodowany URL. Po zdekodowaniu czyli zastosowaniu postaci grant_type=urn:ietf:params:oauth:grant-type:device_code udało mi się uzyskać token. Dostęp porzez API do własnych aukcji działa, mogę je listować i korelowac z firmowym ERP-em. Mam również nadzieję, że bez problemu uda mi się odświeżyć token.

**Comment by MartaNowaczyk** [comment]
No to świetnie, powodzenia w takim razie!! :)
