### ISSUE TITLE
How to get all allegro listings

### ISSUE THREAD

**Issue by CkpOFF** [allegro/allegro-api#4959]
Hello
Is it possible to get all used auto parts listings from allegro? I want to sell it on my woocommerce website. Thank you
Best regards

**Comment by AureliuszBrussy** [comment]
Using the Allegro API in this way is not permitted:

> 4.1. The REST API Software may not be used in a manner that violates the rights of Allegro.pl and third parties, in particular, the following is not permitted:
> ....
> c. using it to present Offers (including archived Offers) published on Allegro on competitor websites;

You can check all the rules [here](https://developer.allegro.pl/en/rules/).

**Comment by webmaestro-ua** [comment]
Hi @CkpOFF ,

we are web studio WebMaestro.
 In our portfolio
https://webmaestro.com.ua/ua/portfolio-development/
there are a lot of successful Allegro data extracting solutions + few projects in progress related above topic:

https://restauto.com.ua/
https://motopoland.com.ua/
https://spolshy.com.ua/
https://dvizok.com.ua/
https://motoallegro.net/
https://zp-auto.com.ua/
https://autodil.com.ua/
https://autoblok.com.ua/
https://automotive.org.ua/
https://avto-plus.com.ua/
https://mrzauto.com/
https://zakroot.com/

 We are open for new challenges and cooperations.
Best Regards
