### ISSUE TITLE
Drzewo kategorii

### ISSUE THREAD

**Issue by jarekp69** [allegro/allegro-api#496]
Idąc po drzewie kategorii (GET na zasobie /sale/categories?parent.id={categoryId}) już na poziomie n-1 nie dostaję pełnej listy porównujac z tym co jest dostępne w serwisie. Wchodząc w 'Motoryzacja' zwracany słownik zawiera tylko 9 podkategorii... na liście brakuje takich jak 'Samochody', 'Motocykle i quady' lub 'Maszyny'. Czy to efekt jakiegoś ukrytego stronicowania? Jak uzyskać kod dla 'Samochodów'?

Pozdrawiam,
Jarek

**Comment by MarcinLuczak** [comment]
@jarekp69 dane zwracane przez zasób są zgodne z formularze wystawiania oferty. Pozostałe kategorie, których zasób w takim zapytaniu nie zwraca, są z innej pod kategorii - Ogłoszenia i usługi.

Nie ma tutaj błędu.

**Comment by jarekp69** [comment]
Zadziałało. Dzięki.
