### ISSUE TITLE
Nie mogę zmienić nazwy aukcji, co zmusza do nie wznawiania jej ale dodawania nowej 

### ISSUE THREAD

**Issue by leszekdubiel** [allegro/allegro-api#4960]
Występuje problem: 
 - [X ] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Allego zaleca, aby nie dodawać nowych aukcji dla produktów, tylko wznawiać zakończone aukcje. 
Ale wtedy nie pozwala zmienić nazwy aukcji, czyli jestem zmuszony, aby po każdym zakupie robić całkiem nową aukcję, jeśli chcę zmienić nazwę. 

To jest sprzeczność... 

Czy to błąd, czy zamierzone działanie? 

Trace id: 

```
błąd komunikacji
422
https://api.allegro.pl/sale/offers/11128087946
trace-id d8aea745e76d719b
date Thu, 23 Sep 2021 20:19:09 GMT
client-peer 5.134.213.11:443
content-type application/json
{
	"errors": [
		{
			"code": "VALIDATION_ERROR",
			"details": "IllegalOfferUpdateException.IllegalChangeOfferName",
			"message": "You cannot modify the name for offer with bids.",
			"path": "name",
			"userMessage": "You cannot modify the name for offer with bids."
		}
	]
}

```

**Comment by AureliuszBrussy** [comment]
Jest to celowe, nie jest to błąd - listę, co można, a czego nie można edytować po wystawieniu oferty znajdziesz w [pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz).
