### ISSUE TITLE
Wysyłam z Allegro status paczki z PP

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4961]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Problem zdaje sie tylko z paczkami z Poczty Polskiej.
Paczka utworzona, ale podczas sprawdzania statusu :
/parcel-management/parcel-create-commands/7eeac0f7-eb98-43d5-9154-93927e823f60
Error "Niepoprawne dane autoryzacyjne"

**Comment by AureliuszBrussy** [comment]
@paafcioc22 z błędu wynika, że użytkownik wprowadził nieprawidłowe dane logowania do API przewoźnika. Dane do logowania należy uzupełnić w zakładce [Umowy własne](https://wysylam.allegro.pl/konto/przewoznicy/dodaj).

**Comment by paafcioc22** [comment]
Dziękuję już wszystko gra.
