### ISSUE TITLE
Połączenie z Allegro API - notoryczne logowanie

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#4962]
Witam,

Wykonuję uwierzytelnianie z Allegro API za pomocą Authorization Code flow. 
Uwierzytelnianie wykonywane jest w programach które m.in wykonują automatyczną aktualizację cen oraz stanów produktu na allegro. 
Niestety po 1 dniu pracy bez przerwy pojawia się problem bo trzeba się zalogować do Allegro przez podanie loginu i hasła i tak notorycznie codziennie. 
Czy istnieję sposób na ominięcie logowania? np. podając login i hasło w dodatkowym parametrze? 
Obecna autoryzacja jest uciążliwa.

**Comment by AureliuszBrussy** [comment]
By nie zmuszać użytkownika aplikacji do ponownej autoryzacji aplikacji dwa razy na dobę (access_token jest ważny 12 godzin), udostępniamy możliwość odświeżania tokenów - służy do tego refresh_token, który otrzymujesz wraz z access_tokenem. Więcej przeczytasz w [naszym poradniku](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena).

**Comment by palmemd** [comment]
Ale refresh token jest odświeżany z każdym zapytaniem do nowego access_code

**Comment by AureliuszBrussy** [comment]
@palmemd czy mógłbyś to rozwinąć? 

Jeżeli chcesz pominąć konieczność ponownej autoryzacji aplikacji przez użytkownika, powinieneś po wygaśnięciu access_tokena skorzystać z refresh_tokena, którego otrzymałeś wraz z tym tokenem, który wygasł. 

Musisz wykonać żądanie:

```
curl -X POST \
  'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJ...SDA&redirect_uri=http://exemplary.redirect.uri' \
  -H 'Authorization: Basic YTI...Hg=' \
```

W odpowiedzi otrzymasz nowy access_token, którego możesz używać przez 12 godzin, oraz kolejny refresh_token.

**Comment by palmemd** [comment]
Właśnie tak robię , mam zmienną refresh_token['access_token'] którą przekazuje do nagłówków:
`headers['Authorization'] = "Bearer {}".format(sign2['access_token'])`
podczas wysyłania zapytań POST , mimo to co jakiś czas(1 dzień, czasami 3 dni) pojawia się allegro.pl do zalogowania i nie wiem dlaczego

**Comment by AureliuszBrussy** [comment]
Nie odnotowujemy żadnych problemów z odświeżaniem tokenów. W tej sytuacji musisz przeanalizować, czy Twoja aplikacja faktycznie prawidłowo korzysta z możliwości odświeżania tokena.
