### ISSUE TITLE
Sprawdzenie zmian w parametrach kategorii

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#4963]
Czy istnieje metoda do sprawdzenia zmian w parametrach kategorii, coś jak dziennik zmian w kategoriach. 
Widzę że istnieje zasób GET /sale/category-parameters-scheduled-changes ale w dokumentacji jest że zwraca tylko wartość REQUIREMENT_CHANGE a mnie interesują takie zdarzenia jak dodawanie, modyfikacja i usuwanie parametrów.
Obecnie aby sprawdzić zmiany w parametrach musze dla każdej kategorii robić zapytanie GET /sale/categories/{categoryId}/parameters co nie jest optymalnym rozwiązaniem.

**Comment by AureliuszBrussy** [comment]
Przyszłe zmiany w parametrach sprawdzisz tylko za pomocą: [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation/#operation/getCategoryParametersScheduledChangesUsingGET_1). Aktualnie jedynym wspieranym typem zmian jest uobowiązkowienie parametrów. W pozostałych przypadkach na ten moment pozostaje _GET /sale/categories/{categoryId}/parameters_.
