### ISSUE TITLE
wystawianie przedmiotu, a konto firmowe

### ISSUE THREAD

**Issue by faran22** [allegro/allegro-api#4964]
Dzień dobry,
nie mogę wystawić przedmiotu bo piszę że konto nie jest firmowe, ale jak wejdę w zakładkę konto to piszę że jest firmowe, Client:44292194.

**Comment by AureliuszBrussy** [comment]
Konto o tym loginie jest kontem zwykłym, nie firmowym. Jeżeli chcesz wyjaśnić kwestię statusu swojego konta - skorzystaj z [formularza kontatkowego](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c).
