### ISSUE TITLE
Allegro API authorize - wiele kont jednocześnie

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#4966]
Witam,

Czy istnieje możliwość uwierzytelnienia API jednocześnie paru kont Allegro i wykonywania operacji na tych kontach? 
Ewentualnie przełączania się między kontami bez potrzeby na nowo logowania loginem i hasła.

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości uwierzytelnienia jednocześnie na kilku kontach. Poza tym nie musisz ciągle logować się loginem i hasłem - aplikacja autoryzuje użytkownika tylko jednokrotnie, następnie może zostać to zautomatyzowane za pomocą refresh tokenów, o których więcej możesz przeczytać [tutaj](https://developer.allegro.pl/auth/#przed%C5%82u%C5%BCenie-wa%C5%BCno%C5%9Bci-tokena).

Informacje o autoryzacji znajdziesz w naszym [poradniku](https://developer.allegro.pl/auth/).

**Comment by thefoe76** [comment]
jak najbardziej się da, wykorzystując polimorfizm odpowiednio napisanej klasy obiektowej, którą wywołujesz dla dowolnej liczby kont i działasz na nich na tych samych metodach

**Comment by MartaNowaczyk** [comment]
@thefoe76 my odpowiadamy na podstawie możliwości danego zasobu API allegro. Wykorzystanie danego zasobu i oprogramowanie jest już inną kwestią.
