### ISSUE TITLE
Zasób zwraca błędne dane

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#4967]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem testowym

Zasób GET /sale/category-events na środowisku testowym zwraca dziwne dane, event ID: 1656626400000168104 ma w polu occurredAt wartość "2022-06-30T22:00:00Z" mam nadzieję że na produkcyjnej wersji takie rzeczy się nie pojawią

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Weryfikuję problem z zespołem odpowiedzialnym za funkcjonalność. Wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Poprawimy działanie zasobu, tak aby zwracał tylko zdarzenia z przeszłości.

**Comment by avello** [comment]
Ze środowiskiem produkcyjnym jest jeszcze gorzej, napisałem o tym tu https://github.com/allegro/allegro-api/issues/4975 
Czy to znaczy że obecnie należy ignorować zdarzenia z przyszłości ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, na tę chwilę ignoruj proszę zdarzenia z przyszłości.
