### ISSUE TITLE
metoda GET na zasobie /offers/listing przestała działać

### ISSUE THREAD

**Issue by 11mszot** [allegro/allegro-api#4968]
Witam ,

Dziś , bez żadnego uprzedzenia przestała działać metoda GET w moich aplikacjach , wszystkieżądania do tej metody dają odpowiedź 

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => VerificationRequired
                    [message] => Access is denied. Verification is required.
                    [details] =>
                    [path] =>
                    [userMessage] => Brak dostępu do danego zasobu. Dostęp możliwy tylko dla zweryfikowanych aplikacji.
                )

        )

)

 jestem developerem którego aplikacje obsługują kilkuset użytkowników Allegro , którzy w sumie mają wystawione dziesiątki milionów ofert , zgodnie z żądaniem Allegro w dniu 29 kwietnia zgłosiłem moje aplikacje do weryfikacji , dziś mamy wrzesień i oczywiście zero odpowiedzi z Allegro  : zgłoszenie nr "15259748" [ ref:_00D24aE05._5003VEPoQu:ref ]

Mimo upływu pięciu miesięcy nie otrzymałem żadnej odpowiedzi ale aplikacje działały z tą metodą , miałem prawo chyba przypuszczać że wszystko jest w porządku

Aktualnie używam aplikacji z następującymi  Nazwami /  Client-Id

ALLEDEMO 9a30990f-89f4-4fb6-aa0b-f62c2da793cc
BBPW   b9e2f78ce82e454caf2be16aa917243d
MYDEMO a1e6c946-049f-4328-bb56-f24a1925d250
STATS c83581a571fc438992de665d3da63608
TFONK 3ebe4219-d42a-4321-bb69-33dac58ab85e

Proszę o pilne wyjaśnienie zaistniałej sytuacji  bo szkodzi ona tak mojej reputacji jako twórcy aplikacji , jak i reputacji Allegro które w mojej opinii powinno traktować zarówno klientów jak i partnerów poważniej

**Comment by PrzemyslawLukanowski** [comment]
Weryfikacja aplikacji jest poza naszym zespołem, w Twoim przypadku musiało dojść do jakiegoś nieporozumienia, za co przepraszam. Zweryfikowałem sprawę wewnętrznie - właśnie powinieneś otrzymać mailowo dane do umowy.
