### ISSUE TITLE
Listy przewozowe przez REST API

### ISSUE THREAD

**Issue by skozuchowicz** [allegro/allegro-api#497]
Witajcie Allegro,
czy jest w planach udostępniania możliwości generowania listów przewozowych bezpośrednio przez REST API?

**Comment by KrzysztofLukanowski** [comment]
Cześć, rozumiem, że masz na myśli API, które odzwierciadlałoby opcję 'Nadaj przesyłkę kurierem' z zakładki [Zamówienia](https://allegro.pl/seller-orders/#!/). Na tę chwilę nie planujemy udostępnić tej opcji w REST API.

**Comment by kormichu** [comment]
@KrzysztofLukanowski czy metoda: https://allegro.pl/webapi/documentation.php/show/id,744 obsługuje identyfikatory transakcji, które są zwracane przez REST API ? Chodzi mi o różnicę pomiędzy typami: wartość numeryczna / UUID pomiędzy różnymi wersjami API (SOAP / REST). W REST API nie ma obecnie takiej możliwości

**Comment by KrzysztofLukanowski** [comment]
@kormichu Nie. Chcąc dodać info o przesyłce za pomocą w/w metody, musisz przesłać wartość w operatorId zgodnie z opisem tej metody. Na razie jest to możliwe tylko w WebAPI. W niedalekiej przyszłości udostępnimy odpowiednie zasoby na REST API. Na bieżąco będziemy informować o wszelkich zmianach, tutaj na forum, jak i na [portalu deweloperskim](https://developer.allegro.pl/news/).
