### ISSUE TITLE
Cała masa błędów w opisie API

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#4970]
Występuje problem: 
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Hej!
Analizuje sobie wasz plik https://developer.allegro.pl/swagger.yaml

Niestety jest tam cała masa błędów, przez co generowanie klientów wymaga dużo zmian.
Jeśli się mylę, to przepraszam.

W komentarzach do niektórych waszych wypowiedzi umieściłem już kilka takich błędów. Oto dwa przykłady pól, które mogą być `null`, ale nie ma takiej informacji w pliku:
`        personalIdentity:
          type: string
          description: Buyer's personal identity number (PESEL)
          example: "67062589524"`
`        companyName:
          type: string
          description: Company name
          example: null`

W każdym z nich brakuje oznaczenia `nullable: true` (zakładając, że dalej pracujecie na wersji openapi 3.0)

Czy planujecie to poprawić, czy po prostu muszę z tym żyć? Tych przykładów jest dużo więcej.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Sprawdzimy naszą dokumentację pod kontem wartości `null` i poprawimy co będzie trzeba.

**Comment by jakubmaguza** [comment]
Hej, dziękuję. Jeśli będziesz pamiętała, to zostaw tu wiadomość jak skończycie.

**Comment by MartaNowaczyk** [comment]
ok
