### ISSUE TITLE
Jeden koszt wysyłki/Jedna wysyłka

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#4971]
Witam, miałbym takie pytanie:
Zdarza się czasem, że klient kupi u nas dwa przedmioty (dwie różne nasze oferty) w jednym zamówieniu i system mu nalicza dwa koszty wysyłki. Czy jest możliwość skonfigurowania kosztów wysyłki na allegro tak aby cena wysyłki była liczona tylko raz?

**Comment by MartaNowaczyk** [comment]
Możliwości łączenia kosztów dostawy na allegro znajdziesz [tutaj](https://allegro.pl/pomoc/dla-sprzedajacych/cennik-dostawy/jak-ustawic-odpowiedni-sposob-laczenia-kosztow-dostawy-dla-ofert-z-roznymi-cennikami-4GDdXnx0LuW).

**Comment by Witold1983** [comment]
Ok, bardzo dziękuję
