### ISSUE TITLE
Średnia cena sprzedaży (ASP)

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#4973]
Czy istnieje możliwość pobrania przez jakiś zasób średniej ceny sprzedaży (ASP) z ostatnich 30 dni dla danego towaru - czyli podstawowej wartości do wyliczeń w programie Smart! Week, które są prezentowane w panelu:
https://allegro.pl/moje-allegro/sprzedaz/kampanie?recoCampaign=SALE_CATEGORY_SMARTWEEK2021

**Comment by MartaNowaczyk** [comment]
Nie mamy takiego zasobu.
