### ISSUE TITLE
metoda  GET /offers/listing - dostęp

### ISSUE THREAD

**Issue by pamdo7** [allegro/allegro-api#4974]
Chcielibyśmy przy pomocy metody GET /offers/listing sprawdzać aktualne ceny produktów oferowane przez konkurencję w konkretnych aukcjach.
Ale niestety aby stosować tę metodę musimy otrzymać autoryzację Allegro. Napisane jest mętnie, że trzeba być VIP’em lub mieć co najmniej 100 userów swojej aplikacji.

Czy jest jakiś inny sposób na uzyskanie tych uprawnień?

**Comment by MartaNowaczyk** [comment]
Tutaj nie weryfikujemy aplikacji. To co piszesz to podstawowe kryteria. Proces weryfikacji aplikacji przejdziesz, kontaktując się przez [formularz ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)- sprawa trafi do odpowiedniego zespołu, który zajmie się zgłoszeniem.

**Comment by thefoe76** [comment]
to jest nieco paranoja, bo ten zasób jest dostępny dla każdego poprzez stronę allegro.pl (bez żadnego logowania), więc niako sami indukujecie sobie problem, bo ludzie zaczną stawiać parsery całych stron wyszukiwania zamiast API, które jest po to by nie obciążać zasobów. Nie mogę pojać, czemu utrudniacie sprawdzanie cen u konkurencji?

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak tutaj zajmujemy się kwestiami działania API, dlatego w sprawie konieczności weryfikacji pytanie zadaj przez wcześniej podesłany formularz.

**Comment by hahyes** [comment]
> Nie mogę pojać, czemu utrudniacie sprawdzanie cen u konkurencji?

@thefoe76 Bo masz korzystać z narzędzi do analizy sprzedaży dostarczanych przez Allegro. Chodzi po prostu o pieniądze, nic więcej. I tak /offers/listing zostało tak ograniczone, że w wielu wypadkach używanie go jest bez sensu (np. możliwość wyszukania do 600 pozycji i nic więcej, dużo danych wycięto itd.).

**Comment by thefoe76** [comment]
wystarczy mi to co wyświetalnie jest zupełnie PUBLICZNIE na stronie allegro.pl, czekam na weryfikację, ponoc jakąś stertę papierów trzeba podpisać. Ale jak będa grać w kulki, to po prostu zacznę web scrapping.

**Comment by hahyes** [comment]
> Ale jak będa grać w kulki, to po prostu zacznę web scrapping.

Brzmi trochę jak taka groźba. Wierz mi, im to lata i powiewa, w /offers/listing są dokładnie te publiczne dane, jednak postanowili je sprzedawcom zabrać.
