### ISSUE TITLE
Zwraca dziwne dane w GET /sale/category-events

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#4975]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym

Zasób zwraca dziwne dane.
Na końcu listy zwracanych danych jest wiele wpisów z datą "2021-10-17T22:00:00Z" czyli z przyszłości np. event ID = 1634508000000420755 
Dodam że nazwa kategorii w tych wpisach to "Testy diagnostyczne" czy to znaczy że robicie sobie testy na produkcji ;)
Taki sam problem jest w środowisku testowym.
Co oznaczają takie wpisy z przyszłości i jak je interpretować ?

**Comment by MartaNowaczyk** [comment]
Powielony post. Odpowiedź udzielona w wątku [#4967](https://github.com/allegro/allegro-api/issues/4967#issuecomment-929007579)
