### ISSUE TITLE
Pobieranie ceny w promocji smart week

### ISSUE THREAD

**Issue by grab95** [allegro/allegro-api#4976]
Wita czy jest mozlliwosc pobierania aktualnej ceny przy promocji smart week? 
Pobieram oferte za pomoca bramki /sale/offers lecz zwracana wartosc z sellingMode->price->amount  nie jest taka jak na aukcji. 
Z góry dzieki z apomoc :)

**Comment by MartaNowaczyk** [comment]
Cenę możesz sprawdzić za pomocą [GET /sale/badges](https://developer.allegro.pl/documentation/#operation/getBadges).

Nie znajdziesz w /sale/offers ceny widocznej dla klienta.

Informowaliśmy o tym :

> Od 24 sierpnia 2021 jeżeli oferta zostanie zakwalifikowana do kampanii:
> - nie zaktualizujemy ceny w jej strukturze - bazowa cena, którą zwrócimy w polu sellingMode.price.amount pozostanie bez zmiany,
> - jeżeli dojdzie do zmiany ceny bazowej w ofercie w polu sellingMode.price.amount w trakcie trwania kampanii - nie zostanie ona z niej wykluczona,
> - w odpowiedzi na GET /sale/offer-events nie zwrócimy zdarzenia o zmianie ceny w ofercie w wyniku jej zakwalifikowania do kampanii.
> Zmiana ceny w ofercie, która jest w trakcie kampanii lub jej usunięcie z kampanii będzie możliwe dzięki PATCH /sale/badges/offers/{offerId}/campaigns/{campaignId}.
