### ISSUE TITLE
Wystawianie oferty z tagiem.

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#4977]
Pytanko czy w trakcie wystawiania oferty można dodać tag?

O ile dobrze rozumiem na daną chwile trzeba wykonać dodatkowy request pod adresem
http://api.allegro.pl/sale/offer-tags 
zeby można było dodać tag.

Jeśli się myle to prosze o wyjasnienie.

**Comment by MartaNowaczyk** [comment]
Tak, trzeba wykonać dodatkowy request, aby przypisać tag do oferty [POST sale/offers/{offerId}/tags](https://developer.allegro.pl/documentation/#operation/assignTagToOfferPOST). Więcej o tagach znajdziesz [tutaj](https://developer.allegro.pl/sale/#tagi-ofertowe).

**Comment by Troom** [comment]
OK, dziękuje materiały przejrzałem, ale zastanawiałem się czy da się to jeszcze uprościć.

**Comment by Troom** [comment]
Okazuje się ze jeszcze mam nieścisłość.
Próbowałem dodać tag do oferty poprzez URL
https://api.allegro.pl/sale/offers/11000611468/tags

Zawartość wysyłanego  jsona:
![image](https://user-images.githubusercontent.com/10126507/135454340-8a607f1c-b64f-4c46-89cd-e8c3394c12f3.png)

W odpowiedzi dostałem 200 OK, ale na stronie nie widze powiązania oferty z Tagiem. 

Coś pominałem?

**Comment by MartaNowaczyk** [comment]
Oferta pod danym tagiem może pojawić się z opóźnieniem. Aby dodać tag wystarczy samo tags.id `{"tags": [{"id": "2938ff8c-fcd2-443f-a462-3b7aedcb5a0d"}]}` Dodałam tag dla sprawdzenia i nie widzę problemów z zasobem.

**Comment by Troom** [comment]
OK, faktycznie, działa, ale z ogromnym opóznieniem.

Przy okazji pytanie - wszystkie aktualizacje ofert wykonywane są co godzine?
Podczas edycji "ręcznej" znalazłem coś takiego:
![image](https://user-images.githubusercontent.com/10126507/135722684-e5bcd543-a291-4ca5-89c6-ebe31f0ba676.png)

Proszę o informację czy jeśli z poziomu API edytuje cenę, to ona również zostanie wprowadzona po "około" godzinie?

**Comment by MartaNowaczyk** [comment]
To jest maksymalny czas jaki zapewniamy, niezależnie od kanału wystawiania (formularz, API). Najczęściej jednak oferty wystawiane są od razu.
