### ISSUE TITLE
Jak automatycznie naprawić błąd: ConstraintViolationException.ValidProduct Kategoria oferty jest różna od kategorii produktu - 250843.

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#4979]
Po próbie zmieny ceny / dostępności oferty dostaję błąd: 

ConstraintViolationException.ValidProduct
Kategoria oferty jest różna od kategorii produktu - 250843.

W jaki sposób mogę to poprawić na wszystkich ofertach automatycznie ? Do tej pory z ofertami nie było problemu działały.... nagle problem zaczyna dotykać coraz większej ilości ofert

**Comment by MartaNowaczyk** [comment]
Jeżeli znajdziesz błąd w produkcie możesz to zgłosić poprzez formularz - https://allegro.pl/offer/product/report/{productId}.
Nie ma możliwości obejścia wystawienia danego produktu w innej kategorii, jeżeli nie ma on przypisanych do siebie kategorii podobnych.

Do weryfikacji czy dany produkt jest poprawny (ma przypisaną poprawną kategorię) potrzebuję ID produktu i trace-id dla otrzymanego błędu. To właśnie na tym opieramy się przy weryfikacji.

**Comment by pliszka** [comment]
Produkt został już wystawiony dawno, problem dotyczy aukcji która już istnieje, w tej chwili system nie daje mi możliwości zmiany ceny na tej aukcji stąd pytanie jak to naprawić?

**Comment by MartaNowaczyk** [comment]
Muszę wiedzieć jaki to produkt, jaka oferta i znaleźć przyczynę. Do tego potrzebuję danych o które prosiłam.
