### ISSUE TITLE
1-  Seller vs Buyer Order Status; 2 - Customer Return Status

### ISSUE THREAD

**Issue by VorobiovK** [allegro/allegro-api#4981]
Projektujemy integrację z systemem Allegro.
Mamy kilka pytań, aby zrozumieć, jak dzieją się w niej pewne rzeczy.
Czy prawidłowo rozumiemy że ten system jest widoczny dla:
- Sprzedawcy (seller)
- Kupującego (buyer)
- I dla nas deweloperów przez API.

w załączniku znajdziecie opis problemu + przykłady
[01 Seller vs Buyer Order Status.pdf](https://github.com/allegro/allegro-api/files/7254398/01.Seller.vs.Buyer.Order.Status.pdf)
[02 Customer Return Status.pdf](https://github.com/allegro/allegro-api/files/7254399/02.Customer.Return.Status.pdf)

**Comment by MartaNowaczyk** [comment]
01 - API allegro skierowane jest w zdecydowanej mierze dla sprzedawców i jako sprzedawca nie zobaczycie statusu kupującego. Możecie pobrać status przesyłki, ale tylko dla przesyłek Allegro. Więcej znajdziecie w naszym [poradniku](https://developer.allegro.pl/wza/#jak-pobra%c4%87-histori%c4%99-status%c3%b3w-przesy%c5%82ek-allegro). Jeśli chodzi o `fullfilment.status` zwracamy wartość, którą sprzedający może sam ustawić. Nie jest to status, który zmienia się automatycznie po kolejnym etapie dostawy czy wyborach kupującego (np. anulowanie zakupu). Kupujący go nie widzi -  status określa etap realizacji zamówienia po stronie sprzedającego.
02 - w opisanym zasobie GET /order/customer-returns nie zwracamy statusu realizacji zwrotu. Możemy to tylko wywnioskować po danych, które otrzymujemy w odpowiedzi. Nie ma też innej możliwości by pobrać ten status.
