### ISSUE TITLE
Wydłużenie czasu dostawy kiedy ilość dostępnych produktów zejdzie do jakiegoś poziomu

### ISSUE THREAD

**Issue by JaroszPatryk** [allegro/allegro-api#4982]
Witam, wystawiam produkty z baselinkera do allegro. Chciałbym zrobić automat który sprawdza stany produktów i w przypadku gdy zejdą do jakiegoś poziomu robi update na aukcji - konkretnie wydłuża czas dostawy. Czy taka opcja jest u państwa dostępna? Otóż interesuje mnie konkretne operacja czyli pobranie jakieś aukcji i update z wydłużeniem czasu dostawy.

**Comment by MartaNowaczyk** [comment]
Witam, możesz edytować ofertę [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) i skorzystać z `handlingTime`, który określa czas wysyłki.

**Comment by JaroszPatryk** [comment]
Dziękuję za odpowiedź. Prosiłbym jedynie o informację jak powinien wyglądać proces zaktualizowania takie czasu dostawy? Mam na myśli czy robię to po jakimś id oferty czy może jest inny sposób?

**Comment by MartaNowaczyk** [comment]
W tym wypadku musisz przesłać całą strukturę oferty:

1.  [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - pobierasz dane oferty
2. PUT /sale/offers/{offerId} - przesyłasz całą strukturę oferty ze zmienionym `handlingTime`

Informacje o edycji oferty znajdziesz na naszej [stronie](https://developer.allegro.pl/my_offers/#edycja-pojedynczej-oferty).

**Comment by JaroszPatryk** [comment]
Czy id oferty mi wystarczy aby zaktualizować ofertę na swoim koncie, czy jednak będę potrzebował więcej danych takich jak token użytkownika? Czy mogę wyciągnąć całą listę id ofert wystawionych na konkretnym koncie?

**Comment by MartaNowaczyk** [comment]
Aby wykonywać operacje na ofertach musisz być zautoryzowany jako sprzedawca, także token będzie potrzebny. 

Pobieranie listy ofert opisaliśmy [w poradniku](https://developer.allegro.pl/my_offers/#jak-pobra%c4%87-moje-oferty-w-rest-api). Token też wymagany ;)
