### ISSUE TITLE
[/sale/product-offers] wystawianie oferty i komunikat błędu PARAMETER_MISMATCH

### ISSUE THREAD

**Issue by michalfurtak** [allegro/allegro-api#4983]
Cześć,
wystawiam ofertę korzystając z endpointa /sale/product-offers, a później ją aktywuję. Czasami akcja udaje się, ale w niektórych przypadkach dostaję komunikat błędu: 

`{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Cover'(75) value (other(75_314838)) does not match the existing parameter value (hardcover(75_2))","details":null,"path":"product.parameters","userMessage":"The provided parameter `Cover` value `other(75_314838)` does not match the existing parameter value `hardcover(75_2)`."},{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Title'(223545) value (La Casa Adormecida / The Napping House) does not match the existing parameter value (La casa adormecida / The Napping House)","details":null,"path":"product.parameters","userMessage":"The provided parameter `Title` value `La Casa Adormecida / The Napping House` does not match the existing parameter value `La casa adormecida / The Napping House`."},{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Author'(223489) value (Wood Audrey) does not match the existing parameter value (Audrey Wood)","details":null,"path":"product.parameters","userMessage":"The provided parameter `Author` value `Wood Audrey` does not match the existing parameter value `Audrey Wood`."}]}
`

Z tego co rozumiem to istnieje rozbieżność pomiędzy wysyłanymi danymi, a danymi w bazie allegro. W tym wypadku rozbieżności dotyczą okładki, tytułu, autora. Czy jedynym wyjściem jest próba wyszukania produktu i wysyłanie zgodnych danych?
W jaki sposób mogę uniknąć tego błędu? 

MF

**Comment by MartaNowaczyk** [comment]
Cześć,
tak, wynika to z różnic między tym co mamy u siebie, a tym co przesyłasz. Jeżeli znajdziesz błąd w produkcie warto to zgłosić poprzez formularz - https://allegro.pl/offer/product/report/{productId}, aby to co wystawiasz było zgodne z produktem jaki będzie widoczny w ofercie. W przyszłości umożliwimy zgłaszanie błędów w produktach również przez API.

**Comment by michalfurtak** [comment]
@MartaNowaczyk złóżmy, że problem jest z moimi danymi. Potwierdź proszę, że powinienem w takim wypadku najpierw wyszukać produktu np. po eanie (sale/products) i wysyłać zgodne dane.  Zgadza się?

**Comment by MartaNowaczyk** [comment]
Tak, zgadza się. 
Możliwości wyszukiwania produktu opisaliśmy w naszym [poradniku](https://developer.allegro.pl/productization/#jak-znale%c5%ba%c4%87-produkt).

**Comment by michalfurtak** [comment]
OK, rozumiem. W takim razie martwi mnie jedna rzecz: ilość ofert, które mogę wystawić w danym czasie.
Jakiś czas temu próbowałem pobierać informacje przez /sale/products, jednak są tam narzucone dodatkowe limity ilości zapytań. Czy jesteś w stanie podać ile wynosi limit zapytań do tej usługi (nie znalazłem konkretnej informacji w dokumentacji)?

**Comment by MartaNowaczyk** [comment]
Zgodnie z [informacją](https://developer.allegro.pl/productization/#1-jak-wyszuka%c4%87-produkt) w części  "Jak znaleźć produkt": 

> Dla tego zasobu obowiązuje [Dodatkowy limit liczby zapytań dla użytkownika](https://developer.allegro.pl/about/#ograniczenie-liczby-zapyta%C5%84-limity).

Nie możemy zatem wskazać Ci konkretnego limitu.
