### ISSUE TITLE
Orlen Paczka

### ISSUE THREAD

**Issue by filip-tkacz** [allegro/allegro-api#4984]
Witam,
w jaki sposób możemy odróżnić - w wysyłce orlen paczka - czy paczka jest wysyłana na stację Orlen, czy do kiosku Ruch?

Mamy problemy z przekazywaniem zamówień przez nasze api.

**Comment by MartaNowaczyk** [comment]
Jak tylko uda mi się to sprawdzić, dam znać.

**Comment by MartaNowaczyk** [comment]
Udało mi się ustalić, że obecnie, sieć punktów dla metody Orlen Paczka po stronie Allegro nie obsługuje stacji Orlen tylko kioski RUCHu.

**Comment by Lukasz-Zurek** [comment]
Sprawa jest nadal weryfikowana. Proszę o cierpliwość.

**Comment by CF-WR617AC** [comment]
Czy coś w tamacie drgnęło ?

**Comment by Lukasz-Zurek** [comment]
Nie, sprawa jest nadal wyjaśniana. Nie jest to w pełni zależne od naszego Serwisu, dlatego czas weryfikacji wydłużył się, za co serdecznie przepraszamy.

**Comment by CF-WR617AC** [comment]
Rozumiem, czy w takim razie wątek zostanie przez Państwa zamknięty bez rozwiązania problemu?

**Comment by Lukasz-Zurek** [comment]
Nie, wątek nie zostanie przez nas zamknięty, chyba, że nastąpi to automatycznie. Zależy mi na wyjaśnieniu tej sprawy do końca, dlatego jak tylko uzyskam informacje dotyczące rozwiązania problemu - poinformuję o tym fakcie w tym wątku.

**Comment by Lukasz-Zurek** [comment]
Myślę, że najlepiej będzie jak skontaktujesz się w tej sprawie poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Tam uzyskasz szczegółowe informacje dotyczące metod dostawy w procesie zakupowym.
