### ISSUE TITLE
CommandID - ile razy wywołać UUID

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#4985]
Dzień dobry,

Proszę o informację czy wywołując zapytanie PUT /sale/offer-price-change-commands/{commandId} ,
w polu commandId wystarczy, że podam tylko raz wartość UUID np. "31991b5-9331-4ca3-90f0-b5efcaabb1e4" czy musze dla każdej zmiany ceny na nowym towarze generować nowy UUID?

**Comment by kfijalko** [comment]
commandId muszą być unikatowe dla każdej wysłanej komendy

**Comment by palmemd** [comment]
Okej, dzięki
