### ISSUE TITLE
Proszę o weryfikację mojej aplikacji dla GET /offers/listing

### ISSUE THREAD

**Issue by kovel3** [allegro/allegro-api#4986]
Cześć.

Proszę o weryfikację mojej aplikacji dla GET /offers/listing

**Comment by MartaNowaczyk** [comment]
Tutaj nie weryfikujemy aplikacji. Proces weryfikacji aplikacji przejdziesz, kontaktując się przez [formularz ](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)- sprawa trafi do odpowiedniego zespołu, który zajmie się zgłoszeniem.

**Comment by kovel3** [comment]
ok
