### ISSUE TITLE
Różnica godzin w zwracanych wartościach podczas publikacji paczki

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#4987]
Używam Waszej metody _/sale/offer-publication-commands/{commandId}/tasks_ do weryfikacji publikacji ofert.
Które wcześniej publikuję za pomocą metody  _/sale/offer-publication-commands/{commandId}_

Zauważyłem że wartości **scheduledAt** oraz **finishedAt** są wcześniejsze od daty wysłania żądania publikacji ofert. 

Przykładowo żądanie wysłane jest o 2021-09-30 12:15:50.157
Natomiast wartości przez Was zwracane to: 
scheduledAt: 2021-09-30 10:15:50.737
finishedAt: 2021-09-30 10:15:50.720

Z czego wynika przesunięcie do tyłu o dwie godziny?

Co więcej **finishedAt** jest czasami wczęsniejsze niż **scheduledAt**.

Rozumiem, że wartość **scheduledAt** mówi o momencie, w którym rozpoczęła się publikacja paczki ofert, natomiast wartość **finishedAt** o dacie zakończenia publikacji paczki.

**Comment by hahyes** [comment]
Allegro zawsze zwraca czas jako UTC.
https://pl.wikipedia.org/wiki/Uniwersalny_czas_koordynowany

**Comment by MartaNowaczyk** [comment]
Dodam tylko jeszcze, że finishedAt - to czas zakończenia zadania, scheduledAt - czas, kiedy zadanie ma zostać wykonane, 
dlatego finishedAt może wystąpić wcześniej.

**Comment by marmited** [comment]
Świetnie, dzięki za informacje.
