### ISSUE TITLE
Mobile, działanie linku "https://allegro.pl", 

### ISSUE THREAD

**Issue by PietkaAppsGarden** [allegro/allegro-api#4989]
Opis problemu:
Smartfony iOS, Android
Zainstalowane aplikacje mobilne Allegro

Działanie aktualne: 
Kliknięcie linku: "https://allegro.pl" na systemie Android otworzy aplikację mobilną Allegro.
Kliknięcie linku: "https://allegro.pl" na systemie iOS otworzy stronę mobilną Allegro.

Działanie pożądane::
Kliknięcie linku: "https://allegro.pl" na systemie iOS otworzy >>>aplikację<<<  mobilną Allegro.

Pytanie:
Jak spowodować aby po kliknięcie linku: "https://allegro.pl" na iOS otworzyła się aplikacja mobilna a nie strona internetowa?

**Comment by MartaNowaczyk** [comment]
Na tym forum zajmujemy się wsparciem API allegro, dlatego w tej sprawie zapytaj proszę przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=30db29ca-fb10-434b-a5f0-fc43019af49b&subjectId=cb1f50d9-378f-4b39-a208-93de6902fb99)
