### ISSUE TITLE
Publish offer on sandbox doesn't work

### ISSUE THREAD

**Issue by filipblajiu** [allegro/allegro-api#4990]
Hello,

I try to publish an offer but i get the following error:
You don't have the required permissions to publish offer (sell blocked). Verify your account as a company.

I was able to create and activate offers a few months ago when we integrate our services with you.
Now it doesn't work anymore.
I've checked the settings and my account (filip.blajiu@frisbo.ro) is active.

What should i do?

**Comment by MartaNowaczyk** [comment]
Go to the [Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) and using the payment simulator, click on the "PAY" button. After a short time, your account will be unblocked.
