### ISSUE TITLE
PUT offer-price-change-commands - response 201 , a cena nie zmieniona

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#4991]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
```
uuidS=generateUUID()
rsta = str('https://api.allegro.pl/sale/offer-price-change-commands/{}').format(str(uuidS))
                                                
t = {
        "modification": {
            "type": "FIXED_PRICE",
            "price":{
                "amount": str(cenaDE),
                "currency":"PLN",
            }
        },
        "offerCriteria": [
            {
            "offers": [
                {
                "id": idoferty
                }
            ],
            "type": "CONTAINS_OFFERS"
            }
        ]
        }

test22 = json.dumps(t)

headers = {}
headers['charset'] = 'UTF-8'
headers['Accept-Language'] = 'pl-PL'
headers['Content-Type'] = 'application/vnd.allegro.public.v1+json'
headers['Api-Key'] = API_KEY
headers['Accept'] = 'application/vnd.allegro.public.v1+json'
headers['Authorization'] = "Bearer {}".format(sign2['access_token'])


with requests.Session() as sesja2:
    try:
        sesja2.headers.update(headers)
        r = sesja2.put(rsta, data=test22, headers=headers)
   except:
       print(r)
```

Problem polega na tym, że otrzymuję od serwera Waszego odpowiedź Response<201> jako Success, a cena jest bez zmian. W polu "amount": str(cenaDE), przesyłam Cenę z naszego systemu do Allegro.pl , kiedy aktualizacja dobiegnie końca na Allegro w dalszym ciągu cena jest nie zmieniona. Proszę o pomoc.

**Comment by hahyes** [comment]
Zasoby tego typu służą do zlecania komend, które wykonają się, gdy będzie to możliwe po stronie Allegro tj. asynchronicznie. Otrzymujesz odpowiedź 201, ponieważ zadanie zostało przyjęte. W odpowiedzi otrzymujesz id, które musisz potem sprawdzić odpytując odpowiedni zasób, czy dana komenda została zrealizowana bądź nie. Cena nie zmieni się natychmiast, to po prostu tak nie działa.

**Comment by palmemd** [comment]
Jak długo może trwać zmiana ceny po otrzymaniu odpowiedzi 201?

**Comment by hahyes** [comment]
> Jak długo może trwać zmiana ceny po otrzymaniu odpowiedzi 201?

Zwykle od tej samej sekundy do paru godzin. Niestety nie jest dane programistom znać obciążenia systemu. 

Ponadto zasób PUT /offer-price-change-commands nie waliduje większości danych w zapytaniu. Jeżeli np. nie podoba się API format ceny czy coś, to zwróci i tak status 201. Nawet jak podasz nie ten token, co powinieneś, to jest 201 (o ile oczywiście to jest poprawny token).
Dlatego musisz użyć uuid komendy do tego zasobu; https://developer.allegro.pl/redoc/redoc-static.html#operation/getPriceModificationCommandTasksStatusesUsingGET
Dostaniesz konkretne informacje, czy komenda się powiodła, lub co było nie tak.

**Comment by palmemd** [comment]
Korzystam już z tego zasobu, tylko nic mi szczególnego nie mówi. W wiadomości otrzymuje "None" , a sam wynik wygląda w większości tak:
`{'id': '1e1132c8-5659-4e06-9dcc-4c3cfad2f5cc', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}`

**Comment by hahyes** [comment]
> Korzystam już z tego zasobu, tylko nic mi szczególnego nie mówi. W wiadomości otrzymuje "None" , a sam wynik wygląda w większości tak: `{'id': '1e1132c8-5659-4e06-9dcc-4c3cfad2f5cc', 'taskCount': {'total': 0, 'success': 0, 'failed': 0}}`

Patrzysz na zły zasób. Poprawny (z detalami) ma na końcu po uuid jeszcze `/tasks`.

**Comment by palmemd** [comment]
Teraz mam coś takiego:
`{'tasks': [{'offer': {'id': '11136220532'}, 'message': None, 'status': 'NEW', 'scheduledAt': '2021-10-01T10:28:45.918Z', 'finishedAt': None, 'field': 'price', 'errors': []}]}`

**Comment by hahyes** [comment]
> Teraz mam coś takiego: `{'tasks': [{'offer': {'id': '11136220532'}, 'message': None, 'status': 'NEW', 'scheduledAt': '2021-10-01T10:28:45.918Z', 'finishedAt': None, 'field': 'price', 'errors': []}]} {'errors': [{'code': 'COMMAND_NOT_FOUND', 'message': 'Nie znaleziono zlecenia.', 'details': None, 'path': '', 'userMessage': 'Nie znaleziono zlecenia.'}]} `

Upewnij się, że nie używasz wielokrotnie tego samego UUID.

**Comment by palmemd** [comment]
Tak, UUID jest generowane losowo dla nowej komendy. Zauważyłem, po części gdzie tkwi problem, jest masa aukcji ponad 250 gdzie brakuje Nam parametrów uzupełnionych. Są jednak też produkty gdzie cenę zaktualizowało poprawnie. Dzięki /task znalazłem prawdopodobnego winowajce braku aktualizacji cen, kompletuje wszystko .xls , jeśli sprawdzą się moje przypuszczenia, temat zamknę i w każdym wypadku dam znać, dziękuje :)

**Comment by p3le** [comment]
To ja się podepnę pod ten temat. Mam ten sam problem. Tworzę zlecenie zmiany ceny, wysyłam komendę z UUID, następnie próbując odpytać ten sam UUID po `/sale/offer-price-change-commands/{commandId}/tasks` dostaję w odpowiedzi "COMMAND_NOT_FOUND". Mimo to na części ofert cena zmienia się. Można coś jeszcze zweryfikować samodzielnie w tym temacie?

**Comment by MartaNowaczyk** [comment]
@p3le tak jak pisał @hahyes upewnij się, że wpisujesz poprawny commandId.

**Comment by p3le** [comment]
> @p3le tak jak pisał @hahyes upewnij się, że wpisujesz poprawny commandId.

Tworząc zlecenie zmiany ceny wysyłam do api UUID, po chwili ten sam UUID (jednakowy jaki zwraca w odpowiedzi api) używam do sprawdzenia statusu komendy. W odpowiedzi dostaję, że komenda nie została odnaleziona. Mało tego, w sporej części przypadków cena się po prostu aktualizuje ale statusu wykonania komendy sprawdzić już nie mogę.

**Comment by palmemd** [comment]
@p3le  Polecam zapisać np. do listy wszystkie UUID jakie wykonujesz wysyłając komendy do Allegro.
Po wykonaniu wszystkich komend, odczytać listę w celu sprawdzenia statusu komend.

**Comment by MartaNowaczyk** [comment]
@p3le podaj trace-id dla wywołania z COMMAND_NOT_FOUND.

**Comment by p3le** [comment]
> @p3le podaj trace-id dla wywołania z COMMAND_NOT_FOUND.

`trace-id: dfb0ee1055aa1cc3` przy czym dziś od rana zmieniając cenę na tej konkretnej aukcji nie mam żadnych problemów, jednak nadal nie mogę sprawdzić statusu komendy.

**Comment by MartaNowaczyk** [comment]
Masz może jeszcze trace-id dla tej konkretnej zmiany ceny, żebym miała parę do porównania?

**Comment by p3le** [comment]
> Masz może jeszcze trace-id dla tej konkretnej zmiany ceny, żebym miała parę do porównania?

Zmiana ceny: `trace-id: a3d656ce834bc5bb`

**Comment by p3le** [comment]
@MartaNowaczyk chyba sprawa została wyjaśniona. Do wykonania zmiany ceny był używany zły endpoint, przez co oczekiwana odpowiedź była niepoprawna. Przepraszam za zamieszanie, ale wygląda na to, że wszystko jest już ok. Jedyne co zastanawia, to brak możliwości zmiany ceny w dniu wczorajszym.

**Comment by MartaNowaczyk** [comment]
@p3le tak samo wygląda to w logach. 
Jeśli chodzi zmianę ceny w tej ofercie to 2 ostatnie są poprawne.
