### ISSUE TITLE
Unable to create invoice for an order

### ISSUE THREAD

**Issue by filipblajiu** [allegro/allegro-api#4992]
Hello,

I want to create an invoice for an order on route order/checkout-forms/[id]/invoices but I get the following error:

{
    "errors": [
        {
            "code": "ORDER-WITHOUT-INVOICE",
            "message": "Order with id [d620e891-22a2-11ec-af07-83fa56eb1bc0] cannot have an invoice",
            "details": null,
            "path": "/order/checkout-forms/d620e891-22a2-11ec-af07-83fa56eb1bc0/invoices",
            "userMessage": "Order with id [d620e891-22a2-11ec-af07-83fa56eb1bc0] cannot have an invoice"
        }
    ]
}

How may I fix this in order to create and upload an invoice?

**Comment by MartaNowaczyk** [comment]
You can add VAT invoices only to orders where the Buyer requested it. When you are checking order data via GET order/checkout-forms/{id} - pay attention to invoice.required field. If the value is false - you cannot add an invoice.

**Comment by filipblajiu** [comment]
How can I request as a buyer an invoice when I order?
Is there a setting I need to activate?

**Comment by MartaNowaczyk** [comment]
The buyer selects the checkbox whether he wants an invoice or not (I marked it in red in the screenshot).
![image](https://user-images.githubusercontent.com/38425363/135822293-fe5b8fa2-319c-4868-905b-2f622adf3150.png)

> How can I request as a buyer an invoice when I order?

You can't.
> Is there a setting I need to activate?

No.

**Comment by filipblajiu** [comment]
I was asking about a setting to activate the invoice since that checkbox is not showing up.

![image](https://user-images.githubusercontent.com/45634782/135860567-f5ec335d-1082-461c-a25c-ad97b0e7561b.png)

**Comment by asoio** [comment]
While creating a new offer, you need to change the invoice information, in the **Invoice options and VAT rates** section:
https://allegro.pl/help/for-sellers/listing-an-offer-via-the-listing-form/how-to-add-invoice-and-vat-information-in-an-offer-5Lkv7WqO1hG
Obviously you have to have a business account to be able to do this.
