### ISSUE TITLE
Jak mogę wyłączyć EMPHASIZED_HIGHLIGHT_BOLD_PACKAGE na ofercie

### ISSUE THREAD

**Issue by Waclaw-W** [allegro/allegro-api#4993]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry,

Nie mogę wyłączyć EMPHASIZED_HIGHLIGHT_BOLD_PACKAGE
opisanej  jako "Pakiet promo"

![Screenshot_3](https://user-images.githubusercontent.com/81759361/135625509-5bf0e105-291a-4164-9e20-684545bddba1.jpg)

w zasobie sale/offer-promotion-packages 
widze takie mozliwe promocje:

![Screenshot_5](https://user-images.githubusercontent.com/81759361/135626992-92e95d2e-2371-436d-b0f1-4d3bcc3cd516.jpg)

próbowałem użyć metody POST sale/offers/7680831054/promo-options-modification
co wyłącza je wszystkie 4 szt:

![Screenshot_4](https://user-images.githubusercontent.com/81759361/135627047-60e9235b-a200-46ce-a8f8-9b3e77a6e08c.jpg)

Metoda działa ale zawsze zostaje ta jedna.  
"trace-id": "98ce8118432d2fe1"

Prosze o pomoc jak nad tym zapanować :)

**Comment by MartaNowaczyk** [comment]
Aby wyłączyć pakiet możesz skorzystać z PUT /sale/offers/{offerId} i przekazać całą strukturę danej oferty wraz ze zmienioną wartością, zgodnie ze swoim wyborem przy "emphasizedHighlightBoldPackage" powinno być false (jeżeli masz włączone wyróżnienie to jest true). Takie ustawienie "true / false" funkcjonuje dla każdej z opcji promowania w obiekcie "promotion".
[Poradnik](https://developer.allegro.pl/sale/#10-promowanie)

**Comment by Waclaw-W** [comment]
Dzień dobry, 

Bardzo dziękuję za podpowiedź. To dobry trop jeśli chcemy wyłączyć odrazu.
Jednak idąc dalej, to trochę się mija z zasadą zarządzania promocjami. Bo jak np. teraz mam wyłączyć EMPHASIZED_HIGHLIGHT_BOLD_PACKAGE ale dopiero pod koniec okresu za jaki  pobrano mi opłatę ?

W.W.

**Comment by MartaNowaczyk** [comment]
Konsultuję sprawę z odpowiednim zespołem. Jak dostanę potwierdzone informacje, dam znać.

**Comment by Waclaw-W** [comment]
Dziękuję. zaczekam :)

Pozdrawiam
W.W.

**Comment by MartaNowaczyk** [comment]
Jak podasz dla POST sale/offers/7680831054/promo-options-modification **tylko jeden** pakiet BASE promoPackage powinno zadziałać. Spróbuj i daj znać.

**Comment by Waclaw-W** [comment]
PS. 

Co jeszcze ciekawego zauważyłem, ze dwie metody podają różne czasy przyszłego naliczenia (jeśli dobrze rozumuje) np.

sale/offers/7680858161/promo-options
nextCycleDate": "2021-10-12T07:53:41.785Z  
![image](https://user-images.githubusercontent.com/81759361/136688862-57c427d1-4292-4af7-bf58-370c626949e5.png)


a  
pricing/offer-quotes?offer.id=7680858161
"nextDate": "2021-10-10T12:46:40Z",
![image](https://user-images.githubusercontent.com/81759361/136688888-6ebabced-2798-49aa-9ae9-1984222cae8e.png)

**Comment by Lukasz-Zurek** [comment]
> PS.
> 
> Co jeszcze ciekawego zauważyłem, ze dwie metody podają różne czasy przyszłego naliczenia (jeśli dobrze rozumuje) np.
> 
> sale/offers/7680858161/promo-options nextCycleDate": "2021-10-12T07:53:41.785Z ![image](https://user-images.githubusercontent.com/81759361/136688862-57c427d1-4292-4af7-bf58-370c626949e5.png)
> 
> a pricing/offer-quotes?offer.id=7680858161 "nextDate": "2021-10-10T12:46:40Z", ![image](https://user-images.githubusercontent.com/81759361/136688888-6ebabced-2798-49aa-9ae9-1984222cae8e.png)

Natomiast opisana przez Ciebie powyżej sytuacja jest możliwa. Data zakończenia cyklu (pobrania opłaty) i data zakończenia oferty - mogą się między sobą różnić.

**Comment by Lukasz-Zurek** [comment]
@Waclaw-W Przepraszam za tak długi czas oczekiwania na odpowiedź.

W sytuacji, gdy w polu **"pendingChanges"** masz już nowy pakiet promowania, jaki włączymy po zakończeniu aktualnego okresu rozliczeniowego - nie wyłączysz go korzystając z opcji **"REMOVE_NOW"**, lub **“REMOVE_WITH_END_OF_CYCLE”**. W celu wyłączenia pakietu widniejącego w **"pendingChanges"** musisz skorzystać z opcji **"modificationType": “CHANGE”**, przekazując w żądaniu ponownie ten pakiet.

Dodamy tę informację do naszego poradnika.

**Comment by Lukasz-Zurek** [comment]
@Waclaw-W Uzupełniając wczorajszą wiadomość - Twój request powinien wyglądać następująco:

```
 curl -X POST \
    'https://api.allegro.pl.allegrosandbox.pl/sale/offers/{offerId}/promo-options-modification' \
    -H 'Authorization: Bearer {token}' \
    -H 'Accept: application/vnd.allegro.public.v1+json' \
    -d '{
        "modifications": [
            {
      	     "modificationType": "CHANGE",      
      	     "packageType": "BASE",		
     	      "packageId": "emphasized1d"      
            }
        ]
    }'
```
