### ISSUE TITLE
Problem z nadaniem paczki Poczta Polska Pocztex - parcel-management/parcel-create-commands/XXX

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#4994]
Ciagle na srodowisku produkcyjnym dostaje zwrotkę: "Pickup point is incorrect".
ID punktu pobrane ze strony Poczty Polskiej (PNI=273155 x=21.053442 y=52.150325).
Wysylam taki json:

`
{
  "serviceId": 7344141,                     
  "receiver": {                             
    "address": {
      "street": "Ulica 1/1",
      "postCode": "02-996",
      "city": "Warszawa",
      "countryCode": "PL"
    },
    "email": "adres+61f795944@allegromail.pl",
    "name": "Adam Slodowy",
    "company": "",
    "phone": "501xxxxxx",
    "pointId": null
  },
  "pickup": {
    "address": {
      "street": "Rumcajsa 666",
      "postCode": "03-222",
      "city": "Warszawa",
      "countryCode": "PL"
    },
    "email": "przykladowy@emailtestowy.com",
    "name": "Firma",
    "company": "Firma s.c.",
    "phone": "602xxxxxx",
    "pointId": "273155"
},
  "items": [
    {
      "weight": {
          "value": 2,
          "unit": "KILOGRAM"
      },

      "dimensions": {
        "height": {
          "value": 20,
          "unit": "CENTIMETER"
        },

        "width": {
          "value": 20,
          "unit": "CENTIMETER"
        },

        "depth": {
          "value": 20,
          "unit": "CENTIMETER"
        }

      },
      "type": "PACKAGE",
      "description": "Produkty z firmy",
      "value": {
        "amount": "59.99",
        "currency": "PLN"
      }
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": {
      "address": {
        "street": "Piekna ulica 1 m. 666",
        "postCode": "03-222",
        "city": "Warszawa",
        "countryCode": "PL",
        "county": null
      },
      "email": "superemail@malpkamoja.pl",
      "name": "",
      "company": "FIRMA S.C.",
      "phone": "602xxxxxx"
    },
    "fileFormat": "PDF",
    "referenceNumber": "11091"
  }
`

**Comment by MartaNowaczyk** [comment]
Jesteś pewny, że `serviceId` ID usługi dostawy jest poprawne? Usługi dostawy dostępne dla zautoryzowanego użytkownika pobierzesz za pomocą [GET /parcels/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices).

Więcej info w naszym [poradniku](https://developer.allegro.pl/wza/#jak-pobra%C4%87-list%C4%99-us%C5%82ug-dostawy).

**Comment by PawelPseudo** [comment]
Tak, pobrałem usługi i poczta ma serviceId = 7344141 i taki własnie podaje.
Co moze byc problemem ?



<html>
<body>


 
--
[2] => Array
  | (
  | [id] => 7344141
  | [service] => POCZTA_POLSKA
  | [name] => Allegro Poczta
  | [owner] => ALLEGRO
  | [carrierId] => POCZTA_POLSKA
  | [additionalServices] => Array
  | (
  | [cashOnDelivery] => Array
  | (
  | [available] =>
  | [expressAvailable] =>
  | )
  |  
  | [options] => Array
  | (
  | [0] => Array
  | (
  | [name] => additionalHandling
  | [description] => Paczka niestandardowa.
  | )
  |  
  | [1] => Array
  | (
  | [name] => fragile
  | [description] => Usługa 'ostrożnie'.
  | )
  |  
  | [2] => Array
  | (
  | [name] => valuableShipment
  | [description] => Paczka wartościowa.
  | )
  |  
  | [3] => Array
  | (
  | [name] => pocztaKurier24
  | [description] => Gwarancja, że paczki (wysłane do strefy A) zostaną dostarczone drugiego dnia po dacie nadania.
  | )
  |  
  | [4] => Array
  | (
  | [name] => registeredCompanyLetter
  | [description] => Nadawanie przesyłek poleconych za potwierdzeniem odbioru.
  | )
  |  
  | [5] => Array
  | (
  | [name] => deliveryConfirmation
  | [description] => Nadawca otrzyma formularz „Potwierdzenie doręczenia” z potwierdzeniem odbioru od odbiorcy.
  | )
  |  
  | )
  |  
  | )
  |  
  | )
  |  


</body>
</html>

**Comment by MartaNowaczyk** [comment]
Podaj trace-id dla tez zwrotki z błędem.

**Comment by PawelPseudo** [comment]
dzisiaj zadziałało bez zmian w kodzie :)
dziekuje za wsparcie.

**Comment by PawelPseudo** [comment]
Jeszcze mam pytanie o kolejny krok czyli "pobieranie protokolu nadania przesylek"
Wywoluje te metode i w odpowiedzi mam http kod 204 No Content.
I nie zaraca PDFa.
Analogiczne uzycie tego dla DPD działa ok.
Czy przy Pocztexie jest jakaś rożnica ?

**Comment by MartaNowaczyk** [comment]
Status 204 otrzymasz, jeśli dany przewoźnik nie udostępnia protokołów dla przesyłek.
