### ISSUE TITLE
Pasuje do i POST /sale/product-offers

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#4995]
W jaki sposób uzupełnić sekcję "pasuje do" w metodzie: POST /sale/product-offers
?

**Comment by MartaNowaczyk** [comment]
Jak podepniesz produkt (na podstawie przekazanych danych rozpoznamy, że produkt istnieje w naszej bazie), który ma uzupełnioną sekcję "pasuje do", to dane te uzupełnią się automatycznie.

**Comment by kfijalko** [comment]
Produkty, które podpinam nie maja uzupełnionej sekcji "pasuje do".
Proszę zagadnienie sekcji "pasuje do" przemyśleć ponownie.
Wskazujecie metodę /sale/product-offers jako preferowana i rozwijaną a nie uwzględnia ona kluczowego pola dla części motoryzacyjnych.
W bazie produktów chyba tylko części tecdoc'owe mają uzupełnioną sekcję pasuje do.
Osobiście uważam, że zarządzanie sekcją pasuje do w częściach motoryzacyjnych jest trudne.
W tecdoc'u robi to całe stado dystrybutorów/producentów.
W katalogu produktów allegro sprzedawcy zamienników nie dadzą sobie z tym rady przy pomocy formularza "zgłoś błąd w produkcie".

Skusił mnie tytuł poradnika: "Jak jednym requestem wystawić ofertę powiązana z produktem" ;)
Teraz żeby wystawić ofertę:
1) muszę wystawić ofertę bez "pasuje do"
2) pobrać dane oferty /sale/offers
3) wysłać dane uzupełnione o sekcję "pasuje do"

**Comment by MartaNowaczyk** [comment]
Rozumiem, wrzuć to proszę do naszych [sugestii](https://github.com/allegro/allegro-api/discussions).

**Comment by MartaNowaczyk** [comment]
Widziałam, że dodałeś. Dzięki!
