### ISSUE TITLE
[/sale/product-offers] błąd UnableToCheckIfImagesExistException 

### ISSUE THREAD

**Issue by michalfurtak** [allegro/allegro-api#4996]
Cześć,
wystawiam oferty korzystając z endpointa /sale/product-offers, a później je aktywuję. Na 10 tysięcy wystawionych ofert w przypadku około 1.5procenta dostaję zwrotkę:
`{
	"errors": [
		{
			"code": "UnableToCheckIfImagesExistException",
			"message": "Unable to check if images [11cf3f/90aeb75b46f1b1065732bd52f483] exist",
			"details": null,
			"path": "product.parameters",
			"userMessage": "Unable to check if images [11cf3f/90aeb75b46f1b1065732bd52f483] exist"
		}
	]
}`

Obrazek jest poprawny tj. serwer zwraca status 200 i obrazek w formacie jpg.
Co może być przyczyną takiego błędu?

pozdrawiam
MF

**Comment by MartaNowaczyk** [comment]
Podaj proszę trace-id dla przykładowego wywołania z błędem.
