### ISSUE TITLE
sale/product-offers/ ambiguousValue customValuesEnabled: true proper value error

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#4997]
i use "https://api.allegro.pl/sale/product-offers/"

my product is in the Category of "76034"
CategoryID 76034
Parameter "id": "201017",
           "name": "Materiał dominujący",
           "type": "dictionary",
           "required": true,
           "requiredForProduct": true,
           "unit": null,
           "options": {
                "variantsAllowed": false,
                "variantsEqual": true,
                "ambiguousValueId": "201017_257870",
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": true
            },

The json in the product I created
                    }, {
                        "id": "201017",
                        "values": ["brak"],
                        "valuesIds": ["201017_257870"]
                    }, {

Server message;
Unable to create product without proper values ​​in all required parameters: [Materiał dominujący]

I cannot detect this information for some products, but I want to upload these products to Allegro. What can I do

is this true;
if the parameter contains ambiguous value and
 If "customValuesEnabled" is true, then I have to set a value to my parameter. 
when I don't set a value, I get an error saying that you must send a value.

Thanks.

**Comment by hahyes** [comment]
Yes, some parameters with ambiguous value require to add custom value to it. If `customValuesEnabled` is set on `true`, probably it needs custom value filled. Not in every case, can't tell what parameters need it or not.

**Comment by PrzemyslawLukanowski** [comment]
You received this error because "brak" is not a proper custom value. If you choose an ambiguous value (i.e. "other"), you should provide the valid value which is not available in the list of values. "Brak" in this case means none/empty.

**Comment by yavuzresif** [comment]
As I wrote above, I do not have this information for some products, is there a general expression that I can set here and not return an error?

**Comment by kfijalko** [comment]
don't fill values if yu dont know proper value:
{
"id": "201017",
"valuesIds": ["201017_257870"]
},

**Comment by PrzemyslawLukanowski** [comment]
@yavuzresif Unfortunately no, this parameter is required so we expect a proper value.
@kfijalko Custom value is required to be sent when creating a product if the ambiguousValueId was chosen.
