### ISSUE TITLE
Błąd komunikacji z API inpostu

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#4998]
Występuje problem: 
 - [ X] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Przy generowaniu paczki przez WzA mam błąd komunikacji. Czy to problem po waszej stronie?
Nr paczki :
e6232eac-9d8d-4774-a2a7-6f4b4bf91932
Wystąpił błąd komunikacji z API przewoźnika

**Comment by Radeq** [comment]
API Inpostu (ShipX) ma problemy więc zapewne wpływa to również na Inpost wysyłam z Allegro

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam, występują aktualnie problemy po stronie InPostu.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Czy problemy nadal występują po stronie API InPostu?

**Comment by PrzemyslawLukanowski** [comment]
@hahyes Tak, problemy nie zostały jeszcze wyeliminowane.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy informację, że problem został już rozwiązany - powróciła możliwość generowania etykiet i tworzenia paczek.

**Comment by hahyes** [comment]
> Otrzymaliśmy informację, że problem został już rozwiązany - powróciła możliwość generowania etykiet i tworzenia paczek.

Dziękuję bardzo za informację zwrotną.
