### ISSUE TITLE
Problem z logowaniem do sandboksa

### ISSUE THREAD

**Issue by coobitus** [allegro/allegro-api#5]
Mam problem z logowaniem do API Sandboksa. Podaję całą strukturę do metody doLoginEnc, łącznie z zahashowanym hasłem które dostałem przed chwilą na maila (zrobiłem wcześniej reset hasła - który notabene wcale tego hasła nie resetuje ...). I ciągle dostaję komunikat ERR_USER_PASSWD (Zła nazwa użytkownika lub hasło!). Są jakieś problemy na sandboksie? Proszę o pomoc bo przez to jakiekolwiek testowanie na sandboksie jest o kant d... potłuc... Aukcji testowych tez nie mogę bez tego oczywiście wystawić

**Comment by coobitus** [comment]
Dodam jeszcze że ten sam kod źródłowy działa bez problemu w środowisku produkcyjnym. I działał w Sandboksie jeszcze na początku stycznia ....

**Comment by MarcinLuczak** [comment]
Jaki login ma Twoje konto na Sandboxie?

Już wkrótce udostępnimy nowe środowisko testowe, które powinno być wolne od tego problemu.

**Comment by coobitus** [comment]
mój login to : cubitus2

**Comment by coobitus** [comment]
Cieszę się że "już wkrótce" udostępnicie ale ja potrzebuję mieć dostęp już teraz :-)

**Comment by MarcinLuczak** [comment]
Zdaję sobie z tego sprawę, ale nie jestem w stanie powiedzieć kiedy uda się przywrócić ten dostęp. Przekazałem zgłoszenie do odpowiedniego działu.

**Comment by coobitus** [comment]
To sobie pogadaliśmy tydzień temu i jak do tej pory nic się w temacie nie zadziało ...

**Comment by MarcinLuczak** [comment]
Problem, o którym mowa, nie jest prosty. Jego usunięcie trochę może potrwać. Proszę o cierpliwość.

**Comment by vanszic** [comment]
Witam,
takie samo zgłoszenie przesłałem formularzem kontakowym 13 lutego "[Ticket#1245046453] Mam problem z logowaniem" i również czekam na odpowiedź. Nie jest to chyba odosobniony przypadek, bo sprawdzałem to również na koncie kolegi i ma to samo. Jedna wspólna cecha dla obu kont na sandboxie była taka, że jakoś z 2 lata temu miałem działające konto na sandboxie i korzystałem również z konta kolegi aby generować sprzedaż z jednego konta a zakup z drugiego i było OK. W lutym br jak wszedłem w menu Api na produkcji, nie miałem wygenerowanego klucza (mimo tego, że 2 lata temu miałem wygenerowane) więc go wygenerowałem i zrestartowałem hasło do sandboxa, po otrzymaniu @ z hasłem nie mogę się zalogować.

**Comment by coobitus** [comment]
@vanszic : z tym brakiem klucza u mnie dokładnie to samo było; a wcześniej korzystałem z tego konta do testów parę miesięcy temu

**Comment by MarcinLuczak** [comment]
@vanszic 
Zgadza się, to nie jest odosobniony przypadek, dlatego usunięcie tego problemu nie jest łatwe. Proszę o cierpliwość.
