### ISSUE TITLE
Logowanie na środowisko deweloperskie przez portal

### ISSUE THREAD

**Issue by mbartuzi** [allegro/allegro-api#50]
Rozpocząłem próby uwierzytelnienia się i o ile wszystko działa poprawnie na środowisku produkcyjnym, to na deweloperskim nie mogę się zalogować. Otrzymałem mailowo login i hasło do Sandbox WebAPI, ale przy próbie logowania zawsze otrzymuję informację, że dane są niepoprawne. Resetowanie hasła nie pomaga - otrzymuję za każdym razem to samo, które mimo wszystko nie działa.

**Comment by 4kssoft** [comment]
Też miałem ten problem. Logowanie działa tylko w subdomenie ssl.
Spróbuj przez: https://ssl.allegro.pl.webapisandbox.pl/login/auth

**Comment by mbartuzi** [comment]
W subdomenie też logowanie mi nie działa. Co więcej, wyświetla mi się wtedy "mediation error" w lewym górnym rogu.

**Comment by MaciejPotepa** [comment]
Jak widzicie, obecnie mamy kłopoty z logowaniem do Sandboxa. 

Wbrew pozorom jest to całkiem skomplikowany problem do rozwiązania. Niestety, nie mam informacji kiedy go usuniemy. 

Mogę powiedzieć, że jeszcze w tym tygodniu planujemy uruchomienie nowego środowiska testowego, na którym ten problem nie powinien występować.

**Comment by amarel123** [comment]
Problemy z sandboxem zgłaszam od połowy grudnia więc się nie trudźcie Panowie :) Może nowe środowisko coś zmieni, ale obiecują mi je od stycznia.
