### ISSUE TITLE
question on orders API

### ISSUE THREAD

**Issue by ventoh** [allegro/allegro-api#500]
Hello, i'm start using the rest api for getting orders and i would ask a question to you.

In my ecommerce i have variations product like size or colors, etc that i can publish in the offer via API. That's ok. My question is related to orders API:

When a user purchase a product i can fetch offer id, price, etc but i haven't any info about what size or color the user has purchased. So i can't update my internal software system according. Is there a way to get info about variations product in the api orders?

thank you.

**Comment by KrzysztofLukanowski** [comment]
Hi,

When you sold something, you can get information about order by [REST API](https://developer.allegro.pl/en/documentation/#/order-management/get_order_checkout_forms) or [WebAPI](doGetPostBuyFormsDataForSellers). We show in responses number of the offer. So, you can get the information about specific offer by [REST API](https://developer.allegro.pl/en/documentation/#/offer-management/getOfferUsingGET) or [WebAPI](https://allegro.pl/webapi/documentation.php/show/id,1134#method-output) and in next step you can update quntify in offers.

**Comment by ventoh** [comment]
Please, suppose i have published a product like shoe having size 36,37,38,39 and 40. After I have published the product the api return the offer_id. 
Now suppose one user has purchased the shoe with size 38. Then i can get the offer_id for that order via rest api. That's ok. 
Also using the rest api /sale/offers/{offerId} i can get all fields of the particular offer. But this doesn't provide any info about that order.
How can I get what size has been purchased ?

**Comment by ventoh** [comment]
thanks you. In short, are you saying that i need to create an offer for each size and color of my products? correct?

**Comment by KrzysztofLukanowski** [comment]
Exactly. In next step, you will be able to assemble different variants of the same product with one mask. It will possible with tool of many variants. You can do it by [graphic site](https://allegro.pl/variants-editor-web/) or [REST API](https://developer.allegro.pl/news/2018-07-09-Wielowariantowosc/).

**Comment by ventoh** [comment]
ok, so there isn't a way to know if an order has been shipped or refuded?
