### ISSUE TITLE
Połączenie kont allegro - dodatkowe możliwości API

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#5002]
Witam,

Połączyliśmy dwa konta allegro.pl w jedno wg. możliwości "Połącz konta". Czy teraz po połączeniu API z kontem głównym mogę pobierać listę ofert podłączonego konta w tym zmieniać ceny i stany towarów?

Dziękuje z góry za odpowiedź.
Pozdrawiam.

**Comment by MartaNowaczyk** [comment]
Witam. Ta opcja jest bardziej dla tych, którzy zarządzają swoją sprzedażą na allegro przez panel allegro. W API pobierzesz oferty, ale edycji już nie zrobisz. Poza tym nie dostaniesz w pobranej liście z jakiego konta jest oferta, więc musisz to trzymać po swojej stronie. Zamówień też nie obsłużysz.

**Comment by palmemd** [comment]
To jak mam zmienić ceny na różnych kontach na Allegro przez API jak łącząc się musze zalogować się na konkretne konto?

**Comment by MartaNowaczyk** [comment]
Tak, musisz wygenerować token dla każdego z kont oddzielnie. Później możesz skorzystać z [refresh_tokena](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena)
