### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by Liketodev3** [allegro/allegro-api#5003]
Hi. Refresh token lasts for 3 months with documentation. But it expires after several times of usage? Is there another way how to use it?

**Comment by MartaNowaczyk** [comment]
Use refresh_token - you can find more information [here](https://developer.allegro.pl/en/auth/#extending-token-validity).

**Comment by hahyes** [comment]
> Hi. Refresh token lasts for 3 months with documentation. But it expires after several times of usage? Is there another way how to use it?

Refresh token expires on first usage, if not used it lasts for 3 months. After using refresh token you are getting new pair of access token and refresh token.
