### ISSUE TITLE
Kontakt w sprawie wykorzystania API

### ISSUE THREAD

**Issue by IamHellToday** [allegro/allegro-api#5005]
Cześć, w sumie na stronie ciężko mi wyczytać z kim mogę się skontaktować w sprawie wykorzystywania API w celach tworzenia komercyjnej analityki. Jesteście w stanie podesłać jakiś adres mailowy? Bo rozumiem, że standardowy formularz weryfikacyjny aplikacji jest dla sprzedających, ja natomiast się pod tę grupę nie łapię. Dajcie proszę znać, dzięki.

**Comment by MartaNowaczyk** [comment]
Jeśli chodzi o weryfikację, to jest jedna droga dla aplikacji i sprzedających. Aby przejść proces weryfikacji skontaktuj się przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by IamHellToday** [comment]
Dzięki Marta. Nie wiem czy wysłałaś poprawny link, bo dotyczył bezpośrednio kwestii konkretnej ofert, natomiast wysłałem tam zapytanie.

**Comment by MartaNowaczyk** [comment]
Spoko, powinno trafić.
