### ISSUE TITLE
PARAMETER_MISMATCH podczas zapytania sale/product-offers

### ISSUE THREAD

**Issue by artuswo443** [allegro/allegro-api#5006]
**Założenie z przykładem:** 
- Utworzenie oferty wraz z produktem (Kubek czerwony termiczny)
- Utworzenie podobnej oferty przez innego sprzedawcy z tym samym produktem (Kubek czerwony termiczny)
- Utworzenie podobnej oferty przez innego sprzedawcy z podobnym produktem (Kubek zielony termiczny) 

Pierwszy podpunkt działa jak należy. Podczas drugiego, spełniając założenia, że parametry są takie same, także działa jak należy. Problem pojawia się przy trzeciej opcji, gdy:

- Wartość conajmniej jednego parametru produktu jest RÓŻNA od uprzednio dodanej oferty z produktem. Skutkuje to poniższym błędem:
```
 "errors": [
        {
            "code": "PARAMETER_MISMATCH",
            "message": "The provided parameter 'Manufacturer Code'(224017) value (1231) does not match the existing parameter value (123)",
            "details": null,
            "path": "product.parameters",
            "userMessage": "The provided parameter `Manufacturer Code` value `1231` does not match the existing parameter value `123`."
        }
    ]
```
- Wartość parametrów produktu jest dokładnie TAKA SAMA, lecz próbuję 'nadpisać' parametr podając go w ofercie. Skutkuje to poniższym błędem:
```
 "errors": [
        {
            "code": "ParameterCategoryException",
            "message": "Unprocessable Entity",
            "details": null,
            "path": "",
            "userMessage": "Given parameter id `224017:Manufacturer Code` should no have been passed as `offer` parameter."
        }
    ]
```

Próbowałem na wiele różnych sposobów, z podobnym rezultatem. Nie ma znaczenia, czy produkt jest dodawany wraz z ofertą, czy osobno. Jeśli wartość parametru się zmienia, jest błąd informujący, że dany produkt istnieje. Np podczas zapytania `/sale/product-proposals` z identycznymi parametrami i wartościami, lub zmienionymi następnie wartościami:
```
"errors": [
        {
            "code": "ProductDuplicate",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": "Produkt z takimi danymi już istnieje. Skontaktuj się z autorem aplikacji."
        }
    ]
```

Podsumowując, chciałbym dodać oferty z następującymi produktami "Kubek czerwony termiczny", "Kubek zielony termiczny". W jaki sposób mam to zrobić, aby zmienić parametry produktu (ponieważ są i zdecydowanie mogą być różne) i wystawić ofertę bez błędu?

**Comment by PrzemyslawLukanowski** [comment]
Produkt, który utworzyłeś na początku, posiada numery EAN 0123456789500, 123456789500. Za każdym razem, nawet jeśli zmienisz kod producenta, to zamiast tworzyć nowy produkt, będziemy próbowali połączyć ofertę z wcześniej utworzonym - id a65ef249-f5a7-4a6b-aeea-3eaac4bb5219. Ze względu na niezgodność danych - zwrócimy błąd. Jeśli zatem chciałbyś utworzyć nowy produkt dla jego innej wersji kolorystycznej, musisz posłużyć się innym numerem EAN.
