### ISSUE TITLE
Brak możliwości zmiany Formatu wygenerowanej etykiety 

### ISSUE THREAD

**Issue by 889konrad889** [allegro/allegro-api#5007]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

 

metoda pod adresem 
https://api.allegro.pl/parcel-management/parcels/label?parcelId=7740851&pageFormat=A6
Brakuje parametru rodzaju pobranej etykiety (pdf)(zpl)(epl) 
metoda pobiera tylko taki rodzaj etykiety jaki został wybrany przy generowaniu etykiety bez możliwości jego zmiany.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nie należy tego traktować jako błąd i jest to zgodne z naszymi założeniami. Wspominamy o tym w [naszym poradniku](https://developer.allegro.pl/wza/#jak-utworzy%c4%87-etykiet%c4%99-na-paczk%c4%99):

> W odpowiedzi otrzymasz plik PDF, EPL lub ZPL (w zależności od wybranego formatu na etapie tworzenia paczki)

**Comment by 889konrad889** [comment]
W takim razie jest to ewidetny błąd w fazie projektowania funkcji, możliwe że osoba odpowiedzialna za to nie miała doczynienia z niezbędnością takiej funkcjonalności wcześniej i tego nie przewidziała.

Wszystkie synchronizacje APi z którymi miałem doczynienia: Inpost, Gls, DPD, posiada funkcjonalność wyboru rodzaju etykiety przy jej pobieraniu. 

"plain/txt"  zajmuje mniej zasobów, przy generowaniu oraz transferze niż PDF.

Brak możliości wybodu rodzaju pobieranej etykiety powoduje spore kłopoty:
Generowanie etykiet np z poziomu Eazy Uploadera na jednym stanowisku, 
następnie gdy z bazy oline'owy system pakowania oparty na PHP pobierze etykiete przez API chce wysłać ją na drukarke zebry.
a na innym stanowisku pakowania z drukarką datamaxa.

Uprzejmie proszę o zmianę struktury zapytanie dodając odpowiedni parametr.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie - zgodnie z [naszym newsem](https://github.com/allegro/allegro-api/issues/4337), wszelkie sugestie, które dotyczą rozwoju API, możesz zgłosić w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by 889konrad889** [comment]
Panie Przemysławie, 
To nie sugestia zmiany, a zgłoszenie ewidetnego błędu w fazie projektowania funkcji, która działa "na odwrót"  powodując problemy z obsługą zamówień.
Z wyrazami szacunku Konrad Woźniak

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, konsultuję jeszcze ten temat z zespołem odpowiedzialnym za funkcjonalność. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej szczegółów.

**Comment by 889konrad889** [comment]
Prosze o informację jaki jest wynik konsultacji?? minęło 30dni, a błąd jak występował jak występuje.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za spóźnioną odpowiedź - niestety, ale na tę chwilę nie mamy możliwości wprowadzenia zmian, ponieważ jesteśmy ograniczeni zewnętrznym dostawcą usług. Jeśli zmieni się coś w tym temacie, opublikujemy odpowiedni komunikat na naszej stronie.
