### ISSUE TITLE
(400) Bad Request - https://api.allegro.pl/parcel-management/parcel-create-commands/

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5010]
Dlaczego otrzymuję błąd 400?

wywołuję PUT na zasobie https://api.allegro.pl/parcel-management/parcel-create-commands/f8360715-d854-4189-a906-3ee275ed255a

zgłoszenie nr 17935191, a w nim: pełny request oraz response

**Comment by PrzemyslawLukanowski** [comment]
W komunikacie  odpowiedzi zwracamy dokładną treść błędu, w Twoim przypadku sekcja `"items"` jest nieuzupełniona, a w polu `referenceNumber` znajduje się niedozwolony znak `:`

```
{
	"errors": [{
		"code": "VALIDATION_ERROR",
		"message": "wielkość musi być pomiędzy 1 a 10",
		"details": "Invalid value: []",
		"path": "items",
		"userMessage": "wielkość musi być pomiędzy 1 a 10"
	}, {
		"code": "VALIDATION_ERROR",
		"message": "musi pasować do wzorca " [A - Za - z0 - 9 - _] + "",
		"details": "Invalid value: Client:39979345",
		"path": "label.referenceNumber",
		"userMessage": "musi pasować do wzorca " [A - Za - z0 - 9 - _] + ""
	}]
}
```
