### ISSUE TITLE
Błędne i niezrozumiałe typy MIME w dokumentacji swagger.yaml

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5011]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [X] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**
Witam,

dokumentacja zawarta w pliku swagger.yaml zawiera błędne informacje, które powinny zostać poprawione.

1. Nie ma takiego typu MIME jak `plain/text`. Istnieje wyłącznie `text/plain`. Zgodnie z dokumentacją choćby starszej specyfikacji RFC2046: https://datatracker.ietf.org/doc/html/rfc2046#section-4.1
2. Kolejna zagwozdka, typ zawartości '*/*', który ma chyba być placeholderem? Skoro Content-Type odpowiedzi w tym wypadku jest przypisany do konkretnego schematu (np. AuthError) bądź struktury danych (np. dane binary oznaczone typem `*/*`, czemu tu nie ma `application/octet-stream` w takim wypadku?), czemu dokumentacja mówi mi, że zwracaną przez zasób zawartością będzie "cokolwiek"? Czy błędy wyświetlane przez REST API Allegro nie należą do schematu `application/vnd.allegro.public.v1+json`? 

Proszę o poprawienie tych błędów w dokumentacji.

**Comment by MartaNowaczyk** [comment]
Dzięki za uwagi. Sprawdzimy naszą dokumentację.
