### ISSUE TITLE
"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5017]
paczka, jaką próbuję stworzyć to Allegro Punkty Kolporter, epaka
nie ma takiej metody wśród zwracanych przez https://api.allegro.pl/parcel-management/delivery-services
jest "Allegro Punkty":  11202211, więc uznałem, że to musi być to

wywołuję GET na zasobie https://api.allegro.pl/parcel-management/parcel-create-commands/e0099751-2773-11ec-93cb-097c1c8f08e4
żeby sprawdzić status tworzenia paczki i otrzymać parcelId
otrzymuję błąd o treści: "Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"

**Comment by PrzemyslawLukanowski** [comment]
Pamiętaj, że dla każdej nowej komendy musisz użyć nowego UUID - są one jednorazowego użytku. W tym przykładzie użyłeś tej samej wartości, dlatego otrzymujesz komunikat dla wcześniejszego zadania.

**Comment by ciaglok2** [comment]
Czy te numery serviceId się codziennie zmieniają? Czy one są różne dla każdego konta Allegro?

**Comment by PrzemyslawLukanowski** [comment]
Tak, numery są inne dla różnych kont, ale w ramach jednego konta nie powinny się zmieniać.
