### ISSUE TITLE
Aktualizacja na aukcji bez konieczności dwuetapowej weryfikacji oraz z mozliwością podpięcia aplikacji do wielu kont

### ISSUE THREAD

**Issue by JaroszPatryk** [allegro/allegro-api#5018]
Przez baselinker wypycham aukcje na różne konta allegro. Chciałbym aktualizować w aukcjach czas dostawy. Czy mogę to zrobić bez dwuetapowej weryfikacji jeżeli chodzi o komunikację z konkretnym kontem? Czy mogę podpiąć własną aplikacje w aplikacjach allegro, aby nie musieć tworzyć dla każdego konota oddzielnej aplikacji do aktualizacji czasu dostawy?

**Comment by JaroszPatryk** [comment]
W sytuacji kiedy mam podpięte już 2 aplikację w jaki sposób mogę dodać kolejną do konta allegro? Jeżeli będę miał aplikację podpiętą pod wiele kont, jak będę rozróżniał wyciągane aukcje ?

**Comment by PrzemyslawLukanowski** [comment]
Dwustopniowa weryfikacja jest wymagana do zarejestrowania aplikacji, ale nie do uzyskania tokena dla danego użytkownika.
