### ISSUE TITLE
Receiver point is incorrect - Orlen Paczka

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5019]
Na produkcji, podstawiam id punktu odbiorcy z danych zamowienia czyli punkt 155002
I caly czas komunikat jak w temacie w metodzie: parcel-management/parcel-create-commands/UUID

"serviceId": 13188715 
"pointId": "155002"

                    [id] => 13188715
                    [service] => ORLEN
                    [owner] => CLIENT
                    [carrierId] => ORLEN

Co może być nie tak ?

**Comment by PawelPseudo** [comment]
mozna prosic o informacje ?

**Comment by Lukasz-Zurek** [comment]
Dziękuję za przesłany UUID. Przekazałem to dalej do weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@PawelPseudo Przekazywany "pointId" jest nieprawidłowy. Powinieneś przekazać go w dłuższym formacie np. _WR-225937-KK-02_. Punkt ten możesz pobrać bezpośrednio z API przewoźnika.

**Comment by PawelPseudo** [comment]
Tylko taki pointid (155002) dostaje w zamowieniu, wiec taki punkt wybrał klient.
Mam zgadywać który punkt wybrał klient czy moze jest jakies mapowanie tych punktow ?

**Comment by CF-WR617AC** [comment]
Pokażę Ci jak ten problem rozwiązano w Sello:

https://forum.insert.com.pl/index.php?/topic/70941-allegro-orlen-paczka-wza-przyk%C5%82ad-konfiguracji/&tab=comments#comment-361195

Dodam, że długa nazwa punktu powinna być gdzieś mimo wszystko zwracana w transakcji, więc moim zdaniem Twoje twierdzenie, że nie masz tej długiej nazwy jest błędne.

**Comment by CF-WR617AC** [comment]
Polecam się. Fan Daniela Obajtka i jego ORLEN paczki :D
