### ISSUE TITLE
Pobieranie zamówień, statusy zamówień, identyfikator paczki 

### ISSUE THREAD

**Issue by jchodubska** [allegro/allegro-api#502]
Dzień dobry, mam kilka pytań

Czy można już w pełni korzystać z nowych zasobów w Allegro REST API (chodzi mi o GET /order/checkout-forms, GET /order/checkout-forms/{id})? Czy są one jeszcze w wersji beta?

W jaki sposób pobrać status zamówienia, wykorzystując web api? I czy istnieje możliwość zmiany statusu zamówień w rest api/ web api?

Czy jest gdzieś zapisywany numer przesyłki (web/rest api)? W web api, metoda doGetPostBuyFormsDataForSellers zwraca tablice postBuyFormShipmentTracking zawierającą postBuyFormPackageId (id paczki) ale w sprawdzonych przeze mnie zamówieniach zawsze jest ona pusta.

**Comment by PawelTaberski** [comment]
Jak korzystać z metod do obsługi zamówień w REST API opisaliśmy [tutaj](https://developer.allegro.pl/orders/). Zachęcam do zapoznania się z tym poradnikiem. Obecnie wszystkie metody do obsługi zamówień w REST API są w wersji beta, ale są one w pełni funkcjonalne jak najbardziej zachęcamy do korzystania z nich. Jeśli napotkasz na jakieś problemy z tymi zasobami to prosimy o kontakt.
Odnośnie obsługi zamówień przez WebAPI całość tego zagadnienia opisaliśmy [tutaj](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421).
Odnośnie Twoich dodatkowych pytań to:
- status zamówienia możesz obecnie zmienić tylko przez Moje Allegro
- przez Web API możesz dodać numer przesyłki metodą [doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744) i później dane te będą widoczne w strukturze o której wspomniałeś. Przez REST API nie ma jeszcze takiej możliwości.

**Comment by jchodubska** [comment]
Czy allegro api umożliwia pobieranie/wysyłanie danych o liście przewozowym?

**Comment by PawelTaberski** [comment]
Jeśli dobrze rozumiem o co pytasz, to numer przesyłki możesz dodać przy pomocy metody 
[doAddPackageInfoToPostBuyForm](https://allegro.pl/webapi/documentation.php/show/id,744).

**Comment by jchodubska** [comment]
Tak, dziękuje. Czy rest api daje taką możliwość? Albo chociaż planujecie wprowadzić taką metodę?

**Comment by jchodubska** [comment]
A czy istnieje możliwość anulowania zamówienia?

**Comment by PawelTaberski** [comment]
Nie ma metody w API do anulowania zamówienia. Nie może Pan anulować przez API czyjegoś zakupu. Jednakże np. w przypadku rezygnacji z transakcji przez kupującego może Pan wystąpić o zwrot prowizji są do tego dedykowane [metody w WebAPI](https://allegro.pl/webapi/documentation.php).
