### ISSUE TITLE
Wysłanie zapytania z obrazem produktu

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#5020]
Witam,
próbuję w PHP przesłać zapytanie z zmienną ($imageUrl) zawierającą adres url obrazu, ale w odpowiedzi otrzymuję poniższy błąd:
`{"errors":[{"code":"RequestNotReadable","message":"Unable to parse request body.","details":null,"path":null,"userMessage":"Invalid upload image request. Please contact the author of the application."}]}`

Zapytanie wygląda następująco:
```
public function postProductImage($imageUrl, $offerId)
        {
            print_r($imageUrl);
            echo '</br>';
            $curl = curl_init();

            curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://api.allegro.pl.allegrosandbox.pl/sale/images',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS =>"{
                'url': $imageUrl
            }",
            CURLOPT_HTTPHEADER => array(
                'Accept: application/vnd.allegro.public.v1+json',
                'Content-Type: application/vnd.allegro.public.v1+json',
                "id_offer: $offerId",
                'Authorization: Bearer ' . $this->token,
            ),
            ));

            $response = curl_exec($curl);

            curl_close($curl);
            echo $response;
        }
```

W jaki sposób poprawić zapytanie by było poprawne ?

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy adres dla wysyłki obrazków to https://upload.allegro.pl.allegrosandbox.pl.

**Comment by Kasia13130** [comment]
Niestety nadal mam problem z przesłaniem obrazku. Próbowałam przez Postman przesłać obraz i się powiodło: 
`{
    "expiresAt": "2021-10-11T13:34:45.856518Z",
    "location": "https://a.allegroimg.allegrosandbox.pl/original/11814f/668f8136423a8cadc7fe327d8c00"
}`
Natomiast od strony PHP w dalszym ciągu otrzymuję błąd:
`{"errors":[{"code":"RequestNotReadable","message":"Unable to parse request body.","details":null,"path":null,"userMessage":"Invalid upload image request. Please contact the author of the application."}]}`
Przypuszczam, że mam błąd składni lecz nie wiem w którym miejscu. 
Dodałabym TraceId, ale w nagłówkach odpowiedzi go nie otrzymuję w przeciwieństwie do nagłówków Postman.
Poniżej zamieszczam aktualny request:
```
public function postProductImage($imageUrl, $offerId)
    {        
        $curl = curl_init();

        curl_setopt_array($curl, array(
        CURLOPT_URL => 'https://upload.allegro.pl.allegrosandbox.pl/sale/images',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => $imageUrl,
        CURLOPT_HTTPHEADER => array(
            'Accept: application/vnd.allegro.public.v1+json',
            'Content-Type: application/vnd.allegro.public.v1+json',
            "id_offer: $offerId",
            'Authorization: Bearer ' . $this->token,
        ),
        ));

        $response = curl_exec($curl);

        curl_close($curl);
        echo $response;
```

**Comment by Radeq** [comment]
@Kasia13130 jak wysyłasz w postaci linku to musi ono być w parametrze url ( https://developer.allegro.pl/advertisement/#3-zdjęcia )

`CURLOPT_POSTFIELDS => http_build_query(['url'=> $imageUrl])`

**Comment by Kasia13130** [comment]
@Radeq udało się poprawić zapytanie i wysłać:
`CURLOPT_POSTFIELDS => json_encode(['url' => $imageUrl])`
Dziękuję za pomoc
