### ISSUE TITLE
Jak przez API pobrać etykiety dla kilku paczek jednocześnie? (WzA)

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5021]
UI zapewnia taką funkcjonalność, ale w dokumentacji API nic na ten temat nie znalazłem.

**Comment by Lukasz-Zurek** [comment]
Nie mamy planów wdrożenia takiej funkcjonalności. Zachęcam Ciebie jednak do utworzenia wątku w [zakładce Discussions](https://github.com/allegro/allegro-api/discussions), gdzie możesz opisać sugestię.
