### ISSUE TITLE
Zgłoszenie na hackerone

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#5022]
Dzień dobry
Znalazłem w waszym systemie trochę dziur i chciałem wam to pozgłaszać. Dotyczy to błędów walidacji, dziur poważnych pozwalających na pobieranie danych. Pierwsze zgłoszenie zrobiłem dotyczące wpisania w koncie imienia i nazwiska małżonka - zostało przez waszego pracownika Pawła Sobótkę odrzucone z adnotacją 'SPAM'

Pytanie mam do was : Czy wy traktujecie zgłoszenia innych deweloperów poważnie? Bo zgłosiłem was dość poważną lukę w systemie która umożliwia zwiększenie kredytu i robienie zakupów za większe kwoty a zostałem zwyczajnie olany. Mam więcej znalezionych luk , włącznie z luką która umożliwia dostęp do danych wrażliwych. Nie będę ich publikował do momentu do kiedy nie przeprosicie mnie i nie zmienicie statusu zgłoszenia które wysłałem. To jest mój oficjalny foch....

#foch #pawelsobotka #hackerone

**Comment by d48u** [comment]
@qshop123 wygląda na to że support ma archadonistyczne podejście do takich zgłoszeń

**Comment by Lukasz-Zurek** [comment]
@qshop123 Co prawda temat nie dotyczy API, proszę jednak o podanie numeru sprawy. Zapewne nastąpiła tutaj pomyłka, za którą w imieniu naszego Serwisu - serdecznie przepraszamy. Jednocześnie dziękujemy za zgłoszenie.
