### ISSUE TITLE
X-Press Courier na sandbox

### ISSUE THREAD

**Issue by mlonc** [allegro/allegro-api#5024]
Czy na koncie sprzedającego na sandboxie trzeba coś aktywować by cennik dostawy z X-Press Courier wyświetlał się poprawnie w ofertach? Na chwilę obecną gdy kupuje coś i w ofercie jest cennik tylko z X-Press to przy wyborze sposobu dostawy mam "Koszt dostawy ustalony ze sprzedawcą"

![image](https://user-images.githubusercontent.com/30781954/136784305-db005070-05a2-411b-92a6-31f15f3b832d.png)

Nazwa konta: **sandboxASCO_SI**

**Comment by MaciejFrackowiak** [comment]
Weryfikuję problem z odpowiedzialnym zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
W przypadku X-Press Couriers konieczne jest ustalenie granicznych godzin zakupu - możesz tę opcję edytować w [ustawieniach dostawy](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy).

**Comment by mlonc** [comment]
> W przypadku X-Press Couriers konieczne jest ustalenie granicznych godzin zakupu - możesz tę opcję edytować w [ustawieniach dostawy](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy).

Ok ustawiłem, poczekam aż zmiany zaczną działać i sprawdzę.
Dzięki za pomoc

**Comment by mlonc** [comment]
Działa, dzięki za pomoc.
