### ISSUE TITLE
Automatyczne przełączanie między kontami Allegro API

### ISSUE THREAD

**Issue by palmemd** [allegro/allegro-api#5029]
Dzień dobry,

W jaki sposób zaprojektować kod, aby po aktualizacji np. cen na koncie Allegro, nastąpywało logowanie na kolejne konto allegro bez potrzeby ręcznego logowania się podając login i hasło?

**Comment by PrzemyslawLukanowski** [comment]
Tak, chodzi właśnie o ten pierwszy krok - może nie tyle co "podczas rejestracji aplikacji" (aby nie mylić z rejestracją aplikacji poprzez https://apps.developer.allegro.pl/) przez jej twórcę , ale wiązania konta z aplikacją. Następne logowania nie są już konieczne.

**Comment by PrzemyslawLukanowski** [comment]
Jeśli nie wygenerowałeś nowego access tokena za pomocą wcześniej otrzymanego refresh tokena w ciągu tych 12h godzin, to tak, to prawidłowe zachowanie.
