### ISSUE TITLE
How to find products with reducting  applies to  my offers?

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#5031]
Dear allegro team, I have been notified that some products will be automatically reduced for qualified sellers starting from 10.18. The article says that these advertisements can be obtained through api or offer page. Which interface is currently available through api? 
Please give me the corresponding link and Corresponding field
![image](https://user-images.githubusercontent.com/72594584/136950810-d1f4a46f-f26c-47d7-97f2-982e6d06f890.png)
News link：
https://allegro.pl/help/for-sellers/listing-an-offer-via-the-listing-form/allegro-prices-the-support-program-for-the-sellers-Ag9A132M0Sm

**Comment by PrzemyslawLukanowski** [comment]
You can check which offers have the badge assigned (and this also applies to Allegro Price) via [GET /sale/badges](https://developer.allegro.pl/documentation/#operation/getBadges).

**Comment by bingnew** [comment]
Sorry, there is another question. If our product is in  Allegro Cena,how do we know the amount of the price cut  amount through the interface?
At present,The current price obtained from the interface is the current price, and there is no price reduction amount, and we cannot calculate the profit。
![image](https://user-images.githubusercontent.com/72594584/137063530-bd826aab-43fc-4f7f-8fc0-7040880be12a.png)

**Comment by PrzemyslawLukanowski** [comment]
The value in the `prices.subsidy.targetPrice.amount` field is the price that is visible for buyers. The base price we return in response to [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) and [GET /sale/offers/{offerID}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - in the  `sellingMode.price.amount` field.

**Comment by bingnew** [comment]
As you said, I found the sellingMode.price.amount field corresponding to this interface. The interface field is interpreted as the current selling price, not the base price.
![lQLPDhrFl9II5fDNA-PNBQiw9vsxx6UJymDCcmjLLmXRKw_1288_995](https://user-images.githubusercontent.com/72594584/137262499-0ab9ed58-3c18-4c5c-b0f9-a02e69d0b491.png)

The Allegro Prices plan will start on 10.18. We currently have no test data. Can you set up an Allegro Prices for our account for testing?

**Comment by PrzemyslawLukanowski** [comment]
Yes, but from [Sandbox environment ](https://developer.allegro.pl/en/about/#test-environment). We cannot set up a test Allegro Price on production.
