### ISSUE TITLE
Błąd "Offer not found. It was deleted, archived or never existed."

### ISSUE THREAD

**Issue by maciek257** [allegro/allegro-api#5033]
Występuje problem: 
 - [x ] z zasobem REST API

**Opis**

Napotkałem na problem z aktualizację ofert przez API.
Pobieram z konta oferty, które mają status "ACTIVE" lub "ENDED" i zaraz potem w pętli sprawdzam czy w systemie zewnętrznym istnieją różnice w parametrach oferty. Jeśli tak to dokonuje aktualizacji przez API.

Niestety regularnie pojawia się problem z zerwaną synchronizacją, ponieważ występuje błąd 404 (Offer not found. It was deleted, archived or never existed.).

Gdy wchodzę do panelu Allegro to znajduję ofertę, która według API nie istnieje (mimo tego, że została chwilę wcześniej przez API pobrana). W panelu ma ona status "zakończona", ale w momencie kliknięcia w link następuje przekierowanie do archiwum.

Czy to, że taka oferta zostaje na koncie ze statusem "ENDED" i jest dostępna przez API jest zamierzone?
Jeśli tak to czy istnieje możliwość, aby pominąć taką ofertę w momencie pobierania?

Skrypt aktualizujący jest na tyle rozbudowany, że ciężko mi utrzymać jego ciągłość po otrzymaniu błędu 404.

Będę wdzięczny za podpowiedzi.

Pozdrawiam.

**Comment by hahyes** [comment]
>W panelu ma ona status "zakończona", ale w momencie kliknięcia w link następuje przekierowanie do archiwum.

Tu leży problem. Oferta jest w archiwum, a jak stanowi błąd przytoczony przez ciebie: 
>Offer not found. It was deleted, **archived** or never existed.

Czyli wszystko się zgadza, po prostu oferta nie jest osiągalna z poziomu API po archiwizacji.

**Comment by maciek257** [comment]
Dodaję komentarz, aby wątek nie został automatycznie zamknięty.

**Comment by MaciejFrackowiak** [comment]
@maciek257 Problem nie powinien już występować.
