### ISSUE TITLE
Ułatwienie rejestracji oprogramowania dla deweloperów

### ISSUE THREAD

**Issue by troncomputers** [allegro/allegro-api#5035]
Witam.
Czy jest szansa, aby ułatwić pracę deweloperom i nie wymagać smsów, dwóch etapów logowania? Właśnie jestem w trakcie wdrożenia 5 kolejnych kont klientowi i powiązanie aplikacji z kontem Allegro wymaga zalogowanie się i potwierdzenia smsem. Nie mam tego telefonu przy sobie, muszę czekać, aż klient łaskawie mi go poda, abym mógł cokolwiek zdziałać. Później kolejny etap to wygenerowanie tokenów... Ja rozumiem, że to jest kwestia bezpieczeństwa ale czy jest szansa, aby to uprościć?

**Comment by PrzemyslawLukanowski** [comment]
Wymagamy dwustopniowego logowania tylko dla kont, które rejestrują aplikację, nie dla użytkowników, którzy wiążą swoje konto z aplikacją. Tę zmianę wprowadziliśmy [15 marca 2021](https://developer.allegro.pl/news/#terms-and-conditions-changed) i nie planujemy z niej rezygnować. Proces generowania tokenów jest natomiast zgodny ze standardem [OAuth](https://oauth.net/2/).
