### ISSUE TITLE
wielkości pól obiektu pickup.address

### ISSUE THREAD

**Issue by Zbigniew-L** [allegro/allegro-api#5037]
podczas tworzenia przesyłki otrzymałem błąd:  **pickup.address.street Ulica punktu nadania przesyłki jest za długa** - jednak nie mogę znaleźć nigdzie w dokumentacji jaka jest maksymalna długość dla tego pola, czy znajdę gdzieś zestawienie, które jasno mówi jakie są maksymalne rozmiary pól, na początek obiektu pickup.address ?
w dokumentacji mamy tylko typy danych ale brak info o rozmiarach...
https://developer.allegro.pl/documentation/#operation/createNewParcel

street
postCode
city
countryCode
county

**Comment by Lukasz-Zurek** [comment]
@Zbigniew-L Limity znaków dla pola: **pickup.address.street** przedstawiają się następująco:

```
DPD -> 2 - 40, litery, cyfry, znaki specjalne
UPS -> 2 - 30, litery, cyfry, znaki specjalne
GLS -> 2 - 40, litery, cyfry, znaki specjalne
Fedex -> 2 - 30, litery, cyfry, znaki specjalne
InPost -> 2 - 100, litery, cyfry, znaki specjalne
InPost Kurier -> 2 - 100, litery, cyfry, znaki specjalne
ORLEN Paczka -> 2 - 30, litery, cyfry, znaki specjalne
Poczta Polska -> 2 - 57, litery, cyfry, znaki specjalne
DHL Parcel -> 2 - 45, litery, cyfry, znaki specjalne
AmbroExpress -> 2 - 55, litery, cyfry, znaki specjalne
```
Nie opisujemy tego w dokumentacji, ponieważ jak wspomniałem - nie są to nasze wewnętrzne limity.

**Comment by Lukasz-Zurek** [comment]
@hahyes Ok, dziękuję.
