### ISSUE TITLE
Raport o nieistniejącym szkicu oferty

### ISSUE THREAD

**Issue by Kasia13130** [allegro/allegro-api#5038]
Witam, 
Próbowałam opublikować kilka ofert produktów na Allegro Sandbox, z tym że podczas sprawdzania raportu za pomocą:
https://api.{environment}/sale/offer-publication-commands/{commandId}/tasks otrzymuję raport o błędzie w nieistniejącej już ofercie  zamiast o ofertach które dziś chciałam opublikować. Jak może być przyczyna ? 
TraceId: ce20af083159ea97

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że z tego samego commandID korzystasz wielokrotnie, dlatego otrzymujesz wynik pierwszej operacji, podczas której go użyłaś. Pamiętaj, że UUID jest jednorazowego użytku, dlatego dla każdej nowej operacji musisz wygenerować nowy numer commandID.
