### ISSUE TITLE
[Sandbox] produktyzacja - przykłady niestandardowych produktów sale/product

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#5039]
Witam,

Chciałbym prosić zespół Allegro o przygotowanie niestandardowych przypadków produktów na serwerze testowym. Umożliwi mi to łatwiejszą obsługę wystawienia oferty powiązanej przez POST sale/product-offers . Przypadki można dodać do Państwa poradnika.

Chodzi mi o:
- 2 produkty należące pod ten sam EAN,
-  produkt nieposiadający EAN,
- produkt, którego podpięcie wymaga dodania cech dodatkowych (kod błędu ConstraintViolationException.MissingRequiredParameters ),
- produkt, którego podpięcie wymaga zmiany opisu (kod błędu ConstraintViolationException.ValidOfferName ),
- produkt, którego podpięcie powoduje błąd parametrów własnych, których nie przekazuję  (kod błędu OfferCustomParametersException).

Gdyby była potrzeba mogę przesłać przykłady z serwera produkcyjnego.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , w nawiązaniu do

> Produkty był słabe jakościowo (nie miały uzupełnionej większej części parametrów). Aktualnie w odpowiedzi na request GET sale/products?ean=0711719282365 powinieneś już otrzymać dwa różne produkty.

Czy można prosić aby zapytanie po EAN ponownie zwracało mi 2 produkty? Obecnie nie zwraca żadnego.

Oba produkty (0b2f498d-3646-4819-8102-a812240472ce , 17ef2e7a-a759-42e9-84c2-93bf1a578ba6) są na sadbox ale nie widać w ich w zapytaniu o EANie.

`GET sale/products?ean=0711719282365 || trace-id:1c1abc187ab4a8b1`

**Comment by PrzemyslawLukanowski** [comment]
Produkt 1`7ef2e7a-a759-42e9-84c2-93bf1a578ba6` jest już prawidłowo zwracany przez wyszukiwarkę. Powodem wystąpienia błędu było to, że produkt nie był umiejscowiony w kategorii najniższego rzędu - poprawiłem to. Produkt `0b2f498d-3646-4819-8102-a812240472ce` został usunięty z naszego indeksu, ponieważ był duplikatem. W takiej sytuacji nie zwrócimy go w wynikach wyszukiwania.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski, na sandbox potrzebuję odtworzyć taką samą sytuację jak na produkcji. 

Przykład na produkcji
`GET /sale/products?ean={ean} || trace-id:302face9612f8ffd`

Proszę zauważyć, że dla jednego nr EAN mam zwrócone 5 różnych produktów. Na sandbox wystarczą mi 2, obojętnie który EAN.

**Comment by PrzemyslawLukanowski** [comment]
@Radeq Skorzystaj proszę w takim razie z parametru EAN o wartości 4050300006734. W odpowiedzi otrzymasz również 5 produktów.

**Comment by Radeq** [comment]
@PrzemyslawLukanowski , dziękuję - dokładnie tego potrzebowałem.
