### ISSUE TITLE
HttpMessageNotReadableException When adding a product

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5040]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Account name : 9Merchants
Client ID : 0b362d641e7c4ad786c3c1ed7eef0b04

Url: https://api.allegro.pl/sale/product-proposals
Method: POST
Request:
{"name":"Love Heart Toggle Bracelet-silver","category":{"id":"257987"},"images":[{"url":"https:\/\/wiseloads.dmsmatrix.net\/direct\/images\/604b9d9a099d76d9f72b3d38.jpg"},{"url":"https:\/\/wiseloads.dmsmatrix.net\/direct\/images\/604b9d9a099d76d9f72b3d3a.jpg"}],"parameters":[{"id":"11323","name":"State","valuesLabels":"New","valuesIds":"11323_1","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"226434","name":"Brand","valuesLabels":"Other Brand","valuesIds":"226434_315782","values":"Unbranded","unit":null,"options":{"identifiesProduct":true}},{"id":"2205","name":"Type","valuesLabels":"Jewelry Product","valuesIds":"2205_2","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"15835","name":"Material","valuesLabels":"Steel","valuesIds":"15835_256","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"17088","name":"Stone","valuesLabels":"Crystal","valuesIds":"17088_512","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"205826","name":"Main Color","valuesLabels":"silver","valuesIds":"205826_225086","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"2206","name":"Total Length","valuesLabels":"1 cm","valuesIds":"1","values":"1","unit":"cm","options":{"identifiesProduct":true}},{"id":"129129","name":"Theme","valuesLabels":"Heart","valuesIds":"129129_2","values":null,"unit":null,"options":{"identifiesProduct":true}},{"id":"206618","name":"Features","valuesLabels":"adjustable length","valuesIds":"206618_4","values":null,"unit":null,"options":{"identifiesProduct":true}}],"description":{"sections":[{"items":[{"type":"string","content":"This Silver Love Heart Toggle Bracelet Comes With A Central Stunning Circular Charm, Which Has Delicate Silver-coloured Heart-shaped Charms And Alternating Circular Swarovski Encrusted Charms, Attached To A Chain Bracelet With Toggle Clasp. Available Colour: Silver, Rose Gold Dimension: 20 Cm, Charm 1x1 Cm, Material: Stainless Steel, Swarovski Crystal"}]}]}}

Response:

{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Invalid request. Please contact the application author."}]}

The problem occurs with the Production version. When I try to add a product.

**Comment by PrzemyslawLukanowski** [comment]
Sorry, not for each parameter, but only for the problematic one - 206618.

**Comment by PrzemyslawLukanowski** [comment]
Can you send me your trace-id for the invalid request? Except for the missing open <p> tag in the description, the structure looks well and it should work.

**Comment by PrzemyslawLukanowski** [comment]
You should find the trace-id in the headers of your API response. This value is connected with your specific request, so owing to it I will be able to check our logs.
Can you try to use the data from my second post (but including your images), so without unnecessary data such as "valuesLabels" field, etc.? Are you sure you are using POST /sale/product-proposals endpoint? I'm asking because I've used my previous JSON structure as well as your last structure and I've got a valid response - the product was created.

**Comment by adityakokate** [comment]
Hello,

We have now rectified the POST request in the body but have received some other error

trace-id: 369968e1b5c9e8c6

Request:

{"name":"Love Heart Toggle Bracelet-silver","category":{"id":"257987"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11614a\/5d23da92480fb664ab91b93190d1"}],"parameters":[{"id":"11323","name":"State","valuesLabels":["New"],"valuesIds":["11323_1"]},{"id":"226434","name":"Brand","valuesLabels":["Other Brand"],"valuesIds":["226434_315782"],"values":["Unbranded"]},{"id":"2205","name":"Type","valuesLabels":["Jewelry Product"],"valuesIds":["2205_2"]},{"id":"15835","name":"Material","valuesLabels":["Steel"],"valuesIds":["15835_256"]},{"id":"17088","name":"Stone","valuesLabels":["Crystal"],"valuesIds":["17088_512"]},{"id":"205826","name":"Main Color","valuesLabels":["silver"],"valuesIds":["205826_225086"]},{"id":"2206","name":"Total Length","valuesLabels":["1 cm"],"values":["1"],"unit":"cm"},{"id":"129129","name":"Theme","valuesLabels":["Heart"],"valuesIds":["129129_2"]},{"id":"206618","name":"Features","valuesLabels":["adjustable length"],"valuesIds":["206618_4"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>This Silver Love Heart Toggle Bracelet Comes With A Central Stunning Circular Charm, Which Has Delicate Silver-coloured Heart-shaped Charms And Alternating Circular Swarovski Encrusted Charms, Attached To A Chain Bracelet With Toggle Clasp. Available Colour: Silver, Rose Gold Dimension: 20 Cm, Charm 1x1 Cm, Material: Stainless Steel, Swarovski Crystal<\/p>"}]}]}}

Response:

{"errors":[{"code":"VALIDATION_ERROR","message":"Nieprawidłowy podzbiór HTML","details":null,"path":"standardized.sections[0].items[0].content","userMessage":"Nieprawidłowy podzbiór HTML"}]}

Could you please check this and let me know the exact issue?

**Comment by adityakokate** [comment]
Hello

Thank you for your support and feedbacks.

We have been able to create the product successfully.

**Comment by PrzemyslawLukanowski** [comment]
You can check your offers [here](https://allegro.pl/moje-allegro/sprzedaz/moje-oferty?offerType=BUY_NOW&page=1&pageSize=20), but it applies only to the offers, not the created products. Your products are visible via [the listing form](https://allegro.pl/offer/) when you enter the product name or ID.

**Comment by adityakokate** [comment]
Hello

As suggested by Allegro team, we were trying to create a product by feeding EAN number in the parameters field but are receiving the error

trace-id: 71de4248856a9d69

Request:
{"name":"Love Heart Toggle Bracelet-silver","category":{"id":"257987"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/115a7b\/66bf1b224593aefb5591de6b9c9c"}],"parameters":[{"name":"EAN","values":["5060805599418"]},{"id":"11323","name":"State","valuesLabels":["New"],"valuesIds":["11323_1"]},{"id":"226434","name":"Brand","valuesLabels":["Other Brand"],"valuesIds":["226434_315782"],"values":["Unbranded"]},{"id":"2205","name":"Type","valuesLabels":["Jewelry Product"],"valuesIds":["2205_2"]},{"id":"15835","name":"Material","valuesLabels":["Steel"],"valuesIds":["15835_256"]},{"id":"17088","name":"Stone","valuesLabels":["Crystal"],"valuesIds":["17088_512"]},{"id":"205826","name":"Main Color","valuesLabels":["silver"],"valuesIds":["205826_225086"]},{"id":"2206","name":"Total Length","valuesLabels":["1 cm"],"values":["1"],"unit":"cm"},{"id":"129129","name":"Theme","valuesLabels":["Heart"],"valuesIds":["129129_2"]},{"id":"206618","name":"Features","valuesLabels":["adjustable length"],"valuesIds":["206618_4"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"

This Silver Love Heart Toggle Bracelet Comes With A Central Stunning Circular Charm, Which Has Delicate Silver-coloured Heart-shaped Charms And Alternating Circular Swarovski Encrusted Charms, Attached To A Chain Bracelet With Toggle Clasp. Available Colour: Silver, Rose Gold Dimension: 20 Cm, Charm 1x1 Cm, Material: Stainless Steel, Swarovski Crystal<\/p>"}]}]}}

Response:

{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Invalid request. Please contact the application author."}]}

Could you please look into it and revert back for the same?

**Comment by PrzemyslawLukanowski** [comment]
If it comes to /sale/product-proposals endpoint you cannot use only names of the parameters, so instead of "name" pass "id" and the proper value.

**Comment by adityakokate** [comment]
Hello,

What should be passed in the "id" for EAN?

**Comment by PrzemyslawLukanowski** [comment]
You can check the ids for a given category via [GET sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). In this case it will be 225693.

**Comment by adityakokate** [comment]
Hello

Thank you for the clarification.
