### ISSUE TITLE
ORLEN paczka - SERWIS MINI

### ISSUE THREAD

**Issue by CF-WR617AC** [allegro/allegro-api#5048]
Otrzymuję etykietę po WzA dla ORLEN paczka.
Wszystko ładnie przechodzi, jednak etykieta raz ma parametr MINIPACZKA, a raz jest bez parametru MINIPACZKA.
Nawet dla tej samej transakcji otrzymuję różne etykiety w zależności od tego, kiedy jest generowana.
Proszę o wsparcie. Zależy mi, aby etykieta była właśnie jako MINIPACZKA, aby korzystać z tańszej opcji tej samej przesyłki.
Orlen twierdzi, że WzA najprawdopodobniej ma problemy z ustawianiem parametru SERWIS MINI,
proszę o wsparcie.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowe informacje. Temat przekazałem dalej do weryfikacji. Wrócę z odpowiedzią w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Dla umów własnych nie wysyłaliśmy z naszej strony informacji do API przewoźnika, że paczka jest mini. W ubiegły piątek o godz. 12:00 wprowadziliśmy poprawkę. Prawdopodobnie jedna paczka jest sprzed wprowadzenia poprawki, druga już po.

Co do zasady:
Paczka MINI - wymiary do 20 x 20 x 30 cm, waga do 5kg
Paczka STANDARD - wymiary do 20 x 30 x 50cm, waga od 5 do 20kg

**Comment by CF-WR617AC** [comment]
Proszę sprawdzić etykiety:
2100426968262 - brak znacznika MINI (punkt ORLEN w sieci LEWIATAN)
2100426699326 - jest znacznik MINI  (SALONIK RUCH)

**Comment by CF-WR617AC** [comment]
![image](https://user-images.githubusercontent.com/84842730/137698141-9e39f561-1e9d-433f-b4ad-79a68dc23995.png)

**Comment by CF-WR617AC** [comment]
Proszę o naprawę Serwisu WzA. W metodzie Allegro ORLEN paczka po zwiększeniu wagi do 9 kg naklejka traci SERWIS MINI, co jest  niezgodne z Pańśtwa deklaracjami na stronie:
https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-orlen-paczka-AVm6XOPV4tZ


![image](https://user-images.githubusercontent.com/84842730/137720408-d676df45-d392-40ef-84eb-204df4d79213.png)

**Comment by CF-WR617AC** [comment]
Proszę o naprawę serwisu WzA.
Po ustawieniu wymiarów przesyłki: 41x38x60cm

traci ona znacznik SERWIS MINI, , co jest niezgodne z Pańśtwa deklaracjami na stronie:
https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-orlen-paczka-AVm6XOPV4tZ

**Comment by CF-WR617AC** [comment]
Co słychać w temacie ?

**Comment by MartaNowaczyk** [comment]
Sprawdzę czy sprawa się wyjaśniła i dam znać.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Wdrożyliśmy poprawkę, dzięki której dla wszystkich rodzajów punktów ORLEN Paczka, rozróżniamy przesyłki Mini (5 kg,  20x20x30 cm) i Standard (20 kg, 20x30x50 cm). Problem nie powinien już występować.

Raz jeszcze przepraszamy za zaistniałe utrudnienia.

**Comment by CF-WR617AC** [comment]
Dziękujemy za informację.

**Comment by CF-WR617AC** [comment]
A co z paczkami do 10kg, też miały być w serwisie MINI:

![image](https://user-images.githubusercontent.com/84842730/144847786-feffaed1-760f-475d-81fa-c95207f15fb1.png)

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Artykuł w Pomocy dotyczy metody Allegro ORLEN Paczka. Natomiast to, o czym wspomniałem powyżej dotyczy - ORLEN Paczki. Sprawa Allegro ORLEN Paczki jest nadal wyjaśniana, tzn. prowadzimy obecnie rozmowy z firmą Orlen, aby to zoptymalizować. Tutaj nadal mogą pojawiać się nieścisłości, za co serdecznie przepraszamy. Sprawa nie jest do końca uzależniona od naszego Serwisu. Niemniej jednak wrócę do Ciebie z pewną informacją, jak już zasady te zostaną ustalone.

**Comment by CF-WR617AC** [comment]
Proszę o info, czy przez WzA możliwe jest wygenerowanie etykiety do transackji oznaczonej jako SMART tak, aby była ona w serwisie MINI, czyli po obiecanych kosztach? Jak dotąd nie udało mi się wygnerować etykiety w żadnych warunkach, zawsze przychodzi bez SERWISU MINI. Czy to błąd, czy tak ma być ?

**Comment by CF-WR617AC** [comment]
generalnie moim zdaniem, to wygląda znów na kolejny błąd serwisu. Gdyż dostałem od Państwa 5.71 na opłacenie przesyłki + 1 zł z PSW. Czyli 6.71zł, a płacę w ORLENie 8.60zł. Proszę o naprawę systemu WzA tak, aby przesyłki SMART również dało się zamawiać w serwisie MINI. Dziękuję

**Comment by CF-WR617AC** [comment]
Rozumiem. Czyli waga do 10kg na ten moment w SERWIS MINI nie działa?

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Pozwól, że upewnię się co do informacji znajdującej się w Pomocy Allegro, we wskazanym przez Ciebie wcześniej linku. Najprawdopodobniej informacja ta nie jest już aktualna, co oznaczałoby, że waga do 10kg w SERWIS MINI - nie działa. Wrócę do Ciebie z pewną informacją, aby nie było tutaj żadnych wątpliwości.

**Comment by CF-WR617AC** [comment]
Allegro cały c;zas Sprzedaje nam usługę SERWIS MINI do 10kg:
https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-orlen-paczka-AVm6XOPV4tZ

**Comment by CF-WR617AC** [comment]
A Państwo generują etykiety SERWIS MINI do 5kg, co oznacza, że obciążają nas Państwo opłatami niezgodnymi z ofertą na powyższej stronie.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Tym bardziej zależy mi na wyjaśnieniu tych nieścisłości. Proszę jednak o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC 

Wskazany przez Ciebie artykuł nie dotyczy opłat i wymiarów Orlen Paczki w ramach podziału na Mini i Standard. [Artykuł](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/allegro-orlen-paczka-AVm6XOPV4tZ) dotyczy wyłącznie opłat za nadanie przesyłki jednopaczkowej. Dla wszystkich rodzajów punktów ORLEN Paczka, rozróżniamy przesyłki Mini (5 kg, 20x20x30 cm) i Standard (20 kg, 20x30x50 cm) i o tym nie ma żadnej wzmianki w artykułach w Pomocy Allegro.

Chciałbym jednocześnie przeprosić za długi czas oczekiwania na odpowiedź. Nie jest to temat związany stricte z API, dlatego konsultacja wymagała czasu. Dlatego w razie pojawienia się jakichkolwiek pytań/wątpliwości (również w kwestii opłat) - zachęcam do korzystania z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by CF-WR617AC** [comment]
Nie kłamie Pan? Wskazany artykuł omawia wysyłkę Allegro ORLEN Paczka
do 10 kg.
Proszę mi zrobić tak, żeby do 10kg było jak w artykule tzn za 5.44 netto.
I przestać nam tu mydlić oczy, bo 10kg za 5.44 nie działa. Nie interesuje mnie podziała na MINI/STANDARD, tylko cena jak w Waszej ofercie 5.44 netto.
Dziękuję !

**Comment by Lukasz-Zurek** [comment]
Artykuł dotyczy Allegro ORLEN Paczki i opłat za nadanie przesyłki jednopaczkowej. Nie dotyczy natomiast opłat i wymiarów w ramach podziału na Mini i Standard, ponieważ takiego podziału, dla tej metody dostawy - nie rozróżniamy.

Przypominam, że na tym forum świadczymy wsparcie w zakresie Allegro API. Dlatego jeżeli masz jeszcze dodatkowe pytania np. dotyczące kosztów pobieranych w ramach usług w Allegro.pl - zachęcam do wyjaśnienia tych kwestii kontaktując się z Serwisem przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by CF-WR617AC** [comment]
Dzień dobry. Mam problem z wygenerowaniem naklejki po API, naklejka przechodzi jednak cały czas przez WzA po www z Serwisu.
Prośba o wsparcie.
ID przesyłki:
fd4c902a-a56d-48db-a154-55445e6b37c5

```
Serwis Allegro zwrócił błąd:
Punkt odbioru nie został odnaleziony (receiver.point)
Point with ID HU716 and delivery method 0855919d-7e04-4f8c-ae0f-bb44659fc68a not found
```



Dziękuję.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Dziękuję za zgłoszenie. Przekazałem dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Podany punkt jest już dostępny. Błąd wskazuje na to, że punkt był tymczasowo niedostępny podczas próby nadania przesyłki.

**Comment by CF-WR617AC** [comment]
Zdecydowanie należy wskazać, że problem z ORLEN Węgry mamy przed dłuższy czas (wiele tygodni) i te przesyłki nie wychodzą po API. Czy sprawdzli Państwo po API? Proszę sprawdzić po API, bo po WWW z Serwisu Allegro jak podałem to działa, ale ja pytałem o API.
Nie działa i nie ma mowy o tymczasowym niedziałaniu - niedziałanie jest permanentne.
Kolejny ID:
852eb83f-0593-47a2-8bcd-7960968dcd44
Jak zrobić do niego etykietę (chodzi o API) ?

Proszę o wsparcie. Dziękuję.

**Comment by CF-WR617AC** [comment]
Także przeprzedni że niby działa?
Na pewno nie po API:
fd4c902a-a56d-48db-a154-55445e6b37c5
Jak to zrobić?
W zwrotce otrzymuję:
"Punkt odbioru nie został odnaleziony (receiver.point)"

**Comment by Lukasz-Zurek** [comment]
@CF-WR617AC Dzięki za konkretne przykłady. Konsultuję już ten temat z odpowiednim zespołem.

**Comment by CF-WR617AC** [comment]
Bardzo proszę. Problem nie jest przejściowy, problem jest permanenty.

**Comment by CF-WR617AC** [comment]
Cały czas nie działa:
c27403ac-0c72-450b-8d57-595ad1800a2c

**Comment by Lukasz-Zurek** [comment]
Spróbuj przekazywać identyfikatory punktów wyłącznie za pomocą małych liter. Z tego co się orientuję - Packeta zwraca punkty na Węgrzech jako `hu437` i `hu716` - i punkty te są obecnie dostępne. 

Od zespołu odpowiedzialnego za wysyłkę przesyłek w ramach WZA - otrzymałem informację, że takie sytuacje są zgodne z założeniem. Może się zdarzyć, że wybrany przez Klienta punkt, nie będzie dostępny dla partnera podczas próby nadania przesyłki. Nie odpowiadamy tutaj za dostępność punktów takich firm jak Packeta, DHL, DPD, itd. W sytuacji jak powyżej należy przekierować paczkę do punktu, który jest najbliżej pierwotnie wskazanego punktu.

**Comment by CF-WR617AC** [comment]
Dziękuję za informację. Sprawdzę potrzeba więcej czasu. Możliwe, że z małymi / wielkimi literami jest coś na rzeczy.

**Comment by CF-WR617AC** [comment]
Dziękuję za wsparcie, potwierdzam rozwiązanie problemu.

**Comment by Lukasz-Zurek** [comment]
Cieszę się, że udało się to rozwiązać. Dzięki za info!
