### ISSUE TITLE
Różne responsy w zależności od strzałów z różnych API

### ISSUE THREAD

**Issue by JaroszPatryk** [allegro/allegro-api#5049]
Mam pewien problem. Otóż w przypadku, gdy robie strzał do api z rested w firefoxie dostaje status code 200, natomiast w  przypadku strzału z postmana dostaje status 401. Proszę o informację czym to może być spowodowane.
Rested:
![obraz](https://user-images.githubusercontent.com/65483534/137583040-a3291ae9-1bcb-4c66-aff4-75219a8a4938.png)
Postman:
![obraz](https://user-images.githubusercontent.com/65483534/137583071-b708f0e6-efac-4a45-8668-f6953cde0602.png)

**Comment by Lukasz-Zurek** [comment]
@JaroszPatryk Musisz [przedłużyć ważność access tokena za pomocą refresh_token](https://developer.allegro.pl/auth/#przedłużenie-ważności-tokena). Komunikat jednoznacznie wskazuje na to, że termin ważności obecnego access tokena - już upłynął. 

Jeśli w "Headers" wprowadzasz aktualny access token, upewnij się, czy w zakładce "Authorization" nie widnieje nieaktualny.

**Comment by Lukasz-Zurek** [comment]
@JaroszPatryk Parametr **grant_type** jest ok. Najprawdopodobniej wprowadzasz nieaktualny **refresh_token**. Musi to być **refresh_token**, jaki otrzymałeś wraz z ostatnim wygenerowanym access_tokenem.

Więcej informacji na temat przedłużania ważności tokena, znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#przedłużenie-ważności-tokena).

**Comment by JaroszPatryk** [comment]
Zgadza się zrobiłem tak jak jest to opisane w poradniku, natomiast w zakładce headers dodałem Authorization: Basic (i tutaj mam zakodowany client_id:client_secret). I nadal dostaję powyższy błąd.
