### ISSUE TITLE
Dane do pobrania przez REST Api

### ISSUE THREAD

**Issue by lokneey** [allegro/allegro-api#505]
Witam.
Czy w tworzonych zasobach pozwalających pobrać dane o aukcjach użytkownika, będą możliwe do pobrania dane takie jak: 
- ilość wejść,
- ilość osób obserwujących ofertę,
- liczba sprzedanych sztuk towaru,
- liczba aktualnie wystawianego towaru,
- nazwa oferty,
- numer oferty,
- czas rozpoczęcia oferty,
- planowany czas zakończenia oferty,
za pomocą jednego zapytania?

**Comment by PawelTaberski** [comment]
Nazw oferty, numer oferty i inne dane m.in. o wybranym czasie trwania oferty możesz sprawdzić przy pomocy metody [GET na zasobie /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET)
Przy pomocy tej metody sprawdzisz również aktualnie dostępną ilość sztuk.
Zachęcam do zapoznania się z naszym poradnikiem odnośnie wystawienia oferty przez REST API, jest on dostępny [tutaj](https://developer.allegro.pl/sale/).
Natomiast odnośnie obsługi zamówień zajrzyj do naszego dedykowanego poradnika [tutaj](https://developer.allegro.pl/orders/).
Odnośnie ilości wejść i ilości obserwujących daną ofertę w REST API nie ma obecnie metody do sprawdzenia takich danych. Jeśli będziemy wprowadzali taką metodę poinformujemy o tym.

**Comment by lokneey** [comment]
Wiem o zasobach, które wymieniłeś i ich używam, ale jak było w moim poście, pytanie dotyczyło czy będzie możliwość pobrania wszystkich tych danych jednym zapytaniem, bądź funkcją. Chodziło mi coś analogicznego do doMyAccount2 w WebApi. 
Rozumiem, że nie planujecie czegoś takiego?

**Comment by PawelTaberski** [comment]
Pytałeś, czy w tworzonych zasobach będzie możliwość pobrania wymienionych przez Ciebie rodzajów danych. I tak, jak odpisałem dane można pobrać za pomocą wybranych metod. Chwilowo nie przewidujemy jednej metody, która zwracałaby taki zestaw danych.
