### ISSUE TITLE
Kalkulator Opłat - rozbieżności

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#5050]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Proszę o pomoc, jak przekazać poprawnie strukturę oferty, aby uzyskać dane kalkulacji jak na web'ie? Chodzi o opłatę za wyróżnienie.
Przykład, `{"offer":{"id":"11250917293","name":"Sukienka damska kwiaty falbany wielokolor one size","category":{"id":"124264"},"product":{"id":"00eb2f9a-32df-444e-a980-021dcb85fde5"},"parameters":[{"valuesIds":["11323_1"],"values":[],"rangeValue":null,"id":"11323","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["15851_1"],"values":[],"rangeValue":null,"id":"15851","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["3786_861616"],"values":[],"rangeValue":null,"id":"3786","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["3806_16"],"values":[],"rangeValue":null,"id":"54","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":[],"values":["50"],"rangeValue":null,"id":"201041","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["451_2","451_4096","451_1024"],"values":[],"rangeValue":null,"id":"451","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["3766_3"],"values":[],"rangeValue":null,"id":"3766","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["127662_2"],"values":[],"rangeValue":null,"id":"127662","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["127488_7"],"values":[],"rangeValue":null,"id":"127488","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["127468_381949"],"values":[],"rangeValue":null,"id":"127468","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["59_7"],"values":[],"rangeValue":null,"id":"59","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["4126_1"],"values":[],"rangeValue":null,"id":"4126","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["18160_212397"],"values":[],"rangeValue":null,"id":"18160","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["201025_2521"],"values":[],"rangeValue":null,"id":"201025","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["201017_2377"],"values":[],"rangeValue":null,"id":"201017","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":[],"values":["95% Poliester","5% Elastan"],"rangeValue":null,"id":"215930","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":["202477_64"],"values":[],"rangeValue":null,"id":"202477","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":[],"values":["100"],"rangeValue":null,"id":"201033","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null},{"valuesIds":[],"values":["2010000997925"],"rangeValue":null,"id":"225693","name":null,"type":0,"required":false,"requiredForProduct":false,"unit":null,"options":null,"restrictions":null}],"customParameters":null,"ean":null,"description":{"sections":[{"items":[{"reference":null,"created_by_id":null,"external_customer_id":null,"comments":null,"mpk":null,"type":"IMAGE","url":"https://a.allegroimg.com/original/114f08/36cb99d747938ee6c91758e16b7b"},{"reference":null,"created_by_id":null,"external_customer_id":null,"comments":null,"mpk":null,"type":"TEXT","content":"<p>Sukienka w kwiaty z falbanami:</p> <p>- wiązany dekolt z dekoracyjną stójką</p> <p>- swobodny krój</p> <p>- długie rękawy wykończone gumką</p> <p>- uszyta ze zwiewnej tkaniny ze wzorem w kwiaty</p> <p>- dekoracyjne falbany na dole</p> <p>Modelka ma 175 cm wzrostu i ma na sobie rozmiar UNIWERSALNY</p>   <p>Wymiary:</p> <p>- szerokość pod pachami 50 cm</p> <p>- długość całkowita 100 cm</p>"}]},{"items":[{"reference":null,"created_by_id":null,"external_customer_id":null,"comments":null,"mpk":null,"type":"IMAGE","url":"https://a.allegroimg.com/original/11d7fc/c36b7ef946e8855673e61178ed7f"},{"reference":null,"created_by_id":null,"external_customer_id":null,"comments":null,"mpk":null,"type":"TEXT","content":"<p><b>Skład: </b>95% Poliester 5% Elastan</p><p><b>Koniecznie odwiedź nasz pozostałe aukcje! </b></p>"}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/114f08/36cb99d747938ee6c91758e16b7b"},{"url":"https://a.allegroimg.com/original/11d7fc/c36b7ef946e8855673e61178ed7f"},{"url":"https://a.allegroimg.com/original/117cf5/2b0ee9224f39a09bae358debf547"},{"url":"https://a.allegroimg.com/original/115bb0/e189e19b4fa68cf7319c4cd1ca69"},{"url":"https://a.allegroimg.com/original/1159ee/c564e0dc438f997f1e2def85996c"},{"url":"https://a.allegroimg.com/original/1107ab/037c5519452cb6918955e13b5dbf"},{"url":"https://a.allegroimg.com/original/111b1e/4600001042f481470678f34a529b"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"99.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":{"amount":"81.29","currency":"PLN"}},"tax":{"percentage":"23.00"},"stock":{"available":8,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"243664a6-ea12-4a24-8f08-65456522a1b0"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"863d48d4-bb5b-4876-81bb-06151edb1a5d"},"returnPolicy":{"id":"6208ff2f-ac81-418d-b22f-eadd6c783e8d"},"warranty":null},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":true,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"DOLNOSLASKIE","city":"Bolesławiec","postCode":"59-700"},"external":{"id":"304ZKW09BOD-1"},"attachments":[],"contact":null,"validation":{"errors":[],"warnings":[],"validatedAt":"2021-10-08T13:08:04.454+00:00"},"createdAt":"2021-10-05T09:12:23+00:00","updatedAt":"2021-10-08T13:08:04.487+00:00"},"classifiedsPackages":null}`

W sekcji promotion, podaję parametr **emphasized** jako prawda, jednak 
zwrotka nie podaje ceny jaką uzyskuje na froncie.
`{"commissions":[{"name":"Prowizja od sprzedaży","type":"commissionFee","fee":{"amount":11.20,"currency":"PLN"}},{"name":"Prowizja od sprzedaży oferty wyróżnionej","type":"commissionFeatureFee","fee":{"amount":8.40,"currency":"PLN"}}],"quotes":[{"name":"Opłata za wystawienie","type":"listingFee","fee":{"amount":0.00,"currency":"PLN"},"cycleDuration":"PT240H","classifiedsPackage":{"id":null}},{"name":"Opłata za wyróżnienie","type":"distinctionFee","fee":{"amount":0,"currency":"PLN"},"cycleDuration":"PT240H","classifiedsPackage":{"id":null}}]}`
![image](https://user-images.githubusercontent.com/49162881/137725557-275746db-898d-4c0e-9e4f-369488f3480d.png)

**Comment by Lukasz-Zurek** [comment]
Niestety nie jest to możliwe.
