### ISSUE TITLE
Wystawiana liczba nie może być mniejsza niż 1.

### ISSUE THREAD

**Issue by esprzedaz** [allegro/allegro-api#5054]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próbuję wznowić ofertę z siedemnastoma sztukami, w odpowiedzi dostaję "Wystawiana liczba nie może być mniejsza niż 1.". Oferta 10439728848.

**Comment by Lukasz-Zurek** [comment]
@esprzedaz To jednostkowy problem. Przekazałem go do odpowiedniego działu. Proszę o cierpliwość.
