### ISSUE TITLE
Zakup produktu z opcja wysylki ORLEN Paczka - zła suma w formularzu

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5056]
Na produkcji, zakup produktu za 84,99 zl z darmowa dostawa smart i dostawą do punktu Orlen.
Od strony kupujacego zapłacone 84,99 zł, wysyłka za darmo bo smart.

I teraz formularz zakupowy który przychodzi z API:

  [delivery] => [smart] => 1
  [payment] => [paidAmount] => [amount] => 90.70
  [summary] => [totalToPay] => [amount] => 90.70

Wiem ze kliet zapłacił dokładnie 84,99 bo ze smartem.
Czy tu nie ma błędu ?
Jak mam sie zorientowac że 5,71 to kwota ktora musze calkowicie pominac ?
Musze klientowi wystawic FV i skad mam wiedziec ktora kwota jest właściwa ?

**Comment by Lukasz-Zurek** [comment]
@PawelPseudo Podaj proszę id zamówienia.

**Comment by CF-WR617AC** [comment]
Czytałeś regulamin PSW? Allegro w SMARTcie dopłaca do każdej przesyłki 4.71 pln lub 5.71 PLN. Moim zdaniem kwotę otrzymałeś OK. To jest kurier bez integracji i kasa nie przeleci ponad naszymi głowami, stąd otrzymujesz ją na konto z PAYU. U mnie tak samo działa.

**Comment by Lukasz-Zurek** [comment]
@PawelPseudo Zgodnie z tym co napisał @CF-WR617AC - koszt 5,71 zł to kwota, jaką Allegro refunduje za przesyłkę SMART. Jest ona zawsze zwracana w sekcji **delivery**, a konkretnie:

```
        "cost": {
            "amount": "5.71",
            "currency": "PLN"
        },
        "smart": true,
```
Więcej informacji znajdziesz [tutaj](https://allegro.pl/dla-sprzedajacych/allegro-smart-zasady-rozliczen-0K6XkWDOeCP).

**Comment by CF-WR617AC** [comment]
Wszystko w temacie.
