### ISSUE TITLE
INTERNAL_SERVER_ERROR 500

### ISSUE THREAD

**Issue by pythooon** [allegro/allegro-api#5057]
Występuje problem: 
 - [ x] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próbuję stworzyć draft oferty na api.allegro.pl/sale/offers
`
Wysyłam taki json:
{"afterSalesServices":{"impliedWarranty":{"id":"ac53c1a3-1179-4d51-8235-2259c2b36dc2"},"returnPolicy":{"id":"e1ac8760-132a-4e23-8bec-bdd4e661f170"}},"category":{"id":91485},"createdAt":"2021-10-20T08:06:59Z","delivery":{"handlingTime":"P10D","shippingRates":{"id":"54f473f2-d813-496f-b4c2-017388e8116c"}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11d2e9\/6939b9d54fadac202f4908ccc153"},{"type":"TEXT","content":"<p>Parker, Alan - Bugsy Malone Alan Parker<\/p>"}]},{"items":[{"type":"TEXT","content":"<p>Product DescriptionGet your students to be gansters in this great play which has been specially adapted for schools from the popular film and it even includes still photographs. So join all the characters: Bugsy, Fat Sam, Tallulah and Dandy Dan for great fun with the whole class.Students will relish this opportunity to play a cast of Prohibition-era mobsters.Fat Sam, who runs one of the most popular speakeasies in town, is in danger of being closed down by his \u2018business rival\u2019 Dandy Dan. Enter baby-faced Bugsy Malone, a killer with the ladies and a definite asset to Fat Sam. Unfortunately, Bugsy has also caught the eye of Sam\u2019s girlfriend Tallulah \u2013 though he\u2019s set his designs on the showgirl Blousey Brown.This play lends itself perfectly to school performance with its large mixed cast and consistent humour.The book contains a stimulating playscript suitable for classwork and school production, accompanied by resources including background material and lively activities.Book DescriptionHave fun with your students with this well-loved children\u2019s playAbout the AuthorSir Alan Parker is a director, writer and producer. His feature films have won nineteen BAFTA awards, ten Golden Globes and ten Oscars. His films include Bugsy Malone, Midnight Express, Mississippi Burning, The Commitments, Evita, Fame, Birdy, Angel Heart and Angela\u2019s Ashes. He was founding chairman of the UK Film Council and past chairman of the BFI. Sir Alan received the CBE in 1995 and a knighthood in 2002. He is also an Officier Des Arts et Lettres (France).<\/p>"}]},{"items":[{"type":"TEXT","content":"<h2>Parametry<\/h2><ul><li><b>ucfirst(edition)<\/b>:None ed.<\/li><li><b>ucfirst(language)<\/b>:English<\/li><li><b>ucfirst(manufacturer)<\/b>:Collins Educational<\/li><li><b>ucfirst(numberOfItems)<\/b>:1<\/li><li><b>ucfirst(packageQuantity)<\/b>:-1<\/li><li><b>ucfirst(productGroup)<\/b>:Book<\/li><li><b>ucfirst(productTypeName)<\/b>:ABIS_BOOK<\/li><li><b>ucfirst(publicationDate)<\/b>:1970-08-18<\/li><li><b>ucfirst(height)<\/b>:5.00<\/li><li><b>ucfirst(length)<\/b>:211.00<\/li><li><b>ucfirst(weight)<\/b>:45.00<\/li><li><b>ucfirst(width)<\/b>:244.60<\/li><li><b>EAN<\/b>: 9780003302301<\/li><\/ul>"}]}]},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/11d2e9\/6939b9d54fadac202f4908ccc153"},{"url":"https:\/\/a.allegroimg.com\/original\/115d5e\/2a3f1be1413fa75cf7c23a6f12aa"}],"location":{"city":"Gryfino","countryCode":"PL","postCode":"74-100","province":"ZACHODNIOPOMORSKIE"},"name":"Bugsy Malone Alan Parker","parameters":[{"id":74,"values":["2000"],"valuesIds":[null]},{"id":223545,"values":["Bugsy Malone"],"valuesIds":[null]},{"id":75,"values":[null],"valuesIds":["75_1"]},{"id":223489,"values":["Alan `Parker"],"valuesIds":[null]},{"id":223541,"values":[null],"valuesIds":["223541_313017"]}],"payments":{"invoice":"VAT"},"product":{"id":"019d384a-7764-462d-85ea-626b46221525"},"publication":{"status":"ACTIVE"},"sellingMode":{"format":"BUY_NOW","price":{"amount":60.44,"currency":"PLN"}},"tax":{"percentage":"23.00"},"stock":{"available":8,"unit":"UNIT"},"updatedAt":"2021-10-20T08:06:59Z","external":{"id":5}}

oraz nagłówki:
{
"Content-Type": "application/vnd.allegro.public.v1+json",
"Accept": "application/vnd.allegro.public.v1+json",
"Authorization: "Bearer ..."
}
`
w odpowiedzi dostaję http error 500:
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Internal server error. Please try again in a few minutes."}]}

Sytuacja trwa od wczoraj. Proszę o jakąś informację zwrtoną.

**Comment by MaciejFrackowiak** [comment]
Problem w opisanym przykładzie dotyczy głównie parametrów - podajesz przy values lub valueIds wartość [null], a w danym parametrze podałeś już ich wartość - prawidłowa struktura parametrów dla oferty z tym produktem:

```
"parameters": [
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "245669",
            "valuesIds": [],
            "values": [
                "9780003302301"
            ],
            "rangeValue": null
        },
        {
            "id": "223541",
            "valuesIds": [
                "223541_313017"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "223545",
            "valuesIds": [],
            "values": [
                "Bugsy Malone"
            ],
            "rangeValue": null
        },
        {
            "id": "75",
            "valuesIds": [
                "75_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "223489",
            "valuesIds": [],
            "values": [
                "Alan Parker"
            ],
            "rangeValue": null
        },
        {
            "id": "74",
            "valuesIds": [],
            "values": [
                "2000"
            ],
            "rangeValue": null
        }
    ],
```

Parametry wzbogacone są o obowiązkowe w tej kategorii parametry Stan oraz ISBN.
Ponadto tworząc draft oferty musisz przekazać jego publication.status jako INACTIVE.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za sugestię, przekazałem ją do odpowiedzialnego zespołu.
