### ISSUE TITLE
Integracja SMART! z zewnętrzną firmą logistyczną, ale bez API

### ISSUE THREAD

**Issue by Allegroselling** [allegro/allegro-api#5059]
Dzień dobry,

W organizacji, która reprezentuję wprowadzamy sprzedaż Allegro. Jednocześnie prowadzimy sprzedaż przez własny eCommerce. Zarówno sprzedaż sklepowa, jak i Allegrowa obsługiwana będzie przez zewnętrzny magazyn fulfillment, który niestety nie ma technicznej możliwości (z uwagi na specyficzne oprogramowanie) zintegrować się za pomocą standardowego API z Allegro.

I tutaj pojawia się pytanie - jak rozwiązać integracje wysyłek "Allegro SMART" (na preferencyjnych warunkach) z zewnętrznym magazynem? Ewentualnie czy i jeśli to jaka jest opcja na umowę kurierską z InPost Allegro i DPD Allegro na stawkach Allegro, aby zachować korzystne stawki dla SMART, ale jednocześnie aby udostępnić zewnętrznemu magazynowi ID klienta InPost Allegro/DPD Allegro i "spiąć" w standardowy sposób zewnętrzny magazyn za pomocą przypisanego ID jak w przypadku standardowej umowy kurierskiej? 

Jeśli chodzi o samo przesyłanie zamówień itp. kwestie, to mamy to rozwiązane, pozostaje tylko kwestia samych wysyłek SMART.

Proszę o podpowiedź i pomoc.

**Comment by Lukasz-Zurek** [comment]
Świadczymy tutaj wsparcie jedynie w zakresie API, dlatego nie jestem w stanie Tobie pomóc. Natomiast jeśli chodzi o Allegro API - dysponujemy wyłącznie tymi zasobami, które opisaliśmy w [naszej dokumentacji](https://developer.allegro.pl/documentation/).

Ewentualne pytania dotyczące usługi Allegro SMART proszę kierować poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=6b0fd6c3-e25e-4e61-a1da-ed23df85af7e&subjectId=84e1c27e-ba93-48c2-b237-c3ae940ae06a).
