### ISSUE TITLE
Zmiana właściciela konta i nazwy

### ISSUE THREAD

**Issue by brandsport24** [allegro/allegro-api#5061]
Dzień dobry,

czy na API REST ma wpływ zmiana właściciela konta allegro [Zbycie zorganizowanej części przedsiębiorstwa}, oraz zmiana nazwy konta ?

Pytam gdyż zmieniamy dane, a integrację mamy przez idosell. 

Denis zalewski

**Comment by MaciejFrackowiak** [comment]
W przypadku zmiany nazwy konta (loginu) może być konieczne uzyskanie ponownej autoryzacji przez aplikację.
