### ISSUE TITLE
Problem z pobieraniem oferty

### ISSUE THREAD

**Issue by walliswoblink** [allegro/allegro-api#5063]
Mam problem z pobieraniem danych oferty

https://api.allegro.pl/sale/offers/11056384540

Dostaję odpowiedź 
`{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]} `

pomimo tego że za pomocą tego samego tokena pobieram dane na temat zamówienia do tej oferty:

https://api.allegro.pl/order/checkout-forms/e06a5116-324c-11ec-8772-c31dff113090

i odpowiedź jest prawidłowa

Próbowałam resetować klucz i nic to nie dało. Problem dotyczy wszystkich ofert, na kilku kontach.

**Comment by Lukasz-Zurek** [comment]
Jeżeli w dalszym ciągu otrzymujesz błąd, prześlij proszę przykładowy request i response wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5063.

**Comment by walliswoblink** [comment]
Tak, już działa. Wielkie dzięki!
