### ISSUE TITLE
Access denied. Contact the author of the application - /sale/offers/{offerId}

### ISSUE THREAD

**Issue by miXXX-er** [allegro/allegro-api#5085]
Mam problem `/sale/offers/{offerId}`
Do tej pory wszystko działało jak należy, ale od paru dni dostaję zwrotkę:

```
Array
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => AccessDenied
                    [message] => Access is denied
                    [details] => 
                    [path] => 
                    [userMessage] => Access denied. Contact the author of the application.
                )

        )
)
```

Coś się zmieniło?
Zakres uprawnień dla aplikacji: 

`"allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read allegro:api:messaging"`

**Comment by jszczypk** [comment]
@miXXX-er Też mnie to spotkało. Wygląda na to, że nagłówek nie został wycięty, tylko wcześniej jak obecność nie była sprawdzana (przynajmniej dla zapytań GET).
