### ISSUE TITLE
Zasób unfilled-parameters nie zwraca wszystkich ofert z niewypełnionymi parametrami obowiązkowymi

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5096]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

Istnieją oferty których nie mogę modyfikować ze względu na brak wypełnionych obowiązkowych parametrów ale numery tych ofert nie pojawiają się gdy pytam o nie poprzez zasób /sale/offers/unfilled-parameters.

Przykład:

1. Pobranie ofert z niewypełnionymi parametrami:
/sale/offers/unfilled-parameters?limit=1000&offset=0&parameterType=REQUIRED
trace-id: 864f913ad3366297

2. Próba modyfikacji jednej z ofert kończy się błędem "Missing required parameters: Type." mimo, że numeru oferty nie otrzymałem w poprzednim requescie.
Trace-id do próby nieudanej modyfikacji: e059e9ba193de1d9

**Comment by AureliuszBrussy** [comment]
@tomylee0 dziękuję za cierpliwość. Problem nie powinien już występować.

**Comment by tomylee0** [comment]
Potwierdzam. Dzięki.
