### ISSUE TITLE
ERR_INTERNAL_SYSTEM_ERROR - Sandbox

### ISSUE THREAD

**Issue by skrux1** [allegro/allegro-api#51]
Dzień dobry, przy próbie logowania poprzez API Sandbox wyrzuca mi (od wczoraj): Błąd ERR_INTERNAL_SYSTEM_ERROR: Wewnętrzny bład systemu.
Tak jak metoda doQuerySysStatus zwraca poprawne dane, tak doLoginEnc już niekoniecznie (ERR_INTERNAL_SYSTEM_ERROR).

Język PHP.

**Comment by MarcinLuczak** [comment]
Dzień dobry. Mamy obecnie problemy z logowaniem do Sandboxa. Nie jest to łatwy problem, dlatego nie mam informacji kiedy zostanie usunięty, ale jeszcze w tym tygodniu planujemy uruchomienie nowego serwisu testowego, który powinien być wolny od tego problemu.

**Comment by karol-gontarski** [comment]
To samo u mnie, kiedy rozwiążecie problem?

**Comment by karol-gontarski** [comment]
Nie możecie testować zmian przed wprowadzeniem ? 
Nasi klienci się niecierpliwią my tracimy czas i pieniądze ....

**Comment by MarcinLuczak** [comment]
@karol-gontarski 
Tak jak wspomniałem wcześniej, nie jest to łatwy problem, dlatego nie mam informacji kiedy zostanie usunięty, ale jeszcze w tym miesiącu planujemy uruchomienie nowego serwisu testowego, który powinien być wolny od tego problemu.

**Comment by karol-gontarski** [comment]
Widzę że sprowadzenie specjalisty pomogło :D
