### ISSUE TITLE
Sandbox aktywacja konta

### ISSUE THREAD

**Issue by bherczyk** [allegro/allegro-api#510]
Dzień dobry,
proszę o aktywacje konta w Sandbox
mail: bherczyk@gmail.com
login: bherczyk

Pozdrawiam

**Comment by bherczyk** [comment]
Niestety nadal nie jest aktywne,
![image](https://user-images.githubusercontent.com/19627522/44336334-71140100-a477-11e8-9a15-c94b5ac87056.png)

**Comment by MartaNowaczyk** [comment]
Zobacz teraz, powinno być ok.

**Comment by bherczyk** [comment]
Konto jest aktywne ale mam problem, kiedy chcę wystawić przedmiot na sprzedaż to otrzymuje taki komunikat:
![image](https://user-images.githubusercontent.com/19627522/44340968-d3283280-a486-11e8-8612-7c9640fc341d.png)

Dane adresowe mam uzupełnione.

**Comment by MartaNowaczyk** [comment]
Wpisz proszę dane, które są poprawne, czyli ulicę, miasto i kod pocztowy, które się zgadzają z rzeczywistością.
