### ISSUE TITLE
Problem ze stanem dyskusji

### ISSUE THREAD

**Issue by therionq** [allegro/allegro-api#5100]
Występuje problem:
 - [X] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Generalnie chodzi o GET /sale/disputes

Problem pojawia się jeśli chodzi o aktualizację stanu dyskusji.
Załóżmy że mam w danym momencie dwie otwarte dyskusje, zamykam je i otwieram trzecią.
Po skorzystaniu z podanego wyżej zasobu dostaję odpowiedź z 1 otwartą i 2 zakończonymi dyskusjami. Ponownie korzystam z zasobu ok. minutę później i w odpowiedzi dostaję "poprzedni stan" dyskusji, widząc tylko nadal otwarte pierwsze dwie dyskusje, bez trzeciej. Czasami ten stan się zmienia kilka razy.

Czy to normalne, oczekiwane zachowanie? I czy takiego samego zachowania powinienem się spodziewać na produkcji?

**Comment by therionq** [comment]
> @therionq czy jesteś w stanie przesłać nam pełne requesty które wysyłasz i response'y które zwracamy? Możesz je zamieścić w wątku (usuń access_tokeny) lub jeżeli wolisz - przesłać poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W zgłoszeniu wskaż numer wątku na GitHubie: #5100.

Nie ma problemu, prześlę je tutaj najszybciej jak będę w stanie.

**Comment by therionq** [comment]
Request 1
Curl options:
[
  CURLOPT_URL => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
  CURLOPT_CUSTOMREQUEST => GET
  CURLOPT_HTTPHEADER => [
    Accept: application/vnd.allegro.public.v1+json
    Authorization: Bearer
  ]
  CURLOPT_RETURNTRANSFER => true
]

Response headers:
[expires] => 0
[cache-control] => no-cache, no-store, max-age=0, must-revalidate
[x-xss-protection] => 1; mode=block
[pragma] => no-cache
[x-frame-options] => DENY
[trace-id] => 14bf6334231bf9aa
[csrf-token] => 
[date] => Tue, 02 Nov 2021 11:15:25 GMT
[x-content-type-options] => nosniff
[content-type] => application/vnd.allegro.public.v1+json

Curl info:
[url] => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
[content_type] => application/vnd.allegro.public.v1+json
[http_code] => 200
[header_size] => 534
[request_size] => 1700
[filetime] => -1
[ssl_verify_result] => 0
[redirect_count] => 0
[total_time] => 0.208571
[namelookup_time] => 0.021705
[connect_time] => 0.040092
[pretransfer_time] => 0.076749
[size_upload] => 0
[size_download] => 4370
[speed_download] => 21009
[speed_upload] => 0
[download_content_length] => -1
[upload_content_length] => -1
[starttransfer_time] => 0.2075
[redirect_time] => 0
[redirect_url] => 
[primary_ip] =>
[certinfo] => Array
    (
    )

[primary_port] => 443
[local_ip] => 
[local_port] => 
[http_version] => 3
[protocol] => 2
[ssl_verifyresult] => 0
[scheme] => HTTPS
[appconnect_time_us] => 76600
[connect_time_us] => 40092
[namelookup_time_us] => 21705
[pretransfer_time_us] => 76749
[redirect_time_us] => 0
[starttransfer_time_us] => 207500
[total_time_us] => 208571

Raw response:
{"disputes":[{"id":"255e242f-94f8-41b4-9e6f-2fb0aabb666f","subject":{"name":"brak produktu w przesyłce"},"status":"ONGOING","messagesStatus":"SELLER_REPLIED","buyer":{"id":"44297046","login":"Client:44297046"},"checkoutForm":{"id":"aa418611-37b2-11ec-b192-a346b7fcd2a5","createdAt":"2021-10-28T05:48:29.000Z"},"message":{"id":"dfbea7c7-0deb-4416-ba17-550f7081d88e","text":"asd","author":{"login":"Client:44297046","role":"BUYER"},"createdAt":"2021-10-28T05:51:29.730Z"},"messagesCount":16,"lastMessageCreationDate":"2021-11-02T09:34:50.145Z"}]}


Request 2
Curl options:
[
  CURLOPT_URL => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
  CURLOPT_CUSTOMREQUEST => GET
  CURLOPT_HTTPHEADER => [
    Accept: application/vnd.allegro.public.v1+json
    Authorization: Bearer
  ]
  CURLOPT_RETURNTRANSFER => true
]

Response headers:
[expires] => 0
[cache-control] => no-cache, no-store, max-age=0, must-revalidate
[x-xss-protection] => 1; mode=block
[pragma] => no-cache
[x-frame-options] => DENY
[trace-id] => 84f8af11a69a041c
[csrf-token] => 
[date] => Tue, 02 Nov 2021 11:25:33 GMT
[x-content-type-options] => nosniff
[content-type] => application/vnd.allegro.public.v1+json

Curl info:
[url] => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
[content_type] => application/vnd.allegro.public.v1+json
[http_code] => 200
[header_size] => 546
[request_size] => 1700
[filetime] => -1
[ssl_verify_result] => 0
[redirect_count] => 0
[total_time] => 0.226182
[namelookup_time] => 0.023074
[connect_time] => 0.029721
[pretransfer_time] => 0.053892
[size_upload] => 0
[size_download] => 4369
[speed_download] => 19331
[speed_upload] => 0
[download_content_length] => -1
[upload_content_length] => -1
[starttransfer_time] => 0.226043
[redirect_time] => 0
[redirect_url] => 
[primary_ip] =>
[certinfo] => Array
    (
    )

[primary_port] => 443
[local_ip] =>
[local_port] =>
[http_version] => 3
[protocol] => 2
[ssl_verifyresult] => 0
[scheme] => HTTPS
[appconnect_time_us] => 53750
[connect_time_us] => 29721
[namelookup_time_us] => 23074
[pretransfer_time_us] => 53892
[redirect_time_us] => 0
[starttransfer_time_us] => 226043
[total_time_us] => 226182

Raw response:
{"disputes":[{"id":"255e242f-94f8-41b4-9e6f-2fb0aabb666f","subject":{"name":"brak produktu w przesyłce"},"status":"ONGOING","messagesStatus":"BUYER_REPLIED","buyer":{"id":"44297046","login":"Client:44297046"},"checkoutForm":{"id":"aa418611-37b2-11ec-b192-a346b7fcd2a5","createdAt":"2021-10-28T05:48:29.000Z"},"message":{"id":"dfbea7c7-0deb-4416-ba17-550f7081d88e","text":"asd","author":{"login":"Client:44297046","role":"BUYER"},"createdAt":"2021-10-28T05:51:29.730Z"},"messagesCount":19,"lastMessageCreationDate":"2021-11-02T11:17:04.294Z"}]}

Request 3
Curl options:
[
  CURLOPT_URL => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
  CURLOPT_CUSTOMREQUEST => GET
  CURLOPT_HTTPHEADER => [
    Accept: application/vnd.allegro.public.v1+json
    Authorization: Bearer
  ]
  CURLOPT_RETURNTRANSFER => true
]

Response headers:
[expires] => 0
[cache-control] => no-cache, no-store, max-age=0, must-revalidate
[x-xss-protection] => 1; mode=block
[pragma] => no-cache
[x-frame-options] => DENY
[trace-id] => f9180085905ec893
[csrf-token] =>
[date] => Tue, 02 Nov 2021 11:27:23 GMT
[x-content-type-options] => nosniff
[content-type] => application/vnd.allegro.public.v1+json

Curl info:
[url] => https://api.allegro.pl.allegrosandbox.pl/sale/disputes?limit=100&offset=0
[content_type] => application/vnd.allegro.public.v1+json
[http_code] => 200
[header_size] => 540
[request_size] => 1700
[filetime] => -1
[ssl_verify_result] => 0
[redirect_count] => 0
[total_time] => 0.115772
[namelookup_time] => 0.022358
[connect_time] => 0.039237
[pretransfer_time] => 0.069066
[size_upload] => 0
[size_download] => 4370
[speed_download] => 38000
[speed_upload] => 0
[download_content_length] => -1
[upload_content_length] => -1
[starttransfer_time] => 0.115659
[redirect_time] => 0
[redirect_url] => 
[primary_ip] =>
[certinfo] => Array
    (
    )

[primary_port] => 443
[local_ip] =>
[local_port] =>
[http_version] => 3
[protocol] => 2
[ssl_verifyresult] => 0
[scheme] => HTTPS
[appconnect_time_us] => 68942
[connect_time_us] => 39237
[namelookup_time_us] => 22358
[pretransfer_time_us] => 69066
[redirect_time_us] => 0
[starttransfer_time_us] => 115659
[total_time_us] => 115772

Raw response:
{"disputes":[{"id":"255e242f-94f8-41b4-9e6f-2fb0aabb666f","subject":{"name":"brak produktu w przesyłce"},"status":"ONGOING","messagesStatus":"SELLER_REPLIED","buyer":{"id":"44297046","login":"Client:44297046"},"checkoutForm":{"id":"aa418611-37b2-11ec-b192-a346b7fcd2a5","createdAt":"2021-10-28T05:48:29.000Z"},"message":{"id":"dfbea7c7-0deb-4416-ba17-550f7081d88e","text":"asd","author":{"login":"Client:44297046","role":"BUYER"},"createdAt":"2021-10-28T05:51:29.730Z"},"messagesCount":16,"lastMessageCreationDate":"2021-11-02T09:34:50.145Z"}]}

**Comment by AureliuszBrussy** [comment]
@therionq dziękuję, przekazałem to do zespołu odpowiedzialnego za ten zasób - wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@therionq rozpoznaliśmy problem - jest związany z cache'owaniem po stronie naszych usług. Obecnie na produkcji zachowanie może być podobne. Jest to zaadresowane w zespole rozwijającej ten zasób, ale aktualnie nie jestem w stanie określić, kiedy to zmienimy.

**Comment by therionq** [comment]
@AureliuszBrussy rozumiem i dziękuję za informacje. Dobrze przynajmniej wiedzieć, że problem rozpoznano i zostanie to zmienione 🙂
