### ISSUE TITLE
Test Order

### ISSUE THREAD

**Issue by Liketodev3** [allegro/allegro-api#5101]
HI . Is there a way to make a test order in Allegro? Should I have a sandbox account? Thanks in advance

**Comment by hynci117** [comment]
Hi, can you please activate sales for my sandbox account too?
login: Artcrystal1989

**Comment by Lukasz-Zurek** [comment]
@hynci117 Hello. I have already fully activated your sandbox account. You can use it without any restrictions.

**Comment by eskono** [comment]
hi. can you activate my sandbox account also?
maksim.shauchuk@ovoko.com

**Comment by Lukasz-Zurek** [comment]
@eskono Your account is active. But as I see right know - you have a block sell. Please go to the [Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro#toolbar-user-menu/konto) tab and pay the fees using the payment simulator ("PAY" button).

**Comment by btetur** [comment]
Dear Allegro support, I am trying to activate sales on my account. My account is in Czech republic.Is it possible to use it
to verify account? Or can you help to activate my sales here as I see it in above contributes?

**Comment by Lukasz-Zurek** [comment]
@btetur If you want to activate your account on the Allegro Sandbox (our test environment) - you will have to give me your login - then I can help you. But if your case concerns an account on the Allegro.pl - please contact Customer Support via this [form](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433).

**Comment by bologer** [comment]
@Lukasz-Zurek can you activate my account as well - Client:106144523?

**Comment by MartaNowaczyk** [comment]
@bologer The specified regular account is already active.

**Comment by TomasPilar** [comment]
@MartaNowaczyk @Lukasz-Zurek can you activate my sandbox account as well - Client: conviu (info@conviu.com) (Sandbox). Thank you

**Comment by PrzemyslawLukanowski** [comment]
@TomasPilar I've activated your account.
