### ISSUE TITLE
Sale offers nie wyszukuje oferty 

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#5109]
Dzień dobry,
przy próbie wyszukania aukcji nie zwraca mi jednej z  istniejących aukcji - możliwe że więcej ale na razie  tą namierzyłem 

https://api.allegro.pl/sale/offers?limit=50&offset=0&external.id=N-008H-P6LU-01BO-0-45

próbowałem bez podawania fitów przeszukać wszystkie strony 
próbowałem podawać wszystkie możliwe opcje w publication.status 
za każdym razem nic 
ale podając numer aukcji https://api.allegro.pl/sale/offers/10196079855 
zostaje prawidłowo wyświetlona 
 
Mogę prosić o jakąś podpowiedź dlaczego ta aukcja nie zostaje znaleziona i co muszę zrobić aby była "wyszukiwalna"?

**Comment by MaciejFrackowiak** [comment]
Wskazana oferta została przez Ciebie ukryta, przez co nie zwracaliśmy jej. Obecnie upłynęło 60 dni od jej zakończenia i została ostatecznie zarchiwizowana.

**Comment by mzawodzinski** [comment]
Mogę prosić o sprecyzowanie co oznacza "wskazana oferta została przez Ciebie ukryta",
konsultuję to z osobami które zajmują się aukcjami i ile osób tyle teorii co kryje się pod słowem "ukryta"

**Comment by MaciejFrackowiak** [comment]
Na stronie WWW istnieje opcja ukrycia zakończonych ofert - tak, aby nie były już widoczne na liście Moje oferty - w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/moje-oferty-lista-sprzedawanych-ofert-5VZjLom02s9#jak-ukryc-zakonczone-oferty) znajdziesz szczegółowe wskazówki.

**Comment by mzawodzinski** [comment]
W sumie to to dalej nie rozwiązuje problemu.

Proszę przykład,
https://api.allegro.pl/sale/offers/10196009033
`
{
...
	"external":{
		"id":"N-008H-P6LU-01BO-0-38"
	},
	"publication":{
		"status":"ENDED",
	}
...
}
`
mam aukcje 10196009033 która jest zakończona.
Teraz wysyłam żądanie "hej api, podaj mi listę zakończonych aukcji o podanym external id", na co api mi odpowiada że nie ma takich aukcji chociaż jak widać wyżej są 

https://api.allegro.pl/sale/offers?external.id=N-008H-P6LU-01BO-0-38&publication.status=ENDED
`{"offers":[],"count":0,"totalCount":0}`

**Comment by MaciejFrackowiak** [comment]
Oferta 10196009033 została ukryta - nie jest dostępna ani na liście Moje oferty na stronie WWW, ani dla zasobu GET /sale/offers. Tym samym nie znajdziesz jej szukając po sygnaturze.
