### ISSUE TITLE
Błąd przy wstawianiu aukcji poprzez REST API ale tylko dla wybranych aukcji?

### ISSUE THREAD

**Issue by tomasz244** [allegro/allegro-api#5114]
Witam.

mam problem przy wystawianiu ofert poprzez REST. Dziwne to ponieważ z tego co zauważyłem to problem występuje dla kategorii i wszystkich podkategorii części samochodowych - Zderzaki. Pozostałe kategorie wskakują normalnie. Gdy ręcznie próbuje wystawić to wszystko jest ok. Rozumiem, że coś po stronie Allegro ?

**Comment by MaciejFrackowiak** [comment]
Czy możesz podać nam więcej szczegółów - np. przykładowy trace-id wywołania? Tylko tak możemy zweryfikować ewentualny problem.
