### ISSUE TITLE
Mam problem z darmową aplikacja allegro 

### ISSUE THREAD

**Issue by Esklep21n** [allegro/allegro-api#5116]
Tworze właśnie swój sklep internetowy gdyż już sprzedaje na allegro.... chciałbym skorzystać na początku z darmowej aplikacji która pozwala mi na darmowe przerzucenie 100 ofert z allegro do mojego sklepu internetowego i nie wiem z jakich przyczyn allegro odmówiło mi dostępu weryfikacji i dostępu do tej właśnie aplikacji nie uzasadniając swojej decyzji do zamówieniu rozmowy telefonicznej z konsultantem powiedziano mi że rzekomo dostęp do tej aplikacji maja osoby z większym obrotem na allegro a nigdzie takie zapisu nie ma.. co mogę zrobić w tej sytuacji gdyż naprawdę chciałbym przetestować tą aplikację. 
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Proces weryfikacji dostępu do zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#tag/Public-offer-information) jest prowadzony całkowicie poza naszym spektrum działania - tym samym wszelkie informacje możesz uzyskać tylko i wyłącznie kontaktując się z obsługą Allegro poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by rafaljosko** [comment]
Pewnie masz sklep na ovh lub innym serwerze, allegro banuje ip ovh automatycznie.
