### ISSUE TITLE
Oszczędzać tokeny?

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#5117]
Pobieram listę wszystkich ofert użytkownika. Trwa to ponad minutę ponieważ pobieram kody EAN z poszczególnych ofert. Zamiast czekać na skończenie ważności tokena, przed każdą operacją odświeżam go. Np. przed pobraniem wszystkich ofert.

Moje pytanie jest takie czy warto badać datę i czas ważności tokena aby nie naprodukować ich zbyt wiele. Np. mogę odświeżać token na godzinę przed jego końcem ważności. Także przed operacją.

**Comment by AureliuszBrussy** [comment]
Obowiązuje limit dla liczby access tokenów, które możesz wygenerować w określonym czasie dla jednego użytkownika. Jeżeli go przekroczysz, w odpowiedzi zwrócimy błąd 429 - Too Many Requests. Dobrą praktyką jest używanie access tokena aż do momentu jego wygaśnięcia i wtedy jego odświeżenie.

**Comment by jmarek-pl** [comment]
Niestety nie ma możliwości sprawdzenia ile dany token jest jeszcze ważny. Zatem muszę obliczyć datę i czas wygaśnięcia i zapisać w bazie danych. Zastanawiam się jaki czas zapisać w bazie danych aby nie było problemów np. przy zmianie czasu letniego na zimowy i odwrotnie. Może zapisać czas UTC w bazie danych?

No i odświeżać token na godzinę przed jego wygaśnięciem, tak aby nie trzeba było potrzeby ponawiać operacji jeśli w czasie niej wygaśnie token. W takim przypadku token będzie odświeżany raz lub dwa razy dziennie. Chyba to nie jest zbyt dużo?

**Comment by AureliuszBrussy** [comment]
@jmarek-pl każdy jwt ma zakodowaną datę wygaśnięcia (exp). Możesz swobodnie go odkodować, żeby odczytać datę. Sprawdź jakie dane są zakodowane w tokenie np. na [https://jwt.io/](https://jwt.io/). 

Oczywiście odświeżanie na godzinę przed wygaśnięciem tokena nie będzie działaniem nieprawidłowym. Nie będzie zupełnie optymalne, ale też nie będzie nadmiarowe.

**Comment by jmarek-pl** [comment]
Przyjrzałem się implementacji JWT dla .net: https://github.com/jwt-dotnet/jwt Dekodowanie tokena to nie taka prosta rzecz.  Mam obawy, że aplikacja stanie się zbyt wrażliwa na szczegóły implementacji JWT przez Allegro. Wygląda, że są możliwe różne algorytmy szyfrowania. Nie wiem jeszcze do czego służy sekret i jak token jest weryfikowany lub nie.

**Comment by AureliuszBrussy** [comment]
@jmarek-pl oczywiście decyzja o ostatecznej implementacji należy do Ciebie - możesz także zdecydować się na rozwiązanie o którym pisałeś wcześniej (zapisywanie czasu UTC). Wraz z access_tokenem zwracamy pole expires_in, gdzie znajdziesz liczbę sekund do wygaśnięcia (nie datę wygaśnięcia).

**Comment by hahyes** [comment]
> Przyjrzałem się implementacji JWT dla .net: https://github.com/jwt-dotnet/jwt Dekodowanie tokena to nie taka prosta rzecz. Mam obawy, że aplikacja stanie się zbyt wrażliwa na szczegóły implementacji JWT przez Allegro. Wygląda, że są możliwe różne algorytmy szyfrowania. Nie wiem jeszcze do czego służy sekret i jak token jest weryfikowany lub nie.

Tylko w .NET da się dużo prościej:

```
public static JwtSecurityToken DecodeToken(string token)
{
     return new JwtSecurityToken(jwtEncodedString: token);
}
```

Potem sobie po prostu pobierasz pole `Claims` z obiektu klasy `JwtSecurityToken` i masz całą listę wartości zawartych w JWT.

**Comment by jmarek-pl** [comment]
Wiem o tym, że Microsoft ma własną implementację ale na blogu: https://briancaos.wordpress.com/2020/02/27/c-get-expiry-timestamp-from-jwt-token/ , zaproponowali inne rozwiązanie ze względu na zależności i kompatybilność. A ja właśnie tworze aplikację WPF/C#, a nie ASP.NET (Core).
I tak przyjąłem inne rozwiązanie. Nawet gdybym rozkodowywał tokena to i tak przechowywał bym w bazie danych datę/czac UTC, aby nie rozkodowywać go wielokrotnie gdy sprawdzam datę. Także łatwiej jest obliczyć datę ważności na podstawie odpowiedzi serwera.
Nie miej ciekawe było dowiedzieć się trochę o tym co zawiera token JWT.
