### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by erichspitz** [allegro/allegro-api#5118]
Good afternoon, our business team wants to sell products on Allegro marketplace, so we would like to use the Allegro API to send items + stock, and receive orders by a job queue without any user interface. What is the correct authentication method - is this DCR? In this case, can you give us please the software statement ID? Is there somebody to talk to for an initial meeting - I'm little bit lost within all the documentations

Thank and regards,
Erich Spitz

**Comment by MartaNowaczyk** [comment]
Hello Erich. For applications without a user interface, you can use device flow authorization. You can find more in [our guide](https://developer.allegro.pl/en/auth/#device-flow).
If you have any questions you can write to us on Github. According to the rule, a new topic - a new issue.
