### ISSUE TITLE
dostępu w API dla GET /offers/listing

### ISSUE THREAD

**Issue by logatero** [allegro/allegro-api#5119]
Witam
Jak uzyskać dostęp w API dla GET /offers/listing ?

**Comment by logatero** [comment]
postępuje wg tego:
https://github.com/allegro/allegro-api/discussions/4569

**Comment by MartaNowaczyk** [comment]
Tutaj nie weryfikujemy aplikacji. Proces weryfikacji aplikacji przejdziesz, kontaktując się przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - sprawa trafi do odpowiedniego zespołu, który zajmie się zgłoszeniem.
