### ISSUE TITLE
Problem z finkcją webapi: doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#512]
request: 
array(2) { ["sessionId"]=> string(52) "257b22____WIADOMO___0bcc68//00_1" ["transactionsIdsArray"]=> array(20) { [0]=> int(889759471) [1]=> int(889740734) [3]=> int(889394957) [4]=> int(889346035) [5]=> int(889255477) [6]=> int(889207715) [7]=> int(889202049) [8]=> int(889150551) [10]=> int(889139782) [11]=> int(889094824) [12]=> int(889008366) [14]=> int(888927275) [16]=> int(888854297) [17]=> int(888807983) [18]=> int(888702873) [19]=> int(888682552) [20]=> int(888667485) [21]=> int(888636943) [22]=> int(888633227) [23]=> int(888622409) } }
RESPONSE Fatal error: Uncaught SoapFault exception: [ERR_INPUT_ARRAY_EMPTY] Podana tablica jest pusta

**Comment by MartaNowaczyk** [comment]
Witam, [wcześniej](https://github.com/allegro/allegro-api/issues/509) pisałeś, że nie działa, a potem, że działa, więc jak to dokładnie wygląda?

**Comment by marcinja2** [comment]
Po czasie odświeżyłem i zadziałało. potem znów nie. Generalnie nie wiem co jest grane. po zastosowaniu request["transactionsIdsArray"]=implode(explode(tablicaIdentyfikatorówFormularzy)) błąd pustej tablicy znika ale funkcja zwraca dane innych formularzy dostawy. Sprawa do realizacji wydaje się bardzo prosta ale  wyniki są przedziwne

**Comment by marcinja2** [comment]
jedyna różnica jaką widzę w dokumentacji a podawanymi danymi to że tablica request jest typu int natomiast w dokumentacji jest long. Piszę w php.

**Comment by marcinja2** [comment]
teraz działa albo coś ze mną jest nie tak albo system wam jaką zawiechę łapie
