### ISSUE TITLE
Opóźnienie w wystawianiu ofert poprzez API

### ISSUE THREAD

**Issue by wwm99** [allegro/allegro-api#5122]
Dzień dobry, obserwujemy od wczoraj dużo opóźnienie w pojawianiu się ofert po stronie Allegro wystawionych via API, z poziomu panelu IdoSell. Kiedy można się spodziewać poprawy?

Pozdrawiam!

**Comment by PrzemyslawLukanowski** [comment]
Aktywacja oferty może potrwać do godziny i nie należy tego traktować jako błąd- czy w tym przypadku czas aktywacji był dłuższy? Jeśli tak, poproszę o przykładowe numery ofert, dla których wystąpiły opóźnienia.

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się znaleźć przyczynę opóźnień, czas aktywacji powinien już wracać do normy. Przepraszam za utrudnienia.
