### ISSUE TITLE
Internal server error na endpoincie /sale/classifieds-packages

### ISSUE THREAD

**Issue by niewiadomsky** [allegro/allegro-api#5123]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
### Request:
{
   "method": "GET",
   "url": "https://api.allegro.pl.allegrosandbox.pl/sale/classifieds-packages?category.id=257753",
   "path": "/sale/classifieds-packages",
   "headers": {
      "Host": [
         "api.allegro.pl.allegrosandbox.pl"
      ],
      "Authorization": [
         "Bearer {{myToken}}"
      ],
      "Accept": [
         "application/vnd.allegro.public.v1+json"
      ],
      "Content-Type": [
         "application/vnd.allegro.public.v1+json"
      ],
      "Accept-Language": [
         "pl-PL"
      ]
   },
   "query": "category.id=257753",
   "body": ""
}

### Response:
{
   "status": 500,
   "body": "{\"errors\":[{\"code\":\"INTERNAL_SERVER_ERROR\",\"message\":\"Internal server error.\",\"details\":null,\"path\":null,\"userMessage\":\"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut.\"}]}",
   "headers": {
      "expires": [
         "0"
      ],
      "cache-control": [
         "no-cache, no-store, max-age=0, must-revalidate"
      ],
      "x-xss-protection": [
         "1; mode=block"
      ],
      "pragma": [
         "no-cache"
      ],
      "x-frame-options": [
         "DENY"
      ],
      "trace-id": [
         "f4d608c4d8ccd4fa"
      ],
      "date": [
         "Wed, 03 Nov 2021 09:14:08 GMT"
      ],
      "x-content-type-options": [
         "nosniff"
      ],
      "content-type": [
         "application/json; charset=utf-8"
      ],
      "content-length": [
         "185"
      ]
   }
}

Trace id: f4d608c4d8ccd4fa

Pojawia się błąd z kodem 500 i nie można pobrać pakietów dla kategorii.

**Comment by PrzemyslawLukanowski** [comment]
Problem występuje, ponieważ używasz tokena wygenerowanego w ramach autoryzacji [client_credentials](https://developer.allegro.pl/auth/#client-credentials-flow). Zgodnie z oznaczeniem w [naszej dokumentacji](https://developer.allegro.pl/documentation/#operation/getClassifiedPackageConfigurationsForCategoryUsingGET), aby skorzystać z tego endpointu, musisz użyć autoryzacji typu [code](https://developer.allegro.pl/auth/#authorization-code-flow) lub [device](https://developer.allegro.pl/auth/#device-flow).

**Comment by niewiadomsky** [comment]
Bardzo dziękuję
