### ISSUE TITLE
Wysylam Z Allegro, błąd zamówienia podjazdu poczta

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#5124]
Występuje problem: 
 - [ ] z zasobem REST API
 - [X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Nie za bardzo wiem komu zgłosić ten problem, ale dla utworzonych paczek nie możemy zamówić podjazdu dla poczty (udało się tylko dla jednej).
Do tej pory nie było problemu - mieliśmy odbiór 3x w tygodniu, teraz ma być codziennie.
![image](https://user-images.githubusercontent.com/49162881/140042966-4756d857-e494-45d1-87d9-a45488fbd27f.png)
![image](https://user-images.githubusercontent.com/49162881/140043095-225f0e39-3db5-417d-a428-a2a234a37b86.png)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać trace-id dla nieudanych prób zamówienia podjazdu kuriera? Jeśli problem występuje tylko na stronie internetowej, skorzystaj proszę z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5).
