### ISSUE TITLE
WzA "Punkt punktu nadania przesyłki jest niepoprawny"

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5125]
zamówienie 0b07d4e2-3c22-11ec-a78c-dd9aa211ae3a
pickup.pointId = "U99495968" (wartość pobrana ze strony https://www.ups.com/dropoff/ adres: JANA KILINSKIEGO 88, 42218, CZESTOCHOWA)
Dlaczego wartość jest odrzucana?

**Comment by AureliuszBrussy** [comment]
Wybrana przez kupującego metoda dostawy to Allegro Punkty Kolporter (aktualnie Allegro One Punkt), natomiast próbujesz nadać przysyłkę z punktu należącego do innego przewoźnika (UPS). Stąd błąd o nieprawidłowym punkcie nadania.

**Comment by ciaglok2** [comment]
Te przesyłki podejmuje kurier UPS, ale rozumiem. Dziękuję.

**Comment by ciaglok2** [comment]
A dlaczego ten sam błąd otrzymuję dla zamówienia 6ce75691-3d49-11ec-857a-ff38b57252af ?
