### ISSUE TITLE
Problem z parametrami FID 237190

### ISSUE THREAD

**Issue by electrosoft1** [allegro/allegro-api#5128]
Witam, w niektórych kategoriach np. alarmy-detektory-46114 podczas wystawiania, aktualizacji oferty w wielu aukcjach pojawia się komunikat "Missing required parameters: 237190", fid wskazuje na "Marka" jednak podczas pobierania wymaganych parametrów "sale/categories/46114/parameters" ten niby wymagany parametr nie występuję, a właściwy fid sugerowany przez allegro wskazuje na 248811 - Marka, 
Sprawdzam już kolejny dzień co może być nie tak w moim oprogramowaniu jednak dochodzę do wniosku że to problem allegro.

**Comment by AureliuszBrussy** [comment]
Aktualnie nie potwierdzam tego problemu -  odpytując GET /sale/categories/46114/parameters zwracamy parametr 237190 (Marka). Jesteś w stanie podać jakiś inny przykład takiej sytuacji?

**Comment by electrosoft1** [comment]
mój błąd, potwierdzam allegro działa OK, problem polegał na zmianie kategorii przez allegro, mój system używa kategorii "Pozostałe" i w niej sprawdzał dostępne parametry a allegro zmienia na "Centrale alarmowe" (co uważam za duży błąd ponieważ nie są to centrale alarmowe ale akcesoria do central alarmowych), jedyne obejście problemu to zakończenie poprzedniej aukcji i wystawienie nowej. 

Przenieśliśmy Twoje oferty:

    Moduł kontrolera przejścia z zasilaczem SATEL (numer: 9761351197)
    Miniaturowy ekspander wejść i wyjsć SATEL (numer: 8697003339)
    Ekspander wyjść ROPAM EXP-O8T-RN (numer: 10710884808)
    MODUŁ ROPAM EKSPANDER EXP-I8 (numer: 9747117871)

z kategorii:

    Dom i Ogród : Budownictwo i Akcesoria : Elektryka i akcesoria : Alarmy : Pozostałe

do kategorii:

    Dom i Ogród : Budownictwo i Akcesoria : Elektryka i akcesoria : Alarmy : Centrale alarmowe
