### ISSUE TITLE
Pytanie o stan aukcji w REST Api

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#513]
Hej,

Pobieranie informacji o auckjach przez WebApi miało tę przypadłość, że jeśli dana aukcja wchodziła w swój moment rozliczeniowy to pokazywana była jako zakończona (endingInfo bodajże 2 lub 3). Później oczywiście wszystko wraca do normy.

Czy podobnie dzieje się w REST Api? Aukcja, która akurat jest rozliczana ma status ENDED/INACTIVE w zasobie GET /sale/offers/{offerId} ?

**Comment by MartaNowaczyk** [comment]
Domyślamy się, że chodzi o oferty ze stałym numerem, ale nie mamy pewności. 

Podeślij proszę jakieś konkretne przykłady ofert, dla których obserwujesz takie zachowanie. Podaj też metodę, którą odpytujesz i info co zwraca.

**Comment by MartaNowaczyk** [comment]
@imper86 podpytuję jeszcze raz 
Masz jakieś przykłady, albo chociaż info jakiego typu była to oferta?

**Comment by imper86** [comment]
@MartaNowaczyk jak mi się uda namierzyć przykład to podeślę

**Comment by MartaNowaczyk** [comment]
@imper86 ok
