### ISSUE TITLE
Brak możliwości wystawienia ofert

### ISSUE THREAD

**Issue by Ziutkaaa** [allegro/allegro-api#5130]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

klikajac na zakladke Sprzedaz>"Wystaw przedmiot", otrzymuje komunikat: 
_Ta witryna jest nieosiągalnaSprawdź, czy w adresie staging-lokalnie.allegrogroup.com nie ma błędu.
Jeśli pisownia jest poprawna, uruchom Diagnostykę sieci systemu Windows.
DNS_PROBE_FINISHED_NXDOMAIN__
poprosze o wskazówki

**Comment by AureliuszBrussy** [comment]
W przypadku konta zwykłego (nie firmowego) na Sandbox ofertę wystawisz tylko poprzez bezpośredni odnośnik: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

**Comment by Ziutkaaa** [comment]
Dziekuje za podpowiedź :)

**Comment by Ziutkaaa** [comment]
Dzien dobry, udało sie wystwic oferte, jednak za kazdym razem, gdy chce wejsc w zakladke moja sprzedaz przerzuca mnie do ekranu logowania, tam moje haslo najpierw jest nieprawidlowe, nastepnie otrzymuje komunikat "Wymagane jest rozwiązanie captchy". prosze o pomoc :)

**Comment by AureliuszBrussy** [comment]
@Ziutkaaa chodzi o zakładkę "[Moje oferty](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty)"? Nie potwierdzam żadnego problemu - Sandbox działa prawidłowo. Spróbuj proszę skorzystać z trybu incognito i sprawdź, czy problem dalej występuje.

**Comment by AureliuszBrussy** [comment]
Gdy korzystasz bezpośrednio z [tego linku](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/moje-oferty) - problem także występuje? Gdy korzystasz z konta zwykłego z niektórych zakładek z sekcji "Sprzedaż", jesteś kierowana na testową wersję Allegro Lokalnie, która nie jest dostępna publicznie. Zwróć uwagę na adres strony, która nie jest osiągalna.

**Comment by Ziutkaaa** [comment]
Gdy korzystam z podanego przez Państwa linku problem nadal występuje

**Comment by AureliuszBrussy** [comment]
@Ziutkaaa podaj proszę jeszcze login swojego konta na Sandboxie.

**Comment by Ziutkaaa** [comment]
proszę :) 
derej.paulina@gmail.com
Filipek_123

**Comment by AureliuszBrussy** [comment]
@Ziutkaaa zweryfikowałem konto - jest ono w pełni aktywne. Nie odnotowujemy na Sandboxie żadnej awarii, więc korzystanie z zakładek związanych ze sprzedażą jest możliwe.
