### ISSUE TITLE
logowanie https://allegro.pl/auth/oauth/token

### ISSUE THREAD

**Issue by fistechcentrum** [allegro/allegro-api#5132]
Chcę wygenerować access token ale nie mogę się zalogować do https://allegro.pl/auth/oauth/token
używam loginu i hasła z allegro ale bez powodzenia ( allegro login "fistechcentrum" )

**Comment by MartaNowaczyk** [comment]
Wygląda to na problem z wartością dla ClientSecret. Sprawdź jaką wartość przekazujesz.

**Comment by fistechcentrum** [comment]
Próbowałem do logowania użyć L: Client ID i P: Client Secret ale otrzymuje komunikat 
{"error":"invalid_request","error_description":"Missing grant type"}

**Comment by MartaNowaczyk** [comment]
Error "Missing grant type" wskazuje na to, że nie przekazujesz tego parametru w zapytaniu. Prawidłowe żądanie wygląda tak:

`https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={redirect_uri}`

**Comment by fistechcentrum** [comment]
Problem rozwiązał się sam, korzystam z e-sklepu Comarchu, okazało się że z poziomu sklepu internetowego integracja z API przebiega automatycznie po wybraniu określonej opcji, dziękuje za pomoc
