### ISSUE TITLE
Allegro odbiór w punkcie DPD -  

### ISSUE THREAD

**Issue by PiotrTaraszkiewicz** [allegro/allegro-api#5133]
Chcemy wdrożyć do naszej aplikacji możliwość przygotowania etykiet dla Allegro odbiór w punkcie DPD poprzez Wysyłam z Allegro.
Przy próbie utworzenia listu otrzymuje komunikat:
ERROR - receiver.pointId: Punkt odbiorcy jest niepoprawny 

Czy do utworzenia takich przesyłek należy wskazać usługę Allegro DPD i id punktu widoczne w formularzu zamówienia ((PL15160)?

Na środowisku testowym Allegro złożone jest zamówienie 
28db4760-3cb1-11ec-a3ea-df8067f7628b
ze sposobem dostawy:  Allegro Odbiór w Punkcie DPD (DPD PL15160)

Próbuję przygotować etykietę przez API  WzA:
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/aaecdffc-1bcc-41d9-a56a-247f25108f1f

W danych odbiorcy podaję id punktu = PL15160
Jako usługę wskazuję Allegro DPD: "serviceId": 9030371,

"receiver": {
		"address": {
			"street": "Radiowa 18",
			"postCode": "01-485",
			"city": "Warszawa",
			"countryCode": "PL",
			"county": null
		},
		"email": "aucw5akm72+280a28792@user.allegrogroup.pl",
		"name": "Jan Kowalski",
		"company": "firma testowa",
		"phone": "111111111",
		"pointId": "PL15160"
	},

**Comment by MartaNowaczyk** [comment]
Na środowisku testowym przewoźnicy ograniczają się do znacznie zmniejszonej puli dostępnych punktów, dlatego może pojawić się opisana sytuacja.

**Comment by PiotrTaraszkiewicz** [comment]
To by tłumaczyło dlaczego na mapie też nie było widać żadnych punktów.
Prosiłbym tylko o potwierdzenie, że należy dla tej metody używać usługi "Allegro DPD" i wskazywać punkt w formacie PL15160.

**Comment by MartaNowaczyk** [comment]
Tak, "Allegro DPD" i odpowiedni punkt odbioru w podanym formacie. Najlepiej korzystaj z zasobów do pobierania aktualnych danych. ServiceId dla "Allegro DPD" pobierzesz przez GET /parcels/delivery-services. W szczegółach zamówienia: GET /order/checkout-forms/{id}, w polu: delivery.pickupPoint.id znajdziesz wartość dla punktu odbioru - to ta sama co w szczegółach zamówienia.

**Comment by PiotrTaraszkiewicz** [comment]
Dziękuję

**Comment by Piotr89-sol** [comment]
Dzień dobry, może będzie mógł ktoś w tym temacie pomóc, przeszukałem forum (możliwe że nieskutecznie, jeśli tak to przepraszam) i nie mogę znaleźć odpowiedzi czy dla przesyłek testowych (API testowe) DPD **dla odbioru w punkcie** ma jakieś specjalne punkty - obsługiwane właśnie przez ich testowe środowisko. Wiem, że taka sytuacja istnieje w wypadku Paczkomatów InPost, gdzie KRA011 i KRA012 umożliwiają zlecanie przesyłek testowych. Z góry dziękuję za pomoc.

**Comment by MartaNowaczyk** [comment]
Na wstępie poproszę zakładaj nowy wątek w nowej sprawie oraz dodawaj kolejne komentarze zamiast edytować, bo Twoje pytania mogą nam umknąć i nie otrzymasz odpowiedzi. 
Mogę podać przykładowy punkt odbioru:
```
“pickupPoint”: {
                    “id”: “PL11500”,
                    “name”: “DPD”,
                    “description”: “Dpd Pickup : 606-711-644”,
                    “address”: {
                        “street”: “Ciołka 13 lok18",
                        “zipCode”: “1445",
                        “city”: “Warszawa”
                    },
                    “modifiedAt”: null
                },
```
