### ISSUE TITLE
Brak odpowiednich informacji o sposobie nadania wybranych w formularzu pozakupowym

### ISSUE THREAD

**Issue by wwm99** [allegro/allegro-api#5135]
Dzień dobry,

wczytujemy zamówienia poprzez IdoSell z Allegro i mamy notoryczny problem z jedną z metod dostawy: Allegro Odbiór w Punkcie UPS. Panowie z BOK, z IdoSell twierdzą, że nie dostajemy w tym przypadku odpowiednich informacji poprzez API, natomiast sprawdzona przez nich konfiguracja mapowania usług kurierskich wygląda w porządku.
Czy to możliwe, że w przypadku tej usługi odpowiednie informacje są nieprzekazywane? 
Przykład takiego zamówienia to zamówienie o id: 6ce16792-3ca3-11ec-af3c-7b492599168b.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, jakich informacji konkretnie brakuje w zamówieniu? W [naszym poradniku](https://developer.allegro.pl/orders/#szczeg%c3%b3%c5%82y-zam%c3%b3wienia) znajdą Państwo komplet danych, jakie zwracamy dla każdej metody dostawy (proszę kliknąć "Kliknij, żeby zobaczyć przykładowy response:").

**Comment by wwm99** [comment]
Wygląda na to, że chodzi o samą metodę dostaw. Czyli  delivery.method. Ciekawy problem jest taki, że dotyczy tylko metod dostaw Allegro UPS.

**Comment by wwm99** [comment]
Nie widzę logów, ale odpowiedź od IAI IdoSell to: "Brak informacji o formie dostawy w odpowiedzi z serwisu aukcyjnego".

**Comment by PrzemyslawLukanowski** [comment]
Nie mogę potwierdzić problemu po naszej stronie, poniżej przesyłam informacje o metodzie dostawy, jakie zwracamy dla tego zamówienia:

```
        "method": {
            "id": "0d69a62b-7a66-4bd1-9134-49dea68dccc8",
            "name": "Allegro Odbiór w Punkcie UPS"
        },
```
[4 października zmieniliśmy nazwy wybranych metodach dostawy](https://developer.allegro.pl/news/#changing-methods-names), w tym wcześniejszą nazwę " Allegro UPS Odbiór w Punkcie" zmieniliśmy na "Allegro Odbiór w Punkcie UPS" - być może to ma wpływ na bieżące problemy. Sugeruję skonsultować to ponownie ze wsparciem  oprogramowania, z którego korzystasz.

**Comment by wwm99** [comment]
Dziękuję Państwu bardzo. Wracam zatem z problemem do naszego usługodawcy.

<http://music99.pl>

MUSIC99
SOUND LIGHT DJ & MUSIC MEGASTORE
WWW.SPRZET-DYSKOTEKOWY.PL <https://sprzet-dyskotekowy.pl>
***@***.*** ***@***.***>
TEL: +48 22 666 64 70 <+48226666470>
<http://facebook.com/music99pl>
<https://www.youtube.com/channel/UCgsZSOgAuvvlhIiqLaZjU3Q>

M99 SP. Z O.O. SP. K.
DANE REJESTROWE SPÓŁKI: UL. FORTUNY 12A/1, 01-339 WARSZAWA, REGON:
363717171, NIP 5223053881
ADRES KORESPONDENCYJNY: UL. FORTUNY 12A/1, 01-339 WARSZAWA
<https://goo.gl/maps/VUrytEeqB5z>
ADRES SERWISU: UL. KOLEJOWA 16L, 22-500 HRUBIESZÓW
DZIAŁ HURTU I DYSTRYBUCJI: MUSICTRADE.PL <https://musictrade.pl>, TEL: +48
22 666 64 72 <+48226666472>


czw., 4 lis 2021 o 10:42 PrzemyslawLukanowski ***@***.***>
napisał(a):
