### ISSUE TITLE
WZA API - Allegro One

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5137]
Witam

Chcę nadać paczkę, wysyłam prawidłowy JSON i dostaje taki komunikat zwrotny.
Nie mam pola ktore jest opisane w bledzie.
Mozna prosic o pomoc w rozwiazaniu zagadki ?

Array
(
    [id] => b5628b98-c52c-47f1-b1b6-bf1a8c2e1370
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => "Inne dane na etykiecie" not supporter for carrier
                    [details] => 
                    [path] => /sender
                    [userMessage] => Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika
                )

        )

)

**Comment by MartaNowaczyk** [comment]
Błąd jest związany z nadpisaniem etykiety. W tym wypadku trzeba pominąć wypełnianie etykiety (pole label: null). Niektórzy przewoźnicy nie pozwalają na to, żeby były inne dane nadawcy i inne dane na etykiecie.

**Comment by PawelPseudo** [comment]
dziękuję, pomogło.

BTW support na bardzo wysokim poziomie.

**Comment by PawelPseudo** [comment]
Udalo sie nadac paczke, etykieta wydrukowana (UUID: 20a9c367-dd97-49b7-84b8-54bf0b46e7f1).
Wycieczka do paczkomatu Allegro One i lipa.
I co teraz ? :)

![image](https://user-images.githubusercontent.com/73448782/140517559-437f17b2-155a-484c-8aba-e617ec5dbdd7.png)

![image](https://user-images.githubusercontent.com/73448782/140517601-4b1885b2-5e92-47b9-895c-f6be3e63f8e3.png)

**Comment by MartaNowaczyk** [comment]
Chętnie bym pomogła, ale to już temat poza API. Podsyłam link do [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). Tam powinieneś uzyskać pomoc. Miłego dnia :)
