### ISSUE TITLE
Feed produktowy

### ISSUE THREAD

**Issue by lukaszwiktorski** [allegro/allegro-api#5138]
Dzień dobry, 
jesteśmy oficjalnym sklepem nivea w strefie marek allegro. 
Producent pracuję nad przyciskiem przejścia ze strony producenta do naszych ofert na allegro. 
Czy istnieję integracja przez api która by pomogła w tym zagadnieniu. 
Firma zajmująca się zagadnieniem ze strony producenta przesłała nam konkretne wytyczne dotyczące przekazywanych informacji które mogę Państwu przekazać
Pozdrawiam
Łukasz Wiktorski
SMA Nivea

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, nie posiadamy dedykowanej integracji dla takiej funkcjonalności, ale jeśli dobrze zrozumiałem potrzebę, to wystarczy, że link, który znajduje się pod przyciskiem, będzie kierować do https://allegro.pl/uzytkownik/{login}, gdzie {login} to Państwa login na Allegro.
