### ISSUE TITLE
The VAT rate "23%" is not supported for chosen category 121808

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#5139]
Dzień dobry. Notuję zwiększoną ilość takich oto błędów jak w tytule, kategorie różne.

**Comment by PrzemyslawLukanowski** [comment]
Dziekuję za informację. Problem nie powinien już występować - jeśli mimo wszystko cały czas otrzymujesz błędy, podaj proszę przykładowe trace-id.

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że komunikaty błędu powróciły, weryfikuję sprawę.

**Comment by hahyes** [comment]
Podpinam się, problem wciąż występuje.

**Comment by KJtTGHAK** [comment]
Problem nadal występuje:
The VAT rate \"23%\" is not supported for chosen category 257701.

Zarówno poprzez Rest API jak formularz na stronie.

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam, problem występuje - wrócę z odpowiedzią, gdy uda się wyeliminować błąd.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować, dziękuję za wszystkie zgłoszenia.

**Comment by KJtTGHAK** [comment]
tak działa
