### ISSUE TITLE
ZAPYTANIE O FILTRY

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#514]
Mam tak zdefiniowane filtry:
         $filter['filterId'] = 'userRole';
         $filter['filterValueId'] = array('seller');    

         $filter2['filterId'] = 'shipmentId';
         $filter2['filterValueId'] =array(11);

         $filter3['filterId'] = 'shipmentId';
         $filter3['filterValueId'] = array(20006);

         $filter4['filterId'] = 'createTime';
         $filter4['filterValueRange']['rangeValueMax']=time();
         $filter4['filterValueRange']['rangeValueMin']=time()-5000;
czyli request: 
array(2) { ["sessionId"]=> string(52) "228025a6c3155461ba37fd8858771ead6908ba420bcc68//00_1" ["filterOptions"]=> array(4) { 
  [0]=> array(2) { ["filterId"]=> string(8) "userRole" 
                         ["filterValueId"]=> array(1) { [0]=> string(6) "seller" } }
  [1]=> array(2) { ["filterId"]=> string(10) "shipmentId" 
                           ["filterValueId"]=> array(1) { [0]=> int(11) } } 
  [2]=> array(2) { ["filterId"]=> string(10) "shipmentId" 
                         ["filterValueId"]=> array(1) { [0]=> int(20006) } } 
  [3]=> array(2) { ["filterId"]=> string(10) "createTime" 
                         [ "filterValueRange"]=> array(2) { ["rangeValueMax"]=> int(1534781246)
                                                                            ["rangeValueMin"]=> int(1534776246) 
} } } }
WYWOŁANIE:
 $request23['filterOptions'][]=$filter;
 $request23['filterOptions'][]=$filter2;
 $request23['filterOptions'][]=$filter3;
 $request23['filterOptions'][]=$filter4;
$soapClient->doGetPostBuyFormsIds($request23)

OTRZYMUJĘ OCZYWIŚCIE BŁĄD: SoapFault exception: [ERR_INCORRECT_FILTER_VALUE] Niepoprawna wartość dla filtra: Czas utworzenia FODiZa - 1534776246. 
To pewnie jest wadliwa konstrukcja samego filtra. Ale wzorowałem się na rzeczy którą już zrealizowałem przy okazji doGetItemsList a tam taka konstrukcja działa. Z responsa doGetPostBuyFormsIds wynika także że to powinno działać. Przemordowałem to kilkanaście razy i nadal nic. Proszę o pomoc

**Comment by MartaNowaczyk** [comment]
Podeślij proszę pliki XML z pełnym requestem i responsem.

**Comment by marcinja2** [comment]
nie ma czasu tworzyć xmlów a może nie znam się na tyle by szybko to wygenerować A response to ERROR a request jakuż wyżej napisałem array(2) { ["sessionId"]=> string(52) "228025a6c3155461ba37fd8858771ead6908ba420bcc68//00_1" ["filterOptions"]=> array(4) {
[0]=> array(2) { ["filterId"]=> string(8) "userRole"
["filterValueId"]=> array(1) { [0]=> string(6) "seller" } }
[1]=> array(2) { ["filterId"]=> string(10) "shipmentId"
["filterValueId"]=> array(1) { [0]=> int(11) } }
[2]=> array(2) { ["filterId"]=> string(10) "shipmentId"
["filterValueId"]=> array(1) { [0]=> int(20006) } }
[3]=> array(2) { ["filterId"]=> string(10) "createTime"
[ "filterValueRange"]=> array(2) { ["rangeValueMax"]=> int(1534781246)
["rangeValueMin"]=> int(1534776246)
} } } }

**Comment by imper86** [comment]
@marcinja2 nikt nie oczekuje, że będziesz coś tworzył, twój klient Soap ma wbudowane metody pobierania requestów i response'ów w formacie xml. Jeżeli używasz standardowego klienta w PHP to użyj na kliencie metody __getLastRequest() i __getLastResponse()

**Comment by marcinja2** [comment]
trochę modyfikowałem te filtry ale generalnie pod zadna opcja praktycznie nie działa oto dane o które prosiłeś:
REQUEST:<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:DoGetPostBuyFormsIdsRequest><ns1:sessionId>98e11f756ab505d25009795f774a4eba3b868fb5030b7b//02_1</ns1:sessionId><ns1:filterOptions><ns1:item><ns1:filterId>userRole</ns1:filterId><ns1:filterValueId><ns1:item>seller</ns1:item></ns1:filterValueId></ns1:item></ns1:filterOptions><ns1:resultSize>25</ns1:resultSize><ns1:resultOffset>0</ns1:resultOffset></ns1:DoGetPostBuyFormsIdsRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
RESPONSE:<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php"><SOAP-ENV:Body><ns1:doGetPostBuyFormsIdsResponse><ns1:formsCount>1624</ns1:formsCount><ns1:formsIds><ns1:item>890436223</ns1:item><ns1:item>890431143</ns1:item><ns1:item>890430846</ns1:item><ns1:item>890428085</ns1:item><ns1:item>890425989</ns1:item><ns1:item>890424445</ns1:item><ns1:item>890423709</ns1:item><ns1:item>890422462</ns1:item><ns1:item>890421900</ns1:item><ns1:item>890413977</ns1:item><ns1:item>890413380</ns1:item><ns1:item>890410521</ns1:item><ns1:item>890406959</ns1:item><ns1:item>890395952</ns1:item><ns1:item>890391506</ns1:item><ns1:item>890388968</ns1:item><ns1:item>890387052</ns1:item><ns1:item>890360859</ns1:item><ns1:item>890351779</ns1:item><ns1:item>890349020</ns1:item><ns1:item>890340895</ns1:item><ns1:item>890337359</ns1:item><ns1:item>890319042</ns1:item><ns1:item>890313338</ns1:item><ns1:item>890303010</ns1:item></ns1:formsIds><ns1:filtersList><ns1:item><ns1:filterId>userRole</ns1:filterId><ns1:filterName>Rola użytkownika w transakcji</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>combobox</ns1:filterControlType><ns1:filterDataType>string</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues><ns1:item><ns1:filterValueId>seller</ns1:filterValueId><ns1:filterValueName>Sprzedający</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>buyer</ns1:filterValueId><ns1:filterValueName>Kupujący</ns1:filterValueName></ns1:item></ns1:filterValues></ns1:item><ns1:item><ns1:filterId>search</ns1:filterId><ns1:filterName>Szukaj w tytule</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>textbox</ns1:filterControlType><ns1:filterDataType>string</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues/><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>itemId</ns1:filterId><ns1:filterName>Identyfikator oferty</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>textbox</ns1:filterControlType><ns1:filterDataType>long</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterArraySize>100</ns1:filterArraySize><ns1:filterValues/><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>userId</ns1:filterId><ns1:filterName>Identyfikator użytkownika</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>textbox</ns1:filterControlType><ns1:filterDataType>int</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues/><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd><ns1:relationExclude><ns1:item>userLogin</ns1:item></ns1:relationExclude></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>userLogin</ns1:filterId><ns1:filterName>Nazwa użytkownika</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>textbox</ns1:filterControlType><ns1:filterDataType>string</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues/><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd><ns1:relationExclude><ns1:item>userId</ns1:item></ns1:relationExclude></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>createTime</ns1:filterId><ns1:filterName>Czas utworzenia FODiZa</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>textbox</ns1:filterControlType><ns1:filterDataType>dateTime</ns1:filterDataType><ns1:filterIsRange>true</ns1:filterIsRange><ns1:filterValues/><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>shipmentId</ns1:filterId><ns1:filterName>Sposób dostawy</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>combobox</ns1:filterControlType><ns1:filterDataType>int</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues><ns1:item><ns1:filterValueId>1</ns1:filterValueId><ns1:filterValueName>Paczka pocztowa ekonomiczna</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>2</ns1:filterValueId><ns1:filterValueName>List ekonomiczny</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>3</ns1:filterValueId><ns1:filterValueName>Paczka pocztowa priorytetowa</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>4</ns1:filterValueId><ns1:filterValueName>List priorytetowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>5</ns1:filterValueId><ns1:filterValueName>Przesyłka pobraniowa / Paczka48 pobranie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>6</ns1:filterValueId><ns1:filterValueName>List polecony ekonomiczny</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>7</ns1:filterValueId><ns1:filterValueName>Przesyłka pobraniowa priorytetowa / Paczka24 pobranie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>8</ns1:filterValueId><ns1:filterValueName>List polecony priorytetowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>9</ns1:filterValueId><ns1:filterValueName>Przesyłka kurierska</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10</ns1:filterValueId><ns1:filterValueName>Odbiór osobisty</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>11</ns1:filterValueId><ns1:filterValueName>Przesyłka kurierska pobraniowa</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>12</ns1:filterValueId><ns1:filterValueName>Przesyłka elektroniczna (e-mail)</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>13</ns1:filterValueId><ns1:filterValueName>Odbiór osobisty po przedpłacie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>16</ns1:filterValueId><ns1:filterValueName>Allegro miniKurier24 InPost</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>17</ns1:filterValueId><ns1:filterValueName>Allegro Kurier24 InPost</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>18</ns1:filterValueId><ns1:filterValueName>Allegro Kurier24 InPost (za pobraniem)</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>19</ns1:filterValueId><ns1:filterValueName>Allegro miniKurier24 InPost (za pobraniem)</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>21</ns1:filterValueId><ns1:filterValueName>Pocztex Kurier48</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>22</ns1:filterValueId><ns1:filterValueName>Pocztex Kurier48 pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>24</ns1:filterValueId><ns1:filterValueName>Pocztex Kurier24</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>25</ns1:filterValueId><ns1:filterValueName>Pocztex Kurier24 pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>26</ns1:filterValueId><ns1:filterValueName>Allegro Pocztex Kurier 48</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>27</ns1:filterValueId><ns1:filterValueName>Allegro Pocztex Kurier 48 pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>28</ns1:filterValueId><ns1:filterValueName>Allegro Przesyłka polecona</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>30</ns1:filterValueId><ns1:filterValueName>Paczka24</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>31</ns1:filterValueId><ns1:filterValueName>Paczka48</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>33</ns1:filterValueId><ns1:filterValueName>Kurier InPost</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>34</ns1:filterValueId><ns1:filterValueName>Kurier InPost (za pobraniem)</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>73</ns1:filterValueId><ns1:filterValueName>Kurier UPS pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>74</ns1:filterValueId><ns1:filterValueName>Kurier UPS</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>75</ns1:filterValueId><ns1:filterValueName>Kurier GLS pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>76</ns1:filterValueId><ns1:filterValueName>Kurier GLS</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>77</ns1:filterValueId><ns1:filterValueName>Kurier DHL pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>78</ns1:filterValueId><ns1:filterValueName>Kurier DHL</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>79</ns1:filterValueId><ns1:filterValueName>Kurier DPD pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>80</ns1:filterValueId><ns1:filterValueName>Kurier DPD</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>81</ns1:filterValueId><ns1:filterValueName>Kurier FedEx pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>82</ns1:filterValueId><ns1:filterValueName>Kurier FedEx</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>83</ns1:filterValueId><ns1:filterValueName>Kurier Raben pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>84</ns1:filterValueId><ns1:filterValueName>Kurier Raben</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>85</ns1:filterValueId><ns1:filterValueName>Kurier Rhenus pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>86</ns1:filterValueId><ns1:filterValueName>Kurier Rhenus</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>98</ns1:filterValueId><ns1:filterValueName>Kurier wieczór</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>99</ns1:filterValueId><ns1:filterValueName>Kurier wieczór pobraniowy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>120</ns1:filterValueId><ns1:filterValueName>Niemcy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>122</ns1:filterValueId><ns1:filterValueName>Wielka Brytania</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>124</ns1:filterValueId><ns1:filterValueName>Czechy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>126</ns1:filterValueId><ns1:filterValueName>Irlandia</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>128</ns1:filterValueId><ns1:filterValueName>Rosja</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>130</ns1:filterValueId><ns1:filterValueName>Słowacja</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>132</ns1:filterValueId><ns1:filterValueName>Szwecja</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>134</ns1:filterValueId><ns1:filterValueName>Holandia</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>136</ns1:filterValueId><ns1:filterValueName>Litwa</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>138</ns1:filterValueId><ns1:filterValueName>Białoruś</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>140</ns1:filterValueId><ns1:filterValueName>Norwegia</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>142</ns1:filterValueId><ns1:filterValueName>Ukraina</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>144</ns1:filterValueId><ns1:filterValueName>Włochy</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>146</ns1:filterValueId><ns1:filterValueName>Francja</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>148</ns1:filterValueId><ns1:filterValueName>Belgia</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>150</ns1:filterValueId><ns1:filterValueName>Dania</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>152</ns1:filterValueId><ns1:filterValueName>Hiszpania</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>154</ns1:filterValueId><ns1:filterValueName>Austria</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10006</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - PACZKA W RUCHu</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10007</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Allegro Paczka w RUCHu</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10011</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - UPS Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10012</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Allegro UPS Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10022</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Paczkomaty 24/7</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10023</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Allegro Paczkomaty 24/7 InPost</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10060</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Paczka24 Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10061</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Paczka48 Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>10062</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie po przedpłacie - Allegro Poczta Polska Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20006</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - PACZKA W RUCHu</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20007</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Allegro Paczka w RUCHu pobranie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20011</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - UPS Odbiór w Punkcie pobranie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20012</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Allegro UPS Odbiór w Punkcie pobranie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20022</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Paczkomaty 24/7</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20023</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Allegro Paczkomaty 24/7 InPost</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20060</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Paczka24 Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20061</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Paczka48 Odbiór w Punkcie</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>20062</ns1:filterValueId><ns1:filterValueName>Odbiór w punkcie - Allegro Poczta Polska Odbiór w Punkcie pobranie</ns1:filterValueName></ns1:item></ns1:filterValues><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>packageInfo</ns1:filterId><ns1:filterName>Informacja o przesyłce</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>combobox</ns1:filterControlType><ns1:filterDataType>string</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues><ns1:item><ns1:filterValueId>added</ns1:filterValueId><ns1:filterValueName>Dodana</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>notAdded</ns1:filterValueId><ns1:filterValueName>Niedodana</ns1:filterValueName></ns1:item></ns1:filterValues><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item><ns1:item><ns1:filterId>paymentStatus</ns1:filterId><ns1:filterName>Status płatności PayU</ns1:filterName><ns1:filterType>country</ns1:filterType><ns1:filterControlType>combobox</ns1:filterControlType><ns1:filterDataType>string</ns1:filterDataType><ns1:filterIsRange>false</ns1:filterIsRange><ns1:filterValues><ns1:item><ns1:filterValueId>started</ns1:filterValueId><ns1:filterValueName>Rozpoczęta</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>finished</ns1:filterValueId><ns1:filterValueName>Zakończona</ns1:filterValueName></ns1:item><ns1:item><ns1:filterValueId>cancelled</ns1:filterValueId><ns1:filterValueName>Anulowana</ns1:filterValueName></ns1:item></ns1:filterValues><ns1:filterRelations><ns1:relationAnd><ns1:item>userRole</ns1:item></ns1:relationAnd></ns1:filterRelations></ns1:item></ns1:filtersList></ns1:doGetPostBuyFormsIdsResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

**Comment by marcinja2** [comment]
dobra poniekąd zapanowałem nad tym przestawiony był nawias. Walczyłem cały dzień żeby się upewnic ze gdzieś jeszcze nie popełniłem błędu. Pytanie dodatkowe czy można podwoić filtr shipmentId tj, dla dwóch wartości chodzi mi o pobrania DPD (value 11) i ruch (value 20006) zwracane w jednym responsie

**Comment by MartaNowaczyk** [comment]
shipmentId jest typu combobox, czyli obsluguje tylko jedną wybraną wartość. Ta informacja jest w responsie w polu filterControlType.
