### ISSUE TITLE
Problem z /parcel-management/parcel-create-commands

### ISSUE THREAD

**Issue by mpakier** [allegro/allegro-api#5141]
Wysyłam komendę PUT /parcel-management/parcel-create-commands/ef1d098f-6c44-4eb6-b709-e96855da7cdf

i dostaję odpowiedź BAD_REQUEST "JSON parse error" "Nieprawidłowa treść żądania JSON"

Mogę przekazać dokładną treść zapytania jeśli po CommandId jest niewidoczna.

**Comment by MartaNowaczyk** [comment]
Przekazujesz pustą tablicę:
 “additionalServices”:
 {
     “options”:[]
 }
 
 Przekaż odpowiednie wartości, a jeśli to niemożliwe, nie przekazuj usług dodatkowych w zapytaniu.

**Comment by mpakier** [comment]
Tak ale bez additionalServices też nie działa.

/parcel-management/parcel-create-commands/e869e402-fc08-4d5f-8f4d-224f336552b6

**Comment by MartaNowaczyk** [comment]
Jeszcze widzę to: "items" to tablica obiektów - brakuje ci [ ].
