### ISSUE TITLE
Problem with Lengow integration

### ISSUE THREAD

**Issue by supporto1spaziolusso** [allegro/allegro-api#5142]
Hi,
as written a few days ago to the Allegro team we have an error on all the products we try to send from Lengow to Allegro PL, the system returns this:

**1_ValidationError.MethodArgumentNotValidException - Collection contains null or empty elements. Collection contains null or empty elements.**

**1_VALIDATION_ERROR - Invalid HTML subset Invalid HTML subset**

Could you help us to understand what it can be due to, please?

Thanks. Gretings.
SpazioLusso team

**Comment by PrzemyslawLukanowski** [comment]
Hello,

1. This error means that the empty value was provided in a certain field in the parameters section, so please make sure that you sent all of the values.
2. This means that you used HTML tags incorrectly. Check our guide in which we described which HTML tags can be used. 

If you still have some issues, please open a ticket with Lengow and ask them to send us logs connected with these error messages - it will be much easier for us to indicate which fields specifically are problematic.
