### ISSUE TITLE
Can't create product offers

### ISSUE THREAD

**Issue by alejandroferrercecotec** [allegro/allegro-api#5143]
Hello to all,

We are trying to create offers associated with an existing product by EAN but we have some errors. Maybe you can explain how we must do it.

This is what are we using: https://developer.allegro.pl/en/documentation/#operation/createProductOffers with header application/vnd.allegro.beta.v3+json and this content:

```
{
  "productSet": [
    {
      "product": {
        "id": "8435484040709"
      }
    }
  ],
  "sellingMode": {
    "price": {
      "amount": 373.76,
      "currency": "PLN"
    }
  },
  "stock": {
    "available": 300
  },
  "publication": {
    "status": "ACTIVE"
  }
}
```

I hope your answer.

Many thanks for your help.

**Comment by Lukasz-Zurek** [comment]
Hello. I will verify your case and I will be back with an answer.

**Comment by Lukasz-Zurek** [comment]
@alejandroferrercecotec I have checked it and as I see - 8435484040709 is a "Manufacturer Code". The correct EAN is: 8435484042581. But if our data seems to be incorrect, please contact us via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by alejandroferrercecotec** [comment]
Both EAN (8435484040709 and  8435484042581) are correct. 
I attach a link to anyone:
-  [8435484040709](https://www.storececotec.com/es/envasadoras-al-vacio/214-sealvac-steel.html)
-  [8435484042581](https://www.storececotec.com/es/envasadoras-al-vacio/980-sealvac-140-steelcut.html)

**Comment by Lukasz-Zurek** [comment]
We do have only a product with EAN: 8435484042581 & Manufacturer Code: 8435484040709 in our product database. So we do not have a product with EAN: 8435484040709, this is why we return an error with an incorrect EAN in your request. But still this error it is not obvious so as I want to help you in this case - I will verify and give you some more information. Please be patient.

**Comment by Lukasz-Zurek** [comment]
@alejandroferrercecotec I have consulted it with another department and as I have already written earlier - we do not have a product with EAN: 8435484040709 in our product database. It is a Manufacturer Code for the product with EAN: 8435484042581.

You have two options to handle it:

1. You can create a product (with EAN: 8435484040709) using the method which you already use - [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). You have to create an active offer assigned to a product, which is not in our database. So you will have to provide in your request (in product object), product data which describe your product. You will find more information in [our tutorial](https://developer.allegro.pl/en/product_offers/).
2. You can create a product using [POST /sale/product-proposals](https://developer.allegro.pl/en/documentation/#operation/proposeSaleProduct) - more information [here](https://developer.allegro.pl/en/productization/#5-how-to-create-a-product). Then you can use [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) again. This time you should not receive an error.
