### ISSUE TITLE
Bład podczas aktualizacji oferty przypiętej do produktu: Temporary product was incorrectly assigned to offer. Delete it or assign other product. Temporary product was incorrectly assigned to offer. Delete it or assign other product.

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#5144]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,
podczas aktualizacji oferty otrzymujemy komunikat:
 Temporary product was incorrectly assigned to offer. Delete it or assign other product. Temporary product was incorrectly assigned to offer. Delete it or assign other product.

Z czym to się wiąże / z czego to wynika?
Parametry oferty wyglądają ok. Są takie same jak w produkcie.

Liczę na pilną odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy sytuację, wrócę z odpowiedzią, gdy uda się wyeliminować problem.

**Comment by PrzemyslawLukanowski** [comment]
Problem był po naszej stronie, błąd nie powinien już występować. Przepraszam za wszelkie niedogodności.

**Comment by manoos** [comment]
Wygląda na to że działa :) 
Dziękuję za szybką reakcję.
