### ISSUE TITLE
How to send EAN number in the product creation/updation API request

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5145]
Hello,

Could you please let me know, how can I send EAN number in the product creation request? Also, could you please let me know how to update the existing products with EAN number?

**Comment by PrzemyslawLukanowski** [comment]
1) It depends on which endpoint you are using. When it comes to:
- [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) - add EAN parameter and its value in the parameters array. Sample request can be found at the end of the "How to create a product" section in [our guide](https://developer.allegro.pl/en/productization/#5-how-to-create-a-product);
- [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) - add EAN parameter in the product.parameters section. [Here](https://developer.allegro.pl/en/product_offers/#provide-ean-as-a-parameter) you can find some samples.

2) You can send your suggestion using the link - https://allegro.pl/offer/product/report/{provide_ProductID_here}. The verification can take some time, so you can check the current status of your suggestion using [this site](https://allegro.pl/moje-allegro/sprzedaz/zmiany-w-katalogu/zgloszenia).
