### ISSUE TITLE
Witam miałbym pytanie dot. wiązania świeżo zaproponowanych nowych produktów

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5146]
Witam, 
mam pytanie w kwestii proponowania produktów, których nie ma na allegro:
Chciałbym otrzymane ID po zaproponowaniu POST'em sale/product-proposals 
od razu przypisać do konkretnych produktów PATCH'em sale/product-offers, które nie mają jeszcze numeru EAN.

Pytam ponieważ po zaproponowaniu trwa kilka dni zanim proponowane produkty są widoczne po sale/products?ean=
A nie chciałbym czegoś popsuć natychmiast je wiążąc z produktami.

Dziękuję

**Comment by Lukasz-Zurek** [comment]
Możesz utworzyć nowy produkt, a następnie przypisać go do ofert, korzystając z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers). Jednakże pamiętaj o tym, że [w części kategorii parametr EAN jest obowiązkowy, dla ofert ze stanem: nowy.](https://allegro.pl/dla-sprzedajacych/od-dzis-parametr-ean-jest-obowiazkowy-dla-produktow-ze-stanem-nowy-w-wybranych-kategoriach-XxjXjqR6lfA) Pozwalamy utworzyć Tobie produkt bez kodu EAN. Upewnij się jednak, że produkt próbujesz przypisać do adekwatnych ofert.

**Comment by Witold1983** [comment]
Ok, dziękuję
