### ISSUE TITLE
cannot launch 12 products on Allegro with Channel Advisor

### ISSUE THREAD

**Issue by csongorvarga** [allegro/allegro-api#5148]
Good morning,

I am contacting you regarding some product launch issues.

We have encountered an issue on Allegro which prevents us from launching 11 new products. The reason seems to be that Allegro are trying to match these products with similar (but not the same) products already present in the catalogue. Here is an example: GLU FK06 0064+FL with EAN 5707275126309 will not get listed because Allegro want us to match this product with one of our own existing product listings: GLU FK06 0061+FLA with EAN: 5702328325517.

Error from Allegro PL: “Provided EAN is not equal with any EAN assigned to the product. (id ProductFailedDataValidation, code VALIDATION_ERROR)”

I have attached a file with all the details for these 11 products. Would you be able to help us push these 11 items live, please? For your information: we are trying to launch these products through our integration partner's “Channel Advisor” platform; the error list is from Channel Advisor.

[Allegro catalog error_Solstro.xlsx](https://github.com/allegro/allegro-api/files/7502402/Allegro.catalog.error_Solstro.xlsx)

I look forward to your advice.

Thank you,

With Regards,
Csongor Varga

**Comment by Lukasz-Zurek** [comment]
This error validation information seems to be correct, but we will need some more informations and logs. If you still have some issues with these products, please contact Channel Advisor and ask them to send us logs connected with these error messages. We will verify it as soon as possible.

**Comment by csongorvarga** [comment]
Good afternoon,

Please leave this ticket open. I’ll get back to you with the requested information soon.

With Regards,
Csongor Varga
Marketplace Shop Specialist
E-mail: ***@***.******@***.***>
Mobile: +36 30 458 1426

VELUX Magyarország Kft.
Online Sales Organisation
1031 Budapest, Zsófia u. 1-3.

**Comment by Lukasz-Zurek** [comment]
Ok, thank you. I would like to clarify that you should ask Channel Advisor about logs and specific information. Then they will contact us and we will verify it.

**Comment by csongorvarga** [comment]
Good morning,

Thank you for your patience.

Let me attach an error log from Channel Advisor that contains only those SKUs we cannot launch on Allegro, with Channel Advisor. They show the same error in case of all 11 products concerned. I’ve received a more detailed error from Channel Advisor, please find it below for your attention:

CUSTOMER ERROR FROM CHANNEL: B[PRICEQUANTITY:https://api.allegro.pl/ca/products/a78d142e-6f0e-4f59-907d-80527f4eb75d/quantityprice/status]I[21228412/GLL FK06 1064+FL] >> Error from Allegro PL: Product Not Found.

I look forward to your advice.

With Regards,
Csongor Varga
Marketplace Shop Specialist
E-mail: ***@***.******@***.***>
Mobile: +36 30 458 1426

VELUX Magyarország Kft.
Online Sales Organisation
1031 Budapest, Zsófia u. 1-3.

**Comment by csongorvarga** [comment]
Sorry, missed this off earlier:

"BatchID": https://api.allegro.pl/ca/products/a78d142e-6f0e-4f59-907d-80527f4eb75d/quantityprice/status


With Regards,
Csongor Varga
Marketplace Shop Specialist
E-mail: ***@***.******@***.***>
Mobile: +36 30 458 1426

VELUX Magyarország Kft.
Online Sales Organisation
1031 Budapest, Zsófia u. 1-3.

From: Csongor Varga ***@***.***>
Sent: 2021. november 16., kedd 9:15
To: allegro/allegro-api ***@***.***>; allegro/allegro-api ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [allegro/allegro-api] cannot launch 12 products on Allegro with Channel Advisor (Issue #5148)

Good morning,

Thank you for your patience.

Let me attach an error log from Channel Advisor that contains only those SKUs we cannot launch on Allegro, with Channel Advisor. They show the same error in case of all 11 products concerned. I’ve received a more detailed error from Channel Advisor, please find it below for your attention:

CUSTOMER ERROR FROM CHANNEL: B[PRICEQUANTITY:https://api.allegro.pl/ca/products/a78d142e-6f0e-4f59-907d-80527f4eb75d/quantityprice/status]I[21228412/GLL FK06 1064+FL] >> Error from Allegro PL: Product Not Found.

I look forward to your advice.

With Regards,
Csongor Varga
Marketplace Shop Specialist
E-mail: ***@***.******@***.***>
Mobile: +36 30 458 1426

VELUX Magyarország Kft.
Online Sales Organisation
1031 Budapest, Zsófia u. 1-3.

**Comment by MartaNowaczyk** [comment]
As @Lukasz-Zurek wrote, errors should be reported to Channel Advisor. Then they will contact us and we will verify it. In that case, write to Channel Advisor to contact us about it. We have direct contact, which will allow for a faster solution to the problem.
