### ISSUE TITLE
Rest API - udostępnienie 

### ISSUE THREAD

**Issue by Einhell** [allegro/allegro-api#5149]
Na początku napiszę ze nie jestem programistą. Znam jedynie HTML i podstawy CSS. Chciałbym się dowiedzieć, w jaki sposób mogę uzyskać od Państwa API do integracji naszego panelu z panelem allegro. API przekażę następnie programistom którzy zajmą się integracją.

**Comment by kamxo412** [comment]
https://apps.developer.allegro.pl/

**Comment by Lukasz-Zurek** [comment]
@Einhell W pierwszej kolejności zapoznaj się proszę z [naszym poradnikiem](https://developer.allegro.pl/getting_started/), jak i całym [naszym portalem](https://developer.allegro.pl/about/), gdzie opisujemy dokładnie wszystkie udostępniane w API zasoby oraz dokumentację. 

Aby móc zarejestrować aplikację, konieczna jest rejestracja konta w Allegro.pl i włączenie [dwustopniowego logowania](https://allegro.pl/pomoc/dla-kupujacych/logowanie-i-haslo/czym-jest-dwustopniowe-logowanie-i-dlaczego-warto-z-niego-korzystac-dykqg9nMKSZ). 

Następnie - jak już zasugerował @kamxo412 -  konieczna jest rejestracja aplikacji na [tej stronie](https://apps.developer.allegro.pl). To pozwoli Wam na rozpoczęcie procesu [autoryzacji i uwierzytelniania](https://developer.allegro.pl/auth/).

Udostępniamy również środowisko testowe, w przypadku którego również można [zarejestrować aplikację](https://apps.developer.allegro.pl.allegrosandbox.pl), by testować zasoby API Allegro.

**Comment by Einhell** [comment]
> https://apps.developer.allegro.pl/

Otrzymałem api do konta Einhell_Polska. Nasze najnowsze konto to Einhell_PL. Czy mógłbym otrzymać api do Einhell_PL? Dodatkowo czy są Państwo w stanie wygenerować nam api do Sandboxa?

**Comment by kamxo412** [comment]
https://apps.developer.allegro.pl/ - pod tym adresem można skonfigurować i zwykłe API do Pana konta i do Sandboxa oddzielnie. Wystarczy wejść, kliknąć "Zarejestruj nową aplikację" i postępować zgodnie z instrukcjami wyświetlanymi na monitorze. Klucze API to Client ID i Secret Code, które pojawią się po skonfigurowaniu aplikacji przy jej tworzeniu.

**Comment by Lukasz-Zurek** [comment]
@Einhell Udostępniamy możliwość zarejestrowania nowej aplikacji, jednakże czynności te należy przeprowadzić samodzielnie. 

W przypadku sandbox musisz skorzystać z [tej strony.](https://apps.developer.allegro.pl.allegrosandbox.pl) Oczywiście po zarejestrowaniu konta na środowisku testowym.

**Comment by Einhell** [comment]
> @Einhell Udostępniamy możliwość zarejestrowania nowej aplikacji, jednakże czynności te należy przeprowadzić samodzielnie.
> 
> W przypadku sandbox musisz skorzystać z [tej strony.](https://apps.developer.allegro.pl.allegrosandbox.pl) Oczywiście po zarejestrowaniu konta na środowisku testowym.

@Lukasz-Zurek
Aplikacja zarejestrowana, token wygenerowany, przykladowe zapytanie listujace katalogi - dziala.
Ale jak juz probujemy uzyc jakiegokolwiek innego zapytania to sa bledy.
W przykladowym /sale/offers mamy cos takiego:
{
    "errors": [
        {
            "code": "AccessDenied",
            "message": "Access is denied",
            "details": null,
            "path": null,
            "userMessage": "Access denied. Contact the author of the application."
        }
    ]
}

Uprzedzam pytanie - podczas generowania tokena nie specyfikowalismy scope'ow - czyli zgodnie z ktorastam strona w dokumentacji - powinnismy miec full scope.
Header accept: application/vnd.allegro.public.v1+json tez jest.

**Comment by Lukasz-Zurek** [comment]
@Einhell Upewnij się, że nie korzystasz z autoryzacji typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. W naszej [dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by RaushanSingh123** [comment]
Hi Lukasz,
We are using device flow but getting a below-attached error message.
Please help me out.


![unauthorized](https://user-images.githubusercontent.com/94611079/142403221-ff41f66c-5490-44b5-a864-d5c5540fd1f3.PNG)
![device flow](https://user-images.githubusercontent.com/94611079/142403676-5e27216f-78b5-47b0-adf6-accccde7edbe.PNG)

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 Please, look into [our tutorial](https://developer.allegro.pl/en/auth/#device-flow-user-authorization) about device flow. In step 1,2 you will see  - as a parameter you should use client_ID, encode client_ID and client_secret and as 'Content-Type" use application/x-www-form-urlencoded.

**Comment by RaushanSingh123** [comment]
Hi @MaciejFrackowiak 

Please see the attached screenshot I try with this also but the same error
![param](https://user-images.githubusercontent.com/94611079/142591685-e4c28576-9022-4fa1-aa90-841fc3d46286.PNG)
![Content type](https://user-images.githubusercontent.com/94611079/142591737-9696e08e-2085-483e-89a4-83293011b057.PNG)
.

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 Content-Type: application/x-www-form-urlencoded is OK, also params Client_ID is OK, you should not add params Client_secret. As I wrote before - you have to encode Client_ID and Client_secret with Base64 and remember to add ":" between the values. Token section should like on my screenshot:

![obraz](https://user-images.githubusercontent.com/53566763/142632817-a45babf3-bd3f-4b80-8f62-2ff220e55e8e.png)

**Comment by RaushanSingh123** [comment]
@MaciejFrackowiak 

I try the same but still not solved

ClientID:Secret-> 8898fe4410684fcbbce2cee9605700e4:MDS6htHL5nyDuitO4VSAniyuweNeOialoKG5smfxBKmRZcIRI20YGopgR92AnyMn

Base64 encode-> Basic ODg5OGZlNDQxMDY4NGZjYmJjZTJjZWU5NjA1NzAwZTQ6TURTNmh0SEw1bnlEdWl0TzRWU0FuaXl1d2VOZU9pYWxvS0c1c21meEJLbVJaY0lSSTIwWUdvcGdSOTJBbnlNbg==

![auth](https://user-images.githubusercontent.com/94611079/142836090-934443d8-8739-4878-aff5-55d9901c4532.PNG)
.

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 You are using values from the production environment (Client_ID and Client_secret), but you are trying to authorize on Sandbox environment - it cannot work. So you should take values from [this site](https://apps.developer.allegro.pl.allegrosandbox.pl/) if you want use Sandbox authorization.

**Comment by RaushanSingh123** [comment]
@MaciejFrackowiak 
This part has been resolved. 
But I am getting 400 errors when trying to call and get the access token please see the attachment

![with device code request](https://user-images.githubusercontent.com/94611079/143222185-af85370c-b125-49e4-a1de-3beb0f4d7573.PN
![400 error](https://user-images.githubusercontent.com/94611079/143222271-6db8f50a-184a-4564-9b22-fcb6d705225b.PNG)
G)

**Comment by RaushanSingh123** [comment]
@MaciejFrackowiak
![with device code request](https://user-images.githubusercontent.com/94611079/143222478-27088519-96bc-47b0-ad4a-be4424023e81.PNG)

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 Device code value should be without {}

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 "checkoutForm_id" is an ID of a single order - to get a list of all orders on your account just use [GET /order/checkout-forms](https://developer.allegro.pl/en/documentation/#operation/getListOfOrdersUsingGET).

Please, look also into [our tutorial](https://developer.allegro.pl/en/orders/) where we described how to process orders.

**Comment by RaushanSingh123** [comment]
@MaciejFrackowiak 

What else do we need to pass apart from content Type any Authorization like basic or Bearer for this API
![orders checkout forms](https://user-images.githubusercontent.com/94611079/144857051-8ba2386a-03e1-43b5-94cb-d2daeb717a4d.PNG)

**Comment by MaciejFrackowiak** [comment]
@RaushanSingh123 You need a accept and content-type headers with value: "application/vnd.allegro.public.v1+json" and bearer-token-for-user.
