### ISSUE TITLE
Błąd generowania etykiety mimo poprawnych ustawień "Allegro returned error: Zamówienie nie należy do sprzedawcy."

### ISSUE THREAD

**Issue by kamxo412** [allegro/allegro-api#5150]
Witam, tak jak w temacie - nie możemy wygenerować etykiety w naszym systemie, mimo, iż wszystko zostało połączone i autoryzowane. Komunikat błędu to - Allegro returned error: Zamówienie nie należy do sprzedawcy. Sprawdzaliśmy kilka razy, czy na pewno ustawienia są dobrze przypisane, oraz autoryzowane jest właściwe konto. mimo to cały czas pojawia się ten sam błąd. Oczywiście integracja jest podpięta przez wersję produkcyjną.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę przykładowy request i response w formie curl, wraz z trace-id przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5150.
