### ISSUE TITLE
Numer katalogowy części2 - paramId 249034

### ISSUE THREAD

**Issue by radoslawkoziol** [allegro/allegro-api#5152]
Czy ktoś może wyjaśnić o co chodzi z tą cechą? Czemu się pojawiła, czemu zniknął stary numer katalogowy? I czemu mamy "2" w nazwie?

Nasi klienci mieli pomapowane swoje cechy ze starym numerem i teraz przestało to działać. To błąd, czy mamy zaakceptować zmiany?

**Comment by PrzemyslawLukanowski** [comment]
To tymczasowy błąd, przepraszam za niedogodności. Jeszcze dziś nazwy parametrów powinny z powrotem otrzymać nazwę bez "2" na końcu.

**Comment by PrzemyslawLukanowski** [comment]
Przywróciliśmy poprzednią nazwę, ID pozostaje 249034.

**Comment by ArturBakAxl** [comment]
są 2 "Numer katalogowy części" z paramid = 215858 i paramid = 249034
W których kategoriach one występują?

**Comment by PrzemyslawLukanowski** [comment]
@ArturBakAxl Parametr z ID 249034 wystąpi w poniższych siedmiu kategoriach:

- Motoryzacja > Części samochodowe > Układ hamulcowy > Hamulce tarczowe > Zestawy (tarcze, klocki, zaciski) (**250407**)
- Motoryzacja > Części samochodowe > Układ hamulcowy > Hamulce bębnowe > Zestawy (bębny, szczęki, cylinderki) (**250426**)
- Motoryzacja > Części samochodowe > Części karoserii > Zestawy części blacharskich (**254718**)
- Motoryzacja > Części samochodowe > Oświetlenie > Lampy przednie i elementy > Lampy przednie (**255099**)
- Motoryzacja > Części samochodowe > Oświetlenie > Lampy tylne i elementy > Lampy tylne (**255119**)
- Motoryzacja > Części samochodowe > Układ wydechowy > Tłumiki > Komplety (**255661**)
- Motoryzacja > Części samochodowe > Filtry > Zestawy filtrów (**49242**)

Parametr z ID 215858 wystąpi w pozostałych 1247 kategoriach.
