### ISSUE TITLE
Wiele kodów kreskowych do jednej oferty.

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#5153]
Struktura pliku JSON przewiduje tablicę dla pola values parametru oferty. Czyli w przypadku kodów EAN/GTIN oznaczałoby to możliwość przypisania do oferty wielu kodów. Np. stary i nowy kod kreskowy produktu. Na ile to jest realna możliwość i przygotowywać program na taką sytuację. Np. przez stronę Allegro nie widzę możliwości dodania wielu kodów. Czy przypadku kodu kreskowego to będzie zawsze jednoelementowa tablica, ewentualnie pusta.

P.S. Rozumiem, że id parametru jest unikalny w tablicy parametrów. Dla kodu EAN/GTIN będzie to 225693.

**Comment by PrzemyslawLukanowski** [comment]
Informację o tym, czy w parametrze możesz przekazać więcej niż jedną wartość, zwracamy w odpowiedzi dla [GET /sale/categories/{categoriesId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) w polu `restrictions.multipleChoices` przy danym parametrze. Wartość `true` oznacza, że możesz to zrobić.

> P.S. Rozumiem, że id parametru jest unikalny w tablicy parametrów. Dla kodu EAN/GTIN będzie to 225693

Tak, ID w sekcji parameters są unikalne, nie możesz przekazać dwa razy tego samego ID. Dla EAN jest to 225693.

**Comment by jmarek-pl** [comment]
To zastanawiam się, czy nie zgłosić błędu/wyjątku gdy oferta ma wiele kodów kreskowych.

**Comment by jmarek-pl** [comment]
Mam jeszcze pytanie co zrobić kiedy użytkownik skasuje kod kreskowy w moim programie, jak taką informację przekazać do Allegro. Eksperymentalnie doszedłem to kodu, w którym do tablicy parametrów przypisuję null. I to działa, nie kasuję tego parametru dla kodu kreskowego. Jak powinienem to robić?

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji powinieneś usunąć obiekt związany z danym parametrem z całej tablicy parametrów. Oczywiście jeśli parametr jest wymagany w danej kategorii, zwrócimy wtedy odpowiedni błąd.

**Comment by jmarek-pl** [comment]
Zrobiłem zgodnie z Pana sugestią, czyli usuwam z tablicy parametrów EAN i wysyłam nową tablicę bez tego parametru. No i mój program zaczął dziwnie działać. Czy jest możliwe, że przy usuwaniu parametrów są jakieś opóźnienia. Bo ja po zmianie pobieram aukcję. Na tej podstawie aktualizuję swoją bazę danych i robię ponownie testy czy wszystko się zgadza między moją tabelą a tabelą danych z Allegro. No i program ostrzega, że kody kreskowe między moją tabelą a tabelą z Allegro się różnią.

**Comment by PrzemyslawLukanowski** [comment]
Każda edycja oferty może zająć do godziny, jednak z reguły realizujemy je dużo szybciej. Trudno jest mi się odnieść do problemów w Pana programie, ponieważ nie wiem, w jaki dokładnie sposób funkcjonuje. Jeśli otrzymuje Pan błędy z naszego API, prośba w takim przypadku o przykładowe trace-id, zweryfikujemy wtedy sytuację.

**Comment by jmarek-pl** [comment]
Błędu z Allegro API nie ma. W takim razie po zmianie danych w Allegro nie mogę od razu dokonać kontrolnego odczytu bo Allegro może zwrócić mi stare dane. Jest to wykonywane niejako asynchronicznie.

**Comment by jmarek-pl** [comment]
Znalazłem błąd w swoim programie. Jednam można po wysłaniu zmian od razu wykonać odczyt z Allegro. Po usunięciu tego błędu wszystko działa OK.
