### ISSUE TITLE
Sposób na pobranie parametru "Kod Producenta"  z parametrów oferty. 

### ISSUE THREAD

**Issue by AdamDubiejko** [allegro/allegro-api#5154]
Próbuję uzyskać możliwość pobrania parametru aukcji zawartego w polu "Kod producenta".

Zawartość pola "external" w wielu przypadkach różni się od zawartości pola "kod producenta". 

W wyniku błędnego tworzenia produktów przez konkurencję bardzo wiele ofert po automatycznym połączeniu ma złe parametry we wskazanym polu. 

W jaki sposób uzyskać dostęp do pola "Kod producenta" ?

**Comment by Lukasz-Zurek** [comment]
Rozumiem, że Twoje oferty zostały przypisane do produktów z błędną wartością "Kod producenta". Uzyskanie dostępu do pierwotnej wartości parametru nie będzie możliwe.

Oczywiście jeśli trafiłeś na nieprawidłowe produkty, możesz je zgłosić poprzez formularz - https://allegro.pl/offer/product/report/{productId}.

**Comment by AdamDubiejko** [comment]
Dziękuję, za odpowiedź.

Czy istnieje możliwość zbiorczych zmian tych parametrów? 

Czy jako producent/SMA istnieje możliwość zbiorczego przesłania zestawień  EAN->Kod SKU lub masowej edycji utworzonych przez innych sprzedawców produktów dotyczących danego EAN? 

Problem polega na tym, że przy korzystaniu z już utworzonych produktów w tabelach cech wpisane są nieprawidłowe wartości. Szukamy sposobu na opracowanie workflow, aby uniknąć prezentacji nieprawidłowych cech w tabeli parametrów.

Na dzień dzisiejszy wystawiamy ofertę bez produktyzacji, niestety często później automatycznie zostaje przypisana do utworzonego przez innego sprzedawcę produktu posiadającego błędne dane. Przypisanie odbywa najprawdopodobniej się na podstawie wcześniej użytego błędnie SKU. 

Byłbym wdzięczny za pochylenie się nad tematem.

**Comment by Lukasz-Zurek** [comment]
Niestety nie ma możliwości zbiorczej zmiany tych parametrów. Jeśli natomiast chodzi o zestawienie produktów, w których należałoby poprawić parametry - możesz je przesłać poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Nasz serwis stara się na bieżąco reagować na tego typu sytuacje i poprawiać błędne wartości parametrów w produktach.
