### ISSUE TITLE
Przedłużanie tokena

### ISSUE THREAD

**Issue by BearimusPrime** [allegro/allegro-api#5155]
Witam czytających.
Otóż mam problem z przedłużeniem tokena, a generowanie go 2 razy dziennie poprostu nie wchodzi w rachubę.
Token 12 godzinny (access token) generuje się bez problemu, jest dostęp do wszystkich funkcji, zakładanie/sprawdzanie/zdejmowanie ofert działa - także ten etap integracji jest zakończony.
Podczas próby wykonania [przedłużenia](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena) wyskakuje błąd:
PHP Warning:  Undefined array key "code" in /home/allegroapi/przedluz.php on line 68
        <html>
        <body>
        <a href="https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=tu_jest_clientid_poprawne&redirect_uri=">Login to Allegro</a>
        </body>
        </html>

Na początku skryptu w zmiennych nie zmieniłem define('REDIRECT_URI', ''); bo nie używam przekierowania (chyba, że mam jakoś to użyć to będę w tym kierunku próbował iść).

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę przykładowy request i response w formacie cURL, w json. W tym celu skorzystaj z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5155.

**Comment by BearimusPrime** [comment]
Panie Lukaszu. Wysłałem co miałem wysłać, po kilku godzinach dostałem odpowiedź, że 'przekazane do innego działu' i sprawa umarła.
Zacznijmy od początku.
1 - zmienne które mam:
$clientid
$clientsecret
nie mam ustawionego zadnego redirecturl.

2 - Wykonanie skryptu php podanego w dokumentacji - zwraca mi tylko poprawny token 12 godzinny. 
czyli mam nastepna zmienna $token12h
Dalej nie wiem co to redirecturl i nie wiem czy to jest np. adres mojego konta allegro, adres mojej strony, czy jeszcze jakies inne przekierowanie i czy wogole tego potrzebuje do przedluzenia tokenu.

3 - Zeby przedluzyc/otrzymac ten 3 miesieczny token co musze dokladnie zrobic? Probowalem uzyc tego pliku php ale wyskakuje blad. Moglby Pan na podstawie posiadanych zmiennych ( $clientid,$clientsecret, $token12h) zlozyc mi zapytanie curl ktorym otrzymam ten wlasciwy dlugowieczny token?

**Comment by MaciejFrackowiak** [comment]
Niestety, Twoja wiadomość dotychczas do nas nie dotarła - proszę, odpowiedz na otrzymany email i raz jeszcze poproś o przekazanie wiadomości do nas.

**Comment by jmarek-pl** [comment]
Cytat z dokumentacji:
"Dzięki obsłudze tzw. odnawialnego czasu życia tokena, za każdym razem gdy używasz refresh token, w odpowiedzi otrzymasz nową parę - access token (ważny kolejne 12h ) oraz refresh token (ważny kolejne 3 miesiące)."
Według mnie nie ominiesz odświeżanie access tokena dwa razy na dobę. Operację są autoryzowane access tokenem ważnym 12 godz. Ja używam go do dostępu do ofert użytkownika.
