### ISSUE TITLE
Konto aktywacja sprzedaży

### ISSUE THREAD

**Issue by ptrocewicz** [allegro/allegro-api#5156]
Witam,
założyłem konto testowe (bestsoft_test),
utworzyłem aplikację,
niestety nie jest aktywna sprzedaż na tym koncie. 
Co powinienem zrobić aby mieć możliwość wystawiania ofert ?

**Comment by Lukasz-Zurek** [comment]
Aktywowałem Twoje konto testowe. Wybrałeś konto firmowe, dlatego w celu jego weryfikacji prześlij proszę dwa dowolne pliki poprzez zakładkę [Dane konta](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php).

**Comment by ptrocewicz** [comment]
ok, wysłałem pliki.

**Comment by Lukasz-Zurek** [comment]
@ptrocewicz Widzę, że Twoje konto firmowe jest już w pełni aktywne i możesz już z niego w pełni korzystać.

**Comment by ptrocewicz** [comment]
Przez formularz faktycznie mogę już wystawić ofertę,
natomiast przez api nadal mam komunikat:
{
    "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Client is not allowed for execute this command",
            "details": "AccessDeniedException",
            "path": "/sale/offers",
            "userMessage": "Client is not allowed for execute this command"
        }
    ]
}

**Comment by Lukasz-Zurek** [comment]
Najprawdopodobniej korzystasz z autoryzacji typu [client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika. W naszej dokumentacji znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow)).

**Comment by ptrocewicz** [comment]
Utworzyłem nową aplikację, z autoryzacją code wg dokumentacji.
Przy próbie rejestracji aplikacji dostaję komunikat (już po zalogowaniu do sandboxa)

Nie możemy wyświetlić strony
Numer błędu: 138d1b64aa7ca0f0

(numer błędu się zmienia).

adres do redirecta jest podany prawidłowy

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, czy w parametrze client_id nie przekazujesz na początku dodatkowej spacji dla wartości.

**Comment by ptrocewicz** [comment]
Faktycznie późna godzina i człowiek ślepy.
Dzięki wielkie.

**Comment by ptrocewicz** [comment]
Jeszcze jedno pytanie czy draft oferty utworzonej przez API może być uzupełniany przez formularz na stronie ?

**Comment by PrzemyslawLukanowski** [comment]
@ptrocewicz Tak, jak najbardziej jest to możliwe.
