### ISSUE TITLE
Shipping to Poland only is set by default. If you didn't include other countries in your delivery price lists, buyers will see the following message when they try to buy your items:

### ISSUE THREAD

**Issue by aswiniimpro** [allegro/allegro-api#5157]
Shipping to Poland only is set by default. If you didn't include other countries in your delivery price lists, buyers will see the following message when they try to buy your items:

If disabled other countries in delivery settings, I'm not able to re-enable the country for delivery settings. https://prnt.sc/1z9tgx5 - this is not shown.

How do we re-enable the country settings?

**Comment by PrzemyslawLukanowski** [comment]
I've answered the #4762 topic.
