### ISSUE TITLE
Pytanie o dodawanie i usuwanie ofert wielowariantowych typu colorPattern

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5158]
Witam,
Mam takie pytanie, umiem w miarę łączyć oferty po rozmiarze w ofertę wielowariantową.
Widzę, że w kategorii 18008 Pompony z mojego sklepu zostały automatycznie połączone wg. color/Pattern.
Chociaż w parametrach tej kategorii nie widzę aby była taka możliwość - atrybut 'Kolor' (451) ma: {"variantsAllowed":false,"variantsEqual":false}

Chciałbym dodać do nich kilka nowych ofert, nie wystawionych wcześniej i powiązać je wg. koloru.
Nie wiem jakie tak naprawdę warunki (oprócz {"variantsEqual":true}) muszą być spełnione aby te oferty zostały połączone.

Nie wiem, czy to wiązanie powstało automatycznie czy to ktoś od was ręcznie je połączył?

Dla oferty https://allegro.pl/oferta/-9378738707
wyciągnąłem lekko przerobione z /sale/offer-variants takie dane:

Oprócz ID oferty dla tych ofert dostaję również parametr colorPattern, podczas kiedy w przypadku rozmiaru dostaję tylko id oferty.
Nie wiem do czego jest to colorPattern, jak odpalam sale/offer-variants/50a6735d-8a89-48ab-8a07-6a824d8ab16f
dostaję błąd.

[variants] => Array
                (
                    [5870a43b-efe7-4974-a27b-ef24883070ef] => Array
                        (
                            [0] => Array
                                (
                                    [id] => 9379380968
                                    [colorPattern] => 50a6735d-8a89-48ab-8a07-6a824d8ab16f
                                )

                            [1] => Array
                                (
                                    [id] => 9379398246
                                    [colorPattern] => 21ee7d5b-ceb7-48d4-9786-6af06d61926a
                                )

                            [2] => Array
                                (
                                    [id] => 9379373946
                                    [colorPattern] => ee86a83c-167b-45f1-a610-4eba4df9c48e
                                )

                            [3] => Array
                                (
                                    [id] => 9379415597
                                    [colorPattern] => 7f59d787-b871-466f-9f83-b4cffa39dd67
                                )

                            [4] => Array
                                (
                                    [id] => 9378738707
                                    [colorPattern] => 7854245b-314e-4518-9ac6-18d0ccd27a53
                                )

                        )

                )

**Comment by PrzemyslawLukanowski** [comment]
> Widzę, że w kategorii 18008 Pompony z mojego sklepu zostały automatycznie połączone wg. color/Pattern.
> Chociaż w parametrach tej kategorii nie widzę aby była taka możliwość - atrybut 'Kolor' (451) ma: {"variantsAllowed":false,"variantsEqual":false}
> 

Parametr colorPattern (kolor/wzór) nie jest powiązany z parametrem Kolor w danej kategorii, to osobny parametr, który wykorzystujemy wyłącznie przy tworzeniu ofert wielowariantowych. Informację o tym, czy w danej kategorii możesz utworzyć ofertę wielowariantową z wykorzystaniem parametru kolor/wzór, znajdziesz w odpowiedzi [GET /sale/categories/{cagegoryID}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) w polu `‘variantsByColorPatternAllowed’` w obiekcie `‘options’`.

> Chciałbym dodać do nich kilka nowych ofert, nie wystawionych wcześniej i powiązać je wg. koloru.
> Nie wiem jakie tak naprawdę warunki (oprócz {"variantsEqual":true}) muszą być spełnione aby te oferty zostały połączone.

Informację o tym, jak edytować ofertę wielowariantową, znajdziesz w [naszym poradniku](https://developer.allegro.pl/multi_variant_offers/#edytuj-ofert%c4%99-wielowariantow%c4%85). Jak wspomniałem wyżej, aby połączyć oferty za pomocą atrybutu `colorPattern`, dana kategoria musi także wspierać łączenie tego typu.

> Nie wiem, czy to wiązanie powstało automatycznie czy to ktoś od was ręcznie je połączył?

Kategoria, w której zostały wystawione oferty oraz wartości dla `colorPattern `(wygenerowane automatycznie), wskazują, że to my automatycznie połączyliśmy oferty. [Tutaj ](https://allegro.pl/regulamin/zalacznik/2) znajdziesz pełną listę kategorii, w których automatycznie tworzymy oferty wielowariantowe.

> Oprócz ID oferty dla tych ofert dostaję również parametr colorPattern, podczas kiedy w przypadku rozmiaru dostaję tylko id oferty.
> Nie wiem do czego jest to colorPattern.

Parametr `colorPattern `wskazuje na to, że oferty zostały/mają zostać połączone w podziałem na różne warianty kolor/wzór. Jeśli chciałbyś utworzyć taką ofertę wielowariantową, w której skład wejdą np. trzy różne warianty kolorystyczne, to każda z tych ofert musi posiadać inne zdjęcie główne i dla każdej z nich musisz przekazać własną, unikalną wartość w parametrze `"colorPattern"`. Aby lepiej zrozumieć ten mechanizm, możesz spojrzeć na przykład z [naszego poradnika](https://developer.allegro.pl/multi_variant_offers/#utw%c3%b3rz-ofert%c4%99-wielowariantow%c4%85).

> Nie wiem do czego jest to colorPattern, jak odpalam sale/offer-variants/50a6735d-8a89-48ab-8a07-6a824d8ab16f
> dostaję błąd.

W zaprezentowanym przykładzie nie ma błędu - rozumiem, że pobierasz dane oferty wielowariantowej za pomocą metody GET. W odpowiedzi zwróciliśmy informacje o ofertach, które wchodzą w jej skład.

**Comment by Witold1983** [comment]
Dobrze, dziękuję.
