### ISSUE TITLE
Pobranie commandId

### ISSUE THREAD

**Issue by therodzyn** [allegro/allegro-api#516]
Witam,
Przed wdrożeniem synchronizatora z Allegro u klienta chciałbym pobrać wystawione do tej pory aukcje. 
Jednak ani zasób z listingiem ofert _/offers/listing_ ani zasób ze szczegółami konkretnej oferty _/sale/offers/{offerId}_ nie zwraca informacji o **commandId**.
Natomiast **commandId** jest niezbędny do chociażby późniejszej zmiany ceny oferty za pomocą zasobu _/offers/{offerId}/change-price-commands/{commandId}_.
Czy jest jakiś sposób aby pobrać **commandId** oferty?
Bez tego nie da się wykonać takiego "pełnego importu" dotychczasowych aukcji.
Pozdrawiam
JR

**Comment by AniaMalinowska** [comment]
CommandId w zosobie /offers/{offerId}/change-price-commands/{commandId} to numer, który wpisuje sam sprzedawca. Możesz go uzyskać za pomocą jakiejś dedykowanej aplikacji do generowania numerów w formacie UUID. Numer ten służy do śledzenia danego zadania, aby np. w przypadku publikacji oferty przy pomocy tego numeru sprawdzić status zadania - czy zostało wykonane (czy zakończyło się sukcesem).
