### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Liketodev3** [allegro/allegro-api#5160]
Hi. How to get product code end VAT rate from order response? Thanks

**Comment by MartaNowaczyk** [comment]
This information is not included in the order responses.

Read about tax rates in [our news](https://developer.allegro.pl/en/news/#vat-2021-preview).

You will get the product id when retrieving the offer details using [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) or [GET sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)

**Comment by Liketodev3** [comment]
thank you
