### ISSUE TITLE
Skąd wiedzieć czy ofertę można edytować (po ponad 30 dniach od ostatniej sprzedaży)

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5161]
Witam,
Tak jak w temacie, kiedy listuję GET'em sale/offers/8441810443
Nie widzę informacji czy mogę zmienić w niej np. tytuł i cene. A dostaję tą informację kiedy próbuję je edytować.
Chciałbym to wiedzieć, po wspomnianym GET'cie żeby nie musieć wysyłać requesta ze zmienionymi parametrami.
Wolałbym aby moja aplikacja reagowała na stosowny parametr/flagę a nie parsowała zwracany komunikat o błędzie.

**Comment by MaciejFrackowiak** [comment]
Jeżeli w ofercie miała miejsce jakakolwiek sprzedaż to nie możesz zmienić już jej tytułu - szereg wytycznych znajdziesz w artykule [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#kup-teraz).

**Comment by Witold1983** [comment]
Tak ja to wiem, ale chciałbym aby moja aplikacja też umiała to rozpoznać. Problem w tym, że po 30 dniach od sprzedaży znika parametr 'sold' w zwracanych GET'em informacjach o ofercie

**Comment by MaciejFrackowiak** [comment]
Obsługa takich informacji pozostaje już w gestii użytkownika, w naszym API ich nie zwracamy.

**Comment by Witold1983** [comment]
Ok, rozumiem.
