### ISSUE TITLE
Pytanie o łączenie ofert po colorPattern

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5163]
Witam, mam pytanie jak w temacie.
W poradniku czytam o łączeniu ofert po rozmiarze (attr.id 54).
Natomiast nie widzę nigdzie jak łączyć po colorPattern.

Chciałbym połączyć oferty po collorPattern własną aplikacją.

Dla zapytania GET'em:
sale/offer-variants/5870a43b-efe7-4974-a27b-ef24883070ef
Otrzymuję 8 ofert, mniej więcej takich:

    [id] => 5870a43b-efe7-4974-a27b-ef24883070ef
    [offers] => Array
        (
            [0] => Array
                (
                    [id] => 11437354164
                    [colorPattern] => 7ae66c3a-2242-43d9-af95-ce250286114d
                )
            (...)
Kiedy GETem odpytuję podając otrzymany id colorPattern:
sale/offer-variants/7ae66c3a-2242-43d9-af95-ce250286114d

dostaję błąd:
[errors] => Array
        (
            [0] => Array
                (
                    [code] => NOT_FOUND
                    [message] => An error has occurred
                    [details] => 
                    [path] => /sale/offer-variants/7ae66c3a-2242-43d9-af95-ce250286114d
                    [userMessage] => Not found
                )

        )

)

Nie wiem za co odpowiada id dla colorPattern, bo dla każdej oferty id jest inne.
Nie wiem czy należy generować je samemu.
Nie mam pojęcia jak to ugryźć i z czym to się je ;-)

**Comment by Witold1983** [comment]
Looknąłem na wcześniejszy issue.
Mniejwięcej jarzę o co chodzi.
Byłoby fajnie aby to było podane w poradniku.
https://github.com/allegro/allegro-api/issues/1285

**Comment by MartaNowaczyk** [comment]
W naszym [poradniku](https://developer.allegro.pl/multi_variant_offers/#utw%c3%b3rz-ofert%c4%99-wielowariantow%c4%85) opisaliśmy jak łączyć po colorPattern. Jeśli mimo to masz jeszcze pytania, pisz śmiało.

**Comment by Witold1983** [comment]
Dziękuję, 
rzeczywiście jest to w poradniku wyjaśnione. 
Za szybko przewinąłem stronę :-)
