### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by tsserg1** [allegro/allegro-api#5164]
Cześć!
Korzystając z Postmana, przez który próbowałem przejść
https://developer.allegro.pl/pl/auth/#device-flow-user-autoryzacja
operacja.
Ale mam taki wynik, jak
{
    "error": "unauthorized_client",
    "error_description": "Klient nie ma przyznania device_code."
}
Więc jak i gdzie mogę uzyskać grant device_code?

**Comment by MartaNowaczyk** [comment]
Sprawdź czy podczas rejestracji aplikacji wybrałeś typ DEVICE. Sprawdź to: [dla SANDBOX](allegro.pl.allegrosandbox.pl), [dla ALLEGRO](https://apps.developer.allegro.pl/). Jeśli typ jest inny musisz zarejestrować nową, wybierając typ DEVICE.
