### ISSUE TITLE
Token Refresh:  invalid_grant /  Invalid refresh token

### ISSUE THREAD

**Issue by mickser** [allegro/allegro-api#5165]
We are using DEVICE Auth for about a year, now we are getting: 

         [0] => Array
                (
                    [error] => invalid_grant
                    [error_description] => Invalid refresh token

Allegro-API-Request seem still to work, but refresh ist not possible.
We started new Authorization with Device-Auth, but with the same result.

**Comment by MaciejFrackowiak** [comment]
Please, send us a request and response in cURL format (with trace-id) via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - add a GitHub thread number 5165.

**Comment by Peymanpn** [comment]
Hello Maciej,

I can confirm the issue.
we are using the same method, and recently I can see in our logs that it happened several times a day.
although our retry policy covers it.

this is from one of the requests in Sandbox

```
  trace-id: fa6a7c52ade17fc1
  Date: Tue, 16 Nov 2021 14:05:38 GMT
```

**Comment by mickser** [comment]
Hello Maciej,

I tried it locally in my test environment and it worked.

API is still working regardless of the warning.

**Comment by MartaNowaczyk** [comment]
@Peymanpn We cannot find this trace-id. Can you provide username for this case?

**Comment by MartaNowaczyk** [comment]
@mickser If you have any problems, in addition to the error, please send us a trace-id and the relevant environment: allegro sandbox or allegro. Then we have some starting point to verify the problem.
