### ISSUE TITLE
Wyrób Akcyzowy

### ISSUE THREAD

**Issue by goliatek86** [allegro/allegro-api#5166]
Witam

Przejrzałęm dokumentacje i nie znalazłęm odpowiedzi.

Klient nam zgłasza iż wystawiając Aukcje po przez Api w Kategori Medycznych, domyślnie jest zaznaczona opcja "Wyroby Akcyzowe" Podczas gdy wystawia z poziomu Allegro ta pozycja jest domyslnie odznaczona. i z tąd Pytanie

Jak kierować tą opcją ? W parametrach jej nie widze, ogolnie jej nie widze w Api. a chce by domyślnie była odznaczona podczas wystawiania.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam więcej szczegółów - jakiej kategorii dotyczy problem, domyślnie nie mamy żadnej flagi na wystawianie produktów akcyzowych.
