### ISSUE TITLE
/order/checkout-forms/ - CheckoutFormNotFoundException

### ISSUE THREAD

**Issue by marmizg** [allegro/allegro-api#5167]
WItam,

Pobrałem transakcje w statusie "READY FOR PROCESSING".
Dla większości z nich wywołanie /order/checkout-forms/ działa prawidłowo, dla niektórych otrzymuję niestety informację
RESPONSE: >{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form 9a0201c1-4320-11ec-9be4-75a93a5de8ba not found","details":null,"path":"/order/checkout-forms/9a0201c1-4320-11ec-9be4-75a93a5de8ba","userMessage":"Checkout form 9a0201c1-4320-11ec-9be4-75a93a5de8ba not found"}]}<

RESPONSE: >{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form 50b8e952-4390-11ec-93e9-1be5f541b4e5 not found","details":null,"path":"/order/checkout-forms/50b8e952-4390-11ec-93e9-1be5f541b4e5","userMessage":"Checkout form 50b8e952-4390-11ec-93e9-1be5f541b4e5 not found"}]}<

RESPONSE: >{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form 3dd4cd41-40d9-11ec-a2cf-05e19ee3060d not found","details":null,"path":"/order/checkout-forms/3dd4cd41-40d9-11ec-a2cf-05e19ee3060d","userMessage":"Checkout form 3dd4cd41-40d9-11ec-a2cf-05e19ee3060d not found"}]}<

Czy dla tych transakcji kupujący zrezygnował ?
Czy może coś poknociłem ?

**Comment by MaciejFrackowiak** [comment]
Dla pierwszego i drugiego zamówienia bez przeszkód pobrałem ich szczegóły - sprawdź proszę raz jeszcze swoje wywołanie.
Natomiast dla zamówienia 3dd4cd41-40d9-11ec-a2cf-05e19ee3060d rzeczywiście nie można go odszukać - być może w tym przypadku kupujący dokonał łącznej płatności za swoje zamówienia, czego efektem będzie zmieniony identyfikator łącznego zamówienia.

**Comment by marmizg** [comment]
niestety lipa
Checkout form 9a0201c1-4320-11ec-9be4-75a93a5de8ba not found
Checkout form 50b8e952-4390-11ec-93e9-1be5f541b4e5 not found

jak była by potrzeba mnie znaleźć w logach to...
'x-requested-with' => 'issues_5167'
'user-agent' => 'libwww-perl/6.31'

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swoich wywołań.

**Comment by MaciejFrackowiak** [comment]
Udało mi się zlokalizować Twoje wywołania - próbujesz pobrać zamówienia z konta A będąc zautoryzowanym na koncie B - aby je pobrać musisz autoryzować się jako konto A.

**Comment by marmizg** [comment]
proszę...
https://api.allegro.pl/order/checkout-forms/50b8e952-4390-11ec-93e9-1be5f541b4e5
'trace-id' => 'f9c843f03b62a80b'

**Comment by MaciejFrackowiak** [comment]
> https://api.allegro.pl/order/checkout-forms/50b8e952-4390-11ec-93e9-1be5f541b4e5 'trace-id' => 'f9c843f03b62a80b'

Transakcja na koncie SmA-Re......., a próbujesz pobrać będąc zautoryzowanym na koncie REN...._WAR....

**Comment by marmizg** [comment]
ach, wszystko jasne, klient skacze pomiędzy dwoma (lub więcej) kontami na allegro.

Dziękuje za pomoc.
