### ISSUE TITLE
Zwrot wiadomość

### ISSUE THREAD

**Issue by trenzipl** [allegro/allegro-api#5168]
Dzień dobry,

założyliśmy konto na Google Workspace dla naszej domeny. Dodaliśmy email do konta allegro. Otrzymujemy takie wiadomości.

Nie znaleziono adresu
Wiadomość nie została dostarczona, ponieważ nie znaleziono adresu odbiorcy (hhkrkkde1u@allegromail.pl) lub odbiorca nie może odebrać wiadomości.
WIĘCEJ INFORMACJI
OstrzeżenieTen link poprowadzi Cię na stronę innej firmy
Odpowiedź otrzymana z serwera zdalnego:
550 5.7.23 <hhkrkkde1u@allegromail.pl>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=kontakt@trenzi.pl;ip=209.85.216.50;r=<UNKNOWN>

Potwierdziliśmy po stronie GOOGLE że domeny i cała reszta jest poprawnie wydelegowane. 

Denis

**Comment by MaciejFrackowiak** [comment]
To kwestia, która stricte nie dotyczy API - proszę, zgłoś swój problem poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c).
