### ISSUE TITLE
Wyrób akcyzowy - problem ze zmianą ceny

### ISSUE THREAD

**Issue by aguuu1994** [allegro/allegro-api#5169]
Witam, 
proszę o wyjaśnienie, dlaczego można wystawić produkt bez błędu, poprawnie, natomiast podczas synchronizacji cen pojawia się błąd: Podstawa wyłączenia z VAT "Wyroby akcyzowe" nie jest dostępna w kategorii 111855.
np:
![image](https://user-images.githubusercontent.com/71771405/141990589-f46809aa-281c-4ec1-b6e2-4b26ce3dde58.png)
![image](https://user-images.githubusercontent.com/71771405/141990766-e063ac83-f81d-44a9-874a-34a22d496e71.png)
oraz:
![image](https://user-images.githubusercontent.com/71771405/141990797-389d1f71-edd8-417a-9c61-acf9e9c241bc.png)
![image](https://user-images.githubusercontent.com/71771405/141990828-ad926cc4-b83b-49f7-9770-0dec3a75e070.png)

**Comment by MaciejFrackowiak** [comment]
Obie wskazane oferty miały przypisane do siebie ustawienia VAT o id=15561cff-4454-452b-b2c1-70df458cc823 - niestety, ani w kategorii 111855, ani w 47478 takie ustawienie nie jest dostępne (sprawdzić to zawsze możesz korzystając z [GET /sale/tax-settings](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory)). Jak widzę obecnie ustawienie VAT dla ofert jest już zmienione na id=ed5b1dc0-55db-4821-a922-39b0a4a5c716 i operacja powinna się poprawnie wykonać.
