### ISSUE TITLE
Sekwencyjna zmiana statusów zamówień, nie powoduje zmiany statusów w panelu klienta. 

### ISSUE THREAD

**Issue by MichalGrzybowski** [allegro/allegro-api#5170]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Klienci zgłaszają problem z brakiem zmian statusów po stronie Allegro. Requesty do Api Allegro od nas wychodzą prawidłowo i dostajemy poprawne odpowiedzi. Natomiast w panelu klienta nie widać efektów zmian. Udało nam się odtworzyć sytuację na sandbox. Mam trzy zamówienia:
633809f0-46b3-11ec-a65a-fd46d52d62cc
4b11f0c0-46b3-11ec-a65a-fd46d52d62cc
0a3f05f0-421d-11ec-a856-f1fcf54faadc

Wszystkie mają status "NEW". Zmieniam im sekwencyjnie statusy poprzez api na PROCESSING:

`
2021-11-16T13:48:45+01:00 INFO (6): 
-------------------------------------
REQUEST:

PUT /order/checkout-forms/633809f0-46b3-11ec-a65a-fd46d52d62cc/fulfillment HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.8.15
Authorization: Bearer 
Api-Key: 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Content-Length: 46

{"status":"PROCESSING","shipmentSummary":null}

-------------------------------------
RESPONSE:

HTTP/1.1 204 No Content
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1 ; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: 2ef5adb4cbdbbb4e
Referrer-policy: no-referrer
Date: Tue, 16 Nov 2021 12:48:45 GMT
X-content-type-options: nosniff
Strict-transport-security: max-age=31536000 ; includeSubDomains
Connection: close

2021-11-16T13:48:46+01:00 INFO (6): 
-------------------------------------
REQUEST:

PUT /order/checkout-forms/4b11f0c0-46b3-11ec-a65a-fd46d52d62cc/fulfillment HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.8.15
Authorization: Bearer
Api-Key: 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Content-Length: 46

{"status":"PROCESSING","shipmentSummary":null}

-------------------------------------
RESPONSE:

HTTP/1.1 204 No Content
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1 ; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: 7cd27e7c9585a90c
Referrer-policy: no-referrer
Date: Tue, 16 Nov 2021 12:48:45 GMT
X-content-type-options: nosniff
Strict-transport-security: max-age=31536000 ; includeSubDomains
Connection: close

2021-11-16T13:48:46+01:00 INFO (6): 
-------------------------------------
REQUEST:

PUT /order/checkout-forms/0a3f05f0-421d-11ec-a856-f1fcf54faadc/fulfillment HTTP/1.1
Host: api.allegro.pl.allegrosandbox.pl
Connection: close
Accept-encoding: gzip, deflate
User-Agent: Allegro API Client/5.8.15
Authorization: Bearer 
Api-Key: 
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Content-Length: 46

{"status":"PROCESSING","shipmentSummary":null}

-------------------------------------
RESPONSE:

HTTP/1.1 204 No Content
Expires: 0
Cache-control: no-cache, no-store, max-age=0, must-revalidate
X-xss-protection: 1 ; mode=block
Pragma: no-cache
X-frame-options: DENY
Trace-id: 7fee083e60a34cc3
Referrer-policy: no-referrer
Date: Tue, 16 Nov 2021 12:48:46 GMT
X-content-type-options: nosniff
Strict-transport-security: max-age=31536000 ; includeSubDomains
Connection: close
`

W efekcie tego jak wołam o status zamówienia po API otrzymuję poprawne odpowiedzi dla wszystkich zamówień. Natomiast klient w panelu dla zamówienia nr 633809f0-46b3-11ec-a65a-fd46d52d62cc ciągle widzi status "Nowe". Pozostałe zamówienia mają prawidłowo widoczny status: "W realizacji"

`
GET /order/checkout-forms/633809f0-46b3-11ec-a65a-fd46d52d62cc

HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 1e0e429e9b06ad61
date: Tue, 16 Nov 2021 12:50:35 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 1698
connection: close

{
  "id": "633809f0-46b3-11ec-a65a-fd46d52d62cc",
  "messageToSeller": null,
  "buyer": {
    "id": "93972135",
    "email": "xxx@user.allegrogroup.pl",
    "login": "Client:93972135",
    "firstName": "mmmm",
    "lastName": "mmmm",
    "companyName": null,
    "guest": false,
    "personalIdentity": null,
    "phoneNumber": "+48 44 444 44 44",
    "address": {
      "street": "mmmm 55",
      "city": "mmmm",
      "postCode": "55-555",
      "countryCode": "PL"
    }
  },
  "payment": {
    "id": "63c5a3f1-46b3-11ec-86f4-63acb1bc811e",
    "type": "ONLINE",
    "provider": "PAYU",
    "finishedAt": "2021-11-16T08:01:49.193Z",
    "paidAmount": {
      "amount": "108.40",
      "currency": "PLN"
    },
    "reconciliation": null
  },
  "status": "READY_FOR_PROCESSING",
  "fulfillment": {
    "status": "PROCESSING",
    "shipmentSummary": {
      "lineItemsSent": "NONE"
    }
  },
  "delivery": {
    "address": {
      "firstName": "mmmm",
      "lastName": "mmmm",
      "street": "mmmm 55",
      "city": "mmmm",
      "zipCode": "55-555",
      "countryCode": "PL",
      "companyName": "mmmm",
      "phoneNumber": "444444444",
      "modifiedAt": null
    },
    "method": {
      "id": "5d9c7838-e05f-4dec-afdd-58e884170ba7",
      "name": "Allegro Kurier24 InPost"
    },
    "pickupPoint": null,
    "cost": {
      "amount": "13.41",
      "currency": "PLN"
    },
    "smart": false,
    "time": {
      "guaranteed": null
    },
    "calculatedNumberOfPackages": 1
  },
  "invoice": {
    "required": false,
    "address": null,
    "dueDate": null
  },
  "lineItems": [
    {
      "id": "6337e2e0-46b3-11ec-a65a-fd46d52d62cc",
      "offer": {
        "id": "7681273903",
        "name": "MrÃ³wkarium",
        "external": {
          "id": "825bd545-22d1-4629-a25a-3d508fe5b49c"
        }
      },
      "quantity": 1,
      "originalPrice": {
        "amount": "94.99",
        "currency": "PLN"
      },
      "price": {
        "amount": "94.99",
        "currency": "PLN"
      },
      "reconciliation": null,
      "selectedAdditionalServices": [],
      "boughtAt": "2021-11-16T08:01:37.093Z"
    }
  ],
  "surcharges": [],
  "discounts": [],
  "summary": {
    "totalToPay": {
      "amount": "108.40",
      "currency": "PLN"
    }
  },
  "updatedAt": "2021-11-16T08:01:49.193Z",
  "revision": "b3a81206"
}
`

Nie jestem w stanie zidentyfikować dlaczego w tym przypadku się tak dzieje. Wykonując podobne operacje na innych zamówieniach wszystko aktualizuje się poprawnie, zarówno w API jak i w panelu. 

Dodam, że takie zblokowane zamówienie jest od tej pory nie do ruszenia przez api. Próba ponownej zmiany statusu dla pojedynczego zamówienia nie powoduje zmiany statusu w panelu, jedynie w api. Jedyna droga wyjścia to ręczna zmiana statusu w panelu. Po ręcznej zmianie requesty api na nowo prawidłowo aktualizują statusy w panelu.  

Proszę o informację co może być przyczyną takiego działania.

**Comment by MaciejFrackowiak** [comment]
Czy problem nadal występuje dla bieżących zamówień? Podpytuję, ponieważ w godzinach południowych mieliśmy opóźnienie w przetwarzaniu danych zamówień, czego jednym z efektów mogły być opóźnienia w aktualizacji danych.

**Comment by MichalGrzybowski** [comment]
Wygląda na to, że na sandbox aktualnie wszystko jest w porządku. Nie rozwiązuje to problemu losowego nie zmieniania się statusów naszych klientów na produkcji. Będziemy to dalej obserwować i gdy uda nam się znaleźć konkretny przykład na produkcji będziemy informować.
