### ISSUE TITLE
Client does not have the device_code grant

### ISSUE THREAD

**Issue by Lyta1enT** [allegro/allegro-api#5171]
Before this I encountered User name from JWT cannot be empty
This error, and then through github, I saw that other people also encountered this problem, I tried to solve this problem based on the answer above, and then encountered this error.How can I solve this problem?

curl -X POST -k 
-H 'Authorization: Basic Base64{client_id:clientpassowrd}' 
-H 'Content-Type: application/x-www-form-urlencoded' 
-H 'Accept: application/vnd.allegro.public.v1+json'
 -i 'https://allegro.pl/auth/oauth/device' 
--data '{
    "client_id":"client_id"
}'

response:
{
    "error": "unauthorized_client",
    "error_description": "Client does not have the device_code grant."
}

**Comment by MartaNowaczyk** [comment]
Please, send us a request and response in cURL format (with trace-id) via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - add a GitHub thread number 5171.

**Comment by Lyta1enT** [comment]
> 请通过[联系表单](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)向我们发送 cURL 格式（带有跟踪 ID）的请求和响应- 添加一个 GitHub 线程编号 5171。

Ok i have sent the mail

**Comment by Lyta1enT** [comment]
Now I have returned to that question, how do I assemble user_name into token, and what value is user_name?
![image](https://user-images.githubusercontent.com/94499471/142146743-465cf762-0e1f-472c-879b-e5afbf667066.png)

**Comment by MartaNowaczyk** [comment]
You are probably using [client_credentials](https://developer.allegro.pl/en/auth/#client-credentials-flow) authorization, which has no user context and is only used to retrieve public data. e.g. GET /sale/ categories. In [our documentation](https://developer.allegro.pl/en/documentation/#section/Authentication), you will find the appropriate markings of what type of authorization you should use. To use GET /order/checkout-forms for an authorized user, you need to use [code](https://developer.allegro.pl/en/auth/#authorization-code-flow) or [device](https://developer.allegro.pl/en/auth/#device-flow) authorization. I'll see more when I get the logs.

**Comment by Lyta1enT** [comment]
I recreated an application based on the same problem in github and checked the device_code. Now I can get the return value of device_code, expires_in, user_code, etc. /auth/oauth/device. Now the new problem is that I call /order/events interface, how do I encapsulate user_name into token, and what field value is user_name?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Client does not have the device_code grant (Issue #5171)





 
You are probably using client_credentials authorization, which has no user context and is only used to retrieve public data. e.g. GET /sale/ categories. In our documentation, you will find the appropriate markings of what type of authorization you should use. To use GET /order/checkout-forms for an authorized user, you need to use code or device authorization. I'll see more when I get the logs.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MartaNowaczyk** [comment]
As I wrote, you should use code or device flow for authorization, then the user id is visible in JWT. The user of the application must consent to the performance of activities on their behalf. After going to the address shown in verification_uri and confirming, you can receive a token that contains user_name.

**Comment by Lyta1enT** [comment]
After entering the link, filling in the user_code, and clicking OK, I entered this page, but did not see the token containing user_name, and then I entered my account, entered Link apps, and saw a new application added, or say Is the token containing user_name sent to the account mailbox of the registered application?

























------------------&nbsp;原始邮件&nbsp;------------------发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;


发送时间:&nbsp;2021年11月17日(星期三) 下午5:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Client does not have the device_code grant (Issue #5171)





 
As I wrote, you should use code or device flow for authorization, then the user id is visible in JWT. The user of the application must consent to the performance of activities on their behalf. After going to the address shown in verification_uri and confirming, you can receive a token that contains user_name.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MartaNowaczyk** [comment]
You should now start calling POST \
`'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=[device_code}' `
substituting the received device_code from the previous response in the appropriate place. Then you will receive the access token.

Everything is described [in point 4b of our guide](https://developer.allegro.pl/en/auth/#device-flow-user-authorization).

**Comment by Lyta1enT** [comment]
According to your prompt, I called this interface and returned this error because of what?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Client does not have the device_code grant (Issue #5171)





 
You should now start calling POST 
 'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&amp;device_code=[device_code}' 
 substituting the received device_code from the previous response in the appropriate place. Then you will receive the access token.
 
Everything is described in point 4b of our guide.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lyta1enT** [comment]
{"error":"authorization_pending","error_description":"User has not authorized the device code yet."}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Client does not have the device_code grant (Issue #5171)





 
You should now start calling POST 
 'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&amp;device_code=[device_code}' 
 substituting the received device_code from the previous response in the appropriate place. Then you will receive the access token.
 
Everything is described in point 4b of our guide.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MartaNowaczyk** [comment]
It looks like you didn't validate the code on the Allegro website.
When the user enters the correct code we will ask them to log on to Allegro and grant their consent to access their personal data. Once all the steps are taken correctly, we will present information about successful account authorization. Only then will you get the correct answer.

**Comment by Lyta1enT** [comment]
I have obtained the permission of these interfaces, are there other steps that I haven't operated yet? Please tell me what should I do?








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月17日(星期三) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Client does not have the device_code grant (Issue #5171)





 
It looks like you didn't validate the code on the Allegro website.
 When the user enters the correct code we will ask them to log on to Allegro and grant their consent to access their personal data. Once all the steps are taken correctly, we will present information about successful account authorization. Only then will you get the correct answer.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MartaNowaczyk** [comment]
Please send me step by step what are you doing, each call - request and response and screenshot via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - add a GitHub thread number 5171.
