### ISSUE TITLE
Platform badge interface returns empty data

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#5172]
We want to get the "campaign  name of the offer  through this interface(https://api.{environment}/sale/badges  ).
but we find that many online offers, the interface returns empty data, please help us to see why
![image](https://user-images.githubusercontent.com/72594584/142145651-ff1278d7-7951-4859-b2d6-a95b706134c7.png)

Our shop homyl returns offers with empty data: 10856071587, 10969629547
![lQLPDhrgT4e_zTPNAVDNBVGwPBJUZTjH9LQBnMDeh0BAAA_1361_336](https://user-images.githubusercontent.com/72594584/142145676-8ac3442f-6975-44b7-a1c4-d8dbb1fd8131.png)
![lQLPDhrgT5c_FW7NATzNBUSwAf-5CHhv1tABnMD3h4BkAA_1348_316](https://user-images.githubusercontent.com/72594584/142145692-8921ced4-8ca4-44b1-8d42-b7d584642ae9.png)

**Comment by hahyes** [comment]
I think developers here can't tell you exactly, what is the problem. You should contact with support of API you are using, because Allegro is not responsible for this integration with "szecommerce". This is support forum for "api.allegro.pl".

**Comment by bingnew** [comment]
This is a screenshot of the result returned by the (**https://api.{environment}/sale/badges** interface of our calling platform).
It was your colleague who told me that this interface can get the promotional advertisements under the account.
![image](https://user-images.githubusercontent.com/72594584/142161280-9d63868d-8098-4b8d-b382-3338c1232e8e.png)
related question：https://github.com/allegro/allegro-api/issues/5031

**Comment by hahyes** [comment]
First of all, I'm not Allegro employer.

> This is a screenshot of the result returned by the (https://api.{environment}/sale/badges interface of our calling platform).

But we don't know here, how your "calling platform" is creating request and processing response. This is not support forum for unknown calling platforms, just for direct communication with Allegro API.

**Comment by MartaNowaczyk** [comment]
1. You are using the POST method.
2. The screenshot shows a different "szecommerce" environment (as hahyes mentioned). 
To get a list of available badge campaigns, you should use GET 'api.allegro.pl/sale/badges'. You can also use this resource to check badges assigned to a particular offer GET 'https://api.allegro.pl/sale/badges?offer.id={offerId}'. 
You can find more information in [our guide](https://developer.allegro.pl/en/badge/#5-check-badges-assigned-to-offers).

Also, if the topic is about the same issue, continue it in the same thread.

**Comment by bingnew** [comment]
through this resource  GET 'https://api.allegro.pl/sale/badges?offer.id={offerId}',it is also empty response as belowing image:
![lQLPDhrgePI5MdHNAvPNBKGwNSipgkcp-3IBnQS5XIBaAA_1185_755](https://user-images.githubusercontent.com/72594584/142192294-0192e87f-64fd-4134-a5ea-f62e0541cdf4.png)
this offer is active in our shop.shop name is homyl.

**Comment by MartaNowaczyk** [comment]
The offer is active, but there are no additional badges. If the offer doesn't take part in any promotional campaign then you get an empty response.

**Comment by bingnew** [comment]
But  In your interface example, there is no such case that the return is empty。
![image](https://user-images.githubusercontent.com/72594584/142194816-99371884-4225-450b-96f8-4321b60830a0.png)

**Comment by MartaNowaczyk** [comment]
Yes, that's ok. If there are no results you get an empty array.
