### ISSUE TITLE
Allegro One protokół nadania

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#5173]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dla paczek z allegro one nie mogę pobrać protokołu nadania.
https://api.allegro.pl/parcel-management/parcels/protocol?parcelId=58008672&parcelId=58011724&parcelId=58015363
Dostaję zwrotkę 204.  Co to dokładnie znaczy? Czy dla tego rodzaju przesyłki nie ma potwierdzeń nadania?

**Comment by MaciejFrackowiak** [comment]
Tak, dla Alegro One nie zwracamy protokołu nadania.

**Comment by paafcioc22** [comment]
W razie zagubienia paczki jest to pierwszy dokument, którego z reguły wymagają firmy kurierskie.
W takim razie czy jest sposób na pobranie danych które prezentowane sa na froncie WzA? Jak niżej..
![image](https://user-images.githubusercontent.com/49162881/142411752-4dbd4c0a-8c09-4b99-a753-ee41772e43b8.png)

**Comment by MaciejFrackowiak** [comment]
Na podstawie dostępnych obecnie [zasobów](https://developer.allegro.pl/documentation/#tag/Parcel-management) nie wygenerujesz takiej listy w API.
