### ISSUE TITLE
Przykład podłączenia API allegro w C#

### ISSUE THREAD

**Issue by Adamszsz** [allegro/allegro-api#5174]
Witam .Czy znajdę gdzieś przykład podłączenia API allegro przez C#? 
Jest duża dokumentacja , ale wszystko opiera się na PHP.

Czy mógłbym  prosić o najprostszy przykład podłączenia się do API i np. pobrania danych dotyczących danej oferty po np. numerze kalaogowym lub czymkolwiek?
Dalej już sobie poradzę tylko potrzebuję prostego przykładu.

Pozdrawiam

**Comment by jacekmichalski** [comment]
Tutaj masz gotowego clienta api w c# napisanego.

https://github.com/PiotrFerenc/Allegro-api-rest-client

Gorąco polecam. Zachęcam również do dodawania PR jak coś ;-)

**Comment by MaciejFrackowiak** [comment]
@Adamszsz Nie posiadamy przykładów wykorzystania API w każdym języku, jednak tu zawsze można liczyć na użytkowników forum, którzy służą pomocą jak w tym przypadku za sprawą @jacekmichalski.

**Comment by jmarek-pl** [comment]
To jest aplikacja webowa ASP.NET czy desktopowa WPF/WinForm? W zależności o rodzaju aplikacji stosuje się różne sposoby autoryzacji.

**Comment by Adamszsz** [comment]
@jmarek-pl  jest to aplikacja WinForm

**Comment by jmarek-pl** [comment]
Czy potrzebujesz działać w imieniu użytkownika, czy wystarczy Ci dostęp do danych publicznych? Mam opracowany kod w C# i RestSharp pobierający do bazy danych wszystkich oferty użytkownika. W bazie danych przechowuję: ClientID, ClientSecret, AccessToken,  RefreshToken, TokenExpirationUtc. Aplikacja musi być zarejestrowana i chyba trzeba wybrać wtedy metodę autoryzacji. W każdym razie dostaniesz parę ClientID, ClientSecret,, która się nie zmienia. Następnym krokiem jest uzyskanie tych danych: user_code, device_code, verification_uri_complete. Aplikację niejako trzeba przypisać do konta użytkownika, mimo że to może być to samo konto co zarejestrowana aplikacja. Użytkownik musi przejść do adresu podanym w polu verification_uri_complete i zalogować się na swoje konto. Wtedy trzeba wykonać operację POST z użyciem device_code aby uzyskać Access Token i Refresh Token. Operację są autoryzowane przy użyciu Access Tokena.

**Comment by Adamszsz** [comment]
Wystarczy mi dostęp do danych publicznych . Chce tylko pobierać oferty ze strony przez api na podstawie nazwy bądź jakiejś nazwy  , lub w danej kategorii nic więcej.

**Comment by jmarek-pl** [comment]
Tego nie mam opracowanego. Skąpa dokumentacja jest tutaj: https://developer.allegro.pl/auth/#client-credentials-flow
Trzeba się domyśleć jak odświeżać później Access Token przy użyciu Refresh Tokena.

**Comment by hahyes** [comment]
> Trzeba się domyśleć jak odświeżać później Access Token przy użyciu Refresh Tokena.

Po co się domyślać, skoro to jest opisane?
https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena

**Comment by hahyes** [comment]
@Adamszsz @jmarek-pl Po co się domyślać, skoro to jest opisane?
https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena

**Comment by jmarek-pl** [comment]
Teraz widzę, że jest to opisane wspólnie dla różnych metod autoryzacji. Ale chyba nadal trzeba się domyśleć, że parametr w URL  redirect_uri w przypadku autoryzacji device flow nie ma sensu.
