### ISSUE TITLE
ParamID 215858 vs paramID 249034 w dziale motoryzacja (oświetlenie) - spadające aukcje

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#5175]
Dzień dobry,

Co się stało z parametrem id 215858 w grupie 
Allegro/ Motoryzacja/ Części samochodowe/ Oświetlenie/ Lampy przednie i elementy/ Lampy przednie

jak widzę obecnie parametr ten jest pod id 249034
Jest to  Numer katalogowy części . 

spadło nam kilkaset aukcji - czy to jest powód ? 
przykład Id: 7912885371

**Comment by MaciejFrackowiak** [comment]
Jak widzę wskazana oferta została zakończona 9 września 2021 - nie posiadamy już logów z tak odległego czasu. Jednocześnie mogę potwierdzić, że dla kategorii o id=255099 parametr Numer katalogowy części przyjął id=249034.

**Comment by wwwfactory** [comment]
Dzień dobry Panie Macieju. 
skupmy się przez chwilkę na ID kategorii. Czy mamy możliwość wcześniej reagować w związku z taką sytuacją ? Mamy kopie aukcji ale z innym ID. Jesteśmy to w stanie oprogramować ale trzeba mieć wiedzę że coś się zmienia .

Pozdrawiamy.

**Comment by MaciejFrackowiak** [comment]
Kategoria: Allegro/ Motoryzacja/ Części samochodowe/ Oświetlenie/ Lampy przednie i elementy/ Lampy przednie to kategoria o id=255099, natomiast wspomniałeś o parametrze o id=215858, a nie o takiej kategorii.

Mamy dwa zasoby, które pozwalają śledzić zmiany w kategoriach i parametrach:

1. [GET /sale/category-events](https://developer.allegro.pl/documentation/#operation/getCategoryEventsUsingGET_1) - wskazuje jakie zmiany zaszły w kategoriach w ciągu ostatnich 3 miesięcy;
2. [GET /sale/category-parameters-scheduled-changes](https://developer.allegro.pl/documentation/#operation/getCategoryParametersScheduledChangesUsingGET_1) - pozwala śledzić planowane zmiany w parametrach.

**Comment by hahyes** [comment]
> pozwala śledzić planowane zmiany w parametrach

Warto dodać, że ten dziennik informuje jedynie o zmianach w obowiązkowości parametrów. Nie pokrywa on sytuacji, którą opisuje tutaj OP.
