### ISSUE TITLE
[Wysyłam z Allegro] zasób parcel-management/parcel-create-commands/uuid

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#5177]
Występuje problem: 
 - [ X] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
W procesie zgłaszania przesyłki, wartośc uuid generowana lokalnie
1. wysyłam dane przesyłki Kurier UPS ( parcel-management/parcel-create-commands/uuid) , zwrotka HTTP/2 201, ok
2. chcę pobrać informacje o statusie utworzenia paczki dostaję
Array
(
    [0] => stdClass Object
        (
            [code] => ERROR
            [message] => Processing error
            [details] => 
            [path] => 
            [userMessage] => Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem
        )

)

trace-id: 3ea7e2c8f2d03ab0

**Comment by MartaNowaczyk** [comment]
Dziś mamy problemy z nadawaniem przesyłek UPS. Wyjaśniamy sprawę.

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować.
