### ISSUE TITLE
Wysyłam z Allegro  - Allegro Kurier UPS

### ISSUE THREAD

**Issue by adamus994** [allegro/allegro-api#5178]
Występuje problem: 
 - [x ] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym

Wyskakuje nam błąd jeśli chcemy utworzyć jakąkolwiek przesyłkę kurierem UPS.
Processing error -  - Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem.

Jeśli chcemy utworzyć przesyłkę bezpośrednio w wysyłam z allegro pojawia się komunikat:
Przesyłka nie została zamówiona.
Dostęp do API UPS jest chwilowo zablokowany, spróbuj ponownie za 30 minut.

Czy są jakieś problemy techniczne?

**Comment by MartaNowaczyk** [comment]
Potwierdzam problemy z nadawaniem przesyłek UPS. Wyjaśniamy sprawę.

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować.

**Comment by adamus994** [comment]
Działa, dziękujemy.
