### ISSUE TITLE
Definiowanie 'innej' marki przy wznawianiu produktów przez API - wymagana ręczna pomoc supportu Allegro?

### ISSUE THREAD

**Issue by ryszard-glegola-learning** [allegro/allegro-api#5179]
Wznowiśmy dwie zamknięte oferty:
https://allegro.pl/oferta/zasilacz-12v-do-lacie-cloudbox-11470052929
https://allegro.pl/oferta/zasilacz-12v-do-lacie-cloudbox-4tb-11470049810

API Allegro przestalo zezwalac na definiowanie wlasnych wartosci dla parametru marka, wiec teraz jest ona po prostu ustawiona na 'inna':
["id"]=>
string(6) "248135"
["name"]=>
string(5) "Marka"
["type"]=>
string(10) "dictionary"
(...)
["options"]=>
array(8) {
  (...)
  ["customValuesEnabled"]=>
  bool(false)
}

Gdzie możemy poprosić o dodanie marki 'myVolts' dla konkretnej kategorii i parametru - tutaj? Bo w przypadku problemów z API system pomocy Allegro nie daje możliwości wysłania zapytania ani otwarcia czatu z supportem Allegro.

Pozdrowienia
Ryszard

**Comment by MartaNowaczyk** [comment]
Tak, mogę to przekazać do odpowiedniego działu. Rozumiem, że chodzi o kategorię 76371 (Elektronika > RTV i AGD > Zasilanie > Zasilacze). Czy jeszcze jakieś?

**Comment by ryszard-glegola-learning** [comment]
Dzień dobry! Super, dziękujemy z góry - tylko ta kategoria  76371
(Elektronika > RTV i AGD > Zasilanie > Zasilacze)  , żadna inna.
Pozdrawiam,
Ryszard Glegoła
MYVOLTS

**Comment by MartaNowaczyk** [comment]
ok, dziękuję za informację. Zgłosiłam dodanie marki dla podanej kategorii.

**Comment by ryszard-glegola-learning** [comment]
Dziękujemy!

**Comment by MartaNowaczyk** [comment]
Marka myVolts została dodana. Pozdrawiam.

**Comment by ryszard-glegola-learning** [comment]
Dziękujemy!
Pozdrawiam serdecznie
Ryszard
MYVOLTS

24 lis 2021 09:30:32 MartaNowaczyk ***@***.***>:
