### ISSUE TITLE
Dane kontaktowe zwracane przez doGetPostBuyData

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#518]
Mam pytanie, które konkretnie dane są zwracane w polach userData, userSentToData oraz companySecondAddress ? Z tego co zauważyłem w polu userData dostaję dane adresowe konta: https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php (to co jest na samej górze) zaś w userSentToData dostaję dane z pól z sekcji "Dane osoby obsługującej konto (opcja)" oraz "Drugi adres przedsiębiorstwa (opcja)". Nie widzę możliwości, aby uzupełnić dane do ostatniego pola companySecondAddress. Rozumiem, że to jakaś zaszłość. Pytanie, czy to pole nie powinno być oznaczone jako deprecated albo usunięte ?

**Comment by AniaMalinowska** [comment]
Dotyczy to kont firmowych. Wówczas w moim Allegro, w zakładce [dane konta](https://allegro.pl/myaccount/mysettings.php) można podać osobę obsługującą konto oraz drugi adres przedsiębiorstwa.

**Comment by AniaMalinowska** [comment]
Dziękujemy. Weryfikujemy ten problem.
