### ISSUE TITLE
Tworzenie przesyłki Allegro One - Processing error

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#5180]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
trace-id: a7d62ca1ba3fe64d
command id: 7c5cdbff-4af7-4d19-8052-79cb1c80550e

Podczas tworzenia przesyłki Allegro One jeden z naszych klientów dostaje błąd code: ERROR, message: "Processing error", userMessage: "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem".
Zanim otrzymał ten błąd, API zwracało kolejno błędy dla items.description: "Opis przesyłki jest za krótki" oraz "Opis przesyłki jest za długi" (swoją drogą, jak można określić min/max długość opisu przesyłki?).
Co może być przyczyną tego bliżej nieokreślonego błędu?

**Comment by AureliuszBrussy** [comment]
Weryfikujemy to. Niebawem wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@magik092 błąd wystąpił przez brak przekazania wartości w polu **pickup.email** - dla tej metody dostawy jest on niezbędny. 

Jeżeli chodzi długość pola **description** - ogólnie jest to od 2 do 100 znaków, choć zależy to od konkretnego przewoźnika:

- DHL — wymagany (od 2 do 30 znaków)
- DPD — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
- FedEx — wymagany (od 2 do 100 znaków)
- GLS — opcjonalny (od 2 do 100 znaków)
- InPost — opcjonalny (od 2 do 100 znaków)
- InPost Kurier — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
- Poczta Polska — opcjonalny (od 2 do 100 znaków)
- ORLEN Paczka — opcjonalny (od 2 do 100 znaków)
- UPS — opcjonalny (od 2 do 50 znaków, jeżeli kraj odbiorcy "PL")
- Allegro — wymagany (od 2 do 50 znaków — jak w UPS)

**Comment by magik092** [comment]
Problem został rozwiązany

**Comment by magik092** [comment]
@AureliuszBrussy , kolejny z naszych klientów nie uzupełnił e-maila nadawcy ( pickup.email ) a zwrotka z API jest nieprecyzyjna (_Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem_)
Przykład: 
trace-id:fa7f92d29438540a
command id e237346d-276d-48b9-8cbe-aca6fb99483b

Czy można poprosić o poprawę komunikatu zwracanego z API?

**Comment by AureliuszBrussy** [comment]
@magik092 faktycznie, problem wywołał brak adresu e-mail w `pickup.email`. Poprawimy ten komunikat błędu.
