### ISSUE TITLE
Przesyłanie pliku z fakturą

### ISSUE THREAD

**Issue by acwirta** [allegro/allegro-api#5181]
Do jakiego formatu trzeba przekonwertować plik pdf, żeby można go było wgrać metodą PUT /order/checkout-forms/{id}/invoices/{invoiceId}/file ?

Za każdym razem dostaję błąd "FILE-CONTENT-INVALID", mimo że ten sam plik ręcznie wgrywa się bez problemu.

**Comment by AureliuszBrussy** [comment]
Plik powinien być właśnie w formacie .pdf. Podaj proszę trace-id (najlepiej cały request i response) przykładowego wywołania, które zakończyło się wspomnianym błędem. Sprawdzę powód.
