### ISSUE TITLE
Statyczne vs dynamiczne typowanie i edycja oferty

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#5182]
Zgodnie z dokumentacją:
https://developer.allegro.pl/my_offers/#edycja-pojedynczej-oferty
powinienem pobrać całą ofertę, zmodyfikować co chcę i wysłał.
Wygląda, że powinienem użyć zmiennej dynamicznej w C# i do niej deserializować JSON. W ten sposób w zmiennej dynamicznej będę miał pola, które w przyszłości dołoży Allegro i nic się nie zgubi po drodze. Zastanawia minie czy nie mogę użyć statycznego typowania  i deserializować JSON do zdefiniowanej w kodzie klasy. Przecież można odróżnić kiedy pola jest brak i powinno być ignorowane, to znaczy nie modyfikuję pola w bazie danych, a kiedy pole jest null i trzeba skasować wartość w bazie danych.

Choć jak spojrzałem na Stackoverflow wykrycie brakującej właściwości nie jest takie proste.

**Comment by AureliuszBrussy** [comment]
W tym przypadku trudno będzie mi doradzić konkretne rozwiązanie. Być może któryś z użytkowników naszego forum ma doświadczenie z taką problematyką w C# i będzie mógł Tobie pomóc.

**Comment by hahyes** [comment]
@jmarek-pl Korzystanie z `dynamic` nie jest wcale takim złym pomysłem, jednak niesie za sobą wiele ograniczeń w korzystaniu z LINQ chociażby. Powinno korzystać się ze statycznego typowania w większości wypadków, chyba że ma się ogromne doświadczenie i wie się, co się robi.

Co do "nieznanych pól", trzeba po prostu być na bieżąco. Zalecałbym zamiast babrać się z dynamic, wywoływać błąd w sytuacji, kiedy model obiektu w REST API się zmieni:
https://www.newtonsoft.com/json/help/html/DeserializeMissingMemberHandling.htm
(nie znalazłem odpowiednika w System.Text.Json, może słabo szukałem)
Użycie tego ustawienia wyrzuci błąd, kiedy pojawi się w JSONie nieznane pole.

**Comment by jmarek-pl** [comment]
Dynamiczne typowanie nie jest takie straszne, są całe języki dynamicznie typowane. Korzystam Newtonsoft ale o zgłaszaniu błędów nie pomyślałem. Faktycznie może to ułatwić ograniczenie użycia dynamic. Wydaje mi się, że powinienem użyć statycznego typowania w obsłudze błędów.
