### ISSUE TITLE
Parametr marki bez możliwości wpisania własnej wartości?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5185]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Dzień dobry,

może to nie bug, raczej jakaś niespójność w parametrach. W kategorii 76024 jest parametr Marka (3946), który ma w opcjach ustawione wartość `customValuesEnabled` na `false`, co mnie mocno zdziwiło, bo dotychczas nie widziałem, żeby taki przypadek występował. Proszę o informację, czy jest to umyślna zmiana czy wynik jakiegoś błędu. 

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Nie jest to bug i w niektórych kategoriach może zdarzyć się taka sytuacja. Konsultuję jeszcze, czy wskazana przez Ciebie kategoria na pewno powinna być tak ustawiona.

**Comment by AureliuszBrussy** [comment]
@hahyes zmieniliśmy ustawienia w tej kategorii - możesz już wprowadzić własną wartość.
