### ISSUE TITLE
Przerwy w nowych zamówieniach po nocnych masowych uploadach/aktualizacjach ofert przez API

### ISSUE THREAD

**Issue by ryszard-glegola-learning** [allegro/allegro-api#5188]
Dzień dobry! Mamy sporo ofert i co kilka dni zdarza nam się zrobić przez API masową aktualizację - oczywiście z zachowaniem numerów ofert, tytułów i kodów EAN, ale niekiedy ze zmianą ceny, liczby sztuk i/lub detali opisu. Po każdym takim nocnym uploadzie produktów zauważam kilka-kilkanaście godzin braku nowych zamówień (a w każdym razie zmniejszenie ich liczby). Czy ktoś aktualizuje może swoje oferty podobnie i ma podobne spostrzeżenia? Czy to kwestia jakiejś indeksacji lub innych algorytmów Allegro, które muszą najpierw przemielić zmienione oferty zanim zaczną one bezproblemowo się wyszukiwać?
Na Allegro Gadane nikt nie był w stanie udzielić mi odpowiedzi na to pytanie na razie.
Pozdrawiam serdecznie
Ryszard

**Comment by AureliuszBrussy** [comment]
Takie podstawowe operacje, jak zmiana liczby sztuk czy zmiana ceny nie wpływają na widoczność oferty - mam na myśli to, że w żaden sposób nie znika ona z listingu. Oczywiście oferta może zmienić swoją pozycję na liście ofert (w zależności od użytego sposobu filtrowania listingu). Oferta zniknie z listingu tylko po jej zakończeniu (zmianie jej statusu na INACTIVE).

**Comment by ryszard-glegola-learning** [comment]
Dziękuję

24 lis 2021 09:42:47 AureliuszBrussy ***@***.***>:

**Comment by ryszard-glegola-learning** [comment]
Dziękuję za odpowiedź!
Pozdrawiam serdecznie
Ryszard

24 lis 2021 09:42:47 AureliuszBrussy ***@***.***>:
