### ISSUE TITLE
Problem z odroczoną płatnością - brak drugiego zdarzenia

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5189]
Występuje problem: 
 - [ X ] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym

Mamy problem z zamówieniami z odroczoną płatnością, wg dokumentacji 
"Dla zamówienia z płatnością odroczoną zwrócimy drugie zdarzenie “READY_FOR_PROCESSING” w momencie przekazania środków przez dostawcę - pole “occurredAt” otrzyma jako wartość datę tej operacji (dzięki temu rozpoznasz, że nie jest to duplikat zdarzenia)."
Dla zamowienia o checkout_form_id 264f67b2-4a2b-11ec-97ba-e9af8d52344e
mamy tylko 3 eventy
id: 1637431010901818 BOUGHT
id: 1637431011126942 FILLED_IN
id: 1637431432386175 READY_FOR_PROCESSING
Nie ma drugiego zdarzenia ready_for_processing natomiast w sekcji payment dla tego checkout_form_id finishedAt i paidAmount są już uzupełnione:
"payment": {
"id": "2ba64991-4a2b-11ec-b97a-b149f18f3537",
"type": "EXTENDED_TERM",
"provider": "EPT",
"finishedAt": "2021-11-20T18:03:41.944Z",
"paidAmount": {
"amount": "155.80",
"currency": "PLN"
},
"reconciliation": null
},
"status": "READY_FOR_PROCESSING",
"fulfillment": {
"status": "SENT",
"shipmentSummary": {
"lineItemsSent": "ALL"
}
},

Z tego co rozumiem zamówienia z odroczoną płatnością powinny zawsze mieć 2 eventy ready_for_processing jeśli środki zostały już wypłacone, czy jest to błąd czy może jednak dopuszczalne są sytuacje z pojedyńczym eventem ready_for_processing dla odroczonej płatności?

**Comment by AureliuszBrussy** [comment]
Od 17 listopada w przypadku płatności odroczonej środki przelewane są sprzedającemu od razu - w związku z tym nie wystąpi już drugi event READY_FOR_PROCESSING. Więcej o zmianie dowiesz [w artykule](https://allegro.pl/dla-sprzedajacych/od-dzis-odroczona-platnosc-w-twoich-ofertach-na-allegro-biznes-pojawi-sie-automatycznie-nnnPAW4xgTM). Nie musisz już podawać na niej terminu odroczenia płatności - wkrótce przestaniemy zwracać datę odroczenia w polu **invoice.dueDate**. Przepraszam za wcześniejszy brak informacji - wkrótce opublikujemy odpowiedniego newsa oraz zaktualizujemy poradnik.
