### ISSUE TITLE
Pomieszanie imienia i nazwiska z firmą w doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#519]
Metoda doGetPostBuyFormsDataForSellers błędnie zwraca złączone imię i nazwisko w polu postBuyFormAdrCompany zamiast w postBuyFormAdrFullName. Dzieję się tak w przypadku kiedy w formularzu pozakupowym uzupełnimy formularz w danymi do faktury. Jako przykład podam transakcję z sandboxa: 727887702 lub d4391732-a21e-11e8-8f93-c3da38f2e5aa

**Comment by AniaMalinowska** [comment]
Podeślij nam przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) pliki *.XML z request i response (z wspomnianym błędem) - zweryfikujemy to.  Po wysłaniu zgłoszenia podaj nam tutaj jego numer.

**Comment by kormichu** [comment]
Ticket#1250468695

**Comment by AniaMalinowska** [comment]
Dziękujemy, weryfikujemy ten problem.
