### ISSUE TITLE
Weryfikacja numeru telefonu

### ISSUE THREAD

**Issue by harorri** [allegro/allegro-api#5191]
Utworzyłem nowe konto na sandboksie. Podczas składania zamówienia proszony jestem o weryfikację sms.
Jest możliwość obejścia tego zabezpieczenia (i smsy nie przychodzą).
Konto: nietestowalem+4@gmail.com

![image](https://user-images.githubusercontent.com/15194256/143214659-c5ae4601-e357-4ae6-bc07-2d55640f5b96.png)

**Comment by AureliuszBrussy** [comment]
W przypadku Sandboxa - nie wyślemy kodu SMS. Spróbuj wprowadzić kod: 1234.

**Comment by harorri** [comment]
Dzięki, działa.
