### ISSUE TITLE
Wystąpił błąd w module integracji Allegro. Nie jest to błąd działania naszego panelu, dlatego prosimy o zapoznanie się z poniższą informacją.

### ISSUE THREAD

**Issue by SlawekBieron** [allegro/allegro-api#5193]
Dzień dobry!

Przy próbie utworzenia oferty za pośrednictwem aplikacji IdoSell otrzymujemy błąd jak poniżej. Wystawiany towar ma stawkę VAT 0%
Chciałem dodać logi błędu ale nie można dodać plików z rozszerzeniem XML

Kod odpowiedzi zwrócony przez API Allegro:
VALIDATION_ERROR

Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
Nie znaleziono ustawienia podatku VAT dla podanej stawki.

Bardzo proszę o pomoc
Dziękuję i pozdrawiam

**Comment by AureliuszBrussy** [comment]
Każda kategoria ma zbiór możliwych do wykorzystania ustawień VAT. Dostępne ustawienia i identyfikatory stawek VAT w danej kategorii aplikacja może sprawdzić za pomocą [GET /sale/tax-settings?category.id={categoryId}](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory). Więcej o tym piszemy w [naszym poradniku](https://developer.allegro.pl/sale/#ustawienia-vat). Błąd o którym piszesz występuje prawdopodobnie dlatego, że aplikacja próbuje wprowadzić nieodpowiednią kombinację wartości pól **tax.rate**, **tax.subject** oraz **tax.exemption**. Skontaktuj się proszę z supportem aplikacji IdoSell aby to wyjaśnić.

**Comment by SlawekBieron** [comment]
Dzień dobry!

Chyba już wiem gdzie jest problem. Dla kategorii: Zdrowie/Domowa apteczka
dostępne są następujące stawki VAT: 23%, 8% oraz ZW. Brakuje natomiast
stawki 0%, która dotyczy sprzedaży testów w kierunku diagnostyki COVID-19 (
W myśl § 10bb pkt 1 rozporządzenia MF z 25.03.2020 w sprawie towarów i
usług, dla których obniża się stawkę podatku od towarów i usług, oraz
warunków stosowania stawek obniżonych (DzU poz. 527) *do 31.12.2022*
dostawy, WNT i import dopuszczonych do obrotu na terytorium RP testów
diagnostycznych w kierunku SARS-CoV-2 i wywołanej nim choroby COVID-19
(będących wyrobami medycznymi do diagnostyki *in vitro*) są opodatkowane
VAT według stawki 0%.)

Proszę o podpowiedź gdzie zgłosić się z prośbą o udostępnienie stawki 0%?

Pozdrawiam
Sławek Bieroń


czw., 25 lis 2021 o 07:56 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
Zgłoś ewentualny brak stawek czy wyłączeń poprzez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by SlawekBieron** [comment]
Dzięki! Zrobione.

Pozdrawiam
Sławek Bieroń


czw., 25 lis 2021 o 12:18 AureliuszBrussy ***@***.***>
napisał(a):
