### ISSUE TITLE
Filtrowanie danych w Raport Allegro - Trade Analytics

### ISSUE THREAD

**Issue by Ruuuda321** [allegro/allegro-api#5194]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [x] inny

:beetle: **Opis**
Cześć!
Pomoc techniczna odesłała mnie tutaj na forum jeśli chodzi o pytania związane z Trade Analytics.

Ogólnie chodzi o sposób działania filtrowania - wydaje mi się, że jest tu jakiś błąd logiczny, ale wolę dopytać. 
Ogólnie chodzi o to, że jak w Raporcie Allegro filtruje produkt po danym parametrze to wydaje mi się, że w kategorii "Sprzedaż wg parametrów" powinnam mieć 100% tylko dla tego parametru (no bo inne transakcje odrzucam podczas filtrowania).
Dla przykładu: Wybieram w kategorii "iPhone 11 Pro Max" i w parametrach "Kolor: zielony" i "Wbudowana pamiec: 64GB". Tak wiec oczekuje, że tylko te transakcje spełniające parametry są brane do raportów. A tu w raporcie wg parametrów mam, że Kolor zielony ma udział 37,61% w liczbie transakcji. Czy tak powinno być?
Jak przetestowałam ten sam produkt bez wyboru koloru to ten udział koloru zielonego jest inny, więc nie chodzi o to, że w tym raporcie jest całość sprzedaży....
Dla przykładu daje screeny.
![1](https://user-images.githubusercontent.com/29038642/143430009-8fb87a29-4fe1-4a21-acfc-403ce19f338a.png)
![2](https://user-images.githubusercontent.com/29038642/143430015-9088378d-fc86-4620-a18f-c4de34726635.png)

**Comment by Ruuuda321** [comment]
Sprecyzuje, że chodzi mi o to, że oba te warunki tj. Kolor=zielony i Wbudowana pamiec=64GB powinny być spełnione jednocześnie

**Comment by MartaNowaczyk** [comment]
Bardzo mi przykro, ale źle Cię przekierowano. Prowadzimy tutaj wsparcie dla API Allegro.

**Comment by Ruuuda321** [comment]
@MartaNowaczyk  a w takim razie z kim mogę się skontaktować w sprawie Trade Analytics?

**Comment by MartaNowaczyk** [comment]
Jeśli kontaktowałaś się z obsługą allegro proszę opisz sytuację w odpowiedzi na ostatnią wiadomość.
