### ISSUE TITLE
Wystawienie produktu powiązanego z TecDoc Tecalliance

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#5195]
Hej, 

podpowiedzcie proszę jak wystawić aukcję w taki sposób by mieć pewność, że będziemy łączyć ją z produktem TecDoc (Tecalliance) by w aukcji pokazała się sekcja Tecalliance oraz Sekcja pasuje do pobrana z Tecalliance 

aktualnie proces wygląda tak że muszę pobrać produkt po EAN  **https://developer.allegro.pl/productization/#1-jak-wyszuka%c4%87-produkt** ( czy można pobrać po TecDoc Article ID ? ) a następnie dopisać do niego sekcję pasuje do bazując na : **https://developer.allegro.pl/compatibility_list/#jak-wyszuka%c4%87-sugerowan%c4%85-sekcj%c4%99-compatibilitylist**

1) Prosił bym o informację jaki na ten moment jest najbardziej "chciany" sposób wystawiania ofert z Produktem z TecDoc 

2 ) oraz czy można już wystawiać ofertę z kilkoma produktami z TecDoc ? - **https://developer.allegro.pl/documentation/#operation/createProductOffers**

Głównie bazujemy też na **https://developer.allegro.pl/product_offers/** szukając rozwiązań naszych problemów

**Co chcemy uzyskać:** 
" W przyszłości, gdy skorzystasz z tego zasobu, w twoich ofertach zaprezentujemy najbardziej aktualne dane z naszego katalogu produktów. Gdy zaktualizujemy dane produktu w katalogu, nie będzie konieczne kopiowanie czy akceptowanie zmian w ofercie, jeśli nie przekażesz własnych wartości, innych niż te w produkcie. Pozwoli to nam także automatycznie uzupełnić parametry, których aktualnie wymagamy przy edycji oferty. " - by to stwierdzenie stało się prawdziwe, aktualnie po zmianie wersji TecDoc dostajemy informację na aukcjach o niekompatybilności wersji TecDoc przy zmianie ceny,

By aukcja od razu była powiązana z Tecalliance (powiązanie z bazą TecDoc)
By aukcja od razu posiadała pełną sekcję "Pasuje do" 

Pytanie może skracać się do: "Czy jeśli użyjemy https://developer.allegro.pl/documentation/#operation/createProductOffers mamy 100% pewności że przywiążemy się tylko o produktów, które są w bazie TecDoc po stronie katalogu allegro oraz czy takie aukcjie nie będą w przyszłości wymagały od nas monitorowania i jakiejś dodatkowej pracy bo całość będzie automatycznie aktualizowana? 

Dziękuję i pozdrawiam

**Comment by MartaNowaczyk** [comment]
1/ Jeśli to produkt z bazy TecDoc powinien już zawierać przypisaną sekcję Pasuje do, więc w tym momencie nie byłoby konieczne dopisywanie tej sekcji. 
To wyszukiwanie jeszcze potwierdzam - dam znać.
2/ Na ten moment nie ma automatycznej aktualizacji. Trzeba wysyłać chociaż pusty PATCH /sale/product-offers/{offerID}, dzięki czemu automatycznie zaktualizujemy w ofercie pola tecdocSpecification i compatibilityList, zgodnie z danymi w powiązanym produkcie.

**Comment by MartaNowaczyk** [comment]
Nie da się wyszukać po tecdoc article id.

**Comment by pliszka** [comment]
@MartaNowaczyk a w jaki sposób upewnimy się że wystawiamy produkt stworzony przez katalog Allegro powiązany z TecDoc a nie produkt wstawiony przez przysłowiowego Kowalskiego ?

**Comment by AureliuszBrussy** [comment]
@pliszka produkty pochodzące z bazy TecDoc mają uzupełnioną sekcję `tecdocSpecification`.

**Comment by pliszka** [comment]
chcemy się upewnić że wszystkie oferty wystawimy w ten sposób (jeśli chodzi o parametry pasuje do i sekcję TecAlliance) 

TraceID: d4712fec03a0c90b

niestety bazując na wystawianiu poprzez EAN mamy też i takie sytuacje TraceID: b04d1e8e28d9e5bd (akurat tego produktu nie ma najprawdopodobniej w TecDoc ale ogólnie chodzi mi tu o pewnego rodzaju uogólnienie)

**Comment by pliszka** [comment]
@AureliuszBrussy wiem, tylko pytanie brzmi jak upewnić się że to właśnie ten wystawimy (czasami pod jeden EAN jest wiele produktów w bazie Allegro), nie chcemy się upewniać czy te które wystawiliśmy mają połączenie ale że sposób w jaki wystawiamy będzie nam to połączenie gwarantował (nie połączy nas z produktem który stworzyła inna osoba)

**Comment by AureliuszBrussy** [comment]
W takiej sytuacji jedyną metodą upewnienia się, że użyty zostanie odpowiedni produkt, jest przekazanie w requeście identyfikatora konkretnego produktu (zdobytego dzięki [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts)) zamiast EAN. Nie ma metody, która od razu gwarantuje takie połączenie.

**Comment by pliszka** [comment]
@AureliuszBrussy ale w takim wypadku skąd będę wiedział, który z zwróconych mi przedmiotów jest tym który został stworzony przez Allegro ? 

```
{
"id": "d0c65fb9-59c6-4b47-9e33-53d73eaf6298",
"name": "AMORTYZATORY TYL SKODA OCTAVIA 3 III SUPERB +osl",
"category": {...}, // 2 keys
"parameters": [...], // 5 items
"images": [...], // 7 items
"description": null
},
```

poza tymi elementami w response powinno jeszcze przyjść tecdocSpecification ?

```
{
"id": "d0c65fb9-59c6-4b47-9e33-53d73eaf6298",
"name": "AMORTYZATORY TYL SKODA OCTAVIA 3 III SUPERB +osl",
"category": {...}, // 2 keys
"parameters": [...], // 5 items
"images": [...], // 7 items
"description": null,
"tecdocSpecification": [...] ????
},
```

**Comment by AureliuszBrussy** [comment]
@pliszka dla [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProduct) faktycznie nie zwrócimy pola **tecdocSpecification**. Pole to zwracamy przy sprawdzaniu szczegółów produktu ([GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)). Jeżeli w response pole to nie jest null'em - znaczy to, że dany produkt został utworzony na podstawie danych z TecDoca.

**Comment by pliszka** [comment]
@AureliuszBrussy ok to reasumując żeby mieć pewność, który produkt należy połączyć muszę: 

1 - pobrać produkty na bazie EAN za pomocą GET /sale/products?ean={ean} 
2 - każdy ID produktu przesłać do GET /sale/products/{productId} i zweryfikować czy ma on tecdocSpecification ?

Co w przypadku jeśli dwa produkty dlatego samego EANu (o różnych productId) będą miały tecdocSpecification?, który wtedy powinienem wybrać ?

**Comment by AureliuszBrussy** [comment]
@pliszka jeżeli produkty różnią się parametrami - wybierasz ten, który bardziej odpowiada sprzedawanemu przedmiotowi.

**Comment by pliszka** [comment]
ok to chyba już wszystko wiem temat do zamknięcia dzięki
