### ISSUE TITLE
Problem pobierania historii operacji płatniczych

### ISSUE THREAD

**Issue by rsartexit** [allegro/allegro-api#5196]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Żądanie historii operacji płatniczych zwraca pustą listę pomimio istniejących danych. Bez znaczenia są filtry zawsze zwraca pustą listę i status 200 OK. 
![image](https://user-images.githubusercontent.com/95028745/143434979-1e315a49-59e1-4227-9169-e05d8e02f939.png)

**Comment by MartaNowaczyk** [comment]
Potrzebuję więcej danych, aby to zweryfikować. Podaj proszę trace-id dla wywołania z pustą tablicą.

**Comment by rsartexit** [comment]
a0cc5b8ef6d261df

**Comment by MartaNowaczyk** [comment]
Dziękuję, sprawdzę i dam znać jak coś ustalimy.

**Comment by MartaNowaczyk** [comment]
Nie udało nam się namierzyć problemu. Ponów proszę ten sam request i daj mi jeszcze raz trace-id.

**Comment by rsartexit** [comment]
29f071c00b0654ea

**Comment by MartaNowaczyk** [comment]
Dziękuję, mam nadzieję, że teraz uda nam się to zweryfikować.

**Comment by MartaNowaczyk** [comment]
Token autoryzacyjny nie ma kontekstu użytkownika. Wygląda na to, że korzystasz z autoryzacji typu [client-credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow) (bearer-token-for-application). Zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/getSaleProducts), musisz być zautoryzowany za pomocą [code](https://developer.allegro.pl/auth/#app) lub [device](https://developer.allegro.pl/auth/#DeviceFlow) flow (bearer-token-for-user).
