### ISSUE TITLE
Odświeżenie AccessTokena

### ISSUE THREAD

**Issue by inmobilus** [allegro/allegro-api#5197]
Witam,
 Nasz klient posiada oprogramowanie wykorzystujące Allegro API. Na chwilę obecną posiada skonfigurowane ok. 20 aktywnych kont. Sporadycznie występuje u niego problem z odświeżeniem AccessTokena i nie możemy namierzyć czy problem leży po naszej stronie czy stronie API. Gdy AccessToken wygaśnie, oprogramowanie wysyła RefreshToken i zapisuje w bazie nową parę AccessToken i RefreshToken. Niestety nie posiadamy loga z Request/Response z każdej operacji jednak logujemy błędy + tokeny przed zapisem do bazy. Tak więc, otrzymaliśmy parę access/refresh, następnego dnia refresh został wykorzystany do odświeżenia tokena, niestety serwer zwrócił "Invalid refresh token". 
W swoich logach nie widzimy aby Refresh Token był wykorzystany wcześniej.
Końcówka refresh tokena "BHQoOMgrfPIAuqmZAalL3NWUwZ40Orier8ZFms51X2hHsly5eZP5w", mogę podesłać więcej informacji po kontakcie. Problem zwykle rozwiązujemy poprzez ponowną weryfikację konta, może jednak mogli by państwo zerknąć w swoje logi co się historycznie dzieje, że sporadycznie nie możemy wykorzystać refresh tokena. Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Prześlij proszę przez przez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) przykłady pełnych refresh tokenów oraz timestampy kiedy te zostały wp. Ciebie użyte. W zgłoszeniu dopisz numer wątku na GitHubie: #5197.

**Comment by AureliuszBrussy** [comment]
@inmobilus podaj proszę numer zgłoszenia. Powinieneś go otrzymać po wysłaniu wiadomości w formularzu (w wiadomości informującej o przyjęciu zgłoszenia).

**Comment by inmobilus** [comment]
18915036 ( ta sama wiadomość co tutaj na początku) następnie 19082214 z tokenami

**Comment by AureliuszBrussy** [comment]
W wiadomości podałeś dwa przykładowe tokeny - szczegółowo jestem w stanie sprawdzić logi tylko tego pierwszego, wygenerowanego 22.11. Twoja aplikacja odświeżyła ten token 2021-11-23 o godzinie 08:10:44 - w tym momencie zwróciliśmy nową parę access i refresh token. Drugą próbę odświeżenia widzimy właśnie o godzinie, którą wskazałeś w wiadomości (08:12). Wygląda na to, że Twoja aplikacja zgubiła pierwszą naszą odpowiedź.

**Comment by inmobilus** [comment]
Ok, dzięki za odpowiedź, szukam dalej

**Comment by troncomputers** [comment]
@inmobilus 
Gdzie zapisujecie tokeny? Do bazy, czy do pliku?

**Comment by inmobilus** [comment]
Do bazy

**Comment by troncomputers** [comment]
Bardzo długo walczyłem z tym problemem, ale ja zapisywałem do pliku i tutaj był problem z dostępem, aplikacja nie zdążyła zapisać nowej pary, a próbowała odpytywać API i tak w kółko. Odkąd przeszliśmy na bazę danych to problem zniknął.

**Comment by inmobilus** [comment]
Dzięki za sugestię, wrzucę trochę więcej logowania do aplikacji  i zobaczymy co się dzieje

**Comment by damianszymanskiphp** [comment]
@inmobilus Token jest ważny 12 godzin. Należy ustawić CRON co np godzinę i odświeżać go automatycznie. Zapis do bazy każdorazowo otrzymanej pary access_token & refresh_token rozwiąże problem, o ile w skrypcie CRON (oraz w skrypcie wykorzystującym Allegro API) będziesz pobierał ostatni rekord z bazy (Select * [...] ORDER BY `created` DESC)

**Comment by inmobilus** [comment]
Piszemy w .Net. Nie bardzo widzę związek z odświeżaniem tokena co godzinę a np. co 24h. Jeżeli klient wykonuje, którąś z operacji to każdorazowo sprawdzamy czy Access jest ważny, a jeżeli nie jest to zanim wykonamy żądanie klienta, aktualizujemy tokeny. Jak mówię, generalnie wszystko działa, problemy są sporadyczne np raz/kilka razy w miesiącu. Dodatkowo gdy dostaniemy zwrotkę o problemie konto ustawiane jest "niezweryfikowane" co zmusza klienta do weryfikacji. 
Moje pytanie wynikało raczej z czystej ciekawości czy u nas jest coś nie halo, czy może jednak po stronie API, dorzuciłem więcej logowania do appki ale narazie problem nie występuje. Czekam ;)

**Comment by troncomputers** [comment]
Nie prościej jest odpytać API, dostać zwrotkę 401 lub 403 `Unauthorized`, odświeżyć token i odpytać API jeszcze raz za pomocą rekurencji?

**Comment by kfijalko** [comment]
Zwrotka 40.. jedynie potwierdza, że token stracił ważność, co nie stanowi problemu.
Problem jaki należy rozwiązać to równoległe przetwarzanie wielu zadań i jednoczesne odświeżenie tokena. Tak żeby wszystkie zadania się wykonały i po ich zakończeniu żebyśmy mieli jeden prawidłowy token.
