### ISSUE TITLE
Dostęp do informacji OpenGraph

### ISSUE THREAD

**Issue by scholtysek-software** [allegro/allegro-api#5198]
Dzień dobry,
jedną z funkcjonalności rozwijanego hobbystycznie projektu jest zwrócenie użytkownikowi podstawowych informacji o stronie (produkcie) na podstawie wskazanego przez niego adresu URL. Zaznaczę od razu wyraźnie, że nie chodzi o webscrapping, a wyłącznie o uzyskanie metadanych konkretnego produktu wskazanego przez użytkownika. Zauważyłem, że udostępniają Państwo informacje za pomocą OpenGraph protocol i są to wystarczające informacje jakich potrzebuję: nazwa produktu, obraz oraz krótki opis.
Niestety wykonując zapytania za pomocą narzędzi "nieprzeglądarkowych" jak Postman czy bibliotek działających na serwerze nie jest możliwe uzyskanie tych informacji w związku ze zwracanym statusem 40X. Powody takiego zachowania są dla mnie oczywiście znane, natomiast chciałem dowiedzieć się czy istnieje jakiś sposób umożliwiający mi uzyskanie tych podstawowych informacji o produkcie w sposób wcześniej opisany.

Innymi słowy: w jaki sposób na podstawie pełnego URL do konkretnego produktu otrzymać informacje OG z poziomu aplikacji uruchamianej na serwerze?

**Comment by hahyes** [comment]
Na pewno otrzymasz tutaj informację, że nie wolno i że nie powinieneś tego robić.

> nie jest możliwe uzyskanie tych informacji

Jest to jak najbardziej możliwe. ;)
O ile nie próbowałem z OpenGraph, to jeżeli działa to na tej samej zasadzie co dostęp do ich API portalu... to aż za proste. Tylko trzeba się domyśleć, czego ci brakuje. ;)

**Comment by scholtysek-software** [comment]
@hahyes Dzięki za odpowiedź. 

Oczywiście, że są inne sposoby na uzyskanie informacji, o których mówię, ale nie o to mi chodzi. 

Po prostu widząc implementację OG na stronie, a następnie brak możliwości jej uzyskania, zastanawiam się czy Allegro przewiduje wsparcie o jakim piszę w pierwszej wiadomości.

**Comment by hahyes** [comment]
> @hahyes Dzięki za odpowiedź.
> 
> Oczywiście, że są inne sposoby na uzyskanie informacji, o których mówię, ale nie o to mi chodzi.
> 
> Po prostu widząc implementację OG na stronie, a następnie brak możliwości jej uzyskania, zastanawiam się czy Allegro przewiduje wsparcie o jakim piszę w pierwszej wiadomości.

@scholtysek-software Nie zrozumieliśmy się. Nie mówiłem o żadnym innym sposobie. Twoje zapytania zawiodły z konkretnego powodu. =)

**Comment by AureliuszBrussy** [comment]
@scholtysek-software działanie takie i korzystanie z tych metadanych jest niezgodne z naszym [regulaminem](https://allegro.pl/regulamin#artykul-10-inne-obowiazki-uzytkownikow).

**Comment by scholtysek-software** [comment]
@AureliuszBrussy Dziękuję za odpowiedź. 

W jaki sposób mogę mieć dostęp do tych danych zgodnie z regulaminem? Przecież za pomocą Allegro API sprzedawcy mają możliwość prawie pełnego wykorzystania serwisu Allegro (dodawanie ofert, przeglądanie itp.).

**Comment by AureliuszBrussy** [comment]
@scholtysek-software możesz pobierać wszystkie dane ofert danego sprzedającego, pod warunkiem, że Twoja aplikacja działa w imieniu tego sprzedającego - co potwierdza w momencie [autoryzacji i uwierzytelniania](https://developer.allegro.pl/auth/) (zaakceptuje powiązanie na consent screenie).

Udostępniamy także dla zweryfikowanych aplikacji zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Więcej o weryfikacji [przeczytasz w newsie](https://developer.allegro.pl/news/#public-offers-restrictions).

**Comment by scholtysek-software** [comment]
@AureliuszBrussy Świetnie. Dzięki za wyjaśnienie tematu.
