### ISSUE TITLE
Creating a product

### ISSUE THREAD

**Issue by tsserg1** [allegro/allegro-api#5199]
Dzień dobry Grupa Allegro.
W obszarze allegrosandbox ja próbuję utworzyć pozycję produktową za pomocą wywołania
https://developer.allegro.pl/en/documentation/#operation/proposeSaleProduct
Otrzymuję odpowiedź o odmowie dostępu chociaż “productCreationEnabled”=true, to znaczy ze ja mam możliwość tworzenia produktów na allegro.
Ten produkt jest na rzeczywistym koncie roboczym , ID 6fa9c0de-d715-458a-9dc7-5911582a91ac

Odpowiedź: 
{
    "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Access denied.",
            "details": null,
            "path": null,
            "userMessage": "Access denied."
        }
    ]
}
Używam Postman. Zapytanie:
curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJhb...vo2ug' \
--data-raw '{
    "name": "Przekładnia kierownicza Mercedes A-CLASS W169 MSG",
    "category":{
        "id": "250847"
    },
    "images": [
        {
            "url": "https://a.allegroimg.allegrosandbox.pl/original/11451d/836a1ddc4299a78fdba0a37cce30"
        }
    ],
    "parameters":[
        {
            "id": "127415",
            "values": [
                "MSG Rebuilding"
            ],
            "valuesIds": [
                "127415_22"
            ],
            "valuesLabels": [
                "Inny (MSG Rebuilding)"
            ],
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "215858",
            "values": [
                "ME 101R"
            ],
            "valuesLabels": [
                "ME 101R"
            ],
            "options": {
                "identifiesProduct": true
            }
        },
        {
            "id": "129591",
            "valuesIds": [
                "129591_1"
            ],
            "valuesLabels": [
                "Samochody osobowe"
            ],
            "options": {
                "identifiesProduct": false
            }
        },
        {
            "id": "227345",
            "values": [
                "169 460 21 00, 169 460 27 00",
                "169 460 31 00, 169 460 30 00",
                "169 460 30 00 80, 1694603300",
                "1694602200, A1694602200, 1694603000",
                "A1694600700, A1694602100, A1694602700",
                "A169460300080, 169 460 07 00",
                "A1694603100, A1694601700, A1694603000",
                "A1694603300, 1694602800, A1694602800"
            ],
            "valuesLabels": [
                "169 460 21 00, 169 460 27 00",
                "169 460 31 00, 169 460 30 00",
                "169 460 30 00 80, 1694603300",
                "1694602200, A1694602200, 1694603000",
                "A1694600700, A1694602100, A1694602700",
                "A169460300080, 169 460 07 00",
                "A1694603100, A1694601700, A1694603000",
                "A1694603300, 1694602800, A1694602800"
            ],
            "options": {
                "identifiesProduct": false
            }
        }
    ]
}'

**Comment by AureliuszBrussy** [comment]
Podaj proszę login (lub adres e-mail) Twojego konta na Sandboxie. Prawdopodobnie Twoje konto nie jest w pełni aktywne.

**Comment by tsserg1** [comment]
Mój login tsserg1@mail.ru

**Comment by AureliuszBrussy** [comment]
@tsserg1 aktywowałem Twoje konto - spróbuj teraz wysłać propozycję produktu.

**Comment by tsserg1** [comment]
Dzięki, zadziałało!

**Comment by tsserg1** [comment]
Czy mogę zobaczyć ten produkt na stronie https://allegro.pl.allegrosandbox.pl/?
Jeśli tak to jak?

**Comment by AureliuszBrussy** [comment]
@tsserg1 jeżeli produkt został utworzony, to oznacza, że jest zapisany w naszym Katalogu Produktów - możesz go odszukać za pomocą [GET /sale/products](https://developer.allegro.pl/en/documentation/#operation/getSaleProducts) oraz pobrać jego wszystkie dane dzięki [GET /sale/products/{productId}](https://developer.allegro.pl/en/documentation/#operation/getSaleProduct). 

Aby wystawić ofertę (będzie ona widoczna na [https://allegro.pl.allegrosandbox.pl/](https://allegro.pl.allegrosandbox.pl/)) powiązaną z tym produktem - skorzystaj z [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST) lub z [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers). Możesz dowiedzieć się więcej o wystawianiu ofert w naszych poradnikach:

- [Jak jednym requestem wystawić ofertę powiązaną z produktem](https://developer.allegro.pl/product_offers/),
- [Jak wystawić ofertę](https://developer.allegro.pl/sale/).

**Comment by tsserg1** [comment]
Czy mogę zobaczyć ten produkt na stronie https://allegro.pl.allegrosandbox.pl/?
Jeśli tak to jak?
