### ISSUE TITLE
Pobranie wszystkich aukcji przez REST API

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#520]
Czy istnieje możliwość pobrania wszystkich moich aukcji zarówno tych otwartych jak i zakończonych za pomocą jednego requesta (oczywiście ze stronicowaniem) ? Zasób https://developer.allegro.pl/documentation/#/offers-listing/getListing w domyślnym ustawieniu searchMode na REGULAR pobiera tylko te aukcje które trwają. Z kolei ustawienie CLOSED pobiera tylko te zakończone. Brakuje opcji ALL zwracającej jedne i drugie naraz :)

**Comment by AniaMalinowska** [comment]
Aktualnie nie ma możliwości, aby otrzymywać za pomocą jednego requesta jednocześnie oferty trwające, jak i zakończone. Planujemy udostępnić taka metodę. O nowych zasobach oczywiście będziemy informować na [portalu developerskim](https://developer.allegro.pl/news/) oraz [tutaj](https://github.com/allegro/allegro-api/issues?q=is%3Aopen+is%3Aissue+label%3Anews).
