### ISSUE TITLE
Dwa aktywne tokeny do jednego client_id

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#5202]
Czy jeśli aplikacja działa na dwóch nie połączonych komputerach potrzebuje nowego client_id i nowej rejestracji?

W przypadku połączonych przez wspólną bazę danych aplikację Windowsowych liczę, że uda mi się uniknąć dwóch aktywnych tokenów. Pobieram z tabeli w bazie danych tokeny i czas wygaśnięcia, ewentualnie odświeżam tokeny i zapisuję w bazie danych, w jednej transakcji z ustawioną insolacją na serialisable. MS SQL Server domyślnie blokuje dane, zatem powinno to dać efekt kolejkowania gdyby zdarzyło się odświeżanie tokenów z dwóch komputerów równolegle.

Problem jest trudny do przetestowania na mało obciążonym serwerze.

**Comment by AureliuszBrussy** [comment]
@jmarek-pl aplikacja w takim przypadku nie potrzebuje nowego client_id. Rzeczywiście możesz wygenerować więcej niż jeden access token równocześnie - wygenerowanie nowego access tokena nie unieważnia tego poprzedniego (co dzieje się tylko w przypadku skorzystania z refresh_tokena). Pamiętaj jednak, że obowiązuje limit dla liczby access tokenów, które możesz wygenerować w określonym czasie dla jednego użytkownika w ramach jednego client_id. Jeżeli go przekroczysz, w odpowiedzi zwrócimy błąd HTTP: 429 Too Many Requests.

W szczególnych przypadkach możesz także rozważyć użycie autoryzacji typu DCR - o ile faktycznie Twoja aplikacja wpisuje się w ten sposób działania. Umożliwia ona tworzenie instancji aplikacji w sposób zautomatyzowany - przeznaczona dla aplikacji, gdzie użytkownik instaluje kopię oprogramowania (np. instancję platformy sklepowej we własnej infrastrukturze). Więcej o tym przeczytasz w [naszym poradniku](https://developer.allegro.pl/auth/#dynamic-client-registration).

**Comment by jmarek-pl** [comment]
Wydaje mi się, że dla zwykłej aplikacji Windowsowej (desktopowej) autoryzacja typu Device Flow powinna wystarczyć. No i nie muszę przerabiać aplikacji :) Tokeny oszczędzam gdyż zapisuje datę jego wygaśnięcia w bazie danych. Uwaga o tym, że refresh token unieważnia access tokena jest ważna gdyż to może być źródłem komunikatów o błędzie.

Przychodzi mi do głowy taka sytuacja: na jednym stanowisku program sprawdził, że token jest jeszcze pół godz. ważny i idzie dalej. Mija chwila, użytkownik uruchamia pobieranie na drugim stanowisku.. Na drugim stanowisku program sprawdzi, że token jest ważny mniej niż pół godz. i chce go odświeżyć. W tym przypadku kolejne żądania do Allegro są autoryzowane starym tokenem na pierwszym stanowisku.

Przychodzą mi do głowy dwa rozwiązania. Każde stanowisko komputerowe ma własną parę tokenów i osobne miejsce w bazie danych na ich zapis. Drugie rozwiązania to pobieranie ofert Allegro w jednej blokującej dostęp do tabeli ustawień (w tym tokenów) transakcji bazodanowej. Efekt powinien być taki, że w czasie jak aplikacja pobiera nie można odświeżyć tokenów.

**Comment by AureliuszBrussy** [comment]
@jmarek-pl zgadza się, obydwa rozwiązania o których piszesz mają swoje uzasadnienie. Ostatecznie decyzja o implementacji należy do Ciebie. Być może na naszym forum znajdzie się użytkownik, który napotkał się na podobną problematykę i wypracował jeszcze jakieś inne rozwiązanie.

**Comment by jmarek-pl** [comment]
To pytanie bardziej do forum: Interesuje mnie czy aplikacja webowa (strona internetowa) jakoś zmienia sytuację z odświeżaniem tokenów. W podstawowej konfiguracji jest centralny serwer generujący strony internetowy, który może jakoś synchronizować żądania odświeżania tokenów. Wydaje mi się, że można zastosować singletona i mechanizmy synchronizacji wątków.

Ja stosuję RestSharp i rezerwuje czas użycia tokena przed operacją. Ale czytałem na forum, że w .net można użyć klasy HttpClient i jakoś ukryć odświeżanie tokenów w odpowiedzi na błąd żądania.
