### ISSUE TITLE
Szczegóły zwrotu towarów w pliku PDF

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#5204]
Witam

Czy istnieje możliwość pobrania przez API pliku ze szczegółami zwrotu towary w pliku PDF?
Chodzi o plik dostępny pod adresem:
https://edge.allegro.pl/returns/rescissions/{id-zwrotu}/form-document

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy takiej możliwości w publicznym API. Wszystkie dostępne opcje opisaliśmy [w poradniku](https://developer.allegro.pl/orders/#zwroty-klienckie) i [dokumentacji](https://developer.allegro.pl/documentation/#tag/Customer-returns).
