### ISSUE TITLE
Create new user's warranty

### ISSUE THREAD

**Issue by tsserg1** [allegro/allegro-api#5207]
Dzień dobry Grupa Allegro.
Próbuję wysłać żądanie POST (PUT):
https://api.allegro.pl.allegrosandbox.pl/after-sales-service-conditions/warranties

JSON
{"name": "Gwarancja","type": "SELLER","individual": {"period": "P6M","lifetime": false},"corporate": {"period": "P6M","lifetime": false},"description": "W celu uzyskania informacji o gwarancjach proszę o kontakt droga telefoniczną bądź mailową."}
application/vnd.allegro.public.v1+json
W Postmanie wszystko działa dobrze.

Ale w moim systemie otrzymuję kod powrotu 403 i opis błędu:
"<html><head><title>allegrosandbox.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMA0aCGGSjxUyQAwxpc0g==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'bv','s':29544,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>"

Co znaczy "Please enable JS and disable any ad blocker" ? Nie używam JS, ad blocker

**Comment by hahyes** [comment]
It seems like your URL is wrong and you're trying to enter sandbox website, not API. Make sure your URL in your system is `api.allegro.pl.allegrosandbox.pl`.

**Comment by PrzemyslawLukanowski** [comment]
Exactly, also please make sure that you don't use any additional "/" characters in the URL.

**Comment by tsserg1** [comment]
Thank you! It helped.
