### ISSUE TITLE
Błąd "Pickup point is invalid" przy walidacji paczki do Pocztex Kurier 48

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5208]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Witam,

mam problem z zamówieniem o UUID: 982d64a1-4f5c-11ec-b768-11ab31027e6a
Jest ono opłacone, wybrano sposób dostawy Pocztex Kurier 48.
Po utworzeniu paczki walidacja zwraca mi `Pickup point is invalid`. Domyślnie dla przesyłek kurierskich wysyłałem `pickup.pointId` (oraz `receiver.pointId`) jako `null`. Czy dla `Pocztex Kurier 48` powinienem wysyłać wypełniony `pointId` w jakiś sposób? Skoro mam podjazd kuriera Pocztexu, czemu wymagany jest ode mnie `pointId`? Problem nie występuje przy każdym zamówieniu z tego co wiem.

Jeszcze UUID świeżo utworzonej przesyłki z tym błędem: bce2b974-cb83-44b6-9805-48666f1097c7

Liczę na szybką odpowiedź.

**Comment by PrzemyslawLukanowski** [comment]
Przekazaliśmy ten problem do dostawcy usługi. Wrócę z odpowiedzią, gdy uda się wyjaśnić sytuację.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku przewoźnika Pocztex Kurier 48 nadanie może odbyć się tylko poprzez wskazanie punktu nadania w postaci placówki pocztowej. Nie będzie możliwości zamówienia podjazdu kuriera po odbiór takiej paczki. 
Taka opcja pojawia się dopiero w przypadku usługi Pocztex Ekspres 24, która daje możliwość zamówienia podjazdu kuriera po odbiór paczki i nie wymaga nadania jej poprzez placówkę pocztową.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Wykupiliśmy usługę Poczta Firmowa. która pozwala nam na podjazd kuriera. Właśnie przed chwilą kurier odebrał nadane dzisiaj paczki. Nie wiem w takim razie, o czym mówi dostawca usługi, ponieważ powinienem móc nadać taką paczkę bez problemu.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Mam też pytanie dotyczące nadawania bez umowy. Czy jest możliwy w ramach Wysyłam z Allegro bez umowy zamawianie podjazdu kuriera dla Allegro Pocztex Kurier 48 oraz Allegro Punkty? Byłbym wdzięczny za odpowiedź też na to pytanie. Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten temat, wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem potwierdzenie, że możliwość zamówienia podjazdu kuriera Poczta Polska do nadawcy istnieje tylko w usłudze Pocztex Ekspres 24. W przypadku Pocztex Kurier 48, Allegro Pocztex Kurier 48, i Allegro Punkty Żabka, Orlen, Ruch, nie ma możliwości zamówienia podjazdu. Wątpliwości w tej kwestii możesz wyjaśnić już bezpośrednio z przewoźnikiem.

**Comment by hahyes** [comment]
![image](https://user-images.githubusercontent.com/37104952/144072317-9d3dda9d-0cfb-4bbe-9b4e-5d2dab2a9da5.png)

@PrzemyslawLukanowski Screen z umowy podpisanej z Pocztą Polską. Dziś podjechał do nas kurier po Pocztex Kurier 48. Poczta oferuje podjazdy i ma cennik tej usługi.

https://allegro.pl/dla-sprzedajacych/metody-dostawy-poczty-polskiej-informacje-dla-sprzedajacych-EY0aDmkkyuA#
Tutaj też piszecie w temacie pomocy: "W przypadku regularnego nadawania dużej liczby paczek, rozważ możliwość skorzystania z usługi Poczta Firmowa zapewniającej odbiór przesyłek kurierem bezpośrednio z siedziby Twojej firmy."

Dla podanego przez nas przypadku na screenie, proszę o podanie poprawnego `pickupPointId`. Z góry dziękuję.

**Comment by PrzemyslawLukanowski** [comment]
@hahyes Musimy zweryfikować tę sytuację bezpośrednio z Pocztą Polską. Prośba o cierpliwość, wrócę z informacją.

**Comment by hahyes** [comment]
@PrzemyslawLukanowski Dzień dobry, chciałbym przypomnieć się z tematem, ponieważ powyższy problem utrudnia funkcjonowanie sklepu. Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Tak, cały czas pamiętam o tym zgłoszeniu, prosiłbym jednak o cierpliwość, ponieważ w tym przypadku czekamy także na odpowiedź ze strony Poczty. Jak tylko uzyskam wszelkie potrzebne informacje, poinformuję w wątku.
