### ISSUE TITLE
Po zmianie rozmiaru dalej nie można aktywować oferty

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#5209]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

98fac946670ba554

Witam,

Mam taki problem, że tworzę aukcję na allegro. Okazuje się, że jest błąd w parametrze rozmiar i zamiast 36 jest wybrany 34. Tworzy się szkic. Później próbuję edytować ten szkic metodą PUT i dalej otrzymuje ten sam błąd. Podałem wyżej trace-id dla metody, która zwróciła błąd mimo, że rozmiar jest już wybrany poprawnie.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem wskazany przez Ciebie request - w parametrze 54 przesłałeś wartość 3806_3, co odpowiada rozmiarowi 36:

`{"id":"54","valuesIds":["3806_3"],"values":[],"rangeValue":null}`

W produkcie 763454cc-6c74-40ae-84de-93ab4e744b1f wartość parametru "Rozmiar" (id 54) to 3806_2 (rozmiar 34). 

Upewnij się, czy faktycznie wysyłasz odpowiednią wartość w tym parametrze (czyli 3806_2).
