### ISSUE TITLE
sale/offer-publication-commands - OfferRepository error

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#521]
Podczas dodawania draftu nie mam żadnych błędów, jednak podczas jego publikacji (SANDBOX) 

`{"tasks":[{"offer":{"id":"6205590759"},"message":"OfferRepository error","status":"FAIL","scheduledAt":"2018-08-21T21:59:50.003+02:00","finishedAt":"2018-08-21T22:00:42.561+02:00","field":"publication"}]}`

Kilka aukcji udało mi się bez problemu opublikować.

**Comment by kkrzysiek11** [comment]
Mam ten sam problem, ale od wczoraj dopiero testuje API, więc nie jestem pewny, czy wszystko dobrze robię. Mój task - 67324004-a5e2-11e8-98d0-529269fb1459
Czy jest jakiś ogólny problem z API na sandboxie?

**Comment by Onixarts** [comment]
Podobnie na starym API sandboxowym:  OFFER_DEFAULT_ERROR_MESSAGE

**Comment by ventoh** [comment]
Same problem here: OfferRepository error in SANDBOX.

**Comment by MaciejPotepa** [comment]
@Rnapzsih @kkrzysiek11 @Rnapzsih @Onixarts sprawdzamy co jest nie tak na Sandboxie. Dzięki za zgłoszenie. 

@ventoh We're looking into it. Thanks for reporting that issue.

**Comment by Rnapzsih** [comment]
I czy ten problem występuje również w środowisku produkcyjnym? 
sale/offer-publication-commands/{commandId}/tasks - daje mi tylko `{"tasks":[]}`

**Comment by Rnapzsih** [comment]
Żeby nie było, publikacja daje: 
`{"id":"0fef6d5a-4e78-4f75-9d0a-ecf5579c21b9","taskCount":{"total":0,"success":0,"failed":0}}` Czyli jak by nie było prawidłowo. 

Natomiast sale/offer-publication-commands/0fef6d5a-4e78-4f75-9d0a-ecf5579c21b9/tasks
`{"tasks":[]}` 

Panie i Panowie z allegro - czas mnie goni a na strefie marek nie mam ani jednego produktu...

**Comment by MaciejPotepa** [comment]
@Rnapzsih pracujemy nad rozwiązaniem problemu. Przepraszamy za kłopoty i prosimy o cierpliwość. Dam znać jak sytuacja się wyjaśni.

**Comment by imper86** [comment]
Potwierdzam, u mnie na produkcji to samo.

**Comment by aktywnitu** [comment]
Jest problem globalny na produkcji. Działajcie!

**Comment by AniaMalinowska** [comment]
Problem na sandboxie nie powinien już występować. Jeśli jednak jest inaczej - także na produkcji - prosimy, podeślijcie nam pliki *.XML z requestami. Jeśli podeślecie je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422), podajcie tutaj numer Ticketa.

**Comment by Rnapzsih** [comment]
U mnie SNADBOX jak i produkcja działają.
