### ISSUE TITLE
Brak możliwości listowania i zarządzania ofertami w portalu allegro.pl.allegrosandbox.pl

### ISSUE THREAD

**Issue by it-cewe-pl** [allegro/allegro-api#5210]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Przechodząc na stronę:
_Allegro - Moje Allegro - Sprzedaż - Obsługa ofert - Moje oferty_
Nie mam możliwości edycji, czy nawet listowania moich ofert. Pojawia się tylko komunikat:
_Twoje oferty połączone z produktem - 100%. Tak trzymaj_
i opcja do filtrowania ofert bez produktu

Problem dotyczy konta:
Client:93962168

Mogę przesłać zrzuty ekranu.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem to i nie potwierdzam tych problemów. Zakładka powinna funkcjonować prawidłowo. Jeżeli wciąż zauważasz ten problem - przyślij proszę zrzut ekranu, który to zobrazuje.

**Comment by it-cewe-pl** [comment]
https://imgur.com/a/1q8njE0

Wybranie opcji Filtruj oferty bez produktu, nie zmienia niczego.
Czyściłem ciasteczka, zmieniałem przeglądarki (chrome i firefox), wchodziłem przez tryb incognito i nadal ten sam błąd.

**Comment by AureliuszBrussy** [comment]
@it-cewe-pl prześlij proszę zrzuty ekranu z konsoli programisty z przeglądarki (np. skrót F12 na Chrome) - chodzi o zakładkę Console i Network.

**Comment by it-cewe-pl** [comment]
Problemem są zmiany w centralnym firewallu. Z jakiegoś powodu cdn.allegrostatic.com.allegrosandbox.pl zostało zablokowane. Wyjaśniam problem z administratorem FW.

Pozdrawiam
Dawid Cz.
