### ISSUE TITLE
Błąd przy łączeniu  sky shop z allegro

### ISSUE THREAD

**Issue by AGCompanyj** [allegro/allegro-api#5211]
Występuje problem: 
 - [ ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [X] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [X] inny

:beetle: **Opis**

<!-- dokładnie opisz problem --
Jak chce połączyć allegro ze sky shop wyskakuje błąd na stronie alllegro apps że Nazwa aplikacji jest już wykorzystywana - podaj inną. jak podaje jakąkolwiek inną dalej taki sam komunikat. Allegro nie potrafi sobie poradzić z tym błędem i odesłali mnie tutaj. Bardzo proszę o pomoc bo nie mogę uzyskać nigdzie Klucz tajny aplikacji/Client Secret który jest niezbędny do połączenia ze Sky-shop
user Id 103471959

![allegro 1](https://user-images.githubusercontent.com/95291095/144053268-02bc84b2-9de5-456f-bb4d-5d073bb62b8e.PNG)
>

**Comment by AureliuszBrussy** [comment]
@AGCompanyj czy możesz podać więcej szczegółów?

**Comment by AGCompanyj** [comment]
Do połączenia ze sky shop potrzebuje uzyskać od allegro ID klienta aplikacji/Client oraz Klucz tajny aplikacji/Client Secret.
![image](https://user-images.githubusercontent.com/95291095/144058877-b1ac4513-da6a-4502-a86d-2e154b2cc4c9.png)
![image](https://user-images.githubusercontent.com/95291095/144058556-9929a3fc-1c83-49a8-9faf-7c7b4177d521.png)
zgodnie z instrukcją na powyższym zdjęciu wchodzę na stronę https://apps.developer.allegro.pl/new i próbuje go wygenerować ale niestety wyskakuje taki błąd: Nazwa aplikacji jest już wykorzystywana - podaj inną.
![image](https://user-images.githubusercontent.com/95291095/144059058-2b981835-98e2-49a2-8e97-11681645313a.png)
Próbowałam wpisać sto innych nazw a i tak wyskakuje ten sam błąd, w pomocy od allegro nikt nie wie o co chodzi, odesłali tutaj, nie znam się na "programowych" sprawach, jeśli brakuje jakichś istotnych informacji z tego punktu widzenia proszę o ich wskazanie

**Comment by AureliuszBrussy** [comment]
Nazwa aplikacji musi być unikatowa w ramach całego Allegro. Jeżeli ktoś już skorzystał z danej nazwy, nie będziesz mógł utworzyć aplikacji z taką samą nazwą. Skorzystaj proszę z innej, unikatowej nazwy, ponieważ ta wskazana na zrzucie już istnieje.

**Comment by AGCompanyj** [comment]
Dziękuję bardzo za pomoc
