### ISSUE TITLE
Return policy

### ISSUE THREAD

**Issue by tsserg1** [allegro/allegro-api#5212]
Hello Allegro Team.
Working with "return policy" API I couldn't find command to create an "attachment" object.
Now my "attachment" is
    "attachment": {
        "id": "d7be84bc-5408-42d2-8d0d-acf3ea02feba",
        "name": "Przykładowy formularz odstąpienia od umów.pdf",
        "url": "https://after-sales.allegrostatic.com/after-sales-service-d2/d7be84bc-5408-42d2-8d0d-acf3ea02feba"
    }
Can I use it as a const value or I have to create this object?
And how to do it in this case?

**Comment by PrzemyslawLukanowski** [comment]
This is a statutory model withdrawal agreement and it's a constant value - we return it for each return policy, You can’t change
this field.
