### ISSUE TITLE
Api przesyłka One Punkt pickup pointId

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#5213]
Tworząc nową przesyłkę podaję $data[pickup][pointId]="......"; ale prawdopodobnie przez to nie mogę zamówić podjazdu kuriera po przesyłki. Czy jeśli chciałbym stworzyć przesyłkę a następnie zamówić podjazd powinienem $data[pickup][pointId] przekazać puste czy wcale nie przekazywać danych w $data[pickup] ?

**Comment by PrzemyslawLukanowski** [comment]
Możesz w polu `pickup.pointId` przekazać null lub w ogóle nie przekazywać tego pola.

**Comment by allegrofan** [comment]
Dzięki za pomoc
