### ISSUE TITLE
Lista marek

### ISSUE THREAD

**Issue by jmarek-pl** [allegro/allegro-api#5214]
Pytanie wydaje się proste ale jakoś nie mogę tego znaleźć. Jak pobrać listę marek i czy taka lista jest globalna, czy związana z daną kategorią.

Mam w swoim programie listę marek do wyboru i chciałbym zrobić powiązanie z marką na Allegro. Przechowywać id marki. Wtedy mogę automatycznie pilnować wartość tego parametru.

**Comment by hahyes** [comment]
Parametry są indywidualne dla kategorii, czyli każda kategoria ma swoje "marki".

**Comment by PrzemyslawLukanowski** [comment]
Lista marek nie jest globalna, możesz pobrać dostępne wartości tego parametru w ramach danej kategorii - użyj w tym celu [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Listy wartości nie są stałe, co jakiś czas dodajemy nowe.

**Comment by hahyes** [comment]
Warto dodać, że id parametrów też mogą ulegać zmianie, więc trzeba to dobrze zaimplementować, żeby nie zostać z id parametru, który już nie działa.

**Comment by jmarek-pl** [comment]
Skoro marki nie są globalne, a mój program nie interesuje się kategoriami, to markę z Allegro muszę przechowywać jako nazwę a nie id. Za każdym razem odszukam sobie identyfikator. Czyli właściwie nie potrzebuję listy marek, tylko zamienić nazwę marki na id.

Jest, pod dłuższej chwili znalazłem :) Trochę to jest ukryte, trzeba w dokumentacji wybrać typ na dictionary i pojawi się pole tablica dictionary.

Czy przeszukanie liniowe takiej tablicy to jedyny sposób na zamianę nazwy marki na jej id? Czy dla każdej kategorii id marki może być różne? Jeśli mam powiązany produkt z mojej bazy z wieloma aukcjami potencjalnie w różnych kategoriach (sposób na ominięcie ograniczenia Allegro) to muszę to przeszukiwać tą tablicę dla każdej aukcji osobno. No i muszę sobie znaleźć parametr marka po id: 129033.

**Comment by PrzemyslawLukanowski** [comment]
Tak, może wystąpić sytuacja, że id będzie różne w zależności od kategorii. Co do przeszukiwania liniowego - na pewno jest to możliwa opcja, być może pozostali użytkownicy forum będą w stanie podpowiedzieć inne rozwiązania.
