### ISSUE TITLE
The stock level of items to be listed may not be lower than 1

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#5215]
Występuje problem: 
 - [X] z zasobem REST API
 - [X] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Próbuję zmienić ilość produktów w ofercie 10217235743. Jeśli wpiszę liczbę mniejszą niż 20, pojawia się błąd "Wystawiana liczba nie może być mniejsza niż 1."
![image](https://user-images.githubusercontent.com/5887720/144270356-46c057ff-53be-4c53-9a92-3407108f1a63.png)

Ten sam problem występuje przy próbie edycji oferty przez API

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem problem do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy wyeliminujemy błąd.

**Comment by PrzemyslawLukanowski** [comment]
Problem już nie powinien występować.

**Comment by rasskabak** [comment]
Niestety, problem znowu się pojawił, tym razem w innym przedmiocie
![image](https://user-images.githubusercontent.com/5887720/151727668-6fb2ac1d-82d0-45df-931c-5d621edbca2d.png)

**Comment by AureliuszBrussy** [comment]
Dla porządku - odpowiedź udzielę w nowym zgłoszeniu: #5372.
