### ISSUE TITLE
Problem z aktualizacją oferty gdy lista pasujących modeli została usunięta w produkcie

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#5216]
Występuje problem: 
 - [x ] z zasobem REST API
 - [ x] ze środowiskiem produkcyjnym

:beetle: **Opis**
Witam,

podczas wznawiania oferty otrzymuje:
`[code] => ConstraintViolationException.ValidCompatibilityTable
[message] => Given compatibility table is outdated, use the current one. Update offer with the most recent product data.
[details] => ConstraintViolationException.ValidCompatibilityTable
[path] => compatibilityTable
[userMessage] => Wskazana sekcja "Pasuje do" jest nieaktualna, podepnij najnowszą wersję dla tego produktu. Zaktualizuj dane produktowe w ofercie.`

Zgodnie z wcześniejszymi informacjami wysłanie pustego PATCH na sale/product-offers/xxx powinno zaktualizować ofertę.

W większości przypadków tak też się dzieję, niestety mamy kilka przypadków gdzie nam się to nie udało.
Po wysłaniu pustego PATCH znowu otrzymujemy ten sam błąd.

Podglądając ofertę przez formularz mamy:
![image](https://user-images.githubusercontent.com/36523118/144332632-f698fe9a-ca87-4d53-87f0-69dda70cdd3d.png)

produkt został zaktualizowany i usunięto z niego listę pasujących modeli - podejrzewam, że to jest przyczyną, że nie możemy zaktualizować teraz tego produktu.

trace-id: cb3c871f20fbb386

**Comment by PrzemyslawLukanowski** [comment]
Sytuację z zachowaniem metody PATCH weryfikuję i wrócę z odpowiedzią. Na tę chwilę problem na pewno nie wystąpi, jeśli pola `compatibilityList` i `tecdocSpecification`  zmodyfikujesz na zgodne z produktem za pomocą [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się ustalić przyczynę problemu, będziemy pracować nad poprawką. Poinformuję w wątku, kiedy już ją wdrożymy.

**Comment by dlis2010** [comment]
@PrzemyslawLukanowski 
udało się załatać problem?

**Comment by PrzemyslawLukanowski** [comment]
@dlis2010 Wdrożyliśmy odpowiednią poprawkę - problem nie powinien już występować.
