### ISSUE TITLE
Kod kreskowy na etykiecie One Punkt

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#5217]
Na etykiecie One Punkt kod kreskowy dotyczy Tracking (przykład 1Z 833 54F 68 ....) - jak mogę pobrać i skąd ten kod?

api.allegro.pl/parcel-management/parcel-create-commands
i
api.allegro.pl/parcel-management/parcels/

nie zwraca tego kodu.

**Comment by PrzemyslawLukanowski** [comment]
W przypadku przesyłek, których przewoźnikiem jest Allegro, w odpowiedzi dla GET /parcel-management/parcels/{parcelId} w polu `items.waybill` zwrócimy numer trackingowy, który rozpoczyna się od `ALE`. Nie zwracamy numerów, które są kodem kreskowym na etykiecie i rozpoczynają się od `1Z`.

**Comment by allegrofan** [comment]
Jak w takim razie powiązać kod kreskowy na etykiecie z zamówieniem? Skanuję wygenerowaną etykietę i muszę wyświetlić zamówienie.

**Comment by PrzemyslawLukanowski** [comment]
Waybill `ALE` również jest umiejscowiony na etykiecie w postaci kodu kreskowego - wystarczy, że go zeskanujesz. Jest to numer, który kupujący widzi i dostaje w komunikacji.

**Comment by allegrofan** [comment]
Zeskanowałem drugi kod z etykiety.

Przesyłka : ALE000009F27146
[parcelId] => 59970018

kod z etykiety po zeskanowaniu: 42044100

Jak poprzez API mogę pobrać ten numer, jak jest on oznaczony?

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za wprowadzenie w błąd, waybill `ALE` nie ma formy kodu kreskowego, w związku z czym nie da się powiązać przesyłki z zamówieniem na podstawie skanowania kodów kreskowych.

**Comment by allegrofan** [comment]
To może te numery są jakoś generowane z danych przesyłki i mógłbym je wygenerować?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie.

**Comment by allegrofan** [comment]
Czy w php da się jakoś przechwycić w momencie generowania etykiety: $api->sendApiRequestEtykieta('https://api.allegro.pl/parcel-management/parcels/label?parcelId='.$parcelId.'&pageFormat=A6', 'GET'); jej zawartość tzn numer przesyłki lub któryś z numerów ukryty pod kodami kreskowymi?

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę jedyne rozwiązanie, które niestety nie jest idealne, to wskazanie na etapie tworzenia paczki formatu termicznego (EPL lub ZPL). Następnie możesz pobrać etykiety i otworzyć pliki - w środku pliku znajdziesz zarowno numer 1Z..., jak i ALE... 
Jeśli coś zmieni się w temacie skanowania kodów kreskowych, wrócę z odpowiednią informacją w tym wątku.

**Comment by danmal85** [comment]
Gdzie można znaleźć przykłady tworzenia paczki w allegro api?
{
    "serviceId": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0",
    "receiver": {
        "address": {
            "street": "Górki 3",
            "postCode": "82-500",
            "city": "Kwidzyn",
            "countryCode": "PL",
            "county": null
        },
        "email": "d1odsarcpo+e4694651@user.allegrogroup.pl",
        "name": "Daniel Malinowski",
        "phone": null
    },
    "pickup": null,
    "items": [{
            "dimensions": {
                "height": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
            },
            "weight": {
                "value": "12.45",
                "unit": "KILOGRAM"
            },
            "value": {
                "amount": "100.00",
                "currency": "PLN"
            },
            "description": "Switch Dell Z9500",
            "type": "PACKAGE"
        }
    ],
    "label": {
        "sender": {
            "address": {
                "street": "Górki 2",
                "postCode": "82-500",
                "city": "Kwidzyn",
                "countryCode": "PL",
                "county": null
            },
            "email": "daniel.malinowski@test.pl",
            "name": "Daniel Malinowski",
            "company": "Altab S.A.",
            "phone": "500600700"
        },
        "fileFormat": "PDF",
        "referenceNumber": "23456789"
    },
    "additionalServices": {
        "cashOnDelivery": null,
        "options": []
    }
}
na https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e
Dostaje odpowiedź:
{"errors": [{
   "code": "BAD_REQUEST",
   "message": "JSON parse error",
   "details": null,
   "path": "/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e",
   "userMessage": "NieprawidĹ‚owa treĹ›Ä‡ ĹĽÄ…dania JSON"
}]}

**Comment by PrzemyslawLukanowski** [comment]
Przykład znajdziesz [w naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke). Widzę, że wkradł się tam nadmiarowy przecinek za sekcją `dimensions`, usunąłem go.

**Comment by danmal85** [comment]
Skopiowałem przykład z powyższego linku i nadal mam tę samą odpowiedź:
{
    "serviceId": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0",
    "receiver": {
        "address": {
            "street": "Testowa 172",
            "postCode": "61-132",
            "city": "Poznań",
            "countryCode": "PL"
        },
        "email": "hamu7udk3p+17454c1b6@allegromail.pl/",
        "name": "Jan Kowalski",
        "company": "Allegro.pl sp. z o.o.",
        "phone": "500600700",
        "pointId": "1234567"
    },
    "pickup": {
        "address": {
            "street": "Testowa 8",
            "postCode": "10-200",
            "city": "Warszawa",
            "countryCode": "PL"
        },
        "email": "email@mail.com",
        "name": "Jan Kowalski",
        "company": "Allegro.pl sp. z o.o.",
        "phone": "500600700",
        "pointId": "1234567"
    },
    "items": [{
            "weight": {
                "value": "12",
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
            },
            "description": "Car wheels.",
            "value": {
                "amount": "2.50",
                "currency": "PLN"
            }
            "type": "PACKAGE"
        }
    ],
    "type": "PACKAGE",
    "label": {
        "sender": {
            "address": {
                "street": "Testowa 8",
                "postCode": "10-200",
                "city": "Warszawa",
                "countryCode": "PL",
                "county": null
            },
            "email": "email@mail.com",
            "name": "Jan Kowalski",
            "company": "Allegro.pl sp. z o.o.",
            "phone": "500600700"
        },
        "fileFormat": "PDF",
        "referenceNumber": "abcd1234"
    },
    "additionalServices": {
        "cashOnDelivery": {
            "value": {
                "amount": "2.50",
                "currency": "PLN"
            },
            "accountNumber": "12345678901234567890123456",
            "name": "Jan Kowalski",
            "express": false
        },
        "options": [
            "guarantee0930"
        ]
    }
}

odpowiedź:
{"errors": [{
   "code": "BAD_REQUEST",
   "message": "JSON parse error",
   "details": null,
   "path": "/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e",
   "userMessage": "NieprawidĹ‚owa treĹ›Ä‡ ĹĽÄ…dania JSON"
}]}

**Comment by danmal85** [comment]
https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e
Niestety nie jest zwracana żadne informacja która mówi, w którym miejscu jest błąd.

**Comment by PrzemyslawLukanowski** [comment]
Przykład na stronie został zaktualizowany, usuń proszę przecinek za sekcją `dimensions`:

```
			"height": {
				"value": "20",
				"unit": "CENTIMETER"
			},
			"width": {
				"value": "20",
				"unit": "CENTIMETER"
			},
			"depth": {
				"value": "20",
				"unit": "CENTIMETER"
			},    <--------
```

**Comment by danmal85** [comment]
{
    "serviceId": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0",
    "receiver": {
        "address": {
            "street": "Testowa 172",
            "postCode": "61-132",
            "city": "Poznań",
            "countryCode": "PL"
        },
        "email": "hamu7udk3p+17454c1b6@allegromail.pl/",
        "name": "Jan Kowalski",
        "company": "Allegro.pl sp. z o.o.",
        "phone": "500600700",
        "pointId": "1234567"
    },
    "pickup": {
        "address": {
            "street": "Testowa 8",
            "postCode": "10-200",
            "city": "Warszawa",
            "countryCode": "PL"
        },
        "email": "email@mail.com",
        "name": "Jan Kowalski",
        "company": "Allegro.pl sp. z o.o.",
        "phone": "500600700",
        "pointId": "1234567"
    },
    "items": [{
            "weight": {
                "value": "12",
                "unit": "KILOGRAM"
            },
            "dimensions": {
                "height": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "width": {
                    "value": "20",
                    "unit": "CENTIMETER"
                },
                "depth": {
                    "value": "20",
                    "unit": "CENTIMETER"
                }
            },
            "description": "Car wheels.",
            "value": {
                "amount": "2.50",
                "currency": "PLN"
            }
            "type": "PACKAGE"
        }
    ],
    "type": "PACKAGE",
    "label": {
        "sender": {
            "address": {
                "street": "Testowa 8",
                "postCode": "10-200",
                "city": "Warszawa",
                "countryCode": "PL",
                "county": null
            },
            "email": "email@mail.com",
            "name": "Jan Kowalski",
            "company": "Allegro.pl sp. z o.o.",
            "phone": "500600700"
        },
        "fileFormat": "PDF",
        "referenceNumber": "abcd1234"
    },
    "additionalServices": {
        "cashOnDelivery": {
            "value": {
                "amount": "2.50",
                "currency": "PLN"
            },
            "accountNumber": "12345678901234567890123456",
            "name": "Jan Kowalski",
            "express": false
        },
        "options": [
            "guarantee0930"
        ]
    }
}

W dalszym ciągu ten sam błąd
{"errors": [{
   "code": "BAD_REQUEST",
   "message": "JSON parse error",
   "details": null,
   "path": "/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e",
   "userMessage": "NieprawidĹ‚owa treĹ›Ä‡ ĹĽÄ…dania JSON"
}]}

**Comment by PrzemyslawLukanowski** [comment]
Możesz wrzucić swój kod do przykładowego [validatora JSON](https://jsonlint.com/). Widać, że tym razem brakuje przecinka za sekcją` items.value`:

```
		"description": "Car wheels.",
		"value": {
			"amount": "2.50",
			"currency": "PLN"
		},
		"type": "PACKAGE"
```

**Comment by danmal85** [comment]
{
	"serviceId": "0e4c7d59-64b6-4b06-89c3-c1d941506dd0",
	"receiver": {
		"address": {
			"street": "Testowa 172",
			"postCode": "61-132",
			"city": "Poznań",
			"countryCode": "PL"
		},
		"email": "hamu7udk3p+17454c1b6@allegromail.pl",
		"name": "Jan Kowalski",
		"company": "Allegro.pl sp. z o.o.",
		"phone": "500600700",
		"pointId": null
	},
	"pickup": {
		"address": {
			"street": "Testowa 8",
			"postCode": "10-200",
			"city": "Warszawa",
			"countryCode": "PL"
		},
		"email": "email@mail.com",
		"name": "Jan Kowalski",
		"company": "Allegro.pl sp. z o.o.",
		"phone": "500600700",
		"pointId": "1234567"
	},
	"items": [{
		"weight": {
			"value": "12",
			"unit": "KILOGRAM"
		},
		"dimensions": {
			"height": {
				"value": "20",
				"unit": "CENTIMETER"
			},
			"width": {
				"value": "20",
				"unit": "CENTIMETER"
			},
			"depth": {
				"value": "20",
				"unit": "CENTIMETER"
			}
		},
		"description": "Car wheels.",
		"value": {
			"amount": "2.50",
			"currency": "PLN"
		},
		"type": "PACKAGE"
	}],
	"type": "PACKAGE",
	"label": {
		"sender": {
			"address": {
				"street": "Testowa 8",
				"postCode": "10-200",
				"city": "Warszawa",
				"countryCode": "PL",
				"county": null
			},
			"email": "email@mail.com",
			"name": "Jan Kowalski",
			"company": "Allegro.pl sp. z o.o.",
			"phone": "500600700"
		},
		"fileFormat": "PDF",
		"referenceNumber": "abcd1234"
	},
	"additionalServices": {
		"cashOnDelivery": {
			"value": {
				"amount": "2.50",
				"currency": "PLN"
			},
			"accountNumber": "12345678901234567890123456",
			"name": "Jan Kowalski",
			"express": false
		},
		"options": [
			"guarantee0930"
		]
	}
}

kod już jest ok 
ale problem jest ten sam 
{"errors": [{
   "code": "BAD_REQUEST",
   "message": "JSON parse error",
   "details": null,
   "path": "/parcel-management/parcel-create-commands/04189b13-6fd0-4410-9d24-46bf18ed916e",
   "userMessage": "NieprawidĹ‚owa treĹ›Ä‡ ĹĽÄ…dania JSON"
}]}

**Comment by danmal85** [comment]
Udało mi się rozwiązać problem zły encoding w request, dziękuję z pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Dodam jeszcze tylko, że dla każdej nowej przesyłki musisz generować nowe commandID. Widzę, że korzystasz z tego samego, dlatego zawsze zwracamy Ci komunikat związany z pierwszą operacją dla tego commandID:

> Aby utworzyć nową paczkę, skorzystaj z [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel). Jako commandId przekaż numer [UUID](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#identyfikatory-zasobow) - wygeneruj go automatycznie we własnym zakresie. Pamiętaj, aby dla każdej nowej przesyłki, którą tworzysz, użyć nowego numeru UUID.

Dodatkowo, w body requestu musisz uwzględnić dane z zamówienia, które należy do konta, na którym jesteś zautoryzowany. Musisz zatem jako kupujący zakupić przedmiot w swojej ofercie, tak aby takie zamówienie utworzyć.
