### ISSUE TITLE
Wysyłam Allegro DPD - VALIDATION_ERROR

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#5218]
Występuje problem: 
 - [X] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
trace-id: 10748dcc42bd5f0e
command id: 82ab7111-9a1f-4bcb-9da5-bb3ef9472370

Podczas tworzenia przesyłki Allegro DPD jeden z naszych klientów dostaje błąd code: VALIDATION_ERROR, message oraz message: "Processing error", path: "pickup.name".
Jeśli wartość pickup.name sprawdzimy sobie jako wyrażenie regularne (np. na regex101.com), przechodzi bez problemu.

**Comment by AureliuszBrussy** [comment]
W pickup.name powinno znaleźć się imię i nazwisko osoby nadającej przesyłkę - akceptujemy dwa elementy (wyrazy) oddzielonych spacją.

**Comment by magik092** [comment]
@AureliuszBrussy pickup.name to w tym wypadku coś w stylu: "**NAZWA KLIENTA SP. ZO.O**"

**Comment by AureliuszBrussy** [comment]
@magik092 zgadza się - i takie wyrażenie nie zostanie zaakceptowane. Nazwa firmy powinna znaleźć się w polu **pickup.company**, natomiast w **pickup.name** imię i nazwisko osoby nadającej przesyłkę, czyli np. "Jan Kowalski".

**Comment by magik092** [comment]
Jeśli name i company są wpisane odwrotnie, walidator to wyłapie?
```
"name":"NAZWA FIRMY SP. ZO.O"
"company":"Jan Kowalski"
```
Wg. komunikatu (wyrażenie regularne) `[\p{L} -]*` spełnia warunek.
Natomiast zasugerujemy klientowi aby zamienił wartości.

**Comment by magik092** [comment]
Właśnie o ten regex mi chodzi, nawet odwrotnie wartości jak wysyłamy to ta zła wartość jest zgodna z regex (w sensie jak złą wartość sprawdzimy tym regexem) jednak API zwraca błąd jakoby się nie zgadzało (być może w requeście z trace-id 10748dcc42bd5f0e będzie coś więcej widać). Być może jest to zły komunikat błędu po prostu.

**Comment by AureliuszBrussy** [comment]
@magik092 `\p{L}` to litery Unicode - tutaj problem powodują znaki ".".

**Comment by magik092** [comment]
@AureliuszBrussy czyli domykając temat, podany wzorzec de facto wygląda tak `^[\p{L} -]*$` (uwzględnia początek i koniec)?
Jeśli tak, poprawimy nasz walidator.

**Comment by AureliuszBrussy** [comment]
@magik092 zgadza się, natomiast i tak możecie otrzymać błąd ze względu na walidację poszczególnych przewoźników, natomiast komunikat błędu w takim przypadku powinien być inny.
