### ISSUE TITLE
Allegro pocztex [pickup][pointId]

### ISSUE THREAD

**Issue by allegrofan** [allegro/allegro-api#5219]
Czy wchodząc w zamówioną przesyłkę w panelu wysylam.allegro.pl w "NADAWCA" po kliknięciu w mapkę (Pokaż na mapie) w informacji jaką widzę tzn "Poczta FUP Białystok 11 , 974555" numer 974555 to jest numer, który powinienem użyć w API przy zamawianiu przesyłki w  $data[pickup][pointId]="974555";  czy w inny sposób muszę znaleźć swój pickup point id? Jeśli tak to w jaki?

**Comment by AureliuszBrussy** [comment]
Aktualnie numer punktu możesz pobrać z API konkretnego przewoźnika. Więcej o API Poczty Polskiej możesz przeczytać na [ich stronie](https://www.poczta-polska.pl/webservices/).

Id punktu zwrócony na mapie powinien być prawidłowy i możliwy do użycia.
