### ISSUE TITLE
SHIPPING_TIME_IS_NOT CUSTOMIZABLE

### ISSUE THREAD

**Issue by darekmeco** [allegro/allegro-api#522]
Przy probie zapisu cennika przy niektorych metodach płatnosci  jest error

SHIPPING_TIME_IS_NOT CUSTOMIZABLE

Ale nie wiadomo ktore można edytowac przed wyslaniem requestu.

GET /sale/delivery-methods nie zwraca informacji na ten temat

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) pełnego cURL-a i requesta sprawdzimy w czym jest problem.

**Comment by darekmeco** [comment]
wyslane, ale tu wszystko widac, poprstu w niektorych metodach dostawy nie mozna zmieniac czasu dostawy. ale taka informacja powinna byc dostepna w GET /sale/delivery-methods

**Comment by PawelTaberski** [comment]
Wklej tutaj proszę numer ticketa.

**Comment by darekmeco** [comment]
03565290

**Comment by darekmeco** [comment]
To moze tak: ref:_00D24aE05._5001o2jIdtn:ref

**Comment by PawelTaberski** [comment]
Wygląda jakby po prostu brakowało w numerze jaki podesłałeś wcześniej 2 cyfr. Jednakże, może poradzimy sobie bez tego. Przetestowałem sytuację o której pisałeś i po wywołaniu takiego błędu otrzymuję wprost o jaką formę dostawy chodzi:
`            "code": "SHIPPING_TIME_IS_NOT_CUSTOMIZABLE",
            "message": "Shipping method 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93 can not have shipping time customized",
            "details": null,
            "path": "rates[0].shippingTime",
            "userMessage": "Shipping method 2488f7b7-5d1c-4d65-b85c-4cbcf253fd93 can not have shipping time customized"` 
Ponadto przy znacznej większości metod wysyłki nie możesz zmieniać tych informacji.

**Comment by darekmeco** [comment]
Ok, wiec w responsie sprawdze czy mozna zmieniac, a potem musze poprawic dane w requescie i wyslac od nowa. Gdyby ta informacja byla w GET /sale/delivery-methods nie musilbym dublowac requestow.

**Comment by PawelTaberski** [comment]
Rozumiem w czym jest problem, jednakże w bardzo niewielu przypadkach wysyłek można ustawić taki czas. Niemniej zgłosiłem Twoją uwagę do odpowiedniego zespołu.

**Comment by darekmeco** [comment]
Jeszcze zeby w odpowiedzi bylo id przesylki a tu musze prasowac message zeby wycignac id. 
Shipping method 496c5d07-a095-4cf3-bc3a-2217e01172a3 can not have shipping time customized

Nie za fajnie.
