### ISSUE TITLE
GET /sale/offers/{offer.id} - 500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by kamilstudent** [allegro/allegro-api#5220]
Mam problem z wyszukaniem konkretnego zamówienia, /sale/offers działa bez zarzutu, natomiast w przypadku GET /sale/offers/{offer.id} dostaję 500 INTERNAL SERVER ERROR

```
{
  "errors": [
    {
      "code": "INTERNAL_SERVER_ERROR",
      "message": "Internal server error.",
      "details": null,
      "path": null,
      "userMessage": "Internal server error. Please try again in a few minutes."
    }
  ]
}
```

trace-id 357c4b7d9c8b0c7f

**Comment by AureliuszBrussy** [comment]
Wygląda na błąd po stronie jednej z naszych usług. Wyjaśniam to - wrócę do Ciebie z odpowiedzią.

**Comment by kamilstudent** [comment]
Zauważyłem, że w momencie kiedy oferta nie ma stworzonego produktu odpowiedzią jest 500 Internal Server Error, w momencie kiedy oferta posiada produkt wszystko działa jak należy.

**Comment by AureliuszBrussy** [comment]
@kamilstudent jeszcze to weryfikujemy - wrócę z informacją, jak tylko to wyjaśnimy.

**Comment by AureliuszBrussy** [comment]
@kamilstudent problem nie powinien już występować.
