### ISSUE TITLE
Problem z wystawieniem produktu przez Ido Sell - nieprawidłowy kod EAN

### ISSUE THREAD

**Issue by Lukaszs1992** [allegro/allegro-api#5225]
Występuje problem: 
 - [X ] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

 Podczas wystawiania produktu przez formularz otrzymuję błąd VALIDATION_ERROR, Provided EAN code is incorrect . Jednakże jest to kod EAN jaki otrzymaliśmy na fakturze i powinien być poprawny. Inni sprzedawcy również posługują się tym kodem. Niestety logi żądania i odpowiedzi są puste. Kod EAN produktu to 778988389601 .

**Comment by Lukasz-Zurek** [comment]
Otrzymujesz błąd, ponieważ podany kod EAN jest nieprawidłowy (cyfra kontrolna w EAN jest niepoprawna). Możesz to sprawdzić poprzez dowolny walidator EAN.

**Comment by Lukaszs1992** [comment]
Dwa walidatory znalezione przeze mnie wskazują na poprawność kodu:
https://formvalidation.io/guide/validators/ean/ lub
https://www.getnewidentity.com/validate-ean.php . Wskazany kod EAN widnieje
także na fakturze otrzymanej od wydawcy.

pon., 6 gru 2021 o 10:31 Lukasz-Zurek ***@***.***> napisał(a):

**Comment by Lukasz-Zurek** [comment]
Faktycznie część walidatorów wskazuje na to, że EAN jest ok. Kod EAN jest jednak nieprawidłowy i zachęcam tutaj do bezpośredniego kontaktu z producentem.
