### ISSUE TITLE
Authoryzacja Device Flow

### ISSUE THREAD

**Issue by ebsmario** [allegro/allegro-api#5226]
Witam, 
Rozpoczynam swoją przygodę z allegro-api i próbuję przeprowadzić integrację w modelu device flow. 
Zarejestrowałem aplikację, otrzymałem client id oraz client secret.

Mam następujące pytania:
czy wywołując stronę https://allegro.pl/auth/oauth/device podaję login i hasło użytkownika allegro czy coś innego? 
pozdrawiam
mario

**Comment by PrzemyslawLukanowski** [comment]
Nie jest to login i hasło użytkownika, w nagłówku Authorization musisz przekazać client_id i client_secret zakodowane przy pomocy Base64 - zgodnie z informacją z [naszego poradnika](https://developer.allegro.pl/auth/#device-flow-autoryzacja-u%c5%bcytkownika):

> Nagłówek HTTP: Authorization zawiera autoryzację typu Basic, z zawartością w formie client_id:client_secret (dane te otrzymałeś przy rejestracji aplikacji) zakodowane przy pomocy Base64. Pamiętaj aby zakodować całość danych client_id:client_secret wraz ze znakiem “:” pomiędzy wartościami.

**Comment by ebsmario** [comment]
Rozumiem, 
czyli zgodnie z instrukcją wywołuję: 
curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'

następnie w responce przychodzi device_code i user_code na który muszę się zalogować do https://allegro.pl/auth/oauth/device
 plus parametry które są opcjonalne.

**Comment by PrzemyslawLukanowski** [comment]
Tzn. user_code użytkownik będzie musiał wpisać na stronie z "verification_uri", czyli https://allegro.pl/skojarz-aplikacje. Po tym, jak użytkownik skojarzy aplikację, wartość dla device code aplikacja powinna wysłać w parametrze dla https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}.

**Comment by ebsmario** [comment]
przykładowy curl w dokumentacji jest prawidłowy? 
curl -X POST \
  'https://allegro.pl/auth/oauth/device' \
  -H 'Authorization: Basic {base64(client_id:client_secret)}' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id={client_id}'

**Comment by PrzemyslawLukanowski** [comment]
Tak, jest prawidłowy. Czy otrzymujesz jakiś błąd?

**Comment by ebsmario** [comment]
zweryfikuję, miałem problem z autoryzacją.
serdecznie dziękuję za pomoc.
________________________________

**Comment by janciupaga** [comment]
chwilowo otrzymuję 401:
Server returned HTTP response code: 401 for URL: https://allegro.pl/auth/oauth/device

**Comment by janciupaga** [comment]
działa, jest logowanie...

**Comment by janciupaga** [comment]
Autryzacja ok, wszystko zaczyna śmigać. level 1 zaliczony.
Teraz pytanie: 
w dokumentacji https://developer.allegro.pl/my_offers/#cena
wywołując zmianę w `PUT /sale/offer-price-change-commands/{commandId}`
mogę zmienić np. tylko cenę 
a jak jest w `PUT /sale/offers/{offerId}`
czy tutaj również mogę zmienić tylko cenę podając parametr w body bo w dokumentacji jest taka informacja:
`Uwaga! Nawet jeśli aktualizujesz wartość tylko w jednym polu, to musisz przesłać pełną strukturę pól oferty, łącznie z numerem oferty.`

**Comment by PrzemyslawLukanowski** [comment]
W PUT /sale/offers/{offerId} musisz przekazać całą strukturę oferty, nawet te pola, dla których nie zmieniasz wartości. Możesz jednak korzystać z [PATCH /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation/#operation/editProductOffers) i w ten sposób wysyłać tylko te pola, które modyfikujesz. Więcej informacji na ten temat znajdziesz [w naszym poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%C4%87-ofert%C4%99).
