### ISSUE TITLE
API about  "Funds & Operations history" &“Settlements with Allegro

### ISSUE THREAD

**Issue by bingnew** [allegro/allegro-api#5228]
Dear Allegro partners,

I want to obtain "Funds & Operations history" &“Settlements with Allegro”data through API and download report data. Is this the interface? https://developer.allegro.pl/documentation/#tag/Payments
![B6FCCDCD-D7BE-4d18-8120-BED7744E4CBA](https://user-images.githubusercontent.com/72594584/144976629-7ee7721c-e8c8-4c45-af34-da5ca44728bd.png)
![image](https://user-images.githubusercontent.com/72594584/144976881-70282d83-ae22-495e-a06e-eef2f9d396e7.png)

I look forward to your reply and wish you a great day.

**Comment by Lukasz-Zurek** [comment]
The first screen shows "Funds & Operations history" which you will find in our API as [GET /payments/payment-operations](https://developer.allegro.pl/en/documentation/#operation/getPaymentsOperationHistory). You will find more information [in our tutorial](https://developer.allegro.pl/en/charges/#payment-operations).

The second screen shows "Settlements with Allegro" which you will find in our API as [GET /billing/billing-entries](https://developer.allegro.pl/en/documentation/#operation/getBillingEntries). You will also find more information [in our tutorial](https://developer.allegro.pl/en/charges/#billing-operations).

Have a nice day too.

**Comment by bingnew** [comment]
Thank you for your prompt reply.
how about the interface for downloading invoices? Is there a related interface?
![image](https://user-images.githubusercontent.com/72594584/144982493-d6df26f5-bb95-4204-ab37-261892b86045.png)

**Comment by Lukasz-Zurek** [comment]
No, we do not have that kind of resource in our API.
