### ISSUE TITLE
identifiesProduct to nie to samo co describesProduct

### ISSUE THREAD

**Issue by skoruppa** [allegro/allegro-api#5233]
Występuje problem: 
 - [x] z zasobem REST API
 - [ ] ze środowiskiem produkcyjnym
 - [x] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**
Jak rozpoznać który parametr będzie służyć do identyfikacji produktu? 
Według 
GET https://api.allegro.pl.allegrosandbox.pl/sale/categories/6091/parameters
sprawdzam parametry **5174** i **248936**
```{
            "id": "5174",
            "name": "Dodatkowe informacje",
            "type": "dictionary",
            "required": false,
            "requiredForProduct": false,
            "unit": null,
            "options": {
                "variantsAllowed": true,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "dictionary": [
                {
                    "id": "5174_32",
                    "value": "Foil",
                    "dependsOnValueIds": []
                },
                {
                    "id": "5174_810013",
                    "value": "Without Foil",
                    "dependsOnValueIds": []
                }
            ],
            "restrictions": {
                "multipleChoices": true
            }
        },
{
            "id": "248936",
            "name": "Producent",
            "type": "dictionary",
            "required": true,
            "requiredForProduct": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": "248936_970286",
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": true
            }
```
_Producent_ ma **requiredForProduct** oraz **describesProduct** na **true**, a _Dodatkowe informacje_ (który definiuje czy karta jest foil czy nie), ma pierwsze na **false** a drugie na **true**. Spodziewałbym się że chociaż jeden z nich identyfikuje produkt jednak według 
GET https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=Ore+Gorger&category.id=6092
```
{
                    "id": "248936",
                    "name": "Producent",
                    "valuesLabels": [
                        "Wizards of the coast"
                    ],
                    "valuesIds": [
                        "248936_970283"
                    ],
                    "values": null,
                    "unit": null,
                    "options": {
                        "identifiesProduct": false
                    }
                },
{
                    "id": "5174",
                    "name": "Dodatkowe informacje",
                    "valuesLabels": [
                        "Without Foil"
                    ],
                    "valuesIds": [
                        "5174_810013"
                    ],
                    "values": null,
                    "unit": null,
                    "options": {
                        "identifiesProduct": false
                    }
                }
```
oba parametry nie identyfikują produktu. Natknąłem się na problem kiedy chciałem dodać dwie karty, jedną z foil, drugą bez wraz z przypisanym produktem co oczywiście skończyło się błędem 409. Według mnie parametr foil powinien definiować produkt ponieważ w zależności od niego cena karty jest zupełnie inna (tak jak jest to często z kolorami dla produktów)

Czy jest możliwość zmiany **identifiesProduct** na **true** dla parametru 5174 w wszystkich kategoriach dla ktorych rodzicem jest kategoria 6066? Czy też powinienem nie dodować tego parametru dla produktów i później ustalać go dopiero w ofercie?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję Twoją sugestię z odpowiednim zespołem, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Nie możemy oznaczyć tego parametru jako identyfikujący produkt - naszym zdaniem produktem jest sama karta. W tym przypadku nie powinieneś przekazywać tego parametru, gdy tworzysz nowy produkt, ale ustalić go dopiero w ofercie.
