### ISSUE TITLE
BAD_REQUEST On  sale/product-offers

### ISSUE THREAD

**Issue by qqc168** [allegro/allegro-api#5234]
In sandbox  Environment

post  url：https://api.allegro.pl.allegrosandbox.pl/sale/product-offers

request data:

 {
"productSet": [{
  "product": {                      
        "name": "Test product",
        "category":{
                "id":"42540aec-367a-4e5e-b411-17c09b08e41f"
        },
    "parameters":[
        
    ],
    "images":[

            "https://…first-image-address.jpeg"
    ]
}}],
"sellingMode": {
        "price": {
            "amount": "220.85",

            "currency": "PLN"
        }
},
 "stock": {
        "available": 10

}
}

==================================

Response  data

{
    "errors": [
        {
            "code": "BAD_REQUEST",
            "message": "Message is not readable.",
            "details": null,
            "path": "request.body",
            "userMessage": "Invalid request. Please contact the application author."
        }
    ]
}

====================
Please help to see what the reason is, thank you

**Comment by Lukasz-Zurek** [comment]
@qqc168 I have checked your request and I see that you have provided **"category.id"="42540aec-367a-4e5e-b411-17c09b08e41f"**, but selected category is not a category of the lowest level. You should provide the lowest tier category id. So if you use [GET /sale/categories](https://developer.allegro.pl/en/documentation/#operation/getCategoriesUsingGET), you will retrieve IDs of main Allegro categories. Use the identifiers to get to the lowest tier category. To do that, please use [GET /sale/categories?parent.id={categoryId}](https://developer.allegro.pl/en/documentation/#operation/getCategoryUsingGET_1).

The second thing is - if you choose a specific category id, you should provide product data which describe your product, e.g. the parameters. Or you can provide in your request EAN code (or product ID) if you already have this data.

The response status which you have received - seems to be different than mine. I have received an 422 error (I have only replaced your image url). Please make sure you sent us the same request you sent and received the mentioned response.
