### ISSUE TITLE
How do I map and associate the channels in the order details with the channels in the available carriers?

### ISSUE THREAD

**Issue by Lyta1enT** [allegro/allegro-api#5235]
This is the channel ID and name in the order details
![image](https://user-images.githubusercontent.com/94499471/145129866-b9e8d2c8-4063-4ec0-899e-948b61a9d526.png)
This is the channel ID and name of the available carriers
![image](https://user-images.githubusercontent.com/94499471/145130266-75ef0bf9-9538-4437-9df5-fc1c9c4718ed.png)

**Comment by Lukasz-Zurek** [comment]
We do not have any resource to map a **delivery.method** from the order details with available carrier. But we do have [a special table in our guide](https://developer.allegro.pl/en/wza/#how-to-create-a-new-parcel) which presents cases where the delivery method selected by the buyer affects the delivery service you can choose. So you have to assign the delivery service to a given shipment, depending on the contract on which you are sending the package.

If you create a new parcel, please use the **pickup.pointId** and **receiver.pointId** fields, fill them with the value taken from the API of the appropriate carrier. You will have to map it by your own.

You will find more information in [our guide](https://developer.allegro.pl/en/wza/#how-to-create-a-new-parcel).

**Comment by Lyta1enT** [comment]
Can I write the&nbsp;delivery.method.id obtained from the order in the program to determine which channel to choose? If possible, can you provide an enumeration of the IDs of these channels in the order details?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] How do I map and associate the channels in the order details with the channels in the available carriers? (Issue #5235)





 
We do not have any resource to map a delivery.method from the order details with available carrier. But we do have a special table in our guide which presents cases where the delivery method selected by the buyer affects the delivery service you can choose. So you have to assign the delivery service to a given shipment, depending on the contract on which you are sending the package.
 
If you create a new parcel, please use the pickup.pointId and receiver.pointId fields, fill them with the value taken from the API of the appropriate carrier. You will have to map it by your own.
 
You will find more information in our guide.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lukasz-Zurek** [comment]
You can use [GET sale/delivery-methods](https://developer.allegro.pl/en/documentation/#operation/getListOfDeliveryMethodsUsingGET) together with [GET /order/carriers](https://developer.allegro.pl/en/documentation/#operation/getOrdersCarriersUsingGET) to map the delivery methods in your program. 

To clarify my last message - I have mentioned about the table above but it is helpful to manage parcels via [Send with Allegro](https://developer.allegro.pl/en/wza/).
