### ISSUE TITLE
PATCH /sale/product-offers/{offerId} - zmiana stanu i czasu wysyłki powoduje m.in. walidacje opisu i paramterów

### ISSUE THREAD

**Issue by MarcinSzyszka** [allegro/allegro-api#5236]
Występuje problem: 
 - [ X ] z zasobem REST API
 - [ X ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

Dzień dobry. 
Zmieniam stan i czas wysyłki w ofertach w statusie ACTIVE z uzyciem PATCH /sale/product-offers/{offerId} (schema application/vnd.allegro.beta.v3+json) - w request body przekazuje jedynie pola Delivery i Stock. Dla wielu ofert dostaje w zwrotce informacje o błędach walidacji np. opisów czy parametrów.
Przykłady:

Calling allegro api url: /sale/product-offers/10745372872. Invalid response status code: UnprocessableEntity. Conent: {"errors":[{"code":"ConstraintViolationException.ValidOfferName","message":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy.","details":"ConstraintViolationException.ValidOfferName","path":"description.id","userMessage":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy."}]}

Calling allegro api url: /sale/product-offers/10745375929. Invalid response status code: UnprocessableEntity. Conent: {"errors":[{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 130152, 214982","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"Uzupełnij parametry obowiązkowe: Rodzaj, Materiał."},{"code":"ConstraintViolationException.ValidOfferName","message":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy.","details":"ConstraintViolationException.ValidOfferName","path":"description.id","userMessage":"Z opisu Twojej oferty wynika, że kupujący powinien się z Tobą skontaktować. Jeżeli zapis dotyczy kontaktu po zakupie przenieś go do zakładki „O Sprzedającym”. Zachęcanie do kontaktu przed zakupem nie jest dozwolone, ponieważ może skutkować sfinalizowaniem transakcji poza Allegro. Usuń z opisu niedozwolone zapisy."}]}

Gdybym dokonywał zmiany tych danych to te błeęy byłyby zasadne, jesli jednak nie zmieniam tych danych, a jedynie stan i czas wysyłki to czemu nie mogę tego zrobic ze względu na walidacje innych danych, których nie dotykam? Przeciez oferty są juz wystawione więc skoro pozwalacie dodac ofertę z błedami (wg responsu z api) to czemu już nie pozwalacie zedytowac jej innych danych? W schemie (application/vnd.allegro.beta.v3+json) jest słowko beta więc rozumiem, że to zasób który dopiero rozwijacie? Czy jest szansa aby walidowac jedynie dane, które są w requeście, a nie cała ofertę? Albo jakiś inny sposób aby to osiagnąć?

Pozdrawiam,
Marcin Szyszka.

**Comment by Lukasz-Zurek** [comment]
Wskazana oferta najwyraźniej została wystawiona przed włączeniem przez nas walidacji tegu typu niedozwolonych treści w opisie oferty, stąd zaistniała sytuacja jest prawidłowa, tzn. w momencie próby edycji - zwracamy błąd w walidacji podczas próby wystawienia oferty. Identyczna sytuacja pojawiłaby się podczas wystawiania/edycji oferty w formularzu (lub z poziomu moich ofert) na Allegro.pl.

Niestety nie ma możliwości walidacji samej treści w requeście. Zasób ten jest złożony i po walidacji żądania, następuje walidacja oferty pod kątem treści i obowiązkowych parametrów.

**Comment by MarcinSzyszka** [comment]
Ok, dziekuję.
Przekażę odpowiedź klientowi.

Pozdrawiam
