### ISSUE TITLE
About the interface to reverse the order status

### ISSUE THREAD

**Issue by Lyta1enT** [allegro/allegro-api#5238]
Regarding the interface for reversing the order status, can you help me see if there is a problem with my request? I think it should be the value in Content-Type. If so, what value should be filled in?
![c6f72ec5c6cb92ad2612ef448c167a8](https://user-images.githubusercontent.com/94499471/145198818-7377054c-ab3e-4d56-b834-810aa3d23b76.png)

Response:
{
  "errors": [{
    "code": "ERROR",
    "message": "Bad Request",
    "details": null,
    "path": null,
    "userMessage": "Bad Request"
  }]
}

**Comment by PrzemyslawLukanowski** [comment]
Try to change `'` sign to `"` in your request structure - `{"status": "READY_FOR_SHIPMENT", "shipmentSummary; {"lineItemsSent": "ALL"}}`. The value in the content-type header is valid.

**Comment by Lyta1enT** [comment]
Send me a request dome,Please
thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上7:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] About the interface to reverse the order status (Issue #5238)





 
Try to change ' sign to " in your request structure - {"status": "READY_FOR_SHIPMENT", "shipmentSummary; {"lineItemsSent": "ALL"}}. The value in the content-type header is valid.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PrzemyslawLukanowski** [comment]
```
curl --location --request PUT 'https://api.allegro.pl/order/checkout-forms/{orderId}/fulfillment' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer  {token}' \
--data-raw '{"status": "READY_FOR_SHIPMENT", "shipmentSummary": {"lineItemsSent": "ALL"}}'
```

**Comment by Lyta1enT** [comment]
This is my request,the same as yours
curl -X PUT -k&nbsp;
-i 'https://api.allegro.pl/order/checkout-forms/{orderId}/fulfillment'
-H 'Authorization: Bearer {token}'&nbsp;
-H 'Content-Type: application/vnd.allegro.public.v1+json'&nbsp;
-H 'Accept: application/vnd.allegro.public.v1+json'&nbsp;&nbsp;
--data '{'\''status'\'':'\''READY_FOR_SHIPMENT'\'','\''shipmentSummary'\'':{'\''lineItemsSent'\'':'\''ALL'\''}}'







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] About the interface to reverse the order status (Issue #5238)





 curl --location --request PUT 'https://api.allegro.pl/order/checkout-forms/{orderId}/fulfillment' \ --header 'Accept: application/vnd.allegro.public.v1+json' \ --header 'Content-Type: application/vnd.allegro.public.v1+json' \ --header 'Authorization: Bearer  {token}' \ --data-raw '{"status": "READY_FOR_SHIPMENT", "shipmentSummary": {"lineItemsSent": "ALL"}}'  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PrzemyslawLukanowski** [comment]
And you still receiving an error? Can you send me your orderId?

**Comment by Lyta1enT** [comment]
This is my orderId d188b0f1-5796-11ec-b735-130190065931


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月8日(星期三) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] About the interface to reverse the order status (Issue #5238)





 
And you still receiving an error? Can you send me your orderId?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PrzemyslawLukanowski** [comment]
There must be something wrong with the text formatting on your side. The structure isn't exactly the same - you are using double `'` instead of `"`. Make sure your JSON is sent in the following form: 
`{"status": "READY_FOR_SHIPMENT", "shipmentSummary; {"lineItemsSent": "ALL"}}`
