### ISSUE TITLE
Wrong reversal of order waybill number

### ISSUE THREAD

**Issue by Lyta1enT** [allegro/allegro-api#5239]
Can you help me see why this error occurs?
![image](https://user-images.githubusercontent.com/94499471/145320694-5a073937-d653-45dc-9c70-d657aa8ca9c3.png)

{
  "errors": [{
    "code": "AccessDenied",
    "message": "Access is denied",
    "details": null,
    "path": null,
    "userMessage": "Access denied. Contact the author of the application."
  }]
}

Access denied. Contact the author of the application.
Get a list of parcel tracking numbers this API and Add a parcel tracking number API，Have this problem

**Comment by Lukasz-Zurek** [comment]
@Lyta1enT It looks like you are using [**client_credentials**](https://developer.allegro.pl/auth/#client-credentials-flow) flow to authorize. This is an authorization method without the user context. You should use another authorization method, for example [code flow](https://developer.allegro.pl/en/auth/#app). All authorization methods are described in our [guide](https://developer.allegro.pl/en/).

**Comment by Lyta1enT** [comment]
If this is the case, should refresh tokens be used? But I still get an error when I use refresh token
response:{
&nbsp; "error": "invalid_token",
&nbsp; "error_description": "Encoded token is a refresh token"
}







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Wrong reversal of order waybill number (Issue #5239)





 
@Lyta1enT It looks like you are using client_credentials flow to authorize. This is an authorization method without the user context. You should use another authorization method, for example code flow. All authorization methods are described in our guide.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hahyes** [comment]
> If this is the case, should refresh tokens be used? But I still get an error when I use refresh token response:{ &nbsp; "error": "invalid_token", &nbsp; "error_description": "Encoded token is a refresh token" }
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "allegro/allegro-api" ***@***.***&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 下午2:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [allegro/allegro-api] Wrong reversal of order waybill number (Issue #5239) @Lyta1enT It looks like you are using client_credentials flow to authorize. This is an authorization method without the user context. You should use another authorization method, for example code flow. All authorization methods are described in our guide. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

You need to change whole authorization method, not use refresh token from client_credentials flow. Read about it in guide linked by developer.

**Comment by Lukasz-Zurek** [comment]
@Lyta1enT You cannot refresh token using access token, especially from client_credentials authorization flow, where extending token validity does not exist. Please read [our guide.](https://developer.allegro.pl/en/auth/#extending-token-validity). As @hahyes has already mentioned - you need to change the whole authorization method. We have introduced 4 authorization methods right [here](https://developer.allegro.pl/en/auth/#introduction). The most popular is [Authorization Code Flow](https://developer.allegro.pl/en/auth/#authorization-code-flow). Please look at this process closely.

**Comment by Lyta1enT** [comment]
I feel that Authorization Code Flow is a bit troublesome;
Can I use Device flow? If I get an access token using Device flow, can I use this access token? And is the refresh token I'm using now still useful?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Wrong reversal of order waybill number (Issue #5239)





 
@Lyta1enT You cannot refresh token using access token, especially from client_credentials authorization flow, where extending token validity does not exist. Please read our guide.. As @hahyes has already mentioned - you need to change the whole authorization method. We have introduced 4 authorization methods right here. The most popular is Authorization Code Flow. Please look at this process closely.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lukasz-Zurek** [comment]
Yes, you can use Device Flow, obviously it is up to you. You can use the access token which you have received in the Device Flow authorization process and then you should use new refresh token, which you have received together with access token. Everything is in [our guide](https://developer.allegro.pl/en/auth/#device-flow). 

Your current refresh token will be useful only if you decide to use current authorization. It will be not useful in your new Device Flow authorization process.

Please remember that the pair of tokens which you receive while extending token validity - are dependent on each other. You cannot use the refresh token to extend other access token validity.

**Comment by Lyta1enT** [comment]
The last question is, is the life cycle of access token and refresh_token the value in expires_in, and the unit is second?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "allegro/allegro-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [allegro/allegro-api] Wrong reversal of order waybill number (Issue #5239)





 
Yes, you can use Device Flow, obviously it is up to you. You can use the access token which you have received in the Device Flow authorization process and then you should use new refresh token, which you have received together with access token. Everything is in our guide.
 
Your current refresh token will be useful only if you decide to use current authorization. It will be not useful in your new Device Flow authorization process.
 
Please remember that the pair of tokens which you receive while extending token validity - are dependent on each other. You cannot use the refresh token to extend other access token validity.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lukasz-Zurek** [comment]
In [our guide](https://developer.allegro.pl/en/auth/#extending-token-validity) you will find an information that in the response, in **"expires_in":43199** field - we return only the validity time of **access token** (in seconds; a token is valid for 12 hours).

The **refresh_token** - is valid for 3 months and after first refresh, you can use it for another 60 seconds.
