### ISSUE TITLE
Pobieranie zamówień, rest api

### ISSUE THREAD

**Issue by jchodubska** [allegro/allegro-api#524]
Dzień dobry,
Próbuje skorzystać z metody Rest Api  GET /order/checkout-forms?limit=10&offset=9.
Jednak podczas pobierania kolejnych porcji danych pojawia się problem - offset przyjmuje wartości od 0 do liczba zamówień -1
Czy rest api pozwala na pobranie liczby wszystkich zamówień?

**Comment by jchodubska** [comment]
Zapoznałam się już z Waszym poradnikiem. Ale w przypadku gdy mam 70 zamówień, limit ustawiony jest na 100 a offset na 0, metoda nie pobiera żadnych zamówień. Działa tylko, gdy limit jest <= liczbie zamówień. 
Co z tym zrobić? Czy to błąd i zostanie on naprawiony?

**Comment by PawelTaberski** [comment]
Sprawdziłem i funkcja działa poprawnie. Jaki status odpowiedzi otrzymujesz?

**Comment by jchodubska** [comment]
Otrzymuje status 500, załączam screeny:

![image](https://user-images.githubusercontent.com/26299339/44711686-3a5d6c80-aaaf-11e8-8df1-4c989ae7371d.png)

![image](https://user-images.githubusercontent.com/26299339/44711712-49441f00-aaaf-11e8-95ed-3b0850af8fad.png)

**Comment by PawelTaberski** [comment]
Podeślij proszę przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1&kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619) pełnego cURL-a z requesta i pełnego responsa z tym błędem sprawdzimy w czym jest problem. Wklej tutaj potem numer ticketa.

**Comment by PawelTaberski** [comment]
Przetestowałem i rzeczywiście jest błąd w Twoim wypadku dla offsetu 300 dla 400 już nie ma tego błędu. Sprawę zgłosiłem do odpowiedniego zespołu proszę o cierpliwość.
