### ISSUE TITLE
Brak isGTIN przy parametrze EAN, publikacja oferty

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#5240]
Czy przy publikacji ofert powiązanych z produktami (`/sale/product/offers`) zawsze powinien być wysyłany parametr EAN (id: 225693), nawet jeśli nie jest oznaczony jako isGTIN w odpowiedzi na `GET /sale/categories/260304/parameters`?

Taka sytuacja występuje w kategorii "Dziecko ->  Zabawki ogrodowe -> Piaskownice i zabawki do piasku -> Zabawki do piasku".

W odpowiedzi na `/sale/products/bdb628a3-4316-4e6e-ac1d-03cbfb58258d` parametr EAN w ogóle nie występuje. To oznacza, że brakuje go w katalogu produktów?

**Comment by PrzemyslawLukanowski** [comment]
Pola `isGTIN `nie zwracamy w tym zasobie, wystąpi tylko przy parametrze EAN w szczegółach produktu. O tym, czy musisz przekazać wartość EAN, świadczą flagi `"required": true` (gdy wystawiasz nową ofertę) oraz `"requiredForProduct": true` (gdy tworzysz nowy produkt). Jeśli zatem korzystasz /sale/product-offers i tworzysz nowe produkty, zwróć uwagę na wartość w `"requiredForProduct"` dla parametru w danej kategori - jeśli wartość dla parametru to true, przekaż EAN w sekcji produktowej. 

Produkt bdb628a3-4316-4e6e-ac1d-03cbfb58258d nie posiada uzupełnionego parametru EAN.
