### ISSUE TITLE
Problem z aktualizacją parametru "Numer katalogowy części" (249034)

### ISSUE THREAD

**Issue by jakub-adamski** [allegro/allegro-api#5241]
Dzień dobry, 

Chciałbym dopytać, czy robię coś źle, czy może jednak jest jakiś drobny błąd w API. Otóż mam problem z aktualizacją parametru produktu 249034 (Numer katalogowy części) np. dla oferty o numerze 9183047496. Podczas próby aktualizacji ceny dla tej oferty, REST API zwróciło mi następujący błąd:

_Niepoprawna wartość parametru Numer katalogowy części (249034) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : "20-1040-05-2, 20-1039-05-2"._

Po pobraniu szczegółów tej oferty za pomocą zasobu "/sale/offers/9183047496" API rzeczywiście zwróciło mi dane tej oferty z parametrem o wartości "20-1040-05-2 20-1039-05-2" (czyli bez przecinka). Z tego, co rozumiem na bazie informacji powyżej, wartość ta powinna być z przecinkiem. 

W związku z tym próbowałem zaktualizować dane tej oferty za pomocą zasobu "/sale/product-offers/9183047496", jako wartość parametru 249034 ustawiłem "20-1040-05-2, 20-1039-05-2", ale niestety przy próbie aktualizacji serwer zwraca mi błąd o następującej treści: 

_status code: 422
code: PARAMETER_MISMATCH
message: The provided parameter 'Catalog Part Number'(249034) value (20-1040-05-2, 20-1039-05-2) does not match the existing parameter value (20-1040-05-2, 20-1039-05-2)_

Już po samej treści błędu widać, że coś jest nie tak. Upewniałem się kilkukrotnie, czy wartości są identyczne. Próbowałem też zamienić przecinek na "+", ale również bez efektu. Nie ma też możliwości usunięcia tego parametru i dodania na nowo (wyrzucą błąd, że jest wymagany).

Prosiłbym o sprawdzenie lub podpowiedź, jak zaktualizować ten parametr poprzez API.

Pozdrawiam,
Jakub

**Comment by PrzemyslawLukanowski** [comment]
`20-1040-05-2` i `20-1039-05-2` to dwie osobne wartości, dlatego przekaż je proszę w poniższej formie, a problem nie wystąpi:

```
    {
            "id": "249034",
            "valuesIds": [],
            "values": [
                "20-1040-05-2",
                "20-1039-05-2"
            ],
            "rangeValue": null
     }
```

Jeśli wykonasz request do GET /sale/products/ac74b62d-e352-4223-8ac9-0caa59316487, aby sprawdzić szczegóły produktu, parametry otrzymasz właśnie w takiej formie.

**Comment by jakub-adamski** [comment]
Zadziałało, dzięki za podpowiedź ;)
