### ISSUE TITLE
Jak zarejestrować nową aplikację

### ISSUE THREAD

**Issue by sklepArberi** [allegro/allegro-api#5242]
Dzień dobry,

Chcę zarejestrować nową aplikację. Na stronie https://developer.allegro.pl/getting_started/#jak-zarejestrowa%c4%87-now%c4%85-aplikacj%c4%99 jest podana instrukcja, jak to zrobić na środowisku testowym. Pytanie: 1) czy mogę testować aplikacje zarejestrowaną na głównym koncie sklepu (ponieważ za dużo informacji do podania wymaga konto na środowisku testowym)? 2) po co tyle informacji wymaga ode mnie allegro dla założenia konta na środowisku testowym? i jakie plusy z korzystania konta na środowisku testowym?
------------------------------------
Jak zarejestrować nową aplikację

Aby zacząć korzystać z REST API Allegro, najpierw zarejestruj swoją aplikację na naszym portalu deweloperskim. Na potrzeby tego poradnika będziemy rejestrować aplikację na środowisku testowym.

Przejdź do strony https://apps.developer.allegro.pl.allegrosandbox.pl/new i zaloguj się danymi swojego konta Allegro ze środowiska testowego. Jeśli nie masz jeszcze konta na środowisku testowym, możesz je założyć na stronie rejestracji konta.

**Comment by Lukasz-Zurek** [comment]
1) Tak, jak najbardziej. Decyzja należy do Ciebie.
2) Środowisko testowe ma odzwierciedlać w pełni środowisko produkcyjne, dlatego rejestrując tego typu konto, wypełniasz formularz identyczny jak ten dostępny w wersji produkcyjnej. Proces aktywacji, weryfikacji firmy również działa analogicznie jak na produkcji - jest to jednak proces bardziej automatyczny. Podobnie jak korzystanie z symulatora płatności podczas dokonywania testowych zakupów czy też regulowania zaległości w "Rozliczenia z Allegro". Ma to ułatwić proces testowania naszych funkcjonalności.

Jakie są plusy z korzystania z konta na środowisku testowym ? Przede wszystkim poznajesz funkcjonowanie Serwisu Allegro. Kupujesz i sprzedajesz. Natomiast za pośrednictwem Allegro API (na sandboxie) weryfikujesz pobierane dane np. w ramach zamówień, wystawionych ofert i możliwości z tym związanych w kontekście udostępnianych przez nas zasobów, których dokładny opis znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/documentation/) oraz w [poradniku](https://developer.allegro.pl/sale/). Testowanie funkcjonalności w naszym API, na środowisku testowym, z pewnością pomoże Tobie podczas integracji w wersji produkcyjnej API Allegro.

**Comment by Lukasz-Zurek** [comment]
Doprecyzuję jeszcze punkt 1. Aby testować możliwości API Allegro na środowisku testowym, wymagane jest założenie konta w serwisie: https://allegro.pl.allegrosandbox.pl. W tym celu skorzystaj z [tego formularza](https://allegro.pl.allegrosandbox.pl/rejestracja).

**Comment by sklepArberi** [comment]
Dziękuje za odpowiedź

**Comment by robboh** [comment]
Witam, mam założone i aktywowane konto w sandbox. Mail z potwierdzeniem aktywacji otrzymałem 2020-01-08
Kiedy próbuję odzyskać hasło  przez https://allegro.pl.allegrosandbox.pl/logowanie/ustalanie-nowego-hasla/email
pomimo informacji o wysłaniu linku z nowym hasłem, maile nie nadchodzą. 
Skrzynka email działa, przychodzą wiadomości testowe z innych kont.
Użytkownik e-autoparts_pl

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie mogę potwierdzić problemu, przed chwilą wygenerowałem prośbę o zmianę hasła na koncie i otrzymałem maila. Wg naszych logów, maile na Twoją skrzynkę w dniu 11.12.21 wysyłaliśmy w poniższych godzinach:

- 15:45:22	
- 15:43:26	
- 15:32:38	
- 14:32:35	
- 14:09:20	
- 14:08:14

Upewnij się proszę, czy wiadomość nie trafiła do spamu lub czy Twoja skrzynka pocztowa w inny sposób nie blokuje wiadomości, które zawierają załącznik w formacie .eml.

**Comment by robboh** [comment]
Dziękuję za pomoc,
pomogło usunięcie filtrowania plików eml w 
/etc/system_filter.exim
