### ISSUE TITLE
Problem z dostępem do GET /offers/listing

### ISSUE THREAD

**Issue by k0rba** [allegro/allegro-api#5244]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

trace-id: c8fb2c8b49442cd8

Od ponad dwóch tygodni nie mam dostępu do GET /offers/listing pomimo tego, że moja aplikacja jest zweryfikowana (wiadomość z 29.05.2021, zgłoszenie 14049822). Próby kontaktu przez formularz (zgłoszenie 19074388, jest tam przykładowe zapytanie i odpowiedź) spełzły na niczym. W odpowiedzi otrzymuję albo nieprawdziwe informacje, albo stosowana jest spychologia, albo odpowiedzi nie otrzymuję wcale. Chciałbym się dowiedzieć co mam zrobić, żeby w końcu rozwiązać ten problem i komu zawdzięczam takie traktowanie.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację, że w przytoczonym przez Ciebie zgłoszeniu 14049822 wysyłaliśmy plik z danymi do uzupełnienia do umowy, jednak nie otrzymaliśmy odpowiedzi. Dzisiaj wysyłamy plik jeszcze raz.

**Comment by k0rba** [comment]
Znowu nie jest to prawda. Plik z danymi wysłałem 22.07.2021 i tego samego dnia otrzymałem potwierdzenie otrzymania go przez Allegro. Dalszej korespondencji w wątku 14049822 nie było.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, przepraszam za niedogodności. Otrzymałem informację, że umowa zostanie do Państwa wysłana w najbliższym czasie i tym samym przywrócimy dostęp do zasobu.

**Comment by PrzemyslawLukanowski** [comment]
Wczoraj wysłaliśmy umowę do podpisu.

**Comment by k0rba** [comment]
Nic nie dostałem. Niemniej bardziej interesuje mnie, kiedy odzyskam dostęp do zasobu?

**Comment by PrzemyslawLukanowski** [comment]
Dostęp odzyskasz po podpisaniu umowy, wysłaliśmy ją na adres z dokumentu, zarejestrowany w domenie @cbros.com.

**Comment by k0rba** [comment]
Nie chce mi się już pisać "i znowu nieprawda" bo rozumiem, że nie jest Pana celem wprowadzenie mnie w błąd. Jak wspomniałem wcześniej, nic nie dostałem. Ani wczoraj, ani dziś. Ani jako odpowiedź w wątku 19074388, ani w wątku 14049822. Tak, sprawdziłem folder ze spamem. I tak, adres e-mail działa poprawnie.

**Comment by PrzemyslawLukanowski** [comment]
@k0rba Otrzymałem informację, że umowa została podpisana dziś w godzinach porannych. Czy możesz to potwierdzić?

**Comment by k0rba** [comment]
Tak, mogę. Niemniej nadal czekam na odpowiedź z pierwszej wiadomości w tym wątku: komu lub czemu zawdzięczam, że rozwiązanie problemu, który można było wyjaśnić w ciągu kilku godzin zajęło prawie miesiąc?

W ciągu tych czterech tygodni komuś nie chciało się kiwnąć palcem w tej sprawie i wykazać odrobiną dobrej woli. Tym bardziej, że problem powstał nie z mojej winy a w wyniku zaniedbania pracownika Allegro. Więcej, w tym czasie przekazywane mi były fałszywe informacje: że dostęp został przywrócony, że nie dostarczyłem żądanych danych. Nawet informacja, że umowa została wysłana w poniedziałek, była nieprawdziwa: ta została wysłana w środę o godzinie 5:28.

Jako ciekawostkę dodam, że sprawa dotyczy najstarszego serwisu udostępnianego użytkownikom Allegro. W poniedziałek skończył 20 lat. I chociaż nie był to pierwszy problem, to po raz pierwszy spotkałem się z tak lekceważącym traktowaniem.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszamy za wszelkie niedogodności, które napotkałeś po drodze, dołożymy wszelkich starań, aby podobne sytuacje nie miały miejsca.
