### ISSUE TITLE
Cannot convert access token to JSON

### ISSUE THREAD

**Issue by qshop123** [allegro/allegro-api#5246]
Występuje problem: 
 - [x] z zasobem REST API
 - [x] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

:beetle: **Opis**

Przy wywołaniu na produkcji metody https://api.allegro.pl/sale/categories/4135/parameters dostaję odpowiedź 

{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}

Co ciekawe u innych klientów to działa poprawnie. 
Zrzut : 
array (
  'options' => 
  array (
    'http' => 
    array (
      'method' => 'GET',
      'header' => 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6Ikp....
Content-Type: application/vnd.allegro.public.v1+json
Accept: application/vnd.allegro.public.v1+json',
      'content' => '[]',
      'ignore_errors' => true,
    ),
  ),
  'url' => 'https://api.allegro.pl/sale/categories/4135/parameters',
  'response' => '{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}',
)

Authorization: Bearer wrzucony do dekodera i pokazuj expiration date 1639255488 więc to nie problem z wygaśnięciem
JTI : 6e5e90e0-98ac-4a3a-a6fe-f109988495be

Sławek

**Comment by PrzemyslawLukanowski** [comment]
Prawdopodobna przyczyna wystąpienia błędu to:
- używasz tokena ze środowiska testowego na produkcyjnym,
- Twoja aplikacja "ucina" część tokena podczas wywołania, np. kilka ostatnich znaków.

Możesz wysłać nam przykładowy request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c). Dopisz wtedy, że dane dotyczą wątku #5246 na Githubie, zweryfikujemy to.

**Comment by qshop123** [comment]
Dzień dobry
1) używasz tokena ze środowiska testowego na produkcyjnym - Nie, używam tokena z produkcji na produkcji
2) Twoja aplikacja "ucina" część tokena podczas wywołania, np. kilka ostatnich znaków. - nie ucina,

**Comment by PrzemyslawLukanowski** [comment]
Czy w takim razie przekazałeś nam przykładowe dane wraz z tokenem przez formularz?

**Comment by qshop123** [comment]
Tak, wysłałem dane z poprzedniego dnia oraz z dzisiaj po logowaniu.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, wrócę z informacją, gdy otrzymamy dane i zweryfikujemy sytuację.

**Comment by qshop123** [comment]
200 OK

**Comment by qshop123** [comment]
Jak tam nasze sprawy?

**Comment by PrzemyslawLukanowski** [comment]
Czy mógłbyś podać numer zgłoszenia, który otrzymałeś w odpowiedzi?

**Comment by PrzemyslawLukanowski** [comment]
Token, który przekazywałeś w requeście był zbyt krótki, co wskazuje na to, że Twoja aplikacja "ucięła" fragment końcowych znaków w nim zawartych.
