### ISSUE TITLE
Szablon aukcji, brak dostepu do allegro api

### ISSUE THREAD

**Issue by versgue** [allegro/allegro-api#5248]
Dzień dobry. Potrzebuje pobrać opis aukcji jako szablon, ale niestety nie mam dostępu do allegro api? czy musze prosić o dostęp czy da się pobrać to w inny sposób? Zależy mi tylko na pobraniu sobie szablonu.

**Comment by PrzemyslawLukanowski** [comment]
Aby pobrać opis oferty, której jesteś właścicielem, musisz posiadać dostęp do API.
