### ISSUE TITLE
Miniaturka

### ISSUE THREAD

**Issue by krystianmagdziarz** [allegro/allegro-api#5249]
Dzień dobry,

- Czy są jakieś limity dotyczące zmiany miniaturki aukcji (zdjęcia głównego),
- Jak często jest to aktualizowane na stronach listingu (zakładam, że jest jakiś cache),
- Czy takie operacje wiążą się z jakąś opłatą?

Chciałbym programowo badać skuteczność miniaturek, czy macie do tego jakieś narzędzie?
Ewentualnie czy jest to możliwe do osiągnięcia poprzez API?

Dziękuję za odpowiedź.

**Comment by MaciejFrackowiak** [comment]
Zdjęcia w ofertach możesz zmieniać / dodawać zgodnie z wytycznymi z [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/jak-zmienic-szczegoly-oferty-po-jej-wystawieniu-3GBbgYX1RSn#licytacje). Zdjęcia są aktualizowane na bieżąco, musisz jednak wziąć pod uwagę, że serwis rozproszony jest na wielu serwerach, stąd operacja ta wymaga sama w sobie czasu. Nie udostępniamy żadnego narzędzia do monitorowania miniaturek.

**Comment by krystianmagdziarz** [comment]
Ok, dziękuje.
Najwyższa jakość wsparcia :).
