### ISSUE TITLE
Nie można zaplanować publikacji oferty w przeszłości

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#5251]
Witam.

W swojej [ bibliotece do obsługi API Allegro c# ](https://github.com/PiotrFerenc/Allegro-api-rest-client)  staram się "przenieść" ofertę ze szkiców do aktywny. 

Dostaję informacje o tym że publikuję zaplanować ofertę w przeszłości. 

Proszę o podpowiedz 

![image](https://user-images.githubusercontent.com/30370747/145973121-031fbbd0-3a46-49e0-88b0-1521c49a441e.png)

Task:
` https://api.allegro.pl/sale/offer-publication-commands/084da2df-6a8d-4644-9868-ac4144b587e4/tasks`

```json
{
    "tasks": [
        {
            "offer": {
                "id": "11387442664"
            },
            "message": "Could not change offer publication status. Nie można zaplanować publikacji oferty w przeszłości.",
            "status": "FAIL",
            "scheduledAt": "2021-12-14T09:34:52.775Z",
            "finishedAt": "2021-12-14T09:34:52.757Z",
            "field": "publication",
            "errors": [
                {
                    "code": "PublicationValidationException.IllegalChangeStatusInThePast",
                    "message": "You cannot schedule activating an offer in the past.",
                    "details": null,
                    "path": "publication.status",
                    "userMessage": "Nie można zaplanować publikacji oferty w przeszłości."
                }
            ]
        }
    ]
}
```

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem logi - 2021-12-14 10:34:52.607 zleciłeś komendę aktywacji oferty z zaplanowanym czasem scheduledFor=2021-12-14T08:39:54.269800900Z - czyli przenosząc do strefy polskiej planowanym czasem była 9:39:54 - czyli de facto termin już z przeszłości i dlatego otrzymałeś błąd "Nie można zaplanować publikacji oferty w przeszłości.".
