### ISSUE TITLE
Sandbox - proszę o weryfikację

### ISSUE THREAD

**Issue by devmiczal** [allegro/allegro-api#5252]
Witam,
proszę o weryfikację :)
login: devmiczal@gmail.com

code: "VALIDATION_ERROR"
details: "ConstraintViolationException.SellerAccountVerified"
message: "To activate sales please verify your account."
path: "seller"
userMessage: "Aby aktywować sprzedaż zweryfikuj konto."

Jak będę testować zapytania do api razem z dokumentacją to w większości przypadkach wystarczy zmienić początek linku na https://allegro.pl.allegrosandbox.pl?
i na koniec dodać ?lokalnie

**Comment by Lukasz-Zurek** [comment]
Aktywowałem Twoje konto.

Adres wywołania metod na środowisku testowym Sandbox, przez REST API, z jakiego powinieneś korzystać to: 

https://api.allegro.pl.allegrosandbox.pl/

Natomiast jeśli chcesz wystawić ofertę bezpośrednio przez stronę (na środowisku testowym), w przypadku konta zwykłego - skorzystaj z: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/about/#środowisko-testowe).

**Comment by devmiczal** [comment]
Dziękuje bardzo :)

miłego dnia :+1:

**Comment by devmiczal** [comment]
Dalej nie działa, ten sam komunikat.

**Comment by Lukasz-Zurek** [comment]
Ok, to zapewne z powodu niepełnych danych na koncie. Przejdź proszę przez formularz na [tej stronie](https://allegro.pl.allegrosandbox.pl/myaccount/FillData.php?fromCode=1).

**Comment by devmiczal** [comment]
Ok, działa teraz :) Dzięki :+1:

**Comment by BoyceYang** [comment]
Witam,
proszę o weryfikację :)
login: boyce_yang@163.com

code: "VALIDATION_ERROR"
details: "ConstraintViolationException.SellerAccountVerified"
message: "To activate sales please verify your account."
path: "seller"
userMessage: "Aby aktywować sprzedaż zweryfikuj konto."

find in https://apps.developer.allegro.pl.allegrosandbox.pl/ 

please help activate this account , thanks

**Comment by Lukasz-Zurek** [comment]
@BoyceYang I have already activated your account. 

You have chosen a company account, so to verify it, please send any two files via the [Account details](https://allegro.pl.allegrosandbox.pl/myaccount/mysettings.php) tab and complete all the data as well.
