### ISSUE TITLE
Problem z odświeżaniem tokenu

### ISSUE THREAD

**Issue by miecha3l** [allegro/allegro-api#5253]
Mamy bazę danych kont allegro na których operuje nasza usługa. Przechowujemy access_token, refresh_token i datę wygaśnięcia access_tokenu.

Odświeżaniem tokenu zajmuje się funkcja, która co 30 minut wybiera X kont, których access_token ma wygasnąć w ciągu najbliższych 2 godzin. Dla każdego z kont jest wykonywane jest standardowe zapytanie:
GET https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=X

W 95% przypadków system działa niezawodnie, natomiast spotkaliśmy się z przypadkami odrzucenia refresh_tokenu wygenerowanego tego samego dnia - odrzucony token jest identyczny do uzyskanego przy poprzednim odświeżeniu. Przykład w załącznikach.

Problem występuje losowo, nie jest powiązany z żadnym konkretnym kontem bądź grupami kont allegro. 
Wykluczyliśmy także możliwość ingerencji innych części systemu w proces odświeżania tokenu.

**Comment by Lukasz-Zurek** [comment]
@miecha3l Usuń proszę zrzuty,na których widoczne są dane wrażliwe.

Jednocześnie prześlij proszę cały refresh_token przez nasz formularz kontaktowy. W zgłoszeniu dopisz GitHub #5253. Zweryfikuję to.

**Comment by miecha3l** [comment]
@Lukasz-Zurek zgłoszenie wysłane

**Comment by Lukasz-Zurek** [comment]
@miecha3l Dziękuję za zgłoszenie. Sprawę przekazałem dalej do weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@miecha3l Podeślij proszę (w odpowiedzi na ostatnią wiadomość) nowe przykłady problematycznych refresh_tokenów z ostatnich 7 dni. Dla przesłanego wcześniej refresh_tokena nie mamy już niestety logów, dlatego nie uda nam się zweryfikować tego konkretnego przypadku.

**Comment by miecha3l** [comment]
@Lukasz-Zurek przesłane

**Comment by Lukasz-Zurek** [comment]
@miecha3l Bardzo Ci dziękuję.

**Comment by miecha3l** [comment]
@Lukasz-Zurek Wznawiam wątek. Przesłałem drogą mailową kolejny RT, tym razem z przed 5ciu dni (z 31.12.2021) - to najnowszy przypadek jaki udało mi się znaleźć.

**Comment by Lukasz-Zurek** [comment]
@miecha3l Ok, dziękuję. Jak tylko otrzymam tę wiadomość - zweryfikuję przesłany przypadek w jak najkrótszym czasie.

**Comment by Lukasz-Zurek** [comment]
@miecha3l Zweryfikowałem już Twoje zgłoszenie. Wskazany refresh_token został unieważniony, ponieważ 2021-12-30 19:57:58 - odnotowaliśmy zmianę hasła na koncie. W takiej sytuacji połączenie z API Allegro jest przerywane.

**Comment by miecha3l** [comment]
Dziękuję za weryfikację oraz informację. Czy są inne, analogiczne przypadki, w których refresh_token może zostać unieważniony?

**Comment by Lukasz-Zurek** [comment]
Tak. Token zostaje unieważniony w przypadku:

- wylogowania się ze wszystkich urządzeń (np. poprzez zakładkę [Logowanie i hasło](https://allegro.pl/moje-allegro/moje-konto/logowanie-i-haslo)), 
- zmiany hasła,
- zmiany adresu e-mail,
- blokady sprzedaży,
- w wyniku przekroczenia liczby aktywnych sesji (max. 20 otwartych sesji dla jednego użytkownika).

**Comment by miecha3l** [comment]
max. 20 otwartych sesji dla jednego użytkownika - co to dokładnie oznacza?

**Comment by Lukasz-Zurek** [comment]
@miecha3l Limit ten oznacza, że może być maksymalnie 20 jednocześnie zalogowanych użytkowników/osób na jednym koncie Sprzedawcy. Przykładem może być mniejszy Sprzedawca, z którego konta korzysta kilkunastu pracowników.

**Comment by miecha3l** [comment]
Dziękuję, uważam że temat został wyczerpany, zamykam zgłoszenie.
