### ISSUE TITLE
Problem z marką przy wystawianiu oferty z produktyzacją - pole zawiera niedozwolone znaki

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#5254]
**Kategoria**: Zabawki -> Lalki i akcesoria -> Lalki -> Lalki hiszpańskie (id: 259356)
**Produkt**: 28e5fd7d-8452-4e95-83c5-24948c3821c6
**Parametry wysyłane w requeście:**
`{"name":"Lalka hiszpa\u0144ska","afterSalesServices":{"impliedWarranty":{"id":"d1a12b3e-9fb9-4b86-a786-9da8032cac65"},"returnPolicy":{"id":"39561da4-dbe9-4257-8ca1-96b329c0de17"}},"compatibilityList":null,"contact":null,"sellingMode":{"format":"BUY_NOW","minimalPrice":null,"price":{"amount":"369","currency":"PLN"},"startingPrice":null},"stock":{"available":1,"unit":"UNIT"},"promotionToFeesPreview":{"bold":false,"departmentPage":false,"emphasized":false,"highlight":false,"emphasizedHighlightBoldPackage":false},"payments":{"invoice":"NO_INVOICE"},"location":{"city":"Warszawa","countryCode":"PL","postCode":"40-001","province":"DOLNOSLASKIE"},"images":[],"additionalServices":null,"attachments":null,"external":{"id":"0$sky_63_1639565848_257814"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Produkt testowy - nie kupowa\u0107<\/p>\n"}]}]},"delivery":{"additionalInfo":"","handlingTime":"P2D","shipmentDate":null,"shippingRates":{"id":"d896b35e-6cc8-4146-9937-66fbc5d92773"}},"publication":{"duration":"P20D","status":"INACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":null},"parameters":[{"id":"11323","rangeValue":null,"values":null,"valuesIds":["11323_1"],"type":4}],"id":null,"category":{"id":"259356"},"productSet":[{"product":{"id":"28e5fd7d-8452-4e95-83c5-24948c3821c6","parameters":[],"category":{"id":"259356"}}}],"productId":63}`

**W odpowiedzi dostaję błąd:** `{"code":"OfferCustomParametersException","message":"Invalid custom value: provided string contains illegal characters","details":null,"path":"productSet[0].product.parameters","userMessage":"To pole zawiera niedozwolone znaki"}`

W katalogu produkt ma uzupełnioną markę "inna (Muñecas Guca)", valuesIds: 127812_24, więc jej nie wysyłam w zapytaniu.

Co powoduje ten błąd? W treści odpowiedzi brakuje szczegółowych informacji.

**Comment by hahyes** [comment]
Jestem w pełni przekonany, że to `ñ` wywołuje problem.

**Comment by krowek** [comment]
@hahyes całkiem możliwe natomiast ja tej wartości nie wysyłam w zapytaniu. Jest już ona zapisana przy produkcie w katalogu, więc nie wiem skąd taka walidacja.

**Comment by Lukasz-Zurek** [comment]
@krowek Problem przekazałem dalej do weryfikacji. Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by hahyes** [comment]
> całkiem możliwe natomiast ja tej wartości nie wysyłam w zapytaniu. Jest już ona zapisana przy produkcie w katalogu, więc nie wiem skąd taka walidacja.

@krowek Walidacja przy wystawianiu ofert sprawdza całą zawartość oferty. Podejrzewam, że walidacja proponowania produktów przepuściła ten znak, chociaż nie powinna.

**Comment by Lukasz-Zurek** [comment]
@krowek Jak już słusznie zauważył @hahyes - walidacja podczas wystawiania oferty nie przepuszcza znaku "ñ". Jest to znak niedozwolony. Mimo, że umożliwiliśmy wprowadzenie go do parametru produktu. Nie mamy zatem tutaj spójnej walidacji.

Sprawę przekazałem do odpowiedniego zespołu. Postaram się wrócić z odpowiedzią w jak najkrótszym czasie.

**Comment by Lukasz-Zurek** [comment]
@krowek Zaktualizowaliśmy problematyczny produkt i dodatkowo planujemy aktualizację wszystkich pozostałych o wartość bez niedozwolonego znaku "ñ". Uspójnienie tego w formularzu to kwestia, która będzie analizowana w odrębnym toku. Jeżeli wprowadzimy zmiany w tym zakresie, poinformuję o tym w wątku.

Oczywiście jeśli problem się powtórzy - będę wdzięczny za nowe zgłoszenie.
