### ISSUE TITLE
Nie można aktywować niepoprawnej oferty.

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#5256]
- Czytelność komunikatów? 
- Nie, nie znam.
kurtyna.

Proszę powiedzieć co znaczy ten komunikat.

![image](https://user-images.githubusercontent.com/30370747/146245489-18361712-c047-45cf-ad35-25f6fe6c78b5.png)

```json
{
    "tasks": [
        {
            "offer": {
                "id": "11387442664"
            },
            "message": "Could not change offer publication status. Nie można aktywować niepoprawnej oferty.",
            "status": "FAIL",
            "scheduledAt": "2021-12-15T18:34:22.175Z",
            "finishedAt": "2021-12-15T18:34:22.174Z",
            "field": "publication",
            "errors": [
                {
                    "code": "UnknownError",
                    "message": "You cannot activate an invalid offer.",
                    "details": null,
                    "path": null,
                    "userMessage": "Nie można aktywować niepoprawnej oferty."
                }
            ]
        }
    ]
}
```

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, komunikat nieprecyzyjnie wskazuje źródło problemu - przekałem temat do właściwego zespołu. Co do sedna przypadku - początkowo oferta nie posiadała średnicy wewnętrznej, a ostatecznie oferta posiada średnicę niezgodną z wartością dla produktu przypisanego.

**Comment by PiotrFerenc** [comment]
Dla potomności. Błąd wynika z tego że nie ma podpiętego produktu do oferty.
![image](https://user-images.githubusercontent.com/30370747/146633998-3494cf2e-f878-4e86-b1c8-aafd4afc2c43.png)
