### ISSUE TITLE
Change order status error

### ISSUE THREAD

**Issue by alejandroferrercecotec** [allegro/allegro-api#5257]
We can't change order status via API with **PHP Curl PUT** function. We are requesting this URL and params:

https://api.allegro.pl/order/checkout-forms/325baf61-5dc6-11ec-827f-67a9f3df3968/fulfillment

Curl Json Data:

{"status":"PROCESSING","shipmentSummary":{"lineItemsSent":"NONE"}}

The error message:

`Array ( [errors] => Array ( [0] => Array ( [code] => ServiceTimeoutException [message] => An error occurred [details] => [path] => [userMessage] => Execution of the request timed-out. Try again. ) ) )`

Can anyone help me? Thanks!

**Comment by MaciejFrackowiak** [comment]
We are investigating why our service returned an error 504. I will back with the answer.

**Comment by alejandroferrercecotec** [comment]
Have you news about this? @MaciejFrackowiak

**Comment by MaciejFrackowiak** [comment]
Not yet. Are you still getting errors?

**Comment by alejandroferrercecotec** [comment]
We are on "pause" until you will have news about this problem

**Comment by MaciejFrackowiak** [comment]
Please, check it now if you still receive an error on [PUT /order/checkout-forms/{id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT) resource.

**Comment by alejandroferrercecotec** [comment]
I tried with this PUT request:

https://api.allegro.pl/order/checkout-forms/275126c1-6115-11ec-8ba5-8189603adbdf/fulfillment

Curl Json Data:

{"status":"READY_FOR_SHIPMENT","shipmentSummary":{"lineItemsSent":"NONE"}}

I have the same error message:

Array ( [errors] => Array ( [0] => Array ( [code] => ServiceTimeoutException [message] => An error occurred [details] => [path] => [userMessage] => Execution of the request timed-out. Try again. ) ) )

**Comment by MaciejFrackowiak** [comment]
Thanks for the new example requests. I will be back as soon as I receive the investigation results.

**Comment by alejandroferrercecotec** [comment]
Have you news? @MaciejFrackowiak

**Comment by MaciejFrackowiak** [comment]
Not yet. As I wrote before I will back with the answer as soon as I receive an explanation.

**Comment by alejandroferrercecotec** [comment]
Have you news? @MaciejFrackowiak. This ticket will be expired soon

**Comment by MaciejFrackowiak** [comment]
I still remember the issue, but I have not received an answer yet.

**Comment by alejandroferrercecotec** [comment]
Hello @MaciejFrackowiak. No answer yet?

**Comment by MaciejFrackowiak** [comment]
The problem you reported (error 504 timeout) is much more serious to solve than we thought. Now, our development team has to find the right solution. At the moment, I cannot indicate the time of solving this problem.

**Comment by alejandroferrercecotec** [comment]
Ok, let me know when you have news. Thanks!

**Comment by alejandroferrercecotec** [comment]
Have you news? @MaciejFrackowiak

**Comment by MaciejFrackowiak** [comment]
No, I still have not got any significant news.

**Comment by alejandroferrercecotec** [comment]
Hello @MaciejFrackowiak. No answer yet?

**Comment by MaciejFrackowiak** [comment]
No, any news yet. As I wrote before - if I receive an answer, I will let you know.

**Comment by MaciejFrackowiak** [comment]
After several days of verification and checking logs, I can say that the indicated problem is only a matter of temporary instability. In the last 7 days, we recorded only 10 requests with error 504. Therefore please try calling the resource again to change the order status.
