### ISSUE TITLE
Symulacja zakupu i sprzedaży na Allegro Sandbox

### ISSUE THREAD

**Issue by lulzsoad** [allegro/allegro-api#5258]
Witam, 

Potrzebuję zasymulować wystawienie oferty i zakup produktu przez Allegro Sandbox i na tej podstawie pobrać pewne dane z API. Niestety po takiej próbie przekierowuje mnie do nieaktywnej strony. W jaki sposób mógłbym przeprowadzić taką operację?

Pozdrawiam

![Zrzut ekranu 2021-12-16 101530](https://user-images.githubusercontent.com/48647372/146342870-6334d85d-89a1-4ffa-b142-237d95573316.png)

![Zrzut ekranu 2021-12-16 101541](https://user-images.githubusercontent.com/48647372/146342935-182da346-d9e8-4e18-a07f-63339e53188e.png)

**Comment by MaciejFrackowiak** [comment]
Aby wystawić ofertę na Sandbox skorzystaj proszę z odnośnika: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.
Proces obsługi zamówień na Sandbox opisaliśmy w [naszym poradniku](https://developer.allegro.pl/orders/#sandbox).

**Comment by lulzsoad** [comment]
Dziękuje!

**Comment by lulzsoad** [comment]
Czy jest możliwość szybszej weryfikacji konta?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj swój login.

**Comment by lulzsoad** [comment]
LULZSOAD

**Comment by lulzsoad** [comment]
Gotowe, dziękuję

**Comment by lulzsoad** [comment]
Nadal nie mogę wystawiać ofert. W informacji o koncie nadal widnieje status weryfikacji
![Zrzut ekranu 2021-12-22 102750](https://user-images.githubusercontent.com/48647372/147070285-a8a54909-78a0-4dd8-9e06-dd7f5030f2a0.png)
![asd](https://user-images.githubusercontent.com/48647372/147070294-224d4421-f64c-4010-b47e-5b5b148d851c.png)

**Comment by MaciejFrackowiak** [comment]
Jak widzę dopiero dzisiaj o 10:33 zweryfikowałeś konto jako firmowe - Twój post wysłałeś minutę wcześniej. Czy problem nadal występuje?

**Comment by lulzsoad** [comment]
Problem już nie występuje, dziękuje
