### ISSUE TITLE
Brak statusu FULFILLMENT_STATUS_CHANGED na zamówieniu - Sandbox

### ISSUE THREAD

**Issue by LukSky24** [allegro/allegro-api#5259]
Cześć!
Testuje właśnie nasz system przetwarzania zamówień z Allegro i używam Sandboxa do składania zamówień.
Złożyłem zamówienie na swoim testowym koncie. Id zamówienia: 45920641-5f21-11ec-9867-71f9be5bea26. I ciągle jest na nim status READY_FOR_PROCESSING. A zmieniałem mu status realizacji parę razy (na do wysyłki, wysłano czy anulowano - wszystko z panelu zamówień sprzedającego na Allegro).
Nasze sellerId na sandboxie to: 44119700.
Być może czegoś nie rozumiem, ale bazując na opisie jaki znalazłem w dokumentacji, to zamówienie dawno powinno zmienić już wartość w polu status zwracanym w endpoincie `https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/{{orderId}}`.

**Comment by Lukasz-Zurek** [comment]
Status READY_FOR_PROCESSING to **status zamówienia** - jest on ustalany przez nasz Serwis w sposób automatyczny, gdy klient wypełnił FOD i zakończył płatność, albo wybrał płatność przy odbiorze lub odbiór osobisty. Status zamówienia zwracamy w polu **"status"**, gdy skorzystasz z [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET), lub [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET), czyli w szczegółach konkretnego zamówienia, lub na liście zamówień. Więcej informacji o statusach zamówień znajdziesz w [naszym poradniku](https://developer.allegro.pl/orders/#zamówienia-w-allegro-rest-api).

Zmieniałeś natomiast **status realizacji zamówienia**, korzystając z [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT). Za status realizacji zamówienia odpowiedzialne jest pole **"fulfillment.status"**. Status ten nie jest w żaden sposób zależny od statusu zamówienia. Jeśli jednak sprzedawca korzysta z [abonamentu](https://allegro.pl/moje-allegro/sprzedaz/abonamenty), w zakładce [Zamówienia](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) może ustawić pewne automatyczne schematy. Więcej informacji znajdziesz [tutaj](https://developer.allegro.pl/orders/#zmiana-statusu-realizacji-zamówienia).

**Comment by LukSky24** [comment]
@Lukasz-Zurek Ok ale w takim razie jak można doprowadzić do sytacji kiedy to na zamówieniu pojawi się status `FULFILLMENT_STATUS_CHANGED` bo o to mi chodziło (może źle wyraziłem się poprzednio). Bo rozumiem że to powinno się pokazać jak zmieni się `fullfilement.status`.

**Comment by Lukasz-Zurek** [comment]
Tak, zgadza się. Tutaj status zamówienia jest zależy od statusu realizacji zamówienia. Aktualizujemy zamówienie poprzez nadanie statusu: FULFILLMENT_STATUS_CHANGED jeśli zmienisz **fullfilement.status**, lub jeśli zmieni się on automatycznie, zgodnie z ustawionym schematem w ustawieniach Zamówień.

**Comment by LukSky24** [comment]
@Lukasz-Zurek no to w takim razie czemu w tym zamówieniu o którym pisałem nie został ustawiony status FULFILLMENT_STATUS_CHANGED jeśli zmieniałem fullfilement.status?

**Comment by Lukasz-Zurek** [comment]
Od razu sprostuję, że status FULFILLMENT_STATUS_CHANGED zwracamy tylko w dzienniku zdarzeń, w [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET). Status zamówienia pozostaje niezmienny, czyli jeśli otrzymałeś zamówienie opłacone przez Klienta i zmieniałeś dodatkowo **fullfilement.status** - status zamówienia pozostaje nadal - READY_FOR_PROCESSING, natomiast w dzienniku zdarzeń status to: FULFILLMENT_STATUS_CHANGED.

Przepraszam za wprowadzenie w błąd.

Dla [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) wyróżniamy statusy:

- BOUGHT,
- FILLED_IN,
- READY_FOR_PROCESSING,
- BUYER_CANCELLED,
- FULFILLMENT_STATUS_CHANGED,
- AUTO_CANCELLED.

Natomiast w przypadku [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) zwracamy statusy:

- BOUGHT,
- FILLED_IN,
- READY_FOR_PROCESSING,
- CANCELLED.

Czyli jak widać - nazwy statusów częściowo się pokrywają.

W tej sytuacji, w przypadku wskazanego zamówienia - nie było błędu.
