### ISSUE TITLE
GET sale/offers/{offerId} - pusta tablica "values" w niektórych parametrach

### ISSUE THREAD

**Issue by MarcinSzyszka** [allegro/allegro-api#5260]
Występuje problem: 
 - [x] z zasobem REST API
 - [x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

W danych zwracanych z metody /sale/offers/{offerId} brakuje danych dotyczących nazw wartości niektórych paramterów - tablice "values" są puste, natomiast tablice z id parametrów "valuesIds" zawiera id.

Kod producenta (224017) zawiera wartość, ale inny paramtr o id 5390 już nie

Przykład:
https://api.allegro.pl/sale/offers/10972225896

`{
    "id": "10972225896",
    "name": "BEFADO KAPCIE TRAMPKI 271X001 skórzana wkł r29",
    "category": {
        "id": "25955"
    },
    "product": {
        "id": "31ae42a0-630f-458e-b7e7-41b27a6a8f33"
    },
    "parameters": [
        {
            "id": "224017",
            "valuesIds": [],
            "values": [
                "271X001"
            ],
            "rangeValue": null
        },
        {
            "id": "5390",
            "valuesIds": [
                "5390_58"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "5389",
            "valuesIds": [],
            "values": [
                "29"
            ],
            "rangeValue": null
        }(........)`

**Comment by MarcinSzyszka** [comment]
@Lukasz-Zurek z tym, że ja pobieram dane o ofercie, a nie tworze/aktualizuje ofertę. Rozumiem ideę ale z Waszej strony chyba nic nie stoi na przeszkodzie abyście zwracali pełne dane dot. paramterów produktu w ofercie - raptem dodanie nazwy parametru i jego wartości tym bardziej, że pola owe już są w modelu danych.

Musze wyeksportowac z allegro produkty ze wszystkimi danymi. Gdybym miał te dane w 
GET /sale/offers/{offerId} 
to bym miał wszystko co potrzeba.
W tej chwili musze dla każdego produktu z oferty odpytać 
GET /sale/products/{productId} 
gdzie te dane są i maja prawie ten sam model danych aby pobrac tylko nazwe paramteru i jego wartosci

offers
![image](https://user-images.githubusercontent.com/14890675/146556188-3bbe3be4-5894-4260-8d3e-d68f2854565c.png)


products
![image](https://user-images.githubusercontent.com/14890675/146556372-a0afc6a3-77ca-42eb-a773-3a3409451dd9.png)

Rozumiem, że się nie obejdzie bez tych nadprogramowcyh (wg mnie) requestów?

**Comment by Lukasz-Zurek** [comment]
Nie. Zachęcam Cię jednak do opisania sugestii dotyczącej rozszerzenia [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) - w dedykowanej zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). To miejsce, w którym zbieramy wszelkiego rodzaju pomysły na usprawnienie API Allegro. Jednocześnie na sugestie te mogą głosować również inni użytkownicy forum.

**Comment by MarcinSzyszka** [comment]
Ok, dzięki
