### ISSUE TITLE
Pobranie listy zakupionych produków (Moje zakupy)

### ISSUE THREAD

**Issue by yaras** [allegro/allegro-api#5263]
Czy jest możliwość pobrania listy moich zakupów przez REST API?

**Comment by MaciejFrackowiak** [comment]
Nie, nie mamy takiej funkcjonalności w API Allegro. Od strony kupującego mamy tylko [zasoby](https://developer.allegro.pl/documentation/#tag/Auctions-and-Bidding) umożliwiające udział w aukcjach.
