### ISSUE TITLE
Nieprzechodzące requesty pod endpoint sugestii

### ISSUE THREAD

**Issue by mateuszkolak1999** [allegro/allegro-api#5264]
Występuje problem:
 - [ ] z zasobem REST API
 - [ x ] ze środowiskiem produkcyjnym
 - [ ] ze środowiskiem testowym
 - [ ] z logowaniem lub autoryzacją
 - [ ] na portalu [https://developer.allegro.pl/](https://developer.allegro.pl/)
 - [ ] inny

**Opis**
Błąd występuje podczas, gdy użytkownik wpisuje frazę w pole sugestii - niektóre requesty są odrzucane na endpoincie https://edge.allegro.pl/suggest/web/suggestions? ... .

Zrzut ekranu prezentujący problem:
![image](https://user-images.githubusercontent.com/56225546/146674705-7f0ec260-fe4c-4a44-a7e8-4d266c201261.png)

Problem występuje na środowisku produkcyjnym w sytuacji, gdy użytkownik wpisuje w szybkim tempie np. dwa znaki (dosłownie w tej samej chwili) w pasku wyszukiwania sugestii. Jak można zauważyć pierwszy request został odrzucony przez serwer natomiast drugi (z dwoma znakami) przeszedł.

Natomiast, jeżeli zostaną wpisane 3 znaki szybko to idzie drugie i trzecie zapytanie do serwera.

**Comment by MaciejFrackowiak** [comment]
Opisujesz tu problem niezwiązany bezpośrednio z API Allegro (to nie jest zasób udostępniony w ramach API Allegro), dlatego problem ze stroną WWW i jej funkcjonowaniem proszę zgłoś poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
