### ISSUE TITLE
Zwroty klienckie

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#5265]
Witam, mam pytanie jaki może być powód tego że przez api (https://api.allegro.pl/order/customer-returns) pobiera mi zwroty z czerwca a nie obecne? Pobieram bez żadnych filtrów.

**Comment by Lukasz-Zurek** [comment]
Podaj proszę trace-id wspomnianego wywołania.

**Comment by mskiba03** [comment]
Tutaj jest return_id ostatniego pobranego zwrotu da konta 8953063f-8729-4291-a104-54219823e414 jest z z 11 czerwca, a na koncie są na pewno aktualne.

**Comment by Lukasz-Zurek** [comment]
Wysyłałeś żądanie z filtrami **GET /order/customer-returns?limit=20&offset=0**, dlatego zwróciliśmy Tobie 20 najstarszych zwrotów (z 254 dostępnych).

**Comment by mskiba03** [comment]
Masz rację dziękuje. Można by trochę ujednolicić strukturę, bo w centrum wiadomości offset 0 obiera limit naj nowszych, w zwrotach najstarszych, a w poradniku nie jest to opisane stąd późniejsze problemy ;)

Nie mniej jednak dziękuję za pomoc.

**Comment by Lukasz-Zurek** [comment]
@mskiba03 Również dziękuję. Doprecyzujemy tę informację w naszym poradniku.

**Comment by tomasz-grzesik** [comment]
Dzień dobry,

a czy istnieje możliwość sortowania wyników od najnowszych? W dokumentacji nic na ten temat, a przydatne by się.

**Comment by MaciejFrackowiak** [comment]
@tomasz-grzesik Nie, mamy tylko standardowe sortowanie wszystkich zwrotów od najstarszego. Dlatego pomocne jest tu korzystanie z dostępnych [filtrów](https://developer.allegro.pl/documentation/#operation/getCustomerReturns).
