### ISSUE TITLE
No products are listed on the store's all products page

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5266]
When I look at the sales menu in the web interface, I see that there are 21K active offers.
When I go by saying all the products of the store, no product is visible(https://allegro.pl/uzytkownik/n11Worldwide).

I'm asking for help.

**Comment by MartaNowaczyk** [comment]
Here you can ask a question about REST API allegro. Problems on the Allegro website should be reported via our [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by MartaNowaczyk** [comment]
I can only confirm that I can see over 20k offers under the link provided.
