### ISSUE TITLE
Wysyłam z Allegro // Zwraca błędy przy dodaniu Umowy dla kuriera Poczty Polskiej

### ISSUE THREAD

**Issue by lukestyl** [allegro/allegro-api#5267]
Mamy 3 konta w których chcę dodać możliwość nadawania paczek. Uzupełniam dane dostępowe do API dla Poczty Polskiej i na jednym koncie przeszło bez problemów, ale na pozostałych zwraca błędy: 

"Dane dostępowe do API do przewoźnika są nieprawidłowe" w czym może być problem? 

Na pewno log i pass są poprawne i aktualne. Z innymi kurierami Inpost, DPD przeszło bez problemu na 3 kontach. To co jeszcze podejrzewamy to, że pierwsze konto jest zarejestrowane pod firmą A a pozostałe dwie znów pod B i może to jest problemem.

**Comment by MaciejFrackowiak** [comment]
Możliwe, że dane dla pozostałych dwóch kont zostały zablokowane w Elektronicznym Nadawcy - Poczta Polska blokuje tak dostęp do umowy w przypadku podania nieprawidłowych danych. Spójrz do EN i sprawdź, czy dostęp nie został zablokowany.

**Comment by lukestyl** [comment]
Gdzie to można sprawdzić w EN? 
No właśnie, jakby był zablokowany to nie dałoby się zalogować do EN, bo to jest ten sam login i pass. Chyba, że API odrębnie traktują.

**Comment by MaciejFrackowiak** [comment]
Niestety, nie posiadamy instrukcji do obsługi programów zewnętrznych, mamy tylko takie szczątkowe informacje od Poczty.
