### ISSUE TITLE
Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert.

### ISSUE THREAD

**Issue by logrox** [allegro/allegro-api#5268]
Cześć.
Cały czas mam taki komunikat "Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert."
Konto niby mam aktywne bo mogę z api korzystać jednak nie wystawiać nowe oferty, tylko szkice.
Pisałem jakiś czas temu w podobnym temacie ale jak już doszedłem do wystawiania ofert to "ściana".
To samo gdy próbowałem wystawić tradycyjnie przez www.
Na stronce https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty mam info "Niestety musieliśmy odrzucić dane Twojej firmy. Nie możesz sprzedawać na Allegro."

nazwa konta lognet

Pomóżcie co robię/zrobiłem źle.

**Comment by logrox** [comment]
Wysłane

**Comment by MaciejFrackowiak** [comment]
Jak widzę Twoje konto jest już zweryfikowane jako firmowe.
