### ISSUE TITLE
"Usługa niedostępna u tego przewoźnika"

### ISSUE THREAD

**Issue by lulzsoad** [allegro/allegro-api#5269]
Witam,

Pracuję na środowisku testowym Allegro Sandbox.

Pobierając dane z zapytania `GET /parcel-management/delivery-services` w odpowiedzi otrzymuję usługi dodatkowe `"additionalServices"`, w których dla:

- Allegro DPD otrzymuję wartość `"expressAvailable": true` w `"cashOnDelivery"`
- Allegro UPS otrzymuę wartość `{"name": "upsSaver", "description": "UPS Express Saver."}` w `"options"`

Jeżeli próbuję utworzyć paczkę dla tych usług dostawy z podanymi usługami dodatkowymi w odpowiedzi dla statusu utworzenia paczki otrzymuję błąd z informacją _"Usługa niedostępna u tego przewoźnika"_.

Z czym to się wiąże? Czy na testowym środowisku sandbox są jakieś ograniczenia? Czy muszę w jakiś sposób aktywować te konkretne usługi?

**Comment by MaciejFrackowiak** [comment]
Tak, na środowisku testowym działają wyłącznie podstawowe opcje Wysyłam z Allegro, i po części także w "okrojonej" wersji.
