### ISSUE TITLE
REST - /offers/{offerId}/change-stock-commands/{commandId}

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#527]
Czy przewidujecie taki zasób? Wiem, że dostępną ilość na chwilę obecną zmieniamy za pomocą PUT na zasobie /sale/offers/{offerId} ale do tego muszę pobrać najpierw wszystkie dane za pomocą GET /sale/offers/{offerId}. Skoro cenę można zmieniać w analogiczny sposób to dlaczego nie obsługiwać tak stanów?

**Comment by KrzysztofLukanowski** [comment]
Na tę chwilę nie planujemy, ale dziękujemy za sugestię. Co do zmiany ceny w ten sposób, był to pierwszy zasób jaki udostępniliśmy na REST API. Umożliwia on zmianę ceny po ofertach kupna, WebAPI na to nie pozwalało.

**Comment by mareklemur** [comment]
W takim razie czym najprościej zastąpić metody doChangeQuantityItem i doChangeItemFields w REST API? Za każdym razem trzeba pobierać wszystkie pola żeby zmienić jedno z nich?

**Comment by Rnapzsih** [comment]
Po dłuższym użytkowaniu raczej obstawał bym za coś takiego **/offers/change-stock-commands/{commandId}** Gdzie wysyłamy tablice z id naszych aukcji i nową dostępnością.

**Comment by mareklemur** [comment]
Ale przecież nie ma takiej metody: https://developer.allegro.pl/documentation/

**Comment by Rnapzsih** [comment]
No nie, to propozycja

**Comment by TomekKaczmarek** [comment]
Pracujemy nad zasobami do zmiany ceny i ilości sztuk w wielu ofertach jednocześnie. Jak tylko się pojawią - damy znać.

**Comment by TomekKaczmarek** [comment]
Nowe zasoby powinniśmy opublikować w ciągu najbliższych 2-3 tygodni.
