### ISSUE TITLE
Parcel management

### ISSUE THREAD

**Issue by BizcomLodz** [allegro/allegro-api#5270]
Hello,
I need help with API parcel management.
When we create parcel with cash on delivery
We need to provide account number and name
What is this account number and name and where to get it ?

I am talking about the below article 
https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices

"additionalServices": {

    "cashOnDelivery": 

{

    "value": 

{

    "amount": "2.50",
    "currency": "PLN"

},
"accountNumber": "12345678901234567890123456",
"name": "Jan Kowalski",

![image](https://user-images.githubusercontent.com/96567831/147207762-dfbf721b-f3b5-4e94-bfde-d685e2c2eba1.png)

Please also let me know what is the point ID example "pointId": "1234567". This should be matching our company adress I think, from where I can get this information?

We would really appreciate if you can provide us where to get this information. Is it just our company name and our bank account or subsidiary account from allegro(in this case where to get number of this account?)
Thank you in advance
Kind Regards

**Comment by lulzsoad** [comment]
Hi,
It should be sender's bank account number and the name of the account's owner on which money from COD (Cash On Delivery) will be transferred after payment is done by customer. Correct me please if I'm wrong.

**Comment by MaciejFrackowiak** [comment]
Account number and name are connected with the sender. PointId is an ID of the pickup point - you can get it from order or directly from courier service.
