### ISSUE TITLE
PARAMETER_MISMATCH","message":"The provided parameter 'Model'...

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5277]
trace-id : c24b86a7f145e06f

I'm not sending an `AR1079` information, how does it return this error? 

the error message : {"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Model'(216321) value (5285863842812964807) does not match the existing parameter value (AR1079)","details":null,"path":"product.parameters","userMessage":"The provided parameter `Model` value `5285863842812964807` does not match the existing parameter value `AR1079`."}],"error":null,"error_description":null}

**Comment by AureliuszBrussy** [comment]
That error message means that based on the parameters that identify the products in this category - we found a product in our database which has similar parameters. Model (216321) parameter is different from what you provided. Id of this product: f23e870d-d96f-4a21-a06f-94700e0a2e58. You should use the value "AR1079" in the given parameter (216321).
