### ISSUE TITLE
Atomowość operacji

### ISSUE THREAD

**Issue by vitapak** [allegro/allegro-api#5278]
https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT

1) Czy masowe operacje zamykania ofert są atomowe? załóżmy, że zamykam 100 ofert jednym commandem - czy jest możliwość, że 1 oferta zostanie zamknięta lecz pozostałe nie i w odpowiedzi będę miał success i failure?, ta sama kwestia tyczy się zmiany ceny/ilości.

2) Z jakich powodów oferty mogą nie zostać zamknięte mimo prawidłowego wysłania zlecenia?, czy brak wymaganych parametrów może mieć wpływ na możliwość zamknięcia takiej oferty?

**Comment by AureliuszBrussy** [comment]
1. Tak, operacje są atomowe - gdy sprawdzisz status operacji za pomocą [GET /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET), otrzymasz odpowiedź w formie, w której zwrócimy informacje o liczbie sukcesów i porażek:

```
{
"id": "string",
"taskCount": {
"failed": 0,
"success": 0,
"total": 0
}
}
```

Możesz sprawdzić też szczegółowo status poszczególnych tasków dzięki [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET).  

2. Ewentualne problemy z zakończeniem mogłby wystąpić w przypadku jakiś problemów technicznych z naszej strony. Nie walidujemy parametrów przy zakańczaniu oferty.

**Comment by vitapak** [comment]
Ad. 1
Czyli skoro są atomowe, to zawsze albo wszystkie będą success albo wszystkie będą failed, prawda?
Czy status operacji jest aktualizowany przez Państwa zawsze na końcu operacji, jednorazowo, czy on może zmieniać się w czasie?

**Comment by AureliuszBrussy** [comment]
@vitapak przepraszam, pomyłka - operacje nie są atomowe, są rozdzielne, czyli część może zakończyć się sukcesem, a część porażką. Zwracamy ostateczny status operacji.

**Comment by vitapak** [comment]
@AureliuszBrussy czyli jest jak myślałem - część ofert może się zamknąć, a część nie :) 

Zakładając, że zamykam 3 oferty w 1 commandzie - response w przypadku zasobu: https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET będzie zawierał 3 osobne elementy tablicy w taskach? czy 2 elementy z podziałem na status grupy success i failed czy jednak jest to losowe?

Jak będzie wyglądał response, jeżeli na 3 oferty, pierwsza się wykonała, a pozostałe 2 nie (nie udało się zamykanie oferty z powodu losowych problemów technicznych), skąd będę wiedział, które błędy dotyczą konkretnych ofert?

**Comment by AureliuszBrussy** [comment]
@vitapak każda oferta to będzie osobny obiekt w tablicy, więc w takim przypadku wylistujemy 3 osobne elementy. W każdym elemencie zwrócimy m.in. id oferty, status operacji oraz błędy, o ile wystąpiły.

**Comment by vitapak** [comment]
W takim razie pozostają dwie kwestie:

1. w jakiej kolejności będą listowane elementy, jeśli wyślę do Państwa 3 oferty w kolejności 1,2,3 - kolejność w response będzie losowa, czy zawsze jest zachowana 1,2,3 niezależnie od daty rozpoczęcia operacji (np. zamknięcie oferty nr 3 było pierwsze)?
2. wysyłając zlecenie na 3 oferty, status od razu nam zwróci 3 osobne elementy ze statusem "new", które następnie będą aktualizowane na success albo fail, czy jednak dopiero po wykonaniu operacji na pojedynczej ofercie, ona wyląduje w response, ale tylko w przypadku oczywiście success albo fail? pytam, ponieważ nie wiem jak zweryfikować czy response jest finalny (wykonał wszystkie operacje i nie ulegnie zmianie)

**Comment by AureliuszBrussy** [comment]
@vitapak konsultuję to z zespołem odpowiedzialnym za zasób. Wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@vitapak dziękuję za cierpliwość:

1. Nie gwarantujemy kolejności zgodnej z wysłanym requestem - może ona wystąpić, ale będzie wynikać z cech systemu, a nie z naszych założeń.
2. Możesz sprawdzić, czy komenda została zakończona porównując: `success + failed == total` w [GET /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPublicationReportUsingGET). W przypadku [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) - komenda jest zakończona w momencie, gdy każdy z tasków ma status SUCCESS lub FAIL. Oczywiście zwracamy taski ze statusem NEW dopóki nie został on przeprocesowany.
