### ISSUE TITLE
Dla części ofert, nie aktualizuje się cena aukcji (mimo podwyżki o zaledwie 10%)

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#5279]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry, próbuje od kilku godzin zmienić cenę oferty 11460344875 z 296 na 328 zł.

Poniżej szczegóły:

Zmiana ceny:
{"id":"87bd7da8-b230-473e-81de-bb0c1c57ef0c","taskCount":{"total":0,"success":0,"failed":0}}

Weryfikacja (NIE UDAŁO SIĘ):
{"id":"87bd7da8-b230-473e-81de-bb0c1c57ef0c","taskCount":{"total":1,"success":0,"failed":1}}

Inna oferta (11461373490) o podobnej cenie (UDAŁO SIĘ):
{"id":"ac00c527-cac0-4c0c-a14e-8ae8f8362d87","taskCount":{"total":1,"success":1,"failed":0}}

Proszę o informację dlaczego dla niektórych aukcji (ok. 90) ceny nie chcą się zmieniać mimo iż podwyżka nie przekracza 20%.

Pozdrawiam
Łukasz

**Comment by lukiopmoto** [comment]
Odpowiedź z API: Kategoria oferty jest różna od kategorii produktu - 257689,257694.
Co to oznacza? Przecież wskazana opona jest oponą dostawczą i do takiej kategorii została przypisana w momencie publikacji.
Poza tym co ma zmiana ceny do kategorii?

Response:
"message":"OPERATION_FAILED",
"status":"FAIL",
"scheduledAt":"2021-12-30T12:25:57.457Z",
"finishedAt":"2021-12-30T12:25:57.456Z",
"field":"price",
"errors":[
{
"code":"ConstraintViolationException.ValidProduct",
"message":"Kategoria oferty jest różna od kategorii produktu - 257689,257694.",
"details":null,
"path":"category",
"userMessage":"Kategoria oferty jest różna od kategorii produktu - 257689,257694."
}

**Comment by MartaNowaczyk** [comment]
Sprawdzam opisaną sytuację. Wrócę z odpowiedzią.

**Comment by lukiopmoto** [comment]
Tylko się przypominam, czy coś już wiadomo w tej sprawie? Dlaczego nie można zmienić ceny produktu, który dodany został do właściwej kategorii. Cena nie przekracza 100% wartości oraz co ma zmiana ceny do kategorii?

**Comment by MartaNowaczyk** [comment]
Problemem była błędna kategoria w produkcie. Przy edycji np. ceny kategoria musi być poprawna. W tym momencie kategoria w produkcie jest już poprawiona. 
Następnym razem, gdy zauważysz błąd w produkcie zgłoś go [przez API](https://developer.allegro.pl/productization/#6-jak-zg%c5%82osi%c4%87-b%c5%82%c4%85d-w-produkcie) albo przez formularz wystawiania: "zgłoś błąd w produkcie".
