### ISSUE TITLE
Message not readable

### ISSUE THREAD

**Issue by PiotrFerenc** [allegro/allegro-api#5280]
Witam.
Co oznacza poniższy błąd ?

````JSON
{
   "errors":[
      {
         "code":"ValidationError.HttpMessageNotReadableException",
         "message":"Message not readable",
         "details":null,
         "path":"/sale/offers",
         "userMessage":"Message not readable"
      }
   ]
}
````

**Comment by MartaNowaczyk** [comment]
Błąd nie jest jednoznaczny. Żeby to sprawdzić potrzebuję pełnego requestu, który zakończył się tym błędem, najlepiej w formie curl (usuń z niego token). Możesz podesłać go też przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).

**Comment by PiotrFerenc** [comment]
```curl
curl --location --request POST 'https://api.allegro.pl/sale/offers' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer token' \
--data-raw '{
   "name":"02S311375A INA",
   "category":{
      "id":"260654"
   },
   "primaryImage":null,
   "sellingMode":null,
   "saleInfo":{
      "currentPrice":{
         "amount":"347",
         "currency":null
      },
      "biddersCount":0
   },
   "stats":null,
   "stock":{
      "available":10,
      "unit":"UNIT"
   },
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"becac0e5-50b1-459b-b7a6-97a35f0f19b6"
      },
      "returnPolicy":{
         "id":"5854ff21-02a2-4b71-8700-71a85d54d65b"
      },
      "warranty":{
         "id":"0f8a2f11-17d6-44b3-8867-0dae16f7c52d"
      }
   },
   "additionalServices":null,
   "external":null,
   "product":null,
   "parameters":null,
   "ean":null,
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"text",
                  "content":"02S311375A INA",
                  "url":null
               },
               {
                  "type":"text",
                  "content":"<ul><li> 02S311375A INA </li><li> Symbol 02S311375A </li><li> Opis Łożysko igiełkowe </li><li> Producent INA </li><li> Wymiary 25 x 43 x 18,3 </li><li> </li></ul>",
                  "url":null
               }
            ]
         }
      ]
   },
   "compatibilityList":null,
   "images":[
      {
         "url":"https://a.allegroimg.com/original/11bc45/0727aa0e45f1ac18c68d837c3039"
      }
   ],
   "delivery":{
      "shippingRates":{
         "id":"00f3fafc-b9e3-433b-85ff-0b18ca068060"
      },
      "handlingTime":"PT24H",
      "additionalInfo":"Przesyłka kurierska",
      "shipmentDate":null
   },
   "payments":{
      "invoice":"VAT"
   },
   "sizeTable":null,
   "promotion":null,
   "location":null,
   "attachments":null,
   "contact":null
}'
```

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i dla tego requestu dostałam error o niepoprawnym JSON. 

Znalazłam błędy w opisie:

- jest `"type":"text" `powinno być `"type":"TEXT"` 
- `"content":"02S311375A INA"` - brak znaczników `<p></p>`
- w jednej sekcji "items" możesz umieścić tylko jeden raz typ tekstowy (`"type": "TEXT"`). Jak chcesz to rozdzielić, możesz dodać kolejną sekcję `"items"` lub kontynuować opis w `"content": "<p>02S311375A INA</p>"`

Przykład poprawnego opisu na podstawie twoich danych:
```
 "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>02S311375A INA</p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<ul><li>02S311375A INA</li><li>Symbol 02S311375A</li><li>Opis Łożysko igiełkowe</li><li>Producent INA</li><li>Wymiary 25 x 43 x 18,3</li></ul>"
                    }
                ]
            }
        ]
    },

```
Sprawdź jeszcze link do zdjęcia i powinno być ok. Jakby coś jeszcze było niejasne daj znać, postaram się pomóc.

**Comment by reprezenter** [comment]
Mam taki sam błąd, w formularzu kontaktowym nie ma opcji przesłania wiadomości dla problemów z API:
endpoint: 
https://api.allegro.pl/sale/offers/ $id
request:
{"id":"11738685659","parameters":{"11323":"11323_1","224017":"134768","127788":"127788_512649","222521":"222521_299589","222537":"80","127768":"127768_71","4906":"4906_4194304","127789":"127789_4","225693":"5902277180827"}}
response:
    [error] => {"errors":[{"code":"ValidationError.HttpMessageNotReadableException","message":"Message not readable","details":null,"path":"/sale/offers/11738685659","userMessage":"Message not readable"}]}

**Comment by MartaNowaczyk** [comment]
@reprezenter sposób w jaki podałeś dane parametrów jest nieprawidłowy. Na przykład dla parametru 11323 struktura powinna wyglądać w ten sposób:
```
{
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
```
Więcej o parametrach przeczytasz w [naszym poradniku](https://developer.allegro.pl/sale/#parametry).
Możesz też wystawić ofertę przez formularz, pobrać ją metodą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET) i zobaczyć jak wygląda prawidłowa struktura. Oczywiście jest też [dokumentacja](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) :)
