### ISSUE TITLE
API dla kupującego (zamówienia, zwroty)

### ISSUE THREAD

**Issue by piotrraczynski** [allegro/allegro-api#5281]
Witam serdecznie, czy Allegro oferuje jakiś zakres API dla kupującego? 

Dla kupujących z dużą ilością zamówień przydatne by było wyświetlanie listy zamówień i zwrotów.

**Comment by MartaNowaczyk** [comment]
Nie mamy API dla kupującego.

Skorzystaj z naszej zakładki [Discussions](https://github.com/allegro/allegro-api/discussions) i dodaj taką sugestię. Dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.

**Comment by piotrraczynski** [comment]
Done, dziękuję.

https://github.com/allegro/allegro-api/discussions/5285
