### ISSUE TITLE
Problem z zamknięta ofertą

### ISSUE THREAD

**Issue by TOBOMEBLE** [allegro/allegro-api#5282]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ X] inny / other

:beetle: **Opis / Description**

**Comment by TOBOMEBLE** [comment]
Dzień dobry,

Dzień dobry, Czemu oferta którą zamykam sama się wznawia?
numer oferty 9486692164.
Ta sytuacja miała miejsce już kilka razy. Aukcja została zamknięta z powodu wycofania produktu z produkcji. Niestety po jakimś czasie wznawia się automatycznie (pomimo wyłączonego ponownego wystawiania). Kilka dni temu znowu została otwarta i niestety klient zakupił aż 5 sztuk niedostępnego produktu, o czym dowiedziałam się dzisiaj po przyjściu do pracy. Szybko zamknęłam aukcję i skontaktowałam się z Allegro , które poinformowało mnie, że wina leży po stronie API. Bardzo proszę o pomoc  w takiej sytuacji i jej rozwiązanie, gdyż źle to wpływa na nasz sklep.

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, komendę z żądaniem wznowienia oferty otrzymaliśmy od aplikacji, której identyfikator kończy się na ...7934e16368 - listę powiązanych aplikacji znajdziesz w zakładce [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje). Przykładowy identyfikator zadania, które wznowiło ofertę 29.12.21 o 11:50 to `de553722-fdf3-4f82-8d74-1325cfae0ab6`. Wszelkie wątpliwości możesz wyjaśnić ze wsparciem wspomnianej aplikacji.
