### ISSUE TITLE
Wymuszenie walidacji

### ISSUE THREAD

**Issue by martacronic** [allegro/allegro-api#5287]
Pojawiły się problemy z edycja istniejących aukcji. Wynikają one ze zmiany wymagań w opisach. Nie stosujemy niedozwolonych praktyk, ale informowaliśmy, że do produktu dodajemy dowód zakupu w postaci paragonu lub faktury VAT, który jest podstawą do reklamacji.

Jestem w trakcie zmiany opisów, na podstawie błędów, ale chciałabym móc systematycznie sprawdzać wszystkie aukcje pod tym kątem, gdyż nie wiem kiedy będzie potrzeba zmiany stocku czy ceny. Próbowałam pobrać ofertę za pomocą GET /sale/offers/{offerId}, a potem zrobić bez zmian w aukcji PUT/sale/offers/{offerId}, ale validatedAt w sekcji validation nie zmieniła się.

Są to tysiące aukcji, których opisy w części były robione przez użytkowników.

Z jakich zasobów powinnam skorzystać, żeby walidować ofertę bez jej zmiany?

**Comment by pliszka** [comment]
z tego co mi wiadomo nie da się tego wykryć w "przód" dopiero po zaistnieniu błędu można zareagować 
czyli zmieniasz cenę (ta zmiana się nie udaje) poprawiasz wtedy opisy i znów zmieniasz cenę

**Comment by PrzemyslawLukanowski** [comment]
Czas walidacji nie zmieni się, jeśli przesyłasz ten sam model oferty i nie zawiera on błędów. Jeśli oferta zawiera błędy, dopiero wtedy informację o nich zwrócimy w sekcji validation (jeśli oferta jest szkicem) i zaktualizujemy czas, lub odpowiemy statusem 422 (jeśli oferta jest aktywna) wraz z odpowiednią treścią błędu.

**Comment by martacronic** [comment]
@PrzemyslawLukanowski ok, to prosiłabym o zgłoszenie do zespołu zajmującego się rozwojem API, żeby rozważyli zmianę daty  w przypadku walidacji, a nie tylko w przypadku kiedy walidacja przebiegnie niepomyślnie.

Mnie osobiście komunikaty po PUT /sale/offers/{offerId} zmyliły właśnie przez niezmienioną datę validatedAt. Byłam przekonana, że wysłany draft przez to, że jest taki sam, nie został zwalidowany. Skoro walidacja nastąpiła i przebiegła bez błędów, to data powinna się zmienić.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię, prosiłbym o jednak, abyś utworzyła ją w poświęconej temu zakładce [Discussions](https://github.com/allegro/allegro-api/discussions ). Zbieramy tam pomysły na rozwój naszego API, inni użytkownicy również mogą głosować na daną sugestię.

**Comment by martacronic** [comment]
@PrzemyslawLukanowski ok, miałam dużą przerwę w korzystaniu z issue na Waszym GitHubie, bo mi wszystko działało i nie zauważyłam, że takie coś wprowadziliście

**Comment by PrzemyslawLukanowski** [comment]
@martacronic Chciałem jeszcze doprecyzować, że data w validatedAt zmieni się, jeśli wysyłasz w szkicu poprawne dane, a wcześniej były one nieprawidłowe. Nie zmieni się wtedy, jeśli przesyłasz dokładnie te same dane i w dalszym ciągu są one prawidłowe lub nie.
