### ISSUE TITLE
Nie da się wystawić oferty według EANu mimo że produkt istnieje 

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#5288]
TraceID: c0e4261f508b9e28

Próba wystawienia oferty według EANu poprzez POST /sale/product-offers (beta.v3) 
Rezultat taki, że produkt jest ale aukcja stworzona być nie może bo produkt zawiera błędy (brak wymaganych parametrów) czy to zachowanie jest celowe / poprawne? czy to błąd po stronie Allegro że w bazie znajdują się produkty, które nie są kompletne?

**Comment by MartaNowaczyk** [comment]
Może się tak zdarzyć, że produkt będzie zawierał błędy. Gdy zauważysz błąd w produkcie zgłoś go [przez API](https://developer.allegro.pl/productization/#6-jak-zg%c5%82osi%c4%87-b%c5%82%c4%85d-w-produkcie) albo przez formularz wystawiania: "zgłoś błąd w produkcie", bo to nie problem samego API.
