### ISSUE TITLE
upload product, brand problem

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5291]
When i set "other", the api returns;
Given dictionary parameter valuesIds `3229_7` in parameter `3229` indicates different value than `values` field.\"
trace-id:"a542f8d5256ba48e"

When i set it's own brand; the api returns;
The provided parameter 'Brand'(3229) value (Arzum(3229_486013)) does not match the existing parameter value (other(3229_7))
trace-id:"fc7cfe2fee699d48"

I think the api wants the brand in the product registered inside, I want it to be added as a new product without associating with the existing product inside. What can I do, is it possible, otherwise how can i upload my products

**Comment by PrzemyslawLukanowski** [comment]
Yes, based on the provided data we've found an existing product in our database. The product from our database has the same EAN code, so it's not possible to create a new product. If in your opinion the found product has incorrect data, you can report this via [our form](https://allegro.pl/offer/product/report/a732b747-c403-491e-a3db-577e632a3551) or [using API](https://developer.allegro.pl/en/productization/#6-how-to-report-incorrect-data-in-a-product).
