### ISSUE TITLE
/sale/offer-events sortowanie

### ISSUE THREAD

**Issue by igornizio** [allegro/allegro-api#5292]
Mam problem z sortowaniem wg OFFER_BID_PLACED  w ramach zapytania https://api.allegro.pl/sale/offer-events w dokumentacji nie ma mowy o sortowaniu wydarzeń związanych z licytujacymi od najnowszych. Pobieranie wielu danych, żeby uzyskać informację o tych najnowszych jest zupełnie bez sensu. Czy API ma opcję sortowania?

drugie pytanie w jakis sposob uzyskac nick osoby licytujacej?

**Comment by PrzemyslawLukanowski** [comment]
Wyniki zwracamy wg kolejności, w jakiej wystąpiły dane zdarzenia - od najstarszych do najnowszych. Nie udostępniamy innej możliwości sortowania. Możesz skorzystać z istniejących filtrów - `from `oraz `type`, aby ograniczyć liczbę wyników.

Podobnie jak na stronie internetowej - nie zwracamy informacji o nicku osoby licytującej.

**Comment by igornizio** [comment]
Na stronie używacie zanonimizowanej formy nicku, czy w API nie możecie wdrożyć takiej możliwości?

**Comment by PrzemyslawLukanowski** [comment]
Nie mamy tego w planach. Możesz zgłosić swoją sugestię za pomocą zakładki [Discussions](https://github.com/allegro/allegro-api/discussions), w której zbieramy pomysły na rozwój API od innych użytkowników.
