### ISSUE TITLE
Problem ze zdobyciem tokena Client_credentials 

### ISSUE THREAD

**Issue by morgutrin** [allegro/allegro-api#5293]
Witam,
dopiero zaczynam przygodę z api i mam taki problem wrzucam w postmana zapytanie typu POST pod ten url:  https://allegro.pl/auth/oauth/token?grant_type=client_credentials
z takimi nagłówkami:
![image](https://user-images.githubusercontent.com/33134863/148626091-53c81390-bf43-42e6-9f39-261608f53dff.png)
robię tak jak jest w dokumentacji, lecz nie mogę uzyskać tokenu...
Czy wie ktoś z was może co robię źle?

**Comment by morgutrin** [comment]
oczywiscie zmienne clientid oraz clientsecret podmieniam na swoje

**Comment by morgutrin** [comment]
dostaje taką zwrotkę:
![image](https://user-images.githubusercontent.com/33134863/148645290-78af3e72-8fc2-4eb7-95ea-45dc91245abf.png)

**Comment by PrzemyslawLukanowski** [comment]
Wartość w nagłówku Authorization musisz dostarczyć już odpowiednią przekonwertowaną. Czyli zamiast `Basic base64(clientId:secret)` przekaż tam `Basic YTliNWFhMDE2NGFlNDVkMmEwYTIzMTR...`
