### ISSUE TITLE
Brak możliwości publikacji drafu

### ISSUE THREAD

**Issue by michalsukiennik** [allegro/allegro-api#5294]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

 Po dodaniu draftu otrzymuję błąd "_You don't have the required permissions to publish offer (sell blocked). Verify your account as a company_.".

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że konto nie jest w pełni aktywne. Podaj proszę login swojego konta na Sandboxie.

**Comment by michalsukiennik** [comment]
michals

**Comment by AureliuszBrussy** [comment]
@michalsukiennik skorzystaj z zakładki [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i opłać rachunek za pomocą symulatora. Po tym blokada wystawiania powinna zostać usunięta.
