### ISSUE TITLE
/sale/offers błędna kwota sprzedanych przemiotów

### ISSUE THREAD

**Issue by igornizio** [allegro/allegro-api#5295]
Mam problem z kwotą sprzedanych produktów, przez zapytanie /sale/offers zwraca sold = 0. Pomimo, że w /order/checkout-forms/  pokazuje zrealizowane płatności. 

Przez kilka dni pokazywało dobrze

`
<img width="1140" alt="Zrzut ekranu 2022-01-8 o 23 00 06" src="https://user-images.githubusercontent.com/38662082/148661639-12445d23-ec61-417f-aed0-3805252f5015.png">
<img width="1150" alt="Zrzut ekranu 2022-01-8 o 23 00 26" src="https://user-images.githubusercontent.com/38662082/148661641-79f08147-20a8-4762-910d-7ee06e89e325.png">
`

**Comment by AureliuszBrussy** [comment]
W polu stock.sold zwracamy informacje o liczbie sprzedanych przedmiotów, ale tylko w ciągu ostatnich **30 dni**. Nie znajdziesz tam informacji o wcześniejszej sprzedaży.
