### ISSUE TITLE
/sale/offers?limit=200&offset=200

### ISSUE THREAD

**Issue by nowyyy31** [allegro/allegro-api#5296]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

Pobieram listę towarów dla kont o ID 9775451, 102776904 konta są powiązane i jak pobieram listę aukcji zapytaniem 
/sale/offers?limit=200&offset=200 to mimo że korzystam z różnych tokenów mam takie same listy aukcji, dlaczego? 

Jeszcze do przed nowym rokiem normalnie działało pobranie aukcji dla tych kont

**Comment by nowyyy31** [comment]
W obu tokenach jest jeden "user_name": "102776904" 
Po usunięciu powiązania aplikacji i utworzeniu nowego powiązania jest ok.

**Comment by Lukasz-Zurek** [comment]
Ok, cieszę się, że problem ustąpił.

**Comment by nowyyy31** [comment]
Panie Łukaszu znowu jest taki sam problem, konto o ID 9775451 pobrało nowy kod token i jest wartość 102776904 w user_name. 
Proszę o informacje gdzie znajdę wartość trace-id  ?

**Comment by Lukasz-Zurek** [comment]
> Panie Łukaszu znowu jest taki sam problem, konto o ID 9775451 pobrało nowy kod token i jest wartość 102776904 w user_name.

Domyślam się, że chodzi o autoryzację w aplikacji zarejestrowanej na koncie 9775451, w której uwierzytelniłeś się jako użytkownik 102776904. W tej sytuacji, w przypadku skorzystania z zasobu GET /sale/offers - uzyskasz listę ofert na koncie 102776904. Aby móc uzyskać dostęp do listy ofert użytkownika 9775451, musiałbyś uwierzytelnić się w aplikacji jako 9775451.

> Proszę o informacje gdzie znajdę wartość trace-id ?

Trace-id znajdziesz w nagłówku żądania np. dotyczącego pobrania listy ofert.
