### ISSUE TITLE
Problem z przedłużeniem trwania ogłoszenia w statusie ENDED

### ISSUE THREAD

**Issue by mankovsky** [allegro/allegro-api#5298]
Dzień dobry, mam problem, ponieważ chyba niedawno została wprowadzona zmiana, w związku z którą, ogłoszenia w statusie "ENDED" nie mogą mieć aktywowanych pakietów poprzez metodę PUT na endpoint "sale/offer-classifieds-packages/{offerId}"

jako przykład mogę podać to ogłoszenie naszego klienta
https://allegro.pl/ogloszenie/land-rover-range-rover-sport-hse-3-0td-245km-autom-11264289618

identyfikator 11264289618

w przypadku pobrania listy dostępnych pakietów dla tego konkretnego ogłoszenia, zwracany jest błąd:
"code" => "ClassifiedForOfferNotFoundException", "message" => "Classified with id: 11264289618 does not exist."

czy da się w jakiś sposób przedłużyć ważność (aktywować pakiet) tego ogłoszenia?

ponieważ pomijając teraz przypisanie pakietu (które obecnie jest niemożliwe), przy próbie aktywowania tego ogłoszenia poprzez użycie metody PUT na endpoint sale/offer-publication-commands/{uuid} otrzymujemy błąd:
"tasks":[{"offer":{"id":"11264289618"},"message":"Could not change offer publication status. Pakiet ogłoszeniowy nie jest przypisany do oferty lub kategoria nie pasuje do pakietu.","status":"FAIL"

bardzo prosiłbym o pomoc, ponieważ nasi klienci nie mogą teraz w łatwy sposób przedłużać czasu trwania ogłoszenia

**Comment by PrzemyslawLukanowski** [comment]
Przed chwilą udało mi się prawidłowo przypisać pakiet dla oferty w statusie ENDED za pomocą wymienionego przez Ciebie endpointu. Czy możesz podać przykładowe trace-id dla wywołania, w którym zwróciliśmy błąd? Upewnij się, że w wywołaniu przekazujesz prawidłowe identyfikatory pakietów dl danej kategorii, sprawdzisz je przy użyciu [GET /sale/classifieds-packages?category.id={category.id}](https://developer.allegro.pl/documentation/#operation/getClassifiedPackageConfigurationsForCategoryUsingGET).

**Comment by mankovsky** [comment]
Hmm, teraz ponowne wykonanie tej samej operacji zadziałało prawidłowo, to błędne wykonanie z dzisiaj to np. trace_id = "f5723b5db97fc083"

**Comment by PrzemyslawLukanowski** [comment]
Udało mi się ustalić przyczynę z zespołem odpowiedzialnym za funkcjonalność - wystapiły problemy po naszej stronie, które skutkowały komunikatem błędu, który otrzymałeś. Wdrożyliśmy właśnie poprawkę, problem już nie powinien występować. Przepraszam za niedogodności.
