### ISSUE TITLE
PROBLEM Z USUWANIEM WIELU OFERT

### ISSUE THREAD

**Issue by marcinja2** [allegro/allegro-api#5299]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Na zasób:  $url= 'https://api.allegro.pl/sale/offer-publication-commands/'.$guid;
wysyłam JSON:{"publication":{"action":"END"},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":10884665527},{"id":10884681052},{"id":10884681364}]}]}
status zapytania prawidłowy.
następnie wysyłam zapytanie o status wg guid i otrzymuję HTTP/1.1 200 OK expires: 0 cache-control: no-cache, no-store, max-age=0, must-revalidate x-xss-protection: 1; mode=block pragma: no-cache x-frame-options: DENY trace-id: d1f09c8330b8619e date: Mon, 10 Jan 2022 13:40:35 GMT x-content-type-options: nosniff content-type: application/vnd.allegro.public.v1+json transfer-encoding: chunked {"id":"9763329a-6759-a8d3-9e3c-595967524bc3","taskCount":{"total":3,"success":0,"failed":3}}" 
, aukcje oczywiście nie kończą się. Gdzie jest błąd?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chcesz znać dokładną przyczynę, przez którą zadanie nie zostało wykoanne, korzystaj proszę z [GET /sale/offer-publication-commands/{commandI}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET). W Twoim przypadku dla każdej z ofert zwróciliśmy komunikat `"Offer doesn't belong to seller." , co jest to zgodne z prawdą - request został wysłany przez z tokenem sprzedawcy o id 17139***, a oferty należy do sprzedawcy z identyfikatorem 85208***.

**Comment by marcinja2** [comment]
Dziękuję za podpowiedź! Pozdrawiam Marcin
