### ISSUE TITLE
Zakres znaków dla pól z własnymi wartościami

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5302]
Dzień dobry,

mam szybkie pytanie - jaki jest zakres znaków dla wartości własnych pól? Widzę, że nie przyjmuje on pewnych wartości Unicode np. słowo Wåven powoduje, że nie mogę wystawić aukcji z taką podaną marką własną. Jaki jest zakres Unicode w takim razie?

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
Zgadza się. Dla własnych, tzw. customowych pól - mamy odrębną, zdefiniowaną listę dozwolonych znaków. Jeżeli chodzi o znaki diaktryczne, dozwolone są te poniżej:

`'ä', 'ö', 'ü', 'ø', 'ò', 'ß', '0', 'á', 'č', 'ě', 'í', 'ř', 'š', 'ů', 'ú', 'ý', 'ž', 'œ', 'æ', 'à', 'â', 'ç', 'é', 'è', 'ê', 'ë', 'î', 'ï', 'ô', 'û', 'ù', 'ü', 'ÿ', '€', '×', 'ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż', 'µ', '⌀'`

**Comment by hahyes** [comment]
> Zgadza się. Dla własnych, tzw. customowych pól - mamy odrębną, zdefiniowaną listę dozwolonych znaków. Jeżeli chodzi o znaki diaktryczne, dozwolone są te poniżej:
> 
> `'ä', 'ö', 'ü', 'ø', 'ò', 'ß', '0', 'á', 'č', 'ě', 'í', 'ř', 'š', 'ů', 'ú', 'ý', 'ž', 'œ', 'æ', 'à', 'â', 'ç', 'é', 'è', 'ê', 'ë', 'î', 'ï', 'ô', 'û', 'ù', 'ü', 'ÿ', '€', '×', 'ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż', 'µ', '⌀'`

Dziękuję za odpowiedź, tego właśnie potrzebowałem.
