### ISSUE TITLE
Szczegółowa konfiguracja Allegro_Rest_API   „Krok 2”

### ISSUE THREAD

**Issue by mortumus15** [allegro/allegro-api#5305]
proszę o pomoc w rozwiązaniu błędu autoryzacji REST API

Problem dotyczy błędu przy autoryzacji i przejścia z kroku 1 do kroku 2 - do Szczegółowej konfiguracji Allegro_Rest_API

**Comment by Lukasz-Zurek** [comment]
Opisz proszę Twój problem. Jaki konkretnie błąd otrzymujesz ? Możesz również wysłać przykładowy request i response przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=6a7ab6d0-2364-4a46-86ff-3aafcca487ab&subjectId=2aad59dd-2c45-422e-8fa7-805492e1e06c). Dopisz wtedy, że dane dotyczą wątku #5305 na Githubie. Zweryfikuję to.

**Comment by mortumus15** [comment]
Próbuje skonfigurować system Linker do Integracji allegro z inpost 
Nie przepuszcza mnie do Szczegółowej konfiguracji Allegro_Rest_API   „Krok 2”

Mam wygenerowane w allegro 2 klucze

Autoryzacja zatrzymuje się na Kroku 1 i nie przechodzi dalej do
Szczegółowej konfiguracji Allegro_Rest_API  „Krok 2”

**Comment by Lukasz-Zurek** [comment]
@mortumus15 Czy kontaktowałeś się już z nami za pośrednictwem formularza kontaktowego ? Jeżeli tak - podaj proszę numer zgłoszenia. Otrzymaliśmy bardzo podobną sprawę (wkrótce zostanie udzielona odpowiedź) i jeżeli jest to Twoje zgłoszenie - mógłbym od razu w tym miejscu udzielić Tobie odpowiedzi.

**Comment by mortumus15** [comment]
Próbuje rozwiązać problem już od dłuższego czasu. Pisałem na chacie gdzie odesłaliście mnie do formularza oraz tutaj na github. Jak dotąd sprawa jest przerzucana a jedyna odpowiedź to 
Właśnie zapoznaję się ze sprawą. 
Proszę o chwilę cierpliwości.
Prosimy o cierpliwość. Odpowiemy tak szybko jak to możliwe.
..mógłbym od razu w tym miejscu udzielić Tobie odpowiedzi.

**Comment by Lukasz-Zurek** [comment]
@mortumus15 Trafiłeś w końcu w odpowiednie miejsce, czyli forum, na którym prowadzimy wsparcie w zakresie Allegro API. Twój opis problemu jest jednak zbyt ogólny. Podaj proszę więcej szczegółów z czym masz problem ? Gdzie otrzymujesz błąd ? Co do prośby kontaktu poprzez formularz kontaktowy - jest to standardowa procedura z uwagi na dane wrażliwe dostępne np. w requeście.

Chętnie Tobie pomogę, podaj jednak dane, które potrzebujemy do zweryfikowania tego problemu.

**Comment by mortumus15** [comment]
Udało się połączyć linker ale dostaję taki Błąd! 

Client error: `POST https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=0TpwbQcV2mnUH3X7C7DjvL2Al8wygmSH` resulted in a `400 Bad Request` response: {"error":"invalid_request","error_description":"Invalid device code"}

**Comment by Lukasz-Zurek** [comment]
Ostatnie logi, do których mam dostęp, są z 14.01, 11:55. Dokładnie w tym czasie próbowałeś wykorzystać wskazany device_code do uzyskania tokena. To się jednak nie powiodło i otrzymałeś błąd:

**Error: User has not authorized the device code yet.**.

Oznacza to, że nie poprosiłeś użytkownika Twojej aplikacji o to, aby przeszedł z poziomu dowolnego urządzenia na podany przez ciebie adres (verification_uri) i podał tam kod użytkownika (user_code). Dopiero wtedy mógłbyś z powodzeniem odpytać:

`POST https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=0TpwbQcV2mnUH3X7C7DjvL2Al8wygmSH`

Natomiast **"error": "Invalid device code"** - oznacza w tym przypadku, że Twój device_code jest nieprawidłowy/nieaktualny, ponieważ upłynął już termin jego ważności (**expires_in: "3600"** - ważność takiego kodu upływa po 1 godzinie). Device_code próbowałeś wykorzystać ponownie dopiero po kilku dniach, a konkretnie - 18.01, 13:22. Błąd jest zatem uzasadniony.

W tej sytuacji wygeneruj nowy device_code i user_code. Ten drugi kod powinien od razu trafić do użytkownika. Następnie uzyskaj token.

Zapoznaj się proszę z [naszym poradnikiem](https://developer.allegro.pl/auth/#device-flow-autoryzacja-użytkownika), gdzie opisaliśmy cały proces tej metody autoryzacji, wraz z możliwymi błędami i ich przyczynami.
