### ISSUE TITLE
GET /parcel-management/delivery-services - Funkcja niedostępna. Skontaktuj się z autorem aplikacji.

### ISSUE THREAD

**Issue by netilmedia** [allegro/allegro-api#5307]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Podczas pobierania danych z zasobu GET /parcel-management/delivery-services otrzymuję odpowiedź:

`object(stdClass)#621 (1) {
  ["errors"]=>
  array(1) {
    [0]=>
    object(stdClass)#617 (5) {
      ["code"]=>
      string(17) "NotFoundException"
      ["message"]=>
      string(9) "Not found"
      ["details"]=>
      NULL
      ["path"]=>
      NULL
      ["userMessage"]=>
      string(58) "Funkcja niedostępna. Skontaktuj się z autorem aplikacji."
    }
  }
}`

Proszę o informację czy ten zasób działa prawidłowo, jeżeli nie posiadam własnych umów z przewoźnikami?

**Comment by Lukasz-Zurek** [comment]
Tak, zasób działa prawidłowo w przypadku, gdy nie masz żadnych własnych umów z przewoźnikami. Powinniśmy Tobie zwrócić te usługi, dla których w typie umowy (w polu "owner") jest Allegro.

Podaj proszę trace-id dla tego żądania.
