### ISSUE TITLE
Shipments pomija numery przesyłek przypisane do zamówień

### ISSUE THREAD

**Issue by vibraterton** [allegro/allegro-api#5308]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

W przypadku pobierania przesyłek przypisanych do transakcji paczka z rodzaju **Allegro Pocztex Kurier 48** nie jest pobierana.
https://api.allegro.pl/order/checkout-forms/d2d0d711-748f-11ec-9513-31be157c64e0/shipments

Wynik jest pusty mimo, że do zamówienia jest przypisana paczka (numer zamówienia prawidłowy, można po nim zweryfikować). W przypadku innych zamówień problem nie występuje i numery przesyłek pobierają się poprawnie. 

Trace-id: 72cf1f21207a88b6

**Comment by Lukasz-Zurek** [comment]
@vibraterton Dzięki za zgłoszenie. To zamówienie na chwilę obecną - nie ma przypisanego numeru listu przewozowego. Wyjaśniam to. Wkrótce wrócę z informacją.

**Comment by vibraterton** [comment]
Wedle panelu "Moje allegro" list przewozowy jest przypiany. Tylko po API go nie widać.

**Comment by Lukasz-Zurek** [comment]
@vibraterton Zgadza się, numer przesyłki jest w zamówieniu, w dedykowanej części "Przesyłki", gdzie aktualizowany jest tracking. Jednakże numeru przesyłki nie ma w miejscu "Numery przesyłek". Nasze API pobiera dane właśnie z tego miejsca.

Jest to oczywiście nietypowa sytuacja, dlatego problem przekazałem do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@vibraterton Mieliśmy opóźnienia, które przyczyniły się do opisanej sytuacji. Problem nie powinien już występować. Natomiast wskazane zamówienie ma już przypisany numer przesyłki.

Przepraszamy za utrudnienia.

**Comment by vibraterton** [comment]
Dobrze, będziemy obserwować sytuację

**Comment by vibraterton** [comment]
Problem nie został rozwiązany. Przesyłka do zamówienia (92ea38a1-786b-11ec-8207-3348432caaa2) nadana przez "Moje allegro".
W panelu widnieje w karcie "Przesyłki", jednak nie widnieje wyżej w szczególach zamowienia. Oczywiście numer przesyłki nie pobiera się przez API. 
trace-id: 167eb84242a52355

**Comment by Lukasz-Zurek** [comment]
Ok, dziękuję za zgłoszenie. Sprawę ponownie zgłosiłem do weryfikacji.

**Comment by vibraterton** [comment]
Dobrze, w takim razie czekam na rozwój sytuacji

**Comment by vibraterton** [comment]
Podbijam

**Comment by Lukasz-Zurek** [comment]
@vibraterton Cały czas pracujemy nad wyeliminowaniem tego problemu. Jest on jednak bardziej złożony. Problem obejmuje faktycznie wszystkie zamówienia z wybraną opcją dostawy - Allegro Pocztex Kurier 48. Jak tylko dowiem się czegoś więcej - poinformuję w wątku.

Raz jeszcze przepraszamy za utrudnienia.

**Comment by vibraterton** [comment]
Podbijam

**Comment by Lukasz-Zurek** [comment]
@vibraterton Sprawę nadal wyjaśniamy. Proszę o cierpliwość.

**Comment by vibraterton** [comment]
Dobrze, choć temat trwa dość długo

**Comment by Lukasz-Zurek** [comment]
@vibraterton Przepraszam za długi czas oczekiwania na wyjaśnienie tego problemu. Wynika to głównie z tego, że temat ten analizowany jest zarówno przez zespół po naszej stronie, jak i po stronie Poczty Polskiej. Z tego względu czas weryfikacji jest dłuższy.

**Comment by vibraterton** [comment]
Teraz problem występuje na jeszcze większej ilości przewoźników. Np. traceid 9f7cd3f1ceec94f2.

**Comment by Lukasz-Zurek** [comment]
@vibraterton Dziękuję za kolejne zgłoszenie. Przekazałem do zespołu, który pracuje nad wyeliminowaniem tego problemu.

**Comment by Lukasz-Zurek** [comment]
@vibraterton Skonsultowaliśmy sprawę z Pocztą Polską. Obecnie w przypadku tego przewoźnika, numer przesyłki pojawi się dopiero po nadaniu przesyłki w urzędzie pocztowym, lub po odbiorze przesyłki przez kuriera. Nieprzekazanie numeru przesyłki przez Pocztę Polską - po samym zleceniu wysyłki - nie jest zatem problemem technicznym.

Raz jeszcze przepraszam za wydłużony czas wyjaśniania tych wątpliwości.
