### ISSUE TITLE
dotyczy środowiska sandbox, brak możliwości zalogowania w panelu, informacja: Nie możemy wyświetlić strony  Numer błędu: 544e378c1485a208

### ISSUE THREAD

**Issue by robboh** [allegro/allegro-api#5309]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, problem nie powinien już występować.

**Comment by robboh** [comment]
Czy w efekcie tego problemu mogły się wysypać tokeny ?

**Comment by PrzemyslawLukanowski** [comment]
Nie, nie powinny.
