### ISSUE TITLE
Niezgodność dokumentacji z tutorialem

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#531]
"payment": {
        "id": "1e5c8911-9585-11e8-96ed-27298c74ae02",       -- identyfikator płatności
        "type": "CASH_ON_DELIVERY"                          -- rodzaj płatności, przyjmuje  
                                                            dwie wartości: “ONLINE” lub 
                                                            “CASH_ON_DELIVERY"
    },

type* | CheckoutFormPaymentTypestringPayment typeEnum:[ CASH_ON_DELIVERY, WIRE_TRANSFER, ONLINE ]
-- | --

**Comment by aktywnitu** [comment]
"surcharges": [              
                 {
                   "id": "5b1f4a62-6969-11e8-b090-8b2d9f391430", -- identyfikator dopłaty
                   "type": "ONLINE",
                   "provider": "PAYU"
                   "finishedAt": "2018-06-06T11:11:23.351",      -- data wpłaty (dopłaty)
                   "**price**": {
                   "amount": “12.00”,                            -- wartość dopłaty
                   "currency": "PLN"
                   }
                 }
               ],


surcharges* | [CheckoutFormPaymentReference{id*string($uuid)example: 0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6Payment idtype*CheckoutFormPaymentTypestringPayment typeEnum:Array [ 3 ]providerCheckoutFormPaymentProviderstringPayment providerEnum:Array [ 2 ]finishedAtstring($date-time)example: 2018-10-12T10:12:32.321Date when the event occurredpaidAmount | id* | string($uuid)example: 0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6Payment id | type* | CheckoutFormPaymentTypestringPayment typeEnum:Array [ 3 ] | provider | CheckoutFormPaymentProviderstringPayment providerEnum:Array [ 2 ] | finishedAt | string($date-time)example: 2018-10-12T10:12:32.321Date when the event occurred | paidAmount
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
id* | string($uuid)example: 0f8f1d13-7e9e-11e8-9b00-c5b0dfb78ea6Payment id
type* | CheckoutFormPaymentTypestringPayment typeEnum:Array [ 3 ]
provider | CheckoutFormPaymentProviderstringPayment providerEnum:Array [ 2 ]
finishedAt | string($date-time)example: 2018-10-12T10:12:32.321Date when the event occurred
**paidAmount**

**Comment by MaciejPotepa** [comment]
Dzień dobry
Dzięki za zgłoszenie, ale czy mógł byś wskazać gdzie dokładnie występuje niezgodność? 
Zgłoszenie nie jest zbyt czytelne.

**Comment by aktywnitu** [comment]
Pierwszy błąd:
dwie wartości: “ONLINE” lub
“CASH_ON_DELIVERY"
} - powinny być trzy

Drugi błąd:
price jako atrybut surcharges - powinien być paidAmount

**Comment by MaciejPotepa** [comment]
Nadal Twoje zgłoszenie jest niejasne. O błędach, w którym tutorialu piszesz?
