### ISSUE TITLE
Error on /sale/offer-price-change-commands/ and /sale/offer-quantity-change-commands

### ISSUE THREAD

**Issue by intco** [allegro/allegro-api#5310]
Hi,

I am getting errors regarding missing required attribute (the error is "Fill in the mandatory parameters: Series, Maximum cutting length." ) ​while trying to update only stock or price information using the endpoint /sale/offer-quantity-change-commands and /sale/offer-price-change-commands/

The offer is active and is visible on the marketplace but I still can not update price nor quantity.

Offer id is: 11256444130

Can you please help?

Thank you for your time.

**Comment by Lukasz-Zurek** [comment]
I have already checked some logs for this offer and I can confirm this error. You will have to:

- add a required parameter "Series" (237222),
- add a required parameter "Maximum Cutting Length" (130681),

You can use [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/en/documentation/#operation/getFlatParametersUsingGET_2) to check the structure or the type of these two parameters and if they are mandatory (please look at the **"required"** field). You will find more information in [our guide](https://developer.allegro.pl/en/sale/#parameters).

- adapt to [new terms of return policy](https://developer.allegro.pl/en/news/#return-policy-changed2).

Please remember that if you have tried to update only stock or price, we will always validate all of the information in the offer - so if you have not added any mandatory fields - you will receive an error message.

**Comment by intco** [comment]
Hi,

first of all thank you for the response

I am puzzled by the fact that a seller can have an offer active and visible even if it has not all mandatory parameters set but still can not be able to update its stock and or price

Is this the intended behaviour?

thanks

**Comment by Lukasz-Zurek** [comment]
Yes, it is the intended behaviour. If the seller has listed an offer before we have made changes in the parameters, e.g. making them mandatory - then in such a case like - editing an offer - we will return an error. The Seller will not be able to update stock or price without updating these required parameters. But the offer will still be active if he will decide not to update the offer.

You can check which parameters will be marked as required in the next 3 months. To do this, please use [GET /sale/categories/parameters/required-changes](https://developer.allegro.pl/documentation/#operation/getCategoriesParametersRequireChangesUsingGET_1). We described it right [here](https://developer.allegro.pl/en/my_offers/#how-to-check-future-changes-in-parameters).

**Comment by intco** [comment]
Thank you for your time
