### ISSUE TITLE
Limity zapytań dla GET /sale/products

### ISSUE THREAD

**Issue by podniesm** [allegro/allegro-api#5313]
Jakie są limity zapytań dla endpointu GET /sale/products? Czy działa tam Leaky Bucket?

**Comment by PrzemyslawLukanowski** [comment]
Tak, na tym endpoincie działa Leaky Bucket. Limit nie posiada stałej wartości, dlatego nie udostępniamy informacji o nim.

**Comment by podniesm** [comment]
Mam do wystawienia oferty dla ok1M produktów. Każdy z nich może istnieć w bazie produktowej Allegro więc wymaga to sprawdzenia po Ean lub innej numerze produktu. Jaki sposób/mechanizm wystawienia ofert rekomendujecie w takim przypadku? Oczywiście biorąc pod uwagę limit zapytań i leaky bucket nałożony na GET /sale/products.

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku możesz korzystać z zasobów `/sale/product-offers`, które [wczoraj udostępniliśmy w wersji public](https://developer.allegro.pl/news/#product-offers-public). Przez `POST /sale/product-offers` wystawisz aktywną ofertę połączoną z produktem, używając jednego requesta - nie musisz w tej sytuacji używać `POST /sale/images` (aby najpierw przesłać zdjęcia na nasz serwer) ani `PUT /sale/offer-publication-commands/{commandId}` (aby aktywować ofertę). Ofertę połączysz z produktem, jeśli:
 - wskażesz bezpośrednio EAN lub identyfikator produktu w polu `productSet.product.id`;
 - jeśli przekażesz nam dane produktu w strukturze `productSet.product` - w tej sytuacji albo utworzymy nowy produkt (jeśli na podstawie przekazanych nie znajdziemy go w naszej bazie) albo połączymy z istniejącym w  Katalogu Allegro (jeśli na podstawie przekazanych danych zidentyfikujemy produkt w naszej bazie).

Więcej informacji na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/).
