### ISSUE TITLE
Wartości dla parametru 247611

### ISSUE THREAD

**Issue by Troom** [allegro/allegro-api#5315]
Proszę o informacje w jaki sposób powinienem zmapować wartości dla parametru 247611 (Język). Podczas próby sprzedaży karty z wartościa French, karta jest wystawiona prawidłowo. W przypadku karty w języku Chinese Simplified CH, karta jest odrzucana z komunikatem:

> message=Invalid parameter Language (247611) value for offer with product. Value should be "angielski".

Języki które są wykorzysytwane w sprzedazy MTG to:

            "LanguageName" : "English",
            "LanguageCode" : "EN" 

            "LanguageName" : "Chinese Simplified",
            "LanguageCode" : "CH"

            "LanguageName" : "Chinese Traditional",
            "LanguageCode" : "TW"

            "LanguageName" : "French",
            "LanguageCode" : "FR"

            "LanguageName" : "German",
            "LanguageCode" : "DE"

            "LanguageName" : "Italian",
            "LanguageCode" : "IT"

            "LanguageName" : "Japanese",
            "LanguageCode" : "JP"

            "LanguageName" : "Korean",
            "LanguageCode" : "KO"

            "LanguageName" : "Portuguese (Brazil)",
            "LanguageCode" : "PT"

            "LanguageName" : "Russian",
            "LanguageCode" : "RU"

            "LanguageName" : "Spanish",
            "LanguageCode" : "SP"

            "LanguageName" : "Other",
            "LanguageCode" : "OT"

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykład wywołania, które wysyłasz (wraz z trace-id) - bez tego trudno mi się odnieść do Twojego problemu, ponieważ parametr ten występuje w 15 kategoriach, a komunikat błędu jest stricte związany z konkretnym produktem.

**Comment by Troom** [comment]
Request
Ograniczam sie tylko do problemartycznego parametru
![image](https://user-images.githubusercontent.com/10126507/149925552-41826d02-9478-456f-8e00-69c7719e5d32.png)

Response
![image](https://user-images.githubusercontent.com/10126507/149925598-3181d6ae-9080-4658-a359-a72166da55ef.png)


trace-id: 16e51cac328121dc

**Comment by MaciejFrackowiak** [comment]
Produkt, który przypisujesz do oferty (id=2ab27817-de88-4a49-931c-1d04f6cc1d6f) w swoich parametrach produktowych ma wartość:
```
{
            "id": "247611",
            "name": "Język",
            "valuesLabels": [
                "angielski"
            ],
            "values": [
                "angielski"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": true
            }
        }
```

W związku z tym, łącząc ofertę z produktem może mieć ona określony język wyłącznie jako angielski - stąd komunikat błędu o niewłaściwej wartości.
Jeżeli uważasz, że dany produkt powinien posiadać inne dane, możesz to zgłosić korzystając z [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal) lub poprzez formularz na stronie WWW - https://allegro.pl/offer/product/report/{productId}.
