### ISSUE TITLE
Pytanie odnośnie pobierania danych z allegro zewnętrznym programem

### ISSUE THREAD

**Issue by Wojtbart** [allegro/allegro-api#5317]
Potrzebuję stworzyć taki program, który wejdzie na allegro i pobierze informację o produkcie (web scraping), jednak gdy próbuję pobrać dane ze strony objętnie jakiego produktu dostaję błąd 503 service unavailable. Gdy wysyłam zapytanie postmanem to dostaję odpowiedź Please enable JS and disable any ad blocker i teraz pytanie czy trzeba coś jeszcze zrobić aby pobierac dane ze strony?

**Comment by MaciejFrackowiak** [comment]
Do wywołania zasobów API Allegro służy adres https://api.allegro.pl/ (lub https://api.allegro.pl.allegrosandbox.pl/ na Sandbox).

**Comment by Wojtbart** [comment]
Dziękuję za odpowiedź

**Comment by PawelW0** [comment]
Mam dostęp do API ale mam wrażenie, że system pozwala na dostęp do swoich ofert, swoich produktów i ich danych. Czy można zatem uzyskać dostęp do innych-obcych ofert?

**Comment by MaciejFrackowiak** [comment]
@PawelW0 Jest to właściwe działanie - masz dostęp do swoich ofert i ich szczegółów. Możesz również przeglądać produkty z Katalogu produktów za pośrednictwem [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Natomiast dostęp do [wyszukiwarki ofert w API](https://developer.allegro.pl/documentation/#tag/Public-offer-information) wymaga zweryfikowania Twojej aplikacji. Aby poznać szczegóły skontaktuj się ze swoim opiekunem jeśli go posiadasz lub poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
