### ISSUE TITLE
Get seller offers and redirect traffic

### ISSUE THREAD

**Issue by MaciejFrackowiak** [allegro/allegro-api#5319]
### Discussed in https://github.com/allegro/allegro-api/discussions/5318

<div type='discussions-op-text'>

<sup>Originally posted by **clementmouret** January 17, 2022</sup>
Hello Allegro's team,

We would like to redirect traffic from our customer website to his Allegro seller shop. Which API we can use to get for a specific seller the list of the offer and for each offer:
- the product details (images, URL, ...)
- the availability and price

I found this tutorial = >https://developer.allegro.pl/en/listing/

Is it the good approach? The redirection link seems missing in the response, how to get it?

Thanks in advance for your help.

Best regards,
Swaven Team</div>

**Comment by MaciejFrackowiak** [comment]
According to our [Terms & Conditions](https://developer.allegro.pl/en/rules/), article 4.1.c you are not permitted to present Allegro offers on third-party sites.
Also, [GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) resource is not available for everyone - you have to verify your application to get access to it.

**Comment by clementmouret** [comment]
Hello, thanks for your return.

After clarification with our customer and his Allegro account manager, our customer is authorized to display the Allegro logo with a link to Allegro.pl customer shop product page (and not offers) and start to redirect high qualified traffic to Allegro. How can we use the API to get the product links and availability of our customer product catalog? We've created an app in the sandbox environment, but we can't figure out how to get product catalog, neither how to create a token as you don't have/need any shopper signin process (https://developer.allegro.pl/auth/#app).

Thank you for your help.
Best regards,
Swaven Team

**Comment by MaciejFrackowiak** [comment]
I answered in the post https://github.com/allegro/allegro-api/issues/5474.
