### ISSUE TITLE
Łączenie z katalogiem dla producenta

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#5320]
W jaki sposób mam łączyć produkty z katalogiem produktów jeśli jestem ich producentem ? 
Chodzi o to że jak szukam produktu przez sale/products?ean=X to albo znajduje 0 produktów albo moją aukcje - podczas testów sprawdzałem na istniejących aukcjach.
Co w takim przypadku ? 
Jak nie podam tego product.id to muszę w panelu allegro dla każdej aukcji wejść w wiązanie i kliknąć zapisz, a jak chciałbym je podać to i tak nie mam czego podać.

**Comment by MaciejFrackowiak** [comment]
W przypadku, gdy danego produktu nie ma w naszej bazie:
1) możesz złożyć propozycję jego dodania korzystając z [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct)  - jeżeli dodamy produkt do bazy, to wówczas będziesz mógł już przypisać jego ID do oferty korzystając z [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) - proces opisaliśmy w [naszym poradniku](https://developer.allegro.pl/productization/#5-jak-doda%c4%87-produkt);
2) możesz wystawić nową ofertę od razu korzystając z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), gdzie od razu stworzymy odpowiedni produkt do bazy produktowej - i tu również zachęcam do spojrzenia do [poradnika](https://developer.allegro.pl/product_offers/#jak-wystawi%c4%87-ofert%c4%99-z-produktem-kt%c3%b3rego-nie-ma-w-naszej-bazie).
