### ISSUE TITLE
Problem z ofertami

### ISSUE THREAD

**Issue by quadowaniepl** [allegro/allegro-api#5321]
Dzień dobry, 
czy mógłbym uzyskać odpowiedź jaka aplikacja wznawia moje oferty? 
Przykładem takiej aukcji jest oferta z numerem 11708685370.
Korzystam z zewnętrznego serwisu do zarządzania aukcjami (baselinker) i tylko za jego pomocą wystawiam aukcje.
Miałem już taki problem, otrzymałem odpowiedź od Allegro, że aukcje dodawane były przez API.
Proszę o pomoc w tej sprawie.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Oferta została automatycznie wznowiona, ponieważ we wcześniejszej ofercie nr 6789825965 miałeś włączoną opcję automatycznego wznowienia po jej zakończeniu.

**Comment by quadowaniepl** [comment]
Czyli mam rozumieć, że najlepiej wyłączyć wznawianie automatyczne po zakończeniu? Czy aukcje, które zakończą się z powodu stanu na magazynie równego 0 wznowią się automatycznie pod tym samym numerem? Chce zostawić jedynie opcję taką, że w momencie zejścia stanu magazynowego na zero aukcja się zakończy, a gdy znowu pojawi się na magazynie system ją wznowi pod tym samym numerem, który jest w systemie baselinker. Jak to wygląda w praktyce?

**Comment by MaciejFrackowiak** [comment]
Jeżeli nie chcesz, aby po zakończeniu oferty wznowiła się ona automatycznie z pełną liczbą przedmiotów to należy opcję wyłączyć. Oferty automatycznie nie wznawiają się z tym samym numerem oferty, zawsze otrzymują nowe ID.
Opcja, o której piszesz w drugiej części to ponowna aktywacja oferta (opcja Wznów w serwisie WWW) po uzupełnieniu stanu magazynowego - nie jest to tożsame co automatyczne wznowienie.

**Comment by quadowaniepl** [comment]
Okej, dzięki za wyjaśnienie.
Pozdrawiam
