### ISSUE TITLE
[Sandbox] Odroczona płatność dla Firm - włączenie usługi vol.2

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#5323]
Dzień dobry, konta ComarchSandbox1 i comarchesklep miały aktywne płatności w wątku #4116, aktualnie nie znalazłem metody żeby to aktywować:

Oferta 7684732347od comarchesklep pokazuje, ze jest płatność odroczona, ale kupić z konta ComarchSanbox1 się nie da:
![image](https://user-images.githubusercontent.com/8465007/149947696-49584865-fc65-4ae9-992d-2aa516a0737b.png)

Proszę o ponowne włączenie płatności odroczonych dla kont: comarchesklep oraz ComarchSandbox1

**Comment by Lukasz-Zurek** [comment]
Sprawę zgłosiłem do odpowiedniego zespołu. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
Odświeżyliśmy wskazane przez Ciebie konta testowe. Daj proszę znać czy możesz już testować płatności odroczone.

**Comment by alekskuc** [comment]
Witam, dalej nie działa z tym samym komunikatem. Bez znaczenia które konto jest sprzedawcą.

oferta 7684478227
![image](https://user-images.githubusercontent.com/8465007/150152376-c3d1435b-1e2b-4698-af2f-2b57cfc81e51.png)
ComarchSandbox1 ma takie informacje w sekcji z płatnością odroczoną:
![image](https://user-images.githubusercontent.com/8465007/150153866-d13597fb-2b1e-4eaf-b1b7-16211ae3523b.png)


oferta 7684732347
![image](https://user-images.githubusercontent.com/8465007/150152445-4b88e874-48d4-4845-b1c0-6e2217b02e7b.png)
comarchesklep ma takie stare informacje w sekcji z płatnością odroczoną:
![image](https://user-images.githubusercontent.com/8465007/150153572-2665add3-c413-47da-a738-55e790035290.png)
![image](https://user-images.githubusercontent.com/8465007/150153520-04f55a41-d01c-42c6-be8b-773913a68ba6.png)

**Comment by Lukasz-Zurek** [comment]
Jeśli chodzi o konto - ComarchSandbox1 - wybrałeś wcześniej jako rodzaj działalności: "Inny" i to było problemem. Zmieniłem na spółkę S.A. i płatności odroczone na tym koncie masz już aktywne.

Problem jest z kontem - comarchesklep i tu chciałbym zapytać czy moglibyśmy wyczyścić Tobie to konto testowe, abyś mógł ponownie od początku przejść przez proces aktywacji odroczonych płatności ?

**Comment by alekskuc** [comment]
Witam, ponownie otwieram wątek, bo dziś przestały działać płatności odroczone, które wczoraj prawidłowo dało się opłacić na sandboxie.

Na przykład zamówienie nr 75ac5420-7ab5-11ec-848f-09750657a993 przy próbie "Płacę później" ma taki błąd:

![Uploading image.png…]()

Proszę o weryfikację, bo nie zdążyliśmy nawet dokończyć wszystkich testów, a przestało działać.

**Comment by Lukasz-Zurek** [comment]
@alekskuc Dziękuję za zgłoszenie. Przekazałem dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@alekskuc Pragma odrzuciła tę płatność na swoim środowisku testowym. Wyjaśniliśmy już to z nimi. Ponów proszę płatność.

**Comment by alekskuc** [comment]
Zadziałało, @Lukasz-Zurek dziękuję.
