### ISSUE TITLE
409 Produkt z takimi danymi już istnieje - ale API wskazuje na inny produkt

### ISSUE THREAD

**Issue by damianopi** [allegro/allegro-api#5324]
Proszę o informację w jaki sposób sprawić, żeby API rozróżniało dwa produkty w kategorii 121604, jeśli rozmiar produktów jest taki sam, a różni je jedynie gatunek stali, kod produktu oraz EAN. Tytuł oraz opis w obu przypadkach są do siebie podobne jednak kod produktu i gatunek stali się różnią. To nie są te same produkty. Przykładowo: 

Przy próbie dodania produktu:
name: Rura nierdzewna bezszwowa 12x2mm 1.4541 100cm
ean: 5908279154682
kod produktu: S-RR-OS/012.00X02.00/1.4541

dostaję błąd 409: "Produkt z takimi danymi już istnieje", który wskazuje na inny produkt:
name: Rura nierdzewna duplex 12 x 2mm 1.4462 100cm
ean: 5908279102461
kod produktu: S-RR/012.00X02.00/1.4462

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, dla którego otrzymałeś błąd 409.

**Comment by damianopi** [comment]
'trace-id': '902baf7eddc1b7c4'

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład. Skontaktowałem się z zespołem odpowiedzialnym za zarządzanie bazą produktów - dokonane zostały zmiany w regułach identyfikacji duplikatów. Tym samym problem nie powinien już występować na podobną skalę.

**Comment by damianopi** [comment]
Dziękuję za pomoc!
