### ISSUE TITLE
Opłata utrzymaniowa - jak sprawdzić od kiedy będzie naliczana

### ISSUE THREAD

**Issue by krzyche** [allegro/allegro-api#5325]
Cześć, 
Korzystając z zasobu `https://api.allegro.pl/pricing/offer-quotes` mogę sprawdzić jakie opłaty cykliczne naliczane są dla moich ofert. Jak sprawdzić jednak od kiedy nastąpi naliczanie opłaty utrzymaniowej. Załóżmy że od pół roku nikt nie kupił na mojej aukcji. Korzystając z tego zasobu nie zobaczę, że za pół roku planowana jest opłata utrzymaniowa. Zasób zwraca odpowiedź, w przypadku kiedy jest już niewiele czasu do pobrania tej opłaty. Dobrze myślę, czy robię coś nie tak?

**Comment by MaciejFrackowiak** [comment]
Zgadza się, ten zasób nie powie Tobie, że za xx dni zaczniemy naliczać opłatę utrzymaniową - zasób zwraca informacje o najbliższych cyklach 10 dniowych. Jeśli chcesz posiadać taką informację to musisz we własnym zakresie zapisywać datę ostatniej sprzedaży w danej ofercie i względem niej obliczać 365 dni do naliczania opłaty utrzymaniowej.
