### ISSUE TITLE
/messaging/threads i AccessDenied

### ISSUE THREAD

**Issue by Kokoscanfly** [allegro/allegro-api#5326]
Witam,
chciałem dzisiaj zabrać się za dodanie do autorskiego systemu modułu zarządzania wiadomościami lecz już na samym początki dostaje taką oto odpowiedź.

Response status code: 403 {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]}

Do wywołania wykorzystuje php i taki kod
`function getMessaging(String $token)
{
    $getMessaging = "https://api.allegro.pl/messaging/threads";

    $ch = curl_init($getMessaging);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
         curl_setopt($ch, CURLOPT_HTTPHEADER, [
            "Authorization: Bearer $token",
                "Accept: application/vnd.allegro.public.v1+json"
         ]);

    $getMessagingResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($getMessagingResult === false || $resultCode !== 200) {
                echo "Response status code: $resultCode\n";
                echo $getMessagingResult;
                exit;
    }

    $result = json_decode($getMessagingResult, true);

    return $result;
}`

Pytanie czy mam zablokowany dostęp czy robie coś źle ? W dokumentacji nie znalazłem informacji, aby tylko zweryfikowane aplikacje miały dostęp do zasobu messaging

**Comment by MaciejFrackowiak** [comment]
Zasoby centrum wiadomości są dostępne dla każdego - kluczowe jest jednak, aby aplikacja posiadała scope "allegro:api:messaging" odpowiedzialny za obsługę centrum wiadomości. Sprawdź proszę, czy Twoja aplikacja posiada odpowiedni scope - sprawdzisz to na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/).

**Comment by Kokoscanfly** [comment]
@MaciejFrackowiak posiada
<img width="1185" alt="Zrzut ekranu 2022-01-19 o 10 15 25" src="https://user-images.githubusercontent.com/57533095/150100412-b84a2334-78af-496b-b76e-caed14681936.png">

**Comment by MaciejFrackowiak** [comment]
Zatem proszę podaj mi trace-id Twojego wywołania, spojrzę w logi.

**Comment by Kokoscanfly** [comment]
Dobra, trzeba usunąć wątek. Okazało się zamiast podawać token to tylko wywoływałem go. Mój błąd. Przepraszam.
