### ISSUE TITLE
AccessDenied - problemy ze scopami

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5327]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Używamy autoryzacji DCR, od ponad tygodnia przy próbie połączenia nowych kont mamy problemy autoryzacyjne. Konto allegro ma włączoną autoryzację dwuetapową, w requescie autoryzacyjnym podajemy scopy
&scope=allegro:api:profile:read%20allegro:api:profile:write%20allegro:api:sale:offers:read%20allegro:api:sale:offers:write%20allegro:api:orders:read%20allegro:api:orders:write%20allegro:api:ratings%20allegro:api:disputes%20allegro:api:messaging%20allegro:api:billing:read%20allegro:api:payments:read%20allegro:api:payments:write%20allegro:api:sale:settings:read%20allegro:api:sale:settings:write%20allegro:api:campaigns

w odpowiedzi dostajemy 
https://allegro.pl/auth/oauth/#error=invalid_scope&error_description=Invalid%20scope:%20allegro:api:billing:read&scope=e7e7c002ddb441d7a7c8793161d92f49

<oauth>
<error_description>Full authentication is required to access this resource</error_description>
<error>unauthorized</error>
</oauth>

Przy usunięciu scopa z requestu efekt taki sam wartoscią invalid_scope ustawiona na kolejny scope.
Próba ustawienia poprzez stronę  https://apps.developer.allegro.pl/ dostępów do scopów aplikacji skutkuje błędem:
Wystąpił błąd podczas edytowania aplikacji.
Spróbuj za chwilę ponownie edytować aplikację.

Czy trzeba wykonać jeszcze jakiś krok, bo nic w dokumentacji nie możemy znaleźć na ten temat.

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem najnowsze logi i nie zwracamy już błędów. Daj proszę znać czy problem nadal występuje. Dotyczy to również błędów na stronie https://apps.developer.allegro.pl/. Jeśli tak - sprawę zgłoszę od razu do odpowiednich zespołów.

**Comment by d3stozaur** [comment]
Niestety w dalszym ciągu jest to samo.

**Comment by Lukasz-Zurek** [comment]
Jest to błąd po naszej stronie. Aktualnie pracujemy nad rozwiązaniem problemu.

Przepraszamy za utrudnienia.

**Comment by d3stozaur** [comment]
@Lukasz-Zurek znany jest termin rozwiazania problemu?

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Niestety nie znam terminu, aczkolwiek sprawa ta ma wysoki priorytet. Jak tylko uda nam się wyeliminować błąd - poinformuję Cię o tym w wątku.

**Comment by Lukasz-Zurek** [comment]
@d3stozaur Wdrożyliśmy poprawkę i problem nie powinien już występować.

Raz jeszcze przepraszamy za zaistniałe utrudnienia.
