### ISSUE TITLE
401 przy próbie odświeżenia access_token-a

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#5330]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie odświeżenia access_token-a za pomocą metody https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhb...
ciągle zwraca kod błąd 401 Unauthorized
mimo tego że wywołania metod z API działają normalnie

**Comment by MaciejFrackowiak** [comment]
Sprawdź proszę, czy wykorzystujesz właściwy refresh token (ostatni z uzyskanych). Jeżeli problem nadal będzie występować, to proszę przekaż do nas szczegóły swoich wywołań poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) (dopisz proszę numer wątku z GitHub - 5330).
