### ISSUE TITLE
[allegro/allegro-api]Can I appeal the account of the software developer?

### ISSUE THREAD

**Issue by keguangqiang** [allegro/allegro-api#5332]
Hello, we are a Chinese ERP software server provider. We want to connect the allegro function into our system and open it to Chinese sellers. Is there an application channel?

**Comment by MaciejFrackowiak** [comment]
Of course, you can integrate with our API - whole documentation of Allegro API you can find [here](https://developer.allegro.pl/en/documentation/). Also, please check the information on our [developer portal](https://developer.allegro.pl/en/).
