### ISSUE TITLE
Logo Allegro

### ISSUE THREAD

**Issue by MagdaMusial** [allegro/allegro-api#5336]
Witam,
Skąd możemy pobrać oficjalne logo Allegro? Czy mają Państwo jakieś wspólne logo Allegro + InPost?

**Comment by MagdaMusial** [comment]
Ewentualnie czy wymagają Państwo podpisania jakiegoś dokumentu regulującego wyświetlania Państwa Logo na stornie aplikacji do zamawiania kuriera ( InPost Allegro Kurier i InPost Allegro PAczkomaty) Logo prezentowane tylko w miejscu wyboru kuriera czy zlecenie będzie realizowane przy użyciu InPost czy InPost Allegro.

**Comment by MaciejFrackowiak** [comment]
Temat wykorzystania logo Allegro wykracza poza nasze możliwości tj. wsparcie zasobów API Allegro. W tej kwestii proszę skontaktuj się bezpośrednio z [serwisem](https://allegro.pl/pomoc/kontakt?kategoria=9cac1ea5-38cd-4d58-92a4-2953cc1aad26&subjectId=41ea0914-0a2e-4d57-b96e-c832b333b0f3).
