### ISSUE TITLE
Odłączanie produktów od ofert poprzez API

### ISSUE THREAD

**Issue by Sahqiel** [allegro/allegro-api#5337]
Dzień dobry,
od pewnego czasu mam problem, że część moich ofert jest odłączana od produktów. Mogę dodać je ponownie, ale po kilku dniach ponownie są odłączane. Pisałem w tej sprawie do allegro czemu są odłączane i dostałem odpowiedź, że API to robi. Dostałem w odpowiedzi taką informację: 

"**Dziękuję Panu za wiadomość.

Sprawdziłam poniższe oferty:
11548975038 produkt usunięty z oferty przez API
11548707318 produkt usunięty z oferty przez API
(i inne)

Nie jestem w stanie podać dokładnego powodu, nie było to usunięcie wykonane przez Allegro.

Proponuję skontaktować się z API.**"

Co mogę w takiej sytuacji zrobić? Korzystamy z API i pytałem o to programisty, ale napisał, że my nie mamy na to wpływu. 

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Z dostępnych mi danych wynika, że odłączenie produktów od wskazanych ofert nastąpiło w pierwszej połowie grudnia. Nie mamy jednak dostępu do szczegółowych logów. Prześlij proszę oferty, w których do odpięcia produktów doszło w ostatnim czasie (najlepiej w ostatnich dniach). Zweryfikuję to po naszej stronie.

**Comment by Sahqiel** [comment]
Ok to podepnę je z powrotem i dam znać. Od grudnia nie łączyłem ich ponownie bo w kółko się odłączały. 

Pozdrawiam

**Comment by krowek** [comment]
@Sahqiel czy udało się rozwiązać problem? U mnie również produkty są odłączane od ofert

**Comment by Lukasz-Zurek** [comment]
@krowek Podaj proszę przykładowe oferty - przyjrzę się temu.

@Sahqiel Jeżeli problem nadal się powtarza - również proszę Cię o wskazanie nowych przykładów.
