### ISSUE TITLE
Czy "List messages in thread" jest cachowane i może zwracać starszą listę wiadomości niż to wynika z lastMessageDateTime wątku?

### ISSUE THREAD

**Issue by MaciejFrackowiak** [allegro/allegro-api#5339]
### Discussed in https://github.com/allegro/allegro-api/discussions/5335

<div type='discussions-op-text'>

<sup>Originally posted by **tomasz-grzesik** January 20, 2022</sup>
Drodzy programiści Allegro,

Czy "List messages in thread" jest cachowane i może zwracać starszą listę wiadomości niż to wynika z lastMessageDateTime wątku?

</div>

**Comment by tomasz-grzesik** [comment]
Dzięki za przeniesienie tematu.

**Comment by MaciejFrackowiak** [comment]
Co do zasady taka sytuacja nie powinna mieć miejsca - jeśli jednak zauważyłeś taki proceder, to prosiłbym o podanie przykładowego id wątku, wówczas wraz z zespołem odpowiedzialnym za zasób zweryfikujemy to.

**Comment by tomasz-grzesik** [comment]
Podaję przykładowy wątek:
Thread_id: FwjxcNl8wDMewm6qIyICvzatbt96lr10o8BHPczuksd

Nie widoczna przez kilka godzin wiadomość z godziny: 
'createdAt': '2022-01-19T14:11:10.313Z'

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład, przekazuję do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Wracam z kluczowym pytaniem - czy lastMessageDateTime wskazywało na wiadomość z 14:11, podczas gdy nie była ona obecna w liście wiadomości?

**Comment by tomasz-grzesik** [comment]
Nie koniecznie. Może to być również efektem opóźnienia w aktualizacji tego pola. Wrócę z odpowiedzią, jak tylko znajdę kolejny przypadek z taką informacją w logach..

**Comment by tomasz-grzesik** [comment]
Przejrzałem kod i jednak wynika z niego to, że lastMessageDateTime musiałbym w tym przypadku uaktualniony. Jeszcze dziś podeślę świeży przykład.

**Comment by tomasz-grzesik** [comment]
Kolejny przykład, który pokazuje anomalię.
thread_id: hPbf5tOiX9IAv9cHq795W3z9LIjxCzqlnEJHkDnvmXM

Wiadomość z godziny: '2022-01-21T09:37:01.570Z'
nie widoczna przez kilka godzin - w tym czasie ostatnia wiadomość z wątku jest z godziny 2022-01-21T09:36:23.000Z.

**Comment by tomasz-grzesik** [comment]
Takich przykładów mogę podesłać więcej. Niestety uważam to za ważny błąd, który wymaga interwencji.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za szczegóły, przekazuję do weryfikacji.

**Comment by MaciejFrackowiak** [comment]
Wracam z wynikami analizy:
- w podanym wątku widać wiadomość zatrzymaną przez bota Allinę i puszczoną przez wysyłającego po około 3 godz. od momentu, kiedy została zatrzymana;
- prawidłowym zachowaniem jest to, że ze swojej strony odbiorca nie zobaczy takiej wiadomości do tego momentu i czas ostatniej wiadomości (przy pobraniu info o wątku) będzie dla niego wskazywał też poprzednią wiadomość do tego momentu;
- kiedy wysyłający zorientuje się, że wiadomość została zatrzymana przez Allinę i kliknie “tak, wysyłam” żeby potwierdzić, że na pewno chce ją wysłać, to dopiero wtedy odbiorca może przy pobraniu info o wątku zobaczyć jej czas utworzenia (pierwotnego utworzenia - nie puszczenia) jako czas ostatniej wiadomości i dopiero wtedy może zobaczyć ją przy pobraniu wiadomości w tym wątku;
- czasy odpowiedzi dla statystyk jakości sprzedaży dla takiej wiadomości są liczone od momentu kiedy odbiorca może zobaczyć taką wiadomość (od momentu kiedy wysyłający przepchnie wiadomość zatrzymaną przez Allinę do wysyłki) - dodatkowo w tym momencie wysyłane jest powiadomienie mailowe o nowej wiadomości do odbiorcy - więc tu nie powinno być zagrożenia wpływem na tę statystykę.

Takie zachowanie jest intencjonalne, zgodne z założeniami, po to, żeby wiadomości puszczone po zatrzymaniu przez Allinę nie zaburzały chronologii w wątku (hipotetycznie mogłoby to pomieszać komunikację i doprowadzić do nieporozumień jeśli byłoby inaczej).

W najbliższej przyszłości planujemy prace nad limitem czasu w jakim wysyłający może puścić wiadomość zatrzymaną przez Allinę - Pańskie zgłoszenie nie jest pierwszym i dlatego podejmiemy próbę rozwiązania tego problemu.

Jeżeli jednak, mimo powyższych wyjaśnień wg Pana data ostatniej wiadomości przy pobraniu szczegółów wątku wskazuje na wiadomość, której nie widać w wątku przy pobraniu wiadomości dla tego wątku to prośba o informację - wówczas będziemy musieli przeprowadzić dalszą weryfikację.

**Comment by tomasz-grzesik** [comment]
Dziękuję za szczegółowe wyjaśnienia. Istotny jest fragment:
 jej czas utworzenia (pierwotnego utworzenia - nie puszczenia) " - niestety ale taka wiadomość w sortowaniu od najnowszej może nie być widoczna np. w komunikatorze. Bez sensu również, aby skanować wszystkie wiadomości. 
 
 Według mnie puszczenie wiadomości oznacza datę jej wysłania, czy utworzenia i taka też data powinna zostać zwrócona przez API. W innym przypadku powoduje to masę komplikacji.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za feedback. Będziemy w przyszłości pracować nad ograniczeniem tego typu sytuacji.

**Comment by tomasz-grzesik** [comment]
Jeśli chodzi o różnice między lastMessageDateTime wątku a createdAt ostatniej wiadomości to problemu tutaj nie ma poza wyjątkami, gdzie wiadomość ma status BLOCKED i różnica czasu jest w drugą stronę createdAt  > lastMessageDateTime. Tutaj nie widzę jednak problemu.

Natknąłem się jednak na inny błąd: Id wiadomości (nie wątku): hSUpAex4laMH72UR7m7md4pQw4AHOMXYafiJMaRuSlO
'interlocutor': None

**Comment by MaciejFrackowiak** [comment]
Po wstępnej weryfikacji sytuacja wygląda następująco:
- czy podany identyfikator "hSUpAex4laMH72UR7m7md4pQw4AHOMXYafiJMaRuSlO" dotyczy wiadomości? - ID wiadomości są w formacie UUID, podany przez Ciebie identyfikator wygląda jednak na ID wątku;
- jaki endpoint z jaką metodą i jakimi parametrami odpytywałeś otrzymując ww. odpowiedź? Tu prośba, abyś podesłał nam pełne wywołanie i odpowiedź (z trace-id) w postaci cURL - dane podeślij proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) podając numer wątku GH 5339.

**Comment by tomasz-grzesik** [comment]
Przepraszam. Podany ID dotyczy jednak wątku, a nie wiadomości:
{'id': 'NS82GRBioESseBZoXvhkZoF4r26wmtJRkn9BHXH58wS', 'read': True, 'lastMessageDateTime': '2022-01-24T09:02:36.000Z', 'interlocutor': None}

**Comment by MaciejFrackowiak** [comment]
W podanych przykładach doszło do usunięcia konta użytkownika występującego jako "interlocutor" - efektem tego jest zwracana wartość None. W samej dokumentacji mieliśmy błąd - to pole powinno widnieć jako opcjonalne, a nie wymagane. Stosowna zmiana została już naniesiona do dokumentacji.

**Comment by tomasz-grzesik** [comment]
tak też myślałem. Dziękuję za weryfikację.

**Comment by tomasz-grzesik** [comment]
@MaciejFrackowiak jeśli chodzi o uzasadnienie:

`"Takie zachowanie jest intencjonalne, zgodne z założeniami, po to, żeby wiadomości puszczone po zatrzymaniu przez Allinę nie zaburzały chronologii w wątku (hipotetycznie mogłoby to pomieszać komunikację i doprowadzić do nieporozumień jeśli byłoby inaczej)."`

To nie przemawia do mnie. Chronologia i tak jest zaburzona bo nie przepuszczanie wiadomości, a to czy się pojawi zależy od dodatkowej akcji Wysyłającego. Widocznie należy poprawić UI lub dodać dodatkowe powiadomienia, aby Użytkownik wiedział o zablokowanej wiadomości. A najlepszym rozwiązaniem byłoby zablokowanie bez możliwości przepuszczenia już po zamknięciu strony z wątkiem, czy też pojawienia się nowych wiadomości. W ten sposób Użytkownik będzie musiał jeszcze raz wysłać wiadomość, którą z łatwością dostrzeże Sprzedawca - nikt nie będzie czytał wiadomości wstecz.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twój punkt widzenia. Jak wspomniałem we wcześniejszym poście zespół odpowiedzialny za funkcjonalność będzie przyglądać się ewentualnym możliwym zmianom w zasobach.

**Comment by tomasz-grzesik** [comment]
Czy aktualnie istnieje jakiś limit czasu, do którego Użytkownik może wysłać zablokowaną przez Allegro wiadomość?

**Comment by MaciejFrackowiak** [comment]
Obecnie taki limit nie istnieje. Planujemy go wprowadzić, jednak póki co nie posiadam żadnych konkretów.

**Comment by tomasz-grzesik** [comment]
Ok. Warto wprowadzić, gdyż zaburza to chronologię przeglądanych wiadomości.--Sent from Yandex.Mail for mobile03.02.2022, 13:50, "MaciejFrackowiak" ***@***.***>:
Obecnie taki limit nie istnieje. Planujemy go wprowadzić, jednak póki co nie posiadam żadnych konkretów.

**Comment by tomasz-grzesik** [comment]
Ponawiam prośbę o rozwiązanie problemu - wprowadzenie limitu czasu na odblokowanie wiadomości, a najlepiej na ustawienie czasu wysyłki wiadomości czasem odblokowania.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem już wcześniej - planujemy dokonać zmian w działaniu mechanizmu, jednak na chwilę obecną nie mogę wskazać żadnego konkretnego terminu zmiany i dokładniejszych szczegółów.

**Comment by MaciejFrackowiak** [comment]
Wprowadzony został limit 24 godzin.

**Comment by tomasz-grzesik** [comment]
Dziękuję.
