### ISSUE TITLE
Allegro Smart w WebAPI?

### ISSUE THREAD

**Issue by gumis496** [allegro/allegro-api#534]
Szanowni Państwo,

Kiedy przewidują Państwo dołączenie do danych aukcji w WebAPI informacji, czy dana aukcja jest objęta programem Allegro Smart?

Z poważaniem,
Michał Kijewski
CTO w Dealavo Sp. z o. o.

**Comment by AniaMalinowska** [comment]
Nie przewidujemy tego w WebAPI. Co do REST API - prosimy podać do czego (z perspektywy sprzedawcy) wykorzystałbyś taką informację?

**Comment by gumis496** [comment]
@AniaMalinowska Chciałbym móc przeanalizować, jak ta opcja wpływa na sprzedaż.

**Comment by AniaMalinowska** [comment]
Dziękujemy za infos. Prośba jeszcze o doprecyzowanie: czy bardziej interesuje Cię to w kontekście oferty czy transakcji? Mam na myśli to, czy potrzebą jest, by takie info byłoby 'doklejone' do każdej transakcji, czy np. wystarczyłoby, że po itemid z transakcji odpytałbyś GET na /sale/offers{id} (i tam wystarczy że będzie stosowne info, że jest Smart!).

**Comment by gumis496** [comment]
@AniaMalinowska w tym momencie w pierwszej kolejności byłaby mi potrzebna informacja przy ofercie, ale w sumie info obecne również przy transakcji byłoby docelowo też bardzo przydatne.

**Comment by AniaMalinowska** [comment]
@gumis496 Dziękujemy za doprecyzowanie. Przekazałam takie zapotrzebowanie do odpowiednich osób.

**Comment by scalp00** [comment]
Jest jedna istotna rzecz do której jest potrzebne dodanie do danych transakcji lub płatności informacji o SMART - mianowicie przy zwrotach w ramach odstąpienia od umowy sami w mailu piszecie żeby nie oddawać kosztów dostawy bo ktoś kupił w ramach SMART. Nie da się teraz tego inaczej weryfikować niż czytając maile o odstąpieniu od umowy. Przecież nie każdy korzysta z formularza dostępnego na Allegro jeśli ktoś nie skorzysta z tego formularza - nie ma możliwości weryfikacji tego.

**Comment by AniaMalinowska** [comment]
@scalp00 dziękujemy za głos w tej kwestii. Przekazałam te informacje do odpowiednich osób.

**Comment by Zbigniew-L** [comment]
Szanowni Państwo,

Wydaje się, że problem związany z Allegro Smart ma również duży wpływ na sposób wystawiania faktur.
Kiedy zakupu dokona klient biznesowy np. sp. z o.o. to na fakturze chcieliby widzieć kwotę przelewu, którego dokonali (lub kwotę obciążenia karty kredytowej) - a nie kwotę całego zamówienia. W chwili obecnej Allegro nie udostępnia informacji jaką kwotę faktycznie przekazuje klient a jaką Allegro i w związku z tym nie wiemy jaką fakturę mamy wystawić klientowi. Skutkuje to koniecznością dokonywania korekty faktury VAT kiedy klient już nam to zgłosi. Powoduje to znacznie więcej pracy w biurze, a w niektórych branżach np. 90% zakupów jest na fakturę a nie na paragon i mamy teraz duży problem.

prosimy o informację kiedy i jak będziemy mogli uzyskać informację o kwocie jaką płaci klient i kwocie którą pokrywa Allegro Smart

pozdrawiam,
Z, Ł.

**Comment by AniaMalinowska** [comment]
@Zbigniew-L dzięki za wiadomość. Tutaj jednak wspieramy w tematach API. W tej kwestii możesz napisać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). Pozdrawiamy.

**Comment by Zbigniew-L** [comment]
Właśnie chodzi nam o API - a mianowicie o informację w API o koszcie dostawy, który został pokryty przez Allegro Smart - i/lub kwocie którą faktycznie płaci klient! Obecnie nie wiemy na jaką kwotę mamy wystawić klientowi fakturę bo nie podajecie nam informacji o tej kwocie! Wystawianie faktury na kwotę transakcji powoduje, że klient prosi nas o korekty tych faktur. Około 90% kupujących w naszym wypadku to firmy więc mamy spory problem, a jak zrezygnujemy ze Smart to może nam spaść sprzedaż...

**Comment by AniaMalinowska** [comment]
Dziękujemy za doprecyzowanie. Przekazałam tę informację do odpowiednich osób.

**Comment by Zbigniew-L** [comment]
Pozwolę sobie zapytać czy problem został rozwiązany? Czyli czy jest możliwość aby przez API pobrać informację o kwocie pokrytej przez Allegro Smart?

**Comment by PawelTaberski** [comment]
@Zbigniew-L  Wprowadziliśmy nowe pole SMART w szczegółach zamówienia. Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/orders/#03). Sprawdzisz dzięki temu czy user korzystał ze smarta, a wyżej w polu "cost" masz koszt wysyłki która została pokryta.

**Comment by Zbigniew-L** [comment]
Super! dziękuję za informację, a przy mogę przy okazji zapytać czy jest jakiś biuletyn do którego mógłbym się zapisać aby otrzymywać mailowo informacje o nowościach w API?
Pozdrawiam!

**Comment by PawelTaberski** [comment]
Polecam naszą stronę o REST API umieszczamy tam informacje o wszystkich nowościach: https://developer.allegro.pl/news/
Ponadto o wszystkich nowościach jakie wprowadzamy w Allegro API zarówno REST API jak i WebAPI informujemy na GitHub-ie z labelką [NEWS].

**Comment by neldh** [comment]
Pozwolę sobie odkopać... Czy jest może jakiś sposób, by dowiedzieć się czy klient korzystał ze smart w pozostałościach webapi? Czy pole smart jest dostępne tylko w rest? (generalnie chodzi mi tylko o to, czy klient korzystał kiedykolwiek ze smart poprzez webapi, z restem sobie poradzę)

**Comment by MaciejFrackowiak** [comment]
Informacje dot. Smart dostępne są wyłącznie w REST API.
