### ISSUE TITLE
GET /order/checkout-forms/ checkoutForm_id zwraca  "Checkout form ... not found" dla niektórych zamówień

### ISSUE THREAD

**Issue by pam83** [allegro/allegro-api#5340]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 
:beetle: **Opis / Description**
Metoda GET /order/checkout-forms/ checkoutForm_id zwraca  czasami:
"Checkout form ... not found" dla niektórych zamówień.

Na stronie allegro zamówienie jest odnajdywane z tym samym checkoutForm_id 

https://allegro.pl/moje-allegro/sprzedaz/zamowienia/?query=7f9fcda1-79ba-11ec-a6ae-3b284da9c685

{"errors":[{"code":"CheckoutFormNotFoundException","message":"Checkout form 7f9fcda1-79ba-11ec-a6ae-3b284da9c685 not found","details":null,"path":"/order/checkout-forms/7f9fcda1-79ba-11ec-a6ae-3b284da9c685","userMessage":"Checkout form 7f9fcda1-79ba-11ec-a6ae-3b284da9c685 not found"}]}

Większość zamówień działa poprawnie. Proszę o sprawdzenie.

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem i nasze API prawidłowo zwraca wskazane zamówienie. Upewnij się czy jesteś autoryzowany jako Sprzedawca, do którego należy to zamówienie.
