### ISSUE TITLE
Tworzenie przesyłki Inpost (WZA) - Processing error

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#5343]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
trace-id: 110ced5b2952c895
command id: 4828f6b9-28b2-4313-a5ac-4c763bda185c

Podczas tworzenia przesyłki przez Wysyłam z Allegro metodą Inpost Paczkomat klient dostaje błąd code: `ERROR`, message: `"Processing error"`, userMessage: `"Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"`.
Zauważyliśmy że klient w danych `receiver.name` ma wprowadzone imię, nazwisko, kod pocztowy oraz miejscowość. Przesyłkę już nadał więc nie damy rady przetestować czy usunięcie kodu pocztowego oraz miejscowości przeszło by pozytywnie, a komunikat zwrotny nie jest niestety oczywisty.
Czy jeśli to pole było problemem jest możliwość aby komunikat chociaż wskazywał jako błąd pole z tego węzła?

**Comment by magik092** [comment]
Żeby nowego tematu nie zakładać: czy wielopaczka jest możliwa do zrealizowania przez API? Klient zgłaszał nam, że przy próbie nadania większej ilości paczek dostaje błąd (swoją drogą, jest literówka):
> additionalServices Usćuga wielopaczka nie jest dostępna u tego przewoźnika

Testuję to teraz na sandboxie i dla kilku paczek dostajemy również taki błąd.
sandbox trace-id: c7a42a3ab7461715
sandbox command-id: 355e2bac-5d05-457d-aea4-c68ba1ef5768
payload:
```json
{
    "additionalServices": {},
    "items": [
        {
            "description": "test",
            "dimensions": {
                "depth": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "height": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "width": {
                    "unit": "CENTIMETER",
                    "value": 15
                }
            },
            "weight": {
                "unit": "KILOGRAM",
                "value": 1
            }
        },
        {
            "description": "test",
            "dimensions": {
                "depth": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "height": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "width": {
                    "unit": "CENTIMETER",
                    "value": 15
                }
            },
            "weight": {
                "unit": "KILOGRAM",
                "value": 1
            }
        },
        {
            "description": "test",
            "dimensions": {
                "depth": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "height": {
                    "unit": "CENTIMETER",
                    "value": 10
                },
                "width": {
                    "unit": "CENTIMETER",
                    "value": 15
                }
            },
            "weight": {
                "unit": "KILOGRAM",
                "value": 1
            }
        }
    ],
    "label": {
        "fileFormat": "PDF",
        "referenceNumber": "c7aafded626711d366ba0d7da5930dc7"
    },
    "pickup": {
        "address": {
            "city": "Kozy",
            "countryCode": "PL",
            "postCode": "43-360",
            "street": "Tęczowa 2b"
        },
        "email": "it@web-com.pl",
        "name": "Jan Kowalski",
        "phone": "605 605 605"
    },
    "receiver": {
        "address": {
            "city": "Kozy",
            "countryCode": "PL",
            "postCode": "43-340",
            "street": "Testowa 12"
        },
        "email": "amqv9rulyu+7fc497995@user.allegrogroup.pl",
        "name": "Tester Testowy",
        "phone": "600500400"
    },
    "serviceId": 9277094,
    "type": "PACKAGE"
}
```

**Comment by Lukasz-Zurek** [comment]
Owszem, w tym przypadku kod pocztowy nie powinien znajdować się we wspomnianym polu. W `receiver.name` musi być imię i nazwisko, bez żadnych znaków specjalnych oraz nie może być jednym ciągiem bez spacji.

Zmiana komunikatu nie jest zależna od nas, ponieważ limity znaków, ograniczenia pól są po stronie serwisu Furgonetka.pl, z którym współpracujemy w zakresie usługi "Wysyłam z Allegro". Jednocześnie jest to problem, którego jesteśmy świadomi, tym bardziej dziękuję za te uwagi.

Co do Twojej drugiej wiadomości - zweryfikuję zgłoszenie i wrócę do Ciebie z odpowiedzią.

**Comment by Lukasz-Zurek** [comment]
@magik092 Przepraszam Cię za długi czas oczekiwania na odpowiedź.

Wielopaczkę możesz nadać przez API. Usługa ta jest jednak dostępna tylko dla DPD.

Jeśli natomiast chodzi o wskazaną literówkę - dziękuję za to zgłoszenie. Zgłosiłem ten błąd do odpowiedniego zespołu.
