### ISSUE TITLE
Limity API

### ISSUE THREAD

**Issue by jakubmaguza** [allegro/allegro-api#5344]
Hej,

Załóżmy, że chciałbym zrobić jakąś dużą aplikację, np. taki Baselinker (od razu mówię, że nie chcę, to tylko przykład).
Przy kilku użytkownikach nie ma problemu z limitami API.

Powiedzmy, że skupiam się na branży moto. Tutaj konta mają po kilkaset tysięcy aukcji. Wystarczy kilku użytkowników i trochę częstsza aktualizacja cen i już kończy się limit zapytań przydzielany per clientid.

Jak to wygląda w takiej sytuacji? Mogę się do was zgłosić po indywidualne limity, czy muszę tworzyć setki kont allegro i używać wygenerowanych tam clientid?

Pozdrawiam!

**Comment by Lukasz-Zurek** [comment]
Limity, które opisaliśmy w [naszym poradniku](https://developer.allegro.pl/about/#ograniczenie-liczby-zapytań-limity), obowiązują wszystkich użytkowników naszego API. Do każdego konkretnego przypadku zawsze podchodzimy indywidualnie. Dokładnie go analizujemy pod względem optymalnego wykorzystywania naszych zasobów, np. czy nie przesyłasz niepotrzebnych requestów, czy nie popełniasz błędów. 

W pierwszej kolejności proponujemy odpowiednie rozwiązania i wskazujemy błędy po to, abyś optymalnie wykorzystywał zasoby naszego API. Może być tak, że po wyeliminowaniu błędnych requestów, generowanie nowych ClientId, jak i zwiększenie limitu - będzie zbędne.

Jeżeli korzystasz z API rozsądnie i prawidłowo, a mimo to obecne limity nie pozwalają na optymalną pracę, istnieje możliwosc ich podniesienia.

**Comment by jakubmaguza** [comment]
Dzięki!
