### ISSUE TITLE
api.allegro.pl/sale/offers/ a promocja Allegro Ceny

### ISSUE THREAD

**Issue by Syzyf1** [allegro/allegro-api#5345]
Oferta korzysta z promocji „Obniżyliśmy cenę Twojej oferty w programie Allegro Ceny” („Jeśli zmienisz cenę oferty, wyłączymy na niej obniżkę ceny.”). Czy gdy zmienię parametry oferty przy pomocy restapi metodą https://api.allegro.pl/sale/offers/nr_oferty (np ilość dostępnych sztuk, ale cena pozostanie ta sama), to czy w/w promocja zostanie zakończona czy też będzie trwała dalej ?

**Comment by MaciejFrackowiak** [comment]
Nie, taka zmiana nie będzie miała wpływu - kluczowym elementem jest cena.
