### ISSUE TITLE
two-factor authentication issue for foreign developer

### ISSUE THREAD

**Issue by RikuyaOda** [allegro/allegro-api#5346]
This isn't really a tech topic but I'm posting here hoping to get some supports...
My company is based in Japan running a cross-border ecommerce. I was about to request access to production environment in allegro developer site. But it seems that we need a polish phone number to receive SMS code which I don't own.
How did you work around with this issue?? I really appreciate with any advise or comments. 
Thank you!! Dziękuję Ci!!

**Comment by MaciejFrackowiak** [comment]
Yes, two-factor authentification is out of our scope, but as far as I know Allegro accept foreign phone numbers. If you have a problem with set up, please contact [Allegro support](https://allegro.pl/help/contact?category=bd5d6384-cd67-4cb1-8773-d41fe30382dc&subjectId=6de6aa76-1505-4d69-8f0f-7e771b2abea1) directly.
