### ISSUE TITLE
Wgranie oferty z IdoSell do Allegro

### ISSUE THREAD

**Issue by Vlad-Katsubo** [allegro/allegro-api#5347]
Dzień Dobry.
Używam IdoSell Shop do handlu online.
Chcemy zintegrować IdoSell z Allegro.

Podłączyliśmy konto Allegro do IdoSell, wybraliśmy przedmiot testowy.
Podczas importowania pojawia się następujący błąd.

_"Uwaga: Wystąpił błąd w module integracji Allegro. Nie jest to błąd działania naszego panelu, dlatego prosimy o zapoznanie się z poniższą informacją.
Kod odpowiedzi zwrócony przez API Allegro:
VALIDATION_ERROR

Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
New offer description is required.

Postępowanie:
Jeżeli to możliwe popraw błędne dane, w przeciwnym wypadku kliknij tutaj by skontaktować się z obsługą Allegro w celu wyjaśnienia przyczyny występowania błędu. Poniżej znajdują się załączniki, o które możesz zostać poproszony.
Możesz w ciągu kilku dni przejrzeć ponownie ten błąd otwierając Dziennik zdarzeń

Załączniki:
Żądanie: request_allegro_20220121_120400
Odpowiedź: response_allegro_20220121_120400
Załączniki będą przechowywane do: 2022-01-28"_

Nazwa sklepu - fursoller
email: fursoller@gmail.com

**Comment by Lukasz-Zurek** [comment]
Komunikat błędu wskazuje na to, że dla oferty nie wprowadziłeś opisu, lub nie użyłeś znaczników HTML, zgodnie z [naszymi zasadami](https://developer.allegro.pl/sale/#6-opis-oferty). 

Abym mógł to dokładnie zweryfikować, potrzebowałbym pełen request i response, czyli załączniki, o których wspomniałeś w wątku. Możesz je przesłać korzystając z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5347.

Jeżeli masz problem z pobraniem plików, zgłoś to proszę do supportu narzędzia, z którego korzystasz.
