### ISSUE TITLE
userMessage w błędach

### ISSUE THREAD

**Issue by TimothyKoval** [allegro/allegro-api#5348]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Ponownie, problem z userMessage w `/parcel-management`

[https://github.com/allegro/restapi-guideline#generate-structured-errors](https://github.com/allegro/restapi-guideline#generate-structured-errors)

Wydrukujcie to sobie i wytapetujcie tym wasze zagrody, bo jak jeszcze raz zobaczę w userMessage `"nie może być puste"` to nie ręczę za siebie...

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowy trace-id, dla którego otrzymałeś ten komunikat.

**Comment by TimothyKoval** [comment]
5780f0d129e6eae6

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład. Temat przekazałem do zespołu odpowiedzialnego za zasoby, który przyjrzy się zwracanym komunikatom.
