### ISSUE TITLE
Product Offers - Access Denied

### ISSUE THREAD

**Issue by Glocom-Global** [allegro/allegro-api#5349]
Hi,

We are trying to connect Allergro live api enevironmet for this endpoint,
https://api.allegro.pl/sale/product-offers/

The developer app we created for Authroization seems to have all the scope to read and write offers including,

 "scope": "allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read allegro:api:messaging",

However, the above endpoint throws the following error.

Response:
{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access Denied, You don’t have permission to access offer."
        }
    ]
}

Please help to rectify this error.

**Comment by Lukasz-Zurek** [comment]
Everything indicates (based on the "userMessage") that you are trying to access an offer that does not belong to the Seller on which you have already authorized. Please make it clear. You cannot manage any offers from different accounts. You must always be authenticated and authorized as a seller.
