### ISSUE TITLE
Link more then 2 offers with different EAN-codes to one product?

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#5350]
Hi

Can I link more then 2 offers with different EAN-codes to the one product?

Thanks

**Comment by MartaNowaczyk** [comment]
Each EAN is a separate product. Besides, these are not REST API allegro issues. Ask questions about productization via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by Folganoid** [comment]
Ok.
thanks
