### ISSUE TITLE
biddersCount w "/sale/offers"

### ISSUE THREAD

**Issue by przestrzal** [allegro/allegro-api#5351]
Wg dokumentacji w przypadku metody "/sale/offers" powinienem otrzymać informację "biddersCount" dla ofert typu "BUY_NOW". Screen poniżej:

<img width="674" alt="Zrzut ekranu 2022-01-24 o 20 16 15" src="https://user-images.githubusercontent.com/17744192/150849444-d1531cb1-2476-4650-8512-048f39643de5.png">

https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET

Gdy odpytuję o ofertę, to mam pusto? Co robię nie tak?

``` ["saleInfo"]=>
      object(stdClass)#7096 (2) {
        ["currentPrice"]=>
        NULL
        ["biddersCount"]=>
        int(0)
      }
```

**Comment by MartaNowaczyk** [comment]
biddersCount - to liczba osób licytujących. Liczba licytujących jest widoczna dla formatu AUCTION. Sprawdzimy poprawność dokumentacji.

**Comment by przestrzal** [comment]
@MartaNowaczyk za pomocą której metody mogę sprawdzi liczbę ofert kupna, tak jak to jest prezentowane w kategorii? Za pomocą metody "/sale/offers" można sprawdzić liczbę sprzedanych sztuk. Mnie interesuje ta wartość, jaką prezentujecie na listingach.

**Comment by MartaNowaczyk** [comment]
@przestrzal wartość, którą prezentujemy na listingu można otrzymać za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#tag/Public-offer-information), ale dostęp mają tylko zweryfikowane aplikacje. Więcej przeczytasz w [naszym poradniku](https://developer.allegro.pl/listing/).
