### ISSUE TITLE
PATCH /sale/product-offers a zachowanie aktualnego opisu, zdjęć i parametrów

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5352]
Chciałbym poprosić o doprecyzowanie informacji z poradnika. Otóż czy prawdą jest, że jeśli stworzę ofertę poprzez POST /sale/offers podając tam swój opis, zdjęcia itp. a potem wykonam PATCH /sale/product-offers podając w requeście **jedynie ilość sztuk** to w ofercie **może zostać zmieniony opis, zdjęcie lub parametry**?

Lub może chodzi o to, że dopiero jeśli w PATCH /sale/product-offers oprócz ilości sztuk podam też **product.id** to wtedy opis, zdjęcie i parametry mogą się zmienić w mojej ofercie?

Chodzi mi o ten fragement:

_Ważne! Jeżeli chcesz zachować aktualny opis, zdjęcia i parametry produktowe, oprócz product.id powinieneś przekazać również takie pola jak: description, images i product.parameters. Możesz je pobrać z edytowanej przez Ciebie oferty, korzystając z GET /sale/offers/{offerId}._

Znaleziony tutaj:
https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99

**Comment by pskz** [comment]
Sam jestem ciekawy tej informacji, bo jest sprzeczna z tym co do tej pory zaobserwowałem.

Korzystam już od jakiegoś czasu z tego zasobu do aktualizacji i podaję tylko te pola do requesta które faktycznie mają ulec zmianie, a opis, zdjęcia i parametry pozostają bez zmian.

Czy szykuje się jakaś zmiana odnośnie tego jak ten zasób będzie funkcjonował w przyszłości?

**Comment by MartaNowaczyk** [comment]
@tomylee0 - jak zmienisz tylko liczbę sztuk, to nic innego się nie zmieni. Ten fragment w ramce, tak jak piszesz, dotyczy przypadku w którym podasz product.id.

**Comment by MartaNowaczyk** [comment]
@pskz na ten moment nie planujemy zmieniać logiki dla tego zasobu. Oczywiście jeśli dojdą jakieś nowe funkcjonalności, to mogą pojawić się też tutaj.

**Comment by tomylee0** [comment]
Dzięki.
