### ISSUE TITLE
Zakończenie powielonych ofert przez Allegro a publication.endedBy

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#5353]
Witam,

Mam pytanie odnośnie newsa

https://allegro.pl/dla-sprzedajacych/nowosci-i-zmiany-dla-sprzedajacych-od-lutego-i-marca-oA6ZmZK30UD#bedziemy-mogli-zakonczyc-powielone-oferty-tego-samego-przedmiotu

`Od 8.02.2022  (...) będziemy mogli zakończyć powielone oferty tego samego przedmiotu`

Czy w dzienniku zdarzeń oferty ( /sale/offer-events ) taka oferta otrzyma OfferEndedEvent z publication.endedBy = "ADMIN"?

Dziękuję za informacje

**Comment by MartaNowaczyk** [comment]
Witam.
W takiej sytuacji powinno się pojawić "ADMIN_STOP".

**Comment by Radeq** [comment]
@MartaNowaczyk , dziękuję za informację, dla mojej integracji jest to kluczowe.

Mam nadzieję, że wkrótce pojawi się news w tej sprawie oraz zostanie zaktualizowana dokumentacja wraz z plikiem swagger.yml

**Comment by MartaNowaczyk** [comment]
@Radeq zgłosiłam to do odpowiedniego zespołu i w każdym wypadku będzie to mapowane na "ADMIN", także dokumentacja pozostanie bez zmian.

**Comment by tomylee0** [comment]
Czy dalej nie będzie możliwości sprawdzenia przy pomocy REST API powodu dla którego pojawiło się endedBy ADMIN? 

Wciąż nie możemy bowiem rozróżnić czy endedBy ADMIN pojawiło się z powodu tymczasowego zablokowania konta (co powoduje, że po odblokowaniu **mogę wystawić ponownie ofertę**) lub z powodu nieprawidłowości w ofercie typu zdjęcie nieodpowiadające standardom czy właśnie powielona oferta (co powoduje, że **nie powinienem wystawiać oferty na nowo**). Temat poruszany w #4090.

**Comment by MartaNowaczyk** [comment]
Przekazałam sugestię do zespołu, który zajmuje się tym tematem. Wrzuć proszę tę sugestię jeszcze na [Discussions](https://github.com/allegro/allegro-api/discussions), dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.

**Comment by sl-aw-ek** [comment]
> @Radeq zgłosiłam to do odpowiedniego zespołu i w każdym wypadku będzie to mapowane na "ADMIN", także dokumentacja pozostanie bez zmian.

Dokumentacja pozostała bez zmian ale api zwraca "ADMIN_STOP" - to może jednak warto zaktualizować dokumentację?

**Comment by MartaNowaczyk** [comment]
Dziękuję za informację. Zgłoszę to do odpowiedniego zespołu do ponownej analizy.
