### ISSUE TITLE
Wysyłka z Allegro API - allegro box

### ISSUE THREAD

**Issue by merigo123** [allegro/allegro-api#5354]
Witam
Mam problem z utworzeniem przesyłki Allegro One Box w API. W GET parcel-management/parcel-create-commands otrzymuje błąd:         
    "code": "ERROR",
            "message": "\"Inne dane na etykiecie\" not supporter for carrier",
            "details": null,
            "path": "/sender",
            "userMessage": "Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"
commandid: ce21b3f1-ad6c-4c9b-9502-0286e888228c
serviceId:12958288
Proszę o pomoc gdzie jest błąd.
Pozdrawiam
ŁK

**Comment by MartaNowaczyk** [comment]
Błąd jest związany z nadpisaniem etykiety. W tym wypadku trzeba pominąć wypełnianie etykiety (pole label: null). Niektórzy przewoźnicy nie pozwalają na to, żeby były inne dane nadawcy i inne dane na etykiecie.

**Comment by merigo123** [comment]
Dziękuje, ustawienie label:null rozwiązało ten problem. Można by o tym gdzieś w dokumentacji wspomnieć.
Pozdrawiam
ŁK

**Comment by MartaNowaczyk** [comment]
Dzięki za uwagę. Postaram się dodać taką informację do [naszego poradnika](https://developer.allegro.pl/wza/#jak-utworzy%C4%87-now%C4%85-paczk%C4%99).
