### ISSUE TITLE
Wysyłam z Allegro - Allegro One Box - numer przesyłki

### ISSUE THREAD

**Issue by merigo123** [allegro/allegro-api#5355]
Witam
Udało mi się utworzyć etykietę i ją pobrać w PDF. Na wydruku są dwa numery, jeden UPS zaczynający się 1Z833... drugi w reference zaczynający się od ALE000... Wywołuje /parcel-management/parcels/ w celu pobrania informacji o przesyłce. W polu waybill jest numer ALE000... Niestety w wyszukiwarce przesyłek na stronie UPS rozpoznaje tylko numer 1Z833.. Jak uzyskać ten numer przesyłki przez API?
Pozdrawiam
ŁK

**Comment by MartaNowaczyk** [comment]
Niestety, na ten moment nie zwracamy numerów UPS czyli te rozpoczynające się na 1Z...
