### ISSUE TITLE
Bulk uploading offers and images

### ISSUE THREAD

**Issue by Folganoid** [allegro/allegro-api#5356]
Hi

Does exist a way for the bulk uploading offers and images by API?

For example If I want to create several thousands offers with 8 images each, should I have to make separate http-request for uploading each image and creating each offer and product?

Many thanks

**Comment by MaciejFrackowiak** [comment]
There are two ways of creating offers:
1. You can use [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) resource - using it you can send all the data of an offer and images in one request - please, check [our tutorial](https://developer.allegro.pl/en/product_offers/) - but one request = one offer;
2. If you use [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST), you have to upload images by [POST /sale/images](https://developer.allegro.pl/en/documentation/#operation/uploadOfferImageUsingPOST) - so it is necessary to make a minimum of two requests - [here](https://developer.allegro.pl/en/sale/) you can find a tutorial.

**Comment by Folganoid** [comment]
ok thanks
