### ISSUE TITLE
Brak uprawnień do pobierania wiadomości 

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#5357]
Dzień  dobry,

Próbuje pobrać wiadomości od użytkowników (Lista wątków na koncie) za pomocą GET /messaging/threads ale w odpowiedzi otrzumuję: AccessDenied. Dlaczego? Analogicznie pobierając dyskusje z konta wszystko jest ok. 

{"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Contact the author of the application."}]}

**Kod od dyskusji (które się ładnie pobierają):**

public function getDisputes($limit = 100, $offset = 0) {
      $url = "https://api.allegro.pl/sale/disputes?limit={$limit}&offset={$offset}";
      $token = $this->getAccessToken();

      $headers = array(
          "Authorization: Bearer {$token}",
          "Accept: application/vnd.allegro.public.v1+json"
      );

      $response = $this->sendRequest($url, 'GET', $headers);

      return $response;
}

**Analogiczny kod od wiadomości, które niestety zwracają AccessDenied:**
public function getMessaging($limit = 20, $offset = 0) {
        $url = "https://api.allegro.pl/messaging/threads?limit={$limit}&offset={$offset}";
        $token = $this->getAccessToken();

        $headers = array(
            "Authorization: Bearer {$token}",
            "Accept: application/vnd.allegro.public.v1+json"
        );
            
        $response = $this->sendRequest($url, 'GET', $headers);

        return $response;         
    }

Proszę o pomoc. Czy może mamy jakąś blokadę na koncie?

**Comment by MartaNowaczyk** [comment]
Sprawdź czy Twoja aplikacja posiada scope "allegro:api:messaging" odpowiedzialny za obsługę centrum wiadomości. Sprawdzisz to na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Jeśli przekazujesz listę scope'ów podczas generowania tokena, to tam też powinien być zawarty scope "allegro:api:messaging". Jeśli nie przekazujesz takiej listy to znaczy, że masz dostęp zgodnie z wybranymi scope'ami na [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Możesz też zdekodować swój token i sprawdzić czy jest tam zawarty odpowiedni scope.

**Comment by lukiopmoto** [comment]
Aplikacja posiada wszystkie scope w tym te do zarządzania wiadomościami. Nie przekazuje listy scopów podczas generowania tokena. Pytanie jak mogę zdekodować swój token? Co jeszcze Państwo potrzebują żeby pomóc rozwiązać problem?

Kod:
$allegro = new Allegro();  
$messages = $allegro->getMessaging(); // NIE działa bo wywala AccessDenied
$messages = $allegro->getDisputes(); // działa

![scopes](https://user-images.githubusercontent.com/43815384/151126403-d0d8ea33-e06a-4e68-988e-f7c410030992.png)

**Comment by hahyes** [comment]
Jeżeli używasz tokena od bardzo dawna i korzystasz z odświeżania tokena, scope się nie aktualizują wraz z odświeżeniem. Możliwe, że tutaj leży problem.

**Comment by MartaNowaczyk** [comment]
Tutaj możesz sprawdzić swój token https://jwt.io/
Możesz też podesłać przez nasz  [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) pełen cURL z requestem i responsem z dopiskiem GitHub #5357. Sprawdzę w czym jest problem.

**Comment by lukiopmoto** [comment]
Dekoder zwraca mi takie dane:
"user_name": "85865703",
  "jti": "blim-blam-blom",
  "client_id": "bla-bli-blu",
  "scope": [
    "allegro:api:orders:read",
    "allegro:api:profile:write",
    "allegro:api:sale:offers:write",
    "allegro:api:billing:read",
    "allegro:api:campaigns",
    "allegro:api:disputes",
    "allegro:api:sale:offers:read",
    "allegro:api:bids",
    "allegro:api:orders:write",
    "allegro:api:ads",
    "allegro:api:payments:write",
    "allegro:api:sale:settings:write",
    "allegro:api:profile:read",
    "allegro:api:ratings",
    "allegro:api:sale:settings:read",
    "allegro:api:payments:read"
  ],
  "allegro_api": true
}

_Jeżeli używasz tokena od bardzo dawna i korzystasz z odświeżania tokena, scope się nie aktualizują wraz z odświeżeniem. Możliwe, że tutaj leży problem._ - Myślę że tutaj leży problem. Jak to poprawić?

**Comment by MartaNowaczyk** [comment]
Musisz wygenerować token na nowo, wtedy będzie on zawierał odpowiedni zakres uprawnień. 
 Podsyłam info z naszych [Aktualności](https://developer.allegro.pl/news/#scopes-on-developer-apps).

**Comment by lukiopmoto** [comment]
Utworzyłem na nowo access_token i refresh_token i teraz działa czyli udaje się pobierać wiadomości.

Dziękuję za pomoc.
