### ISSUE TITLE
Przesyłka Allegro One

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#5358]
Witam
Mam problem z utworzeniem przesyłki Allegro One
ostatnia próba: /parcel-management/parcel-create-commands/472693DF-CC9D-4CCA-9F47-DAED870B5449
rezultat: "code":"BAD_REQUEST","message":"JSON parse error"

Jest możliwość uzyskania informacji co jest problemem w przekazywanym ciągu?

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam, sprawdziłam i "referenceNumber": "65FB7A6F-5F4F-4E0A-B938-E9BB2FC778EB" powinien mieć max 35 znaków, a ma 36.
Pozdrawiam.

**Comment by cemsgh** [comment]
Dziękuję przesyłki tworzą się już prawidłowo, jednak mam problem z anulowaniem.
Dlaczego nie mogę skutecznie zakończyć np. parcel-management/parcel-cancel-commands/98e4601a-d44c-43cc-b926-9ea8790d6b94

**Comment by MartaNowaczyk** [comment]
Jak tylko uda mi się ustalić przyczynę dam znać

**Comment by MartaNowaczyk** [comment]
Nie jest to błąd ze strony API. Otrzymałam informację, że nie ma możliwości anulowania przesyłek Allegro automat paczkowy i punkty odbioru. Jeśli masz jakieś dodatkowe pytania dotyczące samych przesyłek skontaktuj się w tej sprawie poprzez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
