### ISSUE TITLE
Nie działa zmiana ceny dla ofert w kampanii "Prowizja nawet 0.5%"

### ISSUE THREAD

**Issue by cyfranT** [allegro/allegro-api#5359]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Wysłaliśmy request (trace-id: 5a92d71addedcba1) ustawienia ceny na 24.99 zł z użyciem /sale/offer-price-change-commands/{commandId} dla oferty , która jest w kampanii "Prowizja nawet 0.5%"

Otrzymaliśmy potwierdzenie powodzenia ustawienia ceny (trace-id: 8a79a5d7b71a9ed0)
Na portalu jednak nadal widnieje poprzednia cena 24.75 zł, chociaż zasób sale/offers zwraca już cene 24.99 w sellingMode.price.amount (trace-id: baf87f07fa8e93c1)

Nigdzie nie widzimy informacji, aby nie można było zmienić ceny oferty w kampanii Prowizja nawet 0.5%, a feedback o powodzeniu zmiany ceny i informacja zwracana przez sale/offers są błędne.

**Comment by MartaNowaczyk** [comment]
Jeżeli chcesz zmienić cenę w ofercie, która bierze udział w kampanii skorzystaj z [PATCH /sale/badges/offers/{offerId}/campaigns/{campaignId}](https://developer.allegro.pl/documentation/#operation/patchBadge). Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/badge/#6-zmiana-ceny-i-zako%c5%84czenie-oznaczenia).
Podsyłam też nasz komunikat z [Aktualności](https://developer.allegro.pl/news/#badges-change-finish).
