### ISSUE TITLE
Problemy z generowaniem zdarzeń ofert

### ISSUE THREAD

**Issue by czlowiekpolar** [allegro/allegro-api#5360]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource

:beetle: **Opis / Description**
Od wczoraj nie otrzymuję pełnej listy zdarzeń oferty po jej edycji OFFER_CHANGED, przykładowa oferta: 11748555477. Modyfikowałem wielokrotnie czas wysyłki, fakturę czy cennik wysyłki zarówno przez API jak i przez allegro i eventy nie zostały wygenerowane. Zaznaczam, że inne zdarzenia (publikacja, zakończenie, zmiana ceny) generują się prawidłowo.

Proszę o weryfikację.

**Comment by MaciejFrackowiak** [comment]
Nie generujemy eventów dot. zmiany cennika dostawy czy też czasu wysyłki w ofercie. Natomiast informacja o typie faktury taki event generuje.

**Comment by czlowiekpolar** [comment]
Kiedy ta zmiana została wprowadzona? Mam przekonanie graniczące z pewnością, że event był generowany dla zmiany tych pól. Proszę też o wskazanie listy pól dla których generujecie to zdarzenie.

**Comment by MaciejFrackowiak** [comment]
Nie dokonaliśmy tu żadnej zmiany - dla cennika dostawy, czasu wysyłki, cennika hurtowego nie jest generowany event. Dla pozostałych zmian już tak.
