### ISSUE TITLE
Błąd zmiany stanów dla parametrów zdefiniowanych w produktyzacji /sale/offer-quantity-change-commands/ EXCEPTION_DURING_OFFER_QUANTITY_UPDATE MissingRequiredParameters

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#5361]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Dzień dobry, mam oferty powiązane z produktami, które mają zdefiniowane prametry np. Kod producenta i Marka, natomiast przy próbie zmiany stanów jest błąd o ich braku.

Skoro parametry są w produktyzacji, to nie powinno być błędu, proszę o weryfikację.

Przykład:
https://allegro.pl/oferta/9216771717
https://allegro.pl/offer/product/report/c16bc3e3-7d64-47dc-8e60-e6953cded311

```
REQUEST 2022-01-26 11:31:05.0918762
curl -X PUT \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/cd9cafe6-ade2-4767-a206-f4030ee033ba' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \
  -d '{"modification":{"changeType":"FIXED","value":1},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"9216771717"}]}]}' \

RESPONSE 2022-01-26 11:31:05.1389226 Duration: 47,0464ms
{
  "Data": {
    "Id": "cd9cafe6-ade2-4767-a206-f4030ee033ba",
    "TaskCount": {
      "Failed": 0,
      "Success": 0,
      "Total": 0
    }
  },
  "TraceId": "f21e339b1a18a570",
  "StatusCode": 201
}

```

```
REQUEST 2022-01-26 11:56:49.0121229
curl -X GET \
  'https://api.allegro.pl/sale/offer-quantity-change-commands/cd9cafe6-ade2-4767-a206-f4030ee033ba/tasks?' \
  -H 'Accept: application/vnd.allegro.public.v1+json' \
  -H 'Content-Type: application/vnd.allegro.public.v1+json' \
  -H 'Accept-Language: pl-PL' \
  -H 'Authorization: Bearer #' \

RESPONSE 2022-01-26 11:56:49.0589917 Duration: 46,8688ms
{
  "Data": {
    "Tasks": [
      {
        "Field": "quantity",
        "FinishedAt": "2022-01-26T10:31:41.046Z",
        "Message": "EXCEPTION_DURING_OFFER_QUANTITY_UPDATE",
        "Offer": {
          "Id": "9216771717"
        },
        "ScheduledAt": "2022-01-26T10:31:41.047Z",
        "Status": "FAIL",
        "Errors": [
          {
            "Code": "ConstraintViolationException.MissingRequiredParameters",
            "Details": null,
            "Message": "Missing required parameters: 237190, 219809",
            "Path": "parameters",
            "UserMessage": "Uzupełnij parametry obowiązkowe: Marka, Kod producenta."
          }
        ]
      }
    ]
  },
  "TraceId": "7cd456dba6866b41",
  "StatusCode": 200
}
```

**Comment by MaciejFrackowiak** [comment]
Wskazana oferta została po raz pierwszy wystawiona 29 kwietnia 2020, kiedy produkt do niej przypisany nie posiadał jeszcze parametrów Marka oraz Kod producenta. W związku z tym obecnie wchodząc na ofertę (na stronie WWW) przedmiotowe parametry oferty są niewidoczne. Niezbędna jest edycja oferty i ponowne przypięcie produktu - dzięki temu zyska ona parametr Marka i Kod producenta. W serwisie WWW, podczas próby edycji od razu pojawi się okno z nową wersją tego produktu, który należy zaakceptować.

**Comment by alekskuc** [comment]
Ok, dziękuję za szybką odpowiedź.

Proponuję zmianę w tym przypadku żeby zamiast zgłaszać błąd braku parametrów po prostu je przepisać do oferty z powiązanego produktu. Myślę, że wszyscy sprzedawcy docenią brak konieczności edycji.

**Comment by MaciejFrackowiak** [comment]
Taka opcja wymaga jednak decyzji sprzedającego - tylko on może potwierdzić, że nowe parametry produktowe pasują do jego oferty - a w tym wypadku jak wspomniałem oferta nie miała wcześniej parametrów Marka oraz Kod producenta.

**Comment by alekskuc** [comment]
Dzień dobry, zgadzam się, że sprzedający powinien potwierdzać zmiany w parametrach na styku oferty i produktyzacji. W tym konkretnym scenariuszu nie ma zmian w parametrach ani ich nadpisania, tylko następuje uzupełnienie nieistniejących wymaganych parametrów na podstawie powiązanego produktu.

1. Wystawiam ofertę bez parametru Marka, bo aktualnie nie istnieje w tej kategorii.
2. Wiąże ofertę z produktem z produktyzacji i wszystkie wymagane parametry się przepisują z produktu, co akceptuję.
3. Powiązany produkt w produktyzacji zostaje zmieniony i dochodzi nowy parametr Marka oraz zostają zmienione inne parametry.
4. W przypadku próby zmiany stanów magazynowych jest błąd braku parametru Marka. O tym, że inne się różnią, nie ma błędu, bo są uzupełnione. W tym miejscu proponuję zmianę żeby wyłącznie nieistniejące parametry takie jak Marka dodać do oferty bez potwierdzania, bo potwierdzenie było w momencie powiązania z produktem przy wystawianiu. Samo uzupełnienie oferty o wymagany nieistniejący uprzednio parametr Marka nie nadpisuje danych które by mógł ustawić sprzedawca, a zapewnia ciągłość sprzedaży.

**Comment by MaciejFrackowiak** [comment]
Dziękuję za Twoje spojrzenie i sugestię - proszę umieść ją w sekcji [Discussions](https://github.com/allegro/allegro-api/discussions) - dzięki temu inni użytkownicy również będą mogli się wypowiedzieć w tej kwestii.

**Comment by alekskuc** [comment]
Dodane w #5376
