### ISSUE TITLE
PATCH /sale/product-offers/{offerId} Błędnie przesłano definicje parametru

### ISSUE THREAD

**Issue by pskz** [allegro/allegro-api#5362]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby aktualizacji parametrów aukcji **niepowiązanej** z produktem zasobem PATCH /sale/product-offers/{offerId} dostaję zwrotkę z błędem. Ta sama struktura parametrów aktualizowana metodą PUT /sale/offers/{offerId} przechodzi prawidłowo.

Problem występuje zarówno w środowisku produkcyjnym jak i na sadboxie. Dla aukcji powiązanej z produktem, wszystko działa prawidłowo.

Poniższe dane są z testu na produkcji, gdyż początkowo myślałem że jest to typowo problem z sandboxem.

Aukcja 11567889607, z kategorii 48879

```
stdClass Object (
    [errors] => Array (
        [0] => stdClass Object (
            [code] => ParameterCategoryException
            [message] => Unprocessable Entity
            [details] => 
            [path] => parameters
            [userMessage] => Blednie przeslano definicje parametru `17448:Waga produktu z opakowaniem jednostkowym` jako parametr w sekcji `offer`.
        )
    )
)
```

Przesyłane dane:

```
{
    "id":"11567889607",
    "parameters":[
        {
            "id":"17448",
            "values":[
                1
            ]
        },
        {
            "id":"225693",
            "values":[
                "8806092211117"
            ]
        },
        {
            "id":"244505",
            "values":[
                "test skrypt"
            ]
        }
    ]
}

```

**Comment by MartaNowaczyk** [comment]
To nie jest błąd.  Zgodnie z dokumentacją, jeśli korzystasz z: [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers), powinieneś pamiętać o rozróżnieniu parametrów produktowych od ofertowych. To zasób dedykowany typowo dla ofert z produktem.

W podanych przez Ciebie przykładzie widać, że parametry produktowe oznaczone jako "describesProduct": true, przekazujesz w obiekcie "parameters", a powinieneś przekazać w obiekcie "product", stąd opisana sytuacja. 

Wykorzystaj GET /sale/categories/{categoryId}/parameters, by pobrać parametry dla wybranego produktu. Wartość true w polu: "options.describesProduct" oznacza, że dany parametr jest produktowy. 

Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/product_offers/).

**Comment by pskz** [comment]
Ok, poniekąd spodziewałem się takiej odpowiedzi, patrząc na dokumentację.

Jednakże, tym zasobem mogę też aktualizować wiele pozycji dla ofert niepowiązanych z produktem z katalogu, dlatego dziwi mnie to, iż parametry kategorii są w tym przypadku wyłączone z tej aktualizacji. Dlaczego? Nawet jeśli nie jest to oferta powiązana z produktem z katalogu.

Przykład, potrzebuję uzupełnić wymagane obecnie, lub wymagane w przyszłości parametry kategorii, i muszę korzystać w tym przypadku z zasobu PUT, przekazując całość danych z oferty.
Czy nie po to powstał zasób PATCH aby właśnie ograniczyć ilość danych wysyłanych do Api?

**Comment by MartaNowaczyk** [comment]
Tak, zasób PATCH /sale/product-offers/{offerId} ma ograniczyć ilość wysyłanych danych, by nie przekazywać całego modelu oferty. Jednak tak jak napisałam dedykowany jest dla ofert z produktami i jego logika została stworzona właśnie pod produktyzację. Możesz aktualizować wiele pozycji dla ofert niepowiązanych z produktem, bo nie mają one wpływu na strukturę i produkt. Parametry nie są wyłączone z możliwości aktualizacji, jednak są zależne od produktów i logiki, którą przyjęliśmy, by powiązanie ofert z produktem było łatwiejsze, gdy rozpoznamy produkt w naszej bazie. Dla takich ofert są określone parametry, które opisują dany produkt - dzięki temu możemy poszukać czy u nas taki produkt istnieje, jak również możesz dodać produkt, a parametry "opisujące" produkt dodamy sami, przez co nie trzeba ich podawać. 
Podsumowując jest to zasób dedykowany dla ofert z produktem, jednak istnieje możliwość edytowania w pewnym stopniu niepowiązanych ofert i to jest dodatkowa zaleta.

Miej na uwadze, że od 1 marca podniesiemy wymóg połączenia ofert z produktem do 50%, a w drugiej połowie roku planujemy, żeby każda nowo wystawiana oferta była połączona z Katalogiem produktów, a potem wszystkie.

**Comment by pskz** [comment]
Dziękuję za odpowiedź.
Wszystko wydaje się jasne, dążycie do jak najwyższego pokrycia ofert produktami z katalogu. Rozumiem też założenia projektowe, ale nie jestem pewny tak szybkiego progresu, gdyż ciągle pojawiają się błędy w katalogu.

Mam na uwadze wymóg łączenia ofert z produktami, natomiast wszystko zależy od klientów mojej aplikacji.
Tego już nie mogę zagwarantować :)

Wracając do błędów, ciągle dla jednego szukanego EANu pojawiają się produkty, które nie powinny się tam znaleźć. czy możemy spodziewać sie poprawy w tej sprawie?

**Comment by MartaNowaczyk** [comment]
Ciągle pracujemy nad udoskonaleniem naszego katalogu produktów. Gdy zauważysz błąd w produkcie zgłoś go [przez API](https://developer.allegro.pl/productization/#6-jak-zg%c5%82osi%c4%87-b%c5%82%c4%85d-w-produkcie) albo przez formularz wystawiania: "zgłoś błąd w produkcie", bo to nie problem samego API.
