### ISSUE TITLE
Brak wiadomości w api

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#5364]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,
podczas odpytywania zasobu /messaging/threads/ między 2022-01-13 08:58:04 a 2022-01-13 14:46:01 ( kilkanaście requestów ) nie pojawia się informacja o wiadomości. Cały czas data ostatniej wiadomości dla wątku eDJzDy3NLtQlFLdJH0C2L6TSkL47QB3244Zgh2ZhifA to 2022-01-13T07:43:30.742Z (według pola lastMessageDateTime) a wiadomość, której brakuje została utworzona 2022-01-13T07:52:39.302Z (sprwadzałem dzisiaj w API). Stąd moje pytanie dlaczego nie było wiadomości o id f0c8686a-5a43-45a8-beff-f4e3b67a8f81 w API przez te kilka godzin po utworzeniu?
Czy ma to coś wspólnego z botem, który blokuje wysyłkę wiadomości?

**Comment by MartaNowaczyk** [comment]
Tak, wiadomość została przytrzymana przez Allinę (bota) i wysyłający zdecydował się na wysyłkę jej po paru godzinach.
