### ISSUE TITLE
Product creation error UnableToSetCustomValueWithoutAmbiguousValueException

### ISSUE THREAD

**Issue by Glocom-Global** [allegro/allegro-api#5365]
I am trying to create a new product in the catalogue via API. I receive the below error
{
    "errors": [
        {
            "code": "UnableToSetCustomValueWithoutAmbiguousValueException",
            "message": "11323",
            "details": null,
            "path": null,
            "userMessage": "Nie można podać propozycji wartości dla parametru 11323 bez wybierania wartości niejednoznacznej"
        }
    ]
}

There is no explanation available for the error UnableToSetCustomValueWithoutAmbiguousValueException
Could you help me to fix the issue?

**Comment by MartaNowaczyk** [comment]
Check if you add parameter ID 11323_1 in the appropriate array - valuesIds (for dictionary parameters). It should look like this:

```
 {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
```


More information about the parameters can be found in [our guide](https://developer.allegro.pl/en/sale/#parameters).

**Comment by Glocom-Global** [comment]
Below is our full request. We are unable to trace any mistakes. Please help us to fix the error

{
  "name": "Test Parent 1",
  "category": {
    "id": "124264"
  },
  "images": [
    {
      "url": "https://a.allegroimg.com/original/11eb40/5358a3e748f5ad4f2a96ec1ed6ff"	  
    }
  ],
                  "parameters": [                    					
					{
						"id": "11323",											
						"values": [
							"Nowy"
						],
						"valuesIds": [
							"11323_1"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "3786",
						"values": [
							"Oak & Sherry"
						],
						"valuesIds": [
							"3786_85"
						],
						"rangeValue": null,
						"unit":null
					}, 
					{
						"id": "54",
						"values": [
							"4XS"
						],
						"valuesIds": [
							"3806_407362"
						],
						"rangeValue": null,
						"unit":null
					}, 
					{
						"id": "54",
						"values": [
							"bezbarwny"
						],
						"valuesIds": [
							"451_131072"
						],
						"rangeValue": null,
						"unit":null
					}, 
					{
						"id": "3766",
						"values": [
							"aztecki"
						],
						"valuesIds": [
							"3766_14"
						],
						"rangeValue": null,
						"unit":null
					}, 
					{
						"id": "127662",
						"values": [
							"do pracy"
						],
						"valuesIds": [
							"127662_1"
						],
						"rangeValue": null,
						"unit":null
					}, 
					{
						"id": "127488",
						"values": [
							"asymetryczna"
						],
						"valuesIds": [
							"127488_5"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "127468",
						"values": [
							"asymetryczna"
						],
						"valuesIds": [
							"127468_11"
						],
						"rangeValue": null,
						"unit":null
					},					
					{
						"id": "59",
						"values": [
							"asymetryczny"
						],
						"valuesIds": [
							"59_2429"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "4126",
						"values": [
							"bez rękawów"
						],
						"valuesIds": [
							"4126_4"
						],
						"rangeValue": null,
						"unit":null
					},					
					{
						"id": "18160",
						"values": [
							"mini"
						],
						"valuesIds": [
							"18160_1"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "201025",
						"values": [
							"guziki"
						],
						"valuesIds": [
							"201025_2513"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "201017",
						"values": [
							"akryl"
						],
						"valuesIds": [
							"201017_2357"
						],
						"rangeValue": null,
						"unit":null
					},
					{
						"id": "202477",
						"values": [
							"baskinka"
						],
						"valuesIds": [
							"202477_1"
						],
						"rangeValue": null,
						"unit":null
					}
                ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Taking glamour to a whole new level, this women's square collar sequins dress will make you the brightest babe in the whole party. This mesh sleeve will give you a unique look and makes you shine bright like the stars in the sky. This three-quarter-sleeved dress is the way to go when you want to make a statement while staying classy.</p>"
          }
        ]
      }
    ]
  }
}

**Comment by MartaNowaczyk** [comment]
Errors:
- wrong ID for the "Color" parameter - you have "id": "54", it should be "id": "451":
- you still provide "valuesId" for dictionary parameters - leave the array empty
- the description should be between <p> </p> tags

Valid request:
```
{
"name": "Test Parent 1",
"category": {
"id": "124264"
},
"images": [
{
"url": "https://a.allegroimg.com/original/11eb40/5358a3e748f5ad4f2a96ec1ed6ff"
}
],
"parameters": [
{
"id": "11323",
"values": [],
"valuesIds": [
"11323_1"
],
"rangeValue": null
},
{
"id": "3786",
"values": [
"Oak & Sherry"
],
"valuesIds": [
"3786_85"
],
"rangeValue": null
},
{
"id": "54",
"values": [],
"valuesIds": [
"3806_407362"
],
"rangeValue": null
},
{
"id": "451",
"values": [],
"valuesIds": [
"451_131072"
],
"rangeValue": null
},
{
"id": "3766",
"values": [],
"valuesIds": [
"3766_14"
],
"rangeValue": null
},
{
"id": "127662",
"values": [],
"valuesIds": [
"127662_1"
],
"rangeValue": null
},
{
"id": "127488",
"values": [],
"valuesIds": [
"127488_5"
],
"rangeValue": null
},
{
"id": "127468",
"values": [],
"valuesIds": [
"127468_11"
],
"rangeValue": null
},
{
"id": "59",
"values": [],
"valuesIds": [
"59_2429"
],
"rangeValue": null
},
{
"id": "4126",
"values": [],
"valuesIds": [
"4126_4"
],
"rangeValue": null
},
{
"id": "18160",
"values": [],
"valuesIds": [
"18160_1"
],
"rangeValue": null
},
{
"id": "201025",
"values": [],
"valuesIds": [
"201025_2513"
],
"rangeValue": null
},
{
"id": "201017",
"values": [],
"valuesIds": [
"201017_2357"
],
"rangeValue": null
},
{
"id": "202477",
"values": [],
"valuesIds": [
"202477_1"
],
"rangeValue": null
}
],
"description": {
"sections": [
{
"items": [
{
"type": "TEXT",
"content": "<p>Taking glamour to a whole new level, this women's square collar sequins dress will make you the brightest babe in the whole party. This mesh sleeve will give you a unique look and makes you shine bright like the stars in the sky. This three-quarter-sleeved dress is the way to go when you want to make a statement while staying classy.</p>"
}
]
}
]
}}
```

**Comment by MartaNowaczyk** [comment]
In the screenshot, you combine the offers by color/pattern. In the provided example, by the given parameter. If you want to combine offers via color/ pattern, look at [the sample request in our guide](https://developer.allegro.pl/en/multi_variant_offers/#create-a-multi-variant-offer) - click on "Click to view sample request:"
