### ISSUE TITLE
jak sprawdzić parametr "Liczba sztuk w opakowaniu" cudzej aukcji?

### ISSUE THREAD

**Issue by thefoe76** [allegro/allegro-api#5370]
Jak w temacie, w  /offers/listing nie ma takiej informacji, a to jest istotne - utrudnia porównanie realne ceny sprzedaży niektórych towarów, a chyba o to w tym zasobie chodzi?

**Comment by MartaNowaczyk** [comment]
Nie mamy w planach zmiany w tym zakresie. Wrzuć proszę tę sugestię na Discussions, dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.
