### ISSUE TITLE
The stock level of items to be listed may not be lower than 1

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#5372]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Próbuję zmienić ilość produktów w ofercie 11138646466. Jeśli wpiszę liczbę mniejszą niż 20, pojawia się błąd "Wystawiana liczba nie może być mniejsza niż 1."

Problem występował już wcześniej w innej ofercie - https://github.com/allegro/allegro-api/issues/5215

![image](https://user-images.githubusercontent.com/5887720/151727728-719579cc-d96e-432f-9cc4-8c6a50c75989.png)

**Comment by AureliuszBrussy** [comment]
Przekazałem problem do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy wyeliminujemy błąd w tej ofercie.

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować. Przepraszamy za niedogodności.

**Comment by rasskabak** [comment]
Niestety, problem nadal wystęuje. Poza naprawieniem błędu proponuję także zainwestować chwilę w testy automatyczne ;)
![image](https://user-images.githubusercontent.com/5887720/152709716-1d1c4401-5d4b-4675-ae8c-495407e22a5f.png)

**Comment by AureliuszBrussy** [comment]
@rasskabak przekazałem problem z tą ofertą do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy wyeliminujemy w niej błąd.

**Comment by AureliuszBrussy** [comment]
@rasskabak problem z ofertą 11138645914 nie powinien już występować. Aktualnie planujemy pracę nad całkowitym wyeliminowaniem tego problemu, aby takie rozspójnienia nie występowały. Gdybyś trafił na kolejne takie oferty - zgłoś to do nas.

**Comment by rasskabak** [comment]
Trafiam cały czas. Mam ponad 20 tyś ofert, dla których przynajmniej raz dziennie staram się zaktualizować stany magazynowe. Co któraś aukcja się zacina, więc nawet przy kilkugodzinnym cyklu "zgłoszenie-rozwiązanie problemu" efekt jest taki, że albo potrzebuję człowieka, który będzie nad tym czuwał, albo zamiast 1-dniowego cyklu aktualizacji stanów, robi się z niego cykl 1-tygodniowy... albo 1-miesięczny ;/

Ten sam produkt, oferta z innym kolorem - 11138646008

**Comment by rasskabak** [comment]
11138646081

**Comment by AureliuszBrussy** [comment]
Uspójniliśmy ofetę 11138646008. Sprawdzamy szerzej ten problem. Jak tylko coś ustalę - wrócę do Ciebie z odpowiedzią.

**Comment by rasskabak** [comment]
11246422103

**Comment by AureliuszBrussy** [comment]
@rasskabak wracam z informacją, że błędy z rozspójnieniami nie powinny się już powtarzać w przyszłości.
