### ISSUE TITLE
Nie pełny komunikat z WzA, za krótkie pole ulicy 

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#5373]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Tworząc paczkę z dpd ( id paczki 77f333a9-7d0a-419d-86fc-f857cb908c78)
Mam error "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem".
Przechodząc do interfejsu web podświetla mi jednak że nazwa ulicy jest za długa (30 znaków). 
"Świętej Teresy od dzieciątka Jezus XX"
Proszę o obsłużenie błędu przez api i zwiększenie pola.

**Comment by AureliuszBrussy** [comment]
Potwierdzam - błąd był związany z długością przekazanej wartości w polu **receiver.address.street**. Dodamy odpowiedni komunikat błędu dla takich przypadków. Jeżeli chodzi zwiększenie długości pola - tutaj ogranicza nas zewnętrzne API.
