### ISSUE TITLE
Allegro UPS - błąd podczas generowania kilku etykiet

### ISSUE THREAD

**Issue by rafalmaz** [allegro/allegro-api#5374]
Pracuję nad wdrożeniem nowego spedytora UPS do firmowego systemu Allegro. Bez problemu przygotowałem skrypt dla zamówień mieszczących się w jednej paczce, natomiast przy próbie uzyskania dwóch etykiet do jednego zamówienia pojawia się błąd o treści "Usługa wielopaczka nie jest dostępna u tego przewoźnika".
W samej dokumentacji API nie znalazłem fragmentu, który tłumaczyłby w jaki sposób nadawać kilka paczek za pomocą API. Widziałem jednak w poradniku allegro (https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1#zamowione-przesylki), że dla przesyłek UPS można wygenerować jedną paczkę, a następnie do tej jednej paczki dopisać kolejne. Nie widziałem jednak o tym informacji w dokumentacji API.
W jaki sposób mogę za pomocą API wykonać taką samą operację jak za pośrednictwem narzędzia Wysyłam z Allegro?

**Comment by MartaNowaczyk** [comment]
Sprawdzam opisaną sytuację.

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości zamówienia wielopaczki dla UPS - ograniczenie przewoźnika. W podanym poradniku przykłady dotyczą DPD i Poczty Polskiej.

**Comment by rafalmaz** [comment]
> Nie ma możliwości zamówienia wielopaczki dla UPS - ograniczenie przewoźnika. W podanym poradniku przykłady dotyczą DPD i Poczty Polskiej.

W tym fragmencie jest zaznaczony UPS i Poczta Polska i jest tutaj opisany sposób nadawania za pomocą systemu Allegro.
![image](https://user-images.githubusercontent.com/9217372/151797794-0c4a9256-379b-4011-9b2a-66bd4e41aeb7.png)

**Comment by MartaNowaczyk** [comment]
Skonsultowałam ten poradnik i z informacji jaką otrzymałam wynika, że UPS nie powinno być tam ujęte. Przepraszamy jeśli wprowadziliśmy Cię w błąd. Postaramy się w możliwie krótkim czasie zaktualizować stronę z tą informacją.

**Comment by rafalmaz** [comment]
Zweryfikowałem informację u osoby zajmującej się realizacją zamówień Allegro i wydaje mi się, że mówimy o dwóch różnych procesach.
W lipcu zeszłego roku pracownik Allegro potwierdził, że takie działanie jest możliwe (poniżej transkrypcja).

> **M... Sp. z o.o.**
15 lipca 2021, 13:26:13
Tzn., że jeśli w polu "kolejna sztuka" wpiszemy np. 8,99 to: Klient składa zamówienie, na 2 sztuki, także automatycznie koszt powinien się naliczyć 8,99 x 2 - rozumiem że przy SMARcie to ma już inne zasady działania i nadal jest 0 zł, tak?
**K... O...**
15 lipca 2021, 13:28:19
Pole "kolejna sztuka" polega na naliczeniu kosztu za kolejną sztukę w ramach tej samej przesyłki. Natomiast przy rozpoczęciu kolejnej paczki (przekroczeniu maksymalnej liczby w paczce) naliczamy koszt podstawowy przesyłki. Wyjątkiem są transakcje z usługą Allegro Smart w ramach której dodajemy możliwość generowania większej ilości darmowych etykiet
**M... Sp. z o.o.**
15 lipca 2021, 13:29:45
I rozumiem że wystarczy wtedy przy generowaniu etykiety podać adres e-mail kupującego, a wtedy Menadżer paczek/Shipping tool "wie", że pod to zamówienie jest możliwość wygenerowania kilku etykiet w cenie SMARTowej, zgadza się?
**K... O...**
15 lipca 2021, 13:30:05
Zgadza się :)
**M... Sp. z o.o.**
15 lipca 2021, 13:30:54
Rozumiem
**M... Sp. z o.o.**
15 lipca 2021, 13:32:20
Dziękuję za informację dot. cenników dostawy, uprzejmie proszę o wysłanie powyższej rozmowy na czacie na naszego maila (...@....pl)
**M... Sp. z o.o.**
15 lipca 2021, 13:32:32
Pozdrawiam!
**K... O...**
15 lipca 2021, 13:34:24
Oczywiście, prześlę Państwu transkrypt czatu :) Dziękuję za rozmowę, w razie dodatkowy pytań zachęcam do ponownego kontaktu. Pozdrawiam

W tym momencie proces, o którym piszę jest możliwy do wykonania po stronie Menadżera paczek Allegro, co widać poniżej:
![image](https://user-images.githubusercontent.com/9217372/151934560-ffd52006-e673-48e2-8460-92c3480bbadc.png)
Do zamówienia pracownik wygenerował 2 przesyłki UPS ze SMARTem.

Chciałbym taki sam efekt uzyskać korzystając z naszego wewnętrznego narzędzia. Może we wcześniejszych postach zbyt ogólnie opisałem swój problem i te screeny lepiej go przedstawią.

**Comment by MartaNowaczyk** [comment]
Dla UPS nigdy nie było możliwości stworzenia wielopaczki (czyli jednej przesyłki składającej się z kilku paczek). Zawsze są to osobne paczki, tyle, że przypisane do jednego zamówienia. Tak więc możesz nadać kilka osobnych paczek. O tym jak utworzyć paczkę przeczytasz w naszym [poradniku](https://developer.allegro.pl/wza/#jak-utworzy%c4%87-now%c4%85-paczk%c4%99). Jeśli w przyszłości napotkasz problem/otrzymasz błąd podeślij trace-id tego wywołania do weryfikacji.
