### ISSUE TITLE
EN/PL What aspect ratio is used for photos

### ISSUE THREAD

**Issue by pajter121** [allegro/allegro-api#5375]
PL
Dzień dobry, chciałbym się dowiedzieć w jakim formacie są wyświetlane zdjęcia (miniaturki oraz reszta zdjęć) na ekranie smartfonów oraz komputerów np. w aplikacji i przeglądarce, czy jest to zależne od konkretnego sprzętu czy od czegoś innego. Interesuje mnie jakie proporcje są wyświetlane, czy to zależy od zdjęcia czy zdjęcia są jakoś konwertowane na jakiś standard np. 1:1 lub 4:3? 

Good morning, I would like to know in what format (thumbnail and the rest of the photos) are displayed on screens of smartphones and computers ie. in app or web browser, is it dependent on particular hardware or something else. I am interested in what aspect ratio is displayed, is it dependent on the photo or are they converted to some standard like 1:1 or 4:3?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, zadane pytanie nie dotyczy REST API Allegro, dlatego zapraszam do kontaktu przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380&subjectId=3c76fd6e-310d-449a-9ca7-08977f5d30c8).

**Comment by pajter121** [comment]
Dziękuję za informację, kontaktowałem się wcześniej przez czat ale osoba przekierowała mnie właśnie tutaj.
