### ISSUE TITLE
Allegro sandbox wystawianie z pliku

### ISSUE THREAD

**Issue by mikson2137** [allegro/allegro-api#5377]
Dlaczego nie mam możliwości dodania ofert z pliku na stronie: https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/wystaw-z-pliku
?

![image](https://user-images.githubusercontent.com/65091994/151787326-aaf95906-ea75-413e-9aa7-869539bc5cc3.png)

**Comment by MartaNowaczyk** [comment]
Sprawa nie dotyczy API Allegro. Skontaktuj się proszę w tej sprawie przez [formularz kontaktowy.](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380&subjectId=3c76fd6e-310d-449a-9ca7-08977f5d30c8)
