### ISSUE TITLE
Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem - Sello

### ISSUE THREAD

**Issue by soundplayer1994** [allegro/allegro-api#5378]
Witam,

Sello wywala nam błąd przy tworzeniu listów przewozowych DPD: "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem" Jak rozwiązać ten problem?
Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Witam,
potrzebuję więcej danych, sam komunikat nie wskazuje jednoznacznie na przyczynę błędu. Podeślij proszę traceId dla tego wywołania, albo commandId. Jeśli nie masz takich danych, poproś o nie Sello. Pozdrawiam.

**Comment by soundplayer1994** [comment]
============================================================================ 15:06:45:427
GET https://api.allegro.pl/parcel-management/parcel-create-commands/9ee7c276-181a-44ae-81a7-d60427bf5259
{
Accept: application/vnd.allegro.public.v1+json
Accept-Language: pl-PL
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDM2NjMzNTgsInVzZXJfbmFtZSI6IjQzMjUyMzk2IiwianRpIjoiNGRlZTFhYzgtMzBmZi00NWVlLWJiOGYtMTM5YmU0NmJlZWQyIiwiY2xpZW50X2lkIjoiZjdhMTkyOWEtNTU0My00YmNlLWEzOGQtNTNhMGJmMjAwYWVlIiwic2NvcGUiOlsiYWxsZWdybzphcGk6b3JkZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOm9yZGVyczp3cml0ZSJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.yplL6p9ATh54jKW_hvpCBZXJG-Y0zGG5QczD12RuLlxKEthL3ckbzeT2JUibeW7KijL7yBX2Cp95Cl2oKwc_W0bD3V452ZUdoswZQdKwoRxMpIyUPZbTIJ5U-Pm-U0xM1fkqKMuuoF7QJxeVwXXD8C2Rl33hW8sQc_alAVeC9Ov4YuBnkH1VAlbnbcE7YGNgcb6yYlDy0g_V5IBuzjRDo2FDiexu_jLeDZi-8WNEy8dWQMJJLkBFXsdlm8TaAGXgVh5Wod1GlSfcA_C5QiwPHmJ2K8WEvITRJXE2AK4sxoGk1QlEgv1LZ4Jl8utjCojcdsOR5NF0CnHPMikJjcTJnw

}
RESPONSE 200 (OK) ----------------------------------------------------------------- 15:06:45:536 (109ms)
{
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: f8517eed7f9cde13
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
Cache-Control: no-store, must-revalidate, no-cache, max-age=0
Date: Mon, 31 Jan 2022 14:06:45 GMT

Content-Length: 276
Content-Type: application/vnd.allegro.public.v1+json
Expires: 0
}
{"id":"9ee7c276-181a-44ae-81a7-d60427bf5259","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"}]}

**Comment by MartaNowaczyk** [comment]
Błąd jest związany z polem receiver.address.street - przekroczono maksymalną długość dla tej wartości - 30 znaków. Dodamy odpowiedni komunikat błędu dla takich przypadków.
