### ISSUE TITLE
Błąd weryfikacji zweryfikownaej aplikacji

### ISSUE THREAD

**Issue by aogonowski** [allegro/allegro-api#5379]
Od jakiegoś czasu mam problem ze stworzoną dwa lata temu aplikacją dla mojego klienta. Obecnie autoryzacja przebiega pomyślnie, odświeżenie tokenu przebiega pomyślnie, aplikacja została zweryfikowana poprawnie na koncie klienta. Jednak kiedy uruchamiamy operacje na ofertach otrzymuję błąd:
Result: {"errors":[{"code":"VerificationRequired","message":"Access is denied. Verification is required.","details":null,"path":null,"userMessage":"Access denied. Access available only for verified applications."}]}
code: 403
Aplikacja widnieje jako zweryfikowana na koncie klienta.

**Comment by MartaNowaczyk** [comment]
Rozumiem, że chodzi o GET /offers/listing, do tego zasobu dostęp mają tylko zweryfikowane aplikacje. Tutaj masz [komunikat na GitHubie](https://github.com/allegro/allegro-api/issues/4566). Mamy też taką informację w naszym [poradniku](https://developer.allegro.pl/listing/).

**Comment by aogonowski** [comment]
Ok, dzięki.
