### ISSUE TITLE
Delivery-services -> No access to 'Wysyłam z Allegro'

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#5380]
Przy pobieraniu listy usług dostawy przez "https://api.allegro.pl/parcel-management/delivery-services" otrzymałem odpowiedź
trace-id: 17d2e0e7c46c6847
{"errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"Brak dostępu do 'Wysyłam z Allegro'. Aby uzyskać dostęp wystarczy, że przejdziesz na https://wysylam.allegro.pl - Twoje konto Allegro połączy się automatycznie"}]}
Na pięć sprawdzonych kont dla dwóch otrzymałem listę usług, dla pozostałych powyższy błąd.
Co mogę zrobić, aby wszystkie konta obsługiwały wysyłkę z Allegro?

**Comment by MartaNowaczyk** [comment]
Upewnij się czy na każdym koncie, dla którego występuje błąd masz powiązanie z Wysyłam z Allegro. Zaloguj się na każde konto i przejdź na stronę https://wysylam.allegro.pl. W razie dalszych problemów podeślij problemowe konta.
