### ISSUE TITLE
Automatyczna wielowariantowość

### ISSUE THREAD

**Issue by grzegorzwalus** [allegro/allegro-api#5382]
Czy istnieje możliwość wyłączenia automatycznego łączenia ofert dla konkretnego konta?
Nowo wystawione oferty automatycznie łączą się przez co komplikuje to tworzenie własnych wariantów. 

W FAQ w pytaniu numer 3 jest napisane, że można utworzyć ofertę wielowariantową zanim oferty zostaną połączone automatycznie tylko jak to zrobić?

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości wyłączenia automatycznego łączenia ofert.

Jeśli wystawisz oferty, a nasz system nie połączy jeszcze automatycznie ofert w ofertę wielowariantową, to właśnie to jest ten moment w którym możesz to zrobić samodzielnie.
