### ISSUE TITLE
Upload zdjęć psuje zdjęcia z każdym uploadem przez URL z Allegro

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5384]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry, chciałbym zgłosić bardzo osobliwy problem z uploadem zdjęć poprzez URL.
Mianowicie, dla oszczędności łącza wrzucam zdjęcie do aukcji na serwery Allegro jedynie raz. Potem korzystam ze zdjęć ostatniej aukcji, kiedy chcę wystawić nową aukcję tego samego przedmiotu po wygaśnięciu poprzedniej. 

Wygląda to tak:
1. upload poprzez zasób do wysyłania zdjęć w postaci binarnej
2. później upload poprzez podanie URL zdjęć poprzedniej aukcji
3. powtarzam proces dla każdej nowej aukcji korzystając z URL zdjęć poprzedniej aukcji

Problem polega na tym, że z czasem zdjęcia uszkadzają się. Przykład: 
![1](https://user-images.githubusercontent.com/37104952/151957308-79d0dfc6-6d19-498b-8fac-22f50005c80c.jpeg)

Można to odtworzyć, udało mi się przed chwilą to zrobić. Może błąd dotyczyć specyficznych zdjęć, więc podsyłam oryginał:
![2](https://user-images.githubusercontent.com/37104952/151957571-bec60b08-3964-4bf8-a3d9-9a6a31cfbebd.jpg)

Moim skromnym zdaniem nawala tutaj kompresja plików wchodzących przy uploadzie. Przy wielokrotnym procesie kompresji pliki są uszkadzane i pojawiają się artefakty.
Proszę o weryfikację opisanego przypadku.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, dziękuję za zgłoszenie. Podeślę do analizy zespołowi, który działa w tym temacie.

**Comment by MartaNowaczyk** [comment]
Podeślij jeszcze link do tego zdjęcia z utratą jakości.

**Comment by hahyes** [comment]
@MartaNowaczyk https://a.allegroimg.com/original/110a4b/fb9d3ea44387888694872653bdad
Proszę, tutaj odtworzyłem artefakty po bodajże 3 próbach. Nie jest to widoczne w takim stopniu jak w poście tutaj, ale na nogach są już zauważalne te paski.

**Comment by MartaNowaczyk** [comment]
@hahyes dzięki za link. Jak tylko coś ustalimy dam znać.

**Comment by hahyes** [comment]
@MartaNowaczyk Witam, czy coś ruszyło w sprawie tego problemu?

**Comment by MartaNowaczyk** [comment]
Sprawa jest w odpowiednim zespole i jak tylko ją przeanalizują dam znać.

**Comment by hahyes** [comment]
Nie, nie. Wątek wcale nie jest przeterminowany, panie bocie. Ja dalej czekam na odpowiedź. 
@MartaNowaczyk

**Comment by PrzemyslawLukanowski** [comment]
Pamiętamy o tym wątku - jak tylko uda nam się ustalić więcej szczegółów, wrócimy z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
@hahyes dzięki za cierpliwość. Wprowadziliśmy poprawkę. Zerknij czy teraz jest ok.

**Comment by hahyes** [comment]
> @hahyes dzięki za cierpliwość. Wprowadziliśmy poprawkę. Zerknij czy teraz jest ok.

@MartaNowaczyk Tak, błąd już nie występuje. Dziękuje bardzo za pomoc i pozdrawiam.

**Comment by hahyes** [comment]
@MartaNowaczyk Poprawka przestała działać z jakiegoś powodu. Na szybko przekazuje przykład z problemem.

```
https://a.allegroimg.com/original/11c910/114e3c9e40df807a812ac0029051 <= pierwszy upload, wygląda ok
https://a.allegroimg.com/original/11fc08/218cc14d454685a741044b3a0b2a <= drugi upload, pojawiają się paski
```

**Comment by Lukasz-Zurek** [comment]
@hahyes W imieniu mojej koleżanki Marty - przepraszam za te utrudnienia. Problem przekazałem już do zespołu odpowiedzialnego za zdjęcia w naszym Serwisie.

**Comment by Lukasz-Zurek** [comment]
@hahyes Przepraszam, że musiałeś tak długo czekać na odpowiedź.

Problem nie powinien już występować.

**Comment by hahyes** [comment]
> @hahyes Przepraszam, że musiałeś tak długo czekać na odpowiedź.
> 
> Problem nie powinien już występować.

@Lukasz-Zurek Wielkie dzięki. (y)
