### ISSUE TITLE
Limity offer-quantity-change-commands

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#5385]
Dzień dobry,
mam pytanie jakie są limity przy modyfikacji ilości zasobem: sale/offer-quantity-change-commands

Przykładowo dla aukcji: 11109906796 chce zmienić ilość z 89 do 999993

"{"modification":{"changeType":"FIXED","value":999993},"offerCriteria":[{"offers":[{"id":11109906796}],"type":"CONTAINS_OFFERS"}]}"

Ale dostaję informację że ilość jest nie poprawna.
"{"errors":[{"code":"INCORRECT_QUANTITY_VALUE","message":"Incorrect value of quantity","details":null,"path":"modification.value","userMessage":"Niepoprawana liczba sztuk."}]}"

Domyślam się że może być jakaś walidacja tylko nie znalazłem żadnego opisu.

**Comment by AureliuszBrussy** [comment]
Liczba sztuk w ofercie nie może przekroczyć 99999. W limit wlicza się liczba sztuk sprzedanych, czyli maksymalna wartość, o jaką możesz podnieść liczbę sztuk wynosi: 99999-(liczba sprzedanych sztuk). Nową ofertę możesz wystawić maksymalnie z wartością 99999.

**Comment by Raafal78** [comment]
A mam pytanie dodatkowe bo zauważyłem że w niektórych aukcjach nie mogę zaktualizować ceny.
Dostaję komunikat.
'Nie możesz podnieść ceny o więcej niż 100 zł. Maksymalna cena to .......'

Dla wszystkich produktów maksymalny limit zwiększenia ceny to jest 100 zł ?  Czy jest to jakoś progresywnie np produkty z ceną do 100 zł ceny nie można podnieść o dodatkowe 100 zł ale już dla produktów z ceną 1000 to cenę można maksymalnie podnieść o 1000 zł.

**Comment by Lukasz-Zurek** [comment]
@Raafal78 Jeżeli aktualna cena w ofercie wynosi do 50 zł - zwiększysz ją maksymalnie o 100 zł. Jeśli natomiast wynosi ona ponad 50 zł - zwiększysz ją maksymalnie o 200%.
