### ISSUE TITLE
The stock level of items to be listed may not be lower than 1.

### ISSUE THREAD

**Issue by manoos** [allegro/allegro-api#5387]
Występuje problem: 
 - [ x ] z zasobem REST API / with a REST API resource
 - [ x ] ze środowiskiem produkcyjnym / with the production environment

Witam,
dla oferty: 10463505872 wysyłam stan większy niż 1 i dostaję komunikat:  
      The stock level of items to be listed may not be lower than 1.

W czym może być problem ?

**Comment by AureliuszBrussy** [comment]
Przekazałem problem do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy wyeliminujemy błąd w tej ofercie.

**Comment by manoos** [comment]
Witam czy ruszyło się coś w temacie ?

**Comment by AureliuszBrussy** [comment]
@manoos niestety, jeszcze nie - poinformuję Ciebie, gdy tylko zespół odpowiedzialny za usługę naprawi błąd w tej ofercie.

**Comment by AureliuszBrussy** [comment]
@manoos wdrożyliśmy poprawkę. Proszę, spróbuj edytować liczbę sztuk w tej ofercie (10463505872).
