### ISSUE TITLE
Wygasający token przez weekend

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5388]
Witam,

Mam problem praktycznie w każdy weekend, że wygasa mi token, który potem musi ktoś uzyskać ręcznie poprzez logowanie na konto Allegro. Czy mogę gdzieś znaleźć informacje o przyczynie albo czy mogę uzyskać takie dane od Allegro? Chodzi mi o konto: eltrox_pl.

**Comment by MartaNowaczyk** [comment]
Na początek sprawdź proszę działanie swojej aplikacji, bo z tego co widzę, co minutę generujesz nowy token. Jeżeli chcesz pominąć konieczność ponownej autoryzacji aplikacji przez użytkownika, powinieneś po wygaśnięciu access_tokena skorzystać z refresh_tokena. Więcej przeczytasz w [naszym poradniku](https://developer.allegro.pl/auth/#przed%c5%82u%c5%bcenie-wa%c5%bcno%c5%9bci-tokena)
