### ISSUE TITLE
krank/matching-categories - nie działa od poniedziałku

### ISSUE THREAD

**Issue by Maczuga** [allegro/allegro-api#539]
Witam, przez długi czas można było pobierać listę pasujących kategorii do nazwy oferty za pomocą adresu:
http://allegro.pl/krank/matching-categories?country=PL&title=samsung

Zauważyłem, że podany adres od poniedziałku nie działa i został podmieniony nową metodą:
https://allegro.pl/offer-api/categoriesSuggestions/samsung

Problem w tym, że do działania tej metody wymagane jest podanie ciastka QXLSESSID , które jak mniemam jest identyfikatorem aktywnej sesji zalogowania, oraz headeru "Referer: https://allegro.pl/offer/"

2 pytania:

1. Dlaczego został dodany tak dziwny wymóg (chodzi głównie o ciastko QXLSESSID)?
2. Czy istnieje jakikolwiek sposób, aby móc dalej korzystać z tej metody bez kombinowania z ciastkiem sesji?

**Comment by PawelTaberski** [comment]
Wspieramy tylko metody, które udostępniamy naszym partnerom. Wszystkie opisane są w naszej dokumentacji [tutaj](https://developer.allegro.pl/documentation/#/). Aby korzystać z udostępnionych metod musisz się zautoryzować i uwierzytelnić. Więcej na ten temat [tutaj](https://developer.allegro.pl/auth/).

**Comment by rtnet-pl** [comment]
@Maczuga jest jeszcze https://allegro.pl/suggestions/?phrase=samsung&country=pl&sortByElementType=true
Z tym że tutaj sugestii jest mniej

**Comment by Maczuga** [comment]
@rtnet-pl Dzięki! Lepiej mieć chociaż tyle niż wcale :)
