### ISSUE TITLE
Company verification missing

### ISSUE THREAD

**Issue by mboes-nm** [allegro/allegro-api#5390]
Hi there,
we created the nmsales2021 account last year on https://allegro.pl.allegrosandbox.pl/ and uploaded the required documents, but have not yet received any feedback on the company verification. Can you help with this?

Best regards,
Matthias Bös

**Comment by MartaNowaczyk** [comment]
Hi, your account is already active. Have a nice day.

**Comment by mboes-nm** [comment]
Ok, but what about the company verification which is still pending?

**Comment by MartaNowaczyk** [comment]
After manual activation, it sometimes looks like this. Proceed to the next steps and try to list the test offer. If you succeed, that is, everything is fine. If not, let me know and I will verify it.

**Comment by mboes-nm** [comment]
Hi, we wanted to list the first products, but now it says the company verification was rejected. Can you provide more details why its rejected and what needs to be done? Many thanks

**Comment by PrzemyslawLukanowski** [comment]
In the Sandbox environment, everything looks OK on our side. Can you give me more details - screenshot when you're trying to list offer or sample response from our API? If the problem occurs in the production (Allegro.pl) environment please continue this issue via [contact form.](https://allegro.pl/help/contact)

**Comment by mboes-nm** [comment]
im just asking because of the status bar which shows that the company verification was rejected 
![image](https://user-images.githubusercontent.com/98888779/153873063-5bd3f1e6-1abe-42e6-ad16-b0997c41d28c.png)

When i checked it last week, the verification was still pending, but now its rejected. Does it mean anything or should we just proceed?

**Comment by PrzemyslawLukanowski** [comment]
Please proceed, on Sandbox, there may be some discrepancies when it comes to the account information. Sorry for the inconvenience.

**Comment by mboes-nm** [comment]
Ok sure, many thanks for your help.

**Comment by mboes-nm** [comment]
Hey, we received a mail that our account will be deactivated by the 22nd of february if we dont list an offer. This is strange because of two things: 
1. We have already products listed on our sandbox account "nmsales2021"
2. The email was sent to imarket_team@novomind.com which is not added in our sandbox account

Could you check if the email is really related to the account "nmsales2021" or if there might be older, not used accounts for which this mail was sent out? This would help a lot.

Many thanks,
Matthias

**Comment by MartaNowaczyk** [comment]
The e-mail address provided is for a production account, not for a sandbox. Account name edited: imarxxxxxxam.
