### ISSUE TITLE
Metoda pozwalające usunąć tabelę rozmiarów + mozliwość usunięcia jej w panelu Allegro

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#5395]
Świetnie że pojawiły się metody do tabel rozmiarów ale nie można ich usuwać. 
Rozumiem że chodzi o sytuację w której usuwam tabelę do której przypisane są produkty. 
Może teraz dojść do sytuacji że jeżeli jakiś system wysyłający tabele się zapętli to może stworzyć nieskończenie wiele tabel, których ani USER anie API nie jest w stanie pousuwać.

**Comment by hahyes** [comment]
To powinno być jako sugestia w Discussions.
Ale dołączam się, powinna istnieć możliwość usunięcia tabeli rozmiarów, jeżeli są one nieużywane przez jakąkolwiek z ofert na portalu.

**Comment by MartaNowaczyk** [comment]
@mirkosmuz wrzuć proszę tę sugestię na [Discussions](https://github.com/allegro/allegro-api/discussions), dzięki temu również inni użytkownicy będą mogli na nią zagłosować, co dodatkowo określi, jak bardzo priorytetowa jest to potrzeba.
