### ISSUE TITLE
Przy proponowaniu produktu jest zwracany błąd, że w Marka wartość spoza słownika jest niewłaściwa

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5396]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
chcąc utworzyć produkt w kategorii `5554` oraz wypełniając parametr Marka wartością spoza słownika otrzymuje błąd:
```
Nieprawidłowe wartości parametrów: [parameter = Marka [ Wartość spoza słownika - South Beach] , parameter = Rozmiar (obwód głowy w cm) [ Wartość niejednoznaczna - Inny]]
```
Trace-Id: 837f39452aa9f0d1

Z tego, co widzę parametr dla tego produktu ma wyznaczoną wartość dla wartości spoza słownika: `3786_85` i dokładnie taką wybrałem. Podałem wartość spoza słownika, ponieważ opcje tego parametru na to pozwalają poprzez `options.customValuesEnabled` ustawione na `true`. Co jest tutaj problemem? O ile rozumiem, dlaczego wyskakuje problem dla parametru Rozmiar, to dla Marka nie ma to żadnego sensu. 

Proszę o pomoc.

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z odpowiednim zespołem. Niebawem wrócę z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
Błąd dot. parametru Marka (`3786`) nie powoduje zatrzymania procesu tworzenia produktu, choć faktycznie pojawia się w naszym response, co wprowadziło nieco zamieszania. Ustalam kwestię tego komunikatu z zespołem odpowiedzialnym za zasób. 

Nie utworzymy produktu w przypadku, gdy wartość jednego z parametrów to `ambiguousValue`, a parametr ten nie przyjmuje wartości własnej (`customValuesEnabled=false`). Jeżeli w parametrze `4227` wskażesz jakąś konkretną wartość ze słownika (taką, która nie jest niejednoznaczna), to produkt zostanie utworzony.

**Comment by hahyes** [comment]
> Błąd dot. parametru Marka (`3786`) nie powoduje zatrzymania procesu tworzenia produktu, choć faktycznie pojawia się w naszym response, co wprowadziło nieco zamieszania. Ustalam kwestię tego komunikatu z zespołem odpowiedzialnym za zasób.

Definitywnie nie otrzymałem pozytywnego kodu statusu HTTP z zakresu 200, w przeciwnym razie bym nawet nie zauważył błędu, bo nie sprawdzam zawartości odpowiedzi w takim przypadku. Czekam w takim razie na szczegółowe wyjaśnienia, widziałem jeszcze parę takich błędów ale nie zapisałem trace-id. W każdym razie, robi zamieszanie.

> Nie utworzymy produktu w przypadku, gdy wartość jednego z parametrów to ambiguousValue, a parametr ten nie przyjmuje wartości własnej (customValuesEnabled=false).

Zdaje sobie z tego sprawę. Głównym sprawcą zamieszania jest tutaj marka.

**Comment by AureliuszBrussy** [comment]
@hahyes zespół odpowiedziany za zasób poruszy tą kwestię - wrócę do Ciebie z ustaleniami.

**Comment by hahyes** [comment]
bump

**Comment by MaciejFrackowiak** [comment]
@hahyes Pamiętamy o sprawie - czekamy na jednoznaczne informacje, które będziemy mogli Tobie przekazać.

**Comment by AureliuszBrussy** [comment]
@hahyes update: wdrożymy odpowiednią poprawkę, tak aby nasz response nie był mylący. Wrócę jeszcze z informacją po wdrożeniu.

**Comment by hahyes** [comment]
@AureliuszBrussy Pozostawiłem ten problem trochę samemu sobie myśląc, że prędzej czy później to się naprawi i nie chciałem męczyć ciągle pytając o progress ale minął ponad rok czasu a problem nadal występuje mimo wszystko. :/

**Comment by AureliuszBrussy** [comment]
@hahyes przepraszam za dotychczasowy brak rozwiązania, odkopuję ten temat z zespołem odpowiedzianym za tą usługę. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@hahyes w tym czasie wielokrotnie zmienialiśmy walidację, czy byłbyś w stanie podać przykładowe trace-id z taką sytuacją?

**Comment by hahyes** [comment]
@AureliuszBrussy Przesyłam przykład z kategorii sukienek: e270e651f2d50078

**Comment by AureliuszBrussy** [comment]
@hahyes dziękuję, przeanalizujemy to, wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
Tutaj mamy akurat ten sam przypadek, jak w zgłoszeniu #7094. 

Wartość, którą przesłałeś w tym parametrze wpadła na jedną z naszych reguł walidacji produktu. Traktujemy to jako wartość nieprawidłową - powinna się tam znaleźć realna nazwa marki. Jeżeli nie jesteś w stanie dopasować marki, skorzystaj z wartości "bez marki".

Jeżeli natomiast marka w istocie istnieje - sprzedający [poprzez formularz kontaktowy](https://allegro.pl/pomoc/kontakt) może poprosić o dodanie jej do słownika wartości.
