### ISSUE TITLE
Dodanie product id do oferty

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#5397]
Witam, mam pytanie za pomocą https://api.allegro.pl/sale/products?phrase=".$phrase; pobieram products id produktu, a potem jak chce wystawić lub edytować ofertę dostaje błąd:
VALIDATION_ERROR - Given product has TecDoc specification but it is not assigned to offer, use product TecDoc specification. Update offer with the most recent product data. - ConstraintViolationException.ValidTecdocSpecification - tecdocSpecification

Wielu ofert nie mogę połączyć z produktem, bo w waszym katalogu jest bałagan, jeden producent, jeden numer katalogowy a w bazie allegro kilka takich samych produktów. Do tego produkty mogą mieć kilka kodów EAN u Was w bazie jest jeden i jak chce połączyć ofertę dając inny ean ale do tego samego produktu to już nie mogę, bo ean nie pasuje.

Czy planujecie kiedyś zrobić porządek, bo kilka takich samych produktów w jednym katalogu to jest jakaś pomyłka ;)

**Comment by AureliuszBrussy** [comment]
Błąd o tej treści zwrócimy w przypadku, gdy produkt, z którego próbujesz skorzystać podczas wystawiania oferty ma uzupełnioną sekcję **tecdocSpecification**, natomiast w swoim requeście (przy próbie wystawienia oferty) nie wypełniasz tego pola. "tecdocSpecification" zwrócimy, gdy pobierzesz szczegóły danego produktu ([GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)).
Dane w ofercie muszą być takie same, jak dane wybranego produktu. 

Więcej o tym możesz przeczytać w [naszym poradniku](https://developer.allegro.pl/productization/#3-jak-zarz%c4%85dza%c4%87-produktem-w-ofercie). 

Jeden produkt może w naszym Katalogu Produktów posiadać kilka EANów. 

Oczywiście cały czas pracujemy nad poprawą i ulepszeniem naszego Katalogu Produktów. Katalog produktów Allegro tworzymy w oparciu o wiele informacji, w tym sugestii od sprzedających czy integratorów.

**Comment by mskiba03** [comment]
To dlaczego w takim razie nie mogę połączyć z produktem ofert z GATES KP55500XS dostaje komunikat "Parametr EAN w Twojej ofercie jest przypisany do innego produktu w Katalogu." Natomiast gdy sprawdzam ten ean 5414465377051, który mam podany w ofercie to jest on od tego produktu?

Mam jeszcze pytanie, czy dalej automatycznie powiązujecie oferty z produktem i w jakim interwale czasowym. Wcześniej jak wystawiałem kilka tysiecy aukcji bez podawania product id to one sie wiązały same . A obecnie na nowym koncie wystawi sie jedna a reszta idzie do draftu bo ta jedna co się wystawi jest nie powiązana i mam 0% powiązań ;)

**Comment by AureliuszBrussy** [comment]
Podaj proszę trace-id wywołania (znajdziesz go w nagłówku naszego response'a), gdzie próbujesz połączyć ofertę z produktem, a otrzymujesz wspomniany błąd. Sprawdzę to dokładnie.

Co do automatycznego powiązywania: nasze propozycje powiązać ofert z produktami znajdziesz w zakładce [Powiąż oferty z produktami](https://allegro.pl/moje-allegro/sprzedaz/powiaz-oferty-z-produktami). Jeżeli znajdziemy odpowiednie produkty - możesz zaakceptować lub odrzucić powiązanie. Jeżeli nie podejmiesz żadnego działania, powiążemy je automatycznie po 14 dniach.
