### ISSUE TITLE
Nie można wznowić oferty

### ISSUE THREAD

**Issue by ahaw** [allegro/allegro-api#5398]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Nie można wznowić offerty za pomocą api.
Korzystam z zasobu: /sale/offer-publication-commands/

Zasób /sale/offer-publication-commands/guid/tasks zwraca następujący bład:
"Could not change offer publication status. Niedopuszczalne znaki w wartości EANu (dopuszczalne cyfry lub X).",

EAN przypisanego produktu to: 611901211084
GUID operacji: 86DC6952-F83F-475F-8819-3FD8019F7F44

```
{
  "tasks": [
    {
      "offer": {
        "id": "",
        "colorPattern": null
      },
      "message": "Could not change offer publication status. Niedopuszczalne znaki w wartości EANu (dopuszczalne cyfry lub X).",
      "status": "FAIL",
      "scheduledAt": "2022-02-03T21:14:29.753Z",
      "finishedAt": "2022-02-03T21:14:29.736Z",
      "field": "publication",
      "errors": [
        {
          "code": "ConstraintViolationException.InvalidCharacterInGtinParameter",
          "message": "Provided EAN code is incorrect",
          "details": null,
          "path": "parameters",
          "userMessage": "Niedopuszczalne znaki w wartości EANu (dopuszczalne cyfry lub X)."
        }
      ]
    }
  ]
}

```

**Comment by AureliuszBrussy** [comment]
Wartość przekazana w parametrze EAN (id: 225693) w tej ofercie to "204.613.78" - stąd komunikat błędu i brak możliwości aktywacji oferty. Sprawdź draft tej oferty (np. [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET)) i zmodyfikuj (np. [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT)) wartość w parametrze 225693.

**Comment by ahaw** [comment]
@AureliuszBrussy 
Niestety wciąż pojawia się problem dla guid: c6ad57df-434c-4b4a-b4d6-e55dbd9fc6e6 z tym samym błedem.
Zgodnie z sugestią sprawdziłem ean w parametrze o id "225693" i ma on wartość "5999885976898".
