### ISSUE TITLE
Pobranie nowego opisu - struktura json zamiast html

### ISSUE THREAD

**Issue by aktywnitu** [allegro/allegro-api#54]
W jaki sposób mogę szybko pobrać dla wielu ofert opis allegro w formie struktury json.
doGetItemsInfo z parametrem   'getDesc':1 zwraca opis HTML - potrzebuję json nowego opisu.

**Comment by AniaMalinowska** [comment]
W danych zwracanych w metodzie [doGetItemsInfo](https://allegro.pl/webapi/documentation.php/show/id,52#method-output) otrzymujesz 2 pola, które dotyczą opisu. Nowy opis oferty otrzymasz w polu itStandardizedDescription | string.

**Comment by aktywnitu** [comment]
Dziękuję.
