### ISSUE TITLE
GET /offers/listing + filtrowanie

### ISSUE THREAD

**Issue by tony6636** [allegro/allegro-api#540]
W dotychczasowej metodzie WebService doGetItemsList moglem podać filtr offerType=buyNow. Endpoint https://developer.allegro.pl/documentation/#/offers-listing/getListing tego nie wspiera ?

**Comment by PawelTaberski** [comment]
W responsie do tej metody otrzymasz dostępne filtry. Oczywiście można sortować po typie ofert: `        {
            "id": "sellingMode.format",
            "type": "MULTI",
            "name": "rodzaj oferty",
            "values": [
                {
                    "value": "BUY_NOW",
                    "name": "kup teraz",
                    "count": 0,
                    "selected": false
                },
                {
                    "value": "AUCTION",
                    "name": "licytacje",
                    "count": 0,
                    "selected": false
                }
            ]
        },`

**Comment by tony6636** [comment]
tak, ale mi chodzi aby w początkowym zapytaniu ustawić filtr aby szukało tylko aukcji "Kup teraz"

**Comment by PawelTaberski** [comment]
Nie bardzo rozumiem, wyszukiwarka działa na takiej samej zasadzie jak na stronie, aby zastosować wyszukiwanie np. po typie oferty musisz podać np. numer kategorii w jakiej chcesz szukać. Na takiej samej zasadzie działa metoda DoGetItemsList. Jeśli wywołasz request z samym wyszukiwaniem typem oferty w odpowiedzi dostaniesz błąd:
`      <SOAP-ENV:Fault>
         <faultcode>ERR_FILTER_DEPENDENCY_AT_LEAST_ONE</faultcode>`
Możesz wywołać w REST API wyszukiwanie ofert typu kup teraz w danej kategorii np:
GET https://api.allegro.pl/offers/listing?category.id=253597&sellingMode.format=BUY_NOW

**Comment by sbrzezin** [comment]
Witam,

Kontynuując wątek wyszukiwania i filtrowania: czy ja coś przeoczyłem, czy też nie da się wyszukać aukcji gdy znamy jej id?

Sergiusz

**Comment by PawelTaberski** [comment]
@sbrzezin Obecnie nie ma takiej możliwości w zasobie offers/listing.
Jednakże zgłaszałem już takie zapotrzebowanie, gdyż więcej ludzi zgłasza taką potrzebę. Jeśli dostanę informacje, że zdecydujemy się wdrożyć taką opcję to poinformujemy o tym w dedykowanym komunikacie.
