### ISSUE TITLE
Weryfikacja konta firmowego

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#5400]
Już od wielu tygodni mojego konto olmed-sandbox oczekuje na weryfikację firmy. Gdzie mogę się zgłosić żeby ktoś to zatwierdził?

**Comment by MartaNowaczyk** [comment]
Przy ręcznej aktywacji konta, a taka miała miejsce w przypadku tego konta, w krokach do wykonania może Pan widzieć, że "Weryfikacja firmy" jeszcze się nie zakończyła, jednak wszystko powinno działać. W systemie widzę to konto jako firmowe zweryfikowane.

**Comment by relains** [comment]
Jak wchodzę w Jakość mojej sprzedaży to mam komunikat.

> Nie możemy Ci pokazać danych o Twojej jakości sprzedaży
> Wskaźniki pokazujemy tylko aktywnym sprzedawcom. W ostatnich 30 dniach na Twoim koncie nie było żadnej aktywnej oferty.

Mimo, że mam aktywne oferty.

Do tego jak wejdę w Obsługa zamówień -> Zamówienia to na pasku na górze mam ciągle informację, że firma jest w trakcie weryfikacji.

**Comment by MartaNowaczyk** [comment]
Przekazałam te informację do odpowiedniego zespołu. Dam znać jak tylko zweryfikujemy opisany problem.

**Comment by MartaNowaczyk** [comment]
Przepraszam za długie oczekiwanie na odpowiedź. Informacji w zamówieniach o weryfikacji konta firma już nie ma.  
Jeśli mimo to, masz problemy z informacjami o jakości sprzedaży, zgłoś to proszę przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=ec309d78-fd4c-4ed1-aad5-0e382e5a0e14&subjectId=7661201b-66e0-490d-b6a0-3ff5195d478d).
