### ISSUE TITLE
Rozbieżność wymaganego parametru między www a API

### ISSUE THREAD

**Issue by michalpokora** [allegro/allegro-api#5401]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Występuje rozbieżność dla parametru EAN w kategorii id 99392. W formularzu wystawiania oferty przez stronę www parametr EAN oznaczony jest jako opcjonalny. Po pobraniu parametrów dla kategorii po API parametr oznaczony jest jako wymagany. 

GET https://api.allegro.pl/sale/categories/99392/parameters

` {
            "id": "225693",
            "name": "EAN",
            "type": "string",
            "required": true,
            "requiredForProduct": true,
            "unit": null,
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": "11323",
                "requiredDependsOnValueIds": [
                    "11323_1"
                ],
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            }`

**Comment by MartaNowaczyk** [comment]
Wymagalność tego parametru zależna jest od parametru stan "dependsOnParameterId": "11323" - jak na formularzu wybierzesz stan "Nowy" to EAN też będzie wymagany.

**Comment by michalpokora** [comment]
Dziękuję za odpowiedź.
