### ISSUE TITLE
Brak możliwości wystawiania ofert przez API (limit powiązanych ofert)

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#5404]
Dzień dobry,

Osunąłem wszystkie oferty na koncie. Jednak przy próbie wystawiania ofert na nowo dostaję komunikat:
You cannot publish offer without a related product because you have too few offers related to a product in that category. Select or create a new product and associate it with your offer. 

Kategoria: motoryzacja

Podczas wystawiania podaje wszystkie podstawowe parametry, EAN, rozmiar, producenta itd. Dotychczas miałem 100% powiązanych ofert z katalogiem. Dlaczego teraz nie mogę nic dodać skoro mechanizm jest ten sam? Dlaczego wcześniej automatycznie się  to łączyło z produktem na allegro, a teraz jakoś to nie działa?

Proszę o pilną pomoc.

**Comment by MartaNowaczyk** [comment]
Na podstawie tego co piszesz nie jestem w stanie stwierdzić co dokładnie robisz. Podaj konkretne dane jak trace-id lub podeślij request i response dla takiej sytuacji. Poza tym jeśli wcześniej dodałeś produkty lub wyszukałeś, to powinny być już w naszym katalogu do ponownego wykorzystania.

**Comment by lukiopmoto** [comment]
Nie wiem czy o to chodzi:

    [name] => 2x LOREM IPSUM
    [category] => Array
        (
            [id] => 257691
        )

    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => <h1>aaa</h1><p>bbb<p>
                                        )

                                )

                        )                  

                )

        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => 8a26c0ec-65f1-4b07-ad1e-xxx
                )

            [returnPolicy] => Array
                (
                    [id] => 7e38f433-b8e2-46af-bfb7-xxx
                )

            [warranty] => Array
                (
                    [id] => 694fab50-d4ba-4f54-9b30-xxx
                )

        )

    [publication] => Array
        (
            [duration] =>
            [status] => INACTIVE
        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 630
                    [currency] => PLN
                )

            [netPrice] => Array
                (
                    [amount] => 513
                    [currency] => PLN
                )

            [startingPrice] =>
            [minimalPrice] =>
        )

    [tax] => Array
        (
            [rate] => 23.00
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [1] => Array
                (
                    [id] => 15808
                    [valuesIds] => Array
                        (
                            [0] => 15808_2
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [2] => Array
                (
                    [id] => 9300
                    [valuesIds] => Array
                        (
                            [0] => 9300_33
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [3] => Array
                (
                    [id] => 345
                    [valuesIds] => Array
                        (
                            [0] => 345_9
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [4] => Array
                (
                    [id] => 344
                    [valuesIds] => Array
                        (
                            [0] => 344_64
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [5] => Array
                (
                    [id] => 127088
                    [valuesIds] => Array
                        (
                            [0] => 127089_9
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [6] => Array
                (
                    [id] => 201169
                    [valuesIds] => Array
                        (
                            [0] => 201169_151033
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [7] => Array
                (
                    [id] => 9301
                    [valuesIds] => Array
                        (
                            [0] => 9301_15
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [8] => Array
                (
                    [id] => 248224
                    [valuesIds] => Array
                        (
                            [0] => 248224_868943
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [9] => Array
                (
                    [id] => 248225
                    [valuesIds] => Array
                        (
                            [0] => 248225_868955
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [10] => Array
                (
                    [id] => 129191
                    [valuesIds] => Array
                        (
                            [0] => 129191_10
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

            [11] => Array
                (
                    [id] => 217737
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => WR D4
                        )

                    [rangeValue] =>
                )

            [12] => Array
                (
                    [id] => 225693
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 6419440403892
                        )

                    [rangeValue] =>
                )

            [13] => Array
                (
                    [id] => 17448
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 18
                        )

                    [rangeValue] =>
                )

            [14] => Array
                (
                    [id] => 224017
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => T431215
                        )

                    [rangeValue] =>
                )

            [15] => Array
                (
                    [id] => 200981
                    [valuesIds] => Array
                        (
                            [0] => 200981_868933
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] =>
                )

        )

    [customParameters] => Array
        (
            [0] => Array
                (
                    [name] => Kolor napisów na boku
                    [values] => Array
                        (
                            [0] => czarne
                        )

                )

        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => KUJAWSKO_POMORSKIE
            [city] => XXX
            [postCode] => XX-XXX
        )

    [external] => Array
        (
            [id] => 112938
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => d678c5cc-e19d-4855-bb6a-xxx
                )

            [handlingTime] => PT48H
        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/11a50c/7621d5c642bxxx
                )

            [1] => Array
                (
                    [url] => https://a.allegroimg.com/original/11fef5/55675c504d7xxx
                )

            [2] => Array
                (
                    [url] => https://a.allegroimg.com/original/1157a3/c78d587a4d03bxxx
                )

            [3] => Array
                (
                    [url] => https://a.allegroimg.com/original/114e60/eb8a08574980axxx
                )

            [4] => Array
                (
                    [url] => https://a.allegroimg.com/original/111152/39b8f30c430396xxx
                )

            [5] => Array
                (
                    [url] => https://a.allegroimg.com/original/11fb2b/65dae276446cxxx
                )

            [6] => Array
                (
                    [url] => https://a.allegroimg.com/original/11bc2e/a0b544414580a2b6xxx
                )

            [7] => Array
                (
                    [url] => https://a.allegroimg.com/original/113992/09dc0ed24c0xxx
                )

            [8] => Array
                (
                    [url] => https://a.allegroimg.com/original/11be33/54ded3014108axxx
                )

        )

    [stock] => Array
        (
            [available] => 50
            [unit] => PAIR
        )

**Comment by lukiopmoto** [comment]
Pełne response:

<pre>{"id":"11788199779","name":"1x Nokian WR D4 175/65R14 82T 2021 CICHE Nowe","category":{"id":"257691"},"product":null,"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"15808","valuesIds":["15808_1"],"values":[],"rangeValue":null},{"id":"9300","valuesIds":["9300_33"],"values":[],"rangeValue":null},{"id":"345","valuesIds":["345_6"],"values":[],"rangeValue":null},{"id":"344","valuesIds":["344_256"],"values":[],"rangeValue":null},{"id":"127088","valuesIds":["127088_3"],"values":[],"rangeValue":null},{"id":"201169","valuesIds":["201169_150997"],"values":[],"rangeValue":null},{"id":"9301","valuesIds":["9301_14"],"values":[],"rangeValue":null},{"id":"248224","valuesIds":["248224_868943"],"values":[],"rangeValue":null},{"id":"248225","valuesIds":["248225_868955"],"values":[],"rangeValue":null},{"id":"129191","valuesIds":["129191_9"],"values":[],"rangeValue":null},{"id":"217737","valuesIds":[],"values":["WR D4"],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["6419440136882"],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["9"],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["T429501"],"rangeValue":null},{"id":"1","valuesIds":[],"values":["2021"],"rangeValue":null},{"id":"200981","valuesIds":["200981_868933"],"values":[],"rangeValue":null}],"customParameters":[{"name":"Kolor napisów na boku","values":["czarne"]}],"description":{"sections":[{"items":[{"type":"TEXT","content":"\n                    <h1>1x Opona zimowa Nokian WR D4 175/65R14 82T / Cicha / Produkcja 2021</h1>\n                    <p><b>Kup</b> wygodnie i bezpiecznie <b>u certyfikowanego eksperta</b> od opon osobowych i dostawczych.</p><h2>Główne cechy:</h2><ul><li><b>Sezon:</b> opona zimowa</li><li><b>Aukcja dotyczy:</b> 1 sztuki (jednej opony)</li><li><b>Stan:</b> fabrycznie nowa, oryginalna</li><li>Gatunek: pierwszy</li><li>Przeznaczenie: auta osobowe, SUV, 4x4</li><li><b>Rok produkcji:</b> 2021</li><li><b>Gwarancia:</b> 5 lat</li><li>Kod produktu: AT429501</li><li>Krótka droga hamowania na mokrym</li><li>Bardzo ciche</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11a50c/7621d5c642b0b2ff0280b7c86d31"},{"type":"TEXT","content":"<h2>Specyfikacja:</h2><ul><li>Marka: <b>Nokian</b></li><li>Klasa: premium</li><li>Model: <b>WR D4</b></li><li>Rozmiar: <b>175/65R14</b> (175/65 R14)</li><li>Szerokość: 175 mm</li><li>Wysokość: 65</li><li>Średnica: R14 (14 cali)</li><li>Indeks nośności: <b>82</b></li><li>Max. nośność: 475 kg na oponę</li><li>Indeks prędkości: <b>T</b></li><li>Max. prędkość: 190 km/h</li><li>Inne oznaczenia: 3PMSF, M+S</li></ul><h2>Oznaczenia dodatkowe:</h2><ul><li><b>3PMSF</b> - Symbol płatka śniegu na tle potrójnego szczytu (symbol alpejski) oznaczający, że opony gwarantują niezawodność i bezpieczeństwo na śniegu. Oznaczenie otrzymują wyłącznie opony, które otrzymały pozytywny wynik w znormalizowanych testach osiągów w zakresie mobilności i bezpieczeństwa w warunkach zimowych.</li><li><b>M+S</b> - Opona o konstrukcji zoptymalizowanej pod kątem przyczepności na błocie oraz świeżym lub topniejącym śniegu. Stanowi deklarację producenta, że dana opona radzi sobie lepiej w błocie czy śniegu niż standardowa.</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11fef5/55675c504d788d8c2645fd5c52c0"},{"type":"TEXT","content":"<h1>Wady i zalety modelu WR D4</h1><p>Opony Nokian WR D4 zaprojektowano z myślą o środkowoeuropejskich drogach. Zastosowano wyłącznie nowoczesne technologie. Producent gwarantuje pełne bezpieczeństwo podczas jazdy. Bieżnik jest sercem opony dlatego inżynierowie Nokian poświęcili my bardzo dużo uwagi. WR D4 wyposażono w kierunkowy wzór bieżnika, który doskonale sprawdza się w każdych warunkach pogodowych. W centralnej części bieżnika znajduje się podłużne żebro, które zapewnia doskonałe prowadzenie i precyzyjne skręty auta. Opony Nokian WR D4 zbudowano w oparciu o małe klocki na bieżniku, usiane grubą warstwą lameli po obu stronach opony.</p><p>Dzięki szerokim blokom barkowym opony zimowe Nokian zwiększają czułość prowadzenia samochodu na drodze i doskonale podążają za poleceniami kierownicy podczas nagłych manewrów. Specjalna mieszanka gumowa, która w swoim składzie zawiera silikon odpowiada za zmniejszone opory toczenia co przekłada się na oszczędność paliwa. Kolejną cechą wyróżniającą ten bieżnik spośród tłumu innych zimowych propozycji jest niski wskaźnik zużycia, długa żywotność, zachwycająca przyczepność boczna i wzdłużna opony Nokian na oblodzonych drogach.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11214f/d2ea2efa4b37b30739a2b23bd740"},{"type":"TEXT","content":"<h1>Najnowsza etykieta opony</h1>\n<h2>Opór toczenia - klasa C</h2>\n<p>Zużycie paliwa odgrywa ważną rolę z ekonomicznego i ekologicznego punktu widzenia. Im niższe opory toczenia, tym mniejsza ilość zużywanej energii oraz niższe zużycie paliwa i emisja CO2. Przykładowo różnica w spalaniu między klasą E oraz C wynosi 1/10 litra na 100km.</p>\n<h2>Przyczepność na mokrym - klasa B</h2>\n<p>Klasyfikacja przyczepności wskazuje, jak dobrze opona będzie się zachowywać na mokrej nawierzchni, a jej osiągi są oceniane w skali od klasy A do G. Ocena A oznacza krótką drogę hamowania na mokrej nawierzchni. </p>\n<h2>Hałas zewnętrzny - 68dB</h2>\n<p>Poziom hałasu zewnętrznego (w decybelach) emitowanego przez oponę auta poruszającego się z prędkością 80km/h. Opona zimowa 175 65 14 Nokian WR D4 emituje hałas na poziomie 68 decybeli.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/113992/09dc0ed24c0aaa420997910708b9"},{"type":"TEXT","content":"                <h1>Rok produkcji opon - 2021</h1>\n                <p>Pełna automatyzacja magazynu gwarantuje, iż każda zakupiona przez Ciebie opona na 100% pochodzić będzie z <b>2021</b> roku. Masz więc pewność otrzymania nowych, pełnowartościowych opon, których każda przed przyjęciem na magazyn została ręcznie weryfikowana pod kątem jakości oraz roku produkcji.</p>\n                <h2>Dlaczego najwięcej kierowców wybiera opony z 2021?</h2>\n                <p>Bieżnik opony wykonany jest z mieszanki gumy, kauczuku oraz krzemionki. Proces wiązania chemicznego wspomnianych substancji, wymaga czasu by osiągnąć pełną swoją wytrzymałość i parametry. Mamy tutaj analogię do betonu, który pełną swoja wytrzymałość uzyskuje dopiero po 28 dniach. Nic zatem dziwnego, iż coraz częściej <b>roczne opony wygrywają w testach</b> hamowania ze swoimi świeżo wyprodukowanymi odpowiednikami.</p>\n                <h2>Polska norma PN-C94300-7</h2>\n                <p>Według polskiej normy PN-C-94300-7 opony do 3 lat od daty ich produkcji zachowują 100% właściwości oraz wszystkie swoje parametry w zakresie bezpieczeństwa i eksploatacji.</p>\n                <h2>Kup opony z 2021 roku i nie przepłacaj</h2>\n                <p>Opony starzeją się wyłącznie na skutek fizycznych i chemicznych procesów takich jak promieniowanie UV, duża wilgotność, wysoka temperatura czy kontakt z substancjami typu benzyna, oleje, smary czy inne płyny samochodowe. <b>Nasze opony przechowujemy w idealnych warunkach</b> w suchym, klimatyzowanym i ciemnym magazynie z dala od wilgoci, substancji szkodliwych oraz promieniowania słonecznego (UV).</p>\n                <h2>Po ilu latach należy wymienić opony na nowe?</h2>\n                <p>Producenci opon na całym świecie deklarują, iż żywotność opony kończy się mniej więcej <b>po 7-10 latach</b> od daty jej wyprodukowania. Dodatkowo, od kilkunastu lat mieszanki gumowe, z których wykonane są opony - zawierają substancje przeciwstarzeniowe. Dzięki temu mamy gwarancię, że opona składowana w prawidłowy sposób nawet przez wiele lat, dzięki swym odpowiednim właściwościom, zachowuje cechy nowej opony.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11be33/54ded3014108a8b761e9689442ed"},{"type":"TEXT","content":"<h1>Aktualne wyniki w testach</h1><p>Pogrubioną czcionką (np: <b>ADAC</b>) oznaczyliśmy organizatora danego testu.</p><h2>Nokian WR D4:</h2><ul><li>Polecana <b>ADAC</b> 2016</li><li>Polecana <b>Autoklub CR</b> 2016</li><li>Polecana <b>GTU</b> 2015</li><li>2 miejsce <b>Auto Express</b> 2016</li><li>2 miejsce <b>ACE</b> 2018</li><li>2 miejsce <b>GTU</b> 2016</li></ul><h2>Opony zimowe Nokian:</h2><ul><li>1 miejsce <b>OFF-ROAD</b> 2018 (235/60R18)</li><li>2 miejsce <b>ACE</b> 2018 (185/65R15)</li><li>3 miejsce <b>Auto Zeitung</b> 2018 (235/60R18)</li><li>3 miejsce <b>Auto Motor</b> 2018 (205/55R16)</li><li>4 miejsce <b>ADAC</b> 2017 (215/65R16)</li><li>4 miejsce <b>ADAC</b> 2018 (175/65R14)</li></ul>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/114e60/eb8a08574980ad75edb0052b98bf"},{"type":"TEXT","content":"<h1>O firmie Nokian</h1><p>Producentem modelu opony WR D4 w rozmiarze 175/65R14 jest marka Nokian. Nokian to doskonałe osiągi, trwałość i niezawodność. Podobnie jak wiele największych firm oponiarskich naszych czasów, Nokian Tyres została założona na samym początku ery motoryzacyjnej, w 1898 roku. Firma zaczynała od produkcji różnych wyrobów gumowych. Po przeniesieniu zakładu z Helsinek do Nokii na początku w 1924 roku rozpoczęto przygotowania do produkcji rowerów. Wraz z rozwojem motoryzacji znacznie wzrosło zapotrzebowanie na opony, dlatego rozpoczęto także produkcję ogumienia.</p><p>Co ciekawe, pierwsza partia opon Nokian liczyła zaledwie kilka sztuk, ale już dwa lata później produkcja działała przez całą dobę na trzy zmiany. W 1988 roku narodziła się marka opon Nokian, która później stała się jednym z liderów branży oponiarskiej. Z biegiem czasu moce produkcyjne koncernu rosły i wymagały rozbudowy. W 2005 roku produkcja Nokiana została zorganizowana w Rosji w największej i najnowocześniejszej fabryce opon na świecie.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/111152/39b8f30c430396aaa06fd292aff8"},{"type":"TEXT","content":"<h1>Opony zimowe Nokian - bezpieczeństwo w niskich temperaturach, na śniegu i błocie pośniegowym</h1><p>Nokian WR D4 175 65 14 82 T należy to kategorii opon zimowych. Opony zimowe zbudowane są ze specjalnej mieszanki o wysokiej zawartości krzemionki i naturalnego kauczuku, które pozwalają na zachowanie elastyczności gumy w temperaturze poniżej 7°C, co przyczynia się do skrócenia drogi hamowania. Specjalna budowa bieżnika oparta o odpowiednio wyprofilowane, głębokie kanały odprowadzające wodę i błoto pośniegowe ogranicza ryzyko poślizgu nawet przy dużej prędkości. Niezależnie od marki, wspólną cechą wszystkich opon zimowych jest obecność lameli o różnych kształtach gęsto przecinających bloki bieżnika.</p><p>Te niezliczone krawędzie wgryzają się w śnieg i lód zapewniając bezkonkurencyjną przyczepność, i stabilność samochodu w niekorzystnych warunkach. Należy pamiętać, że to nie obecność śniegu i lodu uzasadnia zakup opon zimowych, a odpowiednio niska temperatura. Opon zimowych nie powinno się jednak używać w sezonie letnim. Mieszanka jest zbyt miękka na suchy asfalt, wobec czego szybciej się zużyje. Ponadto w związku z większymi oporami toczenia wzrasta zużycie paliwa oraz hałas na drodze.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11fb2b/65dae276446c93128e1cbb92e392"},{"type":"TEXT","content":"<h1>Opony Nokian - gwarancja najwyższej jakości</h1><p>Opona zimowa 175 65 R14 Nokian WR D4 pozycjonowana jest przez branżę motoryzacyjną jako produkt klasy premium. Oferują doskonałe parametry użytkowe, dzięki wykonaniu z najwyższej jakości składników i zastosowaniu innowacyjnych technologii. Innowacyjna rzeźba bieżnika, specjalnie opracowana mieszanka gumowa i wprowadzenie na rynek poprzedzone długotrwałymi badaniami, sprawiają że opony premium to rozwiązanie dla najbardziej wymagających kierowców. Sprawdzą się szczególnie w samochodach szybkich, sportowych, gwarantując doskonały komfort i bezpieczeństwo zarówno na suchej, jak i na mokrej nawierzchni.</p><p><b>Opony klasy premium</b> to najbardziej zaawansowane technologicznie produkty na rynku. Nowatorskie rozwiązania pojawiają się na początku właśnie w oponach klasy wyższej. W efekcie oferują doskonałą przyczepność niezależnie od warunków panujących na drodze, wysoki poziom komfortu, odporność na zużycie i niskie opory toczenia. Opony klasy premium zajmują czołowe pozycje w testach organizowanych przez organizacje i czasopisma motoryzacyjne.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11bc2e/a0b544414580a2b6fac439d8641f"},{"type":"TEXT","content":"\n            <h1>Kup u eksperta od opon!</h1>\n            <p>Dlaczego warto kupić oponę Nokian WR D4 175/65R14 82T na naszej aukcji? Zobacz co otrzymujesz dodatkowo:</p>\n            <p><b>Całodobowa pomoc</b> - Przez lata udało nam się zebrać prawdziwy zespół profesjonalistów, którzy szybko i sprawnie pomogą w zakupie opon i zorganizowaniu dostawy. Naszą firmę tworzą doświadczeni, energiczni, ambitni ludzie, których zainteresowania obejmują różne dziedziny motoryzacji i nie tylko. W pilnych sprawach dotyczących zamówienia czy przesyłki jesteśmy do dyspozycji przez 7 dni w tygodniu oraz 24h na dobę.</p>\n            <p><b>Najdłuższy okres zwrotów</b> - Jeśli z jakiegoś powodu otrzymane zamówienie cię nie satysfakcjonuje, a opona nie posiada śladów użytkowania to możesz ją zwrócić w ciągu 31 dni od daty dostarczenia.</p>\n            <p><b>Wieloletnie doświadczenie</b> - Na niezwykle trudnym i wymagającym rynku motoryzacyjnym działamy już przeszło 19 lat dostarczając naszym klientom produkty najwyższej jakości.</p>\n            <p><b>Sprawdzeni partnerzy logistyczni</b> - Aby zakupiony towar znalazł się szybko i bezpiecznie w miejscu docelowym korzystamy z usług sprawdzonych przewoźników, a wszystkie nasze przesyłki są ubezpieczone do kwoty 15 000 zł.</p>\n            <p><b>Najlepsze warunki przechowywania</b> - Poświęcamy bardzo dużo uwagi, aby w naszych magazynach zapewnić optymalne warunki składowania opon. Magazyn posiada wentylację i stale kontrolowaną temperaturę w zakresie od 15 do 25 stopni Celsjusza. Chroni opony przed nadmiernym narażeniem na światło słoneczne i promieniowanie UV, a opony są przechowywane w taki sposób, aby żaden inny obiekt nie wywierał na nie nacisku.</p>\n            <p><b>Pełna automatyzacja</b> - Pełna automatyzacja magazynów pozwala nam wysyłać do 10 000 opon dziennie. Ponadto dzięki systemowi zarządzania magazynem jesteśmy w stanie efektywnie i szybko realizować zamówienia unikając nawet najdrobniejszych pomyłek.</p>\n        "}]}]},"compatibilityList":null,"tecdocSpecification":null,"images":[{"url":"https://a.allegroimg.com/original/11a50c/7621d5c642b0b2ff0280b7c86d31"},{"url":"https://a.allegroimg.com/original/11fef5/55675c504d788d8c2645fd5c52c0"},{"url":"https://a.allegroimg.com/original/11214f/d2ea2efa4b37b30739a2b23bd740"},{"url":"https://a.allegroimg.com/original/114e60/eb8a08574980ad75edb0052b98bf"},{"url":"https://a.allegroimg.com/original/111152/39b8f30c430396aaa06fd292aff8"},{"url":"https://a.allegroimg.com/original/11fb2b/65dae276446c93128e1cbb92e392"},{"url":"https://a.allegroimg.com/original/11bc2e/a0b544414580a2b6fac439d8641f"},{"url":"https://a.allegroimg.com/original/113992/09dc0ed24c0aaa420997910708b9"},{"url":"https://a.allegroimg.com/original/11be33/54ded3014108a8b761e9689442ed"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"242","currency":"PLN"},"startingPrice":null,"minimalPrice":null,"netPrice":{"amount":"196.75","currency":"PLN"}},"tax":{"percentage":"23.00","rate":"23.00","subject":null,"exemption":null,"id":"b763d782-572a-47db-8752-8b2cb32b3d0a"},"stock":{"available":100,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":null,"endingAt":null,"endedBy":null,"republish":false},"delivery":{"shippingRates":{"id":"4dcb35e8-e68b-451b-a07e-f0b566f353d5"},"handlingTime":"PT48H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"discounts":null,"afterSalesServices":{"impliedWarranty":{"id":"8a26c0ec-65f1-4b07-ad1e-f6dfb3866e84"},"returnPolicy":{"id":"7e38f433-b8e2-46af-bfb7-ff4276ce1fdb"},"warranty":{"id":"694fab50-d4ba-4f54-9b30-8c389bcc3a41"}},"additionalServices":null,"sizeTable":null,"fundraisingCampaign":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"KUJAWSKO_POMORSKIE","city":"Bydgoszcz","postCode":"85-766"},"external":{"id":"73346"},"attachments":[],"contact":null,"validation":{"errors":[],"warnings":[{"code":"VALIDATION_WARNING","message":"Remove the dispatch date, delivery options, and payment data from the offer description. You can include all this information in the Delivery and Payment tab. Listing an offer that violates the Allegro Terms & Conditions may result in its removal and even a suspension of your account.","details":"","path":"description.id","userMessage":"Remove the dispatch date, delivery options, and payment data from the offer description. You can include all this information in the Delivery and Payment tab. Listing an offer that violates the Allegro Terms & Conditions may result in its removal and even a suspension of your account."}],"validatedAt":"2022-02-04T13:45:08.900Z"},"b2b":{"buyableOnlyByBusiness":false},"createdAt":"2022-02-04T13:45:09.000Z","updatedAt":"2022-02-04T13:45:09.191Z"}

**Comment by lukiopmoto** [comment]
Czytam u was na stronie: "gdy podasz EAN, a my go rozpoznamy - przypiszemy produkt do twojej oferty."

Ja podaje EANy do każdej oferty i zawsze to działało bez żadnego problemu, a teraz na czystym koncie każda dodana oferta nie ma powiązania z oferta allegro. Mimo iż posiada wszystkie niezbędne parametry. O co chodzi?

**Comment by MartaNowaczyk** [comment]
Do wystawienia oferty powiązanej z produktem powinieneś użyć [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers). W tym [poradniku](https://developer.allegro.pl/product_offers/) opisujemy jak wystawić ofertę z produktem. Jeśli wcześniej wystawiałeś już te oferty i dla danego kodu EAN jest produkt w naszej bazie, powinieneś przekazać kod EAN w części produktowej jako product.id. Pole **product.id** służy właśnie do wiązania oferty z produktem. Przykładowy request znajdziesz w pierwszym przykładzie naszego [poradnika](https://developer.allegro.pl/product_offers/#integracja-z-asynchronicznym-api) po kliknięciu w "Kliknij, żeby zobaczyć przykładowy request:" 

Poza tym produkty, wraz z ich id wyszukasz za pomocą [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts). Szczegóły danego produktu pobierz za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).
