### ISSUE TITLE
szczegóły zamówienia i rodzaj płatności

### ISSUE THREAD

**Issue by meddd** [allegro/allegro-api#5406]
witam
w jakiej sytuacji odpowiedz dotycząca szczegółów zamówienia i płatności (https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET)

zwróci
type = "ONLINE"
provider = NULL

czyli jaki musi być rodzaj płatności aby otrzymać typ płatności ONLINE bez dodatkowej wartości odnosnie provider.

**Comment by AureliuszBrussy** [comment]
Weryfikuję to. Niebawem wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@meddd w przypadku płatności o type `ONLINE` - dla każdej metody płatności zawsze powinniśmy zwrócić wartość `P24` lub `PAYU`.
