### ISSUE TITLE
Selected category is inaccessible.

### ISSUE THREAD

**Issue by mindc** [allegro/allegro-api#5407]
Co oznacza ten błąd, podczas wystawiania oferty? Kategoria istnieje, można przeglądać w niej produkty.

**Comment by AureliuszBrussy** [comment]
Czy możesz wskazać o jaką kategorię chodzi, lub wskazać trace-id próby wystawienia kończącej się tym błędem? Zweryfikuję to.

**Comment by mindc** [comment]
trace-id: a197fae599a1a29f
kategoria 260300

W teorii, artykuł nie powinien być wystawiony w tej kategorii (ja to wiem, ale klient już nie), podaję EAN w parametrach, 
**nie podajemy ID produktu**.

Zastanawiam się czy przypadkiem jest niejawnie "spinany" ean z produktem, a ponieważ produkt jest w innej kategorii niż wybrana podczas wystawiania, pojawia się w/w błąd.

Ale to tylko moje gdybanie, proszę o rozwianie wątpliwości.

**Comment by AureliuszBrussy** [comment]
Kategoria o ID 260300 została usunięta z powodu [łączenia kategorii po stronie sprzedawcy](https://developer.allegro.pl/news/#categories-merging-january). Zwróciliśmy tę informację w naszym dzienniku zdarzeń kategorii [GET /sale/category-events](https://developer.allegro.pl/en/documentation/#operation/getCategoryEventsUsingGET_1):

```
{
            "id": "1642753321516570766",
            "occurredAt": "2022-01-21T08:22:01.516Z",
            "type": "CATEGORY_DELETED",
            "category": {
                "id": "260300",
                "name": "Baseny",
                "parent": {
                    "id": "86275"
                },
                "leaf": true
            },
            "redirectCategory": {
                "id": "49846"
            }
        }
```
Użyj kategorii z pola `redirectCategory`.

Jeśli zaktualizujesz drzewo kategorii, kategoria `260300` nie zostanie już zwrócona w odpowiedzi na `GET /sale/categories?parent.id=86275`. Rozumiem, że wątpliwość może jednak wzbudzać odpowiedź ze statusem 200 dla wywołania `GET /sale/categories/260300`. Uspójnimy to - nie będziemy już zwracać usuniętych kategorii z drzewa asortymentowego  dla `GET /sale/categories/{categoryId}`.

**Comment by mindc** [comment]
Zmyliło mnie, że normalnie jest dostęp do tej kategorii od frontu, nie ma tutaj przekierowania
https://allegro.pl/kategoria/baseny-i-zabawki-do-wody-baseny-260300

Ale tak jak piszesz - od strony sprzedającego wygląda to inaczej.

Dzięki za wyjaśnienie.
