### ISSUE TITLE
Usługa niedostępna u tego przewoźnika Inpost

### ISSUE THREAD

**Issue by markip19** [allegro/allegro-api#5408]
Dostaję tę komunikat: "Usługa niedostępna u tego przewoźnika" przy generowaniu wysyłki do paczkomatu. Wysyłka dodaje się z ręki bez problemu.  
uid:695ea120-368f-4ec0-9f85-8ae7216201a9

**Comment by AureliuszBrussy** [comment]
Zgłosiłem to do zespołu odpowiedzialnego za zasób. Wrócę z odpowiedzią po sprawdzeniu.

**Comment by AureliuszBrussy** [comment]
Podany w requeście `serviceId` jest niepoprawny -  należy do Kurier InPost. Firma kurierska za pomocą tej usługi nie dostarcza przesyłek do Paczkomatów. Skorzystaj z [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices) aby pobrać id odpowiedniej usługi.
