### ISSUE TITLE
Aktywacja konta sandbox

### ISSUE THREAD

**Issue by abecikxp** [allegro/allegro-api#541]
Proszę o aktywację kont: 

TymczasoweKontoAllegro2@outlook.com
TymczasoweKontoAllegro@outlook.com
StreamsoftPCB

**Comment by LukaszKorek** [comment]
Konta aktywowałem. Pozdrawiam

**Comment by abecikxp** [comment]
Pierwsze 2 konta są aktywowane, niestety konto StreamsoftPCB pod adresem handel@streamsoft.pl nadal nie jest aktywne.

**Comment by LukaszKorek** [comment]
Powinno już być ok.
