### ISSUE TITLE
Problem z przekroczoną ilością szkiców.

### ISSUE THREAD

**Issue by gufio** [allegro/allegro-api#5411]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,
Mam problem z utworzeniem draftu oferty na środowisku produkcyjnym. API zwraca error: "You cannot create new drafts - your account has exceeded the maximum number 20000 of drafts". Aktualnie na koncie jest dużo mniej szkiców niż wyznaczony limit. Problem pojawił się 4.02 i dzisiaj jest to samo. Niestety nie mam trace-id requestów, jedynie "userId".

"userId":"85126889"

**Comment by AureliuszBrussy** [comment]
Przepraszam za niedogodność - problem nie powinien już występować.

**Comment by bseHlpDsk** [comment]
Dzień dobry, 
prawdopodobnie ten sam błąd spowodował, że w efekcie metody
https://api.{environment}/sale/product-offers
powstawały drafty a nie oferty i obecnie mam na koncie 20 tys. draftów, do których nie ma ID's i których nie mogę usunąć, gdyż 
 API (jak też panel Allegro) nie wspiera pobrania szkiców do pliku, grupowego usuwania szkiców, ani listowania draftów w API. 

Mój userid: 102396271

**Comment by AureliuszBrussy** [comment]
@bseHlpDsk ten przypadek jest inny - faktycznie na tym koncie masz utworzone 20000 draftów. W API możesz pobrać same drafty jeśli skorzystasz z filtra: [GET /sale/offers?publication.status=INACTIVE](https://developer.allegro.pl/my_offers/#filtry). Następnie możesz samodzielnie je usunąć jeśli skorzystasz z [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/deleteOfferUsingDELETE).

**Comment by AureliuszBrussy** [comment]
@dawidikraina poprawiliśmy to - problem nie powinien już występować.

**Comment by jakub-kanski** [comment]
Dzień dobry, mam dokładnie taki sam problem, a na koncie mam 1300 szkiców. User ID: 49453581.

**Comment by AureliuszBrussy** [comment]
@jakub-kanski problem nie powinien już wystąpić na wskazanym koncie.

**Comment by dawidikraina** [comment]
Dzień dobry, mam ten sam problem. W koncie ok. 5800 szkiców. User ID: 11127442

**Comment by AureliuszBrussy** [comment]
@dawidikraina problem nie powinien już wystąpić na wskazanym koncie.

**Comment by jakub-kanski** [comment]
Dzień dobry, ponownie mam dokładnie taki sam problem. Tym razem na koncie mam 1468 szkiców. User ID: 79850626.

**Comment by AureliuszBrussy** [comment]
@jakub-kanski uspójniliśmy to na wskazanym koncie.

**Comment by dawidikraina** [comment]
Dzień dobry, mam ten sam problem. W koncie ok. 4800 szkiców. User ID: 11127442

**Comment by AureliuszBrussy** [comment]
@dawidikraina uspójniliśmy to na wskazanym koncie.

**Comment by jakub-kanski** [comment]
Dzień dobry, ponownie mam dokładnie taki sam problem. Tym razem na koncie mam 2680szkiców. User ID: 49453581.

**Comment by AureliuszBrussy** [comment]
@jakub-kanski uspójniliśmy to na tym koncie.
