### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by snajper1677** [allegro/allegro-api#5412]
Witam
Konto ergold_sandbox
Miałem już zweryfikowane i wystawiałem oferte a nagle każe mi ponownie "zrobić przelew" jednak ta opcja nie działa
Proszę o aktywację konta

**Comment by AureliuszBrussy** [comment]
Twoje konto na Sandboxie jest zablokowane ze względu na zaległość. Skorzystaj z zakładki [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) i przejdź przez symulator płatności. Skorzystaj z opcji Szybka wpłata. Konto zostanie odblokowane. Symulator działa prawidłowo - przed chwilą to zweryfikowałem.

**Comment by sebus9312** [comment]
Dzień dobry,
login TopAGDShop, mamy problem z aktywacją sprzedaży - nie można wysłać przelewu potwierdzającego n kwotę 1zł, nie pozwala na wybór metody płatności. Proszę o pomoc, dziękuję.

**Comment by AureliuszBrussy** [comment]
@sebus9312 czy chodzi o symulację przelewu wykonywanego z poziomu [tej zakładki](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty-eea)? Jaki konkretnie błąd występuje? Czy możesz załączyć zrzut ekranu?

**Comment by sebus9312** [comment]
> @sebus9312 czy chodzi o symulację przelewu wykonywanego z poziomu [tej zakładki](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty-eea)? Jaki konkretnie błąd występuje? Czy możesz załączyć zrzut ekranu?

Dzień dobry, tak, pojawiało się info, że coś poszło nie tak. Udało nam się przejść przez symulator płatności, konto bankowe czeka od kilku dni na potwierdzenie.

**Comment by AureliuszBrussy** [comment]
@sebus9312 aktywowałem Twoje konto. Aktualnie wystawienie oferty powinno być możliwe.
