### ISSUE TITLE
Czy jest możliwe uzupełnianie błędnych pól drafta PATCH'em?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5414]
Witam,
Ładnych kilka godzin grzebałem w kodzie szukając co może powodować, że cokolwiek prześlę PATCH'em dostaję ten sam błąd validacji.
Wreszcie wrzuciłem pytanie w wujka google i ktoś pisał, że trzeba to robić PUT'em.
Chciałem się tylko upewnić czy słusznie czytam. 
Byłoby fajnie móc to zrobić PATCH'em, nie chce mi się przygotowywać wszystkiego specjalnie pod PUT'a

Oto co posyłam:
(Ogonki, psuje mi źle kodowany wynikowy edytor)

curl_exec(https://allegroapi.io/sale/product-offers/11778881961
Array
(
    [0] => Content-Type: application/vnd.allegro.beta.v2+json
    [1] => Accept: application/vnd.allegro.beta.v2+json
)
PATCH {"11323":{"values":[],"valuesIds":["11323_1"]},"224017":{"values":["5900090000001"],"valuesIds":[]},"248922":{"values":["Mazoretka.pl"],"valuesIds":["248922_965457"]},"237206":{"values":["Owijka na paÅkÄ"],"valuesIds":[]},"237978":{"values":["Owijka na paÅkÄ"],"valuesIds":["237978_411982"]},"225693":{"values":"5900091479004","valuesIds":[]},"sellingMode":{"format":"BUY_NOW","price":{"amount":"8","currency":"PLN"}},"name":"Owijka na paÅeczkÄ - czarna","description":{"sections":[{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/images/mazban33.jpg"}]},{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/imgs/a50d6db84a12b5e7900e1ffacabd"},{"type":"TEXT","content":"<h1>Owijka na paÅeczkÄ - Czarna</h1><ul><li><b>Rozmiar: 120 cm.</b></li></ul><p>Specjalna owijka dla maÅŒoretkowych i twirlingowych paÅeczek. Poprawia przyczepnoÅÄ, paÅeczka nie wyÅlizguje siÄ, jest Åatwiejsza do zauwaÅŒenia w wyrzucie, a takÅŒe wchÅania pot.</p>"}]},{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/imgs/45d32689402ca73e715980dc80d9"}]}]},"images":["https://mazoretka.pl/images/omotavka cerna0.jpg","https://mazoretka.pl/imgs/a50d6db84a12b5e7900e1ffacabd","https://mazoretka.pl/imgs/45d32689402ca73e715980dc80d9","https://mazoretka.pl/images/mazban33.jpg"],"delivery":{"shippingRates":{"id":"e1dd8b37-ad08-477a-9d4b-68b4da96d18f"},"handlingTime":"PT72H"},"location":{"countryCode":"CZ","province":"","city":"Praha","postCode":"170 00"},"payments":{"invoice":"VAT"},"tax":{"percentage":"23.00"},"afterSalesServices":{"impliedWarranty":{"id":"d301fa6e-a920-4c13-a663-b1abfc5f7c92"},"returnPolicy":{"id":"b1d19f0b-9cdb-4c47-b97b-0a8c462fecfe"}},"stock":{"available":"84","unit":"UNIT"}}):

Wynik:
{"id":"11778881961","name":"Owijka na paÅeczkÄ - czarna","product":{"id":null,"publication":{"status":"NOT_LISTED"}},"afterSalesServices":{"impliedWarranty":{"id":"d301fa6e-a920-4c13-a663-b1abfc5f7c92"},"returnPolicy":{"id":"b1d19f0b-9cdb-4c47-b97b-0a8c462fecfe"},"warranty":null},"payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":8,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":84,"unit":"UNIT"},"location":{"countryCode":"CZ","province":null,"city":"Praha","postCode":"170 00"},"delivery":{"shippingRates":{"id":"e1dd8b37-ad08-477a-9d4b-68b4da96d18f"},"handlingTime":"PT72H","additionalInfo":null},"publication":{"duration":null,"status":"INACTIVE","endedBy":null,"endingAt":null,"startingAt":null},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/114d63/6e0b49484a4aac60f34eb00a00c6"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1188df/90137a8b4a5bbef6e84798383f4b"},{"type":"TEXT","content":"<h1>Owijka na paÅeczkÄ - Czarna</h1><ul><li><b>Rozmiar: 120 cm.</b></li></ul><p>Specjalna owijka dla maÅŒoretkowych i twirlingowych paÅeczek. Poprawia przyczepnoÅÄ, paÅeczka nie wyÅlizguje siÄ, jest Åatwiejsza do zauwaÅŒenia w wyrzucie, a takÅŒe wchÅania pot.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11178b/e3cff83d436689d532563daaece3"}]}]},
"validation":{"errors":[{"code":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","message":"You can only assign dictionary parameter by valueId for 237978.","details":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","path":"parameters[2]","userMessage":"Parametr sÅownikowy naleÅŒy uzupeÅniÄ poprzez identyfikator wartoÅci dla 237978."},{"code":"ConstraintViolationException.MissingRequiredParameters","message":"Missing required parameters: 11323, 237206","details":"ConstraintViolationException.MissingRequiredParameters","path":"parameters","userMessage":"UzupeÅnij parametry obowiÄzkowe: Stan, Model."},{"code":"ConstraintViolationException.NoValueInDictionaryParameter","message":"No value was given for parameter (237978)","details":"ConstraintViolationException.NoValueInDictionaryParameter","path":"parameters","userMessage":"Nie podano wartoÅci dla parametru Rodzaj (237978)."}],"warnings":[],"validatedAt":"2022-02-07T19:08:10.401Z"},"createdAt":"2022-02-02T12:59:28.000Z","updatedAt":"2022-02-07T19:08:10.401Z","images":["https://a.allegroimg.com/original/11c624/8b3644eb4454a70d9506c5b3fcee","https://a.allegroimg.com/original/1188df/90137a8b4a5bbef6e84798383f4b","https://a.allegroimg.com/original/11178b/e3cff83d436689d532563daaece3","https://a.allegroimg.com/original/114d63/6e0b49484a4aac60f34eb00a00c6"],"external":{"id":"1479"},"category":{"id":"16027"},"tax":{"percentage":"23.00","rate":"23.00","subject":null,"exemption":null,"id":"b763d782-572a-47db-8752-8b2cb32b3d0a"},"sizeTable":null,"discounts":{"wholesalePriceList":null}}

I próba aktywowania oferty:
curl_exec(https://allegroapi.io/sale/offer-publication-commands/8a39e2d3-a745-3580-9914-423a74299c54
Array
(
    [0] => Content-Type: application/vnd.allegro.public.v1+json
    [1] => Accept: application/vnd.allegro.public.v1+json
)
PUT{"publication":{"action":"ACTIVATE"},"offerCriteria":[{
            "offers":[{"id":"11778881961"}],
            "type": "CONTAINS_OFFERS"}]}):{"id":"8a39e2d3-a745-3580-9914-423a74299c54","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by PrzemyslawLukanowski** [comment]
Tak, możesz to zrobić - w odróżnieniu od PUTa przy użyciu PATCHA nie musisz przekazywać całego modelu oferty, a jedynie te sekcje, które chcesz modyfikować. Musisz jednak pamiętać, aby przekazać całą strukturę pola, którą edytujesz - w przesłanym przez Ciebie JSONie nie wskazujesz sekcji "parameters" i nie przekazujesz wartości ID parametru, np. zamiast:

```
{
	"11323": {
	  "values": [],
	  "valuesIds": ["11323_1"]
	}, ...
```

powienieneś przekazać:

```
{
        "id": "11323",
	"values": [], 
        "valuesIds": ["11323_1"], ...
}
```

stąd błędy, które zwróciliśmy w odpowiedzi w sekcji `validation`, jak i nieudana próba aktywacji. Szczegółowy status aktywacji sprawdzisz za pomocą `GET /sale/offer-publication-commands/8a39e2d3-a745-3580-9914-423a74299c54`, zobaczysz tam te same błędy, co ze wspomnanej wyżej sekcji:

```
{
    "tasks": [
        {
            "offer": {
                "id": "11778881961"
            },
            "message": "Could not change offer publication status. Uzupełnij parametry obowiązkowe: Stan, Model. Nie podano wartości dla parametru Rodzaj (237978).",
            "status": "FAIL",
            "scheduledAt": "2022-02-07T19:31:07.659Z",
            "finishedAt": "2022-02-07T19:31:07.658Z",
            "field": "publication",
            "errors": [
                {
                    "code": "ConstraintViolationException.MissingRequiredParameters",
                    "message": "Missing required parameters: 11323, 237206",
                    "details": null,
                    "path": "parameters",
                    "userMessage": "Uzupełnij parametry obowiązkowe: Stan, Model."
                },
                {
                    "code": "ConstraintViolationException.NoValueInDictionaryParameter",
                    "message": "No value was given for parameter (237978)",
                    "details": null,
                    "path": "parameters",
                    "userMessage": "Nie podano wartości dla parametru Rodzaj (237978)."
                }
            ]
        }
    ]
}

```
Chciałbym również wskazać, że prawidłowy, udokumentowany adres do wywoływania metod REST API, to https://api.allegro.pl/.

**Comment by Witold1983** [comment]
O super, bardzo dziękuję za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
mała poprawka z mojej strony - szczegółowy status aktywacji sprawdzisz za pomocą GET /sale/offer-publication-commands/8a39e2d3-a745-3580-9914-423a74299c54/tasks.
