### ISSUE TITLE
Too many requests przy pobraniu tokena

### ISSUE THREAD

**Issue by AnimalDEV** [allegro/allegro-api#5415]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie pobrania tokena z Allegro dostaję w zwrotce `Too many requests`. Raczej aplikacja nie wyczerpuje puli requestów, bo wszystko inne na istniejących tokenach działa bez problemu. Klienci zgłaszają nam problemy od wczoraj.
Trace-id: 56eaf0092feaa53f

**Comment by AureliuszBrussy** [comment]
@AnimalDEV czy mógłbyś wskazać jeszcze jeden trace-id (możliwie świeży) oraz Client ID? Weryfikujemy to.

**Comment by AnimalDEV** [comment]
Trace-id: c9db1470fbe3ba71
Client_id: 8d11edbd5a81438baffc8193b70404d8

**Comment by AureliuszBrussy** [comment]
@AnimalDEV sprawdziliśmy to - przekraczas limit requestów. Zweryfikuj proszę działanie aplikacji i charakterystykę generowanego ruchu.

**Comment by AnimalDEV** [comment]
@AureliuszBrussy Najdziwniejsze jest to, że cała aplikacja działa i nie ma problemów z limitami. W logach nie ma błędów o przekroczeniu limitów. Klienci nie zgłaszają żadnych problemów tylko to występuje przy generowaniu tokena. Może dałoby się to jakoś dokładniej sprawdzić po waszej stronie?

**Comment by AureliuszBrussy** [comment]
@AnimalDEV spod IP którego dotyczy error 429 widzimy ruch tylko na zasób do generowania tokenów, więc faktycznie innych requestów to nie dotyka.
