### ISSUE TITLE
Jak podawać do drafta PATCH'em parametry produktowe?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5416]
Witam serdecznie,
Pytanie jak w temacie.
Chciałbym z pominięciem product-proposal uzupełnić brakujące parametry produktowe w drafcie.
Zauważyłęm, że można je przesyłać POST'em w trakcie dodawania nowego drafta, 
ale już PATCH'em parametrów produktowych drafta uzupełnić mi się nie udaje.

productSet=>parameters słabo jest to opisane w dokumentacji, głownie jako response ale nie jako request.
Stąd moje pytanie:

Kiedy posyłam to:
curl_exec(https://allegroapi.io/sale/product-offers/11778881961Array
(
    [0] => Content-Type: application/vnd.allegro.beta.v2+json
    [1] => Accept: application/vnd.allegro.beta.v2+json
)
PATCH{"parameters":[{"id":11323,"values":[],"valuesIds":["11323_1"]}],"productSet":[{"parameters":[{"id":224017,"values":["5900090000001"]},{"id":248922,"values":["Mazoretka.pl"],"valuesIds":["248922_965457"]},{"id":237206,"values":["Owijka na paÅkÄ"]},{"id":237978,"values":["Owijka na paÅkÄ"],"valuesIds":["237978_411982"]},{"id":225693,"values":["5900091479004"]}]}],"name":"Owijka na paÅeczkÄ - czarna","description":{"sections":[{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/images/mazban33.jpg"}]},{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/imgs/a50d6db84a12b5e7900e1ffacabd"},{"type":"TEXT","content":"<h1>Owijka na paÅeczkÄ - Czarna</h1><ul><li><b>Rozmiar: 120 cm.</b></li></ul><p>Specjalna owijka dla maÅŒoretkowych i twirlingowych paÅeczek. Poprawia przyczepnoÅÄ, paÅeczka nie wyÅlizguje siÄ, jest Åatwiejsza do zauwaÅŒenia w wyrzucie, a takÅŒe wchÅania pot.</p>"}]},{"items":[{"type":"IMAGE","url":"https://mazoretka.pl/imgs/45d32689402ca73e715980dc80d9"}]}]},"images":["https://mazoretka.pl/images/omotavka cerna0.jpg","https://mazoretka.pl/imgs/a50d6db84a12b5e7900e1ffacabd","https://mazoretka.pl/imgs/45d32689402ca73e715980dc80d9","https://mazoretka.pl/images/mazban33.jpg"],"delivery":{"shippingRates":{"id":"e1dd8b37-ad08-477a-9d4b-68b4da96d18f"},"handlingTime":"PT72H"},"location":{"countryCode":"CZ","province":"","city":"Praha","postCode":"170 00"},"payments":{"invoice":"VAT"},"tax":{"percentage":"23.00"},"afterSalesServices":{"impliedWarranty":{"id":"d301fa6e-a920-4c13-a663-b1abfc5f7c92"},"returnPolicy":{"id":"b1d19f0b-9cdb-4c47-b97b-0a8c462fecfe"}},"stock":{"available":"84","unit":"UNIT"}})

Otrzymuję: 
sale/offer-publication-commands/0599fab8-fffd-3859-9768-1d41a2d8627b/tasks

**Comment by PrzemyslawLukanowski** [comment]
W dokumentacji taką przykładową strukturę znajdziesz po prawej stronie, w przykładowym requeście - wystarczy, że wyciągniesz z niej tylko interesującą Cię sekcję, czyli w przypadku tylko parametrów produtkowych będzie to, np:

```
{
      "productSet": [
        {
            "product": {
                "parameters": [
                    {
                        "id": "225693",
                        "name": "EAN",
                        "values": [
                            "40078754934"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ]
}
```


Poniżej znajdziesz natomiast przykładową strukturę z podziałem na parametry i produktowe. To, czy parametr jest produktowy czy ofertowy, sprawdzisz za pomocą [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/product_offers/#parametry-ofertowe) w polu `options.describesProduct`:

```
{
      "productSet": [
        {
            "product": {
                "parameters": [
                    {
                        "id": "225693",
                        "name": "EAN",
                        "values": [
                            "40078754934"
                        ],
                        "valuesIds": null,
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 1
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Condition",
            "valuesIds": [
                "11323_2"
            ],
            "rangeValue": null
        }
    ]
}
```


Tę przykładową strukturę, z podziałem na dwa rodzaje parametrów (ale również z pozostałymi polami) możesz sobie pobrać za pomocą [GET /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation/#operation/getProductOffer). Pamiętaj, aby we wszystkich wywołaniach korzystać z nagłówków application/vnd.allegro.public.v1+json - [wersje beta dla tych zasobów wyłączamy z końcem lutego](https://developer.allegro.pl/news/#product-offers-public).

**Comment by Witold1983** [comment]
Bardzo dziękuję za pomoc.
Okazało się, że nie działało właśnie z powodu złego nagłówka. W życiu bym na to nie wpadł.
Pozdrawiam :+1:
