### ISSUE TITLE
Zwraca 403, python requests auth, sandbox, gdzie użyć scope?

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#5417]
Testowo próbowałem pobrać /sale/offers, ale request zwraca 403. Json zwraca m. in.: 'Access denied. Contact the author of the application.' dla 'userMessage'.

Działam zgodnie z tutorialem.
Używam pythonowego requests. Token otrzymuję bez problemu. Problem jest przy tworzeniu zapytania.
Być może chodzi o scope? Tylko gdzie go dodać?

Autoryzacja i zdobywanie tokena:
`api_client_id = '140c6f77c4cb4b41a51b207161892c98'`
`api_client_secret = 'xxxxxxxxx' # w rzeczywistości używam tego realnego :)`
`token_url = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"`
`api_url = "https://api.allegro.pl.allegrosandbox.pl/"`

`data = {`
    `'grant_type': 'client_credentials',`
`}`
`access_token_response = requests.post(token_url, data=data, verify=False, allow_redirects=False, auth=(api_client_id, api_client_secret)`
`tokens = json.loads(access_token_response.text)`
`access_token = tokens['access_token']`
`print(access_token)`
`headers = {'Authorization': 'Bearer ' + access_token , 'Accept': "application/vnd.allegro.public.v1+json"}`
`url = 'sale/offers'`
`req = requests.get(api_url + url, headers=headers, verify=False)`

req zwraca kod 403

Dla:
`url = 'sale/categories'`
jest ok.

Pewnie powinienem dodać scope `(allegro:api:sale:offers:read)` ale gdzie?

W niektórych postach widziałem coś o weryfikacji aplikacji. Na czym to polega?

**Comment by PrzemyslawLukanowski** [comment]
Szczegóły na temat tego, jak przekazywać scope znajdziesz w [naszym poradniku](https://developer.allegro.pl/auth/#scope-w-api-allegro
), jednak to nie brak odpowiedniego scope jest aktualnie problemem - jeśli nie przekazujesz w żądaniu żadnego scope, to aplikacja ma dostęp do wszystkich zakresów, które wskazałeś na etapie rejestracji aplikacji. W Twoim przypadku problem generuje rodzaj autoryzacji, którym jest client_credentials - ten sposób autoryzacji nie posiada kontekstu użytkownika i za jego pomocą masz dostęp tylko do publicznych danych, dlatego przy pobieraniu kategorii nie zwracamy Tobie błędu. Wyobraź sobie np. że jesteś niezalogowanym użytkownikiem i próbujesz wejść w zakładkę Moje oferty - nie będzie to możliwe, dlatego również w API zwracamy Ci odpowiedź 403. Aby mieć dostęp do takich danych, jak szczegóły oferty, skorzystaj proszę z autoryzacji typu [code](https://developer.allegro.pl/auth/#authorization-code-flow) lub [device](https://developer.allegro.pl/auth/#device-flow). W naszej dokumentacji, przy każdym zasobie, znajdziesz odpowiednie oznaczenia, z jakiego rodzaju autoryzacji powinieneś skorzystać:
 - bearer-token-for-application - wystarczy autoryzacja typu client_credentials,
 - bearer-token-for-user- musisz użyć tokena wygenerowanego w ramach autoryzacji code lub device

Wspomniałeś jeszcze o weryfikacji aplikacji - jest to osobny proces, wymagany wyłącznie do dostępu do zasobu [/offers/listing](https://developer.allegro.pl/listing/). Więcej szczegółow znajdziesz w [naszym newsie.](https://developer.allegro.pl/news/#public-offers-restrictions)

**Comment by PrzemyslawLukanowski** [comment]
Przykłady dla wymienionych wyżej typów autoryzacji w Pythonie również znajdziesz w linkowanym przeze mnie poradniku.

**Comment by uranity** [comment]
Dziękuję za odpowiedź.
Te sale offer to testowo chciałem pobrać, ale docelowo pracuję nad autoresponderem, więc z `messages`.
Czy w tym celu również powinienem się autoryzować poprzez code?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, zasoby związane z Centrum Wiadomości wymagają autoryzacji typu bearer-token-for-user (czyli code lub device) oraz ustawienia odpowiedniego scope dla aplikacji:

![aaaaaaaa](https://user-images.githubusercontent.com/51473661/153201357-1f513550-f272-4428-a597-5da906288571.png)

**Comment by uranity** [comment]
Zacząłem więc używać metody autoryzacji device (ponieważ wszystko ma się dziać w backendzie).
Korzystam z tego przykładu z "Przykładowy kod realizujący autoryzację typu Device Flow" (python).
Działam zgodnie z tutorialem i napotkałem następującą przeszkodę:

`code = get_code()` # funkcja powinna zwrócić odpowiedź (response) z zapytania (`requests.post(...)`)
`code.text` zwraca:
`'<html><head><title>allegrosandbox.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMATtA7y_L50CMATgmQMg==\',\'hsh\':\'77DC0FFBAA0B77570F6B414F8E5BDB\',\'t\':\'bv\',\'r\':\'b\',\'s\':29697,\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n'`
.. a powinien jsona.
Podobnie 


request z linijki 15 (w funkcji `get_code()`) zwraca 403 wciąż:
`api_call_response = requests.post(CODE_URL, auth=(CLIENT_ID, CLIENT_SECRET), headers=headers, data=payload, verify=False)`

Gdzie tkwi zatem problem?

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziliśmy przykładowy kod na naszej stronie i prawidłowo udało nam się wygenerować JSON. Sprawdź proszę, czy na pewno przekazujesz prawidłowe adresy w CODE_URL i TOKEN_URL. Zwróć też uwagę, czy aplikacja, którą zarejestrowałes jest typu DEVICE, a nie WEB. Jeśli nadal będziesz otrzymywać błędy, prześlij nam swój cały kod za pośrednictwem [formularza](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433) - dopisz wtedy, że dane dotyczą zgłoszenia #5417 na GitHub.

**Comment by uranity** [comment]
@PrzemyslawLukanowski,
Zmieniłem koncepcję jednak. Jednak będzie autoryzacja code flow, gdzie użytkownik będzie tworzył autoryzację przez zalogowanie na swoje konto na allegro (przez przeglądarkę).
Wykonałem testowy kod z dokumentacji. Gdy wkleiłem adres url do przeglądarki, otrzymałem:
`{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}`

Adres url:
`https://api.allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=140c6f77c4cb4b41a51b207161892c98&redirect_uri=https://xxx.xx` (oczywiście inny redirect_url)

Na czym polega ta przeszkoda?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku requestów związanych z autoryzacją korzystaj proszę z URL https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize.

**Comment by uranity** [comment]
> W przypadku requestów związanych z autoryzacją korzystaj proszę z URL https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize.

Dziękuję. Zmieniłem. Teraz nie zwraca jsona, tylko strone html, ale niestety jest to:
`"Nie możemy wyświetlić strony Numer błędu: eafb4240d5fd259b"`

**Comment by PrzemyslawLukanowski** [comment]
Występuje rozbieżność między adresem, który przekazujesz w redirect_uri, a tym, który zarejestrowałeś na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/ - te adresy muszą być identyczne.

**Comment by uranity** [comment]
Dziękuję.
Otrzymałem kod w linku redirect_url:
`mój redirect uri?code=zwrocony_kod`
Niestety gdy robię posta do `https://allegro.pl.allegrosandbox.pl/oauth/token` otrzymuję http400 oraz:
`{'error': 'invalid_grant', 'error_description': 'Invalid authorization code: zwrocony_kod'}`

Czy url do autoryzacji tokena jest poprawny?

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy URL to `https://allegro.pl.allegrosandbox.pl/auth/oauth/token`. Upewnij się także, że kod jest prawidłowy i wykorzystujesz go w ciągu 10 sekund momentu, kiedy go wygenerowałeś. Pełen adres powinien wyglądać następująco:
`https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code={code}&redirect_uri={redirect_uri}`
