### ISSUE TITLE
Embedding store with an iframe

### ISSUE THREAD

**Issue by belte42** [allegro/allegro-api#5418]
Hello Allegro team,

We are looking into ways of integrating Allegro with Zyro website builder. The REST API solution currently looks like a very time-consuming project to implement.
I wanted to inquire about other possible solutions to implement into our 3rd party e-commerce platform (Ecwid) or our in-house ZyCommerce solution.
Perhaps there would be a possibility to embed the user stores with an iframe that we could integrate so that users could easily connect/sync their e-commerce websites listings to Allegro?

Looking forward to your reply!

**Comment by PrzemyslawLukanowski** [comment]
Hello, the connection via REST is the only supported connection type for integrators. All of the information can be found on our [Developer Portal](https://developer.allegro.pl/en/about/). If any questions bother you, please let us know.
