### ISSUE TITLE
Wysylam z allegro - Allegro One - Polskie znaki na etykiecie

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#5420]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy zgłaszaniu paczki przez REST API + wysyłam z allegro, rodzaj przesyłki allegro one , przekazujecie do UPS adres punktu odbioru z polskimi znakami i wychodzą krzaki na etykiecie. np. dla punktu Allegro one box, AL093KR1

**Comment by AureliuszBrussy** [comment]
Czy jesteś w stanie wskazać jakiś konkretny przykład przesyłki (np. commandId pod którym została wygenerowana)? Czy możesz jeszcze doprecyzować, jak wygląda ten adres na etykiecie, czy ew. masz taką przykładową etykietę (wyślij proszę np. zrzut ekranu z fragmentu etykiety, gdzie widać problem)?

**Comment by Sebastian-Le** [comment]
UPS po prostu nie obsługuje polskich znaków, tak było od zawsze i wątpię że to kiedyś zmienią. 
ParcelID 68259459

Ocenzurowana etykieta, zielonym strzałkami zaznaczone pola które przekazujecie o punkcie odbioru z polskimi znakami
![allone](https://user-images.githubusercontent.com/82901132/153196151-0b84da88-abbb-4d6a-8306-2a5522249a57.jpg)

**Comment by AureliuszBrussy** [comment]
Poinformowałem o tym zespół odpowiedzialny za usługę. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
@Sebastian-Le potwierdź proszę jeszcze, czy etykietę pobrałeś za pomocą [GET /parcel-management/parcels/label](https://developer.allegro.pl/documentation/#operation/getParcelLabel)? Jeżeli tak - czy jesteś w stanie wskazać trace-id wywołania? Jeżeli nie - to czy ew. możesz przesłać pełen request i response w formie curl przez [formularz kontatkowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)? W formularzu wskaż proszę numer zgłoszenia na GitHubie: #5420.

**Comment by Sebastian-Le** [comment]
Nie przechowuję trace-id , mogę podać jedynie trace-id gdy dokonuję ponownego wydruku wcześniej przygotowanej już paczki. 
W requescie przekazuje z danych punktu odbioru przekazuje jedynie pointId (jego adres dopisujecie po waszej stronie)

Problem najprawdopodobniej został już wyeliminowany, dla etykiety generowanej dzisiaj z innymi danymi, punkt odbioru został pozbawiony już polskich znaków, AL007CT1 TORUN LYSAKOWSKIEGO 8.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za informację.

Dodam tylko, że w przypadku, gdy problem wystąpi ponownie - do dokładnej weryfikacji potrzebne będą wspomniane pliki (dotyczące pobrania etykiety) - request i response w formie curl.

**Comment by awawrowicz** [comment]
Ja mam podobny problem:

/parcel-management/parcels/label?parcelId=99678842

![image](https://user-images.githubusercontent.com/28707773/194570948-f52bfc10-57e8-42be-a327-1414d068071c.png)
