### ISSUE TITLE
Nie znaleziono parametru

### ISSUE THREAD

**Issue by KarolGilFuturiti** [allegro/allegro-api#5421]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry

Przy próbie importu aukcji do Państwa dostaje błędy:

Nie znaleziono parametru P235870C255119
Nie znaleziono parametru P235870C18708
Nie znaleziono parametru P235870C18570
Nie znaleziono parametru P235870C18571

Natomiast parametr P235870 nie jest dostępny do pobrania w ww. kategoriach za pomocą API.

Problem dotyczy np. aukcji https://allegro.pl/oferta/blotnik-do-przyczep-13-14-pcv-domar-mocny-7179893124

**Comment by AureliuszBrussy** [comment]
Identyfikatory parametrów które wskazujesz nie są naszymi wewnętrznymi parametrami, również komunikaty błędów które wymieniłeś nie wyglądają na zwrócone przez nasze API. Nie widzę także próby edycji wskazanej ofety, która w ostatnim czasie zakończyłaby się błędem. Czy możesz wskazać przykładowe trace-id żądania, które zakończyło się błędem? Pozwoli mi to dokładniej to zweryfikować.

**Comment by KarolGilFuturiti** [comment]
Wygląda to tak, że jak się wejdzie na ww. ofertę w Allegro i się ją edytuje i zapisze to wtedy można ją normalnie zaimportować i ww. błąd nie występuje.

**Comment by AureliuszBrussy** [comment]
Jak mniemam, nie jest to problem bezpośrednio dotyczący naszego API, ale aplikacji, z której korzystasz. Najlepiej wyjaśnić to z supportem aplikacji.
