### ISSUE TITLE
Weryfikacja konta firmowego

### ISSUE THREAD

**Issue by sebus9312** [allegro/allegro-api#5422]
Dzień dobry, mamy problem z weryfikacją konta firmowego.
Nie mamy możliwości wyboru formy płatności na etapie przelewu weryfikacyjnego w kwocie 1zł. Jak to zrobić?
Konto: TopAGDShop

**Comment by AureliuszBrussy** [comment]
Temat poruszyłeś w [#5412](https://github.com/allegro/allegro-api/issues/5412#issuecomment-1033733131) - już się odniosłem do Twojej wiadomości. Prosiłbym o odpowiedź w tamtym wątku.
