### ISSUE TITLE
Restrykcyjne limity połączeń w zasobie poświęconym pobieraniu danych konkretnego produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5424]
Witam,

mam dosyć prosty problem - chcę sprawdzić, czy stworzone przeze mnie produkty w katalogu Allegro nadal istnieją. Mam tego trochę, więc chciałbym zapewnić aktualne dane powiązane z przedmiotami, które mam w bazie. Temat wydaje się prosty, jednak ograniczają go spore limity. Po paru/kilku/stu zapytaniach jestem szybko sprowadzany do limitu jednego zapytania na sekundę, co daje ok. 60 zapytań na minutę. 

Zdziwiło mnie to, ponieważ w dokumentacji nie ma wzmianki na ten temat. W istocie poradnik wspomina, że niektóre zasoby mogą mieć dodatkowe ograniczenia, jednakże powinna być informacja przy zasobie, której to brakuje.
https://developer.allegro.pl/documentation/#operation/getSaleProduct

Czy taki lejek faktycznie istnieje, czy ja wpadłem w jakiś filtr, który mnie ogranicza? Z braku danych nie stosowałem żadnych limitów pomiędzy zapytaniami, chociaż dane były pobierane synchronicznie i nawet nie robiłem wielu zapytań jednocześnie.

**Comment by PrzemyslawLukanowski** [comment]
Tak, na tym zasobie funkcjonuje mechanizm Leaky Bucket. Wspominamy o tym w naszym poradniku, w sekcji ["Jak pobrać pełne dane o produkcie"](https://developer.allegro.pl/productization/#2-jak-pobra%c4%87-pe%c5%82ne-dane-o-produkcie).

**Comment by hahyes** [comment]
Brak informacji, jakie konkretnie limity funkcjonują. Chyba, że traktujecie to jako tajemnicę, którą można sprawdzić pierwszą lepszą pętlą napisaną popijając kawę. ;)
https://developer.allegro.pl/about/#ograniczenie-liczby-zapyta%C5%84-limity
Według poradnika, informacje o limitach powinny widnieć w dokumentacji REST API, jednak próżno ich szukać przy odpowiednich zasobach.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zwrócenie uwagi na tę nieścisłość - zaktualizujemy opis zasobów w dokumentacji.  Nie udostępniamy informacji o konkretnych limitach dla Leaky Bucket, ponieważ jest to wartość płynna.

**Comment by hahyes** [comment]
> Nie udostępniamy informacji o konkretnych limitach dla Leaky Bucket, ponieważ jest to wartość płynna.

Rozumiem, w takim razie nie ma sensu o to prosić. Dziękuję na odpowiedź i pozdrawiam.
