### ISSUE TITLE
błąd w module integracji Allegro

### ISSUE THREAD

**Issue by olikacompl** [allegro/allegro-api#5425]
Chcielibyśmy wystawiać produkty z panelu naszego sklepu na allegro. Jednak przy publikowaniu ofert wyskakuje taki błąd.

![allegro](https://user-images.githubusercontent.com/99395132/153380618-e49c9d7e-27da-47f3-a881-e271bb7fce56.png)

[

**Comment by PrzemyslawLukanowski** [comment]
Opis błędu, który otrzymaliście, to "Brakuje jednego z tagów otwierających" i dotyczy opisu oferty. Upewnijcie się, że każdy znacznik HTML jest zarówno otwarty, jak i zamknięty. Czyli każdy fragment tekstu musi być otwarty jakimś znacznikiem, np `<p>` (otwarcie nowego nagłówka), jak i nim zamknięty `</p>`. Błąd, który zwróciliśmy sugeruje, że w Waszym opisie może widnieć np. coś takiego `<p>przykładowy tekst</p>przykładowy tekst</p> `- jak widać, brakuje tutaj drugiego znacznika otwierająceg`o <p>`.
