### ISSUE TITLE
Błąd 'Nieprawidłowe żądanie' podczas pobrania oferty

### ISSUE THREAD

**Issue by propsu** [allegro/allegro-api#5428]
Występuje problem: 
 - [ x ] z zasobem REST API / with a REST API resource
 - [ x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Request:
{"method":"GET","url":"https:\/\/api.allegro.pl\/sale\/offers\/11689229310","path":"\/sale\/offers\/11689229310","headers":{"Host":["api.allegro.pl"],"Authorization":["Bearer MY_TOKEN"],"Accept":["application\/vnd.allegro.public.v1+json"],"Content-Type":["application\/vnd.allegro.public.v1+json"],"Accept-Language":["pl-PL"]},"query":"","body":""}

Response:
{"status":400,"body":"{\"errors\":[{\"code\":\"INVALID_JSON\",\"message\":\"Invalid request.\",\"details\":null,\"path\":null,\"userMessage\":\"Nieprawid\u0142owe \u017c\u0105danie.\"}]}","headers":{"expires":["0"],"cache-control":["no-cache, no-store, max-age=0, must-revalidate"],"x-xss-protection":["1; mode=block"],"pragma":["no-cache"],"x-frame-options":["DENY"],"trace-id":["ac0bdf5eb55541"],"date":["Thu, 10 Feb 2022 14:47:36 GMT"],"x-content-type-options":["nosniff"],"content-type":["application/json"],"transfer-encoding":["chunked"]}}

Trace Id: ac0bdf5eb55541

Podczas pobrania zasobu oferty otrzymuję response 400 z message "Nieprawdłowe żądanie"

**Comment by tomylee0** [comment]
Podłączam się. "Invalid request" u mnie też pojawia się dziś od czasu do czasu. Np. tu: bfda2e35fa9c8359.

**Comment by areklal** [comment]
Podpinam się -  w przypadku pobierania informacji o sprzedanych produktach w przypadku, gdy w zamówieniu jest więcej niż jedna oferta (jedna pozycja - produkt). @Lukasz-Zurek @PrzemyslawLukanowski Czy coś rozgrzebaliście a  API i się wysypało, czy coś się nagle zmieniło w  API (importujemy po 300-400 zam dziennie i dzisiaj do 12stej działało okeej - później zaczęły się problemy.

**Comment by anih** [comment]
zdecydowanie za dużo błędów 
```
{'errors': [{'code': 'INVALID_JSON', 'message': 'Invalid request.', 'details': None, 'path': None, 'userMessage': 'Invalid request.'}]}
```

**Comment by Lukasz-Zurek** [comment]
Problem ten przekazaliśmy już dalej do weryfikacji. 

Przepraszamy za utrudnienia.

@areklal Nie wprowadzaliśmy zmian w tym zakresie. Najprawdopodobniej jest to błąd techniczny.

**Comment by Lukasz-Zurek** [comment]
Problem nie powinien już występować.

Raz jeszcze przepraszam za zaistniałe niedogodności.
