### ISSUE TITLE
Czy jeśli parametr describesProduct == true to znaczy że jest wymagany?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5429]
Witam, po raz pierwszy natknąłem się na taki problem, jestem kompletnie zbity z tropu.
Nie wiem co jest nie tak kiedy wysyłam to:
(https://allegroapi.io/sale/product-offers/11809222060Array
(
    [0] => Content-Type: application/vnd.allegro.public.v1+json
    [1] => Accept: application/vnd.allegro.public.v1+json
)
PATCH{"sellingMode":{"format":"BUY_NOW","price":{"amount":"50","currency":"PLN"}},"parameters":[{"id":"11323","name":"Stan","values":[],"valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"15851","name":"Płeć","values":[],"valuesIds":["15851_1"]},{"id":"226434","name":"Marka","values":["Mazoretka.pl"],"valuesIds":["226434_315782"]},{"id":"2205","name":"Rodzaj","values":[],"valuesIds":["2205_16"]},{"id":"15835","name":"Materiał","values":[],"valuesIds":["15835_256"]},{"id":"206646","name":"Próba złota","values":[],"valuesIds":[]},{"id":"206658","name":"Próba srebra","values":[],"valuesIds":[]},{"id":"2208","name":"Splot","values":[],"valuesIds":["2208_2"]},{"id":"2206","name":"Długość całkowita","values":["50"],"valuesIds":[]},{"id":"129129","name":"Motyw","values":[],"valuesIds":["129129_286445"]},{"id":"206618","name":"Cechy","values":[],"valuesIds":["206618_4"]},{"id":"215926","name":"Kolekcja","values":["Lancuszki"],"valuesIds":[]},{"id":"215922","name":"Nazwa koloru producenta","values":[""],"valuesIds":[]},{"id":"224017","name":"Kod producenta","values":["5900090000001"],"valuesIds":[]},{"id":"225693","name":"EAN","values":["5900091567008"],"valuesIds":[]},{"id":"17448","name":"Waga produktu z opakowaniem jednostkowym","values":["0.01"],"valuesIds":[]}]}}],"name":"Łańcuszek z fgurką ze srebrnymi kamieniami","description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11442d/fc01573f4ee4876707fb7bcddb86"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1191f2/0f213ce742b49f94f5ba2238ec40"},{"type":"TEXT","content":"<h1>Łańcuszek z figurką ze srebrnymi kamieniami</h1><ul><li><b>Rozmiar: 50 cm.</b></li></ul><p>Łańcuszek z wisiorkiem, figurką mażoretki. Figurka jest ozdobiona srebrnymi kamieniami. Długość łańcuszka jest zmienna, można ją regulować na więcej długości, więc nadaje się również do małych lub dużych mażoretek.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11268b/20abfe594d7cb17726d39ca42f3b"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/118e43/e8cb46e049448fa20ca5a0a3126d"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/110700/dedbb4974f34b573d30eb3926699"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11a93e/cf68c4234e90ad3adac2705a269a"}]}]},"images":["https://mazoretka.pl/images/retizek1587.jpg","https://a.allegroimg.com/original/1191f2/0f213ce742b49f94f5ba2238ec40","https://a.allegroimg.com/original/11268b/20abfe594d7cb17726d39ca42f3b","https://a.allegroimg.com/original/118e43/e8cb46e049448fa20ca5a0a3126d","https://a.allegroimg.com/original/110700/dedbb4974f34b573d30eb3926699","https://a.allegroimg.com/original/11a93e/cf68c4234e90ad3adac2705a269a","https://a.allegroimg.com/original/11442d/fc01573f4ee4876707fb7bcddb86"],"delivery":{"shippingRates":{"id":"e1dd8b37-ad08-477a-9d4b-68b4da96d18f"},"handlingTime":"PT72H"},"location":{"countryCode":"CZ","province":"","city":"Praha","postCode":"170 00"},"payments":{"invoice":"VAT"},"tax":{"percentage":"23.00"},"afterSalesServices":{"impliedWarranty":{"id":"d301fa6e-a920-4c13-a663-b1abfc5f7c92"},"returnPolicy":{"id":"b1d19f0b-9cdb-4c47-b97b-0a8c462fecfe"}},"stock":{"available":"84","unit":"UNIT"}})

Wynik:

{"id":"11809222060","name":"Łańcuszek z fgurką ze srebrnymi kamieniami","productSet":[],"parameters":[{"id":"11323","name":"Condition","values":[],"valuesIds":["11323_1"],"rangeValue":null}],"afterSalesServices":{"impliedWarranty":{"id":"d301fa6e-a920-4c13-a663-b1abfc5f7c92"},"returnPolicy":{"id":"b1d19f0b-9cdb-4c47-b97b-0a8c462fecfe"},"warranty":null},"payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":50,"currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":84,"unit":"UNIT"},"location":{"countryCode":"CZ","province":null,"city":"Praha","postCode":"170 00"},"delivery":{"shippingRates":{"id":"e1dd8b37-ad08-477a-9d4b-68b4da96d18f"},"handlingTime":"PT72H","additionalInfo":null,"shipmentDate":null},"publication":{"duration":null,"status":"INACTIVE","endedBy":null,"endingAt":null,"startingAt":null,"republish":false},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11442d/fc01573f4ee4876707fb7bcddb86"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1191f2/0f213ce742b49f94f5ba2238ec40"},{"type":"TEXT","content":"<h1>Łańcuszek z figurką ze srebrnymi kamieniami</h1><ul><li><b>Rozmiar: 50 cm.</b></li></ul><p>Łańcuszek z wisiorkiem, figurką mażoretki. Figurka jest ozdobiona srebrnymi kamieniami. Długość łańcuszka jest zmienna, można ją regulować na więcej długości, więc nadaje się również do małych lub dużych mażoretek.</p>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11268b/20abfe594d7cb17726d39ca42f3b"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/118e43/e8cb46e049448fa20ca5a0a3126d"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/110700/dedbb4974f34b573d30eb3926699"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/11a93e/cf68c4234e90ad3adac2705a269a"}]}]},"validation":{"errors":[{"code":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","message":"You can only assign dictionary parameter by valueId for 206646.","details":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","path":"parameters[6]","userMessage":"Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 206646."},{"code":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","message":"You can only assign dictionary parameter by valueId for 206658.","details":"ConstraintViolationException.ImproperlyAssignedDictionaryParameter","path":"parameters[7]","userMessage":"Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 206658."},{"code":"ConstraintViolationException.ParameterValueValidationFailed","message":"Parameter values were not provided.","details":"ConstraintViolationException.ParameterValueValidationFailed","path":"parameters","userMessage":"Nie podano wartości dla parametru (215922)."}],"warnings":[],"validatedAt":"2022-02-10T21:22:42.781Z"},"createdAt":"2022-02-09T17:00:09.000Z","updatedAt":"2022-02-10T21:22:42.782Z","images":["https://a.allegroimg.com/original/1191f2/0f213ce742b49f94f5ba2238ec40","https://a.allegroimg.com/original/11268b/20abfe594d7cb17726d39ca42f3b","https://a.allegroimg.com/original/118e43/e8cb46e049448fa20ca5a0a3126d","https://a.allegroimg.com/original/110700/dedbb4974f34b573d30eb3926699","https://a.allegroimg.com/original/11a93e/cf68c4234e90ad3adac2705a269a","https://a.allegroimg.com/original/11442d/fc01573f4ee4876707fb7bcddb86"],"external":{"id":"1567"},"category":{"id":"123432"},"tax":{"percentage":"23.00","rate":"23.00","subject":null,"exemption":null,"id":"b763d782-572a-47db-8752-8b2cb32b3d0a"},"sizeTable":null,"discounts":{"wholesalePriceList":null},"contact":null,"fundraisingCampaign":null,"b2b":{"buyableOnlyByBusiness":false},"attachments":[],"additionalServices":null,"compatibilityList":null}

**Comment by PrzemyslawLukanowski** [comment]
Odpowiadając na Twoje pytanie z tytułu - nie oznacza, to że parametr jest wymagany (o tym świadczy pole required == true). To pole wskazuje na to, czy parametr opisuje produkt czy nie, czyli inaczej mówiąc, czy korzystajć z zasobów /sale/product-offers musisz przekazać go w sekcji productSet.product.parameters czy w ogólnej sekcji parameters.
W Twoim przypadku otrzymałeś następujące błędy:

- `"Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 206646."`

ponieważ wskazałeś parametr - jego ID i nazwę, ale nie przekazałeś żadnej wartości w polu valuesId

```
{
  "id": "206646",
  "name": "Próba złota",
  "values": [],
  "valuesIds": []
}
```

- `"Parametr słownikowy należy uzupełnić poprzez identyfikator wartości dla 206658"`

jak wyżej

```
{
  "id": "206658",
  "name": "Próba srebra",
  "values": [],
  "valuesIds": []
 },
```

- `"Nie podano wartości dla parametru (215922)".`

podobnie jak wyżej, ale w tym przypadku nie podałeś wartości w polu values (w odróżnieniu od dwóch powyższych to jest parametr typu string, a nie dictionary):

```
{
  "id": "215922",
  "name": "Nazwa koloru producenta",
  "values": [""],
  "valuesIds": []
 }
```

**Comment by hahyes** [comment]
@Witold1983 Dodam jedynie do wypowiedzi deva, że dla produktów pola obowiązkowe są definiowane również poprzez pole `requiredForProduct`. W tym przypadku korzystasz z zasobu `product-offers`, który tworzy też produkty, jeżeli nie podpinasz już gotowych i istniejących, więc zwróć też na to uwagę. 

![image](https://user-images.githubusercontent.com/37104952/153556666-df66cc81-9c29-4025-89f5-8bcb240876da.png)
