### ISSUE TITLE
GET /sale/offers/{offerId} dla nieistniejącej oferty zwraca błąd INVALID_JSON

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#5430]
- Utworzyłem szkic oferty
- Oferta nie została aktywowana i po odpowiednim czasie została usunięta z Allegro
- Przy próbie wywołania na niej w/w metody, pojawia się mylący komunikat błędu - INVALID_JSON

Przykładowe zapytanie dla którego występuje problem:
- GET, https://api.allegro.pl/sale/offers/11447370855
- TraceId: e12359e8748f34ba

Oczekiwany rezultat:
- komunikat błędu typu "INVALID_OFFER_ID", "OFER_NOT_FOUND" etc, lub
- kod HTTP 404

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już podobne zgłoszenia w wątku #5428. Wyjaśniamy sytuację, o postępach będziemy informować w wyżęj wymienionym wątku. Przepraszam za utrudnienia.
