### ISSUE TITLE
Status oferty

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#5432]
Czy istnieje sposób żeby odpytać się API o własną ofertę Allegro i dowiedzieć się w jakim jest statusie?

**Comment by AureliuszBrussy** [comment]
Oczywiście - zwracamy status ofert w polu `publication.status` po odpytaniu np. [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) czy [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
