### ISSUE TITLE
Pytanie dot. parametru Rozmiar (54) w sale/categories/18008/parameters

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5434]
WItam,
Z góry dziękuję za pomoc.
Chciałbym wyjaśnić jedną rzecz:

Mam taki problem dotyczący parametru Rozmiar (54) w kategorii 18008:
Wyczytałem, że użytkownik może nadawać własne wartości tylko kiedy są dwa warunki: 
Wartość parametru słownikowego valuesIds == ambiguousValueId 
oraz
customValuesEnabled == true

Sęk w tym, że w tej kategorii customValuesEnabled chyba nie jest ustawione jako true,
chociaż jest podana wartość ambiguousValueId.

I jeśli to oleję, to przy innym produkcie, z innej kategorii dostanę błąd, że tak nie wolno.
Bardzo proszę o pomoc w tej kwestii.

**Comment by AureliuszBrussy** [comment]
Może zdarzyć się tak, że w poszczególnych kategoriach jedna z wartości parametru będzie wartością niejednoznaczną, ale nie będziesz miała możliwości wprowadzenia wartości własnej. W tym przypadku jedno nie implikuje drugiego.

**Comment by Witold1983** [comment]
Acha, w porządku. Teraz rozumiem.
