### ISSUE TITLE
429 Too Many Requests podczas odpowiadania w wątku

### ISSUE THREAD

**Issue by gbr161** [allegro/allegro-api#5438]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

trace-id: 80918ecfa0a822c4

Witam
Od kilku dni otrzymuję komunikat podczas wysyłania odpowiedzi w wątku. 
Wiem, że aplikacja nie wysyła więcej niż jedną odpowiedz którą generuję ja wywołując ręcznie skrypt. Aplikacja korzysta ze środowiska testowego i wcześniej nie było problemów. Szukałem odpowiedzi tutaj oraz w internecie, jedyne co znalazłem to nagłówek X-RateLimit-Remaining którego nie znalazłem w odpowiedziach z API. 
Proszę o informacje czy dla https://api.{environment}/messaging/threads/{threadId}/messages obowiązują dodatkowe limity poza 20 sesji i 9000 zapytań na minutę oraz jak sprawdzić który limit został przekroczony (zaznaczam, że skrypt wysyła jedną wiadomość).

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Sprawę konsultuję z zespołem odpowiedzialnym za wskazany zasób. 

Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@gbr161 Dla tego zasobu mamy dodatkowy limit w postaci 1rps dla userId, dlatego otrzymywałeś 429.

**Comment by gbr161** [comment]
Dziękuje za odpowiedź. Rozumiem ze limit 1rps oznacza możliwość wysłania jednej wiadomości przez dane konto allegro korzystające z API, nie jest to limit całej aplikacji ani danego IP. 

Ps. Dodatkowe limity powinny być umieszczone w dokumentacji.
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Tak, limit 1rps oznacza możliwość wysłania jednej wiadomości przez dane konto allegro korzystające z API.

Oczywiście zaktualizujemy naszą dokumentację o tę informację.

Bardzo dziękuję za zgłoszenie.
