### ISSUE TITLE
Time limit for image download

### ISSUE THREAD

**Issue by theazgra** [allegro/allegro-api#5440]
Hello,

what is the timeout for image downloads from provided image URLs?
I am currently testing this in the sandbox environment.

Our image server *works* when browsing in the browser, but when I want to create product offer it fails. I get many responses with
status **408** like:
```
HTTP status code: 408 - RequestTimeout {"errors":[{"code":"UploadImageRequestTimeoutException","message":"Request Timeout","details":null,"path":"","userMessage":"The time limit for downloading an image from the address *redacted* has been exceeded
```

Also **422** with inner exception of **503** and **504**  are received from you API.

**Comment by Lukasz-Zurek** [comment]
The timeout should be checked on your side. You need to verify / increase the timeout for downloading a single photo.

But first of all - please precise your message - what are you trying to do with your images? 

Please send me a trace-id, which will be useful for a verification.

**Comment by theazgra** [comment]
Right, let me explain:

I am trying to create multiple product offers, by calling [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers).
The images are set in the `productSet`'s `product` object.

This endpoint returns varios error statuses (408, 422, 500) caused by to unsuccessful image download.

Here are some trace-ids of the failed requests:
Status code 408
```
e51f29e974017f6c
739fce2b8f903f95
63ee60304fb5b51
9a0662aac77a87f
```

Status code 422
```
6757d8761b0abb5e
69a2d81171d58594
2e5660a8b1c20589
```

Status code 500
```
4a3d72a8247876c2
dede202cbea7d39b
ef15d8adb6d06a5c
```

**Comment by Lukasz-Zurek** [comment]
Thank you for the detailed information. 

I have forwarded this case to another department. Please be patient.

**Comment by Lukasz-Zurek** [comment]
@theazgra In all of the indicated cases, the problem is with the photos server, which takes too long to respond. Therefore downloading the photo when sending the request - ends with various errors, as you have just mentioned. Most of them look like a timeout on your side.

On our side - we do not declare any specific time for download a photo. But if it is too long - we provide errors.

**Comment by theazgra** [comment]
@Lukasz-Zurek Could you specify more exactly what is *too long*? 
Given these new trace-ids
```
b3ab753bc57b87d3
ca85404acf4a6321
39e9c9673c3a35d9
7af6e3854ac8baea
d252df81e6c0b3b1
c71b50ad40624251
91c0d930412bdb4c
78c0045c36341628
e9b8d21ecb0b54a7
30583c0a84546fe8
f5642b5eaf805eb3
3e48b618586cc6ac
dbf1639d12631d0d
```

We have found this in our IIS Image server log:
| date       | time     | cs-method | cs-uri-stem              | cs-uri-query | s-port | cs-username | c-ip          | cs(User-Agent)              | sc-status | sc-substatus | sc-win32-status | time-taken |
|------------|----------|-----------|--------------------------|--------------|--------|-------------|---------------|-----------------------------|-----------|--------------|-----------------|------------|
| 2022-02-16 | 07:49:54 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 156        |
| 2022-02-16 | 07:49:55 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 140        |
| 2022-02-16 | 07:49:56 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 1111       |
| 2022-02-16 | 07:49:56 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 139        |
| 2022-02-16 | 07:49:57 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 111        |
| 2022-02-16 | 07:50:03 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 5.134.208.94  | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 453        |
| 2022-02-16 | 07:50:03 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 5.134.208.94  | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 253        |
| 2022-02-16 | 07:50:04 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 5.134.208.94  | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 109        |
| 2022-02-16 | 07:50:04 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 5.134.208.94  | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 109        |
| 2022-02-16 | 07:50:05 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 406        |
| 2022-02-16 | 07:50:05 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 178.21.154.58 | Allegro-ImageDownloader/1.0 | 200       | 0            | 0               | 546        |
| 2022-02-16 | 07:50:05 | GET       | /prg199/Maia4DATX_61.jpg | -            | 443    | -           | 5.134.208.94  | Allegro-ImageDownloader/1.0 | 200       | 0            | 995             | 312        |

All requests are finished with status 200 and all except one are finished under 1 second

Thank you

**Comment by Lukasz-Zurek** [comment]
@theazgra Thank you for these details. I still consult this case. As soon as I get specific information, I will come back to you.

**Comment by theazgra** [comment]
bad bot, I am still waiting for response from @Lukasz-Zurek  :)

**Comment by Lukasz-Zurek** [comment]
@theazgra We are still verifying this case. Thank you for your patience.

**Comment by Lukasz-Zurek** [comment]
@theazgra We do not see any new bad requests. If the problem still coexists - please send us some new details - when and from what address exactly the photos were downloaded. Together with a team responsible for images - we want to monitor this situation with our diagnostic tools which we have just prepared.

Obviously we are sorry for any inconvenience.

**Comment by theazgra** [comment]
@Lukasz-Zurek I tried again with similiar errors.

You can look for downloads in time period from `2022-02-25 14:15:00` to `2022-02-25 14:20:00`

Interestingly it seems that the problem is only one image https://i2.astratex.pl/prg199/Maia4DATX_61.jpg

I am trying to create multiple variants of this product, and this is the main image, so it has to be downloaded for multilpe product offers, could this be a hint?

**Comment by Lukasz-Zurek** [comment]
No, I do not think that it could be the case, but thank you for this additional information. We will verify it as soon as possible. Please be patient.

**Comment by Lukasz-Zurek** [comment]
At that time, there were a lot of requests to download this picture, most of them were successful, while for some there was a timeout, which means - from our point of view - we did not get a full answer within 10 seconds.

At this moment we do not see any issues.

We are sorry for any inconvenience.
