### ISSUE TITLE
Środowisko testowe a konto ze statusem FIRMA

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5441]
Proszę o włączenie dla konta Client:94513152 na środowisku testowym statusu FIRMA. Chcemy przetestować zarządzanie cennikami hurtowymi, ale otrzymujemy komunikat: "Cenniki hurtowe możesz dodać tylko wtedy, gdy masz aktywne konto Firma na Allegro.
"

**Comment by PrzemyslawLukanowski** [comment]
Rodzaj konta możesz zmienić za pomocą [tej strony](https://allegro.pl.allegrosandbox.pl/biznes). Jeśli w dalszych krokach będziesz mieć problemy z aktywacją konta, napisz proszę w tym wątku.

**Comment by mateuszcom** [comment]
Niestety nie jestem w stanie zmienić rodzaju konta. Otrzymuje komunikat: "Przepraszamy, nie możemy zmienić Twojego konta na firmowe. Korzystasz obecnie z usługi lub ustawień, które nie są dostępne dla kont firmowych."

**Comment by PrzemyslawLukanowski** [comment]
W takim przypadku założ proszę nowe konto, tym razem wybierając rodzaj konta jako "firmowe".

**Comment by PrzemyslawLukanowski** [comment]
Spróbuj proszę wyczyścić pliki cookies lub skorzystaj z innej przeglądarki - nie odntowaliśmy globalnych problemów po naszej stronie.

**Comment by mateuszcom** [comment]
Niestety na innej przeglądarce, po wyczyszczeniu cookies, w trybie prywatnym - nigdzie nie jesteśmy w stanie aktywować konta. Próbowaliśmy ponownie zarejestrować konto i niestety problem jest ten sam. Czy są nam Państwo w stanie ręcznie aktywować to konto?

**Comment by PrzemyslawLukanowski** [comment]
Czy mogę prosić jeszcze o zrzut ekranu z komunikatem błędu? Przekażę w takim razie problem do analizy i wrócę z odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuje, jak wspomniałem - przekazuję problem do analizy do odpowiedniego zespołu. Wrócę z odpowiedzią, gdy uda się ustalić więcej szczególow.

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz spróbować otworzyć załącznik jeszcze raz? Skonsultowałem temat z zespołem odpowiedzialnym za usługę i rzeczywiście wcześniej mogły występować problemy przy otwieraniu pliku.

**Comment by mateuszcom** [comment]
Ok, tym razem już wszystko działa. Dziękuję za pomoc.
Z tego co pamiętam, należy jeszcze aktywować sprzedaż na tym koncie (tak było w przypadku poprzedniego konta) - czy mogę prosić o aktywację?

**Comment by PrzemyslawLukanowski** [comment]
Konto mateuszcom to konto zwykłe, czy na pewno chodzi o nie? Aktywowałem je. Według tego, co napisałeś wcześniej, nie masz możliwości zmiany rodzaju na firmowe przez ten [link](https://allegro.pl.allegrosandbox.pl/biznes). Jeśli chcesz aktywować konto firmowe, załóż proszę nowe konto.

**Comment by mateuszcom** [comment]
Widzę, że cenniki hurtowe działają na tym koncie, więc posiada status FIRMA. Wcześniej właśnie przez powyższy adres rejestrowałem konto

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam za niedogodności, ale rzeczywiście występują rozbieżności z ustawieniami dla tego konta. Czy możesz wejść w ten link -> https://edge.allegro.pl.allegrosandbox.pl/company-onboarding/processes/reverification i ponownie przejść etap weryfikacji konta?

**Comment by mateuszcom** [comment]
Po wejściu we wskazany link otrzymuję: {"errors":[{"code":"AnotherVerificationInProgress","message":"Another verification is in progress","details":null,"path":"/company-onboarding/processes/reverification","userMessage":null}]}

Ale nie wykluczone, że dwukrotnie mi się to wykonało i dla tego ten komunikat

**Comment by PrzemyslawLukanowski** [comment]
Czy podczas wystawiania oferty - czy to przez formularz, czy przez API - otrzymujesz jeszcze jakiś komunikat błędu?

**Comment by mateuszcom** [comment]
W przypadku próby wystawienia oferty przez formularz otrzymuje komunikat "Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert."

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze raz przepraszam za występujące problemy, ale w obecnej sytuacji szybszym rozwiązaniem będzie utworzenie nowego konta. Czy mógłbym prosić o ponowną rejestrację? Jeśli nadal chcesz posługiwać się mailem z obecnego konta, przejdź do edycji konta i zmień mail na inny.

**Comment by mateuszcom** [comment]
Ok już założone. Nowa nazwa to mateuszcom2
