### ISSUE TITLE
Wzrost błądów "You cannot change country of an active offer"

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#5442]
Hej,
Mimo nie zmieniania countryCode(PL) zaczęliśmy otrzymywać poniższe błędy:
`
{'code': 'VALIDATION_ERROR', 'message': 'You cannot change country of an active offer.', 'details': 'IllegalOfferUpdateException.CountryChangeAfterActivation', 'path': 'publication.countryCode', 'userMessage': 'You cannot change country of an active offer.'}]
`
Przykładowe ID ofert: 10839391263, 11092964188

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Faktycznie wystąpiły problemy po naszej stronie, jednak wdrożyliśmy już odpowiednią poprawkę i problem nie powinien występować. Przepraszam za wszelkie niedogodności.

**Comment by array3** [comment]
Potwierdzam, u nas również zaczął występować od godziny ~14:30 i nadal występuje.

**Comment by anih** [comment]
U nas zdecydowanie mniej, ale dalej, np dla oferty 10981314671 o 14:43

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że problem może jeszcze występować. Poinformuję w wątku, gdy ostatecznie uda się go wyeliminować.

**Comment by PrzemyslawLukanowski** [comment]
Wdrożyliśmy odpowiednią poprawkę, problem już nie występuje.
