### ISSUE TITLE
Podgląd oferty przed wystawieniem

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5445]
Wertuje dokumentacje oraz poradniki dostępne na stronie API Allegro i nigdzie nie mogę odszukać informacji w jaki sposób wygenerować przed wystawieniem podgląd oferty. Czy jest taka możliwość z poziomu API?

**Comment by Lukasz-Zurek** [comment]
Nie, w naszym API nie mamy odpowiednika podglądu oferty. Ta funkcjonalność dostępna jest tylko w formularzu sprzedaży, w Moim Allegro.

Oczywiście jeśli korzystasz przykładowo z [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST) czy [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) - wysyłając dane/parametry, w odpowiedzi otrzymujesz draft oferty i w razie braku niektórych parametrów - w polu “validation” wyświetlimy szczegółowe informacje. Dopiero później za pomocą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) publikujesz ofertę w serwisie.

**Comment by mateuszcom** [comment]
Proszę jeszcze o informację czy jesteśmy w stanie pobrać poprzez API w czasie rzeczywistym koszt wystawienia danej oferty + prowizje? Chodzi mi o mechanizm, który znajduje się na stronie Allegro przy ręcznym wystawianiu oferty "Podsumowanie" (Opłaty za wystawienie / Prowizje od sprzedaży)

**Comment by Lukasz-Zurek** [comment]
Możesz skorzystać z odpowiednika kalkulatora opłat, a konkretnie z [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST), dzięki czemu sprawdzisz opłaty, jakie pobieramy dla konkretnej oferty. Natomiast dane oferty pobierzesz za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET).
