### ISSUE TITLE
Pobieranie ofert z powiazanych kont.

### ISSUE THREAD

**Issue by JaroszPatryk** [allegro/allegro-api#5446]
Dzień dobry, stworzyłem aplikację na jednym koncie i powiązałem ją z drugim. Wszystko przebiegło pomyślnie. Natomiast jeżeli chodzi o pobieranie ofert, dostaję pustą listę z drugiego konta. 
Korzystając z takiego requesta  - https://api.allegro.pl/sale/offers - dostaje taki response - 200 OK

{"offers":[],"count":0,"totalCount":0}, mimo że na koncie sa wystawione oferty. Proszę o pomoc i cenne wskazówki. Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Wszystko wskazuje na to, że na wskazanym drugim koncie nie ma żadnych ofert. Podaj proszę trace-id dla tego wywołania. Dzięki temu będę mógł to dokładnie zweryfikować.
