### ISSUE TITLE
Błąd wystawiania ofert baselinker->allegro

### ISSUE THREAD

**Issue by mikoaj92** [allegro/allegro-api#5447]
Oferty samoczynnie zakańczają się na serwisie allegro. W baselinkerze stany na magazynie są większe od 0. W BS zarządzaniu aukcjami również wyświetla się stan magazynowy >0 . 
Jest włączona automatyczna synchronizacja stanów oraz automatyczne wznawianie gdy stan będzie >0 
Allegro twierdzi, że jest wszystko dobrze
Baselinker twierdzi, że robi to allegro

**Comment by Lukasz-Zurek** [comment]
Podaj proszę przykładowe numery zakończonych ofert.

**Comment by mikoaj92** [comment]
11782673081, 11791594698, 11791598482

**Comment by Lukasz-Zurek** [comment]
Oferty zakańczane są zbiorczo przez aplikację o nazwie "Optima1". Najlepiej będzie jak skontaktujesz się z supportem tego narzędzia.

**Comment by mikoaj92** [comment]
Ale optima konfiguruje stany, a bs generuje wznawianie i zakańczanie.  Tym bardziej, że stan w oprtimie jest >1 szt Może Pan przesłać logi ?

**Comment by Lukasz-Zurek** [comment]
Tym bardziej warto, abyś wyjaśnił te wątpliwości z supportem narzędzia. Nie mamy wglądu do konfiguracji. Mogę jedynie potwierdzić, że zakończenie ofert zrealizowane zostało przez wspomnianą aplikację. 

Dodam, że nie udostępniamy na forum naszych wewnętrznych logów.
