### ISSUE TITLE
Zestawy produktowe - wielowariantowość

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#5448]
Czy oferty będące zestawem produktów mogą być łączone w oferty wielowariantowe:
1) Oferta wielowariantowa z ofert "jednoproduktowych" i "zestawów" ?
2) Oferta wielowariantowa tylko z ofert "zestawów" ?

**Comment by PrzemyslawLukanowski** [comment]
Tak, mogę potwierdzić, że na tę chwilę obie opcje są możliwe. Ustalam jednak więcej szczegółow z zespołem odpowiedzialnym za funkcjonalność, dlatego wrócę jeszcze z dodatkową odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam wcześniejsze ustalenia - wielowariantowość istnieje na poziomie ofert, więc obie opcje są możliwe, oferta wielowariantowa musi być tworzona w oparciu o parametry pierwszego produktu z zestawu.
