### ISSUE TITLE
zdjęcia i opis oferty json przy wystawianiu przez csv

### ISSUE THREAD

**Issue by raftech1** [allegro/allegro-api#5450]
Witam

Wystawiam oferty poprzez plik csv. Chciałem użyć formatowania json do opisu oferty, tak aby móc używać sekcji i uatrakcyjnić opis. Trafiłem natomiast na problem ze zdjęciami. 

Przy wystawianiu oferty przez plik csv dodajemy zdjęcia poprzez podanie linku do zdjęcia1, 2, 3 etc. jak rozumiem allegro zaciąga je do swojego serwera i do danej oferty. Również później ściągając "raport" czyli edytując oferty, nadal jest podany adres url obrazka na zewnętrznym serwerze - czyli tym na którym są oryginalne zdjęcia. 

Natomiast wg procedury json, należy podać adres url pliku już na serwerze allegro. Jak dobrze rozumiem, podczas wysyłania pliku zdjęcia na serwer allegro, system zwraca adres tego obrazu (zakodowany) i wtedy można użyć tego adresu. 

Więc defakto nie można wykorzystać tego w ten sposób, chyba że czegoś nie rozumiem.  fajnie jakby dało radę wykorzystać w prosty sposób pliki które zostają przesłane wraz z tworzeniem oferty. np możliwość wyboru pics1, pics2, pics3...

Chyba że ktoś mógłby pomóc w tym temacie, albo jest jakaś inna opcja ?

**Comment by Lukasz-Zurek** [comment]
Skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Tam uzyskasz wsparcie związane z masowym wystawianiem ofert z pliku CSV.

**Comment by raftech1** [comment]
rozmawiałem z allegro, odpowiedzieli że nie ma takiej możliwości, dlatego pisze tutaj

**Comment by Lukasz-Zurek** [comment]
Rozumiem. Na naszym forum świadczymy jednak wsparcie w zakresie publicznego API, dlatego skierowałem Ciebie wcześniej do formularza kontaktowego.

Być może znajdzie się osoba na naszym forum, która pomoże Tobie w tym temacie.

**Comment by kfijalko** [comment]
@raftech1 skoro umiesz przygotować opis w json'ie to zapewne nie będziesz miał też problemu z przygotowaniem oferty w json'ie => bo to tylko kilka pól więcej
potem już tylko jeden mały krok żeby tego jsona wysłać do odpowiedniej metody restapi
Link do dokumentacji:
https://developer.allegro.pl/documentation/#operation/createProductOffers

**Comment by raftech1** [comment]
Właśnie w programowaniu nie jestem biegły, korzystam z php aby generować pliki csv z ofertami i dalej żeby je aktualizować. ale całego procesu nie dam radę zrobić. Natomiast przy csv, opisy są biedne, ograniczone jedynie do kilku znaczników html. okazało się jednak że da radę przekazać w csv opis w json, tylko kłopot z tymi zdjęciami.
