### ISSUE TITLE
Brakuje jednego z tagów otwierajacych- wystawienie allegro

### ISSUE THREAD

**Issue by Justynka21** [allegro/allegro-api#5451]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam nie mogę wystawić oferty pokazują mi sie takie błędy.korzystam z platformy iai i z panelu iai wystawiam aukcję allegro.Jeżeli będzie to potrzebne mogę przesłać kod html szablonu który był wykorzystany do wystawienia oferty  file:///C:/Users/LENOVO/Downloads/request_allegro_20220217_204634.xml , file:///C:/Users/LENOVO/Downloads/response_allegro_20220217_204634(1).xml
Pozdrawiam
A.B

**Comment by Lukasz-Zurek** [comment]
Komunikat błędu: "Brakuje jednego z tagów otwierających" dotyczy opisu oferty. Pamiętaj że każdy użyty przez Ciebie tag musi być zarówno otwarty <>, jak i zamknięty </>. Sprawdź zatem Twój opis. Przykład jak poprawnie łączyć znaczniki HTML - opisaliśmy w [naszym poradniku](https://developer.allegro.pl/sale/#6-opis-oferty).

Dodam, że wskazane przez Ciebie linki są nieprawidłowe. Aby móc sprawdzić Twój request i response, musisz je przesłać na zewnętrzny serwer, z którego będzie można pobrać pliki.
