### ISSUE TITLE
415 dla wysyłki zdjęć sale/images

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#5452]
Dlaczego zapytania o TRACE ID: 

b6c3951097f2755f, 
45668dc37adf08e0,
2d8c966bc488270b

zwracają wciąż błąd 415, skoro przekazuję odpowiedni Content-type?

Czego robimy źle?

**Comment by Lukasz-Zurek** [comment]
W Content-type przekazujesz `application/json`, a powinieneś przekazać: `application/vnd.allegro.public.v1+json`.

**Comment by marmited** [comment]
> W Content-type przekazujesz `application/json`, a powinieneś przekazać: `application/vnd.allegro.public.v1+json`.

Czy możecie sprawdzić również: 49ed6b2ece043780?

Według tego co przekazuje powinno być:
{Content-type=application/vnd.allegro.public.v1+json}
{application/json={"url":"https:/.....jpg"}}

**Comment by marmited** [comment]
Zastanawiam się dlaczego d17e65b049bbf1fe przeszło poprawnie, Możecie powiedzieć czy tutaj jest wszystko ok w tym requescie?

Z tego co widzę, najprawdopodobniej jest to błąd starszej wersji biblioteki RestSharp.

Dla potomnych, to zadziałało:
request.AddHeader("Content-type", "application/vnd.allegro.public.v1+json");

string serializedObject = JsonConvert.SerializeObject(new { url = imagePath });
request.AddParameter("application/vnd.allegro.public.v1+json", serializedObject, ParameterType.RequestBody);

**Comment by Lukasz-Zurek** [comment]
W przypadku - 49ed6b2ece043780 - w Content-type również przekazałeś `application/json`.

Natomiast dla d17e65b049bbf1fe - faktycznie to żądanie zakończyło się powodzeniem, w Content-type przekazałeś już `application/vnd.allegro.public.v1+json`.
