### ISSUE TITLE
using “application/vnd.allegro.public.v1+json” on  "/sale/product-offers"

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5453]
•	for POST /sale/product-offers and GET /sale/product-offers/{offerId} - “product” field has been replaced with the “productSet” field, which is an array of objects.

can you share a sample json for this operation, i can't find in the documents also in the forum.

old model:
        {
            "product": {
                "name": "Poczucie | Plisowana Dluga Spódnica Zielona",
                "category": {
                    "id": "76084"
                },
                "parameters": [{
                        "id": "54",
                        "valuesIds": ["3806_3"],
                        "ReferenceId": "e098ae1a-75fa-497a-b6ac-614ed525458c",
                        "MasterAttributeItemValue": "36"
                    }
                ],
                "images": ["https://n11-image.mncdn.com/a1/org/giyim-ayakkabi/diz-boyu-etek/sense-uzun-piliseli-beli-lastikli-etek-etk32343-yesil__0196517569393815.jpg"]
            },
            "images": ...
            "sellingMode": ...
            "stock": ...
			...

**Comment by Lukasz-Zurek** [comment]
You will find new sample requests in [our tutorial](https://developer.allegro.pl/en/product_offers/), for example right [here](https://developer.allegro.pl/en/product_offers/#how-to-list-an-offer-assigned-to-a-product-that-is-not-in-our-database).
