### ISSUE TITLE
Re: Odpowiedź na zgłoszenie nr "20457808" [ ref:_00D24aE05._5003VLiYTY:ref ] Firma kurierska nie otrzymuje zleceń odbioru generowanych przez baselinker

### ISSUE THREAD

**Issue by electofun** [allegro/allegro-api#5454]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x ] inny / other

:beetle: **Opis / Description**

Mamy problem z odbiorem paczek, firma kurierska nie widzi zleceń odbioru wysyłanych przez zintegrowany system baselinker, od operatora baselinker otrzymaliśmy informację, że po sprawdzeniu zlecenie są poprawnie rejestrowane. W poprzednich wiadomościach przesłaliśmy logi o które Państwo prosili.
[request (1)-2.log](https://github.com/allegro/allegro-api/files/8095907/request.1.-2.log)

**Comment by Lukasz-Zurek** [comment]
Z komunikatu błędu wynika, że odbiór kuriera zleciłeś już wcześniej. Jeżeli we wskazanym zgłoszeniu podałeś commandId dla utworzonej wcześniej paczki - zweryfikuję to dokładnie i jak tylko zgłoszenie do mnie dotrze - udzielę odpowiedzi w tym wątku.
