### ISSUE TITLE
Wznowienie oferty ze statustem endedBy "EXPIRATION".

### ISSUE THREAD

**Issue by kamilsakowicz92** [allegro/allegro-api#5455]
Dzień dobry,
z tego co widzę w dokumentacji jest możliwość wzowienia oferty typu "KUP TERAZ", czy jest możliwość wzowienia oferty typu "ogłoszenie"? 
Gdy próbuję to robić według dokumentacji ( odnośnie KUP TERAZ ), tzn:
PUT "/sale/offer-publication-commands/a0377fd7-9c14-4276-b630-7f77a717cd7b" 
body: "{"offerCriteria":[{"offers":[{"id":"7685129646"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"ACTIVATE"}}". 
Dostaję odp: 
`"tasks" => array:1 [
    0 => array:7 [
      "offer" => array:1 [
        "id" => "7685129646"
      ]
      "message" => ""
      "status" => "SUCCESS"
      "scheduledAt" => "2022-02-07T01:03:46.857Z"
      "finishedAt" => "2022-02-07T01:03:46.837Z"
      "field" => "publication"
      "errors" => []
    ]
  ]`

Data nie zostaje zmieona, oraz ogłoszenie widnieje dalej jako zakończone.
Z góry dzięki za pomoc, pozdrawiam :)

**Comment by Lukasz-Zurek** [comment]
Tak, możesz wznawiać ogłoszenia. Z logów wynika jednak, że korzystasz cały czas z tego samego commandId: a0377fd7-9c14-4276-b630-7f77a717cd7b. Pamiętaj, że przy każdorazowej akcji aktywowania, lub zakończenia oferty, w polu commandId musisz podać unikatową wartość.
