### ISSUE TITLE
Parametr 207786 nie umożliwia podania wartości spoza słownika

### ISSUE THREAD

**Issue by exploIF** [allegro/allegro-api#5456]
Cześć,

Mam problem z podaniem dodatkowej wartości dla parametru 207786 (przeznaczenie) w kategorii 10532. W polu valuesIds podaje wartość 'ambigousId' dla tej kategorii czyli '207786_233878', a mimo wszystko przy próbie podania własnej wartości dostaje komunikat błędu ParameterIsNotCustomValueEnabledException.

Poniżej, jak wysyłam wartość tego parametru:
```
{
  'id': '207786',
  'valuesIds': ['207786_233878'],
  'values': ['Garmin']
}
```

**Comment by Lukasz-Zurek** [comment]
Dla wskazanego parametru **"customValuesEnabled": false**, co oznacza, że nie możesz przekazać własnej wartości. Błąd jest tutaj zatem uzasadniony.

**Comment by exploIF** [comment]
@Lukasz-Zurek 
W dokumentacji (https://developer.allegro.pl/productization/#5-jak-dodać-produkt), zakładka "Dodaj własną wartość dla parametru z wartością niejednoznaczną" jest identyczna sytuacja, a mimo wszystko wartość jest wysyłana. Poza tym w dokuementacji pada takie zdanie:
```
Jeżeli w polu valuesIds przekażesz identyfikator wartości niejednoznacznej ambiguousValueId, to uzupełnienie własnej wartości w polu values będzie obowiązkowe.
```
Dlaczego w takim razie nie mogę przekazać wartości w polu values?
