### ISSUE TITLE
Pickup name is too long

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#5458]
Dzień dobry.
W requeście "id":"6d98c4ea-c378-44c9-a011-4d3caf9bef3d" otrzymałem błąd 
"code":"ERROR","message":"Pickup name is too long","details":null,"path":"pickup.name","userMessage":"Nazwa punktu nadania przesyłki jest za długa"
"code":"ERROR","message":"Receiver name is too long","details":null,"path":"receiver.name","userMessage":"Nazwa odbiorcy jest za długa"

jakie są limity długości dla pól? i gdzie można znaleźć taką informację?

**Comment by PrzemyslawLukanowski** [comment]
Tak, racja, przepraszam, nazwą punktu nadania również może być prywatna osoba. W tym przypadku jednak nie dysponujemy szczegółowymi informacjami o limitach u danych przewoźników.
