### ISSUE TITLE
brak synchronizacji cen i ilości w wybranych produktach

### ISSUE THREAD

**Issue by Przemek98** [allegro/allegro-api#5459]
Witam, Czy mógłbym prosić o wsparcie w kwestii problemu z synchronizacją cen i ilości z Prestashop? Używam wtyczki x13. Teoretycznie wszystko działa ale systematycznie przestaje synchronizować poszczególne produkty. Dodam, że upewniałem się, że wszystkie parametry problematycznego produktu w aukcji allegro są uzupełnione.

**Comment by PrzemyslawLukanowski** [comment]
Czy mógłbyś podać przykładowe numery ofert, dla których występuje problem? Zweryfikuję, czy w naszych logach widać dla nich jakieś błędy.

**Comment by Przemek98** [comment]
11750247408 , 11409050231,  11409047437

**Comment by Przemek98** [comment]
11513522503 - Jeszcze się upewnię. Na tej aukcji robię teraz cały czas testy i od 16 żadnego śladu po próbie edycji ceny u Was nie widać? Tak jakby w ogóle nie było wysyłany update do WEB API?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, nic do nas nie dotarło.
