### ISSUE TITLE
Kilka przesyłek do jednego zamówienia

### ISSUE THREAD

**Issue by robboh** [allegro/allegro-api#5460]
Jak przekazać do jednego zamówienia kilka numerów listów przewozowych generowanych poza systemem Allegro?
/order/checkout-forms/{id}/shipments umożliwia podstawienie jednego numeru listu.
Czy należy wywołać /order/checkout-forms/{id}/shipments kilkukrotnie z kolejnymi numerami listów?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, jak to opisałeś - "należy wywołać /order/checkout-forms/{id}/shipments kilkukrotnie z kolejnymi numerami listów".
