### ISSUE TITLE
Edycja czasu dostawy wielu ofert jednocześnie przez API

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#5461]
Dzień dobry.

jak zmienić czas realizacji (handling time) w wielu ofertach jednocześnie - czy da się to zrobić masowo dla wszystkich ofert lub co najmniej dla dużych grup (po 1000 na raz)? Czy coś się zmieniło od 2019 roku w tej kwestii? 

Czy jak użyję kodu poniżej to zadziała?

```
        $data = array(
            "modification" => array (
                "delivery" => array(
                    "shippingRates" => array (
                        "id" => "12345XXX"
                    ),
                    "HandlingTime" => "PT48H"
                )
            ),
            "offerCriteria" => array(
                array(
                    "offers" => array (
                        array("id" => '12345'), array("id" => '34567'), array("id" => '98765')
                    ),
                    "type" => "CONTAINS_OFFERS"
                )
            )
        );

```

**Comment by lukiopmoto** [comment]
Dziękuje za informację. Pytanie czy czas dostawy czyli "HandlingTime" dla danej oferty mogę zmienić tylko i wyłącznie pobierając ją całą przez [GET sale/offers/{offerId}], następnie zmieniając wartość parametru HandlingTime na właściwą i wysyłając poprzez [PUT /sale/offers/{offerId}]? 

Czy można to zrobić tak jak w pierwszym moim poście przy użyciu [PUT /sale/offer-modification-commands/{commandId}] i podaniu w "offerCriteria" -> "offers" tylko jednej wartości (ID jednej oferty). Zakładam że ta operacja zmienia tylko cennik dostaw a nie wartość czasu dostawy, mimo iż jest on przekazywany.

Problem polega na tym że np. dla 10.000 ofert wypada mi dostawca. Nowy ma o 1-2 dni dłuższy czas dostawy. Chcę zmienić czas dostawy dla 10 000 ofert i muszę to zrobić pojedynczo dla każdej osobno? Pobierając całą ofertę i zmieniając jedną wartość i wysyłając ofertę ponownie zajmuje to ok. 1 sekundy na ofertę. Cała zmiana trwała by zatem prawie 3h bez żadnych przerw.

**Comment by PrzemyslawLukanowski** [comment]
Za pomocą PUT /sale/offer-modification-commands/{commandId} niestety nie zmienisz wartości pola `handlingTime`, ale nie musisz także pobierać oferty przez GET /sale/offers/{offerID} i wysyłać ją następnie przez PUT /sale/offers/{offerID}. Zapoznaj się proszę z naszą metodą [PATCH na zasobie /sale/product-offers/{offerID}](https://developer.allegro.pl/documentation/#operation/editProductOffers), którą szczegółowo opisaliśmy w [naszym poradniku](https://developer.allegro.pl/product_offers/#jak-edytowa%c4%87-ofert%c4%99). W ten sposób nie musisz wcześniej pobierać szczegółow oferty, wystarczy, że prześlesz poniższy request, aby zmienić wartość `handlingTime`  w ofercie:

```
curl --location --request PATCH 'https://api.allegro.pl/sale/product-offers/{offerID}' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer {token}' \
--data-raw '{
    "delivery": {
        "handlingTime": "string"
    }
}'
```

**Comment by lukiopmoto** [comment]
Dzień dobry,

Zrobiłem update czasy dostawy przed chwilą w oparciu o PATCH, wszystko zgodnie w poradnikiem i okazało się że nawet na mocnym serwerze dedykowanym operacja trwa: **Czas wykonania operacji: 0.90947 sekund** czyli prawie sekundę. Podsumowując wychodzi na to że czy pobiorę całą ofertę i wrzucę ja poprawioną (GET, PUT) czy zrobie (PATCH) to i tak muszę się liczyć z kosztem około 1 sekundy co jest nieakceptowalne. Być może coś robię źle że PATCH działa tak wolno? Czy to raczej normalne z Państwa doświadczenia?

**Comment by PrzemyslawLukanowski** [comment]
Twój wynik jest przybliżony do średniego czasu odpowiedzi - w moim przypadku otrzymałem średnio 770ms na 10 requestów. Podobny czas otrzymasz również przypadku edycji za pomocą metody PUT. Oferta musi zostać przez nas zwalidowana, stąd ten czas nie wynosi 0.1s. Długość odpowiedzi jest oczywiście także zależna od zewnętrznych czynników, jak np. aktualny ruch w naszym API.

**Comment by lukiopmoto** [comment]
Rozumiem. Zmiana ceny dla jednej aukcji to średni koszt ok. 0,06 sekundy więc myślałem że czas dostawy też da się jakoś szybko podmienić. Czy w niedalekiej przyszłości przewidziana jest stworzenie metody dedykowanej do zmiany czasu dostawy?

Nie rozumiem co walidować przy edycji jednego parametru jakim jest czas dostawy skoro wiadomo że ma format `PT([0-9]{2,3})H` lub inny którego ewentualna walidacja trwa pewnie tysięczne części sekundy. Nic innego przez PATCH nie zmianiemy przecież.

**Comment by PrzemyslawLukanowski** [comment]
> Czy w niedalekiej przyszłości przewidziana jest stworzenie metody dedykowanej do zmiany czasu dostawy?

Na tę chwilę nie, zachęcam Cię jednak do utworzenia sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Dzięki temu również inni użytkownicy forum będą mogli na nią głosować, a tym samym my będziemy wiedzieć, jak duża jest potrzeba, aby dodać taką funkcjonalność.

> Nie rozumiem co walidować przy edycji jednego parametru jakim jest czas dostawy skoro wiadomo że ma format PT([0-9]{2,3})H lub inny którego ewentualna walidacja trwa pewnie tysięczne części sekundy. Nic innego przez PATCH nie zmianiemy przecież.

Mimo tego, że przesyłasz tylko jedno pole, walidujemy cały model oferty - zwróć uwagę, że odpowiedzi dostajesz także inne pola, włącznie z sekcją `validation`, w której zwracamy wszelkie błędy, jeśli takie występują w ofercie.
