### ISSUE TITLE
Zewnętrzny moduł do wystawienia aukcji allegro z dwustronną integracją

### ISSUE THREAD

**Issue by PWBP** [allegro/allegro-api#5462]
Dzień dobry,
jesteśmy na poziomie rozpoznania możliwości i potrzebnych zasobów do stworzenia zewnętrznej stronny modułu allegro do udostępniania klientom, aby mogli wystawiać automatycznie kilkoma kliknięciami aukcje, ustalać ceny ilości itd. produktów, które udostępnimy do wystawienia.
Czy Allegro ma gotowe rozwiązanie w tym kierunku, czy taki moduł będzie trzeba stworzyć od podstaw indywidualnie?

**Comment by Lukasz-Zurek** [comment]
W Allegro API udostępniamy zasoby służące do przygotowania draftu/szkicu, wystawienia oferty i jej edycji. Są to:

- [POST /sale/offers](https://developer.allegro.pl/documentation/#operation/createOfferUsingPOST),
- [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT).

Proces wystawiania opisaliśmy dokładnie w [w naszym poradniku](https://developer.allegro.pl/sale/).

Udostępniamy również [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), dzięki któremu jednym requestem wystawisz ofertę powiązaną z produktem. [Tutaj](https://developer.allegro.pl/product_offers/) opisaliśmy to szerzej.

Natomiast zarządzanie ofertami, czyli m.in. edycję wielu ofert jednocześnie - opisaliśmy [tutaj](https://developer.allegro.pl/my_offers/#edycja-wielu-ofert-jednocześnie).

Jeśli masz konkretne pytania - chętnie na nie odpowiem.
