### ISSUE TITLE
Czy oferty z endedBy=ADMIN będzie można wznowić?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5463]
Czy oferty z endedBy=ADMIN będzie można wznowić? Jak zachowa się REST API podczas takiej próby wznowienia? Czy odpowiedź będzie uzależniona od przyczyny pojawienia się endedBy ADMIN?

**Comment by Lukasz-Zurek** [comment]
W przypadku:

- ofert zakończonych z powodu naruszenia zasad Allegro.pl - może się zdarzyć, że nie wznowisz niektórych z nich, z uwagi na dodatkowe ograniczenie, które nałożył pracownik serwisu Allegro.pl,
- powielonych ofert tego samego przedmiotu - wznowisz każdą z tego typu ofert.
