### ISSUE TITLE
Brak potwierdzenia zmiany oferty

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#5465]
Wysyłając request zmiany ilości dostępnych produktów:

```
PUT sale/offer-quantity-change-commands/ab349242-8df0-e245-7ae4-dcd14a4c94e9{"modification":{"changeType":"FIXED","value":77},"offerCriteria":[{"offers":[{"id":"10967164509"}],"type":"CONTAINS_OFFERS"}]}
```

W odpowiedzi otrzymuję zawsze to samo:
```
{"id":"ab349242-8df0-e245-7ae4-dcd14a4c94e9","taskCount":{"total":0,"success":0,"failed":0}}
```
Wobec czego **nie wiem** czy dane zostały zaktualizowane czy też nie. I tak często oferty, które do niedawna się aktualizowały, teraz się nie zmieniają, bo oferta w danej kategorii wymaga dodatkowych parametrów np. przypisania do produktu w katalogu Allegro.

Druga sprawa to dostęp do API z dwóch serwerów. Każdy response jest taki sam przy czym zmiany zapisują się gdy request wysyłany jest tylko z jednego. Drugi serwer pomimo dodania jego URLa do aplikacji otrzymuje taką samą odpowiedź ale zmian nie widać.

Czyżbym używał starych metod/endpointów, które już nie są rozwijane?
Czy jest możliwość zmiany ilości dostępnych sztuk, a przy tym dostania odpowiedzi czy operacja się powiodła czy też nie?

**Comment by Lukasz-Zurek** [comment]
Próbujesz zmienić ilość sztuk będąc autoryzowanym jako sprzedający, do którego nie należy wskazana oferta. Szczegółowy status zlecenia możesz sprawdzić za pomocą [GET /sale/offer-quantity-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getQuantityModificationCommandTasksStatusesUsingGET). Dane nie zostały zatem zaktualizowane i w szczegółowym statusie, w polu `"message"` powinieneś otrzymać `"OFFER_DOES_NOT_BELONG_TO_SELLER"`.

Myślę, że to również odpowiada na Twoje drugie pytanie. Upewnij się z jakich tokenów korzystasz podczas wysyłania requestów.

**Comment by hahyes** [comment]
> Wobec czego nie wiem czy dane zostały zaktualizowane czy też nie.

Dodam tylko, że otrzymawszy `id` w odpowiedzi musisz odpytać szczegóły danego polecenia opisanego właśnie tym `id`, żeby się dowiedzieć, czy aktualizacja przebiegła pomyślnie. Zwrotka z `"success": 1` nie oznacza, że aktualizacja doszła do skutku, tylko że dane polecenie zostało przez serwer poprawnie przyjęte. Zasób jest asynchroniczny, dlatego tak jest.

**Comment by gkopec** [comment]
@Lukasz-Zurek @hahyes bardzo Wam dziękuję za szybką podpowiedź. Dzięki szczegółom zlecenia widzę teraz co się dzieje z poszczególnymi akcjami aktualizacji, np EXCEPTION_DURING_OFFER_QUANTITY_UPDATE.
