### ISSUE TITLE
[Sandbox] Captcha HTML zwracany w odpowiedzi z każdej końcówki API

### ISSUE THREAD

**Issue by 9orky** [allegro/allegro-api#5467]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Zapytanie po oferty:
`
curl --location --request GET 'https://allegro.pl.allegrosandbox.pl/sale/offers' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer  {accessToken}' \
--header 'Cookie: {cookieData}'
`

zwraca kod HTML z captcha:
`<html><head><title>allegrosandbox.pl</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMA9luIWLdw4DIAXqypGg==','hsh':'77DC0FFBAA0B77570F6B414F8E5BDB','t':'bv','s':29544,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>`

Przeglądając historię zgłaszanych błędów, ten chyba nie wydaje się nowy :)

**Comment by Lukasz-Zurek** [comment]
Wskazany błąd jest zgodny z założeniem.

Do wywołania zasobów API Allegro służy adres: https://api.allegro.pl.allegrosandbox.pl/ (na środowisku testowym) oraz https://api.allegro.pl/ (na środowisku produkcyjnym).

Aby uzyskać listę ofert za pomocą GET /sale/offers na sandboxie, zamiast adresu https://allegro.pl.allegrosandbox.pl/sale/offers użyj https://api.allegro.pl.allegrosandbox.pl/sale/offers.

**Comment by 9orky** [comment]
Dziękuję za pomoc, niedopatrzenie z mojej strony :)
