### ISSUE TITLE
Podczas konfiguracji systemu allegro one box programiści poprosili mnie o podanie parametru: Sending pickup point id 

### ISSUE THREAD

**Issue by kamilkomtek** [allegro/allegro-api#5469]

**Comment by kamilkomtek** [comment]
Podczas konfiguracji systemu allegro one box programiści poprosili mnie o podanie parametru: Sending pickup point id
Nie mam pojęcia skąd pobrać taki parametr.

**Comment by MaciejFrackowiak** [comment]
Listę punktów Allegro pobierzesz za pomocą [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET). Spójrz także do [naszego poradnika](https://developer.allegro.pl/wza/#jak-pobra%c4%87-list%c4%99-punkt%c3%b3w-allegro), gdzie opisaliśmy ten proces.
