### ISSUE TITLE
Get sale/shipping-rates Access is denied

### ISSUE THREAD

**Issue by ivansurov** [allegro/allegro-api#547]
Hello,

i have a problem with get shipping rates from Rest Api

Try this:

curl -X GET 'https://api.allegro.pl/sale/shipping-rates?seller.id={my_seller_id}' -H 'Accept: application/vnd.allegro.beta.v1+json' -H 'Authorization: Bearer {my_token}' -H 'content-type: application/vnd.allegro.beta.v1+json'

Get this response:
{"errors":[{"code":"ERROR","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. Please retry, or restart application."}]}

what could be the problem? There is a similar problem if I want to get details offer sale/offers/my_offer_id. But for example I successfully  get a list my offers /offers/listing. Also I can upload an image to your server.

**Comment by adampajak** [comment]
Hi,
You provide wrong seller.id in your request.

**Comment by adamczykjac** [comment]
I assume you won't get any shipping rates for other sellers besides yourself authorized, am I right?

**Comment by PawelTaberski** [comment]
Yes, you must be authenticated as seller which created these shipping rates. More about that you will find [here](https://developer.allegro.pl/en/sale/#shipping-rates).

**Comment by adamczykjac** [comment]
Yup I've seen this one. I was only wondering how to fetch possible shipping costs provided by a given (any) seller. This info is available for every offer at the bottom of its description (on the platform itself), in API though it's only the info about the lowest delivery price. Is it anyhow planned to be released or we're rather getting into the field, which constitutes competitive advantage for both - the Allegro as the platform itself and the given seller?

**Comment by PawelTaberski** [comment]
For now we don't plan to implement method by which you would be able to get another seller shipping rates.
