### ISSUE TITLE
Problem z propozycją zmiany kategorii produktu

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#5470]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy propozycji zmiany kategorii produktu (48e26065-2bed-453b-888e-76fc97afd576) za każdym razem otrzymuje błąd "ParameterDoesNotExistException"  ("Parameter: 10563 does not exist") Parametr 10563 to parametr, który występuje w pierwotnej kategorii. Niezależnie od tego czy podaje w requescie parametry tylko dla nowej kategorii ("trace-id: d16621f43056b93"), tylko dla starej kategorii ("trace-id: 880e6df5edb20721") czy dla starej i nowej jednocześnie ("trace-id: 7f5e5c529c2fdd63") to dostaje właśnie wspomniany komunikat błędu.

**Comment by MaciejFrackowiak** [comment]
Konsultuję opisany przypadek z zespołem, wrócę z odpowiedzią.

**Comment by glinkaa** [comment]
@MaciejFrackowiak czy wiadomo już coś?

**Comment by MaciejFrackowiak** [comment]
Zidentyfikowaliśmy źródło problemu, pracujemy obecnie nad wdrożeniem niezbędnej poprawki. Oczywiście poinformuję, gdy ostateczne rozwiązanie zostanie zaimplementowane.
