### ISSUE TITLE
Pytania o usuniętą kategorię

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#5471]
Oferta allegro nr 10533237221 miała ustawioną kategorię 86445. Przy próbie ponownego jej wystawienia został zwrócony komunikat "Category not found", więc domyślam się że kategoria została scalona z inną. Po pobraniu danych oferty z allegro, pojawiła się nowa kategoria nr 318876.
 
1. Dlaczego zasób api `/sale/category-events` nie zwraca informacji usunięciu kategorii 86445?
2. Jaka była pełna nazwa kategorii z id 86445?

**Comment by MaciejFrackowiak** [comment]
Odpowiadając na pytania:

1) Zasób zwraca dane z ostatnich 3 miesiący, a jak widzę kategoria 86445 została zmieniona w dniu 12.05.2021;
2) Dziecko - Rowery i pojazdy - Pojazdy elektryczne - Akcesoria.
