### ISSUE TITLE
Allegro Paczkomaty InPost API ID

### ISSUE THREAD

**Issue by markip19** [allegro/allegro-api#5472]
Jak dodać metodę Allegro Paczkomaty InPost do wysylam.allegro.pl aby otrzymać poprawny service_id skoro nazwa Allegro Paczkomaty InPost jest dłuższa nie dostępne pole. A jak nazwa jest inna to serwis zwraca "Usługa niedostępna u tego przewoźnika" np. 21cb8276-a8e6-4ab1-9547-f1ac38d27831

**Comment by hahyes** [comment]
https://developer.allegro.pl/wza/#jak-pobra%C4%87-list%C4%99-us%C5%82ug-dostawy

**Comment by Lukasz-Zurek** [comment]
@markip19 W polu **"serviceId"** przekazałeś id dotyczący innej metody dostawy (Allegro Inpost). 

Jak już zasugerował @hahyes - skorzystaj z [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices), aby pobrać listę usług dostawy.
