### ISSUE TITLE
[sandbox] Błąd podczas dodawania propozycji produktu, InvalidParameterDtoException id:225693

### ISSUE THREAD

**Issue by T-Pliszka** [allegro/allegro-api#5473]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

 ` {"name":"EHEIM InstallationsSET Przegub kulowy strumie\u0144","category":{"id":257450},"images":[{"url":"https://a.allegroimg.allegrosandbox.pl/original/1135df/6a5e654c4c19ba1249759f6e2104"}],"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"209278","valuesIds":["209278_238642"],"values":[],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["4011708401576"],"rangeValue":null},{"id":"224017","valuesIds":[],"values":["4005600"],"rangeValue":null},{"id":"248368","valuesIds":["248368_905170"],"values":[],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Przedmiotem tej aukcji jest</p><h1>EHEIM InstallationsSET </h1><h2>Przegub kulowy do regulacji k\u0105ta strumienia wody.</h2>"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.allegrosandbox.pl/original/1135df/6a5e654c4c19ba1249759f6e2104"},{"type":"TEXT","content":"<p>Wysokiej jako\u015bci przegub kulowy do regulacji k\u0105ta strumienia wody w instalacjach EHEIM Installations SET 2. Cz\u0119sto stosowany przy deszczownicach EHEIM. \u015arednica wewn\u0119trzna jednego z wyj\u015b\u0107 wynosi 19mm natomiast \u015brednica zewn\u0119trzna drugiego 22mm. </p>\r\n\r\n<p>Podana cena <b>23,87z\u0142</b> jest cen\u0105 brutto, zawiera wliczony podatek VAT.</p>"}]}]}}`

Podczas dodawania propozycji produktu dla allegro /sale/product-proposals mam nie jasne błędy. Zawsze wracam do pierwotnego błędu, gdzie moim zdaniem poprawnie jest przekazany parametr EAN.
` {"errors":[{"code":"ParameterException.InvalidParameterDtoException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 225693."}]}`

Proszę o podpowiedź gdzie jest błąd, czy Wasz system nie zna tego kodu EAN i nie chce go przyjąć?

**Comment by Lukasz-Zurek** [comment]
@T-Pliszka Wskazany kod EAN jest prawidłowy. Usuń proszę pole `"valuesIds": [],` z parametrów 225693 i 224017. Dzięki temu powinieneś utworzyć produkt.

**Comment by T-Pliszka** [comment]
@Lukasz-Zurek Dziękuję za podpowiedź, błąd jednak był a innym miejscu. 

Dostawałem błąd 400 (ParameterException.InvalidParameterDtoException) czyli coś nie było tak z danymi. I mój problem był z tablicą parametrów. Przy kodowaniu do wysłania danych json_encode($array, JSON_UNESCAPED_SLASHES);

Przykład tablicy z błędnymi danymi:
$array2  = [
0 => ['value' => '000'],
5 => ['value' => '111']
];
echo json_encode($array2, JSON_UNESCAPED_SLASHES);

poprawne dane:
