### ISSUE TITLE
Wprowadzenie obowiązkowej produktyzacji a stary zasób do tworzenia ofert

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5478]
Witam,

chciałbym zapytać o produktyzację i zasoby wystawiania nowych ofert. Jakie macie plany wobec zasobu `POST /sale/offers`? Czy będę zmuszony do wykorzystywania `POST /sale/product-offers` do wystawiania? 

Nie ukrywam, że bardzo mi to nie pasuje, ponieważ nowy zasób nie pozwala mi na wybór miniaturki oferty, ponieważ zdjęcia produktu zawsze są w pierwszej kolejności. Wiele produktów utworzonych przez nas skończyło z pomocniczą grafiką prezentującą rozmiary jako miniaturką z powodu usunięcia zdjęć, czego oczywiście nie chcę. 

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Na chwilę obecną zasoby /sale/offers oraz /sale/product-offers funkcjonują w pełni równolegle. Obie grupy zapewniają możliwość łączenia ofert z produktem, do czego w Allegro dążymy. Zasoby /sale/product-offers stworzyliśmy w odpowiedzi na potrzeby zgłaszane przez integratorów, który uznawali nasze dotychczasowe podejście za zbyt skomplikowanie, nie dające możliwości wystawienia ofert jednym requestem. Tym samym, w kontekście najbliższej przyszłości, co do której mogę się wypowiedzieć, obie grupy zasobów działają równolegle, aby realizowały potrzeby każdej z grup odbiorców.

**Comment by hahyes** [comment]
> Zasoby /sale/product-offers stworzyliśmy w odpowiedzi na potrzeby zgłaszane przez integratorów, który uznawali nasze dotychczasowe podejście za zbyt skomplikowanie, nie dające możliwości wystawienia ofert jednym requestem

W tym aspekcie pełna zgoda. Chętnie przeniósłbym się już częściowo na nowy zasób bo ogranicza on ilość wykonywanych zapytań, gdyby nie ww. fakt ze zdjęciami, co nieco komplikuje mi sprawę. No nic, dziękuję za odpowiedź. Będę musiał sobie poradzić we własnym zakresie.
