### ISSUE TITLE
Naliczanie kosztów dostawy dla aukcji kupionej przez użytkownika Allegro Smart

### ISSUE THREAD

**Issue by midzikowski** [allegro/allegro-api#548]
Problem z aukcją z kosztam dostawy metody biorącej udział w allegro smart.

Koszt w aukcji ustawiony na 8,99
Produkt kupuje klient biorący udział w programie Allegro Smart - koszty ma obniżone na 0
My dostajemy informacje o kosztach 8,99 w  [postBuyFormPostageAmount] a powinno być raczej 0
To samo w polu [postBuyFormAmount] - informacja jest z kosztami dostawy regularnymi

To chyba błąd ?

Pozdrawiam
Maciek

stdClass Object
(
    [postBuyFormData] => stdClass Object
        (
            [item] => stdClass Object
                (
                    [postBuyFormId] => XXXXXX
                    [postBuyFormItems] => stdClass Object
                        (
                            [item] => stdClass Object
                                (
                                    [postBuyFormItQuantity] => 1
                                    [postBuyFormItAmount] => 97
                                    [postBuyFormItId] => XXXXX
                                    [postBuyFormItTitle] => XXXX
                                    [postBuyFormItCountry] => 1
                                    [postBuyFormItPrice] => 0
                                    [postBuyFormItDeals] => stdClass Object
                                        (
                                            [item] => stdClass Object
                                                (
                                                    [dealId] => XXXX
                                                    [dealFinalPrice] => 97
                                                    [dealQuantity] => 1
                                                    [dealDate] => 2018-08-29T16:41:46+02:00
                                                    [dealWasDiscounted] => 
                                                    [dealVariant] => stdClass Object
                                                        (
                                                            [variantName] => 
                                                            [variantValue] => 
                                                        )

                                                )

                                        )

                                )

                        )

                    [postBuyFormBuyerId] => XXXX
                    [postBuyFormAmount] => 105.99
                    [postBuyFormPostageAmount] => 8.99
                    [postBuyFormInvoiceOption] => 0
                    [postBuyFormMsgToSeller] => 
                    [postBuyFormInvoiceData] => stdClass Object
                        (
                            [postBuyFormAdrCountry] => 0
                            [postBuyFormAdrStreet] => 
                            [postBuyFormAdrPostcode] => 
                            [postBuyFormAdrCity] => 
                            [postBuyFormAdrFullName] => 
                            [postBuyFormAdrCompany] => 
                            [postBuyFormAdrPhone] => 
                            [postBuyFormAdrNip] => 
                            [postBuyFormCreatedDate] => 
                            [postBuyFormAdrType] => 0
                        )

                    [postBuyFormShipmentId] => 10023
                    [postBuyFormGdAddress] => stdClass Object
                        (
                            [postBuyFormAdrCountry] => 1
                            [postBuyFormAdrStreet] => Grota-Roweckiego 76
                            [postBuyFormAdrPostcode] => 52-232
                            [postBuyFormAdrCity] => Wrocław
                            [postBuyFormAdrFullName] => Paczkomat WRO09N
                            [postBuyFormAdrCompany] => 
                            [postBuyFormAdrPhone] => 
                            [postBuyFormAdrNip] => 
                            [postBuyFormCreatedDate] => 2018-08-29 16:41:48
                            [postBuyFormAdrType] => 0
                            [postBuyFormAdrId] => WRO09N
                        )

)

**Comment by imper86** [comment]
Hm, ale jeśli klient ma wykupiony smart to przecież allegro pokrywa koszt dostawy, prawda? Więc w tym wypadku wszystko się zgadza, bo finalnie Ty jako sprzedający otrzymujesz pieniądze za transport.
Chyba, że źle rozumiem problem.

**Comment by midzikowski** [comment]
Klient kupuje u nas produkt za 100 zł. wysyłka powiedzmy 8 zł. Jest Smart więc dostaje darmową wysyłkę od Allegro. Więc allegro nam oddaje na wysyłkę - my ponosimy koszt - to jasne.
Ale do naszego systemu przechodzi informacja o tym że klient poniósł koszt 108 zł i taka faktura pójdzie do klienta z naszego systemu. 

A patrząc logicznie powinnismy mu wystawić fakturę na 100 zł bo kosztów transportu nie poniósł. 
Tak więc powinna być gdzieś informacja że nie powinniśmy fakturować klienta na 108 zł tylko na 100 wg mojego rozumienia

**Comment by KrzysztofLukanowski** [comment]
Wartość w polu z kosztem dostawy odpowiada cenie wysyłki, jaka była w ofercie. Niestety nie mamy uprawnienia do udzielania porad w zakresie indywidualnych rozliczeń podatkowych. W naszym przekonaniu transakcja powinna zostać udokumentowana zgodnie z jej rzeczywistym przebiegiem. Co do zasady sprzedający powinni wykazać całkowitą sprzedaż jaką dokonali i za jaką otrzymali należne wynagrodzenie.

**Comment by martacronic** [comment]
Wydaje mi się, że wątpliwości @midzikowski są jak najbardziej uzasadnione. 
Kupujący kupuje towar, ale przesyłkę "kupuje" już Allegro. Zatem udokumentowanie z rzeczywistym przebiegiem jest następujące:
1. Kupującemu należy się paragon/faktura za przedmiot od Sprzedającego.
2. Allegro należy się paragon/faktura za przesyłkę od Sprzedającego.
3. Kupującemu raz do roku należy się paragon/faktura za opłatę Allegro Smart od Allegro.

Jeśli z jednej strony ktoś zapłaci z konta 100 zł, a z drugiej dostaje paragon 108 zł to prędzej czy później będą z tego problemy.

Dodanie informacji o objęciu zamówienia Allegro Smart wydaje się zarówno zasadne jak i potrzebne niezwłocznie, bo usługa już działa.

**Comment by KrzysztofLukanowski** [comment]
Sprawdzamy różne podejścia. Wasze propozycje przekazaliśmy już do osób decyzyjnych.

**Comment by dlis2010** [comment]
@KrzysztofLukanowski 
Odkopię troszku temat.

Jako kupujący kupuję 365 towarów od różnych sprzedawców (każdy powyżej 40zł).
Opłacam zakup, wybybieram wysyłkę (metoda wysyłki dostępna w SMART).
Każdorazowo koszt wysyłki mam rekompensowany przez SMART'a.
Po opłaceniu transakcji wysyłam do każdego sprzedającego odstąpienie od umowy wraz z żądaniem zwrotu środków za towar oraz za przesyłkę (zwrot kosztów najtańszej przesyłki zgodnie z prawem).
Każdy sprzedający zgodnie z prawem realizuje zwrot środków, a ja odzyskuje środki zarówno za towar jak i 365 razy koszt wysyłki...
W przypadku wyboru paczkomatu to łącznie 3281,35zł inwestując 49zł

Kupujący zyskuje, sprzedający nic nie traci.
Cała strata jest po Waszej stronie, jesteście zabezpieczeni na powyższą sytuacje?

Widzę, że w odstąpieniu od transakcji realizowanej przez kupującego **za pomocą zwrotów Allegro** **sprzedający dostanie informacje aby nie zwracać za wysyłkę**. Niestety tylko w tym wypadku, a możliwości odstąpienia jest pełno (papierowa, mailowa, telefoniczna...)

**Comment by TomekKaczmarek** [comment]
@dlis2010 https://allegro.pl/pomoc/faq/czy-w-przypadku-odstapienia-od-umowy-musze-zwrocic-koszty-wysylki-kupujacemu-jesli-ten-skorzystal-z-allegro-smart-z8D7Dvzxwho

1/ Kiedy kupujący wypełni formularz odstąpienia od umowy na jego koncie Allegro, wyślemy do sprzedawcy powiadomienie. Znajdzie w nim informację, czy Klient skorzystał z dostawy Allegro Smart! W takim przypadku nie musi zwracać pieniędzy za koszt dostawy.

2/ Jeśli sprzedawca zwrócisz pieniądze za przedmioty przez Allegro Finanse, to proces przebiegnie automatycznie - kupujący otrzyma tylko kwotę odpowiadającą wartości zakupionych przedmiotów.

**Comment by KrzysztofLukanowski** [comment]
Na bieżąco monitorujemy sytuację. Zapewniam, że mamy odpowiednie mechanizmy, ale nie mogę zdradzić szczegółów.

**Comment by mack3d** [comment]
Jeszcze jedno pytanie, czy klient korzystający z usługi smart ma możliwośc oceny kosztów wysyłki.

**Comment by KrzysztofLukanowski** [comment]
Jeżeli klient w takim zamówieniu zaznaczy mniej niż 5 gwiazdek, wyświetlimy komunikat _Wybrałeś dla tej transakcji opcję darmowej wysyłki, więc nie możesz wystawić oceny niższej niż 5._

**Comment by Zbigniew-L** [comment]
Szanowni Państwo,

wspomniany problem związany z wystawianiem faktur jest bardzo istotny, mamy już kilka zgłoszeń od klientów, którzy otrzymali od nas faktury na kwoty INNE niż faktycznie opuściły ich konto bankowe, taka sytuacja jest nie do zaakceptowania na dłuższą metę, bo po stronie naszych klientów powstaje informacja, że mają nieopłacone do końca faktury

sama informacja smart = true/false może nie zawsze zadziałać, z naszych doświadczeń wynika gdy klientowi naliczą się np. 4 paczkomaty (towar duży gabarytowo) to allegro Smart POKRYWA WSZYSTKIE paczkomaty! (a nie np. tylko jeden!)

nie mając informacji ile faktycznie przelewają nasi klienci nie mamy jak wystawić im faktury vat, a w naszej branży akurat głównie kupują biznesowi więc mamy teraz duży problem...

może allegro smart powinno wysyłać jakąś automatycznie wygenerowaną notę księgową, którą kupujący mógłby zbilansować różnicę w fakturze?

czyli:

stan obecny:

klinet kupuje towar za 46,45zł
doliczają mu się 3 szt paczkomatów na kwotę łączną 26,97
paczkomaty są zerowane przez Allegro Smart więc klient wpłaca nam 46,45 (przez PayU) (czy to nie błąd, że pokrywacie więcej niż jeden paczkomat w jednej transakcji?)

my wystawiamy obecnie fakturę na 73,42zł (towar + paczkomaty) - bo nie wiemy czy klient w ogóle korzystał z Allegro Smart...

klient po otrzymaniu faktury pisze do nas, że musimy skorygować fakturę bo jest niepoprawna... i mamy sporo więcej pracy

Allegro powinno wystawić do naszego klienta jakiś dokument (notę księgową/cesji, itp?) potwierdzającą, że Allegro zapłaciło dla sprzedawcy 26,97 - nota mogłaby wyzerować bilans płatniczy - ale co z rozliczeniem VAT itp?

wydaje się, że obecna sytuacja powoduje spore zamieszanie w rozliczeniach między firmami.... chyba w Allegro nie wzięliście tego pod uwagę uruchamiając usługę?

czy w ogóle będziemy mogli liczyć na pomoc w rozsądnym czasie?

pozdrawiam,
Z. Ł.

**Comment by KrzysztofLukanowski** [comment]
W przypadku zakupu z Allegro Smart! pokrywamy maksymalnie 40 zł kosztów przesyłki, jeżeli w zamówieniu znajdą się przedmioty z kilku różnych ofert - oczywiście przy założeniu, że cena wysyłki pierwszego przedmiotu nie przekracza progu wskazanego w naszych [wymaganiach](https://allegro.pl/pomoc/faq/metody-dostawy-i-zwrotu-paczek-w-ramach-allegro-smart-PDajRan67t1). 

Nie udzielamy porad w kwestii rozliczeń podatkowych. Ta sprawa powinna zostać wyjaśniona pomiędzy Państwem.

**Comment by mack3d** [comment]
Panie @KrzysztofLukanowski sprawa jest prosta, wystarczy dać informację sprzedającemu kto jest płatnikiem kosztów wysyłki.

**Comment by Zbigniew-L** [comment]
Szanowni Państwo z Allegro - czy naprawdę nie widzicie problemu? Potrzebujemy aby API podawało nam kwotę jaką płaci klient i/lub kwotę pokrytą przez Allegro - bez tej informacji nie możemy wystawić naszym klientom prawidłowych faktur, nie wiem jak inaczej mam to wyjaśnić?

Napisałem powyżej przykład jak to wygląda proszę raz jeszcze się z nim zapoznać - w skrócie klient płaci nam 46,45 więc chce fakturę na taką kwotę a nie na kwotę 73,42 zł! Skąd mamy wiedzieć, że skorzystał z Allegro Smart skoro nie udostępniacie nam tych informacji?

To nie jest "kwestia rozliczeń podatkowych do wyjaśnienia z kupującym" tylko kwestia, że nie podajecie nam prawidłowej kwoty transakcji na którą mamy wystawić faktury dla naszych klientów.

**Comment by KrzysztofLukanowski** [comment]
Zapewniam Państwa, że dostrzegamy problemy, z jakimi spotykają się nasi sprzedający. Pracujemy już nad tym, aby proces obsługi zamówień z Allegro Smart! był łatwiejszy.

**Comment by KrzysztofLukanowski** [comment]
Już wkrótce będziemy oznaczać zamówienia Allegro Smart! Tymczasem zachęcam do lektury artykułu [Jak rozliczać sprzedaż i zakupy w programie Allegro Smart!?](http://grantthornton.pl/publikacja/jak-rozliczac-sprzedaz-i-zakupy-w-programie-allegro-smart/)

**Comment by 1zp1zp** [comment]
Zwrot kosztów reguluje ustawa. Sprzedawca zwraca najtańszą opcję wysyłki.
Grant Thornton to nie Sejm, nie zmieni ustawy. Ponawiam pytanie jeżeli w
ciągu roku zakupie towar Smart tylko jeden raz to koszt tej przesyłki ile
wyniesie? Zero - nic bo SMART czy 49 zł. Czyli sprzedawca zwróci mi 49zł?

wt., 16 paź 2018 o 08:14 KrzysztofLukanowski <notifications@github.com>
napisał(a):

**Comment by TimothyKoval** [comment]
@1zp1zp Kupiłeś samochód za 100k palący 10l/100km. Zatankowałeś 10l za 50 zł, wszystko wyjeździłeś i samochód sprzedałeś. Samochód pali wobec tego 50zł/100km czy 100050zł/100km?

**Comment by 1zp1zp** [comment]
Ja nie pytałem ile pali. Pali 10 litrów.
A jak kupiłem i nie jeździłem - popatrzyłem - brzydki ten kolor ;) - oddam
to ile pali na 100 km?
Czyli twierdzisz - kupiłem za 100k. Skoro przejechałem 100 km za 50 zł
(moje własne) to Ty rozumujesz, że sprzedający zwróci mi  99 950 zł bo 50
wyjeździłem?
Ale idąc Twoim rozumowaniem to sprzedałem samochód za 120 k - toż to
perpetum mobile - jeździł i oddał pieniądze za benzynę z taką nawiązką.
Kompletny brak logiki.
Dobrze się czujesz?

wt., 16 paź 2018 o 14:50 TimothyKoval <notifications@github.com> napisał(a):

**Comment by KrzysztofLukanowski** [comment]
To sprzedający ustala koszt wysyłki, a jeżeli ten mieści się w odpowiednich widełkach cenowych, klienci Smarta nie zapłacą za dostawę. Nawet w przypadku, gdy klient ze Smartem, przeprowadzi jedną taką transakcją, dla niego koszt wysyłki wyniesie 0 zł, dla jego kontrahenta zgodnie z ustalonym cennikiem.

**Comment by TimothyKoval** [comment]
@1zp1zp Po pierwsze - zmień ton. Po drugie - wykupienie usługi Smart nie jest kosztem wysyłki ani żadną opłatą związaną z jakąkolwiek inną transakcją. Tak jak zakup paliwa nie ma się nijak do zakupu samochodu.

**Comment by 1zp1zp** [comment]
Tykać to możesz do syna jak Ci pozwoli.
Kupiłem samochód i przywieziony został lawetą - to przewóz darmo?
Co ma do tego samochód i benzyna?
Co Ty  masz tylko rower i marzysz o samochodzie, że tak owijasz?
Co ma piernik do wiatraka?
Benzyna w samochodzie to przesyłka?
A może jeszcze dziwka do użytku w tym samochodzie?
Lecz się i nie pisz do mnie bo tworzysz gościu jakieś historie.
Jest zakup jest koszt przesyłki.
Jak bym nie miał Smarta to też napiszesz, że przesyłka nie ma znaczenia tak
jak benzyna.
Ogarnij się albo do przedszkola na panel dyskusyjny!

czw., 18 paź 2018 o 11:30 TimothyKoval <notifications@github.com>
napisał(a):
