### ISSUE TITLE
Allegro One Box, zielony automat - Receiver point is incorrect

### ISSUE THREAD

**Issue by JederKlisiajtys** [allegro/allegro-api#5480]
REST API 
Środowisko - Sandbox 

Przy nadaniu paczki do zielonego automatu Allegro(przykładowo **AL103KR1**) , po wywołaniu metody 
GET **parcel-management/parcel-create-commands/{ID}** 
Orzymuję błąd: 
```
{
            "code": "ERROR",
            "message": "Receiver point is incorrect",
            "details": null,
            "path": "receiver.pointId",
            "userMessage": "Punkt odbiorcy jest niepoprawny"
 }
```
Problem występuje przy próbie nadania do zielonych Automatów Allegro, nie występuje natomiast przy próbie nadania do Allegro One Punkt (przykładowo **A004147**)

Korzystam z delivery-service takiego jak poniżej:
```
 {
            "id": 9472142,
            "service": "ALLEGRO",
            "name": "Allegro One",
            "owner": "ALLEGRO",
            "carrierId": "ALLEGRO",
            "additionalServices": {
                "cashOnDelivery": {
                    "available": false,
                    "expressAvailable": false
                },
                "options": []
            }
        }
```

Ponadto odpowiedź z metody **order/carriers/ALLEGRO/points**  nie zawiera żadnych zielonych automatów
Czy proces nadawania przesyłki do zielonych automatów odbywa się w jakiś inny sposób? 
Czy Api tych zielonych automatów jeszcze nie obsługuje?

EDIT
Możliwe jest że api sandboxowe nie obsługuje jeszcze istniejących zielonych automatów, jednak zwróciło mi taki automat testowy **"id": "TEST-AL-LUB-2",**, (na którym wszystko działa poprawnie) nie wiem czy na api produkcyjnym zwraca już wszystkie działające automaty póki nie dostałem jeszcze do niego dostępu

**Comment by MaciejFrackowiak** [comment]
Lista punktów oraz dostępnych usług w ramach Wysyłam z Allegro na Sandbox występuje w skróconej wersji tzn. dostępna jest tylko pewna liczba puntków i usług, która w żadym stopniu nie musi pokrywać się z produkcyjną listą. Tym samym trafiłeś na punkt stricte testowy, który został stworzony na potrzeby Sandbox ("id": "TEST-AL-LUB-2").
