### ISSUE TITLE
Jak poprawnie wypełnić parametr 203093 - błąd przy tworzeniu produktu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5481]
Witam,

mam szybkie pytanie. 
Jak poprawnie powinienem wypełnić parametr 203093 tworząc produkt jak w zapytaniu o trace-id 40e4f9e81720ac58?
Mam gdzieś buga i nie mogę się go doszukać.

Pozdrawiam.

**Comment by Lukasz-Zurek** [comment]
Przyznam, że dziwna sytuacja. Przekazujesz:

```
      {
         "id": "203093",
         "valuesIds": [],
         "values": [
            "25.00"
         ]
      }
```

Natomiast jak prześlesz request bez `"valuesIds": [],` dla tego parametru, czyli:

```
      {
         "id": "203093",
         "values": [
            "25.00"
         ]
      }
```

Żądanie powinno przejść prawidłowo.

Skonsultuję jeszcze Twoje zgłoszenie z odpowiednim zespołem.

**Comment by Lukasz-Zurek** [comment]
Jeżeli wybrany przez Ciebie parametr nie jest parametrem słownikowym - w polu **"valuesIds"**, w requeście musisz przekazać wartość **null**. Ewentualnie nie przekazuj tego pola. W przeciwnym razie zwrócimy Tobie błąd, o którym mowa w wątku.

**Comment by hahyes** [comment]
> Jeżeli wybrany przez Ciebie parametr nie jest parametrem słownikowym - w polu **"valuesIds"**, w requeście musisz przekazać wartość **null**. Ewentualnie nie przekazuj tego pola. W przeciwnym razie zwrócimy Tobie błąd, o którym mowa w wątku.

Już to wprowadziłem po wczorajszym poście i zadziałało. Dziękuję bardzo za pomoc.
