### ISSUE TITLE
"userMessage":"Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#5483]
Dzień dobry.
W odpowiedzi na request "id":"ade3b72a-74fb-440d-a299-b628d689469d"
otrzymałem: {"id":"ade3b72a-74fb-440d-a299-b628d689469d","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"\"Inne dane na etykiecie\" not supporter for carrier","details":null,"path":"/sender","userMessage":"Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"}]}

Poproszę o wyjaśnienie jaka informacja konkretnie przeszkadza w wygenerowaniu etykiety?

**Comment by MaciejFrackowiak** [comment]
Niektórzy przewoźnicy nie dają możliwiości umieszczania innych danych na etykiecie aniżeli dane nadawcy. W tym przypadku w polu "label" przekaż wartość null.

**Comment by cemsgh** [comment]
Wypełniłem pole label ponieważ w systemie allegro w polu nadawcy pojawiły się dane odbiorcy.
Przykładowa przesyłka nr ref. E677F9AF-AD65-4F16-9724-88EEDFE6D z tym problemem.

**Comment by MaciejFrackowiak** [comment]
Jeżeli opisany problem pojawił się na stronie WWW to proszę skontaktuj się bezpośrednio ze wsparciem poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5) i opisz swoje spostrzeżenie.
