### ISSUE TITLE
Witam, w panelu admin na koncie nie ma ikonki klucz web API. Prośab o poadnie klucza do integracji ze sklepem www Mój login  sklep@cedrom.pl  Sprawa pilna

### ISSUE THREAD

**Issue by JerzyOstapiuk** [allegro/allegro-api#5485]

**Comment by MaciejFrackowiak** [comment]
Klucz (Client_ID i Client_secret) możesz wygenerować we własnym zakresie rejestrując aplikację na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/).

**Comment by JerzyOstapiuk** [comment]
Witam,

 

Bym zintegrował w panelu admin sklepu www produkty z allegro potrzebuje klucza API

Dodałem nowa aplikację do Developer apps i mam takie dane:

Klucze aplikacyjne REST API

Nazwa aplikacj API axodkurzacze.pl

Typ Client ID 590f6c3f31ef4883a3002041fc138aa9

Client Secret QiqSy6kXSM9vLtxTD78j1Tjiew21htb3j48gp2SjpYzdDfZ8eJoqt1oCskj4YuuF

Adresy przekierowań https://axodkurzacze.pl

 

Który to jest klucz API ?

Pzdr

Jerzy Ostapiuk

**Comment by MaciejFrackowiak** [comment]
Client Secret to wartość klucza.

Na przyszłość proszę nie podawaj tych wartości (Client ID i Client Secret) w publicznych postach.

**Comment by JerzyOstapiuk** [comment]
Który numer to klucz API 

Typ Client ID ..... ?

Client Secret….. ?

 

Pzdr

Jerzy Ostapiuk

**Comment by JerzyOstapiuk** [comment]
Jak wpr do sklepu ten klucz to mam błąd komunikacji – screean załącznik

Kiedyś miałem bardzo krótki klucz API teraz mam bardzo długi nr.

 

Prośba o pomoc

 

Pzdr

Jerzy Ostapiuk

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście, przy WebAPI klucz miał długość zaledwie kilku znaków.
Obecnie, w REST API musisz podać zarówno Client ID, które identyfikuje zarejestrowaną aplikację oraz Client Secret, czyli klucz-hasło dla tej wskazanej aplikacji.

Jeżeli masz problem z obsługą swojego sklepu, proszę skontaktuj się z dostawcą oprogramowania, aby ten udzielił Tobie niezbędnych wskazówek.
