### ISSUE TITLE
Sandbox: Status zamówienia nie aktualizuje się

### ISSUE THREAD

**Issue by maqlec** [allegro/allegro-api#5486]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Status zamówienia nie aktualizuje się**

Zgodnie z dokumentacją apropo aktualizacji statusu: https://developer.allegro.pl/orders/#zmiana-statusu-realizacji-zam%C3%B3wienia .
Wykonuje request aktualizacji statusu na adres PUT https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/b52e28e1-957b-11ec-a17e-e9a638140512 z body: 
{"status": "SENT"}
następnie sprawdzam status zamówienia poprzez GET https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms/b52e28e1-957b-11ec-a17e-e9a638140512 i w body otrzymuje taki wynik apropo statusów:
![image](https://user-images.githubusercontent.com/13941930/155572971-5f66aec4-8a98-48c8-ab8f-2a74c6cd8a9f.png)

Czyli zmienił się status fullfillmentu ale nie samego zamówienia. Nie wiem skąd to wynika i czy tak samo zachowuje się środowisko produkcyjne ale zgłaszam jako bug do sprawdzenia dlaczego tak się dzieje. W dokumentacji jest to jedyny sposób na zmianę statusu. Próbowałem jeszcze włączyć w ustawieniach konta automatyczną zmianę statusu przy zapisie shipmentu ale dla Sandboxa nie jest to możliwe.

**Comment by MaciejFrackowiak** [comment]
Zmienisz tylko status realizacji zamówienia (fulfillment.status), a nie status samego zamówienia. Jak widzimy na zrzucie status realizacji zamówienia zmienił się na SENT. Status zamówienia natomiast zmienia się wyłącznie pod wpływem działania ze strony kupującego - dostępne wartości: "BOUGHT", "FILLED_IN", "READY_FOR_PROCESSING", "CANCELLED".

**Comment by maqlec** [comment]
@MaciejFrackowiak a to bardzo ciekawe o czym wspominasz, nie byłem tego świadom. Myślałem że te statusy za sobą wędrują. W takim razie muszę troszeczkę inaczej podejść do tego tematu. Dziękuję.
