### ISSUE TITLE
testowanie wiadomości w środowisku sandbox, 2 użytkowników

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#5487]
Potrzebuję potestować przepływ wiadomości między użytkownikiem, a sprzedawcą, dotyczącymi konkretnej oferty.
Na ten moment mam jednego użytkownika sandboxowego.

Plan mam następujący.
1. Wystawić ofertę - ręcznie się nie da. Czyli można to zrobić na sandboxie jedynie przez api?
2. Stworzyć usera 2, rejestrując nowego użytkownika na https://allegro.pl.allegrosandbox.pl/rejestracja
3. Napisać wiadomosc przez usera 2 do wystawionej oferty usera 1.
4. Odpisac userowi 2 jakąś wiadomością.

Czy ten plan jest realny? Głównie chodzi mi o to czy 2 różne konta na sandboxie mogą do siebie pisać? Czy to raczej 2 konta na "niezależnych środowiskach"?

**Comment by MaciejFrackowiak** [comment]
Skorzystaj proszę z odnośnika: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, aby wystawić ofertę poprzez formularz na Sandbox.
Oczywiście możesz założyć drugie konto na Sandbox i testować zasoby Centrum wiadomości - wysyłanie i odbieranie wiadomości działa prawidłowo.

**Comment by uranity** [comment]
Próbowałem wiele razy wystawić przez https://allegro.pl.allegrosandbox.pl/offer/?lokalnie, ale za każdym razem pojawia się (po wybraniu produktu) komunikat:
"Nie udało się utworzyć oferty dla wybranego produktu."

**Comment by MaciejFrackowiak** [comment]
Podaj proszę login swojego konta na Sandbox.

**Comment by uranity** [comment]
> Podaj proszę login swojego konta na Sandbox.

Client:94611569

**Comment by MaciejFrackowiak** [comment]
Tak jak podejrzewałem, Twoje konto nie było aktywne, a do tego nie uzupełniłeś żadnych danych konta. Ze swojej strony konto aktywowałem, ale musisz jeszcze uzupełnić dane - oczywiście podaj fikcyjne.

**Comment by uranity** [comment]
Dziękuję. Już mogę wystawiać oferty.
