### ISSUE TITLE
Błędy płatności na środowisku sandbox

### ISSUE THREAD

**Issue by mdxkom** [allegro/allegro-api#5488]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Na środowisku testowym. w koszyku zamówienia:

Nie ma dostępnej metody płatności BLIK
Metoda płatności Przelew kończy się niepowodzeniem
Metoda płatności Karta płatnicza jest nieaktywna

**Comment by MaciejFrackowiak** [comment]
Operator płatności, który dostarcza rozwiązanie w dniu dzisiejszym prowadzi prace techniczne - efektem tego są zauważone przez Ciebie niedogodności. Planowane zakończenie prac ma mieć miejsce do końca dzisiejszego dnia. Przepraszam za utrudnienia.
