### ISSUE TITLE
Zmiany dla konta me_DevUser

### ISSUE THREAD

**Issue by jaroslaw-debski-terg** [allegro/allegro-api#5489]
Prośba o dokonanie 2 zmian dla konta me_DevUser:

- podczas wystawiania aukcji w response api mamy info: "Tax may be filled only if you have company account." - proszę by zmienić to konto na firmowe,
- potrzebujemy też pełnej aktywacji konta

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już aktywne, ponadto zostało zweryfikowane jako firmowe.

**Comment by jaroslaw-debski-terg** [comment]
Dziękuję.
