### ISSUE TITLE
Mam dziwne zjawisko przy zmianie cen PUT sale/offer-price-change-commands

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5490]
Witam,
Napisałem sobie skrypt który grupuje oferty wg nowych cen i stara się je nanieść na istniejące oferty allegro.
Problem polega na tym, że czasem mu się to nie udaje o czym nie raczy wspomnieć.
Nie wiem gdzie leży problem. (czyżby zły nagłówek?)
 
Oto przykład:
Próbuję nadać cenę:
curl_exec(https://allegroapi.io/sale/offer-price-change-commands/16744a1f-0d64-3481-9136-205b916a7e63Array
(
    [0] => Content-Type: application/vnd.allegro.public.v1+json
    [1] => Accept: application/vnd.allegro.public.v1+json
)
PUT{"modification":{"type":"FIXED_PRICE","price":{"amount":"82.0","currency":"PLN"}},"offerCriteria":[{"type":"CONTAINS_OFFERS","offers":[{"id":"10746159497"}]}]}):{"id":"16744a1f-0d64-3481-9136-205b916a7e63","taskCount":{"total":0,"success":0,"failed":0}}

I sprawdzenie czy napewno wszystko jest ok:
curl_exec(https://allegroapi.io/sale/offer-price-change-commands/16744a1f-0d64-3481-9136-205b916a7e63/tasksArray
(
    [0] => Content-Type: application/vnd.allegro.public.v1+json
    [1] => Accept: application/vnd.allegro.public.v1+json
)
GETArray):{"tasks":[{"offer":{"id":"10746159497"},"message":null,"status":"NEW","scheduledAt":"2022-02-25T10:06:16.105Z","finishedAt":null,"field":"price","errors":[]}]}

Ale kiedy na drugim serwerze odpalam to sprawdzenie, dostaję:
sale/offer-price-change-commands/16744a1f-0d64-3481-9136-205b916a7e63

Array
(
    [id] => 16744a1f-0d64-3481-9136-205b916a7e63
    [taskCount] => Array
        (
            [total] => 1
            [success] => 0
            [failed] => 1
        )

)
Array
(
    [action] => execute
)
Array
(
    [request] => sale/offer-price-change-commands/16744a1f-0d64-3481-9136-205b916a7e63
)

Wiem dlaczego mu się nie udaje bo /task'iem na drugim komputerze dostaję informacje.

Ale nie wiem dlaczego 'za pierwszym razem', w głównej pętli skryptu nie zwraca odpowiedniego komunikatu.

**Comment by Lukasz-Zurek** [comment]
Wskazany zasób działa asynchronicznie, dlatego do momentu rozpoczęcia przetwarzania pokazujemy wartość 0. Dopiero po chwili pojawią się właściwe liczby ofert do przetworzenia.

Z tego co widzę - najpierw skorzystałeś z [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT) i w odpowiedzi otrzymałeś:

```
{
    "id": "{commandId}",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}

```
Następnie sprawdziłeś szczegółowy status za pomocą [GET /sale/offer-price-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET). Dzięki temu otrzymałeś więcej informacji, o których wspomniałeś:

`{"tasks":[{"offer":{"id":"10746159497"},"message":null,"status":"NEW","scheduledAt":"2022-02-25T10:06:16.105Z","finishedAt":null,"field":"price","errors":[]}]}
`

Następnie sprawdzałeś podstawowy status za pomocą [GET /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandStatusUsingGET), gdzie powyższe liczby zostały już zaktualizowane i w odpowiedzi otrzymałeś:

```
{
    "id": "{commandId}",
    "taskCount": {
        "total": 1,
        "success": 1,
        "failed": 0
    }
}
```
