### ISSUE TITLE
Event o złożeniu oferty, której nie było

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#5492]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

`https://api.allegro.pl/sale/offer-events?from=MTY0NTk2MTkzNjUxMTE2OQ&limit=100 `

5c7224c31014a7f8

Mam problem z pobieraniem eventów. Dostaję informację o evencie: OFFER_BID_PLACED, który w rzeczywistości nie miał miejsca (nie ma żadnego śladu na allegro.pl (w złożonych ofertach), ani na mailu, że np. ktoś złożył, ale anulował oferte). Nasz system bazuje na tych eventach i każda taka sytuacja powoduje sporo komplikacji.

**Comment by MartaNowaczyk** [comment]
Z tego co widzę w ofercie z podanego przez Ciebie zakresu wyszukiwania eventów z typem OFFER_BID_PLACED ma złożoną ofertę kupna. Zamówienie jest już nawet opłacone. 
Jeśli masz jeszcze jakieś problemy z jakimś eventem podaj proszę jego offerEvents.id.

**Comment by mrezlik** [comment]
Teraz już tak, ale chodzi mi konkretnie o daną godzinę. Bo to, że później była oferta to wiem i już jest poprawnie zarejestrowana. Oto offerEvents.id o który mi chodzi: `MTY0NTk2MTkzODEwMjcwNQ`

**Comment by MartaNowaczyk** [comment]
Właśnie w tym momencie - event o id `MTY0NTk2MTkzODEwMjcwNQ` nastąpiło złożenie oferty w licytacji, potem pojawiły się kolejne eventy OFFER_BID_PLACED dla tej oferty, bo ten sam kupujący 7 razy składał ofertę kupna. Nie widzę problemu tutaj po stronie API.
