### ISSUE TITLE
Obowiązkowy EAN podczas wystawiania produktu?

### ISSUE THREAD

**Issue by Pawiel** [allegro/allegro-api#5495]
Dobry wieczór.

Podczas próby wystawienia przedmiotu w BaseLinker pojawia się błąd:

KINGSTON 8GB RAM PC4-3200MHz CL22 MSI32D4S2S1ME-8: error occurred auctions listing (komunikat błędu w tabeli pod danym produktem) Wystąpił błąd podczas wystawiania oferty: Uzupełnij parametry obowiązkowe: EAN. (VALIDATION_ERROR parameters)

Nie mogę wystawić aukcji, pomimo, że ten parametr nie jest obowiązkowy w Allegro. Allegro nie wymaga tego parametru w każdej aukcji, a jedynie w 40% wszystkich aukcji w dziale Elektronika i jak wystawiam aukcję bezpośrednio w formularzu Allegro, ten parametr nie jest wymagany.

Twórcy BaseLinkera twierdzą, że to problem po stronie Allegro, czy to prawda?

Z góry dziękuję za informację.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, sprawdzimy opisaną sytuację, ale podeślij proszę logi do weryfikacji, które otrzymasz od Baselinkera. Podeślij je przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) z informacją, że dotyczy wątku 5495 na Git Hubie.

**Comment by Pawiel** [comment]
W załączniku przesyłam zrzut ekranu z problemem.

W którym miejscu BaseLinkera istnieje możliwość pobrania logów?

![EAN](https://user-images.githubusercontent.com/100620555/156124773-c82e495c-d082-4e50-9762-e57016aed989.jpg)

**Comment by MartaNowaczyk** [comment]
Z tego co widzę na zrzucie masz wybrany stan `Nowy`. W tej kategorii parametr EAN jest zależny od parametru stan Jeśli wybierzesz stan `Nowy`, to parametr `EAN` jest obowiązkowy niezależnie od tego czy wystawiasz przez formularz czy przez zewnętrzną aplikację. W tej sytuacji musisz uzupełnić ten parametr.

**Comment by Pawiel** [comment]
Bardzo dziękuję, wygląda na to, że temat wyjaśniony. :-)
