### ISSUE TITLE
Allegro wysyłam - wieczny status InProgress

### ISSUE THREAD

**Issue by Desseres** [allegro/allegro-api#5496]
Czy API Wysyłam z Allegro działa poprawnie? 
Dziś od rana każde zlecenie dla przewoźnika UPS jest w wiecznym statusie IN_PROGRESS
Przesyłam dane listu przewozowego i sprawdzając status nie otrzymuję ParcelId. Tworzenie listów przewozowych z poziomu https://wysylam.allegro.pl/ działa poprawnie. 

Request UUID: b17f8f7b-9191-4f28-8528-8f6891978fa3
https://api.allegro.pl/parcel-management/parcel-create-commands/b17f8f7b-9191-4f28-8528-8f6891978fa3

Request UUID: d93bf9dc-8f3f-4cad-90f0-8e58c7d45b18
https://api.allegro.pl/parcel-management/parcel-create-commands/d93bf9dc-8f3f-4cad-90f0-8e58c7d45b18

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Sprawdzamy co jest przyczyną. Dam znać jak tylko uda nam się coś ustalić.

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować. Ze swojej strony przepraszamy za niedogodności.
