### ISSUE TITLE
Projekt z 2012 - nic nie działa oprócz logowania.

### ISSUE THREAD

**Issue by JackShalom** [allegro/allegro-api#55]
Witajcie.
W 2012 napisałem program do importu danych z Allegro.
Przez kilka lat był nieużywany aż do dzisiaj.
uruchamiam, a tu zonk - nic oprócz logowania nie działa.
Chcę pobrać aukcje za pomocą 'doGetUserItems' i kicha.
Muszę wszystko od nowa napisać?

**Comment by sqlldev** [comment]
Od 2012 w webapi zmieniło się tyle, że pewnie najlepszym rozwiązaniem będzie napisanie tego od nowa.

**Comment by JackShalom** [comment]
To mnie nie pocieszyłeś.

**Comment by JackShalom** [comment]
No to licho.
Masz może pomysł, dlaczego w tym przykładzie mam 0, a powinno być kilka?

Public Sub PobierzAukcje(ByRef Sesja As String)
        Dim Aukcje(100) As Long
        Dim i As Integer
        Dim Allegro As New SR.AllegroWebApiPortTypeClient
        i = Allegro.doMyAccountItemsCount(Sesja, "sold", Aukcje)
        MsgBox(i)
    End Sub

**Comment by sqlldev** [comment]
Nie wiem, nie znam niestety VB ale problem może leżeć gdzieś wyżej. Allegro dość często coś dodaje, usuwa. Przez co zapewne jakieś metody w twoim programie mogą być już nieaktualne. Na twoim miejscu usiadłbym do tego od zera. Wydaje mi się, że będzie to łatwiejsze i szybsze niż próba wprowadzania zmian w starym kodzie.

**Comment by DINK74** [comment]
To ślepy strzał, ale jeśli podajesz pustą tablicę Aukcje, która ma robić za filtr w tej metodzie to dostajesz pusty zbiór bo żaden numer aukcji z sekcji "sold" nie należy do zbioru pustego ("Możliwe jest także pobranie informacji o liczbie ofert znajdujących się we wskazanej zakładce, z listy przekazanej w itemsArray.")
Spróbuj dodać do tablicy poprawny numer aukcji z sekcji "sold" lub po prostu dać null, nothing czy co tam jest w VBA.

**Comment by JackShalom** [comment]
Masz rację.
Myślałem, że ta metoda zwróci mi w tablicy 'Aukcje' identyfikatory aukcji.
Która z metod zwróci mi identyfikatory moich aukcji?
Chodzi o to, że w starym programie najpierw pobierałem moje aukcje, potem sprzedaż i kontrahentów.

**Comment by DINK74** [comment]
[Tutaj](https://allegro.pl/webapi/documentation.php/theme/id,44) masz wszystkie metody do obsługi własnego konta.
Wygląda na to, że metoda [doGetMySellItems](https://allegro.pl/webapi/documentation.php/show/id,1202) jest tym czego potrzebujesz.

**Comment by JackShalom** [comment]
Dzięki, to jest to.

**Comment by JackShalom** [comment]
Zlecę napisanie programu do importu z Allegro do Akcesa.
Zainteresowanych proszę o kontakt na forum.
