### ISSUE TITLE
Błędy w dokumentacji do Rest Api - niekonsekwencja i bałagan.

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#550]
Szanowni Państwo,

w dokumentacji  dla metody /sale/offers/{offerId} jest napisane: 
prześlij bez zmian dane walidacyjne...
i cytuję dokładnie z waszej strony : 
----------------------------------------------------
validatedAt": "2018-04-06T09:29:47.544Z"
 },
    "createdAt": "2018-04-06T09:29:47Z",
    "updatedAt": "2018-04-06T09:29:47.544Z"
}
---------------------------------------------------
w odpowiedzi : BAD REQUEST.

idziemy dalej - poniżej na stronie macie napisane tak: 
--------------------------------------------------------------------------------------------------
  "validation": {
        "errors": [],                           --  informacje o ewentualnych błędach, 
                                                poinformujemy cię o tym jeśli na przykład podasz 
                                                niepoprawny numer ID cennika.
        "validatedAt": "2018-04-06T08:29:37.461Z"       -- informacje, kiedy odbyła się
                                                        ostatnia walidacja oferty
    },
    "createdAt": "2018-04-06T08:26:32Z",        -- wymagane, data utworzenia oferty
    "updatedAt": "2018-04-06T08:29:38.664Z"     -- wymagane, data ostatniej aktualizacji oferty
---------------------------------------------------------------------------------------------------

Jak widzę ktoś tu o czymś zapomniał ! opis jest błędny i niezgodny ze stanem faktycznym. Przeczy temu co napisaliście na stronie powyżej.
idziemy dalej - w dokumentacji do metod macie napisane tak: 
cytuję kawałek z sekcji request body:
---------------------------------------------------------------
  "updatedAt": "2018-08-30T12:15:54.800Z",
  "validation": {
    "errors": [
      {
        "code": "string",
        "details": "string",
        "message": "string",
        "path": "string",
        "userMessage": "string"
      }
    ],
    "validatedAt": "2018-08-30T12:15:54.800Z"
  }
-----------------------------------------------------------------
To już jest prawdziwe zaskoczenie. 
metodą prób i błędów udało się w końcu wygenerować poprawne zapytanie. Tak jak napisałem - metoda prób i błędów. Jako ciekawostkę dodam że metoda o której mowa działa również bez  parametrów walidacyjnych wbrew temu co jest napisane w dokumentacji. 

Gorąco pozdrawiamy zespół WWW Factory.

**Comment by MaciejPotepa** [comment]
Dzień dobry
@wwwfactory Dzięki za zwrócenie uwagi na niespójności w dokumentacji. Poprawimy je. 

Pozdrawiam
