### ISSUE TITLE
API implementation - Order and OrderStates Processes

### ISSUE THREAD

**Issue by mboes-nm** [allegro/allegro-api#5501]
Hello guys, we have a couple of questions regarding orders and orderstates processes.

1. Can the statuses "CANCELED", "BUYER_CANCELLED" or "AUTO_CANCELLED" happen after the order is "READY_FOR_PROCESSING" and we have imported it? According to the documentation "event “BUYER_CANCELLED” may appear before or after “READY_FOR_PROCESING”" and this may cause an issue because we could have already processed and started shipping the order. 
2. Does transferring a value of "PROCESSING" for the field “fulfillment.status” as soon as we receive the orders response ensure no customer cancellation/modification will occur?
3. For shipments, please ensure the flow below is correct:

- Update tracking number using  [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) 

- Update fulfilment status to  'SENT' using (in case no subscription is enabled) using PUT /order/checkout-forms/{id}/fulfillment

4. Sending shimpments using the call [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) has no option of adding a quantity. Is there a workaround to support partial line shipments?

5. Is it fine if we pass every single lineItemId in a separate call to [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) to be able to have separate tracking numbers or will this cause Allegro to automatically add the tracking number from the first call to all order lines as mentioned in [https://developer.allegro.pl/en/orders/#add-tracking-number-to-order?](https://developer.allegro.pl/en/orders/#add-tracking-number-to-order) According to [GET /order/checkout-forms/{id}/shipments,](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingGET) an order may have multiple shipments.
6. Is it mandatory to send the fulfilment statuses “READY_FOR_SHIPMENT”,“READY_FOR_PICKUP”, “PICKED UP” or can we just send 'PROCESSING' when we import and order and 'SENT' when shipment begins?
7. Regarding the point "if buyer makes two separate orders from the same seller and then combine them into one payment, you will retrieve a new event with new checkoutForm.id, previous checkoutForm.id will not be available anymore"..can this scenario happen after the order is "READY_FOR_PROCESSING"? (ref: Note section in [https://developer.allegro.pl/en/orders/#event-log)](https://developer.allegro.pl/en/orders/#event-log)
8. We can' find an endpoint for seller cancellations. Does this mean that not sending a certain lineItemId in the call [POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST) indicates that this line is cancelled?
9. Is there a way we could place test orders on our own products using sandbox or do the orders have to be created by Allegro?

Best regards & many thanks in advance,
Matthias Bös

**Comment by MaciejFrackowiak** [comment]
Here are the answers:

1. Yes, only BUYER_CANCELLED event can appear after READY_FOR_PROCESSING - there is a field checkoutForm.revision which helps to recognize if anything in the order has changed;
2. Yes, when you change fulfillment.status to PROCESSING, buyer is unable to cancel an order;
3. Yes, it is a correct flow;
4. No, you can only add another shipment number;
5. We will add tracking numbers to all of the order items;
6. No, it is not mandatory. You can add any fulfillment.status as you want;
7. No, after READY_FOR_PROCESSING it is impossible;
8. Seller cannot cancel an order. If you do not send a tracking number, it will not mean that part of the order is cancelled;
9. You can create another Sandbox account which will allow you to buy items from the first account.

**Comment by MaciejFrackowiak** [comment]
@NahlaB Here are the next answers:

5. You are not able to change "fulfillment.shipmentSummary.lineItemsSent" field - we will do this automatically if you add tracking number to the order. Also "fulfillment.status" field you can change only for the whole order, not only for some parts. We will return every single tracking number for the buyer.
6. Here is only your decision which way do you prefer.

And for new questions:

1. There is no option to accept a customer return - if a buyer applies for this, you can only reject it if something is wrong with the returned item.
2. Customer can return a single item from the order or whole order - it depends on its decision.
3. You can use API resource and also for some cases we will do it automatically - please, check [Allegro Help](https://allegro.pl/help/for-sellers/fees-and-commissions/how-to-automatically-get-a-transaction-rebate-commission-refund-5L5vR7oOMia).

**Comment by NahlaB** [comment]
@MaciejFrackowiak 

- Regarding point 5: what do you mean by "We will return every single tracking number for the buyer."? Does this mean Allegro supports multiple tracking numbers per checkoutFormId (i.e: calling POST /order/checkout-forms/{id}/shipments multiple times for the same order using different line item ids and waybill values).

Thanks!

**Comment by Lukasz-Zurek** [comment]
@NahlaB 

Yes, Allegro supports multiple tracking numbers for one **"checkoutFormId"** (for one order). If you do not pass **"lineItem.id"** in your request, we will automatically assign a tracking number to each **"lineItem.id"** in your order. You can find more information in our [guide](https://developer.allegro.pl/en/orders/#how-to-add-tracking-number-to-an-item-in-order).

**Comment by lukeroot** [comment]
@MaciejFrackowiak I understand this is an old thread and might not reflect the current API functionality however just to bring up point 4 again- our company has been doing partial order ship/cancels by calling these endpoints in this order:


`/order/checkout-forms/{id}/fulfillment`
```json
{
  "status": "SENT",
    "shipmentSummary": {
      "lineItemsSent": "SOME"
    }
}
```

`/order/checkout-forms/{id}/shipments`

```json
{
  "carrierId": "string",
  "waybill": "string",
  "lineItems": [{}]
}
```

`/order/checkout-forms/{id}/fulfillment`
```json
{
  "status": "CANCELLED",
    "shipmentSummary": {
      "lineItemsSent": "SOME"
    }
}
```

`/payments/refunds/`
```json
{
  "payment": {
    "id": "string"
  },
  "reason": "string",
  "lineItems": [{
    "id": "string",
    "type": "QUANTITY",
    "quantity": "int"
  }]
}
```

Can you confirm that this is the current preferred method to action a partial refund on Allegro? Thanks

**Comment by MaciejFrackowiak** [comment]
@lukeroot We as Allegro do not specify how this process should go - it is up to you and your arrangements with the buyer. From the technical point of view, the described process is OK.
