### ISSUE TITLE
Błąd w dokumentacji (kod odpowiedzi OK)

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#5502]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

PUT /sale/user-ratings/{ratingId}/answer

JEST: 200 OK 
POWINNO BYĆ: 201 OK

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie, przekażę sprawę do właściwego zespołu.
