### ISSUE TITLE
Problem ze złożoną ofertą, /bidding/offers/

### ISSUE THREAD

**Issue by k0rba** [allegro/allegro-api#5505]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Zapytanie 1:
PUT /bidding/offers/11875434504/bid HTTP/1.1
Host: api.allegro.pl
User-Agent: CHAOS-REST/1.02
Authorization: Bearer [token]
Accept: application/vnd.allegro.public.v1+json
Content-Type: application/vnd.allegro.public.v1+json
Content-Length: 49

{'maxAmount': {'amount': '45.55', 'currency': 'PLN'}}

Odpowiedź 1:
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: a5c49b346827c563
date: Mon, 28 Feb 2022 18:07:53 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 153

{'maxAmount': {'amount': '45.55', 'currency': 'PLN'}, 'highBidder': true, 'minimalPriceMet': true, 'auction': {'currentPrice': {'amount': '34.00', 'currency': 'PLN'}}}

Zapytanie 2:
GET /bidding/offers/11875434504/bid HTTP/1.1
Host: api.allegro.pl
User-Agent: CHAOS-REST/1.02
Authorization: Bearer [token]
Accept: application/vnd.allegro.public.v1+json

Odpowiedź 2:
HTTP/1.1 200 OK
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: b00fc920768a50a1
date: Mon, 28 Feb 2022 18:08:06 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json
content-length: 154

{'maxAmount': {'amount': '37.55', 'currency': 'PLN'}, 'highBidder': false, 'minimalPriceMet': true, 'auction': {'currentPrice': {'amount': '38.55', 'currency': 'PLN'}}}

trace-id:
a5c49b346827c563
b00fc920768a50a1

Zapytanie 1. Złożona zostaje oferta 45.55; odpowiedź sugeruje, że została przyjęta i że aktualna cena to 34. W odpowiedzi na zapytanie 2. po zakończeniu licytacji otrzymałem odpowiedź, że wylicytowana kwota to 38.55 a maksymalna oferta to 37.55. Strona oferty pokazuje cenę 38.55.

**Comment by MartaNowaczyk** [comment]
Z naszych logów wynika, że użytkownik 47***2 złożył dwie oferty:
28 lutego 2022 19:07:53.442 45.55 zł - pierwsza oferta w licytacji
28 lutego 2022 19:07:54.656 37.55 zł - obniżenie oferty w licytacji
Po zaoferowaniu kwoty 37,55 zł Twoja maksymalna cena za ofertę obniżyła się i w tym momencie inny kupujący przebił ofertę, a licytacja zakończyła się wynikiem 38,55 zł.
