### ISSUE TITLE
Error: Pickup street is required

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#5506]
Dzień dobry.
W odpowiedzi na requesta 5b52b840-9ba4-4e39-9ff5-5a23976e95d4 otrzymuję 
""errors":[{"code":"ERROR","message":"Pickup street is required","details":null,"path":"pickup.address.street","userMessage":"Ulica punktu nadania przesy0142ki jest wymagana"}]"
w wysłanych danych była podana informacja z komunikatu.
Co jest przyczyną tego błędu?

**Comment by MartaNowaczyk** [comment]
Sprawdzamy opisaną sytuację. Dam znać, gdy coś ustalimy.

**Comment by cemsgh** [comment]
Dzień dobry.
Czy udało się coś ustalić?
Nadal nie możemy wysłać przesyłek z tym błędem.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, niestety jeszcze nie. Nie jest to do końca zależne od nas, czekamy na informację. Na pewno dam znać jak ustalimy w czym problem z tą ulicą.

**Comment by MartaNowaczyk** [comment]
Otrzymaliśmy informację, że przewoźnik nie przyjmuje adresu bez podania numeru budynku.

**Comment by cemsgh** [comment]
Skąd mam wziąć numer budynku jak nie ma go w danych a API

[id] => A003855
[name] => Allegro One Punkt, Kolporter
[type] => PUDO
[services] => Array
	(
		[0] => stdClass Object
			(
				[type] => PICKUP
			)

		[1] => stdClass Object
			(
				[type] => DROPOFF
			)

	)

[restrictions] => Array
	(
	)

[description] => Pasaż Racławicka - wejście od Racławickiej
[payments] => Array
	(
	)

[address] => stdClass Object
	(
		[postCode] => 02-634
		[city] => Warszawa
		[street] => Metro Racławicka Al. Niepodległości
		[countryCode] => PL
		[coordinates] => stdClass Object
			(
				[lat] => 52.198046
				[lon] => 21.013702
			)

	)

**Comment by AureliuszBrussy** [comment]
@cemsgh faktycznie, nie zwracamy dla tego punktu numeru budynku. Wyjaśniam to z odpowiednim zespołem. Wrócę do Ciebie z informacją.

**Comment by cemsgh** [comment]
Dzień dobry.
Czy już coś wiadomo? 
Przesyłki czekają na wysłanie.

**Comment by AureliuszBrussy** [comment]
@cemsgh wciąż czekam na wyjaśnienie, wrócę z informacją jak tylko coś ustalę.

**Comment by cemsgh** [comment]
Dzień dobry.
Jakiś postęp?

**Comment by AureliuszBrussy** [comment]
@cemsgh wciąż wyjaśniamy temat z Kolporterem. Proszę o jeszcze trochę cierpliwości.

**Comment by cemsgh** [comment]
Dzień dobry.
Jakiś postęp?

**Comment by AureliuszBrussy** [comment]
@cemsgh niestety, wciąż jeszcze to wyjaśniamy. Wrócę do Ciebie z informacją od razu gdy wyjaśnimy ten problem.

**Comment by cemsgh** [comment]
Dzień dobry.
Jakiś postęp?

**Comment by MartaNowaczyk** [comment]
Na ten moment dostaliśmy informację od Kolportera, że nie są w stanie określić dokładniejszego adresu. Twój przypadek jest pierwszy, także pewnie będziemy musieli to rozpracować jakoś po swojej stronie. Na ten moment nie mamy na to rozwiązania. Od razu mówię, że może to nie być szybka zmiana. Mamy na uwadze, że jest to problem i postaramy się to jakoś zaadresować.
