### ISSUE TITLE
Niepotrzebne niedrukowalne znaki unicode w szczegółach zamówienia GET /order/checkout-forms/{id}

### ISSUE THREAD

**Issue by alekskuc** [allegro/allegro-api#5507]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

 **Opis / Description**
curl -X GET \
  'https://api.allegro.pl/order/checkout-forms/0fc818d2-9737-11ec-9899-7bc123f444da' \
  --header 'Accept: application/vnd.allegro.public.v1+json' \
  --header 'Authorization: Bearer #'

trace-id 87c24156a26042a7

W danych dostawy jest niepotrzebny znak unicode w postaci tekstowej:

 "delivery": {
    "address": {
      "street": "\u0001Pobadz 2 ",
    },

Proszę o usuwanie takich znaków. W moim przypadku zablokowało, to zapis danych do baz danych.

**Comment by Lukasz-Zurek** [comment]
W formularzu dostawy i zapłaty, w polu ulica ("street") - kupujący wprowadził " Pobadz 2 ", z dodatkowymi spacjami przed i po. Mogło to wpłynąć na zaistniałą sytuację. Mogę jednak zapewnić, że nasze API zwraca prawidłowy adres.

**Comment by alekskuc** [comment]
To nie jest zwykła spacja tylko niedrukowalny znak unicode \u0001 Unicode Character 'START OF HEADING' (U+0001).

Proszę o wycinanie takich znaków podczas walidacji wprowadzanych danych.

Występowanie takich znaków w jsonie powoduje błędy podczas konwersji danych na xml, bo jest to niedozwolony znak w xml'u.

**Comment by Lukasz-Zurek** [comment]
@alekskuc Dziękuję za przesłane uwagi. Przekażę ten temat do odpowiedniego zespołu.
