### ISSUE TITLE
Weryfikacja aplikacji

### ISSUE THREAD

**Issue by ConsultTL** [allegro/allegro-api#5509]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X ] inny / other

:beetle: **Opis / Description**

Potrzebuję listy ofert konkretnych producentów. Żeby to zrobić muszę mieć zweryfikowaną aplikację ze względu na dostęp do offers/listing tylko dla takich aplikacji. W jaki sposób mogę zweryfikować swoją aplikację ?

**Comment by MaciejFrackowiak** [comment]
Weryfikacja dostępu do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) odbywa się poza nami - proszę skontaktuj się poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) bądź bezpośrednio z opiekunem, jeśli takiego posiadasz.
