### ISSUE TITLE
Weryfikacja konta sandbox

### ISSUE THREAD

**Issue by akarasek** [allegro/allegro-api#5510]
Dzień dobry,
Czy mogę prosić o weryfikację konta w środowisku Sandbox?
Login: perfumeria-sndbx

Dziękuję i pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Twoje konto jest już aktywne i zweryfikowane jako firmowe.

**Comment by akarasek** [comment]
super, dziekuje bardzo
