### ISSUE TITLE
Collection contains null or empty elements

### ISSUE THREAD

**Issue by PvauLy** [allegro/allegro-api#5512]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by PvauLy** [comment]
b'{"errors":[{"code":"ValidationError.MethodArgumentNotValidException","message":"Collection contains null or empty elements.","details":null,"path":"/sale/offers/XXX","userMessage":"Collection contains null or empty elements."}]}'

**Comment by PvauLy** [comment]
When uploading a product through the API, an error of 422 is reported. What is the reason?

**Comment by PvauLy** [comment]
,"userMessage":"Collection contains null or empty elements."
Does it mean which value is null or empty?
I don't know where is the value where this problem occurs

**Comment by AureliuszBrussy** [comment]
"ValidationError.MethodArgumentNotValidException" error means that the empty value was provided in a certain field in the parameters section, so please make sure that you sent all of the values.

**Comment by PvauLy** [comment]
How can I check which parameter is the problem?

**Comment by PvauLy** [comment]
[{'id': '11323', 'name': 'Stan'}, {'id': '224017', 'name': 'Kod producenta'}, {'id': '5390', 'name': 'Marka'}, {'id': '127789', 'name': 'Płeć'}, {'id': '5389', 'name': 'Rozmiar'}, {'id': '127768', 'name': 'Bohater'}, {'id': '451', 'name': 'Kolor'}]

**Comment by AureliuszBrussy** [comment]
@PvauLy please, send me your request in curl format (without access_token). I'll check it out.

**Comment by PvauLy** [comment]
moje parametry

**Comment by PvauLy** [comment]
[{'id': '11323', 'valuesIds': ['11323_1']}, {'id': '224017', 'values': ['XXXX']}, {'id': '5390', 'valuesIds': ['5390_178']}, {'id': '127789', 'valuesIds': ['127789_4']}, {'id': '5389', 'values': ['0']}, {'id': '127768', 'valuesIds': ['127768_71']}, {'id': '451', 'valuesIds': ['451_131072']}]

**Comment by AureliuszBrussy** [comment]
@PvauLy please, send me a full request body.

**Comment by PvauLy** [comment]
Send it here directly to you?

**Comment by PvauLy** [comment]
Can I email the data to you?

**Comment by AureliuszBrussy** [comment]
@PvauLy if you do not want to send the data in this GitHub thread - please send it via the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Please, include the thread number in your message: #5512.

**Comment by PvauLy** [comment]
I send it via the contact form

**Comment by PvauLy** [comment]
Hi, can you help me with this? I haven't received a reply email yet. thanks

**Comment by AureliuszBrussy** [comment]
@PvauLy the message has not been forwarded to me yet. Could you please send your application number? You received this id in the confirmation email for the contact form submission.

**Comment by AureliuszBrussy** [comment]
I received your message. 

The parameter section is correct, but you are passing an invalid value in the `sellingMode.price.amount` field - the number should have 2 decimal places. Also, it seems that the characters such as "<" and ">" are transferred to HTML entities on your side.
