### ISSUE TITLE
Aukcje nie zamknęły się 

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#5513]
Poprzez API zleciłem zamknięcie 200 aukcji m. in. 10463719783.

zasób PUT /sale/offer-publication-commands/{commandId}
data: 03.03.2022 23:10:47 GMT
trace-id: c29c737b13c9592a

Aukcje nie zostały zamknięte. Nawet po kilkunastu godzinach nadal były aktywne.

Co było powodem braku zamknięcia aukcji i jak długo maksymalnie może to trwać?

**Comment by AureliuszBrussy** [comment]
W komendzie powiązanej z trace-id który podałeś (komenda: `4c22b71f-e968-4426-9351-9ad071bcac4d`) nie występuje oferta 10463719783. Sprawdziłem przykładowe oferty z tej komendy - zostały one prawidłowo zakończone.

**Comment by krowek** [comment]
@AureliuszBrussy W tym czasie wysłany był też request z trace-id: 7ea4bdaa0f062d3b z takim samym id komendy, ale z innymi id ofert.

W takim przypadku drugi request z tym samym commandId jest ignorowany, zgadza się?

**Comment by AureliuszBrussy** [comment]
@krowek zadbaj o to, aby commandId dla każdej operacji (z różnym zestawem ofert) był unikatowy. Pamiętaj także, aby sprawdzać status zakończenia komendy - np. gdy skorzystasz z [GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPublicationTasksUsingGET) - zwrócimy listę ofert, których dotyczy komenda oraz statusy poszczególnych operacji. 

Ustalam jeszcze poprawne zachowanie w tym szczególnym przypadku, który wskazałeś. Wrócę z informacją.

**Comment by AureliuszBrussy** [comment]
Zrealizowana została pierwsza z komend. Druga o tym samym commandId jest w takim przypadku ignorowana.
