### ISSUE TITLE
Missed attribute value

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5517]
It seems that the burgundy color in the value list of the attribute below has been removed. Which color should we match our burgundy colored products?

"id": "451",
"name": "Kolor"

**Comment by AureliuszBrussy** [comment]
If a color corresponding to a product is missing from the dictionary in a given category, you can use an ambiguous value (e.g. "other color") or another similar color if you wish.

**Comment by yavuzresif** [comment]
I set ambiguous color option but the service returns error;
{"errors":[{"code":"DictionaryParameterValueNotFound","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"Given dictionary parameter value `bordowy` not found in parameter `Color`."}],"error":null,"error_description":null}

    "_traceId": "409520bc96f19fa"

    "parameters": [{
            "id": "451",
            "values": ["bordowy"],
            "valuesIds": ["451_2048"]
        },..

**Comment by AureliuszBrussy** [comment]
You can provide your own value only for selected parameters. Information whether a parameter supports this functionality can be checked via [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/en/documentation/#operation/getFlatParametersUsingGET_2) in the **customValuesEnabled** field in the options section. Sometimes, you'll just have to use an ambiguous value without specifying your own value.
