### ISSUE TITLE
Is there an endpoint to retrieve price data of all sellers?

### ISSUE THREAD

**Issue by tom598** [allegro/allegro-api#5518]
Hello,

I have found the endpoint https://api/.{environment}/offers/listing, and was wondering if it would be suited to retrieve periodically the competitor price data.

**Comment by AureliuszBrussy** [comment]
Yes, the [GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) endpoint allows you to retrieve listings from other sellers, but note that access to this resource is limited to verified applications only. You can read more about limitations in [our news](https://github.com/allegro/allegro-api/issues/4213).

**Comment by tom598** [comment]
Is it possible with the [GET /offers/listing](https://developer.allegro.pl/en/documentation/#operation/getListing) endpoint to determine who currently has the Buy button, (versus being put in the "Other sellers" block)?

![image](https://user-images.githubusercontent.com/64906495/157492128-85cb587e-f005-4be7-bffd-3feb2e18969c.png)

**Comment by AureliuszBrussy** [comment]
No, it's not possible.
