### ISSUE TITLE
Brak możliwości uregulowania zaległych płatności na Allegro Sandbox

### ISSUE THREAD

**Issue by lulzsoad** [allegro/allegro-api#5519]
Po przerwie w korzystaniu z Sandbox'a dostałem blokadę widoczną na załączniku. Próbowałem uregulować płatność blikiem kodem '123456', jednak płatność zostaje odrzucona. 

Nazwa: LULZSOAD

Proszę o pomoc.

![image](https://user-images.githubusercontent.com/48647372/157261105-13436b08-e2c7-40a9-b39e-2c03cd80a4d4.png)

**Comment by AureliuszBrussy** [comment]
Proszę, zamiast z BLIKa spróbuj skorzystać z "szybka wpłata" -> "przelew", a następnie wybierz dowolny bank. Zostaniesz przekierowany na stronę, gdzie będziesz mógł potwierdzić płatność.

**Comment by lulzsoad** [comment]
Dziękuje za pomoc
