### ISSUE TITLE
Problem z doAddPackageInfoToPostBuyForm

### ISSUE THREAD

**Issue by forfiter1** [allegro/allegro-api#552]
Witam
Chcę uzupełnić zamówienie o nr przesyłki poprzez doAddPackageInfoToPostBuyForm.
Podaję wszystkie niezbędne dane ale wypluwa mi taki błąd

SOAP-ERROR: Encoding: object has no 'operator-name' propertyn

Podaje  operator-id = 6 a podanie operator-name jest obowiązkowe dla operator-id = 0
Kiedy podam operator-id = 0 a także 'operator-name' wszystko działa poprawie i dane są aktualizowane.

**Comment by MartaNowaczyk** [comment]
Witam
Nie wiem czy dobrze rozumiem. Gdy podajesz operatorId = 6 i i packageId = {id_przesyłki} to dostajesz wspomniany błąd?

Nie udało mi się tego powtórzyć. Bez problemu dodałam numer przesyłki do zamówienia za pomocą tej metody, także proszę podeślij mi XMLe z responsem i requestem, w którym widać błąd o którym piszesz, abvym mogła się upewnić czy o to dokładnie chodzi.

**Comment by forfiter1** [comment]
array(3) { [0]=> string(52) "a423806973b913e857283bbadc8a8c3e71728267846f2f//03_1" [1]=> string(9) "894312007" [2]=> array(1) { [0]=> array(2) { ["operator-id"]=> int(6) ["package-id"]=> string(20) "00259007734421269788" } } }

**Comment by MartaNowaczyk** [comment]
Nie widzę tu komunikatu z błędem, ani XMLi. Pobierz je za pomocą wbudowanych metod do pobierania requestów i response'ów w twoim soapie i je podeślij. Wtedy będzie jasne czy wszystko odpowiednio przekazujesz.

**Comment by forfiter1** [comment]
Mam prosty kod w php który nie działa.

$info_dostawy = array('operator-id'=> 6,'package-id'=>$nr);
	
$wysylij_nr = $client->doAddPackageInfoToPostBuyForm($nr_sesji,'894312007',array($info_dostawy));

**Comment by forfiter1** [comment]
Dodam tylko, że to działa poprawnie
$info_dostawy = array('operator-id'=> 0,'package-id'=>$nr, 'operator-name'=> 'Poczta Polska');

$wysylij_nr = $client->doAddPackageInfoToPostBuyForm($nr_sesji,'894312007',array($info_dostawy));

**Comment by MartaNowaczyk** [comment]
Jeżeli używasz standardowego klienta w PHP to użyj na kliencie metody __getLastRequest() i __getLastResponse() i podeślij proszę paczki XML dotyczące opisanego problemu.

**Comment by forfiter1** [comment]
Ale czy jeśli otrzymuję błąd
SOAP-ERROR: Encoding: object has no 'operator-name' propertyn
To __getLastRequest() coś zwróci ? Bo mi nie zwraca. 
Jeśli podam operator-name to __getLastRequest() zwraca XML

**Comment by mack3d** [comment]
Też miałem ten sam problem i po zmianie kodu na obiektowy problemów już nie ma, wygląda na to iż SOAP oczekuje deklaracji operator-name mimo iż jest id inne niż o (zero).

**Comment by forfiter1** [comment]
Czyli jednak po stronie allegro jest jakiś problem. A możesz mi napisać jak sobie z tym poradziłeś ? Walczę i niestety bez efektu.

**Comment by mack3d** [comment]
Mój kod:
`$request = array(
	   'sessionId' => $session->sessionHandlePart,
	   'transactionId' => $numer,
	   'packageInfo' => array(
		array (
			'operatorId' => 6,
			'packageId' => $nrnadania))
	);
$dodanielistu = $soapClient->doAddPackageInfoToPostBuyForm($request);`

**Comment by MartaNowaczyk** [comment]
@forfiter1 czy udało sie rozwiązać problem?

**Comment by forfiter1** [comment]
Nie. Kod podany przez mack3d u mnie nie działa (błędny identyfikator sesji)
A ewidentnie jest problem po waszej stronie. Bo dlaczego 

To działa
$info_dostawy = array('operator-id'=> 0,'package-id'=>$nr, 'operator-name'=> 'Poczta Polska');
$wysylij_nr = $client->doAddPackageInfoToPostBuyForm($nr_sesji,'894312007',array($info_dostawy));

A to nie i wymagania podania operator-name skoro nie jest wymagany 
$info_dostawy = array('operator-id'=> 6,'package-id'=>$nr);
$wysylij_nr = $client->doAddPackageInfoToPostBuyForm($nr_sesji,'894312007',array($info_dostawy));

**Comment by forfiter1** [comment]
Rozwiązane.
Faktycznie kod mack3d działa.

**Comment by mack3d** [comment]
Przydałoby się rozwiązanie, podejrzewam że system nie akceptuje podania "poczta polska" id 0 ponieważ id tego operatora to 6.

**Comment by MartaNowaczyk** [comment]
Sprawdzę i dam znać.

**Comment by MartaNowaczyk** [comment]
@forfiter1 

> Nie działa podanie id=6 bez podania nazwy (przynajmniej w moim kodzie)

Testuję to kolejny raz:
Request:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="https://webapi.allegro.pl/service.php">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DoAddPackageInfoToPostBuyFormRequest>
         <ser:sessionId>d3a1b63f7...8812846f2f//03_1</ser:sessionId>
         <ser:transactionId>906032298</ser:transactionId>
         
         <ser:packageInfo>
            
            <ser:item>
               
               <ser:operatorId>6</ser:operatorId>
               <ser:packageId>12345678910</ser:packageId>
            </ser:item>
         </ser:packageInfo>
      </ser:DoAddPackageInfoToPostBuyFormRequest>
   </soapenv:Body>
</soapenv:Envelope>`
Rsponse:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://webapi.allegro.pl/service.php">
   <SOAP-ENV:Body>
      <ns1:doAddPackageInfoToPostBuyFormResponse>
         <ns1:postBuyFormPackageInfo>
            <ns1:packageIdsAdded>
               <ns1:item>12345678910</ns1:item>
            </ns1:packageIdsAdded>
            <ns1:packageIdsNotAddedIncorrectOperatorId/>
            <ns1:packageIdsNotAddedIncorrectPackageId/>
         </ns1:postBuyFormPackageInfo>
      </ns1:doAddPackageInfoToPostBuyFormResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

i nie mam problemu z dodaniem przesyłki. Nie widzę błędu po naszej stronie.

**Comment by gantel86** [comment]
U mnie też działa tylko w przypadku gdy podam `operator-id`=0, a `operator-name` podam słownie.
Każda inna próba zwraca błąd.
Wydaje mi się, że ta lista z dokumentacji jest błędna. Chociażby dlaczego DPD jest dwa razy?

Identyfikator operatora przesyłki (0 - Inny, 1 - UPS, 2 - GLS, 3 - Ruch, 4 - DHL, 5 - InPost, 6 - Poczta Polska, **7 - DPD, 9 - DPD**, 10 - FedEX, 11 - TNT Express, 12 - DB Schenker, 13 - Raben, 14 - GEIS, 15 - Pocztex,16 - DTS, 17 -PEKAES, 18 - Patron Service).

**Comment by forfiter1** [comment]
Oczywiście, że nie działa. Ale Allegro twierdzi, że wszystko jest w porządku - bo przecież u nich działa.

Allegro - przetestujcie prosty kod PHP a nie XMLe.

**Comment by MartaNowaczyk** [comment]
Sprawa jest w toku. Jak uda nam się ustalić w czym problem damy znać.

**Comment by mack3d** [comment]
U mnie prosty kod PHP działa, podaje id i numer dla poczty i DPD wszystko ok

**Comment by ernestu** [comment]
Czy już coś wiadomo w tej sprawie? U mnie również nie działa. 
poniżej info co wywołuje:

$data =  [
  "sessionId" => "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  "transactionId" => "xxxxxxxxxxxxxxxx"
  "packageInfo" =>  [
    0 =>  [
      "operator-id" => 5
      "package-id" => "639200407859800035616949"
      "operator-name" => ""
    ]
  ]
]

    $this->__soapCall('doAddPackageInfoToPostBuyForm',$data);

zwraca  

{#16 ▼
  +"package-ids-added": []
  +"package-ids-not-added-incorrect-operator-id": array:1 [▼
    0 => "639200407859800035616949"
  ]
  +"package-ids-not-added-incorrect-package-id": []
}

usunięcia z data "operator-name" powoduje: 
SOAP-ERROR: Encoding: object has no 'operator-name' property

doAddPackageInfoToPostBuyForm działa tylko gdy podany zostanie  "operator-id" => 0 i "operator-name"=> "Inpost"

Po zamianie na "operator-id na  operatorId  otrzymuję: 
SOAP-ERROR: Encoding: object has no 'operator-id' property

**Comment by MartaNowaczyk** [comment]
@ernestu  Sprawdzamy czy coś jest na rzeczy, jednak moje wywołania tak jak mack3d nie generują błędów.

**Comment by pskz** [comment]
Również podłączam się do pytania o DPD, w dokumentacji jest zduplikowane pod id 7 i 9.

**Comment by pskz** [comment]
@ernestu Z tego co udało mi się ustalić błąd powoduje wysłanie parametru "operatorName" gdy "operatorId" jest większy od zera, nawet jeśli jest pusty. Mimo iż Allegro powinno pomijać wtedy ten parametr, niestety tak się nie dzieje.
Więc "operatorName" podawaj tylko wtedy jak "operatorId" jest ma być równy zero.

Tak wygląda moja funkcja do wysyłania numeru przesyłki, testowałem na różnych wartościach, działa bez problemu.
```
public function addPackageInfoToPostBuyForm($transactionId, $packageId, $operatorId, $operatorName = '')
{
    $packageInfo = array(
        'packageId' => $packageId,
        'operatorId' => (int)$operatorId,
    );

    if ((int)$operatorId == 0) {
        $packageInfo['operatorName'] = $operatorName;
    }

    return $this->doAddPackageInfoToPostBuyForm(array(
        'transactionId' => (int)$transactionId,
        'packageInfo' => array(
            $packageInfo
        )
    ));
}
```

**Comment by MartaNowaczyk** [comment]
@pskz wiemy, że DPD jest dwa razy, ale obie wartości przypisują poprawnie DPD, także nie jest to w tym momencie duży problem.

**Comment by ernestu** [comment]
Rozwiązania przesłane przez @pskz i  @kamilsu  działają, dziękuję.

Poniżej koperty dla @MartaNowaczyk :

działające rozwiązanie:
Req:
```
<?xml version="1.0" encoding="UTF-8"?>\n
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:AllegroWebApi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:doAddPackageInfoToPostBuyForm><session-id xsi:type="xsd:string">IDSESJI</session-id><transaction-id xsi:type="xsd:long">IDTRANSAKCJI</transaction-id><package-info SOAP-ENC:arrayType="ns1:PackageInfoStruct[1]" xsi:type="ns1:ArrayOfPackageInfoStruct"><item xsi:type="ns1:PackageInfoStruct"><operator-id xsi:type="xsd:int">6</operator-id><package-id xsi:type="xsd:string">NUMERPRZESYLKI</package-id><operator-name xsi:nil="true"/></item></package-info></ns1:doAddPackageInfoToPostBuyForm></SOAP-ENV:Body></SOAP-ENV:Envelope>
```
Res: 
```
<?xml version="1.0" encoding="UTF-8"?>\n
<SOAP-ENV:Envelope  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:typens="urn:AllegroWebApi" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">\n 
<SOAP-ENV:Body SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n
<typens:doAddPackageInfoToPostBuyFormResponse><post-buy-form-package-info xsi:type="typens:PostBuyFormPackageInfoStruct">\n
<package-ids-added xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="xsd:string[1]"><item xsi:type="xsd:string">NUMERPRZESYLKI</item>\n
</package-ids-added>\n
<package-ids-not-added-incorrect-operator-id xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="xsd:string[0]"></package-ids-not-added-incorrect-operator-id>\n
<package-ids-not-added-incorrect-package-id xsi:type="SOAP-ENC:Array" SOAP-ENC:arrayType="xsd:string[0]"></package-ids-not-added-incorrect-package-id>\n
</post-buy-form-package-info>\n
</typens:doAddPackageInfoToPostBuyFormResponse></SOAP-ENV:Body>\n
</SOAP-ENV:Envelope>
```
Bez parametru operator-name nie klient SOAP zwraca wyjątek przed utworzeniem koperty:
SOAP-ERROR: Encoding: object has no 'operator-name' property

**Comment by MartaNowaczyk** [comment]
@ernestu dziękuję

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować. Jeśli jednak napotkacie problem dajcie znać.
