### ISSUE TITLE
Is it possible to update the stock in allegro to have a certain amount left to sell.

### ISSUE THREAD

**Issue by tom598** [allegro/allegro-api#5520]
Hello,
Is it possible to update the stock in allegro to have a certain amount left to sell.

For example we create a offer with 10 units, then there are 4 sales and there will be 6 left.
If I then send an update to update the stock level to 2 (because I only have 2 units left), the Edit Offer endpoint (https://api.{environment}/sale/product-offers/{offerId}) gives me an error:
`{"errors":[{"code":"ERR_INVALID_QUANTITY","message":"The stock level of items may not be lower than sold items.","details":"ERR_INVALID_QUANTITY","path":"stock.initialQuantity","userMessage":"Liczba sztuk nie może być mniejsza od liczby sprzedanych przedmiotów."}]}`

Do i really need to send a stock level of 8 to only have 2 left to sell?
If so, is there a way i can retrieve the current amount of sales?

Our best case scenario would be an endpoint to update the current stock level.

**Comment by AureliuszBrussy** [comment]
Yes, it is possible just to add or remove a certain amount of stock. Just use [PUT /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/en/documentation/#operation/quantityModificationCommandUsingPUT). In the `"changeType"` field, use the `"GAIN"` option. You can read more in [our guide](https://developer.allegro.pl/en/my_offers/#quantity).
