### ISSUE TITLE
Kiedy naliczane są opłaty utrzymaniowe przy wzniowieniu oferty po upływie roku

### ISSUE THREAD

**Issue by krowek** [allegro/allegro-api#5521]
Chodzi o sytuację, gdy np. w 340 dniu po wystawieniu oferty bez sprzedaży, zostaje ona zamknięta. W 370 dniu zostaje wznowiona. 

1. Czy opłaty zostaną naliczone natychmiast po wznowieniu czy po jakimś czasie?
2. Czy api "/pricing/offer-quotes" zwróci wtedy informację o zbliżających się kosztach?

**Comment by AureliuszBrussy** [comment]
1. W momencie wznowienia oferty licznik będzie wynosić 340 dni.
2. Tak, zwracamy informację o zbliżającej się opłacie utrzymaniowej w danym cyklu.

**Comment by krowek** [comment]
ok dziękuję
