### ISSUE TITLE
 bearer-token-for-application 403

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5523]
Wywołuje url https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=85......&redirect_uri=http://localhost:8000 ale zwracami 403?

**Comment by AureliuszBrussy** [comment]
Upewnij się, że Twoja aplikacja jest zarejestrowana w panelu [Zarządzanie aplikacjami Allegro Sandbox](https://apps.developer.allegro.pl.allegrosandbox.pl/) (dla środowiska testowego). Rodzaj aplikacji - WEB.

Gdy przekażesz prawidłowo sparametryzowany adres url np. w przeglądarce - zostaniesz przekierowany do okna logowania na Allegro Sandbox, a później na ekran zgody. Po prawidłowym zalogowaniu oraz potwierdzeniu, zostaniesz przekierowany pod adres z parametru `redirect_uri`, a w adresie url zwrócimy kod:

[http://localhost:8000/?code={code}](http://localhost:8000/?code={code}).

Jeżeli nadal nie będziesz miał problem, prześlij nam proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) z dopiskiem GitHub https://github.com/allegro/allegro-api/issues/5523.

**Comment by silverwind85** [comment]
Wiem że to tak nie na temat ale jest api, które zwraca kot ean produktu

**Comment by AureliuszBrussy** [comment]
@silverwind85 czy możesz doprecyzować, co dokładnie masz na myśli i w czym jeszcze mogę pomóc?
