### ISSUE TITLE
BAD Request parcel-management/parcel-create-commands

### ISSUE THREAD

**Issue by Tomek134** [allegro/allegro-api#5528]
Mam problem z utworzeniem przesyłki Allegro One
```
[code] => BAD_REQUEST
[message] => JSON parse error
[details] => 
[path] => /parcel-management/parcel-create-commands/b9bfcc9e-b5b6-04ea-002f-c400198c5e60
[userMessage] => Nieprawidłowa treść żądania JSON
```

Czy jest możliwość uzyskania informacji co jest problemem w przekazywanym ciągu? próbowałem już wszystkiego

**Comment by MartaNowaczyk** [comment]
Podeślij pełen request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Pozwoli nam to wskazać bezpośrednią przyczynę błędu. Dopisz proszę, że dane dotyczą wątku GitHub #5528.

**Comment by MartaNowaczyk** [comment]
W podesłanych danych nie widać błędu. Sprawdź proszę czy na pewno wysyłasz payload w zapytaniu, bo to może być problem.
