### ISSUE TITLE
Wyróżnienie elastyczne przy tworzeniu draftu

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5529]
Dzień dobry, w jaki sposób przy tworzeniu draft oferty za pomocą POST /sale/offers dodać opcję wyróżnienia elastycznego? Nigdzie w dokumentacji nie mogę znaleźć odpowiedniej struktury

**Comment by MartaNowaczyk** [comment]
Wyróżnienie elastyczne czyli Flexible Emphasized przypiszesz do oferty za pomocą odrębnego zasobu [POST /sale/offers/{offerId}/promo-options-modification](https://developer.allegro.pl/documentation/#operation/modifyOfferPromoOptionsUsingPOST). Więcej na ten temat znajdziesz w [naszym poradniku](https://developer.allegro.pl/my_offers/#jak-zarz%c4%85dza%c4%87-promowaniem).
