### ISSUE TITLE
Wystawienie API ze wszystkimi danymi sprzedaży oraz rozliczeniami z allegro

### ISSUE THREAD

**Issue by UserGEC** [allegro/allegro-api#5530]
Czy jest możliwość wystawienia po API na potrzeby raportowania wszystkich danych konta: sprzedaży, wystawionych ofert oraz rozliczenia z allegro?

Dziękuje za pomoc!

**Comment by AureliuszBrussy** [comment]
Udostępniamy zasoby, dzięki którym:
- pobierzesz oferty wystawione na koncie - [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - [dedykowany poradnik](https://developer.allegro.pl/my_offers/#jak-pobra%c4%87-moje-oferty-w-rest-api), 
- pobierzesz zamówienia - [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET) - [dedykowany poradnik](https://developer.allegro.pl/orders/),
- pobierzesz informacje o opłatach Allegro - [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) - [dedykowany poradnik](https://developer.allegro.pl/charges/).
