### ISSUE TITLE
Invoice due date to "null" przy płatności typu "Odroczona płatność"

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5531]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam,

mam problem z zamówieniem o UUID: `ba4893f3-a2e2-11ec-a1c4-1de23398dea1` (trace-id odpytania o dane zamówienia: `d6632eaee4455655`). Mimo typu płatności `EXTENDED TERM`, w polu `invoice.dueDate` jest wartość `null`. Bez tej daty nie mogę stworzyć poprawnej faktury w systemie, więc to duży problem, który paraliżuje pracę.

Liczę na szybką pomoc, pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Witam, jest to prawidłowe zachowanie, w zamówieniach złożonych od 11 stycznia nie zwracamy już terminu spłaty w tym polu. Więcej informacji znajdziesz w [naszym newsie](https://developer.allegro.pl/news/#extended-payment-changes).

**Comment by hahyes** [comment]
> Witam, jest to prawidłowe zachowanie, w zamówieniach złożonych od 11 stycznia nie zwracamy już terminu spłaty w tym polu. Więcej informacji znajdziesz w [naszym newsie](https://developer.allegro.pl/news/#extended-payment-changes).

Faktycznie. Po przerwie świątecznej musiał mi ten news umknąć. Dziękuję i pozdrawiam.
