### ISSUE TITLE
Parametry aukcji

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5533]
Chcielibyśmy w naszym systemie odtworzyć wystawianie aukcji. Czy jest możliwość pobrania w jakiś sposób wszystkich kategorii i ich parametrów poprzez pojedyńcze requesty? Czy jedyna możliwość to przechodzić po całym drzewie kategori i odpytwać o parametry dla każdej kategorii osobno?

**Comment by AureliuszBrussy** [comment]
Nie, nie ma możliwości pobrania całego drzewka jednym requestem. Jedyna możliwość to przejście po drzewie kategorii dzięki [GET /sale/categories/{categoryId}](https://developer.allegro.pl/documentation/#operation/getCategoryUsingGET_1) oraz [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by hahyes** [comment]
> Chcielibyśmy w naszym systemie odtworzyć wystawianie aukcji. Czy jest możliwość pobrania w jakiś sposób wszystkich kategorii i ich parametrów poprzez pojedyńcze requesty? Czy jedyna możliwość to przechodzić po całym drzewie kategori i odpytwać o parametry dla każdej kategorii osobno?

Dobra rada, nie grupuj parametrów po ich ID. Parametr 1234 dla kategorii 1234 może mieć inne wartości/opcje/ograniczenia jak parametr 1234 dla kategorii 1235. :)
