### ISSUE TITLE
Składanie wniosków o rabat transakcyjny

### ISSUE THREAD

**Issue by krljpcz** [allegro/allegro-api#5535]
Dzień dobry,

mam pytanie dot. składania wniosków o rabaty transakcyjne. Z przeprowadzonej analizy i testów dochodzę do wniosku, że nie można złożyć ponownego wniosku o rabat transakcyjny dla danego lineItem.id niezależnie od statusu wcześniej złożonego wniosku. Proszę o potwierdzenie albo wyjaśnienie wspomnianej kwestii.

Z wyrazami szacunku,

krljpcz

**Comment by AureliuszBrussy** [comment]
Zgadza się - dla każdego lineItem.id możesz utworzyć tylko jeden wniosek o rabat transakcyjny.
