### ISSUE TITLE
API returns "Invalid refresh token" error during refreshing access token

### ISSUE THREAD

**Issue by antalos** [allegro/allegro-api#5536]
The refresh token has been received yesterday and is still valid.

Log of the call being made:
```
13:03:04 INFO      [http_client] >>>>>>>> REQUEST:\nPOST /auth/oauth/token?grant_type=refresh_token&redirect_uri=[urlencodedRedirectURL]&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.[removed].[removed2]-_oelXZocgIw_-INg HTTP/1.1
User-Agent: GuzzleHttp/7
Host: allegro.pl
Content-Type: application/json
Accept: application/vnd.allegro.public.v1+json


13:03:04 INFO      [http_client] <<<<<<<< RESPONSE:\nHTTP/1.1 400 Bad Request
date: Tue, 15 Mar 2022 11:03:04 GMT
content-type: application/vnd.allegro.public.v1+json;charset=UTF-8
transfer-encoding: chunked
cache-control: no-store
pragma: no-cache
vary: Accept-Encoding
age: 0
content-security-policy: block-all-mixed-content; report-uri https://edge.allegro.pl/seclog/csp;
x-content-type-options: nosniff
grace: none
x-xss-protection: 1; report=https://allegro.pl/seclog/xss
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000

{"error":"invalid_grant","error_description":"Invalid refresh token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.[removed].[removed2]-_oelXZocgIw_-INg"}
```

I've dug into logs on our end but had not found any attempt to use this refresh token before this call. 

Can you please check if the token is a correct one?

**Comment by AureliuszBrussy** [comment]
Please send a full refresh token via the [contact form](https://allegro.pl/help/contact?category=b469d1bc-4353-4e65-a65b-6cac33aa595b&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) so that I can check it. Include your GitHub issue number in the message -#5536.

**Comment by AureliuszBrussy** [comment]
Thank you for sending a message in the contact form.

The token has expired due to a changes in the user account.

Please note that access_token and refresh_token can expire due to:
- log out from all devices, e.g. via the Login and password tab,
- password change,
- change of e-mail address,
- sales blockades,
- as a result of exceeding the number of active sessions (max. 20 open sessions for one user).

**Comment by antalos** [comment]
Thanks a lot for your response. Do I understand properly that you've checked the logs on your side and this refresh has not been used to get new access token?

**Comment by AureliuszBrussy** [comment]
@antalos yes, this refresh token was expired before it was used due to changes in the user account.

**Comment by antalos** [comment]
Thanks a lot for the assistance.
