### ISSUE TITLE
[Sandbox] Weryfikacja SMS

### ISSUE THREAD

**Issue by sdomi** [allegro/allegro-api#5539]
Próbuje potwierdzić numer telefonu kodem SMS. W innym issue widziałam info o podaniu kodu 1234 - ale form wymaga 6-cyfrowych kodów. Jaki jest aktualnie poprawny kod do weryfikacji?

![image](https://user-images.githubusercontent.com/22369758/158392569-ac30ea07-8525-4936-a2ce-e7b3e0374986.png)

**Comment by AureliuszBrussy** [comment]
Spróbuj skorzystać z kodu 123456.

**Comment by sdomi** [comment]
Działa, dzięki. Po drodze używałam repeatowania requestów i kodu `1234` (bo wygląda na to, że blokuje go tylko frontend).

Wrzucicie to gdzieś do docsów allegrosandbox? :)

**Comment by AureliuszBrussy** [comment]
@sdomi dziękuję za sugestię. Dopiszemy informację w jednym [z poradników](https://developer.allegro.pl/about/#%c5%9brodowisko-testowe) na naszym devportalu.
