### ISSUE TITLE
Hurtowa zmiana cennika

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#554]
Mam do wszystkich aukcji podpięte cenniki. Dzisiaj rano dokonałem modyfikacji w tych cennikach (poprzez panel Allegro) lecz aukcje nadal mają stare wartości. Dwie godziny temu użyłem metody nowego API `PUT: sale/offer-modification-commands/{commandId}` aby hurtowo ustawić cenniki dla aukcji, ceny nadal bez zmian, choć niby wszystko wykonało się poprawnie (command UUID: `1beedae8-070e-480f-a662-41e08a1a1b4f`) - a aukcja 7522985298 nadal ma złe ceny, choć:

```
object(stdClass)#39 (6) {
--
  | ["offer"]=>
  | object(stdClass)#40 (1) {
  | ["id"]=>
  | string(10) "7522985298"
  | }
  | ["message"]=>
  | string(0) ""
  | ["status"]=>
  | string(7) "SUCCESS"
  | ["scheduledAt"]=>
  | string(29) "2018-08-31T12:55:01.038+02:00"
  | ["finishedAt"]=>
  | string(29) "2018-08-31T12:55:02.974+02:00"
  | ["field"]=>
  | string(13) "shippingRates"
  | }
```

Chciałbym potwierdzenie że coś nie jest tak, zanim uruchomię metodę `PUT: /sale/offers/{offerId}`, która działa, lecz muszę ją wykonać 90k razy.

**Comment by pgasidlo** [comment]
Jak wywołam zmianę przez API hurtową zmianę na inny cennik, a następnie hurtową zmianę na poprawny cennik to wszystko jest już OK. Pytanie dlaczego.

**Comment by MartaNowaczyk** [comment]
Testowałam i każda zmiana przez panel allegro zakończyła się poprawną aktualizacją opcji dostawy w ofercie, dlatego ciężko będzie przejść całą opisaną ścieżkę. Czy problem powtarza się za każdym razem, gdy edytujesz cennik przez panel allegro?

**Comment by pgasidlo** [comment]
Proszę zobaczyć na te aukcje, wszystkie mają podpięte cenniki, które dzisiaj były modyfikowane (wyłączenie odbiorów osobistych). Lecz dla tych aukcji nadal jest on aktywny:

https://allegro.pl/uzytkownik/tradum_pl?dostawa-odbior-osobisty=1&order=m
https://allegro.pl/uzytkownik/tantis_pl?dostawa-odbior-osobisty=1&order=m

**Comment by MartaNowaczyk** [comment]
Podaeślij proszę pełne request i response w formacie XML (bez wrażliwych danych oczywiście), gdzie zmieniasz cenniki, to będzie łatwiej to zweryfikować.
