### ISSUE TITLE
GET /order/events - kolejność kiedy brak from

### ISSUE THREAD

**Issue by AureliuszBrussy** [allegro/allegro-api#5540]
### Discussed in https://github.com/allegro/allegro-api/discussions/5538

<div type='discussions-op-text'>

<sup>Originally posted by **tztztztz** March 15, 2022</sup>
Dzień dobry,

powiedzmy, że uruchomię komendę GET /order/events z parametrami: limit = 1, i type = READY_FOR_PROCESSING, nie ma parametru from.

Pobierze mi się więc jedno zdarzenie, pytanie: czy jest ustalona jakaś kolejność pobierania, czy jest to losowe?

Czy pobierze się np. pierwsze (najstarsze) zdarzenie, czy np. odwrotnie: pierwsze najnowsze, czy to jest gwarantowane zachowanie, czy może ulec zmianie w każdym momencie?

Niestety nie ma nic na ten temat w dokumentacji tutaj:

https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET</div>

**Comment by tztztztz** [comment]
Ok zapomniałem dodać sugestii, oto ona:

Opisać w dokumentacji w jakiej kolejności są pobierane dane, szczególnie, kiedy brak parametru from.

**Comment by AureliuszBrussy** [comment]
@tztztztz w takim przypadku (limit = 1, i type = READY_FOR_PROCESSING) zwrócimy najstarszy spośród dostępnych zdarzeń typu READY_FOR_PROCESSING. W [poradniku](https://developer.allegro.pl/orders/#dziennik-zdarze%c5%84) podajemy więcej szczegółów. Dziękuję za sugestię dot. informacji w dokumentacji - rozważymy jej odpowiednie uzupełnienie.
