### ISSUE TITLE
Sandbox problem z obrazkami

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5541]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Na sandboxie przy próbie wystawienia aukcji przez api dostajemy ciągle zwrotki z poniższym błedem
{
  "errors": [
    {
      "code": "OfferImagesNotFoundException",
      "message": "Provided image address is incorrect.",
      "details": "OfferImagesNotFoundException",
      "path": null,
      "userMessage": "Podany adres obrazka jest nieprawidłowy."
    }
  ]
}

obrazek jest załadowany na sandboxa i działa poprawnie
https://a.allegroimg.allegrosandbox.pl/original/11cb4d/f8942e6a4b7a992168cb5b8352f5

w zalaczniku curl requesta ktorym probojemy stworzyc aukcje
[allegro.txt](https://github.com/allegro/allegro-api/files/8254131/allegro.txt)

**Comment by PrzemyslawLukanowski** [comment]
Wstępnie wygląda to na problem ze wskazanym produktem. Analizujemy jeszcze konkretną przyczynę, ale problem powinien ustąpić, jeśli spróbujecie powiązać ofertę z innym produktem. Pamiętajcie także proszę, aby korzystać z wersji public zasobów sale/product-offers. Od [28 lutego](https://developer.allegro.pl/news/#reminder-disabling-product-offers-beta-versions) nie wspieramy już wersji beta i wkrótce całkowicie je wyłączymy.
