### ISSUE TITLE
Błąd połączenia Sky Shop z Allegro

### ISSUE THREAD

**Issue by ProCorte** [allegro/allegro-api#5542]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przy próbie połączenia Sky Shop z kontem allegro zostaje przekierowany na stronę allegro na której wyświetla się błąd: "Nie możemy wyświetlić strony
Numer błędu: 87517b71a7f84f4"

**Comment by PrzemyslawLukanowski** [comment]
Adres przekierowania, który podajesz w aplikacji, różni się od tego, który zarejestrowałeś na stronie https://apps.developer.allegro.pl/. Te adresy muszą być identyczne.
