### ISSUE TITLE
Problem z wystawieniem draftu oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5543]
Mam problem z wystawieniem nowej oferty z draftu. W przypadku przesyłania struktury poprzez PUT /sale/offers/7687297900 otrzymuję błąd 422 Offer id cannot be changed. ID oferty, które przekazuję w adresie jest takie samo jak przekazuję w strukturze. Z tej samej struktury (tylko bez ID) korzystam w przypadku POST /sale/offers i tutaj ładnie tworzy nasz szkic oferty, problem pojawia się w momencie użycia PUT /sale/offers/{offerId}. W załączniku przesyłam strukturę, którą przekazuję 
[json put complete a draft offer.txt](https://github.com/allegro/allegro-api/files/8257355/json.put.complete.a.draft.offer.txt)

**Comment by PrzemyslawLukanowski** [comment]
Numer oferty jest różny, w ścieżce podajesz 7687297900, a w pliku w polu "id" widnieje 7687297950.

**Comment by mateuszcom** [comment]
Faktycznie - nie zwróciłem uwagi, że przeglądarka trzymała w pamięci jeszcze część starych danych
