### ISSUE TITLE
Proszę o weryfikację konta firmowego

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#5544]
Witam,
Proszę o weryfikację konta firmowego na sandbox annawaskowiak.

Pozdrawiam
Marcin Butak

**Comment by PrzemyslawLukanowski** [comment]
Rodzaj tego konta to zwykłe, aktualnie posiada blokadę sprzedaży ze względu na "nieopłacony" rachunek. Możesz go opłacić przez symulator płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro). Jeśli chcesz zmienić rodzaj konta na firmowe, skorzystaj ze strony https://allegro.pl.allegrosandbox.pl/biznes.

**Comment by makerlabs** [comment]
Dzięki za informacje.
