### ISSUE TITLE
Order not found in restAPI

### ISSUE THREAD

**Issue by slkperkun** [allegro/allegro-api#5546]
Order exist in admin panel and has "checkoutForm_id".
But function https://api.allegro.pl/order/checkout-forms/{checkoutForm_id} return "not found".

What could be causing this?
Why restAPI cannot see this order?

Regards.
Slawomir.

**Comment by slkperkun** [comment]
Thanks for the quick reply :)

Today in the afternoon the order appeared in restAPI - the error is gone ;)
I don't know what the delay is from (24 hours).

**Comment by paafcioc22** [comment]
Mam ten sam problem.. 
https://api.allegro.pl/order/checkout-forms/f959ca79-a46b-11ec-9040-b30c316ce403
trace-id : c48a70e0975aa55b

**Comment by AureliuszBrussy** [comment]
@paafcioc22 przepraszam za problemy. Pobranie zamówienia jest już możliwe.

**Comment by paafcioc22** [comment]
@AureliuszBrussy ok, dzięki. Czy problem usunięty na tyle żebym się nie martwił, że klientom znów się coś nie pobierze?

**Comment by AureliuszBrussy** [comment]
@paafcioc22 jeszcze to sprawdzamy. Nie mogę na ten moment wykluczyć, że podobny problem może się jeszcze przytrafić.

**Comment by AureliuszBrussy** [comment]
@paafcioc22 potwierdzam, że problem nie powinien już występować także dla innych zamówień.
