### ISSUE TITLE
Nie mogę wystawić przedmiotu, system podaje nonsensowny powód

### ISSUE THREAD

**Issue by oponika** [allegro/allegro-api#5547]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ X] inny / other

:beetle: **Opis / Description**

Nie da się wystawić przedmiotu, system podaje nonsensowny powód.
Próbuję wystawić letnie opony do samochodu osobowego Pirelli
poprawnie wybieram kategorię a system nie pozwala mi tego wystawić podając nonsensowny powód
![obraz](https://user-images.githubusercontent.com/60691819/158592194-50bd9a97-de38-4366-9446-ad8a4362c3b1.png)

**Comment by AureliuszBrussy** [comment]
Wszelkie problemy dotyczące wystawiania ofert w Moim Allegro zgłaszaj poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
