### ISSUE TITLE
Zdarzenie opłacenia

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5549]
Mam pytanie, w API zostało pobrane zdarzenie zakupu:
checkout_form_id  25b03191-a46c-11ec-aa37-bdabce94ca6c
ale nie przyszlo zdarzenie oplacenia.
Co moze byc przyczyna ?

**Comment by AureliuszBrussy** [comment]
Potwierdzam, że mogły wystąpić braki eventów w dniu 15.03. Skala problemu jest niewielka. Sprawdzamy to i pracujemy nad przetworzeniem brakujących eventów.
