### ISSUE TITLE
Pobranie szczegółowych informacji o akcie zakupowym

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#555]
Czy moglibyście dorobić metodę w SOAP albo REST API pozwalającą na pobranie szczegółowych informacji o konkretnym akcie zakupowym (deal_id) ? Obecnie korzystam z metody doGetDeals: https://allegro.pl/webapi/documentation.php/show/id,462 aby pobrać cenę (w SOAPowym journalu jest ona niedostępna) ale niestety nie zawsze działa ona poprawnie. Czasami może zdarzyć się sytuacja w której w journalu nie mam podanego transaction_id, a metoda nie zwraca już żadnych informacji gdyż "... Metoda zwraca tylko te akty zakupowe, które nie są jeszcze opłacone ...". W rezultacie jestem zmuszony tworzyć zamówienia na zerową kwotę i aktualizować je dopiero wtedy kiedy transakcja wpadnie do journala. Jest to dość mylące dla klienta

Nawiasem mówiąc dobrze byłoby jakby metoda działała z identyfikatorami numerycznymi i UUID

**Comment by MartaNowaczyk** [comment]
W SOAP nie będziemy wprowadzać zmian, ale udostępniliśmy możliwość pobrania listy zamówień w REST API za pomocą metody GET na zasobie /order/checkout-forms. [Tutaj](https://developer.allegro.pl/orders/#03) znajdziesz więcej szczegółów. Zobacz czy to wystarczy, a jeśli nie, opisz dokładniej czego potrzebujesz.

**Comment by kormichu** [comment]
No nie do końca. Zasób /order/checkout-forms wymaga podania identyfikatora transakcji / zamówienia / formularza pozakupowego (zależy od nazewnictwa stosowanego w SOAP / REST API). Mi chodzi o szczegółu aktu zakupowego, których identyfikator (po staremu dealId) dostajemy w dzienniku zdarzeń przed wypełnieniem przez klienta formularza pozakupowego.  W starym API można było pobrać szczegółowe informacje o takim akcie zakupowym przy pomocy doGetDeals o ile klient w tym samym czasie nie wypełnił formularza. Wówczas wartość nie była już zwracana.

Problem częściowo rozwiązałem pobierając cenę bezpośrednio z danej aukcji. Nie jest to jednak rozwiązanie idealne bo cena na aukcji może ulec zmianie w stosunku do ceny z danego aktu zakupowego

**Comment by MartaNowaczyk** [comment]
Dane takie jak cena dla zakupów bez wypełnionego FODa uzyskasz w dzienniku zdarzeń jak i na liście zamówień filtrując poprzez wartość "BOUGHT":
- https://api.allegro.pl/order/events?type=BOUGHT
- https://api.allegro.pl/events/checkout-forms?status=BOUGHT
