### ISSUE TITLE
Zasób /order/customer-returns zwraca "puste" paczki

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5550]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,

mam problem z zasobem `order/customer-returns`, pobrałem paczkę zwrotów przez wyszukiwarkę, w tym zwrot o ID: `55980891-0300-45bb-8c59-8a36b2c7bb14`. Zwraca on dwie paczki. Jedna paczka nie ma wypełnionego `waybill` oraz `carrierId`, druga jest wypełniona normalnie. Czy taka sytuacja jest akceptowalna, czy to jednak bug? Nie wiem, co ma taka pusta paczka z samym numerem telefonu oznaczać.

Edit: O co chodzi z kolejnością zwrotów w tym zasobie? Dla mnie to nie jest aż taki problem, bo sobie posortuje to w kwerendzie. Jednak zasób wydaje się wyświetlać zwroty losowo, data utworzenia pierwszego zwrotu według zasobu jest późniejsza od drugiego zasobu. Potem jest kilkadziesiąt zwrotów z malejącą datą w stosunku do drugiego zwrotu i nagle skok w czasie do przodu. I tak przez całą kolekcję.
Ja rozumiem, że to beta ale aż miałem wątpliwości, czy powinienem używać parametru `from` w wyszukiwaniu, bo nie wiem czy wybierając ostatnie UUID otrzymam kolejne zwroty czy jednak powtórzą się one z poprzedniego zapytania. Straszny chaos z tym jest, a ten zasób jest całkiem potrzebny.

A i swoją drogą, ustawiając duży offset np. `20000` i limit na `1000` występuje błąd HTTP `504`.
Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
Wyjaśniam tę sytuację z zespołem odpowiedzialnym za funkcjonalność. Wrócę z odpowiedzią, gdy uda mi się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Co do pierwszego pytania, to jest to prawidłowe zachowanie. Zwrot ma 2 "paczki":  "Wysyłka własna" i przewoźnik wspierany przez nas, np DPD:
```
{
  "createdAt": "2022-03-21T09:57:11.158Z",
  "waybill": null,
  "carrierId": null,
  "sender": {
    "phoneNumber": "+48*********"
  }
},
{
  "createdAt": "2022-03-21T09:57:52.970Z",
  "waybill": "0000****",
  "carrierId": "DPD",
  "sender": {
    "phoneNumber": "+48********"
  }
}
```
Dla wysyłki własnej nie znamy przewoźnika ani waybilla.

Co do pozostałych dwóch tematów, czekam jeszcze za odpowiedzią.

**Comment by PrzemyslawLukanowski** [comment]
Co do kolejności zwrotów - są trzymane w kolejności ich zaindeksowania, która zwykle pokrywa się z kolejnością ich utworzenia przez Kupującego.
Parametr from służy do umożliwienia iterowania po kolekcji zwrotów w sposób przyrostowy. W szczególności, jeżeli chcemy synchronizować kolekcję zwrotów ze swoją lokalną kopią, to wystarczy zapamiętać na jakim zwrocie ostatnio synchronizacja się zakończyła i podać je przy następnej synchronizacji w polu from. Wtedy zostaną zwrócone tylko te zwroty, które zostały zaindeksowane później niż podany w polu from zwrot. W takim użyciu nie ma ryzyka, że jakieś zwroty zostaną pominięte.

`A i swoją drogą, ustawiając duży offset np. 20000 i limit na 1000 występuje błąd HTTP 504.`
HTTP 504 to timeout, możesz założyć wtedy, że pytasz o zbyt wiele danych.

**Comment by hahyes** [comment]
> W takim użyciu nie ma ryzyka, że jakieś zwroty zostaną pominięte.

Zdążyłem przetestować to u siebie, ale dziękuję za potwierdzenie i wszystkie informacje. Pozdrawiam.
