### ISSUE TITLE
Upload zdjęć - Unsupported Media type

### ISSUE THREAD

**Issue by morawcik** [allegro/allegro-api#5553]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Do tej pory korzystałem z uploadu przez url ale z pewnych powodów chciałem przejść na przesyłanie pliku bezpośrednio. Niestety otrzymuję 415 Unsupported media type - np. dla trace id 40d428ae093b5b8

Url: https://upload.allegro.pl.allegrosandbox.pl/sale/images
Accept: application/vnd.allegro.public.v1+json
Content-type: image/jpeg, image/png (próbowałem też "image/jpeg", "image/png")
Accept-Language: pl-PL

Samo zdjęcie to samo, które przesyłałem przez url (i działało).

**Comment by AureliuszBrussy** [comment]
W `"Content-type"` przekaż jedną z wartości: `image/jpeg` lub `image/png`.

**Comment by morawcik** [comment]
Niestety dalej to samo.

**Comment by AureliuszBrussy** [comment]
@morawcik upewnij się proszę, czy nie wysyłasz dwóch nagłówków `Content-type`. W requeście trace-id 40d428ae093b5b8 przekazywałeś w nagłówku wartość `image/jpeg, image/png,image/jpeg`. Oczywiście upewnij się także, że przesłany obrazek faktycznie jest w formacie .png lub .jpeg (obsługujemy także .webp).
