### ISSUE TITLE
Dostęp do kategorii fajerwerki - sandbox

### ISSUE THREAD

**Issue by MarcinEtna** [allegro/allegro-api#5554]
Witam, proszę o odblokowanie dodawania produktów w Kategorii Fajerwerki w sandbox dla konta EtnaTest.
Jest mi to niezbędne do testowania aplikacji.

**Comment by PrzemyslawLukanowski** [comment]
Odblokowaliśmy taką możliwość na wskazanym koncie.

**Comment by MarcinEtna** [comment]
Świetnie, mam jeszcze jeden problem przy wystawianiu ofert zwraca mi informację:
"Nie masz wymaganych uprawnień, aby wystawić ofertę (sprzedaż zablokowana). Zweryfikuj swoje konto jako firmowe."

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz podać przykładowe trace-id albo zrzut ekranu z tym błędem? Po naszej stronie konto wygląda na w pełni aktywne.

**Comment by MarcinEtna** [comment]
Sorry za zamieszanie ale okazało się że miałem jakieś "nieuregulowane płatności" i dlatego się sprzedaż zablokowała na tym koncie. Dzięki wielkie za support :) - smiga wszystko
