### ISSUE TITLE
Problem z dodaniem umowy z przewoźnikiem GLS 

### ISSUE THREAD

**Issue by Krzykolod** [allegro/allegro-api#5555]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Problem występuje przy próbie dodania umowy z przewoźnikiem GLS. 
[https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia](url)
Po uzupełnieniu formularza Umowy własne - wysyłam z Allegro oraz uzupełnieniu poprawnych danych dostępowych API pojawia się błąd wskazujący, jakoby API przewoźnika było niedostępne.
Nie jest to prawda, po naszej stronie (GLS) w logach widzimy że dla tego użytkownika API nie jest wysyłany żaden request ze strony Allegro, API nie jest odpytane, dlatego błąd nie może leżeć po stronie naszego interfejsu API.
Problem występuje zarówno w środowisku sandbox jak i produkcyjnym

![Allegro_error](https://user-images.githubusercontent.com/102029448/159248039-9d6537d4-09ae-482f-b810-b18da63e2624.png)

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz jeszcze podać ID usera z Allegro, zarówno ze środowiska produkcyjnego, jak i testowego?

**Comment by PrzemyslawLukanowski** [comment]
Udało nam się znaleźć przyczynę problemu, pracujemy nad rozwiązaniem. Poinformuję o tym w wątku.

**Comment by Krzykolod** [comment]
ID usera ze środowiska testowego to 44089270
Co produkcyjnego to uzyskam, ponieważ inna osoba sprawdzała czy to działa na produkcji i nie mam na tą chwilę tego konta
Dziękuję za informację

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, dane już nie będą potrzebne, pracujemy nad rozwiązaniem.

**Comment by PrzemyslawLukanowski** [comment]
Problem nie powinien już występować.

**Comment by Krzykolod** [comment]
Niestety problem występuje nadal, zarówno w środowisku sandbox jak i produkcyjnym, komunikat "API przewoźnika jest niedostępne" jest w tym przypadku nieprawidłowy, ponieważ żaden request nie dociera do naszego API.

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem ponownie. Wrócimy z odpowiedzią, gdy uda nam się ustalić więcej szczegółów.

**Comment by MaciejFrackowiak** [comment]
@Krzykolod Rzeczywiście, po wdrożeniu poprawki problem ponownie powrócił. Obecnie zespół odpowiedzialny za funkcjonalność pracuje nad ostatecznym wyeliminowaniem błędu. Proszę o dalszą cierpliwość.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy odpowiednią poprawkę, problem nie powinien już występować.

**Comment by Krzykolod** [comment]
Dziękuję, wszystko działa już prawidłowo.
