### ISSUE TITLE
/order/checkout-forms

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#5556]
Prosze o weryfikacje zamowienia d9b47121-a46b-11ec-8e3c-7f28d5127b70, REST zwraca  info ze zamowienie jest niepłacone i ma status "Filled_in", tymczasem na froncie widnieje jako opłacone, co potwierdza na czacie Wasz support.

**Comment by kulisz** [comment]
@PrzemyslawLukanowski przyłączam się do kolegi wyżej, u Nas też ten sam problem, front allegro i mail wskazuje że jest opłacone, rest api zwraca filled_in bez płatności, zamówienie numer "01fdb472-a46c-11ec-aa37-bdabce94ca6c", proszę o szybkie sprawdzenie, miejmy nadzieje że to pojedynczy przypadek
