### ISSUE TITLE
INVALID_JSON - Nieprawidłowe żądanie

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#5557]
TraceId: b74c24f78f9baefb

Request: PUT https://api.allegro.pl/sale/offers/11383636358

Response:
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => INVALID_JSON [message] => Invalid request. [details] => [path] => [userMessage] => Nieprawidłowe żądanie. ) ) )

Przy wywoływaniu zasobu pojawia się komunikat jak wyżej, bez żadnych konkretów. Problem występuje w wielu ofertach pokolei.

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę przykładowy request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5557.

**Comment by rasskabak** [comment]
Wysłany

**Comment by MartaNowaczyk** [comment]
Ok, jak tylko otrzymamy dane zajmiemy się weryfikacją.

**Comment by Lukasz-Zurek** [comment]
@rasskabak 

W sekcji parametrów jest błąd. Przekazujesz:

```
      {
         "id": 129129,
         "valuesIds": "inny"
      },
```

a powinieneś przekazać:

```
       {
           "id": "129129",
           "valuesIds": [
               "129129_21"
           ]
       },
```
