### ISSUE TITLE
Uploadin Product duplicate record problem

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5559]
Hi,

I see that I have created duplicate records while uploading a product. I am trying to detect the error in the code. The start dates of the records created by Allegro seem to be exactly the same or very close to each other. Even if I send duplicate records, it seems very unlikely that I can create them at the same time on the allegro side.
I have one trace-id, can you check this status on the api side?

offerid            externalid                                                         StartedAt
11971676479 CC342A70-3457-4C75-8DD4-B10B57837FEB 2022-03-22 06:17:58,000
11971676469 CC342A70-3457-4C75-8DD4-B10B57837FEB 2022-03-22 06:17:57.000
11971676460 CC342A70-3457-4C75-8DD4-B10B57837FEB 2022-03-22 06:17:57.000

_traceId:5f4b015bde38767e

thanks

**Comment by Lukasz-Zurek** [comment]
You have created all of the products while listing an offer via [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers).

1. First of all, as I see - you have created an offer **11971676460** and simultaneously you have created a product: **09ffd8b1-cde8-4b31-b2ff-1c4f238aa1db** (2022-03-22 07:17:55).

2. Then you have created two more offers:

- **11971676469** and a product: **ae0ffa4b-aaac-4e55-915b-5cdc4326e370** (2022-03-22 07:17:56)
- **11971676479** and a product: **cd9d5c65-1fea-4f48-bda5-54accb35224f** (2022-03-22 07:17:56)

which happened at a very similar time, which made duplicates in our product database. This is not a common situation in our API but it is possible.

So as you have already mentioned - you should detect the error on your side regarding listing your offers.

**Comment by yavuzresif** [comment]
Thank you for reply
