### ISSUE TITLE
Nie można opublikować ofert przez API

### ISSUE THREAD

**Issue by unkn0wn0** [allegro/allegro-api#556]
Występuje błąd "Could not change offer publication status. Date starting at cannot be from past."

Czy coś zostało zmienione, że występuje taki komunikat?

**Comment by MartaNowaczyk** [comment]
Prześlij proszę request i response w formacie XML z widocznym błędem.

**Comment by ircykk** [comment]
U mnie jest ten sam problem, tymczasowym rozwiązaniem jest przy publikacji ustawienie `scheduledFor` na +5 minut.

**Comment by MartaNowaczyk** [comment]
@unkn0wn0 @ircykk  Zajmujemy się tą sprawą i to z wysokim priorytetem. Zbliżamy się ku końcowi, także trzymajcie kciuki za poprawkę.

@unkn0wn0 przykłady już niepotrzebne :)

**Comment by MartaNowaczyk** [comment]
@unkn0wn0 i @ircykk Powinno być ok. Sprawdźcie proszę czy możecie wystawiać.

**Comment by ircykk** [comment]
Tak działa teraz poprawnie, dzięki.

**Comment by MartaNowaczyk** [comment]
Dzięki za informację, zamykam.
