### ISSUE TITLE
Graniczne godziny zamówień dla X-Press Couriers

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#5563]
Czy jest możliwość ustawienia poprzez API godziny do której kupujący może złożyć zamówienie dla sposobu dostawy: X-Press Couriers?

![image](https://user-images.githubusercontent.com/97017267/159507380-c6606e95-6d44-4ea0-a1cc-337c65224c6e.png)

**Comment by Lukasz-Zurek** [comment]
@glinkaa Nie mamy takiej funkcjonalności w naszym API.
