### ISSUE TITLE
Activating production account

### ISSUE THREAD

**Issue by tom598** [allegro/allegro-api#5564]
Hello,

Can you verify our production account is setup correctly?
I am trying to fetch the bearer-token-for-application.

grant_type: client_credentials
client_id: b1f2765f22a94f9792d8a6aa18c1419d

response:  `{"error":"Unauthorized","error_description":"Unauthorized"}`

**Comment by Lukasz-Zurek** [comment]
You are using an access_token without the user context. Using token generated with [Client_credentials flow](https://developer.allegro.pl/en/auth/#client-credentials-flow) you can only access the resources marked as “bearer-token-for-application” in the “Authorizations” section in [documentation](https://developer.allegro.pl/en/documentation) - for example - the resources which give access to public data, e.g. retrieving a list of categories, parameters, etc.

You should generate a token using [Authorization Code flow](https://developer.allegro.pl/en/auth/#authorization-code-flow) or [Device flow](https://developer.allegro.pl/en/auth/#device-flow). Then you will get an access to creating products or offers, getting orders, offers etc. We marked these resources as "bearer-token-for-user".

**Comment by tom598** [comment]
Hello,
This does not answer my question, please read my question carefully

**Comment by Lukasz-Zurek** [comment]
Ok, I am sorry. Please send me your full request via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). In your report please add information about this thread - GitHub #5564.

**Comment by tom598** [comment]
We had contact via ContactForm, Kamil Glapa explained that we should receive a response in this thread

**Comment by Lukasz-Zurek** [comment]
@tom598 I have already read your e-mail. You sent the same information as mentioned in this thread. But we need a full request to verify it closely.

Note the fact that **401 Unauthorized** could happen when you provided an incorrect `"client_id:client_secret"` data encoded along with `":"`. Please check this data first.

**Comment by tom598** [comment]
See below our request,
I want to add that this is the same logic we use for the sandbox (except of course for the url and the authorization header) which is working.

production oauth client_id: b1f2765f22a94f9792d8a6aa18c1419d

Request:
url: ﻿[https://allegro.pl/auth/oauth/token](https://allegro.pl/auth/oauth/token)
﻿method: POST
﻿Headers:
﻿﻿Content-Type: ﻿application/x-www-form-urlencoded
﻿﻿Accept: application/json
﻿﻿Authorization: xxx

﻿RequestBody:
﻿grant_type=client_credentials

﻿Response:
﻿httpCode: 401
﻿body: ﻿{"error":"Unauthorized","error_description":"Unauthorized"}

**Comment by tom598** [comment]
If there is a secure place where I could send the base64 encoded authorization header, I would like to know.

**Comment by Lukasz-Zurek** [comment]
@tom598 I verified your request. You did not encode client_id:client_secret (data obtained upon application registration) as [Base64](http://base64encode.org/) with the ":" sign between the values. You did encode without ":" and this is why you receive 401 error (Unauthorized). You should correct it.
