### ISSUE TITLE
api  /sale/products nie jest zwracane

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5566]
Wywołując api /sale/products w parametrach nie ma ean, na podświetleniu jakoś go dociągacie. Jest możliwość zwrócenia go przez jakieś api ? 
![image](https://user-images.githubusercontent.com/6718212/159590760-ffc63fa7-d513-4440-aee0-1537d7d34755.png)

**Comment by Lukasz-Zurek** [comment]
Kod EAN zwrócimy tylko, gdy pobierzesz dane konkretnego produktu, czyli za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct).
