### ISSUE TITLE
Wielkość liter w nazwie użytkownika zwracana przez "List messages in thread"

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#5567]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Nazwa Użytkownika w polu author.login jest z małych liter.

{
  "messages": [
    {
      "id": "string",
      "status": "VERIFYING",
      "type": "MESSAGE_CENTER",
      "createdAt": "2022-03-23T08:58:22Z",
      "thread": {
        "id": "string"
      },
      "author": {
        "**login**": "string",
        "isInterlocutor": true
      },
      "text": "string",
      "subject": "string",
      "relatesTo": {
        "offer": {
          "id": "string"
        },
        "order": {
          "id": "string"
        }
      },
      "hasAdditionalAttachments": false,
      "attachments": [
        {
          "fileName": "string",
          "mimeType": "string",
          "url": "string",
          "status": "NEW"
        }
      ]
    }
  ],
  "offset": 0,
  "limit": 0
}

**Comment by tomasz-grzesik** [comment]
Nadal mam zgłoszenia od Użytkowników, że przydałaby się rzeczywista wielkość liter.

**Comment by Lukasz-Zurek** [comment]
@tomasz-grzesik Ponownie uderzyłem do zespołu odpowiedzialnego za tę funkcjonalność. Otrzymałem wcześniej informację, że zostanie to dostosowane. Tym bardziej dziękuję Ci za nową wiadomość w wątku.
