### ISSUE TITLE
503 GET /offers/listing

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#5568]
Dzień dobry
Jeden z Klientów zgłasza mi od wczoraj błąd 503 Serwer jest niedostępny.: Serwer nie jest w stanie zrealizować zapytania. Spróbuj ponownie za kilka minut.  na  GET /offers/listing
Czy coś się dzieje?

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry, dziękuję za zgłoszenie. Tak, potwierdzam, że wystąpiły chwilowe problemy po naszej stronie, aktualnie nie powinny już mieć miejsca. Przepraszam za utrudnienia.

**Comment by rtnet-pl** [comment]
Dziękuję, działa

**Comment by rtnet-pl** [comment]
Błąd niestety powrócił

**Comment by PrzemyslawLukanowski** [comment]
Weryfikujemy ten problem. Wrócę z informacją, gdy uda się ustalić więcej szczegołów.

**Comment by PrzemyslawLukanowski** [comment]
Problemy w tym przypadku powodują zapytania użytkownika, które wykorzystują nawias w parametrach. Dla fraz w nawiasie wykorzystujemy składnię LUB - jeśli odpowiedź uwzględnia wiele wyników, może się to zakończyć odpowiedzią 503.

**Comment by PrzemyslawLukanowski** [comment]
Hello, we don't return such data. You can only have access to parameters and descriptions of offers that belongs to you, as an authorized seller.

**Comment by rtnet-pl** [comment]
Ponownie ten sam klient zgłasza nam dużo błędów 504: Gateway timeout, trwa to od 1.10

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku przyczyna problemu jest podobna, jak ostatnim razem:

> Problemy w tym przypadku powodują zapytania użytkownika, które wykorzystują nawias w parametrach. Dla fraz w nawiasie wykorzystujemy składnię LUB - jeśli odpowiedź uwzględnia wiele wyników, może się to zakończyć odpowiedzią 503/504.

**Comment by rtnet-pl** [comment]
ok, dziękuję, przeoczyłem tą odpowiedź z kwietnia
