### ISSUE TITLE
Brak opcji dostawy Allegro One

### ISSUE THREAD

**Issue by mtanasiewicz** [allegro/allegro-api#5571]
Dzień dobry,

Nie moge dodać Allegro One do cennika dostaw dla swoich aukcji w sandboxie. Próbowałem przeszukać już dokumentację i issues na githubie, ale nic na ten temat nie znalazłem. Te opcje nie istnieją na moim koncie sprzedażowym. Identyfikator konta to: 104788165. Uprzejmie proszę o nakierowanie . 

EDIT: Czy to może wymaga jedynie włączenia usługi SMART?

**Comment by AureliuszBrussy** [comment]
Twoje konto powinno mieć status firma - dopiero wtedy będziesz mógł udostępnić tą metodę dostawy. Zmień swoje konto na firmowe z poziomu zakładki [Dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) lub zarejestruj [nowe konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto).

**Comment by mtanasiewicz** [comment]
@AureliuszBrussy Podczas próby konwersji konta na firmowe, dostaję 404. Jest jakiś inny sposób aby to zrobić?

**Comment by mtanasiewicz** [comment]
@AureliuszBrussy znalazłem wątek z przekształcacniem konta i zadziałał link, który był tam podany. Uprzejmie poproszę o zatwierdzenie zgłoszenia zmiany konta na firmowe.

**Comment by AureliuszBrussy** [comment]
@mtanasiewicz Twoje konto jest już aktywne - możesz skorzystać z metody Allegro One w cenniku dostawy.

**Comment by mtanasiewicz** [comment]
Potwierdzam, mam już Allegro One. Dziękuję :)

**Comment by awawrowicz** [comment]
Mam ten sam problem, tzn brak Allegro One w cenniku w sandbox. Moje konto jest firmowe, nazwa konta: expondo_test

**Comment by AureliuszBrussy** [comment]
@awawrowicz Twoje konto nie jest w pełni aktywne - musisz jeszcze przejść weryfikację konta firmowego. Wypełnij proszę [formularz weryfikacji konta](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty?showOnboardingProgressMsg=true) fikcyjnymi danymi (przejdź wszystkie kroki). Gdy to zrobisz - wróć do mnie z informacją, zakończę aktywację konta.

**Comment by awawrowicz** [comment]
> Gdy to zrobisz - wróć do mnie z informacją, zakończę aktywację konta.

zrobione

**Comment by AureliuszBrussy** [comment]
@awawrowicz aktywowałem Twoje konto. Allegro One powinno być już dostępne.

**Comment by awawrowicz** [comment]
Jest super, dziękuję
