### ISSUE TITLE
Wartości pola delivery.handlingTime

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5572]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Jak to jest z wartościami pola delviery.handlingTime na zasobie /sale/offers, według dokumentacji 
Handling time, ISO 8601 duration format. This field must be set to one of the following: PT0S for immediately, PT24H, P2D, P3D, P4D, P5D, P7D, P10D, P14D, P21D, P30D, P60D.
może przyjmować tylko określone wartości natomiast mam oferty które zwracają za api wartość PT48H. Czy to jest jakaś przestarzała wartość i jest równoznaczna z wartością P2D czy jednak coś innego?

**Comment by AureliuszBrussy** [comment]
Wartości te możesz podawać również w godzinach. PT48H jest równe P2D, tak samo zamiast wartości P3D - możesz przekazać wartość PT72H.
