### ISSUE TITLE
Oferty Allegro i logowanie

### ISSUE THREAD

**Issue by AureliuszBrussy** [allegro/allegro-api#5573]
### Discussed in https://github.com/allegro/allegro-api/discussions/5570

<div type='discussions-op-text'>

<sup>Originally posted by **Byweris** March 24, 2022</sup>
Hej,
Nie jestem programistą i nie zbadałem całkowicie allegro api, więc chciałbym uzyskać potwierdzone informacje, jeśli taki przypadek jest możliwy:

Czy mogę za pomocą API otrzymywać oferty umieszczane w mojej sieci? Co więcej, zaimplementuj również login allegro jako moją główną strukturę logowania do strony internetowej?
Zasadniczo robienie mniejszej wersji allegro, gdzie publiczność loguje się i kupuje produkty allegro tylko na mojej stronie?

Naprawdę doceniam twoje wyczerpujące odpowiedzi,
dzięki </div>

**Comment by AureliuszBrussy** [comment]
@Byweris nie udostępniamy zasobów pozwalających na dokonywanie zakupów w imieniu użytkownika (możliwe jest tylko złożenie oferty w licytacji). Ponadto prezentowanie w innym serwisie ofert, które nie należą do Ciebie jest niezgodne z [regulaminem](https://developer.allegro.pl/rules/) API Allegro. 

Możliwe jest natomiast zrealizowanie platformy sklepowej, która powiązana jest z API Allegro i oferta Allegro w takich przypadkach może być synchronizowana ze sklepem internetowym.

**Comment by Byweris** [comment]
dziękuję za odpowiedź, przepraszam za umieszczenie pytań w niewłaściwym miejscu.

Trochę informacji do wyjaśnienia: sklep jest mój i należy do mnie.
Mój cel to
  1. zaimplementować loginy allegro jako główny system logowania do sklepu. 
  2. przenieś oferty z allegro na moją stronę.

w moim sklepie - czy moi widzowie mogą się logować używając loginu allegro i umieszczać oferty allegro w moim sklepie, ale czy trafiłbym na allegro.pl jako zwykłe zamówienie ?

Zakładam, że nie jest to sprzeczne z przepisami?

Mam nadzieję, że wyjaśniłem teraz jaśniej.

**Comment by AureliuszBrussy** [comment]
W procesie uwierzytelniania i autoryzacji użytkownika (aby aplikacja mogła działać w jego imieniu) konieczne jest zalogowanie się użytkownika do Allegro. Technicznie możliwe jest, aby taki proces zintegrować z rejestracją i logowanie konta na stronie.

Można zaimplementować wystawianie ofert w sklepie tak, aby taka oferta trafiła również do Allegro. Natomiast czym innym jest prezentowanie tych ofert innym użytkownikom. 

Proszę, zapoznaj się z regulaminem API Allegro, w szczególności z punktem 4, czyli "Zakres wykorzystania oprogramowania REST API". Dowiesz się, w jakich celach API nie może być wykorzystywane.

**Comment by Byweris** [comment]
dzięki za informacje o opcji logowania.

W sprawie ofert pragnę doprecyzować : chcielibyśmy sprowadzić oferty z allegro i opublikować je w naszym sklepie, ale zachować bezpośredni kontakt, tzn. przy zakupie zamówienie będzie w systemie allegro.
Nie planujemy robienia niestandardowych zamówień i umieszczania ich na allegro.pl.

Naszym celem jest ZAWSZE pracować pod loginem i ofertami allegro.pl, po prostu prezentować je za pośrednictwem naszej platformy.

Dopóki czytam, nie jest to sprzeczne z przepisami, proszę o wyjaśnienie, czy jest to możliwe.
dzięki

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniałem w pierwszej wiadomości - nie udostępniamy zasobów umożliwiających złożenia zamówienia na Allegro.
