### ISSUE TITLE
Lista kategorii z parametrami zależnymi

### ISSUE THREAD

**Issue by glinkaa** [allegro/allegro-api#5574]
Czy jest gdzieś dostępna lista kategorii, w których występują parametry zależne?

**Comment by MartaNowaczyk** [comment]
Nie dostaniesz gotowej listy, ale możesz to sprawdzić pobierając parametry dla danej kategorii [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). Wystarczy zwrócić uwagę na wartość dla "requiredDependsOnValueIds".
