### ISSUE TITLE
/order/events

### ISSUE THREAD

**Issue by JacekStawicki360** [allegro/allegro-api#5576]
Cześć
jak pobrać zdarzenia od konkretnej daty?
Nie widzę takiej możliwości bez ściągnięcia całości dziennika.

Czy dziennik zdarzeń ma jakiś max historię? Czy pobiera się wszystko od samego początku?

**Comment by Lukasz-Zurek** [comment]
Nie pobierzesz zdarzeń od konkretnej daty. Możesz jednak pobrać kolejne porcje zdarzeń używając identyfikatorów zdarzeń za pomocą:

**GET /order/events?from={last_seen_event_id}**.

Dodam, że pobierzesz zdarzenia maksymalnie z ostatnich 60 dni.

Więcej informacji na temat dziennika zdarzeń znajdziesz w naszym [poradniku](https://developer.allegro.pl/orders/#dziennik-zdarzeń).

**Comment by hahyes** [comment]
> jak pobrać zdarzenia od konkretnej daty?
> Nie widzę takiej możliwości bez ściągnięcia całości dziennika.

@JacekStawicki360 
Parametr `from` czy też `eventId` zdarzenia to jest rodzaj daty zwany Unix timestamp, podany w mikrosekundach od 1 stycznia 1970 roku. 
Aby zacząć pobierać od konkretnej daty należy utworzyć timestamp.
Użyj tego narzędzia i stwórz datę od której chcesz zacząć: https://www.epochconverter.com/
Potem do timestampa interesującej cię daty dodaj 6 zer, żeby był to timestamp mikrosekundowy.
Następnie podaj ten timestamp jako parametr `from` w zapytaniu.
