### ISSUE TITLE
Referencja na etykiecie Allegro One

### ISSUE THREAD

**Issue by LukaszMalekBH** [allegro/allegro-api#5577]
Dzień dobry, 

1. Nie jesteśmy w stanie dodać referencji z numerem zamówienia na etykiecie w ramach wysyłam z allegro a konkretnie Allegro One. Czy wszystkie pola na uwagi są zarezerwowane dla was i z poziomu api nic nie można już dodać?

2. Czy normalnym jest to, że na etykiecie UPS Allegro One nie drukują się polskie znaki? Czy jest to dla was jakiś problem?

**Comment by Lukasz-Zurek** [comment]
@LukaszMalekBH Skonsultuję sprawę z odpowiednim zespołem. Wkrótce wrócę do Ciebie z odpowiedzią.

**Comment by LukaszMalekBH** [comment]
@Lukasz-Zurek  OK, czekam na update.

**Comment by Lukasz-Zurek** [comment]
1. Jeśli chodzi o [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel) - w sekcji **"label"**, w polu **"referenceNumber"** możesz przekazać wartość alfanumeryczną od 0 do 35 znaków. Natomiast id zamówienia zawiera 36 znaków, dlatego jak wprowadzisz id zamówienia - otrzymasz błąd 400 (Bad request).

2. Skonsultowałem ten temat. Potrzebujemy jednak przykładowej etykiety, aby zaadresować ten problem do firmy, z którą współpracujemy w tym zakresie. Będę wdzięczny za przesłanie przykładowej, problematycznej etykiety.

**Comment by LukaszMalekBH** [comment]
@Lukasz-Zurek 

'Natomiast id zamówienia zawiera 36 znaków' O jakim polu mówimy na etykiecie? Reference 1 czy reference 2? O jakim 36 znakowym numerze mówimy?

Poniżej zrzut etykiety z błędnym formatowaniem języka i polami z referencją:
[https://drive.google.com/file/d/1enhbo6SuBmkJPaTfXtHLSDtZ517TpEwT/view?usp=sharing](url)

Tutaj kod etykiety w formacie zpl:
[https://drive.google.com/file/d/1faqnOb1B1u1JT3UO_W8uorsYSBE6HDVT/view?usp=sharing](url)

Proszę wystąpić o uprawnienia do plików z maila @allegro a udostępnię Panu te dwa pliku.

**Comment by Lukasz-Zurek** [comment]
@LukaszMalekBH Mam tu na myśli pole **"referenceNumber"**, zgodnie z [dokumentacją](https://developer.allegro.pl/documentation/#operation/createNewParcel). Pole **"referenceNumber"** jako Reference 1. Niestety jest tak, że nie u każdego przewoźnika taki numer pojawi się na etykiecie. Druga sprawa - wspomniane 36 znaków ma id zamówienia, np. 2125ee00-aa8c-11ec-9f73-ad0e6e55b4f0. Napisałem o tym z uwagi na Twój problem dotyczący dodania referencji z numerem zamówienia na etykiecie.

Generalnie tworząc paczkę przez Allegro API, nie przekażesz niestety tego typu danych. Pomijam tutaj odrębne limity u przewoźników (np. DPD ogranicza to pole do 28 znaków).

Co do załączonych linków do zrzutu i kodu etykiety w formacie zpl - prześlij proszę te pliki za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5). Tak będzie najlepiej. Przekażę je od razu do zespołu odpowiedzialnego za tę funkcjonalność.

**Comment by LukaszMalekBH** [comment]
'Pole "referenceNumber" jako Reference 1. Niestety jest tak, że nie u każdego przewoźnika taki numer pojawi się na etykiecie. Druga sprawa - wspomniane 36 znaków ma id zamówienia, np. 2125ee00-aa8c-11ec-9f73-ad0e6e55b4f0. Napisałem o tym z uwagi na Twój problem dotyczący dodania referencji z numerem zamówienia na etykiecie.' Generalnie tworząc paczkę przez Allegro API, nie przekażesz niestety tego typu danych. 

Mówimy o Allegro One (UPS) - tutaj jak rozumiem mamy 36 znaków do wykorzystania. Dalej piszesz jednak, że przez api nie mogę przekazać tego typu danych... Będę wdzięczny za finalną informację: czy w ramach pola referenceNumber lub innego pola dla Allegro one (BOX oraz Point) mogę przesłać ciąg znaków, który będzie naszym wewnętrznym numerem zamówienia (ma 7 znaków - na upartego możemy ten numer skrócić) - taki ciąg znaków ma pojawić się w dowolnym miejscu na etykiecie, którą wydrukujemy.

**Comment by LukaszMalekBH** [comment]
@Lukasz-Zurek 

Panie Łukaszu, nie jestem w stanie wysłać etykiety w formacie zpl przez wskazany formularz.

**Comment by Lukasz-Zurek** [comment]
@LukaszMalekBH Już rozwiewam wątpliwości. W przypadku przesyłek Allegro One nie przekażesz ciągu znaków, np. wewnętrznego numeru zamówienia, niezależnie od limitu. Za pomocą API, dla tego typu przesyłek - nic w tym miejscu nie dodasz. 

Co do etykiety - powinna się ona generować z polskimi znakami. Jeśli nie masz możliwości wysłania etykiety w formacie zpl, prześlij proszę sam zrzut z błędnym formatowaniem języka i polami z referencją.
