### ISSUE TITLE
Sprawdzanie sprzedaży.

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#558]
Jak sprawdzić ostatnią sprzedaż na wybranej aukcji.
Potrzebuję otrzymać  datę kiedy była ostatnia sprzedaż.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Informacje na temat obsługi zamówień znajdziesz w tym [poradniku](https://developer.allegro.pl/orders/).
