### ISSUE TITLE
Cannot create an offer in the sandbox environment

### ISSUE THREAD

**Issue by shing1001** [allegro/allegro-api#5580]
Hello, 

We tried to create an offer in the sandbox environment and received the error message "Failed to create an offer."

Then we also tried to choose "continue without selecting any product", and got the same error. could you advise what's the problem? thank you. 

![Screenshot 2022-03-29 at 10 24 03](https://user-images.githubusercontent.com/101405352/160562225-5613056a-c6b4-4c57-bffe-93510bd0846d.png)
![Screenshot 2022-03-29 at 10 49 42](https://user-images.githubusercontent.com/101405352/160562236-bdb39a63-be00-4f75-b006-e282a0e29562.png)

**Comment by MaciejFrackowiak** [comment]
You have to [set payouts and verify your company account](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto), then you will be able to list an offer on Sandbox.

**Comment by shing1001** [comment]
Thank you for your reply. 
As it is a sandbox environment, could we give fake data for account verification? Thanks.

**Comment by MaciejFrackowiak** [comment]
Yes, it is necessary to use fake data, not a real one.

**Comment by shing1001** [comment]
Thank you. 
I have submitted all the dummy data but it is on pending for over an hour. is it normal?

![Screenshot 2022-03-29 at 11 59 46](https://user-images.githubusercontent.com/101405352/160574785-3c342a6b-8da5-4771-b27e-d907f9e84d07.png)

**Comment by MaciejFrackowiak** [comment]
It can last a minute or more - as I see your account is verified now.

**Comment by shing1001** [comment]
sorted. Thank you.
