### ISSUE TITLE
Powiązanie id metody dostawy w zamówieniu z metodami płatności z /parcel-management/delivery-services

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#5581]
Moje pytanie jak w temacie. 
W zamówieniu dostaję informacji o wybranej metodzie dostawy w formie:
"method": {
            "id": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
            "name": "Allegro One Box"
        },
W jaki sposób "przełożyć" to na listę usług dostawy otrzymaną w formie:
{
            "id": 11237538,
            "service": "ALLEGRO",
            "name": "Allegro One",
            "owner": "ALLEGRO",
            "carrierId": "ALLEGRO",

**Comment by MaciejFrackowiak** [comment]
Nie mamy bezpośredniego mapowania form dostawy z usługami dostępnymi w ramach Wysyłam z Allegro. Posiłkując się jednak [GET /sale/delivery-methods](https://developer.allegro.pl/documentation/#operation/getListOfDeliveryMethodsUsingGET) otrzymujemy istotne szczegóły:

```
{
            "id": "0aafb43c-e66a-46ec-9cc4-29bb39ebb483",
            "name": "Allegro One Box",
            "paymentPolicy": "IN_ADVANCE",
            "allegroEndorsed": true,
            "shippingRatesConstraints": {
                "allowed": true,
            ...
```

W połączeniu z [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices) i dostępną usługą:

```
{
            "id": xxxxxxx,
            "service": "ALLEGRO",
            "name": "Allegro One",
            "owner": "ALLEGRO",
            "carrierId": "ALLEGRO",
            "additionalServices": {
                "cashOnDelivery": {
                    "available": false,
                    "expressAvailable": false
                },
                "options": []
            }
        },
```

można dokonać takiej "ręcznej" korelacji.

**Comment by SlawekMat** [comment]
Ma pan na myśli, że trzeba sobie samemu zrobić mapowanie tego? Bo ja nie widzę żadnego elementu spójnego wiec chyba tylko pozostaje to zrobić samemu i modyfikować przy każdej zmianie po państwa stronie.

**Comment by MaciejFrackowiak** [comment]
Pod Allegro One Box kryją się automaty paczkowe Allegro. Całość usług dostawy świadczona przez Allegro to [One by Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/allegro-one/allegro-one-informacje-dla-sprzedajacych-2YVLlRloquD), zatem w serwisie WzA w przypadku wskazanego zamówienia możesz skorzystać z nadania paczki do automatu paczkowego Allegro.

**Comment by SlawekMat** [comment]
Mi zależy na przygotowaniu paczki za pomocą /parcel-management/parcel-create-commands/
W wywołaniu wymagane jest podanie serviceId i nie wiem skąd mógłbym go pobrać poza indywidualnym przygotowaniem tablicy podstawień. 
Allegro One Box to tylko przykład.

**Comment by MaciejFrackowiak** [comment]
Dla każdego użytkownika dostępne usługi mogą mieć różne id, dlatego kluczowe jest pobranie dostępnych usług poprzez [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices). Cały flow zarządzania przesyłkami opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY).

**Comment by SlawekMat** [comment]
Ja to wszystko już przeczytałem i chyba ze zrozumiem, ale nie znalazłem tam odpowiedzi.
Czy dobrze rozumiem, że nie ma żadnej metody na połączenie tych dwóch informacji i pozostaje tylko indywidualne mapowanie tych usług? Bo ani w moich usługach nie ma id metody dostawy z zamówienia. Ani też nawet nazwa w jednym i drugim przypadku nie są tożsame.

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak, wspomniałem o tym w pierwszym komentarzu - nie ma 1:1 mapowania w postaci usługi z delivery-methods a delivery-services.

**Comment by SlawekMat** [comment]
Napisał pan, że nie ma bezpośredniego, sugeruje to, że można zrobić to jakąś dłuższą ścieżka. Zabrakło mi informacji, że musze sam o to zadbać.
Swoją drogą bardzo szkoda, każda zmiana u państwa będzie niosła za sobą dużo błędów.
Dziękuję za odpowiedź

**Comment by SlawekMat** [comment]
Niestety mam jeszcze jeden problem.
Na liście delivery-methods mam trzy usługi UPS (Allegro Kurier UPS, Allegro Kurier UPS pobranie, Allegro Odbiór w Punkcie UPS), natomiast na liście delivery-services tylko jeden id (Allegro UPS). Czy mam rozumieć, że mapowanie każdej usługi dostawy związanej z UPS mam kierować na Allegro UPS?

**Comment by MaciejFrackowiak** [comment]
Tak, jedna usługa z delivery-services może umożliwiać nadanie kilku typów metod dostawy - w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/metody-dostawy/wysylam-z-allegro-narzedzie-do-nadawania-przesylek-bezposrednio-z-konta-E7doGw8VgI1) znajdziesz dokładny zbiór i opis wg przewoźników.

**Comment by SlawekMat** [comment]
Dziękuję

**Comment by SlawekMat** [comment]
Niestety mam kolejny problem. Dotyczy środowiska testowego.
Przy próbie założenia paczki Allegro otrzymuje komunikat:
"errors": [
        {
            "code": "AUTHENTICATION_ERROR",
            "message": "No access to 'Wysyłam z Allegro'",
            "details": null,
            "path": "header.authorization",
            "userMessage": "Brak dostępu do 'Wysyłam z Allegro' przy użyciu client token"
        }
    ]
W opisie widzę, że do założenia paczki mam podać 
AUTHORIZATIONS:  [bearer-token-for-user]
W czym tkwi problem?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj login lub identyfikator swojego konta, sprawdzę to.

**Comment by SlawekMat** [comment]
neverland_pl

**Comment by SlawekMat** [comment]
Próbowałem dodać paczkę na obu kluczach i zawsze mam tą samą informację.

**Comment by MaciejFrackowiak** [comment]
Twoje konto nie było aktywne oraz nie zweryfikowałeś dotychczas konta jako firmowe. Przed momentem aktywowałem je, natomiast proszę zweryfikuj je jako firmowe na [stronie](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/wybierz-sciezke).

**Comment by SlawekMat** [comment]
Dziękuje za informację, ale czy żeby korzystać  z platformy testowej muszę podawać konto bankowe i robić przelew?

**Comment by MaciejFrackowiak** [comment]
Podaj proszę fikcyjne dane, a co do przelewu - na Sandbox działa symulator płatności, czyli de facto nie musisz robić realnego przelewu.

**Comment by SlawekMat** [comment]
Niestety po podaniu losowego nr konta i próbie przejścia dalej mam komunikat "Nie mogliśmy wybrać metody weryfikacji. Spróbuj ponownie później"

**Comment by SlawekMat** [comment]
Udało mi się przejść przy kolejnej próbie

**Comment by SlawekMat** [comment]
Niestety nadal mam problemy. Żeby zakończyć konfigurację konta muszę wystawić jakąś ofertę, natomiast nie mogę tego zrobić, mam komunikat "Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert."

**Comment by MaciejFrackowiak** [comment]
Proszę sprawdź teraz - ręcznie przeprocesowałem Twój wniosek, powinno być OK.

**Comment by SlawekMat** [comment]
Teraz się udało, ale i tak przy próbie założenia paczki przez API mam ten sam komunikat
{
    "errors": [
        {
            "code": "AUTHENTICATION_ERROR",
            "message": "No access to 'Wysyłam z Allegro'",
            "details": null,
            "path": "header.authorization",
            "userMessage": "Brak dostępu do 'Wysyłam z Allegro' przy użyciu client token"
        }
    ]
}

**Comment by MaciejFrackowiak** [comment]
Jak widzę posiadasz posiadasz na koncie już dostęp do zasobu [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices), zatem pozostałe zasoby związane z Wysyłam z Allegro powinny być aktywne.

**Comment by MaciejFrackowiak** [comment]
Korzystasz zatem z autoryzacji client_credentials, a zasoby odpowiedzialne za obsługę Wysyłam z Allegro wymagają "bearer-token-for-user", czyli autoryzacji [code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow). Zmień sposób autoryzacji i spróbuj ponownie wywołać zasób.

**Comment by SlawekMat** [comment]
No właśnie sposoby, którymi próbuję się autoryzować to code flow i device flow.  Niestety efektów nie ma

**Comment by SlawekMat** [comment]
Przeszedłem całą ścieżkę jeszcze raz i chyba się udało, może trzeba to było zrobić na aktywnym koncie

**Comment by SlawekMat** [comment]
Ale niestety nie jest łatwo cokolwiek sprawdzić na portalu testowym. 
Nie mogę utworzyć paczki, ponieważ "Email odbiorcy nie jest powiązany z żadnym zamówieniem". Czy muszę mieć sprzedaż na koncie testowym, a jeśli tak to jak to testowo zrobić?

**Comment by MartaNowaczyk** [comment]
Załóż dodatkowe konto zwykłe do symulacji zamówień.

**Comment by SlawekMat** [comment]
To niestety będę miał jeszcze mnóstwo pytań.
Przy "kupowaniu" chcę wybrać dostawę Allegro One Box, jak mogę wybrać miejsce odbioru? Na mapie Polski nie widać żadnego.

**Comment by MartaNowaczyk** [comment]
Proszę wybrać jeden z dostępnych np. w Warszawie.
