### ISSUE TITLE
Autoryzacja - nieaktywny przycisk logowania 

### ISSUE THREAD

**Issue by PiotrTaraszkiewicz** [allegro/allegro-api#5583]
Witam 

W ostatnich dniach zauważyliśmy że przycisk do zalogowania podczas autoryzacji nie jest aktywny.
Pierwsze zgłoszenie dotyczące tego tematu pojawiło się u nas ok 2 dni temu.

Do autoryzacji używamy ścieżki z wpisaniem danych logowania przez użytkownika w "przeglądarce" wbudowanej w nasz program.
Do tego używamy kontrolki WebView   osadzonej w aplikacji WPF.

Do przeglądarki przekazujemy URL startowy 
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=....cut....redirect_uri=https%3a%2f%2fprostapaczka.pl%2f
Użytkownik zostaje przekierowany do okna logowania, w którym przycisk "Zaloguj" nie jest dostępny. Uzupełnianie loginu i hasła nie aktywuje przycisku.

Jeżeli ten sam link skopiuję do przeglądarki (np. Edge) to można się zalogować i system Allegro przekierowuje na właściwą stronę z uzupełnionym parametrem "code" w URL.

Nie zmienialiśmy nic w tym mechanizmie  od dłuższego czasu, a problem pojawił się "na dniach". Może zmieniło się coś po Państwa stronie co mogło spowodować taki efekt?
![autoryzacja alegro](https://user-images.githubusercontent.com/51258677/160776535-9e67e377-e878-42e3-89ea-36968c8b6bec.jpg)

**Comment by MaciejFrackowiak** [comment]
W opisanym przypadku niezbędna jest aktualizacja przeglądarki, która wyświetla okna logowania. Jak widzę, podobne zgłoszenia w kontekście logowania do serwisu via WWW trafiły w ostatnich dniach, w każdym z tych przypadków użytkownicy korzystali z nieaktualnej wersji przeglądarki.

**Comment by PiotrTaraszkiewicz** [comment]
Dziękuję za szybką odpowiedź. Sprawdzimy czy zmiana kontrolki pomoże.
