### ISSUE TITLE
Wywołanie z REST API allegrosandbox

### ISSUE THREAD

**Issue by grzegorzn1** [allegro/allegro-api#5586]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Podczas wywoływania api  (wszystkie uprawnienia przy zakladaniu aplikacji) otrzymuje blad (403 Forbidden: Użytkownik jest uwierzytelniony, ale nie ma praw do danego zasobu.)
wywołanie:
curl.exe -X GET https://api.allegro.pl.allegrosandbox.pl/sale/offers -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiZXhwIjoxNjQ4NzUzODc1LCJqdGkiOiJkNjY2Y2Y1Zi02NjAzLTRjY2MtYTQ2ZS1lOTI0NmM2ODIxMjIiLCJjbGllbnRfaWQiOiJlMDFkYWU2OTJhN2E0MzVhOTQxNTFlMjRjYzBjZTBjOSJ9.s1xfqKtfGny8NWiG3U35Yonmtg_FzcfHOMiR3WMVoc3WXfhpTAdPyO_es-NjoHbXhQ-doNYvQ13hj_VpspZZqRfxt4_vwa7QJoLFE60PVqzZwuP-NvEhAQqVd45sNiFkaSyabKcqGpCwns60FNyQi8s8-1NgQriji-mY_AtmmSUCSPvsQ3q4gyVsMb0zOhzHN26giBXnRhh62FjMC5Q3x18ZY7cBBPG2gbHvs4siy-wowdfJye6q0gREJup8aY_IDg7sKJcy0LlEzD1u_Fx9PusnGd3n3dQ1QrD0wMpjoxd3rEVg1Szt6287FbaXyezQpBCQrn4pkDdBbNRit9N3rbzIOtTDNPXixK4JqBFQcfnIuP-Z48e2WlJniw4b5FIV6XVrLH71nEK9Uhvpxo5DV_CeuBsPOJJfwxSNGdm7AEVmz2EP4XzbUEvIOwB9MQAG0q0oOau7x6ZJ33mm-8tofCLTskKTmhl9TJeZKJw9UdB05uYtgVD3tisoqF5ThZTMeAoZHIPmSyr8IQjlupsvQZJ2aBCP3VbZl1AkQayTq6opy6MtRclQZSmVQdqOYpIbQ0k_A3kgv9w8mJtJdhUcSV2lIu1mL6uNlAbaKsv7BICUc62WTlnPCIRw3YJ4fBNQhOP2ThiCJY_Cf3Vpfw3xPUNdo5r07fwzDIcRMls6_eY" -H "Accept: application/vnd.allegro.public.v1+json"

PS.
Dla wywołania takiego samego ale z endpoint /sale/categories otrzymuje wyniki

**Comment by Lukasz-Zurek** [comment]
Korzystasz z autoryzacji typu[ client_credentials](https://developer.allegro.pl/auth/#clientCredentialsFlow), która nie posiada kontekstu użytkownika, dlatego nie uzyskasz dostępu np. do listy ofert. W takiej sytuacji masz dostęp tylko do danych ogólnodostępnych, np. informacji dotyczących kategorii i parametrów. 

W[ naszej dokumentacji](https://developer.allegro.pl/documentation/) znajdziesz odpowiednie oznaczenie, jaki typ autoryzacji wymagany jest dla danego zasobu:

- bearer-token-for-user ([code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub[ device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow-autoryzacja-uzytkownika) flow),
- bearer-token-for-application ([client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow)).

**Comment by Lukasz-Zurek** [comment]
@grzegorzn1 Ingerencja końcowego użytkownika jest potrzebna i bez niej niestety nie uzyskasz dostępu do listy ofert.

**Comment by MartyQek** [comment]
@Lukasz-Zurek Witam, rozwiązuję podobny problem, mam ustawione wszystkie uprawnienia - efekt końcowy powinien działać tak, aby importować produkty z feedu XML do Allegro, czy modyfikować menu, bez konieczności ingerencji użytkownika.
Token Bearer jest generowany poprawnie, ale żądanie GET i POST z tokenem Bearer nie działa, patrz. mój [problem](https://github.com/allegro/allegro-api/issues/5589) wtedy otrzymuję błąd 403 Forbidden

**Comment by Lukasz-Zurek** [comment]
@MartyQek Udzieliliśmy Tobie odpowiedzi w wątku #5589

**Comment by grzegorzn1** [comment]
Dzień Dobry,
Czy w tym endpoint'cie /sale/offers/{offerId} znajdę nazwę produktu/ów dotyczącą danej oferty?
Jesli nie to proszę o podanie jak pobrać nazwę.
Dziękuję

**Comment by Lukasz-Zurek** [comment]
@grzegorzn1 Za pomocą [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) uzyskasz wartość identyfikatora produktu (przypisanego do oferty) w polu **"product.id"**. Nazwę produktu uzyskasz korzystając z [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct), wprowadzając wspomniany **"product.id"**.
