### ISSUE TITLE
Błąd REST Api na środowisku testowym i środowisku produkcyjnym

### ISSUE THREAD

**Issue by lulzsoad** [allegro/allegro-api#5587]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
curl -X POST \
'https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=device_code \
  -H 'Authorization: Basic 'Wygenerowany client secret i client id'

Response:
{"error":"unsupported_grant_type","error_description":"Unsupported grant type"}

Nie działa pobieranie tokenu na środowisku testowym dla aplikacji typu "Device".  Czy są prowadzone jakiś prace? Dodatkowo na środowisku produkcyjnym dla endpointu "/order/checkout-forms/" + orderId + "/shipments" dostajemy błąd Order not found - ten problem występuje od dzisiaj.

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Jeżeli query parametr `grant_type` na 100% przekazujesz w odpowiedniej formie - jak wskazałeś powyżej, czyli:

`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code`

i po drodze kodowanie nie ulega zmianie, podeślij proszę pełen request i response do weryfikacji. Skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) i dopisz, że sprawa dotyczy wątku #5587 na GitHubie. Oczywiście wrócę z informacją w wątku.

Dodatkowo dla przypadku związanego z GET /order/checkout-forms/ - prześlij trace-id. Sam komunikat oznacza, że autoryzujesz się na koncie, na którym wspomnianego zamówienia nie ma. Zweryfikuję to jednak dokładnie na podstawie wspomnianego trace-id.

**Comment by lulzsoad** [comment]
Dzień dobry,
W poprzednich dniach wszystkie zapytania z API działały poprawnie,
pozwoliłem sobie sprawdzić programem zewnętrznym, jakie dane rzeczywiście
przekazujemy i okazuje się, że różni się zapis znaków specjalnych.
Rozumiem, że środowisko testowe zmieniło sposób akceptacji takich danych,
ponieważ tak jak wspomniałem wcześniej wszystko działało bez zarzutu,
ponadto na środowisku produkcyjnym, gdzie zmieniony jest tylko adres url,
zapytanie działa poprawnie.

W podobny sposób przestało działać zapytanie  "/order/checkout-forms/" +
orderId + "/shipments", ponieważ na końcu orderId zostaje doklejony znak
nowej linii %0A, gdzie wcześniej takie zapytanie było akceptowane.

Pozdrawiam
Łukasz Łopata

**Comment by Lukasz-Zurek** [comment]
Mogły nastąpić tutaj zmiany, które nie zezwalają obecnie na zaakceptowanie takiego żądania. Niemniej jednak pozostaje to w zgodzie z naszą [dokumentacją](https://developer.allegro.pl/documentation/#) i obawiam się, że nie będę mógł pomóc.
