### ISSUE TITLE
Błędna informacja w parametrze Rozmiar w kategorii 19913

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#5588]
Dzień dobry,
W kategorii 19913 dając w request 
`{'id': 127048, 'valuesIds': ['127048_381813'], 'values': ['33']}`
Dostaję 
`{"errors":[{"code":"BAD_REQUEST","message":"Custom values are not enabled in the parameter: parameterId=127048","details":null,"path":"","userMessage":"Parameter 'Rozmiar' does not allow to define custom dictionary values"}]}`

Przy czym z API dla tej kategorii mam informację o możliwości użycia ambiguousValueId:
`
  {'id': '127048',
   'name': 'Rozmiar',
   'type': 'dictionary',
   'required': True,
   'requiredForProduct': True,
   'unit': None,
   'options': {'variantsAllowed': True,
    'variantsEqual': False,
    'ambiguousValueId': '127048_381813',
    'dependsOnParameterId': None,
    'requiredDependsOnValueIds': None,
    'displayDependsOnValueIds': None,
    'describesProduct': True,
    'customValuesEnabled': False},

`

**Comment by Lukasz-Zurek** [comment]
Z uwagi na to, że wartości `"33"` nie ma na liście słownikowej, a `customValuesEnabled: False` (czyli nie możesz jej przekazać w requeście, bo nie możesz definiować wartości customowej) - zgłosiłem tę sprawę do odpowiedniego zespołu w celu dodania wskazanej wartości do słownika.

Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@anih Nie możemy dodać wartości `"33"` do naszego słownika, ponieważ wystawiany towar jest dla dzieci, czyli adekwatną kategorią przedmiotu, który próbujesz wystawić - jest _25956_.
