### ISSUE TITLE
Getting 403 error when trying to get data from API

### ISSUE THREAD

**Issue by MartyQek** [allegro/allegro-api#5589]
Hi, I trying to make custom implementation which will work with product data (creating and getting offers data), I used everything by your documentation but I getting error 403 Forgotten after I trying to do request with authorization through Bearer token

My code is here: 
```
`define('CLIENT_ID', 'client_id'); 
define('CLIENT_SECRET', 'client_secret'); 


function getCurl($headers, $url, $content = null) {
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_RETURNTRANSFER => true
    ));
    if ($content !== null) {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $content);
    }
    return $ch;
}

function createListings() {
    $authorization = base64_encode(CLIENT_ID.':'.CLIENT_SECRET);
    $headers = array("Authorization: Basic {$authorization}","Content-Type: application/x-www-form-urlencoded");
    $content = "grant_type=client_credentials";
    $url = "https://allegro.pl/auth/oauth/token";
    $ch = getCurl($headers, $url, $content);
    $tokenResult = curl_exec($ch);
    $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    //var_dump($tokenResult);
    curl_close($ch);
    if ($tokenResult === false || $resultCode !== 200) {
        exit ("Something went wrong");
    }
    $token = json_decode($tokenResult)->access_token;
    $request_url = "https://allegro.pl/sale/offers";
    $request = [
        "category.id" => 260660
    ];
    
    $result = file_get_contents($request_url, false, stream_context_create([
        "http" => [
            'method' => 'GET',
            'header' => implode("\r\n", [
                "Authorization: Bearer " . $token,
                "Accept: application/vnd.allegro.public.v1+json",
                "Content-Type: application/vnd.allegro.public.v1+json",
            ]),
            "content" => json_encode($request)
        ]
    ]));
    
    if(!$result) {
        echo "Jejda! Chybka se vloudila..<br>";
    }
    $response = json_decode($result);
    var_dump($response);
}


createListings();`
```

**Comment by MaciejFrackowiak** [comment]
As I see you chose "client_credentials" authorization - this one gives access to "bearer-token-for-application" resources only. If you want to use e.g.  [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - which required "bearer-token-for-user", you should use [code flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device flow](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) authorization. Also, when you call API resources, you should use "https://api.allegro.pl/..." address, not "https://allegro.pl/...".

**Comment by MartyQek** [comment]
@MaciejFrackowiak Hi, [here](https://imgur.com/a/wAmQWI4) I'm attaching you screenshot settings of the API, I also tried api.allegro.pl url to request, but it still giving me 403 forbidden.. How I will set up it to make it work?

**Comment by MaciejFrackowiak** [comment]
Settings are OK, but as I wrote in the previous message - you have to change the authorization method from client_credentials to code or device flow.

**Comment by MaciejFrackowiak** [comment]
Please, send us details of your request and response with trace-id via [our contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e). Please add GitHub #5589 in your application.
