### ISSUE TITLE
[REST] Zmiana, wyrejestrowanie aplikacji w Developer Apps

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#559]
Czy możliwa jest zmiana adresu URL zwrotnego lub wyrejestrowanie aplikacji w Developer Apps?

**Comment by MaciejPotepa** [comment]
Dzień dobry
@SlawomirMizerski obydwie operacje są możliwe. 

Możemy usunąć aplikację i zmienić redirect uri, z tym, że zmiana adresu można potrwać trochę dłużej.
