### ISSUE TITLE
Błąd z pobraniem tokena, brak autentykacji

### ISSUE THREAD

**Issue by Sdrapinski** [allegro/allegro-api#5590]
Hej, zarejestrowałem aplikację pod tym linkiem: https://apps.developer.allegro.pl/ 
dostałem client ID oraz Client Secret
i wpisałem je do kodu PHP oraz Python który udostępniacie tutaj: https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#python
Po skompilowaniu w php jak i python wyskakuje błąd Unauthorized
co mogę robić nie tak ?

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę przykładowy request i response przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5590.

**Comment by maniutek08** [comment]
Przydałaby się jakaś odpowiedź - mam dokładnie ten sam problem

**Comment by Lukasz-Zurek** [comment]
@maniutek08 Prześlij proszę request przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5590. Posiadając szczegółowe dane, będę w stanie dokładnie zweryfikować zgłoszenie.

**Comment by Lukasz-Zurek** [comment]
@maniutek08 Sprawdziłem Twoje zgłoszenie. Kod PHP w naszym poradniku nie zawiera błędów, dlatego jeśli nadal masz problemy z autoryzacją - prześlij proszę (w toku korespondencji e-mail) cały Twój kod.
