### ISSUE TITLE
Błąd przetwarzania. Allegro One Box.

### ISSUE THREAD

**Issue by mGuzdziol** [allegro/allegro-api#5591]
Dzień dobry,

Przy próbie wykonania tego POSTa: `https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/dff55410-b40f-11ec-b909-0242ac120002` a następnie odpytaniu tego GETa: `https://api.allegro.pl.allegrosandbox.pl/parcel-management/parcel-create-commands/dff55410-b40f-11ec-b909-0242ac120002` dostaję następujący błąd:

`{
    "id": "dff55410-b40f-11ec-b909-0242ac120002",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": null,
            "userMessage": "Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"
        }
    ]
}`

Json, który wysyłam:

`{
  "serviceId": 9504023,
  "receiver": {
    "address": {
      "street": "Mołdawska 7A",
      "postCode": "02-132",
      "city": "Warszawa",
      "countryCode": "PL"
    },
    "email": "kaiurgrzp7+8f4e0269@user.allegrogroup.pl",
    "name": "Jan Kowalski",
    "company": "Allegro.pl sp. z o.o.",
    "phone": "500600700",
    "pointId": "A004919"
  },
  "pickup": {
    "address": {
      "street": "Skarbka z Gór 110",
      "postCode": "03-287",
      "city": "Warszawa",
      "countryCode": "PL"
    },
    "email": "email@mail.com",
    "name": "Jan Kowalski",
    "company": "Allegro.pl sp. z o.o.",
    "phone": "500600700"
  },
  "items": [
    {
      "dimensions": {
        "height": {
          "value": 12,
          "unit": "CENTIMETER"
        },
        "width": {
          "value": 12,
          "unit": "CENTIMETER"
        },
        "depth": {
          "value": 12,
          "unit": "CENTIMETER"
        }
      },
      "weight": {
        "value": "2.45",
        "unit": "KILOGRAM"
      },
      "description": "Car wheels.",
      "value": {
        "amount": "25.50",
        "currency": "PLN"
      },
      "type": "PACKAGE"
    }
  ],
  "type": "PACKAGE",
  "label": {
      "email": "email@mail.com",
      "name": "Jan Kowalski",
      "company": "Allegro.pl sp. z o.o.",
      "phone": "500600700"
    },
    "fileFormat": "PDF",
    "referenceNumber": "abcd1234"
}`

Czy mógłbym prosić o pomoc w zlokalizowaniu błędu, który popełniam?

**Comment by mGuzdziol** [comment]
@Onixarts Dane są zmyślone :)

**Comment by MaciejFrackowiak** [comment]
@mGuzdziol Twoje zgłoszenie weryfikuję wraz z zespołem, wrócę z odpowiedzią.

@Onixarts Rzeczywiście, występują dziś problemy z produkcyjną wersją serwisu, działamy wraz z dostawcą usługi, aby przywrócić właściwe jej działanie.

**Comment by Onixarts** [comment]
> działamy wraz z dostawcą usługi

Ale problem dotyczy wszystkich kurierów, a na pewno minimum 3.

**Comment by MaciejFrackowiak** [comment]
@mGuzdziol Szczegółowa odpowiedź dla Twojego requestu to: "Podany punkt jest obecnie nieobsługiwany." Na Sandbox lista dostępnych punktów jest zdecydowanie mniejsza niż w wersji produkcyjnej serwisu, a wybrany przez Ciebie nie jest obsługiwany na Sandbox.

**Comment by mGuzdziol** [comment]
@MaciejFrackowiak, przeszło, dzięki 👍
