### ISSUE TITLE
Litera „ó” jest źle wyświetlana na etykietach Allegro One

### ISSUE THREAD

**Issue by it-cewe-pl** [allegro/allegro-api#5592]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Litera „ó” jest źle parsowana, zamiast „o”, są krzaczki na etykiecie.
W załączeniu zwrócony plik zpl, oraz wygenerowany na jego podstawie plik png.
https://docs.cewe.de/s/fyKP8PRWjXfqafb

984aa8731ad42704 w środowisku testowym, na produkcji występuje ten sam problem.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie, pracujemy już nad rozwiązaniem problemu z brakiem polskich znaków na etykietach.
