### ISSUE TITLE
Nadmiarowa kampania 0.5%: COMMISSION_DISCOUNT_202200405

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#5593]
W API zwracacie aktualnie dwie aktywne kampanie 0.5%:
- COMMISSION_DISCOUNT_20220405 (właściwa)
- COMMISSION_DISCOUNT_202200405 (prawdopodobnie nadmiarowa)

Proszę o usunięcie/zezaktywowanie nadmiarowej.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie, sprawdzę opisaną sytuację.

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i nie zwraca mi "COMMISSION_DISCOUNT_202200405". Możliwe, że już usunięto nadmiarową kampanię.
