### ISSUE TITLE
Multiple threaded POST create product offers calls sandbox issue

### ISSUE THREAD

**Issue by fatemagnassar** [allegro/allegro-api#5594]
I’m having an issue when trying to make multiple https://developer.allegro.pl/documentation#operation/createProductOffers calls at the same instant (threaded), the calls take too much time to return a response in that case on sandbox environment, my question is , is this an issue for sandbox or is this expected on live environment as well and you don’t allow one seller to make multiple concurrent calls at once to this call ?

**Comment by MaciejFrackowiak** [comment]
Could you give us an example (trace-id) of that kind of request? We will investigate it.
