### ISSUE TITLE
Allegro One

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#5597]
Podczas próby zamówienia kuriera po odbiór przesyłek ciągle otrzymuję błąd że odbiór w tych godzinach jest niedostępny (próbowałem różne godziny i dni). Jednocześnie dziwne jest to że etykieta wygenerowana przez API nie pokazuje się po zalogowaniu na konto w Allegro.

Przesyłam numer paczki: ALE00001598381A

oraz ERROR przy próbie zamówienia kuriera:

stdClass Object ( [id] => 624d6b26-624d-624d-624d-624d6b264b85 [status] => ERROR [errors] => Array ( [0] => stdClass Object ( [code] => ERROR [message] => Parcel pickup between 10:00 and 16:00 is not available. [details] => [path] => parcelIds[0] [userMessage] => Odbiór w godzinach 10:00 - 16:00 jest niedostępny. ) ) )

**Comment by MaciejFrackowiak** [comment]
Czy sprawdzałeś wcześniej proponowane godziny odbioru korzystając z [GET /parcel-management/pickup-date-proposals](https://developer.allegro.pl/documentation/#operation/getParcelsPickupDateProposals)?

**Comment by krzysda** [comment]
Tez jest błąd: stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => NotFoundException [message] => Not found [details] => [path] => [userMessage] => Function is not available. Contact the author of the application. ) ) )

**Comment by MaciejFrackowiak** [comment]
Przejrzałem posiadane przez nas logi i widzę pewną niespójność:
- commandId, który podajesz tj. "624d6b26-624d-624d-624d-624d6b264b85" powiązany jest z parcelId=73861715, a jak widzę ta paczka została już doręczona 1 kwietnia 2022;
- paczka ALE00001598381A powiązana jest z parcelId=74878352 i ona wczoraj została nadana.

Jeżeli nadal obserwujesz jakiś problem, proszę przekaż nam szczegóły.
