### ISSUE TITLE
Client_credentials flow błąd w dokumentacji?

### ISSUE THREAD

**Issue by krzysztofgal** [allegro/allegro-api#5598]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
https://allegro.pl/auth/oauth/token?grant_type=client_credentials w odpowiedzi dostaję JSON z polami [access_token, token_type, expires_in, scope, allegro_api, jti]. **Brak pola refresh_token** jak jest to podane [w dokumentacji](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow).

**Comment by MaciejFrackowiak** [comment]
Dziękuję za zgłoszenie i zwrócenie uwagi - poprawiliśmy już zapis w poradniku.
