### ISSUE TITLE
Nazwa odbiorcy/firmy odbiorcy jest zbyt długa

### ISSUE THREAD

**Issue by shivson1337** [allegro/allegro-api#5599]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy próbie utworzenia paczki Allegro One, otrzymujemy zwrotkę o zbyt długiej nazwie odbiorcy i nazwie firmy odbiorcy.
Nazwa ta ma zaledwie 32 znaki. Proszę o weryfikację i ewentualne wskazanie realnego problemu.

trace-id: b13727692cafbeed

**Comment by MaciejFrackowiak** [comment]
Dla obu wymienionych pól maksymalna ilość znaków to 30.

**Comment by shivson1337** [comment]
Gdzie w takim razie mogę sprawdzić dozwoloną ilość znaków dla pozostałych pól?
Chcielibyśmy uniknąć podobnych sytuacji w przyszłości.

**Comment by MaciejFrackowiak** [comment]
Każdy przewoźnik niestety określa swoje własne wymagania, w przypadku Allegro One/UPS to:

* sender:
    * name - 30
    * company - 30
    * email - długość nieokreślona
    * city - 30
    * street - 31
* receiver:
    * name - 30
    * company - 30
    * email - długość nieokreślona
    * city - 30
    * street - 35
* description - 50

**Comment by shivson1337** [comment]
Jasne. Dziękuję za informacje.
