### ISSUE TITLE
Opis aukcji, zdjęcia produktu 

### ISSUE THREAD

**Issue by sqlldev** [allegro/allegro-api#56]
Dzień dobry,
zgodnie z nowymi zasadami należy teraz wystawiać opis aukcji w polu FID 341. Przez co wszystkie dotychczasowe "szablony" z których ludzie korzystali są teraz bezużyteczne. Mam jednak pytanie czy Jeśli wystawiam aukcje poprzez api i chciałbym w opisie umieścić np. ładny nagłówek i dodam go jako zdjęcie produktu do aukcji (np. w FID 17) to czy później jak będę chciał wstawić go do opisu za pomocą:
        {
          "type": "IMAGE",
          "url": "PHOTO_FID_16"
        }

To czy będę w ten sposób jakoś naruszał zasady wystawiania? 
Przykładowa aukcja jaką znalazłem na allegro, która jest wystawiona w ten sposób:
http://allegro.pl/poduszka-amortyzatora-vw-golf-passat-vento-i7222641383.html#thumb/2

Czy głównym założeniem tej zmiany było ujednolicenie opisów i pozbycie się ładnych opisów?

**Comment by imper86** [comment]
Podobno tego typu aukcje są niezgodne z regulaminem allegro, ale z drugiej strony allegro przymyka na to oko. Takich aukcji jak podałeś są strasznie duże ilości i nikt z tym nic nie robi. Być może coś się w tej materii zacznie zmieniać gdy wymagane już będzie 100% aukcji na nowym opisie.

**Comment by DINK74** [comment]
Są niezgodne - co do tego nie ma wątpliwości. Allegro nie przymyka oka tylko tego nie weryfikuje. Natomiast z pewnością weryfikuje to konkurencja i wtedy na zgłoszone konkretne aukcje Allegro już reaguje - pouczeniem lub usunięciem - w zależności od humoru operatora.

**Comment by DINK74** [comment]
PS. podana aukcja ma do tego niezgodną z zasadami miniaturkę - nie wolno stosować watermarków.

A co do powodów wprowadzenia opisu "plain-text" to można tylko gdybać. Część aukcji miała faktycznie ładne szablony, ale dużo więcej zawierało mnóstwo reklam, linków poza serwis, bzdurnych opisów, kompozycji kolorystycznych wywołujących wymioty, itp. Przy okazji słabo wyglądały na urządzeniach mobilnych. Teraz jest czysto i elegancko, ale widzę, że niektórym brakuje dawnego festyniarstwa i zaczynają kombinować :-)

**Comment by sqlldev** [comment]
Ok, dzięki za komentarz. Osobiście też uważam, że jednolity opis dla wszystkich aukcji jest dobrym rozwiązaniem, bo tak jak mówisz niektóre z tych szablonów wyglądały sztampowo i kiczowato + były jedną wielką reklamą. Jednak czekam jeszcze na jakieś potwierdzenie od kogoś z teamu allegro bo mam do wystawienia przez mój program ponad 5 tys aukcji i chciałbym uniknąć jakichś późniejszych problemów. 
No a ludzie kombinują bo są przyzwyczajeni do swoich szablonów i jeszcze tego nie rozumieją, że era szablonów się skończyła.

**Comment by DINK74** [comment]
Na 100% w opisie produktu ma być wyłącznie opis produktu. Kwestia interpretacji czy ma to być wymagane już (tj. od 22. lutego br.) czy dopiero od czerwca. W zależności na jakiego pracownika Allegro trafisz - odpowiedzi bywają różne. Co do zdjęć to poczytaj [tutaj](https://allegro.pl/dla-sprzedajacych/zasady-dla-pierwszego-zdjecia-miniaturki-w-ofercie-vKgeLv4YXi4) - w skrócie - mają być zdjęcia produktu, ew. logotypy marek, technologii, certyfikaty, schematy ale nie logotypy sprzedawcy czy elementy graficzne szablonu. Timeline mówi też, że w zasadzie wszystkie nowe oferty od kwietnia 2017 mają mieć takie zdjęcia, a od czerwca 2018 obowiązek dotyczy wszystkich ofert - także tych wystawionych przed kwietniem 2017.
Background tych zmian jest jasny - Allegro nie chce reklamować podmiotów tylko przedmioty, a także - w miarę możliwości - ściągać je do OSA.
Jeśli potrzebujesz więcej informacji dot. opisów, interpretacji, itp. to zapisz się do jakiejś grupy sprzedawców na FB.

**Comment by sqlldev** [comment]
Informacje o zdjęciach już czytałem dość dokładnie również timeline, chciałem tylko upewnić się czy moja interpretacja tego jest prawidłowa. Także wielkie dzięki ;)

**Comment by AniaMalinowska** [comment]
Jak słusznie pokierował DINK74 - wszystkie zasady co do zdjęć w ofertach zamieściliśmy [tutaj](https://allegro.pl/dla-sprzedajacych/kategoria/nowe-zasady-dla-zdjec). 

Wprawdzie [aktualnie wymagamy 1% aktywnych ofert z nowym opisem](https://allegro.pl/dla-sprzedajacych/od-dzis-wymagamy-1-aktywnych-ofert-z-nowym-opisem-4GLW4Vx7GCn) na kontach firma, niemniej warto dbać na bieżąco, aby już każda oferta była wystawiana zgodnie ze [standardami nowego opisu](https://allegro.pl/dla-sprzedajacych/kategoria/nowe-zasady-dla-ofert).

Dodam, że wskazaną ofertę przekazałam do weryfikacji do odpowiedniego Działu. 
Jeśli zauważycie, że jakaś oferta jest niezgodna z naszymi zasadami/Regulaminem, to możecie to nam [zgłaszać](https://pomoc.allegro.pl/kontakt/#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=aba9a845-b8b9-474c-8b45-6ec03e655aee).

**Comment by imper86** [comment]
W ramach testów zgłosiłem tą aukcję: http://allegro.pl/buty-meskie-adidas-v-racer-2-0-bc0107-rozne-rozm-i6944317146.html#thumb/2

Ciekawe co z nią zrobicie, aukcja jest w strefie okazji i oczywiście klient VIP, najmocniejszy w branży. Domyślam się, że nic. Wszystkie aukcje z tego konta wyglądają podobnie.

**Comment by DINK74** [comment]
@sqlldev - aukcja, którą wspomniałeś już wyleciała - ktoś Ci podziękuje :-)

**Comment by imper86** [comment]
Aukcję, którą wrzuciłem wyżej ktoś poprawił i niby jest ok. Tylko pytanie teraz powstało czy to zasługa tego, że wrzuciłem link tutaj, na github, czy kwestia wysłanego zgłoszenia :). Chyba to pierwsze, bo zgłosiłem też przy okazji dwie inne aukcje i tych już oczywiście nikt nie ruszył :)

http://allegro.pl/buty-meskie-adidas-v-racer-2-0-db0430-rozne-roz-i7234395627.html
http://allegro.pl/buty-damskie-adidas-lite-racer-bc0074-nowosc-i7082890884.html

Słabe jest takie postępowanie. Rozumiem, że dopóki nie opublikuję pełnej listy aukcji łamiących regulamin tego sprzedawcy to każde zgłoszenie będzie zamiatane pod dywan?

**Comment by martacronic** [comment]
Jeśli zamiast formularza "Zgłoś naruszenie regulaminu" użyjesz formularza kontaktu a Allegor i podasz nick sprzedającego i opis nieprawidłowości na danym koncie, to zostanie wszystko poprawione. Ja miałam sytuację manipulację słowami kluczowymi "marka, nie marka" i pomogło. W ciągu 3-4 dni sprzedający poprawił 700 aukcji. 

Mi to strasznie utrudniało, bo przez webapi wyszukiwałam produktów konkretnego producenta i ciągle miałam złe wyniki, bo ktoś dodał w tytule nazwę producenta, którego produkty nie były sprzedawane w tych aukcjach. Teraz mam porządek.

**Comment by imper86** [comment]
A co za różnica czy zgłoszę tak czy inaczej? Po wejściu w aukcje, które podlinkowałem gołym okiem widać o co chodzi, nie trzeba nawet zjeżdżać do opisu, bo widać po wstawionych zdjęciach.

Ja nadal podtrzymuję zdanie, że allegro po prostu przymyka oko na takie rzeczy, czym sami sobie szkodzą. Uważam, że gdyby nie chodziło o klienta VIP to by nie było sprawy i z tym sprzedającym allegro by postąpiło inaczej.

**Comment by martacronic** [comment]
@imper86  Jeśli chodzi o działanie "Zgłoś naruszenie regulaminu" to z mojego doświadczenia jak najbardziej działa, ale sprzedający dostaje od Allegro chyba jakiś czas na poprawę, bo to się nie zmienia w ciągu 24h od zgłoszenia, aczkolwiek to tylko moje doświadczenia. Ja piszę bardziej o tym, że nie sposób czasami przeklikać 1000, które są tak samo niezgodnie regulaminem przez "Zgłoś naruszenie regulaminu" i w moim przypadku w ciągu 2 tygodni poskutkowało.

Nie do końca też rozumiem co dla Ciebie się kryje pod pojęciem klient VIP, bo ikonka "Super Sprzedawca" jest dostępna po spełnieniu kilku wymogów i z mojej perspektywy nie ułatwia niczego jeśli chodzi support Allegro. Sprzedawca, którego zgłaszałam tez był  "Super Sprzedawcą", a musiał wyedytować i zmienić wszystkie nieprawidłowe aukcje. Co innego sklepy "Strefy Marek".  Tam to rzeczywiście w porównaniu z resztą sprzedawców mają możliwości, tylko dla nich jest osobny regulamin.

**Comment by imper86** [comment]
@martacronic ok, rozumiem o co Ci chodzi.

Co do VIPów - lektura dla Ciebie - https://allegro.pl/pomoc/faq/kim-sa-klienci-vip-i-top-na-allegro-dygqd0mokcr

Super Sprzedawca to zupełnie inna sprawa, nie trzeba być ss żeby być vipem.

**Comment by martacronic** [comment]
Na profilu tego nie widać. Człowiek uczy się całe życie :)

Ja zatem tym bardziej bym zgłaszała, bo jednak VIP, TOP, czy ktokolwiek inny tak samo prowizję płacimy i trzeba wymagać przestrzegania tych samych zasad. Powodzenie i cierpliwości życzę.
