### ISSUE TITLE
[REST] OfferRepository error

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#560]
`{"id":"7544504206","name":"EYE SPOT white 3 6016 Nowodvorski","category":{"id":"5318"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"16101","valuesIds":["16101_9"],"values":[],"rangeValue":null},{"id":"11484","valuesIds":["11484_2"],"values":[],"rangeValue":null},{"id":"129261","valuesIds":["129261_32","129261_2","129261_128","129261_4","129261_1","129261_8"],"values":[],"rangeValue":null},{"id":"24231","valuesIds":[],"values":["8"],"rangeValue":null},{"id":"201585","valuesIds":[],"values":["33"],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["4"],"rangeValue":null},{"id":"129259","valuesIds":["129259_3"],"values":[],"rangeValue":null},{"id":"201573","valuesIds":["201573_208693"],"values":[],"rangeValue":null},{"id":"24232","valuesIds":["24232_16"],"values":[],"rangeValue":null},{"id":"201593","valuesIds":["201593_1"],"values":[],"rangeValue":null},{"id":"201601","valuesIds":["201601_208729"],"values":[],"rangeValue":null},{"id":"213382","valuesIds":[],"values":["35"],"rangeValue":null}],"ean":"5903139601696","description":{"sections":[{"items":[{"type":"IMAGE","url":"https://5.allegroimg.com/original/11b6ab/fa31d8444102960c711f4de26a15"}]},{"items":[{"type":"IMAGE","url":"https://4.allegroimg.com/original/1149a2/36eaecaa40f0ad625e3ba9dec3b4"},{"type":"TEXT","content":"<h1>EYE SPOT white 3 6016 Nowodvorski</h1><p>Nr katalogowy: 6016</p><p><b>Specyfikacja:</b></p><ul><li>Zasilanie: ~230V</li><li>Materiał: stal, chrom</li><li>Szerokość: 33 cm</li><li>Źródło światła: 3 x GU10 max 35W</li><li><b>Lampa sprzedawana jest bez żarówek</b></li></ul><p>Propozycja lamp sufitowych Eye Spot marki Nowodvorski Lighting to przykład konstrukcji wykonanej z estetycznego połączenia stali lakierowanej i chromu. Na kompozycję oświetleniową składają się reflektory (pojedyncze lub w kilkuelementowych zestawach) o zróżnicowanym ustawieniu kierunku światła, które przymocowane są do listwy głównej (kształt prostokąta lub kwadratu). Produkty dostępne w kolorach: białym, srebrnym, grafitowym i czarnym do wyboru.</p>"}]}]},"compatibilityList":null,"images":[{"url":"https://4.allegroimg.com/original/1149a2/36eaecaa40f0ad625e3ba9dec3b4"},{"url":"https://5.allegroimg.com/original/11b6ab/fa31d8444102960c711f4de26a15"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"149","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":20,"unit":"UNIT"},"publication":{"duration":null,"status":"INACTIVE","startingAt":null,"endingAt":null},"delivery":{"shippingRates":{"id":"2324e4fa-5002-45ea-93d4-917b5becde17"},"handlingTime":"PT72H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"1b42b62f-2ea9-4dd7-9982-8bf7fee197f5"},"returnPolicy":{"id":"c9dd1448-e2d3-4c44-b68c-b1ad518ca629"},"warranty":{"id":"4df970ce-c5eb-4833-b0a3-558134c6b22c"}},"additionalServices":null,"sizeTable":null,"promotion":null,"location":{"countryCode":"PL","province":"SLASKIE","city":"Częstochowa","postCode":"42-229"},"external":{"id":"7744"},"contact":null,"validation":{"errors":[],"validatedAt":"2018-09-03T15:35:19.091Z"},"createdAt":"2018-09-03T15:35:19Z","updatedAt":"2018-09-03T15:35:19.092Z"}` 

Już nie wiem o co chodzi....  

`{"tasks":[{"offer":{"id":"7544504206"},"message":"OfferRepository error","status":"FAIL","scheduledAt":"2018-09-03T17:35:28.011+02:00","finishedAt":"2018-09-03T17:35:44.582+02:00","field":"publication"}]}`

A przed chwilą 

`{"id":"7544680073","name":"POINT S 6006 Nowodvorski","category":{"id":"5318"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"16101","valuesIds":["16101_9"],"values":[],"rangeValue":null},{"id":"11484","valuesIds":["11484_2048"],"values":[],"rangeValue":null},{"id":"129261","valuesIds":["129261_32","129261_2","129261_128","129261_4","129261_1","129261_8"],"values":[],"rangeValue":null},{"id":"24231","valuesIds":[],"values":["8"],"rangeValue":null},{"id":"24210","valuesIds":[],"values":["13"],"rangeValue":null},{"id":"17448","valuesIds":[],"values":["1"],"rangeValue":null},{"id":"129259","valuesIds":["129259_1"],"values":[],"rangeValue":null},{"id":"201573","valuesIds":["201573_208693"],"values":[],"rangeValue":null},{"id":"24232","valuesIds":["24232_16"],"values":[],"rangeValue":null},{"id":"201593","valuesIds":["201593_1"],"values":[],"rangeValue":null},{"id":"201601","valuesIds":["201601_208729"],"values":[],"rangeValue":null},{"id":"213382","valuesIds":[],"values":["35"],"rangeValue":null}],"ean":"5903139600699","description":{"sections":[{"items":[{"type":"IMAGE","url":"https://f.allegroimg.com/original/113f89/804f077a43c6bf6ca284f165cf6f"}]},{"items":[{"type":"IMAGE","url":"https://0.allegroimg.com/original/11dc71/34ced5d84e069e90c05cea703360"},{"type":"TEXT","content":"<h1>POINT graphite-silver/graphite-white S 6006 Nowodvorski</h1><p>Nr katalogowy: 6006</p><p><b>Specyfikacja:</b></p><ul><li>Zasilanie: ~230V</li><li>Materiał: stal</li><li>Wysokość: 8 cm</li><li>Średnica: 13 cm</li><li>Źródło światła: 1 x GU10 max 35W</li><li><b>Lampa sprzedawana jest bez żarówek</b></li></ul><p>Rodzina lamp Point firmy Nowodvorski Lighting to produkty przeznaczone do bezpośredniego montażu pod sufitami. Oprawy w kształcie walca dostępne są w trzech rozmiarach i trzech kolorach (biały, srebrny, grafitowy). Ciekawym rozwiązaniem stylistycznym kompozycji oświetleniowej są spody lamp (ze źródłem światła) utrzymane w odmiennym od reszty kolorze. Całość wykonana z najwyższej jakości stali lakierowanej.</p>"}]}]},"compatibilityList":null,"images":[{"url":"https://0.allegroimg.com/original/11dc71/34ced5d84e069e90c05cea703360"},{"url":"https://f.allegroimg.com/original/113f89/804f077a43c6bf6ca284f165cf6f"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"65","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":44,"unit":"UNIT"},"publication":{"duration":null,"status":"ACTIVATING","startingAt":"2018-09-03T17:25:09Z","endingAt":null},"delivery":{"shippingRates":{"id":"2324e4fa-5002-45ea-93d4-917b5becde17"},"handlingTime":"PT72H","additionalInfo":null,"shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"1d6e60ef-3a29-4527-ba4e-8ec357550260"},"returnPolicy":{"id":"c9dd1448-e2d3-4c44-b68c-b1ad518ca629"},"warranty":{"id":"4df970ce-c5eb-4833-b0a3-558134c6b22c"}},"additionalServices":null,"sizeTable":null,"promotion":null,"location":{"countryCode":"PL","province":"SLASKIE","city":"Częstochowa","postCode":"42-229"},"external":{"id":"7794"},"contact":null,"validation":{"errors":[],"validatedAt":"2018-09-03T17:24:01.348Z"},"createdAt":"2018-09-03T17:24:01Z","updatedAt":"2018-09-03T17:24:11.132Z"}`

A tutaj wszystko ok.... 

`{"tasks":[{"offer":{"id":"7544680073"},"message":"","status":"SUCCESS","scheduledAt":"2018-09-03T19:24:10.001+02:00","finishedAt":"2018-09-03T19:24:11.477+02:00","field":"publication"}]}`

Oczywiście nic nie zmieniam w kodzie, wszystko wystawiam za pomocą tej samej funkcji...

**Comment by Rnapzsih** [comment]
Wczoraj przy innej próbie publikacji otrzymałem również pusty tasks....

**Comment by MaciejPotepa** [comment]
Dzień dobry

@Rnapzsih Czy dla ID 7544504206 przy ponownej próbie przesłania requesta nadal występuje błąd OfferRepository?

**Comment by Rnapzsih** [comment]
@MaciejPotepa  Jak najbardziej i to nie tylko przy tym drafcie. Mam sporo takich.

**Comment by MaciejPotepa** [comment]
Rozumiem. Przepraszam za problemy. 

Dorzuć proszę do zgłoszenia **treść nagłówka**, który przesyłasz, **trace id** też pomoże i będziemy działać nad rozwiązaniem tego problemu. Będę wdzięczny za więcej danych, pomoże to szybciej rozwikłać.

**Comment by Rnapzsih** [comment]
Request 
`{"publication":{"action":"ACTIVATE","scheduledFor":"2018-09-04T12:24:08+02:00"},"offerCriteria":[{"offers":[{"id":"7543824248"}],"type":"CONTAINS_OFFERS"}]}`
Response  
`{"id":"34198af6-badb-4a31-be3f-98da80aead00","taskCount":{"total":0,"success":0,"failed":0}} `

ID 7544504206 - udało się za kolejnym razem. 

i skrypt 

`   $aDane['publication']['action'] = 'ACTIVATE';
    $aDane['offerCriteria'][0]['offers'][]['id'] = $sOfferId;
    $aDane['offerCriteria'][0]['type'] = 'CONTAINS_OFFERS';
    $aDane['publication']['scheduledFor'] = $datetime->format(DateTime::ATOM);
    $sDane = json_encode($aDane);
    $oCURL = curl_init(); 
    curl_setopt($oCURL, CURLOPT_CUSTOMREQUEST, "PUT");   
    curl_setopt($oCURL, CURLOPT_POSTFIELDS, $sDane);
    curl_setopt($oCURL, CURLOPT_URL, 'https://api.allegro.pl/sale/offer-publication-commands/'.$uuid);
    curl_setopt($oCURL, CURLOPT_RETURNTRANSFER, 1);
    
    $headers = array();
    $headers[] = "Authorization: Bearer ".$bearer['access_token'];
    $headers[] = "Accept: application/vnd.allegro.beta.v1+json";
    $headers[] = "Content-type: application/vnd.allegro.beta.v1+json";
    curl_setopt($oCURL, CURLOPT_HTTPHEADER, $headers);`

**Comment by Rnapzsih** [comment]
Dziwna sprawa 7543824248 też poszło za 3 razem

**Comment by MaciejPotepa** [comment]
Godzinę lub więcej temu naprawiliśmy podobny problem związany z wystawianiem ofert przez REST API. Zapewne były mocno powiązane. Jeżeli sytuacja się powtórzy, daj znać.

**Comment by Rnapzsih** [comment]
Potwierdzam wszystko działa. Dzięki wielkie.
