### ISSUE TITLE
Dyskusje / pytania - tłumaczenia

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5600]
Witam
Czy jest planowane w tym roku wprowadzenie do API obsługi dyskusji / pytań z informacją o języku pytania + tłumaczenia tego pytania (analogicznie jak to jest w serwisie www) ?

**Comment by MaciejFrackowiak** [comment]
Temat konsultuję z zespołem, wrócę z odpowiedzią.

**Comment by PawelPseudo** [comment]
Witam
Udalo sie skonsultowac ?

**Comment by MaciejFrackowiak** [comment]
Czekam na wiążącą odpowiedź, wrócę gdy tylko ją uzyskam.

**Comment by MaciejFrackowiak** [comment]
Wracam z odpowiedzią - tak, taka funkcjonalność jest w planach. Co do terminu - nie prędzej niż w drugiej połowie roku, jednak konkretnego terminu wdrożenia nie mamy dotychczas ustalonego.
