### ISSUE TITLE
Invalid request. Please contact the application author.

### ISSUE THREAD

**Issue by juansiwei-li** [allegro/allegro-api#5601]
response:

{"errors":[{"code":"JsonMappingException","message":"Message is not readable.","details":null,"path":"images[0]","userMessage":"Invalid request. Please contact the application author."}]}

**Comment by MartaNowaczyk** [comment]
The reason is the wrong structure for the images, it should be:

```
"images":
[
        "https://a.allegroimg.com/original/1102d8/f72c14f64f41a5df3907d5d0bce1",
        "https://a.allegroimg.com/original/1109d5/8cac07224e51ab0e38699d2b1f42"
],
```

See also the description. There are no starting tags. I am sending you a [guide](https://developer.allegro.pl/tutorials/listing-offers-4RAvLdaqMf8#offer-description) where you will find more information about it.
