### ISSUE TITLE
Błąd w dokumentacji GET user's shipping rates

### ISSUE THREAD

**Issue by krzysztofgal** [allegro/allegro-api#5605]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Response samples dla zasobu [Get the user's shipping rates](https://developer.allegro.pl/documentation/#operation/getListOfShippingRatestUsingGET)

Jest:
```
[
    {
        "id": "758fcd59-fbfa-4453-ae07-4800d72c2ca5",
        "name": "Mój cennik"
    }
]
```

Powinno być:
```
"shippingRates": [
    {
        "id": "758fcd59-fbfa-4453-ae07-4800d72c2ca5",
        "name": "Mój cennik"
    }
]
```

**Comment by hahyes** [comment]
Jak w Responses wybierzesz 200 OK to tam jest poprawny model, ale sample jest źle... ot, ktoś przeczoczył.

**Comment by Lukasz-Zurek** [comment]
@krzysztofgal Bardzo Ci dziękujemy za zgłoszenie błędu. Przekazałem już do odpowiedniego zespołu. Wkrótce poprawimy dokumentację.

**Comment by Lukasz-Zurek** [comment]
@krzysztofgal Poprawiliśmy już dokumentację.
