### ISSUE TITLE
przyciski logowania i rejestracji w moim sklepie internetowym

### ISSUE THREAD

**Issue by Byweris** [allegro/allegro-api#5606]
Cześć,

Prosimy o zapoznanie się z dokumentacją dotyczącą implementacji funkcji logowania i rejestracji allegro dla innych stron internetowych.

Moim celem jest wdrożenie systemu użytkownika allegro jako głównego i jedynego systemu identyfikacji użytkowników. Przy okazji, jeśli to niemożliwe, daj mi znać :(

**Comment by hahyes** [comment]
Chodzi ci o samą autoryzację login-hasło? Allegro API nie posiada takiej funkcjonalności do logowania za pomocą loginu i hasła. Wymagane jest zarejestrowanie przez klienta aplikacji i skorzystanie z client_id i client_secret. Więcej o tym masz tutaj: https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR

**Comment by Lukasz-Zurek** [comment]
@Byweris Jak już wspomniał **hahyes** - nie udostępniamy funkcjonalności, o której piszesz.

Jeżeli natomiast chciałbyś zintegrować się z naszym API, to w pierwszej kolejności powinieneś zarejestrować aplikację na [tej stronie](https://apps.developer.allegro.pl). Proces autoryzacji opisaliśmy w naszym [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

W razie dodatkowych pytań - jestem do dyspozycji.

**Comment by Byweris** [comment]
Gdzieś wyczytałem, że jest api do zaimplementowania przycisku logowania i rejestracji ze strony allegro do użycia na dowolnej stronie. Zwykłe przyciski logowania i rejestracji użytkownika, dołączając zrzut ekranu poniżej.
Daj mi znać, jeśli jest do tego jakieś API. dzięki

![paveikslas](https://user-images.githubusercontent.com/102311177/162409926-0b8dc0f7-4ac6-4a9d-88fd-5f816d6900eb.png)
![Screenshot_155](https://user-images.githubusercontent.com/102311177/162409987-dbb9fc4c-e484-463b-8a60-dbf3692279f0.png)

**Comment by Byweris** [comment]
Gdzieś wyczytałem, że jest api do zaimplementowania przycisku logowania i rejestracji ze strony allegro do użycia na dowolnej stronie. Zwykłe przyciski logowania i rejestracji użytkownika, dołączając zrzut ekranu poniżej.
Daj mi znać, jeśli jest do tego jakieś API. dzięki

![paveikslas](https://user-images.githubusercontent.com/102311177/162409926-0b8dc0f7-4ac6-4a9d-88fd-5f816d6900eb.png)

**Comment by Lukasz-Zurek** [comment]
@Byweris Rozumiem. Nie mamy jednak tego typu funkcjonalności w naszym API.

**Comment by hahyes** [comment]
> Gdzieś wyczytałem, że jest api do zaimplementowania przycisku logowania i rejestracji ze strony allegro do użycia na dowolnej stronie. Zwykłe przyciski logowania i rejestracji użytkownika, dołączając zrzut ekranu poniżej. Daj mi znać, jeśli jest do tego jakieś API. dzięki
> 
> ![paveikslas](https://user-images.githubusercontent.com/102311177/162409926-0b8dc0f7-4ac6-4a9d-88fd-5f816d6900eb.png)

@Byweris Teoretycznie, jeżeli wejdziesz na stronie logowania w dev toolsy i wejdziesz w zakładkę Network po czym się zalogujesz... możliwe, że rozwiązanie samo ci się pokaże. :)
