### ISSUE TITLE
Jak sprawdzić w jaką drogą zostały wystawione lub wznowione aukcje. 

### ISSUE THREAD

**Issue by wwm99** [allegro/allegro-api#5607]
Dzień dobry,
czy można sprawdzić czy następujące aukcje zostały wystawione/wznowione poprzez API? Czy ostatnie działanie ich wystawienia lub wznowienia było poprzez panel sprzedażowy Allegro? Chodzi o numery jak poniżej:
9861654680, 11917487581

Pozdrawiam!

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem i nie odnotowałem faktycznych zmian we wskazanych ofertach w ostatnich 30 dniach. Dodam jednak, że dla daty 28.03 sprawdziłem logi i mogę tu jedynie potwierdzić, że mieliśmy jednorazową akcję migracji po naszej stronie. Nie doszło tutaj do żadnej zmiany widocznej na zewnątrz, jednak zostało to odnotowane wewnątrz, choćby w naszych logach.
