### ISSUE TITLE
Problem ze wznawianiem aukcji 

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#5608]
Mam problem ze wznawianiem aukcji, po mimo wysłania żądania które kończy się odpowiedzią sukces aukcja nie zostaje wznowiona.
Wysłane dane mam tylko w postaci dump z php ale myślę ze będą zrozumiałe.

Przykład aukcja 10915078965
UUID f6750b3d-1102-4bf0-8813-407dced23032  sale/offer-quantity-change-commands

`
array(2) {
  ["modification"]=>
  array(2) {
    ["changeType"]=>
    string(5) "FIXED"
    ["value"]=>
    string(1) "1"
  }
  ["offerCriteria"]=>
  array(1) {
    [0]=>
    array(2) {
      ["type"]=>
      string(15) "CONTAINS_OFFERS"
      ["offers"]=>
      array(1) {
        [0]=>
        array(1) {
          ["id"]=>
          string(11) "10915078965"
        }
      }
    }
  }
}
`
i tu odpowiedź sukces 
`
object(stdClass)#16 (1) { ["tasks"]=> array(1) { [0]=> object(stdClass)#15 (7) { ["offer"]=> object(stdClass)#14 (1) { ["id"]=> string(11) "10915078965" } ["message"]=> string(0) "" ["status"]=> string(7) "SUCCESS" ["scheduledAt"]=> string(24) "2022-04-05T06:20:52.445Z" ["finishedAt"]=> string(24) "2022-04-05T06:20:52.445Z" ["field"]=> string(8) "quantity" ["errors"]=> array(0) { } } } } 
`

Teraz wznowienie ten samej aukcji sale/offer-publication-commands
UUID b48e7362-d00f-48aa-b7cb-b1f094071130

`
array(2) {
  ["offerCriteria"]=>
  array(1) {
    [0]=>
    array(2) {
      ["offers"]=>
      array(1) {
        [0]=>
        array(1) {
          ["id"]=>
          string(11) "10915078965"
        }
      }
      ["type"]=>
      string(15) "CONTAINS_OFFERS"
    }
  }
  ["publication"]=>
  array(2) {
    ["action"]=>
    string(8) "ACTIVATE"
    ["scheduledFor"]=>
    string(20) "2022-04-05T08:21:43Z"
  }
}

`

odpowiedź 
`
object(stdClass)#17 (1) { ["tasks"]=> array(1) { [0]=> object(stdClass)#15 (7) { ["offer"]=> object(stdClass)#14 (1) { ["id"]=> string(11) "10915078965" } ["message"]=> string(68) "Could not change offer publication status. Niepoprawna liczba sztuk." ["status"]=> string(4) "FAIL" ["scheduledAt"]=> string(24) "2022-04-05T06:16:43.597Z" ["finishedAt"]=> string(24) "2022-04-05T06:16:43.595Z" ["field"]=> string(11) "publication" ["errors"]=> array(1) { [0]=> object(stdClass)#16 (5) { ["code"]=> string(12) "UnknownError" ["message"]=> string(36) "Incorrect initial quantity of stock." ["details"]=> NULL ["path"]=> NULL ["userMessage"]=> string(25) "Niepoprawna liczba sztuk." } } } } } 

`

No ok rozumiem nie prawidłowa liczba sztuk ale chwilę wcześniej wysłałem ile ich jest, w żądaniu wznowienia specjalnie podaję scheduledFor z czasem +5 minut.

I co ja mam z tym zrobić ?

**Comment by Lukasz-Zurek** [comment]
To problem po naszej stronie. Temat przekazałem już do zespołu odpowiedzialnego za tę funkcjonalność.

Jak tylko uzyskam informacje dotyczące wdrożenia poprawki - dam znać w wątku.

Przepraszamy za utrudnienia.

**Comment by mzawodzinski** [comment]
Podbijam żeby bot nie zamkną
