### ISSUE TITLE
Activation of company account in sandbox

### ISSUE THREAD

**Issue by sellosebastian** [allegro/allegro-api#561]
Hello, 

I've tried activating an account in the sanbox but it's not working. Could you please activate it? The account is "selloio".

**Comment by KrzysztofLukanowski** [comment]
Hi, 

Your account is already fully active.

**Comment by PatrykCholewa** [comment]
Could I have mine activated too? It's 'pcholewa'.

**Comment by TomekKaczmarek** [comment]
@PatrykCholewa Done :).
