### ISSUE TITLE
Centrum wiadomości limit treści wiadomości

### ISSUE THREAD

**Issue by avello** [allegro/allegro-api#5611]
Jaki jest limit długości wiadomości, bo nie ma informacji w dokumentacji a dostałem błąd "Wiadomość zbyt długa"

Trace-ID: 6f88697b740fab4b

Dotyczy metody POST /messaging/threads/{threadId}/messages

**Comment by AureliuszBrussy** [comment]
Limit wiadomości to 2000 znaków. Uzupełnimy tą informację w dokumentacji.

**Comment by avello** [comment]
Trochę utrudnia to pracę, bo można to obejść wysyłając wiadomość przez pocztę email i krótsze wiadomości będzie można wysyłać przez API a dłuższe przez email ;)

**Comment by avello** [comment]
Najlepiej usunąć ten limit, wtedy będzie można całkowicie przejść na obsługę wiadomości z poziomu API

**Comment by AureliuszBrussy** [comment]
@avello przekazałem sugestię. Jeżeli zdecydujemy się na zmianę - poinformuję o tym.
