### ISSUE TITLE
Unsupported grant type - Autoryzacja Device Flow

### ISSUE THREAD

**Issue by Electronc** [allegro/allegro-api#5613]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Korzystając z metody autoryzacyjnej device flow opisanej w poradniku i wykorzystując proponowany kod python uzyskuje taki response z funkcji get_acces_code - {"error":"unsupported_grant_type","error_description":"Unsupported grant type"}

Funkcja:
def get_access_token(device_code):
    try:
        headers = {'Content-type': 'application/x-www-form-urlencoded'}
        data = {'grant_type': 'urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code', 'device_code': device_code}
        api_call_response = requests.post(TOKEN_URL, auth=(CLIENT_ID, CLIENT_SECRET),
                                          headers=headers, data=data, verify=False)
        return api_call_response
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

Pozdrawiam,

**Comment by Lukasz-Zurek** [comment]
@Electronc W naszym przykładzie był błąd. Już go poprawiliśmy.

Poniższą część:

`data = {'grant_type': 'urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code', 'device_code': device_code}`

zamień na:

`data = {'grant_type': 'urn:ietf:params:oauth:grant-type:device_code', 'device_code': device_code}`

**Comment by Electronc** [comment]
@Lukasz-Zurek O dziwo jeszcze w piątek działało :).
Dzięki bardzo za odpowiedź.
