### ISSUE TITLE
Error Numer błędu: f1b49e8fd61af7d9 after integration login 

### ISSUE THREAD

**Issue by shing1001** [allegro/allegro-api#5617]
Hello, 

We have completed the integration but when the user try to login through our integration it shows error: Numer błędu: f1b49e8fd61af7d9

Attached please find the URL and the screenshot of the error.
URL:
https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=f64c581576a4428e9ab7b79562d46d8d&redirect_uri=https://api.outvio.com/allegro/621e2f697c80e51f3affe530/ayth

![Uploading Screenshot 2022-04-13 at 17.44.01.png…]()

**Comment by AureliuszBrussy** [comment]
you are providing an incorrect redirect address, inconsistent with the one declared in the registered application in the [Developer Apps](https://apps.developer.allegro.pl/) tab. The redirect address should be exactly the same.
