### ISSUE TITLE
Upload zdjęcia i status 0

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#5618]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Wysyłam załącznik do dyskusji który wysyłany jest poprzez link

https://upload.allegro.pl/sale/dispute-attachments/34d495a9-fd0f-4e73-b3ba-ff54380ab2e8 

otrzymuję w odpowiedzi status 0 i dodatkowo informację: Nie można zapisać danych do połączenia transportowego: Istniejące połączenie zostało gwałtownie zamknięte przez zdalnego hosta.

Co jest nie tak?

**Comment by hahyes** [comment]
Status 0 oznacza problem z internetem po twojej stronie. To jest odpowiedź klienta HTTP a nie serwera API.

**Comment by AureliuszBrussy** [comment]
@marmited wygląda na to, że problem z połączeniem występuje po Twojej stronie (klienta HTTP). Nie jest to odpowiedź z naszego API.

**Comment by marmited** [comment]
Mieliśmy implementację niezgodną z dokumentacją, co ciekawe wydaje się, że wcześniej nam to działało (rok wcześniej).

Dla potomnych, tak należy to wysłać za pomocą RestSharp:

```
            var request = new RestRequest(Method.PUT);
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Content-Type", contentType);
            request.AddHeader("Authorization", "Bearer " + accessToken);
            
            request.AddParameter(contentType, byteImage, ParameterType.RequestBody);
```
