### ISSUE TITLE
czy oferty testowe na sandbox są płatne?

### ISSUE THREAD

**Issue by krzysztofchowaniak** [allegro/allegro-api#5619]
otrzymuje maile z ponagleniem o oplate dla allegro sandbox
za wystawienie ofert testowych
utworzonych dla testu api w srodowisku testowym

**Comment by krzysztofchowaniak** [comment]
zgodnie z 
Zasady korzystania z testowej wersji interfejsu programistycznego Serwisu Allegro
W ramach strony allegro.pl.allegrosandbox.pl masz możliwość nieodpłatnego testowania interfejsu programistycznego Serwisu Allegro (REST API) w ramach jednego środowiska (dalej “Usługa”).

**Comment by krzysztofchowaniak** [comment]
w ostatnim mailu otrzymalem info o skierowaniu do windykacji

**Comment by AureliuszBrussy** [comment]
Proszę nie przejmować się tymi wiadomościami oraz je zignorować - oczywiście realne opłaty **nie są** naliczane na Sandboxie. Mail dotyczy części jednego z naszym procesów, natomiast oczywiście realnie żadna kwota na koncie testowym nie zostanie poddana windykacji.

**Comment by krzysztofchowaniak** [comment]
ok,rozumiem
