### ISSUE TITLE
Lista wszystkich aukcji - REST

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#562]
Witam,
Potrzebuję informacji w jaki sposób mogę dostać listę wszystkich moich aukcji. Potrzebuje numer tej aukcji, jest już jakiś zasób z którego mogę to otrzymać czy jeszcze muszę korzystać z WebAPI?

**Comment by wwwfactory** [comment]
/offers/listing?seller.id=
i dalej już filtrowanie ... jak w dokumentacji
https://developer.allegro.pl/documentation/#/offers-listing/getListing
