### ISSUE TITLE
Czas oczekiwania na status polecenia (command)

### ISSUE THREAD

**Issue by grzegorzosipiak** [allegro/allegro-api#5620]
Po wywołaniu PUT /sale/offer-quantity-change-commands/{guid}, jak długo należy sprawdzać wykonanie danego polecenia żeby mieć pewność otrzymania jakiegoś statusu - failed lub seccess (GET /sale/offer-quantity-change-commands/{guid})?

**Comment by hahyes** [comment]
https://developer.allegro.pl/documentation#operation/getQuantityModificationCommandTasksStatusesUsingGET

Użyj zasobu GET /sale/offer-quantity-change-commands/{guid}/tasks, tam otrzymasz szczegółowe informacje co do statusu danego polecenia. Co do pewności - nie ma ściśle określonego czasu. W przypadku awarii czas może się wydłużyć do godzin. Dlatego ten zasób jest asynchroniczny.

**Comment by AureliuszBrussy** [comment]
Tak jak napisał @hahyes - jest to zasób asynchroniczny, nie ma ściśle określonego czasu zakończenia. Przyjmujemy natomiast, że może to potrwać nawet do godziny, choć zwykle trwa znacznie krócej. 

Możesz sprawdzić, czy komenda została zakończona porównując: success + failed == total ([GET /sale/offer-quantity-change-commands/{commandId}](https://developer.allegro.pl/documentation#operation/quantityModificationCommandUsingPUT)). Dla [GET /sale/offer-quantity-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation#operation/getQuantityModificationCommandTasksStatusesUsingGET) - komenda jest zakończona w momencie, gdy każdy z tasków ma status SUCCESS lub FAIL. Oczywiście zwracamy taski ze statusem NEW dopóki nie został on przeprocesowany.
