### ISSUE TITLE
Serwer odrzuca połączenie do zasobu /sale/product-offers/{id}/{guid}/

### ISSUE THREAD

**Issue by ahaw** [allegro/allegro-api#5623]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment

Podczas odpytywania zasobu  $"/sale/product-offers/{id}/operations/4bee54ff-0c31-441b-a949-f1e0df89c1d8" w celu sprawdzenia statusu operacji często dostaje wyjątek "SocketException: No connection could be made because the target machine actively refused it."
Problem nie występuje przy korzystaniu z innych zasobów.

Jakich jeszcze informacji mogę udzielić które mogą pomóc rozwiązać problem?

Nie wydaje mi się, że to może być związane z przekroczeniem limitu requestów.

**Comment by AureliuszBrussy** [comment]
Nie jest to odpowiedź z naszego API, nie wchodzi tutaj w grę przekroczenie limitu requestów - otrzymałbyś odpowiedni response. Wygląda to na problem z połączeniem, możliwe, że z Twoim firewallem - może on blokować to połączenie.

**Comment by ahaw** [comment]
To nie jest problem z firewall. Wtedy byłby raczej problem z timeout.
Próbowałem również z innej lokalizacji na innym łączu.
Jest ten sam problem i tylko na tym endpoincie

**Comment by AureliuszBrussy** [comment]
@ahaw sprawdzamy to jeszcze po naszej stronie. Wrócę z informacją.

**Comment by ahaw** [comment]
Co mogę od siebie jeszcze dodać to nie występuje to za każdym razem. Czasem
uda się uzyskać odpowiedź z serwera się po kilku razach znowu jest problem

**Comment by ahaw** [comment]
@AureliuszBrussy widzę, żę chyba coś udało się zadziałać. Problem się rozwiązał :)
