### ISSUE TITLE
Pobieranie ofert wraz z zestawami

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#5624]
Czy jest możliwość szybciej pobrać listę ofert wraz powiązanymi promocjami niż poprzez poniższe kroki?
1. Pobranie ofert.
2. Iterowanie po każdej ofercie i pobieranie każdej promocji osobno (a właściwie zestawu: promotionType=BUNDLE) dla konkretnej oferty: `/sale/loyalty/promotions?offer.id={offerId}`

**Comment by MartaNowaczyk** [comment]
Możesz też pobrać informacje o promocyjnych zestawach ofert, gdy skorzystasz z odpowiedniego filtra dla promotionType GET /sale/loyalty/promotions?promotionType=BUNDLE

**Comment by uranity** [comment]
Tak, ale potrzebuję pobrać listę ofert ze szczegółami ofert, a w /sale/loyalty/promotions?promotionType=BUNDLE&offer.id={offerID} jest tylko informacja o promocyjnych zestawach dla oferty, ale jedynie z ID oferty, bez dodatkowych informacji o ofercie.

Właściwie to potrzebuję docelowo mieć liste ofert, zarówno z promocjami, jak i bez, ze szczegółami zarówno tych ofert, jak i promocyjnych zestawów, jeśli istnieją. Jak zrobić to najszybciej, bez zbędnej ilości zapytań?
