### ISSUE TITLE
Updating parcel status 

### ISSUE THREAD

**Issue by filip-frisbo** [allegro/allegro-api#5625]
Hello,

I couldn't find a way to update the parcel status in the api docs.
The one that shows up when looking at the details of an order.

![image](https://user-images.githubusercontent.com/103931881/163793775-75c95872-a781-491f-938c-d063289be037.png)

Can I get an input on this?
Thank you!

**Comment by AureliuszBrussy** [comment]
Hello. You can only change order fulfillment status by using [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT). Tracking for the buyer is visible after entering the tracking number in the order ([POST /order/checkout-forms/{id}/shipments](https://developer.allegro.pl/documentation/#operation/createOrderShipmentsUsingPOST)), but only for selected carriers.
