### ISSUE TITLE
HttpMessageNotReadableException error following the documentation

### ISSUE THREAD

**Issue by tapasa30** [allegro/allegro-api#5627]
The problem is:
 - [X] with a REST API resource
 - [] with the production environment / with the production environment
 - [X] with the test environment
 - [] with login or authorization
 - [] at https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [] inne / other

:beetle: **Description**

**HttpMessageNotReadableException** occurs on submit product proposal via **/sale/product-proposals**

Full request data: 
```
      "url" => "https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals"
      "options" => [
        "http" => [
          "method" => "POST"
          "header" => """
            User-Agent: AsocialMedia/AllegroApi/v3.1.0 (+https://asocial.media)\r\n
            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTA1MDE0NTAsInVzZXJfbmFtZSI6IjEwNDc1NjExMiIsImp0aSI6ImM0OTAwN2ExLTRmYzEtNDBhZS05MDYwLTUyODVjYzlhM2VkYSIsImNsaWVudF9pZCI6IjU5NDc4YzA0NzlkNjQ0Mzg5ZTdmODM0ZjBmMjA5NzVjIiwic2NvcGUiOlsiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIl0sImFsbGVncm9fYXBpIjp0cnVlfQ.dHBsrwh1QSJUrUy_HFQ5C5KdYvSuxyciYo07OyVnTCTjNz2XachdHn7-coCPoDrkqzUXWQMo4efP7MUlBoNz3patpPfQG3wJbVARO4gDNmMbBm4XwSIjpyXOGUxOefGJ0b75ZwBgoYs4u_FKToVgyX-P_kiCBt4-FZ2qsGBr8Mg_FgNk3GoqebsMgwP9RqbjJZIpUKCxLHaTE8brpg99JLzpxJL_i2yexf0rUf5DVvDu4aauBsVuKSq7CiEU6FVDifJCzNWpzgTJgvEIS2WKrmBhpc_-KLE9_UdjuROW0S05F4Pv_x_bmLOPWHQOEmAeMgSX2WN3gtGiGK5Q2zboE41R0Dew74irgILE_ydK7D1FOZ6RS-iCmyLf983OIWbNk0ZqS98_beleGz6X81BwkrhheFMHGtegJfM7RVtWr7P9Zry8FC-5qBhkRuNabTU6fh3j7Cg8jVzGQVbQ4bQpcadnrPiOsNm7GGun8JdwqribLsGTwRSMyIU4oPl11GCm9qPNIDMiI-JYFSawbYqaFspJSDnX-ghHcSDacfhyfsKtw_hgjI60QLSQaj5To7acJAJLWxwRkbo1ktjcsGJgGRXJe23g6EewKDCq5WANkx5h76D507bs-sKrZNKjFz6886HYdAdB82i1XPYuIgJCgsmlx12gBoxq3WNI4u9A3xc\r\n
            Content-Type: application/vnd.allegro.public.v1+json\r\n
            Accept: application/vnd.allegro.public.v1+json\r\n
            Accept-Language: pl-PL\r\n
            """
          "content" => "{"category":{"id":"316094"},"name":"Blu-Ray Sony BDPS1700B","images":[{"url":"https://www.electrotres.com/pub/media/catalog/product/cache/75eed2686e01eb22cb4050b2f40ddf97/4/5/4548736013544-0_1.jpg"}],"parameters":[{"id":"248281","name":"Rodzaj","values":["inne"],"valuesIds":["248281_891290"],"valuesLabels":["inne"]},{"id":"225693","name":"EAN","values":["4548736013544"],"valuesLabels":["4548736013544"]},{"id":"248811","name":"Marka","values":["Sony"],"valuesLabels":["Sony"]}],"description":{"sections":[{"items":[{"type":"string","content":"Si eres un apasionado de la <b>inform\u00e1tica y la electr\u00f3nica<\/b>, te gusta estar a la \u00faltima en tecnolog\u00eda y no perderte detalle, compra <b>Blu-Ray Sony BDPS1700B<\/b> al mejor precio. <ul><li>Caracter\u00edsticas: <ul><li>Bloqueo para ni\u00f1os<\/li><li>HD<\/li><li>Full HD<\/li><\/ul><\/li><li>Formatos: Blu-ray BD-ROM<\/li><\/ul>"}]}]}}"
        ]
```
Response:
`{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}`

**Comment by tapasa30** [comment]
Oh that fixed the error, many thanks.
I am reviewing the other data sent and now the API is returning some feedback from errors but I don't know how to fix them.

```
"errors":[
      {
         "code":"VALIDATION_ERROR",
         "message":"Błędny tag \"${param1}\", dozwolone są: ${param2}",
         "details":null,
         "path":"standardized.sections[0].items[0].content",
         "userMessage":"Błędny tag \"${param1}\", dozwolone są: ${param2}"
      },
      {
         "code":"ConstraintViolationException.ImageBadOrigin",
         "message":"An error has occurred",
         "details":null,
         "path":"images.url[0]",
         "userMessage":"Niepoprawne zdjęcie. Zdjęcia muszą być przesłane przy pomocy Allegro REST API."
      }
   ]
```
Which are **param1** and **param2** tags?

For the image I see an endpoint to upload them, but I dont really know how is the procedure.
First upload here **https://upload.{environment}/sale/images** and then the result URL is placed into product urls?

**Comment by AureliuszBrussy** [comment]
@tapasa30 your description structure is incorrect. Please check the possible HTML tag combinations in [our tutorial](https://developer.allegro.pl/tutorials/listing-offers-4RAvLdaqMf8#offer-description). 
We are also checking why the response returns variable names instead of specific values.

About image error: yes, for this endpoint ([POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct)) you need to upload images to our server first ([POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST)).

**Comment by tapasa30** [comment]
Continuing with the publish process, I have some doubts when setting parameters:
In the case I have a dictionary value, I understand that parameter "valuesIds" must be filled, the doubt is if other fields like "valuesLabes" have to be filled too or is optional. So just sending "valuesIds" will be fine.

**Comment by AureliuszBrussy** [comment]
Yes, usually for a dictionary parameter you only need to fill the id of the values in "valuesIds" field. But, there may be exceptions in the form of ambiguous values. In this case, it may be necessary to add value to the "values" field. 

You can read more about this in [our news](https://github.com/allegro/allegro-api/issues/3917).
