### ISSUE TITLE
Error in proposed changes to product endpoint

### ISSUE THREAD

**Issue by Glocom-Global** [allegro/allegro-api#5628]
Hi,

We have issues working with "Propose changes in product" endpoint. We do not wish to change the brand and so not mentioning that in request throws error saying its mandatory. With no choice, if we mention Brand parameter , api again throws error "[Too many values in parameter 3786 (Brand)]".

Please clarify on how to proceed further.

Case 1: Without Brand Parameter
POST https://api.allegro.pl/sale/products/a0a41075-dc7a-4a7e-8904-c60a71679be4/change-proposals

{"name":"Test Variant 2","category":{"id":"124264"},"images":[{"url":"https://a.allegroimg.com/original/11eb40/5358a3e748f5ad4f2a96ec1ed6ff"}],"parameters":[{"id":"11323","values":[],"valuesIds":["11323_1"],"rangeValue":null},{"id":"54","values":[],"valuesIds":["54_562125"],"rangeValue":null},{"id":"451","values":[],"valuesIds":["451_524288"],"rangeValue":null},{"id":"3766","values":[],"valuesIds":["3766_14"],"rangeValue":null},{"id":"127662","values":[],"valuesIds":["127662_1"],"rangeValue":null},{"id":"127488","values":[],"valuesIds":["127488_5"],"rangeValue":null},{"id":"127468","values":[],"valuesIds":["127468_11"],"rangeValue":null},{"id":"59","values":[],"valuesIds":["59_2429"],"rangeValue":null},{"id":"4126","values":[],"valuesIds":["4126_4"],"rangeValue":null},{"id":"18160","values":[],"valuesIds":["18160_1"],"rangeValue":null},{"id":"201025","values":[],"valuesIds":["201025_2513"],"rangeValue":null},{"id":"201017","values":[],"valuesIds":["201017_2357"],"rangeValue":null},{"id":"202477","values":[],"valuesIds":["202477_1"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Taking glamour to a whole new level, this women's square collar sequins dress will make you the brightest babe in the whole party. This mesh sleeve will give you a unique look and makes you shine bright like the stars in the sky. This three-quarter-sleeved dress is the way to go when you want to make a statement while staying classy.</p>"}]}]}}

Response Error:
{
    "errors": [
        {
            "code": "CreateProductSuggestionValidationException",
            "message": "Zgłaszanie błedów w produkcie zakończyło się błędem: Wymagane parametry: [3786] nie zostały uzupełnione",
            "details": null,
            "path": "/sale/products/a0a41075-dc7a-4a7e-8904-c60a71679be4/change-proposals",
            "userMessage": "Zgłaszanie błedów w produkcie zakończyło się błędem: Wymagane parametry: [3786] nie zostały uzupełnione"
        }
    ]
}
----------------------------------------------------------------------------
Case 1: With Brand Parameter

Request:

POST https://api.allegro.pl/sale/products/a0a41075-dc7a-4a7e-8904-c60a71679be4/change-proposals

{"name":"Test Variant 2","category":{"id":"124264"},"images":[{"url":"https://a.allegroimg.com/original/11eb40/5358a3e748f5ad4f2a96ec1ed6ff"}],"parameters":[{"id":"11323","values":[],"valuesIds":["11323_1"],"rangeValue":null},{"id":"3786","values":["Oak & Sherry"],"valuesIds":["3786_85"],"rangeValue":null},{"id":"54","values":[],"valuesIds":["54_562125"],"rangeValue":null},{"id":"451","values":[],"valuesIds":["451_524288"],"rangeValue":null},{"id":"3766","values":[],"valuesIds":["3766_14"],"rangeValue":null},{"id":"127662","values":[],"valuesIds":["127662_1"],"rangeValue":null},{"id":"127488","values":[],"valuesIds":["127488_5"],"rangeValue":null},{"id":"127468","values":[],"valuesIds":["127468_11"],"rangeValue":null},{"id":"59","values":[],"valuesIds":["59_2429"],"rangeValue":null},{"id":"4126","values":[],"valuesIds":["4126_4"],"rangeValue":null},{"id":"18160","values":[],"valuesIds":["18160_1"],"rangeValue":null},{"id":"201025","values":[],"valuesIds":["201025_2513"],"rangeValue":null},{"id":"201017","values":[],"valuesIds":["201017_2357"],"rangeValue":null},{"id":"202477","values":[],"valuesIds":["202477_1"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Taking glamour to a whole new level, this women's square collar sequins dress will make you the brightest babe in the whole party. This mesh sleeve will give you a unique look and makes you shine bright like the stars in the sky. This three-quarter-sleeved dress is the way to go when you want to make a statement while staying classy.</p>"}]}]}}

Response Error:
{
    "errors": [
        {
            "code": "CreateProductSuggestionValidationException",
            "message": "Zgłaszanie błedów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Zbyt wiele wartości w parametrze 3786 (Marka)]",
            "details": null,
            "path": "/sale/products/a0a41075-dc7a-4a7e-8904-c60a71679be4/change-proposals",
            "userMessage": "Zgłaszanie błedów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Zbyt wiele wartości w parametrze 3786 (Marka)]"
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
Thank you for reporting this problem. If it comes to the first example, it's not a bug, in the request body, you should provide all of the required parameters in a given category, even those which are not modified. The second case actually indicates a problem on our side. I've reported it to our corresponding team. I'll be back with an answer when the problem is solved.

**Comment by PrzemyslawLukanowski** [comment]
Also, you can add `Accept-Language` header with `en-US` value to receive error messages in English.

**Comment by Glocom-Global** [comment]
Thank you. Please update us when the issue is resolved. Meanwhile, we will
follow you advise on other issues and using language header.

**Comment by Glocom-Global** [comment]
Hello,

Do you have any update on the issue?

Thanks

**Comment by PrzemyslawLukanowski** [comment]
Hello, unfortunately, not yet. I will let you know when the problem is resolved.

**Comment by Glocom-Global** [comment]
Ok. I am trying to understand how listing a brand works. Should I first
register a brand before using it in product listing? I don't find good
explanation for this.

**Comment by PrzemyslawLukanowski** [comment]
If the brand is not available in the list of possible values in the parameter in a given category, you can pass it as a [custom value](https://developer.allegro.pl/news/categories-and-parameters-add-your-own-value-for-dictionary-parameter-with-ambiguous-value-E7ZbqqWLVFB). When it comes to the problem described in the thread - this is a bug on our side.

**Comment by Glocom-Global** [comment]
Do you have any update on the bug?

**Comment by PrzemyslawLukanowski** [comment]
Sorry, but not yet, our team is still working on it. The product from this thread has been removed, are you receiving this kind of error for other products?

**Comment by Glocom-Global** [comment]
Yes it is a common error we receive on any product we try listing

**Comment by PrzemyslawLukanowski** [comment]
This resource is intended for reporting invalid values in the product data. It's a reflection of [this feature](https://allegro.pl/moje-allegro/sprzedaz/zglos-blad-w-produkcie/a3182824-1242-4af4-82da-7027b99b0f44) from our website. What I'm trying to say is - are you sure you are using the proper endpoint to list products? Because you wrote that you "receive on any product we try listing".

**Comment by PrzemyslawLukanowski** [comment]
I've received information that the problem should not occur anymore.

**Comment by Glocom-Global** [comment]
Please ignore the previous message. This is the reply from my developer

Yes we receive error almost for every attempt. Passing [] solves the bug in
their system. We need a proper resolution from them

**Comment by Lukasz-Zurek** [comment]
@Glocom-Global Thank you for your explanation. 

If you have any additional issues, do not hesitate to contact us.
