### ISSUE TITLE
Obsługa czasu w komunikacji z RestApi

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#563]
Dzień dobry.
proszę o uściślenie informacji na temat obsługi czasu: 

Z zapisu wynika że posługujecie się czasem w strefie czasowej UTC ? 
Czy podając czas wystawienia nowej oferty również zamienić nasz czas 'Europe Warsaw' czas na strefę czasową UTC ?
Brak jest w dokumentacji informacji na ten temat. Może warto uzupełnić ? 
(https://developer.allegro.pl/about/#datetime)  

Pozdrawiamy 
wwwfactory

**Comment by wwwfactory** [comment]
Okey, w takim razie poprawcie w dokumentacji w tym miejscu : 
"shipmentDate":"2018-04-01T08:00:00Z"
(macie Z na końcu)

**Comment by TomekKaczmarek** [comment]
@wwwfactory Z jest zgodne z formatem ISO 8601 i tak też proszę podawać daty. Obowiązuje strefa czasowo Zulu (stąd Z). Czyli aktualnie -2h do czasu polskiego.
