### ISSUE TITLE
Brak możliwości wpisania "Rok powstania" - przyjmuje tylko wartość 4 - Kolekcje i sztuka - Antyki i Sztuka - Grafika

### ISSUE THREAD

**Issue by jkalke** [allegro/allegro-api#5632]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dla kategorii https://api.allegro.pl/sale/categories/**321817**/parameters
podano "Rok powstania" (Id: 249266) jako min: 4, max: 4.
W interface graficznym wystawiania pozycji jak i po API przyjmuje wartość tylko 4 ;)
Po API da się załadować pozycję, ale ląduje jako szkic, przy ręcznym wznowieniu trzeba wyczyścić wartość pola.

Powinno walidować np. min 1000 max 2022.

![image](https://user-images.githubusercontent.com/30772007/164770850-e8a121b0-496b-4610-ad15-24bb5e6ccf6c.png)

![image](https://user-images.githubusercontent.com/30772007/164771422-9776eb59-73a0-4160-a948-fdec52b3581f.png)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję bardzo za zgłoszenie błędu. Wrócę z informacją, gdy problem zostanie wyeliminowany.

**Comment by PrzemyslawLukanowski** [comment]
Wprowadziliśmy odpowiednią poprawkę. Przepraszam za wcześniejsze niedogodności.

**Comment by jkalke** [comment]
@PrzemyslawLukanowski bardzo dziękuję za szybką reakcję i poprawkę.

Czy może Pan podpowiedzieć jakim kanałem zgłosić prośbę o rozszerzenie filtrów na stronie allegro.pl?
Np. https://allegro.pl/kategoria/grafika-grafika-archiwalna-i-uzytkowa-26105 jest filtr po Datowaniu.

Na pozycjach (np. https://allegro.pl/oferta/drzeworyt-1898-grobowiec-zygmunta-ii-augusta-12090148808, https://allegro.pl/oferta/litografia-1848-lekno-nagrobek-nikodem-lekinski-12090121031) uzupełniliśmy nowe parametry takie jak Wiek (też wartość słownikowa) ale nie można po niej filtrować od strony panelu klienta, podobnie np. kraj powstania lub właśnie Rok powstania jak konkretny zakres (cena ma filtr od do, rok powstania też taki mógłby mieć).

**Comment by PrzemyslawLukanowski** [comment]
W przypadku pytań lub sugestii, które dotyczą naszej strony internetowej, proszę skorzystać z forum [Allegro Gadane](https://spolecznosc.allegro.pl/) lub z [formularza kontaktowego ](https://allegro.pl/pomoc/kontakt).
