### ISSUE TITLE
Prowizje i opłaty FulFillment

### ISSUE THREAD

**Issue by Fudalii** [allegro/allegro-api#5633]
Czy można pobrać dane z konta FulFillment - opłata za dany produkt lub wasze wymiary / objętość pobierana do wyliczania kosztów?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz doprecyzować, jakie dokładnie opłaty masz na myśli? Jeśli są one widoczne w sekcji "Historia operacji" w zakładce ["Rozliczenia z Allegro"](https://allegro.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro), to możesz je pobrać za pomocą [GET /billing/billing-entries](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-billingowych). Jest to jedyny endpoint, w którym zwracamy informacje o wszelkich opłatach w ramach prowadzenia konta.

**Comment by Fudalii** [comment]
Miałem na myśli opłaty za pakowanie danego produktu Ale ok. W Biling idzie to chyba wyciągnąć.

A czy jest szansa aby w /fulfillment/available-products  zwracane były też wartości waga, i wymiary ? 

![image](https://user-images.githubusercontent.com/35329148/168840232-f6426e1c-ff44-4cfa-ac01-7f3a6141d403.png)

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem taką sugestię zespołowi odpowiedzialnemu za rozwój usługi. Jeśli zdecydujemy się rozszerzyć odpowiedź tego endpointu, poinformujemy o tym na na naszej stronie i forum.

**Comment by Fudalii** [comment]
Ok. Panie Przemysławie jeszcze ostatnia rzecz. Jak usunąć lub ignorować oferty w zakładce "Zakończone". Np. mam zdublowany produkt (drugi ma zły ean) - i jest w zakończone (nie oczekujące). 

Ale w tej zakładce nie można permanentnie usunąć oferty. W efekcie w API przy tworzeniu awizo ciągle mi je dodaje. I są one zwracane w liście z /fulfillment/available-products 

Tak samo jak "oczekujące" mają status "ENDED" ... stąd nie mogę znaleźć jak je ignorować :) 

Tak w ogóle to czemu nie można permanentnie usunąć ofert z konta FF jeśli dana oferta nam nie pasuje / została źle dodana ??

**Comment by PrzemyslawLukanowski** [comment]
Jeśli chodzi o oferty One Fulfillment, to ich "żywotność" jest podobna do standardowych ofert. Usunąć może Pan oferty tylko w statusie "INACTIVE", a zakończone oferty zostaną zarchiwizowane (i tym samym usunięte) 60 dni od momentu, kiedy nadany dla nich został status "ENDED" .

**Comment by Fudalii** [comment]
Ok. Raport wymiarów można jednak pobrać w panelu FulFillment więc teoretycznie jest to gotowe :) Tylko do zwracania w API w dowolnej formie :) 

Pozdrawiam
