### ISSUE TITLE
order/customer-returns: Access denied. Contact the author of the application.

### ISSUE THREAD

**Issue by kurkonrad** [allegro/allegro-api#5634]
Witam,

potrzebuje pobrać dane z endpointu **order/customer-returns** ( jest to endpoint w wersji BETA )

pobranie tokena
```
def get_allegro_access_token(client_id, secrect_id):
    response = requests.post(
        f'{ALLEGROPL_URL_PROD}/auth/oauth/token',

        data={
            'grant_type': 'client_credentials'
        },
        verify=False,
        allow_redirects=False,
        auth=(
            client_id,
            secrect_id
        )
    )

    return json.loads(response.text).get('access_token')
```

pobranie zwrotów z endpointu order/customer-returns
```
access_token = get_allegro_access_token(
    client_id='2adc342e298b4da399ebca87561af077',
    secrect_id='4JuaqwIIgVoskPJGjF2lafF1haQ1MYX1RfsWjU0wlYYWGSQWVeG8XEFzzOswvEP5'
)


response = requests.get(
    'https://api.allegro.pl/order/customer-returns',

    headers={
        'Authorization': 'Bearer ' + access_token,
        'Accept': "application/vnd.allegro.beta.v1+json",
    }
)
```

i dostaje komunikat: **Access denied. Contact the author of the application.**

Dla innych endpointów, dostaje response poprawnie ( nie są one chyba w wersji BETA )

Moje uprawnienia w aplikacji allegro,
https://ibb.co/ww1tQbk

Kolejna jeszcze sprawa,
jak klikam w panelu developer.allegro.pl -> zarządzaj api -> moje aplikacje ( sandbox ) to nie otwiera mi się żadna strona.

Dziękuje za pomoc,
Konrad

**Comment by PrzemyslawLukanowski** [comment]
Korzystasz z autoryzacji typu "client_credentials" - token wygenerowany w ten sposób pozwala wyłacznie na dostęp do publicznych danych, bez kontekstu użytkownika. W naszej dokumentacji oznaczyliśmy je jako bearer-token-for-application przy wybranych endpointach. Jeśli chcesz mieć dostęp do danych użytkownika, musisz skorzystać z autoryzacji typu [code ](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow)lub [device ](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow)(bearer-token-for-user).

> jak klikam w panelu developer.allegro.pl -> zarządzaj api -> moje aplikacje ( sandbox ) to nie otwiera mi się żadna strona.

Spróbuj proszę usunąć pliki cookies i ponownie zalogować się na konto użytkownika. Nie udało nam sie powtórzyć tego problemu, zakładka działa prawidłowo.

**Comment by konradkur** [comment]
Dziękuje, działa. :)
