### ISSUE TITLE
Problem z pobraniem etykiety ZPL

### ISSUE THREAD

**Issue by lulzsoad** [allegro/allegro-api#5636]
Witam,

Mam problem z pobraniem etykiety ZPL.

Dla etykiety PDF przekazuję nagłówki:
Accept: application/pdf
Content-Type: application/pdf

Dla etykiety EPL przekazuję nagłówki
Accept: text/plain
Content-Type: text/plain

Dla dwóch powyższych zapytań etykiety zostają pobrane prawidłowo.
Dla ZPL przekazując nagłówki
Accept: text/plain
Content-Type: text/plain
Otrzymuję błąd 

> {"errors":[{"code":"NotAcceptableException","message":"Not acceptable representation requested. Please check 'Accept' request header","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji"}]}

Natomiast w przypadku nagłówków
Accept: application/pdf
Content-Type: application/pdf
Etykieta pobiera się, ale mam problem z wydrukiem.

Proszę o pomoc/sugestię odnośnie wspomnianego problemu

**Comment by AureliuszBrussy** [comment]
Czy mógłbyś przesyłać trace-id, które znajdziesz w nagłówku odpowiedzi z błędem? Pozwoli mi to sprawdzić to dokładniej.

**Comment by lulzsoad** [comment]
trace-id=93f4e9a7b5cc953c

**Comment by AureliuszBrussy** [comment]
Z tego co widzę, na etapie tworzenia paczki wybrałeś .pdf jako format etykiety. Świadczy o tym wartość w polu **label.fileFormat** na [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel). Jeżeli chcesz pobrać etykietę w formacie ZPL - zadeklaruj to podczas tworzenia przesyłki.

**Comment by lulzsoad** [comment]
Tak, racja, dla ZPL przez pomyłkę przypisywałem PDF. Dziękuje :)

**Comment by lulzsoad** [comment]
Czy mógłby Pan jeszcze spojrzeć na ten trace id:
trace-id: 1367eeb365903cde

Tym razem problem pojawia się z EPL na produkcji, etykieta pobiera się, ale drukarka wypluwa pustą etykietę

**Comment by AureliuszBrussy** [comment]
Weryfikuję to. Wrócę z odpowiedzią, gdy tylko coś ustalę.

**Comment by AureliuszBrussy** [comment]
Zweryfikowaliśmy to - wygenerowany plik wygląda na prawidłowy. Czy problem nadal występuje i masz jakieś podejrzenia co może być przyczyną?

**Comment by lulzsoad** [comment]
Na środowisku testowym drukuje się poprawnie, na środowisku produkcyjnym będziemy monitorować kolejne przypadki.

**Comment by AureliuszBrussy** [comment]
@lulzsoad rozumiem, w razie problemów proszę o informację.
