### ISSUE TITLE
Problem z aktywacją konta na sandbox

### ISSUE THREAD

**Issue by kfrancikowski** [allegro/allegro-api#5637]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Założyłem konto na https://allegro.pl.allegrosandbox.pl/, ale nie mogę przejść weryfikacji numeru konta do przelewów. Po wpisaniu numeru (autentycznego) dostaję komunikat "Nie mogliśmy wybrać metody weryfikacji. Spróbuj ponownie później.". Konto ma login "kfrancikowski"

**Comment by Lukasz-Zurek** [comment]
Aktywowałem i zweryfikowałem Twoje konto firmowe na Sandboxie. Możesz już korzystać z niego bez ograniczeń.

Przepraszamy za utrudnienia.
