### ISSUE TITLE
Czy zmienialiście coś przy autoryzacji aplikacji typu DEVICE?

### ISSUE THREAD

**Issue by Funiek** [allegro/allegro-api#5638]
Dzień dobry,

Wczoraj zauważyłem, że nie mogę ściągnąć zamówień. Gdy zacząłem badać temat okazało się, że problem może być w ściąganiu tokenu. Zamiast normalnego response'a dostaję:

{"error":"unsupported_grant_type","error_description":"Unsupported grant type"}

Wykorzystuję 'grant_type' => 'urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code'
Kod aplikacji nie był zmieniany od dawien dawna. Z góry dziękuję za wszelakie informacje :)

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę szczegółowe dane (w tym request) przez nasz [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub #5638.

**Comment by Lukasz-Zurek** [comment]
Co prawda nie jesteśmy w stanie zweryfikować w logach jak to wyglądało u Ciebie wcześniej, jednak wszystko wskazuje na to, że przyczyna leży po stronie zbędnego encodowania grant_type.

**Comment by Funiek** [comment]
Rzeczywiście tutaj był problem. Dzięki wielkie i życzę miłego dnia ;)
