### ISSUE TITLE
Brak kategorii w API i po stronie formularza choć kategoria z ofertami wyświetla się na Allegro

### ISSUE THREAD

**Issue by stasiubednarek** [allegro/allegro-api#5639]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Cześć,

na Allegro widać tę kategorię:
https://allegro.pl/kategoria/oswietlenie-halogeny-i-naswietlacze-305049

Natomiast przy pobieraniu z API otrzymujemy:
![image (3)](https://user-images.githubusercontent.com/79578749/165280557-3449d955-0cde-4894-8abc-6f0f67bca0c9.png)

Co ciekawe, tej kategorii nie ma też przy wystawianiu w samym Allegro (przy wyborze kategorii).
Dom i Ogród->Ogród->Oświetlenie->Halogeny i naświetlacze
Jednak w tej kategorii są oferty, natomiast teraz jest tak, że nie ma możliwości dodania do niej aukcji czy to przez API czy też sam formularz w Allegro.

Jest podobna kategoria: 301034 ale na innej gałęzi:
https://allegro.pl/kategoria/oswietlenie-halogeny-i-naswietlacze-301034
Dom i Ogród->Oświetlenie->Halogeny i naświetlacze

Pytanie: czy to przeoczenie w API/ formularzu lub dodawanie do tej kategorii zostało wygaszone?
Czy jest jakiś powód od strony konta/ lub ograniczeń dla żądań przez API?

Dzięki

**Comment by PrzemyslawLukanowski** [comment]
Jest to rezultat [scalania kategorii po stronie sprzedającego](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo) i nie należy traktować tego jako błąd. Kupujący może natomiast zobaczyć oferty w dwoch różnych działach.

**Comment by stasiubednarek** [comment]
Dziękuję, od czego zależy w której kategorii wyląduje obecnie oferta/ aukcja? Czy jest jakiś dodatkowy parametr decydujący że będzie w tej lub tej? Czy może dodając do tej właściwej oferta idzie też do tych duplikatów aby kupujący mógł znaleźć je w obu? Dobrze rozumiem?

Czy wszystkie nowe są już umieszczane w tej przekierowanej/ "jedynej poprawnej", a w tej starej są tylko jakieś wznawiane aukcje, które wyświetlają się też w docelowej?

**Comment by PrzemyslawLukanowski** [comment]
Tak, obecnie wystawione oferty również będą widoczne dla kupującego w kilku kategoriach. Więcej na temat tej zmiany możesz przeczytać również na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/laczymy-kategorie-z-tym-samym-asortymentem-AggmRPKrnuY).

**Comment by stasiubednarek** [comment]
Super, dziękuję za pomoc!
