### ISSUE TITLE
Walidacja draftu oferty w kontekście pola 'validation' => zaproszenie do dyskusji

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#564]
Witamy Ponownie.
Chciałbym zaprosić wszystkich do dyskusji na temat tego co prezentujecie w polu walidacyjnym draftu / oferty : 'validation' => ['errors']

Czy format w jakim prezentujecie informacje walidacyjne jest już formatem ostatecznym ? Pytanie to wynika z obserwacji danych jakie zwracacie do klienta w tym polu. A teraz konkrety: 

odpowiedź z RestAPi : (pozwoliłem sobie uciąć pole userMessage)

array (size=5)
              'code' => string 'VALIDATION_ERROR' (length=16)
              'message' => string 'Payments may not be empty.' (length=26)
              'details' => string '' (length=0)
              'path' => string '' (length=0)
              'userMessage' => string 'Podaj dane dotyczące płatności. Dane dotyczące .......' (length=84)
array (size=5)
              'code' => string 'VALIDATION_ERROR' (length=16)
              'message' => string 'Warunki oferty (zwroty, reklamacje) są wymagane .....' (length=64)
              'details' => string '' (length=0)
              'path' => string '' (length=0)
              'userMessage' => string 'Warunki oferty (zwroty, reklamacje) są wymagane .......' (length=64)

1. Walidacja znajduje się w ['validation']['errors'] co jest jasne i klarowne. Jaki jest cel umieszczania w polu ['code'] => 'VALIDATION_ERROR' . To nie ma sensu i jest całkowicie niepotrzebne, tym bardziej że zawsze jest to samo!
2. ['message'] jak sądzę to miała być wersja skrócona informacji zwrotnej. Dlaczego raz jest po angielsku a raz po polsku ? Dlaczego raz jest to coś innego niż w polu ['userMessage '] a następnym razem jest to dokładnie ta sama informacja.
3. pola ['details'] oraz ['path'] zawsze są puste ! 

Czytając dokumentację (https://developer.allegro.pl/about/#errors) odnoszę wrażenie że to dwa różne światy. Dodam że w polu ['userMessage'] pojawiają się różne różności pozamykane w nawiasach posklejane bez spacji lub ze spacjami (zależy jak się udało programiście) - zawarte tam informacje to np numer (catId) parametru którego dotyczy błąd zamknięty w nawiasie i drugi nawias z lakonicznym opisem.

Proszę się teraz zastanowić jak programista który dostaje takie dane ma je oprogramować ? Poproszę o wytyczne ponieważ nie znalazłem sposobu na rozłożenie tego na czynniki pierwsze. 

podsumowanie:
Jeżeli walidacja znalazła błąd w konkretnym miejscu draftu / oferty to dlaczego nie umieścić tego w polu ['code']. Jak wspomniałem powyżej to pole jest wypełnione niepotrzebnym nikomu 'VALIDATION_ERROR'. 

Czy nie powinno to wyglądać mniej więcej tak : 

array (size=5)
              'code' => string 'parameters' (element powodujący błąd - grupa najniższego poziomu)
              'message' => string 'parametr jest pusty lub niepoprawny' (metoda słownikowa ?)
              'details' => string 'valuesIds' (pole które ma złą wartość lub jej nie ma)
              'path' => string '243424' (parametr w którym błąd zaistniał)
              'userMessage' => string 'informacja szczegółowa o zaistniałym błędzie' (wg uznania)

Po otrzymaniu takiej informacji myślę że większość z nas znajdzie grupę 
['parameters'] => ['id'] = '243424', 
- nie ma tu miejsca na domysły i kieruje użytkownika w docelowe miejsce błędu, 
- jest to w 100% zgodne z poszczególnymi elementami składowymi pól draftu / oferty 
('parameters' === 'parameters') etc.
- jest klarowne i 'czyste'. 
- nie wymaga parsowania stringów które zawsze są inne i nie mają jednolitej struktury.

Pozdrawiamy 
wwwfactory

**Comment by KrzysztofLukanowski** [comment]
Mamy świadomość niedoskonałości dokumentacji, będziemy nad tym pracować. Sugestię obsługi błędów walidacji przekazałem osobom odpowiedzialnym za rozwój API.

**Comment by wwwfactory** [comment]
Okey, poczekajmy chwilkę, jeżeli nikt nie włączy się do dyskusji to zamykamy ten wątek.

**Comment by rtnet-pl** [comment]
Cześć

> Walidacja znajduje się w ['validation']['errors'] co jest jasne i klarowne. Jaki jest cel umieszczania w polu ['code'] => 'VALIDATION_ERROR' . To nie ma sensu i jest całkowicie niepotrzebne, tym bardziej że zawsze jest to samo!

Podejrzewam, że jest to przygotowane pod obsługę komunikatów innego rodzaju, jak np. warning czy notice - do wykorzystania w przyszłości

> pola ['details'] oraz ['path'] zawsze są puste !

W polu path oczekiwałbym wskazania konkretnego pola (jsonpath) co do którego proces walidacji wskazał jakieś błędy lub ostrzeżenia.

Niespójności komunikatów o błędach (tu znów domysł 😉) wynika prawdopodobnie z zaszłości i jestem przekonany, że znikną wraz ze starym api. Chociaż trochę szkoda, że nie zostało to uporządkowane wraz z publikacją zasobów, bo wymusza to stosowanie protez po stronie aplikacji.
