### ISSUE TITLE
Produktyzacja - tworzenie nowego produktu przy wystawieniu oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5640]
Przy wystawianiu nowej oferty tworzę propozycję produktu za pomocą POST /sale/product-proposals. W strukturze przekazuję jedynie jedno zdjęcie produktu. Następnie tworzę draft oferty za pomocą POST /sale/offers. W dalszych krokach uzupełniam draft danymi oraz publikuję ofertę. W drafcie uwzględniam większą ilość zdjęć. Problem w tym, że w produktyzacji zamiast jednego zdjęcia, które przekazałem przy propozycji produktu, widzę wszystkie zdjęcia dodane przy wystawianiu oferty. Czy istnieje jakiś sposób, aby nie dodawało nam do produktu Allegro zdjęć z oferty? Wygląda tak, jakby system Allegro pobierał do produktu wszystko co jest przekazywane w ofercie. Nadmienię, że problem występuje tylko w przypadku zdjęć. Opisu przy propozycji produktu nie przekazujemy i opis również nie jest pobierany z oferty - więc tutaj jest wszystko prawidłowo

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie da się wplynąć przy tworzeniu produktu przez API na późniejsze procesy związane z przypisywaniem zdjęć z oferty do produktu.
