### ISSUE TITLE
Sprzedaż - Obsługa ofert - Przegląd cen. Czy jest dostęp do wartości statystycznych przez REST API

### ISSUE THREAD

**Issue by itland1** [allegro/allegro-api#5642]
Dzień dobry,
Czy jest dostęp z poziomu REST API do cen statystycznych podanych w opcji: Sprzedaż - Obsługa ofert - Przegląd cen?
Jeśli tak to jaka bramka? Jak często są aktualizowane te wartości i w jakim czasie?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie, nie udostępniamy na ten moment takiego zasobu w publicznym API. Jeżeli się coś zmieni - zakomunikujemy to.
