### ISSUE TITLE
PROD GET offers/listing zwraca 403 Access denied. Access available only for verified applications.

### ISSUE THREAD

**Issue by edyp** [allegro/allegro-api#5643]
PROD:
Zgodnie  z waszym poradnikiem wykonałem autoryzację i pobrałem access_token z sukcesem (Response [200]). 
Mogę pobrać listę kategorii używając 'GET sale/categories' z wygenerowanym tokenem ale po odpytaniu 'GET offers/listing'  otrzymuje Response [403] `{"errors":[{"code":"VerificationRequired","message":"Access is denied. Verification is required.","details":null,"path":null,"userMessage":"Access denied. Access available only for verified applications."}]}`

Mój kod:
`    search_url ='https://api.allegro.pl/offers/listing'
     headers = {'Authorization': 'Bearer ' + self.token, 'Accept': 'application/vnd.allegro.public.v1+json'}
     params = {'phrase': search}
     response = requests.get(url=search_url, params=params, headers=headers, verify=False)
`

pobieranie access tokena (przypominam - response 200):
`self.client_id = 'c08efe5d992448a6a26da8b5cdf8e299'
self.client_secret = '2mcFRnsCrjXRQFP8iVF1Gj3JyTwzqT1EjAyQu5KERQSizxoIVqogNyx3syrFJuyy'
token_url = 'https://allegro.pl/auth/oauth/token'
data = {'grant_type': 'client_credentials'}
access_token_response = requests.post(token_url, data=data, verify=False, allow_redirects=False, auth=(self.client_id, self.client_secret))
tokens = json.loads(access_token_response.text)
access_token = tokens['access_token']`

Posiadam dwustopniowe logowanie i zarejestrowaną aplikację. Na środowisku testowym otrzymuję 200. 
Proszę o pomoc w rozwiązaniu problemu.

**Comment by AureliuszBrussy** [comment]
Proszę, zapoznaj się z [naszym komunikatem](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1) - [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) na produkcji dostępny jest tylko dla zweryfikowanych aplikacji.

**Comment by edyp** [comment]
@AureliuszBrussy Zarejestrowałem aplikację na https://apps.developer.allegro.pl/, mam dwustopniowe logowanie włączone, otrzymuję access token. Nie wiem co to znaczy, że aplikacja nie jest zweryfikowana. Co jeszcze powinienem zrobić?

**Comment by AureliuszBrussy** [comment]
Zapoznaj się proszę z [naszym komunikatem](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1). Aby przejść proces weryfikacji skontaktuj się z nami [przez formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) lub ze swoim opiekunem jeśli jesteś w Programie Partnerskim dla Sprzedających.

**Comment by edyp** [comment]
Dziękuję za wyjaśnienie.
