### ISSUE TITLE
'Accept: application/vnd.allegro.public.v1+json' błąd dla zasobu Add a users to the blacklist

### ISSUE THREAD

**Issue by T00MANY** [allegro/allegro-api#5645]
Dzień dobry.

Mam pytanie, przy próbie użycia zasobu Add a users to the blacklist jest zwracany błąd "Unsupported content type. Please check 'Content-Type' request header", natomiast request header wydaje się być dodany poprawnie tj. jest to "Accept: application/vnd.allegro.public.v1+json" zgodnie z dokumentacją. Dodam jeszcze że używałem wcześniej innych zasobów z tym samym nagłówkiem i działały. Wracając do pytania, co może być nie tak?

**Comment by Lukasz-Zurek** [comment]
Z otrzymanego przez Ciebie komunikatu błędu wynika, że przekazujesz tylko: 

**Accept: application/vnd.allegro.public.v1+json** 

a powinieneś przekazać również: 

**Content-Type: application/vnd.allegro.public.v1+json**.

Prawidłowy request znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#jak-dodac-kupujacego-do-listy-nieaktywnych-kupujacych).

**Comment by hahyes** [comment]
@T00MANY Trochę teorii, bo może wydać się to dziwne. `Content-Type` oznacza rodzaj zawartości zapytania przesyłanego przez użytkownika w metodach POST czy PUT. `Accept` oznacza rodzaj zawartości odpowiedzi, jaki ma zostać zwrócony przez serwer po zapytaniu dowolną metodą mogącą zwracać informacje (tzw. body). Dlatego `Content-Type` jest wymagane, jeżeli wysyłasz jakieś informacje metodami POST i PUT.
