### ISSUE TITLE
Dyskusje - pobieranie danych zamówienia - CheckoutFormNotFoundException

### ISSUE THREAD

**Issue by kwrobinski** [allegro/allegro-api#5646]
- [x] z zasobem REST API
- [x] ze środowiskiem produkcyjnym 

Pracuję nad prostą apką umożliwiającą odpowiadanie na dyskusje. Dla każdej pobranej dyskusji zaciągam po checkoutForm.id dane o zamówieniu. Problem z tym, że przy niektórych próbach wczytania tych informacji przez GET /order/checkout-forms/{checkoutForm.id} API zwraca mi **CheckoutFormNotFoundException** np. **Checkout form bdc5f2f1-9d3b-11eb-a4d6-8125a31c4328 not found**. Trace-id przykładowego zapytania: 30ef2819bff08786

Znalazłem informacje o tym, że checkoutForm.id mogło się zmienić, gdy klient dokonał oddzielnych zakupów i łącznie je opłacił, ale czy w takim przypadku z dyskusji nie powinno być zwrócone nowe id?

**Comment by Lukasz-Zurek** [comment]
> Pracuję nad prostą apką umożliwiającą odpowiadanie na dyskusje. Dla każdej pobranej dyskusji zaciągam po checkoutForm.id dane o zamówieniu. Problem z tym, że przy niektórych próbach wczytania tych informacji przez GET /order/checkout-forms/{checkoutForm.id} API zwraca mi **CheckoutFormNotFoundException** np. **Checkout form bdc5f2f1-9d3b-11eb-a4d6-8125a31c4328 not found**. Trace-id przykładowego zapytania: 30ef2819bff08786

Próbujesz uzyskać dostęp do zamówienia z śro, 14 kwi 2021, 18:15:09, a w naszym API zwracamy zamówienia tylko z ostatniego roku.
> 
> Znalazłem informacje o tym, że checkoutForm.id mogło się zmienić, gdy klient dokonał oddzielnych zakupów i łącznie je opłacił, ale czy w takim przypadku z dyskusji nie powinno być zwrócone nowe id?

Jeżeli pobierzesz dyskusję - zawsze zwrócimy numer zamówienia, dla którego została ona założona przez Klienta. Dodam również, że przypadek połączenia zakupów nie byłby możliwy jeżeli do jednego z nich założona została dyskusja. Taki zakup jest też opłacony, zatem technicznie nie byłoby to możliwe.
