### ISSUE TITLE
MultipleProductsFoundException: More then one product matches given ean.

### ISSUE THREAD

**Issue by podniesm** [allegro/allegro-api#5647]
Przy wykorzystaniu metody api POST /sale/product-offers otrzymuje odpowiedź HTTP 422 z komunikatem _MultipleProductsFoundException: More then one product matches given ean_. Co mam w takim wypadku zrobić aby stworzyć ofertę bazującą na produkcie? Przykład EAN=4260530792578.

**Comment by hahyes** [comment]
Zamiast EANu jako identyfikatora produktu, podaj jego UUID (które wygląda na przykład tak: c9e39cae-9cb6-11e9-a2a3-2a2ae2dbcce4).

**Comment by Lukasz-Zurek** [comment]
@podniesm Zgodnie z sugestią od **hahyes** - w tej sytuacji najlepiej będzie jak wskażesz preferowany przez Ciebie produkt, o konkretnym ID.

**Comment by Lukasz-Zurek** [comment]
@podniesm Nie mamy niestety innego rozwiązania aniżeli wspomniany GET /sale/products?

**Comment by podniesm** [comment]
@Lukasz-Zurek Szkoda, jest o duży bloker przy dużej skali ofertowej. Czy to, że w bazie produktowej Allegro pod tym samym EAN jest kilka de facto tych samych produktów jest poprawną sytuacją?

**Comment by AureliuszBrussy** [comment]
@podniesm może się tak zdarzyć - jest to poprawna sytuacja. Zdarza się np. że producenci nadają ten sam EAN produktom różniącym się od siebie kolorem lub innymi parametrami.
