### ISSUE TITLE
Komunikat błędu dla /sale/offer-publication-commands/{commandId}/tasks

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5648]
Przeszukałem dokumentację API i nigdzie nie mogę odszukać informacji, jakie dokładnie błędy zwraca metoda GET https://api.{environment}/sale/offer-publication-commands/{commandId}/tasks

Potrzebuję informacji co pojawia się w polu MESSAGE dla statusu FAIL w przypadku próby wznowienia oferty, która już wygasła (minęły 2 miesiące od zakończenia). Nie mamy nawet jak tego spreparować, ponieważ jak nawet ukryjemy ofertę, to API ją reaktywuje - a czekać 2-3 miesiące aż oferta wygaśnie, to bezsensu :) Robimy mechanizm, który wznawia ofertę (gdy jest to możliwe) lub próbuje wystawić jako nową ofertę, kiedy ta zniknie z Allegro. Do tego właśnie potrzebujemy przechwycić kod błędu

**Comment by PrzemyslawLukanowski** [comment]
Komunikat w polu `message`, który otrzymacie w takiej sytuacji, to `"Could not change offer publication status. Offer not found. It was deleted, archived or never existed."`
