### ISSUE TITLE
Pomimo różnic w parametrach, pojawia się błąd "Przedmiot, który chcesz wystawić znajduję się już na liście Twoich aktywnych ofert"

### ISSUE THREAD

**Issue by rasskabak** [allegro/allegro-api#5649]
TraceId: e90e883dceed8068
Oferta 11280545748

Wystawiamy wiele różnych wariantów kolorystycznych tego produktu. Z uwagi na specyficzne nazewnictwo kolorów, w większości ofert pole "Kolor" ma wartość "inny kolor", a faktyczną nazwę handlową koloru podajemy jako parametr dodatkowy.

"customParameters":[{"name":"Wariant","values":["Kolor: 7803 Avocado"]},{"name":"Rozmiar wielopaku","values":["25 m"]},{"name":"Identyfikator"

Mimo, że oferta jest aktualnie aktywna, a zestaw parametrów dodatkowych jest unikatowy, API zwraca komunikat, że nie dało się jej aktywowwać. Natomiast request faktycznie nie przechodzi - dodatkowe parametry podane w requeście, nie są widoczne w ofercie.

![image](https://user-images.githubusercontent.com/5887720/166144882-54d32365-b229-43a9-b4d0-575fae907128.png)

"Przedmiot, który chcesz wystawić znajduję się już na liście Twoich aktywnych ofert. Zgodnie z Regulaminem Allegro nie możesz publikować więcej niż dwóch ofert dotyczących tego samego przedmiotu z parametrem stan “Nowy” w ramach tej samej podkategorii, niezależnie od liczby posiadanych przez Ciebie kont. Wystawianie takiego samego towaru w ramach jednej kategorii wpływa na przejrzystość wyników wyszukiwania co przekłada się na decyzje zakupowe klientów. Publikacja oferty nie jest możliwa."

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że wczoraj o 14:02 wykonali Państwo zmianę (parametr "Kod producenta"), która umożliwiła wystawienie oferty - jest już ona widoczna w serwisie, wraz z parametrami dodatkowymi.
