### ISSUE TITLE
Sandbox - nie działają płatności

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#5650]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
W środowisku testowym po złożeniu zamówienia nie da się go opłacić. Karty płatniczej nie można w ogóle wybrać, button się tylko przeładowuje. Po kliknięciu w przelew mam tylko mBank i Pekao do wyboru, wybranie jakiegokolwiek z nich i kliknięciu Płacę nie jestem nigdzie przekierowywany i po kilku sekundach dostaję komunikat Płatność się nie udała.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Potwierdzam problem z płatnościami. Sprawa jest już przekazana do odpowiedniego zespołu.
