### ISSUE TITLE
Nie można stworzyć oferty poprzez "POST /sale/product-offers" bazując na danych z GET /sale/product-offers

### ISSUE THREAD

**Issue by pliszka** [allegro/allegro-api#5652]
W jaki sposób powinienem zmodyfikować odpowiedź z GET /sale/product-offers by móc użyć danych w POST /sale/product-offers ? (poza oczywiście usunięciem ID)

TraceID: 8653ea7638e86b98

**Comment by MartaNowaczyk** [comment]
Zerknij na [dokumentację](https://developer.allegro.pl/documentation/#operation/createProductOffers), dla compatibilityList nie możesz użyć typu "PRODUCT_BASED" - "For the /sale/product-offers resources you can send only definition of the MANUAL compatibility list. If compatibility list is provided for the product assigned to the offer, it will be used automatically."

Dla GET w [dokumantacji](https://developer.allegro.pl/documentation/#operation/getProductOffer) jest też info: 
1. "PRODUCT_BASED - for offers associated with product - if compatibility list is provided in the product details (GET/sale/products/{productId}), it needs to be included in the offer in unchanged form." 
2. Gdy dostajesz PRODUCT_BASED w odpowiedzi ze statusem 200 dla [items]- "Text representation of the compatibility list items. Provided for informational purposes only - ignored when creating (Post) or updating (Put) compatibility list in the offer."

**Comment by MartaNowaczyk** [comment]
Jest jeszcze jedna kwestia przy kopiowaniu danych z GET nie ma tam "type" dla tablicy "items" (compatibilityList.items[0].type) `"type": "TEXT"`.

**Comment by pliszka** [comment]
hej, nie jestem w stanie zmusić tego żeby to działało teraz dostaję błąd "{"errors":[{"code":"RemoveProductException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product","userMessage":"The product cannot be detached from the offer."}]}" 

TraceID: e6a77105a374a2a3

szczerze nie sądziłem że tak proste zadanie jak pobranie GET'em danych z endpointa i wstawienie ich POSTem w ten sam endpoint spowoduje tyle problemów.... 

czy można prosić o jakiś link do dokumentacji / posta w jaki sposób sklonować (przenieść) ofertę z jednego konta allegro na inne?

**Comment by MartaNowaczyk** [comment]
Hej, gdy dla GET dostajesz `MANUAL` to kopiujesz te dane, a jak dostajesz `PRODUCT_BASED` to powinieneś to usunąć, bo my i tak automatycznie to dołączymy z produktu. Oczywiście usuń ID oferty, podmień ID cennika, gwarancji, reklamacji itp. 

Jeśli będziesz miał mimo to jakiś przypadek z problemami, najlepiej podeślij przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) (z dopiskiem, że dotyczy wątku na GitHbie #5652) REQUEST i RESPONSE z chwili kiedy pobierasz ofertę z jednego konta i z chwili, gdy wysyłasz dane na podstawie tej oferty. Wtedy będziemy to weryfikować.

**Comment by pliszka** [comment]
hej, temat do zamknięcia, wygląda na to, że działa z 36tys ofert zostało mi kilkaset które da się tak przenieść, problem leży w tym, że stare oferty co prawda są wysyłane GETem ale za pomocą tych danych (z GET'a) nie da się stworzyć oferty, w innych przypadkach usunięcie sekcji pasuje do faktycznie pomaga i oferty się tworzą 

dla potomnych: weryfikujcie czy dostajecie cokolwiek w productSet jeśli nie to nie stworzycie na bazie tych danych oferty

**Comment by MaciejFrackowiak** [comment]
Dziękuję, że podzieliłeś się z nami swoimi spostrzeżeniami - dzięki temu inni użytkownicy szybciej uporają się, gdy przytrafi im się podobna sytuacja.
