### ISSUE TITLE
Sandbox - wysyłka maila z fakturą

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#5654]
Występuje problem: 
 - [X] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

Czy po załadowaniu faktury przez API system Allegro nie powinien wysłać powiadomienia e-mail? Jako przykład podam zamówienie w Sandbox (ale mam takich więcej):
de281ac0-cb82-11ec-a331-15659875265c

Załadowałem do niego dokument, ale nie otrzymuję powiadomienia mailowego. Wszystkie inne powiadomienia przychodzą.

**Comment by MartaNowaczyk** [comment]
Jeśli kupujący nie zaznaczył podczas składania zamówienia "Chcę otrzymać fakturę", to wtedy nie wysyłamy takiego powiadomienia.
