### ISSUE TITLE
Zarządzanie ceną z poziomu API

### ISSUE THREAD

**Issue by IAkixxI** [allegro/allegro-api#5655]
Chcielibyśmy zarządzać ceną z poziomu API z wykorzystaniem "Przeglądu cen", informacje podawane w panelu są niewystarczające dla optymalnego zarządzania ceną. Dążymy do automatyzacji procesu sprzedażowego, dostosowanie polityki cenowej, lecz bez porównania oferty konkurencji z naszymi warunkami zakupowymi jest niemożliwe. Czy jesteśmy w stanie pobrać dane z "przeglądu cen" do naszego programu dla wyliczenia marży?

**Comment by Lukasz-Zurek** [comment]
Nie udostępniamy w naszym API wspomnianej funkcjonalności. Ewentualne pytania dotyczące "Przeglądu cen" kieruj proszę za pośrednictwem naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by IAkixxI** [comment]
Chodzi mi konkretnie o funkcję najniższej ceny, która widnieje w Allegro i Baselinker, chcemy przekazać ją dalej w celu porównania ceny z naszymi rabatami. Czy jest to możliwe, czy tylko autoryzowane aplikacje mają taką możliwość?

**Comment by Lukasz-Zurek** [comment]
@IAkixxI Niestety nie ma obecnie takiej możliwości.
