### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by theazgra** [allegro/allegro-api#5656]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**

While I am trying to check the offer status, after the product offer was accepted, I am getting these responses:
```
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52377)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52378)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52379)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52380)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52381)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52383)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52382)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52385)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52384)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52386)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52390)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52387)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52388)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52391)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52392)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52394)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52389)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52393)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52398)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52397)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52400)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52402)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52396)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52399)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52401)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52395)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52403)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:52115)
```

**Comment by MartaNowaczyk** [comment]
It is not a response from our API. This looks like a connection problem, possibly a problem with your firewall - it could be blocking the connection.

**Comment by theazgra** [comment]
@MartaNowaczyk I don't think so. I had no problem beforehand (for like 8 months). I am on no special, or bussiness network. 
The error says that the **target machine** refused the connection.

I am trying to check these product offers
```
https://api.allegro.pl.allegrosandbox.pl:54940/sale/product-offers/7688351801/operations/c7d537ee-5799-4f10-b28a-f338b7c2b532
https://api.allegro.pl.allegrosandbox.pl:54941/sale/product-offers/7688351803/operations/2046f109-5947-4668-869f-d66b6dcdc5c3
https://api.allegro.pl.allegrosandbox.pl:54942/sale/product-offers/7688351804/operations/b404e4bb-9b38-4517-a015-74c34f3655d9
https://api.allegro.pl.allegrosandbox.pl:54943/sale/product-offers/7688351809/operations/fb8a04e5-cc63-4db3-ab35-5c6cb728df22
```

getting these responses
```
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:54940)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:54941)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:54942)
No connection could be made because the target machine actively refused it. (api.allegro.pl.allegrosandbox.pl:54943)
```

**Comment by MartaNowaczyk** [comment]
You are using incorrect addresses.
For example, instead of:
https://api.allegro.pl.allegrosandbox.pl:54940/sale/product-offers/7688351801/operations/c7d537ee-5799-4f10-b28a-f338b7c2b532
you should use:
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7688351801/operations/c7d537ee-5799-4f10-b28a-f338b7c2b532

**Comment by theazgra** [comment]
Ok I get it, the port shouldn't be there.

But for the info your API sent the *incorrect* addresses, I just read them from the `Location` header of the `https://api.{environment}/sale/product-offers` response

**Comment by MartaNowaczyk** [comment]
Thanks, I'll check it out.

**Comment by theazgra** [comment]
Just for info. 
`GET https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7688351801/operations/c7d537ee-5799-4f10-b28a-f338b7c2b532` 
also returns resource URL with port.
e.g.
`https://api.allegro.pl.allegrosandbox.pl:53159/sale/product-offers/7688351801`

**Comment by mikllero** [comment]
Have same issue, waiting for reply or fix.

**Comment by MaciejFrackowiak** [comment]
@mikllero Please, give us a trace-id of your request - it will be helpful for us to verify an issue.

**Comment by mikllero** [comment]
I am not sure what trace-id, but this is example error:
{"No connection could be made because the target machine actively refused it. [::ffff:5.134.213.11]:54615 (api.allegro.pl:54615)"}

And example urls from 'Location' which I am trying to execute:
https://api.allegro.pl:54615/sale/product-offers/10652964180/operations/4a977ffa-c001-4c09-88fb-969953fdc750
https://api.allegro.pl/sale/product-offers/10652964180/operations/e8ab2b78-58a1-4f60-8cb3-ee1c068f99a0
https://api.allegro.pl/sale/product-offers/10652965318/operations/45ddcc1a-0dc9-43a3-ba00-f2a954ed8180
https://api.allegro.pl/sale/product-offers/10636445999/operations/9476d70e-058d-46e7-b1ac-fbd64165ff4f
https://api.allegro.pl/sale/product-offers/10582457095/operations/b50330b1-8d82-475f-ad17-8e354b7b740c
https://api.allegro.pl/sale/product-offers/11539340165/operations/6474ea37-bd7e-4e57-8caf-9a427b022282
https://api.allegro.pl/sale/product-offers/10665244366/operations/6f95eafd-2f67-44a3-88cb-df572cb21475
https://api.allegro.pl/sale/product-offers/10212822788/operations/0a274be8-d8a2-43a2-95ee-5cf4204c002a
https://api.allegro.pl/sale/product-offers/10801860345/operations/f6f54941-7daa-4f1d-ba9d-862d466c1be1
https://api.allegro.pl/sale/product-offers/10821192480/operations/ec3151d2-7894-4733-891a-7ca0684c162b
https://api.allegro.pl/sale/product-offers/10653013388/operations/95cebc1e-c39a-46d0-84af-75019210692a
https://api.allegro.pl/sale/product-offers/12123837283/operations/be043fd7-4134-4c2e-8d92-164a661112fa

I tried urls with port and without port, but result is the same.

I am able to get response from 'Location' url,, but only if the response code is 422 Unprocessable Entity.

**Comment by MaciejFrackowiak** [comment]
@mikllero I asked the development team to investigate an issue. As soon as I receive a response, I will reply in a thread.

**Comment by MaciejFrackowiak** [comment]
@mikllero @theazgra We have implemented a fix which has eliminated the problem you reported.

**Comment by mikllero** [comment]
@MaciejFrackowiak now I have another issue with example urls:

https://api.allegro.pl/sale/product-offers/12131900065/operations/26d40317-f93d-4a13-ae34-0014290b78c5
https://api.allegro.pl/sale/product-offers/11980711106/operations/f595102c-08dc-437c-8a26-28d37f020b09
https://api.allegro.pl/sale/product-offers/11177636919/operations/3b9e20e6-4dc4-4270-9ddd-a9ad49b5e581
https://api.allegro.pl/sale/product-offers/11539340165/operations/c881a39b-56d5-4919-8476-e995730cf3e4
https://api.allegro.pl/sale/product-offers/10582457095/operations/e4613594-45c9-45b1-b3ad-09afe317743b

Response is:
`{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}`

But it is executed just like the others, is this error correct?

**Comment by MaciejFrackowiak** [comment]
@mikllero We are investigating it. I will be back with an answer.

**Comment by MaciejFrackowiak** [comment]
@mikllero It looks like your access token had expired, and then you tried to use it again instead refresh it - as a result, we have not received your request. Please, check your authentication mechanism.

**Comment by mikllero** [comment]
@MaciejFrackowiak the error suggest it but as I explicit said, those requests are executed like all the others with same token and only with those urls I receive this auth errors. @theazgra gave like to my comment, so probably he is troubling with same issue. I am not having any problems with orders for example, which work correct with same token.

**Comment by theazgra** [comment]
I agree with @mikllero 
I think that I have received the same error while testing in the sandbox environment. And it is VERY unlikely, that I would use expired token, since I am always refreshing my tokens, if they are to expire in less than 2 hours.

**Comment by MaciejFrackowiak** [comment]
@mikllero @theazgra Thanks for the details. I will discuss it with the development team.

**Comment by MaciejFrackowiak** [comment]
@mikllero @theazgra From our perspective it looks that the request does not have an authorization header or the header is empty.

**Comment by AureliuszBrussy** [comment]
@mikllero we are investigating it further. I will be back with an answer.

**Comment by MaciejFrackowiak** [comment]
@mikllero Can I ask you to give us an example of the trace-id of the request which finished with error 401?

**Comment by mikllero** [comment]
@MaciejFrackowiak 
af4240238cf73fb9
dff9d0890af970ea
ba7fb47dbabac9b3

**Comment by MaciejFrackowiak** [comment]
@mikllero Thanks for the examples. In our logs, we found that your requests came to us without ClientId and UserId which means that you have lost authorization. It looks like your HTTP client lost authorization when executing 303 - most HTTP clients (by default) strip out authorization headers when following a redirect. You should call the GET request with the location address manually. Also, check your application settings and how does it handle 303 See other response.

**Comment by mikllero** [comment]
@MaciejFrackowiak 
For example operation:
https://api.allegro.pl/sale/product-offers/11073705923/operations/cb0d49c4-e81f-4f00-bed7-8123cb88caf4

I am getting:
Location url from 303 RedirectMethod: https://api.allegro.pl/sale/product-offers/11073705923
...

This is not any secret url to get the operation result.
I want to know status of offer update (I am changing publication status), so this redirect gaves me nothig.
This url is used to get all information about offers product - I can construct it whenever I want without this magic above.

Maybe this redirect is the result of an error?
I repeat that I can get correct 422 response, so why for some cases I will need to handle redirect (for general offer get url)?
Please investigate it again and consider that, this redirect is probably error.

**Comment by MaciejFrackowiak** [comment]
This mechanism works as we described in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-publication-in-asynchronous-api). If we return 303, you should call manually GET /sale/product-offers/{offerId} to see offer details (not using automatic redirect from your application). A similar issue appeared in the thread https://github.com/allegro/allegro-api/issues/5409.

**Comment by mikllero** [comment]
@MaciejFrackowiak very unfriendly and unintuitive mechanism, not described on api documentation:
https://developer.allegro.pl/documentation/#operation/editProductOffers
Anyway, thanks for help.
