### ISSUE TITLE
Sandbox - Parcel Management - Communication error with carrier's API occurred

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#5661]
Dzień dobry.

Jestem w trakcie przygotowywania integracji z usługą AllegroOne jednakże napotykam problem w środowisku testowym.

Po utworzeniu paczki:

`PUT /parcel-management/parcel-create-commands/{uuidv4}` przykładowy trace-id: `132d199bfb84c2f`

Otrzymuję normalnie kod 201 Created, ale kiedy chcę zweryfikować zadanie utworzenia przesyłki w zasobie:
`GET /parcel-management/parcel-create-commands/{użyty wcześniej uuid}` przykładowy trace-id: `168439b170ae90f0`

w raporcie tworzenia przesyłki otrzymuję komunikat: Communication error with carrier's API occurred. Dodam, że wcześniej proces działał, ale generowałem paczki z błędami, występowanie błędu pojawiło się nagle nie ustąpiło od jakiegoś czasu przez co nie mogę kontynuować prac nad integracją.

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
W tym konkretnym przypadku błąd powoduje to, że nie przekazałeś odpowiedniej wartości w polu `receiver.phone`.

**Comment by arkwlcz** [comment]
Dziękuję za odpowiedź.

Tym razem, po podaniu odpowiedniego numeru telefonu w requeście `trace-id: 440fc8a66681f31e` otrzymuję w odpytaniu o status zadania `trace-id: 861cf1999c06e1db` komunikat: _Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem_.

**Comment by AureliuszBrussy** [comment]
@arkwlcz tym razem nie wypełniłeś niektórych pól w obiekcie `receiver.address`.

**Comment by arkwlcz** [comment]
Dziękuję, działa. Zmiana podejścia do podawania danych od absolutnego minimum na podanie wszystkiego co się tylko da, okazała się skuteczna.

Ze swojej strony mogę zaproponować oznaczenie w dokumentacji wszystkich pól wymaganych jako "required" ewentualnie uwzględnienie w mechanizmie, że jeżeli korzystamy z systemu WzA i podajemy email transakcyjny z Allegro to obiekty wartości typu `pointId`, czy `receiver` mogą być w pewnym sensie pomijalne gdyż te informacje posiadacie już Państwo na swoich serwerach.

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
@arkwlcz dziękuję za sugestie. Pola, które ostatecznie są wymagane zależą od konkretnego przewoźnika. Zakres bywa różny, dlatego nie oznaczamy części pól jako required - nie zawsze są to pola wymagane.
