### ISSUE TITLE
0 ofert po otrzymaniu odpowiedzi od api

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5662]
Hey!
Mamy oferty na Allegro i chcemy wykorzystać API do przetwarzania i dodawania tych ofert. 
Jednak przy korzystaniu z API usługa pokazuje, że nie mamy ofert
https://api.allegro.pl/sale/offers
<img width="721" alt="Screenshot_1" src="https://user-images.githubusercontent.com/95347292/167354613-35dc4f09-e3b8-4453-bfd2-ffb982bb4edb.png">
<img width="276" alt="Screenshot_2" src="https://user-images.githubusercontent.com/95347292/167354616-71582f45-affb-43bb-b96e-a6efdb466f22.png">
<img width="947" alt="Screenshot_3" src="https://user-images.githubusercontent.com/95347292/167354916-24ce15b0-9bf6-44e2-b9b3-4396d4d2f814.png">

Widzę to w ten sposób.
Pobieram aktualne produkty i kategorie. Co jest w nich zawarte, a co nie. Porozmawiac z kolegami, co należy zmienić. Omówic, czego potrzebujemy / możemy dodać.
Dowiedziec się, jak dodawać produkty za pośrednictwem interfejsu API. Mam już jedno pytanie dotyczące obrazów. Nie jest do końca jasne, gdzie są wylewane po dodaniu przez api i jak są następnie dołączane do produktu. Ale co ważniejsze, najpierw zdobądź listę aktualnych produktów.

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem działanie zasobu [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i w Twoim przypadku prawidłowo zwraca 1917 aktywnych ofert.
W swoim requeście skorzystałeś z filtra "name" z wartością "fototapety" - żadna Twoja oferta nie posiada takiego słowa w nazwie, stąd wynik wyszukiwania = 0.

**Comment by sergeidebug** [comment]
> Sprawdziłem działanie zasobu [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i w Twoim przypadku prawidłowo zwraca 1917 aktywnych ofert. W swoim requeście skorzystałeś z filtra "name" z wartością "fototapety" - żadna Twoja oferta nie posiada takiego słowa w nazwie, stąd wynik wyszukiwania = 0.

Tak, dokładnie!
Przepraszam!
Parametr pozostal z poprzedniego żądania.
Czy może Pan mi powiedzieć, co zrobić z obrazami?
Czy trzeba je dodać, a następnie przypisać?
Czy może być dostarczony z produktem?

Jeśli zostaną dodane osobno, nie jest dla mnie jasne, gdzie są one przechowywane i jak wyświetlić listę dodanych zdjęć?

**Comment by MaciejFrackowiak** [comment]
Istnieje kilka podejść do kwestii zdjęć przypisanych do ofert:
1) korzystając z zasobów /sale/product-offers automatycznie dołączymy do oferty zdjęcia, które mamy przypisane do produktu w naszej bazie. Możesz także dodać swoje własne zdjęcia, wówczas request musisz wzbogacić o sekcję "images" - szczegółowo opisaliśmy to w [poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty);
2) jeżeli korzystasz z zasobów /sale/offers to najpierw musisz wysłać zdjęcia na nasz serwer korzystając z [POST /sale/images](https://developer.allegro.pl/documentation/#operation/uploadOfferImageUsingPOST), a następnie wykorzystując otrzymane adresy URL dodać je do struktury opisu oferty - [tu](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#opis-oferty) informacja z naszego poradnika.
