### ISSUE TITLE
WzA - zamówienie podjazdu - błąd 404

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5664]
PUT na zasobie https://api.allegro.pl/parcel-management/parcel-pickup-request-commands/96afcd64-6458-4a1e-87b8-970ff16cfbd1

{\"parcelIds\": [\"78733080\"],\"pickupDate\":{\"date\": \"2022-05-09\",\"minTime\": \"12:35\",\"maxTime\": \"18:00\"}}

The remote server returned an error: (404) Not Found.: {\"errors\":[{\"code\":\"ERROR\",\"message\":\"Command doesn't exist\",\"details\":null,\"path\":\"/parcel-management/parcel-pickup-request-commands/{commandId}\",\"userMessage\":\"Komenda nie istnieje\"}]}

**Comment by AureliuszBrussy** [comment]
@ciaglok2 w logach widzę, że wykonujesz request metodą GET, a nie PUT.
