### ISSUE TITLE
Aktualizacja opisu nowej aukcji "Internal Server Error" [REST API]

### ISSUE THREAD

**Issue by mapsi-fixi** [allegro/allegro-api#567]
Na resource "PUT /sale/offers/{offerId}" występuje Internal Server Error.
Próbuję, zaaktualizować ofertę. Postępuję zgodnie z dokumentacją:
1. Pobieram dane ofertty GET /sale/offers/{offerId}
2. Wysyłam taką samą strukturę ze zmienionymi parametrami PUT /sale/offers/{offerId}

Otrzymuję w odpowiedzi błąd cytowany wyżej. Próbowałem również, aby sprawdzić czy dane są poprawne, odesłać nie zmodyfikowany responose z GET'a, również Internal Server Error.

**Comment by KrzysztofLukanowski** [comment]
Podeślij proszę dokładny request jaki wysyłasz, oczywiście wymoderuj wrażliwe dane.

**Comment by mapsi-fixi** [comment]
url: https://api.allegro.pl.allegrosandbox.pl/sale/offers/6205628816
metoda: PUT
nagłówki:
                        'authorization: Bearer ' 
                        'Api-Key: '
                        'content-type: application/vnd.allegro.beta.v1+json',
                        'accept: application/vnd.allegro.beta.v1+json',
                        'Accept-Language: pl-PL'

wysyłana data:
Array
(
    [id] => 6205628816
    [name] => POLSKIE BALLADY ROCKOWE VOL 1-3 CD
    [category] => Array
        (
            [id] => 181
        )

    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [1] => stdClass Object
                (
                    [id] => 124
                    [valuesIds] => Array
                        (
                            [0] => 124_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

            [2] => stdClass Object
                (
                    [id] => 11324
                    [valuesIds] => Array
                        (
                            [0] => 11324_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                )

        )

    [ean] => 
    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => 
testowanie aktualizacji 


                                        )

                                )

                        )

                )

        )

    [compatibilityList] => 
    [images] => Array
        (
            [0] => stdClass Object
                (
                    [url] => https://6.allegroimg.allegrosandbox.pl/original/112cd3/ef7343fa4e15a5dc481962f1bd76
                )

            [1] => stdClass Object
                (
                    [url] => https://1.allegroimg.allegrosandbox.pl/original/11ef1d/adf6775d4e8e969aeb8fd82b56a1
                )

            [2] => stdClass Object
                (
                    [url] => https://3.allegroimg.allegrosandbox.pl/original/113ebe/17f263af410e99d7b713bcc435b3
                )

            [3] => stdClass Object
                (
                    [url] => https://1.allegroimg.allegrosandbox.pl/original/117ffc/52cfc36d4d9ba24d5bc150236981
                )

            [4] => stdClass Object
                (
                    [url] => https://4.allegroimg.allegrosandbox.pl/original/1162fe/4f17fcb14ad2bc5dce4bca9c3334
                )

        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 50000
                    [currency] => PLN
                )

            [startingPrice] => 
            [minimalPrice] => 
        )

    [stock] => Array
        (
            [available] => 10
            [unit] => UNIT
        )

    [publication] => stdClass Object
        (
            [duration] => 
            [status] => ACTIVE
            [startingAt] => 2018-09-12T09:36:00Z
            [endingAt] => 
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => 2103cca7-cd31-4f9b-8370-c8154fa37cfe
                )

            [handlingTime] => PT0S
            [additionalInfo] => 
            [shipmentDate] => 
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => 8d65a908-a177-4f4c-8de7-af158b4fb6cf
                )

            [returnPolicy] => Array
                (
                    [id] => 75a1d8b1-fb3a-45b3-a505-461039f5f240
                )

            [warranty] => Array
                (
                    [id] => 361bfa56-cd48-4770-ae34-bac1294a803d
                )

        )

    [additionalServices] => 
    [sizeTable] => 
    [promotion] => Array
        (
            [emphasized] => 
            [bold] => 
            [highlight] => 
            [departmentPage] => 
            [emphasizedHighlightBoldPackage] => 
        )

    [location] => Array
        (
            [countryCode] => PL
            [province] => /******/
            [city] => /****/
            [postCode] => /****/
        )

    [external] => 
    [contact] => 
    [validation] => stdClass Object
        (
            [errors] => Array
                (
                )

            [validatedAt] => 2018-09-12T09:31:42.493Z
        )

    [createdAt] => 2018-09-12T09:26:44Z
    [updatedAt] => 2018-09-12T09:36:59.979Z
)

**Comment by KrzysztofLukanowski** [comment]
Czy ten problem nadal występuje? Podeślij proszę curl zapytania.
