### ISSUE TITLE
Uzupełnij parametry obowiązkowe: Liczba sztuk w ofercie. - probem z aktualizacją ilości. 

### ISSUE THREAD

**Issue by Raafal78** [allegro/allegro-api#5670]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 

:beetle: **Opis / Description**

993d2f44-6f4f-48a1-9cdf-c9c0300849f6

Proszę o weryfikację dlaczego nie mogę zaktualizować ilości dla aukcji: 11870597087 ( i wielu innych jest ten sam problem) 

Wysyłany request: 
"{"modification":{"changeType":"FIXED","value":19},"offerCriteria":[{"offers":[{"id":11870597087}],"type":"CONTAINS_OFFERS"}]}"

Track-Id: 993d2f44-6f4f-48a1-9cdf-c9c0300849f6

Dostaję komunikat błędu:
"Uzupełnij parametry obowiązkowe: Liczba sztuk w ofercie."

**Comment by MaciejFrackowiak** [comment]
Wskazana oferta nr 11870597087 nie posiada określonego obowiązkowego parametru „Liczba sztuk w ofercie” - id parametru=248489. Aby dokonać zmiany ilości dostępnych ogólnie sztuk konieczne jest określenie ww. parametru.

**Comment by Raafal78** [comment]
Witam, dziękuję za sprawdzenie ale nie rozumiem , przecież ilość sztuk modyfikuje się tą cześcią json-a 
{"changeType":"FIXED","value":19} używając ten metody: /sale/offer-quantity-change-commands/

**Comment by hahyes** [comment]
> Witam, dziękuję za sprawdzenie ale nie rozumiem , przecież ilość sztuk modyfikuje się tą cześcią json-a {"changeType":"FIXED","value":19} używając ten metody: /sale/offer-quantity-change-commands/

Chodzi o to, że w aukcji masz w informacjach dodatkowych pole "Liczba sztuk w ofercie", które jest teraz obowiązkowe i musisz je uzupełnić.

**Comment by MaciejFrackowiak** [comment]
@Raafal78 Dokładnie tak jak wspomniał @hahyes oraz ja w swojej odpowiedzi - dla kategorii Krzesła istnieje parametr obowiązkowy „Liczba sztuk w ofercie”, który musisz uzupełnić by móc zmienić dostępną liczbę sztuk w ofercie.
