### ISSUE TITLE
400 Nieobsługiwany format żądania

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5671]
Korzystam z metody
https://api.{environment}/sale/offers/{offerId}
Wcześniej stworzyłem szkic oferty za pomocą API:
offerId = '12142626732'

headers = {'charset': 'utf-8',
           'Accept-Language': 'pl-PL',
           'Content-Type': 'application/json',
           'Api-Key': api_key,
           'Accept': 'application/vnd.allegro.public.v1+json',
           'Authorization': "Bearer {}".format(access_token)}
offerId = '12142626732'
DEFAULT_API_URL = 'https://api.allegro.pl/sale/offers/{}'.format(offerId)
with requests.Session() as session:
    session.headers.update(headers)
    headers_1 = {'charset': 'utf-8',
                 'Accept-Language': 'pl-PL',
                 'Content-Type': 'application/vnd.allegro.public.v1+json',
                 'Api-Key': api_key,
                 'Accept': 'application/vnd.allegro.public.v1+json',
                 'Authorization': "Bearer {}".format(access_token)}
    response = session.put(
        DEFAULT_API_URL,
        headers=headers_1
    )
    print(response.status_code)
    print(response.json())

{'errors': [{'code': 'ValidationError.HttpMessageNotReadableException', 'message': 'Message not readable', 'details': None, 'path': '/sale/offers/12142626732', 'userMessage': 'Nieobsługiwany format żądania'}]}
<img width="768" alt="Screenshot_4" src="https://user-images.githubusercontent.com/95347292/167789486-915b71c8-5132-4e0b-b346-1459396657b1.png">

Rozumiem, że coś jest nie tak z PATH, ale nie rozumiem, co z tym zrobić, ponieważ nic więcej nie jest napisane w dokumentacji api

**Comment by hahyes** [comment]
>'Api-Key': api_key,

Allegro nie używa takiego headera.

**Comment by sergeidebug** [comment]
> > 'Api-Key': api_key,
> 
> Allegro nie używa takiego headera.

api_key - to jest zmienna, która przechowuje mój klucz API. Myślałem, że to jasne, odkąd otrzymałem odpowiedź z serwera

**Comment by MaciejFrackowiak** [comment]
Jeżeli chcesz usunąć szkic to skorzystaj z metody DELETE - w Twoim przykładzie korzystasz z PUT. Wartość ClientID zakodowana jest w tokenie, nie musisz jej podawać osobno.

**Comment by sergeidebug** [comment]
> Jeżeli chcesz usunąć szkic to skorzystaj z metody DELETE - w Twoim przykładzie korzystasz z PUT. Wartość ClientID zakodowana jest w tokenie, nie musisz jej podawać osobno.

Dziękuję!
Otrzymano kod odpowiedzi 204. Sukces.
Naprawdę zapomniałem zmienić metodę, przepraszam.

Odnośnie ClientID to znaczy, że mogę nie przepisać tej linii?!
Próbowałem usunąć, a także usunąłem headers_1, został zdjęty z poprzedniej inicjalizacji. Również 204 odpowiedzi.
