### ISSUE TITLE
Woocommerce Allegro

### ISSUE THREAD

**Issue by exeboosu** [allegro/allegro-api#5672]
Witam, 
Tworzymy dla klienta sklep oparty o woocommerce z integracją od Grojan Team (WooCommerce Allegro PRO). Niestety mamy problem z połączeniem cały czas otrzymujemy komunikat. Co może być nie tak?

![image](https://user-images.githubusercontent.com/68944418/167792443-90fb4865-8886-4404-bf7d-bf23d9b13e5f.png)

**Comment by MaciejFrackowiak** [comment]
Adres przekierowania, który podajesz w aplikacji nie jest zgodny z tym, który zarejestrowałeś na stronie [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Adres musi być podany w formacie 1:1, w innym przypadku otrzymasz błąd jak na załączonym zrzucie.
