### ISSUE TITLE
Delete active offer

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5675]
chciałem usunąć aktywną ofertę, jednak ta metoda wydaje się działać tylko w przypadku szkic

headers = {'charset': 'utf-8',
           'Accept-Language': 'pl-PL',
           'Content-Type': 'application/json',
           'Accept': 'application/vnd.allegro.public.v1+json',
           'Authorization': "Bearer {}".format(access_token)}
offerId = '12154129601'
DEFAULT_API_URL = 'https://api.allegro.pl/sale/offers/{}'.format(offerId)
# https://api.{environment}/sale/offers/{offerId}
with requests.Session() as session:
    session.headers.update(headers)
    response = session.delete(
        DEFAULT_API_URL
    )
    print(response.status_code)

Jak mogę usunąć aktywną ofertę?

**Comment by sergeidebug** [comment]
Ok dzięki!
A jeśli skończę aktywną ofertę, czy mogę ją przywrócić do życia?

**Comment by Lukasz-Zurek** [comment]
Oczywiście, możesz [wznowić](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-wznowic-oferte) zakończoną ofertę.
