### ISSUE TITLE
wiele szkiców ofert

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5676]
Za pomoca 'https://api.allegro.pl/sale/offers'
Mogę złożyć szkic ofertę, ale jak mogę stworzyć kilka ofert na raz, czy mogę to zrobić tylko jedną na raz?

**Comment by Lukasz-Zurek** [comment]
W naszym API nie ma możliwości utworzenia wielu ofert/szkiców na raz, czyli musisz tworzyć jedną po drugiej, w odrębnym toku. Przy czym jak już uzupełnisz oferty o wszystkie wymagane dane, możesz je aktywować zbiorczo za pomocą [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT).

Więcej informacji na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-wznowic-oferte).

**Comment by sergeidebug** [comment]
jasne, dzięki!
