### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5677]
jak dokładnie korzystać z walidacji?
Czy mogę przesłać wiele szkiców. 
'https://api.allegro.pl/sale/offers'

**Jak mogę je zweryfikować?!**

A potem złóżic aktywne oferty.
https://api.{environment}/sale/offer-publication-commands/{commandId}

Konieczna jest weryfikacja przed aktywacją przez api.

**Comment by Lukasz-Zurek** [comment]
Jak już wspomniałem we wcześniejszym wątku - nie ma możliwości zbiorczego utworzenia szkiców.

Cały proces tworzenia oferty oraz jej aktywację w Allegro.pl - opisaliśmy w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK), począwszy od [tworzenia draftu](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#draft-oferty) (gdzie w polu "validation" zwrócimy błędy), a kończywszy na [aktywacji oferty](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#publikacja-oferty) oraz [informacji o publikacji](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#informacje-o-publikacji).

Pamiętaj, że w drugiej połowie 2022 roku planujemy, aby każda nowo wystawiona oferta była połączona z Katalogiem produktów. W tej sytuacji zachęcam do korzystania z zasobu [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) do tworzenia i wystawiania ofert powiązanych z produktem:

- który istnieje w naszej bazie,
- którego nie ma w naszej bazie.

Proces ten opisaliśmy go [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA).

**Comment by sergeidebug** [comment]
jasne,  w polu "validation" nie dostałem żadnych błędów podczas testowania. Ok, rozumiem.

Powiedz proszę:
czy ta metoda 
[POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers)
pozwala na natychmiastowe stworzenie oferty bez szkicu?
To znaczy, że tak powiem, uproszczenie procesu tworzenia aktywnej oferty, czy jest to dodatek, który również trzeba zastosować w związku ze zmianą polityki w najbliższym czasie?

**Comment by Lukasz-Zurek** [comment]
@sergeidebug Jest to uproszczony proces natychmiastowego utworzenia aktywnej oferty (połączonej już z produktem). Ta funkcjonalność pozwoli Tobie wystawić ofertę korzystając z jednego requestu.

**Comment by sergeidebug** [comment]
to jest super, dzieki!

**Comment by sergeidebug** [comment]
jest pytanie. Aby dodać szkic oferty, podobnie jak istniejące oferte, zaleca się najpierw pobrać aktywną ofertę, a następnie usunąć niektóre pola i złożyć request.
Więc zrobiłem tak z
https://api.{environment}/sale/offers

gdzie mogę zdobyć pola do testów:
[POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers)

**Comment by Lukasz-Zurek** [comment]
Wystawiając ofertę poprzez [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) w odpowiedzi automatycznie uzupełnimy wszelkie dane w ofercie, w tym m.in. kategorię, parametry, zdjęcia, opis, itd.

Nie musisz przekazywać pozostałych informacji wymaganych do wystawienia oferty (np. cennik dostawy, czy warunki zwrotów) - uzupełnimy je wtedy wartościami domyślnymi - jeśli zdefiniujesz je w ustawieniach konta pod nazwą "default".

Zapoznaj się proszę z [poradnikiem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#lokalizacja-i-cenniki) oraz z [dokumentacją](https://developer.allegro.pl/documentation/#operation/createProductOffers). Tam są wszystkie informacje na temat zasobu.
