### ISSUE TITLE
Auth device - pytanie

### ISSUE THREAD

**Issue by konradkur** [allegro/allegro-api#5678]
Witam,

zrobiłem auth device, link który mi zwróciło dodatkowo autoryzowałem

`
response = requests.post(
    f'{conf_settings.ALLEGROPL_URL_PROD}/auth/oauth/device',

    headers={'Content-Type': 'application/x-www-form-urlencoded'},
    auth=(conf_settings.ALLEGROPL_CLIENT_ID, conf_settings.ALLEGROPL_CLIENT_SECRET),

    params={
        'client_id': conf_settings.ALLEGROPL_CLIENT_ID
    }
)`

następnie chce wykonać wg. dokumentacji
"4b. Równocześnie twoja aplikacja powinna zacząć odpytywać zasób:"
`curl -X POST \
'https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}' \
  -H 'Authorization: Basic base64(clientId:secret)`
Nie rozumiem tutaj wartości grant_type.

Finalnie chce pobrać dane z https://api.allegro.pl/order/customer-returns
Mając auth'a auth/oauth/authorize śmigało, ale chce zmienić na auth device.

Dziękuje za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Jest to encodowana wartość `urn:ietf:params:oauth:grant-type:device_code`, która określa rodzaj dostępu potrzebny, aby uzyskać token w przypadku autoryzacji `device code` . Szczegółowe informacje na ten temat znajdziesz [w dokumentacji OAuth 2.0.](https://datatracker.ietf.org/doc/html/rfc8628#section-3.4) 
Jaki konkretnie komunikat błędu otrzymujesz? Najlepiej, jeśli wyślesz nam przykładowy request wraz z odpowiedzią przez nasz formularz kontaktowy. Dopisz w tym przypadku, że zgłoszenie dotyczy wątku #5678 na GitHubie. W międzyczasie możesz nam przesłać także trace-id, jeśli nim dysponujesz.

**Comment by konradkur** [comment]
Działa, kod dla potomnych

`
        response = requests.post(
            f'{conf_settings.ALLEGROPL_URL_PROD}/auth/oauth/device',

            headers={'Content-Type': 'application/x-www-form-urlencoded'},
            auth=(conf_settings.ALLEGROPL_CLIENT_ID, conf_settings.ALLEGROPL_CLIENT_SECRET),

            params={
                'client_id': conf_settings.ALLEGROPL_CLIENT_ID
            }
        )
        # w response jest link, autoryzuj go, nastepnie wykonaj request nizej
        response = requests.post(
            f'{conf_settings.ALLEGROPL_URL_PROD}/auth/oauth/token',
            auth=requests.auth.HTTPBasicAuth(conf_settings.ALLEGROPL_CLIENT_ID, conf_settings.ALLEGROPL_CLIENT_SECRET),

            data={
                'grant_type': 'urn:ietf:params:oauth:grant-type:device_code',
                'device_code': response.json()['device_code'],
                'client_id': conf_settings.ALLEGROPL_CLIENT_ID
            }
        )
`

Pytanie; rozumiem, ze jak zautoryzuje user code; to moj device code w czasie staly bedzie ?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, że podzieliłeś się swoim rozwiązaniem.

> Pytanie; rozumiem, ze jak zautoryzuje user code; to moj device code w czasie staly bedzie ?

Niestety nie, w polu expires_in wskazujemy liczbę sekund, przez którą ważne są oba kody:

```
{
        user_code: "cbt3zdu4g",                             -- kod użytkownika - zalecamy
                                                            przedstawić te dane użytkownikowi
                                                            w postaci XXX XXX XXX. Taka forma
                                                            będzie dla niego czytelniejsza
                                                            przy przepisywaniu.
        device_code: "645629715",                           -- kod aplikacji - niezbędny
                                                            do uzyskania tokenu dostępowego
        expires_in: "3600"                                  -- liczba sekund, przez które ważne są
                                                            oba kody
        interval: “5”,                                      -- wymagany odstęp (w sekundach)
                                                            pomiędzy kolejnymi zapytaniami o
                                                            status autoryzacji. Jeśli będziesz
                                                            odpytywać częściej otrzymasz
                                                            odpowiedź o statusie HTTP 400 z
                                                            kodem: "slow_down".
        verification_uri: “https://allegro.pl/skojarz-aplikacje”,   
                                                            -- adres do weryfikacji użytkownika
        verification_uri_complete: “https://allegro.pl/skojarz-aplikacje?code=cbt3zdu4g”
                                                            -- adres do weryfikacji dla użytkownika 
                                                            z wypełnionym kodem użytkownika
}
```

**Comment by konradkur** [comment]
Okej, to dalej robie requesta do auth/oauth/token dostaje access token, on też ma termin ważności?

Potrzebuje rozwiązanie, że user raz się autoryzuje ( swoje konto z moją aplikacja allegro ) i potem może strzelać sobie po dane aplikacja moja. Imho user nie będzie co N czasu w dobie wykonywał te autoryzacji.

**Comment by PrzemyslawLukanowski** [comment]
Tak, token na 12h ważności, ale żeby nie zmuszać usera to autoryzowania aplikacji raz na 12 godzin, możesz zaimplementować w aplikacji funkcję obsługi refresh tokenów. Więcej na ten temat przeczytasz [tutaj](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena). Dzięki temu interakcja użytkownika będzie miała miejsce tylko raz, na początku, kiedy wyraża zgodę na działanie aplikacji w jego imieniu.
