### ISSUE TITLE
kody parametrów

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5679]
po dodaniu towara 
https://api.{environment}/sale/offers
dostałem odpowiedź.
czy wszystko dobrze rozumiem?

'product': {'id': 'ec7326c8-cc3b-4c81-ae94-5f92189db5e7'}
'ec7326c8-cc3b-4c81-ae94-5f92189db5e7' - fototapeta?

'parameters': [

{'id': '224017', 'valuesIds': [], 'values': ['u33481'], 'rangeValue': None}
224017 - Kod producenta
{'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None} - marka
jak wypełnić tutaj valuesIds?
{'id': '130210', 'valuesIds': ['130210_3'], 'values': [], 'rangeValue': None}
{'id': '216577', 'valuesIds': [], 'values': ['400'], 'rangeValue': None} - Szerokość
{'id': '216669', 'valuesIds': [], 'values': ['200'], 'rangeValue': None} - Wysokość
{'id': '11323', 'valuesIds': ['11323_1'], 'values': [], 'rangeValue': None}
{'id': '130192', 'valuesIds': ['130192_1', '130192_32', '130192_512', '130192_2048', '130192_4096'], 'values': [], 'rangeValue': None}
{'id': '18062', 'valuesIds': ['18062_1', '18062_16', '18062_65536', '18062_2048'], 'values': [], 'rangeValue': None}
ostatnie 3
Nie wiem, co to jest.
Czy jest gdzieś tabela, który parametr pod jakim id?

**Comment by PrzemyslawLukanowski** [comment]
`ec7326c8-cc3b-4c81-ae94-5f92189db5e7`to identyfikator produktu, z którym połączyłeś swoją ofertę. Jego szczegóły możesz zobaczyć w odpowiedzi [GET /sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProduct). Jak rozumiem, wykonałeś to za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers), dlatego w odpowiedzi automatycznie uzupełniliśmy wszelkie dane w ofercie, w tym właśnie parametry danego produktu. Tych parametrów nie możesz swobodnie edytować, ponieważ muszą one być zgodne z parametrami wskazanego produktu. Możesz ewentualnie - jeśli jesteś zdania, że dane są nieprawidłowe - zgłosić sugestię zmiany za pomocą [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). 
Co kryje się pod konkretnym ID parametru sprawdzisz przy użyciu [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) - w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#kategorie-i-parametry) znajdziesz więcej informacji na ten temat.

**Comment by sergeidebug** [comment]
Dziękuję!
Wszystko jasne!
Jedyne, na co chciałbym zwrócić uwagę, to to, że zastosowałem tę metodę
POST /sale/offers,
a nie
POST /sale/product-offers,

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, czyli parametry pobrałeś zapewne z danych produktu i przypisałeś do oferty.
