### ISSUE TITLE
Problem z publikacją ofert przez API

### ISSUE THREAD

**Issue by starzykmateusz** [allegro/allegro-api#568]
Witam, 

Od kliku dni obserwuję problem z wystawianiem aukcji poprzez metodę doNewAuctionExt.

Cały czas otrzymuję kod błędu: ERR_STANDARDIZED_DESCRIPTION_INCORRECT wraz z wiadomością: "Podany opis zawiera błędy."

Oczywiście korzystam z nowego opisu w polu FID 341

Błąd pojawia się nawet gdy opis zawiera po prostu: `"<p>test</p>"`
 Zaznaczę, że jeszcze ok 2 tygodnie temu nie było żadnych problemów z wystawianiem a po stronie mojej aplikacji nie pojawiły się żadne zmiany. 

Czy po stronie API pojawiły się jakieś zmiany?

Dziękuję za odpowiedź

**Comment by KrzysztofLukanowski** [comment]
Nie przeprowadziliśmy żadnych zmian w tym aspekcie, podeślij proszę request i response w formacie xml w celu weryfikacji.

**Comment by starzykmateusz** [comment]
Zagadka rozwiązana. 

Jakiś "krasnoludek" usunął mi zdjęcia z serwera. 

Wygląda na to, że w momencie gdy API dostaje 404 na przesyłanym zdjęciu odpowiada takim błędem. 
Swoją drogą trochę głupio :)

Temat do zamknięcia.

**Comment by MaciejPotepa** [comment]
Nie ma problemu, dzięki za informacje. :) 

Miłego dnia i pozdrawiam,
