### ISSUE TITLE
415 UNSUPPORTED_MEDIA_TYPE

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5680]
headers = {'charset': 'utf-8',
           'Accept-Language': 'pl-PL',
           'Content-Type': 'image/jpeg',
           'Accept': 'application/vnd.allegro.public.v1+json',
           'Authorization': "Bearer {}".format(access_token)}

DEFAULT_API_URL = 'https://api.allegro.pl/sale/images'
# https://upload.{environment}/sale/images
with requests.Session() as session:
    session.headers.update(headers)
    data = {"binary-data": 'Binary.jpg'}
    response = session.post(
        DEFAULT_API_URL,
        json=data
    )
    print(response.json())
    print(response.status_code)

próbowałem:
 'Content-Type': 
'image/jpeg', - 415
'application/vnd.allegro.public.v1+json', - 400

próbowałem:
data = {"url": 'Binary.jpg'} - 400
data = {"binary-data": 'Binary.jpg'} - 415

<img width="749" alt="Screenshot_1" src="https://user-images.githubusercontent.com/95347292/168232473-24ac6829-4b8b-448e-a7df-5781e8de8202.png">
dokumentacja mówi, że możesz wysyłać zarówno z adresu URL, jak i w formie binarnej.
Jednocześnie mówi, że adres URL jest wymagany

moim zadaniem jest wysłanie zdjęcia z pulpitu na Allegro, uzyskanie lokalizacji zdjęcia i podlinkowanie go do oferty. Proszę o pomoc, co muszę w tym celu zrobić w swoim kodzie?

**Comment by sergeidebug** [comment]
to co widze w poradniku 
![image](https://user-images.githubusercontent.com/95347292/168233374-c0a70984-da5f-43e8-a1b8-bbcb2c458433.png)

do którego stale radzę się zwracać i w którym, jeśli znajdę informacje, to nie ma potrzeby się zwracać tu.
Nie mówi poradnik, co zrobić z błędem 415.
Mój obraz jest binarny. Używany moduł cv2

**Comment by hahyes** [comment]
> dokumentacja mówi, że możesz wysyłać zarówno z adresu URL, jak i w formie binarnej. Jednocześnie mówi, że adres URL jest wymagany

Nie, albo wysyłasz JSONa z URL, albo wysyłasz dane binarne. Jak klikniesz na "Content type" w dokumentacji to pokażą ci się opcje dla typów `image/jpeg` i tam nie ma takiego wymagania.

Jeżeli chodzi o wysyłanie danych, to raczej jest tutaj coś nie halo, bo zgodnie z tym co podsyłasz to wysyłasz JSONa o treści: `{"binary-data": 'Binary.jpg'}`. Musisz wysłać bajty zdjęcia, nie znam twojego języka w którym piszesz więc musisz poszukać jak się to robi na własną rękę.

**Comment by Lukasz-Zurek** [comment]
Dokładnie tak jak już słusznie zauważył **hahyes** - błąd 415 otrzymujesz ponieważ przekazujesz "url", który wymagany jest wyłącznie w przypadku przesyłania zdjęcia w formie linku. 

W przypadku przesyłania zdjęcia w formacie binarnym, musisz przekazać zawartość pliku z obrazkiem w postaci binarnej. Sposób przekazania zdjęcia różni się w zależności od języków.

**Comment by sergeidebug** [comment]
> Dokładnie tak jak już słusznie zauważył **hahyes** - błąd 415 otrzymujesz ponieważ przekazujesz "url", który wymagany jest wyłącznie w przypadku przesyłania zdjęcia w formie linku.
> 
> W przypadku przesyłania zdjęcia w formacie binarnym, musisz przekazać zawartość pliku z obrazkiem w postaci binarnej. Sposób przekazania zdjęcia różni się w zależności od języków.

wypróbowałem już moduły cvr2 i base64, ale widzę tylko odpowiedź
'415 UNSUPPORTED_MEDIA_TYPE'

Niestety nie mam wystarczających informacji, aby zrozumieć, na czym polega problem. Więc proszę o radę

**Comment by sergeidebug** [comment]
headers = {'charset': 'utf-8',
           'Accept-Language': 'pl-PL',
           'Content-Type': 'image/jpeg',
           'Accept': 'application/vnd.allegro.public.v1+json',
           'Authorization': "Bearer {}".format(access_token)}

DEFAULT_API_URL = 'https://api.allegro.pl/sale/images'
with requests.Session() as session:
    session.headers.update(headers)
    with open(r'C:\Users\admin\Desktop\z52521.jpg', "rb") as imageFile:
        bw_img = pybase64.b64encode(imageFile.read())
        print(bw_img)  # bardzo duża linia, nie można jej tutaj wstawić
    response = session.post(
        DEFAULT_API_URL,
        data=bw_img)
    print(response.json())
    print(response.status_code)

{'errors': [{'code': '415 UNSUPPORTED_MEDIA_TYPE', 'message': None, 'details': None, 'path': None, 'userMessage': 'Niedozwolony typ zdjęcia.'}]}
415

Gdzie mogę dowiedzieć się więcej o wymaganiach dotyczących przesyłania plików w formie binarnej?

**Comment by sergeidebug** [comment]
> Niepotrzebnie kodujesz do base64. Musisz pominąć ten krok. Takiego pliku nie przyjmiemy.
> 
> Dodam, że w naszym poradniku nie opisujemy wymagań dotyczących przesyłania zdjęć w formie binarnej - dla innych języków programowania. Być może ktoś z użytkowników forum napotkał podobny problem w przeszłości i będzie w stanie Tobie pomóc.


Nie widzę podobnych problemów na forum.
Proszę, daj mi coś, czego mogę się złapać.
Jakie są wymagania w Twoim języku programowania?
Generalnie nie widzę różnicy w jakim języku. Liczy się to, jak powinno być sformatowane. Skinte proszę o przykład transmisji w formie binarnej. A jak dokładnie wygląda ten obraz?

**Comment by sergeidebug** [comment]
Proszę o pomoc w rozwiązaniu mojego problemu.
Muszę wysłać plik z mojego komputera przez API. Aby uzyskać lokalizację pliku w Alegro. Jak mogę to zrobić?
Jak kodować?

**Comment by Lukasz-Zurek** [comment]
@sergeidebug Spróbuj skorzystać z poniższego kodu:

```
import requests
from http.server import BaseHTTPRequestHandler, HTTPServer
import webbrowser

headers = {}
headers['charset'] = 'utf-8'
headers['Accept-Language'] = 'pl-PL'
headers['Content-Type'] = 'image/png'         
headers['Accept'] = 'application/vnd.allegro.public.v1+json'
headers['Authorization'] = "Bearer {}".format("{Twój_token}")

payload=open("twoj_plik", 'rb').read()

with requests.Session() as session:
    session.headers.update(headers)
    response = session.post(
        "https://upload.allegro.pl/sale/images",
        data=payload,
        headers=headers
    )

    print(response.text)
```

Zwróć uwagę na:

- adres (wprowadzałeś błędny https://api.allegro.pl/sale/images; prawidłowy to: https://upload.allegro.pl/sale/images),
- **content-type**, gdzie powinieneś przekazywać tylko jedną wartość,
- plik zdjęcia, który musi być w tym samym miejscu, co Twój projekt.

**Comment by sergeidebug** [comment]
{'expiresAt': '2022-05-16T13:16:34.942434Z', 'location': 'https://a.allegroimg.com/original/11cbe1/992d78694655bb59feef684558ed'}

**bardzo dziękuję, wszystko się udało!**
headers - ten sam testowany wiele razy
payload - także
Myślę, że cały problem tkwił w adresie:
"adres (wprowadzałeś błędny https://api.allegro.pl/sale/images; prawidłowy to: https://upload.allegro.pl/sale/images),"

**Comment by Lukasz-Zurek** [comment]
Cieszę się, że mogłem pomóc.
