### ISSUE TITLE
ConnectionAbortedError(10053)

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5682]
Kontaktuję się ponownie, ponieważ przez cały dzień próbowałem to zrobić, ale nie otrzymałem odpowiedzi.
Mam zadanie: dodać obraz z mojego pulpitu do API Alegro i uzyskać lokalizację obrazu na Alegro, abym mógł go później wykorzystać w ofercie.
Aby to zrobić, jak wskazano w dokumentacji i przewodniku muszę przesłać obraz w formie binarnej metodą
'https://api.allegro.pl/sale/images'

i ciągle otrzymuję następujące odpowiedzi
ConnectionAbortedError(10053)
415 UNSUPPORTED_MEDIA_TYPE

poradnik:
w postaci binarnej
curl -X POST \
'https://upload.allegro.pl/sale/images
-H 'Authorization: Bearer {token}' \
-H 'Accept: application/vnd.allegro.public.v1+json' \
-H 'Content-Type: "image/jpeg", "image/png"' \
-H 'Accept-Language: pl-PL', (albo en-EN) \
--data-binary "@file_to_upload.png"                -- wymagane, zawartość pliku z
                                                     obrazkiem w postaci binarnej

mój kod:
headers = {'charset': 'utf-8',
           'Accept-Language': 'pl-PL',
           'Content-Type': '"image/jpeg", "image/png"',
           'Accept': 'application/vnd.allegro.public.v1+json',
           'Authorization': "Bearer {}".format(access_token)}
DEFAULT_API_URL = 'https://api.allegro.pl/sale/images'
with requests.Session() as session:
    session.headers.update(headers)
    photo = "C:/Users/admin/Desktop/b2.jpg"
    with open(photo, 'rb') as file:
        photo_data = file.read()
        data = {"binary-data": photo_data}
        # pybase64.b64encode(photo_data)
        response = session.post(
                DEFAULT_API_URL,
                data=data)  # 
    print(response.json())
    print(response.status_code)

Proszę powiedzieć, jak mogę rozwiązać problem?

Powiedziano mi już, żebym nie używał kodowania base 64. OK, jakiego kodowania powinienem użyć?
Również to, że mój język programowania może być winny temu, że coś nie działa. Kod w Pythonie. Nie widzę w tym problemu. Muszę zrozumieć wymagania dotyczące przesyłania pliku w formie binarnej. Proszę wskazać te wymagania.

**Comment by Lukasz-Zurek** [comment]
Założyłeś już wątek w tej sprawie #5680 - myślę, że najlepiej będzie jak temat ten kontynuować będziemy w jednym wątku.

**Comment by sergeidebug** [comment]
> Założyłeś już wątek w tej sprawie #5680 - myślę, że najlepiej będzie jak temat ten kontynuować będziemy w jednym wątku.

tak, przepraszam
