### ISSUE TITLE
AccessDenied for sales/offers endpoints

### ISSUE THREAD

**Issue by aheldes** [allegro/allegro-api#5684]
Hello,

Im following guide for [fees ](https://developer.allegro.pl/tutorials/how-to-check-the-fees-3An6Wame3Um#press-here-to-show-response) and Im facing an issue calling sale endpoints `https://api.allegro.pl/sale/offers/`. In aplication settings both read and write permissions are ticked as per screenshot.
![image](https://user-images.githubusercontent.com/59527963/168536615-a1348dc5-ffd8-4807-ac16-027ff3bd39ea.png)

Im using python to call endpoints. Here is my code:

```

import requests
import json

CLIENT_ID = ""
CLIENT_SECRET = ""
TOKEN_URL = "https://allegro.pl/auth/oauth/token"


def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False, allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

header = {
    'Authorization': f'Bearer {get_access_token()}',
    'accept': 'application/vnd.allegro.public.v1+json',
    'content-type': 'application/vnd.allegro.public.v1+json',
    'Accept-Language': 'EN'
}

url = 'https://api.allegro.pl/sale/offers/11758352058'
get = requests.get(url, headers=header)
get.json()
```

and the reponse is

```
{'errors': [{'code': 'AccessDeniedException',
   'message': 'Client is not allowed for execute this command',
   'details': 'AccessDeniedException',
   'path': '/sale/offers/11758352058',
   'userMessage': 'Klient nie ma uprawnień, aby wykonać to polecenie'}]}
```

When I use `https://api.allegro.pl/sale/offers/` I get following reponse:
```
{'errors': [{'code': 'AccessDenied',
   'message': 'Access is denied',
   'details': None,
   'path': None,
   'userMessage': 'Access denied. Contact the author of the application.'}]}
```

Do you know what I might be doing wrong?

Thanks

**Comment by PrzemyslawLukanowski** [comment]
To get access to this endpoint, you should use a token from [code](https://developer.allegro.pl/en/auth/#app) flow or [device](https://developer.allegro.pl/en/auth/#DeviceFlow) flow type of authorization. 
In our [documentation](https://developer.allegro.pl/en/documentation/) you can find information, which type of authorization you should use for the selected resource:

![92729029-ffff5900-f371-11ea-98d4-26185f01632b](https://user-images.githubusercontent.com/51473661/168539917-cdb3df42-8217-4b38-9008-1736353b1002.png)


- bearer-token-for-user - code or device flow,
- bearer-token-for-application - client credentials flow - access only to public resources, without user context, e.g. GET /offers/listing GET /sale/categories.

**Comment by aheldes** [comment]
Thanks @PrzemyslawLukanowski,

I tried using the sample code for device flow however, Im getting a 400 response `{'error': 'unauthorized_client', 'error_description': 'Client does not have the device_code grant.'}`. Is there anything else I need to set up?

**Comment by PrzemyslawLukanowski** [comment]
Are you sure you have completed the [3, 4a, and 4b steps ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow)properly?
![9ca3b1c74d38ada534bf557427c4](https://user-images.githubusercontent.com/51473661/168544944-69f951c6-8fdc-4efd-b752-e9ea3c69728f.png) 

Did you manage to receive an access token?

**Comment by aheldes** [comment]
The sample code from [link](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#python) errors out after calling `get_code()` due to the fact that `result` json does not include `verification_uri_complete` key, so I believe I wasnt able to pass 2nd step. See exact error below.
![image](https://user-images.githubusercontent.com/59527963/168546173-1461ec6f-c494-4843-a82a-c6b12d53b3dc.png)

**Comment by PrzemyslawLukanowski** [comment]
I think this error was caused because of the type of your application. Are you sure you have selected the following option on the [Developer Apps website](https://apps.developer.allegro.pl/):
<img width="789" alt="Zrzut ekranu 2022-05-16 o 11 05 39" src="https://user-images.githubusercontent.com/51473661/168558660-226a9a12-fdf1-491f-953d-afdb60f62a45.png">

**Comment by aheldes** [comment]
Thanks, that worked! Is there an authentification method that does not require human input? For both code and device flow it is mandatory to log in manually during the authentification process.

**Comment by PrzemyslawLukanowski** [comment]
It is mandatory, but only initially. The user always needs at the beginning to grant your app consent to access their account. After you receive pair of tokens, you can use a [refresh token ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity)to extend the token validity. Thanks to this feature, users will not be obligated to authorize the app manually twice a day.

**Comment by aheldes** [comment]
Okay, thanks a lot for your help!

**Comment by aheldes** [comment]
Sorry to bother again @PrzemyslawLukanowski, but I cant seem to find a way to refresh a token while using device flow as the refresh requires an authorization_code and when I put in the `user_code` from `https://allegro.pl/auth/oauth/device` response I receive 401 error with `{'error': 'invalid_client', 'error_description': 'Unauthorized grant type: authorization_code'}` response. Example in documentaion is only for `Code flow` so is it possible to refresh a token for `Device flow`?

**Comment by PrzemyslawLukanowski** [comment]
Yes, it is possible. You need to retrieve refresh token from response of `await_for_access_token(interval, device_code) `function and then use it in the `get_next_token(your_refresh_token)` function.

**Comment by aheldes** [comment]
Thank you very much!
