### ISSUE TITLE
Bład pobierania danych order'ów.

### ISSUE THREAD

**Issue by mdziwirek** [allegro/allegro-api#5685]
Tworzę interfejs pomiędzy systemie księgowym i Allegro w celu pobierania danych potrzebnych do wystawienia faktury w moim programie.
Po wywołaniu metody checkout-forms GET z parametrami określonymi w dokumentacji api dostaję komunikat błędu 400 - bad request.

Autoryzacja przebiega poprawnie.
Access token aktualny,
Zakres dostępu do danych poprawny. (allegro:api:orders:read)

Klient API wygenerowany na podstawie schematu swagger.

Mój program generuje następujące wywołanie celem pobrania zamówień o wymaganych dla nas parametrach:

https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?offset=0&limit=100&status=READY_FOR_PROCESSING&fulfillment.status=NEW&fulfillment.shipmentSummary.lineItemsSent=ALL&lineItems.boughtAt.lte=2022-05-01T00%3A00%3A00&lineItems.boughtAt.gte=2022-05-08T00%3A00%3A00

Poproszę o wsparcie w zakresie, co powoduje komunikat błędu (błąd w w/w składni?) .

Parametry wypełnione zgodnie z dokumentacją, token jest aktualny.
Pomijamy parametry, które zgodnie z dokumentacją nie są wymagane:

- payment.id	string	Find checkout-forms having specified payment id.
- surcharges.id	string	Find checkout-forms having specified surcharge id.
- delivery.method.id	string	Find checkout-forms having specified delivery method id.
- buyer.login	string	Find checkout-forms having specified buyer login.
- updatedAt.lte	string <date-time>	Checkout form last modification date. The upper bound of date time range from which checkout forms will be taken.
- updatedAt.gte	string <date-time>	Checkout form last modification date. The lower bound of date time range from which checkout forms will be taken.
- sort	string	Enum: "lineItems.boughtAt" "-lineItems.boughtAt" "updatedAt" "-updatedAt"	The results' sorting order. No prefix in the value means ascending order. - prefix means descending order. If you don't provide the sort parameter, the list is sorted by line item boughtAt date, descending.

**Comment by PrzemyslawLukanowski** [comment]
W parametrach `lineItems.boughtAt.lte` i `lineItems.boughtAt.gte` brakuje "Z" na końcu wartości, czyli prawidłowa data to np. 2022-05-01T12%3A00%3A00Z.

> Pomijamy parametry, które zgodnie z dokumentacją nie są wymagane:

Uściślając - żadne parametry wyszukiwania nie są wymagane przy tym zasobie.

**Comment by mdziwirek** [comment]
Dziękuję za informację. Faktycznie dodanie Z (odpowiednia zmiana formatu daty w swager) rozwiązało problem. Proszę o zamknięcie wątku.
