### ISSUE TITLE
Wystawiona oferta nie istnieje

### ISSUE THREAD

**Issue by AlpanetPL** [allegro/allegro-api#5689]
Dzień dobry,

Klient wystawiał przez REST API dwie oferty, podczas ich wystawiania otrzymały one następujące ID: 12151329899 (Command ID: 35e4273c-aeab-571d-8d22-4589de23e8a1) oraz 12151325343 (Command ID: 9cd5c83f-19d0-52ec-96a6-557f9a54cdd5). Podczas próby wyświetlenia tych ofert zwracany jest błąd 404, https://api.allegro.pl/sale/offers?offer.id= również zwraca pusty wynik.

Zasób https://api.allegro.pl/sale/offer-publication-commands/{CommandId}/tasks, zwraca taki message: "Could not change offer publication status. Offer not found. It was deleted, archived or never existed.". Natomiast oferty nie były ani usuwane, ani archiwizowane. Można sprawdzić po Państwa stronie co jest przyczyną? Dodam, że klient utworzył w systemie dwa nowe produkty, identyczne jak te, które próbował wystawić i te przeszły bez problemu.

**Comment by AureliuszBrussy** [comment]
W logach widzę, że obydwa szkice zostały po kilku sekundach usunięte przez inną aplikację. Client ID aplikacji, która skorzystała z [DELETE /sale/offers/{offerId}](https://developer.allegro.pl/documentation#operation/deleteOfferUsingDELETE): 2135-xxxx-1bbe (4 pierwsze i 4 ostatnie znaki z całego Client ID).

**Comment by Onyxwroclaw** [comment]
W jaki sposób mogę sprawdzić nazwę aplikacji po Client ID? Wchodzę na allegro w zakładkę "Powiązane aplikacje" i nie widzę żadnej z takim numerem

**Comment by AureliuszBrussy** [comment]
@Onyxwroclaw rozumiem, że tutaj pomyliłeś wątek i chodzi o nazwę aplikacji z wątku o numerze #5688 (c579-xxxx-b223)? Nazwa aplikacji to "ONYX Wrocław" i jest ona powiązana z Twoim kontem.

**Comment by Onyxwroclaw** [comment]
Zgadza się, dopiero teraz zauważyłem, że są dwa podobne tematy obok siebie. Dziękuje

**Comment by AlpanetPL** [comment]
@AureliuszBrussy Gdzie można sprawdzić podane przez Ciebie Client ID? W zakładce "Powiązane aplikacje" nie widzę takiego ID.

**Comment by AureliuszBrussy** [comment]
@AlpanetPL sprawdziłem to - konto, z którego utworzono szkice wciąż jest powiązane z aplikacją o tym Client ID (2135{xxxx}1bbe). Jest to ostatnie powiązanie na tym koncie - będzie na samej górze listy [Powiązane aplikacje](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje) po zalogowaniu na odpowiednie konto.

**Comment by AlpanetPL** [comment]
OK. Dziękuję za pomoc.
