### ISSUE TITLE
Kłopoty parametrami

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5690]
Dzięń dobry,
 mam taką procedurę; Najpierw tworze produkt i podaje tylko parametry opisujące produkt w kategorii 68631 (Dom i Ogród/Budownictwo i Akcesoria/Ściany i elewacje/Tapety/Fototapety)
i parametr, który ma ponad 11 000 wartości słownikowych 
"id"]=>
      string(6) "248811"
      ["name"]=>
      string(5) "Marka"
      ["type"]=>
      string(10) "dictionary"
      ["required"]=>
      bool(true)
      ["requiredForProduct"]=>
      bool(true)
      ["unit"]=>

wystawiam jako
 "id": "248811",
                        "name": "Marka",
                        "valuesIds": [
                            "248811_950468"
                        ]
                    }

i otrzymuje { "errors":[{"code":"ProductValidationException","message":"Marka","details":null,"path":"productSet[0].product","userMessage":"Nie została podana propozycja wartości do wartości niejednoznacznej w parametrze Marka."}]}

i gdzie mam podać propozycje niejednoznaczności?

**Comment by hahyes** [comment]
w polu `values`
```
"id": "248811",
"name": "Marka",
"valuesIds": [
"248811_950468"
],
"values": [
"inna marka, którą chcesz podać"
]
}
```

**Comment by Zbigi** [comment]
ok, dzięki

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak jak opisał @hahyes - w przypadku wartości "ambiguousValue" musisz wskazać konkertną wartość, która wg Ciebie powinna się pojawić dla wskazanego parametru niejednoznacznego.

**Comment by Zbigi** [comment]
No i ma następny problem:))
Parametr, tak podaje parametr

 "id": "130192",
                        "name": "Gama kolorystyczna",
                        "values": [
                            "wielokolorowe"
                        ],
                        "valuesIds": [
                            "130192_2048"
                        ]
Wartości ściągam z systemu 
   object(stdClass)#26 (3) {
          ["id"]=>
          string(11) "130192_2048"
          ["value"]=>
          string(13) "wielokolorowe"
          ["dependsOnValueIds"]=>
          array(0) {
          }
        }
a otrzymuje
Given dictionary parameter value `wielokolorowe` not found in parameter `Color Scheme`.

**Comment by hahyes** [comment]
```
"id": "130192",
"name": "Gama kolorystyczna",
"values": [
"wielokolorowe"
],
"valuesIds": [
"130192_2048"
]
```
Jeżeli wybierasz wartość ze słownika "wielokolorowe" to nie podawaj jej nazwy w `values`. Podajesz tylko `valuesIds`. `valuesIds` i `values` podajesz tylko, jak parametr dla konkretnej wartości np. "inna marka" wymaga podania, co to konkretnie za marka. Tutaj masz kolory, więc gdyby było "inny kolor" albo "inny" to tam wpisuj, co to konkretnie za kolor. Identyfikator takiej wartości, która wymaga lub pozwala na wpisanie własnej wartości, znajdziesz w polu `ambigiousValue`.

**Comment by Zbigi** [comment]
ok, a właśnie zmieniłem funkcje, żeby wszędzie podawał obydwie wartości:))) Czyli tylko dla parametrów z ambigiousValue podawać obydwie wartości. czyli  ["options"]   ["ambiguousValueId"]
w przypadku Parametru Gama kolorystyczna ta wartość jest rożna od  NULL,
 A jak rozpoznać taki parametr
  ["id"]=>
      string(6) "130192"
      ["name"]=>
      string(18) "Gama kolorystyczna"
      ["type"]=>
      string(10) "dictionary"
      ["required"]=>
      bool(false)
      ["requiredForProduct"]=>
      bool(false)
      ["unit"]=>
      NULL
      ["options"]=>
      object(stdClass)#14 (8) {
        ["variantsAllowed"]=>
        bool(true)
        ["variantsEqual"]=>
        bool(false)
        ["ambiguousValueId"]=>
        string(11) "130192_4096"
        ["dependsOnParameterId"]=>
        NULL
        ["requiredDependsOnValueIds"]=>
        NULL
        ["displayDependsOnValueIds"]=>
        NULL
        ["describesProduct"]=>
        bool(true)
        ["customValuesEnabled"]=>
        bool(false)
      }

**Comment by MaciejFrackowiak** [comment]
Dodam jeszcze do wypowiedzi @hahyes, że w przypadku parametru "Gama kolorystyczna" aktywna jest flaga "customValuesEnabled": false", co oznacza, że dla tego parametru nie możesz podać własnej wartości definiującej kolor.

**Comment by Zbigi** [comment]
czyli jesłi customValuesEnabled jest true i jest rózna od NULL

**Comment by Zbigi** [comment]
wystawiam

"name": "Fototapeta lateksowa Dmuchawce w...368x248",No i następny parametr
podaje taką wartość

 "id": "130210",
                        "name": "Rodzaj",
                        "values": [
                            "lateksowa"
                        ],
                        "valuesIds": [
                            "130210_1118193"

i otrzymuję
{"errors":[{"code":"InvalidDictionaryParameter","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"Given dictionary parameter valuesIds `130210_1118193` in parameter `130210` indicates different value than `values` field."}]}

**Comment by MaciejFrackowiak** [comment]
@Zbigi Dokładnie ;)

**Comment by MaciejFrackowiak** [comment]
Podana przez Ciebie marka znajduje się w słowniku wartości:
```
{
                    "id": "248811_949962",
                    "value": "Artgeist",
                    "dependsOnValueIds": []
                },
```

Tym samym skorzystaj z dostępnego id="248811_949962", a nie próbuj dodawać nowej wartości dla "ambiguousValueId": "248811_950468".

**Comment by Zbigi** [comment]
Ok, dzięki, już zanalazłem :))

**Comment by Zbigi** [comment]
Dzień dobry,
teraz mam coś takiego:)
Przy wystawianiu produktu mam 
 "quantity": {
                "value": "5"
            },

i błąd
  ["errors"]=>
  array(1) {
    [0]=>
    array(5) {
      ["code"]=>
      string(16) "VALIDATION_ERROR"
      ["message"]=>
      string(41) "Maximum number of products in offer is 5."
      ["details"]=>
      string(15217) "Invalid value: [ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta lateksowa Kule w...110x200, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[63.05], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[110], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[110], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[200], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[2], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275089], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[L-FT4966A_2O], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta flizelinowa Dmuchawce w...412x248, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[54.39], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[412], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[412], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[248], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[8], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[F-FT4192A_8C], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta Wall Paper HP Łąka z...95x205, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=[HP Wallpaper], valuesIds=[130210_5], rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[65.62], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[95], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[95], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[205], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[1], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275089], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[H-FT4018A_1AN], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta Wall Paper HP Miś Roman w...368x248, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=[HP Wallpaper], valuesIds=[130210_5], rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[54.49], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[368], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[368], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[248], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[8], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[H-FT3983A_8B], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788, https://a.allegroimg.com/original/11c20e/ed12b7f0479b846a03da08b87f00], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta lateksowa Roman w chmurkach...402x240, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[52.23], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[402], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[402], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[240], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[9], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[L-FT3984A_9A], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788, https://a.allegroimg.com/original/11c20e/ed12b7f0479b846a03da08b87f00, https://a.allegroimg.com/original/111367/daa2380d4617870e58bd715f2a37], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta lateksowa Wpadka 402x240, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[54.83], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[402], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[402], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[240], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[9], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[L-FT1345A_9A], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788, https://a.allegroimg.com/original/11c20e/ed12b7f0479b846a03da08b87f00, https://a.allegroimg.com/original/111367/daa2380d4617870e58bd715f2a37, https://a.allegroimg.com/original/111f90/15ccc7684705b16f1cc70918535f], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta lateksowa Przygoda w...400x268, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[59.66], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[400], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[400], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[268], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[8], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[L-FT3955A_8A], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788, https://a.allegroimg.com/original/11c20e/ed12b7f0479b846a03da08b87f00, https://a.allegroimg.com/original/111367/daa2380d4617870e58bd715f2a37, https://a.allegroimg.com/original/111f90/15ccc7684705b16f1cc70918535f, https://a.allegroimg.com/original/11c141/92d4cb394c30976a89d99f7b6704], idType=null), quantity=ProductSetElementQuantity(value=5)), ProductSetElementRequestDto(product=ProductRequestDto(id=___###!!!UNDEF!!!###___, name=Fototapeta lateksowa Zielone dmuchawce...200x135, category=IdDto(id=68631), parameters=[ParameterDto(id=130192, name=Gama kolorystyczna, values=null, valuesIds=[130192_2048], rangeValue=null), ParameterDto(id=130209, name=Informacje dodatkowe, values=null, valuesIds=[130209_4], rangeValue=null), ParameterDto(id=130210, name=Rodzaj, values=null, valuesIds=null, rangeValue=null), ParameterDto(id=17448, name=Waga produktu z opakowaniem jednostkowym, values=[2.5], valuesIds=null, rangeValue=null), ParameterDto(id=18062, name=Motyw, values=null, valuesIds=[18062_131072], rangeValue=null), ParameterDto(id=215178, name=Cena, values=[67.15], valuesIds=null, rangeValue=null), ParameterDto(id=216577, name=Szerokość, values=[200], valuesIds=null, rangeValue=null), ParameterDto(id=216581, name=Gramatura, values=[212], valuesIds=null, rangeValue=null), ParameterDto(id=216665, name=Długość, values=[200], valuesIds=null, rangeValue=null), ParameterDto(id=216669, name=Wysokość, values=[135], valuesIds=null, rangeValue=null), ParameterDto(id=216673, name=Liczba elementów, values=[1], valuesIds=null, rangeValue=null), ParameterDto(id=216677, name=Orientacja, values=null, valuesIds=[216677_275093], rangeValue=null), ParameterDto(id=224017, name=Kod producenta, values=[L-FT5457A_1AL], valuesIds=null, rangeValue=null), ParameterDto(id=248811, name=Marka, values=[Fideli], valuesIds=[248811_950468], rangeValue=null)], images=[https://a.allegroimg.com/original/11b6f5/96561b12404db09c9befce415e98, https://a.allegroimg.com/original/111bfc/af32229146c2b3ad05b6b8e7dd3f, https://a.allegroimg.com/original/118875/537d3e8c4e629974d5d9c3f00788, https://a.allegroimg.com/original/11c20e/ed12b7f0479b846a03da08b87f00, https://a.allegroimg.com/original/111367/daa2380d4617870e58bd715f2a37, https://a.allegroimg.com/original/111f90/15ccc7684705b16f1cc70918535f, https://a.allegroimg.com/original/11c141/92d4cb394c30976a89d99f7b6704, https://a.allegroimg.com/original/118a06/c0d710184a9e97249c9f308cf6c7], idType=null), quantity=ProductSetElementQuantity(value=5))]"
      ["path"]=>
      string(10) "productSet"
      ["userMessage"]=>
      string(41) "Maximum number of products in offer is 5."
    }
  }
}

**Comment by MaciejFrackowiak** [comment]
@Zbigi W zestawie produktowym możesz maksymalnie połączyć ze sobą 5 produktów - tu jak widzę przekroczyłeś ten limit.

**Comment by Zbigi** [comment]
Jedna sztuka to też za dużo?

**Comment by MaciejFrackowiak** [comment]
Problem tkwi w liczbie produktów, które umieszczasz w zestawie - jak wspomniałem może to być maksymalnie 5 produktów. Nie jest istotna liczba sztuk przypisana do każdego produktu.
Obrazowo tłumacząc - tworzysz zestaw nr 1, do którego możesz przypisać tylko produkt A, B, C, D, E - przekroczenie i dodanie np. F i G spowoduje zwrócenie komunikatu błędu.

**Comment by Zbigi** [comment]
Ok, rozumiem, ale próbowałem 1 wyrzuca błąd, że  za dużo. Przy 0 wyrzuca błąd, że invalid value, przy braku wyrzuca błąd, że brak. To ile ma być dla pojedynczego produktu?

**Comment by Zbigi** [comment]
"quantity": {
                "value": "2"
            },
przy 2 także wyrzuca błąd
"Maximum number of products in offer is 5."

**Comment by MaciejFrackowiak** [comment]
Cały czas odnosisz się do wartości z pól „quantity.value”, a problem leży w konstrukcji samego zestawu produktowego, o czym wcześniej sygnalizowałem. 
Jeden zestaw produktowy może się składać maksymalnie z 5 produktów - w Twoim przypadku są to „Fototapeta lateksowa Kule w...110x200”, „Fototapeta flizelinowa Dmuchawce w...412x248”, etc. I takich pojedynczych produktów możesz do zestawu „włożyć” maksymalnie 5, a Twój request jak widzimy we wcześniej zamieszczonym poście zawiera ponad 5 takich składowych produktów.

**Comment by Zbigi** [comment]
ok, dzięki rozumiem

**Comment by Zbigi** [comment]
Co zrobić,:
gdy produkt przypisany do Aukcji nie pasuje w podstawowych parametrach jak szer i wys?
gdy aukcja wystawiła mi się jako zestaw. Czy da się to zmienić, czy trzeba zamknąć aukcje

**Comment by MaciejFrackowiak** [comment]
Jeżeli są to parametry identyfikujące produkt to nie zmienisz ich w trwającej ofercie. Możesz stworzyć nowy produkt lub też zgłosić sugestię zmiany w istniejącym produkcie.

**Comment by Zbigi** [comment]
dzień dobry,
1. Niestety utworzyły mi sie zestawy produktowe tam gdzie ich nie chciałem. czy zmieniając quantity na 1 usunę zestaw.
Nie wiem, dlaczego się tworzą, ponieważ już teraz ustawiam quantity na 1. 
2. co zrobić, gdy produkt przyporządkowany przez Państwa zawiera ewidentne błędy. Jak próbuje podłaczać nowy produkt wraca ten sam , co poprzednio. Jest tego całe mnóstwo
