### ISSUE TITLE
The offer description contains images not present in the offer gallery

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5692]
Hey!
przesłałem kilka zdjęć i uzyskałem ich lokalizacje
'https://upload.allegro.pl/sale/images'
po czym ładuję ofertę
'https://api.allegro.pl/sale/offers'

{'errors': [{'code': 'ValidationError.MethodArgumentNotValidException', 'message': 'The offer description contains images not present in the offer gallery. Remove them from the description

Jak mogę dodać zdjęcia przez api, abym mógł je wykorzystać w opisie?

**Comment by AureliuszBrussy** [comment]
Komunikat który otrzymałeś mówi o tym, że w opisie oferty (obiekt **description**) korzystasz z url do zdjęć, których nie dodałeś do galerii oferty (tablica **images[]**). Wszystkie url zdjęć wykorzystane w opisie muszą zostać dodane do galerii (**images[]**). 

Jeżeli chcesz, abym sprawdził ten konkretny przypadek - podaj proszę trace-id, który znajdziesz w nagłówku odpowiedzi z errorem.

**Comment by sergeidebug** [comment]
dzięki, tak to działa
