### ISSUE TITLE
Problem z aktywacją konta na sandboxie

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5694]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam.
Mam problem z aktywacją konta na sandboxie. Niby przeklikałem się przez formularz łącznie z ustawieniem konta do wypłat oraz aktywacją firmy, ale dalej proces wisi i nie wiem co ze swojej strony moglbym zrobic dalej.
Login konta: **syriusz** mail: **allegro.eltrox@protonmail.com**

I drugi temat dotyczy konta **smartsprzet**. Zostala na nim zablokowana sprzedaż i nie wiem jak na sandboxie miałbym przywrócić ze swojej strony konto do działania.

**Comment by MaciejFrackowiak** [comment]
Aktywowałem Twoje konto "syriusz".
Natomiast na koncie "smartsprzet" musisz uregulować należności wobec Allegro - skorzystaj proszę z symulatora płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by Himon-SYNCRAFT** [comment]
Dziękuje bardzo za pomoc. Teraz już oba konta są aktywne :)
