### ISSUE TITLE
[ERR_STANDARDIZED_DESCRIPTION_INCORRECT]: Opis zawiera zdjęcia spoza galerii

### ISSUE THREAD

**Issue by rmjanowicz** [allegro/allegro-api#57]
Mam taką odpowiedź:
[ERR_STANDARDIZED_DESCRIPTION_INCORRECT]: Opis zawiera zdjęcia spoza galerii: https://c.allegroimg.allegrosandbox.pl/original/fe9833/89807b834e78863aaca2381a3cbc, https://0.allegroimg.allegrosandbox.pl/original/fe6e4d/b42fb4e94bbab0f9a91a2378c100"

A opis nie zawiera zdjęć spoza galerii:
`{"sections":[{"items":[{"type":"TEXT","content":"<h1>The Reporters - Bare Hands<\/h1><h2>Winyl, LP, Album, 1983<\/h2>"}]},{"items":[{"type":"TEXT","content":"<ul><li><b>Wykonawca:<\/b> The Reporters<\/li><li><b>Tytu\u0142:<\/b> Bare Hands<\/li><li><b>Rok wydania:<\/b> 1983<\/li><\/ul>"},{"type":"IMAGE","url":"PHOTO_FID_16"}]},{"items":[{"type":"IMAGE","url":"PHOTO_FID_17"}]}]}`

i FID16 oraz 17 zawiera base64 zdjęć.

Czy w sandboxie nie da się wystawić aukcji ze zdjęciami, czy mam coś jednak nie tak z opisem?

**Comment by sqlldev** [comment]
`<h2>Winyl, LP, Album, 1983<\/h2>"}]}`
Wydaje mi się, że tutaj leży problem, a konkretnie tutaj `<\/h2>`
Spróbuj poprawnie zamknąć tag.

**Comment by rmjanowicz** [comment]
Ha, nawet tego nie zauważyłem. Dodałem JSON_UNESCAPED_SLASHES i teraz wszystkie zamknięcia są ok, a problem nadal występuje.

`{"sections":[{"items":[{"type":"TEXT","content":"<h1>The Reporters - Bare Hands</h1><h2>Winyl, LP, Album, 1983</h2>"}]},{"items":[{"type":"TEXT","content":"<ul><li><b>Wykonawca:</b> The Reporters</li><li><b>Tytu\u0142:</b> Bare Hands</li><li><b>Rok wydania:</b> 1983</li><li><b>Wytw\u00f3rnia:</b> Creep Records</li><li><b>Numer katalogowy:</b> CREEP 01</li><li><b>Stan no\u015bnika:</b> Bardzo Dobry Plus (VG+)</li><li><b>Stan ok\u0142adki:</b> Prawie Idealny (NM)</li></ul>"},{"type":"IMAGE","url":"PHOTO_FID_16"}]},{"items":[{"type":"IMAGE","url":"PHOTO_FID_17"}]}]}`

**Comment by sqlldev** [comment]
Spróbuj bez tego typu rzeczy `\u0142`

**Comment by rmjanowicz** [comment]
Spróbowałem i dalej to samo. Zresztą bez zdjęć taki opis przechodzi bez problemu. Wrzuciłem zrzut xml: [http://wklej.org/hash/42564c2d4b2/txt/](http://wklej.org/hash/42564c2d4b2/txt/)
Może tam się coś wyjaśni :)

**Comment by AniaMalinowska** [comment]
Pracujemy nad problemem ze zdjęciami na Sandboxie. Prośba o cierpliwość.

Dodatkowo, jeśli zamieszczasz opis bez encji, wówczas umieść go w znaczniku <![CDATA[ opis oferty ]]>. Przetestowałam opis, jaki podesłałeś i gdy umieściłam go w w/w znaczniku, wystawia się prawidłowo w środowisku produkcyjnym. Chwilowo mogę zaproponować wystawienie oferty testowej właśnie w środowisku produkcyjnym - w jednej z kategorii z darmowym wystawianiem.

**Comment by rmjanowicz** [comment]
Te wcześniejsze opisy, które podsyłałem, to był podgląd obiektu z mojego systemu przed wysłaniem requesta przez SOAP. Request wysyłany przez SOAP wygląda tak:
`{"sections":[{"items":[{"type":"TEXT","content":"&lt;h1&gt;The Reporters - Bare Hands&lt;/h1&gt;&lt;h2&gt;Winyl, LP, Album, 1983&lt;/h2&gt;"}]},{"items":[{"type":"TEXT","content":"&lt;ul&gt;&lt;li&gt;&lt;b&gt;Wykonawca:&lt;/b&gt; The Reporters&lt;/li&gt;&lt;li&gt;&lt;b&gt;Tytuł:&lt;/b&gt; Bare Hands&lt;/li&gt;&lt;li&gt;&lt;b&gt;Rok wydania:&lt;/b&gt; 1983&lt;/li&gt;&lt;li&gt;&lt;b&gt;Wytwórnia:&lt;/b&gt; Creep Records&lt;/li&gt;&lt;li&gt;&lt;b&gt;Numer katalogowy:&lt;/b&gt; CREEP 01&lt;/li&gt;&lt;li&gt;&lt;b&gt;Stan nośnika:&lt;/b&gt; Bardzo Dobry Plus (VG+)&lt;/li&gt;&lt;li&gt;&lt;b&gt;Stan okładki:&lt;/b&gt; Prawie Idealny (NM)&lt;/li&gt;&lt;/ul&gt;"},{"type":"IMAGE","url":"PHOTO_FID_16"}]},{"items":[{"type":"IMAGE","url":"PHOTO_FID_17"}]}]}`
Czy tak jest prawidłowo? Czy umieszczać go w znaczniku CDATA?

**Comment by AniaMalinowska** [comment]
Ok, jeśli masz opis z encjami, to już nie umieszczaj go w znaczniku CDATA.

**Comment by Onixarts** [comment]
Zdjęcia na sanboxie nie działają od kilku miesięcy i taki też problem pojawia się z nowymi opisami. Nie wystawisz aukcji ze zdjęciem na sandboxie bo ląduje ono w nieistniejącej lokalizacji i validator aukcji zapewne nie może tego zdjęcia znaleźć.

**Comment by rmjanowicz** [comment]
Tylko dziwne, że właśnie w sandboxie widziałem, że ktoś testował wystawianie oferty z nowym opisem i mu się to udawało. Zamiast zdjęć były puste obszary z niewczytanym obrazkiem.

**Comment by SoftSolid** [comment]
Podpisuję się pod tym. Na sandbox nie widać zdjęć przy aukcjach.

**Comment by AniaMalinowska** [comment]
Pracujemy nad problemem ze zdjęciami na Sandboxie. Prosimy o cierpliwość.
Już wkrótce udostępnimy nowe środowisko testowe, które powinno być wolne od tego problemu.

**Comment by WGRINGO** [comment]
Czy dodawanie zdjęć do opisu w sandboxie działa poprawnie bo ja dostaję błąd:
Zdjęcie w przeglądarce pokazuje się bez problemu, załadowane sandboxem:
"url": "https://9.allegroimg.allegrosandbox.pl/original/1165aa/2ead777b4f38b8281005264a1039"

Mój request w sandboxie to:
PUT /sale/offers/6206117765

Dostaję błąd :
422 {"errors":[{"code":"VALIDATION_ERROR","message":"Zdjęcia zawarte w opisie są niepoprawne."

Treść requesta
{
  "name": "Oferta testowa",
  "category": {
    "id": "46113"
  },
  "ean": null,
  "compatibilityList": {
    "items": null
  },
  "images": [],
  "publication": {
    "duration": null,
    "status": "INACTIVE",
    "startingAt": null,
    "endingAt": null
  },
  "payments": {
    "invoice": "NO_INVOICE"
  },
  "afterSalesServices": null,
  "additionalServices": null,
  "sizeTable": null,
  "promotion": null,
  "external": {
    "id": "5"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [],
    "validatedAt": "2019-01-09T14:22:22.043Z"
  },
  "createdAt": "2019-01-09T10:48:45Z",
  "updatedAt": "2019-01-09T14:22:22.043Z",
  "id": "6206117765",
  "location": {
    "countryCode": "PL",
    "province": "WIELKOPOLSKIE",
    "city": "Poznań",
    "postCode": "60-166"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "1499",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_2"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "17448",
      "valuesIds": [],
      "values": [
        "5711"
      ],
      "rangeValue": null
    },
    {
      "id": "395",
      "valuesIds": [
        "395_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "11325",
      "valuesIds": [
        "11325_2"
      ],
      "values": [],
      "rangeValue": null
    }
  ],
  "stock": {
    "available": 4,
    "unit": "UNIT"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Opis </p><p>wer</p><p><br></p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://9.allegroimg.allegrosandbox.pl/original/1165aa/2ead777b4f38b8281005264a1039"
          }
        ]
      }
    ]
  },
  "delivery": {
    "shippingRates": {
      "id": "2e173f84-fb42-4a41-ac6b-bbff1b046b07"
    },
    "handlingTime": "PT168H",
    "additionalInfo": "Dodatkowe informacje o dostawie",
    "shipmentDate": "2018-04-01T08:00:00Z"
  }
}

**Comment by PawelTaberski** [comment]
@WGRINGO A dodałeś te zdjęcie również w strukturze  "images": [], gdzie należy podać ścieżki obrazków?
Więcej na ten temat znajdziesz [tutaj](https://developer.allegro.pl/sale/#new-offer).

**Comment by WGRINGO** [comment]
Ok dziękuję to był mój błąd. Jednak po przejściu requesta zamiast zdjęć widać puste kwadraty. Rozumiem, że w sandboxie dalej to nie jest poprawione? Pytam bo rzutuje to na opis produktu - nie wiadomo czy zdjęcia wczytały się w takim układzie jaki był zamiar bo wszędzie są puste kwadraty.

**Comment by PawelTaberski** [comment]
Przetestowałem i zdjęcia wyświetlają się poprawnie, prześlij jeszcze raz zdjęcia przy pomocy zasobu [/sale/images](https://developer.allegro.pl/sale/#step-3-images), i dodaj je do oferty. Możliwe, że tamte zdjęcia przez to, że ich nigdzie nie wykorzystałeś wygasły. Każdorazowo przy przesłaniu otrzymujesz datę, kiedy usuniemy grafikę z serwera.

**Comment by Onixarts** [comment]
A da się jakoś sprawdzić czy już nie zostały usunięte? Zakładam scenariusz, że sprzedawca powiedzmy założył nową bazę programu i w niej nie ma zapisanych tych dat.

**Comment by PawelTaberski** [comment]
Jeśli nie zapisał tych dat to nie ma jakiejś metody do sprawdzania ich. 
Jednakże nawet jak wykorzystasz zdjęcie tylko w drafcie to już ta data nie obowiązuje.
