### ISSUE TITLE
Wystawianie oferty - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#570]
POST na /sale/offers generuje błąd.
Response:
`{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal Server Error",
            "details": null,
            "path": "/sale/offers",
            "userMessage": null
        }
    ]
}`
Request:
`curl -X POST \
  https://api.allegro.pl/sale/offers \
  -H 'Accept: application/vnd.allegro.beta.v1+json;charset=UTF-8' \
  -H 'Api-Key: apikey' \
  -H 'Authorization: Bearer token' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/vnd.allegro.beta.v1+json' \
  -H 'Postman-Token: 202f3daa-f48b-49d9-99b7-4b2f3168541a' \
  -d '{
  "name": "Srebrne klapki",
  "category": {
    "id": "27000"
  },
  "payments": {
    "invoice": "VAT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "49.99",
      "currency": "PLN"
    }
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE"
  },
  "stock": {
    "available": 999,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "id": "53443cdb-72fe-454c-b1ab-d275fdc3e3d6"
    },
    "handlingTime": "P2D"
  },
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Klapki w stylu rockowym, wykonane z materiału gumowego. Paseczek z ekologicznej skóry, który ozdobiony jest złotymi ćwiekami. Idealnie nadadzą się do każdej stylizacji!</p>"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://b.allegroimg.com/original/110d23/4fa384544252abe210258a15f81b"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://2.allegroimg.com/original/11db15/0783ff084e0caf8d664d19d60482"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://7.allegroimg.com/original/113037/f4110cd3485c9e34518870c34697"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.com/original/1157b8/a2400c30490e8cc3f4297b15ac4a"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://1.allegroimg.com/original/118c50/7db0ebeb4f3fb5d465017b7c7f81"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://b.allegroimg.com/original/11bcf8/9438e30148c7891f03d054d787bb"
          }
        ]
      },
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://0.allegroimg.com/original/11fe5e/f3224512455bb42edd246b7a75c0"
          }
        ]
      }
    ]
  },
  "location": {
    "countryCode": "PL",
    "province": "ZACHODNIOPOMORSKIE",
    "city": "Szczecin",
    "postCode": "71-447"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ]
    },
    {
      "id": "7108",
      "valuesIds": [
        "7108_160"
      ]
    },
    {
      "id": "451",
      "valuesIds": [
        "451_1"
      ]
    },
    {
      "id": "3766",
      "valuesIds": [
        "3766_14"
      ]
    },
    {
      "id": "64",
      "valuesIds": [
        "64_5"
      ]
    },
    {
      "id": "22728",
      "valuesIds": [
        "22728_215173"
      ]
    },
    {
      "id": "6828",
      "valuesIds": [
        "6828_2"
      ]
    },
    {
      "id": "203089",
      "valuesIds": [
        "203089_4096"
      ]
    },
    {
      "id": "128188",
      "valuesIds": [
        "128188_1"
      ]
    },
    {
      "id": "26388",
      "valuesIds": [
        "26388_64"
      ]
    },
    {
      "id": "203093",
      "values": [
        null
      ]
    }
  ],
  "images": [
    {
      "url": "https://b.allegroimg.com/original/110d23/4fa384544252abe210258a15f81b"
    },
    {
      "url": "https://2.allegroimg.com/original/11db15/0783ff084e0caf8d664d19d60482"
    },
    {
      "url": "https://7.allegroimg.com/original/113037/f4110cd3485c9e34518870c34697"
    },
    {
      "url": "https://a.allegroimg.com/original/1157b8/a2400c30490e8cc3f4297b15ac4a"
    },
    {
      "url": "https://1.allegroimg.com/original/118c50/7db0ebeb4f3fb5d465017b7c7f81"
    },
    {
      "url": "https://b.allegroimg.com/original/11bcf8/9438e30148c7891f03d054d787bb"
    },
    {
      "url": "https://0.allegroimg.com/original/11fe5e/f3224512455bb42edd246b7a75c0"
    }
  ],
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "8b6987e8-3412-4df4-b74f-f00d90a6937d"
    },
    "returnPolicy": {
      "id": "742897cd-90db-43ce-a0fc-4b74f9d545a4"
    },
    "warranty": {
      "id": "3d6f0342-fcb3-4500-9cdc-42944b706b07"
    }
  },
  "validation": null,
  "createdAt": null,
  "updatedAt": null
}'`

**Comment by KrzysztofLukanowski** [comment]
Wygląda na to, że przekazujesz niewłaściwie parametry. Wystaw proszę ofertę przez GUI, pobierz GETem i sprawdź jak to powinno wyglądać.
