### ISSUE TITLE
API Error Reponse for messageToSellerSettings

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5701]
Hi, despite of adding **hint** for _messageToSellerSettings_ **REQUIRED**, I am getting following error response:

**trace-id** cbfc2aaa7f8cb5b

**Request**

{"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"10563","name":"Brand","valuesIds":["10563_904793"]},{"id":"54","name":"Size","valuesIds":["54_805474"]},{"id":"451","name":"Color","valuesIds":["451_131072"]},{"id":"3766","name":"Main Pattern","valuesIds":["3766_14"]},{"id":"202677","name":"Collar Type","valuesIds":["202677_212893"]},{"id":"6168","name":"Sleeve","valuesIds":["6168_212889"]},{"id":"129012","name":"Cut","valuesIds":["129012_2"]},{"id":"201017","name":"Main Fabric","valuesIds":["201017_2357"]},{"id":"225693","name":"EAN","values":["5060887873475"]}],"name":"Test Product 1test Product 1","category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628649b2f579db47e03447b7.jpg"]},"quantity":{"value":1}}],"afterSalesServices":{"returnPolicy":{"id":"5c1be946-8ac4-4636-9ca1-706f828382f7","name":"Test Return 1"},"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"},"warranty":{"id":"d5a3dab6-2f90-47d7-8000-fbeda408c8f7","name":"Test Warrenty 1"}},"additionalServices":{"id":"a43b789b-80b1-4bee-9c63-d66f1e9689ff","name":"Test Packagae 2"},"discounts":{"wholesalePriceList":{"id":"fbebc0ec-0da2-48bd-9243-f1c41c8589ed","name":"Test Price 1"}},"delivery":{"handlingTime":"PT0S","shipmentDate":"2022-05-19T19:01:00Z","additionalInfo":"test","shippingRates":{"id":"cfbf12f5-602e-4057-97cb-9a2aa4ccd99c","name":"Test Delivery Price 1"}},"publication":{"startingAt":"2022-05-19T19:13:00Z","duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"messageToSellerSettings":{"mode":"REQUIRED","hint":"test"},"sizeTable":{"id":"70145102-d75e-11ec-8b88-b02628480130","name":"Test Size 1"},"name":"Test Product 1test Product 1","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>test Product 1<\/p>"}]}]},"category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628649b2f579db47e03447b7.jpg"],"sellingMode":{"format":"BUY_NOW","price":{"amount":"1.00","currency":"PLN"}},"stock":{"available":1,"unit":"UNIT"},"external":{"id":"SWAPNILTEST1"}}

**Response**
{"errors":[{"code":"NO_HINT_FOR_REQUIRED_MODE","message":"No hint for required message.","details":null,"path":"messageToSellerSettings.hint","userMessage":"No hint for required message."}

Thanks in advance.

**Comment by AureliuszBrussy** [comment]
At the moment, it is not possible to set the message for the seller as REQUIRED by the public API. We will inform you as soon as this changes.
