### ISSUE TITLE
Allegro sandbox: nie mogę wystawić oferty

### ISSUE THREAD

**Issue by Albert09876** [allegro/allegro-api#5702]
Dzień dobry,

Chciałem poćwiczyć wystawianie ofert na allegro sandbox, jednak gdy klikam "wystaw przedmiot" lub "dodaj nowa ofertę" przekierowuje mnie do pustej strony z tekstem:

Firefox:
Niestety, nie udało się odnaleźć tej strony

Nie udało się połączyć z serwerem pod adresem „staging-lokalnie.allegrogroup.com”.

Chrome:
Ta witryna jest nieosiągalna

Sprawdź, czy w adresie staging-lokalnie.allegrogroup.com nie ma błędu.

Próbowałem też na przeglądarce Edge oraz na innych urządzeniach, wszędzie jest to samo.

Z góry dziękuję za ewentualną pomoc.

Pozdrawiam serdecznie.

**Comment by AureliuszBrussy** [comment]
Wygląda na to, że korzystasz na Sandboxie z konta zwykłego - nie firmowego. W takim przypadku aby przejść do formularza wystawiania skorzystaj z linka: https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

Podaj proszę jeszcze login swojego konta - sprawdzę, czy jest ono aktywne.

**Comment by Albert09876** [comment]
Login to al_sandbox@interia.pl

Może to kwestia nieaktywnego konta, ale przy próbie wystawienia oferty z podanego linka, przekierowuje mnie na stronę allegrolokalnie, czyli nie jestem już na allegrosandbox.

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto. Wyloguj się i zaloguj ponownie. Możesz także spróbować wyczyścić pliki cookies. 

Gdy skorzystasz z linka https://allegro.pl.allegrosandbox.pl/offer/?lokalnie powinieneś zostać prawidłowo przeniesiony do formularza wystawiania na Sandboxie. 

Warto także [zarejestrować nowe konto firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto). Wtedy korzystanie ze specjalnego linka nie będzie konieczne.

**Comment by Albert09876** [comment]
Niestety, kliknięcie "wystaw przedmiot" przekierowuje mnie na: https://allegrolokalnie.pl/oferty/wystaw

Zamknąłem przeglądarkę całkowicie, wyczyściłem cookies, próbowałem też na drugim urządzeniu, na przeglądarce na której jeszcze nigdy się nie logowałem na allegro, oraz w trybie incognito.

**Comment by mdziwirek** [comment]
Ja mam dokładnie ten sam problem

**Comment by AureliuszBrussy** [comment]
Tutaj niestety trudno mi wskazać co jest przyczyną problemu - sprawdziłem ten link z konta zwykłego i zostałem przekierowany prawidłowo na formularz wystawiania na Sandboxie. 

W tym przypadku najlepiej, jeżeli zarejestrujecie [nowe konta firma](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto) (ew. skorzystanie z opcji [konwersji obecnego konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/konwersja-konta)) - wtedy problem na pewno nie wystąpi. Po przejściu wszystkich kroku weryfikacyjnych (uzupełniaj nieprawdziwymi danymi), poinformujcie mnie. Aktywuje konta.

**Comment by AureliuszBrussy** [comment]
@Albert09876 przejdź jeszcze wszystkie kroki weryfikacji (wraz z symulacją przelewu weryfikacyjnego) - kroki dostępne pod [tym linkiem](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Po tym będę mógł w pełni aktywować Twoje konto.

**Comment by Albert09876** [comment]
Wyklikałem co się dało, proszę zobaczyć czy teraz można aktywować.

**Comment by AureliuszBrussy** [comment]
@Albert09876 aktywowałem konto.

**Comment by Albert09876** [comment]
Wygląda na to że konto działa, ale mogę wystawiać oferty jedynie istniejących produktów. Na stronie https://allegro.pl.allegrosandbox.pl/offer/ widnieje poniższa informacja:

"Nie mamy jeszcze produktu, który sprzedajesz?

Możesz wystawić ofertę bez wybierania produktu."

nie widzę jednak nigdzie takiej opcji, nie ma nic do kliknięcia, czy ta funkcjonalność działa?

**Comment by AureliuszBrussy** [comment]
W polu:
![image](https://user-images.githubusercontent.com/68948612/169524352-4a2e73aa-2700-423e-9e24-156559f54fa3.png)
 wprowadź nazwę produktu. 

Wyszukamy go w katalogu, a jeżeli nic nie odnajdziemy pojawi się opcja:
![image](https://user-images.githubusercontent.com/68948612/169524559-fb27af59-ffd9-40c5-85f8-ff1766787f13.png)

**Comment by Albert09876** [comment]
Wszystko gra. Dziękuję bardzo za pomoc i cierpliwość.

Pozdrawiam serdecznie i miłego weekendu.
