### ISSUE TITLE
Dodawanie szkiców DRAFT - dublowanie

### ISSUE THREAD

**Issue by roskrzysztof** [allegro/allegro-api#5705]
Podczas dodawania szkiców DRAFT https://api.allegro.pl/sale/offers 
{"name":"test"  }

Tworzą się duplikaty - podwójne takie same drafty.
Można to sprawdzić czy problem jest po stronie restAPI czy mojej aplikacji.
Wersja produkcyjna

**Comment by MaciejFrackowiak** [comment]
Wykonałem przykładowy request - utworzył się tylko 1 draft.

**Comment by roskrzysztof** [comment]
Może tu coś mam źle:
`$data = '
      {
        "name":"test"
      }';

      $getDraftUrl = "https://api.allegro.pl/sale/offers";
      $ch = curl_init($getDraftUrl);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
      curl_setopt($ch, CURLOPT_HTTPHEADER, [
                   "Authorization: Bearer $token",
                   "Accept: application/vnd.allegro.public.v1+json",
                   "Content-Type: application/vnd.allegro.public.v1+json"
      ]);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $data);    

      $draft = curl_exec($ch);
      $resultCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
      curl_close($ch);`

![image](https://user-images.githubusercontent.com/9614897/169525481-bbcfcb85-eb7a-4185-be57-5b717c7e72e1.png)

**Comment by MaciejFrackowiak** [comment]
Spoglądając w logi zostały wykonane dwa osobne requesty:
1. 12182720986 - 2022-05-20 14:08:58
2. 12182721222 - 2022-05-20 14:09:02

**Comment by roskrzysztof** [comment]
Problem ewidentnie jest po mojej stronie. Dwa razy wykonuje akcję. Teraz będę szukał gdzie jest problem.

Temat do zamknięcia. Dziękuję.
