### ISSUE TITLE
Edycja zestawu promocyjnego. Nie można zmieniać benefitu typu ORDER_FIXED_DISCOUNT.

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#5706]
Próbowałem edytować promocję typu BUNDLE, metodą PUT, ale niestety zwróciło http 422 z takim komunikatem:
url = 'sale/loyalty/promotions/{promotionId}

W danych dla klucza 'benefits' zawarłem:
`[{'specification': {'value': {'amount': '0.50', 'currency': 'PLN'}, 'type': 'ORDER_FIXED_DISCOUNT'}}]`

Takie same dane otrzymałem gdy pobierałem dane o tym zestawie za pomocą GET'a. W jaki sposób mógłbym edytować wartość amount oraz listę ofert z wnętrza 'offerCriteria', skoro nie w taki sposób?

**Comment by MaciejFrackowiak** [comment]
Nie można edytować promocyjnego zestawu ofert - możesz go tylko usunąć, a następnie stworzyć nowy.
