### ISSUE TITLE
Pobranie nr przesyłki przewoźnika dla przesyłek Allegro

### ISSUE THREAD

**Issue by SlawekMat** [allegro/allegro-api#5707]
Dzień dobry
W jaki sposób mogę pobrać nr przesyłki wygenerowany przez przewoźnika dla paczek Allegro?
Niestety nie znalazłem rozwiązania w dokumentacji

**Comment by MaciejFrackowiak** [comment]
Numer przesyłki z usługi dostawy Allegro uzyskasz w odpowiedzi na [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails) w polu items.waybill.

**Comment by SlawekMat** [comment]
Muszę jeszcze dopytać o przesyłki Allegro One Punkt
Przy próbie stworzenia przesyłki mam komunikat "Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika". W czym może być problem?

**Comment by MaciejFrackowiak** [comment]
Ten komunikat oznacza, że nie możesz podać innych danych do pola "label.sender" - przewoźnik pobierze dane z pola "pickup". W każdym takim przypadku "label.sender" powinno zostać polem z wartością null.

**Comment by SlawekMat** [comment]
Dzięki
