### ISSUE TITLE
Error Response - Mismatch existing parameter value

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5708]
Hi, why am I getting following error:

Request => 
Endpoint => https://api.allegro.pl/sale/product-offer
postData:
{"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"10563","name":"Brand","valuesIds":["10563_40"],"values":["test brand"]},{"id":"54","name":"Size","valuesIds":["54_805474"]},{"id":"451","name":"Color","valuesIds":["451_131072"]},{"id":"3766","name":"Main Pattern","valuesIds":["3766_14"]},{"id":"202677","name":"Collar Type","valuesIds":["202677_212893"]},{"id":"6168","name":"Sleeve","valuesIds":["6168_212889"]},{"id":"129012","name":"Cut","valuesIds":["129012_2"]},{"id":"201017","name":"Main Fabric","valuesIds":["201017_2357"]},{"id":"225693","name":"EAN","values":["5060887873475"]}],"name":"Test Product 1test Product 1","category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628649b2f579db47e03447b7.jpg"]},"quantity":{"value":1}}],"afterSalesServices":{"returnPolicy":{"id":"5c1be946-8ac4-4636-9ca1-706f828382f7","name":"Test Return 1"},"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"},"warranty":{"id":"d5a3dab6-2f90-47d7-8000-fbeda408c8f7","name":"Test Warrenty 1"}},"additionalServices":{"id":"a43b789b-80b1-4bee-9c63-d66f1e9689ff","name":"Test Packagae 2"},"discounts":{"wholesalePriceList":{"id":"fbebc0ec-0da2-48bd-9243-f1c41c8589ed","name":"Test Price 1"}},"delivery":{"handlingTime":"PT0S","shipmentDate":"2022-05-20T15:17:38Z","additionalInfo":"test","shippingRates":{"id":"cfbf12f5-602e-4057-97cb-9a2aa4ccd99c","name":"Test Delivery Price 1"}},"publication":{"startingAt":"2022-05-20T15:17:38Z","duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"messageToSellerSettings":null,"sizeTable":{"id":"70145102-d75e-11ec-8b88-b02628480130","name":"Test Size 1"},"name":"Test Product 1test Product 1","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Test Product 1<\/p>"}]}]},"category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628649b2f579db47e03447b7.jpg"],"sellingMode":{"format":"BUY_NOW","price":{"amount":"1.00","currency":"PLN"}},"stock":{"available":1,"unit":"UNIT"},"external":{"id":"SWAPNILTEST1"}}

trace-id = 79ec4faaf410ebcc
Error Response: The provided parameter 'Brand'(10563) value (other(10563_40)) does not match the existing parameter value (2(X)IST(10563_904793))","details":null,"path":"productSet[0].product.parameters","userMessage":"The provided parameter `Brand` value `other(10563_40)` does not match the existing parameter value `2(X)IST(10563_904793)`.

Thanks in advance.

**Comment by MaciejFrackowiak** [comment]
You received an error 422, because we found in our database an existing product with the EAN=5060887873475. 
If you call [GET /sale/products/?ean=5060887873475](https://developer.allegro.pl/documentation/#operation/getSaleProducts), you will find a product.id=fb94160c-3d47-4e49-a46c-65e7580fe77c. 
It has a Brand parameter with assigned value = "2(X)IST" („valuesIds": "10563_904793”). It means that if you want to list an offer you have to use the Brand parameter with "2(X)IST", not your own value "test brand".
