### ISSUE TITLE
[invalid_grant] Invalid refresh token

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5709]
Hi, I am getting the following error response. A provided refresh token is my last refresh token, but it is still considered invalid. How should I know that my refresh token is expired/invalid (like in the case of access token we have an expiry time of 12 hours). How can I generate it using an API instead of below way which I follow if refresh token is considered invalid:

https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=0b362d641e7c4ad786c3c1ed7eef0b04&redirect_uri=https://dmsmatrix.net/users/login

REQUEST:

https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMDIyNDI0MzIiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiYXRpIjoiYjA4NzQ3MWYtYjUwOC00MDEzLWE3ZGUtMzMxMmI4ZDVkMmQ1IiwiZXhwIjoxNjYwODQwMTExLCJqdGkiOiJlYTgzODA2Yy1kOTcxLTRkMjYtODlkNS1lMzJlNjg5NzYxMjkiLCJjbGllbnRfaWQiOiIwYjM2MmQ2NDFlN2M0YWQ3ODZjM2MxZWQ3ZWVmMGIwNCJ9.NLTUJ44LaOTYt9yMI64FzLGS33-g4tpNd7CWK_htPgEF2RYwrg9etPJMAAaJI4vqp0FjOz5ljbmoFv91-7pNFlJ4ZQ0Hyim-iE2kgRf5UlLw74u1MFzFudQRz1jDcr_qfjZ8i1jLoUaSSTE_9Izri1kUUSoRCU43b5Mq9jQPsU-WYLw5ulQUhBZASb2gXFFkUumiu59ZD8ZBBoUqV2ZtL4RBJZBp8rbz-oX06dboq_chPiupbJ6h5L8zdeASCeSR4uMqWs8kPvp-1fnPI4nlVQi3CTylRSyR99mnJgQYOsWAd6hYMuuVNtRxK3b3Qiinl6BG_PG9oBjIdP629oeVhA&redirect_uri=https://dmsmatrix.net/users/login

RESPONSE:
{
    "error": "invalid_grant",
    "error_description": "Invalid refresh token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMDIyNDI0MzIiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiYXRpIjoiYjA4NzQ3MWYtYjUwOC00MDEzLWE3ZGUtMzMxMmI4ZDVkMmQ1IiwiZXhwIjoxNjYwODQwMTExLCJqdGkiOiJlYTgzODA2Yy1kOTcxLTRkMjYtODlkNS1lMzJlNjg5NzYxMjkiLCJjbGllbnRfaWQiOiIwYjM2MmQ2NDFlN2M0YWQ3ODZjM2MxZWQ3ZWVmMGIwNCJ9.NLTUJ44LaOTYt9yMI64FzLGS33-g4tpNd7CWK_htPgEF2RYwrg9etPJMAAaJI4vqp0FjOz5ljbmoFv91-7pNFlJ4ZQ0Hyim-iE2kgRf5UlLw74u1MFzFudQRz1jDcr_qfjZ8i1jLoUaSSTE_9Izri1kUUSoRCU43b5Mq9jQPsU-WYLw5ulQUhBZASb2gXFFkUumiu59ZD8ZBBoUqV2ZtL4RBJZBp8rbz-oX06dboq_chPiupbJ6h5L8zdeASCeSR4uMqWs8kPvp-1fnPI4nlVQi3CTylRSyR99mnJgQYOsWAd6hYMuuVNtRxK3b3Qiinl6BG_PG9oBjIdP629oeVhA"
}

**Comment by PrzemyslawLukanowski** [comment]
Hello, this refresh token has been used today at 10:08 (UTC+1), and in the response, we've returned new pair of tokens. As a result, the next attempts to use this refresh token ended with an "Invalid refresh token" message. There is no method to check whether the refresh token has been already used or is invalid. If you receive a 401 code in the response for any API request - this may mean that your current access and refresh tokens are invalid.

**Comment by adityakokate** [comment]
Got it..Thanks
