### ISSUE TITLE
Allegro REST API warunki i możliwości

### ISSUE THREAD

**Issue by Analyzepartner** [allegro/allegro-api#5710]
Chciałem dopytać o warunki i możliwości korzystania z developer.allegro.pl. Chcielibyśmy zautomatyzować część procesów i potrzebowalibyśmy więcej informacji dot. warunków / limitów itp. korzystania z Allegro REST API.
Czy mogłybyście podesłać mi więcej informacji na ten temat?

**Comment by PrzemyslawLukanowski** [comment]
Informację o limitach znajdziesz na początku naszego [FAQ](https://developer.allegro.pl/faq). Jeśli chodzi o pozostałe kwestie, które dotyczą warunków korzystania, to komplet informacji znajdziesz w naszym [regulaminie](https://developer.allegro.pl/rules).
