### ISSUE TITLE
Smart allegro

### ISSUE THREAD

**Issue by konradkur** [allegro/allegro-api#5711]
Witam,

czy allegro smart posiada API? Bo nie wiedzę.

Jak nie, czy z poziomu pobrania zamówienia mogę uzyskać np. takie informacje jak ID paczki/typ kuriera?

**Comment by PrzemyslawLukanowski** [comment]
Nie do końca jestem pewien, czy dobrze rozumiem Twoje pytanie, ale aby sprawdzić, czy zamówienie jest rodzaju SMART, skorzystaj z [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET) lub [GET /order/checkout-forms/{checkoutFormId}](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET). Informację znajdziesz w polu `delivery.smart`, zwracamy tam również dane o dostawie. 
W styczniu udostępniliśmy także [nowe zasoby,](https://developer.allegro.pl/tutorials/jak-zarzadzac-kontem-danymi-uzytkownika-ZM9YAKgPgi2#klasyfikacja-w-programie-allegro-smart) dzięki którym możesz sprawdzić klasyfikację ofert i sprzedawcy w programie Allegro Smart!
