### ISSUE TITLE
Check Accepted Offer Result using Location

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5712]
Hi, why I am getting the below response while checking the offer 12192118730 for its completion after it's accepted with HTTP/1.1 202 Accepted.

Location: https://api.allegro.pl:42974/sale/product-offers/12192118730/operations/881e4106-1a48-46bd-9f49-d6adf2df2b17

Response:
[
	'server_output' => false,
	'headers' => [],
	'responseBody' => ''
]

1. What response should be expected if it's called...please provide a sample response? 
2. Is it necessary to call **Location** every time even though I am getting response schema (fields and values) in responseBody of the response of https://api.{environment}/sale/product-offers API?
3. Do I have to call this API before editing offer for its completion?

**Comment by AureliuszBrussy** [comment]
It looks like your request didn't reach our server - it doesn't look like a response from our side. 

We describe [in our documentation](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-publication-in-asynchronous-api) what response you should expect. 

If request processing (POST /sale/product-offers) has not been instantly completed (with '201 Created' status), you should expect a '202 Accepted' response with 'retry-after' and 'location' headers until the operation is completed:

```
 HTTP/1.1 202 Accepted
 location: https://api.allegro.pl/sale/product-offers/9531382307/operations/eadb2e97-9850-4c51-bd27-68888b6d7d5d
 retry-after: 5
  {
  "offer": {
    "id": "9531382307"
  },
  "operation": {
    "id": "ef5dd966-d370-44f7-bb30-3631e3511536",
    "status": "IN_PROGRESS",
    "startedAt": "2019-05-29T12:00:00Z"
  }
 }

```
When we finished processing the operation, we will return HTTP status '303 See Other' in the response to GET /sale/product-offers/{offerId}/operations/{operationId}. You will receive a link to offer data in the location header.

```
  HTTP/1.1: 303 See other
  location: https://api.allegro.pl/sale/product-offers/9531382307
```

It is not necessary to call location only if you instantly get '201 Created' response status. 

Before editing - previous operation should be ended.
