### ISSUE TITLE
Problem z refresh_token - Upłynął limit czasu operacje/Złe żądanie

### ISSUE THREAD

**Issue by slodki1997** [allegro/allegro-api#5713]
Występuje problem:
 - [ x ] z zasobem REST API / with a REST API resource
 - [ x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ x  ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

W firmie korzystamy z aplikacji, która ma za zadanie synchronizować zamówienia Allegro z innym, zewnętrznym systemem. Operacja ta jest automatycznie powtarzana co 10 minut. By nie dopuścić do sytuacji, że aplikacja nagle straci połączenie z kontem Allegro poprzez wygaśnięcie access_tokena, to przy każdorazowej integracji (tej, która odbywa się co 10 minut), token jest odświeżany za pomocą refresh_token, a otrzymane dane zapisywane do pliku. 
Nie wiedzieć czemu, co jakiś czas dochodzi do sytuacji, w której pojawia się błąd o treści:  "Upłynął limit czasu operacje". Pomimo to integracja idzie dalej, niemniej jednak przy każdej integracji pojawia się ten sam komunikat. Zmienia się to po 3h, kiedy to komunikat zwracanego błędu zmienia swoją treść na "Złe żądanie", a integracja przestaje całkowicie działać. 
Zaistniała sytuacja skutkuje koniecznością ponownego połączenia konta Allegro i ręcznym wygenerowaniem nowych access i refresh tokena. 

Z czego to może wynikać i w jaki sposób można uniknąć takich sytuacji?

**Comment by PrzemyslawLukanowski** [comment]
Wyślij proszę przykładowe logi (request i response z naszego API) przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopisz, że dane dotyczą wątku #5713 na GitHub. W taki sposób będzie nam najłatwiej odnaleźć przyczynę tych problemów.
Jeśli chodzi o sytuacje, w których para tokenów traci ważność, to dzieje się tak, gdy skorzystasz już z danego refresh tokena (w odpowiedzi zwracamy wtedy nową parę), ale mogą mieć na to wpływ także akcje użytkownika, jak np. zmiana maila na koncie lub zmiana hasła.

**Comment by slodki1997** [comment]
W formularzu do wyboru mam Kupuję/Sprzedaję/Allegro Charytatywni? Który typ mam wybrać?

**Comment by slodki1997** [comment]
> Wyślij proszę przykładowe logi (request i response z naszego API) przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt). W zgłoszeniu dopisz, że dane dotyczą wątku #5713 na GitHub. W taki sposób będzie nam najłatwiej odnaleźć przyczynę tych problemów. Jeśli chodzi o sytuacje, w których para tokenów traci ważność, to dzieje się tak, gdy skorzystasz już z danego refresh tokena (w odpowiedzi zwracamy wtedy nową parę), ale mogą mieć na to wpływ także akcje użytkownika, jak np. zmiana maila na koncie lub zmiana hasła.


W formularzu do wyboru mam Kupuję/Sprzedaję/Allegro Charytatywni? Który typ mam wybrać?

**Comment by PrzemyslawLukanowski** [comment]
Skorzystaj np. [z tej opcji.](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a)
