### ISSUE TITLE
code: 'AccessDenied'

### ISSUE THREAD

**Issue by samuelslak** [allegro/allegro-api#5714]
Dzień dobry,
Próbuję otrzymać zasób https://api.allegro.pl.allegrosandbox.pl/sale/offers za pomocą Axios poprzez serwer Node.js. Otrzymuję prawidłowo token za pomocą Device Flow, który wygląda następująco:

`eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOmZ1bGZpbGxtZW50OnJlYWQiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOndyaXRlIiwiYWxsZWdybzphcGk6ZnVsZmlsbG1lbnQ6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVn [reszta tokenu wycięta]`

Wykonuję następujący kod [załączam tylko istotny fragment]: 

`    const endpointAction = async (payload) => {
        const token = payload.token;
        const link = "https://api.allegro.pl.allegrosandbox.pl/sale/offers";

        let instance = axios.create({
            headers: {
              Authorization : `Bearer ${token}`,
              Accept: 'application/vnd.allegro.public.v1+json',
              'Content-Type': 'application/vnd.allegro.public.v1+json'
              }
            }
        );
        
        try {
            const result = await instance.get(link);
        }
        catch(error)
        {
            console.log("Error");
            console.log(error.response.status);
            console.log(error.request)
            console.log(error.response.data.errors);
        }
    }`

Otrzymuję za każdym razem błąd z error.response.data.errors:

[
  {
    code: 'AccessDenied',
    message: 'Access is denied',
    details: null,
    path: null,
    userMessage: 'Access denied. Contact the author of the application.'
  }
]

Aplikacja otrzymuje wszelkie możliwe uprawnienia.

![upr](https://user-images.githubusercontent.com/65562502/169837098-b98a65f9-bb4a-43fe-b140-69b8041cb376.png)

Proszę o informację co robię nie tak

**Comment by PrzemyslawLukanowski** [comment]
Wszystko wskazuje na to, że korzystasz jednak z tokena uzyskanego dla autoryzacji typu `client_credentials`. Nie posiada on kontekstu użytkownika, dlatego też nie masz dostępu do żadnych ofert na koncie. Upewnij się, że wygenerowałeś token w sposób, który opisaliśmy [w tym fragmencie](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow). Token możesz także zdekodować - jeżeli nie widnieje w nim wartość dla `user_name`, to masz pewność, że to nieprawidłowy token, wygenerowany w ramach autoryzacji `client_credentials`.

**Comment by samuelslak** [comment]
Faktycznie, to był dokładnie ten problem. Dziękuję za pomoc. Po zdekodowaniu tokenu otrzymałem teraz wartość user_name, wcześniej tej wartości faktycznie nie było.
