### ISSUE TITLE
Jak ustawić dane nadawcy na etykiecie dla kuriera, błąd: "Inne dane na etykiecie" not supporter for carrier

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#5715]
Dzień dobry,

kiedy podejmowana jest próba utworzenia paczki dla metody dostawy Allegro ONE Box lub Punkt, i jednocześnie podaję dane nadawcy dla etykiety w parcel->label->sender, występuje błąd 

> "Inne dane na etykiecie" not supporter for carrier 

i paczki nie udaje się stworzyć.

Jeżeli ustawimy parcel->label na NULL, paczkę udaje się stworzyć. 

Jednak skutek jest taki, że po pobraniu etykiety PDF takiej paczki, dane odbiorcy pojawiają się oprócz swojego miejsca, także w miejscu danych nadawcy.

Dane odbiorcy/klienta ustawiam w parcel->receiver, oraz później w parcel->pickup->email, parcel->pickup->name, parcel->pickup->company, parcel->pickup->phone

W jaki sposób przez API ustawić dane nadawcy na etykiecie dla kuriera?

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz przesłać nam za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=21fb60a8-ea5d-4107-9bcd-d434280a3fad&subjectId=70485696-742a-4f9b-b326-25dc5792fa76) przykładowy request, response oraz etykietę, gdzie w danych nadawcy pojawiły się dane odbiorcy? W zgłoszeniu dopisz proszę, że dane dotyczą wątku #5715 na GitHubie. Jeśli w polu `label.sender` przekazujesz null, powinno to rozwiązać problem, dlatego musimy przyjrzeć się bliżej temu przypadkowi.

**Comment by tztztztz** [comment]
Ja chciałbym po pierwsze wiedzieć GDZIE się podaje te dane nadawcy które później mają się pojawić na etykiecie - bo tego nie wiadomo.

Czy to ma być w parcel.label.sender podczas tworzenia paczki? Tak mi się wydaje, ale nigdzie w dokumentacji tego nie piszecie, nic nie wiadomo, wszystkiego się trzeba domyślać.

Jednak kiedy przy tworzeniu paczki podaję w danych obiektu tworzenia paczki dane w parcel.label.sender, to przy weryfikacji stworzenia paczki, wyskakuje błąd który opisuję wyżej.

Poniżej JSON który jest wysyłany jako request, następnie kiedy robię sprawdzenie, czy udało się stworzyć paczkę przez GET /parcel-management/parcel-create-commands/{UUID} w odpowiedzi dostaję błąd opisany wyżej:

REQUEST i RESPONSE JSON z tworzenia paczki:


> [24-May-2022 13:29:47 Europe/Warsaw] REQUEST
> {"serviceId":9534072,"receiver":{"address":{"street":"Komorowicka 39","postCode":"43-300","city":"Bielsko-Bia\u0142a","countryCode":"PL"},"email":"xnpxsci20u+2361af8a2@user.allegrogroup.pl","name":"Bobo LuLU","company":null,"phone":"609355607","pointId":"AL001MBT"},"pickup":{"address":{"street":"Hrubieszowska 6B","postCode":"01-209","city":"Warszawa","countryCode":"PL"},"email":"xnpxsci20u+2361af8a2@user.allegrogroup.pl","name":"Bobo LuLU","company":null,"phone":"609355607","pointId":"AL001MBT"},"items":[{"dimensions":{"width":{"value":"8","unit":"CENTIMETER"},"height":{"value":"38","unit":"CENTIMETER"},"depth":{"value":"64","unit":"CENTIMETER"}},"weight":{"value":0.4,"unit":"KILOGRAM"},"description":"Paczuszka","value":{"amount":"147.99","currency":"PLN"},"type":"PACKAGE"}],"label":{"sender":{"address":{"street":"ul. Junacka 7A","postCode":"43-502","city":"Czechowice-Dziedzice","countryCode":"PL"},"company":"3KROPKI.PL Sp. z o.o.","phone":"537845360","fileFormat":"PDF","referenceNumber":1155283},"fileFormat":"PDF","referenceNumber":1155283}}
> 
> [24-May-2022 13:29:47 Europe/Warsaw] RESPONSE
>  {"id":"8d3d62d5-9c54-483f-a1e0-4d682df363eb","input":{"serviceId":"9534072","label":{"sender":{"name":null,"company":"3KROPKI.PL Sp. z o.o.","address":{"street":"ul. Junacka 7A","postCode":"43-502","city":"Czechowice-Dziedzice","county":null,"countryCode":"PL"},"email":null,"phone":"537845360"},"fileFormat":"PDF","referenceNumber":"1155283"},"receiver":{"name":"Bobo LuLU","company":null,"address":{"street":"Komorowicka 39","postCode":"43-300","city":"Bielsko-Biała","county":null,"countryCode":"PL"},"pointId":"AL001MBT","email":"xnpxsci20u+2361af8a2@user.allegrogroup.pl","phone":"609355607"},"pickup":{"name":"Bobo LuLU","company":null,"address":{"street":"Hrubieszowska 6B","postCode":"01-209","city":"Warszawa","county":null,"countryCode":"PL"},"pointId":"AL001MBT","email":"xnpxsci20u+2361af8a2@user.allegrogroup.pl","phone":"609355607"},"items":[{"dimensions":{"height":{"value":"38","unit":"CENTIMETER"},"width":{"value":"8","unit":"CENTIMETER"},"depth":{"value":"64","unit":"CENTIMETER"}},"weight":{"value":"0.4","unit":"KILOGRAM"},"description":"Paczuszka","value":{"amount":"147.99","currency":"PLN"},"type":"PACKAGE"}],"type":null,"additionalServices":null}}


A teraz komenda sprawdzenia jak (nie)udało sięstowrzyć paczki:

> 
> [24-May-2022 13:31:55 Europe/Warsaw] GET 
> /parcel-management/parcel-create-commands/8d3d62d5-9c54-483f-a1e0-4d682df363eb
> 
> [24-May-2022 13:31:55 Europe/Warsaw] RESPONSE
> {"id":"8d3d62d5-9c54-483f-a1e0-4d682df363eb","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"\"Inne dane na etykiecie\" not supporter for carrier","details":null,"path":"/sender","userMessage":"Opcja 'Inne dane na etykiecie' nie są dostępne dla wybranego przewoźnika"}]}

W załączniku etykieta innej paczki, którą udało się stowrzyć, bo komenda tworzenia paczki miała parcel.label ustawione na null:

[etykieta-test.pdf](https://github.com/allegro/allegro-api/files/8762260/etykieta-test.pdf)

**Comment by tztztztz** [comment]
Przecież pickup to dane punktu odbioru, jak to mogą być dane nadawcy? Przecież to nie ma żadnego sensu.

W jaki sposób kurier dostarczy paczkę i gdzie, jeżeli nie podam danych punktu odbioru, tylko zamiast tego dane nadawcy?

Proszę zauważyć, że dane z pickup pojawiają się we wszystkich trzech miejscach, więc jeżeli zmienię je na dane nadawcy to na etykiecie nie mamy adresu odbioru.

**Comment by PrzemyslawLukanowski** [comment]
Pickup to miejsce nadania, dane odbiorcy to pole receiver.

**Comment by tztztztz** [comment]
Na pewno?

Przypominam,  że w danych pickup jest np. "pointId" - "Pickup point id. You can get it from order or directly from courier service." - czyli miejsce punktu odbioru takiego jak paczkomat albo jakiś kiosk.

Nie ma żadnego innego miejsca gdzie mogę określić ten punkt odbioru paczki przez klienta, więc co - do pickup mam wstawić dane NADAWCY i w tych danych umieścić / tej strukturze umieścić id punktu odbioru który sobie wybrał klient?

**Comment by tztztztz** [comment]
I przypominam jeszcze raz: te dane będą powtórzone 3 razy na etykiecie: dane NADAWCY.

Proszę mi napisać, skąd kurier będzie wiedział gdzie ma dostarczyć paczkę, skoro na etykiecie będą tylko dane nadawcy w 3 miejscach?

**Comment by tztztztz** [comment]
Dowodem na to jest przykładowa etykieta którą wstawiłem wyżej: 3 razy jest na etykiecie ul Hrubieszowska, a w danych JSON ta ulica występuje tylko w danych pickup, z tego wniosek że dane z pickup są kopiowane 3 razy na etykiecie.
