### ISSUE TITLE
Bad Request for Offer API

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5716]
Hi, let me know why I am getting this error:

API:

https://api.{environment}/sale/product-offers

REQUEST:
{"afterSalesServices":{"returnPolicy":{"id":"8757d063-c1dd-4d50-9254-884282ebab5e","name":"Test Return 2"},"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"}},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"cfbf12f5-602e-4057-97cb-9a2aa4ccd99c","name":"Test Delivery Price 1"}},"publication":{"startingAt":"2022-05-23T17:48:37Z","duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"VAT"},"messageToSellerSettings":{"mode":"HIDDEN"},"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_2"]}],"productSet":[{"product":{"parameters":[{"id":"10563","name":"Brand","valuesIds":["10563_904748"]},{"id":"54","name":"Size","valuesIds":["3806_407362"]},{"id":"451","name":"Color","valuesIds":["451_2048"],"values":["451_131072,451_524288"]},{"id":"3766","name":"Main Pattern","valuesIds":["3766_1"]},{"id":"202677","name":"Collar Type","valuesIds":["202677_212897"]},{"id":"6168","name":"Sleeve","valuesIds":["6168_1"]},{"id":"129012","name":"Cut","valuesIds":["129012_1"]},{"id":"201017","name":"Main Fabric","valuesIds":["201017_2317"]}],"name":"Testswapnil2","category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628b9c0b245489555964c9a9.jpg"]},"quantity":{"value":1}}],"name":"Testswapnil2","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>TESTSWAPNIL2<\/p>"}]}]},"category":{"id":"87873"},"images":["https:\/\/dmsmatrix.net\/direct\/images\/628b9c0b245489555964c9a9.jpg"],"sellingMode":{"format":"BUY_NOW","price":{"amount":"1.00","currency":"PLN"}},"stock":{"available":1,"unit":"UNIT"},"external":{"id":"TESTSWAPNIL2"}}

RESPONSE:
[
	'server_output' => 'HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 1c337ab2891ec99b
date: Mon, 23 May 2022 16:48:38 GMT
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
content-type: application/json
content-length: 181

{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}',
	'headers' => [
		'expires' => ' 0',
		'cache-control' => ' no-cache, no-store, max-age=0, must-revalidate',
		'x-xss-protection' => ' 1; mode=block',
		'pragma' => ' no-cache',
		'x-frame-options' => ' DENY',
		'trace-id' => ' 1c337ab2891ec99b',
		'date' => ' Mon, 23 May 2022 16:48:38 GMT',
		'x-content-type-options' => ' nosniff',
		'strict-transport-security' => ' max-age=31536000 ; includeSubDomains',
		'content-type' => ' application/json',
		'content-length' => ' 181'
	],
	'responseBody' => '{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}'
]

**Comment by PrzemyslawLukanowski** [comment]
You are using the PATCH /sale/product-offers/{offerID} method which allows you to modify the data of your offer. Please select specific fields you want to edit or retrieve offer data via GET /sale/product-offers/{offerID}, change the value of fields you want to edit, and send us the modified data via the PATCH method. More information about this method can be found in [our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-edit-an-offer). 
Also, please don't use our production environment for tests, you can do all types of operations on [Sandbox](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#test-environment).

**Comment by adityakokate** [comment]
Thanks for the reply.

But even for lesser fields, I am getting **BAD_REQUEST** error response.

url => https://api.allegro.pl/sale/product-offers/12196111349

postData => {"name":"Swapniltest3","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>SWAPNILTEST3<\/p>"}]}]},"sellingMode":{"price":{"amount":"1.00","currency":"PLN"}}}
output

Response:
[
'server_output' => 'HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: fd2fa9e6d585dd8b
date: Tue, 24 May 2022 11:12:52 GMT
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
content-type: application/json
content-length: 181

{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}',
	'headers' => [
		'expires' => ' 0',
		'cache-control' => ' no-cache, no-store, max-age=0, must-revalidate',
		'x-xss-protection' => ' 1; mode=block',
		'pragma' => ' no-cache',
		'x-frame-options' => ' DENY',
		'trace-id' => ' fd2fa9e6d585dd8b',
		'date' => ' Tue, 24 May 2022 11:12:52 GMT',
		'x-content-type-options' => ' nosniff',
		'strict-transport-security' => ' max-age=31536000 ; includeSubDomains',
		'content-type' => ' application/json',
		'content-length' => ' 181'
	],
	'responseBody' => '{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}'
]

**Comment by adityakokate** [comment]
{"name":"Swapniltest3","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>SWAPNILTEST3</p>"}]}]},"sellingMode":{"price":{"amount":"1.00","currency":"PLN"}}}

This is my postData/request body

**Comment by adityakokate** [comment]
url => https://api.allegro.pl/sale/product-offers/12196111349

Request Body or postData => {"name":"Test Title"}

Response =>
[
	'server_output' => 'HTTP/1.1 400 Bad Request
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 3b0c6cbcda4d9703
date: Tue, 24 May 2022 11:41:45 GMT
x-content-type-options: nosniff
strict-transport-security: max-age=31536000 ; includeSubDomains
content-type: application/json
content-length: 181

{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}',
	'headers' => [
		'expires' => ' 0',
		'cache-control' => ' no-cache, no-store, max-age=0, must-revalidate',
		'x-xss-protection' => ' 1; mode=block',
		'pragma' => ' no-cache',
		'x-frame-options' => ' DENY',
		'trace-id' => ' 3b0c6cbcda4d9703',
		'date' => ' Tue, 24 May 2022 11:41:45 GMT',
		'x-content-type-options' => ' nosniff',
		'strict-transport-security' => ' max-age=31536000 ; includeSubDomains',
		'content-type' => ' application/json',
		'content-length' => ' 181'
	],
	'responseBody' => '{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}'
]

**Comment by adityakokate** [comment]
Another request with error response:

"endpoint" : "PATCH https://api.allegro.pl/sale/product-offers/12196111349",
"request" : "{"sellingMode":{"price":{"amount":"1.00","currency":"PLN"}}}",
"headers" : "{"expires":" 0","cache-control":" no-cache, no-store, max-age=0, must-revalidate","x-xss-protection":" 1; mode=block","pragma":" no-cache","x-frame-options":" DENY","trace-id":" 68d190b962178567","date":" Tue, 24 May 2022 12:20:05 GMT","x-content-type-options":" nosniff","strict-transport-security":" max-age=31536000 ; includeSubDomains","content-type":" application/json","content-length":" 181"}",
"response" : "{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}]}",

**Comment by PrzemyslawLukanowski** [comment]
As you can see the problem is not with the JSON structure, because even for a simple payload you are receiving an error. The problem is with attaching the body to your request, it seems that it's not included properly. In our logs, we see information that confirms this is the source of the problem - "Required request body is missing". I suggest you verify your whole code connected with this request, not the structure of the payload itself. The JSON is valid, but your request doesn't contain it.

**Comment by PrzemyslawLukanowski** [comment]
Offer 12196890146 is connected with a product with ID f3c963a8-755b-45d1-beef-20a4b92c7014. This product includes "2(X)IST" as a Brand value. You can retrieve all the information about this particular product via GET /sale/products/f3c963a8-755b-45d1-beef-20a4b92c7014. A single product can be assigned to multiple offers from various sellers, so you cannot change the product parameters. What you can do is:
- [report incorrect product data i](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-report-incorrect-data-in-a-product)f you are sure some information are invalid;
- [search for a different product](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-search-for-products) from our catalog, or [create a new one.](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-assigned-to-a-product-that-is-not-in-our-database)
