### ISSUE TITLE
Niepoprawna wartość parametru

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5717]
Dzień dobry!

{'code': 'VALIDATION_ERROR', 'message': 'Niepoprawna wartość parametru Rodzaj (130210) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : "winylowa na flizelinie".', 'details': '', 'path': 'null', 'userMessage': 'Niepoprawna wartość parametru Rodzaj (130210) dla oferty z produktem. Prawidłowa wartość atrybutu (dla produktu) to : "winylowa na flizelinie".'}], 'warnings': [], 'validatedAt': '2022-05-24T07:09:37.909Z', 'offer_id': '12195423629', 'status_code': 200}

Mam pytanie o następującym charakterze. Dlaczego nie mogę wybrać innego parametra dla tego produktu?

flizelinowa czy samoprzylepna

"Rodzaj" tylko  "winylowa na flizelinie"
kod produktu ec7326c8-cc3b-4c81-ae94-5f92189db5e7
O ile rozumiem to fototapeta. Być może moglibyśmy ustawić inne tapety z inną wartością parametru "Rodzaj"

jednak wydaje się, że można wybrać ten typ parametru zamiast innego.
Proszę powiedzić, czy możemy zmienić ten typ ustawienia na inny i czy istnieją inne produkty fototapety, w których moglibyśmy ustawić inny rodzaj ustawienia?
Gdzie mogę znaleźć inne kody produktow fototapety?

**Comment by PrzemyslawLukanowski** [comment]
Twoja oferta 12195423629 jest połączona z produktem o ID ec7326c8-cc3b-4c81-ae94-5f92189db5e7. Jeśli skorzystasz z GET /sale/products/ec7326c8-cc3b-4c81-ae94-5f92189db5e7, zobaczysz dokładne dane tego produktu, w tym jego parametry. Tych danych nie możesz edytować, możesz jedynie [zgłosić błąd w produkcie,](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-zglosic-blad-w-produkcie) jeśli uważasz, że są błędne. W związku z tym, jeśli posiadasz ofertę połączoną z tym produktem, to próba edycji parametrów na **niezgodne z produktem**, zakończy się błędem. Możesz w takim razie:
 - [zgłosić błąd w danych produktu, jeśli uważasz, że jego dane są błędne](ttps://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-zglosic-blad-w-produkcie);
 - [przeszukać naszą bazę, aby odnaleźć inny produkt,](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-wyszukac-produkt) który spełni Twoje wymagania. Następnie możesz użyć jego ID lub EAN podczas [tworzenia](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA) lub [edycji](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-przypisac-produkt-do-oferty) nowej oferty;
 - [utworzyć nowy produkt](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-ktorego-nie-ma-w-naszej-bazie), jeśli produktu, który chcesz wystawić, nie ma jeszcze w naszej bazie, .

**Comment by sergeidebug** [comment]
dzieki!
