### ISSUE TITLE
User name from JWT cannot be empty

### ISSUE THREAD

**Issue by dawidof** [allegro/allegro-api#5718]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

• Stworzyłem applikacje z `grant-type: device_code`
<img width="1270" alt="Screenshot 2022-05-24 at 09 33 21" src="https://user-images.githubusercontent.com/1425756/169974964-8735d0f2-ac5e-41e0-b586-b14f3709e851.png">

• Dostałem token za pomocą `https://allegro.pl/auth/oauth/token`
https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#autoryzacja-aplikacji

dostaję dobrą odpowiedż
```
{"access_token"=>"eyJ...P4vBHKEQ", "token_type"=>"bearer", "expires_in"=>43199, "scope"=>"allegro:api:orders:read allegro:api:billing:read allegro:api:payments:read", "allegro_api"=>true, "jti"=>"ac1354b8...8262"}
```

• Robię request według dokumentacji
<img width="1562" alt="Screenshot 2022-05-24 at 09 35 33" src="https://user-images.githubusercontent.com/1425756/169975461-977bfe9a-5d38-48ff-8002-2540494d94c8.png">

```bash
curl -X GET 'https://api.allegro.pl/order/events' \
  -H 'Authorization: Bearer eyJh.....BHKEQ' \
  -H 'accept: application/vnd.allegro.public.v1+json'
=> {"errors":[{"code":"EMPTY_USER_ID","message":"User name from JWT cannot be empty","details":null,"path":"/order/events","userMessage":"User name from JWT cannot be empty"}]}
```

**Comment by PrzemyslawLukanowski** [comment]
Mimo tego, że stworzyłeś aplikację device-code, to posłużyłeś się autoryzacją typu client_credentials, która nie posiada kontekstu użytkownika. Taki token, po rozkodowaniu, nie posiada zapisanej w sobie wartości dla "user_name", dlatego też otrzymujesz błąd "`User name from JWT cannot be empty".` Wygeneruj proszę token w ramach autoryzacji device, o czym szerzej napisaliśmy [w tym fragmencie poradnika.](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow)

**Comment by dawidof** [comment]
@PrzemyslawLukanowski Dzięki, wszystko działa!
