### ISSUE TITLE
błąd An error has occurred przy zasobie  PUT /sale/offers/{offerId}

### ISSUE THREAD

**Issue by chaosjar** [allegro/allegro-api#572]
Witam,

Z czego może wynikać błąd:
object(stdClass)#24 (1) { ["errors"]=> array(1) { [0]=> object(stdClass)#26 (5) { ["code"]=> string(5) "ERROR" ["message"]=> string(21) "An error has occurred" ["details"]=> NULL ["path"]=> string(23) "/sale/offers/7547040651" ["userMessage"]=> NULL } } }

**Przy uzupełnianiu nowej oferty?

Tak wygląda mój kod php:**

    $this_headers = array('Host: allegro.pl',
                          'accept: application/vnd.allegro.beta.v1+json',
                          'content-type: application/vnd.allegro.beta.v1+json',
                          'Authorization: Bearer '. $sprawdz_pro['access_token']);       
    
    
    $this_link = 'https://api.allegro.pl/sale/offers/'.$sprawdz_pro_a['allegro_id'];
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $this_link);    
    curl_setopt($curl, CURLOPT_HTTPHEADER, $this_headers);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
    curl_setopt($curl, CURLOPT_POSTFIELDS, $dane);

Być może ktoś się już spotkał z takim problemem

**Comment by chaosjar** [comment]
Taki błąd może wynikać z błędnej struktury danych czy z zapytania? dzięki za pomoc

**Comment by KrzysztofLukanowski** [comment]
Najprawdopodobniej występuje błąd w zapytaniu do Allegro. Podeślij proszę pełen request w formacie json.

**Comment by chaosjar** [comment]
{
    "id": "7547139621",         
    "name": "Czajnik elektryczny WMF Kitchenminis 413140011",                
    "category": {
        "id": "67428"
    },
    "parameters": [{
                                        "id": "11323",
                                        "valuesIds": ["11323_1"], 
                                        "values": [],
                                        "rangeValue": null
                                    }],
    "ean": "4211129116244",


    "description": {
        "sections": [{
                            "items": [
                                {
                                    "type": "TEXT",
                                    "content": "<p>opis</p>"
                                },
                                {
                                    "type": "IMAGE",
                                    "url": "https://a.allegroimg.com/original/11eb96/805e0a1242c7bfab19239a014ada"
                                }
                            ]
                        
                    }]
    },
    "images": [{
                          "url": "https://a.allegroimg.com/original/11eb96/805e0a1242c7bfab19239a014ada"
                          },{
                          "url": "https://6.allegroimg.com/original/11dad8/78cd64cf4c55bef7c5717c56c8b6"
                          },{
                          "url": "https://3.allegroimg.com/original/11b34c/7676a613412aad0931c54d986da3"
                          },{
                          "url": "https://5.allegroimg.com/original/11e9f6/d874cdad4ead8a207884e58c1965"
                          },{
                          "url": "https://3.allegroimg.com/original/11e484/bab9e751413795cbd1423472d103"
                          }],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "314.10",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 12,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "INACTIVE",
    },
    "delivery": {
        "shippingRates": {
            "id": "937040a4-4d54-4e2b-9935-ee364e5e3ca4"
        },
        "handlingTime": "P4D"
    },
    "payments": {
        "invoice": "VAT"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "e267a46a-66e2-40f1-8c3d-52968d5e15c5"
        },
        "returnPolicy": {
            "id": "b5eefd4c-4033-4d62-b292-bb52852b37ea"
        },
        "warranty": {
            "id": "db278ade-fb52-4a2f-bec3-9de2a979833a"
        }
    },
    "location": {   
        "countryCode": "PL", 
        "province": "MAZOWIECKIE", 
        "city": "Warszawa",
        "postCode": "05-075"
    },
    "external": "413140011",

    "validation": {
        "errors": [],
        "validatedAt": "2018-09-05T00:35:57Z"
    },
    "createdAt": "2018-09-05T00:35:57Z",
    "updatedAt": "2018-09-05T00:35:57Z" 
}

**Comment by wwwfactory** [comment]
Dzień dobry 
Szanowni Państwo z Allegro 
Poprawcie błędy w tutorialu i nie będzie tego typu zgłoszeń :) Nie szkoda Wam czasu ? 

@chaosjar masz błąd w tym miejscu 
"external": "413140011",

odpowiedzi szukaj w ..... no własnie  - może niech Pan @KrzysztofLukanowski się wypowie w tej materii !

oj błędy błędy w podstawach ...

Pozdrawiamy WWWFACTORY

**Comment by chaosjar** [comment]
dzięki @wwwfactory

zmiana na "external": {"id":"413140011"}, nic nie dała, może być jeszcze jakaś przyczyna?

**Comment by chaosjar** [comment]
Dzięki panowie, wszystko działa
