### ISSUE TITLE
Integracja API nie działa w związku z przekazywaniem statusów paczek

### ISSUE THREAD

**Issue by ladnefelgi** [allegro/allegro-api#5721]
Witam.
Zakładam temat na prośbę suportu - integracja API nie działa w związku z przekazywaniem statusów paczek (na podstawie zamaskowanych adresów mailowych).

Szczegóły sprawy:
Prowadzimy sprzedaż przez Allegro oraz mamy sklep na Idosell. Wszystkie zamówienia są obsługiwane przez panel Idosell. Niedawno zaczęliśmy korzystać ze specjalnej integracji „Wysyłam z Allegro”, dzięki której możemy generować listy dla m.in. Allegro Kurier UPS. No i tu zaczynają się schody. Takie zamówienia mają w Allegro status przesyłki „W drodze”, natomiast w rzeczywistości zostały już odebrane przez klienta. W takim wypadki zamówienia mają niepoprawne statusy przesyłek i nie zliczają się do Smarta. Dostałem informację z suportu, że nie otrzymaliście statusów paczek od przewoźnika (przez rzekome przekazywanie niezamaskowanego adresu e-mail kupującego). Jednak z tego co widzimy w panelu Idosell korzystamy tylko z zamaskowanych adresów e-mail (dla poniższych przykładowych zamówień są to: edjhv6bei7+615973973@allegromail.pl oraz jsi8nhm0tt+4f49faba2@allegromail.pl).

Konto Allegro: ladnefelgi_pl

Przykładowe zamówienia:
• f4711671-d5bd-11ec-98eb-9fd7a899308b – dostarczone 05/18/2022 12:57 P.M.
• 1f7cca94-d5bd-11ec-8c34-7dd0924dd1f5 – dostarczone 05/19/2022 11:59 A.M.

**Comment by AureliuszBrussy** [comment]
Prosiłbym o wskazanie przykładowych UUID komend, w których zostały utworzone wspomniane przesyłki. UUID komend uzyskasz od supportu integracji. Pozwoli mi to dokładniej sprawdzić, czy przesyłki zostały utworzone prawidłowo.

**Comment by ladnefelgi** [comment]
Dział IT Idosell w dalszym ciągu analizuje temat

**Comment by AureliuszBrussy** [comment]
@ladnefelgi dziękuję za informację. Oczywiście sprawdzimy to gdy tylko otrzymamy niezbędne dane.

**Comment by ladnefelgi** [comment]
Witam, dostaliśmy odpowiedź od supportu:
"niestety, nie zapisujemy nigdzie w systemie UUID który generujemy, natomiast mamy w bazie identyfikatory zadań w allegro, które od nich otrzymaliśmy w zwrocie. Są to dla zamówień:
- 4a6a4860-6e97-e5eb-9a51-cecc63478f69
- 8880c236-a5da-6d0f-8a9a-8b86e2600087"

**Comment by ladnefelgi** [comment]
Czyli, co muszę zrobić, żeby przesyłki były zliczane do Smarta? Usunąć umowy własne z UPS? Podczas generowania przesyłki w Idosell nie mamy możliwości wybrania umowy.

**Comment by AureliuszBrussy** [comment]
@ladnefelgi nie musisz usuwać umowy własnej. Podczas generowania przesyłki powinieneś wybrać usługę Allegro UPS. Skontaktuj się z supportem Idosell, aby dowiedzieć się, jakie mają możliwości jeżeli chodzi o wybór usługi podczas generowania przesyłki. Listę wszystkich dostępnych usług dla konta można pobrać za pomocą [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices). W [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-uslug-dostawy) opisujemy to szerzej.
