### ISSUE TITLE
siatka wymiarowa

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5722]
![image](https://user-images.githubusercontent.com/95347292/170056615-09eb96d6-3385-49c0-845d-d5a37ec70fd2.png)
jak mogę przesłać wymiary przez API, aby były wypełnione jako siatka wymiarowa?

**Comment by PrzemyslawLukanowski** [comment]
Taki rodzaj oferty to tzw. oferta wielowariantowa, która składa się z utworzonych wcześniej ofert tego samego przedmiotu, ale połączonych według różnych wartości parametrów wariantujących. Czyli w tym przypadku oferty zostały połączone według parametrów "szerokość" i "wysokość". Więcej informacji na ten temat oraz instrukcję, jak utworzyć ofertę wielowariantową, znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo).

**Comment by sergeidebug** [comment]
dziękuję bardzo!
Wszystko jasne

**Comment by PrzemyslawLukanowski** [comment]
Tak, najpierw musisz utworzyć oferty i je aktywować. Przed tworzeniem oferty wielowariantowej zwróć uwagę, czy możesz tworzyć warianty na podstawie parametrów, które wskazujesz w "parameters". Tę informację otrzymasz w odpowiediz zasobu GET /sale/categories/{categoryId}/parameters, w polu `variantsAllowed`:
```

"parameters": [                             -- lista dostępnych parametrów dla
                                            wskazanej kategorii
    {
        "id": "11323",                      -- unikalny identyfikator parametru
        "name": "Stan",                     -- nazwa parametru
        "type": "dictionary",
        "required": true,
        "unit": null,
        "options": {
            "variantsAllowed": false,       -- informacja, czy parametr można  
                                            wykorzystać w wielowariantowości.
                                            dostępne są dwie wartości:
                                            true (tak) i false (nie).
            "variantsEqual": true           -- informacja, czy parametr we wszystkich
                                            wariantach ofert musi mieć tę samą wartość
                                            dostępne są dwie wartości:
                                            true (tak) i false (nie). Jeśli otrzymamy
                                            wartość true (tak) to wszystkie warianty
                                            oferty muszą mieć tą samą wartość w tym parametrze
        }
```
Następnie, kiedy tworzysz ofertę wielowariantową przez POST /sale/offer-variants, wygląda to odrobinę inaczej. Nie musisz przekazywać pola "szerokoscPattern", takie pole nie istnieje :) W tym miejscu przekazujesz tylko "colorPattern", jeśli łączysz oferty według koloru lub wzoru. W sekcji "parameters" natomiast przekazujesz ID parametrów, na podstawie których chcesz utworzyć ofertę wielowariantową, czyli powinno to wyglądać tak:

```
{
    "offers": [                                 
        {
            "id": "{ID_oferty_1}"                 
        },
        {
            "id": "{ID_oferty_2}"
        }
    ],
    "name": "Nazwa oferty wielowariantowej",                          
    "parameters": [                             
        {
            "id": "{ID parametru wysokość}"                    
        },
        {
            "id": "{ID parametru szerokość}"                       
        }
    ]
}
```

Zwróć uwagę na [ten przykład](https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo#kliknij-aby-zobaczyc-request) w poradniku i znajdujący się tam obrazek poniżej. W Twoim przypadku sytuacja będzie wyglądać bardzo podobnie, tyle że z innymi wartościami ID ofert i parametrów.

**Comment by sergeidebug** [comment]
![image](https://user-images.githubusercontent.com/95347292/171364639-007a40ca-4e7f-4662-bb7b-524b15e16344.png)
Chodzi mi o to, że nie mogę przełączyć się na inną opcję oferty, będąc na pierwszej opcji. Jak mogę zobaczyć ofertę w katalogu, aby móc się zmienić?
![image](https://user-images.githubusercontent.com/95347292/171364986-3fbcad0f-026c-4650-8839-2c6642dc5859.png)

**Comment by sergeidebug** [comment]
216577	Szerokość
216669	Wysokość
dla obu parametrów
options.variantsAllowed	True
options.variantsEqual False

**Comment by PrzemyslawLukanowski** [comment]
Czy możesz odświeżyć stronę oferty? Widzę, że powinieneś mieć taką możliwość:
<img width="1013" alt="Zrzut ekranu 2022-06-1 o 10 47 50" src="https://user-images.githubusercontent.com/51473661/171365650-7e828a42-be1a-478c-87ab-d218a16a4231.png">

**Comment by PrzemyslawLukanowski** [comment]
Oferty wielowariantowe wyświetlają się tylko w polskiej wersji językowej serwisu, dlatego jej nie widzisz u siebie.

**Comment by sergeidebug** [comment]
> Oferty wielowariantowe wyświetlają się tylko w polskiej wersji językowej serwisu, dlatego jej nie widzisz u siebie.

ooo teraz jasne!
Dziękuję!
Jeśli wychodzę z trybu incognito, widzę stos wymiarów. Teraz ok!
