### ISSUE TITLE
Refresh Token API

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5723]
Request:

[
	(int) 10002 => 'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=...&redirect_uri=https://dmsmatrix.net/users/login',
	(int) 19913 => true,
	(int) 52 => true,
	(int) 84 => (int) 2,
	(int) 10036 => 'POST',
	(int) 10023 => [
		(int) 0 => 'Authorization: Basic MGIzNjJkNjQxZTdjNGFkNzg2YzNjMWVkN2VlZjBiMDQ6MzNmTUE1YmdXVlM1dXY5UWJKcE45V1dObjBjRkhTY250eGtMdlZ2OG5uM3A5ZDh3NXNhN25HSEE2aGM5VEhxTg=='
	]
]

I randomly get **_false_** as response for above request of new refresh token...and on subsequent request I get valid response like follows:

`{"access_token":"...,"token_type":"bearer","refresh_token":"...,"expires_in":43199,"scope":"allegro:api:orders:read allegro:api:profile:write allegro:api:sale:offers:write allegro:api:billing:read allegro:api:campaigns allegro:api:disputes allegro:api:sale:offers:read allegro:api:bids allegro:api:orders:write allegro:api:ads allegro:api:payments:write allegro:api:sale:settings:write allegro:api:profile:read allegro:api:ratings allegro:api:sale:settings:read allegro:api:payments:read allegro:api:messaging","allegro_api":true,"jti":"53fa58bc-a96f-4519-880f-6c1d2c1b29ca"}`

**Comment by PrzemyslawLukanowski** [comment]
What do you mean by "false" response? What exactly is the message from our API? In our logs, I see that you used this token at 16:59:32.448 (UTC+1) and we correctly returned new pairs of tokens. Then you tried to use again the same refresh token at  17:10:49.443 and 20:20:05.761 and as a result, we returned an error in the response. 
Refresh tokens are valid for 60 seconds after the first use, so if you have some problems with an interrupted connection you can retry to refresh the token with the same refresh token.

**Comment by adityakokate** [comment]
Why it's taking 30 seconds if I run authorization API from my code file and get blank response where else takes one second from postman and gets result.

Code:
$curl = curl_init();
curl_setopt_array($curl, array(
	CURLOPT_URL => 'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMDIyNDI0MzIiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6cmVhZCIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZSwiYXRpIjoiNDNjYzViNjctZjYyNS00NDI2LTliYWEtYTY2ZWZjNTE4N2E4IiwiZXhwIjoxNjYxNDIyOTQwLCJqdGkiOiI3ODU5MTJmMi0yZTcxLTQ2NTEtOWU1YS1lYmVlMjdhZDhkZjgiLCJjbGllbnRfaWQiOiIwYjM2MmQ2NDFlN2M0YWQ3ODZjM2MxZWQ3ZWVmMGIwNCJ9.rAI9y0uMuxqKd2TW4vd17tA4-tHLchtniEWP62YxFwDHpdxSwJo3yfxcuERmbk5kZMTmlo3NKF9osCMck4HZgDV0F0VXhMCHXWMCCObiBYGhuv8_MPnTNCCMq0QEcROlLuWx9zVCbevAF3D7cDFJkG3RhPU1B5uK07PW6_g1G1CuLCbs03IzV16K8p33zqA6Z_ToShd6CzPP_lmCPZ509YW5-YfIKJmS4oBVrRtvtXtfZrg0FW6przl7ybOaAHUXpH6BzAtlud9QDciMupeqk3bnsyievrEXnESJWAFrhSzgRyUiiNwU8Oe_YvJGm-LgHPaucCZkNwfBJle2aQe2Xw&redirect_uri=https://dmsmatrix.net/users/login',
	CURLOPT_RETURNTRANSFER => true,			
	CURLOPT_ENCODING => '',
	CURLOPT_MAXREDIRS => 10,
	CURLOPT_TIMEOUT => 0,
	CURLOPT_FOLLOWLOCATION => true,			
	CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,			
	CURLOPT_CUSTOMREQUEST => 'POST',			
	CURLOPT_HTTPHEADER => array(
		'Authorization: Basic MGIzNjJkNjQxZTdjNGFkNzg2YzNjMWVkN2VlZjBiMDQ6MzNmTUE1YmdXVlM1dXY5UWJKcE45V1dObjBjRkhTY250eGtMdlZ2OG5uM3A5ZDh3NXNhN25HSEE2aGM5VEhxTg=='
	)
));
$response = curl_exec($curl);
curl_close($curl);

**Comment by PrzemyslawLukanowski** [comment]
Please send us your IP address via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=642179d4-cc63-4c9e-8eea-7371effcc5cd&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a). Add information that the data refers to the #5723 GitHub thread. Your IP address may have been blocked because earlier you generated a large number of requests that ended with the error „Invalid refresh token”. We will check it.
Otherwise, the source of the problem may not be connected with our API, but for example with your network, firewall, etc.

**Comment by adityakokate** [comment]
Sent IP addresses using [contact form](https://allegro.pl/pomoc/kontakt?kategoria=642179d4-cc63-4c9e-8eea-7371effcc5cd&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a). Please do the needful ASAP. Also, I request you not to block our IP addresses for next couple of days as we are in load testing phase right now.
