### ISSUE TITLE
500 : GET https://api.allegro.pl.allegrosandbox.pl/sale/offers

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#5724]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Cześć, dziś przestało działać - jak poniżej
GET https://api.allegro.pl.allegrosandbox.pl/sale/offers?publication.status=ACTIVE&sellingMode.format=BUY_NOW&limit=1000&offset=0 HTTP/1.1

HTTP/1.1 500 Internal Server Error
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: da3dd786abf37f77
date: Tue, 24 May 2022 15:46:03 GMT
x-content-type-options: nosniff
content-type: application/json; charset=utf-8
content-length: 185
connection: close

{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie i jednocześnie potwierdzam, że wczoraj, w godzinach popołudniowo-wieczornych, wystapiły problemy na Sandboxie, które skutkowały odpowiedzią 500. Sytuacja ustąpiła ok. godziny 21, aktualnie problem nie powinien już występować. Przepraszam za niedogodności.

**Comment by rtnet-pl** [comment]
Dzięki, działa
