### ISSUE TITLE
opłaty za przesyłki Allegro Smart

### ISSUE THREAD

**Issue by Mihalis76** [allegro/allegro-api#5725]
Czy jest jakiś sposób na pobranie opłaty za przesyłki Allegro Smart?
Chodzi o te stawki:
https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/w-jaki-sposob-rozliczamy-przesylki-w-ramach-allegro-smart-z8DO2O2XVsA

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
Opłatę za przesyłkę Allegro Smart! w ramach danego zamówienia możesz pobrać za pomocą [GET /billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries). W polu type.id zwrócimy wtedy jedną z wartości: HB1, HB2, HB3, itd. (w zależności od przewoźnika), a w polu order.id numer zamówienia powiązany z tą opłatą. 
Zbiór wszystkich operacji billingowych w ramach tego zasobu znajdziesz w odpowiedzi [GET /billing/billing-type](https://developer.allegro.pl/documentation/#operation/getBillingTypes).

**Comment by Mihalis76** [comment]
Dzięki za pomoc, ale to mi nie pomoże. 
Potrzebuję tą wartość żeby oszacować koszty oferty i muszę ją mieć zanim zostanie złożone zamówienie, albo w ofercie, albo taką tabelkę - jaka jest pod przesłanym linkiem, że np. "Allegro Punkty Poczta, Orlen, Żabka, Ruch" <80.00 PLN to opłata 0.99. Wtedy sobie porównam jakie oferta ma opcje przesyłki i dla każdej obliczę koszt.

**Comment by PrzemyslawLukanowski** [comment]
Niestety, ale nie zwracamy tych informacji w API w takiej formie, jak w załączonym artykule.
