### ISSUE TITLE
Zamawianie podjazdu kuriera a wiele firm kurierskich

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5726]
Witam,

chciałbym dowiedzieć się jednej rzeczy. Gdy zamawia się podjazd kuriera przez API, to dotyczy on jedynie firmy, którą paczka jest wysyłana? Czy powinienem dla każdej firmy kurierskiej tworzyć osobne zamówienie podjazdu kuriera? 

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Nie, nie musisz wysyłać osobnych komend odbioru dla przesyłek z różnych firm kurierskich. Możesz to zrobić zbiorczo w jednej komendzie.
