### ISSUE TITLE
Nazwa firmy odbiorcy jest za długa - Poczta Polska. Zbyt restrykcyjny limit?

### ISSUE THREAD

**Issue by mmodrzejewski** [allegro/allegro-api#5727]
Dzień dobry

Jeden z klientów naszych systemów zwrócił nam uwagę na następujący problem przy generowaniu przesyłek, w ramach integracji z Allegro Poczta Polska:
API Allegro zwraca błąd: "Nazwa firmy odbiorcy jest za długa" już przy przekroczeniu 30 znaków, tymczasem w API Poczty Polskiej taki niski limit nie występuje (jest on dużo wyższy, sprawdziłem przed chwilą na 35 znakowej nazwie - przesyłka się wygenerowała, a i pełna nazwa się pojawiła na etykiecie!).

pozdrawiam
Marek Modrzejewski

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku jesteśmy ograniczeni limitami dla konkretnych pól ze strony przewoźnika. Maksymalna długość dla `receiver.company` to 30, a dla `receiver.name` 60.

**Comment by mmodrzejewski** [comment]
Jest tak, jak napisałem wyżej - limit się nie zgadza z tym, na co pozwala  Poczta Polska w swoim API :)
Czy możecie to zweryfikować w praktyce?

**Comment by PrzemyslawLukanowski** [comment]
Czy jesteś pewny, że pole, które uzupełniasz w Elektronicznym Nadawcy, to nie "Nazwa"? Dla tego pola przez WzA możesz prowadzić większą liczbę znaków - 60. Sprawdziłem instrukcję na stronie PP i nie widzę w niej osobnego pola dla nazwy firmy adresata.
<img width="487" alt="Zrzut ekranu 2022-05-26 o 08 59 00" src="https://user-images.githubusercontent.com/51473661/170435132-225e4c90-f51a-4fcf-b0f4-9c74ab770ccf.png">

**Comment by PrzemyslawLukanowski** [comment]
Sprawdziłem również ich dokumentację API i tutaj również występuje "nazwa":
<img width="775" alt="Zrzut ekranu 2022-05-26 o 09 03 24" src="https://user-images.githubusercontent.com/51473661/170435890-b2ebd053-743f-4fe6-bb98-4c44b1ba060e.png">

**Comment by mmodrzejewski** [comment]
Rzeczywiście, nie ma w API dedykowanego pola dla firmy.
Z tym, że są dwa pola nazwa w API Poczty Polskiej, więc teoretycznie nie powinno się narzucać sztucznego ograniczenia 30 znaków na jedno z nich, a wyliczać sumę...
