### ISSUE TITLE
WZA numer przewozowy

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5728]
Czy jest możliwość dostania z api docelowego numeru przewozowego przewoźnika dla przesyłek WZA? Czyli np. dla przesyłki typu Allegro Kurier DPD otrzymać nr przewozowy DPD?

**Comment by PrzemyslawLukanowski** [comment]
Numer listu przewozowego zwracamy w odpowiedzi [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails), w polu `items.waybill`.
