### ISSUE TITLE
Grupowanie draftów w wielowariant

### ISSUE THREAD

**Issue by adampajak** [allegro/allegro-api#573]
Czy jest możliwe zgrupowanie kilku ofert w wielowariant po rozmiarze (s,m,l,xl) w przypadku gdy jedna z ofert (rozmiaru) nie jest jeszcze aktywna (czyli jest w drafcie jako INACTIVE)?

**Comment by KrzysztofLukanowski** [comment]
Nie ma takiej możliwości. Oferta powinna być aktywna.
