### ISSUE TITLE
Token, Autoryzacja, Blokada

### ISSUE THREAD

**Issue by Vortexium** [allegro/allegro-api#5730]
Stworzyłem program CRM, która ma obsługiwać wiele kont allegro.
Przy dodawaniu nowego konta allegro do programu, według instrukcji jest wykonywana autoryzacja typu Device Flow.
Następnie w programie jest otwierana przeglądarka Chromium, w której otwierany jest link z verification_uri_complete.
Po pomyślnym zalogowaniu przez użytkownika na jego konto, należy kliknąć przycisk "Pobierz token", który pobiera token. Po pobraniu tokenu,  klikany jest przycisk "Zapisz", który zapisuje te dane do bazy.
Teraz dostaję informację, że dostęp został zablokowany.
![allegro](https://user-images.githubusercontent.com/96519683/170462972-0718ff5b-2e7b-4155-b723-2f963f3ed14d.JPG)
Wcześniej dodane było około 6 kont allegro. Musi upłynąć co najmniej 15 minut pomiędzy synchronizacjami poszczególnych kont, ale jeśli ten warunek jest spełniony dla wszystkich 6 kont - wtedy wszystkie konta są synchronizowane natychmiast, bez przerw pomiędzy kontami. Czy problemem jest zbyt szybkie odpytywanie o wątki wiadomości z tych kont? Jeśli tak to jaki byłby optymalny czas pomiędzy różnymi kontami allegro? W jaki sposób odblokować ten dostęp do API?

**Comment by AureliuszBrussy** [comment]
Zweryfikuję dokładniej sytuację, proszę jednak, abyś przekazał adres IP oraz ID z wiadomości poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). W treści wiadomości wskaż proszę numer wątku na GitHubie: #5730.

**Comment by javaguru-pl** [comment]
Witam, od wczoraj wieczorem mamy podobny problem co kolega powyżej. Nasz serwer został zablokowany i autoryzacja kont Allegro naszych klientów często zgłasza błędy. Proszę o szybkie odblokowanie. Nasze adresy IP:
37.28.156.94
5.133.12.36-39
Z góry dziękuję za pomoc.

**Comment by javaguru-pl** [comment]
Wysłałem też wiadomość przez formularz wskazany przez p. Aureliusza.

**Comment by AureliuszBrussy** [comment]
Dziękuję @Vortexium @javaguru-pl - sprawdzimy to. Wrócę z informacją.

**Comment by javaguru-pl** [comment]
Bardzo dziękuję Panie Aureliuszu. Dodam tylko że od ok. godz. 11:40 - nasza aplikacja nawet nie może się zalogować na już zautoryzowane konta klientów, a tym samym nie możemy zrealizować żadnego requestu API. Cała aplikacja jest zatrzymana już ponad 2 godziny. Bardzo proszę o szybką interwencję.

**Comment by AureliuszBrussy** [comment]
@javaguru-pl wrócę z informacją gdy tylko coś ustalimy.

**Comment by javaguru-pl** [comment]
Pani Aureliuszu, z tego co widzę to problem został już rozwiązany. API znów działa prawidłowo. Bardzo Państwu dziękuję za szybką reakcję i pomoc;)

**Comment by AureliuszBrussy** [comment]
@javaguru-pl blokady były związane ze zbyt dużą liczbą nowo nawiązywanych połączeń TCP na https://allegro.pl/auth/oauth/token. Aby uniknąć blokady, najlepiej, jeżeli aplikacja re-używa połączeń TCP oraz zwracała uwagę na błędy o status 400.

Jeżeli chodzi o Twój przypadek @Vortexium - niestety nie jestem w stanie wskazać powodu blokady. Proszę, daj znać, gdy sytuacja się powtórzy - sprawdzimy to ponownie.

**Comment by Vortexium** [comment]
Jasne, dziękuję za pomoc. W razie czego powiadomię.

**Comment by autornet** [comment]
Podłączę się pod temat. Od tygodnia są problemy z autoryzacją kont klienta. Komunikat jak poniżej:
You have been blocked.
Why this blocking? Something about the behaviour of the browser has caught our attention.

There are various possible explanations for this:
  you are browsing and clicking at a speed much faster than expected of a human being
  something is preventing Javascript from working on your computer
  there is a robot on the same network (IP 194.49.104.153) as you If something does not work please let us know.
ID: 17d55deb-e643-e5d5-fd89-f8d70f9bd22e

**Comment by AureliuszBrussy** [comment]
@autornet czy blokada występuje aktualnie? Jeżeli nie - kiedy mniej więcej występowała ostatnio?

**Comment by autornet** [comment]
> 

jezeli mówimy o tym komunikacie który Panu przesłałem to nie ma blokady , ostatnio chyba w piatek

**Comment by AureliuszBrussy** [comment]
@autornet prosiłbym o informację, gdy znowu problem wystąpi - prosiłbym wtedy o wskazanie mniej więcej czasu wystąpienia problemów. Sprawdzimy to.
