### ISSUE TITLE
PUT parcel-management/parcel-create-commands/{commandId}

### ISSUE THREAD

**Issue by anaxagore78** [allegro/allegro-api#5732]
czy coś sie zmieniło w nazewnictwie dostepnych opcji wysyłki zwracanych przez parcel-management/delivery-services ?
Klient w zamówieniu b8894fd0-dd0e-11ec-af3d-478bda195b92 wybrał metodę wysyłki 'Allegro One Box', 

Lista zwracana przez parcel-management/delivery-services zawiera między innymi: 

- Allegro One Punkt (One Kurier),
- Allegro One Box (One Kurier), 
- Allegro One (UPS),

która z nich powinna być wybrana żeby utworzyć przesyłkę? Przy wyborze Allegro One Box (One Kurier) otrzymuje komunikat błędu 
"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"
Problem pojawia się też przy innych zamówieniach np 8c9d3220-dce0-11ec-96f9-478bda195b92

**Comment by PrzemyslawLukanowski** [comment]
Allegro One to od wczoraj Allegro One (UPS), pojawilły się także dwa nowe serwisy: Allegro One Box (One Kurier) i Allegro One Punkt (One Kurier) w związku z udostępnieniem całkiem nowych metod realizowanych przez nowego przewoźnika: One Kurier. Dla metody dostawy ze wskazanego zamówienia musisz wybrać serwis Allegro One (UPS). 

Poniżej przesyłam pełne rozróżnienie metod dostawy na serwis:

- Metoda dostawy: Allegro One Punkt (UPS)
  Serwis: Allegro One (UPS)
- Metoda dostawy: Allegro One Box (UPS)
   Serwis: Allegro One (UPS)
- Metoda dostawy: Allegro One Punkt (One Kurier)
   Serwis: Allegro One Punkt (One Kurier) (na TEST: Allegro One Punkt (One Kurier) - dostawa jutro)
- Metoda dostawy: Allegro One Box (One Kurier)
   Serwis:Allegro One Box (One Kurier) (na TEST: Allegro One Box (One Kurier) - dostawa jutro)
- Metoda dostawy: Allegro One Kurier - dostawa dzisiaj
   Serwis: Allegro One Kurier
- Metoda dostawy: Allegro One Kurier - dostawa jutro
   Serwis: Allegro One Kurier
Metody z dopiskiem (do 01.07.2022) oraz pobraniowe NIE SĄ obsługiwane w WzA.

**Comment by kulisz** [comment]
@PrzemyslawLukanowski proponuje dodać do odpowiedzi w parcel-management/delivery-services przy każdym delivery service odpowiadające mu id z /sale/delivery-methods tak aby można było wykorzystując id dostawy z zamówienia sobie odrazu pobrać odpowiednią wartość do tworzenia przesyłki.

Dzięki temu wcześniej stworzone integracje nadal będą działać bo nie będzie się wysypać przygotowane wcześniej mapowanie(bo już nie będzie potrzebne), a Wy będziecie mogli sobie żonglować nazwami itd.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za tę sugestię, przekazuję ją do zespołu odpowiedzialnego za tę usługę.

**Comment by anaxagore78** [comment]
> @PrzemyslawLukanowski proponuje dodać do odpowiedzi w parcel-management/delivery-services przy każdym delivery service odpowiadające mu id z /sale/delivery-methods tak aby można było wykorzystując id dostawy z zamówienia sobie odrazu pobrać odpowiednią wartość do tworzenia przesyłki.
> 
> Dzięki temu wcześniej stworzone integracje nadal będą działać bo nie będzie się wysypać przygotowane wcześniej mapowanie(bo już nie będzie potrzebne), a Wy będziecie mogli sobie żonglować nazwami itd.

Dokładnie to samo miałem pisać :)
