### ISSUE TITLE
Authorization API - Connection Time Out

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5733]
Hi, why it's taking almost 30 seconds if I run authorization API from my code file as below and also get blank curl_exec result and "Failed to connect to allegro.pl port 443: Connection timed out" as curl_error, whereas the same code gives me a valid tokens result in within two seconds using Postman APP.

Code Snippet:
$curl = curl_init();
curl_setopt_array($curl, array(
CURLOPT_URL => 'https://allegro.pl/auth/oauth/token?grant_type=refresh_token&refresh_token=..tHLchtniEWP62YxFwDHpdxSwJo3yfxcuERmbk5kZMTmlo3NKF9osCMck4HZgDV0F0VXhMCHXWMCCObiBYGhuv8_MPnTNCCMq0QEcROlLuWx9zVCbevAF3D7cDFJkG3RhPU1B5uK07PW6_g1G1CuLCbs03IzV16K8p33zqA6Z_ToShd6CzPP_lmCPZ509YW5-YfIKJmS4oBVrRtvtXtfZrg0FW6przl7ybOaAHUXpH6BzAtlud9QDciMupeqk3bnsyievrEXnESJWAFrhSzgRyUiiNwU8Oe_YvJGm-LgHPaucCZkNwfBJle2aQe2Xw&redirect_uri=https://dmsmatrix.net/users/login',
CURLOPT_RETURNTRANSFER => true,
CURLOPT_ENCODING => '',
CURLOPT_MAXREDIRS => 10,
CURLOPT_TIMEOUT => 0,
CURLOPT_FOLLOWLOCATION => true,
CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
CURLOPT_CUSTOMREQUEST => 'POST',
CURLOPT_HTTPHEADER => array(
'Authorization: Basic MGIzNjJkNjQxZTdjNGFkNzg2YzNjMWVkN2VlZjBiMDQ6MzNmTUE1YmdXVlM1dXY5UWJKcE45V1dObjBjRkhTY250eGtMdlZ2OG5uM3A5ZDh3NXNhN25HSEE2aGM5VEhxTg=='
)
));
$response = curl_exec($curl);
curl_close($curl);

**Comment by PrzemyslawLukanowski** [comment]
I've responded in your previous thread - #5723.
