### ISSUE TITLE
Poprawka w dokumnentacji

### ISSUE THREAD

**Issue by KrzychuWalek** [allegro/allegro-api#5736]
:bulb: **Sugestia / Suggestions**

https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR

Punkt "4b. Równocześnie twoja aplikacja powinna zacząć odpytywać zasób"
Fragment:
`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code={device_code}'
jest mylący i prawdopodobnie nie działa o d lipca zeszłego roku.

Zgodnie z sugestią https://github.com/allegro/allegro-api/issues/4958#issuecomment-929120524 można zmienić na:

`grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code}'

Pozdrawiam, Krzysztof Wałek

**Comment by AureliuszBrussy** [comment]
Dziękuję za zwrócenie uwagi - poprawiłem to.

**Comment by hahyes** [comment]
> jest mylący i prawdopodobnie nie działa o d lipca zeszłego roku.

Zależy od technologii i klienta HTTP - u mnie działa.

**Comment by KrzychuWalek** [comment]
Rozumiem
Używam w php biblioteki GuzzleHttp\Client 5.0

W kwietniu 2021 adres z `%3A` chodził. Ten sam kod nie działał w zeszłym tygodniu. Kiedy przestał, tego nie wiem, nie miałem potrzeby odpalania go przez długi czas. Źródła nie były zmieniane (aktualizowane). Wnioskuję, że przed pojawieniem się błędu serwer Allegro dekodował parametr, a teraz nie dekoduje, bo jak inaczej wytłumaczyć zmiany.

Uważam, że dwukropek (:) nie musi być kodowany w odróżnieniu od na przykład &. Nie znam innych technologii niż php, ale wydaje mi się, że wpis `grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={device_code}' powinien być zawsze akceptowalny.
