### ISSUE TITLE
Pobranie informacji o monetach w ofercie

### ISSUE THREAD

**Issue by lukaszkrakowiak** [allegro/allegro-api#5737]
Dzień dobry,
Chciałbym pobrać informacje true/false o tym czy dana oferta posiada MONETY. Niestety w żadnym endpoincie nie widzę takiej informacji. Czy jest jakaś możliwość na pobranie tych informacji?

**Comment by AureliuszBrussy** [comment]
Nie, nie zwracamy takiej informacji o monetach w API. Jedyną ewentualną opcją jest [filtrowanie](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk#oznaczenia) parametrem **option=COINS** na zasobie [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Zwróć jednak uwagę, że dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) mają tylko [zweryfikowane aplikacje](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1).

**Comment by lukaszkrakowiak** [comment]
Aplikacja jest w trakcie tworzenia, także nie spełnia waszych warunków bycia zweryfikowaną aplikacją. W takim razie na ten moment nie będę mógł mieć tego w swojej aplikacji. Dziękuje za odpowiedź.
