### ISSUE TITLE
Rozróżnianie parametrów, które można edytować podczas tworzenia oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5739]
Proszę o naprowadzenie, po czym mam poznać, że dany parametr przy produktyzacji można edytować podczas wystawiana nowej oferty? Pobieram dane produktu za pomocą GET /sale/products/{productId}. Otrzymuję strukturę w której jest pole:

options":{"identifiesProduct":true}

Na podstawie tej struktury uzupełniam parametry dla danej kategorii.

W przypadku "identifiesProduct" o wartości TRUE, zakładałem, że danego parametru nie można edytować. To założenie sprawdzało się, aż trafiłem na produkcyjnym Allegro na produkt o kodzie EAN: 5903887805636. Przy tym produkcie parametr MARKA mamy dodany do produktu przy produktyzacji. W API ten parametr posiada "identifiesProduct" ustawiony na TRUE. Okazuje się, że wchodząc na Allegro i próbując ręcznie wystawić ofertę z takim produktem, pole MARKA możemy edytować.

Jest to o tyle dziwne, że przy tym samym produkcie posiadamy jeszcze 3 inne parametry, które posiadają "identifiesProduct" TRUE i tych parametrów nie można edytować, a czwarty parametr który również posiada TRUE można edytować. Proszę o pomoc

**Comment by PrzemyslawLukanowski** [comment]
Jeśli problem występuje na stronie internetowej, zgłoś go proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W przypadku API parametry odróżnisz właśnie za pomocą pola, o którym napisałeś. Edycja oferty z innym ID wartości parametru "Marka" nie będzie możliwa, zwrócimy w takim przypadku błąd `"Invalid parameter Brand (248135) value for offer with product. Value should be \"ADLER EUROPE\"."`

**Comment by mateuszcom** [comment]
W takim razie co mam traktować jako błąd? To, że na stronie Allegro w formularzu wystawiania ten parametr można edytować, czy to, że po stronie API tego parametru nie można zmieniać?

**Comment by PrzemyslawLukanowski** [comment]
Marka w tym przypadku jest parametrem, który identyfikuje produkt, zatem nie powinieneś móc wystawić oferty przez formularz z inną wartością tego parametru.
