### ISSUE TITLE
[REST] Rejestracja aplikacji

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#574]
Czy jeśli posiada się dwa konta na allegro to czy do każdego trzeba osobno rejestrować aplikacje z różnymi 
adresami zwrotnymi? W przykładowym wywołaniu zwrotnym nie jest przekazywana informacja o tym do jakiej aplikacji odnosi się zwracany kod: http://exemplary.redirect.uri/?code=pOPEy9Tq94aEss540azzC7xL6nCJDWto

**Comment by TomekKaczmarek** [comment]
@SlawomirMizerski Jeśli jesteś użytkownikiem aplikacji, to aplikacja nie powinna od Ciebie wymagać rejestracji. Jeśli jesteś developerem, aplikacje o różnych redirect uri musisz rejestrować osobno. Ale wszystkie możesz zarejestrować na jednym koncie. Użytkownik aplikacji będzie w procesie autoryzacji OAuth wyrażać zgodę, by Twoja aplikacja miała dostęp do jego danych.

Więcej na ten temat znajdziesz w [tym artykule](https://developer.allegro.pl/auth/).
