### ISSUE TITLE
Aktywacja konta allegrosandbox

### ISSUE THREAD

**Issue by Octanee** [allegro/allegro-api#5741]
Witam, 
mam problem z wystawianiem ofert na allegrosandbox. Mianowicie od kilku dni czekam na aktywację mojego konta która nie chce nastąpić. 
![allegrosandbox](https://user-images.githubusercontent.com/45128447/170971679-89ee8eb8-8837-4665-83d6-e7b77161edc2.png)
Email: leoctaneee@gmail.com
Z góry dziękuję za pomoc

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem w pełni Twoje konto.

**Comment by bswierzewski** [comment]
Witam czy ktoś jest w stanie mi odpowiedzieć dlaczego konto zostało negatywnie zweryfikowane?
I czy można jakoś poprawić dane by je w pełni aktywować czy trzeba utworzyć nowe konto?

![image](https://user-images.githubusercontent.com/33912764/171098113-09338c61-aad4-4320-8ac7-61c8c47be7be.png)

**Comment by PrzemyslawLukanowski** [comment]
Z tego co widzę, wybrałeś rodzaj konta jako "zwykły". Aby zmienić rodzaj konta na firmowe, skorzystaj ze strony https://allegro.pl.allegrosandbox.pl/biznes lub utwórz nowe konto i przy rejestracji wybierz opcję "Konto firma".

**Comment by bswierzewski** [comment]
Generalnie początkowo konto utworzyłem jako zwykłe, później w profilu konta zmieniłem na konto firma

![image](https://user-images.githubusercontent.com/33912764/171104337-5991c03a-38b5-4617-a739-eae09baa19a9.png)

**Comment by PrzemyslawLukanowski** [comment]
Twoje konto powinno już być w pełni aktywne.

**Comment by Hornir91** [comment]
Witam. Mam ten sam problem, mianowicie utworzyłem zwykłe konto w sandboxie, zmieniłem na firmowe i czekam na aktywację.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/53277040/171380639-56c2dc6d-199e-42db-9df8-d2be5f3676f0.png">

**Comment by PrzemyslawLukanowski** [comment]
@Hornir91 Twoje konto również powinno już być w pełni aktywne.

**Comment by Hornir91** [comment]
Dziękuję :). Wszystko działa jak należy.

**Comment by dmnk89** [comment]
czy aktywacja konta w sandbox jest w ogóle możliwa bez pisania na forum?

"Jeżeli masz problem z aktywacją konta, skontaktuj się z nami na [naszym forum](https://github.com/allegro/allegro-api/issues/1046)."

**Comment by dmnk89** [comment]
i prośba o aktywację dla loginu: `wiernicd`

**Comment by Lukasz-Zurek** [comment]
@dmnk89 Aktywowałem Twoje konto.

Aktywacja konta na Sandboxie jest możliwa bez konieczności pisania na forum. Przyznam jednak, ze czasami może wystąpić problem i konieczna jest nasza interwencja. Sprawę skonsultujemy jednak z zespołem odpowiedzialnym za proces aktywacji.

**Comment by dmnk89** [comment]
ok, dziękuję

**Comment by mkoniecz-unity** [comment]
Witam. Ja również mam ten problem, utworzyłem w sandboxie konto firmowe i czekam na aktywację. Proszę o aktywację konta `AlleRavenTest`

**Comment by MaciejFrackowiak** [comment]
@mkoniecz-unity Konto jest już aktywne.

**Comment by mkoniecz-unity** [comment]
@MaciejFrackowiak Konto działa poprawnie, dziękuję za pomoc

**Comment by yohadams** [comment]
@MaciejFrackowiak od paru dni wiszę na aktywacji konta prośba o aktywację email: yohadams@gmail.com

**Comment by MaciejFrackowiak** [comment]
@yohadams Sprawdzę sytuację i wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@yohadams Niestety, nie mamy możliwości aktywacji wskazanego konta. Zmuszony jestem Ciebie prosić o założenie nowego, najlepiej w formie jednoosobowej działalności gospodarczej.

**Comment by yohadams** [comment]
@MaciejFrackowiak to mam nadzieje że te konto uda się aktywować :) - leonard.armanowski@gmail.com

**Comment by MaciejFrackowiak** [comment]
@yohadams Tym razem obyło się bez przeszkód - konto aktywowane!

**Comment by MaciejFrackowiak** [comment]
@rtarnowskii Konto jest już aktywne.

**Comment by rtarnowskii** [comment]
@MaciejFrackowiak  dziękuję za ostatnie :) Poproszę jeszcze o aktywację konta `pcoutlet-sandbox`

**Comment by Lukasz-Zurek** [comment]
@rtarnowskii Aktywowałem wskazane konto.
