### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5742]
Proszę powiedziec, bo mam wrażenie, że nie do końca rozumiem.
Kiedy dodaję produkty, jak mam zrozumieć, który produkt powinien być do nich przypisany? Gdzie powinien znajdować się kod tego produktu?
Rozumiem, że są kategorie. Na przykład tapety i obrazy. Kategorie mają swoje własne opcje. Również produkty w tych kategoriach mają swoje własne parametry. Ale jak uzyskać listę opcji produktu w kategorii. Jak mogę zrozumieć, który produkt lepiej przypisać? Dokładniej, przypisać link do oferty.

**Comment by sergeidebug** [comment]
2de4b39f-1577-46b1-93cf-1f63b794d85d
e6b0a3fb-8c4d-4da5-88f7-677607beead0
8bad93c6-d82e-4466-add5-73be82c6c8e0

oto trzy różne kody dla zasadniczo tego samego produktu. To są nasze tapety.

**Comment by PrzemyslawLukanowski** [comment]
Postaram się odpowiedzieć, chociaż nie jestem przekonany, czy dobrze rozumiem Twoje pytania. 
Jeśli korzystasz z POST /sale/product-offers, to informacje o produkcie - jego parametry, opis, zdjęcia, etc. - przekazujesz w sekcji produktowej `productSet.product.` Na tej podstawie albo:

-  utworzymy nowy produkt. W takiej sytuacji w odpowiedzi, w polu `productSet.product.publication.status` zwrócimy wartość `PROPOSED`.
- na podstawie wartości parametrów, które identyfikują dany produkt, znajdziemy produkt w naszym katalogu i przypiszemy go do oferty. W takiej sytuacji w odpowiedzi, w polu `productSet.product.publication.status` zwrócimy wartość `LISTED`.

ID produktu, którego przykład wkleiłeś powyżej, otrzymasz w obu przypadkach w polu `productSet.product.id`. 
Oferta, którą utworzyłeś w ten sposób, posiada od razu przypisany produkt, dlatego nie musisz tego już robić.

> Ale jak uzyskać listę opcji produktu w kategorii. Jak mogę zrozumieć, który produkt lepiej przypisać? 

Nie do końca rozumiem, co masz na myśli przez "listę opcji produktu w kategorii". Czy mógłbyś to rozwinąć? To Ty masz największą wiedzę co do produktu, którego ofertę sprzedaży chcesz wystawić, dlatego decyzja należy do Ciebie, jaki produkt przypisać do oferty.

> 2de4b39f-1577-46b1-93cf-1f63b794d85d
> e6b0a3fb-8c4d-4da5-88f7-677607beead0
> 8bad93c6-d82e-4466-add5-73be82c6c8e0
> 
> oto trzy różne kody dla zasadniczo tego samego produktu. To są nasze tapety.

Nie mogę się zgodzić, że jest to ten sam produkt. Każdy z nich zawiera zarówno inny zestaw parametrów, jak i inne zdjęcia, to są różne produkty.

Jeśli zatem wystawiasz oferty za pomocą POST /sale/product-offers i chcesz, aby oferta byłą połączona z pierwszym produktem, wskaż w sekcji `productSet.product.id `wartość 2de4b39f-1577-46b1-93cf-1f63b794d85d. Na tej podstawie przypiszemy do oferty ten produkt i wszystkie jego parametry.

**Comment by sergeidebug** [comment]
Przepraszam, pierwszy produkt to obraz. I kolejne 2 tapety.
korzystam z POST /sale/offers
a żeby dodać ofertę do katalogu pomyślałem, że konieczne jest wskazanie kodu produktu.

Z odpowiedzi widzę, że mogę zastosować inną metodę 
POST /sale/product-offers
i przekazać niezbędne parametry, natomiast kod produktu zostanie wybrany niezależnie od istniejących lub zostanie utworzony nowy produkt. Tak?

Cieszę się jednak, że w metodzie 
POST /sale/offers
Nie mogę od razu publikować produktów i otrzymywać błędów walidacji.

o ile rozumiem, metoda 
POST /sale/product-offers
od razu publikuje ofertę

O ile rozumiem, na tym polega cała zasadnicza różnica w tych metodach.

Czy mogę również skorzystać z tej metody
POST /sale/offers
bez publikowania kodów produktów z nadzieją, że zostaną one uzupełnione automatycznie na podstawie parametrów?!

**Comment by PrzemyslawLukanowski** [comment]
> i przekazać niezbędne parametry, natomiast kod produktu zostanie wybrany niezależnie od istniejących lub zostanie utworzony nowy produkt. Tak?

Dokładnie tak.


> od razu publikuje ofertę
> 
> O ile rozumiem, na tym polega cała zasadnicza różnica w tych metodach.

Nie tylko, za pomocą POST /sale/offers musisz uwzględnić w strukturze oferty, prócz ID produktu (rozumiem, że tę wartość masz na myśli przez kod produktu), także parametry tego produktu oraz musisz przekazać wartości dla wszystkich pól. Jeśli  skorzystasz z POST /sale/product-offers, to wystarczy, że wskażesz nam ID produktu (lub GTIN albo MPN, czyli numer katalogowy części), liczbę sztuk oraz cenę przedmiotu. Wszystkie pozostałe dane uzupełnimy automatycznie. Nie musisz także przesyłać zdjęć na nasz serwer, ponieważ mogą pochodzić z zewnętrznego źródła. Więcej na ten temat przeczytasz [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA). Nic też nie stoi na przeszkodzie, aby za pomocą tego zasobu, utworzyć ofertę nieaktywną. Więcej na temat, jak przekazać własne wartości, znajdziesz [w tym fragmencie poradnika.](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-przekazac-wlasne-wartosci-w-zadaniu-).

> Czy mogę również skorzystać z tej metody
> POST /sale/offers
> bez publikowania kodów produktów z nadzieją, że zostaną one uzupełnione automatycznie na podstawie parametrów?!

Nie, w przypadku zasobów /sale/offers i /sale/offers/{offerId} takie operacje nie wykonają się automatycznie.

Zachęcam Cię, abyś zaimplementował w aplikacji zasoby /sale/product-offers. Zgodnie z [naszym newsem,](https://github.com/allegro/allegro-api/issues) zasoby /sale/offers i /sale/offers/{offerId} zostaną usunięte z początkiem 2024r.

**Comment by sergeidebug** [comment]
Wielkie dzięki!
Rozumiem
