### ISSUE TITLE
WzA: "Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"

### ISSUE THREAD

**Issue by ciaglok2** [allegro/allegro-api#5743]
Wywołuję GET na zasobie https://api.allegro.pl/parcel-management/parcel-create-commands/54ae6f81-aff9-4fdf-abb9-b204be0949de

W piątek jeszcze działało. Dziś przestało. Pozmienialiście nazwy metod (pobierane za pomocą /parcel-management/delivery-services) z Allegro One Punkt i Allegro One  Box na Allegro One Punkt (One Kurier) i Allegro One Box (One Kurier). 

Dostosowałem algorytm, ale  otrzymuję komunikat ja w tytule.

**Comment by ciaglok2** [comment]
Allegro One Box, więc serviceId 17692443

**Comment by Lukasz-Zurek** [comment]
@ciaglok2 Skorzystaj proszę z serviceId: 13105775.

**Comment by ciaglok2** [comment]
/parcel-management/delivery-services nie zwraca 13105775.

Pełna odpowiedź:

"{\"deliveryServices\":[{\"id\":10388701,\"service\":\"DPD\",\"name\":\"Allegro DPD\",\"owner\":\"ALLEGRO\",\"carrierId\":\"DPD\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":true,\"expressAvailable\":true},\"options\":[{\"name\":\"collectionUponDelivery\",\"description\":\"Przesyłka zwrotna. Po dostawie kurier odbiera kolejną przesyłkę od odbiorcy i dostarcza ją do nadawcy.\"},{\"name\":\"guarantee0930\",\"description\":\"Gwarancja dostawy do 9:30 / 10:30 (w zależności od lokalizacji).\"},{\"name\":\"guarantee1200\",\"description\":\"Gwarancja dostawy do 12:00.\"},{\"name\":\"guaranteeNextDay\",\"description\":\"Gwarancja dostawy w następnym dniu roboczym.\"},{\"name\":\"saturdayDelivery\",\"description\":\"Dostawa w sobotę.\"},{\"name\":\"additionalHandling\",\"description\":\"Paczka niestandardowa.\"},{\"name\":\"privateShipping\",\"description\":\"Doręczenie do osoby prywatnej.\"},{\"name\":\"sendingAtPoint\",\"description\":\"Nadanie paczki w punkcie.\"},{\"name\":\"personalDelivery\",\"description\":\"Dostawa bezpośrednio do odbiorcy.\"}]}},{\"id\":10388702,\"service\":\"UPS\",\"name\":\"Allegro UPS\",\"owner\":\"ALLEGRO\",\"carrierId\":\"UPS\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":true,\"expressAvailable\":false},\"options\":[{\"name\":\"returnOfDocuments\",\"description\":\"Zwróć dokumenty podpisane przez odbiorcę. Po dostawie odbiorca podpisuje dokumenty i zwraca je kurierowi.\"},{\"name\":\"additionalHandling\",\"description\":\"Paczka niestandardowa.\"},{\"name\":\"privateShipping\",\"description\":\"Doręczenie do osoby prywatnej.\"},{\"name\":\"sendingAtPoint\",\"description\":\"Nadanie paczki w punkcie.\"},{\"name\":\"upsSaver\",\"description\":\"UPS Express Saver.\"}]}},{\"id\":10388703,\"service\":\"POCZTA_POLSKA\",\"name\":\"Allegro Poczta\",\"owner\":\"ALLEGRO\",\"carrierId\":\"POCZTA_POLSKA\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[{\"name\":\"additionalHandling\",\"description\":\"Paczka niestandardowa.\"},{\"name\":\"fragile\",\"description\":\"Usługa 'ostrożnie'.\"},{\"name\":\"valuableShipment\",\"description\":\"Paczka wartościowa.\"},{\"name\":\"pocztaKurier24\",\"description\":\"Gwarancja, że paczki (wysłane do strefy A) zostaną dostarczone drugiego dnia po dacie nadania.\"},{\"name\":\"registeredCompanyLetter\",\"description\":\"Nadawanie przesyłek poleconych za potwierdzeniem odbioru.\"},{\"name\":\"deliveryConfirmation\",\"description\":\"Nadawca otrzyma formularz „Potwierdzenie doręczenia” z potwierdzeniem odbioru od odbiorcy.\"}]}},{\"id\":11202211,\"service\":\"ALLEGRO\",\"name\":\"Allegro One (UPS)\",\"owner\":\"ALLEGRO\",\"carrierId\":\"ALLEGRO\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[]}},{\"id\":11546967,\"service\":\"DPD\",\"name\":\"Allegro DPD za granicę\",\"owner\":\"ALLEGRO\",\"carrierId\":\"DPD\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[{\"name\":\"collectionUponDelivery\",\"description\":\"Przesyłka zwrotna. Po dostawie kurier odbiera kolejną przesyłkę od odbiorcy i dostarcza ją do nadawcy.\"},{\"name\":\"guarantee0930\",\"description\":\"Gwarancja dostawy do 9:30 / 10:30 (w zależności od lokalizacji).\"},{\"name\":\"guarantee1200\",\"description\":\"Gwarancja dostawy do 12:00.\"},{\"name\":\"guaranteeNextDay\",\"description\":\"Gwarancja dostawy w następnym dniu roboczym.\"},{\"name\":\"saturdayDelivery\",\"description\":\"Dostawa w sobotę.\"},{\"name\":\"additionalHandling\",\"description\":\"Paczka niestandardowa.\"},{\"name\":\"privateShipping\",\"description\":\"Doręczenie do osoby prywatnej.\"},{\"name\":\"sendingAtPoint\",\"description\":\"Nadanie paczki w punkcie.\"},{\"name\":\"personalDelivery\",\"description\":\"Dostawa bezpośrednio do odbiorcy.\"}]}},{\"id\":17692443,\"service\":\"ALLEGRO\",\"name\":\"Allegro One Box (One Kurier)\",\"owner\":\"ALLEGRO\",\"carrierId\":\"ALLEGRO\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[]}},{\"id\":17692444,\"service\":\"ALLEGRO\",\"name\":\"Allegro One Punkt (One Kurier)\",\"owner\":\"ALLEGRO\",\"carrierId\":\"ALLEGRO\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[]}},{\"id\":17761885,\"service\":\"X_PRESS_COURIERS\",\"name\":\"Allegro One Kurier\",\"owner\":\"ALLEGRO\",\"carrierId\":\"X_PRESS_COURIERS\",\"additionalServices\":{\"cashOnDelivery\":{\"available\":false,\"expressAvailable\":false},\"options\":[{\"name\":\"additionalHandling\",\"description\":\"Paczka niestandardowa.\"},{\"name\":\"sameDay1822\",\"description\":\"Dostawa tego samego dnia, co odbiór od nadawcy.\"},{\"name\":\"nextDay1822\",\"description\":\"Dostawa następnego dnia, po dniu odbioru od nadawcy.\"}]}}]}"

**Comment by hahyes** [comment]
Właśnie byłem w trakcie implementacji Allegro One i zweryfikowałem u siebie. Jest coś zdecydowanie z numerami usług nie tak, bo u mnie `Allegro One Box (One Kurier)` zwraca serviceId: `17631641`. Co tu się dzieje? Ten numer jest indywidualny czy o co chodzi?

Trace-Id: 363026b24eecb4af

**Comment by ciaglok2** [comment]
Tak, numery są inne dla każdego konta Allegro.

**Comment by hahyes** [comment]
> Tak, numery są inne dla każdego konta Allegro.

Ah, to mnie Pan uspokoił, dziękuję.

**Comment by Lukasz-Zurek** [comment]
@ciaglok2 Przepraszam za lekkie zamieszanie :) Pośpieszyłem się i podałem Tobie serviceId, a przecież dla każdego konta jest ono inne.

Klient wybrał metodę dostawy Allegro One Box, czyli powinieneś przekazać serviceId odpowiadające usłudze o nazwie: **Allegro One (UPS)**.

**Comment by ciaglok2** [comment]
Rozumiem, że dla Allegro One Punkt nazwa też zmieniła się na Allegro One (UPS). Dzięki.
