### ISSUE TITLE
API for Ship with Allegro

### ISSUE THREAD

**Issue by filip-frisbo** [allegro/allegro-api#5746]
Hello,

I run across [this](https://allegro.pl/for-sellers/ship-with-allegro-a-tool-for-dispatching-parcels-directly-from-your-account-zllo4Ax4aUq) article about "Ship with Allegro", stating that "you can send parcels directly from your Allegro account or via API".
I could not find in the article or in the allegro api documentation how a parcel can be shipped using this service.

Which routes can be used to implement it? 
Also, can we test this on the allegro sandbox?

Thanks!

**Comment by PrzemyslawLukanowski** [comment]
Hello, you can find all of the information about Ship with Allegro in [this tutorial](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV). And yes, you can test it on the Sandbox environment.
