### ISSUE TITLE
Summary report

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5747]
Witam!
Trochę zdezorientowany w dokumentacji. Potrzebuję pomocy.
Jak mogę uzyskać statystyki podsumowujące za pomocą interfejsu API? Na przykład
https://allegro.pl/moje-allegro/sprzedaz/allegro-analytics/podsumowanie

dzięki czemu można oszacować ilość sprzedaży na dzień, miesiąc, tydzień. Kwota zysku. Koszt reklamy. Liczba wniosków, liczba wniosków odrzuconych. I tak dalej

**Comment by Lukasz-Zurek** [comment]
Niestety w naszym publicznym API nie ma zasobu, za pośrednictwem którego mógłbyś sprawdzić wspomniane statystyki.

**Comment by Lukasz-Zurek** [comment]
Nie mamy tego typu funkcjonalności w naszym API. Zachęcam Cię jednak do opisania sugestii dotyczącej wdrożenia zasobu, który umożliwiłby pobieranie takich danych. Sugestię możesz przekazać w dedykowanym do tego miejscu, czyli [Discussions](https://github.com/allegro/allegro-api/discussions).
