### ISSUE TITLE
Wystawianie oferty czy są jakieś przerwy w działaniu?

### ISSUE THREAD

**Issue by slawomir-kudla** [allegro/allegro-api#575]
Ostatnio dostrzegłem że są przerwy w działaniu jak próbuję wystawić ofertę raz działa raz nie działa (ten sam skrypt) za każdym razem gdy wywołuje dostaje 201 jednak oferta nie zawsze się pojawia

wystawiam za pomocą
/sale/offer-publication-commands

Niby jest status BETA pytanie czy długo on jeszcze będzie?

**Comment by TomekKaczmarek** [comment]
@slawomir-kudla nie powinno byc takich sytuacji. Daj proszę znać, kiedy miała miejsce i podaj trace-Id niepoprawnych requestów. Problem dotyczy produkcji czy środowiska testowego?

**Comment by slawomir-kudla** [comment]
środowiska testowego chyba moje niedopatrzenie

czy kod 201 powinien być zwracany w przypadku gdy nic nie zostało utworzone?

krok 1:
/sale/offers <- wystawiam ofertę z błędami walidacyjnymi dostaję jego ID:6205616680 i kod 200 

krok 2: <- wystawiam ten id który dostałem przed chwilą dostaję kod 201 którego chyba nie powinienem dostać?
/sale/offer-publication-commands/D727DC64-DE05-4DE7-B4C1-F0198CFCF951

**Comment by TomekKaczmarek** [comment]
201 Created: Potwierdza utworzenie dokumentu za pomocą metody POST.

Dla publikacji otrzymasz zawsze 201, bo proces publikacji został utworzony. To czy poprawnie udało się wystawić ofertę sprawdzisz zasobami:

- GET na zasobie /sale/offer-publication-commands/{commandId}
- GET /sale/offer-publication-commands/{commandId}/tasks
