### ISSUE TITLE
Pobranie stanu przeysłki zwortu

### ISSUE THREAD

**Issue by konradkur** [allegro/allegro-api#5751]
Witam,

pobieram zwroty, i w parcels mają one swój numer waybill.
Pytanie czy na podstawie numeru waybill mogę ustalić status zwrotu paczki? Np., że doręczono?
czy to będzie ta metoda? https://developer.allegro.pl/documentation#operation/getParcelDetails

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy takiej funkcji. Metoda, którą linkujesz, jest związana z [Wysyłam z Allegro ](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV)i służy do pobrania szczegółów paczki, wcześniej utworzonej w ramach tej usługi.
