### ISSUE TITLE
primaryImage

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5752]
Nie widzę pola w dokumentacji
"primaryImage"
jednak jest zwracany w odpowiedziach, na przykład:
GET sale/offers

Czy mogę ustawić to pole dla jednego z obrazów i jak to zrobić poprawnie?

**Comment by Lukasz-Zurek** [comment]
Pole **"primaryImage"** zwracamy, gdy skorzystasz z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i jest to odpowiednik "miniaturki", czyli zdjęcia głównego w ofercie.

Jak wystawiasz ofertę np. poprzez [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT), pierwsze zdjęcie w tablicy **"images"** będzie jednocześnie pierwszym zdjęciem w ofercie (miniaturką). To zdjęcie będzie zwracane w polu **"primaryImage"**, w [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET).

**Comment by sergeidebug** [comment]
jasne, rozumiem, dzieki!

**Comment by sergeidebug** [comment]
Witam!
Z jakiegoś powodu, kiedy tylko wypełniam zdjęcia, 
**images**
pierwszy okazuje się być głównym, miniaturą. Jeśli jednak dodam jeden ze zdjęć do opisu
**description**
Obraz dodany do opisu staje się głównym.

Wcześniej dowiedziałem się już, że aby dodać obrazek do opisu, musi on być obecny w tabeli obrazków w polu images.
Jak więc określić główny obraz w tym przypadku?

```
'images': ['https://a.allegroimg.com/original/11eb01/392778b14316a6d1f0f745dfa888', 'https://a.allegroimg.com/original/11cd85/187e385644eaac1dbc0c53e71f0f', 'https://a.allegroimg.com/original/119fee/7a915a944163acd094db8f2e8bc3', 'https://a.allegroimg.com/original/1100a4/2c93cb84447896b3f4bcbbfac3dc', 'https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d'
'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p>Dlaczego warto wybraćć fototapety</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d'}]}]}

https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d stało się najważniejsze, ale powinno być
https://a.allegroimg.com/original/11eb01/392778b14316a6d1f0f745dfa888
```
offer id
12243181188

**Comment by sergeidebug** [comment]
![image](https://user-images.githubusercontent.com/95347292/172161094-5622c9a1-46aa-44f8-8700-20e613eb9d1a.png)
![image](https://user-images.githubusercontent.com/95347292/172161158-c39cfe42-0f5b-4690-8ddb-08de0ee62b37.png)
przepraszam, dodam zrzuty ekranu i usunę ofertę, żeby nie zamawiali, nie daj Boże

**Comment by sergeidebug** [comment]
Teraz próbowałem wysłać **description** do środka 
productSet
wcześniej **description**  był sam

Wynik jest taki sam. Główny obraz został zastąpiony

`'productSet': [{'product': {'category': {'id': '68631'}, 'parameters': [{'id': '224017', 'valuesIds': [], 'values': ['u48556'], 'rangeValue': None}, {'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None}, {'id': '215178', 'valuesIds': [], 'values': ['100'], 'rangeValue': None}, {'id': '130192', 'valuesIds': ['130192_1'], 'values': [], 'rangeValue': None}, {'id': '18062', 'valuesIds': ['18062_1', '18062_16'], 'values': [], 'rangeValue': None}, {'id': '130210', 'valuesIds': ['130210_3'], 'values': [], 'rangeValue': None}, {'id': '130209', 'valuesIds': ['130209_8'], 'values': [], 'rangeValue': None}, {'id': '216581', 'valuesIds': [], 'values': ['210'], 'rangeValue': None}, {'id': '216669', 'valuesIds': [], 'values': ['200'], 'rangeValue': None}, {'id': '216577', 'valuesIds': [], 'values': ['290'], 'rangeValue': None}, {'id': '216677', 'valuesIds': ['216677_275093'], 'values': [], 'rangeValue': None}], 'images': ['https://a.allegroimg.com/original/11995e/e0eb448e48d2ba9db0edd8a7a0e8', 'https://a.allegroimg.com/original/11a41e/c9cb237b4b458108244ffc8a2e43', 'https://a.allegroimg.com/original/117da2/09ac062f4f77bf0a923ed165ef03', 'https://a.allegroimg.com/original/11f3cf/90ea2a634737a581ce4caa9168ff', 'https://a.allegroimg.com/original/11687e/8c9c94924570ae859d858ab48d11'], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p>Dlaczego warto wybraćć fototapety</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11687e/8c9c94924570ae859d858ab48d11'}]}]}, 'name': 'liście palmowe 290x200'}, 'quantity': {'value': 1}}], 'delivery': {'handlingTime': 'PT24H', 'shippingRates': {'id': '83242861-d15c-4293-9478-a5962ae604ae'}}, 'location': {'countryCode': 'PL', 'province': 'LUBELSKIE', 'city': 'Zamość', 'postCode': '22-400'}, 'afterSalesServices': {'warranty': {'id': 'c13ceb5d-2200-466b-91d1-93775534c9ce'}, 'returnPolicy': {'id': '4cba35a0-8f34-451d-8309-57a89682f3a2'}, 'impliedWarranty': {'id': '0ccab1a4-2596-4714-a960-b92f20517066'}}, 'payments': {'invoice': 'VAT'}, 'stock': {'available': '999', 'unit': 'UNIT'}, 'tax': {'percentage': '23.00', 'rate': '23.00', 'subject': 'GOODS', 'exemption': None, 'id': 'ed5b1dc0-55db-4821-a922-39b0a4a5c716'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': '580.0', 'currency': 'PLN'}, 'minimalPrice': None, 'startingPrice': None}}

202
{'name': 'liście palmowe 290x200', 'productSet': [{'product': {'id': 'a6512478-5577-4f4b-bfa6-902bf767330a', 'publication': {'status': 'LISTED'}, 'parameters': [{'id': '248811', 'name': 'Marka', 'values': ['Uwalls'], 'valuesIds': ['248811_950468'], 'rangeValue': None}, {'id': '130210', 'name': 'Rodzaj', 'values': ['winylowa na flizelinie'], 'valuesIds': ['130210_3'], 'rangeValue': None}, {'id': '216577', 'name': 'Szerokość', 'values': ['290'], 'valuesIds': None, 'rangeValue': None}, {'id': '216669', 'name': 'Wysokość', 'values': ['200'], 'valuesIds': None, 'rangeValue': None}, {'id': '224017', 'name': 'Kod producenta', 'values': ['u48556'], 'valuesIds': None, 'rangeValue': None}, {'id': '215178', 'name': 'Cena', 'values': ['100'], 'valuesIds': None, 'rangeValue': None}, {'id': '130192', 'name': 'Gama kolorystyczna', 'values': ['biel'], 'valuesIds': ['130192_1'], 'rangeValue': None}, {'id': '18062', 'name': 'Motyw', 'values': ['Dekor', 'Motywy roślinne'], 'valuesIds': ['18062_1', '18062_16'], 'rangeValue': None}, {'id': '130209', 'name': 'Informacje dodatkowe', 'values': ['Tapeta 3D'], 'valuesIds': ['130209_8'], 'rangeValue': None}, {'id': '216581', 'name': 'Gramatura', 'values': ['210'], 'valuesIds': None, 'rangeValue': None}, {'id': '216677', 'name': 'Orientacja', 'values': ['pozioma'], 'valuesIds': ['216677_275093'], 'rangeValue': None}]}, 'quantity': {'value': 1}}], 'parameters': [{'id': '11323', 'name': 'Stan', 'values': ['Nowy'], 'valuesIds': ['11323_1'], 'rangeValue': None}], 'images': ['https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d', 'https://a.allegroimg.com/original/11995e/e0eb448e48d2ba9db0edd8a7a0e8', 'https://a.allegroimg.com/original/11a41e/c9cb237b4b458108244ffc8a2e43', 'https://a.allegroimg.com/original/117da2/09ac062f4f77bf0a923ed165ef03', 'https://a.allegroimg.com/original/11f3cf/90ea2a634737a581ce4caa9168ff'], 'afterSalesServices': {'impliedWarranty': {'id': '0ccab1a4-2596-4714-a960-b92f20517066'}, 'returnPolicy': {'id': '4cba35a0-8f34-451d-8309-57a89682f3a2'}, 'warranty': {'id': 'c13ceb5d-2200-466b-91d1-93775534c9ce'}}, 'payments': {'invoice': 'VAT'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': 580, 'currency': 'PLN'}, 'startingPrice': None, 'minimalPrice': None}, 'stock': {'available': 999, 'unit': 'UNIT'}, 'location': {'countryCode': 'PL', 'province': 'LUBELSKIE', 'city': 'Zamość', 'postCode': '22-400'}, 'delivery': {'shippingRates': {'id': '83242861-d15c-4293-9478-a5962ae604ae'}, 'handlingTime': 'PT24H', 'additionalInfo': None, 'shipmentDate': None}, 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p>Dlaczego warto wybraćć fototapety</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d'}]}]}, 'external': None, 'category': {'id': '68631'}, 'tax': {'percentage': '23.00', 'rate': '23.00', 'subject': 'GOODS', 'exemption': None, 'id': 'ed5b1dc0-55db-4821-a922-39b0a4a5c716'}, 'sizeTable': None, 'discounts': {'wholesalePriceList': None}, 'contact': None, 'fundraisingCampaign': None, 'messageToSellerSettings': None, 'attachments': [], 'b2b': {'buyableOnlyByBusiness': False}, 'additionalServices': None, 'compatibilityList': None, 'id': '12246181296', 'language': 'pl-PL', 'publication': {'status': 'INACTIVE', 'duration': None, 'endedBy': None, 'endingAt': None, 'startingAt': None, 'republish': False}, 'validation': {'errors': [], 'warnings': [], 'validatedAt': '2022-06-07T07:58:47.995Z'}, 'createdAt': '2022-06-07T07:58:48.000Z', 'updatedAt': '2022-06-07T07:58:48.013Z'}
12246181296 {'errors': [], 'warnings': [], 'validatedAt': '2022-06-07T07:58:47.995Z'}`

powinien być głównym
**https://a.allegroimg.com/original/11995e/e0eb448e48d2ba9db0edd8a7a0e8**
ale zmiany w
**https://a.allegroimg.com/original/11a6b0/181ce31b4777baa4f9b678d1b88d**

proszę pomóż

**Comment by sergeidebug** [comment]
Dyskutowałbym o tym, ale sądząc po poprzedniej dyskusji
#5749, 
jest z tym jakoś pusto
