### ISSUE TITLE
Numer VIN w centrum wiadomości

### ISSUE THREAD

**Issue by mkulig** [allegro/allegro-api#5754]
Witam,
przy zadawaniu pytania do oferty z motoryzacji można podać numer VIN samochodu. 
Moje pytanie brzmi jak ten numer z pola "VIN (Numer Identyfikacyjny Pojazdu)" można sprawdzić w API, ponieważ obecnie nie widzę takowego pola w zasobie /messaging/threads/{threadId}/messages?

![image](https://user-images.githubusercontent.com/48495083/171617664-7e9d6ec5-2dee-44b5-9110-2271994d2a38.png)

Jako przykład mogę podać wiadomość 8adf9ea0-732b-4f7d-8fc5-d232e4edacb4 w wątku 7JpQ5bGzbjMsG3fXr9Hvuw18Q9uYauIs26ArGUrtR0R.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie zwracamy tej informacji w zasobach do zarządzania Centrum Wiadomości. Jeśli zdecydujemy się dodać takie pole, poinformujemy o tym na [naszej stronie](https://developer.allegro.pl/news) oraz forum. Zachęcam Cię również do założenia sugestii w naszej - dedykowanej do tego -  zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).

**Comment by tomasz-grzesik** [comment]
@PrzemyslawLukanowski rozszerzenie wiadomości o nowe dane (VIN) nie powinno pojawić się wcześniej niż w przeglądarce, dopóki nie ma takiej możliwości przez API. Inaczej stwarzacie problemy sprzedawcom, kupującym i developerom.

**Comment by MaciejFrackowiak** [comment]
Numer VIN dostępny jest już w Centrum wiadomości - https://github.com/allegro/allegro-api/issues/5964.

**Comment by tomasz-grzesik** [comment]
> Numer VIN dostępny jest już w Centrum wiadomości - #5964.

Dziękuję za szybkie działanie.
