### ISSUE TITLE
How to create and activate the account in production

### ISSUE THREAD

**Issue by Gauravmitkar** [allegro/allegro-api#5756]
Hi 
I have successfully created and activated my account in sandbox and was able to the see the offer listings using my test application. Now I want to create and activate my account in production can you please let us know how that can be done.

**Comment by Lukasz-Zurek** [comment]
If you have any questions about registration and activation processes on your production account on the Allegro.pl - you will have to use our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=c0e58dc2-7dda-44ab-9ede-d4435f1ddef4&subjectId=0bc27e4d-4963-4626-aba5-3a4f32d5ec4d).

In this forum we provide API support so when you are fully activated and have some questions about the API, please let us know.
