### ISSUE TITLE
Prośba o sprawdzenie opisu aukcji

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#576]
Witam,
podczas wystawiania aukcji dostaję  komunikat 

> sections[0].items[0].content Nieprawidłowy podzbiór HTML 

niestety ja nie widzę żadnego błędu, czy w związku z tym mogę prosić o weryfikację to tu jest nie tak 
`{"sections":[{"items":[{"type":"TEXT","content":"<h1>Filtr kasetowy klasy G4; BARTOSZ-VENA; 275x275x50</h1><p>\u00a0</p><h1>\u00a0</h1><h2>Filtr kasetowy klasy G4 do rekuperator\u00f3w firmy\u00a0BARTOSZ*</h2><p>\u00a0</p><h2><b>Wymiary: 275x275x50</b></h2><p>\u00a0</p><h2>Filtr z atestem higienicznym wydanym przez PZH.</h2><p><b>Producent centrali:\u00a0</b>BARTOSZ</p><p><b>Model centrali:\u00a0</b><b>\u00a0</b></p><ul>\t<li>VENA 3\u00a0(nowsze - od 09.2012r.)</li>\t<li>VENA 4</li></ul><p><b>Uwagi:</b>\u00a0filtr dopasowany do starszych modeli central VENA 3 produkowanych po 09.2012</p><p><b>Typ:\u00a0</b>Filtr kasetowy</p><p><b>Konstrukcja</b>: ramka stalowa, w\u0142\u00f3knina filtracyjna plisowana i wzmocniona siatk\u0105 aluminiow\u0105</p><p><b>Klasa filtracyjna:</b>\u00a0G4</p><p><b>Wymiary:</b>\u00a0275x275x50</p><p>*produkt jest zamiennikiem. Nazwy urz\u0105dze\u0144, cz\u0119\u015bci i marek zosta\u0142y u\u017cyte w celu identyfikacji produktu.</p><h2><b>Produkt atestowany przez PZH - Pa\u0144stwowy Zak\u0142ad Higieny</b></h2><p><br \/>Aukcja dotyczy 1 sztuki filtra. Podana cena jest kwot\u0105 brutto.\u00a0</p><p>Mo\u017cliwo\u015b\u0107 wysy\u0142ki za granic\u0119 po wcze\u015bniejszym ustaleniu indywidualnego kosztu wysy\u0142ki.</p><p>\u00a0</p><ul>\t<li>Typ: Filtr kasetowy</li>\t<li>Klasa filtracyjna: G4</li>\t<li>Producent centrali: BARTOSZ</li>\t<li>Model: VENA 3</li></ul>"}]}]}`

jest to generowane następującym kodem php

```
$json=strtr(json_encode(
				array(
					'sections'=>
						array(
							array(
								'items'=>
									array(
										array(
											"type"=> "TEXT",
											"content"=> html_entity_decode(stripslashes( strtr($KOD_HTML,array("\n"=>'',"\r"=>'','\"'=>'"'))))						
										)
									)
						
								)
							)
						)
				),array('<\\/'=>'</'));
```

**Comment by mzawodzinski** [comment]
Sprawdziłem z innym kodem html i aukcja jest ustawiana.
Czyli problemem musi być sam kod HTML, a nie struktura jsona.

Więc wystawienie aukcji edytorem graficznym chyba nic mi nie  da ?

**Comment by TomekKaczmarek** [comment]
@mzawodzinski  W opisie jest niepoprawny i niedopuszczalny znacznik HMTL - <br \/>. Nie dopuszczamy znaków nowej linii.

**Comment by mzawodzinski** [comment]
Dziękuję za pomoc,
jak się okazuje w ckeditor wcale nie tak łatwo jest usunąć br

**Comment by arhimano** [comment]
@TomekKaczmarek można wiedzieć, co Wami powoduje, że nie lubicie `<br/>` ?
Skoro dopuszczacie paragraf, to raczej nie chodzi o to, ze klienci przesadzą z nowymi liniami.
Bardzo dużo problemów sprawia dopasowanie formatów opisów produktów z różnych systemów naszych klientów, do waszych wymogów.
Często edytory graficzne wypluwają kod w postaci np: (popatrz gdzie się zaczyna `<b>` a gdzie kończy.

```
<p>
  lalalalala:<b><br/>
  tralalala</b><br/>
  trzeciala
</p>
```
Samo wycięcie `<br/>` nie daje dobrego rezultatu, bo znaki nowej linii są tam kluczowe.
Żeby to ogarnąć poprawnie, zamieniamy `<br/>` na `</p><p>`, ale wówczas kod HTML jest nie walidowalny:
```
<p>
  lalalalala:<b></p>
<p>
  tralalala</b></p>
<p>
  trzeciala
</p>
```
o czym nie omieszkujecie wspomnieć przy wystawianiu aukcji...

Jaka rada na takie problemy?

**Comment by imper86** [comment]
@arhimano ja sobie poradziłem w taki sposób: https://github.com/imper86/allegro-new-desc-html-transformer/blob/master/src/Imper86/AllegroNewDescHtmlTransformer/HtmlTransformer.php

Robione na szybko i jakość kodu słaba, ale działa i konwertuje mi opisy w htmlu do potrzeb allegro. Na pewno dałoby się to lepiej zrobić ale nie mam na to czasu :)

**Comment by arhimano** [comment]
@imper86 dobre podejście, czy mogę skorzystać z Twojej wizji?

**Comment by imper86** [comment]
@arhimano pewnie, jeśli korzystasz z composera to możesz sobie ściągnąć całą paczkę i korzystać do woli - https://github.com/imper86/allegro-new-desc-html-transformer

**Comment by arhimano** [comment]
@imper86 Dzięki :)
@TomekKaczmarek ja wszystko rozumiem, ale równie dobrze można zrobić taką samą akcję stosując paragrafy jeden po drugim ;) np:
```
<p>lorem ipsum</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p>dolor sit amet</p>
```

Piszemy dosyć zaawansowane algorytmy parsujące opisy klientów, ale nie powiem, żebyście nam ułatwiali życie. Mając kilkadziesiąt tysięcy aukcji do wystawienia, trochę włosów z głowy musimy powyrywać, żeby to dobrze zautomatyzować...

**Comment by TomekKaczmarek** [comment]
Naturalnie, możesz w ten sposób opis wrzucić, ignorujemy jednak na froncie znaczniki HTML, pomiędzy którymi nie ma treści. W efekcie kod HTML taki jak poniżej 
`<h1>Tytul</h1><p>Opis testowy</p><p></p><p></p><p></p><p></p><p></p><p></p><p></p><p>Opis testowy 2</p>`
będzie wyglądał tak jak na załączonym zrzucie ekranu:
![opis](https://user-images.githubusercontent.com/36262678/45613699-6a24e200-ba67-11e8-8b9d-3cb46eba4d46.png)

**Comment by TimothyKoval** [comment]
`<p>&nbsp;</p>` było fajne za czasów FrontPage-a :)

**Comment by TomekKaczmarek** [comment]
I cały misterny plan w...

No cóż, staramy się jak możemy ograniczyć naszym sprzedawcom opcje robienia krzywdy sobie i ich klientom. Nie zawsze jednak jest to możliwe dla wszystkich przypadków.

Jeśli sprzedawca chce w ten sposób tworzyć swoje opisy - robi problem przede wszystkim kupującym, którzy przy kilku takich nowych akapitach trafią na zupełnie pusty ekran w trakcie przeglądania opisu oferty na urządzeniu mobilnym. A ponad połowa użytkowników Allegro przegląda nasz serwis na takim urządzeniu.
