### ISSUE TITLE
Sent application/pdf content type but return application/pdf;charset=UTF-8

### ISSUE THREAD

**Issue by luiggies** [allegro/allegro-api#5760]
Witam, 
chcąc dodać załączniki do rozmowy w centrum wiadomości po jego zadeklarowaniu przesyłam plik załącznika binarnie z 
content typem o treści: "application/pdf"
w odpowiedzi strona zwraca błąd z kodem 415
"errors": 
        {
            "code": "UNSUPPORTED_MIME_TYPE",
            "message": "Not supported or missing MIME type for _attachmentId_: id [filename=zal.pdf, 
                                mimeType=application/pdf;charset=UTF-8]",
            "details": null,
            "path": "attachment.filename",
            "userMessage": "Format pliku nie jest wspierany."
        }
   
korzystam z pythonowego requesta i wykonuję wszystko wg wskazówek:
https://developer.allegro.pl/tutorials/jak-zarzadzac-centrum-wiadomosci-XxWm2K890Fk#zalaczniki

fragment wywołania:

url  = "messaging/message-attachments/" + attachmentId
headers = {}
headers["Authorization"] = "Bearer " + self.allegroAuth.getToken()
headers["Accept"]        = "application/vnd.allegro.public.v1+json"
headers["Content-Type"]  = "application/pdf"
data = {"data": open(filePath,'rb') }
requests.put(self.urlPrefix + url, headers=headers, data=data)

Proszę o pomoc w rozwiązaniu problemu

**Comment by Lukasz-Zurek** [comment]
Podaj proszę trace-id Twojego wywołania.

**Comment by luiggies** [comment]
Z ostatniego zapytania
'trace-id': 'b7ce44d67a1fe775'

**Comment by Lukasz-Zurek** [comment]
@luiggies Dziękuję. Sprawę przekazałem do dalszej weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@luiggies Wszystko wskazuje na to, że przyczyna leży po stronie samego pliku, który co prawda ma format pdf, ale nie jest to plik w tym formacie. Załączenie tego typu pliku może zakończyć się wspomnianym błędem.

Oczywiście jeśli faktycznie załączasz prawidłowy plik - prześlij nam go proszę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1
).
