### ISSUE TITLE
blad podczas proby fetchowania danych

### ISSUE THREAD

**Issue by mariuszolszolszola** [allegro/allegro-api#5761]
import requests
from requests.structures import CaseInsensitiveDict

CLIENT_ID = ""          # wprowadź Client_ID aplikacji
CLIENT_SECRET = ""      # wprowadź Client_Secret aplikacji
TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def get_access_token():
    try:
        data = {'grant_type': 'client_credentials'}
        access_token_response = requests.post(TOKEN_URL, data=data, verify=False, allow_redirects=False, auth=(CLIENT_ID, CLIENT_SECRET))
        tokens = json.loads(access_token_response.text)
        access_token = tokens['access_token']
        return access_token
    except requests.exceptions.HTTPError as err:
        raise SystemExit(err)

access_token = get_access_token()

url = "https://api.allegro.pl/sale/products?phrase=rekawiczki"

headers = CaseInsensitiveDict()
headers["Authorization"] = f"Bearer {access_token}"
headers["Accept"] = "application/vnd.allegro.public.v1+json"
headers["ContentType"] = "application/vnd.allegro.public.v1+json"

resp = requests.get(url, headers=headers)

print(resp.text)

pytanie brzmi czemu dostaje access denied? czy jest mozliwe wyszukiwanie akucji w oparciu o fraze?

**Comment by PrzemyslawLukanowski** [comment]
Problem występuje, ponieważ korzystasz z tokena wygenerowanego w ramach autoryzacji client credentials. Aby skorzystać z tego zasobu, użyj dostępu bearer token for user - czyli autoryzacja code lub device flow.
