### ISSUE TITLE
Problem z wystawianiem ofert z jednego konta

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5762]
Na jednym z naszych testowych kont na sandbox zauważyliśmy problem z wystawianiem ofert. Otrzymujemy komunikat: "Użytkownik z blokadą konta Firma nie może wystawiać nowych ofert.". Problem dotyczy konta mateuszcom. Proszę o pomoc

**Comment by Lukasz-Zurek** [comment]
Odświeżyłem Twoje konto, spróbuj ponownie wystawić ofertę.

Jeśli sytuacja się powtórzy - daj proszę znać w wątku.

**Comment by mateuszcom** [comment]
Niestety nadal nie mogę wystawiać ofert - ten sam komunikat

**Comment by Lukasz-Zurek** [comment]
Problem przekazałem dalej do weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Na wstępnie przepraszam za tak długi czas oczekiwania na odpowiedź. Udało się nam odświeżyć Twoje konto na sandboxie. Napotkaliśmy na większy problem w bazie danych na środowisku testowym. Będziemy monitorować tego typu przypadki w przyszłości.

**Comment by mateuszcom** [comment]
Dziękuję za informację
