### ISSUE TITLE
Ilość sprzedaży

### ISSUE THREAD

**Issue by bswierzewski** [allegro/allegro-api#5763]
Witam serdecznie w jaki sposób mogę uzyskać ilość sprzedaży danej oferty z api? Przeglądam dokumentację i nie potrafię odnaleźć takiej informacji.

**Comment by PrzemyslawLukanowski** [comment]
Tę informację otrzymasz w odpowiedzi dla GET /sale/offers w polu stock.sold.

**Comment by bswierzewski** [comment]
![image](https://user-images.githubusercontent.com/33912764/172102639-e2615f37-b72f-47c2-9b04-5c70e96774d2.png)
Z tego co widzę to informacja zawiera jest okrojona tylko do 30 dni wstecz a potrzebuję informacji o ilości sprzedanej w ramach wybranego okresu czasu.

Tzn jeśli oferta trwa 4 miesiące to chciałbym wiedzieć np ile przedmiotów sprzedałem w okresie 2-3 miesiąca a ile np w ciągu 1 miesiąca.

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie jest to możliwe. Pole jest odpowiednikiem informacji ze strony internetowej (zakladki Mój asortyment) i tam również zwracamy informacje tylko o ostatnich 30 dniach.

**Comment by bswierzewski** [comment]
A istnieje powiązanie pomiędzy zamówieniami a ofertą? Mogę w jakiś sposób sprawdzić które zamówienia są dla danej oferty?

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście, w danych zamówienia (GET/order/checkout-forms lub GET /order/checkout-forms/{id}) informację o powiązanej ofercie znajdziesz w polu lineItes.offer.id.

**Comment by bswierzewski** [comment]
1) Interesuje mnie jeszcze informacja czy wyniki zwracane z GET/order/checkout-forms możemy przefiltrować po lineItems.offer.id ? W dokumentacji nie widzę takiej możliwości. 
2) Dodatkowo w allegro widzę iż zmówienia możemy szukać po nazwie czy dla api takiej możliwości nie ma?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale w obu przypadkach nie jest to możliwe.
