### ISSUE TITLE
Wyszukiwanie produktu z katalogu TecDoc

### ISSUE THREAD

**Issue by lukasczg** [allegro/allegro-api#5764]
Cześć,

Pytanie dotyczy metody:  **Get search products results**
z zasobu: **/sale/products**

Szukam po numerze katalogowym producenta części.

Chciałbym znaleźć produkt z katalogu TecDoc który później powiąże z ofertą.
Niestety niemal każde zapytanie zamiast jednej pozycji zwraca kilka. 
Zazwyczaj większość jest jakiś "śmietnik".
Skąd mam wiedzieć który produkt z listy to produkt z katalogu TecDoc? 

Zdjęcia to też jakaś porażka. TecDoc ma w swoich zasobach więcej zdjęć a API Allegro często zwraca jedno + inne które albo nie jest właściwe, albo jest to spam innych sprzedawców.  

Przykład:
url: `/sale/products?phrase=GDB1330&mode=MPN`

zwraca:
`{
  products: [
    {
      id: '649f40c2-41d1-4506-9a8b-6c00af6efa18',
      name: 'TRW GDB1330 Zestaw klocków hamulcowych, hamulce tarczowe',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: '9af1f46d-03a0-4e84-b784-f2879f978d76',
      name: 'TRW gdb1330 klocki hamulcowe',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: '366858a2-d4b3-46ea-a57f-fb26940ea58d',
      name: 'TRW GDB1330 Zestaw klocków hamulcowych 9C-31',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: '6f9116f6-1410-464a-a7da-330f4ed32331',
      name: 'Volkswagen OE GDB1330 zestaw klocków hamulcowych, hamulce tarczowe',
      category: [Object],
      parameters: [Array],
      images: [],
      description: null
    },
    {
      id: '70e461b0-e777-408b-b5fd-416df1ce952d',
      name: 'Hart GDB1330 klocki hamulcowe',
      category: [Object],
      parameters: [Array],
      images: [],
      description: [Object]
    },
    {
      id: '7a577e86-a133-421c-adb9-766b24fd7dda',
      name: 'DACO GDB1330',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: 'afa544f8-e77e-4665-9da9-aa89fd78d19a',
      name: 'Lucas GDB1330 klocki hamulc',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: '748d26ba-63b6-4ad1-bcf1-2a3652b719cd',
      name: 'TRW GDB1330',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    },
    {
      id: 'd4144ab8-4b70-4500-8521-3e1e4a5529f0',
      name: '[GDB1330] Klocek hamulcowy kpl. tył AUDI A1, A2,',
      category: [Object],
      parameters: [Array],
      images: [Array],
      description: [Object]
    }
  ],
  categories: {
    subcategories: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    path: [ [Object] ]
  },
  filters: [],
  nextPage: null
}`

**Comment by PrzemyslawLukanowski** [comment]
Aby sprawdzić, czy produkt pochodzi z katalogu TecDoc, musisz pobrać dane konkretnego produktu i zwrócić uwagę na pole tecdocSpecification.id. Jeśli zwrócimy w tym polu konkretny UUID, oznacza to, że jest to produkt z katalogu TecDoc.

W przypadku zastrzeżeń stricte co do danych w katalogu, możesz je zgłosić bezpośrednio za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by lukasczg** [comment]
ok dzięki,
proszę przyjąć sugestię, żeby dodać metodę pozwalającą na filtrowanie w metodzie "Get search products results" tylko produktów z katalogu TecDoc. 

Mam jeszcze pytanie dotyczące zdjęć. 
TecDoc ma więcej zdjęć, niż np te dodane do produktu: 649f40c2-41d1-4506-9a8b-6c00af6efa18
w tym konkretnym udostępniacie te dwa:
https://a.allegroimg.com/original/1188d4/35d6c60a440d9191c726e457f6f8
https://a.allegroimg.com/original/113983/bfa2f9c54d28b7282f603efa611e (te nie jest z TecDoc)

Czy jest metoda pozwalająca na załączenie do oferty zdjęć z katalogu TecDoc?

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie udostępniamy takiej metody. Zdjęcia w produktach działają tak samo, niezależnie od tego, czy produkt jest z bazy TecDoc, czy nie.
