### ISSUE TITLE
Orlen Paczka przez Allegro API

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5765]
Witam

Generujemy paczki przez Allegro API do Orlen Paczka ale Orlen Paczka twierdzi ze nie przekazujemy wymiarów.
To powoduje naliczanie wiekszej oplaty za paczke.
Czy do Orlen Paczka trzeba jakos inaczej przekazywac wymiary ?

      "dimensions": {
        "height": {
          "value": 8,
          "unit": "CENTIMETER"
        },

        "width": {
          "value": 20,
          "unit": "CENTIMETER"
        },

        "depth": {
          "value": 30,
          "unit": "CENTIMETER"
        }

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie. Wyjaśniam sytuację,  wrócę z informacja.

**Comment by PawelPseudo** [comment]
Taka jest odp z Orlen Paczki.
I dzieje się to losowo, raz parametry przechodzą raz nie. Magia.

---------------

Generują Państwo etykiety za pomocą API Allegro, w związku z powyższym proszę uprzejmie o przekazanie informacji o nieprawidłowym gabarycie do działu wsparcia Allegro. Z naszym systemów wynika, że pole <BoxSize> w którym mogą Państwo zdefiniować rozmiar jest puste, dlatego paczka jest generowana jako standard. Nie jesteśmy jednak w stanie z naszego poziomu zweryfikować w jaki sposób Allegro zaprogramowało mechanizm nadawania gabarytów paczkom, dlatego proszę uprzejmie o kontakt z działem wsparcia Allegro.

**Comment by PrzemyslawLukanowski** [comment]
Analizujemy jeszcze tę sytuację. Wrócę z informacją, gdy uda nam się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Wracam z odpowiedzią - API Orlenu nie przyjmuje wymiarów, a jedynie gabaryty. Dostępne są: MINI, S, M, L oraz STANDARD. Mini jest dla paczki mini, S,M,L są dla paczek z doręczeniem do automatu i stacji Orlen. Jeżeli nie zadeklaruje się gabarytu, to domyślnie paczka jest oznaczana jako STANDARD (max. 20 cm x 30 cm x 50 cm, 20 kg).  Poniżej przesyłam informację o wartościach, które są mapowane na konkretne gabaryty:
<img width="463" alt="Zrzut ekranu 2022-06-8 o 16 11 01" src="https://user-images.githubusercontent.com/51473661/172780011-4a7d0872-e1fb-436e-9d0f-231703b8fc83.png">

**Comment by PawelPseudo** [comment]
ok, rozumiem w takim razie jak w api allegro zadeklarowac gabaryt ?
nie widze tego w opcjach allegro api.

![Screenshot_38](https://user-images.githubusercontent.com/73448782/172932237-da9b91ac-701c-4611-9e97-18985d9aebee.jpg)

**Comment by PrzemyslawLukanowski** [comment]
Gabarytu nie deklarujesz bezpośrednio, zostaje on zmapowany na podstawie wartości, które przekazujesz w `dimensions`. Jeśli podajesz tam prawidłowe wymiary, a Orlen mimo to twierdzi, że nie otrzymuje tej wartości, to podeślij nam proszę przez [formularz](https://allegro.pl/pomoc/kontakt) 2-3 przykłady z prawidłowo uzupełnioną tą sekcją. W zgłoszeniu dopisz, że problem dotyczy wątku #5765 na GitHubie.

**Comment by PawelPseudo** [comment]
Piszę tutaj bo Wasz formularz do kontaktu na Allegro tu kieruje :)

paczka
"23987227" ref:_00D24aE05._5003VPsZRX:ref

**Comment by PawelPseudo** [comment]
Dzień dobry,

otrzymałem informacje, że przesyłki zostały odebrane od klientów, 2100508877581 w dniu 2022-05-28 13:52:43,  i 2100510349014 w dniu 2022-06-01 17:44:14.

W razie pytań pozostaję do dyspozycji.

**Comment by PawelPseudo** [comment]
Panowie możemy info ? Ponosimy dodatkowe koszty zwiazane z tym bledem.

**Comment by PrzemyslawLukanowski** [comment]
Przepraszam, ale dane z formularza do nas nie dotarły. Czy, aby przyśpieszyć weryfikację, możesz podać trzy (w miarę możliwości - nowe) numery UUID dla tworzenia paczek, gdzie podaliście wymiary, ale mimo Orlen nie otrzymał informacji o gabarycie?

**Comment by PawelPseudo** [comment]
UUIDY:

e9768fdb-52bc-417c-9024-507a90591af9
a4591706-60f1-4e5b-a4d4-eb5a1e6e2179
0549683b-bdd4-4a04-aea9-c5263c5a1037

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, dotarły do nas także informacje o dwóch wcześniejszych przesyłkach - weryfikujemy sprawę.

**Comment by PrzemyslawLukanowski** [comment]
Wracam z odpowiedzią - jeśli chodzi o przesyłkę 80811620 to została nadana na umowie własnej przez ORLEN Paczka do punktu odbioru. Jej wymiary to 19x30x50. Sprawdzając tabelkę z wymiarami załączoną w wątku, paczka kwalifikuje się jako "Standard". Przesyłka 81579349 - taka sama sytuacja. Jeśli chcecie, aby przesyłki o takich wymiarach zostały oznaczone gabarytem "Rozmiar M", powinniście nadawać je nie do punktu odbioru (saloniki, kiosk), tylko do stacji lub automatu paczkowego Orlenu.

**Comment by PawelPseudo** [comment]
Ale to klient wybiera gdzie chce dostacz paczke a nie sprzedawca.
Dodatkowo wymiar nie kwalifikuje sie jako "standard" bo jest mniejszy.

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, w takiej sytuacji oczywiście to klient wybrał "punkt odbioru". Wymiar jednak kwalifikuje się jako "STANDARD" - maksymalne wymiary dla "MINI" to 20x20x30 , a przykładowy wymiar nadawanej paczki to 19x30x50.

**Comment by PawelPseudo** [comment]
Czy ustawienie 8x20x30 5kg rozwuazuje problem ?

**Comment by PrzemyslawLukanowski** [comment]
> Czy ustawienie 8x20x30 5kg rozwuazuje problem ?

Tak, w ten sposób paczki powinny zostać oznaczona jako MINI.

Załączony fragment artykułu odnosi się do metod **Allegro** Orlen Paczka, a jak wspomniałem wskazane paczki zostały nadane na umowie własnej przez Orlen Paczka do punktów odbioru - czyli przytoczony tekst nie ma dla nich zastosowania, a wymiary w tabeli wyżej są prawidłowe.

**Comment by PrzemyslawLukanowski** [comment]
Wyjaśniamy ponownie te kwestię z zewnętrznym dostawcą usługi i jednocześnie przepraszam za tak długi czas weryfikacji problemu.

**Comment by PrzemyslawLukanowski** [comment]
Wracam z informacją. W przypadku punktów odbioru, sprawdzamy tylko, czy paczka klasyfikuje się jako MINI (waga do 5 kg i wymiary nie większe niż 20 X 20 X 30 cm) jeśli tak — nadajemy gabaryt MINI.
Jeśli któryś z parametrów zostanie przekroczony — wysyłamy bez określonego gabarytu (w domyśle — Standard, jednak API Orlenu wszystkie paczki bez podanego gabarytu klasyfikuje jako standard). Zatem najczęściej Orlen faktycznie nie otrzymuje informacji o gabarycie (taka paczka domyślnie będzie STANDARD).

W Waszym przypadku rozmiar przesyłki, który kwalifikuje ją do MINI, został przekroczony, dlatego zostały nadane bez określonego gabarytu (jako STANDARD).
