### ISSUE TITLE
API przestało pobierac eventy 

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#5766]
Mam problem od 3/06 - API przestało zwracać liste ostatnich eventów.. Nie loguje się żaden błąd połączenia, ani żaden inny..

wywołuje: 
$url = "https://api.allegro.pl/order/events?from={$lastEventID}";

wiem, ze są Eventy

**Comment by MaciejFrackowiak** [comment]
Proszę podaj nam więcej szczegółów - przynajmniej identyfikator użytkownika, abyśmy mogli to sprawdzić. Nie otrzymaliśmy podobnych zgłoszeń w ostatnim czasie.

**Comment by ButcherFromHell** [comment]
Przykładowy event ID: 1654238631910620 - czy to wystarczy? 

Ruszyło teraz - coś z TOKENem się zadziało, zresetowałem i wygenerowałem nowy i poszło.. nie mniej jeśli jakaś dalsza informacja się zalogowała będę wdzięczny za jej przekazanie,,

**Comment by MaciejFrackowiak** [comment]
Przejrzałem posiadane przez nas logi - nie zauważyłem nic nieprawidłowego. Jedyny błąd 401 dla GET /order/events odnotowaliśmy 2022-06-02 13:05:02.072 - od tego czasu widzimy same requesty zakończone 200.
