### ISSUE TITLE
primaryImage 2

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#5768]
tutaj już wcześniej rozpocząłem dyskusję na ten temat
#5752, 
ale nie otrzymałem rozwiązania zapobiegawczego i pojawiły się problemy, jak się spodziewałem.
Teraz nie jestem pewien, czy uzyskam odpowiedź na to pytanie, więc pytam ponownie.
Jak dokładnie określić główny obraz?
PUT /sale/product-offers

Z jakiegoś powodu, kiedy tylko wypełniam zdjęcia,
**images**
pierwszy okazuje się być głównym, miniaturą. Jeśli jednak dodam jeden ze zdjęć do opisu
**description**
Obraz dodany do opisu staje się głównym.

Wcześniej dowiedziałem się już, że aby dodać obrazek do opisu, musi on być obecny w tabeli obrazków w polu **images**.
Jak więc określić główny obraz w tym przypadku?

**Comment by MaciejFrackowiak** [comment]
Proszę nie dubluj wątków - odpowiedź udzielimy we wcześniejszym.

**Comment by sergeidebug** [comment]
dobrze
