### ISSUE TITLE
oznaczenie przesyłki pobraniowej w /sale/delivery-methods

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#577]
W responsie zasobu /sale/delivery-methods przydał by się dodatkowy parametr oznaczający czy dana metoda dostawy jest pobraniowa. Obecnie zwracane jest to w nazwie 
(albo nawet nie jest oznaczone tak jak w przypadku metod o guidzie 
**_121981e4-a14b-450b-b9fe-718df1dc3cd1_** i **_b715fac1-8ec2-4f5c-8fdf-0f9cec9085ad_** gdzie obydwie metody maja nazwę "PACZKA W RUCHu" i zgaduje ze jedna z nich jest pobraniowa). 
Mam jeszcze pytanie jak zmapować metody dostawy pobierane z Rest API z tymi pobieranymi w WebAPI ponieważ nie da się tego zrobić po nazwie ze względu na różnice w nich.

**Comment by TomekKaczmarek** [comment]
@riepa faktywnie. To błąd, poprawimy nazwy i wskażemy, która z metod jest pobraniowa.

Nazwy niestety są różne i nie mamy w planach by je uspójnić. Metody możesz zmapować jedynie ręcznie.

**Comment by riepa** [comment]
A co z parametrem określającym czy dana metoda jest pobraniowa czy nie? Bo bez niego tak naprawdę trzeba wszytko dodawać ręcznie co nie jest najwygodniejszym i najnormalniejszym rozwiązaniem. Brak automatyzacji tego procesu będzie szczególnie dotkliwy w wypadku zmian i dodawania nowych metod dostawy

**Comment by KrzysztofStachyra** [comment]
@TomekKaczmarek - odbieracie istotną funkcjonalność. Miejcie na uwadze, że jak w starym API był taki znacznik to z bardzo dużym prawdopodobieństwem ktoś go użył. Taka flaga jednoznacznie opisująca jaki to typ przesyłki ma wpływ na:
1. Jaką formę płatności umieścić na zamówieniu lub fakturze (nie ma to nic wspólnego z płatnością do transakcji)
2. Jaki typ płatności zaproponować do paczki kurierskiej z takiej transakcji

teraz będzie trzeba kazać ręcznie uzupełniać to użytkownikowi albo robić jakieś parsowanie nazwy i szukać frazy pobranie... Nie cofajmy się w rozwoju tylko faktycznie niech to API coś nowego daje poza problemami.

**Comment by TomekKaczmarek** [comment]
@riepa @KrzysztofStachyra Panowie, trudno odmówić Wam racji. Dziękujemy za sugestie, weźmiemy je pod uwagę w temacie rozwoju zasobów dla Cenników dostawy.
