### ISSUE TITLE
Invalid EAN error (422), for valid EAN codes.

### ISSUE THREAD

**Issue by theazgra** [allegro/allegro-api#5770]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**
For some product offers I am receiving error response 422, for invalid EAN value.

This is the full error:
```
trace-id: '9c6c6f8b8c622c7' | Failed to create product offer. | HTTP status code: 422 - UnprocessableEntity {"errors":[{"code":"ConstraintViolationException.ValidProduct","message":"Podany EAN nie jest zgodny z jakimkolwiek EANem produktu.","details":"ConstraintViolationException.ValidProduct","path":"null","userMessage":"Podany EAN nie jest zgodny z jakimkolwiek EANem produktu."}]}
```

Here is the table with examples, from **SANDBOX** environment. I am getting same erros, for some products even on production environment.

|EAN           |trace-id         | :EAN search result                           |
|---------------|------------------|---------------------------------------------|
| 8596281040160 |  9c6c6f8b8c622c7 | https://www.ean-search.org/?q=8596281040160 |
| 8596281040177 | 5cf90b0f90855ec2 | https://www.ean-search.org/?q=8596281040177 |
| 8596281040184 | 4db84443d23c393e | https://www.ean-search.org/?q=8596281040184 |
| 8596281040191 | c3c363f2348775c  | https://www.ean-search.org/?q=8596281040191 |

Can you tell me why am I getting these errors?

**Comment by Lukasz-Zurek** [comment]
You are trying to provide an EAN which is different than in the product which we (as a service) try to assign to the offer.

**trace.id:** 9c6c6f8b8c622c7  - product.id: 306fcf87-7722-4b44-b6ae-a10ad21e5259,

**trace.id:** 5cf90b0f90855ec2 - product.id: f63d9d2b-d2ff-4215-848f-cc7772a19444,

**trace.id:** 4db84443d23c393e - product.id: 7b6a23a5-01ce-4b2f-b565-3e9e10da96f5,

**trace.id:** c3c363f2348775c  - product.id: 20d7502a-dabd-4689-8fbc-f087c4107c1c.

This is why you receive an error.

Please give me some examples from the production - I will check these products and see what I can do.

**Comment by theazgra** [comment]
Hmm, but how could be our EAN wrong?

Here are some examples from production:

| EAN           | trace-id         |
|---------------|------------------|
| 6181692410668 | a9c4bd8047d19435 |
| 4752162821080 | ad2390db1b03221d |
| 6181692408566 | 9520554e01927a56 |
| 4752162821073 | d0c222ebc2fc46e8 |
| 4752162821066 | c083f4e6bc7e8377 |
| 4750903873190 | dc8bb12cd3582676 |
| 4894728303057 | 74ce2c02a04d2aca |
| 5901656977287 | aaca2731d8d4b823 |
| 6181692353149 | 7c244e09d02a86f6 |
| 6181692353316 | 33303cf5e9cb52ca |

**Comment by Lukasz-Zurek** [comment]
Thank you for your quick response. As I see - our service is trying to assign products with a different EAN (than you provide). The same situation as in Allegro Sandbox.

You can report an incorrect data (in this case it will be an EAN code) in the product using [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).

You can find more information in [our guide](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-report-incorrect-data-in-a-product).
