### ISSUE TITLE
Brak możliwości utworzenia kampanii z kuponami - sandbox

### ISSUE THREAD

**Issue by LukSky24** [allegro/allegro-api#5771]
Dzień dobry,

Mamy sobie konto sandboxowe `FastWhiteCat` na którym wystawiliśmy nawet dziś jedną ofertę, dodaliśmy sobie kilka ocen z innego konta, ale nadal nie mamy określonej jakości sprzedaży, bo niby nie wystawialiśmy żadnych ofert w przeciągu 30 dni. 
![image](https://user-images.githubusercontent.com/52952445/172345724-cf248ed9-d275-4ee5-9e8b-3370288b4964.png)
Także to blokuje nam tworzenie kampanii z kuponami, a potrzebujemy tego aby sprawdzić jedną funkcjonalność.

Bo mieliśmy przypadek na innym koncie (produkcyjnym) kiedy kupon (-10 zł) został tak rozdzielony na 3 produkty w koszyku (gdzie 1 był z jednej aukcji, a dwa z innej), że pierwszy dostał zniżke 3,69zł, a pozostałe produkty (dwa takie same z tej samej aukcji) po 3,15 i 3,16 bo 10 zł nie rodzieliło się tak pięknie między te procenty. W ten sposób w jednym zamówieniu mieliśmy dwa takie same produkty, z tej samej aukcji ale jeden w cenie 82,33 a drugi 82,34. Chcemy to sprawdzić jeszcze na sandoboxie, ale nie możemy utworzyć tam kampanii kuponowej.

**Comment by Lukasz-Zurek** [comment]
Sprawę konsultuję. Proszę o cierpliwość.

**Comment by LukSky24** [comment]
@Lukasz-Zurek Mi zależy na tym aby móc wygenerować kupony rabatowe na sandboxie. Czy to możliwe nawet bez tej jakości sprzedaży?

**Comment by Lukasz-Zurek** [comment]
@LukSky24 Użyłem swojej magii. Wejdź proszę na stronę: https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/jakosc-sprzedazy/ i sprawdź czy jest ok.

**Comment by LukSky24** [comment]
@Lukasz-Zurek Jakość jest ok, dzięki. Ale nie wiem jeszcze co blokuje kupony? 
![image](https://user-images.githubusercontent.com/52952445/172367025-b8ecf093-a1f2-4d4d-b25a-2a0d4037b8ea.png)

**Comment by LukSky24** [comment]
@Lukasz-Zurek I jak udało się coś ustalić? Bo widzę, że nadal ta funkcja nie działa :/

**Comment by Lukasz-Zurek** [comment]
@LukSky24 Nadal weryfikujemy ten problem. Postaram się to wyjaśnić w jak najkrótszym czasie.

**Comment by Lukasz-Zurek** [comment]
@LukSky24 Sprawdź teraz.

**Comment by LukSky24** [comment]
@Lukasz-Zurek Już działa. Świetnie, wielkie dzięki za pomoc.
