### ISSUE TITLE
PUT /order/checkout-forms/{id}/invoices/{invoiceId}/file Brak contentu PDF. Node.js

### ISSUE THREAD

**Issue by samuelslak** [allegro/allegro-api#5772]
Dzień dobry,
Próbuję dodać plik PDF za pomocą zasobu PUT /order/checkout-forms/{id}/invoices/{invoiceId}/file przy pomocy serwera Node.js i biblioteki Axios.
Plik dodaje się do zamówienia natomiast brakuje w nim zawartości. Jak na załączonym obrazku:

![podgląd dodanego pliku](https://user-images.githubusercontent.com/65562502/172601204-a1d67e53-dca4-4a83-9ef8-692dad2c5db0.png)

Tytuł "Testowa faktura" w lewym górnym rogu odczytywana jest dobrze, jak w oryginalnym pliku, więc zakładam, że to jakiś problem z odczytywaniem dalszej zawartości po stronie mojego skryptu.

Istotny fragment kodu wygląda następująco:

`            if(postNewInvoiceResult.status === 201)
            {
                const newLink = linkGenerator.getAllegroLinkBase(appType,`/order/checkout-forms/${payload.orderId}/invoices/${postNewInvoiceResult.data.id}/file`);
                axiosInstance.defaults.headers.common['Content-Type'] = "application/pdf";

                let file_contents = fs.readFileSync(__dirname +`/files/test.pdf`, "binary");
                const allegroFileUpload = await axiosInstance.put(newLink, file_contents , {
                    headers: {"Content-Type": 'application/pdf'}
                }).catch((error)=>
                {
                    console.log(error.response.data.errors);
                })
            }
            else
            {
                console.log("Could not post new invoice");
                console.log(postNewInvoiceResult);
                response.json({
                    success: false,
                });
                response.end();
            }`

W dokumentacji widnieje, że dane powinny być przekazywane jako:
_string <binary>
File in a binary format_

Co w teorii pokrywa się z parametrem "encoding" podanym w  fs.readFileSync.
https://nodejs.org/api/fs.html#fsreadfilesyncpath-options

Oprócz wartości "binary" i jego zamiennika "latin1" testowałem również "ascii" i "utf8". Efekt jest zawsze ten sam.

Poglądowy fragment odczytanego pliku przez mój kod:

![fragment odczytanego pliku](https://user-images.githubusercontent.com/65562502/172604358-c0122c40-1ce5-485d-b5c5-d4aa1f2e6f16.png)

Co może być powodem takiego zachowania?

**Comment by Lukasz-Zurek** [comment]
Z uwagi na dużą liczbę języków programowania nie prowadzimy wsparcia dla każdego z nich. Być może któryś z użytkowników forum napotkał podobny problem i będzie w stanie pomóc.

**Comment by samuelslak** [comment]
Rozumiem.  W takim razie zadam troszkę inaczej pytanie:
Czy string reprezentujący plik może zawierać znaki nowej linii? Jak jest to interpretowane po stronie endpointu? Chodzi mi stricte o /n

![test](https://user-images.githubusercontent.com/65562502/173349909-6d4874b3-f1c5-4fb2-8b53-369f1ee1db84.png)

**Comment by Lukasz-Zurek** [comment]
Czy jak korzystasz z `writeFileSync` to czy czyta Tobie cały plik? Generalnie wygląda na to, że plik nie jest przekazywany w całości.

Co do znaków nowej linii - pozwól proszę, że dopytam i wrócę do Ciebie z informacją.

**Comment by samuelslak** [comment]
Koniec data'y zawiera jeszcze 78 tyś. znaków oprócz tego co zobaczyłeś powyżej. Ponadto logując całość, na końcu widzę %%EOF, więc wydaje mi się, że to całość.

![Zrzut ekranu 2022-06-13 o 15 42 35](https://user-images.githubusercontent.com/65562502/173367293-0b70a995-c0fe-495d-90d8-aab2f5ee5750.png)

Testowałem jeszcze na paru innych metodach odczytu plików i generalnie otrzymuje ciągle to samo. Jedynym moim tropem na ten moment są line breaki, więc czekam na odpowiedź :)

**Comment by Lukasz-Zurek** [comment]
Wszystko wskazuje na to, że problematyczne są znaki nowej linii. Nie odnotowaliśmy tutaj innych błędów, które mogłyby wpłynąć na brak contentu pliku PDF. Spróbuj przekazać część binarną bez wspomnianych znaków.

**Comment by samuelslak** [comment]
Udało się doprowadzić faktury do porządku. Problemem nie były znaki nowej lini lecz sposób przekazywania danych. Zamiast wkładać zdekodowany string typu binary (latin1) należało posłać axiosem cały buffer bez dekodowania jak w poniższej postaci:

<Buffer 25 50 44 46 2d 31 2e 34 0a 25 d3 eb e9 e1 0a 31 20 30 20 6f 62 6a 0a 3c 3c 2f 54 69 74 6c 65 20 28 4f 66 65 72 74 61 29 0a 2f 50 72 6f 64 75 63 65 72 ... >
