### ISSUE TITLE
Zmiana sposobu wystawiania ofert na /sale/product-offers

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5775]
Przerabiamy naszą integrację, aby proces wystawiania oraz edycji ofert odbywał się poprzez /sale/product-offers. Posiadamy wgrane dwa razy to samo zdjęcie i przy próbie wystawiania otrzymujemy błąd:

`Offer image `https://a.allegroimg.allegrosandbox.pl/original/11f963/69c2baa240cc93cc9c5365542421` was specified multiple times`

Do tej pory nie było z tym problemu - czy w przypadku POST /sale/product-offers nie mogę posiadać w galerii dwóch takich samych zdjęć? W przypadku POST /sale/offers nie było to problemem, tak samo wystawiając przez formularz można wgrywać kilka takich samych zdjęć

W załączniku przesyłam pełny kod odpowiedzi
[zrzut.txt](https://github.com/allegro/allegro-api/files/8869523/zrzut.txt)

**Comment by Lukasz-Zurek** [comment]
Tak, potwierdzam, że w przypadku skorzystania z POST /sale/product-offers nie możesz przekazać w galerii dwóch takich samych zdjęć.
