### ISSUE TITLE
Wyłączanie zasobu /sale/offers

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5777]
Na początku 2024 roku wyłączacie zasoby /sale/offers służące do tworzenia i edycji ofert. Czy zasoby sale/product-proposals pozostają bez zmian? Pytam, ponieważ przerabiamy naszą dotychczasową integrację i przez przypadek zostawiliśmy mechanizm tworzenia nowego produktu i okazało się, że nasze rozwiązanie jest kompatybilne z /sale/product-offers. Zastanawiamy się czy pozostawić ten mechanizm

**Comment by MaciejFrackowiak** [comment]
Tak, zasoby /sale/product-proposals wpisują się w ścieżkę produktową związaną bezpośrednio z zasobami /sale/product-offers, które będą dostępne.
