### ISSUE TITLE
Zmiany 06.06

### ISSUE THREAD

**Issue by luxisallegro** [allegro/allegro-api#5778]
Witam,

06 czerwca (wtorek) przestało mi działać API, tzn. nie wiem jeszcze co jest przyczyną, czy tego dnia wchodziły w życie jakieś zmiany? coś się zmieniło? nie widzę żadnego newsa o czymkolwiek co miałoby się zmienić 06 czerwca.

Pozdrawiam

**Comment by luxisallegro** [comment]
błąd jest taki:
Błąd w komunikacji z API - {"error":"authorization_pending","error_description":"User has not authorized the device code yet."}

na forum jest temat z takim błędem ale nie ma podanego rozwiazania

https://github.com/allegro/allegro-api/issues/2429?fbclid=IwAR3w7G8kgTTONwOQA7_nOj0nwYvIvN1rYLjLRt_jXWvK2i2tYhLSw9bp2jw

**Comment by MaciejFrackowiak** [comment]
6 czerwca 2022 wyłączyliśmy zasób GET /sale/offers/{offerId}/shipping-rates - informowaliśmy o tym w poście https://github.com/allegro/allegro-api/issues/5660. Nie jest to jednak bezpośrednio powiązane z funkcjonowaniem samej autoryzacji.

**Comment by luxisallegro** [comment]
a czy Wy możecie jakos pomoc? moj programista znowu tego nie ogarnia xd i nie wie w czym problem, niby konfiguruje tak jak poprzednio a mimo to ciagle nie ma polaczenia z api ; /
w sensie, czy mozecie jakos zdiagnozowac przyczyne, blad?

**Comment by MaciejFrackowiak** [comment]
Abyśmy mogli cokolwiek zweryfikować potrzebujemy przykładowych wywołań i odpowiedzi (najlepiej z trace-id), ponieważ tylko tak możemy przeszukać nasze logi. Najlepszym rozwiązaniem byłoby, aby Twój programista skontaktował się z nami bezpośrednio na GitHubie lub poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
