### ISSUE TITLE
External id in offers/listing REST API

### ISSUE THREAD

**Issue by ivansurov** [allegro/allegro-api#578]
Hello,
Why does not the method offers/listing return a external offer ID? 
Is it possible to receive external offer ID in this method offers/listing?
Otherwise, I have to call the method sale/offers/{offer_ID} every time.

**Comment by TomekKaczmarek** [comment]
@ivansurov  GET offers/listing provides only basic and public data regarding the offers. We are working on additional resources specifically suited for sellers, which will provide you with more detailed offer list.
