### ISSUE TITLE
Własne parametry przy wystawianiu oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5780]
W jaki sposób za pomocą /sale/product-offers przekazać własne parametry? W przypadku tworzenia draftu oferty za pomocą /sale/offers było pole customParameters

**Comment by MaciejFrackowiak** [comment]
Obecnie zasoby /sale/product-offers nie wspierają jeszcze własnych parametrów. Mamy to na uwadze i z pewnością pojawią się w przyszłości.

**Comment by mateuszcom** [comment]
Jeszcze jedno pytanie - w jaki sposób przekazywać opcje promowania w przypadku tworzonych ofert za pomocą POST /sale/product-offers? Do tej pory przekazywało się taką informację w strukturze dla POST /sale/offers

**Comment by MaciejFrackowiak** [comment]
Do zarządzania opcjami promowania przeznaczone są dedykowane zasoby - włączysz je przy pomocy [POST /sale/offers/{offerId}/promo-options-modification](https://developer.allegro.pl/documentation/#operation/modifyOfferPromoOptionsUsingPOST) lub [PUT /sale/offers/{offerId}/promo-options-modification](https://developer.allegro.pl/documentation/#operation/promoModificationCommandUsingPUT). Szczegółowo proces opisaliśmy w [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#jak-zarzadzac-promowaniem).

**Comment by g-radzio** [comment]
Czy wiadomo już, kiedy w zasobach /sale/product-offers dodana zostanie obsługa własnych parametrów?
Zasoby /sale/offers są już oznaczone jako Deprecated, ale bez tego nie mogę się jeszcze całkowicie przestawić na używanie  /sale/product-offers
