### ISSUE TITLE
Czy dane są aktualne?

### ISSUE THREAD

**Issue by badgyro** [allegro/allegro-api#5782]
Dzień dobry

Próbuję pobrać parametry kategorii:
https://api.allegro.pl/sale/categories/260041/parameters

W odpowiedzi dostaję oczekiwane dane jednak mam wrażenie że nie są aktualne.
Konkretny przykład to "Kolor" który przy edycji na stronie jest wymagany jednak API zwraca że nie jest wymagany.

`"id": "204789",
"name": "Kolor",
"required": false,
"requiredForProduct": false,`

Przeszukałem kod w poszukiwaniu niechcianego cachowania jednak nic nie znalazłem.
Czy istnieje możliwość że dane z API nie są aktualne z danymi na stronie?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Sprawdziłem przed momentem stan na stronie WWW - parametr Kolor w kategorii 260041 jest opcjonalny. Zgadza się to z flagą false przy parametrze w API.
![image](https://user-images.githubusercontent.com/53566763/173281752-fa2c02cf-056f-4c7b-8533-ef0ac8a6bb89.png)

**Comment by badgyro** [comment]
Screenshot który otrzymałem od klienta:

![image](https://user-images.githubusercontent.com/24192094/173533648-c8e3e0c6-7970-4f9f-8fd9-7fe141645081.png)

**Comment by badgyro** [comment]
Własnie zauważyłem że API już zwraca required = true.

Czyli rozumiem że może być lekkie opóźnienie między zmianami na stronie i w API?

**Comment by MaciejFrackowiak** [comment]
Nie powinno być takiej różnicy - mechanizm do masowego uzupełniania parametrów opiera się na innej usłudze i być może tam dane zostały wcześniej już przetworzone. Ciężko mi się dokładnie wypowiedzieć, ponieważ nie jest to temat stricte powiązany z funkcjonowaniem samego API.

**Comment by badgyro** [comment]
Ok dziękuje za informacje.
