### ISSUE TITLE
Nie aktywują się zakończone oferty.

### ISSUE THREAD

**Issue by drzemik** [allegro/allegro-api#5783]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x ] inny / other

:beetle: **Opis / Description**

Mam około 100 zakończonych ofert. które nie aktywowują się.
Powyżej cURL,request i response jednej z nich, a struktura poniżej:
{
    "id": "12051936628",
    "name": "STANLEY POMPA DO WODY NA WIERTARKĘ STA40220",
    "category": {
        "id": "85214"
    },
    "product": {
        "id": "ff41a378-8eb8-42ed-bb66-3ec6bb1e5bf2"
    },
    "parameters": [
        {
            "id": "225693",
            "valuesIds": [],
            "values": [
                "5035048375761"
            ],
            "rangeValue": null
        },
        {
            "id": "224017",
            "valuesIds": [],
            "values": [
                "STA40220"
            ],
            "rangeValue": null
        },
        {
            "id": "248801",
            "valuesIds": [
                "248801_1131795"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "11323",
            "valuesIds": [
                "11323_1"
            ],
            "values": [],
            "rangeValue": null
        },
        {
            "id": "211626",
            "valuesIds": [
                "211626_250654"
            ],
            "values": [],
            "rangeValue": null
        }
    ],
    "customParameters": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/11a74f/2e2d67a64144a5915191f41bac31"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h1>STANLEY&nbsp;STA40220</h1><h2>Pompa do wody na wiertarkę 2500l</h2><p><b>Dane techniczne:</b></p><ul><li><b>Maks. wydajność:</b> 2500 l/h</li><li><b>Wysokość zasysania:</b> 4 m</li><li><b>Średnica trzpienia:</b> 8 mm</li><li><b>Przyłącza węża:</b> 19 mm (3/4”)</li><li><b>Max długość węża:</b> 40 m</li></ul><p><b>Cechy produktu:</b></p><p>Praktyczna, mała pompa o szerokim zakresie zastosowań.</p><p>Do napędu stosuje się dowolną wiertarkę lub wkrętarkę elektryczną.</p><p>Obudowa z tworzywa sztucznego.</p>"
                    },
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/117fa9/51e5c09d4f11a8bf1c4eeb600e5a"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/110a08/64f7a9ea40fe8ac6d8de4104482b"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "IMAGE",
                        "url": "https://a.allegroimg.com/original/114222/09b1077c4f198da5cdfcb3600627"
                    }
                ]
            }
        ]
    },
    "compatibilityList": null,
    "tecdocSpecification": null,
    "images": [
        {
            "url": "https://a.allegroimg.com/original/117fa9/51e5c09d4f11a8bf1c4eeb600e5a"
        },
        {
            "url": "https://a.allegroimg.com/original/110a08/64f7a9ea40fe8ac6d8de4104482b"
        },
        {
            "url": "https://a.allegroimg.com/original/11a74f/2e2d67a64144a5915191f41bac31"
        },
        {
            "url": "https://a.allegroimg.com/original/114222/09b1077c4f198da5cdfcb3600627"
        }
    ],
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "68",
            "currency": "PLN"
        },
        "startingPrice": null,
        "minimalPrice": null,
        "netPrice": null
    },
    "tax": null,
    "stock": {
        "available": 1,
        "unit": "UNIT"
    },
    "publication": {
        "duration": null,
        "status": "ENDED",
        "startingAt": null,
        "endingAt": null,
        "endedBy": "USER",
        "republish": false
    },
    "delivery": {
        "shippingRates": {
            "id": "de811550-8378-406d-a13c-0543e8eaeef1"
        },
        "handlingTime": "PT24H",
        "additionalInfo": "",
        "shipmentDate": null
    },
    "payments": {
        "invoice": "VAT"
    },
    "discounts": null,
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "94af0b71-d2ac-4f15-9c97-ecea438f1e8f"
        },
        "returnPolicy": {
            "id": "d20bfbcb-03bb-46b2-9231-56c31389fbfc"
        },
        "warranty": null
    },
    "additionalServices": null,
    "sizeTable": null,
    "fundraisingCampaign": null,
    "promotion": {
        "emphasized": false,
        "bold": false,
        "highlight": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": false
    },
    "location": {
        "countryCode": "PL",
        "province": "MAZOWIECKIE",
        "city": "Mościska",
        "postCode": "05-080"
    },
    "external": {
        "id": "SF-STA40220"
    },
    "attachments": [],
    "contact": null,
    "validation": {
        "errors": [],
        "warnings": [],
        "validatedAt": "2022-05-18T17:20:01.091Z"
    },
    "b2b": {
        "buyableOnlyByBusiness": false
    },
    "messageToSellerSettings": {
        "mode": "OPTIONAL"
    },
    "createdAt": "2022-04-11T12:40:36.000Z",
    "updatedAt": "2022-05-18T20:25:00.943Z",
    "language": "pl-PL"
}

**Comment by MaciejFrackowiak** [comment]
Przykładowa oferta nr 12051936628 nie może zostać aktywowana, ponieważ nie posiada określonych parametrów obowiązkowych Moc silnika, Maksymalna wydajność pompy. Uzupełnij brakujące parametry, a następnij podejmij ponowną próbę aktywacji oferty.
