### ISSUE TITLE
AllegroOneBox - no Access to 'wysylam z Allegro'

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#5784]
probuje przez api nadac paczke do paczkomatu allegroOneBox i za kazdym razem dostej komunikat jak ponizej

Brak dostępu do 'Wysyłam z Allegro'. Aby uzyskać dostęp wystarczy, że przejdziesz na https://allegro.pl/moje-allegro/sprzedaz/wysylam/ustawienia - Twoje konto Allegro połączy się automatycznie

oczywiscie sprawdzalem linka, oraz przez strone allegro potrafie nadac paczke, wiec co jeszcze trzeba zrobic aby moc ta paczke nadac przez API i uzyskac ten sam efekt co poprzez strone

Pawel

**Comment by Lukasz-Zurek** [comment]
Prześlij proszę trace-id dla powyższego wywołania.

**Comment by Pawelpwg** [comment]
nie wiem o ktore id chodzi dokladnie ale mam nadzieje ze to pomoze

respose
id: 16459

{"id":"22aec941-daa2-11ec-a1d3-c73c1491ca01","parcelId":null,"status":"ERROR","errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"Brak dostępu do 'Wysyłam z Allegro'. Aby uzyskać dostęp wystarczy, że przejdziesz na https://allegro.pl/moje-allegro/sprzedaz/wysylam/ustawienia - Twoje konto Allegro połączy się automatycznie"}]}

**Comment by Lukasz-Zurek** [comment]
Upewnij się co do prawidłowości wprowadzanego "serviceId". W przypadku metody dostawy: Allegro One Box prawidłowa usługa to: Allegro One (UPS).

**Comment by Pawelpwg** [comment]
Dzieki faktycznie mialem blad w kodzie i zle dobrane service id

poprawilem request
    "serviceId": **18095360**, "receiver":
    {
        "address": { "street": "Kru", "postCode": "53-000", "city": "wrocław", "countryCode": "PL", "country": null },
        "email": "znsl04oc3v+45e51895@allegromail.pl", "name": "P", "company": "", "phone": "+48 111222333", "pointId": "AL027DW1"
    }, "pickup": { "address": { "street": "K", "postCode": "11-000", "city": "wrocław", "countryCode": "PL", "country": null }, "email": "znsl04oc3v+45e51895@allegromail.pl", "name": "Paweł ", "company": "", "phone": "+48 111 222 333", "pointId": "AL027DW1" }, "items": [{ "dimensions": null, "weight": { "value": 1.0, "unit": "KILOGRAM" }, "description": "1: 1.00kg, (0cm x 0cm x0cm)\r\n test", "value": null, "type": "PACKAGE" }], "type": "PACKAGE", "label": { "sender": { "address": { "street": "kr", "postCode": "53-000", "city": "wroclaw", "countryCode": "PL", "country": null }, "email": "TEST@o2.pl", "name": "ITSmart", "company": "ITSmart", "phone": "111222333" }, "fileFormat": "PDF", "referenceNumber": null },
    "additionalServices": { "cashOnDelivery": null, "options": [] }
}


response wraca z innym serviceId, czy tak powinno byc?

{ "id": "22aec941-daa2-11ec-a1d3-c73c1491ca01", "input": { "serviceId": "**91966**", "label": { "sender": { "name":....


po czym przy sprawdzeniu statusu dostaje ten sam blad co wczesniej


oraz dodatkowe pytanie czy gdzies w checkout form jest zapisane serviceID aby przekazac to bezposrednio do nadania? nie moge tego znalezc

**Comment by Lukasz-Zurek** [comment]
Request jest ok I z tego co widzę - nie odnotowaliśmy tutaj błędów.

Wygląda jednak na to, że w celu sprawdzenia statusu utworzonej paczki korzystasz z tego samego Command Id, dlatego otrzymujesz ten sam błąd. Jako commandId przekaż numer [UUID](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#identyfikatory-zasobow) - wygeneruj go we własnym zakresie tworząc nową przesyłkę. 

Co ważne - dla każdej nowej przesyłki, którą tworzysz - musisz użyć nowego numeru UUID.

Dodam, że w zamówieniach (m.in. w [GET /order/checkout-forms](https://developer.allegro.pl/documentation/#operation/getListOfOrdersUsingGET)) nie zwracamy **"serviceId"**. W sekcji **"delivery"** zwracamy jedynie **"method.id"** i **"method.name"**. W tej sytuacji musisz zmapować po swojej stronie metody dostawy, tak aby móc sprawnie nadawać przesyłki.

**Comment by Pawelpwg** [comment]
"Co ważne - dla każdej nowej przesyłki, którą tworzysz - musisz użyć nowego numeru UUID."

jesli chodzi o uscislenie tego pkt, nowa przesylka to nowy UUID i tutaj ok, ale co w przypadku jesli wracaja bledy z walidacji? tak jak w tym przypadku i chcialem nadac paczke poprawiona, jakie tutaj jest zalozenie ze stworze nowe UUID czy powinienem paczke skasowac i wtedy moge uzyc tego samego ID ponownie, czy bez roznicy

spodziewalem sie ze ponowne nadanie tej samej paczki nadpisze ostatni request i status bedzie wracal dla ostatniego requestu a nie dla pierwszego

**Comment by Lukasz-Zurek** [comment]
Błędy walidacji zwracaliśmy dla wcześniej utworzonej (i błędnej) paczki "22aec941-daa2-11ec-a1d3-c73c1491ca01" - tu nic się nie zmieniło. To UUID odnosi się do wcześniejszej przesyłki.

Ponowne utworzenie tej samej paczki musi się odbyć w ramach nowego UUID i wtedy również odpytując to nowe UUID w statusie utworzonej przesyłki - otrzymasz aktualne informacje.

**Comment by Pawelpwg** [comment]
wszystko fajnie dzialalo na testowych paczkach a u klienta zaczynam dostawac po odpaleniu statusu
{"id":"d6647cc7-23af-4240-9deb-862c73710e91","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Pickup name is required","details":null,"path":"pickup.name","userMessage":"Nazwa punktu nadania przesyłki jest wymagana"}]}

po polewie dnia szukajac bledu okazalo sie ze w nazwie jest tylko jedno slowo, a po wpisaniu dwoch juz jest wszystko ok, jesli moglby zasugerowac to sprawdzac czy pole jest uzupelnione albo podac sensowniejszy komunikat

**Comment by Lukasz-Zurek** [comment]
@Pawelpwg Dziękuję za sugestię. Przekażę ją do odpowiedniego zespołu.

**Comment by Lukasz-Zurek** [comment]
> 
> i jeszcze jedno pytanie czy mozecie podpowiedziec gdzie szukac problemu, przy pobraniu paczki dostaje {"errors":[{"code":"ERROR","message":"Parcel does not exist","details":null,"path":"parcelId","userMessage":"Nie jesteś właścicielem przesyłki"}
> 
> paczki sa nadawane z konta na ktorych zostaly kupione, drukowanie etykiet dziala prawidlowo, rowniez get status, wiec paczka istnieje w systemie

Podaj proszę commandId. Sprawdzę to.

**Comment by Pawelpwg** [comment]
dzieki jednak znalazlem blad po swojej stronie, niestety lub staty moj system dziala na zasadzie plug&play, ale to api ma troche inne przeplywy niz wiekszosc kurierow stad czasami dane sie nie zgadzaja

ale moze tutaj podpowiesz
https://api.allegro.pl/parcel-management/parcels/protocol?parcelId=85404924
wraca noContent i juz nie mam pomyslu dlaczego

traceid: "56207142eb8ea826"

**Comment by Lukasz-Zurek** [comment]
W celu prawidłowego przetworzenia żądania, w nagłówku **Accept** musisz przekazać samą wartość: **application/pdf**.

Ze wskazanego trace-id wnioskuję, że w nagłówku Accept przekazujesz dwie wartości: **application/vnd.allegro.public.v1+json, application/pdf**. Musisz to poprawić.

**Comment by Pawelpwg** [comment]
masz racje ale ten sam mechanizm jest dla etykiet gdzie to dziala bez problemu, 
po usunieciu headera

{Method: GET, RequestUri: 'https://api.allegro.pl/parcel-management/parcels/protocol?parcelId=85404924', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Bearer xxxxxx
  Accept: application/pdf
}}

wraca 

{StatusCode: 204, ReasonPhrase: 'No Content', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  x-xss-protection: 1; mode=block
  pragma: no-cache
  x-frame-options: DENY
  trace-id: a61b748b64906c73
  x-content-type-options: nosniff
  strict-transport-security: max-age=31536000 ; includeSubDomains
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Fri, 01 Jul 2022 08:50:42 GMT
  Expires: 0
}}

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegóły. W takim razie skonsultuję ten problem z zespołem odpowiedzialnym za powyższą funkcjonalność. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@Pawelpwg Protokół nadania przesyłek nie jest generowany dla następujących przesyłek:

- przesyłka międzynarodowa FedEx (drzwi — drzwi)
- przesyłka krajowa InPost Paczkomat (punkt — punkty)
- przesyłka krajowa InPost Paczkomat (punkt — drzwi)
- przesyłka krajowa Orlen Paczka (punkt — punkt)
- przesyłka krajowa Allegro One (drzwi — punkt)
- przesyłka krajowa Allegro One (punkt — punkt)
- przesyłka krajowa Poczta Polska (punkt — drzwi)
- przesyłka krajowa Poczta Polska (punkt — punkt)

W związku z czym błąd `204 no content` jest tu uzasadniony.

**Comment by Pawelpwg** [comment]
ok, dzieki za wyjasnienie, gdzie do dokumentacji mozna by to dodac, chodz z biznesowego pkt widzenia, protokol jest potrzebny do wydania do kuriera paczek, wiec troche nie rozumiem czemu ten protokol nie jest dostepny


jeszcze nie mam kilka pytan
1.
{"id":11577227,"service":"ALLEGRO","name":"Allegro One (UPS)"
{"id":17715424,"service":"ALLEGRO","name":"Allegro One Box (One Kurier)"
{"id":17715425,"service":"ALLEGRO","name":"Allegro One Punkt (One Kurier)"
czym roznia sie te opcje, i z pkt widzenia wystawiajacego aukcje to jaki to jest typ dostawy? bo tam tylko widze allegroOneBox, narazie ustawilem UPS, ale pozostale dwa typy dla jakiego typu dostaw uzywac (api zwraca blad jesli uzyje zle id wiec jest tutaj jakas logika zaszyta)
1a. dlaczego metoda deliveryServices, zwraca rozne id ale tych samych dostaw dla roznych kont? mam klientow ktorzy posiadaja kilkanascie kont zakladalem aby dostawy z allegro zmapowac z odpowiadnia dostawa z api, i zrobic jedno ustawienie globalne, tylko rozne id wymuszaja ze musze robic to per konto. jest jakis powod dlaczego dostawy nie maja takiego samego id? z pkt widzenia uzytkownika koncowego, on w interfejsie bedzie widzial zawsze to samo i bedzie musial robic to per konto

2. czy moge nadac paczke z konta innego niz to na ktorym paczka zostala kupiona?
d

**Comment by Pawelpwg** [comment]
oraz jeszcze jeden problem, musze na etykiete dodac nr fv, ktore pola z requestu wyswietlaja sie na etykiecie? widze pola ref1/2 juz zajete przez was, opis paczki tez nie trafia na etykiete

**Comment by MartaNowaczyk** [comment]
1. 
Poniżej znajdziesz pełne rozróżnienie metod dostawy na serwis:

Metoda dostawy: Allegro One Punkt (UPS) -> Serwis: Allegro One (UPS)
Metoda dostawy: Allegro One Box (UPS) -> Serwis: Allegro One (UPS)
Metoda dostawy: Allegro One Punkt (One Kurier) -> Serwis: Allegro One Punkt (One Kurier) (na Sandbox: Allegro One Punkt (One Kurier) - dostawa jutro)
Metoda dostawy: Allegro One Box (One Kurier) -> Serwis:Allegro One Box (One Kurier) (na Sandbox: Allegro One Box (One Kurier) - dostawa jutro)
Metoda dostawy: Allegro One Kurier - dostawa dzisiaj -> Serwis: Allegro One Kurier
Metoda dostawy: Allegro One Kurier - dostawa jutro -> Serwis: Allegro One Kurier

1a.
Ze względu na kwestie techniczne jak i biznesowe, stad id jest dla danego konta.

> oraz jeszcze jeden problem, musze na etykiete dodac nr fv, ktore pola z requestu wyswietlaja sie na etykiecie? widze pola ref1/2 juz zajete przez was, opis paczki tez nie trafia na etykiete
Doprecyzuj proszę jakiej usługi to dotyczy, bo w każdej może być inaczej.







[13:49](https://allegro.slack.com/archives/DG4AYEM7Y/p1657280964515129)
ad 2 - to zalezy pewnie od uslugi, jedni pozwalaja, drudzy nie

**Comment by MartaNowaczyk** [comment]
1. 
Poniżej znajdziesz pełne rozróżnienie metod dostawy na serwis:

Metoda dostawy: Allegro One Punkt (UPS) -> Serwis: Allegro One (UPS)
Metoda dostawy: Allegro One Box (UPS) -> Serwis: Allegro One (UPS)
Metoda dostawy: Allegro One Punkt (One Kurier) -> Serwis: Allegro One Punkt (One Kurier) (na Sandbox: Allegro One Punkt (One Kurier) - dostawa jutro)
Metoda dostawy: Allegro One Box (One Kurier) -> Serwis:Allegro One Box (One Kurier) (na Sandbox: Allegro One Box (One Kurier) - dostawa jutro)
Metoda dostawy: Allegro One Kurier - dostawa dzisiaj -> Serwis: Allegro One Kurier
Metoda dostawy: Allegro One Kurier - dostawa jutro -> Serwis: Allegro One Kurier

1a.
Ze względu na kwestie techniczne jak i biznesowe, stad id jest dla danego konta.

> oraz jeszcze jeden problem, musze na etykiete dodac nr fv, ktore pola z requestu wyswietlaja sie na etykiecie? widze pola ref1/2 juz zajete przez was, opis paczki tez nie trafia na etykiete

Doprecyzuj proszę jakiej usługi to dotyczy, bo w każdej może być inaczej.

**Comment by Pawelpwg** [comment]
1. wiec dla kazdego konta allegro id sa rozne, ale pod spodem jest logika ktora nie pozwala nadac paczki inaczej niz wybral klient, sprzydalo by sie w takim razie jakas metoda ktora pozwala zamienic wybrana dostawe z allegro na deliveryService w api. od strony programistycznej jedyny sposob aby to teraz zrobic u mnie, to porownywanie stringow wedlug rozpiski ktora podeslales co bedzie dzialac poki nie zmienicie nazw :/ 
2. dodatkowe pole na protokole: narazie uzywam Allegro One Punkt (UPS), ale potrzebuje tej informacji dla 4 pierwszych typow dostaw wymienionych wyzej 
3. czy moge nadac paczke z konta innego niz to na ktorym paczka zostala kupiona?
4. item.description - dostalem blad ze za dlugi opis dodalem, jaka jest maksymalna dlugosc? w dokumentacji nie ma tej informacji

**Comment by Pawelpwg** [comment]
5. w przypadku zamawiania kuriera, gdy klient ma wiele kont, zamowic go z jednego konta wystarczy czy z kazdego osobna?

**Comment by MartaNowaczyk** [comment]
1. O zmianie nazw informujemy z wyprzedzeniem, także będziesz miał czas na wprowadzenie zmian.
2. W przypadku etykiet dla:

* Allegro One (UPS) pole jest już przez nas zajęte (pojawia się tam numer paczki). Więc na tych etykietach nic więcej już się nie zmieści.
* dla Allegro One (One Kurier) tutaj powinna być widoczna wartość z pola description.
4. Nie
5. Jeżeli chodzi o długość pola description - ogólnie jest to od 2 do 100 znaków, choć zależy to od konkretnego przewoźnika:
* DHL — wymagany (od 2 do 30 znaków)
* DPD — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
* FedEx — wymagany (od 2 do 100 znaków)
* GLS — opcjonalny (od 2 do 100 znaków)
* InPost — opcjonalny (od 2 do 100 znaków)
* InPost Kurier — opcjonalny (od 2 do 100 znaków, jeżeli kraj odbiorcy to "PL")
* Poczta Polska — opcjonalny (od 2 do 100 znaków)
* ORLEN Paczka — opcjonalny (od 2 do 100 znaków)
* UPS — opcjonalny (od 2 do 50 znaków, jeżeli kraj odbiorcy "PL")
* Allegro — wymagany (od 2 do 50 znaków — jak w UPS) 
6. Nie, nie można w jednym zleceniu przekazać paczek z różnych kont. Możesz jednak złożyć zlecenie dla paczek z jednego konta, a kurier może odebrać pozostałe przesyłki. Oczywiście to kwestia już "dogadania się" z kurierem czy w taki sposób to odbierze.
