### ISSUE TITLE
Etykieta nie istnieje dla paczek DPD - Wysyłam z Allegro

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5785]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam,
mam taki problem, że dla nowoutworzonych paczek DPD nie istnieje etykieta, którą można pobrać.
Trace-Id: d7ca20ed4000536c

```
https://api.allegro.pl/parcel-management/parcels/label?parcelId=83193809
{
    "errors": [
        {
            "code": "ERROR",
            "message": "Label doesn't exist",
            "details": null,
            "path": "/parcel-management/parcels/label?parcelId={parcelId}",
            "userMessage": "Etykieta nie istnieje"
        }
    ]
}
```

**Comment by AureliuszBrussy** [comment]
Próbujesz pobrać etykietę korzystając z nieprawidłowego access_tokena - przesyłka została utworzona przez innego użytkownika.

**Comment by hahyes** [comment]
> Próbujesz pobrać etykietę korzystając z nieprawidłowego access_tokena - przesyłka została utworzona przez innego użytkownika.

Zagapiłem się, przepraszam. Pozdrawiam serdecznie.
