### ISSUE TITLE
Dziwny problem z wystawieniem oferty poprzez API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5788]
Mamy problem z wystawieniem oferty w produkcyjnym Allegro dla produktu o ID: a01736b3-ed5b-435f-8bc7-f767d9c7d44f

Problem jest z parametrem MARKA. W produktyzacji dodana jest wartość "Inna (Kruger Matz)". Wygląda na to, jakby w międzyczasie marka Kruger&Matz została dodana do rozwijanej listy.

W tym momencie występuje konflikt. Nie jesteśmy w stanie wystawić takiego produktu.

1. W przypadku, gdy wybieramy z rozwijanej listy wartość Kruger&Matz otrzymujemy komunikat: "Invalid parameter Brand (248135) value for offer with product. Value should be "Kruger Matz"."
2. Przy wyborze INNA oraz podaniu wartości Kruger Matz otrzymujemy komunikat: "Value 'Kruger&Matz' already exists in parameter 'Marka'"

Czyli robi się błędne koło. Jak to możemy rozwiązać z poziomu API?

**Comment by MaciejFrackowiak** [comment]
Możesz zgłosić sugestię zmiany w produkcie korzystając z [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). Rzeczywiście, marka Kruger&Matz występuje już w słowniku wartości, dlatego niezbędne jest poprawienie wartości w produkcie.

**Comment by shambo666** [comment]
Ten problem jest u nas na porządku dziennym... W zasadzie uniemożliwia w pełni korzystanie z produktyzacji przez API...
Najnowszy przypadek to produkt `3c61b088-2d9d-4e64-b495-acc2c1ca31b8`
Nie da się takiej oferty poprawić w żaden sposób - ani poprzez API ani przez formularz WWW bo tam też występuje podobny błąd:
![image](https://user-images.githubusercontent.com/63442925/175885713-97d6502a-f49a-4ad4-badf-ab8491685bcf.png)
Jedynym rozwiązaniem jest odłączenie produktu od oferty.

> Możesz zgłosić sugestię zmiany w produkcie korzystając z [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal). Rzeczywiście, marka Kruger&Matz występuje już w słowniku wartości, dlatego niezbędne jest poprawienie wartości w produkcie.

Takich produktów jest za dużo żeby wszystkie zgłaszać... A co robić w czasie oczekiwania na zmianę? Nie sprzedawać? Potrzebna jest jakaś zmiana na poziomie walidacji ofert... Jeżeli chcecie narzucić 100% produktyzacji to musicie rozwiązać ten i inne błędy...

**Comment by MaciejFrackowiak** [comment]
@shambo666 Ze swojej strony mogę wyłącznie Cię zachęcić do zgłaszania sugestii zmian w produktach. Swoje uwagi dot. katalogu produktów i organizacji jego działania możesz przekazać poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
