### ISSUE TITLE
Wysyłam Allegro - Allegro Poczta - Pickup point is incorrect

### ISSUE THREAD

**Issue by magik092** [allegro/allegro-api#5789]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas tworzenia przesyłki dla klienta uvtzrrcfd7+4b1d55468@allegromail.pl na adres prywatny (nie punkt odbioru) metodą Allegro Poczta zostaje zwrócony błąd "Pickup point is incorrect" (pickup.pointId). Punkt nadania jest ustawiony jako adres fizyczny, nie punkt odbioru (sprzedawca chce aby kurier odebrał przesyłkę) - point_id jest null'em. Co może być przyczyną tego problemu?

trace-id: 6cd17c28a572da50
command-id: a6ec4abc-e949-4bdd-b0b3-7e27e3f63913

**Comment by MaciejFrackowiak** [comment]
Dla przesyłek Poczty Polskiej należy wskazać punkt nadania (placówkę nadawczą). Jednocześnie dodam, że poprawimy komunikat błędu, aby był bardziej czytelny.

**Comment by magik092** [comment]
@MaciejFrackowiak dzięki za odpowiedź. W takim razie przekazujemy klientowi aby dla Poczty Polskiej wybrał placówkę nadania - identyfikator punktu zostanie wstawiony do pola `pickup.pointId`.
