### ISSUE TITLE
Publikacja oferty

### ISSUE THREAD

**Issue by SoftWareMG** [allegro/allegro-api#579]
Witam,

Mam problem z publikacją tej oferty 7549813819.
Do wystawienia tej aukcji wykorzystuje dane z aukcji: 5419383624. Wystawiam podobna.

Błąd jaki otrzymuję podczas próby aktywacji aukcji:
"Could not change offer publication status. Delivery price list may not be empty"

W czym może być problem?

Draft jaki wysyłam do allegro to: 

{"name":"WYCIOR Szczotka Kominiarska 175mm Stalowy Drut !!!","category":{"id":"27963"},"parameters":[{"id":"11323","valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":"11325","valuesIds":["11325_2"],"values":[],"rangeValue":null}],"ean":null,"description":{"sections":[{"items":[{"type":"TEXT","content":"<h2>Materiał:</h2>\n<p>Stal</p>\n<h2>Ilość:</h2>\n<p>1 szt.</p>\n<h2>Przeznaczenie:</h2>\n<p>Wycior przeznaczony jest do czyszczenia przewodów kominowych.</p>\n<p>Szczotka jest zakończona standardowym gwintem M12, który umożliwia jej łączenie z Kulami lub Oprawami kominiarskimi.</p>\n<p>Sprawdź POZOSTAŁE ROZMIARY WYCIORÓW na naszych pozostałych aukcjach.</p>\n<p>Przedmiotem niniejszej aukcji jest wyłącznie Wycior kominiarski.</p>\n<p>Kategoria produktu: SZKS</p>"},{"type":"IMAGE","url":"https://6.allegroimg.com/original/03b3ac/eeebdfb14c79883d9b73fbbd52d6"}]},{"items":[{"type":"IMAGE","url":"https://c.allegroimg.com/original/0364db/60b6e6bd441bb0de9ae0af69765c"},{"type":"TEXT","content":"<p><b>ΦD [mm]:</b> 175</p>\n<p><b>L [mm]:</b> 110</p>\n<p><b>A [mm]:</b> 60</p>\n<p><b>GWINT:</b> M12</p>"}]},{"items":[{"type":"IMAGE","url":"https://1.allegroimg.com/original/0346f6/8bccd00242eba57522d8bd7d3f51"},{"type":"IMAGE","url":"https://c.allegroimg.com/original/03377a/c27c15e14f4c97f043368fa34eac"}]}]},"compatibilityList":null,"images":[{"url":"https://6.allegroimg.com/original/03b3ac/eeebdfb14c79883d9b73fbbd52d6"},{"url":"https://c.allegroimg.com/original/03377a/c27c15e14f4c97f043368fa34eac"},{"url":"https://1.allegroimg.com/original/0346f6/8bccd00242eba57522d8bd7d3f51"},{"url":"https://c.allegroimg.com/original/0364db/60b6e6bd441bb0de9ae0af69765c"}],"sellingMode":{"format":"BUY_NOW","price":{"amount":"23.99","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"stock":{"available":10000,"unit":"UNIT"},"publication":{"duration":null,"startingAt":null,"endingAt":null},"delivery":{"shippingRates":{"id":"746f670c-f812-4bd4-8c2e-96372cb92279"},"handlingTime":"PT48H","additionalInfo":"","shipmentDate":null},"payments":{"invoice":"VAT"},"afterSalesServices":{"impliedWarranty":{"id":"85815382-d6e8-4b57-af86-dfda2f5518e7"},"returnPolicy":{"id":"df0ba005-8b86-4731-a3a2-1497ed4e7fcb"},"warranty":{"id":"2ea8b860-9033-4d57-a414-1b0c01e46a87"}},"additionalServices":null,"sizeTable":null,"promotion":{"emphasized":false,"bold":false,"highlight":false,"departmentPage":false,"emphasizedHighlightBoldPackage":false},"location":{"countryCode":"PL","province":"ZACHODNIOPOMORSKIE","city":"Police","postCode":"72-010"},"external":null,"contact":null}

**Comment by TomekKaczmarek** [comment]
Upewnij się, czy na pewno podałeś poprawny ID cennika dostawy:
"delivery": {
		"shippingRates": {
			"id": "746f670c-f812-4bd4-8c2e-96372cb92279"
		},

1/ Czy cennik o takim ID w ogóle istnieje?
2/ Czy cennik o takim ID należy do konta, na którym wystawiasz ofertę?
