### ISSUE TITLE
Jak z autoryzować przez /.well-known/openid-configuration w Authorization Code flow

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5790]
Użyłem biblioteki https://github.com/damienbod/angular-auth-oidc-client 
Tam jest miechanizm .well-known/openid-configuration. 
![image](https://user-images.githubusercontent.com/6718212/173570447-a1828b7d-f4d8-4098-9ba5-e747d810ed1c.png)
Obsługuje go allegro ?

**Comment by MaciejFrackowiak** [comment]
Nie wskazujemy konkretnych narzędzi, które można wykorzystać przy użytkowaniu API Allegro. Być może któryś z użytkowników będzie mógł Tobie pomóc w tej kwestii.

**Comment by MaciejFrackowiak** [comment]
@hahyes Dziękuję za Twoje wsparcie i potwierdzam, że nie wykorzystujemy tego rozwiązania.

**Comment by silverwind85** [comment]
To jaką wersję oauth wykorzystujecie ?

**Comment by MaciejFrackowiak** [comment]
@silverwind85 Wykorzystujemy OAuth2, jednak bez wykorzystania tego mechanizmu. Wszelkie kwestie związane z autoryzacją opisujemy w [poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).

**Comment by bjurga** [comment]
Sorry, że odgrzewam kotleta, ale...
Tak sie zastanawiam czy wystawienie takiego JSONa pod /.well-known/ adresem to taki czelendż?

W późniejszym terminie możecie nawet wymusić jego używanie i zyskać dość dużą elastyczność, bo będziecie mogli cichutko zmieniać np URLe, a apki klijentów zaczytają se nowe dane. Albo nawet dzielić se apki per client podając inny config w zapytaniu jak z 2go linku poniżej: https://allegrp.pl/auth/oauth/.well-known/oauth-authorization-server?client_id=MOJ_CLIENT_ID
Moim zdaniem bajka!

Wincy info:
- https://datatracker.ietf.org/doc/html/rfc8414#section-3
- https://developer.okta.com/docs/reference/api/oidc/#well-known-oauth-authorization-server    

Jakie są szanse, żebyście wystawili statyczny plik z JSONem?

**Comment by MaciejFrackowiak** [comment]
@bjurga W najbliższej przyszłości nie planujemy wprowadzenia takiej aktualizacji.
