### ISSUE TITLE
Allegrosandbox - Płatności

### ISSUE THREAD

**Issue by grzegorzn1** [allegro/allegro-api#5791]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Proszę o odblokowanie sprzedaży dla konta: j.kowal3333@wp.pl ( zablokowana z powodu nieoplaconych rachunków :-) )

**Comment by MaciejFrackowiak** [comment]
Swoje zobowiązania możesz uregulować poprzez symulator płatności na stronie [Rozliczenia z Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro).

**Comment by grzegorzn1** [comment]
Wybieram płatność przez Blik, wpisuje kod i dostaję...
"Płatność odrzucona
Zaksięgowanie wpłaty nie powiodło się. Spróbuj ponownie."

**Comment by MaciejFrackowiak** [comment]
Twoje płatności są już uregulowane - czasami warto skorzystać z alternatywnej metody, np. szybki przelew, gdy pojawiają się trudności z inną metodą.

**Comment by JacekStawicki360** [comment]
Niestety platnosci na sandbox nie dzialaja. Zadna z metod.
Konto: 360sprzedawca


![image](https://user-images.githubusercontent.com/88323215/174983155-249741ff-b581-488f-a57b-c57f482dee8a.png)
