### ISSUE TITLE
Allegrosandbox -  wysyłka e-mail z załącznikiem do klienta i podłączenie faktury PDF pod zamówienie

### ISSUE THREAD

**Issue by grzegorzn1** [allegro/allegro-api#5792]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Czy ktoś z Państwa używał na bazie MSSQL procedury sp_send_dbmail wbudowanej w baze danych 
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-send-dbmail-transact-sql?view=sql-server-ver16
do wysyłki e-maili do klienta z załącznikiem .pdf (po wysłaniu na unikalny adres e-mail do klienta z zamówienia powinna się dołączyć faktura zakupu) ?
Dziekuję

**Comment by grzegorzn1** [comment]
Dodam że jeśli próbuje wysłać za pomocą tej procedury e-mail z załącznikiem .pdf do klienta (e-mail unikalny allegro) to dostaje tylko treść bez załącznika a plik .pdf nie podłącza się pod zamówienie. 
Jeśli natomiast wyślę na jakikolwiek inny e-mail to treść i załącznik się pojawiają.
Ktoś z Państwa ma jakieś pomysły?

**Comment by MaciejFrackowiak** [comment]
Jako Allegro niestety nie korzystamy z powyższego rozwiązania - być może któryś z użytkowników forum będzie mógł Tobie pomóc.

**Comment by grzegorzn1** [comment]
Może Państwo mają w php rozwiązane coś takiego, jeśli tak to poproszę kod.
Dziękuję

**Comment by MaciejFrackowiak** [comment]
Niestety, nie posiadamy przykładów w różnych językach programowania.
