### ISSUE TITLE
Dyskusje - błąd na froncie

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#5794]
po opublikowaniu odpowiedzi na negatywa w treści pojawia się "Odpowiedź z dnia {{answerDate}} 15 cze 2022".
klient tego nie widzi, widoczne jest w panelu sprzedawcy "twoje oceny"
wiem ,że to nie api
proszę przekazać do odpowiedniego działu i zamknąć

**Comment by AureliuszBrussy** [comment]
Bardzo prosiłbym o zgłoszenie tego przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), najlepiej z dołączonym np. zrzut ekranu z widocznym błędem.
