### ISSUE TITLE
how to send zero stock using sale/offer-quantity-change-commands

### ISSUE THREAD

**Issue by all901** [allegro/allegro-api#5795]
Hello everybody. 
I need your help. 
I can't send zero stock using sale/offer-quantity-change-commands

https://developer.allegro.pl/documentation#operation/quantityModificationCommandUsingPUT

There is no changes if I am sending zero stock using **sale/offer-quantity-change-commands**

What to do if products are out of stock ?

Activating and deactivating offer needs much more recourses as we need first to get current status, then deactivate all active products with zero stock. For reactivation of non active products on stock. we have to check the reason of deactivation. Maybe it was deactivated by manager because need repacking.

**Comment by MaciejFrackowiak** [comment]
It is correct - you cannot set 0 as a stock value.
You have to deactivate offer with [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) to stop selling products.
