### ISSUE TITLE
Brak uprawnień przy wywoływaniu /sale/offers

### ISSUE THREAD

**Issue by szymonkrygier** [allegro/allegro-api#5796]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy wywoływaniu GET /sale/offers otrzymuję komunikat: Access denied. Contact the author of the application.

Zweryfikowałem uprawnienia aplikacji i są poprawne - zaznaczone są wszystkie pozycje.

**Comment by MaciejFrackowiak** [comment]
Aby korzystać z tego zasobu musisz korzystać z autoryzacji typu "bearer-token-for-user", czyli [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow.

**Comment by szymonkrygier** [comment]
Korzystam z tego typu autoryzacji. :)

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowy trace-id swojego wywołania.

**Comment by szymonkrygier** [comment]
35039ebc6d96a89d

**Comment by szymonkrygier** [comment]
Racja, teraz jest dobrze. Miałem ustawiony tylko Content-type. :)
Za bardzo zagłębiłem się w treść komunikatu jaki od Was otrzymałem w response i myślałem, że to coś po Waszej stronie..

Bardzo dziękuje, zamykam.
