### ISSUE TITLE
Nie można stworzyć przesyłki Allegro ONE "Order cannot be send using selected delivery service"

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#5797]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Próba weryfikacji utworzenia paczki Allegro ONE skutkuje błędem:

Nieudane stworzenie paczki: [Array ( [0] => stdClass Object ( [code] => VALIDATION_ERROR [message] => Order cannot be send using selected delivery service [details] => [path] => [userMessage] => Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy ) ) ]

Przy czym inna nasza Aplikacja REST operująca na innym koncie sprzedawcy allegro nie ma z tym problemu.

Nie jesteśmy pewni, czy to błąd związany z jakimś ustawieniem konta sprzedawcy, czy bug po Waszej stronie.

UUID: 0bd9b7bf-75be-410e-a797-6c7c6dfa7d20

GET /parcel-management/parcel-create-commands/0bd9b7bf-75be-410e-a797-6c7c6dfa7d20

Wywołał odpowiedź:

{"id":"0bd9b7bf-75be-410e-a797-6c7c6dfa7d20","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Order cannot be send using selected delivery service","details":null,"path":null,"userMessage":"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"}]}

**Comment by MartaNowaczyk** [comment]
Otrzymany komunikat mówi, że przesyłka nie została nadana metodą dostawy zgodną z wyborem kupującego. Wszelkie dostępne metody dostawy na danym koncie sprzedającego znajdziesz przy użyciu [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices).

Pamiętaj, że id usług mogą być różne dla każdego sprzedającego, dlatego zawsze warto sprawdzić jakie są ich wartości na danym koncie. To, że id usługi zadziałało na innym koncie, nie znaczy, że i tu będzie działać.

**Comment by tztztztz** [comment]
Wygląda na to, że o to chodzi - nieprawidłowy id usługi wzięty z innego konta.

Po aktualizacji naszej aplikacji, albo zamknę ten wątek, albo, jeżeli nie będzie działać - dodam nowe informacje.
