### ISSUE TITLE
Api wysyłam z allegro - dane nadawcy i wiązanie przewoźnika

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#5799]
Witam.

Mam 2 pytania odnośnie API z "wysyłaj z Allegro".
Skąd powinno się pobierać dane nadawcy przy tworzeniu paczki?
W panelu konta:
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia
jest możliwość zarządzania adresami z których nadaje się przesyłki.

Przy tworzeniu paczki  ( [PUT /parcel-management/parcel-create-commands/{commandId}]) w sekcji pickup (seller) trzeba wpisać dane nadawcy. Wydaje mi się, że mogłyby to być te same dane nadawcy z książki adresowej, ale nie wiem jak je pobrać z Api, chyba że powinno się pobierać te dane dla każdej paczki z warunków zwrotów albo na sztywno przepisać je do aplikacji. Tak czy siak program mógłby te dane podpowiadać. Proszę mnie oświecić, skąd najlepiej pobrać te pole bo niestety z podstawowych danych o kliencie "GET /me" brakuje kilku danych adresowych.

Druga sprawa to jak automatycznie znaleźć znaleźć właściwe serviceId przy tworzeniu paczki?
W zamówieniu jest sekcja:
delivery method np

"method": {
      "id": "c3066682-97a3-42fe-9eb5-3beeccab840c",
      "name": "Allegro Kurier DPD"
    }

W GetDeliveryMethods 
"id": "c3066682-97a3-42fe-9eb5-3beeccab840c",
      "name": "Allegro Kurier DPD",
}

Ale w delivery services jest kilka ID, które nie mają nic wspólnego z powyższymi, zaś po nazwach też nie za bardzo skoro klient zamówił
"name": "Allegro Kurier DPD", a w delivery services dokładnie takiej nazwy nie ma więc nie wiem jak to wiązać (po jakim polu):

      "id": 9533764,
      "service": "DPD",
      "name": "Allegro DPD",
      "owner": "ALLEGRO",
      "carrierId": "DPD",
	  
    "id": 9533765,
      "service": "DPD",
      "name": "Allegro DPD za granicę",
      "owner": "ALLEGRO",
      "carrierId": "DPD",

No chyba, że przy tworzeniu paczki w aplikacji trzeba operatorowi dać wybór, ale to przynajmniej nie widzę powiązanego pola z DeliveryMethods by ograniczyć wybór po CarrierID albo Service by się ograniczyć tylko do jednego usługodawcy. Proszę o rozwianie moich wątpliwości. Może warto też by było w dokumentacji jaśniej to opisać.

**Comment by AureliuszBrussy** [comment]
W Allegro API nie udostępniamy takiej książki adresowej nadawcy - w tym przypadku aktualnie utworzenie i przechowywanie takich danych stoi po stronie aplikacji. 

Id metod pobrane z zamówienia nie jest tym samym, co identyfikator usługi dostawy. Usługa dostawy odpowiada umowom podpisanym (i [dodanym w panelu](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia)) przez sprzedającego lub przez Allegro z firmą przewozową. 

Przesyłki mogą być wysłane zarówno w ramach umowy własnej z danym przewoźnikiem, jaki i umowy Allegro. Odpowiednie metody mogą być powiązane za pomocą nazwy. Sugeruj się tabelą, którą [udostępniamy w poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).
