### ISSUE TITLE
Publikacja draftów i ich czas 'życia' na waszym serwerze, czas życia zdjęć ? 

### ISSUE THREAD

**Issue by wwwfactory** [allegro/allegro-api#580]
Dzień dobry,

Proszę o wyjaśnienie kilku wariantów które mogą wystąpić ? 

Mamy :  
Draft oferty,  zwalidowany z błędami, posiada wasze ID, status INACTIVE
? kiedy zniknie z waszego serwera ? Jeżeli tak to czy mając zapisany po swojej stronie draft mogę się posłużyć tym samym ID ? 

Mamy: 
Draft oferty,  poprawny, bez błędów, posiada wasze ID, nie był publikowany, status INACTIVE
? kiedy zniknie z waszego serwera ? Jeżeli tak to czy mając zapisany po swojej stronie draft mogę się posłużyć tym samym ID ? 

Jaki jest czas życia zdjęć w powyższych wariantach ? Czy taki jak po publikacji zdjęcia ? Czy jeżeli zdjęcie jest użyte w drafcie to jego czas życia się zmieni ? 

Mamy: Ofertę która jest kompletna, była publikowana, ma status ENDED
? kiedy zniknie z waszego serwera ? Jeżeli tak to czy mając zapisany po swojej stronie draft mogę się posłużyć tym samym ID ? 

Jaki jest czas życia zdjęć dla ofert w statusie ENDED ?

pozdrawiamy wwwfactory

**Comment by MarcinLuczak** [comment]
@wwwfactory Dzień dobry

Draft oferty, dla obu wymienionych przypadków, zniknie po 60 dniach. Oferta, która była publikowana i jest zakończona, przejdzie do archiwum po 30 dniach.

Zdjęcia, jeśli są użyte w ofercie, mają taki sam okres ważności jak dana oferta.

O które ID pytasz?

**Comment by wwwfactory** [comment]
Dzień dobry ponownie

Czy zdjęcia użyte w drafcie (nie ofercie) również mają czas życia 60 dni ? 
Dopytuję ponieważ używacie dwóch słów, draft i oferta. Jak dla mnie to nie to samo.

{
  "id": "7276377308", ---> numer identyfikacyjny oferty (nadajecie ten numer przy tworzeniu draftu).
    "name": "Oferta testowa",
    "category": {
        "id": "257150"  
        ciach  ..........

**Comment by MarcinLuczak** [comment]
@wwwfactory to nie jest to samo - draft oferty to oferta nieopublikowana.

Jeżeli w drafcie oferty są dodane zdjęcia, to one również mają czas życia 60 dni.

**Comment by wwwfactory** [comment]
Dziękuję zamykamy
