### ISSUE TITLE
stock update via file

### ISSUE THREAD

**Issue by HUB2022PETR** [allegro/allegro-api#5800]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

**Comment by HUB2022PETR** [comment]
Hello,

we do not use Allegro API, but we have activated some items already via file upload. How can we update the stock amount?
Do you offer any xml file for upload with our stock?

Thanks

Petr

**Comment by MartaNowaczyk** [comment]
Hello, please use [the contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). There you will get support related to listing offers from a CSV file.
