### ISSUE TITLE
Błąd przy generowaniu etykiety allegro ONE

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#5801]
Witam,
Próbuję wygenerować etykietę Allegro One i ciągle otrzymuję następujący błąd, 

stdClass Object
(
    [id] => 62b02da2-62b0-62b0-62b0-62b02da294d8
    [parcelId] => 
    [status] => ERROR
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => Communication error with carrier's API occurred
                    [details] => 
                    [path] => /parcel-management/parcel-create-commands/{commandId}
                    [userMessage] => Wystąpił błąd komunikacji z API przewoźnika
                )

        )

)

**Comment by PrzemyslawLukanowski** [comment]
Problem wystąpił, ponieważ w polu `receiver.name` widnieje zbyt długa wartość - przyjmujemy w tym polu maksymalnie 35 znaków. Zdajemy sobie sprawę, że komunikat błędu nie jest precyzyjny, dlatego będziemy go aktualizować, tak aby jasno wskazywał przyczynę wystąpienia błędu.

**Comment by krzysda** [comment]
a komunikat 'Wybrana usługa jest niedostępna' też jest nieprecyzyjny ? 

 przykład pod id: 62b2ff55-62b2-62b2-62b2-62b2ff55f01c

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nastapiła próba nadania przesyłki międzymiastowej tego samego dnia, już po maksymalnej możliwej godzinie nadania.
