### ISSUE TITLE
Problem z aktywowanim konta na allegro sandbox

### ISSUE THREAD

**Issue by LogifactTest1** [allegro/allegro-api#5802]
Dzień dobry,
 
W naszych systemach mamy integracje z kurierami. Obecnie chcemy przeprowadzać testy z przesyłkami allegro wysyłanymi za pośrednictwem różnych kurierów. Potrzebne na do  tego konto testowe na allegro, by móc symulować sprzedaż i zakupy i uzyskiwać maskowane emaile allegro, niezbędne do prawidłowego testowania przesyłek kurierskich allegro.
W tym celu założyłem konto na sandboxie i chciałem jest uaktywnić, by móc z niego normalnie korzystać. Dwukrotnie mi się to nie udało, mimo kontaktu ze wsparciem allegro.
Nazwa konta: Logifact_Test1

Zasadniczo występuje problem z aktywowaniem sprzedaży. Polega na tym, że w ramach procedury aktywacji przechodzę bez zacięć przez kroki ‘Ustaw wypłaty środków’ i ‘Weryfikacja firmy’  ale po zakończeniu tych elementów konfiguracji, cały czas widać ikonę zegara, czyli, że nie widzę potwierdzenia pozytywnego zakończenia tych 2 kroków. I faktycznie, sprzedaż jest ciągle niedostępna.

Tak to wygląda:
 
![allegro_sandobx1](https://user-images.githubusercontent.com/106524550/174558525-55ddea57-8d72-4281-8fea-8867c661c20f.jpg)

Procedurę aktywowania konta próbowałem, ze dwa razy, jak wyżej pisałem. Przy ustawianiu wypłaty środków, przechodziłem wszystkie wymagane kroki, wykonywałem udawany przelew (numer konta brałem z generatora numerów kont bankowych) i dostawałem potwierdzenie jego wykonania na email. Przy weryfikacji firmy podawałem wymagane numery, również korzystając z dostępnych generatorów. Wgrywałem plik.
Niestety pomimo prób, cały czas aktywacja jest niedokończona. Proszę o wsparcie i wskazówki jak zakończyć procedurę aktywacji konta.

Pozdrawiam,
Dariusz Puto

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że w przypadku wskazanego konta występuje aktualnie problem z aktywacją. Weryfikuję problem z zespołem odpowiedzialnym za usługę - wrócę z informacją, gdy będę mógł przekazać więcej szczegółów.

**Comment by tomasz-grzesik** [comment]
Poproszę o sprawdzenie również konta SklepikNS.
Niestety nieustannie informacja - czekaj na weryfikację...

**Comment by Lukasz-Zurek** [comment]
@tomasz-grzesik Aktywowałem konto, włącznie z weryfikacją konta firmowego.

**Comment by tomasz-grzesik** [comment]
@Lukasz-Zurek dzięki, teraz bez problemu wystawiłem ofertę.
