### ISSUE TITLE
Problem z pobraniem kategorii

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5804]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Witam dostaje błąd 404 przy pobieraniu kategorii przez API "Wentylatory i cylkulatory": https://api.allegro.pl/sale/categories/258776 , a w portalu taka kategoria istnieje: https://allegro.pl/kategoria/klimatyzacja-i-wentylacja-wentylatory-i-cyrkulatory-258776

trace-id: 658700ed6b49cc83

**Comment by AureliuszBrussy** [comment]
Drzewo asortymentowe (drzewo, z którego korzystasz się podczas wystawiania oferty), różni się od drzewa nawigacyjnego w serwisie - niektóre z kategorii są scalone po stronie drzewa asortymentowego. Więcej o takim scalaniu przeczytasz w [naszym newsie](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo).

Kategoria 258776 nie istnieje w drzewie asortymentowym - nie pobierzesz przez API parametrów tej kategorii. Kategorią nadrzędną, która została dla niej wyznaczona to kategoria o id 255504.

Aktualizuj swoje drzewo kategorii i kieruj się podczas wystawiania drzewem pobranym przez API.
