### ISSUE TITLE
generowanie api z yml org.openapi.generator

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5805]
poprzednia wersja swagger.yml generowała się się bez problemów openApiGenerate w najnowszym swagger.yaml nie wiem czy jest błąd bo leci 
class java.util.UUID cannot be cast to class java.lang.String (java.util.UUID and java.lang.String are in module java.base of loader 'bootstrap')
class java.util.UUID cannot be cast to class java.lang.String (java.util.UUID and java.lang.String are in module java.base of loader 'bootstrap')

**Comment by AureliuszBrussy** [comment]
@silverwind85 sprawdziliśmy swagger.yml - nie potwierdzamy problemu po naszej stronie, plik generuje się prawidłowo.

**Comment by hahyes** [comment]
@silverwind85 Ja się dawno poddałem z generowaniem kodu klienta za pomocą automatów. One nie ogarniają dokumentacji od Allegro, bo jest częściowo niezgodna ze standardami RFC. Allegro nie pomoże, bo generują pod swoje narzędzia, które mają to gdzieś i używają swojej implementacji. Najlepiej użyć jakiejś biblioteki do pisania interfejsów jak Retrofit i po prostu napisać sobie interfejs do obsługi API.
