### ISSUE TITLE
Płatność łączona - wiele nieopłaconych zamówień

### ISSUE THREAD

**Issue by LukSky24** [allegro/allegro-api#5806]
Dzień dobry,

Mam pytanie aporpo nieopłaconych zamówień i płatności łączonej za kilka z nich.
Dajmy na to, klient zamówił sobie jedną sztukę jakiegoś produktu z jednej aukcji i chciał ją opłacić ale nie przeszła mu płatność (no coś poszło nie tak ale to nie ważne w tym momencie). Później próbował robić drugie zamówienie na ten sam produkt też w ilości jedenj sztuki z tej samej aukcji. Płatność znowu nie powiodła się. I dajmy na to po jednym dniu klient zaznacza te dwa nieopłacone zamówienia i wybiera opcje `Opłać` i te dwa zamówienia ma jakby łączone i płaci jak za jedno.
Czy jest możliwość sprawdzenia gdzieś przez API z jakich nieopłaconych zamówień powstało to jedno wspólne opłacone zamówienie?

My w systemie Magento, tworzymy sobie zamówienie jak już przyjdzie event z allegro o tym że takowe zamówienie powstało po stronie Allegro, ale jest jeszcze nieopłacone. I dajmy na to mamy dwa takie zamówienia nieopłacone, a później wpada nam trzecie opłacone już zamówienie, które ma produkty z poprzednich zamówień. I teraz mamy dwa takie zamówienia czekające na opłatę, a moglibyśmy je anulować jakbyśmy wiedzieli że to nowe jest połączeniem poprzednich.
Do systemu u nas wpadają u nas informacje z `id` takich nieopłaconych zamówień, ale po ich złączeniu w jedną opłatę, tamte zamówienia kasowane z Waszej bazy? Bo nie można dostać już informacji na ich temat.

Będę wdzieczny za jakieś informacje w tym temacie.

**Comment by AureliuszBrussy** [comment]
Jeśli kupujący zrobi dwa oddzielne zakupy u tego samego sprzedającego, a następnie np. zaznaczy je do wspólnej zapłaty - otrzymasz nowe zdarzenie ([GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET)) z nowym checkoutForm.id. W zamówieniach zobaczysz tylko ostateczne zamówienie z nowym checkoutForm.id - poprzednie usuniemy. Aby zidentyfikować taką sytuację można np. oprzeć się na pojedynczym akcie zakupowym - lineItem.id (jeżeli jeden lineItem.id występuje w kilku zamówieniach oznacza to, że mamy do czynienia z połączeniem zakupów przez kupującego).

**Comment by LukSky24** [comment]
Ok dziękuję za informację. Myślę że możemy zamknąć temat.
