### ISSUE TITLE
Prowizje od usług dostawy dla danej oferty

### ISSUE THREAD

**Issue by bswierzewski** [allegro/allegro-api#5807]
Witam serdecznie mogę w jakiś sposób połączyć zamówienia dla danej oferty z prowizjami od usług dostawy?

https://developer.allegro.pl/documentation#operation/getBillingEntries udostępnia opcję filtrowania po offerId jednak nie zwraca ona prowizji od usług dostawy.

Załóżmy iż mam 500 zamówień dla jednej oferty to daje mi 500 różnych identyfikatorów zamówienia. A usługa dostawy ma z tego co widzę tylko powiązanie z identyfikatorami zamówień.

**Comment by AureliuszBrussy** [comment]
Dla tego rodzaju opłat zwracamy tylko identyfikatory powiązanego zamówienia. Ew. powiązanie opłaty z konkretnymi ofertami na podstawie zwróconego numeru zamówienia możliwe jest dzięki np. [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET).

**Comment by bswierzewski** [comment]
W jaki sposób mogę wyciągnąć informacje o prowizjach dostawach z checkout-forms/{id} ?

**Comment by AureliuszBrussy** [comment]
@bswierzewski rozumiem, że chodzi o opłaty za koszty dostawy np. w ramach programu Smart? Jeżeli tak - to tak jak wspomniałem, dla opłat takich zwracamy tylko powiązany z opłatą numer zamówienia. 

Na podstawie tego numeru zamówienia możesz sprawdzić numery ofert, w których to zamówienie złożono (pole lineItems[].offer.id).

**Comment by bswierzewski** [comment]
Chodzi o np: Przesyłka DPD, Allegro Paczkomaty InPost, DPD - Kurier opłaty dodatkowe

Mam listę zamówień i chciałbym dla każdego z nich przyporządkować te opłaty.

**Comment by bswierzewski** [comment]
Jak wychodzę od opłat to nie ma problemu ale mnie interesuje ścieżka w drugą stronę.

Mam ofertę w ramach tej oferty zostało złożone 10 zamówień, i teraz chciałbym dla tych 10 zamówień pobrać te prowizje od wysyłek.

**Comment by AureliuszBrussy** [comment]
@bswierzewski rozumiem, czyli chodziłoby tutaj query parameter pozwalającego filtrować opłaty po id zamówienia? Nie udostępniamy takiego filtru. Zachęcam do założenia wątku na [Discussions](https://github.com/allegro/allegro-api/discussions) z sugestią wprowadzenia takiego filtru - inni użytkownicy będą mogli głosować na propozycję. Przy zainteresowaniu jest szansa, że wprowadzimy taką opcję.
