### ISSUE TITLE
https://api.{environment}/sale/products

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5809]
Idzie w nim wyszukiwać tylko np po parametrach np. codeProduct = 23435 ? co to jest w mode MPN ? to są jakieś parametry ?

**Comment by PrzemyslawLukanowski** [comment]
Szczegółowe informacje na temat parametru mode i dostępnych wartości znajdziesz w [naszym newsie](https://developer.allegro.pl/news/usprawnilismy-wyszukiwanie-produktow-w-naszym-katalogu-7G92kkW53fY), a cały proces, jak wyszukiwać produkty za pomocą tego zasobu, opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-znalezc-produkt).
