### ISSUE TITLE
Szukanie w opisie

### ISSUE THREAD

**Issue by apzecom** [allegro/allegro-api#581]
Witam,

czy API pozwala określić parametr (TAK/NIE) wyszukiwania w opisie? Będę wdzięczny za informacje.

**Comment by MarcinLuczak** [comment]
@apzecom Dzień dobry

[Nowe zasoby w REST API](https://developer.allegro.pl/news/2018-07-03-Listing_ofert/) nie pozwalają na szukanie po opisie. Natomiast dotychczasowa metoda z WebAPI, czyli [doGetItemsList](https://allegro.pl/webapi/documentation.php/show/id,1342), pozwala to zrobić za pomocą filtra 'description'. Pamiętaj, że metodę doGetItemsList wygasimy na początku drugiego kwartału 2019 roku. Wcześniej, we wrześniu 2018’ oznaczymy ją jako deprecated.

**Comment by apzecom** [comment]
Dziękuję. A czy to się zmieni? To bardzo ważna funkcja i aż dziw, że nie jest uwzględniona. Są plany do jej kontynuacji?

**Comment by MarcinLuczak** [comment]
@apzecom nie mam niestety informacji na ten temat. Ale dziękuję za sugestię, przekażę ją w odpowiednie miejsce.

**Comment by rtnet-pl** [comment]
Hmmm, a co robi searchMode=DESCRIPTIONS w /offers/listing? 😄

**Comment by MarcinLuczak** [comment]
@rtnet-pl dokładnie to o czym mowa. Mój błąd :)
