### ISSUE TITLE
Dostęp do allegro ads

### ISSUE THREAD

**Issue by bswierzewski** [allegro/allegro-api#5811]
Witam serdecznie, w panelu zarządzania api widnieją opcje jak na zdj poniżej

![image](https://user-images.githubusercontent.com/33912764/174805497-f12ddafd-e8b6-49ce-ab4a-e4b1031dfe68.png)

W dokumentacji nie widzę sekcji w której mógłbym uzyskać dostęp do tych danych. Dlatego moje pytanie w jaki sposób mogę uzyskać dane o ofertach promowanych w ramach ads.allegro ?

**Comment by PrzemyslawLukanowski** [comment]
Aktualnie nie ma możliwości uzyskania dostępu do tych zasobów. Jeżeli w przyszłości podejmiemy decyzję o ich upublicznieniu, poinformujemy o tym w osobnym komunikacie na forum oraz w [aktualnościach](https://developer.allegro.pl/news/) na portalu.
