### ISSUE TITLE
Offer Listing Error

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5813]
Please provide explanations for below:

1) Why cant I send a different Brand value for existing EAN product on Allegro:
"endpoint" : POST https://api.allegro.pl/sale/product-offers
"request" : ` {"afterSalesServices":{"returnPolicy":{"id":"5c1be946-8ac4-4636-9ca1-706f828382f7","name":"Test Return 1"},"impliedWarranty":{"id":"67aa6cfa-07f0-422b-87de-eb485299c9cc","name":"Test Complaint 1"}},"delivery":{"handlingTime":"P7D","shippingRates":{"id":"18ffc1ce-c9af-414b-9f7e-1acc38046662","name":"UK Price"}},"publication":{"duration":null,"status":"ACTIVE","republish":true},"payments":{"invoice":"NO_INVOICE"},"parameters":[{"id":"11323","name":"Condition","valuesIds":["11323_1"]}],"productSet":[{"product":{"parameters":[{"id":"226434","name":"Brand","valuesIds":["226434_315930"]},{"id":"2205","name":"Type","valuesIds":["2205_2"]},{"id":"15835","name":"Material","valuesIds":["15835_268435456"]},{"id":"17088","name":"Stone","valuesIds":["17088_512"]},{"id":"205826","name":"Dominant color","valuesIds":["205826_1081899"]},{"id":"129109","name":"Set Contents","valuesIds":["129109_16","129109_1"]},{"id":"129129","name":"Theme","valuesIds":["129129_246990"]},{"id":"224017","name":"Producent code","values":["JEWELRY SET"]},{"id":225693,"name":"EAN","values":["4632125816431"]}],"name":"Maia Set Silver","category":{"id":"123430"},"images":["https://dmsmatrix.net/direct/images/600ed75c099d76313038414f.jpg","https://dmsmatrix.net/direct/images/6238a54876f38d33cf77eba8.jpg"]},"quantity":{"value":1}}],"name":"Maia Set Silver","description":{"sections":[{"items":[{"type":"TEXT","content":"<p>Two Piece Pendant and Earring set. Made with Swarovski Elelements. Alloy Rhodim Plated Silver Colour. Lobster Clasp. Earrings 5mm. Necklace 45cm Length Adjustable " With 5mm stone.</p>"}]}]},"category":{"id":"123430"},"images":["https://dmsmatrix.net/direct/images/600ed75c099d76313038414f.jpg","https://dmsmatrix.net/direct/images/6238a54876f38d33cf77eba8.jpg"],"sellingMode":{"price":{"amount":"134.99","currency":"PLN"},"format":"BUY_NOW"},"stock":{"available":76,"unit":"UNIT"},"external":{"id":"7141141822625"}}`
"headers" : ` {\"expires\":\" 0\",\"cache-control\":\" no-cache, no-store, max-age=0, must-revalidate\",\"x-xss-protection\":\" 1; mode=block\",\"pragma\":\" no-cache\",\"x-frame-options\":\" DENY\",\"trace-id\":\" 8366dd9bd1223966\",\"date\":\" Tue, 21 Jun 2022 14:51:10 GMT\",\"x-content-type-options\":\" nosniff\",\"strict-transport-security\":\" max-age=31536000 ; includeSubDomains\",\"content-type\":\" application\\/json\",\"content-length\":\" 410\"}`
"response" : `{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Brand'(226434) value (Swarovski(226434_315930)) does not match the existing parameter value (other brand(226434_315782))","details":null,"path":"productSet[0].product.parameters","userMessage":"The provided parameter `Brand` value `Swarovski(226434_315930)` does not match the existing parameter value `other brand(226434_315782)`."}]}`

2) Why do I get the following category mismatch error. I could not provide you trace-id for this. Just need an explanation:
`{"errors":[{"code":"CATEGORY_MISMATCH","message":"Existing Product related to submitted data was found. The provided category `Other` (82602) does not match the existing product category `Other` (99381)","details":null,"path":"productSet[0].product.category.id","userMessage":"Existing Product related to submitted data was found. The provided category `Other` (82602) does not match the existing product category `Other` (99381)."}]}`

**Comment by PrzemyslawLukanowski** [comment]
The answer to both questions is - because you can’t change the data of the existing product in our catalog just like that. If you are sure the data in our database is wrong, you can report us incorrect information in the product by [this resource](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-report-incorrect-data-in-a-product).

I will give you an example, [here](https://allegro.pl/produkt/sony-console-playstation-5-a2598d37-39dd-47cc-9944-72646262523d) you can see a list of 21 offers from different sellers, and those offers are connected with a specific product - Sony PlayStation 5. Product has a certain EAN and thanks to this we know what exactly this product is - its Brand, Manufacturer Code, etc. If the change of the product parameters was possible, anyone could change the „Brand” to another value than „Sony” and we would have a lot of invalid data in our products.

**Comment by adityakokate** [comment]
![image_2022_06_22T11_06_57_156Z](https://user-images.githubusercontent.com/92523331/175019522-e8f059fb-b455-495a-b6cb-54716bc29cc5.png)
![image_2022_06_22T11_05_31_117Z](https://user-images.githubusercontent.com/92523331/175019530-95ddf5fc-cf1e-4dc0-ae43-98a010a9cb7e.png)

But my concern is why SWAROVSKI products are under Other Brand and not added under Brand SWAROVSKI. My clients are trying to add such products to the valid brand SWAROVSKI but getting errors. How can I tell them to add Brand as Other Brand (WITH RANDOM VALUE OF BRAND) even though Brands list is showing me SWAROVSKI as Brand?

Also, clients are getting lots of errors while adding product EAN's with category, brand values they have with them. Allegro asks for specific categories and brand values of products if they already exist in Allegro. How can I tell to my clients to use specific category and brand for EANs so that they wont go wrong after pushing products to Allegro? Is there any API from which I get all EANs with their specific category and brands?

**Comment by PrzemyslawLukanowski** [comment]
In this case, please report incorrect information in the product via [this resource](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-report-incorrect-data-in-a-product) or using [the form](https://allegro.pl/for-sellers/how-to-report-incorrect-product-information-D744ZjLW2Ua).

> Also, clients are getting lots of errors while adding product EAN's with category, brand values they have with them. Allegro asks for specific categories and brand values of products if they already exist in Allegro. How can I tell to my clients to use specific category and brand for EANs so that they wont go wrong after pushing products to Allegro? Is there any API from which I get all EANs with their specific category and brands?

Yes, you can retrieve product details, including category and all parameters, using GET /sale/products?phrase={ean}&mode=GTIN. You will find more information in [our tutorial](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#how-to-search-for-products).

**Comment by adityakokate** [comment]
Thanks for the explanation. Please let me know size limit for images upload as I am getting following error: 

[UploadImageRequestTimeoutException] The time limit for downloading an image from the address https://dmsmatrix.net/direct/images/5f0ee237099d763c6b3d5120.jpg has been exceeded.

**Comment by PrzemyslawLukanowski** [comment]
The maximum size limit is 2560 x 2560 pixels. You can upload images with a maximum resolution of 26 Mpix.

**Comment by adityakokate** [comment]
> maximum resolution of 26 Mpix.

Means max 26 MB in size

**Comment by PrzemyslawLukanowski** [comment]
No, these are megapixels. but when it comes to MB, the value is similar - 26,2 MB.

**Comment by adityakokate** [comment]
OK...thanks.
