### ISSUE TITLE
https://api.{environment}/sale/product-offers jakie pole odpowiada za sygnatura w ofercie 

### ISSUE THREAD

**Issue by silverwind85** [allegro/allegro-api#5815]
Idzie w tym api dodać sygnaturę przeglądałem dokumentację ale nic nie znalazłem takiego w tym api. Możliwe że coś przeoczyłem 
![image](https://user-images.githubusercontent.com/6718212/174904596-1653b3a4-b134-40c3-a95e-f707372b66e1.png)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję @asoio za pomoc użytkownikowi, [link](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#sygnatura) do dokładnego miejsca w przytoczonym poradniku, a w samej [dokumentacji](https://developer.allegro.pl/documentation#operation/createProductOffers) informacja widoczna jest tutaj:
<img width="766" alt="Zrzut ekranu 2022-06-22 o 07 11 39" src="https://user-images.githubusercontent.com/51473661/174948573-4d2f5709-df2a-4f0c-b547-0b3c7ded5d87.png">

**Comment by silverwind85** [comment]
Pole  productSet jest array to jedno zamówienie może mieć wiele produktów z katalogu podpięte ?

**Comment by silverwind85** [comment]
Nie jest to dobrze opisane w dokumentacji

**Comment by PrzemyslawLukanowski** [comment]
Jedno zamówienie czy jedna oferta? Jeśli jedna oferta to tak, może mieć wiele produktów, dlatego w dokumentacji widnieje informacja `"Array of objects[ items ]".` Przekazując wiele produktów utworzysz zestaw produktowy, co opisaliśmy szczegółowo [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-na-podstawie-produktow-z-naszej-bazy).

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, w takim razie sytuacja wygląda tak jak opisałem to wyżej - przekazując więcej niż jeden produkt, utworzysz zestaw produktowy.

**Comment by silverwind85** [comment]
Ten productSet to się odnosi do katalogowanego już produktu, ale ja chce mieć inną cene i ilość sellingMode nie widzę rzadnej listy ?

**Comment by silverwind85** [comment]
Wariantowość też się robi przez ten productSet czy może mylę pojęcia

**Comment by PrzemyslawLukanowski** [comment]
Tak jak napisałeś, productSet jest obiektem, który dotyczy warstwy produktu/produktów, natomiast cenę i liczbę sztuk dla warstwy ofertowej, przekazujesz standardowo w polach `sellingMode` i `stock`.

Nie, wielowariantowość to nie to samo, co zestaw produktowy. Zestaw składa się z kilku różnych produktów (konsola + gra) lub wielu sztuk jednego produktu (tzw. wielopak), podczas gdy wielowariantowość dotyczy różnych wariantów tego samego produktu (np. koszulka, ale w różnych rozmiarach lub wariantach graficznych). Do zarządzania wielowariantowością służą dedykowane zasoby, które opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-utworzyc-oferte-wielowariantowa-oA6ZYBg5XFo).

**Comment by silverwind85** [comment]
Dzięki to sobie zaczynam układać to wszystko w głowie mam jeszcze jeden problem. 
Chodzi o pole description jest to gdzieś opisane, .Jak wrzucę text i image to jak mi się to będzie wyświetlać ?

**Comment by PrzemyslawLukanowski** [comment]
Szczególowe informacje o tym, jak uzupełnić tę sekcję i jak to będzie wyświetlane, znajdziesz [tutaj](https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#opis-oferty) (wkrótce ta informacja będzie widoczna także we wcześniej linkowanym poradniku). Zachęcam też, aby wystawić przykładową ofertę na naszym [środowisku testowym](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe) przez stronę internetową, a następnie pobrać jej szczegóły za pomocą GET /sale/product-offers/{offerID}. Wtedy również dokładnie zobaczysz, jak przekazane zdjęcia i tekst prezentują się w JSON-ie w danych oferty.

**Comment by silverwind85** [comment]
Ten api product-offert fajny nieźle to działa. Mam jeszcze taki przypadek że chciałby tylko zmienić opis ale nie zmieniać zdjęcia tego z produktyzacji. Jakim api moge pozyskać to zdjęcie ?

**Comment by PrzemyslawLukanowski** [comment]
Dowolne pole w ofercie zmienisz za pomocą [PATCH /sale/product-offers](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-edytowac-oferte), w tym właśnie np. sam opis. Zdjęcie danego produktu możesz natomiast pobrać przez [GET /sale/product/{productID}](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-pobrac-pelne-dane-o-produkcie).
