### ISSUE TITLE
Red Cart - Baselinker

### ISSUE THREAD

**Issue by Groszyk88** [allegro/allegro-api#5816]
Witam,

próbowałem wystawić faktury poprzez red cart i w mailu, który przyszedł mi pisało, że nie można tego zrealizować, a gdy wszedłem w powiadomienie bodajże zakładkę powiadomienia, to wyskoczyło okienko  z dwoma ramkami z mailem red cart oraz moim groszyk88@gmail.com że mail jest już przypisany i że nie można tego zrealizować. Niestety już wszystko usunąłem, wiec screenów nie mogę podesłać.

Kolejna sprawa czy, ten red cart, na którym się integruje z hurtowniami i skąd wystawiam produkty można podłączyć jako API do Allegro abym za każdym razem nie musiał pojedynczo klikać i wystawiać np. fakturę lub dowód zakupu tylko od razu automatycznie zbiorczo z takiego zew. platformy wysłać to wszystko, czy to wtedy przez wasz system przeczhoci i dociera, tak ogólnie na mail klienta, który podał dla Was na Allegro? 

Podobno używany jest Baselinker w taki sposób. Dopiero zaczynam drop i po prostu chciałbym to szybko i sprawnie załatwiać

dziekuję

**Comment by PrzemyslawLukanowski** [comment]
Wszelkie pytania dotyczące integracji Red Cart zadaj proszę wsparciu tej aplikacji. My nie jesteśmy jej autorami, nie mamy dokładnej wiedzy, w jaki sposób z nami się łączy i jakie możliwości oferuje. Najbardziej odpowiednim kontaktem, aby wyjaśnić poruszone przez Ciebie kwestie, będzie w tym przypadku właśnie sam Red Cart.

**Comment by Groszyk88** [comment]
Od red cart dostałem info, że gmail zmienił cos w ustawieniach i ich system z tym nie współpracuje i zalecono mi zmianę maila na allegro by móc uzupełnić dane serwera pocztowego. Teraz kolejne pytanie, czy jeśli zmienię maila na Allegro nie przysporzy mi to jakiś kłopotów z powiadomieniami, wysyłkami, zakupami, odpowiedziami do kupujących, no wszystko co z tym związane. Jestem tez połączony np. z Alleasystentem na allegro, czy to nie będzie miało wpływu na zew API

**Comment by PrzemyslawLukanowski** [comment]
Tak, zmiana adresu mail spowoduje, że aktualne tokeny utracą ważność, dlatego będziesz musiał ponownie autoryzować aplikację. 

Co do

> czy jeśli zmienię maila na Allegro nie przysporzy mi to jakiś kłopotów z powiadomieniami, wysyłkami, zakupami, odpowiedziami do kupujących, no wszystko co z tym związane

to pytanie brzmi bardzo ogólnie i nie jest związane z API, dlatego prosiłbym o kontakt przez [formularz.](https://allegro.pl/pomoc/kontakt) Na tym forum udzielamy wsparcia w kwestiach technicznych związanych z API Allegro.
