### ISSUE TITLE
Błąd podczas wyszukiwania produktu . "Nie udało się wyświetlić produktów."

### ISSUE THREAD

**Issue by lukasczg** [allegro/allegro-api#5818]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: 
Problem występuje w zasobie: 
Get all data of the particular product

W przypadku tego numeru katalogowego **NAS109000** zwracany jest błąd: 
`code: "TecdocSpecificationNotFound", message: "An error has occurred", details: null, path: null, userMessage: "Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}`
https://api.allegro.pl/sale/products?phrase=NAS109000&mode=MPN

Problem występuje podczas wyszukiwania produktu na froncie Allegro. 
Wtedy wyświetlany jest komunikat: Nie udało się wyświetlić produktów.

problem występuje wyłącznie w przypadku numeru katalogowego **NAS109000**

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie błędu, problem już nie powinien występować.

**Comment by lukasczg** [comment]
Podobny problem występuje wyszukując produktu "213013".
Widzę, że problem jest powtarzalny. Jak uniknąć w przyszłości takich problemów ?

**Comment by PrzemyslawLukanowski** [comment]
Również dla tego produktu błąd nie powinien już występować. Mamy mechanizmy, które sprawdzają tego typu nieprawidłowości i je poprawiają. Przekazałem informację o występującym problemie do zespołu odpowiedzialnego za usługę.

**Comment by lukasczg** [comment]
Ten również zwraca błąd: **01.43.227**

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku problem także nie powinien już występować.
