### ISSUE TITLE
Problem "Poprzednia edycja oferty jest nadal przetwarzana, spróbuj ponownie."

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5819]
Od paru godzin mam problem (środowisko testowe) przy wykonywaniu GET sale/product-offers/{offerId}/operations/{operationId} - sprawdzam status wykonania operacji zleconej za pomocą PATH - dokładnie: aktualizacja liczby sztuk, aktualizacja ceny oraz wznowienie oferty (łącznie 3 zapytania). Operację chcieliśmy wykonać dla 15 produktów (do tej pory nie było żadnych problemów) - 7 produktów zaktualizowało poprawnie po czym coś gdzieś wisi. API działa nam poprawnie, jedynie nie możemy sprawdzać z poziomu API czy operacje wykonały się poprawnie. Problem dotyczy sandbox user mateuszcom2

Przykładowy link https://api.allegro.pl.allegrosandbox.pl:443/sale/product-offers/7690727967/operations/d361217e-e509-4095-909c-d572d03a79af

Proszę o pomoc, ponieważ chciałbym zrozumieć, dla czego wystąpił ten błąd, aby w przyszłości temu zapobiec

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, udało nam się znaleźć źródło problemu - będziemy wprowadzać poprawkę, która wyeliminuje podobne problemy w przyszłości. Bezpośrednio przyczyną sytuacji było to, że operacja wznowienia oferty zakończyła się błędem z powodu chwilowego "zablokowania" oferty przez wcześniejszą operację. To, co widać w komunikacie, to wynik operacji, która zakończyła się błędem, dlatego on już się nie zmieni.
