### ISSUE TITLE
Usuwanie oferty

### ISSUE THREAD

**Issue by kkrzysiek11** [allegro/allegro-api#582]
Hej,
w jaki sposób mogę usunąć ofertę? W dokumentacji nie ma DELETE, próbuję kombinować z edycją i zmianą endingAt ale nie pomoga.
Z góry dzięki za pomoc.

**Comment by MarcinLuczak** [comment]
@kkrzysiek11 

Wszystko opisaliśmy w [tej części naszego poradnika](https://developer.allegro.pl/sale/#step-7-offer-publication-commands).

Wystarczy przekazać status END w polu 'action' w zasobie [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#!/offer/changePublicationStatusUsingPUT).

**Comment by kkrzysiek11** [comment]
A działa to na pewno?
Wysyłam taki request:

`Criteria":[{"offers":[{"id":"offerId"}],"type":"CONTAINS_OFFERS"}],"publication":{"scheduledFor":"2018-09-10T11:18:00.000Z","action":"END"}}`

i oferta jest dalej aktualna. Próbowałem też bez scheduledFor

**Comment by MarcinLuczak** [comment]
@kkrzysiek11 skorzystaj z tych dwóch zasobów:

[GET /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/sale/#offer-publication-commands-commandId)
[GET /sale/offer-publication-commands/{commandId}/tasks](https://developer.allegro.pl/sale/#offer-publication-commands-commandId-tasks)

i sprawdź, czy oferta została zakończona. O tym też [piszemy w poradniku](https://developer.allegro.pl/sale/#step-8-tasks). Pamiętaj także, że oferta nie zawsze zakończy się w ciągu kilku pierwszych sekund. Kończenie ofert może chwilę potrwać.

**Comment by ircykk** [comment]
U mnie to samo :)
Response zawiera błąd `An error has occurred` i aukcja tra dalej.

**Comment by MarcinLuczak** [comment]
@ircykk udostępnij proszę pełne cURL-e (request i response) w których widać problem i podaj status, jaki otrzymujesz po wywołaniu zasobu.

**Comment by collector1871** [comment]
jest możliwosć całkowitego usunięcia oferty, ale NIE zakończenia/archiwizowania/zamknięcia/wygaszenia?

głównie chodzi o duplikaty : jeżeli duplikat, to pełne usunięcie
W starym allegro chyba było coś takiego

**Comment by MaciejPotepa** [comment]
@collector1871 Nie ma możliwości całkowitego usunięcia oferty. 

Usuwanie nigdy nie działało w taki sposób. Oferty były usuwane jedynie z frontu.

**Comment by collector1871** [comment]
@MaciejPotepa 
ok , a da się przyśpieszyć termin "60 dni pełna archiwizacja", w sensie, że właśnie natychmiastowe pełne usunięcie z frontu ?

**Comment by MaciejPotepa** [comment]
Tylko z poziomu listy [Moje oferty](https://allegro.pl/seller-offers). 

**Oferta nadal będzie dostępna po linku i nie zniknie z serwisu, jedynie z listy Moje oferty.**

**Comment by collector1871** [comment]
@MaciejPotepa 
nie ma dla mnie znaczenia, że będzie widoczna - chodzi, żeby w GUI był porządek.

jak to z poziomu "Moje Oferty"? A da się przez REST Api request jakoś ją "schować", w sensie, że nawet jak nie minęło 60 dni, to żeby nie była widoczna nigdzie już?

Tak jak mówię: chodzi o duplikaty

jest cos takiego, że podaje się id oferty, a REST Api request chowa/całkowicie usuwa ofertę?

**Comment by MaciejPotepa** [comment]
@collector1871 Jeżeli chodzi Ci o ukrywanie ofert w GUI to jest tam dokładnie to czego potrzebujesz, tyle, że nie jest dostępne po API, bo ukrywa oferty jedynie w GUI, dosyć logiczne. 

Będąc w Moich ofertach zaznacz wybrane oferty - muszą mieć status _nieaktywna_ i na belce u spodu ekranu kliknij w _UKRYJ_, oferty znikną z listy, ale nadal będą dostępne po URL. 

Pamiętaj, że ukrytych ofert już nie przywrócisz. 

![screenshot_1](https://user-images.githubusercontent.com/36235479/45999953-80eeb880-c0a7-11e8-883a-e64dea287389.png)

**Comment by imper86** [comment]
@MaciejPotepa a czy z poziomu API taka ukryta oferta będzie się czymś wyróżniała? Czy ona wtedy po prostu przechodzi prosto do archiwum?

**Comment by MaciejPotepa** [comment]
@imper86 Z poziomu API z taką ofertą się nic nie dzieje. 
Oferta zniknie jedynie **wizyalnie** z list [Moje oferty](https://allegro.pl/seller-offers).

**Comment by robsonek** [comment]
Czy coś się może zmieniło w kontekście ukrywania ofert przez API? Czy jest to możliwe przez API? 

Po ukryciu ofert przez stronę WWW znika ona także w wywołaniu przez API podczas pobierania wszystkich ofert. 
Czy ewentualnie jest jakaś możliwość ukrycia oferty przez API, aby nie była dostępna w API?

**Comment by PrzemyslawLukanowski** [comment]
Nie wprowadzaliśmy zmian, ukrywanie oferty jest funkcjonalnością dostępną wyłącznie przez stronę internetową.

**Comment by radhex** [comment]
Czemu nie ma takiej funkcjonalności przez API? Skoro ukrywanie ofert działa praktycznie jak usuwanie, te ukryte przez stronę, przez API też nie są widoczne, a możliwości przywrócenia nie ma.

**Comment by robsonek** [comment]
Niestety ktoś kiedyś mylnie nazwał tą funkcję jako Ukryj zamiast Usuń i nie potrafią tego przyznać :( 

"Ukrywanie" oferty w GUI to usuwanie w API, a z poziomu API nie ma usuwania. Dziwne...

**Comment by radhex** [comment]
Sugerujesz że w Spółce Akcyjnej Allegro wartej kilkadziesiąt miliardów zł, nie ma programisty który by umiał zmienić nazwę przycisku z Ukryj na Usuń? :)

**Comment by robsonek** [comment]
Tutaj nie chodzi o programistę, tylko o approval od PMa, albo kogoś decyzyjnego. Kiedyś ukrywanie nie oddziaływało na API, ale po zmianach już oddziałuje, więc kiedyś to było ukrywanie w GUI, ale teraz to też usuwa w API (bądź ukrywa, jak zwał tak zwał) :)

**Comment by radhex** [comment]
Wiem wiem, w dużych firmach proste rzeczy muszą przechodzić przez całą machinę decyzyjną, choć tak naprawdę problemem jest pewnie że komuś się nie chce tego zrobić (bo nie ma pewnie wystarczającego odzewu od użytkowników)

**Comment by PrzemyslawLukanowski** [comment]
Odnośnie tego, że ukrywanie działa jak usuwanie w API - nie do końca tak to działa, taka oferta cały czas istnieje i można ją pobrać za pomocą GET /sale/product-offers/{offerId} (nie zwrócimy jej w GET /sale/offers).

Na tę chwilę nie planujemy wdrożenia takiej funkcjonalności, możecie jednak dodać odpowiednią sugestię w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Dzięki temu również inni użytkownicy będą mogli się z nią zapoznać i na nią zagłosować.
