### ISSUE TITLE
Centrum wiadomości

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#5820]
Witam, mam pytanie, jak wchodzę w centrum wiadomości przez stronę do nad pytaniem od klienta pojawia się numer VIN. Czy przez api można go również pobrać?

**Comment by PrzemyslawLukanowski** [comment]
W chwili obecnej nie zwracamy numeru VIN w naszym API. Jeśli coś w tej kwestii ulegnie zmianie, to na pewno opublikujemy odpowiedni komunikat na naszej stronie i forum.

**Comment by mskiba03** [comment]
No to chyba w przypadku motoryzacji całe centrum wiadomości można uznać za nieporozumienie. Klient pisze ze chce klocki. W api nie widać ze podał VIN, wiec i tak trzeba sie logować na konto zeby zoabczyć czy podał VIN. Brawo ;)
