### ISSUE TITLE
Length of the Order ID

### ISSUE THREAD

**Issue by smikuczinski** [allegro/allegro-api#5821]
Hello,

I have got an urgent question regarding the length of the order IDs you sent with.
Unfortunately our sytem only can process an length of order ID of 35 characters.
The length of a test order is about 36 characters.

Can you tell me how long the order IDs are in general? Are they fixed with 36 characters or is there a range of characters for example between 36 and 45 characters?

In the appendix you can find an example:
![image](https://user-images.githubusercontent.com/108056808/175253597-a06266ec-1cc8-423e-b395-646ea3dc033b.png)

![image](https://user-images.githubusercontent.com/108056808/175253817-8301c9cc-eb94-4d1c-8309-423241171084.png)

Thank you for your support!
Best regards,

Sabrina Mikuczinski

**Comment by PrzemyslawLukanowski** [comment]
Hello, the order ID is a UUID type of value and on Allegro it always has 36 characters.

**Comment by PrzemyslawLukanowski** [comment]
Unfortunately no, because the UUID format not only applies to order ID, but we also use it in other values, for example - payment ID, shipping rates ID, delivery method ID, etc.

**Comment by smikuczinski** [comment]
Okay I understand it, thank you. Then there is no way except to change something in our system... Thank you, I will close the ticket.
