### ISSUE TITLE
Wystawianie oferty -  Wybrana kategoria nie istnieje.

### ISSUE THREAD

**Issue by holospl** [allegro/allegro-api#5822]
Mam wystawianie ofert po API, ogólnie wszystko działa. Zauważyłem niestety, że mam problem z produktami w jednej kategorii:
Allegro >> Elektronika >> Fotografia >> Wyposażenie studia >> Oświetlenie >> Statywy
Dla przedmiotów, które próbuję umieścić w tym miejscu dostaję zwrotkę:

`tdClass Object ( [errors] => Array ( [0] => stdClass Object ( [code] => VALIDATION_ERROR [message] => Selected category does not exist. [details] => UnknownError [path] => category [userMessage] => Wybrana kategoria nie istnieje. ) ) )`

Jako ID kategorii podaję `148935`.
Bardzo proszę o pomoc, bo szukam w czym problem i nie widzę. Nie zarejestrowałem podobnego problemu dla żadnej innej kategorii. Cała zawartość wysyłanej tablicy wygląda tak:

`

    [name] => Statyw oświetleniowy Jinbei Air 280cm Ciśnieniowy

    [category] => Array
        (
            [id] => 148935
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 11323
                    [valuesIds] => Array
                        (
                            [0] => 11323_1
                        )

                )

            [1] => Array
                (
                    [id] => 225693
                    [valuesIds] => Array
                        (
                            [0] => 6933793980126
                        )

                )

        )

    [description] => Array
        (
            [sections] => Array
                (
                    [0] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => Statyw OPIS

                                        )

                                )

                        )

                    [1] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => TEXT
                                            [content] => OPIS OPIS OPIS
                                        )

                                    [1] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/116e68/a90c795e4ebc99b79e5dfe734200
                                        )

                                )

                        )

                    [2] => Array
                        (
                            [items] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => IMAGE
                                            [url] => https://a.allegroimg.com/original/116e68/a90c795e4ebc99b79e5dfe734200
                                        )

                                    [1] => Array
                                        (
                                            [type] => TEXT
                                            [content] => OPIS OPIS
                                        )

                                )

                        )

                )

        )

    [compatibilityList] => Array
        (
            [items] => 
        )

    [images] => Array
        (
            [0] => Array
                (
                    [url] => https://a.allegroimg.com/original/116e68/a90c795e4ebc99b79e5dfe734200
                )

        )

    [sellingMode] => Array
        (
            [format] => BUY_NOW
            [price] => Array
                (
                    [amount] => 195.00
                    [currency] => PLN
                )

        )

    [stock] => Array
        (
            [available] => 46
            [unit] => UNIT
        )

    [publication] => Array
        (
            [duration] => 
            [status] => INACTIVE
            [startingAt] => 
            [endingAt] => 
        )

    [delivery] => Array
        (
            [shippingRates] => Array
                (
                    [id] => 4e32cee9-5119-4a68-9f49-2e1c1e6f01b8
                )

            [handlingTime] => PT24H
            [additionalInfo] => 
            [shipmentDate] => 
        )

    [payments] => Array
        (
            [invoice] => VAT
        )

    [afterSalesServices] => Array
        (
            [impliedWarranty] => Array
                (
                    [id] => d02d2c8f-2ef0-47ff-9668-4841805a35cc
                )

            [returnPolicy] => Array
                (
                    [id] => 91a6b263-f1ad-47fd-aa8a-767030366d44
                )

            [warranty] => Array
                (
                    [id] => e383ee0d-b446-4294-8985-8f0f3b7d7623
                )

        )

    [additionalServices] => 
    [sizeTable] => 
    [promotion] => 
    [location] => Array
        (
            [countryCode] => PL
            [province] => LODZKIE
            [city] => Łódź
            [postCode] => 93-129
        )

    [external] => Array
        (
            [id] => WSSO-JB-300
        )

    [contact] => 
`

**Comment by PrzemyslawLukanowski** [comment]
Zwrócony komunikat jest prawidłową odpowiedzią, ponieważ takiej kategorii nie zwrócimy, jeśli odpytasz o nią bezpośrednio przez GET /sale/categories/148935, jak i nie znajdziesz jej także w formularzu wystawiania na naszej stronie. Powodem takiego stanu rzeczy jest to, że wskazana kategoria jest kategorią nawigacyjną, którą widzą tylko kupujący, a nie kategorią asortymentową, w której sprzedawcy mogą wystawiać swoje przedmioty. Kategoria została w przeszłości scalona z inną - oznacza to, że jeśli kategoria A została scalona kategorią B, to oferty możesz wystawić tylko w kategorii B, ale kupujący zobaczą ją zarówno w kategorii A, jak i B. Więcej na temat tego przeczytasz na [naszej stronie ](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo), jak i na s[tronie dla sprzedających.](https://allegro.pl/dla-sprzedajacych/laczymy-kategorie-z-tym-samym-asortymentem-AggmRPKrnuY).

**Comment by PrzemyslawLukanowski** [comment]
A konkretnie kategoria została scalona z kategorią 122395 - 
Allegro > Elektronika > Sprzęt estradowy, studyjny i DJ-ski > Światło i efekty > Statywy.

**Comment by holospl** [comment]
Ok, dziękuje serdecznie za jasne wytłumaczenie! :)
