### ISSUE TITLE
Handling_Time

### ISSUE THREAD

**Issue by szymondobrodziej** [allegro/allegro-api#5824]
Czy jest możliwość, pobrania moich ofert wraz z aktualnym czasem wysyłki np. id aukcji handling time PT24/PT48 ITD ?

**Comment by AureliuszBrussy** [comment]
Pole **delivery.handlingTime** zwrócimy, gdy pobierzesz szczegóły konkretnej oferty ([GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation#operation/getProductOffer) lub [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation#operation/getOfferUsingGET)).
