### ISSUE TITLE
Aktywacja konta

### ISSUE THREAD

**Issue by KonradLewinski** [allegro/allegro-api#5825]
Dzień dobry,
Utworzyłem konto sandbox na adres email contact.sysmo@gmail.com bardzo proszę o jego aktywację/weryfikację

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by KonradLewinski** [comment]
Dziękuję 😃
Czy mogę jeszcze poprosić o aktywację konta sysmo.telstar@gmail.com

**Comment by KonradLewinski** [comment]
Mam jeden problem:
Jak próbuję dodać jakąś ofertę to wyskakuje mi komunikat 'Użytkownik z blokadą konta firma nie może wystawić nowych ofert' mimo że wszystko mam już zweryfikowane itd.
Nie wie m co zrobić w tej sytuacji

**Comment by AureliuszBrussy** [comment]
@KonradLewinski wyjaśniam ten problem. Wrócę do Ciebie z odpowiedzią.

**Comment by AureliuszBrussy** [comment]
@KonradLewinski widzę, że udało Ci się już wystawić oferty.
