### ISSUE TITLE
Problem z autoryzacją aplikacji na sandboxie

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5827]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam. Nie moge dokonać autoryzacji aplikacji na sandboxie. Za każdym razem zwraca mi błąd, który za wiele nie mówi.
```json
{
  "errors":[{
    "code":"ERROR",
    "message":"An error has occurred",
    "details":null,
    "path":"/auth/oauth/authorize",
    "userMessage":null
  }]
}
```
Przykładowy link, który wykorzystuje: https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=98310865c92649e4a57413a6ff000d33&redirect_url=http://prestosandbox.eltrox.pl/api/allegro/account/105101803/token/save
Jeszcze wczoraj wszystko działało.

**Comment by AureliuszBrussy** [comment]
W linku zmień "redirect_ur**l**" na "redirect_ur**i**".

**Comment by Himon-SYNCRAFT** [comment]
Czy to jakaś zmiana, która wchodzi na stałe i czy wejdzie też na produkcję? Szczerze mówiąc nie ruszałem kodu do autoryzacji "od lat" i nie wiem jaki cel miała by taka zmiana, a człowiek troche nerwów traci szukając problemu w swoim kodzie.

**Comment by Himon-SYNCRAFT** [comment]
I dziękuje za pomoc. Teraz zadziałało

**Comment by AureliuszBrussy** [comment]
Nie wprowadzaliśmy żadnych zmian. Zawsze poprawne było "redirect_uri".
