### ISSUE TITLE
pytanie - znaki specjalne w responsach (REST API)

### ISSUE THREAD

**Issue by collector1871** [allegro/allegro-api#583]
będę mielił dane przez pliki `csv`, stąd trzeba przyjąć jakąś koncepcję

jako delimiter wstępnie  `;`

pytanie: czy w reponsach - z wyjątkiem tytułu i opisu - pojawia się często ten znak?
trzeba go jakoś escape? jak to wygląda ze znakami specjalnymi ?

bo jak zbyt często i zbyt dużo tego jest - oraz będą jakieś problemy ze znakami - to chyba lepiej od razu bazę postawić
csv czy baza?

**Comment by MarcinLuczak** [comment]
@collector1871 to bardzo szerokie pytanie i nie jestem w stanie odpowiedzieć Ci jednoznacznie. Raczej nie powinieneś zakładać, że średnik pojawi się tylko w tych dwóch miejscach.

Najlepiej będzie, jeśli znajdziesz i skorzystasz z jakiejś biblioteki do parsowania JSON-ów i i z biblioteki do generowania plików csv, która przekonwertuje Ci tekst, który chcesz.

**Comment by collector1871** [comment]
Jakby kogoś interesował nadal temat (budowa CSV pod zarządzanie listingiem):

przeczesałem około **1400** aukcji (próbka): `grep -r ';' ./`
znak `;` zawarty został w: `grep -lr ';' ./ |wc -l` ==> wynik to 7 .

głównie chodzi o znaki xml/html - `&amp;` , `&lt;` , `&gt;` 
`grep -lr 'amp;' ./ |wc -l` ==> wynik 4
`grep -lr 'lt;' ./ |wc -l` ==> wynik 1
`grep -lr 'gt;' ./ |wc -l` ==> wynik 1
plus zwykły tekst w opisie

generalnie wszystko pojawia się wewnątrz  `[{"items":[{"type":"TEXT","content":` , a więc w opisie. Można probówać to ominąć, ale są lepsze sposoby.

Wydaje mi się więc, że nie powinno być bugów kontekście tego delimitera, ale ... udało mi się znaleźć chyba lepszy:
`grep -lr '|'` ./ ==> wynik to 0
`grep -lr '~'` ./ ==> wynik to 0

Myślę jednak nad przyznaniem jako delimitera jakoś bardzo rzadkiego znaku, np. z chińskiego alfabetu. Wtedy nie powinno być problemów z oznaczeniem pól, escape i "cytowaniem" ich. Oczywiście jak komuś nie chce się bawić, no to pozostaje escape/cytowanie/qoutation mark.

Można próbować też iść w stronę "pdwójnego/wielokrotnego delimitera", czyli wziać 2 znaki obok siebie, np. `~|`

**Comment by collector1871** [comment]
tak wiem, ale wtedy trzeba escape/qoutation mark
z mojego doświadczenia (dane po 300k rekordów) wynika, że te escapy/quotation marki powodują, że dane często się rozjeżdżają... wtedy trzeba się bawić w additional checki (np. sprawdź czy delimiter w linii występuje określoną ilość razy -> a jak nie, to exception handling).

lepiej wziąć wielokrotny delimiter

**Comment by TimothyKoval** [comment]
Coś panie kombinujesz, albo się nie rozumiemy. Każdy rekord który nie jest stricte numeryczny zamieniasz `"` na `""` i zamykasz go w cudzysłowiu. Delimiter nie ma tu nic do rzeczy, bo będzie ignorowany jeżeli będzie zamknięty w cudzysłowiu.

Nawet [Wikipedia](https://pl.wikipedia.org/wiki/CSV_(format_pliku)) odpowiada na Twoje pytanie :)

> - Wartości pól mogą być ujęte w cudzysłowy,
> - Wartości zawierające używany znak separatora (przecinek, średnik, znak tabulacji lub znaki końca linii) muszą być ujęte w cudzysłowy.
> - Aby w treści pola umieścić cudzysłów należy wpisać znak cudzysłowu dwukrotnie, całą wartość ujmując w cudzysłowy (por. przykłady).
