### ISSUE TITLE
podłączenie oferty do produktu ale z inną kategorią

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5830]
Odczytuję z bazy produktowej produkt. Widzę w nim kategorię "... -> Pozostałe" która w mojej ocenie jest błędna. Jak zachowa się API jeśli będę próbował wystawić taką ofertę podłączoną do tego produktu ale ustawię inną kategorię niż "... -> Pozostałe"?

Pozdrawiam

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji otrzymasz komunikat błędu, który poinformuje o tym, że kategoria w ofercie nie odpowiada kategorii produktu - `"The offer category {offerCategoryId} does not match the product category {productCategoryId}."`. Jeśli uważasz, że kategoria jest błędna, możesz [zgłosić błąd danych w produkcie ](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-zglosic-blad-w-produkcie) lub wystawić ofertę w [kategorii podobnej ](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-w-kategorii-podobnej).
