### ISSUE TITLE
[REST-Total]: STOP! Dajecie tydzień - bez podania szczegółów zmian (GTIN)!!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#5831]
Odnośnie lakonicznego komunikatu z tego tygodnia, z którego niewiele wynika...
- po pierwsze, nie podaliście konkretnej daty zmian związanych z polem GTIN
- w niejasnym terminie chcecie ZABLOKOWAĆ wszelką edycję milionów ofert
- mamy wojnę i postęp inflacji, jedna z częstszych akcji teraz - to zmiana cen!!
- co ma oznaczać, że blokada dotknie ofert z kodem GTIN, który "nie istnieje"?
- kiedy podacie konkretne zasady walidacji pola GTIN - w dniu wdrożenia?!?!?

Jak przygotować moduły czy aplikacje REST-API, a szczególnie sprawdzić i przygotować ofertę na kontach sprzedażowych, kiedy NIE ZNAMY daty ani konkretnych zasad BLOKOWANIA edycji ofert?? Ludzie - obudźcie się tam!!! Wojna za granicą do cholery...

**Comment by AureliuszBrussy** [comment]
Zmiana wejdzie w życie na początku lipca - aktualnie nie jestem w stanie wskazać bardziej konkretnej daty. W dniu wdrożenia sprzedający otrzymają odpowiednią informację.

Tak jak wspomnieliśmy w komunikacie - dodatkowa walidacja będzie polegać na tym, że będziemy dodatkowo sprawdzać zgodność pierwszych kilku cyfr tj. prefixów ze specyfikacją GS1. 

W zależności od liczby znaków w GTINie prefix to:
- GTIN-8 - pierwsze 3 znaki
- GTIN-12 - pierwsze 2 znaki
- GTIN-13 - pierwsze 3 znaki
- GTIN-14 - pierwsze 4 znaki.

Na [stronie GS1](https://www.gs1.org/standards/id-keys/company-prefix) znajdziesz rodzaje błędnych prefiksów w zależności od danego prefixu.

W przypadku szkicu nastąpi jego walidacja, której szczegóły zwrócimy w polu **validation.errors**. Podobnie z dotychczasowymi ofertami - ich ponowna próba aktywacji lub edycja zwróci również komunikat z przyczyną błędu - dodane zostaną 3 wersje komunikatów:

* Numer, który zaczyna się od XXXX to Numer Ograniczonej Dystrybucji - RCN i nie może być wykorzystany na Allegro. Skontaktuj się z dystrybutorem, wydawcą lub producentem i uzyskaj poprawny numer EAN (GTIN). Dowiedz się więcej.
* Podany EAN (GTIN) jest niepoprawny. GS1 nie nadaje numerów, które zaczynają się od XXXX. Skontaktuj się z dystrybutorem, wydawcą lub producentem i uzyskaj poprawny numer EAN (GTIN). Dowiedz się więcej.
* Numer GTIN, który zaczyna się od XXXX, jest przeznaczony do automatycznej obsługi zwrotów pustych pojemników (np. butelek, palet) i nie może być wykorzystany na Allegro. Skontaktuj się z dystrybutorem, wydawcą lub producentem i uzyskaj poprawny numer EAN (GTIN). Dowiedz się więcej.


Tak jak napisał @MaciejFrackowiak w [wątku](https://github.com/allegro/allegro-api/issues/5810) - na kilka dni przed produkcyjnym wdrożeniem zmiany - kolejne warunki walidacyjne zostaną wdrożone na Sandbox. Natomiast i tutaj na chwilę obecną nie ma jeszcze określonego dokładnego terminu zmiany.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy / @MaciejFrackowiak - oto realne warunki zmian do przyjęcia:
- z początkiem lipca 2022 dodajcie ostrzeżenia dot. GTIN (w polu validation.warnings)
- niech każdy sprzedający ma tu czas na sprawdzenie tego i uporządkowanie sytuacji
- od 1 sierpnia zróbcie sobie blokadę edycji (zbieżnie z obowiązkiem dla Produktów)
- przemyślcie jeszcze ten durny obowiązek 100% ofert startujących z Produktem!!

Pamiętajcie tam zawsze, że tą swoją stabilną robotę na etatach (za grubą kasę) macie dzięki setkom tysięcy drobnych sprzedających, a nie dzięki jakiemuś obecnemu Prezesowi... Przez długie lata już zniszczyliście tysiącom osób drobne biznesiki, więc nie czujcie się tam "panami sytuacji" - wojna dopiero się rozkręca, nie wiadomo co i kiedy kogo jeszcze dosięgnie.

**Comment by hahyes** [comment]
> @AureliuszBrussy / @MaciejFrackowiak - KorpoBrednie...
> 
> Czyli NIE PODACIE nawet daty BLOKADY EDYCJI milionów ofert, tak??? P.S. Co stoi na przeszkodzie, aby system walidacji na produkcji zgłaszał dziś ostrzeżenia dot. GTIN??

@FromAnyHole Myślę, że po prostu tego systemu walidacji nie ma jeszcze na produkcji. Wnioskując po ich wypowiedziach, sami nie są w stanie podać sensownego terminu, bo to zależy od systemu walidacji, który jest tworzony przez zupełnie inny dział (bo system walidacji jest globalny dla całego Allegro). Jeżeli nie ma tego systemu na produkcji, to nie są w stanie podać realnego terminu, choćbyś do nich przyjechał osobiście się wykłócać. A przecież oni tutaj nie będą rozmawiać na temat tego, jak idą u nich prace wewnątrz firmy, bo to jest natychmiastowe zwolnienie z pracy.

**Comment by FromAnyHole** [comment]
@hahyes - a kolega co tu uprawia za wolontariat prawniczy? Szukają pełnomocników?

A poważnie już, napisz dlaczego parę dni temu mogli coś dorzucić do Sandbox, a na produkcji "nie potrafią" tego dodać do ostrzeżeń w polu walidacji?? Na to NIE MA UZASADNIENIA, to tylko ZŁA WOLA!! Na ten śmieszny Sandbox, co często nie działa poprawnie i zbieżnie z produkcją, nie da się tak po prostu "przerzucić" dziesiątek tysięcy ofert, aby wyłapać błędne kody GTIN...

**Comment by hahyes** [comment]
> a kolega co tu uprawia za wolontariat prawniczy?

@FromAnyHole Daruj sobie takie wrzuty, bo to żałosne. Wyrażam więcej zrozumienia dla pracy tych ludzi i nie rzucam z góry, że chcą źle. Allegro to nie jest firma kilkuosobowa, gdzie każdy ma bezpośrednią decyzyjność. Tam są całe działy, często uzależnione od pracy pozostałych działów, aby móc wykonywać swoją pracę. To korporacja.

>A poważnie już, napisz dlaczego parę dni temu mogli coś dorzucić do Sandbox, a na produkcji "nie potrafią" tego dodać do ostrzeżeń w polu walidacji?? Na to NIE MA UZASADNIENIA, to tylko ZŁA WOLA!!

1. Obowiązuje nadal netykieta, przestań się drzeć jak jakiś troll internetowy. Ja do ciebie nie krzyczę.
2. Oczywiście, że jest. Sandbox i produkcja to dwa osobne systemy, które nie mają ze sobą bezpośredniego połączenia. Jeżeli system walidacji nie jest gotowy, jeżeli nadal testują i wyłapują błędy to mają takie coś dodać na produkcję? Pomyślałeś, jak fatalne to może mieć skutki? Wyobraź sobie, że wysypuje się cały zasób. Kto poniesie odpowiedzialność? Krasnoludki? Tam się przewijają każdego dnia miliony złotych, a ty chcesz, żeby oni dodali coś ot tak, bo ty sobie żądasz? 
3. Zgadzam się z tym, że robią to na ostatni moment. Tylko z tego wynika niekompetencja w Allegro zarządzających. Dali termin do wykonania, może jakiś dyrektor sobie coś wymyślił na już "bo powinno być". Ja w tej branży też pracuje i tak jest nie raz. To są doświadczenia setek jak nie tysięcy programistów w tej pracy. Rzucając się do programistów od API, którzy najpewniej nawet systemu walidacji na oczy nie widzieli... no zlituj się. Tego tutaj wysoki szczebel czyli menadżerowie i dyrektorzy nie czytają. Oni mają twoje konwulsje gdzieś.
4. Rozumiem, że ty nie jesteś programistą, skoro twierdzisz, że się nie da? Bo wyłapać błędne kody GTIN przez sandboxa można jakimś prostym programikiem napisanym w parę godzin bez większego bólu. Kwestia podejścia.

**Comment by FromAnyHole** [comment]
@hahyes - samo się to komentuje, tak zniszczono całe Allegro!!

**Comment by FromAnyHole** [comment]
@hahyes - nie masz człowieku chyba pojęcia o czym piszesz... Przez "pole ostrzeżeń" w walidacji na produkcji - przez kilka przewinęła się cała masa przeróżnych ostrzeżeń, które wielokrotnie zmieniano, z wielu się wycofano, no i NIKOMU to nie zrobiło żadnej krzywdy. To pole od początku jest całkowicie nieinwazyjne, bo tego zostało stworzone, aby z wyprzedzeniem powiadamiać i/lub ostrzegać. Chyba nie znasz dobrze tego CYRKU, bo zapewniam tu wszystkich - kiedy w końcu wprowadzą te zmiany, to potem i tak jeszcze kilka razy zmienią zasady, więc daj se spokój z pouczaniem...

**Comment by FromAnyHole** [comment]
@hahyes - nie masz człowieku pojęcia o czym piszesz... Przez "pole ostrzeżeń" w walidacji na produkcji - przez kilka lat przewinęła się cała masa przeróżnych ostrzeżeń, które wielokrotnie zmieniano, z wielu się wycofano, no i NIKOMU to nie zrobiło żadnej krzywdy. To pole od początku jest całkowicie nieinwazyjne, bo tego zostało stworzone, aby z wyprzedzeniem powiadamiać i/lub ostrzegać. Chyba nie znasz dobrze tego CYRKU, bo zapewniam tu wszystkich - kiedy w końcu wprowadzą te zmiany, to potem i tak jeszcze kilka razy zmienią zasady, więc daj se spokój z pouczaniem...

**Comment by hahyes** [comment]
> @hahyes - nie masz człowieku pojęcia o czym piszesz... Przez "pole ostrzeżeń" w walidacji na produkcji - przez kilka lat przewinęła się cała masa przeróżnych ostrzeżeń, które wielokrotnie zmieniano, z wielu się wycofano, no i NIKOMU to nie zrobiło żadnej krzywdy. To pole od początku jest całkowicie nieinwazyjne, bo tego zostało stworzone, aby z wyprzedzeniem powiadamiać i/lub ostrzegać. Chyba nie znasz dobrze tego CYRKU, bo zapewniam tu wszystkich - kiedy w końcu wprowadzą te zmiany, to potem i tak jeszcze kilka razy zmienią zasady, więc daj se spokój z pouczaniem...

@FromAnyHole System walidacji jest poza API Allegro. Oni tam fizycznie nie mają dostępu do systemu walidacji NA PRODUKCJI, bo go nie udostępniono im na produkcję. Nie wdrożą na produkcję testowego systemu walidacji z sandboxa. Oni nie mogą cię ostrzeć o złym GTIN, jeżeli nie mają w rękach narzędzia do zwalidowania tych danych. Narzędzia z testowego systemu nikt na produkcję nie wdroży, bo to jest proszenie się o kłopoty. Ile mam tłumaczyć to samo? Jak by ci wdrożyli te ostrzeżenia i cały system się wypierdzielił, to też byś tutaj pierniczył głupoty, że jak mogli API popsuć? A może chcesz zapłacić za straty i poniesione koszty, jak walnie? Chciałbyś ponieść osobiście ryzyko wdrożenia czegoś niesprawdzonego na produkcję, bo tak bardzo tego chciałeś? 

Ty nie rozumiesz, jak poważne konsekwencje przy tej skali przedsiębiorstwa ma "a sobie coś dodam bo jakiś losowy typek mnie prosi" i wszystko się wysypie na pysk. Ostrzeżenia dawali, kiedy mogli. A nie, kiedy to kompletnie od nich nie zależy. Twoje 15 tysięcy ofert kosztuje mniej jak dzienny przychód Allegro. A wierz mi, na programiście są takie kary umowne, że wykupują ubezpieczenia na takie okazje.

**Comment by FromAnyHole** [comment]
@hahyes - to w którym dziale kolega tam pracuje w Poznaniu?? ;-)

**Comment by hahyes** [comment]
> to w którym dziale kolega tam pracuje w Poznaniu?? ;-)

@FromAnyHole A coś na temat, czy skończyły się argumenty? :)

**Comment by FromAnyHole** [comment]
@hahyes - nie masz człowieku pojęcia o czym piszesz... Przez "pole ostrzeżeń" w walidacji na produkcji - przez kilka lat przewinęła się cała masa przeróżnych ostrzeżeń, które wielokrotnie zmieniano, z wielu się wycofano, no i NIKOMU to nie zrobiło żadnej krzywdy. To pole od początku jest całkowicie nieinwazyjne, do tego zostało stworzone, aby z wyprzedzeniem powiadamiać i/lub ostrzegać. Chyba nie znasz dobrze tego CYRKU, bo zapewniam tu wszystkich - kiedy w końcu wprowadzą te zmiany, to potem i tak jeszcze kilka razy zmienią zasady, więc daj se spokój z pouczaniem...

**Comment by hahyes** [comment]
> @hahyes - nie masz człowieku pojęcia o czym piszesz... Przez "pole ostrzeżeń" w walidacji na produkcji - przez kilka lat przewinęła się cała masa przeróżnych ostrzeżeń, które wielokrotnie zmieniano, z wielu się wycofano, no i NIKOMU to nie zrobiło żadnej krzywdy. To pole od początku jest całkowicie nieinwazyjne, do tego zostało stworzone, aby z wyprzedzeniem powiadamiać i/lub ostrzegać. Chyba nie znasz dobrze tego CYRKU, bo zapewniam tu wszystkich - kiedy w końcu wprowadzą te zmiany, to potem i tak jeszcze kilka razy zmienią zasady, więc daj se spokój z pouczaniem...

@FromAnyHole Po co kopiujesz to samo? Wyjaśniłem ci już, o co chodzi, tylko ty nie przyjmujesz tego do wiadomości. Mam dużo większe pojęcie od ciebie, co tylko zachowujesz się jak pieniacz.

**Comment by FromAnyHole** [comment]
Tak się tu kręci i wprowadza ludzi w błąd:

https://github.com/allegro/allegro-api/issues/5810
