### ISSUE TITLE
Limit zapytań API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5832]
Tworzymy mechanizm mapowania już wystawionych ofert Allegro z naszym wewnętrznym systemem. Nurtuje mnie kwestia limitów minutowych na zapytania. Przy dokumentacji znalazłem informację: `W usłudze Allegro REST API (produkcyjnej oraz testowej) obowiązuje główny limit nakładany na Client ID (lub Software Statement ID w przypadku DCR) - 9000 zapytań na minutę.`

Zastanawia mnie czy powyższy limit sumuje się również dla mechanizmu przesyłania zdjęć do Allegro, który znajduje się na osobnej subdomenie, czy może dla tej subdomeny jest osobny limit:

```
- https://upload.allegro.pl for Production
- https://upload.allegro.pl.allegrosandbox.pl for Sandbox
```

W przypadku pobierania hurtowo kilkuset ofert, w których jest max zdjęć (czyli 16), łatwo przewalić limit 9000 zapytań na minutę. Przesłanie jednego zdjęcia wymaga jednego zapytania, stąd moje zapytanie o limit

**Comment by hahyes** [comment]
Kiedy pobierasz zdjęcia, nie są one na domenie `upload.allegro.pl`, tylko pobierasz je z domeny do zdjęć `a.allegroimg.com`. Stąd raczej nie będzie problemu z pobieraniem zdjęć.

**Comment by MartaNowaczyk** [comment]
Dokładnie, limit nakładany jest na ClientID. W takim wypadku nie wysyłasz requestu, stąd nie wlicza się to do limitu.
