### ISSUE TITLE
[API][Wysyłam Allegro] Allegro One Punkt

### ISSUE THREAD

**Issue by K4R0LW** [allegro/allegro-api#5833]
Witam, próbuję utworzyć paczkę dla zamówienia z metodą dostawy Allegro One Punkt, jednak nie wiem jak uzupełnić sekcję "pickup" w request'cie na endpoint'cie "/parcel-management/parcel-create-commands/". Trzeba tam podać pointId. Czy jest jakiś inny zasób w api który pozwala pobrać miejsca nadania takich paczek i id ich punktów?

Przykładowy response:
{"id":"a5b2bc44-6166-401c-8260-8ec4b766ad72","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Pickup point is incorrect","details":null,"path":"pickup.pointId","userMessage":"Punkt punktu nadania przesyłki jest niepoprawny"}]}

**Comment by PrzemyslawLukanowski** [comment]
Tak, listę punktów Allegro pobierzesz za pomocą [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-liste-punktow-allegro).

**Comment by K4R0LW** [comment]
Dziękuję, teraz wybrałem odpowiedni dla mnie punkt i dostaję w odpowiedzi taki komunikat:

Błąd generowania etykiety - {"id":"1006227b-0047-4144-954c-6e03e843412e","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Błąd przetwarzania. Support został poinformowany o Twoim problemie i pracuje nad rozwiązaniem"}]}

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację z zespołem odpowiedzialnym za usługę. Wrócę z informacją, gdy uda się coś ustalić.

**Comment by PrzemyslawLukanowski** [comment]
Błąd występuje, ponieważ próbujesz nadać przesyłkę z miejscowości, której kod pocztowy pocztowy nie jest obsługiwany w strefie One Kuriera. Dostępność usługi Allegro One Kurier sprawdzisz [na tej stronie](https://allegro.pl/kampania/one/kurier#gdzie).
