### ISSUE TITLE
Ads API

### ISSUE THREAD

**Issue by aheldesgb** [allegro/allegro-api#5834]
Hi team,

is there an endpoint for ads data from `https://ads.allegro.pl/panel/stats/premium`? And also is there a way to get data for `mega okazje` promotions?

Thanks

Adrian

**Comment by MartaNowaczyk** [comment]
Currently it is not possible to access ADS via API. If we decide to make them public in the future, we will inform about it in a separate message on the forum and [in the news](https://developer.allegro.pl/news) on the portal.

You can manage promotional campaigns via API. You can read more on [our website](https://developer.allegro.pl/tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4).

**Comment by aheldesgb** [comment]
Hi @MartaNowaczyk ,

thanks for your answer. When it comes to the `mega okazje` promotion, which billing type is it logged under? Is it just `Promotion`? Thanks

**Comment by MartaNowaczyk** [comment]
According to the [news](https://allegro.pl/dla-sprzedajacych/zakonczymy-program-mega-okazje-K6wyK85Dauw), "Mega okazje" will no longer be available. Unfortunately, it is only in Polish, please translate it.
