### ISSUE TITLE
Problem z parametrami aukcji/produktu

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5837]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam

W jaki sposób powieniem przesłać parametry aukcji  w przypadku jeśli produkt już istnieje natomiast ma nieuzupełnione parametry obowiązkowe?

Mam aukcję z numerem ean, którą łączę z produktem o id: 280ee7f4-7b69-4a71-84dd-c88f95594402, który to nie ma uzupełnionego modelu, a Marke ustawioną jako Inna (EZVIZ).
Z modelem w ogole nie wiem jak sobie poradzić, a w przypadku marki jeśli ustawie identyczną wartość jak na produkcie, dostaje zwrotnie info, że marka Ezviz już jest w słowniku, ale nawet gdybym chciał zgłosić błąd na produkcie to nie mogę jej wybrać :(

trace-id: fdc0f631169d521c

**Comment by MartaNowaczyk** [comment]
Witam, w takim wypadku najlepiej zgłosić błąd w produkcie. Jeśli nie możesz zmienić poszczególnych parametrów lub nie zgadzasz się z danymi produktu, których zmienić nie możesz - opisz to w w informacjach dodatkowych. Przez API też jest możliwość zgłoszenia - więcej na naszej [stronie](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-zglosic-blad-w-produkcie). Marka EZVIZ jest już dostępna.

**Comment by MartaNowaczyk** [comment]
> W jaki sposób powieniem przesłać parametry aukcji w przypadku jeśli produkt już istnieje natomiast ma nieuzupełnione parametry obowiązkowe?

Powinieneś uzupełnić brakujące parametry obowiązkowe, przekazując je w obiekcie product. Więcej [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#kliknij-aby-zobaczyc-request)

**Comment by Himon-SYNCRAFT** [comment]
Tak, rzeczywiście przesłany tutaj json był błedny, ale to kwestia wklejenia 2 razy. Poprawiłem juz w poprzednim poście na taki jaki rzeczywiście wysyłam (bez opisu).

**Comment by PrzemyslawLukanowski** [comment]
Czy obecnie nadal otrzymujesz wspomniany błąd? Pytam, ponieważ nie udało mi się go powtórzyć. Jeżeli użyję niemalże identycznej struktury (usunąłem wartości, które identyfikują danego sprzedawcę i dodałem obiekt `price` w `sellingMode`), oferta z produktem wystawia się prawidłowo:

```
{
  "category": {
    "id": 52558
  },
  "ean": "5902270773101",
  "external": {
    "id": "31752"
  },
  "location": {
    "city": "Cała Polska",
    "countryCode": "PL",
    "postCode": "42-200",
    "province": "SLASKIE"
  },
  "name": "Tuner DVB-T2 LTC LX-DVB101 H.265 HEVC dekoder TV",
  "parameters": [
    {
      "id": 11323,
      "valuesIds": [
        "11323_1"
      ],
      "required_for_product": false
    }
  ],
  "stock": {
    "available": 100,
    "unit": "UNIT"
  },
  "sellingMode": {
    "format": "BUY_NOW",
     "price": {
      "amount": "220.85",
      "currency": "PLN"
    }
  },
  "productSet": [
    {
      "product": {
        "id": "5b5f2726-4b38-4f9c-9774-1bd2b7de7c8c",
        "parameters": [
          {
            "id": 17448,
            "values": [
              "0.4"
            ],
            "required_for_product": true
          },
          {
            "id": 226665,
            "valuesIds": [
              "226665_1",
              "226665_2",
              "226665_4",
              "226665_8"
            ],
            "required_for_product": true
          },
          {
            "id": 217645,
            "values": [
              "Pilot",
              "baterie"
            ],
            "required_for_product": true
          }
        ]
      }
    }
  ],
  "payments": {
    "invoice": "VAT"
  },
  "images": [
    "https://allegro2.eltrox.pl/zdjecia/31752/tuner_dvbt2_ltc_lxdvb101_h265_hevc_7d1f27e54f35d.jpg",
    "https://allegro2.eltrox.pl/zdjecia/31752/tuner_dvbt2_ltc_lxdvb101_h265_hevc_9c0b2f42235e5.jpg",
    "https://allegro2.eltrox.pl/zdjecia/31752/tuner_dvbt2_ltc_lxdvb101_h265_hevc_6d501e8f5f0bc.png",
    "https://allegro2.eltrox.pl/zdjecia/31752/tuner_dvbt2_ltc_lxdvb101_h265_hevc_dbd174b443460.jpg",
    "https://allegro2.eltrox.pl/zdjecia/31752/tuner_dvbt2_ltc_lxdvb101_h265_hevc_d823941f21676.jpg"
  ],
  "publication": {
      "status": "INACTIVE"
  }
}
```

**Comment by PrzemyslawLukanowski** [comment]
W sekcji product.parameters musisz przekzać wszystkie parametry, nie tylko te brakujące. Zgodnie z informacją z naszego [poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-edytowac-oferte), dla metody **PATCH**, z której korzystasz:

> Jeżeli chcesz zachować aktualny opis, zdjęcia i **parametry produktowe**, oprócz product.id powinieneś przekazać również takie pola jak: description, images i **product.parameters**.

**Comment by Himon-SYNCRAFT** [comment]
Ok. To by wyjaśniało temat. A żeby jeszcze uściślić mam pytanie. Podobna sytuacja jak tutaj, ale korzystam z metody POST, żeby dodać nową aukcję powiązaną z produtkem i produkt nie ma wszystkich uzupełnionych wymaganaych parametrów. Wtedy wysyłam w product.parameters tylko brakujące czy też wszystkie parametry?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku metody POST możesz wysłać tylko brakujące parametry.
