### ISSUE TITLE
Internal Server Error podczas pobierania płatności

### ISSUE THREAD

**Issue by egro-allegro** [allegro/allegro-api#5838]
Dzień dobry.
Od ponad godziny mam problemy z pobraniem płatności przez API na produkcji u mojego klienta https://allegro.pl/uzytkownik/Top-Mix
Wysyłając request:
https://api.allegro.pl/payments/payment-operations?occurredAt.gte=2022-06-28T11:30:59.075Z 
otrzymuję cały czas response: 
{"errors":[{"code":"INTERNAL_SERVER_ERROR","message":"Internal server error.","details":null,"path":null,"userMessage":"Wewnętrzny błąd serwera. Spróbuj ponownie za kilka minut."}]}

trace-id: bcd9b9a9b0fc7bbf

**Comment by MartaNowaczyk** [comment]
Weryfikuję sprawę, wrócę z odpowiedzią. Czy problem nadal występuje?

**Comment by MartaNowaczyk** [comment]
Potwierdzam, dla ograniczonej ilości transakcji może występować opisany problem. Pracujemy nad rozwiązaniem. Dzięki za zgłoszenie!
