### ISSUE TITLE
Problem z autoryzacją 

### ISSUE THREAD

**Issue by Mateusz-Nejman** [allegro/allegro-api#5840]
Typ aplikacji: DEVICE
Problem: Klient zgłosił, że od rana podczas próby odświeżenia dostępu allegro zwraca mu błąd:
`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/authorize","userMessage":null}]}`

Błąd wyświetla się pod adresem https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=...&redirect_url=...

**Comment by MartaNowaczyk** [comment]
W żądaniu masz `redirect_url` zamiast `redirect_uri`.
