### ISSUE TITLE
Skąd wziąć klucz RestApi

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5841]
Witam,
Zadałem sobie trud: czytałem w dokumentacji i szukałem na githubie.

Wczoraj i przedwczoraj allegro RestApi chodziło mi bez problemu,
Dzisiaj podczas logowania aplikacji (podczas przekierowania użytkownika na allegro) dostaję taki błąd:

"Nie możemy wyświetlić strony

Numer błędu: 76942d82a0a0f258"

Tak generuję AUTHORIZATION_URI:
Podaję 3 wymagane parametry:

public function getAuthorizationUri()
    {
        $data = array(
            'response_type' => 'code',
            'client_id' => $this->clientId,
            'redirect_uri' => $this->redirectUri /*https://mazoretka.opolex.pl/admin/orders_tracking.php*/
        );

        return static::AUTHORIZATION_URI . '?' . http_build_query($data);
    }

Nie wiem co robię nie tak.
Będę wdzięczny za pomoc

**Comment by Witold1983** [comment]
Czasem dostaję jeszcze to: {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/auth/oauth/authorize","userMessage":null}]}

**Comment by MartaNowaczyk** [comment]
Adres przekierowania, który podajesz w aplikacji, różni się od tego, który zarejestrowałeś na stronie https://apps.developer.allegro.pl/. Te adresy muszą być identyczne.

**Comment by Witold1983** [comment]
Dobrze, bardzo dziękuję za odpowiedź. 
Zadziałało.
