### ISSUE TITLE
Co zrobić jeśli chcemy produkt połączony z katalogiem wystawić w innej kategorii?

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#5843]
Witam,
Pytanie jak w temacie:
Mamy produkt powiązany z katalogiem, który został wystawiony w kategorii 18001 a my chcielibyśmy to skorygować i wystawić go w kategorii 16027. Lecz wówczas jest problem z ustawianiem parametrów. Dodając produkt drugi raz, do kategorii 16027 nie mogłem go powiązać z katalogiem, bo wówczas oferta jest przenoszona do starej kategorii 16027. Pytam, bo jak czytam, od 1 sierpnia ma być wymóg 100% powiązanych z katalogiem. A to już raptem został miesiąc.

Ten produkt to:
https://allegro.pl/oferta/12329095050

**Comment by MartaNowaczyk** [comment]
Podana kategoria 18001 to Kolekcje i sztuka - Kolekcje - Birofilistyka - Kufle - Ceramiczne, a podana oferta "Zestaw - Pałeczka Mistral, Owijka i Pokrowiec 80cm" jest w kategorii 16027 Sport i turystyka - Sporty towarzyskie i rekreacja - Żonglerka - Kije, Sticki - czyli w poprawnej kategorii. 

> wówczas oferta jest przenoszona do starej kategorii 16027
w takim wypadku wygląda na to, że prawidłowo jest przenoszona. Chyba, że chodziło Ci o 18001?  

Czy możesz podać id produktu (nie oferty), który chcesz przypisać do tej oferty, albo trace-id próby przypisania?

**Comment by Witold1983** [comment]
Witam, tutaj jest oferta (jedna z dziewięciu), których nie powiązałem z racji tego, że produkty w katalogu są w kategorii 18008 a chcę wystawić je w kategorii 16027:
https://allegro.pl/oferta/zestaw-paleczka-mistral-owijka-i-pokrowiec-80cm-12329095050
Tutaj jest EAN tej oferty: 5900091714242

**Comment by MartaNowaczyk** [comment]
W takim wypadku zgłoś propozycję zmiany kategorii w produkcie. Możesz to zrobić [przez API](https://developer.allegro.pl/tutorials/jak-powiazac-oferte-z-produktem-BvZjx6exPfD#jak-zglosic-blad-w-produkcie) albo [na stronie allegro](https://allegro.pl/dla-sprzedajacych/jak-zglosic-blad-w-produkcie-ZGZG89WkOU0#jak-mozesz-zglosic-bledne-lub-brakujace-dane).
