### ISSUE TITLE
restricting attributes on create offer at category id 260997

### ISSUE THREAD

**Issue by abhishekkumar20cedommerce** [allegro/allegro-api#5845]
Hi,
    we are creating  offer at category id 260997, So api does not allow own parameter value  or marketplace paramter value, api get error on both case. please check.
![Screenshot_2022-07-01_20-25-06](https://user-images.githubusercontent.com/79986688/176919210-83252943-61dc-42ef-a64b-128f4c8ef2b8.png)
![Screenshot_2022-07-01_20-25-16](https://user-images.githubusercontent.com/79986688/176919221-5d3443e2-2f5f-4fde-918f-07929322c3e3.png)
![Screenshot_2022-07-01_20-25-52](https://user-images.githubusercontent.com/79986688/176919240-4bb76d7b-7398-4079-bc38-5c3c3a57c752.png)
![Screenshot_2022-07-01_20-26-01](https://user-images.githubusercontent.com/79986688/176919245-2beb4274-44b0-4050-a23b-9830dabbcaa3.png)
![Screenshot_2022-07-01_20-26-08](https://user-images.githubusercontent.com/79986688/176919255-b0ad2297-a213-4f1f-bdfe-60eddc6d6173.png)
![Screenshot_2022-07-01_20-26-20](https://user-images.githubusercontent.com/79986688/176919263-2a3ca6ce-f9c6-470d-b4db-97a0421b1674.png)

**Comment by MartaNowaczyk** [comment]
The correct structure for the "Type" parameter and the "deszczownica" (Rain Shower) value is:
```
{
                         "id": "248288",
                         "name": "Type",
                         "values": [],
                         "valuesIds": [
                             "248288_893470"
                         ],
                         "rangeValue": null
                     },
```
It's best to use valuesIds without typing the names. This parameter is marked as "customValuesEnabled": false, therefore you cannot pass your own value.

More information about the parameters can be found on [our website](https://developer.allegro.pl/tutorials/listing-offers-4RAvLdaqMf8#parameters).

**Comment by abhishekkumar20cedommerce** [comment]
HI,
  thank you now it is working
