### ISSUE TITLE
Dane adresowe nadawcy - DPD

### ISSUE THREAD

**Issue by PawelPseudo** [allegro/allegro-api#5847]
Witam

Nadajemy paczkę metodami wysyłki Allegro i mimo wpisania poprawnych danych nadawcy nie ma ich uwzględnionych na etykiecie.
Co może być powodem ?

**Comment by MaciejFrackowiak** [comment]
Proszę doprecyzuj - czy otrzymujesz jakiś komunikat błędu, czy też dane są ignorowane / inne / przekazywane puste? Proszę podaj także przykładowe id przesyłki lub commandId, dla którego zaobserwowałeś problem.

**Comment by PawelPseudo** [comment]
Wszystko przechodzi ok. Ale na koncu dane ktore podajemy nadawcy sa ignorowane i podstawiane inne.
Podaje numer zamowienia: d6fba7e2-f91c-11ec-8071-e7ed90689eff

**Comment by MaciejFrackowiak** [comment]
Czy przesyłki nadajesz poprzez API czy też przez stronę WWW?

**Comment by PawelPseudo** [comment]
API

**Comment by MaciejFrackowiak** [comment]
Proszę zatem podaj poprawne commandId lub parcelId, ponieważ wskazany przez Ciebie numer to numer zamówienia.

**Comment by PawelPseudo** [comment]
percel id = 86227415

**Comment by MaciejFrackowiak** [comment]
Widzę, że request dla [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel) zawierał dokładnie te dane, które pojawiły się na etykiecie nadawczej. Jeżeli masz zapisane inne dane nadawcy w książce adresowej na stronie WWW to one nie zostaną uwzględnione w procesie zamawiania przesyłki poprzez API.
