### ISSUE TITLE
Przeliczanie trafności ofert

### ISSUE THREAD

**Issue by kfijalko** [allegro/allegro-api#5848]
Czy trafność ofert jest przeliczana na bieżąco, na podstawie określonych zdarzeń (np.: zmiana ceny/ilości, transakcja kupna, dodanie do koszyka/obserwowanych, wystawienie oceny przez kupującego ...) czy batch'owo w jakichś interwałach czasowych (np.: tak jak jakość konta, SS, skuteczność wysyłki) ?

**Comment by MaciejFrackowiak** [comment]
Sortowanie po trafności odbywa się z uwzględnieniem bieżących zmian w ofertach - przykłady opisane są w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/jestem-sprzedajacym-na-czym-polega-sortowanie-po-trafnosci-9dGRXKV4MTl). Jeżeli chciałbyś uzyskać więcej informacji proszę skorzystaj z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
