### ISSUE TITLE
Problem z kodem ean

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5849]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam mam problem z utworzeniem aukcji. Dostaję błąd:
ProductValidationException: Nieprawidłowy kod EAN - 5900378939229

**trace-id: 7a34cf28b6eb12ff**

**Comment by MaciejFrackowiak** [comment]
Podany przez Ciebie EAN ma nieprawidłową cyfrę kontrolną - zamiast 9 powinna być 1. Możesz to sprawdzić na stronie [GS1](https://www.gs1.org/services/check-digit-calculator).

**Comment by Himon-SYNCRAFT** [comment]
Dziękuje za pomoc zmiana pomogła. Ale mam inny problem: dla tego samego produktu dostaje błąd:
CATEGORY_MISMATCH: Na podstawie przesłanych danych rozpoznany został produkt z naszej bazy. Wskazana kategoria `Zabezpieczenia i rozdzielnice` (46107) nie jest zgodna z kategorią produktu: `Obudowy` (67325).

trace-id70764efafed4565f

W kategorii, w której próbuje wystawić aukcję nie ma produktu o takim EANIe, dlatego przesyłam parametry tak jakbym chciał utworzyć nowy. Powinienem w jakiś inny sposób wysyłać informację jeśli chce wystawić aukcje z produktem w innej kategorii niż jest u Pańtstwa w bazie?

**Comment by MaciejFrackowiak** [comment]
Znaleźliśmy produkt w naszej bazie (productId=d880caa2-adb4-4b06-b37c-a5be86ad39e8) i dlatego nie możesz dodać jego duplikatu, nawet mając na uwadze inną kategorię. Wskazany produkt nie ma dodanej żadnej kategorii alternatywnej (category.similar), dlatego możesz zgłosić sugestię zmiany w istniejącym produkcie poprzez [POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal).
