### ISSUE TITLE
błedny response PUT /sale/offer-publication-commands/{commandId}

### ISSUE THREAD

**Issue by riepa** [allegro/allegro-api#585]
Request ten w środowisku produkcyjnym zawsze zwraca:
"taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0}
Testowane w obu przypadkach ACTIVATE i END

**Comment by mjag8** [comment]
Potwierdzam, zawsze ten sam response. Wywołując zasób GET'em można pobrać poprawne info, ale dobrze by było mieć to jednoznaczne

**Comment by MaciejPotepa** [comment]
@riepa podeślesz ID ofert, których dotyczy problem? Dzięki temu będziemy mogli szybciej wyeliminować problem.

**Comment by ircykk** [comment]
Tak u mnie jest to samo ale w poradniku też jest zawsze taki response więc chyba tak ma być..

**Comment by wwwfactory** [comment]
Dzień dobry - podpinam się do tego tematu. Zawsze publikacja oferty (PUT) zwraca 0, 0, 0. Dopiero Get zwraca pola wypełnione. 

Jest natomiast ciekawszy przypadek nad którym warto się zastanowić.
@MaciejPotepa ,

Jeżeli dobrze rozumiem, to co chcieliście uzyskać ma wyglądać mniej więcej tak: 
(oczywiście pamiętamy że jest to metoda asynchroniczna)

1. Publikacja (PUT commandId) -> 
2. Sprawdzenie statusu publikacji zadania (GET commandId) ->
3. Sprawdzenie statusu publikacji oferty (GET commandId/task) 

Teraz po waszej stronie dzieje się coś takiego:

oferta jest sprawdzana a następnie zmieniany jest jej status z INACTIVE na ACTIVE. 
jeżeli  odpytam się o ofertę po id (nie commandId) w dobrym momencie to:

metoda GET ComamndId/tasks zwróci status->SUCCESS
a sprawdzenie oferty GET /sale/offers/offerId zwróci INACTIVE

Pytanie - dlaczego tak się dzieje. Czy pierwsze zadanie nie powinno bazować na drugim ? Wg macie odwróconą kolejność. Jak sądzę najpierw zapisujecie gdzieś do bazy że jest SUCCESS a następnie że ACTIVE. 

pozdrawiamy wwwfactory

**Comment by riepa** [comment]
7545814012
7487456473

**Comment by ircykk** [comment]
@wwwfactory Status oferty a status zadania publikacji to osobne statusy, status publikacji może być SUCCESS a status aukcji może być INACTIVE bo publikacja może trwać jakiś czas o ile dobrze rozumiem.

**Comment by wwwfactory** [comment]
@ircykk - to jak w takim razie sprawdzić czy oferta jest już opublikowana ? status zadania to unikalne ID do którego są podpięte ID oferty. Dobrze się zastanów przed odpowiedzią :) Pamiętaj że to metoda asynchroniczna. Samo odpytywanie się o id w kontekście to ACTIVE / INACTIVE jest błędem logicznym.  Wg mnie task nie ma prawa zwrócić success jeżeli oferta nie jest ACTIVE. Zauważ że status jest podpięty per offer ID a nie per Task !

**Comment by ircykk** [comment]
@wwwfactory tak racja, jeśli task zwraca SUCCESS to oferta powinna być ACTIVE.

**Comment by MaciejPotepa** [comment]
Pracujemy nad rozwiązaniem problemu. 

@wwwfactory @ircykk Dzięki za konstruktywne uwagi, analizujemy temat.

**Comment by wwwfactory** [comment]
@MaciejPotepa Może warto się zastanowić nad jeszcze jedną kwestią,

w obecnej chwili po wystawianiu oferty sprawdzamy czy jest ona ACTIVE/INACTIVE/ENDED (oczywiście również TASKS o czym rozmawiamy powyżej) ale zauważcie jakiej metody do tego używamy.
GET /sale/offers/offerId

nie potrzebujemy całego kompletu informacji dotyczącego oferty samej w sobie. 

a może tak: 

in 
GET /sale/offers/offerId/status 
lub raczej tak 
GET /sale/offers/offerId/statuses   (tablica id)

out
[{
 "offerId": {
    "status": "ACTIVE"
     }
 }]                           
szybkie małe przyjazne załatwia większość logiki

pozdrawiamy wwwfactory.
