### ISSUE TITLE
Deal Zone

### ISSUE THREAD

**Issue by adityakokate** [allegro/allegro-api#5854]
Is **Deal Zone connected** with my account? Is **Deal Zone Connection** a setting on Allegro account? Or have I to set it using API for my offer (which I can see in https://api.allegro.pl/sale/loyalty/promotions API)? Please let me know in details whether it's mandatory to use Deal Zone with offers as the same is asked by Allegro for my account?

Allegro asked me following:
_API connection - do you already have any merchants so that we can check the connection? We would also like to confirm with our API team what they see in their backend. Is the Deal Zone connected? (therefore it would be creat to know what the token is for your connection)_

**Comment by MaciejFrackowiak** [comment]
You can use Deal Zone via [website](https://allegro.pl/moje-allegro/sprzedaz/kampanie) or [API](https://developer.allegro.pl/tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4#submitting-offers-to-campaigns-special-programs-and-allegro-badges). It is not mandatory to use Deal Zone. If you have more questions about Deal Zone, please contact us via [the contact form](https://allegro.pl/pomoc/kontakt?kategoria=b4658887-3555-43cd-91b2-68a7bd6e0f8b&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).

**Comment by adityakokate** [comment]
Thanks for the information. But what would be the answer to "Is Deal Zone connected" asked by Allegro? FYI, I am not setting Deal zone for my offers using DealZone API.

**Comment by MaciejFrackowiak** [comment]
Unfortunately, it is difficult for me to answer this question - I would personally ask for more details.

**Comment by adityakokate** [comment]
I am able to submit offers to campaigns successfully using https://developer.allegro.pl/tutorials/how-to-submit-offers-to-campaigns-AgGjd6EmyH4

But I have come across the following issues:
1. How can I check campaign regulations using API (dynamically / run time) which is provided in regulationsLink parameter (link to campaign regulations) of API https://api.allegro.pl/sale/badge-campaigns
2. After adding "promotion price" (prices.bargain.amount parameter in https://api.allegro.pl/sale/badges API), API won't allow me to increase it...I can decrease it only. The same thing is observed on the Allegro website.
Let's say my fixed price / base price / buy now price (prices.market.amount parameter in https://api.allegro.pl/sale/badges API) is 330,99 PLN and the campaign asked me to set a promotion 
![screenshot-allegro pl-2022 07 06-18_41_17](https://user-images.githubusercontent.com/92523331/177558154-b769a072-134d-46b3-80b0-c9f111f40c97.png)
price at 10% lesser that is 297.00 PLN, but I mistakenly sent 261,00 PLN in API. Then I cant change it to 297.00 PLN. I can change it lesser than 234,90 PLN. Please see attached screenshot for reference.

**Comment by MaciejFrackowiak** [comment]
1. There is no other way - you can only copy URL from "regulationsLink" field and then open it in a browser;
2. In API it works the same as on a website - you cannot increase the promotion price. If you have any question about Deal Zone terms please contact us via [the contact form](https://allegro.pl/pomoc/kontakt?kategoria=b4658887-3555-43cd-91b2-68a7bd6e0f8b&subjectId=43c959cd-f86b-44dd-b7f4-34f9f4a1d372).

**Comment by adityakokate** [comment]
Thanks for the information
