### ISSUE TITLE
Błąd Unprocessable Entity dla metody GET

### ISSUE THREAD

**Issue by emSzmal** [allegro/allegro-api#5856]
Dzień dobry.

Co może generować błąd: "Unprocessable Entity (422)" dla poniższego, banalnego zapytania:
https://api.allegro.pl/payments/payment-operations?limit=50&offset=0&occurredAt.gte=2022-07-03T22:00:00.0000000Z&occurredAt.lte=2022-07-05T22:00:00.0000000Z

Dodam, że błąd występuje tylko u jednego klienta.

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [dokumentacją zasobu](https://developer.allegro.pl/documentation/#operation/getPaymentsOperationHistory) taka sytuacja może mieć miejsce, jeśli w odpowiedzi znaleźliśmy więcej niż 10000 operacji.

**Comment by emSzmal** [comment]
W zapytaniu został przekazany parametr limit (50) i offset, to nie ma on żadnego znaczenia?
Poza tym nie sądzę, aby klient miał 10000 operacji w ciągu raptem 2 dni (bo taki jest zakres dat w tym zapytaniu).

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi przykładowy trace-id wywołania.

**Comment by emSzmal** [comment]
Dziś dostaje od klienta informację: "Odblokowało się, wszystko działa", ale żadne zmiany w integracji z Allegro nie zostały wprowadzone. Zgłoszenie można zamknąć.
