### ISSUE TITLE
Blokowanie localhosta przez API

### ISSUE THREAD

**Issue by amelinium23** [allegro/allegro-api#5858]
Cześć,

pracuje aktualnie nad aplikacją, która będzie miała integracje z allegro. W tej aplikacji jest mi potrzebna tylko i wyłącznie pobieranie ofert  np. telefonu. W trakcie testów na swoim serwerze (Flask z Pythonem 3.10) napotykam taki problem, że jeden request wychodzi normalnie zwraca mi całą listę kategorii, lecz kolejne dostaje już błąd:
Warto wspomnieć, że dostaje status code: 401, mimo, że mam ważny JWT token, wygenerowany sekundę wcześniej i zapisany w serwerze.
```json
{
    "error": "invalid_token",
    "error_description": "Cannot convert access token to JSON"
}
```

Poszczególne requesty wykonuje za pomocą biblioteki *requests* robię to w następujący sposób:

```python
from requests import get
from typing import Dict, Any

URL = "https://api.allegro.pl/"

DEFAULT_HEADERS = {
    'Accept': 'application/vnd.allegro.public.v1+json',
    'Authorization': '',
    'Content-Type': 'application/vnd.allegro.public.v1+json'
}

def get_categories(access_token: str) -> Dict[str, Any]:
 try:
  headers = _fill_headers_with_token(access_token)
  response = get(URL.rstrip('/') + '/sale/categories', headers=headers)
  return json.loads(response.text)
 except Exception as e:
  return {'error': str(e)}
  
def _fill_headers_with_token(access_token: str, headers: Dict[str, str] = DEFAULT_HEADERS) -> Dict[str, str]:
 headers['Authorization'] += 'Bearer ' + access_token
 return headers
```

Token jest pozyskiwany w ten sposób:
```python
import json

from requests import post
from typing import Dict
from flask import current_app

AUTHORIZATION_ALLEGRO_TOKEN_URL = "https://allegro.pl/auth/oauth/token"

def get_access_token() -> Dict[str, str]:
 token_response: Dict[str, str] = {}
 try:
   data = {'grant_type': 'client_credentials'}
   client_id = current_app.config.get('ALLEGRO_CLIENT_ID', '')
   client_secret = current_app.config.get('ALLEGRO_CLIENT_SECRET', '')
   token_response = post(AUTHORIZATION_ALLEGRO_TOKEN_URL, data=data,
                           allow_redirects=False, auth=(client_id, client_secret))
   token_response: Dict[str, str] = json.loads(token_response.text)
   return token_response
 except Exception:
  return {}
```

Pytanie jest następujące: czym jest spowodowane takie zachowanie? czy jest to spowodowane, że robię requesty za szybko, czy jest blokowany adres 127.0.0.1?

**Comment by hahyes** [comment]
Nie chodzi o "blokowanie localhosta", tylko o to, że API nie może przekonwertować zawartości twojego tokena. Może jest niekompletny, gdzieś go ucina albo go hashujesz/szyfrujesz w jakiś sposób. Musisz to sprawdzić, bo gdzieś tam musi być problem. Upewnij sie, czy na pewno przesyłasz ten token, który otrzymałeś w procesie autoryzacji.

**Comment by amelinium23** [comment]
> Nie chodzi o "blokowanie localhosta", tylko o to, że API nie może przekonwertować zawartości twojego tokena. Może jest niekompletny, gdzieś go ucina albo go hashujesz/szyfrujesz w jakiś sposób. Musisz to sprawdzić, bo gdzieś tam musi być problem. Upewnij sie, czy na pewno przesyłasz ten token, który otrzymałeś w procesie autoryzacji.

Nie wiem jakby to miało działać, bo dostaje odpowiedź z API, i ją zapisuję, więc raczej nie jest to możliwe.

**Comment by amelinium23** [comment]
```python
def _fill_headers_with_token(access_token: str, headers: Dict[str, str] = DEFAULT_HEADERS) -> Dict[str, str]:
 headers['Authorization'] += 'Bearer ' + access_token
 return headers
```
Ta funkcja jest problem ona dodaje cały czas ten sam token do nagłówka, więc mój błąd dzięki za pomoc!
