### ISSUE TITLE
Opóźniony endpoint /order/events 

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#5859]
Mam problem z endpointem /order/events mianowicie większość eventów pojawia się dopiero +/- po 2 godzinach realnego wystąpienia. Czym ten błąd może być spowodowany i czy mogę w jakiś sposób to przyśpieszyć?

**Comment by hahyes** [comment]
> Mam problem z endpointem /order/events mianowicie większość eventów pojawia się dopiero +/- po 2 godzinach realnego wystąpienia. Czym ten błąd może być spowodowany i czy mogę w jakiś sposób to przyśpieszyć?

Czas podany przy eventach to UTC, my jesteśmy +2 godziny w stosunku do UTC ze względu na strefę czasową i czas letni.

**Comment by MaciejFrackowiak** [comment]
Jest dokładnie tak jak napisał @hahyes - opisujemy to w [naszym poradniku](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#data-i-czas).
