### ISSUE TITLE
Parametr niejednoznaczny - nie można wybrać wartości

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#5860]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam,

Problem dotyczy kategorii 3475 ( `Dziecko/Zabawki/Edukacyjne/Instrumenty muzyczne` ).

Sandbox:

`GET /sale/categories/261571/parameters || trace-id:120fe4d3f55cde4c`

Otrzymuję 

```
    "id" => "3475"
    "name" => "Wiek dziecka"
    "type" => "dictionary"
    "required" => true
    "required_for_product" => true
    "unit" => null
    "options" => array:8 [▼
        "variants_allowed" => true
        "variants_equal" => false
        "ambiguous_value_id" => "3475_1078187"
        "depends_on_parameter_id" => null
        "required_depends_on_value_ids" => null
        "display_depends_on_value_ids" => null
        "describes_product" => true
        "custom_values_enabled" => true
      ]
    "restrictions" => array:1 
    "dictionary" => array:29
```

custom_values_enabled włączone + ambiguous_value_id podany 3475_1078187

Przy próbie utworzenia oferty

`POST sale/offers || trace-id:4c3f9159453ad3e2`

Podaję

```
parameters [
[
          "id" => "3475"
          "range_value" => null
          "values" => array:1 [
            0 => "Niemowle"
          ]
          "values_ids" => array:1 [
            0 => "3475_1078187"
          ]
        ]

]
```

I otrzymuję błąd
```[
    "code": "BAD_REQUEST"
    "message": "Custom value cannot be defined when the dictionary value is not an ambiguous one: parameterId=3475"
    "details": null
    "path": ""
    "userMessage": "Aby móc ustawić własną wartość w parametrze 'Wiek dziecka', należy wybrać wartość niejednoznaczną"
]
```

Na produkcji coś podobnego jest - odtworzyłem na sandbox.

Proszę o pomoc.

**Comment by Radeq** [comment]
@MartaNowaczyk , tak, produkcja

`POST sale/offers || trace-id:8b8e7e4f42b99ebb`

**Comment by MartaNowaczyk** [comment]
Dla parametru "Wiek dziecka"(3475) nie powinno być możliwości dodania własnej wartości. Rozumiem, że oznaczenie przez `"customValuesEnabled": true` jest mylące, dlatego zgłosiłam to do odpowiedniego zespołu. Tak czy inaczej, wartość „3 +”, którą widzę w twoim wywołaniu powinna być wybrana ze słownika jako "3 lata +" (3475_45), a ta z przykładu sandbox zamiast "Niemowle" powinno być "0 +"(3475_1).
W tej chwili dla parametru "id": "3475" proszę wybrać wartość z dostępnej listy.

**Comment by Radeq** [comment]
@MartaNowaczyk od strony językowej również jest to dla mnie zrozumiałe (3+ => 3 lata + | niemowle => 0 +) ale skoro sprzedawca widzi, że może wpisać własną wartość to ją wpisuje a system to umożliwia.

Tak, oznaczenie `"customValuesEnabled": true` jest mylące. Rozumiem, że to przeoczenie i zostanie poprawione na false?

**Comment by MartaNowaczyk** [comment]
Rozumiem. Pracujemy nad zmianą tego. Jest to bardziej złożona kwestia niż mogłoby się wydawać, także potrwa to na pewno dłużej niż kilka dni.  Przepraszamy za te nieścisłości.
