### ISSUE TITLE
[Bugs&Errors] Zrypany system walidacji w powiązaniu z ProDUPtyzacją... STOP!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#5862]
Jakim cudem REST odpowiada losowymi zestawami wartości dla parametrów słownikowych?? Już dawno porzuciliśmy tymczasowe zapisy stanu parametrów dla każdej z kategorii (na potrzeby optymalizacji zapytań), ale to co się ostatnio dzieje - to jakiś KOSZMAR!! Odpytywanie zasobu (/sale/categories/{CatID}/parameters) podającego stan parametrów potrafi przez wiele godzin zwracać różne wyniki - proszę się tam nie tłumaczyć "rozległością systemu", guzik nas to obchodzi... Potem dochodzi do absurdów jak niżej:

[UPL&GET(Params)]:
VALIDATION_ERROR / Missing required parameters: 248920 / Uzupełnij parametry obowiązkowe: Marka.
[MOD(Params)&UPL]:
VALIDATION_ERROR / Assigned valueId  for dictionary parameter 248920 is not found. / Przydzielony identyfikator wartości  nie został znaleziony dla parametru słownikowego 248920.
VALIDATION_ERROR / Parameter value does not exist (248920) / Podana wartość parametru Marka (248920) nie istnieje w słowniku.
VALIDATION_ERROR / No shipping rates assigned to offer. / Brak ustawionego cennika dostaw.

Jak widać powyżej, nagle plujecie dodatkowo błędem cennika dostaw, co jest zupełną aberracją, bo wysyłany cennik jest TEN SAM. Jak by tego było jeszcze mało, to znamy inny paradoks - kiedy dochodzi do zgrania wartości parametru oczekiwanego dla Produktu, a po drodze wartość parametru "przeskoczyła" z proponowanej do katalogu słownika, to powstaje BLOKADA EDYCJI, której nie można inaczej rozwiązać jak poprzez całkowite wykopanie Produktu z oferty... Oby tak dalej!!

**Comment by MaciejFrackowiak** [comment]
Proszę wskaż konkretne przykłady takich sytuacji, najlepiej podając trace-id wywołań.

**Comment by FromAnyHole** [comment]
@MaciejFrackowiak - właśnie lecimy w tę przepaść, super:
https://github.com/allegro/allegro-api/issues/5874

**Comment by hahyes** [comment]
@FromAnyHole Póki co tylko ty gdzieś odlatujesz. Idź na Gadane się pieklić a nie robisz tutaj burdel.

**Comment by FromAnyHole** [comment]
@hahyes - lepiej milcz dzieciaku nie pytany, bo niedawno dałeś już popis. Jak przez 15 lat patrzymy co tu się wyprawia, także na poprzednich forach API, dawno takich bredni tu nikt nie pisał. Jakieś katastroficzne wizje dot. "pola ostrzeżeń w walidacji" - CAŁY SYSTEM SIĘ WYWALI i poniosą tam WIELKIE STRATY!! Ale brednie... ŁuBuDuBu, ŁuBuDuBu ;-) A to tylko badanie kilku cyferek Prefix'u GTIN, gdzie i tak system walidacji podał by to (w ostrzeżeniu) dopiero przy edycji lub kreowaniu nowej oferty, żenada.

**Comment by hahyes** [comment]
@FromAnyHole Dałem popis wiedzy i doświadczenia, którego nie masz ani za grosz. 15 lat patrzycie i żadnych wniosków, tylko darcie japy i pieniactwo. Takie brednie niby napisałem a nie umiesz podać jednego argumentu przeciwko napisanym przeze mnie wnioskom. Tylko "moja racja jest mojsza". Rzeczywiście, twoje zachowanie to żenada. Nie umiesz ogarnąć na sandboxie testów walidacji? Zrobiłem apkę testującą to w parę godzin. A wy z 15 lat doświadczenia ujadacie na forum do zgłaszania błędów, że aż uszy więdną. A i Allegro niby straty poniesie, najlepszy żart tego tygodnia :D
