### ISSUE TITLE
Jak wystawic zaplanowaną aukcje w przyszlosci?

### ISSUE THREAD

**Issue by niksfirefly** [allegro/allegro-api#5864]
Uzywam 
`
"publication" => {
          "status" => "INACTIVE",
          "duration" => "P10D",
          "republish" => true,
          "startingAt" => _data_za_25_dni,
        },
`
niestety w efekcie otrzymuje jedynie szkic a nie zaplanowana w przyszlosci aukcje

**Comment by FromAnyHole** [comment]
@niksfirefly - a co widać po odpytaniu tej "zaplanowanej" oferty wg jej ID??

**Comment by MaciejFrackowiak** [comment]
Aby zaplanować wystawienie oferty w przyszłości skorzystaj z [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) i w polu "publication.scheduleFor" wskaż datę i godzinę wystawienia oferty w przyszłości. Zaplanowane oferty - ich listę znajdziesz przy wykorzystaniu [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) i filtra "publication.status" z wartością "ACTIVATING".

**Comment by niksfirefly** [comment]
Czyli nie ma bezposredniej opcji sklonowania aukcji - tylko najpierw trzeba zrobic szkic na ktorym dopiero wykonujemy akcje z scheduledFor ? Tak?

**Comment by MaciejFrackowiak** [comment]
Dokładnie tak. Najpierw musi powstać szkic, który następnie aktywujesz i tu ewentualnie podajesz termin pojawienia się oferty w serwisie w polu "scheduledFor".
