### ISSUE TITLE
Wysyłam z Allegro - podjazd kuriera a kilka kont Allegro

### ISSUE THREAD

**Issue by arolznov** [allegro/allegro-api#5865]
Dzień dobry

Czy za pomocą PUT /parcel-management/parcel-pickup-request-commands/{commandId} można zamówić **JEDEN** odbiór paczek przez danego kuriera dla paczek (parcelIds) stworzonych na rożnych kontach allegro?

Dla przykładu:
konto allegro o loginie A wygenerowało paczki DPD o parcelId 1, 2, 3
konto allegro o loginie B wygenerowało paczki DPD o parcelId 4, 5
konto allegro o loginie C wygenerowało paczkę DPD o parcelId 6

Czy mogę wysłać jedno żądanie parcel-pickup-request-commands z parcelIds: 1,2,3,4,5,6 tak żeby nie generować kosztów związanych z podjazdem kuriera?

**Comment by MaciejFrackowiak** [comment]
Nie, nie można w jednym zleceniu przekazać paczek z różnych kont.

**Comment by arolznov** [comment]
Myślę, że jest to do poprawienia. Sprzedawcy będą płacić kilkukrotnie za podjazd tego samego kuriera, a kurierzy będą dostawać kilka zleceń odbioru w to samo miejsce.

**Comment by MaciejFrackowiak** [comment]
@arolznov Alternatywnym rozwiązaniem jest model przedstawiony przez @hahyes - składasz zlecenie dla paczek z jednego konta, a kurier odbiera pozostałe przesyłki również. Oczywiście to kwestia już "dogadania się" z kurierem.

**Comment by arolznov** [comment]
Skoro nie ma lepszego rozwiązania to tak zrobimy. Zobaczymy jak to wyjdzie w praktyce.
