### ISSUE TITLE
Oznaczenie parametru 2

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#5867]
Podczas wystawienia pojawił się bład;

Process Item Error. Error Message: Warning: explode() expects parameter 2 to be string, array given in /var/www/html/app/code/Fwc/Allegro/Model/AuctionScheduler.php on line 561
co oznacz parametr 2?

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się proszę w takim razie ze wsparciem aplikacji, której używasz. Błąd w takiej formie niestety zupełnie nic nam nie mówi, ponieważ nie pochodzi od nas.

**Comment by pzareba86** [comment]
Ok, dziękuję.

***@***.***

Patrycja Zaręba
Sales Coordinator

#jestem4F<https://4f.com.pl/jestem4f>

email: ***@***.******@***.***>
fax: +48 12 3120 239
mobile: +48724750784
OTCF S.A.
75-412 Koszalin, ul. Monte Cassino 6, Poland

***@***.***

Sponsor of 8 Olympic Committees: Poland, Croatia, Lithuania, Latvia, Portugal, Greece, Slovakia and Serbia
Presenting Sponsor of the Four Hills Tournament 2018-2020, Global Partner of the Wings for Life World Run 2020
________________________________
OTCF S.A. z siedzibą w Wieliczce przy ul. Grottgera 30, 32-020 Wieliczka, wpisana do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy dla Krakowa – Śródmieścia w Krakowie, XII Wydział Gospodarczy Krajowego Rejestru  Sądowego pod nr KRS: 0000555276, kapitał zakładowy w wysokości: 7 384 500,00 zł opłacony w całości, NIP: 9451978451, REGON: 356630870, o numerze rejestrowym BDO: 000005025. Ta wiadomość i jej treść mogą zawierać informacje poufne lub zastrzeżone, przeznaczone tylko dla adresata wiadomości. Takie informacje są objęte zakazem ich ujawniania. Wszelkie rozprowadzanie, dystrybucja lub powielanie niniejszej wiadomości lub innego rodzaju wykorzystanie przez osobę lub podmiot nie będący jego adresatem, jest zabronione. Jeżeli otrzymałeś tę wiadomość omyłkowo, proszę bezzwłocznie zawiadomić nadawcę wysyłając odpowiedź na niniejszą wiadomość i usunąć ją z poczty. Dziękuję.
OTCF S.A.  with its registered seat in Wieliczka, ul. Grottgera 30, 32-020 Wieliczka, Poland, registered in the entrepreneurs’ register kept by the District Court for Kraków - Śródmieście District in Krakow, 12th Commercial Department of the National Court Register, entry no KRS 0000555276, its share capital of PLN 7 384 500.00 paid in full, Tax ID No.(NIP) : 9451978451, Business Statistical Number (Regon): 356630870, BDO: 000005025. This e-mail and its content might contain confidental or privileged information intended solely fo the use of the addressee. Such information are protected from disclosure. You are hereby notified that any dissemination, distribution or copying or other use of this e-mail by person or entity other than the intended recipient is strictly prohibited.  If you have received this communication in error, please notify the sender immediately by replying to the message and deleting it from your computer. Thank you.

From: PrzemyslawLukanowski ***@***.***>
Sent: Friday, July 8, 2022 3:35 PM
To: allegro/allegro-api ***@***.***>
Cc: Patrycja Zaręba ***@***.***>; Author ***@***.***>
Subject: [Marketing Mail] Re: [allegro/allegro-api] Oznaczenie parametru 2 (Issue #5867)

CAUTION: Ten email pochodzi spoza OTCF. Uważaj na zamieszczone załączniki oraz linki. Podejrzane wiadomości zgłoś na ***@***.******@***.***>

Skontaktuj się proszę w takim razie ze wsparciem aplikacji, której używasz. Błąd w takiej formie niestety zupełnie nic nam nie mówi, ponieważ nie pochodzi od nas.

**Comment by FromAnyHole** [comment]
@pzareba86 - Pani Patrycjo, wynika dość prosto z tego błędu, że ktoś pisząc jakieś funkcje czy obiekty w PHP, nie przewidział (dla natywnej funkcji explode();) możliwości przekazania innego typu zmiennej niż STRING. Przekazanie zapisu tablicowego (zgaduję z parametrów oferty) musi to wysypać, czyli wszystko się zgadza. Czeba do autora siem zgłosić ;-)
