### ISSUE TITLE
Problem z wgrywaniem zdjęć via API

### ISSUE THREAD

**Issue by xVinniVx** [allegro/allegro-api#5869]
Przy wielu produktach pojawia się problem wgrywania zdjęć via API. 
Przykładowy komunikat zwrotny:

Treść komunikatu zwrotnego z serwerów Allegro:

Nie można pobrać zdjęcia z adresu 'https://lombard66.pl/uploads/produkty/p_440805_20220709-111853-1657358333.jpeg'. 
Serwer ze zdjęciem zwrócił kod HTTP: 503 SERVICE_UNAVAILABLE z błędem: '{"destination":{"originalDst":null,"path":"/get?url=https%3A%2F%2Flombard66.pl%2Fuploads%2Fprodukty%2Fp_440805_20220709-111853-1657358333.jpeg&max_size=26214400","serviceTag":null,"host":"public-downloader"},"details":{"connectionId":10121701},"message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","code":"UF,URX"} '.

Co najdziwniejsze - zdjęcia są na pewno wgrane poprawnie na serwer. Wyświetlają się na stronie Sklepu.

Wklejając powyższy link: https://lombard66.pl/uploads/produkty/p_440805_20220709-111853-1657358333.jpeg jasno wydać, że zdjęcie istnieje. 

Co może być przyczyną błędu?

**Comment by mskiba03** [comment]
Właśnie wszedłem na forum, żeby to samo zgłosić ;)

U mnie:
DownloadError.ServiceUnavailable - Downloading image from URL 'ADRES_OBRAZKA.jpg' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: '{"destination":{"originalDst":null,"path":"/get?url=ADRES_OBRAZKA.jpg&max_size=26214400","serviceTag":null,"host":"public-downloader"},"details":{"connectionId":10480590},"message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","code":"UF,URX"}
'. - productSet[0].product.images

**Comment by mskiba03** [comment]
Hallo Allegro? Problem, jest irytujący, można prosić o jego interpretacje?

**Comment by MaciejFrackowiak** [comment]
@xVinniVx @mskiba03 Proszę podajcie przykładowe trace-id wywołań, wówczas będę mógł sprawdzić nasze logi.

**Comment by mateuszbieniascontelizer** [comment]
podbijam

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Podobnie jak u poprzedników proszę o przykładowe trace-id wywołania.

**Comment by mateuszbieniascontelizer** [comment]
trace-id: 4cff249641dda49a
- DownloadError.ServiceUnavailable - Downloading image from URL 'https://storage.waw.cloud.ovh.net/v1/AUTH_57db3a7ead234cb5afc4eec99f55117c/raw_images/f8a5de0d06d29517594381beb4ab86e4.jpg' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: '{"details":{"connectionId":11526138},"code":"UF,URX","message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","destination":{"path":"/get?url=https%3A%2F%2Fstorage.waw.cloud.ovh.net%2Fv1%2FAUTH_57db3a7ead234cb5afc4eec99f55117c%2Fraw_images%2Ff8a5de0d06d29517594381beb4ab86e4.jpg&max_size=26214400","serviceTag":null,"host":"public-downloader","originalDst":null}}

**Comment by mateuszbieniascontelizer** [comment]
trace-id: 5f6257914aed53e8
- DownloadError.ServiceUnavailable - Downloading image from URL 'https://storage.waw.cloud.ovh.net/v1/AUTH_57db3a7ead234cb5afc4eec99f55117c/clients_images/ef1729fa94032904763e8ac0f9aec31e.jpg' failed. Server returned the following HTTP status code: 503 SERVICE_UNAVAILABLE and response body: '{"message":"upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111","destination":{"serviceTag":null,"originalDst":null,"host":"public-downloader","path":"/get?url=https%3A%2F%2Fstorage.waw.cloud.ovh.net%2Fv1%2FAUTH_57db3a7ead234cb5afc4eec99f55117c%2Fclients_images%2Fef1729fa94032904763e8ac0f9aec31e.jpg&max_size=26214400"},"details":{"connectionId":11508625},"code":"UF,URX"}
'.

**Comment by mateuszbieniascontelizer** [comment]
@MaciejFrackowiak u wszystkich naszych klientów jest tak samo

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Weryfikuje sprawę z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer @xVinniVx @mskiba03 Problem nie powinien już występować. Przepraszam za niedogodności.

**Comment by mateuszbieniascontelizer** [comment]
@MaciejFrackowiak a czy mógłbym tak z czystej programistycznej ciekawości wiedzieć co tam się działo?

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Dyplomatycznie odpowiem - problem z konfiguracją jednej z naszych usług.

**Comment by mateuszbieniascontelizer** [comment]
jak juz tak sobie fajnie gadamy to jeszcze czasem mam coś takiego
trace-id: 10c572353dbaaadc
- INTERNAL_SERVER_ERROR - Internal server error. Please try again in a few minutes.

**Comment by MaciejFrackowiak** [comment]
@mateuszbieniascontelizer Tu akurat chwilowo mieliśmy problem z pobraniem jednego ze zdjęć.
