### ISSUE TITLE
itEndingTime return 0

### ISSUE THREAD

**Issue by rpicheta** [allegro/allegro-api#587]
Podczas odpytywania się webApi odnośnie aukcji, która jest aktywna, zwracana odpowiedź parametru 
`itEndingTime` zwraca mi int(0).
Wg dokumentacji jest to `Czas zakończenia oferty (w formacie Unix time).`
Przykładowe aukcja: 7151457538

Dlaczego zwraca 0?

**Comment by imper86** [comment]
@rpicheta z tego co pamiętam, to ten parametr będzie uzupelniony dopiero jak aukcja się zakończy (deaktywuje)

**Comment by MaciejPotepa** [comment]
@rpicheta jest dokładnie tak jak @imper86 pisze.

Dzięk @imper86!

**Comment by rpicheta** [comment]
@imper86 dzięki! Sądziłem, że to parametr, który wskazuje czas do zakończenia oferty.
