### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by Glocom-Global** [allegro/allegro-api#5872]
There is not much information available on how to handle description via API. We want to know what html tags are allowed.

We once we received this response Invalid \ "html \" tag, allowed: {h1, h2, p, ul, ol}

But not p tag is throwing error. Please provide clarity and also examples

**Comment by MaciejFrackowiak** [comment]
You can find all the necessary information in [our tutorial](https://developer.allegro.pl/tutorials/listing-offers-4RAvLdaqMf8#offer-description).
