### ISSUE TITLE
Oferty stają się aktywne same z siebie

### ISSUE THREAD

**Issue by Vlad-Katsubo** [allegro/allegro-api#5873]
Dzień dobry, ostatnio kontaktowałem się z supportem w sprawie automatycznego dołączania części ofert.

Oferty z SKU zawierającym identyfikator "BTO" były z jakiegoś powodu automatycznie włączane.

Powiedziano mi, że odbywa się to za pośrednictwem interfejsu API. Dzisiaj usunąłem połączenie Baselinker -> Allegro z podłączonych aplikacji i wyłączyłem te oferty.

Po jakimś czasie nadal włączały się automatycznie...
Proszę o pomoc w ustaleniu, co dokładnie włącza te oferty za każdym razem? Od prawie tygodnia nie mogę się od nich uwolnić.

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Proszę podaj id przykładowej oferty, która ponownie stała się aktywna.

**Comment by Vlad-Katsubo** [comment]
Przepraszam.

[Green Cell HR20/D 8000mAh B2](https://allegro.pl/oferta/12324580415)
nr: 12324580415
sygnatura: BTO_FS_10428
EAN: 5907813963032

**Comment by MaciejFrackowiak** [comment]
Oferta została aktywowana przez aplikację IAI.

**Comment by Vlad-Katsubo** [comment]
Dziękuję za szybką reakcję. Myślałem, że będę czekał tydzień na odpowiedź.
