### ISSUE TITLE
Brak możliwości wystawienia produktu

### ISSUE THREAD

**Issue by Bober95** [allegro/allegro-api#5874]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Próbuję wystawić ofertę na podstawie produktu - 14539c95-ff9d-413a-ac9f-dce3cb4b0fdf
I otrzymuję komunikat:

`[Wskazany produkt istnieje. Przesłany parametr `Producent` o wartości `Silentium PC(232509_367581)` nie pasuje do parametru produktu `inny(232509_367657)`.,
The provided parameter 'Producent'(232509) value (Silentium PC(232509_367581)) does not match the existing parameter value (inny(232509_367657)),
]`
TraceID: c08c138f0707dee0

I tutaj jak rozumiem po ostatnich zmianach jest to komunikat o tym że parametr w ofercie nie jest zgodny z tym produktem
Więc zmieniam go (na taki jak podany w produkcie) i próbuję ponownie wystawić ofertę lecz tym razem otrzymuję komunikat: 

`[Wartość 'Silentium PC' występuje w parametrze 'Producent',
Value already exists: value='Silentium PC', parameter.id='232509',
]`
TraceID: 756a41fa0ae95355

**Comment by MaciejFrackowiak** [comment]
W tym konkretnym przypadku obecnie produkt ma przypisany parametr Producent jako "inny (SilentiumPC)" z id=232509_367657. W międzyczasie dla kategorii 260029 i parametru Producent przypisano wartość "Silentium PC" z id=232509_367581 (już bez przedrostka inny). Chcąc wystawić ofertę dochodzi do konfliktu pomiędzy identyfikatorami parametru Producent. Aby rozwiązać ten problem zgłoś proszę sugestię zmiany w produkcie - możesz to zrobić poprzez API ([POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation/#operation/productChangeProposal)) lub stronę WWW (https://allegro.pl/moje-allegro/sprzedaz/zglos-blad-w-produkcie/{productId}).

**Comment by MaciejFrackowiak** [comment]
@hahyes @Bober95 Zdaję sobie sprawę, iż nie jest to komfortowe rozwiązanie. W Allegro prowadzony jest cykliczny proces uspójniania parametrów produktów, jednak wymaga to zarówno czasu, jak i mocy przerobowych, aby każdy jeden produkt zaktualizować. W API de facto jesteśmy tylko pośrednikiem w korzystaniu z Katalogu produktów. Swoje uwagi i pomysły możecie przekazać bezpośrednio poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1) - informacje te trafią bezpośrednio do osób odpowiedzialnych za działanie bazy produktowej.

**Comment by FromAnyHole** [comment]
Tak tylko z troski o ten Szpital - wracałem korytarzem i widzę na sali obok, że jakiś pacjent miota się tam i już chyba piąty raz "siebie edytuje" - jakiś lekarz już został wezwany??

**Comment by FromAnyHole** [comment]
Tak tylko z troski o ten Szpital - wracałem korytarzem i widzę na sali obok, że jakiś pacjent miota się tam i już chyba piąty raz "siebie edytuje" - jakiś lekarz został już wezwany??
