### ISSUE TITLE
Kategoria nie jest lisciem?

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5875]
Przy próbie wystawiania otrzymałam taki komunikat
Nie można utworzyć produktu - kategoria \"306861\" nie jest liściem"
Co to oznacza?

**Comment by AureliuszBrussy** [comment]
Kategoria liść, to taka kategoria, która nie ma żadnych kategorii podrzędnych. 

Informację o tym, czy kategoria jest liściem uzyskasz dzięki [GET /sale/categories](https://developer.allegro.pl/documentation#tag/Categories-and-parameters) - wartość **true** w polu "**leaf**".

**Comment by Zbigi** [comment]
Czy to znaczy, że w kategoriach, które nie są liściem, nie można wystawiać?

**Comment by AureliuszBrussy** [comment]
Dokładnie tak. Tak jak informujemy w komunikacie błędu, możesz utworzyć oferty tylko w kategoriach, które są liśćmi drzewa kategorii.

**Comment by Zbigi** [comment]
A jak nie ma podobnej, to gdzie mam wystawiać?
