### ISSUE TITLE
Zarządzanie images

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5877]
Jakiś czas temu a pytanie jak zarządzać grafikami otrzymałem odpowiedź, że to załatwia Państwa system.
Niestety chyba jednak tak nie jest. Gdy zmieniam grafiki i wtedy chwilowe mam więcej niż 16 grafik, otrzymuje
taki błąd.
Opis zawiera zdjęcia spoza galerii: https://a.allegroimg.com/original/11e5a3/ff7bb3964e7db9ddc7bff9d1d39b,https://a.allegroimg.com/original/11e5a3/ff7bb3964e7db9ddc7bff9d1d39b,https://a.allegroimg.com/original/11758e/4e9554b34201ade41f5a394f4868,https://a.allegroimg.com/original/117652/d74393a14459851c97f4b114cb81,https://a.allegroimg.com/original/113ce4/20a557a846e08b8a5630abbe0624,https://a.allegroimg.com/original/11e589/9f805b284f969c0b666d92a64fdf,https://a.allegroimg.com/original/112e2a/cdfef1a742449c20370cc089bcc7,https://a.allegroimg.com/original/11035e/80a185674607986ebf2d800a4942,https://a.allegroimg.com/original/1130e1/b010b979496688a82036ffbeb51d,https://a.allegroimg.com/original/11d9b6/321f53a5445cb64b5a575ebb56ee,https://a.allegroimg.com/original/11e413/635c408347cbb00296394f358464,https://a.allegroimg.com/original/119a2d/e8418c4d4238b7e65873d4b91464,https://a.allegroimg.com/original/1133db/5d2a965e4af7a80f2b7ad4c6f045,https://a.allegroimg.com/original/110fe1/0477982e410bb6963ee60e94b07e.

jak się zatem pozbyć starych grafik?
Blokuje to jakąkolwiek zmianę w aukcji (także ceny)

**Comment by AureliuszBrussy** [comment]
Możesz wyjaśnić co "załatwia nasz system"? 

Zgodnie z komunikatem - powinieneś pozbyć się z "**description**" (opisu) zdjęć, których nie ma w galerii oferty (pole "**images**"). Edytuj opis oferty.

**Comment by Zbigi** [comment]
A jak się ich pozbyć? Mam powiedzmy 10 grafik i chce wszystkie zmienić. Wgrywam następne 10 i nowy opis no i..... nie mogę tego zrobić, ponieważ otrzymuje error jak wyżej.

**Comment by AureliuszBrussy** [comment]
Jeżeli edytujesz w jednym requeście tablicę ze zdjęciami oraz opis oferty (tak, aby korzystać w nim tylko z tych nowych zdjęć) - request powinien zakończyć się powodzeniem. Podaj proszę trace-id przykładowego wywołania - sprawdzę to dokładniej.

**Comment by AureliuszBrussy** [comment]
Sprawdziłem logi - w swoim ostatnim requeście dla tej oferty aktualizujesz tylko cenę - tak jak wspomniałem, powinieneś aktualizować opis oferty ("**description**"), tak, aby zawierał tylko zdjęcia będą w galerii ("**images**").

**Comment by Zbigi** [comment]
Znalazłem na czym polegał błąd u Państwa REST APi. 
Zgodnie z dokumentacją chciałem wystawiać produkt w jednym kroku niestety zawsze wyrzucało błąd, że użyłem grafiki spoza biblioteki. Rozdzieliłem to na dwa kroki. W pierwszym wystawiam produkt z jedną grafiką  w następnie poprzez Patch dodaje opis, grafiki oraz aktywuje ofertę.  I teraz już nie ma tego błędu. Otrzymuje status oferty "LISTED" (nie znalazłem nic na ten temat w dokumentacji) i zakładam, że oznacza to, że oferta jest aktywna "ACTIVE" .
Grafiki nie są od razu dostępne (dostaje link z location) i wtedy taka grafiki nie jest widziana przez system.

**Comment by AureliuszBrussy** [comment]
@Zbigi przekaż mi proszę przykładowy trace-id lub cały request (w formie curl), który kończy się wspomnianym błędem. Chodzi tutaj o ten przypadek, gdzie - zgodnie z dokumentacją - chciałeś wystawiać produkt w jednym kroku, ale wyrzuciło Ci błąd, że użyłeś grafiki spoza biblioteki.

**Comment by Zbigi** [comment]
Niestety nie mam już tej aukcji, została wystawiona

**Comment by AureliuszBrussy** [comment]
@Zbigi aby to dokładnie sprawdzić - potrzebowałbym przykładu. Jeżeli napotkasz jeszcze podobną sytuację w przyszłości, prześlij przykładowe trace-id.
