### ISSUE TITLE
Dodatkowe kategorie do produktu

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#5879]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze spójnością z panelem

:beetle: **Opis / Description**

Produkt w Państwa katalogu: `f18fb6e7-e1a7-4479-86c6-91867d09e4e4`
Dopuszczalne kategorie, które zwraca API: `79456` (czyli Książki i Komiksy / Książki naukowe i popularnonaukowe / Pozostałe).
Klucz `similar` jest pusty.

Prowizja na kategorii "Pozostałe" jest dość duża, dlatego chcemy przejść do innych, dokładniejszych kategorii.

Z całkiem niezłą sprzedażą (aukcja: 12189287244) ktoś to ma w kategorii 79477 (czyli Książki i Komiksy / Książki naukowe i popularnonaukowe / Sztuka, kultura i etnologia), lecz widać że nie ma produktu przypisanego: https://allegro.pl/produkt/liczby-nie-klamia-vaclav-smil-f18fb6e7-e1a7-4479-86c6-91867d09e4e4?order=p (tutaj tej aukcji brak).

Wchodzę więc na formularz:

https://allegro.pl/moje-allegro/sprzedaz/zglos-blad-w-produkcie/f18fb6e7-e1a7-4479-86c6-91867d09e4e4

Blok zmiany wyglada tak:

```
Kategoria produktu
Pozostałe Nr kategorii: 79456
Kultura i rozrywka - Książki i Komiksy - Książki naukowe i popularnonaukowe
```

Wybieram "Zaproponuj zmianę kategorii"

Wpisuje ID: 79477, zatwierdzam.

I nagle pojawia mi się:

```
Kategoria produktu
PozostałeNr kategorii: 79456
Kultura i rozrywka - Książki i Komiksy - Książki naukowe i popularnonaukowe

Możesz wystawić ten produkt również w 10 innych kategoriach
Pokaż wszystkie kategorie wystawiania

zmieniasz na:
Sztuka, kultura i etnologiaNr kategorii: 79477
Kultura i rozrywka - Książki i Komiksy - Książki naukowe i popularnonaukowe
```

To `Możesz wystawić ten produkt również w 10 innych kategoriach` - skąd? W API jak pytam o ten produkt mam tylko jedną kategorię.

O co chodzi?

**Comment by MaciejFrackowiak** [comment]
Potwierdzam, że w API jedyną kategorią dla wskazanego produktu jest kategoria o id=79456. Formularz zgłaszania sugestii via WWW to element, na którego działanie nie mamy żadnego wpływu, dlatego proszę zgłoś swoją uwagę poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
