### ISSUE TITLE
[REST] offers/listing - searchMode=CLOSED

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#588]
Wznowiłem dwie zakończone wcześniej aukcje i mam je teraz na liście aktywnych jak i zakończonych. Czy znikną one z listy zakończonych, jeżeli tak to po jakim czasie się to dzieje?

**Comment by MaciejPotepa** [comment]
Oferty przenosimy automatycznie do archiwum po upływie 60 dni.

**Comment by Rnapzsih** [comment]
NI o to chodzi.... Wznowiłem ofertę a ona był przez przynajmniej godzinę widoczna zarówno na liście aktywnych jak i zakończonych. Pytanie jest dlaczego wznowiona oferta była widoczna w zakończonych...

**Comment by MaciejPotepa** [comment]
Zmiany w ofertach mogą zachodzić nawet do 60 minut, czasami może się zdarzyć, że to potrwa trochę dłużej - z różnych przyczyn. 

Czy statusy wyświetlają się poprawnie w obecnym momencie?

**Comment by Rnapzsih** [comment]
Robiłem to wczoraj wieczorem, rano już było ok. Dzięki za informacje.
