### ISSUE TITLE
Duplikaty zdarzeń CATEGORY_CREATED w event logu

### ISSUE THREAD

**Issue by pgasidlo** [allegro/allegro-api#5883]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Analizując wynik wywołania https://developer.allegro.pl/documentation#operation/getCategoryEventsUsingGET_1 znajduje duplikaty zdarzeń tworzących kategorie, to przykład:

```
{"id": "1657145700000067442", "type": "CATEGORY_CREATED", "category": {"id": "322029", "leaf": true, "name": "Odgrywanie ról", "parent": {"id": "11821"}}, "occurredAt": "2022-07-06T22:15:00Z"}
{"id": "1657146480635067442", "type": "CATEGORY_CREATED", "category": {"id": "322029", "leaf": true, "name": "Odgrywanie ról", "parent": {"id": "11821"}}, "occurredAt": "2022-07-06T22:28:00.635Z"}
{"id": "1657148400000651415", "type": "CATEGORY_CREATED", "category": {"id": "322030", "leaf": true, "name": "Figurki", "parent": {"id": "11818"}}, "occurredAt": "2022-07-06T23:00:00Z"}
{"id": "1657150980335651415", "type": "CATEGORY_CREATED", "category": {"id": "322030", "leaf": true, "name": "Figurki", "parent": {"id": "11818"}}, "occurredAt": "2022-07-06T23:43:00.335Z"}
{"id": "1657155600000962113", "type": "CATEGORY_CREATED", "category": {"id": "322031", "leaf": true, "name": "Pojazdy dla lalek", "parent": {"id": "11825"}}, "occurredAt": "2022-07-07T01:00:00Z"}
{"id": "1657156260175962113", "type": "CATEGORY_CREATED", "category": {"id": "322031", "leaf": true, "name": "Pojazdy dla lalek", "parent": {"id": "11825"}}, "occurredAt": "2022-07-07T01:11:00.175Z"}
{"id": "1657578600000478387", "type": "CATEGORY_CREATED", "category": {"id": "322039", "leaf": true, "name": "Zwierzątka", "parent": {"id": "11837"}}, "occurredAt": "2022-07-11T22:30:00Z"}
{"id": "1657583460386478387", "type": "CATEGORY_CREATED", "category": {"id": "322039", "leaf": true, "name": "Zwierzątka", "parent": {"id": "11837"}}, "occurredAt": "2022-07-11T23:51:00.386Z"}
```

Brak pomiędzy zdarzenia kasowania tego ID, co by było logiczne.

Próbuje skrzętnie analizować całego journala (inne zdarzenia też), aby nic nie przegapić. Ale ten drugi CREATE skutecznie wyrzuca wyjątek, że kategoria o tym ID już istnieje.

**Comment by MartaNowaczyk** [comment]
Sprawdzam opisany przypadek, jak tylko coś ustalę dam znać.

**Comment by pgasidlo** [comment]
Jakiś postęp, dzisiaj patrze a tu taki potworek:
```
{"id": "1658095800000247761", "type": "CATEGORY_CREATED", "category": {"id": "322050", "leaf": true, "name": "Wiertarki", "parent": {"id": "322020"}}, "occurredAt": "2022-07-17T22:10:00Z"}
{"id": "1658095864006247761", "type": "CATEGORY_CREATED", "category": {"id": "322050", "leaf": true, "name": "Wiertarki", "parent": {"id": "322020"}}, "occurredAt": "2022-07-17T22:11:04.006Z"}
{"id": "1658096400000247761", "type": "CATEGORY_CREATED", "category": {"id": "322050", "leaf": true, "name": "Wiertarki", "parent": {"id": "322020"}}, "occurredAt": "2022-07-17T22:20:00Z"}
{"id": "1658097300000247761", "type": "CATEGORY_CREATED", "category": {"id": "322050", "leaf": true, "name": "Wiertarki", "parent": {"id": "322020"}}, "occurredAt": "2022-07-17T22:35:00Z"}
{"id": "1658097840000247761", "type": "CATEGORY_CREATED", "category": {"id": "322050", "leaf": true, "name": "Wiertarki", "parent": {"id": "322020"}}, "occurredAt": "2022-07-17T22:44:00Z"}

**Comment by pgasidlo** [comment]
Albo takie kombo:
```
{"id": "1658107920000114956", "type": "CATEGORY_DELETED", "category": {"id": "259597", "leaf": true, "name": "Polerki elektryczne", "parent": {"id": "259588"}}, "occurredAt": "2022-07-18T01:32:00Z", "redirectCategory": {"id": "322021"}}
| {"id": "1658107920000806976", "type": "CATEGORY_CREATED", "category": {"id": "322021", "leaf": true, "name": "Polerki", "parent": {"id": "18554"}}, "occurredAt": "2022-07-18T01:32:00Z"}
| {"id": "1658107980181806976", "type": "CATEGORY_CREATED", "category": {"id": "322021", "leaf": true, "name": "Polerki", "parent": {"id": "18554"}}, "occurredAt": "2022-07-18T01:33:00.181Z"}
| {"id": "1658108400000323258", "type": "CATEGORY_CREATED", "category": {"id": "322022", "leaf": true, "name": "Klucze udarowe", "parent": {"id": "18554"}}, "occurredAt": "2022-07-18T01:40:00Z"}
```
Kasowana jest kategoria. Jako ID, do której przepiąć aukcje jest podawana kategoria, która dopiero w kolejnym evencie zostanie utworzona.

Niby czasowo OK: w tej samej chwili (baza nie oferuje nic mniejszego od sekundy?), ale w logu powinno to być ID kolejno - a tak nie jest.

Jakim algorytmem jest generowane to ID:
```
1658107920000114956
1658107920000806976
```
Prefiks ten sam (1658107920) - mam to brać jako transakcję?

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady, weryfikuję tę sytuację, wrócę z informacją.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za tę sugestię. Jeżeli zdecydujemy się wprowadzić nowy rodzaj zdarzenia, na pewno poinformujemy o tym na [naszej stronie](https://developer.allegro.pl/news) oraz na forum.

**Comment by PrzemyslawLukanowski** [comment]
@pgasidlo Czy aktualnie nadal natrafiasz na duplikaty zdarzeń? Jeśli tak, poproszę o nowy przykład + trace id tego wywołania lub dokładna data i czas, kiedy je wykonałeś.

**Comment by PrzemyslawLukanowski** [comment]
Zespół odpowiedzialny za usługę zweryfikował tę sytuację, zatem wracam z odpowiedzią. Jak rozumiem duplikatów nie widzisz na raz, w tym samym żądaniu, ale po jakimś czasie. To jest spowodowane tym, że najpierw widzisz event z przyszłości z „occuredAt”, które wskazuje na późniejszą datę - to jest data, na kiedy została zaplanowana zmiana. Po tym, jak zmiana zostanie przez nas wykonana, widzisz event z przeszłości, z późniejszym „occuredAt”.

Polecamy na ten moment ignorować eventy z przyszłą datą w „occuredAt” - jest to błąd w działaniu zasobu, mamy w planach usunięcie takich zdarzeń z odpowiedzi endpointu.
