### ISSUE TITLE
Podłączenie API

### ISSUE THREAD

**Issue by Mov202** [allegro/allegro-api#5885]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X ] inny / other

:beetle: **Opis / Description**

 Dzień Dobry, Bylibyśmy zainteresowani uruchomieniem usługi wysyłki za pośrednictwem Allegro Kurier UPS oraz Allegro One Box. Przy realizacji zamówień korzystamy z integratora Baselinker. Proszę o informację w jaki sposób mogę dokonać integracji przez API aby móc korzystać z tej usługi ?

**Comment by AureliuszBrussy** [comment]
Usługa jest dostępna w ramach [API Wysyłam z Allegro](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY). Skontaktuj się proszę z supportem Baselinkera aby dowiedzieć się, jakie są możliwości w ramach ich integracji.

**Comment by Mov202** [comment]
Dziękuję za wiadomość.
Informuję, że w dniach 20-22.07.2022r. przebywam na urlopie bez dostępu do skrzynki mailowej.
Na maile odpowiem niezwłocznie po powrocie.

Hello,
Thank you for your message. From 20.07 to 22.07.2022 I am out of the office.
I will answer e-mails immediately after my return.
