### ISSUE TITLE
parametry  216501 i 216497

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5886]
Parametry mają podaną oczekiwaną wartość float

{"errors":[{"code":"ProductValidationException","message":"Product has invalid values [ValidatedParameter{parameter=SimpleParameter{id=216497, values=[ParameterValue{id=null, value=0,5-}]}, name=Czas wiązania, validationErrors=[ValidationError{value=0,5-, valueId=null, errorType=INVALID_RANGE_VALUE}]}] in category: 306885","details":null,"path":"productSet[0].product","userMessage":"Nieprawidłowe wartości parametrów: [parameter = Czas wiązania [ Nieprawidłowy parametr zakresowy - 0,5-]]"}]}

**Comment by AureliuszBrussy** [comment]
Zwróć uwagę, że przykładowy parametr 216497 to parametr zakresowy, o czym świadczy pole "range": 
```
            "restrictions": {
                "min": 0.0,
                "max": 1000000.0,
                "range": true,
                "precision": 2
            }
```

Dla parametrów zakresowych powinieneś przekazać wartości np. w ten sposób:
```
  {
      "id": "216497",
      "valuesIds": [],
      "values": [],
      "rangeValue": {
          "from": "0.5",
          "to": "1.0"
       }
  }
```

**Comment by AureliuszBrussy** [comment]
Obiekt "**restrictions**" zwracamy w odpowiedzi dla [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2), tak wygląda całość danych zwróconych dla parametru 216497:

```
        {
            "id": "216497",
            "name": "Czas wiązania",
            "type": "float",
            "required": false,
            "requiredForProduct": false,
            "unit": "h",
            "options": {
                "variantsAllowed": false,
                "variantsEqual": false,
                "ambiguousValueId": null,
                "dependsOnParameterId": null,
                "requiredDependsOnValueIds": null,
                "displayDependsOnValueIds": null,
                "describesProduct": true,
                "customValuesEnabled": false
            },
            "restrictions": {
                "min": 0.0,
                "max": 1000000.0,
                "range": true,
                "precision": 2
            }
        }
```

**Comment by FromAnyHole** [comment]
@Zbigi - jak odpytasz strukturę parametrów, to TYLKO parametr numeryczny może mieć:

[restrictions] => Array
             (
                            [min] => 0
                            [max] => 10000
                            [range] => TRUE | FALSE
                            [precision] => 2
             )

**Comment by Zbigi** [comment]
Jeśli zakres jest od 0- 100000, to dlaczego wyrzuca mi błąd gdy podaje 0.6

**Comment by Zbigi** [comment]
A ten parametr to ewidentny błąd
bject(stdClass)#21 (8) {
      ["id"]=>
      string(6) "216525"
      ["name"]=>
      string(8) "Zużycie"
      ["type"]=>
      string(5) "float"
      ["required"]=>
      bool(false)
      ["requiredForProduct"]=>
      bool(false)
      ["unit"]=>
      string(9) "kg/m²/mm"
      ["options"]=>
      object(stdClass)#22 (8) {
        ["variantsAllowed"]=>
        bool(false)
        ["variantsEqual"]=>
        bool(false)
        ["ambiguousValueId"]=>
        NULL
        ["dependsOnParameterId"]=>
        NULL
        ["requiredDependsOnValueIds"]=>
        NULL
        ["displayDependsOnValueIds"]=>
        NULL
        ["describesProduct"]=>
        bool(true)
        ["customValuesEnabled"]=>
        bool(false)
      }
      ["restrictions"]=>
      object(stdClass)#23 (4) {
        ["min"]=>
        float(0)
        ["max"]=>
        float(1000000)
        ["range"]=>
        bool(false)
        ["precision"]=>
        int(2)

Zaokres jest  0-10000 kg/mm2/mm czyli 
gdy potrzebuje 75 g na 5 m2 na 1 jedną warstwę to wychodzi 0.015 kg/m2/mm, czyli mam wpisać 0 czy 1:))

**Comment by AureliuszBrussy** [comment]
Tak jak wspomniałem - 216497 to parametr zakresowy, więc powinieneś podać wartość maksymalną i minimalną ("from" i "to"). Decyzja, co wprowadzić należy do Ciebie - zaakceptujemy wartość, która jest zgodna z ustalonymi wymaganiami. Jeżeli masz uwagę co do możliwych wartości, które przyjmuje dany parametr - zgłoś to [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by Zbigi** [comment]
Czyli musi być podany zakres a nie liczba z zakresu? ok.
