### ISSUE TITLE
Integracja API z Dynamics 365 Business Central

### ISSUE THREAD

**Issue by aleksandranowaknav** [allegro/allegro-api#5887]
Dzień dobry,

Pracuję w firmie, która jest partnerem MS pracujemy na programie Dynamics 365 Business Central.
Nasz klient pracuje na tym systemie i sprzedaje swoje towary na Allegro. 
Chcielibyśmy zintegrować nasz program z API ALLEGRO. 
Chciałabym uzyskać informację czy taka integracja jest płatna?
Co nasz klient powinien zrobić aby uzyskać możliwość takiej integracji?
Od czego zacząć pracę związane z integracją?
Czy istnieje możliwość uzyskania numeru telefonu aby skontaktować się z Państwem w sprawie integracji?

**Comment by MaciejFrackowiak** [comment]
Dostęp do API Allegro jest bezpłatny. Jego dokumentacja znajduje się [tu](https://developer.allegro.pl/documentation), natomiast podstawowe informacje oraz poradniki dostępne są na [portalu developerskim](https://developer.allegro.pl/). 
Wszelkie prace związane z integracją pozostają w Państwa oraz klienta gestii. Na pytania związane z API Allegro odpowiadamy przede wszystkim tu, czyli na GitHub'ie, nie prowadzimy wsparcia telefonicznego.

**Comment by aleksandranowaknav** [comment]
Dzień dobry, 
dziękujemy za wstępne informacje. Nasz klient chciałby tylko zintegrować się z Allegro w obszarze zamówień - czyli w momencie jak zakup zostanie dokonany na Allegro to chcielibyśmy otrzymać zamówienie poprzez API by móc je mieć od razu w naszym ERP. Czy mógłby Pan podesłać przykładowy plik z zamówieniem? Co ze słownikami? Wiadomo, że w bazie ERP produkty występują pod jakimś kodem, są również jednostki miary, Nabywcy itd. W jaki sposób jest robione mapowanie słowników? Czy my w naszym ERP musimy przechowywać gdzie numery towarów, klientów itd. wg Allegro i tak je rozpoznawać podczas importu zamówienia czy macie Państwo jakieś inne metody na to? 
Dziękuję.

**Comment by MaciejFrackowiak** [comment]
Udostępniamy [środowisko testowe](https://allegro.pl.allegrosandbox.pl/), na którym mogą Państwo dokonać testowego zamówienia, a następnie pobrać jego dane poprzez API. Jako Allegro nie udostępniamy żadnych mapowań. Obsługa zamówienia, czyli co się sprzedało, dane nabywcy, dane wysyłkowe itp. to dane, które są dostępne podczas pobierania szczegółów zamówienia. Natomiast cała ich korelacja z Państwa systemem już stricte wymaga działania po Państwa stronie. Zachęcam do zapoznania się z naszym poradnikiem dot. [obsługi zamówień](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR).
