### ISSUE TITLE
Pytanie odnośnie /order/events i checkout forms

### ISSUE THREAD

**Issue by zocimek** [allegro/allegro-api#589]
Witam,

mam pytanie - pobieram sobie wg dokumentacji listę eventów przez `/order/events` wskazując w pętli kolejny `?from=lastEventId` następnie dla każdego z eventów pobieram checkout form poprzez `/order/checkout-forms/{id}`. Dla wielu z nich dostaję wynik `404 Not found` czy to jest prawidłowe zachowanie ? 

Czy w takim przypadku mam pewność, że wszystkie zamówienia zostaną pobrane czy mogą się zdarzyć braki w zamówieniach pobranych tą metodą ?

**Comment by MarcinLuczak** [comment]
@zocimek podaj proszę przykłady, najlepiej jako cURL-e requesta i response w których widać tą sytuację.

**Comment by zocimek** [comment]
Witam,

Pobranie eventów:
```
curl --request GET --verbose \
  --url 'https://api.allegro.pl/order/events?limit=1&from=1531860770094563' \
  --header 'Accept: application/vnd.allegro.beta.v1+json' \
  --header 'Authorization: Bearer <token>' \
  --header 'Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8'
```

Response:
```
< HTTP/1.1 200 OK
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: afdd02173cfbfda9
< Date: Sat, 15 Sep 2018 14:02:50 GMT
< X-RateLimit-Remaining: 8997
< X-Content-Type-Options: nosniff
< Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8
< Content-Length: 571
< X-RateLimit-Limit: 9000
<
* Connection #0 to host api.allegro.pl left intact
{"events":[{"id":"1531861103082540","order":{"seller":{"id":"29023349"},"buyer":{"id":"25416914","email":"oceanocean@wp.pl","guest":false,"login":"motomarkiewicz"},"lineItems":[{"offer":{"id":"6612640295","name":"PRZYCISK GUZIK BLOKADY DRZWI EUR CITROEN C3 II 13R"},"price":{"amount":"3","currency":"PLN"},"id":"195e8fd0-8a04-11e8-9004-5f5f3e006f9a","quantity":1,"originalPrice":{"amount":"3","currency":"PLN"},"boughtAt":"2018-07-17T20:58:11.455Z"}],"checkoutForm":{"id":"195e8fd2-8a04-11e8-9004-5f5f3e006f9a"}},"type":"BOUGHT","occurredAt":"2018-07-17T20:58:11.455Z"}]}
```

Pobranie checkout-form:
```
curl --request GET --verbose \
  --url https://api.allegro.pl/order/checkout-forms/195e8fd2-8a04-11e8-9004-5f5f3e006f9a \
  --header 'Accept: application/vnd.allegro.beta.v1+json' \
  --header 'Authorization: Bearer <token>' \
  --header 'Content-Type: application/vnd.allegro.beta.v1+json;charset=UTF-8'
```

Response
```
< HTTP/1.1 404 Not Found
< Expires: 0
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< X-XSS-Protection: 1; mode=block
< Pragma: no-cache
< X-Frame-Options: DENY
< Trace-Id: 1a61a96a9126db54
< Date: Sat, 15 Sep 2018 14:04:48 GMT
< X-RateLimit-Remaining: 9000
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Content-Length: 131
< X-RateLimit-Limit: 9000
<
* Connection #0 to host api.allegro.pl left intact
{"errors":[{"code":"ERROR","message":"An error has occurred","path":"/order/checkout-forms/195e8fd2-8a04-11e8-9004-5f5f3e006f9a"}]}
```

**Comment by MaciejPotepa** [comment]
Dzięki za dane, analizujemy Twój problem.

**Comment by TomekKaczmarek** [comment]
Dzień dobry, przeanalizowaliśmy sytuację.

Problem wynika z tego, że próbujesz sczytać dane z formularza pozakupowego, który podaliśmy przy typie zdarzenia "type": "BOUGHT" - czyli odpowiednikowi aktu zakupowego. Kiedy rezerwujemy id formularza pozakupowego i zwracamy w nim podstawowe dane - nie oznacza to jednak, że kupujący go wypełnił.

Wypełniony i kompletny formularz pozakupowy otrzymasz w typie zdarzenia "type": "READY_FOR_PROCESSING" i dla takiego typu zalecamy pobieranie danych dla checkout-form.id.

Klient może kupić kilka przedmiotów, od wielu sprzedawców i opłacić je z opóźnieniem w ramach  formularza pozakupowego. W takim przypadku zamówienie otrzyma nowy checkout-form.id, który zwrócimy dla typu "READY_FOR_PROCESSING.
