### ISSUE TITLE
baza TecDoc w Rest API - nieaktualna w stosunku do dostępnej przez formularz?

### ISSUE THREAD

**Issue by emesio** [allegro/allegro-api#5891]
Hej,

czy dostępna przez REST API baza TecDoc (dopasowanie pojazdów) jest dużo starsza (mniej aktualna) niż ta dostępna przez formularz?

Przykładowo: pobrałem bazę motocykli zasobem https://api.allegro.pl/sale/compatible-products/groups?type=MOTORCYCLE
a potem dla tych grup (marek) - modele - https://api.allegro.pl/sale/compatible-products?type=MOTORCYCLE&group.id=(...)

W tym zasobie jest aktualnie 7588 pozycji (od A do Z), ale brakuje wielu nowszych rocznikowo motocykli, które są dostępne przez formularz. 
Podaję przykłady: Triumph Speed Triple (RR ABS) 1200ccm 180KM 2022, Suzuki (GSX RRQ Hayabusa ABS) 1300ccm 190KM 2022, Husqvarna TC 65ccm 2022 (tak w sumie nie ma żadnego modelu "2022" z kilkudziesięciu które są w formularzu), brakuje także wielu modeli 2021 (np. Yamaha Tracer (7 700 MTT690 ABS) 700ccm 73KM 2021, Yamaha Tracer ( 9 900 ABS) 900ccm 119KM 2021) i tak dalej. 

Baza wygląda na sporo starszą. Czy to jest jakoś aktualizowane z opóźnieniem albo jest inna metoda na aktualność tej bazy?

**Comment by MartaNowaczyk** [comment]
Baza powinna być identyczna prez API i na froncie. Poza tym powinieneś wybierać type=MOTORCYCLE_EXPLODED a nie type=MOTORCYCLE. Jak znajdziesz jakieś rozbieżności, to podaj konkretny przykład.
