### ISSUE TITLE
Na etykiety Allegro ONE BOX nie przenoszą się informacje z ustawień "Zawartość"

### ISSUE THREAD

**Issue by ZildijanEU** [allegro/allegro-api#5895]
Aplikacja z integracją "Wysyłam z allegro" = EasyUploader .

Na etykiety Allegro ONE BOX nie przenoszą się informacje z ustawień "Zawartość",
(Wysyłam z allegro / Konfiguracja / Zawartość), co utrudnia nam pakowanie paczek.

W wysyłce allegro DPD zagranica i DPD punkt przez "wysyłam z allegro" nie ma problemu.

W związku z tym, że coraz więcej użytkowników aplikacji EasyUploader chce rozpocząć współpracę z allegro ONE BOX, pojawiają się w pełni zasadne zgłoszenia typu: 
"Podpinam się do w/w pytania odnośnie parametru "Zawartość" , **która nie jest przenoszona na etykiety. W naszym przypadku jest to niezbędne w procesie pakowania.** "

Nam również jest to niezbędne, a brak tego niestety będzie uniemożliwiał nam korzystanie z ONE BOX, który mamy przy naszym biurowcu, a to będzie przykre.

**Bardzo prosimy o poprawkę, aby w ONE BOX "Zawartość" była przenoszona na etykietę tak samo jak w DPD zagranica i DPD punkt, oraz przynajmniej w 50 znakach, lub więcej jeżeli to możliwe. Autor aplikacji prosił o zgłoszenie do Państwa.**

**Comment by MaciejFrackowiak** [comment]
Opisana kwestia nie dotyczy stricte funkcjonowania samego API Allegro, a jednej z metod dostawy dostępnych w ramach Wysyłam z Allegro. Dlatego proszę, aby przedstawiony tu problem zgłosili Państwo poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&subjectId=2d542135-a6d7-474c-a4a1-f96451c8bbc5).
