### ISSUE TITLE
API nie zwraca informacji o wykonanych zwrotach płatności.

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#5896]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy tworzeniu rządzania zwrotu do płatności 18a698d1-e7de-11ec-a9bc-27071233f79b (orderId: 181d1d84-e7de-11ec-9fcf-7be1fcbeebe1)
otrzymuję komunikat: Couldn't set QUANTITY refund draft type for offer with id=b9e3ee4c-072c-4b55-be2f-5e02757b7d8e, conflict with historical types=AMOUNT".
Trace-Id: e2add3883ebc4f77

Gdy sprawdzam historię zwrotów dla płatności dostaję "{
    "refunds": [],
    "count": 0,
    "totalCount": 0
}" 
Trace-Id: 46d2b2ae5ebd85c7

**Comment by mateuszbieniascontelizer** [comment]
wykonaie poniższego zapytania dla obydwu [payment.id](http://payment.id/) zwraca "{
    "refunds": [],
    "count": 0,
    "totalCount": 0
}"
w tym tkwi cały problem
Jak dotarłeś to tej informacji że została zwrócona kwota 113,06zł? 
curl --location --request GET 'https://api.allegro.pl/payments/refunds?payment.id=18a698d1-e7de-11ec-a9bc-27071233f79b' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer "token"

**Comment by MaciejFrackowiak** [comment]
Zwrot został dokonany w ramach Programu Ochrony Kupujących, dlatego nie jest on widoczny jako zwrot dokonany ręcznie przez sprzedającego.

**Comment by mateuszbieniascontelizer** [comment]
a czy możecie zrobić taki zasób który to udostępni

**Comment by MaciejFrackowiak** [comment]
Wszelkie sugestie zmian w dotychczasowych zasobach, jak i pomysły na nowe możesz zamieścić w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions).
