### ISSUE TITLE
W jakich przypadkach zwracany jest komunikat ACCOUNT_NOT_ALLOWED_TO_SEND_MESSAGES

### ISSUE THREAD

**Issue by MartaNowaczyk** [allegro/allegro-api#5897]
<div type='discussions-op-text'>

<sup>Originally posted by **tomasz-grzesik** July 15, 2022</sup>
Dzień dobry,

w jakich sytuacjach na konto Użytkownika zostaje nałożone ograniczenie skutkujące zwracaniem błędu ACCOUNT_NOT_ALLOWED_TO_SEND_MESSAGES?</div>

**Comment by MartaNowaczyk** [comment]
Występuje wtedy, gdy np. masz blokadę konta. Więcej informacji będę mogła podać, gdy podasz login/ID tego konta. Możesz przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=c1581428-a33f-4506-826f-720b60a920c0&subjectId=7e8829e8-fdce-4bfe-82f3-59f4279fd738) z dopiskiem, że dotyczy zgłoszenia na GitHubie #5897.

Na przyszłość, jeśli temat nie dotyczy sugestii zmian w API twórz proszę nowy wątek w [Issues](https://github.com/allegro/allegro-api/issues/new/choose).

**Comment by tomasz-grzesik** [comment]
@MartaNowaczyk , dziękuję za wyjaśnienia i przepraszam za umieszczenie postu w dyskusjach.
