### ISSUE TITLE
Łączenie w warianty, a odpowiedź z API

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#5898]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Witam, 

Chciałbym zapytać o łączenie ofert. Powiedzmy, że mam jakiś produkt w 3 rozmiarach. Wystawiłem to jako 3 osobne oferty, które później zostały połączone przez allegro. Wchodzą w link oferty zostajemy automatycznie przekierowani do połączonej oferty i to jest okej. Jednak w przypadku próby pobrania tej oferty z API (zasób `sale/offers/`) dostajemy informację, że aukcja została zakończona. Czy takie zachowanie jest normalne?

**Comment by PrzemyslawLukanowski** [comment]
Status w polu `publication.status` danej oferty powinien odzwierciedlać aktualny stan rzeczywisty. Jeśli zatem oferta jest aktywna, to w tym polu powinna widnieć wartość `ACTIVE`. Jeśli jest inaczej, podaj proszę przykładowy numer oferty. Jeśli nie chcesz przekazywać go na forum, skorzystaj z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt) - prześlij dane i dopisz, że dotyczą wątku #5898 na GitHubie.

**Comment by mrezlik** [comment]
A mogę podać trace-id dla przykładowego zapytania którego jest zwracany niepoprawny status? :) Jeśli tak to oto on: `3c566c3f884410ba`, jeśli nie to mam pytanie, którą kategorię wybrać w formularzu kontaktowym? Bo po wybraniu "Allegro API" nie mam możliwości wysłania wiadomości, a tylko napisania wątku na tym forum :)

**Comment by PrzemyslawLukanowski** [comment]
Tak, trace-id wystarczy, dziękuję. Wskazana oferta jest zakończona, możesz skopiować numer do wyszukiwarki - wyświetli się informacja: 

> Sprzedaż zakończona. Nie było ofert kupna.

Status w API wygląda zatem na prawidłowy.

**Comment by mrezlik** [comment]
To dlaczego po wejśćiu w link 'allegro.pl/oferta/numer-oferty` przenosi mnie do aktywnej aukcji? :)

**Comment by PrzemyslawLukanowski** [comment]
<img width="552" alt="Zrzut ekranu 2022-07-15 o 14 03 55" src="https://user-images.githubusercontent.com/51473661/179219451-020877e9-7073-40d7-986c-ed8ef5ea97fe.png">
Czy na pewno rozmawiamy o ofercie ____487? Wg załączonego screena oferta jest nieaktywna w serwisie.

**Comment by mrezlik** [comment]
Tak, to jest ta sama oferta, ale u mnie po wejściu w link przenosi mnie na ofertę ______080 (jeśli to nie wystarczy to podaję trace-id dla tej oferty na którą mnie przenosi: `ab0ebd0aa293f847`

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, że dla tej oferty w API otrzymujesz prawidłowy status "ACTIVE"? 
Co do przekierowania na stronie na inną ofertę, sugeruję tutaj kontakt przez formularz, ponieważ nie jest to mechanizm powiązany z działaniem API. W moim przypadku nie udało się dodatkowo go odtworzyć, trafiam na stronę oferty, o którą pytam.

**Comment by mrezlik** [comment]
Tak, dla tej drugiej już dostaję poprawny status 'ACTIVE'  :) W takim razie napiszę w formularzu kontaktowym. Pozdrawiam :)
