### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by DINK74** [allegro/allegro-api#59]
Hi,

Just started learning Allegro REST API but I find the lack of documentation disturbing :-)

I spotted an example on official page (https://developer.allegro.pl/about/) "GET https://api.allegro.pl/categories/2" which reveals some info about category structure but I couldn't find any explanations on returned values. Where can I find some info on this as well as on /users or /offers or others if they're implemented?

Regards.

**Comment by AniaMalinowska** [comment]
Hi.

This is only an example.

All documentation is [here](https://developer.allegro.pl/documentation/) - 
you will find there all the methods that we provide in the REST API.

**Comment by DINK74** [comment]
yeah, but how come that this example is not documented but working - I've spent hour or so trying to figure other "examples" out (no luck thou) :-) Can you add this /categories, /users, etc. to the official docs?

**Comment by AniaMalinowska** [comment]
How I said, this is only an example. I do not guarantee that this example will return the correct data. All documentation is [here](https://developer.allegro.pl/documentation/) - you will find there all the methods that we provide in the REST API.
