### ISSUE TITLE
Czy po "BUYER_CANCELLED" może wystąpić "READY_FOR_PROCESSING"?

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#5900]
Dzień dobry,

pytanie: jeżeli zamówienie zostało przez klienta anulowane, i tym samym wystąpiło zdarzenie "BUYER_CANCELLED" które jest widoczne przy pobieraniu zdarzeń [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET), to czy po tym zdarzeniu może jeszcze wystąpić zdarzenie "READY_FOR_PROCESSING" dla takiego anulowanego zamówienia?

**Comment by tztztztz** [comment]
Czy mógłbym otrzymać wyjaśnienie w jakiej sytuacji może się to zdarzyć, bo jest to trochę nielogiczne:

1. Klient anuluje zamówienie (zdarzenie BUYER_CANCELLED)
2. Następnie anulowane już zamówienie jest opłacane przez klienta (?) i pokazuje się jako READY_FOR_PROCESSING

To trochę nie ma sensu - no chyba, że Allegro pozwala na opłacenie anulowanego zamówienia?

**Comment by PrzemyslawLukanowski** [comment]
Klient nie może opłacić zamówienia po anulowaniu. Może natomiast zdarzyć się sytuacja, że kupujący od razu anuluje zakup po płatności, ale event związany z opłaceniem przedmiotu zostanie przez nas przetworzony z minimalnym opóźnieniem, przez co zwrócimy go po zdarzeniu "BUYER_CANCELLED" zamiast przed.

**Comment by tztztztz** [comment]
Rozumiem - to efekt uboczny asynchroniczności Waszego systemu. Pytanie tylko, czy Checkout Form pobrany przez [GET /order/checkout-forms/{checkoutFormId}](https://developer.allegro.pl/documentation/#operation/getOrdersDetailsUsingGET) dla takiego zamówienia będzie miał wtedy status "CANCELLED", tak jak to opisano na początku w linku poniżej?

https://github.com/allegro/allegro-api/issues/3085

**Comment by PrzemyslawLukanowski** [comment]
Tak, zamówienie będzie odpowiednio oznaczone jako anulowane, dlatego w polu `"status"` zwrócimy wartość `"CANCELLED"`.

**Comment by tztztztz** [comment]
Ok, myślę, że wszystko już jasne, dziękuję za informację, i zamykam temat.
