### ISSUE TITLE
Błąd przy generowaniu etykiety allegro ONE

### ISSUE THREAD

**Issue by d3stozaur** [allegro/allegro-api#5901]
Występuje problem: 
 - [ X ] z zasobem REST API / with a REST API resource
 - [ X ] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Przy próbie wygenerowanie przesylki Allegro one otrzymujemy blad. W requescie podajemy     "serviceId": 16945537 który jest zwracany jako dostępny dla danego konta

`{
    "errors": [
        {
            "code": "ERROR",
            "details": null,
            "message": "The selected service is not available",
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage": "Wybrana us\u0142uga jest niedost\u0119pna"
        }
    ],
    "id": "17eeaa48-1c1f-40ff-a892-e98e99abe025",
    "parcelId": null,
    "status": "ERROR"
}
`

**Comment by MaciejFrackowiak** [comment]
Jak widzę dla wskazanej transakcji nadałeś już przesyłkę w dniu 1 lipca 2022 - przesyłka ta została doręczona.
