### ISSUE TITLE
Wzrost liczby błędów przy zmianie cen - Error when update offer price

### ISSUE THREAD

**Issue by dlis2010** [allegro/allegro-api#5902]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Witam serdecznie,

od kilku dni zauważyliśmy drastyczny wzrost błędów podczas zmiany cen:

[message] => OPERATION_FAILED
[status] => FAIL
[scheduledAt] => 2022-07-18T07:05:53.338Z
[finishedAt] => 2022-07-18T07:05:53.326Z
[field] => price
[errors] => Array
     [code] => OFFER_PRICE_CHANGE_ERROR
     [message] => Error when update offer price.
     [details] => 
     [path] => 
     [userMessage] => Błąd podczas zmiany ceny.

Powyższe błędy zdarzały się wcześniej, lecz w znacznie mniejszej skali.
Odnotowujemy sytuację w których **ponad 30% requestów z zmianą ceny kończy się w/w błędem.**

przykładowy guid 58bc400a-825e-45ec-b23d-8080c85241d7

w powyższym guid jest zmiana ceny dla jednej oferty - **dla tej konkretnej oferty próbujemy zmienić cenę od 4 dni - za każdym razem ten sam błąd.**

**Comment by MaciejFrackowiak** [comment]
Weryfikuję przypadek z zespołem, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Potwierdzam - mamy problemy techniczne z działaniem funkcjonalności dla części ofert. Trwają już prace naprawcze. Ponownie odezwę się, gdy otrzymam potwierdzenie usunięcia błędu.
