### ISSUE TITLE
Brak kategorii w response api, gdy kategoria istnieje w serwisie.

### ISSUE THREAD

**Issue by support-cti** [allegro/allegro-api#5907]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Odpytując url:  /sale/categories/82284
Otrzymuję odpowiedź:

    ["errors"]=>
    array(1) {
      [0]=>
      array(5) {
        ["code"]=>
        string(5) "ERROR"
        ["message"]=>
        string(26) "Category '82284' not found"
        ["details"]=>
        string(25) "ResourceNotFoundException"
        ["path"]=>
        NULL
        ["userMessage"]=>
        string(26) "Category '82284' not found"
      }
    }

Gdy w serwisie taka kategoria istnieje:
https://allegro.pl/kategoria/architektura-ogrodowa-place-zabaw-82284

**Comment by MaciejFrackowiak** [comment]
Powodem takiego stanu rzeczy jest to, że wskazana kategoria (id=82284) jest kategorią nawigacyjną, którą widzą tylko kupujący, a nie kategorią asortymentową, w której sprzedawcy mogą wystawiać swoje przedmioty (id=86342). Kategoria została w przeszłości scalona z inną - oznacza to, że jeśli kategoria A została scalona kategorią B, to oferty możesz wystawić tylko w kategorii B, ale kupujący zobaczą ją zarówno w kategorii A, jak i B. Więcej na temat tego przeczytasz na [naszej stronie](https://developer.allegro.pl/news/na-poczatku-grudnia-zaczniemy-scalac-kategorie-po-stronie-sprzedajacego-k1nyd205YHo), jak i na [stronie dla sprzedających](https://allegro.pl/dla-sprzedajacych/laczymy-kategorie-z-tym-samym-asortymentem-AggmRPKrnuY).

**Comment by support-cti** [comment]
Dziękuję za informację – pytanie, czy gdzieś można prześledzić tego typu zmiany w kategoriach, aby uniknąć podobnych problemów w przyszłości? 

Dodatkowo, czy można skądś pobrać kompletne, aktualne drzewo kategorii?

 

 

Dziękuję i pozdrawiam
Dariusz Pawłowski

 <http://www.ctinet.pl/> Opis: ctinet
Centrum Technologii Internetowych CTI Sp. z o.o.
ul. Kupiecka 93/10
65-058 Zielona Góra

tel. 68 457 00 07
fax 68 457 00 01
e-mail  ***@***.***> ***@***.***

NIP 9730850537, Regon 080067074, KRS 0000248304
Sąd Rejonowy w Zielonej Górze, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego, Kapitał zakładowy 50 000,00 PLN
Bank Zachodni WBK 93 1090 1636 0000 0001 0477 6343

W świecie ryzyka, wiedz komu zaufać.
 <http://www.ctinet.pl/> ctinet.pl - hosting poczta domeny webdesign  |   <http://www.registry.pl/> registry.pl - rejestracja domen  |   <https://ssl24.pl/> ssl24.pl - certyfikaty SSL - Bezpieczeństwo bez kompromisów

**Comment by MaciejFrackowiak** [comment]
Zmiany w kategoriach można śledzić zasobem [GET /sale/category-events](https://developer.allegro.pl/documentation/#operation/getCategoryEventsUsingGET_1). Natomiast drzewo kategorii możliwe jest do pobrania przy pomocy [GET /sale/categories](https://developer.allegro.pl/documentation/#operation/getCategoriesUsingGET).
