### ISSUE TITLE
Incorrect authorization information - POCZTA_POLSKA

### ISSUE THREAD

**Issue by Desseres** [allegro/allegro-api#5908]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dla formy dostawy POCZTA_POLSKA API zwraca błąd generowania etykiety `Incorrect authorization information`

2022-07-20 08:11:36.902 [INFO]    Request UUID: e489e164-0888-4a40-b2ed-220f964159ca
2022-07-20 08:11:37.090 [INFO]    Status: IN_PROGRESS
2022-07-20 08:11:38.308 [INFO]    Status: IN_PROGRESS
2022-07-20 08:11:39.621 [INFO]    Status: ERROR : Incorrect authorization information

2022-07-20 08:11:35.215 [INFO]    Request UUID: 2065d5ea-18ff-44ca-bf39-3ed86e24f6a0
2022-07-20 08:11:35.480 [INFO]    Status: IN_PROGRESS
2022-07-20 08:11:36.730 [INFO]    Status: ERROR : Incorrect authorization information

2022-07-20 08:11:33.152 [INFO]    Request UUID: a19844b7-e268-4bd5-80b9-808fe9d0db78
2022-07-20 08:11:33.340 [INFO]    Status: IN_PROGRESS
2022-07-20 08:11:34.621 [INFO]    Status: ERROR : Incorrect authorization information

**Comment by MaciejFrackowiak** [comment]
Potwierdzam występowanie problemu dla przesyłek Poczty Polskiej - działamy już, aby usprawnić proces.

**Comment by tobiaxor** [comment]
Czy mogę prosić o przybliżony termin naprawy? Nie wiem u ilu osób to występuje, ale u nas uniemożliwia realizację zamówień.

**Comment by MaciejFrackowiak** [comment]
@tobiaxor Zespół odpowiedzialny za usługę stara się rozwiązać problem najszybciej jak to możliwe, niestety konkretnego terminu obecnie nie potrafię wskazać.

**Comment by Desseres** [comment]
@MaciejFrackowiak możecie nadać temu tematowi najwyższy priorytet? Usługa nie działa i po stronie API i po stronie panelu allegro z tym samym błędem. Zamówienia oczekujące lecą w setki na pojedynczym koncie a zdenerwowanie klientów również rośnie i zaczynają się telefony "czemu nie wysłaliście mojego zamówienia". Cała sytuacja ma również przełożenie na ocenę konta allegro - brak wysyłki w terminie dla sporej ilości zamówień.

**Comment by MaciejFrackowiak** [comment]
@Desseres Jak sam zauważyłeś to nie problem wyłącznie API, a całej usługi (WWW + API) w korelacji z Pocztą Polską - trwają działania mające na celu wyeliminowanie błędu.

**Comment by MaciejFrackowiak** [comment]
@Desseres @tobiaxor Otrzymałem potwierdzenie usunięcia problemu. Przepraszam za niedogodności.

**Comment by Desseres** [comment]
@MaciejFrackowiak dzięki wielkie, potwierdzam że działa :)

**Comment by Kuba-Id** [comment]
Wznawiam temat:

Problem podczas generowania: Allegro Kurier Pocztex pobranie
i pobierania shippment Id.

URL: https://api.allegro.pl/shipment-management/shipments/create-commands/637eb131-f4d8-4dfd-9544-b1dc1afcc4b2

Odpowiedź API:
[{"code":"VALIDATION_ERROR","message":"Incorrect authorization information","details":"","path":"shipmentId","userMessage":"Niepoprawne dane autoryzacyjne"}]

trace-id = 5ae856cdd60f26c7


Co tym razem jest nie tak, będę wdzięczny za pomoc?

**Comment by MaciejFrackowiak** [comment]
@Kuba-Id Sprawdź proszę dane autoryzacyjne Poczty Polskiej, które wprowadziłeś w ustawieniach Wysyłam z Allegro.
