### ISSUE TITLE
Problem z doGetPostBuyFormsDataForSellers

### ISSUE THREAD

**Issue by kylovile** [allegro/allegro-api#591]
Dla niektórych aktów zakupowych API zwraca ShipmentId = 0 z funkcji doGetPostBuyFormsDataForSellers.
Dla przykładu dla aktu o id (postBuyFormId)898637931 i statusie jako "Zakończona" zwraca 0.

![image](https://user-images.githubusercontent.com/39157522/45346055-647f5600-b5a8-11e8-970b-1d39064e830a.png)

**Comment by MarcinLuczak** [comment]
@kylovile w tym formularzu pozakupowym zostały opłacone różne przedmioty od różnych sprzedawców, a każdy z ma przypisany inny sposób dostawy. W polu, które wskazałeś (postBuyFormShipmentId) zwracany jest tylko jeden identyfikator dostawy. Tutaj jest ich więcej, dlatego zwróciliśmy 0.

**Comment by kylovile** [comment]
@MarcinLuczak to w jaki sposób się dowiem jaki został wybrany sposób dostawy w mojej sprzedaży?

**Comment by LukaszKorek** [comment]
Identyfikator sposobu sposobu otrzymasz w polu postBuyFormShipmentId. listę identyfikatorów sposobów dostawy uzyskać można za pomocą metody doGetShipmentData.
