### ISSUE TITLE
Błąd 403 dla GET /offers/listing

### ISSUE THREAD

**Issue by kacperKarman** [allegro/allegro-api#5910]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Mam problem z zasobem GET /offers/listing. Na środowisku testowym wszystko działa bez zarzutu, natomiast na koncie produkcyjnym przy próbie odpytania API otrzymuję Error: Request failed with status Code 403. Pozostałe zasoby jak np odświeżanie tokenów czy pobieranie własnych aukcji działają poprawnie. Według dokumentacji zasób ten jest dostępny na koncie produkcyjnym tylko wtedy gdy jest na nim włączone dwustopniowe logowanie. Miałem je włączone na moim koncie (telstar_sklep) już przed rejestracją aplikacji, ale mimo to zasób nie działa. 
Proszę o informacje czy oprócz dwustopniowego logowania są jeszcze jakieś wytyczne które muszę spełnić by rozwiązać powyższy problem.

**Comment by PrzemyslawLukanowski** [comment]
Tak, istnieją dodatkowe wytyczne. Zgodnie z dokumentacją, zasób jest dostępny tylko dla zweryfikowanych aplikacji  - "[Access for verified applications only](https://developer.allegro.pl/listing/).". Następnie znajdziesz informacje w naszym poradniku:

"Dostęp do [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) mają tylko zweryfikowane aplikacje.

**Jak zweryfikować aplikację?**

Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)."
