### ISSUE TITLE
Brakujące eventy

### ISSUE THREAD

**Issue by ecat-rg** [allegro/allegro-api#5911]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Po wysłaniu requesta na endpoint order/events?limit=1000 z prawidłowym access tokenem, zwracane są eventy, ale nie wszystkie. Na naszym koncie allegro pojawiły się zamówienia np. 12 i 15 lipca, a nie ma po nich śladu w response tego endpointu.

Oto ostatnie eventy:
294 => array:4 [
      "id" => "1657529498718660"
      "order" => array:4 [ …4]
      "type" => "FULFILLMENT_STATUS_CHANGED"
      "occurredAt" => "2022-07-11T08:51:27.710Z"
    ]
    295 => array:4 [
      "id" => "1657529585887053"
      "order" => array:4 [ …4]
      "type" => "FULFILLMENT_STATUS_CHANGED"
      "occurredAt" => "2022-07-11T08:52:54.985Z"
    ]
    296 => array:4 [
      "id" => "1657529668703481"
      "order" => array:4 [ …4]
      "type" => "FULFILLMENT_STATUS_CHANGED"
      "occurredAt" => "2022-07-11T08:54:17.155Z"
    ]
    297 => array:4 [
      "id" => "1658173841071540"
      "order" => array:4 [ …4]
      "type" => "FULFILLMENT_STATUS_CHANGED"
      "occurredAt" => "2022-07-18T19:50:29.429Z"
    ]
    298 => array:4 [
      "id" => "1658217686155900"
      "order" => array:4 [ …4]
      "type" => "FULFILLMENT_STATUS_CHANGED"
      "occurredAt" => "2022-07-19T08:01:15.727Z"
    ]

Jak widać jest dziura między 11, a 18 lipca.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymaliśmy już podobne zgłoszenie za pośrednictwem formularza kontaktowego. Nie możemy potwierdzić występowania błędy, zdarzenia zwracamy poprawnie. Poniżej znajdziesz przykładowe eventy dla zamówienia 58567f54-044d-11ed-b592-1140c67e2932:

1) 1657896643191396 - BOUGHT
2) 1657896643834671 - FILLED_IN
3) 1657896656053858 - READY_FOR_PROCESSING

Zwróć proszę uwagę, czy nie korzystasz w żądaniach z parametrów, które zawężają zakres danych, np. czy nie pobierasz zdarzeń tylko typu "FULFILLMENT_STATUS_CHANGED".

**Comment by ecat-rg** [comment]
[allegro_events.txt](https://github.com/allegro/allegro-api/files/9148680/allegro_events.txt)

Przesyłam cały plik zwrotki, nie dodajemy żadnych parametrów.

**Comment by PrzemyslawLukanowski** [comment]
Wskazane logi dotyczą konta T###o_2, które jest aktualnie zablokowane, a ostatnie zamówienie pochodzi z 4 lipca. Przesłane przeze mnie zdarzenia dotyczą konta T###o2 i w tym przypadku eventy generowane są na bieżąco. Upewnij się proszę, że zdarzenia pobierasz z tokenem dla prawidłowego użytkownika.

**Comment by ecat-rg** [comment]
Znów natrafiłem na ten sam problem.

https://api.allegro.pl/order/events zwraca tablicę eventów, która kończy się na 14 lipca, mimo, że były później zamówienia. Dotyczy konta, na którym jest zamówienie 8d0f5839-1112-11ed-ba81-d3c2ad420f05 (znajdziecie po tym konto i aplikację). Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Sprawdziłam i dla konta p###132 poprawnie zwracamy eventy. Ostatni: 1659300772112649, 2022-07-31T20:52:35.762Z - jest to zamówienie o którym wspomniałeś. Może używasz filtrów, które mogą powodować takie zachowanie? Sprawdź to proszę.

**Comment by MartaNowaczyk** [comment]
Dla konta pr############m1 event 1657818817686793 jest najnowszy, stąd po nim nie ma żadnego == pusta tablica.

**Comment by ecat-rg** [comment]
Ale to jest event konta p###########m132, loguję się na to konto w Allegro i widzę zamówienia (późniejsze niż 14 lipca), a nie widać tego w API, w aplikacji wygenerowanej dla tego konta.

**Comment by ecat-rg** [comment]
Wysłałem zgłoszenie przez formularz kontaktowy, numer 25243289

**Comment by MartaNowaczyk** [comment]
Ok, jak tylko do mnie dotrze, sprawdzę i dam znać jak coś ustalę.

**Comment by MartaNowaczyk** [comment]
W przesłanym załączniku są eventy dla konta T######o_2, a zamówienia o których piszesz - "z 3 sierpnia (0492eb21-####-####-####-f7d03e9ff448) i z 1 sierpnia (a5aed762-####-####-####-f72759e6cc09)" są z konta T######o2 i są zwracane prawidłowo przez nasze API.
Tak jak @PrzemyslawLukanowski pisał wcześniej, upewnij się, że używasz odpowiedniego tokena, bo wygląda na to, że jesteś zautoryzowany na innym koncie niż oczekujesz. Polecam rozkodować token i sprawdzić https://jwt.io/.

**Comment by ecat-rg** [comment]
No i tu dochodzimy do istoty problemu. Loguję się na allegro na konto T######o2 i widzę zamówienia np. z 3 sierpnia (0492eb21-####-####-####-f7d03e9ff448), które jest z innego konta? (T######o_2)? Rozkodowałem token i zgodnie z przypuszczeniem odpytuję konto, którego listę eventów chcę pobrać - T######o2.

**Comment by MartaNowaczyk** [comment]
Dlatego prosiłam, abyś przesłał pełen request i response, a nie tylko response. Możesz też podać trace-id z nagłówka odpowiedzi. Po tym znajdę ten konkretny przypadek w logach.

**Comment by ecat-rg** [comment]
Podsyłam trace-id: 25dd4d51dbcb31dc

**Comment by MartaNowaczyk** [comment]
Z podanego trace-id wynika, że odpytujesz konto T######o_2, także wszystko wygląda dobrze z naszej strony.

**Comment by ecat-rg** [comment]
Zalogowałem się na konto T######o2, przeszedłem na stronę https://apps.developer.allegro.pl/, stamtąd pobrałem Client ID oraz Client Secret, polączyłem konto, wygenerował się klucz, którym odpytałem API o listę eventów. Dostałem to co przekazałem w trace-id. Skąd w takim razie  T######o_2?

**Comment by MartaNowaczyk** [comment]
Tego zweryfikować nie mogę. Możesz podesłać przez formularz kontaktowy wszystkie kroki, jakie dane skąd pobierasz, **pełen** request i response wywołań, wtedy mogę przeanalizować w czym problem.

**Comment by ecat-rg** [comment]
Wysłałem komplet informacji przez formularz.

**Comment by MartaNowaczyk** [comment]
OK, jak tylko do mnie trafi, zweryfikuję i dam znać.
