### ISSUE TITLE
Wyszukiwanie po kodzie EAN nie zwraca produktów

### ISSUE THREAD

**Issue by lukasznurzynski** [allegro/allegro-api#5912]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
REQUEST

GET {srodowisko_testowe}/sale/products?phrase=8003437134920&mode=GTIN

RESPONSE

Array
(
    [products] => Array
        (
        )

    [categories] => Array
        (
            [subcategories] => Array
                (
                    [0] => Array
                        (
                            [id] => 5
                            [name] => Dom i Ogród
                            [count] => 0
                        )

                    [1] => Array
                        (
                            [id] => 11763
                            [name] => Dziecko
                            [count] => 0
                        )

                    [2] => Array
                        (
                            [id] => 42540aec-367a-4e5e-b411-17c09b08e41f
                            [name] => Elektronika
                            [count] => 0
                        )

                    [3] => Array
                        (
                            [id] => 4bd97d96-f0ff-46cb-a52c-2992bd972bb1
                            [name] => Firma i usługi
                            [count] => 0
                        )

                    [4] => Array
                        (
                            [id] => a408e75a-cede-4587-8526-54e9be600d9f
                            [name] => Kolekcje i sztuka
                            [count] => 0
                        )

                    [5] => Array
                        (
                            [id] => 38d588fd-7e9c-4c42-a4ae-6831775eca45
                            [name] => Kultura i rozrywka
                            [count] => 0
                        )

                    [6] => Array
                        (
                            [id] => ea5b98dd-4b6f-4bd0-8c80-22c2629132d0
                            [name] => Moda
                            [count] => 0
                        )

                    [7] => Array
                        (
                            [id] => 3
                            [name] => Motoryzacja
                            [count] => 0
                        )

                    [8] => Array
                        (
                            [id] => 20782
                            [name] => Nieruchomości
                            [count] => 0
                        )

                    [9] => Array
                        (
                            [id] => 3919
                            [name] => Sport i turystyka
                            [count] => 0
                        )

                    [10] => Array
                        (
                            [id] => 258832
                            [name] => Supermarket
                            [count] => 0
                        )

                    [11] => Array
                        (
                            [id] => 1429
                            [name] => Uroda
                            [count] => 0
                        )

                    [12] => Array
                        (
                            [id] => 121882
                            [name] => Zdrowie
                            [count] => 0
                        )

                )

            [path] => Array
                (
                    [0] => Array
                        (
                            [id] => 954b95b6-43cf-4104-8354-dea4d9b10ddf
                            [name] => Allegro
                        )

                )

        )

    [filters] => Array
        (
        )

    [nextPage] => 
)

Problem dokładnie taki sam jak w zamkniętym już wątku: https://github.com/allegro/allegro-api/issues/5852
Sprawdzałem dla kilkudziesięciu EAN , również dla tych podanych w zamkniętym wątku jako działające. Ten EAN 8003437134920 jeszcze w poniedziałek zwracał mi produkty. 

Czy jest jakiś sposób aby znaleźć EAN dla których zwróci mi produkty bez wpisywania w formularzu https://allegro.pl.allegrosandbox.pl/offer/?lokalnie  na chybił trafił?

**Comment by AureliuszBrussy** [comment]
@lukasznurzynski może zdarzyć się, że usuniemy produkty na Sandboxie - żyje ona tak jak baza produktów na produkcji (gdzie także mogą one być usuwane). 

Co do wyszukiwania - możesz alternatywnie wyszukiwać [produkty po frazie](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wyszukac-produkt-z-naszego-katalogu). 

Ostatnią opcją jest także samodzielne tworzenie produktów na swoje potrzeby - wystarczy, że skorzystasz z [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct).

**Comment by lukasznurzynski** [comment]
W tym wypadku pracuję nad czymś co wymaga wyszukiwania po EAN i tylko po nim. Można prosić o podanie chociaż jednego EAN dla którego znajdzie mi produkty na ten moment? To mi wystarczy do samych testów, a jak wspomniałem dotychczasowe EAN mi przestały zwracać cokolwiek. Jednocześnie postaram się w przyszłości skorzystać z opcji tworzenia nowych produktów.

**Comment by AureliuszBrussy** [comment]
@lukasznurzynski przykładowy EAN po którym wyszukasz produkt: 3222764557089.

**Comment by lukasznurzynski** [comment]
Dziękuję za pomoc
