### ISSUE TITLE
Nadpisywanie parametrów produktu podczas wystawiania lub aktualizacji oferty

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#5913]
Witam,

Czy istnieje możliwość nadpisywania części parametrów, które są przypisane do produktu bez zgłaszania błędu przez formularz/API? Chodzi mi o sytuację jak dla tej oferty:

https://allegro.pl/oferta/kamera-zewnetrzna-3-6-1080p-full-2mpx-ir-25m-ip66-7836243054?snapshot=MjAyMi0wNy0xNVQxNTowMzoxNS4wNDlaO3NlbGxlcjtmY2RjZmVmOWZhMzA1ZjUxZDQxMDQ5MWJlNDZhY2NjMjhkNjQxZmE2NzA2OGFmODU1YTZmN2EwZDY5MmYyNGQ0

Do oferty przypisany jest produkt, który w liście  z załączonym wyposażeniem ma przypisany sklad, ale dla kompletnego zestawu CCTV, a oferty dotyczy tylko kamery. Czy jest możliwość, żeby ominąć na przykład taki parametr z produktu i nadpisać go innymi danymi w trakcie wystawiania/aktualizacji parametrów oferty?

**Comment by AureliuszBrussy** [comment]
Możesz nadpisywać podczas wystawiania oferty parametry produktu, które (w odpowiedzi dla [GET sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)) w polu **parameters[].options.identifiesProduct** zwracają wartość **false**. W innym wypadku pozostaje tylko wysłanie propozycji zmiany w produkcie.

**Comment by Himon-SYNCRAFT** [comment]
Rozumiem. Dziękuje za pomoc :)
