### ISSUE TITLE
Czy dziś są jakieś problemy z rozłączaniem kont Allegro?

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#5914]
Dziś pojawiło się nietypowo dużo problemów z połączeniem kont Allegro. Czy u Was coś poszło nie tak?

**Comment by tomasz-grzesik** [comment]
Np. przy odświeżeniu tokena kod błędu 103.

**Comment by tomasz-grzesik** [comment]
Wygląda na błąd po stronie Allegro. Czy te połączenia zostaną przywrócone, czy jednak konieczna jest interwencja Użytkownika?

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję tę sytuację. Wrócę z informacją, jak tylko uda się ustalić więcej szczegółów.

**Comment by magik092** [comment]
Wiadomo już coś? Obecnie leży całe połączenie z Allegro bardzo dużej ilości naszych klientów ...

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że wczoraj między ok. 14:25 a 14:40 wystąpiła awaria po naszej stronie, która spowodowała problemy z autoryzacją części użytkowników. Wygenerowane wcześniej tokeny utraciły już ważność, konieczna jest ponowna autoryzacja aplikacji przez użytkowników w celu wygenerowania nowych par. Raz jeszcze przepraszam za związane z tym trudności, z którymi musieliście się wczoraj mierzyć.

**Comment by tomasz-grzesik** [comment]
Proszę zrobić wszystko, aby taka sytuacja nie miała już miejsca.

**Comment by PrzemyslawLukanowski** [comment]
Oczywiście. Wiemy, jakie jest źródło problemu, zatem dopełnimy wszelkich starań, aby to się już nie powtórzyło.
