### ISSUE TITLE
Provided EAN (GTIN) code is incorrect;Value is too short in parameter (225693)

### ISSUE THREAD

**Issue by yx252419** [allegro/allegro-api#5915]
My ean is 0783162772762. Why is an error reported   Provided EAN (GTIN) code is incorrect;Value is too short in parameter (225693)

**Comment by PrzemyslawLukanowski** [comment]
This GTIN seems to be ok. Could you please send us the trace-id related to this error message?

**Comment by yx252419** [comment]
> 这个 GTIN 似乎没问题。您能否将与此错误消息相关的跟踪 ID 发送给我们？

The ID cannot be provided temporarily. This error exists in many products, such as 0783175015207  0783175279739    0783175275434

**Comment by PrzemyslawLukanowski** [comment]
I couldn't recreate this error and I cannot find any logs with the usage of these EANs. In this case, we will need a trace-id or you can send us a sample request and response via [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b). Please add information that the data refers to the #5915 GitHub thread and also include the seller login.

Are you sure you are sending the proper values? I'm asking cause I have noticed this kind of error in our logs for merchant P__ove, ba___ze and some others, but the provided value in the parameter 225693 is "inna", "N/A"or "1".
