### ISSUE TITLE
Blokada: endpoint : order/sale/offers/<id>

### ISSUE THREAD

**Issue by TECHMED2007** [allegro/allegro-api#5917]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

**Comment by TECHMED2007** [comment]
llegro z jakiś względów zablokowało: endpoint : order/sale/offers/<id>, który Linker wykorzystuje przy pobieraniu zamówienia do pobrania informacji o produktach.
Ze względu na otrzymywanie odpowiedzi jak poniżej, nie dostawaliśmy informacji dla nas niezbędnych czyli poprawnego SKU oraz EAN, przez co nie mogliśmy realizować zamówień na magazynie.


Request po dane produktowe:

[https://api.allegro.pl/order/sale/offers/<id](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.allegro.pl%2Forder%2Fsale%2Foffers%2F%253cid&data=05%7C01%7Cmzakrzewski%40inpost.pl%7C51e9e19e733d43963fda08da6ae46ee1%7C4accae757b724994b3affd3e713e0edb%7C1%7C0%7C637939826621717635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1x7pm%2FtjLd7KOKslHuCSoYwIDsm8KQk7ooqhKI8UhxE%3D&reserved=0)>

Response:

{

    "errors": [

        {

            "code": "NotFoundException",

            "message": "Not found",

            "details": null,

            "path": null,

            "userMessage": "Function is not available. Contact the author of the application."

        }

    ]

}

**Comment by TECHMED2007** [comment]
Proszę o pilne usunięcie problemu.

**Comment by PrzemyslawLukanowski** [comment]
Taki endpoint jak /order/sale/offers/{offerId} nie istnieje. Rozumiem, że chodzi Tobie o /sale/offers/{offerID}, który działa prawidłowo - wystarczy, że zmienisz ścieżkę URL w swoim żądaniu.

**Comment by wap18** [comment]
@PrzemyslawLukanowski 

odkryliśmy problem w innym miejscu, mianowicie po odpytaniu endpointu: 
sale/categories/<categoryID>/parameters
zmieniła się nazwa parametru o ID : 225693.
Wcześniej parametr nazywał się EAN teraz jest to natomiast "name": "EAN (GTIN)".
Czy jest to parametr predefiniowany przez Allegro w API czy jest on modyfikowalny?

**Comment by PrzemyslawLukanowski** [comment]
Tak, potwierdzam, że zmieniliśmy nazwę tego parametru. 
Co masz na myśli przez to, czy jest modyfikowalny? Wartość tego parametru możesz zdefiniować na etapie tworzenia nowego produktu. Jeśli produkt istnieje w naszym Katalogu, posiada uzupełniony ten parametr, to w takiej sytuacji nie możesz go modyfikować.

**Comment by wap18** [comment]
Gdzie zatem mogę znaleźć informację na temat zmian? 
Macie jakiegoś changeloga gdzie takie zmiany są widoczne? 
Poprzez zmianę nazwy parametru nie mogliśmy odpowiednio zmapować produktów z zamówień które pochodzą z Allegro. Spowodowało to u nas masę ręcznej pracy.

**Comment by PrzemyslawLukanowski** [comment]
Identyfikatory parametrów i ich nazwy (w tym przypadku dużo rzadziej) mogą się zmieniać i nie informujemy o zdarzeniach tego typu. Zmiany w parametrach możesz śledzić, aktualizując je za pomocą GET /sale/categories/{categoryId}/parameters, o czym wspominamy w [naszym poradniku:](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe) 

> Parametry pobieraj, sprawdzaj i aktualizuj, w szczególności te słownikowe, bo mogą zmieniać się ich wartości.
