### ISSUE TITLE
Czy dzisiaj są problemy z zamawianiem przesyłek SMART przez wysyłam z allegro poprzez API?

### ISSUE THREAD

**Issue by skmaksio** [allegro/allegro-api#5918]
Dostaję dzisiaj cały czas zamawiając InPost Paczkomaty SMART przez API wysyłam z allegro:

Array
(
    [id] => d21b9306-a0a6-a6a3-30be-c18e907d252b
    [parcelId] =>
    [status] => ERROR
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ERROR
                    [message] => Carrier API timeout.
                    [details] =>
                    [path] => /parcel-management/parcel-create-commands/{commandId}
                    [userMessage] => Upłynął termin oczekiwania na odpowiedź z API w związku z tym przesyłka nie została zamówiona
                )

        )

)

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że wczoraj miały miejsce chwilowe problemy techniczne po stronie przewoźnika. Aktualnie problem nie powinien występować, możesz powtórzyć próby utworzenia przesyłek.
