### ISSUE TITLE
Błąd przy wystawianiu akcji Błędny tag "delete", dozwolone są: {b, p}

### ISSUE THREAD

**Issue by DamianKAtomStore** [allegro/allegro-api#5919]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
endpoint: /sale/offers

Response:
```
(
    [return] => Array
        (
            [faultstring] => Błędny tag "delete", dozwolone są: {b, p}
        )

)
```
Nie mogę wystawić żadnej aukcji tym endpointem, bo dostaję taką zwrotkę. Pomimo, że w żadnym inpucie nie wysyłam tagu "delete" w requescie, czy jest to problem globalny?

**Comment by PrzemyslawLukanowski** [comment]
Nie udało mi się powtórzyć tego problemu. Czy możesz podać trace-id wywołania, które generuje ten błąd w Twoim przypadku? Musimy zweryfikować wysyłaną przez Ciebie strukturę, aby przeanalizować źródło błędu.
