### ISSUE TITLE
Wystawianie zestawów

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5920]
Gdy zadaje zapytania na temat oferty:
12314526486
otrzymuje
 ["id"]=>
  string(11) "12314526486"
  ["name"]=>
  string(19) "Szablon do montażu"
  ["category"]=>
  object(stdClass)#4 (1) {
    ["id"]=>
    string(6) "321125"
  }
  ["product"]=>
  NULL
  ["parameters"]=>
  array(1) {
    [0]=>
    object(stdClass)#8 (4) {
      ["id"]=>
      string(5) "11323"
      ["valuesIds"]=>
      array(1) {
        [0]=>
        string(7) "11323_1"
      }
      ["values"]=>
      array(0) {
      }
      ["rangeValue"]=>
      NULL
    }
  }
i następnie  
["id"]=>
  string(11) "12314526390"
  ["name"]=>
  string(9) "Poziomica"
  ["category"]=>
  object(stdClass)#4 (1) {
    ["id"]=>
    string(5) "15997"
  }
  ["product"]=>
  NULL
  ["parameters"]=>
  array(1) {
    [0]=>
    object(stdClass)#8 (4) {
      ["id"]=>
      string(5) "11323"
      ["valuesIds"]=>
      array(1) {
        [0]=>
        string(7) "11323_1"
      }
      ["values"]=>
      array(0) {
      }
      ["rangeValue"]=>
      NULL
    }
i wystawiam zestaw
"name": "Obraz drukowany Rzeka Clutha w Nowej...90x60",
    "category": {
        "id": "110911"
    },
    "productSet": [
        {
            "product": {
                "id": "5687c81a-dfa1-4a9d-9ebd-6b0787c30e92",
                "category": {
                    "id": "110911"
                }
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Szablon do montażu",
                "category": {
                    "id": "321125"
                },
                "parameters": [
                    {
                        "id": "11323",
                        "name": "Condition",
                        "values": [
                            "New"
                        ],
                        "valuesIds": [
                            "11323_1"
                        ],
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Poziomica",
                "category": {
                    "id": "15997"
                },
                "parameters": [
                    {
                        "id": "11323",
                        "valuesIds": [
                            "11323_1"
                        ],
                        "values": [],
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": "1"
            }
        }
    ],
    "parameters": [
        {
            "id": "11323",
            "name": "Stan",
            "valuesIds": [
                "11323_1"
            ]
        },
        {
            "id": "229205",
            "name": "Stan opakowania",
            "valuesIds": [
                "229205_340245"
            ]
        }
    ],
    i otrzymuje bląd
"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"productSet[2].product.parameters","userMessage":"Given parameter id `11323:Condition` should no have been passed as `product` parameter."}]}', 'WystawProdukt1Step')

Parametr 11323 otrzymałem jako parametr produktowy z istniejących aukcji i mimo tego system nie chce tego zaakceptować?

No i wyrzuciłem te parametry, to znalazł inny błąd:))

"name": "Obraz drukowany Zielone maki 100x70",
    "category": {
        "id": "110911"
    },
    "productSet": [
        {
            "product": {
                "id": "6e1e0519-db58-4f48-9863-79cabbd530ff",
                "category": {
                    "id": "110911"
                },
                "images": [
                    "https://a.allegroimg.com/original/11cc8d/2ae543c34d45a9149f774461fbee"
                ]
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Szablon do montażu",
                "category": {
                    "id": "321125"
                }
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Poziomica",
                "category": {
                    "id": "15997"
                }
            },
            "quantity": {
                "value": "1"
            }
        }
    ],

i dalej do oferty dodano
 "images": [
        "https://a.allegroimg.com/original/11cc8d/2ae543c34d45a9149f774461fbee,https://a.allegroimg.com/original/11cc8d/2ae543c34d45a9149f774461fbee,https://a.allegroimg.com/original/11cc8d/2ae543c34d45a9149f774461fbee,https://a.allegroimg.com/original/11e69b/03ae46874e92842ae655c1cfcfaf,https://a.allegroimg.com/original/115946/f963937c40199ee6a54b49799dab,https://a.allegroimg.com/original/116039/cdffc12f4a9b9395ab9645b27e22,https://a.allegroimg.com/original/116eb7/02655fb44fb9a01ac58413e33114,https://a.allegroimg.com/original/11cff0/b4fc2c5d409880bfb70d3dbaacea,https://a.allegroimg.com/original/114c7a/54c3dbc142b292fd8f17c105625c,https://a.allegroimg.com/original/11c0b1/21cfa80c4a68aa9fc876a249b570,https://a.allegroimg.com/original/11ff0d/5ee07a274549929e6f91b634d4b9,https://a.allegroimg.com/original/116389/857651654d82bd3764031659f9bf,https://a.allegroimg.com/original/119974/ada56b9446ccb93ea17c6d73636e,https://a.allegroimg.com/original/11a72f/8b5d235445a1913d886ca302b753,https://a.allegroimg.com/original/11a5a1/40d584df45369dc9f8a4f66a1f7d,https://a.allegroimg.com/original/11c36d/e36607d240fda008c2b3bd6568b1,https://a.allegroimg.com/original/11ad75/dd6c3e784933b34ba48dbe7e60d6"
    ],
no i  błąd
errors":[{"code":"ProductValidationException","message":"At least one image should be attached to add product.","details":null,"path":"productSet[1].product","userMessage":"Wymagane jest co najmniej 1 zdjęcie."}]}
do każdego produktu w zestawie mam dodawac grafiki?

**Comment by AureliuszBrussy** [comment]
W kategorii 321125 (dla [GET sale/categories/321125/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2)) dla parametru 11323 zwracamy **"describesProduct": false** - to w ten sposób ustalisz, czy dany parametr jest ofertowy czy produktowy. Więcej o parametrach ofertowych przeczytasz [w poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe). 

Jeżeli nie mamy danego produktu w naszej Bazie Produktów (w związku z tym konieczne jest jego utworzenie) - niezbędne jest przekazanie co najmniej jednego zdjęcia w sekcji produktowej.

**Comment by Zbigi** [comment]
Najpierw wystawiłem te dodatki, ale nie zostały utworzone produkty i teraz muszę z tym walczyć, Gdy mam produkty id, to szybko idzie ale tak to jest makabra

**Comment by Zbigi** [comment]
Mam następujący problem. Chcę wystawiać zestawy składające się z obrazu w kat. 127509, szablon do montażu wystawiony jest kategorii 321125 oraz poziomicy  kat. 15997.  Gdy wystawiam, to otrzymuję błąd
errors":[{"code":"ParameterIdNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[1].product.parameters","userMessage":"Given parameter id `127509` has not been found in category `110911`."}]
i jest to prawda, ponieważ parametr `127509` jest w kategorii 321125 i jak go nie podam, to mam błąd, że brak tego parametru.
"name": "Obraz drukowany Rzeka Clutha w Nowej...90x60",
    "category": {
        "id": "110911"
    },
    "productSet": [
        {
            "product": {
                "id": "5687c81a-dfa1-4a9d-9ebd-6b0787c30e92",
                "category": {
                    "id": "110911"
                },
                "images": [
                    "https://a.allegroimg.com/original/11220f/241d6aaa491b90c36556cffde3c0"
                ],
                "parameters": [
                    {
                        "id": "16300",
                        "name": "Sposób wykonania",
                        "valuesIds": [
                            "16300_1"
                        ]
                    },
                    {
                        "id": "17448",
                        "name": "Waga produktu z opakowaniem jednostkowym",
                        "values": [
                            "2.5"
                        ]
                    },
                    {
                        "id": "207442",
                        "name": "Format",
                        "valuesIds": [
                            "207442_232114"
                        ]
                    },
                    {
                        "id": "216161",
                        "name": "Tematyka",
                        "valuesIds": [
                            "216161_273501"
                        ]
                    },
                    {
                        "id": "218845",
                        "name": "Kolor ramy",
                        "valuesIds": [
                            "218845_283145"
                        ]
                    },
                    {
                        "id": "224017",
                        "name": "Kod producenta",
                        "values": [
                            "2371A_3B"
                        ]
                    },
                    {
                        "id": "23088",
                        "name": "Materiał ramy",
                        "valuesIds": [
                            "23088_7"
                        ]
                    },
                    {
                        "id": "24148",
                        "name": "Materiał wykonania",
                        "valuesIds": [
                            "24148_2"
                        ]
                    },
                    {
                        "id": "245545",
                        "name": "Wysokość produktu",
                        "values": [
                            "60"
                        ]
                    },
                    {
                        "id": "245549",
                        "name": "Szerokość produktu",
                        "values": [
                            "90"
                        ]
                    },
                    {
                        "id": "247829",
                        "name": "Cechy dodatkowe",
                        "valuesIds": [
                            "247829_815391"
                        ]
                    },
                    {
                        "id": "248811",
                        "name": "Marka",
                        "values": [
                            "Fideli"
                        ],
                        "valuesIds": [
                            "248811_950468"
                        ]
                    }
                ]
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Szablon do montażu",
                "category": {
                    "id": "321125"
                },
                "images": [
                    "https://a.allegroimg.com/original/11d651/19777a6f4170a0a5949169330316"
                ],
                "parameters": [
                    {
                        "id": "127509",
                        "name": "Marka",
                        "values": [
                            "Fideli"
                        ],
                        "valuesIds": [
                            "127509_30"
                        ]
                    },
                    {
                        "id": "17448",
                        "name": "Waga produktu z opakowaniem jednostkowym",
                        "values": [
                            "0.1"
                        ]
                    },
                    {
                        "id": "205053",
                        "name": "Materiał",
                        "valuesIds": [
                            "205053_222353"
                        ]
                    },
                    {
                        "id": "224017",
                        "name": "Kod producenta",
                        "values": [
                            "Szab_1"
                        ]
                    }
                ]
            },
            "quantity": {
                "value": "1"
            }
        },
        {
            "product": {
                "name": "Poziomica",
                "category": {
                    "id": "15997"
                },
                "images": [
                    "https://a.allegroimg.com/original/11ee32/43487b7b405daec0a968c5273e6e"
                ],
                "parameters": [
                    {
                        "id": "17448",
                        "name": "Waga produktu z opakowaniem jednostkowym",
                        "values": [
                            "0.1"
                        ]
                    },
                    {
                        "id": "224017",
                        "name": "Kod producenta",
                        "values": [
                            "Poz_1"
                        ]
                    },
                    {
                        "id": "248811",
                        "name": "Marka",
                        "values": [
                            "Fideli"
                        ],
                        "valuesIds": [
                            "248811_950468"
                        ]
                    }
                ]
            },
            "quantity": {
                "value": "1"
            }
        }
    ],
i co teraz?

**Comment by AureliuszBrussy** [comment]
@Zbigi jest to błąd po stronie naszej usługi. Wrócę z informacją po wdrożeniu poprawki - aktualnie nie jestem w stanie wskazać dokładniejszego czasu naprawy.
