### ISSUE TITLE
POST sale/product-offers OfferImagesNotFoundException przy powiązaniu bez zdjęć

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#5921]
Dzień dobry,

Mam problem z zasobem POST sale/product-offers - chodzi o wystawienie oferty powiązanej z istniejącym produktem Allegro. Nie przesyłam zdjęcia ani opisu (images, description, product_set[0].images nie są przysyłane). Produkt w Allegro ma zdjęcie.

Serwer produkcyjny.
`POST sale/product-offers || trace-id:6c8fdb4d8335a497`

Response
```
    +"code": "OfferImagesNotFoundException"
    +"message": "Provided image address is incorrect."
    +"details": "OfferImagesNotFoundException"
    +"path": null
    +"userMessage": "Podany adres obrazka jest nieprawidłowy."
```

Czy to prawidłowe zachowanie?

**Comment by AureliuszBrussy** [comment]
@Radeq w opisie tego produktu w naszej bazie znajduje się zdjęcie, które nie jest umieszczone w galerii tego produktu. Zgłosiłem to do poprawki odpowiedniemu zespołowi. Wrócę z informacją po poprawce.

**Comment by Radeq** [comment]
@AureliuszBrussy , ok, dziękuję i czekam na aktualizację, znalazłem jeszcze inny produkt

`POST sale/product-offers || trace-id:1941b90634a41410`

**Comment by AureliuszBrussy** [comment]
@Radeq dziękuję, zgłosiłem i te produkty.

**Comment by AureliuszBrussy** [comment]
@Radeq edytowaliśmy te produkty. Nie powinno być już problemu z ich wykorzystaniem.

**Comment by Radeq** [comment]
@AureliuszBrussy , zgłaszane oferty przeszłe ale czy to nie jest bardziej problem globalny? Mam problemy z innymi klientami, produkty w różnych kategoriach. Przykład

`POST sale/product-offers || trace-id:32cb64b000942767`

`POST sale/product-offers || trace-id:c0b10fc110a304a0`

Jeszcze jeden ciekawy przypadek - również skorzystałem z zasobu `POSt sale/product-offers` 

`GET sale/offers/12389640385? || trace-id:7a0df14e522e17ad` - proszę spojrzeć na podgląd oferty - brak zdjęć. To również niejedyny przypadek.

**Comment by AureliuszBrussy** [comment]
@Radeq tak, potwierdzam, takich produktów może być więcej - jest to szerszy problem, pracujemy nad naprawą. 

Przypadek z brakującymi zdjęciami w ofercie to inny błąd - o tym także wiemy i również pracujemy nad naprawą.

**Comment by Radeq** [comment]
@AureliuszBrussy , jak idą prace nad rozwiązaniem problemu z wystawieniem oferty? Mam kolejnych klientów z tym samym błędem.

**Comment by AureliuszBrussy** [comment]
@Radeq nie, jeszcze nie mam potwierdzenia rozwiązania problemu. Gdy tylko coś się zmieni - wrócę z informacją.

**Comment by Radeq** [comment]
@AureliuszBrussy , czy błąd został już naprawiony?

**Comment by AureliuszBrussy** [comment]
@Radeq mam informacje, że problem nie powinien występować. Czy w ostatnim czasie spotkałeś się z podobnymi przypadkami?

**Comment by Radeq** [comment]
@AureliuszBrussy , tak dalej mam problem

```
POST sale/product-offers || trace-id:8d9d1da95e9a0be3
POST sale/product-offers || trace-id:6da7025c61ad3011
POST sale/product-offers || trace-id:a3a435a5ffb43a65
```

**Comment by AureliuszBrussy** [comment]
@Radeq dziękuję za nowe przykłady - jeszcze raz poruszyłem ten temat z odpowiednim zespołem. Wrócę z informacjami.

**Comment by winyle-online** [comment]
Wygląda na to, że mam ten sam problem.
trace-id: c9756bb4100f96d7

**Comment by Lukasz-Zurek** [comment]
@winyle-online Zgłosiłem dalej do weryfikacji. Wkrótce wrócę do Ciebie z informacją.

**Comment by winyle-online** [comment]
Dziękuję. 
Sprawdzę dzisiaj późnym popołudniem i jakby co, to będę miał jeszcze kilka takich produktów z tym samym błędem.
Wkleję je później tutaj.

**Comment by Lukasz-Zurek** [comment]
@winyle-online Ok, dziękuję.

**Comment by winyle-online** [comment]
W tym wcześniejszym udało się już dodać :)

Mam jeszcze trzy, które zwróciły ten sam błąd:
trace-id: fdb3863a6d2e266a
trace-id: fec9bacd031de8eb
trace-id: ef071db36b64ae6e

**Comment by Lukasz-Zurek** [comment]
@winyle-online Dziękuję za kolejne przykłady. Zgłosiłem je do poprawki.

**Comment by Lukasz-Zurek** [comment]
@winyle-online Problem dla tych konkretnych przypadków nie powinien już występować.
