### ISSUE TITLE
Brak dostępu do 'Wysyłam z Allegro' przy użyciu client token

### ISSUE THREAD

**Issue by R3VANEK** [allegro/allegro-api#5922]
Witam.

Przy próbie wysłania zapytania na url https://api.allegro.pl/parcel-management/delivery-services dostaję taki komunikat:
```
 "errors": [
        {
            "code": "AUTHENTICATION_ERROR",
            "message": "No access to 'Wysyłam z Allegro'",
            "details": null,
            "path": "header.authorization",
            "userMessage": "Brak dostępu do 'Wysyłam z Allegro' przy użyciu client token"
        }
    ]
```
wcześniej odpowiednio wygenerowałem token dostępu na koncie produkcyjnym. Upewniłem się też po jego dekodowaniu, że ma prawidłowo nadane uprawnienie allegro:api:orders:read do tego requestu. W momencie otrzymywania błędu nie stracił też ważności

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Aby korzystać z tego zasobu powinieneś korzystać z **bearer-token-for-user** (token użytkownika, a nie aplikacji), czyli token wygenerowany za pomocą [Authorization Code flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [Device flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow), a nie za pomocą Client_credentials flow.
