### ISSUE TITLE
Ten sam request w 2 jezykach, w jednym nie działa "Offer not found. It was deleted, archived or never existed."

### ISSUE THREAD

**Issue by 000shadow** [allegro/allegro-api#5923]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Próbuję wykonać ten sam request w Python oraz VBA. W Pythonie otrzymuję prawidłowy respond, a w VBA dostaję błąd:  

`{"errors":[{"code":"NOT_FOUND","message":"Offer not found. It was deleted, archived or never existed.","details":"NOT_FOUND","path":"/error","userMessage":"Offer not found. It was deleted, archived or never existed."}]}
}]}`

Skrypt Python:
```
headers = {
        'Authorization': 'Bearer exampleToken',
        'accept': 'application/vnd.allegro.public.v1+json',
        'content-type': 'application/vnd.allegro.public.v1+json'
    }

response = requests.get('https://api.allegro.pl/sale/offers/exampleOfferId', headers=headers)
```

Skrypt VBA:
```
Public Sub Macro1()
    Dim MyRange As Range
    Dim MyCell As Range
    Dim OfferId As String
    Dim Token As String
    
    ' Pod A2 jest token
    Token = Range("A2").Value
    ' 1 aktywna komórka jest zaznaczona i jest tam OfferId
    Set MyRange = ActiveSheet.UsedRange
    
    For Each MyCell In MyRange
        OfferId = MyCell
        Dim request As New WinHttpRequest
        request.Open "Get", "https://api.allegro.pl/sale/offers/ & OfferId"
        request.SetRequestHeader "Authorization", "Bearer " & Token
        request.SetRequestHeader "accept", "application/vnd.allegro.public.v1+json"
        request.SetRequestHeader "content-type", "application/vnd.allegro.public.v1+json"
        request.Send
        
        If request.Status <> 200 Then
            Debug.Print request.ResponseText

            Exit Sub
        End If
        
        Dim response As Object
        Set response = JsonConverter.ParseJson(request.ResponseText)
        Debug.Print response
    
    Next MyCell
    
End Sub
```

**Comment by dlis2010** [comment]
Zerknij jak doklejasz offerId w adresie który odpytujesz.

**Comment by PrzemyslawLukanowski** [comment]
Jak wspomniał wyżej @dlis2010, prawdopodobnie offerID nie jest prawidłową wartością w drugim wywołaniu. Możesz wskazać nam trace-id tego żądania, sprawdzimy wtedy, jak to wygląda po naszej stronie.

**Comment by hahyes** [comment]
> "https://api.allegro.pl/sale/offers/ & OfferId"

Tak powinno być:
"https://api.allegro.pl/sale/offers/" & OfferId
