### ISSUE TITLE
Pobieranie obrazków z zewnętrznego adresu

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#5924]
[code] => UploadImageRequestTimeoutException
[message] => Request Timeout
[details] => 
[path] => 
[userMessage] => The time limit for downloading an image from the address xxxxxxxxxxxx has been exceeded.

Jaki może być powód takiego błedu, obrazek ma 800kb, wiec nie jakiś wielki, serwer na którym leży obrazek nie jest obciążony, a mimo to dzisiaj co 2 -3 aukcje przy edycji spotyka powyższy problem.

**Comment by PrzemyslawLukanowski** [comment]
Prześlij nam proszę przykładowe requesty wraz z odpowiedziami przez nasz[ formularz kontaktowy.](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) Dopisz, że dane dotyczą wątku #5924. Zweryfikujemy tę sytuację.
