### ISSUE TITLE
Business account in sandbox

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#5925]
Hi,
I am having trouble activating my business account on sandbox. I did went thru mock payment, but I am still unable to finish activation. I have noticed, you had to activate the account in the past, but I moght be missing something. Please advice.

Thanks

Jirka (sandbox) Client: zajdalen

**Comment by PrzemyslawLukanowski** [comment]
Hi, I have activated your account. The last step - go to the [Settlements with Allegro](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) tab and use our payment simulator to settle the bill on your account.

**Comment by ZajdaBear** [comment]
All is good, thanks for your help!
