### ISSUE TITLE
 znaczniki tekstu API Allegro

### ISSUE THREAD

**Issue by KETRINAPL** [allegro/allegro-api#5927]

**Comment by KETRINAPL** [comment]
Dzień dobry. Proszę mi powiedzieć, jakie znaczniki tekstu obsługuje Allegro przez API ? Nie możemy przekazać opisu tekstu w pogrubionej czcionce, jest blokada od Allegro.

**Comment by asoio** [comment]
https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy#opis-ogloszenia
3. Możesz użyć pogrubienia < b > < /b > w znacznikach:
- < p > < /p > - akapit
- < ul > < /ul > - lista wypunktowana
- < ol > < /ol > - lista numerowana

**Comment by Lukasz-Zurek** [comment]
@KETRINAPL Zgodnie z sugestią od **asoio** - skorzystaj ze wskazanych w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-wystawic-i-zarzadzac-ogloszeniem-K6r3Z47dKcy#opis-ogloszenia) znaczników.
