### ISSUE TITLE
Allegro ONE - czy da się pobrać tracking number od przewoźnika docelowego

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#5928]
Dzień dobry,

korzystamy z Allegro ONE, gdzie paczki dostarcza np. UPS.

Czy jest jakaś możliwość pobrania tracking number UPS przez REST API?

Obecnie musimy wchodzić do panelu administracyjnego Allegro żeby to sprawdzić ręcznie, i wysłać klientowi.

Niestety nie widzę tego w danych zwracanych z [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails)

Jest tam waybill, ale to jest waybill systemu Allegro ONE a nie UPS, i nie można go użyć w systemie UPS aby śledzić paczkę.

Może czegoś nie widzę w dokumentacji i jest jakaś metoda, którą można to pobrać przez REST API?

**Comment by tztztztz** [comment]
Czy przewidujecie w przyszłości możliwość pobrania tracking number przewoźnika który faktycznie wykonuje usługę?

**Comment by PrzemyslawLukanowski** [comment]
Mamy w planach dodać endpoint, za pomocą którego pobierzesz także historię statusów innych przewoźników z Wysyłam z Allegro. W przypadku Allegro ONE prawdopodobnie pozostanie to w obecnej formie, będziemy udostępniać drogę przesyłki tylko na podstawie naszego numeru waybill. Więcej szczegółów będziemy mogli podać dopiero kiedy funkcjonalność zostanie przez nas upubliczniona - na ten moment nie mogę jeszcze wskazać konkretnej daty.

**Comment by tztztztz** [comment]
Ok, tylko nam akurat nie zależy na historii innego przewoźnika, chcemy tracking number UPS-u, tak żeby nasz klient mógł go wprowadzić na stronie UPS i tam sprawdził sobie aktualny status paczki.

**Comment by PrzemyslawLukanowski** [comment]
W tym przypadku nie planujemy dodatkowych zmian.

**Comment by tztztztz** [comment]
Generalnie nasz problem też polega na tym, że po zeskanowaniu etykiety z takiej paczki allegro ONE otrzymujemy kody z UPS, a nie waybill lub parcel id z Allegro ONE i przez to nie możemy skojarzyć zeskanowanej paczki z zamówieniem, to nam bardzo utrudnia pracę z tymi paczkami.

Gdyby po zeskanowaniu kodu, był tam parcel id lub waybill z allegro bardzo by to nam pomogło.

**Comment by tztztztz** [comment]
Tam n a etykiecie co prawda jest waybill z allegro one, ale tekstowo, tego skaner kodów paskowych niestety nie odczyta, a chodzi o automatyzację pracy.

**Comment by PrzemyslawLukanowski** [comment]
Przekazałem Twoją sugestię do zespołu odpowiedzialnego za usługę. Poinformuję w wątku, jeśli zdecydujemy się wprowadzić zmiany.

**Comment by tztztztz** [comment]
Rozwiązanie byłoby jedno z dwóch:

1) Umożliwienie pobrania przez REST API tego kodu paczki który pojawia się po zeskanowaniu kodu kreskowego
I/LUB
2) Kod kreskowy zwraca oprócz numeru z UPS, także dodatkowo w jakiś sposób waybill lub parcel id z Allegro ONE

sensowniejsze wydaje się 1, może zmienicie zdanie, i jednak umożliwicie pobranie tego przez REST API - to by nam bardzo pomogło.
