### ISSUE TITLE
Problem ze wznowieniem oferty poprzez API

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5930]
Potrzebuję pomocy, ponieważ doszedłem już do ściany. Do tej pory nie miałem problemów ze wznawianiem ofert poprzez API (problem występuje na sandbox oraz na allegro produkcyjnym)

Korzystam z /sale/product-offers/

1. Wystawiam ofertę, następnie ją zakańczam.
2. Wykonuję wznowienie /sale/product-offers/ (zmiana statusu na Active)
3. Wykonuję aktualizację ceny oraz ilości sztuk — tutaj pojawia się problem, ponieważ wznowiona oferta automatycznie zostaje zakończona. Oczywiście dane zostały zaktualizowane, ale oferta, zamiast pozostać wznowiona, zakańcza się.

Wcześniej nie było z tym problemów. Na sandbox wystawiłem ofertę numer: 7691954912

Może pomoże to zdiagnozować problem. Nie mam pojęcia, dlaczego oferta sama się zakańcza.

Powyższa oferta została wystawiona -> zakończona -> wznowiona -> aktualizacja ceny -> aktualizacja ilości sztuk — po tych czynnościach powinna pozostać aktywna (przez kilka sekund była), niestety wróciła do zakończonych

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowy opis sytuacji. Sprawę przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Doszło tutaj do błędu po naszej stronie, za co serdecznie przepraszamy. Pracujemy obecnie nad poprawką, dzięki której unikniemy tego typu sytuacji w przyszłości.

**Comment by mateuszcom** [comment]
Kiedy mniej więcej mogę spodziewać się poprawki?

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Trudno mi określić konkretną datę wdrożenia poprawki. Z całą pewnością jest to temat priorytetowy. Jak tylko uzyskam konkretne informacje - podzielę się nimi w tym wątku.

**Comment by mateuszcom** [comment]
W takim razie jakaś podpowiedź, w jaki sposób przez ten czas skutecznie wznawiać oferty?

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Aby uniknąć nieścisłości od razu doprecyzuję, że nie jest to globalny problem, w związku z czym powinieneś mieć możliwość wznawiania ofert. Napisz proszę jednak czy są to częste przypadki? Czy jesteś w stanie przesłać nam przykładowe oferty ze środowiska produkcyjnego?

**Comment by mateuszcom** [comment]
W tym jest problem, że wznawianie nie działa praktycznie wcale. Dwa przykładowe numery ofert z Allegro produkcyjnego: 12150944860 oraz 12128848807 (są to dwa różne konta)

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Dziękuję. Informacje przekazałem dalej do zespołu, który pracuje nad poprawką.

**Comment by mateuszcom** [comment]
Czy coś wiadomo na temat daty wdrożenia poprawki?

**Comment by MartaNowaczyk** [comment]
Ustalam to z odpowiednim zespołem. Dam znać jak otrzymam informacje.

**Comment by mateuszcom** [comment]
Nadal nie otrzymałem od Państwa żadnej informacji. Proszę zatem o sprecyzowanie czy problem występuje wyłącznie dla zasobów /sale/product-offers/ ? Czy w przypadku korzystania z poniższych zasobów problem nie będzie występował?

/sale/offer-publication-commands
/sale/offer-quantity-change-commands
/sale/offer-price-change-commands

Dodatkowo proszę o informację czy nie jest planowane wyłączenie powyższych zasobów od 2024 roku? Pytam, ponieważ zachęcali Państwo na przejście na /sale/product-offers, ponieważ analogiczne (starsze zasoby) są przeznaczone do zamknięcia, dla tego moje pytanie

**Comment by Lukasz-Zurek** [comment]
Tak, obecny problem dotyczy /sale/product-offers/ - tutaj dodam, że problem jest skomplikowany i wdrożenie poprawki wymaga czasu. Odpowiedni zespół cały czas nad tym pracuje.

W przypadku korzystania z pozostałych - problem nie powinien występować. Nie planujemy również wyłączenia wskazanych zasobów. Gdyby coś się zmieniło w tym temacie, to z pewnością poinformujemy o tym znacznie wcześniej, tak jak to miało miejsce właśnie z [tym newsem](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW).

**Comment by Lukasz-Zurek** [comment]
@mateuszcom Wdrożyliśmy poprawkę, w związku z czym problem nie powinien już występować.

**Comment by mateuszcom** [comment]
Dziękuję za informację
