### ISSUE TITLE
update product quantity

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5931]
Hello,

These two have the same json structure and worked recently, one has no errors but the other returns "bad request...".
trace-id: d442f311d1e2e14b  "code":"BAD_REQUEST","message":"Message is not readable."...
trace-id: 92e16585cc18403e  no error

i need your help, thanks

**Comment by Lukasz-Zurek** [comment]
Please make sure that your trace-ids are correct. If you still get an error, please send a sample request and response via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Please add GitHub #5931 to your message. I will verify it as soon as possible.

**Comment by yavuzresif** [comment]
trace-id 3bfe868f245c2f02
offerid:11637173611

json:
{   "items": [     {       "stock": {         "available": 72,         "sold": 0       },       "external": {         "id": "D95C18BB-78EF-49D1-892E-FE8787699B0C"       }     }   ] }

response :{"errors":[{"code":"BAD_REQUEST","message":"Message is not readable.","details":null,"path":"request.body","userMessage":"Invalid request. Please contact the application author."}],"error":null,"error_description":null}

**Comment by Lukasz-Zurek** [comment]
The problem is with a request body. You should provide it like this:

```
      {
         "stock": {
            "available": 72,
            "unit": "UNIT"
         },
         "external": {
            "id": "D95C18BB-78EF-49D1-892E-FE8787699B0C"
      }
      }
```

**Comment by yavuzresif** [comment]
I accidentally shared the json model on my system. As I mentioned before, sometimes the process is successful with the same model, and sometimes I get an error. Can you check the status via trace_id

**Comment by Lukasz-Zurek** [comment]
I have already checked trace-id: 3bfe868f245c2f02 and we return 400 error as well as for your latest requests from today.

I suggest changing your request body. I understand that the process is sometimes successful with the same model - as you have just mentioned above, but you should provide it according to the documentation. Then you shouldn't receive any error and if so - we will report it to another department.
