### ISSUE TITLE
Sandbox - odblokowanie sprzedaży

### ISSUE THREAD

**Issue by sikorag** [allegro/allegro-api#5932]
Proszę o odblokowanie sprzedaży na Allegro Sandbox, moja nazwa użytkownika: grzessik

**Comment by PrzemyslawLukanowski** [comment]
Sprzedaż możesz odblokować samodzielnie za pomocą zakładki [Rozliczenia z Allegro.](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro) Wybierz "Zapłać" i skorzystaj z naszego symulatora płatności.

**Comment by sikorag** [comment]
Zrobiłem to, ale konto nadal jest zablokowane.

**Comment by PrzemyslawLukanowski** [comment]
Sprawdź teraz proszę, już powinno być ok.

**Comment by sikorag** [comment]
Tak, jest już odblokowane, dziękuję.

Jednak gdy klikam "Dodaj nową ofertę" przekierowuje mnie na adres "https://staging-lokalnie.allegrogroup.com/oferty/wystaw" i blokuje z poniższym komunikatem 
![image](https://user-images.githubusercontent.com/38217009/181002443-f35d1f83-5c2a-4f74-925e-6e33b10c3888.png)

**Comment by PrzemyslawLukanowski** [comment]
Skorzystaj proszę w takiej sytuacji z alternatywnego linka - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie.

**Comment by sikorag** [comment]
Dziękuję
