### ISSUE TITLE
Nie działa synchronizacja przez API

### ISSUE THREAD

**Issue by SportPlusPL** [allegro/allegro-api#5933]
Nie działa mi komunikacja z API pomiędzy ShopGold od kilku godzin. Rano jeszcze działało teraz kompletny brak synchronizacji. Bardzo proszę o weryfikację bo nie możemy wystawiać nowych aukcji.

**Comment by PrzemyslawLukanowski** [comment]
Proszę w tym przypadku o kontakt ze wsparciem aplikacji ShopGold. Nie jesteśmy twórcami tego oprogramowania, dlatego nie możemy na ten moment wskazać przyczyny błędu. Jeśli twórcy stwierdzą błąd po naszej stronie, poprosimy wtedy o dane (np. trace-id), które pomogą nam zidentyfikować problem. Na podstawie obecnych informacji jest to niestety niemożliwe.
