### ISSUE TITLE
zmiana statusu zamówienia API - błąd: Function is not available. Contact the author of the application

### ISSUE THREAD

**Issue by ButcherFromHell** [allegro/allegro-api#5934]
Mój response podczas próby zmiany statusu opłaconego zamówienia: 

a:1:{s:6:"errors";a:1:{i:0;a:5:{s:4:"code";s:17:"NotFoundException";s:7:"message";s:9:"Not found";s:7:"details";N;s:4:"path";N;s:11:"userMessage";s:65:"Function is not available. Contact the author of the application.";}}}

```
 $data = array(
           "status" => "PROCESSING"
 );
                            
 $url = "https://api.allegro.pl/order/checkout-forms/{$event['order']['checkoutForm']['id']}/fulfilment";
 $make_call = callAllegroAPI("PUT", $url, $data, $token);
 $response = json_decode($make_call, true);

What am I doing wrong?

**Comment by Lukasz-Zurek** [comment]
Popraw `fulfilment` na **`fulfillment`**.

**Comment by ButcherFromHell** [comment]
Faktycznie - dziękuje.
Ale błąd też jest:
a:1:{s:6:"errors";a:1:{i:0;a:5:{s:4:"code";s:5:"ERROR";s:7:"message";s:11:"Bad Request";s:7:"details";N;s:4:"path";N;s:11:"userMessage";s:11:"Bad Request";}}}

**Comment by Lukasz-Zurek** [comment]
Ze względu na dużą liczbę jezyków programowania, nie świadczymy wsparcia dla każdego z nich.

Możesz nam jednak przesłać request i response w formacie curl przez[ formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). W zgłoszeniu dopisz GitHub[ #5934](https://github.com/allegro/allegro-api/issues/4257).

**Comment by ButcherFromHell** [comment]
Rozumiem, ale postepuje zgodnie z wytycznymi.

**Comment by ButcherFromHell** [comment]
Wysłałem zapytanie.
Czy w requescie jest jeszcze jakiś parametr wymagany?

**Comment by Lukasz-Zurek** [comment]
@ButcherFromHell Dziękuję. Jak tylko je otrzymam - zweryfikuję dokładnie ten przypadek. 

Dodam, że nie wymagamy żadnego dodatkowego parametru.

**Comment by ButcherFromHell** [comment]
Nie otrzymałem, żadnej odpowiedzi drogą mejlową - jedynie informacje że zgłoszenie trafia do odpowiedniego działu. Numer zgłoszenia 25049518.

**Comment by Lukasz-Zurek** [comment]
@ButcherFromHell Niestety to zgłoszenie ostatecznie do nas nie trafiło. Napisałem już do zespołu odpowiedzialnego za obsługę klienta. Przepraszam Cię za utrudnienia z tego powodu.

**Comment by Lukasz-Zurek** [comment]
@ButcherFromHell Zapoznałem się z Twoim zgłoszeniem. Otrzymałem je ze znacznym opóźnieniem i tu w imieniu Serwisu serdecznie Cię przepraszam. Taka sytuacja nie powinna się w ogóle wydarzyć.

Niestety nie mam już możliwości weryfikacji logów, dlatego jeśli ponownie trafisz na ten problem - prześlij proszę request w formacie json oraz trace-id w odpowiedzi na ostatnią wiadomość. Dopilnuję, aby tym razem komunikacja przebiegała tutaj sprawnie.

Raz jeszcze przepraszam Cię za zaistniałą sytuację.

**Comment by ButcherFromHell** [comment]
@Lukasz-Zurek proszę o kontakt @

**Comment by Lukasz-Zurek** [comment]
@ButcherFromHell Ok, działam w tej sprawie.

**Comment by Lukasz-Zurek** [comment]
@ButcherFromHell Skontaktowałem się z odpowiednim zespołem. Wszystko wskazuje na to, że nie otrzymaliśmy od Ciebie nowej wiadomości. Jeśli jest inaczej - podaj proszę numer nowej sprawy. W przypadku, gdy nie tworzyłeś nowej sprawy - napisz proszę poprzez ten [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Nie zwracaj uwagi na temat zgłoszenia, nie jest to tutaj istotne. Zgłoszenie powinno trafić w odpowiednie miejsce, a następnie powinno zostać przekazane do mnie.

Przepraszam za tego typu utrudnienia.
