### ISSUE TITLE
Błąd przy dodawaniu aukcji przez Ido Sell

### ISSUE THREAD

**Issue by admeister1234** [allegro/allegro-api#5936]
Dzień dobry, 

próbuje dodać nowe oferty przez IdoSell i pojawia mi się następujący błąd:

Kod odpowiedzi zwrócony przez API Allegro:
VALIDATION_ERROR

Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
category: Identyfikator kategorii nie może być pusty. description: Do oferty trzeba dodać nowy opis.

Postępowanie:
Jeżeli to możliwe popraw błędne dane, w przeciwnym wypadku kliknij tutaj by skontaktować się z obsługą Allegro w celu wyjaśnienia przyczyny występowania błędu. Poniżej znajdują się załączniki, o które możesz zostać poproszony.
Możesz w ciągu kilku dni przejrzeć ponownie ten błąd otwierając Dziennik zdarzeń

Nie bardzo rozumiem jaki mam dodać nowy opis. Próbowałem już dokonywać zmian i cały czas wyświetla mi się to samo. Tak samo uzupełniam identyfikator kategorii i również błąd się powtarza. 

pozdrawiam
Adrian Zagórski

**Comment by Lukasz-Zurek** [comment]
Najlepiej będzie jak zgłosisz ten problem bezpośrednio do supportu IdoSell. Komunikat wskazuje na problem po stronie ich konfiguracjil. W przypadku problemów po stronie naszego serwisu, support IdoSell będzie mógł zgłosić to już bezpośrednio do nas.

**Comment by admeister1234** [comment]
Ok, dziękuję za informacje!
