### ISSUE TITLE
patch products-offers, dopasowanie tecdoc

### ISSUE THREAD

**Issue by psos** [allegro/allegro-api#5938]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Trace id: 52d18100566be401

Podczas spinania zestawu produktów, który ma wpięte compabilityTable, patch nie potrafi automatycznie dodać tabeli dopasowania (nie podaje tego parametru). Zerknijcie na trace.

array:1 [
  0 => array:5 [
    "code" => "ConstraintViolationException.ValidCompatibilityTable"
    "message" => "Given compatibility table is outdated, use the current one. Update offer with the most recent product data."
    "details" => "ConstraintViolationException.ValidCompatibilityTable"
    "path" => "compatibilityTable"
    "userMessage" => "Wskazana sekcja "Pasuje do" jest nieaktualna, podepnij najnowszą wersję dla tego zestawu produktowego. Zaktualizuj dane produktowe w ofercie."
  ]
]
 ""
\

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za zgłoszenie, weryfikujemy tę sytuację. Dam znać jak tylko uda się coś ustalić.

**Comment by psos** [comment]
I jak tam mordeczki ? :-)

**Comment by MartaNowaczyk** [comment]
Przepraszam, że tak długo czekasz, sprawa jest bardziej skomplikowana niż wynika to z samego komunikatu błędu. Zespół odpowiedzialny za tą funkcjonalność pracuje nad tym. Damy znać, gdy coś się wyjaśni.

**Comment by MartaNowaczyk** [comment]
@psos będziemy zbierać więcej danych na temat takich przypadków. Spróbuj ponownie wysłać PATCHA i daj znać czy już jest ok. Gdyby trafił się jeszcze jakiś przypadek podsyłaj do weryfikacji.

**Comment by psos** [comment]
Tzn ja odkryłem to, że produkty w produktyzacji pewnie różnią sie wersją tecdoca, ale  nie da się wyfiltrować.

**Comment by MartaNowaczyk** [comment]
Dzięki, że się dzielisz :) Tutaj jeszcze dochodzi kwestia zestawów, także to bardziej złożony problem. Oczywiście jak jeszcze coś zauważysz pisz śmiało.
