### ISSUE TITLE
Dzień dobry, jak zintegrować nowe konto Allegro z aplikacją DPD?

### ISSUE THREAD

**Issue by AWHANDEL** [allegro/allegro-api#5939]

**Comment by PrzemyslawLukanowski** [comment]
Wszystkie informacje powinieneś otrzymać od DPD, ponieważ my jako Allegro nie jesteśmy twórcami tej aplikacji. Z tego co widzę, [instrukcja](https://www.dpd.com/pl/pl/oferta-dla-firm/rozwiazania-it/smart-paczka-dpd-integracja-z-allegro-subiekt-sello-i-shoper/) znajduje się na ich stronie internetowej.

**Comment by AWHANDEL** [comment]
OK,
