### ISSUE TITLE
403 Forbidden podczas próby utworzenia oferty wielowariantowej

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#594]
Dzień dobry.

Po dłuższym czasie spędzonym na próbie utworzenia oferty wielowariantowej muszę niestety poprosić o pomoc.

Próbuję utworzyć ofertę wielowariantową i połączyć oferty w kategorii "Kaski" (id: 256717) na podstawie parametru "Rozmiar" (id: 16029). Oferty są oczywiście aktywne, zgromadzone na jednym koncie sprzedawcy w identycznej kategorii.

Wywołuję zasób z wygenerowanym UUIDem v. 4:
`PUT: https://api.allegro.pl/sale/offer-variants/da2b1312-2b33-[1234]-be32-b97a46b0ba51`
W poście podmieniłem fragment numeryczny na [1234] aby nie wprowadzać potencjalnego zamieszania.

Przesyłam nagłówki:
```
Accept: application/vnd.allegro.beta.v1+json
Content-Type: application/vnd.allegro.beta.v1+json
Accept-Language: pl
```
Plus oczywiście Authorization.
Jako body zapytania używam:

`{"name":"testowy-wariant","offers":[{"id":"id-oferty-1"},{"id":"id-oferty-2"}],"parameters":[{"id":"16029"}]}`

W odpowiedzi otrzymuję: 403 Forbidden
```

{
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
            "path": null,
            "userMessage": null
        }
    ]
}
```
Robię sobie testy za pomocą Postmana, ale taki sam efekt uzyskuję również gdy odpalam ten zasób za pomocą PHP.

Zarówno opis statusu jak i komunikat błędu nie naprowadza mnie na rozwiązanie problemu. Oferty, kategorie i parametry spełniają warunki wielowariantowości. Proszę zatem o pomoc.

Z góry dziękuję, pozdrawiam.

**Comment by MarcinLuczak** [comment]
@arkwlcz Dzień dobry

Jaki jest login oraz identyfikator Twojego konta? I które oferty (podaj proszę numery) próbujesz połączyć?

Spróbuj także połączyć te oferty bezpośrednio w [tym narzędziu](https://allegro.pl/variants-editor-web/), a potem pobierz taką ofertę wielowariantową za pomocą metody GET na zasobie /sale/offer-variants/{setId}. Opisaliśmy ten proces w [tym miejscu](https://developer.allegro.pl/news/2018-07-09-Wielowariantowosc/#04).

Identyfikator oferty wielowariantowej (który musisz podać w requeście w tym zasobie) odczytasz w URL-u, gdy będziesz edytował taką ofertę w tym narzędziu.

**Comment by arkwlcz** [comment]
Witam ponownie.

Stosując się do porad, użyłem narzędzia graficznego do utworzenia testowej oferty wielowariantowej.

Tam wszystko się udało, oferta została założona. Problem pojawił się jednak przy próbie jej odczytu po UUID lub w ogóle przy próbie odczytu listy ofert wielowariantowych.

```
GET: https://api.allegro.pl/sale/offer-variants/f28c87df-e4ff-431e-aef5-a01e9397a132

Nagłówki:
Authorization: Bearer ...
Accept: application/vnd.allegro.beta.v1+json
```

Nie działa... podobnie:

```
GET: https://api.allegro.pl/sale/offer-variants?user.id=26875879

Nagłówki:
Authorization: Bearer ...
Accept: application/vnd.allegro.beta.v1+json
```

obydwa zapytania wyrzucają 403 Forbidden oraz response:

```
 {
    "errors": [
        {
            "code": "ERROR",
            "message": "An error has occurred",
            "details": null,
             "path": null,
            "userMessage": null
        }
     ]
}
```

Domyślam się, że przyczyna dotyczy również mojego pierwszego postu w dyskusji. Oferta z UUID który podałem jest aktywna i wyświetla się na karcie produktów.

**Comment by LukaszKorek** [comment]
Sprawdź proszę jeszcze  czy token którego używasz jest przypisany do konta  na którym wystawiasz oferty.
