### ISSUE TITLE
/sale/product-offers gdy jest więcej niż jeden produkt pod EAN'em

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5940]
W jaki sposób zostanie wybrany podpinany produkt do oferty wystawianej przez /sale/product-offers jeśli /sale/products zwraca więcej niż jeden produkt pod tym samym EAN'em?

Pozdrawiam.

**Comment by PrzemyslawLukanowski** [comment]
W takiej sytuacji zwrócimy informację o tym, że dla danego numeru EAN znaleźliśmy więcej niż jeden produkt. W tej sytuacji musisz wskazać ID produktu (nasz UUID).

**Comment by tomylee0** [comment]
Czy taką informację otrzymam synchronicznie - czyli od razu jako odpowiedź na POST'a?

I przy okazji mam ogólniejsze pytanie: czy POST /sale/product-offers jest walidowany synchronicznie? Tzn. czy jeśli dostanę w odpowiedzi 200 OK, 201 Created lub 202 Accepted to mogę założyć, że oferta będzie prędzej czy później opublikowana?

**Comment by PrzemyslawLukanowski** [comment]
> Czy taką informację otrzymam synchronicznie - czyli od razu jako odpowiedź na POST'a?

Tak, w takiej sytuacji od razu otrzymasz informację o błędzie.

> I przy okazji mam ogólniejsze pytanie: czy POST /sale/product-offers jest walidowany synchronicznie? Tzn. czy jeśli dostanę w odpowiedzi 200 OK, 201 Created lub 202 Accepted to mogę założyć, że oferta będzie prędzej czy później opublikowana?

Tak, walidacja również odbywa się synchronicznie. Musisz jednak zwrócić uwagę na ew. komunikaty w validation, nawet przy kodzie 2xx.

**Comment by tomylee0** [comment]
Dzięki wielkie. Pozdrawiam.
