### ISSUE TITLE
allegro.pl.allegrosandbox.pl - rozbieżność GUI / API

### ISSUE THREAD

**Issue by marmizg** [allegro/allegro-api#5941]
na gui sandbox widzę transakcje 
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/?status=NEW&offset=120
natomiast po stronie sandbox-owego api otrzymuje błąd 404.
https://api.allegro.pl.allegrosandbox.pl/sale/offers/7690094220
resp:
{"errors":[{"code":"NOT_FOUND","message":"Offer not found. It was deleted, archived or never existed.","details":"NOT_FOUND","path":"/sale/offers/7690094220","userMessage":"Offer not found. It was deleted, archived or never existed."}]}

czy nie jest to wynik niezbyt poprawnie wykonanego czyszczenia sandbox-a ?
proszę o poprawienie po swojej stronie.

**Comment by PrzemyslawLukanowski** [comment]
Pierwszy link dotyczy zakładki Zamówienia - w tej części cały czas możesz mieć zamówienia, które dotyczą nieistniejącej już oferty. Natomiast w zakładce Mój Asortyment, podobnie jak w API, nie zwrócimy oferty 7690094220.

**Comment by marmizg** [comment]
Panie Przemku
Rozumiem.
Ale nie rozumiem dlaczego 
https://api.allegro.pl.allegrosandbox.pl/order/checkout-forms?status=READY_FOR_PROCESSING&offset=0&limi
t=25&lineItems.boughtAt.gte=2022-05-28T00:00:00.000Z
zwraca oferty których nie ma ?

**Comment by PrzemyslawLukanowski** [comment]
Odpytuje Pan zasób, w którym zwracamy zamówienia, a nie oferty. Tak jak wspomniałem, w zamówieniach cały czas może Pan mieć transakcje, które dotyczą ofert już nieistniejących. Na Sandboxie prowadzimy akcje, które dotyczą usuwania ofert, ale nie zamówień związanych z tymi ofertami. 
Jeśli czegoś nie dostrzegam w Pańskim zgłoszeniu i być może źle je rozumiem, prosiłbym o więcej szczegółów.

**Comment by marmizg** [comment]
tak, tak. pytam się o zamówienia i niestety muszę dobrać pewne informacje z oferty.
rozumiem że, tak może się zdarzyć.
Dziękuje za wyjaśnienie.
