### ISSUE TITLE
Założyłem konto i nie otrzymuję potwierdzenia @ :( proszę o aktywacje konta fajnetowary

### ISSUE THREAD

**Issue by piotr60** [allegro/allegro-api#5942]

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale bez potwierdzenia konta przez link wysłany na skrzynkę nie możemy aktywować konta. Sprawdź proszę, czy wiadomość nie trafiła do folderu ze spamem lub spróbuj użyć innej skrzynki pocztowej.

**Comment by piotr60** [comment]
Dziękuję za odpowiedź

 

Jednak nie otrzymuję linku, przez który mogę potwierdzić konto

 

Proszę o pomoc.

Pozdrawiam

Piotr

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę lub napisz przez [nasz formularz](https://allegro.pl/pomoc/kontakt) (w takiej sytuacji napisz, że dane dot. wątku #5942) adresy mailowe, na które powinny trafić nasze wiadomości. Zweryfikuję, czy na pewno zostały wysłane.

**Comment by piotr60** [comment]
Mój adres @ ***@***.***

 

Piotr

**Comment by PrzemyslawLukanowski** [comment]
Niestety adres jest zamaskowany. Czy tak jak wspominałem, próbowałeś założyć konto także na inną skrzynkę pocztową? Być może ta wyżej wymieniona blokuje od nas wiadomości z załącznikiem .eml.

**Comment by piotr60** [comment]
Dzień dobry

 

Przepraszam, ze ponownie piszę, jednak cały czas mam problem z otrzymaniem linku aktywacyjnego.

Po rejestracji i podaniu kilku różnych adresów @ nie otrzymałem linku aktywacyjnego.

Proszę o pomoc, chodzi o platformę: https://allegro.pl.allegrosandbox.pl/

 

Dziękuję za pomoc

Piotr

**Comment by PrzemyslawLukanowski** [comment]
Widzę w wątku #1046, że wszystkie Twoje konta założone są w domenie one-bit.pl. Sugerując założenie kont na innych skrzynkach pocztowych, miałem na myśli, abyś spróbował skorzystać z innych domen. Jeśli one-bit.pl blokuje nasze wiadomości, to blokuje je w ramach wszystkich kont. Po tym, gdy uda Ci się uzyskać link aktywacyjny, będziesz mógł z powrotem zmienić adres mailowy na koncie.

**Comment by piotr60** [comment]
Zakładałem też z kontem prowadzonym na gmail ***@***.***)

Piotr

**Comment by PrzemyslawLukanowski** [comment]
Wskazany mali nie jest widoczny, jest zamaskowany (gwiazdki zamiast adresu).

**Comment by piotr60** [comment]
To co mogę podać aby aktywować konto?

Piotr

**Comment by PrzemyslawLukanowski** [comment]
Aktywacja musi odbyć się za pośrednictwem linka, który wysyłamy na skrzynkę mailową. Na podstawie wątku #1046 nasze logi wskazują, że wiadomości są wysyłane, jednak najprawdopodobniej są blokowane przez Twojego klienta pocztowego. Nie mamy na to żadnego wpływu, więc jedyne co możemy zasugerować, to sprawdzenie folderu spam i ustawień na skrzynce lub założenie skrzynki na innej stronie internetowej i podanie założonego adresu przy rejestracji nowego konta na Sandboxie.
