### ISSUE TITLE
Problem z kontem firmowym na sandboxie

### ISSUE THREAD

**Issue by mrezlik** [allegro/allegro-api#5943]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

`4594433f7eed4ac`

Witam, 

Mam na allegro sandbox kilka kont firmowych. Jednak podczas próby wystawienia aukcji otrzymuje informacje, że 
`Kod: 403. Błąd: AccessDeniedException Regular Account (not registered as a Business Account) does not have access to this method. Regular Account (not registered as a Business Account) does not have access to this method. AccessDeniedException /sale/offers. `

Czy powinienem się zgłosić do wątku https://github.com/allegro/allegro-api/issues/1046 żeby wszystkie konta zostały w pełni aktywowane?

**Comment by PrzemyslawLukanowski** [comment]
Możesz również podać je w tym wątku, poproszę.

**Comment by mrezlik** [comment]
Proszę bardzo:

estila.stocksell@gmail.com
citylook.stocksell@gmail.com
looklike.stocksell@gmail.com
p.koziol@androbit.com
androbit_seller
m.stochlik@androbit.com

**Comment by PrzemyslawLukanowski** [comment]
[estila.stocksell@gmail.com](mailto:estila.stocksell@gmail.com)
[citylook.stocksell@gmail.com](mailto:citylook.stocksell@gmail.com)
[looklike.stocksell@gmail.com](mailto:looklike.stocksell@gmail.com)
[m.stochlik@androbit.com](mailto:m.stochlik@androbit.com)

Te konta nie posiadają wprowadzonych wszystkich danych, np. Nazwa firmy, rodzaj przedsiębiorstwa, numer NIP. Uzupełnij proszę te dane przez zakładkę [Dane konta.](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta)

[m.stochlik@androbit.com](mailto:m.stochlik@androbit.com)
[p.koziol@androbit.com](mailto:p.koziol@androbit.com)
W tych dwóch przypadkach wygląda na to, że konwersja na konto firmowe nie do końca się udała. Czy możesz również wejść zakładkę Dane konta i wybrać „zmień na firmowe”?

**Comment by mrezlik** [comment]
Dla konta p.koziol@androbit.com po kliknięciu "zmień na firmowe" wyświetla się informacja, że konto jest w trakcie weryfikacji :)

**Comment by mrezlik** [comment]
[estila.stocksell@gmail.com](mailto:estila.stocksell@gmail.com)
[citylook.stocksell@gmail.com](mailto:citylook.stocksell@gmail.com)
[looklike.stocksell@gmail.com](mailto:looklike.stocksell@gmail.com)]

Dla tych kont dane zostały uzupełnione :)

**Comment by macsanta** [comment]
@PrzemyslawLukanowski , mam ten sam problem. W allegro nie została zweryfikowana firma.

Username: szybkie_towary

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5413700/181297643-6d78a806-e783-4d5b-9a70-4465dae4919a.png">

**Comment by PrzemyslawLukanowski** [comment]
@mrezlik 
estila.stocksell@gmail.com
citylook.stocksell@gmail.com
looklike.stocksell@gmail.com

Konta są już aktywne.

m.stochlik@androbit.com - tutaj aktualnie widzę podobną sytuację co dla trzech wcześniejszych kont - musisz jeszcze uzupełnić nazwę firmy i rodzaj przedsiębiorstwa.

p.koziol@androbit.com 
k.jaszczynski@androbit.com

Te dwa konta muszę jeszcze wyjaśnić, ponieważ wygląda na to, że mamy rozbieżności w naszych danych co do rodzaju konta. Wrócę z informacją

@macsanta Twoje konto powinno być już w pełni aktywne. Zignoruj proszę, jeśli grafika aktualnie tego nie oddaje, ponieważ na Sandboxie mogą występować rozbieżności w tej kwestii.

**Comment by PrzemyslawLukanowski** [comment]
[p.koziol@androbit.com](mailto:p.koziol@androbit.com) - konto jest już aktywne.
[k.jaszczynski@androbit.com](mailto:k.jaszczynski@androbit.com) - czy tutaj mógłbyś wybrać "zmień na firmowe" i dostarczyć wszelkie dane. Wygląda na to, że konwersja na konto firmowe się nie rozpoczęła.

**Comment by mrezlik** [comment]
Gotowe :)

**Comment by PrzemyslawLukanowski** [comment]
Konto również już aktywne :)

**Comment by macsanta** [comment]
@PrzemyslawLukanowski, dalej mam error "AccessDenied". Może coś nie tak robie :)
![image](https://user-images.githubusercontent.com/5413700/181451859-af61470f-e323-4d6b-a8d1-bd16ddc358d5.png)

Kategorie dostać mogę bez problemu.
![image](https://user-images.githubusercontent.com/5413700/181452812-8a3ab6ec-da7c-4d50-920c-f79f9f4011f7.png)

OAuth grant-type: authorization_code
Uprawnienia:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/5413700/181452972-7fbeb176-1570-48d8-849c-59221dc6f414.png">

**Comment by PrzemyslawLukanowski** [comment]
@macsanta Jeżeli otrzymujesz listę kategorii, ale nie możesz korzystać np. z GET /sale/offers, to wszystko wskazuje na to, że skorzystałeś z autoryzacji typu client_credentials, która nie posiada kontekstu użytkownika. Rozkoduj swój token, np. [tutaj](https://jwt.io/) i zwróć uwagę, czy zawiera pole "user_name". Jeśli nie, to masz pewność, że musisz zmienić rodzaj autoryzacji na [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by tomasz-grzesik** [comment]
Dzień dobry,

czy mógłbym również poprosić o podobną weryfikację do konta o loginie NS na sandboxie.

Przy wystawianiu/edycji ofert otrzymuję:
"Prowadząc sprzedaż na koncie zwykłym (nie zarejestrowanym jako konto firma), nie możesz korzystać z tej metody Publicznego API."

W Dane Konta:
Rodzaj konta
konto firmowe

**Comment by PrzemyslawLukanowski** [comment]
@tomasz-grzesik Przykro mi, ale na tym koncie nie możesz wystawiać nowych ofert. Jest to konto Allegro Biznes, ale wyłącznie z intencją zakupową. Nie mamy możliwości ustawienia sprzedaży na tym koncie, dlatego jedynym rozwiązaniem będzie założenie nowego.

**Comment by tomasz-grzesik** [comment]
@PrzemyslawLukanowski  niestety formularz rejestracji nie przechodzi.
Proszę o pilne rozwiązanie problemu.
https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto

**Comment by PrzemyslawLukanowski** [comment]
Potwierdzam, że aktualnie występuję problem z rejestracją na środowisku testowym. Pracujemy nad rozwiązaniem, przepraszam za utrudnienia.

**Comment by tomasz-grzesik** [comment]
Mam nadzieję, że naprawa na sandoxie nie potrwa dłużej niż dziś.

**Comment by PrzemyslawLukanowski** [comment]
@tomasz-grzesik Problem nie powinien już występować.

**Comment by tomasz-grzesik** [comment]
Tak. Już nie występuje. Dziękuję za szybką interwencję.

**Comment by artbski** [comment]
Witam,
proszę o aktywację konta sandbox:
abcode

**Comment by MaciejFrackowiak** [comment]
@artbski Aktywowałem Twoje konto.

**Comment by artbski** [comment]
> @artbski Aktywowałem Twoje konto.

dziękuję

**Comment by michalsukiennik** [comment]
Proszę o aktywację ms.sukiennik@gmail.com

**Comment by MaciejFrackowiak** [comment]
@michalsukiennik Proszę wykonaj przelew weryfikacyjny raz jeszcze.

**Comment by michalsukiennik** [comment]
Prawdziwy przelew na sandbox?

**Comment by MaciejFrackowiak** [comment]
@michalsukiennik Nie, w oparciu o symulator działający na Sandbox - jest to element tzw. krokowca w zakładce [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto).

**Comment by MaciejFrackowiak** [comment]
@michalsukiennik Spróbuj skorzystać z [odnośnika](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty) - to powinno dać możliwość przejścia krokowca raz jeszcze.

**Comment by michalsukiennik** [comment]
Bez zmian. Wyświetla się
![image](https://user-images.githubusercontent.com/41668218/218747384-a28d4a86-ddb3-402d-a622-9158e1a738ce.png)

**Comment by MaciejFrackowiak** [comment]
@michalsukiennik Niestety,  zmuszony jestem prosić Ciebie o założenie nowego konta na Sandbox. Podczas wprowadzania danych wybierz proszę przelew realizowany w ramach płatności elektronicznych (nie przelew tradycyjny).

**Comment by LechKulesza** [comment]
Witam,
proszę o aktywację konta sandbox: kulkazgumek

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem Twoje konto.

**Comment by michalsukiennik** [comment]
Prośba o aktywację: mariusz_wiersz@wp.pl

**Comment by MaciejFrackowiak** [comment]
@michalsukiennik Aktywowałem wskazane konto.
