### ISSUE TITLE
Problem z wysyłka za granicę

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#5945]
Potrzebuję pomocy w zakresie wysyłki za granicę. Na koncie sportcitytest na sandboxie mamy wystawioną aukcję
https://allegro.pl.allegrosandbox.pl/oferta/koszulka-t-shirt-4f-j4l17-jtsd104-104-2110-7691143038
Jako klient nie mogę jej kupić do Niemiec. Nie wiem co jest przyczyną.
Proszę o sprawdzenie, które z ustawień polityki, blokuje na tej dokładnej aukcji sprzedaż na Niemcy.

**Comment by Lukasz-Zurek** [comment]
W tym przypadku do cennika dostawy spośród wszystkich dostępnych metod musisz dodać "Wysyłkę za granicę" -> "Niemcy" i ustalić jej koszt.

**Comment by pzareba86** [comment]
Ale mam dodany cennik allegro 
![image](https://user-images.githubusercontent.com/98810516/181472983-001cf42f-c002-4839-98b1-017cfa67f3b6.png)
sa Niemcy i mom wszystko jest komunikat, że sprzedający nie wysyla do tego kraju.

**Comment by Lukasz-Zurek** [comment]
Skonsultuję sprawę z odpowiednim zespołem. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
Aby wysyłka za granicę - w tym przypadku - do Niemiec - była dostępna, w ustawieniach numerów EPR, w zakładce [dane konta](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta), musisz wprowadzić faktyczne numery EPR, przypisane do właściwej firmy. Również na środowisku testowym korzystamy z prawdziwego rejestru, tak jak na produkcji.

Więcej informacji na temat rozszerzonej odpowiedzialności producenta znajdziesz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/rozszerzona-odpowiedzialnosc-producenta-informacje-dla-sprzedajacych-Ag6YnBkdvue).

**Comment by pzareba86** [comment]
Super, bardzo dziękuję za pomoc - o to chodziło:)
