### ISSUE TITLE
BAD REQUEST dla GET i PUT /parcel-management/parcel-create-commands/{commandId}

### ISSUE THREAD

**Issue by g-radzio** [allegro/allegro-api#5948]
Witam,
Mam problem z utworzeniem przesyłki Allegro One za pomocą parcel-management/parcel-create-commands/{commandId}
Za każdym razem dostaję komunikat o błędzie, np:

`{"errors":[{"code":"BAD_REQUEST","message":"JSON parse error","details":null,"path":"/parcel-management/parcel-create-commands/285f4387-8307-408a-a9ba-3f43 ed39dbe4","userMessage":"Nieprawidłowa treść żądania JSON"}]}`

 JSON dla commandID  285f4387-8307-408a-a9ba-3f43 ed39dbe4:

```
{
	"serviceId":17858218,
	"receiver":{
		"email":"pbfuu600f7+132551c83@allegromail.pl",
		"phone":"518210099",
		"pointId":"A004901"
	},
	"pickup":{
		"address":{
			"street":"TU_JEST_ULICA",
			"postCode":"44-102",
			"city":"TU_JEST_MIASTO"
		}
	},
	"items":[
		{
			"value":{
				"amount":"43.47",
				"currency":"PLN"
			}
		}
	],
	"type":"PACKAGE"
}
```

Starałem się działać według dokumentacji https://developer.allegro.pl/documentation/#operation/createNewParcel i wydaje mi się, że mam wszystkie dane, które są oznaczone jako obowiązkowe. Coś pomijam, albo przekazuję nieprawidłowo?

**Comment by PrzemyslawLukanowski** [comment]
Twój JSON jest prawidłowy, nie udało mi się powtórzyć tego błędu - przesyłka zostaje prawidłowo utworzona. Wygląda na to, że strukturę "opakowujesz" w dodatkowy cudzysłów: "{dane}" zamiast po prostu {dane}. Usuń proszę te znaczniki, a przesyłka powinna wygenerować się prawidłowo.

**Comment by g-radzio** [comment]
Próbowałem wysłać JSON 

`{"serviceId":17858218,"receiver":{"email":"pbfuu600f7+132551c83@allegromail.pl","phone":"518210099","pointId":"A004901"},"pickup":{"address":{"street":"ADRES","postCode":"44-102","city":"MIASTO"}},"items":[{"value":{"amount":"43.47","currency":"PLN"}}],"type":"PACKAGE"}`

dla https://api.allegro.pl/parcel-management/parcel-create-commands/0db57341-b52d-42c2-ad96-c6ac97eb1dc0

Z tego co widzę, nie dokleiły się żadne dodatkowe znaczniki, ale wciąż dostaję ten sam błąd.

Próbowałem zarówno konwersji obieku php na json, jak i wysyłania zwykłego stringa - dla obu przypadków efekt był ten sam.

**Comment by PrzemyslawLukanowski** [comment]
Zwróć proszę uwagę, czy ten JSON nie jest konwertowany w jakiś sposób, który dodaje dodatkowy cudzysłów, ponieważ w naszych logach ponownie widzimy nadmiarowe znaczniki, które przyczyniły się do tego błędu. Sam JSON, w takiej formie, w jakiej wkleiłeś go wyżej, na pewno jest prawidłowy - w odpowiedzi otrzymuję kod 201 Created, jeśli go użyję. Jeśli JSON opakuję w "{...}" otrzymam identyczny błąd, który zwracamy Tobie. Jeśli wkleisz ten kod do konsoli lub użyjesz np. Postmana, również nie otrzymasz błędu:

```
curl --location --request PUT 'https://api.allegro.pl/parcel-management/parcel-create-commands/{uuid}' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer {token}' \
--data-raw '{"serviceId":17858218,"receiver":{"email":"pbfuu600f7+132551c83@allegromail.pl","phone":"518210099","pointId":"A004901"},"pickup":{"address":{"street":"ADRES","postCode":"44-102","city":"MIASTO"}},"items":[{"value":{"amount":"43.47","currency":"PLN"}}],"type":"PACKAGE"}'
```

**Comment by g-radzio** [comment]
Udało mi się rozwiązać problem i PUT /parcel-management/parcel-create-commands/{commandId} działa już prawidłowo, jednak gdy potem robię GET /parcel-management/parcel-create-commands/{commandId} otrzymuję (dla commandId b52ffb9d-b12b-49fe-8ec2-a83b331f9aec):

`{"id":"b52ffb9d-b12b-49fe-8ec2-a83b331f9aec","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Order delivery method is not allowed","details":null,"path":null,"userMessage":"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"}]}
`

W danych zamówienia jest metoda dostawy 08c15d0b-9b24-4b3f-89a8-7a2b502abe55. Sprawdziłem za pomocą GET sale/delivery-methods że to Allegro One Punkt.
Za pomocą GET parcel-management/delivery-services sprawdziłem jakie są możliwości i według mnie najbardziej pasująca to Allegro One Punkt (One Kurier) - tylko ta ma w "name" Allegro One Punkt. Jej id to 17858218. Przekazuję je w PUT /parcel-management/parcel-create-commands/{commandId} jako serviceId.

W tym momencie dla dostawy Allegro One Punkt nie powinienem wybierać tego serviceId tylko jakiś inny?

**Comment by g-radzio** [comment]
Czy znajdę gdzieś opis, w jakich przypadkach dodatkowe pola mogą być obowiązkowe?

W PUT /parcel-management/parcel-create-commands/bba2d429-760e-4f22-b026-8dbc74729fe8 przekazałem JSONA:

`{"serviceId":15148477,"receiver":{"email":"pbfuu600f7+132551c83@allegromail.pl","phone":"518210099","pointId":"A004901"},"pickup":{"address":{"street":"Al. J.N. Jeziora\u0144skiego 39","postCode":"44-102","city":"Gliwice"}},"items":[{"value":{"amount":"43.47","currency":"PLN"}}],"type":"PACKAGE"}`

i w GET /parcel-management/parcel-create-commands/bba2d429-760e-4f22-b026-8dbc74729fe8 otrzymałem wiele błędów dotyczących pól, które w dokumentacji https://developer.allegro.pl/documentation/#operation/createNewParcel nie są oznaczone jako required. Czy po przekazaniu id Allegro One (UPS) czyli 15148477 muszę podawać więcej danych, czy normalnie też były wymagane, tylko nie są oznaczone w dokumentacji?

**Comment by PrzemyslawLukanowski** [comment]
Tak, niektórzy przewoźnicy wymagają, aby przekazać określone pola, które mogą nie być oznaczone jako required w dokumentacji. Niestety nie posiadamy takiego opisu, ale dziękuję za tę sugestię, postaramy się zebrać te informacje i stworzyć odpowiednią sekcję w naszym poradniku.

**Comment by g-radzio** [comment]
Uzupełniając brakujące dane natrafiłem na jeszcze 3 problemy.

Pierwszy dotyczy receiver.company, które jest obowiązkowe, jednak w większości przypadków wysyłam przesyłki do odbiorców prywatnych. Czy w takim razie jako receiver.company i receiver.name mogę podać kolejno imię i nazwisko zamawiającego? 

Taki zabieg zastosowałem dla PUT /parcel-management/parcel-create-commands/436b8ebd-39a4-4102-bc54-bd46463063ac

O ile zwrócona odpowiedź wygląda dobrze, to gdy robię GET /parcel-management/parcel-create-commands/436b8ebd-39a4-4102-bc54-bd46463063ac dostaję:

```
{
    "id": "436b8ebd-39a4-4102-bc54-bd46463063ac",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Pickup name is required",
            "details": null,
            "path": "pickup.name",
            "userMessage": "Nazwa punktu nadania przesyłki jest wymagana"
        },
        {
            "code": "ERROR",
            "message": "Receiver name is required",
            "details": null,
            "path": "receiver.name",
            "userMessage": "Nazwa odbiorcy jest wymagana"
        },
        {
            "code": "ERROR",
            "message": "Parcel weight is incorrect",
            "details": null,
            "path": "items.weight.value",
            "userMessage": "Proszę podać prawidłową wagę"
        },
        {
            "code": "ERROR",
            "message": "Parcel dimensions incorrect",
            "details": null,
            "path": "items.dimensions",
            "userMessage": "Nieprawidłowe wymiary przesyłki"
        }
    ]
}
```

Błedy dotyczące wagi i wymiarów mają sens, nie podałem ich. Problem w tym, że pickup.name i receiver.name zostały podane w JSONie, który dla PUT /parcel-management/parcel-create-commands/436b8ebd-39a4-4102-bc54-bd46463063ac ma postać: 

```
{
    "serviceId": 15148477,
    "receiver": {
        "address": {
            "postCode": "41-902",
            "city": "MIASTO",
            "countryCode": "PL"
        },
        "email": "pbfuu600f7+132551c83@allegromail.pl",
        "name": "IMIE",
        "company": "NAZWISKO",
        "phone": "518210099",
        "pointId": "A004901"
    },
    "pickup": {
        "address": {
            "street": "ULICA",
            "postCode": "44-102",
            "city": "MIASTO",
            "countryCode": "PL"
        },
        "email": "MAIL",
        "name": "NAZWA",
        "company": "FIRMA",
        "phone": "322309863"
    },
    "items": [
        {
            "description": "Ksi\u0105\u017cka",
            "value": {
                "amount": "43.47",
                "currency": "PLN"
            }
        }
    ],
    "type": "PACKAGE"
}
```

**Comment by Lukasz-Zurek** [comment]
@g-radzio Dzięki za dokładny opis. Pola **pickup.name** i **receiver.name** muszą zawierać dwuczłonową wartość (imię i nazwisko).

**Comment by g-radzio** [comment]
Ok, więc jeśli w **receiver.name** przekażę imię i nazwisko, to co wtedy przekazać w **receiver.company** dla klienta indywidualnego, skoro to również nie może być puste? W obu polach przekazywać imię i nazwisko?
