### ISSUE TITLE
doGetSellFormFieldsForCategory - ERR_INTERNAL_SYSTEM_ERROR

### ISSUE THREAD

**Issue by joe1d83** [allegro/allegro-api#595]
Witam,

każde wywołanie metody doGetSellFormFieldsForCategory zwraca błąd ERR_INTERNAL_SYSTEM_ERROR

**Comment by Maczuga** [comment]
Potwierdzam

**Comment by mirkosmuz** [comment]
potwierdzam

**Comment by MarcinLuczak** [comment]
@joe1d83 @Maczuga @mirkosmuz sprawdziłem metodę - działa bez zarzutu. Jeśli problem faktycznie był, to był chwilowy i już nie występuje.
