### ISSUE TITLE
[QUESTION] Publiczne Allegro API - ogólne pytania / Public Allegro API - general questions 

### ISSUE THREAD

**Issue by sluckos** [allegro/allegro-api#5950]
Witam,
Należę do zespołu w software house, który przymierza się do integracji z Waszym publicznym API na potrzeby jednego z naszych klientów. W związku z tym mam kilka pytań, jeśli chodzi o utrzymanie takiej integracji. Na ten moment najbardziej interesuje nas API dotyczące wystawiania ofert na Allegro. 

1. Przy ewentualnych zmianach w publicznym API (które nas by dotyczyło) jak informujecie o konieczności dostosowania się do nowego API?
2. Czy informujecie o tym wcześniej (przed wprowadzeniem zmian)? Jeśli tak, to jaki jest kanał informacyjny?
3. Ile czasu dajecie na dostosowanie się do nowych zmian? 
4. Czy dopuszczacie możliwość wprowadzenia zmian w publicznym API, która może spowodować zepsucie istniejącej integracji z dnia na dzień, bez żadnej informacji na ten temat? 

Chodzi mi o taki ogólny zarys Waszej polityki dotyczącej zmian w publicznym API. 

W dokumentacji znalazłem tylko informację o kompatybilności wstecznej I wersjonowaniu API, jeśli taka kompatybilność zostałaby złamana. Czy moglibyście nam podpowiedzieć w tym obszarze, abyśmy mogli podjąć wewnętrzne decyzje?

Z góry dziękuję za odpowiedź.

**Comment by Lukasz-Zurek** [comment]
> 1. Przy ewentualnych zmianach w publicznym API (które nas by dotyczyło) jak informujecie o konieczności dostosowania się do nowego API?

O każdej zmianie w naszym API informujemy w [aktualnościach](https://developer.allegro.pl/news) na naszym Allegro Developer Portalu. Zachęcam tutaj do zasubskrybowania naszego [newslettera](https://developer.allegro.pl/newsletter). Dodatkowo aktualności te udostępniamy również na [Githubie](https://github.com/allegro/allegro-api/issues).
> 2. Czy informujecie o tym wcześniej (przed wprowadzeniem zmian)? Jeśli tak, to jaki jest kanał informacyjny?

O istotnej zmianie, która np. łamie kompatybilność wsteczną - informujemy do ok 3 miesięcy wcześniej. Natomiast w przypadku mniejszych zmian - około 2 tygodnie przed wdrożeniem. Natomiast w sytuacji, gdy zmiana nie łamie kompatybilności i nie jest kluczowa - nie informujemy jej z wyprzedzeniem.

> 3. Ile czasu dajecie na dostosowanie się do nowych zmian?

Do zmian w API podchodzimy indywidualnie - patrz pkt 2. Staramy się jednak pilnować terminów tak, aby Partnerzy mieli możliwość dostosowania się do zmian wystarczająco wcześniej. Nie chcemy, aby jakakolwiek zmiana zaburzyła integrację z naszym API.

W wyjątkowych przypadkach informujemy nawet ze znacznie większym wyprzedzeniem. Przykładem jest informacja o [wyłączeniu zasobów /sale/offers na początku 2024 roku](https://developer.allegro.pl/news/na-poczatku-2024-roku-wylaczymy-zasoby-sale-offers-sluzace-do-tworzenia-i-edycji-ofert-BvqK3XOaEcW).

> 4. Czy dopuszczacie możliwość wprowadzenia zmian w publicznym API, która może spowodować zepsucie istniejącej integracji z dnia na dzień, bez żadnej informacji na ten temat?

Nie. Każdą zmianę w API analizujemy pod kątem m.in. wpływu na obecnie działające integracje.

**Comment by sluckos** [comment]
Dziękuję za odpowiedzi, a wracając jeszcze do dokumentacji i wersjonowania zasobów. Rozumiem, że gdy łamana jest kompatybilność wsteczna to tworzycie nową metodę z nową wersją nagłówka Accept/Content-Type, bazując na dokumentacji. 

Wobec tego jak długo wspieracie starszą wersję API. Kiedy jest ona usuwana/kończy się dla niej wsparcie? Np. wprowadzacie wersję v2, to po jakim czasie usuwacie v1?

**Comment by Lukasz-Zurek** [comment]
> Dziękuję za odpowiedzi, a wracając jeszcze do dokumentacji i wersjonowania zasobów. Rozumiem, że gdy łamana jest kompatybilność wsteczna to tworzycie nową metodę z nową wersją nagłówka Accept/Content-Type, bazując na dokumentacji.

Tak.

> Wobec tego jak długo wspieracie starszą wersję API. Kiedy jest ona usuwana/kończy się dla niej wsparcie? Np. wprowadzacie wersję v2, to po jakim czasie usuwacie v1?

To jest też kwestia indywidualna, zależna od zasobów. [Tutaj](https://developer.allegro.pl/news/kampanie-w-wersji-public-q018m2eZxHR) możesz zobaczyć przykład zakończenia okresu testowego dla kampanii w wersji beta, której zakończenie zapowiedzieliśmy miesiąc przed przejściem do wersji public.

Natomiast w przypadku wersji public zasobów /sale/product-offers - zmianę polegającą na wyłączeniu zasobów w wersji beta [zapowiedzieliśmy](https://developer.allegro.pl/news/udostepnilismy-wersje-public-zasobow-sale-product-offers-LRVG9RXDXUP) około 1,5 miesiąca wcześniej oraz dodatkowo [2 tygodnie przed zmianą](https://developer.allegro.pl/news/28-lutego-wylaczymy-wersje-beta-zasobow-sale-product-offers-5LnvrD8kLs9). Wersja beta.v3 funkcjonowała [od 15 lipca 2021](https://developer.allegro.pl/news/udostepnilismy-wersje-beta-v3-zasobow-sale-product-offers-yPy9lOEMDCM).

Czyli poprzednią, starszą wersję danego zasobu wspieramy jeszcze około 1-2 miesiące od momentu zapowiedzi wygaszenia/zmiany na nową wersję.
