### ISSUE TITLE
odświeżanie tokena na więcej niż 1 koncie

### ISSUE THREAD

**Issue by uranity** [allegro/allegro-api#5951]
Moim klienci korzystający z api allegro korzystają z więcej niż jedna aplikacja, która robi różne rzeczy przez api. Obserwuję ostatnio dziwne zachowania związane z utratą ważności tokena, ale nie jestem czy to nie błąd po naszej stronie.

1) Np. gdy konto nie jest używane jakiś czas (nawet krótki - 1 dzień) to odświeżenie tokena nie działa (Bad Request) w jednej aplikacji, a w drugiej działa (ta sama metoda odświeżania). Z czego to może wynikać?

2) A nawet jak działa api w aplikacji 1 to żeby działała w 2-giej to muszę skopiować ręcznie tokeny do bazy, bo odświeżenie nie działa w aplikacji 2. Czy to jest "normalne" zachowanie? Być może jest to powiązane z pkt 1, ale nie wiem.

Proszę o wskazówki. Dziekuję.

**Comment by PrzemyslawLukanowski** [comment]
Czy na pewno korzystasz z dwóch różnych tokenów odświeżenia w takiej sytuacji, tzn. czy w pierwszej aplikacji posługujesz się refresh tokenem z tej samej pary, gdzie otrzymałeś access token i w drugiej aplikacji podobnie - musisz użyć właściwego refresh tokena. Ten sam refresh token nie odświeży oczywiście autoryzacji użytkownika w dwóch rożnych aplikacjach. 
Najlepiej będzie, jeśli prześlesz nam konkretne przykłady, gdzie odświeżenie tokenów nie poszło po myśli. Skorzystaj w tym celu z naszego [formularza kontaktowego,](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a) dopisz, że przesłane dane dotyczą wątku #5951 na GitHubie. Sprawdzimy, jak to wygląda w naszych logach, przeanalizujemy sytuację i wrócimy z odpowiedzią.

**Comment by uranity** [comment]
Dziękuję za odpowiedź.
Tak, czasami używam tych samych, zdarza mi się skopiować. Czy to błąd? Właśnie po skopiowaniu tokenów (i głowny i refresh token) z aplikacji 1 do 2, działają obie aplikacje.

**Comment by PrzemyslawLukanowski** [comment]
Gdy wysyłasz żądanie odświeżenia tokena, przekazujesz przy tym nagłówek Authorization, który posiada informacje na temat clientId. Sam token również posiada zakodowaną informację dot. clientId, za pomocą którego został wygenerowany. Nie powinieneś mieć możliwości, aby refresh token wygenerowany w ramach aplikacji A użyć do przedłużenia ważności tokena w ramach aplikacji B.

**Comment by uranity** [comment]
Rozumiem. Czyli sam token bedzie działał dopóki termin ważności nie wygaśnie. A odświeżenie nie zadziała. Zatem jakie jest rozwiązanie? Takie, że w każdej aplikacji autoryzacja powinna przebiegać osobno i niezależnie (przez logowanie do panelu allegro)?

**Comment by PrzemyslawLukanowski** [comment]
> Rozumiem. Czyli sam token bedzie działał dopóki termin ważności nie wygaśnie. 

Token może dodatkowo wygasnąć jeśli. np. zostanie już zużyty (bo wygenerujesz nową parę) albo kiedy użytkownik otrzyma blokadę, zmieni hasło lub adres mailowy.

> Zatem jakie jest rozwiązanie? Takie, że w każdej aplikacji autoryzacja powinna przebiegać osobno i niezależnie (przez logowanie do panelu allegro)?

Tak, autoryzacja w każdej aplikacji powinna przebiegać osobno, jednak nie musisz za każdym razem zmuszać użytkownika do logowania do panelu Allegro. Tę czynność może wykonać tylko za pierwszym razem, kiedy autoryzuje aplikacje, aby te mogły wykonywać czynności w jego imieniu. Następnie możesz już korzystać z refresh tokenów, osobno w ramach każdej z aplikacji.
