### ISSUE TITLE
Plik excel z ofertami danego konta

### ISSUE THREAD

**Issue by amicadermo** [allegro/allegro-api#5952]
Witam serdecznie, Zwracamy się z prośbą o wprowadzenie dodatkowej kolumny dotyczącej sortowania produktów pobranych z pliku z ofertami. Kolumna dotyczy Statusu ofert. Prosimy o wprowadzenie możliwości sortowania także po ofertach, których faktyczny status to 'Ukryte'. Aktualnie oferty ukryte posiadają status zakończonych co utrudnia pracę z plikiem. Pozdrawiam

![StatusOferty](https://user-images.githubusercontent.com/110237114/181755515-0681908d-f56b-49e2-a689-75867032be39.JPG)

**Comment by PrzemyslawLukanowski** [comment]
Prosiłbym w tym przypadku o kontakt przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt), ponieważ na forum świadczymy wsparcie związane z API Allegro. Twoje zgłoszenie jest natomiast związane z generowaniem pliku excel na stronie internetowej.

**Comment by amicadermo** [comment]
Dziękuję za szybką odpowiedź. Proszę o informację jaki temat będzie odpowiedni dla naszego zapytania?

**Comment by PrzemyslawLukanowski** [comment]
Proszę spróbować wybrać Sprzedaję > Zarządzanie sprzedażą > Wystawianie oferty przez formularz. Niestety nie widzę sekcji stricte powiązanej z zakładką "Mój asortyment", ale zgłoszenie na pewno trafi w odpowiednie ręce.
