### ISSUE TITLE
GTIN czy na pewno jest obowiązkowy?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5953]
1. Zaglądam np. do parametrów kategorii 260273 i mam, że 225693 EAN (GTIN) nie jest obowiązkowy.

2. I przy okazji: czy mamy gwarancję, że identyfikator pól GTIN się nie zmieni? Bo np. jakiś czas temu dla kategorii 260273 parametr 225693 nazywał się "EAN". A teraz jest "EAN (GTIN)".

**Comment by hahyes** [comment]
1) 100% powiązań z katalogiem produktów nie oznacza, że 100% ofert musi mieć podany EAN.
2) Nie mamy żadnej. Natomiast parametr ma dla wszystkich kategorii ten sam identyfikator, więc podejrzewam, że raczej tak pozostanie.

**Comment by PrzemyslawLukanowski** [comment]
1. Dokładnie jak opisał to hayhes, np. w kategorii Moda parametr nie jest obowiązkowy, a w niektórych kategoriach jego obowiązkowość jest zależna od parametru stan, np. jeśli stan jest "Nowy", to tylko wtedy GTIN jest obowiązkowy.
2. Identyfikator nie powinien się zmienić. Zmieniliśmy nazwę parametru, ponieważ GTIN to bardziej aktualne określenie stosowane przez GS1.

**Comment by tomylee0** [comment]
Dzięki za odpowiedź. 

Czy mamy się spodziewać, że niedługo ISBN w kategoriach książkowych zamieni się na "ISBN (GTIN)"?

**Comment by tomylee0** [comment]
I jeszcze jedno pytanie. Czy jest jakiś szybki sposób dla konta ze 100 tys. ofert na sprawdzenie które oferty nie mają ustawionego GTIN? Coś analogicznego jak sprawdzenie które oferty nie są podpięte do produktu. Tak, żeby nie trzeba było odpytywać każdej oferty osobno.

**Comment by hahyes** [comment]
@tomylee0 Jest taki zasób, ale wymóg parametru musi obowiązywać już na Allegro: https://developer.allegro.pl/documentation#operation/getOffersUnfilledParametersUsingGET_1

**Comment by tomylee0** [comment]
No tak. Dzięki @hahyes

**Comment by PrzemyslawLukanowski** [comment]
A co do:

> Czy mamy się spodziewać, że niedługo ISBN w kategoriach książkowych zamieni się na "ISBN (GTIN)"?

to nie, nie planujemy na razie takich zmian.

**Comment by tomylee0** [comment]
Dzięki za pomoc.
