### ISSUE TITLE
Generowanie przesyłki Allegro One Box

### ISSUE THREAD

**Issue by PawOb** [allegro/allegro-api#5955]
Witam
Próbuję wygenerować nową przesyłkę Allegro One Box.
Wykorzystuję metodę /parcel-management/parcel-create-commands z UUID 0a48199e-0f4d-11ed-861d-0242ac120012 i usługą 17871574
Wygląda, że wszystko jest ok.
Ale już przy sprawdzeniu statusu tworzenia przesyłki metodą /parcel-management/parcel-create-commands otrzymuję
"id": "0a48199e-0f4d-11ed-861d-0242ac120012",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": null,
            "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
        }
    ]
Prośba o zdiagnozowanie dlaczego nie chce utworzyć się przesyłka.

**Comment by Lukasz-Zurek** [comment]
Wybrana usługa nie jest dostępna dla kodu pocztowego nadawcy tj. **pickup.address.postCode**. W tym polu przekazałeś kod 05-080. Dostępność wg. kodu pocztowego możesz sprawdzić [na stronie](https://allegro.pl/kampania/one/kurier).
