### ISSUE TITLE
Czy i jakie funkcje API zostaną dla kont prywatnych?

### ISSUE THREAD

**Issue by niksfirefly** [allegro/allegro-api#5956]
Czy i jakie funkcje API zostaną dla kont prywatnych?

**Comment by Lukasz-Zurek** [comment]
Nie posiadamy tego typu listy zasobów API. Z większości z nich mogą obecnie korzystać zarówno użytkownicy z kontem firmowym, jak i zwykłym. Jednakże zalecamy zarejestrowanie konta firmowego m.in. z uwagi na ograniczenie, jakie ostatnio wdrożyliśmy - czyli [możliwość wystawiania i edycji ofert przez API wyłącznie przez użytkowników z kontem firmowym](https://developer.allegro.pl/news/od-dzis-oferty-przez-api-moga-wystawiac-i-edytowac-tylko-uzytkownicy-z-kontem-firmowym-9gRePwXxGiP). 

Nawet jeśli będziesz korzystał z naszego API na koncie zwykłym, to dodasz warunki zwrotów i reklamacji czy cenniki dostawy, ale ostatecznie nie wystawisz ofert w naszym Serwisie.

**Comment by Lukasz-Zurek** [comment]
@niksfirefly Dziękuję za Twoje uwagi. Wskaż proszę miejsce występowania błędu w dokumentacji. Zależy nam na tym, aby była ona zgodna ze stanem faktycznym.

**Comment by niksfirefly** [comment]
https://developer.allegro.pl/tutorials/jak-wystawic-oferte-GRaj0q1PMSK#jak-wystawic-podobna-oferte
nie ma nic o tym że cały proces czy jego część działa tylko dla konta firmowego

Czy wystawianie draftów lub ofert zaplanowanych jest też zablokowana? Wasza dokumentacja jest nieaktualna.

**Comment by Lukasz-Zurek** [comment]
@niksfirefly Dzięki. Doprecyzujemy wskazane informacje w naszym poradniku.

Tak, tworzenie draftów i zaplanowanych ofert również jest zablokowane. Przy próbie utworzenia draftu otrzymasz błąd 403 - `"Regular Account (not registered as a Business Account) does not have access to this method."`
