### ISSUE TITLE
connected to Catalog fails

### ISSUE THREAD

**Issue by fxsshiwo** [allegro/allegro-api#5957]
Hello, when I am connected to Catalog, the color attribute under the category 255634 shows that it supports ambiguous parameters, but it fails to save, what is the reason?
![801F0C31-6AE2-4447-B0B1-E5A1B4107F8D](https://user-images.githubusercontent.com/20201824/182090213-af537178-bfb5-4ba5-93ec-569dc0151bb0.png)
![69CEEAC5-A444-4775-8579-B669F8ABF79E](https://user-images.githubusercontent.com/20201824/182090235-edea81ef-b8e1-4d67-b087-29458dac8b35.png)
![8D5BBC94-DB87-4665-9244-B69C16245FF7](https://user-images.githubusercontent.com/20201824/182090248-3cb02e28-62aa-494d-b30a-77869367a9e7.png)

**Comment by Lukasz-Zurek** [comment]
@fxsshiwo As **hahyes** has already mentioned - there is no possibility to choose ambiguous value in this situation.

**Comment by fxsshiwo** [comment]
Means I can't select the value provided by ambiguousValueId for an attribute? 
So how should we judge whether the value of ambiguousValueId can be used?

> @fxsshiwo As **hahyes** has already mentioned - there is no possibility to choose ambiguous value in this situation.



> Pick anything but "other color" as Color parameter value. Then it will be fine. Seems like this is acryl colored item, so "white" seems to be right one. You can't pick ambigious value for product.

**Comment by hahyes** [comment]
@fxsshiwo For linking with product you simply can't use ambiguous value. Product need to have specified values, not "unknown"/"other".

**Comment by fxsshiwo** [comment]
I see.
that when I use
Ambiguous values also cannot be used in the POST /sale/product-offers method?

**Comment by hahyes** [comment]
> I see. that when I use Ambiguous values also cannot be used in the POST /sale/product-offers method?

Unless they can be filled with own value. It means `customValuesEnabled` need to be `true` for parameter.

**Comment by fxsshiwo** [comment]
Hello, I would also like to ask, is it possible to implement connected to Catalog through API?

**Comment by Lukasz-Zurek** [comment]
@fxsshiwo You can assign a product to the listed offers. You have two ways to do this:

1. Using [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/updateOfferUsingPUT) and providing product.id, category id (or similar category ID) matching selected product, proper parameters, etc.
2. Using [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) and providing specific product parameters to match the product.

More information you will find in [our guide](https://developer.allegro.pl/tutorials/assigning-offers-products-3An6WaVWnHO#assigning-products-to-listed-offers).

However, regarding listing an offer with product - we recommend using [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers). This is a main approach to list an offer. More information [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-edit-an-offer).
