### ISSUE TITLE
 [code: InvalidLanguage ] błąd podczas łączenia z katalogiem

### ISSUE THREAD

**Issue by Lordoze** [allegro/allegro-api#5959]
Występuje problem: 
 - [code: InvalidLanguage ] z zasobem REST API / with a REST API resource
 

:beetle: **Opis / Description**
Dzisiaj od rana mam problem z przypisywaniem produktów do katalogu. Wywala błąd: Niepoprawnie zdefiniowano parametr language lub nagłówek Accept-Language. [code: InvalidLanguage] GET sale/products/57ee4eac-8540-478f-a2cd-7b8d161e286b

Weszły jakieś zmiany API czy to tylko u mnie się coś wykrzaczyło?

**Comment by MartaNowaczyk** [comment]
Nie było zmian w tym zakresie. Nie udało mi się powtórzyć błędu. Możesz podesłać swój request w formacie JSON?

**Comment by Lordoze** [comment]
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: pl-PL,pl;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 3799
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAAp8tqaeyiGRdMK5

Nie wiem czy o to chodzi, ale to jedyne miejsce w którym znalazłem request odnoście języka

**Comment by MartaNowaczyk** [comment]
Accept-Language powinien mieć wartość w formacie [BCP-47](https://tools.ietf.org/rfc/bcp/bcp47) czyli en-EN, pl-PL itd.

**Comment by Lordoze** [comment]
Dziękuję za odpowiedź. Udało się naprawić. Szczerze mówiąc nie wiem dlaczego wcześniej działało bez problemu.
