### ISSUE TITLE
Problem z wygenerowaniem paczki Allegro odbiór w punkcie UPS

### ISSUE THREAD

**Issue by myszaq99** [allegro/allegro-api#5960]
Gdy próbuję wygenerować paczkę do zamówienia numer: ac9559c1-10fe-11ed-af19-55d83af58565
otrzymuję błąd: "Punkt odbiorcy jest niepoprawny (ERROR receiver.pointId)
#PP1"

**Comment by AureliuszBrussy** [comment]
Podaj proszę commandId próby utworzenia przesyłki lub trace-id wywołania kończącego się tym błędem (znajdziesz je w nagłówku odpowiedzi). To pozwoli mi dokładniej sprawdzić przyczynę problemu.

**Comment by AureliuszBrussy** [comment]
@myszaq99 wskazany punkt odbioru jest aktualnie niedostępny po stronie UPS z przyczyn niezależnych od nas. Więcej informacji może udzielić bezpośrednio UPS.
