### ISSUE TITLE
Zmiana konta na firmowe na sandboxie

### ISSUE THREAD

**Issue by akapela986** [allegro/allegro-api#5962]
Chcę zmienić konta na firmowe (na sandboxie), jednak czekam na weryfikację płatności, którą przeprowadziłem Waszym symulatorem. Czy powinienem jeszcze coś zrobić, żebyście zweryfikowali konta?
Loginy:
client10520
Marek12345
sandbox2
Sandbox3

**Comment by MaciejFrackowiak** [comment]
Przeprocesowałem wnioski do końca, wskazane konta są już kontami firmowymi.

**Comment by akapela986** [comment]
Dzięki
