### ISSUE TITLE
How to use categories options ?

### ISSUE THREAD

**Issue by niuniubaba** [allegro/allegro-api#5963]
How to use these parameters ?   what do they mean ?

dependsOnParameterId": null    
requiredDependsOnValueIds": null,
displayDependsOnValueIds": null,

**Comment by MaciejFrackowiak** [comment]
These fields describe dependent parameters:
- dependsOnParameterId: here we return id for "A" parameter, which indicates can be provided in "B" parameter, e.g. for the Model parameter (parameter "B") we will return the id of the parameter Brand (parameter "A") Parameter id in this field is returned only for dictionary type parameters, in other cases we will return a null value;
- requiredDependsOnValueIds: here we return the value identifiers of the conditioning parameter, which determines whether a parameter will be required, e.g. ID of the value "New" for the "State" parameter;
- displayDependsOnValueIds: here we return a set of values identifiers of the conditioning parameter, which determines whether a parameter will be visible, e.g. if this field applies to the "Volume" parameter in the "Soaps" category, we will return identifiers of the "liquid" and "paste" values for the "Type" parameter.

Please, read our articles about these options - [here](https://developer.allegro.pl/news/new-fields-for-dependent-parameters-oA6jyygxGTx) and [here](https://developer.allegro.pl/news/get-sale-categories-categoryid-parameters-we-have-added-new-fields-for-handling-dependent-parameters-nn9Y172GySL).
