### ISSUE TITLE
Zgłaszanie zmian w produktach

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5966]
Witam,

implementuje do swoich systemów moduł zgłaszania zmian w produktach i martwi mnie, jak podawanie danych może wpływać na szanse powodzenia. Nie chcę zmieniać zdjęć bądź nazw produktu - nie jest to w moim interesie i nie chcę walczyć z generowanymi tytułami produktów. Jednakże zasób zgłaszania zmian wymaga dodania jednego zdjęcia i nazwy produktu, których nie chcę zmieniać ani w ogóle dodawać. Moim jedynym celem jest aktualizacja parametrów przez wzgląd na niedoskonałość opisanych produktów przez klienta.

Zatem moje pytanie brzmi - czy jeżeli podam zmienione parametry oraz inną niż obecna nazwę produktu, to czy Allegro mając "pretensje" do nazwy produktu odrzuci zmiany całkowicie? Czy zmiana zostanie wprowadzona częściowo? W takim razie, czy nie myśleliście o zgłaszaniu zmian bez obowiązkowego tytułu produktu i zdjęcia? Szczerze mówiąc te wymogi mnie trochę blokują, bo nie chcę specjalnie pobierać produktu przed zgłoszeniem zmian, aby uzupełnić istniejącymi danymi wymagane pola. Zapisuje tylko UUID w bazie danych i na tej podstawie chcę aktualizować parametry produktu w katalogu.

**Comment by Lukasz-Zurek** [comment]
@hahyes Sprawę konsultuję z zespołem odpowiedzialnym za ten proces. Wkrótce wrócę z pewną informacją.

**Comment by Lukasz-Zurek** [comment]
@hahyes Przepraszam, że musiałeś czekać, ale zależało mi na pewnej informacji.

Każda sugestia jest rozpatrywana indywidualnie i odrzucając propozycję zmiany nazwy nasz Serwis może zaakceptować inne sugestie np. dotyczące kodu producenta, czy też innych przekazanych parametrów. Oznacza to, że zawsze weryfikujemy wszystkie przekazywane parametry.

W pełni rozumiem, że zgłaszanie zmian bez obowiązkowego tytułu produktu i zdjęcia byłoby przydatną funkcjonalnością, dlatego sugestię przekażę do właściwego zespołu w celu analizy.
