### ISSUE TITLE
How to list through channeladvisor

### ISSUE THREAD

**Issue by emilyze** [allegro/allegro-api#5967]
I use channeladvisor to list the listing, but the system reports an error: Shipping rate with given name not found. I have tried to fill in free, 0, DHL, Deutsche post, but the original error is still reported. The customer service of channeladvisor suggested that I contact the customer service of allegro. How should I fill in the content of this section?

**Comment by MaciejFrackowiak** [comment]
Here on GitHub, we support topics related to the functioning of Allegro API. If you have questions about Channel Advisor integration, please contact directly with Allegro Help by [contact form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
