### ISSUE TITLE
Which API can I use to verify whether this ean already exists on the platform

### ISSUE THREAD

**Issue by yx252419** [allegro/allegro-api#5968]
Which API can I use to verify whether this ean already exists on the platform

**Comment by Lukasz-Zurek** [comment]
You can use [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) to search for products in our Catalog, e.g. GET /sale/products?phrase=888462600712&mode=GTIN. You will find more information in [our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-find-a-product).

**Comment by yx252419** [comment]
I searched ean:0782043141727, but I couldn't find it





Request parameters：
{"headers":{"Accept":"application/vnd.allegro.public.v1+json","Content-Type":"application/vnd.allegro.public.v1+json","Authorization":"Bearer ..."},"query":{"phrase":"0782043141727","mode":"GTIN"}}

Return parameters：
{"products":[],"categories":{"subcategories":[{"id":"5","name":"Dom i Ogr\u00f3d","count":0},{"id":"11763","name":"Dziecko","count":0},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","count":0},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma i us\u0142ugi","count":0},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","count":0},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","count":0},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","count":0},{"id":"3","name":"Motoryzacja","count":0},{"id":"20782","name":"Nieruchomo\u015bci","count":0},{"id":"3919","name":"Sport i turystyka","count":0},{"id":"258832","name":"Supermarket","count":0},{"id":"1429","name":"Uroda","count":0},{"id":"121882","name":"Zdrowie","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[],"nextPage":null}

**Comment by Lukasz-Zurek** [comment]
I can confirm it. We do not have a product with EAN: 0782043141727 in our database.

**Comment by yx252419** [comment]
![image](https://user-images.githubusercontent.com/23545157/182585636-07078e3b-82c6-4460-a439-6308e2dda4f6.png)

**Comment by Lukasz-Zurek** [comment]
@yx252419 It is not a product. It is an offer. The resource which I have just sent you - is dedicated for product searching (in our product database). We do not have a product with EAN: 0782043141727 in our database.
