### ISSUE TITLE
informacje o przypięciu do katalogu produktów i SMART w zasobie offers/list

### ISSUE THREAD

**Issue by barpas** [allegro/allegro-api#5969]
mój pracodawca otrzymał dostęp do zasobu offers/listing w celu stworzenia pewnej aplikacji
zgodnie z instrukcjami które otrzymałem potrzebuję się dowiedzieć czy dana oferta jest objęta programem SMART
oraz czy jest przypięta do katalogu produktów
niestety zasób nie podaje tych informacji 
o ile z pierwszym problemem poradzić jest sobie łatwo używając filtrów (choć trzeba wykonać 2 zapytania zamiast jednego)
o tyle nie wiem jak poradzić sobie z drugim (czy jest przypięta do katalogu produktów)

stąd pytanie: czy jest jakaś możliwość dowiedzenia się czy dana oferta (wynik wyszukiwania przy pomocy zasobu offers/listing) jest przypięta do katalogu produktów ?

i drugie: czy jest jakaś szansa na to by ww. informacje znalazły się w odpowiedzi tak żeby nie trzeba było kombinować ?

**Comment by Lukasz-Zurek** [comment]
> stąd pytanie: czy jest jakaś możliwość dowiedzenia się czy dana oferta (wynik wyszukiwania przy pomocy zasobu offers/listing) jest przypięta do katalogu produktów ?

Nie. [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) nie zwraca tego typu informacji.

> i drugie: czy jest jakaś szansa na to by ww. informacje znalazły się w odpowiedzi tak żeby nie trzeba było kombinować ?

Nie. Generalnie nie planujemy rozszerzać zakresu danych zwracanych w [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).

**Comment by barpas** [comment]
do pierwszego nie: 
wiem że nie zwraca - pytam czy jest jakiś inny sposób by przy pomocy restapi dowiedzieć się czy oferta jest przypięta do katalogu produktów

**Comment by Lukasz-Zurek** [comment]
Możesz skorzystać jedynie z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET), filtrując wg. parametru **product.id.empty** , np. GET /sale/offers?product.id.empty=false - wyszukasz wtedy oferty, które posiadają przypisany produkt (product.id). Pamiętaj jednak, że [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) jest odpowiednikiem wyszukiwarki w Serwisie, w związku z czym są tutaj wszystkie oferty, różnych Sprzedawców. Jeśli natomiast chcesz sprawdzić wybrane oferty za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - musisz być autoryzowany jako Sprzedawca.

Innymi słowy - sposób, który podesłałem wyżej - przyda się wyłącznie w odniesieniu do ofert, do których masz dostęp. Nie sprawdzisz tutaj każdej oferty, którą znalazłeś za pomocą [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing).
