### ISSUE TITLE
Pole na numer magazynowy lub SKU firmy

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#597]
Częstą praktyką jest to że w tytule aukcji pojawia się dziwne oznaczenie (SKU) które pozwala sprzedawcy na identyfikację towaru we własnym systemie sprzedażowym. Jednak obecne zmiany w regulaminie Allegro nakazują usunięcie tego typu rzeczy... mamy pole EAN ale często jest tak że producent nie posługuje się EANami tylko swoimi własnymi kodami. 
Aby sprostać regulaminowi potrzebne jest pole które będziemy mogli wysyłać razem z ofertą oraz pobierać przy ściąganiu transakcji. Myślę że jest to problem który dotyczy olbrzymiej liczy sprzedających, a do tego takie pole przydało by się do integracji z programami sprzedażowymi.

**Comment by TimothyKoval** [comment]
Czy Wasze programy sprzedażowe nie potrafią przypisać numeru aukcji do danego produktu?

**Comment by mirkosmuz** [comment]
Zgadzam się z Onixarts. Wśród naszych klientów mamy takie sytuacje. 
Do tego dochodzą klienci którzy mają powyżej 50 000 trwających ofert które są na licytacjach np. 7 dni i bez przerwy zmieniają im się nr aukcji. 
To było by wielkie ułatwienie.

**Comment by TimothyKoval** [comment]
Czemu dwa różne programy zajmują się jedną rzeczą?

**Comment by Onixarts** [comment]
Bo tak. Nie każdy biznes jest prowadzony przez każdego tak samo. A jako najprostszy przykład masz aukcje ze wznowieniem wystawiane na 4 dni automatycznie przez Allegro (program A), odbierane dane przez program do obsługi transakcji (program B). I już nie masz żadnego sztywnego powiązania pomiędzy nową aukcją a zakupionym towarem.

**Comment by mirkosmuz** [comment]
TimothyKoval soft który tworzymy rozwiązuje problemy których inny soft na rynku nie daje rady załatwić. Więc twoje rady są nie przydatne. Będę wdzięczny jak ktoś z Allegro się wypowie.

**Comment by TimothyKoval** [comment]
Co z tego że rozwiązuje, skoro tworzy kolejne?

https://xkcd.com/927/

**Comment by martacronic** [comment]
Nie jestem z Allegro, ale może chodzi Ci o pole external w drafcie 
[Dokumentacja](https://developer.allegro.pl/sale/#new-offer)

**Comment by Onixarts** [comment]
Ale czemu Ty mi to mówisz. Ja Ci mówię jak pracują ludzie. A z naszego softu korzysta wielu sprzedawców. Więc my nic tutaj nie kleimy z, jak to powiedziałeś śmieci, tylko takie są realia e-handlu w pl.

**Comment by TimothyKoval** [comment]
A ten wasz soft to ten A któremu brakuje funkcjonalności B, czy B któremu brakuje A?

**Comment by Onixarts** [comment]
Czy Ty próbujesz sprzedać nam swoje super rozwiązanie czy o co Ci chodzi? :) Jest potrzeba, która wynika z działalności sprzedawców i ktoś o nią pyta, a Ty tutaj uprawiasz jakiś szemrany marketing na zasadzie wy robicie syf, tylko moje rozwiązanie jest najlepsze. Daj spokój skoro nie wnosisz nic do tematu i po prostu odpuść sobie.

**Comment by TimothyKoval** [comment]
Nie ma problemu. Tylko odpowiedz na pytanie.

**Comment by Onixarts** [comment]
Nie czuję takiej potrzeby, poza tym dałem już orzykład wczesniej :).

**Comment by TimothyKoval** [comment]
Tak więc już widać gdzie leży problem :)

**Comment by Onixarts** [comment]
Już? Ulżyłeś sobie? Poczułeś się przez to lepszy? Gdzie jak gdzie ale tutaj się takich ludzi nie spodziewałem.

**Comment by TimothyKoval** [comment]
Oh, oh.. A cóż takiego powiedziałem, że jego eminencja się tak obruszyła?

**Comment by Onixarts** [comment]
Nic, po prostu szkoda mi czasu na rozmowę z Tobą. Papatki.

**Comment by TimothyKoval** [comment]
Papa :)

**Comment by MarcinLuczak** [comment]
@mirkosmuz jeżeli dobrze Cię zrozumiałem, to pole **external**, o którym wspomniał wcześniej @martacronic powinno wystarczyć do Twoich potrzeb. Pole opisaliśmy w tym [przykładowym requeście](https://developer.allegro.pl/sale/#new-offer).

**Comment by mirkosmuz** [comment]
Super !!! Właśnie o to mi chodziło. Dziękuję za pomoc.

**Comment by imper86** [comment]
@TimothyKoval po co trollujesz?
a reszta mogłaby przestać karmić trolla, najlepiej by było usunąć wszystkie komentarze, które nic nie wnoszą do tematu.

**Comment by mack3d** [comment]
@MarcinLuczak czy pole external pojawi się w całym serwisie czy będzie tylko w wybranych kategoriach?

**Comment by MarcinLuczak** [comment]
@mack3d nie planujemy ograniczać tego pola tylko do wybranych kategorii.
