### ISSUE TITLE
Zarządzanie obrazkami

### ISSUE THREAD

**Issue by Zbigi** [allegro/allegro-api#5971]
Dzień dobry,
gdy próbuje aktualizować  ofertę za pomocą Patch dostaje błąd 422
 z informacją 
 "message": "Offer image `https://a.allegroimg.com/original/1176b7/f048c1b0489f9d2f724cc21c58c6,
			https://a.allegroimg.com/original/1176b7/f048c1b0489f9d2f724cc21c58c6,
			https://a.allegroimg.com/original/11018f/0e16b0354912949808aa90ea567e,
			https://a.allegroimg.com/original/114cbd/3447e5a841a683b954e441fc330e,
			https://a.allegroimg.com/original/114173/219567fe42048f7be2922ce84760,
			https://a.allegroimg.com/original/11ba21/c564011b4119856ae90de1c9dfee,
			https://a.allegroimg.com/original/1100d8/fc2d95084a85a7c2d478e35e7c50,
			https://a.allegroimg.com/original/1132d3/fe78fc1d46f8b57bacaa75b7bd72,
			https://a.allegroimg.com/original/11fbd6/a3ab33df470abbe51ffa7dd5da33,
			https://a.allegroimg.com/original/115947/b5e3aafd40ea806661f55296a4a4,
			https://a.allegroimg.com/original/11502a/1501b754411a8ea95309b0de5410,
			https://a.allegroimg.com/original/114979/77a1a03d43249cb553f0511d5cea,
			https://a.allegroimg.com/original/110f99/1cc156094218b84b9603fc5e6fea,
			https://a.allegroimg.com/original/11c599/b100f3e744528b75249c6269ee31,
			https://a.allegroimg.com/original/1176b7/f048c1b0489f9d2f724cc21c58c6,
			https://a.allegroimg.com/original/1176b7/f048c1b0489f9d2f724cc21c58c6,
			https://a.allegroimg.com/original/11018f/0e16b0354912949808aa90ea567e,
			https://a.allegroimg.com/original/1188eb/f8f7760e4feba6afbab318676fb4,
			https://a.allegroimg.com/original/11f3b4/a261e80e4891b0b57e9bc9185c37,
			https://a.allegroimg.com/original/11235b/cc59d7c14da9aec93e366f63d4fc,
			https://a.allegroimg.com/original/11363e/1b262368402582c1530e24c5b2d2,
			https://a.allegroimg.com/original/117e82/5cbfe5f544dc932be49b7d4120f8,
			https://a.allegroimg.com/original/115748/95e4fb824810bcf7323edc8ee52e,
			https://a.allegroimg.com/original/116c0f/66df7cb14a6c80cfde09c29a35b0,
			https://a.allegroimg.com/original/110a7a/7c20c56144bd8514705c2d39f09c,
			https://a.allegroimg.com/original/1104be/9c5ad14f4d0dbac8ce6e3cdbb8fd,
			https://a.allegroimg.com/original/110990/6a4b7159462fafa67c3a570976e6,
			https://a.allegroimg.com/original/1143e2/13bbbbe64098862e51c0ca1c1949` was specified multiple times.",

Kiedyś zadałem tutaj pytanie,  czy mam zarządzać grafikami otrzymałem informację, że Państwa system się tym zajmie.
W ofercie mam 15 grafik a reszta z tej listy powyżej, to powtórzenia i nie wiem jak je usunąć, co bym chętnie zrobił

**Comment by MaciejFrackowiak** [comment]
Proszę podaj przykładowe trace-id wywołania.

**Comment by Zbigi** [comment]
co to znaczy trace id? Skąd mam to zdobyć?

**Comment by Zbigi** [comment]
trace-id: e84120e2122ab80f

**Comment by MaciejFrackowiak** [comment]
Dziękuję za przykład. W Twoim requeście znalazłem kilka nieprawidłowości:
1. Kolejne zdjęcia podajesz jednym "ciągiem", a zgodnie z dokumentacją każde kolejne powinno być dodane jako string - obecnie: "adres_zdjecia1, adres_zdjecia2, adres_zdjecia3", a powinno być: "adres_zdjecia1", "adres_zdjecia2", "adres_zdjecia3" - zgodnie z [naszym poradnikiem](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#obsluga-zdjec);
2. W tablicy "images" przekazujesz te same zdjęcia - https://a.allegroimg.com/original/......24cc21c58c6 wystąpiło 4 razy;
3. Tablica "images" zawiera de facto dwa razy te same ciągi zdjęć, o których wspomniałem w punkcie 1.

**Comment by Zbigi** [comment]
Robię konkatenację stringów a powinny być elementy tablicy, ok rozumiem

**Comment by Zbigi** [comment]
Przy definicji Patch w opisie jest
"images": [

    "string"

],
natomiast przy Post

"images": [

{

    "url": "string"

}
i teraz co jest prawidłowe, bo przy Patch wyraźnie jest to jeden string a przy POST

**Comment by MaciejFrackowiak** [comment]
Pierwsza strukura dotyczy zasobów /sale/product-offers, druga natomiast /sale/offers.

**Comment by Zbigi** [comment]
I tak zostało zaakcpetowane
 "images": [
        "https://a.allegroimg.com/original/119510/f59768b343d1ba2405df0c62c1ff,https://a.allegroimg.com/original/11b5f6/7ffdcca64ce3bed8966b2452ee2c,https://a.allegroimg.com/original/11acb9/5502fb7b4e46bd0bfdf4b9542fba,https://a.allegroimg.com/original/11b43d/b1ae8e5549a7845015b9c3b30185,https://a.allegroimg.com/original/112262/920758cd4a9b94ab4373be5789cd,https://a.allegroimg.com/original/111de4/f2f6fc974f8abe08bb0997a0db52,https://a.allegroimg.com/original/111a55/e90206774f949ae8a5917590aa84,https://a.allegroimg.com/original/113408/4457eb1447b5a510a9d3c95504a8,https://a.allegroimg.com/original/11d179/df57f760492bb383c68f991eb4ae,https://a.allegroimg.com/original/1125ee/803a59d14a93b9011a4bd47de815,https://a.allegroimg.com/original/111b2c/08d2ceb745b3801e949b08428f22,https://a.allegroimg.com/original/11da58/4b8ca9a64071ad28d741ce626bc3,https://a.allegroimg.com/original/11f0e5/f9c092a24a56b68dbb17e2a40024"
    ],
czyli jako 1 string

**Comment by Zbigi** [comment]
Szkoda, że nie jest tak samo, teraz muszę napisać nową funkcje do tego:(

**Comment by MaciejFrackowiak** [comment]
Zasoby /sale/product-offers powstały w odpowiedzi na uproszczenie dotychczasowych składni i rozwiązań - dlatego dla nich kolejne zdjęcia w tablicy "images" podajemy jako stringi - [tu](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#dodaj-zdjecia-produktu) jednoznaczny przykład.
