### ISSUE TITLE
Sprawdzanie statusu przesyłek DPD i UPS

### ISSUE THREAD

**Issue by R3VANEK** [allegro/allegro-api#5972]
Dzień dobry

Czy da się za pomocą REST API sprawdzić status doręczenia przesyłki przez kuriera sposobem Allegro DPD lub Allegro UPS?

Pobieram odpowiedni waybill zamówienia używając ```GET order/checkout-forms/{id}/shipments```
ale używając tak uzyskanego waybill w metodzie ```GET order/carriers/ALLEGRO/tracking?waybill={waybill}```trackingDetails jest zawsze nullem

**Comment by Lukasz-Zurek** [comment]
Niestety nie, obecnie możesz śledzić wyłącznie przesyłki, w których przewoźnikiem jest Allegro.

Mamy jednak w planach zasób, dzięki któremu sprawdzisz historię statusów wskazanej przesyłki nadanej za pośrednictwem "Wysyłam z Allegro". Nie jestem jednak w stanie zadeklarować konkretnego terminu wdrożenia. Warto śledzić nasze [aktualności](https://developer.allegro.pl/news/).

**Comment by R3VANEK** [comment]
Rozumiem. Czy jest jakaś inna możliwość żeby to zrobić np. z wykorzystaniem API DHL lub UPS?

**Comment by Lukasz-Zurek** [comment]
@R3VANEK Obawiam się, że nie ma innej możliwości, a już z pewnością nie w naszym publicznym API.
