### ISSUE TITLE
brak zdarzenia BUYER_CANCELLED w dzienniku 

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#5974]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Do zakupu a633c221-1481-11ed-b2a7-5f3cabb16f99 (utworzone 2022-08-05, ok. 07:46) klient dokonał wpłaty, a następnie zgłosił zwrot. Równocześnie otrzymałem powiadomienie mailowe, o zwrocie użytkownika o godzinie 09:44.  Niestety, w dzienniku zdarzeń Allegro nie pojawiło się zdarzenie BUYER_CANCELLED aż do tej pory czyli do 12:45. Dlaczego?

Sergiusz

**Comment by Lukasz-Zurek** [comment]
Status BUYER_CANCELLED zwrócimy w [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) tylko wtedy, gdy Kupujący anuluje zakup, a w opisanej sytuacji Klient go nie anulował, tylko wystąpił o zwrot towaru. Dla zwrotu towaru nie zwracamy dodatkowego statusu.

Więcej informacji na temat anulowania zakupu przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#anulowanie-zamowienia) oraz w [Pomocy Allegro](https://allegro.pl/pomoc/dla-sprzedajacych/wystawianie-oferty-przez-formularz/anulowanie-zakupu-informacje-dla-sprzedajacych-KMOZGKlO5fR#w-ktorych-kategoriach-nie-mozna-anulowac-zakupu).

**Comment by hahyes** [comment]
> Status BUYER_CANCELLED zwrócimy w [GET /order/events](https://developer.allegro.pl/documentation/#operation/getOrderEventsUsingGET) tylko wtedy, gdy Kupujący anuluje zakup, a w opisanej sytuacji Klient go nie anulował, tylko wystąpił o zwrot towaru. Dla zwrotu towaru nie zwracamy dodatkowego statusu.

@Lukasz-Zurek Czy w takim wypadku zwrot nie powinien być traktowany równoznacznie z anulowaniem zamówienia? Jeżeli zamówienie nie zostało jeszcze zrealizowane, to zgłoszenie zwrotu to praktycznie anulowanie zamówienia. Wszak sprzedawca  nie będzie go realizował tak czy tak. Myślę, że to byłoby bardziej logiczne zachowanie. Ot, taka sugestia.

**Comment by Lukasz-Zurek** [comment]
@hahyes Brakuje faktycznie statusu dla tego typu zdarzenia, a przyznajmy szczerze - anulowanie zakupu i zwrot towaru dotyczą identycznej sytuacji - odstąpienia od umowy.

Dzięki za sugestię. Przekaże ją do odpowiedniego zespołu.
