### ISSUE TITLE
Testing order service in sandbox environment

### ISSUE THREAD

**Issue by furkanakharman** [allegro/allegro-api#5975]
Greetings,
I've been working on Allegro rest api for an integration project. I wanted to test my application in sandbox environment. I've completed my registration.

I want to fetch order details using /order/checkout-forms service however I am getting zero orders in response. How is order service suppose to work in sandbox environment?
Do I have to publish a product and an offer then buy it from another sandbox account?
I've checked the documentation but couldn't find anything about fetching orders in sandbox environment.

Appreciate the help.

**Comment by Lukasz-Zurek** [comment]
> I want to fetch order details using /order/checkout-forms service however I am getting zero orders in response. How is order service suppose to work in sandbox environment? Do I have to publish a product and an offer then buy it from another sandbox account? I've checked the documentation but couldn't find anything about fetching orders in sandbox environment.

Yes, exactly. You will have to register another account on the Allegro Sandbox and make some orders. Please note the fact that you will have to use our simulator, so the payment process is easy. Then using /order/checkout-forms, being authorized as a Seller - you will be able to retrieve information about the orders.

**Comment by furkanakharman** [comment]
Understood, thanks for the quick response. However in order to create an offer I must activate the sandbox account for the sales as I see, I tried to activate sandbox account from Account > Sales > Activate Sales and filled up the information and clicking next I'm getting ERR_CONNECTION_RESET on my browser on this url allegro .pl. allegrosandbox. pl/moje-allegro/moje-konto/dane-konta, any ideas how can I activate sales for the sandbox account? Thanks!

**Comment by Lukasz-Zurek** [comment]
Please give me your Allegro Sandbox account's login. I will check it out.

**Comment by furkanakharman** [comment]
> Please give me your Allegro Sandbox account's login. I will check it out.

Where should I send it to, is it okay if I share the email/password here?

**Comment by Lukasz-Zurek** [comment]
@furkanakharman Do not provide your password. All I need is your login. It is a test environment so you can send me right here.

**Comment by furkanakharman** [comment]
Alright, here is the account I use for the sandbox besir.yucesoy@gsscommerce.com

**Comment by Lukasz-Zurek** [comment]
@furkanakharman Your account is active. If you want to have a business account - please transform it via [this site](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by furkanakharman** [comment]
Perfect thanks, however using "List using form" to add new offer doesn't work. It redirects me to staging-lokalnie.allegrogroup.com/oferty/wystaw but it's unreachable. Is there a way to create an offer using gui in sandbox environment?

**Comment by furkanakharman** [comment]
Any ideas on this? I asked my client to create an offer and buy it from an another account (in sandbox) so I can test the api however they're unable to do because of the error. Are we missing something?

**Comment by PrzemyslawLukanowski** [comment]
In this case, please use our alternative link - https://allegro.pl.allegrosandbox.pl/offer/?lokalnie. Sorry for the inconvenience.

**Comment by furkanakharman** [comment]
Thank you everything seems to be working right now. Cheers.
