### ISSUE TITLE
Problem z sale/product-offers

### ISSUE THREAD

**Issue by tomasz244** [allegro/allegro-api#5976]
Dzień dobry.
Mam przykładowy request 

"productSet": [{ 
"product": { 
"name":"MASKA POKRYWA SILNIKA PEUGEOT 1007", 
"category":{ "id":"254559" }, 
"parameters":[
{ "name": "EAN", "values": ["7901K9"] },
{ "id": "11323", "values": ["11323_1"] },
{ "id": "127415", "values": ["127415_45"] },
{ "id": "129591", "values": ["129591_1"] },
{ "id": "214434", "values": ["214434_266978"] }
], 
"images": [ "http://strefalakiernika.pl/phbdnowy/allegrofiles/1630949646_20210902_150146.jpg" ] }}], 
"name": "MASKA POKRYWA SILNIKA PEUGEOT 1007", "category": {"id": "254559"}, 
"location": { "city": "Mosina-Drużyna", "countryCode": "PL", "postCode": "62-050", "province": "WIELKOPOLSKIE" }, 
"sellingMode": { "format": "BUY_NOW", "price": { "amount": "230", "currency": "PLN" } }, 
"stock": { "available": 1, "unit": "UNIT" } 
"payments": { "invoice": "VAT" }, 
"description": {"sections": [{"items": [{"type": "Przedmiot aukcji: MASKA SILNIKA PEUGEOT 1007" }]}] }, 
"delivery": { 
"handlingTime": "PT24H", "shippingRates": ce7503c6-4168-4988-ae92-7ff8933e17bb, }, 
"publication": { "duration": "PT24H" }, 
"afterSalesServices": { "impliedWarranty": {"id": "167e78cf-d128-49f0-8c35-f953d88d7aaf"}, "returnPolicy": {"id": "61a6cfe7-d21f-4d54-b2d5-04064e46be22"}, "warranty": {"id": "c1546115-fb49-43bb-8099-804f13d4fc3f"} 

za pomoca  /sale/product-offers próbóje wystawić akcje z prduktem. 
<code>$api->sale->{'product-offers'}->post->($zmienna);</code>
niestety nic się nie dzieje, nie wiem czy to błąd złego request ?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id Twojego wywołania. Na pewno kod EAN, który podajesz nie jest prawidłowym kodem typu GTIN.

**Comment by tomasz244** [comment]
W kategorii w której próbuje wystawić ofertę z produktem nie jest wymagany kod EAN. Produkt jest tworzony po nr OEM części samochodowej.
Czyli 
<code>
"name":"MASKA POKRYWA SILNIKA PEUGEOT 1007",
"category":{ "id":"254559" },
"parameters":[
{ "id": "11323", "values": ["11323_1"] },
{ "id": "127415", "values": ["127415_45"] },
{ "id": "129591", "values": ["129591_1"] },
{ "id": "214434", "values": ["214434_266978"] }
],
</code> 
czyli przekazuje parametry produktu bez podawania kodu EAN?
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Spójrz proszę na [nasz poradnik](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#uzupelnij-kategorie-i-parametry), gdzie opisaliśmy różne sposoby przekazywania parametrów i ich wartości. Trudno mi się natomiast odnieść do pozostałej struktury, ponieważ wklejasz tu "ucięty" request.
