### ISSUE TITLE
Kanlux - SMART wysyłka do punktów API

### ISSUE THREAD

**Issue by KarolMryka** [allegro/allegro-api#5977]
Firma Kanlux S.A. korzystająca z usług DPD Polska chce rozpocząć obsługę . wysyłkę do punktów. 
Obecnie paczki nadajemy w swoim programie korzystając z webserwisu DPD Polska. 
Proszę o przesłanie dokumentacji / informacji jak obsłużyć wysyłkę do punktów w ramach SMART ALLEGRO.

Karol Mryka
Z-ca Dyrektora ds. IT 
605-074-563

**Comment by hahyes** [comment]
Z usług DPD można korzystać poprzez wbudowaną usługę Wysyłam z Allegro: 
https://allegro.pl/dla-sprzedajacych/wysylam-z-allegro-bezplatne-narzedzie-do-nadawania-przesylek-9gwBoLx2EIv
Poradnik do API: https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY
Dokumentacja API: https://developer.allegro.pl/documentation

Miłego czytania. :)

**Comment by MaciejFrackowiak** [comment]
Z naszej strony nic więcej dodać nie mogę aniżeli @hahyes już wskazał materiały i dokumentację - dziękuję.

**Comment by KarolMryka** [comment]
Rozumiem, że dokumentacja opisuje szereg komend do tworzenia przesyłek w Allegro - czyli nie w DPD? 
Proszę nakreślić mi biznesowo jak wygląda obieg dokumentów. My chcemy i MUSIMY nadal rejestrować paczki w naszym systemie tak jak robimy to obecnie, natomiast chcemy wdrożyć usługę dostawy do punktu - wymagane do SMART. Stąd pytanie którą część / który API winniśmy odpalić, aby dodać tę usługę do naszego systemu (obsłużyć ją).

**Comment by MaciejFrackowiak** [comment]
Dokumentacja opisuje niezbędne zasoby do obsługi jakiejkolwiek metody dostawy dostępnej w ramach Wysyłam z Allegro, również DPD. W związku z tym każdy jeden z wymienionych zasobów powinien zostać obsłużony, aby został zapewniony prawidłowy przebieg procesu - od samego złożenia zlecenia, po krok z pobraniem etykiety czy też zamówieniem podjazdu kuriera.
