### ISSUE TITLE
błąd /sale/product-offers

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#5978]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

po wystawieniu oferty (/sale/product-offers):
{
    "id": null,
    "tax": {
        "id": "b763d782-572a-47db-8752-8b2cb32b3d0a",
        "rate": null,
        "subject": null,
        "exemption": null,
        "percentage": null
    },
    "name": "F&F Sterownik Radiowy Dwukanau0142owy LED 12VDC",
    "stock": {
        "unit": "UNIT",
        "available": 376
    },
    "images": [
        {
            "url": "https://a.allegroimg.com/original/11b49e/c04e617c4abb8e8ac8cdf64cd73f"
        },
        {
            "url": "https://a.allegroimg.com/original/11d60d/bc67b16b41f69febccc514bea0d0"
        },
        {
            "url": "https://a.allegroimg.com/original/11a822/fcc7b46b47ddaa27ca36572bac2a"
        },
        {
            "url": "https://a.allegroimg.com/original/11f285/1bfe01c54fe78adb6d343817915a"
        },
        {
            "url": "https://a.allegroimg.com/original/11074d/745b5113433bbe1b66b3ec476443"
        }
    ],
    "product": {
        "id": "82a6ccf6-1b45-4025-b9f1-5fbb27fefaf8"
    },
    "category": {
        "id": "251247"
    },
    "delivery": {
        "handlingTime": "P2D",
        "shipmentDate": null,
        "shippingRates": {
            "id": "284affe2-cd17-49b2-afd8-b76fa629fee1"
        },
        "additionalInfo": ""
    },
    "external": {
        "id": "FW-LED2D"
    },
    "location": {
        "city": "Wschowa",
        "postCode": "67-400",
        "province": "LUBUSKIE",
        "countryCode": "PL"
    },
    "payments": {
        "invoice": "VAT"
    },
    "promotion": {
        "bold": false,
        "highlight": false,
        "emphasized": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": null
    },
    "sizeTable": null,
    "parameters": {
        "0": {
            "id": "11323",
            "values": null,
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        },
        "4": {
            "id": "229205",
            "values": null,
            "valuesIds": [
                "229205_340245"
            ],
            "rangeValue": null
        }
    },
    "productSet": [
        {
            "product": {
                "name": "F&F Sterownik Radiowy Dwukanau0142owy LED 12VDC",
                "images": [
                    "https://a.allegroimg.com/original/11b49e/c04e617c4abb8e8ac8cdf64cd73f",
                    "https://a.allegroimg.com/original/11d60d/bc67b16b41f69febccc514bea0d0",
                    "https://a.allegroimg.com/original/11a822/fcc7b46b47ddaa27ca36572bac2a",
                    "https://a.allegroimg.com/original/11f285/1bfe01c54fe78adb6d343817915a",
                    "https://a.allegroimg.com/original/11074d/745b5113433bbe1b66b3ec476443"
                ],
                "category": {
                    "id": "251247"
                },
                "parameters": [
                    {
                        "id": "17448",
                        "values": [
                            1
                        ]
                    },
                    {
                        "id": "224017",
                        "values": [
                            "FW-LED2D"
                        ]
                    },
                    {
                        "name": "EAN",
                        "values": [
                            "5908312599326"
                        ]
                    },
                    {
                        "id": "234181",
                        "valuesIds": [
                            "234181_585781"
                        ]
                    },
                    {
                        "id": "237222",
                        "values": [
                            "F&Wave"
                        ]
                    },
                    {
                        "id": "248155",
                        "valuesIds": [
                            "248155_862058"
                        ]
                    }
                ]
            }
        }
    ],
    "attachments": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "url": "https://a.allegroimg.com/original/11b49e/c04e617c4abb8e8ac8cdf64cd73f",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>Sterownik Dwukanau0142owy LED Radiowy</h2><p><b>F&amp;F FW-LED2D</b></p><p>u2714ufe0f <b>Do sterowania tau015bmami LED lub </b>u015bciemnialnymi u017caru00f3wkami LED 12V</p><p>u2714ufe0f Wspu00f3u0142praca<b> z nadajnikami zdalnego sterowania F&amp;Wave</b></p><p>u2714ufe0f Mou017cliwou015bu0107<b> sterowania z maksymalnie 8 nadajniku00f3w</b></p><p>u2714ufe0f Przeznaczony do montau017cu<b> na szynie 35 mm</b></p><p>u2714ufe0f Retransmisja rozkazu00f3w z nadajnika <b>- mou017cliwou015bu0107 zwiu0119kszenia zasiu0119gu zdalnego sterowania;</b></p><p>u2714ufe0f Miu0119kki start - <b>pu0142ynne zau0142u0105czenie/wyu0142u0105czenie ou015bwietlenia</b></p><p><b>Zestaw sku0142ada siu0119 z</b></p><ul><li><b>1 szt. </b>Sterownik dwukanau0142owy<b> LED FW-LED2D</b></li><li>Instrukcja obsu0142ugi w<b> ju0119zyku polskim</b></li></ul><p>u274c <b>Szyna TH-35 nie jest czu0119u015bciu0105 zestawu!</b></p><p><b>Pilot do sterowania radiowego dostu0119pny w naszej ofercie!</b></p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>Czym jest System F&amp;Wave-radiowy?</h2><p>u27a1 Jeu017celi cenisz sobie komfort codziennego u017cycia, <b>zdalne sterowanie radiowe F&amp;Wave</b> jest zdecydowanie dla Ciebie.</p><p>u27a1 F&amp;Wave to <b>zdalne sterowanie</b> ou015bwietleniem ( w tym pu0142ynna regulacja jasnou015bci ou015bwietlenia, taku017ce za pomocu0105 <b>uniwersalnego u015bciemniacza oswietlenia FW-D1D</b>), sterowanie roletami, u017caluzjami, markizami, bramami wjazdowymi i garau017cowymi oraz innymi urzu0105dzeniami w domu.</p><p><b>Radiowy system zdalnego sterowania F&amp;Wave</b> to przede wszystkim:</p><ul><li><b>u0141atwy montau017c,</b></li><li><b>Prosta obsu0142uga,</b></li><li><b>u0141atwa konfiguracja elementu00f3w systemu,</b></li><li><b>Mou017cliwou015bu0107 samodzielnego montau017cu,</b></li><li><b>Atrakcyjna cenna.</b></li></ul>"
                    },
                    {
                        "url": "https://a.allegroimg.com/original/11d60d/bc67b16b41f69febccc514bea0d0",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https://a.allegroimg.com/original/11a822/fcc7b46b47ddaa27ca36572bac2a",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>Retransmisja sygnau0142u-unikalna cecha systemu radiowego sterowania F&amp;Wave</h2><p>Unikalnu0105 cechu systemu F&amp;Wave jest <b>retransmisja sygnau0142u</b> - kau017cdy odbiornik, ktu00f3ry odbierze sygnau0142 steruju0105cy z nadajnika, automatycznie przesyu0142a go dalej. Zwiu0119ksza to znacznie zasiu0119g sterowania w przypadku odbiorniku00f3w oddalonych od nadajnika na tyle, u017ce znajduju0105 siu0119 poza zasiu0119giem pierwotnego sygnau0142u. </p><p><b> Jakie urzu0105dzenia tworzu0105 system zdalnego sterowania radiowego F&amp;Wave?</b></p><p> Na system sku0142adaju0105 siu0119:</p><ul><li> <b>odbiorniki</b> </li></ul><p>Urzu0105dzenia wykonawcze. Wyprodukowane su0105 w wersji do montau017cu w puszce podtynkowej u00d860 lub do montau017cu na szynie TH-35 (szerokou015bu0107 1 moduu0142u tj. 17,5 mm). O<b>bok odbiorniku00f3w w systemie F&amp;Wave wystu0119puju0105 ru00f3wnieu017c </b></p><ul><li><b>nadajniki</b>.</li></ul><p>Su0105 to podru0119czne piloty lub urzu0105dzenia <b>do montau017cu w puszce podtynkowej (przyciski nau015bcienne, taku017ce bateryjne).</b></p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>Dane techniczne</h2><ul><li><b>Napiu0119cie zasilania:</b> 10u00f716 V DC</li><li><b>Liczba kanau0142u00f3w: </b>2</li><li><b>Funkcja u015bciemniacz: </b>12 V</li><li><b>Weju015bcia sterownicze:</b> 2</li><li><b>Sygnau0142 steruju0105cy</b>: -</li><li><b>Obciu0105u017calnou015bu0107 wyju015bcia (AC-1):</b> 6 A /12 V</li><li><b>Element wykonawczy: </b>tranzystor</li><li><b>Czu0119stotliwou015bu0107 radia:</b> 868 MHz</li><li><b>Przyu0142u0105cze:</b> zaciski u015brubowe 2,5 mmu00b2</li><li><b>Moment dokru0119caju0105cy: </b>0,4 Nm</li><li><b>Pobu00f3r mocy czuwanie/praca: </b>0,25 W / 0,4 W</li><li><b>Temperatura pracy</b>: -25 u00f7 65u00b0C</li><li><b>Wymiary: </b>1 moduu0142 (18 mm)</li><li><b>Montau017c:</b> na szynie 35 mm</li><li><b>Stopieu0144 ochrony:</b> IP20</li></ul>"
                    },
                    {
                        "url": "https://a.allegroimg.com/original/11f285/1bfe01c54fe78adb6d343817915a",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https://a.allegroimg.com/original/11074d/745b5113433bbe1b66b3ec476443",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>O Producencie F&amp;F</h2><p><b>Firma F&amp;F</b> powstau0142a w 1992 roku. Wyu0142oniu0142a siu0119 z firmy handlowo-usu0142ugowej <b>dziau0142aju0105cej w branu017cy elektronicznej.</b></p><p>Dou015bwiadczenie wu0142au015bcicieli z zakresu elektroniki i elektrotechniki pozwoliu0142o stworzyu0107 firmu0119 o profilu produkcyjnym, <b>oferuju0105cu0105 elektroniczne urzu0105dzenia steruju0105ce dla automatyki domowej i przemysu0142owej.</b></p><p>Obecnie wspu00f3u0142praca dziau0142u badawczo-rozwojowego firmy ze u015brodowiskiem naukowym oraz klientami prowadzi do dynamicznego rozwoju oferty i p<b>ozwala tworzyu0107 rozwiu0105zania o coraz wyu017cszym stopniu zaawansowania technologicznego, czego przyku0142adem su0105 systemy inteligentnego domu F&amp;Home i systemy telemetryczne. </b></p><p><b>F&amp;F</b> jest znanu0105 w Polsce marku0105, a wyroby pod niu0105 produkowane trafiaju0105 ru00f3wnieu017c na rynki Ukrainy, Biau0142orusi, Litwy, u0141otwy, Czech, Su0142owacji, Wu0119gier, Rumunii, Serbii, Niemiec, Grecji, Irlandii, Szwecji, Norwegii, Portugalii, Chile i Stanu00f3w Zjednoczonych.</p><p>Dewizu0105 firmy jest<b> tworzenie innowacyjnych rozwiu0105zau0144 dla partneru00f3w.</b></p>"
                    }
                ]
            }
        ]
    },
    "publication": {
        "status": null,
        "endedBy": null,
        "duration": null,
        "endingAt": null,
        "republish": false,
        "startingAt": null
    },
    "sellingMode": {
        "price": {
            "amount": "138.90",
            "currency": "PLN"
        },
        "format": "BUY_NOW",
        "minimalPrice": null,
        "startingPrice": null
    },
    "__internal_array": null,
    "afterSalesServices": {
        "warranty": {
            "id": "bf58dd5f-6440-4a25-9aa0-aaf9f166a26e"
        },
        "returnPolicy": {
            "id": "ede03507-f138-4fa6-bbf2-95d812ef8bea"
        },
        "impliedWarranty": {
            "id": "f112d989-d08b-4697-a6fd-c23aeaaa66eb"
        }
    }
}
błąd:
 'code' => 'ValidationError.HttpMessageNotReadableException',
        'path' => '/sale/offers',
        'details' => NULL,
        'message' => 'Message not readable',
        'userMessage' => 'Message not readable'

**Comment by MartaNowaczyk** [comment]
Na początek może zapoznaj się z naszą [dokumentacją](https://developer.allegro.pl/documentation/#operation/createProductOffers) i naszym [poradnikiem](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-z-produktem-za-pomoca-zasobu-sale-product-offers). W swoim requeście masz wiele błędów dotyczących struktury, jak zdjęcia w nawiasach klamrowych, id produktu powinno być w polu productSet[].product.id itd. stad ten błąd. Wystaw ofertę z produktem przez www i potem pobierz przez API, aby zobaczyć jak to powinno wyglądać.
