### ISSUE TITLE
Zasób uploadujący zdjęcia w API nie działa dla niektórych linków

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5979]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Trace-id: 92d6c97db9a5df73

Z jakiegoś powodu zasób /sale/images wyrzuca dla tego linku błąd 400 Bad Request. Nie byłoby w tym nic dziwnego, gdyby link nie był normalnie osiągalny w przeglądarce i Postmanie. Próbowałem to jakoś odtworzyć w Postmanie ale nawet wysyłając zapytanie bez nagłówków (nie licząc Host) mogę na spokojnie pobierać obrazek.

**Comment by Lukasz-Zurek** [comment]
Problem przekazałem do odpowiedniego zespołu w celu dalszej weryfikacji. Jak tylko otrzymam info - dam znać w wątku.

**Comment by rtarnowskii** [comment]
Witam
 podobny problem występuje na sandbox. Zdjęcie jest dostępne z poziomu przeglądarki i postmana zwraca HTTP 200 natomiast API podczas tworzenia draftu zwraca HTTP 502.

**Comment by MartaNowaczyk** [comment]
@rtarnowskii możesz podać konkretny przypadek na sandboxie?

**Comment by hahyes** [comment]
@Lukasz-Zurek Ruszyło coś w temacie?

**Comment by Lukasz-Zurek** [comment]
@hahyes Tak, potwierdzam błąd, który występuje po naszej stronie. URL zdjęcia jest prawidłowy, planujemy zatem poprawkę, by bez problemu ów adres obsługiwać. Może to jednak potrwać i tu proszę o cierpliwość. Jak tylko uzyskam konkretne informacje - dam znać w wątku.

Przepraszamy za utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@hahyes Na wstępie bardzo Cię przepraszam za to, że musiałeś tak długo czekać na wyjaśnienie problemu.

Ze względu na to, że wielu użytkowników przekazuje do Allegro niepoprawnie zakodowane URLe (np. ze spacjami), w Allegro przekodowujemy otrzymane URLe, aby były zgodne ze specyfikacją RFC 3986 (przeglądarki tego nie robią, stąd zdjęcie się wyświetla). Dla zapewnienia stabilności API nie możemy wyłączyć tego mechanizmu. 

W tym konkretnym przypadku URL:
https://img1.theiconic.com.au/jCQAlxv_PSdxvcV24W4NjMyxUUs=/634x811/filters:quality(95):fill(ffffff)/http%3A%2F%2Fstatic.theiconic.com.au%2Fp%2Fdazie-4576-5092711-1.jpg

zostaje przekodowany na:

https://img1.theiconic.com.au/jCQAlxv_PSdxvcV24W4NjMyxUUs=/634x811/filters:quality(95):fill(ffffff)/http:%2F%2Fstatic.theiconic.com.au%2Fp%2Fdazie-4576-5092711-1.jpg

ponieważ wyżej wspomniana specyfikacja mówi, że znak ":" w ścieżce URLa nie powinien być zakodowany, a tutaj w przekazywanym do Allegro URLu widzimy niespójność, występują ":" zarówno w postaci zakodowanej ("%3A") jak i niezakodowanej.

W tej sytuacji muszę Cię odesłać do właściciela serwera [theiconic.com.au](http://theiconic.com.au/), dlaczego wymaga niezgodnie ze standardem zakodowanych ":", a żądań zakodowanych ze standardem nie obsługuje zwracając błąd 400.
