### ISSUE TITLE
Podany opis zawiera błędy. 

### ISSUE THREAD

**Issue by GrzegorzP** [allegro/allegro-api#598]
Przy wystawieniu aukcji **doNewAuctionExt** otrzymuje komunikat bledu przez SOAP: "Podany opis zawiera błędy. ".
Zwiazane jest to z nowym formatem opisu aukcji (FID 341). Nie jestem pewien czy dobrze tworze to pole przypisujac do wlasciwosci **fvalueString** Json Stringa z nowym formatem opisu ?

**Comment by MarcinLuczak** [comment]
@GrzegorzP 

> tworze to pole przypisujac do wlasciwosci fvalueString Json Stringa z nowym formatem opisu

Tzn. jak dokładnie, bo nie jestem pewien, czy Cię dobrze rozumiem. Podajesz treść nowego opisu sformatowaną w jsonie, tak? Jeśli tak, to dobrze, tak należy robić.

Upewnij się, że treść jest prawidłowa. Że nie podajesz niedozwolonych znaczników, że umieszczasz opis w znaczniku `<![CDATA[ ]]>` lub znaki & w encjach ponownie encjujesz. Najlepiej, jeśli wystawisz ofertę za pomocą graficznej wersji serwisu, a potem pobierzesz jej zawartość za pomocą metody [GET na zasobie /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/operations/offer-management/getOfferUsingGET).

Pamiętaj też, że jeszcze we wrześniu metody WebAPI do wystawiania oferty oznaczymy jako deprecated i nie będziemy ich już rozwijać. Tym samym zasoby REST API do wystawiania ofert wyjdą z bety. W [naszym poradniku](https://developer.allegro.pl/sale/) opisaliśmy jak za pomocą tych zasobów można wystawiać oferty.

**Comment by GrzegorzP** [comment]
Dla testow strukture bardzo uproscilem, jedynie czego nie dodalem to znacznika `<![CDATA[ ]]>` - sprawdze. Zauwazylem ze w REST API podaje sie URL do zdjecia wczesniej wyslanego. W SOAP'owym API podajemy jako URL zdjecia: `PHOTO_FID_16`, `PHOTO_FID_17` ... Rozumiem ze to jest aktualne?

**Comment by MarcinLuczak** [comment]
@GrzegorzP W przypadku zasobów REST API najpierw przesyłasz zdjęcie na nasz serwer. Opisaliśmy to w [poradniku](https://developer.allegro.pl/sale/#step-3-images). Dopiero potem do oferty dodajesz zdjęcie w postaci odnośnika do niego na serwerze. Ten odnośnik/adres znajdziesz w responsie zasobu, którym dodajesz zdjęcie na nasz serwer.

W przypadku WebAPI zdjęcie trzeba zakodować w base64 i taki kod przekazać w danym fidzie.

**Comment by GrzegorzP** [comment]
Problem lezal ze blednie wprowadzalem parametry zdjec: `FOTO_FID_16` ... zamiast `PHOTO_FID_16`. Zamykam issue.
