### ISSUE TITLE
Jeszcze raz o możliwości zmiany kategorii w ofercie

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#5980]
Sprzedający otrzymuje taką informację:

_Usunęliśmy Twoją ofertę (...) Nie możesz umieszczać oferty w kategorii nieodpowiadającej sprzedawanemu towarowi (...) Możesz poprawić i wznowić swoją ofertę (...)_

Nawiązując do #5870 chciałbym podpytać czy to znaczy, że jednak są wyjątki i wybrane oferty są jakoś oznaczane, że można zmienić kategorię nawet po 12 godzinach?

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
W przypadku ofert zamkniętych przez administratora Serwisu mogą być pewne wyjątki. Skontaktuj się najlepiej za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1), a powinieneś otrzymać szczegółowe informacje.

**Comment by tomylee0** [comment]
OK. Dzięki.
