### ISSUE TITLE
Przełączenie z sandboxa na właściwe API

### ISSUE THREAD

**Issue by michaltoczko** [allegro/allegro-api#5982]
Dzień dobry
Przełączyłem aplikacje ze środowiska testowego sandbox na główne API i po zalogowaniu pokazuje się błąd. Po otworzeniu https://allegro.pl/auth/oauth/authorize pokazuje się po prostu kod błędu. Co trzeba zrobić w tej sytuacji? 

Client ID: 74ddd41e87ac4470a063e7c0f597259c
Kod błędu: 45dd11dac0184d72

**Comment by MartaNowaczyk** [comment]
Problem jest nieprawidłowy adres przekierowań w parametrze redirect_uri. Musi być on **identyczny** jak przy zarejestrowanej aplikacji w zakładce [Developer Apps](https://apps.developer.allegro.pl/).
