### ISSUE TITLE
Znacznik SUPER CENA

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#5983]
Czy z poziomu API można pobrać (wyodrębnić) oferty, które oznaczenie znacznik SUPER CENA?

**Comment by MartaNowaczyk** [comment]
Oferty z etykietą "SUPER CENA" można wyfiltrować tylko korzystając z [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing). Jest możliwość filtrowania wyników po [odpowiednim filtrze](https://developer.allegro.pl/listing/#kampanie). Jednak dostęp do tego zasobu mają tylko [zweryfikowane aplikacje](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk).

**Comment by mateuszcom** [comment]
Nieprecyzyjnie się wyraziłem - nie zależy mi na pobieraniu globalnie (wszystkich publicznych) produktów z SUPER CENĄ, lecz tylko zalogowanego (uwierzytelnianego) użytkownika. Czy do tego celu mogę skorzystać z innego zasobu?

**Comment by MartaNowaczyk** [comment]
Nie mamy innego zasobu, który zwraca te dane.
