### ISSUE TITLE
Endpoint sale/offer-quantity-change-commands nie działa

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#5984]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Wywołanie sale/offer-quantity-change-commands nie powoduje zmiany stanu w aukcji mimo pozytywnego statusu zadania.
Trace-Id rządania: bc4ef4bfc75fb337
Trace-Id sprawdzenia statusu zadania: 4c2102888fc4773a

Payload: 
{
  "modification": {
    "changeType": "GAIN",
    "value": {{value}}
  },
  "offerCriteria": [
    {
      "offers": [
        {
          "id": "{{allegro_offer_id}}"
        }
      ],
      "type": "CONTAINS_OFFERS"
    }
  ]
}

**Comment by MartaNowaczyk** [comment]
Nie widzę tutaj błędu.
1. Stan oferty na 2022-08-08 16:20:41 - 3 szt.
2. Request 2022-08-08 16:29:22 z trace-id bc4ef4bfc75fb337  +1 szt.
3. Docelowo stan w ofercie na tamten moment to 4 szt. 
Teraz jest 7 szt. bo była kolejna zmiana 2022-08-09 07:52:38
