### ISSUE TITLE
Allegro ONE - nie można wybrać punktu ze zbyt długim adresem?

### ISSUE THREAD

**Issue by tztztztz** [allegro/allegro-api#5985]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Podczas próby weryfikacji tworzenia paczki, przez GET /parcel-management/parcel-create-commands/, generowany jest błąd " Maksymalna liczba znaków w ulicy odbiorcy to 35". 

Tymczasem w danych odbiorcy ulica jest bardzo krótka. 

Za to wybrany przez klienta punkt allegro one ma ulicę która ma łącznie 44 znaki: "al. Marszałka Józefa Piłsudskiego 85 i 87"

W związku z tym, najprawdopodobniej o to chodzi, że punkt wybrany przez klienta ma za długą ulicę, co kłóci się z zasadami/constraints systemu Allegro. Jeżeli tak to jest to bug do naprawienia, bo inaczej klienci nie będą mogli wybierać punktów ze zbyt długim adresem. Sensowne byłoby zwiększenie limitu np. do 64 znaków.

**Comment by AureliuszBrussy** [comment]
Czy możesz przekazać trace-id przykładowego wywołania kończącego się tym błędem? Trace-id znajdziesz w nagłówku naszego response'a. Pozwoli mi to dokładniej zweryfikować i wyjaśnić ten problem.

**Comment by hahyes** [comment]
> Jeżeli tak to jest to bug do naprawienia, bo inaczej klienci nie będą mogli wybierać punktów ze zbyt długim adresem. Sensowne byłoby zwiększenie limitu np. do 64 znaków.

@tztztztz To są ograniczenia API dostawców, a nie Allegro. Allegro robi za nas integrację z poszczególnymi dostawcami i każdy z nich ma swoje ograniczenia. Niestety przy tworzeniu paczki trzeba manualnie nazwę ulicy jakoś skrócić i nie ma innej opcji.

**Comment by tztztztz** [comment]
Niestety z trace-id nie jest tak prosto, ale może później uda mi się dostarczyć.

Natomiast na teraz, spróbuję skracać ulicę punktu odbioru.
