### ISSUE TITLE
INVALID_JSON dla post /sale/offers

### ISSUE THREAD

**Issue by yncki** [allegro/allegro-api#5986]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**
Request

`{
    "id": null,
    "tax": {
        "id": "b763d782-572a-47db-8752-8b2cb32b3d0a",
        "rate": null,
        "subject": null,
        "exemption": null,
        "percentage": null
    },
    "name": "F&F Sterownik Radiowy Dwukana\u0142owy LED 12VDC",
    "stock": {
        "unit": "UNIT",
        "available": 371
    },
    "images": [
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11df5d\/337837174b55a2ae12b36a38d776"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/1100d2\/d412a5df42d5862d2831b324a9db"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/115c32\/426b4e47402a87a88c03bf0def0d"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/11a359\/e5390e1249aaa73651dba3b33af2"
        },
        {
            "url": "https:\/\/a.allegroimg.com\/original\/113a62\/bb445fe24dd8a848e728f3dcc006"
        }
    ],
    "product": {
        "id": "82a6ccf6-1b45-4025-b9f1-5fbb27fefaf8"
    },
    "category": {
        "id": "251247"
    },
    "delivery": {
        "handlingTime": "P2D",
        "shipmentDate": null,
        "shippingRates": {
            "id": "284affe2-cd17-49b2-afd8-b76fa629fee1"
        },
        "additionalInfo": ""
    },
    "external": {
        "id": "FW-LED2D"
    },
    "location": {
        "city": "Wschowa",
        "postCode": "67-400",
        "province": "LUBUSKIE",
        "countryCode": "PL"
    },
    "payments": {
        "invoice": "VAT"
    },
    "promotion": {
        "bold": false,
        "highlight": false,
        "emphasized": false,
        "departmentPage": false,
        "emphasizedHighlightBoldPackage": null
    },
    "sizeTable": null,
    "parameters": {
        "0": {
            "id": "11323",
            "values": null,
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        },
        "4": {
            "id": "229205",
            "values": null,
            "valuesIds": [
                "229205_340245"
            ],
            "rangeValue": null
        }
    },
    "attachments": null,
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11df5d\/337837174b55a2ae12b36a38d776",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>Sterownik Dwukana\u0142owy LED Radiowy<\/h2><p><b>F&amp;F FW-LED2D<\/b><\/p><p>\u2714\ufe0f <b>Do sterowania ta\u015bmami LED lub <\/b>\u015bciemnialnymi \u017car\u00f3wkami LED 12V<\/p><p>\u2714\ufe0f Wsp\u00f3\u0142praca<b> z nadajnikami zdalnego sterowania F&amp;Wave<\/b><\/p><p>\u2714\ufe0f Mo\u017cliwo\u015b\u0107<b> sterowania z maksymalnie 8 nadajnik\u00f3w<\/b><\/p><p>\u2714\ufe0f Przeznaczony do monta\u017cu<b> na szynie 35 mm<\/b><\/p><p>\u2714\ufe0f Retransmisja rozkaz\u00f3w z nadajnika <b>- mo\u017cliwo\u015b\u0107 zwi\u0119kszenia zasi\u0119gu zdalnego sterowania;<\/b><\/p><p>\u2714\ufe0f Mi\u0119kki start - <b>p\u0142ynne za\u0142\u0105czenie\/wy\u0142\u0105czenie o\u015bwietlenia<\/b><\/p><p><b>Zestaw sk\u0142ada si\u0119 z<\/b><\/p><ul><li><b>1 szt. <\/b>Sterownik dwukana\u0142owy<b> LED FW-LED2D<\/b><\/li><li>Instrukcja obs\u0142ugi w<b> j\u0119zyku polskim<\/b><\/li><\/ul><p>\u274c <b>Szyna TH-35 nie jest cz\u0119\u015bci\u0105 zestawu!<\/b><\/p><p><b>Pilot do sterowania radiowego dost\u0119pny w naszej ofercie!<\/b><\/p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>Czym jest System F&amp;Wave-radiowy?<\/h2><p>\u27a1 Je\u017celi cenisz sobie komfort codziennego \u017cycia, <b>zdalne sterowanie radiowe F&amp;Wave<\/b> jest zdecydowanie dla Ciebie.<\/p><p>\u27a1 F&amp;Wave to <b>zdalne sterowanie<\/b> o\u015bwietleniem ( w tym p\u0142ynna regulacja jasno\u015bci o\u015bwietlenia, tak\u017ce za pomoc\u0105 <b>uniwersalnego \u015bciemniacza oswietlenia FW-D1D<\/b>), sterowanie roletami, \u017caluzjami, markizami, bramami wjazdowymi i gara\u017cowymi oraz innymi urz\u0105dzeniami w domu.<\/p><p><b>Radiowy system zdalnego sterowania F&amp;Wave<\/b> to przede wszystkim:<\/p><ul><li><b>\u0141atwy monta\u017c,<\/b><\/li><li><b>Prosta obs\u0142uga,<\/b><\/li><li><b>\u0141atwa konfiguracja element\u00f3w systemu,<\/b><\/li><li><b>Mo\u017cliwo\u015b\u0107 samodzielnego monta\u017cu,<\/b><\/li><li><b>Atrakcyjna cenna.<\/b><\/li><\/ul>"
                    },
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/1100d2\/d412a5df42d5862d2831b324a9db",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/115c32\/426b4e47402a87a88c03bf0def0d",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>Retransmisja sygna\u0142u-unikalna cecha systemu radiowego sterowania F&amp;Wave<\/h2><p>Unikaln\u0105 cechu systemu F&amp;Wave jest <b>retransmisja sygna\u0142u<\/b> - ka\u017cdy odbiornik, kt\u00f3ry odbierze sygna\u0142 steruj\u0105cy z nadajnika, automatycznie przesy\u0142a go dalej. Zwi\u0119ksza to znacznie zasi\u0119g sterowania w przypadku odbiornik\u00f3w oddalonych od nadajnika na tyle, \u017ce znajduj\u0105 si\u0119 poza zasi\u0119giem pierwotnego sygna\u0142u. <\/p><p><b> Jakie urz\u0105dzenia tworz\u0105 system zdalnego sterowania radiowego F&amp;Wave?<\/b><\/p><p> Na system sk\u0142adaj\u0105 si\u0119:<\/p><ul><li> <b>odbiorniki<\/b> <\/li><\/ul><p>Urz\u0105dzenia wykonawcze. Wyprodukowane s\u0105 w wersji do monta\u017cu w puszce podtynkowej \u00d860 lub do monta\u017cu na szynie TH-35 (szeroko\u015b\u0107 1 modu\u0142u tj. 17,5 mm). O<b>bok odbiornik\u00f3w w systemie F&amp;Wave wyst\u0119puj\u0105 r\u00f3wnie\u017c <\/b><\/p><ul><li><b>nadajniki<\/b>.<\/li><\/ul><p>S\u0105 to podr\u0119czne piloty lub urz\u0105dzenia <b>do monta\u017cu w puszce podtynkowej (przyciski na\u015bcienne, tak\u017ce bateryjne).<\/b><\/p>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<h2>Dane techniczne<\/h2><ul><li><b>Napi\u0119cie zasilania:<\/b> 10\u00f716 V DC<\/li><li><b>Liczba kana\u0142\u00f3w: <\/b>2<\/li><li><b>Funkcja \u015bciemniacz: <\/b>12 V<\/li><li><b>Wej\u015bcia sterownicze:<\/b> 2<\/li><li><b>Sygna\u0142 steruj\u0105cy<\/b>: -<\/li><li><b>Obci\u0105\u017calno\u015b\u0107 wyj\u015bcia (AC-1):<\/b> 6 A \/12 V<\/li><li><b>Element wykonawczy: <\/b>tranzystor<\/li><li><b>Cz\u0119stotliwo\u015b\u0107 radia:<\/b> 868 MHz<\/li><li><b>Przy\u0142\u0105cze:<\/b> zaciski \u015brubowe 2,5 mm\u00b2<\/li><li><b>Moment dokr\u0119caj\u0105cy: <\/b>0,4 Nm<\/li><li><b>Pob\u00f3r mocy czuwanie\/praca: <\/b>0,25 W \/ 0,4 W<\/li><li><b>Temperatura pracy<\/b>: -25 \u00f7 65\u00b0C<\/li><li><b>Wymiary: <\/b>1 modu\u0142 (18 mm)<\/li><li><b>Monta\u017c:<\/b> na szynie 35 mm<\/li><li><b>Stopie\u0144 ochrony:<\/b> IP20<\/li><\/ul>"
                    },
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/11a359\/e5390e1249aaa73651dba3b33af2",
                        "type": "IMAGE"
                    }
                ]
            },
            {
                "items": [
                    {
                        "url": "https:\/\/a.allegroimg.com\/original\/113a62\/bb445fe24dd8a848e728f3dcc006",
                        "type": "IMAGE"
                    },
                    {
                        "type": "TEXT",
                        "content": "<h2>O Producencie F&amp;F<\/h2><p><b>Firma F&amp;F<\/b> powsta\u0142a w 1992 roku. Wy\u0142oni\u0142a si\u0119 z firmy handlowo-us\u0142ugowej <b>dzia\u0142aj\u0105cej w bran\u017cy elektronicznej.<\/b><\/p><p>Do\u015bwiadczenie w\u0142a\u015bcicieli z zakresu elektroniki i elektrotechniki pozwoli\u0142o stworzy\u0107 firm\u0119 o profilu produkcyjnym, <b>oferuj\u0105c\u0105 elektroniczne urz\u0105dzenia steruj\u0105ce dla automatyki domowej i przemys\u0142owej.<\/b><\/p><p>Obecnie wsp\u00f3\u0142praca dzia\u0142u badawczo-rozwojowego firmy ze \u015brodowiskiem naukowym oraz klientami prowadzi do dynamicznego rozwoju oferty i p<b>ozwala tworzy\u0107 rozwi\u0105zania o coraz wy\u017cszym stopniu zaawansowania technologicznego, czego przyk\u0142adem s\u0105 systemy inteligentnego domu F&amp;Home i systemy telemetryczne. <\/b><\/p><p><b>F&amp;F<\/b> jest znan\u0105 w Polsce mark\u0105, a wyroby pod ni\u0105 produkowane trafiaj\u0105 r\u00f3wnie\u017c na rynki Ukrainy, Bia\u0142orusi, Litwy, \u0141otwy, Czech, S\u0142owacji, W\u0119gier, Rumunii, Serbii, Niemiec, Grecji, Irlandii, Szwecji, Norwegii, Portugalii, Chile i Stan\u00f3w Zjednoczonych.<\/p><p>Dewiz\u0105 firmy jest<b> tworzenie innowacyjnych rozwi\u0105za\u0144 dla partner\u00f3w.<\/b><\/p>"
                    }
                ]
            }
        ]
    },
    "publication": {
        "status": null,
        "endedBy": null,
        "duration": null,
        "endingAt": null,
        "republish": false,
        "startingAt": null
    },
    "sellingMode": {
        "price": {
            "amount": "138.90",
            "currency": "PLN"
        },
        "format": "BUY_NOW",
        "minimalPrice": null,
        "startingPrice": null
    },
    "afterSalesServices": {
        "warranty": {
            "id": "bf58dd5f-6440-4a25-9aa0-aaf9f166a26e"
        },
        "returnPolicy": {
            "id": "ede03507-f138-4fa6-bbf2-95d812ef8bea"
        },
        "impliedWarranty": {
            "id": "f112d989-d08b-4697-a6fd-c23aeaaa66eb"
        }
    }
}`

Response
 {
    "errors": [
        {
            "code": "INVALID_JSON",
            "message": "Invalid request.",
            "details": null,
            "path": null,
            "userMessage": "Invalid request."
        }
    ]
}
 

Trace ID : b0b18342ec2f5bfa

**Comment by AureliuszBrussy** [comment]
Niepoprawnie przekazujesz parametry:

```
    "parameters": {
        "0": {
            "id": "11323",
            "values": null,
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        },
        "4": {
            "id": "229205",
            "values": null,
            "valuesIds": [
                "229205_340245"
            ],
            "rangeValue": null
        }
    }
```

Pole **parameters** to lista, więc struktura powinna wyglądać tak:

```
    "parameters": [
        {
            "id": "11323",
            "values": null,
            "valuesIds": [
                "11323_1"
            ],
            "rangeValue": null
        },
        {
            "id": "229205",
            "values": null,
            "valuesIds": [
                "229205_340245"
            ],
            "rangeValue": null
        }
    ]
```
