### ISSUE TITLE
Problem przy wystawianiu oferty

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#5988]
Witam, po wystawieniu oferty mam zwrotkę, że oferta została wystawiona, jednak ląduje ona w szkicu. I teraz pytanie, czy oferty zostaną wystawione w jakimś czasie (asynchroniczne wystawianie) czy coś jest nie tak.

Przykładowe oferty, które się poprawnie z walidowały i wystawiły, ale są szkicami.

12481867988
12481868299
12481868681
12481870114
12481871613

**Comment by AureliuszBrussy** [comment]
Widzę, że oferty są już aktywne.
