### ISSUE TITLE
Zdobycie informacji o produktach tylko przy użyciu /sale/offers

### ISSUE THREAD

**Issue by JurekAndrzejewski** [allegro/allegro-api#5989]
Hej, czy jest możliwość aby pobrać wszystkie oferty z danego konta (ok. 100k) (sale/offers) i bez użycia kolejnego requesta zdobyć dane o produkcie z aukcji? Wystarczą podstawowe jak id lub nazwa lub cokolwiek innego co chociaż zbliży mnie do możliwości konkretnego ustalenia produktu. Wykonanie 100k requestów po każdy produkt zawsze da się zrobić, ale nie jest to najoptymalniejsze rozwiązanie.

EDIT: Jeśli nie, to przy założeniu, że do 2024 produktyzacja obejmie całe allegro może miałoby sens wprowadzenie tego?

**Comment by AureliuszBrussy** [comment]
Nie udostępniamy takiego zasobu. Zachęcam do przekazania swojej sugestii w zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Inni użytkownicy będą mogli zagłosować na Twoją propozycję - ułatwia nam to rozpoznawanie rzeczywistych potrzeb użytkowników naszego API.

**Comment by JurekAndrzejewski** [comment]
Założone, może komuś się spodoba ten pomysł
https://github.com/allegro/allegro-api/discussions/5992

**Comment by JurekAndrzejewski** [comment]
Założone, może komuś się spodoba ten pomysł: https://github.com/allegro/allegro-api/discussions/5992
