### ISSUE TITLE
ID transakcji InPost

### ISSUE THREAD

**Issue by therodzyn** [allegro/allegro-api#599]
Witam,
Korzystam z API Allegro REST oraz z API InPostu. 
Aby dodać przesyłkę Allegro (jakąkolwiek) przez API InPost należy podać _allegro_transaction_id_, czyli _Numer transakcji formularza posprzedażowego Allegro, w którym kupujący wybrał formę dostawy Allegro Paczkomaty InPost_. 
Czy jest jakaś możliwość, aby pobrać tę daną za pomocą Allegro API REST na podstawie ID zamówienia lub UUID płatności?
W zasobie zamówienia ani eventów nie widzę nigdzie takiej danej.
Dostaję tę daną na pocztę e-mail, gdy ktoś złoży zamówienie, jednak wprowadzanie tej danej dla każdej przesyłki InPost ręcznie jest bardzo niewygodne. 
Z kolei gdy w systemie InPost wykona się import z Allegro, to w jakiś sposób pobierane jest to ID transakcji.
W jaki sposób pobrać tę daną?

Pozdrawiam
Jakub Rodziński

**Comment by therodzyn** [comment]
W takim razie w jaki sposób to ID jest pobierane z poziomu platformy InPost?
Po zalogowaniu i zaimportowaniu zamówień z Allegro w platformie InPost ID transakcji jest widoczne.

**Comment by crowpy** [comment]
Z tego co pamiętam, można pobrać tą informację przez SOAP.

**Comment by imper86** [comment]
@therodzyn zapewne zainteresuje Cię metoda doGetPostBuyFormsIds, aczkolwiek uważam, że lepiej jest pobierać dziennik zdarzeń (doGetSiteJournalDeals) i na jego podstawie ogarniać sobie zamówienia.

**Comment by therodzyn** [comment]
Za pomocą połączenia przez SOAP i wymienionych wyżej metod udało mi się pobrać to ID.
Wynika stąd, że jeszcze przez jakiś czas trzeba się pomęczyć na hybrydzie SOAP + REST.
Dzięki wielkie
Pozdrawiam

**Comment by aktywnitu** [comment]
@therodzyn  czy Inpost oczekuje wartości z dealTransactionId,  czy dealId?

**Comment by therodzyn** [comment]
Ja użyłem metody doGetTransactionsIDs. Zwraca typ long[], czyli tablicę identyfikatorów dla InPostu. Można przekazać tablicę identyfikatorów ofert.

**Comment by aktywnitu** [comment]
Dzięki. Właśnie na tą metodę się zaopatrywałem - wystarczy podać id oferty i kupującego i pobrać id transakcji.

**Comment by imper86** [comment]
@aktywnitu tylko do inpostu tam podajesz id sprzedawcy, a nie kupującego :)

**Comment by aktywnitu** [comment]
@imper86 , tak zgadza się. 
Przypuśćmy, że ten sam przedmiot kupiło dwóch różnych kupujących.
Jakie skutki będą z pomieszania transakcji tego nie wiem. Możliwe, że Inpost wysyła do Allegro statusy wysyłek, a te mogą wprowadzać w błąd kupujących.
Najlepiej, gdyby ktoś z Allegro, czy Inpostu się wypowiedział - @LukaszKorek.

**Comment by imper86** [comment]
@aktywnitu nie bardzo rozumiem dlaczego tak. Oczywiście wszystko zależy od implementacji, ale moim zdaniem nie ma prawa się nic pomieszać, gdy korzystasz z dziennika zdarzeń i przypisujesz prawidłowe idy transakcji do przesyłek. Zresztą inpost nie akceptuje byle jakich numerów id, ale tylko tych, w których faktycznie kupujący wybrali usługi Allegro Inpost.

Konkludując:
1) Powinieneś pobierać dziennik zdarzeń, gdzie masz potrzebne numery ID
2) Do każdego wypełnionego formularza pobierasz dane
3) Dopiero na tej podstawie tworzysz wysyłkę w Inpoście, mając id transakcji oraz pewność, że kupujący wybrał przesyłkę typu allegro inpost.

**Comment by aktywnitu** [comment]
@imper86 , tak rozumiem, przy czym chciałbym zachować pobieranie zamówień poprzez nowe REST API, aby tylko uzupełnić numery transakcji - samo użycie metody doGetTransactionsIDs może właśnie spowodować nieprawidłowo przypisane numery. Dlatego trzeba by jeszcze sprawdzić numery przy pomocy doGetPostBuyFormsDataForSellers, a to dodatkowa komplikacja.

**Comment by imper86** [comment]
@aktywnitu rozumiem, tylko mam dziwne wrażenie, że zbyt wiele oczekujesz od tego nowego API. O ile dobrze pamiętam to zasób dotyczący obsługi zamówień jest jeszcze w wersji beta, więc używanie go na produkcji to proszenie się o problemy :)

Owszem, SOAPowe api jest nieładne, stare i wolne, ale działa. Ma być wygaszane, ale patrząc na tempo prac nad nowym to chyba nie za szybko się to stanie :). Nie wiem z jakiej technologii korzystasz, ale zakładam, że większość języków programowania posiada biblioteki importujące dane z WSDL, dzięki czemu praca ze starym api staje się zdecydowanie bardziej przyjemna i przyjazna.

**Comment by aktywnitu** [comment]
@imper86 tak, jednak zrobiłem to przy pomocy metody doGetSiteJournalDeals.
Webapi ogarniam, ale miałem zamiar nowy projekt wykonać wyłącznie przy użyciu REST API. Niestety się nie da.

**Comment by therodzyn** [comment]
Rzeczywiście doGetSiteJournalDeals załatwia sprawę. 
A co w sytuacji gdy JEDEN kupujący złoży kilka zamówień na TĄ SAMĄ ofertę?
Np. najpierw kupił sobie 1 sztukę, a potem stwierdził, że kupi jeszcze kilka i złoży 2 zamówienia do jednej oferty. Wtedy doGetSiteJournalDeals mimo podania ID oferty i ID kupującego i tak zwróci kilka ID transakcji. Jakiś pomysł jak to rozwiązać?

**Comment by imper86** [comment]
@therodzyn no ale co chcesz rozwiązywać? ;) Do Inpostu podajesz id transakcji + id sprzedawcy - jaką przeszkodą jest to, że masz tych idów transakcji kilka bo klient złożył kilka zamówień?
Jeżeli wysyłasz tylko jedną paczkę - korzystasz z jednego id, jeżeli do każdego zamówienia osobną - odpowiedź jest chyba oczywista :)

**Comment by therodzyn** [comment]
Jest przeszkodą, ponieważ ja w swoim systemie mam jeszcze warstwę pośrednią - warstwę zamówień (pobrane z Allegro). Potem do InPostu chcę eksportować tylko zaznaczone zamówienia ;) Na zamówieniu mam ID oferty i ID kupującego. Pobieram dziennik zdarzeń, który filtruję na podstawie tych danych i mogę dostać kolekcję ID transakcji zamiast pojedynczego rekordu (w wyżej opisanym przypadku - kilka zamówień jednego kupującego do jednej oferty). Nie wiem które ID transakcji przypisać do konkretnego zamówienia.

**Comment by imper86** [comment]
No więc skoro pobierasz z allegro zamówienia (zakładam że robisz to przez stare api) to czemu nie możesz sobie przypisać do danego zamówienia id transakcji?
Przecież jedno zamówienie z allegro = jeden id transakcji.

**Comment by therodzyn** [comment]
Gdybym pobierał zamówienia przez stare API to pewnie bym w ogóle nie zakładał tego wątku ;)
Restowe API pobiera mi zamówienia prawidłowo, tylko nie mam jednej danej - ID transakcji.
Chciałem więc spróbować je pobrać przez SOAP na podstawie pobranego zamówienia przez REST, ale wychodzi na to, że zamówienia również będę musiał pobrać przez SOAP.
Z tego wynika, że zasób pobierania zamówień przez REST jest jak na razie mi zupełnie nieprzydatny tylko dlatego, ze nie pobiera ID transakcji ;)
Aby dopasować zamówienie = transakcja, muszę mieć ID zamówienia, które mi zwróci SOAP, ponieważ REST zwraca UUID, który nie jest wykorzystywany w SOAP i nie jestem w stanie zweryfikować zamówienia.

**Comment by imper86** [comment]
No dobra, ale tu znów muszę poruszyć ten sam temat co w innym zgłoszeniu - opierasz swoje rozwiązania biznesowe na zasobie, który jest w wersji beta :). Ja serio rozumiem, że nowe api jest fajniejsze, szybsze itd, ale po to jest ta beta żeby zgłaszać bugi/uwagi itd, a nie do tego żeby korzystać z niej na produkcji :)

**Comment by aktywnitu** [comment]
Aby wyjść z bety musi jednak ktoś korzystać :)
@therodzyn  dla zdarzenia z          dealEventType = 1 dealEventTime jest taki sam co w rest api - po tym można sparować zdarzenia.

**Comment by aktywnitu** [comment]
@therodzyn niestety nie ma pewnego sposobu. Rada @imper86 będzie najlepszym rozwiązaniem.
Support od Allegro, jak zwykle siedzi cicho. Nie wiem za co im płacą.

**Comment by therodzyn** [comment]
Nie znalazłem żadnej metody, która zwracałaby listę zamówień w tak rozbudowanej formie jak w REST.
Metoda doGetSiteJournalDeals zwraca same identyfikatory.
A więc tworząc w moim systemie obiekt zamówienia musiałbym wykonać jeszcze żądania SOAP o szczegóły kupującego, szczegóły płatności itd. W REST (GET /order/checkout-forms) mam jeden obiekt, który zawiera wszystkie te dane w jednym żądaniu.
Czy jest jakaś metoda pobierająca zamówienia przez SOAP bardziej szczegółowa niż doGetSiteJournalDeals?
Idąc tym tropem zaraz będę miał więcej żądań SOAP niż REST, a to tylko dlatego, że (GET /order/checkout-forms) nie zwraca ID transakcji (1 POLE!)

**Comment by martacronic** [comment]
@therodzyn jesli mówimy o WebAPi, to ja najpierw pobieram sobie dziennik za pomocą [doGetSiteJournalDeals](https://allegro.pl/webapi/documentation.php/show/id,742#method-output), a nastepnie dla zdarzeń, które mają **dealTransactionId** rózne od 0 pobieram metodą [GetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703)  wszystkie informacje o zamówieniu.

**Comment by LukaszKorek** [comment]
Tak jak już wcześniej w toku tej dyskuscji wspomniałem i padało to także w innych wypowiedziach - cały czas pracujemy nad REST API - rozwijamy je. Jesteśmy wdzięczni za wszytskie sugestie, analizujemy je i jeśli są zasadne dodajemy, rozwijamy zasoby. Również przeanalizujemy te z tego wątku. Cały czas możecie także korzystać z WebAPI. Zachęcam do lektury naszego poradnika ["jak montorować sprzedaż".](https://allegro.pl/webapi/tutorials.php/tutorial/id,100421).

**Comment by aktywnitu** [comment]
W planach jest oznaczenie WEBAPI jako DEPRECATED i jego wyłączenie. Zachęcanie zatem do korzystania ze starszego rozwiązania nie jest rozwiązaniem.
Jedna metoda do konwersji UUID na INTEGER, albo umożliwcie Impostowi operowane poprzez UUID i przyciśnijcie ich do zmiany.
.

**Comment by therodzyn** [comment]
> @therodzyn jesli mówimy o WebAPi, to ja najpierw pobieram sobie dziennik za pomocą [doGetSiteJournalDeals](https://allegro.pl/webapi/documentation.php/show/id,742#method-output), a nastepnie dla zdarzeń, które mają **dealTransactionId** rózne od 0 pobieram metodą [GetPostBuyFormsDataForSellers](https://allegro.pl/webapi/documentation.php/show/id,703) wszystkie informacje o zamówieniu.

Potwierdzam. Podane przez Ciebie metody działają bez problemu i do każdego zamówienia przypisuję sobie ID transakcji. Dzięki wielkie!
Oczywiście przyłączam się do prośby o ID transakcji w REST ;)

**Comment by kormichu** [comment]
Od siebie dodam tyle, że konwersja UUID na INTEGER albo ich jednoczesna obsługa przez REST API byłaby niezwykle pomocna. Nasz monitoring sprzedaży identyfikuje zamówienia na podstawie wartości zwracanej w polu dealTransactionId oraz dealId (czyli INT) więc w chwili przejścia SOAP -> REST integracja będzie mogła powielić zamówienia jeśli w journalu pojawią się informacje z zamówień pobranych wcześniej

**Comment by coobitus** [comment]
@LukaszKorek minęło już prawie półtora miesiąca i nic nie drgnęło w temacie ???

**Comment by MartaNowaczyk** [comment]
@coobitus tak jak ci pisałam w innych wątkach, sprawa jest w toku.

**Comment by coobitus** [comment]
@MartaNowaczyk widzę, że jest w toku - już półtora miesiąca ... Ale w toku w żaden sposób nie rokującym rychłego rozwiązania problemu :-D A Wy za chwilę radośnie napiszecie "obsługa zamówień w wersji PUBLIC NARESZCIE! ZAJEBIŚCIE!" (wg Waszego schedule stąd : https://developer.allegro.pl/news/2018-06-06-Wygaszamy_webapi/ miało się to odbyć już w październiku ;-))))  a problem z Inpostem zostawicie nierozwiązany

**Comment by coobitus** [comment]
Minął kolejny miesiąc i nadal temat nie jest rozwiązany ...

**Comment by MartaNowaczyk** [comment]
@coobitus Pytasz o to samo w kilku wątach. Tak jak napisał Ci Paweł:

> Trwają rozmowy z Inpostem w sprawie rozwiązania tej sytuacji, jak już wielokrotnie informowaliśmy, jak tylko otrzymamy jakieś konkretne informacje, poinformujemy o tym w dedykowanym komunikacie.

**Comment by coobitus** [comment]
@MartaNowaczyk podtrzymuję po prostu wątek, żebyście go nie zamietli automatycznie pod dywan :-) Naprawcie ten problem w końcu, to nie będzie tematu :-D "Rozmawiacie z Inpostem" już prawie pół roku i nic z tego dla nas nie wynika ...

**Comment by mjag8** [comment]
Przyłączam się, brak jednego drobnego pola int z numerem transakcji, lub możliwości zmapowania po uuid powoduje uciążliwe problemy...

**Comment by PawelTaberski** [comment]
Już wdrożyliśmy możliwość dodawania numerów przesyłek przez REST API, więcej tutaj: #1217

**Comment by MartaNowaczyk** [comment]
Zgodnie z informacją [#1043](https://github.com/allegro/allegro-api/issues/1043) ten problem chcemy rozwiązać do końca marca.

**Comment by wilktomasz** [comment]
Czy udało się komuś rozwiązać problem jak powiązać zamówienia pobierane z WebAPI z zamówieniami pobranymi za pomocą REST?

Nie chciałbym tego robić "pośrednio" przez porównywanie id kupujących, id ofert, ilości, ceny, daty...

PS. Przechodzę na REST bo tylko tam mogę nadawać numery przesyłek. Hehe, ale nie wygeneruję przesyłki bo nie mam allegro_transaction_id.

**Comment by MartaNowaczyk** [comment]
@wilktomasz udostępniliśmy [mapowanie dealId i lineItemId](https://github.com/allegro/allegro-api/issues/731) - może nie jest to doskonały i prosty sposób na połączenie obu światów, ale może okazać się pomocny.

**Comment by mjag8** [comment]
Też próbowałem na wiele różnych sposobów i tylko "pośrednio" przez takie kombinowanie można to zrobić właśnie, jeśli chce się to zrobić jednoznacznie i porządnie.
Również dostępna była karta płatności z przydatnymi informacjami dla osób obsługujących klientów pod adresem http://allegro.pl/myaccount/newpayments_payment_details.php. Problem w tym, że nie można podlinkować parametru GET z numerem transakcji, bo nie ma możliwości uzyskania tegoż przez nowe API, próbowałem uuid płatności wyświetlany w karcie w nawiasie, ale nie działa

**Comment by coobitus** [comment]
@MartaNowaczyk z tego co widzę, to nic NOWEGO nie zrobiliście w temacie - czyli nadal nie rozwiązaliście problemu opisanego przez @therodzyn ... Koniec marca już blisko - kiedy można się spodziewać tego rozwiązania?

**Comment by MartaNowaczyk** [comment]
@coobitus nie chcę tu pisać w ciemno i szacować, dlatego potrzebuję czasu na informacje ze strony inPostu.

**Comment by pijablonski** [comment]
Z racji ostatniego dnia roboczego w marcu ponawiamy pytanie - kiedy można się spodziewać rozwiązania problemu?

**Comment by MartaNowaczyk** [comment]
@pijablonski czekam na oficjalne informacje. Jak je dostanę dam znać. Niestety wiadomo, że podany wcześniej termin nie został dotrzymany.
