### ISSUE TITLE
Integracja z fulfilmentem - klient id, secret oraz klucze jako DEV

### ISSUE THREAD

**Issue by mogigor** [allegro/allegro-api#5990]
Wprowadzamy w swojej firmie integrację z fulfilmentem i osoba odpowiedzialna za integrację poprosiła nas o następujące dane:

Klient ID:
klient SECRET:
Po 1 kluczu dla DPD, Poczty polskiej , oraz 2 klucze dla UPS   „Klucze jako DEV”

Z tego co rozumiem muszę te informację wyciągnąć z rest api allegro jednak nie mam pojęcia w jaki sposób. Proszę o pomoc w tym temacie :)

**Comment by AureliuszBrussy** [comment]
Jeżeli chodzi o generowanie kluczy do naszego API - aby uzyskać Client ID oraz Client Secret musisz zarejestrować aplikację w zakładce [Zarządzanie aplikacjami Allegro](https://apps.developer.allegro.pl/). Dla wersji testowej [zarejestruj aplikację na Sandboxie](https://apps.developer.allegro.pl.allegrosandbox.pl/).
