### ISSUE TITLE
POST sale/product-offers InvalidDictionaryParameter własna wartość w produkcie Allegro

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#5993]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,

Mam problem z zasobem POST sale/product-offers - chodzi o wystawienie oferty powiązanej z istniejącym produktem Allegro.

Produkt Allegro ma w katalogu produktów wybraną jako Producenta wartość inny producent

`GET https://api.allegro.pl/sale/products/{id} || trace-id:b65bdf860b743f68`

```
parameters[][
          "id" => "210826"
          "name" => "Producent"
          "range_value" => null
          "values" => array:1 [▼
            0 => "Kenay AG"
          ]
          "values_ids" => array:1 [▼
            0 => "210826_245198"
          ]
          "values_labels" => array:1 [▼
            0 => "inny producent (Kenay AG)"
          ]]
```

Przy tworzeniu produktu przekazuję
`POST sale/product-offers || trace-id:b80c8039a156bcd3`

```
productSet[].product.parameters[][
            +"id": "210826"
            +"values": array:1 [
              0 => "Kenay AG"
            ]
            +"valuesIds": array:1 [
              0 => "210826_245198"
            ]
]
```

Otrzymuję błąd
```
    +"code": "InvalidDictionaryParameter"
    +"message": "Unprocessable Entity"
    +"details": null
    +"path": "productSet[0].product.parameters"
    +"userMessage": "Podany identyfikator wartości słownikowej `210826_245198` w parametrze o identyfikatorze`210826` wskazuje na inną wartość niż przekazana w polu `values`."
```

Proszę o pomoc

**Comment by MaciejFrackowiak** [comment]
W tym przypadku wartość, którą należy przekazać to "inny producent (Kenay AG)" - i w takiej postaci request zakończy się powodzeniem.
