### ISSUE TITLE
null: Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii.

### ISSUE THREAD

**Issue by mateis1234412** [allegro/allegro-api#5994]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Od kilkunastu dni nie można wystawić żadnego produktu przez  Idoshell.  Nie można wystawić na żadnym koncie. W polu wyboru produktu na IaI nie ma produktu przypisanego do kodu EAN (wystawiam suplement diety, proponuje drukarki). Wybranie nawet nieprawidłowego produktu nic nie zmienia, błąd jest ten sam. Wszystkie wymagane parametry w produkcie są ustawione prawidłowo. 

Treść komunikatu:
"<html>
<body>

Uwaga: Wystąpił błąd w module integracji Allegro. Nie jest to błąd działania naszego panelu, dlatego prosimy o zapoznanie się z poniższą informacją.
--
Kod odpowiedzi zwrócony przez API Allegro:
VALIDATION_ERROR 
Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro
:null: Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą.
Postępowanie:
Jeżeli to możliwe popraw błędne dane, w przeciwnym wypadku kliknij tutaj by skontaktować się z obsługą Allegro w celu wyjaśnienia przyczyny występowania błędu. Poniżej znajdują się załączniki, o które możesz zostać poproszony. Możesz w ciągu kilku dni przejrzeć ponownie ten błąd otwierając Dziennik zdarzeń Załączniki:
Żądanie: request_allegro_20220810_122105Odpowiedź: response_allegro_20220810_122105Załączniki będą przechowywane do: 2022-08-17

</body>
</html>Uwaga: Wystąpił błąd w module integracji Allegro. Nie jest to błąd działania naszego panelu, dlatego prosimy o zapoznanie się z poniższą informacją.
Kod odpowiedzi zwrócony przez API Allegro:
VALIDATION_ERROR

Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
null: Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą.

Postępowanie:
Jeżeli to możliwe popraw błędne dane, w przeciwnym wypadku kliknij [tutaj] by skontaktować się z obsługą Allegro w celu wyjaśnienia przyczyny występowania błędu. Poniżej znajdują się załączniki, o które możesz zostać poproszony.

"

**Comment by MaciejFrackowiak** [comment]
Zgodnie z [naszym komunikatem](https://github.com/allegro/allegro-api/issues/5961), od 1 sierpnia 2022 dla większości kategorii wymagamy, aby wystawiając nową ofertę była ona powiązana z Katalogiem produktów Allegro. Wspomniany komunikat jednoznacznie mówi, że wystawiana oferta nie posiadała powiązanego produktu i dlatego właśnie oferta finalnie nie została wystawiona. 
Jeżeli produktu nie ma w naszej bazie, to korzystając z zasobów /sale/product-offers taką propozycję produktu można zgłosić, i tym samym stworzony zostanie nowy produkt. Również, dla niektórych kategorii Allegro nie jest konieczne określenie kodu GTIN. 
Trudności związane z korzystaniem z Idosell powinni Państwo zgłosić bezpośrednio do dostawcy oprogramowania, ponieważ jako Allegro nie mamy wpływu na sposób jej funkcjonowania.

**Comment by mateis1234412** [comment]
Produkty które chcę wystawić są w bazie allegro, nawet mieliśmy je już wystawione i połączone z produktem. Iai twierdzi, że to wina po stronie allegro. 

Już mieliśmy taki problem i rzeczywiście okazało się że to przez allegro nie przechodziło wystawianie ofert, bo było za dużo produktów niepołączonych z  katalogiem, ale ich się nie dało połączyć bo nie miały nadanego kodu ean. Więc proszę sprawdzić jeszcze raz, żeby nie okazało się ponownie, że to nie wina IAI.

**Comment by MaciejFrackowiak** [comment]
Jeżeli produkt jest w bazie to nie widzę powodu, dla którego nie można go wystawić - jeżeli jest inaczej proszę o konkretny przykład takiego produktu.

**Comment by mateis1234412** [comment]
Kody ean produtków:
6009544906315
5060245609456
5060469986913

**Comment by MaciejFrackowiak** [comment]
Produkty dla podanych kodów GTIN (EAN) dostępne są w Katalogu produktów Allegro, dlatego bez przeszkód wymienione produkty można wystawić w serwisie. Raz jeszcze proszę o kontakt z autorem aplikacji i wyjaśnienie wszelkich wątpliwości.

**Comment by mateis1234412** [comment]
Czy mogę dostać adres mailowy do Pana? Jeżeli oni będą pisać, że problem leży po stornie allegro, przekieruje wiadomość

**Comment by MaciejFrackowiak** [comment]
Integrator posiada do nas bezpośredni adres email - zawsze preferujemy taki kontakt, aby nie angażować użytkownika w pośredniczenie w kontakty pomiędzy firmami.
