### ISSUE TITLE
Niezrozumiały błąd podczas wysyłania propozycji zmian w produkcie

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#5995]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Próbując wykonać zapytanie o zmianę kategorii w produkcie otrzymałem taki komunikat.

```
{
   "errors":[
      {
         "code":"CreateProductSuggestionValidationException",
         "message":"Zgłaszanie błedów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Zbyt wiele wartości w parametrze 229173 (Marka)]",
         "details":null,
         "path":"/sale/products/da86b5ca-cfdb-4191-a0aa-6a6a386bfbfd/change-proposals",
         "userMessage":"Zgłaszanie błedów w produkcie zakończyło się błędem: Nieprawidłowo wypełnione parametry: [Zbyt wiele wartości w parametrze 229173 (Marka)]"
      }
   ]
}
```

Trace-id: 6bb32de061f9b315

Nie rozumiem, czemu występuje taki błąd. Podawana jest marka o wartości "inna" z podaną wartością. Podałem dokładnie jedną wartość słownikową i jej uzupełnienie. O co chodzi?

**Comment by hahyes** [comment]
> W przypadku zgłaszania sugestii zmian w produkcie nie można dodać własnej wartości dla wartości niejednoznacznej - "inna".

@MaciejFrackowiak Dlaczego nie można tego zrobić, skoro można to zrobić tworząc sam produkt? Obawiam się, że nadal nie rozumiem. Utworzyłem produkt z właśnie takimi parametrami i w poradniku każecie mi te parametry przekazywać, więc je przekazuje.

**Comment by MaciejFrackowiak** [comment]
Mechanizm jest tożsamy z mechanizmem działającym na stronie WWW - tam również dla wartości "inna" nie ma możliwości wskazania własnej wartości.

**Comment by hahyes** [comment]
@MaciejFrackowiak Proszę natomiast wskazać rozwiązanie dla podanej sytuacji: mechanizm tworzenia produktów na portalu wymieszał kompletnie ich kategorie (na przykład: biustonosze w kategorii opasek, nie ma to sensu). Jak mogę przez API zgłosić do zmiany wyłącznie kategorię? Zasób API wymaga ode mnie podawania nie tylko kategorii, ale też zdjęć czy parametrów. Obecna sytuacja dla wielu produktów blokuje mi kompletnie możliwość zgłoszenia zmian dla nich.

**Comment by MaciejFrackowiak** [comment]
Niestety, ale nie ma alternatywnego wyjścia - musisz przekazać każdorazowo zestaw wymaganych danych.

**Comment by hahyes** [comment]
> W przypadku zgłaszania sugestii zmian w produkcie nie można dodać własnej wartości dla wartości niejednoznacznej - "inna".

@MaciejFrackowiak Teraz dopiero zrozumiałem. Muszę podać ten parametr bez wartości własnej. To było tak nielogiczne rozwiązanie, że dopiero na nie wpadłem.
