### ISSUE TITLE
Kategorie (similar) Nie.Podobne - dezinformacja i bałagan w Produktach

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#5996]
https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA

W powyższym poradniku podajecie raczej nieścisłe dane dot. kategorii "similar":

RESP:
"category": {
        "id": "261573",
        "similar": [
            {
                "id": "110914"
            },
            {
                "id": "305121"
            }
        ]
    },
    

REQ:
"category": {
        "id": "261573"                           -- id kategorii podobnej, czyli jedna z
                                                wartości, którą zwróciliśmy w
                                                produkcie w liście category.similar
    },

RESP:
"category": {
        "id": "305121"
    },

Ale pytanie jest inne - kto i kiedy decyduje o sub-katalogu kategorii podobnych w danym Produkcie? Czy ma to prosty związek ze 100% pokryciem się (w kategorii bazowej oraz tych podobnych) tychże parametrów, które identyfikują Produkt i są nienaruszalne?

**Comment by AureliuszBrussy** [comment]
Dziękuję za zwrócenie uwagi - poprawiłem błąd w poradniku. 

Zbiory kategorii podobnych są definiowane przez nas - kategorie mogą różnić się dostępnymi w nich parametrami, dlatego część uzupełnionych w produkcie parametrów może nie być zgodna z tymi możliwymi do użycia w kategorii podobnej. Nie ma tutaj zależności, że parametry identyfikujące produkt są nienaruszalne pomiędzy kategoriami podobnymi, a kategorią główną.

Użyj [GET ​/sale​/products​/{productId}?category.id={similarCategoryId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct), a w parametrze category.id podaj id ze zwróconego przez nas zbioru kategorii podobnych, aby filtrować uzupełnione w produkcie parametry dla wybranej kategorii podobnej. W odpowiedzi otrzymasz parametry produktu, które możesz wykorzystać podczas wystawiania oferty we wskazanej kategorii podobnej.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - Ok, fajnie, świetnie, rewelacja...

Ale czy chce Pan przez to powiedzieć (napisać), że do każdego Produktu z osobna siada ktoś i "analizuje" stan rzeczy, no i dodaje pierwsze lub kolejne kategorie podobne? Jest to taka robota niezależna od zgłoszeń (dot. błędów / nieścisłości w Produkcie), czy jednak ktoś tam opiera się o zgłaszane sugestie? I chyba najważniejsze pytanie - czy jeśli są różne Produkty (bardziej lub mniej do siebie podobne), których kategoria BAZOWA jest dokładnie ta sama, to czy te Produkty mogą mieć też inne zestawy kategorii podobnych, i to całkiem inne ich zestawy? Naprawdę, żadnych ramowych zasad? Wróżki teraz do wystawiania są potrzebne??

**Comment by AureliuszBrussy** [comment]
@FromAnyHole kategorie podobne to zbiory, więc każdy produkt, który został utworzony w jakiejś kategorii znajdującej się w takim zbiorze - będzie miał ten sam zestaw kategorii podobnych.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - no luuudzie... czy to jakiś teleturniej??

Konkretnie poproszę napisać:
Produkt-A w kat. bazowej 1234, ma kat. podobne: 2345, 3456.
Produkt-B w kat. bazowej 2345, zawsze (jeśli są) ma kat. podobne: 1234, 3456 ??
Produkt-C w kat. bazowej 3456, zawsze (jeśli są) ma kat. podobne: 1234, 2345 ??

**Comment by AureliuszBrussy** [comment]
@FromAnyHole jest tak jak opisujesz to w pierwszym przypadku, czyli przy produkcie A, B i C. Do Kategoria bazowa definiuje kategorie podobne i jest to ten sam zbiór kategorii.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - ostatnia kwestia, bo nie padło:

A co jeśli mamy taki przypadek:
INNY Produkt-X w tej samej kat. bazowej 1234, czy może mieć też inne kat. podobne?
Czyli precyzując - czy dla danej kat. bazowej są możliwe różne zbiory kat. podobnych?

**Comment by AureliuszBrussy** [comment]
@FromAnyHole nie, nie powinno być takiej sytuacji.
