### ISSUE TITLE
Dziwne numery paczkomatów

### ISSUE THREAD

**Issue by Tomash667** [allegro/allegro-api#5997]
Na sandbox zaczęły się pojawiać się jakieś dziwne numery paczkomatów. Kiedyś były tam prawdziwe numery paczkomatów.

Teraz są np takie:
CZE-TMS1
CZE-TMS2
CZE-TMS3
ILSCZS001
AUTO1644935449215

![image](https://user-images.githubusercontent.com/260290/183902063-15e6cdcf-2ea3-4330-8aca-a1d6aa606df6.png)

Takich paczkomatów inpostu nie ma na produkcji/środowisku testowym.

**Comment by AureliuszBrussy** [comment]
Dziękuję za zwrócenie uwagi. Czy to utrudnia Ci testowanie funkcjonalności na Sandboxie?

**Comment by Tomash667** [comment]
Tak, gdy robimy u nas testy e2e to trzeba kombinować z wygenerowaniem listu w inpost.

**Comment by AureliuszBrussy** [comment]
@Tomash667 rozumiem, zgłosiłem to do zespołu odpowiedzialnego za usługę - przyjrzą się problemowi. Wrócę do Ciebie z informacją.

**Comment by AureliuszBrussy** [comment]
Punkty odbioru dostarcza nam InPost i nie filtrujemy ich w żaden sposób. InPost może wystawiać testowe punkty służące do testowania integracji przyszłych funkcjonalności. Nie moderujemy tych punktów po naszej stronie.
