### ISSUE TITLE
/order/refund-claims POST powinien zwrócić identyfikator wniosku o prowizję

### ISSUE THREAD

**Issue by sbrzezin** [allegro/allegro-api#5999]
:bulb: **Sugestia / Suggestions**

/order/refund-claims POST nie zwraca identyfikatora utworzonoego wniosku. Jeśli potem chcę odpytać o status wniosku za pomocą /order/refund-claims/{claimId} to najpierw muszę poznać claimId wywołując /order/refund-claims GET i wyszukać go, a potem dopiero użyć /order/refund-claims/{claimId}. Gdyby /order/refund-claims POST od razu zwracało claimId, uniknęlibyśmy jednego niepotrzebnego zapytania.

Dodatkowo, gdy chcę utworzyć za pomocą /order/refund-claims POST nowy wniosek, to może się tak zdażyć, że jest on już utworzony automatycznie przez Allegro. Wówczas dostaję błąd ClaimExistsException. Także w tym wypadku, w treści błędu mógłby być zawarty claimId wniosku z powodów j.w.

pozdrawiam

Sergiusz

**Comment by AureliuszBrussy** [comment]
W odpowiedzi dla [POST /order/refund-claims](https://developer.allegro.pl/documentation/#operation/createRefundApplication) zwracamy identyfikator wniosku o rabat transakcyjny, przykład odpowiedzi znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-obslugiwac-zamowienia-GRaj0qyvwtR#rabaty-transakcyjne-zwroty-prowizji). 

Jeżeli chodzi o sugestię dotyczącą zwracania id wniosku w odpowiedzi z błędem ClaimExistsException - proszę, zgłoś taką sugestię w naszej zakładce [Discussions](https://github.com/allegro/allegro-api/discussions). Dzięki temu inni użytkownicy będą mogli zagłosować na takie rozwiązanie, a my będziemy mieli wgląd w faktyczne zapotrzebowanie na taką funkcjonalność.
