### ISSUE TITLE
Wielowariantowość dostępna po API

### ISSUE THREAD

**Issue by anih** [allegro/allegro-api#6]
Jedno słowo: kiedy?

**Comment by MarcinLuczak** [comment]
Niestety nie jestem w stanie określić terminu udostępnienia API do wielowariantowości. Obserwuj proszę nasze komunikaty - dam tam znać, gdy będziemy znali termin oraz szczegóły.

**Comment by rasskabak** [comment]
+1
Ficzer jest fajny, kiedy ustawilismy na naszych aukcjach wielowariantowosc recznie, sprzedaz wzrosla o kilkadziesiat %. Niestety api nie obsluguje wielowariantowosci, wiec:
a) trzeba konfigurowac setki aukcji recznie
b) zrezygnowac z wielowariantowosic i cieszyc sie znacznie mniejsza sprzedaza.

**Comment by MarcinLuczak** [comment]
@rasskabak rozumiem i cieszę się, że wielowariantowość pomaga. Tak jak wspomniałem w poprzedniej odpowiedzi, nie jestem w stanie określić terminu udostępnienia API do wielowariantowości. Obserwuj proszę nasze komunikaty - dam tam znać, gdy będziemy znali termin oraz szczegóły.
