### ISSUE TITLE
pobranie userId z poziomu REST API - jak?

### ISSUE THREAD

**Issue by DINK74** [allegro/allegro-api#60]
Dopiero zacząłem się bawić REST API - większość rzeczy jakoś ogarnąłem i pierwsza, prosta aplikacja już działa, ale mam zagwozdkę z uzyskaniem userId użytkownika, który zalogował się do aplikacji. Nie znalazłem tego w dokumentacji i jedyne co przychodzi mi do głowy to zalogowanie się do WebAPI przez **doLoginWithAccessToken** co - oprócz **sessionHandlePart** - zwraca także **userId**.
Tak to się robi czy jest jakaś prostsza metoda?

**Comment by TomekKaczmarek** [comment]
Odpisaliśmy Tobie w wcześniejszym wątku. Token możesz rozkodować - więcej informacji na ten temat znajdziesz tutaj: https://en.wikipedia.org/wiki/JSON_Web_Token

**Comment by rtnet-pl** [comment]
Tym narzędziem możesz sprawdzić co zawiera token: https://jwt.io/

**Comment by DINK74** [comment]
Dzięki za odpowiedzi. Powinienem sobie poradzić :-)
