### ISSUE TITLE
[REST] Notyfikacja zmiany drzewa kategorii i pól formularza sprzedaży

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#600]
W Soap WebAPI  jest metoda QueryAllSysStatus za pomocą której można sprawdzić czy zmieniła się wersja drzewa kategorii i  formularza sprzedaży, czy w za pomocą REST też jest/będzie taka możliwość ?

**Comment by LukaszKorek** [comment]
Obecnie nie mamy takiej metody. Dziękujemy za sugestię, przeanalizujemy ją.

**Comment by marcinja2** [comment]
i jakieś decyzje są?

**Comment by PawelTaberski** [comment]
W najbliższym czasie nie planujemy wprowadzać takiego zasobu w REST API.
