### ISSUE TITLE
Błąd "You cannot list items..." podczas PUT'a na ofertach

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6000]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

Podczas wykonywania PUT'a na ofertach zacząłem otrzymywać błąd "You cannot list items after terminating the User Agreement". Czy konto dostało blokadę i treść błędu powinna być inna?

Przykładowy trace-id: d499d3125f79f367

Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
@tomylee0 komunikat jest prawidłowy. Działalność na tym koncie została zakończona - użytkownik rozwiązał umowę z serwisem.

**Comment by tomylee0** [comment]
Dzięki wielkie. Pozdrawiam.
