### ISSUE TITLE
Zatwierdzenie zmian w katalogu - Sandbox

### ISSUE THREAD

**Issue by LukSky24** [allegro/allegro-api#6001]
Czy istnieje szansa aby dodać te zmiany na produkcie w katalogu na Sandbox?
![image](https://user-images.githubusercontent.com/52952445/184068213-3beda505-9d5e-4807-bbc8-8e95eef59735.png)

https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zmiany-w-katalogu/zgloszenia/454ef731-101e-4292-a318-e709653f78e7

Potrzebujemy aby ten produkt miał dodany EAN w katalogu, bo na razie nie możemy wystawić nowej aukcji z Magento. Bazujemy na razie na starym zapytaniu i bez EAN w katalogu, obecnie nie wystawimy tej aukcji. Prosilibyśmy o zatwierdzenie tych zmian.

**Comment by AureliuszBrussy** [comment]
Zgłosiłem Twoją prośbę do odpowiedniego zespołu. Wrócę z odpowiedzią.

**Comment by LukSky24** [comment]
@AureliuszBrussy Czy udało się coś ogarnąć w tym zakresie? Bo widzę, że nadal te zmiany wiszą jako oczekujące.

**Comment by AureliuszBrussy** [comment]
@LukSky24 wprowadziliśmy EAN do tego produktu.

**Comment by LukSky24** [comment]
@AureliuszBrussy Mam pytanie jeszcze do wystawiania nowych aukcji. Korzystamy jeszcze z endpointu 
i chcemy wystawić produkt o EAN `5903609973988` do kategorii o ID `76104` ale dostajemy ciągle błąd: `VALIDATION_ERROR";s:150:"You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer.`. Niby jest taki produkt na koncie `sportcitytest` w tej kategorii ale nie rozumiem czemu draft się utworzył a ale aukcja nie chce się opublikować. 
![image](https://user-images.githubusercontent.com/52952445/184841860-db2aaa9f-a00a-45df-aa93-808a73b9ca94.png)

**Comment by LukSky24** [comment]
@AureliuszBrussy Ok a czy jeśli dany produkt istnieje i wyślemy jakieś inne dane w jednym z atrybutów to czy on się nadpisze? Na jakiej zasadzie możemy określić co możemy nadpisać w danej ofercie a co nie? Bo cześć danych zawsze brana jest z katalogu Allegro i nie ma znaczenia co wyślemy w naszym requeście. Zauważyłem że tak jest z nazwą aukcji dla danego produktu.

**Comment by LukSky24** [comment]
@AureliuszBrussy Czy da się odróżnić w produkcie atrybuty które możemy nadpisać np. w duplikacie aukcji a które są brane z Katalogu Allegro?

**Comment by AureliuszBrussy** [comment]
@LukSky24 parametry przekazane w ofercie powinny być zgodne z tymi, które są zapisane w produkcie, który próbujesz powiązać z daną ofertą. 

Zgodne z produktem muszą być:
- identyfikator kategorii lub identyfikator kategorii podobnej,
- parametry i ich wartości (w przypadku, gdy w produkcie występuje kilka numerów EAN, przekaż tylko jeden z nich),
- wartość parametru GTIN,
- zawartość sekcji Pasuje do (compatibilityList),
- specyfikacja techniczną TecDoc (tecdocSpecification).

Nazwę oferty podajesz własną. 

Zdarzają się produkty, które nie mają zdefiniowanych wartości wszystkich parametrów. Gdy produkt nie ma wypełnionego jakiegoś parametru, który w danej kategorii istnieje - możesz przekazać w nim swoją wartość.
