### ISSUE TITLE
Weryfikacja konta allegrosandbox

### ISSUE THREAD

**Issue by tomaszcicomputer** [allegro/allegro-api#6002]
Witam,

czy jest jakaś szansa na szybszą weryfikację konta testowego allegrosandbox??:)

Potrzebuję pilnie potestować integrację.....

z góry dzięki za info

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by tomaszcicomputer** [comment]
Niestety nie widzę tego po zalogowniu....

![image](https://user-images.githubusercontent.com/111047909/184104815-7b442524-c3e1-42cb-942e-58e446c57cc8.png)

**Comment by AureliuszBrussy** [comment]
@tomaszcicomputer uzupełnij jeszcze fikcyjne dane w zakładce [Weryfikacja firmy](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty). Prześlij tam także dowolne pliki. Gdy to zrobisz - wróć z informacją, zakończę aktywację konta.

**Comment by tomaszcicomputer** [comment]
Zrobione:)

**Comment by AureliuszBrussy** [comment]
Twoje konto jest aktywne.

**Comment by tomaszcicomputer** [comment]
Dzięki za szybką pomoc!:)
