### ISSUE TITLE
"Nie udało się jednoznacznie dopasować produktu" pomimo jednoznaczności.

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6003]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

Problem występuje przy próbie wystawienia oferty (zestaw), błąd jak w tytule "Nie udało się jednoznacznie dopasować produktu" dla EAN'u 5907719402161 pomimo tego ,że przed wystawieniem oferty wysyłam zapytanie na /sale/products?phrase=5907719402161 i zwraca ono dokładnie 1 produkt.

**Comment by AureliuszBrussy** [comment]
Prześlij proszę trace-id swojego wywołania - znajdziesz go w nagłówku naszego response'a. Sprawdzę to.

**Comment by Maciej-Wilkosz** [comment]
trace-id: ca0a8e6a2169aa40

**Comment by AureliuszBrussy** [comment]
Wyjaśniam to z zespołem odpowiedzialnym za ten zasób. Wrócę z odpowiedzią.

**Comment by Maciej-Wilkosz** [comment]
Udało się coś ustalić? @AureliuszBrussy

**Comment by AureliuszBrussy** [comment]
@Maciej-Wilkosz występuje błąd po naszej stronie - faktycznie nie zwracamy dla tego EAN więcej niż jednego produktu, jednak technicznie posiadamy w naszym Katalogu dwa produkty o tym EAN, stąd brak możliwości jednoznacznego dopasowania. Wyjaśniamy jeszcze powód tego błędu. Wrócę z informacją gdy tylko ustalę coś nowego.

**Comment by AureliuszBrussy** [comment]
@Maciej-Wilkosz problem nie powinien już występować.

**Comment by Maciej-Wilkosz** [comment]
Zgadza się już wszystko w porządku , dzięki.
