### ISSUE TITLE
POST sale/product-offers IllegalCharactersInStringParameter - Wartość parametru Cechy dodatkowe zawiera niedozwolone znaki

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6004]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Dzień dobry,

Mam problem z zasobem POST sale/product-offers - chodzi o wystawienie oferty powiązanej z istniejącym produktem Allegro.

`POST sale/product-offers || trace-id:920d9637697118bc`

```
      +"code": "ConstraintViolationException.IllegalCharactersInStringParameter"
      +"message": "The value of a parameter Cechy dodatkowe (216325) contains illegal characters: Unicode 8221"
      +"details": "ConstraintViolationException.IllegalCharactersInStringParameter"
      +"path": "parameters"
      +"userMessage": "Wartość parametru Cechy dodatkowe (216325) zawiera niedozwolone znaki: ”."

```

1. Podpinam się pod produkt, nie przesyłam żadnych parametrów
2. W produkcie Allegro widzę, że w cechach dodatkowych jest fraza „non drip”

Proszę o pomoc

**Comment by hahyes** [comment]
> 1. Podpinam się pod produkt, nie przesyłam żadnych parametrów

@Radeq Produkt posiada zakazane przy wystawianiu znaki. Wymagania co do produktów i ofert niestety nie są spójne. Musisz zgłosić zmiany w produkcie, żeby pozbyli się tego uporczywego znaku.

**Comment by AureliuszBrussy** [comment]
@Radeq faktycznie, produkt w parametrze 216325 posiada niedozwolone znaki (`"`) - tak jak wspomniał @hahyes najlepiej w tym przypadku zgłosić błąd w produkcie, wartość zostanie poprawiona.
