### ISSUE TITLE
unsupported_grant_type z endpointa https://allegro.pl/auth/oauth/token

### ISSUE THREAD

**Issue by walliswoblink** [allegro/allegro-api#6005]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dotychczas żeby pobrać nowy token używaliśmy endpointa 
curl --location --request POST 'https://allegro.pl/auth/oauth/device' \
--header 'Authorization: Basic MDY2YzhhOTk2N2MwNGZjOTk3Mzhm==' \
--header 'Content-Type: application/x-www-form-urlencoded' 
--data-urlencode 'client_id=066c8a9967c04fc99738f67879d67466'

Otrzymujemy wtedy poprawną odpowiedź typu:
{"device_code":"CDaKm9AofVWIiw1cC1LV9ttZQ9FkZnxG","expires_in":3600,"user_code":"mqhjjqu82","interval":5,"verification_uri":"https://allegro.pl/skojarz-aplikacje","verification_uri_complete":"https://allegro.pl/skojarz-aplikacje?code=mqhjjqu82"}

Kod podany w odpowiedzi używamy żeby uzyskać token w ten sposób:
curl --location --request POST 'https://allegro.pl/auth/oauth/token' \
--header 'Authorization: Basic MDY2YzhhOTk2==' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code' \
--data-urlencode 'device_code=CDaKm9AofVWIiw1cC1LV9ttZQ9FkZnxG'

Po potwierdzeniu linka dostajemy odpowiedź
{
    "error": "unsupported_grant_type",
    "error_description": "Unsupported grant type"
}

Czy coś się zmieniło? Ten flow działał nam od kilku lat.

**Comment by AureliuszBrussy** [comment]
Spróbuj zmienić query parametr **grant_type** na `urn:ietf:params:oauth:grant-type:device_code` (bez kodowania).

**Comment by walliswoblink** [comment]
działa, dziękuję
