### ISSUE TITLE
Odpytywanie endpointa | sandbox

### ISSUE THREAD

**Issue by artbski** [allegro/allegro-api#6006]
Witam, odpytuję tego endpointa w środowisku sandbox:
https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=888462600712&mode=GTIN
i nie otrzymuję response'a z produktem

**Comment by MaciejFrackowiak** [comment]
Produktu o wskazanym GTIN (EAN) nie ma w naszej bazie produktowej na Sandbox.

**Comment by artbski** [comment]
a ten jest i sytuacja jest podobna:

https://api.allegro.pl.allegrosandbox.pl/sale/products?phrase=5904622995988&mode=GTIN

**Comment by MaciejFrackowiak** [comment]
Rzeczywiście - ten przypadek wyjaśniam z zespołem, wrócę z odpowiedzią.

**Comment by LukSky24** [comment]
U nas jest podobna sytaucja na sandbox dla tego produktu:
![image](https://user-images.githubusercontent.com/52952445/184325318-612dfe12-d515-4ce4-ac9f-8734d3e5fb38.png)
Widzę dane na Allegro i nr GTIN a API nie zwraca danych:
 
![image](https://user-images.githubusercontent.com/52952445/184325405-0dccb88f-0440-47f1-97e0-1d1b3c0189f2.png)

**Comment by Lukasz-Zurek** [comment]
@LukSky24 Dziękuję za kolejny przykład. Zespół odpowiedzialny za tę funkcjonalność weryfikuje to.
