### ISSUE TITLE
Sandbox account creation / activation

### ISSUE THREAD

**Issue by hendrik2022** [allegro/allegro-api#6007]
Hi, 
we want to use the sandbox account for testing our connection to allegro and new developments, but for finalizing the account creation we need to set the payout. I asked via chat before if we can use fictional bank data. The allegro support said yes, but the blocker is the checksum for the fields and i think we must use real bank data. For this, i need to know if there are any costs or / transfers.
I sent this message to the chat and they redirected me here.

Maybe there is another way to activate and fully use the sandbox account.

Best regards,
Hendrik

**Comment by MartaNowaczyk** [comment]
Hi, you can use bank account generators like [this one](http://generatory.it/) or look for another one. We have payment simulators on the sandbox, so you will not incur any costs.

**Comment by hendrik2022** [comment]
Hi, thank you! And for the company verification, do you need the real documents and data or are empty / fictional data enough for the sandbox account?

**Comment by MartaNowaczyk** [comment]
Fictional

**Comment by hendrik2022** [comment]
Thank you again. How long does the verification process take? Our account: plentymarkets

**Comment by AureliuszBrussy** [comment]
@hendrik2022 I have fully activated your account.
