### ISSUE TITLE
Produktyzacja 

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#6008]
Mam pytania co do produktów w katalogu Allegro.

Rozumiem, że mogę zaproponować nowy produkt w za pomocą https://api.{environment}/sale/product-proposals.
Co w momencie gdy nie zostanie on od razu zatwierdzony?
Czy mogę go pomimo tego od razu wpiąć do oferty Allegro? 
Jeżeli nie - to jak długo można czekać na zatwierdzenie i jak przekonać się czy produkt został zatwierdzony. 
Jeżeli tak - to co w momencie gdy stwierdzicie że produkt zostanie odrzucony? Co się stanie z moją aukcją jak i samym produktem?

Jeżeli wepnę produkt do oferty Allegro (wciąż używamy starych endpointów) to czy nie ma konieczności uzupełniania parametrów produktu, "pasuje do" zdjęć itp.? System zaciągnie to z katalogu produktu?  

Co w momencie gdy jakiś produkt zmieni swoje parametry w katalogu.
Od razu wszystkie oferty z nim powiązanem prezentują nowe wartości?

**Comment by hahyes** [comment]
> Co w momencie gdy nie zostanie on od razu zatwierdzony?

Wstępnie jest zatwierdzany od razu - o ile przejdzie 201 Created, wiadomo.
Później może zostać zmodyfikowany lub usunięty, więc bądź ostrożny. ;)

>Jeżeli wepnę produkt do oferty Allegro (wciąż używamy starych endpointów) to czy nie ma konieczności uzupełniania parametrów produktu, "pasuje do" zdjęć itp.?

W przypadku starego endpointu /sale/offers, niestety jest konieczność uzupełniania parametrów dokładnie tak samo. Zdjęcia trzeba przesyłać własne w każdym wypadku.

>Co w momencie gdy jakiś produkt zmieni swoje parametry w katalogu.
Od razu wszystkie oferty z nim powiązanem prezentują nowe wartości?

Tego nie jestem niestety pewien.

**Comment by MartaNowaczyk** [comment]
> Co w momencie gdy jakiś produkt zmieni swoje parametry w katalogu.
> Od razu wszystkie oferty z nim powiązanem prezentują nowe wartości?

Oferta nie aktualizuje się automatycznie.

Dodam tylko, że warto korzystać z [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers). Na początku 2023 roku przestaniemy wspierać [POST /sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST), a w 2024 planujemy go całkowicie wyłączyć.

**Comment by marmited** [comment]
@hahyes , @MartaNowaczyk dzięki.

Co się stanie gdy Allegro zdecyduje się usunąć produkt, który utworzyłem, bo np. ja mogę źle wyfiltrować dostępne produkty i stwierdzić, że mojego nie ma i dodać nowy nadmiarowy. Czy jeżeli produkt zostanie po czasie usunięty, to zostanie do oferty podpięty „właściwy” produkt? Jeżeli tak to jak można się o tym dowiedzieć, że nastąpiła taka zmiana? Chcę się dowiedzieć, jak przestrzec się przed sytuacją, gdy my cały czas tworzymy nowe produkty, a Allegro będzie je usuwać.

**Comment by AureliuszBrussy** [comment]
@marmited po usunięciu produktu oferta pozostanie bez produktu. Przy kolejnej edycji oferty otrzymasz odpowiedni komunikat - wtedy (w zależności od kategorii) konieczne będzie podpięcie produktu.  

Jeżeli produkt został usunięty i nie istnieje, to po odpytaniu [/sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProducts) zwrócimy response status 404: Not Found.

**Comment by marmited** [comment]
Operujemy tylko na częściach samochodowych, co wymusza zawsze podpięcie produktu. Proszę o rozwinięcie odpowiedzi na pierwszą część pytania. Napisana została bardzo ogólnikowo.

Jeszcze raz:

Co się stanie jeżeli utworzyłem produkt, który po sprawdzeniu okazałby się duplikatem? (mowię tutaj o jakiejś późniejszej analizie, a nie kod 409) 
Produkt zostanie usunięty, odpięty od oferty i oferta pozostanie bez produktu? W momencie edycji takiej oferty będę musiał znowu wpiąć jakiś produkt, tak? Informujecie o tym jakoś użytkownika?
Czy możliwe są jakieś przepięcia produktów po waszej stronie. Np. zauważyliście że ten produkt to jednak nie jest to co użytkownik wskazał, albo jest to duplikat czegoś innego. Przepniecie produkt na inny? Jeżeli tak, to w jaki sposób informujecie użytkownika o takiej akcji?

**Comment by AureliuszBrussy** [comment]
@marmited po rozłączeniu produktu od oferty użytkownik otrzymuje wiadomość e-mailową. W [artykule pomocy](https://allegro.pl/dla-sprzedajacych/rozlaczymy-twoje-oferty-polaczone-z-niewlasciwymi-produktami-z-katalogu-allegro-PgDjoEBalTE) możesz spojrzeć na przykład takiej wiadomości. 

Jeżeli oferta nie jest powiązany z produktem, a jest to konieczne w danej kategorii - przy próbie edycji oferty zwrócimy odpowiedni błąd informujący o tym. 

Jeżeli chodzi o nasze sugestie produktów do połączenia - istnieje taki mechanizm. W osobnych wiadomości e-mail użytkownik może otrzymać sugestie produktów do powiązania z ofertą - samymi powiązaniami może zarządzać z poziomu zakładki [Powiąż oferty z produktami](https://allegro.pl/moje-allegro/sprzedaz/powiaz-oferty-z-produktami). W przypadku motoryzacji takie sugestie są automatycznie akceptowane po 14 dniach (jeżeli nie zostały świadomie przez użytkownika odrzucone). Więcej o tym możesz przeczytać w [artykule pomocy](https://allegro.pl/dla-sprzedajacych/jak-skatalogowac-swoja-oferte-VEWrZz6n4sv#katalogowanie-juz-istniejacych-ofert).

**Comment by marmited** [comment]
Dziękuję. 

Mam jeszcze inne pytanie do produktyzacji.

W sandboxie istnieje przedmiot o identyfikatorze: b607c515-9058-4604-b812-2b0e6bfaf21f.
Zapytanie /sale/products/b607c515-9058-4604-b812-2b0e6bfaf21f zwraca informacje na jego temat.

Korzystając z parametru ISBN chciałbym go odnaleźć za pomocą filtra:

/sale/products?phrase=9788380082434&mode=GTIN&includeDrafts=true

Zwraca brak produktów. Dlaczego?

`{
    "products": [],
    "categories": {
        "subcategories": [
            {
                "id": "5",
                "name": "Dom i Ogród",
                "count": 0
            },
            {
                "id": "11763",
                "name": "Dziecko",
                "count": 0
            },
            {
                "id": "42540aec-367a-4e5e-b411-17c09b08e41f",
                "name": "Elektronika",
                "count": 0
            },
            {
                "id": "4bd97d96-f0ff-46cb-a52c-2992bd972bb1",
                "name": "Firma i usługi",
                "count": 0
            },
            {
                "id": "a408e75a-cede-4587-8526-54e9be600d9f",
                "name": "Kolekcje i sztuka",
                "count": 0
            },
            {
                "id": "38d588fd-7e9c-4c42-a4ae-6831775eca45",
                "name": "Kultura i rozrywka",
                "count": 0
            },
            {
                "id": "ea5b98dd-4b6f-4bd0-8c80-22c2629132d0",
                "name": "Moda",
                "count": 0
            },
            {
                "id": "3",
                "name": "Motoryzacja",
                "count": 0
            },
            {
                "id": "20782",
                "name": "Nieruchomości",
                "count": 0
            },
            {
                "id": "3919",
                "name": "Sport i turystyka",
                "count": 0
            },
            {
                "id": "258832",
                "name": "Supermarket",
                "count": 0
            },
            {
                "id": "1429",
                "name": "Uroda",
                "count": 0
            },
            {
                "id": "121882",
                "name": "Zdrowie",
                "count": 0
            }
        ],
        "path": [
            {
                "id": "954b95b6-43cf-4104-8354-dea4d9b10ddf",
                "name": "Allegro"
            }
        ]
    },
    "filters": [],
    "nextPage": null
}`

Używając waszych przykładów z https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#kliknij-aby-zobaczyc-request

również nie mogłem znaleźć produktów.

W czym jest problem?

**Comment by marmited** [comment]
Czytam też, że podczas szukania produktów w katalogu Allegro:

Lista filtrów:
nie jest tożsama z wartościami, które otrzymasz dla GET /sale/categories/{categoryId}/parameters. Filtr tworzysz, podając identyfikator filtra i identyfikator szukanej wartości, na zasadzie {filter.id}={filter.value}

W takim razie jak w łatwy sposób mogę "przetłumaczyć" parametry oferty na filtry i ich wartości? Bo musi istnieć do tego jakieś podejście.

**Comment by AureliuszBrussy** [comment]
@marmited jeżeli chodzi o brak produktu z ISBN 9788380082434 w wyszukiwaniu - wygląda to na błąd z naszej strony, produkt powinien zostać zwrócony w wynikach. Zgłosiłem to do zespołu odpowiedzialnego za zasób. Wrócę z informacją. 

Jeżeli chodzi o dostępne filtry - powinieneś się sugerować tylko listą **filters** którą zwrócimy w pierwotnym wyniku. Oczywiście pamiętaj o doprecyzowaniu kategorii wyszukiwania (query parametr category.id) - tylko wtedy zwrócimy tą listę. Tak jak wspomnieliśmy w poradniku - parametry i ich wartości, które umożliwiają filtrowanie w danej kategorii nie muszą być dokładnie skorelowane z parametrami dostępnymi w GET /sale/categories/{categoryId}/parameters.

**Comment by marmited** [comment]
OK. 

Czyli jeżeli mam ofertę Allegro, która posiada pełny zakres parametrów to nie mogę ich użyć automatycznie do filtrowania produktów, tak by wyszukać odpowiedniego?
Mówimy o najniższych kategoriach "liściach" i parametrach oznaczonych jako requiredForProduct.

Muszę znaleźć wszystkie filtry obowiązujące w danej kategorii, a następnie kazać użytkownikowi wskazać ręcznie opcje, pomimo tego, że wskazywał odpowiednie parametry na ofercie?

Czy jeżeli podam błędny identyfikator filtra, lub jego opcję to system pominie ten filtr nie rzucając błędu?

**Comment by AureliuszBrussy** [comment]
Zgadza się, powinieneś sugerować się filtrami zwracanymi w **filters** - tylko wtedy masz pewność jaki parametrów możesz użyć do filtrowania wyników oraz jakie wartości możesz przekazać. 

Ignorujemy niepoprawnie użyte filtry - otrzymasz wyniki wyszukiwania, tak jakby błędny filtr nie został użyty. 

Dodatkowo, jeżeli użyjesz wielu filtrów, traktujemy je jako połączone operatorem AND.
