### ISSUE TITLE
Ukrywanie ofert

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6009]
Czy istnieje możliwość, aby z poziomu API ukryć zakończoną ofertę? Chodzi mi o analogiczne działanie jak przycisku UKRYJ w zakładce Mój Asortyment, ale z poziomu API

**Comment by MartaNowaczyk** [comment]
Nie mamy tej opcji w API.

**Comment by mlonc** [comment]
> Nie mamy tej opcji w API.

A czy planujecie w końcu ją dodać?

Temat trafił do sugestii w 2020 roku :)
Pojawiły się już takie sugestie - dopisałem także twoje zgłoszenie. Jeśli wprowadzimy taką funkcjonalność, opublikujemy odpowiedni komunikat.

_Originally posted by @PatrykBocian in https://github.com/allegro/allegro-api/issues/2782#issuecomment-579703757_

**Comment by MartaNowaczyk** [comment]
W najbliższym czasie nie mamy tego w planach, dlatego @mlonc @mateuszcom dodajcie swoje głosy do [odpowiedniego wątku w disscusions](https://github.com/allegro/allegro-api/discussions/4330) + opiszcie szerzej potrzebę i problem jaki stwarza brak tej opcji w API, abyśmy mogli ustalić priorytet i skalę. Zbieramy wszelkie sygnały i zgłaszamy do zespołów odpowiedzialnych za daną funkcjonalność, więc im więcej konkretnych argumentów podacie, tym lepiej.
