### ISSUE TITLE
Metody dostawy, a wybór klienta.

### ISSUE THREAD

**Issue by Skuria** [allegro/allegro-api#6010]
Dzień dobry,
W module wysyłam.allegro.pl.sandbox.pl, dodając przesyłkę automatycznie wyszarzają nam się nie dostępne opcje dla wybranej przez klienta metody dostawy. 
![chrome_iDYC422F4r](https://user-images.githubusercontent.com/42569681/184311867-532fefc2-3b6c-4a16-933a-7f853ec47c5c.png)

Czy jest możliwe aby jeszcze przed tworzeniem przesyłki w api można było znaleźć informacje, które z metod dostawy pobranych z endpointa 
"parcel-management/delivery-services"
są poprawne dla wybranej przez klienta metody dostawy?

Na ten moment, mam wybór wszystkich metod, a dużej mierze dostaję odpowiedź 
"Order cannot be send using selected delivery services" 

Jeśli temat się pojawił już wcześniej to przepraszam ale nie udało mi się przeszukać całości :)

**Comment by MartaNowaczyk** [comment]
Nie ma takiej możliwości. Metodę dostawy jaką wybrał klient widzisz w zamówieniu i z tym musisz powiązać metody z "parcel-management/delivery-services".
