### ISSUE TITLE
WzA problem z Pocztex Automat

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6011]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Witam, problem z paczką ID : 0ff72b4b-8883-42ca-89e1-d47ad7ccf214 
Błąd lakoniczny : "..skontaktuj się z nami najszybciej" ;)

**Comment by Lukasz-Zurek** [comment]
Dziękuję za zgłoszenie. Temat przekazałem dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
Błąd to "Usługa Automat Pocztowy nie jest dostępna dla Format XL". Konsultujemy go dodatkowo z Pocztą Polską. Jak tylko uda się wyeliminować problemy - wrócę z informacją w tym wątku.

Przepraszamy za te utrudnienia.

**Comment by paafcioc22** [comment]
Ale paczka nie była w formacie XL. 
Przekazując dane z zamówienia bezpośrednio do API e-nadawcy - paczka została utworzona.

**Comment by Lukasz-Zurek** [comment]
@paafcioc22 Zgadza się. Nie doprecyzowałem we wcześniejszej wiadomości. Wspomniany komunikat zwraca Poczta Polska i jest on błędny.
