### ISSUE TITLE
Produktyzacja, a lista compatibilityList w produkcie.

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#6012]
Podczas tworzenia nowego produktu za pomocą zasobu `POST /sale/product-proposals` nie zauważyłem, aby było przewidziane dopisanie do niego wartości `compatibilityList`. Ponadto, gdy zepnie się ofertę, która wcześniej miała podaną sekcję Pasuje do... z tak utworzonym produktem, to ta w widoku oferty na stronie Allegro jest nadpisywana przez sekcję z produktu - czyli null i naturalnie znika.

Czy istnieje jakaś inna możliwość podania listy kompatybilności, by została dopisana do produktu?

Rozumiem, że może to być przewidziane przez zasób `POST /sale/product-offers` jednakże, gdy w naszym systemie zaimplementowaliśmy podejście do produktyzacji omawiane w jednym z waszych webinarów o wykorzystaniu tego zasobu, podejście to okazało się zupełnie niepraktyczne z powodu licznych błędów w Państwa bazie produktowej.

**Comment by Lukasz-Zurek** [comment]
@arkwlcz Generalnie jeżeli tworzysz nowy produkt za pomocą POST /sale/product-proposals to faktycznie nie przekażesz `compatibilityList`. Zgodnie z [naszą dokumentacją](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct) - przypiszemy ją automatycznie i zwrócimy w polu "compatibilityList" na podstawie informacji z bazy danych TecDoc.

Nie ma innej możliwości przekazania `compatibilityList`.

**Comment by gantel86** [comment]
1. Cała kategoria części motocyklowe nie jest u was oparta o tecdoc. 
2. Posiadamy tysiące produktów których niema w tecodoc. 

Co wtedy?

**Comment by PrzemyslawLukanowski** [comment]
Nie umożliwiamy dołączenia compatibilityList na poziomie produktu zarówno w przypadku zasobu /sale/product-proposals, jak i /sale/product-offers, tę sekcję możecie obsłużyć tylko na poziomie oferty. Jeśli korzystacie z pierwszego endpointu, to po połączeniu oferty z produktem, możecie uzupełnić listę „pasuje do”, modyfikując ofertę za pomocą PUT /sale/offers/{id} lub PATCH /sale/product-offers. Wystawiając ofertę z produktem za pomocą POST /sale/product-offers, możecie te dane od razu uwzględnić w strukturze - ale poza obiektem productSet.product (na wspomnianym poziomie oferty, nie produktu).

**Comment by gantel86** [comment]
Oferta posiadająca compatibilityList po przypisaniu do produktu który nie ma tej sekcji traci ją. Rozumiem że trzeba jeszcze raz zrobić update oferty po podpięciu do produktu?

**Comment by PrzemyslawLukanowski** [comment]
Dokładnie tak, chodzi o to, aby ten ten krok został wykonany po tym, jak produkt zostanie przypisany do oferty.
