### ISSUE TITLE
Business account - w trakcie weryfikacji

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6013]
Hi, with your help I was able to convert my sandbox account to business. Since then all my offers cannot be purchased thru cart, because
![image](https://user-images.githubusercontent.com/109143627/184367741-21131c72-9bc0-4b78-b327-635bc105b6bd.png)
 https://allegro.pl.allegrosandbox.pl/oferta/nazev-nabidky-7692746827

I did have this option enabled before. If I go to PayU setp page, I am not sure, what can be done to re-enable PayU with the account

Seller account: jiri.zajicek@codingbear.com

![image](https://user-images.githubusercontent.com/109143627/184368010-b0d08f1a-1441-48e3-bbde-cee71d8977dd.png)

Can you help me, so I can list the offers with "add to cart" option?

Thanks!

**Comment by PrzemyslawLukanowski** [comment]
Hello, you see this message in the offer, because you didn't enable any delivery method with payment in advance (only cash on delivery). Add to your shipping price list such delivery method to enable "add to cart" option.

**Comment by ZajdaBear** [comment]
Thank you so much Przemyslaw, I have missed this one!
