### ISSUE TITLE
Pomoc przy request

### ISSUE THREAD

**Issue by wybitnygracz** [allegro/allegro-api#6014]
Dostaję błąd 
"Given parameter id `15851` has not been found in category `83708`, ale w requescie nie przekazuje nigdzie kategorii 83708. Proszę o pomoc. 

REQUEST: 
POST /sale/product-offers HTTP/2
Host: api.allegro.pl
`{"productSet":[{"product":{"name":"Japonki Damskie AquaWave Rachela fioletowe 41","id":"5902786375196","idType":"GTIN","category":{"id":"19918"},"parameters":[{"id":15851,"valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":64,"valuesIds":["64_4"],"values":[],"rangeValue":null},{"id":3766,"valuesIds":["3766_11"],"values":[],"rangeValue":null},{"id":7108,"valuesIds":["7108_651593"],"values":[],"rangeValue":null},{"id":22728,"valuesIds":["22728_2"],"values":[],"rangeValue":null},{"id":203089,"valuesIds":["203089_2048"],"values":[],"rangeValue":null},{"id":215926,"valuesIds":[],"values":["Basen 2022"],"rangeValue":null},{"id":217481,"valuesIds":[],"values":["EVA PHYLON"],"rangeValue":null},{"id":224017,"valuesIds":[],"values":["m000162123"],"rangeValue":null},{"id":232289,"valuesIds":["232289_366677"],"values":[],"rangeValue":null},{"id":237206,"valuesIds":[],"values":["RACHELA WMNS"],"rangeValue":null},{"id":225693,"valuesIds":[],"values":["5902786375196"],"rangeValue":null}],"images":["https:\/\/a.allegroimg.com\/original\/11a196\/e41f1726480fbcc44ffa2b4af8f8","https:\/\/a.allegroimg.com\/original\/11296f\/135c06cf4435ace5c8e0e4b62217","https:\/\/a.allegroimg.com\/original\/119366\/e058eb3f44899e4d8c194ce95f7a","https:\/\/a.allegroimg.com\/original\/11ec50\/07a9f5ef4ff48d0ecf1665914e82","https:\/\/a.allegroimg.com\/original\/11715a\/dbac41e54d09a4a24d7d4e8746b3","https:\/\/a.allegroimg.com\/original\/119193\/3c97053c47bc8a1985a29ae9abf4","https:\/\/a.allegroimg.com\/original\/11f3c1\/03c760cf4e4e837ae05b848f3acd","https:\/\/a.allegroimg.com\/original\/112ce2\/366e4e1b409ba7a87bf7c63a73ec","https:\/\/a.allegroimg.com\/original\/11c2ca\/d7c54a084d83bc5c34e8dc254483"]}}],"b2b":{"buyableOnlyByBusiness":false},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"82bd8369-ebb9-480a-bd43-ec55941e95d1"}},"publication":{"durationUnlimited":true,"startingAt":"2022-08-14T00:00:00Z","status":"INACTIVE","republish":false},"language":"pl-PL","afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"a2f5e179-fa72-4b54-9d4f-72f76ddb4889"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"name":"Japonki Damskie AquaWave Rachela fioletowe 41","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":40,"currency":"PLN"}},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"images":["https:\/\/a.allegroimg.com\/original\/11a196\/e41f1726480fbcc44ffa2b4af8f8","https:\/\/a.allegroimg.com\/original\/11296f\/135c06cf4435ace5c8e0e4b62217","https:\/\/a.allegroimg.com\/original\/119366\/e058eb3f44899e4d8c194ce95f7a","https:\/\/a.allegroimg.com\/original\/11ec50\/07a9f5ef4ff48d0ecf1665914e82","https:\/\/a.allegroimg.com\/original\/11715a\/dbac41e54d09a4a24d7d4e8746b3","https:\/\/a.allegroimg.com\/original\/119193\/3c97053c47bc8a1985a29ae9abf4","https:\/\/a.allegroimg.com\/original\/11f3c1\/03c760cf4e4e837ae05b848f3acd","https:\/\/a.allegroimg.com\/original\/112ce2\/366e4e1b409ba7a87bf7c63a73ec","https:\/\/a.allegroimg.com\/original\/11c2ca\/d7c54a084d83bc5c34e8dc254483"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Japonki Damskie AquaWave Rachela fioletowe 41<\/h1><ul><li>Kolor fioletowy,<\/li><li>Logo na froncie,<\/li><li>Sk\u0142ad podeszwy: EVA Phylon<\/li><li>Sk\u0142ad wierzch: PVC<\/li><li>Wk\u0142adka pianka EVA<\/li><li>Produkt Oryginalny<\/li><li>Technologia Wodoodporne<\/li><\/ul><p><\/p><p>rozmiar: <b>41<\/b><\/p><h1>Cena: 40 z\u0142<\/h1>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11a196\/e41f1726480fbcc44ffa2b4af8f8"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11296f\/135c06cf4435ace5c8e0e4b62217"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/119366\/e058eb3f44899e4d8c194ce95f7a"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11ec50\/07a9f5ef4ff48d0ecf1665914e82"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11715a\/dbac41e54d09a4a24d7d4e8746b3"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/119193\/3c97053c47bc8a1985a29ae9abf4"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f3c1\/03c760cf4e4e837ae05b848f3acd"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/112ce2\/366e4e1b409ba7a87bf7c63a73ec"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11c2ca\/d7c54a084d83bc5c34e8dc254483"}]}]},"stock":{"available":"17","unit":"UNIT"}}`

RESPONSE:
`{"errors":[{"code":"ParameterIdNotFoundException","message":"Unprocessable Entity","details":null,"path":"productSet[0].product.parameters","userMessage":"Given parameter id `15851` has not been found in category `83708`."}]}`

**Comment by PrzemyslawLukanowski** [comment]
1. W tym przypadku doszło do sytuacji, gdzie na podstawie przekazanych danych odnaleźliśmy istniejący produkt w naszym Katalogu (1521b6ba-116d-4cf4-a841-03d93265321e), ale z tego względu, że znajduje się w kategorii 83708, w której nie ma parametru 15851, zwróciliśmy przytoczony komunikat błędu. Zgłosiłem prośbę do zespołu odpowiedzialnego za usługę o weryfikację tej sytuacji i zmianę komunikatu, tak aby bardziej precyzyjnie wskazywał na źródło problemu. W takiej sytuacji możesz usunąć problematyczny parametr ze struktury.
2. Tak, taka logika jest jak najbardziej prawidłowa, ponieważ w rezultacie oferta zawsze będzie połączona z produktem.

**Comment by PrzemyslawLukanowski** [comment]
Tak, taka sytuacja zawsze będzie mieć miejsce, jeśli na podstawie przekazanych danych rozpoznamy, że produkt istnieje już w naszym Katalogu. Jeśli uważacie, że kategoria, którą ustawiliśmy jest nieprawidłowa, możecie zgłosić [sugestię zmiany danych produktu](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).

**Comment by PrzemyslawLukanowski** [comment]
W przypadku API nie umożliwiamy przekazania zbioru kategorii w requeście. Sam produkt posiada kategorię główną, którą zwrócimy w odpowiedzi [GET /sale/products/{productID} ](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wyszukac-produkt-z-naszego-katalogu)w polu [category.id](http://category.id/). To, czego dotyczy odpowiedź konsultanta, to jak rozumiem zbiór kategorii podobnych, w których również możecie wystawić ofertę danego produktu - informację o nich znajdziecie w sekcji category.similar wyżej wspomnianego zasobu. W takim przypadku również jednak musicie dostosować parametry zgodnie z przekazywaną kategorią. Obsługę kategorii podobnych opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-wystawic-oferte-w-kategorii-podobnej).
