### ISSUE TITLE
GET /order/carriers/ALLEGRO/tracking/

### ISSUE THREAD

**Issue by psos** [allegro/allegro-api#6015]
Dla paczki allegro one nie działa pobranie informacji o trackingu

Nr paczki: 003205402591

Prosze o naprawę błędu.

**Comment by PrzemyslawLukanowski** [comment]
Wskazany numer przesyłki dotyczy usługi dostawy "X_PRESS_COURIERS" z dostawą tego samego dnia - dla tej usługi na tę chwilę nie zwracamy historii statusów. Informacja z [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-pobrac-historie-statusow-przesylek-allegro):

"_Za pomocą [GET /order/carriers/ALLEGRO/tracking?waybill={waybill}](https://developer.allegro.pl/documentation/#operation/getAllegroParcelTrackingUsingGET) pobierzesz historię statusów przesyłek Allegro. Jako waybill przekaż numer przesyłki z usługi dostawy Allegro, który otrzymasz w odpowiedzi na [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails) w polu items.waybill. **Usługa dostawy Allegro jest bezpośrednio powiązana z przewoźnikiem o id “ALLEGRO”** - skorzystaj z [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices) i zwróć uwagę na wartość w polu carrierID, aby łatwo rozróżnić usługę dostawy tego typu._"

**Comment by PrzemyslawLukanowski** [comment]
Udostępniliśmy dziś możliwość śledzenia wszystkich przesyłek w ramach Wysyłam z Allegro. Więcej informacji znajdziesz w naszym [newsie](https://github.com/allegro/allegro-api/issues/6020).
