### ISSUE TITLE
AccessDenied podczas próby pobrania /sale/products na środowisku testowym

### ISSUE THREAD

**Issue by synek317** [allegro/allegro-api#6016]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Cześć, próbuję wykorzystać API Allegro po raz pierwszy. Udało mi się wysłać zapytanie o np. /sale/categories. Niestety, przy próbie pobrania /sale/products od początku dostaję AccessDenied:

    curl -H "Authorization: Bearer $TOKEN" -H "Accept: application/vnd.allegro.public.v1+json" "https://api.allegro.pl.allegrosandbox.pl/sale/products

Odpowiedź:

```
{
  "errors": [
    {
      "code": "AccessDeniedException",
      "message": "Access denied.",
      "details": null,
      "path": null,
      "userMessage": "Access denied."
    }
  ]
}
```

Moja aplikacja ma tylko jedno uprawnienie: `allegro:api:sale:offers:read`, ale z tego, co rozumiem, to powinno wystarczyć.

Co mogę robić nie tak?

Client ID: cedeb97ad7a64deb9db8995baba31f9b
Client z apps.developer.allegro.pp.allegrosandbox.pl: 105478841

**Comment by PrzemyslawLukanowski** [comment]
Otrzymujesz ten błąd, ponieważ korzystasz z tokena wygenerowanego w ramach autoryzacji "client_credentials". Token tego typu nie posiada kontekstu użytkownika, dlatego możesz pobrać publiczne dane, jak właśnie listę kategorii, ale nie otrzymasz już informacji np. o swoich ofertach. Skorzystaj proszę z autoryzacji typu [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by synek317** [comment]
Dzięki,  spróbuję! A czy mogę jakoś wykonać zwykle wyszukiwanie tak samo,  jak niezalogowany użytkownik?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie. Przy każdym zasobie w [naszej dokumentacji](https://developer.allegro.pl/documentation) znajdziesz odpowiednie oznaczenie, z jakiego rodzaju autoryzacji musisz skorzystać:
 - bearer-token-for-user - code lub device,
 - bearer-token-for-application - client credentials.

**Comment by synek317** [comment]
Dziękuję za szybką pomoc, wszystko jasne!

**Comment by PrzemyslawLukanowski** [comment]
Jeszcze tylko dopowiem co do ostatniego pytania, bo nie mam pewności, czy początkowo dobrze je zrozumiałem. Możesz skorzystać z GET /offers/listing, aby przeszukiwać oferty w naszym serwisie, jednak jest to zasób, który wymaga dodatkowej weryfikacji. Więcej informacji na ten temat znajdziesz na początku [naszego poradnika](https://developer.allegro.pl/tutorials/jak-wyszukiwac-przegladac-oferty-ZM9YAKAwgfk):

> Jak zweryfikować aplikację?
> 
> Jeśli jesteś w [Programie Partnerskim](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) skontaktuj się ze swoim opiekunem. W innym wypadku skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by synek317** [comment]
O,  świetnie. Czyli ja źle zrozumiałem tamten endpoint :)

Czy na środowisku testowym też niezbędna jest weryfikacja?

Czy prosta aplikacja,  która chciałbym usprawnić swoją sprzedaż,  używana wyłącznie przez jedną osobę i generująca ruch na poziomie kilkunastu-kilkudziesięciu wyszukiwań dziennie ma szansę na taką weryfikację?

**Comment by PrzemyslawLukanowski** [comment]
> Czy na środowisku testowym też niezbędna jest weryfikacja?

Nie, w tym przypadku nie ma takiej potrzeby, endpoint jest dostępny.

> Czy prosta aplikacja, która chciałbym usprawnić swoją sprzedaż, używana wyłącznie przez jedną osobę i generująca ruch na poziomie kilkunastu-kilkudziesięciu wyszukiwań dziennie ma szansę na taką weryfikację?

Weryfikacja odbywa się w zupełności poza naszym działem wsparcia API, dlatego najlepiej będzie, jeśli skontaktujesz się bezpośrednio przez formularz.

**Comment by synek317** [comment]
Ok, dziękuję raz jeszcze. Myślę, że tym razem już naprawdę wszystko jasne :)
