### ISSUE TITLE
Sandbox account activation

### ISSUE THREAD

**Issue by hendrik2022** [allegro/allegro-api#6018]
Hi together,

we want to start using the sandbox for testing / developing, can someone activate our account please?

Our account: plentymarkets
Mail: [hendrik.schulze@plentymarkets.com](mailto:hendrik.schulze@plentymarkets.com)

Thank you very much!

Best regards,
Hendrik Schulze

**Comment by PrzemyslawLukanowski** [comment]
We have activated your account.

**Comment by hendrik2022** [comment]
Big thx!!

**Comment by rafciozarzecz** [comment]
Witam,
Też mogę prosić o aktywację konta do sprzedaży na sandbox'ie?
Mail: ninebot3@int.pl

**Comment by AureliuszBrussy** [comment]
@rafciozarzecz aktywowałem Twoje konto.

**Comment by AureliuszBrussy** [comment]
@navlukaszzborek aktywowałem Twoje konto.

**Comment by AureliuszBrussy** [comment]
@proscinski2k przejdź proszę najpierw [formularz weryfikacyjny](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty) na tym koncie krok po kroku. Wykonaj symulację przelewu weryfikacyjnego oraz uzupełnij fikcyjne dane w formularzu. Gdy to zrobisz wróć z informacją, aktywuję Twoje konto.

**Comment by proscinski2k** [comment]
@AureliuszBrussy Wykonałem wszystkie kroki, proszę o aktywację jeszcze raz:
alewtyczki
adrianp2k@o2.pl

**Comment by AureliuszBrussy** [comment]
@proscinski2k aktywowałem Twoje konto.

**Comment by vaclavdedek** [comment]
Hi, 
@AureliuszBrussy 
I switched my account to business on sandbox, can I also ask you to activate it?
account: vaclav (vaclav.dedek@codingbear.cz)

Thank you very much.

**Comment by AureliuszBrussy** [comment]
@vaclavdedek please, fill in the form with fictitious data on the [Verification](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/przeslij-dokumenty?showOnboardingProgressMsg=true) tab. Come back with the information when you do this - I will activate your account.

**Comment by vaclavdedek** [comment]
@AureliuszBrussy hi, a think all should be filled now

**Comment by AureliuszBrussy** [comment]
@vaclavdedek I have activated your account.

**Comment by rafciozarzecz** [comment]
@AureliuszBrussy Mogę jeszcze prosić o aktywację możliwości wystawiania ofert z metodami wysyłki Allegro SMART?
email: ninebot3@int.pl

**Comment by AureliuszBrussy** [comment]
@rafciozarzecz aby w Twoich ofertach wyświetlał się Smart! musisz spełnić na Sandboxie te same warunki, co na produkcji. Stwórz dodatkowe konta kupujących (pięć), dokonaj zakupów w ofertach i oceń je pozytywnie. Powinieneś także uzupełnić warunki zwrotów (jeśli tego nie zrobiłeś) i udostępnić w cenniku dostawy jedną z wymaganych metod dostawy. 

Po spełnieniu wymagań oferty zostaną oznaczone jako Smart! automatycznie.

Więcej możesz przeczytać w [artykule o Allegro Smart!](https://allegro.pl/dla-sprzedajacych/kategoria/allegro-smart#co-zrobic-aby-twoje-oferty-byly-oznaczone-ikona-allegro-smart).

**Comment by peterk636** [comment]
Hi. Can you please activate my sandbox account - username peterk636. It has been under verification process for several weeks already. Thanks

**Comment by AureliuszBrussy** [comment]
@peterk636 I have activated your account.

**Comment by inTestowy** [comment]
@AureliuszBrussy mogę prosić o aktywację konta do sprzedaży w sandbox'ie? 

mail: test.tescikowy@gmail.com

**Comment by AureliuszBrussy** [comment]
@inTestowy to konto jest specyficzne - założyłeś je jeszcze przed nowym procesem weryfikacji, natomiast nie było w tamtym czasie aktywowane. W tym przypadku proszę, abyś [zarejestrował nowe konto firmowe](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F) pod innym adresem e-mail.

**Comment by inTestowy** [comment]
@AureliuszBrussy Dzięki za odpowiedz ;) w takim razie proszę jeszcze raz o aktywację do sprzedaży kont z e-mail:

intest2.testowy@gmail.com
intest.testowy@gmail.com

**Comment by AureliuszBrussy** [comment]
@inTestowy aktywowałem konto intest.testowy@gmail.com. Wystąpiły małe komplikacje z aktywacją konta intest2.testowy@gmail.com. Zgłosiłem to do odpowiedniego zespołu. Wrócę z informacją po pełnej aktywacji.

**Comment by inTestowy** [comment]
@AureliuszBrussy dziękuję za aktywację konta i czekam na info dotyczące drugiego konta.

**Comment by ArhipenkoVitaliu** [comment]
@AureliuszBrussy Hi. Can you please activate my sandbox business account - username: TestAPI email: arhipenko.vitaliu@gmail.com

**Comment by AureliuszBrussy** [comment]
@ArhipenkoVitaliu I have activated your account.

**Comment by sebastianziobron** [comment]
@AureliuszBrussy  mogę również prosić o aktywację konta w sandbox'ie? email: testyallegro2@gmail.com

**Comment by AureliuszBrussy** [comment]
@sebastianziobron aktywowałem Twoje konto.

@inTestowy Twoje drugie konto także jest już aktywne.

**Comment by inTestowy** [comment]
@AureliuszBrussy Dziękuję, a czy mogę prosić jeszcze o przeprowadzenie weryfikacji firmy na koncie: intest2.testowy@gmail.com oraz intest.testowy@gmail.com

**Comment by AureliuszBrussy** [comment]
@inTestowy obydwa te konta są już zweryfikowanymi kontami firmowymi.

**Comment by inTestowy** [comment]
@AureliuszBrussy  hmm to w takim razie co oznacza informacja: 'Weryfikujemy dane Twojej firmy' ? 
![image](https://user-images.githubusercontent.com/111511140/186357372-e7bdcb28-47fc-4e40-8145-a37421d081c3.png)
![image](https://user-images.githubusercontent.com/111511140/186357534-e3ebdd02-c321-4b12-b854-f3267b405f39.png)

**Comment by AureliuszBrussy** [comment]
@inTestowy konto intest2.testowy@gmail.com jest zweryfikowane i aktywowane. Z kolei na na koncie intest.testowy@gmail.com nastąpiła próba zmiany danych, stąd ponowiona weryfikacja. Natomiast czy mimo to masz problem z wystawieniem oferty na tym koncie?

**Comment by inTestowy** [comment]
@AureliuszBrussy z wystawianiem oferta na Sandboxie nie mam. Jednak mam problem z kontem intest2.testowy@gmail.com, polegający na tym iż z poziomu mojej aplikacji nie przebiega synchronizacja metod dostawy.

**Comment by AureliuszBrussy** [comment]
@inTestowy to konto jest aktywowane, wszystkie metody dostawy dostępne tylko dla konta firmowego są na tym koncie odblokowane. Zweryfikuj poprawność działania swojej aplikacji.

**Comment by inTestowy** [comment]
@AureliuszBrussy przy próbie synchronizacji metod dostawy dla tego konta zwrotnie otrzymuję info:

{"errors":[{"code":"AUTHENTICATION_ERROR","message":"No access to 'Wysyłam z Allegro'","details":null,"path":"header.authorization","userMessage":"Brak dostępu do 'Wysyłam z Allegro'. Aby uzyskać dostęp wystarczy, że przejdziesz na https://allegro.pl/moje-allegro/sprzedaz/wysylam/ustawienia - Twoje konto Allegro połączy się automatycznie"}]}

czy możesz mi pomóc z konfiguracją ?

**Comment by inTestowy** [comment]
@AureliuszBrussy nie, to nie ten sam problem ;) Być może kwestia odświeżenia danych - bo obecnie jest już ok ;) Dziękuję za pomoc.

**Comment by AureliuszBrussy** [comment]
@nthe registration confirmation notifications should arrive without any problem right now. Please check your spam folder, or try registering again using a different e-mail address (service). You will not be able to activate your account without clicking on the registration confirmation link.

**Comment by nthe** [comment]
Understood. The confirmation e-mail never arrived though, I've checked the spam folder as well.
Just FYI, I've tried to register on production site (allegro.pl) with the same e-mail address and all went well without any issues.

I'll try to use different e-mail for sandbox.
Thanks

**Comment by AureliuszBrussy** [comment]
@jakub-marchewka konto aktywne: #1046.

**Comment by jakub-marchewka** [comment]
@AureliuszBrussy dzięki ;)

**Comment by bartlomiejmytnik-is** [comment]
Cześć @AureliuszBrussy, czy mogę prosić o aktywacje konta założonego na : allegrofirmoweis@gmail.com

**Comment by bartlomiejmytnik-is** [comment]
> Cześć @AureliuszBrussy, czy mogę prosić o aktywacje konta założonego na : [allegrofirmoweis@gmail.com](mailto:allegrofirmoweis@gmail.com)

Proszę ponownie o aktywacje.

**Comment by AureliuszBrussy** [comment]
@bartlomiejmytnik-is aktywowałem Twoje konto.

**Comment by bartlomiejmytnik-is** [comment]
@AureliuszBrussy dziękuje
