### ISSUE TITLE
Pomoc z request

### ISSUE THREAD

**Issue by wybitnygracz** [allegro/allegro-api#6019]
REQUEST: 
POST /sale/product-offers HTTP/2
Host: api.allegro.pl
`
{"productSet":[{"product":{"name":"Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41","category":{"id":"55207"},"parameters":[{"id":64,"valuesIds":["64_4"],"values":[],"rangeValue":null},{"id":3766,"valuesIds":["3766_1"],"values":[],"rangeValue":null},{"id":7108,"valuesIds":["7108_85"],"values":[],"rangeValue":null},{"id":15851,"valuesIds":["15851_2"],"values":[],"rangeValue":null},{"id":22728,"valuesIds":["22728_2"],"values":[],"rangeValue":null},{"id":127848,"valuesIds":["127848_2"],"values":[],"rangeValue":null},{"id":203085,"valuesIds":["203085_4"],"values":[],"rangeValue":null},{"id":203105,"valuesIds":["203105_381765"],"values":[],"rangeValue":null},{"id":203729,"valuesIds":["203729_8"],"values":[],"rangeValue":null},{"id":219857,"valuesIds":["219857_287861"],"values":[],"rangeValue":null},{"id":451,"valuesIds":["451_4"],"values":[],"rangeValue":null},{"id":215926,"valuesIds":[],"values":["Jesie\u0144 Zima 2022"],"rangeValue":null},{"id":217481,"valuesIds":[],"values":["GUMA TPR"],"rangeValue":null},{"id":232289,"valuesIds":["232289_366645"],"values":[],"rangeValue":null},{"id":237206,"valuesIds":[],"values":["ARNEL MID"],"rangeValue":null},{"id":127048,"valuesIds":["127048_1024"],"values":[],"rangeValue":null},{"id":203093,"valuesIds":[],"values":["26.5"],"rangeValue":null},{"id":203097,"valuesIds":["203097_215233"],"values":[],"rangeValue":null},{"id":203101,"valuesIds":["203101_215321"],"values":[],"rangeValue":null},{"id":225693,"valuesIds":[],"values":["5902786266388"],"rangeValue":null},{"id":224017,"valuesIds":[],"values":["5902786266388"],"rangeValue":null}],"images":["https:\/\/a.allegroimg.com\/original\/115500\/4deadde24f68ba112b2cc175e0a0","https:\/\/a.allegroimg.com\/original\/11399f\/d37c7d564d70be7de2aca5eae7bc","https:\/\/a.allegroimg.com\/original\/11f033\/dcbbb6e94c35be5db487f70703b1","https:\/\/a.allegroimg.com\/original\/11db10\/e6d3ec9c4673812917857d7bd753","https:\/\/a.allegroimg.com\/original\/116304\/dde05ba64fc7a1ddcdbd8d2a07f9","https:\/\/a.allegroimg.com\/original\/11cb20\/e550db954c1084d17cec70cd514b","https:\/\/a.allegroimg.com\/original\/11dd63\/138d288345e3a686bb411916312f","https:\/\/a.allegroimg.com\/original\/1148ab\/dfc971fc4d709ec02affc6c47528"]}}],"b2b":{"buyableOnlyByBusiness":false},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"82bd8369-ebb9-480a-bd43-ec55941e95d1"}},"publication":{"durationUnlimited":true,"startingAt":"2022-08-16T11:43:34Z","status":"INACTIVE","republish":false},"language":"pl-PL","parameters":[{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":219629,"valuesIds":["219629_286869"],"values":[],"rangeValue":null}],"afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"a2f5e179-fa72-4b54-9d4f-72f76ddb4889"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"name":"Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":269,"currency":"PLN"}},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"images":["https:\/\/a.allegroimg.com\/original\/115500\/4deadde24f68ba112b2cc175e0a0","https:\/\/a.allegroimg.com\/original\/11399f\/d37c7d564d70be7de2aca5eae7bc","https:\/\/a.allegroimg.com\/original\/11f033\/dcbbb6e94c35be5db487f70703b1","https:\/\/a.allegroimg.com\/original\/11db10\/e6d3ec9c4673812917857d7bd753","https:\/\/a.allegroimg.com\/original\/116304\/dde05ba64fc7a1ddcdbd8d2a07f9","https:\/\/a.allegroimg.com\/original\/11cb20\/e550db954c1084d17cec70cd514b","https:\/\/a.allegroimg.com\/original\/11dd63\/138d288345e3a686bb411916312f","https:\/\/a.allegroimg.com\/original\/1148ab\/dfc971fc4d709ec02affc6c47528"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41<\/h1><ul><li>Kolor czarny, br\u0105zowy,<\/li><li>Logo na bokach,<\/li><li>Sk\u0142ad podeszwy: Guma TPR EVA Phylon<\/li><li>Sk\u0142ad wierzch: PU siatka,<\/li><li>Wk\u0142adka pianka EVA<\/li><li>Produkt Oryginalny<\/li><\/ul><p> M\u0119skie buty casualowe Arnel marki Hi-Tec dobrze sprawdzaj\u0105 si\u0119 zar\u00f3wno na miejskich ulicach, jak i na plenerowych spacerach!     Niezwykle uniwersalne, a przy tym interesuj\u0105ce wizualnie \u2013 buty Hi-Tec gustownie dope\u0142ni\u0105 ka\u017cdy zestaw o sportowym lub weekendowym charakterze.      Jednak nie tylko ich estetyka jest warta uwagi! To, co najlepsze, to wysoka jako\u015b\u0107 zastosowanych materia\u0142\u00f3w oraz precyzja wykonania.      W ten spos\u00f3b ka\u017cdy krok b\u0119dzie prawdziw\u0105 przyjemno\u015bci\u0105.      Nie musisz martwi\u0107 si\u0119 tak\u017ce o stabilno\u015b\u0107 \u2013 dzi\u0119ki tradycyjnemu sznurowaniu i solidnej podeszwie o wysokiej przyczepno\u015bci przejdziesz ca\u0142\u0105 tras\u0119 pewnym krokiem. Przekonaj si\u0119 o ich walorach ju\u017c teraz!  <\/p><p>rozmiar: <b>41<\/b><\/p><h1>Cena: 269 z\u0142<\/h1>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/115500\/4deadde24f68ba112b2cc175e0a0"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11399f\/d37c7d564d70be7de2aca5eae7bc"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11f033\/dcbbb6e94c35be5db487f70703b1"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11db10\/e6d3ec9c4673812917857d7bd753"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/116304\/dde05ba64fc7a1ddcdbd8d2a07f9"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11cb20\/e550db954c1084d17cec70cd514b"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11dd63\/138d288345e3a686bb411916312f"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1148ab\/dfc971fc4d709ec02affc6c47528"}]}]},"stock":{"available":"129","unit":"UNIT"}}`

RESPONSE:
`{"errors":[{"code":"PARAMETER_MISMATCH","message":"The provided parameter 'Manufacturer's code'(224017) value (5902786266388) does not match the existing parameter value (Nowa kolekcja)","details":null,"path":"productSet[0].product.parameters","userMessage":"The provided parameter `Manufacturer's code` value `5902786266388` does not match the existing parameter value `Nowa kolekcja`."}]}`

Proszę o wyjaśnienie tego błędu.

**Comment by AureliuszBrussy** [comment]
Na podstawie wysłanego przez Ciebie zestawu parametrów rozpoznaliśmy, że ten produkt istnieje już w naszym Katalogu Produktów, jednak posiada inną wartość w parametrze id 224017 ("Kod producenta"). Po zmianie wartości w tym parametrze na tą oczekiwaną przez nas ("Nowa kolekcja") - wystawianie oferty zakończy się powodzeniem.

Jeżeli w produkcie w naszym Katalogu są błędne dane produktu - możesz zgłosić propozycję zmiany. Więcej o tym przeczytasz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).
