### ISSUE TITLE
[REST] Dziwne wartości 

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#602]
Czy takie dziwne wartości jak 3.4028235e+38 w parametrach kategorii to błąd czy poprawna wartość zasięgu:

{"min":-3.4028235e+38,"max":40,"range":false,"precision":2}
{"min":0,"max":3.4028235e+38,"range":false,"precision":2}

?

**Comment by LukaszKorek** [comment]
Podaj proszę id kategorii w której występuje problem.

**Comment by LukaszKorek** [comment]
Sprawdź proszę zwyklym curlem czy dostajesz  takie dane i czy następnie parsujesz dane do dobrego typu. Być może że w danym języku programowania parsujesz je do zbyt wąskiego typu danych.

Poprosze także o  parametry, których dotyczy problem.

**Comment by SlawomirMizerski** [comment]
Wywołanie w curl-u pod debianem także daje takie same rezultaty:

> {"id":"203093","name":"Długość wkładki (cm)","type":"float","required":false,"unit":null,"options":{"variantsAllowed":false},"restrictions":{"min":-3.4028235E38,"max":40.0,"range":false,"precision":2}}

Lista pól których dotyczy problem:

> 17448 'Waga (z opakowaniem)'  {"min":0,"max":3.4028235e+38,"range":false,"precision":2}
203093 'Długość wkładki (cm)'  {"min":-3.4028235e+38,"max":40,"range":false,"precision":2}
203513 'Szerokość cholewki (cm)'  {"min":-3.4028235e+38,"max":60,"range":false,"precision":2}
203517 'Wysokość cholewki (cm)' {"min":-3.4028235e+38,"max":100,"range":false,"precision":2}

**Comment by LukaszKorek** [comment]
Sprawę zgłosiłem i ją weryfikujemy. Odezwę sie w temacie.
