### ISSUE TITLE
Connect plugin with sandbox account

### ISSUE THREAD

**Issue by hendrik2022** [allegro/allegro-api#6021]
Hello,
I would like to connect our allegro plugin to the allegro sandbox. 
The plugin has production status and works normally.

When I click authorize in our plugin, it takes me to this https://allegro.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=.... (I deleted the code)

After that I am supposed to log in, but it is not the sandbox. And when I add the url with the sandbox url, it asks me if I am "plentymarkets" and I click on. After that I am redirected to the page of the link above, but with the message invalid code.

How can I connect the plugin to the sandbox? I can't find any credentials in the sandbox account.

Best regards,
Hendrik Schulze

**Comment by MartaNowaczyk** [comment]
It looks like you're using production data. On the test environment - Sandbox, you should use data from the test environment and separate addresses:

- Resource address - https://api.allegro.pl.allegrosandbox.pl/
- Application registration - https://apps.developer.allegro.pl.allegrosandbox.pl/
- Authorization address - https://allegro.pl.allegrosandbox.pl/auth/oauth/

You can find more in our [guide](https://developer.allegro.pl/tutorials/basic-information-VL6YelvVKTn#test-environment).
