### ISSUE TITLE
Duplikaty w katalogu produktów? 

### ISSUE THREAD

**Issue by wybitnygracz** [allegro/allegro-api#6022]
Wyszukuję produkty po kodzie phrase=5902786266388&mode=GTIN

I dostaję 3 różne wyniki: 
Męskie buty casual ARNEL MID 41
Buty miejskie Hi-Tec Arnel Mid r. 41
Buty trekkingowe Hi-Tec Arnel Mid r. 41

Proszę o informację w jaki sposób udało się Wam pod tym samym kodem skatalogować 3 różne produkty i który w takim razie mamy wybrać próbując wystawić produkt powiązany z Waszym katalogiem.

**Comment by MartaNowaczyk** [comment]
EAN nie zawsze jest unikalny dla produktu, stąd w tym przypadku widzisz 3 propozycje. Czasami jest tak, że pod jednym numerem EAN kryją się warianty (np. kolorystyczne), dla których producent nie wykupił oddzielnych numerów. 
Nie jest to błąd techniczny po stronie API, dlatego jeśli masz więcej pytań o wyniki wyszukiwania w Katalogu proszę o kontakt przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).
