### ISSUE TITLE
Create a new parcel - mandatory pickup

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6024]
Hi, in your documentation, the object "pickup" in resource PUT /parcel-management/parcel-create-commands/ i marked as mandatory. I am quite not sure what should I pass here, if the delivery is not to parcel shop, but rather a home delivery. Do I send some dummy data? Please advice.

Thanks

Jirka

**Comment by AureliuszBrussy** [comment]
In the "pickup" object you need to enter the data of the sender of the package - that is, the address from where the package should be picked up (from sender) by the courier. You can read more about creating parcels in [our guide](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#press-here-to-show-request).

**Comment by ZajdaBear** [comment]
Thanks for your help, I was working with the page you provided, but for some reason, JSON comments did not get transated. Opening the link from different browsers gives me different result :)

**Comment by ZajdaBear** [comment]
Can I have additional question within same tocket please? I am having trouble undrerstaving the formulation

-- required, if parcel is shipped from a pickup point.
                                        You can retrieve pickup point ID from the order via
                                        GET /order/checkout-forms

![image](https://user-images.githubusercontent.com/109143627/185147744-45a05229-b6f4-4def-956e-d3f7f16c6187.png)

On the order, I have pickupPoint.id, which is a information about the parcel shop, the customer wish the order to be delivered to. I am not sure what do you mean by "shipped from pickup point".

**Comment by AureliuszBrussy** [comment]
Feel free - you can ask any number of questions in a single thread :).

I see that one of the comments (for receiver.pointId), is poorly worded. I already corrected it. Value is required if the parcel is shipped **to** a pickup point (buyer ordered shipment to pickup point). 

As for pickup.pointId - there are courier services, where the seller can send the parcel at the parcel shop, so you can point out this point.

**Comment by ZajdaBear** [comment]
Amazing, thank you. Is there a reason, the message has two occurences of pointId?

**Comment by AureliuszBrussy** [comment]
@ZajdaBear you mean **receiver.pointId** and **pickup.pointId**? 

As I mentioned - the fields are used for something else:
- receiver.pointId is used to define the pickup point from which the buyer will pick up the package, 
- pickup.pointId is used to define the point of sending the package, that is, the seller will send the package at the defined point.

**Comment by ZajdaBear** [comment]
Thanks for your patience :)
So the business case is, I am a smaller seller and carrier won't pick up shipemts at my warehouse, but I will bring it to carriers parcelShop, right? 
How do I use this feature from your GUI? I cannot find, anywhere to enter id of the parcelshop for goods to be picked up from.

**Comment by AureliuszBrussy** [comment]
You need to take the value of point ID from the API of the appropriate carrier. 

You can check our points (Allegro One service) by using [GET /order/carriers/ALLEGRO/points](https://developer.allegro.pl/documentation/#operation/getAllegroPickupDropOffPointsGET). Read more in [our guide](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-list-of-allegro-pickup-drop-off-points).

**Comment by ZajdaBear** [comment]
Ok, but there is no way to set this up from Allegro GUI, right?

**Comment by AureliuszBrussy** [comment]
You can use Send with Allegro feature from [Orders](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/) tab. [Here are instructions](https://allegro.pl/for-sellers/how-to-use-ship-with-allegro-Bvvbez976hG) on how this feature works in our GUI.
