### ISSUE TITLE
Pomoc w request

### ISSUE THREAD

**Issue by wybitnygracz** [allegro/allegro-api#6025]
REQUEST: 
POST /sale/product-offers HTTP/2
Host: api.allegro.pl
`{"productSet":[{"product":{"name":"Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41","images":["https:\/\/a.allegroimg.com\/original\/11a9d7\/5b09315a400280fd18d2f0098fae","https:\/\/a.allegroimg.com\/original\/117a61\/858e24a84398b2adbd523c2b24f3","https:\/\/a.allegroimg.com\/original\/11a43e\/b7f0a4c347dcbf9b3aba0cae0c0f","https:\/\/a.allegroimg.com\/original\/1158fd\/74756d3d4d08a9ab365a7c651cc4","https:\/\/a.allegroimg.com\/original\/11ee66\/6b7be0a642fb92d9609f47eef999","https:\/\/a.allegroimg.com\/original\/119020\/e9f5dc2f4ed6bd5a53b04fee93ad","https:\/\/a.allegroimg.com\/original\/11bd17\/e0a9f6cc40f68d12037d23dda5a5","https:\/\/a.allegroimg.com\/original\/11bbbf\/22b7961e41beb489ebf3e002a68c"],"category":{"id":"55207"},"id":"5902786266388","idType":"GTIN"}}],"b2b":{"buyableOnlyByBusiness":false},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"82bd8369-ebb9-480a-bd43-ec55941e95d1"}},"publication":{"durationUnlimited":true,"startingAt":"2022-08-17T15:03:18Z","status":"INACTIVE","republish":false},"language":"pl-PL","parameters":[{"id":11323,"valuesIds":["11323_1"],"values":[],"rangeValue":null},{"id":219629,"valuesIds":["219629_286869"],"values":[],"rangeValue":null}],"afterSalesServices":{"impliedWarranty":{"id":"d2742331-2bdd-4daf-a7d5-61d01ab29e82"},"returnPolicy":{"id":"a2f5e179-fa72-4b54-9d4f-72f76ddb4889"},"warranty":{"id":"ac0b75d7-6008-4f3a-b300-6b53f8c7d0a1"}},"name":"Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41","payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":269,"currency":"PLN"}},"location":{"countryCode":"PL","province":"LUBELSKIE","city":"Lubart\u00f3w","postCode":"21-100"},"images":["https:\/\/a.allegroimg.com\/original\/11a9d7\/5b09315a400280fd18d2f0098fae","https:\/\/a.allegroimg.com\/original\/117a61\/858e24a84398b2adbd523c2b24f3","https:\/\/a.allegroimg.com\/original\/11a43e\/b7f0a4c347dcbf9b3aba0cae0c0f","https:\/\/a.allegroimg.com\/original\/1158fd\/74756d3d4d08a9ab365a7c651cc4","https:\/\/a.allegroimg.com\/original\/11ee66\/6b7be0a642fb92d9609f47eef999","https:\/\/a.allegroimg.com\/original\/119020\/e9f5dc2f4ed6bd5a53b04fee93ad","https:\/\/a.allegroimg.com\/original\/11bd17\/e0a9f6cc40f68d12037d23dda5a5","https:\/\/a.allegroimg.com\/original\/11bbbf\/22b7961e41beb489ebf3e002a68c"],"description":{"sections":[{"items":[{"type":"TEXT","content":"<h1>Buty M\u0119skie Hi Tec Arnel Mid br\u0105zowe sportowe 41<\/h1><ul><li>Kolor czarny, br\u0105zowy,<\/li><li>Logo na bokach,<\/li><li>Sk\u0142ad podeszwy: Guma TPR EVA Phylon<\/li><li>Sk\u0142ad wierzch: PU siatka,<\/li><li>Wk\u0142adka pianka EVA<\/li><li>Produkt Oryginalny<\/li><\/ul><p> M\u0119skie buty casualowe Arnel marki Hi-Tec dobrze sprawdzaj\u0105 si\u0119 zar\u00f3wno na miejskich ulicach, jak i na plenerowych spacerach!     Niezwykle uniwersalne, a przy tym interesuj\u0105ce wizualnie \u2013 buty Hi-Tec gustownie dope\u0142ni\u0105 ka\u017cdy zestaw o sportowym lub weekendowym charakterze.      Jednak nie tylko ich estetyka jest warta uwagi! To, co najlepsze, to wysoka jako\u015b\u0107 zastosowanych materia\u0142\u00f3w oraz precyzja wykonania.      W ten spos\u00f3b ka\u017cdy krok b\u0119dzie prawdziw\u0105 przyjemno\u015bci\u0105.      Nie musisz martwi\u0107 si\u0119 tak\u017ce o stabilno\u015b\u0107 \u2013 dzi\u0119ki tradycyjnemu sznurowaniu i solidnej podeszwie o wysokiej przyczepno\u015bci przejdziesz ca\u0142\u0105 tras\u0119 pewnym krokiem. Przekonaj si\u0119 o ich walorach ju\u017c teraz!  <\/p><p>rozmiar: <b>41<\/b><\/p><h1>Cena: 269 z\u0142<\/h1>"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11a9d7\/5b09315a400280fd18d2f0098fae"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/117a61\/858e24a84398b2adbd523c2b24f3"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11a43e\/b7f0a4c347dcbf9b3aba0cae0c0f"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1158fd\/74756d3d4d08a9ab365a7c651cc4"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11ee66\/6b7be0a642fb92d9609f47eef999"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/119020\/e9f5dc2f4ed6bd5a53b04fee93ad"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11bd17\/e0a9f6cc40f68d12037d23dda5a5"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11bbbf\/22b7961e41beb489ebf3e002a68c"}]}]},"stock":{"available":"129","unit":"UNIT"}}
`
RESPONSE:
HTTP/2 422 
 

`{"errors":[{"code":"ProductValidationException","message":"Unable to create product without proper values in all required parameters: [Marka, Rozmiar, Długość wkładki, Kolor, Materiał zewnętrzny, Materiał wkładki, Wysokość, Ocieplenie, Cechy dodatkowe, Kod producenta] in category: 55207","details":null,"path":"productSet[0].product","userMessage":"Nie można stworzyć produktu bez podania poprawnych wartości wszystkich parametrów wymaganych: [Marka, Rozmiar, Długość wkładki, Kolor, Materiał zewnętrzny, Materiał wkładki, Wysokość, Ocieplenie, Cechy dodatkowe, Kod producenta]"}]}`

Przed stworzeniem tego zapytania, odszukaliśmy istniejące produkty na podstawie zapytania: 
$data['mode'] = 'GTIN';
$data['phrase'] = '5902786266388';
$data['category.id'] = '55207';

Na podstawie tego zapytania, allegro zwróciło jeden produkt, dlatego zakładamy, że przekazując powyższe zapytanie, nie powinniśmy "tworzyć" nowego produktu, a wykorzystać istniejący. 

Jeśli natomiast podamy komplet naszych cech to dostajemy błąd 

"Given parameter id `203729` has not been found in category `55205`." 
Który wskazuje, że allegro dopasowało jednak produkt. 

Gdy zaktualizujemy kategorie na taką (mimo, tego że różne produkty o tym samym EAN należą w Waszym katalogu do różnych kategorii!) to  dostajemy błędy związane z tym że produkt w Waszym katalogu posiada inną wartość niż chcemy podać (my podajemy prawidłową, a posiadacie złą) 

Proszę o opisanie algorytmu który powinniśmy zaimplementować, jeśli 
- posiadamy nasze przypisania cech do produktów które od dawana funkcjonowały i chcemy z nich nadal korzystać lub użyć istniejących z Waszego katalogu produktów na podstawie EAN produktu (jak dopasować produkt, ponieważ próbowaliśmy kombinacji kategorai-EAN, kolor-EAN, producent-EAN), ale żadne podejście nie zapewnia nam automatyzacji procesu. 
- chcemy zautomatyzować proces wystawiania produktów, tak aby nie zgłaszać do allegro "prośby o poprawki" w katalogu produktów za każdym razem gdy chcemy wystawić produkt. Ponieważ to nie wchodzi w grę musimy zautomatyzować cały proces.

**Comment by MartaNowaczyk** [comment]
EAN nie zawsze jest unikalny dla produktu i nie zawsze jest ostatecznym czynnikiem, który decyduje, czy produkt już istnieje, czy nie. Liczą się też parametry, takie jak np. kolor czy kod producenta, które mogą wymusić stworzenie nowego produktu nawet dla wpisanego numeru EAN. Dlatego w tym przypadku jeśli wyszukałeś produkt podaj jego identyfikator w części produktowej. Jeżeli w odpowiedzi otrzymujesz informację, aby uzupełnić brakujące parametry obowiązkowe, przekaż je w obiekcie product.

Jeśli pobierzesz pełne dane o produkcie [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct), masz tam informację o kategoriach podobnych (category.similar) - oznacza to, że możesz powiązać ten produkt również z ofertą w jednej z tych kategorii podobnych.
 
Jeśli widzisz błąd w produkcie, nie ma innej możliwości, jak zgłosić błąd.

Wszystko szczegółowo opisujemy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA). 

Jeśli podajesz przykłady i błędy podaj proszę trace-id do weryfikacji, żebyśmy mieli pełen obraz sytuacji.
