### ISSUE TITLE
Internal server error na POST sale/offers

### ISSUE THREAD

**Issue by pkoziolandrobit** [allegro/allegro-api#6026]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Przykładowe zapytanie z odpowiedzią:
`POST   https://api.allegro.pl/sale/offers   {"afterSalesServices":{"impliedWarranty":{"id":"2a9a1b91-16ee-425b-8d61-7552a6454f31"},"returnPolicy":{"id":"6ddcdb4c-285c-4214-8210-42425ff76f4a"},"warranty":{"id":"c38e278a-525c-4cd8-9343-cf09e82c7f5d"}},"category":{"id":"124264"},"delivery":{"shippingRates":{"id":"b872568d-4b22-4198-b8d3-037a673d604c"},"handlingTime":"PT24H"},"external":{"id":"stocksell_811995367"},"images":[{"url":"https://a.allegroimg.com/original/1124fd/251210d040baad93d3f48ee89338"},{"url":"https://a.allegroimg.com/original/118830/e454d8904de9b3d684b2628913ad"}],"location":{"city":"Olesno","countryCode":"PL","postCode":"33-210","province":"MALOPOLSKIE"},"parameters":[{"id":"15851","valuesIds":["15851_1"]},{"id":"201025","valuesIds":["201025_2521"]},{"id":"127662","valuesIds":["127662_2"]},{"id":"11323","valuesIds":["11323_1"]},{"id":"54","valuesIds":["3806_3"]},{"id":"451","valuesIds":["451_2"]},{"id":"59","valuesIds":["59_9"]},{"id":"3766","valuesIds":["3766_1"]},{"id":"127488","valuesIds":["127488_225850"]},{"id":"3786","valuesIds":["3786_270490"]},{"id":"4126","valuesIds":["4126_206685"]},{"id":"127468","valuesIds":["127468_4"]},{"id":"201017","valuesIds":["201017_2377"]},{"id":"18160","valuesIds":["18160_1"]},{"id":"201089","values":["35"]},{"id":"202477","valuesIds":["202477_2"]}],"name":"MISSGUIDED SUKIENKA MINI CZARNA 36 1HAA","payments":{"invoice":"VAT"},"publication":{"startingAt":"2022-08-17T17:10:53.000Z","duration":"PT72H","republish":true},"sellingMode":{"format":"AUCTION","price":{"amount":53.99,"currency":"PLN"},"startingPrice":{"amount":45.99,"currency":"PLN"}},"stock":{"available":1,"sold":0,"unit":"UNIT"},"description":{"sections":[{"items":[{"type":"TEXT","content":"\u003ch2\u003eMISSGUIDED SUKIENKA MINI CZARNA\u003c/h2\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/1124fd/251210d040baad93d3f48ee89338"},{"type":"TEXT","content":"\u003ch2\u003eOpis Produktu\u003c/h2\u003e\u003cul\u003e\u003cli\u003e\u003cb\u003eMarka\u003c/b\u003e MISSGUIDED \u003c/li\u003e\u003cli\u003e\u003cb\u003eKolor\u003c/b\u003e czarny\u003c/li\u003e\u003cli\u003e\u003cb\u003eSkład\u003c/b\u003e 75% poliester 20% wiskoza 5% elastan\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka papierowa\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eMetka wewnętrzna\u003c/b\u003e Tak\u003c/li\u003e\u003cli\u003e\u003cb\u003eRozmiar\u003c/b\u003e EU 36 S UK 8\u003c/li\u003e\u003cli\u003e\u003cb\u003eStan przedmiotu\u003c/b\u003e drobne zaciągnięcie na dole sukienki\u003c/li\u003e\u003cli\u003e\u003cb\u003eCena katalogowa\u003c/b\u003e 75,99 zł\u003c/li\u003e\u003c/ul\u003e"}]},{"items":[{"type":"IMAGE","url":"https://a.allegroimg.com/original/118830/e454d8904de9b3d684b2628913ad"}]}]},"tax":{"percentage":"23.00"},"product":{"id":"d1fa3524-aeec-4c38-9052-bee4b68b0416"}}`

`INTERNAL_SERVER_ERROR Internal server error. Please try again in a few minutes. Internal server error. . Trace-id=[80f6c6e6b26c76b9].`

Trace-id=[80f6c6e6b26c76b9]

W ostatnich ok 3 godzinach dostaliśmy kilkadziesiąt razy taki wyjątek w odpowiedzi na próbę utworzenia aukcji.

Konto: outletover@gmail.com

**Comment by MartaNowaczyk** [comment]
Wczoraj mieliśmy problemy w tych godzinach, jednak nie powinny już występować. Przepraszamy za niedogodności.
