### ISSUE TITLE
sens istnienia metody https://api.{environment}/sale/offer-price-change-commands/{commandId}

### ISSUE THREAD

**Issue by barpas** [allegro/allegro-api#6027]
w aplikacji nad którą pracuję zachodzi konieczność zmiany cen w wielu aukcjach 
chciałem zastosować metodę opisywaną jako metoda "hurtowej" zmiany cen
ale albo źle to rozumiem albo zasób /sale/offer-price-change-commands/ kompletnie się do tego nie nadaje
ponieważ umożliwia zmianę ceny w wielu aukcjach ale na 1 wspólną cenę 

stąd pytanie jak zmienić ceny w wielu aukcjach jeżeli każda cena ma być inna - czy trzeba wielokrotnie wywoływać tą samą podobno "hurtową" metodę ?

**Comment by jakubmaguza** [comment]
Po jednej :)

**Comment by MartaNowaczyk** [comment]
Nie ma możliwości by zmienić wiele ofert na różne ceny w jednym requeście, także jeśli cena jest inna, trzeba wysłać odrębny request.

**Comment by mirkosmuz** [comment]
Przydało by się by ten endpoint mógł modyfikować ceny licytacji.

**Comment by MartaNowaczyk** [comment]
@mirkosmuz Sugestie możesz dodać w [Disscussions](https://github.com/allegro/allegro-api/discussions).

**Comment by jakubmaguza** [comment]
@MartaNowaczyk ta sugestia pojawia się od początku wprowadzenia tej metody. Czy jest jakakolwiek szansa że to wprowadzicie?

**Comment by barpas** [comment]
> Nie ma możliwości by zmienić wiele ofert na różne ceny w jednym requeście, także jeśli cena jest inna, trzeba wysłać odrębny request.

jaki jest sens istnienia hurtowej metody zmiany cen skoro nie da się przy jej pomocy zmieniać cen hurtowo ?
dlaczego nie można podawać par - nr aukcji - nowa cena? 
nie sądzi Pani że taka metoda była by zdecydowanie bardziej przydatna ?
(tak samo powinno działać hurtowe zmienianie stocku)

**Comment by jakubmaguza** [comment]
@barpas Da się zmieniać wiele aukcji. W bardzo dziwny sposób, ale się da :P

**Comment by jakubmaguza** [comment]
https://github.com/allegro/allegro-api/discussions/6035

**Comment by MartaNowaczyk** [comment]
@jakubmaguza @barpas praktycznie każda sugestia jest przez nas rozpatrywana + oceniane są potrzeby i możliwości jej wprowadzenia. Bierzemy pod uwagę wasze pomysły, jednak nie zawsze możemy je wdrożyć. Na ten moment nie mamy tego w planach, ale właśnie przekazałam Wasze pomysły do odpowiedniego zespołu. Kiedy i czy w ogóle da się coś zrobić w tym temacie, tego nie mogę określić, bo dopiero przekazałam potrzebę.

**Comment by jakubmaguza** [comment]
@MartaNowaczyk Dziękuję.
Motywacja jest bardzo prosta: zamiast wysyłać 10 000 requestów ze zmianą ceny, można wysłać np. 10 requestów po 1000 zmian w jednym. Do tego później łatwiej też sprawdzić czy wszystko się udało.
