### ISSUE TITLE
Ship with allegro - linking order with parcel

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6028]
Hi, I was reading thru your documentation and I believe I have some understanding, but I must be missing something. When I use GUI, I create packages for specific order, but I cannot find the  way to link order with package in  the API. So my quations are: 

1. Is there a way to link order with package using API?
2. Possibly related question. Do I need to update order tracking information (using POST /order/checkout-forms/{id}/shipments) when using ship with Allegro delivery services? If so, where do I get the package number? Is it parcelId i get from package status after creating package? Business documentation suggests you will do this for seller, but I am not sure, not seeing the link :)

Thanks so much for your advice

Jirka

**Comment by MartaNowaczyk** [comment]
1. You can add a package using [Ship with Allegro](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV) via API. In this case, the package will be associated with the order via a [masked e-mail]([url](https://developer.allegro.pl/news/as-of-march-26th-we-will-start-masking-e-mails-in-the-allegro-api-XxW41EEVGHy)) that contains information about the transaction.
2. You don't need to update the package tracking status. In fact, there is no such possibility. If you add a package number to an order, the buyer will see the status of their shipment.

**Comment by ZajdaBear** [comment]
Hi,
1. Thanks, I must have missed that one
2. Sry, my question might not be worded correctly. So in case of shipping with Allegro, do I need to add package number to an order?

**Comment by MartaNowaczyk** [comment]
Hi,

1. :) 
2. No, you do not have to.

**Comment by ZajdaBear** [comment]
Thanks very much for your help. Have a nice day.
