### ISSUE TITLE
Czy jest możliwość pozyskania product_id z aukcji bez pobierania całej aukcji?

### ISSUE THREAD

**Issue by adamzaw** [allegro/allegro-api#6029]
Czy jest możliwość pozyskania product_id z aukcji bez pobierania całej aukcji?
w liście z sale/offers nie widzę.

**Comment by FromAnyHole** [comment]
Ni Who Yaaa ;-)
ID Produktu lub teraz Produkto-Szkico-Draftu masz tylko w obiekcie Oferty.
Jeśli przeszukujesz bazę Produktów możesz dostać zestaw ID (30 na stronę).

**Comment by MartaNowaczyk** [comment]
@adamzaw Nie ma takiej możliwości. Mamy już taką [sugestię](https://github.com/allegro/allegro-api/discussions/5992). Dodaj tam proszę swój głos.
