### ISSUE TITLE
[REST] Parametr typu dictionary zwraca wartości w values zamiast valuesIds

### ISSUE THREAD

**Issue by imper86** [allegro/allegro-api#603]
Witam,

Zauważyłem dzisiaj bardzo ciekawą rzecz - mianowicie otrzymałem sobie taki response: https://pastebin.com/wBAMZFuT

I chciałbym tutaj zauważyć, że parametr id 451 ma typ dictionary, czyli jego wartość powinna być określona w valuesIds. Tutaj natomiast widać, że jakimś cudem wypluwa dane w values.

Dacie radę usunąć ten błąd? Niestety wygląda na to, że ma on szerszy impact niż tylko pobieranie danych, ponieważ próba wznowienia takiej aukcji kończy się błędem "VALIDATION_ERROR - Attribute value does not exists Kolor(451)".

**Comment by LukaszKorek** [comment]
Podeślij proszę response z podanym komunikatem. Pozwoli to na pełną weryfikację problemu.

**Comment by imper86** [comment]
No dobrze, więc weźmy na warsztat aukcję 7448242337
Odpytanie z GET /sale/offer/7448242337 - https://pastebin.com/1nEAa94K
Uuid wznowienia - ccf0eb1a-5c93-4e46-ba46-5d156f2ab71f
Odpowiedź po odpytaniu GET /sale/offer-publication-commands/ccf0eb1a-5c93-4e46-ba46-5d156f2ab71f/tasks - https://pastebin.com/miMZEFmh

Z większością aukcji poradziłem sobie po prostu aktualizując dane oferty za pomocą PUT /sale/offer/ natomiast akurat na tej powyższej aukcji nie wiedzieć czemu nie chce to zadziałać i wisi nie wznowiona. No i boję się, że sytuacja dotyczy dużo większej ilości aukcji i w przyszłości wolałbym uniknąć aktualizowania parametru, który już dawno temu był prawidłowo ustawiony.

**Comment by LukaszKorek** [comment]
Przepraszam za zwłokę w odpowiedzi. Sprawę analizujemy, gdy tylko będę coś wiedział odezwę sie.

**Comment by imper86** [comment]
@LukaszKorek wydaje mi się, że można to było lepiej rozegrać niż zwracać nieprawidłowe dane w GET /sale/offer/ no ale trudno, domyślam się, że tak to już ma zostać.

**Comment by LukaszKorek** [comment]
Metodą  GET na zasobie /sale/offers/{offerId} pobierzesz wszystkie pola wskazanej oferty łącznie z parametrami takiej oferty na, które są w ofercie w momencie pobierania. Nie ma tutaj błędu.
