### ISSUE TITLE
Super Sprzedawca konto sportcitytest

### ISSUE THREAD

**Issue by pzareba86** [allegro/allegro-api#6030]
Dzień dobry,
potrzebuje na koncie sportcitytest na sandboxie ustawić, żeby być Super Sprzedawcą, jest to niezbędny bym miała smart, a testuje dostawy w smarcie. Jest info, że konto mam zwykłe a ma być firmowe ale ja widze że mam firmowe. Prosze to ustawić - jest to dla mnie ważne.

**Comment by MartaNowaczyk** [comment]
@pzareba86 aktywowałam to konto. Zobacz czy teraz jest ok.

**Comment by pzareba86** [comment]
Niestety dalej nic się nie zmieniło.
![image](https://user-images.githubusercontent.com/98810516/185383131-455f6037-3e87-414c-b676-e2cd33fc13ea.png)
mam weryfikacje konta firmowego i na aukcji nie widać ze jest smart.

**Comment by pzareba86** [comment]
![image](https://user-images.githubusercontent.com/98810516/185383351-5778fcb7-b803-4993-9ef9-71b8ba06f3bc.png)

**Comment by MartaNowaczyk** [comment]
Jeżeli chcesz, aby Twoje oferty były oznaczone jako Smart - konto i oferta musi spełnić [takie same warunki](https://allegro.pl/pomoc/dla-sprzedajacych/informacje-dla-sprzedajacych/co-zrobic-aby-moje-oferty-byly-oznaczone-ikona-allegro-smart-lDkP8VbKncV) jak na środowisku produkcyjnym. Sprawdź czy je spełniasz.
