### ISSUE TITLE
Brakuje sekcji "saleInfo" w requstcie /sale/offers/id-oferty

### ISSUE THREAD

**Issue by mirkosmuz** [allegro/allegro-api#6031]
Występuje problem: < get sale/offers/[ idoferty]>
 - [*] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Request:   GET /sale/offers/id-oferty
do tej pory zwracał sekcje (z samouczka: https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#kliknij-aby-zobaczyc-response):

 "saleInfo": {
                "currentPrice": null,         -- cena zakupu w licytacji
                "biddersCount": 0             -- liczba osób licytujących

W tej chwili tego niema. Nigdzie nie znalazłem informacji o tym że ma to zostać zdjęte.

**Comment by flixus-milan99** [comment]
Też mam taki błąd - pole currentPrice ma wartość null. Proszę o naprawę błędu.

**Comment by maxmax2121** [comment]
So do I

**Comment by MartaNowaczyk** [comment]
@mirkosmuz dane te zwracamy dla listy ofert czyli GET /sale/offers.
@flixus-milan99 @maxmax2121 nie udało mi się powtórzyć błędu. Może są to szkice ofert? Podaj proszę trace-id, gdy nadal widzisz błąd.

**Comment by flixus-milan99** [comment]
> @mirkosmuz dane te zwracamy dla listy ofert czyli GET /sale/offers. @flixus-milan99 @maxmax2121 nie udało mi się powtórzyć błędu. Może są to szkice ofert? Podaj proszę trace-id, gdy nadal widzisz błąd.

trace-id: 49ba05eda26cd08a

w odpowiedzi jest m.in:
"sellingMode": null,
            "saleInfo": {
                "currentPrice": null,
                "biddersCount": 0
            }

**Comment by MartaNowaczyk** [comment]
@flixus-milan99 dzięki, sprawdzamy opisaną sytuację. Damy znać jak coś się wyjaśni.

**Comment by MartaNowaczyk** [comment]
Problem nie powinien już występować. Przepraszamy za niedogodności.

**Comment by flixus-milan99** [comment]
Potwierdzam, struktura sellingMode jest już prawidłowo zwracana
