### ISSUE TITLE
parcel-create-command dla Allegro One Box zwraca "Processing error"

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6036]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Po utworzeniu przesyłki z metodą wysyłki Allegro One Box

Z GET https://api.{environment}/parcel-management/parcel-create-commands/2f4a6eb8-f178-4239-aa95-7607db83f40a

dostaję:

```
{
    "id": "2f4a6eb8-f178-4239-aa95-7607db83f40a",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Processing error",
            "details": null,
            "path": null,
            "userMessage": "Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
        }
    ]
}
```

**Comment by AureliuszBrussy** [comment]
@awawrowicz wskazany pickup.pointId jest obecnie niedostępny. Spróbuj skorzystać z innego. Zespół odpowiedzialny za zasób planuje poprawi ten komunikat błędu, aby wskazywał na rzeczywisty problem.

**Comment by awawrowicz** [comment]
Ale zaraz, przecież ten pickup.pointId został wybrany przez kupującego... Pomijam już fakt, w jaki sposób kupujący mógł wybrać niedostępny pickup.pointId. Jeśli teraz ja jako sprzedający wybiorę inny pickup.pointId, to czy system mi to przyjmie? Czy kupujący zostanie powiadomiony o zmianie? Czy mogę wybrać dowolny inny pickup.pointId nawet jeśli jest w zupełnie innym miejscu kraju? Sorry ale jakoś mi się to nie trzyma kupy.

**Comment by awawrowicz** [comment]
Zmieniłem pickup.pointId na losowo wybrany z listy dostępnych punktów (A004036) i mam dokładnie taki sam komunikat błędu.

**Comment by AureliuszBrussy** [comment]
Pole **pickup.pointId** to pole, w którym zdefiniować możesz punkt nadania paczki, czyli punkt, w którym sprzedawca paczkę wyśle. 

Id punktu odbioru powinieneś przekazać w polu **receiver.pointId**. Punkt może być dowolny - nie musi być koniecznie ten, który wskazał w zamówieniu Kupujący (choć oczywiście musi być obsługiwany w ramach wybranej usługi kurierskiej). Kupujący otrzyma dane punktu odbioru.

Jeżeli chodzi o dalsze błędy z utworzeniem przesyłki - wyjaśniam to z zespołem odpowiedzialnym za usługę. Wrócę do Ciebie z informacją.
