### ISSUE TITLE
Puste sellingMode

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#6037]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Oferty te nie są widoczne w Mój Asortyment.

**Comment by flixus-milan99** [comment]
trace-id: 49ba05eda26cd08a

w odpowiedzi jest m.in:
"sellingMode": null,
"saleInfo": {
"currentPrice": null,
"biddersCount": 0
}
