### ISSUE TITLE
przekazywanie serviceId przy generowaniu przesyłki

### ISSUE THREAD

**Issue by kubaimag** [allegro/allegro-api#6038]
Dzień dobry,
Chcę nadać przesyłkę przez Wysyłam z Allegro, zastanawiam się jak przekazać serviceId do metody PUT /parcel-management/parcel-create-commands/{commandId}]
bazując na id zamówienia i pobierając szczegóły przez https://api.{environment}/order/checkout-forms w sekcji delivery/metod/id
API zwraca id w formacie "1fa56f79-4b6a-4821-a6f2-ca9c16d5c925" a GET /parcel-management/delivery-services zwraca id-ki w innym formacie.
Moje pytanie brzmi jak to powiązać, albo w jaki sposób przekazać do metody createNewParcel id dostawy, którą mogę pobrać bazując na id zamówienia.
Z góry dziękuję za odpowiedź.

**Comment by AureliuszBrussy** [comment]
@kubaimag Id metod pobrane z zamówienia nie jest tym samym, co identyfikator usługi dostawy. Usługa dostawy odpowiada umowom podpisanym (i [dodanym w panelu](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia)) przez sprzedającego lub przez Allegro z firmą przewozową. 

Przesyłki mogą być wysłane zarówno w ramach umowy własnej z danym przewoźnikiem, jaki i umowy Allegro. Odpowiednie metody mogą być powiązane za pomocą nazwy. Sugeruj się tabelą, którą [udostępniamy w poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

**Comment by PiotrTaraszkiewicz** [comment]
Podepnę się pod wątek.
Wskazana tabela nie rozwiewa wszystkich wątpliwości :(
W ramach usług dostępnych w WzA jest: Allegro One UPS, Allegro One Box (One Kurier), Allegro One Punkty (One Kurier)
Jest może sposób aby być pewnym kiedy należy użyć Allegro One UPS a kiedy innej usługi dostawy?

**Comment by AureliuszBrussy** [comment]
Pełne rozróżnienie metod dostawy na serwis:

- Metoda dostawy: Allegro One Punkt
   Serwis: Allegro One (UPS)
- Metoda dostawy: Allegro One Box 
   Serwis: Allegro One (UPS)
- Metoda dostawy: Allegro One Punkt (One Kurier)
   Serwis: Allegro One Punkt (One Kurier) 
- Metoda dostawy: Allegro One Box (One Kurier)
   Serwis: Allegro One Box (One Kurier)
- Metoda dostawy: Allegro One Kurier - dostawa dzisiaj
   Serwis: Allegro One Kurier
- Metoda dostawy: Allegro One Kurier - dostawa jutro
   Serwis: Allegro One Kurier.

**Comment by PiotrTaraszkiewicz** [comment]
Dziękuję za pomoc :)

**Comment by bartoszslx** [comment]
Cześć

Podepnę się pod temat. Proszę o pomoc. Moje id zamówienia to: 3e4b7451-28fe-11ed-a8e8-1156d3588185 i metoda dostawy 'Allegro Paczkomaty InPost'.
Zgodnie z tym co Pan pisze 'Odpowiednie metody mogą być powiązane za pomocą nazwy.' mapowanie powinno odbywać się po nazwie dostawy. Za pomocą zasobu 'parcel-management/delivery-services' pobieram dostępne metody dostaw dla swojego konta sandbox (test_sprzedawca).
Niestety na liście nie ma zasobu o nazwie 'Allegro Paczkomaty InPost'. Proszę po podpowiedź co mi umknęło?
Zauważyłem, że posiadacie fajną metodę extended w której są wszystkie informacje. Gdybym tylko miał do niej dostęp, nie byłoby tematu :)

**Comment by AureliuszBrussy** [comment]
Dla metody dostawy "Allegro Paczkomaty 24/7 InPost" odpowiednia umowa to "Allegro Inpost". 

Umowa Allegro Inpost wymaga jednak dodania [w ustawieniach Wysyłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) ([zakładka w Sandboxie](https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/zamowienia/ustawienia)) umowy własnej i wybrania opcji "Używaj oferty dla sprzedawców Allegro". Dopiero wtedy będzie ona dostępna na [GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation#operation/getAvailableDeliveryServices). 

Jeżeli chcesz mieć dostęp do umowy testowej (dane dostępowe do testowego API ShipX) - skontaktuj się z InPostem.

**Comment by bartoszslx** [comment]
Jest jeden mały problem to co jest w tabelce na stronie "Jak zarządzać przesyłkami przez Wysyłam z Allegro" nie pokrywa mi się z tym co jest w aukcji. 
Nie znalałem tam sposobu dostawy o nazwie "Allegro Paczkomaty InPost". Zamiast tego jest "Allegro Paczkomaty 24/7 InPost".
Jest jakaś różnica między "Allegro Paczkomaty InPost", a "Allegro Paczkomaty 24/7 InPost"?

Na swoim koncie posiadam skonfigurowane dwie umowy Inpost: Inpost umowa nr 1, Inpost umowa nr 2. Obie mają zaznaczone opcje 'Używaj oferty dla sprzedawców Allegro'.
Dla zamówienia o id: 3e4b7451-28fe-11ed-a8e8-1156d3588185,w sekcji delivery otrzymuję następującą odpowiedź: 

```
"method": {
      "id": "2488f7b7-5d1c-4d65-b85c-4cbcf253fd93",
      "name": "Allegro Paczkomaty InPost"
}
```

Zasób "/parcel-management/delivery-services" zwraca następujące wartości: 

```
{
	"id": 9615232,
	"service": "INPOST_PACZKOMAT",
	"name": "Inpost umowa nr 1",
	"owner": "CLIENT",
	"carrierId": "INPOST",
	"additionalServices": {
		"cashOnDelivery": {
			"available": true,
			"expressAvailable": false
		},
		"options": [
			{
				"name": "additionalHandling",
				"description": "Paczka niestandardowa."
			},
			{
				"name": "saturdaySundayDelivery",
				"description": "Dostawa paczek do punktu odbioru w sobotę lub niedzielę. Konieczne jest, aby data nadania przypadała między 20:00 w czwartek, a 13:00 w sobotę."
			}
		]
	}
},
{
	"id": 9615233,
	"service": "INPOST_KURIER",
	"name": "Inpost umowa nr 1",
	"owner": "CLIENT",
	"carrierId": "INPOST",
	"additionalServices": {
		"cashOnDelivery": {
			"available": true,
			"expressAvailable": true
		},
		"options": [
			{
				"name": "returnOfDocuments",
				"description": "Zwróć dokumenty podpisane przez odbiorcę. Po dostawie odbiorca podpisuje dokumenty i zwraca je kurierowi."
			},
			{
				"name": "saturdayDelivery",
				"description": "Dostawa w sobotę."
			},
			{
				"name": "additionalHandling",
				"description": "Paczka niestandardowa."
			},
			{
				"name": "smsPredeliveryInformation",
				"description": "Awizo SMS doręczenia paczki."
			}
		]
	}
},
{
	"id": 9615234,
	"service": "INPOST_PACZKOMAT",
	"name": "Inpost umowa nr 2",
	"owner": "CLIENT",
	"carrierId": "INPOST",
	"additionalServices": {
		"cashOnDelivery": {
			"available": true,
			"expressAvailable": false
		},
		"options": [
			{
				"name": "additionalHandling",
				"description": "Paczka niestandardowa."
			},
			{
				"name": "saturdaySundayDelivery",
				"description": "Dostawa paczek do punktu odbioru w sobotę lub niedzielę. Konieczne jest, aby data nadania przypadała między 20:00 w czwartek, a 13:00 w sobotę."
			}
		]
	}
},
{
	"id": 9615235,
	"service": "INPOST_KURIER",
	"name": "Inpost umowa nr 2",
	"owner": "CLIENT",
	"carrierId": "INPOST",
	"additionalServices": {
		"cashOnDelivery": {
			"available": true,
			"expressAvailable": true
		},
		"options": [
			{
				"name": "returnOfDocuments",
				"description": "Zwróć dokumenty podpisane przez odbiorcę. Po dostawie odbiorca podpisuje dokumenty i zwraca je kurierowi."
			},
			{
				"name": "saturdayDelivery",
				"description": "Dostawa w sobotę."
			},
			{
				"name": "additionalHandling",
				"description": "Paczka niestandardowa."
			},
			{
				"name": "smsPredeliveryInformation",
				"description": "Awizo SMS doręczenia paczki."
			}
		]
	}
}

```		
Chce napisać do tego jakiś automat, który wybierze mi odpowiednie id umowy lub umów na podstawie metody dostawy, w tym wypadku  "Allegro Paczkomaty InPost". Coś mi umyka, ale nie wiem co dlatego proszę o pomoc. Jak tu zrobić powiązania w tym konkretnym przypadku?
Nie chcę pisać rozwiązania typu jeżeli wybrano "Allegro Paczkomaty InPost" to pobierz serwisy które mają w nazwie INPOST_PACZKOMAT, itd. Chyba, że nie ma innej możliwości?

**Comment by AureliuszBrussy** [comment]
@bartoszslx w tym przypadku musiałbyś wybrać jedną z umów INPOST_PACZKOMAT. Nie ma innego sposobu, aby powiązać wybraną metodę dostawy z serwisem.

**Comment by bartoszslx** [comment]
@AureliuszBrussy dziękuje.
