### ISSUE TITLE
Metoda PUT nie działa w C# - UnsupportedMediaType

### ISSUE THREAD

**Issue by mareklemur** [allegro/allegro-api#604]
Witam,

Wywołanie RestClient:
var client = new RestClient("https://api.allegro.pl/offers/7302451880/change-price-commands/0fe541aa-01e6-406f-a619-ba708f59aca4");
var request = new RestRequest(Method.PUT);
request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");
request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
request.AddHeader("Authorization", "Bearer {TOKEN}");
request.AddParameter("application/json", "{\"id\":\"0fe541aa-01e6-406f-a619-ba708f59aca4\",\"input\":{\"buyNowPrice\":{\"amount\":\"199\",\"currency\":\"PLN\"}}}", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);

zwraca:
{"errors":[{"code":"NotSupportedException","message":"An error has occurred","details":null,"path":null,"userMessage":"An error occurred"}]}

Działają mi metody POST i GET, a PUT zwraca status UnsupportedMediaType.

Gdzie szukać przyczyny?

Trace-id: 36a1bd168bd58211

**Comment by KrzysztofLukanowski** [comment]
Cześć,

sprawdziliśmy trace-id, błąd wskazuje, że zawartość content-type była nieprawidłowa. Upewnij się, że przesyłasz `application/vnd.allegro.public.v1+json`.

**Comment by mareklemur** [comment]
Tak jak pisałem powyżej:
request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");
to samo dla GET i POST działa.
Dziwna sprawa.

**Comment by rtnet-pl** [comment]
Podejrzyj sobie Fiddlerem faktyczny request wysyłany do Allegro. Podejrzewam że możesz mieć więcej niż 1 nagłówków content-type.

**Comment by mareklemur** [comment]
Dzięki, faktycznie content-type nie był ustawiany przez AddHeader. Ostatecznie zadziałał poniższy kod:

var client = new RestClient("https://api.allegro.pl/offers/7302451880/change-price-commands/{UUID}");
var request = new RestRequest(Method.PUT);
request.Parameters.Clear();
request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
request.AddHeader("Authorization", "Bearer {token}");
request.AddParameter("application/vnd.allegro.public.v1+json", "{\"id\":\"{UUID}\",\"input\":{\"buyNowPrice\":{\"amount\":\"199\",\"currency\":\"PLN\"}}}", ParameterType.RequestBody);
IRestResponse response = client.Execute(request);

Może komuś pomoże:)
