### ISSUE TITLE
Punch Out catalogue

### ISSUE THREAD

**Issue by Ladi9999** [allegro/allegro-api#6040]
Hello,

I would like to get an IT person to talk regarding collaboration for B2B between Allegro and TE Connectivity in Poland.

We currently use Marketplace called Aquiire/Coupa and would like to integrate your eCat there so our colleagues will be able to shop there.

thanks in advance

**Comment by MartaNowaczyk** [comment]
We provide support for the Allegro API on this forum. When it comes to integrations with our public API, all data can be found in our [documentation](https://developer.allegro.pl/documentation) and our [guides](https://developer.allegro.pl/tutorials/getting-started-with-the-rest-api-0A2x4WaX8iB). If you have questions about our API, feel free to ask.

**Comment by Ladi9999** [comment]
Hello,

I do not understand where to go to,

I need a sales and IT person to talk to.

Kind regards
Ladislav Nezbeda

[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018_telogo.gif]<http://www.te.com/>
Ladislav Nezbeda
Commodity Manager Spares & Supplies EMEA
Corporate Procurement
MOBILE +420 778 451 197  EMAIL ***@***.******@***.***>
[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Facebook-Icon.gif]<https://www.facebook.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Twitter-Icon.gif]<https://twitter.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Instagram-Icon.gif]<http://instagram.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-LinkedIn-Icon.gif]<https://www.linkedin.com/company/te-connectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-YouTube-Icon.gif]<https://www.youtube.com/teconnectivity>
te.com<http://www.te.com/>
Click to read<http://www.te.com/global-en/private/te-email-confidentiality-statement.html> email confidentiality disclaimer.

**Comment by MartaNowaczyk** [comment]
I don't know what you mean. At this forum, we only support our public API and we only support this form of contact. If you have questions about our API, you can ask me here, otherwise contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=bf78f387-8bda-46e1-9ecd-5ffa5016101b&subjectId=0bc27e4d-4963-4626-aba5-3a4f32d5ec4d) describing in detail what you need.

**Comment by Ladi9999** [comment]
I was directed here to send a request for B2B connection.

I really would appreciate to get a sales/IT contact to talk to.

Kind regards
Ladislav Nezbeda

[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018_telogo.gif]<http://www.te.com/>
Ladislav Nezbeda
Commodity Manager Spares & Supplies EMEA
Corporate Procurement
MOBILE +420 778 451 197  EMAIL ***@***.******@***.***>
[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Facebook-Icon.gif]<https://www.facebook.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Twitter-Icon.gif]<https://twitter.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-Instagram-Icon.gif]<http://instagram.com/teconnectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-LinkedIn-Icon.gif]<https://www.linkedin.com/company/te-connectivity>[http://www.te.com/content/dam/te-com/images/corporate/marketing/global/brand-resources/2018-YouTube-Icon.gif]<https://www.youtube.com/teconnectivity>
te.com<http://www.te.com/>
Click to read<http://www.te.com/global-en/private/te-email-confidentiality-statement.html> email confidentiality disclaimer.

**Comment by MartaNowaczyk** [comment]
You have been redirected incorrectly. Unfortunately, I cannot help you in this case. Please return to the earlier conversation to explain the situation.
