### ISSUE TITLE
Trasa do punktu nie jest dostępna następnego dnia

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6041]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
 
Podczas próby utworzenia przesyłki z poziomu GUI dostaję błąd jak na screenie poniżej

![image](https://user-images.githubusercontent.com/28707773/185578929-dae2962f-cdc8-4d85-afd6-c0c5cfd9f5be.png)

Podobny błąd jest zwracany w przypadku API:

`{
    "id": "2f4a6eb8-f178-4239-aa95-9507db83f407",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Route not available for next day - parcelId[13560466], errorId[0HMK1LHB5H3UP:00000033]",
            "details": null,
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage": "Trasa do punktu nie jest dostępna następnego dnia - parcelId[%1$s], errorId[%2$s]"
        }
    ]
}`

**Comment by MartaNowaczyk** [comment]
Konsultuję ten przypadek z zespołem odpowiedzialnym za usługę, także dam znać gdy coś ustalimy.

**Comment by MartaNowaczyk** [comment]
Błąd namierzyliśmy i poprawiliśmy, więc można ponowić request. Zmienimy jeszcze komunikat by był bardziej czytelny. Przepraszamy za niedogodności.
