### ISSUE TITLE
Status zwrotu środków CANCELLED

### ISSUE THREAD

**Issue by ConteMainteiner** [allegro/allegro-api#6042]
Zwrot środków dostaje status CANCELLED według dokumentacji "nie udało się pobrać środków z salda lub wystąpił błąd po stronie operatora". 
Utworzenie ponownie zwrotu do płatności  (POST https://api.allegro.pl/payments/refunds) skutkuje komunikatem:
VALIDATION_ERROR - Oferta: ID_OFERTY ilość przekroczona, dostępna: 0, żądana: 1 Oferta: ID_OFERTY ilość przekroczona, dostępna: 0, żądana: 1
trace-id: 8596768533aadb82
W jaki sposób wykonać ponownie zwrot płatności?

**Comment by AureliuszBrussy** [comment]
Z moich informacji wynika, że zwrot dla tego zamówienia (i tej płatności) został zrealizowany. Czy jesteś w stanie wskazać id zwrotu, dla którego zwracamy status CANCELLED?

**Comment by ConteMainteiner** [comment]
refund id : f9cbdc98-13ec-11ed-823b-efea455d6df8.
Faktycznie jest zrobiony zwrot płatności, widocznie klient zrobił ręcznie przez Allegro. Postaram się znaleźć inny przykład.
