### ISSUE TITLE
Błąd przy próbie wystawienia ofery wraz z utworzeniem produktu w katalogu

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6043]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment

trace-id: 2e05f6f651b51a9

Próba wystawienia oferty produktowej , wraz z próbą utworzenia produktu w katalogu kończy się utworzeniem oferty, z jedonczesnym błędem:  You cannot publish offer without a related product in this category. Select from the catalog or create a new product and associate it with your offer.","details":"ConstraintViolationException.ProductizationMinLimitReached","path":"null","userMessage":"Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą."}]. Obiekt oferty który jest zwracany nie posiada "body" dla  wartości "productSet" tak jakby produkt nie utworzył się w katalogu. Prosił bym o pomoc

**Comment by PrzemyslawLukanowski** [comment]
Jest to znany nam problem, nad którego rozwiązaniem pracujemy. Mianowicie, przyczyną błędu jest wybór [wartości niejednoznacznych](https://developer.allegro.pl/news/kategorie-i-parametry-nowe-pole-ambiguousvalueid-dla-parametrow-z-wartoscia-niejednoznaczna-3Anlee0YXFL) w parametrach "Rozmiar" i "Postać/temat", gdzie dodatkowo nie umożliwiamy przekazania własnej wartości w polu "values".  Poinformuję w wątku, kiedy uda nam się wprowadzić odpowiedną poprawkę. Przepraszam za utrudnienia.

**Comment by Maciej-Wilkosz** [comment]
Czy problem nadal powinien występować?

**Comment by PrzemyslawLukanowski** [comment]
Tak, wciąż pracujemy nad rozwiązaniem. Poinformuję w wątku, kiedy uda się wyeliminować problem.

**Comment by PrzemyslawLukanowski** [comment]
@Maciej-Wilkosz Wprowadziliśmy odpowiednią poprawkę - obecnie będziemy próbowali utworzyć produkt, ewentualnie zwrócimy informację o tym, że nie można utworzyć produktu, ze względu na to, że nie jest możliwe ustawienie parametru z wartością inny.
