### ISSUE TITLE
Problem z autoryzacją

### ISSUE THREAD

**Issue by DesignCart** [allegro/allegro-api#6044]
Witam Was 

Próbuję przeprowadzić autoryzację w Waszym REST API i w zwrotce otrzymuję:
Secure {"error":"Unauthorized","error_description":"Unauthorized"}

Kod:
$client_id     = $this->request->post['module_dc_allegro_client_id'];
$client_secret = $this->request->post['module_dc_allegro_client_secret'];
			
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://allegro.pl/auth/oauth/token?grant_type=client_credentials");
curl_setopt($ch, CURLOPT_HEADER, array('Authorization: Basic '.base64_encode($client_id.':'.$client_secret)));
$output = curl_exec($ch);
curl_close($ch);

Mogę prosić o pomoc?

Moje drugie pytanie czy konta sandbox autoryzuje się na jakimś innym adresie niż https://allegro.pl/auth/oauth/token?grant_type=client_credentials?

Niemniej error w autoryzacji jest i z  danymi client_id, client_secret pochodzącymi z konta sandbox jak i z konta normalnego

**Comment by Lukasz-Zurek** [comment]
Do dokładnej weryfikacji przydatny będzie pełny request w formacie json. Prawdopodobnie problem leży po stronie kodowania base64, które nie funkcjonuje prawidłowo.

Jeśli chodzi o Twoje drugie pytanie - tak, w przypadku środowiska testowego Sandbox musisz używać innego adresu: https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials

Różnice między produkcyjnym a testowym REST API przedstawiliśmy [tutaj](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe).

**Comment by DesignCart** [comment]
Ale to funkcja php base64_encode(): https://www.php.net/manual/en/function.base64-encode.php - jak może działać nieprawidłowo?
Nie wysyłam jeszcze żadnego requestu. Tak po prostu napisałem kodzik by otrzymać choćby access_token :)

**Comment by Lukasz-Zurek** [comment]
@DesignCart Rozumiem. Błąd "Unauthorized" może jednak wskazywać na nieprawidłową wartość w kodowanych danych `client_id:client_secret` (należy zwrócić uwagę na to, aby całość danych wraz ze znakiem “:” pomiędzy wartościami - była kodowana).

**Comment by Lukasz-Zurek** [comment]
Wspomniany localhost nie powinien mieć na to wpływu.

Nie mając jednak szczegółowych danych trudno będzie mi się odnieść do problemu. Skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a) i przekaż szczegóły. Dodatkowo dzięki temu będę mógł sprawdzić nasze logi.

**Comment by DarkStoorM** [comment]
@DesignCart możesz również wypróbować [bibliotekę do RESTa od Wiatrogona](https://github.com/Wiatrogon/php-allegro-rest-api) lub jej pochodne. Autoryzacja z tym jest prosta, a rozwijanie aplikacji z tym nie sprawiało mi żadnych problemów, korzystam z tego praktycznie od samego początku. Repo może i ma z 6 lat, ale z PHP 8.1 nadal działa, nawet cURLem nie musisz się bawić. Wystarczy jedynie URLe w bibliotece sprawdzić w `API.php` i `Sandbox.php` i lecieć z dokumentacją RESTa.

Jest już pewnie od groma gotowych bibliotek, ja akurat korzystam z tej razem z Laravel. Możesz ją przez Composera pobrać

```
composer require wiatrogon/allegro-rest-api
```
