### ISSUE TITLE
Problem z Dodaniem Oferty W AllergroSandbox Przez Aplikacje

### ISSUE THREAD

**Issue by Zuczekk** [allegro/allegro-api#6045]
Witam, nwm czy robie coś źle, ale próbóje dodać oferte testową na allegro sandbox. Konto na email albert123124@gmail.com. Podczas próby wystawienia oferty przenosi mnie na allegro lokalni  i wyrzuca mi błąd. Czy istnieje możliwość dodania oferty przez aplikacje czy trzeba to robić przez zasoby API ?  Jeśli to też nie problem to proszę o aktywacja konta na allegro sandbox na emailu który podałem wcześniej.

**Comment by Lukasz-Zurek** [comment]
Twoje konto nie było w pełni aktywne. Aktywowałem je. Pamiętaj jednak, aby móc wystawiać oferty - zarówno bezpośrednio na stronie, jak i przez zasoby naszego API - musisz przekształcić konto zwykłe w firmowe. W tym celu przejdź do [tej](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) zakładki, przekształć konto na firmowe i uzupełnij wszystkie wymagane dane przedsiębiorstwa.

**Comment by Zuczekk** [comment]
Kiedy próboje dodać oferte dalej dostaje błąd: 
POST | https://edge.allegro.pl.allegrosandbox.pl/sale/offers
{
	"errors": [
		{
			"code": "VALIDATION_ERROR",
			"message": "To activate sales please verify your account.",
			"details": "ConstraintViolationException.SellerAccountVerified",
			"path": "seller",
			"userMessage": "Aby aktywować sprzedaż zweryfikuj konto."
		}
	]
}
Email konta: albert123124@gmail.com
![image](https://user-images.githubusercontent.com/67339989/185910136-060334a1-df58-4ce4-98b0-bdf6a3775759.png)
Mam też taką informacje na koncie. 
Plus jak próboje to aktywowac dostaje taki błąd.
{
	"errors": [
		{
			"code": "IllegalActionForOnboardingInState",
			"message": "Illegal action for onboarding in state: STARTED",
			"details": null,
			"path": "/company-onboarding/commands/resumptions",
			"userMessage": null
		}
	]
}

**Comment by Zuczekk** [comment]
{
	"errors": [
		{
			"code": "VALIDATION_ERROR",
			"message": "To activate sales please verify your account.",
			"details": "ConstraintViolationException.SellerAccountVerified",
			"path": "seller",
			"userMessage": "Aby aktywować sprzedaż zweryfikuj konto."
		}
	]
}

Dalej dostaje taki problem przy próbie wystawienia oferty, konto mam firmowe.

**Comment by Lukasz-Zurek** [comment]
@Zuczekk Zweryfikowałem Twoje konto firmowe. Powinno być już ok.

**Comment by applejablko** [comment]
czy mogę aktywować konto testowe ? "applejablko" wykonałem przelew testowy ale nie mogę dodawać ofert :(

**Comment by Lukasz-Zurek** [comment]
@applejablko Aktywowałem Twoje konto, włącznie z weryfikacją firmy.

**Comment by mrsuchy** [comment]
Czy mogę prosić o weryfikację konta psogt85? Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
@mrsuchy Konto jest już w pełni zweryfikowane.

**Comment by mrsuchy** [comment]
Potwierdzam. Dziękuje.
