### ISSUE TITLE
Punkt odbiorcy jest niepoprawny

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6047]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Przy próbie utworzenia przesyłki dla Inpost Paczkomaty mam błąd jak na załączonym screenie. Paczkomat został wybrany przez kupującego za pomocą widgetu więc pointId powinien być poprawny.
![image](https://user-images.githubusercontent.com/28707773/185934317-0efa9f51-5dee-469f-9216-9eeff2e21d3d.png)

Błąd zwracany przez API:
`{
    "id": "2f4a6eb8-f178-4239-aa95-9507db83f415",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Receiver point is incorrect",
            "details": null,
            "path": "receiver.pointId",
            "userMessage": "Punkt odbiorcy jest niepoprawny"
        }
    ]
}`

**Comment by Lukasz-Zurek** [comment]
Na środowisku testowym przewoźnicy ograniczają się do znacznie zmniejszonej puli dostępnych punktów, dlatego może dojść do tego typu sytuacji, w której wybrany punkt jest nieprawidłowy, ponieważ nie jest on dostępny. Proszę o wyrozumiałość.

**Comment by awawrowicz** [comment]
Czy można zatem prosić o listę dostępnych punktów w środowisku testowym? Wydawało mi się, że jeśli punkt został wybrany przez kupującego w środowisku testowym, to powinien być poprawny w tym środowisku.

**Comment by Lukasz-Zurek** [comment]
@awawrowicz Temat dodatkowo konsultowałem i nie mamy niestety takiej listy. Spróbuj z tym punktem: `KIE100`.
