### ISSUE TITLE
Ten sam identyfikator parametru w różnych kategoriach

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6048]
Czy mamy gwarancję, że identyfikator parametru jednoznacznie określa parametr niezależnie od tego w której kategorii się on znajduje? Czyli jeśli np. w kategorii 66784 i w kategorii 66785 jest parametr 223541 to parametr 223541 będzie dokładnie tak samo zdefiniowany w obu kategoriach?

Niektóre parametry słownikowe mają po kilka tysięcy pozycji - chcę takie parametry słownikowe zaczytywać tylko raz niezależnie od kategorii w której występują.

**Comment by hahyes** [comment]
@tomylee0 Nie, nie masz takiej gwarancji. Parametry o tych samych nazwach mogą mieć różne identyfikatory. Parametry o tych samych identyfikatorach mogą mieć różne ograniczenia i opcje w zależności od kategorii. "Zaczytywanie" tylko raz niezależnie od kategorii będzie po prostu złym pomysłem.

**Comment by Lukasz-Zurek** [comment]
@tomylee0 Dokładnie tak jak już wspomniał **hahyes** - nie masz takiej gwarancji, a przykładem może być choćby parametr "Producent", który występuje w wielu różnych kategoriach, np. Motoryzacja, Elektronika czy Dom i Ogród. W każdej z kategorii parametr ten posiada odrębną listę słownikową.

**Comment by tomylee0** [comment]
Dzięki za odpowiedź. Jeśli chodzi o parameter.name to OK - to rozumiem. Trochę zaskoczyła mnie jednak informacja odnośnie parameter.id. Jeszcze fakt, że może być ten sam parameter.id ale inne ograniczenia lub opcje wydaje się zrozumiały. Mnie najbardziej interesuje parametr typu "dictionary" a dokładniej mapowanie dictionary.id na dictionary.value dlatego dopytam na wszelki wypadek konkretniej.

Czy to znaczy, że np. parameter.id = 223541 który pojawia się w każdej kategorii książkowej może mieć inne "dictionary" w środku w zależności od kategorii? 
1. Czyli, że w jednej kategorii wydawnictwo "100 Procent" może mieć dictionary.id = 223541_834637 a w innej kategorii wydawnictwo "100 Procent" może mieć np. dictionary.id = 223541_123456?
2. Czyli, że w jednej kategorii może być więcej wydawnictw a w innej mniej mimo, że cały czas jest to ten sam parameter.id = 223541?


_{ "parameters": [ {
    ...
    { "id": "223541", "name": "Wydawnictwo",
       ...
       "dictionary": [ { "id": "223541_834637", "value": "100 Procent", "dependsOnValueIds": [] }, {
...
}_

**Comment by Lukasz-Zurek** [comment]
Jak wspomniałem powyżej - nie ma gwarancji, co nie oznacza, że tak jest dla wszystkich parametrów.

Parametr "223541_834637" (Wydawnictwo) w każdej kategorii książkowej ma identyczną listę słownikową.

1. Opierając się na tym konkretnym parametrze - nie, dictionary.id dla "100 Procent" = 223541_834637 i jest jednakowe również w innych podkategoriach książkowych, podobnie jak pozostałe wartości słownikowe w tym parametrze.
2. Patrz pkt 1.

Różnice są w kategoriach, które się od siebie znacząco różnią, np. Motoryzacja, Dom i Ogród. Nie dodawaliśmy tutaj wspólnej listy słownikowej producentów, bo byłoby to nielogiczne, kłopotliwe i niewygodne dla Kupujących, którzy w gąszczu producentów chcieliby odnaleźć konkretną markę kosiarki.

**Comment by hahyes** [comment]
@tomylee0 
> Czy to znaczy, że np. parameter.id = 223541 który pojawia się w każdej kategorii książkowej może mieć inne "dictionary" w środku w zależności od kategorii?

Tak, może mieć. Chociaż możliwe, że w książkach nie jest to tak różnorodne.
Ale na przykład w takiej Modzie to pomiędzy bluzkami i biustonoszami chociażby marki będą zupełnie inne.

> Czyli, że w jednej kategorii wydawnictwo "100 Procent" może mieć dictionary.id = 223541_834637 a w innej kategorii wydawnictwo "100 Procent" może mieć np. dictionary.id = 223541_123456?

Zależy od różnic pomiędzy kategoriami. Jeżeli przeskakujemy np. z książek do komiksów to pewnie wydawnictwa będą inne. Pomiędzy podkategoriami książek możliwe, że te parametry będą spójne. Jednak Allegro nie gwarantuje, że tak jest. Allegro wręcz zaleca, żeby trzymać dla każdej kategorii osobny zbiór parametrów i dla tych parametrów zbiory słownikowe. 

> Czyli, że w jednej kategorii może być więcej wydawnictw a w innej mniej mimo, że cały czas jest to ten sam parameter.id = 223541?

Tak. Dokładnie taka sytuacja może wystąpić. Dla różnych kategorii może być dostępny np. parametr Stan o różnych zbiorach słownikowych wartości. Niektóre ograniczają się do Nowy/Używany, w innych opcje są dużo bardziej szerokie. 

Generalnie możemy w teorii założyć, że bliskie sobie kategorie dzielą ten sam zbiór parametrów.

**Comment by tomylee0** [comment]
Dziękuję Wam bardzo za pomoc. I pozdrawiam.
