### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by JurekAndrzejewski** [allegro/allegro-api#6049]
Hej, mam problem z updatowaniem ceny, stocku i aktywacji szkicu oferty.
Wystawiam produkt używając zasobu Create offer based on product. potem [chciałbym go zupdatować używając zasobu Complete a draft offer or edit an offer](https://pastebin.com/c9AS909y), lecz dostaję [zwrotkę "Invalid request."](https://pastebin.com/idRiW8Vb)

EDIT: [Zupdatowałem parametry ](https://pastebin.com/nG0T6PFD) - nic się nie zmieniło

**Comment by hahyes** [comment]
Korzystasz ze złego zasobu. Wystawiając za pomocą /sale/product-offers nie możesz edytować poprzez /sale/offers. To tak jakby inny rodzaj oferty, którego ten zasób nie obsługuje.

Poszukujesz tego zasobu: https://developer.allegro.pl/documentation#operation/editProductOffers

**Comment by Lukasz-Zurek** [comment]
@JurekAndrzejewski Zgodnie z sugestią od **hahyes** - rekomendujemy korzystanie z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers). O edycji za pośrednictwem wspomnianego zasobu przeczytasz w naszym [poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pol-oferty).

**Comment by JurekAndrzejewski** [comment]
Hej, faktycznie - mój błąd. Dzięki za poświęcony czas.
