### ISSUE TITLE
Metoda na pobieranie kosztów allegro https://allegro.pl/billinghistory/#/history

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#605]
Potrzebuje pobrać zestawienie w CSV przez API.
zamów zestawienie za:
ostatnie 3 miesiące
wszystkie transakcje

aktualnie klikam to ręcznie co jakiś czas, i ręcznie ładuję do naszego systemu. Chciałbym jednak, żeby te statystyki pobierać codziennie w nocy za pomocą API allegro. Wtedy będziemy mieć aktualny podgląd na koszty. Będę wdzięczny za wskazanie metod, którymi da rade to ogarnąć dział IT w mojej firmie.   Bo podobno się nie da.

**Comment by KrzysztofLukanowski** [comment]
Aktualnie nie udostępniamy takiej opcji w API.

**Comment by TimothyKoval** [comment]
1. Pobierz dziennik transakcji (Web API [doGetSiteJournalDeals](https://allegro.pl/webapi/documentation.php/show/id,742))
2. Pobierz informacje o aukcji z dealEventType == 1 - utworzenie aktu zakupowego, wtedy naliczana jest prowizja (Web API [doGetItemFields](https://allegro.pl/webapi/documentation.php/show/id,842) lub REST API [/sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/getOfferUsingGET))
3. Na podstawie otrzymanych danych pobierz informacje o opłatach dla aukcji o podobnych parametrach (REST API [/pricing/fee-preview](https://developer.allegro.pl/documentation/#/pricing/previewFeesPublicAPIUsingPOST))

Tak, jest to do dupy, tak, może w 100% nie pokrywać się z rzeczywistością, ale nic innego nie wymyślisz.

**Comment by centrumelektroniki** [comment]
Dzięki za odpowiedź!
