### ISSUE TITLE
parcel label.fileFormat ZPL

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6050]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Po utworzeniu przesyłki przez API z label.FileFormat: "ZPL" endpoint GET /parcel-management/parcels/{parcelId} zwraca label.fileFormat: "PDF"

Endpoint parcel-management/parcels/label?parcelId={parcelId} również oczekuje paramteru ACCEPT w header odpowiedniego dla PDF

kod utworzenia przesyłki: 2f4a6eb8-f178-4239-aa95-9507db83f417
id utworzonej przesyłki: 13574269

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowe dane. Przekazałem już temat do odpowiedniego zespołu, w celu dalszej weryfikacji. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@awawrowicz W przypadku, gdy korzystasz z GET /parcel-management/parcels/{parcelId} powinniśmy zwrócić Ci w tej sytuacji format ZPL, natomiast na Sandboxie zwracamy PDF. Jest to błąd po naszej stronie. Przepraszamy za te utrudnienia. Postaramy się to usprawnić. Niemniej jednak nie powinieneś mieć problemu z pobraniem etykiety. Sprawdzaliśmy to np. za pomocą GET /parcel-management/parcels/label?parcelId={id}&pageFormat=A6 i generuje się poprawny plik ZPL. Spróbuj proszę ponownie.
