### ISSUE TITLE
Niejasny błąd "Provided image address is incorrect"

### ISSUE THREAD

**Issue by Maciej-Wilkosz** [allegro/allegro-api#6051]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

trace-id: 7bcbab15e638d003

Próba aktualizacji oferty produktowej kończy się błedem "Provided image address is incorrect". Wszystkie podane obrazki w requescie sprawdzałem i istnieją po stronie allegro. Co taki błąd tak naprawdę oznacza w tym wypadku i jak go rozwiązać? Dziękuję z góry za pomoc

**Comment by Lukasz-Zurek** [comment]
Problem przekazałem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
Przepraszam za długi czas oczekiwania na odpowiedź.

Wszystko wskazuje na to, że był to tymczasowy problem związany z naszą usługą odpowiedzialną za zdjęcia. Przepraszamy za zaistniałe utrudnienia.

**Comment by Maciej-Wilkosz** [comment]
trace-id: 21aa1cad73953e8

Problem nadal występuje, podaje nowe traceId

**Comment by Lukasz-Zurek** [comment]
Dziękuję, przekazałem do weryfikacji.

**Comment by Maciej-Wilkosz** [comment]
Czy udało się coś ustalić?

**Comment by MaciejFrackowiak** [comment]
@Maciej-Wilkosz Czekamy wciąż na wynik weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Dwa z trzech zdjęć przekazywanych w żądaniu tj.

https://a.allegroimg.com/original/11b592/4adfdab64569b0ca9c869d21d39a
https://a.allegroimg.com/original/1182b6/276337344cb5bf293ecbb820457e

nie były wcześniej dodane do oferty, dlatego w dniu 25.08 zostały przez nas usunięte (upłynął ich termin ważności). 

Problem dotyczący trzeciego zdjęcia czyli:

https://a.allegroimg.com/original/11d4bb/3183c2f649c3a73e881293b9c0b3

był po naszej stronie, za co serdecznie przepraszamy.

Jeżeli problem ze zdjęciami występuje u Ciebie cyklicznie - daj proszę znać. Zależy nam na tym, aby sytuacja nie powtarzała się w przyszłości.

**Comment by Maciej-Wilkosz** [comment]
Oferta nadal nie chce się zaaktualizować - ten sam błąd

Zaaktualizowałem podane pierwsze dwa zdjęcia. Dodatkowo aby mieć pewność usunąłem podane trzecie które sprawiało problemy. Niestety nic to nie dało. Ponownie zweryfikowałem, i na ten moment wszystkie zdjęcia które przesyłam istnieją na allegro

trace-id: 5328bcf0f17625e6

**Comment by Lukasz-Zurek** [comment]
Dziękuję, ponownie przekazałem do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Kiedy przesyłałeś zdjęcia na nasze serwery? Pytam ponieważ z logów wynika, że zdjęcia uploadowane były ponad tydzień temu, co oznacza, że termin ich ważności już upłynął.

**Comment by Maciej-Wilkosz** [comment]
Jeśli chodzi o poprzednie trace-ids to już nie aktualne, ofertę udało mi się faktycznie zaaktualizować przepychając wszystkie zdjęcia na nowo. Natomiast napotkałem identyczny problem, próbując wystawić ofertę. Błąd z API identyczny, zdjęcia wg. mnie istnieją - przeklikałem każde. Mimo to oferty nie udaje się wystawić

trace-id: 5a486fdf8b780998

**Comment by Lukasz-Zurek** [comment]
@Maciej-Wilkosz Sprawę przekazuję do ponownej weryfikacji.

**Comment by Maciej-Wilkosz** [comment]
Podbijam

**Comment by Lukasz-Zurek** [comment]
Wszystkim zdjęciom przekazywanym podczas aktualizacji oferty - minął tzw. TTL (czyli upłynął termin ważności). Dokładnie nastąpiło to 11.09 ok godziny 2:38.

Fakt iż zdjęcia są widoczne po kliknięciu w link nie oznacza, że zdjęcie może być wykorzystane w ofercie. Jeśli upłynął termin ważności zdjęcia - zwrócimy błąd i nie będziesz mógł z niego skorzystać. Dlatego najlepiej będzie jak zweryfikujesz cały proces po swojej stronie. Po stronie naszego API nie odnotowaliśmy błędów. Cały czas zwracamy prawidłowy komunikat.

**Comment by Maciej-Wilkosz** [comment]
Czy jest szansa ,że w przyszłości ten błąd będzie wskazywał na zdjęcie które było problemem? Proces zweryfikowałem po swojej stornie i faktycznie to błąd u mnie. Dzięki

**Comment by Lukasz-Zurek** [comment]
Zależy nam na precyzyjnych komunikatach błędów w naszym API, dlatego na bieżąco zgłaszamy tego typu nieprawidłowości do odpowiednich zespołów. Jeśli chodzi o Twój przypadek ze zdjęciami - również poruszę ten temat.
