### ISSUE TITLE
ProductSetMinSizeExceeded - Zestaw produktów musi składać się z minimum 1 produktu. 

### ISSUE THREAD

**Issue by promsters** [allegro/allegro-api#6052]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**
Błąd pojawia się dla aukcji opon samochodowych podczas aktualizacji ilości sztuk/ceny/publikacji poprzez batch modification.

Przykładowy request command'a:
```
curl --request PUT \
  --url https://api.allegro.pl/sale/offer-quantity-change-commands/2df84618-cf00-4071-9ff0-187e52bf5d90 \
  --header 'Accept:  application/vnd.allegro.public.v1+json' \
  --header 'Authorization: Bearer xxxx' \
  --header 'Content-Type:  application/vnd.allegro.public.v1+json' \
  --data '{
	"modification": {
		"changeType": "FIXED",
		"value": 4
	},
	"offerCriteria": [
		{
			"offers": [
				{
					"id": "12093883136"
				}
			],
			"type": "CONTAINS_OFFERS"
		}
	]
}'
```

trace-id
`fa099dc8a110f471`

Request command status:
```
curl --request GET \
  --url https://api.allegro.pl/sale/offer-quantity-change-commands/2df84618-cf00-4071-9ff0-187e52bf5d90/tasks \
  --header 'Accept:  application/vnd.allegro.public.v1+json' \
  --header 'Authorization: Bearer xxxxx'
```

Response:
```
HTTP/2 200 
expires: 0
cache-control: no-cache, no-store, max-age=0, must-revalidate
x-xss-protection: 1; mode=block
pragma: no-cache
x-frame-options: DENY
trace-id: 243f788d0c3d5273
date: Tue, 23 Aug 2022 20:56:49 GMT
x-content-type-options: nosniff
content-type: application/vnd.allegro.public.v1+json

{"tasks":[{"offer":{"id":"12093883136"},"message":"EXCEPTION_DURING_OFFER_QUANTITY_UPDATE","status":"FAIL","scheduledAt":"2022-08-23T19:53:08.974Z","finishedAt":"2022-08-23T19:53:08.925Z","field":"quantity","errors":[{"code":"ProductSetMinSizeExceeded","message":null,"details":null,"path":"products","userMessage":"Zestaw produktów musi składać się z minimum 1 produktu."}]}]}
```

trace-id:
`243f788d0c3d5273`

Problem nie dotyczy wszystkich aukcji, pojawia się raczej losowo. Dodatkowo problem pojawił się w momencie gdy w kategorii opony weszło określanie ilości sztuk produktu w zestawie.

Poprzez request PATCH:
`https://api.allegro.pl/sale/product-offers/12093881151`

można bez problemu zaktualizować ilość sztuk w ofercie.

**Comment by Lukasz-Zurek** [comment]
Dziękuję za szczegółowe opisanie problemu. Sprawę konsultuję. Proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@promsters To błąd po naszej stronie. Pracujemy nad poprawką.

Przepraszamy za utrudnienia.

**Comment by promsters** [comment]
Super, że udało się namierzyć problem. Czekamy na poprawkę :)

**Comment by promsters** [comment]
Czy mamy już jakiś update w tej kwestii? Nie ukrywam, że te błąd sprawia sporo problemów :)

**Comment by Lukasz-Zurek** [comment]
@promsters Według posiadanych przeze mnie informacji wynika, że trwają już prace naprawcze. Nie jestem jednak w stanie zadeklarować konkretnego terminu, w którym zostaną one zakończone. Bardzo proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@promsters Problem polegał na tym, że w ofercie był wcześniej zestaw produktowy, który wskutek naszego błędu - został usunięty. Przywróciliśmy go we wskazanej ofercie i komunikat błędu nie powinien już się pojawiać podczas np. aktualizacji.

Jeżeli masz jeszcze inne problematyczne oferty, w których otrzymujesz wspomniany komunikat błędu - wskaż ich numery w tym wątku.

Przepraszamy za zaistniałe utrudnienia.

**Comment by promsters** [comment]
Czy jesteśmy w stanie sami przez api przywracać ten zestaw produktowy?

Kilka innych przykładowych aukcji:
11627705317
11374990279
11374987201
11828064051

**Comment by Lukasz-Zurek** [comment]
> Czy jesteśmy w stanie sami przez api przywracać ten zestaw produktowy?

Niestety nie.
> 
> Kilka innych przykładowych aukcji: 11627705317 11374990279 11374987201 11828064051

Przekazałem je dalej. Wkrótce wrócę z informacją.

**Comment by promsters** [comment]
Nadal pojawiają nam się sporadycznie aukcje z tym błędem. Pytanie czy nie ma możliwości poprawienia po waszej stronie wszystkich aukcji na których występuje ten problem?

Jeśli nie to zaczniemy zapisywać wszystkie numery aukcji z tym problemem i raz na jakiś czas podeślemy listę.

**Comment by Lukasz-Zurek** [comment]
@promsters Przepraszamy Cię za te utrudnienia. Wcześniejsze przypadki poprawiliśmy.

Natomiast sprawę dotyczącą wdrożenia poprawki dla wszystkich problematycznych ofert na danym koncie, konsultuję z odpowiednim zespołem. Wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@promsters Podaj proszę numery kolejnych problematycznych ofert. Chcemy je przeanalizować.

**Comment by promsters** [comment]
Podaje kilka kolejnych przykładów z dzisiaj:
`11374987887
11670120438
12138975636
12138943218
11853944819
`

Czy może to wynikać z tego, że wykorzystujemy obu metod do aktualizacji oferty?
PATCH /sale/product-offers/{offerId}
PUT /sale/offers/{offerId}

**Comment by Lukasz-Zurek** [comment]
> Podaje kilka kolejnych przykładów z dzisiaj:
> 
> ```
> 11374987887
> 11670120438
> 12138975636
> 12138943218
> 11853944819
> ```

Dziękuję.

> Czy może to wynikać z tego, że wykorzystujemy obie poniższe metody do aktualizacji oferty?
> 
> ```
> PATCH /sale/product-offers/{offerId}
> PUT /sale/offers/{offerId}
> ```

Nie wykluczamy takiej możliwości. Nadal jednak badamy przyczynę.

**Comment by Lukasz-Zurek** [comment]
@promsters Przyczyna leżała gdzie indziej. Generalnie oferty utraciły wcześniej dodane zestawy produktowe natomiast podczas aktualizacji ofert zwracaliśmy błędy. Naprawiliśmy większość Twoich ofert na koncie, prócz 12492973325 i 12492973728, które również są problematyczne. Musisz je poprawić samodzielnie tzn. ponownie utworzyć dla nich zestaw produktów.

Raz jeszcze przepraszamy za zaistniałe utrudnienia.

**Comment by promsters** [comment]
W porządku, ponownie zmapujemy produkt dla podanych aukcji.
Mam jeszcze pytanie czy te oferty naprawiliście tylko w obrębie tego jednego konta czy wszystkich kont pod naszym NIPem?

**Comment by Lukasz-Zurek** [comment]
Oferty naprawiliśmy w obrębie konta (uid: 63913176), którego dotyczy to zgłoszenie.
