### ISSUE TITLE
Za szybko wygasający token

### ISSUE THREAD

**Issue by JurekAndrzejewski** [allegro/allegro-api#6053]
Hej, Chciałbym się dowiedzieć jak to jest możliwe, że token wygenerowany o 9:58 https://pastebin.com/nRtuin4N wygasa już o 10:02 https://pastebin.com/td1kzqEx? Oczywiście tokeny poukrywałem, gdyż nie chciałbym się nimi dzielić ze wszystkimi, ale w obydwu przypadkach access_token jest taki sam. Jeśli jest taka potrzeba mogę podrzucić dokładne błędy wraz z tokenami gdzieś prywatnie.

**Comment by Lukasz-Zurek** [comment]
Token może utracić ważność w sytuacji:

- wylogowania się ze wszystkich urządzeń, np. poprzez zakładkę [Logowanie i hasło](https://allegro.pl/moje-allegro/moje-konto/logowanie-i-haslo),
- zmiany hasła,
- zmiany adresu e-mail,
- blokady sprzedaży,
- w wyniku przekroczenia liczby aktywnych sesji (max. 20 otwartych sesji dla jednego użytkownika).

Upewnij się czy nie doszło do jednej z powyższych sytuacji. Jeśli nie - prześlij nam proszę szczegóły za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by JurekAndrzejewski** [comment]
Dzięki, skontaktuję się w formularzu.

**Comment by Lukasz-Zurek** [comment]
@JurekAndrzejewski W zgłoszeniu dopisz proszę GitHub[ #6053](https://github.com/allegro/allegro-api/issues/6053).

**Comment by JurekAndrzejewski** [comment]
Ticket już napisałem, ale zawarłem w nim zdanie "Dzień dobry, jest to kontynuacja wątku https://github.com/allegro/allegro-api/issues/6053"

> @JurekAndrzejewski W zgłoszeniu dopisz proszę GitHub[ #6053](https://github.com/allegro/allegro-api/issues/6053).

**Comment by Lukasz-Zurek** [comment]
@JurekAndrzejewski Dziękuję raz jeszcze za przesłaną wiadomość. Z naszych logów wynika, że zbyt często odświeżasz tokeny. Pamiętaj, że gdy tworzysz nową parę - access token (ważny kolejne 12h ) oraz refresh token (ważny kolejne 3 miesiące) - dotychczasowe stają się nieważne i nie możesz już ich użyć odpytując zasoby naszego API.

Szczegóły przekazałem we wiadomości, którą wkrótce powinieneś otrzymać.
