### ISSUE TITLE
Produktyzacja - połączenie istniejącej oferty z produktem, a konieczność zmiany kategorii

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#6055]
Dzień dobry. W migracji naszych systemów do Państwa nowej polityki produktyzacyjnej odbijamy się od kolejnej ściany. Proszę o wyjaśnienie kwestii.

Posiadamy wiele ofert wystawionych we wcześniejszym czasie, które nie są połączone z produktem, wybraliśmy dla nich odpowiednie `product.id` z Państwa katalogu, jednakże często ten produkt posiada inną kategorię niż nasza istniejąca oferta, zbiór `category.similar` również nie zawiera kategorii obecnej oferty, ale żeby nie było, oferty o których mowa umieszczone są w kategoriach oddających rzeczywiste przeznaczenie oferowanego artykułu.

Próba takiej aktualizacji kończy się oczywiście błędem, że kategoria oferty nie zgadza się z produktem.

Chcielibyśmy zachować nasze istniejące oferty. Co w takim wypadku?

- Próbować tworzyć kolejny produkt (de facto taki sam), ale w pasującej nam kategorii?
- Niestety kasować nasze istniejące oferty i wystawiać je na nowo w innej kategorii, ale z przypisanym produktem?
- A może jakieś inne rozwiązanie? Może planujecie Państwo wdrożenie do tego jakiegoś kompromisowego rozwiązania?

Dodam, że raczej nie będziemy zajmować się zgłaszaniem poprawek do produktów gdyż z reguły je Państwo odrzucacie - przykład: Jakiś czas temu zgłosiliśmy poprawkę dla sprawdzenia jak to działa, że produkt "Płytka zaworowa X" powinien być przypisany do kategorii "Płytki zaworowe", a był w kategorii "Zawory". Nasza propozycja została po 1,5 dnia odrzucona.

**Comment by MartaNowaczyk** [comment]
Dzień dobry, przy próbie tworzenia nowego produktu, jeśli na podstawie parametrów identyfikujących np. EAN czy kod producenta, znajdziemy już taki produkt, dostaniecie zwrotkę z id produktu, który powinien być podpięty. W takim wypadku i tak pozostaje wystawienie oferty w kategorii produktu lub jego kategorii podobnej. 
Jeśli zgłaszacie błąd kategorii produktu, to w informacjach dodatkowych dodajcie argumenty dla zmiany kategorii lub dodania kategorii podobnej.  
Jeśli wdrożymy jakieś "kompromisowe rozwiązanie" na pewno dodamy odpowiedni komunikat.
