### ISSUE TITLE
Błąd walidacji EAN podczas aktywacji oferty

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#6056]
Witam,
Zauważyłem niespójność/błąd w procesie walidacji oferty.
Przykładem jest oferta 12451255761. 
Jej edycja nie zwraca błędów walidacji (PUT na zasobie sale/offers/{offerId}), ale nie można jej aktywować ponieważ zwracany jest błąd:
Incorrect value of the EAN/ISBN/ISSN (245669) parameter for the offered product. The correct parameter value for the product is: \"9788306015775\"
Jeżeli zachowanie jest celowe, to wymusza to na użytkowniku pobranie produktu i walidację tego parametru po swojej stronie. 

Takich aukcji mam kilkadziesiąt (nie tylko EAN, również auto, tytuł itd) co może wskazywać na problem z walidacją po Waszej stronie (inne przykłady 12451298695, 12451333345, 12451267625, 12462923869, 12451304371

Przy okazji zapytam: czy (i ewentualnie gdzie) w dokumentacji znajdę wszystkie formaty komunikatów o błędach walidacji?

**Comment by MartaNowaczyk** [comment]
Sprawdziłam na tych danych oferty i przy każdym PUT dostaję informację, że mam niezgodny EAN/ISBN/ISSN z produktem. Możesz podesłać trace-id w którym nie otrzymałeś błędu w walidacji?

**Comment by dol1234** [comment]
PUT na zasobie sale/offers/12451255761? 
trace-id=329a7ccabe0c3762

**Comment by MartaNowaczyk** [comment]
Powtórzyłam sytuację (jednak sprawdzałam na POST ;)  Konsultuję to jeszcze z zespołem odpowiedzialnym za tą funkcjonalność. Wrócę z odpowiedzią.

**Comment by MartaNowaczyk** [comment]
Według naszych założeń, żebyśmy zwrócili błąd na PUT to musi zajść istotna zmiana, która wywoła walidację czyli m.in. utworzenie draftu (dlatego na POST to działa), zmiana statusu oferty na aktywną, zmiana nazwy, zmiana kategorii, zmiana produktu.

Dodam tylko, że warto korzystać z [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers). Na początku 2023 roku przestaniemy wspierać [POST /sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST), a w 2024 planujemy go całkowicie wyłączyć.

**Comment by dol1234** [comment]
Wystarczy dodać do kolekcji Parameters nieistniejący parametr i oferta zwraca błąd walidacji (ale tylko związany z nowododanym niepoprawnym parametrem więc domyslam się, że walidacja robiona jest na diffie).
Jeżeli zmienię nazwę oferty, to faktycznie zwracany jest wtedy oczekiwany błąd walidacji. 
Czyli teoretycznie może zdarzyć się sytuacja w której zostaniemy z ofertą, której nie możemy aktywować: tworzymy draft, walidujemy ofertę, poprawiamy błędy zgodnie z błędami walidacji i przy okazji zmieniamy parametr, który był wcześniej poprawny na niepoprawny. 

Zauważyłem, że komunikaty walidacyjne o niepoprawnych wartościach zostały zmienione (było "Invalid parameter ABC (123) value for offer with product. Value should be "321"", a a teraz jest "Incorrect value of the ABC (123) parameter for the offered product. The correct parameter value for the product is: "321").
Gdzie znajdę aktualną listę komunikatów?

**Comment by MartaNowaczyk** [comment]
Może się tak zdarzyć, że dopiero podczas aktywacji oferty zobaczysz błąd. Może to być spowodowane również tym, że od czasu utworzenia draftu, do aktywacji oferty jakieś parametry zmieniliśmy w samym allegro - czyli raz utworzony draft, mimo, że nie zwracał błędu (nawet przy istotnej zmianie) może zwrócić błąd podczas aktywacji. Chyba, że wysyłasz requesty w krótkim odstępie czasu, to już by było mało prawdopodobne. 
Jeśli chodzi o listę komunikatów, to nie mamy takiej.
