### ISSUE TITLE
Błędnie wykrywany "Please remove the part in the description..." ?

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6057]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

:beetle: **Opis / Description**

Podczas wykonywania PUT /sale/offers (trace-id: 9e5a34f7b228b0bb) dostajemy błąd:
_Please remove the part in the description that redirects to the “About Seller” tab._
Jednak nie znajdujemy niczego niestosownego w opisie. Proszę o weryfikację.

**Comment by MartaNowaczyk** [comment]
Poprawiliśmy ten błąd - nie powinien już występować. Przepraszamy za problemy z tym związane.
