### ISSUE TITLE
Parcel returned from carrier

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6058]
Hi, I was wondering what the process is for parcels, that were never claimed by customer.
Only piece of information I found was in [here](https://allegro.pl/for-sellers/allegro-one-courier-information-for-sellers-nnLOalXazIW#zwroty-przesylek)
I am quite happy on what I found about customer returns, but I was not able to find information about operational return of the goods (unclaimed parcel)
![image](https://user-images.githubusercontent.com/109143627/186462648-72fab98c-1b54-47f7-9472-13dbb136141b.png)
Is there any aditional information to be found on this topic for

1. Ship with Allegro
2. When partner manages carriers themself
I am interested in order status change, refunds and similar.

Thanks in advance

Jirka

**Comment by Lukasz-Zurek** [comment]
Regarding operational return of the goods - Merchant can always change order fulfillment status via [PUT /order/checkout-forms/{checkoutForm.id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT), where he can use one of these statuses mentioned in the documentation. For example: "CANCELLED" which would be the most adequate in this particular situation.

If the customer returns the product, you will be able to use Customer Return resources, which we described in [our tutorial](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#customer-returns).

But if the customer didn't return the product - so we've got a situation where the customer didn't picked up the delivery package - Merchant should contact him, determine the details. Obviously he can use Payment refunds resources, which we described right [here](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#how-to-refund-a-payment).
