### ISSUE TITLE
Czy Allegro One - Zielone będą dostępne w Sandboxie?

### ISSUE THREAD

**Issue by gkopec** [allegro/allegro-api#6059]
Jak można testować AllegroOne - Zielony automat w Sandboxie?

**Comment by MartaNowaczyk** [comment]
Są dostępne testowe punkty w okrojonej ilości i nie pokrywają się z listą na produkcji. 
Np. Allegro One Box, zielony automat (AL007WK1)
Godziny otwarcia: całodobowo
Dzieci Warszawy 9
02-495 Warszawa
