### ISSUE TITLE
"/sale/offer-modification-commands/{commandId}" a zmiana parametrów oferty

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#606]
Witam,
czy poprzez metodę "/sale/offer-modification-commands/{commandId}" powinienem być w stanie zmodyfikować także parametry zakończonej (niesprzedanej) oferty? Jeżeli tak to jaka powinna być składnia takiego zapytania? W dokumentacji czegoś podobnego nie widzę.

A jeżeli nie to jak mogę w takim razie utworzyć nową ofertę na podstawie tej zakończonej (zmieniając już oczywiście ręcznie parametry) i upewnić się że stara oferta zniknie z niesprzedanych.

W skrócie chodzi o masowe ponowne wystawianie aukcji z brakującym parametrem który w międzyczasie stał się parametrem wymaganym i poprzez starą metodę `doSellSomeAgain` oferta nie może zostać wystawiona.

**Comment by Uriziel01** [comment]
Dla jasności poprzez parametry mam na myśli wartości zwracane poprzez metodę `/sale/offers/{offerId}` w kluczu `parameters` czyli przykładowo `Wzór dominujący:` czy `Cechy dodatkowe:`

**Comment by KrzysztofLukanowski** [comment]
Cześć,

nie. Wskazany przez Ciebie zasób służy do grupowej edycji ofert, ale nie uzupełnisz nim parametrów. Więcej o tym zasobie przeczytasz pod tym [adresem](https://developer.allegro.pl/news/2018-04-19-News_grupowa_edycja_ofert_update/).

Z kolei jak przygotować nową ofertę, czy zmienić zakończoną, a także jak wystawić podobną przeczytasz w naszym [poradniku](https://developer.allegro.pl/sale/#new-offer). Ofertę uzupełnisz zasobem [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/updateOfferUsingPUT).

**Comment by Uriziel01** [comment]
Witam,
przeczytałem przytoczony przez Pana poradnik kilkukrotnie ale nie znalazłem nigdzie informacji o tym jak mogę edytować zakończone aukcje a następnie skierować je do ponownego wystawienia, jeżeli mógł bym prosić o odrobinę dokładniejsze nakierowanie we właściwym kierunku był bym bardzo wdzięczny :)

**Comment by KrzysztofLukanowski** [comment]
Zakończone oferty można edytować tak jak trwające, wskazanym przeze mnie zasobem. Proszę pamiętać, że jeżeli oferta ma zostać później opublikowana, należy zmienić jej status na ACTIVE, a także   ilość dostępnych przedmiotów musi wynosić co najmniej 1. Po wprowadzeniu zmian wystarczy opublikować ofertę, zgodnie z [poradnikiem](https://developer.allegro.pl/sale/#step-7-offer-publication-commands).

**Comment by Uriziel01** [comment]
Używając metody [PUT /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#/offer-management/updateOfferUsingPUTl) dla zakończonych aukcji trafiam niestety na dość dziwne błędy, próbowałem zmienić jakieś pojedyncze pole jak na przykład `name` ale w odpowiedzi dostaje enigmatyczne `{"errors":[{"code":"VALIDATION_ERROR","message":"Offer id cannot be changed.","details":"","path":"","userMessage":"Nie możesz zmienić identyfikatora oferty."}]}` (mimo że identyfikatora z całą pewnością zmieniać nie próbuje)

Natomiast jeżeli próbuje przekazać całą obecną strukturę oferty pobraną z `GET sale/offers/{offerId}` dostaje już jawnie w odpowiedzi:
`{"errors":[{"code":"VALIDATION_ERROR","message":"You cannot edit an ended offer.","details":"","path":"","userMessage":"Nie można edytować zakończonej oferty."}]}`

Oczywiście dla aukcji trwających metoda ta działa wyśmienicie, problem występuje tylko dla ofert zakończonych.

**Comment by KrzysztofLukanowski** [comment]
Podeślij proszę requesty w formacie json.

**Comment by Uriziel01** [comment]
URL: `PUT sale/offers/7477528023`
DATA: `{"name":"test"}`
Trace-Id: `7521bff2cb845944`
Result: `{"errors":[{"code":"VALIDATION_ERROR","message":"Offer id cannot be changed.","details":"","path":"","userMessage":"Nie możesz zmienić identyfikatora oferty."}]}`


oraz 

URL: `PUT sale/offers/7477528023`
DATA: 
```
{
   "name":"#13KSS1386 ASHELY BROOKE ZIELONA SUKIENKA 40",
   "category":{
      "id":"124265"
   },
   "parameters":[
      {
         "id":"59",
         "valuesIds":[
            "59_5"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"451",
         "valuesIds":[

         ],
         "values":[
            "Odcienie zieleni"
         ],
         "rangeValue":null
      },
      {
         "id":"3766",
         "valuesIds":[
            "3766_1"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"3786",
         "valuesIds":[
            "3786_85"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"3806",
         "valuesIds":[
            "3806_5"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"4126",
         "valuesIds":[
            "4126_4"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"11323",
         "valuesIds":[
            "11323_246514"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"18160",
         "valuesIds":[
            "18160_4"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"127488",
         "valuesIds":[
            "127488_256934"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"128188",
         "valuesIds":[
            "128188_1"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"201017",
         "valuesIds":[
            "201017_257870"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":"202477",
         "valuesIds":[
            "202477_2"
         ],
         "values":[

         ],
         "rangeValue":null
      },
      {
         "id":201025,
         "valuesIds":[
            "201025_2521"
         ],
         "values":[

         ],
         "rangeValue":null
      }
   ],
   "ean":null,
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"<p>Zjawiskowa sukienka znanej i renomowanej marki,\rwykonana z wysokiej jako\u015bci materia\u0142u, uszyta na podszewce,\rz ty\u0142u na elastycznej gumce,\rsukienka na cienkich, odpinanych rami\u0105czkach,\rmiseczki lekko usztywniane,\rpod biustem odcinana,\rprz\u00f3d pi\u0119knie zdobiony b\u0142yszcz\u0105cymi aplikacjami.Uwaga: brak rami\u0105czek.\r<\/p><p> <\/p><p>Jako\u015b\u0107:100% poliester<\/p><p>Kolor:odcie\u0144 zieleni<\/p><p>D\u0142ugo\u015b\u0107:133 od pachy<\/p><p>D\u0142ugo\u015b\u0107 r\u0119kawa:--<\/p><p>Szer. pod pachami:34<\/p><p>Szer. w pasie:36<\/p><p>Szer. w biodrach:51<\/p><p>wszystkie wymiary podane w centymetrach (cm)<\/p>"
               },
               {
                  "type":"IMAGE",
                  "url":"https:\/\/7.allegroimg.com\/original\/0645e8\/e85a92dc4a70b9cab2677d81e6f7"
               }
            ]
         }
      ]
   },
   "compatibilityList":null,
   "images":[
      {
         "url":"https:\/\/7.allegroimg.com\/original\/0645e8\/e85a92dc4a70b9cab2677d81e6f7"
      }
   ],
   "sellingMode":{
      "format":"AUCTION",
      "price":null,
      "startingPrice":{
         "amount":"49.99",
         "currency":"PLN"
      },
      "minimalPrice":null
   },
   "stock":{
      "available":1,
      "unit":"UNIT"
   },
   "publication":{
      "duration":"PT72H",
      "status":"ENDED",
      "startingAt":null,
      "endingAt":"2018-07-29T17:41:01Z"
   },
   "delivery":{
      "shippingRates":{
         "id":"dc0d66cf-81a4-413e-a6c1-05757b25e075"
      },
      "handlingTime":"PT120H",
      "additionalInfo":"",
      "shipmentDate":null
   },
   "payments":{
      "invoice":"VAT"
   },
   "afterSalesServices":{
      "impliedWarranty":{
         "id":"d2acbb0b-a03d-4b0b-940c-2c140b21312f"
      },
      "returnPolicy":{
         "id":"06e24147-ca2a-40b9-96ab-54df56de9b81"
      },
      "warranty":{
         "id":"10c52b16-90d1-427d-ac26-f434d24a43d1"
      }
   },
   "additionalServices":null,
   "sizeTable":null,
   "promotion":{
      "emphasized":false,
      "bold":false,
      "highlight":false,
      "departmentPage":false,
      "emphasizedHighlightBoldPackage":false
   },
   "location":{
      "countryCode":"PL",
      "province":"LUBUSKIE",
      "city":"Warszawa",
      "postCode":"66-002"
   },
   "external":{
      "id":"930195888"
   },
   "contact":null
}
```
Trace-Id: `6ad3cd8cb14c88ea`
Result: `{"errors":[{"code":"VALIDATION_ERROR","message":"Offer id cannot be changed.","details":"","path":"","userMessage":"Nie możesz zmienić identyfikatora oferty."}]}`


co ciekawe jeszcze wczoraj te drugie zapytanie (ze zmianą parametrów) zwracało błąd `{"errors":[{"code":"VALIDATION_ERROR","message":"You cannot edit an ended offer.","details":"","path":"","userMessage":"Nie można edytować zakończonej oferty."}]}`

Jeżeli potrzeba czegoś jeszcze (mogę dostarczyć nawet w formie czystej komendy cURL jeżeli pomoże to rozwiązać problem) proszę pisać.

**Comment by KrzysztofLukanowski** [comment]
Widzę, że wznawiana oferta to aukcja. Wznowić można jedynie oferty Kupo teraz. W tym przypadku sugeruję pobrać zakończoną ofertę zasobem GET, a następnie na podstawie otrzymanych pól przygotować draft oferty POSTem i uzupełnić wszystkie wymagane parametry przed publikacją zasobem PUT, po czym wystawić ofertę PUTem offer-publication-commands. Dokładnie tak jak opisaliśmy to w akapicie [Wystaw podobną ofertę](https://developer.allegro.pl/sale/#similar-offer).

**Comment by Uriziel01** [comment]
No fajnie ale to sprawi że taka zakończona aukcja będzie wisieć u klienta w nieskończoność? Skoro jej nie wystawiłem ponownie to nie mam jak jej usunąć, prawda?

**Comment by Uriziel01** [comment]
Mam też pytanie innego pokroju, rozumiem że metoda nie potrafi edytować niczego w zakończonej aukcji gdyż nie ma to sensu w świetle tego że takiej aukcji i tak ponownie nie wystawimy? Ale w takim razie czy:
1)Taka informacja nie powinna być zawarta i podkreślona w dokumentacji technicznej?
2)Zwracany błąd nie mógł by być troszkę bliżej prawdy aniżeli błędne `Nie możesz zmienić identyfikatora oferty.`?

**Comment by KrzysztofLukanowski** [comment]
Nie ma technicznej możliwości usunięcia aukcji. Można jedynie ją wyłączyć z podglądu w zakładce Moje Allegro, jednak sam ślad po aukcji cały czas jest w naszym systemie.

**Comment by KrzysztofLukanowski** [comment]
Planujemy wprowadzić poprawki w dokumentacji, jak i w treściach zwracanych błędów.
