### ISSUE TITLE
Wysyłka faktur przez API

### ISSUE THREAD

**Issue by kubaimag** [allegro/allegro-api#6060]
Dzień dobry,
Mam problem z wysyłką faktur przez API.
Teoretycznie wszystkie przechodzi prawidłowo, statusy z API prawidłowe jednak w samym Allegro po przejściu do zamówienia i sprawdzeniu "dowodu zakupu" a następnie pobraniu PDF-a nie można go otworzyć.
Przykładowy numer zamówienia na środowisku testowym:
c0c7ab80-fd1e-11ec-8a59-57b7dec82e1f

**Comment by MartaNowaczyk** [comment]
Sprawdzę opisaną sytuację i wrócę z odpowiedzią.

**Comment by kubaimag** [comment]
Dziękuję

**Comment by MartaNowaczyk** [comment]
Przetestowałam u siebie i nie mam problemu z otwarciem pobranego pliku pdf. Wygląda to na problem z samym plikiem. Próbowałeś dodać różne pliki, żeby sprawdzić czy nie zależy to od pliku który dodajesz? Możesz podesłać plik, który nie chce się otwierać przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) z dopiskiem, że dotyczy wątku na GH #6060.

**Comment by kubaimag** [comment]
Tak, próbowałem ale bezskutecznie. Wysłałem już pliki przez formularz

**Comment by kubaimag** [comment]
Udało się wysłać plik prawidłowo, błąd był w sposobie wysyłania pliku po mojej stronie. Temat można zamknąć, dziękuję za pomoc
