### ISSUE TITLE
Rest Api Token Problem

### ISSUE THREAD

**Issue by barismisir** [allegro/allegro-api#6061]
When i try to create token i always get same answer

{"error":"invalid_request","error_description":"Unauthorized"}

Help me please 
![Screenshot_3](https://user-images.githubusercontent.com/88281303/186693985-87c70923-1f7a-4c27-a43e-e1fd4f5e4ee7.png)

**Comment by Lukasz-Zurek** [comment]
Please make sure to encode all client_id: client_secret data with the ":" sign between the values.

If it's not the case, please send us your full request in the json curl form with the data - via our [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). In your message please add GitHub[ #6061](https://github.com/allegro/allegro-api/issues/6061).

**Comment by barismisir** [comment]
I put : between client id and client secret.
![Screenshot_4](https://user-images.githubusercontent.com/88281303/186838109-7a4c570a-cc18-420c-963a-e553ce12642d.png)

**Comment by Lukasz-Zurek** [comment]
Ok, thank you. Please contact us via our contact form, as above.

**Comment by hahyes** [comment]
> When i try to create token i always get same answer
> 
> {"error":"invalid_request","error_description":"Unauthorized"}
> 
> Help me please ![Screenshot_3](https://user-images.githubusercontent.com/88281303/186693985-87c70923-1f7a-4c27-a43e-e1fd4f5e4ee7.png)

@barismisir Hi there.
From what I can see (and I remember from RestSharp), problem is with using of `.AddParameter()`. `grant_type`, `redirect_uri` and `code` are a query parameters, `.AddParameter() adds a POST parameter, when Allegro API requires GET parameter (in url).
Look on example of request query from the tutorial: 
`POST https://allegro.pl/auth/oauth/token?grant_type=authorization_code&code=pOPEy9Tq94aEss540azzC7xL6nCJDWto&redirect_uri=http://exemplary.redirect.uri`

**Comment by barismisir** [comment]
> Ok, thank you. Please contact us via our contact form, as above.

Thanks i created the form i am waiting for reply

**Comment by Lukasz-Zurek** [comment]
@barismisir **hahyes** is right. You should use method `AddQueryParameter()` thanks to which you will add the (Query) parameters in the header of the message. The `AddParameter()` will only add the parameters to the message body which will cause the error.

**Comment by barismisir** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/88281303/187184800-b94bd69a-8534-459f-937a-929498390d2f.png)

Thanks, I also tried making a request like this, but I still couldn't find the solution. Even though I have the code, I get the response {"error":"Unauthorized","error_description":"Unauthorized"}

**Comment by barismisir** [comment]
> @barismisir **hahyes** is right. You should use method `AddQueryParameter()` thanks to which you will add the (Query) parameters in the header of the message. The `AddParameter()` will only add the parameters to the message body which will cause the error.
![Screenshot_7](https://user-images.githubusercontent.com/88281303/187184878-6f2b8034-393d-438b-8a73-2bf55b0300e8.png)

Thanks, I also tried making a request like this, but I still couldn't find the solution. Even though I have the code, I get the response {"error":"Unauthorized","error_description":"Unauthorized"

**Comment by barismisir** [comment]
@Lukasz-Zurek Does allegro accept localhost as the redirect_uri?

**Comment by Lukasz-Zurek** [comment]
@barismisir Yes, we do.
