### ISSUE TITLE
Aktywacja konta firmowego

### ISSUE THREAD

**Issue by makerlabs** [allegro/allegro-api#6062]
Witam,
Proszę o aktywacje konta firmowego dla konta sandbox **annawaskowiak**

Pozdrawiam
Marcin Butlak

**Comment by MartaNowaczyk** [comment]
Witaj Marcin. Nie przeszedłeś jeszcze wszystkich kroków konfiguracji sprzedaży. [Ustaw wypłaty środków](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/konwersja-konta/ustaw-konto-do-wyplat) i [zweryfikuj konto firmowe](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/konwersja-konta/przeslij-dokumenty) - uzupełnij dane i prześlij dowolne pliki. Jeśli napotkasz jakiś problem, daj znać.

**Comment by makerlabs** [comment]
Aktualnie dane zostały uzupełnione i pliki przesłane ale w 2 kroku (Weryfikacja firmy) wyświetla się cały czas tylko informacja:
Weryfikujemy dane Twojej firmy a konto dalej nie jest przełączone jako konto Firmowe

**Comment by MartaNowaczyk** [comment]
Sprawdź teraz czy jest ok.

**Comment by makerlabs** [comment]
Tak teraz działa dzięki.
