### ISSUE TITLE
【/sale/product-offers】the image reports an error

### ISSUE THREAD

**Issue by niuniubaba** [allegro/allegro-api#6064]
When I call the api (/sale/product-offers), the image reports an error, Why?  Can an image only be used for one product ?
http_response_422  Product image `https://a.allegroimg.com/original/115b49/b39a31ae4a7b9355c3740de8e42d` was specified multiple times.;Offer image `https://a.allegroimg.com/original/115b49/b39a31ae4a7
http_response_422  Offer image `https://a.allegroimg.com/original/116459/e51f4e014e7188fdfb8fd251b66d` was specified multiple times.;Product image `https://a.allegroimg.com/original/112d75/c14e7c9042a

**Comment by PrzemyslawLukanowski** [comment]
One image can be specified only once in the `productSet.product.images` and `images` sections in a single request. In your case, those images links were provided more than once.
