### ISSUE TITLE
Nie znaleziono zamówienia Allegro dla podanego adresu email odbiorcy.

### ISSUE THREAD

**Issue by Desseres** [allegro/allegro-api#6065]
Występuje problem:
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Mam problem z kilkoma zamówieniami. Użytkownicy wybrali formę wysyłki "SMART" Allegro Paczkomaty InPost. API zwraca informację że: `{
    "status": 400,
    "error": "validation_failed",
    "message": "Wystąpiły błędy podczas walidacji. Szczegóły poniżej.",
    "details": {
        "custom_attributes": [
            {
                "target_point": [
                    "Nie istnieje"
                ]
            }
        ],
        "receiver": [
            {
                "email": "Nie znaleziono zamówienia Allegro dla podanego adresu email odbiorcy."
            }
        ]
    }
}`

Oba zamówienia mają status `OPŁACONY` i powinno dać się wygenerować dla nich nr. listu przewozowego. Po stronie wysylam.allegro.pl prosi o dodanie umowy własnej z InPOST - czego nie powinien robić, tylko lecieć na Waszej umowie.

Numer zamówienia: 70373111-2639-11ed-9bfe-a7e99757b691 email: youpxvi6oo+25d664010@allegromail.pl
Numer zamówienia: b6d3f2b1-26d0-11ed-b5cf-7b0838e3cfd8 email: shy0mja9vx+1596cfc95@allegromail.pl

**Comment by Desseres** [comment]
Kolejne zamówienie z tym błędem: cbdd9ac5-26fe-11ed-81ec-058ec869d5c9 email: vbq1sk3muq+23959eae7@allegromail.pl

**Comment by PrzemyslawLukanowski** [comment]
Zgodnie z informacją z [naszego poradnika](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke), aby skorzystać z umowy Allegro InPost, musisz dodać w [ustawieniach Wysyłam z Allegro](https://allegro.pl/moje-allegro/sprzedaz/zamowienia/ustawienia) umowę własną i wybrać opcję "Używaj oferty dla sprzedawców Allegro".

**Comment by Desseres** [comment]
@PrzemyslawLukanowski ale ja nie chce dodawać swojej umowy. Klient zamówił przesyłkę SMART InPOST Paczkomat. Tysiąc innych zamówień generuje się poprawnie. Te 3 zamówienia mają jakiś problem ze sobą, tak jak by nie zostały zgłoszone do programu SMART po stronie systemu InPOST. 

Jeżeli wchodzę w wysylam.allegro.pl to każe dodać mi umowę własną z inpostem. Co jest błędem.
Zamówienie zgodnie z informacją jest w metodzie smart za 0 zł. Dlaczego ja mam to nadawać na swojej umowie i drugi raz płacić za wysyłkę?
![screen](https://user-images.githubusercontent.com/4050097/187178139-938b77a0-ff21-46d2-9051-7b8c03b4ad41.png)


zgłoszenie przez API SHIP X InPOSTu z poprawnym adresem e-mail odrzuca zamówienie że to nie jest poprawne zamówienie z Allegro i że oni nie mają limitów na to zamówienie. 

Błąd jest w komunikacji Allegro <=> InPOST, bo oba serwisy powinny pozwolić mi wygenerować list przewozowy w ramach usługi SMART, gdzie nie muszę posiadać żadnej umowy z przewoźnikiem.

**Comment by Desseres** [comment]
Wskazane majle, mimo tego że użytkownik określił metodę wysyłki jako Allegro Smart, nie zostały zaraportowane do systemu InPOST jako adresy przypisane do zamówień dla których można wygenerować etykietę.

![2 brak](https://user-images.githubusercontent.com/4050097/187179605-3de32f35-79d4-4061-9a1a-7b3f4e0313b9.png)
![1 brak](https://user-images.githubusercontent.com/4050097/187179609-26c73b55-2663-419b-89a2-a3d87fcf8944.png)
![3 brak](https://user-images.githubusercontent.com/4050097/187179611-17a7d205-6dba-4ffd-8bf4-c99cad4fce70.png)

**Comment by PrzemyslawLukanowski** [comment]
Skontaktuj się proszę bezpośrednio przez [formularz kontaktowy ](https://allegro.pl/pomoc/kontakt?kategoria=6b0fd6c3-e25e-4e61-a1da-ed23df85af7e&subjectId=84e1c27e-ba93-48c2-b237-c3ae940ae06a) i przekaż przytoczone wyżej szczegóły. Wskazany problem nie jest bezpośrednio związany z Allegro API, nie jesteśmy zatem w stanie pomóc w tej sytuacji.
