### ISSUE TITLE
Błąd poczas  zakładania produktu w katalogu product-proposals

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#6066]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**
 

Próbuję założyć produkt w katalogu, ale dostaję błąd, który nie tłumaczy dokładnie co jest nie tak:
Wykonanie requesta na sandobxie:

POST https://api.allegro.pl.allegrosandbox.pl/sale/product-proposals
Zwraca błąd

422 {"errors":[{"code":"ParameterException.InvalidParameterDtoException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 2978."}]}.

Parametr 2978 to szerokość w cm. Nie rozumiem co robię nie tak. Próbowałem na kilka sposobów go przekazać (jako liczbę  jako string , z dwoma zerami po przecinku) ciągle jest ten sam błąd.

poniżej JSON
```
{
  "name": "Płyty brukowe Semmelrock",
  "category": {
    "id": "126193"
  },
  "parameters": [
    {
      "id": "130575",
      "valuesIds": [
        "130575_6"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "130576",
      "valuesIds": [
        "130576_6"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "2978",
      "valuesIds": [],
      "values": [
        "15"
      ]
    },
    {
      "id": "2977",
      "valuesIds": [],
      "values": [
        "60"
      ],
      "rangeValue": null
    },
    {
      "id": "244021",
      "valuesIds": [],
      "values": [
        "440"
      ],
      "rangeValue": null
    },
    {
      "id": "224017",
      "valuesIds": [],
      "values": [
        "SEM0001"
      ],
      "rangeValue": null
    },
    {
      "id": "248811",
      "valuesIds": [
        "248811_950468"
      ],
      "values": [],
      "rangeValue": null
    }
  ],
  "images": [
    {
      "url": "https://a.allegroimg.allegrosandbox.pl/original/11a134/cdbfffeb48bebd919e27cf259aaa"
    }
  ],
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Opis testat</p>"
          }
        ]
      }
    ]
  }
}
 

```

**Comment by PrzemyslawLukanowski** [comment]
W przypadku, gdy przekazujesz wartość w polu "value", usuń proszę pustą tablicę w "valuesIds" i zamiast tego przekaż null. Prócz parametru 2978 dotyczy to także 2977, 244021 i 224017. 
Dla parametru "Marka" (248811) wybrałeś wartość niejednoznaczną ("inna") dlatego dodatkowo wskaż proszę swoją wartość w "values", np.:

```
    {
      "id": "248811",
      "valuesIds": [
        "248811_950468"
      ],
      "values": ["Twoja nazwa marki"],
      "rangeValue": null
    }
```

**Comment by WGRINGO** [comment]
Dziękuję, pomogło. Swoją drogą w przypadku tworzenia oferty zamiast produktu posyłałem pustą tablicę zamiast null w parametrach i przechodziło więc można by to ujednolicić.
Czy oprócz Marki o wartości "inna" 248811_950468 jest więcej analogicznych przypadków, gdzie trzeba podać sugerowaną własną wartość? Jakieś przykłady?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli w odpowiedzi dla [GET /sale/categories/categoryID/parameters ](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) zwrócimy wartość `true` w polach `requiredForProduct` i `options.customValuesEnabled`, to w takim przypadku należy również dostarczyć własną wartość w "values". Przykład - parametr "Producent części" (127415) w kategorii np. 258679.

**Comment by WGRINGO** [comment]
Dziękuję.
Kiedy req z utworzeniem produktu przejdzie to mija trochę czasu zanim /sale/products zwraca go przy wyszukiwaniu po frazie (zapytanie po frazie zwraca pusty wynik).
Proszę rozwiać moje wątpliwości - gdy req przejdzie powinienem sobie zapisać ID z responsa po czym odpytywać po tym ID czy produkt został założony, a dopiero potem pozwolić wystawić ofertę? 

Inaczej mówiąc czy pole

`  isDraft: false
`
znajdujące się po sekcji description informuje o tym, że produkt jest już założony albo jeszcze nie i trwa jego weryfikacja

`  isDraft: true
`
Czyli dopóki ta wartość jest =true nie mogę wystawić oferty powiązanej z tym produktem?

**Comment by PrzemyslawLukanowski** [comment]
Wartość `true` w polu `isDraft` aktualnie dotyczy wyłącznie draftów produktu, które tworzymy na podstawie sugestii zmian użytkowników ze strony internetowej. Więcej informacji na ten temat możesz przeczytać w [naszym newsie](https://developer.allegro.pl/news/drafty-produktow-wprowadzilismy-nowy-filtr-oraz-pole-w-wyszukiwarce-produktow-yPm5l3Ow1s6). Pole zatem nie jest związane z nowymi produktami, które tworzysz za pomocą POST /sale/product-offers lub POST /sale/product-proposals. ID takich nowo utworzonych produktów możesz od razu wykorzystać przy wystawianiu nowej oferty.

**Comment by WGRINGO** [comment]
Witam ponownie.
O ile na sandboxie działa wszystko jak należy to na produkcyjnym u klienta mam taki problem:
Wygląda na to, że towar jest zakładany w katalogu Allegro poprawnie, po czym wyszukiwanie zwraca pusty wynik (czy to po EANie czy frazie) więc program próbuje założyć ten towar i w efekcie dostaję błąd Duplicate (towar już istnieje skontaktuj się z autorem aplikacji). Przykładowo:

```
https://api.allegro.pl/sale/products?phrase=5415125547364&mode=GTIN

{"products":[],"categories":{"subcategories":[{"id":"5","name":"Dom i Ogród","count":0},{"id":"11763","name":"Dziecko","count":0},{"id":"42540aec-367a-4e5e-b411-17c09b08e41f","name":"Elektronika","count":0},{"id":"4bd97d96-f0ff-46cb-a52c-2992bd972bb1","name":"Firma i usługi","count":0},{"id":"a408e75a-cede-4587-8526-54e9be600d9f","name":"Kolekcje i sztuka","count":0},{"id":"38d588fd-7e9c-4c42-a4ae-6831775eca45","name":"Kultura i rozrywka","count":0},{"id":"ea5b98dd-4b6f-4bd0-8c80-22c2629132d0","name":"Moda","count":0},{"id":"3","name":"Motoryzacja","count":0},{"id":"20782","name":"Nieruchomości","count":0},{"id":"3919","name":"Sport i turystyka","count":0},{"id":"258832","name":"Supermarket","count":0},{"id":"1429","name":"Uroda","count":0},{"id":"121882","name":"Zdrowie","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"}]},"filters":[],"nextPage":null}
```

```
https://api.allegro.pl/sale/products?phrase=QUICK-STEP%20Winyl%20PUCP40083%20Pulse%20Click&category.id=304865

{"products":[],"categories":{"subcategories":[{"id":"304865","name":"Panele laminowane","count":0}],"path":[{"id":"954b95b6-43cf-4104-8354-dea4d9b10ddf","name":"Allegro"},{"id":"5","name":"Dom i Ogród"},{"id":"1520","name":"Budownictwo i Akcesoria"},{"id":"15960","name":"Podłogi"},{"id":"304853","name":"Panele podłogowe"},{"id":"304865","name":"Panele laminowane"}]},"filters":[{"id":"215286","name":"Długość","type":"NUMERIC","values":[{"name":"od","value":null,"idSuffix":".from","count":null,"selected":false},{"name":"do","value":null,"idSuffix":".to","count":null,"selected":false}],"minValue":0,"maxValue":1000,"unit":"cm"},{"id":"215290","name":"Szerokość","type":"NUMERIC","values":[{"name":"od","value":null,"idSuffix":".from","count":null,"selected":false},{"name":"do","value":null,"idSuffix":".to","count":null,"selected":false}],"minValue":0,"maxValue":1000,"unit":"cm"},{"id":"130154","name":"Grubość całkowita","type":"SINGLE","values":[{"name":"mniej niż 6 mm","value":"1","idSuffix":null,"count":0,"selected":false},{"name":"6 mm","value":"2","idSuffix":null,"count":0,"selected":false},{"name":"7 mm","value":"3","idSuffix":null,"count":0,"selected":false},{"name":"8 mm","value":"4","idSuffix":null,"count":0,"selected":false},{"name":"9 mm","value":"5","idSuffix":null,"count":0,"selected":false},{"name":"10 mm","value":"6","idSuffix":null,"count":0,"selected":false},{"name":"12 mm","value":"7","idSuffix":null,"count":0,"selected":false},{"name":"więcej niż 12 mm","value":"8","idSuffix":null,"count":0,"selected":false},{"name":"brak informacji","value":"381585","idSuffix":null,"count":0,"selected":false}],"minValue":null,"maxValue":null,"unit":null}],"nextPage":null}

```

**Comment by PrzemyslawLukanowski** [comment]
Widzę, że produkt nie jest również zwracany przez wyszukiwarkę na stronie internetowej (a jej odpowiednikiem jest GET /sale/products). Taka sytuacja może mieć miejsce, gdy produkt jest "słaby jakościowo", czyli np. nie posiada uzupełnionych wszystkich parametrów obowiązkowych. Jeśli w odpowiedzi POST /sale/product-proposals zwrócimy w takim przypadku informację o duplikacie, proszę zwrócić uwagę na nagłówek `Location` w odpowiedzi. Zwrócimy w nim adres głównego produktu, którego dane można pobrać i uwzględnić w ofercie.
