### ISSUE TITLE
Publikacja komunikatów walidacyjnych zwracanych przez serwis (PL/ENG)

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#6067]
Prosiłbym o dodanie do dokumentacji wszystkich formatów komunikatów walidacyjnych.
Co jakiś czas ulegają one zmianie, co nie pozwala poprawiać ofert automatycznie przy pomocy wyrażeń regularnych.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię, weźmiemy ją pod uwagę w dalszych planach rozwoju naszej strony.
