### ISSUE TITLE
Konto testowe - allegro

### ISSUE THREAD

**Issue by szzynaa** [allegro/allegro-api#6068]
Witam,

Mam u Państwa od prawie 3 lat konto firmowe. Obecnie będę chciał zmienić swoje oprogramowanie CRM i tym samym będzie inna integracja z allegro. Chce jednak wcześniej potestować zanim "przepnę" prawdziwe konto. Czy jest możliwość otrzymania jakiegoś konta testowego ? Obiła mi się kiedyś o uszy nazwa "sandbox" ale nie wiem czy to o to chodzi. Prośbą o pomoc.

**Comment by Lukasz-Zurek** [comment]
Tak, mamy [środowisko testowe Sandbox](https://allegro.pl.allegrosandbox.pl). Rejestracja konta przebiega w niemal identyczny sposób jak w przypadku wersji produkcyjnej Serwisu Allegro.pl.

Natomiast jeżeli chodzi o proces aktywacji - proces jest automatyczny, w związku z czym w celu aktywacji musisz skorzystać z naszego symulatora płatności (nie jest to zatem prawdziwy przelew, a symulacja).

Generalnie najlepiej zarejestrować przynajmniej dwa konta, z których jedno koniecznie firmowe. Formularz rejestracji znajduje się pod [tym adresem](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/nowe-konto?origin_url=%2F).

Oczywiście w razie problemu z aktywacją, lub weryfikacji firmy - daj proszę znać w tym wątku.

Zapoznaj się również proszę z [naszym poradnikiem](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe), gdzie opisaliśmy również to jak korzystać z Sandboxa przez REST API.

**Comment by szzynaa** [comment]
ok, dziękuję - udało się.

**Comment by szzynaa** [comment]
Witam,

Pytanie od mojego DEV : 

"proszę o potwierdzenie u obsługi allegro czy pozwalają na integrację pomiędzy SANDBOXallegro, a beslinker - aktualnie nie widzę w BL takiej możliwości."

**Comment by szzynaa** [comment]
Witam,

Mam pytanie od mojego DEV :

proszę o potwierdzenie u obsługi allegro czy pozwalają na integrację pomiędzy SANDBOXallegro, a beslinker - aktualnie nie widzę w BL takiej możliwości.

**Comment by Lukasz-Zurek** [comment]
@szzynaa Po naszej stronie udostępniamy tylko środowisko testowe Sandbox. Nic więcej.

**Comment by Zuczekk** [comment]
Witam proszę o aktywacje konta allegro.pl.allegrosandbox.pl na emailu tomaszorganek1874@gmail.com. Proszę też o informacje zwrotno czy konto już działa jako firmowe. Za pomoc dziekuje :)

**Comment by szzynaa** [comment]
To chyba jakaś pomyłka ?

**Comment by MartaNowaczyk** [comment]
@szzynaa "Zuczekk" podpiął się tylko pod Twój wątek.
@Zuczekk Twoje konto już sprawdzałam, ale na ten moment mam problem z jego pełną aktywacją. Możesz spróbować założyć jeszcze jedno konto i podać mi jego dane, albo poczekaj - być może uda mi się aktywować to co podałeś. Tak poza tym, czysto informacyjnie - gdy wątek jest już zamknięty stwórz proszę nowy, albo poszukaj aktywnego w Twoim temacie :)

**Comment by MartaNowaczyk** [comment]
@Zuczekk jeśli możesz to załóż nowe konto, od razu z intencją na sprzedaż - konto firmowe, z tamtym niestety jest problem i nie będę go mogła aktywować.
