### ISSUE TITLE
Offer based on product, manufacturer error

### ISSUE THREAD

**Issue by raimondases4b** [allegro/allegro-api#6069]
- /sale/product-offers
 - production & test environment

Getting error on submitting offer with "other" part manufacturer parameter.

Request:
`{"id":null,"name":"MERCEDES-BENZ C124 Wentylator grzejnik 0005008593","category":{"id":"258679"},"external":{"id":"P-11"},"images":["https:\/\/a.allegroimg.com\/original\/11a035\/d59a44ad4288abe31901f7e9717d","https:\/\/a.allegroimg.com\/original\/1111da\/60dc11ff4f17acf97f8874add4b7","https:\/\/a.allegroimg.com\/original\/115a1b\/6c9b6cb14313a7d96a7fb4a7a30c","https:\/\/a.allegroimg.com\/original\/1176b1\/c2435efe4edf96309671acd0606b","https:\/\/a.allegroimg.com\/original\/11703d\/37aa55f84de184688fb69f7bfbbe"],"location":{"city":"\u0160aki\u0173 r. sav.","countryCode":"LT","postCode":"71176"},"description":{"sections":[{"items":[{"type":"TEXT","content":"<p>MERCEDES-BENZ COUPE (C124) Wentylator, grzejnik,&nbsp;<\/p><p><\/p><p>Kod OEM - 000 500 85 93<\/p><p>Kod produktu - P-11<\/p><p><\/p><p>----------------------------------------------------------------------------------------------------<\/p><p>Zawsze sprawdzaj kod OEM i niestandardowe ustawienia, kt\u00f3re zapewniamy dla przedmiotu.<\/p><p>Je\u015bli cz\u0119\u015b\u0107 ma wady, s\u0105 one wskazane na zdj\u0119ciach.<\/p><p><\/p><p><\/p>"}]}]},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":"e66cb0dc-66bb-456a-84c9-c29037144a4b"}},"sellingMode":{"format":"BUY_NOW","price":{"amount":"199.44","currency":"PLN"}},"payments":{"invoice":"VAT"},"tax":{"rate":"23.00"},"stock":{"available":3,"unit":"UNIT"},"customParameters":null,"parameters":[{"id":11323,"valuesIds":["11323_1"]}],"compatibilityList":{"items":[{"id":"4a28c2e6-bffc-4012-9940-8dc77362adab","type":"ID","additionalInfo":[]},{"id":"c328299a-8041-444b-a100-f545713c4d94","type":"ID","additionalInfo":[]},{"id":"72a5b0e6-d2e8-423e-bdce-fc1d499adb4c","type":"ID","additionalInfo":[]},{"id":"c6b6b34a-5be1-4340-b591-2b3e0c756dbd","type":"ID","additionalInfo":[]},{"id":"1a4a08fb-79c2-4cfb-b2ae-a680815cc181","type":"ID","additionalInfo":[]},{"id":"2f258f9c-1787-4132-abaf-70e7cf817564","type":"ID","additionalInfo":[]},{"id":"5c08104a-7bd2-42fe-b372-426332332ba9","type":"ID","additionalInfo":[]},{"id":"47899da4-9e6a-4873-b8d5-4579fa4418b1","type":"ID","additionalInfo":[]},{"id":"88c94dea-c189-48c6-b0a3-e44b59381426","type":"ID","additionalInfo":[]},{"id":"62517232-2107-47b7-85b6-c10bf0a5e395","type":"ID","additionalInfo":[]},{"id":"75fd153e-5408-4928-9550-c3b79d1828f0","type":"ID","additionalInfo":[]},{"id":"08cf7f02-5ec2-4d17-aac8-e7f935670e50","type":"ID","additionalInfo":[]},{"id":"35320b8b-97b4-4838-bcae-b18d4b5ecbf2","type":"ID","additionalInfo":[]},{"id":"b1d84340-4e59-4709-bdee-4a2a6b70965c","type":"ID","additionalInfo":[]},{"id":"d0fa1e08-e865-4f24-9ca5-8a08ea8af61f","type":"ID","additionalInfo":[]},{"id":"e89cb099-a4aa-4265-bc03-672ee87254f5","type":"ID","additionalInfo":[]},{"id":"afc96e71-b46d-44f7-ac80-0946e0ef69a7","type":"ID","additionalInfo":[]},{"id":"b9bc7121-afc5-4853-90b5-fcac40ba3154","type":"ID","additionalInfo":[]},{"id":"c0d1de22-a7dd-44f6-a3c8-d997676fa88c","type":"ID","additionalInfo":[]},{"id":"8be62538-e3b5-49cd-ae79-c2a72e018a83","type":"ID","additionalInfo":[]},{"id":"e94944b3-ad4d-43cc-98d5-b9411ed4eb11","type":"ID","additionalInfo":[]},{"id":"2c3dcb80-2ef3-46d5-9be0-8eb9756c4f14","type":"ID","additionalInfo":[]},{"id":"e7fdcc1c-78db-4e7e-af20-55d7caa9e73e","type":"ID","additionalInfo":[]},{"id":"a1813e58-e78c-4954-a1b1-c6fa47a580b9","type":"ID","additionalInfo":[]},{"id":"8a77726d-6d7b-48ab-b614-61c6a2a2d531","type":"ID","additionalInfo":[]},{"id":"90ef5c03-83d6-4d84-974e-5e8c97988af4","type":"ID","additionalInfo":[]},{"id":"da47bae9-fd47-4bc9-8fbc-6aa3adf5626f","type":"ID","additionalInfo":[]},{"id":"7076ae6f-3917-432c-82ec-f09e3f62d16d","type":"ID","additionalInfo":[]},{"id":"2b58541d-6e63-4336-a334-330dd85b961c","type":"ID","additionalInfo":[]},{"id":"96c6dc61-71f2-47b6-be0d-bedac9ef0c01","type":"ID","additionalInfo":[]},{"id":"60662095-0a85-48c8-ab6a-79610ebfda5f","type":"ID","additionalInfo":[]},{"id":"d9a1efc8-661f-44e9-aba6-3d786fd75e2f","type":"ID","additionalInfo":[]},{"id":"908fa577-7cbc-40e8-af31-ff26b67f6e1c","type":"ID","additionalInfo":[]},{"id":"878a945a-6206-4fcd-bb17-fa1f6704e369","type":"ID","additionalInfo":[]},{"id":"952e96df-7d10-49cd-a8d5-2db72c009f8a","type":"ID","additionalInfo":[]},{"id":"d1eea579-0c34-493a-81f5-2889bc654551","type":"ID","additionalInfo":[]},{"id":"bb0da877-a9c3-4f49-8a5d-a0b8a7049b67","type":"ID","additionalInfo":[]},{"id":"6b64124e-5194-4e28-a2ea-841392921af4","type":"ID","additionalInfo":[]},{"id":"8336d859-16de-4dac-99ff-6cbf3a86a0e2","type":"ID","additionalInfo":[]},{"id":"9bd8bf8f-ea46-40dd-8c87-29401cf970df","type":"ID","additionalInfo":[]},{"id":"d6258e55-20f3-4aec-a463-96ab0cf43361","type":"ID","additionalInfo":[]},{"id":"31046038-ffb2-4ffe-86b8-1818b01df83d","type":"ID","additionalInfo":[]},{"id":"67951e40-ae23-4fac-9446-2dc0611b5dd1","type":"ID","additionalInfo":[]},{"id":"57790d67-1cba-4d7a-a455-98231a135edc","type":"ID","additionalInfo":[]},{"id":"c7917b19-11b4-463f-bf49-3769895aa5af","type":"ID","additionalInfo":[]},{"id":"ed6c8a82-2fad-4a99-a907-738bada8379a","type":"ID","additionalInfo":[]},{"id":"38f957ed-021e-4659-be1e-977ab9834f1e","type":"ID","additionalInfo":[]},{"id":"250dcd89-1bb6-4453-b52f-b18b192f2a60","type":"ID","additionalInfo":[]},{"id":"b6851f96-e22f-4de2-8280-2e0c59df4c26","type":"ID","additionalInfo":[]},{"id":"8b8397cb-3560-4a36-a045-88ef81c2b660","type":"ID","additionalInfo":[]},{"id":"d7b1b344-6b7d-44cc-b6a3-6bc3d1e2bb98","type":"ID","additionalInfo":[]},{"id":"91c0ece6-fbb7-4563-9c40-d3b342649059","type":"ID","additionalInfo":[]},{"id":"c112a3f7-196f-494d-bbc7-89691a2c670c","type":"ID","additionalInfo":[]},{"id":"3fbbf47f-d956-4156-8d66-265d73f33dee","type":"ID","additionalInfo":[]},{"id":"519d9d8f-c227-4176-91de-504e7a41f517","type":"ID","additionalInfo":[]},{"id":"6714d145-d204-4042-b285-69155398f792","type":"ID","additionalInfo":[]},{"id":"89559708-a1c0-4db8-9840-19e244c13de0","type":"ID","additionalInfo":[]},{"id":"d9d3ef38-d2e1-4466-8be5-c59befd2f792","type":"ID","additionalInfo":[]},{"id":"c94380d5-3f58-40ac-a760-a2ead8fd6400","type":"ID","additionalInfo":[]},{"id":"d1ca1091-7fca-4608-a38f-4b248f3bb2a9","type":"ID","additionalInfo":[]},{"id":"860099fc-3380-4084-a603-cc732655413b","type":"ID","additionalInfo":[]}]},"afterSalesServices":{"returnPolicy":{"id":"446bd29e-2155-49a3-8c04-cb2dbbebfef6"},"impliedWarranty":{"id":"bdb0264e-520d-46e8-897c-f06adec92e87"}},"productSet":[{"product":{"name":"MERCEDES-BENZ C124 Wentylator grzejnik 0005008593","category":{"id":"258679"},"parameters":[{"id":127415,"valuesIds":["127415_22"]},{"id":129591,"valuesIds":["129591_1"]},{"id":215858,"values":["000 500 85 93"]}],"images":["https:\/\/a.allegroimg.com\/original\/11a035\/d59a44ad4288abe31901f7e9717d","https:\/\/a.allegroimg.com\/original\/1111da\/60dc11ff4f17acf97f8874add4b7","https:\/\/a.allegroimg.com\/original\/115a1b\/6c9b6cb14313a7d96a7fb4a7a30c","https:\/\/a.allegroimg.com\/original\/1176b1\/c2435efe4edf96309671acd0606b","https:\/\/a.allegroimg.com\/original\/11703d\/37aa55f84de184688fb69f7bfbbe"]},"quantity":{"value":1}}]}`

Error response:
`  "errors": array:1 [
    0 => {#5772
      "code": "ProductValidationException"
      "message": "Part manufacturer"
      "details": null
      "path": "productSet[0].product"
      "userMessage": "Custom value proposition has not been provided for ambiguous value in parameter Part manufacturer"
    }
  ]`

**Comment by PrzemyslawLukanowski** [comment]
In the 127415 parameter, you have chosen an ambiguous value. In this case, provide your custom value in the "values" field, for example:
```
{
	"id": 127415,
	"valuesIds": ["127415_22"],
        "values": ["Your value"]
}
```

**Comment by raimondases4b** [comment]
Ok.
How to know when i need add extra custom value when not? Because with other categories than i choose "other" part manufacturer there is no need add extra value (but I not remember if it same or not parameter ID). In short are there more conditions or just this parameter need extra value?

**Comment by PrzemyslawLukanowski** [comment]
If in the response to [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2) we return `true` in the `requiredForProduct`  and `options.customValuesEnabled` fields, then you should provide custom value.

**Comment by raimondases4b** [comment]
Okey great, thank you.
