### ISSUE TITLE
Tworzenie nowego produktu

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#6070]
Chaiałbym utworzyć nowy produkt na środowisku sandbox.

Co jest nie tak z tym requestem pod link: https://api.allegro.pl.allegrosandbox.pl/sale/product-proposal o TraceId: "a283273cd0e62020"?

Dostaję zwrotkę, ale nie wiem w czym jest problem:
{"errors":[{"code":"NotFoundException","message":"Not found","details":null,"path":null,"userMessage":"Funkcja niedostępna. Skontaktuj się z autorem aplikacji."}]}

**Comment by PrzemyslawLukanowski** [comment]
Prawidłowy adres endpointu to /sale/product-proposals (zabrakło "s" na końcu).

**Comment by marmited** [comment]
Faktycznie, dziękuję za pomoc, teraz jednak mam inne pytanie.

Tworząc produkt dostaję zwrotkę:

{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

TraceId: "705528209c249683"

Błąd jest dość ogólny, nie wiem co jest nie tak,

**Comment by marmited** [comment]
Jednak rozwiązałem problem. Dane były niepoprawnie serializowane.
