### ISSUE TITLE
Problem z aktualizacją cen, zwracany jest status SUCCESS pomimo niezmienionej ceny

### ISSUE THREAD

**Issue by kl-innosoft** [allegro/allegro-api#6071]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Został wysłany request, zgodnie z przykładem z poradnika https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-wielu-ofert-jednoczesnie.
Dodam, że obsługujemy w ten sposób set tysiecy aukcji i do tej pory większość ofert aktualizowała się prawidłowo.

```
curl --location --request PUT 'https://api.allegro.pl/sale/offer-price-change-commands/2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3' \
--header 'accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer XXX' \
--data-raw '{
    "modification":{
        "type":"FIXED_PRICE",
        "price":{ 
            "amount":"32.19",
            "currency":"PLN"
           }
        },
    "offerCriteria":[
        {
          "type":"CONTAINS_OFFERS",
          "offers":[
           {
             "id":"12102759726"
           }
          ]
        }
     ]
  }'
```
  
Odpowiedź z api: 201 Created
```
{
    "id": "2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3",
    "taskCount": {
        "total": 0,
        "success": 0,
        "failed": 0
    }
}
```

Został odpytany status
```
curl --location --request GET 'https://api.allegro.pl/sale/offer-price-change-commands/2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3' \
--header 'accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer XXX'
```

Odpowiedź z api: 200 OK
```
{
    "id": "2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3",
    "taskCount": {
        "total": 1,
        "success": 1,
        "failed": 0
    }
}
```

Zostały odpytane taski
```
curl --location --request GET 'https://api.allegro.pl/sale/offer-price-change-commands/2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3/tasks' \
--header 'accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer XXX'
```

Odpowiedź z api: 200 OK
```
{
    "tasks": [
        {
            "offer": {
                "id": "12102759726"
            },
            "message": "",
            "status": "SUCCESS",
            "scheduledAt": "2022-08-30T08:04:17.999Z",
            "finishedAt": "2022-08-30T08:04:17.983Z",
            "field": "price",
            "errors": []
        }
    ]
}
```

Po wykonaniu całego procesu kilkukrotnie automatycznie, dwukrotnie ręcznie aukcja zawiera cały czas nieaktualną cenę.
Identyfikatory commandów z ostatnich 12 godzin.
`2ba87b8d-d9f0-49ea-80f0-d2c42125bbc0`
`2ba87b8d-d9f0-49ea-80f0-d2c42125bbc2`
`2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3`

Czy coś jest nie tak z requestami, czy to coś po Waszej stronie?

**Comment by PrzemyslawLukanowski** [comment]
Przenalizowałem nasze logi i nie mogę potwierdzić występowania problemu. Poniżej przesyłam chronologicznie akcje wykonywane na ofercie:

- 2ba87b8d-d9f0-49ea-80f0-d2c42125bbc0 - 2022-08-30 02:03:39 - zmiana ceny na 32.19zł. Cena nie została zmieniona, ponieważ aktualna cena w ofercie to właśnie 32.19zł (w takim przypadku również zwrócimy status SUCCESS);
- 2ba87b8d-d9f0-49ea-80f0-d2c42125bbc2 - 2022-08-30 10:01:37 - zmiana ceny na 32.09zł. Cenę w ofercie zmieniliśmy od razu po otrzymaniu żądania;
- 2ba87b8d-d9f0-49ea-80f0-d2c42125bbc3 - 2022-08-30 10:04:17 - zmiana ceny na 32.19. Cenę w ofercie również zmieniliśmy od razu po otrzymaniu żądania;

Zmiany na ofercie powinny być widocznie maksymalnie do godziny, jednak zazwyczaj dzieje się to dużo szybciej, jak widać również w powyższych przykładach.

**Comment by kl-innosoft** [comment]
To nie jest zgodne z prawdą, ponieważ do godziny 10 cena wynosiła 28PLN. Zmieniła się po trzecim wykonanym commandzie.

**Comment by kl-innosoft** [comment]
Mamy również zrealizowany zakup tego poniżej ceny, która została rzekomo została zaktualizowana. Niestety nie jestem w stanie podać uuid commandów aktualizujących ceny sprzed zakupu.

**Comment by PrzemyslawLukanowski** [comment]
Wyjaśniam tę kwestię z zespołem odpowiedzialnym za usługę i wrócę z informacją, kiedy uda się ustalić więcej szczegółów. Wygląda na to, że problemem jest tutaj cena widoczna dla kupującego, ponieważ w danych oferty po stronie sprzedającego aktualizowała się ona zgodnie z przekazanymi wytycznymi.

**Comment by PrzemyslawLukanowski** [comment]
Otrzymałem informację, że cena widoczna dla kupującego wynikała z tego, że w danym okresie oferta znajdowała się w programie "Allegro Ceny". W takim przypadku powinniście otrzymać zwrot na billing w związku ze sprzedażą w tej kampanii.

**Comment by PrzemyslawLukanowski** [comment]
Tak, dokładnie - oferta była w programie od 12.08.22 do 30.08.22, do momentu kiedy cena została zmieniona za pomocą wspomnianej komendy.
