### ISSUE TITLE
Problem z dodaniem pliku faktury

### ISSUE THREAD

**Issue by Kuba-Id** [allegro/allegro-api#6075]
**Adres URL requesta:**
https://api.allegro.pl/order/checkout-forms/99b7ff70-26fc-11ed-af5f-634a18170286/invoices/2e5247d3-e3ea-4fd1-bcee-e30f2134d506/file

**Wysyłane nagłówki w requeście:**
Array
(
[0] => Accept-Language: pl
[1] => Authorization: bearer eyJhbGciOiJSUzI1NiIsIn ...
[2] => Accept: application/vnd.allegro.public.v1+json;charset=UTF-8
[3] => Content-Type: application/pdf
)

**Metoda requesta:**
PUT

**Request (zawartość pliku PDF):**
%PDF-1.6
%����
1 0 obj
<< /Metadata 3 0 R /Names 4 0 R /Pages 5 0 R /Type /Catalog >>
endobj
2 0 obj
<< /CreationDate <9756c1d56143198ec6f1d81c937c9f34fe61aebf4b5e2f> /Creator <2d93f392531729dff5b3e940a22cae2cd5219cf4> /ModDate <9756c1d56143198ec6f1d81c937c9f34fe61aebf4b5e2f> /Producer <943cbfc5141946c581b28a5fcb3dda22ec7fa9a8> >>
endobj
3 0 obj
<< /Subtype /XML /Type /Metadata /Length 539 /Filter /FlateDecode >>...

**Odpowiedź:**
{"success":false,"errors":{"api":"EMPTY-ATTACHMENT. Attachment for given order [99b7ff70-26fc-11ed-af5f-634a18170286] and invoice [2e5247d3-e3ea-4fd1-bcee-e30f2134d506] must not be empty"}}

**W ciele requesta wczytany został plik:**
curl_setopt($ch, CURLOPT_POSTFIELDS, file_get_contents(plik_pdf_sciezka));

Plikiem jest faktura. Sprawdzałem zawartość pliku, to normalny dokument PDF, mogę go otworzyć, zawartość pokazuje się na ekranie.

Co jest zatem nie tak? Skąd odpowiedź: 
**Attachment must not be empty**

Będę wdzięczny za pomoc :-)

**Comment by Lukasz-Zurek** [comment]
Sprawdziłem nasze logi i wg. nich przekazujesz nieprawidłowy plik, który waży 0 bajtów, co powoduje, że nasza usługa odpowiedzialna za faktury odczytuje ten plik jako "EMPTY-ATTACHMENT".

**Comment by Kuba-Id** [comment]
Faktycznie, sprawdziłem, był warunek, który eliminował wysyłanie pliku! Dziękuję! Wątek do zamknięcia!
