### ISSUE TITLE
Jak zacząć

### ISSUE THREAD

**Issue by xcmspl** [allegro/allegro-api#6076]
Planuje stworzyć integrację dla sklepu internetowego w postaci modułu korzystającego właśnie z Allegro REST Api. Chciałbym aby moduł działał z minimalnym angażowaniem użytkownika. Czyli klik i np. oferta jest już na allegro.
Chciałem zadać kilka pytań. 
Czy za pomocą REST API można zbudować tego typu moduł (który nie wymaga przekierowywania, logowania)?
Którego rodzaju autoryzacji użyć do tego celu? 

Z góry dziękuję za odpowiedzi :)

**Comment by Lukasz-Zurek** [comment]
Wszystkie metody autoryzacji w naszym publicznym API wymagają zalogowania się użytkownika na koncie w Allegro.pl. W związku z czym nie jestem w stanie wskazać metody, która spełniłaby Twoje wymagania co do braku logowania/przekierowania, zatem decyzja co do preferowanej metody należy do Ciebie.

Metody autoryzacji w Allegro API opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#wstep). Jak widać - w każdym przypadku wymagana jest autoryzacja użytkownika. Różnice są tylko w sposobie autoryzacji, ale i nie tylko - o czym świadczy metoda [Device Flow](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow), która przeznaczona jest do aplikacji typu device - bez interfejsu graficznego.
