### ISSUE TITLE
Numery przewozowe One by Allegro a Allegro One Box (UPS)

### ISSUE THREAD

**Issue by janselato** [allegro/allegro-api#6078]
Dzień dobry,
czy istnieje jakieś rozróżnienie w numeracji listów przewozowych pomiędzy nadaniami poprzez One by Allegro, a przesyłkami zabieranymi przez UPS (Allegro One Box)? Może zawierają jakąś sumę kontrolną po której jestem wstanie ocenić po numerze jaki to przewoźnik?

**Comment by PrzemyslawLukanowski** [comment]
Aktualnie nie ma takiej możliwości. Mamy w planach zwracanie dodatkowego numeru przewozowego przewoźnika, który jest na kodzie kreskowym - po tym będzie można rozpoznać przesyłki UPS. Nie jestem jednak w stanie na tę chwilę ocenić, kiedy dokładnie to się wydarzy.
