### ISSUE TITLE
Funkcja `wystaw podobną` dla zakończonej licytacji

### ISSUE THREAD

**Issue by Uriziel01** [allegro/allegro-api#608]
Witam,
posiadam aukcje typu licytacja która została zakończona bez ofert kupna, widnieje teraz w zakładce `niesprzedane` a także jest zwracana przez metodę starego API `doGetMyNotSoldItems`. Aukcja ta nie może być wystawiona ponownie gdyż nie posiada parametrów które w tym czasie stały się obowiązkowe więc próba wystawienia aukcji z API kończy się mailem `Ponowne wystawienie Twoich przedmiotów nie powiodło się`.

Mam z związku z powyższym kilka pytań:

1. Czy link `wystaw ponownie` w treści maila (np. `https://allegro.pl/offer/7539576987/similar/`) różni się czymkolwiek od ponownego wystawienia na zasadzie pobrania wszystkich pól oferty a następnie stworzenia nowej licytacji z tamtych danych metodami `GET /sale/offers/{offerId}` oraz `POST /sale/offers`

2. Po adresie widzę że link ten jest jednaki z kliknięciem `WYSTAW PODOBNĄ` z poziomu interfejsu Allegro?

3. Czy ponownie wystawiona w ten sposób (lub w jakikolwiek innych) licytacja przestanie być zwracana przez `doGetMyNotSoldItems`?

4. Jeśli nie to czy istnieje metoda na to aby daną niesprzedaną licytację oznaczyć jako wystawioną ponownie i wykluczyć z listy ofert zwracanych przez `doGetMyNotSoldItems`?

5. Zasadniczo chodzi o sposób w jaki możemy niesprzedaną licytację z brakującymi parametrami wystawić ponownie ale ukryć ja z niesprzedanych tak aby jeśli pracownik wejdzie tam ponownie nie doszło do zduplikowania aukcji przez kolejne wystawienia.

Założyłem nowe issue gdyż w poprzednim temat przewodni został moim zdaniem wyczerpany.

**Comment by MaciejPotepa** [comment]
Dzień dobry

Zadałeś dużo trafnych pytań. Potrzebuję trochę czasu żeby zebrać informację. Proszę cierpliwość, badam temat.

**Comment by Uriziel01** [comment]
Jakiekolwiek postępy w tej sprawie? Nie ukrywam że czekam na tę odpowiedź żeby kontynuować prace z klientem.

**Comment by Uriziel01** [comment]
Przepraszam za ton ale PROSZĘ spojrzeć dokładniej na zgłoszony przeze mnie problem zamiast odpisywać skopiowanymi regułkami. Dziękuję.

**Comment by MaciejPotepa** [comment]
@Uriziel01 Nie ma problemu, nie musisz przepraszać. To mój błąd w 'rozumowaniu'. Mylnie założyłem, że chodzi Ci o oferty, dużo użytkowników nazywa oferty aukcjami ze względu na stare przyzwyczajenia i z automatu założyłem, że piszesz o modelu ofertowym. 

Z założenia, aukcji się nie wznawia tylko wystawia ponownie. Wynika to z wielu zależności, które definiują różnicę w modelu ofertowym i aukcyjnym. 
Aukcji nie wznowisz nawet jeżeli będziesz miał uzupełnione parametry, musisz wystawić jako nową ofertę, uzupełnić parametry i dopiero finalnie wystawić. 

Model aukcyjnym nie jest głównym formatem sprzedażowym w Allegro, jest obarczony wieloma corner case'mi, których adresowanie nie jest priorytetem. 

Przepraszam, że czekałeś na odpowiedź tak długo, i że nie ma tu zbyt pozytywnych informacji.
