### ISSUE TITLE
Create offer based on product access denied exception

### ISSUE THREAD

**Issue by furkanakharman** [allegro/allegro-api#6081]
Greetings,
Even though **allegro:api:sale:offers:write** scope is allowed and account I use is already registered as a company account I am getting OfferAccessDeniedException while using **/sale/product-offers** service.

We registered account using [this link](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty)

Account id is 105397693

Help appreciated!

**Comment by PrzemyslawLukanowski** [comment]
Hi, you registered a regular account, not a company. Please use [this link](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) and select "Change to Business Account."

**Comment by furkanakharman** [comment]
Thank you for the quick answer however Change to business account button seems to be disabled. Any idea why that might happen?

**Comment by PrzemyslawLukanowski** [comment]
Could you please in this case try to choose "Zmień na konto firmowe" from [this link](https://allegro.pl.allegrosandbox.pl/biznes)?

**Comment by furkanakharman** [comment]
Unfortunately still not able to click it.

**Comment by PrzemyslawLukanowski** [comment]
I'm verifying this issue with our Team responsible for this service. You can also try to create a new account (but this time as a company type from the beginning). Sorry for the inconvenience.

**Comment by furkanakharman** [comment]
Thank you, is there an ETA for this problem to be resolved?

**Comment by PrzemyslawLukanowski** [comment]
I’ve just received information from our team that conversion of an account on Sandbox is not possible for users from countries other than Poland. Once again, sorry for the inconvenience, but the only way to solve this issue right now is to create a new company account.

**Comment by furkanakharman** [comment]
Alright, thanks for the help.
