### ISSUE TITLE
Błąd pickup.name - musi pasować do wzorca "^[\p{L}0-9 .,:;()/*#`'"_-]*$". - Wysyłam z Allegro 

### ISSUE THREAD

**Issue by wap18** [allegro/allegro-api#6082]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy próbie wygenerowania etykiet dla WzA Allegro One UPS dostaje błąd: 
Allegro returned error: Field: pickup.name - musi pasować do wzorca "^[\p{L}0-9 .,:;()/*#`'"_-]*$".
Prośba o wsparcie którego pola w request może dotyczyć błąd

**Comment by Lukasz-Zurek** [comment]
Komunikat świadczy o tym, że w polu **"pickup.name"** przekazujesz niedozwolony znak. Abym mógł dokładnie zweryfikować Twojego zgłoszenie, potrzebny mi będzie commandId dla wspomnianego żądania. Zwróć jednak uwagę na przekazywane dane w tym konkretnym polu. Docelowo powinno tam być imię i nazwisko.

**Comment by wap18** [comment]
Dziękuje za pomoc, namierzyłem problem.
