### ISSUE TITLE
Problem ze zmianą konta na firmowe (Sandbox)

### ISSUE THREAD

**Issue by Zimoslaw** [allegro/allegro-api#6083]
Witam,

posiadam na sandboxie Allegro konto do testowania połączenia oprogramowania Soteshop z API Allegro. Wielokrotnie próbowałem już zweryfikować dane konta do wypłat w celu zmiany konta na firmowe i przywrócenia możliwości wystawiania ofert. Jednakże za każdym razem otrzymuję maila z informacją, że nie można było zweryfikować danych: "Dane Twojej firmy nie zgadzają się z danymi konta do wypłat.".

W związku z tym, czy mógłbym prosić o ręczną zmianę mojego konta na firmowe? Mój login to: test-serwis-sote

Dziękuję i pozdrawiam
Jakub Niewiarowski

**Comment by Lukasz-Zurek** [comment]
Udało mi się w pełni aktywować Twoje konto, zmienić je na firmowe i pozytywnie zweryfikować. Możesz już na nim działać.

**Comment by Zimoslaw** [comment]
Dziękuję
