### ISSUE TITLE
Two API issues

### ISSUE THREAD

**Issue by niuniubaba** [allegro/allegro-api#6084]
1、How to handle the following errors？
http_response_400 Invalid request. Please contact the application author.
2、Use 【/sale/product-offers】 to create offer based on product, if offers can't linked to the catalog,  new offers Is it "active" status？

**Comment by MaciejFrackowiak** [comment]
1. If you get error 400, it means that your request is invalid - you have to check its structure according to resource documentation;
2. If we do not recognize a product from our database, we will create a new one - and yes, the offer will be in an active mode - you can read about it [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product-via-sale-product-offers-resource).
