### ISSUE TITLE
POST sale/product-offers ConstraintViolationException.ValidCompatibilityTable

### ISSUE THREAD

**Issue by Radeq** [allegro/allegro-api#6085]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other
 - [ ] 
Dzień dobry,

Mam problem z zasobem POST sale/product-offers - chodzi o wystawienie oferty powiązanej z istniejącym produktem Allegro.

Nie podaję sekcji tech doc / pasuje do.

`POST sale/product-offers || trace-id:8dae917ef2e3d193`

```
    +"code": "ConstraintViolationException.ValidCompatibilityTable"
    +"message": "Selected compatibility table has different type than supported in offer category."
    +"details": "ConstraintViolationException.ValidCompatibilityTable"
    +"path": "compatibilityTable"
    +"userMessage": "Typ wskazanej sekcji "Pasuje do" nie jest wspierany w kategorii przypisanej do oferty."
```

Proszę o pomoc.

**Comment by MaciejFrackowiak** [comment]
Potwierdzam, że do produktu dołączona jest niewłaściwa wersja Pasuje do, czego efektem finalnym jest komunikat błędu. Obecnie działamy nad rozwiązaniem problemu, wrócę z odpowiedzią.

**Comment by MaciejFrackowiak** [comment]
Od wskazanego produktu odpięta została sekcja Pasuje do, teraz bez przeszkód wystawisz już ofertę.
