### ISSUE TITLE
Usługa wielopaczka nie jest dostępna u tego przewoźnika

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#6086]
Witam,

Zauważyłem taką nieścisłość podczas próby wygenerowania 2 paczek w Allegro One Box (One Kurier) dostawa dzisiaj otrzymuje komunikat "Usćuga wielopaczka nie jest dostępna u tego przewoźnika" natomiast w zamówieniu otrzymuje w polu delivery_number_of_packages  liczbę 2. Zamówienie jest ze SMART-em. Jeżeli w takim przypadku może być tylko 1 paczka to raczej powinno być to zablokowane na etapie składania zamówienia przez klienta. Co sprzedawca ma zrobić w takiej sytuacji?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj mi szczegóły tego zlecenia - commandId operacji.

**Comment by krzysda** [comment]
id => 6315bb62-6315-6315-6315-6315bb622de7 serviceId =>19205483

**Comment by MaciejFrackowiak** [comment]
W opisanej sytuacji musisz wykonać dwa osobne requesty [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel), aby wygenerować dwie osobne paczki zgodnie z zamówieniem. Usługa wielopaczki nie jest dostępna dla Allegro One.

**Comment by krzysda** [comment]
I wtedy zostanie to prawidłowo rozliczone z Allegro SMART ?

**Comment by MaciejFrackowiak** [comment]
Tak.
