### ISSUE TITLE
Długość stringa AllegroOrder.MessageToSeller

### ISSUE THREAD

**Issue by polakmaciej** [allegro/allegro-api#6087]
Dzień dobry 
Pobieram przez API allegro obiekt AllegroOrder.MessageToSeller. Samo pobieranie działa, ale z niezrozumiałych dla mnie powodów nie da się zwalidować istnienia tego stringa. To znaczy, w przypadku braku wiadomości (potwierdzone przez stronę) nie działa żadne String.IsNullOrEmpty(). Jakież było moje zdziwienie, kiedy okazało się, że przy pobraniu 4 różnych stringów (które na stronie były puste bo nie było wiadomości od kupującego) miały one 4 różne długości: 19, 26, 41, 32. Jak zwalidować istnienie wiadomości od kupującego i czemu one mają różne długości?

**Comment by PrzemyslawLukanowski** [comment]
W przypadku braku wiadomości ze strony kupującego w danych zamówienia, w polu messageToSeller, zawsze zwrócimy `null` i powinna być to stała długość. Czy możesz przesłać nam przesłać [za pomocą formularza](https://allegro.pl/pomoc/kontakt) przykładowe logi wraz z ID zamówień, gdzie zwróciliśmy rozbieżne informacje? W zgłoszeniu dopisz, że dane dotyczą wątku #6087 na GitHubie.

**Comment by polakmaciej** [comment]
Dzień dobry

Jak mogę to zrobić? Formularz dotyczący API Allegro przekierowuje tylko do GitHuba.

**Comment by PrzemyslawLukanowski** [comment]
Proszę wybrać [dowolną inną opcję](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) - jeśli w zgłoszeniu uwzględnisz, że dane dotyczą wskazanego wątku na forum, załącznik trafi do nas.
