### ISSUE TITLE
Rodzaj tokenu a metody, które go wymagają

### ISSUE THREAD

**Issue by arvato-damkos** [allegro/allegro-api#6088]
Występuje problem:
 - [X] z logowaniem lub autoryzacją / with login or authorization

Dla metod, które potrzebujemy, wymagana jest autoryzacja poprzez bearer-token-for-user, które z kolei można uzyskać na dwa sposoby. Problem jest taki, że w obu przepływach potrzebna jest ingerencja użytkownika. Nasza aplikacja jest, można nazwać, proxy pomiędzy jednym systemem, a API spedytorów. Ta aplikacja dostaje dane, które ma odpowiednio przygotować i wysłać request do wybranego przewoźnika i ingerencja użytkownika tutaj praktycznie nie zachodzi i zachodzić nie może. Próbowaliśmy wykorzystać **Device Flow**, ale na pewnym etapie ktoś musi fizycznie wejść w link i akceptować możliwość wygenerowania tokenu za pomocą **device_code**. Jaka jest możliwość w naszym przypadku, aby uzyskiwać i wykorzystywać token bez ingerencji użytkownika do requestów, np. https://developer.allegro.pl/documentation#operation/createNewParcel i innych (wszystkie dotyczą tworzenia przesyłki/pobierania etykiety/pobierania protokołu nadania/itp), które wymagają **bearer-token-for-user**? Czy jest/będzie możliwość używania **bearer-token-for-application**? Jeśli nie to jak w naszym przypadku możemy wdrożyć komunikację między naszą aplikacją a waszym API?

**Comment by PrzemyslawLukanowski** [comment]
Niestety nie ma tutaj możliwości dla bearer-token-for-application, ponieważ jest to autoryzacja pozbawiona kontekstu użytkownika. W przypadku tworzenia paczek dzieje się to w ramach konta danego usera, dlatego musi on wcześniej zautoryzować aplikację, aby ta mogła wykonywać czynności w jego imieniu. Jest to krok, którego nie da się pominąć. Ingerencja użytkownika może nastąpić tylko na samym początku, następnie możecie wykorzystać [mechanizm refresh tokenów](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#przedluzenie-waznosci-tokena), aby przedłużać ważności tokenów.
