### ISSUE TITLE
Problem z pobraniem eventów dotyczących zamowienia

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#6089]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Witam,

Przy użyciu endpointu https://api.allegro.pl/order/events nie dostaje zdarzeń związanych z zamówieniem 36e0c490-2543-11ed-9701-33e9792bb288 na koncie eltrox_pl. Jako parametry przekazuje from: 1661517145850880 i limit: 1000, a potem zwiększam from, az dojde ze zdarzeniami do dnia dzisiejszego.
Wg informacji w portalu Allegro platność do tego zamowienia nastapila 26 sierpnia o 15:30, wiec przynajmniej zdarzenie, ze zamowienie jest gotowe do realizacji powinno sie zmiescic w tym zakresie.

**Comment by PrzemyslawLukanowski** [comment]
Nie mogę potwierdzić wystąpienia problemu, dla wskazanego zamówienia zwróciliśmy trzy eventy:
```
1661520629376105
 "type": "BOUGHT",
 "occurredAt": "2022-08-26T13:30:18.359Z"
```
```
1661520630934020
"type": "FILLED_IN",
"occurredAt": "2022-08-26T13:30:18.359Z"
```
```
1661520636571747
"type": "READY_FOR_PROCESSING",
"occurredAt": "2022-08-26T13:30:20.701Z"
```

W API zwracamy czas uniwersalny ("czas Zulu").

**Comment by Himon-SYNCRAFT** [comment]
Dziękuję za pomoc. Udało mi się rozwiązać problem.
