### ISSUE TITLE
Nie działają płatności na sandboxie ?

### ISSUE THREAD

**Issue by mzawodzinski** [allegro/allegro-api#609]
Witam,
czy występują jakieś problemy z płatnościami na  sandboxie ?
Próbowałem wybierać w szybkich płatnościach różne banki ale zawsze dostaję "Płatność się nie udała.".
Płatność kartą nie działa wcale.
Jak dobrze pamiętam to zawsze na tym etapie było przekierowanie na sandboxowe payu z "zielonym i czerwonym przyciskiem".

ps. 
wydaje mi się że komunikat "Płatność nie udała się" byłby bardziej po polsku.

**Comment by LukaszKorek** [comment]
Dziękuję za zgłoszenie. Zajmiemy się problemem. Za utrudnienia przepraszam.

**Comment by mzawodzinski** [comment]
Dzisiaj już działa.
