### ISSUE TITLE
Automatyczne odłączenie produktu od oferty

### ISSUE THREAD

**Issue by dol1234** [allegro/allegro-api#6090]
Często zdarza się, że produkt podłączony do oferty zostaje od niej odłączony. 
Zgaduje, że wynika to z rozbieżności w parametrach produktu oraz oferty.
Prosiłby o podanie logiki jaką kierujecie się podczas procesu rozłączania. 
Czy nazwa oferty ma znaczenie? Czy pod uwagę brane są wszystkie parametry, czy też tylko te wymagane?

**Comment by MaciejFrackowiak** [comment]
Proces ten odbywa się poza API Allegro, dlatego aby poznać szczegółowe informacje proszę skontaktuj się bezpośrednio z obsługą serwisu poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by dol1234** [comment]
Kontaktowałem się wiele razy i nigdy nie otrzymałem tych informacji.

**Comment by MaciejFrackowiak** [comment]
Jak wspomniałem proces ten odbywa się całkowicie poza nami tj. API Allegro i co kluczowe samo API nie ma niego wpływu, dlatego trudno nam tu wyjaśniać kwestie, na które wpływu nie mamy.

**Comment by dol1234** [comment]
Skoro przypisuje to przez API i jest to magicznie rozłączane, to wydaje mi się, że powinniście chociaż znać powód. Domyślam się, że nie jestem pierwszą osobą która o to pyta - czy naprawdę nie możecie skontaktować się z kimś ze swojej firmy i o to zapytać?

**Comment by MaciejFrackowiak** [comment]
Proces rozłączania odbywa się poza API i dlatego nie sposób nam odpowiedzieć, co w danym przypadku było niezgodne z produktem. Zgodnie z [ogólnodostępnymi informacjami](https://allegro.pl/dla-sprzedajacych/asortyment/katalog-produktow-allegro/baza-wiedzy#na-jakiej-zasadzie-sa-laczone-produkty-w-katalogu-) weryfikowane są parametry m.in. numer GTIN, Marka, Producent, Kod producenta.

**Comment by dol1234** [comment]
To informacje dotyczące automatycznego powiązania oferty z produktem. Niestety w moim przypadku pomimo tego, że powyższe informacje są zgodne w ofercie oraz produkcie oferty zostają odłączone. 
Wygląda na to, że w większości przypadków parametry oferty muszą jeden do jednego odpowiadać tym z produktu (mam przypadki odłączenia nawet wtedy, gdy wszystkie parametry z własciwością Required/RequiredForProduct są identyczne).

**Comment by MaciejFrackowiak** [comment]
W artykule wskazałem tylko na część czynników, które brane są pod uwagę podczas łączenia, a zatem i w odwrotnym procesie również muszą być w pewnym stopniu brane pod uwagę.
