### ISSUE TITLE
Nieprzeniesione zamówienia Allegro>Wapro Aukcje

### ISSUE THREAD

**Issue by PatrykBLOW** [allegro/allegro-api#6091]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

:beetle: **Opis / Description**

Dzień dobry, 
Zauważaliśmy iż w niedzielę, 4 wrz 2022, około godziny 21:47 nie przeniosło się nam około 50 zamówień do Wapro Aukcji. 
Nie zauważyliśmy jakiejś zależności jeżeli chodzi o te zamówienia. Bardziej obstawiamy jakąś przerwę w przesyłaniu zamówień przez API (godzina 21:47-22:00).
Niestety w późniejszych dniach te zamówienia dalej się nie przeniosły. Według pracownika Wapro nie jest możliwe ponowne przesłanie paczki API z zamówieniami które już zostały przesłane. 
Czy jest możliwość weryfikacji tych zamówień, w celu uniknięcia takich sytuacji w przyszłości? 
Dodam także ze w tamtym tygodniu bardzo często spotykaliśmy się z sytuacją zdublowanych zamówień w Wapro Aukcjach, przez co nie dało się nic z nimi zrobić. 
Przykładowe zamówienie: 
159eefc1-2c8a-11ed-bcf8-71754531f768

**Comment by MaciejFrackowiak** [comment]
Nie potwierdzam problemów z dostępnością zamówień w API Allegro. Również wskazane zamówienie jest w pełni dostępne. API Allegro nie ogranicza dostępu do zamówień tj. można je pobrać dowolną ilość razy, to wyłącznie ograniczenie wskazanego oprogramowania. W tym miejscu sugeruję ponowny kontakt z dostawcą oprogramowania, ponieważ jako Allegro nie mamy żadnego wpływu na funkcjonowanie aplikacji zewnętrznej.
