### ISSUE TITLE
Brak numeru zamówienia (order.id) w /billing-entries dla rekordów typu CPF (opłata za monety)

### ISSUE THREAD

**Issue by javaguru-pl** [allegro/allegro-api#6092]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Opis problemu:
Metoda billing-entries zwraca pozycje kosztów/billingu, W odpowiedzi występuje też pole order.id, które zwraca numer zamówienia dla kosztów dotyczących zamówienia (np. prowizja od sprzedaży). Jednakże dla kosztów typu CPF (opłata za monety) - pole z numerem zamówienia NIE występuje (pomimo że dotyczą one konkretnego zamówienia). Czy możemy Państwa prosić o naprawę tego błędu?
Z góry dziękuję za pomoc.

Przykładowy cURL:
https://api.allegro.pl/billing/billing-entries?limit=100&occurredAt.gte=2022-09-05T05:50:00.000Z&occurredAt.lte=2022-09-05T05:52:00.000Z

Trace-id:
7277a8eecd7eaf57

**Comment by MaciejFrackowiak** [comment]
To nie jest błąd - w serwisie WWW przy operacji "Opłata za monety" podajemy wyłącznie numer oferty, nie ma tam również numeru zamówienia.
