### ISSUE TITLE
Literówka na portalu

### ISSUE THREAD

**Issue by Deletor** [allegro/allegro-api#6093]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [x] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

[Środowisko testowe](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe) -> Jak to działa -> przez REST API (za pomocą https://api.allegro.pl.allegrosandbox.pl)/. W link wkradł się nawias, przez co url nie działa.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, poprawiłem już link na stronie. Swoją drogą, jest to adres do wywoływania metod w REST API Allegro, nie zostaniesz w tym przypadku przeniesiony w żadne konkretne miejsce w ramach przeglądarki internetowej.
