### ISSUE TITLE
Jak można rozwiązać ten problem w ustawianiach na mojej stronie Allegro 

### ISSUE THREAD

**Issue by KevinKati** [allegro/allegro-api#6095]
Dzień Dobry, 

Mam problem ze wtyczką WooCommerce Allegro.

Jak można rozwiązać ten problem w ustawianiach na mojej stronie Allegro ? 
Czy w ustawieniach Allegro po stronie woocommerce ? 
Oraz proszę podpowiedzieć co to za link w edycji produktu na WooCommerce --> Enable link to allegro oraz CTA allegro link ?
Co mam odhaczyć ?
Czego dotyczy problem: Wtyczka WooCommerce Allegro nie łapie, że towar wystawiony na moim wordpress pochodzi z hurtowni (za pośrednictwem API). I nie daje nakaz pobrać zakupiony towar z hurtowni. 
Po tym, jak klient zapłacił za produkt na Allegro, moja strona WooCommerce widzi zamówienie: nazwa produktu, płatność. Ale na mojej stronie WooCommerce w szczegółach zamówienia w zakładce zamówienia jest napisane 'There are no details for this order' i produkt cyfrowy nie jest przekazywany do kupującego. 
Oznacza to, że wtyczka WooCommerce Allegro nie może powiązać konkretny zakup z odpowiednim produktem z hurtowni. 
Czy można rozwiązać ten problem po stronie Allegro ?
Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
W opisanej sytuacji musisz skontaktować się z dostawcą wykorzystywanego oprogramowania, ponieważ jako Allegro nie mamy żadnego wpływu na funkcjonalności aplikacji zewnętrznej. W ustawieniach Allegro nie dokonasz zmian we wspomnianej wtyczce.

**Comment by KevinKati** [comment]
![ALLEGRO](https://user-images.githubusercontent.com/112970356/188832915-3bf9334a-22ff-4764-9b1a-0fe382ec7f95.png)
Jeszcze proszę podpowiedzieć co to za linki w edycji produktu na WooCommerce:
1) Enable link to allegro 
2) oraz CTA allegro link ?
Co robią te linki, co mam wpisać ?

**Comment by MaciejFrackowiak** [comment]
To również pytania stricte do autorów wtyczki.

**Comment by KevinKati** [comment]
Z Pana doświadczenia, czy są  inne wtyczki from Allegro to Wooconnerce, oprócz WooCommerce Allegro PRO (wphocus) oraz Allegro Woocommerce ( wpdeck) ?
Jakie mogą być inne warianty integracji Allegro z woocommerce ?

**Comment by MaciejFrackowiak** [comment]
Jako Allegro nie jesteśmy twórcą żadnej wtyczki czy też oprogramowania bazującego na API Allegro. Dlatego też prowadzimy wsparcie w zakresie wykorzystania zasobów API Allegro, nie zaś oprogramowania wykorzystującego jego zasoby. Tym samym nie mogę Ci udzielić tu żadnych wskazówek, być może któryś z forumowiczów będzie mógł Ci udzielić rad.
