### ISSUE TITLE
GIF - miniaturka i obrazy w aukcji

### ISSUE THREAD

**Issue by j4n3cz3k** [allegro/allegro-api#6096]
Dzień dobry
Tak jak w tytule postu - w jaki sposób można wrzucić plik z rozszerzeniem .gif?
W taki sposób, żeby była widoczna animacja?
**Przykład:**
https://allegro.pl/oferta/gramofon-z-glosnikami-winyl-klasyka-gratis-lp-8779775221
Czy potrzebne są do tego jakieś specjalne narzędzia?
Czy można użyć do tego BaseLinkera?

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Nie ma obecnie takiej możliwości. Wskazana przez Ciebie oferta została wystawiona w czasach, gdy taka możliwość istniała.
