### ISSUE TITLE
Występujące czasem kody błędu 503 przy próbie odświeżenia tokena

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#6097]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Czy coś wiadomo w tej kwestii?
Odpowiedzi ze statusem 503 jest stosunkowo niewiele, ale być może warto to zgłosić.

**Comment by PrzemyslawLukanowski** [comment]
Na tę chwilę nie widzimy niczego niepokojącego w naszych usługach, więc aby zweryfikować te konkretne przypadki, będziemy potrzebować więcej szczegółów. Możesz nam przesłać przykładowe logi za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=0cad5ed6-ca26-4669-8ff0-6a7da503fe80&subjectId=8b7d668e-6f52-47e4-8c6b-cfb5e985789a), uwzględniając przy tym client_id, user_id oraz datę, kiedy wystąpił problem (dopisz, że dane dotyczą wątku #6097 na GitHubie).

**Comment by tomasz-grzesik** [comment]
Dzięki. Na ten moment to promil tego typu żądań, ale zauważam lekki trend rosnący. Sprawdzę jeszcze przez kilka najbliższych dni i w razie czego doślę szczegóły.

**Comment by tomylee0** [comment]
Podepnę się tylko informacyjnie, że dziś gdzieś między 14:00 a 14:30 mieliśmy te same problemy. Ale potem zaczęło działać.
