### ISSUE TITLE
request PUT do zasobu https://api.allegro.pl/sale/offer-modification-commands/  Wykonuje się poprawnie, zgodnie z oczekiwaniem, ale odpowiedź zawiera same 0 w podsumowaniu

### ISSUE THREAD

**Issue by centrumelektroniki** [allegro/allegro-api#6098]
Dzień dobry, 
request PUT do zasobu https://api.allegro.pl/sale/offer-modification-commands/
z następującymi parametrami:

Array
(
    [offerCriteria] => Array
        (
            [0] => Array
               (
                   [offers] => Array
                       (
                           [0] => Array
                               (
                                   [id] => 12589569997
                               )
                       )
                   [type] => CONTAINS_OFFERS
               )
       )

   [modification] => Array
       (
           [promotion] => Array
               (
                   [bold] => false
                   [departmentPage] => false
                   [emphasized] => false
                   [emphasizedHighlightBoldPackage] => false
                   [highlight] => false
               )
       )
)

Wykonuje się poprawnie, zgodnie z oczekiwaniem, ale odpowiedź zawiera same 0 w podsumowaniu
{"id":"e2c6a8ae-a49b-42e2-98f8-b5de571b6a7e","taskCount":{"total":0,"success":0,"failed":0}}

**Comment by PrzemyslawLukanowski** [comment]
Wspomniany zasób działa asynchronicznie, dlatego aby uzyskać biężący status wykonania zadania, skorzystaj z [GET sale/offer-modification-commands/{commandID}/tasks.](https://developer.allegro.pl/documentation#operation/getTasksUsingGET)
