### ISSUE TITLE
Wystawianie aukcji na wordpressie

### ISSUE THREAD

**Issue by pachnacachatka** [allegro/allegro-api#6099]
Wystawianie aukcji na wordpressie
Wcześniej nie mieliśmy tego problemu, jednak po,, udogodnieniach" allegro nie możemy wystawić aukcji na allegro przez wordpress. komunikat jaki się pojawia to:
Aukcja nie została wystawiona: Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą.
Aukcja nie jest poprawna: Miejscowość musi składać się od 1 do 50 znaków. Wskazany kod pocztowy jest nieprawidłowy. Podaj kod w formacie XX-XXX. Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą. Brak uzupełnionych danych o dostawie.
Proszę o pomoc co możemy z tym zrobić?

**Comment by MaciejFrackowiak** [comment]
Komunikat, o którym wspominasz związany jest z wprowadzeniem od 1 sierpnia 2022 wymogu połączenia oferty z produktem podczas wystawiania nowej oferty - informowaliśmy o tym w [poście](https://github.com/allegro/allegro-api/issues/5961). Pozostałe komunikaty to również konsekwencja braku wymaganych danych dla oferty. W opisanej sytuacji sugeruję kontakt z autorem aplikacji, ponieważ my jako Allegro nie jesteśmy twórcą tego rozwiązania.
