### ISSUE TITLE
Metoda doGetItemsInfo  i itEndingInfo != 1

### ISSUE THREAD

**Issue by rtnet-pl** [allegro/allegro-api#61]
Mam taki problem, który jest trudny do uchwycenia i zreplikowania.
Bardzo sporadycznie dla niektórych itemów metoda doGetItemsInfo  w wartości itEndingInfo zwraca wynik różny od 1, pomimo tego, że oferta trwa nadal.
Przykłady takich ofert:
6953378529
7169451638
7169451861
7169451949
6640597440
6809847332
6809845836
6592907978
Zwykle jeśli item zostanie odpytany ponownie po krótkim czasie, wynik jest już prawidłowy (1).
Czy mogę prosić o weryfikację?

**Comment by DINK74** [comment]
prawdopodobnie zdarza się to w czasie cyklu "odświeżania" aukcji - aukcja przez kilka-/kilkanaście minut jest "unstable" - np. znika z listingu

**Comment by TomekKaczmarek** [comment]
@rtnet-pl niestety - tak właśnie jest. Mimo, że oferta jest wystawiona w formacie do wyczerpania przedmiotów, co 10 lub 30 dni następuje wznowienie cyklu. W tym czasie może się zdarzyć, ze przez API zwrócimy informacje, że oferta jest zakończona.

**Comment by rtnet-pl** [comment]
Dziękuję serdecznie za odpowiedź. Przekazuję do Klienta.
Czy jest jakaś możliwość, abyśmy po stronie aplikacji dodatkowo weryfikowali tą wartość w sposób niezawodny? np. w relacji z itEndingTime?
Wykrycie zamknięcia oferty ma w aplikacji dalsze konsekwencje i musimy być na 100% pewni że faktycznie nastąpiło.

**Comment by TomekKaczmarek** [comment]
Obawiam się, że nie. Przynajmniej na teraz. 
Ogólnie, można zwrócić uwagę na cykliczność tego stanu:
- dla ofert w formacie Kup teraz będzie się powtarzał co 10 dni
- dla ofert w formacie Sklep będzie się powtarzał co 30 dni.

**Comment by manhunto** [comment]
> Obawiam się, że nie. Przynajmniej na teraz.
> Ogólnie, można zwrócić uwagę na cykliczność tego stanu:
> 
> * dla ofert w formacie Kup teraz będzie się powtarzał co 10 dni
> * dla ofert w formacie Sklep będzie się powtarzał co 30 dni.

Ile może trwać ten proces? W sensie przez jaki czas (co 10, 30 dni) aukcja widnieje jako zakończona. Prosiłbym o średnią i/lub maksymalną wartość. Chciałbym u siebie wprowadzić jakieś okno czasowe na tę ewentualność.

**Comment by PawelTaberski** [comment]
@manhunto Ciężko określić dokładny czas, bo oferta wznawiana jest automatycznie, jednakże odstęp 5 minutowy wydaje się być wystarczający. Ale tak jak w przypadku każdej zmiany w ofercie może maksymalnie potrwać do godziny.
