### ISSUE TITLE
[SOAP] Wystawianie aukcji z dużymi zdjęciami

### ISSUE THREAD

**Issue by manhunto** [allegro/allegro-api#610]
Dzień dobry, 
probując wystawić aukcję z dużymy zdjęciami. Dostałem początkowo exception z komunikatem: `error in msg parsing: XML error parsing SOAP payload on line 3: No memory`. Zdjęcia pierwotnie ważyły 14MB (9 zdjęć) w rozmiarze 2560x2560. Skompresowałem je i udało mi się uzyskać 5.6MB. Niestety odpowiedź serwera przekracza ponad minutę (45-85 sekund) co w moim przypadku jest niestety nieakceptowalne. Używam metody `doNewAuctionExt` Zawartość requestu https://ufile.io/uy793

Czy jest możliwość przyspieszenia metody lub mają Państwo jakąś sugestie co do rozwiązania mojego problemu?

Pozdrawiam

**Comment by TimothyKoval** [comment]
1. Nie korzystaj ze starego WSDL-a
2. Możesz użyć REST-owego API, ale wystawianie oferty działa tam inaczej
