### ISSUE TITLE
Integracja - dostęp do aplikacji

### ISSUE THREAD

**Issue by Gosteczek11** [allegro/allegro-api#6101]
Witam,
Zwracam się z prośbą o dostęp do aplikacji, sprawa została również zgłoszona poprzez czat.

Chcemy dokonać integracji pomiędzy naszym system a Państwa platformą, oto uzasadnienie w jakim celu jest nam potrzebny dostęp do aplikacji : 
Wykorzystujemy serwis Allegro do sprzedaży naszych produktów klientom.
W tym celu chcemy: 
1. Zaimportować zamówienia z allegro do naszego systemu ERP
2. Pobrać etykiety
3. Zaktualizować szczegóły naszych produktów, w tym opis, stan magazynowy, ceny z naszego systemu ERP do Allegro

Dlatego właśnie potrzebujemy integracji.

W celu skorzystania z integracji postępujemy zgodnie z dokumentacją zamieszczoną na stronie https://apps.developer.allegro.pl/. 
Zarejestrowaliśmy aplikację pod naszym kontem, ale nadal dostajemy błąd.

Oto id klienta : a202404b-xxxxxxxxx-dc8572ea5

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Korzystasz z autoryzacji typu "client_credentials", która nie posiada kontekstu użytkownika. Musisz skorzystać z [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow) flow, aby uzyskać dostęp do większości zasobów API Allegro.
