### ISSUE TITLE
Pickup name is required - mylacy komunikat

### ISSUE THREAD

**Issue by Pawelpwg** [allegro/allegro-api#6102]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
dzisiaj trafilem u klienta taki problem, w zaleznosci od danych nadawcy request przechodzil albo nie 
ponizej dwa request dla tej same transakcji (dane odbiorcy usuniete)

ten request nie przechodzi 
{
    "serviceId": 11577227,
        "receiver": {
            "address": { .... },
        "email": .....
    },
    "pickup":
    {
        "address":
        {   "street": "jarowa 11", "postCode": "35-083 ", "city": "Rzeszów", "countryCode": "PL", "country": null },
           "email": "biuro@lavi24.pl",
            "name": "Lavi",
            "company": "LAVI Sp zoo",
            "phone": "0000", "pointId": null
    },
    "items": [{ "dimensions": { "height": { "value": 10, "unit": "CENTIMETER" }, "width": { "value": 10, "unit": "CENTIMETER" }, "depth": { "value": 10, "unit": "CENTIMETER" } }, "weight": { "value": "1.00", "unit": "KILOGRAM" }, "description": "BABYMAM PRZEŚCIERADŁO DO ŁÓŻECZKA 120x60 BAWEŁNA\r\n", "value": { "amount": "10", "currency": "PLN" }, "type": "PACKAGE", "waybill": null }], "type": "PACKAGE", "label": null, "additionalServices": null

    {
        "id": "a766cf63-3084-4475-8289-957dc8f7a956", "parcelId": null, "status": "ERROR",
            "errors": [{ "code": "ERROR", "message": "Pickup name is required", "details": null, "path": "pickup.name", "userMessage": "Nazwa punktu nadania przesyłki jest wymagana" }]
    }
}

ten juz zadzial prawidlowo
{
    "serviceId": 11577227, "receiver": {
        "address": {.... },
        "email": .....
    }, "pickup": {
        "address": { "street": "MALAWA 892A - magazyn 22", "postCode": "36-007", "city": "Rzeszów", "countryCode": "PL", "country": null },
        "email": "biuro@lavi24.pl", "name": "LAVI spolka", "company": "LAVI Sp. z o.o.", "phone": "0000", "pointId": null
    }, "items": [{
        "dimensions": {
            "height": { "value": 10, "unit": "CENTIMETER" }, "width": { "value": 10, "unit": "CENTIMETER" },
            "depth": { "value": 10, "unit": "CENTIMETER" }
        }, "weight": { "value": "1.00", "unit": "KILOGRAM" }, "description": "BABYMAM PRZEŚCIERADŁO DO ŁÓŻECZKA 120x60 BAWEŁNA\r\n", "value": { "amount": "10", "currency": "PLN" }, "type": "PACKAGE", "waybill": null
    }], "type": "PACKAGE", "label": null, "additionalServices": null
}

requesty roznia sie tylko danymi adresowymi nadawacy, prosze mi powiedziec gdzie dokladnie jest problem w pierwszym requescie, bo komunikat zwrotny nie pomaga, sa jakies dodatkowe wymagania do nazwy w pickup?

Pawel

**Comment by PrzemyslawLukanowski** [comment]
Pole powinno składać się z dwóch wyrazów, dlatego za pierwszym razem otrzymałeś błąd, a za drugim request przeszedł bez problemu. W tym miejscu oczekujemy imienia i nazwiska, stąd wymagalność dwuczłonowej wartości.

**Comment by Pawelpwg** [comment]
powiedzialbym ze to malo praktyczna regula, zwiazku z tym ze wiekszosc klientow to firmy a nie konkretne osoby

jesli moglby zasugerowac to dodanie takich informacji zwiazanych z walidacja do dokumentacji, napewno zaoszczedzilo by to sporo czasu, napewno mi szukajac problemu ;)

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za sugestię, postaramy się uzupełnić tę informację.
