### ISSUE TITLE
PATCH /sale/product-offers/{offerId} 

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#6104]
Witam!
Przeczytałem dokumentację tutaj
https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase
 i tutaj
https://developer.allegro.pl/documentation#operation/editProductOffers

Otrzymuję następującą **odpowiedź serwera**:
422
`{'errors': [{'code': 'JsonMappingException', 'message': 'Message is not readable.', 'details': None, 'path': 'productSet[0].product.parameters[0].values', 'userMessage': 'Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.'}]}`

productSet[0].product.parameters[0].values - oto zmiana, którą wprowadzam

otrzymuję dane stąd
GET /sale/offers/{offerId}
productSet
images
description
parameters (Próbowałem z tymi danymi i bez tych danych, zgodnie z doświadczeniem z API Allegro czasami konieczne jest, aby dane były zarówno osobno w parametrach, jak i w parametrach w tablicy danych produktu)

Dokonuję jednej zmiany w ofercie
11929481801
potrzebuje zmiany parametru
```
('id': '224017', 'name': 'Kod producenta', 'values': 'u73159', 'valuesIds': None, 'rangeValue': None}
('id': '224017', 'name': 'Kod producenta', 'values': 's06799', 'valuesIds': None, 'rangeValue': None}
```

to wszystko czego potrzebuję. Ta manipulacja będzie musiała zostać przeprowadzona z częścią produktów, więc robię to za pomocą API.

Proszę mi powiedzieć, dlaczego przekazuję dane zgodnie z dokumentacją i przekazuję wszystko w tym samym formacie, w jakim jest to określone, z wyjątkiem miejsca, w którym potrzebuję zmiany. A w tym miejscu jest błąd?!

**Comment by PrzemyslawLukanowski** [comment]
Problem jest spowodowany tym, że pierwszy parametr w sekcji product (224017) przekazujesz bezpośrednio jako ciąg znaków, a nie element tablicy. Czyli zamiast:

```
{
	"id": "224017",
	"name": "Kod producenta",
	"values": "s06799",
	"valuesIds": null,
	"rangeValue": null
}
```

musisz przekazać:

```
{
	"id": "224017",
	"name": "Kod producenta",
	"values": ["s06799"],
	"valuesIds": null,
	"rangeValue": null
}
```

**Comment by sergeidebug** [comment]
dokładnie tak jest.
Dziękuję!
Ciekawe jest również to, że jednego wymaganego parametru nie było w produkcie, a teraz przy aktualizacji prosi o to, więc musiałem dodać kolejny parametr, ale teraz działa :)
