### ISSUE TITLE
Produktyzacja, nowa oferta - Błędne koło wymaganych parametrów.

### ISSUE THREAD

**Issue by arkwlcz** [allegro/allegro-api#6108]
Dzień dobry.

Szanowni Państwo, zacznę od przykładu.
Podczas próby wystawienia oferty połączonej z produktem o ID: `0aafcd90-f0f9-4acc-ad5c-b6efc4948ab7` otrzymuję błąd, że parametr `"Przeznaczenie" nie jest uzupełniony`. Odpytuję API o ten produkt i faktycznie tak jest. Zatem próbujemy przekazać ten parametr przy ofercie, ale wówczas trafiamy na błąd, że parametr `"Przeznaczenie" należy podawać przy produkcie, a nie ofercie.`

To jest tylko jednostkowy przykład, takich sytuacji mamy więcej.

- Czy mogę wybrać inny produkt? Nie bardzo, ponieważ wszystkie produkty w Państwa katalogu dotyczące tego przedmiotu nie posiadają kompletnej listy parametrów. Do tego przeglądanie listy produktów, aby wybrać ten który na pewno ma wszystkie parametry jest czasochłonne i nieopłacalne.

- A może utworzyć nowy produkt? Ale po co, skoro takowe już istnieją w dobrych kategoriach. Zapychanie katalogu zbędnymi pozycjami.

- Czyli pozostaje zgłoszenie poprawki do produktu, ale to opcja karkołomna i nie opłacalna dla nas. Godziny pracy naszych pracowników kosztują i co, mamy delegować ludzi, którzy mają poświęcać czas, aby usprawniać Państwa katalog?

Najsensowniejszym podejściem wydawać się może zaimplementowanie rozwiązanie, że gdy produkt nie posiada jakiegoś parametru, a należy go uwzględnić w ofercie to Państwa aplikacja mogłaby akceptować podanie tego parametru w ofercie, a nie rzucanie wyjątku, że ten ma być podany przy produkcie.

Od siebie, jako programisty dodam, że odkąd wprowadziliście Państwo obostrzenia związane z produktyzowaniem ofert, praca przy Państwa API jest najgorszym kejsem jaki trafił mi się od lat. Jest karkołomna, momentami pozbawiona logiki, a co najgorsze znalezienie jednego rozwiązania skutkuje pojawieniem się kilkunastu innych problemów.

Pozdrawiam.

**Comment by MaciejFrackowiak** [comment]
Zależności związane z obsługą produktyzacji w API są odzwierciedleniem reguł i zasad w serwisie WWW. Wymogi dotyczące produktów w API, mechanizm zgłaszania sugestii zmian, itp. to nie zasady określone tylko dla API, a ogólne zasady produktyzacji obejmujące całe Allegro. Dlatego swoje uwagi dot. produktyzacji proszę zgłoś poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by arkwlcz** [comment]
Dziękuję, skorzystałem zatem z formularza.
