### ISSUE TITLE
Problem z refresh tokenem

### ISSUE THREAD

**Issue by kormichu** [allegro/allegro-api#611]
Witam,

Mam duży problem z odświeżeniem access tokenów przy pomocy refresh tokena. Klienci który połączyli się z naszą aplikacją rok temu nie mogą odświeżyć teraz access_tokena. Dostaję błąd:
`{"error":"invalid_token","error_description":"Invalid refresh token (expired)...`

Zdaję sobie sprawę, że refresh token jest ważny tylko rok. Problem w tym, że odświeżam access tokeny średnio co 12h i zapisuję za każdym razem zwrócony zarówno access token jak i **refresh token**, które później wykorzystuję. W teorii więc zwrócony refresh token powinien działać przez kolejny rok od ostatniego odświeżenia access tokena. Po logach API z ostatniego miesiąca widzę, że wartości tokenów się zgadzają. Jeśli będzie trzeba to je udostępnię przez formularz kontaktowy

**Comment by kormichu** [comment]
Ticket#1251273188

**Comment by TimothyKoval** [comment]
Z tego co wiem to właśnie tak nie jest, co rok trzeba się ponownie logować.

**Comment by kormichu** [comment]
Tak mam powiedzieć tysiącom klientów ?

**Comment by kocyk74** [comment]
Informacja ze strony https://developer.allegro.pl/auth/

> Ważność refresh tokena nie ulega przedłużeniu - niezależnie od liczby wygenerowanych tokenów dostępowych na podstawie kolejnych refresh tokenów, autoryzację użytkownika dla aplikacji można przedłużyć do maksymalnie 365 dni od momentu wygenerowania pierwszego tokena.

Więc jest dokładnie tak jak napisał @TimothyKoval

**Comment by TimothyKoval** [comment]
Więc wiesz... Może tysiącom klientów daj numer telefonu do Allegro :)

**Comment by kormichu** [comment]
Rzeczywiście jest to opisane w dokumentacji :/ Być może wcześniej nie było albo nie zwróciłem na to uwagi. Nowy sposób autoryzacji wdrażaliśmy równo rok temu i teraz z dnia na dzień będą pojawiać się dziesiątki zgłoszeń dotyczących rozłączonego konta. W moim odczuciu jest to bezsensowny mechanizm bo teraz będę musiał dodatkowo wysyłać maile do klienta, aby połączyli konto na nowo. I tak co roku. Sprawa dodatkowo się komplikuje bo zamówienia zaciągamy od daty połączenia konta więc mogą pojawić się luki

**Comment by LukaszKorek** [comment]
@kormichu Refresh token jest ważny przez 365 dni ponieważ w ten sposób możemy przypomnieć klientom, że mają taką autoryzację dla aplikacji. Jeśli klient uzna, że chce dlaej mieć zautoryzowaną danę aplikację powinien to potwierdzić.

**Comment by TimothyKoval** [comment]
To jest chyba największa bzdura jaką usłyszałem z waszych "ust". Jeżeli tak dbacie o interes użytkownika, to czemu nie dajecie możliwości zarządzania powiązanymi aplikacjami?

**Comment by LukaszKorek** [comment]
@TimothyKoval Pracujemy nad taką listę, która można zarządzać. Pracujemy też nad zmianami w autoryzacji dla aplikacji. Jak tylko będą gotowe szczegóły poinformujemy o tym.
