### ISSUE TITLE
Jak powiązać sposób dostawy zamówienia z usługą dostawy Wysyłam z Allegro?

### ISSUE THREAD

**Issue by lukasz-lopata** [allegro/allegro-api#6112]
Witam,

Chciałbym zautomatyzować wysyłkę za pomocą usługi Wysyłam z Allegro poprzez pobranie szczegółów zamówienia i nadania przesyłki.
Do pobrania szczegółów zamówienia wykorzystuję endpoint `https://api.{environment}/order/checkout-forms/{id}`, który zwraca mi następującą informację odnośnie zamówienia:
`"delivery": {
		"address": {
			...
		},
		"method": {
			"id": "08c15d0b-9b24-4b3f-89a8-7a2b502abe55",
			"name": "Allegro One Punkt"
		},
		"pickupPoint": {
			"id": "A004225",
			"name": "Allegro One Punkt, Kolporter",
			"description": "Osiedle",
			"address": {
				"street": "Powstańców 34c",
				"zipCode": "31-422",
				"city": "Kraków"
			},
			"modifiedAt": null
		},
		"cost": {
			"amount": "0.00",
			"currency": "PLN"
		},
		"smart": false,
		"time": {
			"guaranteed": null
		},
		"calculatedNumberOfPackages": 1
	}`

W jaki sposób mogę powiązać sposób dostawy z dostępnymi usługami dostawy? Ze szczegółów mogę wyciągnąć jedynie id, które jest GUID'em i nazwę sposobu dostawy, która wydaje mi się, że jest zbyt ogólna, ponieważ jeżeli chodzi o usługi dostawy, które mam do wyboru odnośnie "Allegro One Punkt" to:

ALLEGRO	Allegro One (UPS)
ALLEGRO	Allegro One Box (One Kurier) - dostawa jutro
ALLEGRO	Allegro One Punkt (One Kurier) - dostawa jutro
X_PRESS_COURIERS Allegro One Kurier
ALLEGRO	Allegro One Box (One Kurier) - dostawa dzisiaj

Id tych usług nie pokrywą się w żaden sposób ze sposobem dostawy zamówienia.

**Comment by MaciejFrackowiak** [comment]
Z pomocą w tym przypadku przychodzi [nasz poradnik](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke), gdzie opisaliśmy zależności pomiędzy metodą dostawy wybraną przez kupującego a wybraną usługą Wysyłam z Allegro.

**Comment by lukasz-lopata** [comment]
Dziękuję za nakierowanie
