### ISSUE TITLE
Products and Product Sets

### ISSUE THREAD

**Issue by RuMont** [allegro/allegro-api#6114]
Hi, I am trying to understand how products and offers really work in Allegro and have some questions.

Are product proposals manually accepted? Other platforms just let you upload your products and start selling them.
Can I create an offer before the product proposal has been accepted?
Can I create an offer from a product that has not even been proposed? Using the product-offers endpoint I think.
If the last question is a yes, should I propose products?

Thanks in advance.

**Comment by MaciejFrackowiak** [comment]
Product proposals are accepted automatically and manually. 
If a product does not exist in our database, you can provide product data which describes your product, and we based on them will create an active offer - please, read [our tutorial](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA), where we describe the whole process.
