### ISSUE TITLE
Brak ofert w "moim asortymencie"

### ISSUE THREAD

**Issue by JurekAndrzejewski** [allegro/allegro-api#6115]
Hej, na stronie "https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment" nie wyświetlają się oferty (sprawdzone dwa konta), a gdy odpalam publiczną stronę aukcji korzystając z jej numeru i wchodząc w hiperłącze pozwalające na edycję oferty nie jest to możliwe. 
![image](https://user-images.githubusercontent.com/88549154/189897754-73675222-7293-4f66-8e80-685ba12a32f2.png)
![image](https://user-images.githubusercontent.com/88549154/189897789-e48dc712-624a-4d43-8673-cea1c4d4fc3e.png)

**Comment by MaciejFrackowiak** [comment]
Nie jest to problem bezpośrednio związany z funkcjonowaniem API Allegro, jednak mogę potwierdzić występowanie problemów z działaniem serwisu - pracujemy już, aby je wyeliminować.

**Comment by MaciejFrackowiak** [comment]
Problem nie powinien już występować - przepraszam za niedogodności.

**Comment by JurekAndrzejewski** [comment]
@MaciejFrackowiak super, dzięki
