### ISSUE TITLE
500 - internal server error po zapytaniu sale/offers/nr_aukcji

### ISSUE THREAD

**Issue by barpas** [allegro/allegro-api#6116]
jak w temacie - pytam o aukcję jak zawsze, od kilkunastu minut dostaję kod 500

**Comment by MaciejFrackowiak** [comment]
Potwierdzam - mamy chwilowe problemy techniczne i już działamy, aby je wyeliminować.

**Comment by MaciejFrackowiak** [comment]
Problem nie powinien już występować - przepraszam za niedogodności.
