### ISSUE TITLE
Skąd pobrać sekcje pasuje do? Błąd: Wskazana sekcja \"Pasuje do\" jest nieprawidłowa dla danego produktu, użyj produktowej sekcji \"Pasuje do\". Zaktualizuj dane produktowe w ofercie.

### ISSUE THREAD

**Issue by pawliszka** [allegro/allegro-api#6117]
TraceID: c05872d84cc6f19d

Skąd pobrać poprawną sekcję Pasuje do ? 
Aktualnie pobieram ją z TecDoc i mapuję identyfikatory z TecDoc na ID z allegro, bazując na tym co wystawiam, ale allegro mnie nie puszcza

**Comment by AureliuszBrussy** [comment]
Sekcję "Pasuje do" możesz pobrać bezpośrednio z naszego Katalogu Produktów, pobierając dane tego produktu za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProduct). Id tego produktu to: 294cc24f-8bf8-4381-a99c-201a8e29cf35. 

Możesz także posłużyć się zasobem [GET /sale/compatibility-list-suggestions](https://developer.allegro.pl/documentation/#operation/getCompatibilityListSuggestion) - zwrócimy wtedy sugerowaną sekcję compatibilityList. 

Jest jeszcze opcja, że w żądaniu [POST /sale/product-offers](https://developer.allegro.pl/documentation#operation/createProductOffers) możesz w ogóle nie przekazywać sekcji **compatibilityList** - wtedy uzupełnimy ją automatycznie na podstawie rozpoznanego produktu.

**Comment by pawliszka** [comment]
dzięki działa :)
