### ISSUE TITLE
Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 244505

### ISSUE THREAD

**Issue by artur-janczarek** [allegro/allegro-api#6120]
Witam,
w requeście dla /sale/product-proposals przekazuję 
{"name":"\u017bel przeciwb\u00f3lowy Arctic Ice Analgesic Gel 227g","category":{"id":"122464"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/112dc3\/0ff8618f4c7691b3b42e00d1569b"},{"url":"https:\/\/a.allegroimg.com\/original\/114587\/e122b8d04b7bb0b72400ba57ab01"}],"parameters":[{"id":"244505","valuesIds":[],"values":["test"],"rangeValue":null},{"id":"210758","valuesIds":["210758_669241"],"values":[],"rangeValue":null},{"id":"210826","valuesIds":["210826_245198"],"values":["Arctic"],"rangeValue":null},{"id":"225693","valuesIds":[],"values":["041348006378"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"
Oryginalny, ameryka\u0144ski \u017cel przeciwb\u00f3lowy. Skutecznie \u0142agodzi b\u00f3l w miejscu posmarowania. Skuteczny tak\u017ce przy zakwasach mi\u0119\u015bni. U\u017cywany ch\u0119tnie przez masa\u017cyst\u00f3w, osoby ucz\u0119szczaj\u0105ce na si\u0142ownie i uprawiaj\u0105ce aktywnie sport.<\/p>"}]}]}}

W odpowiedzi dostaję błąd:
{"errors":[{"code":"ParameterException.InvalidParameterDtoException","message":"An error has occurred","details":null,"path":"parameters","userMessage":"Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 244505."}]}

Proszę o pomoc w jakim formacie ma być wartość dla 244505, które ma być po prostu stringiem o długości od 1 do 40 znaków?

**Comment by AureliuszBrussy** [comment]
Nie przekazuj w parametrach pustej tablicy w polu "**valuesIds**":

`"valuesIds":[]`

Pomiń całkowicie to pole, lub przekaż **null**.

**Comment by artur-janczarek** [comment]
No niestety, gdy ustawię na null jest błąd, gdy null-e pominę też jest błąd. Oto dwa przykładowego requesty:

{"name":"Advil Ibuprofen 200 mg 360 Tablets","category":{"id":"122464"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/115215\/855e4a4e46158955ece74b1da94c"},{"url":"https:\/\/a.allegroimg.com\/original\/117608\/8d2ac4e04d4cb282922f72c137b9"}],"parameters":[{"id":"244505","valuesIds":null,"values":["Advil Ibuprofen 200 mg 360 Tablets"],"rangeValue":null},{"id":"210758","valuesIds":["210758_244702"],"values":null,"rangeValue":null},{"id":"210826","valuesIds":["210826_245198"],"values":["Advil"],"rangeValue":null},{"id":"225693","valuesIds":null,"values":["0305730154604"],"rangeValue":null}],"description":{"sections":[{"items":[{"type":"tresc"}]}]}}
{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

{"name":"Advil Ibuprofen 200 mg 360 Tablets","category":{"id":"122464"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/115215\/855e4a4e46158955ece74b1da94c"},{"url":"https:\/\/a.allegroimg.com\/original\/117608\/8d2ac4e04d4cb282922f72c137b9"}],"parameters":[{"id":"244505","values":["Advil Ibuprofen 200 mg 360 Tablets"]},{"id":"210758","valuesIds":["210758_244702"]},{"id":"210826","valuesIds":["210826_245198"],"values":["Advil"]},{"id":"225693","values":["0305730154604"]}],"description":{"sections":[{"items":[{"type":"tresc"}]}]}}
{"errors":[{"code":"HttpMessageNotReadableException","message":"An error has occurred","details":null,"path":null,"userMessage":"Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji."}]}

**Comment by AureliuszBrussy** [comment]
W tym przypadku błąd znajduje się w sekcji **description**, powinna ona wyglądać tak:

```
"description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "<p>treść</p>"
                    }
                ]
            }
        ]
    }
```
WIęcej o budowaniu opisu znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#wlasne-zdjecia-i-opis-oferty).

**Comment by artur-janczarek** [comment]
Nie mam sił do Was, chyba nie jestem jedyny ;)

https://developer.allegro.pl/documentation#operation/proposeSaleProduct - tu jest tak:
`"description": {
"sections": [
{
"items": [
{
"type": "string"
}
]
}
]
}`

https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#dodaj-propozycje-produktu - a tu jest inaczej w podglądzie requestu
`"description": {                                          -- opis produktu
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<p>Opis produktu</p>"
          }
        ]
      }
    ]
  }`

**Comment by AureliuszBrussy** [comment]
@artur-janczarek wejdź w szczegóły poszczególnych obiektów - znajdziesz tam dokładną strukturę:
![image](https://user-images.githubusercontent.com/68948612/191704453-6aa17141-f729-4dba-b68d-19b34a770aa9.png)

**Comment by artur-janczarek** [comment]
Dzięki, działa wszystko. Ale jak mieliście lata temu bałagan w dokumentacji, tak dalej macie bałagan miejscami ;)
