### ISSUE TITLE
Dostep do API Allegro.

### ISSUE THREAD

**Issue by lymbf** [allegro/allegro-api#6121]
Witam serdecznie!

W imieniu klienta mam przygotowac sklep internetowy oraz jego pelna integracje z API allegro w celu usprawnienia sprzedazy. Po przeczytaniu regulaminu chcialem wyjasnic nastgepujaca kwestie:

1. Regulamin stwierdza, iz aplikacja korzystajaca z API Allegro musi miec 100 aktywnych uzytkownikow, aby uzyskac dostep. Jak mam rozumiec ten punkt w kontekscie sklepu internetowego?

Pozdrawiam serdecznie!

**Comment by AureliuszBrussy** [comment]
Ten zapis regulaminu nie dotyczy całego publicznego API Allegro - informuje tylko, że, cyt.: "W odniesieniu do **niektórych** funkcjonalności w ramach Zasobów REST API, w tym z uwagi na ich charakter lub zawartość, **może być wymagane** [...]:
b. osiągnięcie przez Użytkownika wymaganej przez Spółkę minimalnej liczby Użytkowników korzystających z aplikacji Użytkownika (co najmniej 100)"

Na ten moment zapis ten stosuje się tylko dla zasobu [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), gdzie dostęp mają tylko [zweryfikowane aplikacje](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1). Z pozostałych zasobów możesz korzystać swobodnie.
