### ISSUE TITLE
Dodanie oferty opartej o produty - "Access Denied"

### ISSUE THREAD

**Issue by jaroslaw-sarecki** [allegro/allegro-api#6122]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x ] ze środowiskiem testowym / with the test environment
 - [x ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas próby utworzenia oferty opartej na poroduktach, podczas próby dodania nieistniejącego produktu otrzymuję komunikat :

`["code"] => string(26) "OfferAccessDeniedException"
      ["message"] => string(9) "Forbidden"
      ["details"] => NULL
      ["path"] => string(0) ""
      ["userMessage"] => string(59) "Access Denied, You don’t have permission to access offer."`
      
      
 Używam konta firmowego założonego na sandbox. Na stronie https://apps.developer.allegro.pl.allegrosandbox.pl/ 
 dodałem sobie klucze do aplikacji, której używam. Dodałem pełne dostępy dla danego klucza.
 
 Dane wysyłam na `/sale/product-offers`. Walidacja nie zwraca żadnych błędów dotyczących struktury requesta jakiego wysyłam, więc zakładam że jest poprawna.
 
 `{"delivery":{"shippingRates":{"id":"a2122f01-7644-458b-9768-bfe4f54a056d"},"handlingTime":"PT24H","additionalInfo":"","shipmentDate":null},"location":{"countryCode":"PL","province":"WIELKOPOLSKIE","city":"Kalisz","postCode":"62-800"},"payments":{"invoice":"VAT"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"39.00","currency":"PLN"},"startingPrice":null,"minimalPrice":null},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.allegrosandbox.pl\/original\/110c4e\/0285ec2e4290a1f30b6ecfded27b"},{"type":"TEXT","content":"<h2>Produkt Testowy<\/h2>"}]},{"items":[{"type":"TEXT","content":"<p>Opis produktu testowego<\/p>"}]}]},"category":{"id":"76005"},"productSet":[{"product":{"name":"Produkt Testowy","category":{"id":"76005"},"parameters":[{"id":"15851","valuesIds":["15851_1"],"values":[],"rangeValue":null},{"id":"3946","valuesIds":["3946_217313"],"values":[],"rangeValue":null},{"id":"1815","valuesIds":["1815_10"],"values":[],"rangeValue":null},{"id":"451","valuesIds":["451_32768"],"values":[],"rangeValue":null},{"id":"16059","valuesIds":["16059_225482"],"values":[],"rangeValue":null},{"id":"205570","valuesIds":["205570_259410"],"values":[],"rangeValue":null},{"id":"203929","valuesIds":["203929_218433"],"values":[],"rangeValue":null},{"id":"220153","valuesIds":null,"values":["6"],"rangeValue":null},{"id":"3766","valuesIds":["3766_1"],"values":[],"rangeValue":null},{"id":"205554","valuesIds":["205554_223866"],"values":[],"rangeValue":null},{"id":"129150","valuesIds":["129150_3"],"values":[],"rangeValue":null},{"id":225693,"valuesIds":null,"values":["5900714198619"],"rangeValue":null},{"id":224017,"valuesIds":null,"values":["273517403"],"rangeValue":null}],"idType":"GTIN","id":"5900714198619","images":["https:\/\/a.allegroimg.allegrosandbox.pl\/original\/110c4e\/0285ec2e4290a1f30b6ecfded27b"]},"quantity":{"value":99}}],"stock":{"available":99,"unit":"UNIT"}}`

**Comment by MaciejFrackowiak** [comment]
Korzystasz z konta, które od 2018 roku nie zostało w pełni zweryfikowane jako firmowe, dlatego otrzymujesz błąd przy wystawianiu oferty zgodnie z [ostatnimi zmianami](https://github.com/allegro/allegro-api/issues/5935). Niestety, obecnie nie mam już możliwości zweryfikować tego konta, dlatego sugeruję, abyś utworzył nowe konto testowe - firmowe na Sandbox, wówczas będziesz mógł wystawiać oferty.

**Comment by jaroslaw-sarecki** [comment]
Proszę o aktywację konta sandboxowego "ma-sandbox"

**Comment by MaciejFrackowiak** [comment]
Abym mógł w pełni aktywować i zweryfikować konto, proszę przejdź cały proces rejestracji konta w zakładce [Moje konto](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto). Chodzi tutaj o wykonanie symulacji przelewu weryfikacyjnego oraz uzupełnienie wszystkich danych i przesłanie plików.

**Comment by jaroslaw-sarecki** [comment]
Ok, uzupełniłem ( mam nadzieję że wszystko)

**Comment by MaciejFrackowiak** [comment]
Konto jest już zweryfikowane.

**Comment by jaroslaw-sarecki** [comment]
Dziękuję
