### ISSUE TITLE
Jednoelementowe obowiązkowe parametry słownikowe

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6123]
Jaka idea kryje się za obowiązkowymi parametrami słownikowymi z jedną dozwoloną wartością? Poniżej przykład dla parametru 249493 w kategorii nr 91490:

   ```
{
      "id": "249493",
      "name": "Gatunek",
      "type": "dictionary",
      "required": true,
      ...
      },
      "dictionary": [
        {
          "id": "249493_1645911",
          "value": "Pozostałe",
          ... 
        }
      ]
      ...
    }
```

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Struktura kategorii i parametrów w API to odzwierciedlenie układu kategorii i parametrów wprost ze strony WWW Allegro. Jednym słowem - dostępne wartości nie są przez nas jako API ustalane, a przez osoby działające w ramach całej platformy - swoją uwagę proszę przekaż poprzez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) do obsługi serwisu.

**Comment by FromAnyHole** [comment]
@tomylee0 - bardzo dobre pytanie, bardzo dobre!!
Przy okazji - pomijając samą durnotę logiki z jednym "wyborem" - pojawia się coraz więcej tych parametrów, które są narzucone jako tzw. współzależne... Już czasem są nieoczekiwane zdarzenia przez to, bardziej jak dywersja wygląda, w końcu wojna trwa.
