### ISSUE TITLE
Problem z dekodowaniem odpowiedzi json

### ISSUE THREAD

**Issue by tomasz-grzesik** [allegro/allegro-api#6125]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Proszę sprawdzić, czy metoda DELETE /sale/loyalty/promotions/ zwraca poprawnie sformatowaną odpowiedź (JSON).

**Comment by hahyes** [comment]
> metoda DELETE /sale/loyalty/promotions/

Metoda ta zwraca JSONa tylko w przypadku 401 Unauthorized.

**Comment by tomasz-grzesik** [comment]
Nagłówek odpowiedzi sugeruje coś innego.

**Comment by hahyes** [comment]
@tomasz-grzesik A to przepraszam, zerknąłem do dokumentacji tylko a zasobu nie używam.

**Comment by tomasz-grzesik** [comment]
> @tomasz-grzesik A to przepraszam, zerknąłem do dokumentacji tylko a zasobu nie używam.

nie ma problemu. Dodałem wyjątek obsługujący.

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik dziękuję za zwrócenie na to uwagi - wyjaśniam to. Wrócę z informacją.

**Comment by tomasz-grzesik** [comment]
Znowu jakieś problemy?

**Comment by tomasz-grzesik** [comment]
Całe szczęście chwilowe.

**Comment by AureliuszBrussy** [comment]
@tomasz-grzesik napotkałeś jakieś ponowne problem z tym zasobem? Już nie występują?
