### ISSUE TITLE
Ilość tarcz w ofercie - Uzupełnij brakujące parametry

### ISSUE THREAD

**Issue by mskiba03** [allegro/allegro-api#6126]
Witam, mam problem, z wystawienie aukcji z tarczami hamulcowymi.

W parametrach ofertowych podaje cos takiego:

 "parameters": [
                {
                    "id": "249422",
                    "valuesIds": [
                        "249422_1218233"
                    ],
                    "rangeValue": null
                },
                {
                    "id": "11323",
                    "valuesIds": [
                        "11323_1"
                    ],
                    "values": [],
                    "rangeValue": null
                }
            ]

Dostaje blad:

CODE: ConstraintViolationException.MissingRequiredParameters - MESSAGE: Missing required parameters: 249422 - DETAILS: ConstraintViolationException.MissingRequiredParameters - PATH: parameters - USER MESSAGE: Uzupełnij parametry obowiązkowe: Liczba tarcz w ofercie.

**Comment by AureliuszBrussy** [comment]
@mskiba03 czy mógłbyś przesłać cały payload (cały json) oraz trace-id tego wywołania?

**Comment by mskiba03** [comment]
Poniżej pełny json

{
    "productSet": [
        {
            "product": {
                "id": "266d219c-874f-40a4-9f0d-2fbcca77bde5",
                "parameters": [
                    {
                        "id": "129591",
                        "valuesIds": [
                            "129591_1"
                        ],
                        "values": [],
                        "rangeValue": null
                    },
                    {
                        "id": "225693",
                        "valuesIds": [],
                        "values": [
                            "4006633427142"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "215858",
                        "valuesIds": [],
                        "values": [
                            "24.0122-0293.1"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "127415",
                        "valuesIds": [],
                        "values": [
                            "ATE"
                        ],
                        "rangeValue": null
                    },
                    {
                        "id": "127636",
                        "valuesIds": [
                            "127636_384985"
                        ],
                        "values": [],
                        "rangeValue": null
                    }
                ]
            },
            "quantity": {
                "value": 2
            },
            "parameters": [
                {
                    "id": "249422",
                    "valuesIds": [
                        "249422_1218233"
                    ],
                    "values": [],
                    "rangeValue": null
                },
                {
                    "id": "11323",
                    "valuesIds": [
                        "11323_1"
                    ],
                    "values": [],
                    "rangeValue": null
                }
            ]
        }
    ],
    "name": "TARCZE HAMULCOWE PRZ\u00d3D ATE 24.0122-0293.1 ",
    "category": {
        "id": "250406"
    },
    "description": {
        "sections": [
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
TARCZE HAMULCOWE PRZ\u00d3D ATE 24.0122-0293.1 <\/h1>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
NAZWA<\/h2>
Tarcza hamulcowa<\/li><\/ul>
NUMER KATALOGOWY<\/h2>
24.0122-0293.1 \/ 24012202931<\/li><\/ul>
SZCZEG\u00d3\u0141Y PRODUKTU<\/h2>
Strona zabudowy :  O\u015b przednia<\/li>
Strona zabudowy :  Po obydwu stronach<\/li>
Ci\u0119\u017car [kg] :  5.2<\/li><\/ul>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
NAZWA<\/h2>
Tarcza hamulcowa<\/li><\/ul>
NUMER KATALOGOWY<\/h2>
24.0122-0293.1 \/ 24012202931<\/li><\/ul>
SZCZEG\u00d3\u0141Y PRODUKTU<\/h2>
Strona zabudowy :  O\u015b przednia<\/li>
Strona zabudowy :  Po obydwu stronach<\/li>
Ci\u0119\u017car [kg] :  5.2<\/li><\/ul>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
CENA ZA KOMPLET NA JEDN\u0104 O\u015a<\/h2>"
                    }
                ]
            },
            {
                "items": [
                    {
                        "type": "TEXT",
                        "content": "
Szanowny Kliencie. Prawid\u0142owe dopasowanie cz\u0119\u015bci do danego samochodu jest mo\u017cliwe tylko po numerze VIN. Brak VIN-u w zam\u00f3wieniu nara\u017ca Ci\u0119 na to, \u017ce zakupione cz\u0119\u015bci nie b\u0119d\u0105 pasowa\u0142y do Twojego samochodu. Co b\u0119dzie skutkowa\u0142o Twoj\u0105 strat\u0105 czasu na kolejn\u0105 wizyt\u0119 w warsztacie, odsy\u0142anie towaru i oczekiwanie na prawid\u0142owy towar b\u0105d\u017a zwrot \u015brodk\u00f3w.<\/h2>
<\/p>

U\u0142atw sobie \u017cycie \u2013 nie jeste\u015b pewien \u2013 wy\u015blij nam w wiadomo\u015bci numer VIN auta zweryfikujemy Tw\u00f3j wyb\u00f3r.<\/h2>
<\/p>

Na innych aukcjach allegro, mamy szerok\u0105 ofert\u0119 wielu producent\u00f3w olej\u00f3w silnikowych, uk\u0142adu hamulcowego, filtr\u00f3w i innych cz\u0119\u015bci samochodowych.<\/h1>"
                    }
                ]
            }
        ]
    },
    "delivery": {
        "shippingRates": {
            "id": "7604211b-f17c-425d-8001-2b8b10f62946"
        },
        "handlingTime": "P2D"
    },
    "sellingMode": {
        "format": "BUY_NOW",
        "price": {
            "amount": "466.44",
            "currency": "PLN"
        }
    },
    "payments": {
        "invoice": "VAT"
    },
    "tax": {
        "percentage": "23.00"
    },
    "stock": {
        "available": "10",
        "unit": "SET"
    },
    "afterSalesServices": {
        "impliedWarranty": {
            "id": "63924c58-de32-46b5-8112-250605782ef6"
        },
        "returnPolicy": {
            "id": "611e60b4-33cb-4858-ab92-3811bb5bbc10"
        },
        "warranty": {
            "id": "1874bcbb-8c7a-4af6-bdfc-68fd6c6e84d0"
        }
    },
    "publication": {
        "duration": "P30D",
        "status": "ACTIVE"
    }
}

**Comment by AureliuszBrussy** [comment]
Przekazujesz parametry ofertowe (druga tablica "parameters"), wewnątrz obiektu **productSet[].product**. Powinieneś to zrobić poza tym obiektem, czyli całkowicie poza produktową częścią jsona (poza tablicą productSet[]).

**Comment by mskiba03** [comment]
Dziękuje, już jest ok.

Pozdrawiam
