### ISSUE TITLE
Dublowanie zdjęć w przypadku dodawania produktu do katalogu

### ISSUE THREAD

**Issue by bacok** [allegro/allegro-api#6127]
Witam.

Chciałbym się dowiedzieć w jaki sposób obsługiwane są zdjęcia, podczas gdy nie mamy produktu w katalogu Allegro (nie znajduję go po EAN, nie mam jego ID). Tworząc drafta, potrzebuję mieć URLe do zdjęć w opisie, stąd wysyłam je w base64 na endpoint `/sale/images` i wrzucam je w opis, jednocześnie w drafcie nie przesyłam nic we własności `images`.
Zdjęcia znajdują się dopiero w `productSet` -> `product` -> `images` dla endpointu `/sale/product-offers`. Przykładowy trace-id `906277d8a5c91f2e`.
W jaki sposób mam dodać zdjęcia do opisu i za jednym zamachem dodać je do katalogu produktowego aby nie dublowały się w galerii?
![Zrzut ekranu z 2022-09-19 14-35-46](https://user-images.githubusercontent.com/3853015/191018587-2c86412b-a08e-42f2-a39f-eb0d0ffd3fbe.png)

**Comment by AureliuszBrussy** [comment]
W podanym przez Ciebie przykładzie nie utworzyłeś produktu - ten produkt istniał już w naszym Katalogu Produktów i zostało on dopasowany automatycznie po naszej stronie (na podstawie parametrów). Jeżeli nie przekażesz w swoim wywołaniu tablicy **images** - prócz tych zdjęć, które dodałeś w opisie, w galerii znajdą się też zdjęcia z naszego Katalogu Produktów. 

Jeśli chcesz w ofercie zaprezentować wyłącznie własne zdjęcia, bez obrazków, które pochodzą z naszego Katalogu, przekaż w polu **productSet[].product.images** pustą tablicę lub przekaż w niej własne zdjęcia.

**Comment by bacok** [comment]
W porządku, dziękuję za wyjaśnienie. Zamykam.
