### ISSUE TITLE
ServiceTimeoutException przy próbie zamknięcia oferty

### ISSUE THREAD

**Issue by Mateusz-Nejman** [allegro/allegro-api#6128]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Request**
curl -X PUT https://api.allegro.pl/sale/offer-publication-commands/8BEEFDA8-44AB-4240-90FC-7627A25B31FB -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: application/vnd.allegro.public.v1+json' -d '{"offerCriteria":[{"offers":[{"id":"12638735348"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END"}}'

**Response**
{"errors":[{"code":"ServiceTimeoutException","message":"An error occurred","details":null,"path":null,"userMessage":"Execution of the request timed-out. Try again."}]}

Podobna sytuacja miała miejsce przy zapytaniu do _sale/offer-price-change-commands_ i _sale/offer-quantity-change-commands_.

**Comment by MartaNowaczyk** [comment]
Dzięki za zgłoszenie. Wygląda to na chwilowy problem. Sprawdziłam kilka razy i nie powtórzyłam błędu. Sprawdź proszę jeszcze u siebie dla pewności i daj znać.

**Comment by Mateusz-Nejman** [comment]
Zgłosiłem błąd, ponieważ od dłuższego czasu tak jest.

**Comment by MartaNowaczyk** [comment]
Rozumiem, że nadal masz ten problem. Na tym koncie co podałeś widziałam tylko wczoraj wieczorem taki problem. Możesz podać inne trace-id z tym błędem?

**Comment by Mateusz-Nejman** [comment]
W środowisku testowym:

curl -X PUT https://api.allegro.pl.allegrosandbox.pl/sale/offer-publication-commands/145E2B1B-5B7A-4B26-8A3B-D9E7A143B29E -H 'Authorization: Bearer [ACCESS_TOKEN]' -H 'Accept: application/vnd.allegro.public.v1+json' -H 'Content-Type: application/vnd.allegro.public.v1+json' -d '{"offerCriteria":[{"offers":[{"id":"7694319078"}],"type":"CONTAINS_OFFERS"}],"publication":{"action":"END"}}'

**Comment by MartaNowaczyk** [comment]
Weryfikuję sprawę. Dam znać, gdy coś ustalimy.
