### ISSUE TITLE
Export ogłoszeń do CSV lub Prestshop

### ISSUE THREAD

**Issue by soliniak** [allegro/allegro-api#613]
Witam,

Szukam informacji w jaki sposób exportować wystawione aukcje na allegro do pliku csv lub (docelowo) Prestashop. Chodzi mi o jednorazowy export (aukcji jest około 600 dlatego ręczne przenoszenie nie wchodzi w grę), potem całość będzie zintegrowana z baselinkerem.
Nie znalazłem informacji w dokumentacji WebAPI, ani w Menadżerze Sprzedaży.

Pozdrawiam

**Comment by collector1871** [comment]
Niestety samemu chyba uszyć skrypt. Ja będę miał do 3-4 tyg gotowe rozwiązania (perl - [https://metacpan.org/pod/Text::CSV](https://metacpan.org/pod/Text::CSV)).
tutaj jedno z najbardziej fundamentalnych pytań o delimiter
[https://github.com/allegro/allegro-api/issues/583](https://github.com/allegro/allegro-api/issues/583)

jakbyś był zainteresowany więcej tematem, to możemy się jakoś skontaktować (email)
