### ISSUE TITLE
Nie mogę wystawić oferty na Allegro.

### ISSUE THREAD

**Issue by cINKQ** [allegro/allegro-api#6130]
Niestety nie mogę wystawić oferty bo wyskakuje mi taki błąd. Dodam, że produkt z takimi danymi nie istnieje, jest jedynie z inną wersją systemu, ale nie mogę w żaden sposób go przypisać. 

![prze1](https://user-images.githubusercontent.com/113972993/191195360-d1b66097-0c99-439b-ad9f-1c5a7ed3f2cc.JPG)

tutaj załączam ustawienia profilu dostaw

![prze2](https://user-images.githubusercontent.com/113972993/191195413-07453b86-7b3c-4a79-afe9-65b89a028d83.JPG)

**Comment by MartaNowaczyk** [comment]
Do weryfikacji tego problemu potrzebuję więcej informacji. Sam zrzut pokazuje tylko komunikat błędu, który mówi, że taki produkt istnieje. Nie wiem jak działają opcje z tej aplikacji. Dlatego najpierw zawsze zalecamy kontakt z obsługą oprogramowania z którego korzystasz, być może wybierasz niewłaściwe opcje. 

Z tego co mogę się domyślać istnieje produkt podobny, ale według Ciebie niezgodny z Twoim produktem. W takim wypadku nie jest to problem API tylko katalogu produktów. Jeśli tamten produkt ma podane błędne dane [możesz zgłosić błąd w produkcie](https://allegro.pl/dla-sprzedajacych/jak-zglosic-blad-w-produkcie-ZGZG89WkOU0). Gdy jest to problem z katalogiem produktu - jeśli chcesz dodać inny produkt, ale nie możesz, bo wykrywa duplikat (też poprawny i nie chcesz go zmieniać/zgłaszać błędu) napisz przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Podaj wszelkie dane dotyczące produktów: id, nazwa, parametry i różnice. 
Jeśli źle Cię zrozumiałam i to błąd API Allegro, to [podeślij](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b) te załączniki ze zrzutu, żebym mogła sprawdzić jak to od strony API wygląda. Dopisz, że dotyczy wątku na GitHubie #6130.
