### ISSUE TITLE
Problem z zaciąganiem etykiet do Linkera

### ISSUE THREAD

**Issue by Mateuszzicher** [allegro/allegro-api#6132]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by AureliuszBrussy** [comment]
Zgłoś proszę takie problem do supportu aplikacji, z której korzystasz.

**Comment by Mateuszzicher** [comment]
Dzień dobry,

Dziękuje za odpowiedź, zrobiłem to w pierwszej kolejności i dostałem
informacje, ze problem jest po stronie Allegro.

W dniu wt., 20.09.2022 o 13:06 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
@Mateuszzicher aktualnie nie potwierdzam globalnych problemów z generowaniem etykiet do przesyłek wygenerowanych w ramach Wysyłam z Allegro. Nie znając szczegółów nic więcej nie ustalę. Jeżeli support aplikacji potwierdza problemy i twierdzi, że te występują po naszej stronie - najlepiej, jeżeli skontakują się oni bezpośrednio z nami.

**Comment by Mateuszzicher** [comment]
Dzień dobry,

Rozumiem, w jaki sposób maja się z Państwem skontaktować? Przez stworzenie
ticketu czy na adres mailowy?

W dniu wt., 20.09.2022 o 13:38 AureliuszBrussy ***@***.***>
napisał(a):

**Comment by AureliuszBrussy** [comment]
@Mateuszzicher dotarła do mnie informacja, że aktualnie w jednej z usług zewnętrznych trwa awaria, która wpływa na działanie Wysyłam z Allegro. Trwają prace nad przywróceniem działania do normy. Proszę o cierpliwość.
