### ISSUE TITLE
Wyszukiwanie po EAN

### ISSUE THREAD

**Issue by ZIMADEU** [allegro/allegro-api#6135]
Witam
Czy API Allegro umożliwia wyszukiwanie ofert użytkownika po numerze EAN? Np. https://api.allegro.pl/sale/offers?ean=XXX

**Comment by MartaNowaczyk** [comment]
Wszystkie filtry znajdziesz w naszej [dokumentacji](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET). Nie ma tam numeru EAN.
