### ISSUE TITLE
Porozumienie dotyczące dostępu do zasobów REST API

### ISSUE THREAD

**Issue by k0rba** [allegro/allegro-api#6136]
W czerwcu wygasło podpisane przeze mnie porozumienie dotyczące dostępu do zasobu `GET /offers/listing`. Wielokrotnie pisałem do obsługi Allegro w sprawie przedłużenia go; zgłoszenie ma numer 19074388. Cały czas (już ponad trzy miesiące) otrzymuję tylko odpowiedzi w stylu "nadal to konsultujemy". W jaki sposób mogę zmobilizować kogoś do udzielenia mi wiążącej odpowiedzi zanim znowu [utracę dostęp do tego zasobu](https://github.com/allegro/allegro-api/issues/5244)?

**Comment by MartaNowaczyk** [comment]
Przykro mi, ale nie bierzemy udziału w procesie weryfikacji, dlatego pozostaje kontakt mailowy kontynuując odpowiedni wątek.

**Comment by k0rba** [comment]
O jakiej weryfikacji Pani pisze? Moja aplikacja jest już dawno zweryfikowana.

**Comment by MartaNowaczyk** [comment]
Rozumiem, jednak w całym procesie weryfikacji (dostępu lub przedłużenia), jak i innych działaniach dotyczących możliwości korzystania z zasobu` GET /offers/listing` pozostaje ścieżka mailowa i kontynuacja korespondencji. My tutaj nic nie przyspieszymy.
