### ISSUE TITLE
Złe adresy w readme / wybór api

### ISSUE THREAD

**Issue by prugala** [allegro/allegro-api#614]
Cześć

Na początku w readme w sekcji REST Api podlinkowane są złe adresy:
https://developer.allegroapi.io/documentation/
https://developer.allegroapi.io/news/

Teraz pytanie czy Soap api jest dalej wspierane czy tworząc aplikację lepiej opierać się już tylko o Rest api?

**Comment by LukaszKorek** [comment]
Dziękujemy za zgłoszenie w sprawie linków - poprawimy. Odnośnie drugiego pytania - Docelowo REST API Allegro będzie jedynym interfejsem aplikacyjnym, który pozwoli ci zarządzać ofertą i zamówieniami. Szczegółowe informacje, w tym harmonogram, odnadziesz w artykule https://allegro.pl/webapi/news.php/page,2#news_100617

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
_Docelowo REST API Allegro będzie jedynym interfejsem aplikacyjnym, który pozwoli ci zarządzać ofertą i zamówieniami._
@LukaszKorek - a czy osoby, które dwa lata temu składały podobne deklaracje w sprawie WebAPI - wyleciały z roboty ??
