### ISSUE TITLE
REST API. Nie działa aktualizacja ceny + dziwny komunikat

### ISSUE THREAD

**Issue by lukiopmoto** [allegro/allegro-api#6142]
Dzień dobry, 

Próbuję zaktualizować przez REST API cenę aukcji 11969584489 z 5380 na 5624, ale operacja kończy się błędem:

`{"tasks":[{"offer":{"id":"11969584489"},"message":"OPERATION_FAILED","status":"FAIL","scheduledAt":"2022-09-21T14:04:09.474Z","finishedAt":"2022-09-21T14:04:09.458Z","field":"price","errors":[{"code":"ProductSetMinSizeExceeded","message":null,"details":null,"path":"products","userMessage":"Zestaw produktów musi składać się z minimum 1 produktu."}]}]}`

CommandId: 83565447-49fe-4f06-aa5f-0d9964b6468f

Robię normalnie jak zawsze PUT z FIXED_PRICE na sale/offer-price-change-commands.

Dlaczego przy zmianie ceny dostaję informację o jakimś zestawie? Przecież tylko chcę zmienić cenę. Co ma jedno do drugiego? Nie pamiętam żebym w ogóle jakieś zestawy tworzył.

Takich aukcji jest sporo, bo ponad 1000 i zostały dodane przed 25.06.2022 jeżeli to coś pomoże. 

Proszę o pomoc.

**Comment by MartaNowaczyk** [comment]
Mieliśmy już podobne przypadki i robiliśmy poprawkę. Sprawdzę czy to na pewno ten sam przypadek i dam znać.

**Comment by lukiopmoto** [comment]
Ok, to czekam na informację bo nie wiem co z tymi ofertami teraz robić. 

Pozdrawiam
Łukasz

**Comment by MartaNowaczyk** [comment]
Z weryfikacji wynika, że to nie ten sam przypadek jaki był zgłaszany wcześniej. Problemem było odpięcie produktu od oferty. Z naszej strony staramy się naprawić ten problem, bo wygląda na to, że jest to nieprawidłowe działanie.

**Comment by lukiopmoto** [comment]
OK rozumiem. Ale ja go nie odpinałem oferty od produktu, to musiał jakiś automat allegro chyba. Pytanie ile mniej więcej czasu może zająć FIX? Mówimy o minutach, godzinach czy dniach?

**Comment by lukiopmoto** [comment]
Dzień dobry, wracam po kilku dniach i wygląda na to że problem udało się rozwiązać. Możecie Państwo to potwierdzić? Kilkanaście ofert które miały po 50-60 prób zmienienia ceny na nową w końcu się zaktualizowały. Przypadek czy robiliście Państwo coś w kierunku naprawy tego błedu?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, poprawka jeszcze nie jest wdrożona. Możliwe, że edycja takiej oferty przez formularz pomogła.
