### ISSUE TITLE
Prośba o aktywację konta firmowego na sandboxie

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6143]
Występuje problem: 
 - [x] ze środowiskiem testowym / with the test environment

:beetle: **Opis / Description**
Nazwa konta: tomylee999
Zatrzymałem się na _"Jeśli jeszcze nie wykonałeś przelewu, zrób to teraz. Dane do przelewu możesz zobaczyć poniżej."_ 

Pozdrawiam

**Comment by MartaNowaczyk** [comment]
Aktywowałam Twoje konto.

**Comment by tomylee0** [comment]
Dzięki.
