### ISSUE TITLE
Nie mogę wycofać ofert sprzedaży.

### ISSUE THREAD

**Issue by QbcolPL** [allegro/allegro-api#6144]
Nie mogę wycofać ofert sprzedaży.

https://allegro.pl/oferta/12644882622

Sprzęt został uszkodzony dzisiaj rano w wyniku przepięcia.....

**Comment by MartaNowaczyk** [comment]
Niestety, nie pomogę Ci w tym temacie. Zgłoś się proszę przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
