### ISSUE TITLE
API zwraca błąd o obrazkach pomimo ich braku

### ISSUE THREAD

**Issue by SzooX** [allegro/allegro-api#6145]
- [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - 
trace-id: 79857d6e68d4606b

Pomimo nie wysłania żadnych zdjęć, API zwraca błąd OfferImagesNotFoundException Provided image address is incorrect przy próbie wystawienia oferty

**Comment by MartaNowaczyk** [comment]
To pojedynczy przypadek, czy masz więcej takich sytuacji?

**Comment by SzooX** [comment]
Niestety to też jedyny przypadek na jaki natrafiłem. Czy teoretycznie już API powinno pozwolić mi wystawić/edytować ofertę?

**Comment by MartaNowaczyk** [comment]
Tak, powinna być taka możliwość.
