### ISSUE TITLE
Historia oferty

### ISSUE THREAD

**Issue by Himon-SYNCRAFT** [allegro/allegro-api#6146]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment

:beetle: **Opis / Description**

Witam. Mam problem z dojściem co się stało z ofertą o numerze 9217813283.

Z moich logów wynika, że o 22:33 nastąpiłą aktualizacja stocku, a potem oferta została aktywowana.
Dzisiaj dostałem zgłoszenie, że aukcja jest nieaktywna.

Sprawdzając status publikacji dostaje informację: endedBy: 'user' z datą ostatniej aktualizacji na 2022-09-21 22:34.

Czy jest jakiś zasób w api za pomocą, którego mogę prześledzić historię oferty? Ewentualnie czy mogę dostać taką informację od Państwa co się dzialo konkretnie z tą ofertą.

**Comment by AureliuszBrussy** [comment]
Źródłem danych historycznych o ofertach w API jest jedynie dziennik zdarzeń: [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents). W [poradniku opisujemy](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#dziennik-zdarzen-w-ofertach-sprzedawcy), jakie można uzyskać dzięki niemu informacje.

Oferta została zakończona przez jedną z aplikacji zewnętrznych z której ten sprzedający korzysta. Szczegóły możemy udzielić jedynie sprzedającemu na bezpośrednią prośbę - wystarczy, że ten skorzysta z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b), a w nim wskaże numer oferty i opisze sprawę.

**Comment by Himon-SYNCRAFT** [comment]
Dziękuję za pomoc. Skorzystałem z formularza
