### ISSUE TITLE
Publication command : Offer not found. It was deleted, archived or never existed

### ISSUE THREAD

**Issue by lwillems** [allegro/allegro-api#6148]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
We are calling the API to get the inactive offers (to batch activate them)
`GET /sale/offers?publication.status=INACTIVE&limit=100 HTTP/1.1`

Api is replying us with INACTIVE items (truncated response below) :

`{"offers":[{"id":"12645634147","name":"Moneta, TERYTORIA FRANCUSKIE, BOUILLON & SEDAN, 2","category":{"id":"11748"},"primaryImage":{"url":"https://a.allegroimg.com/original/11597c/a80309544874a3eefd1979be685a"},"sellingMode":{"format":"BUY_NOW","price":{"amount":"450.0","currency":"PLN"},"minimalPrice":null,"startingPrice":null},"saleInfo":{"currentPrice":null,"biddersCount":0},"stats":{"watchersCount":0,"visitsCount":0},"stock":{"available":1,"sold":0},"publication":{"status":"INACTIVE","startingAt":null,"startedAt":null,"endingAt":null,"endedAt":null},"afterSalesServices":{"warranty":null,"returnPolicy":{"id":"589b6b03-fc44-4a02-849f-cf3bc0b0d235"},"impliedWarranty":{"id":"e9f1a2fa-700d-4823-9ebd-6b5ae9b61d8a"}},"additionalServices":null,"external":{"id":"32810"},"delivery":{"shippingRates":null},"b2b":{"buyableOnlyByBusiness":false}}],"count":4,"totalCount":4}`

Then we are sending a publication batch (also truncated) : 
`PUT /sale/offer-publication-commands/xxxx`
`{
    "offerCriteria": [
        {
            "offers": [
                "12645634147"
            ],
            "type": "CONTAINS_OFFERS"
        }
    ],
    "publication": {
        "action": "ACTIVATE"
    }
}
`
When checking batch status :

`GET /sale/offer-publication-commands/xxxx`

`{"tasks":[{"offer":{"id":"12645634147"},"message":"Could not change offer publication status. Oferta nieznaleziona. Została usunięta, zarchiwizowana lub nigdy nie istniała.","status":"FAIL","scheduledAt":"2022-09-22T12:00:11.13Z","finishedAt":"2022-09-22T12:00:11.127Z","field":"publication","errors":[{"code":"NOT_FOUND","message":"Offer not found. It was deleted, archived or never existed.","details":null,"path":null,"userMessage":"Oferta nieznaleziona. Została usunięta, zarchiwizowana lub nigdy nie istniała."}]},{"offer":{"id":"12649377288"},"message":"","status":"SUCCESS","scheduledAt":"2022-09-22T12:00:11.412Z","finishedAt":"2022-09-22T12:00:11.41Z","field":"publication","errors":[]}]}
`
Status is FAIL so try to delete offer : 
`DELETE /sale/offers/12645634147 HTTP/1.1`

Got a 404 not found

`{"errors":[{"code":"NOT_FOUND","message":"Offer not found. It was deleted, archived or never existed.","details":"NOT_FOUND","path":null,"userMessage":"Offer not found. It was deleted, archived or never existed."}]}`

But when restarting full process this offer is still returned as inactive so it leads to an infinite loop.

Thx for your help

Regards

**Comment by AureliuszBrussy** [comment]
@lwillems It looks like we should not return this draft for GET /sale/offers because it has been archived. I reported this error to the team responsible for this resource. I'll be back with an update on the fix.

**Comment by AureliuszBrussy** [comment]
We have fixed this - this offer draft should no longer be returned for GET /sale/offers.

**Comment by lwillems** [comment]
@AureliuszBrussy seems always returned i have tried a few minutes ago ..

**Comment by AureliuszBrussy** [comment]
Yes, I confirm this problem still occurs - we are still returning this offer. I have again reported this to the team responsible for this resource.

**Comment by AureliuszBrussy** [comment]
@lwillems currently this draft offer should not be returned - please confirm if the problem has been solved.

**Comment by lwillems** [comment]
@AureliuszBrussy 

Yes it seems fixed since Oct 6, 2022, 12:41:11 PM UTC

Thx
