### ISSUE TITLE
Endpoint for "ship from" adrresses

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6149]
Hi, when using ship with Allegro, we need to include ship from (pickup) adress when creating parcel. When done from you GUI, adresses set in "Ustawienia zamówień" can be used. Is there an API endpoint, we can use to obtain these adrresses, or do we need to store them in our aplication?
![image](https://user-images.githubusercontent.com/109143627/191761803-6f441d0b-abaa-4960-b7ef-e434d509a6c2.png)
![image](https://user-images.githubusercontent.com/109143627/191762481-678c883e-3e4f-4172-b32f-8078f8edfbd5.png)

Thanks

Jirka

**Comment by MartaNowaczyk** [comment]
Hi, in Allegro API, we don't provide such an address book of the sender - in this case, the creation and storage of such data is currently the responsibility of the application.

**Comment by ZajdaBear** [comment]
Thanks for the information.

Jirka
