### ISSUE TITLE
Problem z komuniakcją sklepu shopgold z kontem allegro

### ISSUE THREAD

**Issue by TomKowalsk** [allegro/allegro-api#6151]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

 brak komunikacji sklepu shopgold z serwerem allegro, zresetowaliśy REST API, na nowych ustawieniach nadal łączenie trwa w nieskończoność. Po podłączeniu innego aktywnego konta komunikacja bez problemu. Konto którego dotyczy problem to udekorowac_pl
Problem pojawił się dziś, do wczoraj sklep działał bez zarzutu. Producent oprogramowania po sprawdzeniu potwierdził brak komunikacji po stronie allegro

**Comment by MartaNowaczyk** [comment]
W naszych logach widzimy requesty dla tego konta, ale nie wiem czy to tej aplikacji to dotyczy. Możecie podać więcej szczegółów opisanej sytuacji? Może początek i koniec Client ID na którym nie działa aplikacja i jakiś błąd, który dostajecie. W innym wypadku ciężko będzie cokolwiek znaleźć.

**Comment by TomKowalsk** [comment]
Witam, komunikacja się poprawiła, sklep widzi aukcje ale nie można ich edytować z poziomu sklepu. Po wybraniu edycji pojawia się komunikat "Błąd w serwisie allegro"

**Comment by TomKowalsk** [comment]
ID 480xx215

**Comment by TomKowalsk** [comment]
Takie dokładnie info mamy:
Błąd w serwisie Allegro - nie można zaktualizować danych
Access is denied

**Comment by MartaNowaczyk** [comment]
Ten komunikat nic nam nie mówi, bo jest z aplikacji, z której korzystasz. Skontaktuj się proszę z obsługą shopgold, aby wyjaśnić ten problem. Jeśli stwierdzą, że błąd jest po naszej stronie, mogą skontaktować się bezpośrednio z nami lub niech podadzą Ci trace-id dla problemowej sytuacji, abyśmy mogli to zweryfikować.
