### ISSUE TITLE
Problem z nadaniem przesyłki - Allegro One Kurier

### ISSUE THREAD

**Issue by michal-dulik** [allegro/allegro-api#6152]
Występuje problem: Problem z nadaniem przesyłki
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Podczas próby stworzenia przesyłki np dla usługi: `Allegro One Box (One Kurier) - dostawa dzisiaj` dostaje w odpowiedzi błąd: `Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej.`

Błąd występuję również dla metod: `'Allegro One Kurier - dostawa jutro', 'Allegro One Kurier - dostawa dzisiaj', 'Allegro One Box (One Kurier) - dostawa dzisiaj'`

### PUT /parcel-management/parcel-create-commands/
Request:
```json
{
   "serviceId":19793040,
   "receiver":{
      "address":{
         "street":"...",
         "postCode":"30-198",
         "city":"Kraków",
         "countryCode":"PL",
         "county":null
      },
      "email":"...",
      "name":"...",
      "company":"...",
      "phone":"..."
   },
   "pickup":{
      "address":{
         "street":"...",
         "postCode":"...",
         "city":"...",
         "countryCode":"PL"
      },
      "email":"...",
      "name":"...",
      "company":"...",
      "phone":"..."
   },
   "items":[
      {
         "dimensions":{
            "height":{
               "value":10,
               "unit":"CENTIMETER"
            },
            "width":{
               "value":10,
               "unit":"CENTIMETER"
            },
            "depth":{
               "value":10,
               "unit":"CENTIMETER"
            }
         },
         "weight":{
            "value":"10",
            "unit":"KILOGRAM"
         },
         "description":"Ksiazki\/Gry\/Zabawki",
         "type":"PACKAGE"
      }
   ],
   "type":"PACKAGE"
}
```
Response:
```json
{
   "id":"0a0c86f1-cee2-4d54-a4d0-45b1a94b5f08",
   "input":{
      "serviceId":"19793040",
      "label":null,
      "receiver":{
         "name":"...",
         "company":"...",
         "address":{
            "street":"...",
            "postCode":"30-198",
            "city":"Kraków",
            "county":null,
            "countryCode":"PL"
         },
         "pointId":null,
         "email":"...",
         "phone":"..."
      },
      "pickup":{
         "name":"...",
         "company":"...",
         "address":{
            "street":"...",
            "postCode":"...",
            "city":"...",
            "county":null,
            "countryCode":"PL"
         },
         "pointId":null,
         "email":"...",
         "phone":"..."
      },
      "items":[
         {
            "dimensions":{
               "height":{
                  "value":"10",
                  "unit":"CENTIMETER"
               },
               "width":{
                  "value":"10",
                  "unit":"CENTIMETER"
               },
               "depth":{
                  "value":"10",
                  "unit":"CENTIMETER"
               }
            },
            "weight":{
               "value":"10",
               "unit":"KILOGRAM"
            },
            "description":"Ksiazki/Gry/Zabawki",
            "value":null,
            "type":"PACKAGE"
         }
      ],
      "type":"PACKAGE",
      "additionalServices":null
   }
}
```

### GET /parcel-management/parcel-create-commands/0a0c86f1-cee2-4d54-a4d0-45b1a94b5f08
Response:
```json
{
   "id":"0a0c86f1-cee2-4d54-a4d0-45b1a94b5f08",
   "parcelId":null,
   "status":"ERROR",
   "errors":[
      {
         "code":"ERROR",
         "message":"Processing error",
         "details":null,
         "path":null,
         "userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."
      }
   ]
}
```

**Comment by MartaNowaczyk** [comment]
Weryfikujemy opisaną sytuację. Wrócę z odpowiedzią.

**Comment by GunFix** [comment]
Pani Marto dziękujemy za podjęcie tematu. Zgłoszenie jest o tyle istotne dla nas jak i Pana Rafała koordynującego "allegro one" w Panstwa strukturze, że dotyczy wdrożenia tej funkcjonalności u jednego z największych państwa partnerów w jednej z głównych kategorii. Jeśli były by potrzebne jakiekolwiek dodatkowe informacje albo dzialania z naszej strony prosimy dać znać.

**Comment by MartaNowaczyk** [comment]
Sprawdziliśmy i One Kurier jest niedostępny w Bielsko-Białej pod kodem 43-382. Czyli Partner nie powinien dodawać metody dostawy w cenniku, bo nie jest w stanie tego nadać. Można to sprawdzić [tutaj](https://allegro.pl/kampania/one/kurier). Jeśli macie pytania o brak dostępności tej metody dostawy, kierujcie je proszę na adres onehandlowy@allegro.pl. Pozdrawiam.

**Comment by GunFix** [comment]
Pani Marto nasz magazyn realizuje wysyłki tylko i wylacznie z Krakowa. Dla tej też lokalizacji realizujemy projekt z Panem Rafałem.

**Comment by michal-dulik** [comment]
Pani Marto

Dla `pickup` z KRK również otrzymujemy taki sam błąd:
```json
"pickup":{
   "name":"...",
   "company":"...",
   "address":{
      "street":"...",
      "postCode":"30-740",
      "city":"Kraków",
      "county":null,
      "countryCode":"PL"
   },
   "email":"...",
```

TrackingId: `ff2f2198-0331-44f9-8a27-71b770f80273`

**Comment by MartaNowaczyk** [comment]
To jest zamówienie Allegro One Box - czyli doręczenie powinno być do One Box, a nie na "adres". Brakuje ID punktu.

**Comment by michal-dulik** [comment]
TrackingId: `c74f2e7d-d75a-4548-8e06-3f9f876d05e4`
Metoda dostawy: `Allegro One Kurier - dostawa dzisiaj`

**Comment by MartaNowaczyk** [comment]
To inny błąd. Sprawdź czy masz wprowadzony odpowiedni serwis do metody dostawy. Poniżej znajdziesz pełne rozróżnienie metod dostawy na serwis:

Metoda dostawy: Allegro One Punkt
Serwis: Allegro One (UPS)
---
Metoda dostawy: Allegro One Box
Serwis: Allegro One (UPS)
---
Metoda dostawy: Allegro One Punkt (One Kurier)
Serwis: Allegro One Punkt (One Kurier) (na Sandbox: Allegro One Punkt (One Kurier) - dostawa jutro)
---
Metoda dostawy: Allegro One Box (One Kurier)
Serwis:Allegro One Box (One Kurier) (na Sandbox: Allegro One Box (One Kurier) - dostawa jutro)
---
Metoda dostawy: Allegro One Kurier - dostawa dzisiaj
Serwis: Allegro One Kurier
---
Metoda dostawy: Allegro One Kurier - dostawa jutro
Serwis: Allegro One Kurier

Metody z dopiskiem (do 01.07.2022) oraz pobraniowe NIE SĄ obsługiwane w WzA.
