### ISSUE TITLE
Problem z etykietami PDF Allegro One Box, Kurier

### ISSUE THREAD

**Issue by SoDaUser** [allegro/allegro-api#6153]
Występuje problem: 
 - [X] ze środowiskiem produkcyjnym / with the production environment

Witam

Mam problem z etykietami PDF pobranymi z Allegro REST API
Chodzi o etykiety Allegro One Box, Kurier.  
Etykiety Allegro One (UPS) nie sprawiają tych problemów.

Etykiety bez problemu wyświetlają się w oknie przeglądarki, jednak nie można ich otworzyć w Acrobat Reader. 
Przy próbie otworzenia wyskakuje okienko Drukuj. (jak w załączniku) a sama etykieta nie wyświetla się nawet w oknie AR.

Wykorzystujemy Acrobat Reader w aplikacji desktopowej do wydruku etykiet i jedyną opcją jest dla nas wydruk w tle.
Te etykiety to pierwszy przypadek, że Acrobat zachowuje się w ten sposób. 

  

![okno](https://user-images.githubusercontent.com/44569188/192163041-d7a21d0a-cd25-4c61-84b9-0fd9d383ab4c.jpg)

**Comment by AureliuszBrussy** [comment]
@SoDaUser możesz spróbować wyłączyć JavaScript dokumentów z poziomu Adobe Readera. Skorzystaj z opcji Edit -> Preferences -> JavaScript i odznacz "Enable Acrobat JavaScript". Jeżeli to nie rozwiązuje problemu - daj znać.

**Comment by SoDaUser** [comment]
W moich testach to rozwiązało mój problem, jutro idzie na produkcję :)

Dziękuję, dziękuję, to bardzo dobra wiadomość z rana !
