### ISSUE TITLE
Problem z publikacją towaru z podpiętym produktem z specyfikacją TecDoc

### ISSUE THREAD

**Issue by navlukaszzborek** [allegro/allegro-api#6154]
Występuje problem: 
 - [x ] z zasobem REST API / with a REST API resource
 - [x ] ze środowiskiem produkcyjnym / with the production environment

Witam,
mam problem z opublikowaniem oferty z przypisanym produktem o identyfikatorze 405e2336-284e-4844-9ff6-52f53272b9cf. Korzystamy jeszcze ze "starej" metody /sale/offers. Przepisuje wszystkie pola z produktu do oferty (w tym compatibilityList i tecdocSpecification). Jednak przy próbie opublikowania oferty, dostaje bład "Wskazany produkt nie posiada specyfikacji technicznej TecDoc, nie przypisuj jej do oferty. ". Błąd jest mylący ponieważ produkt który podałem taką specyfikacje posiada (tecdocSpecification) więc nie rozumiem problemu. Tymbardziej że nie jest to odosobniony przypadek.
Co w takiej sytuacji zrobić? (Rozwiązanie typu w tym przypadku nie podawać specyfikacji TecDoc w ofercie odpada lub prosze o wskazanie jak rozpoznać, że w tym przypadku tej specyfikacji nie powinno być)

Identyfikator publikacji: f3b49f58-01f5-4822-ba3a-4f27a0aacf0a
Znajduje się tam publikacja jednej oferty z błedem.

**Comment by Lukasz-Zurek** [comment]
Komunikat może wprowadzać w błąd. Produkt, którego próbujesz użyć nie powinien być zwracany przez nasze API, dlatego problem ten wyjaśniam z odpowiednim zespołem. Przepraszamy za te utrudnienia.

Właściwy produkt w tej sytuacji to ten o identyfikatorze: c9f00a35-7647-4692-8455-bb4442055b8b. Spróbuj skorzystać z niego podczas wystawiania oferty.

**Comment by navlukaszzborek** [comment]
Dzięki, zmiana produktu pomogła.
Pytanie co z innymi przypadkami, zapewne wszędzie gdzie dostaję ten błąd odepnę aktualnie przypisany produkt, aby wyszukało na nowo. Jednak dobrze by było, gdyby przy pobieraniu produktu próbie aktywacji lub tworzenia draftu był błąd w stylu "produkt nie znaleziono" albo "produkt nie dostępny". A tak to operujemy trochę na zasadzie domysłu.

**Comment by Lukasz-Zurek** [comment]
@navlukaszzborek Potwierdzam, że komunikat powinien być inny. Aczkolwiek tego typu produkty nie powinny być w ogóle zwracane w naszym API. Konsultuję ten temat z zespołem odpowiedzialnym za produkty. Jak tylko uzyskam konkretne informacje, wrócę do Ciebie w tym wątku.

**Comment by navlukaszzborek** [comment]
Trochę czasu minęło, czy coś się zmieniło w kwestii pobierania produktów których nie powinny być widoczne?

**Comment by Lukasz-Zurek** [comment]
@navlukaszzborek Temat już wcześniej przekazałem do zespołu odpowiedzialnego za prodpktyzację w naszym Serwisie. Faktycznie tego typu sytuacje mogą się czasem zdarzyć i tu wspomniany zespół na bieżąco to monitoruje i reaguje. Jeśli zauważysz nowe podobne przypadki - podeślij je proszę w tym wątku. 

Przepraszamy za te utrudnienia.

**Comment by navlukaszzborek** [comment]
Przykładowy: 2ce7871f-bbfb-43ec-a29c-08c5357ffb38
Produkt wyszukany jakiś czas temu i zapisany. Teraz próba wystawienia oferty z nim kończy się błędem na etapie publikacji. W wyszukiwaniu produktów po 'KYB 341177' nie znajduje go, ale pobranie po identyfikatorze bez problemu go zwraca

**Comment by Lukasz-Zurek** [comment]
@navlukaszzborek Dziękuję. Potwierdzam ten problem. Przekazałem do odpowiedniego zespołu.

Przepraszamy za zaistniałe utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@navlukaszzborek Wspomniany produkt zwracamy w wynikach, natomiast w id jest 826b449f-fcfd-48f9-a48f-4cbf6c79ce50. Dotychczas dostępne były dwa produkty i tu nastąpiło ich scalenie. Nowe id to: 826b449f-fcfd-48f9-a48f-4cbf6c79ce50 i takie zwracamy zarówno po wysłaniu żądania GET /sale/products/2ce7871f-bbfb-43ec-a29c-08c5357ffb38, jak i  GET /sale/products?phrase=KYB 341177.
