### ISSUE TITLE
Wysyłam z Allegro - DPD Pickup

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#6155]
Proszę o informację odnośnie zasilania struktury żądania REST w przypadku gdy:
- klient wybiera DPD Pickup i wskazuje punkt odbioru
- wysyłka paczki będzie z magazynu centralnego wraz z pozostałymi przesyłkami kuriera DPD

Niestety przewodnik w tym obszarze jest dla mnie dość niejasny i nie wskazuje, jakie dane powinny znaleźć się w obiekcie "pickup", którego API wymaga.
Czy mamy w nim podać dane adresowe punktu nadawcy, czy punktu odbiorcy? Jeśli nadawcy, nie będziemy w stanie dostarczyć Point ID (nadanie z magazynu), jeśli odbiorcy - jaki jest sens duplikowania danych i dodatkowego zasilania struktury (obiekt jest wymagany), jeśli w przypadku DPD wystarczy podanie samego identyfikatora PUDO, zatem pointId w strukturze reciever powinno być wystarczające?

W przypadku COD rozumiem, że w polach:
name: podajemy nazwę nadawcy paczki - w tym przypadku nazwę firmy
accountNumber: podajemy numer rachunku, na który Allegro przekaże pobraną od klienta opłatę dodatkową za pobranie?

Dodatkowo - przy próbie zamówienia z wybraną opcją DPD PICUKUP na środowisku sandbox otrzymuję komunikat:
Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy
Przykładowo:
{"id":"0a800b76-fdab-45f2-929f-a022857effd3","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Order cannot be send using selected delivery service","details":null,"path":null,"userMessage":"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"}]}

{"id":"da1275a9-e4bf-4618-8dcf-52edf067dcea","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Order cannot be send using selected delivery service","details":null,"path":null,"userMessage":"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"}]}
TraceId:  dla ostatniego komunikatu: 5d30060635b0b56

Lista usług jest pobierana z https://api.allegro.pl.allegrosandbox.pl/parcel-management/delivery-services z użyciem tokena dla konta, które mamy utworzone na sandbox.

**Comment by AureliuszBrussy** [comment]
W strukturze "**pickup**" należy podać dane nadawcy - czyli dane, spod których przesyłka zostanie odebrana od nadawcy. W **pickup.pointId** można wskazać identyfikator punktu nadawczego, spod którego przesyłka zostanie nadana. Numer punktu można uzyskać np. z API przewoźnika. Samo Wysyłam z Allegro służy do nadawania przesyłek za pomocą różnych firm kurierskich, dlatego niektóre pola dla jednego przewoźnika mogą być wymagane, a dla innego nie.

Co do przesyłek COD - tak, w polu **additionalServices.cashOnDelivery.accountNumber** podajesz numer rachunku, na który ma zostać wysłana kwota pobrania, a w **additionalServices.cashOnDelivery.name** podajesz nazwę odbiory przelewu. 

Dla metody dostawy w tym zamówieniu ("Allegro Odbiór w Punkcie DPD Pickup pobranie") powinieneś wybrać usługę "Allegro DPD". Dla tego konta id tej usługi to 9628762. W swoich przykładowych requestach wskazałeś id 111608447. Nie jestem pewien, skąd pobrałeś ten id, dla tego konta po pobraniu dostępnych usług ([GET /parcel-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getAvailableDeliveryServices)) zwracamy właśnie 9628762 dla usługi o nazwie "Allegro DPD".

**Comment by Wojtu204** [comment]
Dziękuję za wyjaśnienie - faktycznie w przypadku ID usługi miałem stare mapowanie zmiennych - poprawione :)
Wygląda na to, że API przyjmuje żądanie bez pickup.pointId nadawcy.
W receiver.pointId polecam użyć: PL50004 - na tym punkcie udało mi się założyć paczkę :)

**Comment by Wojtu204** [comment]
Aktualizacja - Punkt DPD Pickup na który udaje się poprawnie założyć paczki przez Państwa API to PL90001
