### ISSUE TITLE
Brak synchronizacji Allegro-DHLParcel problem API?

### ISSUE THREAD

**Issue by smiecieok** [allegro/allegro-api#6156]
Jak w temacie, nie moge wysyłac palet przez llegro-dhl bo konta nie sa zsynchronizowane pomimo tego ze klucz API został wygenerowany poprawnie.  Przy próbie n adania przesyłki nie mam opcji paleta jak w załaczniku.

![ScreenHunter_01 Sep  26 13 35](https://user-images.githubusercontent.com/114404106/192268372-a8c0e0ed-9eb0-4552-b02d-6731cb2a096b.jpg)
![all](https://user-images.githubusercontent.com/114404106/192268402-ebe4ab22-4750-4b23-ac1c-5b68ceb5991a.jpg)

**Comment by smiecieok** [comment]
zał.aczniki
![all](https://user-images.githubusercontent.com/114404106/192267091-5a35d220-3b02-40e2-975d-008f406fb832.jpg)
![ScreenHunter_01 Sep  26 13 35](https://user-images.githubusercontent.com/114404106/192267101-3363d6d5-2680-4713-8715-e9c2bbe93d51.jpg)

**Comment by AureliuszBrussy** [comment]
W Wysyłam z Allegro nie wspieramy jeszcze palet. Przesyłki takie wyślesz na ten moment bezpośrednio z poziomu DHL24.

**Comment by smiecieok** [comment]
Z poziomu dhl nie moge zamówic wg cennika z umowy dhlparcel

**Comment by AureliuszBrussy** [comment]
Nie jest już to kwestia związana bezpośrednio z API. Aby uzyskać pomoc - skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
