### ISSUE TITLE
Brak możliwości przesłania zdjęcia (mimo iż link jest porpawny) - DownloadError.GatewayTimeout

### ISSUE THREAD

**Issue by pawliszka** [allegro/allegro-api#6157]
Url podawany w odpowiedzi z Allegro (jak i ten przesyłany do api) działa w przeglądarce bez większych problemów. (Testowane z naszej sieci i z zewnątrz).

Czy to jest błąd allegro czy wina leży po naszej stronie?

TraceID: 26ae4e1301a489ea

{"errors":[{"code":"DownloadError.GatewayTimeout","message":"Downloading image from URL ' TUTAJ URL ' failed. Server returned the following HTTP status code: 504 GATEWAY_TIMEOUT and response body: 'The remote server timed out'.","details":null,"path":"productSet[0].product.images","userMessage":"Downloading image from URL ' TUTAJ URL ' failed. Server returned the following HTTP status code: 504 GATEWAY_TIMEOUT and response body: 'The remote server timed out'."}]}

**Comment by AureliuszBrussy** [comment]
Poprosiłem zespół odpowiedzialny za usługę pobierania zdjęć o sprawdzenie tego przypadku. Wrócę do Ciebie z informacją.

**Comment by pawliszka** [comment]
zweryfikowałem teorię, że problemem jest niestandardowy port w URL, czy Allegro ma jakieś limity na adresy URL, port może mieć wartość tylko 80 i 443 czy nie ma żadnych limitów i zaisrniała sytuacja jest błędem?

**Comment by AureliuszBrussy** [comment]
@pawliszka masz rację - problem wynika stąd, że ze względów bezpieczeństwa my nie wspieramy pobierania z innych portów niż standardowe dla http i https. W tym przypadku port jest niestandardowy.

**Comment by pawliszka** [comment]
@AureliuszBrussy chciałbym się tylko upewnić, że: "jest to celowe działanie Allegro" nie błąd? Bo jeszcze jakiś czas temu takie rozwiązanie wysyłania zdjęć działało bez problemu a teraz ta zmiana wymaga od nas dość srogiej ingerencjii w konfigurację serwerów, routerów, domen etc. stąd pytanie, zdecydowanie wolał bym żeby dalej można było wysyłać foty z niestandardowego portu :)

**Comment by AureliuszBrussy** [comment]
@pawliszka nie, nie jest to błąd po naszej stronie - działanie jest świadome.
