### ISSUE TITLE
[BUG] Produkty tymczasowe... Durne komunikaty błędów!

### ISSUE THREAD

**Issue by FromAnyHole** [allegro/allegro-api#6158]
VALIDATION_ERROR:
Given temporary product is linked to other offer.
Podany produkt tymczasowy jest przypisany do innej oferty.

Sprawdzamy rzeczony Produkt tymczasowy:
[offerRequirements][id] => FALSE
[isDraft] => FALSE !!

Oby tak dalej...

**Comment by AureliuszBrussy** [comment]
Flaga **isDraft** nie informuje o tym, czy produkt jest tymczasowy, tylko o tym, czy produkt jest draftem. Produkt tymczasowy i draft to różne, niezależne od siebie byty. 

O produkcie tymczasowym możesz [przeczytać w newsie](https://developer.allegro.pl/news/w-wybranych-kategoriach-bedziemy-tworzyc-produkty-tymczasowe-nn9Y12dbqHM). Produkt taki rozpoznasz dzięki polu **id** w sekcji **offerRequirements**. Zwrócimy w nim identyfikator oferty, na podstawie której go utworzyliśmy - produkt może zostać połączony wyłącznie ze wskazaną ofertą.

Z kolei o drafcie produktów piszemy [tutaj](https://developer.allegro.pl/news/drafty-produktow-wprowadzilismy-nowy-filtr-oraz-pole-w-wyszukiwarce-produktow-yPm5l3Ow1s6).

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - super, cieszymy się jak dzieci!!

Tylko co kiedy pole [id] również jest puste?? A mam tu i takie kwiatki...

**Comment by AureliuszBrussy** [comment]
@FromAnyHole podaj proszę id takich produktów (ew. trace-id wywołań, gdzie zwróciliśmy rzeczony komunikat błędu) - przeanalizujemy to.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - pytanie za $1-Bilion: Po co istnieje możliwość wiązania INNEJ oferty z Produktem tymczasowym, skoro jest on ewidentnie dla JEDNEJ oferty w całym serwisie?? Bałagan sami tworzycie, a to blokuje edycje potem...

**Comment by AureliuszBrussy** [comment]
Nie istnieje możliwość powiązana innej oferty z produktem tymczasowym - produkt taki może być połączony tylko z tą jedną ofertą, na rzecz której powstał. Produktów tymczasowych nie zwrócimy w wyszukiwarce [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts), ale szczegóły takiego produktu pobierzesz za pomocą [GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct) - ale tylko jeśli znasz jego identyfikator.

**Comment by hahyes** [comment]
@FromAnyHole XD

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - no dobra, skoro nadworny idiota już się wypowiedział, to konkrety do Pana:

Panie Aureliuszu - Produkt tymczasowy: "f06a4f49-060d-4c4b-9eac-fb889038d7f7", który stworzyliście do oferty ze stanem innym niż "nowy", jeszcze dwa dni temu w niedzielę miał powiązanie z INNĄ ofertą z INNEGO konta (nawet na inny NIP).

I co teraz, przeprosi Pan publicznie?? Ja mam dowody, ale celowo tu nie publikuję...
Sami sobie sprawdźcie historię zdarzeń (powiązań) na Produkcie, macie ID i wystarczy.

**Comment by hahyes** [comment]
@FromAnyHole Przeprosić to ty powinieneś za twoje zachowanie, bo z kulturą to nic wspólnego nie ma.

**Comment by AureliuszBrussy** [comment]
Bardzo proszę o zachowanie kultury dyskusji i zaprzestanie konfliktu - obrażanie się nawzajem nie przybliży nas do rozwiązywania problemów na forum. 

Ten produkt tymczasowy (f06a4f49-060d-4c4b-9eac-fb889038d7f7) od samego początku został stworzony na potrzeby oferty 12320352158 - tak jak aktualnie wskazujemy  w polu **offerRequirements.id** przy odpytywaniu o jego szczegóły. Oferta została już zarchiwizowana - ten produkt tymczasowy zostanie po pewnym czasie całkowicie usunięty. 

Natomiast faktycznie potwierdzam - produkt ten jest podpięty także pod inne oferty. I tutaj występuje błąd po nasze stronie. Nie powinno się tak zdarzyć. Problem ujawnił się przy próbie edycji oferty, która nie powinna być powiązana z tym produktem.  Zespół odpowiedzialny za tą usługę już dokładniej weryfikuje ten problem. 

Wrócę z informacjami.

**Comment by AureliuszBrussy** [comment]
Poprawka jest już wdrożona - aktualnie tymczasowy produkt może być przypisany tylko do oferty na rzecz której powstał.

**Comment by FromAnyHole** [comment]
@AureliuszBrussy - jest luzik, czyli to wyjątki potwierdzają reguły, warto było!

p.s.
Jak ktoś co chwila wtrąca się tam gdzie nie trzeba, to niech zmieni zajęcie. Osobnik ten uczy innych kultury, a sam napisał w swoim wątku o "pracy po pijaku" w Allegro. Niedawno też Tomek Grzesik go pogonił u siebie za brednie, no i dobrze!!

**Comment by hahyes** [comment]
> p.s. Jak ktoś co chwila wtrąca się tam gdzie nie trzeba, to niech zmieni zajęcie. Osobnik ten uczy innych kultury, a sam napisał w swoim wątku o "pracy po pijaku" w Allegro. Niedawno też Tomek Grzesik go pogonił u siebie za brednie, no i dobrze!!

@FromAnyHole Ja popełniam błędy i umiem to przyznać w odróżnieniu od niektórych krzykaczy. :)

**Comment by FromAnyHole** [comment]
Ukrywanie wątków jest cechą biedy umysłowej, zacytuję więc poziom kultury:

"Nie jestem pewien, czy to bug w API czy ktoś przyszedł pijany do pracy?"

**Comment by MartaNowaczyk** [comment]
@hahyes & @FromAnyHole można się tu wypowiadać jeśli macie taką potrzebę, ale w temacie API Allegro, rozwiązań z jakich korzystacie itp. Wasza dyskusja o tym, kto jak się zachowuje, nic nie wnosi. Przełączcie się proszę na priv, bo to nie jest na to miejsce.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - przy okazji Pani Marto, rozważcie może zmianę ustawień na tym forum, aby ważne merytorycznie wątki (lub oczekujące na rozwiązanie) nie mogły być ukrywane przez co poniektórych egoistów. To ważne i dla Was, bo nie każdy tu użyje wyszukiwarki, a jak po 2-3 dniach ktoś ukrywa wątek tylko "dla siebie", to czasem temat wraca, całkiem niepotrzebnie.

**Comment by hahyes** [comment]
> Ukrywanie wątków jest cechą biedy umysłowej, zacytuję więc poziom kultury:
> "Nie jestem pewien, czy to bug w API czy ktoś przyszedł pijany do pracy?"

@FromAnyHole Lekcja na dzisiaj:
Na Githubie zgłoszenia oznaczamy jako otwarte i zamknięte. Nadal każdy ma dostęp do zamkniętego zgłoszenia, po prostu domyślny filtr wyświetlania na Githubie wyświetla otwarte wątki.
![image](https://user-images.githubusercontent.com/37104952/193054200-0c3dd5b2-e953-4a4e-a9b5-07e15a72f109.png)
Usuń filtry i zobaczysz wszystkie "ukryte" wątki. Proszę do mnie nie mieć pretensji, że ja coś ukrywam. Bo ja niczego nie ukryłem. Zamykanie rozwiązanych wątków to jest standardowa praktyka na Githubie, tak też są domyślnie ustawione filtry przez Microsoft.
Na dodatek każdy tutaj może wrócić z wyszukiwarki Google, bo zamknięte wątki też są indeksowane w niej.

**Comment by MartaNowaczyk** [comment]
@FromAnyHole dziękujemy za sugestię. Nie mamy w planach zmian w ustawieniach forum, ale temat przedyskutujemy.

**Comment by FromAnyHole** [comment]
@MartaNowaczyk - Okay, nie wiem nawet czy można tak forum moderować, ale miłego weekendu ŻyCzę ;-)
