### ISSUE TITLE
Metoda doShowItemInfoExt zwraca niepoprawny czas zakończenia oferty

### ISSUE THREAD

**Issue by fredzi** [allegro/allegro-api#616]
Metoda doShowItemInfoExt zwraca itEndingInfo = 2 i niepoprawny czas zakończenia itEndingTime. Np. aukcja 7515228277 jest do wyczerpania zapasów i dalej trwa na allegro a api zwraca niepoprawne informacje jak wyżej.

**Comment by fredzi** [comment]
Teraz jest ok, ale to tylko dzieje się w określonym momencie czasowym. Np. ta poniższa odpowiedź wystąpiła 16.09.2018 16:36

array (
  'item-list-info-ext' => 
  stdClass::__set_state(array(
     'it-id' => 7515228277,
     'it-country' => 1,
     'it-name' => 'Toshiba C55-B5350 Core i3-4005U 15,6 6GB RAM 750GB',
     'it-price' => 0,
     'it-bid-count' => 0,
     'it-ending-time' => 1537108498,
     'it-seller-id' => 43394085,
     'it-seller-login' => 'servecom_pl',
     'it-seller-rating' => 0,
     'it-starting-time' => 1534515894,
     'it-starting-price' => 0,
     'it-quantity' => 1,
     'it-foto-count' => 4,
     'it-reserve-price' => 0,
     'it-location' => 'Częstochowa',
     'it-buy-now-price' => 1599,
     'it-buy-now-active' => 1,
     'it-advertisement-price' => 0,
     'it-advertisement-active' => 0,
     'it-high-bidder' => 0,
     'it-high-bidder-login' => '',
     'it-description' => '',
     'it-standardized-description' => '',
     'it-options' => 50331940,
     'it-state' => 12,
     'it-wire-transfer' => 8.9900000000000002131628207280300557613372802734375,
     'it-post-delivery' => -1,
     'it-post-info' => '',
     'it-quantity-type' => 0,
     'it-is-eco' => 0,
     'it-hit-count' => 188,
     'it-postcode' => '',
     'it-vat-invoice' => 1,
     'it-vat-margin-invoice' => 0,
     'it-without-vat-invoice' => 0,
     'it-bank-account1' => '',
     'it-bank-account2' => '',
     'it-starting-quantity' => 1,
     'it-is-for-guests' => 0,
     'it-has-product' => 0,
     'it-order-fulfillment-time' => 48,
     'it-ending-info' => 2,
     'it-is-allegro-standard' => 0,
     'it-is-new-used' => 1,
     'it-is-brand-zone' => 0,
     'it-is-fulfillment-time-active' => 1,
     'it-ean' => '',
     'it-contact' => '',
  )),
  'item-cat-path' => 
  array (
    0 => 
    stdClass::__set_state(array(
       'cat-level' => 0,
       'cat-id' => 2,
       'cat-name' => 'Komputery',
    )),
    1 => 
    stdClass::__set_state(array(
       'cat-level' => 1,
       'cat-id' => 491,
       'cat-name' => 'Laptopy',
    )),
    2 => 
    stdClass::__set_state(array(
       'cat-level' => 2,
       'cat-id' => 4180,
       'cat-name' => 'Uszkodzone',
    )),
    3 => 
    stdClass::__set_state(array(
       'cat-level' => 3,
       'cat-id' => 63107,
       'cat-name' => 'Toshiba',
    )),
  ),
  'item-img-list' => 
  array (
  ),
  'item-attrib-list' => 
  array (
  ),
  'item-postage-options' => 
  array (
  ),
  'item-payment-options' => 
  stdClass::__set_state(array(
     'pay-option-transfer' => 0,
     'pay-option-on-delivery' => 1,
     'pay-option-allegro-pay' => 1,
     'pay-option-see-desc' => 0,
     'pay-option-payu' => 0,
     'pay-option-escrow' => 0,
     'pay-option-qiwi' => 0,
  )),
  'item-company-info' => 
  stdClass::__set_state(array(
     'company-first-name' => '',
     'company-last-name' => '',
     'company-name' => '',
     'company-address' => '',
     'company-postcode' => '',
     'company-city' => '',
     'company-nip' => '',
  )),
  'item-product-info' => 
  stdClass::__set_state(array(
     'product-id' => 0,
     'product-name' => '',
     'product-description' => '',
     'product-images-list' => 
    array (
    ),
     'product-parameters-group-list' => 
    array (
    ),
  )),
  'item-variants' => 'Array',
  'item-after-sales-service-conditions' => 
  stdClass::__set_state(array(
     'implied-warranty' => '',
     'return-policy' => '',
     'warranty' => '',
  )),
  'item-additional-services-group' => 'Array',
)

**Comment by KoniecWebAPI-KoniecAllegro** [comment]
@fredzi - hej, nie sugeruj się tym co ci piszą spece z Amazollegro, oni sami nie wiedzą co się dzieje w ich systemie ;-) A sprawa o którą pytasz ciągnie się już ponad 5 lat, no i nikogo to nie obchodzi, że błędna "flaga zamknięcia" oferty może generować furę błędów. Przyjmij więc, że tak się dzieje cyklicznie, no i trzeba to sobie samemu "oprogramować", inaczej zwariujesz ;-)

**Comment by MaciejPotepa** [comment]
Okay, dziękuję za informacje. Jeżeli problem się powtórzy to daj znać.

**Comment by fredzi** [comment]
Znowu potwórzyło się kilka razy. Oto ostatnie zakończenie z 23 września o 11:02

array (
  'item-list-info-ext' => 
  stdClass::__set_state(array(
     'it-id' => 7509463624,
     'it-country' => 1,
     'it-name' => 'Laptop Lenovo IdeaPad 100-15IBD 15,6\'\' HD i3-5005U',
     'it-price' => 0,
     'it-bid-count' => 0,
     'it-ending-time' => 1537693163,
     'it-seller-id' => 43394085,
     'it-seller-login' => 'servecom_pl',
     'it-seller-rating' => 0,
     'it-starting-time' => 1534236255,
     'it-starting-price' => 0,
     'it-quantity' => 1,
     'it-foto-count' => 5,
     'it-reserve-price' => 0,
     'it-location' => 'Częstochowa',
     'it-buy-now-price' => 1699,
     'it-buy-now-active' => 1,
     'it-advertisement-price' => 0,
     'it-advertisement-active' => 0,
     'it-high-bidder' => 0,
     'it-high-bidder-login' => '',
     'it-description' => '',
     'it-standardized-description' => '',
     'it-options' => 16777508,
     'it-state' => 12,
     'it-wire-transfer' => 8.5999999999999996447286321199499070644378662109375,
     'it-post-delivery' => -1,
     'it-post-info' => '',
     'it-quantity-type' => 0,
     'it-is-eco' => 0,
     'it-hit-count' => 35,
     'it-postcode' => '',
     'it-vat-invoice' => 1,
     'it-vat-margin-invoice' => 0,
     'it-without-vat-invoice' => 0,
     'it-bank-account1' => '',
     'it-bank-account2' => '',
     'it-starting-quantity' => 1,
     'it-is-for-guests' => 0,
     'it-has-product' => 0,
     'it-order-fulfillment-time' => 48,
     'it-ending-info' => 2,
     'it-is-allegro-standard' => 0,
     'it-is-new-used' => 1,
     'it-is-brand-zone' => 0,
     'it-is-fulfillment-time-active' => 1,
     'it-ean' => '',
     'it-contact' => '',
  )),
  'item-cat-path' => 
  array (
    0 => 
    stdClass::__set_state(array(
       'cat-level' => 0,
       'cat-id' => 2,
       'cat-name' => 'Komputery',
    )),
    1 => 
    stdClass::__set_state(array(
       'cat-level' => 1,
       'cat-id' => 491,
       'cat-name' => 'Laptopy',
    )),
    2 => 
    stdClass::__set_state(array(
       'cat-level' => 2,
       'cat-id' => 77920,
       'cat-name' => 'IBM, Lenovo',
    )),
  ),
  'item-img-list' => 
  array (
  ),
  'item-attrib-list' => 
  array (
  ),
  'item-postage-options' => 
  array (
  ),
  'item-payment-options' => 
  stdClass::__set_state(array(
     'pay-option-transfer' => 0,
     'pay-option-on-delivery' => 1,
     'pay-option-allegro-pay' => 1,
     'pay-option-see-desc' => 0,
     'pay-option-payu' => 0,
     'pay-option-escrow' => 0,
     'pay-option-qiwi' => 0,
  )),
  'item-company-info' => 
  stdClass::__set_state(array(
     'company-first-name' => '',
     'company-last-name' => '',
     'company-name' => '',
     'company-address' => '',
     'company-postcode' => '',
     'company-city' => '',
     'company-nip' => '',
  )),
  'item-product-info' => 
  stdClass::__set_state(array(
     'product-id' => 0,
     'product-name' => '',
     'product-description' => '',
     'product-images-list' => 
    array (
    ),
     'product-parameters-group-list' => 
    array (
    ),
  )),
  'item-variants' => 'Array',
  'item-after-sales-service-conditions' => 
  stdClass::__set_state(array(
     'implied-warranty' => '',
     'return-policy' => '',
     'warranty' => '',
  )),
  'item-additional-services-group' => 'Array',
)

**Comment by MaciejPotepa** [comment]
Wybacz długi czas odpowiedzi. 
Czy masz możliwość podesłania treści requesta i response w XML?
