### ISSUE TITLE
Wszystkie Rozmiary w danej kategorii mogą zostać wybrane tylko dla jednej opcji Rodzaju

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6160]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Dzień dobry,
Nie jestem pewien, czy to bug w API czy ktoś przyszedł pijany do pracy? W kategorii 76024 każda wartość w parametrze Rozmiar jest wybieralna tylko, gdy Rodzaj zostanie ustawiony na wartość "komplet". Walidacja od wystawiania aukcji wyrzuca problem z tym, kiedy mam wybraną dowolną inną wartość w Rodzaj.
Trace id parametrów kategorii: dc3b88b87e9817e5
Trace id próby wystawienia (draftu) oferty: 6a055e5e8de467b7

**Comment by Lukasz-Zurek** [comment]
Jeśli przekazujesz parametr Rodzaj (215534): góra (215534_270222) to nie możesz przekazać parametru Rozmiar (128610), bo jest to parametr zależny i dostępny tylko w przypadku, gdy wybierzesz Rodzaj (215534): komplet (215534_270230).

Czyli dla pozostałych parametrów tj. Rodzaj (215534): góra (215534_270222) możesz przekazać opcjonalnie Rozmiar góry (249417), natomiast dla parametru Rodzaj (215534): góra (215534_270226) - Rozmiar majtek (249418).

**Comment by hahyes** [comment]
> Jeśli przekazujesz parametr Rodzaj (215534): góra (215534_270222) to nie możesz przekazać parametru Rozmiar (128610), bo jest to parametr zależny i dostępny tylko w przypadku, gdy wybierzesz Rodzaj (215534): komplet (215534_270230).
> 
> Czyli dla pozostałych parametrów tj. Rodzaj (215534): góra (215534_270222) możesz przekazać opcjonalnie Rozmiar góry (249417), natomiast dla parametru Rodzaj (215534): dół (215534_270226) - Rozmiar majtek (249418).

Pamiętam jak parę lat temu Allegro mówiło o potrzebie uporządkowania i ujednolicenia parametrów. I teraz wracamy z powrotem do dzielenia parametrów na drobne? Co za absurd.
@Lukasz-Zurek Mam w takim razie problem z produktami, które tworzyłem np. 7ee4c7c8-b8b7-4feb-b490-47878591e162
Czy mogę liczyć na to, że jakaś synchronizacja poprawi te rozmiary?

**Comment by Lukasz-Zurek** [comment]
@hahyes Temat przekazuję dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@hahyes Wracam do Ciebie z informacją, że pracujemy obecnie nad synchronizacją tych parametrów we wszystkich ofertach i produktach.
