### ISSUE TITLE
Metody płatności w punktach allegro

### ISSUE THREAD

**Issue by baambaam** [allegro/allegro-api#6161]
Mam pytanie do zasobu:
`https://api.allegro.pl/order/carriers/ALLEGRO/points`

pole `payments` zwraca listę elementów (CASH/CARD). W przypadku, gdy lista jest pusta to punkt nie obsługuje COD (płatność za pobraniem)? Na sandbox niektóre punkty zwracają coś w tym polu, natomiast obecnie na produkcji payments jest wszędzie puste

**Comment by MartaNowaczyk** [comment]
W punktach allegro na ten moment nie ma możliwości dostawy za pobraniem, stąd puste pole. Jeśli chodzi o sandbox i produkcję, to dane te mogą się nieznacznie różnić.
