### ISSUE TITLE
Błąd przy generowaniu etykiety Allegro One Box, zielony automat

### ISSUE THREAD

**Issue by pogotowiefiskalne** [allegro/allegro-api#6164]
Występuje problem: 
 - [X ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przy tworzeniu przesyłki /parcel-management/parcel-create-commands/ac4a6223-9d50-4897-a40a-ff45221a1555

Otrzymuję odpowiedź: "Wystąpił błąd komunikacji z API przewoźnik"

```
{
    "id": "ac4a6223-9d50-4897-a40a-ff45221a1555",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message":"Communication error with carrier\'s API occurred",
            "details": null,
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage":"Wyst\xc4\x85pi\xc5\x82 b\xc5\x82\xc4\x85d komunikacji z API przewo\xc5\xbanika"
        }
    ]
}
```

Proszę o pomoc w rozwiązaniu problemu.

**Comment by MartaNowaczyk** [comment]
Sprawdzamy opisaną sytuację. Dam znać, gdy uda nam się ustalić przyczynę.

**Comment by MartaNowaczyk** [comment]
Doprecyzuję tylko, że była to czasowa niedostępność z powodów technicznych, która mogła zakończyć się w ciągu tamtego dnia. Przepraszam, że tak długo czekałeś na odpowiedź, jednak dopiero teraz dostałam wyjaśnienie od firmy zewnętrznej.
