### ISSUE TITLE
Sandbox, sale/product-offers i błąd związany z obrazkiem

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6165]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [x] inny / other

Mam kłopot z wystawieniem oferty na sandboxie używając /sale/product-offers. Wykonuję kolejno:

POST https://api.allegro.pl.allegrosandbox.pl/sale/images
trace-id: 465365d494eff9ec
POST https://api.allegro.pl.allegrosandbox.pl/sale/product-offers
trace-id: 4ec93d4da0fe6651

Adres obrazka otrzymałem od sandboxowego allegro. 

A otrzymuję błąd:
{"errors":[{"code":"OfferImagesNotFoundException","message":"Provided image address is incorrect.","details":"OfferImagesNotFoundException","path":null,"userMessage":"Podany adres obrazka jest nieprawidłowy."}]}

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Problematyczne było jedno "puste" zdjęcie z produktu, które usunąłem, w związku z czym możesz ponownie spróbować wystawić ofertę.

**Comment by qusand** [comment]
**Komentarz post-mortem 2026-05-12** dla osób trafiających tu z wyszukiwarki:

Trafiliśmy na ten sam `OfferImagesNotFoundException` mimo że obrazki w `productSet[].product.images` i `payload.images` były świeżo zuploadowane na sandboxowy CDN (`a.allegroimg.allegrosandbox.pl/...`) i odpowiadały na HEAD 200 OK z poprawnym `Content-Length` i `etag`. Klasyczne hipotezy (propagation delay, format string vs object, cache staleness, scope tokena) wszystkie obalone.

**Faktyczny powód u nas:** w `description.sections[*].items` typu `IMAGE` były URL-e **produkcyjnego** CDN-u (`a.allegroimg.com/...`) — to obrazki z opisu oferty produkcyjnej kopiowanej do sandboxa. Allegro Sandbox waliduje **wszystkie** URL-e w payloadzie `POST /sale/product-offers`, nie tylko te w `productSet`/`offer.images`. Produkcyjny URL zwraca 422 z `OfferImagesNotFoundException` — komunikat jest dokładnie ten sam, co dla pustego/błędnego zdjęcia w productSet, więc bardzo łatwo szukać nie tam, gdzie trzeba.

**Co utrudnia diagnozę:** response 422 ma `path: null` i `metadata: {}`, więc nie widać która konkretnie URL-ka jest "invalid". Trzeba zdumpować cały payload tuż przed POST i zgrepować `a.allegroimg.com` (bez `sandbox`) w `description.sections`.

**Możliwe podejścia:** wystrippować inline `IMAGE` z `description.sections` (TEXT sekcje zostają), albo zrehostować każdy URL z description przez `POST /sale/images` tak samo jak galerię, albo — przy katalogowym `product.id` — w ogóle dropnąć `description` i pozwolić Allegro użyć opisu z katalogu serwerowo.

**Sugestia ulepszenia dla Allegro:** dodanie pola `path` w response z konkretną ścieżką do problematycznego URL-a (np. `"description.sections[3].items[0].url"`) skróciłoby diagnozę o godziny.

**Comment by Lukasz-Zurek** [comment]
@qusand Dziękuję za przesłaną sugestię optymalizacji.
