### ISSUE TITLE
Changing offer stock to zero quantity

### ISSUE THREAD

**Issue by furkanakharman** [allegro/allegro-api#6166]
Hello there,
I want to set my offers' quantity to zero. To do this I'm using /sale/offer-quantity-change-commands/ service.

However when I try to send the quantity as 0, it returns INCORRECT_QUANTITY_VALUE even though in the documentation it says it can be set >=0

If this is not possible which services can I use to pause and resume the offer?

Thanks in advance.

**Comment by Lukasz-Zurek** [comment]
You will not be able to use this resource to end the offers. This resource is intended only for the collective/bulk change of the quantity of items in the offers. However you are right - in the documentation it says it can be set >=0 which is incorrect and can be misleading. We will verify it and fix it in the future. Thank you!

But to end or resume the offer - you can use [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT) and provide in the **"publication.action"** field:

- END value to end/suspend selected offers ,
- ACTIVATE value to activate selected offers.

You can read more about it in [our guide](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#ending-offers).

**Comment by furkanakharman** [comment]
Thank you for the explanation.
