### ISSUE TITLE
Przyczyna zamknięcia ofert

### ISSUE THREAD

**Issue by tomylee0** [allegro/allegro-api#6167]
Chciałbym zapytać o przyczynę ustawienia endedBy = ADMIN dla ofert z tych trace-id (środowisko produkcyjne):

trace-id: 95408086f63b54b5
trace-id: 6f06913d977187a4

Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Oferty ze wskazanych trace-id zostały zakończone przez pracownika Allegro, stąd status endedBy = ADMIN.

**Comment by tomylee0** [comment]
Czy mogę uzyskać informację dlaczego pracownik Allegro zamknął te oferty?

**Comment by Lukasz-Zurek** [comment]
Taką informację możesz uzyskać kontaktując się z Serwisem za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380&subjectId=3c76fd6e-310d-449a-9ca7-08977f5d30c8).
