### ISSUE TITLE
Problem z propozycją produktu

### ISSUE THREAD

**Issue by sajkuu** [allegro/allegro-api#6168]
Mam problem z proponowaniem produktu:

REQUEST:
Array
(
    [name] => RENAULT ESPACE V CIĘGNO ZAMKA
    [category] => Array
        (
            [id] => 254599
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 129591
                    [name] => Typ samochodu
                    [valuesIds] => Array
                        (
                            [0] => 129591_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 
                        )

                )

            [1] => Array
                (
                    [id] => 127415
                    [name] => Producent części
                    [valuesIds] => Array
                        (
                            [0] => 127415_46
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 
                        )

                )

            [2] => Array
                (
                    [id] => 215858
                    [name] => Numer katalogowy części
                    [valuesIds] => Array
                        (
                        )

                    [values] => Array
                        (
                            [0] => 82506000654R
                        )

                    [unit] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 1
                        )

                )

        )

    [images] => Array
        (
            [url] => https://wyszukiwarka.autoczesci.market//photos/0099-1/28/53/213927-iidscn6549-jpg-800_nobackground.jpg
        )

)

RESPONSE:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ParameterException.InvalidParameterDtoException
                    [message] => An error has occurred
                    [details] => 
                    [path] => parameters
                    [userMessage] => Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 215858.
                )

        )

HTTP Code: 422
trace-id: ebe2b33acd40058a
date: Wed, 28 Sep 2022 10:43:37 GMT

Na czym polega to nieprawidłowe zdefiniowanie dla tego parametru?

**Comment by MartaNowaczyk** [comment]
Nie przekazuj w parametrach pustej tablicy w polu "valuesIds" `"valuesIds":[]`. Pomiń całkowicie to pole, lub przekaż null.
Jeszcze dostaniesz błąd ze zdjęciem, bo muszą być [przesłane przy pomocy Allegro REST API](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#zdjecia).

**Comment by sajkuu** [comment]
ok teraz mam
REQUEST:
Array
(
    [name] => RENAULT ESPACE V CIĘGNO ZAMKA
    [category] => Array
        (
            [id] => 254599
        )

    [parameters] => Array
        (
            [0] => Array
                (
                    [id] => 129591
                    [name] => Typ samochodu
                    [valuesIds] => Array
                        (
                            [0] => 129591_1
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 
                        )

                )

            [1] => Array
                (
                    [id] => 127415
                    [name] => Producent części
                    [valuesIds] => Array
                        (
                            [0] => 127415_46
                        )

                    [values] => Array
                        (
                        )

                    [rangeValue] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 
                        )

                )

            [2] => Array
                (
                    [id] => 215858
                    [name] => Numer katalogowy części
                    [values] => Array
                        (
                            [0] => 82506000654R
                        )

                    [unit] => 
                    [options] => Array
                        (
                            [identifiesProduct] => 1
                        )

                )

        )

    [images] => Array
        (
            [url] => https://wyszukiwarka.autoczesci.market//photos/0099-1/28/53/213927-iidscn6549-jpg-800_nobackground.jpg
        )

)

response

[errors] => Array
        (
            [0] => Array
                (
                    [code] => HttpMessageNotReadableException
                    [message] => An error has occurred
                    [details] => 
                    [path] => 
                    [userMessage] => Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.
                )

        )

trace-id: 15135b6da17f1858
date: Wed, 28 Sep 2022 12:26:29 GMT

[14:28, 28.09.2022] Marcin Stelmaszczyk: bez valuesID
[14:28, 28.09.2022] Marcin Stelmaszczyk: HTTP error code: 400

**Comment by MartaNowaczyk** [comment]
Nie poprawiłeś linku do obrazka. Poza tym brakuje tablicy dla zdjęć np.

```
"images": [                                               
    {
      "url": "https://a.allegroimg.com/original/03d68a/6092f8024506a01087c820e58f0c"
    }
  ]
```

**Comment by sajkuu** [comment]
Dzięki, działa, mam pytanie pomocnicze, czy jest jakaś metoda na info o tym, że operator allegro zatwierdził ten produkt i że można już coś pod nim wystawić?

**Comment by MartaNowaczyk** [comment]
Nie ma takiego zasobu. Gdy wyślesz request z propozycją produktu i dostaniesz informację zwrotną z danymi produktu (status HTTP 201 - Created), to możesz już z niego korzystać.
