### ISSUE TITLE
Błąd w module integracji Allegro

### ISSUE THREAD

**Issue by swiesiul** [allegro/allegro-api#6169]
Dzień dobry, mamy problem z wystawianiem aukcji przez sklep internetowy. Konto zostało skonfigurowane prawidłowo.
Natomiast nie możemy wystawić aukcji ponieważ otrzymujemy taki błąd : 
Wyjaśnienie przyczyny nie wykonania operacji przez API Allegro:
 Nie znaleziono ustawienia podatku VAT dla podanej stawki.

Proszę o pomoc, w którym miejscu i w jaki sposób mogę znaleźć powyższe ustawienia. 

W załaczniku screen z błędu. 
![IAI](https://user-images.githubusercontent.com/114586811/192780882-91abb305-abc1-48ad-ac9d-e37ffd5d4062.png)

**Comment by Lukasz-Zurek** [comment]
Skontaktuj się w tej sprawie bezpośrednio z supportem narzędzia, z którego korzystasz.

Dodam, że sam błąd oznacza zastosowanie błędnej wartości, która nie jest dostępna w podanej kategorii. Każda kategoria ma zbiór możliwych do wykorzystania ustawień VAT. Dostępne ustawienia i identyfikatory stawek VAT w danej kategorii aplikacja może sprawdzić za pomocą [GET /sale/tax-settings?category.id={categoryId}](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory). Więcej o tym piszemy w [naszym poradniku](https://developer.allegro.pl/sale/#ustawienia-vat).
