### ISSUE TITLE
problem z parametrami do kategorii id 76024

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#6170]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Wysyłamy taki payload**

`{
    "productSet":[
        {
            "product":{
                "name":"Du00d3u0141 OD BIKINI V7E XXC__M",
                "category":{
                    "id":"76024"
                },
                "parameters":[
                    {
                        "id":"451",
                        "valuesIds":[
                            "451_2"
                        ]
                    },
                    {
                        "id":"3766",
                        "valuesIds":[
                            "3766_1"
                        ]
                    },
                    {
                        "id":"201017",
                        "valuesIds":[
                            "201017_2373"
                        ]
                    },
                    {
                        "id":"204501",
                        "valuesIds":[
                            "204501_221229"
                        ]
                    },
                    {
                        "id":"215534",
                        "valuesIds":[
                            "215534_270226"
                        ]
                    },
                    {
                        "id":"249418",
                        "valuesIds":[
                            "249418_1217351"
                        ]
                    },
                    {
                        "id":"224017",
                        "values":[
                            "10057722"
                        ],
                        "rangeValue":null
                    },
                    {
                        "id":"3946",
                        "valuesIds":[
                            "3946_40"
                        ],
                        "values":[
                            "AS"
                        ],
                        "rangeValue":null
                    }
                ],
                "images":[
                    "https:\/\/a.allegroimg.com\/original\/110d57\/5519c43747b0b94cb56a108cf0a3"
                ]
            }
        }
    ],
    "name":"Du00d3u0141 OD BIKINI V7E XXC__M",
    "afterSalesServices":{
        "impliedWarranty":{
            "id":"6a7525c5-1e93-44a1-816b-fc406b7a9421"
        },
        "warranty":{
            "id":"d1effd69-ccc6-4154-b777-15681a2f22d0"
        },
        "returnPolicy":{
            "id":"dc8c74dc-2853-4f1c-8982-0e6603c36e21"
        }
    },
    "category":{
        "id":"76024"
    },
    "delivery":{
        "handlingTime":"PT24H",
        "shippingRates":{
            "id":"ea116684-f35f-4e50-8c6b-1e22f7bd6225"
        }
    },
    "description":{
        "sections":[
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/1192bd\/c90181c647cd87836415aeb00b82"
                    },
                    {
                        "type":"TEXT",
                        "content":"<p><b>OPIS PRODUKTU<\/b><\/p><p>_________________________________________<\/p><ul><li><p>Sku0142ad materiau0142u: <b> Gu0142u00f3wny: 78% Poliamid 22% Elastan. Wewnu0105trz: 100% Poliester<\/b><\/p><\/li><li><p>Kolor: <b> Czarny<\/b><\/p><\/li><li><p>Rozmiar: <b> M<\/b><\/p><\/li><li><p>Metka papierowa: <b> Produkt zgodny z naszu0105 ideologiu0105 less waste. Dbaju0105c o wytyczne marki produkt mou017ce nie posiadau0107 czu0119u015bci metek.<\/b><\/p><\/li><li><p>Cena katalogowa: <b> 39zu0142<\/b><\/p><\/li><li><p>Informacje dodatkowe: <b> Oferta dotyczy dou0142u od bikini. <\/b><\/p><\/li><\/ul>"
                    }
                ]
            },
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/116d9c\/44a7887540d395831b680070b82d"
                    },
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/11f5fe\/41bb03eb4aabb2c923e04e95de55"
                    }
                ]
            },
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/114e74\/31ef57914b27b0d81eff8a260199"
                    },
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/11c4b7\/1aabd6e345a4a1f6afae7f401549"
                    }
                ]
            }
        ]
    },
    "external":{
        "id":"easyitem_3447693"
    },
    "images":[
        "https:\/\/a.allegroimg.com\/original\/110d57\/5519c43747b0b94cb56a108cf0a3",
        "https:\/\/a.allegroimg.com\/original\/1192bd\/c90181c647cd87836415aeb00b82",
        "https:\/\/a.allegroimg.com\/original\/116d9c\/44a7887540d395831b680070b82d",
        "https:\/\/a.allegroimg.com\/original\/11f5fe\/41bb03eb4aabb2c923e04e95de55",
        "https:\/\/a.allegroimg.com\/original\/114e74\/31ef57914b27b0d81eff8a260199",
        "https:\/\/a.allegroimg.com\/original\/11c4b7\/1aabd6e345a4a1f6afae7f401549"
    ],
    "location":{
        "city":"MOTYCZ",
        "postCode":"21-030",
        "countryCode":"PL",
        "province":"LUBELSKIE"
    },
    "parameters":[
        {
            "id":"11323",
            "valuesIds":[
                "11323_1"
            ]
        }
    ],
    "payments":{
        "invoice":"VAT"
    },
    "publication":{
        "status":"INACTIVE"
    },
    "sellingMode":{
        "format":"BUY_NOW",
        "price":{
            "amount":19.95,
            "currency":"PLN"
        }
    },
    "sizeTable":{
        "id":"7ef2673e-4c3e-11ea-bbff-b8ca3a6f71e0"
    },
    "stock":{
        "available":1,
        "unit":"UNIT"
    },
    "tax":{
        "percentage":"23.00"
    },
    "language":"pl-PL"
}`

**taką odpowiedź otrzymujemy**

`"errors": [
            {
                "code": "ConstraintViolationException.DependencyValidator",
                "message": "Dependent parameter Rozmiar (128610) cannot take values [M] when parameter Rodzaj (215534) has values [dół]",
                "details": "ConstraintViolationException.DependencyValidator",
                "path": "parameters",
                "userMessage": "Parametr zależny Rozmiar (128610) nie może przyjąć wartości [M], gdy parametr Rodzaj (215534) ma wartości [dół]."
            }
        ],`

trace-id 260bfc708aa16cab

Problem
Od niedawna w kategoriach związanych z bikini pojawił się parametr rozdzaj :
gdzie wybieramy dół góra albo komplet, ten parametr jest w korelacji z rozmiarami które no ta bene uzupełniamy prawidłowo tak jak widać wyżej. Co my robimy źle?

**Comment by hahyes** [comment]
> Jeśli przekazujesz parametr Rodzaj (215534): góra (215534_270222) to nie możesz przekazać parametru Rozmiar (128610), bo jest to parametr zależny i dostępny tylko w przypadku, gdy wybierzesz Rodzaj (215534): komplet (215534_270230).

> Czyli dla pozostałych parametrów tj. Rodzaj (215534): góra (215534_270222) możesz przekazać opcjonalnie Rozmiar góry (249417), natomiast dla parametru Rodzaj (215534): dół (215534_270226) - Rozmiar majtek (249418).

Innymi słowy, dla kompletów masz Rozmiar. Dla góry masz Rozmiar góry. Dla dołu masz Rozmiar majtek. W zależności od Rodzaju jest wymagane wypełnienie innego parametru.

**Comment by MartaNowaczyk** [comment]
@mbcont wygląda na to, że problemem tutaj jest sam produkt, w którym jest nieprawidłowo dodany parametr Rozmiar. Zgłosiłam już ten problem. Pracujemy obecnie nad synchronizacją tych parametrów we wszystkich ofertach i produktach.

**Comment by mbcont** [comment]
@hahyes ja ro rozumiem i w payloadzie który wysyłam tak jest.

**Comment by MartaNowaczyk** [comment]
@mbcont Rodzaj zostaje. Tutaj chodzi o parametr Rozmiar, który powinien być w produkcie tylko jeśli dla parametru Rodzaj wybierzesz "komplet". Problem był u nas w Katalogu produktów - mieliśmy tam parametr Rozmiar, dla Rodzaju "góra". Usunęliśmy nieprawidłową wartość i teraz powinno być ok.

**Comment by mbcont** [comment]
witam, nadal to samo
trace-id: 33d338a3008137db
Parametr zależny Rozmiar góry (249417) nie może przyjąć wartości [52], gdy parametr Rodzaj (215534) ma wartości [komplet].
Parametr zależny Rozmiar majtek (249418) nie może przyjąć wartości [52], gdy parametr Rodzaj (215534) ma wartości [komplet].

**Comment by mbcont** [comment]
trace-id: c270a2371b9ee994
Parametr zależny Rozmiar (128610) nie może przyjąć wartości [38], gdy parametr Rodzaj (215534) ma wartości [góra].
Parametr zależny Rozmiar majtek (249418) nie może przyjąć wartości [35], gdy parametr Rodzaj (215534) ma wartości [góra].

**Comment by mbcont** [comment]
Parametr zależny Rozmiar (128610) nie może przyjąć wartości [38], gdy parametr Rodzaj (215534) ma wartości [góra].

128610 - komplet
249417 - góra
249418 - dół

Wartości parametrów w bazie
{"451": "451_524288", "3766": "3766_5", "3946": "3946_53", "8242": "", "11323": "11323_1", "15851": "15851_1", "17448": "", "128610": "", "201017": "201017_240338", "204501": "204501_221221", "215534": "215534_270222", "215922": "", "215926": "", "215930": "", "216925": "", "224017": "", "225693": "", "237206": "23800539", "249417": "249417_1216975", "249418": "", "3766_8": "", "3946_40": "River Island", "201017_257870": ""}
więc mamy dobrze
tak jak w tamtym przypadku
"128610": ""
Nasz parametr Rozmiar nie jest nawet wysyłany

**Comment by MartaNowaczyk** [comment]
@mbcont parametry zależne w tej kategorii zostały włączone stosunkowo niedawno, stąd problemy z pokryciem w produktach. Pracujemy nad wprowadzeniem odpowiednich wartości w parametrach Rozmiar góry i Rozmiar majtek w całej kategorii. Proszę o jeszcze trochę cierpliwości.

**Comment by glorifyingpeace** [comment]
Mamy ten sam problem co opisał @mbcont

**Comment by Lukasz-Zurek** [comment]
@glorifyingpeace Przepraszamy za te utrudnienia. Jeśli jesteś w stanie wskazać problematyczne produkty, podaj ich identyfikatory w tym wątku. Zgłosiłbym je do poprawki.

**Comment by mbcont** [comment]
@Lukasz-Zurek  dotyczy to wszysktich produktów które były tworzone do 1 miesiąca wstecz w kategori bikini, są ich setki

**Comment by Lukasz-Zurek** [comment]
@mbcont Mamy tego świadomość i mogę tylko zapewnić, że trwają prace nad tym, aby to globalnie zsynchronizować.

**Comment by glorifyingpeace** [comment]
Chciałbym podbić temat czy coś wiadomo w tym temacie.

**Comment by MartaNowaczyk** [comment]
Wyjaśniam to z zespołem odpowiedzialnym za tę funkcjonalność. Jeśli będę potrzebowała jakieś przykłady dam znać.

**Comment by mbcont** [comment]
witam, czy temat już został zakończony przez zespół dev'ów?

**Comment by Lukasz-Zurek** [comment]
@mbcont Temat konsultuję. Proszę o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@mbcont Temat ten został już zakończony. Przepraszamy za wcześniejsze utrudnienia.

**Comment by glorifyingpeace** [comment]
**Problem nadal występuje:** 

Payload który wysyłamy:
{
    "productSet":[
        {
            "product":{
                "name":"YE3056 SPORTOWE BIKINI__38",
                "category":{
                    "id":"76024"
                },
                "parameters":[
                    {
                        "id":"451",
                        "valuesIds":[
                            "451_1024"
                        ]
                    },
                    {
                        "id":"2969",
                        "valuesIds":[
                            "2969_512"
                        ]
                    },
                    {
                        "id":"3766",
                        "valuesIds":[
                            "3766_279833"
                        ]
                    },
                    {
                        "id":"3946",
                        "valuesIds":[
                            "3946_48"
                        ]
                    },
                    {
                        "id":"8242",
                        "valuesIds":[
                            "8242_1"
                        ]
                    },
                    {
                        "id":"15851",
                        "valuesIds":[
                            "15851_1"
                        ]
                    },
                    {
                        "id":"128610",
                        "valuesIds":[
                            "128610_137"
                        ]
                    },
                    {
                        "id":"201017",
                        "valuesIds":[
                            "201017_2373"
                        ]
                    },
                    {
                        "id":"204501",
                        "valuesIds":[
                            "204501_221229"
                        ]
                    },
                    {
                        "id":"205646",
                        "valuesIds":[
                            "205646_1024",
                            "205646_895955",
                            "205646_8192",
                            "205646_512"
                        ]
                    },
                    {
                        "id":"215534",
                        "valuesIds":[
                            "215534_270230"
                        ]
                    }
                ],
                "images":[
                    "https:\/\/a.allegroimg.com\/original\/11905c\/649602924f298ed53f68db170e24"
                ]
            }
        }
    ],
    "name":"YE3056 SPORTOWE BIKINI__38",
    "afterSalesServices":{
        "impliedWarranty":{
            "id":"03909aa2-85ed-4ee8-b7a4-9ce598cde38a"
        },
        "returnPolicy":{
            "id":"27e29665-07ba-47b5-9b4e-3d56879b126d"
        }
    },
    "category":{
        "id":"76024"
    },
    "delivery":{
        "handlingTime":"PT24H",
        "shippingRates":{
            "id":"0f6e6116-fcf1-46b1-8781-8e8d6c1e6e2e"
        }
    },
    "description":{
        "sections":[
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/11bcc1\/71bd2251460c961111f0e8faa172"
                    },
                    {
                        "type":"TEXT",
                        "content":"<p><b>OPIS PRODUKTU<\/b><\/p><p>_________________________________________<\/p><ul><li><p>Marka: <b>Bonprix<\/b><\/p><\/li><li><p>Sk\u0142ad materia\u0142u: <b> prawa strona: 80%polimaid, 20%elastan; podszewka: 100%poliester<\/b><\/p><\/li><li><p>Kolor: <b> WIELOKOLOROWY<\/b><\/p><\/li><li><p>Rozmiar: <b> 38<\/b><\/p><\/li><li><p>Metka papierowa: <b> Brak metki papierowej - Produkt posiada wszystkie metki wewn\u0119trzne.<\/b><\/p><\/li><li><p>Cena katalogowa: <b> 79z\u0142<\/b><\/p><\/li><\/ul>"
                    }
                ]
            },
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/110dcd\/d79c24e74dcd9760bf56129d8dbb"
                    },
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/118451\/abf7486448c79f42606fcaacfb13"
                    }
                ]
            },
            {
                "items":[
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/11e1c6\/7462e4544234bcb2bcc4550b00c7"
                    },
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/1113a0\/754e211b4c20b80cb5e9e4437d11"
                    }
                ]
            },
            {
                "items":[
                    {
                        "type":"TEXT",
                        "content":"<p>_________________________________________<\/p>"
                    },
                    {
                        "type":"IMAGE",
                        "url":"https:\/\/a.allegroimg.com\/original\/11b727\/bc52e3394daaab96c7b25f2a56ad"
                    }
                ]
            }
        ]
    },
    "external":{
        "id":"easyitem_1784551"
    },
    "images":[
        "https:\/\/a.allegroimg.com\/original\/11905c\/649602924f298ed53f68db170e24",
        "https:\/\/a.allegroimg.com\/original\/11bcc1\/71bd2251460c961111f0e8faa172",
        "https:\/\/a.allegroimg.com\/original\/110dcd\/d79c24e74dcd9760bf56129d8dbb",
        "https:\/\/a.allegroimg.com\/original\/118451\/abf7486448c79f42606fcaacfb13",
        "https:\/\/a.allegroimg.com\/original\/11e1c6\/7462e4544234bcb2bcc4550b00c7",
        "https:\/\/a.allegroimg.com\/original\/1113a0\/754e211b4c20b80cb5e9e4437d11",
        "https:\/\/a.allegroimg.com\/original\/11b727\/bc52e3394daaab96c7b25f2a56ad"
    ],
    "location":{
        "city":"TUROBIN",
        "postCode":"23-465",
        "countryCode":"PL",
        "province":"LUBELSKIE"
    },
    "parameters":[
        {
            "id":"11323",
            "valuesIds":[
                "11323_246510"
            ]
        }
    ],
    "payments":{
        "invoice":"VAT"
    },
    "publication":{
        "duration":"P3D",
        "status":"INACTIVE",
        "republish":true
    },
    "sellingMode":{
        "format":"AUCTION",
        "startingPrice":{
            "amount":46.99,
            "currency":"PLN"
        }
    },
    "stock":{
        "available":1,
        "unit":"UNIT"
    },
    "language":"pl-PL"
}


Dostajemy taki komunikat:
trace-id: fd7505a7fa104e0e

Parametr zależny Rozmiar góry (249417) nie może przyjąć wartości [38], gdy parametr Rodzaj (215534) ma wartości [komplet].
Parametr zależny Rozmiar majtek (249418) nie może przyjąć wartości [38], gdy parametr Rodzaj (215534) ma wartości [komplet].

**Comment by Lukasz-Zurek** [comment]
@glorifyingpeace Problem przekazałem dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@glorifyingpeace Poprawiliśmy ten konkretny produkt. Przepraszamy za te utrudnienia.

Dodam, że nadal mogą  pojawiać się jednostkowe przypadki, których nie udało się poprawić globalnie. Jeśli zatem posiadasz kolejne przykładowe trace-id dla innych problematycznych przypadków - podeślij je w tym wątku.

**Comment by mbcont** [comment]
witam, trace-id c7a9a6a1f7503dd

**Comment by mbcont** [comment]
problem jak widać nadal występuje

**Comment by Lukasz-Zurek** [comment]
@mbcont Zgłosiłem do poprawki. Jak tylko uzyskam informacje - wrócę do Ciebie w tym wątku.

**Comment by Lukasz-Zurek** [comment]
@mbcont Poprawiliśmy już produkt, który posiadał nadmiarowe parametry.
