### ISSUE TITLE
Błąd zakładania przesyłek przez Wysyłam z Allegro - produkcja

### ISSUE THREAD

**Issue by Wojtu204** [allegro/allegro-api#6171]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

W momencie wysyłki na środowisku produkcyjnym requesta o założenie przesyłki z DPD otrzymuję komunikat zwrtony:
{
	"errors": [
		{
			"code": "NotAcceptableException",
			"message": "Not acceptable representation requested. Please check 'Accept' request header",
			"details": null,
			"path": null,
			"userMessage": "The request contains incorrect data. Contact the author of the application."
		}
	]
}

W nagłówku requesta jest przesyłany parametr:
Content-Type: application/vnd.allegro.public.v1+json
zgodny z dokumentacją, co więcej na środowisku testowym bez problemu udawało się założyć paczkę dla analogicznego zapytania z tym parametrem.
Proszę o weryfikację i rozwiązanie błędu.
TraceId dla requesta: c84644bc727d9ba0

**Comment by hahyes** [comment]
> Please check 'Accept' request header

@Wojtu204 Sprawdź header "Accept" a nie Content-Type. :)
