### ISSUE TITLE
Klucz API

### ISSUE THREAD

**Issue by Zdrowieija** [allegro/allegro-api#6172]

**Comment by Zdrowieija** [comment]
Dzień Dobry

Zostałam przez allegro przekierowana tu, aby uzyskać pomoc w sprawie Klucza API.

Dzień Dobry Mamy problem z integracją naszego systemu z Państwa. W tej chwili wszystkie paczki, zamawiane przez klientów do paczkomatu nadajemy na swojej umowie, aby to zmienić potrzebujemy: klucza API oraz ewentualnie Tokena. Proszę o informację jak mogę je uzyskać i czy jest to możliwe bez uruchamiania dwuetapowego logowania. Na naszych kontach allegro pracuje wiele osób w różnych miejscach i nie mamy możliwości przekazywać sobie kodu z telefonu. Pozdrawiam Katarzyna

**Comment by MartaNowaczyk** [comment]
Witaj Katarzyna! Z Twojego opisu nie do końca wiem w jaki sposób integrujecie się z allegro, stąd nie mam pewności czy to właśnie tych danych od nas potrzebujesz. Jeśli przez API, to macie już wygenerowane dane lub umożliwiliście dostęp do swoich danych jakiejś aplikacji. Jeśli integracja następuje na jakiejś zewnętrznej stronie np. Inpostu - [Manager Paczkomatów InPost](https://manager.paczkomaty.pl/account/api), to inna sprawa. Tak czy inaczej dużo tutaj domysłów, a lepiej jak mi opiszesz jak i gdzie działacie. Daj też znać dokładnie o które metody dostawy chodzi, bo to robi różnicę. 
Do [rejestracji aplikacji ](https://apps.developer.allegro.pl/new) zgodnie z regulaminem, trzeba mieć włączone dwustopniowe logowanie.

**Comment by Zdrowieija** [comment]
Dziękuje za odpowiedź

 

Zamówienia obsługujemy z Baselinkera, a etykiety drukujemy z naszego WMS.

 

Tam mamy podobno integrację z API 

 

Otrzymujemy  od Państwa wiadomości z treścią poniżej i nie bardzo wiemy, co z tym zrobić;

 



 <https://t.allegro.pl/?utm_source=notification&utm_medium=Smart%20Alert%20Wrong%20Parcel%20Notification&utm_campaign=bf1ff161-9279-4084-943c-df572442f577&utm_content=logo&tr_n=Smart%20Alert%20Wrong%20Parcel%20Notification_generic&tr_id=dc9de271-fa64-408d-9dc1-5489447a1c1b&tr_d=allegro.pl&tr_c=logo&tr_s=EVH6l2C5> 


Dzień dobry zdrowieija, 


Zauważyliśmy, że niepoprawnie nadajesz przesyłki Allegro Paczkomaty InPost w ramach Smart!, przez co będziesz rozliczać się z InPost, a nie z nami. W ten sposób znacząco zwiększysz koszty wysyłki. 



Chcemy mieć pewność, że to Twoje świadome działanie, a nie wynik złych ustawień Twojej umowy w Wysyłam z Allegro lub nieprawidłowego serwisu, jaki przekazujesz do InPost kiedy nadajesz przez API.


Niepoprawnie nadane przesyłki


1. Nr zamówienia: 685cd021-3dc8-11ed-9dd9-690772a53f55 / Nr przesyłki: 616001037225671014546188

2. Nr zamówienia: 8cbc2d51-3d3f-11ed-972e-8ffa4f817422 / Nr przesyłki: 616001927260256019727688

3. Nr zamówienia: 6baa6889-3e4c-11ed-a319-5b20d9aa7a78 / Nr przesyłki: 616001927299320037012251

4. Nr zamówienia: c9da8d21-3ecb-11ed-83ec-fb499f0c6d16 / Nr przesyłki: 616001927205500013678668

5. Nr zamówienia: 9ff64d01-3e53-11ed-805a-11e6cab448f0 / Nr przesyłki: 616001927232733032842952

Liczba niepoprawnie nadanych przesyłek: 13


Co zrobić, aby płacić mniej


Gdy nadajesz przesyłki przez Wysyłam z Allegro


1.      Wejdź do Wysyłam z Allegro i otwórz zakładkę  <https://t.allegro.pl/konto/przewoznicy?utm_source=notification&utm_medium=Smart%20Alert%20Wrong%20Parcel%20Notification&utm_campaign=bf1ff161-9279-4084-943c-df572442f577&tr_n=smart-alert-credentials&tr_id=dc9de271-fa64-408d-9dc1-5489447a1c1b&tr_d=wysylam.allegro.pl&tr_s=WuxqLPnX> Umowy własne.

2.      Przejdź do edycji umowy z InPost.

3.      Pod danymi dostępowymi do API ShipX zaznacz opcję: Używaj oferty dla sprzedawców Allegro.

4.      Kliknij przycisk [zapisz]. Gotowe!


Gdy nadajesz przesyłki przez API


Użyj prawidłowego serwisu dla metody Allegro Paczkomaty InPost: inpost_locker_allegro. 


Jak to działa


Przesyłki, które nadajesz metodą Allegro Paczkomaty InPost w ramach Smart!, należy rozliczać bezpośrednio z nami. Tylko wtedy skorzystasz ze stawek oferowanych w ramach usługi Allegro Smart!. Więcej na ten temat przeczytasz  <https://t.allegro.pl/dla-sprzedajacych/allegro-paczkomaty-inpost-model-rozliczeniowy-dyBd14MXRFg?utm_source=notification&utm_medium=Smart%20Alert%20Wrong%20Parcel%20Notification&utm_campaign=bf1ff161-9279-4084-943c-df572442f577&tr_n=smart-alert-to-info&tr_id=dc9de271-fa64-408d-9dc1-5489447a1c1b&tr_d=allegro.pl&tr_s=b83yO%2BzR> tutaj. 

Jeśli potrzebujesz więcej informacji lub nie chcesz otrzymywać tych mejli,  <https://t.allegro.pl/pomoc/kontakt?utm_source=notification&utm_medium=Smart%20Alert%20Wrong%20Parcel%20Notification&utm_campaign=bf1ff161-9279-4084-943c-df572442f577&kategoria=44362df6-b15a-4eac-a24c-c534495b1bda&tr_n=smart-alert-contact&tr_id=dc9de271-fa64-408d-9dc1-5489447a1c1b&tr_d=allegro.pl&tr_s=0E5bwIo5> skontaktuj się z nami. 

Pozdrawiamy 
Zespół Allegro

 


Katarzyna Grochowska
Specjalista ds. ecommerce

Dział Ecommerce

				

 

mob.: +48 503901554
email:  ***@***.***> ***@***.***




EURUS Sp z o.o.
NIP: 5423094347 KRS: 0000314581
Ignatki 40/1,16-001 Kleosin
tel. biuro: +48 661 678 777
 <https://www.eurus.com.pl/> www.eurus.com.pl

**Comment by MartaNowaczyk** [comment]
Z tego co widzę chodzi Ci pewnie o dane API ShipX Inpostu - "Dane dostępowe do API ShipX" czyli klucz autoryzacyjny. Takie dane powinnaś otrzymać od firmy Inpost. Pamiętaj, żeby zaznaczyć "Używaj oferty dla sprzedawców Allegro".

**Comment by Zdrowieija** [comment]
Witam

 

Bardzo dziękuje za pomoc przy integracji inpostu – działa.

 

W ten sam sposób chcemy podpiąć inne formy wysyłki:

 


Allegro One Box

	

Allegro One Punkt

	

 

 

W jaki sposób otrzymać od nich API ShipX - "Dane dostępowe do API ShipX" czyli klucz autoryzacyjny.  One Box rozumiem, że obsługuje UPS a One Punkt?


Katarzyna Grochowska
Specjalista ds. ecommerce

Dział Ecommerce

				

 

mob.: +48 503901554
email:  ***@***.***> ***@***.***




EURUS Sp z o.o.
NIP: 5423094347 KRS: 0000314581
Ignatki 40/1,16-001 Kleosin
tel. biuro: +48 661 678 777
 <https://www.eurus.com.pl/> www.eurus.com.pl

**Comment by MartaNowaczyk** [comment]
Witam, z tego co widzę pytanie nie dotyczy API, ale obie metody powinien obsługiwać UPS. Nie potrzeba tutaj klucza autoryzacyjnego jak w przypadku InPostu. Metody te można rozliczać sposobem "[Allegro Standard](https://allegro.pl/dla-sprzedajacych/jak-rozliczac-koszty-dostaw-na-allegro-m0jYAdk54Sr#metody-rozliczane-sposobem-allegro-standard)". Więcej szczegółów dotyczących rozliczeń możesz uzyskać przez [formularz kontaktowy](https://allegro.pl/pomoc/kontakt?kategoria=713f3db7-e741-4fba-9404-09ee86a58e6c&subjectId=d5222a2f-4de5-45ae-903d-65aa05d86d79).
