### ISSUE TITLE
Podany identyfikator wartości słownikowej

### ISSUE THREAD

**Issue by sergeidebug** [allegro/allegro-api#6175]
mam następujący błąd:
422
`{'errors': [{'code': 'InvalidDictionaryParameter', 'message': 'Unprocessable Entity', 'details': None, 'path': 'productSet[0].product.parameters', 'userMessage': 'Podany identyfikator wartości słownikowej `248811_950468` w parametrze o identyfikatorze`248811` wskazuje na inną wartość niż przekazana w polu `values`.'}]}`

oto co wysyłam:

`{'productSet': [{'product': {'category': {'id': '110911'}, 'parameters': [{'id': '224017', 'valuesIds': [], 'values': ['s00022'], 'rangeValue': None}, {'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None}, {'id': '215178', 'valuesIds': [], 'values': ['100'], 'rangeValue': None}, {'id': '16300', 'valuesIds': ['16300_1'], 'values': [], 'rangeValue': None}, {'id': '24148', 'valuesIds': ['24148_2'], 'values': [], 'rangeValue': None}, {'id': '216161', 'valuesIds': ['216161_273449'], 'values': [], 'rangeValue': None}, {'id': '247829', 'valuesIds': ['247829_815392'], 'values': [], 'rangeValue': None}, {'id': '130192', 'valuesIds': ['130192_256'], 'values': [], 'rangeValue': None}, {'id': '245545', 'valuesIds': [], 'values': ['30'], 'rangeValue': None}, {'id': '245549', 'valuesIds': [], 'values': ['45'], 'rangeValue': None}, {'id': '207442', 'valuesIds': ['207442_232110'], 'values': [], 'rangeValue': None}], 'images': ['https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059', 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'], 'name': 'Obrazy Gwiaździsta noc art s00022 45x30'}, 'quantity': {'value': 1}}], 'delivery': {'handlingTime': 'PT24H', 'shippingRates': {'id': '83242861-d15c-4293-9478-a5962ae604ae'}}, 'location': {'countryCode': 'PL', 'province': 'LUBELSKIE', 'city': 'Zamość', 'postCode': '22-400'}, 'afterSalesServices': {'warranty': {'id': 'c13ceb5d-2200-466b-91d1-93775534c9ce'}, 'returnPolicy': {'id': '4cba35a0-8f34-451d-8309-57a89682f3a2'}, 'impliedWarranty': {'id': '0ccab1a4-2596-4714-a960-b92f20517066'}}, 'payments': {'invoice': 'VAT'}, 'images': ['https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059', 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Obrazy są sprzedawane bez ramek. Obrazy są gotowe do powieszenia</b></p>\n<p>Nie ulega wątpliwości, że Polacy coraz chętniej wybierają obrazy na płótnie do swoich mieszkań. Urządzając wnętrza w nowoczesnym stylu, tj. loftowy, industrialny czy też minimalistyczny, warto wziąć pod uwagę obrazy drukowane na płótnie. Tego typu rozwiązania przydają się szczególnie wtedy, kiedy w domu królują szarości, biele i brązy. Nie od dziś bowiem wiadomo, że we wnętrzach, które mają na ścianie obrazy drukowane na płótnie bardzo dobrze się wypoczywa, łatwiej w nich zebrać myśli czy po prostu się zrelaksować.</p>\n<p>W dzisiejszych czasach kiedy jedynym ograniczeniem w projektowaniu przestrzeni mieszkalnej jest wyobraźnia, warto postawić na kreatywność i stworzyć wyjątkowy dom, w którym na ścianie znajdą się niewiarygodne obrazy nadające pomieszczeniu charakteru i ciekawego akcentu.</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059'}]}]}, 'stock': {'available': '999', 'unit': 'UNIT'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': '13.5', 'currency': 'PLN'}, 'minimalPrice': None, 'startingPrice': None}}`

wcześniej dodałem fototapety i wszystko było w porządku, ale teraz dodaję zdjęcia.
Przeczytałem dokumentację i wziąłem pod uwagę parametry zdjęć, ale nie rozumiem co jest nie tak, dlaczego ten błąd występuje?
proszę o pomoc

**Comment by MartaNowaczyk** [comment]
Nie powinieneś w tym przypadku korzystać z wartości niejednoznacznej. Dla parametru "Marka"mamy wartość słownikową "Uwalls":
```
                {
                    "id": "248811_1667748",
                    "value": "Uwalls",
                    "dependsOnValueIds": []
                },
```

**Comment by sergeidebug** [comment]
tak, rozumiem.
Wcześniej "Uwalls" nie była wartośćą słownikową.
okazuje się, że to dobra wiadomość dla naszej marki :)

**Comment by sergeidebug** [comment]
spełniliśmy kilka warunków, aby dostać się na listę marek na Allegro?

**Comment by sergeidebug** [comment]
Witam!
Nadal nie działa
[{'errors': [{'code': 'ParameterIdNotFoundException', 'message': 'Unprocessable Entity', 'details': None, 'path': 'productSet[0].product.parameters', 'userMessage': 'Nie znaleziono parametru o id `215178` w podanej kategorii `110911`.'}]}]

testowalem tak:
{
                    "id": "248811",
                    "value": "Uwalls",
                    "dependsOnValueIds": []
                }

tak:

{
                    "id": "248811_950468",
                    "value": "Uwalls",
                    "dependsOnValueIds": []
                }

Cóż, kiedyś było tak:
[{'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None}](url)
i to też nie działa:
[{'id': '248811', 'valuesIds': ['248811_950468'], 'values': 'Uwalls', 'rangeValue': None}](url)

jak dodać tę opcję?

**Comment by sergeidebug** [comment]
wykorzystałem
https://api.{environment}/sale/categories/{categoryId}/product-parameters
Nie widzę naszej marki w słowniku marki...
czyli muszę wyświetlać naszą markę ze specjalnym identyfikatorem
248811_950468

ale proszę powiedz mi, dlaczego moja oryginalna wersja nie działa

**Comment by sergeidebug** [comment]
Jeśli to wpiszę, to błąd jest:
`[{'id': '248811', 'valuesIds': ['248811_950468'], 'values': 'Uwalls', 'rangeValue': None}](https://github.com/allegro/allegro-api/issues/url)`
422
`{'errors': [{'code': 'JsonMappingException', 'message': 'Message is not readable.', 'details': None, 'path': 'productSet[0].product.parameters[1].values', 'userMessage': 'Żądanie zawiera błędne dane. Skontaktuj się z autorem aplikacji.'}]}`

**Comment by sergeidebug** [comment]
do tego kodu
```
{
                    "id": "248811",
                    "value": "Uwalls",
                    "dependsOnValueIds": []
                }
```

teraz mam ten błąd
422
{'errors': [{'code': 'ProductValidationException', 'message': 'An error has occurred', 'details': None, 'path': 'productSet[0].product', 'userMessage': 'Niepoprawnie zdefininiowano values, valueIds lub rangeValue dla parametru 248811.'}]}

czyli to, co mi oferujesz, w ogóle mi nie odpowiada

**Comment by MartaNowaczyk** [comment]
Nie podałam Ci gotowego kodu, tylko wartość jaką zwraca [GET /sale/categories/{categoryId}parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) dl kategorii 110911. Nie wiem jak potem konwertujesz sobie te dane, ale na pewno nie może być "None" tylko "null", masz tam parametry, których nie ma w tej kategorii i jeszcze rzuciło mi się w oczy brak nawiasów klamrowych przy zdjęciach. Zerknij sobie tutaj do [poradnika](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA). 
Przy kolejnych problemach podsyłaj proszę trace-id takiego wywołania, będzie prościej weryfikować.

Kwestia dodawania marek do allegro to już nie w moim zasięgu, ale możliwe, że ktoś zgłosił prośbę o dodanie i ją dodaliśmy.

**Comment by sergeidebug** [comment]
![image](https://user-images.githubusercontent.com/95347292/193579964-03cbcaaa-ea87-4813-b710-8a5754439501.png)
https://developer.allegro.pl/documentation#operation/createProductOffers
Od trzech miesięcy wysyłam go dokładnie tak i wszystko było w porządku, chociaż wysłałem go do innej kategorii

**Comment by sergeidebug** [comment]
![image](https://user-images.githubusercontent.com/95347292/193580518-da59efc6-4538-4f5a-8ae9-81c77093a99c.png)
nie ma nawiasów klamrowych

**Comment by sergeidebug** [comment]
Owszem, moge ustalic "null" zamiast "None" ale jak skoro to działało wcześniej, nie ma pewności, że to jest problem

**Comment by sergeidebug** [comment]
nie rozumiem co do questii konwertacji.
to jest dane przed post request
oto co wysyłam:

{'productSet': [{'product': {'category': {'id': '110911'}, 'parameters': [{'id': '224017', 'valuesIds': [], 'values': ['s00022'], 'rangeValue': None}, {'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None}, {'id': '215178', 'valuesIds': [], 'values': ['100'], 'rangeValue': None}, {'id': '16300', 'valuesIds': ['16300_1'], 'values': [], 'rangeValue': None}, {'id': '24148', 'valuesIds': ['24148_2'], 'values': [], 'rangeValue': None}, {'id': '216161', 'valuesIds': ['216161_273449'], 'values': [], 'rangeValue': None}, {'id': '247829', 'valuesIds': ['247829_815392'], 'values': [], 'rangeValue': None}, {'id': '130192', 'valuesIds': ['130192_256'], 'values': [], 'rangeValue': None}, {'id': '245545', 'valuesIds': [], 'values': ['30'], 'rangeValue': None}, {'id': '245549', 'valuesIds': [], 'values': ['45'], 'rangeValue': None}, {'id': '207442', 'valuesIds': ['207442_232110'], 'values': [], 'rangeValue': None}], 'images': ['https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059', 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'], 'name': 'Obrazy Gwiaździsta noc art s00022 45x30'}, 'quantity': {'value': 1}}], 'delivery': {'handlingTime': 'PT24H', 'shippingRates': {'id': '83242861-d15c-4293-9478-a5962ae604ae'}}, 'location': {'countryCode': 'PL', 'province': 'LUBELSKIE', 'city': 'Zamość', 'postCode': '22-400'}, 'afterSalesServices': {'warranty': {'id': 'c13ceb5d-2200-466b-91d1-93775534c9ce'}, 'returnPolicy': {'id': '4cba35a0-8f34-451d-8309-57a89682f3a2'}, 'impliedWarranty': {'id': '0ccab1a4-2596-4714-a960-b92f20517066'}}, 'payments': {'invoice': 'VAT'}, 'images': ['https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059', 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Obrazy są sprzedawane bez ramek. Obrazy są gotowe do powieszenia</b></p>\n<p>Nie ulega wątpliwości, że Polacy coraz chętniej wybierają obrazy na płótnie do swoich mieszkań. Urządzając wnętrza w nowoczesnym stylu, tj. loftowy, industrialny czy też minimalistyczny, warto wziąć pod uwagę obrazy drukowane na płótnie. Tego typu rozwiązania przydają się szczególnie wtedy, kiedy w domu królują szarości, biele i brązy. Nie od dziś bowiem wiadomo, że we wnętrzach, które mają na ścianie obrazy drukowane na płótnie bardzo dobrze się wypoczywa, łatwiej w nich zebrać myśli czy po prostu się zrelaksować.</p>\n<p>W dzisiejszych czasach kiedy jedynym ograniczeniem w projektowaniu przestrzeni mieszkalnej jest wyobraźnia, warto postawić na kreatywność i stworzyć wyjątkowy dom, w którym na ścianie znajdą się niewiarygodne obrazy nadające pomieszczeniu charakteru i ciekawego akcentu.</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/114123/865dec1f4858a1568fc405742c2c'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/112e59/2f779e964eb79c6866bdf8729059'}]}]}, 'stock': {'available': '999', 'unit': 'UNIT'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': '13.5', 'currency': 'PLN'}, 'minimalPrice': None, 'startingPrice': None}}

Sprawdziłem kody parametrów i wszystko wydaje się być w kategorii 110911
224017 - Kod producenta
248811 - Marka
215178 - Cena (to z innej kategorii, juz nie wysylam)
16300 - Sposób wykonania
24148 - Materiał wykonania
216161 - Tematyka
247829 - Cechy dodatkowe
130192 - Gama kolorystyczna (to z innej kategorii, juz nie wysylam)
245545 - Wysokość produktu
245549 - Szerokość produktu
207442 - Format

**Comment by sergeidebug** [comment]
ponownie
`'trace-id': 'a2f77bd7abec79ca'`

`{'productSet': [{'product': {'category': {'id': '110911'}, 'parameters': [{'id': '224017', 'valuesIds': [], 'values': ['s00022'], 'rangeValue': None}, {'id': '248811', 'valuesIds': ['248811_950468'], 'values': ['Uwalls'], 'rangeValue': None}, {'id': '16300', 'valuesIds': ['16300_1'], 'values': [], 'rangeValue': None}, {'id': '24148', 'valuesIds': ['24148_2'], 'values': [], 'rangeValue': None}, {'id': '216161', 'valuesIds': ['216161_273449'], 'values': [], 'rangeValue': None}, {'id': '247829', 'valuesIds': ['247829_815392'], 'values': [], 'rangeValue': None}, {'id': '245545', 'valuesIds': [], 'values': ['30'], 'rangeValue': None}, {'id': '245549', 'valuesIds': [], 'values': ['45'], 'rangeValue': None}, {'id': '207442', 'valuesIds': ['207442_232110'], 'values': [], 'rangeValue': None}], 'images': ['https://a.allegroimg.com/original/116460/db376d6444f2bd6adf947dd5c837', 'https://a.allegroimg.com/original/11e7f3/41ff175d46e6b4b3eb900be1c159'], 'name': 'Obrazy Gwiaździsta noc art s00022 45x30'}, 'quantity': {'value': 1}}], 'delivery': {'handlingTime': 'PT24H', 'shippingRates': {'id': '83242861-d15c-4293-9478-a5962ae604ae'}}, 'location': {'countryCode': 'PL', 'province': 'LUBELSKIE', 'city': 'Zamość', 'postCode': '22-400'}, 'afterSalesServices': {'warranty': {'id': 'c13ceb5d-2200-466b-91d1-93775534c9ce'}, 'returnPolicy': {'id': '4cba35a0-8f34-451d-8309-57a89682f3a2'}, 'impliedWarranty': {'id': '0ccab1a4-2596-4714-a960-b92f20517066'}}, 'payments': {'invoice': 'VAT'}, 'images': ['https://a.allegroimg.com/original/116460/db376d6444f2bd6adf947dd5c837', 'https://a.allegroimg.com/original/11e7f3/41ff175d46e6b4b3eb900be1c159'], 'description': {'sections': [{'items': [{'type': 'TEXT', 'content': '<p><b>Obrazy są sprzedawane bez ramek. Obrazy są gotowe do powieszenia</b></p>\n<p>Nie ulega wątpliwości, że Polacy coraz chętniej wybierają obrazy na płótnie do swoich mieszkań. Urządzając wnętrza w nowoczesnym stylu, tj. loftowy, industrialny czy też minimalistyczny, warto wziąć pod uwagę obrazy drukowane na płótnie. Tego typu rozwiązania przydają się szczególnie wtedy, kiedy w domu królują szarości, biele i brązy. Nie od dziś bowiem wiadomo, że we wnętrzach, które mają na ścianie obrazy drukowane na płótnie bardzo dobrze się wypoczywa, łatwiej w nich zebrać myśli czy po prostu się zrelaksować.</p>\n<p>W dzisiejszych czasach kiedy jedynym ograniczeniem w projektowaniu przestrzeni mieszkalnej jest wyobraźnia, warto postawić na kreatywność i stworzyć wyjątkowy dom, w którym na ścianie znajdą się niewiarygodne obrazy nadające pomieszczeniu charakteru i ciekawego akcentu.</p>'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/11e7f3/41ff175d46e6b4b3eb900be1c159'}]}, {'items': [{'type': 'IMAGE', 'url': 'https://a.allegroimg.com/original/116460/db376d6444f2bd6adf947dd5c837'}]}]}, 'stock': {'available': '999', 'unit': 'UNIT'}, 'sellingMode': {'format': 'BUY_NOW', 'price': {'amount': '13.9', 'currency': 'PLN'}, 'minimalPrice': None, 'startingPrice': None}}`

422
`{'errors': [{'code': 'InvalidDictionaryParameter', 'message': 'Unprocessable Entity', 'details': None, 'path': 'productSet[0].product.parameters', 'userMessage': 'Podany identyfikator wartości słownikowej `248811_950468` w parametrze o identyfikatorze`248811` wskazuje na inną wartość niż przekazana w polu `values`.'}]}`

**Comment by sergeidebug** [comment]
ah okay, let me explain that thing with None and null:
Python null is called None. None is a special object that represents the absence of a value. A function that does not return a value automatically returns None.

generalnie nie ma problemu

**Comment by sergeidebug** [comment]
prosze Pani,
tak ma byc dla kat. kategorii 110911, to dziala
```
Marka = {
                'id': '248811',
                'valuesIds': [],
                'values': ['Uwalls'],
                'rangeValue': None
            }
```
![image](https://user-images.githubusercontent.com/95347292/193603640-fd5b1d99-6882-4761-b382-5d0ce356cad5.png)
niestety jest tu blad w documentacji

**Comment by MartaNowaczyk** [comment]
Jeśli dla wartości niejednoznacznej wybierzesz "Uwalls" czyli markę, która jest dostępna na liście, to wtedy dostaniesz błąd. Możesz tam wpisać tylko taką, której nie ma na liście. Z tego co widzę dla trace-id: a2f77bd7abec79ca, cały czas próbujesz dodać markę "Uwalls" dla wartości niejednoznacznej, a mamy taką markę dodaną.

Jeśli chodzi o ostatni zrzut, to nie widzę tu błędu. W tej kategorii jest możliwość dodania wartości niejednoznacznej ("ambiguousValueId": "248811_950468") dla parametru "Marka", ale dodasz tylko taką wartość, której nie ma na liście.

Jest kilka sposobów [przekazywania wartości parametrów](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe).

**Comment by sergeidebug** [comment]
Pani nie rozumie, Marki nie ma na liście, nie dostalem takiej Marki w dict (Państwo mają dict z markami, wyglana jakos tak)
![image](https://user-images.githubusercontent.com/95347292/194003633-3d14a988-f26f-402b-9e41-e16d38675617.png)


 z [GET /sale/categories/{categoryId}parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) dla kategorii 110911.
Musze podac jako wartośc niejednoznaczna.
to nie dziala 
{
                    "id": "248811",
                    "value": "Uwalls",
                    "dependsOnValueIds": []
                }

zatem to dziala
Marka = {
                'id': '248811',
                'valuesIds': [],
                'values': ['Uwalls'],
                'rangeValue': None
            }

wczszniej do valuesIds pisalem 248811_950468 bo tak jest napisane w dokumentacji . I to wypracowane dobrze dla kategorii 68631. 

Państwo mają niespójność w dokumentacji.

Miałem nadzieję, że z tym wszystkim dostanę pomoc, żeby to rozgryźć, żebym nie tracił czasu na testy, ale sam musiałem to rozgryźć.

Istnieje teoretyczna szansa, że ​​marka dla każdego parametru jest inna i że istnieje marka Uwalls dla kategorii 110911, ale dla
68631 nie ma. Moim zdaniem to dziwne, jeśli tak jest

**Comment by MartaNowaczyk** [comment]
Parametry nie są stałe i trzeba mieć na uwadze, że mogą się zmienić. Jeśli wcześniej nie było marki "Uwalls" i działało Tobie przekazanie wartości niejednoznacznej, to nie znaczy, że marka "Uwalls" nigdy się tam nie pojawi. Powinieneś to monitorować po swojej stronie, a nie opierać się na wcześniejszym rozwiązaniu, które działało, bo może przestać działać. W tym wypadku widocznie to się zmieniło i marka "Uwalls" jest już w słowniku dla kategorii 110911 i 68631. 

> {
> "id": "248811",
> "value": "Uwalls",
> "dependsOnValueIds": []
> }

tu nie ma co działać, to po prostu trochę zmieniony (zmieniłeś tam "id", bo było "248811_1667748") wycinek danych zwracanych przez zasób GET /sale/categories/{categoryId}parameters, które podałam Tobie byś zobaczył, że taka marka jest w słowniku.

> 
> 'id': '248811',
> 'valuesIds': [],
> 'values': ['Uwalls'],
> 'rangeValue': None

to nie jest przypisanie do wartości niejednoznacznej, a wybranie wartości z listy, dlatego działa. Możesz przekazywać id lub wartość.

Poza tym dla ogólnego zarysu o parametrach w różnych kategoriach:
To, że w jednej kategorii są jakieś parametry, nie znaczy, że w innej będą. W każdej z kategorii, parametr może posiadać odrębną listę słownikową.
Parametry o tych samych nazwach mogą mieć różne identyfikatory. Parametry o tych samych identyfikatorach mogą mieć różne ograniczenia i opcje w zależności od kategorii. Na bieżąco trzeba pobierać listę parametrów dla danej kategorii.

**Comment by sergeidebug** [comment]
to wszystko jest jasne, juz nie pierwszy miesiac z tym pracuję.
Nie wiem co Pani chce mi udowodnić, wszystko już opisałem i sam znalazłem rozwiązanie. Dalsza dyskusja nie jest konieczna.
