### ISSUE TITLE
Liczba wyświetleń aukcji - API

### ISSUE THREAD

**Issue by lukaszolewniczak23** [allegro/allegro-api#6177]
Zabrali Państwo wiele podstawowych wskaźników w nowej wersji API. Przykład to liczba wyświetleń aukcji (przynajmniej z ostatnich 30 dni), której nie można nigdzie znaleźć w nowym API, a jest to tak podstawowy wskaźnik dla biznesów, że ciężko zrozumieć taki stan rzeczy. Co teraz mamy robić? Wchodzić codziennie w panel w godzinach późnych wieczornych i ręcznie spisywać dane o odwiedzinach za ostatnie 30 dni? Na scrapping i używanie botów Państwo nie zezwalają, a nie udostępniają w API tak podstawowej informacji. Proszę o pomoc w rozwiązaniu tego problemu.

**Comment by Lukasz-Zurek** [comment]
Liczbę wyświetleń ofert znajdziesz w polu **"stats.visitsCount"**, gdy skorzystasz z [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET). Oczywiście są to dane z ostatnich 30 dni.
