### ISSUE TITLE
Błąd: "Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii"

### ISSUE THREAD

**Issue by diamedica-pl** [allegro/allegro-api#6178]
Dzień dobry, Nie mogę wystawić oferty przez API z platformy IdoSell. Mam komunikat: "null: Nie możesz wystawić oferty bez powiązanego produktu w tej kategorii. Wybierz z katalogu lub utwórz nowy produkt i połącz go ze swoją ofertą.". Próbowałem też przypisać produkt do produktyzacji i nie działa, być może z uwagi na GTIN wśród znalezionych na Allegro produktów, które mają nieprawidłowy GTIN. Jesteśmy importerem i dystrybutorem firmy MDF w Polsce i na pewno mamy właściwy GTIN, tj. 6940211618370 dla modelu MDF747-BO.
Proszę o wyjaśnienie. Nasze konto: diamedica.
Pozdrawiam

**Comment by Lukasz-Zurek** [comment]
Z naszych logów wynika, że komunikat błędu pojawia się podczas korzystania z [POST /sale/offers](https://developer.allegro.pl/documentation#operation/createOfferUsingPOST) - podczas próby wystawiania oferty nie podajesz identyfikatora produktu, co w tym przypadku jest niezbędne.

Nie mając jednak wiedzy na temat działania danej aplikacji - najlepiej będzie jak skontaktujesz się bezpośrednio z supportem IdoSell.
