### ISSUE TITLE
Czyszczenie bazy

### ISSUE THREAD

**Issue by PatrykCholewa** [allegro/allegro-api#618]
Dzień dobry, 

Na moim koncie na Allegro Sandbox (test1253@wp.pl) zniknęły dane z zakładki Sprzedane, a próba wyciągnięcia ich przez api też zakończyła się klęską. Zastanawiam się, czy to jakieś tymczasowe czyszczenie bazy w ramach tylko wersji testowej, czy też spodziewać się takich sytuacji w produkcyjnej też. Dodatkowo,  nie wiem, czy mogę w przyszłości na metodzie doGetMySoldItems, jako związanej z usuwaną zakładką?

**Comment by ircykk** [comment]
Sandbox jest czyszczony co jakiś czas ze wszystkich danych.

**Comment by MaciejPotepa** [comment]
Dzień dobry

To co napisał @ircykk nie jest już zgodne z prawdą, od dłuższego czasu nie czyścimy Sandboxa, zmieniliśmy architekturę środowiska żeby właśnie tego uniknąć i poprawić ogólną stabilność.

@PatrykCholewa Co masz na myśli, że operacja zakończyła się klęską? Potrzebna jest treść requestu i respone żeby przeanalizować problem. 

Upewnij się proszę, że sprawdzałeś właściwe konto na Sandboxie. 

Takich sytuacji nie ma w serwisie produkcyjnym. 

> Dodatkowo, nie wiem, czy mogę w przyszłości na metodzie doGetMySoldItems, jako związanej z usuwaną zakładką?

Odrobinę niejasne zdanie, co możesz w przyszłości na metodzie doGetMySoldItems? :)

**Comment by PatrykCholewa** [comment]
Przepraszam że tak późno odpisuję, ale przestałem śledzić ten wątek otrzymawszy poprzednią odpowiedź.

Operacja zakończyła się klęską, ponieważ dokonane przeze mnie zamówienia po prosu zniknęły. Nie ma po prostu tych danych widocznych nawet w menu graficznym. Został wyrzucony Exception na skutek próby pobrania pustej listy (Nie jestem jednak pewien już teraz, czy został on rzucony na skutek Webmetody, czy później). Nie mam niestety już logów ze względu na fakt, że problem był już dość dawno. 

Co do pytania o doGetMySoldItems, to jest ona w dokumentacji opisana jako "**Metoda odtwarza** pełną funkcjonalność zakładki >>**Sprzedane**<< w Moim Allegro", a zaś ta zakładka w menu graficznym ma informację "Zakładką Moje oferty wkrótce zastąpimy Sprzedaję, Sprzedane, Niesprzedane oraz Do wystawienia Oznacza to, że **usuniemy te zakładki** z Mojego Allegro". Wyraziłem po prostu obawę, czy wraz z usunięciem tych zakładek zostanie też usunięta wspomniana wyżej metoda. 

Dziękuję za próbę sprostowania.

Pozdrawiam,
Patryk Cholewa

**Comment by MaciejPotepa** [comment]
@PatrykCholewa Przepraszam za długi czas odpowiedzi. 

1/ Przepraszam za kłopoty, które napotkałeś na naszym środowisku testowym. 

2/ Na ten moment **nie mamy planów co do usunięcia** metody doGetMySoldItems, ale biorąc pod uwagę okoliczności i zmianę zakładek to się może w przyszłości zmienić. Jeżeli taki scenariusz będzie miał wejść w życie to damy znać ze stosownym wyprzedzeniem.

**Comment by PatrykCholewa** [comment]
Zgodnie z oficjalną dokumentacją, od momentu mojego zapytania, ale przed otrzymaną odpowiedzią, wspomniana przeze mnie metoda jednak **zostanie usunięta**. 

> W kwietniu 2019 usuniemy metodę doGetItemsList / In April 2019, we will delete the method doGetItemsList
> Od dziś metodę doGetItemsList oznaczmy jako deprecated.

https://allegro.pl/webapi/news.php#news_100632

Traktuję to oświadczenie jako oficjalne już zamknięcie sprawy.
