### ISSUE TITLE
Pobranie danych historycznych

### ISSUE THREAD

**Issue by AbePersei** [allegro/allegro-api#6180]
Dzień dobry, Czy jest możliwość pobrania danych historycznych sprzedanych produktów przez _**wszystkich użytkowników**_ serwisu przy pomocy API?
 Informacje jakie mnie interesują to: 
1.Informacje o kategoriach oraz ich identyfikatorach: 
-nazwy wszystkich kategorii produktów oraz ich id
 2. Informacje o sprzedanym produkcie:
-id kategorii 
-nazwa kategorii (opcjonalnie jeżeli posiadałbym nazwy kategorii z ich id)
-id produktu 
-nazwa produktu
-ilość sprzedanego produktu
-cena za produkt 
-data sprzedaży
-opis produktu 
-ilość wyświetleń
-opcjonalnie sposób płatności
-opcjonalnie zanonimizowany id sprzedawcy
-Okres powiedzmy od 2022r lub w miarę możliwości poprzednie lata.

**Comment by PrzemyslawLukanowski** [comment]
Nie udostępniamy takiej funkcjonalności, która w pełni spełni Twoje potrzeby. Za pomocą [GET /sale/offers](https://developer.allegro.pl/documentation#operation/searchOffersUsingGET), w polu `stock.sold` pobierzesz informacje o liczbie sprzedanych przedmiotów w ciągu ostatnich 30 dni, a w polu `stats.visitsCount` zwrócimy liczbę wyświetleń, również z ostatnich 30 dni. Szczegóły zamówień, które zwracamy w [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET), udostępniamy przez minimum 180 dni. Nie pobierzesz jednak przez nasze API zamówień starszych niż z ostatnich 12 miesięcy.
