### ISSUE TITLE
Weryfikacja konta allegrosandbox

### ISSUE THREAD

**Issue by nkowalec** [allegro/allegro-api#6181]
Czy mogę prosić o aktywację konta na https://allegro.pl.allegrosandbox.pl/ ?
Zrobiłem konto wczoraj, jutro muszę rozpocząć prace. Login nk-expert.

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem w pełni Twoje konto.

**Comment by nkowalec** [comment]
Serdeczne dzięki.
