### ISSUE TITLE
Problem z wystawieniem aukcji na koncie testowym allegrosandbox 

### ISSUE THREAD

**Issue by Darior950** [allegro/allegro-api#6182]
Problem z wystawieniem aukcji na koncie testowym allegrosandbox.
pojawia się komunikat o nieuregulowanej płatności??
Moje konto to darior950

**Comment by PrzemyslawLukanowski** [comment]
Komunikat jest zgodny z prawdą, ponieważ masz na koncie "nieopłacony" rachunek. Wejdź proszę na stronę ["Rozliczenia z Allegro"](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/rachunki/rozliczenia-z-allegro), wybierz "Zapłać" i za pomocą symulatora płatności ureguluj płatność. Po jej przeprocesowaniu, co może zająć kilka minut, zdejmiemy blokadę sprzedaży.

**Comment by Darior950** [comment]
Dziękuję bardzo za pomoc.
Próbowałem blikiem, a wystarczyło zrobić przelew.
Jeszcze raz dziękuję.
