### ISSUE TITLE
plik csv

### ISSUE THREAD

**Issue by Bobik6K** [allegro/allegro-api#6184]
mam problem z załadowaniem pliku csv, gdyż allegro wymaga maxymalnego rozmairu 5MB. Mój plik ma ponad 17 MB czy w jakiś sposób mogę go skompreować?

**Comment by Lukasz-Zurek** [comment]
W poprzednim [Twoim wątku](https://github.com/allegro/allegro-api/issues/6183#issuecomment-1266866250) napisałem, że sprawa nie dotyczy publicznego API, dlatego aby uzyskać potrzebne informacje skorzystaj proszę z [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
