### ISSUE TITLE
/sale/offers 

### ISSUE THREAD

**Issue by avmarketeu** [allegro/allegro-api#6185]
Dzień dobry.
Mam pytanie odnośnie usuniecia zasobów /sale/offers . Informacje na ten temat są troche niespójne. Informujecie Państwo że zasób /sale/offers zostanie usunięty ale w innym miejscu piszecie że zasób • GET /sale/offers/{offerId} zostanie usunięty ale o scieżce • GET /sale/offers nie ma słowa. To co dokładnie zostanie usunięte?. Zasób GET /sale/offers/{offerId} mozna zastapić • GET /sale/product-offers/{offerId}. Ale jeżeli zostanie usunięty zasób GET /sale/offers to nie widzę zastepstawa gdyż według mnie jest to jedyna sciezka za pomoca której można np. pobrać wszystkie numeru ofert z konta.

**Comment by PrzemyslawLukanowski** [comment]
Na zasobie /sale/offers zostanie usunięta wyłącznie metoda POST, zatem GET /sale/offers pozostanie bez zmian. Szczegóły znajdziesz w [naszych komunikatach](https://github.com/allegro/allegro-api/issues/5729):
<img width="375" alt="Zrzut ekranu 2022-10-5 o 08 14 10" src="https://user-images.githubusercontent.com/51473661/193993365-2a9399b3-e512-4528-bb03-8126bb7acf0c.png">

**Comment by avmarketeu** [comment]
Dziękuje za wyjasnienie
