### ISSUE TITLE
Jakie aukcje są w strefie okazji?

### ISSUE THREAD

**Issue by nowyyy31** [allegro/allegro-api#6186]
Dzień dobry, 

Jakim poleceniem API wyciągnąć wszystkie aukcje które są w strefie okazji? 

Pozdrawiam
Karol Damps

**Comment by PrzemyslawLukanowski** [comment]
Zrobisz to za pomocą [GET /sale/badges](https://developer.allegro.pl/documentation/#operation/getBadges). Więcej informacji znajdziesz w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-przypisac-oferte-kampanii-GRaj0q6Gwuy#kampanie-przypisane-do-ofert).
