### ISSUE TITLE
 https://api.allegro.pl/sale/offers "nowy dziwny komunikat"

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#6188]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Headers:
Accept: application/vnd.allegro.public.v1+json,  content-type: application/vnd.allegro.public.v1+json

{"name":"HL7030 BLUZA Z SZALOWYM KO\u0141NIERZEM__40\/42","category":{"id":"76035"},"delivery":{"handlingTime":"PT24H","shippingRates":{"id":null}},"description":{"sections":[{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11b029\/e89b318f4837b598a167fb4cece6"},{"type":"TEXT","content":"<p><b>OPIS PRODUKTU<\/b><\/p><p>_________________________________________<\/p><ul><li><p>Marka: <b>bpc bonprix collection<\/b><\/p><\/li><li><p>Sk\u0142ad materia\u0142u: <b> 95% bawe\u0142na  5% elastan<\/b><\/p><\/li><li><p>Kolor: <b> CZARNY<\/b><\/p><\/li><li><p>Rozmiar: <b> 40\/42<\/b><\/p><\/li><li><p>Metka papierowa: <b> Brak metki papierowej - Produkt posiada wszystkie metki wewn\u0119trzne.<\/b><\/p><\/li><li><p>Cena katalogowa: <b> 69z\u0142<\/b><\/p><\/li><\/ul>"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/115188\/690a8938430ba18feac4c419c016"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/112817\/a7de81754937a39d34cb918fe98a"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/1122b0\/21a61600493a919dc4a48e088918"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/113ed8\/5fac6a9d4fb18d574bf7ff59fb11"}]},{"items":[{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/11ae61\/53be15c54beca63e9df035e9bcc2"},{"type":"IMAGE","url":"https:\/\/a.allegroimg.com\/original\/112f14\/d1f375a2441b91e796b6d9a30d5f"}]}]},"external":{"id":"easyitem_1755275"},"images":[{"url":"https:\/\/a.allegroimg.com\/original\/1138b1\/7b439f8e40d79b5406c5fe45bbb7"},{"url":"https:\/\/a.allegroimg.com\/original\/11b029\/e89b318f4837b598a167fb4cece6"},{"url":"https:\/\/a.allegroimg.com\/original\/115188\/690a8938430ba18feac4c419c016"},{"url":"https:\/\/a.allegroimg.com\/original\/112817\/a7de81754937a39d34cb918fe98a"},{"url":"https:\/\/a.allegroimg.com\/original\/1122b0\/21a61600493a919dc4a48e088918"},{"url":"https:\/\/a.allegroimg.com\/original\/113ed8\/5fac6a9d4fb18d574bf7ff59fb11"},{"url":"https:\/\/a.allegroimg.com\/original\/11ae61\/53be15c54beca63e9df035e9bcc2"},{"url":"https:\/\/a.allegroimg.com\/original\/112f14\/d1f375a2441b91e796b6d9a30d5f"}],"location":{"city":"TUROBIN","postCode":"23-465","countryCode":"PL","province":"LUBELSKIE"},"parameters":[{"id":"54","valuesIds":["3806_5"]},{"id":"59","valuesIds":["59_2"]},{"id":"451","valuesIds":["451_2"]},{"id":"1294","valuesIds":["1294_8","1294_2"]},{"id":"3786","valuesIds":["3786_109"]},{"id":"11323","valuesIds":["11323_246510"]},{"id":"15851","valuesIds":["15851_1"]},{"id":"18293","valuesIds":["18293_1"]},{"id":"201017","valuesIds":["201017_2317"]},{"id":"201025","valuesIds":["201025_2521"]},{"id":"201069","valuesIds":["201069_262144"]}],"payments":{"invoice":"VAT"},"publication":{"duration":"P7D","status":"INACTIVE","republish":true},"sellingMode":{"format":"AUCTION","startingPrice":{"amount":1,"currency":"PLN"}},"sizeTable":{"id":"ac2a02ee-3bb0-11ec-9f92-b026284ba3e0"},"stock":{"available":1,"unit":"UNIT"},"language":"pl-PL"}

trace-id: ffe2a81b81165b9e

witam, dzisiaj zauważyliśmy taki błąd allegro podczas tworzenia draftu :

W serwisie innym niż [allegro.pl](http://allegro.pl/) wspierane są tylko oferty z opcją Kup Teraz.

o co chodzi i co musimy zmienić, dodam tylko że aukcja ma być wystawiona wyłącznie na allegro i tak ją wysyłamy od ponad 2 lat, nic nie zmienialiśmy.

**Comment by Lukasz-Zurek** [comment]
@mbcont Dziękuję za szczegóły. Przekazuję ten temat dalej do weryfikacji. Wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@mbcont Problem nie powinien się już powtarzać. Przepraszamy za tymczasowe utrudnienia.

**Comment by mbcont** [comment]
@Lukasz-Zurek  a tak z ciekawości to co to za platforma nie allegro.pl?

**Comment by Lukasz-Zurek** [comment]
@mbcont Więcej szczegółów na ten temat będziemy mogli udzielić w przyszłości - udostępnimy odpowiedni komunikat.
