### ISSUE TITLE
Daty odbiorów w /parcel-management/parcel-pickup-request-commands

### ISSUE THREAD

**Issue by PawOb** [allegro/allegro-api#6189]
Prośba o doprecyzowanie dla metody  /parcel-management/parcel-pickup-request-commands, jakie zakresy godzin należy podawać w pickupDate/minTime i pickupDate/maxTime dla przesyłek Allegro One Kurier/Box/Punkt Dzisiaj. Dla przesyłek Allegro One Kurier/Box/Punkt Jutro stosuję zakres 08:00 - 16:00 i tutaj nie ma problemu. Natomiast dla przesyłek z usługą "Dzisiaj" są z tym problemy, szczególnie jeśli mija godzina 15:00. Zamieszanie jest spotęgowane tym, że w zamówieniach nie wiadomo przesyłka jest wewnątrzmiastowa, czy też międzymiastowa. Czy jest przygotowany dla tej metody i różnych sposobów dostaw jakiś algorytm, który można zaimplementować?

**Comment by Lukasz-Zurek** [comment]
Temat ten weryfikuję z odpowiednim zespołem. Wkrótce wrócę z informacją.

**Comment by PawOb** [comment]
A jak odczytać że zamówienie ma mieć przesyłkę wewnątrzmiastową czy międzymiastową?
