### ISSUE TITLE
Edycja redirect_uri w konfiguracji aplikacji lub usuwanie aplikacji

### ISSUE THREAD

**Issue by nataniel** [allegro/allegro-api#619]
W tej chwili nie ma możliwości edycji redirect_uri w konfiguracji aplikacji na https://apps.developer.allegro.pl, przez co jeżeli chcemy zmienić url, trzeba tworzyć nową aplikację, oczywiście z inną nazwą. Powinna być możliwość edycji aplikacji (nazwy, opisu, redirect_uri) lub przynajmniej możliwość usunięcia.

**Comment by nataniel** [comment]
Usuwanie przez komentarze na GitHubie to nie do końca to, o co mi chodziło :-). Aczkolwiek skorzystam, jak już będę miał listę aplikacji do usunięcia.

**Comment by MaciejPotepa** [comment]
@nataniel Domyślam się. Możesz jeszcze wysłać taką prośbę przez [Formularz kontaktowy](https://allegro.pl/pomoc/kontakt).
