### ISSUE TITLE
Aktywacja sprzedaży - sandbox

### ISSUE THREAD

**Issue by NM97** [allegro/allegro-api#6190]
Proszę o aktywację sprzedaży dla konta pomoc.binsoft@gmail.com.

**Comment by Lukasz-Zurek** [comment]
Aktywowałem i zweryfikowałem Twoje konto firmowe.

**Comment by urszulade** [comment]
proszę o aktywację konta na sandboxie: testyita

**Comment by PrzemyslawLukanowski** [comment]
@urszulade Prosimy o pisanie w jednym wątku. Nie mamy takiego użytkownika w naszej bazie. Czy konto zostało aktywowane za pomocą linku aktywacyjnego, który wysłaliśmy na maila?

**Comment by PrzemyslawLukanowski** [comment]
Aktywowałem oba konta, jednak zarówno w jednym, jak i drugim przypadku, są to konta zwykłe. Aby m.in. móc wystawiać oferty przez API, musisz posiadać konto firmowe. Możesz zmienić rodzaj konta za pomocą [tej zakładki](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta) ("zmień na firmowe") i następnie aktywować sprzedaż. W razie problemów, napisz proszę w tym wątku.

**Comment by urszulade** [comment]
Wystawiać przez API nie potrzebuję. Ale płatności przez API już tak - czy do tego też konto formowe musi być?

**Comment by PrzemyslawLukanowski** [comment]
Co dokładnie masz na myśli przez płatności przez API? Jedyne ograniczenia, jakie nakładamy na konta zwykłe w API, to wystawianie i edycja oferty oraz możliwość dodania opcji faktury do oferty.

**Comment by urszulade** [comment]
Zmieniłam konto testyita2 na firmowe. przeszło. aktywowalam sprzedaż, formularz poszedł, pliki przesłałam. Proszę o aktywacje w konta firmowego.

**Comment by urszulade** [comment]
Bo teraz mam błąd: "Aby aktywować sprzedaż zweryfikuj konto." (to pewnie po tej zmianie na konto firmowe)

**Comment by PrzemyslawLukanowski** [comment]
@urszulade Aktywowałem w pełni Twoje konto.

**Comment by dudiqo** [comment]
proszę o aktywację konta: inkpad

**Comment by PrzemyslawLukanowski** [comment]
@dudiqo Aktywowałem Twoje konto.
