### ISSUE TITLE
Problem z płatnościami w zamówieniach

### ISSUE THREAD

**Issue by kl-innosoft** [allegro/allegro-api#6192]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
curl --location --request GET 'https://api.allegro.pl/order/checkout-forms?fulfillment.status=PROCESSING&offset=500' \
--header 'accept: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer xxx'

mamy taką sytuację, że w panelu allegro widnieje informacja o opłaconym zamówieniu `3a56b081-3cf4-11ed-805a-11e6cab448f0` natomiast API w tym zamówieniu zwraca 
```
            "payment": {
                "id": "bcc93871-4411-11ed-bb72-d1914dd88af6",
                "type": "ONLINE",
                "provider": "PAYU",
                "finishedAt": null,
                "paidAmount": null,
                "reconciliation": null
            },
            "status": "FILLED_IN",
            "fulfillment": {
                "status": "PROCESSING",
                "shipmentSummary": {
                    "lineItemsSent": "NONE"
                }
            },
``` 

Czy to błąd po Waszej stronie?

**Comment by PrzemyslawLukanowski** [comment]
Według naszych danych płatność nie została jeszcze przeprocesowana, zatem status zamówienia wydaje się być prawidłowy. Czy mógłbym Cię jeszcze prosić o zrzut ekranu poniższych danych ze szczegółów zamówienia? Czy na pewno widnieje tam informacja, że płatność została zakończona?

<img width="962" alt="Zrzut ekranu 2022-10-6 o 07 14 12" src="https://user-images.githubusercontent.com/51473661/194219854-2f4e65f4-f92b-4387-a8dc-e196f7035fbc.png">

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, wątek zostanie automatycznie zamknięty w ciągu najbliższych 7 dni.
