### ISSUE TITLE
Zapytanie techniczne odnośnie Api - allegro one box / one kurier

### ISSUE THREAD

**Issue by dariuszrup** [allegro/allegro-api#6193]
Dzień dobry,

Nie mogę zintegrować usług:

Allegro One Box (One Kurier)
Allegro One Punkt (One Kurier)
Allegro One Box (One Kurier) - dostawa dzisiaj

przez państwa api.

Za każdym razem jest wysyłany komunikat, że usługa nie jest dostępna:

{"id":"202eaec1-d452-4a47-91ab-935aee2d5895","parcelId":null,"status":"ERROR","errors":[{"code":"VALIDATION_ERROR","message":"Order cannot be send using selected delivery service","details":null,"path":null,"userMessage":"Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy"}]}

WIem, że jest jakaś blokada po kodzie pocztowym -> ale używam kodu dla Krakowa:  31-764 lub 31-048 więc powinno przejść.

Proszę o informację jakich danych użyć - jakiś przykładowy request dla którego system poprawnie tworzy paczkę.

**Comment by PrzemyslawLukanowski** [comment]
Upewnij się, że w polu `serviceId` przekazujesz prawidłową wartość, ponieważ wskazany komunikat wskazuje na problem związany z tym polem. W [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke) znajdziesz tabelę z rozróżnieniem na metody dostawy i usługę dostawy, jaką należy wybrać w każdym przypadku. Pamiętaj, że ID usług dostawy są różne w zależności od konta (czyli np. usługa dostawy 
Allegro One Box (One Kurier) - dostawa jutro będzie miała inne ID na koncie A, inne na koncie B). Problemem nie są kody pocztowe, sprawdziłem je [na stronie One Kurier](https://allegro.pl/kampania/one/kurier) i oba są obsługiwane.

Poniżej przesyłam przykładowy request, który utworzy paczkę. Dane, które musisz zmienić, to oczywiście wspomniane serviceID oraz mail kupującego, tak aby był powiązany z Twoim zamówieniem:

```
{
  "serviceId": 8531582,  
  "receiver": { 
    "address": {
      "street": "Testowa 172",          
      "postCode": "61-132",            
      "city": "Poznań",        
      "countryCode": "PL" 
    },
    "email": "mc27j6sg6k+66a3fb576@user.allegrogroup.pl", 
    "name": "Jan Kowalski",            
    "company": "Allegro.pl sp. z o.o.",   
    "phone": "500600700",                 
    "pointId": null
  },
  "pickup": {         
    "address": {          
      "street": "Testowa 8",              
      "postCode": "61-132",          
      "city": "Poznań",     
      "countryCode": "PL"        
    },
    "email": "email@mail.com",        
    "name": "Jan Kowalski",            
    "company": "Allegro.pl sp. z o.o.",        
    "phone": "500600700",            
    "pointId": null           
  },
  "items": [
    {
      "weight": {              
          "value": 12,
          "unit": "KILOGRAM"
      },                    
      "dimensions": {            
        "height": {                
          "value": 20,
          "unit": "CENTIMETER"
        },                
        "width": {                  
          "value": 20,
          "unit": "CENTIMETER"
        },        
        "depth": {                       
          "value": 20,
          "unit": "CENTIMETER"
        }                 
      },
      "type": "PACKAGE",
      "description": "Car wheels.",  
      "value": {   
        "amount": "2.50",
        "currency": "PLN"
      }
    }
  ],
  "type": "PACKAGE",
  "label": {
    "sender": null,
    "fileFormat": "PDF",              
    "referenceNumber": "abcd1234"  
  },
   "additionalServices": null
 }
```

**Comment by PrzemyslawLukanowski** [comment]
Niestety, nie mogę podać wszystkich serviceID, ponieważ tak jak wspomniałem, nie są to wartości uniwersalne dla każdego z użytkowników - każde konto dysponuje swoimi własnymi identyfikatorami. Wartość z przykładu w przypadku mojego konta to po prostu Allegro DPD, które powyżej kryje się pod 9132804. Dla przesyłek One Kurier musisz użyć serwisu jednego z poniższych:

9628743" Allegro One Box (One Kurier) - dostawa dzisiaj
9628744" Allegro One Box (One Kurier) - dostawa jutro 
9628745" Allegro One Punkt (One Kurier) - dostawa jutro 
9628746" Allegro One Kurier
9630841" Allegro One Kurier - dostawa jutro 
9630842" Allegro One Kurier - dostawa dzisiaj 

w zależności od metody dostawy wybranej przez kupującego. 
Pełen podział metod dostawy na serwis, który należy wybrać, znajduje się [tutaj](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke).

**Comment by dariuszrup** [comment]
Właśnie tu jest problem, bo ustawiając Allegro One Kurier -> 9628746 paczka się normalnie generuje.
Natomiast dla takich samych danych zmiana na Allegro One Box / One Punkt :

9628743" Allegro One Box (One Kurier) - dostawa dzisiaj
9628744" Allegro One Box (One Kurier) - dostawa jutro
9628745" Allegro One Punkt (One Kurier) - dostawa jutro

Czy te serviceId (9628743, 9628744, 9628745) są niepoprawne?

Dostaje błąd o którym pisałem powyżej.

**Comment by PrzemyslawLukanowski** [comment]
Czy mógłbym prosić o trace-id lub commandID, za pomocą którego generujesz przesyłkę? Pozwoli mi to szczegółowo zweryfikować tę sytuację.

**Comment by PrzemyslawLukanowski** [comment]
Chciałbym jeszcze dodać, że nie możesz wybrać dowolnej usługi dostawy One Kurier, ona musi być powiązana z metodą dostawy, którą wybrał kupujący. W Twoim przypadku wygląda na to, że właśnie serviceID 9628746 jej odpowiada.

**Comment by dariuszrup** [comment]
Jak moge w requescie zadeklarować metodę dostawy?

**Comment by PrzemyslawLukanowski** [comment]
W samym requeście, za pomocą którego tworzysz przesyłkę, nie deklarujesz metody dostawy, ale przekazujesz mail kupującego (w polu receiver.email). Ten mail otrzymałeś wcześniej w szczegółach zamówienia [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET) i dzięki niemu wiemy, jaką metodę dostawy wybrał kupujący. A to, jaką wybrał, sprawdzisz również w szczegółach zamówienia w polu delivery.method:

<img width="760" alt="Zrzut ekranu 2022-10-6 o 10 14 54" src="https://user-images.githubusercontent.com/51473661/194259033-08b1e37f-82db-4815-aa1a-d3356c165e20.png">

**Comment by dariuszrup** [comment]
Jaką metode dostawy wybrać aby działały te usługi?
9628743" Allegro One Box (One Kurier) - dostawa dzisiaj
9628744" Allegro One Box (One Kurier) - dostawa jutro
9628745" Allegro One Punkt (One Kurier) - dostawa jutro

**Comment by dariuszrup** [comment]
Załaczam json w requescie jaki wysyłam który zwraca błąd:

`{
    "json": {
        "serviceId": "9628744",
        "receiver": {
            "address": {
                "street": "Luborzycka 30",
                "postCode": "31-764",
                "city": "Krak\u00f3w",
                "countryCode": "PL"
            },
            "email": "tjv0b84amw+2fe9e3e2@user.allegrogroup.pl",
            "name": "Dariusz Rup",
            "company": "",
            "phone": "510507112",
            "pointId": "UP Krak\u00f3w 55"
        },
        "pickup": {
            "address": {
                "street": "Borowskiego 2",
                "postCode": "03-745",
                "city": "Warszawa",
                "countryCode": "PL"
            },
            "email": "info@linker.shop",
            "name": "darek_operator Harry Positive",
            "company": "darek_operator",
            "phone": "504866892"
        },
        "items": [
            {
                "dimensions": {
                    "height": {
                        "unit": "CENTIMETER",
                        "value": "11"
                    },
                    "width": {
                        "unit": "CENTIMETER",
                        "value": "15"
                    },
                    "depth": {
                        "unit": "CENTIMETER",
                        "value": "11"
                    }
                },
                "weight": {
                    "value": "1",
                    "unit": "KILOGRAM"
                },
                "description": "0000065\/LTSB\/22 0\/1",
                "value": {
                    "amount": "0",
                    "currency": "PLN"
                },
                "type": "PACKAGE"
            }
        ],
        "label": {
            "fileFormat": "PDF",
            "referenceNumber": "0000065LTSB22"
        }
    },
    "headers": {
        "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjUwODc2MTksInVzZXJfbmFtZSI6IjQ0MTk3MjAwIiwianRpIjoiMmI2NDViM2QtZjEyZS00MWRkLWIwMDQtNWVlYWUwYzBlNGFlIiwiY2xpZW50X2lkIjoiNmY1MjA4ZDhhNDM2NDA4ZmEzOTg1ZDJlOWZlOGRiMTYiLCJzY29wZSI6WyJhbGxlZ3JvOmFwaTpvcmRlcnM6cmVhZCIsImFsbGVncm86YXBpOnByb2ZpbGU6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczp3cml0ZSIsImFsbGVncm86YXBpOmJpbGxpbmc6cmVhZCIsImFsbGVncm86YXBpOmNhbXBhaWducyIsImFsbGVncm86YXBpOmRpc3B1dGVzIiwiYWxsZWdybzphcGk6YmlkcyIsImFsbGVncm86YXBpOnNhbGU6b2ZmZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpvcmRlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTphZHMiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6d3JpdGUiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOnJlYWQiLCJhbGxlZ3JvOmFwaTpyYXRpbmdzIiwiYWxsZWdybzphcGk6c2FsZTpzZXR0aW5nczpyZWFkIiwiYWxsZWdybzphcGk6cGF5bWVudHM6cmVhZCIsImFsbGVncm86YXBpOm1lc3NhZ2luZyJdLCJhbGxlZ3JvX2FwaSI6dHJ1ZX0.icrZYE8laUlKnNLhG6vKaRZ-Zw8rU7Q4Si5-vl8AvYcSxaAQgl0itXLfdC0mZRy7eJD9zy1MvqonbvN3p0FDfUTv93kqvhIOCkswc1tmFpQ10XeXtdnfcMvpwhzYMyiJlaxSu4ts84TUvFFQDnEMV_0nTEMgqejXGoX-jaLiH13ekrTZAYoaTUmceylTwtdbZN_JZVt5wiYDYes9z5XpOtnNmlELEUANu1GzDXF9y5ysR4OEobbEfO6GOzpCqheiCM9d8FZ2Io_nPMLXt78cPagFgV9iDOyAsiw80Y1Zpk1M_OgNKTHJw4U9zkGcFTxEtdrDB4JgTFZ6MpA4hjlPktdv9VcBB9H29ELtRE5-G0y9D1UqoaY_rkNV2uLABsTK6fWr73B6OcOlzYyLZghqtutU6qieuDpEw7hBPNxYVD55dYktqefpICKsORknA8IAPnpZ9ZYk8Pl31H9ZYAvEGM0-po7KNGrpE9j9vqw4uu5CrvqRa4FeJq_Zi5b5fnz9Xp7JGWSXRRJmLcpeMMISVPXw9krHHS6RU5TWgf9BUgpjatjrVmfsUqpFhUUhnK1ekFsrwlB69D4jBuqop_uZVZXDyAEjcKARSqPRINkkOIuAKBNUBbPWBDyS05lwhnSHJFajA1sALYuLtmSxK0aQMlZxo_xkcpprFHI3wgpgnB8",
        "Accept": "application\/vnd.allegro.public.v1+json",
        "Content-Type": "application\/vnd.allegro.public.v1+json"
    }
}`

**Comment by PrzemyslawLukanowski** [comment]
9628743" Allegro One Box (One Kurier) - dostawa dzisiaj
metoda:

>             "id": "0e454c54-21dd-4e5c-9db2-0553724f9077",
>             "name": "Allegro One Box, One Kurier - dostawa dzisiaj",

9628744" Allegro One Box (One Kurier) - dostawa jutro
metoda:

>             "id": "0b9bed2c-0bc1-4e1f-9694-29bb39ebb483",
>             "name": "Allegro One Box, One Kurier",

9628745" Allegro One Punkt (One Kurier) - dostawa jutro
metoda:

>             "id": "0ee3467f-5451-4060-856e-7a2b502abe55",
>             "name": "Allegro One Punkt, One Kurier",

**Comment by PrzemyslawLukanowski** [comment]
Przyznam, że nie wiem, czy do końca dobrze rozumiem pytanie, ponieważ metodę dostawy wybiera kupujący spośród tych, które sprzedawca udostępnia w cenniku dostaw. Jako sprzedający możesz zarządzać cennikami dostaw, przypisywać do nich różne metody, zarówno za pomocą API jak i przez web.
