### ISSUE TITLE
Hurtowa zmiana czasu wysyłki

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6195]
Czy z poziomu API jestem w stanie zmienić hurtowo czas wysyłki dla X ofert jednocześnie? Potrzebuję wykonać mechanizm, który będzie umożliwiaj nam szybką zmianę czasu wysyłki dla wybranych ofert

**Comment by PrzemyslawLukanowski** [comment]
Przykro mi, ale nie jest to możliwe. Możesz natomiast skorzystać z metody [PATCH na zasobie /sale/product-offers/{offerID}](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#edycja-pojedynczej-oferty), dzięki czemu nie będziesz musiał wcześniej pobierać szczegółów oferty za pomocą metody GET, ponieważ w JSON możesz przekazać tylko to pole, które chcesz edytować. Jeden request jest jednak równoznaczny ze zmianą w jednej ofercie.
