### ISSUE TITLE
Connect my order ERP for allegro smart,shows Error code

### ISSUE THREAD

**Issue by steven112641** [allegro/allegro-api#6197]
hi there
 I recently tried to use allegro API to interface with my order system are failing to keep showing error codes like (Numer błędu: 90da941af8b47e62), whether it is clearing my browser of cookies or changing the browser are failing. I want to use the API to connect to my order system for allegro smart.
Please check the attachment
![45](https://user-images.githubusercontent.com/115202845/194461373-12d143e9-d126-4757-bd4b-3c186bb71a41.PNG)

best regard

**Comment by steven112641** [comment]
![563](https://user-images.githubusercontent.com/115202845/194461629-f756eb5d-30b4-4d75-811e-86dd6c6b139d.png)

**Comment by PrzemyslawLukanowski** [comment]
Hi, The error is caused because of a discrepancy in the redirect URI in Allegro Developer Apps and the one you provide in your application (http://info.edaeu.com/index_debug.php/Public/getAllegroToken/id/1) - these addresses must be the same. It seems there's a missing "7" in the second URI. Also, I removed two of your images. Please keep in mind not to share sensitive data.

**Comment by steven112641** [comment]
hi there
thanks very much for your help. the problem is solve
best regard

________________________________
发件人: PrzemyslawLukanowski ***@***.***>
发送时间: 2022年10月7日 13:32
收件人: allegro/allegro-api ***@***.***>
抄送: steven112641 ***@***.***>; Author ***@***.***>
主题: Re: [allegro/allegro-api] Connect my order ERP for allegro smart,shows Error code (Issue #6197)


Hi, The error is caused because of a discrepancy in the redirect URI in Allegro Developer Apps and the one you provide in your application (http://info.edaeu.com/index_debug.php/Public/getAllegroToken/id/1) - these addresses must be the same. It seems there's a missing "7" in the second URI. Also, I removed two of your images. Please keep in mind not to share sensitive data.

―
