### ISSUE TITLE
Pomoc przy podłączeniu API do allegro 

### ISSUE THREAD

**Issue by MichalPiwow** [allegro/allegro-api#6199]
Dzień dobry,

Chciałbym podłączyć hurtownie za pomocą API do allegro czy jest ktoś kto mógłby mi w tym pomóc, nie mam zielonego pojęcia jak to się robi i cud, że w ogóle tu trafiłem. Hurtownia daje jedynie klucz API, gdy wszystko zadziała będę miał możliwość aby wysyłki SMART u mnie na aukcjach, były również darmowe w hurtowni, jeśli jest ktoś w stanie zaoferować mi pomoc bardzo był bym wdzięczny.

**Comment by Lukasz-Zurek** [comment]
Najlepiej będzie jak w sprawie konfiguracji skontaktujesz się z hurtownią. Nie mamy wiedzy na temat tego jak działa wspomniana integracja zewnętrzna. Hurtownia powinna Cię poinstruować oraz umożliwić autoryzację i uwierzytelnienie.

**Comment by MichalPiwow** [comment]
Hurtownia właśnie nie pomoże ona daje jedynie dostęp, tutaj wysyłam link o co konkretnie chodzi [https://tanie-zakupy.pl/apidocs/allegro-smart]

**Comment by MichalPiwow** [comment]
Ja jestem w stanie to zrobić sam, tylko potrzebuje nakierowania tutaj na allegro developer na początku co gdzie kliknąć.

**Comment by Lukasz-Zurek** [comment]
Na [wskazanej stronie](https://tanie-zakupy.pl/apidocs/external-integrations) hurtownia informuje o tym, że jeśli korzystasz z gotowych integracji - musisz kontaktować się bezpośrednio z firmą, która tą integrację utworzyła. Jako przykład hurtownia podaje jedną z większych integracji. Tam również jest stosowna instrukcja.

Nie jestem pewien czy na pewno chciałbyś utworzyć odrębną aplikację/integrację z Serwisem Allegro, by później zintegrować się z hurtownią. Proces tworzenia aplikacji wymaga wsparcia developerów. Jest to złożony proces. Główne procesy Allegro API opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/najwazniejsze-procesy-allegro-w-pigulce-lLAZ8eOP0SP).

Myślę, że w tej sytuacji raczej pozostaje Tobie skorzystanie z jednej z istniejących już integracji, a tutaj niestety nie pomogę.
