### ISSUE TITLE
Jak zarządzać/dodawać/usuwać wyróżnienia (promowanie) ofert przez RestAPI

### ISSUE THREAD

**Issue by r-a-f** [allegro/allegro-api#62]
Nie widzę nigdzie opisu na ten temat w nowej dokumentacji Rest API.

**Comment by TomekKaczmarek** [comment]
Niestety, nie mamy jeszcze takiej opcji. Ofertą możesz zarządzać przez WebAPI. Zmiany promowania wykonaj ofertą [doChangeItemFields](https://allegro.pl/webapi/documentation.php/show/id,922).
