### ISSUE TITLE
[REST] - Zmiana kategorii. PUT /sale/offers/

### ISSUE THREAD

**Issue by Rnapzsih** [allegro/allegro-api#620]
Czy można zmienić kategorię już wystawionej aukcji przez PUT na zasobie https://api.allegro.pl/sale/offers/ ??

Niestety zrobił się bałagan  
Dom i Ogród->Wyposażenie->Oświetlenie->Lampy  dostała podkategorie i nie wiem na jakiej zasadzie moje aukcje zostały przypisane do tych podkategorii , na pewno nie po **rodzaju lampy** 

Próba zmiany kategorii daje takie komunikaty: 

`[1881] => {"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/7524258807","userMessage":null}]}`

**Comment by Rnapzsih** [comment]
Tak szczerze to mam nawet problem ze wznowieniem aukcji (7535328351) przez panel  

Kategoria
Dom i Ogród - Wyposażenie - Oświetlenie - Lampy
Nr kategorii 5318

Formularz nie ładuje się, zatrzymało się na Kategorii, gdzie nie mogę nic zmienić.... nie ma parametrów... nic.

**Comment by MaciejPotepa** [comment]
Kategorię w ofertach możesz zmienić do 12 godzin od wystawienia lub do momentu zakupu. 

W jaki sposób dokładnie próbujesz wznowić ofertę 7535328351? Opisany przez Ciebie błąd nie wskazuje miejsca gdzie występuje problem.

**Comment by Rnapzsih** [comment]
Co do: 7535328351

Zaznaczam, że nie próbowałem jeszcze zmienić za pomocą PUT na sale/offers/$id - kategorii tej aukcji. Więc opisuje jak to robiłem jeszcze kilka dni temu. 

Najpierw aktualizacja stanów - GET i PUT na sale/offers/$id: 
` {"errors":[{"code":"VALIDATION_ERROR","message":"ERR_CATEGORY_NOT_FOUND","details":"","path":"","userMessage":""}]} ` - Oczywiście wiem co to znaczy - Nr kategorii 5318 - to nie jest już kategoria najniższego rzędu. 

Następnie publikacja - PUT sale/offer-publication-commands 
`{"id":"90300b13-1c6d-40e0-84c9-93d396dea90a","taskCount":{"total":0,"success":0,"failed":0}}`

`Array ( [tasks] => Array ( [0] => Array ( [offer] => Array ( [id] => 7535328351 ) [message] => OfferRepository error [status] => FAIL [scheduledAt] => 2018-09-18T15:54:49.001+02:00 [finishedAt] => 2018-09-18T15:55:04.894+02:00 [field] => publication ) ) ) ` - Wynik publikacji nie jest żadnym zaskoczeniem, skoro edycja stanów zwróciła błąd. 

A teraz opisana wyżej próba edycji/wznowienia poprzez **panel allegro**, powiem to tak, przez **panel allegro** nie ma możliwości wznowienia tej aukcji. Nie mam możliwości zmiany kategorii, a z pól formularza ładuje się tylko pole Tytuł. Nic więcej się nie ładuje.

**Comment by Rnapzsih** [comment]
Dobra próbowałem zmienić kategorię poprzez PUT na sale/offers/$id:

`{"errors":[{"code":"ERROR","message":"An error has occurred","details":null,"path":"/sale/offers/7535328351","userMessage":null}]}{"id":"fd78eb4b-9962-458b-9051-43667f5fb5f4","taskCount":{"total":0,"success":0,"failed":0}}`

**Comment by AniaMalinowska** [comment]
Prosimy, [podeślij nam](https://allegro.pl/pomoc/kontakt#appId=c6833109-86ff-46db-a0f8-45f311a30470&subjectId=9fe60f94-a07b-47e5-84b4-b15beafe2422) pełen cURL z PUT, jakiego próbujesz wysłać.

**Comment by Rnapzsih** [comment]
@AniaMalinowska Ale odnośnie czego? Zmiana stanów dla aukcji aktywnych **działa** bez problemu, zmiana stanów dla aukcji zakończonych **działała** bez problemu, do czasu jak kategoria 5318 była kategorią najniższego rzędu. Więc cURL mam prawidłowy. Więc gdzie miałbym mieć błądw cURL?

**Comment by mr-luke** [comment]
@AniaMalinowska aby potem nie było, że nie podajemy przykładów. Oto i on, znaleziony dziś rano: #628

**Comment by MaciejPotepa** [comment]
> > Kategorię w ofertach możesz zmienić do 12 godzin od wystawienia lub do momentu zakupu.
> > W jaki sposób dokładnie próbujesz wznowić ofertę 7535328351? Opisany przez Ciebie błąd nie wskazuje miejsca gdzie występuje problem.
> 
> To może warto popracować nad jakością zwracanych komunikatów/błędów? 😏 Wasze API pełne jest błędów klasy "Coś się chyba stało", "Bo nie" etc.

Wiemy o tym doskonale, Ty sam przypominasz nam o tym co jakiś czas, co bardzo doceniamy.  Zapewniam, spędza nam to sen z powiek i chcemy to zmienić. :)

@mr-luke Dzięki za zaangażowanie w temat. Pracujemy nad rozwiązaniem. ;)

**Comment by Rnapzsih** [comment]
@MaciejPotepa, po rozmowie telefonicznej z Key Account Managerem Home & Garden Market Panem Adamem, zostaje tylko kwestia tego, że nie działa mi wznowienie zakończonych aukcji które przypisana są do kategorii 5318, wiem to nie jest już kategoria najniższego rzędu. Teraz pytanie, czy w tych aukcjach (zakończonych) też jest ograniczenie do zmiany kategorii 12h od czasu wystawienia? Jeżeli tak to nie ma tematu.  Wtedy wszystko po stronie API działa prawidłowo. 

Zaznaczę tylko, że ludzie wystawiający w dziale Lampy będą mocno zdenerwowani, gdyż z zakończonymi aukcjami, przypisanymi do kategorii 5318 nie można nic zrobić, czy to przez API czy przez panel allegro.

**Comment by MaciejPotepa** [comment]
> @MaciejPotepa, po rozmowie telefonicznej z Key Account Managerem Home & Garden Market, Panem Adamem, zostaje tylko kwestia tego, że nie działa mi wznawianie zakończonych aukcji, które przypisana są do kategorii 5318, wiem to nie jest już kategoria najniższego rzędu. Teraz pytanie, czy w tych aukcjach (zakończonych) też jest ograniczenie do zmiany kategorii 12h od czasu wystawienia? Jeżeli tak to nie ma tematu. Wtedy wszystko po stronie API działa prawidłowo.

Tak, w ofertach zakończonych również jest ograniczenie do 12 godzin. Ogólna zasada jest taka, że po upływie 12 godzin nie można zmienić kategorii, chyba, że w ofercie będzie sprzedaż przed upływem 12 godzin, to zmiana kategorii zostanie zablokowana z momentem sprzedaży.
