### ISSUE TITLE
Jak hurtowo zwiększyć ceny o 10% wszystkich ofert

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#6200]
Witam,
Jak w temacie, chciałbym szybko zwiększyć ceny wszystkich ofert o 10%.
Nie mam czasu w tej chwili studiować dokumentację Rest Api.
Mam pytanie jak mogę to zrobić.
Zależy mi na czasie.

**Comment by Witold1983** [comment]
Póki co znalazłem w dokumentacji to,
tylko najchętniej podałbym listę wszystkich ofert i ich nowych cen w jednym zapytaniu...

curl -X PATCH
‘https://api.allegro.pl/sale/product-offers/9531382307’
-H 'Authorization: Bearer {token}'
-H 'Accept: application/vnd.allegro.public.v1+json'
-H 'Content-Type: application/vnd.allegro.public.v1+json'
-d ’{
"sellingMode": {
"price": {
  "amount": "50",
  “currency”: “PLN”
}
}    
}’

**Comment by Lukasz-Zurek** [comment]
Cenę w wielu ofertach (w liczbie od 1 do 1000) zmienisz za pomocą [PUT /sale/offer-price-change-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/priceModificationCommandUsingPUT). W [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#cena) sprawdzisz różne sposoby zmiany ceny, w tym również o podany procent.
