### ISSUE TITLE
Parametr  MARKA w kategorii pościele (ID 15989)  (globalny id parametru Marka 248811)

### ISSUE THREAD

**Issue by mbcont** [allegro/allegro-api#6201]
Witam, nasz klient skontaktował się z działem technicznym allegro ponieważ pole Marka w kategorii pościele zaczęło zwracać Marki samochodów, myśleliśmy że to jest błąd, ale dostaliśmy taką odpowiedź co nie ukrywam nas zaskoczyło : 

"Otrzymałem odpowiedź od naszego zespołu, że w kategorii Allegro > Wyposażenie > Pościel i koce > Prześcieradła (ID 15989) wykorzystujemy globalny parametr Marka (ID 248811) do określania marki produktu. Oznacza to, że spójne ID parametru wykorzystane w wielu kategoriach. Parametr ten umiejscowiony jest w kategoriach z obszaru Domu i Ogrodu. Jednocześnie praca naszych zespołów technicznych doprowadziła do pożądanej delimitacji słowników w kategorii. Oznacza to, że w ramach wszystkich kategorii, w których występuje parametr, udostępniamy (ale nie pokazujemy) wszystkie wartości dostępne w tym parametrze.

W formularzu wystawiania, cały słownik parametru jest udostępniony, ale ograniczony - w ramach parametrów z dużą liczbą wartości, wyświetlamy okno do wyszukania/wpisania frazy. Wpisując po kolei znaki, otrzymujemy 10 podpowiedzi najbardziej zbliżonych do wpisywanej frazy. 

Aktualnie System ten działa prawidłowo przy wystawianiu oferty bezpośrednio przez nasz Serwis. Jeśli jest Pan w stanie sprecyzować jaki błąd/problem występuje w API, to proszę o takie informacje, wraz ze zrzutami ekranów. Dzięki temu będziemy mogli przyjrzeć się Pana sprawie bliżej.

W razie dodatkowych pytań pozostaję do dyspozycji."

Chce zrozumieć motywacje, proszę o informacje co wami kierowało, że się zdecydowaliście na taki krok?
Czy macie jakiś pomysł jak to obsłużyć na froncie, żeby w miarę dział wybór tak obszernego parametru?

**Comment by Lukasz-Zurek** [comment]
Twoje pytanie nie dotyczy stricte Allegro API. Szczegółowe informacje uzyskasz korzystając z naszego [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1).

**Comment by mbcont** [comment]
@Lukasz-Zurek a czego niby dotyczy ? zasobu odpowiedzialnego za kategorie i parametry

**Comment by Lukasz-Zurek** [comment]
Twoje pytania dotyczą kategorii i parametrów, ale nie w kontekście API.

**Comment by mbcont** [comment]
to w takim razie chciałem zgłosić, że parametr od id 248811 w kategorii pościele ID 15989 zwraca głupoty tzn.
https://api.allegro.pl/sale/categories/15989/parameters

np: 
`{
    "id": "248811",
    "name": "Marka",
    "type": "dictionary",
    "required": true,
    "requiredForProduct": true,
    "unit": null,
    "options": {
        "variantsAllowed": false,
        "variantsEqual": false,
        "ambiguousValueId": "248811_950468",
        "dependsOnParameterId": null,
        "requiredDependsOnValueIds": null,
        "displayDependsOnValueIds": null,
        "describesProduct": true,
        "customValuesEnabled": true
    },
    "dictionary": [
        {
            "id": "248811_1150475",
            "value": "\"MSpa",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_958056",
            "value": "(Geberit, Mexen)",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1019221",
            "value": "101lights",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1091847",
            "value": "151",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_949828",
            "value": "1Control",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1081242",
            "value": "2313190003211",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1220973",
            "value": "24bottles",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1157545",
            "value": "24garden",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1154797",
            "value": "295 Studio",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1023190",
            "value": "2AIM",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1187197",
            "value": "2G",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1187858",
            "value": "2G Lipov",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1017152",
            "value": "2K",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1073204",
            "value": "2MS Serwis",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1112258",
            "value": "2MStalSystem",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_949829",
            "value": "2VV",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1065554",
            "value": "3Claveles",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1189512",
            "value": "3DeXtruder",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_972154",
            "value": "3DLIGHT",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1189436",
            "value": "3D Rings",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_973491",
            "value": "3M",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1143717",
            "value": "3 Sprouts",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1158206",
            "value": "3xW",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1107938",
            "value": "4Aqua",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1125906",
            "value": "4Bee",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1137043",
            "value": "4concepts",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_949830",
            "value": "4Deck",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_1133699",
            "value": "4Dekor",
            "dependsOnValueIds": []
        },
        {
            "id": "248811_949833",
            "value": "4ektech",
            "dependsOnValueIds": []
        },
  {
            "id": "248811_1017678",
            "value": "Zygmunt Wachowiak Zakład Rzemieślniczy",
            "dependsOnValueIds": []
        },`

gdzie połowa wartości w tym parametrze ma tyle wspólnego z pościelą co św.............. z gwiazdami
Proszę o weryfikacje powyższych wartość? lub jeśli to nie błąd z czego one wynikaja w tej kategorii?

**Comment by Lukasz-Zurek** [comment]
Parametr ten jest wspólny dla wielu różnych kategorii w dziale "Dom i Ogród", np. 54068 (imbryki) czy 64607 (poduszki), w związku z czym - w słowniku dostępne są różne marki.

**Comment by mateuszbienias** [comment]
czy to tak będzie wyglądało już zawsze ? czy to jest tymczasowe? jeśli zawsze to w jakim celu?

**Comment by Lukasz-Zurek** [comment]
@mateuszbienias Nie mam wiedzy o tym, czy tak będzie już zawsze. Z dostępnych mi informacji wynika jednak, że w najbliższym czasie nie będzie zmian w tym zakresie. Przyporządkowanie wszystkich marek per dział w ramach globalnego parametru miało na celu zmniejszenie liczby parametrów i wartości.

**Comment by mbcont** [comment]
ok. ale zamiast zmniejszyć liczbę parametrów to mam wrażenie, że ją zwiększyliście, a na domiar złego zrobił się taki syf, że wg mnie najlepszym rozwiązaniem do wywalenie parametru marka jako select wprowadzeni inputa, bo dla użytkownika ten worek przypisany per dział jest kompletnie nieobsługiwalny, to jest jakaś kula błota, był porządek jak w bibliotece, to teraz wywaliliście wszystkie książki na ladę i wywiesiliście kartkę samoobsługa.

**Comment by Lukasz-Zurek** [comment]
@mbcont Dziękujemy za opinię. Kwestie dotyczące kategorii i parametrów obejmują cały serwis. API to jedynie ścieżka za pośrednictwem której ów informacje możesz pozyskać/pobrać. Tym samym niestety w tej kwestii nie mamy decyzyjności. Niemniej jednak zachęcam do przekazywania wszelkich sugestii w tym zakresie za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=603fd405-2a43-4abf-83e7-243743286380&subjectId=3c76fd6e-310d-449a-9ca7-08977f5d30c8).
