### ISSUE TITLE
Carrier API timeout

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6202]
Występuje problem: 
 - [x] z zasobem REST API / with a REST API resource
 - [x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

/parcel-management/parcel-create-commands/f89b8b3a-d15d-4cbc-bf21-a4892a0d8fd4

Zarówno dla Allegro One Box jak i Allegro Paczkomaty Inpost

zwraca

{
    "id": "f89b8b3a-d15d-4cbc-bf21-a4892a0d8fd4",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Carrier API timeout.",
            "details": null,
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage": "Upłynął termin oczekiwania na odpowiedź z API w związku z tym przesyłka nie została zamówiona"
        }
    ]
}

Z czym może to być związane?

Integracja z Inpost API raczej działa bo można utworzyć i nadać przesyłkę z poziomu strony Allegro.

**Comment by Lukasz-Zurek** [comment]
Problem zgłosiłem dalej do weryfikacji. Proszę Cię o cierpliwość.

**Comment by Lukasz-Zurek** [comment]
@awawrowicz Masz nieuregulowane rachunki na swoim koncie i InPost nie pozwala Tobie zamówić paczki. Dodam, że pracujemy nad poprawą komunikatu.

Jeśli natomiast chodzi o Allegro One - nie odnotowaliśmy błędów. Prześlij proszę konkretny przykład jeśli problem nadal występuje.

**Comment by awawrowicz** [comment]
Ok, Allegro One to prawdopodobnie inny problem ale odnośnie Inpost nie do końca rozumiem ponieważ mogę utworzyć przesyłkę i ją nadać z poziomu www Allegro a nie mogę tego zrobić przez API? Gdyby przyczyną  były nieuregulowane rachunki to nie powinno działać również przez www Allegro.

**Comment by Lukasz-Zurek** [comment]
Mimo wszystko skontaktuj się z firmą Inpost, aby wyjaśnić tę sytuację. Nie wiem jak to działa na www. Wiem tylko, że powodem błędu dla commandId: f89b8b3a-d15d-4cbc-bf21-a4892a0d8fd4 jest nieuregulowany rachunek.
