### ISSUE TITLE
WzA inpost nowe etykiety

### ISSUE THREAD

**Issue by paafcioc22** [allegro/allegro-api#6203]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Czy od dziś etykiety generowane do inpostu nie powinny mieć nowego wyglądu?
Czy coś trzeba zmienić w API?

**Comment by AureliuszBrussy** [comment]
Etykiety pobieramy od przewoźnika. Po zmianie - InPost zacznie zwracać nowe etykiety.
