### ISSUE TITLE
Brak kampanii AlleObniżka

### ISSUE THREAD

**Issue by esprzedaz** [allegro/allegro-api#6204]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Od 26 września można zgłaszać oferty do "Smart! Week AlleObniżka", ale sale/badge-campaigns w ogóle nie zwraca takiej kampanii. Zakładam, że to nie to samo, co "Smart! Week 2022".

**Comment by AureliuszBrussy** [comment]
Kampania ta nie jest jeszcze dostępna w API. To się zmieni, jednak nie jestem jeszcze w stanie podać konkretów.
