### ISSUE TITLE
Polskie znaki na etykiecie Allegro One

### ISSUE THREAD

**Issue by awawrowicz** [allegro/allegro-api#6205]
Ja mam podobny problem:

/parcel-management/parcels/label?parcelId=99678842

![image](https://user-images.githubusercontent.com/28707773/194570948-f52bfc10-57e8-42be-a327-1414d068071c.png)

_Originally posted by @awawrowicz in https://github.com/allegro/allegro-api/issues/5420#issuecomment-1271635311_

**Comment by Lukasz-Zurek** [comment]
Problem zgłosiłem do zespołu odpowiedzialnego za tę funkcjonalność.

Przepraszamy za utrudnienia.

**Comment by Lukasz-Zurek** [comment]
@awawrowicz Przepraszam Cię za długi czas oczekiwania na odpowiedź. Poprawka została wdrożona i podobny problem nie powinien już występować.
