### ISSUE TITLE
Proszę o link dot. tego jak sprawdzać zadania kolejkowe metody PUT z UUID

### ISSUE THREAD

**Issue by Witold1983** [allegro/allegro-api#6206]
Witam,
Jak w temacie, nie umiem znaleźć w dokumentacji jak mam odpytywać allegro RestApi, aby pobrać stan o tym jak przebiegła realizacja zapytania z UUID: Dla których ofert komendy przeszły a przy których zapytaniach był problem.

**Comment by Witold1983** [comment]
Konkretnie chodzi mi o zmianę cen PUT'em. 
Z jakiegoś powodu na większości ofert cena się nie zmieniła i potrzebuję ich listę.

**Comment by Lukasz-Zurek** [comment]
W przypadku zbiorczej zmiany cen w ofertach, dokładny status sprawdzisz za pomocą [GET /sale/offer-price-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getPriceModificationCommandTasksStatusesUsingGET).

Opisaliśmy to w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-ofertami-7GzB2L37ase#cena).

**Comment by Witold1983** [comment]
Ok, super.
Bardzo dziękuję.
