### ISSUE TITLE
Niewłaściwe linki w artykule "Pierwsze kroki"

### ISSUE THREAD

**Issue by EntropistA** [allegro/allegro-api#6207]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [X] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj#python

Zarówno w opisie, jak i w przykładach kodu występują błędne odwołania do domeny

**https://allegro.pl.allegrosandbox.pl** zamiast **allegro.pl**

Przykłady kodu wykonują się poprawnie jedynie po zmianie linków np. w przykładzie z Python

TOKEN_URL = "https://allegro.pl.allegrosandbox.pl/auth/oauth/token"
wynik: KeyError: 'access_token'

TOKEN_URL = "https://allegro.pl./auth/oauth/token"
wynik: access token = ...

**Comment by PrzemyslawLukanowski** [comment]
Wspomniane przez Ciebie odwołania dotyczą środowiska testowego. Wspominamy o tym w artykule:

> Na potrzeby tego poradnika będziemy rejestrować aplikację na środowisku testowym.
