### ISSUE TITLE
WzA

### ISSUE THREAD

**Issue by Sebastian-Le** [allegro/allegro-api#6210]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
po wybraniu daty/godziny podjazdu dla kurier DPD otrzymuję komunikat błędu:

dla 12 parcelID, dostępne daty/godziny podjazdów

2022-10-10 w godzinach 14:00 - 16:00
2022-10-10 w godzinach 15:00 - 17:00
2022-10-11 w godzinach 10:00 - 12:00
2022-10-11 w godzinach 11:00 - 13:00
2022-10-11 w godzinach 12:00 - 14:00
2022-10-11 w godzinach 13:00 - 15:00
2022-10-11 w godzinach 14:00 - 16:00
2022-10-11 w godzinach 15:00 - 17:00 

Wybieram: 2022-10-10 w godzinach 14:00 - 16:00 , payload:

 {"parcelIds":["99912144","99914267","99915965","99918300","99922977","99924280","99925653","99926510","99927823","99928772","99930346","99932798"],"pickupDate":{"date":"2022-10-10","minTime":"14:00","maxTime":"16:00"}}

otrzymuję zwrotkę z błędem który nie wiele mówi:

[id] => 9b2ebdc0-d5b4-4777-a211-c3fae5ad0202
    [status] => PARTIAL_SUCCESS
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ERROR
                    [message] => Pickup request failed
                    [details] => 
                    [path] => parcelIds[%s]
                    [userMessage] => Nie udało się złożyć zlecenia odbioru
                )

        )

 trace-id: ac624ea9ecc43658

----------------- inne przyklad 1.)

dla 5 z tych 12, inna godzina pojazdu, komunikat ten sam

{"parcelIds":["99912144","99914267","99915965","99918300","99922977","99925653"],"pickupDate":{"date":"2022-10-10","minTime":"15:00","maxTime":"17:00"}}

trace-id: 8d94341349b3724

----------------- inne przyklad 1.)
dla 4 ostatnich z tych 12, komunikat ten sam

{"parcelIds":["99927823","99928772","99930346","99932798"],"pickupDate":{"date":"2022-10-10","minTime":"14:00","maxTime":"16:00"}}

 trace-id: 38495d88eeba8ad

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za przykłady. Wyjaśniamy już tę sytuację bezpośrednio z DPD. Wrócę z odpowiedzią, gdy otrzymamy więcej informacji.

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję za informację, z zamówieniami na jutro nie powinno być problemu - występuje on tylko dla dzisiejszych zamówień podjazdu.. Przepraszam za niedogodności.
