### ISSUE TITLE
Lista ofert z opłatą utrzymaniową

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6211]
W jaki sposób mogę za pomocą API pobrać listę wszystkich ofert, dla których naliczana zostaje opłata utrzymaniowa? Potrzebuję takiej listy, jaka jest w zakładce "Nadchodzące opłaty", ale z poziomu API

**Comment by MartaNowaczyk** [comment]
Za pomocą [GET /pricing/offer-quotes](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#data-naliczenia-kolejnej-oplaty) można sprawdzić opłaty nadchodzące w najbliższym cyklu 10-dniowym - w tym również informację o opłacie utrzymaniowej.
