### ISSUE TITLE
fullfilement status CANCELLED

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6212]
Hi, do you have any details on how to cancell the order from sellers side? I found no mention in documentation. It refernences only cancellation from buyer side (https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#order-cancellation)
I have changed fullfillement status to cancelled, but when looking on the order from buyers account, nothing tells me, I should not expect the orders.
orderId: d3800630-3a79-11ed-a1cf-e1b62c5638f7

![image](https://user-images.githubusercontent.com/109143627/195066630-27be06f6-a192-45d9-a4e8-2c4de96fe931.png)

**Comment by AureliuszBrussy** [comment]
On our platform we do not provide sellers with the function of order cancellation. In situations where an order cannot be fulfilled - we encourage the seller to contact the buyer to clarify the situation. 

There is only an option to change the fulfillment status of the order by using [PUT /order/checkout-forms/{id}/fulfillment](https://developer.allegro.pl/documentation/#operation/setOrderFulfillmentUsingPUT). 

In addition, if for some reason the order was not fulfilled, the seller can also apply for a refund of the commission - we write more about this [in our guide](https://developer.allegro.pl/tutorials/process-orders-PgPMlWDr8Cv#sale-commission-refunds).

**Comment by ZajdaBear** [comment]
Thanks, what is the fullfilemt staus "CANCELLED" intended to be used for?
