### ISSUE TITLE
Błąd: 403 forbidden podczas pobierania parcel-management/delivery-services

### ISSUE THREAD

**Issue by lmichalFerrodo** [allegro/allegro-api#6213]
Dzień dobry,

na serwerze testowym podczas próby pobrania delivery-services otrzymuje błąd:

{StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  x-xss-protection: 1; mode=block
  pragma: no-cache
  x-frame-options: DENY
  trace-id: f76237ea6efd3665
  x-content-type-options: nosniff
  strict-transport-security: max-age=31536000 ; includeSubDomains
  Cache-Control: no-store, must-revalidate, no-cache, max-age=0
  Date: Tue, 11 Oct 2022 12:23:55 GMT
  Content-Length: 352
  Content-Type: application/vnd.allegro.public.v1+json
  Expires: 0
}}

poniżej kod z tworzenia Requesta:
`
string adres_metod = "https://api.allegro.pl.allegrosandbox.pl/";

HttpClient client = new HttpClient();
var url = new Uri(adres_metod + "parcel-management/delivery-services");
client.Timeout = TimeSpan.FromSeconds(3);
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
client.DefaultRequestHeaders.Clear();
client.DefaultRequestHeaders.Add("Authorization", authHeader);
client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("pl-PL"));
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/vnd.allegro.public.v1+json"));
        
odp = await get(client, url);
`
Authorization: Bearer XXXXXXXXXXXXXXXX

Autoryzacje otrzymuje za pomocą Device flow: https://allegro.pl.allegrosandbox.pl/uzytkownik/bezpieczenstwo/skojarz-aplikacje?code=

Token dostępu jest pobierany praktycznie bezpośrednio przed wywołaniem zapytania.

**Comment by AureliuszBrussy** [comment]
Wygląda to na chwilowe problemy z tą usługą na Sandboxie. Spróbuj jeszcze raz - aktualnie problem nie powinien wystąpić.
