### ISSUE TITLE
Zmiana przeliczania znaków w tytułach ofert?

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6214]
Witam,
zauważyłem pojawienie się błędów:
```
Przekroczono maksymalny dopuszczalny rozmiar tytułu oferty (50 znaków, przy założeniu, że niektóre litery i symbole liczone są jako więcej niż 1 znak).
```
Co przedziwne w przypadku tytułów, które mogę nawet znaleźć w istniejących i aktywnych ofertach. Zauważyłem, że wspólnym mianownikiem wszystkich błędów jest dwukrotne wykorzystanie znaku cudzysłowia: `"`. 
Przykładowe trace-Id: 1a3b6877feef1e89

Mógłbym prosić o instrukcję, jak powinienem przeliczać znaki w tytule, aby mieścić się w 50 znakach?

**Comment by AureliuszBrussy** [comment]
Znaki specjalne zamieniane są na encję HTML. W tytule można skorzystać z poniższych znaków specjalnych:

```
Znaki specjalne:'!','@','[',']','#','$','%','^','&','*','{','}','(',')','.',',','/','\\','|','?',' ',';','~','²','³',
'`','\'','’','´','\"','”','"','„','“','″','<','>','_','\t',':','-','=','+','0','…','–','°','°'
```
Dla przykładu przytoczony znak `"` interpretowany jest jako `&quot;` co daje razem 6 znaków.

Czy jesteś w stanie podać przykładową ofertę, gdzie tytuł przekracza 50 znaków - a mimo to jest ona aktywna? Chodzi tutaj o ten tytuł, który aktualnie nie przejdzie walidacji, a wcześniej - przeszedł. Sprawdzimy to.
