### ISSUE TITLE
Błąd przy nadawaniu paczek allegro pocztex

### ISSUE THREAD

**Issue by gallart-pl** [allegro/allegro-api#6215]
Witam, nie możemy nadać paczek przez baselinkera, ich support twierdzi że problem jest w komunikacji z api, przesyłam log w załączniku.
[allegrokurier_460701679.log](https://github.com/allegro/allegro-api/files/9762258/allegrokurier_460701679.log)

**Comment by gallart-pl** [comment]
Mamy w integracji wskazany numer o którym Pan pisze, dla pewności usunąłem go i dodałem od nowa i nadal to samo niestety.

**Comment by AureliuszBrussy** [comment]
Aplikacja nie przekazuje identyfikatora tego punktu - prosiłbym o wyjaśnienie tego z Baselinkerem.
