### ISSUE TITLE
Nadanie przesyłki Allegro One

### ISSUE THREAD

**Issue by krzysda** [allegro/allegro-api#6216]
Witam,
Jakiej metody dostawy powinienem użyć przy formie transportu 08c15d0b-9b24-4b3f-89a8-7a2b502abe55 Allegro One Punkt (One Kurier) nie działa pojawia się błąd Nie można użyć wybranej usługi ponieważ jest ona niezgodna z zamówioną przez kupującego metodą dostawy.

**Comment by AureliuszBrussy** [comment]
Metoda dostawy o id `08c15d0b-9b24-4b3f-89a8-7a2b502abe55` to "Allegro One Punkt". Usługa dostawy odpowiednia dla tej metody to "Allegro One (UPS)". 

W tabeli w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY#jak-utworzyc-nowa-paczke) wskazujemy jaką usługę wybrać dla jakiej metody.
