### ISSUE TITLE
About the categories suggestions api usage

### ISSUE THREAD

**Issue by fxsshiwo** [allegro/allegro-api#6217]
Hello, we use the [suggestion categories api](https://developer.allegro.pl/documentation/#operation/categorySuggestionUsingGET)  to fix our upload directory,
The platform supports English quotes recently, can I continue to call this api with the English name?
Is there a length limit to the name?
Do you need to add Accept-Language to the header?

**Comment by fxsshiwo** [comment]
We can use the Polish title to get the suggestion categories. After Google translating the same title into English, the api returns empty. What is the reason for this situation (the request header has been added Accept-Language: en-US)

English：
**name**：Scale 1: 64 miniature model of the painter igures street scene for
**trace-id**：2b4fe8734ac30c6e
 **response**：`{"matchingCategories": []}`

Polish：
**name**：Skala 1: 64 miniaturowy model malarza igures scena uliczna dla
**trace-id**：742b47734e27d53e
**response**：`{"matchingCategories":[{"id":"16008","name":"Artificial Flowers and Fruits","parent":{"id":"9317","name":"Decorations and Ornaments","parent":{"id":"123","name":"Equipment","parent":{"id":"5","name":"Home and Garden","parent":null}}}},{"id":"93211","name":"Racers","parent":{"id":"305613","name":"Other Series","parent":{"id":"305601","name":"Sets","parent":{"id":"17865","name":"LEGO","parent":{"id":"11823","name":"Building Toys","parent":{"id":"11818","name":"Toys","parent":{"id":"11763","name":"Kids","parent":null}}}}}}},{"id":"309529","name":"Construction blocks","parent":{"id":"322023","name":"Plastic","parent":{"id":"11823","name":"Building Toys","parent":{"id":"11818","name":"Toys","parent":{"id":"11763","name":"Kids","parent":null}}}}},{"id":"259368","name":"Doll Houses","parent":{"id":"307477","name":"Doll Houses and Furniture","parent":{"id":"11825","name":"Dolls and Accessories","parent":{"id":"11818","name":"Toys","parent":{"id":"11763","name":"Kids","parent":null}}}}},{"id":"322030","name":"Figurines","parent":{"id":"11818","name":"Toys","parent":{"id":"11763","name":"Kids","parent":null}}}]}`

**Comment by bingnew** [comment]
Dear allegro team, after uploading the title in English, how long does it take for the platform to automatically translate it into Polish?

**Comment by PrzemyslawLukanowski** [comment]
@fxsshiwo This title doesn't seem fully correct even in Polish. It looks like we had even more problems with the English phrase and that's why we returned an empty array.
@bingnew The offer is translated immediately.

**Comment by bingnew** [comment]
how  adbout description of offer?will you also translate immediately?
![image](https://user-images.githubusercontent.com/72594584/197671352-2a227982-4d8b-4f60-a743-d1cac5b5d31b.png)

**Comment by PrzemyslawLukanowski** [comment]
Yes, automatic translation applies to the title and also description.

**Comment by fxsshiwo** [comment]
> Yes, automatic translation applies to the title and also description.

But why is the description of the offer we posted today not translated?

This is trace_id：`4752774ca5434dc2`

https://allegro.pl/oferta/12785917695

**Comment by PrzemyslawLukanowski** [comment]
We have found a bug on our side - translation is available to download via API (using [GET /sale/offers/{offerId}/translations](https://developer.allegro.pl/documentation/#operation/getOfferTranslationUsingGET)), but it is not updated on our website. In the next few days, we will fix this issue. Sorry for inconvenience.

**Comment by fxsshiwo** [comment]
> We have found a bug on our side - translation is available to download via API (using [GET /sale/offers/{offerId}/translations](https://developer.allegro.pl/documentation/#operation/getOfferTranslationUsingGET)), but it is not updated on our website. In the next few days, we will fix this issue. Sorry for inconvenience.

So can we post offer in English? Or use Polish, wait for the bug to be fixed and then use English

**Comment by PrzemyslawLukanowski** [comment]
You can use Polish till the end of the week, otherwise - when you post offers in English - Polish customers will see offers in English until the fix is implemented.

**Comment by bingnew** [comment]
> 您可以在本周末之前使用波兰语，否则 - 当您以英语发布报价时 - 波兰客户将看到英语报价，直到修复实施。

Is it fixed?

**Comment by PrzemyslawLukanowski** [comment]
It should be fixed today, I'll let you know. Sorry for the delay.

**Comment by fxsshiwo** [comment]
![image](https://user-images.githubusercontent.com/20201824/200797178-b673b33a-6266-45c5-b6c5-f67e3cfeeb4c.png)

After publishing an English offer, can I edit the offer in the background?

**Comment by PrzemyslawLukanowski** [comment]
Yes, but only via API, for example, using [PATCH /sale/product-offers/{offerID}](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#editing-single-offer).

**Comment by PrzemyslawLukanowski** [comment]
Do you mean by our website? Yes, we have such plans, but right now I cannot give you more details about the 
approximate date.
