### ISSUE TITLE
Pytanie do dokumentacji w swagger

### ISSUE THREAD

**Issue by Streamsoft-ecommerce** [allegro/allegro-api#6218]
Witam,
Proszę o sprawdzenie czy klasa 'CompatibilityListProductOfferResponse', która jest wykorzystana w polu 'SaleProductOfferResponseV1.compatibilityList' posiada prawidłowy opis w swagger. (https://developer.allegro.pl/swagger.yaml). Wydaje mi się, że jej opis jest nieprawidłowy i powoduje błędnie generowanie źródeł przy pomocy narzędzia OpenApi. 

Podobnie klasy CompatibilityListProductBased, CompatibilityListManual i CompatibilityListProductBasedProductOfferResponse

**Comment by PrzemyslawLukanowski** [comment]
Skonsultowałem ten temat z odpowiednim zespołem - OpenApi nie wspiera w pełni dziedziczenia typów, którego używamy.

**Comment by Streamsoft-ecommerce** [comment]
> Skonsultowałem ten temat z odpowiednim zespołem - OpenApi nie wspiera w pełni dziedziczenia typów, którego używamy.

Polecacie jakieś inne narzędzie do generowania kodu źródłowego w Java ?
