### ISSUE TITLE
Dodanie umowy własnej Inpost Allegro Sandbox

### ISSUE THREAD

**Issue by michalsenetic** [allegro/allegro-api#6219]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [x] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Dzień dobry,
nie mogę dodać na środowisku testowym umowy własnej z inpost. Wklejam klucz autoryzacyjny, później klikając "Dodaj" nic się nie dzieje. Nie ma znaczenia czy zaznaczę: Używaj oferty dla sprzedawców Allegro. 
Klucz jest na pewno poprawny, działa na koncie na allegro.pl.

Kontaktowałem się wielokrotnie z supportem Allegro, jednak oni sugerowali jedynie spróbowanie z trybu incognito, lub wyczyszczenie  cookies - nie pomogło. 

Będę wdzięczny za pomoc.

**Comment by PrzemyslawLukanowski** [comment]
Klucz autoryzacyjny z produkcji nie zadziała na środowisku testowym. W tym przypadku skonsultuj proszę tę sprawę bezpośrednio z InPost (my nie mamy dostępu do ich testowych kluczy) lub wykonaj testy na przewoźnikach DPD/UPS.
