### ISSUE TITLE
[REST] Nieaktywna aukcja

### ISSUE THREAD

**Issue by SlawomirMizerski** [allegro/allegro-api#622]
Czy nieaktywne aukcje są po upływie jakiegoś czasu przenoszone do archiwum i nie da się ich już wznowić i czy do nieaktywnych aukcji zdjęcia są usuwane ?

**Comment by Rnapzsih** [comment]
Z tego co wiem to po 60 dniach, zdjęcia zostaną usunięte jeżeli nie użyjesz ich gdzie indziej.

**Comment by MaciejPotepa** [comment]
@SlawomirMizerski Po 60 dniach nieaktywne oferty przenosimy do archiwum.
