### ISSUE TITLE
Allegro One - wielopaczkowość

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#6220]
Czy i kiedy planujecie obsłużyć wielopaczkowość dla kuriera Allegro One, konkretnie chodzi mi o kurierów o ID **0d83955a-4297-4169-adef-9790d53b11ff** oraz **0decb356-e694-42e7-82eb-f260691b856f** ?

Przez wielopaczkowość mam na myśli obsłużenie w bramce parcel-management/parcel-create-commands/ dla paramteru items tablicy większej niż z jednym elementem.

**Comment by AureliuszBrussy** [comment]
Kurier Allegro One nie wspiera wielopaczkowości. Aktualnie nie mamy planów, aby to uległo zmianie. Jeżeli jednak coś się w tym temacie zmieni, będziemy o tym informować.

**Comment by relains** [comment]
To po co w ogóle ta funkcjonalność w API WzA skoro nawet Wasz własny kurier tego nie wspiera? Pocztex również nie jest wspierany mimo, że przez API e-nadawcy już takie etykiety wielopaczkowe można nadawać.

**Comment by AureliuszBrussy** [comment]
Jest to coś, co w przyszłości możemy rozszerzać - struktura payloadu na to pozwala. Natomiast na ten moment niczego nie jestem w stanie zadeklarować.  Tak jak wspomniałem, jeżeli coś zmienimy w tym temacie, będziemy to komunikować.
