### ISSUE TITLE
autoryzacja You have been blocked

### ISSUE THREAD

**Issue by dudiqo** [allegro/allegro-api#6221]
Witam, 
testuję autoryzację code flow dla aplikacji napisanej we Flutterze (do allegro sandbox).  Gdy testuję na emulatorze ios, po kliknięciu zaloguj aplikacja normlanie przechodzi do logowania allegro, ale na emulatorze android otrzymuję błąd "You have been blocked", mimo że kod jest ten sam.
Czy ktoś może mi powiedzieć/sprawdzić w czym jest problem? IP które dostawałem w powiadomieniu to: IP: 77.65.179.60, (wczoraj ok. godz 20.13 i wcześniej).

**Comment by AureliuszBrussy** [comment]
Sprawdzimy to. Potwierdź tylko proszę - czy testy były wykonywane manualnie?

**Comment by dudiqo** [comment]
Tak, manualnie.

**Comment by AureliuszBrussy** [comment]
@dudiqo dostałem informację, że Twoja aplikacja korzysta z błędnych endpointów do logowania. Dla środowiska testowego korzystaj z:  https://allegro.pl.allegrosandbox.pl/auth/oauth/. Sposób w jaki korzystać z endpointu do autoryzacji opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR).
