### ISSUE TITLE
Sprawdzenie ilości ofert w produkcie

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6222]
Czy istnieje możliwość sprawdzenia z poziomu API, ile dany produkt z produktyzacji posiada przypisanych aktywnych ofert? Chodzi mi o ogólną liczbę ofert, nie tylko oferty zalogowanego użytkownika

**Comment by AureliuszBrussy** [comment]
Nie, nie ma takiej możliwości - nie udostępniamy takiego zasobu.
