### ISSUE TITLE
Weryfikacja konta sandbox

### ISSUE THREAD

**Issue by asmolkowicz** [allegro/allegro-api#6223]
Witam, proszę o weryfikację konta na sandboxie, login: yellowketchup.

**Comment by AureliuszBrussy** [comment]
Aktywowałem Twoje konto.

**Comment by michaltrojmiasto** [comment]
Również proszę o weryfikacje konta na sandbox, nie mogę wystawić nowej oferty, login: microtel

**Comment by MaciejFrackowiak** [comment]
@michaltrojmiasto Twoje konto zostało zarejestrowane w 2018 roku i niestety obecnie nie mam już możliwości jego weryfikacji. Proszę załóż nowe konto, wówczas będziemy mogli przeprowadzić proces weryfikacji.

**Comment by michaltrojmiasto** [comment]
> @michaltrojmiasto Twoje konto zostało zarejestrowane w 2018 roku i niestety obecnie nie mam już możliwości jego weryfikacji. Proszę załóż nowe konto, wówczas będziemy mogli przeprowadzić proces weryfikacji.

Proszę w takim razie o aktywacje konta: MICROTEL24

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak Proszę w takim razie o aktywacje konta: MICROTEL24

**Comment by MaciejFrackowiak** [comment]
@michaltrojmiasto Nie przeszedłeś wszystkich kroków związanych z rejestracją konta. Ustaw jeszcze np. [wypłaty środków](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty). Uzupełnij także stronę z dokumentami, które należy przesłać - tu prześlij dowolne zdjęcia.

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak Uzupełnione.

**Comment by MaciejFrackowiak** [comment]
@michaltrojmiasto Konto aktywowane i zweryfikowane.

**Comment by michaltrojmiasto** [comment]
@MaciejFrackowiak Dziękuje.
