### ISSUE TITLE
Propozycje zmian w katalogu bez szkicu/aktywnej oferty

### ISSUE THREAD

**Issue by relains** [allegro/allegro-api#6224]
Dzień dobry, sprawa może nie jest bezpośrednio związania z API, ale Helpdesk Allegro nie był w tej kwestii zbyt pomocny.

Mianowicie problem jest taki, że nasze konto drogeriaolmed nie ma statusu apteki. I teraz mamy np. produkt o kodzie EAN 5908311593752, który jest wyrobem medycznym, natomiast został błędnie skategoryzowany w kategorii "Leki bez recepty" i nie możemy dla niego utworzyć oferty, co jest z kolei wymagane by zaproponować zmiany w katalogu.

![image](https://user-images.githubusercontent.com/19413434/195780679-0e3ad467-7ed7-48b6-90c7-717a6b6c6984.png)

Bardzo proszę o umożliwienie w jakiś sposób propozycji korekt do katalogu w takich sytuacjach.

Pozdrawiam
Rafał Stępień

**Comment by AureliuszBrussy** [comment]
Czy zgłaszałeś propozycje zmiany w produkcie? Można to zrobić zarówno przez API ([POST /sale/products/{productId}/change-proposals](https://developer.allegro.pl/documentation#operation/proposeSaleProduct)), jaki przez formularz: [klik](https://allegro.pl/moje-allegro/sprzedaz/zglos-blad-w-produkcie/8ace33d3-502d-4b92-ba42-97817e5775d9). Istnieje możliwość zaproponowania zmiany kategorii:

![image](https://user-images.githubusercontent.com/68948612/195782358-d17f36b7-a333-41da-8fc9-03f42053e4be.png)

**Comment by relains** [comment]
Dziękuję za szybką odpowiedź. Tutaj faktycznie nie dotarłem. Jak się do tego dostać przechodząc przez elementy menu w panelu Allegro?

**Comment by AureliuszBrussy** [comment]
Przejdź do [formularza wystawiania](https://allegro.pl/offer/). Wyszukaj produkt np. po EAN (pole wyszukiwania pod "Wybierz produkt z Katalogu Allegro"). Wybierz konkretny produkt, wyświetlą się jego szczegóły:

![image](https://user-images.githubusercontent.com/68948612/195789554-9fc53d31-10b3-4b40-8ea9-8d3ae0a95a99.png)

W wyświetlonym modalu kliknij na "ZGŁOŚ BŁĄD W PRODUKCIE".
