### ISSUE TITLE
Śr testowe - brak Allegro Standard w cenniku

### ISSUE THREAD

**Issue by PiotrTaraszkiewicz** [allegro/allegro-api#6225]
Przy dodawaniu nowego cennika na środowisku testowym nie widać form dostawy Allegro Standard.
Konto jest już używane od lat i mieliśmy na nim formy dostawy Allegro* .
Czy musimy coś jeszcze zrobić aby można było zdefiniować w cenniku  dostawy Allegro Standard?
Konto: lcsoft

**Comment by MartaNowaczyk** [comment]
Z tego co widzę Twoje konto nie jest do końca zweryfikowane jako firmowe i tu zapewne tkwi problem. Niestety to konto z 2018 roku, weryfikacja była jeszcze w naszym starym procesie przez co nie uda mi się do końca zweryfikować tego konta. W tym wypadku pozostaje utworzenie nowego konta firmowego na sandboxie.

**Comment by PiotrTaraszkiewicz** [comment]
Założyliśmy nowe konto: lcsoft3
Mogę prosić o aktywację? :)

**Comment by MartaNowaczyk** [comment]
To prawidłowa nazwa konta? Niestety, nie widzę jej u nas. Daj znać czy potwierdziłeś konto w mailu aktywacyjnym, który przychodzi z sandboxa (link jest w załączniku).

**Comment by MartaNowaczyk** [comment]
Niestety, nie :( Możesz podać jeszcze adres email, który wpisałeś podczas zakładania konta?

**Comment by PiotrTaraszkiewicz** [comment]
lcsoft3 - było zakładane na tomek@lcsoft.pl
lcsoft4 - najpierw na piotr@prostapaczka.pl a później zmieniałem na  skrzynkę gmail: elce.software@gmail.com

Na skrzynce gmail znalazłem zablokowaną wiadomość w spamie i z ostrzeżeniami.
Mogę prosić o aktywację konta: lcsoft4 ?

**Comment by MartaNowaczyk** [comment]
Widzę konto lcsoft4. Uzupełnij jeszcze proszę dane konta, jak nr konta [w tej zakładce](https://allegro.pl.allegrosandbox.pl/rejestracja/konto-firmowe/ustaw-wyplaty).

**Comment by PiotrTaraszkiewicz** [comment]
Numer rachunku uzupełniliśmy, wykonaliśmy próbę przelewu i wyświetla się ostrzeżenie:
"Do czasu pozytywnej weryfikacji rachunku bankowego wystawianie ofert i wypłaty środków będą wstrzymane.

"

**Comment by MartaNowaczyk** [comment]
O to chodziło. Dzięki tym danym mogłam aktywować Twoje konto firmowe. Powinno być już ok.

**Comment by PiotrTaraszkiewicz** [comment]
Dziękuje bardzo za pomoc :)
Na nowym koncie w cennikach są już formy dostawy Allegro Standard.
