### ISSUE TITLE
Wystawienie podobnej oferty

### ISSUE THREAD

**Issue by mateuszcom** [allegro/allegro-api#6226]
Czy mogę w łatwy sposób z poziomu API wystawić podobną ofertę, bez konieczności przesyłania całych struktur? Chodzi mi o jak najprostszy mechanizm, np. podanie wyłącznie numeru oferty zalogowanego użytkownika

**Comment by mateuszcom** [comment]
Potrzebuję zrobić porządek ze starymi ofertami. Chce wystawić taką samą ofertę, jak ta stara, z tym że po wystawieniu wykonam request odpowiedzialny za zakończenie tej starej oferty.

**Comment by MartaNowaczyk** [comment]
Czyli chcesz wystawić tę samą ofertę, ale z innym numerem. Możesz na przykład pobrać dane oferty za pomocą [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) i wystawić nową z tymi pobranymi danymi za pomocą [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers).
