### ISSUE TITLE
Aktywacja sprzedaży

### ISSUE THREAD

**Issue by PSchelenz** [allegro/allegro-api#6227]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

Czy w środowisku testowym (na sandboxie) na koncie firmowym jedyną opcją aktywacji sprzedaży jest zrobienie przelewu? Próbowałem dzisiaj wykonać przelew online, jednak otrzymałem błąd:
"Szybki przelew online jest niedostępny, zmień IBAN lub skorzystaj z przelewu tradycyjnego".

Zmiana numeru konta na IBAN nie naprawiła błędu.

Próbując zrobić przelew tradycyjny z kolei otrzymałem błąd o "Niepoprawnym numerze rachunku", który z pewnością istnieje.
Numer rachunku był wpisany w formacie:

XX XXXX XXXX XXXX XXXX XXXX XXXX

Czy jest jakaś alternatywna wersja poradzenia sobie z tym problemem? Czy może robię coś nie tak?

**Comment by PrzemyslawLukanowski** [comment]
Tak, taki fikcyjny przelew musi mieć miejsce. Nie udało mi się powtórzyć opisanego błędu - udało mi się wykonać zarówno szyki przelew online, jak i tradycyjny. Czy możesz spróbować ponownie, np. używając innego, wygenerowanego numeru konta?

**Comment by PSchelenz** [comment]
Szybkiego przelewu nie udało się wykonać z 4 różnych numerów kont. 

Jeśli chodzi o przelew tradycyjny, również nie udało się go wykonać, bo bank (w tym wypadku **Alior Bank**) nie przyjmuje takiego numeru konta, jakie zostało wygenerowane na stronie, ani w formie IBAN ani NRB.

Błąd wraz z wygenerowanym numerem konta w załączniku.
![dane_do_przelewu](https://user-images.githubusercontent.com/46569683/196153973-54708c98-d402-4352-a3c3-b999bea2fcfd.png)
![blad](https://user-images.githubusercontent.com/46569683/196154011-b816f47b-0389-421f-8a9b-b5c20e477036.png)

**Comment by PrzemyslawLukanowski** [comment]
Weryfikuję ten temat z odpowiednim zespołem. Wrócę z informacją, gdy będę mógł udzielić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
@PSchelenz Czy mógłbyś jeszcze podać nam login lub adres mailowy, na który zakładasz konto?

**Comment by PSchelenz** [comment]
**Konto założone na allegro sandbox**

Login: netrizon
Email: hello@netrizon.eu

**Comment by PrzemyslawLukanowski** [comment]
Wykonaliśmy przelew manualnie po naszej stronie. Twoje konto powinno już być aktywne. Przepraszam za niedogodności.

**Comment by PSchelenz** [comment]
Zgadza się, konto jest aktywne. Dziękuję za pomoc!
