### ISSUE TITLE
Getting 415 when uploading image

### ISSUE THREAD

**Issue by sellosebastian** [allegro/allegro-api#623]
Most of my images are uploading correctly but every once in a while I get the following response: 

"errorMessage": "415 - "{
"errors":[
{"code":"NotSupportedException","message":"An error has occurred","details":null,"path":null,"userMessage":"An error occurred"}
]
}"",
"errorType": "StatusCodeError"

I've double checked and I am sending a valid jpg-file following all the rules listed regarding uploading images to Allegro. Any idea what the issue could be?

**Comment by MartaNowaczyk** [comment]
Send to us your request. We will verify this.

**Comment by sellosebastian** [comment]
Essentially I'm doing this: 
rp.get(imgUrl).pipe(rp.post({
        headers: {
            "Accept": "application/vnd.allegro.beta.v1+json",
            "Authorization": `Bearer ${token}`,
            "Content-Type": "image/jpeg",
        },
        uri: process.env.ALLEGRO_API_URL + "sale/images",
    })

There's nothing wrong with this. 90% of my images are uploaded correctly.

**Comment by MartaNowaczyk** [comment]
Thanks! 
I need more information. Send me client-id or trace-id.

**Comment by sellosebastian** [comment]
This problem occurs in the sandbox. Sandbox client id is ca90f2ef319b4a9d9a31e11bfaf47682.

**Comment by MartaNowaczyk** [comment]
The solution is still a mystery. Can you give me trace-id? We will try resolve that...

**Comment by sellosebastian** [comment]
Trace-id: 79b163d9c8175ab5

It looks like the image is being uploaded but I get the wrong response code from the sandbox?

**Comment by MartaNowaczyk** [comment]
For this trace-id, we return the correct status: 201 CREATED.
You must check this out in your application or give us another example with trace-id.
