### ISSUE TITLE
Wysyłam z allegro

### ISSUE THREAD

**Issue by PrzemyslawLukanowski** [allegro/allegro-api#6230]
### Discussed in https://github.com/allegro/allegro-api/discussions/6229

<div type='discussions-op-text'>

<sup>Originally posted by **gkrupkowski** October 14, 2022</sup>
Chcę się zintegrować  z Allegro One Box i korzystać z tej usługi. Zapoznałem się z poniższą dokumentacją: https://developer.allegro.pl/tutorials/jak-zarzadzac-przesylkami-przez-wysylam-z-allegro-LRVjK7K21sY .

Nigdzie tu jednak nie widzę generowania paczki na podstawie istniejącego zamówienia. Z panelu allegro, ręcznie da się wygenerować etykietę podając tylko wymiary paczki. Czy przez api przesyłka zawsze musi być przygotowywana poprzez podanie wszystkich danych adresowych? Czy istnieje jakaś możliwość poprzez api, żeby  dane na paczkę od razu zaciągnąć z zamówienia? W jaki sposób w ogóle kojarzy się wysyłkę One Box z konkretnym zamówieniem z allegro? </div>

**Comment by PrzemyslawLukanowski** [comment]
Dane do utworzenia paczki musisz zaciągnąć po swojej stronie na podstawie informacji z zamówienia. Przesyłkę kojarzymy z zamówieniem na podstawie adresu mailowego kupującego, który przekazujesz w polu `receiver.email`.

**Comment by gkrupkowski** [comment]
To jeszcze jedno pytanie, czy jeśli kurier ups jest u nas i tak codziennie i odbiera paczki, to czy musimy dodatkowo korzystać z zamawiania kuriera przez api, czy po prostu możemy przekazać mu paczki jak u nas będzie?

**Comment by PrzemyslawLukanowski** [comment]
Jeśli kurier zabiera wszystko, co przygotujecie, to nie musicie zamawiać osobno takiego zlecenie podjazdu.

**Comment by gkrupkowski** [comment]
Jeszcze kilka pytań o oneboxa.
Czy wymagane jest podawanie wymiarow paczki, wagi i wartosci przy tworzeniu paczki?
Czy mozliwe jest stworzenie dwoch paczek onebox do jedneog zamowienia podjac ten sam email? Czy może właśnie do tego sluzy parametr items? W tym parametrze przekazujemy ile będzie fizycznie kartonów czy elementy z zamowienia? Czy do jednej paczki zawsze wydrukuje sie jeden label czy tyle ile jest itemów?

**Comment by PrzemyslawLukanowski** [comment]
> Czy wymagane jest podawanie wymiarow paczki, wagi i wartosci przy tworzeniu paczki?

Tak, wymagamy tych danych.

> Czy mozliwe jest stworzenie dwoch paczek onebox do jedneog zamowienia podjac ten sam email? Czy może właśnie do tego sluzy parametr items? W tym parametrze przekazujemy ile będzie fizycznie kartonów czy elementy z zamowienia? Czy do jednej paczki zawsze wydrukuje sie jeden label czy tyle ile jest itemów?

To, co opisałeś, czyli utworzenie wielu paczek w ramach jednego żądania, to tzw. wielopaczka, którą aktualnie wspiera wyłącznie DPD. Jeśli chcesz nadać kilka paczek dla jednego zamówienia dla innych przewoźników, musisz wykonać osobny request (jeden request per jedna paczka). W sekcji items wskazujesz liczbę kartonów, czyli to będzie jedna pozycja dla przewoźników innych niż DPD - kolejna paczka to następny, osobny request.

**Comment by gkrupkowski** [comment]
Ale moge zrobic dwie paczki do 1 zamowienia uzywajac onebox wysylajac 2 requesty?

**Comment by PrzemyslawLukanowski** [comment]
Tak.
