### ISSUE TITLE
Nie możesz zarejestrować nowej aplikacji (aktywacja konta)

### ISSUE THREAD

**Issue by marmizg** [allegro/allegro-api#6231]
Występuje problem: https://apps.developer.allegro.pl/
Przy próbie rejestracji nowej aplikacji otrzymuję komunikat
Nie możesz zarejestrować nowej aplikacji.
    Twoje konto nie zostało aktywowane

natomiast na stronie https://allegro.pl/moje-allegro/moje-konto konto jest aktywowane.

**Comment by PrzemyslawLukanowski** [comment]
Podaj proszę login/ID konta i prześlij zrzut ekranu z błędem, który otrzymujesz. Możesz to zrobić tutaj lub za pośrednictwem [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=61571da6-f6de-4b8f-9ab9-699c8c797cfc&subjectId=35c2c795-4f94-49e2-8057-bbf00efe4433) (wtedy dopisz, że dane dotyczą wątku #6231 na GitHubie)

**Comment by marmizg** [comment]
ok. "Twoje zapytanie zostało wysłane do doradcy"

Dla potomnych....
https://apps.developer.allegro.pl/

`Nie możesz zarejestrować nowej aplikacji.

    Twoje konto nie zostało aktywowane

    Do zarejestrowania nowej aplikacji wymagana jest [pełna aktywacja konta](https://allegro.pl/pomoc/dla-sprzedajacych/rejestracja-i-aktywacja/czym-jest-pelna-aktywacja-konta-i-jak-moge-ja-przeprowadzic-GDeq5WOB8uE).`
