### ISSUE TITLE
Wielopaczki - wsparcie dla określonych dostawców

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6234]
Dzień dobry,
przepraszam że może głupio pytam. Nie zdołałem nigdzie znaleźć jednoznacznej odpowiedzi.
Jacy dostawcy wspierają wielopaczki poprzez Wysyłam z Allegro? Głównie zależy mi na dostawcach DPD, Poczta Polska, InPost.
Pozdrawiam.

**Comment by AureliuszBrussy** [comment]
Wielopaczkowość aktualnie wspieramy tylko dla DPD. W przypadku pozostałych przewoźników - jeden request, jedna paczka.

**Comment by hahyes** [comment]
@AureliuszBrussy Dziękuję za odpowiedź i pozdrawiam. :)

**Comment by lmichalFerrodo** [comment]
Czy coś się zmieniło w tym temacie? Czy nadal wielopaczkowość jest obsługiwana tylko przez DPD?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Aktualnie wielopaczkowość wspiera DPD oraz WE|DO.

**Comment by lmichalFerrodo** [comment]
Dziękuje za odpowiedź. A czy Allegro One obsługuje wielopaczkowość?

Pozdrawiam

**Comment by AureliuszBrussy** [comment]
Nie, na ten moment nie.

**Comment by lmichalFerrodo** [comment]
Dzień dobry, czy coś uległo zmianie i zaczęliście Państwo wspierać wielopaczkowość dla innych przewoźników?

**Comment by AureliuszBrussy** [comment]
Nie, sytuacja nie uległa zmianie.
