### ISSUE TITLE
Błąd podczas wystawiania produktów skyshop na allegro 

### ISSUE THREAD

**Issue by patrykr124** [allegro/allegro-api#6235]
Hey! Mam taki problem, podczas wystawiania produktów przez skyshop na allegro wyskakuje mi taki błąd ''Brak dostępu. Nie masz uprawnień do operacji na wskazanej ofercie [Forbidden (OfferAccessDeniedException)] ''  wiecie jak temu zaradzić?

**Comment by MartaNowaczyk** [comment]
Komunikat może wskazywać na to, że próbujesz wystawić ofertę, która nie należy do Ciebie. W tym przypadku najlepiej będzie jak skontaktujesz się bezpośrednio ze Sky-Shop.pl, bo problem może leżeć po stronie integracji. Jest też możliwość, że masz zablokowane konto.
