### ISSUE TITLE
API sale/images zwraca kod 500

### ISSUE THREAD

**Issue by Janusz4** [allegro/allegro-api#6238]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Podczas dodawania zdjęć przy pomocy API przy niektórych zdjęciach dostaje kod 500.
cURL requestu z błedem
curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/images' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMzI2NTMsInVzZXJfbmFtZSI6IjEwNTYwMjMxMyIsImp0aSI6IjE2YTY4YjE1LWIyYTItNGI2ZS1iNWZhLWI2OGFjNGEyMDZiNCIsImNsaWVudF9pZCI6IjhhMWNmYWQxZmJhZDQ4OGM4NmUxOTUzNzI2NGZiN2IyIiwic2NvcGUiOlsiYWxsZWdybzphcGk6b3JkZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpmdWxmaWxsbWVudDpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOmZ1bGZpbGxtZW50OndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpiaWxsaW5nOnJlYWQiLCJhbGxlZ3JvOmFwaTpjYW1wYWlnbnMiLCJhbGxlZ3JvOmFwaTpkaXNwdXRlcyIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIiwiYWxsZWdybzphcGk6b3JkZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YWRzIiwiYWxsZWdybzphcGk6cGF5bWVudHM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOndyaXRlIiwiYWxsZWdybzphcGk6cHJvZmlsZTpyZWFkIiwiYWxsZWdybzphcGk6cmF0aW5ncyIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6cmVhZCIsImFsbGVncm86YXBpOnBheW1lbnRzOnJlYWQiLCJhbGxlZ3JvOmFwaTptZXNzYWdpbmciXSwiYWxsZWdyb19hcGkiOnRydWV9.VueV7aJakISGSbe2rGyeDxJHaMSEVQAdxLiiAEkCzwIs35LdsFcifBa6aoLy9J9RhFht_EpbEnxw7bDsowX_qcHLYFpuuSns4cnPuV5oi9kQR-fiKysylzXUWxkDS-odYq7PjDuS8L8Sdklo7Ig_PIvJjPwCdVYQDDyDZnzxChishcwxZ25Rcx8irqQ0DBCCH1gUemtGUTtyIR5lnHXceqahWnlUijYc8KcIpbvNZWfEqTfVwuiVAzad_2QsySK_rRZRlWFuAJjY5wDZ2StLTAnEqONBvkejKHtr2j2mHR-zuA5ATqEKwq4ZiR8TX4-rTXtPllU0b0jByf4rEkMqvKtHiD4zx6mDDecspdzjvXIc7na5I27u2sEBhZQ89codHyyrIYZdNel8RFVkdh8WQcDNne11XM__jp2fdg9wQWb5nRAUqM3-ugi-5RyrtNv_zyAgmpVRueaac7_ocEIYH_jtCO2mPOVsF0HjBwgyeQObcqIB56iFkrr3PPypS1HJF_po2ZgS4k6cEUgfMWXLGcGO6dqvtm2iXHNP3TS_10l3BuyPArh3C4wFcbC4ywXl1cXgAZC_-z28QnskjpLpRXQigZ1-ERuImeuhrtDDRTi4u7SyqdStXEngHaWVyGwZ0ruytP9j0iNk5FRgNHru-k8ewzJAQr7Och2lz1LFv_o' \
--header 'Cookie: datadome=GI7Go7vY6K8L76GQxhUN.s.e7SrQRsCyta0yK9PO6y5A_oAe0TFk3P0bpRS2YMpn90k3YcbNpjfZjWveNt3g1i~7~MI5ouZXM46F8NcIpTuAcOIeIxAG_rNoNtK6tMc; TEST_QXLSESSID=c7b72efb111a74c324a2e521711ca2cba7436f1f0bcc68//00; _cmuid=68746ea5-1775-47a5-8d42-85b41cba716c' \
--data-raw '{"url":"https:\/\/www.imperial5dev.dev.agendo.pl\/data\/domains\/1\/m_shop_products\/29\/images\/folia-ochronna-hydrozelowa-uzien-na-kazdy-tele.jpg"}'

trace-id: a596ebda547e687f

Response
{
    "errors": [
        {
            "code": "DownloadError.InternalServerError",
            "message": "Downloading image from URL 'https://www.imperial5dev.dev.agendo.pl/data/domains/1/m_shop_products/29/images/folia-ochronna-hydrozelowa-uzien-na-kazdy-tele.jpg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'.",
            "details": null,
            "path": null,
            "userMessage": "Downloading image from URL 'https://www.imperial5dev.dev.agendo.pl/data/domains/1/m_shop_products/29/images/folia-ochronna-hydrozelowa-uzien-na-kazdy-tele.jpg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'."
        }
    ]
}

Jednak przy niektórych zdjęciach działa poprawnie.
cURL requestu poprawnego
curl --location --request POST 'https://api.allegro.pl.allegrosandbox.pl/sale/images' \
--header 'Accept: application/vnd.allegro.public.v1+json' \
--header 'Content-Type: application/vnd.allegro.public.v1+json' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxMzMwMDAsInVzZXJfbmFtZSI6IjEwNTYwMjMxMyIsImp0aSI6IjYwN2YzNDg2LWZlMjQtNGNjYy1iNjJhLWY5MTUwODViMjQ0ZiIsImNsaWVudF9pZCI6IjhhMWNmYWQxZmJhZDQ4OGM4NmUxOTUzNzI2NGZiN2IyIiwic2NvcGUiOlsiYWxsZWdybzphcGk6b3JkZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpmdWxmaWxsbWVudDpyZWFkIiwiYWxsZWdybzphcGk6cHJvZmlsZTp3cml0ZSIsImFsbGVncm86YXBpOmZ1bGZpbGxtZW50OndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpiaWxsaW5nOnJlYWQiLCJhbGxlZ3JvOmFwaTpjYW1wYWlnbnMiLCJhbGxlZ3JvOmFwaTpkaXNwdXRlcyIsImFsbGVncm86YXBpOmJpZHMiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIiwiYWxsZWdybzphcGk6b3JkZXJzOndyaXRlIiwiYWxsZWdybzphcGk6YWRzIiwiYWxsZWdybzphcGk6cGF5bWVudHM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOndyaXRlIiwiYWxsZWdybzphcGk6cHJvZmlsZTpyZWFkIiwiYWxsZWdybzphcGk6cmF0aW5ncyIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6cmVhZCIsImFsbGVncm86YXBpOnBheW1lbnRzOnJlYWQiLCJhbGxlZ3JvOmFwaTptZXNzYWdpbmciXSwiYWxsZWdyb19hcGkiOnRydWV9.vzEfR1gcWpwufro6ixjD6x3an1a0Xbjr9OUaTd7KgHZ1FA9-rpQhRN2oNvLXlgQGCr8NFU1ckAusXW-3kgekK7TS1LYl7QFVXPOxmbI1YsixyN8xe-AaOKDvJBfzlB3zUgO6cErbjdj58eLqzRyX1qi0fZSoL9Nc2m2_yvBY0Dc4i_wNenAs9DL3Qm0b4iAysAs6cB5aSzKncuKc1Gq2iSxaCEbR6OQCrDD_HGEQV1NOLa20qV4dEH9rKsKrbiXaa16uvf6r42TMClH946E94GaZcDMpxl8sX7j5TWzkgjlADyxnjaNkgaLGlPh-ZlwR7NoW_fZfumYE7obHD_ze9NFJxVbNRYTndRejGAxNDhySTc3oO4fMNWhn2JRkK1Wz6RvBZ32vRial_cMmS667ZHoZVAvobgPSzCNLQLsV9YD4F_wNOyZbySDHPR9TH5b-t3SW5g64UMQIUisZik-uEB2uFSjrshMyA-EL6NbvtiFbH3ATKSGVRUzQ7PKZ5zqsA4NvNOmRGAEL1ojVSEdnAvrzU7vrRG_FArctnkvI28hdmUMQfT7AHCPTAxEjnWkIEdOr3_KhFl8Sck7118sRH2oqlCojrcmr5F2C7dybHS4FhL0qo1MkFFvkIiO4h_jWd4WlQApLw2tmMGaluQN48ya-YiHtQ27njt1piaLY7FU' \
--header 'Cookie: datadome=GI7Go7vY6K8L76GQxhUN.s.e7SrQRsCyta0yK9PO6y5A_oAe0TFk3P0bpRS2YMpn90k3YcbNpjfZjWveNt3g1i~7~MI5ouZXM46F8NcIpTuAcOIeIxAG_rNoNtK6tMc; TEST_QXLSESSID=c7b72efb111a74c324a2e521711ca2cba7436f1f0bcc68//00; _cmuid=68746ea5-1775-47a5-8d42-85b41cba716c' \
--data-raw '{"url":"https:\/\/www.imperial5dev.dev.agendo.pl\/data\/domains\/1\/m_shop_products\/27\/images\/recea-bluza-meska-z-kapturem-zielona-recea.jpg"}'

trace-id: cc01d6ca4409c661

Response
{
    "expiresAt": "2022-10-18T16:45:03.038709Z",
    "location": "https://a.allegroimg.allegrosandbox.pl/original/11222f/0b28bcc24d8d8b2213a40bb67095"
}

Od czego zależ to czy upload zdjęcia się powiedzie czy nie?

**Comment by hahyes** [comment]
W przypadku A wysyłasz link, z którego Allegro pobiera zdjęcie. 
W przypadku B wysyłasz plik zdjęcia po prostu.

Serwer pod tym linkiem `https://www.imperial5dev.dev.agendo.pl/data/domains/1/m_shop_products/29/images/folia-ochronna-hydrozelowa-uzien-na-kazdy-tele.jpg` zwraca Allegro błąd 500, więc Allegro nie może tego zdjęcia pobrać.

**Comment by AureliuszBrussy** [comment]
@Janusz4 wygląda na to, że problem występuje po stronie serwera- zwraca on przy części requestów błąd 500.
