### ISSUE TITLE
Marketing Costs

### ISSUE THREAD

**Issue by KFulbiszewski** [allegro/allegro-api#6239]
Witam, nie mogę znaleźć w dokumentacji API który zwróci mi wszystkie Marketing Costy dla mojego konta - mianowicie koszty zwiazane z reklamami, pozycjonowanie, promowaniem ofert? Prosze o pomoc.

**Comment by AureliuszBrussy** [comment]
Zasoby do sprawdzania opłat opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-sprawdzic-oplaty-nn9DOL5PASX#historia-operacji-billingowych). Możesz sprawdzić historię operacji billingowych, datę naliczeń kolejnych opłat czy możliwość oszacowania opłat za ofertę dzięki kalkulatorowi opłat.
