### ISSUE TITLE
Duplikat z innej kategorii

### ISSUE THREAD

**Issue by marmited** [allegro/allegro-api#6240]
Cześć, podczas próby stworzenia produktu na środowisku produkcyjnym nie możemy go stworzyć pomimo wyboru innej parametrów. System zwraca info na temat duplikatu w innej kategorii. Czy to jest normalne? Duplikaty nie powinny być znajdywane tylko wewnątrz tej samej kategorii?

TrackingId: "87480a46e52d6bbf"

**Comment by MartaNowaczyk** [comment]
Cześć, tak, duplikaty są wyszukiwane we wszystkich kategoriach na podstawie parametrów, które identyfikują produkt. Znaleźliśmy duplikat, bo podałeś takie same parametry identyfikujące jak w podanym duplikacie: Producent części, Numer katalogowy części.
