### ISSUE TITLE
ERROR: Pickup street is incorrect

### ISSUE THREAD

**Issue by cemsgh** [allegro/allegro-api#6241]
Dzień dobry.
W odpowiedzi na requesta 80a8acfe-20b4-47e1-bb8e-e3e421977093 otrzymuję
""errors":[{"code":"ERROR","message":"Pickup street is incorrect","details":null,"path":"pickup.address.street","userMessage":"Ulica punktu nadania przesyłki zawiera nieprawidłowe znaki"}]"
Ulica wybranego automatu to "Mościckiego 46A, (obok Kościuszki 16A)" niestety nie znajduję nigdzie informacji o jakie znaki chodzi.
Co jest przyczyną tego błędu?

**Comment by MartaNowaczyk** [comment]
Dzień dobry, w podanym adresie problemem są nawiasy. Poza tym dla punktów nadania nie potrzeba wpisywać adresu.

**Comment by cemsgh** [comment]
Czyli adres musi być poprawny albo pusty? 
W dokumentacji jest to wymagany parametr https://developer.allegro.pl/documentation/#operation/createNewParcel
Z drugiej strony, czy jest chociaż w planach regulacja adresów punktów, tak żeby dane udostępniane przez API spełniały warunki API? (np. długość, numery, znaki)

**Comment by MartaNowaczyk** [comment]
Adres dostawy jest wymagany tylko dla Poczty Polskiej. Staramy się, aby udostępniane dane spełniały warunki. 
Jeśli masz jeszcze jakieś problemy ze zwracanymi danymi podaj nam przykłady.
