### ISSUE TITLE
Access denied. You are not authorized to perform operations on the indicated offer

### ISSUE THREAD

**Issue by sinteit** [allegro/allegro-api#6243]
Konto testowe na Sandbox, W Dane konta Sprzedaż Nieaktywna. Dwa dni temu wyklikałem aktywację sprzedaży na dwóch kontach zwykłe i bieznes i do dzisiaj nie ma zmian. Podejrzewam że komunikat z tematu wpisy Access denied własnie wynika z faktu że na koncie sprzedaż jest nieaktywna. Jak długo czeka się na aktywację dla kont na Sandbox?

**Comment by MartaNowaczyk** [comment]
Podaj mi proszę te dwa konta, sprawdzę i postaram się pomóc w aktywacji.

**Comment by sinteit** [comment]
Podaje loginy i przypisane adresy e-mail
1. sinte_developer, admin@hartmann24.pl - zwykłe
2. hartmann_work, webmaster@hartmann24.pl  - firmowe

Dzięki śliczne z góry za pomoc.

**Comment by sinteit** [comment]
Pani @MartaNowaczyk, muszę kontynuować ten wątek bo nie udało mi się rozwiązać problemu. Przy wystawieniu oferty otrzymuje komunikat:
Something went wrong 403 {"errors":[{"code":"OfferAccessDeniedException","message":"Forbidden","details":null,"path":"","userMessage":"Access denied. You are not authorized to perform operations on the indicated offer"}]}

Zgodnie z zaleceniami w poradniku wystawiamy ofertę z produktem za pomocą zasobu /sale/product-offers
- aktywna oferta powiązana z produktem, który istnieje w naszym Katalogu.
przykładowy POST znajduje się poniżej
{
    "productSet": [
        {
            "product": {
                "name": "Testowy RJ-45",
                "category": {
                    "id": "63052"
                },
                "images": [
                    "http:\/\/www.freepngimg.com\/download\/lion\/3-2-lion-png.png"
                ],
                "id": "4040849964138",
                "idType": "GTIN"
            }
        }
    ],
    "delivery": {
        "shippingRates": {
            "id": "e9a3fe03-3292-4266-b5b5-7b795c7371c6"
        }
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 5
    }
}

Kategoria produktu na pewnosię zgadza, kod GTIN także bo taka oferta znajduje się już w katalogu na sandboxie. 
Próbowaliśmy także inny produkt dla przykładu i komunikat jest dokładnie taki sam
{
    "productSet": [
        {
            "product": {
                "name": "Produkt testowy",
                "category": {
                    "id": "259398"
                },
                "images": [
                    "http:\/\/www.freepngimg.com\/download\/lion\/3-2-lion-png.png"
                ],
                "id": "34c3c3af-9f27-4b1d-ab50-3eaed101fe3a",
                "idType": "GTIN"
            }
        }
    ],
    "delivery": {
        "shippingRates": {
            "id": "e9a3fe03-3292-4266-b5b5-7b795c7371c6"
        }
    },
    "sellingMode": {
        "price": {
            "amount": "220.85",
            "currency": "PLN"
        }
    },
    "stock": {
        "available": 1
    }
}

Autoryzacja konta przebiega poprawnie, zatem pytanie jaki jest inny problem, że nie możemy z naszego konta wystawić takiej oferty, co oznacza ten kod błędu?

**Comment by Dzik-GM** [comment]
Witam, 
przy okazji proszę o aktywowanie mojego konta na sandbox-ie bo mi  wyskakuje nieautoryzowany dostęp
we wszystkim oprócz katalogów...

Test-Api, dzik.kotlet@gmail.com

i z góry dzięki za pomoc

**Comment by MartaNowaczyk** [comment]
@sinteit na którym koncie robisz ten request? Możesz zawsze podesłać trace-id do weryfikacji.

**Comment by sinteit** [comment]
@MartaNowaczyk póki co będziemy wszystko robić na firmowym tak jak docelowo na produkcji będzie to działać. Zatem autoryzacja jest z konta hartmann_work, define('CLIENT_ID', '0d1b3f11d5d44d198a8724c6da93df71');

**Comment by MartaNowaczyk** [comment]
@sinteit z tego co widzę w logach, próbujesz wystawić ofertę z konta zwykłego sinte_developer, stąd błąd.

**Comment by MartaNowaczyk** [comment]
@Dzik-GM niestety, nie mogę aktywować konta Test-Api. Problem jest po naszej stronie. Najszybciej i najprościej będzie jak założysz nowe konto. Przepraszam za te niedogodności.

**Comment by sinteit** [comment]
@MartaNowaczyk do autoryzacji używamy następującego access token 
define('USER_ACCESS_TOKEN', 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU2OTM0OTcsInVzZXJfbmFtZSI6IjEwNTYxMjI4NCIsImp0aSI6IjNhYzE3ODI2LTBiMmEtNDM1Ni04NGY0LWM3MGFjNzRmNDZmMSIsImNsaWVudF9pZCI6IjBkMWIzZjExZDVkNDRkMTk4YTg3MjRjNmRhOTNkZjcxIiwic2NvcGUiOlsiYWxsZWdybzphcGk6b3JkZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwcm9maWxlOndyaXRlIiwiYWxsZWdybzphcGk6c2FsZTpvZmZlcnM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpiaWxsaW5nOnJlYWQiLCJhbGxlZ3JvOmFwaTpzYWxlOm9mZmVyczpyZWFkIiwiYWxsZWdybzphcGk6b3JkZXJzOndyaXRlIiwiYWxsZWdybzphcGk6cGF5bWVudHM6d3JpdGUiLCJhbGxlZ3JvOmFwaTpzYWxlOnNldHRpbmdzOndyaXRlIiwiYWxsZWdybzphcGk6cHJvZmlsZTpyZWFkIiwiYWxsZWdybzphcGk6cmF0aW5ncyIsImFsbGVncm86YXBpOnNhbGU6c2V0dGluZ3M6cmVhZCIsImFsbGVncm86YXBpOnBheW1lbnRzOnJlYWQiLCJhbGxlZ3JvOmFwaTptZXNzYWdpbmciXSwiYWxsZWdyb19hcGkiOnRydWV9.myGScjMZBpW_OjYtmJzA1W_ypLZvAkpBRqgmPZApYNPL7c44BGJijzAVZFSdlQ_XI7J6AUqf3ETqDtHRQ1OC9fBfw4E8GB58MYIalcfr_w5m0ndPyTgbOl3sX8mXEvmNXQWJy0OTS_Q9MD5cHxKxzir-5uh1iHbLiFlprm-DGgRbC--GeHf6J1FWwbozYfS4G57M1MH1drttTVa-ygMKTTJvLtofPNomdOsuTmhxgMWfLaQXH9-5Y0uWmvMmafyPyN85RvJ009TQqavRoXcMssVvtb9ZmjnJj9Hys7FGVB_JYaqz-u459Sb6WRx4lugHel4Ys75NWYgQyYOe9yAkYYw0cAuCye4TG1HKkT4LcygGaLgHLjJaldYZxUErOWdjCU7tA-tDe2ve8uFKtGjVHHAJGoVQMz0pzJIBsixI0rh4SRi1Y_F9Hr3tFgJ1weQmUZH8UIx7HeCTohyGi8V6iuT812LhNAg9rZmJdGl90YSdvP-2IDImadWZ7qa-jkS4mGTsJ89W3uf3HPDsZTmcQmwA_lit1PcTirMM7xwVRPwpsgbEUl-3TuhYiX82tz0lkPYmS_pBczJ7flp3KKHjmYUpNKL6PfZbzbq79SYIZo-DVLooJTkbaPdHCCrNlDHJEBIYO2Q60CI-0wVF4pCYSQzItv1U31PqgeXsFZ4QIeY');

Wygenerowany jest z Client ID i Client Secret aplikacji zarejestrowanej na koncie hartmann_work.

**Comment by sinteit** [comment]
@MartaNowaczyk wywoływałem ten skrypt z przeglądarki na której faktycznie byłem zalogowany na koncie sinte_developer, zrobiłem to teraz z drugiej przeglądarki gdzie logowanie jest na to firmowe konto hartmann_work i komunikat zmienił się na Something went wrong 422 {"errors":[{"code":"ReturnPolicyNotFoundException","message":"Unprocessable Entity","details":null,"path":"afterSalesServices.returnPolicy","userMessage":"The user does not have Returns Terms named: default."}]}
Mam na koncie dwa warunki zwrotu skonfigurowane Podstawowy i Standardowe. 
![warunki_zwrotow](https://user-images.githubusercontent.com/57946737/196885194-d72e3f62-a262-4fc9-8aff-055416a15c61.jpg)

**Comment by MartaNowaczyk** [comment]
@sinteit jeśli chcesz użyć jednego z podanych warunków musisz dodać ich identyfikator w requeście. Automatycznie dodajemy tylko te, które nazwiesz "default".

**Comment by sinteit** [comment]
@MartaNowaczyk, ślicznie dziękuję Ci za pomoc, jest OK, oferta poszła.

**Comment by Dzik-GM** [comment]
> @Dzik-GM niestety, nie mogę aktywować konta Test-Api. Problem jest po naszej stronie. Najszybciej i najprościej będzie jak założysz nowe konto. Przepraszam za te niedogodności.

Założyłem nowe konto:
grzegorz@agencja-promocyjna.eu, DZIK-API
czy można jakoś szybko to aktywować?

i wywala mi adres do rejestracji aplikacji "https://apps.developer.allegro.pl.allegrosandbox.pl" jako nieosiągalny...

**Comment by romigrabarz** [comment]
Mam identyczny błąd przy próbie aktualizacji ilości sztuk na aukcji:
`var client = new RestClient("https://api.allegro.pl.allegrosandbox.pl");
            var request = new RestRequest($"/sale/product-offers/7695845821", Method.PATCH);
            request.AddHeader("Authorization", $"Bearer xxx");
            request.AddHeader("Accept", "application/vnd.allegro.public.v1+json");
            request.AddHeader("Content-Type", "application/vnd.allegro.public.v1+json");
            var requestBody = new
            {
                stock = new
                {
                    available = 90,
                    unit = "UNIT"
                }
            };
            request.AddParameter("application/vnd.allegro.public.v1+json", JsonConvert.SerializeObject(requestBody), ParameterType.RequestBody);
            var response = client.Execute(request);`

Proszę o pomoc.

**Comment by PrzemyslawLukanowski** [comment]
@Dzik-GM Aktywowałem Twoje konto, jednak jest to konto zwykłe. Oznacza to, że nie będziesz miał dostępu do wszystkich opcji, np. wystawiania ofert za pomocą API. Możesz utworzyć nowe konto lub zmienić rodzaj obecnego za pomocą zakładki ["Dane konta"](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

> i wywala mi adres do rejestracji aplikacji "https://apps.developer.allegro.pl.allegrosandbox.pl/" jako nieosiągalny...

Tego błędu nie jestem w stanie odtworzyć, strona ładuje się prawidłowo. Spróbuj proszę wyczyścić pliki cookies lub skorzystać z innej przeglądarki.

**Comment by PrzemyslawLukanowski** [comment]
@romigrabarz Twoje konto również jest kontem zwykłym, co oznacza, że nie możesz edytować ofert za pomocą API. Jak wspomniałem wcześniej, możesz utworzyć nowe konto lub zmienić rodzaj obecnego za pomocą zakładki ["Dane konta"](https://allegro.pl.allegrosandbox.pl/moje-allegro/moje-konto/dane-konta).

**Comment by Dzik-GM** [comment]
Dzięki za aktywowanie konta, ale nadal mam problem z https://apps.developer.allegro.pl.allegrosandbox.pl/ - wywala mi błąd "DNS_PROBE_FINISHED_NXDOMAIN"

> > i wywala mi adres do rejestracji aplikacji "https://apps.developer.allegro.pl.allegrosandbox.pl/" jako nieosiągalny...
> 
> Tego błędu nie jestem w stanie odtworzyć, strona ładuje się prawidłowo. Spróbuj proszę wyczyścić pliki cookies lub skorzystać z innej przeglądarki.

od wczoraj nie mogę wejść na ten adres (do obsługi aplikacji na sandbox-ie)  - na stronę gdzie obsługuje się aplikacje normalne czyli https://apps.developer.allegro.pl/ - wszystko jest ok.
Jestem w kropce bo nie mogę nic zrobić z nowym kontem - testowałem na różnych przeglądarkach i telefonie z różnymi dostępami  - i ciągle to samo, proszę o pomoc. podajcie przynajmniej IP witryny, może tak przejdę...

**Comment by PrzemyslawLukanowski** [comment]
Ten błąd nie wskazuje na problem po stronie naszego serwera, ale bardziej na błędną konfigurację DNS Twojego urządzenia. Nie chciałbym tutaj udostępniać linków do zewnętrznych stron, niezwiązanych z Allegro, ale widzę, że istnieją materiały, które tłumaczą, jak rozwiązać problem związany z tym komunikatem. Czy mógłbyś się z nimi zapoznać? W moim przypadku problem udaje się odtworzyć, jeśli spróbuję wejść na stronę przez link https://www.apps.developer.allegro.pl.allegrosandbox.pl/ ale nie wystąpi, jeśli ominę "www" - https://apps.developer.allegro.pl.allegrosandbox.pl/.

**Comment by Dzik-GM** [comment]
oczywiście że próbowałem, także poprzez VPN-a i pytałem u 2 znajomych - ten sam problem!

**Comment by PrzemyslawLukanowski** [comment]
Rozumiem, weryfikujemy tę sytuację. Wrócę z informacją, jak tylko uda się ustalić więcej szczegółów.

**Comment by PrzemyslawLukanowski** [comment]
Opisany problem już nie występuje, przepraszam za niedogodności.
