### ISSUE TITLE
Problem z generowaniem paczki Inpost na środowisku testowym przez API

### ISSUE THREAD

**Issue by marekbarczyk123** [allegro/allegro-api#6244]
Dzień dobry, mamy problem z generowaniem wysyłek InpostAllegro przez API. Zamówienia i przesyłki generowane na środowiskach sandboxowych. W załączniku przesyłam response, request i błąd, który dostajemy.

 UUID: bca02661-4eb6-11ed-bb79-a363d981901c 
email: kuh1dgvy73+6c414f01@allegromail.pl

Prośba o sprawdzenie i informację, co robimy źle. Z góry dziękuję za pomoc!

**Comment by marekbarczyk123** [comment]
W requeście wysyłamy adres kuh1dgvy73+6c414f01@user.allegrogroup.pl, taki jak na zamówieniu w panelu.
W panelu numer zamówienia to bca02661-4eb6-11ed-bb79-a363d981901c.

![image](https://user-images.githubusercontent.com/116170823/196710723-ce8cc9f5-a0c2-4b37-8144-3a42e793c2e8.png)

**Comment by marekbarczyk123** [comment]
Nie jest czasem tak, że aby zamówienie się pojawiło w API, to musi zostać złożone w Allegro przez API?

**Comment by AureliuszBrussy** [comment]
@marekbarczyk123 nie, oczywiście, że nie ma takiego wymogu. W swojej przykładowej komendzie przekazałeś właśnie wartość kuh1dgvy73+6c414f01@allegromail.pl zamiast kuh1dgvy73+6c414f01@**user**.allegrogroup.pl. Jeżeli w innym requeście przekazywałeś poprawny email i mimo to problem się powtórzył - proszę, przyślij ponownie uuid tej komendy.

**Comment by marekbarczyk123** [comment]
Wczoraj wysyłałem z oboma mailami bo zdziwiło mnie, że do requesta z mailem z domeną @user.allegrogroup.pl dostaję response z mailem receivera z domeną @allegromail.pl.


Tutaj request i response dla komunikatu, gdzie receivera wysyłamy "kuh1dgvy73+6c414f01@user.allegrogroup.pl".

[allegro response i error z poprawnym mailem.txt](https://github.com/allegro/allegro-api/files/9828619/allegro.response.i.error.z.poprawnym.mailem.txt)
[allegro request z poprawnym mailem.txt](https://github.com/allegro/allegro-api/files/9828620/allegro.request.z.poprawnym.mailem.txt)

**Comment by AureliuszBrussy** [comment]
@marekbarczyk123 próbujesz utworzyć przesyłkę korzystając z access tokena, które nie ma zamówienia, z którym powiązany jest adres e-mail "kuh1dgvy73+6c414f01@user.allegrogroup.pl". Zweryfikuj jaki access token używasz.

**Comment by bob0swager** [comment]
Access token generuję ścieżką Device Flow i odświerzam token co 12h
https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow
Czy tego nie wystarczy?
Przy tworzeniu paczki dostaję HTTP code 201, czyli paczka utworzona:
https://developer.allegro.pl/documentation/#operation/createNewParce
Dopiero przy sprawdzaniu statusu utworzonej paczki dostaję błąd (https://github.com/allegro/allegro-api/issues/6244#issuecomment-1284053629):
https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus

**Comment by AureliuszBrussy** [comment]
@bob0swager na zasobie [PUT /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/createNewParcel) część walidacji odbywa się asynchronicznie, w związku z tym to normalne, że ostateczny wynik komendy poznasz dopiero po pobraniu jej statusu [GET /parcel-management/parcel-create-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/getParcelCreationStatus). 

Tutaj chodzi o to, że używasz access tokenu wygenerowanego dla konta X, żeby obsłużyć zamówienie należące do konta Y (bo to konto Y jest sprzedawcą). Zwracamy wtedy błąd, że podany e-mail kupującego nie jest powiązany z żadnym zamówieniem na koncie X. Musisz użyć access tokenu wygenerowanego dla konta Y żeby pomyślnie wygenerować przesyłkę.

**Comment by bob0swager** [comment]
@AureliuszBrussy jestem przekonany, że zamówienie jest na tym samym koncie sprzedawcy, ale chcę jeszcze raz sprawdzić clientId i secretId, ale ta strona nie działa https://apps.developer.allegro.pl.allegrosandbox.pl/

**Comment by AureliuszBrussy** [comment]
To nie jest kwestia Client ID i Client Secret, ale użytkownika, w imieniu którego aplikacja działa. Informacja ta jest zakodowana w access tokenie. Możesz zdekodować informacje zapisane w access tokenie (online możesz to zrobić np. na stronie https://jwt.io/). Porównaj sobie "user_name" w access tokenie, którego używasz z user id na koncie, na którym jest zamówienie.  

Potwierdzam natomiast problemy z dostępem do Sandboxowej wersji [Moich aplikacji](https://apps.developer.allegro.pl.allegrosandbox.pl/). Pracujemy nad poprawką.

**Comment by bob0swager** [comment]
@AureliuszBrussy  dziękuję, teraz działa, tylko pojawia się błąd:
{
  "id": "2533c4dd-6054-421c-9dd1-e600bc059bd7",
  "parcelId": null,
  "status": "ERROR",
  "errors": [
    {
      "code": "ERROR",
      "message": "Communication error with carrier's API occurred",
      "details": null,
      "path": "/parcel-management/parcel-create-commands/{commandId}",
      "userMessage": "Wystąpił błąd komunikacji z API przewoźnika"
    }
  ]
}
Wybrano "serviceId":9654544, nie może to być związane z problemami na Sandbox?

**Comment by marekbarczyk123** [comment]
Jak tylko uda się rozwiążać błąd zgłaszany przz @bob0swager , prośba o info. :)

**Comment by MaciejFrackowiak** [comment]
@marekbarczyk123 Oczywiście wrócimy z odpowiedzią.

**Comment by marekbarczyk123** [comment]
Udało się może coś ustalić?

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Użyte dane dostępowe nie mają powiązanej metody nadania kurierem. W tej sytuacji, w managerze paczek należy uzupełnić konfigurację.

**Comment by marekbarczyk123** [comment]
Chodzi to to miejsce?
https://allegro.pl.allegrosandbox.pl/moje-allegro/sprzedaz/ustawienia-dostawy

**Comment by Lukasz-Zurek** [comment]
Nie, chodzi tutaj o konfigurację na stronie przewoźnika.

**Comment by marekbarczyk123** [comment]
To teraz mamy taki problem, że API odbija nam z powodu błędnego numeru telefonu i błędnego Access Point ID.

GUID shipmentu: 07167b8d-88fe-4c1d-8620-9fad4dc13dc1
GUID zamówienia w Allegro: 5a64a160-5537-11ed-bca5-d17a6174b958

Fragment requesta, do którego odnosi się błąd:
	"receiver": {
		"address": {
			"city": "Gdansk",
			"countryCode": "PL",
			"postCode": "80-180",
			"street": "Pilkarska 6"
		},
		"company": "Marek Barczyk",
		"email": "p85s8nyr94+6f715e64@user.allegrogroup.pl",
		"name": "Maciek Nowak",
		"phone": "+48123456789",
		"pointId": "BOK02M"
	},
	"serviceId": 9654543,
	"type": "PACKAGE"

Response:

{
	"id": "07167b8d-88fe-4c1d-8620-9fad4dc13dc1",
	"parcelId": null,
	"status": "ERROR",
	"errors": [
		{
			"code": "ERROR",
			"message": "Receiver phone number is incorrect",
			"details": null,
			"path": "receiver.phone",
			"userMessage": "Numer telefonu komórkowego odbiorcy jest nieprawidłowy"
		},
		{
			"code": "ERROR",
			"message": "Receiver point is incorrect",
			"details": null,
			"path": "receiver.pointId",
			"userMessage": "Punkt odbiorcy jest niepoprawny"
		}
	]
}

**Comment by Lukasz-Zurek** [comment]
W requeście przekazujesz numer telefonu stacjonarnego - tak przynajmniej jest on odczytywany. Wprowadź proszę numer bez _+48_ na początku i w takiej formie, aby był to numer telefonu komórkowego.

Ponadto podany przez Ciebie punkt odbiorcy najprawdopodobniej nie istnieje. Lista punktów na sandboxie jest ograniczona. Spróbuj skorzystać z _KIE100_.

**Comment by marekbarczyk123** [comment]
Wysłałem requesta z tym paczkomatem i numerem telefonu bez +48, i dostałem teraz taki błąd:

{"id":"00264eee-efae-4621-845c-153010623a34","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

Zaznaczam, że na zakupie z konta testowego mam inny ID access pointa i numer telefonu.
Tego paczkomatu KIE100 nie ma na mapie inpostu przy wyborze miejsca dostawy.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Dzięki! Przekazałem ten temat dalej do weryfikacji.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Inpost zwraca informację o zaległościach na koncie (stąd wskazany błąd). Zachęcam zatem do bezpośredniego kontaktu z firmą Inpost w celu wyjaśnienia sytuacji.

**Comment by marekbarczyk123** [comment]
Rozumiem, że chodzi o zaległości na koncie InPost na środowisku sandboxowym?

**Comment by marekbarczyk123** [comment]
Tak, o to chodziło.
"Doładowałem" na sandboxowym managerze konto i teraz mamy taki błąd:
Path: /parcel-management/parcel-create-commands/{commandId} Message: Communication error with carrier's API occurred

UUID 46cafa70-27ec-40ff-b44a-b4102786994d

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Weryfikujemy ten przypadek.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Powyższy przypadek najprawdopodobniej spowodowany był przez błąd komunikacji z API Inpost.

Jeśli sytuacja będzie się powtarzać - podeślij proszę nowe przykłady.

**Comment by marekbarczyk123** [comment]
Dziś znowu mam ten błąd. 

Path: /parcel-management/parcel-create-commands/{commandId} Message: Communication error with carrier's API occurred

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Podaj proszę commandId, lub trace-id.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Dziękuję. Przekazałem dalej do weryfikacji.

**Comment by marekbarczyk123** [comment]
Sprwadziłem to jeszcze pod kątem metody wysyłki i problem jest właśnie znią. 
Mają Państwo może dokładną treść błędu dla tego komunikatu?

**Comment by marekbarczyk123** [comment]
Jesteście Państwo w stanie podać mi service id dla metody wysyłki INPOST_KURIER? U nas leci 9654544.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Nasz Serwis otrzymał odpowiedź: _trucker_ID_is_not_set_for_organization_ - a to wskazuje na problemy po stronie umowy z InPost.

Jeśli chodzi o Twój kolejny post - jaką metodę dostawy wybrał Klient?

**Comment by marekbarczyk123** [comment]
Zamówienie z mailem p85s8nyr94+5da3a7678@user.allegrogroup.pl.

Allegro One Kurier - dostawa jutro (do 20.09.2022)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Dziękuję. Wkrótce wrócę do Ciebie z informacją.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Pracujemy obecnie nad poprawką. Wskazana metoda dostawy to Allegro One Kurier - dostawa jutro (X_PRESS) - 01d3468e-42af-474d-b06c-9a2f986f2ec3. Nie powinna być ona dostępna, podobnie jak Allegro One Kurier - dostawa dzisiaj (do 20.09.2022) - 0ffc08e7-9ef9-4189-adcc-ec6d99f27f02. Zaktualizujemy to w najbliższym czasie. Poinformuję o tym w wątku.

**Comment by marekbarczyk123** [comment]
Dzień dobry, czy coś może udało się ustalić? 
Ciężko mi przygotowywać scenariusze testowe w obecnej sytuacji bo tak naprawdę nie wiem, jakie metody i AP są dostępne w danej lokalziacji w API. :)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Wiem, w pełni Cię rozumiem, niestety musimy jeszcze poczekać. Jak tylko decyzja o usunięciu zostanie podjęta - dam znać w wątku.

**Comment by marekbarczyk123** [comment]
Podbijam posta, żeby bot go nie zamknął. :)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Dzięki za cierpliwość. Jak tylko uzyskam jakiekolwiek aktualności w tym temacie - niezależnie od statusu wątku - wrócę tutaj z informacją.

**Comment by marekbarczyk123** [comment]
Jak rozumiem, ciągle czekamy? :)

**Comment by marekbarczyk123** [comment]
Dzień dobry, rozumiem że ciągle czekamy?

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Tak, mogę jednak zapewnić, że planujemy usunąć wspomniane metody w najbliższym czasie - jeśli wszystko pójdzie po myśli - jeszcze w tym roku :)

**Comment by marekbarczyk123** [comment]
Witam serdecznie, czy moze udalo sie poprawic sandboxa? :)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Niestety wspomniana zmiana została przesunięta i wdrożenie planowane jest już w nowym roku.

Przepraszam Cię za długi czas oczekiwania i jednocześnie bardzo dziękuję za Twoją cierpliwość :)

**Comment by marekbarczyk123** [comment]
A mamy jakąś przybliżoną datę wdrożenia?

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Nie mamy ustalonej, czy też przybliżonej daty. Planujemy jednak poinformować o tej zmianie w naszych [aktualnościach](https://developer.allegro.pl/news), w dniu wdrożenia.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Usunęliśmy dzisiaj wspomniane wcześniej metody dostawy - zgodnie z [newsem](https://github.com/allegro/allegro-api/issues/6558). Ponadto metody te nie powinny być już widoczne/dostępne w formularzu dostawy i zapłaty z poziomu Kupującego.

**Comment by marekbarczyk123** [comment]
Czy API działa?

Dostaję ciągle taki błąd:
Processing error

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Doprecyzuj problem i prześlij proszę trace-id.

**Comment by marekbarczyk123** [comment]
Jasne. :) 


Request paczki poniżej. Numer telefonu teraz zmieniłem na ***, w requescie leci pełny:
{
    "items": [
        {
            "dimensions": {
                "depth": {
                    "unit": "CENTIMETER",
                    "value": 2
                },
                "height": {
                    "unit": "CENTIMETER",
                    "value": 3
                },
                "width": {
                    "unit": "CENTIMETER",
                    "value": 1
                }
            },
            "type": "PACKAGE",
            "weight": {
                "unit": "KILOGRAM",
                "value": 0.8
            }
        }
    ],
    "label": {
        "fileFormat": "PDF",
        "referenceNumber": "112858509",
        "sender": {
            "address": {
                "city": "Katowice",
                "countryCode": "PL",
                "postCode": "40-600",
                "street": "Kosciuszki 227"
            },
            "company": "Senetic S.A.",
            "email": "info@senetic.pl",
            "name": "Senetic S.A.",
            "phone": "+48324209200"
        }
    },
    "pickup": {
        "address": {
            "city": "Katowice",
            "countryCode": "PL",
            "postCode": "40-600",
            "street": "Kosciuszki 227"
        },
        "company": "Senetic S.A.",
        "email": "info@senetic.pl",
        "name": "Senetic S.A.",
        "phone": "+48324209200"
    },
    "receiver": {
        "address": {
            "city": "Katowice",
            "countryCode": "PL",
            "postCode": "40-615",
            "street": "Jankego 15D"
        },
        "company": "Marek Barczyk",
        "email": "p85s8nyr94+7c498b2d3@user.allegrogroup.pl",
        "name": "Marek Barczyk",
        "phone": "516***275",
        "pointId": "KAT17A"
    },
    "serviceId": 9654543,
    "type": "PACKAGE"
}

Response:

{
    "errors": [
        {
            "code": "ERROR",
            "details": null,
            "message": "Processing error",
            "path": null,
            "userMessage": "Problem z nadaniem przesy\u0142ki. Skontaktuj si\u0119 z nami. Pomo\u017cemy jak najszybciej."
        }
    ],
    "id": "a99e8aad-af05-47cf-a050-a60a5c59458a",
    "parcelId": null,
    "status": "ERROR"
}

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Upewnij się proszę czy nie masz zaległości na koncie u przewoźnika Inpost.

**Comment by marekbarczyk123** [comment]
Doładowałem na sandboxie inpostu konto.

![image](https://user-images.githubusercontent.com/116170823/214056839-6711e9af-a95f-4a2b-8964-2467e8499e13.png)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 W takim razie przekazuję ten problem dalej do weryfikacji. Wkrótce wrócę z informacją.

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Występowały tymczasowe problemy po stronie Inpost. Sytuacja wróciła już jednak do normy.

**Comment by marekbarczyk123** [comment]
Niestety dziś znowu mam błąd. Request ten sam.

Path: /parcel-management/parcel-create-commands/{commandId} Message: Communication error with carrier's API occurred

**Comment by Lukasz-Zurek** [comment]
Podaj proszę nowe commandId.

**Comment by marekbarczyk123** [comment]
{
    "errors": [
        {
            "code": "ERROR",
            "details": null,
            "message": "Communication error with carrier's API occurred",
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage": "Wyst\u0105pi\u0142 b\u0142\u0105d komunikacji z API przewo\u017anika"
        }
    ],
    "id": "ec5f43d9-8e19-4eaf-8021-16a6fc7c6c12",
    "parcelId": null,
    "status": "ERROR"
}

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Dziękuję. Zgłosiłem to dalej do weryfikacji.

**Comment by marekbarczyk123** [comment]
:)

**Comment by Lukasz-Zurek** [comment]
@marekbarczyk123 Nasz operator miał problemy techniczne. Tego typu sytuacje niestety mogą się powtarzać. W przypadku środowiska testowego należy podejmować kolejne próby.

Dodam, że operator planuje zoptymalizować to po swojej stronie, tak, aby tego typu problemy już nie występowały.

**Comment by marekbarczyk123** [comment]
Czy dalej występują problemy? Próbowałem wygenerować teraz etykietę i dostałem taki błąd:

{"id":"ad046f4a-f15e-4e7f-9359-22411109dc18","parcelId":null,"status":"ERROR","errors":[{"code":"ERROR","message":"Processing error","details":null,"path":null,"userMessage":"Problem z nadaniem przesyłki. Skontaktuj się z nami. Pomożemy jak najszybciej."}]}

**Comment by AureliuszBrussy** [comment]
@marekbarczyk123 tak, tutaj także mamy do czynienia z błędami API przewoźnika.
