### ISSUE TITLE
Brak adresu email użytkownika przy pobieraniu zamówień

### ISSUE THREAD

**Issue by janex-PL** [allegro/allegro-api#6245]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

W zamówieniach od klientów pojawiły się dwa zamówienia, które nie zawierały wypełnionego pola email w sekcji buyer. 

Jeśli dobrze rozumiem, to te adresy email są generowane przez Allegro na podstawie kodu nadawcy i identyfikatora zamówienia. 

Identyfikatory zamówień: 

- `43cce5e3-4f90-11ed-9ac4-a30312cf1006`
- `9b4b89d1-4f8f-11ed-8a18-e1d46b4c362a`

**Comment by AureliuszBrussy** [comment]
Sprawdziłem te zamówienia i widzę, że zwracamy dla nich wartość w polu **buyer.email**. Spróbuj pobrać zamówienia ponownie.

**Comment by janex-PL** [comment]
Sprawdziłem i faktycznie, teraz maile się pojawiły 😑 

Musiało one zostać wypełnione przed momentem, ponieważ wcześniej te pola były puste, co powodowało problemy później po naszej stronie...

**Comment by AureliuszBrussy** [comment]
@janex-PL mieliśmy chwilowe problemy techniczne, które mogły wpłynąć na widoczność pola. Przepraszam za niedogodność.
