### ISSUE TITLE
Popsute zamówienie, dziwne dane i zachowanie na portalu

### ISSUE THREAD

**Issue by hahyes** [allegro/allegro-api#6247]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Przepraszam, jeżeli zgłaszam w złym miejscu ale może możecie to przekazać do odpowiedniego działu, bo coś się złego dzieje z jednym zamówieniem i jego dane są w jakiś sposób popsute.
Mam zamówienie o UUID: `a603a342-4f8e-11ed-87e8-7bf3cee6336c` oraz identyfikatorze płatności: `57328727-4f8f-11ed-a39b-6b878ad758ef`.
Jest ono opłacone i ma wypełnione dane do dostawy. Wydaje się, że powinno ono mieć status `READY_FOR_PROCESSING` ale ma status `FILLED_IN`. Chcąc podejrzeć informacje na portalu i wchodząc na podstronę ze szczegółami, ona zaczyna sypać błędami 404 dla zasobu zamówienia `/packages` i restartuje ładowanie danych zamówienia na stronie. Prowadzi to do niekończącej się pętli, oczywiście do czasu wyskoczenia captcha.
Proszę o reakcję, ponieważ zamówienie wisi i nie można go obsłużyć poprzez naszą integrację i zewnętrzne oprogramowanie.

**Comment by MartaNowaczyk** [comment]
Rzeczywiście status jest niepoprawny. Zgłosiłam to do zespołu, który odpowiada za zamówienia. Dam znać jak uda nam się to poprawić.

**Comment by hahyes** [comment]
> Rzeczywiście status jest niepoprawny. Zgłosiłam to do zespołu, który odpowiada za zamówienia. Dam znać jak uda nam się to poprawić.

Widzę, że już zamówienie ma poprawny status. Dziękuję za pomoc. (y)
