### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by arslansahin** [allegro/allegro-api#6248]
Hello, I encountered an error similar to the one in this link (https://github.com/allegro/allegro-api/issues/6017). Account type is company, necessary downloads for activation have been made.
client:107613817
Can you check ?

**Comment by MartaNowaczyk** [comment]
I don't have such a sandbox account. Did you activate this account via the link form the e-mail?

**Comment by arslansahin** [comment]
Account created with this e-mail address. 
arsann@gmail.com

**Comment by arslansahin** [comment]
yes i passed the checkout step and uploaded the documents. Do the documents I upload have to be real documents? The warning said do not enter real personal data.

**Comment by PrzemyslawLukanowski** [comment]
Hi, I've just activated your account. Everything should work properly now.

**Comment by arslansahin** [comment]
Hello, yes it is working now, no problem, thank you.
