### ISSUE TITLE
problme z metoda offer-publication-commands

### ISSUE THREAD

**Issue by djmiq** [allegro/allegro-api#6249]
Występuje problem: 
 - [ x] z zasobem REST API / with a REST API resource
 - [ x] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

wysyłam PUT na:

https://api.allegro.pl/sale/offer-publication-commands/3e8fccdd-e900-430f-b6ac-5359f6a99dde?Accept=application/vnd.allegro.public.v1+json

body jak ponizej:
{
    "offerCriteria": [
        {
            "offers": [
                {
                    "id": "12721509704"
                }
            ],
            "type": "CONTAINS_OFFERS"
        }
    ],
    "publication": {
        "action": "END"
    }
}

uzyskuje od wczoraj taki komunikat, dotyczy różnych ofert nie tylko tej z przykładu,
na drugim koncie identyczna logika działa poprawnie
{
    "errors": [
        {
            "code": "INTERNAL_SERVER_ERROR",
            "message": "Internal server error.",
            "details": null,
            "path": null,
            "userMessage": "Internal server error. Please try again in a few minutes."
        }
    ]
}

**Comment by PrzemyslawLukanowski** [comment]
Twoje wywołania odbywają się w ramach tokena, który nie posiada zakodowanej informacji o użytkowniku. Oznacza to, że najprawdopodobniej token wygenerowałeś w drodze autoryzacji [client_credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow) zamiast [code](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#authorization-code-flow) lub [device](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#device-flow).

**Comment by djmiq** [comment]
chyba zmiana nazwy konta zlikwidowała przy okazji device tak mi sie wydaje
generalnie wskazówka przydatna i udało się rozwiązać temat

**Comment by djmiq** [comment]
:)
