### ISSUE TITLE
Oznaczenie ofert jako zestawy produktów

### ISSUE THREAD

**Issue by KJtTGHAK** [allegro/allegro-api#6250]
Dostałem dzisiaj maila że część moich produktów została oznaczona jako zestawy produktów. W jaki sposób poprzez API mogę sam to zrobić ?
Przykład oferty z zestawem 4 sztuk: https://allegro.pl/oferta/305-70r19-5-bieznikowana-wzor-michelin-xde2-4-szt-12328325694

**Comment by Lukasz-Zurek** [comment]
Zestawy produktów możesz utworzyć korzystając z [POST /sale/product-offers](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA), przekazując:

- **productSet.product.id** - identyfikator lub GTIN produktu z naszego Katalogu,
- **productSet.quantity.value** - liczba sztuk wskazanego produktu, która wejdzie w skład zestawu.

Cały proces opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-utworzyc-zestaw-produktowy).

**Comment by KJtTGHAK** [comment]
A jak dodać zestaw produktów do już istniejącej oferty, jak ją edytować, aby dodać te parametry ?

**Comment by Lukasz-Zurek** [comment]
W tym celu skorzystaj z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) i w strukturze przekaż kolejne produkty, które mają wchodzić w skład zestawu. 

Przykładowo masz wystawioną ofertę z produktem "a". Podczas próby edycji dodajesz kolejny produkt "b" (maksymalnie możesz dodać do 10 produktów):

```
{
     "name": "Zestaw Xiaomi",
     "productSet": [
        {
         "product": {"id": "05dda462-c99b-4e73-972d-cdee225fe9b1"}, - produkt "a" (produkt główny)
        "quantity": {"value": 1}
        },
        {
        "product": {"id": "640d39d1-d2c3-4524-8e2e-b49c9dbcd32c"}, - produkt "b" (dodając go 
                                                                   podczas edycji, tworzysz zestaw)
          "quantity": {"value": 3}
        },
        {
         "product": {"id": "1f7b1568-0cc7-47a9-9956-f52787f047c9"}, - produkt "c"
        "quantity": {"value": 1}
        },
     ],
     "sellingMode": {
       "price": {
          "amount": "667.00", - w tej sytuacji jest to cena za cały zestaw
          "currency": "PLN"
        }
      },
     "stock": {
       "available": 2 - liczba zestawów
     }
  }
```

Pamiętaj, że parametry określają tylko cechy produktu głównego. To oznacza, że domyślnie nie wyświetlimy parametrów dla produktów dodatkowych z zestawu. Jeśli zatem wyedytujesz swoją ofertę, dodając kolejne produkty - tworząc w ten sposób zestaw - zwrócimy Tobie parametry produktu głównego i takie będą widoczne w ofercie.

**Comment by KJtTGHAK** [comment]
Dziękuję działa

**Comment by KJtTGHAK** [comment]
Jest jednak problem z taką edycją, tak jak pisaliście odnośnie parametrów. Nie mogę dodać nowych parametrów.
Edytując ogłoszenie w ten sposób usuwane są wszystkie parametry oprócz zapisanych dla propose product.


Za pomocą PATCH /sale/product-offers/{offerId} nie mogę ich dodać
dostaję error:
'{"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"parameters","userMessage":"The definitions of the parameter `224017:Kod producenta` were incorrectly specified as a parameter in section `offer`."}]}'

Podobnie jest dla: 
`237206:Model`
 `1:Rok produkcji`
`24209:Oś`
itp

**Comment by Lukasz-Zurek** [comment]
Zgodnie z komunikatem błędu - parametry produktowe, które mają **"describesProduct": true** (a te wymienione powyżej takie są) powinny być umieszczone w sekcji **productSet** w polu **product.parameters**, a nie jak obecnie - w **parameters** (to pole odpowiedzialne jest za parametry ofertowe, które szerzej opisaliśmy [tutaj](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#parametry-ofertowe)).

Co do zasady - korzystając z [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) - w strukturze przekazuj tylko te pola, które chcesz edytować.

**Comment by KJtTGHAK** [comment]
Dziękuję.
