### ISSUE TITLE
Zasób product-parameters nie zwraca który parametr jest "inny"

### ISSUE THREAD

**Issue by szymoki** [allegro/allegro-api#6251]
Zasób /sale/categories/{categoryId}/product-parameters nie zwraca wartości ambigousId, który parametr słownikowy jest oznaczony jako "inny".

**Comment by Lukasz-Zurek** [comment]
Tak, zgadza się. Zgodnie z dokumentacją nie zwracamy takiego pola w odpowiedzi podczas korzystania ze wskazanego zasobu. Informacje te zwracamy w odpowiedzi wtedy, gdy skorzystasz z [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).

**Comment by szymoki** [comment]
Dobra, a pytanie czy nie powinno też tu być zwracane? :) Przy dodawaniu propozycji przez API w wybieraniu wartości słownikowej "inna" nie ma tego jak zweryfikować czy w tym parametrze powinna być podana odrębna wartość tesktowa. Ewentualnie pobrać drugi zasób /parameters i wyszukać ten sam parametr, ale to chyba nie o to chodzi.

**Comment by Lukasz-Zurek** [comment]
Przyznam, że zasób ten nie był w ostatnim czasie rozwijany. Twoja propozycja ma rację bytu. Zachęcam Cię do przekazania jej w dedykowanej części [Discussions](https://github.com/allegro/allegro-api/discussions), tak aby również inni użytkownicy forum mogli oddać na nią swój głos.
