### ISSUE TITLE
Problem z przypisaniem innej wartości parametru niż w katalogu produktów

### ISSUE THREAD

**Issue by WGRINGO** [allegro/allegro-api#6254]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment

Witam,
Klient ma problem ze zmianą wartości mocy kotła, który jest powiązany z produktem. W katalogu produktów moc jest ustawiona na sztywno 20kW, kiedy klient ma pewność, że ten produkt występuje również w wersji z mocą 25 kW i taki chce wystawić.
Spróbowałem więc na sandboxie wywołać analogiczną sytuację i potwierdza się to co mówi klient.
Treść szkicu aukcji udało się przepchać (draft się zapisał):
`{
  "id": "7695923832",
  "name": "KOCIOŁ BERETTA CIAO GREEN 25 R.S.I. KOND",
  "category": {
    "id": "111869"
  },
  "product": {
    "id": "acaa3401-0978-4c25-8a29-8ec2ee3b753a"
  },
  "parameters": [
    {
      "id": "11323",
      "valuesIds": [
        "11323_1"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "248811",
      "valuesIds": [
        "248811_950036"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "129861",
      "valuesIds": [
        "129861_2"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "219137",
      "valuesIds": [],
      "values": [
        "25"
      ],
      "rangeValue": null
    },
    {
      "id": "129862",
      "valuesIds": [
        "129862_512"
      ],
      "values": [],
      "rangeValue": null
    },
    {
      "id": "224017",
      "valuesIds": [],
      "values": [
        "20095432"
      ],
      "rangeValue": null
    }
  ],
  "customParameters": null,
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "IMAGE",
            "url": "https://a.allegroimg.allegrosandbox.pl/original/11aba8/d57484a54b6ea998b5331c483ae5"
          },
          {
            "type": "TEXT",
            "content": "<p>KOCIOŁ BERETTA CIAO GREEN 25 R.S.I. KONDENSACYJNY JEDNOFUNKCYJNY</p><p>20095432</p><p>PHI BERETTA</p>"
          }
        ]
      }
    ]
  },
  "compatibilityList": null,
  "tecdocSpecification": null,
  "images": [
    {
      "url": "https://a.allegroimg.allegrosandbox.pl/original/11aba8/d57484a54b6ea998b5331c483ae5"
    }
  ],
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "1234",
      "currency": "PLN"
    },
    "startingPrice": null,
    "minimalPrice": null,
    "netPrice": null
  },
  "tax": null,
  "stock": {
    "available": 1,
    "unit": "UNIT"
  },
  "publication": {
    "duration": null,
    "status": "INACTIVE",
    "startingAt": null,
    "endingAt": null,
    "endedBy": null,
    "republish": false
  },
  "delivery": {
    "shippingRates": {
      "id": "fe2a27a1-71c3-4b3b-b40d-c25a4cbe576c"
    },
    "handlingTime": "PT24H",
    "additionalInfo": null,
    "shipmentDate": null
  },
  "payments": {
    "invoice": "VAT"
  },
  "discounts": null,
  "afterSalesServices": {
    "impliedWarranty": {
      "id": "6fed31d8-4ff1-4f14-a272-a85e1016db8c"
    },
    "returnPolicy": {
      "id": "3c43c24c-696e-40b0-bbe8-8d530679cf8a"
    },
    "warranty": {
      "id": "98c46e30-f1a5-4979-b5ac-90b2e475993f"
    }
  },
  "additionalServices": null,
  "sizeTable": null,
  "fundraisingCampaign": null,
  "promotion": {
    "emphasized": false,
    "bold": false,
    "highlight": false,
    "departmentPage": false,
    "emphasizedHighlightBoldPackage": false
  },
  "location": {
    "countryCode": "PL",
    "province": "WARMINSKO_MAZURSKIE",
    "city": "IŁAWA",
    "postCode": "14-200"
  },
  "external": {
    "id": "08B/CIAOGREEN25RSI"
  },
  "attachments": [],
  "contact": null,
  "validation": {
    "errors": [],
    "warnings": [],
    "validatedAt": "2022-10-21T09:40:50.462Z"
  },
  "b2b": {
    "buyableOnlyByBusiness": false
  },
  "messageToSellerSettings": null,
  "createdAt": "2022-10-21T09:40:16.000Z",
  "updatedAt": "2022-10-21T09:40:50.463Z",
  "language": "pl-PL"
}`

Natomiast przy aktywacji aukcji dostaję taki błąd:

`{
  "tasks": [
    {
      "offer": {
        "id": "7695923832"
      },
      "message": "Could not change offer publication status. Niepoprawna wartość parametru Moc (219137) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: \"20\".",
      "status": "FAIL",
      "scheduledAt": "2022-10-21T09:54:19.864Z",
      "finishedAt": "2022-10-21T09:54:19.845Z",
      "field": "publication",
      "errors": [
        {
          "code": "ProductConstraintViolationException.DataIntegrity",
          "message": "Incorrect value of the Moc (219137) parameter for the offered product. The correct parameter value for the product is: \"20\".",
          "details": null,
          "path": null,
          "userMessage": "Niepoprawna wartość parametru Moc (219137) dla produktu w ofercie. Prawidłowa wartość parametru dla produktu to: \"20\"."
        }
      ]
    }
  ]
}`

Ponadto wystawiając ten sam produkt za pomocą przeglądarki używając Waszej strony i formularza nie ma z tym problemu i da się wystawić kocioł powiązany z produktem o mocy 25 kW gdy w katalogu jest 20 kW.

Jak można rozwiązać ten problem skoro przez przeglądarkę się, a przez Api nie?

**Comment by AureliuszBrussy** [comment]
Parametr "Moc" (219137) w tej kategorii to parametr identyfikujący ten produkt. Oznacza to, że nie można go zmienić, także w naszym formularzu. Po wybraniu tego produktu - parametr ten nie wyświetla się pośród parametrów możliwych do edycji. 

W tym przypadku są dwie możliwości: albo w parametrach produktu jest błąd, co można zgłosić zarówno w formularzu (opcja "Zgłoś błąd w produkcie") jak i poprzez API: cały proces opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA#jak-zglosic-blad-w-produkcie).

Drugą możliwością jest utworzenie nowego produktu wraz z ofertą, z inną wartością, bo jest to po prostu inny produkt. Gdy skorzystasz z [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) i nie przekażesz id konkretnego produktu - utworzymy nowy produkt, jeżeli oczywiście nie wykryjemy duplikatu o tych samych parametrach.
Możesz też wysłać propozycję nowego produktu za pomocą [POST /sale/product-proposals](https://developer.allegro.pl/documentation/#operation/proposeSaleProduct). 
Obydwie możliwości opisujemy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-jednym-requestem-wystawic-oferte-powiazana-z-produktem-D7Kj9gw4xFA).
