### ISSUE TITLE
Error: Downloading image from UR, Code 500 Internal server error

### ISSUE THREAD

**Issue by sinteit** [allegro/allegro-api#6255]
Konto z loginem hartmann_work, testy na sandboxie 

Podczas wysyłania oferty mamy problem z obrazkami. Api zwraca komunikat:
Błąd: 422 {"errors":[{"code":"DownloadError.InternalServerError","message":"Downloading image from URL 'https://www.hartmann24.pl/resources/pimg_d/524_image1_pho94_29_omnisilk_1.jpg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'.","details":null,"path":"productSet[0].product.images","userMessage":"Downloading image from URL 'https://www.hartmann24.pl/resources/pimg_d/524_image1_pho94_29_omnisilk_1.jpg' failed. Server returned the following HTTP status code: 500 INTERNAL_SERVER_ERROR and response body: 'Internal server error'."}]}

URLe z tego serwera są dostępne online bez autoryzacji. Robiliśmy też na tym serwerze file scraping i też działa, bez problemu pobraliśmy wszystkie obrazki z folderu. 
Pytanie zatem dlaczego poprzez API mamy code 500?

**Comment by AureliuszBrussy** [comment]
Nasz request do tego serwera kończy się odpowiedzią z błędem 500 - powód tej sytuacji jest raczej do ustalenia po stronie właśnie tego serwera.
