### ISSUE TITLE
offer change quantity

### ISSUE THREAD

**Issue by seraslanx** [allegro/allegro-api#6260]
Hello,

I  use this endpoint "sale/offer-quantity-change-commands" for change offer stock to 1.But when I call the it first ,it gives me :
[total] => 0
            [success] => 0
            [failed] => 0

And then I call it again without changing request ,it gives me:
        [total] => 1
            [success] => 1
            [failed] => 0

sometimes it gives  [success] => 1  at the third calling.
why can't I change stock it at first calling?

The request is :
{
"modification": {
"changeType": "GAIN",
"value": -98
},
"offerCriteria": [
{
"offers": [
{
"id": "123456789"
}
],
"type": "CONTAINS_OFFERS"
}
]
}

**Comment by Lukasz-Zurek** [comment]
This resource works asynchronously, so you will get all zeros in response (well, most of the time). I suggest you to check statuses of bulk quantity editing operation via [GET /sale/offer-quantity-change-commands/{commandId}/tasks](https://developer.allegro.pl/documentation/#operation/getQuantityModificationCommandTasksStatusesUsingGET) where you will get more details.

**Comment by seraslanx** [comment]
thanks for reply
