### ISSUE TITLE
batch offer change stock

### ISSUE THREAD

**Issue by seraslanx** [allegro/allegro-api#6261]
Hello,

I want to change my offers stocks in bulk.When I use "sale/offer-quantity-change-commands" endpoint, I cant write different modification values for offers.My offers's stocks are different from eachother and they decrease/encrease with different quantities.So  the endpoint "sale/offer-quantity-change-commands" is not what I am looking for.

Also I can change offer stock via this endpoint "sale/product-offers",but considering that there are 30000 offers it's not useful to change stock one by one.

Which endpoint can I call for change stock in bulk?

**Comment by Lukasz-Zurek** [comment]
If you want to change the stock in your offers, you will not be able to provide different values for any specific offers in one request. You can only use sale/offer-quantity-change-commands - which you have already mentioned - providing one value for all of the offers. There is no other possibility.

**Comment by seraslanx** [comment]
thanks for reply
