### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by mrmarcin12** [allegro/allegro-api#6262]
Kiedy próbuje wyszukiwać produkty na całym allegro przez Wasze api poprzez /offers/listing otrzymuje komunikat "Access denied. Access available only for verified applications.". Podobny problem ma kiedy próbuje wywołać "sale/offers" mimo że aktywowałem wszystko a autoryzacja i pobieranie kategorii działa poprawnie. Zapytanie zwraca error 403.

**Comment by Lukasz-Zurek** [comment]
Zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) dostępny jest tylko dla zweryfikowanych aplikacji. Więcej informacji na ten temat znajdziesz [tutaj](https://developer.allegro.pl/news/get-offers-listing-tylko-dla-zweryfikowanych-aplikacji-GRax4oVgrs1). 

Aby przejść proces weryfikacji skontaktuj się z nami przez [formularz](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).
