### ISSUE TITLE
Praca dyplomowa - testy penetracyjne platformy allegro sandbox

### ISSUE THREAD

**Issue by ErykM** [allegro/allegro-api#6263]
Dzień dobry,
W ramach pisania pracy dyplomowej, chciałbym przeprowadzić testy penetracyjne platformy allegro(sandboxa przygotowanego na potrzeby programu bug bounty), oraz przygotować raport z przeprowadzonych testów. Raport wykorzystałbym do napisania pracy licencjackiej. Wszystkie znalezione podatności zaraportowałbym również przez program bug bounty na platformie hackerone.com. Proszę o zgodę na zawarcie informacji z testów w mojej pracy dyplomowej oraz o informację o dodatkowych krokach, które powinienem podjąć przed rozpoczęciem prac.

**Comment by Lukasz-Zurek** [comment]
Możesz w pełni korzystać z naszego środowiska testowego. [Tutaj](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe) znajdziesz informacje podstawowe na temat Sandboxa. Pierwsze kroki z Allegro API opisaliśmy w [naszym poradniku](https://developer.allegro.pl/tutorials/jak-zaczac-prace-z-rest-api-4RAvV2bgwtj). Całą konfigurację opisaliśmy "pod Sandboxa".

Zapoznaj się również z [Regulaminem Allegro Sandbox](https://developer.allegro.pl/tutorials/informacje-podstawowe-b21569boAI1#srodowisko-testowe-regulamin).
