### ISSUE TITLE
Label barcode value

### ISSUE THREAD

**Issue by ZajdaBear** [allegro/allegro-api#6265]
Hi,
 I need to know the package number that is sent on shipping label in the barcode. Is there a way to obtian this thru API? I cannot check this on sandbox.

Following is just en example of what I need. Thanks

![image](https://user-images.githubusercontent.com/109143627/197505952-caa728ca-9982-4cdf-a14f-66cc8f071fce.png)

**Comment by Lukasz-Zurek** [comment]
Our API returns only a waybill number. You can receive it via [GET /parcel-management/parcels/{parcelId}](https://developer.allegro.pl/documentation/#operation/getParcelDetails) in the **“items.waybill”** field.
