### ISSUE TITLE
produktyzacja produkt dd9867cc-19ec-4cb8-9eb4-f3205f25fef6

### ISSUE THREAD

**Issue by ArturBakAxl** [allegro/allegro-api#6271]
co jest prawdą:
w produkcie parametr Model id:237206 jest oznaczony jako ofertowy
natomiast w kategorii id:257694 ten parametr jest oznaczony jako produktowy
co jest ważniejsze, czy te parametry w produkcie są aktualizowane o te informacje?

**Comment by PrzemyslawLukanowski** [comment]
Parametr jest produktowy, ponieważ w odpowiedzi `GET /sale/categories/257694/parameters`, w polu `"describesProduct"`, zwracamy wartość `true`. Dzięki temu wiesz, że podczas tworzenia/edycji oferty, należy przekazać go w sekcji `productSet.product.parameters`, a nie poza nią, w `parameters`.
Natomiast w danych produktu, w polu "`options.identifiesProduct"`, widnieje wartość `false` - oznacza to, że nie bierzemy go pod uwagę przy identyfikacji produktu, tzn. nie uwzględniamy go w kontekście wyszukiwania podobnego produktu na podstawie przekazanych parametrów, możesz go także dowolnie edytować.
