### ISSUE TITLE
nie łączy się z wtyczką "Moje aukcje allegro" 

### ISSUE THREAD

**Issue by kuniszko** [allegro/allegro-api#6272]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ x] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

dotyczy wtyczki "Moje aukcje allegro" stworzonej przez https://wphocus.com/; requestu - nie rozwiązuje problemu; login użytkownika: kuniszko; problem występuje zawsze; w załączniku okna - tworzę aplikację, loguję się do niej, zatwierdzam wszystko a nie dochodzi do łączności - tak jakby API było zablokowane na moim koncie; Proszę o pomoc.
![image (1)](https://user-images.githubusercontent.com/116730018/198029119-861056d3-e782-4dab-a93e-95bde77680a6.png)
![image](https://user-images.githubusercontent.com/116730018/198029138-b6d5757c-3740-4b93-ad22-1f4e9eec2440.png)

**Comment by PrzemyslawLukanowski** [comment]
Z danych, które posiadamy, wynika że usunąłeś aplikację qnisz_2 dziś o 12:46. Widzę, że minutę później założyłeś już nową, jednak wg naszych logów, po stronie aplikacji, po tym, gdy klikasz "Tak, powiąż konto", nie dochodzi do próby wygenerowania tokena, nie widzimy żadnych wpisów na  ten temat. Sugeruję skonsultować ten problem bezpośrednio ze wsparciem aplikacji, z której korzystasz, ponieważ my niestety nie wiemy, w jaki sposób ona dokładnie funkcjonuje. Możesz także spróbować skorzystać z innej przeglądarki oraz wyczyścić pliki cookies.

**Comment by kuniszko** [comment]
Sprawdziliśmy, wtyczka działa z innego hostingu. Nie można się połączyć tylko na hostingu lh.pl 
Czy Allegro przypadkiem nie blokuje lh.pl ???
Czy też odwrotnie może to lh.pl blokuje Allegro.pl ???

Napisałem do lh.pl ale może coś Państwo jeszcze odkryjecie w tej sprawie.

**Comment by kuniszko** [comment]
Problem rozwiązany - winny był hosting lh.pl - już jest wszystko ok.
Dziękuję za pomoc.
