### ISSUE TITLE
Problem z listą zamówień /order/checkout-forms

### ISSUE THREAD

**Issue by bond0091** [allegro/allegro-api#6275]
Dzień dobry,
Mam taki problem - napisałem skrypt w PHP pobierający listę zamówień i niby wszystko działa poprawnie, ale zwracana liczba to zawsze zero zamówień.

Adres wywołania (oczywiście autoryzacja access_tokenem jest poprawna):
https://api.allegro.pl/order/checkout-forms?limit=10&offset=0&lineItems.boughtAt.lte=2022-10-01T00%3A00%3A00Z&lineItems.boughtAt.gte=2022-10-26T23%3A59%3A59Z

Taki wynik zawsze otrzymuję:
Array ( [checkoutForms] => Array ( ) [count] => 0 [totalCount] => 0 )

Co może być tego przyczyną?

Poniżej funkcja:

function getOrders($access_token,$data1,$data2)
{
 $ch = curl_init("https://api.allegro.pl/order/checkout-forms?limit=100&offset=1&lineItems.boughtAt.lte=".$data1."&lineItems.boughtAt.gte=".$data2);
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Bearer ".$access_token, "Accept: application/vnd.allegro.public.v1+json"));
    $result = curl_exec($ch);
    return json_decode($result,1);
}

Pozdrawiam
Krzysztof

**Comment by asoio** [comment]
Masz w parametrach, że data ma być mniejsza niż 2022-10-01 (boughtAt.lte) i jednocześnie większa niż 2022-10-26 (boughtAt.gte). Zamień lte z gte i powinno działać.

**Comment by MaciejFrackowiak** [comment]
Zgodnie ze wskazówką @asoio - lineItems.boughtAt.lte to górna granica przedziału dat, a lineItems.boughtAt.gte to dolna granica przedziału - u Ciebie te paramtery występują na odwrót.

**Comment by bond0091** [comment]
Zmieniłem na:
https://api.allegro.pl/order/checkout-forms?limit=10&offset=0&lineItems.boughtAt.lte=2022-10-27T23%3A59%3A59Z&lineItems.boughtAt.gte=2022-07-01T00%3A00%3A00Z

To też nie działa:
https://api.allegro.pl/order/checkout-forms?limit=10&offset=0&lineItems.boughtAt.gte=2022-07-01T00%3A00%3A00Z&lineItems.boughtAt.lte=2022-10-27T23%3A59%3A59Z

Co robię nie tak?

**Comment by MaciejFrackowiak** [comment]
Proszę podaj trace-id swojego wywołania, wówczas będziemy mogli odtworzyć Twój request.

**Comment by bond0091** [comment]
Dzień dobry,  Bedę bardzo wdzięczny za pomoc w rozwiązaniu problemu.   Moje ostatnie wywołanie:  api.allegro.pl https://api.allegro.pl/order/checkout-forms?limit=10&amp;offset=0&amp;lineItems.boughtAt.gte=2022-08-01T00%3A00%3A00Z&amp;lineItems.boughtAt.lte=2022-10-28T23%3A59%3A59Z   Poniżej parametry jakie posiadam:   client_id: cf5284ef3c064ea9b380df17ff77edb3   client_secret: RQ15EOq8scD2dsla2A9420aiXlga258RWw0xWseZiMDqz0JZRJFI8YGkYrMw6KfO   access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjY5NDA4NjEsInVzZXJfbmFtZSI6IjExMDk5MjAiLCJqdGkiOiJjY2I0Yjk4MC1kYjE0LTQwZTMtYjI0Yy0xMjhhOGI4Zjg0MDkiLCJjbGllbnRfaWQiOiJjZjUyODRlZjN   refresh_token:  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiIxMTA5OTIwIiwic2NvcGUiOlsiYWxsZWdybzphcGk6b3JkZXJzOnJlYWQiLCJhbGxlZ3JvOmFwaTpwYXltZW50czp3cml0ZSIsImFsbGVncm86YXBpOnByb2ZpbGU   Pozdrawiam  Krzysztof Książek  tel. 607 345 350   
            
          
     
      
       
        Dnia 28 października 2022 06:10 MaciejFrackowiak ***@***.***&gt; napisał(a):
       
    
       
         
 Proszę podaj trace-id swojego wywołania, wówczas będziemy mogli odtworzyć Twój request.

**Comment by MaciejFrackowiak** [comment]
Czy przypadkiem nie wywołujesz zasobu korzystając z tokena konta, na którym nie ma żadnych zamówień - sprawdź proszę to dokładnie.

**Comment by bond0091** [comment]
Tak - teraz wszystko chodzi. Klient dla którego wykonywałem zlecenie wprowadził mnie w błąd i nie miał na tym koncie żadnych zamówień. Dziękuję za pomoc, pozdrawiam
