### ISSUE TITLE
Sprzedaję > API Allegro > parcel-management/parcel-create-commands

### ISSUE THREAD

**Issue by barii86** [allegro/allegro-api#6276]
Dzień Dobry, mam pytanie dotyczące API do nadawania przesyłek, czy raz jak wyślę dane do nadawania przesyłem i wystąpił błąd to nie mogę poprawić danych? 

wysyłam: [content] => {"serviceId":"19397777","receiver":{"email":"xxxxxxx@allegromail.pl","name":"Barto","address":{"street":"ul. Adres","postCode":"51-504","city":"Wroc\u0142aw","countryCode":"PL"}},"pickup":{"address":{"street":"ul. Mi\u0142oszycka 11","postCode":"51-502","city":"Wroc\u0142aw","countryCode":"PL"},"name":"Allegro One Box, zielony automat","phone":"123456","pointId":"AL089DW1","email":"xxxxxxx@allegromail.pl"},"label":{"sender":{"address":{"street":"ul. Mydlana 1","postCode":"51-502","city":"Wroc\u0142aw","countryCode":"PL"},"phone":"123456","email":"biuro@xxx"},"fileFormat":"PDF"},"items":[{"value":{"amount":"10","currency":"PLN"},"type":"PACKAGE"}] 

a w odpowiedzi otrzymuję (proszę zobaczyć np. w zapytaniu jest serviceid = 19397777 a w odpowiedzi dostaję 18173961) - jak ponownie wysyłam dane zmienione to system odpowiada mi danymi z pierwszego zapytania. 

Array ( [id] => 794dd460-55ec-11ed-8813-f78e3567a6d6 [input] => Array ( [serviceId] => 18173961 [label] => Array ( [sender] => Array ( [name] => [company] => [address] => Array ( [street] => ul. Mydlana 1 [postCode] => 51-502 [city] => WrocĹaw [county] => [countryCode] => PL ) [email] => biuro@xxx [phone] => 123456 ) [fileFormat] => PDF ) [receiver] => Array ( [name] => Barto [company] => [address] => Array ( [street] => ul. Adres [postCode] => 51-504 [city] => WrocĹaw [county] => [countryCode] => PL ) [pointId] => [email] => xxxxxxx@allegromail.pl [phone] => ) [pickup] => Array ( [name] => Allegro One Box, zielony automat [company] => [address] => Array ( [street] => ul. MiĹoszycka 11 [postCode] => 51-502 [city] => WrocĹaw [county] => [countryCode] => PL ) [pointId] => AL089DW1 [email] => xxxxxxx@allegromail.pl [phone] => 123456 ) [items] => Array ( [0] => Array ( [dimensions] => [weight] => [description] => [value] => Array ( [amount] => 10 [currency] => PLN ) [type] => PACKAGE ) ) [type] => [additionalServices] => ) )

**Comment by MaciejFrackowiak** [comment]
Do każdego wywołania musisz użyć nowego commandId - jeśli użyjesz już wcześniej wykorzystane, to w odpowiedzi otrzymasz dane dla pierwotnego wywołania, a nie dla ostatniego z tym samym commandId.

**Comment by barii86** [comment]
commandId może być dowolne? czy musi być generowane na podstawie jakiegoś klucza?

**Comment by MaciejFrackowiak** [comment]
Jako commandId przekaż numer UUID, który wygenerujesz automatycznie we własnym zakresie.

**Comment by barii86** [comment]
W czym może być problem, jeżeli w odpowiedzi otrzymuję taką odpowiedź?

       [0] => Array
                (
                    [code] => ERROR
                    [message] => Processing error
                    [details] => 
                    [path] => 
                    [userMessage] => Problem z nadaniem przesyĹki. Skontaktuj siÄ z nami. PomoĹźemy jak najszybciej.
                )

Wcześniej były inne błędy, że jakieś wymagane pole nie zostało uzupełnione, ze wszystkim sobie poradziłem, natomiast jak już się wydaje, że wszystko jest uzupełnione prawidłowo to mam błąd jak wyżej.

**Comment by MaciejFrackowiak** [comment]
Proszę podaj commandId operacji lub trace-id, wówczas będę mógł zweryfikować logi.
