### ISSUE TITLE
GET dla parcel-create-commands zwraca Communication error with carrier's API occurred dla poprawnie utworzonej paczki

### ISSUE THREAD

**Issue by krzwaw83** [allegro/allegro-api#6277]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**
Tworzę nową paczkę poprzez PUT https://api.allegro.pl/parcel-management/parcel-create-commands/a1bda6af-d2b5-4f5c-8b09-e27d3a94ac4a i w odpowiedzi dostaję 201 ze zwrotką z powtórzonym body requestu.

Wywołanie GET dla https://api.allegro.pl/parcel-management/parcel-create-commands/a1bda6af-d2b5-4f5c-8b09-e27d3a94ac4a zwraca
{
    "id": "a1bda6af-d2b5-4f5c-8b09-e27d3a94ac4a",
    "parcelId": null,
    "status": "ERROR",
    "errors": [
        {
            "code": "ERROR",
            "message": "Communication error with carrier's API occurred",
            "details": null,
            "path": "/parcel-management/parcel-create-commands/{commandId}",
            "userMessage": "Wystąpił błąd komunikacji z API przewoźnika"
        }
    ]
}

Pozdrawiam

**Comment by MaciejFrackowiak** [comment]
Operator zwrócił komunikat - "Niepoprawny urząd nadania".

**Comment by krzwaw83** [comment]
@MaciejFrackowiak Dziękuję za wskazówkę, okazało się że klient ma to sprecyzowane w swojej umowie i dodanie tego parametru rozwiązało problem. Natomiast jest jeszcze inna kwestia:
Puszczenie GETa na /parcel-management/delivery-services i przefiltrowanie po "Allegro Poczta" zwraca dostępne serwisy z opcjami gdzie interesują mnie usługi pocztexu 
- Allegro Kurier Pocztex
- Automat Pocztex
- Odbiór w Punkcie Pocztex

Dostaję tylko 
object(stdClass)#1336 (2) {
        ["name"]=>
        string(7) "pocztex"
        ["description"]=>
        string(7) "Pocztex"
      }
      
Czy aby nadać do Automat Pocztex należy w strukturze receiver uzupełnić pointId o identyfikator takiego automatu ?

**Comment by MaciejFrackowiak** [comment]
Tak, id punktu znajdziesz w szczegółach zamówienia lub pobierzesz bezpośrednio z serwisu firmy kurierskiej.
