### ISSUE TITLE
Pobieranie danych o akcjach ze sklepu

### ISSUE THREAD

**Issue by Zapotoczny** [allegro/allegro-api#6278]
Witam,
czy jest możliwość pobrania przy pomocy API informacji o aukcjach danego sklepu?
Np. Podaje adres sklepu https://allegro.pl/uzytkownik/nazwa-sklepu i mogę wygenerować raport o produktach

**Comment by MaciejFrackowiak** [comment]
Tak, taką możliwość daje zasób [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) - dostęp do niego posiadają tylko [zweryfikowane aplikacje](https://github.com/allegro/allegro-api/issues/4213).
