### ISSUE TITLE
public offers 

### ISSUE THREAD

**Issue by Serp4** [allegro/allegro-api#6279]
Dlaczego dotyczące public offers 
https://developer.allegro.pl/documentation#tag/Public-offer-information

Dlaczego **stock** posiadają informacje o liczbie dostępnych produktach, a już o ilość sprzedanych nie.
Przeglądając przez przeglądarkę danego sprzedawce posiadamy tą informacje i jest dostępna publicznie.

**Comment by MaciejFrackowiak** [comment]
Od 1 czerwca 2021 zwracamy tylko informacje w przedziałach liczbowych zgodnie z [komunikatem](https://github.com/allegro/allegro-api/issues/4566).
